Asterisk - The Open Source Telephony Project: lpcdec.c File Reference
lpcdec.c File Reference
#include "f2c.h"
Macros
#define contrl_1 contrl_
Functions
int initlpcdec_ (void)
int lpc10_decode (integer *bits, real *speech, struct lpc10_decoder_state *st)
int lpcdec_ (integer *bits, real *speech)
Variables
static integer c__10 = 10
struct {
logical corrp
integer lframe
integer order
} contrl_
Macro Definition Documentation
contrl_1
#define contrl_1 contrl_
Definition at line 58 of file lpcdec.c.
Function Documentation
initlpcdec_()
int initlpcdec_ (void)
lpc10_decode()
int lpc10_decode (integer * bits, real * speech, struct lpc10_decoder_state * st)
Definition at line 113 of file lpcdec.c.
References c__10, chanrd_(), decode_(), len(), and synths_().
Referenced by lpc10tolin_framein().
 {
     integer irms, voice[2], pitch, ipitv;
     extern /* Subroutine */ int decode_(integer *, integer *, integer *,
        integer *, integer *, real *, real *, struct lpc10_decoder_state *);
     real rc[10];
     extern /* Subroutine */ int chanrd_(integer *, integer *, integer *,
        integer *, integer *), synths_(integer *,
        integer *, real *, real *, real *, integer *,
                   struct lpc10_decoder_state *);
     integer irc[10], len;
     real rms;
 /* $Log$
  * Revision 1.15  2004/06/26 03:50:14  markster
  * Merge source cleanups (bug #1911)
  *
  * Revision 1.14  2003/02/12 13:59:15  matteo
  * mer feb 12 14:56:57 CET 2003
  *
  * Revision 1.1.1.1  2003/02/12 13:59:15  matteo
  * mer feb 12 14:56:57 CET 2003
  *
  * Revision 1.2  2000/01/05 08:20:39  markster
  * Some OSS fixes and a few lpc changes to make it actually work
  *
  * Revision 1.2  1996/08/20  20:30:11  jaf
  * Removed all static local variables that were SAVE'd in the Fortran
  * code, and put them in struct lpc10_encoder_state that is passed as an
  * argument.
  *
  * Removed init function, since all initialization is now done in
  * init_lpc10_encoder_state().
  *
  * Changed name of function from lpcenc_ to lpc10_encode, simply to make
  * all lpc10 functions have more consistent naming with each other.
  *
  * Revision 1.1  1996/08/19  22:31:48  jaf
  * Initial revision
  * */
 /* Revision 1.3  1996/03/29  22:03:47  jaf */
 /* Removed definitions for any constants that were no longer used. */
 /* Revision 1.2  1996/03/26  19:34:33  jaf */
 /* Added comments indicating which constants are not needed in an */
 /* application that uses the LPC-10 coder. */
 /* Revision 1.1  1996/02/07  14:43:51  jaf */
 /* Initial revision */
 /*   LPC Configuration parameters: */
 /* Frame size, Prediction order, Pitch period */
 /*       Arguments */
 /* $Log$
  * Revision 1.15  2004/06/26 03:50:14  markster
  * Merge source cleanups (bug #1911)
  *
  * Revision 1.14  2003/02/12 13:59:15  matteo
  * mer feb 12 14:56:57 CET 2003
  *
  * Revision 1.1.1.1  2003/02/12 13:59:15  matteo
  * mer feb 12 14:56:57 CET 2003
  *
  * Revision 1.2  2000/01/05 08:20:39  markster
  * Some OSS fixes and a few lpc changes to make it actually work
  *
  * Revision 1.2  1996/08/20  20:30:11  jaf
  * Removed all static local variables that were SAVE'd in the Fortran
  * code, and put them in struct lpc10_encoder_state that is passed as an
  * argument.
  *
  * Removed init function, since all initialization is now done in
  * init_lpc10_encoder_state().
  *
  * Changed name of function from lpcenc_ to lpc10_encode, simply to make
  * all lpc10 functions have more consistent naming with each other.
  *
  * Revision 1.1  1996/08/19  22:31:48  jaf
  * Initial revision
  * */
 /* Revision 1.3  1996/03/29  22:05:55  jaf */
 /* Commented out the common block variables that are not needed by the */
 /* embedded version. */
 /* Revision 1.2  1996/03/26  19:34:50  jaf */
 /* Added comments indicating which constants are not needed in an */
 /* application that uses the LPC-10 coder. */
 /* Revision 1.1  1996/02/07  14:44:09  jaf */
 /* Initial revision */
 /*   LPC Processing control variables: */
 /* *** Read-only: initialized in setup */
 /*  Files for Speech, Parameter, and Bitstream Input & Output, */
 /*    and message and debug outputs. */
 /* Here are the only files which use these variables: */
 /* lpcsim.f setup.f trans.f error.f vqsetup.f */
 /* Many files which use fdebug are not listed, since it is only used in */
 /* those other files conditionally, to print trace statements. */
 /*    integer fsi, fso, fpi, fpo, fbi, fbo, pbin, fmsg, fdebug */
 /*  LPC order, Frame size, Quantization rate, Bits per frame, */
 /*    Error correction */
 /* Subroutine SETUP is the only place where order is assigned a value, */
 /* and that value is 10.  It could increase efficiency 1% or so to */
 /* declare order as a constant (i.e., a Fortran PARAMETER) instead of as
 */
 /* a variable in a COMMON block, since it is used in many places in the */
 /* core of the coding and decoding routines.  Actually, I take that back.
 */
 /* At least when compiling with f2c, the upper bound of DO loops is */
 /* stored in a local variable before the DO loop begins, and then that is
 */
 /* compared against on each iteration. */
 /* Similarly for lframe, which is given a value of MAXFRM in SETUP. */
 /* Similarly for quant, which is given a value of 2400 in SETUP.  quant */
 /* is used in only a few places, and never in the core coding and */
 /* decoding routines, so it could be eliminated entirely. */
 /* nbits is similar to quant, and is given a value of 54 in SETUP. */
 /* corrp is given a value of .TRUE. in SETUP, and is only used in the */
 /* subroutines ENCODE and DECODE.  It doesn't affect the speed of the */
 /* coder significantly whether it is .TRUE. or .FALSE., or whether it is
 */
 /* a constant or a variable, since it is only examined once per frame. */
 /* Leaving it as a variable that is set to .TRUE.  seems like a good */
 /* idea, since it does enable some error-correction capability for */
 /* unvoiced frames, with no change in the coding rate, and no noticeable
 */
 /* quality difference in the decoded speech. */
 /*    integer quant, nbits */
 /* *** Read/write: variables for debugging, not needed for LPC algorithm
 */
 /*  Current frame, Unstable frames, Output clip count, Max onset buffer,
 */
 /*    Debug listing detail level, Line count on listing page */
 /* nframe is not needed for an embedded LPC10 at all. */
 /* nunsfm is initialized to 0 in SETUP, and incremented in subroutine */
 /* ERROR, which is only called from RCCHK.  When LPC10 is embedded into */
 /* an application, I would recommend removing the call to ERROR in RCCHK,
 */
 /* and remove ERROR and nunsfm completely. */
 /* iclip is initialized to 0 in SETUP, and incremented in entry SWRITE in
 */
 /* sread.f.  When LPC10 is embedded into an application, one might want */
 /* to cause it to be incremented in a routine that takes the output of */
 /* SYNTHS and sends it to an audio device.  It could be optionally */
 /* displayed, for those that might want to know what it is. */
 /* maxosp is never initialized to 0 in SETUP, although it probably should
 */
 /* be, and it is updated in subroutine ANALYS.  I doubt that its value */
 /* would be of much interest to an application in which LPC10 is */
 /* embedded. */
 /* listl and lincnt are not needed for an embedded LPC10 at all. */
 /*    integer nframe, nunsfm, iclip, maxosp, listl, lincnt */
 /*    common /contrl/ fsi, fso, fpi, fpo, fbi, fbo, pbin, fmsg, fdebug */
 /*    common /contrl/ quant, nbits */
 /*    common /contrl/ nframe, nunsfm, iclip, maxosp, listl, lincnt */
 /*       Local variables that need not be saved */
 /*       Uncoded speech parameters */
 /*       Coded speech parameters */
 /*       Others */
 /*       Local state */
 /*       None */
     /* Parameter adjustments */
     if (bits) {
    --bits;
    }
     if (speech) {
    --speech;
    }
     /* Function Body */
     chanrd_(&c__10, &ipitv, &irms, irc, &bits[1]);
     decode_(&ipitv, &irms, irc, voice, &pitch, &rms, rc, st);
     synths_(voice, &pitch, &rms, rc, &speech[1], &len, st);
     return 0;
 } /* lpcdec_ */
lpcdec_()
int lpcdec_ (integer * bits, real * speech)
Variable Documentation
c__10
integer c__10 = 10 static
Definition at line 62 of file lpcdec.c.
Referenced by lpc10_decode().
contrl_
struct { ... } contrl_
corrp
logical corrp
Definition at line 55 of file lpcdec.c.
lframe
integer lframe
Definition at line 54 of file lpcdec.c.
order
integer order
Definition at line 54 of file lpcdec.c.