Asterisk - The Open Source Telephony Project: test_voicemail_api.c File Reference
test_voicemail_api.c File Reference
Skeleton Test.
#include "asterisk.h"
#include <sys/stat.h>
#include "asterisk/utils.h"
#include "asterisk/module.h"
#include "asterisk/test.h"
#include "asterisk/paths.h"
#include "asterisk/channel.h"
#include "asterisk/app.h"
#include "asterisk/format_cache.h"
Macros
#define TOTAL_SNAPSHOTS 4
#define VM_API_FORWARD_MESSAGE(from_mailbox, from_context, from_folder, to_mailbox, to_context, to_folder, number_of_messages, message_numbers_in, delete_old)
#define VM_API_FORWARD_MESSAGE_OFF_NOMINAL(from_mailbox, from_context, from_folder, to_mailbox, to_context, to_folder, number_of_messages, message_numbers_in, delete_old)
#define VM_API_INT_VERIFY(expected, actual)
#define VM_API_MOVE_MESSAGE(mailbox, context, number_of_messages, source, message_numbers_in, dest)
#define VM_API_MOVE_MESSAGE_OFF_NOMINAL(mailbox, context, number_of_messages, source, message_numbers_in, dest)
#define VM_API_PLAYBACK_MESSAGE(channel, mailbox, context, folder, message, callback_fn)
#define VM_API_PLAYBACK_MESSAGE_OFF_NOMINAL(channel, mailbox, context, folder, message, callback_fn)
#define VM_API_REMOVE_MESSAGE(mailbox, context, number_of_messages, folder, message_numbers_in)
#define VM_API_REMOVE_MESSAGE_OFF_NOMINAL(mailbox, context, number_of_messages, folder, message_numbers_in)
#define VM_API_SNAPSHOT_CREATE(mailbox, context, folder, desc, sort, old_and_inbox)
#define VM_API_SNAPSHOT_MSG_VERIFY(expected, actual, expected_folder, expected_index)
#define VM_API_SNAPSHOT_OFF_NOMINAL_TEST(mailbox, context, folder, desc, sort, old_and_inbox)
#define VM_API_SNAPSHOT_TEST_CLEANUP
#define VM_API_STRING_FIELD_VERIFY(expected, actual)
#define VM_API_TEST_CLEANUP test_vm_api_test_teardown()
#define VM_API_TEST_SETUP
#define VOICEMAIL_DIR_MODE 0777
#define VOICEMAIL_FILE_MODE 0666
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
AST_TEST_DEFINE (voicemail_api_nominal_snapshot)
AST_TEST_DEFINE (voicemail_api_off_nominal_snapshot)
AST_TEST_DEFINE (voicemail_api_nominal_move)
AST_TEST_DEFINE (voicemail_api_off_nominal_move)
AST_TEST_DEFINE (voicemail_api_nominal_remove)
AST_TEST_DEFINE (voicemail_api_off_nominal_remove)
AST_TEST_DEFINE (voicemail_api_nominal_forward)
AST_TEST_DEFINE (voicemail_api_off_nominal_forward)
AST_TEST_DEFINE (voicemail_api_nominal_msg_playback)
AST_TEST_DEFINE (voicemail_api_off_nominal_msg_playback)
static int get_folder_by_name (const char *folder)
static int load_module (void)
static void message_playback_callback_fn (struct ast_channel *chan, const char *file, int duration)
static struct ast_channel * test_vm_api_create_mock_channel (void)
static struct ast_vm_msg_snapshot * test_vm_api_create_mock_snapshot (const char *context, const char *exten, const char *callerid)
static int test_vm_api_create_voicemail_files (const char *context, const char *mailbox, struct ast_vm_msg_snapshot *snapshot)
static int test_vm_api_create_voicemail_folder (const char *folder_path)
static void test_vm_api_destroy_mailbox_voicemails (const char *mailbox, struct ast_vm_mailbox_snapshot *mailbox_snapshot)
static void test_vm_api_destroy_mock_snapshot (struct ast_vm_msg_snapshot *snapshot)
static struct ast_frame * test_vm_api_mock_channel_read (struct ast_channel *chan)
static int test_vm_api_mock_channel_write (struct ast_channel *chan, struct ast_frame *frame)
static void test_vm_api_remove_all_messages (void)
static void test_vm_api_remove_voicemail (struct ast_vm_msg_snapshot *snapshot)
static int test_vm_api_test_setup (void)
static void test_vm_api_test_teardown (void)
static void test_vm_api_update_test_snapshots (struct ast_vm_mailbox_snapshot *mailbox_snapshot)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Core Voicemail API Tests" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, }
static const struct ast_module_info * ast_module_info = &__mod_info
static int global_entered_playback_callback = 0
static const char *const mailbox_folders []
static const struct ast_channel_tech mock_channel_tech
static struct ast_vm_msg_snapshot * test_snapshots [TOTAL_SNAPSHOTS]
Detailed Description
Skeleton Test.
Author
Matt Jordan <mjordan@digium.com>
Tests for the publicly exposed Voicemail API
Definition in file test_voicemail_api.c.
Macro Definition Documentation
TOTAL_SNAPSHOTS
#define TOTAL_SNAPSHOTS 4
Definition at line 66 of file test_voicemail_api.c.
Referenced by test_vm_api_test_setup(), test_vm_api_test_teardown(), and test_vm_api_update_test_snapshots().
VM_API_FORWARD_MESSAGE
#define VM_API_FORWARD_MESSAGE (from_mailbox, from_context, from_folder, to_mailbox, to_context, to_folder, number_of_messages, message_numbers_in, delete_old)
Definition at line 263 of file test_voicemail_api.c.
Referenced by AST_TEST_DEFINE().
VM_API_FORWARD_MESSAGE_OFF_NOMINAL
#define VM_API_FORWARD_MESSAGE_OFF_NOMINAL (from_mailbox, from_context, from_folder, to_mailbox, to_context, to_folder, number_of_messages, message_numbers_in, delete_old)
Definition at line 276 of file test_voicemail_api.c.
Referenced by AST_TEST_DEFINE().
VM_API_INT_VERIFY
#define VM_API_INT_VERIFY (expected, actual)
Definition at line 129 of file test_voicemail_api.c.
Referenced by AST_TEST_DEFINE().
VM_API_MOVE_MESSAGE
#define VM_API_MOVE_MESSAGE (mailbox, context, number_of_messages, source, message_numbers_in, dest)
Definition at line 211 of file test_voicemail_api.c.
Referenced by AST_TEST_DEFINE().
VM_API_MOVE_MESSAGE_OFF_NOMINAL
#define VM_API_MOVE_MESSAGE_OFF_NOMINAL (mailbox, context, number_of_messages, source, message_numbers_in, dest)
Definition at line 223 of file test_voicemail_api.c.
Referenced by AST_TEST_DEFINE().
VM_API_PLAYBACK_MESSAGE
#define VM_API_PLAYBACK_MESSAGE (channel, mailbox, context, folder, message, callback_fn)
Definition at line 292 of file test_voicemail_api.c.
Referenced by AST_TEST_DEFINE().
VM_API_PLAYBACK_MESSAGE_OFF_NOMINAL
#define VM_API_PLAYBACK_MESSAGE_OFF_NOMINAL (channel, mailbox, context, folder, message, callback_fn)
Definition at line 307 of file test_voicemail_api.c.
Referenced by AST_TEST_DEFINE().
VM_API_REMOVE_MESSAGE
#define VM_API_REMOVE_MESSAGE (mailbox, context, number_of_messages, folder, message_numbers_in)
Definition at line 235 of file test_voicemail_api.c.
Referenced by AST_TEST_DEFINE().
VM_API_REMOVE_MESSAGE_OFF_NOMINAL
#define VM_API_REMOVE_MESSAGE_OFF_NOMINAL (mailbox, context, number_of_messages, folder, message_numbers_in)
Definition at line 251 of file test_voicemail_api.c.
Referenced by AST_TEST_DEFINE().
VM_API_SNAPSHOT_CREATE
#define VM_API_SNAPSHOT_CREATE (mailbox, context, folder, desc, sort, old_and_inbox)
Definition at line 183 of file test_voicemail_api.c.
Referenced by AST_TEST_DEFINE().
VM_API_SNAPSHOT_MSG_VERIFY
#define VM_API_SNAPSHOT_MSG_VERIFY (expected, actual, expected_folder, expected_index)
Definition at line 143 of file test_voicemail_api.c.
Referenced by AST_TEST_DEFINE().
VM_API_SNAPSHOT_OFF_NOMINAL_TEST
#define VM_API_SNAPSHOT_OFF_NOMINAL_TEST (mailbox, context, folder, desc, sort, old_and_inbox)
Definition at line 198 of file test_voicemail_api.c.
Referenced by AST_TEST_DEFINE().
VM_API_SNAPSHOT_TEST_CLEANUP
#define VM_API_SNAPSHOT_TEST_CLEANUP
Value:
if (test_mbox_snapshot) { \
         test_mbox_snapshot = ast_vm_mailbox_snapshot_destroy(test_mbox_snapshot); \
      } \
      VM_API_TEST_CLEANUP; \
Definition at line 103 of file test_voicemail_api.c.
VM_API_STRING_FIELD_VERIFY
#define VM_API_STRING_FIELD_VERIFY (expected, actual)
Definition at line 116 of file test_voicemail_api.c.
Referenced by AST_TEST_DEFINE().
VM_API_TEST_CLEANUP
#define VM_API_TEST_CLEANUP test_vm_api_test_teardown()
Definition at line 95 of file test_voicemail_api.c.
Referenced by AST_TEST_DEFINE().
VM_API_TEST_SETUP
#define VM_API_TEST_SETUP
Definition at line 73 of file test_voicemail_api.c.
Referenced by AST_TEST_DEFINE().
VOICEMAIL_DIR_MODE
#define VOICEMAIL_DIR_MODE 0777
Definition at line 52 of file test_voicemail_api.c.
Referenced by test_vm_api_create_voicemail_folder().
VOICEMAIL_FILE_MODE
#define VOICEMAIL_FILE_MODE 0666
Definition at line 60 of file test_voicemail_api.c.
Referenced by test_vm_api_create_voicemail_files().
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 1579 of file test_voicemail_api.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 1579 of file test_voicemail_api.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 1579 of file test_voicemail_api.c.
AST_TEST_DEFINE() [1/10]
AST_TEST_DEFINE (voicemail_api_nominal_snapshot)
Definition at line 840 of file test_voicemail_api.c.
References AST_TEST_NOT_RUN, AST_TEST_PASS, ast_test_status_update, ast_vm_mailbox_snapshot_destroy(), AST_VM_SNAPSHOT_SORT_BY_ID, AST_VM_SNAPSHOT_SORT_BY_TIME, sip_to_pjsip::info(), NULL, TEST_EXECUTE, TEST_INIT, ast_vm_mailbox_snapshot::total_msg_num, VM_API_INT_VERIFY, VM_API_SNAPSHOT_CREATE, VM_API_SNAPSHOT_MSG_VERIFY, VM_API_TEST_CLEANUP, and VM_API_TEST_SETUP.
 {
    struct ast_vm_mailbox_snapshot *test_mbox_snapshot = NULL;
    switch (cmd) {
    case TEST_INIT:
       info->name = "nominal_snapshot";
       info->category = "/main/voicemail_api/";
       info->summary = "Nominal mailbox snapshot tests";
       info->description =
          "Test retrieving mailbox snapshots";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    VM_API_TEST_SETUP;
    ast_test_status_update(test, "Test retrieving message 1 from INBOX of test_vm_1234\n");
    VM_API_SNAPSHOT_CREATE("test_vm_api_1234", "default", "INBOX", 0, AST_VM_SNAPSHOT_SORT_BY_TIME, 0);
    VM_API_INT_VERIFY(1, test_mbox_snapshot->total_msg_num);
    VM_API_SNAPSHOT_MSG_VERIFY(test_snapshots[1], test_mbox_snapshot, "INBOX", 0);
    ast_vm_mailbox_snapshot_destroy(test_mbox_snapshot);
    ast_test_status_update(test, "Test retrieving message 0 from Old of test_vm_1234\n");
    VM_API_SNAPSHOT_CREATE("test_vm_api_1234", "default", "Old", 0, AST_VM_SNAPSHOT_SORT_BY_TIME, 0);
    VM_API_INT_VERIFY(1, test_mbox_snapshot->total_msg_num);
    VM_API_SNAPSHOT_MSG_VERIFY(test_snapshots[0], test_mbox_snapshot, "Old", 0);
    ast_vm_mailbox_snapshot_destroy(test_mbox_snapshot);
    ast_test_status_update(test, "Test retrieving message 0, 1 from Old and INBOX of test_vm_1234 ordered by time\n");
    VM_API_SNAPSHOT_CREATE("test_vm_api_1234", "default", "INBOX", 0, AST_VM_SNAPSHOT_SORT_BY_TIME, 1);
    VM_API_INT_VERIFY(2, test_mbox_snapshot->total_msg_num);
    VM_API_SNAPSHOT_MSG_VERIFY(test_snapshots[0], test_mbox_snapshot, "INBOX", 0);
    VM_API_SNAPSHOT_MSG_VERIFY(test_snapshots[1], test_mbox_snapshot, "INBOX", 1);
    ast_vm_mailbox_snapshot_destroy(test_mbox_snapshot);
    ast_test_status_update(test, "Test retrieving message 1, 0 from Old and INBOX of test_vm_1234 ordered by time desc\n");
    VM_API_SNAPSHOT_CREATE("test_vm_api_1234", "default", "INBOX", 1, AST_VM_SNAPSHOT_SORT_BY_TIME, 1);
    VM_API_INT_VERIFY(2, test_mbox_snapshot->total_msg_num);
    VM_API_SNAPSHOT_MSG_VERIFY(test_snapshots[1], test_mbox_snapshot, "INBOX", 0);
    VM_API_SNAPSHOT_MSG_VERIFY(test_snapshots[0], test_mbox_snapshot, "INBOX", 1);
    ast_vm_mailbox_snapshot_destroy(test_mbox_snapshot);
    ast_test_status_update(test, "Test retrieving message 0, 1 from Old and INBOX of test_vm_1234 ordered by id\n");
    VM_API_SNAPSHOT_CREATE("test_vm_api_1234", "default", "INBOX", 0, AST_VM_SNAPSHOT_SORT_BY_ID, 1);
    VM_API_INT_VERIFY(2, test_mbox_snapshot->total_msg_num);
    VM_API_SNAPSHOT_MSG_VERIFY(test_snapshots[1], test_mbox_snapshot, "INBOX", 0);
    VM_API_SNAPSHOT_MSG_VERIFY(test_snapshots[0], test_mbox_snapshot, "INBOX", 1);
    ast_vm_mailbox_snapshot_destroy(test_mbox_snapshot);
    ast_test_status_update(test, "Test retrieving message 1, 0 from Old and INBOX of test_vm_1234 ordered by id desc\n");
    VM_API_SNAPSHOT_CREATE("test_vm_api_1234", "default", "INBOX", 1, AST_VM_SNAPSHOT_SORT_BY_ID, 1);
    VM_API_INT_VERIFY(2, test_mbox_snapshot->total_msg_num);
    VM_API_SNAPSHOT_MSG_VERIFY(test_snapshots[0], test_mbox_snapshot, "INBOX", 0);
    VM_API_SNAPSHOT_MSG_VERIFY(test_snapshots[1], test_mbox_snapshot, "INBOX", 1);
    ast_vm_mailbox_snapshot_destroy(test_mbox_snapshot);
    ast_test_status_update(test, "Test retrieving message 0, 1 from all folders of test_vm_1234 ordered by id\n");
    VM_API_SNAPSHOT_CREATE("test_vm_api_1234", "default", NULL, 0, AST_VM_SNAPSHOT_SORT_BY_ID, 0);
    VM_API_INT_VERIFY(2, test_mbox_snapshot->total_msg_num);
    VM_API_SNAPSHOT_MSG_VERIFY(test_snapshots[0], test_mbox_snapshot, "Old", 0);
    VM_API_SNAPSHOT_MSG_VERIFY(test_snapshots[1], test_mbox_snapshot, "INBOX", 0);
    ast_vm_mailbox_snapshot_destroy(test_mbox_snapshot);
    ast_test_status_update(test, "Test retrieving message 0, 1 from all folders of test_vm_1234 ordered by time\n");
    VM_API_SNAPSHOT_CREATE("test_vm_api_1234", "default", NULL, 0, AST_VM_SNAPSHOT_SORT_BY_TIME, 0);
    VM_API_INT_VERIFY(2, test_mbox_snapshot->total_msg_num);
    VM_API_SNAPSHOT_MSG_VERIFY(test_snapshots[0], test_mbox_snapshot, "Old", 0);
    VM_API_SNAPSHOT_MSG_VERIFY(test_snapshots[1], test_mbox_snapshot, "INBOX", 0);
    ast_vm_mailbox_snapshot_destroy(test_mbox_snapshot);
    ast_test_status_update(test, "Test retrieving message 0, 1 from all folders of test_vm_1234, default context ordered by time\n");
    VM_API_SNAPSHOT_CREATE("test_vm_api_1234", NULL, NULL, 0, AST_VM_SNAPSHOT_SORT_BY_TIME, 0);
    VM_API_INT_VERIFY(2, test_mbox_snapshot->total_msg_num);
    VM_API_SNAPSHOT_MSG_VERIFY(test_snapshots[0], test_mbox_snapshot, "Old", 0);
    VM_API_SNAPSHOT_MSG_VERIFY(test_snapshots[1], test_mbox_snapshot, "INBOX", 0);
    ast_vm_mailbox_snapshot_destroy(test_mbox_snapshot);
    VM_API_TEST_CLEANUP;
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [2/10]
AST_TEST_DEFINE (voicemail_api_off_nominal_snapshot)
Definition at line 924 of file test_voicemail_api.c.
References AST_TEST_NOT_RUN, AST_TEST_PASS, ast_test_status_update, AST_VM_SNAPSHOT_SORT_BY_TIME, sip_to_pjsip::info(), NULL, TEST_EXECUTE, TEST_INIT, VM_API_SNAPSHOT_OFF_NOMINAL_TEST, VM_API_TEST_CLEANUP, and VM_API_TEST_SETUP.
 {
    struct ast_vm_mailbox_snapshot *test_mbox_snapshot = NULL;
    switch (cmd) {
    case TEST_INIT:
       info->name = "off_nominal_snapshot";
       info->category = "/main/voicemail_api/";
       info->summary = "Off nominal mailbox snapshot tests";
       info->description =
          "Test off nominal requests for mailbox snapshots.  This includes"
          " testing the following:\n"
          " * Access to non-exisstent mailbox\n"
          " * Access to NULL mailbox\n"
          " * Access to non-existent context\n"
          " * Access to non-existent folder\n"
          " * Access to NULL folder\n"
          " * Invalid sort identifier";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    VM_API_TEST_SETUP;
    ast_test_status_update(test, "Test access to non-existent mailbox test_vm_api_3456\n");
    VM_API_SNAPSHOT_OFF_NOMINAL_TEST("test_vm_api_3456", "default", "INBOX", 0, AST_VM_SNAPSHOT_SORT_BY_TIME, 0);
    ast_test_status_update(test, "Test access to null mailbox\n");
    VM_API_SNAPSHOT_OFF_NOMINAL_TEST(NULL, "default", "INBOX", 0, AST_VM_SNAPSHOT_SORT_BY_TIME, 0);
    ast_test_status_update(test, "Test access non-existent context test_vm_api_defunct\n");
    VM_API_SNAPSHOT_OFF_NOMINAL_TEST("test_vm_api_1234", "test_vm_api_defunct", "INBOX", 0, AST_VM_SNAPSHOT_SORT_BY_TIME, 0);
    ast_test_status_update(test, "Test non-existent folder test_vm_api_platypus\n");
    VM_API_SNAPSHOT_OFF_NOMINAL_TEST("test_vm_api_1234", "default", "test_vm_api_platypus", 0, AST_VM_SNAPSHOT_SORT_BY_TIME, 0);
    VM_API_TEST_CLEANUP;
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [3/10]
AST_TEST_DEFINE (voicemail_api_nominal_move)
Definition at line 966 of file test_voicemail_api.c.
References AST_TEST_NOT_RUN, AST_TEST_PASS, ast_test_status_update, ast_vm_mailbox_snapshot_destroy(), AST_VM_SNAPSHOT_SORT_BY_TIME, sip_to_pjsip::info(), ast_vm_msg_snapshot::msg_id, NULL, TEST_EXECUTE, TEST_INIT, test_vm_api_update_test_snapshots(), VM_API_INT_VERIFY, VM_API_MOVE_MESSAGE, VM_API_SNAPSHOT_CREATE, VM_API_STRING_FIELD_VERIFY, VM_API_TEST_CLEANUP, and VM_API_TEST_SETUP.
 {
    struct ast_vm_mailbox_snapshot *test_mbox_snapshot = NULL;
    const char *inbox_msg_id;
    const char *old_msg_id;
    const char *multi_msg_ids[2];
    switch (cmd) {
    case TEST_INIT:
       info->name = "nominal_move";
       info->category = "/main/voicemail_api/";
       info->summary = "Nominal move voicemail tests";
       info->description =
          "Test nominal requests to move a voicemail to a different"
          " folder.  This includes moving messages given a context,"
          " given a NULL context, and moving multiple messages";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    VM_API_TEST_SETUP;
    old_msg_id = test_snapshots[0]->msg_id;
    inbox_msg_id = test_snapshots[1]->msg_id;
    multi_msg_ids[0] = test_snapshots[2]->msg_id;
    multi_msg_ids[1] = test_snapshots[3]->msg_id;
    ast_test_status_update(test, "Test move of test_vm_api_1234 message from INBOX to Family\n");
    VM_API_MOVE_MESSAGE("test_vm_api_1234", "default", 1, "INBOX", &inbox_msg_id, "Family");
    ast_test_status_update(test, "Test move of test_vm_api_1234 message from Old to Family\n");
    VM_API_MOVE_MESSAGE("test_vm_api_1234", NULL, 1, "Old", &old_msg_id, "Family");
    /* Take a snapshot and update the test snapshots for verification */
    VM_API_SNAPSHOT_CREATE("test_vm_api_1234", "default", "Family", 0, AST_VM_SNAPSHOT_SORT_BY_TIME, 0);
    test_vm_api_update_test_snapshots(test_mbox_snapshot);
    test_mbox_snapshot = ast_vm_mailbox_snapshot_destroy(test_mbox_snapshot);
    VM_API_STRING_FIELD_VERIFY("Family", test_snapshots[0]->folder_name);
    VM_API_STRING_FIELD_VERIFY("Family", test_snapshots[1]->folder_name);
    VM_API_INT_VERIFY(0, test_snapshots[1]->msg_number);
    VM_API_INT_VERIFY(1, test_snapshots[0]->msg_number);
    /* Move both of the 2345 messages to Family */
    ast_test_status_update(test, "Test move of test_vm_api_2345 messages from Inbox to Family\n");
    VM_API_MOVE_MESSAGE("test_vm_api_2345", "default", 2, "INBOX", multi_msg_ids, "Family");
    /* Take a snapshot and update the test snapshots for verification */
    VM_API_SNAPSHOT_CREATE("test_vm_api_2345", "default", "Family", 0, AST_VM_SNAPSHOT_SORT_BY_TIME, 0);
    test_vm_api_update_test_snapshots(test_mbox_snapshot);
    test_mbox_snapshot = ast_vm_mailbox_snapshot_destroy(test_mbox_snapshot);
    VM_API_STRING_FIELD_VERIFY("Family", test_snapshots[2]->folder_name);
    VM_API_STRING_FIELD_VERIFY("Family", test_snapshots[3]->folder_name);
    ast_test_status_update(test, "Test move of test_vm_api_2345 message from Family to INBOX\n");
    VM_API_MOVE_MESSAGE("test_vm_api_2345", "default", 2, "Family", multi_msg_ids, "INBOX");
    VM_API_SNAPSHOT_CREATE("test_vm_api_2345", "default", "INBOX", 0, AST_VM_SNAPSHOT_SORT_BY_TIME, 0);
    test_vm_api_update_test_snapshots(test_mbox_snapshot);
    test_mbox_snapshot = ast_vm_mailbox_snapshot_destroy(test_mbox_snapshot);
    VM_API_STRING_FIELD_VERIFY("INBOX", test_snapshots[2]->folder_name);
    VM_API_STRING_FIELD_VERIFY("INBOX", test_snapshots[3]->folder_name);
    VM_API_TEST_CLEANUP;
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [4/10]
AST_TEST_DEFINE (voicemail_api_off_nominal_move)
Definition at line 1037 of file test_voicemail_api.c.
References AST_TEST_NOT_RUN, AST_TEST_PASS, ast_test_status_update, sip_to_pjsip::info(), ast_vm_msg_snapshot::msg_id, NULL, TEST_EXECUTE, TEST_INIT, VM_API_MOVE_MESSAGE_OFF_NOMINAL, VM_API_TEST_CLEANUP, and VM_API_TEST_SETUP.
 {
    const char *inbox_msg_id;
    const char *multi_msg_ids[4];
    switch (cmd) {
    case TEST_INIT:
       info->name = "off_nominal_move";
       info->category = "/main/voicemail_api/";
       info->summary = "Off nominal mailbox message move tests";
       info->description =
          "Test nominal requests to move a voicemail to a different"
          " folder.  This includes testing the following:\n"
          " * Moving to a non-existent mailbox\n"
          " * Moving to a NULL mailbox\n"
          " * Moving to a non-existent context\n"
          " * Moving to/from non-existent folder\n"
          " * Moving to/from NULL folder\n"
          " * Invalid message identifier(s)";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    VM_API_TEST_SETUP;
    inbox_msg_id = test_snapshots[1]->msg_id;
    multi_msg_ids[0] = test_snapshots[0]->msg_id;
    multi_msg_ids[1] = test_snapshots[1]->msg_id;
    multi_msg_ids[2] = test_snapshots[2]->msg_id;
    multi_msg_ids[3] = test_snapshots[3]->msg_id;
    ast_test_status_update(test, "Test move attempt for invalid mailbox test_vm_3456\n");
    VM_API_MOVE_MESSAGE_OFF_NOMINAL("test_vm_api_3456", "default", 1, "INBOX", &inbox_msg_id, "Family");
    VM_API_MOVE_MESSAGE_OFF_NOMINAL(NULL, "default", 1, "INBOX", &inbox_msg_id, "Family");
    ast_test_status_update(test, "Test move attempt for invalid context test_vm_api_defunct\n");
    VM_API_MOVE_MESSAGE_OFF_NOMINAL("test_vm_api_1234", "test_vm_api_defunct", 1, "INBOX", &inbox_msg_id, "Family");
    ast_test_status_update(test, "Test move attempt to invalid folder\n");
    VM_API_MOVE_MESSAGE_OFF_NOMINAL("test_vm_api_1234", "default", 1, "INBOX", &inbox_msg_id, "SPAMALOT");
    ast_test_status_update(test, "Test move attempt from invalid folder\n");
    VM_API_MOVE_MESSAGE_OFF_NOMINAL("test_vm_api_1234", "default", 1, "MEATINACAN", &inbox_msg_id, "Family");
    ast_test_status_update(test, "Test move attempt to NULL folder\n");
    VM_API_MOVE_MESSAGE_OFF_NOMINAL("test_vm_api_1234", "default", 1, "INBOX", &inbox_msg_id, NULL);
    ast_test_status_update(test, "Test move attempt from NULL folder\n");
    VM_API_MOVE_MESSAGE_OFF_NOMINAL("test_vm_api_1234", "default", 1, NULL, &inbox_msg_id, "Family");
    ast_test_status_update(test, "Test move attempt with non-existent message number\n");
    inbox_msg_id = "6";
    VM_API_MOVE_MESSAGE_OFF_NOMINAL("test_vm_api_1234", "default", 1, "INBOX", &inbox_msg_id, "Family");
    ast_test_status_update(test, "Test move attempt with invalid message number\n");
    inbox_msg_id = "";
    VM_API_MOVE_MESSAGE_OFF_NOMINAL("test_vm_api_1234", "default", 1, "INBOX", &inbox_msg_id, "Family");
    ast_test_status_update(test, "Test move attempt with 0 number of messages\n");
    inbox_msg_id = test_snapshots[1]->msg_id;
    VM_API_MOVE_MESSAGE_OFF_NOMINAL("test_vm_api_1234", "default", 0, "INBOX", &inbox_msg_id, "Family");
    ast_test_status_update(test, "Test move attempt with invalid number of messages\n");
    VM_API_MOVE_MESSAGE_OFF_NOMINAL("test_vm_api_1234", "default", -30, "INBOX", &inbox_msg_id, "Family");
    ast_test_status_update(test, "Test move attempt with non-existent multiple messages, where some messages exist\n");
    VM_API_MOVE_MESSAGE_OFF_NOMINAL("test_vm_api_1234", "default", 4, "INBOX", multi_msg_ids, "Family");
    VM_API_TEST_CLEANUP;
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [5/10]
AST_TEST_DEFINE (voicemail_api_nominal_remove)
Definition at line 1113 of file test_voicemail_api.c.
References AST_TEST_NOT_RUN, AST_TEST_PASS, ast_test_status_update, sip_to_pjsip::info(), ast_vm_msg_snapshot::msg_id, NULL, TEST_EXECUTE, TEST_INIT, VM_API_REMOVE_MESSAGE, VM_API_TEST_CLEANUP, and VM_API_TEST_SETUP.
 {
    struct ast_vm_mailbox_snapshot *test_mbox_snapshot = NULL;
    const char *inbox_msg_id;
    const char *old_msg_id;
    const char *multi_msg_ids[2];
    switch (cmd) {
    case TEST_INIT:
       info->name = "nominal_remove";
       info->category = "/main/voicemail_api/";
       info->summary = "Nominal mailbox remove message tests";
       info->description =
          "Tests removing messages from voicemail folders.  Includes"
          " both removing messages one at a time, and in a set";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    VM_API_TEST_SETUP;
    old_msg_id = test_snapshots[0]->msg_id;
    inbox_msg_id = test_snapshots[1]->msg_id;
    multi_msg_ids[0] = test_snapshots[2]->msg_id;
    multi_msg_ids[1] = test_snapshots[3]->msg_id;
    ast_test_status_update(test, "Test removing a single message from INBOX\n");
    VM_API_REMOVE_MESSAGE("test_vm_api_1234", "default", 1, "INBOX", &inbox_msg_id);
    ast_test_status_update(test, "Test removing a single message from Old\n");
    VM_API_REMOVE_MESSAGE("test_vm_api_1234", "default", 1, "Old", &old_msg_id);
    ast_test_status_update(test, "Test removing multiple messages from INBOX\n");
    VM_API_REMOVE_MESSAGE("test_vm_api_2345", "default", 2, "INBOX", multi_msg_ids);
    VM_API_TEST_CLEANUP;
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [6/10]
AST_TEST_DEFINE (voicemail_api_off_nominal_remove)
Definition at line 1155 of file test_voicemail_api.c.
References AST_TEST_NOT_RUN, AST_TEST_PASS, ast_test_status_update, sip_to_pjsip::info(), ast_vm_msg_snapshot::msg_id, NULL, TEST_EXECUTE, TEST_INIT, VM_API_REMOVE_MESSAGE_OFF_NOMINAL, VM_API_TEST_CLEANUP, and VM_API_TEST_SETUP.
 {
    const char *inbox_msg_id;
    const char *multi_msg_ids[2];
    const char *empty_msg_ids[] = { };
    switch (cmd) {
    case TEST_INIT:
       info->name = "off_nominal_remove";
       info->category = "/main/voicemail_api/";
       info->summary = "Off nominal mailbox message removal tests";
       info->description =
          "Test off nominal requests for removing messages from "
          "a mailbox.  This includes:\n"
          " * Removing messages with an invalid mailbox\n"
          " * Removing messages from a NULL mailbox\n"
          " * Removing messages from an invalid context\n"
          " * Removing messages from an invalid folder\n"
          " * Removing messages from a NULL folder\n"
          " * Removing messages with bad identifiers";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    VM_API_TEST_SETUP;
    inbox_msg_id = test_snapshots[1]->msg_id;
    multi_msg_ids[0] = test_snapshots[2]->msg_id;
    multi_msg_ids[1] = test_snapshots[3]->msg_id;
    ast_test_status_update(test, "Test removing a single message with an invalid mailbox\n");
    VM_API_REMOVE_MESSAGE_OFF_NOMINAL("test_vm_api_3456", "default", 1, "INBOX", &inbox_msg_id);
    ast_test_status_update(test, "Test removing a single message with a NULL mailbox\n");
    VM_API_REMOVE_MESSAGE_OFF_NOMINAL(NULL, "default", 1, "INBOX", &inbox_msg_id);
    ast_test_status_update(test, "Test removing a single message with an invalid context\n");
    VM_API_REMOVE_MESSAGE_OFF_NOMINAL("test_vm_api_1234", "defunct", 1, "INBOX", &inbox_msg_id);
    ast_test_status_update(test, "Test removing a single message with an invalid folder\n");
    VM_API_REMOVE_MESSAGE_OFF_NOMINAL("test_vm_api_1234", "default", 1, "SPAMINACAN", &inbox_msg_id);
    ast_test_status_update(test, "Test removing a single message with a NULL folder\n");
    VM_API_REMOVE_MESSAGE_OFF_NOMINAL("test_vm_api_1234", "default", 1, NULL, &inbox_msg_id);
    ast_test_status_update(test, "Test removing a single message with an invalid message number\n");
    inbox_msg_id = "POOPOO";
    VM_API_REMOVE_MESSAGE_OFF_NOMINAL("test_vm_api_1234", "default", 1, "INBOX", &inbox_msg_id);
    ast_test_status_update(test, "Test removing multiple messages with a single invalid message number\n");
    multi_msg_ids[1] = "POOPOO";
    VM_API_REMOVE_MESSAGE_OFF_NOMINAL("test_vm_api_2345", "default", 2, "INBOX", multi_msg_ids);
    ast_test_status_update(test, "Test removing no messages with no message numbers\n");
    VM_API_REMOVE_MESSAGE_OFF_NOMINAL("test_vm_api_1234", "default", 0, "INBOX", empty_msg_ids);
    ast_test_status_update(test, "Test removing multiple messages with an invalid size specifier\n");
    VM_API_REMOVE_MESSAGE_OFF_NOMINAL("test_vm_api_2345", "default", -30, "INBOX", multi_msg_ids);
    VM_API_TEST_CLEANUP;
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [7/10]
AST_TEST_DEFINE (voicemail_api_nominal_forward)
Definition at line 1220 of file test_voicemail_api.c.
References AST_TEST_NOT_RUN, AST_TEST_PASS, ast_test_status_update, ast_vm_mailbox_snapshot_destroy(), AST_VM_SNAPSHOT_SORT_BY_TIME, sip_to_pjsip::info(), ast_vm_msg_snapshot::msg_id, NULL, TEST_EXECUTE, TEST_INIT, ast_vm_mailbox_snapshot::total_msg_num, VM_API_FORWARD_MESSAGE, VM_API_INT_VERIFY, VM_API_SNAPSHOT_CREATE, VM_API_TEST_CLEANUP, and VM_API_TEST_SETUP.
 {
    struct ast_vm_mailbox_snapshot *test_mbox_snapshot = NULL;
    const char *inbox_msg_id;
    const char *multi_msg_ids[2];
    switch (cmd) {
    case TEST_INIT:
       info->name = "nominal_forward";
       info->category = "/main/voicemail_api/";
       info->summary = "Nominal message forward tests";
       info->description =
          "Tests the nominal cases of forwarding messages"
          " between mailboxes";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    VM_API_TEST_SETUP;
    inbox_msg_id = test_snapshots[1]->msg_id;
    multi_msg_ids[0] = test_snapshots[2]->msg_id;
    multi_msg_ids[1] = test_snapshots[3]->msg_id;
    ast_test_status_update(test, "Test forwarding message 0 from test_vm_api_1234 INBOX to test_vm_api_2345 INBOX\n");
    VM_API_FORWARD_MESSAGE("test_vm_api_1234", "default", "INBOX", "test_vm_api_2345", "default", "INBOX", 1, &inbox_msg_id, 0);
    /* Make sure we didn't delete the message */
    VM_API_SNAPSHOT_CREATE("test_vm_api_1234", "default", "INBOX", 0, AST_VM_SNAPSHOT_SORT_BY_TIME, 0);
    VM_API_INT_VERIFY(1, test_mbox_snapshot->total_msg_num);
    test_mbox_snapshot = ast_vm_mailbox_snapshot_destroy(test_mbox_snapshot);
    /* We should now have a total of 3 messages in test_vm_api_2345 INBOX */
    VM_API_SNAPSHOT_CREATE("test_vm_api_2345", "default", "INBOX", 0, AST_VM_SNAPSHOT_SORT_BY_TIME, 0);
    VM_API_INT_VERIFY(3, test_mbox_snapshot->total_msg_num);
    test_mbox_snapshot = ast_vm_mailbox_snapshot_destroy(test_mbox_snapshot);
    ast_test_status_update(test, "Test forwarding message 0 from test_vm_api_1234 INBOX with default context to test_vm_api_2345 INBOX\n");
    VM_API_FORWARD_MESSAGE("test_vm_api_1234", NULL, "INBOX", "test_vm_api_2345", "default", "INBOX", 1, &inbox_msg_id, 0);
    /* Make sure we didn't delete the message */
    VM_API_SNAPSHOT_CREATE("test_vm_api_1234", "default", "INBOX", 0, AST_VM_SNAPSHOT_SORT_BY_TIME, 0);
    VM_API_INT_VERIFY(1, test_mbox_snapshot->total_msg_num);
    test_mbox_snapshot = ast_vm_mailbox_snapshot_destroy(test_mbox_snapshot);
    /* We should now have a total of 4 messages in test_vm_api_2345 INBOX */
    VM_API_SNAPSHOT_CREATE("test_vm_api_2345", "default", "INBOX", 0, AST_VM_SNAPSHOT_SORT_BY_TIME, 0);
    VM_API_INT_VERIFY(4, test_mbox_snapshot->total_msg_num);
    test_mbox_snapshot = ast_vm_mailbox_snapshot_destroy(test_mbox_snapshot);
    ast_test_status_update(test, "Test forwarding message 0 from test_vm_api_1234 INBOX to test_vm_api_2345 INBOX with default context\n");
    VM_API_FORWARD_MESSAGE("test_vm_api_1234", "default", "INBOX", "test_vm_api_2345", NULL, "INBOX", 1, &inbox_msg_id, 0);
    /* Make sure we didn't delete the message */
    VM_API_SNAPSHOT_CREATE("test_vm_api_1234", "default", "INBOX", 0, AST_VM_SNAPSHOT_SORT_BY_TIME, 0);
    VM_API_INT_VERIFY(1, test_mbox_snapshot->total_msg_num);
    test_mbox_snapshot = ast_vm_mailbox_snapshot_destroy(test_mbox_snapshot);
    /* We should now have a total of 5 messages in test_vm_api_2345 INBOX */
    VM_API_SNAPSHOT_CREATE("test_vm_api_2345", "default", "INBOX", 0, AST_VM_SNAPSHOT_SORT_BY_TIME, 0);
    VM_API_INT_VERIFY(5, test_mbox_snapshot->total_msg_num);
    test_mbox_snapshot = ast_vm_mailbox_snapshot_destroy(test_mbox_snapshot);
    ast_test_status_update(test, "Test forwarding message 0 from test_vm_api_1234 INBOX to test_vm_api_2345 INBOX, deleting original\n");
    VM_API_FORWARD_MESSAGE("test_vm_api_1234", "default", "INBOX", "test_vm_api_2345", NULL, "INBOX", 1, &inbox_msg_id, 1);
    /* Make sure we deleted the message */
    VM_API_SNAPSHOT_CREATE("test_vm_api_1234", "default", "INBOX", 0, AST_VM_SNAPSHOT_SORT_BY_TIME, 0);
    VM_API_INT_VERIFY(0, test_mbox_snapshot->total_msg_num);
    test_mbox_snapshot = ast_vm_mailbox_snapshot_destroy(test_mbox_snapshot);
    /* We should now have a total of 6 messages in test_vm_api_2345 INBOX */
    VM_API_SNAPSHOT_CREATE("test_vm_api_2345", "default", "INBOX", 0, AST_VM_SNAPSHOT_SORT_BY_TIME, 0);
    VM_API_INT_VERIFY(6, test_mbox_snapshot->total_msg_num);
    test_mbox_snapshot = ast_vm_mailbox_snapshot_destroy(test_mbox_snapshot);
    ast_test_status_update(test, "Test forwarding 2 messages from test_vm_api_2345 INBOX to test_vm_api_1234 INBOX");
    VM_API_FORWARD_MESSAGE("test_vm_api_2345", "default", "INBOX", "test_vm_api_1234", "default", "INBOX", 2, multi_msg_ids, 0);
    /* Make sure we didn't delete the messages */
    VM_API_SNAPSHOT_CREATE("test_vm_api_2345", "default", "INBOX", 0, AST_VM_SNAPSHOT_SORT_BY_TIME, 0);
    VM_API_INT_VERIFY(6, test_mbox_snapshot->total_msg_num);
    test_mbox_snapshot = ast_vm_mailbox_snapshot_destroy(test_mbox_snapshot);
    /* We should now have a total of 2 messages in test_vm_api_1234 INBOX */
    VM_API_SNAPSHOT_CREATE("test_vm_api_1234", "default", "INBOX", 0, AST_VM_SNAPSHOT_SORT_BY_TIME, 0);
    VM_API_INT_VERIFY(2, test_mbox_snapshot->total_msg_num);
    test_mbox_snapshot = ast_vm_mailbox_snapshot_destroy(test_mbox_snapshot);
    ast_test_status_update(test, "Test forwarding 2 messages from test_vm_api_2345 INBOX to test_vm_api_1234 Family, deleting original\n");
    VM_API_FORWARD_MESSAGE("test_vm_api_2345", "default", "INBOX", "test_vm_api_1234", "default", "Family", 2, multi_msg_ids, 1);
    /* Make sure we deleted the messages */
    VM_API_SNAPSHOT_CREATE("test_vm_api_2345", "default", "INBOX", 0, AST_VM_SNAPSHOT_SORT_BY_TIME, 0);
    VM_API_INT_VERIFY(4, test_mbox_snapshot->total_msg_num);
    test_mbox_snapshot = ast_vm_mailbox_snapshot_destroy(test_mbox_snapshot);
    /* We should now have a total of 2 messages in test_vm_api_1234 Family */
    VM_API_SNAPSHOT_CREATE("test_vm_api_1234", "default", "Family", 0, AST_VM_SNAPSHOT_SORT_BY_TIME, 0);
    VM_API_INT_VERIFY(2, test_mbox_snapshot->total_msg_num);
    test_mbox_snapshot = ast_vm_mailbox_snapshot_destroy(test_mbox_snapshot);
    VM_API_TEST_CLEANUP;
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [8/10]
AST_TEST_DEFINE (voicemail_api_off_nominal_forward)
Definition at line 1328 of file test_voicemail_api.c.
References AST_TEST_NOT_RUN, AST_TEST_PASS, ast_test_status_update, sip_to_pjsip::info(), ast_vm_msg_snapshot::msg_id, NULL, TEST_EXECUTE, TEST_INIT, VM_API_FORWARD_MESSAGE_OFF_NOMINAL, VM_API_TEST_CLEANUP, and VM_API_TEST_SETUP.
 {
    const char *inbox_msg_id;
    const char *multi_msg_ids[4];
    const char *empty_msg_ids[] = { };
    switch (cmd) {
    case TEST_INIT:
       info->name = "off_nominal_forward";
       info->category = "/main/voicemail_api/";
       info->summary = "Off nominal message forwarding tests";
       info->description =
          "Test off nominal forwarding of messages.  This includes:\n"
          " * Invalid/NULL from mailbox\n"
          " * Invalid from context\n"
          " * Invalid/NULL from folder\n"
          " * Invalid/NULL to mailbox\n"
          " * Invalid to context\n"
          " * Invalid/NULL to folder\n"
          " * Invalid message numbers\n"
          " * Invalid number of messages";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    VM_API_TEST_SETUP;
    inbox_msg_id = test_snapshots[1]->msg_id;
    multi_msg_ids[0] = test_snapshots[0]->msg_id;
    multi_msg_ids[1] = test_snapshots[1]->msg_id;
    multi_msg_ids[2] = test_snapshots[2]->msg_id;
    multi_msg_ids[3] = test_snapshots[3]->msg_id;
    ast_test_status_update(test, "Test forwarding from an invalid mailbox\n");
    VM_API_FORWARD_MESSAGE_OFF_NOMINAL("test_vm_api_3456", "default", "INBOX", "test_vm_api_2345", "default", "INBOX", 1, &inbox_msg_id, 0);
    ast_test_status_update(test, "Test forwarding from a NULL mailbox\n");
    VM_API_FORWARD_MESSAGE_OFF_NOMINAL(NULL, "default", "INBOX", "test_vm_api_2345", "default", "INBOX", 1, &inbox_msg_id, 0);
    ast_test_status_update(test, "Test forwarding from an invalid context\n");
    VM_API_FORWARD_MESSAGE_OFF_NOMINAL("test_vm_api_1234", "defunct", "INBOX", "test_vm_api_2345", "default", "INBOX", 1, &inbox_msg_id, 0);
    ast_test_status_update(test, "Test forwarding from an invalid folder\n");
    VM_API_FORWARD_MESSAGE_OFF_NOMINAL("test_vm_api_1234", "default", "POTTEDMEAT", "test_vm_api_2345", "default", "INBOX", 1, &inbox_msg_id, 0);
    ast_test_status_update(test, "Test forwarding from a NULL folder\n");
    VM_API_FORWARD_MESSAGE_OFF_NOMINAL("test_vm_api_1234", "default", NULL, "test_vm_api_2345", "default", "INBOX", 1, &inbox_msg_id, 0);
    ast_test_status_update(test, "Test forwarding to an invalid mailbox\n");
    VM_API_FORWARD_MESSAGE_OFF_NOMINAL("test_vm_api_1234", "default", "INBOX", "test_vm_api_3456", "default", "INBOX", 1, &inbox_msg_id, 0);
    ast_test_status_update(test, "Test forwarding to a NULL mailbox\n");
    VM_API_FORWARD_MESSAGE_OFF_NOMINAL("test_vm_api_1234", "default", "INBOX", NULL, "default", "INBOX", 1, &inbox_msg_id, 0);
    ast_test_status_update(test, "Test forwarding to an invalid context\n");
    VM_API_FORWARD_MESSAGE_OFF_NOMINAL("test_vm_api_1234", "default", "INBOX", "test_vm_api_2345", "defunct", "INBOX", 1, &inbox_msg_id, 0);
    ast_test_status_update(test, "Test forwarding to an invalid folder\n");
    VM_API_FORWARD_MESSAGE_OFF_NOMINAL("test_vm_api_1234", "default", "INBOX", "test_vm_api_2345", "default", "POTTEDMEAT", 1, &inbox_msg_id, 0);
    ast_test_status_update(test, "Test forwarding to a NULL folder\n");
    VM_API_FORWARD_MESSAGE_OFF_NOMINAL("test_vm_api_1234", "default", "INBOX", "test_vm_api_2345", "default", NULL, 1, &inbox_msg_id, 0);
    ast_test_status_update(test, "Test forwarding when no messages are select\n");
    VM_API_FORWARD_MESSAGE_OFF_NOMINAL("test_vm_api_1234", "default", "INBOX", "test_vm_api_2345", "default", "INBOX", 0, empty_msg_ids, 0);
    ast_test_status_update(test, "Test forwarding a message that doesn't exist\n");
    inbox_msg_id = "POOPOO";
    VM_API_FORWARD_MESSAGE_OFF_NOMINAL("test_vm_api_1234", "default", "INBOX", "test_vm_api_2345", "default", "INBOX", 1, &inbox_msg_id, 0);
    ast_test_status_update(test, "Test forwarding multiple messages, where some messages don't exist\n");
    VM_API_FORWARD_MESSAGE_OFF_NOMINAL("test_vm_api_2345", "default", "INBOX", "test_vm_api_1234", "default", "INBOX", 4, multi_msg_ids, 0);
    ast_test_status_update(test, "Test forwarding a message with an invalid size specifier\n");
    VM_API_FORWARD_MESSAGE_OFF_NOMINAL("test_vm_api_1234", "default", "INBOX", "test_vm_api_2345", "default", "INBOX", -30, &inbox_msg_id, 0);
    VM_API_TEST_CLEANUP;
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [9/10]
AST_TEST_DEFINE (voicemail_api_nominal_msg_playback)
Definition at line 1413 of file test_voicemail_api.c.
References ast_hangup(), ast_log, AST_LOG_ERROR, AST_TEST_FAIL, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_test_status_update, ast_vm_mailbox_snapshot_destroy(), AST_VM_SNAPSHOT_SORT_BY_TIME, global_entered_playback_callback, sip_to_pjsip::info(), message_playback_callback_fn(), ast_vm_msg_snapshot::msg_id, NULL, TEST_EXECUTE, TEST_INIT, test_vm_api_create_mock_channel(), ast_vm_mailbox_snapshot::total_msg_num, VM_API_INT_VERIFY, VM_API_PLAYBACK_MESSAGE, VM_API_SNAPSHOT_CREATE, VM_API_TEST_CLEANUP, and VM_API_TEST_SETUP.
 {
    struct ast_vm_mailbox_snapshot *test_mbox_snapshot = NULL;
    struct ast_channel *test_channel;
    const char *message_id_1234;
    const char *message_id_2345[2];
    switch (cmd) {
    case TEST_INIT:
       info->name = "nominal_msg_playback";
       info->category = "/main/voicemail_api/";
       info->summary = "Nominal message playback";
       info->description =
          "Tests playing back a message on a provided"
          " channel or callback function";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    VM_API_TEST_SETUP;
    message_id_1234 = test_snapshots[1]->msg_id;
    message_id_2345[0] = test_snapshots[2]->msg_id;
    message_id_2345[1] = test_snapshots[3]->msg_id;
    if (!(test_channel = test_vm_api_create_mock_channel())) {
       ast_log(AST_LOG_ERROR, "Failed to create mock channel for testing\n");
       VM_API_TEST_CLEANUP;
       return AST_TEST_FAIL;
    }
    ast_test_status_update(test, "Playing back message from test_vm_api_1234 to mock channel\n");
    VM_API_PLAYBACK_MESSAGE(test_channel, "test_vm_api_1234", "default", "INBOX", message_id_1234, NULL);
    ast_test_status_update(test, "Playing back message from test_vm_api_2345 to callback function\n");
    VM_API_PLAYBACK_MESSAGE(test_channel, "test_vm_api_2345", "default", "INBOX", message_id_2345[0], &message_playback_callback_fn);
    VM_API_INT_VERIFY(1, global_entered_playback_callback);
    global_entered_playback_callback = 0;
    ast_test_status_update(test, "Playing back message from test_vm_api_2345 to callback function with default context\n");
    VM_API_PLAYBACK_MESSAGE(test_channel, "test_vm_api_2345", NULL, "INBOX", message_id_2345[1], &message_playback_callback_fn);
    VM_API_INT_VERIFY(1, global_entered_playback_callback);
    global_entered_playback_callback = 0;
    VM_API_SNAPSHOT_CREATE("test_vm_api_1234", "default", "Old", 0, AST_VM_SNAPSHOT_SORT_BY_TIME, 0);
    VM_API_INT_VERIFY(2, test_mbox_snapshot->total_msg_num);
    test_mbox_snapshot = ast_vm_mailbox_snapshot_destroy(test_mbox_snapshot);
    VM_API_SNAPSHOT_CREATE("test_vm_api_2345", "default", "Old", 0, AST_VM_SNAPSHOT_SORT_BY_TIME, 0);
    VM_API_INT_VERIFY(2, test_mbox_snapshot->total_msg_num);
    test_mbox_snapshot = ast_vm_mailbox_snapshot_destroy(test_mbox_snapshot);
    ast_hangup(test_channel);
    VM_API_TEST_CLEANUP;
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [10/10]
AST_TEST_DEFINE (voicemail_api_off_nominal_msg_playback)
Definition at line 1472 of file test_voicemail_api.c.
References ast_hangup(), ast_log, AST_LOG_ERROR, AST_TEST_FAIL, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_test_status_update, sip_to_pjsip::info(), ast_vm_msg_snapshot::msg_id, NULL, TEST_EXECUTE, TEST_INIT, test_vm_api_create_mock_channel(), VM_API_PLAYBACK_MESSAGE_OFF_NOMINAL, VM_API_TEST_CLEANUP, and VM_API_TEST_SETUP.
 {
    struct ast_channel *test_channel;
    const char *msg_id;
    const char *invalid_msg_id = "POOPOO";
    switch (cmd) {
    case TEST_INIT:
       info->name = "off_nominal_msg_playback";
       info->category = "/main/voicemail_api/";
       info->summary = "Off nominal message playback";
       info->description =
          "Tests off nominal conditions in playing back a "
          "message.  This includes:\n"
          " * Invalid/NULL mailbox\n"
          " * Invalid context\n"
          " * Invalid/NULL folder\n"
          " * Invalid message identifiers";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    VM_API_TEST_SETUP;
    msg_id = test_snapshots[0]->msg_id;
    if (!(test_channel = test_vm_api_create_mock_channel())) {
       ast_log(AST_LOG_ERROR, "Failed to create mock channel for testing\n");
       VM_API_TEST_CLEANUP;
       return AST_TEST_FAIL;
    }
    ast_test_status_update(test, "Playing back message from invalid mailbox\n");
    VM_API_PLAYBACK_MESSAGE_OFF_NOMINAL(test_channel, "test_vm_api_3456", "default", "INBOX", msg_id, NULL);
    ast_test_status_update(test, "Playing back message from NULL mailbox\n");
    VM_API_PLAYBACK_MESSAGE_OFF_NOMINAL(test_channel, NULL, "default", "INBOX", msg_id, NULL);
    ast_test_status_update(test, "Playing back message from invalid context\n");
    VM_API_PLAYBACK_MESSAGE_OFF_NOMINAL(test_channel, "test_vm_api_1234", "defunct", "INBOX", msg_id, NULL);
    ast_test_status_update(test, "Playing back message from invalid folder\n");
    VM_API_PLAYBACK_MESSAGE_OFF_NOMINAL(test_channel, "test_vm_api_1234", "default", "BACON", msg_id, NULL);
    ast_test_status_update(test, "Playing back message from NULL folder\n");
    VM_API_PLAYBACK_MESSAGE_OFF_NOMINAL(test_channel, "test_vm_api_1234", "default",  NULL, msg_id, NULL);
    ast_test_status_update(test, "Playing back message with invalid message specifier\n");
    VM_API_PLAYBACK_MESSAGE_OFF_NOMINAL(test_channel, "test_vm_api_1234", "default", "INBOX", invalid_msg_id, NULL);
    ast_test_status_update(test, "Playing back message with NULL message specifier\n");
    VM_API_PLAYBACK_MESSAGE_OFF_NOMINAL(test_channel, "test_vm_api_1234", "default", "INBOX", NULL, NULL);
    ast_hangup(test_channel);
    VM_API_TEST_CLEANUP;
    return AST_TEST_PASS;
 }
get_folder_by_name()
static int get_folder_by_name (const char * folder) static
Definition at line 353 of file test_voicemail_api.c.
References ARRAY_LEN, and mailbox_folders.
 {
    size_t i;
    for (i = 0; i < ARRAY_LEN(mailbox_folders); i++) {
       if (strcasecmp(folder, mailbox_folders[i]) == 0) {
          return i;
       }
    }
    return -1;
 }
load_module()
static int load_module (void) static
Definition at line 1554 of file test_voicemail_api.c.
References AST_MODULE_LOAD_SUCCESS, and AST_TEST_REGISTER.
 {
    /* Snapshot tests */
    AST_TEST_REGISTER(voicemail_api_nominal_snapshot);
    AST_TEST_REGISTER(voicemail_api_off_nominal_snapshot);
    /* Move Tests */
    AST_TEST_REGISTER(voicemail_api_nominal_move);
    AST_TEST_REGISTER(voicemail_api_off_nominal_move);
    /* Remove Tests */
    AST_TEST_REGISTER(voicemail_api_nominal_remove);
    AST_TEST_REGISTER(voicemail_api_off_nominal_remove);
    /* Forward Tests */
    AST_TEST_REGISTER(voicemail_api_nominal_forward);
    AST_TEST_REGISTER(voicemail_api_off_nominal_forward);
    /* Message Playback Tests */
    AST_TEST_REGISTER(voicemail_api_nominal_msg_playback);
    AST_TEST_REGISTER(voicemail_api_off_nominal_msg_playback);
    return AST_MODULE_LOAD_SUCCESS;
 }
message_playback_callback_fn()
static void message_playback_callback_fn (struct ast_channel * chan, const char * file, int duration) static
Definition at line 775 of file test_voicemail_api.c.
References ast_log, AST_LOG_WARNING, ast_strlen_zero, and global_entered_playback_callback.
Referenced by AST_TEST_DEFINE().
 {
    if ((chan) && !ast_strlen_zero(file) && duration > 0) {
       global_entered_playback_callback = 1;
    } else {
       ast_log(AST_LOG_WARNING, "Entered into message playback callback function with invalid parameters\n");
    }
 }
test_vm_api_create_mock_channel()
static struct ast_channel* test_vm_api_create_mock_channel (void) static
Definition at line 818 of file test_voicemail_api.c.
References ast_channel_alloc, ast_channel_nativeformats(), ast_channel_set_rawreadformat(), ast_channel_set_rawwriteformat(), ast_channel_set_readformat(), ast_channel_set_writeformat(), ast_channel_tech_set(), ast_channel_unlock, ast_channel_writeformat(), ast_format_cap_append, ast_format_gsm, AST_STATE_DOWN, and NULL.
Referenced by AST_TEST_DEFINE().
 {
    struct ast_channel *mock_channel;
    struct ast_format_cap *native_formats;
    if (!(mock_channel = ast_channel_alloc(0, AST_STATE_DOWN, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, "TestChannel"))) {
       return NULL;
    }
    ast_channel_set_writeformat(mock_channel, ast_format_gsm);
    ast_channel_set_rawwriteformat(mock_channel, ast_format_gsm);
    ast_channel_set_readformat(mock_channel, ast_format_gsm);
    ast_channel_set_rawreadformat(mock_channel, ast_format_gsm);
    ast_channel_tech_set(mock_channel, &mock_channel_tech);
    native_formats = ast_channel_nativeformats(mock_channel);
    ast_format_cap_append(native_formats, ast_channel_writeformat(mock_channel), 0);
    ast_channel_unlock(mock_channel);
    return mock_channel;
 }
test_vm_api_create_mock_snapshot()
static struct ast_vm_msg_snapshot* test_vm_api_create_mock_snapshot (const char * context, const char * exten, const char * callerid) static
Definition at line 377 of file test_voicemail_api.c.
References ast_calloc, ast_free, AST_MAX_CONTEXT, AST_MAX_EXTENSION, ast_str_hash(), ast_string_field_init, ast_string_field_set, ast_vm_msg_snapshot::callerid, ast_vm_msg_snapshot::msg_id, and NULL.
Referenced by test_vm_api_test_setup().
 {
    char msg_id_hash[AST_MAX_CONTEXT + AST_MAX_EXTENSION + sizeof(callerid) + 1];
    char msg_id_buf[256];
    struct ast_vm_msg_snapshot *snapshot;
    snprintf(msg_id_hash, sizeof(msg_id_hash), "%s%s%s", exten, context, callerid);
    snprintf(msg_id_buf, sizeof(msg_id_buf), "%ld-%d", (long)time(NULL), ast_str_hash(msg_id_hash));
    if ((snapshot = ast_calloc(1, sizeof(*snapshot)))) {
       if (ast_string_field_init(snapshot, 128)) {
          ast_free(snapshot);
          return NULL;
       }
       ast_string_field_set(snapshot, msg_id, msg_id_buf);
       ast_string_field_set(snapshot, exten, exten);
       ast_string_field_set(snapshot, callerid, callerid);
    }
    return snapshot;
 }
test_vm_api_create_voicemail_files()
static int test_vm_api_create_voicemail_files (const char * context, const char * mailbox, struct ast_vm_msg_snapshot * snapshot) static
Definition at line 445 of file test_voicemail_api.c.
References ast_config_AST_DATA_DIR, ast_config_AST_SPOOL_DIR, AST_LOCK_FAILURE, ast_lock_path(), ast_log, AST_LOG_ERROR, ast_unlock_path(), ast_vm_msg_snapshot::callerchan, ast_vm_msg_snapshot::callerid, ast_vm_msg_snapshot::duration, errno, ast_vm_msg_snapshot::exten, ast_vm_msg_snapshot::flag, ast_vm_msg_snapshot::folder_name, ast_vm_msg_snapshot::msg_id, ast_vm_msg_snapshot::msg_number, ast_vm_msg_snapshot::origdate, ast_vm_msg_snapshot::origtime, PATH_MAX, test_vm_api_create_voicemail_folder(), and VOICEMAIL_FILE_MODE.
Referenced by test_vm_api_test_setup().
 {
    FILE *msg_file;
    char folder_path[PATH_MAX];
    char msg_path[PATH_MAX];
    char snd_path[PATH_MAX];
    char beep_path[PATH_MAX];
    /* Note that we create both the text and a dummy sound file here.  Without
     * the sound file, a number of the voicemail operations 'silently' fail, as it
     * does not believe that an actual voicemail exists
     */
    snprintf(folder_path, sizeof(folder_path), "%s/voicemail/%s/%s/%s",
       ast_config_AST_SPOOL_DIR, context, mailbox, snapshot->folder_name);
    snprintf(msg_path, sizeof(msg_path), "%s/msg%04u.txt",
       folder_path, snapshot->msg_number);
    snprintf(snd_path, sizeof(snd_path), "%s/msg%04u.gsm",
       folder_path, snapshot->msg_number);
    snprintf(beep_path, sizeof(beep_path), "%s/sounds/en/beep.gsm", ast_config_AST_DATA_DIR);
    if (test_vm_api_create_voicemail_folder(folder_path)) {
       return 1;
    }
    if (ast_lock_path(folder_path) == AST_LOCK_FAILURE) {
       ast_log(AST_LOG_ERROR, "Unable to lock directory %s\n", folder_path);
       return 1;
    }
    if (symlink(beep_path, snd_path)) {
       ast_unlock_path(folder_path);
       ast_log(AST_LOG_ERROR, "Failed to create a symbolic link from %s to %s: %s\n",
          beep_path, snd_path, strerror(errno));
       return 1;
    }
    if (!(msg_file = fopen(msg_path, "w"))) {
       /* Attempt to remove the sound file */
       unlink(snd_path);
       ast_unlock_path(folder_path);
       ast_log(AST_LOG_ERROR, "Failed to open %s for writing\n", msg_path);
       return 1;
    }
    fprintf(msg_file, ";\n; Message Information file\n;\n"
       "[message]\n"
       "origmailbox=%s\n"
       "context=%s\n"
       "macrocontext=%s\n"
       "exten=%s\n"
       "rdnis=%s\n"
       "priority=%d\n"
       "callerchan=%s\n"
       "callerid=%s\n"
       "origdate=%s\n"
       "origtime=%s\n"
       "category=%s\n"
       "msg_id=%s\n"
       "flag=%s\n"
       "duration=%s\n",
       mailbox,
       context,
       "",
       snapshot->exten,
       "unknown",
       1,
       snapshot->callerchan,
       snapshot->callerid,
       snapshot->origdate,
       snapshot->origtime,
       "",
       snapshot->msg_id,
       snapshot->flag,
       snapshot->duration);
    fclose(msg_file);
    if (chmod(msg_path, VOICEMAIL_FILE_MODE) < 0) {
       ast_unlock_path(folder_path);
       ast_log(AST_LOG_ERROR, "Couldn't set permissions on voicemail text file %s: %s", msg_path, strerror(errno));
       return 1;
    }
    ast_unlock_path(folder_path);
    return 0;
 }
test_vm_api_create_voicemail_folder()
static int test_vm_api_create_voicemail_folder (const char * folder_path) static
Definition at line 419 of file test_voicemail_api.c.
References ast_log, AST_LOG_ERROR, ast_mkdir(), and VOICEMAIL_DIR_MODE.
Referenced by test_vm_api_create_voicemail_files().
 {
    mode_t mode = VOICEMAIL_DIR_MODE;
    int res;
    if ((res = ast_mkdir(folder_path, mode))) {
       ast_log(AST_LOG_ERROR, "ast_mkdir '%s' failed: %s\n", folder_path, strerror(res));
       return 1;
    }
    return 0;
 }
test_vm_api_destroy_mailbox_voicemails()
static void test_vm_api_destroy_mailbox_voicemails (const char * mailbox, struct ast_vm_mailbox_snapshot * mailbox_snapshot) static
Definition at line 572 of file test_voicemail_api.c.
References AST_LIST_TRAVERSE, ast_string_field_set, exten, ast_vm_msg_snapshot::msg, ast_vm_mailbox_snapshot::snapshots, and test_vm_api_remove_voicemail().
Referenced by test_vm_api_remove_all_messages().
 {
    struct ast_vm_msg_snapshot *msg;
    int i;
    for (i = 0; i < 12; ++i) {
       AST_LIST_TRAVERSE(&mailbox_snapshot->snapshots[i], msg, msg) {
          ast_string_field_set(msg, exten, mailbox);
          test_vm_api_remove_voicemail(msg);
       }
    }
 }
test_vm_api_destroy_mock_snapshot()
static void test_vm_api_destroy_mock_snapshot (struct ast_vm_msg_snapshot * snapshot) static
Definition at line 402 of file test_voicemail_api.c.
References ast_free, and ast_string_field_free_memory.
Referenced by test_vm_api_test_setup(), and test_vm_api_test_teardown().
 {
    if (snapshot) {
       ast_string_field_free_memory(snapshot);
       ast_free(snapshot);
    }
 }
test_vm_api_mock_channel_read()
static struct ast_frame* test_vm_api_mock_channel_read (struct ast_channel * chan) static
Definition at line 797 of file test_voicemail_api.c.
References ast_null_frame.
 {
    return &ast_null_frame;
 }
test_vm_api_mock_channel_write()
static int test_vm_api_mock_channel_write (struct ast_channel * chan, struct ast_frame * frame) static
Definition at line 788 of file test_voicemail_api.c.
 {
    return 0;
 }
test_vm_api_remove_all_messages()
static void test_vm_api_remove_all_messages (void) static
Definition at line 589 of file test_voicemail_api.c.
References ast_log, AST_LOG_WARNING, ast_vm_mailbox_snapshot_create(), ast_vm_mailbox_snapshot_destroy(), AST_VM_SNAPSHOT_SORT_BY_ID, NULL, and test_vm_api_destroy_mailbox_voicemails().
Referenced by test_vm_api_test_setup(), and test_vm_api_test_teardown().
 {
    struct ast_vm_mailbox_snapshot *mailbox_snapshot;
    /* Take a snapshot of each mailbox and remove the contents.  Note that we need to use
     * snapshots of the mailboxes in addition to our tracked test snapshots, as there's a good chance
     * we've created copies of the snapshots */
    if ((mailbox_snapshot = ast_vm_mailbox_snapshot_create("test_vm_api_1234", "default", NULL, 0, AST_VM_SNAPSHOT_SORT_BY_ID, 0))) {
       test_vm_api_destroy_mailbox_voicemails("test_vm_api_1234", mailbox_snapshot);
       mailbox_snapshot = ast_vm_mailbox_snapshot_destroy(mailbox_snapshot);
    } else {
       ast_log(AST_LOG_WARNING, "Failed to create mailbox snapshot - could not remove test messages for test_vm_api_1234\n");
    }
    if ((mailbox_snapshot = ast_vm_mailbox_snapshot_create("test_vm_api_2345", "default", NULL, 0, AST_VM_SNAPSHOT_SORT_BY_ID, 0))) {
       test_vm_api_destroy_mailbox_voicemails("test_vm_api_2345", mailbox_snapshot);
       mailbox_snapshot = ast_vm_mailbox_snapshot_destroy(mailbox_snapshot);
    } else {
       ast_log(AST_LOG_WARNING, "Failed to create mailbox snapshot - could not remove test messages for test_vm_api_2345\n");
    }
 }
test_vm_api_remove_voicemail()
static void test_vm_api_remove_voicemail (struct ast_vm_msg_snapshot * snapshot) static
Definition at line 537 of file test_voicemail_api.c.
References ast_config_AST_SPOOL_DIR, ast_vm_msg_snapshot::exten, ast_vm_msg_snapshot::folder_name, ast_vm_msg_snapshot::msg_number, and PATH_MAX.
Referenced by test_vm_api_destroy_mailbox_voicemails(), and test_vm_api_test_teardown().
 {
    char msg_path[PATH_MAX];
    char snd_path[PATH_MAX];
    char folder_path[PATH_MAX];
    if (!snapshot) {
       return;
    }
    snprintf(folder_path, sizeof(folder_path), "%s/voicemail/%s/%s/%s",
       ast_config_AST_SPOOL_DIR, "default", snapshot->exten, snapshot->folder_name);
    snprintf(msg_path, sizeof(msg_path), "%s/msg%04u.txt",
          folder_path, snapshot->msg_number);
    snprintf(snd_path, sizeof(snd_path), "%s/msg%04u.gsm",
          folder_path, snapshot->msg_number);
    unlink(msg_path);
    unlink(snd_path);
    return;
 }
test_vm_api_test_setup()
static int test_vm_api_test_setup (void) static
Definition at line 626 of file test_voicemail_api.c.
References ast_log, AST_LOG_ERROR, ast_string_field_set, ast_vm_test_create_user(), ast_vm_msg_snapshot::callerchan, ast_vm_msg_snapshot::duration, exten, ast_vm_msg_snapshot::folder_name, ast_vm_msg_snapshot::msg_number, NULL, ast_vm_msg_snapshot::origdate, ast_vm_msg_snapshot::origtime, test_vm_api_create_mock_snapshot(), test_vm_api_create_voicemail_files(), test_vm_api_destroy_mock_snapshot(), test_vm_api_remove_all_messages(), and TOTAL_SNAPSHOTS.
 {
    int i, res = 0;
    struct ast_vm_msg_snapshot *msg_one = NULL;
    struct ast_vm_msg_snapshot *msg_two = NULL;
    struct ast_vm_msg_snapshot *msg_three = NULL;
    struct ast_vm_msg_snapshot *msg_four = NULL;
    /* Make the four sample voicemails */
    if (   !((msg_one = test_vm_api_create_mock_snapshot("default", "test_vm_api_1234", "\"Phil\" <2000>")))
       || !((msg_two = test_vm_api_create_mock_snapshot("default", "test_vm_api_1234", "\"Noel\" <8000>")))
       || !((msg_three = test_vm_api_create_mock_snapshot("default", "test_vm_api_2345", "\"Phil\" <2000>")))
       || !((msg_four = test_vm_api_create_mock_snapshot("default", "test_vm_api_2345", "\"Bill\" <3000>")))) {
       ast_log(AST_LOG_ERROR, "Failed to create mock snapshots for test\n");
       test_vm_api_destroy_mock_snapshot(msg_one);
       test_vm_api_destroy_mock_snapshot(msg_two);
       test_vm_api_destroy_mock_snapshot(msg_three);
       test_vm_api_destroy_mock_snapshot(msg_four);
       return 1;
    }
    /* Create the voicemail users */
    if (ast_vm_test_create_user("default", "test_vm_api_1234")
       || ast_vm_test_create_user("default", "test_vm_api_2345")) {
       ast_log(AST_LOG_ERROR, "Failed to create test voicemail users\n");
       test_vm_api_destroy_mock_snapshot(msg_one);
       test_vm_api_destroy_mock_snapshot(msg_two);
       test_vm_api_destroy_mock_snapshot(msg_three);
       test_vm_api_destroy_mock_snapshot(msg_four);
       /* Note that the cleanup macro will ensure that any test user that
        * was successfully created is removed
        */
       return 1;
    }
    /* Now that the users exist from the perspective of the voicemail
     * application, attempt to remove any existing voicemails
     */
    test_vm_api_remove_all_messages();
    /* Set the basic properties on each */
    ast_string_field_set(msg_one, callerchan, "SIP/2000-00000000");
    ast_string_field_set(msg_one, origdate, "Mon Mar 19 04:14:21 PM UTC 2012");
    ast_string_field_set(msg_one, origtime, "1332173661");
    ast_string_field_set(msg_one, duration, "8");
    ast_string_field_set(msg_one, folder_name, "Old");
    msg_one->msg_number = 0;
    test_snapshots[0] = msg_one;
    ast_string_field_set(msg_two, callerchan, "SIP/8000-00000001");
    ast_string_field_set(msg_two, origdate, "Mon Mar 19 06:16:13 PM UTC 2012");
    ast_string_field_set(msg_two, origtime, "1332180973");
    ast_string_field_set(msg_two, duration, "24");
    ast_string_field_set(msg_two, folder_name, "INBOX");
    msg_two->msg_number = 0;
    test_snapshots[1] = msg_two;
    ast_string_field_set(msg_three, callerchan, "IAX/2000-000000a3");
    ast_string_field_set(msg_three, origdate, "Thu Mar 22 23:13:03 PM UTC 2012");
    ast_string_field_set(msg_three, origtime, "1332181251");
    ast_string_field_set(msg_three, duration, "25");
    ast_string_field_set(msg_three, folder_name, "INBOX");
    msg_three->msg_number = 0;
    test_snapshots[2] = msg_three;
    ast_string_field_set(msg_four, callerchan, "DAHDI/3000-00000010");
    ast_string_field_set(msg_four, origdate, "Fri Mar 23 03:01:03 AM UTC 2012");
    ast_string_field_set(msg_four, origtime, "1332181362");
    ast_string_field_set(msg_four, duration, "13");
    ast_string_field_set(msg_four, folder_name, "INBOX");
    msg_three->msg_number = 1;
    test_snapshots[3] = msg_four;
    /* Store the messages */
    for (i = 0; i < TOTAL_SNAPSHOTS; ++i) {
       if (test_vm_api_create_voicemail_files("default", test_snapshots[i]->exten, test_snapshots[i])) {
          /* On a failure, the test_vm_api_test_teardown method will remove and
           * unlink any created files. Since we failed to create the file, clean
           * up the object here instead */
          ast_log(AST_LOG_ERROR, "Failed to store voicemail %s/%s\n",
             "default", test_snapshots[i]->exten);
          test_vm_api_destroy_mock_snapshot(test_snapshots[i]);
          test_snapshots[i] = NULL;
          res = 1;
       }
    }
    return res;
 }
test_vm_api_test_teardown()
static void test_vm_api_test_teardown (void) static
Definition at line 716 of file test_voicemail_api.c.
References ast_vm_test_destroy_user(), NULL, test_vm_api_destroy_mock_snapshot(), test_vm_api_remove_all_messages(), test_vm_api_remove_voicemail(), and TOTAL_SNAPSHOTS.
 {
    int i;
    /* Remove our test message snapshots */
    for (i = 0; i < TOTAL_SNAPSHOTS; ++i) {
       test_vm_api_remove_voicemail(test_snapshots[i]);
       test_vm_api_destroy_mock_snapshot(test_snapshots[i]);
       test_snapshots[i] = NULL;
    }
    test_vm_api_remove_all_messages();
    /* Remove the test users */
    ast_vm_test_destroy_user("default", "test_vm_api_1234");
    ast_vm_test_destroy_user("default", "test_vm_api_2345");
 }
test_vm_api_update_test_snapshots()
static void test_vm_api_update_test_snapshots (struct ast_vm_mailbox_snapshot * mailbox_snapshot) static
Definition at line 740 of file test_voicemail_api.c.
References AST_LIST_TRAVERSE, ast_string_field_set, ast_vm_msg_snapshot::callerchan, ast_vm_msg_snapshot::callerid, ast_vm_msg_snapshot::duration, exten, ast_vm_msg_snapshot::exten, ast_vm_msg_snapshot::flag, ast_vm_msg_snapshot::folder_name, ast_vm_msg_snapshot::msg, ast_vm_msg_snapshot::msg_id, ast_vm_msg_snapshot::msg_number, ast_vm_msg_snapshot::origdate, ast_vm_msg_snapshot::origtime, ast_vm_mailbox_snapshot::snapshots, and TOTAL_SNAPSHOTS.
Referenced by AST_TEST_DEFINE().
 {
    int i, j;
    struct ast_vm_msg_snapshot *msg;
    for (i = 0; i < TOTAL_SNAPSHOTS; ++i) {
       for (j = 0; j < 12; ++j) {
          AST_LIST_TRAVERSE(&mailbox_snapshot->snapshots[j], msg, msg) {
             if (!strcmp(msg->msg_id, test_snapshots[i]->msg_id)) {
                ast_string_field_set(test_snapshots[i], callerid, msg->callerid);
                ast_string_field_set(test_snapshots[i], callerchan, msg->callerchan);
                ast_string_field_set(test_snapshots[i], exten, msg->exten);
                ast_string_field_set(test_snapshots[i], origdate, msg->origdate);
                ast_string_field_set(test_snapshots[i], origtime, msg->origtime);
                ast_string_field_set(test_snapshots[i], duration, msg->duration);
                ast_string_field_set(test_snapshots[i], folder_name, msg->folder_name);
                ast_string_field_set(test_snapshots[i], flag, msg->flag);
                test_snapshots[i]->msg_number = msg->msg_number;
             }
          }
       }
    }
 }
unload_module()
static int unload_module (void) static
Definition at line 1530 of file test_voicemail_api.c.
References AST_TEST_UNREGISTER.
 {
    /* Snapshot tests */
    AST_TEST_UNREGISTER(voicemail_api_nominal_snapshot);
    AST_TEST_UNREGISTER(voicemail_api_off_nominal_snapshot);
    /* Move Tests */
    AST_TEST_UNREGISTER(voicemail_api_nominal_move);
    AST_TEST_UNREGISTER(voicemail_api_off_nominal_move);
    /* Remove Tests */
    AST_TEST_UNREGISTER(voicemail_api_nominal_remove);
    AST_TEST_UNREGISTER(voicemail_api_off_nominal_remove);
    /* Forward Tests */
    AST_TEST_UNREGISTER(voicemail_api_nominal_forward);
    AST_TEST_UNREGISTER(voicemail_api_off_nominal_forward);
    /* Message Playback Tests */
    AST_TEST_UNREGISTER(voicemail_api_nominal_msg_playback);
    AST_TEST_UNREGISTER(voicemail_api_off_nominal_msg_playback);
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Core Voicemail API Tests" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, } static
Definition at line 1579 of file test_voicemail_api.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 1579 of file test_voicemail_api.c.
global_entered_playback_callback
int global_entered_playback_callback = 0 static
Definition at line 347 of file test_voicemail_api.c.
Referenced by AST_TEST_DEFINE(), and message_playback_callback_fn().
mailbox_folders
const char* const mailbox_folders[] static
Definition at line 322 of file test_voicemail_api.c.
Referenced by get_folder_by_name().
mock_channel_tech
const struct ast_channel_tech mock_channel_tech static
Initial value:
= {
      .write = test_vm_api_mock_channel_write,
      .read = test_vm_api_mock_channel_read,
}
Definition at line 806 of file test_voicemail_api.c.
test_snapshots
struct ast_vm_msg_snapshot* test_snapshots[TOTAL_SNAPSHOTS] static
Definition at line 341 of file test_voicemail_api.c.