Asterisk - The Open Source Telephony Project: bridge_technology.h File Reference
bridge_technology.h File Reference
Channel Bridging API.
Data Structures
struct ast_bridge_tech_optimizations
Structure specific to bridge technologies capable of performing talking optimizations.
struct ast_bridge_technology
Structure that is the essence of a bridge technology.
Macros
#define ast_bridge_technology_register(technology) __ast_bridge_technology_register(technology, AST_MODULE_SELF)
See __ast_bridge_technology_register()
Enumerations
enum ast_bridge_preference {
AST_BRIDGE_PREFERENCE_BASE_HOLDING = 50, AST_BRIDGE_PREFERENCE_BASE_EARLY = 100, AST_BRIDGE_PREFERENCE_BASE_NATIVE = 90, AST_BRIDGE_PREFERENCE_BASE_1TO1MIX = 50,
AST_BRIDGE_PREFERENCE_BASE_MULTIMIX = 10
}
Base preference values for choosing a bridge technology.
Functions
int __ast_bridge_technology_register (struct ast_bridge_technology *technology, struct ast_module *mod)
Register a bridge technology for use.
void ast_bridge_technology_suspend (struct ast_bridge_technology *technology)
Suspend a bridge technology from consideration.
int ast_bridge_technology_unregister (struct ast_bridge_technology *technology)
Unregister a bridge technology from use.
void ast_bridge_technology_unsuspend (struct ast_bridge_technology *technology)
Unsuspend a bridge technology.
Detailed Description
Channel Bridging API.
Author
Joshua Colp jcolp.nosp@m.@dig.nosp@m.ium.c.nosp@m.om
Definition in file bridge_technology.h.
Macro Definition Documentation
ast_bridge_technology_register
#define ast_bridge_technology_register (technology) __ast_bridge_technology_register(technology, AST_MODULE_SELF)
See __ast_bridge_technology_register()
Definition at line 223 of file bridge_technology.h.
Referenced by dahdi_native_load(), and load_module().
Enumeration Type Documentation
ast_bridge_preference
enum ast_bridge_preference
Base preference values for choosing a bridge technology.
Note
Higher is more preference.
Enumerator
AST_BRIDGE_PREFERENCE_BASE_HOLDING
AST_BRIDGE_PREFERENCE_BASE_EARLY
AST_BRIDGE_PREFERENCE_BASE_NATIVE
AST_BRIDGE_PREFERENCE_BASE_1TO1MIX
AST_BRIDGE_PREFERENCE_BASE_MULTIMIX
Definition at line 36 of file bridge_technology.h.
{
    AST_BRIDGE_PREFERENCE_BASE_HOLDING  = 50,
    AST_BRIDGE_PREFERENCE_BASE_EARLY    = 100,
    AST_BRIDGE_PREFERENCE_BASE_NATIVE   = 90,
    AST_BRIDGE_PREFERENCE_BASE_1TO1MIX  = 50,
    AST_BRIDGE_PREFERENCE_BASE_MULTIMIX = 10,
 };
Function Documentation
__ast_bridge_technology_register()
int __ast_bridge_technology_register (struct ast_bridge_technology * technology, struct ast_module * mod)
Register a bridge technology for use.
Parameters
technology The bridge technology to register
mod The module that is registering the bridge technology
Return values
0 on success
-1 on failure
Example usage:
ast_bridge_technology_register(&simple_bridge_tech);
This registers a bridge technology declared as the structure simple_bridge_tech with the bridging core and makes it available for use when creating bridges.
Definition at line 214 of file bridge.c.
References ast_log, AST_RWLIST_INSERT_BEFORE_CURRENT, AST_RWLIST_INSERT_TAIL, AST_RWLIST_TRAVERSE, AST_RWLIST_TRAVERSE_SAFE_BEGIN, AST_RWLIST_TRAVERSE_SAFE_END, AST_RWLIST_UNLOCK, AST_RWLIST_WRLOCK, ast_strlen_zero, ast_verb, ast_bridge_technology::capabilities, LOG_WARNING, ast_bridge_technology::mod, ast_bridge_technology::name, ast_bridge_technology::preference, and ast_bridge_technology::write.
 {
    struct ast_bridge_technology *current;
    /* Perform a sanity check to make sure the bridge technology conforms to our needed requirements */
    if (ast_strlen_zero(technology->name)
       || !technology->capabilities
       || !technology->write) {
       ast_log(LOG_WARNING, "Bridge technology %s failed registration sanity check.\n",
          technology->name);
       return -1;
    }
    AST_RWLIST_WRLOCK(&bridge_technologies);
    /* Look for duplicate bridge technology already using this name, or already registered */
    AST_RWLIST_TRAVERSE(&bridge_technologies, current, entry) {
       if ((!strcasecmp(current->name, technology->name)) || (current == technology)) {
          ast_log(LOG_WARNING, "A bridge technology of %s already claims to exist in our world.\n",
             technology->name);
          AST_RWLIST_UNLOCK(&bridge_technologies);
          return -1;
       }
    }
    /* Copy module pointer so reference counting can keep the module from unloading */
    technology->mod = module;
    /* Find the correct position to insert the technology. */
    AST_RWLIST_TRAVERSE_SAFE_BEGIN(&bridge_technologies, current, entry) {
       /* Put the highest preference tech's first in the list. */
       if (technology->preference >= current->preference) {
          AST_RWLIST_INSERT_BEFORE_CURRENT(technology, entry);
          break;
       }
    }
    AST_RWLIST_TRAVERSE_SAFE_END;
    if (!current) {
       /* Insert our new bridge technology to the end of the list. */
       AST_RWLIST_INSERT_TAIL(&bridge_technologies, technology, entry);
    }
    AST_RWLIST_UNLOCK(&bridge_technologies);
    ast_verb(2, "Registered bridge technology %s\n", technology->name);
    return 0;
 }
ast_bridge_technology_suspend()
void ast_bridge_technology_suspend (struct ast_bridge_technology * technology)
Suspend a bridge technology from consideration.
Parameters
technology The bridge technology to suspend
Example usage:
ast_bridge_technology_suspend(&simple_bridge_tech);
This suspends the bridge technology simple_bridge_tech from being considered when creating a new bridge. Existing bridges using the bridge technology are not affected.
Definition at line 3108 of file bridge.c.
References ast_bridge_technology::suspended.
Referenced by handle_bridge_technology_suspend(), and handle_manager_bridge_tech_suspend().
 {
    technology->suspended = 1;
 }
ast_bridge_technology_unregister()
int ast_bridge_technology_unregister (struct ast_bridge_technology * technology)
Unregister a bridge technology from use.
Parameters
technology The bridge technology to unregister
Return values
0 on success
-1 on failure
Example usage:
ast_bridge_technology_unregister(&simple_bridge_tech);
This unregisters a bridge technlogy declared as the structure simple_bridge_tech with the bridging core. It will no longer be considered when creating a new bridge.
Definition at line 265 of file bridge.c.
References AST_RWLIST_REMOVE_CURRENT, AST_RWLIST_TRAVERSE_SAFE_BEGIN, AST_RWLIST_TRAVERSE_SAFE_END, AST_RWLIST_UNLOCK, AST_RWLIST_WRLOCK, ast_verb, and ast_bridge_technology::name.
Referenced by dahdi_native_unload(), and unload_module().
 {
    struct ast_bridge_technology *current;
    AST_RWLIST_WRLOCK(&bridge_technologies);
    /* Ensure the bridge technology is registered before removing it */
    AST_RWLIST_TRAVERSE_SAFE_BEGIN(&bridge_technologies, current, entry) {
       if (current == technology) {
          AST_RWLIST_REMOVE_CURRENT(entry);
          ast_verb(2, "Unregistered bridge technology %s\n", technology->name);
          break;
       }
    }
    AST_RWLIST_TRAVERSE_SAFE_END;
    AST_RWLIST_UNLOCK(&bridge_technologies);
    return current ? 0 : -1;
 }
ast_bridge_technology_unsuspend()
void ast_bridge_technology_unsuspend (struct ast_bridge_technology * technology)
Unsuspend a bridge technology.
Parameters
technology The bridge technology to unsuspend
Example usage:
ast_bridge_technology_unsuspend(&simple_bridge_tech);
This makes the bridge technology simple_bridge_tech considered when creating a new bridge again.
Definition at line 3113 of file bridge.c.
References ast_bridge_technology::suspended.
Referenced by handle_bridge_technology_suspend(), and handle_manager_bridge_tech_suspend().
 {
    /*
     * XXX We may want the act of unsuspending a bridge technology
     * to prod all existing bridges to see if they should start
     * using it.
     */
    technology->suspended = 0;
 }