Asterisk - The Open Source Telephony Project: slinfactory.h File Reference
slinfactory.h File Reference
A machine to gather up arbitrary frames and convert them to raw slinear on demand.
#include "asterisk/format.h"
Data Structures
struct ast_slinfactory
Macros
#define AST_SLINFACTORY_MAX_HOLD 1280
Functions
unsigned int ast_slinfactory_available (const struct ast_slinfactory *sf)
Retrieve number of samples currently in a slinfactory.
void ast_slinfactory_destroy (struct ast_slinfactory *sf)
Destroy the contents of a slinfactory.
int ast_slinfactory_feed (struct ast_slinfactory *sf, struct ast_frame *f)
Feed audio into a slinfactory.
void ast_slinfactory_flush (struct ast_slinfactory *sf)
Flush the contents of a slinfactory.
void ast_slinfactory_init (struct ast_slinfactory *sf)
Initialize a slinfactory.
int ast_slinfactory_init_with_format (struct ast_slinfactory *sf, struct ast_format *slin_out)
Initialize a slinfactory.
int ast_slinfactory_read (struct ast_slinfactory *sf, short *buf, size_t samples)
Read samples from a slinfactory.
Detailed Description
A machine to gather up arbitrary frames and convert them to raw slinear on demand.
Definition in file slinfactory.h.
Macro Definition Documentation
AST_SLINFACTORY_MAX_HOLD
#define AST_SLINFACTORY_MAX_HOLD 1280
Definition at line 33 of file slinfactory.h.
Referenced by ast_slinfactory_read().
Function Documentation
ast_slinfactory_available()
unsigned int ast_slinfactory_available (const struct ast_slinfactory * sf)
Retrieve number of samples currently in a slinfactory.
Parameters
sf The slinfactory to peek into
Returns
Number of samples in slinfactory
Definition at line 199 of file slinfactory.c.
References ast_slinfactory::size.
Referenced by ast_audiohook_write_frame(), audio_audiohook_write_list(), audiohook_read_frame_both(), audiohook_read_frame_single(), softmix_bridge_write_voice(), and softmix_process_read_audio().
 {
    return sf->size;
 }
ast_slinfactory_destroy()
void ast_slinfactory_destroy (struct ast_slinfactory * sf)
Destroy the contents of a slinfactory.
Parameters
sf The slinfactory that is no longer needed
This function will free any memory allocated for the contents of the slinfactory. It does not free the slinfactory itself. If the sf is malloc'd, then it must be explicitly free'd after calling this function.
Returns
Nothing
Definition at line 58 of file slinfactory.c.
References ao2_cleanup, ast_frfree, AST_LIST_REMOVE_HEAD, ast_translator_free_path(), ast_slinfactory::format, NULL, ast_slinfactory::output_format, and ast_slinfactory::trans.
Referenced by ast_audiohook_destroy(), audiohook_set_internal_rate(), set_softmix_bridge_data(), and softmix_bridge_leave().
 {
    struct ast_frame *f;
    if (sf->trans) {
       ast_translator_free_path(sf->trans);
       sf->trans = NULL;
    }
    while ((f = AST_LIST_REMOVE_HEAD(&sf->queue, frame_list))) {
       ast_frfree(f);
    }
    ao2_cleanup(sf->output_format);
    sf->output_format = NULL;
    ao2_cleanup(sf->format);
    sf->format = NULL;
 }
ast_slinfactory_feed()
int ast_slinfactory_feed (struct ast_slinfactory * sf, struct ast_frame * f)
Feed audio into a slinfactory.
Parameters
sf The slinfactory to feed into
f Frame containing audio to feed in
Returns
Number of frames currently in factory
Definition at line 77 of file slinfactory.c.
References ao2_replace, ast_format_cmp(), AST_FORMAT_CMP_NOT_EQUAL, ast_format_get_codec_id(), ast_format_get_name(), ast_frdup, ast_frfree, ast_frisolate, AST_LIST_INSERT_TAIL, AST_LIST_NEXT, AST_LIST_TRAVERSE, ast_log, ast_translate(), ast_translator_build_path(), ast_translator_free_path(), ast_frame::data, ast_slinfactory::format, ast_frame_subclass::format, LOG_WARNING, NULL, ast_slinfactory::output_format, ast_frame::ptr, ast_frame::samples, ast_slinfactory::size, ast_frame::subclass, and ast_slinfactory::trans.
Referenced by ast_audiohook_write_frame(), and softmix_bridge_write_voice().
 {
    struct ast_frame *begin_frame = f, *duped_frame = NULL, *frame_ptr;
    unsigned int x = 0;
    /* In some cases, we can be passed a frame which has no data in it, but
     * which has a positive number of samples defined. Once such situation is
     * when a jitter buffer is in use and the jitter buffer interpolates a frame.
     * The frame it produces has data set to NULL, datalen set to 0, and samples
     * set to either 160 or 240.
     */
    if (!f->data.ptr) {
       return 0;
    }
    if (ast_format_cmp(f->subclass.format, sf->output_format) == AST_FORMAT_CMP_NOT_EQUAL) {
       if (sf->trans && (ast_format_cmp(f->subclass.format, sf->format) == AST_FORMAT_CMP_NOT_EQUAL)) {
          ast_translator_free_path(sf->trans);
          sf->trans = NULL;
       }
       if (!sf->trans) {
          if (!(sf->trans = ast_translator_build_path(sf->output_format, f->subclass.format))) {
             ast_log(LOG_WARNING, "Cannot build a path from %s (%u)to %s (%u)\n",
                ast_format_get_name(f->subclass.format),
                ast_format_get_codec_id(f->subclass.format),
                ast_format_get_name(sf->output_format),
                ast_format_get_codec_id(sf->output_format));
             return 0;
          }
          ao2_replace(sf->format, f->subclass.format);
       }
       if (!(begin_frame = ast_translate(sf->trans, f, 0))) {
          return 0;
       }
       if (!(duped_frame = ast_frisolate(begin_frame))) {
          return 0;
       }
       if (duped_frame != begin_frame) {
          ast_frfree(begin_frame);
       }
    } else {
       if (sf->trans) {
          ast_translator_free_path(sf->trans);
          sf->trans = NULL;
       }
       if (!(duped_frame = ast_frdup(f)))
          return 0;
    }
    AST_LIST_TRAVERSE(&sf->queue, frame_ptr, frame_list) {
       x++;
    }
    /* if the frame was translated, the translator may have returned multiple
       frames, so process each of them
    */
    for (begin_frame = duped_frame; begin_frame; begin_frame = AST_LIST_NEXT(begin_frame, frame_list)) {
       AST_LIST_INSERT_TAIL(&sf->queue, begin_frame, frame_list);
       sf->size += begin_frame->samples;
    }
    return x;
 }
ast_slinfactory_flush()
void ast_slinfactory_flush (struct ast_slinfactory * sf)
Flush the contents of a slinfactory.
Parameters
sf The slinfactory to flush
Returns
Nothing
Definition at line 204 of file slinfactory.c.
References ast_frfree, AST_LIST_REMOVE_HEAD, ast_translator_free_path(), ast_slinfactory::hold, ast_slinfactory::holdlen, NULL, ast_slinfactory::offset, ast_slinfactory::size, and ast_slinfactory::trans.
Referenced by ast_audiohook_write_frame(), clear_talking(), and softmix_bridge_write_voice().
 {
    struct ast_frame *fr = NULL;
    if (sf->trans) {
       ast_translator_free_path(sf->trans);
       sf->trans = NULL;
    }
    while ((fr = AST_LIST_REMOVE_HEAD(&sf->queue, frame_list)))
       ast_frfree(fr);
    sf->size = sf->holdlen = 0;
    sf->offset = sf->hold;
    return;
 }
ast_slinfactory_init()
void ast_slinfactory_init (struct ast_slinfactory * sf)
Initialize a slinfactory.
Parameters
sf The slinfactory to initialize
Returns
Nothing
Definition at line 39 of file slinfactory.c.
References ao2_bump, ast_format_slin, ast_slinfactory::hold, ast_slinfactory::offset, and ast_slinfactory::output_format.
 {
    memset(sf, 0, sizeof(*sf));
    sf->offset = sf->hold;
    sf->output_format = ao2_bump(ast_format_slin);
 }
ast_slinfactory_init_with_format()
int ast_slinfactory_init_with_format (struct ast_slinfactory * sf, struct ast_format * slin_out)
Initialize a slinfactory.
Parameters
sf The slinfactory to initialize
slin_out the slinear output format desired.
Returns
0 on success, non-zero on failure
Definition at line 46 of file slinfactory.c.
References ao2_bump, ast_format_cache_is_slinear(), ast_slinfactory::hold, ast_slinfactory::offset, and ast_slinfactory::output_format.
Referenced by audiohook_set_internal_rate(), and set_softmix_bridge_data().
 {
    memset(sf, 0, sizeof(*sf));
    sf->offset = sf->hold;
    if (!ast_format_cache_is_slinear(slin_out)) {
       return -1;
    }
    sf->output_format = ao2_bump(slin_out);
    return 0;
 }
ast_slinfactory_read()
int ast_slinfactory_read (struct ast_slinfactory * sf, short * buf, size_t samples)
Read samples from a slinfactory.
Parameters
sf The slinfactory to read from
buf Buffer to put samples into
samples Number of samples wanted
Returns
Number of samples read
Definition at line 145 of file slinfactory.c.
References ast_frfree, AST_LIST_REMOVE_HEAD, AST_SLINFACTORY_MAX_HOLD, buf, ast_frame::data, ast_slinfactory::hold, ast_slinfactory::holdlen, ast_slinfactory::offset, ast_frame::offset, ast_frame::ptr, ast_frame::samples, and ast_slinfactory::size.
Referenced by audio_audiohook_write_list(), audiohook_read_frame_both(), audiohook_read_frame_single(), and softmix_process_read_audio().
 {
    struct ast_frame *frame_ptr;
    unsigned int sofar = 0, ineed, remain;
    short *frame_data, *offset = buf;
    while (sofar < samples) {
       ineed = samples - sofar;
       if (sf->holdlen) {
          if (sf->holdlen <= ineed) {
             memcpy(offset, sf->offset, sf->holdlen * sizeof(*offset));
             sofar += sf->holdlen;
             offset += sf->holdlen;
             sf->holdlen = 0;
             sf->offset = sf->hold;
          } else {
             remain = sf->holdlen - ineed;
             memcpy(offset, sf->offset, ineed * sizeof(*offset));
             sofar += ineed;
             sf->offset += ineed;
             sf->holdlen = remain;
          }
          continue;
       }
       if ((frame_ptr = AST_LIST_REMOVE_HEAD(&sf->queue, frame_list))) {
          frame_data = frame_ptr->data.ptr;
          if (frame_ptr->samples <= ineed) {
             memcpy(offset, frame_data, frame_ptr->samples * sizeof(*offset));
             sofar += frame_ptr->samples;
             offset += frame_ptr->samples;
          } else {
             remain = frame_ptr->samples - ineed;
             memcpy(offset, frame_data, ineed * sizeof(*offset));
             sofar += ineed;
             frame_data += ineed;
             if (remain > (AST_SLINFACTORY_MAX_HOLD - sf->holdlen)) {
                remain = AST_SLINFACTORY_MAX_HOLD - sf->holdlen;
             }
             memcpy(sf->hold, frame_data, remain * sizeof(*offset));
             sf->holdlen = remain;
          }
          ast_frfree(frame_ptr);
       } else {
          break;
       }
    }
    sf->size -= sofar;
    return sofar;
 }