Asterisk - The Open Source Telephony Project: db.c File Reference
utils/db1-ast/db/db.c File Reference
#include <sys/types.h>
#include <errno.h>
#include <fcntl.h>
#include <stddef.h>
#include <stdio.h>
#include "../include/db.h"
Macros
#define DB_FLAGS (DB_LOCK | DB_SHMEM | DB_TXN)
#define USE_OPEN_FLAGS
Functions
void __dbpanic (DB *dbp)
static int __dberr __P ((void))
DB * dbopen (char *fname, int flags, int mode, DBTYPE type, const void *openinfo) const
Macro Definition Documentation
DB_FLAGS
#define DB_FLAGS (DB_LOCK | DB_SHMEM | DB_TXN)
Referenced by dbopen().
USE_OPEN_FLAGS
#define USE_OPEN_FLAGS
Value:
(O_CREAT | O_EXCL | O_EXLOCK | O_NONBLOCK | O_RDONLY |      \
    O_RDWR | O_SHLOCK | O_TRUNC)
Referenced by dbopen().
Function Documentation
__dbpanic()
void __dbpanic (DB * dbp)
Definition at line 89 of file utils/db1-ast/db/db.c.
References __P().
Referenced by __bt_split().
 {
    /* The only thing that can succeed is a close. */
    dbp->del = (int (*)__P((const struct __db *,
             const DBT *, u_int))) __dberr;
    dbp->get = (int (*)__P((const struct __db *,
             const DBT *, DBT *, u_int))) __dberr;
    dbp->put = (int (*)__P((const struct __db *,
             DBT *, const DBT *, u_int))) __dberr;
    dbp->seq = (int (*)__P((const struct __db *,
             DBT *, DBT *, u_int))) __dberr;
    dbp->sync = (int (*)__P((const struct __db *, u_int))) __dberr;
    dbp->fd = (int (*)__P((const struct __db *))) __dberr;
 }
__P()
static int __dberr __P ((void)) static
Definition at line 77 of file utils/db1-ast/db/db.c.
References RET_ERROR.
Referenced by __dbpanic().
 {
    return (RET_ERROR);
 }
dbopen()
DB* dbopen (char * fname, int flags, int mode, DBTYPE type, const void * openinfo) const
Definition at line 48 of file utils/db1-ast/db/db.c.
References __bt_open(), __hash_open(), __rec_open(), DB_BTREE, DB_FLAGS, DB_HASH, DB_RECNO, errno, NULL, type, and USE_OPEN_FLAGS.
Referenced by convert_bdb_to_sqlite3(), create_bdb_astdb(), and mssql_connect().
 {
 #define  DB_FLAGS (DB_LOCK | DB_SHMEM | DB_TXN)
 #define  USE_OPEN_FLAGS                   \
    (O_CREAT | O_EXCL | O_EXLOCK | O_NONBLOCK | O_RDONLY |      \
     O_RDWR | O_SHLOCK | O_TRUNC)
    if ((flags & ~(USE_OPEN_FLAGS | DB_FLAGS)) == 0)
       switch (type) {
       case DB_BTREE:
          return (__bt_open(fname, flags & USE_OPEN_FLAGS,
              mode, openinfo, flags & DB_FLAGS));
       case DB_HASH:
          return (__hash_open(fname, flags & USE_OPEN_FLAGS,
              mode, openinfo, flags & DB_FLAGS));
       case DB_RECNO:
          return (__rec_open(fname, flags & USE_OPEN_FLAGS,
              mode, openinfo, flags & DB_FLAGS));
       }
    errno = EINVAL;
    return (NULL);
 }