Asterisk - The Open Source Telephony Project: test_media_cache.c File Reference
test_media_cache.c File Reference
Tests for the media cache API.
#include "asterisk.h"
#include "asterisk/utils.h"
#include "asterisk/module.h"
#include "asterisk/test.h"
#include "asterisk/bucket.h"
#include "asterisk/media_cache.h"
Macros
#define CATEGORY "/main/media_cache/"
#define INVALID_RESOURCE "httptest://localhost:8088/test_media_cache/bad.wav"
#define INVALID_SCHEME "foo://localhost:8088/test_media_cache/monkeys.wav"
#define NO_SCHEME "localhost:8088/test_media_cache/monkeys.wav"
#define VALID_RESOURCE "httptest://localhost:8088/test_media_cache/monkeys.wav"
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
AST_TEST_DEFINE (exists_nominal)
AST_TEST_DEFINE (exists_off_nominal)
AST_TEST_DEFINE (create_update_nominal)
AST_TEST_DEFINE (create_update_off_nominal)
AST_TEST_DEFINE (create_update_metadata)
static int bucket_http_test_wizard_create (const struct ast_sorcery *sorcery, void *data, void *object)
static int bucket_http_test_wizard_delete (const struct ast_sorcery *sorcery, void *data, void *object)
static void * bucket_http_test_wizard_retrieve_id (const struct ast_sorcery *sorcery, void *data, const char *type, const char *id)
static int bucket_http_test_wizard_update (const struct ast_sorcery *sorcery, void *data, void *object)
static int load_module (void)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Media Cache Tests" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, }
static const struct ast_module_info * ast_module_info = &__mod_info
static struct ast_sorcery_wizard bucket_file_test_wizard
static struct ast_sorcery_wizard bucket_test_wizard
Detailed Description
Tests for the media cache API.
Author
Matt Jordan <mjordan@digium.com>
Definition in file test_media_cache.c.
Macro Definition Documentation
CATEGORY
#define CATEGORY "/main/media_cache/"
The unit test category
Definition at line 42 of file test_media_cache.c.
Referenced by AST_TEST_DEFINE().
INVALID_RESOURCE
#define INVALID_RESOURCE "httptest://localhost:8088/test_media_cache/bad.wav"
An 'invalid' resource for the test bucket behind the media cache facade
Definition at line 48 of file test_media_cache.c.
Referenced by AST_TEST_DEFINE().
INVALID_SCHEME
#define INVALID_SCHEME "foo://localhost:8088/test_media_cache/monkeys.wav"
An 'invalid' scheme, not mapping to a valid bucket backend
Definition at line 51 of file test_media_cache.c.
Referenced by AST_TEST_DEFINE().
NO_SCHEME
#define NO_SCHEME "localhost:8088/test_media_cache/monkeys.wav"
A URI with no scheme
Definition at line 54 of file test_media_cache.c.
Referenced by AST_TEST_DEFINE().
VALID_RESOURCE
#define VALID_RESOURCE "httptest://localhost:8088/test_media_cache/monkeys.wav"
A 'valid' resource for the test bucket behind the media cache facade
Definition at line 45 of file test_media_cache.c.
Referenced by AST_TEST_DEFINE(), bucket_http_test_wizard_create(), bucket_http_test_wizard_delete(), bucket_http_test_wizard_retrieve_id(), and bucket_http_test_wizard_update().
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 413 of file test_media_cache.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 413 of file test_media_cache.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 413 of file test_media_cache.c.
AST_TEST_DEFINE() [1/5]
AST_TEST_DEFINE (exists_nominal)
Definition at line 134 of file test_media_cache.c.
References ast_media_cache_exists(), AST_TEST_NOT_RUN, AST_TEST_PASS, CATEGORY, sip_to_pjsip::info(), INVALID_RESOURCE, TEST_EXECUTE, TEST_INIT, and VALID_RESOURCE.
 {
    int res;
    switch (cmd) {
    case TEST_INIT:
       info->name = __func__;
       info->category = CATEGORY;
       info->summary = "Test nominal existance of resources in the cache";
       info->description =
          "This test verifies that if a known resource is in the cache, "
          "calling ast_media_cache_exists will return logical True. If "
          "a resource does not exist, the same function call will return "
          "logical False.";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    res = ast_media_cache_exists(INVALID_RESOURCE);
    ast_test_validate(test, res == 0);
    res = ast_media_cache_exists(VALID_RESOURCE);
    ast_test_validate(test, res == 1);
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [2/5]
AST_TEST_DEFINE (exists_off_nominal)
Definition at line 162 of file test_media_cache.c.
References ast_media_cache_exists(), AST_TEST_NOT_RUN, AST_TEST_PASS, CATEGORY, sip_to_pjsip::info(), INVALID_SCHEME, NO_SCHEME, NULL, TEST_EXECUTE, and TEST_INIT.
 {
    int res;
    switch (cmd) {
    case TEST_INIT:
       info->name = __func__;
       info->category = CATEGORY;
       info->summary = "Test off nominal existance of resources in the cache";
       info->description =
          "This test verifies that checking for bad resources (NULL, bad "
          "scheme, etc.) does not result in false positivies.";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    res = ast_media_cache_exists("");
    ast_test_validate(test, res != 1);
    res = ast_media_cache_exists(NULL);
    ast_test_validate(test, res != 1);
    res = ast_media_cache_exists(NO_SCHEME);
    ast_test_validate(test, res != 1);
    res = ast_media_cache_exists(INVALID_SCHEME);
    ast_test_validate(test, res != 1);
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [3/5]
AST_TEST_DEFINE (create_update_nominal)
Definition at line 194 of file test_media_cache.c.
References ast_media_cache_create_or_update(), ast_media_cache_retrieve(), AST_TEST_FAIL, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_test_status_update, CATEGORY, ast_sorcery_wizard::close, sip_to_pjsip::info(), NULL, PATH_MAX, TEST_EXECUTE, TEST_INIT, and VALID_RESOURCE.
 {
    int res;
    char file_path[PATH_MAX];
    char tmp_path_one[PATH_MAX] = "/tmp/test-media-cache-XXXXXX";
    char tmp_path_two[PATH_MAX] = "/tmp/test-media-cache-XXXXXX";
    int fd;
    switch (cmd) {
    case TEST_INIT:
       info->name = __func__;
       info->category = CATEGORY;
       info->summary = "Test nominal creation/updating of a resource";
       info->description =
          "This test creates a resource and associates it with a file. "
          "It then updates the resource with a new file. In both cases, "
          "the test verifies that the resource is associated with the "
          "file.";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    /* Create two local files to associate with a resource */
    fd = mkstemp(tmp_path_one);
    if (fd < 0) {
       ast_test_status_update(test, "Failed to create first tmp file: %s\n",
          tmp_path_one);
       return AST_TEST_FAIL;
    }
    /* We don't need anything in the file */
    close(fd);
    fd = mkstemp(tmp_path_two);
    if (fd < 0) {
       ast_test_status_update(test, "Failed to create second tmp file: %s\n",
          tmp_path_two);
       return AST_TEST_FAIL;
    }
    close(fd);
    ast_test_status_update(test, "Creating resource with %s\n", tmp_path_one);
    res = ast_media_cache_create_or_update(VALID_RESOURCE, tmp_path_one, NULL);
    ast_test_validate(test, res == 0);
    res = ast_media_cache_retrieve(VALID_RESOURCE, NULL, file_path, PATH_MAX);
    ast_test_status_update(test, "Got %s for first file path\n", file_path);
    ast_test_validate(test, res == 0);
    ast_test_validate(test, strcmp(file_path, tmp_path_one) == 0);
    ast_test_status_update(test, "Creating resource with %s\n", tmp_path_two);
    res = ast_media_cache_create_or_update(VALID_RESOURCE, tmp_path_two, NULL);
    ast_test_validate(test, res == 0);
    res = ast_media_cache_retrieve(VALID_RESOURCE, NULL, file_path, PATH_MAX);
    ast_test_status_update(test, "Got %s for second file path\n", file_path);
    ast_test_validate(test, res == 0);
    ast_test_validate(test, strcmp(file_path, tmp_path_two) == 0);
    unlink(tmp_path_one);
    unlink(tmp_path_two);
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [4/5]
AST_TEST_DEFINE (create_update_off_nominal)
Definition at line 259 of file test_media_cache.c.
References ast_media_cache_create_or_update(), AST_TEST_FAIL, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_test_status_update, CATEGORY, ast_sorcery_wizard::close, sip_to_pjsip::info(), INVALID_RESOURCE, INVALID_SCHEME, NO_SCHEME, NULL, PATH_MAX, TEST_EXECUTE, TEST_INIT, and VALID_RESOURCE.
 {
    int res;
    char tmp_path[PATH_MAX] = "/tmp/test-media-cache-XXXXXX";
    int fd;
    switch (cmd) {
    case TEST_INIT:
       info->name = __func__;
       info->category = CATEGORY;
       info->summary = "Test off nominal creation/updating of a resource";
       info->description =
          "Test creation/updating of a resource with a variety of invalid\n"
          "inputs.";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    /* Create two local files to associate with a resource */
    fd = mkstemp(tmp_path);
    if (fd < 0) {
       ast_test_status_update(test, "Failed to create first tmp file: %s\n",
          tmp_path);
       return AST_TEST_FAIL;
    }
    /* We don't need anything in the file */
    close(fd);
    res = ast_media_cache_create_or_update(VALID_RESOURCE, NULL, NULL);
    ast_test_validate(test, res != 0);
    res = ast_media_cache_create_or_update(VALID_RESOURCE, "", NULL);
    ast_test_validate(test, res != 0);
    res = ast_media_cache_create_or_update(VALID_RESOURCE, "I don't exist", NULL);
    ast_test_validate(test, res != 0);
    res = ast_media_cache_create_or_update(INVALID_RESOURCE, tmp_path, NULL);
    ast_test_validate(test, res != 0);
    res = ast_media_cache_create_or_update(INVALID_SCHEME, tmp_path, NULL);
    ast_test_validate(test, res != 0);
    res = ast_media_cache_create_or_update(NO_SCHEME, tmp_path, NULL);
    ast_test_validate(test, res != 0);
    unlink(tmp_path);
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [5/5]
AST_TEST_DEFINE (create_update_metadata)
Definition at line 311 of file test_media_cache.c.
References ast_media_cache_create_or_update(), ast_media_cache_retrieve(), ast_media_cache_retrieve_metadata(), AST_TEST_FAIL, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_test_status_update, ast_variable_list_append, ast_variable_new, CATEGORY, sip_to_pjsip::info(), NULL, PATH_MAX, TEST_EXECUTE, TEST_INIT, tmp(), and VALID_RESOURCE.
 {
    int res;
    char tmp_path[PATH_MAX] = "/tmp/test-media-cache-XXXXXX";
    char file_path[PATH_MAX];
    char actual_metadata[32];
    struct ast_variable *meta_list = NULL;
    struct ast_variable *tmp;
    int fd;
    switch (cmd) {
    case TEST_INIT:
       info->name = __func__;
       info->category = CATEGORY;
       info->summary = "Test nominal creation/updating of a resource";
       info->description =
          "This test creates a resource and associates it with a file. "
          "It then updates the resource with a new file. In both cases, "
          "the test verifies that the resource is associated with the "
          "file.";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    /* Create two local files to associate with a resource */
    fd = mkstemp(tmp_path);
    if (fd < 0) {
       ast_test_status_update(test, "Failed to create first tmp file: %s\n",
          tmp_path);
       return AST_TEST_FAIL;
    }
    /* We don't need anything in the file */
    close(fd);
    tmp = ast_variable_new("meta1", "value1", __FILE__);
    if (!tmp) {
       ast_test_status_update(test, "Failed to create metadata 1 for test\n");
       return AST_TEST_FAIL;
    }
    ast_variable_list_append(&meta_list, tmp);
    tmp = ast_variable_new("meta2", "value2", __FILE__);
    if (!tmp) {
       ast_test_status_update(test, "Failed to create metadata 2 for test\n");
       return AST_TEST_FAIL;
    }
    ast_variable_list_append(&meta_list, tmp);
    res = ast_media_cache_create_or_update(VALID_RESOURCE, tmp_path, meta_list);
    ast_test_validate(test, res == 0);
    res = ast_media_cache_retrieve(VALID_RESOURCE, NULL, file_path, PATH_MAX);
    ast_test_status_update(test, "Got %s for second file path\n", file_path);
    ast_test_validate(test, res == 0);
    ast_test_validate(test, strcmp(file_path, tmp_path) == 0);
    res = ast_media_cache_retrieve_metadata(VALID_RESOURCE, "meta1",
       actual_metadata, sizeof(actual_metadata));
    ast_test_validate(test, res == 0);
    ast_test_validate(test, strcmp(actual_metadata, "value1") == 0);
    res = ast_media_cache_retrieve_metadata(VALID_RESOURCE, "meta2",
       actual_metadata, sizeof(actual_metadata));
    ast_test_validate(test, res == 0);
    ast_test_validate(test, strcmp(actual_metadata, "value2") == 0);
    unlink(tmp_path);
    return AST_TEST_PASS;
 }
bucket_http_test_wizard_create()
static int bucket_http_test_wizard_create (const struct ast_sorcery * sorcery, void * data, void * object) static
Definition at line 60 of file test_media_cache.c.
References ast_sorcery_object_get_id(), and VALID_RESOURCE.
 {
    if (!strcmp(ast_sorcery_object_get_id(object), VALID_RESOURCE)) {
       return 0;
    }
    return -1;
 }
bucket_http_test_wizard_delete()
static int bucket_http_test_wizard_delete (const struct ast_sorcery * sorcery, void * data, void * object) static
Definition at line 109 of file test_media_cache.c.
References ast_sorcery_object_get_id(), and VALID_RESOURCE.
 {
    if (!strcmp(ast_sorcery_object_get_id(object), VALID_RESOURCE)) {
       return 0;
    }
    return -1;
 }
bucket_http_test_wizard_retrieve_id()
static void* bucket_http_test_wizard_retrieve_id (const struct ast_sorcery * sorcery, void * data, const char * type, const char * id) static
Definition at line 88 of file test_media_cache.c.
References ast_bucket_file_alloc(), ast_bucket_file_temporary_create(), NULL, and VALID_RESOURCE.
 {
    struct ast_bucket_file *bucket_file;
    if (!strcmp(type, "file") && !strcmp(id, VALID_RESOURCE)) {
       bucket_file = ast_bucket_file_alloc(id);
       if (!bucket_file) {
          return NULL;
       }
       ast_bucket_file_temporary_create(bucket_file);
       return bucket_file;
    }
    return NULL;
 }
bucket_http_test_wizard_update()
static int bucket_http_test_wizard_update (const struct ast_sorcery * sorcery, void * data, void * object) static
Definition at line 74 of file test_media_cache.c.
References ast_sorcery_object_get_id(), and VALID_RESOURCE.
 {
    if (!strcmp(ast_sorcery_object_get_id(object), VALID_RESOURCE)) {
       return 0;
    }
    return -1;
 }
load_module()
static int load_module (void) static
Definition at line 395 of file test_media_cache.c.
References ast_bucket_scheme_register, ast_log, AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, AST_TEST_REGISTER, LOG_ERROR, and NULL.
 {
    if (ast_bucket_scheme_register("httptest", &bucket_test_wizard,
       &bucket_file_test_wizard, NULL, NULL)) {
       ast_log(LOG_ERROR, "Failed to register Bucket HTTP test wizard scheme implementation\n");
       return AST_MODULE_LOAD_DECLINE;
    }
    AST_TEST_REGISTER(exists_nominal);
    AST_TEST_REGISTER(exists_off_nominal);
    AST_TEST_REGISTER(create_update_nominal);
    AST_TEST_REGISTER(create_update_metadata);
    AST_TEST_REGISTER(create_update_off_nominal);
    return AST_MODULE_LOAD_SUCCESS;
 }
unload_module()
static int unload_module (void) static
Definition at line 383 of file test_media_cache.c.
References AST_TEST_UNREGISTER.
 {
    AST_TEST_UNREGISTER(exists_nominal);
    AST_TEST_UNREGISTER(exists_off_nominal);
    AST_TEST_UNREGISTER(create_update_nominal);
    AST_TEST_UNREGISTER(create_update_metadata);
    AST_TEST_UNREGISTER(create_update_off_nominal);
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Media Cache Tests" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, } static
Definition at line 413 of file test_media_cache.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 413 of file test_media_cache.c.
bucket_file_test_wizard
struct ast_sorcery_wizard bucket_file_test_wizard static
Definition at line 126 of file test_media_cache.c.
bucket_test_wizard
struct ast_sorcery_wizard bucket_test_wizard static
Definition at line 119 of file test_media_cache.c.