Asterisk - The Open Source Telephony Project: stasis_app.h File Reference
stasis_app.h File Reference
Stasis Application API. See Stasis Application API for detailed documentation.
#include "asterisk/channel.h"
Data Structures
struct stasis_app_control_rule
Rule to check to see if an operation is allowed.
struct stasis_app_event_source
Event source information and callbacks.
enum stasis_app_user_event_res {
STASIS_APP_USER_OK, STASIS_APP_USER_APP_NOT_FOUND, STASIS_APP_USER_EVENT_SOURCE_NOT_FOUND, STASIS_APP_USER_EVENT_SOURCE_BAD_SCHEME,
STASIS_APP_USER_USEREVENT_INVALID, STASIS_APP_USER_INTERNAL_ERROR
}
Return code for stasis_app_user_event.
enum stasis_app_subscribe_res {
STASIS_ASR_OK, STASIS_ASR_APP_NOT_FOUND, STASIS_ASR_EVENT_SOURCE_NOT_FOUND, STASIS_ASR_EVENT_SOURCE_BAD_SCHEME,
STASIS_ASR_INTERNAL_ERROR
}
Return code for stasis_app_[un]subscribe.
typedef void(* stasis_app_cb) (void *data, const char *app_name, struct ast_json *message)
Callback for Stasis application handler.
struct ao2_container * stasis_app_get_all (void)
Gets the names of all registered Stasis applications.
struct stasis_app * stasis_app_get_by_name (const char *name)
Retrieve a handle to a Stasis application by its name.
int stasis_app_register (const char *app_name, stasis_app_cb handler, void *data)
Register a new Stasis application.
int stasis_app_register_all (const char *app_name, stasis_app_cb handler, void *data)
Register a new Stasis application that receives all Asterisk events.
void stasis_app_unregister (const char *app_name)
Unregister a Stasis application.
int stasis_app_send (const char *app_name, struct ast_json *message)
Send a message to the given Stasis application.
const char * stasis_app_name (const struct stasis_app *app)
Retrieve an application's name.
struct ast_json * stasis_app_object_to_json (struct stasis_app *app)
Return the JSON representation of a Stasis application.
struct ast_json * stasis_app_to_json (const char *app_name)
Return the JSON representation of a Stasis application.
void stasis_app_register_event_source (struct stasis_app_event_source *obj)
Register an application event source.
void stasis_app_register_event_sources (void)
Register core event sources.
void stasis_app_unregister_event_source (struct stasis_app_event_source *obj)
Unregister an application event source.
void stasis_app_unregister_event_sources (void)
Unregister core event sources.
enum stasis_app_user_event_res stasis_app_user_event (const char *app_name, const char *event_name, const char **source_uris, int sources_count, struct ast_json *json_variables)
Generate a Userevent for stasis app (echo to AMI)
enum stasis_app_subscribe_res stasis_app_subscribe (const char *app_name, const char **event_source_uris, int event_sources_count, struct ast_json **json)
Subscribes an application to a list of event sources.
enum stasis_app_subscribe_res stasis_app_unsubscribe (const char *app_name, const char **event_source_uris, int event_sources_count, struct ast_json **json)
Unsubscribes an application from a list of event sources.
enum stasis_app_subscribe_res stasis_app_subscribe_channel (const char *app_name, struct ast_channel *chan)
Directly subscribe an application to a channel.
enum stasis_app_control_channel_result { STASIS_APP_CHANNEL_OKAY = 0, STASIS_APP_CHANNEL_RECORDING }
Result codes used when adding/removing channels to/from bridges.
void stasis_app_control_register_add_rule (struct stasis_app_control *control, struct stasis_app_control_rule *rule)
Registers an add channel to bridge rule.
void stasis_app_control_unregister_add_rule (struct stasis_app_control *control, struct stasis_app_control_rule *rule)
UnRegister an add channel to bridge rule.
void stasis_app_control_register_remove_rule (struct stasis_app_control *control, struct stasis_app_control_rule *rule)
Registers a remove channel from bridge rule.
void stasis_app_control_unregister_remove_rule (struct stasis_app_control *control, struct stasis_app_control_rule *rule)
Unregisters a remove channel from bridge rule.
struct stasis_app_control * stasis_app_control_find_by_channel (const struct ast_channel *chan)
Returns the handler for the given channel.
struct stasis_app_control * stasis_app_control_find_by_channel_id (const char *channel_id)
Returns the handler for the channel with the given id.
struct stasis_app_control * stasis_app_control_create (struct ast_channel *chan)
Creates a control handler for a channel that isn't in a stasis app.
void stasis_app_control_execute_until_exhausted (struct ast_channel *chan, struct stasis_app_control *control)
Act on a stasis app control queue until it is empty.
int stasis_app_control_is_done (struct stasis_app_control *control)
Check if a control is marked as done.
void stasis_app_control_flush_queue (struct stasis_app_control *control)
Flush the control command queue.
const char * stasis_app_control_get_channel_id (const struct stasis_app_control *control)
Returns the uniqueid of the channel associated with this control.
int stasis_app_control_add_role (struct stasis_app_control *control, const char *role)
Apply a bridge role to a channel controlled by a stasis app control.
void stasis_app_control_clear_roles (struct stasis_app_control *control)
Clear bridge roles currently applied to a channel controlled by a stasis app control.
int stasis_app_control_continue (struct stasis_app_control *control, const char *context, const char *extension, int priority)
Exit res_stasis and continue execution in the dialplan.
int stasis_app_control_move (struct stasis_app_control *control, const char *app_name, const char *app_args)
Exit res_stasis and move to another Stasis application.
int stasis_app_control_redirect (struct stasis_app_control *control, const char *endpoint)
Redirect a channel in res_stasis to a particular endpoint.
int stasis_app_control_ring (struct stasis_app_control *control)
Indicate ringing to the channel associated with this control.
int stasis_app_control_ring_stop (struct stasis_app_control *control)
Stop locally generated ringing on the channel associated with this control.
int stasis_app_control_dtmf (struct stasis_app_control *control, const char *dtmf, int before, int between, unsigned int duration, int after)
Send DTMF to the channel associated with this control.
int stasis_app_control_mute (struct stasis_app_control *control, unsigned int direction, enum ast_frame_type frametype)
Mute the channel associated with this control.
int stasis_app_control_unmute (struct stasis_app_control *control, unsigned int direction, enum ast_frame_type frametype)
Unmute the channel associated with this control.
int stasis_app_control_answer (struct stasis_app_control *control)
Answer the channel associated with this control.
int stasis_app_control_set_channel_var (struct stasis_app_control *control, const char *variable, const char *value)
Set a variable on the channel associated with this control to value.
void stasis_app_control_hold (struct stasis_app_control *control)
Place the channel associated with the control on hold.
void stasis_app_control_unhold (struct stasis_app_control *control)
Remove the channel associated with the control from hold.
void stasis_app_control_moh_start (struct stasis_app_control *control, const char *moh_class)
Play music on hold to a channel (does not affect hold status)
void stasis_app_control_moh_stop (struct stasis_app_control *control)
Stop playing music on hold to a channel (does not affect hold status)
void stasis_app_control_silence_start (struct stasis_app_control *control)
Start playing silence to a channel.
void stasis_app_control_silence_stop (struct stasis_app_control *control)
Stop playing silence to a channel.
struct ast_channel_snapshot * stasis_app_control_get_snapshot (const struct stasis_app_control *control)
Returns the most recent snapshot for the associated channel.
void stasis_app_control_publish (struct stasis_app_control *control, struct stasis_message *message)
Publish a message to the control's channel's topic.
struct stasis_topic * ast_app_get_topic (struct stasis_app *app)
Returns the stasis topic for an app.
int stasis_app_control_queue_control (struct stasis_app_control *control, enum ast_control_frame_type frame_type)
Queue a control frame without payload.
struct ast_bridge * stasis_app_bridge_create (const char *type, const char *name, const char *id)
Create a bridge of the specified type.
struct ast_bridge * stasis_app_bridge_create_invisible (const char *type, const char *name, const char *id)
Create an invisible bridge of the specified type.
struct ast_bridge * stasis_app_bridge_find_by_id (const char *bridge_id)
Returns the bridge with the given id.
struct ast_channel * stasis_app_bridge_moh_channel (struct ast_bridge *bridge)
Finds or creates an announcer channel in a bridge that can play music on hold.
int stasis_app_bridge_moh_stop (struct ast_bridge *bridge)
Breaks down MOH channels playing on the bridge created by stasis_app_bridge_moh_channel.
struct ast_channel * stasis_app_bridge_playback_channel_find (struct ast_bridge *bridge)
Finds an existing ARI playback channel in a bridge.
int stasis_app_bridge_playback_channel_add (struct ast_bridge *bridge, struct ast_channel *chan, struct stasis_app_control *control)
Adds a channel to the list of ARI playback channels for bridges.
void stasis_app_bridge_playback_channel_remove (char *bridge_id, struct stasis_app_control *control)
remove channel from list of ARI playback channels for bridges.
int stasis_app_control_add_channel_to_bridge (struct stasis_app_control *control, struct ast_bridge *bridge)
Add a channel to the bridge.
int stasis_app_control_remove_channel_from_bridge (struct stasis_app_control *control, struct ast_bridge *bridge)
Remove a channel from the bridge.
int stasis_app_control_bridge_features_init (struct stasis_app_control *control)
Initialize bridge features into a channel control.
void stasis_app_control_absorb_dtmf_in_bridge (struct stasis_app_control *control, int absorb)
Set whether DTMF from the channel is absorbed instead of passing through to the bridge.
void stasis_app_control_mute_in_bridge (struct stasis_app_control *control, int mute)
Set whether audio from the channel is muted instead of passing through to the bridge.
void stasis_app_control_inhibit_colp_in_bridge (struct stasis_app_control *control, int inhibit_colp)
Set whether COLP frames should be generated when joining the bridge.
struct ast_bridge * stasis_app_get_bridge (struct stasis_app_control *control)
Gets the bridge currently associated with a control object.
void stasis_app_bridge_destroy (const char *bridge_id)
Destroy the bridge.
struct stasis_message_sanitizer * stasis_app_get_sanitizer (void)
Get the Stasis message sanitizer for app_stasis applications.
void stasis_app_channel_set_stasis_end_published (struct ast_channel *chan)
Indicate that this channel has had a StasisEnd published for it.
int stasis_app_channel_is_stasis_end_published (struct ast_channel *chan)
Has this channel had a StasisEnd published on it?
int stasis_app_channel_is_internal (struct ast_channel *chan)
Is this channel internal to Stasis?
int stasis_app_channel_unreal_set_internal (struct ast_channel *chan)
Mark this unreal channel and it's other half as being internal to Stasis.
int stasis_app_channel_set_internal (struct ast_channel *chan)
Mark this channel as being internal to Stasis.
int stasis_app_control_dial (struct stasis_app_control *control, const char *dialstring, unsigned int timeout)
Dial a channel.
void stasis_app_control_shutdown (void)
Let Stasis app internals shut down.
void stasis_app_set_debug (struct stasis_app *app, int debug)
Enable/disable request/response and event logging on an application.
void stasis_app_set_debug_by_name (const char *app_name, int debug)
Enable/disable request/response and event logging on an application.
int stasis_app_get_debug (struct stasis_app *app)
Get debug status of an application.
int stasis_app_get_debug_by_name (const char *app_name)
Get debug status of an application.
void stasis_app_set_global_debug (int debug)
Enable/disable request/response and event logging on all applications.
void stasis_app_to_cli (const struct stasis_app *app, struct ast_cli_args *a)
Dump properties of a stasis_app to the CLI.
struct ast_json * stasis_app_event_filter_to_json (struct stasis_app *app, struct ast_json *json)
Convert and add the app's event type filter(s) to the given json object.
int stasis_app_event_filter_set (struct stasis_app *app, struct ast_json *filter)
Set the application's event type filter.
int stasis_app_event_allowed (const char *app_name, struct ast_json *event)
Check if the given event should be filtered.
Detailed Description
Stasis Application API. See Stasis Application API for detailed documentation.
Author
David M. Lee, II dlee@.nosp@m.digi.nosp@m.um.co.nosp@m.m
Since
12
Definition in file stasis_app.h.
Typedef Documentation
stasis_app_cb
typedef void(* stasis_app_cb) (void *data, const char *app_name, struct ast_json *message)
Callback for Stasis application handler.
The message given to the handler is a borrowed copy. If you want to keep a reference to it, you should use ao2_ref() to keep it around.
Parameters
data Data ptr given when registered.
app_name Name of the application being dispatched to.
message Message to handle. (borrowed copy)
Definition at line 67 of file stasis_app.h.
Enumeration Type Documentation
stasis_app_control_channel_result
enum stasis_app_control_channel_result
Result codes used when adding/removing channels to/from bridges.
Enumerator
STASIS_APP_CHANNEL_OKAY
The channel is okay to be added/removed
STASIS_APP_CHANNEL_RECORDING
The channel is currently recording
Definition at line 777 of file stasis_app.h.
{
    /*! The channel is okay to be added/removed */
    STASIS_APP_CHANNEL_OKAY = 0,
    /*! The channel is currently recording */
    STASIS_APP_CHANNEL_RECORDING
 };
stasis_app_subscribe_res
enum stasis_app_subscribe_res
Return code for stasis_app_[un]subscribe.
Enumerator
STASIS_ASR_OK
STASIS_ASR_APP_NOT_FOUND
STASIS_ASR_EVENT_SOURCE_NOT_FOUND
STASIS_ASR_EVENT_SOURCE_BAD_SCHEME
STASIS_ASR_INTERNAL_ERROR
Definition at line 282 of file stasis_app.h.
{
    STASIS_ASR_OK,
    STASIS_ASR_APP_NOT_FOUND,
    STASIS_ASR_EVENT_SOURCE_NOT_FOUND,
    STASIS_ASR_EVENT_SOURCE_BAD_SCHEME,
    STASIS_ASR_INTERNAL_ERROR,
 };
stasis_app_user_event_res
enum stasis_app_user_event_res
Return code for stasis_app_user_event.
Enumerator
STASIS_APP_USER_OK
STASIS_APP_USER_APP_NOT_FOUND
STASIS_APP_USER_EVENT_SOURCE_NOT_FOUND
STASIS_APP_USER_EVENT_SOURCE_BAD_SCHEME
STASIS_APP_USER_USEREVENT_INVALID
STASIS_APP_USER_INTERNAL_ERROR
Definition at line 255 of file stasis_app.h.
{
    STASIS_APP_USER_OK,
    STASIS_APP_USER_APP_NOT_FOUND,
    STASIS_APP_USER_EVENT_SOURCE_NOT_FOUND,
    STASIS_APP_USER_EVENT_SOURCE_BAD_SCHEME,
    STASIS_APP_USER_USEREVENT_INVALID,
    STASIS_APP_USER_INTERNAL_ERROR,
 };
Function Documentation
ast_app_get_topic()
struct stasis_topic* ast_app_get_topic (struct stasis_app * app)
Returns the stasis topic for an app.
Parameters
app Stasis app to get topic of
Definition at line 1028 of file res/stasis/app.c.
References stasis_app::topic.
Referenced by app_send_end_msg(), send_start_msg_snapshots(), and stasis_app_user_event().
 {
    return app->topic;
 }
stasis_app_bridge_create()
struct ast_bridge* stasis_app_bridge_create (const char * type, const char * name, const char * id)
Create a bridge of the specified type.
Parameters
type The type of bridge to be created
name Optional name to give to the bridge
id Optional Unique ID to give to the bridge
Returns
New bridge.
NULL on error.
Definition at line 851 of file res_stasis.c.
References bridge_create_common().
Referenced by ast_ari_bridges_create(), and ast_ari_bridges_create_with_id().
 {
    return bridge_create_common(type, name, id, 0);
 }
stasis_app_bridge_create_invisible()
struct ast_bridge* stasis_app_bridge_create_invisible (const char * type, const char * name, const char * id)
Create an invisible bridge of the specified type.
Parameters
type The type of bridge to be created
name Optional name to give to the bridge
id Optional Unique ID to give to the bridge
Returns
New bridge.
NULL on error.
Definition at line 856 of file res_stasis.c.
References bridge_create_common().
Referenced by get_dial_bridge().
 {
    return bridge_create_common(type, name, id, 1);
 }
stasis_app_bridge_destroy()
void stasis_app_bridge_destroy (const char * bridge_id)
Destroy the bridge.
Parameters
bridge_id Uniqueid of bridge to be destroyed
Return values
non-zero on failure
zero on success
Definition at line 861 of file res_stasis.c.
References ao2_unlink, ast_bridge_destroy(), and stasis_app_bridge_find_by_id().
Referenced by ast_ari_bridges_destroy().
 {
    struct ast_bridge *bridge = stasis_app_bridge_find_by_id(bridge_id);
    if (!bridge) {
       return;
    }
    ao2_unlink(app_bridges, bridge);
    ast_bridge_destroy(bridge, 0);
 }
stasis_app_bridge_find_by_id()
struct ast_bridge* stasis_app_bridge_find_by_id (const char * bridge_id)
Returns the bridge with the given id.
Parameters
bridge_id Uniqueid of the bridge.
Returns
NULL bridge not created by a Stasis application, or bridge does not exist.
Pointer to bridge.
Definition at line 774 of file res_stasis.c.
References ao2_find, and OBJ_SEARCH_KEY.
Referenced by bridge_find(), find_bridge(), and stasis_app_bridge_destroy().
 {
    return ao2_find(app_bridges, bridge_id, OBJ_SEARCH_KEY);
 }
stasis_app_bridge_moh_channel()
struct ast_channel* stasis_app_bridge_moh_channel (struct ast_bridge * bridge)
Finds or creates an announcer channel in a bridge that can play music on hold.
Parameters
bridge Bridge we want an MOH channel for
Returns
NULL if the music on hold channel fails to be created or join the bridge for any reason.
Pointer to the ;1 end of the announcer channel chain.
Definition at line 629 of file res_stasis.c.
References ao2_find, ao2_lock, ao2_ref, ao2_unlock, ast_channel_get_by_name(), bridge_moh_create(), stasis_app_bridge_channel_wrapper::channel_id, OBJ_NOLOCK, OBJ_SEARCH_KEY, and ast_bridge::uniqueid.
Referenced by ast_ari_bridges_start_moh().
 {
    struct ast_channel *chan;
    struct stasis_app_bridge_channel_wrapper *moh_wrapper;
    ao2_lock(app_bridges_moh);
    moh_wrapper = ao2_find(app_bridges_moh, bridge->uniqueid, OBJ_SEARCH_KEY | OBJ_NOLOCK);
    if (!moh_wrapper) {
       chan = bridge_moh_create(bridge);
    }
    ao2_unlock(app_bridges_moh);
    if (moh_wrapper) {
       chan = ast_channel_get_by_name(moh_wrapper->channel_id);
       ao2_ref(moh_wrapper, -1);
    }
    return chan;
 }
stasis_app_bridge_moh_stop()
int stasis_app_bridge_moh_stop (struct ast_bridge * bridge)
Breaks down MOH channels playing on the bridge created by stasis_app_bridge_moh_channel.
Parameters
bridge Bridge we want to stop the MOH on
Returns
-1 if no moh channel could be found and stopped
0 on success
Definition at line 649 of file res_stasis.c.
References ao2_cleanup, ao2_find, ao2_ref, AST_CAUSE_NORMAL_CLEARING, ast_channel_get_by_name(), ast_moh_stop(), ast_softhangup(), stasis_app_bridge_channel_wrapper::channel_id, OBJ_SEARCH_KEY, OBJ_UNLINK, and ast_bridge::uniqueid.
Referenced by ast_ari_bridges_stop_moh().
 {
    struct stasis_app_bridge_channel_wrapper *moh_wrapper;
    struct ast_channel *chan;
    moh_wrapper = ao2_find(app_bridges_moh, bridge->uniqueid, OBJ_SEARCH_KEY | OBJ_UNLINK);
    if (!moh_wrapper) {
       return -1;
    }
    chan = ast_channel_get_by_name(moh_wrapper->channel_id);
    ao2_ref(moh_wrapper, -1);
    if (!chan) {
       return -1;
    }
    ast_moh_stop(chan);
    ast_softhangup(chan, AST_CAUSE_NORMAL_CLEARING);
    ao2_cleanup(chan);
    return 0;
 }
stasis_app_bridge_playback_channel_add()
int stasis_app_bridge_playback_channel_add (struct ast_bridge * bridge, struct ast_channel * chan, struct stasis_app_control * control)
Adds a channel to the list of ARI playback channels for bridges.
Parameters
bridge Bridge we are adding the playback channel for
chan Channel being added as a playback channel (must be ;1)
Return values
-1 failed to add channel for any reason
0 on success
Definition at line 705 of file res_stasis.c.
References AO2_ALLOC_OPT_LOCK_NOLOCK, ao2_alloc_options, ao2_cleanup, ao2_link, ast_bridge_set_after_callback(), ast_channel_uniqueid(), ast_free, ast_strdup, ast_string_field_init, ast_string_field_set, NULL, playback_after_bridge_cb(), playback_after_bridge_cb_failed(), RAII_VAR, stasis_app_bridge_channel_wrapper_destructor(), and ast_bridge::uniqueid.
Referenced by ari_bridges_play_new().
 {
    RAII_VAR(struct stasis_app_bridge_channel_wrapper *, new_wrapper, NULL, ao2_cleanup);
    char *bridge_id = ast_strdup(bridge->uniqueid);
    if (!bridge_id) {
       return -1;
    }
    if (ast_bridge_set_after_callback(chan,
       playback_after_bridge_cb, playback_after_bridge_cb_failed, bridge_id)) {
       ast_free(bridge_id);
       return -1;
    }
    new_wrapper = ao2_alloc_options(sizeof(*new_wrapper),
       stasis_app_bridge_channel_wrapper_destructor, AO2_ALLOC_OPT_LOCK_NOLOCK);
    if (!new_wrapper) {
       return -1;
    }
    if (ast_string_field_init(new_wrapper, 32)) {
       return -1;
    }
    ast_string_field_set(new_wrapper, bridge_id, bridge->uniqueid);
    ast_string_field_set(new_wrapper, channel_id, ast_channel_uniqueid(chan));
    if (!ao2_link(app_bridges_playback, new_wrapper)) {
       return -1;
    }
    ao2_link(app_controls, control);
    return 0;
 }
stasis_app_bridge_playback_channel_find()
struct ast_channel* stasis_app_bridge_playback_channel_find (struct ast_bridge * bridge)
Finds an existing ARI playback channel in a bridge.
Parameters
bridge Bridge we want to find the playback channel for
Returns
NULL if the playback channel can not be found for any reason.
Pointer to the ;1 end of the playback channel chain.
Definition at line 759 of file res_stasis.c.
References ao2_find, ao2_ref, ast_channel_get_by_name(), stasis_app_bridge_channel_wrapper::channel_id, NULL, OBJ_SEARCH_KEY, and ast_bridge::uniqueid.
Referenced by ari_bridges_handle_play().
 {
    struct stasis_app_bridge_channel_wrapper *playback_wrapper;
    struct ast_channel *chan;
    playback_wrapper = ao2_find(app_bridges_playback, bridge->uniqueid, OBJ_SEARCH_KEY);
    if (!playback_wrapper) {
       return NULL;
    }
    chan = ast_channel_get_by_name(playback_wrapper->channel_id);
    ao2_ref(playback_wrapper, -1);
    return chan;
 }
stasis_app_bridge_playback_channel_remove()
void stasis_app_bridge_playback_channel_remove (char * bridge_id, struct stasis_app_control * control)
remove channel from list of ARI playback channels for bridges.
Parameters
bridge_id The unique ID of the bridge the playback channel is in.
control The app control structure for the playback channel
Definition at line 743 of file res_stasis.c.
References ao2_find, ao2_ref, ao2_unlink, OBJ_SEARCH_KEY, and OBJ_UNLINK.
Referenced by ari_bridges_play_new(), and bridge_channel_control_thread().
 {
    struct stasis_app_bridge_channel_wrapper *wrapper;
    wrapper = ao2_find(app_bridges_playback, bridge_id, OBJ_SEARCH_KEY | OBJ_UNLINK);
    if (wrapper) {
       /* If wrapper is not found, then that means the after bridge callback has been
        * called or is in progress. No need to unlink the control here since that has
        * been done or is about to be done in the after bridge callback
        */
       ao2_unlink(app_controls, control);
       ao2_ref(wrapper, -1);
    }
 }
stasis_app_channel_is_internal()
int stasis_app_channel_is_internal (struct ast_channel * chan)
Is this channel internal to Stasis?
Parameters
chan The channel to check.
Return values
0 No
1 Yes
Definition at line 2322 of file res_stasis.c.
References ast_channel_datastore_find(), ast_channel_lock, ast_channel_unlock, and NULL.
Referenced by bridge_stasis_push().
 {
    struct ast_datastore *datastore;
    int res = 0;
    ast_channel_lock(chan);
    datastore = ast_channel_datastore_find(chan, &stasis_internal_channel_info, NULL);
    if (datastore) {
       res = 1;
    }
    ast_channel_unlock(chan);
    return res;
 }
stasis_app_channel_is_stasis_end_published()
int stasis_app_channel_is_stasis_end_published (struct ast_channel * chan)
Has this channel had a StasisEnd published on it?
Parameters
chan The channel upon which the query rests.
Return values
0 No
1 Yes
Definition at line 1299 of file res_stasis.c.
References ast_channel_datastore_find(), ast_channel_lock, ast_channel_unlock, and NULL.
Referenced by internal_bridge_after_cb(), and stasis_app_exec().
 {
    struct ast_datastore *datastore;
    ast_channel_lock(chan);
    datastore = ast_channel_datastore_find(chan, &set_end_published_info, NULL);
    ast_channel_unlock(chan);
    return datastore ? 1 : 0;
 }
stasis_app_channel_set_internal()
int stasis_app_channel_set_internal (struct ast_channel * chan)
Mark this channel as being internal to Stasis.
Parameters
chan The channel to mark.
Return values
zero Success
non-zero Failure
Definition at line 2311 of file res_stasis.c.
References ast_channel_lock, ast_channel_unlock, and set_internal_datastore().
 {
    int res;
    ast_channel_lock(chan);
    res = set_internal_datastore(chan);
    ast_channel_unlock(chan);
    return res;
 }
stasis_app_channel_set_stasis_end_published()
void stasis_app_channel_set_stasis_end_published (struct ast_channel * chan)
Indicate that this channel has had a StasisEnd published for it.
Parameters
The channel that is exiting Stasis.
Definition at line 1287 of file res_stasis.c.
References ast_channel_datastore_add(), ast_channel_lock, ast_channel_unlock, ast_datastore_alloc, and NULL.
Referenced by bridge_stasis_moving(), and channel_stolen_cb().
 {
    struct ast_datastore *datastore;
    datastore = ast_datastore_alloc(&set_end_published_info, NULL);
    if (datastore) {
       ast_channel_lock(chan);
       ast_channel_datastore_add(chan, datastore);
       ast_channel_unlock(chan);
    }
 }
stasis_app_channel_unreal_set_internal()
int stasis_app_channel_unreal_set_internal (struct ast_channel * chan)
Mark this unreal channel and it's other half as being internal to Stasis.
Parameters
chan The channel to mark.
Return values
zero Success
non-zero Failure
Definition at line 2288 of file res_stasis.c.
References ao2_ref, ao2_unlock, ast_channel_tech_pvt(), ast_channel_unlock, ast_channel_unref, ast_unreal_lock_all(), NULL, and set_internal_datastore().
Referenced by bridge_moh_create(), and prepare_bridge_media_channel().
 {
    struct ast_channel *outchan = NULL, *outowner = NULL;
    int res = 0;
    struct ast_unreal_pvt *unreal_pvt = ast_channel_tech_pvt(chan);
    ao2_ref(unreal_pvt, +1);
    ast_unreal_lock_all(unreal_pvt, &outowner, &outchan);
    if (outowner) {
       res |= set_internal_datastore(outowner);
       ast_channel_unlock(outowner);
       ast_channel_unref(outowner);
    }
    if (outchan) {
       res |= set_internal_datastore(outchan);
       ast_channel_unlock(outchan);
       ast_channel_unref(outchan);
    }
    ao2_unlock(unreal_pvt);
    ao2_ref(unreal_pvt, -1);
    return res;
 }
stasis_app_control_absorb_dtmf_in_bridge()
void stasis_app_control_absorb_dtmf_in_bridge (struct stasis_app_control * control, int absorb)
Set whether DTMF from the channel is absorbed instead of passing through to the bridge.
Parameters
control Control whose channel should have its DTMF absorbed when bridged
absorb Whether DTMF should be absorbed (1) instead of passed through (0).
Definition at line 1464 of file control.c.
References stasis_app_control::bridge_features, and ast_bridge_features::dtmf_passthrough.
Referenced by ast_ari_bridges_add_channel().
 {
    control->bridge_features->dtmf_passthrough = !absorb;
 }
stasis_app_control_add_channel_to_bridge()
int stasis_app_control_add_channel_to_bridge (struct stasis_app_control * control, struct ast_bridge * bridge)
Add a channel to the bridge.
Parameters
control Control whose channel should be added to the bridge
bridge Pointer to the bridge
Returns
non-zero on failure
zero on success
Definition at line 1383 of file control.c.
References app_control_can_add_channel_to_bridge(), app_send_command_on_condition(), ast_debug, control_add_channel_to_bridge(), NULL, and stasis_app_control_get_channel_id().
Referenced by ast_ari_bridges_add_channel().
 {
    ast_debug(3, "%s: Sending channel add_to_bridge command\n",
          stasis_app_control_get_channel_id(control));
    return app_send_command_on_condition(
       control, control_add_channel_to_bridge, bridge, NULL,
       app_control_can_add_channel_to_bridge);
 }
stasis_app_control_add_role()
int stasis_app_control_add_role (struct stasis_app_control * control, const char * role)
Apply a bridge role to a channel controlled by a stasis app control.
Parameters
control Control for res_stasis
role Role to apply
Returns
0 for success
-1 for error.
Definition at line 316 of file control.c.
References app_control_add_role(), ast_free_ptr(), ast_strdup, and stasis_app_send_command_async().
Referenced by ast_ari_bridges_add_channel().
 {
    char *role_dup;
    role_dup = ast_strdup(role);
    if (!role_dup) {
       return -1;
    }
    stasis_app_send_command_async(control, app_control_add_role, role_dup, ast_free_ptr);
    return 0;
 }
stasis_app_control_answer()
int stasis_app_control_answer (struct stasis_app_control * control)
Answer the channel associated with this control.
Parameters
control Control for res_stasis.
Returns
0 for success.
Non-zero for error.
Definition at line 44 of file res_stasis_answer.c.
References app_control_answer(), ast_debug, ast_log, LOG_WARNING, NULL, retval, stasis_app_control_get_channel_id(), and stasis_app_send_command().
Referenced by ast_ari_channels_answer().
 {
    int retval;
    ast_debug(3, "%s: Sending answer command\n",
       stasis_app_control_get_channel_id(control));
    retval = stasis_app_send_command(control, app_control_answer, NULL, NULL);
    if (retval != 0) {
       ast_log(LOG_WARNING, "%s: Failed to answer channel\n",
          stasis_app_control_get_channel_id(control));
       return -1;
    }
    return 0;
 }
stasis_app_control_bridge_features_init()
int stasis_app_control_bridge_features_init (struct stasis_app_control * control)
Initialize bridge features into a channel control.
Note
Bridge features on a control are destroyed after each bridge session, so new features need to be initialized before each bridge add.
Parameters
control Control in which to store the features
Returns
non-zero on failure
zero on success
Definition at line 1451 of file control.c.
References ast_bridge_features_new(), and stasis_app_control::bridge_features.
Referenced by ast_ari_bridges_add_channel().
 {
    struct ast_bridge_features *features;
    features = ast_bridge_features_new();
    if (!features) {
       return 1;
    }
    control->bridge_features = features;
    return 0;
 }
stasis_app_control_clear_roles()
void stasis_app_control_clear_roles (struct stasis_app_control * control)
Clear bridge roles currently applied to a channel controlled by a stasis app control.
Parameters
control Control for res_stasis
Definition at line 338 of file control.c.
References app_control_clear_roles(), NULL, and stasis_app_send_command_async().
Referenced by ast_ari_bridges_add_channel().
 {
    stasis_app_send_command_async(control, app_control_clear_roles, NULL, NULL);
 }
stasis_app_control_continue()
int stasis_app_control_continue (struct stasis_app_control * control, const char * context, const char * extension, int priority)
Exit res_stasis and continue execution in the dialplan.
If the channel is no longer in res_stasis, this function does nothing.
Parameters
control Control for res_stasis
context An optional context to continue to
extension An optional extension to continue to
priority An optional priority to continue to
Returns
0 for success
-1 for error.
Definition at line 389 of file control.c.
References app_control_continue(), ast_calloc, ast_copy_string(), ast_free_ptr(), stasis_app_control_continue_data::context, stasis_app_control_continue_data::extension, priority, stasis_app_control_continue_data::priority, S_OR, and stasis_app_send_command_async().
Referenced by ast_ari_channels_continue_in_dialplan().
 {
    struct stasis_app_control_continue_data *continue_data;
    if (!(continue_data = ast_calloc(1, sizeof(*continue_data)))) {
       return -1;
    }
    ast_copy_string(continue_data->context, S_OR(context, ""), sizeof(continue_data->context));
    ast_copy_string(continue_data->extension, S_OR(extension, ""), sizeof(continue_data->extension));
    if (priority > 0) {
       continue_data->priority = priority;
    } else {
       continue_data->priority = -1;
    }
    stasis_app_send_command_async(control, app_control_continue, continue_data, ast_free_ptr);
    return 0;
 }
stasis_app_control_create()
struct stasis_app_control* stasis_app_control_create (struct ast_channel * chan)
Creates a control handler for a channel that isn't in a stasis app.
Since
12.0.0
Parameters
chan Channel to create controller handle for
Returns
NULL on failure to create the handle
Pointer to res_stasis handler.
Definition at line 333 of file res_stasis.c.
References control_create(), and NULL.
Referenced by ari_bridges_play_new(), and ast_ari_bridges_record().
 {
    return control_create(chan, NULL);
 }
stasis_app_control_dial()
int stasis_app_control_dial (struct stasis_app_control * control, const char * dialstring, unsigned int timeout)
Dial a channel.
Parameters
control Control for res_stasis.
dialstring The dialstring to pass to the channel driver
timeout Optional timeout in milliseconds
Definition at line 1666 of file control.c.
References app_control_dial(), args, control_dial_args_alloc(), control_dial_args_destroy(), and stasis_app_send_command_async().
Referenced by ast_ari_channels_dial().
 {
    struct control_dial_args *args;
    args = control_dial_args_alloc(dialstring, timeout);
    if (!args) {
       return -1;
    }
    return stasis_app_send_command_async(control, app_control_dial,
       args, control_dial_args_destroy);
 }
stasis_app_control_dtmf()
int stasis_app_control_dtmf (struct stasis_app_control * control, const char * dtmf, int before, int between, unsigned int duration, int after)
Send DTMF to the channel associated with this control.
Parameters
control Control for res_stasis.
dtmf DTMF string.
before Amount of time to wait before sending DTMF digits.
between Amount of time between each DTMF digit.
duration Amount of time each DTMF digit lasts for.
after Amount of time to wait after sending DTMF digits.
Returns
0 for success.
-1 for error.
Definition at line 565 of file control.c.
References stasis_app_control_dtmf_data::after, app_control_dtmf(), ast_calloc, ast_free_ptr(), stasis_app_control_dtmf_data::before, stasis_app_control_dtmf_data::between, stasis_app_control_dtmf_data::dtmf, stasis_app_control_dtmf_data::duration, and stasis_app_send_command_async().
Referenced by ast_ari_channels_send_dtmf().
 {
    struct stasis_app_control_dtmf_data *dtmf_data;
    if (!(dtmf_data = ast_calloc(1, sizeof(*dtmf_data) + strlen(dtmf) + 1))) {
       return -1;
    }
    dtmf_data->before = before;
    dtmf_data->between = between;
    dtmf_data->duration = duration;
    dtmf_data->after = after;
    strcpy(dtmf_data->dtmf, dtmf);
    stasis_app_send_command_async(control, app_control_dtmf, dtmf_data, ast_free_ptr);
    return 0;
 }
stasis_app_control_execute_until_exhausted()
void stasis_app_control_execute_until_exhausted (struct ast_channel * chan, struct stasis_app_control * control)
Act on a stasis app control queue until it is empty.
Since
12.0.0
Parameters
chan Channel to handle
control Control object to execute
Definition at line 1250 of file res_stasis.c.
References ao2_lock, ao2_unlock, ast_channel_fdno(), control_command_count(), control_dispatch_all(), control_is_done(), and control_mark_done().
Referenced by bridge_channel_control_thread().
 {
    while (!control_is_done(control)) {
       int command_count;
       command_count = control_dispatch_all(control, chan);
       ao2_lock(control);
       if (control_command_count(control)) {
          /* If the command queue isn't empty, something added to the queue before it was locked. */
          ao2_unlock(control);
          continue;
       }
       if (command_count == 0 || ast_channel_fdno(chan) == -1) {
          control_mark_done(control);
          ao2_unlock(control);
          break;
       }
       ao2_unlock(control);
    }
 }
stasis_app_control_find_by_channel()
struct stasis_app_control* stasis_app_control_find_by_channel (const struct ast_channel * chan)
Returns the handler for the given channel.
Parameters
chan Channel to handle.
Returns
NULL channel not in Stasis application.
Pointer to res_stasis handler.
Definition at line 338 of file res_stasis.c.
References ast_channel_uniqueid(), NULL, and stasis_app_control_find_by_channel_id().
Referenced by ari_bridges_play_found(), bridge_stasis_moving(), bridge_stasis_push(), bridge_stasis_push_peek(), and bridge_timeout().
 {
    if (chan == NULL) {
       return NULL;
    }
    return stasis_app_control_find_by_channel_id(
       ast_channel_uniqueid(chan));
 }
stasis_app_control_find_by_channel_id()
struct stasis_app_control* stasis_app_control_find_by_channel_id (const char * channel_id)
Returns the handler for the channel with the given id.
Parameters
channel_id Uniqueid of the channel.
Returns
NULL channel not in Stasis application, or channel does not exist.
Pointer to res_stasis handler.
Definition at line 349 of file res_stasis.c.
References ao2_find, and OBJ_SEARCH_KEY.
Referenced by find_channel_control(), find_control(), remove_bridge_playback(), and stasis_app_control_find_by_channel().
 {
    return ao2_find(app_controls, channel_id, OBJ_SEARCH_KEY);
 }
stasis_app_control_flush_queue()
void stasis_app_control_flush_queue (struct stasis_app_control * control)
Flush the control command queue.
Since
13.9.0
Parameters
control Control object to flush command queue.
Returns
Nothing
Definition at line 1278 of file res_stasis.c.
References control_flush_queue().
Referenced by bridge_channel_control_thread().
 {
    control_flush_queue(control);
 }
stasis_app_control_get_channel_id()
const char* stasis_app_control_get_channel_id (const struct stasis_app_control * control)
Returns the uniqueid of the channel associated with this control.
Parameters
control Control object.
Returns
Uniqueid of the associate channel.
NULL if control is NULL.
Definition at line 1430 of file control.c.
References ast_channel_uniqueid(), and stasis_app_control::channel.
Referenced by app_control_answer(), app_control_remove_channel_from_bridge(), app_control_silence_start(), check_add_remove_channel(), control_compare(), control_hash(), control_silence_stop_now(), control_swap_channel_in_bridge(), masq_match_cb(), playback_publish(), recording_publish(), stasis_app_control_add_channel_to_bridge(), stasis_app_control_answer(), stasis_app_control_get_snapshot(), stasis_app_control_play_uri(), stasis_app_control_record(), and stasis_app_control_remove_channel_from_bridge().
 {
    return ast_channel_uniqueid(control->channel);
 }
stasis_app_control_get_snapshot()
struct ast_channel_snapshot* stasis_app_control_get_snapshot (const struct stasis_app_control * control)
Returns the most recent snapshot for the associated channel.
The returned pointer is AO2 managed, so ao2_cleanup() when you're done.
Parameters
control Control for res_stasis.
Returns
Most recent snapshot. ao2_cleanup() when done.
NULL if channel isn't in cache.
Definition at line 860 of file control.c.
References ast_channel_snapshot_get_latest(), and stasis_app_control_get_channel_id().
Referenced by ari_bridges_play_helper(), ari_channels_handle_play(), ast_ari_channels_continue_in_dialplan(), and channel_state_invalid().
 {
    return ast_channel_snapshot_get_latest(stasis_app_control_get_channel_id(control));
 }
stasis_app_control_hold()
void stasis_app_control_hold (struct stasis_app_control * control)
Place the channel associated with the control on hold.
Parameters
control Control for res_stasis.
Definition at line 748 of file control.c.
References app_control_hold(), NULL, and stasis_app_send_command_async().
Referenced by ast_ari_channels_hold().
 {
    stasis_app_send_command_async(control, app_control_hold, NULL, NULL);
 }
stasis_app_control_inhibit_colp_in_bridge()
void stasis_app_control_inhibit_colp_in_bridge (struct stasis_app_control * control, int inhibit_colp)
Set whether COLP frames should be generated when joining the bridge.
Since
18
Parameters
control Control whose channel should have its COLP frames inhibited when bridged
mute Whether COLP frames should be generated (0) or not (1).
Definition at line 1476 of file control.c.
References stasis_app_control::bridge_features, and ast_bridge_features::inhibit_colp.
Referenced by ast_ari_bridges_add_channel().
 {
    control->bridge_features->inhibit_colp = inhibit_colp;
 }
stasis_app_control_is_done()
int stasis_app_control_is_done (struct stasis_app_control * control)
Check if a control is marked as done.
Since
12.2.0
Parameters
control Which control object is being evaluated
Definition at line 1273 of file res_stasis.c.
References control_is_done().
Referenced by ari_bridges_play_found().
 {
    return control_is_done(control);
 }
stasis_app_control_moh_start()
void stasis_app_control_moh_start (struct stasis_app_control * control, const char * moh_class)
Play music on hold to a channel (does not affect hold status)
Parameters
control Control for res_stasis.
moh_class class of music on hold to play (NULL allowed)
Definition at line 780 of file control.c.
References app_control_moh_start(), ast_free_ptr(), ast_strdup, ast_strlen_zero, NULL, and stasis_app_send_command_async().
Referenced by ast_ari_channels_start_moh().
 {
    char *data = NULL;
    if (!ast_strlen_zero(moh_class)) {
       data = ast_strdup(moh_class);
    }
    stasis_app_send_command_async(control, app_control_moh_start, data, ast_free_ptr);
 }
stasis_app_control_moh_stop()
void stasis_app_control_moh_stop (struct stasis_app_control * control)
Stop playing music on hold to a channel (does not affect hold status)
Parameters
control Control for res_stasis.
Definition at line 798 of file control.c.
References app_control_moh_stop(), NULL, and stasis_app_send_command_async().
Referenced by ast_ari_channels_stop_moh().
 {
    stasis_app_send_command_async(control, app_control_moh_stop, NULL, NULL);
 }
stasis_app_control_move()
int stasis_app_control_move (struct stasis_app_control * control, const char * app_name, const char * app_args)
Exit res_stasis and move to another Stasis application.
If the channel is no longer in res_stasis, this function does nothing.
Parameters
control Control for res_stasis
app_name The name of the application to switch to
app_args The list of arguments to pass to the application
Returns
0 for success
-1 for error
Definition at line 451 of file control.c.
References stasis_app_control_move_data::app_args, app_control_move(), stasis_app_control_move_data::app_name, ast_calloc, ast_free_ptr(), NULL, and stasis_app_send_command_async().
Referenced by ast_ari_channels_move().
 {
    struct stasis_app_control_move_data *move_data;
    size_t size;
    size = sizeof(*move_data) + strlen(app_name) + 1;
    if (app_args) {
       /* Application arguments are optional */
       size += strlen(app_args) + 1;
    }
    if (!(move_data = ast_calloc(1, size))) {
       return -1;
    }
    move_data->app_name = (char *)move_data + sizeof(*move_data);
    strcpy(move_data->app_name, app_name); /* Safe */
    if (app_args) {
       move_data->app_args = move_data->app_name + strlen(app_name) + 1;
       strcpy(move_data->app_args, app_args); /* Safe */
    } else {
       move_data->app_args = NULL;
    }
    stasis_app_send_command_async(control, app_control_move, move_data, ast_free_ptr);
    return 0;
 }
stasis_app_control_mute()
int stasis_app_control_mute (struct stasis_app_control * control, unsigned int direction, enum ast_frame_type frametype)
Mute the channel associated with this control.
Parameters
control Control for res_stasis.
direction The direction in which the audio should be muted.
frametype The type of stream that should be muted.
Returns
0 for success
-1 for error.
Definition at line 631 of file control.c.
References app_control_mute(), ast_calloc, ast_free_ptr(), stasis_app_control_mute_data::direction, stasis_app_control_mute_data::frametype, and stasis_app_send_command_async().
Referenced by ast_ari_channels_mute().
 {
    struct stasis_app_control_mute_data *mute_data;
    if (!(mute_data = ast_calloc(1, sizeof(*mute_data)))) {
       return -1;
    }
    mute_data->direction = direction;
    mute_data->frametype = frametype;
    stasis_app_send_command_async(control, app_control_mute, mute_data, ast_free_ptr);
    return 0;
 }
stasis_app_control_mute_in_bridge()
void stasis_app_control_mute_in_bridge (struct stasis_app_control * control, int mute)
Set whether audio from the channel is muted instead of passing through to the bridge.
Parameters
control Control whose channel should have its audio muted when bridged
mute Whether audio should be muted (1) instead of passed through (0).
Definition at line 1470 of file control.c.
References stasis_app_control::bridge_features, mute, and ast_bridge_features::mute.
Referenced by ast_ari_bridges_add_channel().
 {
    control->bridge_features->mute = mute;
 }
stasis_app_control_publish()
void stasis_app_control_publish (struct stasis_app_control * control, struct stasis_message * message)
Publish a message to the control's channel's topic.
Parameters
control Control to publish to
message Message to publish
Definition at line 1436 of file control.c.
References ast_channel_topic(), stasis_app_control::channel, and stasis_publish().
Referenced by playback_publish(), and recording_publish().
 {
    if (!control || !control->channel || !message) {
       return;
    }
    stasis_publish(ast_channel_topic(control->channel), message);
 }
stasis_app_control_queue_control()
int stasis_app_control_queue_control (struct stasis_app_control * control, enum ast_control_frame_type frame_type)
Queue a control frame without payload.
Parameters
control Control to publish to.
frame_type type of control frame.
Returns
zero on success
non-zero on failure
Definition at line 1445 of file control.c.
References ast_queue_control(), and stasis_app_control::channel.
Referenced by playback_forward(), playback_pause(), playback_restart(), playback_reverse(), playback_stop(), playback_unpause(), recording_cancel(), recording_mute(), recording_pause(), recording_stop(), recording_unmute(), and recording_unpause().
 {
    return ast_queue_control(control->channel, frame_type);
 }
stasis_app_control_redirect()
int stasis_app_control_redirect (struct stasis_app_control * control, const char * endpoint)
Redirect a channel in res_stasis to a particular endpoint.
Parameters
control Control for res_stasis
endpoint The endpoint transfer string where the channel should be sent to
Returns
0 for success
-1 for error
Definition at line 500 of file control.c.
References app_control_redirect(), ast_free_ptr(), ast_strdup, and stasis_app_send_command_async().
Referenced by ast_ari_channels_redirect().
 {
    char *endpoint_data = ast_strdup(endpoint);
    if (!endpoint_data) {
       return -1;
    }
    stasis_app_send_command_async(control, app_control_redirect, endpoint_data, ast_free_ptr);
    return 0;
 }
stasis_app_control_register_add_rule()
void stasis_app_control_register_add_rule (struct stasis_app_control * control, struct stasis_app_control_rule * rule)
Registers an add channel to bridge rule.
Parameters
control Control object
rule The rule to register
Definition at line 217 of file control.c.
References stasis_app_control::add_rules, and app_control_register_rule().
Referenced by stasis_app_control_record().
 {
    return app_control_register_rule(control, &control->add_rules, rule);
 }
stasis_app_control_register_remove_rule()
void stasis_app_control_register_remove_rule (struct stasis_app_control * control, struct stasis_app_control_rule * rule)
Registers a remove channel from bridge rule.
Parameters
control Control object
rule The rule to register
Definition at line 231 of file control.c.
References app_control_register_rule(), and stasis_app_control::remove_rules.
 {
    return app_control_register_rule(control, &control->remove_rules, rule);
 }
stasis_app_control_remove_channel_from_bridge()
int stasis_app_control_remove_channel_from_bridge (struct stasis_app_control * control, struct ast_bridge * bridge)
Remove a channel from the bridge.
Parameters
control Control whose channel should be removed from the bridge
bridge Pointer to the bridge
Returns
non-zero on failure
zero on success
Definition at line 1420 of file control.c.
References app_control_can_remove_channel_from_bridge(), app_control_remove_channel_from_bridge(), app_send_command_on_condition(), ast_debug, NULL, and stasis_app_control_get_channel_id().
Referenced by ast_ari_bridges_remove_channel().
 {
    ast_debug(3, "%s: Sending channel remove_from_bridge command\n",
          stasis_app_control_get_channel_id(control));
    return app_send_command_on_condition(
       control, app_control_remove_channel_from_bridge, bridge, NULL,
       app_control_can_remove_channel_from_bridge);
 }
stasis_app_control_ring()
int stasis_app_control_ring (struct stasis_app_control * control)
Indicate ringing to the channel associated with this control.
Parameters
control Control for res_stasis.
Returns
0 for success.
-1 for error.
Definition at line 592 of file control.c.
References app_control_ring(), NULL, and stasis_app_send_command_async().
Referenced by ast_ari_channels_ring().
 {
    stasis_app_send_command_async(control, app_control_ring, NULL, NULL);
    return 0;
 }
stasis_app_control_ring_stop()
int stasis_app_control_ring_stop (struct stasis_app_control * control)
Stop locally generated ringing on the channel associated with this control.
Parameters
control Control for res_stasis.
Returns
0 for success.
-1 for error.
Definition at line 607 of file control.c.
References app_control_ring_stop(), NULL, and stasis_app_send_command_async().
Referenced by ast_ari_channels_ring_stop().
 {
    stasis_app_send_command_async(control, app_control_ring_stop, NULL, NULL);
    return 0;
 }
stasis_app_control_set_channel_var()
int stasis_app_control_set_channel_var (struct stasis_app_control * control, const char * variable, const char * value)
Set a variable on the channel associated with this control to value.
Parameters
control Control for res_stasis.
variable The name of the variable
value The value to set the variable to
Returns
0 for success.
-1 for error.
Definition at line 711 of file control.c.
References app_control_set_channel_var(), ast_calloc, ast_strdup, free_chanvar(), chanvar::name, stasis_app_send_command_async(), chanvar::value, and var.
Referenced by ast_ari_channels_set_channel_var().
 {
    struct chanvar *var;
    var = ast_calloc(1, sizeof(*var));
    if (!var) {
       return -1;
    }
    var->name = ast_strdup(variable);
    if (!var->name) {
       free_chanvar(var);
       return -1;
    }
    /* It's kosher for value to be NULL. It means the variable is being unset */
    if (value) {
       var->value = ast_strdup(value);
       if (!var->value) {
          free_chanvar(var);
          return -1;
       }
    }
    stasis_app_send_command_async(control, app_control_set_channel_var, var, free_chanvar);
    return 0;
 }
stasis_app_control_shutdown()
void stasis_app_control_shutdown (void)
Let Stasis app internals shut down.
This is called when res_stasis is unloaded. It ensures that the Stasis app internals can free any resources they may have allocated during the time that res_stasis was loaded.
Definition at line 1680 of file control.c.
References ast_bridge_destroy(), ast_mutex_lock, ast_mutex_unlock, dial_bridge_lock, NULL, and shutting_down.
Referenced by unload_module().
 {
    ast_mutex_lock(&dial_bridge_lock);
    shutting_down = 1;
    if (dial_bridge) {
       ast_bridge_destroy(dial_bridge, 0);
       dial_bridge = NULL;
    }
    ast_mutex_unlock(&dial_bridge_lock);
 }
stasis_app_control_silence_start()
void stasis_app_control_silence_start (struct stasis_app_control * control)
Start playing silence to a channel.
Parameters
control Control for res_stasis.
Definition at line 832 of file control.c.
References app_control_silence_start(), NULL, and stasis_app_send_command_async().
Referenced by ast_ari_channels_start_silence().
 {
    stasis_app_send_command_async(control, app_control_silence_start, NULL, NULL);
 }
stasis_app_control_silence_stop()
void stasis_app_control_silence_stop (struct stasis_app_control * control)
Stop playing silence to a channel.
Parameters
control Control for res_stasis.
Definition at line 855 of file control.c.
References app_control_silence_stop(), NULL, and stasis_app_send_command_async().
Referenced by ast_ari_channels_stop_silence().
 {
    stasis_app_send_command_async(control, app_control_silence_stop, NULL, NULL);
 }
stasis_app_control_unhold()
void stasis_app_control_unhold (struct stasis_app_control * control)
Remove the channel associated with the control from hold.
Parameters
control Control for res_stasis.
Definition at line 761 of file control.c.
References app_control_unhold(), NULL, and stasis_app_send_command_async().
Referenced by ast_ari_channels_unhold().
 {
    stasis_app_send_command_async(control, app_control_unhold, NULL, NULL);
 }
stasis_app_control_unmute()
int stasis_app_control_unmute (struct stasis_app_control * control, unsigned int direction, enum ast_frame_type frametype)
Unmute the channel associated with this control.
Parameters
control Control for res_stasis.
direction The direction in which the audio should be unmuted.
frametype The type of stream that should be unmuted.
Returns
0 for success
-1 for error.
Definition at line 659 of file control.c.
References app_control_unmute(), ast_calloc, ast_free_ptr(), stasis_app_control_mute_data::direction, stasis_app_control_mute_data::frametype, and stasis_app_send_command_async().
Referenced by ast_ari_channels_unmute().
 {
    struct stasis_app_control_mute_data *mute_data;
    if (!(mute_data = ast_calloc(1, sizeof(*mute_data)))) {
       return -1;
    }
    mute_data->direction = direction;
    mute_data->frametype = frametype;
    stasis_app_send_command_async(control, app_control_unmute, mute_data, ast_free_ptr);
    return 0;
 }
stasis_app_control_unregister_add_rule()
void stasis_app_control_unregister_add_rule (struct stasis_app_control * control, struct stasis_app_control_rule * rule)
UnRegister an add channel to bridge rule.
Parameters
control Control object
rule The rule to unregister
Definition at line 224 of file control.c.
References stasis_app_control::add_rules, and app_control_unregister_rule().
Referenced by record_file(), and recording_fail().
 {
    app_control_unregister_rule(control, &control->add_rules, rule);
 }
stasis_app_control_unregister_remove_rule()
void stasis_app_control_unregister_remove_rule (struct stasis_app_control * control, struct stasis_app_control_rule * rule)
Unregisters a remove channel from bridge rule.
Parameters
control Control object
rule The rule to unregister
Definition at line 238 of file control.c.
References app_control_unregister_rule(), and stasis_app_control::remove_rules.
 {
    app_control_unregister_rule(control, &control->remove_rules, rule);
 }
stasis_app_event_allowed()
int stasis_app_event_allowed (const char * app_name, struct ast_json * event)
Check if the given event should be filtered.
Attempts first to find the event in the application's disallowed events list. If found then the event won't be sent to the remote. If not found in the disallowed list then a search is done to see if it can be found in the allowed list. If found the event message is sent, otherwise it is not sent.
Parameters
app_name The application name
event The event to check
Returns
True if allowed, false otherwise
Definition at line 1739 of file res/stasis/app.c.
References ao2_lock, ao2_ref, ao2_unlock, app, app_event_filter_matched(), stasis_app::events_allowed, stasis_app::events_disallowed, and stasis_app_get_by_name().
Referenced by stasis_app_message_handler().
 {
    struct stasis_app *app = stasis_app_get_by_name(app_name);
    int res;
    if (!app) {
       return 0;
    }
    ao2_lock(app);
    res = !app_event_filter_matched(app->events_disallowed, event, 0) &&
       app_event_filter_matched(app->events_allowed, event, 1);
    ao2_unlock(app);
    ao2_ref(app, -1);
    return res;
 }
stasis_app_event_filter_set()
int stasis_app_event_filter_set (struct stasis_app * app, struct ast_json * filter)
Set the application's event type filter.
Parameters
app The application
filter The allowed and/or disallowed event filter
Returns
0 if successfully set
Definition at line 1713 of file res/stasis/app.c.
References app_events_allowed_set(), and app_events_disallowed_set().
Referenced by ast_ari_applications_filter().
 {
    return app_events_disallowed_set(app, filter) || app_events_allowed_set(app, filter);
 }
stasis_app_event_filter_to_json()
struct ast_json* stasis_app_event_filter_to_json (struct stasis_app * app, struct ast_json * json)
Convert and add the app's event type filter(s) to the given json object.
Parameters
app The application
json The json object to add the filter data to
Returns
The given json object
Definition at line 1641 of file res/stasis/app.c.
References ast_json_array_create(), ast_json_object_set(), ast_json_ref(), stasis_app::events_allowed, and stasis_app::events_disallowed.
Referenced by stasis_app_object_to_json().
 {
    if (!app || !json) {
       return json;
    }
    ast_json_object_set(json, "events_allowed", app->events_allowed ?
       ast_json_ref(app->events_allowed) : ast_json_array_create());
    ast_json_object_set(json, "events_disallowed", app->events_disallowed ?
       ast_json_ref(app->events_disallowed) : ast_json_array_create());
    return json;
 }
stasis_app_get_all()
struct ao2_container* stasis_app_get_all (void)
Gets the names of all registered Stasis applications.
Returns
ast_str_container of container names.
NULL on error.
Definition at line 1708 of file res_stasis.c.
References ao2_callback, append_name(), apps, ast_str_container_alloc, NULL, and OBJ_NODATA.
Referenced by ari_show_apps(), ast_ari_applications_list(), complete_ari_app(), and stasis_app_set_global_debug().
 {
    struct ao2_container *apps;
    if (!apps_registry) {
       return NULL;
    }
    apps = ast_str_container_alloc(1);
    if (!apps) {
       return NULL;
    }
    ao2_callback(apps_registry, OBJ_NODATA, append_name, apps);
    return apps;
 }
stasis_app_get_bridge()
struct ast_bridge* stasis_app_get_bridge (struct stasis_app_control * control)
Gets the bridge currently associated with a control object.
Since
12
Note
If the bridge returned by this function is to be held for any length of time, its refcount should be incremented until the caller is finished with it.
Parameters
control Control object for the channel to query.
Returns
Associated ast_bridge.
NULL if not associated with a bridge.
Definition at line 931 of file control.c.
References ao2_lock, ao2_unlock, stasis_app_control::bridge, and NULL.
Referenced by app_control_continue(), app_control_dtmf(), app_control_remove_channel_from_bridge(), ast_ari_bridges_remove_channel(), ast_ari_bridges_set_video_source(), control_swap_channel_in_bridge(), play_uri(), record_file(), and stasis_app_exec().
 {
    struct ast_bridge *ret;
    if (!control) {
       return NULL;
    }
    ao2_lock(control);
    ret = control->bridge;
    ao2_unlock(control);
    return ret;
 }
stasis_app_get_by_name()
struct stasis_app* stasis_app_get_by_name (const char * name)
Retrieve a handle to a Stasis application by its name.
Parameters
name The name of the registered Stasis application
Returns
stasis_app on success.
NULL on error.
Definition at line 1694 of file res_stasis.c.
References find_app_by_name().
Referenced by ari_set_debug(), ari_show_app(), ast_ari_applications_filter(), stasis_app_event_allowed(), stasis_app_get_debug_by_name(), stasis_app_set_debug_by_name(), and stasis_app_set_global_debug().
 {
    return find_app_by_name(name);
 }
stasis_app_get_debug()
int stasis_app_get_debug (struct stasis_app * app)
Get debug status of an application.
Parameters
app The app to check
Returns
The debug flag for the app || the global debug flag
Definition at line 863 of file res/stasis/app.c.
References stasis_app::debug, and global_debug.
 {
    return (app ? app->debug : 0) || global_debug;
 }
stasis_app_get_debug_by_name()
int stasis_app_get_debug_by_name (const char * app_name)
Get debug status of an application.
Parameters
app_name The app_name to check
Returns
The debug flag for the app || the global debug flag
Definition at line 868 of file res/stasis/app.c.
References ao2_ref, app, stasis_app::debug, global_debug, and stasis_app_get_by_name().
Referenced by ast_ari_callback(), and stasis_app_message_handler().
 {
    int debug_enabled = 0;
    if (global_debug) {
       debug_enabled = 1;
    } else {
       struct stasis_app *app = stasis_app_get_by_name(app_name);
       if (app) {
          if (app->debug) {
             debug_enabled = 1;
          }
          ao2_ref(app, -1);
       }
    }
    return debug_enabled;
 }
stasis_app_get_sanitizer()
struct stasis_message_sanitizer* stasis_app_get_sanitizer (void)
Get the Stasis message sanitizer for app_stasis applications.
Return values
The stasis message sanitizer
Definition at line 2264 of file res_stasis.c.
References app_sanitizer.
Referenced by app_send_end_msg(), ast_ari_bridges_create(), ast_ari_bridges_create_with_id(), ast_ari_bridges_get(), ast_ari_bridges_list(), ast_ari_channels_list(), ast_ari_endpoints_get(), ast_ari_endpoints_list(), ast_ari_endpoints_list_by_tech(), channel_callerid(), channel_connected_line(), channel_destroyed_event(), channel_dialplan(), message_received_handler(), simple_bridge_event(), simple_channel_event(), simple_endpoint_event(), and sub_default_handler().
 {
    return &app_sanitizer;
 }
stasis_app_name()
const char* stasis_app_name (const struct stasis_app * app)
Retrieve an application's name.
Parameters
app An application
Returns
The name of the application.
Definition at line 1156 of file res/stasis/app.c.
References stasis_app::name.
Referenced by app_compare(), app_hash(), app_send_end_msg(), app_subscribe(), app_unsubscribe(), append_name(), ari_set_debug(), bridge_stasis_push_peek(), cleanup_cb(), device_state_subscription_create(), devices_to_json(), find_device_state_subscription(), send_start_msg_snapshots(), stasis_app_exec(), and subscribe_device_state().
 {
    return app->name;
 }
stasis_app_object_to_json()
struct ast_json* stasis_app_object_to_json (struct stasis_app * app)
Return the JSON representation of a Stasis application.
Since
16.3.0
Parameters
app The application.
Returns
JSON representation of app with given name.
NULL on error.
Definition at line 1866 of file res_stasis.c.
References app_event_sources_to_json(), app_to_json(), NULL, and stasis_app_event_filter_to_json().
Referenced by app_handle_subscriptions(), ast_ari_applications_filter(), and stasis_app_to_json().
 {
    if (!app) {
       return NULL;
    }
    return stasis_app_event_filter_to_json(
       app, app_event_sources_to_json(app, app_to_json(app)));
 }
stasis_app_register()
int stasis_app_register (const char * app_name, stasis_app_cb handler, void * data)
Register a new Stasis application.
If an application is already registered with the given name, the old application is sent a 'replaced' message and unregistered.
Parameters
app_name Name of this application.
handler Callback for application messages.
data Data blob to pass to the callback. Must be AO2 managed.
Returns
0 for success
-1 for error.
Definition at line 1777 of file res_stasis.c.
References __stasis_app_register().
Referenced by AST_TEST_DEFINE(), and event_session_alloc().
 {
    return __stasis_app_register(app_name, handler, data, 0);
 }
stasis_app_register_all()
int stasis_app_register_all (const char * app_name, stasis_app_cb handler, void * data)
Register a new Stasis application that receives all Asterisk events.
If an application is already registered with the given name, the old application is sent a 'replaced' message and unregistered.
Parameters
app_name Name of this application.
handler Callback for application messages.
data Data blob to pass to the callback. Must be AO2 managed.
Returns
0 for success
-1 for error.
Definition at line 1782 of file res_stasis.c.
References __stasis_app_register().
Referenced by event_session_alloc().
 {
    return __stasis_app_register(app_name, handler, data, 1);
 }
stasis_app_register_event_source()
void stasis_app_register_event_source (struct stasis_app_event_source * obj)
Register an application event source.
Parameters
obj the event source to register
Definition at line 1816 of file res_stasis.c.
References AST_LIST_INSERT_TAIL, AST_RWLIST_UNLOCK, and AST_RWLIST_WRLOCK.
Referenced by load_module(), and stasis_app_register_event_sources().
 {
    AST_RWLIST_WRLOCK(&event_sources);
    AST_LIST_INSERT_TAIL(&event_sources, obj, next);
    AST_RWLIST_UNLOCK(&event_sources);
 }
stasis_app_register_event_sources()
void stasis_app_register_event_sources (void)
Register core event sources.
Definition at line 1627 of file res/stasis/app.c.
References stasis_app_register_event_source().
Referenced by load_module().
 {
    stasis_app_register_event_source(&channel_event_source);
    stasis_app_register_event_source(&bridge_event_source);
    stasis_app_register_event_source(&endpoint_event_source);
 }
stasis_app_send()
int stasis_app_send (const char * app_name, struct ast_json * message)
Send a message to the given Stasis application.
The message given to the handler is a borrowed copy. If you want to keep a reference to it, you should use ao2_ref() to keep it around.
Parameters
app_name Name of the application to invoke.
message Message to send (borrowed reference)
Returns
0 for success.
-1 for error.
Definition at line 1656 of file res_stasis.c.
References ao2_find, ao2_ref, app, app_send(), ast_log, LOG_WARNING, and OBJ_SEARCH_KEY.
Referenced by AST_TEST_DEFINE(), and send_device_state().
 {
    struct stasis_app *app;
    if (!apps_registry) {
       return -1;
    }
    app = ao2_find(apps_registry, app_name, OBJ_SEARCH_KEY);
    if (!app) {
       /* XXX We can do a better job handling late binding, queueing up
        * the call for a few seconds to wait for the app to register.
        */
       ast_log(LOG_WARNING,
          "Stasis app '%s' not registered\n", app_name);
       return -1;
    }
    app_send(app, message);
    ao2_ref(app, -1);
    return 0;
 }
stasis_app_set_debug()
void stasis_app_set_debug (struct stasis_app * app, int debug)
Enable/disable request/response and event logging on an application.
Parameters
app The app to debug
debug If non-zero, enable debugging. If zero, disable.
Definition at line 842 of file res/stasis/app.c.
References stasis_app::debug.
Referenced by ari_set_debug(), and stasis_app_set_global_debug().
 {
    if (!app) {
       return;
    }
    app->debug = debug;
 }
stasis_app_set_debug_by_name()
void stasis_app_set_debug_by_name (const char * app_name, int debug)
Enable/disable request/response and event logging on an application.
Parameters
app_name The app name to debug
debug If non-zero, enable debugging. If zero, disable.
Definition at line 851 of file res/stasis/app.c.
References ao2_cleanup, app, stasis_app::debug, and stasis_app_get_by_name().
 {
    struct stasis_app *app = stasis_app_get_by_name(app_name);
    if (!app) {
       return;
    }
    app->debug = debug;
    ao2_cleanup(app);
 }
stasis_app_set_global_debug()
void stasis_app_set_global_debug (int debug)
Enable/disable request/response and event logging on all applications.
Parameters
debug If non-zero, enable debugging. If zero, disable.
Definition at line 887 of file res/stasis/app.c.
References ao2_cleanup, ao2_container_count(), ao2_iterator_cleanup(), ao2_iterator_init(), ao2_iterator_next, app, app_name(), stasis_app::debug, global_debug, stasis_app_get_all(), stasis_app_get_by_name(), and stasis_app_set_debug().
Referenced by ari_set_debug().
 {
    global_debug = debug;
    if (!global_debug) {
       struct ao2_container *app_names = stasis_app_get_all();
       struct ao2_iterator it_app_names;
       char *app_name;
       struct stasis_app *app;
       if (!app_names || !ao2_container_count(app_names)) {
          ao2_cleanup(app_names);
          return;
       }
       it_app_names = ao2_iterator_init(app_names, 0);
       while ((app_name = ao2_iterator_next(&it_app_names))) {
          if ((app = stasis_app_get_by_name(app_name))) {
             stasis_app_set_debug(app, 0);
          }
          ao2_cleanup(app_name);
          ao2_cleanup(app);
       }
       ao2_iterator_cleanup(&it_app_names);
       ao2_cleanup(app_names);
    }
 }
stasis_app_subscribe()
enum stasis_app_subscribe_res stasis_app_subscribe (const char * app_name, const char ** event_source_uris, int event_sources_count, struct ast_json ** json)
Subscribes an application to a list of event sources.
Parameters
app_name Name of the application to subscribe.
event_source_uris URIs for the event sources to subscribe to.
event_sources_count Array size of event_source_uris.
json Optional output pointer for JSON representation of the app after adding the subscription.
Returns
stasis_app_subscribe_res return code.
Note
Do not hold any channel locks if subscribing to a channel.
Definition at line 2045 of file res_stasis.c.
References app_handle_subscriptions(), and app_subscribe().
Referenced by ast_ari_applications_subscribe().
 {
    return app_handle_subscriptions(
       app_name, event_source_uris, event_sources_count,
       json, app_subscribe);
 }
stasis_app_subscribe_channel()
enum stasis_app_subscribe_res stasis_app_subscribe_channel (const char * app_name, struct ast_channel * chan)
Directly subscribe an application to a channel.
Parameters
app_name Name of the application to subscribe.
chan The channel to subscribe to
Returns
stasis_app_subscribe_res return code.
Note
This method can be used when you already hold a channel and its lock. This bypasses the channel lookup that would normally be performed by stasis_app_subscribe.
Definition at line 1984 of file res_stasis.c.
References ao2_ref, app_subscribe_channel(), ast_channel_uniqueid(), ast_debug, ast_log, find_app_by_name(), LOG_ERROR, STASIS_ASR_APP_NOT_FOUND, STASIS_ASR_INTERNAL_ERROR, and STASIS_ASR_OK.
Referenced by ari_channels_handle_originate_with_id(), and ast_ari_channels_create().
 {
    struct stasis_app *app = find_app_by_name(app_name);
    int res;
    if (!app) {
       return STASIS_ASR_APP_NOT_FOUND;
    }
    ast_debug(3, "%s: Subscribing to %s\n", app_name, ast_channel_uniqueid(chan));
    res = app_subscribe_channel(app, chan);
    ao2_ref(app, -1);
    if (res != 0) {
       ast_log(LOG_ERROR, "Error subscribing app '%s' to channel '%s'\n",
          app_name, ast_channel_uniqueid(chan));
       return STASIS_ASR_INTERNAL_ERROR;
    }
    return STASIS_ASR_OK;
 }
stasis_app_to_cli()
void stasis_app_to_cli (const struct stasis_app * app, struct ast_cli_args * a)
Dump properties of a stasis_app to the CLI.
Parameters
app The application
a The CLI arguments
Definition at line 1173 of file res/stasis/app.c.
References ao2_callback, ao2_container_count(), ao2_iterator_destroy(), ao2_iterator_next, ao2_ref, ast_cli(), bridges, channels, stasis_app::debug, endpoints, ast_cli_args::fd, FORWARD_BRIDGE, FORWARD_CHANNEL, FORWARD_ENDPOINT, stasis_app::forwards, forwards_filter_by_type(), app_forwards::id, app_forwards::interested, stasis_app::name, OBJ_MULTIPLE, STASIS_APP_SUBSCRIBE_ALL, and stasis_app::subscription_model.
Referenced by ari_show_app().
 {
    struct ao2_iterator *channels;
    struct ao2_iterator *endpoints;
    struct ao2_iterator *bridges;
    struct app_forwards *forward;
    enum forward_type forward_type;
    ast_cli(a->fd, "Name: %s\n"
       "  Debug: %s\n"
       "  Subscription Model: %s\n",
       app->name,
       app->debug ? "Yes" : "No",
       app->subscription_model == STASIS_APP_SUBSCRIBE_ALL ?
          "Global Resource Subscription" :
          "Application/Explicit Resource Subscription");
    ast_cli(a->fd, "  Subscriptions: %d\n", ao2_container_count(app->forwards));
    ast_cli(a->fd, "    Channels:\n");
    forward_type = FORWARD_CHANNEL;
    channels = ao2_callback(app->forwards, OBJ_MULTIPLE,
       forwards_filter_by_type, &forward_type);
    if (channels) {
       while ((forward = ao2_iterator_next(channels))) {
          ast_cli(a->fd, "      %s (%d)\n", forward->id, forward->interested);
          ao2_ref(forward, -1);
       }
       ao2_iterator_destroy(channels);
    }
    ast_cli(a->fd, "    Bridges:\n");
    forward_type = FORWARD_BRIDGE;
    bridges = ao2_callback(app->forwards, OBJ_MULTIPLE,
       forwards_filter_by_type, &forward_type);
    if (bridges) {
       while ((forward = ao2_iterator_next(bridges))) {
          ast_cli(a->fd, "      %s (%d)\n", forward->id, forward->interested);
          ao2_ref(forward, -1);
       }
       ao2_iterator_destroy(bridges);
    }
    ast_cli(a->fd, "    Endpoints:\n");
    forward_type = FORWARD_ENDPOINT;
    endpoints = ao2_callback(app->forwards, OBJ_MULTIPLE,
       forwards_filter_by_type, &forward_type);
    if (endpoints) {
       while ((forward = ao2_iterator_next(endpoints))) {
          ast_cli(a->fd, "      %s (%d)\n", forward->id, forward->interested);
          ao2_ref(forward, -1);
       }
       ao2_iterator_destroy(endpoints);
    }
 }
stasis_app_to_json()
struct ast_json* stasis_app_to_json (const char * app_name)
Return the JSON representation of a Stasis application.
Parameters
app_name Name of the application.
Returns
JSON representation of app with given name.
NULL on error.
Definition at line 1876 of file res_stasis.c.
References ao2_cleanup, app, find_app_by_name(), and stasis_app_object_to_json().
Referenced by append_json(), and ast_ari_applications_get().
 {
    struct stasis_app *app = find_app_by_name(app_name);
    struct ast_json *json = stasis_app_object_to_json(app);
    ao2_cleanup(app);
    return json;
 }
stasis_app_unregister()
void stasis_app_unregister (const char * app_name)
Unregister a Stasis application.
Parameters
app_name Name of the application to unregister.
Definition at line 1787 of file res_stasis.c.
References ao2_find, ao2_ref, app, app_deactivate(), ast_log, cleanup(), LOG_ERROR, and OBJ_SEARCH_KEY.
Referenced by AST_TEST_DEFINE(), and event_session_shutdown().
 {
    struct stasis_app *app;
    if (!app_name) {
       return;
    }
    if (!apps_registry) {
       return;
    }
    app = ao2_find(apps_registry, app_name, OBJ_SEARCH_KEY);
    if (!app) {
       ast_log(LOG_ERROR,
          "Stasis app '%s' not registered\n", app_name);
       return;
    }
    app_deactivate(app);
    /* There's a decent chance that app is ready for cleanup. Go ahead
     * and clean up, just in case
     */
    cleanup();
    ao2_ref(app, -1);
 }
stasis_app_unregister_event_source()
void stasis_app_unregister_event_source (struct stasis_app_event_source * obj)
Unregister an application event source.
Parameters
obj the event source to unregister
Definition at line 1823 of file res_stasis.c.
References AST_RWLIST_REMOVE_CURRENT, AST_RWLIST_TRAVERSE_SAFE_BEGIN, AST_RWLIST_TRAVERSE_SAFE_END, AST_RWLIST_UNLOCK, AST_RWLIST_WRLOCK, and stasis_app_event_source::next.
Referenced by stasis_app_unregister_event_sources(), and unload_module().
 {
    struct stasis_app_event_source *source;
    AST_RWLIST_WRLOCK(&event_sources);
    AST_RWLIST_TRAVERSE_SAFE_BEGIN(&event_sources, source, next) {
       if (source == obj) {
          AST_RWLIST_REMOVE_CURRENT(next);
          break;
       }
    }
    AST_RWLIST_TRAVERSE_SAFE_END;
    AST_RWLIST_UNLOCK(&event_sources);
 }
stasis_app_unregister_event_sources()
void stasis_app_unregister_event_sources (void)
Unregister core event sources.
Definition at line 1634 of file res/stasis/app.c.
References stasis_app_unregister_event_source().
Referenced by unload_module().
 {
    stasis_app_unregister_event_source(&endpoint_event_source);
    stasis_app_unregister_event_source(&bridge_event_source);
    stasis_app_unregister_event_source(&channel_event_source);
 }
stasis_app_unsubscribe()
enum stasis_app_subscribe_res stasis_app_unsubscribe (const char * app_name, const char ** event_source_uris, int event_sources_count, struct ast_json ** json)
Unsubscribes an application from a list of event sources.
Parameters
app_name Name of the application to subscribe.
event_source_uris URIs for the event sources to subscribe to.
event_sources_count Array size of event_source_uris.
json Optional output pointer for JSON representation of the app after adding the subscription.
Returns
stasis_app_subscribe_res return code.
Definition at line 2086 of file res_stasis.c.
References app_handle_subscriptions(), and app_unsubscribe().
Referenced by ast_ari_applications_unsubscribe().
 {
    return app_handle_subscriptions(
       app_name, event_source_uris, event_sources_count,
       json, app_unsubscribe);
 }
stasis_app_user_event()
enum stasis_app_user_event_res stasis_app_user_event (const char * app_name, const char * event_name, const char ** source_uris, int sources_count, struct ast_json * json_variables)
Generate a Userevent for stasis app (echo to AMI)
Parameters
app_name Name of the application to generate event for/to.
event_name Name of the Userevent.
source_uris URIs for the source objects to attach to event.
sources_count Array size of source_uris.
json_variables event blob variables.
Returns
stasis_app_user_event_res return code.
Definition at line 2095 of file res_stasis.c.
References ao2_cleanup, ao2_ref, ast_app_get_topic(), ast_begins_with(), ast_bridge_get_snapshot_by_uniqueid(), ast_channel_snapshot_get_latest(), ast_endpoint_latest_snapshot(), ast_json_object_set(), ast_json_pack(), ast_json_ref(), ast_json_string_create(), ast_json_unref(), ast_log, ast_manager_get_topic(), ast_multi_object_blob_add(), ast_multi_object_blob_create(), ast_multi_user_event_type(), start_message_blob::blob, find_app_by_name(), LOG_ERROR, LOG_WARNING, NULL, RAII_VAR, STASIS_APP_USER_APP_NOT_FOUND, STASIS_APP_USER_EVENT_SOURCE_BAD_SCHEME, STASIS_APP_USER_EVENT_SOURCE_NOT_FOUND, STASIS_APP_USER_INTERNAL_ERROR, STASIS_APP_USER_OK, stasis_message_create(), stasis_publish(), STASIS_UMOS_BRIDGE, STASIS_UMOS_CHANNEL, STASIS_UMOS_ENDPOINT, and type.
Referenced by ast_ari_events_user_event().
 {
    RAII_VAR(struct stasis_app *, app, find_app_by_name(app_name), ao2_cleanup);
    struct ast_json *blob = NULL;
    struct ast_multi_object_blob *multi;
    struct stasis_message *message;
    enum stasis_app_user_event_res res = STASIS_APP_USER_INTERNAL_ERROR;
    int have_channel = 0;
    int i;
    if (!app) {
       ast_log(LOG_WARNING, "App %s not found\n", app_name);
       return STASIS_APP_USER_APP_NOT_FOUND;
    }
    if (!ast_multi_user_event_type()) {
       return res;
    }
    if (json_variables) {
       struct ast_json *json_value = ast_json_string_create(event_name);
       if (json_value && !ast_json_object_set(json_variables, "eventname", json_value)) {
          blob = ast_json_ref(json_variables);
       }
    } else {
       blob = ast_json_pack("{s: s}", "eventname", event_name);
    }
    if (!blob) {
       ast_log(LOG_ERROR, "Failed to initialize blob\n");
       return res;
    }
    multi = ast_multi_object_blob_create(blob);
    ast_json_unref(blob);
    if (!multi) {
       ast_log(LOG_ERROR, "Failed to initialize multi\n");
       return res;
    }
    for (i = 0; i < sources_count; ++i) {
       const char *uri = source_uris[i];
       void *snapshot=NULL;
       enum stasis_user_multi_object_snapshot_type type;
       if (ast_begins_with(uri, "channel:")) {
          type = STASIS_UMOS_CHANNEL;
          snapshot = ast_channel_snapshot_get_latest(uri + 8);
          have_channel = 1;
       } else if (ast_begins_with(uri, "bridge:")) {
          type = STASIS_UMOS_BRIDGE;
          snapshot = ast_bridge_get_snapshot_by_uniqueid(uri + 7);
       } else if (ast_begins_with(uri, "endpoint:")) {
          type = STASIS_UMOS_ENDPOINT;
          snapshot = ast_endpoint_latest_snapshot(uri + 9, NULL);
       } else {
          ast_log(LOG_WARNING, "Invalid scheme: %s\n", uri);
          ao2_ref(multi, -1);
          return STASIS_APP_USER_EVENT_SOURCE_BAD_SCHEME;
       }
       if (!snapshot) {
          ast_log(LOG_ERROR, "Unable to get snapshot for %s\n", uri);
          ao2_ref(multi, -1);
          return STASIS_APP_USER_EVENT_SOURCE_NOT_FOUND;
       }
       ast_multi_object_blob_add(multi, type, snapshot);
    }
    message = stasis_message_create(ast_multi_user_event_type(), multi);
    ao2_ref(multi, -1);
    if (!message) {
       ast_log(LOG_ERROR, "Unable to create stasis user event message\n");
       return res;
    }
    /*
     * Publishing to two different topics is normally to be avoided -- except
     * in this case both are final destinations with no forwards (only listeners).
     * The message has to be delivered to the application topic for ARI, but a
     * copy is also delivered directly to the manager for AMI if there is a channel.
     */
    stasis_publish(ast_app_get_topic(app), message);
    if (have_channel) {
       stasis_publish(ast_manager_get_topic(), message);
    }
    ao2_ref(message, -1);
    return STASIS_APP_USER_OK;
 }