Asterisk - The Open Source Telephony Project: format_ogg_speex.c File Reference
format_ogg_speex.c File Reference
Module: Media File Formats
OGG/Speex streams.
#include "asterisk.h"
#include "asterisk/mod_format.h"
#include "asterisk/module.h"
#include "asterisk/format_cache.h"
#include <speex/speex_header.h>
#include <ogg/ogg.h>
Data Structures
struct speex_desc
Macros
#define BLOCK_SIZE 4096 /* buffer size for feeding OGG routines */
#define BUF_SIZE 200
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int load_module (void)
static void ogg_speex_close (struct ast_filestream *fs)
Close a OGG/Speex filestream.
static int ogg_speex_open (struct ast_filestream *fs)
Create a new OGG/Speex filestream and set it up for reading.
static struct ast_frame * ogg_speex_read (struct ast_filestream *fs, int *whennext)
Read a frame full of audio data from the filestream.
static int ogg_speex_seek (struct ast_filestream *s, off_t sample_offset, int whence)
Seek to a specific position in an OGG/Speex filestream.
static off_t ogg_speex_tell (struct ast_filestream *s)
static int ogg_speex_trunc (struct ast_filestream *s)
Trucate an OGG/Speex filestream.
static int read_packet (struct ast_filestream *fs)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "OGG/Speex audio" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_EXTENDED, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_APP_DEPEND }
static const struct ast_module_info * ast_module_info = &__mod_info
static struct ast_format_def speex16_f
static struct ast_format_def speex32_f
static struct ast_format_def speex_f
Detailed Description
OGG/Speex streams.
File name extension: spx
Definition in file format_ogg_speex.c.
Macro Definition Documentation
BLOCK_SIZE
#define BLOCK_SIZE 4096 /* buffer size for feeding OGG routines */
Definition at line 39 of file format_ogg_speex.c.
Referenced by ogg_speex_open(), and read_packet().
BUF_SIZE
#define BUF_SIZE 200
Definition at line 40 of file format_ogg_speex.c.
Referenced by ogg_speex_read().
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 345 of file format_ogg_speex.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 345 of file format_ogg_speex.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 345 of file format_ogg_speex.c.
load_module()
static int load_module (void) static
Definition at line 324 of file format_ogg_speex.c.
References ast_format_def_register, ast_format_speex, ast_format_speex16, ast_format_speex32, AST_MODFLAG_LOAD_ORDER, AST_MODPRI_APP_DEPEND, AST_MODULE_INFO(), AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, AST_MODULE_SUPPORT_EXTENDED, ASTERISK_GPL_KEY, ast_format_def::format, and unload_module().
 {
    speex_f.format = ast_format_speex;
    speex16_f.format = ast_format_speex16;
    speex32_f.format = ast_format_speex32;
    if (ast_format_def_register(&speex_f) ||
        ast_format_def_register(&speex16_f) ||
        ast_format_def_register(&speex32_f)) {
       unload_module();
       return AST_MODULE_LOAD_DECLINE;
    }
    return AST_MODULE_LOAD_SUCCESS;
 }
ogg_speex_close()
static void ogg_speex_close (struct ast_filestream * fs) static
Close a OGG/Speex filestream.
Parameters
fs A OGG/Speex filestream.
Definition at line 214 of file format_ogg_speex.c.
References ast_filestream::_private, speex_desc::os, and speex_desc::oy.
 {
    struct speex_desc *s = (struct speex_desc *)fs->_private;
    ogg_stream_clear(&s->os);
    ogg_sync_clear(&s->oy);
 }
ogg_speex_open()
static int ogg_speex_open (struct ast_filestream * fs) static
Create a new OGG/Speex filestream and set it up for reading.
Parameters
fs File that points to on disk storage of the OGG/Speex data.
Returns
The new filestream.
Definition at line 130 of file format_ogg_speex.c.
References ast_filestream::_private, ast_format_get_sample_rate(), ast_log, BLOCK_SIZE, error(), ast_filestream::f, ast_filestream::fmt, ast_format_def::format, LOG_ERROR, NULL, speex_desc::og, speex_desc::op, speex_desc::os, speex_desc::oy, read_packet(), result, and speex_desc::serialno.
 {
    char *buffer;
    size_t bytes;
    struct speex_desc *s = (struct speex_desc *)fs->_private;
    SpeexHeader *hdr = NULL;
    int i, result, expected_rate;
    expected_rate = ast_format_get_sample_rate(fs->fmt->format);
    s->serialno = -1;
    ogg_sync_init(&s->oy);
    buffer = ogg_sync_buffer(&s->oy, BLOCK_SIZE);
    bytes = fread(buffer, 1, BLOCK_SIZE, fs->f);
    ogg_sync_wrote(&s->oy, bytes);
    result = ogg_sync_pageout(&s->oy, &s->og);
    if (result != 1) {
       if(bytes < BLOCK_SIZE) {
          ast_log(LOG_ERROR, "Run out of data...\n");
       } else {
          ast_log(LOG_ERROR, "Input does not appear to be an Ogg bitstream.\n");
       }
       ogg_sync_clear(&s->oy);
       return -1;
    }
    ogg_stream_init(&s->os, ogg_page_serialno(&s->og));
    if (ogg_stream_pagein(&s->os, &s->og) < 0) {
       ast_log(LOG_ERROR, "Error reading first page of Ogg bitstream data.\n");
       goto error;
    }
    if (read_packet(fs) < 0) {
       ast_log(LOG_ERROR, "Error reading initial header packet.\n");
       goto error;
    }
    hdr = speex_packet_to_header((char*)s->op.packet, s->op.bytes);
    if (memcmp(hdr->speex_string, "Speex   ", 8)) {
       ast_log(LOG_ERROR, "OGG container does not contain Speex audio!\n");
       goto error;
    }
    if (hdr->frames_per_packet != 1) {
       ast_log(LOG_ERROR, "Only one frame-per-packet OGG/Speex files are currently supported!\n");
       goto error;
    }
    if (hdr->nb_channels != 1) {
       ast_log(LOG_ERROR, "Only monophonic OGG/Speex files are currently supported!\n");
       goto error;
    }
    if (hdr->rate != expected_rate) {
       ast_log(LOG_ERROR, "Unexpected sampling rate (%d != %d)!\n",
          hdr->rate, expected_rate);
       goto error;
    }
    /* this packet is the comment */
    if (read_packet(fs) < 0) {
       ast_log(LOG_ERROR, "Error reading comment packet.\n");
       goto error;
    }
    for (i = 0; i < hdr->extra_headers; i++) {
       if (read_packet(fs) < 0) {
          ast_log(LOG_ERROR, "Error reading extra header packet %d.\n", i+1);
          goto error;
       }
    }
    speex_header_free(hdr);
    return 0;
 error:
    if (hdr) {
       speex_header_free(hdr);
    }
    ogg_stream_clear(&s->os);
    ogg_sync_clear(&s->oy);
    return -1;
 }
ogg_speex_read()
static struct ast_frame* ogg_speex_read (struct ast_filestream * fs, int * whennext) static
Read a frame full of audio data from the filestream.
Parameters
fs The filestream.
whennext Number of sample times to schedule the next call.
Returns
A pointer to a frame containing audio data or NULL ifthere is no more audio data.
Definition at line 228 of file format_ogg_speex.c.
References ast_filestream::_private, ast_codec_samples_count(), AST_FRAME_SET_BUFFER, AST_FRIENDLY_OFFSET, ast_filestream::buf, BUF_SIZE, ast_frame::data, ast_frame::datalen, ast_filestream::fr, if(), NULL, speex_desc::op, ast_frame::ptr, read_packet(), and ast_frame::samples.
 {
    struct speex_desc *s = (struct speex_desc *)fs->_private;
    if (read_packet(fs) < 0) {
       return NULL;
    }
    AST_FRAME_SET_BUFFER(&fs->fr, fs->buf, AST_FRIENDLY_OFFSET, BUF_SIZE);
    memcpy(fs->fr.data.ptr, s->op.packet, s->op.bytes);
    fs->fr.datalen = s->op.bytes;
    fs->fr.samples = *whennext = ast_codec_samples_count(&fs->fr);
    return &fs->fr;
 }
ogg_speex_seek()
static int ogg_speex_seek (struct ast_filestream * s, off_t sample_offset, int whence) static
Seek to a specific position in an OGG/Speex filestream.
Parameters
s The filestream to truncate.
sample_offset New position for the filestream, measured in 8KHz samples.
whence Location to measure
Returns
0 on success, -1 on failure.
Definition at line 264 of file format_ogg_speex.c.
References ast_log, and LOG_WARNING.
 {
    ast_log(LOG_WARNING, "Seeking is not supported on OGG/Speex streams!\n");
    return -1;
 }
ogg_speex_tell()
static off_t ogg_speex_tell (struct ast_filestream * s) static
Definition at line 270 of file format_ogg_speex.c.
References ast_log, and LOG_WARNING.
 {
    ast_log(LOG_WARNING, "Telling is not supported on OGG/Speex streams!\n");
    return -1;
 }
ogg_speex_trunc()
static int ogg_speex_trunc (struct ast_filestream * s) static
Trucate an OGG/Speex filestream.
Parameters
s The filestream to truncate.
Returns
0 on success, -1 on failure.
Definition at line 251 of file format_ogg_speex.c.
References ast_log, and LOG_WARNING.
 {
    ast_log(LOG_WARNING, "Truncation is not supported on OGG/Speex streams!\n");
    return -1;
 }
read_packet()
static int read_packet (struct ast_filestream * fs) static
Definition at line 55 of file format_ogg_speex.c.
References ast_filestream::_private, ast_log, BLOCK_SIZE, speex_desc::eos, ast_filestream::f, LOG_WARNING, speex_desc::og, speex_desc::op, speex_desc::os, speex_desc::oy, result, speex_desc::serialno, and while().
Referenced by ogg_speex_open(), and ogg_speex_read().
 {
    struct speex_desc *s = (struct speex_desc *)fs->_private;
    char *buffer;
    int result;
    size_t bytes;
    while (1) {
       /* Get one packet */
       result = ogg_stream_packetout(&s->os, &s->op);
       if (result > 0) {
          if (s->op.bytes >= 5 && !memcmp(s->op.packet, "Speex", 5)) {
             s->serialno = s->os.serialno;
          }
          if (s->serialno == -1 || s->os.serialno != s->serialno) {
             continue;
          }
          return 0;
       }
       if (result < 0) {
          ast_log(LOG_WARNING,
             "Corrupt or missing data at this page position; continuing...\n");
       }
       /* No more packets left in the current page... */
       if (s->eos) {
          /* No more pages left in the stream */
          return -1;
       }
       while (!s->eos) {
          /* See if OGG has any pages in it's internal buffers */
          result = ogg_sync_pageout(&s->oy, &s->og);
          if (result > 0) {
             /* Read all streams. */
             if (ogg_page_serialno(&s->og) != s->os.serialno) {
                ogg_stream_reset_serialno(&s->os, ogg_page_serialno(&s->og));
             }
             /* Yes, OGG has more pages in it's internal buffers,
                add the page to the stream state */
             result = ogg_stream_pagein(&s->os, &s->og);
             if (result == 0) {
                /* Yes, got a new, valid page */
                if (ogg_page_eos(&s->og) &&
                    ogg_page_serialno(&s->og) == s->serialno)
                   s->eos = 1;
                break;
             }
             ast_log(LOG_WARNING,
                "Invalid page in the bitstream; continuing...\n");
          }
          if (result < 0) {
             ast_log(LOG_WARNING,
                "Corrupt or missing data in bitstream; continuing...\n");
          }
          /* No, we need to read more data from the file descrptor */
          /* get a buffer from OGG to read the data into */
          buffer = ogg_sync_buffer(&s->oy, BLOCK_SIZE);
          bytes = fread(buffer, 1, BLOCK_SIZE, fs->f);
          ogg_sync_wrote(&s->oy, bytes);
          if (bytes == 0) {
             s->eos = 1;
          }
       }
    }
 }
unload_module()
static int unload_module (void) static
Definition at line 315 of file format_ogg_speex.c.
References ast_format_def_unregister(), and ast_format_def::name.
Referenced by load_module().
 {
    int res = 0;
    res |= ast_format_def_unregister(speex_f.name);
    res |= ast_format_def_unregister(speex16_f.name);
    res |= ast_format_def_unregister(speex32_f.name);
    return res;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "OGG/Speex audio" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_EXTENDED, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_APP_DEPEND } static
Definition at line 345 of file format_ogg_speex.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 345 of file format_ogg_speex.c.
speex16_f
struct ast_format_def speex16_f static
Definition at line 289 of file format_ogg_speex.c.
speex32_f
struct ast_format_def speex32_f static
Definition at line 302 of file format_ogg_speex.c.
speex_f
struct ast_format_def speex_f static
Definition at line 276 of file format_ogg_speex.c.