Asterisk - The Open Source Telephony Project: analog_callback Struct Reference
analog_callback Struct Reference
#include <sig_analog.h>
Data Fields
void(*const all_subchannels_hungup)(void *pvt)
int(*const allocate_sub)(void *pvt, enum analog_sub sub)
void(*const answer_polarityswitch)(void *pvt)
Switch FXS line polarity, based on answeronpolarityswitch=yes.
int(*const callwait)(void *pvt)
void(*const cancel_cidspill)(void *pvt)
int(*const check_confirmanswer)(void *pvt)
int(*const check_for_conference)(void *pvt)
int(*const check_waitingfordt)(void *pvt)
int(*const complete_conference_update)(void *pvt, int needconf)
int(*const conf_add)(void *pvt, enum analog_sub sub)
int(*const conf_del)(void *pvt, enum analog_sub sub)
int(*const confmute)(void *pvt, int mute)
void(*const deadlock_avoidance_private)(void *pvt)
void(*const decrease_ss_count)(void)
int(*const dial_digits)(void *pvt, enum analog_sub sub, struct analog_dialoperation *dop)
int(*const distinctive_ring)(struct ast_channel *chan, void *pvt, int idx, int *ringdata)
int(*const dsp_reset_and_flush_digits)(void *pvt)
int(*const dsp_set_digitmode)(void *pvt, enum analog_dsp_digitmode mode)
int(*const flash)(void *pvt)
void(*const get_and_handle_alarms)(void *pvt)
int(*const get_callerid)(void *pvt, char *name, char *num, enum analog_event *ev, size_t timeout)
int(*const get_event)(void *pvt)
int(*const get_firstdigit_timeout)(void *pvt)
int(*const get_interdigit_timeout)(void *pvt)
int(*const get_matchdigit_timeout)(void *pvt)
const char *(*const get_orig_dialstring)(void *pvt)
void *(*const get_sigpvt_bridged_channel)(struct ast_channel *chan)
int(*const get_sub_fd)(void *pvt, enum analog_sub sub)
void(*const handle_dtmf)(void *pvt, struct ast_channel *ast, enum analog_sub analog_index, struct ast_frame **dest)
void(*const handle_notify_message)(struct ast_channel *chan, void *pvt, int cid_flags, int neon_mwievent)
void(*const hangup_polarityswitch)(void *pvt)
Switch FXS line polarity, based on answeronpolarityswitch and hanguponpolarityswitch.
int(*const has_voicemail)(void *pvt)
int(*const have_progressdetect)(void *pvt)
void(*const increase_ss_count)(void)
int(*const is_dialing)(void *pvt, enum analog_sub sub)
int(*const is_off_hook)(void *pvt)
void(*const lock_private)(void *pvt)
struct ast_channel *(*const new_ast_channel)(void *pvt, int state, int startpbx, enum analog_sub sub, const struct ast_channel *requestor)
int(*const off_hook)(void *pvt)
Set channel off hook.
int(*const on_hook)(void *pvt)
Set channel on hook.
int(*const play_tone)(void *pvt, enum analog_sub sub, enum analog_tone tone)
int(*const ring)(void *pvt)
int(*const send_callerid)(void *pvt, int cwcid, struct ast_party_caller *caller)
int(*const send_fsk)(void *pvt, struct ast_channel *ast, char *fsk)
void(*const set_alarm)(void *pvt, int in_alarm)
void(*const set_cadence)(void *pvt, int *cidrings, struct ast_channel *chan)
void(*const set_callwaiting)(void *pvt, int callwaiting_enable)
void(*const set_confirmanswer)(void *pvt, int flag)
void(*const set_dialing)(void *pvt, int is_dialing)
int(*const set_echocanceller)(void *pvt, int enable)
void(*const set_inthreeway)(void *pvt, enum analog_sub sub, int inthreeway)
int(*const set_linear_mode)(void *pvt, enum analog_sub sub, int linear_mode)
void(*const set_needringing)(void *pvt, int value)
void(*const set_new_owner)(void *pvt, struct ast_channel *new_owner)
void(*const set_outgoing)(void *pvt, int is_outgoing)
void(*const set_polarity)(void *pvt, int value)
Set FXS line polarity to 0=IDLE NZ=REVERSED.
void(*const set_pulsedial)(void *pvt, int flag)
void(*const set_ringtimeout)(void *pvt, int ringt)
void(*const set_waitingfordt)(void *pvt, struct ast_channel *ast)
int(*const start)(void *pvt)
int(*const start_cid_detect)(void *pvt, int cid_signalling)
void(*const start_polarityswitch)(void *pvt)
Reset FXS line polarity to IDLE, based on answeronpolarityswitch and hanguponpolarityswitch.
int(*const stop_callwait)(void *pvt)
int(*const stop_cid_detect)(void *pvt)
void(*const swap_subs)(void *pvt, enum analog_sub a, struct ast_channel *new_a_owner, enum analog_sub b, struct ast_channel *new_b_owner)
int(*const train_echocanceller)(void *pvt)
int(*const unallocate_sub)(void *pvt, enum analog_sub sub)
void(*const unlock_private)(void *pvt)
int(*const wait_event)(void *pvt)
int(*const wink)(void *pvt, enum analog_sub sub)
Detailed Description
Definition at line 136 of file sig_analog.h.
Field Documentation
all_subchannels_hungup
void(* const all_subchannels_hungup) (void *pvt)
Definition at line 213 of file sig_analog.h.
Referenced by analog_all_subchannels_hungup().
allocate_sub
int(* const allocate_sub) (void *pvt, enum analog_sub sub)
Definition at line 195 of file sig_analog.h.
Referenced by analog_alloc_sub().
answer_polarityswitch
void(* const answer_polarityswitch) (void *pvt)
Switch FXS line polarity, based on answeronpolarityswitch=yes.
Definition at line 167 of file sig_analog.h.
Referenced by analog_answer_polarityswitch().
callwait
int(* const callwait) (void *pvt)
Definition at line 190 of file sig_analog.h.
Referenced by analog_callwait().
cancel_cidspill
void(* const cancel_cidspill) (void *pvt)
Definition at line 240 of file sig_analog.h.
Referenced by analog_cancel_cidspill().
check_confirmanswer
int(* const check_confirmanswer) (void *pvt)
Definition at line 238 of file sig_analog.h.
Referenced by analog_check_confirmanswer().
check_for_conference
int(* const check_for_conference) (void *pvt)
Definition at line 216 of file sig_analog.h.
Referenced by analog_check_for_conference().
check_waitingfordt
int(* const check_waitingfordt) (void *pvt)
Definition at line 236 of file sig_analog.h.
Referenced by analog_check_waitingfordt().
complete_conference_update
int(* const complete_conference_update) (void *pvt, int needconf)
Definition at line 209 of file sig_analog.h.
Referenced by analog_update_conf().
conf_add
int(* const conf_add) (void *pvt, enum analog_sub sub)
Definition at line 203 of file sig_analog.h.
Referenced by analog_update_conf().
conf_del
int(* const conf_del) (void *pvt, enum analog_sub sub)
Definition at line 205 of file sig_analog.h.
Referenced by analog_update_conf().
confmute
int(* const confmute) (void *pvt, int mute)
Definition at line 241 of file sig_analog.h.
Referenced by analog_confmute().
deadlock_avoidance_private
void(* const deadlock_avoidance_private) (void *pvt)
Definition at line 142 of file sig_analog.h.
Referenced by analog_deadlock_avoidance_private().
decrease_ss_count
void(* const decrease_ss_count) (void)
Definition at line 221 of file sig_analog.h.
Referenced by analog_decrease_ss_count().
dial_digits
int(* const dial_digits) (void *pvt, enum analog_sub sub, struct analog_dialoperation *dop)
Definition at line 173 of file sig_analog.h.
Referenced by analog_dial_digits().
distinctive_ring
int(* const distinctive_ring) (struct ast_channel *chan, void *pvt, int idx, int *ringdata)
Definition at line 223 of file sig_analog.h.
Referenced by analog_distinctive_ring().
dsp_reset_and_flush_digits
int(* const dsp_reset_and_flush_digits) (void *pvt)
Definition at line 180 of file sig_analog.h.
Referenced by analog_dsp_reset_and_flush_digits().
dsp_set_digitmode
int(* const dsp_set_digitmode) (void *pvt, enum analog_dsp_digitmode mode)
Definition at line 179 of file sig_analog.h.
Referenced by analog_dsp_set_digitmode().
flash
int(* const flash) (void *pvt)
Definition at line 156 of file sig_analog.h.
Referenced by analog_flash().
get_and_handle_alarms
void(* const get_and_handle_alarms) (void *pvt)
Definition at line 227 of file sig_analog.h.
Referenced by analog_get_and_handle_alarms().
get_callerid
int(* const get_callerid) (void *pvt, char *name, char *num, enum analog_event *ev, size_t timeout)
Definition at line 183 of file sig_analog.h.
Referenced by analog_get_callerid().
get_event
int(* const get_event) (void *pvt)
Definition at line 149 of file sig_analog.h.
Referenced by analog_get_event().
get_firstdigit_timeout
int(* const get_firstdigit_timeout) (void *pvt)
Definition at line 247 of file sig_analog.h.
get_interdigit_timeout
int(* const get_interdigit_timeout) (void *pvt)
Definition at line 248 of file sig_analog.h.
get_matchdigit_timeout
int(* const get_matchdigit_timeout) (void *pvt)
Definition at line 249 of file sig_analog.h.
get_orig_dialstring
const char*(* const get_orig_dialstring) (void *pvt)
Definition at line 245 of file sig_analog.h.
Referenced by analog_get_orig_dialstring().
get_sigpvt_bridged_channel
void*(* const get_sigpvt_bridged_channel) (struct ast_channel *chan)
Definition at line 228 of file sig_analog.h.
Referenced by analog_get_bridged_channel().
get_sub_fd
int(* const get_sub_fd) (void *pvt, enum analog_sub sub)
Definition at line 229 of file sig_analog.h.
Referenced by analog_get_sub_fd().
handle_dtmf
void(* const handle_dtmf) (void *pvt, struct ast_channel *ast, enum analog_sub analog_index, struct ast_frame **dest)
Definition at line 147 of file sig_analog.h.
Referenced by analog_cb_handle_dtmf().
handle_notify_message
void(* const handle_notify_message) (struct ast_channel *chan, void *pvt, int cid_flags, int neon_mwievent)
Definition at line 217 of file sig_analog.h.
Referenced by analog_handle_notify_message().
hangup_polarityswitch
void(* const hangup_polarityswitch) (void *pvt)
Switch FXS line polarity, based on answeronpolarityswitch and hanguponpolarityswitch.
Definition at line 169 of file sig_analog.h.
Referenced by analog_hangup_polarityswitch().
has_voicemail
int(* const has_voicemail) (void *pvt)
Definition at line 215 of file sig_analog.h.
Referenced by analog_has_voicemail().
have_progressdetect
int(* const have_progressdetect) (void *pvt)
Definition at line 246 of file sig_analog.h.
Referenced by analog_have_progressdetect().
increase_ss_count
void(* const increase_ss_count) (void)
Definition at line 220 of file sig_analog.h.
Referenced by analog_increase_ss_count().
is_dialing
int(* const is_dialing) (void *pvt, enum analog_sub sub)
Definition at line 152 of file sig_analog.h.
Referenced by analog_is_dialing().
is_off_hook
int(* const is_off_hook) (void *pvt)
Definition at line 151 of file sig_analog.h.
Referenced by analog_is_off_hook().
lock_private
void(* const lock_private) (void *pvt)
Definition at line 140 of file sig_analog.h.
Referenced by analog_lock_private().
new_ast_channel
struct ast_channel*(* const new_ast_channel) (void *pvt, int state, int startpbx, enum analog_sub sub, const struct ast_channel *requestor)
Definition at line 200 of file sig_analog.h.
Referenced by analog_new_ast_channel().
off_hook
int(* const off_hook) (void *pvt)
Set channel off hook.
Definition at line 160 of file sig_analog.h.
Referenced by analog_off_hook().
on_hook
int(* const on_hook) (void *pvt)
Set channel on hook.
Definition at line 158 of file sig_analog.h.
Referenced by analog_on_hook().
play_tone
int(* const play_tone) (void *pvt, enum analog_sub sub, enum analog_tone tone)
Definition at line 175 of file sig_analog.h.
Referenced by analog_play_tone().
ring
int(* const ring) (void *pvt)
Definition at line 155 of file sig_analog.h.
Referenced by analog_ring().
send_callerid
int(* const send_callerid) (void *pvt, int cwcid, struct ast_party_caller *caller)
Definition at line 181 of file sig_analog.h.
Referenced by analog_send_callerid().
send_fsk
int(* const send_fsk) (void *pvt, struct ast_channel *ast, char *fsk)
Definition at line 174 of file sig_analog.h.
set_alarm
void(* const set_alarm) (void *pvt, int in_alarm)
Definition at line 231 of file sig_analog.h.
Referenced by analog_set_alarm().
set_cadence
void(* const set_cadence) (void *pvt, int *cidrings, struct ast_channel *chan)
Definition at line 230 of file sig_analog.h.
Referenced by analog_set_cadence().
set_callwaiting
void(* const set_callwaiting) (void *pvt, int callwaiting_enable)
Definition at line 239 of file sig_analog.h.
Referenced by analog_set_callwaiting().
set_confirmanswer
void(* const set_confirmanswer) (void *pvt, int flag)
Definition at line 237 of file sig_analog.h.
Referenced by analog_set_confirmanswer().
set_dialing
void(* const set_dialing) (void *pvt, int is_dialing)
Definition at line 232 of file sig_analog.h.
Referenced by analog_set_dialing().
set_echocanceller
int(* const set_echocanceller) (void *pvt, int enable)
Definition at line 177 of file sig_analog.h.
Referenced by analog_set_echocanceller().
set_inthreeway
void(* const set_inthreeway) (void *pvt, enum analog_sub sub, int inthreeway)
Definition at line 226 of file sig_analog.h.
Referenced by analog_set_inthreeway().
set_linear_mode
int(* const set_linear_mode) (void *pvt, enum analog_sub sub, int linear_mode)
Definition at line 225 of file sig_analog.h.
Referenced by analog_set_linear_mode().
set_needringing
void(* const set_needringing) (void *pvt, int value)
Definition at line 161 of file sig_analog.h.
Referenced by analog_set_needringing().
set_new_owner
void(* const set_new_owner) (void *pvt, struct ast_channel *new_owner)
Definition at line 243 of file sig_analog.h.
Referenced by analog_set_new_owner().
set_outgoing
void(* const set_outgoing) (void *pvt, int is_outgoing)
Definition at line 233 of file sig_analog.h.
Referenced by analog_set_outgoing().
set_polarity
void(* const set_polarity) (void *pvt, int value)
Set FXS line polarity to 0=IDLE NZ=REVERSED.
Definition at line 163 of file sig_analog.h.
Referenced by analog_set_needringing().
set_pulsedial
void(* const set_pulsedial) (void *pvt, int flag)
Definition at line 242 of file sig_analog.h.
Referenced by analog_set_pulsedial().
set_ringtimeout
void(* const set_ringtimeout) (void *pvt, int ringt)
Definition at line 234 of file sig_analog.h.
Referenced by analog_set_ringtimeout().
set_waitingfordt
void(* const set_waitingfordt) (void *pvt, struct ast_channel *ast)
Definition at line 235 of file sig_analog.h.
Referenced by analog_set_waitingfordt().
start
int(* const start) (void *pvt)
Definition at line 154 of file sig_analog.h.
Referenced by analog_start().
start_cid_detect
int(* const start_cid_detect) (void *pvt, int cid_signalling)
Definition at line 185 of file sig_analog.h.
Referenced by analog_start_cid_detect().
start_polarityswitch
void(* const start_polarityswitch) (void *pvt)
Reset FXS line polarity to IDLE, based on answeronpolarityswitch and hanguponpolarityswitch.
Definition at line 165 of file sig_analog.h.
Referenced by analog_start_polarityswitch().
stop_callwait
int(* const stop_callwait) (void *pvt)
Definition at line 192 of file sig_analog.h.
Referenced by analog_stop_callwait().
stop_cid_detect
int(* const stop_cid_detect) (void *pvt)
Definition at line 187 of file sig_analog.h.
Referenced by analog_stop_cid_detect().
swap_subs
void(* const swap_subs) (void *pvt, enum analog_sub a, struct ast_channel *new_a_owner, enum analog_sub b, struct ast_channel *new_b_owner)
This function is for swapping of the owners with the underlying subs. Typically it means you need to change the fds of the new owner to be the fds of the sub specified, for each of the two subs given
Definition at line 199 of file sig_analog.h.
Referenced by analog_swap_subs().
train_echocanceller
int(* const train_echocanceller) (void *pvt)
Definition at line 178 of file sig_analog.h.
Referenced by analog_train_echocanceller().
unallocate_sub
int(* const unallocate_sub) (void *pvt, enum analog_sub sub)
Definition at line 196 of file sig_analog.h.
Referenced by analog_unalloc_sub().
unlock_private
void(* const unlock_private) (void *pvt)
Definition at line 138 of file sig_analog.h.
Referenced by analog_unlock_private().
wait_event
int(* const wait_event) (void *pvt)
Definition at line 150 of file sig_analog.h.
Referenced by analog_wait_event().
wink
int(* const wink) (void *pvt, enum analog_sub sub)
Definition at line 172 of file sig_analog.h.
Referenced by analog_wink().
The documentation for this struct was generated from the following file:
sig_analog.h