Asterisk - The Open Source Telephony Project: channelstate.h File Reference
channelstate.h File Reference
Channel states.
#include "asterisk.h"
Enumerations
enum ast_channel_state {
AST_STATE_DOWN, AST_STATE_RESERVED, AST_STATE_OFFHOOK, AST_STATE_DIALING,
AST_STATE_RING, AST_STATE_RINGING, AST_STATE_UP, AST_STATE_BUSY,
AST_STATE_DIALING_OFFHOOK, AST_STATE_PRERING, AST_STATE_MUTE = (1 << 16)
}
ast_channel states
Functions
int ast_setstate (struct ast_channel *chan, enum ast_channel_state)
Change the state of a channel.
Detailed Description
Channel states.
See also:
Asterisk Channels
Module: Asterisk Channel Drivers
Definition in file channelstate.h.
Enumeration Type Documentation
ast_channel_state
enum ast_channel_state
ast_channel states
Note
Bits 0-15 of state are reserved for the state (up/down) of the line Bits 16-32 of state are reserved for flags
Enumerator
AST_STATE_DOWN
Channel is down and available
AST_STATE_RESERVED
Channel is down, but reserved
AST_STATE_OFFHOOK
Channel is off hook
AST_STATE_DIALING
Digits (or equivalent) have been dialed
AST_STATE_RING
Line is ringing
AST_STATE_RINGING
Remote end is ringing
AST_STATE_UP
Line is up
AST_STATE_BUSY
Line is busy
AST_STATE_DIALING_OFFHOOK
Digits (or equivalent) have been dialed while offhook
AST_STATE_PRERING
Channel has detected an incoming call and is waiting for ring
AST_STATE_MUTE
Do not transmit voice data
Definition at line 35 of file channelstate.h.
{
    AST_STATE_DOWN,         /*!< Channel is down and available */
    AST_STATE_RESERVED,     /*!< Channel is down, but reserved */
    AST_STATE_OFFHOOK,      /*!< Channel is off hook */
    AST_STATE_DIALING,      /*!< Digits (or equivalent) have been dialed */
    AST_STATE_RING,         /*!< Line is ringing */
    AST_STATE_RINGING,      /*!< Remote end is ringing */
    AST_STATE_UP,        /*!< Line is up */
    AST_STATE_BUSY,         /*!< Line is busy */
    AST_STATE_DIALING_OFFHOOK, /*!< Digits (or equivalent) have been dialed while offhook */
    AST_STATE_PRERING,      /*!< Channel has detected an incoming call and is waiting for ring */
    AST_STATE_MUTE = (1 << 16),   /*!< Do not transmit voice data */
 };
Function Documentation
ast_setstate()
int ast_setstate (struct ast_channel * chan, enum ast_channel_state)
Change the state of a channel.
Precondition
chan is locked
Definition at line 7486 of file channel.c.
References ast_channel_flags(), AST_CHANNEL_NAME, ast_channel_name(), ast_channel_publish_snapshot(), ast_channel_state_set(), ast_copy_string(), AST_DEVICE_UNKNOWN, AST_DEVSTATE_CACHABLE, ast_devstate_changed_literal(), AST_DEVSTATE_NOT_CACHABLE, AST_FLAG_DISABLE_DEVSTATE_CACHE, ast_test_flag, and name.
Referenced by __analog_handle_event(), __analog_ss_thread(), __ast_read(), __dahdi_exception(), alsa_answer(), analog_answer(), analog_call(), analog_exception(), analog_ss_thread(), ast_raw_answer_with_stream_topology(), AST_TEST_DEFINE(), cb_events(), chan_pjsip_answer(), chan_pjsip_incoming_response(), console_answer(), dahdi_answer(), dahdi_call(), dahdi_handle_event(), dahdi_indicate(), dahdi_read(), handle_invite_replaces(), handle_request_invite(), handle_response_ciev(), handle_response_invite(), iax2_call(), indicate_busy(), indicate_congestion(), jingle_action_session_info(), jingle_action_session_initiate(), jingle_call(), mbl_hangup(), mgcp_answer(), mgcp_call(), mgcp_ss(), misdn_call(), misdn_indication(), my_set_waitingfordt(), nbs_call(), nbs_hangup(), onAlerting(), onProgress(), ooh323_answer(), ooh323_new(), oss_answer(), phone_answer(), phone_call(), phone_exception(), phone_hangup(), phone_write(), refer_incoming_invite_request(), release_chan(), release_chan_early(), setsubstate(), sip_answer(), skinny_newcall(), unistim_answer(), unistim_call(), unistim_new(), unistim_ss(), and unreal_queue_frame().
 {
    int oldstate = ast_channel_state(chan);
    char name[AST_CHANNEL_NAME], *dashptr;
    if (oldstate == state)
       return 0;
    ast_copy_string(name, ast_channel_name(chan), sizeof(name));
    if ((dashptr = strrchr(name, '-'))) {
       *dashptr = '\0';
    }
    ast_channel_state_set(chan, state);
    ast_channel_publish_snapshot(chan);
    /* We have to pass AST_DEVICE_UNKNOWN here because it is entirely possible that the channel driver
     * for this channel is using the callback method for device state. If we pass in an actual state here
     * we override what they are saying the state is and things go amuck. */
    ast_devstate_changed_literal(AST_DEVICE_UNKNOWN, (ast_test_flag(ast_channel_flags(chan), AST_FLAG_DISABLE_DEVSTATE_CACHE) ? AST_DEVSTATE_NOT_CACHABLE : AST_DEVSTATE_CACHABLE), name);
    return 0;
 }