Asterisk - The Open Source Telephony Project: command.h File Reference
command.h File Reference
Internal API for the Stasis application commands.
#include "asterisk/stasis_app_impl.h"
Functions
void command_complete (struct stasis_app_command *command, int retval)
struct stasis_app_command * command_create (stasis_app_command_cb callback, void *data, command_data_destructor_fn data_destructor)
void command_invoke (struct stasis_app_command *command, struct stasis_app_control *control, struct ast_channel *chan)
int command_join (struct stasis_app_command *command)
struct ao2_container * command_prestart_get_container (struct ast_channel *chan)
Get the Stasis() prestart commands for a channel.
int command_prestart_queue_command (struct ast_channel *chan, stasis_app_command_cb command_fn, void *data, command_data_destructor_fn data_destructor)
Queue a Stasis() prestart command for a channel.
Detailed Description
Internal API for the Stasis application commands.
Author
David M. Lee, II dlee@.nosp@m.digi.nosp@m.um.co.nosp@m.m
Since
12
Definition in file command.h.
Function Documentation
command_complete()
void command_complete (struct stasis_app_command * command, int retval)
Definition at line 77 of file command.c.
References ast_cond_signal, ast_mutex_lock, ast_mutex_unlock, stasis_app_command::condition, stasis_app_command::is_done, stasis_app_command::lock, and stasis_app_command::retval.
Referenced by command_invoke(), control_flush_queue(), and exec_command_on_condition().
 {
    ast_mutex_lock(&command->lock);
    command->is_done = 1;
    command->retval = retval;
    ast_cond_signal(&command->condition);
    ast_mutex_unlock(&command->lock);
 }
command_create()
struct stasis_app_command* command_create (stasis_app_command_cb callback, void * data, command_data_destructor_fn data_destructor)
Definition at line 55 of file command.c.
References ao2_alloc, ast_cond_init, ast_mutex_init, stasis_app_command::callback, command_dtor(), stasis_app_command::condition, stasis_app_command::data, stasis_app_command::data_destructor, stasis_app_command::lock, and NULL.
Referenced by command_prestart_queue_command(), and exec_command_on_condition().
 {
    struct stasis_app_command *command;
    command = ao2_alloc(sizeof(*command), command_dtor);
    if (!command) {
       if (data_destructor) {
          data_destructor(data);
       }
       return NULL;
    }
    ast_mutex_init(&command->lock);
    ast_cond_init(&command->condition, 0);
    command->callback = callback;
    command->data = data;
    command->data_destructor = data_destructor;
    return command;
 }
command_invoke()
void command_invoke (struct stasis_app_command * command, struct stasis_app_control * control, struct ast_channel * chan)
Definition at line 101 of file command.c.
References stasis_app_command::callback, command_complete(), stasis_app_command::data, stasis_app_command::data_destructor, NULL, and stasis_app_command::retval.
Referenced by control_dispatch_all(), and control_prestart_dispatch_all().
 {
    int retval = command->callback(control, chan, command->data);
    if (command->data_destructor) {
       command->data_destructor(command->data);
       command->data_destructor = NULL;
    }
    command_complete(command, retval);
 }
command_join()
int command_join (struct stasis_app_command * command)
Definition at line 86 of file command.c.
References ast_cond_wait, ast_mutex_lock, ast_mutex_unlock, stasis_app_command::condition, stasis_app_command::is_done, stasis_app_command::lock, and stasis_app_command::retval.
Referenced by app_send_command_on_condition().
 {
    int ret;
    ast_mutex_lock(&command->lock);
    while (!command->is_done) {
       ast_cond_wait(&command->condition, &command->lock);
    }
    ret = command->retval;
    ast_mutex_unlock(&command->lock);
    return ret;
 }
command_prestart_get_container()
struct ao2_container* command_prestart_get_container (struct ast_channel * chan)
Get the Stasis() prestart commands for a channel.
Precondition
chan must be locked
Parameters
chan The channel from which to get prestart commands
Returns
The command prestart container for chan (must be ao2_cleanup()'d)
Definition at line 160 of file command.c.
References ao2_bump, ast_channel_datastore_find(), ast_datastore::data, and NULL.
Referenced by control_prestart_dispatch_all().
 {
    struct ast_datastore *datastore = ast_channel_datastore_find(chan, &command_queue_prestart, NULL);
    if (!datastore) {
       return NULL;
    }
    return ao2_bump(datastore->data);
 }
command_prestart_queue_command()
int command_prestart_queue_command (struct ast_channel * chan, stasis_app_command_cb command_fn, void * data, command_data_destructor_fn data_destructor)
Queue a Stasis() prestart command for a channel.
Precondition
chan must be locked
Parameters
chan The channel on which to queue the prestart command
command_fn The callback to call for the command
data The data to pass to the command callback
data_destructor Optional function which will be called on the data in either the event of command completion or failure to schedule or complete the command
Return values
zero on success
non-zero on failure
Definition at line 123 of file command.c.
References AO2_ALLOC_OPT_LOCK_MUTEX, ao2_cleanup, ao2_container_alloc_list, ao2_link, ast_channel_datastore_add(), ast_channel_datastore_find(), ast_datastore_alloc, command_create(), ast_datastore::data, NULL, and RAII_VAR.
Referenced by bridge_stasis_queue_join_action().
 {
    struct ast_datastore *datastore;
    struct ao2_container *command_queue;
    RAII_VAR(struct stasis_app_command *, command,
       command_create(command_fn, data, data_destructor), ao2_cleanup);
    if (!command) {
       return -1;
    }
    datastore = ast_channel_datastore_find(chan, &command_queue_prestart, NULL);
    if (datastore) {
       command_queue = datastore->data;
       ao2_link(command_queue, command);
       return 0;
    }
    command_queue = ao2_container_alloc_list(AO2_ALLOC_OPT_LOCK_MUTEX, 0, NULL, NULL);
    if (!command_queue) {
       return -1;
    }
    datastore = ast_datastore_alloc(&command_queue_prestart, NULL);
    if (!datastore) {
       ao2_cleanup(command_queue);
       return -1;
    }
    ast_channel_datastore_add(chan, datastore);
    datastore->data = command_queue;
    ao2_link(command_queue, command);
    return 0;
 }