Asterisk - The Open Source Telephony Project: pbx_sw.c File Reference
pbx_sw.c File Reference
Dialplan switch routines.
#include "asterisk.h"
#include "asterisk/_private.h"
#include "asterisk/pbx.h"
#include "pbx_private.h"
Data Structures
struct ast_sw
ast_sw: Switch statement in extensions.conf
Functions
const char * ast_get_switch_data (const struct ast_sw *sw)
int ast_get_switch_eval (const struct ast_sw *sw)
const char * ast_get_switch_name (const struct ast_sw *sw)
const char * ast_get_switch_registrar (const struct ast_sw *sw)
struct ast_sw * sw_alloc (const char *value, const char *data, int eval, const char *registrar)
void sw_free (struct ast_sw *sw)
Detailed Description
Dialplan switch routines.
Author
Corey Farrell git@c.nosp@m.fwar.nosp@m.e.com
Definition in file pbx_sw.c.
Function Documentation
ast_get_switch_data()
const char* ast_get_switch_data (const struct ast_sw * sw)
Definition at line 53 of file pbx_sw.c.
References ast_sw::data, and NULL.
Referenced by ast_context_add_switch2(), ast_context_remove_switch2(), context_merge_incls_swits_igps_other_registrars(), handle_cli_dialplan_save(), manager_show_dialplan_helper(), pbx_find_extension(), and show_dialplan_helper().
 {
    return sw ? sw->data : NULL;
 }
ast_get_switch_eval()
int ast_get_switch_eval (const struct ast_sw * sw)
Definition at line 58 of file pbx_sw.c.
References ast_sw::eval.
Referenced by context_merge_incls_swits_igps_other_registrars(), and pbx_find_extension().
 {
    return sw->eval;
 }
ast_get_switch_name()
const char* ast_get_switch_name (const struct ast_sw * sw)
Definition at line 48 of file pbx_sw.c.
References ast_sw::name, and NULL.
Referenced by ast_context_add_switch2(), ast_context_remove_switch2(), context_merge_incls_swits_igps_other_registrars(), handle_cli_dialplan_save(), manager_show_dialplan_helper(), pbx_find_extension(), and show_dialplan_helper().
 {
    return sw ? sw->name : NULL;
 }
ast_get_switch_registrar()
const char* ast_get_switch_registrar (const struct ast_sw * sw)
Definition at line 63 of file pbx_sw.c.
References NULL, and ast_sw::registrar.
Referenced by __ast_context_destroy(), ast_context_remove_switch2(), context_merge_incls_swits_igps_other_registrars(), handle_cli_dialplan_save(), manager_show_dialplan_helper(), and show_dialplan_helper().
 {
    return sw ? sw->registrar : NULL;
 }
sw_alloc()
struct ast_sw* sw_alloc (const char * value, const char * data, int eval, const char * registrar)
Definition at line 68 of file pbx_sw.c.
References ast_calloc, ast_sw::data, ast_sw::eval, ast_sw::name, NULL, ast_sw::registrar, and ast_sw::stuff.
Referenced by ast_context_add_switch2().
 {
    struct ast_sw *new_sw;
    int length;
    char *p;
    if (!data) {
       data = "";
    }
    length = sizeof(struct ast_sw);
    length += strlen(value) + 1;
    length += strlen(data) + 1;
    /* allocate new sw structure ... */
    if (!(new_sw = ast_calloc(1, length))) {
       return NULL;
    }
    /* ... fill in this structure ... */
    p = new_sw->stuff;
    new_sw->name = p;
    strcpy(p, value);
    p += strlen(value) + 1;
    new_sw->data = p;
    strcpy(p, data);
    new_sw->eval     = eval;
    new_sw->registrar = registrar;
    return new_sw;
 }
sw_free()
void sw_free (struct ast_sw * sw)
Definition at line 101 of file pbx_sw.c.
References ast_free.
Referenced by __ast_context_destroy(), __ast_internal_context_destroy(), ast_context_add_switch2(), and ast_context_remove_switch2().
 {
    ast_free(sw);
 }