Asterisk - The Open Source Telephony Project: app_page.c File Reference
app_page.c File Reference
Dial plan applications
page() - Paging application
#include "asterisk.h"
#include "asterisk/channel.h"
#include "asterisk/pbx.h"
#include "asterisk/module.h"
#include "asterisk/file.h"
#include "asterisk/app.h"
#include "asterisk/chanvars.h"
#include "asterisk/utils.h"
#include "asterisk/devicestate.h"
#include "asterisk/dial.h"
Data Structures
struct page_options
Macros
#define PAGE_BEEP "beep"
Enumerations
enum { OPT_ARG_ANNOUNCE = 0, OPT_ARG_PREDIAL_CALLEE = 1, OPT_ARG_PREDIAL_CALLER = 2, OPT_ARG_ARRAY_SIZE = 3 }
enum page_opt_flags {
PAGE_DUPLEX = (1 << 0), PAGE_QUIET = (1 << 1), PAGE_RECORD = (1 << 2), PAGE_SKIP = (1 << 3),
PAGE_IGNORE_FORWARDS = (1 << 4), PAGE_ANNOUNCE = (1 << 5), PAGE_NOCALLERANNOUNCE = (1 << 6), PAGE_PREDIAL_CALLEE = (1 << 7),
PAGE_PREDIAL_CALLER = (1 << 8)
}
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int load_module (void)
static int page_exec (struct ast_channel *chan, const char *data)
static void page_state_callback (struct ast_dial *dial)
static void setup_profile_bridge (struct ast_channel *chan, struct page_options *options)
static void setup_profile_caller (struct ast_channel *chan, struct page_options *options)
static void setup_profile_paged (struct ast_channel *chan, struct page_options *options)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_DEFAULT , .description = "Page Multiple Phones" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .requires = "app_confbridge", }
static const char *const app_page = "Page"
static const struct ast_module_info * ast_module_info = &__mod_info
static const struct ast_app_option page_opts [128] = { [ 'b' ] = { .flag = PAGE_PREDIAL_CALLEE , .arg_index = OPT_ARG_PREDIAL_CALLEE + 1 }, [ 'B' ] = { .flag = PAGE_PREDIAL_CALLER , .arg_index = OPT_ARG_PREDIAL_CALLER + 1 }, [ 'd' ] = { .flag = PAGE_DUPLEX }, [ 'q' ] = { .flag = PAGE_QUIET }, [ 'r' ] = { .flag = PAGE_RECORD }, [ 's' ] = { .flag = PAGE_SKIP }, [ 'i' ] = { .flag = PAGE_IGNORE_FORWARDS }, [ 'A' ] = { .flag = PAGE_ANNOUNCE , .arg_index = OPT_ARG_ANNOUNCE + 1 }, [ 'n' ] = { .flag = PAGE_NOCALLERANNOUNCE }, }
Detailed Description
page() - Paging application
Author
Mark Spencer marks.nosp@m.ter@.nosp@m.digiu.nosp@m.m.co.nosp@m.m
Definition in file app_page.c.
Macro Definition Documentation
PAGE_BEEP
#define PAGE_BEEP "beep"
Definition at line 163 of file app_page.c.
Referenced by page_exec().
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
OPT_ARG_ANNOUNCE
OPT_ARG_PREDIAL_CALLEE
OPT_ARG_PREDIAL_CALLER
OPT_ARG_ARRAY_SIZE
Definition at line 144 of file app_page.c.
      {
    OPT_ARG_ANNOUNCE = 0,
    OPT_ARG_PREDIAL_CALLEE = 1,
    OPT_ARG_PREDIAL_CALLER = 2,
    OPT_ARG_ARRAY_SIZE = 3,
 };
page_opt_flags
enum page_opt_flags
Enumerator
PAGE_DUPLEX
PAGE_QUIET
PAGE_RECORD
PAGE_SKIP
PAGE_IGNORE_FORWARDS
PAGE_ANNOUNCE
PAGE_NOCALLERANNOUNCE
PAGE_PREDIAL_CALLEE
PAGE_PREDIAL_CALLER
Definition at line 132 of file app_page.c.
                     {
    PAGE_DUPLEX = (1 << 0),
    PAGE_QUIET = (1 << 1),
    PAGE_RECORD = (1 << 2),
    PAGE_SKIP = (1 << 3),
    PAGE_IGNORE_FORWARDS = (1 << 4),
    PAGE_ANNOUNCE = (1 << 5),
    PAGE_NOCALLERANNOUNCE = (1 << 6),
    PAGE_PREDIAL_CALLEE = (1 << 7),
    PAGE_PREDIAL_CALLER = (1 << 8),
 };
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 459 of file app_page.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 459 of file app_page.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 459 of file app_page.c.
load_module()
static int load_module (void) static
Definition at line 449 of file app_page.c.
References app_page, AST_MODFLAG_DEFAULT, AST_MODULE_INFO(), AST_MODULE_SUPPORT_CORE, ast_register_application_xml, ASTERISK_GPL_KEY, page_exec(), and unload_module().
 {
    return ast_register_application_xml(app_page, page_exec);
 }
page_exec()
static int page_exec (struct ast_channel * chan, const char * data) static
Definition at line 250 of file app_page.c.
References app, args, AST_APP_ARG, ast_app_exec_sub(), ast_app_expand_sub_args(), ast_app_parse_options(), ast_calloc, ast_channel_language(), AST_CHANNEL_NAME, ast_channel_name(), ast_copy_string(), AST_DECLARE_APP_ARGS, AST_DEVICE_NOT_INUSE, AST_DEVICE_UNKNOWN, ast_devstate2str(), ast_dial_append(), ast_dial_create(), ast_dial_destroy(), ast_dial_hangup(), ast_dial_join(), AST_DIAL_OPTION_ANSWER_EXEC, AST_DIAL_OPTION_DISABLE_CALL_FORWARDING, ast_dial_option_global_enable(), AST_DIAL_OPTION_PREDIAL, ast_dial_run(), ast_dial_set_global_timeout(), ast_dial_set_state_callback(), ast_dial_set_user_data(), ast_fileexists(), ast_free, ast_log, ast_random(), ast_replace_subargument_delimiter(), AST_STANDARD_APP_ARGS, ast_strdupa, ast_streamfile(), ast_strip(), ast_strlen_zero, ast_test_flag, ast_verb, ast_waitstream(), page_options::flags, LOG_ERROR, LOG_WARNING, NULL, OPT_ARG_PREDIAL_CALLEE, OPT_ARG_PREDIAL_CALLER, page_options::opts, PAGE_BEEP, PAGE_IGNORE_FORWARDS, page_opts, PAGE_PREDIAL_CALLEE, PAGE_PREDIAL_CALLER, PAGE_QUIET, PAGE_SKIP, page_state_callback(), parse(), pbx_exec(), pbx_findapp(), setup_profile_bridge(), setup_profile_caller(), strsep(), timeout, and tmp().
Referenced by load_module().
 {
    char *tech;
    char *resource;
    char *tmp;
    char *predial_callee = NULL;
    char confbridgeopts[128];
    char originator[AST_CHANNEL_NAME];
    struct page_options options = { { 0, }, { 0, } };
    unsigned int confid = ast_random();
    struct ast_app *app;
    int res = 0;
    int pos = 0;
    int i = 0;
    struct ast_dial **dial_list;
    unsigned int num_dials;
    int timeout = 0;
    char *parse;
    AST_DECLARE_APP_ARGS(args,
       AST_APP_ARG(devices);
       AST_APP_ARG(options);
       AST_APP_ARG(timeout);
    );
    if (!(app = pbx_findapp("ConfBridge"))) {
       ast_log(LOG_WARNING, "There is no ConfBridge application available!\n");
       return -1;
    };
    parse = ast_strdupa(data ?: "");
    AST_STANDARD_APP_ARGS(args, parse);
    ast_copy_string(originator, ast_channel_name(chan), sizeof(originator));
    if ((tmp = strchr(originator, '-'))) {
       *tmp = '\0';
    }
    if (!ast_strlen_zero(args.options)) {
       ast_app_parse_options(page_opts, &options.flags, options.opts, args.options);
    }
    if (!ast_strlen_zero(args.timeout)) {
       timeout = atoi(args.timeout);
    }
    snprintf(confbridgeopts, sizeof(confbridgeopts), "ConfBridge,%u", confid);
    /* Count number of extensions in list by number of ampersands + 1 */
    num_dials = 1;
    tmp = args.devices ?: "";
    while (*tmp) {
       if (*tmp == '&') {
          num_dials++;
       }
       tmp++;
    }
    if (!(dial_list = ast_calloc(num_dials, sizeof(struct ast_dial *)))) {
       ast_log(LOG_ERROR, "Can't allocate %ld bytes for dial list\n", (long)(sizeof(struct ast_dial *) * num_dials));
       return -1;
    }
    /* PREDIAL: Preprocess any callee gosub arguments. */
    if (ast_test_flag(&options.flags, PAGE_PREDIAL_CALLEE)
       && !ast_strlen_zero(options.opts[OPT_ARG_PREDIAL_CALLEE])) {
       ast_replace_subargument_delimiter(options.opts[OPT_ARG_PREDIAL_CALLEE]);
       predial_callee =
          (char *) ast_app_expand_sub_args(chan, options.opts[OPT_ARG_PREDIAL_CALLEE]);
    }
    /* PREDIAL: Run gosub on the caller's channel */
    if (ast_test_flag(&options.flags, PAGE_PREDIAL_CALLER)
       && !ast_strlen_zero(options.opts[OPT_ARG_PREDIAL_CALLER])) {
       ast_replace_subargument_delimiter(options.opts[OPT_ARG_PREDIAL_CALLER]);
       ast_app_exec_sub(NULL, chan, options.opts[OPT_ARG_PREDIAL_CALLER], 0);
    }
    /* Go through parsing/calling each device */
    while ((tech = strsep(&args.devices, "&"))) {
       int state = 0;
       struct ast_dial *dial = NULL;
       tech = ast_strip(tech);
       if (ast_strlen_zero(tech)) {
          /* No tech/resource in this position. */
          continue;
       }
       /* don't call the originating device */
       if (!strcasecmp(tech, originator)) {
          continue;
       }
       /* If no resource is available, continue on */
       if (!(resource = strchr(tech, '/'))) {
          ast_log(LOG_WARNING, "Incomplete destination: '%s' supplied.\n", tech);
          continue;
       }
       /* Ensure device is not in use if skip option is enabled */
       if (ast_test_flag(&options.flags, PAGE_SKIP)) {
          state = ast_device_state(tech);
          if (state == AST_DEVICE_UNKNOWN) {
             ast_verb(3, "Destination '%s' has device state '%s'. Paging anyway.\n",
                tech, ast_devstate2str(state));
          } else if (state != AST_DEVICE_NOT_INUSE) {
             ast_verb(3, "Destination '%s' has device state '%s'.\n",
                tech, ast_devstate2str(state));
             continue;
          }
       }
       *resource++ = '\0';
       /* Create a dialing structure */
       if (!(dial = ast_dial_create())) {
          ast_log(LOG_WARNING, "Failed to create dialing structure.\n");
          continue;
       }
       /* Append technology and resource */
       if (ast_dial_append(dial, tech, resource, NULL) == -1) {
          ast_log(LOG_ERROR, "Failed to add %s/%s to outbound dial\n", tech, resource);
          ast_dial_destroy(dial);
          continue;
       }
       /* Set ANSWER_EXEC as global option */
       ast_dial_option_global_enable(dial, AST_DIAL_OPTION_ANSWER_EXEC, confbridgeopts);
       if (predial_callee) {
          ast_dial_option_global_enable(dial, AST_DIAL_OPTION_PREDIAL, predial_callee);
       }
       if (timeout) {
          ast_dial_set_global_timeout(dial, timeout * 1000);
       }
       if (ast_test_flag(&options.flags, PAGE_IGNORE_FORWARDS)) {
          ast_dial_option_global_enable(dial, AST_DIAL_OPTION_DISABLE_CALL_FORWARDING, NULL);
       }
       ast_dial_set_state_callback(dial, &page_state_callback);
       ast_dial_set_user_data(dial, &options);
       /* Run this dial in async mode */
       ast_dial_run(dial, chan, 1);
       /* Put in our dialing array */
       dial_list[pos++] = dial;
    }
    ast_free(predial_callee);
    if (!ast_test_flag(&options.flags, PAGE_QUIET)) {
       if (!ast_fileexists(PAGE_BEEP, NULL, NULL)) {
          ast_log(LOG_WARNING, "Missing required sound file: '" PAGE_BEEP "'\n");
       } else {
          res = ast_streamfile(chan, PAGE_BEEP, ast_channel_language(chan));
          if (!res) {
             res = ast_waitstream(chan, "");
          }
       }
    }
    if (!res) {
       setup_profile_bridge(chan, &options);
       setup_profile_caller(chan, &options);
       snprintf(confbridgeopts, sizeof(confbridgeopts), "%u", confid);
       pbx_exec(chan, app, confbridgeopts);
    }
    /* Go through each dial attempt cancelling, joining, and destroying */
    for (i = 0; i < pos; i++) {
       struct ast_dial *dial = dial_list[i];
       /* We have to wait for the async thread to exit as it's possible ConfBridge won't throw them out immediately */
       ast_dial_join(dial);
       /* Hangup all channels */
       ast_dial_hangup(dial);
       /* Destroy dialing structure */
       ast_dial_destroy(dial);
    }
    ast_free(dial_list);
    return -1;
 }
page_state_callback()
static void page_state_callback (struct ast_dial * dial) static
Definition at line 235 of file app_page.c.
References ast_dial_answered(), ast_dial_get_user_data(), AST_DIAL_RESULT_ANSWERED, ast_dial_state(), options, setup_profile_bridge(), and setup_profile_paged().
Referenced by page_exec().
 {
    struct ast_channel *chan;
    struct page_options *options;
    if (ast_dial_state(dial) != AST_DIAL_RESULT_ANSWERED ||
        !(chan = ast_dial_answered(dial)) ||
        !(options = ast_dial_get_user_data(dial))) {
       return;
    }
    setup_profile_bridge(chan, options);
    setup_profile_paged(chan, options);
 }
setup_profile_bridge()
static void setup_profile_bridge (struct ast_channel * chan, struct page_options * options) static
Definition at line 180 of file app_page.c.
References ast_func_write(), ast_test_flag, page_options::flags, and PAGE_RECORD.
Referenced by page_exec(), and page_state_callback().
 {
    /* Use default_bridge as a starting point */
    ast_func_write(chan, "CONFBRIDGE(bridge,template)", "");
    if (ast_test_flag(&options->flags, PAGE_RECORD)) {
       ast_func_write(chan, "CONFBRIDGE(bridge,record_conference)", "yes");
    }
 }
setup_profile_caller()
static void setup_profile_caller (struct ast_channel * chan, struct page_options * options) static
Definition at line 222 of file app_page.c.
References ast_func_write(), ast_strlen_zero, ast_test_flag, page_options::flags, OPT_ARG_ANNOUNCE, page_options::opts, PAGE_ANNOUNCE, and PAGE_NOCALLERANNOUNCE.
Referenced by page_exec().
 {
    /* Use default_user as a starting point if not already setup. */
    ast_func_write(chan, "CONFBRIDGE(user,template)", "");
    ast_func_write(chan, "CONFBRIDGE(user,quiet)", "yes");
    ast_func_write(chan, "CONFBRIDGE(user,marked)", "yes");
    if (!ast_test_flag(&options->flags, PAGE_NOCALLERANNOUNCE)
       && ast_test_flag(&options->flags, PAGE_ANNOUNCE)
       && !ast_strlen_zero(options->opts[OPT_ARG_ANNOUNCE])) {
       ast_func_write(chan, "CONFBRIDGE(user,announcement)", options->opts[OPT_ARG_ANNOUNCE]);
    }
 }
setup_profile_paged()
static void setup_profile_paged (struct ast_channel * chan, struct page_options * options) static
Definition at line 198 of file app_page.c.
References ast_func_write(), ast_strlen_zero, ast_test_flag, page_options::flags, OPT_ARG_ANNOUNCE, page_options::opts, PAGE_ANNOUNCE, and PAGE_DUPLEX.
Referenced by page_state_callback().
 {
    /* Use default_user as a starting point */
    ast_func_write(chan, "CONFBRIDGE(user,template)", "");
    ast_func_write(chan, "CONFBRIDGE(user,quiet)", "yes");
    ast_func_write(chan, "CONFBRIDGE(user,end_marked)", "yes");
    if (!ast_test_flag(&options->flags, PAGE_DUPLEX)) {
       ast_func_write(chan, "CONFBRIDGE(user,startmuted)", "yes");
    }
    if (ast_test_flag(&options->flags, PAGE_ANNOUNCE)
       && !ast_strlen_zero(options->opts[OPT_ARG_ANNOUNCE])) {
       ast_func_write(chan, "CONFBRIDGE(user,announcement)", options->opts[OPT_ARG_ANNOUNCE]);
    }
 }
unload_module()
static int unload_module (void) static
Definition at line 444 of file app_page.c.
References app_page, and ast_unregister_application().
Referenced by load_module().
 {
    return ast_unregister_application(app_page);
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_DEFAULT , .description = "Page Multiple Phones" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .requires = "app_confbridge", } static
Definition at line 459 of file app_page.c.
app_page
const char* const app_page = "Page" static
Definition at line 130 of file app_page.c.
Referenced by load_module(), and unload_module().
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 459 of file app_page.c.
page_opts
const struct ast_app_option page_opts[128] = { [ 'b' ] = { .flag = PAGE_PREDIAL_CALLEE , .arg_index = OPT_ARG_PREDIAL_CALLEE + 1 }, [ 'B' ] = { .flag = PAGE_PREDIAL_CALLER , .arg_index = OPT_ARG_PREDIAL_CALLER + 1 }, [ 'd' ] = { .flag = PAGE_DUPLEX }, [ 'q' ] = { .flag = PAGE_QUIET }, [ 'r' ] = { .flag = PAGE_RECORD }, [ 's' ] = { .flag = PAGE_SKIP }, [ 'i' ] = { .flag = PAGE_IGNORE_FORWARDS }, [ 'A' ] = { .flag = PAGE_ANNOUNCE , .arg_index = OPT_ARG_ANNOUNCE + 1 }, [ 'n' ] = { .flag = PAGE_NOCALLERANNOUNCE }, } static
Definition at line 161 of file app_page.c.
Referenced by page_exec().