Asterisk - The Open Source Telephony Project: res_pjsip_dtmf_info.c File Reference
res_pjsip_dtmf_info.c File Reference
#include "asterisk.h"
#include <pjsip.h>
#include <pjsip_ua.h>
#include "asterisk/res_pjsip.h"
#include "asterisk/res_pjsip_session.h"
#include "asterisk/module.h"
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int dtmf_info_incoming_request (struct ast_sip_session *session, struct pjsip_rx_data *rdata)
static char get_event (const char *c)
static int is_media_type (pjsip_rx_data *rdata, char *subtype)
static int load_module (void)
static void send_response (struct ast_sip_session *session, struct pjsip_rx_data *rdata, int code)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "PJSIP DTMF INFO Support" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_APP_DEPEND, .requires = "res_pjsip,res_pjsip_session", }
static const struct ast_module_info * ast_module_info = &__mod_info
static struct ast_sip_session_supplement dtmf_info_supplement
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 182 of file res_pjsip_dtmf_info.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 182 of file res_pjsip_dtmf_info.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 182 of file res_pjsip_dtmf_info.c.
dtmf_info_incoming_request()
static int dtmf_info_incoming_request (struct ast_sip_session * session, struct pjsip_rx_data * rdata) static
Definition at line 82 of file res_pjsip_dtmf_info.c.
References AST_CONTROL_FLASH, AST_FRAME_CONTROL, AST_FRAME_DTMF, ast_log, ast_queue_frame(), ast_skip_blanks(), buf, c, ast_sip_session::channel, get_event(), ast_frame_subclass::integer, is_media_type(), ast_frame::len, LOG_ERROR, send_response(), strsep(), and ast_frame::subclass.
 {
    pjsip_msg_body *body = rdata->msg_info.msg->body;
    char buf[body ? body->len + 1 : 1];
    char *cur = buf;
    char *line;
    char event = '\0';
    unsigned int duration = 100;
    char is_dtmf, is_dtmf_relay, is_flash;
    int res;
    if (!session->channel) {
       return 0;
    }
    is_dtmf = is_media_type(rdata, "dtmf");
    is_dtmf_relay = is_media_type(rdata, "dtmf-relay");
    is_flash = is_media_type(rdata, "hook-flash");
    if (!is_flash && !is_dtmf && !is_dtmf_relay) {
       return 0;
    }
    if (!body || !body->len) {
       /* need to return 200 OK on empty body */
       send_response(session, rdata, 200);
       return 1;
    }
    res = body->print_body(body, buf, body->len);
    if (res < 0) {
       send_response(session, rdata, 500);
       return 1;
    }
    buf[res] = '\0';
    if (is_dtmf) {
       /* directly use what is in the message body */
       event = get_event(cur);
    } else if (is_dtmf_relay) { /* content type = application/dtmf-relay */
       while ((line = strsep(&cur, "\r\n"))) {
          char *c;
          if (!(c = strchr(line, '='))) {
             continue;
          }
          *c++ = '\0';
          c = ast_skip_blanks(c);
          if (!strcasecmp(line, "signal")) {
             if (!(event = get_event(c))) {
                break;
             }
          } else if (!strcasecmp(line, "duration")) {
             sscanf(c, "%30u", &duration);
          }
       }
    }
    if (event == '!' || is_flash) {
       struct ast_frame f = { AST_FRAME_CONTROL, { AST_CONTROL_FLASH, } };
       ast_queue_frame(session->channel, &f);
    } else if (event != '\0') {
       struct ast_frame f = { AST_FRAME_DTMF, };
       f.len = duration;
       f.subclass.integer = event;
       ast_queue_frame(session->channel, &f);
    } else {
       ast_log(LOG_ERROR, "Invalid DTMF event signal in INFO message.\n");
    }
    send_response(session, rdata, event ? 200 : 500);
    return 1;
 }
get_event()
static char get_event (const char * c) static
Definition at line 55 of file res_pjsip_dtmf_info.c.
References c.
Referenced by dtmf_info_incoming_request().
 {
    unsigned int event;
    if (*c == '!' || *c == '*' || *c == '#' ||
        ('A' <= *c && *c <= 'D') ||
        ('a' <= *c && *c <= 'd')) {
       return *c;
    }
    if ((sscanf(c, "%30u", &event) != 1) || event > 16) {
       return '\0';
    }
    if (event < 10) {
       return *c;
    }
    switch (event) {
    case 10: return '*';
    case 11: return '#';
    case 16: return '!';
    }
    return 'A' + (event - 12);
 }
is_media_type()
static int is_media_type (pjsip_rx_data * rdata, char * subtype) static
Definition at line 35 of file res_pjsip_dtmf_info.c.
Referenced by dtmf_info_incoming_request().
 {
    return rdata->msg_info.ctype
       && !pj_strcmp2(&rdata->msg_info.ctype->media.type, "application")
       && !pj_strcmp2(&rdata->msg_info.ctype->media.subtype, subtype);
 }
load_module()
static int load_module (void) static
Definition at line 164 of file res_pjsip_dtmf_info.c.
References AST_MODULE_LOAD_SUCCESS, and ast_sip_session_register_supplement.
Referenced by unload_module().
 {
    ast_sip_session_register_supplement(&dtmf_info_supplement);
    return AST_MODULE_LOAD_SUCCESS;
 }
send_response()
static void send_response (struct ast_sip_session * session, struct pjsip_rx_data * rdata, int code) static
Definition at line 42 of file res_pjsip_dtmf_info.c.
References ast_sip_session::inv_session, and NULL.
Referenced by dtmf_info_incoming_request().
 {
    pjsip_tx_data *tdata;
    pjsip_dialog *dlg = session->inv_session->dlg;
    if (pjsip_dlg_create_response(dlg, rdata, code,
                   NULL, &tdata) == PJ_SUCCESS) {
       struct pjsip_transaction *tsx = pjsip_rdata_get_tsx(rdata);
       pjsip_dlg_send_response(dlg, tsx, tdata);
    }
 }
unload_module()
static int unload_module (void) static
Definition at line 170 of file res_pjsip_dtmf_info.c.
References AST_MODFLAG_LOAD_ORDER, AST_MODPRI_APP_DEPEND, AST_MODULE_INFO(), AST_MODULE_SUPPORT_CORE, ast_sip_session_unregister_supplement(), ASTERISK_GPL_KEY, and load_module().
 {
    ast_sip_session_unregister_supplement(&dtmf_info_supplement);
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "PJSIP DTMF INFO Support" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_APP_DEPEND, .requires = "res_pjsip,res_pjsip_session", } static
Definition at line 182 of file res_pjsip_dtmf_info.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 182 of file res_pjsip_dtmf_info.c.
dtmf_info_supplement
struct ast_sip_session_supplement dtmf_info_supplement static
Initial value:
= {
   .method = "INFO",
   .priority = AST_SIP_SUPPLEMENT_PRIORITY_FIRST,
   .incoming_request = dtmf_info_incoming_request,
}
Definition at line 158 of file res_pjsip_dtmf_info.c.