Asterisk - The Open Source Telephony Project: app_system.c File Reference
app_system.c File Reference
Dial plan applications
Execute arbitrary system commands.
#include "asterisk.h"
#include "asterisk/pbx.h"
#include "asterisk/module.h"
#include "asterisk/app.h"
#include "asterisk/channel.h"
#include "asterisk/strings.h"
#include "asterisk/threadstorage.h"
Functions
static void __init_buf_buf (void)
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int load_module (void)
static int system_exec (struct ast_channel *chan, const char *data)
static int system_exec_helper (struct ast_channel *chan, const char *data, int failmode)
static int trysystem_exec (struct ast_channel *chan, const char *data)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Generic System() application" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, }
static char * app = "System"
static char * app2 = "TrySystem"
static const struct ast_module_info * ast_module_info = &__mod_info
static struct ast_threadstorage buf_buf = { .once = PTHREAD_ONCE_INIT , .key_init = __init_buf_buf , .custom_init = NULL , }
static char * chanvar = "SYSTEMSTATUS"
Detailed Description
Execute arbitrary system commands.
Author
Mark Spencer marks.nosp@m.ter@.nosp@m.digiu.nosp@m.m.co.nosp@m.m
Definition in file app_system.c.
Function Documentation
__init_buf_buf()
static void __init_buf_buf (void) static
Definition at line 107 of file app_system.c.
 {
__reg_module()
static void __reg_module (void) static
Definition at line 194 of file app_system.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 194 of file app_system.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 194 of file app_system.c.
load_module()
static int load_module (void) static
Definition at line 184 of file app_system.c.
References app, app2, ast_register_application_xml, system_exec(), and trysystem_exec().
 {
    int res;
    res = ast_register_application_xml(app2, trysystem_exec);
    res |= ast_register_application_xml(app, system_exec);
    return res;
 }
system_exec()
static int system_exec (struct ast_channel * chan, const char * data) static
Definition at line 164 of file app_system.c.
References system_exec_helper().
Referenced by load_module().
 {
    return system_exec_helper(chan, data, -1);
 }
system_exec_helper()
static int system_exec_helper (struct ast_channel * chan, const char * data, int failmode) static
Definition at line 115 of file app_system.c.
References ast_autoservice_start(), ast_autoservice_stop(), ast_log, ast_safe_system(), ast_str_buffer(), ast_str_get_encoded_str(), ast_str_strlen(), ast_str_thread_get(), ast_strlen_zero, buf, buf_buf, errno, LOG_NOTICE, LOG_WARNING, and pbx_builtin_setvar_helper().
Referenced by system_exec(), and trysystem_exec().
 {
    int res = 0;
    struct ast_str *buf = ast_str_thread_get(&buf_buf, 16);
    char *cbuf;
    if (ast_strlen_zero(data)) {
       ast_log(LOG_WARNING, "System requires an argument(command)\n");
       pbx_builtin_setvar_helper(chan, chanvar, "FAILURE");
       return failmode;
    }
    ast_autoservice_start(chan);
    /* Do our thing here */
    ast_str_get_encoded_str(&buf, 0, (char *) data);
    cbuf = ast_str_buffer(buf);
    if (strchr("\"'", cbuf[0]) && cbuf[ast_str_strlen(buf) - 1] == cbuf[0]) {
       cbuf[ast_str_strlen(buf) - 1] = '\0';
       cbuf++;
       ast_log(LOG_NOTICE, "It is not necessary to quote the argument to the System application.\n");
    }
    res = ast_safe_system(cbuf);
    if ((res < 0) && (errno != ECHILD)) {
       ast_log(LOG_WARNING, "Unable to execute '%s'\n", (char *)data);
       pbx_builtin_setvar_helper(chan, chanvar, "FAILURE");
       res = failmode;
    } else if (res == 127) {
       ast_log(LOG_WARNING, "Unable to execute '%s'\n", (char *)data);
       pbx_builtin_setvar_helper(chan, chanvar, "FAILURE");
       res = failmode;
    } else {
       if (res < 0)
          res = 0;
       if (res != 0)
          pbx_builtin_setvar_helper(chan, chanvar, "APPERROR");
       else
          pbx_builtin_setvar_helper(chan, chanvar, "SUCCESS");
       res = 0;
    }
    ast_autoservice_stop(chan);
    return res;
 }
trysystem_exec()
static int trysystem_exec (struct ast_channel * chan, const char * data) static
Definition at line 169 of file app_system.c.
References system_exec_helper().
Referenced by load_module().
 {
    return system_exec_helper(chan, data, 0);
 }
unload_module()
static int unload_module (void) static
Definition at line 174 of file app_system.c.
References app, app2, and ast_unregister_application().
 {
    int res;
    res = ast_unregister_application(app);
    res |= ast_unregister_application(app2);
    return res;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Generic System() application" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, } static
Definition at line 194 of file app_system.c.
app
char* app = "System" static
Definition at line 109 of file app_system.c.
Referenced by load_module(), and unload_module().
app2
char* app2 = "TrySystem" static
Definition at line 111 of file app_system.c.
Referenced by load_module(), and unload_module().
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 194 of file app_system.c.
buf_buf
struct ast_threadstorage buf_buf = { .once = PTHREAD_ONCE_INIT , .key_init = __init_buf_buf , .custom_init = NULL , } static
Definition at line 107 of file app_system.c.
Referenced by system_exec_helper().
chanvar
char* chanvar = "SYSTEMSTATUS" static
Definition at line 113 of file app_system.c.
Referenced by load_config().