Asterisk - The Open Source Telephony Project: config_global.c File Reference
config_global.c File Reference
#include "asterisk.h"
#include <pjsip.h>
#include <pjlib.h>
#include "asterisk/res_pjsip.h"
#include "include/res_pjsip_private.h"
#include "asterisk/pbx.h"
#include "asterisk/sorcery.h"
#include "asterisk/taskprocessor.h"
#include "asterisk/ast_version.h"
#include "asterisk/res_pjsip_cli.h"
Data Structures
struct global_config
Macros
#define DEFAULT_CONTACT_EXPIRATION_CHECK_INTERVAL 30
#define DEFAULT_DEBUG "no"
#define DEFAULT_DISABLE_MULTI_DOMAIN 0
#define DEFAULT_ENDPOINT_IDENTIFIER_ORDER "ip,username,anonymous"
#define DEFAULT_FROM_USER "asterisk"
#define DEFAULT_IGNORE_URI_USER_OPTIONS 0
#define DEFAULT_KEEPALIVE_INTERVAL 90
#define DEFAULT_MAX_FORWARDS 70
#define DEFAULT_MAX_INITIAL_QUALIFY_TIME 0
#define DEFAULT_MWI_DISABLE_INITIAL_UNSOLICITED 0
#define DEFAULT_MWI_TPS_QUEUE_HIGH AST_TASKPROCESSOR_HIGH_WATER_LEVEL
#define DEFAULT_MWI_TPS_QUEUE_LOW -1
#define DEFAULT_NOREFERSUB 1
#define DEFAULT_OUTBOUND_ENDPOINT "default_outbound_endpoint"
#define DEFAULT_REALM "asterisk"
#define DEFAULT_REGCONTEXT ""
#define DEFAULT_SEND_CONTACT_STATUS_ON_UPDATE_REGISTRATION 0
#define DEFAULT_TASKPROCESSOR_OVERLOAD_TRIGGER TASKPROCESSOR_OVERLOAD_TRIGGER_GLOBAL
#define DEFAULT_UNIDENTIFIED_REQUEST_COUNT 5
#define DEFAULT_UNIDENTIFIED_REQUEST_PERIOD 5
#define DEFAULT_UNIDENTIFIED_REQUEST_PRUNE_INTERVAL 30
#define DEFAULT_USE_CALLERID_CONTACT 0
#define DEFAULT_USERAGENT_PREFIX "Asterisk PBX"
#define DEFAULT_VOICEMAIL_EXTENSION ""
Functions
static AO2_GLOBAL_OBJ_STATIC (global_cfg)
Cached global config object.
int ast_sip_destroy_sorcery_global (void)
unsigned int ast_sip_get_contact_expiration_check_interval (void)
Retrieve the system contact expiration check interval setting.
char * ast_sip_get_debug (void)
Retrieve the system debug setting (yes|no|host).
void ast_sip_get_default_from_user (char *from_user, size_t size)
Retrieve the global default from user.
void ast_sip_get_default_realm (char *realm, size_t size)
Retrieve the global default realm.
char * ast_sip_get_default_voicemail_extension (void)
Retrieve the default voicemail extension.
unsigned int ast_sip_get_disable_multi_domain (void)
Retrieve the system setting 'disable multi domain'.
char * ast_sip_get_endpoint_identifier_order (void)
Retrieve the global endpoint_identifier_order setting.
unsigned int ast_sip_get_ignore_uri_user_options (void)
Retrieve the global setting 'ignore_uri_user_options'.
unsigned int ast_sip_get_keep_alive_interval (void)
Retrieve the system keep alive interval setting.
unsigned int ast_sip_get_max_initial_qualify_time (void)
Retrieve the system max initial qualify time.
unsigned int ast_sip_get_mwi_disable_initial_unsolicited (void)
Retrieve the global setting 'disable sending unsolicited mwi on startup'.
unsigned int ast_sip_get_mwi_tps_queue_high (void)
Retrieve the global MWI taskprocessor high water alert trigger level.
int ast_sip_get_mwi_tps_queue_low (void)
Retrieve the global MWI taskprocessor low water clear alert level.
unsigned int ast_sip_get_norefersub (void)
Retrieve the global setting 'norefersub'.
char * ast_sip_get_regcontext (void)
Retrieve the global regcontext setting.
unsigned int ast_sip_get_send_contact_status_on_update_registration (void)
Retrieve the global setting 'send_contact_status_on_update_registration'.
enum ast_sip_taskprocessor_overload_trigger ast_sip_get_taskprocessor_overload_trigger (void)
void ast_sip_get_unidentified_request_thresholds (unsigned int *count, unsigned int *period, unsigned int *prune_interval)
Retrieve the unidentified request security event thresholds.
unsigned int ast_sip_get_use_callerid_contact (void)
Retrieve the global setting 'use_callerid_contact'.
char * ast_sip_global_default_outbound_endpoint (void)
int ast_sip_initialize_sorcery_global (void)
const char * ast_sip_overload_trigger_to_str (enum ast_sip_taskprocessor_overload_trigger trigger)
static int check_regcontext (const struct global_config *cfg)
static struct global_config * get_global_cfg (void)
static void * global_alloc (const char *name)
static int global_apply (const struct ast_sorcery *sorcery, void *obj)
static void global_destructor (void *obj)
static void global_loaded_observer (const char *name, const struct ast_sorcery *sorcery, const char *object_type, int reloaded)
static int overload_trigger_handler (const struct aco_option *opt, struct ast_variable *var, void *obj)
static int overload_trigger_to_str (const void *obj, const intptr_t *args, char **buf)
int sip_cli_print_global (struct ast_sip_cli_context *context)
Variables
static char default_useragent [256]
static const struct ast_sorcery_instance_observer observer_callbacks_global
static const char * overload_trigger_map []
static char * previous_regcontext = NULL
Macro Definition Documentation
DEFAULT_CONTACT_EXPIRATION_CHECK_INTERVAL
#define DEFAULT_CONTACT_EXPIRATION_CHECK_INTERVAL 30
Definition at line 42 of file config_global.c.
Referenced by ast_sip_get_contact_expiration_check_interval(), and ast_sip_initialize_sorcery_global().
DEFAULT_DEBUG
#define DEFAULT_DEBUG "no"
Definition at line 36 of file config_global.c.
Referenced by ast_sip_get_debug(), and ast_sip_initialize_sorcery_global().
DEFAULT_DISABLE_MULTI_DOMAIN
#define DEFAULT_DISABLE_MULTI_DOMAIN 0
Definition at line 43 of file config_global.c.
Referenced by ast_sip_get_disable_multi_domain(), and ast_sip_initialize_sorcery_global().
DEFAULT_ENDPOINT_IDENTIFIER_ORDER
#define DEFAULT_ENDPOINT_IDENTIFIER_ORDER "ip,username,anonymous"
Definition at line 37 of file config_global.c.
Referenced by ast_sip_get_endpoint_identifier_order(), and ast_sip_initialize_sorcery_global().
DEFAULT_FROM_USER
#define DEFAULT_FROM_USER "asterisk"
Definition at line 39 of file config_global.c.
Referenced by ast_sip_get_default_from_user(), and ast_sip_initialize_sorcery_global().
DEFAULT_IGNORE_URI_USER_OPTIONS
#define DEFAULT_IGNORE_URI_USER_OPTIONS 0
Definition at line 51 of file config_global.c.
Referenced by ast_sip_get_ignore_uri_user_options(), and ast_sip_initialize_sorcery_global().
DEFAULT_KEEPALIVE_INTERVAL
#define DEFAULT_KEEPALIVE_INTERVAL 90
Definition at line 33 of file config_global.c.
Referenced by ast_sip_get_keep_alive_interval(), and ast_sip_initialize_sorcery_global().
DEFAULT_MAX_FORWARDS
#define DEFAULT_MAX_FORWARDS 70
Definition at line 32 of file config_global.c.
Referenced by ast_sip_initialize_sorcery_global().
DEFAULT_MAX_INITIAL_QUALIFY_TIME
#define DEFAULT_MAX_INITIAL_QUALIFY_TIME 0
Definition at line 38 of file config_global.c.
Referenced by ast_sip_get_max_initial_qualify_time(), and ast_sip_initialize_sorcery_global().
DEFAULT_MWI_DISABLE_INITIAL_UNSOLICITED
#define DEFAULT_MWI_DISABLE_INITIAL_UNSOLICITED 0
Definition at line 50 of file config_global.c.
Referenced by ast_sip_get_mwi_disable_initial_unsolicited(), and ast_sip_initialize_sorcery_global().
DEFAULT_MWI_TPS_QUEUE_HIGH
#define DEFAULT_MWI_TPS_QUEUE_HIGH AST_TASKPROCESSOR_HIGH_WATER_LEVEL
Definition at line 48 of file config_global.c.
Referenced by ast_sip_get_mwi_tps_queue_high(), and ast_sip_initialize_sorcery_global().
DEFAULT_MWI_TPS_QUEUE_LOW
#define DEFAULT_MWI_TPS_QUEUE_LOW -1
Definition at line 49 of file config_global.c.
Referenced by ast_sip_get_mwi_tps_queue_low(), and ast_sip_initialize_sorcery_global().
DEFAULT_NOREFERSUB
#define DEFAULT_NOREFERSUB 1
Definition at line 55 of file config_global.c.
Referenced by ast_sip_get_norefersub(), and ast_sip_initialize_sorcery_global().
DEFAULT_OUTBOUND_ENDPOINT
#define DEFAULT_OUTBOUND_ENDPOINT "default_outbound_endpoint"
Definition at line 35 of file config_global.c.
Referenced by ast_sip_global_default_outbound_endpoint(), and ast_sip_initialize_sorcery_global().
DEFAULT_REALM
#define DEFAULT_REALM "asterisk"
Definition at line 40 of file config_global.c.
Referenced by ast_sip_get_default_realm(), and ast_sip_initialize_sorcery_global().
DEFAULT_REGCONTEXT
#define DEFAULT_REGCONTEXT ""
Definition at line 41 of file config_global.c.
Referenced by ast_sip_get_regcontext(), and ast_sip_initialize_sorcery_global().
DEFAULT_SEND_CONTACT_STATUS_ON_UPDATE_REGISTRATION
#define DEFAULT_SEND_CONTACT_STATUS_ON_UPDATE_REGISTRATION 0
Definition at line 53 of file config_global.c.
Referenced by ast_sip_get_send_contact_status_on_update_registration(), and ast_sip_initialize_sorcery_global().
DEFAULT_TASKPROCESSOR_OVERLOAD_TRIGGER
#define DEFAULT_TASKPROCESSOR_OVERLOAD_TRIGGER TASKPROCESSOR_OVERLOAD_TRIGGER_GLOBAL
Definition at line 54 of file config_global.c.
Referenced by ast_sip_get_taskprocessor_overload_trigger(), and ast_sip_initialize_sorcery_global().
DEFAULT_UNIDENTIFIED_REQUEST_COUNT
#define DEFAULT_UNIDENTIFIED_REQUEST_COUNT 5
Definition at line 45 of file config_global.c.
Referenced by ast_sip_get_unidentified_request_thresholds(), and ast_sip_initialize_sorcery_global().
DEFAULT_UNIDENTIFIED_REQUEST_PERIOD
#define DEFAULT_UNIDENTIFIED_REQUEST_PERIOD 5
Definition at line 46 of file config_global.c.
Referenced by ast_sip_get_unidentified_request_thresholds(), and ast_sip_initialize_sorcery_global().
DEFAULT_UNIDENTIFIED_REQUEST_PRUNE_INTERVAL
#define DEFAULT_UNIDENTIFIED_REQUEST_PRUNE_INTERVAL 30
Definition at line 47 of file config_global.c.
Referenced by ast_sip_get_unidentified_request_thresholds(), and ast_sip_initialize_sorcery_global().
DEFAULT_USE_CALLERID_CONTACT
#define DEFAULT_USE_CALLERID_CONTACT 0
Definition at line 52 of file config_global.c.
Referenced by ast_sip_get_use_callerid_contact(), and ast_sip_initialize_sorcery_global().
DEFAULT_USERAGENT_PREFIX
#define DEFAULT_USERAGENT_PREFIX "Asterisk PBX"
Definition at line 34 of file config_global.c.
Referenced by ast_sip_initialize_sorcery_global().
DEFAULT_VOICEMAIL_EXTENSION
#define DEFAULT_VOICEMAIL_EXTENSION ""
Definition at line 44 of file config_global.c.
Referenced by ast_sip_get_default_voicemail_extension(), and ast_sip_initialize_sorcery_global().
Function Documentation
AO2_GLOBAL_OBJ_STATIC()
static AO2_GLOBAL_OBJ_STATIC (global_cfg) static
Cached global config object.
Cached so we don't have to keep asking sorcery for the config. We could ask for it hundreds of times a second if not more.
ast_sip_destroy_sorcery_global()
int ast_sip_destroy_sorcery_global (void)
Definition at line 630 of file config_global.c.
References ao2_t_global_obj_release, ast_context_destroy_by_name(), ast_free, ast_sip_get_sorcery(), ast_sorcery_instance_observer_remove(), previous_regcontext, and sorcery.
Referenced by ast_res_pjsip_destroy_configuration().
 {
    struct ast_sorcery *sorcery = ast_sip_get_sorcery();
    ast_sorcery_instance_observer_remove(sorcery, &observer_callbacks_global);
    if (previous_regcontext) {
       ast_context_destroy_by_name(previous_regcontext, "PJSIP");
       ast_free(previous_regcontext);
    }
    ao2_t_global_obj_release(global_cfg, "Module is unloading");
    return 0;
 }
ast_sip_get_contact_expiration_check_interval()
unsigned int ast_sip_get_contact_expiration_check_interval (void)
Retrieve the system contact expiration check interval setting.
Return values
the contact expiration check interval.
Definition at line 309 of file config_global.c.
References ao2_ref, global_config::contact_expiration_check_interval, DEFAULT_CONTACT_EXPIRATION_CHECK_INTERVAL, and get_global_cfg().
Referenced by expiration_global_loaded().
 {
    unsigned int interval;
    struct global_config *cfg;
    cfg = get_global_cfg();
    if (!cfg) {
       return DEFAULT_CONTACT_EXPIRATION_CHECK_INTERVAL;
    }
    interval = cfg->contact_expiration_check_interval;
    ao2_ref(cfg, -1);
    return interval;
 }
ast_sip_get_debug()
char* ast_sip_get_debug (void)
Retrieve the system debug setting (yes|no|host).
Note
returned string needs to be de-allocated by caller.
Return values
the system debug setting.
Definition at line 232 of file config_global.c.
References ao2_ref, ast_strdup, global_config::debug, DEFAULT_DEBUG, and get_global_cfg().
Referenced by check_debug().
 {
    char *res;
    struct global_config *cfg;
    cfg = get_global_cfg();
    if (!cfg) {
       return ast_strdup(DEFAULT_DEBUG);
    }
    res = ast_strdup(cfg->debug);
    ao2_ref(cfg, -1);
    return res;
 }
ast_sip_get_default_from_user()
void ast_sip_get_default_from_user (char * from_user, size_t size)
Retrieve the global default from user.
This is the value placed in outbound requests' From header if there is no better option (such as an endpoint-configured from_user or caller ID number).
Parameters
[out] from_user The default from user
size The buffer size of from_user
Returns
nothing
Definition at line 388 of file config_global.c.
References ao2_ref, ast_copy_string(), DEFAULT_FROM_USER, global_config::default_from_user, and get_global_cfg().
Referenced by sip_dialog_create_from().
 {
    struct global_config *cfg;
    cfg = get_global_cfg();
    if (!cfg) {
       ast_copy_string(from_user, DEFAULT_FROM_USER, size);
    } else {
       ast_copy_string(from_user, cfg->default_from_user, size);
       ao2_ref(cfg, -1);
    }
 }
ast_sip_get_default_realm()
void ast_sip_get_default_realm (char * realm, size_t size)
Retrieve the global default realm.
This is the value placed in outbound challenges' realm if there is no better option (such as an auth-configured realm).
Parameters
[out] realm The default realm
size The buffer size of realm
Returns
nothing
Definition at line 375 of file config_global.c.
References ao2_ref, ast_copy_string(), DEFAULT_REALM, global_config::default_realm, and get_global_cfg().
Referenced by create_artificial_auth(), and global_loaded().
 {
    struct global_config *cfg;
    cfg = get_global_cfg();
    if (!cfg) {
       ast_copy_string(realm, DEFAULT_REALM, size);
    } else {
       ast_copy_string(realm, cfg->default_realm, size);
       ao2_ref(cfg, -1);
    }
 }
ast_sip_get_default_voicemail_extension()
char* ast_sip_get_default_voicemail_extension (void)
Retrieve the default voicemail extension.
Since
13.9.0
Note
returned string needs to be de-allocated by caller.
Return values
the default voicemail extension
Definition at line 263 of file config_global.c.
References ao2_ref, ast_strdup, DEFAULT_VOICEMAIL_EXTENSION, global_config::default_voicemail_extension, and get_global_cfg().
Referenced by global_loaded().
 {
    char *res;
    struct global_config *cfg;
    cfg = get_global_cfg();
    if (!cfg) {
       return ast_strdup(DEFAULT_VOICEMAIL_EXTENSION);
    }
    res = ast_strdup(cfg->default_voicemail_extension);
    ao2_ref(cfg, -1);
    return res;
 }
ast_sip_get_disable_multi_domain()
unsigned int ast_sip_get_disable_multi_domain (void)
Retrieve the system setting 'disable multi domain'.
Since
13.9.0
Return values
non zero if disable multi domain.
Definition at line 324 of file config_global.c.
References ao2_ref, DEFAULT_DISABLE_MULTI_DOMAIN, global_config::disable_multi_domain, and get_global_cfg().
Referenced by anonymous_identify(), find_endpoint(), request(), and sip_dialog_create_from().
 {
    unsigned int disable_multi_domain;
    struct global_config *cfg;
    cfg = get_global_cfg();
    if (!cfg) {
       return DEFAULT_DISABLE_MULTI_DOMAIN;
    }
    disable_multi_domain = cfg->disable_multi_domain;
    ao2_ref(cfg, -1);
    return disable_multi_domain;
 }
ast_sip_get_endpoint_identifier_order()
char* ast_sip_get_endpoint_identifier_order (void)
Retrieve the global endpoint_identifier_order setting.
Specifies the order by which endpoint identifiers should be regarded.
Return values
the global endpoint_identifier_order value
Definition at line 279 of file config_global.c.
References ao2_ref, ast_strdup, DEFAULT_ENDPOINT_IDENTIFIER_ORDER, global_config::endpoint_identifier_order, and get_global_cfg().
Referenced by ast_sip_register_endpoint_identifier_with_name(), and global_loaded().
 {
    char *res;
    struct global_config *cfg;
    cfg = get_global_cfg();
    if (!cfg) {
       return ast_strdup(DEFAULT_ENDPOINT_IDENTIFIER_ORDER);
    }
    res = ast_strdup(cfg->endpoint_identifier_order);
    ao2_ref(cfg, -1);
    return res;
 }
ast_sip_get_ignore_uri_user_options()
unsigned int ast_sip_get_ignore_uri_user_options (void)
Retrieve the global setting 'ignore_uri_user_options'.
Since
13.12.0
Return values
non zero if ignore the user field options.
Definition at line 447 of file config_global.c.
References ao2_ref, DEFAULT_IGNORE_URI_USER_OPTIONS, get_global_cfg(), and global_config::ignore_uri_user_options.
Referenced by find_registrar_aor().
 {
    unsigned int ignore_uri_user_options;
    struct global_config *cfg;
    cfg = get_global_cfg();
    if (!cfg) {
       return DEFAULT_IGNORE_URI_USER_OPTIONS;
    }
    ignore_uri_user_options = cfg->ignore_uri_user_options;
    ao2_ref(cfg, -1);
    return ignore_uri_user_options;
 }
ast_sip_get_keep_alive_interval()
unsigned int ast_sip_get_keep_alive_interval (void)
Retrieve the system keep alive interval setting.
Return values
the keep alive interval.
Definition at line 294 of file config_global.c.
References ao2_ref, DEFAULT_KEEPALIVE_INTERVAL, get_global_cfg(), and global_config::keep_alive_interval.
Referenced by keepalive_global_loaded().
 {
    unsigned int interval;
    struct global_config *cfg;
    cfg = get_global_cfg();
    if (!cfg) {
       return DEFAULT_KEEPALIVE_INTERVAL;
    }
    interval = cfg->keep_alive_interval;
    ao2_ref(cfg, -1);
    return interval;
 }
ast_sip_get_max_initial_qualify_time()
unsigned int ast_sip_get_max_initial_qualify_time (void)
Retrieve the system max initial qualify time.
Return values
the maximum initial qualify time.
Definition at line 339 of file config_global.c.
References ao2_ref, DEFAULT_MAX_INITIAL_QUALIFY_TIME, get_global_cfg(), and global_config::max_initial_qualify_time.
Referenced by sip_options_determine_initial_qualify_time().
 {
    unsigned int time;
    struct global_config *cfg;
    cfg = get_global_cfg();
    if (!cfg) {
       return DEFAULT_MAX_INITIAL_QUALIFY_TIME;
    }
    time = cfg->max_initial_qualify_time;
    ao2_ref(cfg, -1);
    return time;
 }
ast_sip_get_mwi_disable_initial_unsolicited()
unsigned int ast_sip_get_mwi_disable_initial_unsolicited (void)
Retrieve the global setting 'disable sending unsolicited mwi on startup'.
Since
13.12.0
Return values
non zero if disable.
Definition at line 432 of file config_global.c.
References ao2_ref, DEFAULT_MWI_DISABLE_INITIAL_UNSOLICITED, global_config::disable_initial_unsolicited, get_global_cfg(), and global_config::mwi.
Referenced by load_module(), and reload().
 {
    unsigned int disable_initial_unsolicited;
    struct global_config *cfg;
    cfg = get_global_cfg();
    if (!cfg) {
       return DEFAULT_MWI_DISABLE_INITIAL_UNSOLICITED;
    }
    disable_initial_unsolicited = cfg->mwi.disable_initial_unsolicited;
    ao2_ref(cfg, -1);
    return disable_initial_unsolicited;
 }
ast_sip_get_mwi_tps_queue_high()
unsigned int ast_sip_get_mwi_tps_queue_high (void)
Retrieve the global MWI taskprocessor high water alert trigger level.
Since
13.12.0
Return values
the system MWI taskprocessor high water alert trigger level
Definition at line 402 of file config_global.c.
References ao2_ref, DEFAULT_MWI_TPS_QUEUE_HIGH, get_global_cfg(), global_config::mwi, and global_config::tps_queue_high.
Referenced by global_loaded().
 {
    unsigned int tps_queue_high;
    struct global_config *cfg;
    cfg = get_global_cfg();
    if (!cfg) {
       return DEFAULT_MWI_TPS_QUEUE_HIGH;
    }
    tps_queue_high = cfg->mwi.tps_queue_high;
    ao2_ref(cfg, -1);
    return tps_queue_high;
 }
ast_sip_get_mwi_tps_queue_low()
int ast_sip_get_mwi_tps_queue_low (void)
Retrieve the global MWI taskprocessor low water clear alert level.
Since
13.12.0
Return values
the system MWI taskprocessor low water clear alert level
Definition at line 417 of file config_global.c.
References ao2_ref, DEFAULT_MWI_TPS_QUEUE_LOW, get_global_cfg(), global_config::mwi, and global_config::tps_queue_low.
Referenced by global_loaded().
 {
    int tps_queue_low;
    struct global_config *cfg;
    cfg = get_global_cfg();
    if (!cfg) {
       return DEFAULT_MWI_TPS_QUEUE_LOW;
    }
    tps_queue_low = cfg->mwi.tps_queue_low;
    ao2_ref(cfg, -1);
    return tps_queue_low;
 }
ast_sip_get_norefersub()
unsigned int ast_sip_get_norefersub (void)
Retrieve the global setting 'norefersub'.
Return values
non zero if norefersub is to be sent in "Supported" Headers
Definition at line 507 of file config_global.c.
References ao2_ref, DEFAULT_NOREFERSUB, get_global_cfg(), and global_config::norefersub.
Referenced by load_module().
 {
    unsigned int norefersub;
    struct global_config *cfg;
    cfg = get_global_cfg();
    if (!cfg) {
       return DEFAULT_NOREFERSUB;
    }
    norefersub = cfg->norefersub;
    ao2_ref(cfg, -1);
    return norefersub;
 }
ast_sip_get_regcontext()
char* ast_sip_get_regcontext (void)
Retrieve the global regcontext setting.
Since
13.8.0
Note
returned string needs to be de-allocated by caller.
Return values
the global regcontext setting
Definition at line 247 of file config_global.c.
References ao2_ref, ast_strdup, DEFAULT_REGCONTEXT, get_global_cfg(), and global_config::regcontext.
Referenced by ast_sip_persistent_endpoint_update_state().
 {
    char *res;
    struct global_config *cfg;
    cfg = get_global_cfg();
    if (!cfg) {
       return ast_strdup(DEFAULT_REGCONTEXT);
    }
    res = ast_strdup(cfg->regcontext);
    ao2_ref(cfg, -1);
    return res;
 }
ast_sip_get_send_contact_status_on_update_registration()
unsigned int ast_sip_get_send_contact_status_on_update_registration (void)
Retrieve the global setting 'send_contact_status_on_update_registration'.
Since
16.2.0
Return values
non zero if need to send AMI ContactStatus event when a contact is updated.
Definition at line 477 of file config_global.c.
References ao2_ref, DEFAULT_SEND_CONTACT_STATUS_ON_UPDATE_REGISTRATION, get_global_cfg(), and global_config::send_contact_status_on_update_registration.
Referenced by contact_observer_updated().
 {
    unsigned int send_contact_status_on_update_registration;
    struct global_config *cfg;
    cfg = get_global_cfg();
    if (!cfg) {
       return DEFAULT_SEND_CONTACT_STATUS_ON_UPDATE_REGISTRATION;
    }
    send_contact_status_on_update_registration = cfg->send_contact_status_on_update_registration;
    ao2_ref(cfg, -1);
    return send_contact_status_on_update_registration;
 }
ast_sip_get_taskprocessor_overload_trigger()
enum ast_sip_taskprocessor_overload_trigger ast_sip_get_taskprocessor_overload_trigger (void)
Definition at line 492 of file config_global.c.
References ao2_ref, DEFAULT_TASKPROCESSOR_OVERLOAD_TRIGGER, get_global_cfg(), and global_config::overload_trigger.
Referenced by global_loaded().
 {
    enum ast_sip_taskprocessor_overload_trigger trigger;
    struct global_config *cfg;
    cfg = get_global_cfg();
    if (!cfg) {
       return DEFAULT_TASKPROCESSOR_OVERLOAD_TRIGGER;
    }
    trigger = cfg->overload_trigger;
    ao2_ref(cfg, -1);
    return trigger;
 }
ast_sip_get_unidentified_request_thresholds()
void ast_sip_get_unidentified_request_thresholds (unsigned int * count, unsigned int * period, unsigned int * prune_interval)
Retrieve the unidentified request security event thresholds.
Since
13.8.0
Parameters
count The maximum number of unidentified requests per source ip to accumulate before emitting a security event
period The period in seconds over which to accumulate unidentified requests
prune_interval The interval in seconds at which expired entries will be pruned
Definition at line 354 of file config_global.c.
References ao2_ref, DEFAULT_UNIDENTIFIED_REQUEST_COUNT, DEFAULT_UNIDENTIFIED_REQUEST_PERIOD, DEFAULT_UNIDENTIFIED_REQUEST_PRUNE_INTERVAL, get_global_cfg(), global_config::unidentified_request_count, global_config::unidentified_request_period, and global_config::unidentified_request_prune_interval.
Referenced by global_loaded(), and prune_task().
 {
    struct global_config *cfg;
    cfg = get_global_cfg();
    if (!cfg) {
       *count = DEFAULT_UNIDENTIFIED_REQUEST_COUNT;
       *period = DEFAULT_UNIDENTIFIED_REQUEST_PERIOD;
       *prune_interval = DEFAULT_UNIDENTIFIED_REQUEST_PRUNE_INTERVAL;
       return;
    }
    *count = cfg->unidentified_request_count;
    *period = cfg->unidentified_request_period;
    *prune_interval = cfg->unidentified_request_prune_interval;
    ao2_ref(cfg, -1);
    return;
 }
ast_sip_get_use_callerid_contact()
unsigned int ast_sip_get_use_callerid_contact (void)
Retrieve the global setting 'use_callerid_contact'.
Since
13.24.0
Return values
non zero if CALLERID(num) is to be used as the default username in the contact
Definition at line 462 of file config_global.c.
References ao2_ref, DEFAULT_USE_CALLERID_CONTACT, get_global_cfg(), and global_config::use_callerid_contact.
Referenced by set_from_header().
 {
    unsigned int use_callerid_contact;
    struct global_config *cfg;
    cfg = get_global_cfg();
    if (!cfg) {
       return DEFAULT_USE_CALLERID_CONTACT;
    }
    use_callerid_contact = cfg->use_callerid_contact;
    ao2_ref(cfg, -1);
    return use_callerid_contact;
 }
ast_sip_global_default_outbound_endpoint()
char* ast_sip_global_default_outbound_endpoint (void)
Definition at line 217 of file config_global.c.
References ao2_ref, ast_strdup, DEFAULT_OUTBOUND_ENDPOINT, global_config::default_outbound_endpoint, get_global_cfg(), and str.
Referenced by ast_sip_default_outbound_endpoint().
 {
    char *str;
    struct global_config *cfg;
    cfg = get_global_cfg();
    if (!cfg) {
       return ast_strdup(DEFAULT_OUTBOUND_ENDPOINT);
    }
    str = ast_strdup(cfg->default_outbound_endpoint);
    ao2_ref(cfg, -1);
    return str;
 }
ast_sip_initialize_sorcery_global()
int ast_sip_initialize_sorcery_global (void)
Definition at line 647 of file config_global.c.
References __stringify, ast_get_version(), ast_sip_get_sorcery(), ast_sorcery_apply_default, ast_sorcery_instance_observer_add(), ast_sorcery_object_field_register, ast_sorcery_object_field_register_custom, ast_sorcery_object_register, global_config::contact_expiration_check_interval, global_config::debug, DEFAULT_CONTACT_EXPIRATION_CHECK_INTERVAL, DEFAULT_DEBUG, DEFAULT_DISABLE_MULTI_DOMAIN, DEFAULT_ENDPOINT_IDENTIFIER_ORDER, DEFAULT_FROM_USER, global_config::default_from_user, DEFAULT_IGNORE_URI_USER_OPTIONS, DEFAULT_KEEPALIVE_INTERVAL, DEFAULT_MAX_FORWARDS, DEFAULT_MAX_INITIAL_QUALIFY_TIME, DEFAULT_MWI_DISABLE_INITIAL_UNSOLICITED, DEFAULT_MWI_TPS_QUEUE_HIGH, DEFAULT_MWI_TPS_QUEUE_LOW, DEFAULT_NOREFERSUB, DEFAULT_OUTBOUND_ENDPOINT, global_config::default_outbound_endpoint, DEFAULT_REALM, global_config::default_realm, DEFAULT_REGCONTEXT, DEFAULT_SEND_CONTACT_STATUS_ON_UPDATE_REGISTRATION, DEFAULT_TASKPROCESSOR_OVERLOAD_TRIGGER, DEFAULT_UNIDENTIFIED_REQUEST_COUNT, DEFAULT_UNIDENTIFIED_REQUEST_PERIOD, DEFAULT_UNIDENTIFIED_REQUEST_PRUNE_INTERVAL, DEFAULT_USE_CALLERID_CONTACT, default_useragent, DEFAULT_USERAGENT_PREFIX, DEFAULT_VOICEMAIL_EXTENSION, global_config::default_voicemail_extension, global_config::disable_multi_domain, global_config::endpoint_identifier_order, FLDSET, global_alloc(), global_apply(), global_config::ignore_uri_user_options, global_config::keep_alive_interval, global_config::max_initial_qualify_time, global_config::mwi, global_config::norefersub, NULL, OPT_BOOL_T, OPT_INT_T, OPT_NOOP_T, OPT_STRINGFIELD_T, OPT_UINT_T, OPT_YESNO_T, overload_trigger_handler(), overload_trigger_map, overload_trigger_to_str(), global_config::regcontext, global_config::send_contact_status_on_update_registration, sorcery, STRFLDSET, global_config::unidentified_request_count, global_config::unidentified_request_period, global_config::unidentified_request_prune_interval, global_config::use_callerid_contact, and global_config::useragent.
Referenced by ast_res_pjsip_initialize_configuration().
 {
    struct ast_sorcery *sorcery = ast_sip_get_sorcery();
    snprintf(default_useragent, sizeof(default_useragent), "%s %s",
       DEFAULT_USERAGENT_PREFIX, ast_get_version());
    ast_sorcery_apply_default(sorcery, "global", "config", "pjsip.conf,criteria=type=global,single_object=yes,explicit_name=global");
    if (ast_sorcery_object_register(sorcery, "global", global_alloc, NULL, global_apply)) {
       return -1;
    }
    ast_sorcery_object_field_register(sorcery, "global", "type", "", OPT_NOOP_T, 0, 0);
    ast_sorcery_object_field_register(sorcery, "global", "max_forwards",
       __stringify(DEFAULT_MAX_FORWARDS),
       OPT_UINT_T, 0, FLDSET(struct global_config, max_forwards));
    ast_sorcery_object_field_register(sorcery, "global", "user_agent", default_useragent,
       OPT_STRINGFIELD_T, 0, STRFLDSET(struct global_config, useragent));
    ast_sorcery_object_field_register(sorcery, "global", "default_outbound_endpoint",
       DEFAULT_OUTBOUND_ENDPOINT,
       OPT_STRINGFIELD_T, 0, STRFLDSET(struct global_config, default_outbound_endpoint));
    ast_sorcery_object_field_register(sorcery, "global", "debug", DEFAULT_DEBUG,
       OPT_STRINGFIELD_T, 0, STRFLDSET(struct global_config, debug));
    ast_sorcery_object_field_register(sorcery, "global", "endpoint_identifier_order",
       DEFAULT_ENDPOINT_IDENTIFIER_ORDER,
       OPT_STRINGFIELD_T, 0, STRFLDSET(struct global_config, endpoint_identifier_order));
    ast_sorcery_object_field_register(sorcery, "global", "keep_alive_interval",
       __stringify(DEFAULT_KEEPALIVE_INTERVAL),
       OPT_UINT_T, 0, FLDSET(struct global_config, keep_alive_interval));
    ast_sorcery_object_field_register(sorcery, "global", "max_initial_qualify_time",
       __stringify(DEFAULT_MAX_INITIAL_QUALIFY_TIME),
       OPT_UINT_T, 0, FLDSET(struct global_config, max_initial_qualify_time));
    ast_sorcery_object_field_register(sorcery, "global", "default_from_user", DEFAULT_FROM_USER,
       OPT_STRINGFIELD_T, 0, STRFLDSET(struct global_config, default_from_user));
    ast_sorcery_object_field_register(sorcery, "global", "default_voicemail_extension",
       DEFAULT_VOICEMAIL_EXTENSION, OPT_STRINGFIELD_T, 0, STRFLDSET(struct global_config,
       default_voicemail_extension));
    ast_sorcery_object_field_register(sorcery, "global", "regcontext", DEFAULT_REGCONTEXT,
       OPT_STRINGFIELD_T, 0, STRFLDSET(struct global_config, regcontext));
    ast_sorcery_object_field_register(sorcery, "global", "contact_expiration_check_interval",
       __stringify(DEFAULT_CONTACT_EXPIRATION_CHECK_INTERVAL),
       OPT_UINT_T, 0, FLDSET(struct global_config, contact_expiration_check_interval));
    ast_sorcery_object_field_register(sorcery, "global", "disable_multi_domain",
       DEFAULT_DISABLE_MULTI_DOMAIN ? "yes" : "no",
       OPT_BOOL_T, 1, FLDSET(struct global_config, disable_multi_domain));
    ast_sorcery_object_field_register(sorcery, "global", "unidentified_request_count",
       __stringify(DEFAULT_UNIDENTIFIED_REQUEST_COUNT),
       OPT_UINT_T, 0, FLDSET(struct global_config, unidentified_request_count));
    ast_sorcery_object_field_register(sorcery, "global", "unidentified_request_period",
       __stringify(DEFAULT_UNIDENTIFIED_REQUEST_PERIOD),
       OPT_UINT_T, 0, FLDSET(struct global_config, unidentified_request_period));
    ast_sorcery_object_field_register(sorcery, "global", "unidentified_request_prune_interval",
       __stringify(DEFAULT_UNIDENTIFIED_REQUEST_PRUNE_INTERVAL),
       OPT_UINT_T, 0, FLDSET(struct global_config, unidentified_request_prune_interval));
    ast_sorcery_object_field_register(sorcery, "global", "default_realm", DEFAULT_REALM,
       OPT_STRINGFIELD_T, 0, STRFLDSET(struct global_config, default_realm));
    ast_sorcery_object_field_register(sorcery, "global", "mwi_tps_queue_high",
       __stringify(DEFAULT_MWI_TPS_QUEUE_HIGH),
       OPT_UINT_T, 0, FLDSET(struct global_config, mwi.tps_queue_high));
    ast_sorcery_object_field_register(sorcery, "global", "mwi_tps_queue_low",
       __stringify(DEFAULT_MWI_TPS_QUEUE_LOW),
       OPT_INT_T, 0, FLDSET(struct global_config, mwi.tps_queue_low));
    ast_sorcery_object_field_register(sorcery, "global", "mwi_disable_initial_unsolicited",
       DEFAULT_MWI_DISABLE_INITIAL_UNSOLICITED ? "yes" : "no",
       OPT_BOOL_T, 1, FLDSET(struct global_config, mwi.disable_initial_unsolicited));
    ast_sorcery_object_field_register(sorcery, "global", "ignore_uri_user_options",
       DEFAULT_IGNORE_URI_USER_OPTIONS ? "yes" : "no",
       OPT_BOOL_T, 1, FLDSET(struct global_config, ignore_uri_user_options));
    ast_sorcery_object_field_register(sorcery, "global", "use_callerid_contact",
       DEFAULT_USE_CALLERID_CONTACT ? "yes" : "no",
       OPT_YESNO_T, 1, FLDSET(struct global_config, use_callerid_contact));
    ast_sorcery_object_field_register(sorcery, "global", "send_contact_status_on_update_registration",
       DEFAULT_SEND_CONTACT_STATUS_ON_UPDATE_REGISTRATION ? "yes" : "no",
       OPT_YESNO_T, 1, FLDSET(struct global_config, send_contact_status_on_update_registration));
    ast_sorcery_object_field_register_custom(sorcery, "global", "taskprocessor_overload_trigger",
       overload_trigger_map[DEFAULT_TASKPROCESSOR_OVERLOAD_TRIGGER],
       overload_trigger_handler, overload_trigger_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register(sorcery, "global", "norefersub",
       DEFAULT_NOREFERSUB ? "yes" : "no",
       OPT_YESNO_T, 1, FLDSET(struct global_config, norefersub));
    if (ast_sorcery_instance_observer_add(sorcery, &observer_callbacks_global)) {
       return -1;
    }
    return 0;
 }
ast_sip_overload_trigger_to_str()
const char* ast_sip_overload_trigger_to_str (enum ast_sip_taskprocessor_overload_trigger trigger)
Definition at line 546 of file config_global.c.
References ARRAY_IN_BOUNDS, and overload_trigger_map.
Referenced by overload_trigger_to_str().
 {
    return ARRAY_IN_BOUNDS(trigger, overload_trigger_map) ?
       overload_trigger_map[trigger] : "";
 }
check_regcontext()
static int check_regcontext (const struct global_config * cfg) static
Definition at line 147 of file config_global.c.
References ast_context_destroy_by_name(), ast_free, ast_sip_persistent_endpoint_add_to_regcontext(), ast_strdup, ast_strlen_zero, NULL, previous_regcontext, and global_config::regcontext.
Referenced by global_apply().
 {
    char *current = NULL;
    if (previous_regcontext && !strcmp(previous_regcontext, cfg->regcontext)) {
       /* Nothing changed so nothing to do */
       return 0;
    }
    if (!ast_strlen_zero(cfg->regcontext)) {
       current = ast_strdup(cfg->regcontext);
       if (!current) {
          return -1;
       }
       if (ast_sip_persistent_endpoint_add_to_regcontext(cfg->regcontext)) {
          ast_free(current);
          return -1;
       }
    }
    if (!ast_strlen_zero(previous_regcontext)) {
       ast_context_destroy_by_name(previous_regcontext, "PJSIP");
       ast_free(previous_regcontext);
       previous_regcontext = NULL;
    }
    if (current) {
       previous_regcontext = current;
    }
    return 0;
 }
get_global_cfg()
static struct global_config* get_global_cfg (void) static
Definition at line 212 of file config_global.c.
References ao2_global_obj_ref.
Referenced by ast_sip_get_contact_expiration_check_interval(), ast_sip_get_debug(), ast_sip_get_default_from_user(), ast_sip_get_default_realm(), ast_sip_get_default_voicemail_extension(), ast_sip_get_disable_multi_domain(), ast_sip_get_endpoint_identifier_order(), ast_sip_get_ignore_uri_user_options(), ast_sip_get_keep_alive_interval(), ast_sip_get_max_initial_qualify_time(), ast_sip_get_mwi_disable_initial_unsolicited(), ast_sip_get_mwi_tps_queue_high(), ast_sip_get_mwi_tps_queue_low(), ast_sip_get_norefersub(), ast_sip_get_regcontext(), ast_sip_get_send_contact_status_on_update_registration(), ast_sip_get_taskprocessor_overload_trigger(), ast_sip_get_unidentified_request_thresholds(), ast_sip_get_use_callerid_contact(), ast_sip_global_default_outbound_endpoint(), and sip_cli_print_global().
 {
    return ao2_global_obj_ref(global_cfg);
 }
global_alloc()
static void* global_alloc (const char * name) static
Definition at line 128 of file config_global.c.
References ao2_cleanup, ast_sorcery_generic_alloc(), ast_string_field_init, global_destructor(), and NULL.
Referenced by ast_sip_initialize_sorcery_global().
 {
    struct global_config *cfg;
    cfg = ast_sorcery_generic_alloc(sizeof(*cfg), global_destructor);
    if (!cfg || ast_string_field_init(cfg, 100)) {
       ao2_cleanup(cfg);
       return NULL;
    }
    return cfg;
 }
global_apply()
static int global_apply (const struct ast_sorcery * sorcery, void * obj) static
Definition at line 181 of file config_global.c.
References ao2_t_global_obj_replace_unref, ast_log, ast_sip_add_global_request_header(), ast_sip_add_global_response_header(), ast_strlen_zero, check_regcontext(), global_config::debug, global_config::default_from_user, LOG_ERROR, global_config::max_forwards, and global_config::useragent.
Referenced by ast_sip_initialize_sorcery_global(), and global_loaded_observer().
 {
    struct global_config *cfg = obj;
    char max_forwards[10];
    if (ast_strlen_zero(cfg->debug)) {
       ast_log(LOG_ERROR,
          "Global option 'debug' can't be empty.  Set it to a valid value or remove the entry to accept 'no' as the default\n");
       return -1;
    }
    if (ast_strlen_zero(cfg->default_from_user)) {
       ast_log(LOG_ERROR,
          "Global option 'default_from_user' can't be empty.  Set it to a valid value or remove the entry to accept 'asterisk' as the default\n");
       return -1;
    }
    snprintf(max_forwards, sizeof(max_forwards), "%u", cfg->max_forwards);
    ast_sip_add_global_request_header("Max-Forwards", max_forwards, 1);
    ast_sip_add_global_request_header("User-Agent", cfg->useragent, 1);
    ast_sip_add_global_response_header("Server", cfg->useragent, 1);
    if (check_regcontext(cfg)) {
       return -1;
    }
    ao2_t_global_obj_replace_unref(global_cfg, cfg, "Applying global settings");
    return 0;
 }
global_destructor()
static void global_destructor (void * obj) static
Definition at line 121 of file config_global.c.
References ast_string_field_free_memory.
Referenced by global_alloc().
 {
    struct global_config *cfg = obj;
    ast_string_field_free_memory(cfg);
 }
global_loaded_observer()
static void global_loaded_observer (const char * name, const struct ast_sorcery * sorcery, const char * object_type, int reloaded) static
Definition at line 570 of file config_global.c.
References ao2_container_count(), ao2_ref, ast_debug, ast_log, AST_RETRIEVE_FLAG_ALL, AST_RETRIEVE_FLAG_MULTIPLE, ast_sorcery_alloc(), ast_sorcery_retrieve_by_fields(), global_apply(), globals, LOG_ERROR, and NULL.
 {
    struct ao2_container *globals;
    struct global_config *cfg;
    if (strcmp(object_type, "global")) {
       /* Not interested */
       return;
    }
    globals = ast_sorcery_retrieve_by_fields(sorcery, "global",
       AST_RETRIEVE_FLAG_MULTIPLE | AST_RETRIEVE_FLAG_ALL, NULL);
    if (globals) {
       int count;
       count = ao2_container_count(globals);
       ao2_ref(globals, -1);
       if (1 < count) {
          ast_log(LOG_ERROR,
             "At most one pjsip.conf type=global object can be defined.  You have %d defined.\n",
             count);
          return;
       }
       if (count) {
          return;
       }
    }
    ast_debug(1, "No pjsip.conf type=global object exists so applying defaults.\n");
    cfg = ast_sorcery_alloc(sorcery, "global", NULL);
    if (!cfg) {
       return;
    }
    global_apply(sorcery, cfg);
    ao2_ref(cfg, -1);
 }
overload_trigger_handler()
static int overload_trigger_handler (const struct aco_option * opt, struct ast_variable * var, void * obj) static
Definition at line 522 of file config_global.c.
References ast_log, LOG_WARNING, ast_variable::name, global_config::overload_trigger, TASKPROCESSOR_OVERLOAD_TRIGGER_GLOBAL, TASKPROCESSOR_OVERLOAD_TRIGGER_NONE, TASKPROCESSOR_OVERLOAD_TRIGGER_PJSIP_ONLY, and ast_variable::value.
Referenced by ast_sip_initialize_sorcery_global().
 {
    struct global_config *cfg = obj;
    if (!strcasecmp(var->value, "none")) {
       cfg->overload_trigger = TASKPROCESSOR_OVERLOAD_TRIGGER_NONE;
    } else if (!strcasecmp(var->value, "global")) {
       cfg->overload_trigger = TASKPROCESSOR_OVERLOAD_TRIGGER_GLOBAL;
    } else if (!strcasecmp(var->value, "pjsip_only")) {
       cfg->overload_trigger = TASKPROCESSOR_OVERLOAD_TRIGGER_PJSIP_ONLY;
    } else {
       ast_log(LOG_WARNING, "Unknown overload trigger '%s' specified for %s\n",
             var->value, var->name);
       return -1;
    }
    return 0;
 }
overload_trigger_to_str()
static int overload_trigger_to_str (const void * obj, const intptr_t * args, char ** buf) static
Definition at line 552 of file config_global.c.
References ast_sip_overload_trigger_to_str(), ast_strdup, and global_config::overload_trigger.
Referenced by ast_sip_initialize_sorcery_global().
 {
    const struct global_config *cfg = obj;
    *buf = ast_strdup(ast_sip_overload_trigger_to_str(cfg->overload_trigger));
    return 0;
 }
sip_cli_print_global()
int sip_cli_print_global (struct ast_sip_cli_context * context)
Definition at line 612 of file config_global.c.
References ao2_ref, ast_sip_cli_print_sorcery_objectset(), ast_sip_get_sorcery(), ast_sorcery_alloc(), ast_str_append(), get_global_cfg(), NULL, and ast_sip_cli_context::output_buffer.
Referenced by cli_show_settings().
 {
    struct global_config *cfg = get_global_cfg();
    if (!cfg) {
       cfg = ast_sorcery_alloc(ast_sip_get_sorcery(), "global", NULL);
       if (!cfg) {
          return -1;
       }
    }
    ast_str_append(&context->output_buffer, 0, "\nGlobal Settings:\n\n");
    ast_sip_cli_print_sorcery_objectset(cfg, context, 0);
    ao2_ref(cfg, -1);
    return 0;
 }
Variable Documentation
default_useragent
char default_useragent[256] static
Definition at line 66 of file config_global.c.
Referenced by ast_sip_initialize_sorcery_global().
observer_callbacks_global
const struct ast_sorcery_instance_observer observer_callbacks_global static
Initial value:
= {
   .object_type_loaded = global_loaded_observer,
}
Definition at line 608 of file config_global.c.
overload_trigger_map
const char* overload_trigger_map[] static
Initial value:
= {
   [TASKPROCESSOR_OVERLOAD_TRIGGER_NONE] = "none",
   [TASKPROCESSOR_OVERLOAD_TRIGGER_GLOBAL] = "global",
   [TASKPROCESSOR_OVERLOAD_TRIGGER_PJSIP_ONLY] = "pjsip_only"
}
Definition at line 540 of file config_global.c.
Referenced by ast_sip_initialize_sorcery_global(), and ast_sip_overload_trigger_to_str().
previous_regcontext
char* previous_regcontext = NULL static
Definition at line 145 of file config_global.c.
Referenced by ast_sip_destroy_sorcery_global(), and check_regcontext().