Asterisk - The Open Source Telephony Project: config_parser.h File Reference
config_parser.h File Reference
sip.conf parser header file
#include "sip.h"
Functions
void sip_config_parser_register_tests (void)
register config parsing tests
void sip_config_parser_unregister_tests (void)
unregister config parsing tests
int sip_parse_host (char *line, int lineno, char **hostname, int *portnum, enum ast_transport *transport)
parses a config line for a host with a transport
void sip_parse_nat_option (const char *value, struct ast_flags *mask, struct ast_flags *flags)
Parse the comma-separated nat= option values.
int sip_parse_register_line (struct sip_registry *reg, int default_expiry, const char *value, int lineno)
Parse register=> line in sip.conf.
Detailed Description
sip.conf parser header file
Definition in file config_parser.h.
Function Documentation
sip_config_parser_register_tests()
void sip_config_parser_register_tests (void)
register config parsing tests
register config parsing tests
Definition at line 913 of file config_parser.c.
References AST_TEST_REGISTER.
Referenced by sip_register_tests().
 {
    AST_TEST_REGISTER(sip_parse_register_line_test);
    AST_TEST_REGISTER(sip_parse_host_line_test);
    AST_TEST_REGISTER(sip_parse_nat_test);
 }
sip_config_parser_unregister_tests()
void sip_config_parser_unregister_tests (void)
unregister config parsing tests
unregister config parsing tests
Definition at line 921 of file config_parser.c.
References AST_TEST_UNREGISTER.
Referenced by sip_unregister_tests().
 {
    AST_TEST_UNREGISTER(sip_parse_register_line_test);
    AST_TEST_UNREGISTER(sip_parse_host_line_test);
    AST_TEST_UNREGISTER(sip_parse_nat_test);
 }
sip_parse_host()
int sip_parse_host (char * line, int lineno, char ** hostname, int * portnum, enum ast_transport * transport)
parses a config line for a host with a transport
An example input would be: tls://www.google.com:8056
Return values
0 on success
-1 on failure
Definition at line 647 of file config_parser.c.
References ast_log, ast_sockaddr_split_hostport(), ast_strlen_zero, AST_TRANSPORT_TCP, AST_TRANSPORT_TLS, AST_TRANSPORT_UDP, hostname, LOG_NOTICE, LOG_WARNING, NULL, STANDARD_SIP_PORT, and STANDARD_TLS_PORT.
Referenced by AST_TEST_DEFINE(), and proxy_from_config().
 {
    char *port;
    if (ast_strlen_zero(line)) {
       *hostname = NULL;
       return -1;
    }
    if ((*hostname = strstr(line, "://"))) {
       *hostname += 3;
       if (!strncasecmp(line, "tcp", 3)) {
          *transport = AST_TRANSPORT_TCP;
       } else if (!strncasecmp(line, "tls", 3)) {
          *transport = AST_TRANSPORT_TLS;
       } else if (!strncasecmp(line, "udp", 3)) {
          *transport = AST_TRANSPORT_UDP;
       } else if (lineno) {
          ast_log(LOG_NOTICE, "'%.3s' is not a valid transport type on line %d of sip.conf. defaulting to udp.\n", line, lineno);
       } else {
          ast_log(LOG_NOTICE, "'%.3s' is not a valid transport type in sip config. defaulting to udp.\n", line);
       }
    } else {
       *hostname = line;
       *transport = AST_TRANSPORT_UDP;
    }
    if ((line = strrchr(*hostname, '@')))
       line++;
    else
       line = *hostname;
    if (ast_sockaddr_split_hostport(line, hostname, &port, 0) == 0) {
       if (lineno) {
          ast_log(LOG_WARNING, "Cannot parse host '%s' on line %d of sip.conf.\n",
             line, lineno);
       } else {
          ast_log(LOG_WARNING, "Cannot parse host '%s' in sip config.\n", line);
       }
       return -1;
    }
    if (port) {
       if (!sscanf(port, "%5d", portnum)) {
          if (lineno) {
             ast_log(LOG_NOTICE, "'%s' is not a valid port number on line %d of sip.conf. using default.\n", port, lineno);
          } else {
             ast_log(LOG_NOTICE, "'%s' is not a valid port number in sip config. using default.\n", port);
          }
          port = NULL;
       }
    }
    if (!port) {
       if (*transport & AST_TRANSPORT_TLS) {
          *portnum = STANDARD_TLS_PORT;
       } else {
          *portnum = STANDARD_SIP_PORT;
       }
    }
    return 0;
 }
sip_parse_nat_option()
void sip_parse_nat_option (const char * value, struct ast_flags * mask, struct ast_flags * flags)
Parse the comma-separated nat= option values.
Parameters
value The comma-separated value
mask An array of ast_flags that will be set by this function and used as a mask for copying the flags later
flags An array of ast_flags that will be set by this function
Note
The nat-related values in both mask and flags are assumed to empty. This function will treat the first "yes" or "no" value in a list of values as overiding all other values and will stop parsing. Auto values will override their non-auto counterparts.
Definition at line 794 of file config_parser.c.
References ast_clear_flag, ast_false(), ast_log, ast_set_flag, ast_strdupa, ast_test_flag, LOG_WARNING, parse(), SIP_NAT_FORCE_RPORT, SIP_PAGE2_SYMMETRICRTP, SIP_PAGE3_NAT_AUTO_COMEDIA, SIP_PAGE3_NAT_AUTO_RPORT, and strsep().
Referenced by AST_TEST_DEFINE(), and handle_common_options().
 {
    char *parse, *this;
    if (!(parse = ast_strdupa(value))) {
       return;
    }
    /* Since we need to completely override the general settings if we are being called
     * later for a peer, always set the flags for all options on the mask */
    ast_set_flag(&mask[0], SIP_NAT_FORCE_RPORT);
    ast_set_flag(&mask[1], SIP_PAGE2_SYMMETRICRTP);
    ast_set_flag(&mask[2], SIP_PAGE3_NAT_AUTO_RPORT);
    ast_set_flag(&mask[2], SIP_PAGE3_NAT_AUTO_COMEDIA);
    while ((this = strsep(&parse, ","))) {
       if (ast_false(this)) {
          ast_clear_flag(&flags[0], SIP_NAT_FORCE_RPORT);
          ast_clear_flag(&flags[1], SIP_PAGE2_SYMMETRICRTP);
          ast_clear_flag(&flags[2], SIP_PAGE3_NAT_AUTO_RPORT);
          ast_clear_flag(&flags[2], SIP_PAGE3_NAT_AUTO_COMEDIA);
          break; /* It doesn't make sense to have no + something else */
       } else if (!strcasecmp(this, "yes")) {
          ast_log(LOG_WARNING, "nat=yes is deprecated, use nat=force_rport,comedia instead\n");
          ast_set_flag(&flags[0], SIP_NAT_FORCE_RPORT);
          ast_set_flag(&flags[1], SIP_PAGE2_SYMMETRICRTP);
          ast_clear_flag(&flags[2], SIP_PAGE3_NAT_AUTO_RPORT);
          ast_clear_flag(&flags[2], SIP_PAGE3_NAT_AUTO_COMEDIA);
          break; /* It doesn't make sense to have yes + something else */
       } else if (!strcasecmp(this, "force_rport") && !ast_test_flag(&flags[2], SIP_PAGE3_NAT_AUTO_RPORT)) {
          ast_set_flag(&flags[0], SIP_NAT_FORCE_RPORT);
       } else if (!strcasecmp(this, "comedia") && !ast_test_flag(&flags[2], SIP_PAGE3_NAT_AUTO_COMEDIA)) {
          ast_set_flag(&flags[1], SIP_PAGE2_SYMMETRICRTP);
       } else if (!strcasecmp(this, "auto_force_rport")) {
          ast_set_flag(&flags[2], SIP_PAGE3_NAT_AUTO_RPORT);
          /* In case someone did something dumb like nat=force_rport,auto_force_rport */
          ast_clear_flag(&flags[0], SIP_NAT_FORCE_RPORT);
       } else if (!strcasecmp(this, "auto_comedia")) {
          ast_set_flag(&flags[2], SIP_PAGE3_NAT_AUTO_COMEDIA);
          /* In case someone did something dumb like nat=comedia,auto_comedia*/
          ast_clear_flag(&flags[1], SIP_PAGE2_SYMMETRICRTP);
       }
    }
 }
sip_parse_register_line()
int sip_parse_register_line (struct sip_registry * reg, int default_expiry, const char * value, int lineno)
Parse register=> line in sip.conf.
Return values
0 on success
-1 on failure
register => [peer?][transport://]user[][:secret[:authuser]][:port][/extension][~expiry] becomes userpart => [peer?][transport://]user[][:secret[:authuser]] hostpart => host[:port][/extension][~expiry]
pre1.peer => peer pre1.userpart => [transport://]user[][:secret[:authuser]] hostpart => host[:port][/extension][~expiry]
pre1.peer => peer pre2.transport = transport pre2.userpart => user[][:secret[:authuser]] hostpart => host[:port][/extension][~expiry]
pre1.peer => peer pre2.transport = transport user1.userpart => user[] user1.secret => secret user1.authuser => authuser hostpart => host[:port][/extension][~expiry]
pre1.peer => peer pre2.transport = transport user1.userpart => user[] user1.secret => secret user1.authuser => authuser host1.hostpart => host[:port][/extension] host1.expiry => [expiry]
pre1.peer => peer pre2.transport = transport user1.userpart => user[] user1.secret => secret user1.authuser => authuser host2.hostpart => host[:port] host2.extension => [extension] host1.expiry => [expiry]
pre1.peer => peer pre2.transport = transport user1.userpart => user[] user1.secret => secret user1.authuser => authuser host3.host => host host3.port => port host2.extension => extension host1.expiry => expiry
pre1.peer => peer pre2.transport = transport user2.user => user user2.domain => domain user1.secret => secret user1.authuser => authuser host3.host => host host3.port => port host2.extension => extension host1.expiry => expiry
pre1.peer => peer pre2.transport = transport user2.user => user user2.domain => domain user1.secret => secret user3.authuser => authuser user3.domainport => domainport host3.host => host host3.port => port host2.extension => extension host1.expiry => expiry
Definition at line 37 of file config_parser.c.
References AST_APP_ARG, ast_copy_string(), AST_DECLARE_APP_ARGS, ast_log, AST_NONSTANDARD_RAW_ARGS, ast_string_field_set, ast_strip_quoted(), ast_strlen_zero, AST_TRANSPORT_TCP, AST_TRANSPORT_TLS, AST_TRANSPORT_UDP, buf, sip_registry::callid_valid, sip_registry::configured_expiry, default_expiry, sip_registry::expire, sip_registry::expiry, FALSE, host, hostname, INITIAL_CSEQ, LOG_NOTICE, LOG_WARNING, NULL, sip_registry::ocseq, port_str2int(), sip_registry::portno, sip_registry::refresh, sip_registry::regdomainport, S_OR, STANDARD_SIP_PORT, STANDARD_TLS_PORT, sip_registry::timeout, and sip_registry::transport.
Referenced by AST_TEST_DEFINE(), and sip_register().
 {
    int portnum = 0;
    int domainport = 0;
    enum ast_transport transport = AST_TRANSPORT_UDP;
    char buf[256] = "";
    char *userpart = NULL, *hostpart = NULL;
    /* register => [peer?][transport://]user[@domain][:secret[:authuser]]@host[:port][/extension][~expiry] */
    AST_DECLARE_APP_ARGS(pre1,
       AST_APP_ARG(peer);
       AST_APP_ARG(userpart);
    );
    AST_DECLARE_APP_ARGS(pre2,
       AST_APP_ARG(transport);
       AST_APP_ARG(blank);
       AST_APP_ARG(userpart);
    );
    AST_DECLARE_APP_ARGS(user1,
       AST_APP_ARG(userpart);
       AST_APP_ARG(secret);
       AST_APP_ARG(authuser);
    );
    AST_DECLARE_APP_ARGS(user2,
       AST_APP_ARG(user);
       AST_APP_ARG(domain);
    );
    AST_DECLARE_APP_ARGS(user3,
       AST_APP_ARG(authuser);
       AST_APP_ARG(domainport);
    );
    AST_DECLARE_APP_ARGS(host1,
       AST_APP_ARG(hostpart);
       AST_APP_ARG(expiry);
    );
    AST_DECLARE_APP_ARGS(host2,
       AST_APP_ARG(hostpart);
       AST_APP_ARG(extension);
    );
    AST_DECLARE_APP_ARGS(host3,
       AST_APP_ARG(host);
       AST_APP_ARG(port);
    );
    if (!reg) {
       return -1;
    }
    reg->expire = -1;
    reg->timeout = -1;
    if (!value) {
       return -1;
    }
    ast_copy_string(buf, value, sizeof(buf));
    /*! register => [peer?][transport://]user[@domain][:secret[:authuser]]@host[:port][/extension][~expiry]
     * becomes
     *   userpart => [peer?][transport://]user[@domain][:secret[:authuser]]
     *   hostpart => host[:port][/extension][~expiry]
     */
    if ((hostpart = strrchr(buf, '@'))) {
       *hostpart++ = '\0';
       userpart = buf;
    }
    if (ast_strlen_zero(userpart) || ast_strlen_zero(hostpart)) {
       ast_log(LOG_WARNING, "Format for registration is [peer?][transport://]user[@domain][:secret[:authuser]]@host[:port][/extension][~expiry] at line %d\n", lineno);
       return -1;
    }
    /*!
     * pre1.peer => peer
     * pre1.userpart => [transport://]user[@domain][:secret[:authuser]]
     * hostpart => host[:port][/extension][~expiry]
     */
    AST_NONSTANDARD_RAW_ARGS(pre1, userpart, '?');
    if (ast_strlen_zero(pre1.userpart)) {
       pre1.userpart = pre1.peer;
       pre1.peer = NULL;
    }
    /*!
     * pre1.peer => peer
     * pre2.transport = transport
     * pre2.userpart => user[@domain][:secret[:authuser]]
     * hostpart => host[:port][/extension][~expiry]
     */
    AST_NONSTANDARD_RAW_ARGS(pre2, pre1.userpart, '/');
    if (ast_strlen_zero(pre2.userpart)) {
       pre2.userpart = pre2.transport;
       pre2.transport = NULL;
    } else {
       pre2.transport[strlen(pre2.transport) - 1] = '\0'; /* Remove trailing : */
    }
    if (!ast_strlen_zero(pre2.blank)) {
       ast_log(LOG_WARNING, "Format for registration is [peer?][transport://]user[@domain][:secret[:authuser]]@host[:port][/extension][~expiry] at line %d\n", lineno);
       return -1;
    }
    /*!
     * pre1.peer => peer
     * pre2.transport = transport
     * user1.userpart => user[@domain]
     * user1.secret => secret
     * user1.authuser => authuser
     * hostpart => host[:port][/extension][~expiry]
     */
    AST_NONSTANDARD_RAW_ARGS(user1, pre2.userpart, ':');
    /*!
     * pre1.peer => peer
     * pre2.transport = transport
     * user1.userpart => user[@domain]
     * user1.secret => secret
     * user1.authuser => authuser
     * host1.hostpart => host[:port][/extension]
     * host1.expiry => [expiry]
     */
    AST_NONSTANDARD_RAW_ARGS(host1, hostpart, '~');
    /*!
     * pre1.peer => peer
     * pre2.transport = transport
     * user1.userpart => user[@domain]
     * user1.secret => secret
     * user1.authuser => authuser
     * host2.hostpart => host[:port]
     * host2.extension => [extension]
     * host1.expiry => [expiry]
     */
    AST_NONSTANDARD_RAW_ARGS(host2, host1.hostpart, '/');
    /*!
     * pre1.peer => peer
     * pre2.transport = transport
     * user1.userpart => user[@domain]
     * user1.secret => secret
     * user1.authuser => authuser
     * host3.host => host
     * host3.port => port
     * host2.extension => extension
     * host1.expiry => expiry
     */
    AST_NONSTANDARD_RAW_ARGS(host3, host2.hostpart, ':');
    /*!
      * pre1.peer => peer
      * pre2.transport = transport
      * user2.user => user
      * user2.domain => domain
      * user1.secret => secret
      * user1.authuser => authuser
      * host3.host => host
      * host3.port => port
      * host2.extension => extension
      * host1.expiry => expiry
     */
    AST_NONSTANDARD_RAW_ARGS(user2, user1.userpart, '@');
    /*!
      * pre1.peer => peer
      * pre2.transport = transport
      * user2.user => user
      * user2.domain => domain
      * user1.secret => secret
      * user3.authuser => authuser
      * user3.domainport => domainport
      * host3.host => host
      * host3.port => port
      * host2.extension => extension
      * host1.expiry => expiry
     */
    AST_NONSTANDARD_RAW_ARGS(user3, user1.authuser, ':');
    /* Reordering needed due to fields being [(:secret[:username])|(:regdomainport:secret:username)]
       but parsing being [secret[:username[:regdomainport]]] */
    if (user3.argc == 2) {
       char *reorder = user3.domainport;
       user3.domainport = user1.secret;
       user1.secret = user3.authuser;
       user3.authuser = reorder;
    }
    if (host3.port) {
       if (!(portnum = port_str2int(host3.port, 0))) {
          ast_log(LOG_NOTICE, "'%s' is not a valid port number on line %d of sip.conf. using default.\n", host3.port, lineno);
       }
    }
    if (user3.domainport) {
       if (!(domainport = port_str2int(user3.domainport, 0))) {
          ast_log(LOG_NOTICE, "'%s' is not a valid domain port number on line %d of sip.conf. using default.\n", user3.domainport, lineno);
       }
    }
    /* set transport type */
    if (!pre2.transport) {
       transport = AST_TRANSPORT_UDP;
    } else if (!strncasecmp(pre2.transport, "tcp", 3)) {
       transport = AST_TRANSPORT_TCP;
    } else if (!strncasecmp(pre2.transport, "tls", 3)) {
       transport = AST_TRANSPORT_TLS;
    } else if (!strncasecmp(pre2.transport, "udp", 3)) {
       transport = AST_TRANSPORT_UDP;
    } else {
       transport = AST_TRANSPORT_UDP;
       ast_log(LOG_NOTICE, "'%.3s' is not a valid transport type on line %d of sip.conf. defaulting to udp.\n", pre2.transport, lineno);
    }
    /* if no portnum specified, set default for transport */
    if (!portnum) {
       if (transport == AST_TRANSPORT_TLS) {
          portnum = STANDARD_TLS_PORT;
       } else {
          portnum = STANDARD_SIP_PORT;
       }
    }
    /* copy into sip_registry object */
    ast_string_field_set(reg, callback, ast_strip_quoted(S_OR(host2.extension, "s"), "\"", "\""));
    ast_string_field_set(reg, username, ast_strip_quoted(S_OR(user2.user, ""), "\"", "\""));
    ast_string_field_set(reg, hostname, ast_strip_quoted(S_OR(host3.host, ""), "\"", "\""));
    ast_string_field_set(reg, authuser, ast_strip_quoted(S_OR(user3.authuser, ""), "\"", "\""));
    ast_string_field_set(reg, secret, ast_strip_quoted(S_OR(user1.secret, ""), "\"", "\""));
    ast_string_field_set(reg, peername, ast_strip_quoted(S_OR(pre1.peer, ""), "\"", "\""));
    ast_string_field_set(reg, regdomain, ast_strip_quoted(S_OR(user2.domain, ""), "\"", "\""));
    reg->transport = transport;
    reg->portno = portnum;
    reg->regdomainport = domainport;
    reg->callid_valid = FALSE;
    reg->ocseq = INITIAL_CSEQ;
    reg->refresh = reg->expiry = reg->configured_expiry = (host1.expiry ? atoi(ast_strip_quoted(host1.expiry, "\"", "\"")) : default_expiry);
    return 0;
 }