Asterisk - The Open Source Telephony Project: test_res_pjsip_session_caps.c File Reference
test_res_pjsip_session_caps.c File Reference
res_pjsip_session format caps tests
#include "asterisk.h"
#include "asterisk/test.h"
#include "asterisk/module.h"
#include "asterisk/res_pjsip.h"
#include "asterisk/utils.h"
#include "asterisk/format.h"
#include "asterisk/format_cap.h"
#include "asterisk/res_pjsip_session.h"
#include "asterisk/res_pjsip_session_caps.h"
Macros
#define RUN_CREATE_JOINT(local, remote, pref, outgoing, expected, result)
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
AST_TEST_DEFINE (low_level)
static int load_module (void)
static enum ast_test_result_state test_create_joint (struct ast_test *test, const char *local_string, const char *remote_string, const char *pref_string, int is_outgoing, const char *expected_string, enum ast_test_result_state expected_result)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_DEFAULT , .description = "res_pjsip_session caps test module" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .requires = "res_pjsip_session", }
static const struct ast_module_info * ast_module_info = &__mod_info
Detailed Description
res_pjsip_session format caps tests
Author
George Joseph gjose.nosp@m.ph@s.nosp@m.angom.nosp@m.a.co.nosp@m.m
Definition in file test_res_pjsip_session_caps.c.
Macro Definition Documentation
RUN_CREATE_JOINT
#define RUN_CREATE_JOINT (local, remote, pref, outgoing, expected, result)
Value:
do { \
   if (test_create_joint(test, local, remote, pref, outgoing, expected, result) != AST_TEST_PASS) { \
      rc += 1; \
   } \
} while (0)
Definition at line 110 of file test_res_pjsip_session_caps.c.
Referenced by AST_TEST_DEFINE().
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 176 of file test_res_pjsip_session_caps.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 176 of file test_res_pjsip_session_caps.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 176 of file test_res_pjsip_session_caps.c.
AST_TEST_DEFINE()
AST_TEST_DEFINE (low_level)
Definition at line 117 of file test_res_pjsip_session_caps.c.
References AST_TEST_FAIL, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_test_status_update, sip_to_pjsip::info(), RUN_CREATE_JOINT, TEST_EXECUTE, and TEST_INIT.
 {
    int rc = 0;
    switch (cmd) {
    case TEST_INIT:
       info->name = __func__;
       info->category = "/res/res_pjsip_session/caps/";
       info->summary = "Test res_pjsip_session_caps";
       info->description = "Test res_pjsip_session_caps";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    /* Incoming */
    ast_test_status_update(test, "Testing incoming expected pass\n");
    RUN_CREATE_JOINT("ulaw,alaw,g722",  "g722,alaw,g729", "local",       0, "alaw,g722",   AST_TEST_PASS);
    RUN_CREATE_JOINT("ulaw,alaw,g722",  "g722,alaw,g729", "local_first", 0, "alaw",        AST_TEST_PASS);
    RUN_CREATE_JOINT("slin",         "all",            "local",    0, "slin",        AST_TEST_PASS);
    RUN_CREATE_JOINT("ulaw,alaw,g722",  "g722,alaw,g729", "remote",      0, "g722,alaw",   AST_TEST_PASS);
    RUN_CREATE_JOINT("ulaw,alaw,g722",  "g722,alaw,g729", "remote_first",   0, "g722",        AST_TEST_PASS);
    RUN_CREATE_JOINT("all",          "slin",           "remote_first",   0, "slin",        AST_TEST_PASS);
    ast_test_status_update(test, "Testing incoming expected fail\n");
    RUN_CREATE_JOINT("ulaw,alaw,g722",  "g729",           "local",    0, "",            AST_TEST_FAIL);
    RUN_CREATE_JOINT("ulaw,alaw,g722",  "g722,alaw,g729", "local_merge", 0, "",            AST_TEST_FAIL);
    RUN_CREATE_JOINT("ulaw,alaw,g722",  "g722,alaw,g729", "remote_merge",   0, "",            AST_TEST_FAIL);
    ast_test_status_update(test, "Testing outgoing expected pass\n");
    RUN_CREATE_JOINT("ulaw,alaw,g722",  "g722,g729,alaw", "local",    1, "alaw,g722",         AST_TEST_PASS);
    RUN_CREATE_JOINT("ulaw,alaw,g722",  "g722,g729,alaw", "local_first", 1, "alaw",              AST_TEST_PASS);
    RUN_CREATE_JOINT("ulaw,alaw,g722",  "g722,g729,alaw", "local_merge", 1, "ulaw,alaw,g722", AST_TEST_PASS);
    RUN_CREATE_JOINT("ulaw,alaw,g722",  "g722,g729,alaw", "remote",      1, "g722,alaw",         AST_TEST_PASS);
    RUN_CREATE_JOINT("ulaw,alaw,g722",  "g722,g729,alaw", "remote_first",   1, "g722",              AST_TEST_PASS);
    RUN_CREATE_JOINT("ulaw,alaw,g722",  "g722,g729,alaw", "remote_merge",   1, "g722,alaw,ulaw", AST_TEST_PASS);
    RUN_CREATE_JOINT("!all",         "g722,g729,alaw", "remote_merge",   1, "nothing",     AST_TEST_PASS);
    return rc >= 1 ? AST_TEST_FAIL : AST_TEST_PASS;
 }
load_module()
static int load_module (void) static
Definition at line 159 of file test_res_pjsip_session_caps.c.
References AST_MODULE_LOAD_SUCCESS, and AST_TEST_REGISTER.
Referenced by unload_module().
 {
    AST_TEST_REGISTER(low_level);
    return AST_MODULE_LOAD_SUCCESS;
 }
test_create_joint()
static enum ast_test_result_state test_create_joint (struct ast_test * test, const char * local_string, const char * remote_string, const char * pref_string, int is_outgoing, const char * expected_string, enum ast_test_result_state expected_result) static
Definition at line 46 of file test_res_pjsip_session_caps.c.
References ao2_cleanup, ast_format_cap_alloc, AST_FORMAT_CAP_FLAG_DEFAULT, ast_format_cap_get_names(), AST_FORMAT_CAP_NAMES_LEN, ast_format_cap_update_by_allow_disallow(), AST_MEDIA_TYPE_AUDIO, ast_sip_call_codec_str_to_pref(), ast_sip_create_joint_call_cap(), ast_str_alloca, ast_str_strlen(), ast_str_truncate(), AST_TEST_FAIL, AST_TEST_PASS, ast_test_status_update, NULL, and RAII_VAR.
 {
    RAII_VAR(struct ast_format_cap *, local, ast_format_cap_alloc(AST_FORMAT_CAP_FLAG_DEFAULT), ao2_cleanup);
    RAII_VAR(struct ast_format_cap *, remote, ast_format_cap_alloc(AST_FORMAT_CAP_FLAG_DEFAULT), ao2_cleanup);
    RAII_VAR(struct ast_format_cap *, joint, ast_format_cap_alloc(AST_FORMAT_CAP_FLAG_DEFAULT), ao2_cleanup);
    struct ast_str *joint_str = ast_str_alloca(AST_FORMAT_CAP_NAMES_LEN);
    const char *joint_string;
    char *stripped_joint;
    struct ast_flags codec_prefs;
    int rc;
    int i;
    ast_test_status_update(test, "Testing local: (%s), remote: (%s), pref: (%-12s), outgoing: (%s), expected: (%s) expected result: (%s)\n",
       local_string, remote_string, pref_string, is_outgoing ? "yes" : "no ", expected_string,
       expected_result == AST_TEST_PASS ? "PASS" : "FAIL");
    ast_test_validate(test, local != NULL && remote != NULL && joint != NULL);
    rc = ast_format_cap_update_by_allow_disallow(local, local_string, 1);
    if (rc != 0) {
       ast_test_status_update(test, "    %sxpected Failure: Coulldn't parse local codecs (%s)\n",
          expected_result == AST_TEST_FAIL ? "E" : "Une", local_string);
       return expected_result == AST_TEST_FAIL ? AST_TEST_PASS : AST_TEST_FAIL;
    }
    rc = ast_format_cap_update_by_allow_disallow(remote, remote_string, 1);
    if (rc != 0) {
       ast_test_status_update(test, "    %sxpected Failure: Coulldn't parse remote codecs (%s)\n",
          expected_result == AST_TEST_FAIL ? "E" : "Une", remote_string);
       return expected_result == AST_TEST_FAIL ? AST_TEST_PASS : AST_TEST_FAIL;
    }
    rc = ast_sip_call_codec_str_to_pref(&codec_prefs, pref_string, is_outgoing);
    if (rc != 0) {
       ast_test_status_update(test, "    %sxpected Failure: Invalid preference string incoming/outgoing combination.\n",
          expected_result == AST_TEST_FAIL ? "E" : "Une");
       return expected_result == AST_TEST_FAIL ? AST_TEST_PASS : AST_TEST_FAIL;
    }
    joint = ast_sip_create_joint_call_cap(remote, local, AST_MEDIA_TYPE_AUDIO, codec_prefs);
    if (joint == NULL) {
       ast_test_status_update(test, "    %sxpected Failure: No joint caps.\n",
          expected_result == AST_TEST_FAIL ? "E" : "Une");
       return expected_result == AST_TEST_FAIL ? AST_TEST_PASS : AST_TEST_FAIL;
    }
    joint_string = ast_format_cap_get_names(joint, &joint_str);
    stripped_joint = ast_str_truncate(joint_str, ast_str_strlen(joint_str) - 1) + 1;
    for(i = 0; i <= strlen(stripped_joint); i++) {
       if(stripped_joint[i] == '|') {
          stripped_joint[i] = ',';
       }
    }
    if (!joint_string || strcmp(stripped_joint, expected_string) != 0) {
       ast_test_status_update(test, "    %sxpected Failure: Expected: (%s) Actual: (%s)\n",
          expected_result == AST_TEST_FAIL ? "E" : "Une", expected_string, stripped_joint);
       return expected_result == AST_TEST_FAIL ? AST_TEST_PASS : AST_TEST_FAIL;
    }
    return AST_TEST_PASS;
 }
unload_module()
static int unload_module (void) static
Definition at line 165 of file test_res_pjsip_session_caps.c.
References AST_MODFLAG_DEFAULT, AST_MODULE_INFO(), AST_MODULE_SUPPORT_CORE, AST_TEST_UNREGISTER, ASTERISK_GPL_KEY, and load_module().
 {
    AST_TEST_UNREGISTER(low_level);
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_DEFAULT , .description = "res_pjsip_session caps test module" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .requires = "res_pjsip_session", } static
Definition at line 176 of file test_res_pjsip_session_caps.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 176 of file test_res_pjsip_session_caps.c.