Asterisk - The Open Source Telephony Project: ast_sorcery_instance_observer Struct Reference
ast_sorcery_instance_observer Struct Reference
Interface for the sorcery instance observer.
#include <sorcery.h>
Data Fields
void(* instance_loaded)(const char *name, const struct ast_sorcery *sorcery, int reloaded)
Callback after instance is loaded/reloaded.
void(* instance_loading)(const char *name, const struct ast_sorcery *sorcery, int reloaded)
Callback before instance is loaded/reloaded.
void(* object_type_loaded)(const char *name, const struct ast_sorcery *sorcery, const char *object_type, int reloaded)
Callback after any object_type is loaded/reloaded.
void(* object_type_loading)(const char *name, const struct ast_sorcery *sorcery, const char *object_type, int reloaded)
Callback before any object_type is loaded/reloaded.
void(* object_type_registered)(const char *name, struct ast_sorcery *sorcery, const char *object_type)
Callback after any object_type is registered.
void(* wizard_mapped)(const char *name, struct ast_sorcery *sorcery, const char *object_type, struct ast_sorcery_wizard *wizard, const char *wizard_args, void *wizard_data)
Callback after a wizard is mapped to an object_type.
Detailed Description
Interface for the sorcery instance observer.
Definition at line 237 of file sorcery.h.
Field Documentation
instance_loaded
void(* instance_loaded) (const char *name, const struct ast_sorcery *sorcery, int reloaded)
Callback after instance is loaded/reloaded.
Definition at line 243 of file sorcery.h.
Referenced by AST_TEST_DEFINE().
instance_loading
void(* instance_loading) (const char *name, const struct ast_sorcery *sorcery, int reloaded)
Callback before instance is loaded/reloaded.
Definition at line 239 of file sorcery.h.
Referenced by AST_TEST_DEFINE().
object_type_loaded
void(* object_type_loaded) (const char *name, const struct ast_sorcery *sorcery, const char *object_type, int reloaded)
Callback after any object_type is loaded/reloaded.
Definition at line 260 of file sorcery.h.
Referenced by AST_TEST_DEFINE().
object_type_loading
void(* object_type_loading) (const char *name, const struct ast_sorcery *sorcery, const char *object_type, int reloaded)
Callback before any object_type is loaded/reloaded.
Definition at line 256 of file sorcery.h.
Referenced by AST_TEST_DEFINE().
object_type_registered
void(* object_type_registered) (const char *name, struct ast_sorcery *sorcery, const char *object_type)
Callback after any object_type is registered.
Definition at line 252 of file sorcery.h.
wizard_mapped
void(* wizard_mapped) (const char *name, struct ast_sorcery *sorcery, const char *object_type, struct ast_sorcery_wizard *wizard, const char *wizard_args, void *wizard_data)
Callback after a wizard is mapped to an object_type.
Definition at line 247 of file sorcery.h.
Referenced by AST_TEST_DEFINE().
The documentation for this struct was generated from the following file:
sorcery.h