Asterisk - The Open Source Telephony Project: frame.h File Reference
utils/frame.h File Reference
Macros
#define BUFFSIZE 50000 /* How many samples to read in one go (preferred) */
#define DEFAULTFREQ 44100
#define FALSE (0==1)
#define INBIN (1+2)
#define INTEXT (1+0)
#define IOBIN (32)
#define MINBUFFSIZE 5000 /* How many samples to read in one go (minimum) */
#define NOCOMPLAIN (16)
#define NOFILES (0)
#define OUTBIN (4+8)
#define OUTTEXT (4)
#define TRUE (0==0)
Enumerations
enum Errornum {
ME_NOINT, ME_NODOUBLE, ME_NOTIME, ME_NOVOL,
ME_NOSWITCH, ME_TOOMANYFILES, ME_HEADERONTEXTFILE, ME_NOINFILE,
ME_NOOUTFILE, ME_NOIOFILE, ME_NOSTDIN, ME_NOSTDOUT,
ME_NOSTDIO, ME_NOTENOUGHFILES, ME_THISCANTHAPPEN
}
Functions
void argerror (char *s)
void argerrornum (char *s, Errornum code)
void argerrortxt (char *s, char *message)
int chat (const char *format,...)
void checknoargs (int argcount, char *args[])
double double2db (double value)
int error (const char *format,...)
void fatalerror (const char *format,...)
void fatalperror (const char *string)
int findoption (int argcount, char *args[], char *s)
int getremainingfilelength (FILE *anyin, long *result)
int inform (const char *format,...)
int isoptionchar (char coal)
void makewavheader (void)
char * mallocconcat (char *one, char *two)
char * malloccopy (char *string)
int myexit (int value)
void parseargs (int argcount, char *args[], int fileswitch)
int parsedoublearg (int argcount, char *args[], char *string, double *result)
char * parsefilearg (int argcount, char *args[])
int parsefreq (char *string, double *result)
int parseintarg (int argcount, char *args[], char *string, int *result)
int parseswitch (char *found, char *wanted)
int parseswitcharg (int argcount, char *args[], char *string)
int parsetime (char *string, int *result)
int parsetimearg (int argcount, char *args[], char *string, int *result)
int parsevolarg (int argcount, char *args[], char *string, double *result)
int parsevolume (char *s, double *result)
void readawaysamples (FILE *in, size_t size)
void readpkheader (FILE *anyin)
void readwavheader (FILE *anyin)
int say (const char *format,...)
void startstopwatch (void)
int workloop (FILE *theinfile, FILE *theoutfile, int(*work)(short *buffer, int length))
Variables
unsigned short channels
FILE * in
char * infilename
int iswav
FILE * out
char * outfilename
int samplefrequency
unsigned short samplewidth
char * usage
int verboselevel
char * version
int wavout
Macro Definition Documentation
BUFFSIZE
#define BUFFSIZE 50000 /* How many samples to read in one go (preferred) */
Definition at line 54 of file utils/frame.h.
Referenced by main(), readawaysamples(), and workloop().
DEFAULTFREQ
#define DEFAULTFREQ 44100
Definition at line 53 of file utils/frame.h.
Referenced by parseargs().
FALSE
#define FALSE (0==1)
Definition at line 36 of file utils/frame.h.
INBIN
#define INBIN (1+2)
Definition at line 28 of file utils/frame.h.
INTEXT
#define INTEXT (1+0)
Definition at line 27 of file utils/frame.h.
IOBIN
#define IOBIN (32)
Definition at line 33 of file utils/frame.h.
MINBUFFSIZE
#define MINBUFFSIZE 5000 /* How many samples to read in one go (minimum) */
Definition at line 55 of file utils/frame.h.
NOCOMPLAIN
#define NOCOMPLAIN (16)
Definition at line 32 of file utils/frame.h.
Referenced by main().
NOFILES
#define NOFILES (0)
Definition at line 31 of file utils/frame.h.
Referenced by main().
OUTBIN
#define OUTBIN (4+8)
Definition at line 30 of file utils/frame.h.
OUTTEXT
#define OUTTEXT (4)
Definition at line 29 of file utils/frame.h.
TRUE
#define TRUE (0==0)
Definition at line 37 of file utils/frame.h.
Enumeration Type Documentation
Errornum
enum Errornum
Enumerator
ME_NOINT
ME_NODOUBLE
ME_NOTIME
ME_NOVOL
ME_NOSWITCH
ME_TOOMANYFILES
ME_HEADERONTEXTFILE
ME_NOINFILE
ME_NOOUTFILE
ME_NOIOFILE
ME_NOSTDIN
ME_NOSTDOUT
ME_NOSTDIO
ME_NOTENOUGHFILES
ME_THISCANTHAPPEN
Definition at line 60 of file utils/frame.h.
 {
   ME_NOINT,
   ME_NODOUBLE,
   ME_NOTIME,
   ME_NOVOL,
   ME_NOSWITCH,
   ME_TOOMANYFILES,
   ME_HEADERONTEXTFILE,
   ME_NOINFILE,
   ME_NOOUTFILE,
   ME_NOIOFILE,
   ME_NOSTDIN,
   ME_NOSTDOUT,
   ME_NOSTDIO,
   ME_NOTENOUGHFILES,
   ME_THISCANTHAPPEN
 } Errornum;
Function Documentation
argerror()
void argerror (char * s)
Definition at line 625 of file utils/frame.c.
References error(), and fatalerror().
 {
   error ("Error parsing command line. Unrecognized option:\n\t-%s\n", s);
   fatalerror("\nTry --help for help.\n");
 }
argerrornum()
void argerrornum (char * s, Errornum code)
Definition at line 635 of file utils/frame.c.
References error(), fatalerror(), ME_HEADERONTEXTFILE, ME_NODOUBLE, ME_NOINFILE, ME_NOINT, ME_NOIOFILE, ME_NOOUTFILE, ME_NOSTDIN, ME_NOSTDIO, ME_NOSTDOUT, ME_NOSWITCH, ME_NOTENOUGHFILES, ME_NOTIME, ME_NOVOL, ME_THISCANTHAPPEN, ME_TOOMANYFILES, and NULL.
Referenced by main(), parseargs(), parsedoublearg(), parsefreq(), parseintarg(), parseswitch(), parseswitcharg(), parsetime(), parsetimearg(), and parsevolarg().
 {
   char *message;
   if (code == ME_TOOMANYFILES)
     {
       error("Too many files on command line: '%s'.\n", s);
     }
   else
     {
       if (s != NULL)
    error ("Error parsing option -%s:\n\t", s);
       switch( code)
    {
    case ME_NOINT:
      message = "Integer expected";
      break;
    case ME_NODOUBLE:
      message = "Floating point number expected";
      break;
    case ME_NOTIME:
      message = "Time argument expected";
      break;
    case ME_NOVOL:
      message = "Volume argument expected";
      break;
    case ME_NOSWITCH:
      message = "Garbage after switch-type option";
      break;
    case ME_HEADERONTEXTFILE:
      message = "Option -h is not useful for text-output";
      break;
    case ME_NOINFILE:
      message = "No input file specified";
      break;
    case ME_NOOUTFILE:
      message = "No output file specified";
      break;
    case ME_NOIOFILE:
      message = "No input/output file specified";
      break;
    case ME_NOSTDIN:
      message = "Standard in not supported here";
      break;
    case ME_NOSTDOUT:
      message = "Standard out not supported here";
      break;
    case ME_NOSTDIO:
      message = "Standard in/out not supported here";
      break;
    case ME_NOTENOUGHFILES:
      message = "Not enough files specified";
      break;
    case ME_THISCANTHAPPEN:
      fatalerror("\nThis can't happen. Report this as a bug\n");
      /* fatalerror does not return */
    default:
      error("Error code %d not implemented. Fix me!\n", code);
      message = "Error message not implemented. Fix me!";
    }
       error("%s\n", message);
     }
   fatalerror("\nTry --help for help.\n");
 }
argerrortxt()
void argerrortxt (char * s, char * message)
Definition at line 704 of file utils/frame.c.
References error(), fatalerror(), and NULL.
Referenced by main(), and parseargs().
 {
   if (s != NULL)
     error ("Error parsing option -%s:\n\t", s);
   else
     error ("Error parsing command line:\n\t");
   error ("%s\n", message);
   fatalerror("\nTry --help for help.\n");
 }
chat()
int chat (const char * format, ...)
Definition at line 971 of file utils/frame.c.
References result, and verboselevel.
Referenced by makewavheader(), myexit(), and readwavheader().
 {
     va_list ap;
     int result = 0;
     if (verboselevel > 5)
     {
    va_start( ap, format);
    result = vfprintf( stderr, format, ap);
    va_end( ap);
     }
     return result;
 }
checknoargs()
void checknoargs (int argcount, char * args[])
Definition at line 717 of file utils/frame.c.
References error(), and fatalerror().
Referenced by main().
 {
   int i, errorcount = 0;
   for (i = 1; i < argcount; i++)
     {
       if (args[i][0] != '\0')   /* An unused argument! */
    {
      errorcount++;
      if (errorcount == 1)
        error("The following arguments were not recognized:\n");
      error("\t%s\n", args[i]);
    }
     }
   if (errorcount > 0)           /* Errors are fatal */
     fatalerror("\nTry --help for help.\n");
   return;                       /* No errors? Return. */
 }
double2db()
double double2db (double value)
Definition at line 1062 of file utils/frame.c.
References value.
 {
   if (value < 0)
     value = -value;
   return 6.0 * log( value / 32767) / log( 2);
 }
error()
int error (const char * format, ...)
Definition at line 999 of file utils/frame.c.
References result.
Referenced by __ast_pbx_run(), __rtp_recvfrom(), acl_handler(), acl_handler_fn(), aco_info_init(), aco_process_ast_config(), append_string(), apply_general_options(), argerror(), argerrornum(), argerrortxt(), ast_channel_internal_errno_set(), ast_iostream_printf(), ast_json_vpack(), ast_odbc_find_table(), ast_parse_arg(), ast_tcptls_client_create(), ast_tcptls_server_start(), AST_TEST_DEFINE(), ast_unload_resource(), authenticate(), build_callno_limits(), build_expression_queue(), build_peer(), cdr_handler(), checknoargs(), conf_load_config(), confbridge_cfg_alloc(), config_handler(), deliver_file(), endpoint_acl_handler(), evaluate_history_entry(), exec(), fax_gateway_attach(), fax_gateway_detect_t38(), fax_gateway_framehook(), fax_gateway_start(), generic_fax_exec(), handle_cli_agi_show(), handle_cli_queue_test(), handle_incoming(), handle_request_invite(), handler_wait_for_message(), http_callback(), ip_identify_match_handler(), ip_identify_match_host_lookup(), jingle_outgoing_hook(), jingle_send_error_response(), keypad_cfg_read(), load_config(), load_module(), load_or_reload_lua_stuff(), load_pjsip(), load_values_config(), logged_dlclose(), lua_get_state(), message_template_build(), mgcp_devicestate(), minivm_accmess_exec(), mysql_log(), named_acl_config_alloc(), ogg_speex_open(), osp_check_destination(), osp_create_provider(), osp_create_transaction(), osp_finish(), osp_load(), osp_lookup(), osp_next(), osp_validate_token(), parse_uri_full(), pjsip_enable_logger_host(), pubsub_on_rx_mwi_notify_request(), realtime_destroy_handler(), realtime_handler(), realtime_multi_handler(), realtime_store_handler(), realtime_update2_handler(), realtime_update_handler(), receivefax_exec(), refer_progress_alloc(), reload_config(), rtcp_debug_test_addr(), sendfax_exec(), setup_filestack(), skel_config_alloc(), store_config(), sub_persistence_recreate(), t30_phase_e_handler(), test_config_alloc(), transport_localnet_handler(), unbound_config_alloc(), update2_ldap(), user_event_wait_for_events(), verify_user_event_fields(), wait_for_channel_callback(), wait_for_device_state_updates(), write_cel(), xmpp_component_register_get_hook(), xmpp_config_alloc(), and xmpp_pubsub_handle_error().
 {
     va_list ap;
     int result;
     va_start( ap, format);
     result = vfprintf( stderr, format, ap);
     va_end( ap);
     return result;
 }
fatalerror()
void fatalerror (const char * format, ...)
Definition at line 1010 of file utils/frame.c.
References myexit().
Referenced by argerror(), argerrornum(), argerrortxt(), checknoargs(), main(), and parseargs().
 {
     va_list ap;
     va_start( ap, format);
     vfprintf( stderr, format, ap);
     va_end( ap);
     myexit(1);
 }
fatalperror()
void fatalperror (const char * string)
Definition at line 1020 of file utils/frame.c.
References myexit().
Referenced by main(), parsefilearg(), readawaysamples(), and workloop().
 {
   perror( string);
   myexit( 1);
 }
findoption()
int findoption (int argcount, char * args[], char * s)
Definition at line 900 of file utils/frame.c.
References isoptionchar(), and test_usage.
Referenced by parsedoublearg(), parseintarg(), parseswitcharg(), parsetimearg(), and parsevolarg().
 {
    int i;
    if (test_usage)
      printf("Checking for option -%s\n", s);
    for (i=1; i<argcount; i++)
    {
      if (isoptionchar (args[i][0]) &&
     strncmp( args[i] + 1, s, strlen( s)) == 0)
        {
     args[i][0] = '\0';
     return i;
        }
    }
    return -1;
 }
getremainingfilelength()
int getremainingfilelength (FILE * anyin, long * result)
Definition at line 58 of file utils/frame.c.
References FALSE, samplewidth, and TRUE.
 {
     long i;
     i = ftell(anyin);
     if (i == -1) return FALSE;
     if (fseek(anyin, 0, SEEK_END) == -1) return FALSE;
     *result = ftell(anyin);
     if (*result == -1) return FALSE;
     (*result) -= i;
     (*result) /= samplewidth;
     if (fseek(anyin, i, SEEK_SET) == -1) return FALSE;
     return TRUE;
 }
inform()
int inform (const char * format, ...)
Definition at line 985 of file utils/frame.c.
References result, and verboselevel.
Referenced by main(), parseargs(), and statistics().
 {
     va_list ap;
     int result = 0;
     if (verboselevel > 1)
     {
    va_start( ap, format);
    result = vfprintf( stderr, format, ap);
    va_end( ap);
     }
     return result;
 }
isoptionchar()
int isoptionchar (char coal)
Definition at line 319 of file utils/frame.c.
Referenced by findoption(), and parsefilearg().
 {
    return (coal =='-');
 }
makewavheader()
void makewavheader (void)
Definition at line 219 of file utils/frame.c.
References channels, chat(), out, and samplefrequency.
Referenced by main(), myexit(), and parseargs().
 {
    unsigned int tempuint, filelength;
    unsigned short tempushort;
    /* If fseek fails, don't create the header. */
    if (fseek(out, 0, SEEK_END) != -1)
    {
       filelength = ftell(out);
       chat("filelength %d, ", filelength);
       fseek(out, 0, SEEK_SET);
       if (!fwrite("RIFF", 1, 4, out)) { /* 0 */
          return;
       }
       tempuint = filelength - 8;
       if (!fwrite(&tempuint, 4, 1, out)) {    /* 4 */
          return;
       }
       if (!fwrite("WAVEfmt ", 1, 8, out)) {   /* 8 */
          return;
       }
       /* length of fmt data 16 bytes */
       tempuint = 16;
       if (!fwrite(&tempuint, 4, 1, out)) {   /* 16 */
          return;
       }
       /* Format tag: 1 for pcm */
       tempushort = 1;
       if (!fwrite(&tempushort, 2, 1, out)) { /* 20 */
          return;
       }
       chat("%d channels\n", channels);
       if (!fwrite(&channels, 2, 1, out)) {
          return;
       }
       chat("samplefrequency %d\n", samplefrequency);
       if (!fwrite(&samplefrequency, 4, 1, out)) {   /* 24 */
          return;
       }
       /* Bytes per second */
       tempuint = channels * samplefrequency * 2;
       if (!fwrite(&tempuint, 4, 1, out)) {         /* 28 */
          return;
       }
       /* Block align */
       tempushort = 2 * channels;
       if (!fwrite(&tempushort, 2, 1, out)) {       /* 32 */
          return;
       }
       /* Bits per sample */
       tempushort = 16;
       if (!fwrite(&tempushort, 2, 1, out)) {       /* 34 */
          return;
       }
       if (!fwrite("data", 4, 1, out)) {            /* 36 */
          return;
       }
       tempuint = filelength - 44;
       if (!fwrite(&tempuint, 4, 1, out)) {   /* 40 */
          return;
       }
    }
    return;
 }
mallocconcat()
char* mallocconcat (char * one, char * two)
Definition at line 1049 of file utils/frame.c.
References malloc(), NULL, and result.
 {
     char *result;
     result = malloc( strlen( one) + strlen( two) + 1);
     if (result != NULL)
       {
    strcpy( result, one);
    strcat( result, two);
       }
     return result;
 }
malloccopy()
char* malloccopy (char * string)
Definition at line 1038 of file utils/frame.c.
References malloc(), NULL, and result.
 {
     char *result;
     result = malloc( strlen( string) + 1);
     if (result != NULL)
    strcpy( result, string);
     return result;
 }
myexit()
int myexit (int value)
Definition at line 922 of file utils/frame.c.
References chat(), makewavheader(), and wavout.
Referenced by fatalerror(), fatalperror(), and main().
 {
   switch (value)
     {
     case 0:
       if (wavout)
    makewavheader();  /* Writes a fully informed .WAV header */
       chat("Success!\n");
       break;
     default:
       chat("Failure.\n");
       break;
     }
   exit (value);
 }
parseargs()
void parseargs (int argcount, char * args[], int fileswitch)
Definition at line 744 of file utils/frame.c.
References argerrornum(), argerrortxt(), channels, DEFAULTFREQ, errno, FALSE, fatalerror(), in, infilename, inform(), makewavheader(), ME_HEADERONTEXTFILE, ME_NOINFILE, ME_NOIOFILE, ME_NOOUTFILE, ME_NOSTDIN, ME_TOOMANYFILES, NULL, out, outfilename, parsefilearg(), parseintarg(), parseswitcharg(), readwavheader(), samplefrequency, samplewidth, standardusage, standardversion, test_usage, usage, verboselevel, version, and wavout.
Referenced by main().
 {
    char *filename;
    int tempint = 0;
    if ((fileswitch & 1) != 0)     /* If getting infile  */
      in = NULL;
    if ((fileswitch & 4) != 0)     /* If getting outfile */
      out = NULL;
    wavout = FALSE;
    verboselevel = 5;
    samplefrequency = DEFAULTFREQ;
    samplewidth = 2;
    channels = 1;
    /*-----------------------------------------------*
     * First first check testcase, usage and version *
     *-----------------------------------------------*/
    test_usage = parseswitcharg( argcount, args, "-test-usage");
    if (parseswitcharg( argcount, args, "-help"))
        {
     printf("%s%s", usage, standardusage);
     exit(0);
        }
    if (parseswitcharg( argcount, args, "-version"))
        {
     printf("%s\n(%s)\n", version, standardversion);
     exit(0);
        }
    /*--------------------------------------*
     * Set verboselevel                     *
     *--------------------------------------*/
    while (parseswitcharg( argcount, args, "V"))
                verboselevel = 10;
    while (parseswitcharg( argcount, args, "Q"))
                verboselevel = 1;
    /*-------------------------------------------------*
     * Get filenames and open files *
     *-------------------------------------------------*/
    if ((fileswitch & 1) != 0)        /* Infile wanted */
      {
        infilename = parsefilearg( argcount, args);
        if (infilename == NULL)
     argerrornum( NULL, ME_NOINFILE);
        if (strcmp( infilename, "-") == 0)
     {
       infilename = "<stdin>";
       in = stdin;
       if ((fileswitch & 2) != 0)   /* Binfile wanted */
         readwavheader( in);
     }
        else
     {
       if ((fileswitch & 2) == 0)   /* Textfile wanted */
         in = fopen(infilename, "rt");
       else                         /* Binfile wanted */
         if ((in = fopen(infilename, "rb")) != NULL)
           readwavheader( in);
     }
        if (in == NULL)
     fatalerror("Error opening input file '%s': %s\n", infilename,strerror(errno));
        else
     inform("Using file '%s' as input\n", infilename);
      }
    if ((fileswitch & 4) != 0)        /* Outfile wanted */
      {
        outfilename = parsefilearg( argcount, args);
        if (outfilename == NULL)
     argerrornum( NULL, ME_NOOUTFILE);
        if (strcmp( outfilename, "-") == 0)
     {
       outfilename = "<stdout>";
       out = stdout;
     }
        else
     {
       if ((fileswitch & 8) == 0)   /* Textfile wanted */
         out = fopen(outfilename, "wt");
       else                         /* Binfile wanted */
         out = fopen(outfilename, "wb");
     }
        if (out == NULL)
     fatalerror("Error opening output file '%s': %s\n", outfilename,strerror(errno));
        else
     inform("Using file '%s' as output\n", outfilename);
      }
    if ((fileswitch & 32) != 0)      /* In-/Outfile wanted */
      {
        assert (in == NULL && out == NULL);
        infilename = outfilename = parsefilearg( argcount, args);
        if (outfilename == NULL)
     argerrornum( NULL, ME_NOIOFILE);
        if (strcmp( infilename, "-") == 0)
     argerrornum( infilename, ME_NOSTDIN);
        inform("Using file '%s' as input/output\n", outfilename);
        in = out = fopen(outfilename, "r+");
        if (out == NULL)
     fatalerror("Error opening input/output file '%s': %s\n", outfilename,strerror(errno));
        readwavheader( in);
      }
    if ((fileswitch & 16) == 0)  /* No additional files wanted */
      {
        if ((filename = parsefilearg( argcount, args)) != NULL)
     argerrornum( filename, ME_TOOMANYFILES);
      }
    /*-------------------------------------------------*
     * Set samplefrequency, width, wavout,
     *-------------------------------------------------*/
    parseintarg( argcount, args, "f", &samplefrequency);
    wavout = parseswitcharg( argcount, args, "h");
    if (parseintarg( argcount, args, "w", &tempint))
      {
        if (tempint != 16)
     argerrortxt(NULL, "Option -w is only valid "
            "with value 16. Sorry.");
        else
     samplewidth = tempint;
      }
    if (parseintarg( argcount, args, "c", &tempint))
      {
        if (tempint != 1 && tempint != 2)
     argerrortxt(NULL, "Option -c is only valid "
            "with values 1 or 2. Sorry.");
        else
     channels = tempint;
      }
    /*-------------------------------------------------*
     * Create WAV-header on output if wanted.          *
     *-------------------------------------------------*/
    if (wavout)
      switch (fileswitch & (12))
        {
        case 4:   /* User wants header on textfile */
     argerrornum( NULL, ME_HEADERONTEXTFILE);
        case 12:  /* User wants header on binfile  */
     makewavheader();
     break;
        case 0:   /* User wants header, but there is no outfile */
     /* Problem: what about i/o-file, 32? You might want a header
        on that? Better ignore this case. */
     break;
        case 8:    /* An application musn't ask for this */
        default:   /* This can't happen */
     assert( FALSE);
        }
    return;
 }
parsedoublearg()
int parsedoublearg (int argcount, char * args[], char * string, double * result)
Definition at line 505 of file utils/frame.c.
References argerrornum(), end, FALSE, findoption(), ME_NODOUBLE, say(), and TRUE.
 {
   int i;
   double temp;
   char end;
   if ((i = findoption( argcount, args, string)) > 0)
     {
       switch (sscanf(args[i] + 1 + strlen( string), "%30lf%1c", &temp, &end))
    {
    case 0: case EOF: case 2:
      argerrornum(args[i]+1, ME_NODOUBLE);
      return FALSE;
    case 1:
      *result = temp;
      break;
    default:
      say("frame.c: This can't happen\n");
    }
       return TRUE;
     }
   else
     {
       return FALSE;
     }
 }
parsefilearg()
char* parsefilearg (int argcount, char * args[])
Definition at line 419 of file utils/frame.c.
References fatalperror(), isoptionchar(), malloc(), NULL, and result.
Referenced by main(), and parseargs().
 {
   int i;
   char *result = NULL;
    for (i = 1; i < argcount; i++)
    {
       if (args[i][0] != '\0' &&
      (!isoptionchar (args[i][0]) || args[i][1] == '\0' ))
       {
    /*---------------------------------------------*
     * The argument is a filename:                 *
     * it is either no dash followed by something, *
     * or it is a dash following by nothing.       *
     *---------------------------------------------*/
    result = malloc( strlen( args[i]) + 1);
    if (result == NULL)
        fatalperror( "Couldn't allocate memory for filename\n");
    strcpy( result, args[i]);
    args[i][0] = '\0';                    /* Mark as used up */
    break;
       }
    }
    return result;
 }
parsefreq()
int parsefreq (char * string, double * result)
Definition at line 393 of file utils/frame.c.
References argerrornum(), end, FALSE, ME_THISCANTHAPPEN, NULL, samplefrequency, and TRUE.
 {
     int k;
     double temp;
     char m, s, end;
     k = sscanf(string, "%30lf%1c%1c%1c", &temp, &m, &s, &end);
     switch (k)
       {
       case 0: case EOF: case 2: case 4:
    return FALSE;
       case 1:
    *result = temp;
    break;
       case 3:
    if (m == 'H' && s == 'z')
      *result = samplefrequency / temp;
    else
      return FALSE;
    break;
       default:
    argerrornum(NULL, ME_THISCANTHAPPEN);
       }
     return TRUE;
 }
parseintarg()
int parseintarg (int argcount, char * args[], char * string, int * result)
Definition at line 471 of file utils/frame.c.
References argerrornum(), c, FALSE, findoption(), ME_NOINT, say(), and TRUE.
Referenced by parseargs().
 {
   int i, temp;
   char c;
   if ((i = findoption( argcount, args, string)) > 0)
    {
       switch (sscanf(args[i] + 1 + strlen( string),
            "%30d%1c", &temp, &c))
       {
    case 0: case EOF: case 2:
             argerrornum(args[i]+1, ME_NOINT);
             return FALSE;
          case 1:
       *result = temp;
             break;
          default:
             say("frame.c: This can't happen\n");
       }
       return TRUE;
    }
   else
     {
       return FALSE;
     }
 }
parseswitch()
int parseswitch (char * found, char * wanted)
Definition at line 445 of file utils/frame.c.
References argerrornum(), FALSE, ME_NOSWITCH, and TRUE.
 {
   if (strncmp( found, wanted, strlen( wanted)) == 0)
     {
       if (found[strlen( wanted)] == '\0')
    return TRUE;
       else
    argerrornum( found, ME_NOSWITCH);
     }
   return FALSE;
 }
parseswitcharg()
int parseswitcharg (int argcount, char * args[], char * string)
Definition at line 457 of file utils/frame.c.
References argerrornum(), FALSE, findoption(), ME_NOSWITCH, and TRUE.
Referenced by parseargs().
 {
   int i;
   if ((i = findoption( argcount, args, string)) > 0)
     {
       if (args[i][strlen( string) + 1] == '\0')
    return TRUE;
       else
    argerrornum( args[i] + 1, ME_NOSWITCH);
     }
   return FALSE;
 }
parsetime()
int parsetime (char * string, int * result)
Definition at line 352 of file utils/frame.c.
References argerrornum(), end, FALSE, ME_THISCANTHAPPEN, NULL, samplefrequency, and TRUE.
Referenced by parsetimearg().
 {
     int k;
     double temp;
     char m, s, end;
     k = sscanf(string, "%30lf%1c%1c%1c", &temp, &m, &s, &end);
     switch (k)
       {
       case 0: case EOF: case 4:
    return FALSE;
       case 1:
    *result = temp;
    break;
       case 2:
    if (m == 's')
      *result = temp * samplefrequency;
    else
      return FALSE;
    break;
       case 3:
    if (m == 'm' && s == 's')
      *result = temp * samplefrequency / 1000;
    else if (m == 'H' && s == 'z')
      *result = samplefrequency / temp;
    else
      return FALSE;
    break;
       default:
    argerrornum(NULL, ME_THISCANTHAPPEN);
       }
     return TRUE;
 }
parsetimearg()
int parsetimearg (int argcount, char * args[], char * string, int * result)
Definition at line 332 of file utils/frame.c.
References argerrornum(), FALSE, findoption(), ME_NOTIME, parsetime(), and TRUE.
 {
     int i;
     if ((i = findoption( argcount, args, string)) > 0)
     {
    if (parsetime(args[i] + 1 + strlen( string), result))
        return TRUE;
    argerrornum(args[i]+1, ME_NOTIME);
     }
     return FALSE;
 }
parsevolarg()
int parsevolarg (int argcount, char * args[], char * string, double * result)
Definition at line 539 of file utils/frame.c.
References argerrornum(), end, FALSE, findoption(), ME_NOVOL, say(), and TRUE.
 {
   double vol = 1.0;
   char sbd, sbb, end;
   int i, weird = FALSE;
   if ((i = findoption( argcount, args, string)) > 0)
     {
       switch (sscanf(args[i] + 1 + strlen( string),
            "%30lf%1c%1c%1c", &vol, &sbd, &sbb, &end))
    {
      case 0: case EOF: case 4:
      weird = TRUE;
      break;    /* No number: error */
    case 1:
      *result = vol;
      break;
    case 2:
      if (sbd == '%')
        *result = vol / 100;
      else
        weird = TRUE;    /* One char but no percent: error */
      break;
    case 3:
      if (sbd =='d' && sbb == 'b')
        *result = pow(2, vol / 6.02);
      else
        weird = TRUE;    /* Two chars but not db: error */
      break;
    default:
      say("frame.c: This can't happen.\n");
    }
       if (weird)
    argerrornum( args[i] + 1, ME_NOVOL);
      /* ("Weird option: couldn't parse volume '%s'\n", args[i]+2); */
       return !weird;
     }
   else
     {
       return FALSE;
     }
 }
parsevolume()
int parsevolume (char * s, double * result)
Definition at line 590 of file utils/frame.c.
References end, FALSE, say(), and TRUE.
 {
     int k;
     char sbd, sbb, end;
     *result = 1.0;
     k = sscanf(s, "%30lf%1c%1c%1c", result, &sbd, &sbb, &end);
     switch (k)
     {
       case 0:
       case EOF:
       case 4:
        return FALSE;
       case 1:
        break;
       case 2:
        if (sbd != '%')
       return FALSE;
        (*result) /=100;
        break;
       case 3:
        if (sbd !='d' || sbb != 'b')
       return FALSE;
        (*result) = pow(2, (*result) / 6.02);
        break;
       default:
        say("parsevolume: This can't happen (%d).\n", k);
     }
     return TRUE;
 }
readawaysamples()
void readawaysamples (FILE * in, size_t size)
Definition at line 1069 of file utils/frame.c.
References BUFFSIZE, fatalperror(), free(), malloc(), and NULL.
 {
   short *buffer;
   int samplesread, count;
   buffer = malloc( sizeof( *buffer) * BUFFSIZE);
   if (buffer == NULL) fatalperror("Couldn't allocate buffer");
   while (size > 0)
     {
       if (size > BUFFSIZE)
    count = BUFFSIZE;
       else
    count = size;
       samplesread = fread( buffer, sizeof(*buffer), count, input);
       if (ferror( input) != 0)
    fatalperror("Error reading input file");
       size -= samplesread;
     }
   free( buffer);
 }
readpkheader()
void readpkheader (FILE * anyin)
Definition at line 76 of file utils/frame.c.
 {
    unsigned short tempushort;
    int tempint, i, x;
    unsigned char blood[8];
    for (i = 0; i < 11; i++)
    {
       if (!fread( &tempint, 4, 1, anyin)) {
          return;
       }
       printf( "%d: %d, ", i, tempint);
    }
    printf( "\n");
    if (!fread( blood, 1, 8, anyin)) {
       return;
    }
    for (i = 0; i < 8; i++)
       printf( "%d ", blood[i]);
    printf( "\n");
    for (i = 0; i < 8; i++)
    {
       for (x = 128; x > 0; x /= 2)
          printf((blood[i] & x) == 0? "0 ":"1 ");
       printf(i%4==3? "\n":"| ");
    }
    printf( "\n");
    for (i = 0; i < 2; i++)
    {
       if (!fread( &tempint, 4, 1, anyin)) {
          return;
       }
       printf( "%d: %d, ", i, tempint);
    }
    printf( "\n");
    for (i = 0; i < 2; i++)
    {
       if (!fread( &tempushort, 2, 1, anyin)) {
          return;
       }
       printf( "%d: %d, ", i, tempushort);
    }
    printf( "\n");
 }
readwavheader()
void readwavheader (FILE * anyin)
Definition at line 126 of file utils/frame.c.
References channels, chat(), FALSE, iswav, samplefrequency, str, and TRUE.
Referenced by main(), and parseargs().
 {
    unsigned int tempuint, sf;
    unsigned short tempushort, cn;
    char str[9];
    int nowav = FALSE;
    iswav = FALSE;
    if (ftell(anyin) == -1) /* If we cannot seek this file */
    {
       nowav = TRUE;   /* -> Pretend this is no wav-file */
       chat("File not seekable: not checking for WAV-header.\n");
    }
    else
    {
       /* Expect four bytes "RIFF" and four bytes filelength */
       if (!fread(str, 1, 8, anyin)) {           /* 0 */
          return;
       }
       str[4] = '\0';
       if (strcmp(str, "RIFF") != 0) nowav = TRUE;
       /* Expect eight bytes "WAVEfmt " */
       if (!fread(str, 1, 8, anyin)) {           /* 8 */
          return;
       }
       str[8] = '\0';
       if (strcmp(str, "WAVEfmt ") != 0) nowav = TRUE;
       /* Expect length of fmt data, which should be 16 */
       if (!fread(&tempuint, 4, 1, anyin)) {  /* 16 */
          return;
       }
       if (tempuint != 16) nowav = TRUE;
       /* Expect format tag, which should be 1 for pcm */
       if (!fread(&tempushort, 2, 1, anyin)) { /* 20 */
          return;
       }
       if (tempushort != 1)
          nowav = TRUE;
       /* Expect number of channels */
       if (!fread(&cn, 2, 1, anyin)) { /* 20 */
          return;
       }
       if (cn != 1 && cn != 2) nowav = TRUE;
       /* Read samplefrequency */
       if (!fread(&sf, 4, 1, anyin)) {  /* 24 */
          return;
       }
       /* Read bytes per second: Should be samplefreq * channels * 2 */
       if (!fread(&tempuint, 4, 1, anyin)) {         /* 28 */
          return;
       }
       if (tempuint != sf * cn * 2) nowav = TRUE;
       /* read bytes per frame: Should be channels * 2 */
       if (!fread(&tempushort, 2, 1, anyin)) {       /* 32 */
          return;
       }
       if (tempushort != cn * 2) nowav = TRUE;
       /* Read bits per sample: Should be 16 */
       if (!fread(&tempushort, 2, 1, anyin)) {       /* 34 */
          return;
       }
       if (tempushort != 16) nowav = TRUE;
       if (!fread(str, 4, 1, anyin)) {            /* 36 */
          return;
       }
       str[4] = '\0';
       if (strcmp(str, "data") != 0) nowav = TRUE;
       if (!fread(&tempuint, 4, 1, anyin)) {   /* 40 */
          return;
       }
       if (nowav)
       {
          fseek(anyin, 0, SEEK_SET);   /* Back to beginning of file */
          chat("File has no WAV header.\n");
       }
       else
       {
          samplefrequency = sf;
          channels = cn;
          chat("Read WAV header: %d channels, samplefrequency %d.\n",
           channels, samplefrequency);
          iswav = TRUE;
       }
    }
    return;
 }
say()
int say (const char * format, ...)
Definition at line 1026 of file utils/frame.c.
References result.
Referenced by parsedoublearg(), parseintarg(), parsevolarg(), and parsevolume().
 {
     va_list ap;
     int result;
     va_start( ap, format);
     result = vfprintf( stdout, format, ap);
     va_end( ap);
     return result;
 }
startstopwatch()
void startstopwatch (void)
Definition at line 307 of file utils/frame.c.
References NULL, statistics(), and stopwatch.
Referenced by main().
 {
    stopwatch = time(NULL);       /* Remember time 'now' */
    atexit(statistics);           /* Call function statistics() at exit. */
    return;
 }
workloop()
int workloop (FILE * theinfile, FILE * theoutfile, int(*)(short *buffer, int length) work)
Definition at line 943 of file utils/frame.c.
References BUFFSIZE, FALSE, fatalperror(), malloc(), NULL, and TRUE.
 {
   short *buffer;
   int length, nowlength;
   length = BUFFSIZE;
   if ((buffer = malloc( sizeof(short) * length)) == NULL)
     fatalperror ("");
   while (TRUE)
     {
       nowlength = fread(buffer, sizeof(short), length, theinfile);
       if (ferror( theinfile) != 0)
    fatalperror("Error reading input file");
       if (nowlength == 0)   /* Reached end of input file */
    break;
       /* Call the routine that does the work */
       if (!work (buffer, nowlength))         /* On error, stop. */
    return FALSE;
       if (!fwrite(buffer, sizeof(short), nowlength, theoutfile)) {
          return FALSE;
       }
       if (ferror( theoutfile) != 0)
    fatalperror("Error writing to output file");
     }
   return TRUE;      /* Input file done with, no errors. */
 }
Variable Documentation
channels
unsigned short channels
Definition at line 30 of file utils/frame.c.
Referenced by makewavheader(), parseargs(), and readwavheader().
in
FILE* in
Definition at line 33 of file utils/frame.c.
Referenced by __rtp_recvfrom(), __stub__ast_aes_set_decrypt_key(), ast_aes_decrypt(), ast_aes_encrypt(), AST_TEST_DEFINE(), do_forward(), fast_originate(), get_comma(), json_escape(), osp_choose_timelimit(), parseargs(), resampler_basic_direct_single(), resampler_basic_interpolate_single(), and wait_for_answer().
infilename
char* infilename
Definition at line 34 of file utils/frame.c.
Referenced by parseargs().
iswav
int iswav
Definition at line 32 of file utils/frame.c.
Referenced by main(), and readwavheader().
out
FILE * out
Definition at line 33 of file utils/frame.c.
Referenced by __ast_frdup(), __ast_frisolate(), __queues_show(), __stub__ast_aes_set_decrypt_key(), _macro_exec(), acf_escape(), action_agents(), agent_handle_show_specific(), agent_show_requested(), ast_aes_decrypt(), ast_aes_encrypt(), ast_escape_quoted(), ast_escape_semicolons(), ast_fax_caps_to_str(), ast_http_create_response(), ast_manager_build_bridge_state_string_prefix(), ast_manager_build_channel_state_string_prefix(), AST_TEST_DEFINE(), ast_translate(), ast_uri_encode(), ast_var_channels_table(), attended_transfer_to_json(), auth_http_callback(), blind_transfer_to_json(), custom_log(), dahdi_create_channel_range(), dahdi_digit_begin(), dahdi_digit_end(), dial_exec_full(), function_realtime_read(), function_realtime_readdestroy(), generic_http_callback(), get_in_brackets(), handle_show_translation_table(), httpstatus_callback(), is_zero_or_null(), keypad_cfg_read(), main(), makewavheader(), manager_build_parked_call_string(), multi_user_event_to_json(), my_conf_add(), osp_choose_timelimit(), parse_sip_options(), parseargs(), print_queue(), print_uptimestr(), process_token(), record_exec(), resampler_basic_direct_single(), resampler_basic_interpolate_single(), sendmail(), sendurl_exec(), sip_rtp_read(), transmit_notify_with_mwi(), try_calling(), and vm_execmain().
outfilename
char * outfilename
Definition at line 34 of file utils/frame.c.
Referenced by main(), and parseargs().
samplefrequency
int samplefrequency
Definition at line 28 of file utils/frame.c.
Referenced by makewavheader(), parseargs(), parsefreq(), parsetime(), and readwavheader().
samplewidth
unsigned short samplewidth
Definition at line 29 of file utils/frame.c.
Referenced by getremainingfilelength(), and parseargs().
usage
char* usage
Definition at line 37 of file utils/frame.c.
Referenced by main(), parseargs(), pbx_builtin_execiftime(), and vm_allocate_dh().
verboselevel
int verboselevel
Definition at line 35 of file utils/frame.c.
Referenced by chat(), inform(), and parseargs().
version
char* version
Definition at line 502 of file main/security_events.c.
Referenced by parseargs().
wavout
int wavout
Definition at line 31 of file utils/frame.c.
Referenced by main(), myexit(), and parseargs().