Asterisk - The Open Source Telephony Project: app_exec.c File Reference
app_exec.c File Reference
Dial plan applications
Exec application.
#include "asterisk.h"
#include "asterisk/file.h"
#include "asterisk/channel.h"
#include "asterisk/pbx.h"
#include "asterisk/module.h"
#include "asterisk/app.h"
Macros
#define MAXRESULT 1024
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int exec_exec (struct ast_channel *chan, const char *data)
static int execif_exec (struct ast_channel *chan, const char *data)
static int load_module (void)
static int tryexec_exec (struct ast_channel *chan, const char *data)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Executes dialplan applications" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, }
static const char app_exec [] = "Exec"
static const char app_execif [] = "ExecIf"
static const char app_tryexec [] = "TryExec"
static const struct ast_module_info * ast_module_info = &__mod_info
Detailed Description
Exec application.
Author
Tilghman Lesher app_e.nosp@m.xec_.nosp@m._v002.nosp@m.@the.nosp@m.-tilg.nosp@m.hman.nosp@m..com
Philipp Dunkel phili.nosp@m.pp.d.nosp@m.unkel.nosp@m.@ebo.nosp@m.x.at
Definition in file app_exec.c.
Macro Definition Documentation
MAXRESULT
#define MAXRESULT 1024
Definition at line 115 of file app_exec.c.
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 300 of file app_exec.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 300 of file app_exec.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 300 of file app_exec.c.
exec_exec()
static int exec_exec (struct ast_channel * chan, const char * data) static
Definition at line 133 of file app_exec.c.
References app, args, ast_free, ast_log, ast_str_buffer(), ast_str_create, ast_str_substitute_variables(), ast_strdupa, ast_strlen_zero, LOG_WARNING, NULL, pbx_exec(), pbx_findapp(), and strsep().
Referenced by load_module().
 {
    int res = 0;
    char *s, *appname, *endargs;
    struct ast_app *app;
    struct ast_str *args = NULL;
    if (ast_strlen_zero(data))
       return 0;
    s = ast_strdupa(data);
    appname = strsep(&s, "(");
    if (s) {
       endargs = strrchr(s, ')');
       if (endargs)
          *endargs = '\0';
       if ((args = ast_str_create(16))) {
          ast_str_substitute_variables(&args, 0, chan, s);
       }
    }
    if (appname) {
       app = pbx_findapp(appname);
       if (app) {
          res = pbx_exec(chan, app, args ? ast_str_buffer(args) : NULL);
       } else {
          ast_log(LOG_WARNING, "Could not find application (%s)\n", appname);
          res = -1;
       }
    }
    ast_free(args);
    return res;
 }
execif_exec()
static int execif_exec (struct ast_channel * chan, const char * data) static
Definition at line 202 of file app_exec.c.
References app, AST_APP_ARG, AST_DECLARE_APP_ARGS, ast_log, AST_NONSTANDARD_RAW_ARGS, AST_STANDARD_APP_ARGS, ast_strdupa, ast_strlen_zero, end, LOG_ERROR, LOG_WARNING, NULL, parse(), pbx_checkcondition(), pbx_exec(), pbx_findapp(), and S_OR.
Referenced by load_module().
 {
    int res = 0;
    char *truedata = NULL, *falsedata = NULL, *end, *firstcomma, *firstquestion;
    struct ast_app *app = NULL;
    AST_DECLARE_APP_ARGS(expr,
       AST_APP_ARG(expr);
       AST_APP_ARG(remainder);
    );
    AST_DECLARE_APP_ARGS(apps,
       AST_APP_ARG(t);
       AST_APP_ARG(f);
    );
    char *parse = ast_strdupa(data);
    firstcomma = strchr(parse, ',');
    firstquestion = strchr(parse, '?');
    if ((firstcomma != NULL && firstquestion != NULL && firstcomma < firstquestion) || (firstquestion == NULL)) {
       /* Deprecated syntax */
       AST_DECLARE_APP_ARGS(depr,
          AST_APP_ARG(expr);
          AST_APP_ARG(appname);
          AST_APP_ARG(appargs);
       );
       AST_STANDARD_APP_ARGS(depr, parse);
       ast_log(LOG_WARNING, "Deprecated syntax found.  Please upgrade to using ExecIf(<expr>?%s(%s))\n", depr.appname, depr.appargs);
       /* Make the two syntaxes look the same */
       expr.expr = depr.expr;
       apps.t = depr.appname;
       apps.f = NULL;
       truedata = depr.appargs;
    } else {
       /* Preferred syntax */
       AST_NONSTANDARD_RAW_ARGS(expr, parse, '?');
       if (ast_strlen_zero(expr.remainder)) {
          ast_log(LOG_ERROR, "Usage: ExecIf(<expr>?<appiftrue>(<args>)[:<appiffalse>(<args)])\n");
          return -1;
       }
       AST_NONSTANDARD_RAW_ARGS(apps, expr.remainder, ':');
       if (apps.t && (truedata = strchr(apps.t, '('))) {
          *truedata++ = '\0';
          if ((end = strrchr(truedata, ')'))) {
             *end = '\0';
          }
       }
       if (apps.f && (falsedata = strchr(apps.f, '('))) {
          *falsedata++ = '\0';
          if ((end = strrchr(falsedata, ')'))) {
             *end = '\0';
          }
       }
    }
    if (pbx_checkcondition(expr.expr)) {
       if (!ast_strlen_zero(apps.t) && (app = pbx_findapp(apps.t))) {
          res = pbx_exec(chan, app, S_OR(truedata, ""));
       } else {
          ast_log(LOG_WARNING, "Could not find application! (%s)\n", apps.t);
          res = -1;
       }
    } else if (!ast_strlen_zero(apps.f)) {
       if ((app = pbx_findapp(apps.f))) {
          res = pbx_exec(chan, app, S_OR(falsedata, ""));
       } else {
          ast_log(LOG_WARNING, "Could not find application! (%s)\n", apps.f);
          res = -1;
       }
    }
    return res;
 }
load_module()
static int load_module (void) static
Definition at line 292 of file app_exec.c.
References app_exec, app_execif, app_tryexec, ast_register_application_xml, exec_exec(), execif_exec(), and tryexec_exec().
 {
    int res = ast_register_application_xml(app_exec, exec_exec);
    res |= ast_register_application_xml(app_tryexec, tryexec_exec);
    res |= ast_register_application_xml(app_execif, execif_exec);
    return res;
 }
tryexec_exec()
static int tryexec_exec (struct ast_channel * chan, const char * data) static
Definition at line 167 of file app_exec.c.
References app, args, ast_free, ast_log, ast_str_buffer(), ast_str_create, ast_str_substitute_variables(), ast_strdupa, ast_strlen_zero, LOG_WARNING, NULL, pbx_builtin_setvar_helper(), pbx_exec(), pbx_findapp(), and strsep().
Referenced by load_module().
 {
    int res = 0;
    char *s, *appname, *endargs;
    struct ast_app *app;
    struct ast_str *args = NULL;
    if (ast_strlen_zero(data))
       return 0;
    s = ast_strdupa(data);
    appname = strsep(&s, "(");
    if (s) {
       endargs = strrchr(s, ')');
       if (endargs)
          *endargs = '\0';
       if ((args = ast_str_create(16))) {
          ast_str_substitute_variables(&args, 0, chan, s);
       }
    }
    if (appname) {
       app = pbx_findapp(appname);
       if (app) {
          res = pbx_exec(chan, app, args ? ast_str_buffer(args) : NULL);
          pbx_builtin_setvar_helper(chan, "TRYSTATUS", res ? "FAILED" : "SUCCESS");
       } else {
          ast_log(LOG_WARNING, "Could not find application (%s)\n", appname);
          pbx_builtin_setvar_helper(chan, "TRYSTATUS", "NOAPP");
       }
    }
    ast_free(args);
    return 0;
 }
unload_module()
static int unload_module (void) static
Definition at line 281 of file app_exec.c.
References app_exec, app_execif, app_tryexec, and ast_unregister_application().
 {
    int res;
    res = ast_unregister_application(app_exec);
    res |= ast_unregister_application(app_tryexec);
    res |= ast_unregister_application(app_execif);
    return res;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Executes dialplan applications" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, } static
Definition at line 300 of file app_exec.c.
app_exec
const char app_exec[] = "Exec" static
Note
The key difference between these two apps is exit status. In a nutshell, Exec tries to be transparent as possible, behaving in exactly the same way as if the application it calls was directly invoked from the dialplan.
TryExec, on the other hand, provides a way to execute applications and catch any possible fatal error without actually fatally affecting the dialplan.
Definition at line 129 of file app_exec.c.
Referenced by load_module(), and unload_module().
app_execif
const char app_execif[] = "ExecIf" static
Definition at line 131 of file app_exec.c.
Referenced by load_module(), and unload_module().
app_tryexec
const char app_tryexec[] = "TryExec" static
Definition at line 130 of file app_exec.c.
Referenced by load_module(), and unload_module().
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 300 of file app_exec.c.