Asterisk - The Open Source Telephony Project: cdr_manager.c File Reference
cdr_manager.c File Reference
Module: CDR Drivers
Asterisk Call Manager CDR records.
#include "asterisk.h"
#include <time.h>
#include "asterisk/channel.h"
#include "asterisk/cdr.h"
#include "asterisk/module.h"
#include "asterisk/utils.h"
#include "asterisk/manager.h"
#include "asterisk/config.h"
#include "asterisk/pbx.h"
Macros
#define CONF_FILE "cdr_manager.conf"
#define CUSTOM_FIELDS_BUF_SIZE 1024
#define DATE_FORMAT "%Y-%m-%d %T"
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int load_config (int reload)
static int load_module (void)
static int manager_log (struct ast_cdr *cdr)
static int reload (void)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Asterisk Manager Interface CDR Backend" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .reload = reload, .load_pri = AST_MODPRI_CDR_DRIVER, .requires = "cdr", }
static const struct ast_module_info * ast_module_info = &__mod_info
static struct ast_str * customfields
static ast_rwlock_t customfields_lock = { PTHREAD_RWLOCK_INITIALIZER , NULL, {1, 0} }
static int enablecdr = 0
static const char name [] = "cdr_manager"
Detailed Description
Asterisk Call Manager CDR records.
See also
CDR - Call Data Records and billing
AMI - The Manager Interface
AMI configuration
Definition in file cdr_manager.c.
Macro Definition Documentation
CONF_FILE
#define CONF_FILE "cdr_manager.conf"
Definition at line 180 of file cdr_manager.c.
Referenced by load_config().
CUSTOM_FIELDS_BUF_SIZE
#define CUSTOM_FIELDS_BUF_SIZE 1024
Definition at line 181 of file cdr_manager.c.
Referenced by load_config(), and manager_log().
DATE_FORMAT
#define DATE_FORMAT "%Y-%m-%d %T"
Definition at line 179 of file cdr_manager.c.
Referenced by manager_log().
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 375 of file cdr_manager.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 375 of file cdr_manager.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 375 of file cdr_manager.c.
load_config()
static int load_config (int reload) static
Definition at line 192 of file cdr_manager.c.
References ast_category_browse(), ast_cdr_backend_suspend(), ast_cdr_backend_unsuspend(), ast_config_destroy(), ast_config_load, ast_free, ast_log, ast_rwlock_unlock, ast_rwlock_wrlock, ast_str_append(), ast_str_create, ast_str_size(), ast_str_strlen(), ast_strlen_zero, ast_true(), ast_variable_browse(), CONF_FILE, CONFIG_FLAG_FILEUNCHANGED, CONFIG_STATUS_FILEINVALID, CONFIG_STATUS_FILEUNCHANGED, CUSTOM_FIELDS_BUF_SIZE, customfields_lock, enablecdr, LOG_ERROR, LOG_NOTICE, LOG_WARNING, ast_variable::name, name, ast_variable::next, NULL, and ast_variable::value.
Referenced by load_module(), and reload().
 {
    char *cat = NULL;
    struct ast_config *cfg;
    struct ast_variable *v;
    struct ast_flags config_flags = { reload ? CONFIG_FLAG_FILEUNCHANGED : 0 };
    int newenablecdr = 0;
    cfg = ast_config_load(CONF_FILE, config_flags);
    if (cfg == CONFIG_STATUS_FILEUNCHANGED) {
       return 0;
    }
    if (cfg == CONFIG_STATUS_FILEINVALID) {
       ast_log(LOG_ERROR, "Config file '%s' could not be parsed\n", CONF_FILE);
       return -1;
    }
    if (!cfg) {
       /* Standard configuration */
       ast_log(LOG_WARNING, "Failed to load configuration file. Module not activated.\n");
       if (enablecdr) {
          ast_cdr_backend_suspend(name);
       }
       enablecdr = 0;
       return -1;
    }
    if (reload) {
       ast_rwlock_wrlock(&customfields_lock);
    }
    if (reload && customfields) {
       ast_free(customfields);
       customfields = NULL;
    }
    while ( (cat = ast_category_browse(cfg, cat)) ) {
       if (!strcasecmp(cat, "general")) {
          v = ast_variable_browse(cfg, cat);
          while (v) {
             if (!strcasecmp(v->name, "enabled"))
                newenablecdr = ast_true(v->value);
             v = v->next;
          }
       } else if (!strcasecmp(cat, "mappings")) {
          customfields = ast_str_create(CUSTOM_FIELDS_BUF_SIZE);
          v = ast_variable_browse(cfg, cat);
          while (v) {
             if (customfields && !ast_strlen_zero(v->name) && !ast_strlen_zero(v->value)) {
                if ((ast_str_strlen(customfields) + strlen(v->value) + strlen(v->name) + 14) < ast_str_size(customfields)) {
                   ast_str_append(&customfields, -1, "%s: ${CDR(%s)}\r\n", v->value, v->name);
                   ast_log(LOG_NOTICE, "Added mapping %s: ${CDR(%s)}\n", v->value, v->name);
                } else {
                   ast_log(LOG_WARNING, "No more buffer space to add other custom fields\n");
                   break;
                }
             }
             v = v->next;
          }
       }
    }
    if (reload) {
       ast_rwlock_unlock(&customfields_lock);
    }
    ast_config_destroy(cfg);
    if (!newenablecdr) {
       ast_cdr_backend_suspend(name);
    } else if (newenablecdr) {
       ast_cdr_backend_unsuspend(name);
    }
    enablecdr = newenablecdr;
    return 0;
 }
load_module()
static int load_module (void) static
Definition at line 349 of file cdr_manager.c.
References ast_cdr_register(), ast_cdr_unregister(), AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, load_config(), manager_log(), and name.
Referenced by reload().
 {
    if (ast_cdr_register(name, "Asterisk Manager Interface CDR Backend", manager_log)) {
       return AST_MODULE_LOAD_DECLINE;
    }
    if (load_config(0)) {
       ast_cdr_unregister(name);
       return AST_MODULE_LOAD_DECLINE;
    }
    return AST_MODULE_LOAD_SUCCESS;
 }
manager_log()
static int manager_log (struct ast_cdr * cdr) static
Definition at line 273 of file cdr_manager.c.
References ast_cdr::accountcode, ast_cdr::amaflags, ast_cdr::answer, ast_cdr_disp2str(), ast_cdr_dup(), ast_channel_amaflags2string(), ast_channel_cdr_set(), ast_channel_unref, ast_dummy_channel_alloc, ast_localtime(), ast_log, ast_rwlock_rdlock, ast_rwlock_unlock, ast_str_buffer(), ast_str_strlen(), ast_strftime(), ast_cdr::billsec, buf, ast_cdr::channel, ast_cdr::clid, CUSTOM_FIELDS_BUF_SIZE, customfields_lock, DATE_FORMAT, ast_cdr::dcontext, ast_cdr::disposition, ast_cdr::dst, ast_cdr::dstchannel, dummy(), ast_cdr::duration, enablecdr, ast_cdr::end, EVENT_FLAG_CDR, ast_cdr::lastapp, ast_cdr::lastdata, LOG_ERROR, manager_event, NULL, pbx_substitute_variables_helper(), ast_cdr::src, ast_cdr::start, ast_cdr::uniqueid, and ast_cdr::userfield.
Referenced by load_module().
 {
    struct ast_tm timeresult;
    char strStartTime[80] = "";
    char strAnswerTime[80] = "";
    char strEndTime[80] = "";
    char buf[CUSTOM_FIELDS_BUF_SIZE];
    if (!enablecdr)
       return 0;
    ast_localtime(&cdr->start, &timeresult, NULL);
    ast_strftime(strStartTime, sizeof(strStartTime), DATE_FORMAT, &timeresult);
    if (cdr->answer.tv_sec) {
       ast_localtime(&cdr->answer, &timeresult, NULL);
       ast_strftime(strAnswerTime, sizeof(strAnswerTime), DATE_FORMAT, &timeresult);
    }
    ast_localtime(&cdr->end, &timeresult, NULL);
    ast_strftime(strEndTime, sizeof(strEndTime), DATE_FORMAT, &timeresult);
    buf[0] = '\0';
    ast_rwlock_rdlock(&customfields_lock);
    if (customfields && ast_str_strlen(customfields)) {
       struct ast_channel *dummy = ast_dummy_channel_alloc();
       if (!dummy) {
          ast_log(LOG_ERROR, "Unable to allocate channel for variable substitution.\n");
          return 0;
       }
       ast_channel_cdr_set(dummy, ast_cdr_dup(cdr));
       pbx_substitute_variables_helper(dummy, ast_str_buffer(customfields), buf, sizeof(buf) - 1);
       ast_channel_unref(dummy);
    }
    ast_rwlock_unlock(&customfields_lock);
    manager_event(EVENT_FLAG_CDR, "Cdr",
        "AccountCode: %s\r\n"
        "Source: %s\r\n"
        "Destination: %s\r\n"
        "DestinationContext: %s\r\n"
        "CallerID: %s\r\n"
        "Channel: %s\r\n"
        "DestinationChannel: %s\r\n"
        "LastApplication: %s\r\n"
        "LastData: %s\r\n"
        "StartTime: %s\r\n"
        "AnswerTime: %s\r\n"
        "EndTime: %s\r\n"
        "Duration: %ld\r\n"
        "BillableSeconds: %ld\r\n"
        "Disposition: %s\r\n"
        "AMAFlags: %s\r\n"
        "UniqueID: %s\r\n"
        "UserField: %s\r\n"
        "%s",
        cdr->accountcode, cdr->src, cdr->dst, cdr->dcontext, cdr->clid, cdr->channel,
        cdr->dstchannel, cdr->lastapp, cdr->lastdata, strStartTime, strAnswerTime, strEndTime,
        cdr->duration, cdr->billsec, ast_cdr_disp2str(cdr->disposition),
        ast_channel_amaflags2string(cdr->amaflags), cdr->uniqueid, cdr->userfield,buf);
    return 0;
 }
reload()
static int reload (void) static
Definition at line 363 of file cdr_manager.c.
References AST_MODFLAG_LOAD_ORDER, AST_MODPRI_CDR_DRIVER, AST_MODULE_INFO(), AST_MODULE_SUPPORT_CORE, ASTERISK_GPL_KEY, load_config(), load_module(), and unload_module().
 {
    return load_config(1);
 }
unload_module()
static int unload_module (void) static
Definition at line 337 of file cdr_manager.c.
References ast_cdr_unregister(), ast_free, and name.
Referenced by reload().
 {
    if (ast_cdr_unregister(name)) {
       return -1;
    }
    if (customfields)
       ast_free(customfields);
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Asterisk Manager Interface CDR Backend" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .reload = reload, .load_pri = AST_MODPRI_CDR_DRIVER, .requires = "cdr", } static
Definition at line 375 of file cdr_manager.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 375 of file cdr_manager.c.
customfields
struct ast_str* customfields static
Definition at line 187 of file cdr_manager.c.
customfields_lock
ast_rwlock_t customfields_lock = { PTHREAD_RWLOCK_INITIALIZER , NULL, {1, 0} } static
Definition at line 188 of file cdr_manager.c.
Referenced by load_config(), and manager_log().
enablecdr
int enablecdr = 0 static
Definition at line 185 of file cdr_manager.c.
Referenced by load_config(), and manager_log().
name
const char name[] = "cdr_manager" static
Definition at line 183 of file cdr_manager.c.
Referenced by load_config(), load_module(), and unload_module().