Asterisk - The Open Source Telephony Project: res_pjsip_path.c File Reference
res_pjsip_path.c File Reference
#include "asterisk.h"
#include <pjsip.h>
#include <pjsip_ua.h>
#include "asterisk/res_pjsip.h"
#include "asterisk/res_pjsip_session.h"
#include "asterisk/module.h"
#include "asterisk/strings.h"
Functions
static void __reg_module (void)
static void __unreg_module (void)
static int add_supported (pjsip_tx_data *tdata)
struct ast_module * AST_MODULE_SELF_SYM (void)
static struct ast_sip_aor * find_aor (struct ast_sip_endpoint *endpoint, pjsip_uri *uri)
static int load_module (void)
static int path_get_string (pj_pool_t *pool, struct ast_sip_contact *contact, pj_str_t *path_str)
Get the path string associated with this contact and tdata.
static void path_outgoing_request (struct ast_sip_endpoint *endpoint, struct ast_sip_contact *contact, pjsip_tx_data *tdata)
static void path_outgoing_response (struct ast_sip_endpoint *endpoint, struct ast_sip_contact *contact, pjsip_tx_data *tdata)
static void path_session_outgoing_request (struct ast_sip_session *session, pjsip_tx_data *tdata)
static void path_session_outgoing_response (struct ast_sip_session *session, pjsip_tx_data *tdata)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "PJSIP Path Header Support" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_APP_DEPEND, .requires = "res_pjsip,res_pjsip_session", }
static const struct ast_module_info * ast_module_info = &__mod_info
static const pj_str_t PATH_NAME = { "Path", 4 }
static struct ast_sip_session_supplement path_session_supplement
static struct ast_sip_supplement path_supplement
static pj_str_t PATH_SUPPORTED_NAME = { "path", 4 }
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 273 of file res_pjsip_path.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 273 of file res_pjsip_path.c.
add_supported()
static int add_supported (pjsip_tx_data * tdata) static
Definition at line 123 of file res_pjsip_path.c.
References NULL, and PATH_SUPPORTED_NAME.
Referenced by path_outgoing_request(), and path_outgoing_response().
 {
    pjsip_supported_hdr *hdr;
    int i;
    hdr = pjsip_msg_find_hdr(tdata->msg, PJSIP_H_SUPPORTED, NULL);
    if (!hdr) {
       /* insert a new Supported header */
       hdr = pjsip_supported_hdr_create(tdata->pool);
       if (!hdr) {
          return -1;
       }
       pjsip_msg_add_hdr(tdata->msg, (pjsip_hdr *)hdr);
    }
    /* Don't add the value if it's already there */
    for (i = 0; i < hdr->count; ++i) {
       if (pj_stricmp(&hdr->values[i], &PATH_SUPPORTED_NAME) == 0) {
          return 0;
       }
    }
    if (hdr->count >= PJSIP_GENERIC_ARRAY_MAX_COUNT) {
       return -1;
    }
    /* add on to the existing Supported header */
    pj_strassign(&hdr->values[hdr->count++], &PATH_SUPPORTED_NAME);
    return 0;
 }
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 273 of file res_pjsip_path.c.
find_aor()
static struct ast_sip_aor* find_aor (struct ast_sip_endpoint * endpoint, pjsip_uri * uri) static
Definition at line 39 of file res_pjsip_path.c.
References ao2_cleanup, ast_sip_endpoint::aors, ast_alloca, ast_copy_pj_str(), ast_free, ast_sip_get_sorcery(), ast_sip_location_retrieve_aor(), AST_SIP_USER_OPTIONS_TRUNCATE_CHECK, ast_sorcery_retrieve_by_id(), ast_str_append(), ast_str_buffer(), ast_str_create, ast_str_set(), ast_strdupa, ast_strip(), ast_strlen_zero, ast_sip_domain_alias::domain, NULL, and strsep().
Referenced by path_outgoing_request(), and path_outgoing_response().
 {
    char *configured_aors, *aor_name;
    pjsip_sip_uri *sip_uri;
    char *domain_name;
    char *username;
    struct ast_str *id = NULL;
    if (ast_strlen_zero(endpoint->aors)) {
       return NULL;
    }
    sip_uri = pjsip_uri_get_uri(uri);
    domain_name = ast_alloca(sip_uri->host.slen + 1);
    ast_copy_pj_str(domain_name, &sip_uri->host, sip_uri->host.slen + 1);
    username = ast_alloca(sip_uri->user.slen + 1);
    ast_copy_pj_str(username, &sip_uri->user, sip_uri->user.slen + 1);
    /*
     * We may want to match without any user options getting
     * in the way.
     */
    AST_SIP_USER_OPTIONS_TRUNCATE_CHECK(username);
    configured_aors = ast_strdupa(endpoint->aors);
    /* Iterate the configured AORs to see if the user or the user+domain match */
    while ((aor_name = ast_strip(strsep(&configured_aors, ",")))) {
       struct ast_sip_domain_alias *alias = NULL;
       if (ast_strlen_zero(aor_name)) {
          continue;
       }
       if (!strcmp(username, aor_name)) {
          break;
       }
       if (!id && !(id = ast_str_create(strlen(username) + sip_uri->host.slen + 2))) {
          aor_name = NULL;
          break;
       }
       ast_str_set(&id, 0, "%s@", username);
       if ((alias = ast_sorcery_retrieve_by_id(ast_sip_get_sorcery(), "domain_alias", domain_name))) {
          ast_str_append(&id, 0, "%s", alias->domain);
          ao2_cleanup(alias);
       } else {
          ast_str_append(&id, 0, "%s", domain_name);
       }
       if (!strcmp(aor_name, ast_str_buffer(id))) {
          break;
       }
    }
    ast_free(id);
    if (ast_strlen_zero(aor_name)) {
       return NULL;
    }
    return ast_sip_location_retrieve_aor(aor_name);
 }
load_module()
static int load_module (void) static
Definition at line 252 of file res_pjsip_path.c.
References AST_MODULE_LOAD_SUCCESS, ast_sip_register_supplement(), and ast_sip_session_register_supplement.
Referenced by unload_module().
 {
    ast_sip_register_supplement(&path_supplement);
    ast_sip_session_register_supplement(&path_session_supplement);
    return AST_MODULE_LOAD_SUCCESS;
 }
path_get_string()
static int path_get_string (pj_pool_t * pool, struct ast_sip_contact * contact, pj_str_t * path_str) static
Get the path string associated with this contact and tdata.
Parameters
endpoint The endpoint from which to pull associated path data
contact_uri The URI identifying the associated contact
path_str The place to store the retrieved path information
Return values
zero on success
non-zero on failure or no available path information
Definition at line 113 of file res_pjsip_path.c.
References ast_strlen_zero, and ast_sip_contact::path.
Referenced by path_outgoing_response().
 {
    if (!contact || ast_strlen_zero(contact->path)) {
       return -1;
    }
    *path_str = pj_strdup3(pool, contact->path);
    return 0;
 }
path_outgoing_request()
static void path_outgoing_request (struct ast_sip_endpoint * endpoint, struct ast_sip_contact * contact, pjsip_tx_data * tdata) static
Definition at line 165 of file res_pjsip_path.c.
References add_supported(), ao2_cleanup, ast_sip_set_outbound_proxy(), ast_strlen_zero, find_aor(), NULL, ast_sip_contact::path, and RAII_VAR.
Referenced by path_session_outgoing_request().
 {
    RAII_VAR(struct ast_sip_aor *, aor, NULL, ao2_cleanup);
    if (!endpoint) {
       return;
    }
    aor = find_aor(endpoint, tdata->msg->line.req.uri);
    if (!aor || !aor->support_path) {
       return;
    }
    if (add_supported(tdata)) {
       return;
    }
    if (contact && !ast_strlen_zero(contact->path)) {
       ast_sip_set_outbound_proxy(tdata, contact->path);
    }
 }
path_outgoing_response()
static void path_outgoing_response (struct ast_sip_endpoint * endpoint, struct ast_sip_contact * contact, pjsip_tx_data * tdata) static
Definition at line 200 of file res_pjsip_path.c.
References add_supported(), ao2_cleanup, find_aor(), NULL, path_get_string(), PATH_NAME, and RAII_VAR.
Referenced by path_session_outgoing_response().
 {
    struct pjsip_status_line status = tdata->msg->line.status;
    pj_str_t path_dup;
    pjsip_generic_string_hdr *path_hdr;
    pjsip_contact_hdr *contact_hdr;
    RAII_VAR(struct ast_sip_aor *, aor, NULL, ao2_cleanup);
    pjsip_cseq_hdr *cseq = pjsip_msg_find_hdr(tdata->msg, PJSIP_H_CSEQ, NULL);
    const pj_str_t REGISTER_METHOD = {"REGISTER", 8};
    if (!endpoint
       || !pj_stristr(&REGISTER_METHOD, &cseq->method.name)
       || !PJSIP_IS_STATUS_IN_CLASS(status.code, 200)) {
       return;
    }
    contact_hdr = pjsip_msg_find_hdr(tdata->msg, PJSIP_H_CONTACT, NULL);
    if (!contact_hdr) {
       return;
    }
    aor = find_aor(endpoint, contact_hdr->uri);
    if (!aor || !aor->support_path || add_supported(tdata)
       || path_get_string(tdata->pool, contact, &path_dup)) {
       return;
    }
    path_hdr = pjsip_generic_string_hdr_create(tdata->pool, &PATH_NAME, &path_dup);
    if (!path_hdr) {
       return;
    }
    pjsip_msg_add_hdr(tdata->msg, (pjsip_hdr*)path_hdr);
 }
path_session_outgoing_request()
static void path_session_outgoing_request (struct ast_sip_session * session, pjsip_tx_data * tdata) static
Definition at line 187 of file res_pjsip_path.c.
References ast_sip_session::contact, ast_sip_session::endpoint, and path_outgoing_request().
 {
    path_outgoing_request(session->endpoint, session->contact, tdata);
 }
path_session_outgoing_response()
static void path_session_outgoing_response (struct ast_sip_session * session, pjsip_tx_data * tdata) static
Definition at line 235 of file res_pjsip_path.c.
References ast_sip_session::contact, ast_sip_session::endpoint, and path_outgoing_response().
 {
    path_outgoing_response(session->endpoint, session->contact, tdata);
 }
unload_module()
static int unload_module (void) static
Definition at line 260 of file res_pjsip_path.c.
References AST_MODFLAG_LOAD_ORDER, AST_MODPRI_APP_DEPEND, AST_MODULE_INFO(), AST_MODULE_SUPPORT_CORE, ast_sip_session_unregister_supplement(), ast_sip_unregister_supplement(), ASTERISK_GPL_KEY, and load_module().
 {
    ast_sip_unregister_supplement(&path_supplement);
    ast_sip_session_unregister_supplement(&path_session_supplement);
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "PJSIP Path Header Support" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_APP_DEPEND, .requires = "res_pjsip,res_pjsip_session", } static
Definition at line 273 of file res_pjsip_path.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 273 of file res_pjsip_path.c.
PATH_NAME
const pj_str_t PATH_NAME = { "Path", 4 } static
Definition at line 36 of file res_pjsip_path.c.
Referenced by path_outgoing_response().
path_session_supplement
struct ast_sip_session_supplement path_session_supplement static
Initial value:
= {
   .priority = AST_SIP_SUPPLEMENT_PRIORITY_CHANNEL - 100,
   .outgoing_request = path_session_outgoing_request,
   .outgoing_response = path_session_outgoing_response,
}
Definition at line 246 of file res_pjsip_path.c.
path_supplement
struct ast_sip_supplement path_supplement static
Initial value:
= {
   .priority = AST_SIP_SUPPLEMENT_PRIORITY_CHANNEL - 100,
   .outgoing_request = path_outgoing_request,
   .outgoing_response = path_outgoing_response,
}
Definition at line 240 of file res_pjsip_path.c.
PATH_SUPPORTED_NAME
pj_str_t PATH_SUPPORTED_NAME = { "path", 4 } static
Definition at line 37 of file res_pjsip_path.c.
Referenced by add_supported().