Asterisk - The Open Source Telephony Project: set_format_access Struct Reference
set_format_access Struct Reference
Data Fields
const char * direction
struct ast_format *(* get_format)(struct ast_channel *chan)
struct ast_format *(* get_rawformat)(struct ast_channel *chan)
struct ast_trans_pvt *(* get_trans)(const struct ast_channel *chan)
void(* set_format)(struct ast_channel *chan, struct ast_format *format)
void(* set_rawformat)(struct ast_channel *chan, struct ast_format *format)
void(* set_trans)(struct ast_channel *chan, struct ast_trans_pvt *value)
int setoption
Detailed Description
Definition at line 5647 of file channel.c.
Field Documentation
direction
const char* direction
Definition at line 5648 of file channel.c.
Referenced by set_format().
get_format
struct ast_format*(* get_format) (struct ast_channel *chan)
Definition at line 5651 of file channel.c.
Referenced by set_format().
get_rawformat
struct ast_format*(* get_rawformat) (struct ast_channel *chan)
Definition at line 5653 of file channel.c.
Referenced by set_format().
get_trans
struct ast_trans_pvt*(* get_trans) (const struct ast_channel *chan)
Definition at line 5649 of file channel.c.
Referenced by set_format().
set_format
void(* set_format) (struct ast_channel *chan, struct ast_format *format)
Definition at line 5652 of file channel.c.
Referenced by set_format().
set_rawformat
void(* set_rawformat) (struct ast_channel *chan, struct ast_format *format)
Definition at line 5654 of file channel.c.
Referenced by set_format().
set_trans
void(* set_trans) (struct ast_channel *chan, struct ast_trans_pvt *value)
Definition at line 5650 of file channel.c.
Referenced by set_format().
setoption
int setoption
Definition at line 5655 of file channel.c.
Referenced by set_format().
The documentation for this struct was generated from the following file:
channel.c