Asterisk - The Open Source Telephony Project: features_config.h File Reference
include/asterisk/features_config.h File Reference
#include "asterisk/stringfields.h"
Data Structures
struct ast_applicationmap_item
An applicationmap configuration item.
struct ast_featuremap_config
Configuration for the builtin features.
struct ast_features_general_config
General features configuration items.
struct ast_features_pickup_config
Configuration relating to call pickup.
struct ast_features_xfer_config
Feature configuration relating to transfers.
Macros
#define AST_FEATURE_MAX_LEN 11
Functions
int ast_get_builtin_feature (struct ast_channel *chan, const char *feature, char *buf, size_t len)
Get the DTMF code for a builtin feature.
struct ao2_container * ast_get_chan_applicationmap (struct ast_channel *chan)
Get the applicationmap for a given channel.
struct ast_featuremap_config * ast_get_chan_featuremap_config (struct ast_channel *chan)
Get the featuremap configuration options for a channel.
char * ast_get_chan_features_atxferabort (struct ast_channel *chan)
Get the transfer configuration option atxferabort.
struct ast_features_general_config * ast_get_chan_features_general_config (struct ast_channel *chan)
Get the general configuration options for a channel.
struct ast_features_pickup_config * ast_get_chan_features_pickup_config (struct ast_channel *chan)
Get the pickup configuration options for a channel.
struct ast_features_xfer_config * ast_get_chan_features_xfer_config (struct ast_channel *chan)
Get the transfer configuration options for a channel.
char * ast_get_chan_features_xferfailsound (struct ast_channel *chan)
Get the transfer configuration option xferfailsound.
int ast_get_feature (struct ast_channel *chan, const char *feature, char *buf, size_t len)
Get the DTMF code for a call feature.
Macro Definition Documentation
AST_FEATURE_MAX_LEN
#define AST_FEATURE_MAX_LEN 11
Definition at line 231 of file include/asterisk/features_config.h.
Referenced by action_atxfer(), attended_transfer_exec(), bridge_agent_hold_push(), builtin_features_helper(), detect_disconnect(), handle_incoming_request(), handle_request_info(), and wait_for_answer().
Function Documentation
ast_get_builtin_feature()
int ast_get_builtin_feature (struct ast_channel * chan, const char * feature, char * buf, size_t len)
Get the DTMF code for a builtin feature.
Note
The channel should be locked before calling this function
If no channel is provided, then the global setting for the option is returned.
Parameters
chan The channel to get the option from
feature The short name of the feature (as it appears in features.conf)
[out] buf The buffer to write the DTMF value into
size The size of the buffer in bytes
Return values
0 Success
non-zero Unrecognized builtin feature name
Definition at line 1233 of file features_config.c.
References ao2_cleanup, ao2_global_obj_ref, featuremap_get(), get_feature_ds(), globals, NULL, and RAII_VAR.
Referenced by action_atxfer(), ast_get_feature(), attended_transfer_exec(), builtin_feature_get_exten(), detect_disconnect(), and internal_featuremap_read().
 {
    RAII_VAR(struct features_config *, cfg, NULL, ao2_cleanup);
    if (chan) {
       cfg = get_feature_ds(chan);
    } else {
       cfg = ao2_global_obj_ref(globals);
    }
    if (!cfg) {
       return -1;
    }
    return featuremap_get(cfg->featuremap, feature, buf, len);
 }
ast_get_chan_applicationmap()
struct ao2_container* ast_get_chan_applicationmap (struct ast_channel * chan)
Get the applicationmap for a given channel.
Note
The channel should be locked before calling this function.
This uses the value of the DYNAMIC_FEATURES channel variable to build a custom applicationmap for this channel. The returned container has applicationmap_items inside.
Parameters
chan The channel for which applicationmap is being retrieved.
Return values
NULL An error occurred or the channel has no dynamic features.
non-NULL A container of applicationmap_items pertaining to the channel.
Definition at line 1325 of file features_config.c.
References add_item(), ao2_callback, ao2_cleanup, ao2_container_count(), ao2_find, ao2_global_obj_ref, ao2_link, ao2_ref, applicationmap_alloc(), ast_assert, ast_channel_name(), ast_log, ast_strdupa, ast_strlen_zero, globals, item, LOG_WARNING, name, NULL, OBJ_KEY, pbx_builtin_getvar_helper(), RAII_VAR, S_OR, and strsep().
Referenced by ast_get_feature(), set_config_flags(), and setup_bridge_features_dynamic().
 {
    RAII_VAR(struct features_config *, cfg, ao2_global_obj_ref(globals), ao2_cleanup);
    struct ao2_container *applicationmap;
    char *group_names;
    char *name;
    if (!cfg) {
       return NULL;
    }
    if (!chan) {
       if (!cfg->applicationmap || ao2_container_count(cfg->applicationmap) == 0) {
          return NULL;
       }
       ao2_ref(cfg->applicationmap, +1);
       return cfg->applicationmap;
    }
    group_names = ast_strdupa(S_OR(pbx_builtin_getvar_helper(chan, "DYNAMIC_FEATURES"), ""));
    if (ast_strlen_zero(group_names)) {
       return NULL;
    }
    applicationmap = applicationmap_alloc(0);
    if (!applicationmap) {
       return NULL;
    }
    /* global config must be initialized */
    ast_assert(cfg->featuregroups != NULL);
    ast_assert(cfg->applicationmap != NULL);
    while ((name = strsep(&group_names, "#"))) {
       RAII_VAR(struct featuregroup *, group, ao2_find(cfg->featuregroups, name, OBJ_KEY), ao2_cleanup);
       if (!group) {
          RAII_VAR(struct ast_applicationmap_item *, item, ao2_find(cfg->applicationmap, name, OBJ_KEY), ao2_cleanup);
          if (item) {
             ao2_link(applicationmap, item);
          } else {
             ast_log(LOG_WARNING, "Unknown DYNAMIC_FEATURES item '%s' on channel %s.\n",
                name, ast_channel_name(chan));
          }
       } else {
          ao2_callback(group->items, 0, add_item, applicationmap);
       }
    }
    if (ao2_container_count(applicationmap) == 0) {
       ao2_cleanup(applicationmap);
       return NULL;
    }
    return applicationmap;
 }
ast_get_chan_featuremap_config()
struct ast_featuremap_config* ast_get_chan_featuremap_config (struct ast_channel * chan)
Get the featuremap configuration options for a channel.
Note
The channel should be locked before calling this function.
The returned value has its reference count incremented.
If no channel is provided, then the global featuremap configuration is returned.
Parameters
chan The channel to get configuration options for
Return values
NULL Failed to get configuration
non-NULL The pickup features configuration
Definition at line 1213 of file features_config.c.
References ao2_cleanup, ao2_global_obj_ref, ao2_ref, ast_assert, get_feature_ds(), globals, NULL, and RAII_VAR.
Referenced by testsuite_notify_feature_success().
 {
    RAII_VAR(struct features_config *, cfg, NULL, ao2_cleanup);
    if (chan) {
       cfg = get_feature_ds(chan);
    } else {
       cfg = ao2_global_obj_ref(globals);
    }
    if (!cfg) {
       return NULL;
    }
    ast_assert(cfg->featuremap != NULL);
    ao2_ref(cfg->featuremap, +1);
    return cfg->featuremap;
 }
ast_get_chan_features_atxferabort()
char* ast_get_chan_features_atxferabort (struct ast_channel * chan)
Get the transfer configuration option atxferabort.
Note
The channel should be locked before calling this function.
The returned value has to be freed.
If no channel is provided, then option is pulled from the global transfer configuration.
Parameters
chan The channel to get configuration options for
Return values
NULL Failed to get configuration
non-NULL The atxferabort
Definition at line 1178 of file features_config.c.
References ao2_ref, ast_get_chan_features_xfer_config(), ast_strdup, ast_features_xfer_config::atxferabort, and NULL.
Referenced by action_cancel_atxfer().
 {
    char *res;
    struct ast_features_xfer_config *cfg = ast_get_chan_features_xfer_config(chan);
    if (!cfg) {
       return NULL;
    }
    res = ast_strdup(cfg->atxferabort);
    ao2_ref(cfg, -1);
    return res;
 }
ast_get_chan_features_general_config()
struct ast_features_general_config* ast_get_chan_features_general_config (struct ast_channel * chan)
Get the general configuration options for a channel.
Note
The channel should be locked before calling this function.
The returned value has its reference count incremented.
If no channel is provided, then the global features configuration is returned.
Parameters
chan The channel to get configuration options for
Return values
NULL Failed to get configuration
non-NULL The general features configuration
Definition at line 1123 of file features_config.c.
References ao2_cleanup, ao2_global_obj_ref, ao2_ref, ast_assert, get_feature_ds(), globals, NULL, and RAII_VAR.
Referenced by bridge_channel_feature_digit_timeout(), feature_automixmonitor(), and feature_automonitor().
 {
    RAII_VAR(struct features_config *, cfg, NULL, ao2_cleanup);
    if (chan) {
       cfg = get_feature_ds(chan);
    } else {
       cfg = ao2_global_obj_ref(globals);
    }
    if (!cfg) {
       return NULL;
    }
    ast_assert(cfg->global && cfg->global->general);
    ao2_ref(cfg->global->general, +1);
    return cfg->global->general;
 }
ast_get_chan_features_pickup_config()
struct ast_features_pickup_config* ast_get_chan_features_pickup_config (struct ast_channel * chan)
Get the pickup configuration options for a channel.
Note
The channel should be locked before calling this function.
The returned value has its reference count incremented.
If no channel is provided, then the global pickup configuration is returned.
Parameters
chan The channel to get configuration options for
Return values
NULL Failed to get configuration
non-NULL The pickup features configuration
Definition at line 1193 of file features_config.c.
References ao2_cleanup, ao2_global_obj_ref, ao2_ref, ast_assert, get_feature_ds(), globals, NULL, and RAII_VAR.
Referenced by __analog_ss_thread(), analog_ss_thread(), ast_pickup_call(), call_pickup_incoming_request(), cb_events(), get_destination(), handle_call_outgoing(), handle_request_invite(), key_main_page(), and mgcp_ss().
 {
    RAII_VAR(struct features_config *, cfg, NULL, ao2_cleanup);
    if (chan) {
       cfg = get_feature_ds(chan);
    } else {
       cfg = ao2_global_obj_ref(globals);
    }
    if (!cfg) {
       return NULL;
    }
    ast_assert(cfg->global && cfg->global->pickup);
    ao2_ref(cfg->global->pickup, +1);
    return cfg->global->pickup;
 }
ast_get_chan_features_xfer_config()
struct ast_features_xfer_config* ast_get_chan_features_xfer_config (struct ast_channel * chan)
Get the transfer configuration options for a channel.
Note
The channel should be locked before calling this function.
The returned value has its reference count incremented.
If no channel is provided, then the global transfer configuration is returned.
Parameters
chan The channel to get configuration options for
Return values
NULL Failed to get configuration
non-NULL The transfer features configuration
Definition at line 1143 of file features_config.c.
References ao2_cleanup, ao2_global_obj_ref, ao2_ref, ast_assert, get_feature_ds(), globals, NULL, and RAII_VAR.
Referenced by action_bridge(), add_transferer_role(), ast_get_chan_features_atxferabort(), ast_get_chan_features_xferfailsound(), attended_transfer_properties_alloc(), bridge_exec(), grab_transfer(), and testsuite_notify_feature_success().
 {
    RAII_VAR(struct features_config *, cfg, NULL, ao2_cleanup);
    if (chan) {
       cfg = get_feature_ds(chan);
    } else {
       cfg = ao2_global_obj_ref(globals);
    }
    if (!cfg) {
       return NULL;
    }
    ast_assert(cfg->global && cfg->global->xfer);
    ao2_ref(cfg->global->xfer, +1);
    return cfg->global->xfer;
 }
ast_get_chan_features_xferfailsound()
char* ast_get_chan_features_xferfailsound (struct ast_channel * chan)
Get the transfer configuration option xferfailsound.
Note
The channel should be locked before calling this function.
The returned value has to be freed.
If no channel is provided, then option is pulled from the global transfer configuration.
Parameters
chan The channel to get configuration options for
Return values
NULL Failed to get configuration
non-NULL The xferfailsound
Definition at line 1163 of file features_config.c.
References ao2_ref, ast_get_chan_features_xfer_config(), ast_strdup, NULL, and ast_features_xfer_config::xferfailsound.
Referenced by play_failsound(), and stream_failsound().
 {
    char *res;
    struct ast_features_xfer_config *cfg = ast_get_chan_features_xfer_config(chan);
    if (!cfg) {
       return NULL;
    }
    res = ast_strdup(cfg->xferfailsound);
    ao2_ref(cfg, -1);
    return res;
 }
ast_get_feature()
int ast_get_feature (struct ast_channel * chan, const char * feature, char * buf, size_t len)
Get the DTMF code for a call feature.
Note
The channel should be locked before calling this function
If no channel is provided, then the global setting for the option is returned.
This function is like ast_get_builtin_feature except that it will also check the applicationmap in addition to the builtin features.
Parameters
chan The channel to get the option from
feature The short name of the feature
[out] buf The buffer to write the DTMF value into
size The size of the buffer in bytes
Return values
0 Success
non-zero Unrecognized feature name
Definition at line 1250 of file features_config.c.
References ao2_cleanup, ao2_find, ast_copy_string(), ast_get_builtin_feature(), ast_get_chan_applicationmap(), item, NULL, OBJ_KEY, and RAII_VAR.
Referenced by handle_incoming_request(), and handle_request_info().
 {
    RAII_VAR(struct ao2_container *, applicationmap, NULL, ao2_cleanup);
    RAII_VAR(struct ast_applicationmap_item *, item, NULL, ao2_cleanup);
    if (!ast_get_builtin_feature(chan, feature, buf, len)) {
       return 0;
    }
    /* Dang, must be in the application map */
    applicationmap = ast_get_chan_applicationmap(chan);
    if (!applicationmap) {
       return -1;
    }
    item = ao2_find(applicationmap, feature, OBJ_KEY);
    if (!item) {
       return -1;
    }
    ast_copy_string(buf, item->dtmf, len);
    return 0;
 }