Asterisk - The Open Source Telephony Project: stasis_bridges.c File Reference
stasis_bridges.c File Reference
Stasis Messages and Data Types for Bridge Objects.
#include "asterisk.h"
#include "asterisk/astobj2.h"
#include "asterisk/stasis.h"
#include "asterisk/stasis_cache_pattern.h"
#include "asterisk/channel.h"
#include "asterisk/stasis_bridges.h"
#include "asterisk/stasis_channels.h"
#include "asterisk/bridge.h"
#include "asterisk/bridge_technology.h"
Macros
#define SNAPSHOT_CHANNELS_BUCKETS 1
Functions
int ast_attended_transfer_message_add_app (struct ast_attended_transfer_message *transfer_msg, const char *app, struct ast_channel *replace_channel)
Add details for an attended transfer to an application.
int ast_attended_transfer_message_add_link (struct ast_attended_transfer_message *transfer_msg, struct ast_channel *locals[2])
Add details for an attended transfer that has a link between bridges.
int ast_attended_transfer_message_add_merge (struct ast_attended_transfer_message *transfer_msg, struct ast_bridge *final_bridge)
Add details for a bridge merge to an attended transfer message.
int ast_attended_transfer_message_add_threeway (struct ast_attended_transfer_message *transfer_msg, struct ast_channel *survivor_channel, struct ast_bridge *survivor_bridge)
Add details for an attended transfer that was resolved as a three-way call.
struct ast_attended_transfer_message * ast_attended_transfer_message_create (int is_external, struct ast_channel *to_transferee, struct ast_bridge *transferee_bridge, struct ast_channel *to_transfer_target, struct ast_bridge *target_bridge, struct ast_channel *transferee, struct ast_channel *transfer_target)
Create an Attended transfer message to be published.
struct ast_blind_transfer_message * ast_blind_transfer_message_create (int is_external, struct ast_channel *transferer, const char *exten, const char *context)
Create a blind transfer message to be published.
struct stasis_message * ast_bridge_blob_create (struct stasis_message_type *message_type, struct ast_bridge *bridge, struct ast_channel *chan, struct ast_json *blob)
Creates a ast_bridge_blob message.
struct stasis_message * ast_bridge_blob_create_from_snapshots (struct stasis_message_type *message_type, struct ast_bridge_snapshot *bridge_snapshot, struct ast_channel_snapshot *chan_snapshot, struct ast_json *blob)
Creates a ast_bridge_blob message from snapshots.
struct ast_bridge_snapshot * ast_bridge_get_snapshot (struct ast_bridge *bridge)
Returns the current snapshot for the bridge.
struct ast_bridge_snapshot * ast_bridge_get_snapshot_by_uniqueid (const char *uniqueid)
Returns the current snapshot for the bridge.
static struct ast_json * ast_bridge_merge_message_to_json (struct stasis_message *msg, const struct stasis_message_sanitizer *sanitize)
void ast_bridge_publish_attended_transfer (struct ast_attended_transfer_message *transfer_msg)
Publish an attended transfer.
void ast_bridge_publish_blind_transfer (struct ast_blind_transfer_message *transfer_message)
Publish a blind transfer event.
void ast_bridge_publish_enter (struct ast_bridge *bridge, struct ast_channel *chan, struct ast_channel *swap)
Publish a bridge channel enter event.
void ast_bridge_publish_leave (struct ast_bridge *bridge, struct ast_channel *chan)
Publish a bridge channel leave event.
void ast_bridge_publish_merge (struct ast_bridge *to, struct ast_bridge *from)
Publish a bridge merge.
void ast_bridge_publish_state (struct ast_bridge *bridge)
Publish the state of a bridge.
struct ast_bridge_snapshot * ast_bridge_snapshot_create (struct ast_bridge *bridge)
Generate a snapshot of the bridge state. This is an ao2 object, so ao2_cleanup() to deallocate.
struct ast_json * ast_bridge_snapshot_to_json (const struct ast_bridge_snapshot *snapshot, const struct stasis_message_sanitizer *sanitize)
Build a JSON object from a ast_bridge_snapshot.
struct stasis_topic * ast_bridge_topic (struct ast_bridge *bridge)
A topic which publishes the events for a particular bridge.
struct stasis_topic * ast_bridge_topic_all (void)
A topic which publishes the events for all bridges.
static struct ast_json * ast_channel_entered_bridge_to_json (struct stasis_message *msg, const struct stasis_message_sanitizer *sanitize)
static struct ast_json * ast_channel_left_bridge_to_json (struct stasis_message *msg, const struct stasis_message_sanitizer *sanitize)
int ast_stasis_bridging_init (void)
static void attended_transfer_dtor (void *obj)
static struct ast_manager_event_blob * attended_transfer_to_ami (struct stasis_message *message)
static struct ast_json * attended_transfer_to_json (struct stasis_message *msg, const struct stasis_message_sanitizer *sanitize)
static void blind_transfer_dtor (void *obj)
static struct ast_manager_event_blob * blind_transfer_to_ami (struct stasis_message *message)
static struct ast_json * blind_transfer_to_json (struct stasis_message *msg, const struct stasis_message_sanitizer *sanitize)
static void bridge_blob_dtor (void *obj)
static void bridge_channel_snapshot_pair_cleanup (struct ast_bridge_channel_snapshot_pair *pair)
static int bridge_channel_snapshot_pair_init (struct ast_channel *channel, struct ast_bridge *bridge, struct ast_bridge_channel_snapshot_pair *snapshot_pair)
static struct ast_bridge_merge_message * bridge_merge_message_create (struct ast_bridge *to, struct ast_bridge *from)
Bridge merge message creation helper.
static void bridge_merge_message_dtor (void *obj)
Destructor for bridge merge messages.
static void bridge_publish_state_from_blob (struct ast_bridge *bridge, struct ast_bridge_blob *obj)
static void bridge_snapshot_dtor (void *obj)
Destructor for bridge snapshots.
static struct ast_bridge_snapshot_update * bridge_snapshot_update_create (struct ast_bridge_snapshot *old, struct ast_bridge_snapshot *new)
static void bridge_snapshot_update_dtor (void *obj)
void bridge_topics_destroy (struct ast_bridge *bridge)
int bridge_topics_init (struct ast_bridge *bridge)
static const char * capability2str (uint32_t capabilities)
static struct ast_json * container_to_json_array (struct ao2_container *items, const struct stasis_message_sanitizer *sanitize)
static struct ast_json * simple_bridge_channel_event (const char *type, struct ast_bridge_snapshot *bridge_snapshot, struct ast_channel_snapshot *channel_snapshot, const struct timeval *tv, const struct stasis_message_sanitizer *sanitize)
static void stasis_bridging_cleanup (void)
STASIS_MESSAGE_TYPE_DEFN (ast_bridge_snapshot_type)
Define bridge message types.
STASIS_MESSAGE_TYPE_DEFN (ast_bridge_merge_message_type,.to_json=ast_bridge_merge_message_to_json)
STASIS_MESSAGE_TYPE_DEFN (ast_channel_entered_bridge_type,.to_json=ast_channel_entered_bridge_to_json)
STASIS_MESSAGE_TYPE_DEFN (ast_channel_left_bridge_type,.to_json=ast_channel_left_bridge_to_json)
STASIS_MESSAGE_TYPE_DEFN (ast_blind_transfer_type,.to_json=blind_transfer_to_json,.to_ami=blind_transfer_to_ami)
STASIS_MESSAGE_TYPE_DEFN (ast_attended_transfer_type,.to_json=attended_transfer_to_json,.to_ami=attended_transfer_to_ami)
Variables
static struct stasis_topic * bridge_topic_all
static struct stasis_topic_pool * bridge_topic_pool
static const char * result_strs []
Detailed Description
Stasis Messages and Data Types for Bridge Objects.
Author
Kinsey Moore kmoor.nosp@m.e@di.nosp@m.gium..nosp@m.com
Definition in file stasis_bridges.c.
Macro Definition Documentation
SNAPSHOT_CHANNELS_BUCKETS
#define SNAPSHOT_CHANNELS_BUCKETS 1
Definition at line 44 of file stasis_bridges.c.
Referenced by ast_bridge_snapshot_create().
Function Documentation
ast_attended_transfer_message_add_app()
int ast_attended_transfer_message_add_app (struct ast_attended_transfer_message * transfer_msg, const char * app, struct ast_channel * replace_channel)
Add details for an attended transfer to an application.
If the transfer is sending one or more parties into an application, then this should be called to add appropriate details to the transfer message being published.
Parameters
transfer_msg The message to add details to
app The name of the application that the parties are being transferred to
replace_channel The local channel that is in the bridge and running the application
Return values
0 Success
-1 Failure
Definition at line 1313 of file stasis_bridges.c.
References ast_attended_transfer_message::app, AST_ATTENDED_TRANSFER_DEST_APP, AST_ATTENDED_TRANSFER_DEST_LOCAL_APP, ast_channel_snapshot_get_latest(), ast_channel_uniqueid(), ast_copy_string(), ast_attended_transfer_message::dest, ast_attended_transfer_message::dest_type, and ast_attended_transfer_message::replace_channel.
Referenced by ast_bridge_transfer_attended(), and attended_transfer_bridge().
 {
    transfer_msg->dest_type = replace_channel ? AST_ATTENDED_TRANSFER_DEST_LOCAL_APP : AST_ATTENDED_TRANSFER_DEST_APP;
    if (replace_channel) {
       transfer_msg->replace_channel = ast_channel_snapshot_get_latest(ast_channel_uniqueid(replace_channel));
       if (!transfer_msg->replace_channel) {
          return -1;
       }
    }
    ast_copy_string(transfer_msg->dest.app, app, sizeof(transfer_msg->dest.app));
    return 0;
 }
ast_attended_transfer_message_add_link()
int ast_attended_transfer_message_add_link (struct ast_attended_transfer_message * transfer_msg, struct ast_channel * locals[2])
Add details for an attended transfer that has a link between bridges.
An attended transfer may be accomplished by linking two bridges together with local channels. If this is how the transfer is to be completed, call this function in order to fill in details about the transfer.
Parameters
transfer_msg The message to add details to.
locals An array of local channel halves that each are in one of the involved bridges.
Return values
0 Success
-1 Failure
Definition at line 1330 of file stasis_bridges.c.
References AST_ATTENDED_TRANSFER_DEST_LINK, ast_channel_snapshot_get_latest(), ast_channel_uniqueid(), ast_attended_transfer_message::dest, ast_attended_transfer_message::dest_type, and ast_attended_transfer_message::links.
Referenced by attended_transfer_bridge().
 {
    int i;
    transfer_msg->dest_type = AST_ATTENDED_TRANSFER_DEST_LINK;
    for (i = 0; i < 2; ++i) {
       transfer_msg->dest.links[i] = ast_channel_snapshot_get_latest(ast_channel_uniqueid(locals[i]));
       if (!transfer_msg->dest.links[i]) {
          return -1;
       }
    }
    return 0;
 }
ast_attended_transfer_message_add_merge()
int ast_attended_transfer_message_add_merge (struct ast_attended_transfer_message * transfer_msg, struct ast_bridge * final_bridge)
Add details for a bridge merge to an attended transfer message.
If the transfer is accomplished by a bridge merge (or swap optimization), then this should be called on the created attended transfer message to have the appropriate details added on.
Parameters
transfer_msg The transfer message to add details to
final_bridge The bridge where the surviving parties reside
Return values
0 Success
-1 Failure
Definition at line 1283 of file stasis_bridges.c.
References AST_ATTENDED_TRANSFER_DEST_BRIDGE_MERGE, ast_copy_string(), ast_attended_transfer_message::bridge, ast_attended_transfer_message::dest, ast_attended_transfer_message::dest_type, and ast_bridge::uniqueid.
Referenced by publish_transfer_success(), and two_bridge_attended_transfer().
 {
    transfer_msg->dest_type = AST_ATTENDED_TRANSFER_DEST_BRIDGE_MERGE;
    ast_copy_string(transfer_msg->dest.bridge, final_bridge->uniqueid,
          sizeof(transfer_msg->dest.bridge));
    return 0;
 }
ast_attended_transfer_message_add_threeway()
int ast_attended_transfer_message_add_threeway (struct ast_attended_transfer_message * transfer_msg, struct ast_channel * survivor_channel, struct ast_bridge * survivor_bridge)
Add details for an attended transfer that was resolved as a three-way call.
If the transfer results in a three-way call between the transferer, the transferee, and the transfer target, then this should be called in order to add appropriate details to the transfer message to be published.
Parameters
transfer_msg The message to add details to
survivor_channel The transferer channel that exists in the three-way call
survivor_bridge The bridge where the three-way call takes place.
Return values
0 Success
-1 Failure
Definition at line 1293 of file stasis_bridges.c.
References AST_ATTENDED_TRANSFER_DEST_THREEWAY, ast_channel_uniqueid(), ast_channel_snapshot::base, ast_bridge_channel_snapshot_pair::bridge_snapshot, ast_bridge_channel_snapshot_pair::channel_snapshot, ast_attended_transfer_message::dest, ast_attended_transfer_message::dest_type, ast_attended_transfer_message::threeway, ast_attended_transfer_message::to_transfer_target, ast_attended_transfer_message::to_transferee, ast_channel_snapshot_base::uniqueid, ast_bridge_snapshot::uniqueid, and ast_bridge::uniqueid.
Referenced by publish_transfer_threeway().
 {
    transfer_msg->dest_type = AST_ATTENDED_TRANSFER_DEST_THREEWAY;
    if (!strcmp(ast_channel_uniqueid(survivor_channel), transfer_msg->to_transferee.channel_snapshot->base->uniqueid)) {
       transfer_msg->dest.threeway.channel_snapshot = transfer_msg->to_transferee.channel_snapshot;
    } else {
       transfer_msg->dest.threeway.channel_snapshot = transfer_msg->to_transfer_target.channel_snapshot;
    }
    if (!strcmp(survivor_bridge->uniqueid, transfer_msg->to_transferee.bridge_snapshot->uniqueid)) {
       transfer_msg->dest.threeway.bridge_snapshot = transfer_msg->to_transferee.bridge_snapshot;
    } else {
       transfer_msg->dest.threeway.bridge_snapshot = transfer_msg->to_transfer_target.bridge_snapshot;
    }
    return 0;
 }
ast_attended_transfer_message_create()
struct ast_attended_transfer_message* ast_attended_transfer_message_create (int is_external, struct ast_channel * to_transferee, struct ast_bridge * transferee_bridge, struct ast_channel * to_transfer_target, struct ast_bridge * target_bridge, struct ast_channel * transferee, struct ast_channel * transfer_target)
Create an Attended transfer message to be published.
The parameters to this function are the basic necessities in order to create the initial attended transfer message.
The transferee and transfer_target parameters are optional. If not provided, then this function will attempt to determine who the transferee and transfer target are based on the input transferer channels and bridges. You typically will not need to provide an explicit transferee and transfer target channel unless your attended transfer is implemented in a strange way.
Parameters
is_external Non-zero if the transfer was initiated by a native channel driver protocol.
to_transferee The transferer channel that is bridged to the transferee channel.
transferee_bridge The bridge between the transferer and transferee. May be NULL.
to_transfer_target The transferer channel that is bridged to the transfer target.
target_bridge The bridge between the transferer and transfer target. May be NULL.
transferee The channel that is being transferred. Optional.
transfer_target The channel that is being transferred to. Optional.
Return values
NULL Failure to allocate or create snapshots
non-NULL The created attended transfer message
Definition at line 1226 of file stasis_bridges.c.
References ao2_alloc, ao2_cleanup, ast_bridge_peer(), ast_channel_snapshot_get_latest(), ast_channel_uniqueid(), attended_transfer_dtor(), bridge_channel_snapshot_pair_init(), NULL, ast_attended_transfer_message::target, ast_attended_transfer_message::to_transfer_target, ast_attended_transfer_message::to_transferee, and ast_attended_transfer_message::transferee.
Referenced by ast_bridge_transfer_attended(), publish_transfer_fail(), publish_transfer_success(), and publish_transfer_threeway().
 {
    struct ast_attended_transfer_message *transfer_msg;
    transfer_msg = ao2_alloc(sizeof(*transfer_msg), attended_transfer_dtor);
    if (!transfer_msg) {
       return NULL;
    }
    if (bridge_channel_snapshot_pair_init(to_transferee, transferee_bridge, &transfer_msg->to_transferee) ||
          bridge_channel_snapshot_pair_init(to_transfer_target, target_bridge, &transfer_msg->to_transfer_target)) {
       ao2_cleanup(transfer_msg);
       return NULL;
    }
    if (transferee) {
       transfer_msg->transferee = ast_channel_snapshot_get_latest(ast_channel_uniqueid(transferee));
       if (!transfer_msg->transferee) {
          ao2_cleanup(transfer_msg);
          return NULL;
       }
    } else if (transferee_bridge) {
       transferee = ast_bridge_peer(transferee_bridge, to_transferee);
       if (transferee) {
          transfer_msg->transferee = ast_channel_snapshot_get_latest(ast_channel_uniqueid(transferee));
          ao2_cleanup(transferee);
          if (!transfer_msg->transferee) {
             ao2_cleanup(transfer_msg);
             return NULL;
          }
       }
    }
    if (transfer_target) {
       transfer_msg->target = ast_channel_snapshot_get_latest(ast_channel_uniqueid(transfer_target));
       if (!transfer_msg->target) {
          ao2_cleanup(transfer_msg);
          return NULL;
       }
    } else if (target_bridge) {
       transfer_target = ast_bridge_peer(target_bridge, to_transfer_target);
       if (transfer_target) {
          transfer_msg->target = ast_channel_snapshot_get_latest(ast_channel_uniqueid(transfer_target));
          ao2_cleanup(transfer_target);
          if (!transfer_msg->target) {
             ao2_cleanup(transfer_msg);
             return NULL;
          }
       }
    }
    return transfer_msg;
 }
ast_blind_transfer_message_create()
struct ast_blind_transfer_message* ast_blind_transfer_message_create (int is_external, struct ast_channel * transferer, const char * exten, const char * context)
Create a blind transfer message to be published.
Parameters
is_external Whether the blind transfer was initiated externally (e.g. via AMI or native protocol)
transferer The transferer's channel that is bridged to the transferee
bridge The bridge the transferer and transferee are in
context The destination context for the blind transfer
exten The destination extension for the blind transfer
Return values
NULL Failure to allocate or create snapshots
non-NULL The created blind transfer message
Definition at line 929 of file stasis_bridges.c.
References ao2_alloc, ao2_cleanup, ast_channel_snapshot_get_latest(), ast_channel_uniqueid(), ast_copy_string(), blind_transfer_dtor(), ast_blind_transfer_message::context, ast_blind_transfer_message::exten, ast_blind_transfer_message::is_external, NULL, and ast_blind_transfer_message::transferer.
Referenced by ast_bridge_transfer_blind(), and AST_TEST_DEFINE().
 {
    struct ast_blind_transfer_message *msg;
    msg = ao2_alloc(sizeof(*msg), blind_transfer_dtor);
    if (!msg) {
       return NULL;
    }
    msg->transferer = ast_channel_snapshot_get_latest(ast_channel_uniqueid(transferer));
    if (!msg->transferer) {
       ao2_cleanup(msg);
       return NULL;
    }
    msg->is_external = is_external;
    ast_copy_string(msg->context, context, sizeof(msg->context));
    ast_copy_string(msg->exten, exten, sizeof(msg->exten));
    return msg;
 }
ast_bridge_blob_create()
struct stasis_message* ast_bridge_blob_create (struct stasis_message_type * type, struct ast_bridge * bridge, struct ast_channel * chan, struct ast_json * blob)
Creates a ast_bridge_blob message.
Since
12 The blob JSON object requires a "type" field describing the blob. It should also be treated as immutable and not modified after it is put into the message.
Precondition
bridge is locked.
No channels are locked.
Parameters
bridge Channel blob is associated with, or NULL for global/all bridges.
blob JSON object representing the data.
Returns
ast_bridge_blob message.
NULL on error
Definition at line 500 of file stasis_bridges.c.
References ao2_alloc, ao2_ref, ast_bridge_snapshot_create(), ast_channel_snapshot_get_latest(), ast_channel_uniqueid(), ast_json_ref(), ast_bridge_blob::blob, ast_bridge_blob::bridge, bridge_blob_dtor(), ast_bridge_blob::channel, NULL, and stasis_message_create().
Referenced by ast_bridge_publish_enter(), ast_bridge_publish_leave(), and send_conf_stasis().
 {
    struct ast_bridge_blob *obj;
    struct stasis_message *msg;
    if (!message_type) {
       return NULL;
    }
    obj = ao2_alloc(sizeof(*obj), bridge_blob_dtor);
    if (!obj) {
       return NULL;
    }
    if (bridge) {
       obj->bridge = ast_bridge_snapshot_create(bridge);
       if (obj->bridge == NULL) {
          ao2_ref(obj, -1);
          return NULL;
       }
    }
    if (chan) {
       obj->channel = ast_channel_snapshot_get_latest(ast_channel_uniqueid(chan));
       if (obj->channel == NULL) {
          ao2_ref(obj, -1);
          return NULL;
       }
    }
    if (blob) {
       obj->blob = ast_json_ref(blob);
    }
    msg = stasis_message_create(message_type, obj);
    ao2_ref(obj, -1);
    return msg;
 }
ast_bridge_blob_create_from_snapshots()
struct stasis_message* ast_bridge_blob_create_from_snapshots (struct stasis_message_type * type, struct ast_bridge_snapshot * bridge_snapshot, struct ast_channel_snapshot * chan_snapshot, struct ast_json * blob)
Creates a ast_bridge_blob message from snapshots.
Since
13.28
16.5 The blob JSON object requires a "type" field describing the blob. It should also be treated as immutable and not modified after it is put into the message.
Precondition
bridge is locked.
No channels are locked.
Parameters
bridge_snapshot Bridge snapshot
channel_snapshot Channel snapshot
blob JSON object representing the data.
Returns
ast_bridge_blob message.
NULL on error
Definition at line 546 of file stasis_bridges.c.
References ao2_alloc, ao2_bump, ao2_ref, ast_json_ref(), ast_bridge_blob::blob, ast_bridge_blob::bridge, bridge_blob_dtor(), ast_bridge_blob::channel, NULL, and stasis_message_create().
Referenced by send_conf_stasis_snapshots().
 {
    struct ast_bridge_blob *obj;
    struct stasis_message *msg;
    if (!message_type) {
       return NULL;
    }
    obj = ao2_alloc(sizeof(*obj), bridge_blob_dtor);
    if (!obj) {
       return NULL;
    }
    if (bridge_snapshot) {
       obj->bridge = ao2_bump(bridge_snapshot);
    }
    if (chan_snapshot) {
       obj->channel = ao2_bump(chan_snapshot);
    }
    if (blob) {
       obj->blob = ast_json_ref(blob);
    }
    msg = stasis_message_create(message_type, obj);
    ao2_ref(obj, -1);
    return msg;
 }
ast_bridge_get_snapshot()
struct ast_bridge_snapshot* ast_bridge_get_snapshot (struct ast_bridge * bridge)
Returns the current snapshot for the bridge.
Since
17.0
The returned pointer is AO2 managed, so ao2_cleanup() when you're done.
Parameters
bridge The bridge from which to get the snapshot.
Returns
Most recent snapshot. ao2_cleanup() when done.
NULL if there isn't a snapshot.
Definition at line 1378 of file stasis_bridges.c.
References ao2_bump, ast_bridge_lock, ast_bridge_unlock, ast_bridge::current_snapshot, and NULL.
Referenced by ast_ari_bridges_list(), bridges_scrape_cb(), handle_bridge_show_all(), send_bridge_list_item_cb(), and test_cel_generate_peer_str_snapshot().
 {
    struct ast_bridge_snapshot *snapshot;
    if (!bridge) {
       return NULL;
    }
    ast_bridge_lock(bridge);
    snapshot = ao2_bump(bridge->current_snapshot);
    ast_bridge_unlock(bridge);
    return snapshot;
 }
ast_bridge_get_snapshot_by_uniqueid()
struct ast_bridge_snapshot* ast_bridge_get_snapshot_by_uniqueid (const char * bridge_id)
Returns the current snapshot for the bridge.
Since
17.0
The returned pointer is AO2 managed, so ao2_cleanup() when you're done.
Parameters
bridge_id Uniqueid of the bridge from which to get the snapshot.
Returns
Most recent snapshot. ao2_cleanup() when done.
NULL if bridge or snapshot doesn't exist.
Definition at line 1359 of file stasis_bridges.c.
References ao2_bump, ao2_ref, ast_assert, ast_bridge_find_by_id(), ast_bridge_lock, ast_bridge_unlock, ast_strlen_zero, ast_bridge::current_snapshot, and NULL.
Referenced by ast_ari_bridges_get(), find_bridge(), handle_bridge_show_specific(), manager_bridge_info(), and stasis_app_user_event().
 {
    struct ast_bridge *bridge;
    struct ast_bridge_snapshot *snapshot;
    ast_assert(!ast_strlen_zero(uniqueid));
    bridge = ast_bridge_find_by_id(uniqueid);
    if (!bridge) {
       return NULL;
    }
    ast_bridge_lock(bridge);
    snapshot = ao2_bump(bridge->current_snapshot);
    ast_bridge_unlock(bridge);
    ao2_ref(bridge, -1);
    return snapshot;
 }
ast_bridge_merge_message_to_json()
static struct ast_json * ast_bridge_merge_message_to_json (struct stasis_message * msg, const struct stasis_message_sanitizer * sanitize) static
Definition at line 438 of file stasis_bridges.c.
References ast_bridge_snapshot_to_json(), ast_json_pack(), ast_json_timeval(), ast_json_unref(), ast_bridge_merge_message::from, NULL, stasis_message_data(), stasis_message_timestamp(), and ast_bridge_merge_message::to.
 {
    struct ast_bridge_merge_message *merge = stasis_message_data(msg);
    struct ast_json *json_bridge_to = ast_bridge_snapshot_to_json(merge->to, sanitize);
    struct ast_json *json_bridge_from = ast_bridge_snapshot_to_json(merge->from, sanitize);
    if (!json_bridge_to || !json_bridge_from) {
       ast_json_unref(json_bridge_to);
       ast_json_unref(json_bridge_from);
       return NULL;
    }
    return ast_json_pack("{s: s, s: o, s: o, s: o}",
       "type", "BridgeMerged",
       "timestamp", ast_json_timeval(*stasis_message_timestamp(msg), NULL),
       "bridge", json_bridge_to,
       "bridge_from", json_bridge_from);
 }
ast_bridge_publish_attended_transfer()
void ast_bridge_publish_attended_transfer (struct ast_attended_transfer_message * transfer_msg)
Publish an attended transfer.
Parameters
transfer_msg The transfer message to publish
Definition at line 1346 of file stasis_bridges.c.
References ao2_ref, ast_attended_transfer_type(), ast_bridge_topic_all(), stasis_message_create(), and stasis_publish().
Referenced by ast_bridge_transfer_attended(), publish_transfer_fail(), publish_transfer_success(), and publish_transfer_threeway().
 {
    struct stasis_message *msg;
    msg = stasis_message_create(ast_attended_transfer_type(), transfer_msg);
    if (!msg) {
       return;
    }
    stasis_publish(ast_bridge_topic_all(), msg);
    ao2_ref(msg, -1);
 }
ast_bridge_publish_blind_transfer()
void ast_bridge_publish_blind_transfer (struct ast_blind_transfer_message * transfer_message)
Publish a blind transfer event.
Precondition
Bridges involved are locked. Channels involved are not locked.
Parameters
is_external Whether the blind transfer was initiated externally (e.g. via AMI or native protocol)
result The success or failure of the transfer
to_transferee The bridge between the transferer and transferee plus the transferer channel
context The destination context for the blind transfer
exten The destination extension for the blind transfer
transferee_channel If a single channel is being transferred, this is it. If multiple parties are being transferred, this is NULL.
replace_channel If multiple parties are being transferred or the transfer cannot reach across the bridge due to bridge flags, this is the channel connecting their bridge to the destination.
Definition at line 953 of file stasis_bridges.c.
References ao2_cleanup, ast_blind_transfer_type(), ast_bridge_topic_all(), stasis, stasis_message_create(), and stasis_publish().
Referenced by ast_bridge_transfer_blind(), and AST_TEST_DEFINE().
 {
    struct stasis_message *stasis;
    stasis = stasis_message_create(ast_blind_transfer_type(), transfer_message);
    if (!stasis) {
       return;
    }
    stasis_publish(ast_bridge_topic_all(), stasis);
    ao2_cleanup(stasis);
 }
ast_bridge_publish_enter()
void ast_bridge_publish_enter (struct ast_bridge * bridge, struct ast_channel * chan, struct ast_channel * swap)
Publish a bridge channel enter event.
Since
12
Precondition
bridge is locked.
No channels are locked.
Parameters
bridge The bridge a channel entered
chan The channel that entered the bridge
swap The channel being swapped out of the bridge
Definition at line 582 of file stasis_bridges.c.
References ao2_ref, ast_bridge_blob_create(), AST_BRIDGE_FLAG_INVISIBLE, ast_bridge_topic(), ast_channel_entered_bridge_type(), ast_channel_uniqueid(), ast_json_pack(), ast_json_unref(), ast_test_flag, bridge_publish_state_from_blob(), ast_bridge::feature_flags, NULL, stasis_message_data(), and stasis_publish().
Referenced by bridge_channel_internal_push_full().
 {
    struct stasis_message *msg;
    struct ast_json *blob = NULL;
    if (ast_test_flag(&bridge->feature_flags, AST_BRIDGE_FLAG_INVISIBLE)) {
       return;
    }
    if (swap) {
       blob = ast_json_pack("{s: s}", "swap", ast_channel_uniqueid(swap));
       if (!blob) {
          return;
       }
    }
    msg = ast_bridge_blob_create(ast_channel_entered_bridge_type(), bridge, chan, blob);
    ast_json_unref(blob);
    if (!msg) {
       return;
    }
    /* enter blob first, then state */
    stasis_publish(ast_bridge_topic(bridge), msg);
    bridge_publish_state_from_blob(bridge, stasis_message_data(msg));
    ao2_ref(msg, -1);
 }
ast_bridge_publish_leave()
void ast_bridge_publish_leave (struct ast_bridge * bridge, struct ast_channel * chan)
Publish a bridge channel leave event.
Since
12
Precondition
bridge is locked.
No channels are locked.
Parameters
bridge The bridge a channel left
chan The channel that left the bridge
Definition at line 611 of file stasis_bridges.c.
References ao2_ref, ast_bridge_blob_create(), AST_BRIDGE_FLAG_INVISIBLE, ast_bridge_topic(), ast_channel_left_bridge_type(), ast_test_flag, bridge_publish_state_from_blob(), ast_bridge::feature_flags, NULL, stasis_message_data(), and stasis_publish().
Referenced by bridge_channel_internal_pull().
 {
    struct stasis_message *msg;
    if (ast_test_flag(&bridge->feature_flags, AST_BRIDGE_FLAG_INVISIBLE)) {
       return;
    }
    msg = ast_bridge_blob_create(ast_channel_left_bridge_type(), bridge, chan, NULL);
    if (!msg) {
       return;
    }
    /* state first, then leave blob (opposite of enter, preserves nesting of events) */
    bridge_publish_state_from_blob(bridge, stasis_message_data(msg));
    stasis_publish(ast_bridge_topic(bridge), msg);
    ao2_ref(msg, -1);
 }
ast_bridge_publish_merge()
void ast_bridge_publish_merge (struct ast_bridge * to, struct ast_bridge * from)
Publish a bridge merge.
Since
12
Precondition
Bridges involved are locked
Parameters
to The bridge to which channels are being added
from The bridge from which channels are being removed
Definition at line 460 of file stasis_bridges.c.
References ao2_ref, ast_assert, AST_BRIDGE_FLAG_INVISIBLE, ast_bridge_merge_message_type(), ast_bridge_topic_all(), ast_test_flag, bridge_merge_message_create(), ast_bridge::feature_flags, NULL, stasis_message_create(), and stasis_publish().
Referenced by bridge_do_merge().
 {
    struct ast_bridge_merge_message *merge_msg;
    struct stasis_message *msg;
    if (!ast_bridge_merge_message_type()) {
       return;
    }
    ast_assert(to != NULL);
    ast_assert(from != NULL);
    ast_assert(ast_test_flag(&to->feature_flags, AST_BRIDGE_FLAG_INVISIBLE) == 0);
    ast_assert(ast_test_flag(&from->feature_flags, AST_BRIDGE_FLAG_INVISIBLE) == 0);
    merge_msg = bridge_merge_message_create(to, from);
    if (!merge_msg) {
       return;
    }
    msg = stasis_message_create(ast_bridge_merge_message_type(), merge_msg);
    ao2_ref(merge_msg, -1);
    if (!msg) {
       return;
    }
    stasis_publish(ast_bridge_topic_all(), msg);
    ao2_ref(msg, -1);
 }
ast_bridge_publish_state()
void ast_bridge_publish_state (struct ast_bridge * bridge)
Publish the state of a bridge.
Since
12
Precondition
Bridge is locked
Parameters
bridge The bridge for which to publish state
Definition at line 350 of file stasis_bridges.c.
References ao2_cleanup, ao2_ref, ast_assert, ast_bridge_snapshot_create(), ast_bridge_snapshot_type(), ast_bridge_topic(), bridge_snapshot_update_create(), ast_bridge::current_snapshot, NULL, stasis_message_create(), stasis_publish(), and update().
Referenced by ast_bridge_set_single_src_video_mode(), ast_bridge_update_talker_src_video_mode(), bridge_reconfigured(), and bridge_register().
 {
    struct ast_bridge_snapshot *new_snapshot;
    struct ast_bridge_snapshot_update *update;
    struct stasis_message *msg;
    ast_assert(bridge != NULL);
    new_snapshot = ast_bridge_snapshot_create(bridge);
    if (!new_snapshot) {
       return;
    }
    update = bridge_snapshot_update_create(bridge->current_snapshot, new_snapshot);
    /* There may not have been an old snapshot */
    ao2_cleanup(bridge->current_snapshot);
    bridge->current_snapshot = new_snapshot;
    if (!update) {
       return;
    }
    msg = stasis_message_create(ast_bridge_snapshot_type(), update);
    ao2_ref(update, -1);
    if (!msg) {
       return;
    }
    stasis_publish(ast_bridge_topic(bridge), msg);
    ao2_ref(msg, -1);
 }
ast_bridge_snapshot_create()
struct ast_bridge_snapshot* ast_bridge_snapshot_create (struct ast_bridge * bridge)
Generate a snapshot of the bridge state. This is an ao2 object, so ao2_cleanup() to deallocate.
Since
12
Precondition
Bridge is locked
Parameters
bridge The bridge from which to generate a snapshot
Return values
AO2 refcounted snapshot on success
NULL on error
Definition at line 202 of file stasis_bridges.c.
References AO2_ALLOC_OPT_LOCK_NOLOCK, ao2_alloc_options, ao2_ref, AST_BRIDGE_FLAG_INVISIBLE, AST_BRIDGE_VIDEO_MODE_SINGLE_SRC, AST_BRIDGE_VIDEO_MODE_TALKER_SRC, ast_channel_uniqueid(), AST_LIST_TRAVERSE, ast_str_container_add(), ast_str_container_alloc, ast_string_field_init, ast_string_field_set, ast_test_flag, bridge_snapshot_dtor(), ast_bridge_technology::capabilities, ast_bridge_snapshot::capabilities, ast_bridge_channel::chan, ast_bridge_video_single_src_data::chan_vsrc, ast_bridge_video_talker_src_data::chan_vsrc, ast_bridge_snapshot::channels, ast_bridge::channels, ast_bridge_snapshot::creationtime, ast_bridge::creationtime, ast_bridge::creator, ast_bridge_snapshot::feature_flags, ast_bridge::feature_flags, ast_bridge_video_mode::mode, ast_bridge_video_mode::mode_data, ast_bridge_technology::name, name, ast_bridge_methods::name, ast_bridge::name, NULL, ast_bridge_snapshot::num_active, ast_bridge::num_active, ast_bridge_snapshot::num_channels, ast_bridge::num_channels, ast_bridge_video_mode::single_src_data, SNAPSHOT_CHANNELS_BUCKETS, ast_bridge::softmix, ast_bridge_video_mode::talker_src_data, ast_bridge::technology, ast_bridge::uniqueid, ast_bridge::v_table, ast_bridge_softmix::video_mode, and ast_bridge_snapshot::video_mode.
Referenced by ast_ari_bridges_create(), ast_ari_bridges_create_with_id(), ast_bridge_blob_create(), ast_bridge_publish_state(), ast_bridge_transfer_blind(), AST_TEST_DEFINE(), bridge_channel_snapshot_pair_init(), bridge_merge_message_create(), bridge_topics_destroy(), and send_conf_stasis_snapshots().
 {
    struct ast_bridge_snapshot *snapshot;
    struct ast_bridge_channel *bridge_channel;
    if (ast_test_flag(&bridge->feature_flags, AST_BRIDGE_FLAG_INVISIBLE)) {
       return NULL;
    }
    snapshot = ao2_alloc_options(sizeof(*snapshot), bridge_snapshot_dtor,
       AO2_ALLOC_OPT_LOCK_NOLOCK);
    if (!snapshot) {
       return NULL;
    }
    if (ast_string_field_init(snapshot, 128)) {
       ao2_ref(snapshot, -1);
       return NULL;
    }
    snapshot->channels = ast_str_container_alloc(SNAPSHOT_CHANNELS_BUCKETS);
    if (!snapshot->channels) {
       ao2_ref(snapshot, -1);
       return NULL;
    }
    AST_LIST_TRAVERSE(&bridge->channels, bridge_channel, entry) {
       if (ast_str_container_add(snapshot->channels,
             ast_channel_uniqueid(bridge_channel->chan))) {
          ao2_ref(snapshot, -1);
          return NULL;
       }
    }
    ast_string_field_set(snapshot, uniqueid, bridge->uniqueid);
    ast_string_field_set(snapshot, technology, bridge->technology->name);
    ast_string_field_set(snapshot, subclass, bridge->v_table->name);
    ast_string_field_set(snapshot, creator, bridge->creator);
    ast_string_field_set(snapshot, name, bridge->name);
    snapshot->feature_flags = bridge->feature_flags;
    snapshot->capabilities = bridge->technology->capabilities;
    snapshot->num_channels = bridge->num_channels;
    snapshot->num_active = bridge->num_active;
    snapshot->creationtime = bridge->creationtime;
    snapshot->video_mode = bridge->softmix.video_mode.mode;
    if (snapshot->video_mode == AST_BRIDGE_VIDEO_MODE_SINGLE_SRC
       && bridge->softmix.video_mode.mode_data.single_src_data.chan_vsrc) {
       ast_string_field_set(snapshot, video_source_id,
          ast_channel_uniqueid(bridge->softmix.video_mode.mode_data.single_src_data.chan_vsrc));
    } else if (snapshot->video_mode == AST_BRIDGE_VIDEO_MODE_TALKER_SRC
       && bridge->softmix.video_mode.mode_data.talker_src_data.chan_vsrc) {
       ast_string_field_set(snapshot, video_source_id,
          ast_channel_uniqueid(bridge->softmix.video_mode.mode_data.talker_src_data.chan_vsrc));
    }
    return snapshot;
 }
ast_bridge_snapshot_to_json()
struct ast_json* ast_bridge_snapshot_to_json (const struct ast_bridge_snapshot * snapshot, const struct stasis_message_sanitizer * sanitize)
Build a JSON object from a ast_bridge_snapshot.
Parameters
snapshot The bridge snapshot to convert to JSON
sanitize The message sanitizer to use on the snapshot
Returns
JSON object representing bridge snapshot.
NULL on error
Definition at line 712 of file stasis_bridges.c.
References AST_BRIDGE_VIDEO_MODE_NONE, ast_bridge_video_mode_to_string(), ast_json_object_set(), ast_json_pack(), ast_json_string_create(), ast_json_timeval(), ast_strlen_zero, ast_bridge_snapshot::capabilities, capability2str(), ast_bridge_snapshot::channels, container_to_json_array(), ast_bridge_snapshot::creationtime, ast_bridge_snapshot::creator, ast_bridge_snapshot::name, NULL, ast_bridge_snapshot::subclass, ast_bridge_snapshot::technology, ast_bridge_snapshot::uniqueid, ast_bridge_snapshot::video_mode, and ast_bridge_snapshot::video_source_id.
Referenced by ast_ari_bridges_create(), ast_ari_bridges_create_with_id(), ast_ari_bridges_get(), ast_ari_bridges_list(), ast_bridge_merge_message_to_json(), attended_transfer_to_json(), blind_transfer_to_json(), bridge_to_json(), multi_user_event_to_json(), simple_bridge_channel_event(), and simple_bridge_event().
 {
    struct ast_json *json_bridge;
    struct ast_json *json_channels;
    if (snapshot == NULL) {
       return NULL;
    }
    json_channels = container_to_json_array(snapshot->channels, sanitize);
    if (!json_channels) {
       return NULL;
    }
    json_bridge = ast_json_pack("{s: s, s: s, s: s, s: s, s: s, s: s, s: o, s: o, s: s}",
       "id", snapshot->uniqueid,
       "technology", snapshot->technology,
       "bridge_type", capability2str(snapshot->capabilities),
       "bridge_class", snapshot->subclass,
       "creator", snapshot->creator,
       "name", snapshot->name,
       "channels", json_channels,
       "creationtime", ast_json_timeval(snapshot->creationtime, NULL),
       "video_mode", ast_bridge_video_mode_to_string(snapshot->video_mode));
    if (!json_bridge) {
       return NULL;
    }
    if (snapshot->video_mode != AST_BRIDGE_VIDEO_MODE_NONE
       && !ast_strlen_zero(snapshot->video_source_id)) {
       ast_json_object_set(json_bridge, "video_source_id",
          ast_json_string_create(snapshot->video_source_id));
    }
    return json_bridge;
 }
ast_bridge_topic()
struct stasis_topic* ast_bridge_topic (struct ast_bridge * bridge)
A topic which publishes the events for a particular bridge.
Since
12 If the given bridge is NULL, ast_bridge_topic_all() is returned.
Parameters
bridge Bridge for which to get a topic or NULL.
Return values
Topic for bridge's events.
ast_bridge_topic_all() if bridge is NULL.
Definition at line 184 of file stasis_bridges.c.
References ast_bridge_topic_all(), and ast_bridge::topic.
Referenced by ari_bridges_play_new(), ast_ari_bridges_record(), ast_bridge_publish_enter(), ast_bridge_publish_leave(), ast_bridge_publish_state(), bridge_base_init(), bridge_publish_state_from_blob(), bridge_topics_destroy(), forwards_create_bridge(), send_conf_stasis(), and send_conf_stasis_snapshots().
 {
    if (!bridge) {
       return ast_bridge_topic_all();
    }
    return bridge->topic;
 }
ast_bridge_topic_all()
struct stasis_topic* ast_bridge_topic_all (void)
A topic which publishes the events for all bridges.
Since
12
Return values
Topic for all bridge events.
Definition at line 179 of file stasis_bridges.c.
References bridge_topic_all.
Referenced by app_create(), ast_bridge_publish_attended_transfer(), ast_bridge_publish_blind_transfer(), ast_bridge_publish_merge(), ast_bridge_topic(), create_subscriptions(), manager_bridging_init(), manager_confbridge_init(), refer_blind_callback(), and setup_stasis_subs().
 {
    return bridge_topic_all;
 }
ast_channel_entered_bridge_to_json()
struct ast_json * ast_channel_entered_bridge_to_json (struct stasis_message * msg, const struct stasis_message_sanitizer * sanitize) static
Definition at line 653 of file stasis_bridges.c.
References ast_bridge_blob::bridge, ast_bridge_blob::channel, simple_bridge_channel_event(), stasis_message_data(), and stasis_message_timestamp().
 {
    struct ast_bridge_blob *obj = stasis_message_data(msg);
    return simple_bridge_channel_event("ChannelEnteredBridge", obj->bridge,
       obj->channel, stasis_message_timestamp(msg), sanitize);
 }
ast_channel_left_bridge_to_json()
struct ast_json * ast_channel_left_bridge_to_json (struct stasis_message * msg, const struct stasis_message_sanitizer * sanitize) static
Definition at line 663 of file stasis_bridges.c.
References ast_bridge_blob::bridge, ast_bridge_blob::channel, simple_bridge_channel_event(), stasis_message_data(), and stasis_message_timestamp().
 {
    struct ast_bridge_blob *obj = stasis_message_data(msg);
    return simple_bridge_channel_event("ChannelLeftBridge", obj->bridge,
       obj->channel, stasis_message_timestamp(msg), sanitize);
 }
ast_stasis_bridging_init()
int ast_stasis_bridging_init (void)
Definition at line 1407 of file stasis_bridges.c.
References ast_attended_transfer_type(), ast_blind_transfer_type(), ast_bridge_merge_message_type(), ast_bridge_snapshot_type(), ast_channel_entered_bridge_type(), ast_channel_left_bridge_type(), ast_register_cleanup(), stasis_bridging_cleanup(), STASIS_MESSAGE_TYPE_INIT, stasis_topic_create(), and stasis_topic_pool_create().
Referenced by ast_bridging_init().
 {
    int res = 0;
    ast_register_cleanup(stasis_bridging_cleanup);
    bridge_topic_all = stasis_topic_create("bridge:all");
    if (!bridge_topic_all) {
       return -1;
    }
    bridge_topic_pool = stasis_topic_pool_create(bridge_topic_all);
    if (!bridge_topic_pool) {
       return -1;
    }
    res |= STASIS_MESSAGE_TYPE_INIT(ast_bridge_snapshot_type);
    res |= STASIS_MESSAGE_TYPE_INIT(ast_bridge_merge_message_type);
    res |= STASIS_MESSAGE_TYPE_INIT(ast_channel_entered_bridge_type);
    res |= STASIS_MESSAGE_TYPE_INIT(ast_channel_left_bridge_type);
    res |= STASIS_MESSAGE_TYPE_INIT(ast_blind_transfer_type);
    res |= STASIS_MESSAGE_TYPE_INIT(ast_attended_transfer_type);
    return res;
 }
attended_transfer_dtor()
static void attended_transfer_dtor (void * obj) static
Definition at line 1206 of file stasis_bridges.c.
References ao2_cleanup, ARRAY_LEN, AST_ATTENDED_TRANSFER_DEST_LINK, bridge_channel_snapshot_pair_cleanup(), ast_attended_transfer_message::dest, ast_attended_transfer_message::dest_type, ast_attended_transfer_message::links, ast_attended_transfer_message::replace_channel, ast_attended_transfer_message::target, ast_attended_transfer_message::to_transfer_target, ast_attended_transfer_message::to_transferee, and ast_attended_transfer_message::transferee.
Referenced by ast_attended_transfer_message_create().
 {
    struct ast_attended_transfer_message *msg = obj;
    int i;
    bridge_channel_snapshot_pair_cleanup(&msg->to_transferee);
    bridge_channel_snapshot_pair_cleanup(&msg->to_transfer_target);
    ao2_cleanup(msg->replace_channel);
    ao2_cleanup(msg->transferee);
    ao2_cleanup(msg->target);
    if (msg->dest_type != AST_ATTENDED_TRANSFER_DEST_LINK) {
       return;
    }
    for (i = 0; i < ARRAY_LEN(msg->dest.links); ++i) {
       ao2_cleanup(msg->dest.links[i]);
    }
 }
attended_transfer_to_ami()
static struct ast_manager_event_blob * attended_transfer_to_ami (struct stasis_message * message) static
Definition at line 1103 of file stasis_bridges.c.
References ast_attended_transfer_message::app, AST_ATTENDED_TRANSFER_DEST_APP, AST_ATTENDED_TRANSFER_DEST_BRIDGE_MERGE, AST_ATTENDED_TRANSFER_DEST_FAIL, AST_ATTENDED_TRANSFER_DEST_LINK, AST_ATTENDED_TRANSFER_DEST_LOCAL_APP, AST_ATTENDED_TRANSFER_DEST_THREEWAY, ast_free_ptr(), ast_manager_build_bridge_state_string_prefix(), ast_manager_build_channel_state_string_prefix(), ast_manager_event_blob_create(), ast_str_append(), ast_str_buffer(), ast_str_create, ast_channel_snapshot::base, ast_attended_transfer_message::bridge, ast_bridge_channel_snapshot_pair::bridge_snapshot, ast_bridge_channel_snapshot_pair::channel_snapshot, ast_attended_transfer_message::dest, ast_attended_transfer_message::dest_type, EVENT_FLAG_CALL, ast_attended_transfer_message::is_external, ast_attended_transfer_message::links, ast_channel_snapshot_base::name, NULL, RAII_VAR, ast_attended_transfer_message::result, result_strs, stasis_message_data(), ast_attended_transfer_message::target, ast_attended_transfer_message::threeway, ast_attended_transfer_message::to_transfer_target, ast_attended_transfer_message::to_transferee, ast_attended_transfer_message::transferee, and ast_bridge_snapshot::uniqueid.
 {
    RAII_VAR(struct ast_str *, variable_data, ast_str_create(64), ast_free_ptr);
    RAII_VAR(struct ast_str *, transferer1_state, NULL, ast_free_ptr);
    RAII_VAR(struct ast_str *, bridge1_state, NULL, ast_free_ptr);
    RAII_VAR(struct ast_str *, transferer2_state, NULL, ast_free_ptr);
    RAII_VAR(struct ast_str *, bridge2_state, NULL, ast_free_ptr);
    RAII_VAR(struct ast_str *, local1_state, NULL, ast_free_ptr);
    RAII_VAR(struct ast_str *, local2_state, NULL, ast_free_ptr);
    RAII_VAR(struct ast_str *, transferee_state, NULL, ast_free_ptr);
    RAII_VAR(struct ast_str *, target_state, NULL, ast_free_ptr);
    struct ast_attended_transfer_message *transfer_msg = stasis_message_data(msg);
    if (!variable_data) {
       return NULL;
    }
    transferer1_state = ast_manager_build_channel_state_string_prefix(transfer_msg->to_transferee.channel_snapshot, "OrigTransferer");
    transferer2_state = ast_manager_build_channel_state_string_prefix(transfer_msg->to_transfer_target.channel_snapshot, "SecondTransferer");
    if (!transferer1_state || !transferer2_state) {
       return NULL;
    }
    if (transfer_msg->transferee) {
       transferee_state = ast_manager_build_channel_state_string_prefix(transfer_msg->transferee, "Transferee");
       if (!transferee_state) {
          return NULL;
       }
    }
    if (transfer_msg->target) {
       target_state = ast_manager_build_channel_state_string_prefix(transfer_msg->target, "TransferTarget");
       if (!target_state) {
          return NULL;
       }
    }
    if (transfer_msg->to_transferee.bridge_snapshot) {
       bridge1_state = ast_manager_build_bridge_state_string_prefix(
          transfer_msg->to_transferee.bridge_snapshot, "Orig");
       if (!bridge1_state) {
          return NULL;
       }
    }
    if (transfer_msg->to_transfer_target.bridge_snapshot) {
       bridge2_state = ast_manager_build_bridge_state_string_prefix(
          transfer_msg->to_transfer_target.bridge_snapshot, "Second");
       if (!bridge2_state) {
          return NULL;
       }
    }
    switch (transfer_msg->dest_type) {
    case AST_ATTENDED_TRANSFER_DEST_BRIDGE_MERGE:
       ast_str_append(&variable_data, 0, "DestType: Bridge\r\n");
       ast_str_append(&variable_data, 0, "DestBridgeUniqueid: %s\r\n", transfer_msg->dest.bridge);
       break;
    case AST_ATTENDED_TRANSFER_DEST_APP:
    case AST_ATTENDED_TRANSFER_DEST_LOCAL_APP:
       ast_str_append(&variable_data, 0, "DestType: App\r\n");
       ast_str_append(&variable_data, 0, "DestApp: %s\r\n", transfer_msg->dest.app);
       break;
    case AST_ATTENDED_TRANSFER_DEST_LINK:
       local1_state = ast_manager_build_channel_state_string_prefix(transfer_msg->dest.links[0], "LocalOne");
       local2_state = ast_manager_build_channel_state_string_prefix(transfer_msg->dest.links[1], "LocalTwo");
       if (!local1_state || !local2_state) {
          return NULL;
       }
       ast_str_append(&variable_data, 0, "DestType: Link\r\n");
       ast_str_append(&variable_data, 0, "%s", ast_str_buffer(local1_state));
       ast_str_append(&variable_data, 0, "%s", ast_str_buffer(local2_state));
       break;
    case AST_ATTENDED_TRANSFER_DEST_THREEWAY:
       ast_str_append(&variable_data, 0, "DestType: Threeway\r\n");
       ast_str_append(&variable_data, 0, "DestBridgeUniqueid: %s\r\n", transfer_msg->dest.threeway.bridge_snapshot->uniqueid);
       ast_str_append(&variable_data, 0, "DestTransfererChannel: %s\r\n", transfer_msg->dest.threeway.channel_snapshot->base->name);
       break;
    case AST_ATTENDED_TRANSFER_DEST_FAIL:
       ast_str_append(&variable_data, 0, "DestType: Fail\r\n");
       break;
    }
    return ast_manager_event_blob_create(EVENT_FLAG_CALL, "AttendedTransfer",
          "Result: %s\r\n"
          "%s"
          "%s"
          "%s"
          "%s"
          "%s"
          "%s"
          "IsExternal: %s\r\n"
          "%s",
          result_strs[transfer_msg->result],
          ast_str_buffer(transferer1_state),
          bridge1_state ? ast_str_buffer(bridge1_state) : "",
          ast_str_buffer(transferer2_state),
          bridge2_state ? ast_str_buffer(bridge2_state) : "",
          transferee_state ? ast_str_buffer(transferee_state) : "",
          target_state ? ast_str_buffer(target_state) : "",
          transfer_msg->is_external ? "Yes" : "No",
          ast_str_buffer(variable_data));
 }
attended_transfer_to_json()
static struct ast_json * attended_transfer_to_json (struct stasis_message * msg, const struct stasis_message_sanitizer * sanitize) static
Definition at line 967 of file stasis_bridges.c.
References ast_attended_transfer_message::app, AST_ATTENDED_TRANSFER_DEST_APP, AST_ATTENDED_TRANSFER_DEST_BRIDGE_MERGE, AST_ATTENDED_TRANSFER_DEST_FAIL, AST_ATTENDED_TRANSFER_DEST_LINK, AST_ATTENDED_TRANSFER_DEST_LOCAL_APP, AST_ATTENDED_TRANSFER_DEST_THREEWAY, ast_bridge_snapshot_to_json(), ast_channel_snapshot_to_json(), ast_json_boolean(), ast_json_object_set(), ast_json_pack(), ast_json_ref(), ast_json_string_create(), ast_json_timeval(), ast_json_unref(), ast_attended_transfer_message::bridge, ast_bridge_channel_snapshot_pair::bridge_snapshot, ast_bridge_channel_snapshot_pair::channel_snapshot, ast_attended_transfer_message::dest, ast_attended_transfer_message::dest_type, ast_attended_transfer_message::is_external, ast_attended_transfer_message::links, NULL, out, RAII_VAR, ast_attended_transfer_message::replace_channel, ast_attended_transfer_message::result, result_strs, stasis_message_data(), stasis_message_timestamp(), ast_attended_transfer_message::target, ast_attended_transfer_message::threeway, ast_attended_transfer_message::to_transfer_target, ast_attended_transfer_message::to_transferee, and ast_attended_transfer_message::transferee.
 {
    struct ast_attended_transfer_message *transfer_msg = stasis_message_data(msg);
    RAII_VAR(struct ast_json *, out, NULL, ast_json_unref);
    struct ast_json *json_transferer1, *json_transferer2, *json_bridge, *json_channel;
    struct ast_json *json_transferee = NULL, *json_target = NULL;
    const struct timeval *tv = stasis_message_timestamp(msg);
    int res = 0;
    json_transferer1 = ast_channel_snapshot_to_json(transfer_msg->to_transferee.channel_snapshot, sanitize);
    if (!json_transferer1) {
       return NULL;
    }
    json_transferer2 = ast_channel_snapshot_to_json(transfer_msg->to_transfer_target.channel_snapshot, sanitize);
    if (!json_transferer2) {
       ast_json_unref(json_transferer1);
       return NULL;
    }
    if (transfer_msg->transferee) {
       json_transferee = ast_channel_snapshot_to_json(transfer_msg->transferee, sanitize);
       if (!json_transferee) {
          ast_json_unref(json_transferer2);
          ast_json_unref(json_transferer1);
          return NULL;
       }
    }
    if (transfer_msg->target) {
       json_target = ast_channel_snapshot_to_json(transfer_msg->target, sanitize);
       if (!json_target) {
          ast_json_unref(json_transferee);
          ast_json_unref(json_transferer2);
          ast_json_unref(json_transferer1);
          return NULL;
       }
    }
    out = ast_json_pack("{s: s, s: o, s: o, s: o, s: s, s: o}",
       "type", "BridgeAttendedTransfer",
       "timestamp", ast_json_timeval(*tv, NULL),
       "transferer_first_leg", json_transferer1,
       "transferer_second_leg", json_transferer2,
       "result", result_strs[transfer_msg->result],
       "is_external", ast_json_boolean(transfer_msg->is_external));
    if (!out) {
       ast_json_unref(json_target);
       ast_json_unref(json_transferee);
       return NULL;
    }
    if (json_transferee && ast_json_object_set(out, "transferee", json_transferee)) {
       ast_json_unref(json_target);
       return NULL;
    }
    if (json_target && ast_json_object_set(out, "transfer_target", json_target)) {
       return NULL;
    }
    if (transfer_msg->to_transferee.bridge_snapshot) {
       json_bridge = ast_bridge_snapshot_to_json(transfer_msg->to_transferee.bridge_snapshot, sanitize);
       if (!json_bridge) {
          return NULL;
       }
       res |= ast_json_object_set(out, "transferer_first_leg_bridge", json_bridge);
    }
    if (transfer_msg->to_transfer_target.bridge_snapshot) {
       json_bridge = ast_bridge_snapshot_to_json(transfer_msg->to_transfer_target.bridge_snapshot, sanitize);
       if (!json_bridge) {
          return NULL;
       }
       res |= ast_json_object_set(out, "transferer_second_leg_bridge", json_bridge);
    }
    switch (transfer_msg->dest_type) {
    case AST_ATTENDED_TRANSFER_DEST_BRIDGE_MERGE:
       res |= ast_json_object_set(out, "destination_type", ast_json_string_create("bridge"));
       res |= ast_json_object_set(out, "destination_bridge", ast_json_string_create(transfer_msg->dest.bridge));
       break;
    case AST_ATTENDED_TRANSFER_DEST_LOCAL_APP:
       res |= ast_json_object_set(out, "replace_channel", ast_channel_snapshot_to_json(transfer_msg->replace_channel, sanitize));
       /* fallthrough */
    case AST_ATTENDED_TRANSFER_DEST_APP:
       res |= ast_json_object_set(out, "destination_type", ast_json_string_create("application"));
       res |= ast_json_object_set(out, "destination_application", ast_json_string_create(transfer_msg->dest.app));
       break;
    case AST_ATTENDED_TRANSFER_DEST_LINK:
       res |= ast_json_object_set(out, "destination_type", ast_json_string_create("link"));
       json_channel = ast_channel_snapshot_to_json(transfer_msg->dest.links[0], sanitize);
       if (!json_channel) {
          return NULL;
       }
       res |= ast_json_object_set(out, "destination_link_first_leg", json_channel);
       json_channel = ast_channel_snapshot_to_json(transfer_msg->dest.links[1], sanitize);
       if (!json_channel) {
          return NULL;
       }
       res |= ast_json_object_set(out, "destination_link_second_leg", json_channel);
       break;
    case AST_ATTENDED_TRANSFER_DEST_THREEWAY:
       res |= ast_json_object_set(out, "destination_type", ast_json_string_create("threeway"));
       json_channel = ast_channel_snapshot_to_json(transfer_msg->dest.threeway.channel_snapshot, sanitize);
       if (!json_channel) {
          return NULL;
       }
       res |= ast_json_object_set(out, "destination_threeway_channel", json_channel);
       json_bridge = ast_bridge_snapshot_to_json(transfer_msg->dest.threeway.bridge_snapshot, sanitize);
       if (!json_bridge) {
          return NULL;
       }
       res |= ast_json_object_set(out, "destination_threeway_bridge", json_bridge);
       break;
    case AST_ATTENDED_TRANSFER_DEST_FAIL:
       res |= ast_json_object_set(out, "destination_type", ast_json_string_create("fail"));
       break;
    }
    if (res) {
       return NULL;
    }
    return ast_json_ref(out);
 }
blind_transfer_dtor()
static void blind_transfer_dtor (void * obj) static
Definition at line 919 of file stasis_bridges.c.
References ao2_cleanup, ast_blind_transfer_message::bridge, ast_blind_transfer_message::replace_channel, ast_blind_transfer_message::transferee, and ast_blind_transfer_message::transferer.
Referenced by ast_blind_transfer_message_create().
 {
    struct ast_blind_transfer_message *msg = obj;
    ao2_cleanup(msg->transferer);
    ao2_cleanup(msg->bridge);
    ao2_cleanup(msg->transferee);
    ao2_cleanup(msg->replace_channel);
 }
blind_transfer_to_ami()
static struct ast_manager_event_blob * blind_transfer_to_ami (struct stasis_message * message) static
Definition at line 870 of file stasis_bridges.c.
References ast_free_ptr(), ast_manager_build_bridge_state_string(), ast_manager_build_channel_state_string_prefix(), ast_manager_event_blob_create(), ast_str_buffer(), ast_blind_transfer_message::bridge, ast_blind_transfer_message::context, EVENT_FLAG_CALL, ast_blind_transfer_message::exten, ast_blind_transfer_message::is_external, NULL, RAII_VAR, ast_blind_transfer_message::result, result_strs, stasis_message_data(), ast_blind_transfer_message::transferee, and ast_blind_transfer_message::transferer.
 {
    RAII_VAR(struct ast_str *, transferer_state, NULL, ast_free_ptr);
    RAII_VAR(struct ast_str *, bridge_state, NULL, ast_free_ptr);
    RAII_VAR(struct ast_str *, transferee_state, NULL, ast_free_ptr);
    struct ast_blind_transfer_message *transfer_msg = stasis_message_data(msg);
    if (!transfer_msg) {
       return NULL;
    }
    transferer_state = ast_manager_build_channel_state_string_prefix(
          transfer_msg->transferer, "Transferer");
    if (!transferer_state) {
       return NULL;
    }
    if (transfer_msg->bridge) {
       bridge_state = ast_manager_build_bridge_state_string(transfer_msg->bridge);
       if (!bridge_state) {
          return NULL;
       }
    }
    if (transfer_msg->transferee) {
       transferee_state = ast_manager_build_channel_state_string_prefix(
             transfer_msg->transferee, "Transferee");
       if (!transferee_state) {
          return NULL;
       }
    }
    return ast_manager_event_blob_create(EVENT_FLAG_CALL, "BlindTransfer",
          "Result: %s\r\n"
          "%s"
          "%s"
          "%s"
          "IsExternal: %s\r\n"
          "Context: %s\r\n"
          "Extension: %s\r\n",
          result_strs[transfer_msg->result],
          ast_str_buffer(transferer_state),
          transferee_state ? ast_str_buffer(transferee_state) : "",
          bridge_state ? ast_str_buffer(bridge_state) : "",
          transfer_msg->is_external ? "Yes" : "No",
          transfer_msg->context,
          transfer_msg->exten);
 }
blind_transfer_to_json()
static struct ast_json * blind_transfer_to_json (struct stasis_message * msg, const struct stasis_message_sanitizer * sanitize) static
Definition at line 799 of file stasis_bridges.c.
References ast_bridge_snapshot_to_json(), ast_channel_snapshot_to_json(), ast_json_boolean(), ast_json_object_set(), ast_json_pack(), ast_json_timeval(), ast_json_unref(), ast_blind_transfer_message::bridge, ast_blind_transfer_message::context, ast_blind_transfer_message::exten, ast_blind_transfer_message::is_external, NULL, out, ast_blind_transfer_message::replace_channel, ast_blind_transfer_message::result, result_strs, stasis_message_data(), stasis_message_timestamp(), ast_blind_transfer_message::transferee, and ast_blind_transfer_message::transferer.
 {
    struct ast_blind_transfer_message *transfer_msg = stasis_message_data(msg);
    struct ast_json *json_transferer;
    struct ast_json *json_transferee = NULL;
    struct ast_json *out;
    struct ast_json *json_replace = NULL;
    const struct timeval *tv = stasis_message_timestamp(msg);
    json_transferer = ast_channel_snapshot_to_json(transfer_msg->transferer, sanitize);
    if (!json_transferer) {
       return NULL;
    }
    if (transfer_msg->transferee) {
       json_transferee = ast_channel_snapshot_to_json(transfer_msg->transferee, sanitize);
       if (!json_transferee) {
          ast_json_unref(json_transferer);
          return NULL;
       }
    }
    if (transfer_msg->replace_channel) {
       json_replace = ast_channel_snapshot_to_json(transfer_msg->replace_channel, sanitize);
       if (!json_replace) {
          ast_json_unref(json_transferee);
          ast_json_unref(json_transferer);
          return NULL;
       }
    }
    out = ast_json_pack("{s: s, s: o, s: o, s: s, s: s, s: s, s: o}",
       "type", "BridgeBlindTransfer",
       "timestamp", ast_json_timeval(*tv, NULL),
       "channel", json_transferer,
       "exten", transfer_msg->exten,
       "context", transfer_msg->context,
       "result", result_strs[transfer_msg->result],
       "is_external", ast_json_boolean(transfer_msg->is_external));
    if (!out) {
       ast_json_unref(json_transferee);
       ast_json_unref(json_replace);
       return NULL;
    }
    if (json_transferee && ast_json_object_set(out, "transferee", json_transferee)) {
       ast_json_unref(out);
       ast_json_unref(json_replace);
       return NULL;
    }
    if (json_replace && ast_json_object_set(out, "replace_channel", json_replace)) {
       ast_json_unref(out);
       return NULL;
    }
    if (transfer_msg->bridge) {
       struct ast_json *json_bridge = ast_bridge_snapshot_to_json(
             transfer_msg->bridge, sanitize);
       if (!json_bridge || ast_json_object_set(out, "bridge", json_bridge)) {
          ast_json_unref(out);
          return NULL;
       }
    }
    return out;
 }
bridge_blob_dtor()
static void bridge_blob_dtor (void * obj) static
Definition at line 489 of file stasis_bridges.c.
References ao2_cleanup, ast_json_unref(), and NULL.
Referenced by ast_bridge_blob_create(), and ast_bridge_blob_create_from_snapshots().
 {
    struct ast_bridge_blob *event = obj;
    ao2_cleanup(event->bridge);
    event->bridge = NULL;
    ao2_cleanup(event->channel);
    event->channel = NULL;
    ast_json_unref(event->blob);
    event->blob = NULL;
 }
bridge_channel_snapshot_pair_cleanup()
static void bridge_channel_snapshot_pair_cleanup (struct ast_bridge_channel_snapshot_pair * pair) static
Definition at line 786 of file stasis_bridges.c.
References ao2_cleanup, ast_bridge_channel_snapshot_pair::bridge_snapshot, and ast_bridge_channel_snapshot_pair::channel_snapshot.
Referenced by attended_transfer_dtor().
 {
    ao2_cleanup(pair->bridge_snapshot);
    ao2_cleanup(pair->channel_snapshot);
 }
bridge_channel_snapshot_pair_init()
static int bridge_channel_snapshot_pair_init (struct ast_channel * channel, struct ast_bridge * bridge, struct ast_bridge_channel_snapshot_pair * snapshot_pair) static
Definition at line 760 of file stasis_bridges.c.
References ast_bridge_lock, ast_bridge_snapshot_create(), ast_bridge_unlock, ast_channel_snapshot_get_latest(), ast_channel_uniqueid(), ast_bridge_channel_snapshot_pair::bridge_snapshot, and ast_bridge_channel_snapshot_pair::channel_snapshot.
Referenced by ast_attended_transfer_message_create().
 {
    if (bridge) {
       ast_bridge_lock(bridge);
       snapshot_pair->bridge_snapshot = ast_bridge_snapshot_create(bridge);
       ast_bridge_unlock(bridge);
       if (!snapshot_pair->bridge_snapshot) {
          return -1;
       }
    }
    snapshot_pair->channel_snapshot = ast_channel_snapshot_get_latest(ast_channel_uniqueid(channel));
    if (!snapshot_pair->channel_snapshot) {
       return -1;
    }
    return 0;
 }
bridge_merge_message_create()
static struct ast_bridge_merge_message* bridge_merge_message_create (struct ast_bridge * to, struct ast_bridge * from) static
Bridge merge message creation helper.
Definition at line 418 of file stasis_bridges.c.
References ao2_alloc, ao2_ref, ast_bridge_snapshot_create(), bridge_merge_message_dtor(), ast_bridge_merge_message::from, NULL, and ast_bridge_merge_message::to.
Referenced by ast_bridge_publish_merge().
 {
    struct ast_bridge_merge_message *msg;
    msg = ao2_alloc(sizeof(*msg), bridge_merge_message_dtor);
    if (!msg) {
       return NULL;
    }
    msg->to = ast_bridge_snapshot_create(to);
    msg->from = ast_bridge_snapshot_create(from);
    if (!msg->to || !msg->from) {
       ao2_ref(msg, -1);
       return NULL;
    }
    return msg;
 }
bridge_merge_message_dtor()
static void bridge_merge_message_dtor (void * obj) static
Destructor for bridge merge messages.
Definition at line 407 of file stasis_bridges.c.
References ao2_cleanup, ast_bridge_merge_message::from, NULL, and ast_bridge_merge_message::to.
Referenced by bridge_merge_message_create().
 {
    struct ast_bridge_merge_message *msg = obj;
    ao2_cleanup(msg->to);
    msg->to = NULL;
    ao2_cleanup(msg->from);
    msg->from = NULL;
 }
bridge_publish_state_from_blob()
static void bridge_publish_state_from_blob (struct ast_bridge * bridge, struct ast_bridge_blob * obj) static
Definition at line 381 of file stasis_bridges.c.
References ao2_bump, ao2_cleanup, ao2_ref, ast_assert, ast_bridge_snapshot_type(), ast_bridge_topic(), ast_bridge_blob::bridge, bridge_snapshot_update_create(), ast_bridge::current_snapshot, NULL, stasis_message_create(), stasis_publish(), and update().
Referenced by ast_bridge_publish_enter(), and ast_bridge_publish_leave().
 {
    struct ast_bridge_snapshot_update *update;
    struct stasis_message *msg;
    ast_assert(obj != NULL);
    update = bridge_snapshot_update_create(bridge->current_snapshot, obj->bridge);
    ao2_cleanup(bridge->current_snapshot);
    bridge->current_snapshot = ao2_bump(obj->bridge);
    if (!update) {
       return;
    }
    msg = stasis_message_create(ast_bridge_snapshot_type(), update);
    ao2_ref(update, -1);
    if (!msg) {
       return;
    }
    stasis_publish(ast_bridge_topic(bridge), msg);
    ao2_ref(msg, -1);
 }
bridge_snapshot_dtor()
static void bridge_snapshot_dtor (void * obj) static
Destructor for bridge snapshots.
Definition at line 194 of file stasis_bridges.c.
References ao2_cleanup, ast_string_field_free_memory, ast_bridge_snapshot::channels, and NULL.
Referenced by ast_bridge_snapshot_create().
 {
    struct ast_bridge_snapshot *snapshot = obj;
    ast_string_field_free_memory(snapshot);
    ao2_cleanup(snapshot->channels);
    snapshot->channels = NULL;
 }
bridge_snapshot_update_create()
static struct ast_bridge_snapshot_update* bridge_snapshot_update_create (struct ast_bridge_snapshot * old, struct ast_bridge_snapshot * new) static
Definition at line 275 of file stasis_bridges.c.
References AO2_ALLOC_OPT_LOCK_NOLOCK, ao2_alloc_options, ao2_bump, ast_debug, bridge_snapshot_update_dtor(), ast_bridge_snapshot_update::new_snapshot, NULL, ast_bridge_snapshot_update::old_snapshot, ast_bridge_snapshot::uniqueid, and update().
Referenced by ast_bridge_publish_state(), bridge_publish_state_from_blob(), and bridge_topics_destroy().
 {
    struct ast_bridge_snapshot_update *update;
    update = ao2_alloc_options(sizeof(*update), bridge_snapshot_update_dtor,
          AO2_ALLOC_OPT_LOCK_NOLOCK);
    if (!update) {
       return NULL;
    }
    update->old_snapshot = ao2_bump(old);
    update->new_snapshot = ao2_bump(new);
    ast_debug(3, "Update: %p  Old: %s  New: %s\n", update,
       update->old_snapshot ? update->old_snapshot->uniqueid : "<none>",
       update->new_snapshot ? update->new_snapshot->uniqueid : "<none>");
    return update;
 }
bridge_snapshot_update_dtor()
static void bridge_snapshot_update_dtor (void * obj) static
Definition at line 264 of file stasis_bridges.c.
References ao2_cleanup, ast_debug, ast_bridge_snapshot_update::new_snapshot, ast_bridge_snapshot_update::old_snapshot, ast_bridge_snapshot::uniqueid, and update().
Referenced by bridge_snapshot_update_create().
 {
    struct ast_bridge_snapshot_update *update = obj;
    ast_debug(3, "Update: %p  Old: %s  New: %s\n", update,
       update->old_snapshot ? update->old_snapshot->uniqueid : "<none>",
       update->new_snapshot ? update->new_snapshot->uniqueid : "<none>");
    ao2_cleanup(update->old_snapshot);
    ao2_cleanup(update->new_snapshot);
 }
bridge_topics_destroy()
void bridge_topics_destroy (struct ast_bridge * bridge)
Definition at line 319 of file stasis_bridges.c.
References ao2_ref, ast_assert, ast_bridge_snapshot_create(), ast_bridge_snapshot_type(), ast_bridge_topic(), bridge_snapshot_update_create(), ast_bridge::current_snapshot, NULL, stasis_message_create(), stasis_publish(), stasis_topic_name(), stasis_topic_pool_delete_topic(), and update().
Referenced by destroy_bridge().
 {
    struct ast_bridge_snapshot_update *update;
    struct stasis_message *msg;
    ast_assert(bridge != NULL);
    if (!bridge->current_snapshot) {
       bridge->current_snapshot = ast_bridge_snapshot_create(bridge);
       if (!bridge->current_snapshot) {
          return;
       }
    }
    update = bridge_snapshot_update_create(bridge->current_snapshot, NULL);
    if (!update) {
       return;
    }
    msg = stasis_message_create(ast_bridge_snapshot_type(), update);
    ao2_ref(update, -1);
    if (!msg) {
       return;
    }
    stasis_publish(ast_bridge_topic(bridge), msg);
    ao2_ref(msg, -1);
    stasis_topic_pool_delete_topic(bridge_topic_pool, stasis_topic_name(ast_bridge_topic(bridge)));
 }
bridge_topics_init()
int bridge_topics_init (struct ast_bridge * bridge)
Definition at line 295 of file stasis_bridges.c.
References ast_asprintf, ast_free, ast_log, ast_strlen_zero, LOG_ERROR, stasis_topic_pool_get_topic(), ast_bridge::topic, and ast_bridge::uniqueid.
Referenced by bridge_base_init().
 {
    char *topic_name;
    int ret;
    if (ast_strlen_zero(bridge->uniqueid)) {
       ast_log(LOG_ERROR, "Bridge id initialization required\n");
       return -1;
    }
    ret = ast_asprintf(&topic_name, "bridge:%s", bridge->uniqueid);
    if (ret < 0) {
       return -1;
    }
    bridge->topic = stasis_topic_pool_get_topic(bridge_topic_pool, topic_name);
    ast_free(topic_name);
    if (!bridge->topic) {
       return -1;
    }
    return 0;
 }
capability2str()
static const char* capability2str (uint32_t capabilities) static
Definition at line 703 of file stasis_bridges.c.
References AST_BRIDGE_CAPABILITY_HOLDING.
Referenced by ast_bridge_snapshot_to_json().
 {
    if (capabilities & AST_BRIDGE_CAPABILITY_HOLDING) {
       return "holding";
    } else {
       return "mixing";
    }
 }
container_to_json_array()
static struct ast_json* container_to_json_array (struct ao2_container * items, const struct stasis_message_sanitizer * sanitize) static
Definition at line 673 of file stasis_bridges.c.
References ao2_cleanup, ao2_iterator_destroy(), ao2_iterator_init(), ao2_iterator_next, ast_json_array_append(), ast_json_array_create(), ast_json_string_create(), ast_json_unref(), stasis_message_sanitizer::channel_id, item, and NULL.
Referenced by ast_bridge_snapshot_to_json().
 {
    struct ast_json *json_items = ast_json_array_create();
    char *item;
    struct ao2_iterator it;
    if (!json_items) {
       return NULL;
    }
    for (it = ao2_iterator_init(items, 0);
       (item = ao2_iterator_next(&it)); ao2_cleanup(item)) {
       if (sanitize && sanitize->channel_id && sanitize->channel_id(item)) {
          continue;
       }
       if (ast_json_array_append(json_items, ast_json_string_create(item))) {
          ao2_cleanup(item);
          ao2_iterator_destroy(&it);
          ast_json_unref(json_items);
          return NULL;
       }
    }
    ao2_iterator_destroy(&it);
    return json_items;
 }
simple_bridge_channel_event()
static struct ast_json* simple_bridge_channel_event (const char * type, struct ast_bridge_snapshot * bridge_snapshot, struct ast_channel_snapshot * channel_snapshot, const struct timeval * tv, const struct stasis_message_sanitizer * sanitize) static
Definition at line 629 of file stasis_bridges.c.
References ast_bridge_snapshot_to_json(), ast_channel_snapshot_to_json(), ast_json_pack(), ast_json_timeval(), ast_json_unref(), and NULL.
Referenced by ast_channel_entered_bridge_to_json(), and ast_channel_left_bridge_to_json().
 {
    struct ast_json *json_bridge = ast_bridge_snapshot_to_json(bridge_snapshot, sanitize);
    struct ast_json *json_channel = ast_channel_snapshot_to_json(channel_snapshot, sanitize);
    if (!json_bridge || !json_channel) {
       ast_json_unref(json_bridge);
       ast_json_unref(json_channel);
       return NULL;
    }
    return ast_json_pack("{s: s, s: o, s: o, s: o}",
       "type", type,
       "timestamp", ast_json_timeval(*tv, NULL),
       "bridge", json_bridge,
       "channel", json_channel);
 }
stasis_bridging_cleanup()
static void stasis_bridging_cleanup (void) static
Definition at line 1392 of file stasis_bridges.c.
References ao2_cleanup, ast_attended_transfer_type(), ast_blind_transfer_type(), ast_bridge_merge_message_type(), ast_bridge_snapshot_type(), ast_channel_entered_bridge_type(), ast_channel_left_bridge_type(), NULL, and STASIS_MESSAGE_TYPE_CLEANUP.
Referenced by ast_stasis_bridging_init().
 {
    STASIS_MESSAGE_TYPE_CLEANUP(ast_bridge_snapshot_type);
    STASIS_MESSAGE_TYPE_CLEANUP(ast_bridge_merge_message_type);
    STASIS_MESSAGE_TYPE_CLEANUP(ast_channel_entered_bridge_type);
    STASIS_MESSAGE_TYPE_CLEANUP(ast_channel_left_bridge_type);
    STASIS_MESSAGE_TYPE_CLEANUP(ast_blind_transfer_type);
    STASIS_MESSAGE_TYPE_CLEANUP(ast_attended_transfer_type);
    ao2_cleanup(bridge_topic_pool);
    bridge_topic_pool = NULL;
    ao2_cleanup(bridge_topic_all);
    bridge_topic_all = NULL;
 }
STASIS_MESSAGE_TYPE_DEFN() [1/6]
STASIS_MESSAGE_TYPE_DEFN (ast_bridge_snapshot_type)
Define bridge message types.
STASIS_MESSAGE_TYPE_DEFN() [2/6]
STASIS_MESSAGE_TYPE_DEFN (ast_bridge_merge_message_type , . to_json = ast_bridge_merge_message_to_json)
STASIS_MESSAGE_TYPE_DEFN() [3/6]
STASIS_MESSAGE_TYPE_DEFN (ast_channel_entered_bridge_type , . to_json = ast_channel_entered_bridge_to_json)
STASIS_MESSAGE_TYPE_DEFN() [4/6]
STASIS_MESSAGE_TYPE_DEFN (ast_channel_left_bridge_type , . to_json = ast_channel_left_bridge_to_json)
STASIS_MESSAGE_TYPE_DEFN() [5/6]
STASIS_MESSAGE_TYPE_DEFN (ast_blind_transfer_type , . to_json = blind_transfer_to_json, . to_ami = blind_transfer_to_ami)
STASIS_MESSAGE_TYPE_DEFN() [6/6]
STASIS_MESSAGE_TYPE_DEFN (ast_attended_transfer_type , . to_json = attended_transfer_to_json, . to_ami = attended_transfer_to_ami)
Variable Documentation
bridge_topic_all
struct stasis_topic* bridge_topic_all static
Definition at line 158 of file stasis_bridges.c.
Referenced by ast_bridge_topic_all().
bridge_topic_pool
struct stasis_topic_pool* bridge_topic_pool static
Definition at line 159 of file stasis_bridges.c.
result_strs
const char* result_strs[] static
Definition at line 792 of file stasis_bridges.c.
Referenced by attended_transfer_to_ami(), attended_transfer_to_json(), blind_transfer_to_ami(), and blind_transfer_to_json().