Asterisk - The Open Source Telephony Project: localtime.h File Reference
localtime.h File Reference
Custom localtime functions for multiple timezones.
#include <locale.h>
Data Structures
struct ast_tm
Macros
#define AST_ISO8601_FORMAT "%FT%T.%q%z"
ast_strftime for ISO8601 formatting timestamps.
#define AST_ISO8601_LEN 29
Max length of an null terminated, millisecond resolution, ISO8601 timestamp string.
Typedefs
typedef void * locale_t
Functions
void ast_get_dst_info (const time_t *const timep, int *dst_enabled, time_t *dst_start, time_t *dst_end, int *gmt_off, const char *const zone)
struct ast_tm * ast_localtime (const struct timeval *timep, struct ast_tm *p_tm, const char *zone)
Timezone-independent version of localtime_r(3).
void ast_localtime_wakeup_monitor (struct ast_test *info)
struct timeval ast_mktime (struct ast_tm *const tmp, const char *zone)
Timezone-independent version of mktime(3).
const char * ast_setlocale (const char *locale)
Set the thread-local representation of the current locale.
int ast_strftime (char *buf, size_t len, const char *format, const struct ast_tm *tm)
Special version of strftime(3) that handles fractions of a second. Takes the same arguments as strftime(3), with the addition of q, which specifies microseconds.
int ast_strftime_locale (char *buf, size_t len, const char *format, const struct ast_tm *tm, const char *locale)
char * ast_strptime (const char *s, const char *format, struct ast_tm *tm)
Special version of strptime(3) which places the answer in the common structure ast_tm. Also, unlike strptime(3), ast_strptime() initializes its memory prior to use.
char * ast_strptime_locale (const char *s, const char *format, struct ast_tm *tm, const char *locale)
Detailed Description
Custom localtime functions for multiple timezones.
Definition in file localtime.h.
Macro Definition Documentation
AST_ISO8601_FORMAT
#define AST_ISO8601_FORMAT "%FT%T.%q%z"
ast_strftime for ISO8601 formatting timestamps.
Definition at line 103 of file localtime.h.
Referenced by ast_json_timeval().
AST_ISO8601_LEN
#define AST_ISO8601_LEN 29
Max length of an null terminated, millisecond resolution, ISO8601 timestamp string.
Definition at line 105 of file localtime.h.
Referenced by ast_json_timeval().
Typedef Documentation
locale_t
typedef void* locale_t
Definition at line 32 of file localtime.h.
Function Documentation
ast_get_dst_info()
void ast_get_dst_info (const time_t *const timep, int * dst_enabled, time_t * dst_start, time_t * dst_end, int * gmt_off, const char *const zone)
Definition at line 1754 of file localtime.c.
References ast_tzset(), state::ats, AVGSECSPERYEAR, state::goahead, state::goback, int_fast64_t, NULL, state::timecnt, ttinfo::tt_gmtoff, ttinfo::tt_isdst, state::ttis, state::typecnt, state::types, and YEARSPERREPEAT.
Referenced by set_timezone_variables().
 {
    int i;
    int transition1 = -1;
    int transition2 = -1;
    time_t      seconds;
    int  bounds_exceeded = 0;
    time_t  t = *timep;
    const struct state *sp;
    if (NULL == dst_enabled)
       return;
    *dst_enabled = 0;
    if (NULL == dst_start || NULL == dst_end || NULL == gmt_off)
       return;
    *gmt_off = 0;
    sp = ast_tzset(zone);
    if (NULL == sp)
       return;
    /* If the desired time exceeds the bounds of the defined time transitions
    * then give up on determining DST info and simply look for gmt offset
    * This requires that I adjust the given time using increments of Gregorian
    * repeats to place the time within the defined time transitions in the
    * timezone structure.
    */
    if ((sp->goback && t < sp->ats[0]) ||
          (sp->goahead && t > sp->ats[sp->timecnt - 1])) {
       time_t      tcycles;
       int_fast64_t   icycles;
       if (t < sp->ats[0])
          seconds = sp->ats[0] - t;
       else  seconds = t - sp->ats[sp->timecnt - 1];
       --seconds;
       tcycles = seconds / YEARSPERREPEAT / AVGSECSPERYEAR;
       ++tcycles;
       icycles = tcycles;
       if (tcycles - icycles >= 1 || icycles - tcycles >= 1)
          return;
       seconds = icycles;
       seconds *= YEARSPERREPEAT;
       seconds *= AVGSECSPERYEAR;
       if (t < sp->ats[0])
          t += seconds;
       else
          t -= seconds;
       if (t < sp->ats[0] || t > sp->ats[sp->timecnt - 1])
          return;  /* "cannot happen" */
       bounds_exceeded = 1;
    }
    if (sp->timecnt == 0 || t < sp->ats[0]) {
       /* I have no transition times or I'm before time */
       *dst_enabled = 0;
       /* Find where I can get gmtoff */
       i = 0;
       while (sp->ttis[i].tt_isdst) {
          if (++i >= sp->typecnt) {
             i = 0;
             break;
          }
       }
       *gmt_off = sp->ttis[i].tt_gmtoff;
       return;
    }
    for (i = 1; i < sp->timecnt; ++i) {
       if (t < sp->ats[i]) {
          transition1 = sp->types[i - 1];
          transition2 = sp->types[i];
          break;
       }
    }
    /* if I found transition times that do not bounded the given time and these correspond to
       or the bounding zones do not reflect a changes in day light savings, then I do not have dst active */
    if (i >= sp->timecnt || 0 > transition1 || 0 > transition2 ||
          (sp->ttis[transition1].tt_isdst == sp->ttis[transition2].tt_isdst)) {
       *dst_enabled = 0;
       *gmt_off = sp->ttis[sp->types[sp->timecnt -1]].tt_gmtoff;
    } else {
       /* I have valid daylight savings information. */
       if(sp->ttis[transition2].tt_isdst)
          *gmt_off = sp->ttis[transition1].tt_gmtoff;
       else
          *gmt_off = sp->ttis[transition2].tt_gmtoff;
       /* If I adjusted the time earlier, indicate that the dst is invalid */
       if (!bounds_exceeded) {
          *dst_enabled = 1;
          /* Determine which of the bounds is the start of daylight savings and which is the end */
          if(sp->ttis[transition2].tt_isdst) {
             *dst_start = sp->ats[i];
             *dst_end = sp->ats[i -1];
          } else {
             *dst_start = sp->ats[i -1];
             *dst_end = sp->ats[i];
          }
       }
    }
    return;
 }
ast_localtime()
struct ast_tm* ast_localtime (const struct timeval * timep, struct ast_tm * p_tm, const char * zone)
Timezone-independent version of localtime_r(3).
Parameters
timep Current time, including microseconds
p_tm Pointer to memory where the broken-out time will be stored
zone Text string of a standard system zoneinfo file. If NULL, the system localtime will be used.
Return values
p_tm is returned for convenience
Definition at line 1739 of file localtime.c.
References ast_tzset(), localsub(), and NULL.
Referenced by acf_strftime(), action_corestatus(), append_date(), ast_cel_fabricate_channel_from_event(), ast_check_timing2(), ast_http_send(), ast_json_timeval(), ast_queue_log(), ast_say_date_da(), ast_say_date_de(), ast_say_date_en(), ast_say_date_fr(), ast_say_date_gr(), ast_say_date_he(), ast_say_date_hu(), ast_say_date_is(), ast_say_date_ja(), ast_say_date_ka(), ast_say_date_nl(), ast_say_date_pt(), ast_say_date_th(), ast_say_date_with_format_da(), ast_say_date_with_format_de(), ast_say_date_with_format_en(), ast_say_date_with_format_es(), ast_say_date_with_format_fr(), ast_say_date_with_format_gr(), ast_say_date_with_format_he(), ast_say_date_with_format_is(), ast_say_date_with_format_it(), ast_say_date_with_format_ja(), ast_say_date_with_format_nl(), ast_say_date_with_format_pl(), ast_say_date_with_format_pt(), ast_say_date_with_format_th(), ast_say_date_with_format_vi(), ast_say_date_with_format_zh(), ast_say_datetime_de(), ast_say_datetime_en(), ast_say_datetime_fr(), ast_say_datetime_from_now_en(), ast_say_datetime_from_now_fr(), ast_say_datetime_from_now_he(), ast_say_datetime_from_now_ka(), ast_say_datetime_from_now_pt(), ast_say_datetime_gr(), ast_say_datetime_he(), ast_say_datetime_hu(), ast_say_datetime_ja(), ast_say_datetime_ka(), ast_say_datetime_nl(), ast_say_datetime_pt(), ast_say_datetime_pt_BR(), ast_say_datetime_th(), ast_say_datetime_zh(), ast_say_time_de(), ast_say_time_en(), ast_say_time_fr(), ast_say_time_gr(), ast_say_time_he(), ast_say_time_hu(), ast_say_time_ja(), ast_say_time_ka(), ast_say_time_nl(), ast_say_time_pt(), ast_say_time_pt_BR(), ast_say_time_th(), ast_say_time_zh(), AST_TEST_DEFINE(), beanstalk_put(), build_device(), build_radius_record(), callerid_genmsg(), cdr_get_tv(), cdr_read_callback(), cel_bs_put(), cli_prompt(), cli_show_tasks(), conf_run(), enc_ie_date(), epoch_to_string(), exchangecal_get_events_between(), execute_cb(), find_conf_realtime(), format_log_message_ap(), get_date(), get_ewscal_ids_for(), handle_cli_odbc_show(), handle_cli_test_locales(), handle_minivm_show_stats(), handle_show_settings(), http_callback(), iax2_datetime(), isodate(), leave_voicemail(), main(), make_email_file(), make_logchannel(), manager_log(), mstime(), mysql_log(), odbc_log(), packdate(), pgsql_log(), phone_call(), play_message_datetime(), prep_email_sub_vars(), prometheus_show_status(), rt_extend_conf(), say_date_generic(), send_date_time(), send_date_time2(), send_date_time3(), sendmail(), set_header(), set_timezone_variables(), sip_show_registry(), sms_compose2(), sms_handleincoming_proto2(), static_callback(), timeout_write(), transmit_definetimedate(), transmit_notify_request_with_callerid(), vmu_tm(), write_history(), and write_metadata().
 {
    const struct state *sp = ast_tzset(zone);
    memset(tmp, 0, sizeof(*tmp));
    return sp ? localsub(timep, 0L, tmp, sp) : NULL;
 }
ast_localtime_wakeup_monitor()
void ast_localtime_wakeup_monitor (struct ast_test * info)
Definition at line 795 of file localtime.c.
References ast_cond_timedwait, AST_LIST_LOCK, AST_LIST_UNLOCK, AST_PTHREADT_NULL, ast_tvnow(), sip_to_pjsip::info(), lock, and NULL.
Referenced by AST_TEST_DEFINE().
 {
    struct timeval wait_now = ast_tvnow();
    struct timespec wait_time = { .tv_sec = wait_now.tv_sec + 2, .tv_nsec = wait_now.tv_usec * 1000 };
    if (inotify_thread != AST_PTHREADT_NULL) {
       AST_LIST_LOCK(&zonelist);
 #ifdef TEST_FRAMEWORK
       test = info;
 #endif
       pthread_kill(inotify_thread, SIGURG);
       ast_cond_timedwait(&initialization, &(&zonelist)->lock, &wait_time);
 #ifdef TEST_FRAMEWORK
       test = NULL;
 #endif
       AST_LIST_UNLOCK(&zonelist);
    }
 }
ast_mktime()
struct timeval ast_mktime (struct ast_tm *const tmp, const char * zone)
Timezone-independent version of mktime(3).
Parameters
tmp Current broken-out time, including microseconds
zone Text string of a standard system zoneinfo file. If NULL, the system localtime will be used.
Return values
A structure containing both seconds and fractional thereof since January 1st, 1970 UTC
Definition at line 2357 of file localtime.c.
References ast_tzset(), localsub(), and time1().
Referenced by acf_strptime(), conf_run(), find_conf_realtime(), icalfloat_to_timet(), mstime_to_time_t(), rt_extend_conf(), sms_handleincoming_proto2(), sms_readfile(), testtime_write(), and unpackdate().
 {
    const struct state *sp;
    if (!(sp = ast_tzset(zone)))
       return WRONG;
    return time1(tmp, localsub, 0L, sp);
 }
ast_setlocale()
const char* ast_setlocale (const char * locale)
Set the thread-local representation of the current locale.
Definition at line 2420 of file localtime.c.
References ast_calloc, AST_LIST_INSERT_TAIL, AST_LIST_LOCK, AST_LIST_UNLOCK, find_by_name(), locale_entry::list, locale_entry::locale, locale_entry::name, NULL, and store_by_locale().
Referenced by ast_strftime_locale(), ast_strptime_locale(), and handle_cli_test_locales().
 {
    struct locale_entry *cur;
    locale_t prevlocale = LC_GLOBAL_LOCALE;
    if (locale == NULL) {
       return store_by_locale(uselocale(LC_GLOBAL_LOCALE));
    }
    AST_LIST_LOCK(&localelist);
    if ((cur = find_by_name(locale))) {
       prevlocale = uselocale(cur->locale);
    }
    if (!cur) {
       if ((cur = ast_calloc(1, sizeof(*cur) + strlen(locale) + 1))) {
          cur->locale = newlocale(LC_ALL_MASK, locale, NULL);
          strcpy(cur->name, locale); /* SAFE */
          AST_LIST_INSERT_TAIL(&localelist, cur, list);
          prevlocale = uselocale(cur->locale);
       }
    }
    AST_LIST_UNLOCK(&localelist);
    return store_by_locale(prevlocale);
 }
ast_strftime()
int ast_strftime (char * buf, size_t len, const char * format, const struct ast_tm * tm)
Special version of strftime(3) that handles fractions of a second. Takes the same arguments as strftime(3), with the addition of q, which specifies microseconds.
Parameters
buf Address in memory where the resulting string will be stored.
len Size of the chunk of memory buf.
format A string specifying the format of time to be placed into buf.
tm Pointer to the broken out time to be used for the format.
Return values
An integer value specifying the number of bytes placed into buf or -1 on error.
Definition at line 2524 of file localtime.c.
References ast_strftime_locale(), and NULL.
Referenced by acf_strftime(), action_corestatus(), append_date(), ast_cel_fabricate_channel_from_event(), ast_http_send(), ast_json_timeval(), ast_queue_log(), beanstalk_put(), build_radius_record(), cdr_get_tv(), cdr_read_callback(), cel_bs_put(), cli_prompt(), cli_show_tasks(), conf_run(), dump_datetime(), epoch_to_string(), exchangecal_get_events_between(), execute_cb(), find_conf_realtime(), format_log_message_ap(), get_date(), get_ewscal_ids_for(), handle_cli_odbc_show(), handle_cli_test_locales(), handle_minivm_show_stats(), handle_show_settings(), http_callback(), isodate(), leave_voicemail(), make_email_file(), make_logchannel(), manager_log(), mstime(), mysql_log(), odbc_log(), pgsql_log(), prometheus_show_status(), rt_extend_conf(), sendmail(), sendpage(), set_header(), sip_show_registry(), static_callback(), timeout_write(), and write_metadata().
 {
    return ast_strftime_locale(buf, len, tmp, tm, NULL);
 }
ast_strftime_locale()
int ast_strftime_locale (char * buf, size_t len, const char * format, const struct ast_tm * tm, const char * locale)
Definition at line 2452 of file localtime.c.
References ast_calloc, ast_free, ast_realloc, ast_setlocale(), format, ast_tm::tm_usec, and tmp().
Referenced by ast_strftime(), make_email_file(), prep_email_sub_vars(), and sendpage().
 {
    size_t fmtlen = strlen(tmp) + 1;
    char *format = ast_calloc(1, fmtlen), *fptr = format, *newfmt;
    int decimals = -1, i, res;
    long fraction;
    const char *prevlocale;
    buf[0] = '\0';/* Ensure the buffer is initialized. */
    if (!format) {
       return -1;
    }
    for (; *tmp; tmp++) {
       if (*tmp == '%') {
          switch (tmp[1]) {
          case '1':
          case '2':
          case '3':
          case '4':
          case '5':
          case '6':
             if (tmp[2] != 'q') {
                goto defcase;
             }
             decimals = tmp[1] - '0';
             tmp++;
             /* Fall through */
          case 'q': /* Milliseconds */
             if (decimals == -1) {
                decimals = 3;
             }
             /* Juggle some memory to fit the item */
             newfmt = ast_realloc(format, fmtlen + decimals);
             if (!newfmt) {
                ast_free(format);
                return -1;
             }
             fptr = fptr - format + newfmt;
             format = newfmt;
             fmtlen += decimals;
             /* Reduce the fraction of time to the accuracy needed */
             for (i = 6, fraction = tm->tm_usec; i > decimals; i--) {
                fraction /= 10;
             }
             fptr += sprintf(fptr, "%0*ld", decimals, fraction);
             /* Reset, in case more than one 'q' specifier exists */
             decimals = -1;
             tmp++;
             break;
          default:
             goto defcase;
          }
       } else {
 defcase: *fptr++ = *tmp;
       }
    }
    *fptr = '\0';
 #undef strftime
    if (locale) {
       prevlocale = ast_setlocale(locale);
    }
    res = (int)strftime(buf, len, format, (struct tm *)tm);
    if (locale) {
       ast_setlocale(prevlocale);
    }
    ast_free(format);
    return res;
 }
ast_strptime()
char* ast_strptime (const char * s, const char * format, struct ast_tm * tm)
Special version of strptime(3) which places the answer in the common structure ast_tm. Also, unlike strptime(3), ast_strptime() initializes its memory prior to use.
Parameters
s A string specifying some portion of a date and time.
format The format in which the string, s, is expected.
tm The broken-out time structure into which the parsed data is expected.
Return values
A pointer to the first character within s not used to parse the date and time.
Definition at line 2550 of file localtime.c.
References ast_strptime_locale(), and NULL.
Referenced by acf_strptime(), conf_run(), find_conf_realtime(), mstime_to_time_t(), rt_extend_conf(), and testtime_write().
 {
    return ast_strptime_locale(s, format, tm, NULL);
 }
ast_strptime_locale()
char* ast_strptime_locale (const char * s, const char * format, struct ast_tm * tm, const char * locale)
Definition at line 2529 of file localtime.c.
References ast_setlocale(), ast_tm::tm_isdst, and ast_tm::tm_usec.
Referenced by ast_strptime().
 {
    struct tm tm2 = { 0, };
    char *res;
    const char *prevlocale;
    prevlocale = ast_setlocale(locale);
    res = strptime(s, format, &tm2);
    ast_setlocale(prevlocale);
    /* ast_time and tm are not the same size - tm is a subset of
     * ast_time.  Hence, the size of tm needs to be used for the
     * memcpy
     */
    memcpy(tm, &tm2, sizeof(tm2));
    tm->tm_usec = 0;
    /* strptime(3) doesn't set .tm_isdst correctly, so to force ast_mktime(3)
     * to deal with it correctly, we set it to -1. */
    tm->tm_isdst = -1;
    return res;
 }