Asterisk - The Open Source Telephony Project: format_mp3.c File Reference
format_mp3.c File Reference
Module: Media File Formats
MP3 Format Handler.
#include "asterisk.h"
#include "mp3/mpg123.h"
#include "mp3/mpglib.h"
#include "asterisk/module.h"
#include "asterisk/mod_format.h"
#include "asterisk/logger.h"
#include "asterisk/format_cache.h"
Data Structures
struct mp3_private
Macros
#define BLOCKSIZE 160
#define GAIN -4 /* 2^GAIN is the multiple to increase the volume by */
#define MP3_BUFLEN 320
#define MP3_DCACHE 8192
#define MP3_SCACHE 16384
#define OUTSCALE 4096
Functions
AST_MODULE_INFO_STANDARD_EXTENDED (ASTERISK_GPL_KEY, "MP3 format [Any rate but 8000hz mono is optimal]")
static int load_module (void)
static void mp3_close (struct ast_filestream *s)
static int mp3_dqueue (struct ast_filestream *s)
static char * mp3_getcomment (struct ast_filestream *s)
static int mp3_open (struct ast_filestream *s)
static int mp3_queue (struct ast_filestream *s)
static struct ast_frame * mp3_read (struct ast_filestream *s, int *whennext)
static int mp3_rewrite (struct ast_filestream *s, const char *comment)
static int mp3_seek (struct ast_filestream *s, off_t sample_offset, int whence)
static int mp3_squeue (struct ast_filestream *s)
static off_t mp3_tell (struct ast_filestream *s)
static int mp3_trunc (struct ast_filestream *s)
static int mp3_write (struct ast_filestream *fs, struct ast_frame *f)
static int unload_module (void)
Variables
static struct ast_format_def mp3_f
static const char name [] = "mp3"
Detailed Description
MP3 Format Handler.
Definition in file format_mp3.c.
Macro Definition Documentation
BLOCKSIZE
#define BLOCKSIZE 160
Definition at line 70 of file format_mp3.c.
GAIN
#define GAIN -4 /* 2^GAIN is the multiple to increase the volume by */
Definition at line 73 of file format_mp3.c.
MP3_BUFLEN
#define MP3_BUFLEN 320
Definition at line 45 of file format_mp3.c.
Referenced by mp3_read().
MP3_DCACHE
#define MP3_DCACHE 8192
Definition at line 47 of file format_mp3.c.
Referenced by mp3_dqueue(), and mp3_squeue().
MP3_SCACHE
#define MP3_SCACHE 16384
Definition at line 46 of file format_mp3.c.
Referenced by mp3_squeue().
OUTSCALE
#define OUTSCALE 4096
Definition at line 71 of file format_mp3.c.
Referenced by mp3_open(), and mp3_queue().
Function Documentation
AST_MODULE_INFO_STANDARD_EXTENDED()
AST_MODULE_INFO_STANDARD_EXTENDED (ASTERISK_GPL_KEY , "MP3 format " [Any rate but 8000hz mono is optimal])
Referenced by unload_module().
load_module()
static int load_module (void) static
Definition at line 317 of file format_mp3.c.
References ast_format_def_register, ast_format_slin, and ast_format_def::format.
 {
    mp3_f.format = ast_format_slin;
    InitMP3Constants();
    return ast_format_def_register(&mp3_f);
 }
mp3_close()
static void mp3_close (struct ast_filestream * s) static
Definition at line 106 of file format_mp3.c.
References ast_filestream::_private, and mp3_private::mp.
 {
    struct mp3_private *p = s->_private;
    ExitMP3(&p->mp);
    return;
 }
mp3_dqueue()
static int mp3_dqueue (struct ast_filestream * s) static
Definition at line 135 of file format_mp3.c.
References ast_filestream::_private, mp3_private::dbuf, mp3_private::dbuflen, mp3_private::dbufoffset, mp3_private::mp, MP3_DCACHE, NULL, and mp3_private::sbuflen.
Referenced by mp3_queue().
 {
    struct mp3_private *p = s->_private;
    int res=0;
    if((res = decodeMP3(&p->mp,NULL,0,p->dbuf,MP3_DCACHE,&p->dbuflen)) == MP3_OK) {
       p->sbuflen -= p->dbuflen;
       p->dbufoffset = 0;
    }
    return res;
 }
mp3_getcomment()
static char* mp3_getcomment (struct ast_filestream * s) static
Definition at line 295 of file format_mp3.c.
References NULL.
 {
    return NULL;
 }
mp3_open()
static int mp3_open (struct ast_filestream * s) static
Definition at line 98 of file format_mp3.c.
References ast_filestream::_private, mp3_private::mp, and OUTSCALE.
 {
    struct mp3_private *p = s->_private;
    InitMP3(&p->mp, OUTSCALE);
    return 0;
 }
mp3_queue()
static int mp3_queue (struct ast_filestream * s) static
Definition at line 147 of file format_mp3.c.
References ast_filestream::_private, mp3_private::dbuflen, mp3_private::dbufoffset, ast_filestream::f, mp3_private::mp, mp3_dqueue(), mp3_squeue(), mp3_private::offset, OUTSCALE, mp3_private::sbuflen, and mp3_private::seek.
Referenced by mp3_read().
 {
    struct mp3_private *p = s->_private;
    int res = 0, bytes = 0;
    if(p->seek) {
       ExitMP3(&p->mp);
       InitMP3(&p->mp, OUTSCALE);
       fseek(s->f, 0, SEEK_SET);
       p->sbuflen = p->dbuflen = p->offset = 0;
       while(p->offset < p->seek) {
          if(mp3_squeue(s))
             return -1;
          while(p->offset < p->seek && ((res = mp3_dqueue(s))) == MP3_OK) {
             for(bytes = 0 ; bytes < p->dbuflen ; bytes++) {
                p->dbufoffset++;
                p->offset++;
                if(p->offset >= p->seek)
                   break;
             }
          }
          if(res == MP3_ERR)
             return -1;
       }
       p->seek = 0;
       return 0;
    }
    if(p->dbuflen == 0) {
       if(p->sbuflen) {
          res = mp3_dqueue(s);
          if(res == MP3_ERR)
             return -1;
       }
       if(! p->sbuflen || res != MP3_OK) {
          if(mp3_squeue(s))
             return -1;
       }
    }
    return 0;
 }
mp3_read()
static struct ast_frame* mp3_read (struct ast_filestream * s, int * whennext) static
Definition at line 191 of file format_mp3.c.
References ast_filestream::_private, AST_FRAME_SET_BUFFER, AST_FRIENDLY_OFFSET, ast_filestream::buf, mp3_private::buflen, mp3_private::dbuf, mp3_private::dbuflen, mp3_private::dbufoffset, ast_filestream::fr, MP3_BUFLEN, mp3_queue(), NULL, mp3_private::offset, and ast_frame::samples.
 {
    struct mp3_private *p = s->_private;
    int delay =0;
    int save=0;
    /* Pre-populate the buffer that holds audio to be returned (dbuf) */
    if (mp3_queue(s)) {
       return NULL;
    }
    if (p->dbuflen) {
       /* Read out what's waiting in dbuf */
       for (p->buflen = 0; p->buflen < MP3_BUFLEN && p->buflen < p->dbuflen; p->buflen++) {
          s->buf[p->buflen + AST_FRIENDLY_OFFSET] = p->dbuf[p->buflen + p->dbufoffset];
       }
       p->dbufoffset += p->buflen;
       p->dbuflen -= p->buflen;
    }
    if (p->buflen < MP3_BUFLEN) {
       /* dbuf didn't have enough, so reset dbuf, fill it back up and continue */
       p->dbuflen = p->dbufoffset = 0;
       if (mp3_queue(s)) {
          return NULL;
       }
       /* Make sure dbuf has enough to complete this read attempt */
       if (p->dbuflen >= (MP3_BUFLEN - p->buflen)) {
          for (save = p->buflen; p->buflen < MP3_BUFLEN; p->buflen++) {
             s->buf[p->buflen + AST_FRIENDLY_OFFSET] = p->dbuf[(p->buflen - save) + p->dbufoffset];
          }
          p->dbufoffset += (MP3_BUFLEN - save);
          p->dbuflen -= (MP3_BUFLEN - save);
       }
    }
    p->offset += p->buflen;
    delay = p->buflen / 2;
    AST_FRAME_SET_BUFFER(&s->fr, s->buf, AST_FRIENDLY_OFFSET, p->buflen);
    s->fr.samples = delay;
    *whennext = delay;
    return &s->fr;
 }
mp3_rewrite()
static int mp3_rewrite (struct ast_filestream * s, const char * comment) static
Definition at line 275 of file format_mp3.c.
References ast_log, and LOG_ERROR.
 {
    ast_log(LOG_ERROR,"I Can't write MP3 only read them.\n");
    return -1;
 }
mp3_seek()
static int mp3_seek (struct ast_filestream * s, off_t sample_offset, int whence) static
Definition at line 248 of file format_mp3.c.
References ast_filestream::_private, ast_filestream::f, max, min, mp3_private::offset, mp3_private::seek, and SEEK_FORCECUR.
 {
    struct mp3_private *p = s->_private;
    off_t min,max,cur;
    long offset=0,samples;
    samples = sample_offset * 2;
    min = 0;
    fseek(s->f, 0, SEEK_END);
    max = ftell(s->f) * 100;
    cur = p->offset;
    if (whence == SEEK_SET)
       offset = samples + min;
    else if (whence == SEEK_CUR || whence == SEEK_FORCECUR)
       offset = samples + cur;
    else if (whence == SEEK_END)
       offset = max - samples;
    if (whence != SEEK_FORCECUR) {
       offset = (offset > max)?max:offset;
    }
    p->seek = offset;
    return fseek(s->f, offset, SEEK_SET);
 }
mp3_squeue()
static int mp3_squeue (struct ast_filestream * s) static
Definition at line 114 of file format_mp3.c.
References ast_filestream::_private, ast_log, mp3_private::dbuf, mp3_private::dbuflen, mp3_private::dbufoffset, errno, ast_filestream::f, LOG_WARNING, mp3_private::mp, MP3_DCACHE, MP3_SCACHE, mp3_private::sbuf, and mp3_private::sbuflen.
Referenced by mp3_queue().
 {
    struct mp3_private *p = s->_private;
    int res=0;
    res = ftell(s->f);
    p->sbuflen = fread(p->sbuf, 1, MP3_SCACHE, s->f);
    if (p->sbuflen < MP3_SCACHE) {
       if (ferror(s->f)) {
          ast_log(LOG_WARNING, "Error while reading MP3 file: %s\n", strerror(errno));
          return -1;
       }
    }
    res = decodeMP3(&p->mp,p->sbuf,p->sbuflen,p->dbuf,MP3_DCACHE,&p->dbuflen);
    if(res != MP3_OK)
       return -1;
    p->sbuflen -= p->dbuflen;
    p->dbufoffset = 0;
    return 0;
 }
mp3_tell()
static off_t mp3_tell (struct ast_filestream * s) static
Definition at line 288 of file format_mp3.c.
References ast_filestream::_private, and mp3_private::offset.
 {
    struct mp3_private *p = s->_private;
    return p->offset/2;
 }
mp3_trunc()
static int mp3_trunc (struct ast_filestream * s) static
Definition at line 281 of file format_mp3.c.
References ast_log, and LOG_ERROR.
 {
    ast_log(LOG_ERROR,"I Can't write MP3 only read them.\n");
    return -1;
 }
mp3_write()
static int mp3_write (struct ast_filestream * fs, struct ast_frame * f) static
Definition at line 240 of file format_mp3.c.
References ast_log, and LOG_ERROR.
 {
    ast_log(LOG_ERROR,"I Can't write MP3 only read them.\n");
    return -1;
 }
unload_module()
static int unload_module (void) static
Definition at line 324 of file format_mp3.c.
References ast_format_def_unregister(), AST_MODULE_INFO_STANDARD_EXTENDED(), ASTERISK_GPL_KEY, and name.
 {
    return ast_format_def_unregister(name);
 }
Variable Documentation
mp3_f
struct ast_format_def mp3_f static
Definition at line 300 of file format_mp3.c.
name
const char name[] = "mp3" static
Definition at line 68 of file format_mp3.c.
Referenced by unload_module().