Asterisk - The Open Source Telephony Project: config_transport.c File Reference
config_transport.c File Reference
#include "asterisk.h"
#include <math.h>
#include <pjsip.h>
#include <pjlib.h>
#include "asterisk/res_pjsip.h"
#include "asterisk/res_pjsip_cli.h"
#include "asterisk/logger.h"
#include "asterisk/astobj2.h"
#include "asterisk/sorcery.h"
#include "asterisk/acl.h"
#include "asterisk/utils.h"
#include "include/res_pjsip_private.h"
#include "asterisk/http_websocket.h"
Data Structures
struct internal_state
Macros
#define BIND_DELAY_US 100000
#define BIND_TRIES 3
#define DEFAULT_STATE_BUCKETS 53
Default number of state container buckets.
#define MAX_POINTER_STRING 33
Functions
static void __init_temp_state_store (void)
int ast_sip_destroy_sorcery_transport (void)
struct ast_sip_transport_state * ast_sip_get_transport_state (const char *transport_id)
Retrieve transport state.
struct ao2_container * ast_sip_get_transport_states (void)
Retrieves all transport states.
int ast_sip_initialize_sorcery_transport (void)
Initialize sorcery with transport support.
void ast_sip_message_apply_transport (const char *transport_name, pjsip_tx_data *tdata)
Apply the configuration for a transport to an outgoing message.
struct ast_sip_service_route_vector * ast_sip_service_route_vector_alloc (void)
Allocate a vector of service routes.
void ast_sip_service_route_vector_destroy (struct ast_sip_service_route_vector *service_routes)
Destroy a vector of service routes.
int ast_sip_transport_state_set_preferred_identity (const char *transport_name, const char *identity)
Sets the P-Preferred-Identity on a child transport.
int ast_sip_transport_state_set_service_routes (const char *transport_name, struct ast_sip_service_route_vector *service_routes)
Sets the service routes on a child transport.
int ast_sip_transport_state_set_transport (const char *transport_name, pjsip_transport *transport)
Sets the PJSIP transport on a child transport.
static int ca_list_file_to_str (const void *obj, const intptr_t *args, char **buf)
static int ca_list_path_to_str (const void *obj, const intptr_t *args, char **buf)
static int cert_file_to_str (const void *obj, const intptr_t *args, char **buf)
static struct ao2_container * cli_get_container (const char *regex)
static int cli_iterate (void *container, ao2_callback_fn callback, void *args)
static int cli_print_body (void *obj, void *arg, int flags)
static int cli_print_header (void *obj, void *arg, int flags)
static void * cli_retrieve_by_id (const char *id)
static void copy_state_to_transport (struct ast_sip_transport *transport)
static int destroy_sip_transport_state (void *data)
static struct internal_state * find_internal_state_by_transport (const struct ast_sip_transport *transport)
static struct ast_sip_transport_state * find_or_create_temporary_state (struct ast_sip_transport *transport)
static struct ast_sip_transport_state * find_state_by_transport (const struct ast_sip_transport *transport)
static struct ast_sip_transport_state * find_temporary_state (struct ast_sip_transport *transport)
static int format_ami_endpoint_transport (const struct ast_sip_endpoint *endpoint, struct ast_sip_ami *ami)
static int has_state_changed (struct ast_sip_transport_state *a, struct ast_sip_transport_state *b)
static struct internal_state * internal_state_alloc (struct ast_sip_transport *transport)
static int internal_state_cmp (void *obj, void *arg, int flags)
comparator function for state objects
static void internal_state_destroy (void *obj)
Destructor for ast_sip_transport state information.
static int internal_state_hash (const void *obj, const int flags)
hashing function for state objects
static int localnet_to_str (const void *obj, const intptr_t *args, char **buf)
static int localnet_to_vl (const void *obj, struct ast_variable **fields)
static void localnet_to_vl_append (struct ast_variable **head, struct ast_ha *ha)
static int populate_transport_states (void *obj, void *arg, int flags)
static int privkey_file_to_str (const void *obj, const intptr_t *args, char **buf)
static int remove_temporary_state (void)
static int require_client_cert_to_str (const void *obj, const intptr_t *args, char **buf)
static void set_qos (struct ast_sip_transport *transport, pj_qos_params *qos)
static void * sip_transport_alloc (const char *name)
Allocator for transport.
static void sip_transport_destroy (void *obj)
Destructor for transport.
static void sip_transport_state_destroy (void *obj)
Destructor for ast_sip_transport state information.
static int sip_transport_to_ami (const struct ast_sip_transport *transport, struct ast_str **buf)
static void states_cleanup (void *states)
static void temp_state_store_cleanup (void *data)
static int tls_method_to_str (const void *obj, const intptr_t *args, char **buf)
static int tos_to_str (const void *obj, const intptr_t *args, char **buf)
static int transport_apply (const struct ast_sorcery *sorcery, void *obj)
Apply handler for transports.
static int transport_bind_handler (const struct aco_option *opt, struct ast_variable *var, void *obj)
Custom handler for turning a string bind into a pj_sockaddr.
static int transport_bind_to_str (const void *obj, const intptr_t *args, char **buf)
static int transport_localnet_handler (const struct aco_option *opt, struct ast_variable *var, void *obj)
Helper function which turns a cipher name into an identifier.
static int transport_protocol_handler (const struct aco_option *opt, struct ast_variable *var, void *obj)
Custom handler for turning a string protocol into an enum.
static int transport_protocol_to_str (const void *obj, const intptr_t *args, char **buf)
static int transport_state_cmp (void *obj, void *arg, int flags)
comparator function for state objects
static int transport_state_hash (const void *obj, const int flags)
hashing function for state objects
static int transport_state_init (const struct aco_option *opt, struct ast_variable *var, void *obj)
Custom handler for type just makes sure the state is created.
static int transport_tls_bool_handler (const struct aco_option *opt, struct ast_variable *var, void *obj)
Custom handler for TLS boolean settings.
static int transport_tls_file_handler (const struct aco_option *opt, struct ast_variable *var, void *obj)
Custom handler for TLS method setting.
static int transport_tls_method_handler (const struct aco_option *opt, struct ast_variable *var, void *obj)
Custom handler for TLS method setting.
static int transport_tos_handler (const struct aco_option *opt, struct ast_variable *var, void *obj)
Custom handler for TOS setting.
static int verify_client_to_str (const void *obj, const intptr_t *args, char **buf)
static int verify_server_to_str (const void *obj, const intptr_t *args, char **buf)
Variables
static struct ast_cli_entry cli_commands []
static struct ast_sip_cli_formatter_entry * cli_formatter
struct ast_sip_endpoint_formatter endpoint_transport_formatter
static struct ast_threadstorage temp_state_store = { .once = PTHREAD_ONCE_INIT , .key_init = __init_temp_state_store , .custom_init = NULL , }
static const char * tls_method_map []
static struct ao2_container * transport_states
static const char * transport_types []
Macro Definition Documentation
BIND_DELAY_US
#define BIND_DELAY_US 100000
Referenced by transport_apply().
BIND_TRIES
#define BIND_TRIES 3
Referenced by transport_apply().
DEFAULT_STATE_BUCKETS
#define DEFAULT_STATE_BUCKETS 53
Default number of state container buckets.
Definition at line 39 of file config_transport.c.
Referenced by ast_sip_get_transport_states(), and ast_sip_initialize_sorcery_transport().
MAX_POINTER_STRING
#define MAX_POINTER_STRING 33
Definition at line 36 of file config_transport.c.
Function Documentation
__init_temp_state_store()
static void __init_temp_state_store (void) static
Definition at line 60 of file config_transport.c.
 {
ast_sip_destroy_sorcery_transport()
int ast_sip_destroy_sorcery_transport (void)
Definition at line 1692 of file config_transport.c.
References ao2_ref, ARRAY_LEN, ast_cli_unregister_multiple(), ast_sip_unregister_cli_formatter(), ast_sip_unregister_endpoint_formatter(), and NULL.
Referenced by ast_res_pjsip_destroy_configuration().
 {
    ast_cli_unregister_multiple(cli_commands, ARRAY_LEN(cli_commands));
    ast_sip_unregister_cli_formatter(cli_formatter);
    ast_sip_unregister_endpoint_formatter(&endpoint_transport_formatter);
    ao2_ref(transport_states, -1);
    transport_states = NULL;
    return 0;
 }
ast_sip_get_transport_state()
struct ast_sip_transport_state* ast_sip_get_transport_state (const char * transport_id)
Retrieve transport state.
Since
13.7.1
Parameters
transport_id
Returns
transport_state
Note
ao2_cleanup(...) or ao2_ref(..., -1) must be called on the returned object
Definition at line 1564 of file config_transport.c.
References ao2_bump, ao2_find, ao2_lock, ao2_ref, ao2_unlock, ast_sip_transport_state::flow, NULL, OBJ_SEARCH_KEY, internal_state::state, and ast_sip_transport_state::transport.
Referenced by ast_sip_message_apply_transport(), ast_sip_set_tpselector_from_transport(), ast_sip_transport_state_set_preferred_identity(), ast_sip_transport_state_set_service_routes(), ast_sip_transport_state_set_transport(), change_outgoing_sdp_stream_media_address(), create_rtp(), and session_outgoing_nat_hook().
 {
    struct internal_state *state = NULL;
    struct ast_sip_transport_state *trans_state;
    if (!transport_states) {
       return NULL;
    }
    state = ao2_find(transport_states, transport_id, OBJ_SEARCH_KEY);
    if (!state) {
       return NULL;
    }
    trans_state = ao2_bump(state->state);
    ao2_ref(state, -1);
    /* If this is a child transport see if the transport is actually dead */
    if (trans_state->flow) {
       ao2_lock(trans_state);
       if (trans_state->transport && trans_state->transport->is_shutdown == PJ_TRUE) {
          pjsip_transport_dec_ref(trans_state->transport);
          trans_state->transport = NULL;
       }
       ao2_unlock(trans_state);
    }
    return trans_state;
 }
ast_sip_get_transport_states()
struct ao2_container* ast_sip_get_transport_states (void)
Retrieves all transport states.
Since
13.7.1
Returns
ao2_container
Note
ao2_cleanup(...) or ao2_ref(..., -1) must be called on the returned object
Definition at line 1604 of file config_transport.c.
References AO2_ALLOC_OPT_LOCK_MUTEX, ao2_callback, ao2_container_alloc_hash, DEFAULT_STATE_BUCKETS, NULL, OBJ_MULTIPLE, OBJ_NODATA, populate_transport_states(), transport_state_cmp(), and transport_state_hash().
Referenced by anonymous_identify(), find_endpoint(), get_udp_transport(), get_write_timeout(), and process_nat().
 {
    struct ao2_container *states = ao2_container_alloc_hash(AO2_ALLOC_OPT_LOCK_MUTEX, 0,
       DEFAULT_STATE_BUCKETS, transport_state_hash, NULL, transport_state_cmp);
    if (!states) {
       return NULL;
    }
    ao2_callback(transport_states, OBJ_NODATA | OBJ_MULTIPLE, populate_transport_states, states);
    return states;
 }
ast_sip_initialize_sorcery_transport()
int ast_sip_initialize_sorcery_transport (void)
Initialize sorcery with transport support.
Definition at line 1618 of file config_transport.c.
References ao2_alloc, AO2_ALLOC_OPT_LOCK_MUTEX, ao2_cleanup, ao2_container_alloc_hash, ARRAY_LEN, ast_cli_register_multiple, AST_DEFAULT_WEBSOCKET_WRITE_TIMEOUT_STR, ast_log, AST_RETRIEVE_FLAG_ALL, AST_RETRIEVE_FLAG_MULTIPLE, ast_sip_get_sorcery(), ast_sip_register_cli_formatter(), ast_sip_register_endpoint_formatter(), ast_sorcery_apply_default, ast_sorcery_object_field_register, ast_sorcery_object_field_register_custom, ast_sorcery_object_get_id(), ast_sorcery_object_register, ast_sorcery_retrieve_by_fields(), ca_list_file_to_str(), ca_list_path_to_str(), cert_file_to_str(), cli_get_container(), cli_iterate(), cli_print_body(), cli_print_header(), cli_retrieve_by_id(), cos, DEFAULT_STATE_BUCKETS, FLDSET, ast_sip_cli_formatter_entry::get_container, ast_sip_cli_formatter_entry::get_id, internal_state_cmp(), internal_state_hash(), ast_sip_cli_formatter_entry::iterate, localnet_to_str(), localnet_to_vl(), LOG_ERROR, ast_sip_cli_formatter_entry::name, NULL, OPT_BOOL_T, OPT_INT_T, OPT_STRINGFIELD_T, OPT_UINT_T, PARSE_IN_RANGE, password, ast_sip_cli_formatter_entry::print_body, ast_sip_cli_formatter_entry::print_header, privkey_file_to_str(), require_client_cert_to_str(), ast_sip_cli_formatter_entry::retrieve_by_id, sip_transport_alloc(), sorcery, STRFLDSET, tls_method_to_str(), tos_to_str(), transport_apply(), transport_bind_handler(), transport_bind_to_str(), transport_localnet_handler(), transport_protocol_handler(), transport_protocol_to_str(), transport_state_init(), transport_tls_bool_handler(), transport_tls_file_handler(), transport_tls_method_handler(), transport_tos_handler(), verify_client_to_str(), and verify_server_to_str().
Referenced by ast_res_pjsip_initialize_configuration().
 {
    struct ast_sorcery *sorcery = ast_sip_get_sorcery();
    struct ao2_container *transports = NULL;
    /* Create outbound registration states container. */
    transport_states = ao2_container_alloc_hash(AO2_ALLOC_OPT_LOCK_MUTEX, 0,
       DEFAULT_STATE_BUCKETS, internal_state_hash, NULL, internal_state_cmp);
    if (!transport_states) {
       ast_log(LOG_ERROR, "Unable to allocate transport states container\n");
       return -1;
    }
    ast_sorcery_apply_default(sorcery, "transport", "config", "pjsip.conf,criteria=type=transport");
    if (ast_sorcery_object_register(sorcery, "transport", sip_transport_alloc, NULL, transport_apply)) {
       return -1;
    }
    /* Normally type is a OPT_NOOP_T but we're using it to make sure that state is created */
    ast_sorcery_object_field_register_custom(sorcery, "transport", "type", "", transport_state_init, NULL, NULL, 0, 0);
    ast_sorcery_object_field_register_custom(sorcery, "transport", "protocol", "udp", transport_protocol_handler, transport_protocol_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register_custom(sorcery, "transport", "bind", "", transport_bind_handler, transport_bind_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register(sorcery, "transport", "async_operations", "1", OPT_UINT_T, 0, FLDSET(struct ast_sip_transport, async_operations));
    ast_sorcery_object_field_register_custom(sorcery, "transport", "ca_list_file", "", transport_tls_file_handler, ca_list_file_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register_custom(sorcery, "transport", "ca_list_path", "", transport_tls_file_handler, ca_list_path_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register_custom(sorcery, "transport", "cert_file", "", transport_tls_file_handler, cert_file_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register_custom(sorcery, "transport", "priv_key_file", "", transport_tls_file_handler, privkey_file_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register(sorcery, "transport", "password", "", OPT_STRINGFIELD_T, 0, STRFLDSET(struct ast_sip_transport, password));
    ast_sorcery_object_field_register(sorcery, "transport", "external_signaling_address", "", OPT_STRINGFIELD_T, 0, STRFLDSET(struct ast_sip_transport, external_signaling_address));
    ast_sorcery_object_field_register(sorcery, "transport", "external_signaling_port", "0", OPT_UINT_T, PARSE_IN_RANGE, FLDSET(struct ast_sip_transport, external_signaling_port), 0, 65535);
    ast_sorcery_object_field_register(sorcery, "transport", "external_media_address", "", OPT_STRINGFIELD_T, 0, STRFLDSET(struct ast_sip_transport, external_media_address));
    ast_sorcery_object_field_register(sorcery, "transport", "domain", "", OPT_STRINGFIELD_T, 0, STRFLDSET(struct ast_sip_transport, domain));
    ast_sorcery_object_field_register_custom(sorcery, "transport", "verify_server", "", transport_tls_bool_handler, verify_server_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register_custom(sorcery, "transport", "verify_client", "", transport_tls_bool_handler, verify_client_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register_custom(sorcery, "transport", "require_client_cert", "", transport_tls_bool_handler, require_client_cert_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register_custom(sorcery, "transport", "method", "", transport_tls_method_handler, tls_method_to_str, NULL, 0, 0);
 #if defined(PJ_HAS_SSL_SOCK) && PJ_HAS_SSL_SOCK != 0
    ast_sorcery_object_field_register_custom(sorcery, "transport", "cipher", "", transport_tls_cipher_handler, transport_tls_cipher_to_str, NULL, 0, 0);
 #endif
    ast_sorcery_object_field_register_custom(sorcery, "transport", "local_net", "", transport_localnet_handler, localnet_to_str, localnet_to_vl, 0, 0);
    ast_sorcery_object_field_register_custom(sorcery, "transport", "tos", "0", transport_tos_handler, tos_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register(sorcery, "transport", "cos", "0", OPT_UINT_T, 0, FLDSET(struct ast_sip_transport, cos));
    ast_sorcery_object_field_register(sorcery, "transport", "websocket_write_timeout", AST_DEFAULT_WEBSOCKET_WRITE_TIMEOUT_STR, OPT_INT_T, PARSE_IN_RANGE, FLDSET(struct ast_sip_transport, write_timeout), 1, INT_MAX);
    ast_sorcery_object_field_register(sorcery, "transport", "allow_reload", "no", OPT_BOOL_T, 1, FLDSET(struct ast_sip_transport, allow_reload));
    ast_sorcery_object_field_register(sorcery, "transport", "symmetric_transport", "no", OPT_BOOL_T, 1, FLDSET(struct ast_sip_transport, symmetric_transport));
    ast_sip_register_endpoint_formatter(&endpoint_transport_formatter);
    cli_formatter = ao2_alloc(sizeof(struct ast_sip_cli_formatter_entry), NULL);
    if (!cli_formatter) {
       ast_log(LOG_ERROR, "Unable to allocate memory for cli formatter\n");
       return -1;
    }
    cli_formatter->name = "transport";
    cli_formatter->print_header = cli_print_header;
    cli_formatter->print_body = cli_print_body;
    cli_formatter->get_container = cli_get_container;
    cli_formatter->iterate = cli_iterate;
    cli_formatter->get_id = ast_sorcery_object_get_id;
    cli_formatter->retrieve_by_id = cli_retrieve_by_id;
    ast_sip_register_cli_formatter(cli_formatter);
    ast_cli_register_multiple(cli_commands, ARRAY_LEN(cli_commands));
    /* trigger load of transports from realtime by trying to revrieve them all */
    transports = ast_sorcery_retrieve_by_fields(sorcery, "transport", AST_RETRIEVE_FLAG_ALL | AST_RETRIEVE_FLAG_MULTIPLE, NULL);
    ao2_cleanup(transports);
    return 0;
 }
ast_sip_message_apply_transport()
void ast_sip_message_apply_transport (const char * transport_name, pjsip_tx_data * tdata)
Apply the configuration for a transport to an outgoing message.
Since
17.0.0
Parameters
transport_name The name of the transport to apply configuration from
tdata The SIP message
Definition at line 301 of file config_transport.c.
References ao2_lock, ao2_ref, ao2_unlock, ast_sip_add_header(), ast_sip_get_transport_state(), ast_strlen_zero, AST_VECTOR_GET, AST_VECTOR_SIZE, ast_sip_transport_state::flow, ast_sip_transport_state::preferred_identity, and ast_sip_transport_state::service_routes.
Referenced by ast_sip_send_out_of_dialog_request(), handle_outgoing_request(), handle_outgoing_response(), and supplement_outgoing_response().
 {
    struct ast_sip_transport_state *transport_state;
    if (ast_strlen_zero(transport_name)) {
       return;
    }
    /* We only currently care about requests that are of the INVITE, CANCEL, or OPTIONS
     * type but in the future we could support other messages.
     */
    if (tdata->msg->type != PJSIP_REQUEST_MSG ||
       (pjsip_method_cmp(&tdata->msg->line.req.method, &pjsip_invite_method) &&
       pjsip_method_cmp(&tdata->msg->line.req.method, &pjsip_cancel_method) &&
       pjsip_method_cmp(&tdata->msg->line.req.method, &pjsip_options_method))) {
       return;
    }
    transport_state = ast_sip_get_transport_state(transport_name);
    if (!transport_state) {
       return;
    }
    if (!transport_state->flow) {
       ao2_ref(transport_state, -1);
       return;
    }
    ao2_lock(transport_state);
    /* If a Preferred Identity has been set then add it to the request */
    if (transport_state->preferred_identity) {
       ast_sip_add_header(tdata, "P-Preferred-Identity", transport_state->preferred_identity);
    }
    /* If Service Routes have been set then add them to the request */
    if (transport_state->service_routes) {
       int idx;
       for (idx = 0; idx < AST_VECTOR_SIZE(transport_state->service_routes); ++idx) {
          char *service_route = AST_VECTOR_GET(transport_state->service_routes, idx);
          ast_sip_add_header(tdata, "Route", service_route);
       }
    }
    ao2_unlock(transport_state);
    ao2_ref(transport_state, -1);
 }
ast_sip_service_route_vector_alloc()
struct ast_sip_service_route_vector* ast_sip_service_route_vector_alloc (void)
Allocate a vector of service routes.
Since
17.0.0
Return values
non-NULL success
NULL failure
Definition at line 352 of file config_transport.c.
References ast_calloc, AST_VECTOR_INIT, and NULL.
Referenced by save_response_fields_to_transport().
 {
    struct ast_sip_service_route_vector *service_routes;
    service_routes = ast_calloc(1, sizeof(*service_routes));
    if (!service_routes) {
       return NULL;
    }
    AST_VECTOR_INIT(service_routes, 0);
    return service_routes;
 }
ast_sip_service_route_vector_destroy()
void ast_sip_service_route_vector_destroy (struct ast_sip_service_route_vector * service_routes)
Destroy a vector of service routes.
Since
17.0.0
Parameters
service_routes A vector of service routes
Definition at line 366 of file config_transport.c.
References ast_free, and AST_VECTOR_CALLBACK_VOID.
Referenced by ast_sip_transport_state_set_service_routes(), and save_response_fields_to_transport().
 {
    if (!service_routes) {
       return;
    }
    AST_VECTOR_CALLBACK_VOID(service_routes, ast_free);
    ast_free(service_routes);
 }
ast_sip_transport_state_set_preferred_identity()
int ast_sip_transport_state_set_preferred_identity (const char * transport_name, const char * identity)
Sets the P-Preferred-Identity on a child transport.
Since
17.0.0
Parameters
transport_name The name of the transport to be set on
identity The P-Preferred-Identity to use on requests on this transport
Return values
0 success
-1 failure
Definition at line 242 of file config_transport.c.
References ao2_lock, ao2_ref, ao2_unlock, ast_free, ast_sip_get_transport_state(), ast_strdup, ast_strlen_zero, ast_sip_transport_state::flow, and ast_sip_transport_state::preferred_identity.
Referenced by save_response_fields_to_transport().
 {
    struct ast_sip_transport_state *transport_state;
    if (ast_strlen_zero(transport_name)) {
       return 0;
    }
    transport_state = ast_sip_get_transport_state(transport_name);
    if (!transport_state) {
       return -1;
    }
    if (!transport_state->flow) {
       ao2_ref(transport_state, -1);
       return 0;
    }
    ao2_lock(transport_state);
    ast_free(transport_state->preferred_identity);
    transport_state->preferred_identity = ast_strdup(identity);
    ao2_unlock(transport_state);
    ao2_ref(transport_state, -1);
    return 0;
 }
ast_sip_transport_state_set_service_routes()
int ast_sip_transport_state_set_service_routes (const char * transport_name, struct ast_sip_service_route_vector * service_routes)
Sets the service routes on a child transport.
Since
17.0.0
Parameters
transport_name The name of the transport to be set on
service_routes A vector of service routes
Return values
0 success
-1 failure
Note
This assumes ownership of the service routes in both success and failure scenarios
Definition at line 270 of file config_transport.c.
References ao2_lock, ao2_ref, ao2_unlock, ast_sip_get_transport_state(), ast_sip_service_route_vector_destroy(), ast_strlen_zero, ast_sip_transport_state::flow, and ast_sip_transport_state::service_routes.
Referenced by save_response_fields_to_transport().
 {
    struct ast_sip_transport_state *transport_state;
    if (ast_strlen_zero(transport_name)) {
       ast_sip_service_route_vector_destroy(service_routes);
       return 0;
    }
    transport_state = ast_sip_get_transport_state(transport_name);
    if (!transport_state) {
       ast_sip_service_route_vector_destroy(service_routes);
       return -1;
    }
    if (!transport_state->flow) {
       ao2_ref(transport_state, -1);
       ast_sip_service_route_vector_destroy(service_routes);
       return 0;
    }
    ao2_lock(transport_state);
    ast_sip_service_route_vector_destroy(transport_state->service_routes);
    transport_state->service_routes = service_routes;
    ao2_unlock(transport_state);
    ao2_ref(transport_state, -1);
    return 0;
 }
ast_sip_transport_state_set_transport()
int ast_sip_transport_state_set_transport (const char * transport_name, pjsip_transport * transport)
Sets the PJSIP transport on a child transport.
Since
17.0.0
Parameters
transport_name The name of the transport to be updated
transport The PJSIP transport
Return values
0 success
-1 failure
Definition at line 206 of file config_transport.c.
References ao2_lock, ao2_ref, ao2_unlock, ast_sip_get_transport_state(), ast_strlen_zero, ast_sip_transport_state::flow, internal_state::transport, and ast_sip_transport_state::transport.
Referenced by save_response_fields_to_transport().
 {
    struct ast_sip_transport_state *transport_state;
    /* To make it easier on callers we allow an empty transport name */
    if (ast_strlen_zero(transport_name)) {
       return 0;
    }
    transport_state = ast_sip_get_transport_state(transport_name);
    if (!transport_state) {
       return -1;
    }
    if (!transport_state->flow) {
       ao2_ref(transport_state, -1);
       return 0;
    }
    ao2_lock(transport_state);
    if (transport_state->transport != transport) {
       if (transport_state->transport) {
          pjsip_transport_dec_ref(transport_state->transport);
       }
       transport_state->transport = transport;
       if (transport_state->transport) {
          pjsip_transport_add_ref(transport_state->transport);
       }
    }
    ao2_unlock(transport_state);
    ao2_ref(transport_state, -1);
    return 0;
 }
ca_list_file_to_str()
static int ca_list_file_to_str (const void * obj, const intptr_t * args, char ** buf) static
Definition at line 922 of file config_transport.c.
References ast_strdup, ast_sip_transport::ca_list_file, and internal_state::transport.
Referenced by ast_sip_initialize_sorcery_transport().
 {
    const struct ast_sip_transport *transport = obj;
    *buf = ast_strdup(transport->ca_list_file);
    return 0;
 }
ca_list_path_to_str()
static int ca_list_path_to_str (const void * obj, const intptr_t * args, char ** buf) static
Definition at line 931 of file config_transport.c.
References ast_strdup, ast_sip_transport::ca_list_path, and internal_state::transport.
Referenced by ast_sip_initialize_sorcery_transport().
 {
    const struct ast_sip_transport *transport = obj;
    *buf = ast_strdup(transport->ca_list_path);
    return 0;
 }
cert_file_to_str()
static int cert_file_to_str (const void * obj, const intptr_t * args, char ** buf) static
Definition at line 940 of file config_transport.c.
References ast_strdup, ast_sip_transport::cert_file, and internal_state::transport.
Referenced by ast_sip_initialize_sorcery_transport().
 {
    const struct ast_sip_transport *transport = obj;
    *buf = ast_strdup(transport->cert_file);
    return 0;
 }
cli_get_container()
static struct ao2_container* cli_get_container (const char * regex) static
Definition at line 1454 of file config_transport.c.
References AO2_ALLOC_OPT_LOCK_NOLOCK, ao2_cleanup, ao2_container_alloc_list, ao2_container_dup(), ao2_ref, ast_sip_get_sorcery(), ast_sorcery_object_id_compare(), ast_sorcery_object_id_sort(), ast_sorcery_retrieve_by_regex(), container, NULL, and RAII_VAR.
Referenced by ast_sip_initialize_sorcery_transport().
 {
    RAII_VAR(struct ao2_container *, container, NULL, ao2_cleanup);
    struct ao2_container *s_container;
    container = ast_sorcery_retrieve_by_regex(ast_sip_get_sorcery(), "transport",
       regex);
    if (!container) {
       return NULL;
    }
    s_container = ao2_container_alloc_list(AO2_ALLOC_OPT_LOCK_NOLOCK, 0,
       ast_sorcery_object_id_sort, ast_sorcery_object_id_compare);
    if (!s_container) {
       return NULL;
    }
    if (ao2_container_dup(s_container, container, 0)) {
       ao2_ref(s_container, -1);
       return NULL;
    }
    return s_container;
 }
cli_iterate()
static int cli_iterate (void * container, ao2_callback_fn callback, void * args) static
Definition at line 1479 of file config_transport.c.
References ast_sip_get_sorcery(), ast_sorcery_retrieve_by_id(), container, internal_state::transport, and ast_sip_endpoint::transport.
Referenced by ast_sip_initialize_sorcery_transport().
 {
    const struct ast_sip_endpoint *endpoint = container;
    struct ast_sip_transport *transport = ast_sorcery_retrieve_by_id(ast_sip_get_sorcery(),
       "transport", endpoint->transport);
    if (!transport) {
       return -1;
    }
    return callback(transport, args, 0);
 }
cli_print_body()
static int cli_print_body (void * obj, void * arg, int flags) static
Definition at line 1512 of file config_transport.c.
References ao2_cleanup, ARRAY_IN_BOUNDS, ast_assert, ast_sip_cli_print_sorcery_objectset(), ast_sorcery_object_get_id(), ast_str_append(), CLI_INDENT_TO_SPACES, context, ast_sip_transport::cos, find_state_by_transport(), ast_sip_transport_state::host, ast_sip_cli_context::indent_level, NULL, ast_sip_cli_context::output_buffer, RAII_VAR, ast_sip_cli_context::show_details, ast_sip_cli_context::show_details_only_level_0, ast_sip_transport::tos, internal_state::transport, transport_types, and ast_sip_transport::type.
Referenced by ast_sip_initialize_sorcery_transport().
 {
    struct ast_sip_transport *transport = obj;
    struct ast_sip_cli_context *context = arg;
    char hoststr[PJ_INET6_ADDRSTRLEN];
    RAII_VAR(struct ast_sip_transport_state *, state, find_state_by_transport(transport), ao2_cleanup);
    if (!state) {
       return -1;
    }
    ast_assert(context->output_buffer != NULL);
    pj_sockaddr_print(&state->host, hoststr, sizeof(hoststr), 3);
    ast_str_append(&context->output_buffer, 0, "%*s:  %-21s  %6s  %5u  %5u  %s\n",
       CLI_INDENT_TO_SPACES(context->indent_level), "Transport",
       ast_sorcery_object_get_id(transport),
       ARRAY_IN_BOUNDS(transport->type, transport_types) ? transport_types[transport->type] : "Unknown",
       transport->cos, transport->tos, hoststr);
    if (context->show_details
       || (context->show_details_only_level_0 && context->indent_level == 0)) {
       ast_str_append(&context->output_buffer, 0, "\n");
       ast_sip_cli_print_sorcery_objectset(transport, context, 0);
    }
    return 0;
 }
cli_print_header()
static int cli_print_header (void * obj, void * arg, int flags) static
Definition at line 1497 of file config_transport.c.
References ast_assert, ast_str_append(), CLI_HEADER_FILLER, CLI_INDENT_TO_SPACES, CLI_MAX_WIDTH, context, ast_sip_cli_context::indent_level, NULL, and ast_sip_cli_context::output_buffer.
Referenced by ast_sip_initialize_sorcery_transport().
 {
    struct ast_sip_cli_context *context = arg;
    int indent = CLI_INDENT_TO_SPACES(context->indent_level);
    int filler = CLI_MAX_WIDTH - indent - 61;
    ast_assert(context->output_buffer != NULL);
    ast_str_append(&context->output_buffer, 0,
       "%*s:  <TransportId........>  <Type>  <cos>  <tos>  <BindAddress%*.*s>\n",
       indent, "Transport", filler, filler, CLI_HEADER_FILLER);
    return 0;
 }
cli_retrieve_by_id()
static void* cli_retrieve_by_id (const char * id) static
Definition at line 1492 of file config_transport.c.
References ast_sip_get_sorcery(), and ast_sorcery_retrieve_by_id().
Referenced by ast_sip_initialize_sorcery_transport().
 {
    return ast_sorcery_retrieve_by_id(ast_sip_get_sorcery(), "transport", id);
 }
copy_state_to_transport()
static void copy_state_to_transport (struct ast_sip_transport * transport) static
Definition at line 568 of file config_transport.c.
References ast_assert, ast_sip_transport_state::ciphers, ast_sip_transport::ciphers, ast_sip_transport::external_address, ast_sip_transport::external_address_refresher, ast_sip_transport_state::external_signaling_address, ast_sip_transport::external_signaling_address, ast_sip_transport_state::external_signaling_address_refresher, ast_sip_transport_state::host, ast_sip_transport::host, ast_sip_transport_state::localnet, ast_sip_transport::localnet, ast_sip_transport::state, ast_sip_transport_state::tls, and ast_sip_transport::tls.
Referenced by transport_apply().
 {
    ast_assert(transport && transport->state);
    memcpy(&transport->host, &transport->state->host, sizeof(transport->host));
    memcpy(&transport->tls, &transport->state->tls, sizeof(transport->tls));
    memcpy(&transport->ciphers, &transport->state->ciphers, sizeof(transport->ciphers));
    transport->localnet = transport->state->localnet;
    transport->external_address_refresher = transport->state->external_signaling_address_refresher;
    memcpy(&transport->external_address, &transport->state->external_signaling_address, sizeof(transport->external_signaling_address));
 }
destroy_sip_transport_state()
static int destroy_sip_transport_state (void * data) static
Definition at line 415 of file config_transport.c.
References ast_dnsmgr_release(), ast_free, ast_free_ha(), ast_sip_transport_state::external_media_address_refresher, ast_sip_transport_state::external_signaling_address_refresher, ast_sip_transport_state::id, ast_sip_transport_state::localnet, and ast_sip_transport_state::transport.
Referenced by sip_transport_state_destroy().
 {
    struct ast_sip_transport_state *transport_state = data;
    ast_free(transport_state->id);
    ast_free_ha(transport_state->localnet);
    if (transport_state->external_signaling_address_refresher) {
       ast_dnsmgr_release(transport_state->external_signaling_address_refresher);
    }
    if (transport_state->external_media_address_refresher) {
       ast_dnsmgr_release(transport_state->external_media_address_refresher);
    }
    if (transport_state->transport) {
       pjsip_transport_shutdown(transport_state->transport);
    }
    return 0;
 }
find_internal_state_by_transport()
static struct internal_state* find_internal_state_by_transport (const struct ast_sip_transport * transport) static
Definition at line 453 of file config_transport.c.
References ao2_find, ast_sorcery_object_get_id(), OBJ_NOLOCK, and OBJ_SEARCH_KEY.
Referenced by find_state_by_transport(), and transport_apply().
 {
    const char *key = ast_sorcery_object_get_id(transport);
    return ao2_find(transport_states, key, OBJ_SEARCH_KEY | OBJ_NOLOCK);
 }
find_or_create_temporary_state()
static struct ast_sip_transport_state* find_or_create_temporary_state (struct ast_sip_transport * transport) static
Definition at line 534 of file config_transport.c.
References ao2_alloc, ao2_ref, ast_sorcery_object_get_id(), ast_strdup, ast_threadstorage_get(), ast_sip_transport_state::ciphers, find_temporary_state(), ast_sip_transport_state::id, NULL, sip_transport_state_destroy(), internal_state::state, temp_state_store, ast_sip_transport_state::tls, ast_sip_transport_state::type, and ast_sip_transport::type.
Referenced by tls_method_to_str(), transport_bind_handler(), transport_localnet_handler(), transport_protocol_handler(), transport_state_init(), transport_tls_bool_handler(), transport_tls_file_handler(), and transport_tls_method_handler().
 {
    struct ast_sip_transport_state **state;
    struct ast_sip_transport_state *new_state;
    if ((new_state = find_temporary_state(transport))) {
       return new_state;
    }
    state = ast_threadstorage_get(&temp_state_store, sizeof(state));
    if (!state || *state) {
       return NULL;
    }
    new_state = ao2_alloc(sizeof(**state), sip_transport_state_destroy);
    if (!new_state) {
       return NULL;
    }
    new_state->id = ast_strdup(ast_sorcery_object_get_id(transport));
    new_state->type = transport->type;
    pjsip_tls_setting_default(&new_state->tls);
 #ifdef HAVE_PJSIP_TLS_TRANSPORT_PROTO
    /* proto must be forced to 0 to enable all protocols otherwise only TLS will work */
    new_state->tls.proto = 0;
 #endif
    new_state->tls.ciphers = new_state->ciphers;
    ao2_ref(new_state, +1);
    *state = new_state;
    return new_state;
 }
find_state_by_transport()
static struct ast_sip_transport_state* find_state_by_transport (const struct ast_sip_transport * transport) static
Definition at line 460 of file config_transport.c.
References ao2_bump, ao2_ref, find_internal_state_by_transport(), NULL, and internal_state::state.
Referenced by cli_print_body(), localnet_to_str(), localnet_to_vl(), require_client_cert_to_str(), tls_method_to_str(), transport_bind_to_str(), verify_client_to_str(), and verify_server_to_str().
 {
    struct internal_state *state;
    struct ast_sip_transport_state *trans_state;
    state = find_internal_state_by_transport(transport);
    if (!state) {
       return NULL;
    }
    trans_state = ao2_bump(state->state);
    ao2_ref(state, -1);
    return trans_state;
 }
find_temporary_state()
static struct ast_sip_transport_state* find_temporary_state (struct ast_sip_transport * transport) static
Definition at line 489 of file config_transport.c.
References ao2_ref, ast_threadstorage_get(), NULL, internal_state::state, and temp_state_store.
Referenced by find_or_create_temporary_state(), and internal_state_alloc().
 {
    struct ast_sip_transport_state **state;
    state = ast_threadstorage_get(&temp_state_store, sizeof(state));
    if (state && *state) {
       ao2_ref(*state, +1);
       return *state;
    }
    return NULL;
 }
format_ami_endpoint_transport()
static int format_ami_endpoint_transport (const struct ast_sip_endpoint * endpoint, struct ast_sip_ami * ami) static
Definition at line 168 of file config_transport.c.
References ao2_cleanup, ast_free, ast_sip_create_ami_event(), ast_sip_get_sorcery(), ast_sorcery_object_get_id(), ast_sorcery_retrieve_by_id(), ast_str_append(), ast_str_buffer(), ast_strlen_zero, astman_append(), astman_send_error_va(), buf, ast_sip_ami::count, ast_sip_ami::m, NULL, RAII_VAR, ast_sip_ami::s, sip_transport_to_ami(), internal_state::transport, and ast_sip_endpoint::transport.
 {
    RAII_VAR(struct ast_str *, buf, NULL, ast_free);
    RAII_VAR(struct ast_sip_transport *, transport, NULL, ao2_cleanup);
    if (ast_strlen_zero(endpoint->transport)) {
       return 0;
    }
    buf = ast_sip_create_ami_event("TransportDetail", ami);
    if (!buf) {
       return -1;
    }
    transport = ast_sorcery_retrieve_by_id(ast_sip_get_sorcery(), "transport",
       endpoint->transport);
    if (!transport) {
       astman_send_error_va(ami->s, ami->m, "Unable to retrieve "
                  "transport %s\n", endpoint->transport);
       return -1;
    }
    sip_transport_to_ami(transport, &buf);
    ast_str_append(&buf, 0, "EndpointName: %s\r\n",
              ast_sorcery_object_get_id(endpoint));
    astman_append(ami->s, "%s\r\n", ast_str_buffer(buf));
    ami->count++;
    return 0;
 }
has_state_changed()
static int has_state_changed (struct ast_sip_transport_state * a, struct ast_sip_transport_state * b) static
Definition at line 580 of file config_transport.c.
References ast_ha::addr, ast_sockaddr_cmp(), ast_sip_transport_state::ciphers, ast_sip_transport_state::external_media_address, ast_sip_transport_state::external_signaling_address, HAVE_PJSIP_TLS_TRANSPORT_PROTO, ast_sip_transport_state::host, ast_sip_transport_state::localnet, ast_ha::netmask, ast_sip_transport_state::tls, and ast_sip_transport_state::type.
Referenced by transport_apply().
 {
    if (a->type != b->type) {
       return -1;
    }
    if (pj_sockaddr_cmp(&a->host, &b->host)) {
       return -1;
    }
    if ((a->localnet || b->localnet)
       && ((!a->localnet != !b->localnet)
       || ast_sockaddr_cmp(&a->localnet->addr, &b->localnet->addr)
       || ast_sockaddr_cmp(&a->localnet->netmask, &b->localnet->netmask)))
    {
       return -1;
    }
    if (ast_sockaddr_cmp(&a->external_signaling_address, &b->external_signaling_address)) {
       return -1;
    }
    if (ast_sockaddr_cmp(&a->external_media_address, &b->external_media_address)) {
       return -1;
    }
    if (a->tls.method != b->tls.method
       || a->tls.ciphers_num != b->tls.ciphers_num
 #ifdef HAVE_PJSIP_TLS_TRANSPORT_PROTO
       || a->tls.proto != b->tls.proto
 #endif
       || a->tls.verify_client != b->tls.verify_client
       || a->tls.verify_server != b->tls.verify_server
       || a->tls.require_client_cert != b->tls.require_client_cert) {
       return -1;
    }
    if (memcmp(a->ciphers, b->ciphers, sizeof(pj_ssl_cipher) * fmax(a->tls.ciphers_num, b->tls.ciphers_num))) {
       return -1;
    }
    return 0;
 }
internal_state_alloc()
static struct internal_state* internal_state_alloc (struct ast_sip_transport * transport) static
Definition at line 502 of file config_transport.c.
References ao2_alloc, ao2_bump, ao2_cleanup, ast_sorcery_object_get_id(), ast_strdup, find_temporary_state(), internal_state::id, internal_state_destroy(), NULL, remove_temporary_state(), internal_state::state, ast_sip_transport::state, and internal_state::transport.
Referenced by transport_apply().
 {
    struct internal_state *internal_state;
    internal_state = ao2_alloc(sizeof(*internal_state), internal_state_destroy);
    if (!internal_state) {
       return NULL;
    }
    internal_state->id = ast_strdup(ast_sorcery_object_get_id(transport));
    if (!internal_state->id) {
       ao2_cleanup(internal_state);
       return NULL;
    }
    /* We're transferring the reference from find_temporary_state */
    internal_state->state = find_temporary_state(transport);
    if (!internal_state->state) {
       ao2_cleanup(internal_state);
       return NULL;
    }
    internal_state->transport = ao2_bump(transport);
    internal_state->transport->state = internal_state->state;
    remove_temporary_state();
    return internal_state;
 }
internal_state_cmp()
static int internal_state_cmp (void * obj, void * arg, int flags) static
comparator function for state objects
Definition at line 84 of file config_transport.c.
References ast_assert, CMP_MATCH, internal_state::id, OBJ_SEARCH_KEY, OBJ_SEARCH_MASK, OBJ_SEARCH_OBJECT, and OBJ_SEARCH_PARTIAL_KEY.
Referenced by ast_sip_initialize_sorcery_transport().
 {
    const struct internal_state *object_left = obj;
    const struct internal_state *object_right = arg;
    const char *right_key = arg;
    int cmp;
    switch (flags & OBJ_SEARCH_MASK) {
    case OBJ_SEARCH_OBJECT:
       right_key = object_right->id;
       /* Fall through */
    case OBJ_SEARCH_KEY:
       cmp = strcmp(object_left->id, right_key);
       break;
    case OBJ_SEARCH_PARTIAL_KEY:
       /* Not supported by container. */
       ast_assert(0);
       return 0;
    default:
       cmp = 0;
       break;
    }
    if (cmp) {
       return 0;
    }
    return CMP_MATCH;
 }
internal_state_destroy()
static void internal_state_destroy (void * obj) static
Destructor for ast_sip_transport state information.
Definition at line 444 of file config_transport.c.
References ao2_cleanup, ast_free, internal_state::id, internal_state::state, and internal_state::transport.
Referenced by internal_state_alloc().
 {
    struct internal_state *state = obj;
    ast_free(state->id);
    ao2_cleanup(state->transport);
    ao2_cleanup(state->state);
 }
internal_state_hash()
static int internal_state_hash (const void * obj, const int flags) static
hashing function for state objects
Definition at line 63 of file config_transport.c.
References ast_assert, ast_str_hash(), OBJ_SEARCH_KEY, OBJ_SEARCH_MASK, and OBJ_SEARCH_OBJECT.
Referenced by ast_sip_initialize_sorcery_transport().
 {
    const struct internal_state *object;
    const char *key;
    switch (flags & OBJ_SEARCH_MASK) {
    case OBJ_SEARCH_KEY:
       key = obj;
       break;
    case OBJ_SEARCH_OBJECT:
       object = obj;
       key = object->id;
       break;
    default:
       ast_assert(0);
       return 0;
    }
    return ast_str_hash(key);
 }
localnet_to_str()
static int localnet_to_str (const void * obj, const intptr_t * args, char ** buf) static
Definition at line 1403 of file config_transport.c.
References ao2_cleanup, ast_free, ast_ha_join(), ast_str_buffer(), ast_str_create, ast_strdup, find_state_by_transport(), ast_sip_transport_state::localnet, MAX_OBJECT_FIELD, RAII_VAR, str, and internal_state::transport.
Referenced by ast_sip_initialize_sorcery_transport().
 {
    RAII_VAR(struct ast_str *, str, ast_str_create(MAX_OBJECT_FIELD), ast_free);
    const struct ast_sip_transport *transport = obj;
    RAII_VAR(struct ast_sip_transport_state *, state, find_state_by_transport(transport), ao2_cleanup);
    if (!state) {
       return -1;
    }
    ast_ha_join(state->localnet, &str);
    *buf = ast_strdup(ast_str_buffer(str));
    return 0;
 }
localnet_to_vl()
static int localnet_to_vl (const void * obj, struct ast_variable ** fields) static
Definition at line 1381 of file config_transport.c.
References ao2_cleanup, find_state_by_transport(), ast_sip_transport_state::localnet, localnet_to_vl_append(), ast_ha::next, NULL, RAII_VAR, and internal_state::transport.
Referenced by ast_sip_initialize_sorcery_transport().
 {
    const struct ast_sip_transport *transport = obj;
    struct ast_variable *head = NULL;
    struct ast_ha *ha;
    RAII_VAR(struct ast_sip_transport_state *, state, find_state_by_transport(transport), ao2_cleanup);
    if (!state) {
       return -1;
    }
    for (ha = state->localnet; ha; ha = ha->next) {
       localnet_to_vl_append(&head, ha);
    }
    if (head) {
       *fields = head;
    }
    return 0;
 }
localnet_to_vl_append()
static void localnet_to_vl_append (struct ast_variable ** head, struct ast_ha * ha) static
Definition at line 1371 of file config_transport.c.
References ast_ha::addr, AST_SENSE_ALLOW, ast_sockaddr_stringify_addr(), ast_strdupa, ast_variable_list_append, ast_variable_new, MAX_OBJECT_FIELD, ast_ha::netmask, ast_ha::sense, and str.
Referenced by localnet_to_vl().
 {
    char str[MAX_OBJECT_FIELD];
    const char *addr = ast_strdupa(ast_sockaddr_stringify_addr(&ha->addr));
    snprintf(str, MAX_OBJECT_FIELD, "%s%s/%s", ha->sense == AST_SENSE_ALLOW ? "!" : "",
           addr, ast_sockaddr_stringify_addr(&ha->netmask));
    ast_variable_list_append(head, ast_variable_new("local_net", str, ""));
 }
populate_transport_states()
static int populate_transport_states (void * obj, void * arg, int flags) static
Definition at line 1594 of file config_transport.c.
References ao2_link, CMP_MATCH, container, and internal_state::state.
Referenced by ast_sip_get_transport_states().
 {
    struct internal_state *state = obj;
    struct ao2_container *container = arg;
    ao2_link(container, state->state);
    return CMP_MATCH;
 }
privkey_file_to_str()
static int privkey_file_to_str (const void * obj, const intptr_t * args, char ** buf) static
Definition at line 949 of file config_transport.c.
References ast_strdup, ast_sip_transport::privkey_file, and internal_state::transport.
Referenced by ast_sip_initialize_sorcery_transport().
 {
    const struct ast_sip_transport *transport = obj;
    *buf = ast_strdup(transport->privkey_file);
    return 0;
 }
remove_temporary_state()
static int remove_temporary_state (void) static
Definition at line 475 of file config_transport.c.
References ao2_cleanup, ast_threadstorage_get(), NULL, internal_state::state, and temp_state_store.
Referenced by internal_state_alloc().
 {
    struct ast_sip_transport_state **state;
    state = ast_threadstorage_get(&temp_state_store, sizeof(state));
    if (!state) {
       return -1;
    }
    ao2_cleanup(*state);
    *state = NULL;
    return 0;
 }
require_client_cert_to_str()
static int require_client_cert_to_str (const void * obj, const intptr_t * args, char ** buf) static
Definition at line 1100 of file config_transport.c.
References ao2_cleanup, ast_strdup, AST_YESNO, find_state_by_transport(), RAII_VAR, and internal_state::transport.
Referenced by ast_sip_initialize_sorcery_transport().
 {
    const struct ast_sip_transport *transport = obj;
    RAII_VAR(struct ast_sip_transport_state *, state, find_state_by_transport(transport), ao2_cleanup);
    if (!state) {
       return -1;
    }
    *buf = ast_strdup(AST_YESNO(state->tls.require_client_cert));
    return 0;
 }
set_qos()
static void set_qos (struct ast_sip_transport * transport, pj_qos_params * qos) static
Definition at line 376 of file config_transport.c.
References ast_sip_transport::cos, and ast_sip_transport::tos.
Referenced by transport_apply().
 {
    int tos_as_dscp = transport->tos >> 2;
    if (transport->tos) {
       qos->flags |= PJ_QOS_PARAM_HAS_DSCP;
       qos->dscp_val = tos_as_dscp;
    }
    if (transport->cos) {
       qos->flags |= PJ_QOS_PARAM_HAS_SO_PRIO;
       qos->so_prio = transport->cos;
    }
 }
sip_transport_alloc()
static void* sip_transport_alloc (const char * name) static
Allocator for transport.
Definition at line 399 of file config_transport.c.
References ao2_cleanup, ast_sorcery_generic_alloc(), ast_string_field_init, NULL, sip_transport_destroy(), and internal_state::transport.
Referenced by ast_sip_initialize_sorcery_transport().
 {
    struct ast_sip_transport *transport = ast_sorcery_generic_alloc(sizeof(*transport), sip_transport_destroy);
    if (!transport) {
       return NULL;
    }
    if (ast_string_field_init(transport, 256)) {
       ao2_cleanup(transport);
       return NULL;
    }
    return transport;
 }
sip_transport_destroy()
static void sip_transport_destroy (void * obj) static
Destructor for transport.
Definition at line 391 of file config_transport.c.
References ast_string_field_free_memory, and internal_state::transport.
Referenced by sip_transport_alloc().
 {
    struct ast_sip_transport *transport = obj;
    ast_string_field_free_memory(transport);
 }
sip_transport_state_destroy()
static void sip_transport_state_destroy (void * obj) static
Destructor for ast_sip_transport state information.
Definition at line 436 of file config_transport.c.
References ast_sip_push_task_wait_servant(), destroy_sip_transport_state(), and NULL.
Referenced by find_or_create_temporary_state().
 {
    struct ast_sip_transport_state *state = obj;
    ast_sip_push_task_wait_servant(NULL, destroy_sip_transport_state, state);
 }
sip_transport_to_ami()
static int sip_transport_to_ami (const struct ast_sip_transport * transport, struct ast_str ** buf) static
Definition at line 162 of file config_transport.c.
References ast_sip_sorcery_object_to_ami().
Referenced by format_ami_endpoint_transport().
 {
    return ast_sip_sorcery_object_to_ami(transport, buf);
 }
states_cleanup()
static void states_cleanup (void * states) static
Definition at line 624 of file config_transport.c.
References ao2_unlock.
Referenced by transport_apply().
 {
    if (states) {
       ao2_unlock(states);
    }
 }
temp_state_store_cleanup()
static void temp_state_store_cleanup (void * data) static
Definition at line 52 of file config_transport.c.
References ao2_cleanup, and ast_free.
 {
    struct ast_sip_transport_state **temp_state = data;
    ao2_cleanup(*temp_state);
    ast_free(data);
 }
tls_method_to_str()
static int tls_method_to_str (const void * obj, const intptr_t * args, char ** buf) static
Definition at line 1161 of file config_transport.c.
References a, ao2_cleanup, args, ARRAY_IN_BOUNDS, ARRAY_LEN, ast_cli(), ast_free, ast_log, ast_str_append(), ast_str_buffer(), ast_str_create, ast_strdup, ast_strdupa, ast_strip(), ast_strlen_zero, buf, ast_sip_transport_state::ciphers, ast_sip_transport::ciphers, CLI_GENERATE, CLI_INIT, CLI_SUCCESS, ast_cli_entry::command, ast_cli_args::fd, find_or_create_temporary_state(), find_state_by_transport(), LOG_ERROR, name, NULL, parse(), RAII_VAR, S_OR, str, strsep(), ast_sip_transport_state::tls, tls_method_map, internal_state::transport, ast_cli_entry::usage, ast_variable::value, and var.
Referenced by ast_sip_initialize_sorcery_transport().
 {
    const struct ast_sip_transport *transport = obj;
    RAII_VAR(struct ast_sip_transport_state *, state, find_state_by_transport(transport), ao2_cleanup);
    if (!state) {
       return -1;
    }
    if (ARRAY_IN_BOUNDS(state->tls.method, tls_method_map)) {
       *buf = ast_strdup(tls_method_map[state->tls.method]);
    }
    return 0;
 }
tos_to_str()
static int tos_to_str (const void * obj, const intptr_t * args, char ** buf) static
Definition at line 1444 of file config_transport.c.
References ast_asprintf, ast_sip_transport::tos, and internal_state::transport.
Referenced by ast_sip_initialize_sorcery_transport().
 {
    const struct ast_sip_transport *transport = obj;
    if (ast_asprintf(buf, "%u", transport->tos) == -1) {
       return -1;
    }
    return 0;
 }
transport_apply()
static int transport_apply (const struct ast_sorcery * sorcery, void * obj) static
Apply handler for transports.
Definition at line 632 of file config_transport.c.
References ast_sip_transport::allow_reload, ao2_cleanup, ao2_link_flags, ao2_replace, ao2_unlink_flags, ao2_wrlock, ast_compare_versions(), ast_debug, ast_dnsmgr_lookup(), ast_log, ast_sip_get_pjsip_endpoint(), AST_SIP_X_AST_TXP, AST_SIP_X_AST_TXP_LEN, ast_sorcery_diff(), ast_sorcery_object_get_id(), ast_strlen_zero, AST_TRANSPORT_TCP, AST_TRANSPORT_TLS, AST_TRANSPORT_UDP, AST_TRANSPORT_WS, AST_TRANSPORT_WSS, ast_variables_destroy(), ast_sip_transport::async_operations, BIND_DELAY_US, BIND_TRIES, ast_sip_transport::ca_list_file, ast_sip_transport::ca_list_path, ast_sip_transport::cert_file, copy_state_to_transport(), ast_sip_transport::cos, ast_sip_transport::external_media_address, ast_sip_transport::external_signaling_address, find_internal_state_by_transport(), ast_sip_transport::flow, has_state_changed(), internal_state_alloc(), LOG_ERROR, LOG_WARNING, NULL, OBJ_NOLOCK, ast_sip_transport::password, ast_sip_transport::privkey_file, RAII_VAR, set_qos(), ast_sip_transport::state, states_cleanup(), ast_sip_transport_state::tls, ast_sip_transport::tos, internal_state::transport, and ast_sip_transport::type.
Referenced by ast_sip_initialize_sorcery_transport().
 {
    struct ast_sip_transport *transport = obj;
    const char *transport_id = ast_sorcery_object_get_id(obj);
    RAII_VAR(struct ao2_container *, states, transport_states, states_cleanup);
    RAII_VAR(struct internal_state *, temp_state, NULL, ao2_cleanup);
    RAII_VAR(struct internal_state *, perm_state, NULL, ao2_cleanup);
    RAII_VAR(struct ast_variable *, changes, NULL, ast_variables_destroy);
    pj_status_t res = -1;
    int i;
 #define BIND_TRIES 3
 #define BIND_DELAY_US 100000
    if (!states) {
       return -1;
    }
    /*
     * transport_apply gets called for EVERY retrieval of a transport when using realtime.
     * We need to prevent multiple threads from trying to mess with underlying transports
     * at the same time.  The container is the only thing we have to lock on.
     */
    ao2_wrlock(states);
    temp_state = internal_state_alloc(transport);
    if (!temp_state) {
       ast_log(LOG_ERROR, "Transport '%s' failed to allocate memory\n", transport_id);
       return -1;
    }
    perm_state = find_internal_state_by_transport(transport);
    if (perm_state) {
       ast_sorcery_diff(sorcery, perm_state->transport, transport, &changes);
       if (!changes && !has_state_changed(perm_state->state, temp_state->state)) {
          /* In case someone is using the deprecated fields, reset them */
          transport->state = perm_state->state;
          copy_state_to_transport(transport);
          ao2_replace(perm_state->transport, transport);
          return 0;
       }
       /* If we aren't allowed to reload then we copy values that can't be changed from perm_state */
       if (!transport->allow_reload) {
          memcpy(&temp_state->state->host, &perm_state->state->host, sizeof(temp_state->state->host));
          memcpy(&temp_state->state->tls, &perm_state->state->tls, sizeof(temp_state->state->tls));
          memcpy(&temp_state->state->ciphers, &perm_state->state->ciphers, sizeof(temp_state->state->ciphers));
       }
    }
    if (!transport->flow && (!perm_state || transport->allow_reload)) {
       if (temp_state->state->host.addr.sa_family != PJ_AF_INET && temp_state->state->host.addr.sa_family != PJ_AF_INET6) {
          ast_log(LOG_ERROR, "Transport '%s' could not be started as binding not specified\n", transport_id);
          return -1;
       }
       /* Set default port if not present */
       if (!pj_sockaddr_get_port(&temp_state->state->host)) {
          pj_sockaddr_set_port(&temp_state->state->host, (transport->type == AST_TRANSPORT_TLS) ? 5061 : 5060);
       }
    }
    /* Now that we know what address family we can set up a dnsmgr refresh for the external addresses if present */
    if (!ast_strlen_zero(transport->external_signaling_address)) {
       if (temp_state->state->host.addr.sa_family == pj_AF_INET()) {
          temp_state->state->external_signaling_address.ss.ss_family = AF_INET;
       } else if (temp_state->state->host.addr.sa_family == pj_AF_INET6()) {
          temp_state->state->external_signaling_address.ss.ss_family = AF_INET6;
       } else {
          ast_log(LOG_ERROR, "Unknown address family for transport '%s', could not get external signaling address\n",
                transport_id);
          return -1;
       }
       if (ast_dnsmgr_lookup(transport->external_signaling_address, &temp_state->state->external_signaling_address, &temp_state->state->external_signaling_address_refresher, NULL) < 0) {
          ast_log(LOG_ERROR, "Could not create dnsmgr for external signaling address on '%s'\n", transport_id);
          return -1;
       }
    }
    if (!ast_strlen_zero(transport->external_media_address)) {
       if (temp_state->state->host.addr.sa_family == pj_AF_INET()) {
          temp_state->state->external_media_address.ss.ss_family = AF_INET;
       } else if (temp_state->state->host.addr.sa_family == pj_AF_INET6()) {
          temp_state->state->external_media_address.ss.ss_family = AF_INET6;
       } else {
          ast_log(LOG_ERROR, "Unknown address family for transport '%s', could not get external media address\n",
                transport_id);
          return -1;
       }
       if (ast_dnsmgr_lookup(transport->external_media_address, &temp_state->state->external_media_address, &temp_state->state->external_media_address_refresher, NULL) < 0) {
          ast_log(LOG_ERROR, "Could not create dnsmgr for external media address on '%s'\n", transport_id);
          return -1;
       }
    }
    if (transport->flow) {
       pj_str_t address;
       ast_debug(1, "Ignoring any bind configuration on transport '%s' as it is a child of another\n",
          transport_id);
       pj_sockaddr_parse(pj_AF_UNSPEC(), 0, pj_cstr(&address, "0.0.0.0"), &temp_state->state->host);
       temp_state->state->flow = 1;
       res = PJ_SUCCESS;
    } else if (!transport->allow_reload && perm_state) {
       /* We inherit the transport from perm state, untouched */
       ast_log(LOG_WARNING, "Transport '%s' is not fully reloadable, not reloading: protocol, bind, TLS, TCP, ToS, or CoS options.\n", transport_id);
       temp_state->state->transport = perm_state->state->transport;
       perm_state->state->transport = NULL;
       temp_state->state->factory = perm_state->state->factory;
       perm_state->state->factory = NULL;
       res = PJ_SUCCESS;
    } else if (transport->type == AST_TRANSPORT_UDP) {
       for (i = 0; i < BIND_TRIES && res != PJ_SUCCESS; i++) {
          if (perm_state && perm_state->state && perm_state->state->transport) {
             pjsip_udp_transport_pause(perm_state->state->transport,
                PJSIP_UDP_TRANSPORT_DESTROY_SOCKET);
             usleep(BIND_DELAY_US);
          }
          if (temp_state->state->host.addr.sa_family == pj_AF_INET()) {
             res = pjsip_udp_transport_start(ast_sip_get_pjsip_endpoint(),
                &temp_state->state->host.ipv4, NULL, transport->async_operations,
                &temp_state->state->transport);
          } else if (temp_state->state->host.addr.sa_family == pj_AF_INET6()) {
             res = pjsip_udp_transport_start6(ast_sip_get_pjsip_endpoint(),
                &temp_state->state->host.ipv6, NULL, transport->async_operations,
                &temp_state->state->transport);
          }
       }
       if (res == PJ_SUCCESS) {
          temp_state->state->transport->info = pj_pool_alloc(temp_state->state->transport->pool,
             (AST_SIP_X_AST_TXP_LEN + strlen(transport_id) + 2));
          sprintf(temp_state->state->transport->info, "%s:%s", AST_SIP_X_AST_TXP, transport_id);
          if (transport->tos || transport->cos) {
             pj_sock_t sock;
             pj_qos_params qos_params;
             sock = pjsip_udp_transport_get_socket(temp_state->state->transport);
             pj_sock_get_qos_params(sock, &qos_params);
             set_qos(transport, &qos_params);
             pj_sock_set_qos_params(sock, &qos_params);
          }
       }
    } else if (transport->type == AST_TRANSPORT_TCP) {
       pjsip_tcp_transport_cfg cfg;
       static int option = 1;
       pjsip_tcp_transport_cfg_default(&cfg, temp_state->state->host.addr.sa_family);
       cfg.bind_addr = temp_state->state->host;
       cfg.async_cnt = transport->async_operations;
       set_qos(transport, &cfg.qos_params);
       /* sockopt_params.options is copied to each newly connected socket */
       cfg.sockopt_params.options[0].level = pj_SOL_TCP();
       cfg.sockopt_params.options[0].optname = pj_TCP_NODELAY();
       cfg.sockopt_params.options[0].optval = &option;
       cfg.sockopt_params.options[0].optlen = sizeof(option);
       cfg.sockopt_params.cnt = 1;
       for (i = 0; i < BIND_TRIES && res != PJ_SUCCESS; i++) {
          if (perm_state && perm_state->state && perm_state->state->factory
             && perm_state->state->factory->destroy) {
             perm_state->state->factory->destroy(perm_state->state->factory);
             usleep(BIND_DELAY_US);
          }
          res = pjsip_tcp_transport_start3(ast_sip_get_pjsip_endpoint(), &cfg,
             &temp_state->state->factory);
       }
    } else if (transport->type == AST_TRANSPORT_TLS) {
 #if defined(PJ_HAS_SSL_SOCK) && PJ_HAS_SSL_SOCK != 0
       static int option = 1;
       if (transport->async_operations > 1 && ast_compare_versions(pj_get_version(), "2.5.0") < 0) {
          ast_log(LOG_ERROR, "Transport: %s: When protocol=tls and pjproject version < 2.5.0, async_operations can't be > 1\n",
                ast_sorcery_object_get_id(obj));
          return -1;
       }
       temp_state->state->tls.password = pj_str((char*)transport->password);
       set_qos(transport, &temp_state->state->tls.qos_params);
       /* sockopt_params.options is copied to each newly connected socket */
       temp_state->state->tls.sockopt_params.options[0].level = pj_SOL_TCP();
       temp_state->state->tls.sockopt_params.options[0].optname = pj_TCP_NODELAY();
       temp_state->state->tls.sockopt_params.options[0].optval = &option;
       temp_state->state->tls.sockopt_params.options[0].optlen = sizeof(option);
       temp_state->state->tls.sockopt_params.cnt = 1;
       for (i = 0; i < BIND_TRIES && res != PJ_SUCCESS; i++) {
          if (perm_state && perm_state->state && perm_state->state->factory
             && perm_state->state->factory->destroy) {
             perm_state->state->factory->destroy(perm_state->state->factory);
             usleep(BIND_DELAY_US);
          }
          res = pjsip_tls_transport_start2(ast_sip_get_pjsip_endpoint(), &temp_state->state->tls,
             &temp_state->state->host, NULL, transport->async_operations,
             &temp_state->state->factory);
       }
 #else
       ast_log(LOG_ERROR, "Transport: %s: PJSIP has not been compiled with TLS transport support, ensure OpenSSL development packages are installed\n",
          ast_sorcery_object_get_id(obj));
       return -1;
 #endif
    } else if ((transport->type == AST_TRANSPORT_WS) || (transport->type == AST_TRANSPORT_WSS)) {
       if (transport->cos || transport->tos) {
          ast_log(LOG_WARNING, "TOS and COS values ignored for websocket transport\n");
       } else if (!ast_strlen_zero(transport->ca_list_file) || !ast_strlen_zero(transport->ca_list_path) ||
          !ast_strlen_zero(transport->cert_file) || !ast_strlen_zero(transport->privkey_file)) {
          ast_log(LOG_WARNING, "TLS certificate values ignored for websocket transport as they are configured in http.conf\n");
       }
       res = PJ_SUCCESS;
    }
    if (res != PJ_SUCCESS) {
       char msg[PJ_ERR_MSG_SIZE];
       pj_strerror(res, msg, sizeof(msg));
       ast_log(LOG_ERROR, "Transport '%s' could not be started: %s\n", ast_sorcery_object_get_id(obj), msg);
       return -1;
    }
    copy_state_to_transport(transport);
    if (perm_state) {
       ao2_unlink_flags(states, perm_state, OBJ_NOLOCK);
    }
    ao2_link_flags(states, temp_state, OBJ_NOLOCK);
    return 0;
 }
transport_bind_handler()
static int transport_bind_handler (const struct aco_option * opt, struct ast_variable * var, void * obj) static
Custom handler for turning a string bind into a pj_sockaddr.
Definition at line 1014 of file config_transport.c.
References ao2_cleanup, buf, find_or_create_temporary_state(), RAII_VAR, internal_state::transport, and ast_variable::value.
Referenced by ast_sip_initialize_sorcery_transport().
 {
    struct ast_sip_transport *transport = obj;
    pj_str_t buf;
    int rc;
    RAII_VAR(struct ast_sip_transport_state *, state, find_or_create_temporary_state(transport), ao2_cleanup);
    if (!state) {
       return -1;
    }
    rc = pj_sockaddr_parse(pj_AF_UNSPEC(), 0, pj_cstr(&buf, var->value), &state->host);
    return rc != PJ_SUCCESS ? -1 : 0;
 }
transport_bind_to_str()
static int transport_bind_to_str (const void * obj, const intptr_t * args, char ** buf) static
Definition at line 1030 of file config_transport.c.
References ao2_cleanup, ast_calloc, find_state_by_transport(), MAX_OBJECT_FIELD, RAII_VAR, and internal_state::transport.
Referenced by ast_sip_initialize_sorcery_transport().
 {
    const struct ast_sip_transport *transport = obj;
    RAII_VAR(struct ast_sip_transport_state *, state, find_state_by_transport(transport), ao2_cleanup);
    if (!state) {
       return -1;
    }
    if (!(*buf = ast_calloc(MAX_OBJECT_FIELD, sizeof(char)))) {
       return -1;
    }
    /* include port as well as brackets if IPv6 */
    pj_sockaddr_print(&state->host, *buf, MAX_OBJECT_FIELD, 1 | 2);
    return 0;
 }
transport_localnet_handler()
static int transport_localnet_handler (const struct aco_option * opt, struct ast_variable * var, void * obj) static
Helper function which turns a cipher name into an identifier.
Custom handler for TLS cipher setting
Custom handler for localnet setting
Definition at line 1346 of file config_transport.c.
References ao2_cleanup, ast_append_ha(), ast_free_ha(), ast_strlen_zero, error(), find_or_create_temporary_state(), ast_sip_transport_state::localnet, NULL, RAII_VAR, internal_state::transport, and ast_variable::value.
Referenced by ast_sip_initialize_sorcery_transport().
 {
    struct ast_sip_transport *transport = obj;
    int error = 0;
    RAII_VAR(struct ast_sip_transport_state *, state, find_or_create_temporary_state(transport), ao2_cleanup);
    if (!state) {
       return -1;
    }
    if (ast_strlen_zero(var->value)) {
       ast_free_ha(state->localnet);
       state->localnet = NULL;
       return 0;
    }
    /* We use only the ast_apply_ha() which defaults to ALLOW
     * ("permit"), so we add DENY rules. */
    if (!(state->localnet = ast_append_ha("deny", var->value, state->localnet, &error))) {
       return -1;
    }
    return error;
 }
transport_protocol_handler()
static int transport_protocol_handler (const struct aco_option * opt, struct ast_variable * var, void * obj) static
Custom handler for turning a string protocol into an enum.
Definition at line 959 of file config_transport.c.
References ao2_cleanup, AST_TRANSPORT_TCP, AST_TRANSPORT_TLS, AST_TRANSPORT_UDP, AST_TRANSPORT_WS, AST_TRANSPORT_WSS, find_or_create_temporary_state(), ast_sip_transport::flow, RAII_VAR, internal_state::transport, ast_sip_transport::type, and ast_variable::value.
Referenced by ast_sip_initialize_sorcery_transport().
 {
    struct ast_sip_transport *transport = obj;
    RAII_VAR(struct ast_sip_transport_state *, state, find_or_create_temporary_state(transport), ao2_cleanup);
    if (!state) {
       return -1;
    }
    if (!strcasecmp(var->value, "flow")) {
       transport->flow = 1;
    } else {
       if (!strcasecmp(var->value, "udp")) {
          transport->type = AST_TRANSPORT_UDP;
       } else if (!strcasecmp(var->value, "tcp")) {
          transport->type = AST_TRANSPORT_TCP;
       } else if (!strcasecmp(var->value, "tls")) {
          transport->type = AST_TRANSPORT_TLS;
       } else if (!strcasecmp(var->value, "ws")) {
          transport->type = AST_TRANSPORT_WS;
       } else if (!strcasecmp(var->value, "wss")) {
          transport->type = AST_TRANSPORT_WSS;
       } else {
          return -1;
       }
       transport->flow = 0;
    }
    state->type = transport->type;
    return 0;
 }
transport_protocol_to_str()
static int transport_protocol_to_str (const void * obj, const intptr_t * args, char ** buf) static
Definition at line 1000 of file config_transport.c.
References ARRAY_IN_BOUNDS, ast_strdup, ast_sip_transport::flow, internal_state::transport, transport_types, and ast_sip_transport::type.
Referenced by ast_sip_initialize_sorcery_transport().
 {
    const struct ast_sip_transport *transport = obj;
    if (transport->flow) {
       *buf = ast_strdup("flow");
    } else if (ARRAY_IN_BOUNDS(transport->type, transport_types)) {
       *buf = ast_strdup(transport_types[transport->type]);
    }
    return 0;
 }
transport_state_cmp()
static int transport_state_cmp (void * obj, void * arg, int flags) static
comparator function for state objects
Definition at line 134 of file config_transport.c.
References ast_assert, CMP_MATCH, ast_sip_transport_state::id, OBJ_SEARCH_KEY, OBJ_SEARCH_MASK, OBJ_SEARCH_OBJECT, and OBJ_SEARCH_PARTIAL_KEY.
Referenced by ast_sip_get_transport_states().
 {
    const struct ast_sip_transport_state *object_left = obj;
    const struct ast_sip_transport_state *object_right = arg;
    const char *right_key = arg;
    int cmp;
    switch (flags & OBJ_SEARCH_MASK) {
    case OBJ_SEARCH_OBJECT:
       right_key = object_right->id;
       /* Fall through */
    case OBJ_SEARCH_KEY:
       cmp = strcmp(object_left->id, right_key);
       break;
    case OBJ_SEARCH_PARTIAL_KEY:
       /* Not supported by container. */
       ast_assert(0);
       return 0;
    default:
       cmp = 0;
       break;
    }
    if (cmp) {
       return 0;
    }
    return CMP_MATCH;
 }
transport_state_hash()
static int transport_state_hash (const void * obj, const int flags) static
hashing function for state objects
Definition at line 113 of file config_transport.c.
References ast_assert, ast_str_hash(), OBJ_SEARCH_KEY, OBJ_SEARCH_MASK, and OBJ_SEARCH_OBJECT.
Referenced by ast_sip_get_transport_states().
 {
    const struct ast_sip_transport_state *object;
    const char *key;
    switch (flags & OBJ_SEARCH_MASK) {
    case OBJ_SEARCH_KEY:
       key = obj;
       break;
    case OBJ_SEARCH_OBJECT:
       object = obj;
       key = object->id;
       break;
    default:
       ast_assert(0);
       return 0;
    }
    return ast_str_hash(key);
 }
transport_state_init()
static int transport_state_init (const struct aco_option * opt, struct ast_variable * var, void * obj) static
Custom handler for type just makes sure the state is created.
Definition at line 869 of file config_transport.c.
References ao2_cleanup, find_or_create_temporary_state(), and internal_state::transport.
Referenced by ast_sip_initialize_sorcery_transport().
 {
    struct ast_sip_transport *transport = obj;
    struct ast_sip_transport_state *state = find_or_create_temporary_state(transport);
    ao2_cleanup(state);
    return 0;
 }
transport_tls_bool_handler()
static int transport_tls_bool_handler (const struct aco_option * opt, struct ast_variable * var, void * obj) static
Custom handler for TLS boolean settings.
Definition at line 1050 of file config_transport.c.
References ao2_cleanup, ast_true(), find_or_create_temporary_state(), ast_variable::name, RAII_VAR, internal_state::transport, and ast_variable::value.
Referenced by ast_sip_initialize_sorcery_transport().
 {
    struct ast_sip_transport *transport = obj;
    RAII_VAR(struct ast_sip_transport_state *, state, find_or_create_temporary_state(transport), ao2_cleanup);
    if (!state) {
       return -1;
    }
    if (!strcasecmp(var->name, "verify_server")) {
       state->tls.verify_server = ast_true(var->value) ? PJ_TRUE : PJ_FALSE;
    } else if (!strcasecmp(var->name, "verify_client")) {
       state->tls.verify_client = ast_true(var->value) ? PJ_TRUE : PJ_FALSE;
    } else if (!strcasecmp(var->name, "require_client_cert")) {
       state->tls.require_client_cert = ast_true(var->value) ? PJ_TRUE : PJ_FALSE;
    } else {
       return -1;
    }
    return 0;
 }
transport_tls_file_handler()
static int transport_tls_file_handler (const struct aco_option * opt, struct ast_variable * var, void * obj) static
Custom handler for TLS method setting.
Definition at line 880 of file config_transport.c.
References ao2_cleanup, ast_file_is_readable(), ast_log, ast_sorcery_object_get_id(), ast_string_field_set, ast_strlen_zero, ast_sip_transport::ca_list_file, ast_sip_transport::ca_list_path, ast_sip_transport::cert_file, find_or_create_temporary_state(), LOG_ERROR, LOG_WARNING, ast_variable::name, ast_sip_transport::privkey_file, RAII_VAR, internal_state::transport, and ast_variable::value.
Referenced by ast_sip_initialize_sorcery_transport().
 {
    struct ast_sip_transport *transport = obj;
    RAII_VAR(struct ast_sip_transport_state *, state, find_or_create_temporary_state(transport), ao2_cleanup);
    if (!state) {
       return -1;
    }
    if (ast_strlen_zero(var->value)) {
       /* Ignore empty options */
       return 0;
    }
    if (!ast_file_is_readable(var->value)) {
       ast_log(LOG_ERROR, "Transport: %s: %s %s is either missing or not readable\n",
          ast_sorcery_object_get_id(obj), var->name, var->value);
       return -1;
    }
    if (!strcasecmp(var->name, "ca_list_file")) {
       state->tls.ca_list_file = pj_str((char*)var->value);
       ast_string_field_set(transport, ca_list_file, var->value);
    } else if (!strcasecmp(var->name, "ca_list_path")) {
 #ifdef HAVE_PJ_SSL_CERT_LOAD_FROM_FILES2
       state->tls.ca_list_path = pj_str((char*)var->value);
       ast_string_field_set(transport, ca_list_path, var->value);
 #else
       ast_log(LOG_WARNING, "Asterisk has been built against a version of pjproject that does not "
             "support the 'ca_list_path' option. Please upgrade to version 2.4 or later.\n");
 #endif
    } else if (!strcasecmp(var->name, "cert_file")) {
       state->tls.cert_file = pj_str((char*)var->value);
       ast_string_field_set(transport, cert_file, var->value);
    } else if (!strcasecmp(var->name, "priv_key_file")) {
       state->tls.privkey_file = pj_str((char*)var->value);
       ast_string_field_set(transport, privkey_file, var->value);
    }
    return 0;
 }
transport_tls_method_handler()
static int transport_tls_method_handler (const struct aco_option * opt, struct ast_variable * var, void * obj) static
Custom handler for TLS method setting.
Definition at line 1115 of file config_transport.c.
References ao2_cleanup, ast_strlen_zero, find_or_create_temporary_state(), RAII_VAR, internal_state::transport, and ast_variable::value.
Referenced by ast_sip_initialize_sorcery_transport().
 {
    struct ast_sip_transport *transport = obj;
    RAII_VAR(struct ast_sip_transport_state *, state, find_or_create_temporary_state(transport), ao2_cleanup);
    if (!state) {
       return -1;
    }
    if (ast_strlen_zero(var->value) || !strcasecmp(var->value, "default")) {
       state->tls.method = PJSIP_SSL_DEFAULT_METHOD;
    } else if (!strcasecmp(var->value, "unspecified")) {
       state->tls.method = PJSIP_SSL_UNSPECIFIED_METHOD;
    } else if (!strcasecmp(var->value, "tlsv1")) {
       state->tls.method = PJSIP_TLSV1_METHOD;
 #ifdef HAVE_PJSIP_TLS_TRANSPORT_PROTO
    } else if (!strcasecmp(var->value, "tlsv1_1")) {
       state->tls.method = PJSIP_TLSV1_1_METHOD;
    } else if (!strcasecmp(var->value, "tlsv1_2")) {
       state->tls.method = PJSIP_TLSV1_2_METHOD;
 #endif
    } else if (!strcasecmp(var->value, "sslv2")) {
       state->tls.method = PJSIP_SSLV2_METHOD;
    } else if (!strcasecmp(var->value, "sslv3")) {
       state->tls.method = PJSIP_SSLV3_METHOD;
    } else if (!strcasecmp(var->value, "sslv23")) {
       state->tls.method = PJSIP_SSLV23_METHOD;
    } else {
       return -1;
    }
    return 0;
 }
transport_tos_handler()
static int transport_tos_handler (const struct aco_option * opt, struct ast_variable * var, void * obj) static
Custom handler for TOS setting.
Definition at line 1419 of file config_transport.c.
References ast_log, ast_sorcery_object_get_id(), ast_str2tos(), LOG_ERROR, LOG_WARNING, ast_sip_transport::tos, internal_state::transport, value, and ast_variable::value.
Referenced by ast_sip_initialize_sorcery_transport().
 {
    struct ast_sip_transport *transport = obj;
    unsigned int value;
    if (ast_str2tos(var->value, &value)) {
       ast_log(LOG_ERROR, "Error configuring transport '%s' - Could not "
          "interpret 'tos' value '%s'\n",
          ast_sorcery_object_get_id(transport), var->value);
       return -1;
    }
    if (value % 4) {
       value = value >> 2;
       value = value << 2;
       ast_log(LOG_WARNING,
          "transport '%s' - 'tos' value '%s' uses bits that are "
          "discarded when converted to DSCP. Using equivalent %u instead.\n",
          ast_sorcery_object_get_id(transport), var->value, value);
    }
    transport->tos = value;
    return 0;
 }
verify_client_to_str()
static int verify_client_to_str (const void * obj, const intptr_t * args, char ** buf) static
Definition at line 1086 of file config_transport.c.
References ao2_cleanup, ast_strdup, AST_YESNO, find_state_by_transport(), RAII_VAR, and internal_state::transport.
Referenced by ast_sip_initialize_sorcery_transport().
 {
    const struct ast_sip_transport *transport = obj;
    RAII_VAR(struct ast_sip_transport_state *, state, find_state_by_transport(transport), ao2_cleanup);
    if (!state) {
       return -1;
    }
    *buf = ast_strdup(AST_YESNO(state->tls.verify_client));
    return 0;
 }
verify_server_to_str()
static int verify_server_to_str (const void * obj, const intptr_t * args, char ** buf) static
Definition at line 1072 of file config_transport.c.
References ao2_cleanup, ast_strdup, AST_YESNO, find_state_by_transport(), RAII_VAR, and internal_state::transport.
Referenced by ast_sip_initialize_sorcery_transport().
 {
    const struct ast_sip_transport *transport = obj;
    RAII_VAR(struct ast_sip_transport_state *, state, find_state_by_transport(transport), ao2_cleanup);
    if (!state) {
       return -1;
    }
    *buf = ast_strdup(AST_YESNO(state->tls.verify_server));
    return 0;
 }
Variable Documentation
cli_commands
struct ast_cli_entry cli_commands[] static
Definition at line 1542 of file config_transport.c.
cli_formatter
struct ast_sip_cli_formatter_entry* cli_formatter static
Definition at line 1562 of file config_transport.c.
endpoint_transport_formatter
struct ast_sip_endpoint_formatter endpoint_transport_formatter
Initial value:
= {
   .format_ami = format_ami_endpoint_transport
}
Definition at line 202 of file config_transport.c.
temp_state_store
struct ast_threadstorage temp_state_store = { .once = PTHREAD_ONCE_INIT , .key_init = __init_temp_state_store , .custom_init = NULL , } static
Definition at line 60 of file config_transport.c.
Referenced by find_or_create_temporary_state(), find_temporary_state(), and remove_temporary_state().
tls_method_map
const char* tls_method_map[] static
Definition at line 1149 of file config_transport.c.
Referenced by tls_method_to_str().
transport_states
struct ao2_container* transport_states static
Definition at line 40 of file config_transport.c.
Referenced by anonymous_identify(), find_endpoint(), get_udp_transport(), get_write_timeout(), and process_nat().
transport_types
const char* transport_types[] static
Definition at line 992 of file config_transport.c.
Referenced by cli_print_body(), and transport_protocol_to_str().