Asterisk - The Open Source Telephony Project: res_mwi_external.h File Reference
res_mwi_external.h File Reference
Core external MWI support.
Macros
#define ast_mwi_mailbox_unref(mailbox) ao2_ref((struct ast_mwi_mailbox_object *) mailbox, -1)
Convienience unref function for mailbox object.
Functions
struct ast_mwi_mailbox_object * ast_mwi_mailbox_alloc (const char *mailbox_id)
Allocate an external MWI object.
struct ast_mwi_mailbox_object * ast_mwi_mailbox_copy (const struct ast_mwi_mailbox_object *mailbox)
Copy the external MWI counts object.
int ast_mwi_mailbox_delete (const char *mailbox_id)
Delete matching external MWI object.
int ast_mwi_mailbox_delete_all (void)
Delete all external MWI objects.
int ast_mwi_mailbox_delete_by_regex (const char *regex)
Delete all external MWI objects selected by the regular expression.
const struct ast_mwi_mailbox_object * ast_mwi_mailbox_get (const char *mailbox_id)
Get matching external MWI object.
struct ao2_container * ast_mwi_mailbox_get_all (void)
Get all external MWI objects.
struct ao2_container * ast_mwi_mailbox_get_by_regex (const char *regex)
Get all external MWI objects selected by the regular expression.
const char * ast_mwi_mailbox_get_id (const struct ast_mwi_mailbox_object *mailbox)
Get mailbox id.
unsigned int ast_mwi_mailbox_get_msgs_new (const struct ast_mwi_mailbox_object *mailbox)
Get the number of new messages.
unsigned int ast_mwi_mailbox_get_msgs_old (const struct ast_mwi_mailbox_object *mailbox)
Get the number of old messages.
void ast_mwi_mailbox_set_msgs_new (struct ast_mwi_mailbox_object *mailbox, unsigned int num_msgs)
Set the number of new messages.
void ast_mwi_mailbox_set_msgs_old (struct ast_mwi_mailbox_object *mailbox, unsigned int num_msgs)
Set the number of old messages.
int ast_mwi_mailbox_update (struct ast_mwi_mailbox_object *mailbox)
Update the external MWI counts with the given object.
Detailed Description
Core external MWI support.
Author
Richard Mudgett rmudg.nosp@m.ett@.nosp@m.digiu.nosp@m.m.co.nosp@m.m
See Also:
CREDITS
Definition in file res_mwi_external.h.
Macro Definition Documentation
ast_mwi_mailbox_unref
#define ast_mwi_mailbox_unref (mailbox) ao2_ref((struct ast_mwi_mailbox_object *) mailbox, -1)
Convienience unref function for mailbox object.
Definition at line 42 of file res_mwi_external.h.
Referenced by ast_mwi_mailbox_delete(), ast_mwi_mailbox_update(), mwi_has_voicemail(), mwi_inboxcount(), mwi_initial_events(), mwi_mailbox_delete_all(), mwi_mailbox_get(), mwi_mailbox_update(), mwi_messagecount(), stasis_app_mailbox_delete(), stasis_app_mailbox_to_json(), stasis_app_mailbox_update(), and stasis_app_mailboxes_to_json().
Function Documentation
ast_mwi_mailbox_alloc()
struct ast_mwi_mailbox_object* ast_mwi_mailbox_alloc (const char * mailbox_id)
Allocate an external MWI object.
Since
12.1.0
Parameters
mailbox_id Name of mailbox.
Return values
object on success. The object is an ao2 object.
NULL on error.
Definition at line 196 of file res_mwi_external.c.
References ast_sorcery_alloc(), ast_strlen_zero, MWI_MAILBOX_TYPE, and NULL.
Referenced by mwi_mailbox_update(), and stasis_app_mailbox_update().
 {
    if (ast_strlen_zero(mailbox_id)) {
       return NULL;
    }
    return ast_sorcery_alloc(mwi_sorcery, MWI_MAILBOX_TYPE, mailbox_id);
 }
ast_mwi_mailbox_copy()
struct ast_mwi_mailbox_object* ast_mwi_mailbox_copy (const struct ast_mwi_mailbox_object * mailbox)
Copy the external MWI counts object.
Since
12.1.0
Parameters
mailbox What to copy.
Return values
copy on success. The object is an ao2 object.
NULL on error.
Definition at line 205 of file res_mwi_external.c.
References ast_sorcery_copy().
 {
    return ast_sorcery_copy(mwi_sorcery, mailbox);
 }
ast_mwi_mailbox_delete()
int ast_mwi_mailbox_delete (const char * mailbox_id)
Delete matching external MWI object.
Since
12.1.0
Parameters
mailbox_id Name of mailbox to delete.
Return values
0 on success.
-1 on error.
Definition at line 310 of file res_mwi_external.c.
References ast_mwi_mailbox_get(), ast_mwi_mailbox_unref, ast_strlen_zero, mailbox, and mwi_mailbox_delete().
Referenced by mwi_mailbox_delete(), and stasis_app_mailbox_delete().
 {
    const struct ast_mwi_mailbox_object *mailbox;
    if (ast_strlen_zero(mailbox_id)) {
       return -1;
    }
    mailbox = ast_mwi_mailbox_get(mailbox_id);
    if (mailbox) {
       mwi_mailbox_delete((struct ast_mwi_mailbox_object *) mailbox);
       ast_mwi_mailbox_unref(mailbox);
    }
    return 0;
 }
ast_mwi_mailbox_delete_all()
int ast_mwi_mailbox_delete_all (void)
Delete all external MWI objects.
Since
12.1.0
Return values
0 on success.
-1 on error.
Definition at line 286 of file res_mwi_external.c.
References ao2_ref, ast_mwi_mailbox_get_all(), mailboxes, and mwi_mailbox_delete_all().
 {
    struct ao2_container *mailboxes;
    mailboxes = ast_mwi_mailbox_get_all();
    if (mailboxes) {
       mwi_mailbox_delete_all(mailboxes);
       ao2_ref(mailboxes, -1);
    }
    return 0;
 }
ast_mwi_mailbox_delete_by_regex()
int ast_mwi_mailbox_delete_by_regex (const char * regex)
Delete all external MWI objects selected by the regular expression.
Since
12.1.0
Parameters
regex Regular expression in extended syntax. (NULL is same as "")
Note
The provided regex is treated as extended case sensitive.
Return values
0 on success.
-1 on error.
Definition at line 298 of file res_mwi_external.c.
References ao2_ref, ast_mwi_mailbox_get_by_regex(), mailboxes, and mwi_mailbox_delete_all().
Referenced by mwi_mailbox_delete().
 {
    struct ao2_container *mailboxes;
    mailboxes = ast_mwi_mailbox_get_by_regex(regex);
    if (mailboxes) {
       mwi_mailbox_delete_all(mailboxes);
       ao2_ref(mailboxes, -1);
    }
    return 0;
 }
ast_mwi_mailbox_get()
const struct ast_mwi_mailbox_object* ast_mwi_mailbox_get (const char * mailbox_id)
Get matching external MWI object.
Since
12.1.0
Parameters
mailbox_id Name of mailbox to retrieve.
Return values
requested mailbox on success. The object is an ao2 object.
NULL on error or no mailbox.
Note
The object must be treated as read-only.
Definition at line 187 of file res_mwi_external.c.
References ast_sorcery_retrieve_by_id(), ast_strlen_zero, MWI_MAILBOX_TYPE, and NULL.
Referenced by ast_mwi_mailbox_delete(), mwi_has_voicemail(), mwi_inboxcount(), mwi_mailbox_get(), mwi_messagecount(), stasis_app_mailbox_delete(), and stasis_app_mailbox_to_json().
 {
    if (ast_strlen_zero(mailbox_id)) {
       return NULL;
    }
    return ast_sorcery_retrieve_by_id(mwi_sorcery, MWI_MAILBOX_TYPE, mailbox_id);
 }
ast_mwi_mailbox_get_all()
struct ao2_container* ast_mwi_mailbox_get_all (void)
Get all external MWI objects.
Since
12.1.0
Return values
container of struct ast_mwi_mailbox_object on success.
NULL on error.
Note
The objects in the container must be treated as read-only.
Definition at line 176 of file res_mwi_external.c.
References AST_RETRIEVE_FLAG_ALL, AST_RETRIEVE_FLAG_MULTIPLE, ast_sorcery_retrieve_by_fields(), MWI_MAILBOX_TYPE, and NULL.
Referenced by ast_mwi_mailbox_delete_all(), mwi_initial_events(), and stasis_app_mailboxes_to_json().
 {
    return ast_sorcery_retrieve_by_fields(mwi_sorcery, MWI_MAILBOX_TYPE,
       AST_RETRIEVE_FLAG_MULTIPLE | AST_RETRIEVE_FLAG_ALL, NULL);
 }
ast_mwi_mailbox_get_by_regex()
struct ao2_container* ast_mwi_mailbox_get_by_regex (const char * regex)
Get all external MWI objects selected by the regular expression.
Since
12.1.0
Parameters
regex Regular expression in extended syntax. (NULL is same as "")
Note
The provided regex is treated as extended case sensitive.
Return values
container of struct ast_mwi_mailbox_object on success.
NULL on error.
Note
The objects in the container must be treated as read-only.
Definition at line 182 of file res_mwi_external.c.
References ast_sorcery_retrieve_by_regex(), and MWI_MAILBOX_TYPE.
Referenced by ast_mwi_mailbox_delete_by_regex(), and mwi_mailbox_get().
 {
    return ast_sorcery_retrieve_by_regex(mwi_sorcery, MWI_MAILBOX_TYPE, regex ?: "");
 }
ast_mwi_mailbox_get_id()
const char* ast_mwi_mailbox_get_id (const struct ast_mwi_mailbox_object * mailbox)
Get mailbox id.
Since
12.1.0
Parameters
mailbox Object to get id.
Returns
mailbox_id of the object.
Note
This should never return NULL unless there is a bug in sorcery.
Definition at line 210 of file res_mwi_external.c.
References ast_sorcery_object_get_id().
Referenced by mailbox_to_json(), and mwi_mailbox_get().
 {
    return ast_sorcery_object_get_id(mailbox);
 }
ast_mwi_mailbox_get_msgs_new()
unsigned int ast_mwi_mailbox_get_msgs_new (const struct ast_mwi_mailbox_object * mailbox)
Get the number of new messages.
Since
12.1.0
Parameters
mailbox Object to get number of new messages.
Returns
Number of new messages.
Definition at line 215 of file res_mwi_external.c.
References ast_mwi_mailbox_object::msgs_new.
Referenced by mailbox_to_json(), and mwi_mailbox_get().
 {
    return mailbox->msgs_new;
 }
ast_mwi_mailbox_get_msgs_old()
unsigned int ast_mwi_mailbox_get_msgs_old (const struct ast_mwi_mailbox_object * mailbox)
Get the number of old messages.
Since
12.1.0
Parameters
mailbox Object to get number of old messages.
Returns
Number of old messages.
Definition at line 220 of file res_mwi_external.c.
References ast_mwi_mailbox_object::msgs_old.
Referenced by mailbox_to_json(), and mwi_mailbox_get().
 {
    return mailbox->msgs_old;
 }
ast_mwi_mailbox_set_msgs_new()
void ast_mwi_mailbox_set_msgs_new (struct ast_mwi_mailbox_object * mailbox, unsigned int num_msgs)
Set the number of new messages.
Since
12.1.0
Parameters
mailbox Object to set number of new messages.
num_msgs Number of messages to set.
Returns
Nothing
Definition at line 225 of file res_mwi_external.c.
References ast_mwi_mailbox_object::msgs_new.
Referenced by mwi_mailbox_update(), and stasis_app_mailbox_update().
 {
    mailbox->msgs_new = num_msgs;
 }
ast_mwi_mailbox_set_msgs_old()
void ast_mwi_mailbox_set_msgs_old (struct ast_mwi_mailbox_object * mailbox, unsigned int num_msgs)
Set the number of old messages.
Since
12.1.0
Parameters
mailbox Object to set number of old messages.
num_msgs Number of messages to set.
Returns
Nothing
Definition at line 230 of file res_mwi_external.c.
References ast_mwi_mailbox_object::msgs_old.
Referenced by mwi_mailbox_update(), and stasis_app_mailbox_update().
 {
    mailbox->msgs_old = num_msgs;
 }
ast_mwi_mailbox_update()
int ast_mwi_mailbox_update (struct ast_mwi_mailbox_object * mailbox)
Update the external MWI counts with the given object.
Since
12.1.0
Parameters
mailbox What to update.
Return values
0 on success.
-1 on error.
Definition at line 235 of file res_mwi_external.c.
References ast_mwi_mailbox_unref, ast_sorcery_create(), ast_sorcery_object_get_id(), ast_sorcery_retrieve_by_id(), ast_sorcery_update(), exists(), and MWI_MAILBOX_TYPE.
Referenced by mwi_mailbox_update(), and stasis_app_mailbox_update().
 {
    const struct ast_mwi_mailbox_object *exists;
    int res;
    exists = ast_sorcery_retrieve_by_id(mwi_sorcery, MWI_MAILBOX_TYPE,
       ast_sorcery_object_get_id(mailbox));
    if (exists) {
       res = ast_sorcery_update(mwi_sorcery, mailbox);
       ast_mwi_mailbox_unref(exists);
    } else {
       res = ast_sorcery_create(mwi_sorcery, mailbox);
    }
    return res;
 }