Asterisk - The Open Source Telephony Project: codec_builtin.c File Reference
codec_builtin.c File Reference
Built-in supported codecs.
#include "asterisk.h"
#include "asterisk/ilbc.h"
#include "asterisk/logger.h"
#include "asterisk/astobj2.h"
#include "asterisk/codec.h"
#include "asterisk/format.h"
#include "asterisk/format_cache.h"
#include "asterisk/frame.h"
#include "asterisk/smoother.h"
Macros
#define CODEC_REGISTER_AND_CACHE(codec)
#define CODEC_REGISTER_AND_CACHE_NAMED(fmt_name, codec)
#define TYPE_MASK 0x3
Enumerations
enum frame_type { TYPE_HIGH, TYPE_LOW, TYPE_SILENCE, TYPE_DONTSEND }
Functions
int __ast_codec_register_with_format (struct ast_codec *codec, const char *format_name, struct ast_module *mod)
int ast_codec_builtin_init (void)
Initialize built-in codecs within the core.
static int codec2_length (unsigned int samples)
static int codec2_samples (struct ast_frame *frame)
static int g719_length (unsigned int samples)
static int g719_samples (struct ast_frame *frame)
static int g723_len (unsigned char buf)
static int g723_length (unsigned int samples)
static int g723_samples (struct ast_frame *frame)
static int g726_length (unsigned int samples)
static int g726_samples (struct ast_frame *frame)
static int g729_length (unsigned int samples)
static int g729_samples (struct ast_frame *frame)
static unsigned char get_n_bits_at (unsigned char *data, int n, int bit)
static int gsm_length (unsigned int samples)
static int gsm_samples (struct ast_frame *frame)
static int ilbc_samples (struct ast_frame *frame)
static int lpc10_samples (struct ast_frame *frame)
static int none_length (unsigned int samples)
static int none_samples (struct ast_frame *frame)
static int opus_samples (struct ast_frame *frame)
static int silk_samples (struct ast_frame *frame)
static int siren14_length (unsigned int samples)
static int siren14_samples (struct ast_frame *frame)
static int siren7_length (unsigned int samples)
static int siren7_samples (struct ast_frame *frame)
static int slin_length (unsigned int samples)
static int slin_samples (struct ast_frame *frame)
static int speex16_samples (struct ast_frame *frame)
static int speex32_samples (struct ast_frame *frame)
static int speex8_samples (struct ast_frame *frame)
static int speex_get_wb_sz_at (unsigned char *data, int len, int bit)
static int speex_samples (unsigned char *data, int len)
static int ulaw_length (unsigned int samples)
static int ulaw_samples (struct ast_frame *frame)
Variables
static struct ast_codec adpcm
static struct ast_codec alaw
static struct ast_codec codec2
static struct ast_codec g719
static struct ast_codec g722
static struct ast_codec g723
static struct ast_codec g726aal2
static struct ast_codec g726rfc3551
static struct ast_codec g729a
static struct ast_codec gsm
static struct ast_codec h261
static struct ast_codec h263
static struct ast_codec h263p
static struct ast_codec h264
static struct ast_codec h265
static struct ast_codec ilbc
static struct ast_codec jpeg
static struct ast_codec lpc10
static struct ast_codec mpeg4
static struct ast_codec none
static struct ast_codec opus
static struct ast_codec png
static struct ast_codec silk12
static struct ast_codec silk16
static struct ast_codec silk24
static struct ast_codec silk8
static struct ast_codec siren14
static struct ast_codec siren7
static struct ast_codec slin12
static struct ast_codec slin16
static struct ast_codec slin192
static struct ast_codec slin24
static struct ast_codec slin32
static struct ast_codec slin44
static struct ast_codec slin48
static struct ast_codec slin8
static struct ast_codec slin96
static struct ast_codec speex16
static struct ast_codec speex32
static struct ast_codec speex8
static struct ast_codec t140
static struct ast_codec t140red
static struct ast_codec t38
static struct ast_codec testlaw
static struct ast_codec ulaw
static struct ast_codec vp8
static struct ast_codec vp9
Detailed Description
Built-in supported codecs.
Author
Joshua Colp jcolp.nosp@m.@dig.nosp@m.ium.c.nosp@m.om
Definition in file codec_builtin.c.
Macro Definition Documentation
CODEC_REGISTER_AND_CACHE
#define CODEC_REGISTER_AND_CACHE (codec)
Definition at line 914 of file codec_builtin.c.
Referenced by ast_codec_builtin_init().
CODEC_REGISTER_AND_CACHE_NAMED
#define CODEC_REGISTER_AND_CACHE_NAMED (fmt_name, codec)
Definition at line 928 of file codec_builtin.c.
Referenced by ast_codec_builtin_init().
TYPE_MASK
#define TYPE_MASK 0x3
Definition at line 51 of file codec_builtin.c.
Referenced by g723_len().
Enumeration Type Documentation
frame_type
enum frame_type
Enumerator
TYPE_HIGH
TYPE_LOW
TYPE_SILENCE
TYPE_DONTSEND
Definition at line 44 of file codec_builtin.c.
                 {
    TYPE_HIGH,     /* 0x0 */
    TYPE_LOW,      /* 0x1 */
    TYPE_SILENCE,  /* 0x2 */
    TYPE_DONTSEND  /* 0x3 */
 };
Function Documentation
__ast_codec_register_with_format()
int __ast_codec_register_with_format (struct ast_codec * codec, const char * format_name, struct ast_module * mod)
Definition at line 277 of file codec.c.
References AO2_ALLOC_OPT_LOCK_NOLOCK, ao2_find, ao2_link_flags, ao2_ref, ao2_t_alloc_options, ast_codec_media_type2str(), ast_log, AST_MEDIA_TYPE_AUDIO, AST_MEDIA_TYPE_UNKNOWN, ast_module_shutdown_ref, ast_verb, codec_dtor(), codec_id, ast_codec::description, internal_ast_codec::external, internal_ast_codec::format_name, ast_codec::id, lock, LOG_ERROR, ast_codec::name, OBJ_NOLOCK, OBJ_SEARCH_OBJECT, S_OR, ast_codec::sample_rate, SCOPED_AO2WRLOCK, and ast_codec::type.
Referenced by __ast_codec_register().
 {
    SCOPED_AO2WRLOCK(lock, codecs);
    struct internal_ast_codec *codec_new;
    /* Some types have specific requirements */
    if (codec->type == AST_MEDIA_TYPE_UNKNOWN) {
       ast_log(LOG_ERROR, "A media type must be specified for codec '%s'\n", codec->name);
       return -1;
    } else if (codec->type == AST_MEDIA_TYPE_AUDIO) {
       if (!codec->sample_rate) {
          ast_log(LOG_ERROR, "A sample rate must be specified for codec '%s' of type '%s'\n",
             codec->name, ast_codec_media_type2str(codec->type));
          return -1;
       }
    }
    codec_new = ao2_find(codecs, codec, OBJ_SEARCH_OBJECT | OBJ_NOLOCK);
    if (codec_new) {
       ast_log(LOG_ERROR, "A codec with name '%s' of type '%s' and sample rate '%u' is already registered\n",
          codec->name, ast_codec_media_type2str(codec->type), codec->sample_rate);
       ao2_ref(codec_new, -1);
       return -1;
    }
    codec_new = ao2_t_alloc_options(sizeof(*codec_new), codec_dtor,
       AO2_ALLOC_OPT_LOCK_NOLOCK, S_OR(codec->description, ""));
    if (!codec_new) {
       ast_log(LOG_ERROR, "Could not allocate a codec with name '%s' of type '%s' and sample rate '%u'\n",
          codec->name, ast_codec_media_type2str(codec->type), codec->sample_rate);
       return -1;
    }
    codec_new->external = *codec;
    codec_new->format_name = format_name;
    codec_new->external.id = codec_id++;
    ao2_link_flags(codecs, codec_new, OBJ_NOLOCK);
    /* Once registered a codec can not be unregistered, and the module must persist until shutdown */
    ast_module_shutdown_ref(mod);
    ast_verb(2, "Registered '%s' codec '%s' at sample rate '%u' with id '%u'\n",
       ast_codec_media_type2str(codec->type), codec->name, codec->sample_rate, codec_new->external.id);
    ao2_ref(codec_new, -1);
    return 0;
 }
ast_codec_builtin_init()
int ast_codec_builtin_init (void)
Initialize built-in codecs within the core.
Return values
0 success
-1 failure
Definition at line 942 of file codec_builtin.c.
References CODEC_REGISTER_AND_CACHE, and CODEC_REGISTER_AND_CACHE_NAMED.
Referenced by asterisk_daemon().
 {
    int res = 0;
    res |= CODEC_REGISTER_AND_CACHE(codec2);
    res |= CODEC_REGISTER_AND_CACHE(g723);
    res |= CODEC_REGISTER_AND_CACHE(ulaw);
    res |= CODEC_REGISTER_AND_CACHE(alaw);
    res |= CODEC_REGISTER_AND_CACHE(gsm);
    res |= CODEC_REGISTER_AND_CACHE(g726rfc3551);
    res |= CODEC_REGISTER_AND_CACHE(g726aal2);
    res |= CODEC_REGISTER_AND_CACHE(adpcm);
    res |= CODEC_REGISTER_AND_CACHE(slin8);
    res |= CODEC_REGISTER_AND_CACHE_NAMED("slin12", slin12);
    res |= CODEC_REGISTER_AND_CACHE_NAMED("slin16", slin16);
    res |= CODEC_REGISTER_AND_CACHE_NAMED("slin24", slin24);
    res |= CODEC_REGISTER_AND_CACHE_NAMED("slin32", slin32);
    res |= CODEC_REGISTER_AND_CACHE_NAMED("slin44", slin44);
    res |= CODEC_REGISTER_AND_CACHE_NAMED("slin48", slin48);
    res |= CODEC_REGISTER_AND_CACHE_NAMED("slin96", slin96);
    res |= CODEC_REGISTER_AND_CACHE_NAMED("slin192", slin192);
    res |= CODEC_REGISTER_AND_CACHE(lpc10);
    res |= CODEC_REGISTER_AND_CACHE(g729a);
    res |= CODEC_REGISTER_AND_CACHE(speex8);
    res |= CODEC_REGISTER_AND_CACHE_NAMED("speex16", speex16);
    res |= CODEC_REGISTER_AND_CACHE_NAMED("speex32", speex32);
    res |= CODEC_REGISTER_AND_CACHE(ilbc);
    res |= CODEC_REGISTER_AND_CACHE(g722);
    res |= CODEC_REGISTER_AND_CACHE(siren7);
    res |= CODEC_REGISTER_AND_CACHE(siren14);
    res |= CODEC_REGISTER_AND_CACHE(testlaw);
    res |= CODEC_REGISTER_AND_CACHE(g719);
    res |= CODEC_REGISTER_AND_CACHE(opus);
    res |= CODEC_REGISTER_AND_CACHE(jpeg);
    res |= CODEC_REGISTER_AND_CACHE(png);
    res |= CODEC_REGISTER_AND_CACHE(h261);
    res |= CODEC_REGISTER_AND_CACHE(h263);
    res |= CODEC_REGISTER_AND_CACHE(h263p);
    res |= CODEC_REGISTER_AND_CACHE(h264);
    res |= CODEC_REGISTER_AND_CACHE(h265);
    res |= CODEC_REGISTER_AND_CACHE(mpeg4);
    res |= CODEC_REGISTER_AND_CACHE(vp8);
    res |= CODEC_REGISTER_AND_CACHE(vp9);
    res |= CODEC_REGISTER_AND_CACHE(t140red);
    res |= CODEC_REGISTER_AND_CACHE(t140);
    res |= CODEC_REGISTER_AND_CACHE(t38);
    res |= CODEC_REGISTER_AND_CACHE(none);
    res |= CODEC_REGISTER_AND_CACHE_NAMED("silk8", silk8);
    res |= CODEC_REGISTER_AND_CACHE_NAMED("silk12", silk12);
    res |= CODEC_REGISTER_AND_CACHE_NAMED("silk16", silk16);
    res |= CODEC_REGISTER_AND_CACHE_NAMED("silk24", silk24);
    return res;
 }
codec2_length()
static int codec2_length (unsigned int samples) static
Definition at line 115 of file codec_builtin.c.
 {
    return (samples / 160) * 6;
 }
codec2_samples()
static int codec2_samples (struct ast_frame * frame) static
Definition at line 110 of file codec_builtin.c.
References ast_frame::datalen.
 {
    return 160 * (frame->datalen / 6);
 }
g719_length()
static int g719_length (unsigned int samples) static
Definition at line 724 of file codec_builtin.c.
 {
    return (int) samples / ((float) 48000 / 8000);
 }
g719_samples()
static int g719_samples (struct ast_frame * frame) static
Definition at line 719 of file codec_builtin.c.
References ast_frame::datalen.
 {
    return (int) frame->datalen * ((float) 48000 / 8000);
 }
g723_len()
static int g723_len (unsigned char buf) static
Definition at line 53 of file codec_builtin.c.
References ast_log, LOG_WARNING, type, TYPE_DONTSEND, TYPE_HIGH, TYPE_LOW, TYPE_MASK, and TYPE_SILENCE.
Referenced by g723_samples().
 {
    enum frame_type type = buf & TYPE_MASK;
    switch(type) {
    case TYPE_DONTSEND:
       return 0;
       break;
    case TYPE_SILENCE:
       return 4;
       break;
    case TYPE_HIGH:
       return 24;
       break;
    case TYPE_LOW:
       return 20;
       break;
    default:
       ast_log(LOG_WARNING, "Badly encoded frame (%u)\n", type);
    }
    return -1;
 }
g723_length()
static int g723_length (unsigned int samples) static
Definition at line 92 of file codec_builtin.c.
 {
    return (samples / 240) * 20;
 }
g723_samples()
static int g723_samples (struct ast_frame * frame) static
Definition at line 76 of file codec_builtin.c.
References buf, ast_frame::data, g723_len(), and ast_frame::ptr.
 {
    unsigned char *buf = frame->data.ptr;
    int pos = 0, samples = 0, res;
    while(pos < frame->datalen) {
       res = g723_len(buf[pos]);
       if (res <= 0)
          break;
       samples += 240;
       pos += res;
    }
    return samples;
 }
g726_length()
static int g726_length (unsigned int samples) static
Definition at line 223 of file codec_builtin.c.
 {
    return samples / 2;
 }
g726_samples()
static int g726_samples (struct ast_frame * frame) static
Definition at line 218 of file codec_builtin.c.
References ast_frame::datalen.
 {
    return frame->datalen * 2;
 }
g729_length()
static int g729_length (unsigned int samples) static
Definition at line 443 of file codec_builtin.c.
 {
    return samples / 8;
 }
g729_samples()
static int g729_samples (struct ast_frame * frame) static
Definition at line 438 of file codec_builtin.c.
References ast_frame::datalen.
 {
    return frame->datalen * 8;
 }
get_n_bits_at()
static unsigned char get_n_bits_at (unsigned char * data, int n, int bit) static
Definition at line 462 of file codec_builtin.c.
Referenced by speex_get_wb_sz_at(), and speex_samples().
 {
    int byte = bit / 8;       /* byte containing first bit */
    int rem = 8 - (bit % 8);  /* remaining bits in first byte */
    unsigned char ret = 0;
    if (n <= 0 || n > 8)
       return 0;
    if (rem < n) {
       ret = (data[byte] << (n - rem));
       ret |= (data[byte + 1] >> (8 - n + rem));
    } else {
       ret = (data[byte] >> (rem - n));
    }
    return (ret & (0xff >> (8 - n)));
 }
gsm_length()
static int gsm_length (unsigned int samples) static
Definition at line 199 of file codec_builtin.c.
 {
    return (samples / 160) * 33;
 }
gsm_samples()
static int gsm_samples (struct ast_frame * frame) static
Definition at line 194 of file codec_builtin.c.
References ast_frame::datalen.
 {
    return 160 * (frame->datalen / 33);
 }
ilbc_samples()
static int ilbc_samples (struct ast_frame * frame) static
Definition at line 622 of file codec_builtin.c.
References ast_format_get_attribute_data(), ast_format_get_sample_rate(), ast_frame::datalen, ast_frame_subclass::format, ilbc_attr::mode, and ast_frame::subclass.
 {
    struct ilbc_attr *attr = ast_format_get_attribute_data(frame->subclass.format);
    const unsigned int mode = attr ? attr->mode : 30;
    const unsigned int samples_per_frame = mode * ast_format_get_sample_rate(frame->subclass.format) / 1000;
    const unsigned int octets_per_frame = (mode == 20) ? 38 : 50;
    return samples_per_frame * frame->datalen / octets_per_frame;
 }
lpc10_samples()
static int lpc10_samples (struct ast_frame * frame) static
Definition at line 415 of file codec_builtin.c.
References ast_frame::data, and ast_frame::ptr.
 {
    int samples = 22 * 8;
    /* assumes that the RTP packet contains one LPC10 frame */
    samples += (((char *)(frame->data.ptr))[7] & 0x1) * 8;
    return samples;
 }
none_length()
static int none_length (unsigned int samples) static
Definition at line 139 of file codec_builtin.c.
{
    return samples;
 }
none_samples()
static int none_samples (struct ast_frame * frame) static
Definition at line 134 of file codec_builtin.c.
References ast_frame::datalen.
 {
    return frame->datalen;
 }
opus_samples()
static int opus_samples (struct ast_frame * frame) static
Definition at line 742 of file codec_builtin.c.
References ast_format_get_sample_rate(), ast_frame_subclass::format, and ast_frame::subclass.
 {
    /*
     * XXX This is likely not at all what's intended from this
     * callback.  If you have codec_opus.so loaded then this
     * function is overridden anyway.  However, since opus is
     * variable bit rate and I cannot extract the calculation code
     * from the opus library, I am going to punt and assume 20ms
     * worth of samples.  In testing, this has worked just fine.
     * Pass through support doesn't seem to care about the value
     * returned anyway.
     */
    return ast_format_get_sample_rate(frame->subclass.format) / 50;
 }
silk_samples()
static int silk_samples (struct ast_frame * frame) static
Definition at line 855 of file codec_builtin.c.
References ast_format_get_sample_rate(), ast_frame_subclass::format, and ast_frame::subclass.
 {
    /* XXX This is likely not at all what's intended from this callback. However,
     * since SILK is variable bit rate, I have no idea how to take a frame of data
     * and determine the number of samples present. Instead, we base this on the
     * sample rate of the codec and the expected number of samples to receive in 20ms.
     * In testing, this has worked just fine.
     */
    return ast_format_get_sample_rate(frame->subclass.format) / 50;
 }
siren14_length()
static int siren14_length (unsigned int samples) static
Definition at line 687 of file codec_builtin.c.
 {
    return (int) samples / ((float) 32000 / 6000);;
 }
siren14_samples()
static int siren14_samples (struct ast_frame * frame) static
Definition at line 682 of file codec_builtin.c.
References ast_frame::datalen.
 {
    return (int) frame->datalen * ((float) 32000 / 6000);
 }
siren7_length()
static int siren7_length (unsigned int samples) static
Definition at line 664 of file codec_builtin.c.
 {
    return samples / (16000 / 4000);
 }
siren7_samples()
static int siren7_samples (struct ast_frame * frame) static
Definition at line 659 of file codec_builtin.c.
References ast_frame::datalen.
 {
    return frame->datalen * (16000 / 4000);
 }
slin_length()
static int slin_length (unsigned int samples) static
Definition at line 275 of file codec_builtin.c.
 {
    return samples * 2;
 }
slin_samples()
static int slin_samples (struct ast_frame * frame) static
Definition at line 270 of file codec_builtin.c.
References ast_frame::datalen.
 {
    return frame->datalen / 2;
 }
speex16_samples()
static int speex16_samples (struct ast_frame * frame) static
Definition at line 588 of file codec_builtin.c.
References ast_frame::data, ast_frame::datalen, ast_frame::ptr, and speex_samples().
 {
    return 2 * speex_samples(frame->data.ptr, frame->datalen);
 }
speex32_samples()
static int speex32_samples (struct ast_frame * frame) static
Definition at line 605 of file codec_builtin.c.
References ast_frame::data, ast_frame::datalen, ast_frame::ptr, and speex_samples().
 {
    return 4 * speex_samples(frame->data.ptr, frame->datalen);
 }
speex8_samples()
static int speex8_samples (struct ast_frame * frame) static
Definition at line 571 of file codec_builtin.c.
References ast_frame::data, ast_frame::datalen, ast_frame::ptr, and speex_samples().
 {
    return speex_samples(frame->data.ptr, frame->datalen);
 }
speex_get_wb_sz_at()
static int speex_get_wb_sz_at (unsigned char * data, int len, int bit) static
Definition at line 481 of file codec_builtin.c.
References ast_log, c, get_n_bits_at(), and LOG_WARNING.
Referenced by speex_samples().
 {
    static const int SpeexWBSubModeSz[] = {
       4, 36, 112, 192,
       352, 0, 0, 0 };
    int off = bit;
    unsigned char c;
    /* skip up to two wideband frames */
    if (((len * 8 - off) >= 5) &&
       get_n_bits_at(data, 1, off)) {
       c = get_n_bits_at(data, 3, off + 1);
       off += SpeexWBSubModeSz[c];
       if (((len * 8 - off) >= 5) &&
          get_n_bits_at(data, 1, off)) {
          c = get_n_bits_at(data, 3, off + 1);
          off += SpeexWBSubModeSz[c];
          if (((len * 8 - off) >= 5) &&
             get_n_bits_at(data, 1, off)) {
             ast_log(LOG_WARNING, "Encountered corrupt speex frame; too many wideband frames in a row.\n");
             return -1;
          }
       }
    }
    return off - bit;
 }
speex_samples()
static int speex_samples (unsigned char * data, int len) static
Definition at line 511 of file codec_builtin.c.
References ast_log, c, get_n_bits_at(), LOG_WARNING, and speex_get_wb_sz_at().
Referenced by speex16_samples(), speex32_samples(), and speex8_samples().
 {
    static const int SpeexSubModeSz[] = {
       5, 43, 119, 160,
       220, 300, 364, 492,
       79, 0, 0, 0,
       0, 0, 0, 0 };
    static const int SpeexInBandSz[] = {
       1, 1, 4, 4,
       4, 4, 4, 4,
       8, 8, 16, 16,
       32, 32, 64, 64 };
    int bit = 0;
    int cnt = 0;
    int off;
    unsigned char c;
    while ((len * 8 - bit) >= 5) {
       /* skip wideband frames */
       off = speex_get_wb_sz_at(data, len, bit);
       if (off < 0)  {
          ast_log(LOG_WARNING, "Had error while reading wideband frames for speex samples\n");
          break;
       }
       bit += off;
       if ((len * 8 - bit) < 5)
          break;
       /* get control bits */
       c = get_n_bits_at(data, 5, bit);
       bit += 5;
       if (c == 15) {
          /* terminator */
          break;
       } else if (c == 14) {
          /* in-band signal; next 4 bits contain signal id */
          c = get_n_bits_at(data, 4, bit);
          bit += 4;
          bit += SpeexInBandSz[c];
       } else if (c == 13) {
          /* user in-band; next 4 bits contain msg len */
          c = get_n_bits_at(data, 4, bit);
          bit += 4;
          /* after which it's 5-bit signal id + c bytes of data */
          bit += 5 + c * 8;
       } else if (c > 8) {
          /* unknown */
          ast_log(LOG_WARNING, "Unknown speex control frame %d\n", c);
          break;
       } else {
          /* skip number bits for submode (less the 5 control bits) */
          bit += SpeexSubModeSz[c] - 5;
          cnt += 160; /* new frame */
       }
    }
    return cnt;
 }
ulaw_length()
static int ulaw_length (unsigned int samples) static
Definition at line 161 of file codec_builtin.c.
 {
    return samples;
 }
ulaw_samples()
static int ulaw_samples (struct ast_frame * frame) static
Definition at line 156 of file codec_builtin.c.
References ast_frame::datalen.
 {
    return frame->datalen;
 }
Variable Documentation
adpcm
struct ast_codec adpcm static
Definition at line 256 of file codec_builtin.c.
alaw
struct ast_codec alaw static
Definition at line 180 of file codec_builtin.c.
Referenced by AST_TEST_DEFINE().
codec2
struct ast_codec codec2 static
Definition at line 120 of file codec_builtin.c.
Referenced by ast_format_cap_append_by_type().
g719
struct ast_codec g719 static
Definition at line 729 of file codec_builtin.c.
g722
struct ast_codec g722 static
Definition at line 645 of file codec_builtin.c.
g723
struct ast_codec g723 static
Definition at line 97 of file codec_builtin.c.
g726aal2
struct ast_codec g726aal2 static
Definition at line 242 of file codec_builtin.c.
g726rfc3551
struct ast_codec g726rfc3551 static
Definition at line 228 of file codec_builtin.c.
g729a
struct ast_codec g729a static
Definition at line 448 of file codec_builtin.c.
gsm
struct ast_codec gsm static
Definition at line 204 of file codec_builtin.c.
h261
struct ast_codec h261 static
Definition at line 781 of file codec_builtin.c.
h263
struct ast_codec h263 static
Definition at line 788 of file codec_builtin.c.
Referenced by AST_TEST_DEFINE().
h263p
struct ast_codec h263p static
Definition at line 795 of file codec_builtin.c.
h264
struct ast_codec h264 static
Definition at line 802 of file codec_builtin.c.
h265
struct ast_codec h265 static
Definition at line 809 of file codec_builtin.c.
ilbc
struct ast_codec ilbc static
Definition at line 632 of file codec_builtin.c.
jpeg
struct ast_codec jpeg static
Initial value:
= {
   .name = "jpeg",
   .description = "JPEG image",
   .type = AST_MEDIA_TYPE_IMAGE,
}
Definition at line 769 of file codec_builtin.c.
lpc10
struct ast_codec lpc10 static
Definition at line 425 of file codec_builtin.c.
mpeg4
struct ast_codec mpeg4 static
Definition at line 816 of file codec_builtin.c.
none
struct ast_codec none static
Definition at line 143 of file codec_builtin.c.
opus
struct ast_codec opus static
Definition at line 757 of file codec_builtin.c.
png
struct ast_codec png static
Initial value:
= {
   .name = "png",
   .description = "PNG Image",
   .type = AST_MEDIA_TYPE_IMAGE,
}
Definition at line 775 of file codec_builtin.c.
silk12
struct ast_codec silk12 static
Definition at line 878 of file codec_builtin.c.
silk16
struct ast_codec silk16 static
Definition at line 890 of file codec_builtin.c.
silk24
struct ast_codec silk24 static
Definition at line 902 of file codec_builtin.c.
silk8
struct ast_codec silk8 static
Definition at line 866 of file codec_builtin.c.
siren14
struct ast_codec siren14 static
Definition at line 692 of file codec_builtin.c.
siren7
struct ast_codec siren7 static
Definition at line 669 of file codec_builtin.c.
slin12
struct ast_codec slin12 static
Definition at line 295 of file codec_builtin.c.
slin16
struct ast_codec slin16 static
Definition at line 310 of file codec_builtin.c.
slin192
struct ast_codec slin192 static
Definition at line 400 of file codec_builtin.c.
slin24
struct ast_codec slin24 static
Definition at line 325 of file codec_builtin.c.
slin32
struct ast_codec slin32 static
Definition at line 340 of file codec_builtin.c.
slin44
struct ast_codec slin44 static
Definition at line 355 of file codec_builtin.c.
slin48
struct ast_codec slin48 static
Definition at line 370 of file codec_builtin.c.
slin8
struct ast_codec slin8 static
Definition at line 280 of file codec_builtin.c.
slin96
struct ast_codec slin96 static
Definition at line 385 of file codec_builtin.c.
speex16
struct ast_codec speex16 static
Definition at line 593 of file codec_builtin.c.
speex32
struct ast_codec speex32 static
Definition at line 610 of file codec_builtin.c.
speex8
struct ast_codec speex8 static
Definition at line 576 of file codec_builtin.c.
t140
struct ast_codec t140 static
Initial value:
= {
   .name = "t140",
   .description = "Passthrough T.140 Realtime Text",
   .type = AST_MEDIA_TYPE_TEXT,
}
Definition at line 843 of file codec_builtin.c.
t140red
struct ast_codec t140red static
Initial value:
= {
   .name = "red",
   .description = "T.140 Realtime Text with redundancy",
   .type = AST_MEDIA_TYPE_TEXT,
}
Definition at line 837 of file codec_builtin.c.
t38
struct ast_codec t38 static
Initial value:
= {
   .name = "t38",
   .description = "T.38 UDPTL Fax",
   .type = AST_MEDIA_TYPE_IMAGE,
}
Definition at line 849 of file codec_builtin.c.
testlaw
struct ast_codec testlaw static
Definition at line 705 of file codec_builtin.c.
ulaw
struct ast_codec ulaw static
Definition at line 166 of file codec_builtin.c.
Referenced by AST_TEST_DEFINE().
vp8
struct ast_codec vp8 static
Definition at line 823 of file codec_builtin.c.
vp9
struct ast_codec vp9 static
Definition at line 830 of file codec_builtin.c.