Asterisk - The Open Source Telephony Project: app_cdr.c File Reference
app_cdr.c File Reference
Dial plan applications
Applications connected with CDR engine.
#include "asterisk.h"
#include "asterisk/channel.h"
#include "asterisk/module.h"
#include "asterisk/app.h"
#include "asterisk/stasis.h"
#include "asterisk/stasis_message_router.h"
Data Structures
struct app_cdr_message_payload
Enumerations
enum reset_cdr_options { OPT_DISABLE_DISPATCH = (1 << 0), OPT_KEEP_VARS = (1 << 1), OPT_ENABLE = (1 << 2) }
Functions
static void __reg_module (void)
static void __unreg_module (void)
static void appcdr_callback (void *data, struct stasis_subscription *sub, struct stasis_message *message)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int load_module (void)
static int nocdr_exec (struct ast_channel *chan, const char *data)
static int publish_app_cdr_message (struct ast_channel *chan, struct app_cdr_message_payload *payload)
static int resetcdr_exec (struct ast_channel *chan, const char *data)
STASIS_MESSAGE_TYPE_DEFN_LOCAL (appcdr_message_type)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Tell Asterisk to not maintain a CDR for the current call" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, }
static const struct ast_module_info * ast_module_info = &__mod_info
static const char nocdr_app [] = "NoCDR"
static const char resetcdr_app [] = "ResetCDR"
static const struct ast_app_option resetcdr_opts [128] = { [ 'v' ] = { .flag = AST_CDR_FLAG_KEEP_VARS }, [ 'e' ] = { .flag = AST_CDR_FLAG_DISABLE_ALL }, }
Detailed Description
Applications connected with CDR engine.
Author
Martin Pycko marti.nosp@m.np@d.nosp@m.igium.nosp@m..com
Definition in file app_cdr.c.
Enumeration Type Documentation
reset_cdr_options
enum reset_cdr_options
Enumerator
OPT_DISABLE_DISPATCH
OPT_KEEP_VARS
OPT_ENABLE
Definition at line 104 of file app_cdr.c.
{
    OPT_DISABLE_DISPATCH = (1 << 0),
    OPT_KEEP_VARS = (1 << 1),
    OPT_ENABLE = (1 << 2),
 };
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 268 of file app_cdr.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 268 of file app_cdr.c.
appcdr_callback()
static void appcdr_callback (void * data, struct stasis_subscription * sub, struct stasis_message * message) static
Definition at line 131 of file app_cdr.c.
References ast_cdr_clear_property(), AST_CDR_FLAG_DISABLE_ALL, ast_cdr_reset(), ast_cdr_set_property(), ast_log, AST_LOG_WARNING, app_cdr_message_payload::channel_name, app_cdr_message_payload::disable, app_cdr_message_payload::keep_variables, app_cdr_message_payload::reenable, app_cdr_message_payload::reset, stasis_message_data(), and stasis_message_type().
Referenced by load_module().
 {
    struct app_cdr_message_payload *payload;
    if (stasis_message_type(message) != appcdr_message_type()) {
       return;
    }
    payload = stasis_message_data(message);
    if (!payload) {
       return;
    }
    if (payload->disable) {
       if (ast_cdr_set_property(payload->channel_name, AST_CDR_FLAG_DISABLE_ALL)) {
          ast_log(AST_LOG_WARNING, "Failed to disable CDRs on channel %s\n",
             payload->channel_name);
       }
    }
    if (payload->reenable) {
       if (ast_cdr_clear_property(payload->channel_name, AST_CDR_FLAG_DISABLE_ALL)) {
          ast_log(AST_LOG_WARNING, "Failed to enable CDRs on channel %s\n",
             payload->channel_name);
       }
    }
    if (payload->reset) {
       if (ast_cdr_reset(payload->channel_name, payload->keep_variables)) {
          ast_log(AST_LOG_WARNING, "Failed to reset CDRs on channel %s\n",
             payload->channel_name);
       }
    }
 }
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 268 of file app_cdr.c.
load_module()
static int load_module (void) static
Definition at line 246 of file app_cdr.c.
References ao2_cleanup, appcdr_callback(), ast_cdr_message_router(), AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, ast_register_application_xml, nocdr_app, nocdr_exec(), NULL, RAII_VAR, resetcdr_app, resetcdr_exec(), router, stasis_message_router_add(), STASIS_MESSAGE_TYPE_INIT, and unload_module().
 {
    RAII_VAR(struct stasis_message_router *, router, ast_cdr_message_router(), ao2_cleanup);
    int res = 0;
    if (!router) {
       return AST_MODULE_LOAD_DECLINE;
    }
    res |= STASIS_MESSAGE_TYPE_INIT(appcdr_message_type);
    res |= ast_register_application_xml(nocdr_app, nocdr_exec);
    res |= ast_register_application_xml(resetcdr_app, resetcdr_exec);
    res |= stasis_message_router_add(router, appcdr_message_type(),
                                     appcdr_callback, NULL);
    if (res) {
       unload_module();
       return AST_MODULE_LOAD_DECLINE;
    }
    return AST_MODULE_LOAD_SUCCESS;
 }
nocdr_exec()
static int nocdr_exec (struct ast_channel * chan, const char * data) static
Definition at line 218 of file app_cdr.c.
References ao2_alloc, ao2_cleanup, ast_channel_name(), NULL, publish_app_cdr_message(), and RAII_VAR.
Referenced by load_module().
 {
    RAII_VAR(struct app_cdr_message_payload *, payload,
       ao2_alloc(sizeof(*payload), NULL), ao2_cleanup);
    if (!payload) {
       return -1;
    }
    payload->channel_name = ast_channel_name(chan);
    payload->disable = 1;
    return publish_app_cdr_message(chan, payload);
 }
publish_app_cdr_message()
static int publish_app_cdr_message (struct ast_channel * chan, struct app_cdr_message_payload * payload) static
Definition at line 166 of file app_cdr.c.
References ao2_cleanup, ast_cdr_message_router(), ast_channel_name(), ast_log, AST_LOG_WARNING, app_cdr_message_payload::channel_name, NULL, RAII_VAR, router, stasis_message_create(), and stasis_message_router_publish_sync().
Referenced by nocdr_exec(), and resetcdr_exec().
 {
    RAII_VAR(struct stasis_message *, message, NULL, ao2_cleanup);
    RAII_VAR(struct stasis_message_router *, router, ast_cdr_message_router(), ao2_cleanup);
    if (!router) {
       ast_log(AST_LOG_WARNING, "Failed to manipulate CDR for channel %s: no message router\n",
          ast_channel_name(chan));
       return -1;
    }
    message = stasis_message_create(appcdr_message_type(), payload);
    if (!message) {
       ast_log(AST_LOG_WARNING, "Failed to manipulate CDR for channel %s: unable to create message\n",
          payload->channel_name);
       return -1;
    }
    stasis_message_router_publish_sync(router, message);
    return 0;
 }
resetcdr_exec()
static int resetcdr_exec (struct ast_channel * chan, const char * data) static
Definition at line 188 of file app_cdr.c.
References ao2_alloc, ao2_cleanup, args, ast_app_parse_options(), AST_CDR_FLAG_DISABLE_ALL, AST_CDR_FLAG_KEEP_VARS, ast_channel_name(), ast_strdupa, ast_strlen_zero, ast_test_flag, NULL, publish_app_cdr_message(), RAII_VAR, and resetcdr_opts.
Referenced by load_module().
 {
    RAII_VAR(struct app_cdr_message_payload *, payload,
       ao2_alloc(sizeof(*payload), NULL), ao2_cleanup);
    char *args;
    struct ast_flags flags = { 0 };
    if (!payload) {
       return -1;
    }
    if (!ast_strlen_zero(data)) {
       args = ast_strdupa(data);
       ast_app_parse_options(resetcdr_opts, &flags, NULL, args);
    }
    payload->channel_name = ast_channel_name(chan);
    payload->reset = 1;
    if (ast_test_flag(&flags, AST_CDR_FLAG_DISABLE_ALL)) {
       payload->reenable = 1;
    }
    if (ast_test_flag(&flags, AST_CDR_FLAG_KEEP_VARS)) {
       payload->keep_variables = 1;
    }
    return publish_app_cdr_message(chan, payload);
 }
STASIS_MESSAGE_TYPE_DEFN_LOCAL()
STASIS_MESSAGE_TYPE_DEFN_LOCAL (appcdr_message_type)
unload_module()
static int unload_module (void) static
Definition at line 233 of file app_cdr.c.
References ao2_cleanup, ast_cdr_message_router(), ast_unregister_application(), nocdr_app, RAII_VAR, resetcdr_app, router, stasis_message_router_remove(), and STASIS_MESSAGE_TYPE_CLEANUP.
Referenced by load_module().
 {
    RAII_VAR(struct stasis_message_router *, router, ast_cdr_message_router(), ao2_cleanup);
    if (router) {
       stasis_message_router_remove(router, appcdr_message_type());
    }
    STASIS_MESSAGE_TYPE_CLEANUP(appcdr_message_type);
    ast_unregister_application(nocdr_app);
    ast_unregister_application(resetcdr_app);
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Tell Asterisk to not maintain a CDR for the current call" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, } static
Definition at line 268 of file app_cdr.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 268 of file app_cdr.c.
nocdr_app
const char nocdr_app[] = "NoCDR" static
Definition at line 101 of file app_cdr.c.
Referenced by load_module(), and unload_module().
resetcdr_app
const char resetcdr_app[] = "ResetCDR" static
Definition at line 102 of file app_cdr.c.
Referenced by load_module(), and unload_module().
resetcdr_opts
const struct ast_app_option resetcdr_opts[128] = { [ 'v' ] = { .flag = AST_CDR_FLAG_KEEP_VARS }, [ 'e' ] = { .flag = AST_CDR_FLAG_DISABLE_ALL }, } static
Definition at line 113 of file app_cdr.c.
Referenced by resetcdr_exec().