Asterisk - The Open Source Telephony Project: cdr_sqlite3_custom.c File Reference
cdr_sqlite3_custom.c File Reference
Module: CDR Drivers
Custom SQLite3 CDR records.
#include "asterisk.h"
#include <sqlite3.h>
#include "asterisk/paths.h"
#include "asterisk/channel.h"
#include "asterisk/cdr.h"
#include "asterisk/module.h"
#include "asterisk/config.h"
#include "asterisk/pbx.h"
#include "asterisk/utils.h"
#include "asterisk/cli.h"
#include "asterisk/app.h"
Data Structures
struct sql_values
struct values
Functions
static void free_config (int reload)
static int load_column_config (const char *tmp)
static int load_values_config (const char *tmp)
Variables
static int busy_timeout
static char * columns
static const char config_file [] = "cdr_sqlite3_custom.conf"
static sqlite3 * db = NULL
static const char desc [] = "Customizable SQLite3 CDR Backend"
static ast_mutex_t lock = { PTHREAD_RECURSIVE_MUTEX_INITIALIZER_NP , NULL, {1, 0} }
static const char name [] = "cdr_sqlite3_custom"
static struct sql_values sql_values = { .first = NULL, .last = NULL, .lock = { PTHREAD_RECURSIVE_MUTEX_INITIALIZER_NP , NULL, {1, 0} } , }
static char table [80]
Detailed Description
Custom SQLite3 CDR records.
Author
Adapted by Alejandro Rios aleja.nosp@m.ndro.nosp@m..rios.nosp@m.@ava.nosp@m.tar.c.nosp@m.om.c.nosp@m.o and Russell Bryant russe.nosp@m.ll@d.nosp@m.igium.nosp@m..com from cdr_mysql_custom by Edward Eastman ed@dm.nosp@m.3.co.nosp@m..uk, and cdr_sqlite by Holger Schurig hs423.nosp@m.3@ma.nosp@m.il.mn.nosp@m.-sol.nosp@m.ution.nosp@m.s.de
See also CDR - Call Data Records and billing
Definition in file cdr_sqlite3_custom.c.
Function Documentation
free_config()
static void free_config (int reload) static
Referenced by load_values_config().
load_column_config()
static int load_column_config (const char * tmp) static
Definition at line 75 of file cdr_sqlite3_custom.c.
References ast_free, ast_log, ast_str_append(), ast_str_buffer(), ast_str_create, ast_str_strlen(), ast_strdup, ast_strip(), ast_strlen_zero, LOG_ERROR, LOG_WARNING, NULL, strsep(), and table.
Referenced by load_values_config().
 {
    char *col = NULL;
    char *cols = NULL, *save = NULL;
    char *escaped = NULL;
    struct ast_str *column_string = NULL;
    if (ast_strlen_zero(tmp)) {
       ast_log(LOG_WARNING, "Column names not specified. Module not loaded.\n");
       return -1;
    }
    if (!(column_string = ast_str_create(1024))) {
       ast_log(LOG_ERROR, "Out of memory creating temporary buffer for column list for table '%s.'\n", table);
       return -1;
    }
    if (!(save = cols = ast_strdup(tmp))) {
       ast_log(LOG_ERROR, "Out of memory creating temporary buffer for column list for table '%s.'\n", table);
       ast_free(column_string);
       return -1;
    }
    while ((col = strsep(&cols, ","))) {
       col = ast_strip(col);
       escaped = sqlite3_mprintf("%q", col);
       if (!escaped) {
          ast_log(LOG_ERROR, "Out of memory creating entry for column '%s' in table '%s.'\n", col, table);
          ast_free(column_string);
          ast_free(save);
          return -1;
       }
       ast_str_append(&column_string, 0, "%s%s", ast_str_strlen(column_string) ? "," : "", escaped);
       sqlite3_free(escaped);
    }
    if (!(columns = ast_strdup(ast_str_buffer(column_string)))) {
       ast_log(LOG_ERROR, "Out of memory copying columns string for table '%s.'\n", table);
       ast_free(column_string);
       ast_free(save);
       return -1;
    }
    ast_free(column_string);
    ast_free(save);
    return 0;
 }
load_values_config()
static int load_values_config (const char * tmp) static
Definition at line 119 of file cdr_sqlite3_custom.c.
References AST_APP_ARG, ast_calloc, ast_cdr_dup(), ast_cdr_register(), ast_cdr_unregister(), ast_channel_cdr_set(), ast_channel_unref, ast_config_AST_LOG_DIR, ast_config_destroy(), ast_config_load, ast_copy_string(), ast_debug, AST_DECLARE_APP_ARGS, ast_dummy_channel_alloc, ast_free, AST_LIST_INSERT_TAIL, AST_LIST_REMOVE_HEAD, AST_LIST_TRAVERSE, ast_log, AST_MODFLAG_LOAD_ORDER, AST_MODPRI_CDR_DRIVER, AST_MODULE_INFO(), AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, AST_MODULE_SUPPORT_EXTENDED, ast_mutex_lock, ast_mutex_unlock, ast_parse_arg(), AST_STANDARD_RAW_ARGS, ast_str_append(), ast_str_buffer(), ast_str_create, ast_str_strlen(), ast_strdup, ast_strip_quoted(), ast_strlen_zero, ast_variable_browse(), ast_variable_retrieve(), ast_verb, ASTERISK_GPL_KEY, busy_timeout, config_file, CONFIG_FLAG_FILEUNCHANGED, CONFIG_STATUS_FILEINVALID, CONFIG_STATUS_FILEMISSING, CONFIG_STATUS_FILEUNCHANGED, db, desc, dummy(), error(), values::expression, free_config(), values::list, load_column_config(), load_config(), load_module(), lock, LOG_ERROR, LOG_WARNING, name, NULL, PARSE_DEFAULT, PARSE_INT32, PATH_MAX, pbx_substitute_variables_helper(), reload(), table, tmp(), unload_module, and value.
Variable Documentation
busy_timeout
int busy_timeout static
Definition at line 64 of file cdr_sqlite3_custom.c.
Referenced by load_values_config().
columns
char* columns static
Definition at line 63 of file cdr_sqlite3_custom.c.
config_file
const char config_file[] = "cdr_sqlite3_custom.conf" static
Definition at line 56 of file cdr_sqlite3_custom.c.
Referenced by load_values_config().
db
sqlite3* db = NULL static
Definition at line 60 of file cdr_sqlite3_custom.c.
Referenced by __bt_put(), __rec_iput(), ast_config_internal_load(), ast_destroy_realtime_fields(), ast_load_realtime_all_fields(), ast_load_realtime_multientry_fields(), ast_realtime_require_field(), ast_store_realtime_fields(), ast_unload_realtime(), ast_update2_realtime_fields(), ast_update_realtime_fields(), db_cmp_fn(), db_destructor(), db_hash_fn(), db_sync_thread(), dbm_close(), dbm_open(), is_dirty_cb(), load_values_config(), mark_dirty_cb(), my_swap_subchannels(), new_realtime_sqlite3_db(), parse_config(), realtime_sqlite3_exec_query(), realtime_sqlite3_exec_update(), realtime_sqlite3_require(), stop_batch_cb(), and trace_cb().
desc
const char desc[] = "Customizable SQLite3 CDR Backend" static
Definition at line 58 of file cdr_sqlite3_custom.c.
Referenced by load_values_config().
lock
ast_mutex_t lock = { PTHREAD_RECURSIVE_MUTEX_INITIALIZER_NP , NULL, {1, 0} } static
Definition at line 54 of file cdr_sqlite3_custom.c.
Referenced by load_values_config().
name
const char name[] = "cdr_sqlite3_custom" static
Definition at line 59 of file cdr_sqlite3_custom.c.
Referenced by load_values_config().
sql_values
struct sql_values sql_values = { .first = NULL, .last = NULL, .lock = { PTHREAD_RECURSIVE_MUTEX_INITIALIZER_NP , NULL, {1, 0} } , } static
table
char table[80] static
Definition at line 62 of file cdr_sqlite3_custom.c.
Referenced by load_column_config(), and load_values_config().