Asterisk - The Open Source Telephony Project: bt_open.c File Reference
bt_open.c File Reference
#include <sys/param.h>
#include <sys/stat.h>
#include <errno.h>
#include <fcntl.h>
#include <limits.h>
#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include "../include/db.h"
#include "btree.h"
Functions
int __bt_fd (DB *dbp) const
DB * __bt_open (char *fname, int flags, int mode, const BTREEINFO *openinfo, int dflags) const
static int byteorder __P ((void))
static int nroot __P ((BTREE *))
static int byteorder ()
static int nroot (BTREE *t)
static int tmp ()
Function Documentation
__bt_fd()
int __bt_fd (DB * dbp) const
Definition at line 439 of file bt_open.c.
References B_INMEM, _btree::bt_fd, _btree::bt_mp, _btree::bt_pinned, errno, F_ISSET, __db::internal, mpool_put(), and NULL.
Referenced by __bt_open().
 {
    BTREE *t;
    t = dbp->internal;
    /* Toss any page pinned across calls. */
    if (t->bt_pinned != NULL) {
       mpool_put(t->bt_mp, t->bt_pinned, 0);
       t->bt_pinned = NULL;
    }
    /* In-memory database can't have a file descriptor. */
    if (F_ISSET(t, B_INMEM)) {
       errno = ENOENT;
       return (-1);
    }
    return (t->bt_fd);
 }
__bt_open()
DB* __bt_open (char * fname, int flags, int mode, const BTREEINFO * openinfo, int dflags) const
Definition at line 90 of file bt_open.c.
References __bt_close(), __bt_defcmp(), __bt_defpfx(), __bt_delete(), __bt_fd(), __bt_get(), __bt_pgin(), __bt_pgout(), __bt_put(), __bt_seq(), __bt_sync(), b, B_DB_LOCK, B_DB_SHMEM, B_DB_TXN, B_INMEM, B_METADIRTY, B_NEEDSWAP, B_NODUPS, B_RDONLY, BIG_ENDIAN, _btree::bt_dbp, _btree::bt_fd, _btree::bt_free, _btree::bt_lorder, _btree::bt_mp, _btree::bt_nrecs, _btree::bt_order, _btree::bt_ovflsize, _btree::bt_psize, _btree::bt_rfd, BTDATAOFF, BTREEMAGIC, BTREEVERSION, byteorder(), BTREEINFO::cachesize, DB_BTREE, DB_LOCK, DB_SHMEM, DB_TXN, dbp, DEFMINKEYPAGE, EFTYPE, errno, F_CLR, F_ISSET, F_SET, BTREEINFO::flags, _btree::flags, free(), __db::internal, LITTLE_ENDIAN, BTREEINFO::lorder, malloc(), MAX_PAGE_OFFSET, MINCACHE, BTREEINFO::minkeypage, MINPSIZE, mpool_filter(), mpool_open(), NBLEAFDBT, NOVFLSIZE, nroot(), NULL, P_INVALID, BTREEINFO::psize, R_DUP, RET_ERROR, SAVEMETA, tmp(), and __db::type.
Referenced by __rec_open(), and dbopen().
 {
    struct stat sb;
    BTMETA m;
    BTREE *t;
    BTREEINFO b;
    DB *dbp;
    pgno_t ncache;
    ssize_t nr;
    int machine_lorder;
    t = NULL;
    /*
     * Intention is to make sure all of the user's selections are okay
     * here and then use them without checking.  Can't be complete, since
     * we don't know the right page size, lorder or flags until the backing
     * file is opened.  Also, the file's page size can cause the cachesize
     * to change.
     */
    machine_lorder = byteorder();
    if (openinfo) {
       b = *openinfo;
       /* Flags: R_DUP. */
       if (b.flags & ~(R_DUP))
          goto einval;
       /*
        * Page size must be indx_t aligned and >= MINPSIZE.  Default
        * page size is set farther on, based on the underlying file
        * transfer size.
        */
       if (b.psize &&
           (b.psize < MINPSIZE || b.psize > MAX_PAGE_OFFSET + 1 ||
           b.psize & (sizeof(indx_t) - 1)))
          goto einval;
       /* Minimum number of keys per page; absolute minimum is 2. */
       if (b.minkeypage) {
          if (b.minkeypage < 2)
             goto einval;
       } else
          b.minkeypage = DEFMINKEYPAGE;
       /* If no comparison, use default comparison and prefix. */
       if (b.compare == NULL) {
          b.compare = __bt_defcmp;
          if (b.prefix == NULL)
             b.prefix = __bt_defpfx;
       }
       if (b.lorder == 0)
          b.lorder = machine_lorder;
    } else {
       b.compare = __bt_defcmp;
       b.cachesize = 0;
       b.flags = 0;
       b.lorder = machine_lorder;
       b.minkeypage = DEFMINKEYPAGE;
       b.prefix = __bt_defpfx;
       b.psize = 0;
    }
    /* Check for the ubiquitous PDP-11. */
    if (b.lorder != BIG_ENDIAN && b.lorder != LITTLE_ENDIAN)
       goto einval;
    /* Allocate and initialize DB and BTREE structures. */
    if ((t = (BTREE *)malloc(sizeof(BTREE))) == NULL)
       goto err;
    memset(t, 0, sizeof(BTREE));
    t->bt_fd = -1;       /* Don't close unopened fd on error. */
    t->bt_lorder = b.lorder;
    t->bt_order = NOT;
    t->bt_cmp = b.compare;
    t->bt_pfx = b.prefix;
    t->bt_rfd = -1;
    if ((t->bt_dbp = dbp = (DB *)malloc(sizeof(DB))) == NULL)
       goto err;
    memset(t->bt_dbp, 0, sizeof(DB));
    if (t->bt_lorder != machine_lorder)
       F_SET(t, B_NEEDSWAP);
    dbp->type = DB_BTREE;
    dbp->internal = t;
    dbp->close = __bt_close;
    dbp->del = __bt_delete;
    dbp->fd = __bt_fd;
    dbp->get = __bt_get;
    dbp->put = __bt_put;
    dbp->seq = __bt_seq;
    dbp->sync = __bt_sync;
    /*
     * If no file name was supplied, this is an in-memory btree and we
     * open a backing temporary file.  Otherwise, it's a disk-based tree.
     */
    if (fname) {
       switch (flags & O_ACCMODE) {
       case O_RDONLY:
          F_SET(t, B_RDONLY);
          break;
       case O_RDWR:
          break;
       case O_WRONLY:
       default:
          goto einval;
       }
       if ((t->bt_fd = open(fname, flags, mode)) < 0)
          goto err;
    } else {
       if ((flags & O_ACCMODE) != O_RDWR)
          goto einval;
       if ((t->bt_fd = tmp()) == -1)
          goto err;
       F_SET(t, B_INMEM);
    }
    if (fcntl(t->bt_fd, F_SETFD, 1) == -1)
       goto err;
    if (fstat(t->bt_fd, &sb))
       goto err;
    if (sb.st_size) {
       if ((nr = read(t->bt_fd, &m, sizeof(BTMETA))) < 0)
          goto err;
       if (nr != sizeof(BTMETA))
          goto eftype;
       /*
        * Read in the meta-data.  This can change the notion of what
        * the lorder, page size and flags are, and, when the page size
        * changes, the cachesize value can change too.  If the user
        * specified the wrong byte order for an existing database, we
        * don't bother to return an error, we just clear the NEEDSWAP
        * bit.
        */
       if (m.magic == BTREEMAGIC)
          F_CLR(t, B_NEEDSWAP);
       else {
          F_SET(t, B_NEEDSWAP);
          M_32_SWAP(m.magic);
          M_32_SWAP(m.version);
          M_32_SWAP(m.psize);
          M_32_SWAP(m.free);
          M_32_SWAP(m.nrecs);
          M_32_SWAP(m.flags);
       }
       if (m.magic != BTREEMAGIC || m.version != BTREEVERSION)
          goto eftype;
       if (m.psize < MINPSIZE || m.psize > MAX_PAGE_OFFSET + 1 ||
           m.psize & (sizeof(indx_t) - 1))
          goto eftype;
       if (m.flags & ~SAVEMETA)
          goto eftype;
       b.psize = m.psize;
       F_SET(t, m.flags);
       t->bt_free = m.free;
       t->bt_nrecs = m.nrecs;
    } else {
       /*
        * Set the page size to the best value for I/O to this file.
        * Don't overflow the page offset type.
        */
       if (b.psize == 0) {
 #ifdef _STATBUF_ST_BLKSIZE
          b.psize = sb.st_blksize;
 #endif
          if (b.psize < MINPSIZE)
             b.psize = MINPSIZE;
          if (b.psize > MAX_PAGE_OFFSET + 1)
             b.psize = MAX_PAGE_OFFSET + 1;
       }
       /* Set flag if duplicates permitted. */
       if (!(b.flags & R_DUP))
          F_SET(t, B_NODUPS);
       t->bt_free = P_INVALID;
       t->bt_nrecs = 0;
       F_SET(t, B_METADIRTY);
    }
    t->bt_psize = b.psize;
    /* Set the cache size; must be a multiple of the page size. */
    if (b.cachesize && b.cachesize & (b.psize - 1))
       b.cachesize += (~b.cachesize & (b.psize - 1)) + 1;
    if (b.cachesize < b.psize * MINCACHE)
       b.cachesize = b.psize * MINCACHE;
    /* Calculate number of pages to cache. */
    ncache = (b.cachesize + t->bt_psize - 1) / t->bt_psize;
    /*
     * The btree data structure requires that at least two keys can fit on
     * a page, but other than that there's no fixed requirement.  The user
     * specified a minimum number per page, and we translated that into the
     * number of bytes a key/data pair can use before being placed on an
     * overflow page.  This calculation includes the page header, the size
     * of the index referencing the leaf item and the size of the leaf item
     * structure.  Also, don't let the user specify a minkeypage such that
     * a key/data pair won't fit even if both key and data are on overflow
     * pages.
     */
    t->bt_ovflsize = (t->bt_psize - BTDATAOFF) / b.minkeypage -
        (sizeof(indx_t) + NBLEAFDBT(0, 0));
    if (t->bt_ovflsize < NBLEAFDBT(NOVFLSIZE, NOVFLSIZE) + sizeof(indx_t))
       t->bt_ovflsize =
           NBLEAFDBT(NOVFLSIZE, NOVFLSIZE) + sizeof(indx_t);
    /* Initialize the buffer pool. */
    if ((t->bt_mp =
        mpool_open(NULL, t->bt_fd, t->bt_psize, ncache)) == NULL)
       goto err;
    if (!F_ISSET(t, B_INMEM))
       mpool_filter(t->bt_mp, __bt_pgin, __bt_pgout, t);
    /* Create a root page if new tree. */
    if (nroot(t) == RET_ERROR)
       goto err;
    /* Global flags. */
    if (dflags & DB_LOCK)
       F_SET(t, B_DB_LOCK);
    if (dflags & DB_SHMEM)
       F_SET(t, B_DB_SHMEM);
    if (dflags & DB_TXN)
       F_SET(t, B_DB_TXN);
    return (dbp);
 einval:  errno = EINVAL;
    goto err;
 eftype:  errno = EFTYPE;
    goto err;
 err:  if (t) {
       if (t->bt_dbp)
          free(t->bt_dbp);
       if (t->bt_fd != -1)
          (void)close(t->bt_fd);
       free(t);
    }
    return (NULL);
 }
__P() [1/2]
static int tmp __P ((void)) static
__P() [2/2]
static int nroot __P ((BTREE *)) static
byteorder()
static int byteorder () static
Definition at line 421 of file bt_open.c.
References BIG_ENDIAN, and LITTLE_ENDIAN.
Referenced by __bt_open().
 {
    u_int32_t x;
    u_char *p;
    x = 0x01020304;
    p = (u_char *)&x;
    switch (*p) {
    case 1:
       return (BIG_ENDIAN);
    case 4:
       return (LITTLE_ENDIAN);
    default:
       return (0);
    }
 }
nroot()
static int nroot (BTREE * t) static
Definition at line 355 of file bt_open.c.
References _btree::bt_mp, _btree::bt_psize, BTDATAOFF, errno, _page::flags, _page::lower, env::meta, MPOOL_DIRTY, mpool_get(), mpool_new(), mpool_put(), _page::nextpg, NULL, P_BLEAF, P_INVALID, P_ROOT, _page::pgno, _page::prevpg, RET_ERROR, RET_SUCCESS, and _page::upper.
Referenced by __bt_open().
 {
    PAGE *meta, *root;
    pgno_t npg;
    if ((meta = mpool_get(t->bt_mp, 0, 0)) != NULL) {
       mpool_put(t->bt_mp, meta, 0);
       return (RET_SUCCESS);
    }
    if (errno != EINVAL)    /* It's OK to not exist. */
       return (RET_ERROR);
    errno = 0;
    if ((meta = mpool_new(t->bt_mp, &npg)) == NULL)
       return (RET_ERROR);
    if ((root = mpool_new(t->bt_mp, &npg)) == NULL)
       return (RET_ERROR);
    if (npg != P_ROOT)
       return (RET_ERROR);
    root->pgno = npg;
    root->prevpg = root->nextpg = P_INVALID;
    root->lower = BTDATAOFF;
    root->upper = t->bt_psize;
    root->flags = P_BLEAF;
    memset(meta, 0, t->bt_psize);
    mpool_put(t->bt_mp, meta, MPOOL_DIRTY);
    mpool_put(t->bt_mp, root, MPOOL_DIRTY);
    return (RET_SUCCESS);
 }
tmp()
static int tmp () static
Examples:
/usr/src/asterisk-18.5.0/main/app.c.
Definition at line 389 of file bt_open.c.
References free(), malloc(), and NULL.
Referenced by __aco_option_register(), __ast_channel_alloc_ap(), __ast_channel_internal_alloc(), __ast_context_create(), __ast_context_destroy(), __ast_dummy_channel_alloc(), __ast_format_def_register(), __ast_internal_context_destroy(), __ast_pthread_mutex_lock(), __ast_pthread_mutex_trylock(), __ast_register_translator(), __ast_rwlock_rdlock(), __ast_rwlock_timedrdlock(), __ast_rwlock_timedwrlock(), __ast_rwlock_tryrdlock(), __ast_rwlock_trywrlock(), __ast_rwlock_wrlock(), __bt_open(), _build_port_config(), _macro_exec(), _parse(), _sip_tcp_helper_thread(), acf_curlopt_write(), acf_odbc_read(), acf_rand_exec(), action_dahdishowchannels(), action_login(), action_originate(), actual_load_config(), add_crypto_to_stream(), add_date(), add_digit(), add_expires(), add_menu_entry(), add_pri(), add_priority(), add_rpid(), add_ssrc_to_stream(), adpcmtolin_framein(), adsi_process(), aes_helper(), alsa_new(), alsa_request(), aMYSQL_set(), append_date(), append_event(), append_ha_core(), append_int(), append_mailbox(), aqm_exec(), ast_add_extension2(), ast_add_extension2_lockopt(), ast_alertpipe_flush(), ast_alertpipe_read(), ast_alertpipe_write(), ast_app_group_split_group(), ast_append_acl(), ast_ari_asterisk_get_global_var(), ast_bucket_alloc(), ast_bucket_file_alloc(), ast_callerid_parse(), ast_callerid_split(), ast_callid_threadstorage_auto(), ast_cli_command_full(), ast_config_hook_unregister(), ast_config_option(), ast_context_find(), ast_context_find_or_create(), ast_format_def_unregister(), ast_get_enum(), ast_get_hint(), ast_hashtab_hash_string(), ast_hashtab_hash_string_nocase(), ast_iax2_new(), ast_jb_read_conf(), ast_loader_register(), ast_media_cache_create_or_update(), ast_merge_contexts_and_delete(), ast_mkdir(), ast_monitor_stop(), ast_privacy_check(), ast_privacy_set(), ast_read_image(), ast_register_application2(), ast_register_switch(), ast_remotecontrol(), ast_sched_add_variable(), ast_sched_context_create(), ast_sip_create_dialog_uac(), ast_sip_create_rdata_with_contact(), ast_sip_set_outbound_proxy(), ast_sorcery_changeset_create(), ast_sorcery_objectset_create2(), ast_sorcery_objectset_json_create(), ast_srtp_policy_alloc(), ast_str_encode_mime(), ast_str_get_hint(), ast_strftime_locale(), AST_TEST_DEFINE(), ast_unregister_translator(), ast_uri_decode(), ast_utf8_validator_new(), ast_variables_dup(), ast_xmldoc_printable(), auth_exec(), background_detect_exec(), bucket_file_wizard_retrieve(), bucket_wizard_retrieve(), build_channels(), build_contact(), build_peer(), build_radius_record(), build_rand_pad(), build_secret(), cache_lookup(), caldav_add_event(), calendar_join_attendees(), callstate2str(), cb_events(), cdr_handler(), chan_misdn_log(), channel_spy(), chanspy_exec(), check_peer_ok(), check_user_full(), check_via(), cli_fax_show_session(), cli_prompt(), cli_show_module_options(), cli_show_module_type(), cli_show_module_types(), codec2_destroy_stuff(), codec2_new(), codec2tolin_framein(), common_exec(), complete_queue_remove_member(), conf_get_pin(), config_module(), console_dial(), console_transfer(), control2str(), controlplayback_exec(), copy_all_header(), copy_header(), copy_plain_file(), copy_rules(), copy_vars(), cpeid_setstatus(), create_client(), create_followme_number(), create_jb(), create_outgoing_sdp_stream(), create_queue_member(), crypto_get_attrib(), custom_presence_callback(), dahdi_cc_callback(), dahdi_new(), dahdi_request(), dahdi_set_hwgain(), dahdi_set_swgain(), dahdi_show_channel(), dahdi_show_channels(), device2str(), dial_exec_full(), dialgroup_read(), disa_exec(), do_monitor(), do_pktccops(), dump_answer(), dump_ies(), dump_prov_ies(), dump_samprate(), dundi_do_lookup(), dundi_do_precache(), dundi_do_query(), dundi_ie_append_answer(), dundi_ie_append_cause(), dundi_ie_append_encdata(), dundi_ie_append_hint(), dundi_ie_append_raw(), dundi_lookup_local(), dundi_parse_ies(), dundi_reject(), dundi_showframe(), eivr_comm(), epoch_to_exchange_time(), export_ch(), extenspy_exec(), fetch_response_reader(), find_by_mark(), find_channel(), find_queue_by_name_rt(), find_result(), find_subchannel_and_lock(), free_zone(), function_enum(), g722tolin16_new(), g722tolin_framein(), g722tolin_new(), g726aal2tolin_framein(), g726tolin_framein(), generate_fmtp_attr(), generate_rtpmap_attr(), generator_force(), get_also_info(), get_chan_by_ast_name(), get_destination(), get_extension_data(), get_in_brackets(), get_in_brackets_full(), get_multiple_fields_as_var_list(), get_name_from_variable(), get_rdnis(), get_rpid(), get_single_field_as_var_list(), get_token(), gr_say_number_female(), gsm_destroy_stuff(), gsm_new(), gsmtolin_framein(), handle_call_forward(), handle_characters(), handle_cli_check_permissions(), handle_cli_confbridge_show_bridge_profile(), handle_cli_database_get(), handle_cli_iax2_show_cache(), handle_cli_keys_init(), handle_cli_misdn_send_digit(), handle_cli_misdn_send_display(), handle_cli_misdn_send_facility(), handle_cli_misdn_toggle_echocancel(), handle_dahdi_show_cadences(), handle_minivm_show_users(), handle_request_info(), handle_select_option(), handle_setcallerid(), handle_speechrecognize(), has_voicemail(), hash_string(), hashkeys_read2(), heap_swap(), iax2_call(), iax2_datetime(), iax2_devicestate(), iax2_transfer(), iax2_trunk_queue(), iax_ie_append_raw(), iax_parse_ies(), iax_provision_build(), iax_provision_version(), iax_showframe(), iax_template_parse(), icalendar_add_event(), ilbctolin_framein(), ilbctolin_new(), import_ch(), inboxcount2(), init_acf_query(), init_phone_step2(), internal_format_cap_identical(), io_context_create(), io_grow(), jingle_add_ice_udp_candidates_to_transport(), jingle_add_payloads_to_description(), launch_script(), leave_voicemail(), lin16tog722_new(), lintoadpcm_framein(), lintoadpcm_frameout(), lintocodec2_framein(), lintocodec2_frameout(), lintog722_framein(), lintog722_new(), lintog726_framein(), lintog726_new(), lintog726aal2_framein(), lintogsm_framein(), lintogsm_frameout(), lintoilbc_framein(), lintoilbc_frameout(), lintoilbc_new(), lintolpc10_framein(), lintolpc10_frameout(), lintospeex_feedback(), lintospeex_framein(), lintospeex_frameout(), load_config(), load_module(), load_password(), load_values_config(), local_read(), loopback_subst(), lpc10_dec_new(), lpc10_enc_new(), lpc10tolin_framein(), lua_pbx_exec(), main(), manage_calls(), manager_action(), manager_dbget(), manager_login(), mgcp_devicestate(), mgcp_new(), mgcp_request(), mgcp_senddigit_end(), minivm_accmess_exec(), minivm_greet_exec(), minivm_mwi_exec(), minivm_notify_exec(), minivm_record_exec(), misdn_answer(), misdn_call(), misdn_cfg_get_ports_string(), misdn_chan_is_valid(), misdn_new(), misdn_read(), misdn_send_text(), misdn_set_opt_exec(), mixmonitor_save_prep(), mkif(), mkintf(), moh_files_write_format_change(), my_load_config_number(), my_load_config_string(), nbs_new(), nbs_request(), new_iax(), normalise_history(), odbc_load_module(), odbc_log(), ogg_vorbis_rewrite(), ooh323_request(), open_history(), optimize_transactions(), osp_create_uuid(), osp_get_varfloat(), osp_get_varint(), osp_lookup(), osp_report_qos(), ospauth_exec(), ospfinished_exec(), osplookup_exec(), ospnext_exec(), P2(), page_exec(), parse_hint_device(), parse_hint_presence(), parse_tag(), parse_uri_cb(), pbx_builtin_importvar(), pbx_builtin_saynumber(), pbx_extension_helper(), pbx_find_extension(), pbx_load_users(), pbx_outgoing_attempt(), pbx_substitute_variables_helper_full(), peer_set_srcaddr(), phone_new(), phone_request(), playback_exec(), presence_write(), process_dahdi(), process_my_load_module(), process_sdp_a_audio(), prov_ver_calc(), pw_cb(), random_binaural_pos_change(), rcv_mac_addr(), read_exec(), read_mf_exec(), read_sf_exec(), realtime_directory(), realtime_ldap_base_ap(), realtime_ldap_result_to_vars(), realtime_peer(), realtime_peer_by_name(), realtime_user(), rebuild_channels(), record_exec(), register_verify(), reload_config(), reload_followme(), reload_module(), reload_single_member(), reply_digest(), reqprep(), request(), res_sdp_crypto_parse_offer(), res_sdp_srtp_get_attr(), restart_monitor(), rxqcheck(), save_secret(), sched_alloc(), send_eivr_event(), send_raw_client(), send_request(), send_response(), sendmail(), sendurl_exec(), set_config(), set_remote_mslabel_and_stream_group(), show_config_description(), show_phone_number(), sip_devicestate(), sip_dialog_create_contact(), sip_dialog_create_from(), sip_new(), sip_outbound_publisher_set_uri(), sip_outbound_registration_regc_alloc(), sip_prune_realtime(), sip_request_call(), sip_tcptls_write(), skel_exec(), skinny_devicestate(), skinny_new(), skinny_request(), skinny_senddigit_end(), smb_pitch_shift(), socket_receive_file_to_buff(), softmix_mixing_array_grow(), sorcery_config_open(), sorcery_realtime_open(), sort_items(), speech_background(), speech_read(), speech_score(), speex_decoder_construct(), speex_encoder_construct(), speextolin_framein(), sqlite3_escape_column_op(), sqlite3_escape_string_helper(), start_monitor_exec(), start_resource(), StateConstructW(), StateSearchW(), store_tone_zone_ring_cadence(), substate2str(), time2sub(), timesub(), to_string(), transfer_redirect(), transfer_refer(), transmit_connect(), transmit_connect_with_sdp(), transmit_modify_request(), transmit_modify_with_sdp(), transmit_notify_with_sipfrag(), transmit_register(), transmit_response_with_auth(), transmit_response_with_minexpires(), transmit_state_notify(), try_calling(), try_redirect(), unistim_line_copy(), unistim_new(), unistim_request(), unistim_sendtext(), unistim_sp(), unistimsock_read(), uri_parse_and_default(), ustmtext(), vm_allocate_dh(), vm_change_password(), vm_exec(), vq(), wav_open(), wav_read(), wav_rewrite(), wav_write(), while_continue_exec(), write_history(), xml_encode_str(), xmldoc_get_formatted(), xmldoc_get_syntax_config_object(), xmldoc_parse_para(), xmldoc_parse_variable(), xmldoc_parse_variablelist(), xmldoc_reverse_helper(), xmldoc_string_wrap(), and xmldoc_update_config_type().
 {
    sigset_t set, oset;
    int fd;
    const char *envtmp;
    char *path;
    static const char fmt[] = "%s/bt.XXXXXX";
    size_t n;
    envtmp = getenv("TMPDIR");
    if (!envtmp)
      envtmp = "/tmp";
    n = strlen (envtmp) + sizeof fmt;
 #ifdef   __GNUC__
    path = __builtin_alloca(n);
 #else
    path = malloc(n);
 #endif
    (void)snprintf(path, n, fmt, envtmp ? envtmp : "/tmp");
    (void)sigfillset(&set);
    (void)sigprocmask(SIG_BLOCK, &set, &oset);
    if ((fd = mkstemp(path)) != -1)
       (void)unlink(path);
    (void)sigprocmask(SIG_SETMASK, &oset, NULL);
 #ifndef  __GNUC__
    free(path);
 #endif
    return(fd);
 }