Asterisk - The Open Source Telephony Project: res_pjsip_xpidf_body_generator.c File Reference
res_pjsip_xpidf_body_generator.c File Reference
#include "asterisk.h"
#include <pjsip.h>
#include <pjsip_simple.h>
#include <pjlib.h>
#include "asterisk/module.h"
#include "asterisk/res_pjsip.h"
#include "asterisk/res_pjsip_pubsub.h"
#include "asterisk/res_pjsip_presence_xml.h"
#include "asterisk/res_pjsip_body_generator_types.h"
Macros
#define MAX_STRING_GROWTHS 5
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int load_module (void)
static int unload_module (void)
static void unregister_all (void)
static void * xpidf_allocate_body (void *data)
static int xpidf_generate_body_content (void *body, void *data)
static void xpidf_to_string (void *body, struct ast_str **str)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "PJSIP Extension State PIDF Provider" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_CHANNEL_DEPEND, .requires = "res_pjsip,res_pjsip_pubsub", }
static const struct ast_module_info * ast_module_info = &__mod_info
static struct ast_sip_pubsub_body_generator cpim_pidf_body_generator
static struct ast_sip_pubsub_body_generator xpidf_body_generator
Macro Definition Documentation
MAX_STRING_GROWTHS
#define MAX_STRING_GROWTHS 5
Definition at line 99 of file res_pjsip_xpidf_body_generator.c.
Referenced by xpidf_to_string().
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 178 of file res_pjsip_xpidf_body_generator.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 178 of file res_pjsip_xpidf_body_generator.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 178 of file res_pjsip_xpidf_body_generator.c.
load_module()
static int load_module (void) static
Definition at line 149 of file res_pjsip_xpidf_body_generator.c.
References AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, ast_sip_pubsub_register_body_generator(), and unregister_all().
Referenced by unload_module().
 {
    if (ast_sip_pubsub_register_body_generator(&xpidf_body_generator)) {
       goto fail;
    }
    if (ast_sip_pubsub_register_body_generator(&cpim_pidf_body_generator)) {
       goto fail;
    }
    return AST_MODULE_LOAD_SUCCESS;
 fail:
    unregister_all();
    return AST_MODULE_LOAD_DECLINE;
 }
unload_module()
static int unload_module (void) static
Definition at line 166 of file res_pjsip_xpidf_body_generator.c.
References AST_MODFLAG_LOAD_ORDER, AST_MODPRI_CHANNEL_DEPEND, AST_MODULE_INFO(), AST_MODULE_SUPPORT_CORE, ASTERISK_GPL_KEY, load_module(), and unregister_all().
 {
    unregister_all();
    return 0;
 }
unregister_all()
static void unregister_all (void) static
Definition at line 143 of file res_pjsip_xpidf_body_generator.c.
References ast_sip_pubsub_unregister_body_generator().
Referenced by load_module(), and unload_module().
 {
    ast_sip_pubsub_unregister_body_generator(&cpim_pidf_body_generator);
    ast_sip_pubsub_unregister_body_generator(&xpidf_body_generator);
 }
xpidf_allocate_body()
static void* xpidf_allocate_body (void * data) static
Definition at line 38 of file res_pjsip_xpidf_body_generator.c.
References ast_strdupa, ast_strip_quoted(), ast_sip_exten_state_data::local, name, and ast_sip_exten_state_data::pool.
 {
    struct ast_sip_exten_state_data *state_data = data;
    char *local = ast_strdupa(state_data->local);
    pjxpidf_pres *pres;
    pj_str_t name;
    pres = pjxpidf_create(state_data->pool, pj_cstr(&name, ast_strip_quoted(local, "<", ">")));
    return pres;
 }
xpidf_generate_body_content()
static int xpidf_generate_body_content (void * body, void * data) static
Definition at line 49 of file res_pjsip_xpidf_body_generator.c.
References ast_sip_presence_exten_state_to_str(), ast_sip_presence_xml_create_attr(), ast_sip_presence_xml_find_node_attr(), ast_sip_sanitize_xml(), ast_sip_exten_state_data::exten, ast_sip_exten_state_data::exten_state, NOTIFY_INUSE, NOTIFY_OPEN, NULL, ast_sip_exten_state_data::pool, ast_sip_exten_state_data::remote, and status.
 {
    pjxpidf_pres *pres = body;
    struct ast_sip_exten_state_data *state_data = data;
    static pj_str_t STR_ADDR_PARAM = { ";user=ip", 8 };
    char *statestring = NULL, *pidfstate = NULL, *pidfnote = NULL;
    pj_xml_attr *attr;
    enum ast_sip_pidf_state local_state;
    pj_str_t uri;
    char sanitized[PJSIP_MAX_URL_SIZE];
    pj_xml_node *atom;
    pj_xml_node *address;
    pj_xml_node *status;
    pj_xml_node *msnsubstatus;
    ast_sip_presence_exten_state_to_str(state_data->exten_state, &statestring,
          &pidfstate, &pidfnote, &local_state, 0);
    ast_sip_presence_xml_find_node_attr(state_data->pool, pres, "atom", "id",
          &atom, &attr);
    pj_strdup2(state_data->pool, &attr->value, state_data->exten);
    ast_sip_presence_xml_find_node_attr(state_data->pool, atom, "address",
          "uri", &address, &attr);
    ast_sip_sanitize_xml(state_data->remote, sanitized, sizeof(sanitized));
    uri.ptr = (char*) pj_pool_alloc(state_data->pool,
          strlen(sanitized) + STR_ADDR_PARAM.slen);
    pj_strcpy2( &uri, sanitized);
    pj_strcat( &uri, &STR_ADDR_PARAM);
    pj_strdup(state_data->pool, &attr->value, &uri);
    ast_sip_presence_xml_create_attr(state_data->pool, address, "priority", "0.80000");
    ast_sip_presence_xml_find_node_attr(state_data->pool, address,
          "status", "status", &status, &attr);
    pj_strdup2(state_data->pool, &attr->value,
          (local_state ==  NOTIFY_OPEN) ? "open" :
          (local_state == NOTIFY_INUSE) ? "inuse" : "closed");
    ast_sip_presence_xml_find_node_attr(state_data->pool, address,
          "msnsubstatus", "substatus", &msnsubstatus, &attr);
    pj_strdup2(state_data->pool, &attr->value,
          (local_state == NOTIFY_OPEN) ? "online" :
          (local_state == NOTIFY_INUSE) ? "onthephone" : "offline");
    return 0;
 }
xpidf_to_string()
static void xpidf_to_string (void * body, struct ast_str ** str) static
Definition at line 101 of file res_pjsip_xpidf_body_generator.c.
References ast_log, AST_PJSIP_XML_PROLOG_LEN, ast_str_buffer(), ast_str_make_space, ast_str_size(), ast_str_update(), LOG_WARNING, and MAX_STRING_GROWTHS.
 {
    pjxpidf_pres *pres = body;
    int growths = 0;
    int size;
    do {
       size = pjxpidf_print(pres, ast_str_buffer(*str), ast_str_size(*str) - 1);
       if (size <= AST_PJSIP_XML_PROLOG_LEN) {
          ast_str_make_space(str, ast_str_size(*str) * 2);
          ++growths;
       }
    } while (size <= AST_PJSIP_XML_PROLOG_LEN && growths < MAX_STRING_GROWTHS);
    if (size <= AST_PJSIP_XML_PROLOG_LEN) {
       ast_log(LOG_WARNING, "XPIDF body text too large\n");
       return;
    }
    *(ast_str_buffer(*str) + size) = '\0';
    ast_str_update(*str);
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "PJSIP Extension State PIDF Provider" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_CHANNEL_DEPEND, .requires = "res_pjsip,res_pjsip_pubsub", } static
Definition at line 178 of file res_pjsip_xpidf_body_generator.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 178 of file res_pjsip_xpidf_body_generator.c.
cpim_pidf_body_generator
struct ast_sip_pubsub_body_generator cpim_pidf_body_generator static
Definition at line 133 of file res_pjsip_xpidf_body_generator.c.
xpidf_body_generator
struct ast_sip_pubsub_body_generator xpidf_body_generator static
Definition at line 123 of file res_pjsip_xpidf_body_generator.c.