Asterisk - The Open Source Telephony Project: ast_dns_resolver Struct Reference
ast_dns_resolver Struct Reference
DNS resolver implementation.
#include <dns_resolver.h>
Public Member Functions
AST_RWLIST_ENTRY (ast_dns_resolver) next
Linked list information.
Data Fields
int(* cancel)(struct ast_dns_query *query)
Cancel resolution of a DNS query.
const char * name
The name of the resolver implementation.
unsigned int priority
Priority for this resolver if multiple exist, lower being higher priority.
int(* resolve)(struct ast_dns_query *query)
Perform resolution of a DNS query.
Detailed Description
DNS resolver implementation.
Definition at line 32 of file dns_resolver.h.
Member Function Documentation
AST_RWLIST_ENTRY()
AST_RWLIST_ENTRY (ast_dns_resolver)
Linked list information.
Field Documentation
cancel
int(* cancel) (struct ast_dns_query *query)
Cancel resolution of a DNS query.
Definition at line 48 of file dns_resolver.h.
Referenced by ast_dns_query_set_resolve_cancel(), ast_dns_resolve_cancel(), and ast_dns_resolver_register().
name
const char* name
The name of the resolver implementation.
Definition at line 34 of file dns_resolver.h.
Referenced by ast_dns_resolve_async(), ast_dns_resolver_register(), ast_dns_resolver_unregister(), AST_TEST_DEFINE(), PathSegment::get_child(), Parameter::load(), SwaggerType::load(), and Property::load().
priority
unsigned int priority
Priority for this resolver if multiple exist, lower being higher priority.
Definition at line 37 of file dns_resolver.h.
Referenced by ast_dns_resolver_register().
resolve
int(* resolve) (struct ast_dns_query *query)
Perform resolution of a DNS query.
Note
The reference count of the query should be increased and released upon the query completing or being successfully cancelled
Definition at line 45 of file dns_resolver.h.
Referenced by ast_dns_query_set_resolve_async(), ast_dns_resolve_async(), and ast_dns_resolver_register().
The documentation for this struct was generated from the following file:
dns_resolver.h