Asterisk - The Open Source Telephony Project: app_mp3.c File Reference
app_mp3.c File Reference
Dial plan applications
Silly application to play an MP3 file – uses mpg123.
#include "asterisk.h"
#include <sys/time.h>
#include <sys/types.h>
#include <signal.h>
#include "asterisk/lock.h"
#include "asterisk/file.h"
#include "asterisk/channel.h"
#include "asterisk/frame.h"
#include "asterisk/pbx.h"
#include "asterisk/module.h"
#include "asterisk/translate.h"
#include "asterisk/app.h"
#include "asterisk/format_cache.h"
Macros
#define LOCAL_MPG_123 "/usr/local/bin/mpg123"
#define MPG_123 "/usr/bin/mpg123"
Functions
AST_MODULE_INFO_STANDARD_EXTENDED (ASTERISK_GPL_KEY, "Silly MP3 Application")
static int load_module (void)
static int mp3_exec (struct ast_channel *chan, const char *data)
static int mp3play (const char *filename, unsigned int sampling_rate, int fd)
static int timed_read (int fd, void *data, int datalen, int timeout, int pid)
static int unload_module (void)
Variables
static char * app = "MP3Player"
Detailed Description
Silly application to play an MP3 file – uses mpg123.
Author
Mark Spencer marks.nosp@m.ter@.nosp@m.digiu.nosp@m.m.co.nosp@m.m
Note
Add feature to play local M3U playlist file Vincent Li mchun.nosp@m..li@.nosp@m.gmail.nosp@m..com
Definition in file app_mp3.c.
Macro Definition Documentation
LOCAL_MPG_123
#define LOCAL_MPG_123 "/usr/local/bin/mpg123"
Definition at line 51 of file app_mp3.c.
Referenced by mp3play().
MPG_123
#define MPG_123 "/usr/bin/mpg123"
Definition at line 52 of file app_mp3.c.
Referenced by mp3play().
Function Documentation
AST_MODULE_INFO_STANDARD_EXTENDED()
AST_MODULE_INFO_STANDARD_EXTENDED (ASTERISK_GPL_KEY , "Silly MP3 Application")
Referenced by load_module().
load_module()
static int load_module (void) static
Definition at line 296 of file app_mp3.c.
References app, AST_MODULE_INFO_STANDARD_EXTENDED(), ast_register_application_xml, ASTERISK_GPL_KEY, and mp3_exec().
 {
    return ast_register_application_xml(app, mp3_exec);
 }
mp3_exec()
static int mp3_exec (struct ast_channel * chan, const char * data) static
Definition at line 172 of file app_mp3.c.
References ao2_bump, ao2_cleanup, ast_channel_nativeformats(), ast_channel_writeformat(), ast_debug, ast_format_cache_get_slin_by_rate(), ast_format_cap_get_format(), ast_format_get_sample_rate(), AST_FRAME_DTMF, AST_FRAME_VOICE, ast_frfree, AST_FRIENDLY_OFFSET, ast_log, ast_read(), ast_samp2tv(), ast_set_write_format(), ast_stopstream(), ast_strlen_zero, ast_tvadd(), ast_tvdiff_ms(), ast_tvnow(), ast_waitfor(), ast_write(), ast_frame::frametype, LOG_WARNING, mp3play(), NULL, ast_frame::offset, RAII_VAR, timed_read(), and timeout.
Referenced by load_module().
 {
    int res=0;
    int fds[2];
    int ms = -1;
    int pid = -1;
    RAII_VAR(struct ast_format *, owriteformat, NULL, ao2_cleanup);
    int timeout = 2;
    struct timeval next;
    struct ast_frame *f;
    struct myframe {
       struct ast_frame f;
       char offset[AST_FRIENDLY_OFFSET];
       short frdata[160];
    } myf = {
       .f = { 0, },
    };
    struct ast_format * native_format;
    unsigned int sampling_rate;
    struct ast_format * write_format;
    if (ast_strlen_zero(data)) {
       ast_log(LOG_WARNING, "MP3 Playback requires an argument (filename)\n");
       return -1;
    }
    if (pipe(fds)) {
       ast_log(LOG_WARNING, "Unable to create pipe\n");
       return -1;
    }
    ast_stopstream(chan);
    native_format = ast_format_cap_get_format(ast_channel_nativeformats(chan), 0);
    sampling_rate = ast_format_get_sample_rate(native_format);
    write_format = ast_format_cache_get_slin_by_rate(sampling_rate);
    owriteformat = ao2_bump(ast_channel_writeformat(chan));
    res = ast_set_write_format(chan, write_format);
    if (res < 0) {
       ast_log(LOG_WARNING, "Unable to set write format to signed linear\n");
       return -1;
    }
    myf.f.frametype = AST_FRAME_VOICE;
    myf.f.subclass.format = write_format;
    myf.f.mallocd = 0;
    myf.f.offset = AST_FRIENDLY_OFFSET;
    myf.f.src = __PRETTY_FUNCTION__;
    myf.f.delivery.tv_sec = 0;
    myf.f.delivery.tv_usec = 0;
    myf.f.data.ptr = myf.frdata;
    res = mp3play(data, sampling_rate, fds[1]);
    if (!strncasecmp(data, "http://", 7)) {
       timeout = 10;
    }
    /* Wait 1000 ms first */
    next = ast_tvnow();
    next.tv_sec += 1;
    if (res >= 0) {
       pid = res;
       /* Order is important -- there's almost always going to be mp3...  we want to prioritize the
          user */
       for (;;) {
          ms = ast_tvdiff_ms(next, ast_tvnow());
          if (ms <= 0) {
             res = timed_read(fds[0], myf.frdata, sizeof(myf.frdata), timeout, pid);
             if (res > 0) {
                myf.f.datalen = res;
                myf.f.samples = res / 2;
                if (ast_write(chan, &myf.f) < 0) {
                   res = -1;
                   break;
                }
             } else {
                ast_debug(1, "No more mp3\n");
                res = 0;
                break;
             }
             next = ast_tvadd(next, ast_samp2tv(myf.f.samples, sampling_rate));
          } else {
             ms = ast_waitfor(chan, ms);
             if (ms < 0) {
                ast_debug(1, "Hangup detected\n");
                res = -1;
                break;
             }
             if (ms) {
                f = ast_read(chan);
                if (!f) {
                   ast_debug(1, "Null frame == hangup() detected\n");
                   res = -1;
                   break;
                }
                if (f->frametype == AST_FRAME_DTMF) {
                   ast_debug(1, "User pressed a key\n");
                   ast_frfree(f);
                   res = 0;
                   break;
                }
                ast_frfree(f);
             }
          }
       }
    }
    close(fds[0]);
    close(fds[1]);
    if (pid > -1)
       kill(pid, SIGKILL);
    if (!res && owriteformat)
       ast_set_write_format(chan, owriteformat);
    ast_frfree(&myf.f);
    return res;
 }
mp3play()
static int mp3play (const char * filename, unsigned int sampling_rate, int fd) static
Definition at line 79 of file app_mp3.c.
References ast_close_fds_above_n(), ast_log, ast_opt_high_priority, ast_safe_fork(), ast_set_priority(), LOCAL_MPG_123, LOG_WARNING, MPG_123, and NULL.
Referenced by mp3_exec().
 {
    int res;
    char sampling_rate_str[8];
    res = ast_safe_fork(0);
    if (res < 0)
       ast_log(LOG_WARNING, "Fork failed\n");
    if (res) {
       return res;
    }
    if (ast_opt_high_priority)
       ast_set_priority(0);
    dup2(fd, STDOUT_FILENO);
    ast_close_fds_above_n(STDERR_FILENO);
    snprintf(sampling_rate_str, 8, "%u", sampling_rate);
    /* Execute mpg123, but buffer if it's a net connection */
    if (!strncasecmp(filename, "http://", 7) && strstr(filename, ".m3u")) {
        char buffer_size_str[8];
        snprintf(buffer_size_str, 8, "%u", (int) 0.5*2*sampling_rate/1000); // 0.5 seconds for a live stream
       /* Most commonly installed in /usr/local/bin */
        execl(LOCAL_MPG_123, "mpg123", "-q", "-s", "-b", buffer_size_str, "-f", "8192", "--mono", "-r", sampling_rate_str, "-@", filename, (char *)NULL);
       /* But many places has it in /usr/bin */
        execl(MPG_123, "mpg123", "-q", "-s", "-b", buffer_size_str, "-f", "8192", "--mono", "-r", sampling_rate_str, "-@", filename, (char *)NULL);
       /* As a last-ditch effort, try to use PATH */
        execlp("mpg123", "mpg123", "-q", "-s", "-b", buffer_size_str, "-f", "8192", "--mono", "-r", sampling_rate_str, "-@", filename, (char *)NULL);
    }
    else if (!strncasecmp(filename, "http://", 7)) {
        char buffer_size_str[8];
        snprintf(buffer_size_str, 8, "%u", 6*2*sampling_rate/1000); // 6 seconds for a remote MP3 file
       /* Most commonly installed in /usr/local/bin */
        execl(LOCAL_MPG_123, "mpg123", "-q", "-s", "-b", buffer_size_str, "-f", "8192", "--mono", "-r", sampling_rate_str, filename, (char *)NULL);
       /* But many places has it in /usr/bin */
        execl(MPG_123, "mpg123", "-q", "-s", "-b", buffer_size_str, "-f", "8192", "--mono", "-r", sampling_rate_str, filename, (char *)NULL);
       /* As a last-ditch effort, try to use PATH */
        execlp("mpg123", "mpg123", "-q", "-s", "-b", buffer_size_str, "-f", "8192", "--mono", "-r", sampling_rate_str, filename, (char *)NULL);
    }
    else if (strstr(filename, ".m3u")) {
       /* Most commonly installed in /usr/local/bin */
        execl(LOCAL_MPG_123, "mpg123", "-q", "-z", "-s", "-f", "8192", "--mono", "-r", sampling_rate_str, "-@", filename, (char *)NULL);
       /* But many places has it in /usr/bin */
        execl(MPG_123, "mpg123", "-q", "-z", "-s", "-f", "8192", "--mono", "-r", sampling_rate_str, "-@", filename, (char *)NULL);
       /* As a last-ditch effort, try to use PATH */
        execlp("mpg123", "mpg123", "-q", "-z", "-s",  "-f", "8192", "--mono", "-r", sampling_rate_str, "-@", filename, (char *)NULL);
    }
    else {
       /* Most commonly installed in /usr/local/bin */
        execl(MPG_123, "mpg123", "-q", "-s", "-f", "8192", "--mono", "-r", sampling_rate_str, filename, (char *)NULL);
       /* But many places has it in /usr/bin */
        execl(LOCAL_MPG_123, "mpg123", "-q", "-s", "-f", "8192", "--mono", "-r", sampling_rate_str, filename, (char *)NULL);
       /* As a last-ditch effort, try to use PATH */
        execlp("mpg123", "mpg123", "-q", "-s", "-f", "8192", "--mono", "-r", sampling_rate_str, filename, (char *)NULL);
    }
    /* Can't use ast_log since FD's are closed */
    fprintf(stderr, "Execute of mpg123 failed\n");
    _exit(0);
 }
timed_read()
static int timed_read (int fd, void * data, int datalen, int timeout, int pid) static
Definition at line 140 of file app_mp3.c.
References ast_log, ast_poll, errno, LOG_NOTICE, and timeout.
Referenced by mp3_exec().
 {
    int res;
    int i;
    struct pollfd fds[1];
    fds[0].fd = fd;
    fds[0].events = POLLIN;
    for (i = 0; i < timeout; i++) {
       res = ast_poll(fds, 1, 1000);
       if (res > 0) {
          break;
       } else if (res == 0) {
          /* is mpg123 still running? */
          kill(pid, 0);
          if (errno == ESRCH) {
             return -1;
          }
       } else {
          ast_log(LOG_NOTICE, "error polling mpg123: %s\n", strerror(errno));
          return -1;
       }
    }
    if (i == timeout) {
       ast_log(LOG_NOTICE, "Poll timed out.\n");
       return -1;
    }
    return read(fd, data, datalen);
 }
unload_module()
static int unload_module (void) static
Definition at line 291 of file app_mp3.c.
References app, and ast_unregister_application().
 {
    return ast_unregister_application(app);
 }
Variable Documentation
app
char* app = "MP3Player" static
Definition at line 77 of file app_mp3.c.
Referenced by load_module(), and unload_module().