Asterisk - The Open Source Telephony Project: syslog.h File Reference
syslog.h File Reference
Syslog support functions for Asterisk logging.
Macros
#define ASTNUMLOGLEVELS 32
Functions
int ast_syslog_facility (const char *facility)
Maps a syslog facility name from a string to a syslog facility constant.
const char * ast_syslog_facility_name (int facility)
Maps a syslog facility constant to a string.
int ast_syslog_priority (const char *priority)
Maps a syslog priority name from a string to a syslog priority constant.
int ast_syslog_priority_from_loglevel (int level)
Maps an Asterisk log level (i.e. LOG_ERROR) to a syslog priority constant.
const char * ast_syslog_priority_name (int priority)
Maps a syslog priority constant to a string.
Detailed Description
Syslog support functions for Asterisk logging.
Definition in file syslog.h.
Macro Definition Documentation
ASTNUMLOGLEVELS
#define ASTNUMLOGLEVELS 32
Definition at line 31 of file syslog.h.
Referenced by ast_syslog_priority_from_loglevel().
Function Documentation
ast_syslog_facility()
int ast_syslog_facility (const char * facility)
Maps a syslog facility name from a string to a syslog facility constant.
Since
1.8
Parameters
facility Facility name to map (i.e. "daemon")
Return values
syslog facility constant (i.e. LOG_DAEMON) if found
-1 if facility is not found
Definition at line 85 of file syslog.c.
References ARRAY_LEN, facility_map, and name.
Referenced by load_config(), and make_logchannel().
 {
    int index;
    for (index = 0; index < ARRAY_LEN(facility_map); index++) {
       if (!strcasecmp(facility_map[index].name, facility)) {
          return facility_map[index].value;
       }
    }
    return -1;
 }
ast_syslog_facility_name()
const char* ast_syslog_facility_name (int facility)
Maps a syslog facility constant to a string.
Since
1.8
Parameters
facility syslog facility constant to map (i.e. LOG_DAEMON)
Return values
facility name (i.e. "daemon") if found
NULL if facility is not found
Definition at line 98 of file syslog.c.
References ARRAY_LEN, facility_map, LOG_DEBUG, LOG_NOTICE, LOG_WARNING, name, NULL, priority_map, and value.
Referenced by load_config().
 {
    int index;
    for (index = 0; index < ARRAY_LEN(facility_map); index++) {
       if (facility_map[index].value == facility) {
          return facility_map[index].name;
       }
    }
    return NULL;
 }
ast_syslog_priority()
int ast_syslog_priority (const char * priority)
Maps a syslog priority name from a string to a syslog priority constant.
Since
1.8
Parameters
priority Priority name to map (i.e. "notice")
Return values
syslog priority constant (i.e. LOG_NOTICE) if found
-1 if priority is not found
Definition at line 126 of file syslog.c.
References ARRAY_LEN, name, and priority_map.
Referenced by load_config().
 {
    int index;
    for (index = 0; index < ARRAY_LEN(priority_map); index++) {
       if (!strcasecmp(priority_map[index].name, priority)) {
          return priority_map[index].value;
       }
    }
    return -1;
 }
ast_syslog_priority_from_loglevel()
int ast_syslog_priority_from_loglevel (int level)
Maps an Asterisk log level (i.e. LOG_ERROR) to a syslog priority constant.
Since
1.8
Parameters
level Asterisk log level constant (i.e. LOG_ERROR)
Return values
syslog priority constant (i.e. LOG_ERR) if found
-1 if priority is not found
Definition at line 162 of file syslog.c.
References ARRAY_LEN, ASTNUMLOGLEVELS, LOG_NOTICE, and logger_level_to_syslog_map.
Referenced by logger_print_normal().
 {
    /* First 16 levels are reserved for system use.
     * Default to using LOG_NOTICE for dynamic logging.
     */
    if (level >= 16 && level < ASTNUMLOGLEVELS) {
       return LOG_NOTICE;
    }
    if (level < 0 || level >= ARRAY_LEN(logger_level_to_syslog_map)) {
       return -1;
    }
    return logger_level_to_syslog_map[level];
 }
ast_syslog_priority_name()
const char* ast_syslog_priority_name (int priority)
Maps a syslog priority constant to a string.
Since
1.8
Parameters
priority syslog priority constant to map (i.e. LOG_NOTICE)
Return values
priority name (i.e. "notice") if found
NULL if priority is not found
Definition at line 139 of file syslog.c.
References ARRAY_LEN, NULL, priority_map, and value.
Referenced by load_config().
 {
    int index;
    for (index = 0; index < ARRAY_LEN(priority_map); index++) {
       if (priority_map[index].value == priority) {
          return priority_map[index].name;
       }
    }
    return NULL;
 }