Asterisk - The Open Source Telephony Project: func_scramble.c File Reference
func_scramble.c File Reference
Module: Dial plan functions
Frequency inverter.
#include "asterisk.h"
#include "asterisk/module.h"
#include "asterisk/channel.h"
#include "asterisk/pbx.h"
#include "asterisk/utils.h"
#include "asterisk/audiohook.h"
#include "asterisk/app.h"
#include <stdio.h>
#include <string.h>
Data Structures
struct scramble_information
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static void destroy_callback (void *data)
static void freq_invert (short *amp, int samples)
static int load_module (void)
static int remove_scrambler (struct ast_channel *chan)
static int scramble_callback (struct ast_audiohook *audiohook, struct ast_channel *chan, struct ast_frame *frame, enum ast_audiohook_direction direction)
static int scramble_write (struct ast_channel *chan, const char *cmd, char *data, const char *value)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Frequency inverting voice scrambler" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, }
static const struct ast_module_info * ast_module_info = &__mod_info
static const struct ast_datastore_info scramble_datastore
Static structure for datastore information.
static struct ast_custom_function scramble_function
Detailed Description
Frequency inverter.
Author
Naveen Albert aster.nosp@m.isk@.nosp@m.phrea.nosp@m.knet.nosp@m..org
Definition in file func_scramble.c.
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 239 of file func_scramble.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 239 of file func_scramble.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 239 of file func_scramble.c.
destroy_callback()
static void destroy_callback (void * data) static
Definition at line 77 of file func_scramble.c.
References ast_audiohook_destroy(), ast_audiohook_detach(), ast_audiohook_lock, ast_audiohook_unlock, ast_free, and scramble_information::audiohook.
 {
    struct scramble_information *ni = data;
    /* Destroy the audiohook, and destroy ourselves */
    ast_audiohook_lock(&ni->audiohook);
    ast_audiohook_detach(&ni->audiohook);
    ast_audiohook_unlock(&ni->audiohook);
    ast_audiohook_destroy(&ni->audiohook);
    ast_free(ni);
    return;
 }
freq_invert()
static void freq_invert (short * amp, int samples) inline static
Definition at line 99 of file func_scramble.c.
Referenced by scramble_callback().
 {
    int i;
    /* invert every other sample by 1 */
    for (i = 0; i < samples; i += 2)
       amp[i] = -amp[i];
 }
load_module()
static int load_module (void) static
Definition at line 234 of file func_scramble.c.
References ast_custom_function_register.
 {
    return ast_custom_function_register(&scramble_function);
 }
remove_scrambler()
static int remove_scrambler (struct ast_channel * chan) static
Definition at line 131 of file func_scramble.c.
References ast_audiohook_remove(), ast_channel_datastore_find(), ast_channel_datastore_remove(), ast_channel_name(), ast_datastore_free(), ast_log, AST_LOG_WARNING, scramble_information::audiohook, ast_datastore::data, NULL, and SCOPED_CHANNELLOCK.
Referenced by scramble_write().
 {
    struct ast_datastore *datastore = NULL;
    struct scramble_information *data;
    SCOPED_CHANNELLOCK(chan_lock, chan);
    datastore = ast_channel_datastore_find(chan, &scramble_datastore, NULL);
    if (!datastore) {
       ast_log(AST_LOG_WARNING, "Cannot remove SCRAMBLE from %s: SCRAMBLE not currently enabled\n",
               ast_channel_name(chan));
       return -1;
    }
    data = datastore->data;
    if (ast_audiohook_remove(chan, &data->audiohook)) {
       ast_log(AST_LOG_WARNING, "Failed to remove SCRAMBLE audiohook from channel %s\n", ast_channel_name(chan));
       return -1;
    }
    if (ast_channel_datastore_remove(chan, datastore)) {
       ast_log(AST_LOG_WARNING, "Failed to remove SCRAMBLE datastore from channel %s\n",
               ast_channel_name(chan));
       return -1;
    }
    ast_datastore_free(datastore);
    return 0;
 }
scramble_callback()
static int scramble_callback (struct ast_audiohook * audiohook, struct ast_channel * chan, struct ast_frame * frame, enum ast_audiohook_direction direction) static
Definition at line 107 of file func_scramble.c.
References AST_AUDIOHOOK_DIRECTION_READ, AST_AUDIOHOOK_STATUS_DONE, ast_channel_datastore_find(), AST_FRAME_VOICE, ast_frame::data, ast_frame::frametype, freq_invert(), NULL, ast_frame::ptr, scramble_information::rx, ast_frame::samples, ast_audiohook::status, and scramble_information::tx.
Referenced by scramble_write().
 {
    struct ast_datastore *datastore = NULL;
    struct scramble_information *ni = NULL;
    /* If the audiohook is stopping it means the channel is shutting down.... but we let the datastore destroy take care of it */
    if (audiohook->status == AST_AUDIOHOOK_STATUS_DONE)
       return 0;
    /* Grab datastore which contains our gain information */
    if (!(datastore = ast_channel_datastore_find(chan, &scramble_datastore, NULL)))
       return 0;
    if (frame->frametype == AST_FRAME_VOICE) { /* only invert voice frequencies */
       /* Based on direction of frame, and confirm it is applicable */
       if (!(direction == AST_AUDIOHOOK_DIRECTION_READ ? &ni->rx : &ni->tx))
          return 0;
       /* Scramble the sample now */
       freq_invert(frame->data.ptr, frame->samples);
    }
    return 0;
 }
scramble_write()
static int scramble_write (struct ast_channel * chan, const char * cmd, char * data, const char * value) static
Definition at line 160 of file func_scramble.c.
References args, AST_APP_ARG, ast_audiohook_attach(), ast_audiohook_init(), AST_AUDIOHOOK_MANIPULATE_ALL_RATES, AST_AUDIOHOOK_TYPE_MANIPULATE, ast_calloc, ast_channel_datastore_add(), ast_channel_datastore_find(), ast_channel_lock, ast_channel_unlock, ast_datastore_alloc, ast_datastore_free(), AST_DECLARE_APP_ARGS, ast_log, AST_STANDARD_APP_ARGS, ast_strdupa, scramble_information::audiohook, ast_datastore::data, LOG_ERROR, LOG_WARNING, ast_audiohook::manipulate_callback, NULL, parse(), remove_scrambler(), scramble_information::rx, scramble_callback(), and scramble_information::tx.
 {
    char *parse;
    struct ast_datastore *datastore = NULL;
    struct scramble_information *ni = NULL;
    int is_new = 0;
    AST_DECLARE_APP_ARGS(args,
       AST_APP_ARG(direction);
    );
    if (!chan) {
       ast_log(LOG_WARNING, "No channel was provided to %s function.\n", cmd);
       return -1;
    }
    parse = ast_strdupa(value);
    AST_STANDARD_APP_ARGS(args, parse);
    ast_channel_lock(chan);
    if (!(datastore = ast_channel_datastore_find(chan, &scramble_datastore, NULL))) {
       ast_channel_unlock(chan);
       /* Allocate a new datastore to hold the reference to this audiohook information */
       if (!(datastore = ast_datastore_alloc(&scramble_datastore, NULL)))
          return 0;
       if (!(ni = ast_calloc(1, sizeof(*ni)))) {
          ast_datastore_free(datastore);
          return 0;
       }
       ast_audiohook_init(&ni->audiohook, AST_AUDIOHOOK_TYPE_MANIPULATE, "Voice scrambler", AST_AUDIOHOOK_MANIPULATE_ALL_RATES);
       ni->audiohook.manipulate_callback = scramble_callback;
       is_new = 1;
    } else {
       ast_channel_unlock(chan);
       ni = datastore->data;
    }
    if (!strcasecmp(args.direction, "tx")) {
       ni->tx = 1;
       ni->rx = 0;
    } else if (!strcasecmp(args.direction, "rx")) {
       ni->rx = 0;
       ni->tx = 1;
    } else if (!strcasecmp(args.direction, "both")) {
       ni->rx = 1;
       ni->tx = 1;
    } else if (!strcasecmp(args.direction, "remove")) {
       return remove_scrambler(chan);
    } else {
       ast_log(LOG_ERROR, "Direction must be either RX, TX or remove\n");
       return -1;
    }
    if (is_new) {
       datastore->data = ni;
       ast_channel_lock(chan);
       ast_channel_datastore_add(chan, datastore);
       ast_channel_unlock(chan);
       ast_audiohook_attach(chan, &ni->audiohook);
    }
    return 0;
 }
unload_module()
static int unload_module (void) static
Definition at line 229 of file func_scramble.c.
References ast_custom_function_unregister().
 {
    return ast_custom_function_unregister(&scramble_function);
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Frequency inverting voice scrambler" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, } static
Definition at line 239 of file func_scramble.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 239 of file func_scramble.c.
scramble_datastore
const struct ast_datastore_info scramble_datastore static
Initial value:
= {
   .type = "scramble",
   .destroy = destroy_callback
}
Static structure for datastore information.
Definition at line 92 of file func_scramble.c.
scramble_function
struct ast_custom_function scramble_function static
Initial value:
= {
   .name = "SCRAMBLE",
   .write = scramble_write,
}
Definition at line 224 of file func_scramble.c.