Asterisk - The Open Source Telephony Project: res_mwi_external.c File Reference
res_mwi_external.c File Reference
Core external MWI support.
#include "asterisk.h"
#include "asterisk/app.h"
#include "asterisk/mwi.h"
#include "asterisk/module.h"
#include "asterisk/res_mwi_external.h"
#include "asterisk/sorcery.h"
#include "asterisk/cli.h"
Data Structures
struct ast_mwi_mailbox_object
Macros
#define FORMAT_MAILBOX_HDR "%6s %6s %s\n"
#define FORMAT_MAILBOX_ROW "%6u %6u %s\n"
#define MWI_ASTDB_PREFIX "mwi_external"
#define MWI_MAILBOX_TYPE "mailboxes"
Enumerations
enum folder_map { FOLDER_INVALID = 0, FOLDER_INBOX = 1, FOLDER_OLD = 2 }
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
struct ast_mwi_mailbox_object * ast_mwi_mailbox_alloc (const char *mailbox_id)
Allocate an external MWI object.
struct ast_mwi_mailbox_object * ast_mwi_mailbox_copy (const struct ast_mwi_mailbox_object *mailbox)
Copy the external MWI counts object.
int ast_mwi_mailbox_delete (const char *mailbox_id)
Delete matching external MWI object.
int ast_mwi_mailbox_delete_all (void)
Delete all external MWI objects.
int ast_mwi_mailbox_delete_by_regex (const char *regex)
Delete all external MWI objects selected by the regular expression.
const struct ast_mwi_mailbox_object * ast_mwi_mailbox_get (const char *mailbox_id)
Get matching external MWI object.
struct ao2_container * ast_mwi_mailbox_get_all (void)
Get all external MWI objects.
struct ao2_container * ast_mwi_mailbox_get_by_regex (const char *regex)
Get all external MWI objects selected by the regular expression.
const char * ast_mwi_mailbox_get_id (const struct ast_mwi_mailbox_object *mailbox)
Get mailbox id.
unsigned int ast_mwi_mailbox_get_msgs_new (const struct ast_mwi_mailbox_object *mailbox)
Get the number of new messages.
unsigned int ast_mwi_mailbox_get_msgs_old (const struct ast_mwi_mailbox_object *mailbox)
Get the number of old messages.
void ast_mwi_mailbox_set_msgs_new (struct ast_mwi_mailbox_object *mailbox, unsigned int num_msgs)
Set the number of new messages.
void ast_mwi_mailbox_set_msgs_old (struct ast_mwi_mailbox_object *mailbox, unsigned int num_msgs)
Set the number of old messages.
int ast_mwi_mailbox_update (struct ast_mwi_mailbox_object *mailbox)
Update the external MWI counts with the given object.
static int load_module (void)
static enum folder_map mwi_folder_map (const char *folder)
static int mwi_has_voicemail (const char *mailboxes, const char *folder)
static int mwi_inboxcount (const char *mailboxes, int *newmsgs, int *oldmsgs)
static int mwi_inboxcount2 (const char *mailboxes, int *urgentmsgs, int *newmsgs, int *oldmsgs)
static void mwi_initial_events (void)
static void mwi_mailbox_delete (struct ast_mwi_mailbox_object *mailbox)
static void mwi_mailbox_delete_all (struct ao2_container *mailboxes)
static int mwi_messagecount (const char *mailbox_id, const char *folder)
static void mwi_observe_delete (const void *obj)
static void mwi_observe_update (const void *obj)
static void mwi_post_event (const struct ast_mwi_mailbox_object *mailbox)
static int mwi_sorcery_init (void)
static void * mwi_sorcery_object_alloc (const char *id)
Internal function to allocate a mwi object.
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_GLOBAL_SYMBOLS | AST_MODFLAG_LOAD_ORDER , .description = "Core external MWI resource" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_CHANNEL_DEPEND - 5, }
static const struct ast_module_info * ast_module_info = &__mod_info
static const struct ast_sorcery_observer mwi_observers
static struct ast_sorcery * mwi_sorcery
static const struct ast_vm_functions vm_table
Detailed Description
Core external MWI support.
The module manages the persistent message counts cache and supplies an API to allow the protocol specific modules to control the counts or a subset.
Author
Richard Mudgett rmudg.nosp@m.ett@.nosp@m.digiu.nosp@m.m.co.nosp@m.m
See Also:
CREDITS
Definition in file res_mwi_external.c.
Macro Definition Documentation
FORMAT_MAILBOX_HDR
#define FORMAT_MAILBOX_HDR "%6s %6s %s\n"
Definition at line 650 of file res_mwi_external.c.
FORMAT_MAILBOX_ROW
#define FORMAT_MAILBOX_ROW "%6u %6u %s\n"
Definition at line 651 of file res_mwi_external.c.
MWI_ASTDB_PREFIX
#define MWI_ASTDB_PREFIX "mwi_external"
Define to include CLI commands to manipulate the external MWI mailboxes. Useful for testing the module functionality.
Definition at line 72 of file res_mwi_external.c.
Referenced by mwi_sorcery_init().
MWI_MAILBOX_TYPE
#define MWI_MAILBOX_TYPE "mailboxes"
Definition at line 73 of file res_mwi_external.c.
Referenced by ast_mwi_mailbox_alloc(), ast_mwi_mailbox_get(), ast_mwi_mailbox_get_all(), ast_mwi_mailbox_get_by_regex(), ast_mwi_mailbox_update(), load_module(), mwi_sorcery_init(), and unload_module().
Enumeration Type Documentation
folder_map
enum folder_map
Enumerator
FOLDER_INVALID
FOLDER_INBOX
FOLDER_OLD
Definition at line 326 of file res_mwi_external.c.
                 {
    FOLDER_INVALID = 0,
    FOLDER_INBOX = 1,
    FOLDER_OLD = 2,
 };
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 957 of file res_mwi_external.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 957 of file res_mwi_external.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 957 of file res_mwi_external.c.
ast_mwi_mailbox_alloc()
struct ast_mwi_mailbox_object* ast_mwi_mailbox_alloc (const char * mailbox_id)
Allocate an external MWI object.
Since
12.1.0
Parameters
mailbox_id Name of mailbox.
Return values
object on success. The object is an ao2 object.
NULL on error.
Definition at line 196 of file res_mwi_external.c.
References ast_sorcery_alloc(), ast_strlen_zero, MWI_MAILBOX_TYPE, and NULL.
Referenced by mwi_mailbox_update(), and stasis_app_mailbox_update().
 {
    if (ast_strlen_zero(mailbox_id)) {
       return NULL;
    }
    return ast_sorcery_alloc(mwi_sorcery, MWI_MAILBOX_TYPE, mailbox_id);
 }
ast_mwi_mailbox_copy()
struct ast_mwi_mailbox_object* ast_mwi_mailbox_copy (const struct ast_mwi_mailbox_object * mailbox)
Copy the external MWI counts object.
Since
12.1.0
Parameters
mailbox What to copy.
Return values
copy on success. The object is an ao2 object.
NULL on error.
Definition at line 205 of file res_mwi_external.c.
References ast_sorcery_copy().
 {
    return ast_sorcery_copy(mwi_sorcery, mailbox);
 }
ast_mwi_mailbox_delete()
int ast_mwi_mailbox_delete (const char * mailbox_id)
Delete matching external MWI object.
Since
12.1.0
Parameters
mailbox_id Name of mailbox to delete.
Return values
0 on success.
-1 on error.
Definition at line 310 of file res_mwi_external.c.
References ast_mwi_mailbox_get(), ast_mwi_mailbox_unref, ast_strlen_zero, mailbox, and mwi_mailbox_delete().
Referenced by mwi_mailbox_delete(), and stasis_app_mailbox_delete().
 {
    const struct ast_mwi_mailbox_object *mailbox;
    if (ast_strlen_zero(mailbox_id)) {
       return -1;
    }
    mailbox = ast_mwi_mailbox_get(mailbox_id);
    if (mailbox) {
       mwi_mailbox_delete((struct ast_mwi_mailbox_object *) mailbox);
       ast_mwi_mailbox_unref(mailbox);
    }
    return 0;
 }
ast_mwi_mailbox_delete_all()
int ast_mwi_mailbox_delete_all (void)
Delete all external MWI objects.
Since
12.1.0
Return values
0 on success.
-1 on error.
Definition at line 286 of file res_mwi_external.c.
References ao2_ref, ast_mwi_mailbox_get_all(), mailboxes, and mwi_mailbox_delete_all().
 {
    struct ao2_container *mailboxes;
    mailboxes = ast_mwi_mailbox_get_all();
    if (mailboxes) {
       mwi_mailbox_delete_all(mailboxes);
       ao2_ref(mailboxes, -1);
    }
    return 0;
 }
ast_mwi_mailbox_delete_by_regex()
int ast_mwi_mailbox_delete_by_regex (const char * regex)
Delete all external MWI objects selected by the regular expression.
Since
12.1.0
Parameters
regex Regular expression in extended syntax. (NULL is same as "")
Note
The provided regex is treated as extended case sensitive.
Return values
0 on success.
-1 on error.
Definition at line 298 of file res_mwi_external.c.
References ao2_ref, ast_mwi_mailbox_get_by_regex(), mailboxes, and mwi_mailbox_delete_all().
Referenced by mwi_mailbox_delete().
 {
    struct ao2_container *mailboxes;
    mailboxes = ast_mwi_mailbox_get_by_regex(regex);
    if (mailboxes) {
       mwi_mailbox_delete_all(mailboxes);
       ao2_ref(mailboxes, -1);
    }
    return 0;
 }
ast_mwi_mailbox_get()
const struct ast_mwi_mailbox_object* ast_mwi_mailbox_get (const char * mailbox_id)
Get matching external MWI object.
Since
12.1.0
Parameters
mailbox_id Name of mailbox to retrieve.
Return values
requested mailbox on success. The object is an ao2 object.
NULL on error or no mailbox.
Note
The object must be treated as read-only.
Definition at line 187 of file res_mwi_external.c.
References ast_sorcery_retrieve_by_id(), ast_strlen_zero, MWI_MAILBOX_TYPE, and NULL.
Referenced by ast_mwi_mailbox_delete(), mwi_has_voicemail(), mwi_inboxcount(), mwi_mailbox_get(), mwi_messagecount(), stasis_app_mailbox_delete(), and stasis_app_mailbox_to_json().
 {
    if (ast_strlen_zero(mailbox_id)) {
       return NULL;
    }
    return ast_sorcery_retrieve_by_id(mwi_sorcery, MWI_MAILBOX_TYPE, mailbox_id);
 }
ast_mwi_mailbox_get_all()
struct ao2_container* ast_mwi_mailbox_get_all (void)
Get all external MWI objects.
Since
12.1.0
Return values
container of struct ast_mwi_mailbox_object on success.
NULL on error.
Note
The objects in the container must be treated as read-only.
Definition at line 176 of file res_mwi_external.c.
References AST_RETRIEVE_FLAG_ALL, AST_RETRIEVE_FLAG_MULTIPLE, ast_sorcery_retrieve_by_fields(), MWI_MAILBOX_TYPE, and NULL.
Referenced by ast_mwi_mailbox_delete_all(), mwi_initial_events(), and stasis_app_mailboxes_to_json().
 {
    return ast_sorcery_retrieve_by_fields(mwi_sorcery, MWI_MAILBOX_TYPE,
       AST_RETRIEVE_FLAG_MULTIPLE | AST_RETRIEVE_FLAG_ALL, NULL);
 }
ast_mwi_mailbox_get_by_regex()
struct ao2_container* ast_mwi_mailbox_get_by_regex (const char * regex)
Get all external MWI objects selected by the regular expression.
Since
12.1.0
Parameters
regex Regular expression in extended syntax. (NULL is same as "")
Note
The provided regex is treated as extended case sensitive.
Return values
container of struct ast_mwi_mailbox_object on success.
NULL on error.
Note
The objects in the container must be treated as read-only.
Definition at line 182 of file res_mwi_external.c.
References ast_sorcery_retrieve_by_regex(), and MWI_MAILBOX_TYPE.
Referenced by ast_mwi_mailbox_delete_by_regex(), and mwi_mailbox_get().
 {
    return ast_sorcery_retrieve_by_regex(mwi_sorcery, MWI_MAILBOX_TYPE, regex ?: "");
 }
ast_mwi_mailbox_get_id()
const char* ast_mwi_mailbox_get_id (const struct ast_mwi_mailbox_object * mailbox)
Get mailbox id.
Since
12.1.0
Parameters
mailbox Object to get id.
Returns
mailbox_id of the object.
Note
This should never return NULL unless there is a bug in sorcery.
Definition at line 210 of file res_mwi_external.c.
References ast_sorcery_object_get_id().
Referenced by mailbox_to_json(), and mwi_mailbox_get().
 {
    return ast_sorcery_object_get_id(mailbox);
 }
ast_mwi_mailbox_get_msgs_new()
unsigned int ast_mwi_mailbox_get_msgs_new (const struct ast_mwi_mailbox_object * mailbox)
Get the number of new messages.
Since
12.1.0
Parameters
mailbox Object to get number of new messages.
Returns
Number of new messages.
Definition at line 215 of file res_mwi_external.c.
References ast_mwi_mailbox_object::msgs_new.
Referenced by mailbox_to_json(), and mwi_mailbox_get().
 {
    return mailbox->msgs_new;
 }
ast_mwi_mailbox_get_msgs_old()
unsigned int ast_mwi_mailbox_get_msgs_old (const struct ast_mwi_mailbox_object * mailbox)
Get the number of old messages.
Since
12.1.0
Parameters
mailbox Object to get number of old messages.
Returns
Number of old messages.
Definition at line 220 of file res_mwi_external.c.
References ast_mwi_mailbox_object::msgs_old.
Referenced by mailbox_to_json(), and mwi_mailbox_get().
 {
    return mailbox->msgs_old;
 }
ast_mwi_mailbox_set_msgs_new()
void ast_mwi_mailbox_set_msgs_new (struct ast_mwi_mailbox_object * mailbox, unsigned int num_msgs)
Set the number of new messages.
Since
12.1.0
Parameters
mailbox Object to set number of new messages.
num_msgs Number of messages to set.
Returns
Nothing
Definition at line 225 of file res_mwi_external.c.
References ast_mwi_mailbox_object::msgs_new.
Referenced by mwi_mailbox_update(), and stasis_app_mailbox_update().
 {
    mailbox->msgs_new = num_msgs;
 }
ast_mwi_mailbox_set_msgs_old()
void ast_mwi_mailbox_set_msgs_old (struct ast_mwi_mailbox_object * mailbox, unsigned int num_msgs)
Set the number of old messages.
Since
12.1.0
Parameters
mailbox Object to set number of old messages.
num_msgs Number of messages to set.
Returns
Nothing
Definition at line 230 of file res_mwi_external.c.
References ast_mwi_mailbox_object::msgs_old.
Referenced by mwi_mailbox_update(), and stasis_app_mailbox_update().
 {
    mailbox->msgs_old = num_msgs;
 }
ast_mwi_mailbox_update()
int ast_mwi_mailbox_update (struct ast_mwi_mailbox_object * mailbox)
Update the external MWI counts with the given object.
Since
12.1.0
Parameters
mailbox What to update.
Return values
0 on success.
-1 on error.
Definition at line 235 of file res_mwi_external.c.
References ast_mwi_mailbox_unref, ast_sorcery_create(), ast_sorcery_object_get_id(), ast_sorcery_retrieve_by_id(), ast_sorcery_update(), exists(), and MWI_MAILBOX_TYPE.
Referenced by mwi_mailbox_update(), and stasis_app_mailbox_update().
 {
    const struct ast_mwi_mailbox_object *exists;
    int res;
    exists = ast_sorcery_retrieve_by_id(mwi_sorcery, MWI_MAILBOX_TYPE,
       ast_sorcery_object_get_id(mailbox));
    if (exists) {
       res = ast_sorcery_update(mwi_sorcery, mailbox);
       ast_mwi_mailbox_unref(exists);
    } else {
       res = ast_sorcery_create(mwi_sorcery, mailbox);
    }
    return res;
 }
load_module()
static int load_module (void) static
Definition at line 924 of file res_mwi_external.c.
References ARRAY_LEN, ast_cli_register_multiple, ast_log, AST_MODFLAG_GLOBAL_SYMBOLS, AST_MODFLAG_LOAD_ORDER, AST_MODPRI_CHANNEL_DEPEND, AST_MODULE_INFO(), AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, AST_MODULE_SUPPORT_CORE, ast_sorcery_observer_add(), ast_vm_register, ASTERISK_GPL_KEY, LOG_ERROR, mwi_initial_events(), MWI_MAILBOX_TYPE, mwi_sorcery_init(), and unload_module().
 {
    int res;
    if (mwi_sorcery_init()
       || ast_sorcery_observer_add(mwi_sorcery, MWI_MAILBOX_TYPE, &mwi_observers)
 #if defined(MWI_DEBUG_CLI)
       || ast_cli_register_multiple(mwi_cli, ARRAY_LEN(mwi_cli))
 #endif   /* defined(MWI_DEBUG_CLI) */
       ) {
       unload_module();
       return AST_MODULE_LOAD_DECLINE;
    }
    /* ast_vm_register may return DECLINE if another module registered for vm */
    res = ast_vm_register(&vm_table);
    if (res) {
       ast_log(LOG_ERROR, "Failure registering as a voicemail provider\n");
       unload_module();
       return AST_MODULE_LOAD_DECLINE;
    }
    /* Post initial MWI count events. */
    mwi_initial_events();
    return AST_MODULE_LOAD_SUCCESS;
 }
mwi_folder_map()
static enum folder_map mwi_folder_map (const char * folder) static
Definition at line 341 of file res_mwi_external.c.
References ast_strlen_zero, FOLDER_INBOX, FOLDER_INVALID, and FOLDER_OLD.
Referenced by mwi_has_voicemail(), and mwi_messagecount().
 {
    enum folder_map which_folder;
    if (ast_strlen_zero(folder) || !strcasecmp(folder, "INBOX")) {
       which_folder = FOLDER_INBOX;
    } else if (!strcasecmp(folder, "Old")) {
       which_folder = FOLDER_OLD;
    } else {
       which_folder = FOLDER_INVALID;
    }
    return which_folder;
 }
mwi_has_voicemail()
static int mwi_has_voicemail (const char * mailboxes, const char * folder) static
Definition at line 407 of file res_mwi_external.c.
References ast_mwi_mailbox_get(), ast_mwi_mailbox_unref, ast_strdupa, FOLDER_INBOX, FOLDER_INVALID, FOLDER_OLD, mailbox, ast_mwi_mailbox_object::msgs_new, ast_mwi_mailbox_object::msgs_old, mwi_folder_map(), parse(), and strsep().
 {
    char *parse;
    char *mailbox_id;
    enum folder_map which_folder;
    which_folder = mwi_folder_map(folder);
    if (which_folder == FOLDER_INVALID) {
       return 0;
    }
    /* For each mailbox in the list. */
    parse = ast_strdupa(mailboxes);
    while ((mailbox_id = strsep(&parse, ",&"))) {
       const struct ast_mwi_mailbox_object *mailbox;
       int num_msgs;
       /* Get the specified mailbox. */
       mailbox = ast_mwi_mailbox_get(mailbox_id);
       if (!mailbox) {
          continue;
       }
       /* Done if the found mailbox has any messages. */
       num_msgs = 0;
       switch (which_folder) {
       case FOLDER_INVALID:
          break;
       case FOLDER_INBOX:
          num_msgs = mailbox->msgs_new;
          break;
       case FOLDER_OLD:
          num_msgs = mailbox->msgs_old;
          break;
       }
       ast_mwi_mailbox_unref(mailbox);
       if (num_msgs) {
          return 1;
       }
    }
    return 0;
 }
mwi_inboxcount()
static int mwi_inboxcount (const char * mailboxes, int * newmsgs, int * oldmsgs) static
Definition at line 467 of file res_mwi_external.c.
References ast_mwi_mailbox_get(), ast_mwi_mailbox_unref, ast_strdupa, mailbox, ast_mwi_mailbox_object::msgs_new, ast_mwi_mailbox_object::msgs_old, parse(), and strsep().
Referenced by mwi_inboxcount2().
 {
    char *parse;
    char *mailbox_id;
    if (!newmsgs && !oldmsgs) {
       /* Nowhere to accumulate counts */
       return 0;
    }
    /* For each mailbox in the list. */
    parse = ast_strdupa(mailboxes);
    while ((mailbox_id = strsep(&parse, ", "))) {
       const struct ast_mwi_mailbox_object *mailbox;
       /* Get the specified mailbox. */
       mailbox = ast_mwi_mailbox_get(mailbox_id);
       if (!mailbox) {
          continue;
       }
       /* Accumulate the counts. */
       if (newmsgs) {
          *newmsgs += mailbox->msgs_new;
       }
       if (oldmsgs) {
          *oldmsgs += mailbox->msgs_old;
       }
       ast_mwi_mailbox_unref(mailbox);
    }
    return 0;
 }
mwi_inboxcount2()
static int mwi_inboxcount2 (const char * mailboxes, int * urgentmsgs, int * newmsgs, int * oldmsgs) static
Definition at line 520 of file res_mwi_external.c.
References mwi_inboxcount().
 {
    /*
     * This module does not support urgentmsgs.  Just ignore them.
     * The global API call has already set the count to zero.
     */
    return mwi_inboxcount(mailboxes, newmsgs, oldmsgs);
 }
mwi_initial_events()
static void mwi_initial_events (void) static
Definition at line 888 of file res_mwi_external.c.
References ao2_iterator_destroy(), ao2_iterator_init(), ao2_iterator_next, AO2_ITERATOR_UNLINK, ao2_ref, ast_mwi_mailbox_get_all(), ast_mwi_mailbox_unref, mailbox, mailboxes, and mwi_post_event().
Referenced by load_module().
 {
    struct ao2_container *mailboxes;
    const struct ast_mwi_mailbox_object *mailbox;
    struct ao2_iterator iter;
    /* Get all mailbox counts. */
    mailboxes = ast_mwi_mailbox_get_all();
    if (!mailboxes) {
       return;
    }
    /* Post all mailbox counts. */
    iter = ao2_iterator_init(mailboxes, AO2_ITERATOR_UNLINK);
    for (; (mailbox = ao2_iterator_next(&iter)); ast_mwi_mailbox_unref(mailbox)) {
       mwi_post_event(mailbox);
    }
    ao2_iterator_destroy(&iter);
    ao2_ref(mailboxes, -1);
 }
mwi_mailbox_delete()
static void mwi_mailbox_delete (struct ast_mwi_mailbox_object * mailbox) static
Definition at line 260 of file res_mwi_external.c.
References ast_sorcery_delete().
Referenced by ast_mwi_mailbox_delete(), and mwi_mailbox_delete_all().
 {
    ast_sorcery_delete(mwi_sorcery, mailbox);
 }
mwi_mailbox_delete_all()
static void mwi_mailbox_delete_all (struct ao2_container * mailboxes) static
Definition at line 274 of file res_mwi_external.c.
References ao2_iterator_destroy(), ao2_iterator_init(), ao2_iterator_next, AO2_ITERATOR_UNLINK, ast_mwi_mailbox_unref, mailbox, and mwi_mailbox_delete().
Referenced by ast_mwi_mailbox_delete_all(), and ast_mwi_mailbox_delete_by_regex().
 {
    struct ast_mwi_mailbox_object *mailbox;
    struct ao2_iterator iter;
    iter = ao2_iterator_init(mailboxes, AO2_ITERATOR_UNLINK);
    for (; (mailbox = ao2_iterator_next(&iter)); ast_mwi_mailbox_unref(mailbox)) {
       mwi_mailbox_delete(mailbox);
    }
    ao2_iterator_destroy(&iter);
 }
mwi_messagecount()
static int mwi_messagecount (const char * mailbox_id, const char * folder) static
Definition at line 365 of file res_mwi_external.c.
References ast_mwi_mailbox_get(), ast_mwi_mailbox_unref, FOLDER_INBOX, FOLDER_INVALID, FOLDER_OLD, mailbox, ast_mwi_mailbox_object::msgs_new, ast_mwi_mailbox_object::msgs_old, and mwi_folder_map().
 {
    const struct ast_mwi_mailbox_object *mailbox;
    int num_msgs;
    enum folder_map which_folder;
    which_folder = mwi_folder_map(folder);
    if (which_folder == FOLDER_INVALID) {
       return 0;
    }
    mailbox = ast_mwi_mailbox_get(mailbox_id);
    if (!mailbox) {
       return 0;
    }
    num_msgs = 0;
    switch (which_folder) {
    case FOLDER_INVALID:
       break;
    case FOLDER_INBOX:
       num_msgs = mailbox->msgs_new;
       break;
    case FOLDER_OLD:
       num_msgs = mailbox->msgs_old;
       break;
    }
    ast_mwi_mailbox_unref(mailbox);
    return num_msgs;
 }
mwi_observe_delete()
static void mwi_observe_delete (const void * obj) static
Definition at line 110 of file res_mwi_external.c.
References ast_delete_mwi_state, ast_publish_mwi_state, ast_sorcery_object_get_id(), mailbox, ast_mwi_mailbox_object::msgs_new, ast_mwi_mailbox_object::msgs_old, and NULL.
 {
    const struct ast_mwi_mailbox_object *mailbox = obj;
    if (mailbox->msgs_new || mailbox->msgs_old) {
       /* Post a count clearing event. */
       ast_publish_mwi_state(ast_sorcery_object_get_id(mailbox), NULL, 0, 0);
    }
    /* Post a cache remove event. */
    ast_delete_mwi_state(ast_sorcery_object_get_id(mailbox), NULL);
 }
mwi_observe_update()
static void mwi_observe_update (const void * obj) static
Definition at line 98 of file res_mwi_external.c.
References mwi_post_event().
 {
    mwi_post_event(obj);
 }
mwi_post_event()
static void mwi_post_event (const struct ast_mwi_mailbox_object * mailbox) static
Definition at line 92 of file res_mwi_external.c.
References ast_publish_mwi_state, ast_sorcery_object_get_id(), ast_mwi_mailbox_object::msgs_new, ast_mwi_mailbox_object::msgs_old, and NULL.
Referenced by mwi_initial_events(), and mwi_observe_update().
 {
    ast_publish_mwi_state(ast_sorcery_object_get_id(mailbox), NULL,
       mailbox->msgs_new, mailbox->msgs_old);
 }
mwi_sorcery_init()
static int mwi_sorcery_init (void) static
Definition at line 143 of file res_mwi_external.c.
References ast_log, ast_sorcery_apply_default, AST_SORCERY_APPLY_FAIL, ast_sorcery_object_field_register_nodoc, ast_sorcery_object_register, ast_sorcery_open, FLDSET, LOG_ERROR, ast_mwi_mailbox_object::msgs_new, ast_mwi_mailbox_object::msgs_old, MWI_ASTDB_PREFIX, MWI_MAILBOX_TYPE, mwi_sorcery_object_alloc(), NULL, and OPT_UINT_T.
Referenced by load_module().
 {
    int res;
    mwi_sorcery = ast_sorcery_open();
    if (!mwi_sorcery) {
       ast_log(LOG_ERROR, "MWI external: Sorcery failed to open.\n");
       return -1;
    }
    /* Map the external MWI wizards. */
    if (ast_sorcery_apply_default(mwi_sorcery, MWI_MAILBOX_TYPE, "astdb",
          MWI_ASTDB_PREFIX) == AST_SORCERY_APPLY_FAIL) {
       ast_log(LOG_ERROR, "MWI external: Sorcery could not setup wizards.\n");
       return -1;
    }
    res = ast_sorcery_object_register(mwi_sorcery, MWI_MAILBOX_TYPE,
       mwi_sorcery_object_alloc, NULL, NULL);
    if (res) {
       ast_log(LOG_ERROR, "MWI external: Sorcery could not register object type '%s'.\n",
          MWI_MAILBOX_TYPE);
       return -1;
    }
    /* Define the MWI_MAILBOX_TYPE object fields. */
    res |= ast_sorcery_object_field_register_nodoc(mwi_sorcery, MWI_MAILBOX_TYPE,
       "msgs_new", "0", OPT_UINT_T, 0, FLDSET(struct ast_mwi_mailbox_object, msgs_new));
    res |= ast_sorcery_object_field_register_nodoc(mwi_sorcery, MWI_MAILBOX_TYPE,
       "msgs_old", "0", OPT_UINT_T, 0, FLDSET(struct ast_mwi_mailbox_object, msgs_old));
    return res ? -1 : 0;
 }
mwi_sorcery_object_alloc()
static void* mwi_sorcery_object_alloc (const char * id) static
Internal function to allocate a mwi object.
Definition at line 130 of file res_mwi_external.c.
References ast_sorcery_generic_alloc(), and NULL.
Referenced by mwi_sorcery_init().
 {
    return ast_sorcery_generic_alloc(sizeof(struct ast_mwi_mailbox_object), NULL);
 }
unload_module()
static int unload_module (void) static
Definition at line 910 of file res_mwi_external.c.
References ARRAY_LEN, ast_cli_unregister_multiple(), ast_sorcery_observer_remove(), ast_sorcery_unref, ast_vm_unregister(), ast_vm_functions::module_name, MWI_MAILBOX_TYPE, and NULL.
Referenced by load_module().
 {
    ast_vm_unregister(vm_table.module_name);
 #if defined(MWI_DEBUG_CLI)
    ast_cli_unregister_multiple(mwi_cli, ARRAY_LEN(mwi_cli));
 #endif   /* defined(MWI_DEBUG_CLI) */
    ast_sorcery_observer_remove(mwi_sorcery, MWI_MAILBOX_TYPE, &mwi_observers);
    ast_sorcery_unref(mwi_sorcery);
    mwi_sorcery = NULL;
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_GLOBAL_SYMBOLS | AST_MODFLAG_LOAD_ORDER , .description = "Core external MWI resource" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_CHANNEL_DEPEND - 5, } static
Definition at line 957 of file res_mwi_external.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 957 of file res_mwi_external.c.
mwi_observers
const struct ast_sorcery_observer mwi_observers static
Initial value:
= {
   .created = mwi_observe_update,
   .updated = mwi_observe_update,
   .deleted = mwi_observe_delete,
}
Definition at line 123 of file res_mwi_external.c.
mwi_sorcery
struct ast_sorcery* mwi_sorcery static
Definition at line 83 of file res_mwi_external.c.
vm_table
const struct ast_vm_functions vm_table static
Definition at line 529 of file res_mwi_external.c.