Asterisk - The Open Source Telephony Project: conf_state_single.c File Reference
conf_state_single.c File Reference
Dial plan applications
Confbridge state handling for the SINGLE state.
#include "include/confbridge.h"
#include "include/conf_state.h"
Functions
static void join_marked (struct confbridge_user *user)
static void join_unmarked (struct confbridge_user *user)
static void leave_unmarked (struct confbridge_user *user)
static void transition_to_single (struct confbridge_user *user)
Variables
struct confbridge_state * CONF_STATE_SINGLE = &STATE_SINGLE
Conference state with only a single unmarked active user.
struct confbridge_state STATE_SINGLE
Detailed Description
Confbridge state handling for the SINGLE state.
Author
Terry Wilson <twilson@digium.com>
Definition in file conf_state_single.c.
Function Documentation
join_marked()
static void join_marked (struct confbridge_user * user) static
Definition at line 63 of file conf_state_single.c.
References conf_add_user_marked(), conf_change_state(), conf_handle_second_active(), CONF_STATE_MULTI_MARKED, conf_update_user_mute(), and confbridge_user::conference.
 {
    conf_add_user_marked(user->conference, user);
    conf_handle_second_active(user->conference);
    conf_update_user_mute(user);
    conf_change_state(user, CONF_STATE_MULTI_MARKED);
 }
join_unmarked()
static void join_unmarked (struct confbridge_user * user) static
Definition at line 54 of file conf_state_single.c.
References conf_add_user_active(), conf_change_state(), conf_handle_second_active(), CONF_STATE_MULTI, conf_update_user_mute(), and confbridge_user::conference.
 {
    conf_add_user_active(user->conference, user);
    conf_handle_second_active(user->conference);
    conf_update_user_mute(user);
    conf_change_state(user, CONF_STATE_MULTI);
 }
leave_unmarked()
static void leave_unmarked (struct confbridge_user * user) static
Definition at line 72 of file conf_state_single.c.
References conf_change_state(), conf_moh_stop(), conf_remove_user_active(), CONF_STATE_EMPTY, CONF_STATE_INACTIVE, confbridge_user::conference, confbridge_user::playing_moh, and confbridge_conference::waitingusers.
 {
    conf_remove_user_active(user->conference, user);
    if (user->playing_moh) {
       conf_moh_stop(user);
    }
    if (user->conference->waitingusers) {
       conf_change_state(user, CONF_STATE_INACTIVE);
    } else {
       conf_change_state(user, CONF_STATE_EMPTY);
    }
 }
transition_to_single()
static void transition_to_single (struct confbridge_user * user) static
Definition at line 86 of file conf_state_single.c.
References conf_mute_only_active(), and confbridge_user::conference.
 {
    conf_mute_only_active(user->conference);
 }
Variable Documentation
CONF_STATE_SINGLE
struct confbridge_state* CONF_STATE_SINGLE = &STATE_SINGLE
Conference state with only a single unmarked active user.
Definition at line 52 of file conf_state_single.c.
Referenced by join_unmarked(), leave_marked(), and leave_unmarked().
STATE_SINGLE
struct confbridge_state STATE_SINGLE
Definition at line 43 of file conf_state_single.c.