Asterisk - The Open Source Telephony Project: ast_sip_cli_formatter_entry Struct Reference
ast_sip_cli_formatter_entry Struct Reference
#include <res_pjsip_cli.h>
Data Fields
struct ao2_container *(* get_container)(const char *regex)
const char *(* get_id)(const void *obj)
int(* iterate)(void *container, ao2_callback_fn callback, void *args)
const char * name
ao2_callback_fn * print_body
ao2_callback_fn * print_header
void *(* retrieve_by_id)(const char *id)
Detailed Description
Definition at line 52 of file res_pjsip_cli.h.
Field Documentation
get_container
struct ao2_container*(* get_container) (const char *regex)
The function used to retrieve a container of all objects of this type.
Definition at line 64 of file res_pjsip_cli.h.
Referenced by ast_res_pjsip_initialize_configuration(), ast_sip_initialize_distributor(), ast_sip_initialize_sorcery_auth(), ast_sip_initialize_sorcery_location(), ast_sip_initialize_sorcery_transport(), ast_sip_register_cli_formatter(), load_module(), and pjsip_channel_cli_register().
get_id
const char*(* get_id) (const void *obj)
The function used to retrieve an id string from an object.
Definition at line 70 of file res_pjsip_cli.h.
Referenced by ast_res_pjsip_initialize_configuration(), ast_sip_initialize_distributor(), ast_sip_initialize_sorcery_auth(), ast_sip_initialize_sorcery_location(), ast_sip_initialize_sorcery_transport(), ast_sip_register_cli_formatter(), complete_show_sorcery_object(), load_module(), and pjsip_channel_cli_register().
iterate
int(* iterate) (void *container, ao2_callback_fn callback, void *args)
The function used to iterate over a container of objects.
Definition at line 66 of file res_pjsip_cli.h.
Referenced by ast_res_pjsip_initialize_configuration(), ast_sip_initialize_distributor(), ast_sip_initialize_sorcery_auth(), ast_sip_initialize_sorcery_location(), ast_sip_initialize_sorcery_transport(), ast_sip_register_cli_formatter(), cli_aor_print_body(), load_module(), and pjsip_channel_cli_register().
name
const char* name
A globally unique name for this formatter. If this formatter entry is for an existing sorcery object type, then this name must match the sorcery object type. Otherwise it can be any string as long as it's globally unique.
Definition at line 58 of file res_pjsip_cli.h.
Referenced by ast_res_pjsip_initialize_configuration(), ast_sip_initialize_distributor(), ast_sip_initialize_sorcery_auth(), ast_sip_initialize_sorcery_location(), ast_sip_initialize_sorcery_transport(), ast_sip_register_cli_formatter(), formatter_compare(), formatter_hash(), formatter_sort(), PathSegment::get_child(), Parameter::load(), SwaggerType::load(), Property::load(), load_module(), and pjsip_channel_cli_register().
print_body
ao2_callback_fn* print_body
The callback used to print the details of the object.
Definition at line 62 of file res_pjsip_cli.h.
Referenced by ast_res_pjsip_initialize_configuration(), ast_sip_initialize_distributor(), ast_sip_initialize_sorcery_auth(), ast_sip_initialize_sorcery_location(), ast_sip_initialize_sorcery_transport(), ast_sip_register_cli_formatter(), cli_aor_print_body(), load_module(), and pjsip_channel_cli_register().
print_header
ao2_callback_fn* print_header
The callback used to print the object's column headers.
Definition at line 60 of file res_pjsip_cli.h.
Referenced by ast_res_pjsip_initialize_configuration(), ast_sip_initialize_distributor(), ast_sip_initialize_sorcery_auth(), ast_sip_initialize_sorcery_location(), ast_sip_initialize_sorcery_transport(), ast_sip_register_cli_formatter(), cli_aor_print_header(), load_module(), and pjsip_channel_cli_register().
retrieve_by_id
void*(* retrieve_by_id) (const char *id)
The function used to retrieve a specific object from it's container.
Definition at line 68 of file res_pjsip_cli.h.
Referenced by ast_res_pjsip_initialize_configuration(), ast_sip_initialize_distributor(), ast_sip_initialize_sorcery_auth(), ast_sip_initialize_sorcery_location(), ast_sip_initialize_sorcery_transport(), ast_sip_register_cli_formatter(), load_module(), and pjsip_channel_cli_register().
The documentation for this struct was generated from the following file:
res_pjsip_cli.h