Asterisk - The Open Source Telephony Project: cdr_syslog.c File Reference
cdr_syslog.c File Reference
Module: CDR Drivers
syslog CDR logger
#include "asterisk.h"
#include "asterisk/module.h"
#include "asterisk/lock.h"
#include "asterisk/cdr.h"
#include "asterisk/pbx.h"
#include <syslog.h>
Data Structures
struct cdr_syslog_config
struct sinks
Functions
static void __init_syslog_buf (void)
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static void free_config (void)
static int load_config (int reload)
static enum ast_module_load_result load_module (void)
static int reload (void)
static int syslog_log (struct ast_cdr *cdr)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Customizable syslog CDR Backend" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .reload = reload, .load_pri = AST_MODPRI_CDR_DRIVER, .requires = "cdr", }
static const struct ast_module_info * ast_module_info = &__mod_info
static const char CONFIG [] = "cdr_syslog.conf"
static const char name [] = "cdr-syslog"
static struct sinks sinks = { .first = NULL, .last = NULL, .lock = { PTHREAD_RWLOCK_INITIALIZER , NULL, {1, 0} } , }
static struct ast_threadstorage syslog_buf = { .once = PTHREAD_ONCE_INIT , .key_init = __init_syslog_buf , .custom_init = NULL , }
Detailed Description
syslog CDR logger
Author
Sean Bright sean@.nosp@m.mall.nosp@m.eable.nosp@m..com
See also
Config_cdr
Definition in file cdr_syslog.c.
Function Documentation
__init_syslog_buf()
static void __init_syslog_buf (void) static
Definition at line 58 of file cdr_syslog.c.
 {
__reg_module()
static void __reg_module (void) static
Definition at line 296 of file cdr_syslog.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 296 of file cdr_syslog.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 296 of file cdr_syslog.c.
free_config()
static void free_config (void) static
Definition at line 75 of file cdr_syslog.c.
References ast_free, ast_mutex_destroy, AST_RWLIST_REMOVE_HEAD, ast_string_field_free_memory, cdr_syslog_config::list, and cdr_syslog_config::lock.
Referenced by load_config(), reload(), and unload_module().
 {
    struct cdr_syslog_config *sink;
    while ((sink = AST_RWLIST_REMOVE_HEAD(&sinks, list))) {
       ast_mutex_destroy(&sink->lock);
       ast_string_field_free_memory(sink);
       ast_free(sink);
    }
 }
load_config()
static int load_config (int reload) static
Definition at line 134 of file cdr_syslog.c.
References ast_calloc_with_stringfields, ast_category_browse(), ast_config_destroy(), ast_config_load, ast_log, AST_LOG_ERROR, AST_LOG_WARNING, ast_mutex_init, AST_RWLIST_EMPTY, AST_RWLIST_INSERT_TAIL, ast_string_field_set, ast_strlen_zero, ast_syslog_facility(), ast_syslog_facility_name(), ast_syslog_priority(), ast_syslog_priority_name(), ast_variable_retrieve(), CONFIG, CONFIG_FLAG_FILEUNCHANGED, CONFIG_STATUS_FILEINVALID, CONFIG_STATUS_FILEMISSING, CONFIG_STATUS_FILEUNCHANGED, cdr_syslog_config::facility, cdr_syslog_config::format, free_config(), cdr_syslog_config::ident, cdr_syslog_config::list, cdr_syslog_config::lock, NULL, cdr_syslog_config::priority, and tmp().
Referenced by load_module(), and reload().
 {
    struct ast_config *cfg;
    struct ast_flags config_flags = { reload ? CONFIG_FLAG_FILEUNCHANGED : 0 };
    int default_facility = LOG_LOCAL4;
    int default_priority = LOG_INFO;
    const char *catg = NULL, *tmp;
    cfg = ast_config_load(CONFIG, config_flags);
    if (cfg == CONFIG_STATUS_FILEMISSING || cfg == CONFIG_STATUS_FILEINVALID) {
       ast_log(AST_LOG_ERROR,
          "Unable to load %s. Not logging custom CSV CDRs to syslog.\n", CONFIG);
       return -1;
    } else if (cfg == CONFIG_STATUS_FILEUNCHANGED) {
       return 0;
    }
    if (reload) {
       free_config();
    }
    if (!(ast_strlen_zero(tmp = ast_variable_retrieve(cfg, "general", "facility")))) {
       int facility = ast_syslog_facility(tmp);
       if (facility < 0) {
          ast_log(AST_LOG_WARNING,
             "Invalid facility '%s' specified, defaulting to '%s'\n",
             tmp, ast_syslog_facility_name(default_facility));
       } else {
          default_facility = facility;
       }
    }
    if (!(ast_strlen_zero(tmp = ast_variable_retrieve(cfg, "general", "priority")))) {
       int priority = ast_syslog_priority(tmp);
       if (priority < 0) {
          ast_log(AST_LOG_WARNING,
             "Invalid priority '%s' specified, defaulting to '%s'\n",
             tmp, ast_syslog_priority_name(default_priority));
       } else {
          default_priority = priority;
       }
    }
    while ((catg = ast_category_browse(cfg, catg))) {
       struct cdr_syslog_config *sink;
       if (!strcasecmp(catg, "general")) {
          continue;
       }
       if (ast_strlen_zero(tmp = ast_variable_retrieve(cfg, catg, "template"))) {
          ast_log(AST_LOG_WARNING,
             "No 'template' parameter found for '%s'.  Skipping.\n", catg);
          continue;
       }
       sink = ast_calloc_with_stringfields(1, struct cdr_syslog_config, 1024);
       if (!sink) {
          ast_log(AST_LOG_ERROR,
             "Unable to allocate memory for configuration settings.\n");
          free_config();
          break;
       }
       ast_mutex_init(&sink->lock);
       ast_string_field_set(sink, ident, catg);
       ast_string_field_set(sink, format, tmp);
       if (ast_strlen_zero(tmp = ast_variable_retrieve(cfg, catg, "facility"))) {
          sink->facility = default_facility;
       } else {
          int facility = ast_syslog_facility(tmp);
          if (facility < 0) {
             ast_log(AST_LOG_WARNING,
                "Invalid facility '%s' specified for '%s,' defaulting to '%s'\n",
                tmp, catg, ast_syslog_facility_name(default_facility));
          } else {
             sink->facility = facility;
          }
       }
       if (ast_strlen_zero(tmp = ast_variable_retrieve(cfg, catg, "priority"))) {
          sink->priority = default_priority;
       } else {
          int priority = ast_syslog_priority(tmp);
          if (priority < 0) {
             ast_log(AST_LOG_WARNING,
                "Invalid priority '%s' specified for '%s,' defaulting to '%s'\n",
                tmp, catg, ast_syslog_priority_name(default_priority));
          } else {
             sink->priority = priority;
          }
       }
       AST_RWLIST_INSERT_TAIL(&sinks, sink, list);
    }
    ast_config_destroy(cfg);
    return AST_RWLIST_EMPTY(&sinks) ? -1 : 0;
 }
load_module()
static enum ast_module_load_result load_module (void) static
Definition at line 254 of file cdr_syslog.c.
References ast_cdr_register(), ast_log, AST_LOG_ERROR, AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, AST_RWLIST_UNLOCK, AST_RWLIST_WRLOCK, ast_module_info::description, load_config(), name, and syslog_log().
Referenced by reload().
 {
    int res;
    if (AST_RWLIST_WRLOCK(&sinks)) {
       ast_log(AST_LOG_ERROR, "Unable to lock sink list.  Load failed.\n");
       return AST_MODULE_LOAD_DECLINE;
    }
    res = load_config(0);
    AST_RWLIST_UNLOCK(&sinks);
    if (res) {
       return AST_MODULE_LOAD_DECLINE;
    }
    ast_cdr_register(name, ast_module_info->description, syslog_log);
    return AST_MODULE_LOAD_SUCCESS;
 }
reload()
static int reload (void) static
Definition at line 272 of file cdr_syslog.c.
References ast_log, AST_LOG_ERROR, AST_MODFLAG_LOAD_ORDER, AST_MODPRI_CDR_DRIVER, AST_MODULE_INFO(), AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, AST_MODULE_SUPPORT_CORE, AST_RWLIST_UNLOCK, AST_RWLIST_WRLOCK, ASTERISK_GPL_KEY, free_config(), load_config(), load_module(), and unload_module().
 {
    int res;
    if (AST_RWLIST_WRLOCK(&sinks)) {
       ast_log(AST_LOG_ERROR, "Unable to lock sink list.  Load failed.\n");
       return AST_MODULE_LOAD_DECLINE;
    }
    if ((res = load_config(1))) {
       free_config();
    }
    AST_RWLIST_UNLOCK(&sinks);
    return res ? AST_MODULE_LOAD_DECLINE : AST_MODULE_LOAD_SUCCESS;
 }
syslog_log()
static int syslog_log (struct ast_cdr * cdr) static
Definition at line 86 of file cdr_syslog.c.
References ast_cdr_dup(), ast_channel_cdr_set(), ast_channel_unref, ast_dummy_channel_alloc, AST_LIST_TRAVERSE, ast_log, AST_LOG_ERROR, ast_mutex_lock, ast_mutex_unlock, AST_RWLIST_RDLOCK, AST_RWLIST_UNLOCK, ast_str_buffer(), ast_str_substitute_variables(), ast_str_thread_get(), dummy(), cdr_syslog_config::facility, cdr_syslog_config::format, cdr_syslog_config::ident, cdr_syslog_config::list, cdr_syslog_config::lock, cdr_syslog_config::priority, str, and syslog_buf.
Referenced by load_module(), and unload_module().
 {
    struct ast_channel *dummy;
    struct ast_str *str;
    struct cdr_syslog_config *sink;
    /* Batching saves memory management here.  Otherwise, it's the same as doing an
       allocation and free each time. */
    if (!(str = ast_str_thread_get(&syslog_buf, 16))) {
       return -1;
    }
    if (!(dummy = ast_dummy_channel_alloc())) {
       ast_log(AST_LOG_ERROR, "Unable to allocate channel for variable substitution.\n");
       return -1;
    }
    /* We need to dup here since the cdr actually belongs to the other channel,
       so when we release this channel we don't want the CDR getting cleaned
       up prematurely. */
    ast_channel_cdr_set(dummy, ast_cdr_dup(cdr));
    AST_RWLIST_RDLOCK(&sinks);
    AST_LIST_TRAVERSE(&sinks, sink, list) {
       ast_str_substitute_variables(&str, 0, dummy, sink->format);
       /* Even though we have a lock on the list, we could be being chased by
          another thread and this lock ensures that we won't step on anyone's
          toes.  Once each CDR backend gets it's own thread, this lock can be
          removed. */
       ast_mutex_lock(&sink->lock);
       openlog(sink->ident, LOG_CONS, sink->facility);
       syslog(sink->priority, "%s", ast_str_buffer(str));
       closelog();
       ast_mutex_unlock(&sink->lock);
    }
    AST_RWLIST_UNLOCK(&sinks);
    ast_channel_unref(dummy);
    return 0;
 }
unload_module()
static int unload_module (void) static
Definition at line 237 of file cdr_syslog.c.
References ast_cdr_register(), ast_cdr_unregister(), ast_log, AST_LOG_ERROR, AST_RWLIST_UNLOCK, AST_RWLIST_WRLOCK, ast_module_info::description, free_config(), name, and syslog_log().
Referenced by reload().
 {
    if (ast_cdr_unregister(name)) {
       return -1;
    }
    if (AST_RWLIST_WRLOCK(&sinks)) {
       ast_cdr_register(name, ast_module_info->description, syslog_log);
       ast_log(AST_LOG_ERROR, "Unable to lock sink list.  Unload failed.\n");
       return -1;
    }
    free_config();
    AST_RWLIST_UNLOCK(&sinks);
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Customizable syslog CDR Backend" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .reload = reload, .load_pri = AST_MODPRI_CDR_DRIVER, .requires = "cdr", } static
Definition at line 296 of file cdr_syslog.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 296 of file cdr_syslog.c.
CONFIG
const char CONFIG[] = "cdr_syslog.conf" static
Definition at line 56 of file cdr_syslog.c.
Referenced by load_config().
name
const char name[] = "cdr-syslog" static
Definition at line 60 of file cdr_syslog.c.
Referenced by load_module(), and unload_module().
sinks
struct sinks sinks = { .first = NULL, .last = NULL, .lock = { PTHREAD_RWLOCK_INITIALIZER , NULL, {1, 0} } , } static
syslog_buf
struct ast_threadstorage syslog_buf = { .once = PTHREAD_ONCE_INIT , .key_init = __init_syslog_buf , .custom_init = NULL , } static
Definition at line 58 of file cdr_syslog.c.
Referenced by syslog_log().