Asterisk - The Open Source Telephony Project: func_pjsip_contact.c File Reference
func_pjsip_contact.c File Reference
Module: Dial plan functions
Get information about a PJSIP contact.
#include "asterisk.h"
#include <pjsip.h>
#include <pjlib.h>
#include "asterisk/app.h"
#include "asterisk/pbx.h"
#include "asterisk/module.h"
#include "asterisk/sorcery.h"
#include "asterisk/res_pjsip.h"
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int contact_function_get_permanent (void *obj, void *arg, int flags)
static int load_module (void)
static int pjsip_contact_function_read (struct ast_channel *chan, const char *cmd, char *data, struct ast_str **buf, ssize_t len)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_DEFAULT , .description = "Get information about a PJSIP contact" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .requires = "res_pjsip", }
static const struct ast_module_info * ast_module_info = &__mod_info
static struct ast_custom_function pjsip_contact_function
Detailed Description
Get information about a PJSIP contact.
Author
Joshua Colp <jcolp@digium.com>
Definition in file func_pjsip_contact.c.
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 212 of file func_pjsip_contact.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 212 of file func_pjsip_contact.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 212 of file func_pjsip_contact.c.
contact_function_get_permanent()
static int contact_function_get_permanent (void * obj, void * arg, int flags) static
Definition at line 75 of file func_pjsip_contact.c.
References ast_sorcery_object_get_id(), CMP_MATCH, and CMP_STOP.
Referenced by pjsip_contact_function_read().
 {
    const char *id = arg;
    if (!strcmp(ast_sorcery_object_get_id(obj), id)) {
       return CMP_MATCH | CMP_STOP;
    }
    return 0;
 }
load_module()
static int load_module (void) static
Definition at line 202 of file func_pjsip_contact.c.
References ast_custom_function_register, AST_MODFLAG_DEFAULT, AST_MODULE_INFO(), AST_MODULE_SUPPORT_CORE, ASTERISK_GPL_KEY, and unload_module().
 {
    return ast_custom_function_register(&pjsip_contact_function);
 }
pjsip_contact_function_read()
static int pjsip_contact_function_read (struct ast_channel * chan, const char * cmd, char * data, struct ast_str ** buf, ssize_t len) static
Definition at line 86 of file func_pjsip_contact.c.
References ao2_callback, ao2_cleanup, args, AST_APP_ARG, AST_DECLARE_APP_ARGS, ast_log, AST_LOG_ERROR, AST_LOG_WARNING, ast_sip_get_contact_status(), ast_sip_get_contact_status_label(), ast_sip_get_sorcery(), ast_sorcery_objectset_create, ast_sorcery_retrieve_by_id(), AST_STANDARD_APP_ARGS, ast_str_set(), ast_strdupa, ast_strlen_zero, ast_variables_destroy(), AVAILABLE, contact_function_get_permanent(), ast_variable::name, ast_variable::next, NULL, RAII_VAR, UNKNOWN, and ast_variable::value.
 {
    struct ast_sorcery *pjsip_sorcery;
    char *parsed_data = ast_strdupa(data);
    char *contact_name;
    RAII_VAR(struct ast_sip_contact *, contact_obj, NULL, ao2_cleanup);
    RAII_VAR(struct ast_sip_contact_status *, contact_status, NULL, ao2_cleanup);
    int res = 0;
    AST_DECLARE_APP_ARGS(args,
       AST_APP_ARG(contact_name);
       AST_APP_ARG(field_name);
    );
    /* Check for zero arguments */
    if (ast_strlen_zero(parsed_data)) {
       ast_log(AST_LOG_ERROR, "Cannot call %s without arguments\n", cmd);
       return -1;
    }
    AST_STANDARD_APP_ARGS(args, parsed_data);
    if (ast_strlen_zero(args.contact_name)) {
       ast_log(AST_LOG_ERROR, "Cannot call %s without a contact name to query\n", cmd);
       return -1;
    }
    if (ast_strlen_zero(args.field_name)) {
       ast_log(AST_LOG_ERROR, "Cannot call %s with an empty field name to query\n", cmd);
       return -1;
    }
    pjsip_sorcery = ast_sip_get_sorcery();
    if (!pjsip_sorcery) {
       ast_log(AST_LOG_ERROR, "Unable to retrieve PJSIP configuration: sorcery object is NULL\n");
       return -1;
    }
    /* Determine if this is a permanent contact or a normal contact */
    if ((contact_name = strstr(args.contact_name, "@@"))) {
       size_t aor_name_len = contact_name - args.contact_name;
       char aor_name[aor_name_len + 1];
       RAII_VAR(struct ast_sip_aor *, aor_obj, NULL, ao2_cleanup);
       /* Grab only the AOR name so we can retrieve the AOR which will give us the contact */
       strncpy(aor_name, args.contact_name, aor_name_len);
       aor_name[aor_name_len] = '\0';
       aor_obj = ast_sorcery_retrieve_by_id(pjsip_sorcery, "aor", aor_name);
       if (!aor_obj) {
          ast_log(AST_LOG_WARNING, "Failed to retrieve information for contact '%s'\n", args.contact_name);
          return -1;
       }
       contact_obj = ao2_callback(aor_obj->permanent_contacts, 0, contact_function_get_permanent, args.contact_name);
    } else {
       contact_obj = ast_sorcery_retrieve_by_id(pjsip_sorcery, "contact", args.contact_name);
    }
    if (!contact_obj) {
       ast_log(AST_LOG_WARNING, "Failed to retrieve information for contact '%s'\n", args.contact_name);
       return -1;
    }
    contact_status = ast_sip_get_contact_status(contact_obj);
    if (!strcmp(args.field_name, "status")) {
       ast_str_set(buf, len, "%s", ast_sip_get_contact_status_label(contact_status ? contact_status->status : UNKNOWN));
    } else if (!strcmp(args.field_name, "rtt")) {
       if (!contact_status || contact_status->status != AVAILABLE) {
          ast_str_set(buf, len, "%s", "N/A");
       } else {
          ast_str_set(buf, len, "%" PRId64, contact_status->rtt);
       }
    } else {
       struct ast_variable *change_set;
       struct ast_variable *it_change_set;
       change_set = ast_sorcery_objectset_create(pjsip_sorcery, contact_obj);
       if (!change_set) {
          ast_log(AST_LOG_WARNING, "Failed to retrieve information for contact '%s': change set is NULL\n", args.contact_name);
          return -1;
       }
       for (it_change_set = change_set; it_change_set; it_change_set = it_change_set->next) {
          if (!strcmp(it_change_set->name, args.field_name)) {
             ast_str_set(buf, len, "%s", it_change_set->value);
             break;
          }
       }
       if (!it_change_set) {
          ast_log(AST_LOG_WARNING, "Unknown property '%s' for PJSIP contact\n", args.field_name);
          res = 1;
       }
       ast_variables_destroy(change_set);
    }
    return res;
 }
unload_module()
static int unload_module (void) static
Definition at line 197 of file func_pjsip_contact.c.
References ast_custom_function_unregister().
Referenced by load_module().
 {
    return ast_custom_function_unregister(&pjsip_contact_function);
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_DEFAULT , .description = "Get information about a PJSIP contact" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .requires = "res_pjsip", } static
Definition at line 212 of file func_pjsip_contact.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 212 of file func_pjsip_contact.c.
pjsip_contact_function
struct ast_custom_function pjsip_contact_function static
Initial value:
= {
   .name = "PJSIP_CONTACT",
   .read2 = pjsip_contact_function_read,
}
Definition at line 192 of file func_pjsip_contact.c.