Asterisk - The Open Source Telephony Project: f2clib.c File Reference
f2clib.c File Reference
#include "f2c.h"
#include "math.h"
Functions
integer i_nint (real *x)
integer pow_ii (integer *ap, integer *bp)
double r_sign (real *a, real *b)
Function Documentation
i_nint()
integer i_nint (real * x)
Definition at line 80 of file f2clib.c.
Referenced by placea_(), r_sign(), voicin_(), and vparms_().
 {
 return( (integer)((*x)>=0 ?
    floor(*x + .5) : -floor(.5 - *x)) );
 }
pow_ii()
integer pow_ii (integer * ap, integer * bp)
Definition at line 30 of file f2clib.c.
References a, b, and r_sign().
Referenced by decode_(), and encode_().
 {
    integer pow, x, n;
    unsigned long u;
    x = *ap;
    n = *bp;
    if (n <= 0) {
       if (n == 0 || x == 1)
          return 1;
       if (x != -1)
          return x == 0 ? 0 : 1/x;
       n = -n;
       }
    u = n;
    for(pow = 1; ; )
       {
       if(u & 01)
          pow *= x;
       if(u >>= 1)
          x *= x;
       else
          break;
       }
    return(pow);
    }
r_sign()
double r_sign (real * a, real * b)
Definition at line 64 of file f2clib.c.
References a, and i_nint().
Referenced by onset_(), pow_ii(), and vparms_().
 {
 double x;
 x = (*a >= 0 ? *a : - *a);
 return( *b >= 0 ? x : -x);
 }