Asterisk - The Open Source Telephony Project: sip_to_pjsip Namespace Reference
sip_to_pjsip Namespace Reference
Data Structures
class Registration
Functions
def build_host (config, host, section='general', port_key=None)
def cli_options ()
def convert (sip, filename, non_mappings, include)
def create_tcp (sip, pjsip, nmapped)
def create_tls (sip, pjsip, nmapped)
def create_udp (sip, pjsip, nmapped)
def find_non_mapped (sections, nmapped)
def from_dtlsenable (key, val, section, pjsip, nmapped)
def from_encryption_taglen (key, val, section, pjsip, nmapped)
def from_host (key, val, section, pjsip, nmapped)
def from_mailbox (key, val, section, pjsip, nmapped)
def from_nat (key, val, section, pjsip, nmapped)
def from_progressinband (key, val, section, pjsip, nmapped)
def from_recordfeature (key, val, section, pjsip, nmapped)
def from_sendrpid (key, val, section, pjsip, nmapped)
def get_bind (sip, pjsip, protocol)
def ignore (key=None, val=None, section=None, pjsip=None, nmapped=None, type='endpoint')
def info (msg)
def map_auth (sip, pjsip, nmapped)
def map_peer (sip, section, pjsip, nmapped)
def map_registrations (sip, pjsip, nmapped)
def map_setvars (sip, section, pjsip, nmapped)
def map_system (sip, pjsip, nmapped)
def map_transports (sip, pjsip, nmapped)
def merge_codec_value (key=None, val=None, section=None, pjsip=None, nmapped=None, type='endpoint', section_to=None, key_to=None)
def merge_value (key=None, val=None, section=None, pjsip=None, nmapped=None, type='endpoint', section_to=None, key_to=None)
def non_mapped (nmapped)
def section_by_type (section, pjsip, type)
some utility functions
def set_direct_media (key, val, section, pjsip, nmapped)
def set_dtmfmode (key, val, section, pjsip, nmapped)
mapping functions - define f(key, val, section) where key/val are the key/value pair to write to given section in pjsip.conf
def set_media_encryption (key, val, section, pjsip, nmapped)
def set_record_off_feature (key, val, section, pjsip, nmapped)
def set_record_on_feature (key, val, section, pjsip, nmapped)
def set_timers (key, val, section, pjsip, nmapped)
def set_tls_cafile (val, pjsip, section, nmapped)
def set_tls_capath (val, pjsip, section, nmapped)
def set_tls_cert_file (val, pjsip, section, nmapped)
def set_tls_cipher (val, pjsip, section, nmapped)
def set_tls_private_key (val, pjsip, section, nmapped)
def set_tls_verifyclient (val, pjsip, section, nmapped)
def set_tls_verifyserver (val, pjsip, section, nmapped)
def set_transport_common (section, sip, pjsip, protocol, nmapped)
def set_value (key=None, val=None, section=None, pjsip=None, nmapped=None, type='endpoint')
def setup_auth (key, val, section, pjsip, nmapped)
def setup_ident (key, val, section, pjsip, nmapped)
def setup_udptl (section, pjsip, nmapped)
def split_hostport (addr)
def write_pjsip (filename, pjsip, non_mappings)
Variables
non_mappings
list peer_map
pjsip
pjsip_filename
string PREFIX = 'pjsip_'
bool QUIET = False
sip = astconfigparser.MultiOrderedConfigParser()
sip_filename
Function Documentation
build_host()
def sip_to_pjsip.build_host (config, host, section = 'general', port_key = None)
Returns a string composed of a host:port. This assumes that the host
may have a port as part of the initial value. The port_key overrides
a port in host, see parameter 'bindport' in chan_sip.
Definition at line 289 of file sip_to_pjsip.py.
Referenced by from_host(), and get_bind().
 def build_host(config, host, section='general', port_key=None):
     """
     Returns a string composed of a host:port. This assumes that the host
     may have a port as part of the initial value. The port_key overrides
     a port in host, see parameter 'bindport' in chan_sip.
     """
     try:
         socket.inet_pton(socket.AF_INET6, host)
         if not host.startswith('['):
             # SIP URI will need brackets.
             host = '[' + host + ']'
     except socket.error:
         pass
     # Literal IPv6 (like [::]), IPv4, or hostname
     # does not work for IPv6 without brackets; case catched above
     url = urlparse('sip://' + host)
     if port_key:
         try:
             port = config.get(section, port_key)[0]
             host = url.hostname # no port, but perhaps no brackets
             try:
                 socket.inet_pton(socket.AF_INET6, host)
                 if not host.startswith('['):
                     # SIP URI will need brackets.
                     host = '[' + host + ']'
             except socket.error:
                 pass
             return host + ':' + port
         except LookupError:
             pass
     # Returns host:port, in brackets if required
     # TODO Does not compress IPv6, for example 0:0:0:0:0:0:0:0 should get [::]
     return url.netloc
cli_options()
def sip_to_pjsip.cli_options ()
Parse command line options and apply them. If invalid input is given,
print usage information
Definition at line 1285 of file sip_to_pjsip.py.
References len().
 def cli_options():
     """
     Parse command line options and apply them. If invalid input is given,
     print usage information
     """
     global PREFIX
     global QUIET
     usage = "usage: %prog [options] [input-file [output-file]]\n\n" \
         "Converts the chan_sip configuration input-file to the chan_pjsip output-file.\n" \
         "The input-file defaults to 'sip.conf'.\n" \
         "The output-file defaults to 'pjsip.conf'."
     parser = optparse.OptionParser(usage=usage)
     parser.add_option('-p', '--prefix', dest='prefix', default=PREFIX,
                       help='output prefix for include files')
     parser.add_option('-q', '--quiet', dest='quiet', default=False, action='store_true',
                       help="don't print messages to stdout")
     options, args = parser.parse_args()
     PREFIX = options.prefix
     if options.quiet:
         QUIET = True
     sip_filename = args[0] if len(args) else 'sip.conf'
     pjsip_filename = args[1] if len(args) == 2 else 'pjsip.conf'
     return sip_filename, pjsip_filename
convert()
def sip_to_pjsip.convert (sip, filename, non_mappings, include)
Entry point for configuration file conversion. This
function will create a pjsip.conf object and begin to
map specific sections from sip.conf into it.
Returns the new pjsip.conf object once completed
Definition at line 1229 of file sip_to_pjsip.py.
References find_non_mapped(), map_auth(), map_peer(), map_registrations(), map_setvars(), map_system(), map_transports(), and non_mapped().
 def convert(sip, filename, non_mappings, include):
     """
     Entry point for configuration file conversion. This
     function will create a pjsip.conf object and begin to
     map specific sections from sip.conf into it.
     Returns the new pjsip.conf object once completed
     """
     pjsip = sip.__class__()
     non_mappings[filename] = astdicts.MultiOrderedDict()
     nmapped = non_mapped(non_mappings[filename])
     if not include:
         # Don't duplicate transport and registration configs
         map_system(sip, pjsip, nmapped)
         map_transports(sip, pjsip, nmapped)
         map_registrations(sip, pjsip, nmapped)
     map_auth(sip, pjsip, nmapped)
     for section in sip.sections():
         if section == 'authentication':
             pass
         else:
             map_peer(sip, section, pjsip, nmapped)
             map_setvars(sip, section, pjsip, nmapped)
     find_non_mapped(sip.defaults(), nmapped)
     find_non_mapped(sip.sections(), nmapped)
     for key, val in sip.includes().iteritems():
         pjsip.add_include(PREFIX + key, convert(val, PREFIX + key,
                           non_mappings, True)[0])
     return pjsip, non_mappings
create_tcp()
def sip_to_pjsip.create_tcp (sip, pjsip, nmapped)
Creates a 'transport-tcp' section in the pjsip.conf file based
on the following settings from sip.conf:
tcpenable
tcpbindaddr (or bindaddr)
Definition at line 745 of file sip_to_pjsip.py.
References get_bind(), set_transport_common(), and set_value().
Referenced by map_transports().
 def create_tcp(sip, pjsip, nmapped):
     """
     Creates a 'transport-tcp' section in the pjsip.conf file based
     on the following settings from sip.conf:
     tcpenable
     tcpbindaddr (or bindaddr)
     """
     protocol = 'tcp'
     bind, section = get_bind(sip, pjsip, protocol)
     if not bind:
         return
     set_value('protocol', protocol, section, pjsip, nmapped, 'transport')
     set_value('bind', bind, section, pjsip, nmapped, 'transport')
     set_transport_common(section, sip, pjsip, protocol, nmapped)
create_tls()
def sip_to_pjsip.create_tls (sip, pjsip, nmapped)
Creates a 'transport-tls' section in pjsip.conf based on the following
settings from sip.conf:
tlsenable (or sslenable)
tlsbindaddr (or sslbindaddr or bindaddr)
tlsprivatekey (or sslprivatekey)
tlscipher (or sslcipher)
tlscafile
tlscapath (or tlscadir)
tlscertfile (or sslcert or tlscert)
tlsverifyclient
tlsdontverifyserver
tlsclientmethod (or sslclientmethod)
Definition at line 814 of file sip_to_pjsip.py.
References get_bind(), set_transport_common(), and set_value().
Referenced by map_transports().
 def create_tls(sip, pjsip, nmapped):
     """
     Creates a 'transport-tls' section in pjsip.conf based on the following
     settings from sip.conf:
     tlsenable (or sslenable)
     tlsbindaddr (or sslbindaddr or bindaddr)
     tlsprivatekey (or sslprivatekey)
     tlscipher (or sslcipher)
     tlscafile
     tlscapath (or tlscadir)
     tlscertfile (or sslcert or tlscert)
     tlsverifyclient
     tlsdontverifyserver
     tlsclientmethod (or sslclientmethod)
     """
     protocol = 'tls'
     bind, section = get_bind(sip, pjsip, protocol)
     if not bind:
         return
     set_value('protocol', protocol, section, pjsip, nmapped, 'transport')
     set_value('bind', bind, section, pjsip, nmapped, 'transport')
     set_transport_common(section, sip, pjsip, protocol, nmapped)
     tls_map = [
         (['tlscertfile', 'sslcert', 'tlscert'], set_tls_cert_file),
         (['tlsprivatekey', 'sslprivatekey'], set_tls_private_key),
         (['tlscipher', 'sslcipher'], set_tls_cipher),
         (['tlscafile'], set_tls_cafile),
         (['tlscapath', 'tlscadir'], set_tls_capath),
         (['tlsverifyclient'], set_tls_verifyclient),
         (['tlsdontverifyserver'], set_tls_verifyserver)
     ]
     for i in tls_map:
         try:
             i[1](sip.multi_get('general', i[0])[0], pjsip, section, nmapped)
         except LookupError:
             pass
     try:
         method = sip.multi_get('general', ['tlsclientmethod',
                                            'sslclientmethod'])[0]
         if section != 'transport-' + protocol + '6':  # print only once
             print('In chan_sip, you specified the TLS version. With chan_sip,' \
                   ' this was just for outbound client connections. In' \
                   ' chan_pjsip, this value is for client and server. Instead,' \
                   ' consider not to specify \'tlsclientmethod\' for chan_sip' \
                   ' and \'method = sslv23\' for chan_pjsip.', file=sys.stderr)
     except LookupError:
         """
         OpenSSL emerged during the 90s. SSLv2 and SSLv3 were the only
         existing methods at that time. The OpenSSL project continued. And as
         of today (OpenSSL 1.0.2) this does not start SSLv2 and SSLv3 anymore
         but TLSv1.0 and v1.2. Or stated differently: This method should
         have been called 'method = secure' or 'method = automatic' back in
         the 90s. The PJProject did not realize this and uses 'tlsv1' as
         default when unspecified, which disables TLSv1.2. chan_sip used
         'sslv23' as default when unspecified, which gives TLSv1.0 and v1.2.
         """
         method = 'sslv23'
     set_value('method', method, section, pjsip, nmapped, 'transport')
create_udp()
def sip_to_pjsip.create_udp (sip, pjsip, nmapped)
Creates a 'transport-udp' section in the pjsip.conf file based
on the following settings from sip.conf:
bindaddr (or udpbindaddr)
bindport
Definition at line 729 of file sip_to_pjsip.py.
References get_bind(), set_transport_common(), and set_value().
Referenced by map_transports().
 def create_udp(sip, pjsip, nmapped):
     """
     Creates a 'transport-udp' section in the pjsip.conf file based
     on the following settings from sip.conf:
     bindaddr (or udpbindaddr)
     bindport
     """
     protocol = 'udp'
     bind, section = get_bind(sip, pjsip, protocol)
     set_value('protocol', protocol, section, pjsip, nmapped, 'transport')
     set_value('bind', bind, section, pjsip, nmapped, 'transport')
     set_transport_common(section, sip, pjsip, protocol, nmapped)
find_non_mapped()
def sip_to_pjsip.find_non_mapped (sections, nmapped)
Determine sip.conf options that were not properly mapped to pjsip.conf
options.
Definition at line 1165 of file sip_to_pjsip.py.
Referenced by convert().
 def find_non_mapped(sections, nmapped):
     """
     Determine sip.conf options that were not properly mapped to pjsip.conf
     options.
     """
     for section, sect in sections.iteritems():
         try:
             # since we are pulling from sip.conf this should always
             # be a single value list
             sect = sect[0]
             # loop through the section and store any values that were not
             # mapped
             for key in sect.keys(True):
                 for i in peer_map:
                     if i[0] == key:
                         break
                 else:
                     nmapped(section, key, sect[key])
         except LookupError:
             pass
from_dtlsenable()
def sip_to_pjsip.from_dtlsenable (key, val, section, pjsip, nmapped)
Optionally sets media_encryption=dtls based on sip.conf dtlsenable
Definition at line 441 of file sip_to_pjsip.py.
References set_value().
 def from_dtlsenable(key, val, section, pjsip, nmapped):
     """Optionally sets media_encryption=dtls based on sip.conf dtlsenable"""
     if val == 'yes':
         set_value('media_encryption', 'dtls', section, pjsip, nmapped)
from_encryption_taglen()
def sip_to_pjsip.from_encryption_taglen (key, val, section, pjsip, nmapped)
Sets the srtp_tag32 option based on sip.conf encryption_taglen
Definition at line 435 of file sip_to_pjsip.py.
References set_value().
 def from_encryption_taglen(key, val, section, pjsip, nmapped):
     """Sets the srtp_tag32 option based on sip.conf encryption_taglen"""
     if val == '32':
         set_value('srtp_tag_32', 'yes', section, pjsip, nmapped)
from_host()
def sip_to_pjsip.from_host (key, val, section, pjsip, nmapped)
Sets contact info in an AOR section in pjsip.conf using 'host'
and 'port' data from sip.conf
Definition at line 327 of file sip_to_pjsip.py.
References build_host(), and set_value().
 def from_host(key, val, section, pjsip, nmapped):
     """
     Sets contact info in an AOR section in pjsip.conf using 'host'
     and 'port' data from sip.conf
     """
     # all aors have the same name as the endpoint so makes
     # it easy to set endpoint's 'aors' value
     set_value('aors', section, section, pjsip, nmapped)
     if val == 'dynamic':
         # Easy case. Just set the max_contacts on the aor and we're done
         set_value('max_contacts', 1, section, pjsip, nmapped, 'aor')
         return
     result = 'sip:'
     # More difficult case. The host will be either a hostname or
     # IP address and may or may not have a port specified. pjsip.conf
     # expects the contact to be a SIP URI.
     user = None
     try:
         user = sip.multi_get(section, ['defaultuser', 'username'])[0]
         result += user + '@'
     except LookupError:
         # It's fine if there's no user name
         pass
     result += build_host(sip, val, section, 'port')
     set_value('contact', result, section, pjsip, nmapped, 'aor')
from_mailbox()
def sip_to_pjsip.from_mailbox (key, val, section, pjsip, nmapped)
Determines whether a mailbox configured in sip.conf should map to
an endpoint or aor in pjsip.conf. If subscribemwi is true, then the
mailboxes are set on an aor. Otherwise the mailboxes are set on the
endpoint.
Examples:
/usr/src/asterisk-18.5.0/main/app.c.
Definition at line 360 of file sip_to_pjsip.py.
References set_value().
 def from_mailbox(key, val, section, pjsip, nmapped):
     """
     Determines whether a mailbox configured in sip.conf should map to
     an endpoint or aor in pjsip.conf. If subscribemwi is true, then the
     mailboxes are set on an aor. Otherwise the mailboxes are set on the
     endpoint.
     """
     try:
         subscribemwi = sip.get(section, 'subscribemwi')[0]
     except LookupError:
         # No subscribemwi option means default it to 'no'
         subscribemwi = 'no'
     set_value('mailboxes', val, section, pjsip, nmapped, 'aor'
               if subscribemwi == 'yes' else 'endpoint')
from_nat()
def sip_to_pjsip.from_nat (key, val, section, pjsip, nmapped)
Sets values from nat into the appropriate pjsip.conf options.
Definition at line 191 of file sip_to_pjsip.py.
References set_value().
 def from_nat(key, val, section, pjsip, nmapped):
     """Sets values from nat into the appropriate pjsip.conf options."""
     # nat from sip.conf can be comma separated list of values:
     # yes/no, [auto_]force_rport, [auto_]comedia
     if 'yes' in val:
         set_value('rtp_symmetric', 'yes', section, pjsip, nmapped)
         set_value('rewrite_contact', 'yes', section, pjsip, nmapped)
     if 'comedia' in val:
         set_value('rtp_symmetric', 'yes', section, pjsip, nmapped)
     if 'force_rport' in val:
         set_value('force_rport', 'yes', section, pjsip, nmapped)
         set_value('rewrite_contact', 'yes', section, pjsip, nmapped)
from_progressinband()
def sip_to_pjsip.from_progressinband (key, val, section, pjsip, nmapped)
Sets the inband_progress value in pjsip.conf
Definition at line 281 of file sip_to_pjsip.py.
References set_value().
 def from_progressinband(key, val, section, pjsip, nmapped):
     """Sets the inband_progress value in pjsip.conf"""
     # progressinband can = yes/no/never
     if val == 'never':
         val = 'no'
     set_value('inband_progress', val, section, pjsip, nmapped)
from_recordfeature()
def sip_to_pjsip.from_recordfeature (key, val, section, pjsip, nmapped)
If record on/off feature is set to automixmon then set
one_touch_recording, otherwise it can't be mapped.
Definition at line 265 of file sip_to_pjsip.py.
References set_value().
Referenced by set_record_off_feature(), and set_record_on_feature().
 def from_recordfeature(key, val, section, pjsip, nmapped):
     """
     If record on/off feature is set to automixmon then set
     one_touch_recording, otherwise it can't be mapped.
     """
     set_value('one_touch_recording', 'yes', section, pjsip, nmapped)
     set_value(key, val, section, pjsip, nmapped)
from_sendrpid()
def sip_to_pjsip.from_sendrpid (key, val, section, pjsip, nmapped)
Sets the send_rpid/pai values in pjsip.conf.
Definition at line 243 of file sip_to_pjsip.py.
References set_value().
 def from_sendrpid(key, val, section, pjsip, nmapped):
     """Sets the send_rpid/pai values in pjsip.conf."""
     if val == 'yes' or val == 'rpid':
         set_value('send_rpid', 'yes', section, pjsip, nmapped)
     elif val == 'pai':
         set_value('send_pai', 'yes', section, pjsip, nmapped)
get_bind()
def sip_to_pjsip.get_bind (sip, pjsip, protocol)
Given the protocol (udp, tcp, or tls), return
- the bind address, like [::] or 0.0.0.0
- name of the section to be created
Definition at line 664 of file sip_to_pjsip.py.
References build_host(), split_hostport(), and str.
Referenced by create_tcp(), create_tls(), and create_udp().
 def get_bind(sip, pjsip, protocol):
     """
     Given the protocol (udp, tcp, or tls), return
     - the bind address, like [::] or 0.0.0.0
     - name of the section to be created
     """
     section = 'transport-' + protocol
     # UDP cannot be disabled in chan_sip
     if protocol != 'udp':
         try:
             enabled = sip.get('general', protocol + 'enable')[0]
         except LookupError:
             # No value means disabled by default. Don't create this transport
             return (None, section)
         if enabled != 'yes':
             return (None, section)
     try:
         bind = pjsip.get(section, 'bind')[0]
         # The first run created an transport already but this
         # server was not configured for IPv4/IPv6 Dual Stack
         return (None, section)
     except LookupError:
         pass
     try:
         bind = pjsip.get(section + '6', 'bind')[0]
         # The first run created an IPv6 transport, because
         # the server was configured with :: as bindaddr.
         # Now, re-use its port and create the IPv4 transport
         host, port = split_hostport(bind)
         bind = '0.0.0.0'
         if port:
             bind += ':' + str(port)
     except LookupError:
         # This is the first run, no transport in pjsip exists.
         try:
             bind = sip.get('general', protocol + 'bindaddr')[0]
         except LookupError:
             if protocol == 'udp':
                 try:
                     bind = sip.get('general', 'bindaddr')[0]
                 except LookupError:
                     bind = '0.0.0.0'
             else:
                 try:
                     bind = pjsip.get('transport-udp6', 'bind')[0]
                 except LookupError:
                     bind = pjsip.get('transport-udp', 'bind')[0]
                 # Only TCP reuses host:port of UDP, others reuse just host
                 if protocol == 'tls':
                     bind, port = split_hostport(bind)
         host, port = split_hostport(bind)
         if host == '::':
             section += '6'
     if protocol == 'udp':
         host = build_host(sip, bind, 'general', 'bindport')
     else:
         host = build_host(sip, bind)
     return (host, section)
ignore()
def sip_to_pjsip.ignore (key = None, val = None, section = None, pjsip = None, nmapped = None, type = 'endpoint')
Ignore a key and mark it as mapped
Definition at line 48 of file sip_to_pjsip.py.
Referenced by acl_handler(), endpoint_acl_handler(), find_unused_payload(), and section_by_type().
            nmapped=None, type='endpoint'):
     """Ignore a key and mark it as mapped"""
info()
def sip_to_pjsip.info (msg)
Definition at line 1313 of file sip_to_pjsip.py.
Referenced by __ast_datastore_alloc(), _jb_get(), acf_version_exec(), add_media_cb(), alloc_variant(), ami_outbound_registration_task(), ast_build_timing(), ast_datastores_alloc_datastore(), ast_localtime_wakeup_monitor(), ast_media_get_variants(), ast_module_register(), ast_res_pjsip_initialize_configuration(), ast_rtp_ice_turn_request(), ast_sip_publish_client_alloc_datastore(), ast_sip_session_alloc_datastore(), AST_TEST_DEFINE(), asyncgoto_exec(), build_ami_notify(), build_cli_notify(), capture_info_dtor(), cdr_object_update_party_b_userfield_cb(), cdr_read_callback(), chanavail_exec(), complete_config_option(), complete_config_type(), conf_exec(), dbm_open(), device_state_info_dt(), dumpchan_exec(), find_variant(), get_device_state_causing_channels(), get_name_from_resource(), handle_cli_agi_show(), handle_client_registration(), handle_client_state_destruction(), handle_registration_response(), handle_show_function(), hcreate(), hepv3_create_capture_info(), keypad_cfg_read(), media_info_alloc(), media_info_destroy(), notify_ami_channel_data_create(), notify_ami_channel_data_destroy(), notify_ami_data_create(), notify_ami_data_destroy(), notify_ami_uri_data_create(), notify_ami_uri_data_destroy(), notify_cli_data_create(), notify_cli_uri_data_create(), notify_cli_uri_data_destroy(), refresh_list(), reregister_immediately_cb(), res_sdp_crypto_parse_offer(), schedule_registration(), and unregister_task().
 def info(msg):
     if QUIET:
         return
     print(msg)
map_auth()
def sip_to_pjsip.map_auth (sip, pjsip, nmapped)
Creates auth sections based on entries in the authentication section of
sip.conf. pjsip.conf section names consist of "auth_" followed by the name
of the realm.
Definition at line 912 of file sip_to_pjsip.py.
References set_value().
Referenced by convert().
 def map_auth(sip, pjsip, nmapped):
     """
     Creates auth sections based on entries in the authentication section of
     sip.conf. pjsip.conf section names consist of "auth_" followed by the name
     of the realm.
     """
     try:
         auths = sip.get('authentication', 'auth')
     except LookupError:
         return
     for i in auths:
         creds, at, realm = i.partition('@')
         if not at and not realm:
             # Invalid. Move on
             continue
         user, colon, secret = creds.partition(':')
         if not secret:
             user, sharp, md5 = creds.partition('#')
             if not md5:
                 #Invalid. move on
                 continue
         section = "auth_" + realm
         set_value('realm', realm, section, pjsip, nmapped, 'auth')
         set_value('username', user, section, pjsip, nmapped, 'auth')
         if secret:
             set_value('password', secret, section, pjsip, nmapped, 'auth')
         else:
             set_value('md5_cred', md5, section, pjsip, nmapped, 'auth')
             set_value('auth_type', 'md5', section, pjsip, nmapped, 'auth')
map_peer()
def sip_to_pjsip.map_peer (sip, section, pjsip, nmapped)
Map the options from a peer section in sip.conf into the appropriate
sections in pjsip.conf
Definition at line 1149 of file sip_to_pjsip.py.
References setup_udptl().
Referenced by convert().
 def map_peer(sip, section, pjsip, nmapped):
     """
     Map the options from a peer section in sip.conf into the appropriate
     sections in pjsip.conf
     """
     for i in peer_map:
         try:
             # coming from sip.conf the values should mostly be a list with a
             # single value.  In the few cases that they are not a specialized
             # function (see merge_value) is used to retrieve the values.
             i[1](i[0], sip.get(section, i[0])[0], section, pjsip, nmapped)
         except LookupError:
             pass  # key not found in sip.conf
     setup_udptl(section, pjsip, nmapped)
map_registrations()
def sip_to_pjsip.map_registrations (sip, pjsip, nmapped)
Gathers all necessary outbound registration data in sip.conf and creates
corresponding registration sections in pjsip.conf
Definition at line 1106 of file sip_to_pjsip.py.
Referenced by convert().
 def map_registrations(sip, pjsip, nmapped):
     """
     Gathers all necessary outbound registration data in sip.conf and creates
     corresponding registration sections in pjsip.conf
     """
     try:
         regs = sip.get('general', 'register')
     except LookupError:
         return
     try:
         retry_interval = sip.get('general', 'registertimeout')[0]
     except LookupError:
         retry_interval = '20'
     try:
         max_attempts = sip.get('general', 'registerattempts')[0]
     except LookupError:
         max_attempts = '10'
     try:
         outbound_proxy = sip.get('general', 'outboundproxy')[0]
     except LookupError:
         outbound_proxy = ''
     for i in regs:
         reg = Registration(i, retry_interval, max_attempts, outbound_proxy)
         reg.write(pjsip, nmapped)
map_setvars()
def sip_to_pjsip.map_setvars (sip, section, pjsip, nmapped)
Map all setvar in peer section to the appropriate endpoint set_var
Definition at line 1136 of file sip_to_pjsip.py.
References set_value().
Referenced by convert().
 def map_setvars(sip, section, pjsip, nmapped):
     """
     Map all setvar in peer section to the appropriate endpoint set_var
     """
     try:
         setvars = sip.section(section)[0].get('setvar')
     except LookupError:
         return
     for setvar in setvars:
         set_value('set_var', setvar, section, pjsip, nmapped)
map_system()
def sip_to_pjsip.map_system (sip, pjsip, nmapped)
Definition at line 1187 of file sip_to_pjsip.py.
References set_value().
Referenced by convert().
 def map_system(sip, pjsip, nmapped):
     section = 'system' # Just a label; you as user can change that
     type = 'system' # Not a label, therefore not the same as section
     try:
         user_agent = sip.get('general', 'useragent')[0]
         set_value('user_agent', user_agent, 'global', pjsip, nmapped, 'global')
     except LookupError:
         pass
     try:
         sipdebug = sip.get('general', 'sipdebug')[0]
         set_value('debug', sipdebug, 'global', pjsip, nmapped, 'global')
     except LookupError:
         pass
     try:
         useroption_parsing = sip.get('general', 'legacy_useroption_parsing')[0]
         set_value('ignore_uri_user_options', useroption_parsing, 'global', pjsip, nmapped, 'global')
     except LookupError:
         pass
     try:
         timer_t1 = sip.get('general', 'timert1')[0]
         set_value('timer_t1', timer_t1, section, pjsip, nmapped, type)
     except LookupError:
         pass
     try:
         timer_b = sip.get('general', 'timerb')[0]
         set_value('timer_b', timer_b, section, pjsip, nmapped, type)
     except LookupError:
         pass
     try:
         compact_headers = sip.get('general', 'compactheaders')[0]
         set_value('compact_headers', compact_headers, section, pjsip, nmapped, type)
     except LookupError:
         pass
map_transports()
def sip_to_pjsip.map_transports (sip, pjsip, nmapped)
Finds options in sip.conf general section pertaining to
transport configuration and creates appropriate transport
configuration sections in pjsip.conf.
sip.conf only allows a single UDP transport, TCP transport,
and TLS transport for each IP version. As such, the mapping
into PJSIP can be made consistent by defining six sections:
transport-udp6
transport-udp
transport-tcp6
transport-tcp
transport-tls6
transport-tls
To accommodate the default behaviors in sip.conf, we'll need to
create the UDP transports first, followed by the TCP and TLS transports.
Definition at line 879 of file sip_to_pjsip.py.
References create_tcp(), create_tls(), and create_udp().
Referenced by convert().
 def map_transports(sip, pjsip, nmapped):
     """
     Finds options in sip.conf general section pertaining to
     transport configuration and creates appropriate transport
     configuration sections in pjsip.conf.
     sip.conf only allows a single UDP transport, TCP transport,
     and TLS transport for each IP version. As such, the mapping
     into PJSIP can be made consistent by defining six sections:
     transport-udp6
     transport-udp
     transport-tcp6
     transport-tcp
     transport-tls6
     transport-tls
     To accommodate the default behaviors in sip.conf, we'll need to
     create the UDP transports first, followed by the TCP and TLS transports.
     """
     # First create a UDP transport. Even if no bind parameters were provided
     # in sip.conf, chan_sip would always bind to UDP 0.0.0.0:5060
     create_udp(sip, pjsip, nmapped)
     create_udp(sip, pjsip, nmapped)
     # TCP settings may be dependent on UDP settings, so do it second.
     create_tcp(sip, pjsip, nmapped)
     create_tcp(sip, pjsip, nmapped)
     create_tls(sip, pjsip, nmapped)
     create_tls(sip, pjsip, nmapped)
merge_codec_value()
def sip_to_pjsip.merge_codec_value (key = None, val = None, section = None, pjsip = None, nmapped = None, type = 'endpoint', section_to = None, key_to = None)
Merge values from allow/deny with those from the default. Special treatment for all
Definition at line 93 of file sip_to_pjsip.py.
References merge_value(), and set_value().
Referenced by merge_value().
                 key_to=None):
     """Merge values from allow/deny with those from the default. Special treatment for all"""
     def _merge_codec_value(k, v, s, r, n):
         merge_codec_value(key if key else k, v, s, r, n, type, section_to, key_to)
     # if no value or section return the merge_codec_value
     # function with the enclosed key and type
     if not val and not section:
         return _merge_codec_value
     if key == 'allow':
         try:
             disallow = sip.get(section, 'disallow')[0]
             if disallow == 'all':
                 #don't inherit
                 for i in sip.get(section, 'allow'):
                     set_value(key, i, section, pjsip, nmapped, type)
             else:
                 merge_value(key, val, section, pjsip, nmapped, type, section_to, key_to)
         except LookupError:
             print("lookup error", file=sys.stderr)
             merge_value(key, val, section, pjsip, nmapped, type, section_to, key_to)
             return
     elif key == 'disallow':
         try:
             allow = sip.get(section, 'allow')[0]
             if allow == 'all':
                 #don't inherit
                 for i in sip.get(section, 'disallow'):
                     set_value(key, i, section, pjsip, nmapped, type)
             else:
                 merge_value(key, val, section, pjsip, nmapped, type, section_to, key_to)
         except LookupError:
             merge_value(key, val, section, pjsip, nmapped, type, section_to, key_to)
             return
     else:
         merge_value(key, val, section, pjsip, nmapped, type, section_to, key_to)
merge_value()
def sip_to_pjsip.merge_value (key = None, val = None, section = None, pjsip = None, nmapped = None, type = 'endpoint', section_to = None, key_to = None)
Merge values from the given section with those from the default.
Definition at line 70 of file sip_to_pjsip.py.
References merge_codec_value(), and set_value().
Referenced by merge_codec_value(), set_transport_common(), and set_value().
                 key_to=None):
     """Merge values from the given section with those from the default."""
     def _merge_value(k, v, s, r, n):
         merge_value(key if key else k, v, s, r, n, type, section_to, key_to)
     # if no value or section return the merge_value
     # function with the enclosed key and type
     if not val and not section:
         return _merge_value
     # should return a single value section list
     try:
         sect = sip.section(section)[0]
     except LookupError:
         sect = sip.default(section)[0]
     # for each merged value add it to pjsip.conf
     for i in sect.get_merged(key):
         set_value(key_to if key_to else key, i,
                   section_to if section_to else section,
                   pjsip, nmapped, type)
non_mapped()
def sip_to_pjsip.non_mapped (nmapped)
Write non-mapped sip.conf values to the non-mapped object
Definition at line 132 of file sip_to_pjsip.py.
Referenced by convert().
 def non_mapped(nmapped):
     """Write non-mapped sip.conf values to the non-mapped object"""
     def _non_mapped(section, key, val):
         """Writes a non-mapped value from sip.conf to the non-mapped object."""
         if section not in nmapped:
             nmapped[section] = astconfigparser.Section()
             if isinstance(val, list):
                 for v in val:
                     # since coming from sip.conf we can assume
                     # single section lists
                     nmapped[section][0][key] = v
             else:
                 nmapped[section][0][key] = val
     return _non_mapped
section_by_type()
def sip_to_pjsip.section_by_type (section, pjsip, type)
some utility functions
Finds a section based upon the given type, adding it if not found.
Definition at line 23 of file sip_to_pjsip.py.
References ignore().
Referenced by set_value().
 def section_by_type(section, pjsip, type):
     """Finds a section based upon the given type, adding it if not found."""
     def __find_dict(mdicts, key, val):
         """Given a list of multi-dicts, return the multi-dict that contains
            the given key/value pair."""
         def found(d):
             return key in d and val in d[key]
         try:
             return [d for d in mdicts if found(d)][0]
         except IndexError:
             raise LookupError("Dictionary not located for key = %s, value = %s"
                               % (key, val))
     try:
         return __find_dict(pjsip.section(section), 'type', type)
     except LookupError:
         # section for type doesn't exist, so add
         sect = pjsip.add_section(section)
         sect['type'] = type
         return sect
set_direct_media()
def sip_to_pjsip.set_direct_media (key, val, section, pjsip, nmapped)
Maps values from the sip.conf comma separated direct_media option
into pjsip.conf direct_media options.
Definition at line 224 of file sip_to_pjsip.py.
References set_value().
 def set_direct_media(key, val, section, pjsip, nmapped):
     """
     Maps values from the sip.conf comma separated direct_media option
     into pjsip.conf direct_media options.
     """
     if 'yes' in val:
         set_value('direct_media', 'yes', section, pjsip, nmapped)
     if 'update' in val:
         set_value('direct_media_method', 'update', section, pjsip, nmapped)
     if 'outgoing' in val:
         set_value('directed_media_glare_mitigation', 'outgoing', section,
                   pjsip, nmapped)
     if 'nonat' in val:
         set_value('disable_directed_media_on_nat', 'yes', section, pjsip,
                   nmapped)
     if 'no' in val:
         set_value('direct_media', 'no', section, pjsip, nmapped)
set_dtmfmode()
def sip_to_pjsip.set_dtmfmode (key, val, section, pjsip, nmapped)
mapping functions - define f(key, val, section) where key/val are the key/value pair to write to given section in pjsip.conf
Sets the dtmfmode value.  If value matches allowable option in pjsip
then map it, otherwise set it to none.
Definition at line 154 of file sip_to_pjsip.py.
References set_value().
 def set_dtmfmode(key, val, section, pjsip, nmapped):
     """
     Sets the dtmfmode value.  If value matches allowable option in pjsip
     then map it, otherwise set it to none.
     """
     key = 'dtmf_mode'
     # available pjsip.conf values: rfc4733, inband, info, none
     if val == 'inband' or val == 'info' or val == 'auto':
         set_value(key, val, section, pjsip, nmapped)
     elif val == 'rfc2833':
         set_value(key, 'rfc4733', section, pjsip, nmapped)
     else:
         nmapped(section, key, val + " ; did not fully map - set to none")
         set_value(key, 'none', section, pjsip, nmapped)
set_media_encryption()
def sip_to_pjsip.set_media_encryption (key, val, section, pjsip, nmapped)
Sets the media_encryption value in pjsip.conf
Definition at line 251 of file sip_to_pjsip.py.
References set_value().
 def set_media_encryption(key, val, section, pjsip, nmapped):
     """Sets the media_encryption value in pjsip.conf"""
     try:
         dtls = sip.get(section, 'dtlsenable')[0]
         if dtls == 'yes':
             # If DTLS is enabled, then that overrides SDES encryption.
             return
     except LookupError:
         pass
     if val == 'yes':
         set_value('media_encryption', 'sdes', section, pjsip, nmapped)
set_record_off_feature()
def sip_to_pjsip.set_record_off_feature (key, val, section, pjsip, nmapped)
Sets the record_off_feature in pjsip.conf
Definition at line 277 of file sip_to_pjsip.py.
References from_recordfeature().
 def set_record_off_feature(key, val, section, pjsip, nmapped):
     """Sets the record_off_feature in pjsip.conf"""
     from_recordfeature('record_off_feature', val, section, pjsip, nmapped)
set_record_on_feature()
def sip_to_pjsip.set_record_on_feature (key, val, section, pjsip, nmapped)
Sets the record_on_feature in pjsip.conf
Definition at line 273 of file sip_to_pjsip.py.
References from_recordfeature().
 def set_record_on_feature(key, val, section, pjsip, nmapped):
     """Sets the record_on_feature in pjsip.conf"""
     from_recordfeature('record_on_feature', val, section, pjsip, nmapped)
set_timers()
def sip_to_pjsip.set_timers (key, val, section, pjsip, nmapped)
Sets the timers in pjsip.conf from the session-timers option
found in sip.conf.
Definition at line 205 of file sip_to_pjsip.py.
References set_value().
 def set_timers(key, val, section, pjsip, nmapped):
     """
     Sets the timers in pjsip.conf from the session-timers option
     found in sip.conf.
     """
     # pjsip.conf values can be yes/no, required, always
     # 'required' is a new feature of chan_pjsip, which rejects
     #            all SIP clients not supporting Session Timers
     # 'Accept' is the default value of chan_sip and maps to 'yes'
     # chan_sip ignores the case, for example 'session-timers=Refuse'
     val = val.lower()
     if val == 'originate':
         set_value('timers', 'always', section, pjsip, nmapped)
     elif val == 'refuse':
         set_value('timers', 'no', section, pjsip, nmapped)
     else:
         set_value('timers', 'yes', section, pjsip, nmapped)
set_tls_cafile()
def sip_to_pjsip.set_tls_cafile (val, pjsip, section, nmapped)
Sets ca_list_file based on sip.conf tlscafile
Definition at line 785 of file sip_to_pjsip.py.
References set_value().
 def set_tls_cafile(val, pjsip, section, nmapped):
     """Sets ca_list_file based on sip.conf tlscafile"""
     set_value('ca_list_file', val, section, pjsip, nmapped,
               'transport')
set_tls_capath()
def sip_to_pjsip.set_tls_capath (val, pjsip, section, nmapped)
Sets ca_list_path based on sip.conf tlscapath
Definition at line 791 of file sip_to_pjsip.py.
References set_value().
 def set_tls_capath(val, pjsip, section, nmapped):
     """Sets ca_list_path based on sip.conf tlscapath"""
     set_value('ca_list_path', val, section, pjsip, nmapped,
               'transport')
set_tls_cert_file()
def sip_to_pjsip.set_tls_cert_file (val, pjsip, section, nmapped)
Sets cert_file based on sip.conf tlscertfile
Definition at line 763 of file sip_to_pjsip.py.
References set_value().
 def set_tls_cert_file(val, pjsip, section, nmapped):
     """Sets cert_file based on sip.conf tlscertfile"""
     set_value('cert_file', val, section, pjsip, nmapped,
               'transport')
set_tls_cipher()
def sip_to_pjsip.set_tls_cipher (val, pjsip, section, nmapped)
Sets cipher based on sip.conf tlscipher or sslcipher
Definition at line 775 of file sip_to_pjsip.py.
References set_value().
 def set_tls_cipher(val, pjsip, section, nmapped):
     """Sets cipher based on sip.conf tlscipher or sslcipher"""
     if val == 'ALL':
         return
     print('chan_sip ciphers do not match 1:1 with PJSIP ciphers.' \
           ' You should manually review and adjust this.', file=sys.stderr)
     set_value('cipher', val, section, pjsip, nmapped, 'transport')
set_tls_private_key()
def sip_to_pjsip.set_tls_private_key (val, pjsip, section, nmapped)
Sets privkey_file based on sip.conf tlsprivatekey or sslprivatekey
Definition at line 769 of file sip_to_pjsip.py.
References set_value().
 def set_tls_private_key(val, pjsip, section, nmapped):
     """Sets privkey_file based on sip.conf tlsprivatekey or sslprivatekey"""
     set_value('priv_key_file', val, section, pjsip, nmapped,
               'transport')
set_tls_verifyclient()
def sip_to_pjsip.set_tls_verifyclient (val, pjsip, section, nmapped)
Sets verify_client based on sip.conf tlsverifyclient
Definition at line 797 of file sip_to_pjsip.py.
References set_value().
 def set_tls_verifyclient(val, pjsip, section, nmapped):
     """Sets verify_client based on sip.conf tlsverifyclient"""
     set_value('verify_client', val, section, pjsip, nmapped,
               'transport')
set_tls_verifyserver()
def sip_to_pjsip.set_tls_verifyserver (val, pjsip, section, nmapped)
Sets verify_server based on sip.conf tlsdontverifyserver
Definition at line 803 of file sip_to_pjsip.py.
References set_value().
 def set_tls_verifyserver(val, pjsip, section, nmapped):
     """Sets verify_server based on sip.conf tlsdontverifyserver"""
     if val == 'no':
         set_value('verify_server', 'yes', section, pjsip, nmapped,
                   'transport')
     else:
         set_value('verify_server', 'no', section, pjsip, nmapped,
                   'transport')
set_transport_common()
def sip_to_pjsip.set_transport_common (section, sip, pjsip, protocol, nmapped)
sip.conf has several global settings that in pjsip.conf apply to individual
transports. This function adds these global settings to each individual
transport.
The settings included are:
externaddr (or externip)
externhost
externtcpport for TCP
externtlsport for TLS
localnet
tos_sip
cos_sip
Definition at line 611 of file sip_to_pjsip.py.
References merge_value(), set_value(), and split_hostport().
Referenced by create_tcp(), create_tls(), and create_udp().
 def set_transport_common(section, sip, pjsip, protocol, nmapped):
     """
     sip.conf has several global settings that in pjsip.conf apply to individual
     transports. This function adds these global settings to each individual
     transport.
     The settings included are:
     externaddr (or externip)
     externhost
     externtcpport for TCP
     externtlsport for TLS
     localnet
     tos_sip
     cos_sip
     """
     try:
         extern_addr = sip.multi_get('general', ['externaddr', 'externip',
                                                 'externhost'])[0]
         host, port = split_hostport(extern_addr)
         try:
             port = sip.get('general', 'extern' + protocol + 'port')[0]
         except LookupError:
             pass
         set_value('external_media_address', host, section, pjsip,
                   nmapped, 'transport')
         set_value('external_signaling_address', host, section, pjsip,
                   nmapped, 'transport')
         if port:
             set_value('external_signaling_port', port, section, pjsip,
                       nmapped, 'transport')
     except LookupError:
         pass
     try:
         merge_value('localnet', sip.get('general', 'localnet')[0], 'general',
                     pjsip, nmapped, 'transport', section, "local_net")
     except LookupError:
         # No localnet options configured. Move on.
         pass
     try:
         set_value('tos', sip.get('general', 'tos_sip')[0], section, pjsip,
                   nmapped, 'transport')
     except LookupError:
         pass
     try:
         set_value('cos', sip.get('general', 'cos_sip')[0], section, pjsip,
                   nmapped, 'transport')
     except LookupError:
         pass
set_value()
def sip_to_pjsip.set_value (key = None, val = None, section = None, pjsip = None, nmapped = None, type = 'endpoint')
Sets the key to the value within the section in pjsip.conf
Definition at line 53 of file sip_to_pjsip.py.
References merge_value(), and section_by_type().
Referenced by create_tcp(), create_tls(), create_udp(), from_dtlsenable(), from_encryption_taglen(), from_host(), from_mailbox(), from_nat(), from_progressinband(), from_recordfeature(), from_sendrpid(), map_auth(), map_setvars(), map_system(), merge_codec_value(), merge_value(), set_direct_media(), set_dtmfmode(), set_media_encryption(), set_timers(), set_tls_cafile(), set_tls_capath(), set_tls_cert_file(), set_tls_cipher(), set_tls_private_key(), set_tls_verifyclient(), set_tls_verifyserver(), set_transport_common(), setup_auth(), setup_ident(), setup_udptl(), and Registration.write().
               nmapped=None, type='endpoint'):
     """Sets the key to the value within the section in pjsip.conf"""
     def _set_value(k, v, s, r, n):
         set_value(key if key else k, v, s, r, n, type)
     # if no value or section return the set_value
     # function with the enclosed key and type
     if not val and not section:
         return _set_value
     # otherwise try to set the value
     section_by_type(section, pjsip, type)[key] = \
         val[0] if isinstance(val, list) else val
setup_auth()
def sip_to_pjsip.setup_auth (key, val, section, pjsip, nmapped)
Sets up authentication information for a specific endpoint based on the
'secret' setting on a peer in sip.conf
Definition at line 378 of file sip_to_pjsip.py.
References set_value().
 def setup_auth(key, val, section, pjsip, nmapped):
     """
     Sets up authentication information for a specific endpoint based on the
     'secret' setting on a peer in sip.conf
     """
     set_value('username', section, section, pjsip, nmapped, 'auth')
     # In chan_sip, if a secret and an md5secret are both specified on a peer,
     # then in practice, only the md5secret is used. If both are encountered
     # then we build an auth section that has both an md5_cred and password.
     # However, the auth_type will indicate to authenticators to use the
     # md5_cred, so like with sip.conf, the password will be there but have
     # no purpose.
     if key == 'secret':
         set_value('password', val, section, pjsip, nmapped, 'auth')
     else:
         set_value('md5_cred', val, section, pjsip, nmapped, 'auth')
         set_value('auth_type', 'md5', section, pjsip, nmapped, 'auth')
     realms = [section]
     try:
         auths = sip.get('authentication', 'auth')
         for i in auths:
             user, at, realm = i.partition('@')
             realms.append(realm)
     except LookupError:
         pass
     realm_str = ','.join(realms)
     set_value('auth', section, section, pjsip, nmapped)
     set_value('outbound_auth', realm_str, section, pjsip, nmapped)
setup_ident()
def sip_to_pjsip.setup_ident (key, val, section, pjsip, nmapped)
Examines the 'type' field for a sip.conf peer and creates an identify
section if the type is either 'peer' or 'friend'. The identify section uses
either the host or defaultip field of the sip.conf peer.
Definition at line 411 of file sip_to_pjsip.py.
References set_value().
 def setup_ident(key, val, section, pjsip, nmapped):
     """
     Examines the 'type' field for a sip.conf peer and creates an identify
     section if the type is either 'peer' or 'friend'. The identify section uses
     either the host or defaultip field of the sip.conf peer.
     """
     if val != 'peer' and val != 'friend':
         return
     try:
         ip = sip.get(section, 'host')[0]
     except LookupError:
         return
     if ip == 'dynamic':
         try:
             ip = sip.get(section, 'defaultip')[0]
         except LookupError:
             return
     set_value('endpoint', section, section, pjsip, nmapped, 'identify')
     set_value('match', ip, section, pjsip, nmapped, 'identify')
setup_udptl()
def sip_to_pjsip.setup_udptl (section, pjsip, nmapped)
Sets values from udptl into the appropriate pjsip.conf options.
Definition at line 170 of file sip_to_pjsip.py.
References set_value().
Referenced by map_peer().
 def setup_udptl(section, pjsip, nmapped):
     """Sets values from udptl into the appropriate pjsip.conf options."""
     try:
         val = sip.get(section, 't38pt_udptl')[0]
     except LookupError:
         try:
             val = sip.get('general', 't38pt_udptl')[0]
         except LookupError:
             return
     ec = 'none'
     if 'yes' in val:
         set_value('t38_udptl', 'yes', section, pjsip, nmapped)
     if 'no' in val:
         set_value('t38_udptl', 'no', section, pjsip, nmapped)
     if 'redundancy' in val:
         ec = 'redundancy'
     if 'fec' in val:
         ec = 'fec'
     set_value('t38_udptl_ec', ec, section, pjsip, nmapped)
split_hostport()
def sip_to_pjsip.split_hostport (addr)
Given an address in the form 'host:port' separate the host and port
components.
Returns a two-tuple of strings, (host, port). If no port is present in the
string, then the port section of the tuple is None.
Definition at line 590 of file sip_to_pjsip.py.
Referenced by get_bind(), load_module(), set_transport_common(), and unload_module().
 def split_hostport(addr):
     """
     Given an address in the form 'host:port' separate the host and port
     components.
     Returns a two-tuple of strings, (host, port). If no port is present in the
     string, then the port section of the tuple is None.
     """
     try:
         socket.inet_pton(socket.AF_INET6, addr)
         if not addr.startswith('['):
             return (addr, None)
     except socket.error:
         pass
     # Literal IPv6 (like [::]), IPv4, or hostname
     # does not work for IPv6 without brackets; case catched above
     url = urlparse('sip://' + addr)
     # TODO Does not compress IPv6, for example 0:0:0:0:0:0:0:0 should get [::]
     return (url.hostname, url.port)
write_pjsip()
def sip_to_pjsip.write_pjsip (filename, pjsip, non_mappings)
Write pjsip.conf file to disk
Definition at line 1261 of file sip_to_pjsip.py.
References astconfigparser.write_dicts().
 def write_pjsip(filename, pjsip, non_mappings):
     """
     Write pjsip.conf file to disk
     """
     try:
         with open(filename, 'wt') as fp:
             fp.write(';--\n')
             fp.write(';;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;\n')
             fp.write('Non mapped elements start\n')
             fp.write(';;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;\n\n')
             astconfigparser.write_dicts(fp, non_mappings[filename])
             fp.write(';;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;\n')
             fp.write('Non mapped elements end\n')
             fp.write(';;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;\n')
             fp.write('--;\n\n')
             # write out include file(s)
             pjsip.write(fp)
     except IOError:
         print("Could not open file " + filename + " for writing", file=sys.stderr)
Variable Documentation
non_mappings
non_mappings
Definition at line 1328 of file sip_to_pjsip.py.
peer_map
list peer_map
Definition at line 452 of file sip_to_pjsip.py.
pjsip
pjsip
Definition at line 1328 of file sip_to_pjsip.py.
pjsip_filename
pjsip_filename
Definition at line 1320 of file sip_to_pjsip.py.
PREFIX
string PREFIX = 'pjsip_'
Definition at line 15 of file sip_to_pjsip.py.
QUIET
bool QUIET = False
Definition at line 16 of file sip_to_pjsip.py.
sip
sip = astconfigparser.MultiOrderedConfigParser()
Definition at line 1322 of file sip_to_pjsip.py.
sip_filename
sip_filename
Definition at line 1320 of file sip_to_pjsip.py.