Asterisk - The Open Source Telephony Project: bridge_basic.h File Reference
bridge_basic.h File Reference
Basic bridge subclass API.
Macros
#define AST_TRANSFERER_ROLE_NAME "transferer"
Functions
struct ast_bridge * ast_bridge_basic_new (void)
Create a new basic class bridge.
void ast_bridge_basic_set_flags (struct ast_bridge *bridge, unsigned int flags)
Set feature flags on a basic bridge.
int ast_bridge_features_ds_append (struct ast_channel *chan, struct ast_flags *flags)
Append basic bridge DTMF feature flags on the channel.
struct ast_flags * ast_bridge_features_ds_get (struct ast_channel *chan)
Get DTMF feature flags from the channel.
int ast_bridge_features_ds_get_string (struct ast_channel *chan, char *buffer, size_t buf_size)
writes a channel's DTMF features to a buffer string
int ast_bridge_features_ds_set (struct ast_channel *chan, struct ast_flags *flags)
Set basic bridge DTMF feature flags datastore on the channel.
int ast_bridge_features_ds_set_string (struct ast_channel *chan, const char *features)
Sets the features a channel will use upon being bridged.
void ast_bridging_init_basic (void)
Variables
struct ast_bridge_methods ast_bridge_basic_v_table
Bridge basic class virtual method table.
Detailed Description
Basic bridge subclass API.
Author
Richard Mudgett rmudg.nosp@m.ett@.nosp@m.digiu.nosp@m.m.co.nosp@m.m
See Also:
CREDITS
Definition in file bridge_basic.h.
Macro Definition Documentation
AST_TRANSFERER_ROLE_NAME
#define AST_TRANSFERER_ROLE_NAME "transferer"
Definition at line 36 of file bridge_basic.h.
Referenced by add_transferer_role(), attended_transfer_properties_shutdown(), bridge_personality_atxfer_push(), and handle_hangup().
Function Documentation
ast_bridge_basic_new()
struct ast_bridge* ast_bridge_basic_new (void)
Create a new basic class bridge.
Return values
a pointer to a new bridge on success
NULL on failure
Example usage:
struct ast_bridge *bridge;
bridge = ast_bridge_basic_new();
This creates a basic two party bridge with any configured DTMF features enabled that will be destroyed once one of the channels hangs up.
Definition at line 3617 of file bridge_basic.c.
References ast_bridge_basic_v_table, AST_BRIDGE_CAPABILITY_1TO1MIX, AST_BRIDGE_CAPABILITY_MULTIMIX, AST_BRIDGE_CAPABILITY_NATIVE, bridge_alloc(), bridge_base_init(), bridge_basic_personality_alloc(), bridge_register(), NORMAL_FLAGS, and NULL.
Referenced by action_bridge(), agent_request_exec(), ast_bridge_call_with_flags(), AST_TEST_DEFINE(), bridge_exec(), feature_attended_transfer(), and parked_call_app_exec().
 {
    struct ast_bridge *bridge;
    bridge = bridge_alloc(sizeof(struct ast_bridge), &ast_bridge_basic_v_table);
    bridge = bridge_base_init(bridge,
       AST_BRIDGE_CAPABILITY_NATIVE | AST_BRIDGE_CAPABILITY_1TO1MIX
          | AST_BRIDGE_CAPABILITY_MULTIMIX, NORMAL_FLAGS, NULL, NULL, NULL);
    bridge = bridge_basic_personality_alloc(bridge);
    bridge = bridge_register(bridge);
    return bridge;
 }
ast_bridge_basic_set_flags()
void ast_bridge_basic_set_flags (struct ast_bridge * bridge, unsigned int flags)
Set feature flags on a basic bridge.
Using this function instead of setting flags directly will ensure that after operations such as an attended transfer, the bridge will maintain the flags that were set on it.
Flags to set on the bridge. These are added to the flags already set.
Definition at line 3630 of file bridge_basic.c.
References ast_bridge_lock, ast_bridge_unlock, ast_set_flag, personality_details::bridge_flags, bridge_basic_personality::current, bridge_basic_personality::details, ast_bridge::feature_flags, lock, ast_bridge::personality, and SCOPED_LOCK.
Referenced by ast_bridge_call_with_flags().
 {
    SCOPED_LOCK(lock, bridge, ast_bridge_lock, ast_bridge_unlock);
    struct bridge_basic_personality *personality = bridge->personality;
    personality->details[personality->current].bridge_flags |= flags;
    ast_set_flag(&bridge->feature_flags, flags);
 }
ast_bridge_features_ds_append()
int ast_bridge_features_ds_append (struct ast_channel * chan, struct ast_flags * flags)
Append basic bridge DTMF feature flags on the channel.
Since
12.0.0
Parameters
chan Channel to append DTMF features datastore.
flags Builtin DTMF feature flags. (ast_bridge_config flags)
Note
The channel must be locked before calling this function.
This function differs from ast_bridge_features_ds_set only in that it won't remove features already set on the channel.
Return values
0 on success.
-1 on error.
Definition at line 263 of file bridge_basic.c.
References bridge_features_ds_set_full().
Referenced by pre_bridge_setup().
 {
    return bridge_features_ds_set_full(chan, flags, 0);
 }
ast_bridge_features_ds_get()
struct ast_flags* ast_bridge_features_ds_get (struct ast_channel * chan)
Get DTMF feature flags from the channel.
Since
12.0.0
Parameters
chan Channel to get DTMF features datastore.
Note
The channel should be locked before calling this function.
The channel must remain locked until the flags returned have been consumed.
Return values
flags on success.
NULL if the datastore does not exist.
Definition at line 268 of file bridge_basic.c.
References ast_channel_datastore_find(), ast_datastore::data, and NULL.
Referenced by ast_bridge_features_ds_get_string(), attended_transfer_properties_alloc(), parked_call_retrieve_enable_features(), and setup_bridge_features_builtin().
 {
    struct ast_datastore *datastore;
    datastore = ast_channel_datastore_find(chan, &dtmf_features_info, NULL);
    if (!datastore) {
       return NULL;
    }
    return datastore->data;
 }
ast_bridge_features_ds_get_string()
int ast_bridge_features_ds_get_string (struct ast_channel * chan, char * buffer, size_t buf_size)
writes a channel's DTMF features to a buffer string
Since
12.0.0
Parameters
chan channel whose feature flags should be checked
buffer pointer string buffer where the output should be stored
buf_size size of the provided buffer (ideally enough for all features, 6+)
Return values
0 on successful write
-1 on failure
Definition at line 208 of file bridge_basic.c.
References ast_bridge_features_ds_get(), ast_channel_lock, ast_channel_unlock, and dtmf_features_flags_to_string().
Referenced by func_channel_read().
 {
    struct ast_flags *channel_flags;
    struct ast_flags held_copy;
    ast_channel_lock(chan);
    if (!(channel_flags = ast_bridge_features_ds_get(chan))) {
       ast_channel_unlock(chan);
       return -1;
    }
    held_copy = *channel_flags;
    ast_channel_unlock(chan);
    return dtmf_features_flags_to_string(&held_copy, buffer, buf_size);
 }
ast_bridge_features_ds_set()
int ast_bridge_features_ds_set (struct ast_channel * chan, struct ast_flags * flags)
Set basic bridge DTMF feature flags datastore on the channel.
Since
12.0.0
Parameters
chan Channel to set DTMF features datastore.
flags Builtin DTMF feature flags. (ast_bridge_config flags)
Note
The channel must be locked before calling this function.
Return values
0 on success.
-1 on error.
Definition at line 258 of file bridge_basic.c.
References bridge_features_ds_set_full().
Referenced by ast_bridge_features_ds_set_string(), parked_call_retrieve_enable_features(), and recalling_exit().
 {
    return bridge_features_ds_set_full(chan, flags, 1);
 }
ast_bridge_features_ds_set_string()
int ast_bridge_features_ds_set_string (struct ast_channel * chan, const char * features)
Sets the features a channel will use upon being bridged.
Since
12.0.0
Parameters
chan Which channel to set features for
features Which feature codes to set for the channel
Return values
0 on success
-1 on failure
Definition at line 189 of file bridge_basic.c.
References ast_bridge_features_ds_set(), ast_channel_lock, ast_channel_name(), ast_channel_unlock, ast_log, build_dtmf_features(), and LOG_ERROR.
Referenced by func_channel_write_real().
 {
    struct ast_flags flags = {0};
    if (build_dtmf_features(&flags, features)) {
       return -1;
    }
    ast_channel_lock(chan);
    if (ast_bridge_features_ds_set(chan, &flags)) {
       ast_channel_unlock(chan);
       ast_log(LOG_ERROR, "Failed to apply features datastore for '%s' to channel '%s'\n", features, ast_channel_name(chan));
       return -1;
    }
    ast_channel_unlock(chan);
    return 0;
 }
ast_bridging_init_basic()
void ast_bridging_init_basic (void)
Initialize the basic bridge class for use by the system.
Definition at line 3639 of file bridge_basic.c.
References ast_bridge_base_v_table, ast_bridge_basic_v_table, AST_BRIDGE_BUILTIN_ATTENDEDTRANSFER, AST_BRIDGE_BUILTIN_BLINDTRANSFER, ast_bridge_features_register(), bridge_basic_destroy(), bridge_basic_pull(), bridge_basic_push(), bridge_personality_atxfer_pull(), bridge_personality_atxfer_push(), bridge_personality_normal_push(), ast_bridge_methods::destroy, feature_attended_transfer(), feature_blind_transfer(), ast_bridge_methods::name, NULL, personality_atxfer_v_table, personality_normal_v_table, ast_bridge_methods::pull, and ast_bridge_methods::push.
Referenced by ast_bridging_init().
 {
    /* Setup bridge basic subclass v_table. */
    ast_bridge_basic_v_table = ast_bridge_base_v_table;
    ast_bridge_basic_v_table.name = "basic";
    ast_bridge_basic_v_table.push = bridge_basic_push;
    ast_bridge_basic_v_table.pull = bridge_basic_pull;
    ast_bridge_basic_v_table.destroy = bridge_basic_destroy;
    /*
     * Personality vtables don't have the same rules as
     * normal bridge vtables.  These vtable functions are
     * used as alterations to the ast_bridge_basic_v_table
     * method functionality and are checked for NULL before
     * calling.
     */
    personality_normal_v_table.name = "normal";
    personality_normal_v_table.push = bridge_personality_normal_push;
    personality_atxfer_v_table.name = "attended transfer";
    personality_atxfer_v_table.push = bridge_personality_atxfer_push;
    personality_atxfer_v_table.pull = bridge_personality_atxfer_pull;
    ast_bridge_features_register(AST_BRIDGE_BUILTIN_ATTENDEDTRANSFER, feature_attended_transfer, NULL);
    ast_bridge_features_register(AST_BRIDGE_BUILTIN_BLINDTRANSFER, feature_blind_transfer, NULL);
 }
Variable Documentation
ast_bridge_basic_v_table
struct ast_bridge_methods ast_bridge_basic_v_table
Bridge basic class virtual method table.
Definition at line 3526 of file bridge_basic.c.
Referenced by ast_bridge_basic_new(), and ast_bridging_init_basic().