Asterisk - The Open Source Telephony Project: ooh323cDriver.h File Reference
ooh323cDriver.h File Reference
#include "chan_ooh323.h"
#include "ootypes.h"
#include "ooh323ep.h"
#include "oochannels.h"
#include "ooCalls.h"
#include "ooCapability.h"
#include "ooStackCmds.h"
#include "asterisk/format.h"
Macros
#define H323_DTMF_CISCO (1 << 5)
#define H323_DTMF_H245ALPHANUMERIC (1 << 2)
#define H323_DTMF_H245SIGNAL (1 << 3)
#define H323_DTMF_INBAND (1 << 4)
#define H323_DTMF_INBANDRELAX (1 << 8)
#define H323_DTMF_Q931 (1 << 1)
#define H323_DTMF_RFC2833 (1 << 0)
Functions
struct ast_format * convertH323CapToAsteriskCap (int cap)
int ooh323c_set_capability (struct ast_format_cap *cap, int dtmf, int dtmfcodec)
int ooh323c_set_capability_for_call (ooCallData *call, struct ast_format_cap *cap, int dtmf, int dtmfcodec, int t38support, int g729onlyA)
int ooh323c_start_call_thread (ooCallData *call)
int ooh323c_start_stack_thread (void)
int ooh323c_stop_call_thread (ooCallData *call)
int ooh323c_stop_stack_thread (void)
Macro Definition Documentation
H323_DTMF_CISCO
#define H323_DTMF_CISCO (1 << 5)
Definition at line 31 of file ooh323cDriver.h.
Referenced by build_peer(), build_user(), configure_local_rtp(), handle_cli_ooh323_show_config(), handle_cli_ooh323_show_peer(), handle_cli_ooh323_show_user(), ooh323_digit_begin(), ooh323_digit_end(), ooh323_set_write_format(), ooh323c_set_capability(), ooh323c_set_capability_for_call(), and reload_config().
H323_DTMF_H245ALPHANUMERIC
#define H323_DTMF_H245ALPHANUMERIC (1 << 2)
Definition at line 28 of file ooh323cDriver.h.
Referenced by build_peer(), build_user(), handle_cli_ooh323_show_config(), handle_cli_ooh323_show_peer(), handle_cli_ooh323_show_user(), ooh323_digit_begin(), ooh323c_set_capability(), ooh323c_set_capability_for_call(), and reload_config().
H323_DTMF_H245SIGNAL
#define H323_DTMF_H245SIGNAL (1 << 3)
Definition at line 29 of file ooh323cDriver.h.
Referenced by build_peer(), build_user(), handle_cli_ooh323_show_config(), handle_cli_ooh323_show_peer(), handle_cli_ooh323_show_user(), ooh323_digit_begin(), ooh323c_set_capability(), ooh323c_set_capability_for_call(), and reload_config().
H323_DTMF_INBAND
#define H323_DTMF_INBAND (1 << 4)
Definition at line 30 of file ooh323cDriver.h.
Referenced by build_peer(), build_user(), handle_cli_ooh323_show_config(), handle_cli_ooh323_show_peer(), handle_cli_ooh323_show_user(), ooh323_digit_begin(), ooh323_digit_end(), ooh323_new(), ooh323_rtp_read(), and reload_config().
H323_DTMF_INBANDRELAX
#define H323_DTMF_INBANDRELAX (1 << 8)
Definition at line 32 of file ooh323cDriver.h.
Referenced by build_peer(), build_user(), handle_cli_ooh323_show_config(), handle_cli_ooh323_show_peer(), handle_cli_ooh323_show_user(), ooh323_new(), and reload_config().
H323_DTMF_Q931
#define H323_DTMF_Q931 (1 << 1)
Definition at line 27 of file ooh323cDriver.h.
Referenced by build_peer(), build_user(), handle_cli_ooh323_show_config(), handle_cli_ooh323_show_peer(), handle_cli_ooh323_show_user(), ooh323_digit_begin(), and reload_config().
H323_DTMF_RFC2833
#define H323_DTMF_RFC2833 (1 << 0)
Definition at line 26 of file ooh323cDriver.h.
Referenced by build_peer(), build_user(), configure_local_rtp(), handle_cli_ooh323_show_config(), handle_cli_ooh323_show_peer(), handle_cli_ooh323_show_user(), ooh323_digit_begin(), ooh323_digit_end(), ooh323_set_write_format(), ooh323c_set_capability(), ooh323c_set_capability_for_call(), and reload_config().
Function Documentation
convertH323CapToAsteriskCap()
struct ast_format* convertH323CapToAsteriskCap (int cap)
Definition at line 664 of file ooh323cDriver.c.
References ast_debug, ast_format_alaw, ast_format_g723, ast_format_g726, ast_format_g726_aal2, ast_format_g729, ast_format_gsm, ast_format_h263, ast_format_speex, ast_format_ulaw, and NULL.
Referenced by ooh323c_start_receive_channel(), and ooh323c_start_transmit_channel().
 {
    switch(cap)
    {
       case OO_G711ULAW64K:
          return ast_format_ulaw;
       case OO_G711ALAW64K:
          return ast_format_alaw;
       case OO_GSMFULLRATE:
          return ast_format_gsm;
       case OO_SPEEX:
          return ast_format_speex;
       case OO_G729:
          return ast_format_g729;
       case OO_G729A:
          return ast_format_g729;
       case OO_G729B:
          return ast_format_g729;
       case OO_G7231:
          return ast_format_g723;
       case OO_G726:
          return ast_format_g726;
       case OO_G726AAL2:
          return ast_format_g726_aal2;
       case OO_H263VIDEO:
          return ast_format_h263;
       default:
          ast_debug(1, "Cap %d is not supported by driver yet\n", cap);
          return NULL;
    }
    return NULL;
 }
ooh323c_set_capability()
int ooh323c_set_capability (struct ast_format_cap * cap, int dtmf, int dtmfcodec)
Definition at line 228 of file ooh323cDriver.c.
References ao2_ref, ast_format_alaw, ast_format_cap_count(), ast_format_cap_get_format(), ast_format_cmp(), AST_FORMAT_CMP_EQUAL, ast_format_g723, ast_format_g726, ast_format_g726_aal2, ast_format_g729, ast_format_gsm, ast_format_h263, ast_format_speex, ast_format_ulaw, ast_verb, FALSE, format, gH323Debug, grxframes, gtxframes, H323_DTMF_CISCO, H323_DTMF_H245ALPHANUMERIC, H323_DTMF_H245SIGNAL, H323_DTMF_RFC2833, ooh323c_set_capability_for_call(), ooh323c_start_receive_channel(), ooh323c_start_transmit_channel(), ooh323c_stop_receive_channel(), and ooh323c_stop_transmit_channel().
Referenced by load_module(), and ooh323c_stop_stack_thread().
 {
    int ret = 0, x;
    if (gH323Debug) {
      ast_verb(0, "\tAdding capabilities to H323 endpoint\n");
    }
    for(x=0; x<ast_format_cap_count(cap); x++)
    {
     struct ast_format *format = ast_format_cap_get_format(cap, x);
       if(ast_format_cmp(format, ast_format_ulaw) == AST_FORMAT_CMP_EQUAL)
       {
          if (gH323Debug) {
             ast_verb(0, "\tAdding g711 ulaw capability to H323 endpoint\n");
     }
          ret= ooH323EpAddG711Capability(OO_G711ULAW64K, gtxframes, grxframes,
                                      OORXANDTX, &ooh323c_start_receive_channel,
                                      &ooh323c_start_transmit_channel,
                                      &ooh323c_stop_receive_channel,
                                      &ooh323c_stop_transmit_channel);
       }
       if(ast_format_cmp(format, ast_format_alaw) == AST_FORMAT_CMP_EQUAL)
       {
          if (gH323Debug) {
             ast_verb(0, "\tAdding g711 alaw capability to H323 endpoint\n");
     }
          ret= ooH323EpAddG711Capability(OO_G711ALAW64K, gtxframes, grxframes,
                                      OORXANDTX, &ooh323c_start_receive_channel,
                                      &ooh323c_start_transmit_channel,
                                      &ooh323c_stop_receive_channel,
                                      &ooh323c_stop_transmit_channel);
       }
       if(ast_format_cmp(format, ast_format_g729) == AST_FORMAT_CMP_EQUAL)
       {
          if (gH323Debug) {
        ast_verb(0, "\tAdding g729A capability to H323 endpoint\n");
     }
          ret = ooH323EpAddG729Capability(OO_G729A, 2, 24,
                                      OORXANDTX, &ooh323c_start_receive_channel,
                                      &ooh323c_start_transmit_channel,
                                      &ooh323c_stop_receive_channel,
                                      &ooh323c_stop_transmit_channel);
          if (gH323Debug) {
             ast_verb(0, "\tAdding g729 capability to H323 endpoint\n");
     }
          ret |= ooH323EpAddG729Capability(OO_G729, 2, 24,
                                      OORXANDTX, &ooh323c_start_receive_channel,
                                      &ooh323c_start_transmit_channel,
                                      &ooh323c_stop_receive_channel,
                                      &ooh323c_stop_transmit_channel);
          if (gH323Debug) {
             ast_verb(0, "\tAdding g729b capability to H323 endpoint\n");
     }
          ret |= ooH323EpAddG729Capability(OO_G729B, 2, 24,
                                      OORXANDTX, &ooh323c_start_receive_channel,
                                      &ooh323c_start_transmit_channel,
                                      &ooh323c_stop_receive_channel,
                                      &ooh323c_stop_transmit_channel);
       }
       if(ast_format_cmp(format, ast_format_g723) == AST_FORMAT_CMP_EQUAL)
       {
          if (gH323Debug) {
             ast_verb(0, "\tAdding g7231 capability to H323 endpoint\n");
     }
          ret = ooH323EpAddG7231Capability(OO_G7231, 1, 1, FALSE,
                                      OORXANDTX, &ooh323c_start_receive_channel,
                                      &ooh323c_start_transmit_channel,
                                      &ooh323c_stop_receive_channel,
                                      &ooh323c_stop_transmit_channel);
       }
       if(ast_format_cmp(format, ast_format_g726) == AST_FORMAT_CMP_EQUAL)
       {
          if (gH323Debug) {
             ast_verb(0, "\tAdding g726 capability to H323 endpoint\n");
     }
          ret = ooH323EpAddG726Capability(OO_G726, gtxframes, grxframes, FALSE,
                                      OORXANDTX, &ooh323c_start_receive_channel,
                                      &ooh323c_start_transmit_channel,
                                      &ooh323c_stop_receive_channel,
                                      &ooh323c_stop_transmit_channel);
       }
       if(ast_format_cmp(format, ast_format_g726_aal2) == AST_FORMAT_CMP_EQUAL)
       {
          if (gH323Debug) {
             ast_verb(0, "\tAdding g726aal2 capability to H323 endpoint\n");
     }
          ret = ooH323EpAddG726Capability(OO_G726AAL2, gtxframes, grxframes, FALSE,
                                      OORXANDTX, &ooh323c_start_receive_channel,
                                      &ooh323c_start_transmit_channel,
                                      &ooh323c_stop_receive_channel,
                                      &ooh323c_stop_transmit_channel);
       }
       if(ast_format_cmp(format, ast_format_h263) == AST_FORMAT_CMP_EQUAL)
       {
          if (gH323Debug) {
             ast_verb(0, "\tAdding h263 capability to H323 endpoint\n");
     }
          ret = ooH323EpAddH263VideoCapability(OO_H263VIDEO, 1, 0, 0, 0, 0, 320*1024,
                                      OORXANDTX, &ooh323c_start_receive_channel,
                                      &ooh323c_start_transmit_channel,
                                      &ooh323c_stop_receive_channel,
                                      &ooh323c_stop_transmit_channel);
       }
       if(ast_format_cmp(format, ast_format_gsm) == AST_FORMAT_CMP_EQUAL)
       {
          if (gH323Debug) {
             ast_verb(0, "\tAdding gsm capability to H323 endpoint\n");
     }
          ret = ooH323EpAddGSMCapability(OO_GSMFULLRATE, 4, FALSE, FALSE,
                                      OORXANDTX, &ooh323c_start_receive_channel,
                                      &ooh323c_start_transmit_channel,
                                      &ooh323c_stop_receive_channel,
                                      &ooh323c_stop_transmit_channel);
       }
       if(ast_format_cmp(format, ast_format_speex) == AST_FORMAT_CMP_EQUAL)
       {
          if (gH323Debug) {
             ast_verb(0, "\tAdding speex capability to H323 endpoint\n");
     }
          ret = ooH323EpAddSpeexCapability(OO_SPEEX, 4, 4, FALSE,
                                      OORXANDTX, &ooh323c_start_receive_channel,
                                      &ooh323c_start_transmit_channel,
                                      &ooh323c_stop_receive_channel,
                                      &ooh323c_stop_transmit_channel);
       }
     ao2_ref(format, -1);
    }
    if(dtmf & H323_DTMF_CISCO)
       ret |= ooH323EpEnableDTMFCISCO(0);
    if(dtmf & H323_DTMF_RFC2833)
       ret |= ooH323EpEnableDTMFRFC2833(0);
    else if(dtmf & H323_DTMF_H245ALPHANUMERIC)
       ret |= ooH323EpEnableDTMFH245Alphanumeric();
    else if(dtmf & H323_DTMF_H245SIGNAL)
       ret |= ooH323EpEnableDTMFH245Signal();
    return ret;
 }
ooh323c_set_capability_for_call()
int ooh323c_set_capability_for_call (ooCallData * call, struct ast_format_cap * cap, int dtmf, int dtmfcodec, int t38support, int g729onlyA)
Definition at line 384 of file ooh323cDriver.c.
References ao2_ref, ast_format_alaw, ast_format_cap_count(), ast_format_cap_get_format(), ast_format_cap_get_format_framing(), ast_format_cmp(), AST_FORMAT_CMP_EQUAL, ast_format_g723, ast_format_g726, ast_format_g726_aal2, ast_format_g729, ast_format_gsm, ast_format_h263, ast_format_speex, ast_format_ulaw, ast_verb, FALSE, format, gH323Debug, grxframes, H323_DTMF_CISCO, H323_DTMF_H245ALPHANUMERIC, H323_DTMF_H245SIGNAL, H323_DTMF_RFC2833, ooh323c_start_receive_channel(), ooh323c_start_receive_datachannel(), ooh323c_start_transmit_channel(), ooh323c_start_transmit_datachannel(), ooh323c_stop_receive_channel(), ooh323c_stop_receive_datachannel(), ooh323c_stop_transmit_channel(), and ooh323c_stop_transmit_datachannel().
Referenced by onNewCallCreated(), ooh323_onReceivedSetup(), and ooh323c_set_capability().
 {
    int ret = 0, x, txframes;
    if (gH323Debug) {
      ast_verb(0, "\tAdding capabilities to call(%s, %s)\n", call->callType,
                                                             call->callToken);
    }
    if(dtmf & H323_DTMF_CISCO || 1)
       ret |= ooCallEnableDTMFCISCO(call,dtmfcodec);
    if(dtmf & H323_DTMF_RFC2833 || 1)
       ret |= ooCallEnableDTMFRFC2833(call,dtmfcodec);
    if(dtmf & H323_DTMF_H245ALPHANUMERIC || 1)
       ret |= ooCallEnableDTMFH245Alphanumeric(call);
    if(dtmf & H323_DTMF_H245SIGNAL || 1)
       ret |= ooCallEnableDTMFH245Signal(call);
    if (t38support)
       ooCapabilityAddT38Capability(call, OO_T38, OORXANDTX,
                &ooh323c_start_receive_datachannel,
                &ooh323c_start_transmit_datachannel,
                &ooh323c_stop_receive_datachannel,
                &ooh323c_stop_transmit_datachannel,
                0);
    for(x=0; x<ast_format_cap_count(cap); x++)
    {
     struct ast_format *format = ast_format_cap_get_format(cap, x);
       if(ast_format_cmp(format, ast_format_ulaw) == AST_FORMAT_CMP_EQUAL)
       {
          if (gH323Debug) {
             ast_verb(0, "\tAdding g711 ulaw capability to call(%s, %s)\n",
                                               call->callType, call->callToken);
     }
     txframes = ast_format_cap_get_format_framing(cap, format);
          ret= ooCallAddG711Capability(call, OO_G711ULAW64K, txframes,
                                       txframes, OORXANDTX,
                                       &ooh323c_start_receive_channel,
                                       &ooh323c_start_transmit_channel,
                                       &ooh323c_stop_receive_channel,
                                       &ooh323c_stop_transmit_channel);
       }
       if(ast_format_cmp(format, ast_format_alaw) == AST_FORMAT_CMP_EQUAL)
       {
          if (gH323Debug) {
             ast_verb(0, "\tAdding g711 alaw capability to call(%s, %s)\n",
                                             call->callType, call->callToken);
     }
          txframes = ast_format_cap_get_format_framing(cap, format);
          ret= ooCallAddG711Capability(call, OO_G711ALAW64K, txframes,
                                      txframes, OORXANDTX,
                                      &ooh323c_start_receive_channel,
                                      &ooh323c_start_transmit_channel,
                                      &ooh323c_stop_receive_channel,
                                      &ooh323c_stop_transmit_channel);
       }
       if(ast_format_cmp(format, ast_format_g726) == AST_FORMAT_CMP_EQUAL)
       {
          if (gH323Debug) {
             ast_verb(0, "\tAdding g726 capability to call (%s, %s)\n",
                                            call->callType, call->callToken);
     }
     txframes = ast_format_cap_get_format_framing(cap, format);
          ret = ooCallAddG726Capability(call, OO_G726, txframes, grxframes, FALSE,
                                      OORXANDTX, &ooh323c_start_receive_channel,
                                      &ooh323c_start_transmit_channel,
                                      &ooh323c_stop_receive_channel,
                                      &ooh323c_stop_transmit_channel);
       }
       if(ast_format_cmp(format, ast_format_g726_aal2) == AST_FORMAT_CMP_EQUAL)
       {
          if (gH323Debug) {
             ast_verb(0, "\tAdding g726aal2 capability to call (%s, %s)\n",
                                            call->callType, call->callToken);
     }
     txframes = ast_format_cap_get_format_framing(cap, format);
          ret = ooCallAddG726Capability(call, OO_G726AAL2, txframes, grxframes, FALSE,
                                      OORXANDTX, &ooh323c_start_receive_channel,
                                      &ooh323c_start_transmit_channel,
                                      &ooh323c_stop_receive_channel,
                                      &ooh323c_stop_transmit_channel);
       }
       if(ast_format_cmp(format, ast_format_g729) == AST_FORMAT_CMP_EQUAL)
       {
          txframes = (ast_format_cap_get_format_framing(cap, format))/10;
          if (gH323Debug) {
             ast_verb(0, "\tAdding g729A capability to call(%s, %s)\n",
                                             call->callType, call->callToken);
     }
          ret= ooCallAddG729Capability(call, OO_G729A, txframes, txframes,
                                      OORXANDTX, &ooh323c_start_receive_channel,
                                      &ooh323c_start_transmit_channel,
                                      &ooh323c_stop_receive_channel,
                                      &ooh323c_stop_transmit_channel);
     if (g729onlyA)
       continue;
          if (gH323Debug) {
             ast_verb(0, "\tAdding g729 capability to call(%s, %s)\n",
                                             call->callType, call->callToken);
     }
          ret|= ooCallAddG729Capability(call, OO_G729, txframes, txframes,
                                      OORXANDTX, &ooh323c_start_receive_channel,
                                      &ooh323c_start_transmit_channel,
                                      &ooh323c_stop_receive_channel,
                                      &ooh323c_stop_transmit_channel);
          if (gH323Debug) {
             ast_verb(0, "\tAdding g729B capability to call(%s, %s)\n",
                                             call->callType, call->callToken);
     }
          ret|= ooCallAddG729Capability(call, OO_G729B, txframes, txframes,
                                      OORXANDTX, &ooh323c_start_receive_channel,
                                      &ooh323c_start_transmit_channel,
                                      &ooh323c_stop_receive_channel,
                                      &ooh323c_stop_transmit_channel);
       }
       if(ast_format_cmp(format, ast_format_g723) == AST_FORMAT_CMP_EQUAL)
       {
          if (gH323Debug) {
             ast_verb(0, "\tAdding g7231 capability to call (%s, %s)\n",
                                            call->callType, call->callToken);
     }
          ret = ooCallAddG7231Capability(call, OO_G7231, 1, 1, FALSE,
                                      OORXANDTX, &ooh323c_start_receive_channel,
                                      &ooh323c_start_transmit_channel,
                                      &ooh323c_stop_receive_channel,
                                      &ooh323c_stop_transmit_channel);
       }
       if(ast_format_cmp(format, ast_format_h263) == AST_FORMAT_CMP_EQUAL)
       {
          if (gH323Debug) {
             ast_verb(0, "\tAdding h263 capability to call (%s, %s)\n",
                                            call->callType, call->callToken);
     }
          ret = ooCallAddH263VideoCapability(call, OO_H263VIDEO, 1, 0, 0, 0, 0, 320*1024,
                                      OORXANDTX, &ooh323c_start_receive_channel,
                                      &ooh323c_start_transmit_channel,
                                      &ooh323c_stop_receive_channel,
                                      &ooh323c_stop_transmit_channel);
       }
       if(ast_format_cmp(format, ast_format_gsm) == AST_FORMAT_CMP_EQUAL)
       {
          if (gH323Debug) {
             ast_verb(0, "\tAdding gsm capability to call(%s, %s)\n",
                                              call->callType, call->callToken);
     }
          ret = ooCallAddGSMCapability(call, OO_GSMFULLRATE, 4, FALSE, FALSE,
                                      OORXANDTX, &ooh323c_start_receive_channel,
                                      &ooh323c_start_transmit_channel,
                                      &ooh323c_stop_receive_channel,
                                      &ooh323c_stop_transmit_channel);
       }
       if(ast_format_cmp(format, ast_format_speex) == AST_FORMAT_CMP_EQUAL)
       {
          if (gH323Debug) {
             ast_verb(0, "\tAdding Speex capability to call(%s, %s)\n",
                                              call->callType, call->callToken);
     }
          ret = ooCallAddSpeexCapability(call, OO_SPEEX, 4, 4, FALSE,
                                      OORXANDTX, &ooh323c_start_receive_channel,
                                      &ooh323c_start_transmit_channel,
                                      &ooh323c_stop_receive_channel,
                                      &ooh323c_stop_transmit_channel);
       }
       ao2_ref(format, -1);
    }
    return ret;
 }
ooh323c_start_call_thread()
int ooh323c_start_call_thread (ooCallData * call)
Definition at line 130 of file ooh323cDriver.c.
References ast_calloc, ast_debug, ast_free, ast_log, ast_module_ref, ast_mutex_destroy, ast_mutex_init, ast_mutex_lock, ast_mutex_trylock, ast_mutex_unlock, ast_pthread_create_detached_background, c, callthread::call, callThreads, callThreadsLock, gH323Debug, callthread::inUse, callthread::lock, LOG_ERROR, callthread::next, NULL, ooh323c_call_thread(), PF_LOCAL, callthread::thePipe, and TRUE.
Referenced by onNewCallCreated().
{
  char c = 'c';
  struct callthread *cur = callThreads;
  ast_mutex_lock(&callThreadsLock);
  while (cur != NULL && (cur->inUse || ast_mutex_trylock(&cur->lock))) {
    cur = cur->next;
  }
  ast_mutex_unlock(&callThreadsLock);
  if (cur != NULL) {
    if (cur->inUse || write(cur->thePipe[1], &c, 1) < 0) {
    ast_mutex_unlock(&cur->lock);
    cur = NULL;
    }
  }
 /* make new thread */
  if (cur == NULL) {
    if (!(cur = ast_calloc(1, sizeof(struct callthread)))) {
       ast_log(LOG_ERROR, "Unable to allocate thread structure for call %s\n",
                      call->callToken);
       return -1;
    }
    ast_module_ref(myself);
    if ((socketpair(PF_LOCAL, SOCK_STREAM, 0, cur->thePipe)) == -1) {
       ast_log(LOG_ERROR, "Can't create thread pipe for call %s\n", call->callToken);
       ast_free(cur);
       return -1;
    }
    cur->inUse = TRUE;
    cur->call = call;
    ast_mutex_init(&cur->lock);
    if (gH323Debug)
       ast_debug(1,"new call thread created for call %s\n", call->callToken);
    if(ast_pthread_create_detached_background(&call->callThread, NULL, ooh323c_call_thread, cur) < 0)
    {
       ast_log(LOG_ERROR, "Unable to start ooh323c call thread for call %s\n",
                call->callToken);
       ast_mutex_destroy(&cur->lock);
       close(cur->thePipe[0]);
       close(cur->thePipe[1]);
       ast_free(cur);
       return -1;
    }
  } else {
    if (gH323Debug)
       ast_debug(1,"using existing call thread for call %s\n", call->callToken);
    cur->inUse = TRUE;
    cur->call = call;
    ast_mutex_unlock(&cur->lock);
  }
  return 0;
 }
ooh323c_start_stack_thread()
int ooh323c_start_stack_thread (void)
Definition at line 199 of file ooh323cDriver.c.
References ast_log, ast_pthread_create_background, LOG_ERROR, NULL, ooh323c_cmd_thread(), ooh323c_stack_thread(), ooh323c_thread, and ooh323cmd_thread.
Referenced by load_module().
 {
    if(ast_pthread_create_background(&ooh323c_thread, NULL, ooh323c_stack_thread, NULL) < 0)
    {
       ast_log(LOG_ERROR, "Unable to start ooh323c thread.\n");
       return -1;
    }
    if(ast_pthread_create_background(&ooh323cmd_thread, NULL, ooh323c_cmd_thread, NULL) < 0)
    {
       ast_log(LOG_ERROR, "Unable to start ooh323cmd thread.\n");
       return -1;
    }
    return 0;
 }
ooh323c_stop_call_thread()
int ooh323c_stop_call_thread (ooCallData * call)
Definition at line 192 of file ooh323cDriver.c.
References AST_PTHREADT_NULL.
Referenced by onCallCleared().
{
  if (call->callThread != AST_PTHREADT_NULL) {
   ooStopMonitorCallChannels(call);
  }
  return 0;
 }
ooh323c_stop_stack_thread()
int ooh323c_stop_stack_thread (void)
Definition at line 214 of file ooh323cDriver.c.
References AST_PTHREADT_NULL, NULL, ooh323c_set_capability(), ooh323c_thread, and ooh323cmd_thread.
Referenced by unload_module().
 {
    if(ooh323c_thread !=  AST_PTHREADT_NULL)
    {
       ooStopMonitor();
       pthread_join(ooh323c_thread, NULL);
       ooh323c_thread =  AST_PTHREADT_NULL;
       pthread_join(ooh323cmd_thread, NULL);
       ooh323cmd_thread =  AST_PTHREADT_NULL;
    }
    return 0;
 }