Asterisk - The Open Source Telephony Project: format_g723.c File Reference
format_g723.c File Reference
Module: Media File Formats
Old-style G.723.1 frame/timestamp format.
#include "asterisk.h"
#include "asterisk/mod_format.h"
#include "asterisk/module.h"
#include "asterisk/format_cache.h"
Macros
#define G723_MAX_SIZE 1024
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static struct ast_frame * g723_read (struct ast_filestream *s, int *whennext)
static int g723_seek (struct ast_filestream *fs, off_t sample_offset, int whence)
static off_t g723_tell (struct ast_filestream *fs)
static int g723_trunc (struct ast_filestream *fs)
static int g723_write (struct ast_filestream *s, struct ast_frame *f)
static int load_module (void)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "G.723.1 Simple Timestamp File Format" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_APP_DEPEND }
static const struct ast_module_info * ast_module_info = &__mod_info
static struct ast_format_def g723_1_f
Detailed Description
Old-style G.723.1 frame/timestamp format.
Extensions: g723, g723sf
Definition in file format_g723.c.
Macro Definition Documentation
G723_MAX_SIZE
#define G723_MAX_SIZE 1024
Definition at line 38 of file format_g723.c.
Referenced by g723_read().
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 163 of file format_g723.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 163 of file format_g723.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 163 of file format_g723.c.
g723_read()
static struct ast_frame* g723_read (struct ast_filestream * s, int * whennext) static
Definition at line 40 of file format_g723.c.
References ast_format_get_name(), AST_FRAME_SET_BUFFER, AST_FRIENDLY_OFFSET, ast_log, ast_filestream::buf, ast_frame::data, ast_frame::datalen, errno, ast_filestream::f, ast_frame_subclass::format, ast_filestream::fr, G723_MAX_SIZE, LOG_WARNING, NULL, ast_frame::ptr, ast_frame::samples, and ast_frame::subclass.
 {
    unsigned short size;
    size_t res;
    int delay;
    /* Read the delay for the next packet, and schedule again if necessary */
    /* XXX is this ignored ? */
    if (fread(&delay, 1, 4, s->f) == 4)
       delay = ntohl(delay);
    else
       delay = -1;
    if (fread(&size, 1, 2, s->f) != 2) {
       /* Out of data, or the file is no longer valid.  In any case
          go ahead and stop the stream */
       return NULL;
    }
    /* Looks like we have a frame to read from here */
    size = ntohs(size);
    if (size > G723_MAX_SIZE) {
       ast_log(LOG_WARNING, "Size %d is invalid\n", size);
       /* The file is apparently no longer any good, as we
          shouldn't ever get frames even close to this
          size.  */
       return NULL;
    }
    /* Read the data into the buffer */
    AST_FRAME_SET_BUFFER(&s->fr, s->buf, AST_FRIENDLY_OFFSET, size);
    if ((res = fread(s->fr.data.ptr, 1, s->fr.datalen, s->f)) != s->fr.datalen) {
       if (res) {
          ast_log(LOG_WARNING, "Short read of %s data (expected %d bytes, read %zu): %s\n",
                ast_format_get_name(s->fr.subclass.format), s->fr.datalen, res,
                strerror(errno));
       }
       return NULL;
    }
    *whennext = s->fr.samples = 240;
    return &s->fr;
 }
g723_seek()
static int g723_seek (struct ast_filestream * fs, off_t sample_offset, int whence) static
Definition at line 106 of file format_g723.c.
 {
    return -1;
 }
g723_tell()
static off_t g723_tell (struct ast_filestream * fs) static
Definition at line 128 of file format_g723.c.
 {
    return -1;
 }
g723_trunc()
static int g723_trunc (struct ast_filestream * fs) static
Definition at line 111 of file format_g723.c.
References ast_log, AST_LOG_WARNING, errno, and ast_filestream::f.
 {
    int fd;
    off_t cur;
    if ((fd = fileno(fs->f)) < 0) {
       ast_log(AST_LOG_WARNING, "Unable to determine file descriptor for g723 filestream %p: %s\n", fs, strerror(errno));
       return -1;
    }
    if ((cur = ftello(fs->f)) < 0) {
       ast_log(AST_LOG_WARNING, "Unable to determine current position in g723 filestream %p: %s\n", fs, strerror(errno));
       return -1;
    }
    /* Truncate file to current length */
    return ftruncate(fd, cur);
 }
g723_write()
static int g723_write (struct ast_filestream * s, struct ast_frame * f) static
Definition at line 79 of file format_g723.c.
References ast_log, ast_frame::data, ast_frame::datalen, errno, ast_filestream::f, LOG_WARNING, and ast_frame::ptr.
 {
    uint32_t delay;
    uint16_t size;
    int res;
    /* XXX there used to be a check s->fr means a read stream */
    delay = 0;
    if (f->datalen <= 0) {
       ast_log(LOG_WARNING, "Short frame ignored (%d bytes long?)\n", f->datalen);
       return 0;
    }
    if ((res = fwrite(&delay, 1, 4, s->f)) != 4) {
       ast_log(LOG_WARNING, "Unable to write delay: res=%d (%s)\n", res, strerror(errno));
       return -1;
    }
    size = htons(f->datalen);
    if ((res = fwrite(&size, 1, 2, s->f)) != 2) {
       ast_log(LOG_WARNING, "Unable to write size: res=%d (%s)\n", res, strerror(errno));
       return -1;
    }
    if ((res = fwrite(f->data.ptr, 1, f->datalen, s->f)) != f->datalen) {
       ast_log(LOG_WARNING, "Unable to write frame: res=%d (%s)\n", res, strerror(errno));
       return -1;
    }
    return 0;
 }
load_module()
static int load_module (void) static
Definition at line 144 of file format_g723.c.
References ast_format_def_register, ast_format_g723, AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, and ast_format_def::format.
Referenced by unload_module().
 {
    g723_1_f.format = ast_format_g723;
    if (ast_format_def_register(&g723_1_f))
       return AST_MODULE_LOAD_DECLINE;
    return AST_MODULE_LOAD_SUCCESS;
 }
unload_module()
static int unload_module (void) static
Definition at line 153 of file format_g723.c.
References ast_format_def_unregister(), AST_MODFLAG_LOAD_ORDER, AST_MODPRI_APP_DEPEND, AST_MODULE_INFO(), AST_MODULE_SUPPORT_CORE, ASTERISK_GPL_KEY, load_module(), and ast_format_def::name.
 {
    return ast_format_def_unregister(g723_1_f.name);
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "G.723.1 Simple Timestamp File Format" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_APP_DEPEND } static
Definition at line 163 of file format_g723.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 163 of file format_g723.c.
g723_1_f
struct ast_format_def g723_1_f static
Definition at line 133 of file format_g723.c.