Asterisk - The Open Source Telephony Project: resource_applications.h File Reference
resource_applications.h File Reference
Generated file - declares stubs to be implemented in res/ari/resource_applications.c.
#include "asterisk/ari.h"
Data Structures
struct ast_ari_applications_filter_args
struct ast_ari_applications_get_args
struct ast_ari_applications_list_args
struct ast_ari_applications_subscribe_args
struct ast_ari_applications_unsubscribe_args
Functions
void ast_ari_applications_filter (struct ast_variable *headers, struct ast_ari_applications_filter_args *args, struct ast_ari_response *response)
Filter application events types.
int ast_ari_applications_filter_parse_body (struct ast_json *body, struct ast_ari_applications_filter_args *args)
Body parsing function for /applications/{applicationName}/eventFilter.
void ast_ari_applications_get (struct ast_variable *headers, struct ast_ari_applications_get_args *args, struct ast_ari_response *response)
Get details of an application.
void ast_ari_applications_list (struct ast_variable *headers, struct ast_ari_applications_list_args *args, struct ast_ari_response *response)
List all applications.
void ast_ari_applications_subscribe (struct ast_variable *headers, struct ast_ari_applications_subscribe_args *args, struct ast_ari_response *response)
Subscribe an application to a event source.
int ast_ari_applications_subscribe_parse_body (struct ast_json *body, struct ast_ari_applications_subscribe_args *args)
Body parsing function for /applications/{applicationName}/subscription.
void ast_ari_applications_unsubscribe (struct ast_variable *headers, struct ast_ari_applications_unsubscribe_args *args, struct ast_ari_response *response)
Unsubscribe an application from an event source.
int ast_ari_applications_unsubscribe_parse_body (struct ast_json *body, struct ast_ari_applications_unsubscribe_args *args)
Body parsing function for /applications/{applicationName}/subscription.
Detailed Description
Generated file - declares stubs to be implemented in res/ari/resource_applications.c.
Stasis application resources
Author
David M. Lee, II dlee@.nosp@m.digi.nosp@m.um.co.nosp@m.m
Definition in file resource_applications.h.
Function Documentation
ast_ari_applications_filter()
void ast_ari_applications_filter (struct ast_variable * headers, struct ast_ari_applications_filter_args * args, struct ast_ari_response * response)
Filter application events types.
Allowed and/or disallowed event type filtering can be done. The body (parameter) should specify a JSON key/value object that describes the type of event filtering needed. One, or both of the following keys can be designated:
"allowed" - Specifies an allowed list of event types
"disallowed" - Specifies a disallowed list of event types
Further, each of those key's value should be a JSON array that holds zero, or more JSON key/value objects. Each of these objects must contain the following key with an associated value:
"type" - The type name of the event to filter
The value must be the string name (case sensitive) of the event type that needs filtering. For example:
{ "allowed": [ { "type": "StasisStart" }, { "type": "StasisEnd" } ] }
As this specifies only an allowed list, then only those two event type messages are sent to the application. No other event messages are sent.
The following rules apply:
* If the body is empty, both the allowed and disallowed filters are set empty.
* If both list types are given then both are set to their respective values (note, specifying an empty array for a given type sets that type to empty).
* If only one list type is given then only that type is set. The other type is not updated.
* An empty "allowed" list means all events are allowed.
* An empty "disallowed" list means no events are disallowed.
* Disallowed events take precedence over allowed events if the event type is specified in both lists.
Parameters
headers HTTP headers
args Swagger parameters
[out] response HTTP response
Definition at line 172 of file resource_applications.c.
References ao2_ref, app, ast_ari_applications_filter_args::application_name, ast_ari_response_error(), ast_ari_response_ok(), ast_ari_applications_filter_args::filter, stasis_app_event_filter_set(), stasis_app_get_by_name(), and stasis_app_object_to_json().
Referenced by ast_ari_applications_filter_cb().
 {
    struct stasis_app *app = stasis_app_get_by_name(args->application_name);
    if (!app) {
       ast_ari_response_error(response, 404, "Not Found", "Application not found");
       return;
    }
    if (stasis_app_event_filter_set(app, args->filter)) {
       ast_ari_response_error(response, 400, "Bad Request", "Invalid format definition");
    } else {
       ast_ari_response_ok(response, stasis_app_object_to_json(app));
    }
    ao2_ref(app, -1);
 }
ast_ari_applications_filter_parse_body()
int ast_ari_applications_filter_parse_body (struct ast_json * body, struct ast_ari_applications_filter_args * args)
Body parsing function for /applications/{applicationName}/eventFilter.
Parameters
body The JSON body from which to parse parameters.
[out] args The args structure to parse into.
Return values
zero on success
non-zero on failure
Definition at line 462 of file res_ari_applications.c.
 {
    /* Parse query parameters out of it */
    return 0;
 }
ast_ari_applications_get()
void ast_ari_applications_get (struct ast_variable * headers, struct ast_ari_applications_get_args * args, struct ast_ari_response * response)
Get details of an application.
Parameters
headers HTTP headers
args Swagger parameters
[out] response HTTP response
Definition at line 72 of file resource_applications.c.
References ast_ari_applications_get_args::application_name, ast_ari_response_error(), ast_ari_response_ok(), and stasis_app_to_json().
Referenced by ast_ari_applications_get_cb().
 {
    struct ast_json *json;
    json = stasis_app_to_json(args->application_name);
    if (!json) {
       ast_ari_response_error(response, 404, "Not Found",
          "Application not found");
       return;
    }
    ast_ari_response_ok(response, json);
 }
ast_ari_applications_list()
void ast_ari_applications_list (struct ast_variable * headers, struct ast_ari_applications_list_args * args, struct ast_ari_response * response)
List all applications.
Parameters
headers HTTP headers
args Swagger parameters
[out] response HTTP response
Definition at line 42 of file resource_applications.c.
References ao2_callback, ao2_cleanup, ao2_container_count(), ao2_lock, ao2_unlock, append_json(), ast_ari_response_error(), ast_ari_response_ok(), ast_json_array_create(), ast_json_array_size(), ast_json_ref(), ast_json_unref(), NULL, OBJ_NODATA, OBJ_NOLOCK, RAII_VAR, and stasis_app_get_all().
Referenced by ast_ari_applications_list_cb().
 {
    RAII_VAR(struct ao2_container *, apps, NULL, ao2_cleanup);
    RAII_VAR(struct ast_json *, json, NULL, ast_json_unref);
    size_t count;
    apps = stasis_app_get_all();
    json = ast_json_array_create();
    if (!apps || !json) {
       ast_ari_response_error(response, 500, "Internal Server Error",
          "Allocation failed");
       return;
    }
    ao2_lock(apps);
    count = ao2_container_count(apps);
    ao2_callback(apps, OBJ_NOLOCK | OBJ_NODATA, append_json, json);
    ao2_unlock(apps);
    if (count != ast_json_array_size(json)) {
       ast_ari_response_error(response, 500, "Internal Server Error",
          "Allocation failed");
       return;
    }
    ast_ari_response_ok(response, ast_json_ref(json));
 }
ast_ari_applications_subscribe()
void ast_ari_applications_subscribe (struct ast_variable * headers, struct ast_ari_applications_subscribe_args * args, struct ast_ari_response * response)
Subscribe an application to a event source.
Returns the state of the application after the subscriptions have changed
Parameters
headers HTTP headers
args Swagger parameters
[out] response HTTP response
Definition at line 89 of file resource_applications.c.
References ast_ari_applications_subscribe_args::application_name, ast_ari_response_error(), ast_ari_response_ok(), ast_json_ref(), ast_json_unref(), ast_strlen_zero, ast_ari_applications_subscribe_args::event_source, ast_ari_applications_subscribe_args::event_source_count, NULL, RAII_VAR, stasis_app_subscribe(), STASIS_ASR_APP_NOT_FOUND, STASIS_ASR_EVENT_SOURCE_BAD_SCHEME, STASIS_ASR_EVENT_SOURCE_NOT_FOUND, STASIS_ASR_INTERNAL_ERROR, and STASIS_ASR_OK.
Referenced by ast_ari_applications_subscribe_cb().
 {
    RAII_VAR(struct ast_json *, json, NULL, ast_json_unref);
    enum stasis_app_subscribe_res res;
    if (args->event_source_count <= 0) {
       ast_ari_response_error(response, 400, "Bad Request",
          "Missing parameter eventSource");
       return;
    }
    if (ast_strlen_zero(args->application_name)) {
       ast_ari_response_error(response, 400, "Bad Request",
          "Missing parameter applicationName");
       return;
    }
    res = stasis_app_subscribe(args->application_name, args->event_source,
       args->event_source_count, &json);
    switch (res) {
    case STASIS_ASR_OK:
       ast_ari_response_ok(response, ast_json_ref(json));
       break;
    case STASIS_ASR_APP_NOT_FOUND:
       ast_ari_response_error(response, 404, "Not Found",
          "Application not found");
       break;
    case STASIS_ASR_EVENT_SOURCE_NOT_FOUND:
       ast_ari_response_error(response, 422, "Unprocessable Entity",
          "Event source does not exist");
       break;
    case STASIS_ASR_EVENT_SOURCE_BAD_SCHEME:
       ast_ari_response_error(response, 400, "Bad Request",
          "Invalid event source URI scheme");
       break;
    case STASIS_ASR_INTERNAL_ERROR:
       ast_ari_response_error(response, 500, "Internal Server Error",
          "Error processing request");
       break;
    }
 }
ast_ari_applications_subscribe_parse_body()
int ast_ari_applications_subscribe_parse_body (struct ast_json * body, struct ast_ari_applications_subscribe_args * args)
Body parsing function for /applications/{applicationName}/subscription.
Parameters
body The JSON body from which to parse parameters.
[out] args The args structure to parse into.
Return values
zero on success
non-zero on failure
Definition at line 161 of file res_ari_applications.c.
References ast_free, AST_JSON_ARRAY, ast_json_array_get(), ast_json_array_size(), ast_json_object_get(), ast_json_string_get(), ast_json_typeof(), ast_malloc, ast_ari_applications_subscribe_args::event_source, and ast_ari_applications_subscribe_args::event_source_count.
Referenced by ast_ari_applications_subscribe_cb().
 {
    struct ast_json *field;
    /* Parse query parameters out of it */
    field = ast_json_object_get(body, "eventSource");
    if (field) {
       /* If they were silly enough to both pass in a query param and a
        * JSON body, free up the query value.
        */
       ast_free(args->event_source);
       if (ast_json_typeof(field) == AST_JSON_ARRAY) {
          /* Multiple param passed as array */
          size_t i;
          args->event_source_count = ast_json_array_size(field);
          args->event_source = ast_malloc(sizeof(*args->event_source) * args->event_source_count);
          if (!args->event_source) {
             return -1;
          }
          for (i = 0; i < args->event_source_count; ++i) {
             args->event_source[i] = ast_json_string_get(ast_json_array_get(field, i));
          }
       } else {
          /* Multiple param passed as single value */
          args->event_source_count = 1;
          args->event_source = ast_malloc(sizeof(*args->event_source) * args->event_source_count);
          if (!args->event_source) {
             return -1;
          }
          args->event_source[0] = ast_json_string_get(field);
       }
    }
    return 0;
 }
ast_ari_applications_unsubscribe()
void ast_ari_applications_unsubscribe (struct ast_variable * headers, struct ast_ari_applications_unsubscribe_args * args, struct ast_ari_response * response)
Unsubscribe an application from an event source.
Returns the state of the application after the subscriptions have changed
Parameters
headers HTTP headers
args Swagger parameters
[out] response HTTP response
Definition at line 134 of file resource_applications.c.
References ast_ari_applications_unsubscribe_args::application_name, ast_ari_response_error(), ast_ari_response_ok(), ast_json_ref(), ast_json_unref(), ast_ari_applications_unsubscribe_args::event_source, ast_ari_applications_unsubscribe_args::event_source_count, NULL, RAII_VAR, stasis_app_unsubscribe(), STASIS_ASR_APP_NOT_FOUND, STASIS_ASR_EVENT_SOURCE_BAD_SCHEME, STASIS_ASR_EVENT_SOURCE_NOT_FOUND, STASIS_ASR_INTERNAL_ERROR, and STASIS_ASR_OK.
Referenced by ast_ari_applications_unsubscribe_cb().
 {
    RAII_VAR(struct ast_json *, json, NULL, ast_json_unref);
    enum stasis_app_subscribe_res res;
    if (args->event_source_count == 0) {
       ast_ari_response_error(response, 400, "Bad Request",
          "Missing parameter eventSource");
       return;
    }
    res = stasis_app_unsubscribe(args->application_name, args->event_source,
       args->event_source_count, &json);
    switch (res) {
    case STASIS_ASR_OK:
       ast_ari_response_ok(response, ast_json_ref(json));
       break;
    case STASIS_ASR_APP_NOT_FOUND:
       ast_ari_response_error(response, 404, "Not Found",
          "Application not found");
       break;
    case STASIS_ASR_EVENT_SOURCE_NOT_FOUND:
       ast_ari_response_error(response, 422, "Unprocessable Entity",
          "Event source was not subscribed to");
       break;
    case STASIS_ASR_EVENT_SOURCE_BAD_SCHEME:
       ast_ari_response_error(response, 400, "Bad Request",
          "Invalid event source URI scheme");
       break;
    case STASIS_ASR_INTERNAL_ERROR:
       ast_ari_response_error(response, 500, "Internal Server Error",
          "Error processing request");
    }
 }
ast_ari_applications_unsubscribe_parse_body()
int ast_ari_applications_unsubscribe_parse_body (struct ast_json * body, struct ast_ari_applications_unsubscribe_args * args)
Body parsing function for /applications/{applicationName}/subscription.
Parameters
body The JSON body from which to parse parameters.
[out] args The args structure to parse into.
Return values
zero on success
non-zero on failure
Definition at line 311 of file res_ari_applications.c.
References ast_free, AST_JSON_ARRAY, ast_json_array_get(), ast_json_array_size(), ast_json_object_get(), ast_json_string_get(), ast_json_typeof(), ast_malloc, ast_ari_applications_unsubscribe_args::event_source, and ast_ari_applications_unsubscribe_args::event_source_count.
Referenced by ast_ari_applications_unsubscribe_cb().
 {
    struct ast_json *field;
    /* Parse query parameters out of it */
    field = ast_json_object_get(body, "eventSource");
    if (field) {
       /* If they were silly enough to both pass in a query param and a
        * JSON body, free up the query value.
        */
       ast_free(args->event_source);
       if (ast_json_typeof(field) == AST_JSON_ARRAY) {
          /* Multiple param passed as array */
          size_t i;
          args->event_source_count = ast_json_array_size(field);
          args->event_source = ast_malloc(sizeof(*args->event_source) * args->event_source_count);
          if (!args->event_source) {
             return -1;
          }
          for (i = 0; i < args->event_source_count; ++i) {
             args->event_source[i] = ast_json_string_get(ast_json_array_get(field, i));
          }
       } else {
          /* Multiple param passed as single value */
          args->event_source_count = 1;
          args->event_source = ast_malloc(sizeof(*args->event_source) * args->event_source_count);
          if (!args->event_source) {
             return -1;
          }
          args->event_source[0] = ast_json_string_get(field);
       }
    }
    return 0;
 }