Asterisk - The Open Source Telephony Project: ast_rtp_engine_dtls Struct Reference
ast_rtp_engine_dtls Struct Reference
Structure that represents the optional DTLS SRTP support within an RTP engine.
#include <rtp_engine.h>
Data Fields
int(* active)(struct ast_rtp_instance *instance)
enum ast_rtp_dtls_connection(* get_connection)(struct ast_rtp_instance *instance)
const char *(* get_fingerprint)(struct ast_rtp_instance *instance)
enum ast_rtp_dtls_hash(* get_fingerprint_hash)(struct ast_rtp_instance *instance)
enum ast_rtp_dtls_setup(* get_setup)(struct ast_rtp_instance *instance)
void(* reset)(struct ast_rtp_instance *instance)
int(* set_configuration)(struct ast_rtp_instance *instance, const struct ast_rtp_dtls_cfg *dtls_cfg)
void(* set_fingerprint)(struct ast_rtp_instance *instance, enum ast_rtp_dtls_hash hash, const char *fingerprint)
void(* set_setup)(struct ast_rtp_instance *instance, enum ast_rtp_dtls_setup setup)
void(* stop)(struct ast_rtp_instance *instance)
Detailed Description
Structure that represents the optional DTLS SRTP support within an RTP engine.
Definition at line 570 of file rtp_engine.h.
Field Documentation
active
int(* active) (struct ast_rtp_instance *instance)
Get if the DTLS SRTP support is active or not
Definition at line 574 of file rtp_engine.h.
Referenced by add_dtls_to_sdp(), ast_sdp_get_rtp_profile(), process_sdp(), and rtp_dtls_wrap_active().
get_connection
enum ast_rtp_dtls_connection(* get_connection) (struct ast_rtp_instance *instance)
Get the current connection state
Definition at line 580 of file rtp_engine.h.
Referenced by add_crypto_to_stream(), add_dtls_to_sdp(), and rtp_dtls_wrap_get_connection().
get_fingerprint
const char*(* get_fingerprint) (struct ast_rtp_instance *instance)
Get the local fingerprint
Definition at line 590 of file rtp_engine.h.
Referenced by add_crypto_to_stream(), add_dtls_to_sdp(), and rtp_dtls_wrap_get_fingerprint().
get_fingerprint_hash
enum ast_rtp_dtls_hash(* get_fingerprint_hash) (struct ast_rtp_instance *instance)
Get the local fingerprint hash type
Definition at line 588 of file rtp_engine.h.
Referenced by add_crypto_to_stream(), add_dtls_to_sdp(), and rtp_dtls_wrap_get_fingerprint_hash().
get_setup
enum ast_rtp_dtls_setup(* get_setup) (struct ast_rtp_instance *instance)
Get the current setup state
Definition at line 582 of file rtp_engine.h.
Referenced by add_crypto_to_stream(), add_dtls_to_sdp(), and rtp_dtls_wrap_get_setup().
reset
void(* reset) (struct ast_rtp_instance *instance)
Reset the connection and start fresh
Definition at line 578 of file rtp_engine.h.
Referenced by apply_dtls_attrib(), process_sdp_a_dtls(), and rtp_dtls_wrap_reset().
set_configuration
int(* set_configuration) (struct ast_rtp_instance *instance, const struct ast_rtp_dtls_cfg *dtls_cfg)
Set the configuration of the DTLS support on the instance
Definition at line 572 of file rtp_engine.h.
Referenced by dialog_initialize_dtls_srtp(), rtp_dtls_wrap_set_configuration(), and setup_dtls_srtp().
set_fingerprint
void(* set_fingerprint) (struct ast_rtp_instance *instance, enum ast_rtp_dtls_hash hash, const char *fingerprint)
Set the remote fingerprint
Definition at line 586 of file rtp_engine.h.
Referenced by apply_dtls_attrib(), process_sdp_a_dtls(), and rtp_dtls_wrap_set_fingerprint().
set_setup
void(* set_setup) (struct ast_rtp_instance *instance, enum ast_rtp_dtls_setup setup)
Set the remote setup state
Definition at line 584 of file rtp_engine.h.
Referenced by apply_dtls_attrib(), process_sdp_a_dtls(), and rtp_dtls_wrap_set_setup().
stop
void(* stop) (struct ast_rtp_instance *instance)
Stop and terminate DTLS SRTP support
Definition at line 576 of file rtp_engine.h.
Referenced by process_crypto(), and rtp_dtls_wrap_stop().
The documentation for this struct was generated from the following file:
rtp_engine.h