Asterisk - The Open Source Telephony Project: resource_playbacks.h File Reference
resource_playbacks.h File Reference
Generated file - declares stubs to be implemented in res/ari/resource_playbacks.c.
#include "asterisk/ari.h"
Data Structures
struct ast_ari_playbacks_control_args
struct ast_ari_playbacks_get_args
struct ast_ari_playbacks_stop_args
Functions
void ast_ari_playbacks_control (struct ast_variable *headers, struct ast_ari_playbacks_control_args *args, struct ast_ari_response *response)
Control a playback.
int ast_ari_playbacks_control_parse_body (struct ast_json *body, struct ast_ari_playbacks_control_args *args)
Body parsing function for /playbacks/{playbackId}/control.
void ast_ari_playbacks_get (struct ast_variable *headers, struct ast_ari_playbacks_get_args *args, struct ast_ari_response *response)
Get a playback's details.
void ast_ari_playbacks_stop (struct ast_variable *headers, struct ast_ari_playbacks_stop_args *args, struct ast_ari_response *response)
Stop a playback.
Detailed Description
Generated file - declares stubs to be implemented in res/ari/resource_playbacks.c.
Playback control resources
Author
David M. Lee, II dlee@.nosp@m.digi.nosp@m.um.co.nosp@m.m
Definition in file resource_playbacks.h.
Function Documentation
ast_ari_playbacks_control()
void ast_ari_playbacks_control (struct ast_variable * headers, struct ast_ari_playbacks_control_args * args, struct ast_ari_response * response)
Control a playback.
Parameters
headers HTTP headers
args Swagger parameters
[out] response HTTP response
Definition at line 89 of file resource_playbacks.c.
References ao2_cleanup, ast_ari_response_error(), ast_ari_response_no_content(), NULL, ast_ari_playbacks_control_args::operation, ast_ari_playbacks_control_args::playback_id, RAII_VAR, stasis_app_playback_find_by_id(), stasis_app_playback_operation(), STASIS_PLAYBACK_FORWARD, STASIS_PLAYBACK_OPER_FAILED, STASIS_PLAYBACK_OPER_NOT_PLAYING, STASIS_PLAYBACK_OPER_OK, STASIS_PLAYBACK_PAUSE, STASIS_PLAYBACK_RESTART, STASIS_PLAYBACK_REVERSE, and STASIS_PLAYBACK_UNPAUSE.
Referenced by ast_ari_playbacks_control_cb().
 {
    RAII_VAR(struct stasis_app_playback *, playback, NULL, ao2_cleanup);
    enum stasis_app_playback_media_operation oper;
    enum stasis_playback_oper_results res;
    if (!args->operation) {
       ast_ari_response_error(response, 400,
          "Bad Request", "Missing operation");
       return;
    }
    if (strcmp(args->operation, "unpause") == 0) {
       oper = STASIS_PLAYBACK_UNPAUSE;
    } else if (strcmp(args->operation, "pause") == 0) {
       oper = STASIS_PLAYBACK_PAUSE;
    } else if (strcmp(args->operation, "restart") == 0) {
       oper = STASIS_PLAYBACK_RESTART;
    } else if (strcmp(args->operation, "reverse") == 0) {
       oper = STASIS_PLAYBACK_REVERSE;
    } else if (strcmp(args->operation, "forward") == 0) {
       oper = STASIS_PLAYBACK_FORWARD;
    } else {
       ast_ari_response_error(response, 400,
          "Bad Request", "Invalid operation %s",
          args->operation);
       return;
    }
    playback = stasis_app_playback_find_by_id(args->playback_id);
    if (playback == NULL) {
       ast_ari_response_error(response, 404, "Not Found",
          "Playback not found");
       return;
    }
    res = stasis_app_playback_operation(playback, oper);
    switch (res) {
    case STASIS_PLAYBACK_OPER_OK:
       ast_ari_response_no_content(response);
       return;
    case STASIS_PLAYBACK_OPER_FAILED:
       ast_ari_response_error(response, 500,
          "Internal Server Error", "Could not %s playback",
          args->operation);
       return;
    case STASIS_PLAYBACK_OPER_NOT_PLAYING:
       ast_ari_response_error(response, 409, "Conflict",
          "Can only %s while media is playing", args->operation);
       return;
    }
 }
ast_ari_playbacks_control_parse_body()
int ast_ari_playbacks_control_parse_body (struct ast_json * body, struct ast_ari_playbacks_control_args * args)
Body parsing function for /playbacks/{playbackId}/control.
Parameters
body The JSON body from which to parse parameters.
[out] args The args structure to parse into.
Return values
zero on success
non-zero on failure
Definition at line 170 of file res_ari_playbacks.c.
References ast_json_object_get(), ast_json_string_get(), and ast_ari_playbacks_control_args::operation.
Referenced by ast_ari_playbacks_control_cb().
 {
    struct ast_json *field;
    /* Parse query parameters out of it */
    field = ast_json_object_get(body, "operation");
    if (field) {
       args->operation = ast_json_string_get(field);
    }
    return 0;
 }
ast_ari_playbacks_get()
void ast_ari_playbacks_get (struct ast_variable * headers, struct ast_ari_playbacks_get_args * args, struct ast_ari_response * response)
Get a playback's details.
Parameters
headers HTTP headers
args Swagger parameters
[out] response HTTP response
Definition at line 35 of file resource_playbacks.c.
References ao2_cleanup, ast_ari_response_error(), ast_ari_response_ok(), NULL, ast_ari_playbacks_get_args::playback_id, RAII_VAR, stasis_app_playback_find_by_id(), and stasis_app_playback_to_json().
Referenced by ast_ari_playbacks_get_cb().
 {
    RAII_VAR(struct stasis_app_playback *, playback, NULL, ao2_cleanup);
    struct ast_json *json;
    playback = stasis_app_playback_find_by_id(args->playback_id);
    if (playback == NULL) {
       ast_ari_response_error(response, 404, "Not Found",
          "Playback not found");
       return;
    }
    json = stasis_app_playback_to_json(playback);
    if (json == NULL) {
       ast_ari_response_error(response, 500,
          "Internal Server Error", "Error building response");
       return;
    }
    ast_ari_response_ok(response, json);
 }
ast_ari_playbacks_stop()
void ast_ari_playbacks_stop (struct ast_variable * headers, struct ast_ari_playbacks_stop_args * args, struct ast_ari_response * response)
Stop a playback.
Parameters
headers HTTP headers
args Swagger parameters
[out] response HTTP response
Definition at line 58 of file resource_playbacks.c.
References ao2_cleanup, ast_ari_response_error(), ast_ari_response_no_content(), ast_assert, NULL, ast_ari_playbacks_stop_args::playback_id, RAII_VAR, stasis_app_playback_find_by_id(), stasis_app_playback_operation(), STASIS_PLAYBACK_OPER_FAILED, STASIS_PLAYBACK_OPER_NOT_PLAYING, STASIS_PLAYBACK_OPER_OK, and STASIS_PLAYBACK_STOP.
Referenced by ast_ari_playbacks_stop_cb().
 {
    RAII_VAR(struct stasis_app_playback *, playback, NULL, ao2_cleanup);
    enum stasis_playback_oper_results res;
    playback = stasis_app_playback_find_by_id(args->playback_id);
    if (playback == NULL) {
       ast_ari_response_error(response, 404, "Not Found",
          "Playback not found");
       return;
    }
    res = stasis_app_playback_operation(playback, STASIS_PLAYBACK_STOP);
    switch (res) {
    case STASIS_PLAYBACK_OPER_OK:
       ast_ari_response_no_content(response);
       return;
    case STASIS_PLAYBACK_OPER_FAILED:
       ast_ari_response_error(response, 500,
          "Internal Server Error", "Could not stop playback");
       return;
    case STASIS_PLAYBACK_OPER_NOT_PLAYING:
       /* Stop operation should be valid even when not playing */
       ast_assert(0);
       ast_ari_response_error(response, 500,
          "Internal Server Error", "Could not stop playback");
       return;
    }
 }