Asterisk - The Open Source Telephony Project: version.c File Reference
version.c File Reference
#include "asterisk.h"
#include "asterisk/ast_version.h"
Functions
const char * ast_get_build_opts (void)
const char * ast_get_version (void)
Retrieve the Asterisk version string.
const char * ast_get_version_num (void)
Retrieve the numeric Asterisk version.
Variables
static const char asterisk_build_opts [] = "AST_DEVMODE, DONT_OPTIMIZE, COMPILE_DOUBLE, DEBUG_THREADS, BETTER_BACKTRACES, BUILD_NATIVE, OPTIONAL_API, TEST_FRAMEWORK"
static const char asterisk_version [] = "18.5.0"
static const char asterisk_version_num [] = "180500"
Function Documentation
ast_get_build_opts()
const char* ast_get_build_opts (void)
Retrieve the Asterisk build options
Definition at line 26 of file version.c.
References asterisk_build_opts.
Referenced by handle_show_settings(), and prometheus_config_post_apply().
 {
    return asterisk_build_opts;
 }
ast_get_version()
const char* ast_get_version (void)
Retrieve the Asterisk version string.
Definition at line 16 of file version.c.
References asterisk_version.
Referenced by __ast_http_load(), acf_version_exec(), action_coresettings(), ast_ari_asterisk_get_info(), ast_dump_locks(), ast_sip_initialize_sorcery_global(), ast_var_Version(), cli_fax_show_version(), env_init(), handle_show_settings(), handle_version(), make_logchannel(), netconsole(), prometheus_config_post_apply(), reload_config(), setup_env(), show_cli_help(), show_version(), and test_generate_results().
 {
    return asterisk_version;
 }
ast_get_version_num()
const char* ast_get_version_num (void)
Retrieve the numeric Asterisk version.
Format ABBCC AABB - Major version (1.4 would be 104) CC - Minor version
1.4.17 would be 10417.
Definition at line 21 of file version.c.
References asterisk_version_num.
Referenced by acf_version_exec(), ast_var_Version(), and test_generate_results().
 {
    return asterisk_version_num;
 }
Variable Documentation
asterisk_build_opts
const char asterisk_build_opts[] = "AST_DEVMODE, DONT_OPTIMIZE, COMPILE_DOUBLE, DEBUG_THREADS, BETTER_BACKTRACES, BUILD_NATIVE, OPTIONAL_API, TEST_FRAMEWORK" static
Definition at line 14 of file version.c.
Referenced by ast_get_build_opts().
asterisk_version
const char asterisk_version[] = "18.5.0" static
Definition at line 10 of file version.c.
Referenced by ast_get_version().
asterisk_version_num
const char asterisk_version_num[] = "180500" static
Definition at line 12 of file version.c.
Referenced by ast_get_version_num().