Asterisk - The Open Source Telephony Project: channel_internal.h File Reference
channel_internal.h File Reference
Internal channel functions for channel.c to use.
Macros
#define ast_channel_internal_alloc(destructor, assignedid, requestor) __ast_channel_internal_alloc(destructor, assignedid, requestor, __FILE__, __LINE__, __PRETTY_FUNCTION__)
Functions
struct ast_channel * __ast_channel_internal_alloc (void(*destructor)(void *obj), const struct ast_assigned_ids *assignedids, const struct ast_channel *requestor, const char *file, int line, const char *function)
void ast_channel_internal_cleanup (struct ast_channel *chan)
enum ast_channel_error ast_channel_internal_errno (void)
void ast_channel_internal_errno_set (enum ast_channel_error error)
void ast_channel_internal_finalize (struct ast_channel *chan)
int ast_channel_internal_is_finalized (struct ast_channel *chan)
void ast_channel_internal_set_stream_topology (struct ast_channel *chan, struct ast_stream_topology *topology)
void ast_channel_internal_set_stream_topology_change_source (struct ast_channel *chan, void *change_source)
int ast_channel_internal_setup_topics (struct ast_channel *chan)
void ast_channel_internal_swap_stream_topology (struct ast_channel *chan1, struct ast_channel *chan2)
Detailed Description
Internal channel functions for channel.c to use.
Definition in file channel_internal.h.
Macro Definition Documentation
ast_channel_internal_alloc
#define ast_channel_internal_alloc (destructor, assignedid, requestor) __ast_channel_internal_alloc(destructor, assignedid, requestor, __FILE__, __LINE__, __PRETTY_FUNCTION__)
Definition at line 24 of file channel_internal.h.
Function Documentation
__ast_channel_internal_alloc()
struct ast_channel* __ast_channel_internal_alloc (void(*)(void *obj) destructor, const struct ast_assigned_ids * assignedids, const struct ast_channel * requestor, const char * file, int line, const char * function)
Definition at line 1331 of file channel_internal_api.c.
References __ao2_alloc(), AO2_ALLOC_OPT_LOCK_MUTEX, ao2_container_alloc_hash, ast_atomic_fetchadd_int(), ast_channel_unref, ast_config_AST_SYSTEM_NAME, ast_copy_string(), AST_FLAGS_ALL, AST_MAX_FDS, ast_set_flag, ast_string_field_init, ast_strlen_zero, AST_VECTOR_INIT, ast_channel_id::creation_time, ast_channel_id::creation_unique, ast_channel::dialed_causes, DIALED_CAUSES_BUCKETS, ast_channel::linkedid, NULL, pvt_cause_cmp_fn(), pvt_cause_hash_fn(), tmp(), ast_channel_id::unique_id, ast_channel::uniqueid, and ast_assigned_ids::uniqueid.
Referenced by __ast_channel_alloc_ap(), and __ast_dummy_channel_alloc().
 {
    struct ast_channel *tmp;
    tmp = __ao2_alloc(sizeof(*tmp), destructor,
       AO2_ALLOC_OPT_LOCK_MUTEX, "", file, line, function);
    if (!tmp) {
       return NULL;
    }
    if ((ast_string_field_init(tmp, 128))) {
       return ast_channel_unref(tmp);
    }
    tmp->dialed_causes = ao2_container_alloc_hash(AO2_ALLOC_OPT_LOCK_MUTEX, 0,
       DIALED_CAUSES_BUCKETS, pvt_cause_hash_fn, NULL, pvt_cause_cmp_fn);
    if (!tmp->dialed_causes) {
       return ast_channel_unref(tmp);
    }
    /* set the creation time in the uniqueid */
    tmp->uniqueid.creation_time = time(NULL);
    tmp->uniqueid.creation_unique = ast_atomic_fetchadd_int(&uniqueint, 1);
    /* use provided id or default to historical {system-}time.# format */
    if (assignedids && !ast_strlen_zero(assignedids->uniqueid)) {
       ast_copy_string(tmp->uniqueid.unique_id, assignedids->uniqueid, sizeof(tmp->uniqueid.unique_id));
    } else if (ast_strlen_zero(ast_config_AST_SYSTEM_NAME)) {
       snprintf(tmp->uniqueid.unique_id, sizeof(tmp->uniqueid.unique_id), "%li.%d",
          (long)(tmp->uniqueid.creation_time),
          tmp->uniqueid.creation_unique);
    } else {
       snprintf(tmp->uniqueid.unique_id, sizeof(tmp->uniqueid.unique_id), "%s-%li.%d",
          ast_config_AST_SYSTEM_NAME,
          (long)(tmp->uniqueid.creation_time),
          tmp->uniqueid.creation_unique);
    }
    /* copy linked id from parent channel if known */
    if (requestor) {
       tmp->linkedid = requestor->linkedid;
    } else {
       tmp->linkedid = tmp->uniqueid;
    }
    AST_VECTOR_INIT(&tmp->fds, AST_MAX_FDS);
    /* Force all channel snapshot segments to be created on first use, so we don't have to check if
     * an old snapshot exists.
     */
    ast_set_flag(&tmp->snapshot_segment_flags, AST_FLAGS_ALL);
    return tmp;
 }
ast_channel_internal_cleanup()
void ast_channel_internal_cleanup (struct ast_channel * chan)
Definition at line 1471 of file channel_internal_api.c.
References ao2_cleanup, ao2_t_ref, ast_channel_internal_set_stream_topology(), ast_string_field_free_memory, AST_VECTOR_FREE, ast_channel::dialed_causes, NULL, and stasis_forward_cancel().
Referenced by ast_channel_destructor(), and ast_dummy_channel_destructor().
 {
    if (chan->dialed_causes) {
       ao2_t_ref(chan->dialed_causes, -1,
          "done with dialed causes since the channel is going away");
       chan->dialed_causes = NULL;
    }
    ast_string_field_free_memory(chan);
    chan->channel_forward = stasis_forward_cancel(chan->channel_forward);
    chan->endpoint_forward = stasis_forward_cancel(chan->endpoint_forward);
    ao2_cleanup(chan->topic);
    chan->topic = NULL;
    ast_channel_internal_set_stream_topology(chan, NULL);
    AST_VECTOR_FREE(&chan->fds);
 }
ast_channel_internal_errno()
enum ast_channel_error ast_channel_internal_errno (void)
Definition at line 1573 of file channel_internal_api.c.
References AST_CHANNEL_ERROR_UNKNOWN, ast_threadstorage_get(), and channel_errno.
Referenced by ast_channel_errno().
 {
    enum ast_channel_error *error_code = ast_threadstorage_get(&channel_errno, sizeof(*error_code));
    if (!error_code) {
       return AST_CHANNEL_ERROR_UNKNOWN;
    }
    return *error_code;
 }
ast_channel_internal_errno_set()
void ast_channel_internal_errno_set (enum ast_channel_error error)
Definition at line 1563 of file channel_internal_api.c.
References ast_threadstorage_get(), channel_errno, and error().
Referenced by __ast_channel_alloc_ap().
 {
    enum ast_channel_error *error_code = ast_threadstorage_get(&channel_errno, sizeof(*error_code));
    if (!error_code) {
       return;
    }
    *error_code = error;
 }
ast_channel_internal_finalize()
void ast_channel_internal_finalize (struct ast_channel * chan)
Definition at line 1492 of file channel_internal_api.c.
Referenced by __ast_channel_alloc_ap().
 {
    chan->finalized = 1;
 }
ast_channel_internal_is_finalized()
int ast_channel_internal_is_finalized (struct ast_channel * chan)
Definition at line 1497 of file channel_internal_api.c.
Referenced by ast_channel_destructor().
 {
    return chan->finalized;
 }
ast_channel_internal_set_stream_topology()
void ast_channel_internal_set_stream_topology (struct ast_channel * chan, struct ast_stream_topology * topology)
Definition at line 658 of file channel_internal_api.c.
References ast_stream_topology_free(), and channel_set_default_streams().
Referenced by __ast_channel_alloc_ap(), ast_channel_internal_cleanup(), ast_channel_nativeformats_set(), and ast_channel_set_stream_topology().
 {
    ast_stream_topology_free(chan->stream_topology);
    chan->stream_topology = topology;
    channel_set_default_streams(chan);
 }
ast_channel_internal_set_stream_topology_change_source()
void ast_channel_internal_set_stream_topology_change_source (struct ast_channel * chan, void * change_source)
Definition at line 666 of file channel_internal_api.c.
Referenced by ast_channel_request_stream_topology_change(), and ast_channel_stream_topology_changed_externally().
 {
    chan->stream_topology_change_source = change_source;
 }
ast_channel_internal_setup_topics()
int ast_channel_internal_setup_topics (struct ast_channel * chan)
Definition at line 1527 of file channel_internal_api.c.
References ao2_ref, ast_asprintf, ast_assert, ast_atomic_fetchadd_int(), ast_channel_topic(), ast_channel_topic_all(), ast_free, ast_strlen_zero, NULL, stasis_forward_all(), stasis_topic_create(), ast_channel_id::unique_id, and ast_channel::uniqueid.
Referenced by __ast_channel_alloc_ap(), and __ast_dummy_channel_alloc().
 {
    char *topic_name;
    int ret;
    ast_assert(chan->topic == NULL);
    if (ast_strlen_zero(chan->uniqueid.unique_id)) {
       static int dummy_id;
       ret = ast_asprintf(&topic_name, "channel:dummy-%d", ast_atomic_fetchadd_int(&dummy_id, +1));
    } else {
       ret = ast_asprintf(&topic_name, "channel:%s", chan->uniqueid.unique_id);
    }
    if (ret < 0) {
       return -1;
    }
    chan->topic = stasis_topic_create(topic_name);
    ast_free(topic_name);
    if (!chan->topic) {
       return -1;
    }
    chan->channel_forward = stasis_forward_all(ast_channel_topic(chan),
       ast_channel_topic_all());
    if (!chan->channel_forward) {
       ao2_ref(chan->topic, -1);
       chan->topic = NULL;
       return -1;
    }
    return 0;
 }
ast_channel_internal_swap_stream_topology()
void ast_channel_internal_swap_stream_topology (struct ast_channel * chan1, struct ast_channel * chan2)
Definition at line 1628 of file channel_internal_api.c.
References ast_assert, channel_set_default_streams(), and NULL.
Referenced by channel_do_masquerade().
 {
    struct ast_stream_topology *tmp_topology;
    ast_assert(chan1 != NULL && chan2 != NULL);
    tmp_topology = chan1->stream_topology;
    chan1->stream_topology = chan2->stream_topology;
    chan2->stream_topology = tmp_topology;
    channel_set_default_streams(chan1);
    channel_set_default_streams(chan2);
 }