Asterisk - The Open Source Telephony Project: resource_sounds.h File Reference
resource_sounds.h File Reference
Generated file - declares stubs to be implemented in res/ari/resource_sounds.c.
#include "asterisk/ari.h"
Data Structures
struct ast_ari_sounds_get_args
struct ast_ari_sounds_list_args
Functions
void ast_ari_sounds_get (struct ast_variable *headers, struct ast_ari_sounds_get_args *args, struct ast_ari_response *response)
Get a sound's details.
void ast_ari_sounds_list (struct ast_variable *headers, struct ast_ari_sounds_list_args *args, struct ast_ari_response *response)
List all sounds.
int ast_ari_sounds_list_parse_body (struct ast_json *body, struct ast_ari_sounds_list_args *args)
Body parsing function for /sounds.
Detailed Description
Generated file - declares stubs to be implemented in res/ari/resource_sounds.c.
Sound resources
Author
David M. Lee, II dlee@.nosp@m.digi.nosp@m.um.co.nosp@m.m
Definition in file resource_sounds.h.
Function Documentation
ast_ari_sounds_get()
void ast_ari_sounds_get (struct ast_variable * headers, struct ast_ari_sounds_get_args * args, struct ast_ari_response * response)
Get a sound's details.
Parameters
headers HTTP headers
args Swagger parameters
[out] response HTTP response
Definition at line 220 of file resource_sounds.c.
References ao2_cleanup, ast_ari_response_error(), ast_ari_response_ok(), ast_sounds_get_index_for_file(), create_sound_blob(), NULL, and ast_ari_sounds_get_args::sound_id.
Referenced by ast_ari_sounds_get_cb().
 {
    struct ast_json *sound_blob;
    struct ast_media_index *sounds_index = ast_sounds_get_index_for_file(args->sound_id);
    sound_blob = create_sound_blob(args->sound_id, NULL, sounds_index);
    ao2_cleanup(sounds_index);
    if (!sound_blob) {
       ast_ari_response_error(response, 404, "Not Found", "Sound not found");
       return;
    }
    ast_ari_response_ok(response, sound_blob);
 }
ast_ari_sounds_list()
void ast_ari_sounds_list (struct ast_variable * headers, struct ast_ari_sounds_list_args * args, struct ast_ari_response * response)
List all sounds.
Parameters
headers HTTP headers
args Swagger parameters
[out] response HTTP response
Definition at line 180 of file resource_sounds.c.
References ao2_callback_data, ao2_cleanup, append_sound_cb(), args, sounds_cb_data::args, ast_ari_response_error(), ast_ari_response_ok(), ast_json_array_create(), ast_json_array_size(), ast_json_unref(), ast_media_get_media(), ast_sounds_get_index(), NULL, OBJ_NODATA, and RAII_VAR.
Referenced by ast_ari_sounds_list_cb().
 {
    RAII_VAR(struct ao2_container *, sound_files, NULL, ao2_cleanup);
    struct ast_json *sounds_blob;
    RAII_VAR(struct ast_media_index *, sounds_index, ast_sounds_get_index(), ao2_cleanup);
    struct sounds_cb_data cb_data = {
       .args = args,
       .index = sounds_index,
    };
    if (!sounds_index) {
       ast_ari_response_error(response, 500, "Internal Error", "Sounds index not available");
       return;
    }
    sound_files = ast_media_get_media(sounds_index);
    if (!sound_files) {
       ast_ari_response_error(response, 500, "Internal Error", "Allocation Error");
       return;
    }
    sounds_blob = ast_json_array_create();
    if (!sounds_blob) {
       ast_ari_response_error(response, 500, "Internal Error", "Allocation Error");
       return;
    }
    ao2_callback_data(sound_files, OBJ_NODATA, append_sound_cb, sounds_blob, &cb_data);
    if (!ast_json_array_size(sounds_blob)) {
       ast_ari_response_error(response, 404, "Not Found", "No sounds found that matched the query");
       ast_json_unref(sounds_blob);
       return;
    }
    ast_ari_response_ok(response, sounds_blob);
 }
ast_ari_sounds_list_parse_body()
int ast_ari_sounds_list_parse_body (struct ast_json * body, struct ast_ari_sounds_list_args * args)
Body parsing function for /sounds.
Parameters
body The JSON body from which to parse parameters.
[out] args The args structure to parse into.
Return values
zero on success
non-zero on failure
Definition at line 53 of file res_ari_sounds.c.
References ast_json_object_get(), ast_json_string_get(), ast_ari_sounds_list_args::format, and ast_ari_sounds_list_args::lang.
Referenced by ast_ari_sounds_list_cb().
 {
    struct ast_json *field;
    /* Parse query parameters out of it */
    field = ast_json_object_get(body, "lang");
    if (field) {
       args->lang = ast_json_string_get(field);
    }
    field = ast_json_object_get(body, "format");
    if (field) {
       args->format = ast_json_string_get(field);
    }
    return 0;
 }