Asterisk - The Open Source Telephony Project: hash.c File Reference
hash.c File Reference
#include <sys/param.h>
#include <sys/stat.h>
#include <errno.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include "../include/db.h"
#include "hash.h"
#include "page.h"
#include "extern.h"
Macros
#define ABNORMAL (1)
#define ERROR (-1)
#define MOD(x, y) ((x) & ((y) - 1))
#define OLDHASHVERSION 1
#define RETURN_ERROR(ERR, LOC) { save_errno = ERR; goto LOC; }
#define SUCCESS (0)
Functions
u_int32_t __call_hash (HTAB *hashp, char *k, int len)
int __expand_table (HTAB *hashp)
DB * __hash_open (char *file, int flags, int mode, const HASHINFO *info, int dflags) const
static int alloc_segs __P ((HTAB *, int))
static int flush_meta __P ((HTAB *))
static int hash_access __P ((HTAB *, ACTION, DBT *, DBT *))
static int hash_close __P ((DB *))
static int hash_delete __P ((const DB *, const DBT *, u_int32_t))
static int hash_fd __P ((const DB *))
static int hash_get __P ((const DB *, const DBT *, DBT *, u_int32_t))
static void *hash_realloc __P ((SEGMENT **, int, int))
static int hash_seq __P ((const DB *, DBT *, DBT *, u_int32_t))
static int hash_sync __P ((const DB *, u_int32_t))
static HTAB *init_hash __P ((HTAB *, const char *, const HASHINFO *))
static void swap_header_copy __P ((HASHHDR *, HASHHDR *))
static int alloc_segs (HTAB *hashp, int nsegs)
static int flush_meta (HTAB *hashp)
static int hash_access (HTAB *hashp, ACTION action, DBT *key, DBT *val)
static int hash_close (DB *dbp)
static int hash_delete (DB *dbp, const DBT *key, u_int32_t flag) const
static int hash_fd (DB *dbp) const
static int hash_get (DB *dbp, const DBT *key, DBT *data, u_int32_t flag) const
static int hash_put (DB *dbp, DBT *key, const DBT *data, u_int32_t flag) const
static void * hash_realloc (SEGMENT **p_ptr, int oldsize, int newsize)
static int hash_seq (DB *dbp, DBT *key, DBT *data, u_int32_t flag) const
static int hash_sync (DB *dbp, u_int32_t flags) const
static int hdestroy (HTAB *hashp)
static HTAB * init_hash (HTAB *hashp, const char *file, const HASHINFO *info)
static int init_htab (HTAB *hashp, int nelem)
static void swap_header (HTAB *hashp)
static void swap_header_copy (HASHHDR *srcp, HASHHDR *destp)
Macro Definition Documentation
ABNORMAL
#define ABNORMAL (1)
Definition at line 86 of file hash.c.
Referenced by hash_access(), and hash_seq().
ERROR
#define ERROR (-1)
Definition at line 85 of file hash.c.
Referenced by hash_access(), hash_close(), hash_delete(), hash_fd(), hash_get(), hash_put(), hash_seq(), hash_sync(), hdestroy(), and vm_allocate_dh().
MOD
#define MOD (x, y) ((x) & ((y) - 1))
Definition at line 79 of file hash.c.
OLDHASHVERSION
#define OLDHASHVERSION 1
Referenced by __hash_open().
RETURN_ERROR
#define RETURN_ERROR (ERR, LOC) { save_errno = ERR; goto LOC; }
Definition at line 81 of file hash.c.
Referenced by __hash_open().
SUCCESS
#define SUCCESS (0)
Definition at line 84 of file hash.c.
Referenced by hash_access(), hash_seq(), and hdestroy().
Function Documentation
__call_hash()
u_int32_t __call_hash (HTAB * hashp, char * k, int len)
Definition at line 886 of file hash.c.
Referenced by __big_split(), __split_page(), hash_access(), and ugly_split().
 {
    int n, bucket;
    n = hashp->hash(k, len);
    bucket = n & hashp->HIGH_MASK;
    if (bucket > hashp->MAX_BUCKET)
       bucket = bucket & hashp->LOW_MASK;
    return (bucket);
 }
__expand_table()
int __expand_table (HTAB * hashp)
Definition at line 815 of file hash.c.
References __hash_log2(), __split_page(), calloc, htab::dir, htab::exsegs, hash_realloc(), htab::nsegs, and NULL.
Referenced by __addel().
 {
    u_int32_t old_bucket, new_bucket;
    int dirsize, new_segnum, spare_ndx;
 #ifdef HASH_STATISTICS
    hash_expansions++;
 #endif
    new_bucket = ++hashp->MAX_BUCKET;
    old_bucket = (hashp->MAX_BUCKET & hashp->LOW_MASK);
    new_segnum = new_bucket >> hashp->SSHIFT;
    /* Check if we need a new segment */
    if (new_segnum >= hashp->nsegs) {
       /* Check if we need to expand directory */
       if (new_segnum >= hashp->DSIZE) {
          /* Reallocate directory */
          dirsize = hashp->DSIZE * sizeof(SEGMENT *);
          if (!hash_realloc(&hashp->dir, dirsize, dirsize << 1))
             return (-1);
          hashp->DSIZE = dirsize << 1;
       }
       if ((hashp->dir[new_segnum] =
           (SEGMENT)calloc(hashp->SGSIZE, sizeof(SEGMENT))) == NULL)
          return (-1);
       hashp->exsegs++;
       hashp->nsegs++;
    }
    /*
     * If the split point is increasing (MAX_BUCKET's log base 2
     * * increases), we need to copy the current contents of the spare
     * split bucket to the next bucket.
     */
    spare_ndx = __hash_log2(hashp->MAX_BUCKET + 1);
    if (spare_ndx > hashp->OVFL_POINT) {
       hashp->SPARES[spare_ndx] = hashp->SPARES[hashp->OVFL_POINT];
       hashp->OVFL_POINT = spare_ndx;
    }
    if (new_bucket > (u_int32_t) hashp->HIGH_MASK) {
       /* Starting a new doubling */
       hashp->LOW_MASK = hashp->HIGH_MASK;
       hashp->HIGH_MASK = new_bucket | hashp->LOW_MASK;
    }
    /* Relocate records to the new bucket */
    return (__split_page(hashp, old_bucket, new_bucket));
 }
__hash_open()
DB* __hash_open (char * file, int flags, int mode, const HASHINFO * info, int dflags) const
Definition at line 96 of file hash.c.
References __buf_init(), alloc_segs(), BYTE_SHIFT, HASHINFO::cachesize, calloc, htab::cbucket, CHARKEY, DB_HASH, dbp, DEF_BUFSIZE, EFTYPE, errno, htab::flags, htab::fp, free(), hash_close(), hash_delete(), hash_fd(), hash_get(), hash_put(), hash_seq(), hash_sync(), HASHMAGIC, HASHVERSION, hdestroy(), htab::hdr, if(), init_hash(), malloc(), htab::mapp, htab::new_file, htab::nmaps, htab::nsegs, NULL, OLDHASHVERSION, RETURN_ERROR, htab::save_file, and swap_header().
Referenced by dbm_open(), dbopen(), and hcreate().
 {
    HTAB *hashp;
    struct stat statbuf;
    DB *dbp;
    int bpages, hdrsize, new_table, nsegs, save_errno;
    if ((flags & O_ACCMODE) == O_WRONLY) {
       errno = EINVAL;
       return (NULL);
    }
    if (!(hashp = (HTAB *)calloc(1, sizeof(HTAB))))
       return (NULL);
    hashp->fp = -1;
    /*
     * Even if user wants write only, we need to be able to read
     * the actual file, so we need to open it read/write. But, the
     * field in the hashp structure needs to be accurate so that
     * we can check accesses.
     */
    hashp->flags = flags;
    new_table = 0;
    if (!file || (flags & O_TRUNC) ||
        (stat(file, &statbuf) && (errno == ENOENT))) {
       if (errno == ENOENT)
          errno = 0; /* Just in case someone looks at errno */
       new_table = 1;
    }
    if (file) {
       if ((hashp->fp = open(file, flags, mode)) == -1)
          RETURN_ERROR(errno, error0);
       (void)fcntl(hashp->fp, F_SETFD, 1);
    }
    if (new_table) {
       if (!(hashp = init_hash(hashp, file, info)))
          RETURN_ERROR(errno, error1);
    } else {
       /* Table already exists */
       if (info && info->hash)
          hashp->hash = info->hash;
       else
          hashp->hash = __default_hash;
       hdrsize = read(hashp->fp, &hashp->hdr, sizeof(HASHHDR));
 #if BYTE_ORDER == LITTLE_ENDIAN
       swap_header(hashp);
 #endif
       if (hdrsize == -1)
          RETURN_ERROR(errno, error1);
       if (hdrsize != sizeof(HASHHDR))
          RETURN_ERROR(EFTYPE, error1);
       /* Verify file type, versions and hash function */
       if (hashp->MAGIC != HASHMAGIC)
          RETURN_ERROR(EFTYPE, error1);
 #define  OLDHASHVERSION 1
       if (hashp->VERSION != HASHVERSION &&
           hashp->VERSION != OLDHASHVERSION)
          RETURN_ERROR(EFTYPE, error1);
       if (hashp->hash(CHARKEY, sizeof(CHARKEY))
           != (u_int32_t) hashp->H_CHARKEY)
          RETURN_ERROR(EFTYPE, error1);
       /*
        * Figure out how many segments we need.  Max_Bucket is the
        * maximum bucket number, so the number of buckets is
        * max_bucket + 1.
        */
       nsegs = (hashp->MAX_BUCKET + 1 + hashp->SGSIZE - 1) /
           hashp->SGSIZE;
       hashp->nsegs = 0;
       if (alloc_segs(hashp, nsegs))
          /*
           * If alloc_segs fails, table will have been destroyed
           * and errno will have been set.
           */
          return (NULL);
       /* Read in bitmaps */
       bpages = (hashp->SPARES[hashp->OVFL_POINT] +
           (hashp->BSIZE << BYTE_SHIFT) - 1) >>
           (hashp->BSHIFT + BYTE_SHIFT);
       hashp->nmaps = bpages;
       (void)memset(&hashp->mapp[0], 0, bpages * sizeof(u_int32_t *));
    }
    /* Initialize Buffer Manager */
    if (info && info->cachesize)
       __buf_init(hashp, info->cachesize);
    else
       __buf_init(hashp, DEF_BUFSIZE);
    hashp->new_file = new_table;
    hashp->save_file = file && (hashp->flags & O_ACCMODE) != O_RDONLY;
    hashp->cbucket = -1;
    if (!(dbp = (DB *)malloc(sizeof(DB)))) {
       save_errno = errno;
       hdestroy(hashp);
       errno = save_errno;
       return (NULL);
    }
    dbp->internal = hashp;
    dbp->close = hash_close;
    dbp->del = hash_delete;
    dbp->fd = hash_fd;
    dbp->get = hash_get;
    dbp->put = hash_put;
    dbp->seq = hash_seq;
    dbp->sync = hash_sync;
    dbp->type = DB_HASH;
 #ifdef DEBUG
    (void)fprintf(stderr,
 "%s\n%s%x\n%s%d\n%s%d\n%s%d\n%s%d\n%s%d\n%s%d\n%s%d\n%s%d\n%s%d\n%s%x\n%s%x\n%s%d\n%s%d\n",
        "init_htab:",
        "TABLE POINTER   ", hashp,
        "BUCKET SIZE     ", hashp->BSIZE,
        "BUCKET SHIFT    ", hashp->BSHIFT,
        "DIRECTORY SIZE  ", hashp->DSIZE,
        "SEGMENT SIZE    ", hashp->SGSIZE,
        "SEGMENT SHIFT   ", hashp->SSHIFT,
        "FILL FACTOR     ", hashp->FFACTOR,
        "MAX BUCKET      ", hashp->MAX_BUCKET,
        "OVFL POINT        ", hashp->OVFL_POINT,
        "LAST FREED      ", hashp->LAST_FREED,
        "HIGH MASK       ", hashp->HIGH_MASK,
        "LOW  MASK       ", hashp->LOW_MASK,
        "NSEGS           ", hashp->nsegs,
        "NKEYS           ", hashp->NKEYS);
 #endif
 #ifdef HASH_STATISTICS
    hash_overflows = hash_accesses = hash_collisions = hash_expansions = 0;
 #endif
    return (dbp);
 error1:
    if (hashp != NULL)
       (void)close(hashp->fp);
 error0:
    free(hashp);
    errno = save_errno;
    return (NULL);
 }
__P() [1/12]
static int alloc_segs __P ((HTAB *, int)) static
__P() [2/12]
static int flush_meta __P ((HTAB *)) static
__P() [3/12]
static int hash_access __P ((HTAB *, ACTION, DBT *, DBT *)) static
__P() [4/12]
static int hash_close __P ((DB *)) static
__P() [5/12]
static int hash_delete __P ((const DB *, const DBT *, u_int32_t)) static
__P() [6/12]
static int hash_fd __P ((const DB *)) static
__P() [7/12]
static int hash_put __P ((const DB *, const DBT *, DBT *, u_int32_t)) static
__P() [8/12]
static void* hash_realloc __P ((SEGMENT **, int, int)) static
__P() [9/12]
static int hash_seq __P ((const DB *, DBT *, DBT *, u_int32_t)) static
__P() [10/12]
static int hash_sync __P ((const DB *, u_int32_t)) static
__P() [11/12]
static HTAB* init_hash __P ((HTAB *, const char *, const HASHINFO *)) static
__P() [12/12]
static void swap_header_copy __P ((HASHHDR *, HASHHDR *)) static
alloc_segs()
static int alloc_segs (HTAB * hashp, int nsegs) static
Definition at line 906 of file hash.c.
References calloc, htab::dir, errno, hdestroy(), htab::nsegs, and NULL.
Referenced by __hash_open(), and init_htab().
 {
    register int i;
    register SEGMENT store;
    int save_errno;
    if ((hashp->dir =
        (SEGMENT *)calloc(hashp->DSIZE, sizeof(SEGMENT *))) == NULL) {
       save_errno = errno;
       (void)hdestroy(hashp);
       errno = save_errno;
       return (-1);
    }
    /* Allocate segments */
    if ((store =
        (SEGMENT)calloc(nsegs << hashp->SSHIFT, sizeof(SEGMENT))) == NULL) {
       save_errno = errno;
       (void)hdestroy(hashp);
       errno = save_errno;
       return (-1);
    }
    for (i = 0; i < nsegs; i++, hashp->nsegs++)
       hashp->dir[i] = &store[i << hashp->SSHIFT];
    return (0);
 }
flush_meta()
static int flush_meta (HTAB * hashp) static
Definition at line 486 of file hash.c.
References __put_page(), CHARKEY, EFTYPE, errno, htab::errnum, htab::fp, HASHMAGIC, HASHVERSION, htab::hdr, htab::mapp, NCACHED, htab::save_file, and swap_header_copy().
Referenced by hash_sync(), and hdestroy().
 {
    HASHHDR *whdrp;
 #if BYTE_ORDER == LITTLE_ENDIAN
    HASHHDR whdr;
 #endif
    int fp, i, wsize;
    if (!hashp->save_file)
       return (0);
    hashp->MAGIC = HASHMAGIC;
    hashp->VERSION = HASHVERSION;
    hashp->H_CHARKEY = hashp->hash(CHARKEY, sizeof(CHARKEY));
    fp = hashp->fp;
    whdrp = &hashp->hdr;
 #if BYTE_ORDER == LITTLE_ENDIAN
    whdrp = &whdr;
    swap_header_copy(&hashp->hdr, whdrp);
 #endif
    if ((lseek(fp, (off_t)0, SEEK_SET) == -1) ||
        ((wsize = write(fp, whdrp, sizeof(HASHHDR))) == -1))
       return (-1);
    else
       if (wsize != sizeof(HASHHDR)) {
          errno = EFTYPE;
          hashp->errnum = errno;
          return (-1);
       }
    for (i = 0; i < NCACHED; i++)
       if (hashp->mapp[i])
          if (__put_page(hashp, (char *)hashp->mapp[i],
             hashp->BITMAPS[i], 0, 1))
             return (-1);
    return (0);
 }
hash_access()
static int hash_access (HTAB * hashp, ACTION action, DBT * key, DBT * val) static
Definition at line 596 of file hash.c.
References __addel(), __big_return(), __call_hash(), __delpair(), __find_bigpair(), __find_last_page(), __get_buf(), ABNORMAL, BUF_PIN, DBT::data, ERROR, _bufhead::flags, HASH_DELETE, HASH_GET, HASH_PUT, HASH_PUTNEW, if(), NULL, OVFLPAGE, _bufhead::page, REAL_KEY, DBT::size, and SUCCESS.
Referenced by hash_delete(), hash_get(), and hash_put().
 {
    register BUFHEAD *rbufp;
    BUFHEAD *bufp, *save_bufp;
    register u_int16_t *bp;
    register int n, ndx, off, size;
    register char *kp;
    u_int16_t pageno;
 #ifdef HASH_STATISTICS
    hash_accesses++;
 #endif
    off = hashp->BSIZE;
    size = key->size;
    kp = (char *)key->data;
    rbufp = __get_buf(hashp, __call_hash(hashp, kp, size), NULL, 0);
    if (!rbufp)
       return (ERROR);
    save_bufp = rbufp;
    /* Pin the bucket chain */
    rbufp->flags |= BUF_PIN;
    for (bp = (u_int16_t *)rbufp->page, n = *bp++, ndx = 1; ndx < n;)
       if (bp[1] >= REAL_KEY) {
          /* Real key/data pair */
          if (size == off - *bp &&
              memcmp(kp, rbufp->page + *bp, size) == 0)
             goto found;
          off = bp[1];
 #ifdef HASH_STATISTICS
          hash_collisions++;
 #endif
          bp += 2;
          ndx += 2;
       } else if (bp[1] == OVFLPAGE) {
          rbufp = __get_buf(hashp, *bp, rbufp, 0);
          if (!rbufp) {
             save_bufp->flags &= ~BUF_PIN;
             return (ERROR);
          }
          /* FOR LOOP INIT */
          bp = (u_int16_t *)rbufp->page;
          n = *bp++;
          ndx = 1;
          off = hashp->BSIZE;
       } else if (bp[1] < REAL_KEY) {
          if ((ndx =
              __find_bigpair(hashp, rbufp, ndx, kp, size)) > 0)
             goto found;
          if (ndx == -2) {
             bufp = rbufp;
             if (!(pageno =
                 __find_last_page(hashp, &bufp))) {
                ndx = 0;
                rbufp = bufp;
                break;   /* FOR */
             }
             rbufp = __get_buf(hashp, pageno, bufp, 0);
             if (!rbufp) {
                save_bufp->flags &= ~BUF_PIN;
                return (ERROR);
             }
             /* FOR LOOP INIT */
             bp = (u_int16_t *)rbufp->page;
             n = *bp++;
             ndx = 1;
             off = hashp->BSIZE;
          } else {
             save_bufp->flags &= ~BUF_PIN;
             return (ERROR);
          }
       }
    /* Not found */
    switch (action) {
    case HASH_PUT:
    case HASH_PUTNEW:
       if (__addel(hashp, rbufp, key, val)) {
          save_bufp->flags &= ~BUF_PIN;
          return (ERROR);
       } else {
          save_bufp->flags &= ~BUF_PIN;
          return (SUCCESS);
       }
    case HASH_GET:
    case HASH_DELETE:
    default:
       save_bufp->flags &= ~BUF_PIN;
       return (ABNORMAL);
    }
 found:
    switch (action) {
    case HASH_PUTNEW:
       save_bufp->flags &= ~BUF_PIN;
       return (ABNORMAL);
    case HASH_GET:
       bp = (u_int16_t *)rbufp->page;
       if (bp[ndx + 1] < REAL_KEY) {
          if (__big_return(hashp, rbufp, ndx, val, 0))
             return (ERROR);
       } else {
          val->data = (u_char *)rbufp->page + (int)bp[ndx + 1];
          val->size = bp[ndx] - bp[ndx + 1];
       }
       break;
    case HASH_PUT:
       if ((__delpair(hashp, rbufp, ndx)) ||
           (__addel(hashp, rbufp, key, val))) {
          save_bufp->flags &= ~BUF_PIN;
          return (ERROR);
       }
       break;
    case HASH_DELETE:
       if (__delpair(hashp, rbufp, ndx))
          return (ERROR);
       break;
    default:
       abort();
    }
    save_bufp->flags &= ~BUF_PIN;
    return (SUCCESS);
 }
hash_close()
static int hash_close (DB * dbp) static
Definition at line 246 of file hash.c.
References ERROR, free(), hdestroy(), __db::internal, and retval.
Referenced by __hash_open().
 {
    HTAB *hashp;
    int retval;
    if (!dbp)
       return (ERROR);
    hashp = (HTAB *)dbp->internal;
    retval = hdestroy(hashp);
    free(dbp);
    return (retval);
 }
hash_delete()
static int hash_delete (DB * dbp, const DBT * key, u_int32_t flag) const static
Definition at line 573 of file hash.c.
References errno, htab::errnum, ERROR, htab::flags, hash_access(), HASH_DELETE, if(), __db::internal, NULL, and R_CURSOR.
Referenced by __hash_open().
 {
    HTAB *hashp;
    hashp = (HTAB *)dbp->internal;
    if (flag && flag != R_CURSOR) {
       hashp->errnum = errno = EINVAL;
       return (ERROR);
    }
    if ((hashp->flags & O_ACCMODE) == O_RDONLY) {
       hashp->errnum = errno = EPERM;
       return (ERROR);
    }
    return (hash_access(hashp, HASH_DELETE, (DBT *)key, NULL));
 }
hash_fd()
static int hash_fd (DB * dbp) const static
Definition at line 262 of file hash.c.
References errno, ERROR, htab::fp, if(), and __db::internal.
Referenced by __hash_open().
 {
    HTAB *hashp;
    if (!dbp)
       return (ERROR);
    hashp = (HTAB *)dbp->internal;
    if (hashp->fp == -1) {
       errno = ENOENT;
       return (-1);
    }
    return (hashp->fp);
 }
hash_get()
static int hash_get (DB * dbp, const DBT * key, DBT * data, u_int32_t flag) const static
Definition at line 534 of file hash.c.
References errno, htab::errnum, ERROR, hash_access(), HASH_GET, if(), and __db::internal.
Referenced by __hash_open().
 {
    HTAB *hashp;
    hashp = (HTAB *)dbp->internal;
    if (flag) {
       hashp->errnum = errno = EINVAL;
       return (ERROR);
    }
    return (hash_access(hashp, HASH_GET, (DBT *)key, data));
 }
hash_put()
static int hash_put (DB * dbp, DBT * key, const DBT * data, u_int32_t flag) const static
Definition at line 551 of file hash.c.
References errno, htab::errnum, ERROR, htab::flags, hash_access(), HASH_PUT, HASH_PUTNEW, if(), __db::internal, and R_NOOVERWRITE.
Referenced by __hash_open().
 {
    HTAB *hashp;
    hashp = (HTAB *)dbp->internal;
    if (flag && flag != R_NOOVERWRITE) {
       hashp->errnum = errno = EINVAL;
       return (ERROR);
    }
    if ((hashp->flags & O_ACCMODE) == O_RDONLY) {
       hashp->errnum = errno = EPERM;
       return (ERROR);
    }
    return (hash_access(hashp, flag == R_NOOVERWRITE ?
        HASH_PUTNEW : HASH_PUT, (DBT *)key, (DBT *)data));
 }
hash_realloc()
static void* hash_realloc (SEGMENT ** p_ptr, int oldsize, int newsize) static
Definition at line 870 of file hash.c.
References free(), and malloc().
Referenced by __expand_table().
 {
    register void *p;
    if ((p = malloc(newsize))) {
       memmove(p, *p_ptr, oldsize);
       memset((char *)p + oldsize, 0, newsize - oldsize);
       free(*p_ptr);
       *p_ptr = p;
    }
    return (p);
 }
hash_seq()
static int hash_seq (DB * dbp, DBT * key, DBT * data, u_int32_t flag) const static
Definition at line 725 of file hash.c.
References __big_keydata(), __get_buf(), ABNORMAL, htab::cbucket, htab::cndx, htab::cpage, DBT::data, DEBUG, errno, htab::errnum, ERROR, if(), __db::internal, NULL, OVFLPAGE, _bufhead::page, R_FIRST, R_NEXT, REAL_KEY, DBT::size, and SUCCESS.
Referenced by __hash_open().
 {
    register u_int32_t bucket;
    register BUFHEAD *bufp = NULL;
    HTAB *hashp;
    u_int16_t *bp, ndx;
    hashp = (HTAB *)dbp->internal;
    if (flag && flag != R_FIRST && flag != R_NEXT) {
       hashp->errnum = errno = EINVAL;
       return (ERROR);
    }
 #ifdef HASH_STATISTICS
    hash_accesses++;
 #endif
    if ((hashp->cbucket < 0) || (flag == R_FIRST)) {
       hashp->cbucket = 0;
       hashp->cndx = 1;
       hashp->cpage = NULL;
    }
    for (bp = NULL; !bp || !bp[0]; ) {
       if (!(bufp = hashp->cpage)) {
          for (bucket = hashp->cbucket;
              bucket <= (u_int32_t) hashp->MAX_BUCKET;
              bucket++, hashp->cndx = 1) {
             bufp = __get_buf(hashp, bucket, NULL, 0);
             if (!bufp)
                return (ERROR);
             hashp->cpage = bufp;
             bp = (u_int16_t *)bufp->page;
             if (bp[0])
                break;
          }
          hashp->cbucket = bucket;
          if (hashp->cbucket > hashp->MAX_BUCKET) {
             hashp->cbucket = -1;
             return (ABNORMAL);
          }
       } else
          bp = (u_int16_t *)hashp->cpage->page;
 #ifdef DEBUG
       assert(bp);
       assert(bufp);
 #endif
       while (bp[hashp->cndx + 1] == OVFLPAGE) {
          bufp = hashp->cpage =
              __get_buf(hashp, bp[hashp->cndx], bufp, 0);
          if (!bufp)
             return (ERROR);
          bp = (u_int16_t *)(bufp->page);
          hashp->cndx = 1;
       }
       if (!bp[0]) {
          hashp->cpage = NULL;
          ++hashp->cbucket;
       }
    }
    ndx = hashp->cndx;
    if (bp[ndx + 1] < REAL_KEY) {
       if (__big_keydata(hashp, bufp, key, data, 1))
          return (ERROR);
    } else {
       key->data = (u_char *)hashp->cpage->page + bp[ndx];
       key->size = (ndx > 1 ? bp[ndx - 1] : hashp->BSIZE) - bp[ndx];
       data->data = (u_char *)hashp->cpage->page + bp[ndx + 1];
       data->size = bp[ndx] - bp[ndx + 1];
       ndx += 2;
       if (ndx > bp[0]) {
          hashp->cpage = NULL;
          hashp->cbucket++;
          hashp->cndx = 1;
       } else
          hashp->cndx = ndx;
    }
    return (SUCCESS);
 }
hash_sync()
static int hash_sync (DB * dbp, u_int32_t flags) const static
Definition at line 457 of file hash.c.
References __buf_free(), errno, ERROR, flush_meta(), if(), __db::internal, htab::new_file, and htab::save_file.
Referenced by __hash_open().
 {
    HTAB *hashp;
    if (flags != 0) {
       errno = EINVAL;
       return (ERROR);
    }
    if (!dbp)
       return (ERROR);
    hashp = (HTAB *)dbp->internal;
    if (!hashp->save_file)
       return (0);
    if (__buf_free(hashp, 0, 1) || flush_meta(hashp))
       return (ERROR);
    hashp->new_file = 0;
    return (0);
 }
hdestroy()
static int hdestroy (HTAB * hashp) static
Definition at line 397 of file hash.c.
References __buf_free(), htab::dir, errno, ERROR, htab::exsegs, flush_meta(), htab::fp, free(), htab::mapp, NCACHED, htab::nmaps, htab::nsegs, htab::save_file, and SUCCESS.
Referenced by __hash_open(), alloc_segs(), and hash_close().
 {
    int i, save_errno;
    save_errno = 0;
 #ifdef HASH_STATISTICS
    (void)fprintf(stderr, "hdestroy: accesses %ld collisions %ld\n",
        hash_accesses, hash_collisions);
    (void)fprintf(stderr, "hdestroy: expansions %ld\n",
        hash_expansions);
    (void)fprintf(stderr, "hdestroy: overflows %ld\n",
        hash_overflows);
    (void)fprintf(stderr, "keys %ld maxp %d segmentcount %d\n",
        hashp->NKEYS, hashp->MAX_BUCKET, hashp->nsegs);
    for (i = 0; i < NCACHED; i++)
       (void)fprintf(stderr,
           "spares[%d] = %d\n", i, hashp->SPARES[i]);
 #endif
    /*
     * Call on buffer manager to free buffers, and if required,
     * write them to disk.
     */
    if (__buf_free(hashp, 1, hashp->save_file))
       save_errno = errno;
    if (hashp->dir) {
       free(*hashp->dir);   /* Free initial segments */
       /* Free extra segments */
       while (hashp->exsegs--)
          free(hashp->dir[--hashp->nsegs]);
       free(hashp->dir);
    }
    if (flush_meta(hashp) && !save_errno)
       save_errno = errno;
    /* Free Bigmaps */
    for (i = 0; i < hashp->nmaps; i++)
       if (hashp->mapp[i])
          free(hashp->mapp[i]);
    if (hashp->fp != -1)
       (void)close(hashp->fp);
    free(hashp);
    if (save_errno) {
       errno = save_errno;
       return (ERROR);
    }
    return (SUCCESS);
 }
init_hash()
static HTAB* init_hash (HTAB * hashp, const char * file, const HASHINFO * info) static
Definition at line 280 of file hash.c.
References __hash_log2(), BIG_ENDIAN, HASHINFO::bsize, BYTE_ORDER, DEF_BUCKET_SHIFT, DEF_BUCKET_SIZE, DEF_DIRSIZE, DEF_FFACTOR, DEF_SEGSIZE, DEF_SEGSIZE_SHIFT, errno, HASHINFO::ffactor, init_htab(), LITTLE_ENDIAN, HASHINFO::lorder, MAX_BSIZE, HASHINFO::nelem, and NULL.
Referenced by __hash_open().
 {
 #ifdef _STATBUF_ST_BLKSIZE
    struct stat statbuf;
 #endif
    int nelem;
    nelem = 1;
    hashp->NKEYS = 0;
    hashp->LORDER = BYTE_ORDER;
    hashp->BSIZE = DEF_BUCKET_SIZE;
    hashp->BSHIFT = DEF_BUCKET_SHIFT;
    hashp->SGSIZE = DEF_SEGSIZE;
    hashp->SSHIFT = DEF_SEGSIZE_SHIFT;
    hashp->DSIZE = DEF_DIRSIZE;
    hashp->FFACTOR = DEF_FFACTOR;
    hashp->hash = __default_hash;
    memset(hashp->SPARES, 0, sizeof(hashp->SPARES));
    memset(hashp->BITMAPS, 0, sizeof (hashp->BITMAPS));
    /* Fix bucket size to be optimal for file system */
 #ifdef _STATBUF_ST_BLKSIZE
    if (file != NULL) {
       if (stat(file, &statbuf))
          return (NULL);
       hashp->BSIZE = statbuf.st_blksize;
       hashp->BSHIFT = __hash_log2(hashp->BSIZE);
    }
 #endif
    if (info) {
       if (info->bsize) {
          /* Round pagesize up to power of 2 */
          hashp->BSHIFT = __hash_log2(info->bsize);
          hashp->BSIZE = 1 << hashp->BSHIFT;
          if (hashp->BSIZE > MAX_BSIZE) {
             errno = EINVAL;
             return (NULL);
          }
       }
       if (info->ffactor)
          hashp->FFACTOR = info->ffactor;
       if (info->hash)
          hashp->hash = info->hash;
       if (info->nelem)
          nelem = info->nelem;
       if (info->lorder) {
          if (info->lorder != BIG_ENDIAN &&
              info->lorder != LITTLE_ENDIAN) {
             errno = EINVAL;
             return (NULL);
          }
          hashp->LORDER = info->lorder;
       }
    }
    /* init_htab should destroy the table and set errno if it fails */
    if (init_htab(hashp, nelem))
       return (NULL);
    else
       return (hashp);
 }
init_htab()
static int init_htab (HTAB * hashp, int nelem) static
Definition at line 351 of file hash.c.
References __hash_log2(), __ibitmap(), alloc_segs(), MAX, MINHDRSIZE, and OADDR_OF.
Referenced by init_hash().
 {
    register int nbuckets, nsegs;
    int l2;
    /*
     * Divide number of elements by the fill factor and determine a
     * desired number of buckets.  Allocate space for the next greater
     * power of two number of buckets.
     */
    nelem = (nelem - 1) / hashp->FFACTOR + 1;
    l2 = __hash_log2(MAX(nelem, 2));
    nbuckets = 1 << l2;
    hashp->SPARES[l2] = l2 + 1;
    hashp->SPARES[l2 + 1] = l2 + 1;
    hashp->OVFL_POINT = l2;
    hashp->LAST_FREED = 2;
    /* First bitmap page is at: splitpoint l2 page offset 1 */
    if (__ibitmap(hashp, OADDR_OF(l2, 1), l2 + 1, 0))
       return (-1);
    hashp->MAX_BUCKET = hashp->LOW_MASK = nbuckets - 1;
    hashp->HIGH_MASK = (nbuckets << 1) - 1;
    hashp->HDRPAGES = ((MAX(sizeof(HASHHDR), MINHDRSIZE) - 1) >>
        hashp->BSHIFT) + 1;
    nsegs = (nbuckets - 1) / hashp->SGSIZE + 1;
    nsegs = 1 << __hash_log2(nsegs);
    if (nsegs > hashp->DSIZE)
       hashp->DSIZE = nsegs;
    return (alloc_segs(hashp, nsegs));
 }
swap_header()
static void swap_header (HTAB * hashp) static
Definition at line 969 of file hash.c.
References hashhdr::bitmaps, hashhdr::bshift, hashhdr::bsize, hashhdr::dsize, hashhdr::ffactor, hashhdr::h_charkey, htab::hdr, hashhdr::hdrpages, hashhdr::high_mask, hashhdr::last_freed, hashhdr::lorder, hashhdr::low_mask, hashhdr::magic, hashhdr::max_bucket, NCACHED, hashhdr::nkeys, hashhdr::ovfl_point, hashhdr::spares, hashhdr::sshift, hashhdr::ssize, and hashhdr::version.
Referenced by __hash_open().
 {
    HASHHDR *hdrp;
    int i;
    hdrp = &hashp->hdr;
    M_32_SWAP(hdrp->magic);
    M_32_SWAP(hdrp->version);
    M_32_SWAP(hdrp->lorder);
    M_32_SWAP(hdrp->bsize);
    M_32_SWAP(hdrp->bshift);
    M_32_SWAP(hdrp->dsize);
    M_32_SWAP(hdrp->ssize);
    M_32_SWAP(hdrp->sshift);
    M_32_SWAP(hdrp->ovfl_point);
    M_32_SWAP(hdrp->last_freed);
    M_32_SWAP(hdrp->max_bucket);
    M_32_SWAP(hdrp->high_mask);
    M_32_SWAP(hdrp->low_mask);
    M_32_SWAP(hdrp->ffactor);
    M_32_SWAP(hdrp->nkeys);
    M_32_SWAP(hdrp->hdrpages);
    M_32_SWAP(hdrp->h_charkey);
    for (i = 0; i < NCACHED; i++) {
       M_32_SWAP(hdrp->spares[i]);
       M_16_SWAP(hdrp->bitmaps[i]);
    }
 }
swap_header_copy()
static void swap_header_copy (HASHHDR * srcp, HASHHDR * destp) static
Definition at line 940 of file hash.c.
References hashhdr::bitmaps, hashhdr::bshift, hashhdr::bsize, hashhdr::dsize, hashhdr::ffactor, hashhdr::h_charkey, hashhdr::hdrpages, hashhdr::high_mask, hashhdr::last_freed, hashhdr::lorder, hashhdr::low_mask, hashhdr::magic, hashhdr::max_bucket, NCACHED, hashhdr::nkeys, hashhdr::ovfl_point, hashhdr::spares, hashhdr::sshift, hashhdr::ssize, and hashhdr::version.
Referenced by flush_meta().
 {
    int i;
    P_32_COPY(srcp->magic, destp->magic);
    P_32_COPY(srcp->version, destp->version);
    P_32_COPY(srcp->lorder, destp->lorder);
    P_32_COPY(srcp->bsize, destp->bsize);
    P_32_COPY(srcp->bshift, destp->bshift);
    P_32_COPY(srcp->dsize, destp->dsize);
    P_32_COPY(srcp->ssize, destp->ssize);
    P_32_COPY(srcp->sshift, destp->sshift);
    P_32_COPY(srcp->ovfl_point, destp->ovfl_point);
    P_32_COPY(srcp->last_freed, destp->last_freed);
    P_32_COPY(srcp->max_bucket, destp->max_bucket);
    P_32_COPY(srcp->high_mask, destp->high_mask);
    P_32_COPY(srcp->low_mask, destp->low_mask);
    P_32_COPY(srcp->ffactor, destp->ffactor);
    P_32_COPY(srcp->nkeys, destp->nkeys);
    P_32_COPY(srcp->hdrpages, destp->hdrpages);
    P_32_COPY(srcp->h_charkey, destp->h_charkey);
    for (i = 0; i < NCACHED; i++) {
       P_32_COPY(srcp->spares[i], destp->spares[i]);
       P_16_COPY(srcp->bitmaps[i], destp->bitmaps[i]);
    }
 }