Asterisk - The Open Source Telephony Project: confbridge.h File Reference
confbridge.h File Reference
#include "asterisk.h"
#include "asterisk/app.h"
#include "asterisk/logger.h"
#include "asterisk/linkedlists.h"
#include "asterisk/channel.h"
#include "asterisk/bridge.h"
#include "asterisk/bridge_features.h"
#include "asterisk/stasis_bridges.h"
#include "conf_state.h"
Data Structures
struct bridge_profile
struct bridge_profile_sounds
struct conf_menu
struct conf_menu_action
struct conf_menu_entry
struct confbridge_conference
The structure that represents a conference bridge.
struct confbridge_user
The structure that represents a conference bridge user.
struct post_join_action
struct user_profile
Macros
#define DEFAULT_BRIDGE_PROFILE "default_bridge"
#define DEFAULT_MENU_PROFILE "default_menu"
#define DEFAULT_SILENCE_THRESHOLD 2500
#define DEFAULT_TALKING_THRESHOLD 160
#define DEFAULT_USER_PROFILE "default_user"
#define MAX_CONF_NAME AST_MAX_EXTENSION
#define MAX_PIN 80
#define MAX_PROFILE_NAME 128
Enumerations
enum bridge_profile_flags {
BRIDGE_OPT_RECORD_CONFERENCE = (1 << 0), BRIDGE_OPT_VIDEO_SRC_LAST_MARKED = (1 << 1), BRIDGE_OPT_VIDEO_SRC_FIRST_MARKED = (1 << 2), BRIDGE_OPT_VIDEO_SRC_FOLLOW_TALKER = (1 << 3),
BRIDGE_OPT_RECORD_FILE_APPEND = (1 << 4), BRIDGE_OPT_RECORD_FILE_TIMESTAMP = (1 << 5), BRIDGE_OPT_BINAURAL_ACTIVE = (1 << 6), BRIDGE_OPT_VIDEO_SRC_SFU = (1 << 7),
BRIDGE_OPT_REMB_BEHAVIOR_AVERAGE = (1 << 8), BRIDGE_OPT_REMB_BEHAVIOR_LOWEST = (1 << 9), BRIDGE_OPT_REMB_BEHAVIOR_HIGHEST = (1 << 10), BRIDGE_OPT_ENABLE_EVENTS = (1 << 11),
BRIDGE_OPT_REMB_BEHAVIOR_AVERAGE_ALL = (1 << 12), BRIDGE_OPT_REMB_BEHAVIOR_LOWEST_ALL = (1 << 13), BRIDGE_OPT_REMB_BEHAVIOR_HIGHEST_ALL = (1 << 14), BRIDGE_OPT_REMB_BEHAVIOR_FORCE = (1 << 15)
}
enum conf_menu_action_id {
MENU_ACTION_TOGGLE_MUTE = 1, MENU_ACTION_PLAYBACK, MENU_ACTION_PLAYBACK_AND_CONTINUE, MENU_ACTION_INCREASE_LISTENING,
MENU_ACTION_DECREASE_LISTENING, MENU_ACTION_RESET_LISTENING, MENU_ACTION_RESET_TALKING, MENU_ACTION_INCREASE_TALKING,
MENU_ACTION_DECREASE_TALKING, MENU_ACTION_DIALPLAN_EXEC, MENU_ACTION_ADMIN_TOGGLE_LOCK, MENU_ACTION_ADMIN_KICK_LAST,
MENU_ACTION_LEAVE, MENU_ACTION_NOOP, MENU_ACTION_SET_SINGLE_VIDEO_SRC, MENU_ACTION_RELEASE_SINGLE_VIDEO_SRC,
MENU_ACTION_PARTICIPANT_COUNT, MENU_ACTION_ADMIN_TOGGLE_MUTE_PARTICIPANTS, MENU_ACTION_TOGGLE_BINAURAL
}
enum conf_sounds {
CONF_SOUND_HAS_JOINED, CONF_SOUND_HAS_LEFT, CONF_SOUND_KICKED, CONF_SOUND_MUTED,
CONF_SOUND_UNMUTED, CONF_SOUND_ONLY_ONE, CONF_SOUND_THERE_ARE, CONF_SOUND_OTHER_IN_PARTY,
CONF_SOUND_PLACE_IN_CONF, CONF_SOUND_WAIT_FOR_LEADER, CONF_SOUND_LEADER_HAS_LEFT, CONF_SOUND_GET_PIN,
CONF_SOUND_INVALID_PIN, CONF_SOUND_ONLY_PERSON, CONF_SOUND_LOCKED, CONF_SOUND_LOCKED_NOW,
CONF_SOUND_UNLOCKED_NOW, CONF_SOUND_ERROR_MENU, CONF_SOUND_JOIN, CONF_SOUND_LEAVE,
CONF_SOUND_PARTICIPANTS_MUTED, CONF_SOUND_PARTICIPANTS_UNMUTED, CONF_SOUND_BEGIN, CONF_SOUND_BINAURAL_ON,
CONF_SOUND_BINAURAL_OFF
}
enum user_profile_flags {
USER_OPT_ADMIN = (1 << 0), USER_OPT_NOONLYPERSON = (1 << 1), USER_OPT_MARKEDUSER = (1 << 2), USER_OPT_STARTMUTED = (1 << 3),
USER_OPT_MUSICONHOLD = (1 << 4), USER_OPT_QUIET = (1 << 5), USER_OPT_ANNOUNCEUSERCOUNT = (1 << 6), USER_OPT_WAITMARKED = (1 << 7),
USER_OPT_ENDMARKED = (1 << 8), USER_OPT_DENOISE = (1 << 9), USER_OPT_ANNOUNCE_JOIN_LEAVE = (1 << 10), USER_OPT_TALKER_DETECT = (1 << 11),
USER_OPT_DROP_SILENCE = (1 << 12), USER_OPT_DTMF_PASS = (1 << 13), USER_OPT_ANNOUNCEUSERCOUNTALL = (1 << 14), USER_OPT_JITTERBUFFER = (1 << 15),
USER_OPT_ANNOUNCE_JOIN_LEAVE_REVIEW = (1 << 16), USER_OPT_SEND_EVENTS = (1 << 17), USER_OPT_ECHO_EVENTS = (1 << 18), USER_OPT_TEXT_MESSAGING = (1 << 19),
USER_OPT_ANSWER_CHANNEL = (1 << 20)
}
Functions
int async_play_sound_file (struct confbridge_conference *conference, const char *filename, struct ast_channel *initiator)
Play sound file into conference bridge asynchronously.
void async_play_sound_ready (struct ast_channel *chan)
Indicate the initiator of an async sound file is ready for it to play.
int conf_add_post_join_action (struct confbridge_user *user, int(*func)(struct confbridge_user *user))
Queue a function to run with the given conference bridge user as an argument once the state transition is complete.
void conf_add_user_active (struct confbridge_conference *conference, struct confbridge_user *user)
Add a conference bridge user as an unmarked active user of the conference.
void conf_add_user_marked (struct confbridge_conference *conference, struct confbridge_user *user)
Add a conference bridge user as a marked active user of the conference.
void conf_add_user_waiting (struct confbridge_conference *conference, struct confbridge_user *user)
Add a conference bridge user as an waiting user of the conference.
int conf_announce_channel_push (struct ast_channel *ast)
Push the announcer channel into the conference.
struct ast_channel_tech * conf_announce_get_tech (void)
Get ConfBridge announce channel technology struct.
void conf_bridge_profile_copy (struct bridge_profile *dst, struct bridge_profile *src)
copies a bridge profile
void conf_bridge_profile_destroy (struct bridge_profile *b_profile)
Destroy a bridge profile found by 'conf_find_bridge_profile'.
void conf_destroy_config (void)
destroy the information loaded from the confbridge.conf file
void conf_ended (struct confbridge_conference *conference)
Callback to be called when the conference has become empty.
struct confbridge_conference * conf_find_bridge (const char *conference_name)
Find a confbridge by name.
const struct bridge_profile * conf_find_bridge_profile (struct ast_channel *chan, const char *bridge_profile_name, struct bridge_profile *result)
Find a bridge profile given a bridge profile's name and store that profile in result structure.
int conf_find_menu_entry_by_sequence (const char *dtmf_sequence, struct conf_menu *menu, struct conf_menu_entry *result)
Finds a menu_entry in a menu structure matched by DTMF sequence.
const struct user_profile * conf_find_user_profile (struct ast_channel *chan, const char *user_profile_name, struct user_profile *result)
find a user profile given a user profile's name and store that profile in result structure.
const char * conf_get_sound (enum conf_sounds sound, struct bridge_profile_sounds *custom_sounds)
Looks to see if sound file is stored in bridge profile sounds, if not default sound is provided.
int conf_handle_dtmf (struct ast_bridge_channel *bridge_channel, struct confbridge_user *user, struct conf_menu_entry *menu_entry, struct conf_menu *menu)
Once a DTMF sequence matches a sequence in the user's DTMF menu, this function will get called to perform the menu action.
void conf_handle_first_join (struct confbridge_conference *conference)
Callback to execute any time we transition from zero to one active users.
int conf_handle_inactive_waitmarked (struct confbridge_user *user)
Handle actions every time a waitmarked user joins w/o a marked user present.
int conf_handle_only_person (struct confbridge_user *user)
Handle actions whenever an user joins an empty conference.
void conf_handle_second_active (struct confbridge_conference *conference)
Handle when a conference moves to having more than one active participant.
int conf_load_config (void)
load confbridge.conf file
void conf_menu_entry_destroy (struct conf_menu_entry *menu_entry)
Destroys and frees all the actions stored in a menu_entry structure.
void conf_moh_start (struct confbridge_user *user)
Start MOH for the conference user.
void conf_moh_stop (struct confbridge_user *user)
Stop MOH for the conference user.
void conf_mute_only_active (struct confbridge_conference *conference)
Attempt to mute/play MOH to the only user in the conference if they require it.
struct ast_channel_tech * conf_record_get_tech (void)
Get ConfBridge record channel technology struct.
int conf_reload_config (void)
reload confbridge.conf file
void conf_remove_user_active (struct confbridge_conference *conference, struct confbridge_user *user)
Remove a conference bridge user from the unmarked active conference users in the conference.
void conf_remove_user_marked (struct confbridge_conference *conference, struct confbridge_user *user)
Remove a conference bridge user from the marked active conference users in the conference.
void conf_remove_user_waiting (struct confbridge_conference *conference, struct confbridge_user *user)
Remove a conference bridge user from the waiting conference users in the conference.
void conf_send_event_to_participants (struct confbridge_conference *conference, struct ast_channel *chan, struct stasis_message *msg)
Send events to bridge participants.
int conf_set_menu_to_user (struct ast_channel *chan, struct confbridge_user *user, const char *menu_profile_name)
find a menu profile given a menu profile's name and apply the menu in DTMF hooks.
void conf_update_user_mute (struct confbridge_user *user)
Update the actual mute status of the user and set it on the bridge.
struct stasis_message_type * confbridge_end_type (void)
get the confbridge end stasis message type
const char * confbridge_event_type_to_string (struct stasis_message_type *event_type)
Get the string representation of a confbridge stasis message type.
void confbridge_handle_atxfer (struct ast_attended_transfer_message *msg)
Create join/leave events for attended transfers.
struct stasis_message_type * confbridge_join_type (void)
get the confbridge join stasis message type
struct stasis_message_type * confbridge_leave_type (void)
get the confbridge leave stasis message type
struct stasis_message_type * confbridge_mute_type (void)
get the confbridge mute stasis message type
struct stasis_message_type * confbridge_start_record_type (void)
get the confbridge start_record stasis message type
struct stasis_message_type * confbridge_start_type (void)
get the confbridge start stasis message type
struct stasis_message_type * confbridge_stop_record_type (void)
get the confbridge stop_record stasis message type
struct stasis_message_type * confbridge_talking_type (void)
get the confbridge talking stasis message type
struct stasis_message_type * confbridge_unmute_type (void)
get the confbridge unmute stasis message type
struct stasis_message_type * confbridge_welcome_type (void)
get the confbridge welcome stasis message type
int func_confbridge_helper (struct ast_channel *chan, const char *cmd, char *data, const char *value)
int manager_confbridge_init (void)
register stasis message routers to handle manager events for confbridge messages
void manager_confbridge_shutdown (void)
unregister stasis message routers to handle manager events for confbridge messages
int play_sound_file (struct confbridge_conference *conference, const char *filename)
Play sound file into conference bridge.
Variables
struct ao2_container * conference_bridges
Container to hold all conference bridges in progress.
Macro Definition Documentation
DEFAULT_BRIDGE_PROFILE
#define DEFAULT_BRIDGE_PROFILE "default_bridge"
Definition at line 42 of file confbridge.h.
Referenced by conf_find_bridge_profile(), confbridge_exec(), func_confbridge_helper(), and verify_default_profiles().
DEFAULT_MENU_PROFILE
#define DEFAULT_MENU_PROFILE "default_menu"
Definition at line 43 of file confbridge.h.
Referenced by conf_set_menu_to_user(), confbridge_exec(), func_confbridge_helper(), and verify_default_profiles().
DEFAULT_SILENCE_THRESHOLD
#define DEFAULT_SILENCE_THRESHOLD 2500
Default time in ms of silence necessary to declare talking stopped by the bridge.
Definition at line 49 of file confbridge.h.
Referenced by conf_load_config(), and confbridge_exec().
DEFAULT_TALKING_THRESHOLD
#define DEFAULT_TALKING_THRESHOLD 160
Default minimum average magnitude threshold to determine talking by the DSP.
Definition at line 46 of file confbridge.h.
Referenced by conf_load_config(), and confbridge_exec().
DEFAULT_USER_PROFILE
#define DEFAULT_USER_PROFILE "default_user"
Definition at line 41 of file confbridge.h.
Referenced by conf_find_user_profile(), confbridge_exec(), func_confbridge_helper(), and verify_default_profiles().
MAX_CONF_NAME
#define MAX_CONF_NAME AST_MAX_EXTENSION
Maximum length of a conference bridge name
Definition at line 35 of file confbridge.h.
Referenced by confbridge_exec().
MAX_PIN
#define MAX_PIN 80
Maximum length of a conference pin
Definition at line 37 of file confbridge.h.
MAX_PROFILE_NAME
#define MAX_PROFILE_NAME 128
Maximum length of bridge/user/menu profile names
Definition at line 39 of file confbridge.h.
Enumeration Type Documentation
bridge_profile_flags
enum bridge_profile_flags
Enumerator
BRIDGE_OPT_RECORD_CONFERENCE
Set if the conference should be recorded
BRIDGE_OPT_VIDEO_SRC_LAST_MARKED
Set if conference should feed video of last marked user to all participants.
BRIDGE_OPT_VIDEO_SRC_FIRST_MARKED
Set if conference should feed video of first marked user to all participants.
BRIDGE_OPT_VIDEO_SRC_FOLLOW_TALKER
Set if conference set the video feed to follow the loudest talker.
BRIDGE_OPT_RECORD_FILE_APPEND
Set if the record file should be appended to between start/stops.
BRIDGE_OPT_RECORD_FILE_TIMESTAMP
Set if the record file should have a timestamp appended
BRIDGE_OPT_BINAURAL_ACTIVE
Set if binaural convolution is activated
BRIDGE_OPT_VIDEO_SRC_SFU
Selective forwarding unit
BRIDGE_OPT_REMB_BEHAVIOR_AVERAGE
The average of all REMB reports is sent to the sender
BRIDGE_OPT_REMB_BEHAVIOR_LOWEST
The lowest estimated maximum bitrate is sent to the sender
BRIDGE_OPT_REMB_BEHAVIOR_HIGHEST
The highest estimated maximum bitrate is sent to the sender
BRIDGE_OPT_ENABLE_EVENTS
Enable sending events to participants
BRIDGE_OPT_REMB_BEHAVIOR_AVERAGE_ALL
The average of all REMB reports in the entire bridge is sent to each sender
BRIDGE_OPT_REMB_BEHAVIOR_LOWEST_ALL
The lowest estimated maximum bitrate from all receivers is sent to each sender
BRIDGE_OPT_REMB_BEHAVIOR_HIGHEST_ALL
The highest estimated maximum bitrate from all receivers is sent to each sender
BRIDGE_OPT_REMB_BEHAVIOR_FORCE
Force the REMB estimated bitrate to that specifiec in remb_estimated_bitrate
Definition at line 75 of file confbridge.h.
{
    BRIDGE_OPT_RECORD_CONFERENCE = (1 << 0), /*!< Set if the conference should be recorded */
    BRIDGE_OPT_VIDEO_SRC_LAST_MARKED = (1 << 1), /*!< Set if conference should feed video of last marked user to all participants. */
    BRIDGE_OPT_VIDEO_SRC_FIRST_MARKED = (1 << 2), /*!< Set if conference should feed video of first marked user to all participants. */
    BRIDGE_OPT_VIDEO_SRC_FOLLOW_TALKER = (1 << 3), /*!< Set if conference set the video feed to follow the loudest talker.  */
    BRIDGE_OPT_RECORD_FILE_APPEND = (1 << 4), /*!< Set if the record file should be appended to between start/stops.  */
    BRIDGE_OPT_RECORD_FILE_TIMESTAMP = (1 << 5), /*!< Set if the record file should have a timestamp appended */
    BRIDGE_OPT_BINAURAL_ACTIVE = (1 << 6), /*!< Set if binaural convolution is activated */
    BRIDGE_OPT_VIDEO_SRC_SFU = (1 << 7), /*!< Selective forwarding unit */
    BRIDGE_OPT_REMB_BEHAVIOR_AVERAGE = (1 << 8), /*!< The average of all REMB reports is sent to the sender */
    BRIDGE_OPT_REMB_BEHAVIOR_LOWEST = (1 << 9), /*!< The lowest estimated maximum bitrate is sent to the sender */
    BRIDGE_OPT_REMB_BEHAVIOR_HIGHEST = (1 << 10), /*!< The highest estimated maximum bitrate is sent to the sender */
    BRIDGE_OPT_ENABLE_EVENTS = (1 << 11), /*!< Enable sending events to participants */
    BRIDGE_OPT_REMB_BEHAVIOR_AVERAGE_ALL = (1 << 12), /*!< The average of all REMB reports in the entire bridge is sent to each sender */
    BRIDGE_OPT_REMB_BEHAVIOR_LOWEST_ALL = (1 << 13), /*!< The lowest estimated maximum bitrate from all receivers is sent to each sender */
    BRIDGE_OPT_REMB_BEHAVIOR_HIGHEST_ALL = (1 << 14), /*!< The highest estimated maximum bitrate from all receivers is sent to each sender */
    BRIDGE_OPT_REMB_BEHAVIOR_FORCE = (1 << 15), /*!< Force the REMB estimated bitrate to that specifiec in remb_estimated_bitrate */
 };
conf_menu_action_id
enum conf_menu_action_id
Enumerator
MENU_ACTION_TOGGLE_MUTE
MENU_ACTION_PLAYBACK
MENU_ACTION_PLAYBACK_AND_CONTINUE
MENU_ACTION_INCREASE_LISTENING
MENU_ACTION_DECREASE_LISTENING
MENU_ACTION_RESET_LISTENING
MENU_ACTION_RESET_TALKING
MENU_ACTION_INCREASE_TALKING
MENU_ACTION_DECREASE_TALKING
MENU_ACTION_DIALPLAN_EXEC
MENU_ACTION_ADMIN_TOGGLE_LOCK
MENU_ACTION_ADMIN_KICK_LAST
MENU_ACTION_LEAVE
MENU_ACTION_NOOP
MENU_ACTION_SET_SINGLE_VIDEO_SRC
MENU_ACTION_RELEASE_SINGLE_VIDEO_SRC
MENU_ACTION_PARTICIPANT_COUNT
MENU_ACTION_ADMIN_TOGGLE_MUTE_PARTICIPANTS
MENU_ACTION_TOGGLE_BINAURAL
Definition at line 94 of file confbridge.h.
{
    MENU_ACTION_TOGGLE_MUTE = 1,
    MENU_ACTION_PLAYBACK,
    MENU_ACTION_PLAYBACK_AND_CONTINUE,
    MENU_ACTION_INCREASE_LISTENING,
    MENU_ACTION_DECREASE_LISTENING,
    MENU_ACTION_RESET_LISTENING,
    MENU_ACTION_RESET_TALKING,
    MENU_ACTION_INCREASE_TALKING,
    MENU_ACTION_DECREASE_TALKING,
    MENU_ACTION_DIALPLAN_EXEC,
    MENU_ACTION_ADMIN_TOGGLE_LOCK,
    MENU_ACTION_ADMIN_KICK_LAST,
    MENU_ACTION_LEAVE,
    MENU_ACTION_NOOP,
    MENU_ACTION_SET_SINGLE_VIDEO_SRC,
    MENU_ACTION_RELEASE_SINGLE_VIDEO_SRC,
    MENU_ACTION_PARTICIPANT_COUNT,
    MENU_ACTION_ADMIN_TOGGLE_MUTE_PARTICIPANTS,
    MENU_ACTION_TOGGLE_BINAURAL,
 };
conf_sounds
enum conf_sounds
Enumerator
CONF_SOUND_HAS_JOINED
CONF_SOUND_HAS_LEFT
CONF_SOUND_KICKED
CONF_SOUND_MUTED
CONF_SOUND_UNMUTED
CONF_SOUND_ONLY_ONE
CONF_SOUND_THERE_ARE
CONF_SOUND_OTHER_IN_PARTY
CONF_SOUND_PLACE_IN_CONF
CONF_SOUND_WAIT_FOR_LEADER
CONF_SOUND_LEADER_HAS_LEFT
CONF_SOUND_GET_PIN
CONF_SOUND_INVALID_PIN
CONF_SOUND_ONLY_PERSON
CONF_SOUND_LOCKED
CONF_SOUND_LOCKED_NOW
CONF_SOUND_UNLOCKED_NOW
CONF_SOUND_ERROR_MENU
CONF_SOUND_JOIN
CONF_SOUND_LEAVE
CONF_SOUND_PARTICIPANTS_MUTED
CONF_SOUND_PARTICIPANTS_UNMUTED
CONF_SOUND_BEGIN
CONF_SOUND_BINAURAL_ON
CONF_SOUND_BINAURAL_OFF
Definition at line 167 of file confbridge.h.
                  {
    CONF_SOUND_HAS_JOINED,
    CONF_SOUND_HAS_LEFT,
    CONF_SOUND_KICKED,
    CONF_SOUND_MUTED,
    CONF_SOUND_UNMUTED,
    CONF_SOUND_ONLY_ONE,
    CONF_SOUND_THERE_ARE,
    CONF_SOUND_OTHER_IN_PARTY,
    CONF_SOUND_PLACE_IN_CONF,
    CONF_SOUND_WAIT_FOR_LEADER,
    CONF_SOUND_LEADER_HAS_LEFT,
    CONF_SOUND_GET_PIN,
    CONF_SOUND_INVALID_PIN,
    CONF_SOUND_ONLY_PERSON,
    CONF_SOUND_LOCKED,
    CONF_SOUND_LOCKED_NOW,
    CONF_SOUND_UNLOCKED_NOW,
    CONF_SOUND_ERROR_MENU,
    CONF_SOUND_JOIN,
    CONF_SOUND_LEAVE,
    CONF_SOUND_PARTICIPANTS_MUTED,
    CONF_SOUND_PARTICIPANTS_UNMUTED,
    CONF_SOUND_BEGIN,
    CONF_SOUND_BINAURAL_ON,
    CONF_SOUND_BINAURAL_OFF,
 };
user_profile_flags
enum user_profile_flags
Enumerator
USER_OPT_ADMIN
Set if the caller is an administrator
USER_OPT_NOONLYPERSON
Set if the "you are currently the only person in this conference" sound file should not be played
USER_OPT_MARKEDUSER
Set if the caller is a marked user
USER_OPT_STARTMUTED
Set if the caller should be initially set muted
USER_OPT_MUSICONHOLD
Set if music on hold should be played if nobody else is in the conference bridge
USER_OPT_QUIET
Set if no audio prompts should be played
USER_OPT_ANNOUNCEUSERCOUNT
Set if the number of users should be announced to the caller
USER_OPT_WAITMARKED
Set if the user must wait for a marked user before starting
USER_OPT_ENDMARKED
Set if the user should be kicked after the last Marked user exits
USER_OPT_DENOISE
Sets if denoise filter should be used on audio before mixing.
USER_OPT_ANNOUNCE_JOIN_LEAVE
Sets if the user's name should be recorded and announced on join and leave.
USER_OPT_TALKER_DETECT
Sets if start and stop talking events should generated for this user over AMI.
USER_OPT_DROP_SILENCE
Sets if silence should be dropped from the mix or not.
USER_OPT_DTMF_PASS
Sets if dtmf should be passed into the conference or not
USER_OPT_ANNOUNCEUSERCOUNTALL
Sets if the number of users should be announced to everyone.
USER_OPT_JITTERBUFFER
Places a jitterbuffer on the user.
USER_OPT_ANNOUNCE_JOIN_LEAVE_REVIEW
modifies ANNOUNCE_JOIN_LEAVE - user reviews the recording before continuing
USER_OPT_SEND_EVENTS
Send text message events to users
USER_OPT_ECHO_EVENTS
Send events only to the admin(s)
USER_OPT_TEXT_MESSAGING
Send text messages to the user
USER_OPT_ANSWER_CHANNEL
Sets if the channel should be answered if currently unanswered
Definition at line 51 of file confbridge.h.
{
    USER_OPT_ADMIN =        (1 << 0), /*!< Set if the caller is an administrator */
    USER_OPT_NOONLYPERSON = (1 << 1), /*!< Set if the "you are currently the only person in this conference" sound file should not be played */
    USER_OPT_MARKEDUSER =   (1 << 2), /*!< Set if the caller is a marked user */
    USER_OPT_STARTMUTED =   (1 << 3), /*!< Set if the caller should be initially set muted */
    USER_OPT_MUSICONHOLD =  (1 << 4), /*!< Set if music on hold should be played if nobody else is in the conference bridge */
    USER_OPT_QUIET =        (1 << 5), /*!< Set if no audio prompts should be played */
    USER_OPT_ANNOUNCEUSERCOUNT = (1 << 6), /*!< Set if the number of users should be announced to the caller */
    USER_OPT_WAITMARKED =   (1 << 7), /*!< Set if the user must wait for a marked user before starting */
    USER_OPT_ENDMARKED =    (1 << 8), /*!< Set if the user should be kicked after the last Marked user exits */
    USER_OPT_DENOISE =      (1 << 9), /*!< Sets if denoise filter should be used on audio before mixing. */
    USER_OPT_ANNOUNCE_JOIN_LEAVE = (1 << 10), /*!< Sets if the user's name should be recorded and announced on join and leave. */
    USER_OPT_TALKER_DETECT = (1 << 11), /*!< Sets if start and stop talking events should generated for this user over AMI. */
    USER_OPT_DROP_SILENCE =  (1 << 12), /*!< Sets if silence should be dropped from the mix or not. */
    USER_OPT_DTMF_PASS    =  (1 << 13), /*!< Sets if dtmf should be passed into the conference or not */
    USER_OPT_ANNOUNCEUSERCOUNTALL = (1 << 14), /*!< Sets if the number of users should be announced to everyone. */
    USER_OPT_JITTERBUFFER =  (1 << 15), /*!< Places a jitterbuffer on the user. */
    USER_OPT_ANNOUNCE_JOIN_LEAVE_REVIEW = (1 << 16), /*!< modifies ANNOUNCE_JOIN_LEAVE - user reviews the recording before continuing */
    USER_OPT_SEND_EVENTS = (1 << 17), /*!< Send text message events to users */
    USER_OPT_ECHO_EVENTS = (1 << 18), /*!< Send events only to the admin(s) */
    USER_OPT_TEXT_MESSAGING = (1 << 19), /*!< Send text messages to the user */
    USER_OPT_ANSWER_CHANNEL = (1 << 20), /*!< Sets if the channel should be answered if currently unanswered */
 };
Function Documentation
async_play_sound_file()
int async_play_sound_file (struct confbridge_conference * conference, const char * filename, struct ast_channel * initiator)
Play sound file into conference bridge asynchronously.
If the initiator parameter is non-NULL, then the playback will wait for that initiator channel to get back in the bridge before playing the sound file. This way, the initiator has no danger of hearing a "clipped" file.
Parameters
conference The conference bridge to play sound file into
filename Sound file to play
initiator Channel that initiated playback.
Return values
0 success
-1 failure
Definition at line 2282 of file app_confbridge.c.
References async_play_sound_helper().
Referenced by action_toggle_mute_participants(), confbridge_exec(), and leave_marked().
 {
    return async_play_sound_helper(conference, filename, -1, initiator);
 }
async_play_sound_ready()
void async_play_sound_ready (struct ast_channel * chan)
Indicate the initiator of an async sound file is ready for it to play.
When playing an async sound file, the initiator is typically either out of the bridge or not in a position to hear the queued announcement. This function lets the announcement thread know that the initiator is now ready for the sound to play.
If an async announcement was queued and no initiator channel was provided, then this is a no-op
Parameters
chan The channel that initiated the async announcement
Definition at line 2288 of file app_confbridge.c.
References ast_channel_datastore_find(), ast_channel_lock, ast_channel_unlock, ast_cond_signal, ast_mutex_lock, ast_mutex_unlock, async_datastore_data::cond, ast_datastore::data, async_datastore_data::lock, NULL, and async_datastore_data::wait.
Referenced by conf_handle_dtmf(), confbridge_exec(), and join_callback().
 {
    struct ast_datastore *async_datastore;
    struct async_datastore_data *add;
    ast_channel_lock(chan);
    async_datastore = ast_channel_datastore_find(chan, &async_datastore_info, NULL);
    ast_channel_unlock(chan);
    if (!async_datastore) {
       return;
    }
    add = async_datastore->data;
    ast_mutex_lock(&add->lock);
    add->wait = 0;
    ast_cond_signal(&add->cond);
    ast_mutex_unlock(&add->lock);
 }
conf_add_post_join_action()
int conf_add_post_join_action (struct confbridge_user * user, int(*)(struct confbridge_user *user) func)
Queue a function to run with the given conference bridge user as an argument once the state transition is complete.
Parameters
user The conference bridge user to pass to the function
func The function to queue
Return values
0 success
non-zero failure
Definition at line 1445 of file app_confbridge.c.
References ast_calloc, AST_LIST_INSERT_TAIL, post_join_action::func, post_join_action::list, and confbridge_user::post_join_list.
Referenced by conf_default_join_waitmarked(), join_marked(), join_unmarked(), and transition_to_marked().
 {
    struct post_join_action *action;
    if (!(action = ast_calloc(1, sizeof(*action)))) {
       return -1;
    }
    action->func = func;
    AST_LIST_INSERT_TAIL(&user->post_join_list, action, list);
    return 0;
 }
conf_add_user_active()
void conf_add_user_active (struct confbridge_conference * conference, struct confbridge_user * user)
Add a conference bridge user as an unmarked active user of the conference.
Parameters
conference The conference bridge to add the user to
user The conference bridge user to add to the conference
Definition at line 4303 of file app_confbridge.c.
References confbridge_conference::active_list, confbridge_conference::activeusers, and AST_LIST_INSERT_TAIL.
Referenced by join_active(), and join_unmarked().
 {
    AST_LIST_INSERT_TAIL(&conference->active_list, user, list);
    conference->activeusers++;
 }
conf_add_user_marked()
void conf_add_user_marked (struct confbridge_conference * conference, struct confbridge_user * user)
Add a conference bridge user as a marked active user of the conference.
Parameters
conference The conference bridge to add the user to
user The conference bridge user to add to the conference
Definition at line 4309 of file app_confbridge.c.
References confbridge_conference::active_list, confbridge_conference::activeusers, AST_LIST_INSERT_TAIL, and confbridge_conference::markedusers.
Referenced by join_marked().
 {
    AST_LIST_INSERT_TAIL(&conference->active_list, user, list);
    conference->activeusers++;
    conference->markedusers++;
 }
conf_add_user_waiting()
void conf_add_user_waiting (struct confbridge_conference * conference, struct confbridge_user * user)
Add a conference bridge user as an waiting user of the conference.
Parameters
conference The conference bridge to add the user to
user The conference bridge user to add to the conference
Definition at line 4316 of file app_confbridge.c.
References AST_LIST_INSERT_TAIL, confbridge_conference::waiting_list, and confbridge_conference::waitingusers.
Referenced by conf_default_join_waitmarked().
 {
    AST_LIST_INSERT_TAIL(&conference->waiting_list, user, list);
    conference->waitingusers++;
 }
conf_announce_channel_push()
int conf_announce_channel_push (struct ast_channel * ast)
Push the announcer channel into the conference.
Since
12.0.0
Parameters
ast Either channel in the announcer channel pair.
Return values
0 on success.
-1 on error.
Definition at line 144 of file conf_chan_announce.c.
References ao2_cleanup, ao2_lock, ao2_ref, ao2_unlock, AST_BRIDGE_CHANNEL_FLAG_IMMOVABLE, ast_bridge_features_new(), ast_bridge_impart(), AST_BRIDGE_IMPART_CHAN_INDEPENDENT, ast_channel_tech_pvt(), ast_set_flag, AST_UNREAL_CARETAKER_THREAD, ast_bridge_features::feature_flags, lock, NULL, RAII_VAR, and SCOPED_CHANNELLOCK.
Referenced by push_announcer().
 {
    struct ast_bridge_features *features;
    struct ast_channel *chan;
    RAII_VAR(struct announce_pvt *, p, NULL, ao2_cleanup);
    {
       SCOPED_CHANNELLOCK(lock, ast);
       p = ast_channel_tech_pvt(ast);
       if (!p) {
          return -1;
       }
       ao2_ref(p, +1);
       chan = p->base.chan;
       if (!chan) {
          return -1;
       }
    }
    features = ast_bridge_features_new();
    if (!features) {
       return -1;
    }
    ast_set_flag(&features->feature_flags, AST_BRIDGE_CHANNEL_FLAG_IMMOVABLE);
    /* Impart the output channel into the bridge */
    if (ast_bridge_impart(p->bridge, chan, NULL, features,
       AST_BRIDGE_IMPART_CHAN_INDEPENDENT)) {
       return -1;
    }
    ao2_lock(p);
    ast_set_flag(&p->base, AST_UNREAL_CARETAKER_THREAD);
    ao2_unlock(p);
    return 0;
 }
conf_announce_get_tech()
struct ast_channel_tech* conf_announce_get_tech (void)
Get ConfBridge announce channel technology struct.
Since
12.0.0
Returns
ConfBridge announce channel technology.
Definition at line 139 of file conf_chan_announce.c.
References announce_tech.
Referenced by announce_request(), load_module(), and unload_module().
 {
    return &announce_tech;
 }
conf_bridge_profile_copy()
void conf_bridge_profile_copy (struct bridge_profile * dst, struct bridge_profile * src)
copies a bridge profile
Note
conf_bridge_profile_destroy must be called on the dst structure
Definition at line 2523 of file conf_config_parser.c.
References ao2_ref, and bridge_profile::sounds.
Referenced by conf_find_bridge_profile(), and join_conference_bridge().
 {
    *dst = *src;
    if (src->sounds) {
       ao2_ref(src->sounds, +1);
    }
 }
conf_bridge_profile_destroy()
void conf_bridge_profile_destroy (struct bridge_profile * b_profile)
Destroy a bridge profile found by 'conf_find_bridge_profile'.
Definition at line 2531 of file conf_config_parser.c.
References ao2_ref, NULL, and bridge_profile::sounds.
Referenced by confbridge_exec(), destroy_conference_bridge(), func_confbridge_data_destructor(), func_confbridge_helper(), and handle_cli_confbridge_show_bridge_profile().
 {
    if (b_profile->sounds) {
       ao2_ref(b_profile->sounds, -1);
       b_profile->sounds = NULL;
    }
 }
conf_destroy_config()
void conf_destroy_config (void)
destroy the information loaded from the confbridge.conf file
Definition at line 2694 of file conf_config_parser.c.
References aco_info_destroy(), ao2_global_obj_release, ARRAY_LEN, ast_cli_unregister_multiple(), and cfg_handle.
Referenced by conf_load_config(), and unload_module().
 {
    ast_cli_unregister_multiple(cli_confbridge_parser, ARRAY_LEN(cli_confbridge_parser));
    aco_info_destroy(&cfg_info);
    ao2_global_obj_release(cfg_handle);
 }
conf_ended()
void conf_ended (struct confbridge_conference * conference)
Callback to be called when the conference has become empty.
Parameters
conference The conference bridge
Definition at line 1473 of file app_confbridge.c.
References ao2_lock, ao2_unlink, ao2_unlock, ast_context_remove_extension(), ast_strlen_zero, confbridge_conference::b_profile, conf_stop_record(), E_MATCH, confbridge_conference::name, NULL, pbx_find_extension(), bridge_profile::regcontext, send_conf_end_event(), and pbx_find_info::stacklen.
Referenced by transition_to_empty().
 {
    struct pbx_find_info q = { .stacklen = 0 };
    /* Called with a reference to conference */
    ao2_unlink(conference_bridges, conference);
    send_conf_end_event(conference);
    if (!ast_strlen_zero(conference->b_profile.regcontext) &&
          pbx_find_extension(NULL, NULL, &q, conference->b_profile.regcontext,
             conference->name, 1, NULL, "", E_MATCH)) {
       ast_context_remove_extension(conference->b_profile.regcontext,
             conference->name, 1, NULL);
    }
    ao2_lock(conference);
    conf_stop_record(conference);
    ao2_unlock(conference);
 }
conf_find_bridge()
struct confbridge_conference* conf_find_bridge (const char * conference_name)
Find a confbridge by name.
Since
13.22.0
15.5.0
Parameters
confbridge_name The name to search for
Returns
ConfBridge (which must be unreffed) or NULL.
Definition at line 787 of file app_confbridge.c.
References ao2_find, and OBJ_KEY.
Referenced by confbridge_publish_manager_event().
 {
    return ao2_find(conference_bridges, conference_name, OBJ_KEY);
 }
conf_find_bridge_profile()
const struct bridge_profile* conf_find_bridge_profile (struct ast_channel * chan, const char * bridge_profile_name, struct bridge_profile * result)
Find a bridge profile given a bridge profile's name and store that profile in result structure.
Parameters
chan channel the bridge profile is requested for
bridge_profile_name name of the profile requested (optional)
result data contained by the bridge profile will be copied to this struct pointer
If bridge_profile_name is not provided, this function will check for the presence of a bridge profile set by the CONFBRIDGE function on a channel datastore. If that doesn't exist, the default_bridge profile is used.
Return values
bridge profile on success
NULL on failure
Definition at line 2539 of file conf_config_parser.c.
References ao2_cleanup, ao2_find, ao2_global_obj_ref, ao2_lock, ao2_ref, ao2_unlock, ast_channel_datastore_find(), ast_channel_lock, ast_channel_unlock, ast_strlen_zero, func_confbridge_data::b_profile, func_confbridge_data::b_usable, cfg_handle, conf_bridge_profile_copy(), ast_datastore::data, DEFAULT_BRIDGE_PROFILE, NULL, OBJ_KEY, RAII_VAR, and result.
Referenced by bridge_template_handler(), confbridge_exec(), and handle_cli_confbridge_show_bridge_profile().
 {
    struct bridge_profile *tmp2;
    struct ast_datastore *datastore = NULL;
    struct func_confbridge_data *b_data = NULL;
    RAII_VAR(struct confbridge_cfg *, cfg, ao2_global_obj_ref(cfg_handle), ao2_cleanup);
    if (chan && ast_strlen_zero(bridge_profile_name)) {
       ast_channel_lock(chan);
       datastore = ast_channel_datastore_find(chan, &confbridge_datastore, NULL);
       ast_channel_unlock(chan);
       if (datastore) {
          b_data = datastore->data;
          if (b_data->b_usable) {
             conf_bridge_profile_copy(result, &b_data->b_profile);
             return result;
          }
       }
    }
    if (!cfg) {
       return NULL;
    }
    if (ast_strlen_zero(bridge_profile_name)) {
       bridge_profile_name = DEFAULT_BRIDGE_PROFILE;
    }
    if (!(tmp2 = ao2_find(cfg->bridge_profiles, bridge_profile_name, OBJ_KEY))) {
       return NULL;
    }
    ao2_lock(tmp2);
    conf_bridge_profile_copy(result, tmp2);
    ao2_unlock(tmp2);
    ao2_ref(tmp2, -1);
    return result;
 }
conf_find_menu_entry_by_sequence()
int conf_find_menu_entry_by_sequence (const char * dtmf_sequence, struct conf_menu * menu, struct conf_menu_entry * result)
Finds a menu_entry in a menu structure matched by DTMF sequence.
Note
the menu entry found must be destroyed using conf_menu_entry_destroy()
Return values
1 success, entry is found and stored in result
0 failure, no entry found for given DTMF sequence
Definition at line 2610 of file conf_config_parser.c.
References ao2_lock, ao2_unlock, AST_LIST_TRAVERSE, copy_menu_entry(), conf_menu_entry::dtmf, conf_menu::entries, and NULL.
Referenced by action_playback_and_continue().
 {
    struct conf_menu_entry *menu_entry = NULL;
    ao2_lock(menu);
    AST_LIST_TRAVERSE(&menu->entries, menu_entry, entry) {
       if (!strcasecmp(menu_entry->dtmf, dtmf_sequence)) {
          copy_menu_entry(result, menu_entry);
          ao2_unlock(menu);
          return 1;
       }
    }
    ao2_unlock(menu);
    return 0;
 }
conf_find_user_profile()
const struct user_profile* conf_find_user_profile (struct ast_channel * chan, const char * user_profile_name, struct user_profile * result)
find a user profile given a user profile's name and store that profile in result structure.
Parameters
chan channel the user profile is requested for
user_profile_name name of the profile requested (optional)
result data contained by the user profile will be copied to this struct pointer
If user_profile_name is not provided, this function will check for the presence of a user profile set by the CONFBRIDGE function on a channel datastore. If that doesn't exist, the default_user profile is used.
Return values
user profile on success
NULL on failure
Definition at line 2486 of file conf_config_parser.c.
References ao2_cleanup, ao2_find, ao2_global_obj_ref, ao2_lock, ao2_ref, ao2_unlock, ast_channel_datastore_find(), ast_channel_lock, ast_channel_unlock, ast_strlen_zero, cfg_handle, conf_user_profile_copy(), ast_datastore::data, DEFAULT_USER_PROFILE, NULL, OBJ_KEY, RAII_VAR, result, func_confbridge_data::u_profile, and func_confbridge_data::u_usable.
Referenced by conf_send_event_to_participants(), confbridge_exec(), handle_cli_confbridge_show_user_profile(), and user_template_handler().
 {
    struct user_profile *tmp2;
    struct ast_datastore *datastore = NULL;
    struct func_confbridge_data *b_data = NULL;
    RAII_VAR(struct confbridge_cfg *, cfg, ao2_global_obj_ref(cfg_handle), ao2_cleanup);
    if (chan && ast_strlen_zero(user_profile_name)) {
       ast_channel_lock(chan);
       datastore = ast_channel_datastore_find(chan, &confbridge_datastore, NULL);
       ast_channel_unlock(chan);
       if (datastore) {
          b_data = datastore->data;
          if (b_data->u_usable) {
             conf_user_profile_copy(result, &b_data->u_profile);
             return result;
          }
       }
    }
    if (!cfg) {
       return NULL;
    }
    if (ast_strlen_zero(user_profile_name)) {
       user_profile_name = DEFAULT_USER_PROFILE;
    }
    if (!(tmp2 = ao2_find(cfg->user_profiles, user_profile_name, OBJ_KEY))) {
       return NULL;
    }
    ao2_lock(tmp2);
    conf_user_profile_copy(result, tmp2);
    ao2_unlock(tmp2);
    ao2_ref(tmp2, -1);
    return result;
 }
conf_get_sound()
const char* conf_get_sound (enum conf_sounds sound, struct bridge_profile_sounds * custom_sounds)
Looks to see if sound file is stored in bridge profile sounds, if not default sound is provided.
Definition at line 526 of file app_confbridge.c.
References bridge_profile_sounds::begin, bridge_profile_sounds::binauraloff, bridge_profile_sounds::binauralon, CONF_SOUND_BEGIN, CONF_SOUND_BINAURAL_OFF, CONF_SOUND_BINAURAL_ON, CONF_SOUND_ERROR_MENU, CONF_SOUND_GET_PIN, CONF_SOUND_HAS_JOINED, CONF_SOUND_HAS_LEFT, CONF_SOUND_INVALID_PIN, CONF_SOUND_JOIN, CONF_SOUND_KICKED, CONF_SOUND_LEADER_HAS_LEFT, CONF_SOUND_LEAVE, CONF_SOUND_LOCKED, CONF_SOUND_LOCKED_NOW, CONF_SOUND_MUTED, CONF_SOUND_ONLY_ONE, CONF_SOUND_ONLY_PERSON, CONF_SOUND_OTHER_IN_PARTY, CONF_SOUND_PARTICIPANTS_MUTED, CONF_SOUND_PARTICIPANTS_UNMUTED, CONF_SOUND_PLACE_IN_CONF, CONF_SOUND_THERE_ARE, CONF_SOUND_UNLOCKED_NOW, CONF_SOUND_UNMUTED, CONF_SOUND_WAIT_FOR_LEADER, bridge_profile_sounds::errormenu, bridge_profile_sounds::getpin, bridge_profile_sounds::hasjoin, bridge_profile_sounds::hasleft, bridge_profile_sounds::invalidpin, bridge_profile_sounds::join, bridge_profile_sounds::kicked, bridge_profile_sounds::leaderhasleft, bridge_profile_sounds::leave, bridge_profile_sounds::locked, bridge_profile_sounds::lockednow, bridge_profile_sounds::muted, bridge_profile_sounds::onlyone, bridge_profile_sounds::onlyperson, bridge_profile_sounds::otherinparty, bridge_profile_sounds::participantsmuted, bridge_profile_sounds::participantsunmuted, bridge_profile_sounds::placeintoconf, S_OR, bridge_profile_sounds::thereare, bridge_profile_sounds::unlockednow, bridge_profile_sounds::unmuted, and bridge_profile_sounds::waitforleader.
Referenced by action_kick_last(), action_toggle_binaural(), action_toggle_mute(), action_toggle_mute_participants(), announce_user_count(), conf_get_pin(), conf_handle_inactive_waitmarked(), conf_handle_only_person(), confbridge_exec(), execute_menu_entry(), handle_cli_confbridge_show_bridge_profile(), join_conference_bridge(), leave_marked(), and post_join_play_begin().
 {
    switch (sound) {
    case CONF_SOUND_HAS_JOINED:
       return S_OR(custom_sounds->hasjoin, "conf-hasjoin");
    case CONF_SOUND_HAS_LEFT:
       return S_OR(custom_sounds->hasleft, "conf-hasleft");
    case CONF_SOUND_KICKED:
       return S_OR(custom_sounds->kicked, "conf-kicked");
    case CONF_SOUND_MUTED:
       return S_OR(custom_sounds->muted, "conf-muted");
    case CONF_SOUND_UNMUTED:
       return S_OR(custom_sounds->unmuted, "conf-unmuted");
    case CONF_SOUND_BINAURAL_ON:
       return S_OR(custom_sounds->binauralon, "confbridge-binaural-on");
    case CONF_SOUND_BINAURAL_OFF:
       return S_OR(custom_sounds->binauraloff, "confbridge-binaural-off");
    case CONF_SOUND_ONLY_ONE:
       return S_OR(custom_sounds->onlyone, "conf-onlyone");
    case CONF_SOUND_THERE_ARE:
       return S_OR(custom_sounds->thereare, "conf-thereare");
    case CONF_SOUND_OTHER_IN_PARTY:
       return S_OR(custom_sounds->otherinparty, "conf-otherinparty");
    case CONF_SOUND_PLACE_IN_CONF:
       return S_OR(custom_sounds->placeintoconf, "conf-placeintoconf");
    case CONF_SOUND_WAIT_FOR_LEADER:
       return S_OR(custom_sounds->waitforleader, "conf-waitforleader");
    case CONF_SOUND_LEADER_HAS_LEFT:
       return S_OR(custom_sounds->leaderhasleft, "conf-leaderhasleft");
    case CONF_SOUND_GET_PIN:
       return S_OR(custom_sounds->getpin, "conf-getpin");
    case CONF_SOUND_INVALID_PIN:
       return S_OR(custom_sounds->invalidpin, "conf-invalidpin");
    case CONF_SOUND_ONLY_PERSON:
       return S_OR(custom_sounds->onlyperson, "conf-onlyperson");
    case CONF_SOUND_LOCKED:
       return S_OR(custom_sounds->locked, "conf-locked");
    case CONF_SOUND_LOCKED_NOW:
       return S_OR(custom_sounds->lockednow, "conf-lockednow");
    case CONF_SOUND_UNLOCKED_NOW:
       return S_OR(custom_sounds->unlockednow, "conf-unlockednow");
    case CONF_SOUND_ERROR_MENU:
       return S_OR(custom_sounds->errormenu, "conf-errormenu");
    case CONF_SOUND_JOIN:
       return S_OR(custom_sounds->join, "confbridge-join");
    case CONF_SOUND_LEAVE:
       return S_OR(custom_sounds->leave, "confbridge-leave");
    case CONF_SOUND_PARTICIPANTS_MUTED:
       return S_OR(custom_sounds->participantsmuted, "conf-now-muted");
    case CONF_SOUND_PARTICIPANTS_UNMUTED:
       return S_OR(custom_sounds->participantsunmuted, "conf-now-unmuted");
    case CONF_SOUND_BEGIN:
       return S_OR(custom_sounds->begin, "confbridge-conf-begin");
    }
    return "";
 }
conf_handle_dtmf()
int conf_handle_dtmf (struct ast_bridge_channel * bridge_channel, struct confbridge_user * user, struct conf_menu_entry * menu_entry, struct conf_menu * menu)
Once a DTMF sequence matches a sequence in the user's DTMF menu, this function will get called to perform the menu action.
Parameters
bridge_channel Bridged channel this is involving
user the conference user to perform the action on.
menu_entry the menu entry that invoked this callback to occur.
menu an AO2 referenced pointer to the entire menu structure the menu_entry derived from.
Note
The menu_entry is a deep copy of the entry found in the menu structure. This allows for the menu_entry to be accessed without requiring the menu lock. If the menu must be accessed, the menu lock must be held. Reference counting of the menu structure is handled outside of the scope of this function.
Return values
0 success
-1 failure
Definition at line 3214 of file app_confbridge.c.
References async_play_sound_ready(), ast_bridge_channel::chan, conf_moh_suspend(), conf_moh_unsuspend(), confbridge_user::conference, and execute_menu_entry().
Referenced by menu_hook_callback().
 {
    /* See if music on hold is playing */
    conf_moh_suspend(user);
    /* execute the list of actions associated with this menu entry */
    execute_menu_entry(user->conference, user, bridge_channel, menu_entry, menu);
    /* See if music on hold needs to be started back up again */
    conf_moh_unsuspend(user);
    async_play_sound_ready(bridge_channel->chan);
    return 0;
 }
conf_handle_first_join()
void conf_handle_first_join (struct confbridge_conference * conference)
Callback to execute any time we transition from zero to one active users.
Parameters
conference The conference bridge with a single active user joined
Return values
0 success
-1 failure
Definition at line 1457 of file app_confbridge.c.
References AST_DEVICE_INUSE, AST_DEVSTATE_CACHABLE, ast_devstate_changed(), and confbridge_conference::name.
Referenced by join_marked(), join_unmarked(), and join_waitmarked().
 {
    ast_devstate_changed(AST_DEVICE_INUSE, AST_DEVSTATE_CACHABLE, "confbridge:%s", conference->name);
 }
conf_handle_inactive_waitmarked()
int conf_handle_inactive_waitmarked (struct confbridge_user * user)
Handle actions every time a waitmarked user joins w/o a marked user present.
Parameters
user The waitmarked user
Return values
0 success
-1 failure
Definition at line 1421 of file app_confbridge.c.
References ast_test_flag, confbridge_conference::b_profile, conf_get_sound(), CONF_SOUND_WAIT_FOR_LEADER, confbridge_user::conference, play_prompt_to_user(), bridge_profile::sounds, confbridge_user::u_profile, and USER_OPT_QUIET.
Referenced by conf_default_join_waitmarked().
 {
    /* If we have not been quieted play back that they are waiting for the leader */
    if (!ast_test_flag(&user->u_profile, USER_OPT_QUIET) && play_prompt_to_user(user,
          conf_get_sound(CONF_SOUND_WAIT_FOR_LEADER, user->conference->b_profile.sounds))) {
       /* user hungup while the sound was playing */
       return -1;
    }
    return 0;
 }
conf_handle_only_person()
int conf_handle_only_person (struct confbridge_user * user)
Handle actions whenever an user joins an empty conference.
Parameters
user The user
Definition at line 1432 of file app_confbridge.c.
References ast_test_flag, confbridge_conference::b_profile, conf_get_sound(), CONF_SOUND_ONLY_PERSON, confbridge_user::conference, play_prompt_to_user(), bridge_profile::sounds, confbridge_user::u_profile, USER_OPT_NOONLYPERSON, and USER_OPT_QUIET.
Referenced by join_marked(), and join_unmarked().
 {
    /* If audio prompts have not been quieted or this prompt quieted play it on out */
    if (!ast_test_flag(&user->u_profile, USER_OPT_QUIET | USER_OPT_NOONLYPERSON)) {
       if (play_prompt_to_user(user,
          conf_get_sound(CONF_SOUND_ONLY_PERSON, user->conference->b_profile.sounds))) {
          /* user hungup while the sound was playing */
          return -1;
       }
    }
    return 0;
 }
conf_handle_second_active()
void conf_handle_second_active (struct confbridge_conference * conference)
Handle when a conference moves to having more than one active participant.
Parameters
conference The conference bridge with more than one active participant
Definition at line 1462 of file app_confbridge.c.
References confbridge_conference::active_list, AST_LIST_FIRST, ast_test_flag, conf_moh_stop(), conf_update_user_mute(), confbridge_user::u_profile, and USER_OPT_MUSICONHOLD.
Referenced by join_active(), join_marked(), and join_unmarked().
 {
    /* If we are the second participant we may need to stop music on hold on the first */
    struct confbridge_user *first_user = AST_LIST_FIRST(&conference->active_list);
    if (ast_test_flag(&first_user->u_profile, USER_OPT_MUSICONHOLD)) {
       conf_moh_stop(first_user);
    }
    conf_update_user_mute(first_user);
 }
conf_load_config()
int conf_load_config (void)
load confbridge.conf file
Definition at line 2384 of file conf_config_parser.c.
References __stringify, ACO_EXACT, aco_info_init(), aco_option_register, aco_option_register_custom, ACO_PREFIX, aco_process_config(), ACO_PROCESS_ERROR, ACO_REGEX, announce_user_count_all_handler(), ARRAY_LEN, ast_cli_register_multiple, BRIDGE_OPT_BINAURAL_ACTIVE, BRIDGE_OPT_ENABLE_EVENTS, BRIDGE_OPT_RECORD_CONFERENCE, BRIDGE_OPT_RECORD_FILE_APPEND, BRIDGE_OPT_RECORD_FILE_TIMESTAMP, bridge_template_handler(), CHARFLDSET, conf_destroy_config(), DEFAULT_SILENCE_THRESHOLD, DEFAULT_TALKING_THRESHOLD, error(), FLDSET, language, menu_option_handler(), menu_template_handler(), mix_interval_handler(), NULL, OPT_BOOLFLAG_T, OPT_CHAR_ARRAY_T, OPT_NOOP_T, OPT_UINT_T, PARSE_DEFAULT, regcontext, remb_behavior_handler(), sound_option_handler(), timeout, USER_OPT_ADMIN, USER_OPT_ANNOUNCE_JOIN_LEAVE, USER_OPT_ANNOUNCE_JOIN_LEAVE_REVIEW, USER_OPT_ANNOUNCEUSERCOUNT, USER_OPT_ANSWER_CHANNEL, USER_OPT_DENOISE, USER_OPT_DROP_SILENCE, USER_OPT_DTMF_PASS, USER_OPT_ECHO_EVENTS, USER_OPT_ENDMARKED, USER_OPT_JITTERBUFFER, USER_OPT_MARKEDUSER, USER_OPT_MUSICONHOLD, USER_OPT_NOONLYPERSON, USER_OPT_QUIET, USER_OPT_SEND_EVENTS, USER_OPT_STARTMUTED, USER_OPT_TALKER_DETECT, USER_OPT_TEXT_MESSAGING, USER_OPT_WAITMARKED, user_template_handler(), and video_mode_handler().
Referenced by load_module().
 {
    if (aco_info_init(&cfg_info)) {
       return -1;
    }
    /* User options */
    aco_option_register(&cfg_info, "type", ACO_EXACT, user_types, NULL, OPT_NOOP_T, 0, 0);
    aco_option_register(&cfg_info, "admin", ACO_EXACT, user_types, "no", OPT_BOOLFLAG_T, 1, FLDSET(struct user_profile, flags), USER_OPT_ADMIN);
    aco_option_register(&cfg_info, "send_events", ACO_EXACT, user_types, "no", OPT_BOOLFLAG_T, 1, FLDSET(struct user_profile, flags), USER_OPT_SEND_EVENTS);
    aco_option_register(&cfg_info, "echo_events", ACO_EXACT, user_types, "no", OPT_BOOLFLAG_T, 1, FLDSET(struct user_profile, flags), USER_OPT_ECHO_EVENTS);
    aco_option_register(&cfg_info, "marked", ACO_EXACT, user_types, "no", OPT_BOOLFLAG_T, 1, FLDSET(struct user_profile, flags), USER_OPT_MARKEDUSER);
    aco_option_register(&cfg_info, "startmuted", ACO_EXACT, user_types, "no", OPT_BOOLFLAG_T, 1, FLDSET(struct user_profile, flags), USER_OPT_STARTMUTED);
    aco_option_register(&cfg_info, "music_on_hold_when_empty", ACO_EXACT, user_types, "no", OPT_BOOLFLAG_T, 1, FLDSET(struct user_profile, flags), USER_OPT_MUSICONHOLD);
    aco_option_register(&cfg_info, "quiet", ACO_EXACT, user_types, "no", OPT_BOOLFLAG_T, 1, FLDSET(struct user_profile, flags), USER_OPT_QUIET);
    aco_option_register_custom(&cfg_info, "announce_user_count_all", ACO_EXACT, user_types, "no", announce_user_count_all_handler, 0);
    aco_option_register(&cfg_info, "announce_user_count", ACO_EXACT, user_types, "no", OPT_BOOLFLAG_T, 1, FLDSET(struct user_profile, flags), USER_OPT_ANNOUNCEUSERCOUNT);
    /* Negative logic. Defaults to "yes" and evaluates with ast_false(). If !ast_false(), USER_OPT_NOONLYPERSON is cleared */
    aco_option_register(&cfg_info, "announce_only_user", ACO_EXACT, user_types, "yes", OPT_BOOLFLAG_T, 0, FLDSET(struct user_profile, flags), USER_OPT_NOONLYPERSON);
    aco_option_register(&cfg_info, "wait_marked", ACO_EXACT, user_types, "no", OPT_BOOLFLAG_T, 1, FLDSET(struct user_profile, flags), USER_OPT_WAITMARKED);
    aco_option_register(&cfg_info, "end_marked", ACO_EXACT, user_types, "no", OPT_BOOLFLAG_T, 1, FLDSET(struct user_profile, flags), USER_OPT_ENDMARKED);
    aco_option_register(&cfg_info, "talk_detection_events", ACO_EXACT, user_types, "no", OPT_BOOLFLAG_T, 1, FLDSET(struct user_profile, flags), USER_OPT_TALKER_DETECT);
    aco_option_register(&cfg_info, "dtmf_passthrough", ACO_EXACT, user_types, "no", OPT_BOOLFLAG_T, 1, FLDSET(struct user_profile, flags), USER_OPT_DTMF_PASS);
    aco_option_register(&cfg_info, "announce_join_leave", ACO_EXACT, user_types, "no", OPT_BOOLFLAG_T, 1, FLDSET(struct user_profile, flags), USER_OPT_ANNOUNCE_JOIN_LEAVE);
    aco_option_register(&cfg_info, "announce_join_leave_review", ACO_EXACT, user_types, "no", OPT_BOOLFLAG_T, 1, FLDSET(struct user_profile, flags), USER_OPT_ANNOUNCE_JOIN_LEAVE_REVIEW);
    aco_option_register(&cfg_info, "pin", ACO_EXACT, user_types, NULL, OPT_CHAR_ARRAY_T, 0, CHARFLDSET(struct user_profile, pin));
    aco_option_register(&cfg_info, "music_on_hold_class", ACO_EXACT, user_types, NULL, OPT_CHAR_ARRAY_T, 0, CHARFLDSET(struct user_profile, moh_class));
    aco_option_register(&cfg_info, "announcement", ACO_EXACT, user_types, NULL, OPT_CHAR_ARRAY_T, 0, CHARFLDSET(struct user_profile, announcement));
    aco_option_register(&cfg_info, "denoise", ACO_EXACT, user_types, "no", OPT_BOOLFLAG_T, 1, FLDSET(struct user_profile, flags), USER_OPT_DENOISE);
    aco_option_register(&cfg_info, "dsp_drop_silence", ACO_EXACT, user_types, "no", OPT_BOOLFLAG_T, 1, FLDSET(struct user_profile, flags), USER_OPT_DROP_SILENCE);
    aco_option_register(&cfg_info, "dsp_silence_threshold", ACO_EXACT, user_types, __stringify(DEFAULT_SILENCE_THRESHOLD), OPT_UINT_T, 0, FLDSET(struct user_profile, silence_threshold));
    aco_option_register(&cfg_info, "dsp_talking_threshold", ACO_EXACT, user_types, __stringify(DEFAULT_TALKING_THRESHOLD), OPT_UINT_T, 0, FLDSET(struct user_profile, talking_threshold));
    aco_option_register(&cfg_info, "jitterbuffer", ACO_EXACT, user_types, "no", OPT_BOOLFLAG_T, 1, FLDSET(struct user_profile, flags), USER_OPT_JITTERBUFFER);
    aco_option_register(&cfg_info, "timeout", ACO_EXACT, user_types, "0", OPT_UINT_T, 0, FLDSET(struct user_profile, timeout));
    aco_option_register(&cfg_info, "text_messaging", ACO_EXACT, user_types, "yes", OPT_BOOLFLAG_T, 1, FLDSET(struct user_profile, flags), USER_OPT_TEXT_MESSAGING);
    aco_option_register(&cfg_info, "answer_channel", ACO_EXACT, user_types, "yes", OPT_BOOLFLAG_T, 1, FLDSET(struct user_profile, flags), USER_OPT_ANSWER_CHANNEL);
    /* This option should only be used with the CONFBRIDGE dialplan function */
    aco_option_register_custom(&cfg_info, "template", ACO_EXACT, user_types, NULL, user_template_handler, 0);
 /* XXX ASTERISK-21271 need a user supplied bridge merge_priority to merge ConfBridges (default = 1, range 1-INT_MAX) */
    /* Bridge options */
    aco_option_register(&cfg_info, "type", ACO_EXACT, bridge_types, NULL, OPT_NOOP_T, 0, 0);
    aco_option_register(&cfg_info, "jitterbuffer", ACO_EXACT, bridge_types, "no", OPT_BOOLFLAG_T, 1, FLDSET(struct bridge_profile, flags), USER_OPT_JITTERBUFFER);
    /* "auto" will fail to parse as a uint, but we use PARSE_DEFAULT to set the value to 0 in that case, which is the value that auto resolves to */
    aco_option_register(&cfg_info, "internal_sample_rate", ACO_EXACT, bridge_types, "0", OPT_UINT_T, PARSE_DEFAULT, FLDSET(struct bridge_profile, internal_sample_rate), 0);
    aco_option_register(&cfg_info, "binaural_active", ACO_EXACT, bridge_types, "no", OPT_BOOLFLAG_T, 1, FLDSET(struct bridge_profile, flags), BRIDGE_OPT_BINAURAL_ACTIVE);
    aco_option_register(&cfg_info, "maximum_sample_rate", ACO_EXACT, bridge_types, "0", OPT_UINT_T, PARSE_DEFAULT, FLDSET(struct bridge_profile, maximum_sample_rate), 0);
    aco_option_register_custom(&cfg_info, "mixing_interval", ACO_EXACT, bridge_types, "20", mix_interval_handler, 0);
    aco_option_register(&cfg_info, "record_conference", ACO_EXACT, bridge_types, "no", OPT_BOOLFLAG_T, 1, FLDSET(struct bridge_profile, flags), BRIDGE_OPT_RECORD_CONFERENCE);
    aco_option_register_custom(&cfg_info, "video_mode", ACO_EXACT, bridge_types, NULL, video_mode_handler, 0);
    aco_option_register(&cfg_info, "record_file_append", ACO_EXACT, bridge_types, "yes", OPT_BOOLFLAG_T, 1, FLDSET(struct bridge_profile, flags), BRIDGE_OPT_RECORD_FILE_APPEND);
    aco_option_register(&cfg_info, "record_file_timestamp", ACO_EXACT, bridge_types, "yes", OPT_BOOLFLAG_T, 1, FLDSET(struct bridge_profile, flags), BRIDGE_OPT_RECORD_FILE_TIMESTAMP);
    aco_option_register(&cfg_info, "max_members", ACO_EXACT, bridge_types, "0", OPT_UINT_T, 0, FLDSET(struct bridge_profile, max_members));
    aco_option_register(&cfg_info, "record_file", ACO_EXACT, bridge_types, NULL, OPT_CHAR_ARRAY_T, 0, CHARFLDSET(struct bridge_profile, rec_file));
    aco_option_register(&cfg_info, "record_options", ACO_EXACT, bridge_types, NULL, OPT_CHAR_ARRAY_T, 0, CHARFLDSET(struct bridge_profile, rec_options));
    aco_option_register(&cfg_info, "record_command", ACO_EXACT, bridge_types, NULL, OPT_CHAR_ARRAY_T, 0, CHARFLDSET(struct bridge_profile, rec_command));
    aco_option_register(&cfg_info, "regcontext", ACO_EXACT, bridge_types, NULL, OPT_CHAR_ARRAY_T, 0, CHARFLDSET(struct bridge_profile, regcontext));
    aco_option_register(&cfg_info, "language", ACO_EXACT, bridge_types, "en", OPT_CHAR_ARRAY_T, 0, CHARFLDSET(struct bridge_profile, language));
    aco_option_register_custom(&cfg_info, "sound_", ACO_PREFIX, bridge_types, NULL, sound_option_handler, 0);
    aco_option_register(&cfg_info, "video_update_discard", ACO_EXACT, bridge_types, "2000", OPT_UINT_T, 0, FLDSET(struct bridge_profile, video_update_discard));
    aco_option_register(&cfg_info, "remb_send_interval", ACO_EXACT, bridge_types, "0", OPT_UINT_T, 0, FLDSET(struct bridge_profile, remb_send_interval));
    aco_option_register_custom(&cfg_info, "remb_behavior", ACO_EXACT, bridge_types, "average", remb_behavior_handler, 0);
    aco_option_register(&cfg_info, "remb_estimated_bitrate", ACO_EXACT, bridge_types, "0", OPT_UINT_T, 0, FLDSET(struct bridge_profile, remb_estimated_bitrate));
    aco_option_register(&cfg_info, "enable_events", ACO_EXACT, bridge_types, "no", OPT_BOOLFLAG_T, 1, FLDSET(struct bridge_profile, flags), BRIDGE_OPT_ENABLE_EVENTS);
    /* This option should only be used with the CONFBRIDGE dialplan function */
    aco_option_register_custom(&cfg_info, "template", ACO_EXACT, bridge_types, NULL, bridge_template_handler, 0);
    /* Menu options */
    aco_option_register(&cfg_info, "type", ACO_EXACT, menu_types, NULL, OPT_NOOP_T, 0, 0);
    /* This option should only be used with the CONFBRIDGE dialplan function */
    aco_option_register_custom(&cfg_info, "template", ACO_EXACT, menu_types, NULL, menu_template_handler, 0);
    aco_option_register_custom(&cfg_info, "^[0-9A-D*#]+$", ACO_REGEX, menu_types, NULL, menu_option_handler, 0);
    if (aco_process_config(&cfg_info, 0) == ACO_PROCESS_ERROR) {
       goto error;
    }
    if (ast_cli_register_multiple(cli_confbridge_parser, ARRAY_LEN(cli_confbridge_parser))) {
       goto error;
    }
    return 0;
 error:
    conf_destroy_config();
    return -1;
 }
conf_menu_entry_destroy()
void conf_menu_entry_destroy (struct conf_menu_entry * menu_entry)
Destroys and frees all the actions stored in a menu_entry structure.
Definition at line 2602 of file conf_config_parser.c.
References conf_menu_entry::actions, ast_free, AST_LIST_REMOVE_HEAD, and NULL.
Referenced by action_playback_and_continue(), conf_menu_profile_copy(), and menu_destructor().
 {
    struct conf_menu_action *menu_action = NULL;
    while ((menu_action = AST_LIST_REMOVE_HEAD(&menu_entry->actions, action))) {
       ast_free(menu_action);
    }
 }
conf_moh_start()
void conf_moh_start (struct confbridge_user * user)
Start MOH for the conference user.
Parameters
user Conference user to start MOH on.
Returns
Nothing
Definition at line 1360 of file app_confbridge.c.
References ast_bridge_lock, ast_bridge_suspend(), ast_bridge_unlock, ast_bridge_unsuspend(), ast_moh_start(), confbridge_conference::bridge, confbridge_user::chan, confbridge_user::conference, user_profile::moh_class, NULL, confbridge_user::playing_moh, confbridge_user::suspended_moh, and confbridge_user::u_profile.
Referenced by conf_mute_moh_inactive_waitmarked(), conf_mute_only_active(), and leave_marked().
 {
    user->playing_moh = 1;
    if (!user->suspended_moh) {
       int in_bridge;
       /*
        * Locking the ast_bridge here is the only way to hold off the
        * call to ast_bridge_join() in confbridge_exec() from
        * interfering with the bridge and MOH operations here.
        */
       ast_bridge_lock(user->conference->bridge);
       /*
        * Temporarily suspend the user from the bridge so we have
        * control to start MOH if needed.
        */
       in_bridge = !ast_bridge_suspend(user->conference->bridge, user->chan);
       ast_moh_start(user->chan, user->u_profile.moh_class, NULL);
       if (in_bridge) {
          ast_bridge_unsuspend(user->conference->bridge, user->chan);
       }
       ast_bridge_unlock(user->conference->bridge);
    }
 }
conf_moh_stop()
void conf_moh_stop (struct confbridge_user * user)
Stop MOH for the conference user.
Parameters
user Conference user to stop MOH on.
Returns
Nothing
Definition at line 1333 of file app_confbridge.c.
References ast_bridge_lock, ast_bridge_suspend(), ast_bridge_unlock, ast_bridge_unsuspend(), ast_moh_stop(), confbridge_conference::bridge, confbridge_user::chan, confbridge_user::conference, confbridge_user::playing_moh, and confbridge_user::suspended_moh.
Referenced by conf_default_leave_waitmarked(), conf_handle_second_active(), leave_marked(), leave_unmarked(), and transition_to_marked().
 {
    user->playing_moh = 0;
    if (!user->suspended_moh) {
       int in_bridge;
       /*
        * Locking the ast_bridge here is the only way to hold off the
        * call to ast_bridge_join() in confbridge_exec() from
        * interfering with the bridge and MOH operations here.
        */
       ast_bridge_lock(user->conference->bridge);
       /*
        * Temporarily suspend the user from the bridge so we have
        * control to stop MOH if needed.
        */
       in_bridge = !ast_bridge_suspend(user->conference->bridge, user->chan);
       ast_moh_stop(user->chan);
       if (in_bridge) {
          ast_bridge_unsuspend(user->conference->bridge, user->chan);
       }
       ast_bridge_unlock(user->conference->bridge);
    }
 }
conf_mute_only_active()
void conf_mute_only_active (struct confbridge_conference * conference)
Attempt to mute/play MOH to the only user in the conference if they require it.
Parameters
conference A conference bridge containing a single user
Definition at line 4335 of file app_confbridge.c.
References confbridge_conference::active_list, AST_LIST_FIRST, ast_test_flag, conf_moh_start(), conf_update_user_mute(), confbridge_user::u_profile, and USER_OPT_MUSICONHOLD.
Referenced by transition_to_single(), and transition_to_single_marked().
 {
    struct confbridge_user *only_user = AST_LIST_FIRST(&conference->active_list);
    /* Turn on MOH if the single participant is set up for it */
    if (ast_test_flag(&only_user->u_profile, USER_OPT_MUSICONHOLD)) {
       conf_moh_start(only_user);
    }
    conf_update_user_mute(only_user);
 }
conf_record_get_tech()
struct ast_channel_tech* conf_record_get_tech (void)
Get ConfBridge record channel technology struct.
Since
12.0.0
Returns
ConfBridge record channel technology.
Definition at line 102 of file conf_chan_record.c.
References record_tech.
Referenced by load_module(), rec_request(), and unload_module().
 {
    return &record_tech;
 }
conf_reload_config()
int conf_reload_config (void)
reload confbridge.conf file
Definition at line 2472 of file conf_config_parser.c.
References aco_process_config(), and ACO_PROCESS_ERROR.
Referenced by reload().
 {
    if (aco_process_config(&cfg_info, 1) == ACO_PROCESS_ERROR) {
       /* On a reload, just keep the config we already have in place. */
       return -1;
    }
    return 0;
 }
conf_remove_user_active()
void conf_remove_user_active (struct confbridge_conference * conference, struct confbridge_user * user)
Remove a conference bridge user from the unmarked active conference users in the conference.
Parameters
conference The conference bridge to remove the user from
user The conference bridge user to remove from the conference
Definition at line 4322 of file app_confbridge.c.
References confbridge_conference::active_list, confbridge_conference::activeusers, and AST_LIST_REMOVE.
Referenced by leave_active(), and leave_unmarked().
 {
    AST_LIST_REMOVE(&conference->active_list, user, list);
    conference->activeusers--;
 }
conf_remove_user_marked()
void conf_remove_user_marked (struct confbridge_conference * conference, struct confbridge_user * user)
Remove a conference bridge user from the marked active conference users in the conference.
Parameters
conference The conference bridge to remove the user from
user The conference bridge user to remove from the conference
Definition at line 4328 of file app_confbridge.c.
References confbridge_conference::active_list, confbridge_conference::activeusers, AST_LIST_REMOVE, and confbridge_conference::markedusers.
Referenced by leave_marked().
 {
    AST_LIST_REMOVE(&conference->active_list, user, list);
    conference->activeusers--;
    conference->markedusers--;
 }
conf_remove_user_waiting()
void conf_remove_user_waiting (struct confbridge_conference * conference, struct confbridge_user * user)
Remove a conference bridge user from the waiting conference users in the conference.
Parameters
conference The conference bridge to remove the user from
user The conference bridge user to remove from the conference
Definition at line 4346 of file app_confbridge.c.
References AST_LIST_REMOVE, confbridge_user::list, confbridge_conference::waiting_list, and confbridge_conference::waitingusers.
Referenced by conf_default_leave_waitmarked().
 {
    AST_LIST_REMOVE(&conference->waiting_list, user, list);
    conference->waitingusers--;
 }
conf_send_event_to_participants()
void conf_send_event_to_participants (struct confbridge_conference * conference, struct ast_channel * chan, struct stasis_message * msg)
Send events to bridge participants.
Since
15.7
16.1
Parameters
conference The conference bridge
chan The channel triggering the action
msg The stasis message describing the event
Definition at line 414 of file confbridge_manager.c.
References confbridge_conference::active_list, ao2_lock, ao2_ref, ao2_unlock, ast_channel_name(), ast_channel_snapshot_get_latest(), ast_channel_uniqueid(), ast_debug, ast_json_array_append(), ast_json_array_create(), ast_json_object_get(), ast_json_string_set(), ast_json_unref(), AST_LIST_TRAVERSE, ast_log, ast_test_flag, ast_bridge_blob::blob, ast_bridge_blob::bridge, bridge_to_json(), confbridge_user::chan, ast_bridge_blob::channel, channel_to_json(), conf_find_user_profile(), confbridge_event_type_to_string(), confbridge_join_type(), confbridge_welcome_type(), confbridge_user::list, LOG_ERROR, user_profile::name, confbridge_conference::name, NULL, pack_bridge_and_channels(), pack_snapshots(), send_message(), stasis_message_data(), stasis_message_type(), confbridge_user::u_profile, user, USER_OPT_ECHO_EVENTS, and USER_OPT_SEND_EVENTS.
Referenced by send_conf_stasis().
 {
    struct ast_bridge_blob *obj = stasis_message_data(msg);
    struct ast_json *extras = obj->blob;
    struct user_profile u_profile = {{0}};
    int source_send_events = 0;
    int source_echo_events = 0;
    struct ast_json* json_channels = NULL;
    struct confbridge_user *user;
    const char *msg_name = confbridge_event_type_to_string(stasis_message_type(msg));
    ast_debug(3, "Distributing %s event to participants\n", msg_name);
    /* This could be a channel level event or a bridge level event */
    if (chan) {
       if (!conf_find_user_profile(chan, NULL, &u_profile)) {
          ast_log(LOG_ERROR, "Unable to retrieve user profile for channel '%s'\n",
             ast_channel_name(chan));
          return;
       }
       source_send_events = ast_test_flag(&u_profile, USER_OPT_SEND_EVENTS);
       source_echo_events = ast_test_flag(&u_profile, USER_OPT_ECHO_EVENTS);
       ast_debug(3, "send_events: %d  echo_events: %d for profile %s\n",
          source_send_events, source_echo_events, u_profile.name);
    }
    /* Now send a message to the participants with the json string. */
    ao2_lock(conference);
    AST_LIST_TRAVERSE(&conference->active_list, user, list) {
       struct ast_json *json_object;
       /*
        * If the msg type is join, we need to capture all targets channel info so we can
        * send a welcome message to the source channel with all current participants.
        */
       if (source_send_events && stasis_message_type(msg) == confbridge_join_type()) {
          struct ast_channel_snapshot *target_snapshot;
          struct ast_json *target_json_channel;
          target_snapshot = ast_channel_snapshot_get_latest(ast_channel_uniqueid(user->chan));
          if (!target_snapshot) {
             ast_log(LOG_ERROR, "Unable to get a channel snapshot for '%s'\n",
                ast_channel_name(user->chan));
             continue;
          }
          target_json_channel = channel_to_json(target_snapshot, extras, NULL);
          ao2_ref(target_snapshot, -1);
          if (!json_channels) {
             json_channels = ast_json_array_create();
             if (!json_channels) {
                ast_log(LOG_ERROR, "Unable to allocate json array\n");
                ast_json_unref(target_json_channel);
                return;
             }
          }
          ast_json_array_append(json_channels, target_json_channel);
       }
       /* Don't send a message to the user that triggered the event. */
       if (!source_echo_events && user->chan == chan) {
          ast_debug(3, "Skipping queueing %s message to '%s'. Same channel.\n", msg_name,
             ast_channel_name(user->chan));
          continue;
       }
       /* Don't send a message to users in profiles not sending events. */
       if (!ast_test_flag(&user->u_profile, USER_OPT_SEND_EVENTS)) {
          ast_debug(3, "Skipping queueing %s message to '%s'. Not receiving events.\n", msg_name,
             ast_channel_name(user->chan));
          continue;
       }
       json_object = pack_snapshots(obj->bridge, obj->channel, extras, NULL, msg);
       if (!json_object) {
          ast_log(LOG_ERROR, "Unable to convert %s message to json\n", msg_name);
          continue;
       }
       send_message(msg_name, conference->name, json_object, user->chan);
       ast_json_unref(json_object);
    }
    ao2_unlock(conference);
    /*
     * If this is a join event, send the welcome message to just the joining user
     * if it's not audio-only or otherwise restricted.
     */
    if (source_send_events && json_channels
       && stasis_message_type(msg) == confbridge_join_type()) {
       struct ast_json *json_object;
       struct ast_json *json_bridge;
       const char *welcome_msg_name = confbridge_event_type_to_string(confbridge_welcome_type());
       json_bridge = bridge_to_json(obj->bridge);
       json_object = pack_bridge_and_channels(json_bridge, json_channels, msg);
       if (!json_object) {
          ast_log(LOG_ERROR, "Unable to convert ConfbridgeWelcome message to json\n");
          return;
       }
       ast_json_string_set(ast_json_object_get(json_object, "type"), welcome_msg_name);
       send_message(welcome_msg_name, conference->name, json_object, chan);
       ast_json_unref(json_object);
    }
 }
conf_set_menu_to_user()
int conf_set_menu_to_user (struct ast_channel * chan, struct confbridge_user * user, const char * menu_profile_name)
find a menu profile given a menu profile's name and apply the menu in DTMF hooks.
Parameters
chan channel the menu profile is requested for
user user profile the menu is being applied to
menu_profile_name name of the profile requested (optional)
If menu_profile_name is not provided, this function will check for the presence of a menu profile set by the CONFBRIDGE function on a channel datastore. If that doesn't exist, the default_menu profile is used.
Return values
0 on success
-1 on failure
Definition at line 2656 of file conf_config_parser.c.
References ao2_bump, ao2_cleanup, ao2_find, ao2_global_obj_ref, apply_menu_to_user(), ast_channel_datastore_find(), ast_channel_lock, ast_channel_unlock, ast_strlen_zero, cfg_handle, ast_datastore::data, DEFAULT_MENU_PROFILE, func_confbridge_data::m_usable, func_confbridge_data::menu, NULL, OBJ_KEY, and RAII_VAR.
Referenced by confbridge_exec().
 {
    RAII_VAR(struct confbridge_cfg *, cfg, ao2_global_obj_ref(cfg_handle), ao2_cleanup);
    RAII_VAR(struct conf_menu *, menu, NULL, ao2_cleanup);
    if (chan && ast_strlen_zero(menu_profile_name)) {
       struct ast_datastore *datastore;
       struct func_confbridge_data *b_data;
       ast_channel_lock(chan);
       datastore = ast_channel_datastore_find(chan, &confbridge_datastore, NULL);
       ast_channel_unlock(chan);
       if (datastore) {
          /* If a menu exists in the CONFBRIDGE function datastore, use it. */
          b_data = datastore->data;
          if (b_data->m_usable) {
             menu = ao2_bump(b_data->menu);
             return apply_menu_to_user(user, menu);
          }
       }
    }
    /* Otherwise, we need to get whatever menu profile is specified to use (or default). */
    if (!cfg) {
       return -1;
    }
    if (ast_strlen_zero(menu_profile_name)) {
       menu_profile_name = DEFAULT_MENU_PROFILE;
    }
    if (!(menu = ao2_find(cfg->menus, menu_profile_name, OBJ_KEY))) {
       return -1;
    }
    return apply_menu_to_user(user, menu);
 }
conf_update_user_mute()
void conf_update_user_mute (struct confbridge_user * user)
Update the actual mute status of the user and set it on the bridge.
Parameters
user User to update the mute status.
Returns
Nothing
Definition at line 1275 of file app_confbridge.c.
References ast_channel_name(), ast_debug, ast_test_flag, ast_test_suite_event_notify, confbridge_conference::b_profile, confbridge_user::chan, confbridge_user::conference, confbridge_user::features, confbridge_conference::markedusers, ast_bridge_features::mute, confbridge_user::muted, bridge_profile::name, confbridge_user::playing_moh, confbridge_user::u_profile, and USER_OPT_WAITMARKED.
Referenced by action_toggle_mute_participants(), conf_handle_second_active(), conf_mute_moh_inactive_waitmarked(), conf_mute_only_active(), generic_mute_unmute_user(), join_active(), join_marked(), join_unmarked(), leave_marked(), and transition_to_marked().
 {
    int mute_user;
    int mute_system;
    int mute_effective;
    /* User level mute request. */
    mute_user = user->muted;
    /* System level mute request. */
    mute_system = user->playing_moh
       /*
        * Do not allow waitmarked users to talk to anyone unless there
        * is a marked user present.
        */
       || (!user->conference->markedusers
          && ast_test_flag(&user->u_profile, USER_OPT_WAITMARKED));
    mute_effective = mute_user || mute_system;
    ast_debug(1, "User %s is %s: user:%d system:%d.\n",
       ast_channel_name(user->chan), mute_effective ? "muted" : "unmuted",
       mute_user, mute_system);
    user->features.mute = mute_effective;
    ast_test_suite_event_notify("CONF_MUTE_UPDATE",
       "Mode: %s\r\n"
       "Conference: %s\r\n"
       "Channel: %s",
       mute_effective ? "muted" : "unmuted",
       user->conference->b_profile.name,
       ast_channel_name(user->chan));
 }
confbridge_end_type()
struct stasis_message_type* confbridge_end_type (void)
get the confbridge end stasis message type
Since
12.0
Return values
stasis message type for confbridge end messages if it's available
NULL if it isn't
Referenced by confbridge_event_type_to_string(), manager_confbridge_init(), manager_confbridge_shutdown(), and send_conf_end_event().
confbridge_event_type_to_string()
const char* confbridge_event_type_to_string (struct stasis_message_type * event_type)
Get the string representation of a confbridge stasis message type.
Since
15.5
Parameters
event_type The confbridge event type such as 'confbridge_welcome_type()'
Return values
The string representation of the message type
unknown if not found
Definition at line 249 of file confbridge_manager.c.
References confbridge_end_type(), confbridge_join_type(), confbridge_leave_type(), confbridge_mute_type(), confbridge_start_record_type(), confbridge_start_type(), confbridge_stop_record_type(), confbridge_talking_type(), confbridge_unmute_type(), and confbridge_welcome_type().
Referenced by conf_send_event_to_participants(), confbridge_publish_manager_event(), pack_bridge_and_channels(), and send_message().
 {
    if (event_type == confbridge_start_type()) {
       return "ConfbridgeStart";
    } else if (event_type == confbridge_end_type()) {
       return "ConfbridgeEnd";
    } else if (event_type == confbridge_join_type()) {
       return "ConfbridgeJoin";
    } else if (event_type == confbridge_leave_type()) {
       return "ConfbridgeLeave";
    } else if (event_type == confbridge_start_record_type()) {
       return "ConfbridgeRecord";
    } else if (event_type == confbridge_stop_record_type()) {
       return "ConfbridgeStopRecord";
    } else if (event_type == confbridge_mute_type()) {
       return "ConfbridgeMute";
    } else if (event_type == confbridge_unmute_type()) {
       return "ConfbridgeUnmute";
    } else if (event_type == confbridge_talking_type()) {
       return "ConfbridgeTalking";
    } else if (event_type == confbridge_welcome_type()) {
       return "ConfbridgeWelcome";
    } else {
       return "unknown";
    }
 }
confbridge_handle_atxfer()
void confbridge_handle_atxfer (struct ast_attended_transfer_message * msg)
Create join/leave events for attended transfers.
Since
13.28
16.5
Parameters
msg The attended transfer stasis message
Definition at line 1562 of file app_confbridge.c.
References confbridge_conference::active_list, ao2_find, ao2_lock, ast_channel_snapshot_dialplan::appl, ast_channel_name(), ast_debug, ast_json_pack(), ast_json_unref(), AST_LIST_TRAVERSE, ast_log, ast_strdupa, ast_strlen_zero, ast_test_flag, ast_channel_snapshot::base, confbridge_user::chan, ast_bridge_channel_snapshot_pair::channel_snapshot, confbridge_join_type(), confbridge_leave_type(), confbridge_unlock_and_unref(), hangup_data::conference, ast_channel_snapshot_dialplan::data, ast_channel_snapshot::dialplan, LOG_ERROR, confbridge_user::muted, ast_channel_snapshot_base::name, NULL, OBJ_SEARCH_KEY, RAII_VAR, send_conf_stasis_snapshots(), ast_attended_transfer_message::target, ast_attended_transfer_message::to_transfer_target, ast_attended_transfer_message::to_transferee, ast_attended_transfer_message::transferee, confbridge_user::u_profile, USER_OPT_ADMIN, confbridge_conference::waiting_list, and confbridge_conference::waitingusers.
Referenced by confbridge_atxfer_cb().
 {
    struct ast_channel_snapshot *old_snapshot;
    struct ast_channel_snapshot *new_snapshot;
    char *confbr_name = NULL;
    char *comma;
    RAII_VAR(struct confbridge_conference *, conference, NULL, confbridge_unlock_and_unref);
    struct confbridge_user *user = NULL;
    int found_user = 0;
    struct ast_json *json_object;
    if (msg->to_transferee.channel_snapshot
       && strcmp(msg->to_transferee.channel_snapshot->dialplan->appl, "ConfBridge") == 0
       && msg->target) {
       /* We're transferring a bridge to an extension */
       old_snapshot = msg->to_transferee.channel_snapshot;
       new_snapshot = msg->target;
    } else if (msg->to_transfer_target.channel_snapshot
       && strcmp(msg->to_transfer_target.channel_snapshot->dialplan->appl, "ConfBridge") == 0
       && msg->transferee) {
       /* We're transferring a call to a bridge */
       old_snapshot = msg->to_transfer_target.channel_snapshot;
       new_snapshot = msg->transferee;
    } else {
       ast_log(LOG_ERROR, "Could not determine proper channels\n");
       return;
    }
    /*
     * old_snapshot->data should have the original parameters passed to
     * the ConfBridge app:
     * conference[,bridge_profile[,user_profile[,menu]]]
     * We'll use "conference" to look up the bridge.
     *
     * We _could_ use old_snapshot->bridgeid to get the bridge but
     * that would involve locking the conference_bridges container
     * and iterating over it looking for a matching bridge.
     */
    if (ast_strlen_zero(old_snapshot->dialplan->data)) {
       ast_log(LOG_ERROR, "Channel '%s' didn't have app data set\n", old_snapshot->base->name);
       return;
    }
    confbr_name = ast_strdupa(old_snapshot->dialplan->data);
    comma = strchr(confbr_name, ',');
    if (comma) {
       *comma = '\0';
    }
    ast_debug(1, "Confbr: %s  Leaving: %s  Joining: %s\n", confbr_name, old_snapshot->base->name, new_snapshot->base->name);
    conference = ao2_find(conference_bridges, confbr_name, OBJ_SEARCH_KEY);
    if (!conference) {
       ast_log(LOG_ERROR, "Conference bridge '%s' not found\n", confbr_name);
       return;
    }
    ao2_lock(conference);
    /*
     * We need to grab the user profile for the departing user in order to
     * properly format the join/leave messages.
     */
    AST_LIST_TRAVERSE(&conference->active_list, user, list) {
       if (strcasecmp(ast_channel_name(user->chan), old_snapshot->base->name) == 0) {
          found_user = 1;
          break;
       }
    }
    /*
     * If we didn't find the user in the active list, try the waiting list.
     */
    if (!found_user && conference->waitingusers) {
       AST_LIST_TRAVERSE(&conference->waiting_list, user, list) {
          if (strcasecmp(ast_channel_name(user->chan), old_snapshot->base->name) == 0) {
             found_user = 1;
             break;
          }
       }
    }
    if (!found_user) {
       ast_log(LOG_ERROR, "Unable to find user profile for channel '%s' in bridge '%s'\n",
          old_snapshot->base->name, confbr_name);
       return;
    }
    /*
     * We're going to use the existing user profile to create the messages.
     */
    json_object = ast_json_pack("{s: b}",
       "admin", ast_test_flag(&user->u_profile, USER_OPT_ADMIN)
    );
    if (!json_object) {
       return;
    }
    send_conf_stasis_snapshots(conference, old_snapshot, confbridge_leave_type(), json_object);
    ast_json_unref(json_object);
    json_object = ast_json_pack("{s: b, s: b}",
       "admin", ast_test_flag(&user->u_profile, USER_OPT_ADMIN),
       "muted", user->muted);
    if (!json_object) {
       return;
    }
    send_conf_stasis_snapshots(conference, new_snapshot, confbridge_join_type(), json_object);
    ast_json_unref(json_object);
 }
confbridge_join_type()
struct stasis_message_type* confbridge_join_type (void)
get the confbridge join stasis message type
Since
12.0
Return values
stasis message type for confbridge join messages if it's available
NULL if it isn't
Referenced by conf_send_event_to_participants(), confbridge_event_type_to_string(), confbridge_handle_atxfer(), manager_confbridge_init(), manager_confbridge_shutdown(), and send_join_event().
confbridge_leave_type()
struct stasis_message_type* confbridge_leave_type (void)
get the confbridge leave stasis message type
Since
12.0
Return values
stasis message type for confbridge leave messages if it's available
NULL if it isn't
Referenced by confbridge_event_type_to_string(), confbridge_handle_atxfer(), manager_confbridge_init(), manager_confbridge_shutdown(), send_leave_event(), and send_message().
confbridge_mute_type()
struct stasis_message_type* confbridge_mute_type (void)
get the confbridge mute stasis message type
Since
12.0
Return values
stasis message type for confbridge mute messages if it's available
NULL if it isn't
Referenced by confbridge_event_type_to_string(), manager_confbridge_init(), manager_confbridge_shutdown(), and send_mute_event().
confbridge_start_record_type()
struct stasis_message_type* confbridge_start_record_type (void)
get the confbridge start_record stasis message type
Since
12.0
Return values
stasis message type for confbridge start_record messages if it's available
NULL if it isn't
Referenced by confbridge_event_type_to_string(), manager_confbridge_init(), manager_confbridge_shutdown(), and send_start_record_event().
confbridge_start_type()
struct stasis_message_type* confbridge_start_type (void)
get the confbridge start stasis message type
Since
12.0
Return values
stasis message type for confbridge start messages if it's available
NULL if it isn't
Referenced by confbridge_event_type_to_string(), manager_confbridge_init(), manager_confbridge_shutdown(), and send_conf_start_event().
confbridge_stop_record_type()
struct stasis_message_type* confbridge_stop_record_type (void)
get the confbridge stop_record stasis message type
Since
12.0
Return values
stasis message type for confbridge stop_record messages if it's available
NULL if it isn't
Referenced by confbridge_event_type_to_string(), manager_confbridge_init(), manager_confbridge_shutdown(), and send_stop_record_event().
confbridge_talking_type()
struct stasis_message_type* confbridge_talking_type (void)
get the confbridge talking stasis message type
Since
12.0
Return values
stasis message type for confbridge talking messages if it's available
NULL if it isn't
Referenced by conf_handle_talker_cb(), confbridge_event_type_to_string(), manager_confbridge_init(), and manager_confbridge_shutdown().
confbridge_unmute_type()
struct stasis_message_type* confbridge_unmute_type (void)
get the confbridge unmute stasis message type
Since
12.0
Return values
stasis message type for confbridge unmute messages if it's available
NULL if it isn't
Referenced by confbridge_event_type_to_string(), manager_confbridge_init(), manager_confbridge_shutdown(), and send_unmute_event().
confbridge_welcome_type()
struct stasis_message_type* confbridge_welcome_type (void)
get the confbridge welcome stasis message type
Since
15.5
Return values
stasis message type for confbridge welcome messages if it's available
NULL if it isn't
Referenced by conf_send_event_to_participants(), confbridge_event_type_to_string(), manager_confbridge_init(), and manager_confbridge_shutdown().
func_confbridge_helper()
int func_confbridge_helper (struct ast_channel * chan, const char * cmd, char * data, const char * value)
Definition at line 1115 of file conf_config_parser.c.
References aco_process_var(), ao2_cleanup, args, AST_APP_ARG, ast_calloc, ast_channel_datastore_add(), ast_channel_datastore_find(), ast_channel_datastore_remove(), ast_channel_lock, ast_channel_unlock, ast_datastore_alloc, ast_datastore_free(), AST_DECLARE_APP_ARGS, ast_log, AST_STANDARD_APP_ARGS, ast_strdupa, ast_strlen_zero, func_confbridge_data::b_profile, func_confbridge_data::b_usable, bridge_profile_sounds_alloc(), conf_bridge_profile_destroy(), ast_datastore::data, DEFAULT_BRIDGE_PROFILE, DEFAULT_MENU_PROFILE, DEFAULT_USER_PROFILE, ast_variable::file, LOG_WARNING, func_confbridge_data::m_usable, func_confbridge_data::menu, menu_alloc(), ast_variable::name, NULL, parse(), bridge_profile::sounds, type, func_confbridge_data::u_profile, func_confbridge_data::u_usable, user_profile_destructor(), value, and ast_variable::value.
 {
    struct ast_datastore *datastore;
    struct func_confbridge_data *b_data;
    char *parse;
    struct ast_variable tmpvar = { 0, };
    struct ast_variable template = {
       .name = "template",
       .file = "CONFBRIDGE"
    };
    AST_DECLARE_APP_ARGS(args,
       AST_APP_ARG(type);
       AST_APP_ARG(option);
    );
    if (!chan) {
       ast_log(LOG_WARNING, "No channel was provided to %s function.\n", cmd);
       return -1;
    }
    /* parse all the required arguments and make sure they exist. */
    if (ast_strlen_zero(data)) {
       return -1;
    }
    parse = ast_strdupa(data);
    AST_STANDARD_APP_ARGS(args, parse);
    if (ast_strlen_zero(args.type) || ast_strlen_zero(args.option)) {
       return -1;
    }
    ast_channel_lock(chan);
    datastore = ast_channel_datastore_find(chan, &confbridge_datastore, NULL);
    if (!datastore) {
       datastore = ast_datastore_alloc(&confbridge_datastore, NULL);
       if (!datastore) {
          ast_channel_unlock(chan);
          return 0;
       }
       b_data = ast_calloc(1, sizeof(*b_data));
       if (!b_data) {
          ast_channel_unlock(chan);
          ast_datastore_free(datastore);
          return 0;
       }
       datastore->data = b_data;
       b_data->b_profile.sounds = bridge_profile_sounds_alloc();
       if (!b_data->b_profile.sounds) {
          ast_channel_unlock(chan);
          ast_datastore_free(datastore);
          return 0;
       }
       if (!(b_data->menu = menu_alloc("dialplan"))) {
          ast_channel_unlock(chan);
          ast_datastore_free(datastore);
          return 0;
       }
       ast_channel_datastore_add(chan, datastore);
    } else {
       b_data = datastore->data;
    }
    ast_channel_unlock(chan);
    /* SET(CONFBRIDGE(type,option)=value) */
    if (!value) {
       value = "";
    }
    tmpvar.name = args.option;
    tmpvar.value = value;
    tmpvar.file = "CONFBRIDGE";
    if (!strcasecmp(args.type, "bridge")) {
       if (!strcasecmp(args.option, "clear")) {
          b_data->b_usable = 0;
          conf_bridge_profile_destroy(&b_data->b_profile);
          memset(&b_data->b_profile, 0, sizeof(b_data->b_profile)) ;
          if (!(b_data->b_profile.sounds = bridge_profile_sounds_alloc())) {
             /* If this reallocation fails, the datastore has become unusable and must be destroyed. */
             ast_channel_lock(chan);
             ast_channel_datastore_remove(chan, datastore);
             ast_channel_unlock(chan);
             ast_datastore_free(datastore);
          }
          return 0;
       }
       if (b_data && !b_data->b_usable && strcasecmp(args.option, "template")) {
          template.value = DEFAULT_BRIDGE_PROFILE;
          aco_process_var(&bridge_type, "dialplan", &template, &b_data->b_profile);
       }
       if (!aco_process_var(&bridge_type, "dialplan", &tmpvar, &b_data->b_profile)) {
          b_data->b_usable = 1;
          return 0;
       }
    } else if (!strcasecmp(args.type, "user")) {
       if (!strcasecmp(args.option, "clear")) {
          b_data->u_usable = 0;
          user_profile_destructor(&b_data->u_profile);
          memset(&b_data->u_profile, 0, sizeof(b_data->u_profile));
          return 0;
       }
       if (b_data && !b_data->u_usable && strcasecmp(args.option, "template")) {
          template.value = DEFAULT_USER_PROFILE;
          aco_process_var(&user_type, "dialplan", &template, &b_data->u_profile);
       }
       if (!aco_process_var(&user_type, "dialplan", &tmpvar, &b_data->u_profile)) {
          b_data->u_usable = 1;
          return 0;
       }
    } else if (!strcasecmp(args.type, "menu")) {
       if (!strcasecmp(args.option, "clear")) {
          b_data->m_usable = 0;
          ao2_cleanup(b_data->menu);
          if (!(b_data->menu = menu_alloc("dialplan"))) {
             /* If this reallocation fails, the datastore has become unusable and must be destroyed */
             ast_channel_lock(chan);
             ast_channel_datastore_remove(chan, datastore);
             ast_channel_unlock(chan);
             ast_datastore_free(datastore);
          }
          return 0;
       }
       if (b_data && !b_data->m_usable && strcasecmp(args.option, "template")) {
          template.value = DEFAULT_MENU_PROFILE;
          aco_process_var(&menu_type, "dialplan", &template, &b_data->menu);
       }
       if (!aco_process_var(&menu_type, "dialplan", &tmpvar, b_data->menu)) {
          b_data->m_usable = 1;
          return 0;
       }
    }
    ast_log(LOG_WARNING, "%s(%s,%s) cannot be set to '%s'. Invalid type, option, or value.\n",
       cmd, args.type, args.option, value);
    return -1;
 }
manager_confbridge_init()
int manager_confbridge_init (void)
register stasis message routers to handle manager events for confbridge messages
Since
12.0
Return values
0 success
non-zero failure
Definition at line 721 of file confbridge_manager.c.
References ast_attended_transfer_type(), ast_bridge_topic_all(), ast_channel_topic_all(), confbridge_atxfer_cb(), confbridge_end_cb(), confbridge_end_type(), confbridge_join_cb(), confbridge_join_type(), confbridge_leave_cb(), confbridge_leave_type(), confbridge_mute_cb(), confbridge_mute_type(), confbridge_start_cb(), confbridge_start_record_cb(), confbridge_start_record_type(), confbridge_start_type(), confbridge_stop_record_cb(), confbridge_stop_record_type(), confbridge_talking_cb(), confbridge_talking_type(), confbridge_unmute_cb(), confbridge_unmute_type(), confbridge_welcome_type(), manager_confbridge_shutdown(), NULL, stasis_message_router_add(), stasis_message_router_create, and STASIS_MESSAGE_TYPE_INIT.
Referenced by load_module().
 {
    STASIS_MESSAGE_TYPE_INIT(confbridge_start_type);
    STASIS_MESSAGE_TYPE_INIT(confbridge_end_type);
    STASIS_MESSAGE_TYPE_INIT(confbridge_join_type);
    STASIS_MESSAGE_TYPE_INIT(confbridge_leave_type);
    STASIS_MESSAGE_TYPE_INIT(confbridge_start_record_type);
    STASIS_MESSAGE_TYPE_INIT(confbridge_stop_record_type);
    STASIS_MESSAGE_TYPE_INIT(confbridge_mute_type);
    STASIS_MESSAGE_TYPE_INIT(confbridge_unmute_type);
    STASIS_MESSAGE_TYPE_INIT(confbridge_talking_type);
    STASIS_MESSAGE_TYPE_INIT(confbridge_welcome_type);
    bridge_state_router = stasis_message_router_create(
       ast_bridge_topic_all());
    if (!bridge_state_router) {
       return -1;
    }
    if (stasis_message_router_add(bridge_state_router,
          confbridge_start_type(),
          confbridge_start_cb,
          NULL)) {
       manager_confbridge_shutdown();
       return -1;
    }
    if (stasis_message_router_add(bridge_state_router,
          confbridge_end_type(),
          confbridge_end_cb,
          NULL)) {
       manager_confbridge_shutdown();
       return -1;
    }
    if (stasis_message_router_add(bridge_state_router,
          confbridge_join_type(),
          confbridge_join_cb,
          NULL)) {
       manager_confbridge_shutdown();
       return -1;
    }
    if (stasis_message_router_add(bridge_state_router,
          ast_attended_transfer_type(),
          confbridge_atxfer_cb,
          NULL)) {
       manager_confbridge_shutdown();
       return -1;
    }
    if (stasis_message_router_add(bridge_state_router,
          confbridge_leave_type(),
          confbridge_leave_cb,
          NULL)) {
       manager_confbridge_shutdown();
       return -1;
    }
    if (stasis_message_router_add(bridge_state_router,
          confbridge_start_record_type(),
          confbridge_start_record_cb,
          NULL)) {
       manager_confbridge_shutdown();
       return -1;
    }
    if (stasis_message_router_add(bridge_state_router,
          confbridge_stop_record_type(),
          confbridge_stop_record_cb,
          NULL)) {
       manager_confbridge_shutdown();
       return -1;
    }
    if (stasis_message_router_add(bridge_state_router,
          confbridge_mute_type(),
          confbridge_mute_cb,
          NULL)) {
       manager_confbridge_shutdown();
       return -1;
    }
    if (stasis_message_router_add(bridge_state_router,
          confbridge_unmute_type(),
          confbridge_unmute_cb,
          NULL)) {
       manager_confbridge_shutdown();
       return -1;
    }
    if (stasis_message_router_add(bridge_state_router,
          confbridge_talking_type(),
          confbridge_talking_cb,
          NULL)) {
       manager_confbridge_shutdown();
       return -1;
    }
    channel_state_router = stasis_message_router_create(
       ast_channel_topic_all());
    if (!channel_state_router) {
       manager_confbridge_shutdown();
       return -1;
    }
    if (stasis_message_router_add(channel_state_router,
          confbridge_start_type(),
          confbridge_start_cb,
          NULL)) {
       manager_confbridge_shutdown();
       return -1;
    }
    if (stasis_message_router_add(channel_state_router,
          confbridge_end_type(),
          confbridge_end_cb,
          NULL)) {
       manager_confbridge_shutdown();
       return -1;
    }
    if (stasis_message_router_add(channel_state_router,
          confbridge_join_type(),
          confbridge_join_cb,
          NULL)) {
       manager_confbridge_shutdown();
       return -1;
    }
    if (stasis_message_router_add(channel_state_router,
          confbridge_leave_type(),
          confbridge_leave_cb,
          NULL)) {
       manager_confbridge_shutdown();
       return -1;
    }
    if (stasis_message_router_add(channel_state_router,
          confbridge_start_record_type(),
          confbridge_start_record_cb,
          NULL)) {
       manager_confbridge_shutdown();
       return -1;
    }
    if (stasis_message_router_add(channel_state_router,
          confbridge_stop_record_type(),
          confbridge_stop_record_cb,
          NULL)) {
       manager_confbridge_shutdown();
       return -1;
    }
    if (stasis_message_router_add(channel_state_router,
          confbridge_mute_type(),
          confbridge_mute_cb,
          NULL)) {
       manager_confbridge_shutdown();
       return -1;
    }
    if (stasis_message_router_add(channel_state_router,
          confbridge_unmute_type(),
          confbridge_unmute_cb,
          NULL)) {
       manager_confbridge_shutdown();
       return -1;
    }
    if (stasis_message_router_add(channel_state_router,
          confbridge_talking_type(),
          confbridge_talking_cb,
          NULL)) {
       manager_confbridge_shutdown();
       return -1;
    }
    /* FYI: confbridge_welcome_type is never routed */
    return 0;
 }
manager_confbridge_shutdown()
void manager_confbridge_shutdown (void)
unregister stasis message routers to handle manager events for confbridge messages
Since
12.0
Definition at line 698 of file confbridge_manager.c.
References confbridge_end_type(), confbridge_join_type(), confbridge_leave_type(), confbridge_mute_type(), confbridge_start_record_type(), confbridge_start_type(), confbridge_stop_record_type(), confbridge_talking_type(), confbridge_unmute_type(), confbridge_welcome_type(), NULL, stasis_message_router_unsubscribe(), and STASIS_MESSAGE_TYPE_CLEANUP.
Referenced by manager_confbridge_init(), and unload_module().
{
    STASIS_MESSAGE_TYPE_CLEANUP(confbridge_start_type);
    STASIS_MESSAGE_TYPE_CLEANUP(confbridge_end_type);
    STASIS_MESSAGE_TYPE_CLEANUP(confbridge_join_type);
    STASIS_MESSAGE_TYPE_CLEANUP(confbridge_leave_type);
    STASIS_MESSAGE_TYPE_CLEANUP(confbridge_start_record_type);
    STASIS_MESSAGE_TYPE_CLEANUP(confbridge_stop_record_type);
    STASIS_MESSAGE_TYPE_CLEANUP(confbridge_mute_type);
    STASIS_MESSAGE_TYPE_CLEANUP(confbridge_unmute_type);
    STASIS_MESSAGE_TYPE_CLEANUP(confbridge_talking_type);
    STASIS_MESSAGE_TYPE_CLEANUP(confbridge_welcome_type);
    if (bridge_state_router) {
       stasis_message_router_unsubscribe(bridge_state_router);
       bridge_state_router = NULL;
    }
    if (channel_state_router) {
       stasis_message_router_unsubscribe(channel_state_router);
       channel_state_router = NULL;
    }
 }
play_sound_file()
int play_sound_file (struct confbridge_conference * conference, const char * filename)
Play sound file into conference bridge.
Parameters
conference The conference bridge to play sound file into
filename Sound file to play
Return values
0 success
-1 failure
Definition at line 2035 of file app_confbridge.c.
References play_sound_helper().
Referenced by action_toggle_mute_participants(), announce_user_count(), confbridge_exec(), and post_join_play_begin().
 {
    return play_sound_helper(conference, filename, -1);
 }
Variable Documentation
conference_bridges
struct ao2_container* conference_bridges
Container to hold all conference bridges in progress.
Definition at line 469 of file app_confbridge.c.
Referenced by announce_request().