Asterisk - The Open Source Telephony Project: strcompat.c File Reference
strcompat.c File Reference
Compatibility functions for strsep and strtoq missing on Solaris.
#include "asterisk.h"
#include <ctype.h>
#include <sys/time.h>
#include <sys/resource.h>
#include <sys/types.h>
#include <dirent.h>
#include <unistd.h>
#include <fcntl.h>
#include "asterisk/utils.h"
Macros
#define ASTMM_LIBC ASTMM_IGNORE
#define POLL_SIZE 1024
Functions
void closefrom (int n)
uint64_t htonll (uint64_t host64)
uint64_t ntohll (uint64_t net64)
Detailed Description
Compatibility functions for strsep and strtoq missing on Solaris.
.. and lots of other functions too.
Definition in file strcompat.c.
Macro Definition Documentation
ASTMM_LIBC
#define ASTMM_LIBC ASTMM_IGNORE
Definition at line 28 of file strcompat.c.
POLL_SIZE
#define POLL_SIZE 1024
Definition at line 41 of file strcompat.c.
Referenced by closefrom().
Function Documentation
closefrom()
void closefrom (int n)
Definition at line 429 of file strcompat.c.
References ast_random(), errno, len(), mkdtemp(), NULL, POLL_SIZE, and roundf().
Referenced by ast_close_fds_above_n().
 {
    int maxfd;
 #ifndef _SC_OPEN_MAX
    struct rlimit rl;
 #endif
    struct pollfd fds[POLL_SIZE];
    int fd=n, loopmax, i;
 #ifndef STRICT_COMPAT
    long flags;
 #endif
 #ifndef _SC_OPEN_MAX
    if (getrlimit(RLIMIT_NOFILE, &rl) == -1) {
       maxfd = -1;
    } else {
       maxfd = rl.rlim_cur;
    }
 #else
    maxfd = sysconf (_SC_OPEN_MAX);
 #endif
    if (maxfd == -1 || maxfd > 65536) {
       /* A more reasonable value.  Consider that the primary source of
        * file descriptors in Asterisk are UDP sockets, of which we are
        * limited to 65,535 per address.  We additionally limit that down
        * to about 10,000 sockets per protocol.  While the kernel will
        * allow us to set the fileno limit higher (up to 4.2 billion),
        * there really is no practical reason for it to be that high.
        *
        * sysconf as well as getrlimit can return -1 on error. Let's set
        * maxfd to the mentioned reasonable value of 65,535 in this case.
        */
       maxfd = 65536;
    }
    while (fd < maxfd) {
       loopmax = maxfd - fd;
       if (loopmax > POLL_SIZE) {
          loopmax = POLL_SIZE;
       }
       for (i = 0; i < loopmax; i++) {
          fds[i].fd = fd+i;
          fds[i].events = 0;
       }
       poll(fds, loopmax, 0);
       for (i = 0; i < loopmax; i++) {
          if (fds[i].revents == POLLNVAL) {
             continue;
          }
 #ifdef STRICT_COMPAT
          close(fds[i].fd);
 #else
          /* This isn't strictly compatible, but it's actually faster
           * for our purposes to set the CLOEXEC flag than to close
           * file descriptors.
           */
          flags = fcntl(fds[i].fd, F_GETFD);
          if (flags == -1 && errno == EBADF) {
             continue;
          }
          fcntl(fds[i].fd, F_SETFD, flags | FD_CLOEXEC);
 #endif
       }
       fd += loopmax;
    }
 }
htonll()
uint64_t htonll (uint64_t host64)
Definition at line 390 of file strcompat.c.
References c, and ffsll().
Referenced by ast_websocket_write(), and iax_ie_append_versioned_uint64().
 {
 #if BYTE_ORDER == BIG_ENDIAN
    return host64;
 #elif BYTE_ORDER == LITTLE_ENDIAN
    union {
       unsigned char c[8];
       uint64_t u;
    } number;
    number.u = host64;
    return
       (((uint64_t) number.c[0]) << 56) |
       (((uint64_t) number.c[1]) << 48) |
       (((uint64_t) number.c[2]) << 40) |
       (((uint64_t) number.c[3]) << 32) |
       (((uint64_t) number.c[4]) << 24) |
       (((uint64_t) number.c[5]) << 16) |
       (((uint64_t) number.c[6]) <<  8) |
       (((uint64_t) number.c[7]) <<  0);
 #else
    #error "Unknown byte order"
 #endif
 }
ntohll()
uint64_t ntohll (uint64_t net64)
Definition at line 364 of file strcompat.c.
References c.
Referenced by ast_websocket_read(), dump_versioned_codec(), and iax_parse_ies().
 {
 #if BYTE_ORDER == BIG_ENDIAN
    return net64;
 #elif BYTE_ORDER == LITTLE_ENDIAN
    union {
       unsigned char c[8];
       uint64_t u;
    } number;
    number.u = net64;
    return
       (((uint64_t) number.c[0]) << 56) |
       (((uint64_t) number.c[1]) << 48) |
       (((uint64_t) number.c[2]) << 40) |
       (((uint64_t) number.c[3]) << 32) |
       (((uint64_t) number.c[4]) << 24) |
       (((uint64_t) number.c[5]) << 16) |
       (((uint64_t) number.c[6]) <<  8) |
       (((uint64_t) number.c[7]) <<  0);
 #else
    #error "Unknown byte order"
 #endif
 }