Asterisk - The Open Source Telephony Project: res_ari_playbacks.c File Reference
res_ari_playbacks.c File Reference
Playback control resources.
#include "asterisk.h"
#include "asterisk/app.h"
#include "asterisk/module.h"
#include "asterisk/stasis_app.h"
#include "ari/resource_playbacks.h"
#include "ari/ari_model_validators.h"
Macros
#define MAX_VALS 128
Functions
static void __reg_module (void)
static void __unreg_module (void)
static void ast_ari_playbacks_control_cb (struct ast_tcptls_session_instance *ser, struct ast_variable *get_params, struct ast_variable *path_vars, struct ast_variable *headers, struct ast_json *body, struct ast_ari_response *response)
Parameter parsing callback for /playbacks/{playbackId}/control.
int ast_ari_playbacks_control_parse_body (struct ast_json *body, struct ast_ari_playbacks_control_args *args)
Body parsing function for /playbacks/{playbackId}/control.
static void ast_ari_playbacks_get_cb (struct ast_tcptls_session_instance *ser, struct ast_variable *get_params, struct ast_variable *path_vars, struct ast_variable *headers, struct ast_json *body, struct ast_ari_response *response)
Parameter parsing callback for /playbacks/{playbackId}.
static void ast_ari_playbacks_stop_cb (struct ast_tcptls_session_instance *ser, struct ast_variable *get_params, struct ast_variable *path_vars, struct ast_variable *headers, struct ast_json *body, struct ast_ari_response *response)
Parameter parsing callback for /playbacks/{playbackId}.
struct ast_module * AST_MODULE_SELF_SYM (void)
static int load_module (void)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_DEFAULT , .description = "RESTful API module - Playback control resources" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .requires = "res_ari,res_ari_model,res_stasis,res_stasis_playback", }
static const struct ast_module_info * ast_module_info = &__mod_info
static struct stasis_rest_handlers playbacks
REST handler for /api-docs/playbacks.json.
static struct stasis_rest_handlers playbacks_playbackId
REST handler for /api-docs/playbacks.json.
static struct stasis_rest_handlers playbacks_playbackId_control
REST handler for /api-docs/playbacks.json.
Detailed Description
Playback control resources.
Author
David M. Lee, II dlee@.nosp@m.digi.nosp@m.um.co.nosp@m.m
Definition in file res_ari_playbacks.c.
Macro Definition Documentation
MAX_VALS
#define MAX_VALS 128
Definition at line 52 of file res_ari_playbacks.c.
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 308 of file res_ari_playbacks.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 308 of file res_ari_playbacks.c.
ast_ari_playbacks_control_cb()
static void ast_ari_playbacks_control_cb (struct ast_tcptls_session_instance * ser, struct ast_variable * get_params, struct ast_variable * path_vars, struct ast_variable * headers, struct ast_json * body, struct ast_ari_response * response) static
Parameter parsing callback for /playbacks/{playbackId}/control.
Parameters
get_params GET parameters in the HTTP request.
path_vars Path variables extracted from the request.
headers HTTP headers.
[out] response Response to the HTTP request.
Definition at line 190 of file res_ari_playbacks.c.
References ast_ari_playbacks_control(), ast_ari_playbacks_control_parse_body(), ast_ari_response_alloc_failed(), ast_ari_response_error(), ast_ari_validate_void(), ast_log, LOG_ERROR, ast_ari_response::message, ast_variable::name, ast_variable::next, NULL, ast_ari_playbacks_control_args::operation, ast_ari_playbacks_control_args::playback_id, ast_ari_response::response_code, and ast_variable::value.
 {
    struct ast_ari_playbacks_control_args args = {};
    struct ast_variable *i;
 #if defined(AST_DEVMODE)
    int is_valid;
    int code;
 #endif /* AST_DEVMODE */
    for (i = get_params; i; i = i->next) {
       if (strcmp(i->name, "operation") == 0) {
          args.operation = (i->value);
       } else
       {}
    }
    for (i = path_vars; i; i = i->next) {
       if (strcmp(i->name, "playbackId") == 0) {
          args.playback_id = (i->value);
       } else
       {}
    }
    if (ast_ari_playbacks_control_parse_body(body, &args)) {
       ast_ari_response_alloc_failed(response);
       goto fin;
    }
    ast_ari_playbacks_control(headers, &args, response);
 #if defined(AST_DEVMODE)
    code = response->response_code;
    switch (code) {
    case 0: /* Implementation is still a stub, or the code wasn't set */
       is_valid = response->message == NULL;
       break;
    case 500: /* Internal Server Error */
    case 501: /* Not Implemented */
    case 400: /* The provided operation parameter was invalid */
    case 404: /* The playback cannot be found */
    case 409: /* The operation cannot be performed in the playback's current state */
       is_valid = 1;
       break;
    default:
       if (200 <= code && code <= 299) {
          is_valid = ast_ari_validate_void(
             response->message);
       } else {
          ast_log(LOG_ERROR, "Invalid error response %d for /playbacks/{playbackId}/control\n", code);
          is_valid = 0;
       }
    }
    if (!is_valid) {
       ast_log(LOG_ERROR, "Response validation failed for /playbacks/{playbackId}/control\n");
       ast_ari_response_error(response, 500,
          "Internal Server Error", "Response validation failed");
    }
 #endif /* AST_DEVMODE */
 fin: __attribute__((unused))
    return;
 }
ast_ari_playbacks_control_parse_body()
int ast_ari_playbacks_control_parse_body (struct ast_json * body, struct ast_ari_playbacks_control_args * args)
Body parsing function for /playbacks/{playbackId}/control.
Parameters
body The JSON body from which to parse parameters.
[out] args The args structure to parse into.
Return values
zero on success
non-zero on failure
Definition at line 170 of file res_ari_playbacks.c.
References ast_json_object_get(), ast_json_string_get(), and ast_ari_playbacks_control_args::operation.
Referenced by ast_ari_playbacks_control_cb().
 {
    struct ast_json *field;
    /* Parse query parameters out of it */
    field = ast_json_object_get(body, "operation");
    if (field) {
       args->operation = ast_json_string_get(field);
    }
    return 0;
 }
ast_ari_playbacks_get_cb()
static void ast_ari_playbacks_get_cb (struct ast_tcptls_session_instance * ser, struct ast_variable * get_params, struct ast_variable * path_vars, struct ast_variable * headers, struct ast_json * body, struct ast_ari_response * response) static
Parameter parsing callback for /playbacks/{playbackId}.
Parameters
get_params GET parameters in the HTTP request.
path_vars Path variables extracted from the request.
headers HTTP headers.
[out] response Response to the HTTP request.
Definition at line 61 of file res_ari_playbacks.c.
References ast_ari_playbacks_get(), ast_ari_response_error(), ast_ari_validate_playback(), ast_log, LOG_ERROR, ast_ari_response::message, ast_variable::name, ast_variable::next, NULL, ast_ari_playbacks_get_args::playback_id, ast_ari_response::response_code, and ast_variable::value.
 {
    struct ast_ari_playbacks_get_args args = {};
    struct ast_variable *i;
 #if defined(AST_DEVMODE)
    int is_valid;
    int code;
 #endif /* AST_DEVMODE */
    for (i = path_vars; i; i = i->next) {
       if (strcmp(i->name, "playbackId") == 0) {
          args.playback_id = (i->value);
       } else
       {}
    }
    ast_ari_playbacks_get(headers, &args, response);
 #if defined(AST_DEVMODE)
    code = response->response_code;
    switch (code) {
    case 0: /* Implementation is still a stub, or the code wasn't set */
       is_valid = response->message == NULL;
       break;
    case 500: /* Internal Server Error */
    case 501: /* Not Implemented */
    case 404: /* The playback cannot be found */
       is_valid = 1;
       break;
    default:
       if (200 <= code && code <= 299) {
          is_valid = ast_ari_validate_playback(
             response->message);
       } else {
          ast_log(LOG_ERROR, "Invalid error response %d for /playbacks/{playbackId}\n", code);
          is_valid = 0;
       }
    }
    if (!is_valid) {
       ast_log(LOG_ERROR, "Response validation failed for /playbacks/{playbackId}\n");
       ast_ari_response_error(response, 500,
          "Internal Server Error", "Response validation failed");
    }
 #endif /* AST_DEVMODE */
 fin: __attribute__((unused))
    return;
 }
ast_ari_playbacks_stop_cb()
static void ast_ari_playbacks_stop_cb (struct ast_tcptls_session_instance * ser, struct ast_variable * get_params, struct ast_variable * path_vars, struct ast_variable * headers, struct ast_json * body, struct ast_ari_response * response) static
Parameter parsing callback for /playbacks/{playbackId}.
Parameters
get_params GET parameters in the HTTP request.
path_vars Path variables extracted from the request.
headers HTTP headers.
[out] response Response to the HTTP request.
Definition at line 119 of file res_ari_playbacks.c.
References ast_ari_playbacks_stop(), ast_ari_response_error(), ast_ari_validate_void(), ast_log, LOG_ERROR, ast_ari_response::message, ast_variable::name, ast_variable::next, NULL, ast_ari_playbacks_stop_args::playback_id, ast_ari_response::response_code, and ast_variable::value.
 {
    struct ast_ari_playbacks_stop_args args = {};
    struct ast_variable *i;
 #if defined(AST_DEVMODE)
    int is_valid;
    int code;
 #endif /* AST_DEVMODE */
    for (i = path_vars; i; i = i->next) {
       if (strcmp(i->name, "playbackId") == 0) {
          args.playback_id = (i->value);
       } else
       {}
    }
    ast_ari_playbacks_stop(headers, &args, response);
 #if defined(AST_DEVMODE)
    code = response->response_code;
    switch (code) {
    case 0: /* Implementation is still a stub, or the code wasn't set */
       is_valid = response->message == NULL;
       break;
    case 500: /* Internal Server Error */
    case 501: /* Not Implemented */
    case 404: /* The playback cannot be found */
       is_valid = 1;
       break;
    default:
       if (200 <= code && code <= 299) {
          is_valid = ast_ari_validate_void(
             response->message);
       } else {
          ast_log(LOG_ERROR, "Invalid error response %d for /playbacks/{playbackId}\n", code);
          is_valid = 0;
       }
    }
    if (!is_valid) {
       ast_log(LOG_ERROR, "Response validation failed for /playbacks/{playbackId}\n");
       ast_ari_response_error(response, 500,
          "Internal Server Error", "Response validation failed");
    }
 #endif /* AST_DEVMODE */
 fin: __attribute__((unused))
    return;
 }
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 308 of file res_ari_playbacks.c.
load_module()
static int load_module (void) static
Definition at line 289 of file res_ari_playbacks.c.
References ast_ari_add_handler(), AST_MODFLAG_DEFAULT, AST_MODULE_INFO(), AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, AST_MODULE_SUPPORT_CORE, ASTERISK_GPL_KEY, and unload_module().
 {
    int res = 0;
    res |= ast_ari_add_handler(&playbacks);
    if (res) {
       unload_module();
       return AST_MODULE_LOAD_DECLINE;
    }
    return AST_MODULE_LOAD_SUCCESS;
 }
unload_module()
static int unload_module (void) static
Definition at line 283 of file res_ari_playbacks.c.
References ast_ari_remove_handler().
Referenced by load_module().
 {
    ast_ari_remove_handler(&playbacks);
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_DEFAULT , .description = "RESTful API module - Playback control resources" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .requires = "res_ari,res_ari_model,res_stasis,res_stasis_playback", } static
Definition at line 308 of file res_ari_playbacks.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 308 of file res_ari_playbacks.c.
playbacks
struct stasis_rest_handlers playbacks static
REST handler for /api-docs/playbacks.json.
Definition at line 275 of file res_ari_playbacks.c.
playbacks_playbackId
struct stasis_rest_handlers playbacks_playbackId static
REST handler for /api-docs/playbacks.json.
Definition at line 264 of file res_ari_playbacks.c.
playbacks_playbackId_control
struct stasis_rest_handlers playbacks_playbackId_control static
REST handler for /api-docs/playbacks.json.
Definition at line 255 of file res_ari_playbacks.c.