Asterisk - The Open Source Telephony Project: test_core_codec.c File Reference
test_core_codec.c File Reference
Core Codec API Unit Tests.
#include "asterisk.h"
#include "asterisk/test.h"
#include "asterisk/module.h"
#include "asterisk/codec.h"
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
AST_TEST_DEFINE (codec_register)
AST_TEST_DEFINE (codec_register_twice)
AST_TEST_DEFINE (codec_register_unknown)
AST_TEST_DEFINE (codec_register_audio_no_sample_rate)
AST_TEST_DEFINE (codec_get)
AST_TEST_DEFINE (codec_get_unregistered)
AST_TEST_DEFINE (codec_get_unknown)
AST_TEST_DEFINE (codec_get_id)
static int load_module (void)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Core codec API test module" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, }
static const struct ast_module_info * ast_module_info = &__mod_info
static struct ast_codec audio_get
static struct ast_codec audio_get_id
static struct ast_codec audio_get_unknown
static struct ast_codec audio_without_rate
static struct ast_codec doubly
static struct ast_codec known_unknown
static struct ast_codec unknown
Detailed Description
Core Codec API Unit Tests.
Author
Joshua Colp jcolp.nosp@m.@dig.nosp@m.ium.c.nosp@m.om
Definition in file test_core_codec.c.
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 367 of file test_core_codec.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 367 of file test_core_codec.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 367 of file test_core_codec.c.
AST_TEST_DEFINE() [1/8]
AST_TEST_DEFINE (codec_register)
Definition at line 107 of file test_core_codec.c.
References ast_codec_register, AST_TEST_FAIL, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_test_status_update, sip_to_pjsip::info(), TEST_EXECUTE, and TEST_INIT.
 {
    switch (cmd) {
    case TEST_INIT:
       info->name = "codec_register";
       info->category = "/main/core_codec/";
       info->summary = "codec registration unit test";
       info->description =
          "Test registration of a core codec that is known to be unknown";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    if (ast_codec_register(&known_unknown)) {
       ast_test_status_update(test, "Unsuccessfully registered a codec that is known to be unknown\n");
       return AST_TEST_FAIL;
    }
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [2/8]
AST_TEST_DEFINE (codec_register_twice)
Definition at line 129 of file test_core_codec.c.
References ast_codec_register, AST_TEST_FAIL, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_test_status_update, sip_to_pjsip::info(), TEST_EXECUTE, and TEST_INIT.
 {
    switch (cmd) {
    case TEST_INIT:
       info->name = "codec_register_twice";
       info->category = "/main/core_codec/";
       info->summary = "codec registration unit test";
       info->description =
          "Test double registration of a core codec to confirm it fails";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    if (ast_codec_register(&doubly)) {
       ast_test_status_update(test, "Unsuccessfully registered a codec that is known to be unknown\n");
       return AST_TEST_FAIL;
    }
    if (!ast_codec_register(&doubly)) {
       ast_test_status_update(test, "Successfully registered a codec twice\n");
       return AST_TEST_FAIL;
    }
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [3/8]
AST_TEST_DEFINE (codec_register_unknown)
Definition at line 156 of file test_core_codec.c.
References ast_codec_register, AST_TEST_FAIL, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_test_status_update, sip_to_pjsip::info(), TEST_EXECUTE, and TEST_INIT.
 {
    switch (cmd) {
    case TEST_INIT:
       info->name = "codec_register_unknown";
       info->category = "/main/core_codec/";
       info->summary = "codec registration unit test";
       info->description =
          "Test that registration of an unknown codec type fails";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    if (!ast_codec_register(&unknown)) {
       ast_test_status_update(test, "Successfully registered a codec with an unknown media type\n");
       return AST_TEST_FAIL;
    }
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [4/8]
AST_TEST_DEFINE (codec_register_audio_no_sample_rate)
Definition at line 178 of file test_core_codec.c.
References ast_codec_register, AST_TEST_FAIL, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_test_status_update, sip_to_pjsip::info(), TEST_EXECUTE, and TEST_INIT.
 {
    switch (cmd) {
    case TEST_INIT:
       info->name = "codec_register_audio_no_sample_rate";
       info->category = "/main/core_codec/";
       info->summary = "codec registration unit test";
       info->description =
          "Test that registration of an audio codec without sample rate fails";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    if (!ast_codec_register(&audio_without_rate)) {
       ast_test_status_update(test, "Successfully registered an audio codec without a sample rate\n");
       return AST_TEST_FAIL;
    }
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [5/8]
AST_TEST_DEFINE (codec_get)
Definition at line 200 of file test_core_codec.c.
References ao2_cleanup, ast_codec_get(), ast_codec_register, AST_MEDIA_TYPE_AUDIO, AST_TEST_FAIL, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_test_status_update, sip_to_pjsip::info(), ast_codec::name, NULL, RAII_VAR, ast_codec::sample_rate, TEST_EXECUTE, TEST_INIT, and ast_codec::type.
 {
    RAII_VAR(struct ast_codec *, codec, NULL, ao2_cleanup);
    switch (cmd) {
    case TEST_INIT:
       info->name = "codec_get";
       info->category = "/main/core_codec/";
       info->summary = "codec get unit test";
       info->description =
          "Test that getting of a known codec succeeds";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    if (ast_codec_register(&audio_get)) {
       ast_test_status_update(test, "Unsucessfully registered a codec for getting\n");
       return AST_TEST_FAIL;
    }
    codec = ast_codec_get("unit_test_audio_get", AST_MEDIA_TYPE_AUDIO, 8000);
    if (!codec) {
       ast_test_status_update(test, "Unsuccessfully retrieved a codec we just registered\n");
       return AST_TEST_FAIL;
    } else if (strcmp(codec->name, audio_get.name)) {
       ast_test_status_update(test, "Name of retrieved codec does not match registered codec\n");
       return AST_TEST_FAIL;
    } else if (codec->type != audio_get.type) {
       ast_test_status_update(test, "Type of retrieved codec does not match registered codec\n");
       return AST_TEST_FAIL;
    } else if (codec->sample_rate != audio_get.sample_rate) {
       ast_test_status_update(test, "Sample rate of retrieved codec does not match registered codec\n");
       return AST_TEST_FAIL;
    }
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [6/8]
AST_TEST_DEFINE (codec_get_unregistered)
Definition at line 239 of file test_core_codec.c.
References ao2_cleanup, ast_codec_get(), AST_MEDIA_TYPE_AUDIO, AST_TEST_FAIL, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_test_status_update, sip_to_pjsip::info(), test::name, NULL, RAII_VAR, TEST_EXECUTE, and TEST_INIT.
 {
    RAII_VAR(struct ast_codec *, codec, NULL, ao2_cleanup);
    switch (cmd) {
    case TEST_INIT:
       info->name = "codec_get_unregistered";
       info->category = "/main/core_codec/";
       info->summary = "codec get unit test";
       info->description =
          "Test that getting of a codec that is not registered fails";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    codec = ast_codec_get("goats", AST_MEDIA_TYPE_AUDIO, 8000);
    if (codec) {
       ast_test_status_update(test, "Successfully got a codec named '%s' when getting a codec named 'goats'\n",
          codec->name);
       return AST_TEST_FAIL;
    }
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [7/8]
AST_TEST_DEFINE (codec_get_unknown)
Definition at line 265 of file test_core_codec.c.
References ao2_cleanup, ast_codec_get(), ast_codec_register, AST_MEDIA_TYPE_UNKNOWN, AST_TEST_FAIL, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_test_status_update, sip_to_pjsip::info(), ast_codec::name, NULL, RAII_VAR, ast_codec::sample_rate, TEST_EXECUTE, TEST_INIT, and ast_codec::type.
 {
    RAII_VAR(struct ast_codec *, codec, NULL, ao2_cleanup);
    switch (cmd) {
    case TEST_INIT:
       info->name = "codec_get_unknown";
       info->category = "/main/core_codec/";
       info->summary = "codec get unit test";
       info->description =
          "Test that getting of a known codec using name and unknown type succeeds";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    if (ast_codec_register(&audio_get_unknown)) {
       ast_test_status_update(test, "Unsucessfully registered a codec for getting\n");
       return AST_TEST_FAIL;
    }
    codec = ast_codec_get("unit_test_audio_get_unknown", AST_MEDIA_TYPE_UNKNOWN, 8000);
    if (!codec) {
       ast_test_status_update(test, "Unsuccessfully retrieved a codec we just registered\n");
       return AST_TEST_FAIL;
    } else if (strcmp(codec->name, audio_get_unknown.name)) {
       ast_test_status_update(test, "Name of retrieved codec does not match registered codec\n");
       return AST_TEST_FAIL;
    } else if (codec->type != audio_get_unknown.type) {
       ast_test_status_update(test, "Type of retrieved codec does not match registered codec\n");
       return AST_TEST_FAIL;
    } else if (codec->sample_rate != audio_get_unknown.sample_rate) {
       ast_test_status_update(test, "Sample rate of retrieved codec does not match registered codec\n");
       return AST_TEST_FAIL;
    }
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [8/8]
AST_TEST_DEFINE (codec_get_id)
Definition at line 304 of file test_core_codec.c.
References ao2_cleanup, ast_codec_get(), ast_codec_get_by_id(), ast_codec_register, AST_MEDIA_TYPE_AUDIO, AST_TEST_FAIL, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_test_status_update, sip_to_pjsip::info(), NULL, RAII_VAR, TEST_EXECUTE, and TEST_INIT.
 {
    RAII_VAR(struct ast_codec *, named, NULL, ao2_cleanup);
    RAII_VAR(struct ast_codec *, codec, NULL, ao2_cleanup);
    switch (cmd) {
    case TEST_INIT:
       info->name = "codec_get_unknown";
       info->category = "/main/core_codec/";
       info->summary = "codec get unit test";
       info->description =
          "Test that getting of a known codec using name and unknown type succeeds";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    if (ast_codec_register(&audio_get_id)) {
       ast_test_status_update(test, "Unsucessfully registered a codec for getting\n");
       return AST_TEST_FAIL;
    }
    named = ast_codec_get("unit_test_audio_get_id", AST_MEDIA_TYPE_AUDIO, 8000);
    if (!named) {
       ast_test_status_update(test, "Unsuccessfully retrieved a codec we just registered\n");
       return AST_TEST_FAIL;
    }
    codec = ast_codec_get_by_id(named->id);
    if (!codec) {
       ast_test_status_update(test, "Unsuccessfully retrieved a codec using id of a named codec we just got\n");
       return AST_TEST_FAIL;
    }
    return AST_TEST_PASS;
 }
load_module()
static int load_module (void) static
Definition at line 354 of file test_core_codec.c.
References AST_MODULE_LOAD_SUCCESS, and AST_TEST_REGISTER.
 {
    AST_TEST_REGISTER(codec_register);
    AST_TEST_REGISTER(codec_register_twice);
    AST_TEST_REGISTER(codec_register_unknown);
    AST_TEST_REGISTER(codec_register_audio_no_sample_rate);
    AST_TEST_REGISTER(codec_get);
    AST_TEST_REGISTER(codec_get_unregistered);
    AST_TEST_REGISTER(codec_get_unknown);
    AST_TEST_REGISTER(codec_get_id);
    return AST_MODULE_LOAD_SUCCESS;
 }
unload_module()
static int unload_module (void) static
Definition at line 341 of file test_core_codec.c.
References AST_TEST_UNREGISTER.
 {
    AST_TEST_UNREGISTER(codec_register);
    AST_TEST_UNREGISTER(codec_register_twice);
    AST_TEST_UNREGISTER(codec_register_unknown);
    AST_TEST_UNREGISTER(codec_register_audio_no_sample_rate);
    AST_TEST_UNREGISTER(codec_get);
    AST_TEST_UNREGISTER(codec_get_unregistered);
    AST_TEST_UNREGISTER(codec_get_unknown);
    AST_TEST_UNREGISTER(codec_get_id);
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Core codec API test module" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, } static
Definition at line 367 of file test_core_codec.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 367 of file test_core_codec.c.
audio_get
struct ast_codec audio_get static
Definition at line 77 of file test_core_codec.c.
audio_get_id
struct ast_codec audio_get_id static
Definition at line 97 of file test_core_codec.c.
audio_get_unknown
struct ast_codec audio_get_unknown static
Definition at line 87 of file test_core_codec.c.
audio_without_rate
struct ast_codec audio_without_rate static
Definition at line 68 of file test_core_codec.c.
doubly
struct ast_codec doubly static
Definition at line 48 of file test_core_codec.c.
known_unknown
struct ast_codec known_unknown static
Definition at line 38 of file test_core_codec.c.
unknown
struct ast_codec unknown static
Definition at line 58 of file test_core_codec.c.
Referenced by odbc_log().