Asterisk - The Open Source Telephony Project: res_pjsip.c File Reference
res_pjsip.c File Reference
#include "asterisk.h"
#include <pjsip.h>
#include <pjsip_simple.h>
#include <pjsip/sip_transaction.h>
#include <pj/timer.h>
#include <pjlib.h>
#include <pjmedia/errno.h>
#include "asterisk/res_pjsip.h"
#include "res_pjsip/include/res_pjsip_private.h"
#include "asterisk/linkedlists.h"
#include "asterisk/logger.h"
#include "asterisk/lock.h"
#include "asterisk/utils.h"
#include "asterisk/astobj2.h"
#include "asterisk/module.h"
#include "asterisk/serializer.h"
#include "asterisk/threadpool.h"
#include "asterisk/taskprocessor.h"
#include "asterisk/uuid.h"
#include "asterisk/sorcery.h"
#include "asterisk/file.h"
#include "asterisk/cli.h"
#include "asterisk/res_pjsip_cli.h"
#include "asterisk/test.h"
#include "asterisk/res_pjsip_presence_xml.h"
#include "asterisk/res_pjproject.h"
Data Structures
struct endpoint_formatters
struct endpoint_identifier_list
struct endpoint_identifiers
struct send_request_data
Structure to hold information about an outbound request.
struct send_request_wrapper
struct supplements
struct sync_task_data
Macros
#define ENDPOINT_IDENTIFIER_FORMAT "%-20.20s\n"
#define MOD_DATA_CONTACT "contact"
#define SERIALIZER_POOL_SIZE 8
#define SIP_SERVANT_ID 0x5E2F1D
#define TIMEOUT_TIMER2 5
#define TIMER_INACTIVE 0
Typedefs
typedef pj_status_t(* create_dlg_uac) (pjsip_user_agent *ua, pjsip_rx_data *rdata, const pj_str_t *contact, pjsip_dialog **p_dlg)
Functions
static void __init_pj_thread_storage (void)
static void __init_servant_id_storage (void)
static void __reg_module (void)
static void __unreg_module (void)
static pjsip_msg_body * ast_body_to_pjsip_body (pj_pool_t *pool, const struct ast_sip_body *body)
void ast_copy_pj_str (char *dest, const pj_str_t *src, size_t size)
Copy a pj_str_t into a standard character buffer.
int ast_copy_pj_str2 (char **dest, const pj_str_t *src)
Create and copy a pj_str_t into a standard character buffer.
struct ast_module * AST_MODULE_SELF_SYM (void)
int ast_sip_add_body (pjsip_tx_data *tdata, const struct ast_sip_body *body)
Add a body to an outbound SIP message.
int ast_sip_add_body_multipart (pjsip_tx_data *tdata, const struct ast_sip_body *bodies[], int num_bodies)
Add a multipart body to an outbound SIP message.
void ast_sip_add_date_header (pjsip_tx_data *tdata)
Adds a Date header to the tdata, formatted like: Date: Wed, 01 Jan 2021 14:53:01 GMT.
int ast_sip_add_header (pjsip_tx_data *tdata, const char *name, const char *value)
Add a header to an outbound SIP message.
void ast_sip_add_usereqphone (const struct ast_sip_endpoint *endpoint, pj_pool_t *pool, pjsip_uri *uri)
Add 'user=phone' parameter to URI if enabled and user is a phone number.
int ast_sip_append_body (pjsip_tx_data *tdata, const char *body_text)
Append body data to a SIP message.
const char * ast_sip_call_codec_pref_to_str (struct ast_flags pref)
Convert the call codec preference flags to a string.
int ast_sip_call_codec_str_to_pref (struct ast_flags *pref, const char *pref_str, int is_outgoing)
Convert a call codec preference string to preference flags.
enum ast_sip_check_auth_result ast_sip_check_authentication (struct ast_sip_endpoint *endpoint, pjsip_rx_data *rdata, pjsip_tx_data *tdata)
Method to determine authentication status of an incoming request.
pjsip_dialog * ast_sip_create_dialog_uac (const struct ast_sip_endpoint *endpoint, const char *uri, const char *request_user)
General purpose method for creating a UAC dialog with an endpoint.
pjsip_dialog * ast_sip_create_dialog_uas (const struct ast_sip_endpoint *endpoint, pjsip_rx_data *rdata, pj_status_t *status)
General purpose method for creating a UAS dialog with an endpoint.
pjsip_dialog * ast_sip_create_dialog_uas_locked (const struct ast_sip_endpoint *endpoint, pjsip_rx_data *rdata, pj_status_t *status)
General purpose method for creating a UAS dialog with an endpoint.
int ast_sip_create_rdata (pjsip_rx_data *rdata, char *packet, const char *src_name, int src_port, char *transport_type, const char *local_name, int local_port)
General purpose method for creating an rdata structure using specific information.
int ast_sip_create_rdata_with_contact (pjsip_rx_data *rdata, char *packet, const char *src_name, int src_port, char *transport_type, const char *local_name, int local_port, const char *contact)
General purpose method for creating an rdata structure using specific information.
int ast_sip_create_request (const char *method, struct pjsip_dialog *dlg, struct ast_sip_endpoint *endpoint, const char *uri, struct ast_sip_contact *contact, pjsip_tx_data **tdata)
General purpose method for creating a SIP request.
int ast_sip_create_request_with_auth (const struct ast_sip_auth_vector *auths, pjsip_rx_data *challenge, pjsip_tx_data *old_request, pjsip_tx_data **new_request)
Create a response to an authentication challenge.
int ast_sip_create_response (const pjsip_rx_data *rdata, int st_code, struct ast_sip_contact *contact, pjsip_tx_data **tdata)
General purpose method for creating a SIP response.
struct ast_taskprocessor * ast_sip_create_serializer (const char *name)
Create a new serializer for SIP tasks.
struct ast_taskprocessor * ast_sip_create_serializer_group (const char *name, struct ast_serializer_shutdown_group *shutdown_group)
Create a new serializer for SIP tasks.
void * ast_sip_dict_get (void *ht, const char *key)
Retrieves the value associated with the given key.
void * ast_sip_dict_set (pj_pool_t *pool, void *ht, const char *key, void *val)
Set the value for the given key.
int ast_sip_dlg_set_transport (const struct ast_sip_endpoint *endpoint, pjsip_dialog *dlg, pjsip_tpselector *selector)
Set the transport on a dialog.
int ast_sip_dtmf_to_str (const enum ast_sip_dtmf_mode dtmf, char *buf, size_t buf_len)
Convert the DTMF mode enum value into a string.
int ast_sip_failover_request (pjsip_tx_data *tdata)
Set a request to use the next value in the list of resolved addresses.
int ast_sip_format_endpoint_ami (struct ast_sip_endpoint *endpoint, struct ast_sip_ami *ami, int *count)
Formats the endpoint and sends over AMI.
int ast_sip_get_host_ip (int af, pj_sockaddr *addr)
Retrieve the local host address in IP form.
const char * ast_sip_get_host_ip_string (int af)
Retrieve the local host address in string form.
pjsip_endpoint * ast_sip_get_pjsip_endpoint (void)
Get a pointer to the PJSIP endpoint.
int ast_sip_get_transport_name (const struct ast_sip_endpoint *endpoint, pjsip_sip_uri *sip_uri, char *buf, size_t buf_len)
Get the transport name from an endpoint or request uri.
struct ast_sip_endpoint * ast_sip_identify_endpoint (pjsip_rx_data *rdata)
Determine the endpoint that has sent a SIP message.
int ast_sip_is_content_type (pjsip_media_type *content_type, char *type, char *subtype)
Checks if the given content type matches type/subtype.
void ast_sip_modify_id_header (pj_pool_t *pool, pjsip_fromto_hdr *id_hdr, const struct ast_party_id *id)
Set name and number information on an identity header.
int ast_sip_push_task (struct ast_taskprocessor *serializer, int(*sip_task)(void *), void *task_data)
Pushes a task to SIP servants.
int ast_sip_push_task_synchronous (struct ast_taskprocessor *serializer, int(*sip_task)(void *), void *task_data)
Push a task to SIP servants and wait for it to complete.
static int ast_sip_push_task_wait (struct ast_taskprocessor *serializer, int(*sip_task)(void *), void *task_data)
int ast_sip_push_task_wait_serializer (struct ast_taskprocessor *serializer, int(*sip_task)(void *), void *task_data)
Push a task to the serializer and wait for it to complete.
int ast_sip_push_task_wait_servant (struct ast_taskprocessor *serializer, int(*sip_task)(void *), void *task_data)
Push a task to SIP servants and wait for it to complete.
char * ast_sip_rdata_get_header_value (pjsip_rx_data *rdata, const pj_str_t str)
Get a specific header value from rdata.
int ast_sip_register_authenticator (struct ast_sip_authenticator *auth)
Register a SIP authenticator.
void ast_sip_register_endpoint_formatter (struct ast_sip_endpoint_formatter *obj)
Register an endpoint formatter.
int ast_sip_register_endpoint_identifier (struct ast_sip_endpoint_identifier *identifier)
Register a SIP endpoint identifier.
int ast_sip_register_endpoint_identifier_with_name (struct ast_sip_endpoint_identifier *identifier, const char *name)
Register a SIP endpoint identifier with a name.
int ast_sip_register_outbound_authenticator (struct ast_sip_outbound_authenticator *auth)
Register an outbound SIP authenticator.
int ast_sip_register_service (pjsip_module *module)
Register a SIP service in Asterisk.
void ast_sip_register_supplement (struct ast_sip_supplement *supplement)
Register a supplement to SIP out of dialog processing.
int ast_sip_requires_authentication (struct ast_sip_endpoint *endpoint, pjsip_rx_data *rdata)
Determine if an incoming request requires authentication.
int ast_sip_send_out_of_dialog_request (pjsip_tx_data *tdata, struct ast_sip_endpoint *endpoint, int timeout, void *token, void(*callback)(void *token, pjsip_event *e))
General purpose method for sending an Out-Of-Dialog SIP request.
int ast_sip_send_request (pjsip_tx_data *tdata, struct pjsip_dialog *dlg, struct ast_sip_endpoint *endpoint, void *token, void(*callback)(void *token, pjsip_event *e))
General purpose method for sending a SIP request.
int ast_sip_send_response (pjsip_response_addr *res_addr, pjsip_tx_data *tdata, struct ast_sip_endpoint *sip_endpoint)
Send a response to an out of dialog request.
int ast_sip_send_stateful_response (pjsip_rx_data *rdata, pjsip_tx_data *tdata, struct ast_sip_endpoint *sip_endpoint)
Send a stateful response to an out of dialog request.
int ast_sip_set_outbound_proxy (pjsip_tx_data *tdata, const char *proxy)
Set the outbound proxy for an outbound SIP message.
int ast_sip_set_tpselector_from_ep_or_uri (const struct ast_sip_endpoint *endpoint, pjsip_sip_uri *sip_uri, pjsip_tpselector *selector)
Sets pjsip_tpselector from an endpoint or uri.
int ast_sip_set_tpselector_from_transport (const struct ast_sip_transport *transport, pjsip_tpselector *selector)
Sets pjsip_tpselector from ast_sip_transport.
int ast_sip_set_tpselector_from_transport_name (const char *transport_name, pjsip_tpselector *selector)
Sets pjsip_tpselector from ast_sip_transport.
int ast_sip_str_to_dtmf (const char *dtmf_mode)
Convert the DTMF mode name into an enum.
int ast_sip_thread_is_servant (void)
Determine if the current thread is a SIP servant thread.
struct ast_threadpool * ast_sip_threadpool (void)
Retrieve the SIP threadpool object.
long ast_sip_threadpool_queue_size (void)
Return the size of the SIP threadpool's task queue.
void ast_sip_tpselector_unref (pjsip_tpselector *selector)
Unreference a pjsip_tpselector.
void ast_sip_unregister_authenticator (struct ast_sip_authenticator *auth)
Unregister a SIP authenticator.
void ast_sip_unregister_endpoint_formatter (struct ast_sip_endpoint_formatter *obj)
Unregister an endpoint formatter.
void ast_sip_unregister_endpoint_identifier (struct ast_sip_endpoint_identifier *identifier)
Unregister a SIP endpoint identifier.
void ast_sip_unregister_outbound_authenticator (struct ast_sip_outbound_authenticator *auth)
Unregister an outbound SIP authenticator.
void ast_sip_unregister_service (pjsip_module *module)
void ast_sip_unregister_supplement (struct ast_sip_supplement *supplement)
Unregister a an supplement to SIP out of dialog processing.
int ast_sip_will_uri_survive_restart (pjsip_sip_uri *uri, struct ast_sip_endpoint *endpoint, pjsip_rx_data *rdata)
AST_TEST_DEFINE (xml_sanitization_end_null)
AST_TEST_DEFINE (xml_sanitization_exceeds_buffer)
static int check_request_status (struct send_request_data *req_data, pjsip_event *e)
static char * cli_dump_endpt (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static char * cli_show_endpoint_identifiers (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static char * cli_show_settings (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static pjsip_dialog * create_dialog_uas (const struct ast_sip_endpoint *endpoint, pjsip_rx_data *rdata, pj_status_t *status, create_dlg_uac create_fun)
static int create_in_dialog_request (const pjsip_method *method, struct pjsip_dialog *dlg, pjsip_tx_data **tdata)
static int create_out_of_dialog_request (const pjsip_method *method, struct ast_sip_endpoint *endpoint, const char *uri, struct ast_sip_contact *provided_contact, pjsip_tx_data **tdata)
static int do_cli_dump_endpt (void *v_a)
static pj_bool_t does_method_match (const pj_str_t *message_method, const char *supplement_method)
static pj_status_t endpt_send_request (struct ast_sip_endpoint *endpoint, pjsip_tx_data *tdata, pj_int32_t timeout, void *token, pjsip_endpt_send_callback cb)
static void endpt_send_request_cb (void *token, pjsip_event *e)
static const pjsip_method * get_pjsip_method (const char *method)
static int load_module (void)
static int load_pjsip (void)
static void * monitor_thread_exec (void *endpt)
void never_called_res_pjsip (void)
static int register_service (void *data)
static int reload_configuration_task (void *obj)
static int reload_module (void)
static void remove_request_headers (pjsip_endpoint *endpt)
static int send_in_dialog_request (pjsip_tx_data *tdata, struct pjsip_dialog *dlg)
static void send_request_cb (void *token, pjsip_event *e)
static struct send_request_data * send_request_data_alloc (struct ast_sip_endpoint *endpoint, void *token, void(*callback)(void *token, pjsip_event *e))
static void send_request_data_destroy (void *obj)
static void send_request_timer_callback (pj_timer_heap_t *theap, pj_timer_entry *entry)
static void send_request_wrapper_destructor (void *obj)
static int sip_dialog_create_from (pj_pool_t *pool, pj_str_t *from, const char *user, const char *domain, const pj_str_t *target, pjsip_tpselector *selector)
static void sip_thread_start (void)
static void stop_monitor_thread (void)
static pj_bool_t supplement_on_rx_request (pjsip_rx_data *rdata)
static void supplement_outgoing_response (pjsip_tx_data *tdata, struct ast_sip_endpoint *sip_endpoint)
static int sync_task (void *data)
static int uas_use_sips_contact (pjsip_rx_data *rdata)
Determine if a SIPS Contact header is required.
static int unload_module (void)
static int unload_pjsip (void *data)
static int unregister_service (void *data)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_GLOBAL_SYMBOLS | AST_MODFLAG_LOAD_ORDER , .description = "Basic SIP resource" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .reload = reload_module, .load_pri = AST_MODPRI_CHANNEL_DEPEND - 5, .requires = "dnsmgr,res_pjproject,res_sorcery_config,res_sorcery_memory,res_sorcery_astdb", .optional_modules = "res_statsd", }
static const struct ast_module_info * ast_module_info = &__mod_info
static pjsip_endpoint * ast_pjsip_endpoint
pj_caching_pool caching_pool
static struct ast_cli_entry cli_commands []
struct endpoint_formatters endpoint_formatters = { .first = NULL, .last = NULL, .lock = { PTHREAD_RWLOCK_INITIALIZER , NULL, {1, 0} } , }
static struct endpoint_identifiers endpoint_identifiers = { .first = NULL, .last = NULL, .lock = { PTHREAD_RWLOCK_INITIALIZER , NULL, {1, 0} } , }
static pj_sockaddr host_ip_ipv4
static char host_ip_ipv4_string [PJ_INET6_ADDRSTRLEN]
static pj_sockaddr host_ip_ipv6
static char host_ip_ipv6_string [PJ_INET6_ADDRSTRLEN]
static const pjsip_method info_method = {PJSIP_OTHER_METHOD, {"INFO", 4} }
pj_pool_t * memory_pool
static const pjsip_method message_method = {PJSIP_OTHER_METHOD, {"MESSAGE", 7} }
struct {
const char * method
const pjsip_method * pmethod
} methods []
static int monitor_continue
pj_thread_t * monitor_thread
static struct ast_threadstorage pj_thread_storage = { .once = PTHREAD_ONCE_INIT , .key_init = __init_pj_thread_storage , .custom_init = NULL , }
static struct ast_sip_authenticator * registered_authenticator
static struct ast_sip_outbound_authenticator * registered_outbound_authenticator
static struct ast_threadstorage servant_id_storage = { .once = PTHREAD_ONCE_INIT , .key_init = __init_servant_id_storage , .custom_init = NULL , }
static struct ast_serializer_pool * sip_serializer_pool
static struct ast_threadpool * sip_threadpool
static pjsip_module supplement_module
struct supplements supplements = { .first = NULL, .last = NULL, .lock = { PTHREAD_RWLOCK_INITIALIZER , NULL, {1, 0} } , }
Macro Definition Documentation
ENDPOINT_IDENTIFIER_FORMAT
#define ENDPOINT_IDENTIFIER_FORMAT "%-20.20s\n"
Referenced by cli_show_endpoint_identifiers().
MOD_DATA_CONTACT
#define MOD_DATA_CONTACT "contact"
Definition at line 3264 of file res_pjsip.c.
Referenced by ast_sip_create_response(), ast_sip_send_out_of_dialog_request(), ast_sip_send_stateful_response(), create_out_of_dialog_request(), and supplement_outgoing_response().
SERIALIZER_POOL_SIZE
#define SERIALIZER_POOL_SIZE 8
Number of serializers in pool if one not supplied.
Definition at line 3267 of file res_pjsip.c.
Referenced by load_module().
SIP_SERVANT_ID
#define SIP_SERVANT_ID 0x5E2F1D
Definition at line 5294 of file res_pjsip.c.
Referenced by ast_sip_thread_is_servant(), and sip_thread_start().
TIMEOUT_TIMER2
#define TIMEOUT_TIMER2 5
Definition at line 4568 of file res_pjsip.c.
Referenced by endpt_send_request(), endpt_send_request_cb(), and send_request_timer_callback().
TIMER_INACTIVE
#define TIMER_INACTIVE 0
Definition at line 4567 of file res_pjsip.c.
Referenced by endpt_send_request(), endpt_send_request_cb(), and send_request_timer_callback().
Typedef Documentation
create_dlg_uac
typedef pj_status_t(* create_dlg_uac) (pjsip_user_agent *ua, pjsip_rx_data *rdata, const pj_str_t *contact, pjsip_dialog **p_dlg)
Definition at line 4174 of file res_pjsip.c.
Function Documentation
__init_pj_thread_storage()
static void __init_pj_thread_storage (void) static
Definition at line 5292 of file res_pjsip.c.
 {
__init_servant_id_storage()
static void __init_servant_id_storage (void) static
Definition at line 5293 of file res_pjsip.c.
 {
__reg_module()
static void __reg_module (void) static
Definition at line 5962 of file res_pjsip.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 5962 of file res_pjsip.c.
ast_body_to_pjsip_body()
static pjsip_msg_body* ast_body_to_pjsip_body (pj_pool_t * pool, const struct ast_sip_body * body) static
Definition at line 5078 of file res_pjsip.c.
References ast_sip_body::body_text, ast_sip_body::subtype, type, and ast_sip_body::type.
Referenced by ast_sip_add_body(), and ast_sip_add_body_multipart().
 {
    pj_str_t type;
    pj_str_t subtype;
    pj_str_t body_text;
    pj_cstr(&type, body->type);
    pj_cstr(&subtype, body->subtype);
    pj_cstr(&body_text, body->body_text);
    return pjsip_msg_body_create(pool, &type, &subtype, &body_text);
 }
ast_copy_pj_str()
void ast_copy_pj_str (char * dest, const pj_str_t * src, size_t size)
Copy a pj_str_t into a standard character buffer.
pj_str_t is not NULL-terminated. Any place that expects a NULL- terminated string needs to have the pj_str_t copied into a separate buffer.
This method copies the pj_str_t contents into the destination buffer and NULL-terminates the buffer.
Parameters
dest The destination buffer
src The pj_str_t to copy
size The size of the destination buffer.
Definition at line 5240 of file res_pjsip.c.
References MIN.
Referenced by add_identity_header(), apply_dtls_attrib(), apply_negotiated_sdp_stream(), assign_uuid(), ast_sip_get_transport_name(), ast_sip_report_auth_challenge_sent(), ast_sip_report_auth_failed_challenge_response(), chan_pjsip_get_uniqueid(), change_outgoing_sdp_stream_media_address(), channel_read_pjsip(), cli_complete_subscription_common(), cli_list_subscriptions_detail(), cli_show_subscriptions_detail(), determine_sip_publish_type(), dialog_info_generate_body_content(), endpoint_lookup(), evaluate_like(), extract_contact_addr(), find_aor(), find_aor_name(), find_challenge(), get_auth_header(), get_codecs(), get_destination(), get_endpoint_details(), get_from_header(), get_mid_bundle_group(), get_user_agent(), handle_incoming_sdp(), handle_negotiated_sdp_session_media(), handle_registration_response(), headers_to_vars(), incoming_in_dialog_request(), log_failed_request(), negotiate_incoming_sdp_stream(), options_on_rx_request(), parse_uri_cb(), process_extmap_attributes(), process_ice_attributes(), process_ice_auth_attrb(), process_ssrc_attributes(), publish_request_initial(), pubsub_on_rx_publish_request(), pubsub_on_rx_subscribe_request(), refer_blind_callback(), refer_incoming_blind_request(), refer_incoming_refer_request(), register_aor_core(), rfc3326_use_reason_header(), rx_data_to_ast_msg(), save_response_fields_to_transport(), sdp_requires_deferral(), security_event_populate(), session_inv_on_redirected(), session_outgoing_nat_hook(), set_id_from_hdr(), set_id_from_oli(), set_mid_and_bundle_group(), set_redirecting_value(), set_remote_mslabel_and_stream_group(), set_sipdomain_variable(), sip_resolve(), sip_subscription_to_ami(), sub_persistence_recreate(), subscription_get_generator_from_rdata(), subscription_get_handler_from_rdata(), subscription_persistence_create(), subscription_persistence_update(), and transfer_refer().
 {
    size_t chars_to_copy = MIN(size - 1, pj_strlen(src));
    memcpy(dest, pj_strbuf(src), chars_to_copy);
    dest[chars_to_copy] = '\0';
 }
ast_copy_pj_str2()
int ast_copy_pj_str2 (char ** dest, const pj_str_t * src)
Create and copy a pj_str_t into a standard character buffer.
pj_str_t is not NULL-terminated. Any place that expects a NULL- terminated string needs to have the pj_str_t copied into a separate buffer.
Copies the pj_str_t contents into a newly allocated buffer pointed to by dest. NULL-terminates the buffer.
Note
Caller is responsible for freeing the allocated memory.
Parameters
dest [out] The destination buffer
src The pj_str_t to copy
Return values
Number of characters copied or negative value on error
Definition at line 5247 of file res_pjsip.c.
References ast_asprintf, and NULL.
 {
    int res = ast_asprintf(dest, "%.*s", (int)pj_strlen(src), pj_strbuf(src));
    if (res < 0) {
       *dest = NULL;
    }
    return res;
 }
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 5962 of file res_pjsip.c.
ast_sip_add_body()
int ast_sip_add_body (pjsip_tx_data * tdata, const struct ast_sip_body * body)
Add a body to an outbound SIP message.
If this is called multiple times, the latest body will replace the current body.
Parameters
tdata The message to add the body to
body The message body to add
Return values
0 Success
-1 Failure
Definition at line 5091 of file res_pjsip.c.
References ast_body_to_pjsip_body().
Referenced by build_notify_body(), msg_send(), send_unsolicited_mwi_notify_to_contact(), sendtext(), sip_publisher_service_queue(), transmit_info_dtmf(), and transmit_info_with_vidupdate().
 {
    pjsip_msg_body *pjsip_body = ast_body_to_pjsip_body(tdata->pool, body);
    tdata->msg->body = pjsip_body;
    return 0;
 }
ast_sip_add_body_multipart()
int ast_sip_add_body_multipart (pjsip_tx_data * tdata, const struct ast_sip_body * bodies[], int num_bodies)
Add a multipart body to an outbound SIP message.
This will treat each part of the input vector as part of a multipart body and add each part to the SIP message.
Parameters
tdata The message to add the body to
bodies The parts of the body to add
Return values
0 Success
-1 Failure
Definition at line 5098 of file res_pjsip.c.
References ast_body_to_pjsip_body(), and NULL.
 {
    int i;
    /* NULL for type and subtype automatically creates "multipart/mixed" */
    pjsip_msg_body *body = pjsip_multipart_create(tdata->pool, NULL, NULL);
    for (i = 0; i < num_bodies; ++i) {
       pjsip_multipart_part *part = pjsip_multipart_create_part(tdata->pool);
       part->body = ast_body_to_pjsip_body(tdata->pool, bodies[i]);
       pjsip_multipart_add_part(tdata->pool, body, part);
    }
    tdata->msg->body = body;
    return 0;
 }
ast_sip_add_date_header()
void ast_sip_add_date_header (pjsip_tx_data * tdata)
Adds a Date header to the tdata, formatted like: Date: Wed, 01 Jan 2021 14:53:01 GMT.
Since
16.19.0
Note
There is no checking done to see if the header already exists before adding it. It's up to the caller of this function to determine if that needs to be done or not.
Definition at line 3288 of file res_pjsip.c.
References ast_sip_add_header(), and NULL.
Referenced by add_date_header(), and register_aor_core().
 {
    char date[256];
    struct tm tm;
    time_t t = time(NULL);
    gmtime_r(&t, &tm);
    strftime(date, sizeof(date), "%a, %d %b %Y %T GMT", &tm);
    ast_sip_add_header(tdata, "Date", date);
 }
ast_sip_add_header()
int ast_sip_add_header (pjsip_tx_data * tdata, const char * name, const char * value)
Add a header to an outbound SIP message.
Parameters
tdata The message to add the header to
name The header name
value The header value
Return values
0 Success
-1 Failure
Definition at line 5063 of file res_pjsip.c.
Referenced by add_header_from_channel_var(), add_headers_to_message(), ast_sip_add_date_header(), ast_sip_message_apply_transport(), build_notify(), notify_channel(), notify_contact(), notify_uri(), options_incoming_request(), rfc3326_add_reason_header(), send_options_response(), sip_publication_respond(), transfer_refer(), and vars_to_headers().
 {
    pj_str_t hdr_name;
    pj_str_t hdr_value;
    pjsip_generic_string_hdr *hdr;
    pj_cstr(&hdr_name, name);
    pj_cstr(&hdr_value, value);
    hdr = pjsip_generic_string_hdr_create(tdata->pool, &hdr_name, &hdr_value);
    pjsip_msg_add_hdr(tdata->msg, (pjsip_hdr *) hdr);
    return 0;
 }
ast_sip_add_usereqphone()
void ast_sip_add_usereqphone (const struct ast_sip_endpoint * endpoint, pj_pool_t * pool, pjsip_uri * uri)
Add 'user=phone' parameter to URI if enabled and user is a phone number.
Parameters
endpoint The endpoint to use for configuration
pool The memory pool to allocate the parameter from
uri The URI to check for user and to add parameter to
Definition at line 3994 of file res_pjsip.c.
References AST_DIGIT_ANY, and ast_sip_endpoint::usereqphone.
Referenced by ast_sip_create_dialog_uac(), create_out_of_dialog_request(), and set_from_header().
 {
    pjsip_sip_uri *sip_uri;
    int i = 0;
    static const pj_str_t STR_PHONE = { "phone", 5 };
    if (!endpoint || !endpoint->usereqphone || (!PJSIP_URI_SCHEME_IS_SIP(uri) && !PJSIP_URI_SCHEME_IS_SIPS(uri))) {
       return;
    }
    sip_uri = pjsip_uri_get_uri(uri);
    if (!pj_strlen(&sip_uri->user)) {
       return;
    }
    if (pj_strbuf(&sip_uri->user)[0] == '+') {
       i = 1;
    }
    /* Test URI user against allowed characters in AST_DIGIT_ANY */
    for (; i < pj_strlen(&sip_uri->user); i++) {
       if (!strchr(AST_DIGIT_ANY, pj_strbuf(&sip_uri->user)[i])) {
          break;
       }
    }
    if (i < pj_strlen(&sip_uri->user)) {
       return;
    }
    sip_uri->user_param = STR_PHONE;
 }
ast_sip_append_body()
int ast_sip_append_body (pjsip_tx_data * tdata, const char * body_text)
Append body data to a SIP message.
This acts mostly the same as ast_sip_add_body, except that rather than replacing a body if it currently exists, it appends data to an existing body.
Parameters
tdata The message to append the body to
body The string to append to the end of the current body
Return values
0 Success
-1 Failure
Definition at line 5114 of file res_pjsip.c.
References ast_str_alloca, ast_str_buffer(), and ast_str_set().
 {
    size_t combined_size = strlen(body_text) + tdata->msg->body->len;
    struct ast_str *body_buffer = ast_str_alloca(combined_size);
    ast_str_set(&body_buffer, 0, "%.*s%s", (int) tdata->msg->body->len, (char *) tdata->msg->body->data, body_text);
    tdata->msg->body->data = pj_pool_alloc(tdata->pool, combined_size);
    pj_memcpy(tdata->msg->body->data, ast_str_buffer(body_buffer), combined_size);
    tdata->msg->body->len = combined_size;
    return 0;
 }
ast_sip_call_codec_pref_to_str()
const char* ast_sip_call_codec_pref_to_str (struct ast_flags pref)
Convert the call codec preference flags to a string.
Since
18.0.0
Parameters
pref the call codec preference setting
Returns
a constant string with either the setting value or 'unknown'
Note
Don't try to free the string!
Definition at line 5534 of file res_pjsip.c.
References value.
Referenced by incoming_call_offer_pref_to_str(), log_caps(), and outgoing_call_offer_pref_to_str().
 {
    const char *value;
    if (ast_sip_call_codec_pref_test(pref, LOCAL) &&  ast_sip_call_codec_pref_test(pref, INTERSECT) && ast_sip_call_codec_pref_test(pref, ALL)) {
       value = "local";
    } else if (ast_sip_call_codec_pref_test(pref, LOCAL) &&  ast_sip_call_codec_pref_test(pref, UNION) && ast_sip_call_codec_pref_test(pref, ALL)) {
       value = "local_merge";
    } else if (ast_sip_call_codec_pref_test(pref, LOCAL) &&  ast_sip_call_codec_pref_test(pref, INTERSECT) && ast_sip_call_codec_pref_test(pref, FIRST)) {
       value = "local_first";
    } else if (ast_sip_call_codec_pref_test(pref, REMOTE) &&  ast_sip_call_codec_pref_test(pref, INTERSECT) && ast_sip_call_codec_pref_test(pref, ALL)) {
       value = "remote";
    } else if (ast_sip_call_codec_pref_test(pref, REMOTE) &&  ast_sip_call_codec_pref_test(pref, UNION) && ast_sip_call_codec_pref_test(pref, ALL)) {
       value = "remote_merge";
    } else if (ast_sip_call_codec_pref_test(pref, REMOTE) &&  ast_sip_call_codec_pref_test(pref, UNION) && ast_sip_call_codec_pref_test(pref, FIRST)) {
       value = "remote_first";
    } else {
       value = "unknown";
    }
    return value;
 }
ast_sip_call_codec_str_to_pref()
int ast_sip_call_codec_str_to_pref (struct ast_flags * pref, const char * pref_str, int is_outgoing)
Convert a call codec preference string to preference flags.
Since
18.0.0
Parameters
pref A pointer to an ast_flags structure to receive the preference flags
pref_str The call codec preference setting string
is_outgoing Is for outgoing calls?
Return values
0 The string was parsed successfully
-1 The string option was invalid
Definition at line 5557 of file res_pjsip.c.
References ast_set_flag, AST_SIP_CALL_CODEC_PREF_ALL, AST_SIP_CALL_CODEC_PREF_FIRST, AST_SIP_CALL_CODEC_PREF_INTERSECT, AST_SIP_CALL_CODEC_PREF_LOCAL, AST_SIP_CALL_CODEC_PREF_REMOTE, AST_SIP_CALL_CODEC_PREF_UNION, and ast_flags::flags.
Referenced by call_offer_pref_handler(), and test_create_joint().
 {
    pref->flags = 0;
    if (strcmp(pref_str, "local") == 0) {
       ast_set_flag(pref, AST_SIP_CALL_CODEC_PREF_LOCAL | AST_SIP_CALL_CODEC_PREF_INTERSECT | AST_SIP_CALL_CODEC_PREF_ALL);
    } else if (is_outgoing && strcmp(pref_str, "local_merge") == 0) {
       ast_set_flag(pref, AST_SIP_CALL_CODEC_PREF_LOCAL | AST_SIP_CALL_CODEC_PREF_UNION | AST_SIP_CALL_CODEC_PREF_ALL);
    } else if (strcmp(pref_str, "local_first") == 0) {
       ast_set_flag(pref, AST_SIP_CALL_CODEC_PREF_LOCAL | AST_SIP_CALL_CODEC_PREF_INTERSECT | AST_SIP_CALL_CODEC_PREF_FIRST);
    } else if (strcmp(pref_str, "remote") == 0) {
       ast_set_flag(pref, AST_SIP_CALL_CODEC_PREF_REMOTE | AST_SIP_CALL_CODEC_PREF_INTERSECT | AST_SIP_CALL_CODEC_PREF_ALL);
    } else if (is_outgoing && strcmp(pref_str, "remote_merge") == 0) {
       ast_set_flag(pref, AST_SIP_CALL_CODEC_PREF_REMOTE | AST_SIP_CALL_CODEC_PREF_UNION | AST_SIP_CALL_CODEC_PREF_ALL);
    } else if (strcmp(pref_str, "remote_first") == 0) {
       ast_set_flag(pref, AST_SIP_CALL_CODEC_PREF_REMOTE | AST_SIP_CALL_CODEC_PREF_UNION | AST_SIP_CALL_CODEC_PREF_FIRST);
    } else {
       return -1;
    }
    return 0;
 }
ast_sip_check_authentication()
enum ast_sip_check_auth_result ast_sip_check_authentication (struct ast_sip_endpoint * endpoint, pjsip_rx_data * rdata, pjsip_tx_data * tdata)
Method to determine authentication status of an incoming request.
This will call into a registered authenticator. The registered authenticator will do what is necessary to determine whether the incoming request passes authentication. A tentative response is passed into this function so that if, say, a digest authentication challenge should be sent in the ensuing response, it can be added to the response.
Parameters
endpoint The endpoint from the request was sent
rdata The request to potentially authenticate
tdata Tentative response to the request
Returns
The result of checking authentication.
Definition at line 3377 of file res_pjsip.c.
References ast_log, AST_SIP_AUTHENTICATION_SUCCESS, ast_sip_authenticator::check_authentication, and LOG_WARNING.
Referenced by authenticate().
 {
    if (!registered_authenticator) {
       ast_log(LOG_WARNING, "No SIP authenticator registered. Assuming authentication is successful\n");
       return AST_SIP_AUTHENTICATION_SUCCESS;
    }
    return registered_authenticator->check_authentication(endpoint, rdata, tdata);
 }
ast_sip_create_dialog_uac()
pjsip_dialog* ast_sip_create_dialog_uac (const struct ast_sip_endpoint * endpoint, const char * aor_name, const char * request_user)
General purpose method for creating a UAC dialog with an endpoint.
Parameters
endpoint A pointer to the endpoint
aor_name Optional name of the AOR to target, may even be an explicit SIP URI
request_user Optional user to place into the target URI
Return values
non-NULL success
NULL failure
Definition at line 4028 of file res_pjsip.c.
References ast_log, ast_sip_add_usereqphone(), ast_sip_dlg_set_transport(), ast_sip_tpselector_unref(), ast_sorcery_object_get_id(), ast_strlen_zero, ast_sip_endpoint::contact_user, ast_sip_endpoint::fromdomain, ast_sip_endpoint::fromuser, ast_sip_endpoint::info, LOG_ERROR, NULL, ast_sip_endpoint::outbound_proxy, sip_dialog_create_from(), and tmp().
Referenced by ast_sip_create_subscription(), and ast_sip_session_create_outgoing().
 {
    char enclosed_uri[PJSIP_MAX_URL_SIZE];
    pj_str_t local_uri = { "sip:temp@temp", 13 }, remote_uri, target_uri;
    pj_status_t res;
    pjsip_dialog *dlg = NULL;
    const char *outbound_proxy = endpoint->outbound_proxy;
    pjsip_tpselector selector = { .type = PJSIP_TPSELECTOR_NONE, };
    static const pj_str_t HCONTACT = { "Contact", 7 };
    snprintf(enclosed_uri, sizeof(enclosed_uri), "<%s>", uri);
    pj_cstr(&remote_uri, enclosed_uri);
    pj_cstr(&target_uri, uri);
    res = pjsip_dlg_create_uac(pjsip_ua_instance(), &local_uri, NULL, &remote_uri, &target_uri, &dlg);
    if (res == PJ_SUCCESS && !(PJSIP_URI_SCHEME_IS_SIP(dlg->target) || PJSIP_URI_SCHEME_IS_SIPS(dlg->target))) {
       /* dlg->target is a pjsip_other_uri, but it's assumed to be a
        * pjsip_sip_uri below. Fail fast. */
       res = PJSIP_EINVALIDURI;
       pjsip_dlg_terminate(dlg);
    }
    if (res != PJ_SUCCESS) {
       if (res == PJSIP_EINVALIDURI) {
          ast_log(LOG_ERROR,
             "Endpoint '%s': Could not create dialog to invalid URI '%s'.  Is endpoint registered and reachable?\n",
             ast_sorcery_object_get_id(endpoint), uri);
       }
       return NULL;
    }
    /* We have to temporarily bump up the sess_count here so the dialog is not prematurely destroyed */
    dlg->sess_count++;
    ast_sip_dlg_set_transport(endpoint, dlg, &selector);
    if (sip_dialog_create_from(dlg->pool, &local_uri, endpoint->fromuser, endpoint->fromdomain, &remote_uri, &selector)) {
       dlg->sess_count--;
       pjsip_dlg_terminate(dlg);
       ast_sip_tpselector_unref(&selector);
       return NULL;
    }
    ast_sip_tpselector_unref(&selector);
    /* Update the dialog with the new local URI, we do it afterwards so we can use the dialog pool for construction */
    pj_strdup_with_null(dlg->pool, &dlg->local.info_str, &local_uri);
    dlg->local.info->uri = pjsip_parse_uri(dlg->pool, dlg->local.info_str.ptr, dlg->local.info_str.slen, 0);
    if (!dlg->local.info->uri) {
       ast_log(LOG_ERROR,
          "Could not parse URI '%s' for endpoint '%s'\n",
          dlg->local.info_str.ptr, ast_sorcery_object_get_id(endpoint));
       dlg->sess_count--;
       pjsip_dlg_terminate(dlg);
       return NULL;
    }
    dlg->local.contact = pjsip_parse_hdr(dlg->pool, &HCONTACT, local_uri.ptr, local_uri.slen, NULL);
    if (!ast_strlen_zero(endpoint->contact_user)) {
       pjsip_sip_uri *sip_uri;
       sip_uri = pjsip_uri_get_uri(dlg->local.contact->uri);
       pj_strdup2(dlg->pool, &sip_uri->user, endpoint->contact_user);
    }
    /* If a request user has been specified and we are permitted to change it, do so */
    if (!ast_strlen_zero(request_user)) {
       pjsip_sip_uri *sip_uri;
       if (PJSIP_URI_SCHEME_IS_SIP(dlg->target) || PJSIP_URI_SCHEME_IS_SIPS(dlg->target)) {
          sip_uri = pjsip_uri_get_uri(dlg->target);
          pj_strdup2(dlg->pool, &sip_uri->user, request_user);
       }
       if (PJSIP_URI_SCHEME_IS_SIP(dlg->remote.info->uri) || PJSIP_URI_SCHEME_IS_SIPS(dlg->remote.info->uri)) {
          sip_uri = pjsip_uri_get_uri(dlg->remote.info->uri);
          pj_strdup2(dlg->pool, &sip_uri->user, request_user);
       }
    }
    /* Add the user=phone parameter if applicable */
    ast_sip_add_usereqphone(endpoint, dlg->pool, dlg->target);
    ast_sip_add_usereqphone(endpoint, dlg->pool, dlg->remote.info->uri);
    if (!ast_strlen_zero(outbound_proxy)) {
       pjsip_route_hdr route_set, *route;
       static const pj_str_t ROUTE_HNAME = { "Route", 5 };
       pj_str_t tmp;
       pj_list_init(&route_set);
       pj_strdup2_with_null(dlg->pool, &tmp, outbound_proxy);
       if (!(route = pjsip_parse_hdr(dlg->pool, &ROUTE_HNAME, tmp.ptr, tmp.slen, NULL))) {
          ast_log(LOG_ERROR, "Could not create dialog to endpoint '%s' as outbound proxy URI '%s' is not valid\n",
             ast_sorcery_object_get_id(endpoint), outbound_proxy);
          dlg->sess_count--;
          pjsip_dlg_terminate(dlg);
          return NULL;
       }
       pj_list_insert_nodes_before(&route_set, route);
       pjsip_dlg_set_route_set(dlg, &route_set);
    }
    dlg->sess_count--;
    return dlg;
 }
ast_sip_create_dialog_uas()
pjsip_dialog* ast_sip_create_dialog_uas (const struct ast_sip_endpoint * endpoint, pjsip_rx_data * rdata, pj_status_t * status)
General purpose method for creating a UAS dialog with an endpoint.
Deprecated:
This function is unsafe (due to the returned object not being locked nor having its reference incremented) and should no longer be used. Instead use ast_sip_create_dialog_uas_locked so a properly locked and referenced object is returned.
Parameters
endpoint A pointer to the endpoint
rdata The request that is starting the dialog
[out] status On failure, the reason for failure in creating the dialog
Definition at line 4233 of file res_pjsip.c.
References create_dialog_uas().
 {
 #ifdef HAVE_PJSIP_DLG_CREATE_UAS_AND_INC_LOCK
    pjsip_dialog *dlg;
    dlg = create_dialog_uas(endpoint, rdata, status, pjsip_dlg_create_uas_and_inc_lock);
    if (dlg) {
       pjsip_dlg_dec_lock(dlg);
    }
    return dlg;
 #else
    return create_dialog_uas(endpoint, rdata, status, pjsip_dlg_create_uas);
 #endif
 }
ast_sip_create_dialog_uas_locked()
pjsip_dialog* ast_sip_create_dialog_uas_locked (const struct ast_sip_endpoint * endpoint, pjsip_rx_data * rdata, pj_status_t * status)
General purpose method for creating a UAS dialog with an endpoint.
This function creates and returns a locked, and referenced counted pjsip dialog object. The caller is thus responsible for freeing the allocated memory, decrementing the reference, and releasing the lock when done with the returned object.
Note
The safest way to unlock the object, and decrement its reference is by calling pjsip_dlg_dec_lock. Alternatively, pjsip_dlg_dec_session can be used to decrement the reference only.
The dialog is returned locked and with a reference in order to ensure that the dialog object, and any of its associated objects (e.g. transaction) are not untimely destroyed. For instance, that could happen when a transport error occurs.
As long as the caller maintains a reference to the dialog there should be no worry that it might unknowningly be destroyed. However, once the caller unlocks the dialog there is a danger that some of the dialog's internal objects could be lost and/or compromised. For example, when the aforementioned transport error occurs the dialog's associated transaction gets destroyed (see pjsip_dlg_on_tsx_state in sip_dialog.c, and mod_inv_on_tsx_state in sip_inv.c).
In this case and before using the dialog again the caller should re-lock the dialog, check to make sure the dialog is still established, and the transaction still exists and has not been destroyed.
Parameters
endpoint A pointer to the endpoint
rdata The request that is starting the dialog
[out] status On failure, the reason for failure in creating the dialog
Return values
A locked, and reference counted pjsip_dialog object.
NULL on failure
Definition at line 4249 of file res_pjsip.c.
References create_dialog_uas().
Referenced by create_subscription_tree(), and pre_session_setup().
 {
 #ifdef HAVE_PJSIP_DLG_CREATE_UAS_AND_INC_LOCK
    return create_dialog_uas(endpoint, rdata, status, pjsip_dlg_create_uas_and_inc_lock);
 #else
    /*
     * This is put here in order to be compatible with older versions of pjproject.
     * Best we can do in this case is immediately lock after getting the dialog.
     * However, that does leave a "gap" between creating and locking.
     */
    pjsip_dialog *dlg;
    dlg = create_dialog_uas(endpoint, rdata, status, pjsip_dlg_create_uas);
    if (dlg) {
       pjsip_dlg_inc_lock(dlg);
    }
    return dlg;
 #endif
  }
ast_sip_create_rdata()
int ast_sip_create_rdata (pjsip_rx_data * rdata, char * packet, const char * src_name, int src_port, char * transport_type, const char * local_name, int local_port)
General purpose method for creating an rdata structure using specific information.
Parameters
rdata[out] The rdata structure that will be populated
packet A SIP message
src_name The source IP address of the message
src_port The source port of the message
transport_type The type of transport the message was received on
local_name The local IP address the message was received on
local_port The local port the message was received on
Return values
0 success
-1 failure
Definition at line 4323 of file res_pjsip.c.
References ast_sip_create_rdata_with_contact(), and NULL.
 {
    return ast_sip_create_rdata_with_contact(rdata, packet, src_name, src_port, transport_type,
       local_name, local_port, NULL);
 }
ast_sip_create_rdata_with_contact()
int ast_sip_create_rdata_with_contact (pjsip_rx_data * rdata, char * packet, const char * src_name, int src_port, char * transport_type, const char * local_name, int local_port, const char * contact_uri)
General purpose method for creating an rdata structure using specific information.
Since
13.15.0
Parameters
rdata[out] The rdata structure that will be populated
packet A SIP message
src_name The source IP address of the message
src_port The source port of the message
transport_type The type of transport the message was received on
local_name The local IP address the message was received on
local_port The local port the message was received on
contact_uri The contact URI of the message
Return values
0 success
-1 failure
Definition at line 4271 of file res_pjsip.c.
References ast_copy_string(), ast_log, ast_strlen_zero, LOG_WARNING, NULL, and tmp().
Referenced by ast_sip_create_rdata(), and subscription_persistence_recreate().
 {
    pj_str_t tmp;
    /*
     * Initialize the error list in case there is a parse error
     * in the given packet.
     */
    pj_list_init(&rdata->msg_info.parse_err);
    rdata->tp_info.transport = PJ_POOL_ZALLOC_T(rdata->tp_info.pool, pjsip_transport);
    if (!rdata->tp_info.transport) {
       return -1;
    }
    ast_copy_string(rdata->pkt_info.packet, packet, sizeof(rdata->pkt_info.packet));
    ast_copy_string(rdata->pkt_info.src_name, src_name, sizeof(rdata->pkt_info.src_name));
    rdata->pkt_info.src_port = src_port;
    pj_sockaddr_parse(pj_AF_UNSPEC(), 0, pj_cstr(&tmp, src_name), &rdata->pkt_info.src_addr);
    pj_sockaddr_set_port(&rdata->pkt_info.src_addr, src_port);
    pjsip_parse_rdata(packet, strlen(packet), rdata);
    if (!rdata->msg_info.msg || !pj_list_empty(&rdata->msg_info.parse_err)) {
       return -1;
    }
    if (!ast_strlen_zero(contact)) {
       pjsip_contact_hdr *contact_hdr;
       contact_hdr = pjsip_msg_find_hdr(rdata->msg_info.msg, PJSIP_H_CONTACT, NULL);
       if (contact_hdr) {
          contact_hdr->uri = pjsip_parse_uri(rdata->tp_info.pool, (char *)contact,
             strlen(contact), PJSIP_PARSE_URI_AS_NAMEADDR);
          if (!contact_hdr->uri) {
             ast_log(LOG_WARNING, "Unable to parse contact URI from '%s'.\n", contact);
             return -1;
          }
       }
    }
    pj_strdup2(rdata->tp_info.pool, &rdata->msg_info.via->recvd_param, rdata->pkt_info.src_name);
    rdata->msg_info.via->rport_param = -1;
    rdata->tp_info.transport->key.type = pjsip_transport_get_type_from_name(pj_cstr(&tmp, transport_type));
    rdata->tp_info.transport->type_name = transport_type;
    pj_strdup2(rdata->tp_info.pool, &rdata->tp_info.transport->local_name.host, local_name);
    rdata->tp_info.transport->local_name.port = local_port;
    return 0;
 }
ast_sip_create_request()
int ast_sip_create_request (const char * method, struct pjsip_dialog * dlg, struct ast_sip_endpoint * endpoint, const char * uri, struct ast_sip_contact * contact, pjsip_tx_data ** tdata)
General purpose method for creating a SIP request.
Its typical use would be to create one-off requests such as an out of dialog SIP MESSAGE.
The request can either be in- or out-of-dialog. If in-dialog, the dlg parameter MUST be present. If out-of-dialog the endpoint parameter MUST be present. If both are present, then we will assume that the message is to be sent in-dialog.
The uri parameter can be specified if the request should be sent to an explicit URI rather than one configured on the endpoint.
Parameters
method The method of the SIP request to send
dlg Optional. If specified, the dialog on which to request the message.
endpoint Optional. If specified, the request will be created out-of-dialog to the endpoint.
uri Optional. If specified, the request will be sent to this URI rather than one configured for the endpoint.
contact The contact with which this request is associated for out-of-dialog requests.
[out] tdata The newly-created request
The provided contact is attached to tdata with its reference bumped, but will not survive for the entire lifetime of tdata since the contact is cleaned up when all supplements have completed execution.
Return values
0 Success
-1 Failure
Definition at line 4490 of file res_pjsip.c.
References ast_assert, ast_log, create_in_dialog_request(), create_out_of_dialog_request(), get_pjsip_method(), LOG_WARNING, NULL, and pmethod.
Referenced by msg_send(), notify_channel(), notify_contact(), notify_uri(), send_unsolicited_mwi_notify_to_contact(), sendtext(), sip_options_qualify_contact(), transmit_info_dtmf(), and transmit_info_with_vidupdate().
 {
    const pjsip_method *pmethod = get_pjsip_method(method);
    if (!pmethod) {
       ast_log(LOG_WARNING, "Unknown method '%s'. Cannot send request\n", method);
       return -1;
    }
    if (dlg) {
       return create_in_dialog_request(pmethod, dlg, tdata);
    } else {
       ast_assert(endpoint != NULL);
       return create_out_of_dialog_request(pmethod, endpoint, uri, contact, tdata);
    }
 }
ast_sip_create_request_with_auth()
int ast_sip_create_request_with_auth (const struct ast_sip_auth_vector * auths, pjsip_rx_data * challenge, pjsip_tx_data * tdata, pjsip_tx_data ** new_request)
Create a response to an authentication challenge.
This will call into an outbound authenticator's create_request_with_auth callback to create a new request with authentication credentials. See the create_request_with_auth callback in the ast_sip_outbound_authenticator structure for details about the parameters and return values.
Definition at line 3412 of file res_pjsip.c.
References ast_log, ast_sip_outbound_authenticator::create_request_with_auth, and LOG_WARNING.
Referenced by check_request_status(), handle_registration_response(), outbound_invite_auth(), session_inv_on_tsx_state_changed(), and sip_outbound_publish_callback().
 {
    if (!registered_outbound_authenticator) {
       ast_log(LOG_WARNING, "No SIP outbound authenticator registered. Cannot respond to authentication challenge\n");
       return -1;
    }
    return registered_outbound_authenticator->create_request_with_auth(auths, challenge, old_request, new_request);
 }
ast_sip_create_response()
int ast_sip_create_response (const pjsip_rx_data * rdata, int st_code, struct ast_sip_contact * contact, pjsip_tx_data ** p_tdata)
General purpose method for creating a SIP response.
Its typical use would be to create responses for out of dialog requests.
Parameters
rdata The rdata from the incoming request.
st_code The response code to transmit.
contact The contact with which this request is associated.
[out] tdata The newly-created response
The provided contact is attached to tdata with its reference bumped, but will not survive for the entire lifetime of tdata since the contact is cleaned up when all supplements have completed execution.
Return values
0 Success
-1 Failure
Definition at line 5448 of file res_pjsip.c.
References ao2_bump, ast_sip_get_pjsip_endpoint(), ast_sip_mod_data_set, MOD_DATA_CONTACT, NULL, and supplement_module.
Referenced by register_aor_core(), send_options_response(), and send_response().
 {
    int res = pjsip_endpt_create_response(ast_sip_get_pjsip_endpoint(), rdata, st_code, NULL, tdata);
    if (!res) {
       ast_sip_mod_data_set((*tdata)->pool, (*tdata)->mod_data, supplement_module.id, MOD_DATA_CONTACT, ao2_bump(contact));
    }
    return res;
 }
ast_sip_dict_get()
void* ast_sip_dict_get (void * ht, const char * key)
Retrieves the value associated with the given key.
Parameters
ht the hash table/dictionary to search
key the key to find
Return values
the value associated with the key, NULL otherwise.
Definition at line 5338 of file res_pjsip.c.
References NULL.
 {
    unsigned int hval = 0;
    if (!ht) {
       return NULL;
    }
    return pj_hash_get(ht, key, PJ_HASH_KEY_STRING, &hval);
 }
ast_sip_dict_set()
void* ast_sip_dict_set (pj_pool_t * pool, void * ht, const char * key, void * val)
Set the value for the given key.
Note - if the hash table does not exist one is created first, the key/value pair is set, and the hash table returned.
Parameters
pool the pool to allocate memory in
ht the hash table/dictionary in which to store the key/value pair
key the key to associate a value with
val the value to associate with a key
Return values
the given, or newly created, hash table.
Definition at line 5349 of file res_pjsip.c.
 {
    if (!ht) {
       ht = pj_hash_create(pool, 11);
    }
    pj_hash_set(pool, ht, key, PJ_HASH_KEY_STRING, 0, val);
    return ht;
 }
ast_sip_dlg_set_transport()
int ast_sip_dlg_set_transport (const struct ast_sip_endpoint * endpoint, pjsip_dialog * dlg, pjsip_tpselector * selector)
Set the transport on a dialog.
Since
13.15.0
Parameters
endpoint
dlg
selector (optional)
Note
This API calls ast_sip_get_transport_name(endpoint, dlg->target) and if the result is non-NULL, calls pjsip_dlg_set_transport. If 'selector' is non-NULL, it is updated with the selector used.
It is the responsibility of the caller to unref the passed in selector if one is provided.
Definition at line 3791 of file res_pjsip.c.
References ast_sip_set_tpselector_from_ep_or_uri(), and ast_sip_tpselector_unref().
Referenced by ast_sip_create_dialog_uac().
 {
    pjsip_sip_uri *uri;
    pjsip_tpselector sel = { .type = PJSIP_TPSELECTOR_NONE, };
    uri = pjsip_uri_get_uri(dlg->target);
    if (!selector) {
       selector = &sel;
    }
    ast_sip_set_tpselector_from_ep_or_uri(endpoint, uri, selector);
    pjsip_dlg_set_transport(dlg, selector);
    if (selector == &sel) {
       ast_sip_tpselector_unref(&sel);
    }
    return 0;
 }
ast_sip_dtmf_to_str()
int ast_sip_dtmf_to_str (const enum ast_sip_dtmf_mode dtmf, char * buf, size_t buf_len)
Convert the DTMF mode enum value into a string.
Since
13.18.0
Parameters
dtmf the dtmf mode
buf Buffer to receive dtmf mode string
buf_len Buffer length
Return values
0 Success
-1 Failure
Definition at line 5484 of file res_pjsip.c.
References ast_copy_string(), AST_SIP_DTMF_AUTO, AST_SIP_DTMF_AUTO_INFO, AST_SIP_DTMF_INBAND, AST_SIP_DTMF_INFO, AST_SIP_DTMF_NONE, and AST_SIP_DTMF_RFC_4733.
Referenced by dtmf_to_str(), and pjsip_acf_dtmf_mode_read().
 {
    switch (dtmf) {
    case AST_SIP_DTMF_NONE:
       ast_copy_string(buf, "none", buf_len);
       break;
    case AST_SIP_DTMF_RFC_4733:
       ast_copy_string(buf, "rfc4733", buf_len);
       break;
    case AST_SIP_DTMF_INBAND:
       ast_copy_string(buf, "inband", buf_len);
       break;
    case AST_SIP_DTMF_INFO:
       ast_copy_string(buf, "info", buf_len);
       break;
    case AST_SIP_DTMF_AUTO:
       ast_copy_string(buf, "auto", buf_len);
       break;
    case AST_SIP_DTMF_AUTO_INFO:
       ast_copy_string(buf, "auto_info", buf_len);
       break;
    default:
       buf[0] = '\0';
       return -1;
    }
    return 0;
 }
ast_sip_failover_request()
int ast_sip_failover_request (pjsip_tx_data * tdata)
Set a request to use the next value in the list of resolved addresses.
Parameters
tdata the tx data from the original request
Return values
0 No more addresses to try
1 The request was successfully re-intialized
Definition at line 4871 of file res_pjsip.c.
References NULL, and send_request_cb().
Referenced by check_request_status(), and handle_registration_response().
 {
    pjsip_via_hdr *via;
    if (!tdata || !tdata->dest_info.addr.count
       || (tdata->dest_info.cur_addr == tdata->dest_info.addr.count - 1)) {
       /* No more addresses to try */
       return 0;
    }
    /* Try next address */
    ++tdata->dest_info.cur_addr;
    via = (pjsip_via_hdr*)pjsip_msg_find_hdr(tdata->msg, PJSIP_H_VIA, NULL);
    via->branch_param.slen = 0;
    pjsip_tx_data_invalidate_msg(tdata);
    return 1;
 }
ast_sip_format_endpoint_ami()
int ast_sip_format_endpoint_ami (struct ast_sip_endpoint * endpoint, struct ast_sip_ami * ami, int * count)
Formats the endpoint and sends over AMI.
Parameters
endpoint the endpoint to format and send
endpoint ami AMI variable container
count the number of formatters operated on
Return values
0 Success, otherwise non-zero on error
Definition at line 3699 of file res_pjsip.c.
References AST_RWLIST_RDLOCK, AST_RWLIST_TRAVERSE, AST_RWLIST_UNLOCK, ast_sip_endpoint_formatter::format_ami, lock, and SCOPED_LOCK.
Referenced by ami_show_endpoint().
 {
    int res = 0;
    struct ast_sip_endpoint_formatter *i;
    SCOPED_LOCK(lock, &endpoint_formatters, AST_RWLIST_RDLOCK, AST_RWLIST_UNLOCK);
    *count = 0;
    AST_RWLIST_TRAVERSE(&endpoint_formatters, i, next) {
       if (i->format_ami && ((res = i->format_ami(endpoint, ami)) < 0)) {
          return res;
       }
       if (!res) {
          (*count)++;
       }
    }
    return 0;
 }
ast_sip_get_host_ip()
int ast_sip_get_host_ip (int af, pj_sockaddr * addr)
Retrieve the local host address in IP form.
Parameters
af The address family to retrieve
addr A place to store the local host address
Return values
0 success
-1 failure
Since
13.6.0
Definition at line 5460 of file res_pjsip.c.
References ast_strlen_zero, host_ip_ipv4, host_ip_ipv4_string, host_ip_ipv6, and host_ip_ipv6_string.
 {
    if (af == pj_AF_INET() && !ast_strlen_zero(host_ip_ipv4_string)) {
       pj_sockaddr_copy_addr(addr, &host_ip_ipv4);
       return 0;
    } else if (af == pj_AF_INET6() && !ast_strlen_zero(host_ip_ipv6_string)) {
       pj_sockaddr_copy_addr(addr, &host_ip_ipv6);
       return 0;
    }
    return -1;
 }
ast_sip_get_host_ip_string()
const char* ast_sip_get_host_ip_string (int af)
Retrieve the local host address in string form.
Parameters
af The address family to retrieve
Return values
non-NULL success
NULL failure
Since
13.6.0
Note
An empty string may be returned if the address family is valid but no local address exists
Definition at line 5473 of file res_pjsip.c.
References host_ip_ipv4_string, host_ip_ipv6_string, and NULL.
Referenced by create_local_sdp(), create_outgoing_sdp_stream(), and multihomed_rewrite_sdp().
 {
    if (af == pj_AF_INET()) {
       return host_ip_ipv4_string;
    } else if (af == pj_AF_INET6()) {
       return host_ip_ipv6_string;
    }
    return NULL;
 }
ast_sip_get_pjsip_endpoint()
pjsip_endpoint* ast_sip_get_pjsip_endpoint (void)
Get a pointer to the PJSIP endpoint.
This is useful when modules have specific information they need to register with the PJSIP core.
Return values
NULL endpoint has not been created yet.
non-NULL PJSIP endpoint.
Definition at line 3718 of file res_pjsip.c.
References ast_pjsip_endpoint.
Referenced by acl_on_rx_msg(), ast_res_pjsip_cleanup_options_handling(), ast_res_pjsip_init_options_handling(), ast_sip_create_response(), ast_sip_destroy_transport_events(), ast_sip_initialize_transport_events(), ast_sip_pubsub_register_body_generator(), ast_sip_send_response(), ast_sip_session_defer_termination(), ast_sip_session_resume_reinvite(), authenticate(), cancel_publish_refresh(), cancel_registration(), channel_read_pjsip(), create_out_of_dialog_request(), digest_create_request_with_auth(), distribute(), distributor(), do_cli_dump_endpt(), endpoint_lookup(), endpt_send_request(), endpt_send_request_cb(), exten_state_data_alloc(), exten_state_data_destructor(), exten_state_publisher_cb(), filter_on_tx_message(), find_registrar_aor(), keepalive_transport_send_keepalive(), load_module(), logging_on_rx_msg(), logging_on_tx_msg(), notify_task(), on_rx_process_uris(), options_incoming_request(), parse_uri_cb(), pre_session_setup(), publish_request_initial(), pubsub_on_rx_mwi_notify_request(), pubsub_on_rx_publish_request(), pubsub_on_rx_subscribe_request(), register_aor(), register_aor_core(), registrar_on_rx_request(), reschedule_reinvite(), schedule_publish_refresh(), schedule_registration(), send_options_response(), session_reinvite_on_rx_request(), sip_check_transport(), sip_dialog_create_contact(), sip_dialog_create_from(), sip_outbound_publisher_init(), sip_outbound_registration_regc_alloc(), sip_publication_respond(), sip_replace_resolver(), sip_session_defer_termination_stop_timer(), subscription_persistence_load(), system_create_resolver_and_set_nameservers(), t38_change_state(), transport_apply(), and transport_create().
 {
    return ast_pjsip_endpoint;
 }
ast_sip_get_transport_name()
int ast_sip_get_transport_name (const struct ast_sip_endpoint * endpoint, pjsip_sip_uri * sip_uri, char * buf, size_t buf_len)
Get the transport name from an endpoint or request uri.
Since
13.15.0
Parameters
endpoint
sip_uri
buf Buffer to receive transport name
buf_len Buffer length
Return values
0 Success
-1 Failure
Note
If endpoint->transport is not NULL, it is returned in buf. Otherwise if sip_uri has an 'x-ast-txp' parameter AND the sip_uri host is an ip4 or ip6 address, its value is returned,
Definition at line 3762 of file res_pjsip.c.
References ast_alloca, ast_copy_pj_str(), ast_copy_string(), AST_SIP_X_AST_TXP, AST_SIP_X_AST_TXP_LEN, ast_sockaddr_parse(), ast_strlen_zero, host, NULL, PARSE_PORT_FORBID, and ast_sip_endpoint::transport.
Referenced by ast_sip_set_tpselector_from_ep_or_uri().
 {
    char *host = NULL;
    static const pj_str_t x_name = { AST_SIP_X_AST_TXP, AST_SIP_X_AST_TXP_LEN };
    pjsip_param *x_transport;
    if (!ast_strlen_zero(endpoint->transport)) {
       ast_copy_string(buf, endpoint->transport, buf_len);
       return 0;
    }
    x_transport = pjsip_param_find(&sip_uri->other_param, &x_name);
    if (!x_transport) {
       return -1;
    }
    /* Only use x_transport if the uri host is an ip (4 or 6) address */
    host = ast_alloca(sip_uri->host.slen + 1);
    ast_copy_pj_str(host, &sip_uri->host, sip_uri->host.slen + 1);
    if (!ast_sockaddr_parse(NULL, host, PARSE_PORT_FORBID)) {
       return -1;
    }
    ast_copy_pj_str(buf, &x_transport->value, buf_len);
    return 0;
 }
ast_sip_identify_endpoint()
struct ast_sip_endpoint* ast_sip_identify_endpoint (pjsip_rx_data * rdata)
Determine the endpoint that has sent a SIP message.
This will call into each of the registered endpoint identifiers' identify_endpoint() callbacks until one returns a non-NULL endpoint. This will return an ao2 object. Its reference count will need to be decremented when completed using the endpoint.
Parameters
rdata The inbound SIP message to use when identifying the endpoint.
Return values
NULL No matching endpoint
non-NULL The matching endpoint
Definition at line 3528 of file res_pjsip.c.
References ast_assert, AST_RWLIST_RDLOCK, AST_RWLIST_TRAVERSE, AST_RWLIST_UNLOCK, endpoint_identifier_list::identifier, ast_sip_endpoint_identifier::identify_endpoint, lock, NULL, and SCOPED_LOCK.
Referenced by endpoint_lookup().
 {
    struct endpoint_identifier_list *iter;
    struct ast_sip_endpoint *endpoint = NULL;
    SCOPED_LOCK(lock, &endpoint_identifiers, AST_RWLIST_RDLOCK, AST_RWLIST_UNLOCK);
    AST_RWLIST_TRAVERSE(&endpoint_identifiers, iter, list) {
       ast_assert(iter->identifier->identify_endpoint != NULL);
       endpoint = iter->identifier->identify_endpoint(rdata);
       if (endpoint) {
          break;
       }
    }
    return endpoint;
 }
ast_sip_is_content_type()
int ast_sip_is_content_type (pjsip_media_type * content_type, char * type, char * subtype)
Checks if the given content type matches type/subtype.
Compares the pjsip_media_type with the passed type and subtype and returns the result of that comparison. The media type parameters are ignored.
Parameters
content_type The pjsip_media_type structure to compare
type The media type to compare
subtype The media subtype to compare
Return values
0 No match
-1 Match
Definition at line 5259 of file res_pjsip.c.
References compare().
Referenced by asterisk_publication_devicestate_state_change(), asterisk_publication_mwi_state_change(), check_content_type(), filter_on_tx_message(), pubsub_on_rx_notify_request(), session_outgoing_nat_hook(), and video_info_incoming_request().
 {
    pjsip_media_type compare;
    if (!content_type) {
       return 0;
    }
    pjsip_media_type_init2(&compare, type, subtype);
    return pjsip_media_type_cmp(content_type, &compare, 0) ? 0 : -1;
 }
ast_sip_modify_id_header()
void ast_sip_modify_id_header (pj_pool_t * pool, pjsip_fromto_hdr * id_hdr, const struct ast_party_id * id)
Set name and number information on an identity header.
Parameters
pool Memory pool to use for string duplication
id_hdr A From, P-Asserted-Identity, or Remote-Party-ID header to modify
id The identity information to apply to the header
Definition at line 5587 of file res_pjsip.c.
References ast_alloca, ast_escape_quoted(), ast_strlen_zero, ast_party_id::name, NULL, ast_party_id::number, ast_party_name::str, ast_party_number::str, ast_party_name::valid, and ast_party_number::valid.
Referenced by add_pai_header(), add_rpid_header(), and set_from_header().
 {
    pjsip_name_addr *id_name_addr;
    pjsip_sip_uri *id_uri;
    id_name_addr = (pjsip_name_addr *) id_hdr->uri;
    id_uri = pjsip_uri_get_uri(id_name_addr->uri);
    if (id->name.valid) {
       if (!ast_strlen_zero(id->name.str)) {
          int name_buf_len = strlen(id->name.str) * 2 + 1;
          char *name_buf = ast_alloca(name_buf_len);
          ast_escape_quoted(id->name.str, name_buf, name_buf_len);
          pj_strdup2(pool, &id_name_addr->display, name_buf);
       } else {
          pj_strdup2(pool, &id_name_addr->display, NULL);
       }
    }
    if (id->number.valid) {
       pj_strdup2(pool, &id_uri->user, id->number.str);
    }
 }
ast_sip_push_task_wait()
static int ast_sip_push_task_wait (struct ast_taskprocessor * serializer, int(*)(void *) sip_task, void * task_data) static
Definition at line 5176 of file res_pjsip.c.
References ast_cond_destroy, ast_cond_init, ast_cond_wait, ast_mutex_destroy, ast_mutex_init, ast_mutex_lock, ast_mutex_unlock, ast_sip_push_task(), sync_task_data::complete, sync_task_data::cond, sync_task_data::fail, sync_task_data::lock, NULL, sync_task(), sync_task_data::task, and sync_task_data::task_data.
Referenced by ast_sip_push_task_wait_serializer(), and ast_sip_push_task_wait_servant().
 {
    /* This method is an onion */
    struct sync_task_data std;
    memset(&std, 0, sizeof(std));
    ast_mutex_init(&std.lock);
    ast_cond_init(&std.cond, NULL);
    std.task = sip_task;
    std.task_data = task_data;
    if (ast_sip_push_task(serializer, sync_task, &std)) {
       ast_mutex_destroy(&std.lock);
       ast_cond_destroy(&std.cond);
       return -1;
    }
    ast_mutex_lock(&std.lock);
    while (!std.complete) {
       ast_cond_wait(&std.cond, &std.lock);
    }
    ast_mutex_unlock(&std.lock);
    ast_mutex_destroy(&std.lock);
    ast_cond_destroy(&std.cond);
    return std.fail;
 }
ast_sip_rdata_get_header_value()
char* ast_sip_rdata_get_header_value (pjsip_rx_data * rdata, const pj_str_t str)
Get a specific header value from rdata.
Note
The returned value does not need to be freed since it's from the rdata pool
Parameters
rdata The rdata
str The header to find
Return values
NULL on failure
The header value on success
Definition at line 3543 of file res_pjsip.c.
References NULL.
Referenced by stir_shaken_incoming_request().
 {
    pjsip_generic_string_hdr *hdr;
    pj_str_t hdr_val;
    hdr = pjsip_msg_find_hdr_by_name(rdata->msg_info.msg, &str, NULL);
    if (!hdr) {
       return NULL;
    }
    pj_strdup_with_null(rdata->tp_info.pool, &hdr_val, &hdr->hvalue);
    return hdr_val.ptr;
 }
ast_sip_register_authenticator()
int ast_sip_register_authenticator (struct ast_sip_authenticator * auth)
Register a SIP authenticator.
An authenticator has three main purposes: 1) Determining if authentication should be performed on an incoming request 2) Gathering credentials necessary for issuing an authentication challenge 3) Authenticating a request that has credentials
Asterisk provides a default authenticator, but it may be replaced by a custom one if desired.
Parameters
auth The authenticator to register
Return values
0 Success
-1 Failure
Definition at line 3338 of file res_pjsip.c.
References ast_debug, ast_log, and LOG_WARNING.
Referenced by load_module().
 {
    if (registered_authenticator) {
       ast_log(LOG_WARNING, "Authenticator %p is already registered. Cannot register a new one\n", registered_authenticator);
       return -1;
    }
    registered_authenticator = auth;
    ast_debug(1, "Registered SIP authenticator module %p\n", auth);
    return 0;
 }
ast_sip_register_endpoint_formatter()
void ast_sip_register_endpoint_formatter (struct ast_sip_endpoint_formatter * obj)
Register an endpoint formatter.
Parameters
obj the formatter to register
Definition at line 3679 of file res_pjsip.c.
References AST_RWLIST_INSERT_TAIL, AST_RWLIST_UNLOCK, AST_RWLIST_WRLOCK, lock, ast_cli_entry::next, and SCOPED_LOCK.
Referenced by ast_res_pjsip_init_options_handling(), ast_sip_initialize_sorcery_auth(), ast_sip_initialize_sorcery_location(), ast_sip_initialize_sorcery_transport(), and load_module().
 {
    SCOPED_LOCK(lock, &endpoint_formatters, AST_RWLIST_WRLOCK, AST_RWLIST_UNLOCK);
    AST_RWLIST_INSERT_TAIL(&endpoint_formatters, obj, next);
 }
ast_sip_register_endpoint_identifier()
int ast_sip_register_endpoint_identifier (struct ast_sip_endpoint_identifier * identifier)
Register a SIP endpoint identifier.
An endpoint identifier's purpose is to determine which endpoint a given SIP message has come from.
Multiple endpoint identifiers may be registered so that if an endpoint cannot be identified by one identifier, it may be identified by another.
Asterisk provides two endpoint identifiers. One identifies endpoints based on the user part of the From header URI. The other identifies endpoints based on the source IP address.
If the order in which endpoint identifiers is run is important to you, then be sure to load individual endpoint identifier modules in the order you wish for them to be run in modules.conf
Note
endpoint identifiers registered using this method (no name specified) are placed at the front of the endpoint identifiers list ahead of any named identifiers.
Parameters
identifier The SIP endpoint identifier to register
Return values
0 Success
-1 Failure
Definition at line 3508 of file res_pjsip.c.
References ast_sip_register_endpoint_identifier_with_name(), and NULL.
Referenced by load_module().
 {
    return ast_sip_register_endpoint_identifier_with_name(identifier, NULL);
 }
ast_sip_register_endpoint_identifier_with_name()
int ast_sip_register_endpoint_identifier_with_name (struct ast_sip_endpoint_identifier * identifier, const char * name)
Register a SIP endpoint identifier with a name.
An endpoint identifier's purpose is to determine which endpoint a given SIP message has come from.
Multiple endpoint identifiers may be registered so that if an endpoint cannot be identified by one identifier, it may be identified by another.
Parameters
identifier The SIP endpoint identifier to register
name The name of the endpoint identifier
Return values
0 Success
-1 Failure
Definition at line 3431 of file res_pjsip.c.
References ast_calloc, ast_debug, ast_free, ast_log, AST_RWLIST_EMPTY, AST_RWLIST_INSERT_AFTER, AST_RWLIST_INSERT_BEFORE_CURRENT, AST_RWLIST_INSERT_HEAD, AST_RWLIST_INSERT_TAIL, AST_RWLIST_NEXT, AST_RWLIST_TRAVERSE_SAFE_BEGIN, AST_RWLIST_TRAVERSE_SAFE_END, AST_RWLIST_UNLOCK, AST_RWLIST_WRLOCK, ast_sip_get_endpoint_identifier_order(), ast_strlen_zero, endpoint_identifier_list::identifier, lock, LOG_ERROR, endpoint_identifier_list::name, endpoint_identifier_list::priority, and SCOPED_LOCK.
Referenced by ast_sip_register_endpoint_identifier(), and load_module().
 {
    char *prev, *current, *identifier_order;
    struct endpoint_identifier_list *iter, *id_list_item;
    SCOPED_LOCK(lock, &endpoint_identifiers, AST_RWLIST_WRLOCK, AST_RWLIST_UNLOCK);
    id_list_item = ast_calloc(1, sizeof(*id_list_item));
    if (!id_list_item) {
       ast_log(LOG_ERROR, "Unable to add endpoint identifier. Out of memory.\n");
       return -1;
    }
    id_list_item->identifier = identifier;
    id_list_item->name = name;
    ast_debug(1, "Register endpoint identifier %s(%p)\n", name ?: "", identifier);
    if (ast_strlen_zero(name)) {
       /* if an identifier has no name then place in front */
       AST_RWLIST_INSERT_HEAD(&endpoint_identifiers, id_list_item, list);
       return 0;
    }
    /* see if the name of the identifier is in the global endpoint_identifier_order list */
    identifier_order = prev = current = ast_sip_get_endpoint_identifier_order();
    if (ast_strlen_zero(identifier_order)) {
       id_list_item->priority = UINT_MAX;
       AST_RWLIST_INSERT_TAIL(&endpoint_identifiers, id_list_item, list);
       ast_free(identifier_order);
       return 0;
    }
    id_list_item->priority = 0;
    while ((current = strchr(current, ','))) {
       ++id_list_item->priority;
       if (!strncmp(prev, name, current - prev)
          && strlen(name) == current - prev) {
          break;
       }
       prev = ++current;
    }
    if (!current) {
       /* check to see if it is the only or last item */
       if (!strcmp(prev, name)) {
          ++id_list_item->priority;
       } else {
          id_list_item->priority = UINT_MAX;
       }
    }
    if (id_list_item->priority == UINT_MAX || AST_RWLIST_EMPTY(&endpoint_identifiers)) {
       /* if not in the endpoint_identifier_order list then consider it less in
          priority and add it to the end */
       AST_RWLIST_INSERT_TAIL(&endpoint_identifiers, id_list_item, list);
       ast_free(identifier_order);
       return 0;
    }
    AST_RWLIST_TRAVERSE_SAFE_BEGIN(&endpoint_identifiers, iter, list) {
       if (id_list_item->priority < iter->priority) {
          AST_RWLIST_INSERT_BEFORE_CURRENT(id_list_item, list);
          break;
       }
       if (!AST_RWLIST_NEXT(iter, list)) {
          AST_RWLIST_INSERT_AFTER(&endpoint_identifiers, iter, id_list_item, list);
          break;
       }
    }
    AST_RWLIST_TRAVERSE_SAFE_END;
    ast_free(identifier_order);
    return 0;
 }
ast_sip_register_outbound_authenticator()
int ast_sip_register_outbound_authenticator (struct ast_sip_outbound_authenticator * outbound_auth)
Register an outbound SIP authenticator.
An outbound authenticator is responsible for creating responses to authentication challenges by remote endpoints.
Parameters
auth The authenticator to register
Return values
0 Success
-1 Failure
Definition at line 3389 of file res_pjsip.c.
References ast_debug, ast_log, and LOG_WARNING.
Referenced by load_module().
 {
    if (registered_outbound_authenticator) {
       ast_log(LOG_WARNING, "Outbound authenticator %p is already registered. Cannot register a new one\n", registered_outbound_authenticator);
       return -1;
    }
    registered_outbound_authenticator = auth;
    ast_debug(1, "Registered SIP outbound authenticator module %p\n", auth);
    return 0;
 }
ast_sip_register_service()
int ast_sip_register_service (pjsip_module * module)
Register a SIP service in Asterisk.
This is more-or-less a wrapper around pjsip_endpt_register_module(). Registering a service makes it so that PJSIP will call into the service at appropriate times. For more information about PJSIP module callbacks, see the PJSIP documentation. Asterisk modules that call this function will likely do so at module load time.
Parameters
module The module that is to be registered with PJSIP
Return values
0 Success
-1 Failure
Definition at line 3315 of file res_pjsip.c.
References ast_sip_push_task_wait_servant(), NULL, and register_service().
Referenced by ast_res_pjsip_init_message_filter(), ast_sip_initialize_distributor(), ast_sip_initialize_global_headers(), ast_sip_initialize_transport_management(), and load_module().
 {
    return ast_sip_push_task_wait_servant(NULL, register_service, &module);
 }
ast_sip_register_supplement()
void ast_sip_register_supplement (struct ast_sip_supplement * supplement)
Register a supplement to SIP out of dialog processing.
This allows for someone to insert themselves in the processing of out of dialog SIP requests and responses. This, for example could allow for a module to set channel data based on headers in an incoming message. Similarly, a module could reject an incoming request if desired.
Parameters
supplement The supplement to register
Return values
0 Success
-1 Failure
Definition at line 4511 of file res_pjsip.c.
References AST_RWLIST_INSERT_BEFORE_CURRENT, AST_RWLIST_INSERT_TAIL, AST_RWLIST_TRAVERSE_SAFE_BEGIN, AST_RWLIST_TRAVERSE_SAFE_END, AST_RWLIST_UNLOCK, AST_RWLIST_WRLOCK, lock, ast_sip_supplement::next, ast_sip_supplement::priority, and SCOPED_LOCK.
Referenced by ast_res_pjsip_init_message_filter(), and load_module().
 {
    struct ast_sip_supplement *iter;
    int inserted = 0;
    SCOPED_LOCK(lock, &supplements, AST_RWLIST_WRLOCK, AST_RWLIST_UNLOCK);
    AST_RWLIST_TRAVERSE_SAFE_BEGIN(&supplements, iter, next) {
       if (iter->priority > supplement->priority) {
          AST_RWLIST_INSERT_BEFORE_CURRENT(supplement, next);
          inserted = 1;
          break;
       }
    }
    AST_RWLIST_TRAVERSE_SAFE_END;
    if (!inserted) {
       AST_RWLIST_INSERT_TAIL(&supplements, supplement, next);
    }
 }
ast_sip_requires_authentication()
int ast_sip_requires_authentication (struct ast_sip_endpoint * endpoint, pjsip_rx_data * rdata)
Determine if an incoming request requires authentication.
This calls into the registered authenticator's requires_authentication callback in order to determine if the request requires authentication.
If there is no registered authenticator, then authentication will be assumed not to be required.
Parameters
endpoint The endpoint from which the request originates
rdata The incoming SIP request
Return values
non-zero The request requires authentication
0 The request does not require authentication
Definition at line 3361 of file res_pjsip.c.
References ast_sip_endpoint::allow_unauthenticated_options, ast_debug, ast_log, LOG_WARNING, and ast_sip_authenticator::requires_authentication.
Referenced by authenticate().
 {
    if (endpoint->allow_unauthenticated_options
       && !pjsip_method_cmp(&rdata->msg_info.msg->line.req.method, &pjsip_options_method)) {
       ast_debug(3, "Skipping OPTIONS authentication due to endpoint configuration\n");
       return 0;
    }
    if (!registered_authenticator) {
       ast_log(LOG_WARNING, "No SIP authenticator registered. Assuming authentication is not required\n");
       return 0;
    }
    return registered_authenticator->requires_authentication(endpoint, rdata);
 }
ast_sip_send_out_of_dialog_request()
int ast_sip_send_out_of_dialog_request (pjsip_tx_data * tdata, struct ast_sip_endpoint * endpoint, int timeout, void * token, void(*)(void *token, pjsip_event *e) callback)
General purpose method for sending an Out-Of-Dialog SIP request.
This is a companion function for ast_sip_create_request. The request created there can be passed to this function, though any request may be passed in.
This will automatically set up handling outbound authentication challenges if they arrive.
Parameters
tdata The request to send
endpoint Optional. If specified, the out-of-dialog request is sent to the endpoint.
timeout. If non-zero, after the timeout the transaction will be terminated and the callback will be called with the PJSIP_EVENT_TIMER type.
token Data to be passed to the callback upon receipt of out-of-dialog response.
callback Callback to be called upon receipt of out-of-dialog response.
Return values
0 Success
-1 Failure (out-of-dialog callback will not be called.)
Note
Timeout processing: There are 2 timers associated with this request, PJSIP timer_b which is set globally in the "system" section of pjsip.conf, and the timeout specified on this call. The timer that expires first (before normal completion) will cause the callback to be run with e->body.tsx_state.type = PJSIP_EVENT_TIMER. The timer that expires second is simply ignored and the callback is not run again.
Definition at line 4993 of file res_pjsip.c.
References ao2_cleanup, AST_LIST_TRAVERSE, AST_RWLIST_RDLOCK, AST_RWLIST_UNLOCK, ast_sip_message_apply_transport(), ast_sip_mod_data_get, ast_sip_mod_data_set, does_method_match(), endpt_send_request(), ast_sip_supplement::method, MOD_DATA_CONTACT, NULL, ast_sip_supplement::outgoing_request, send_request_data_alloc(), supplement_module, and ast_sip_endpoint::transport.
Referenced by ast_sip_send_request(), and sip_options_qualify_contact().
 {
    struct ast_sip_supplement *supplement;
    struct send_request_data *req_data;
    struct ast_sip_contact *contact;
    req_data = send_request_data_alloc(endpoint, token, callback);
    if (!req_data) {
       pjsip_tx_data_dec_ref(tdata);
       return -1;
    }
    if (endpoint) {
       ast_sip_message_apply_transport(endpoint->transport, tdata);
    }
    contact = ast_sip_mod_data_get(tdata->mod_data, supplement_module.id, MOD_DATA_CONTACT);
    AST_RWLIST_RDLOCK(&supplements);
    AST_LIST_TRAVERSE(&supplements, supplement, next) {
       if (supplement->outgoing_request
          && does_method_match(&tdata->msg->line.req.method.name, supplement->method)) {
          supplement->outgoing_request(endpoint, contact, tdata);
       }
    }
    AST_RWLIST_UNLOCK(&supplements);
    ast_sip_mod_data_set(tdata->pool, tdata->mod_data, supplement_module.id, MOD_DATA_CONTACT, NULL);
    ao2_cleanup(contact);
    if (endpt_send_request(endpoint, tdata, timeout, req_data, send_request_cb)
       != PJ_SUCCESS) {
       ao2_cleanup(req_data);
       return -1;
    }
    return 0;
 }
ast_sip_send_request()
int ast_sip_send_request (pjsip_tx_data * tdata, struct pjsip_dialog * dlg, struct ast_sip_endpoint * endpoint, void * token, void(*)(void *token, pjsip_event *e) callback)
General purpose method for sending a SIP request.
This is a companion function for ast_sip_create_request. The request created there can be passed to this function, though any request may be passed in.
This will automatically set up handling outbound authentication challenges if they arrive.
Parameters
tdata The request to send
dlg Optional. The dialog in which the request is sent. Otherwise it is out-of-dialog.
endpoint Optional. If specified, the out-of-dialog request is sent to the endpoint.
token Data to be passed to the callback upon receipt of out-of-dialog response.
callback Callback to be called upon receipt of out-of-dialog response.
Return values
0 Success
-1 Failure (out-of-dialog callback will not be called.)
Definition at line 5034 of file res_pjsip.c.
References ast_assert, ast_sip_send_out_of_dialog_request(), and send_in_dialog_request().
Referenced by msg_send(), notify_channel(), notify_contact(), notify_uri(), send_unsolicited_mwi_notify_to_contact(), and sendtext().
 {
    ast_assert(tdata->msg->type == PJSIP_REQUEST_MSG);
    if (dlg) {
       return send_in_dialog_request(tdata, dlg);
    } else {
       return ast_sip_send_out_of_dialog_request(tdata, endpoint, -1, token, callback);
    }
 }
ast_sip_send_response()
int ast_sip_send_response (pjsip_response_addr * res_addr, pjsip_tx_data * tdata, struct ast_sip_endpoint * sip_endpoint)
Send a response to an out of dialog request.
Use this function sparingly, since this does not create a transaction within PJSIP. This means that if the request is retransmitted, it is your responsibility to detect this and not process the same request twice, and to send the same response for each retransmission.
Parameters
res_addr The response address for this response
tdata The response to send
endpoint The ast_sip_endpoint associated with this response
Return values
0 Success
-1 Failure
Definition at line 5407 of file res_pjsip.c.
References ast_sip_get_pjsip_endpoint(), NULL, status, and supplement_outgoing_response().
 {
    pj_status_t status;
    supplement_outgoing_response(tdata, sip_endpoint);
    status = pjsip_endpt_send_response(ast_sip_get_pjsip_endpoint(), res_addr, tdata, NULL, NULL);
    if (status != PJ_SUCCESS) {
       pjsip_tx_data_dec_ref(tdata);
    }
    return status == PJ_SUCCESS ? 0 : -1;
 }
ast_sip_send_stateful_response()
int ast_sip_send_stateful_response (pjsip_rx_data * rdata, pjsip_tx_data * tdata, struct ast_sip_endpoint * sip_endpoint)
Send a stateful response to an out of dialog request.
This creates a transaction within PJSIP, meaning that if the request that we are responding to is retransmitted, we will not attempt to re-handle the request.
Parameters
rdata The request that is being responded to
tdata The response to send
endpoint The ast_sip_endpoint associated with this response
Since
13.4.0
Return values
0 Success
-1 Failure
Definition at line 5420 of file res_pjsip.c.
References ao2_cleanup, ast_sip_mod_data_get, ast_sip_mod_data_set, MOD_DATA_CONTACT, NULL, supplement_module, and supplement_outgoing_response().
Referenced by register_aor(), send_options_response(), and send_response().
 {
    pjsip_transaction *tsx;
    if (pjsip_tsx_create_uas(NULL, rdata, &tsx) != PJ_SUCCESS) {
       struct ast_sip_contact *contact;
       /* ast_sip_create_response bumps the refcount of the contact and adds it to the tdata.
        * We'll leak that reference if we don't get rid of it here.
        */
       contact = ast_sip_mod_data_get(tdata->mod_data, supplement_module.id, MOD_DATA_CONTACT);
       ao2_cleanup(contact);
       ast_sip_mod_data_set(tdata->pool, tdata->mod_data, supplement_module.id, MOD_DATA_CONTACT, NULL);
       pjsip_tx_data_dec_ref(tdata);
       return -1;
    }
    pjsip_tsx_recv_msg(tsx, rdata);
    supplement_outgoing_response(tdata, sip_endpoint);
    if (pjsip_tsx_send_msg(tsx, tdata) != PJ_SUCCESS) {
       pjsip_tx_data_dec_ref(tdata);
       return -1;
    }
    return 0;
 }
ast_sip_set_outbound_proxy()
int ast_sip_set_outbound_proxy (pjsip_tx_data * tdata, const char * proxy)
Set the outbound proxy for an outbound SIP message.
Parameters
tdata The message to set the outbound proxy on
proxy SIP uri of the proxy
Return values
0 Success
-1 Failure
Definition at line 5047 of file res_pjsip.c.
References NULL, and tmp().
Referenced by create_out_of_dialog_request(), path_outgoing_request(), and sip_options_qualify_contact().
 {
    pjsip_route_hdr *route;
    static const pj_str_t ROUTE_HNAME = { "Route", 5 };
    pj_str_t tmp;
    pj_strdup2_with_null(tdata->pool, &tmp, proxy);
    if (!(route = pjsip_parse_hdr(tdata->pool, &ROUTE_HNAME, tmp.ptr, tmp.slen, NULL))) {
       return -1;
    }
    pj_list_insert_nodes_before(&tdata->msg->hdr, (pjsip_hdr*)route);
    return 0;
 }
ast_sip_set_tpselector_from_ep_or_uri()
int ast_sip_set_tpselector_from_ep_or_uri (const struct ast_sip_endpoint * endpoint, pjsip_sip_uri * sip_uri, pjsip_tpselector * selector)
Sets pjsip_tpselector from an endpoint or uri.
Since
13.15.0
Parameters
endpoint If endpoint->transport is set, it's used
sip_uri If sip_uri contains a x-ast-txp parameter, it's used
selector The selector to be populated
Return values
0 success
-1 failure
Definition at line 3975 of file res_pjsip.c.
References ast_sip_get_transport_name(), and ast_sip_set_tpselector_from_transport_name().
Referenced by ast_sip_dlg_set_transport(), create_dialog_uas(), and create_out_of_dialog_request().
 {
    char transport_name[128];
    if (ast_sip_get_transport_name(endpoint, sip_uri, transport_name, sizeof(transport_name))) {
       return 0;
    }
    return ast_sip_set_tpselector_from_transport_name(transport_name, selector);
 }
ast_sip_set_tpselector_from_transport()
int ast_sip_set_tpselector_from_transport (const struct ast_sip_transport * transport, pjsip_tpselector * selector)
Sets pjsip_tpselector from ast_sip_transport.
Since
13.8.0
Parameters
transport The transport to be used
selector The selector to be populated
Return values
0 success
-1 failure
Note
The transport selector must be unreffed using ast_sip_tpselector_unref
Definition at line 3907 of file res_pjsip.c.
References ao2_lock, ao2_ref, ao2_unlock, ast_log, ast_sip_get_transport_state(), ast_sorcery_object_get_id(), AST_TRANSPORT_WS, AST_TRANSPORT_WSS, ast_sip_transport_state::factory, ast_sip_transport_state::flow, ast_sip_transport::flow, LOG_ERROR, LOG_WARNING, ast_sip_transport_state::transport, and ast_sip_transport::type.
Referenced by ast_sip_set_tpselector_from_transport_name().
 {
    int res = 0;
    struct ast_sip_transport_state *transport_state;
    transport_state = ast_sip_get_transport_state(ast_sorcery_object_get_id(transport));
    if (!transport_state) {
       ast_log(LOG_ERROR, "Unable to retrieve PJSIP transport state for '%s'\n",
          ast_sorcery_object_get_id(transport));
       return -1;
    }
    /* Only flows maintain dynamic state which needs protection */
    if (transport_state->flow) {
       ao2_lock(transport_state);
    }
    if (transport_state->transport) {
       selector->type = PJSIP_TPSELECTOR_TRANSPORT;
       selector->u.transport = transport_state->transport;
       pjsip_transport_add_ref(selector->u.transport);
    } else if (transport_state->factory) {
       selector->type = PJSIP_TPSELECTOR_LISTENER;
       selector->u.listener = transport_state->factory;
    } else if (transport->type == AST_TRANSPORT_WS || transport->type == AST_TRANSPORT_WSS) {
       /* The WebSocket transport has no factory as it can not create outgoing connections, so
        * even if an endpoint is locked to a WebSocket transport we let the PJSIP logic
        * find the existing connection if available and use it.
        */
    } else if (transport->flow) {
       /* This is a child of another transport, so we need to establish a new connection */
 #ifdef HAVE_PJSIP_TRANSPORT_DISABLE_CONNECTION_REUSE
       selector->disable_connection_reuse = PJ_TRUE;
 #else
       ast_log(LOG_WARNING, "Connection reuse could not be disabled on transport '%s' as support is not available\n",
          ast_sorcery_object_get_id(transport));
 #endif
    } else {
       res = -1;
    }
    if (transport_state->flow) {
       ao2_unlock(transport_state);
    }
    ao2_ref(transport_state, -1);
    return res;
 }
ast_sip_set_tpselector_from_transport_name()
int ast_sip_set_tpselector_from_transport_name (const char * transport_name, pjsip_tpselector * selector)
Sets pjsip_tpselector from ast_sip_transport.
Since
13.8.0
Parameters
transport_name The name of the transport to be used
selector The selector to be populated
Return values
0 success
-1 failure
Note
The transport selector must be unreffed using ast_sip_tpselector_unref
Definition at line 3957 of file res_pjsip.c.
References ao2_cleanup, ast_log, ast_sip_get_sorcery(), ast_sip_set_tpselector_from_transport(), ast_sorcery_retrieve_by_id(), ast_strlen_zero, LOG_ERROR, NULL, RAII_VAR, and ast_sip_transport_state::transport.
Referenced by ast_sip_set_tpselector_from_ep_or_uri(), registration_client_send(), set_transport(), and sip_outbound_registration_regc_alloc().
 {
    RAII_VAR(struct ast_sip_transport *, transport, NULL, ao2_cleanup);
    if (ast_strlen_zero(transport_name)) {
       return 0;
    }
    transport = ast_sorcery_retrieve_by_id(ast_sip_get_sorcery(), "transport", transport_name);
    if (!transport) {
       ast_log(LOG_ERROR, "Unable to retrieve PJSIP transport '%s'\n",
          transport_name);
       return -1;
    }
    return ast_sip_set_tpselector_from_transport(transport, selector);
 }
ast_sip_str_to_dtmf()
int ast_sip_str_to_dtmf (const char * dtmf_mode)
Convert the DTMF mode name into an enum.
Since
13.18.0
Parameters
dtmf_mode dtmf mode as a string
Return values
>= 0 The enum value
-1 Failure
Definition at line 5513 of file res_pjsip.c.
References AST_SIP_DTMF_AUTO, AST_SIP_DTMF_AUTO_INFO, AST_SIP_DTMF_INBAND, AST_SIP_DTMF_INFO, AST_SIP_DTMF_NONE, AST_SIP_DTMF_RFC_4733, and result.
Referenced by dtmf_handler(), and pjsip_acf_dtmf_mode_write().
 {
    int result = -1;
    if (!strcasecmp(dtmf_mode, "info")) {
       result = AST_SIP_DTMF_INFO;
    } else if (!strcasecmp(dtmf_mode, "rfc4733")) {
       result = AST_SIP_DTMF_RFC_4733;
    } else if (!strcasecmp(dtmf_mode, "inband")) {
       result = AST_SIP_DTMF_INBAND;
    } else if (!strcasecmp(dtmf_mode, "none")) {
       result = AST_SIP_DTMF_NONE;
    } else if (!strcasecmp(dtmf_mode, "auto")) {
       result = AST_SIP_DTMF_AUTO;
    } else if (!strcasecmp(dtmf_mode, "auto_info")) {
       result = AST_SIP_DTMF_AUTO_INFO;
    }
    return result;
 }
ast_sip_threadpool()
struct ast_threadpool* ast_sip_threadpool (void)
Retrieve the SIP threadpool object.
Definition at line 5630 of file res_pjsip.c.
References sip_threadpool.
Referenced by load_module().
 {
    return sip_threadpool;
 }
ast_sip_threadpool_queue_size()
long ast_sip_threadpool_queue_size (void)
Return the size of the SIP threadpool's task queue.
Since
13.7.0
Definition at line 5625 of file res_pjsip.c.
References ast_threadpool_queue_size().
 {
    return ast_threadpool_queue_size(sip_threadpool);
 }
ast_sip_tpselector_unref()
void ast_sip_tpselector_unref (pjsip_tpselector * selector)
Unreference a pjsip_tpselector.
Since
17.0.0
Parameters
selector The selector to be unreffed
Definition at line 3987 of file res_pjsip.c.
Referenced by ast_sip_create_dialog_uac(), ast_sip_dlg_set_transport(), create_dialog_uas(), create_out_of_dialog_request(), registration_client_send(), set_transport(), and sip_outbound_registration_regc_alloc().
 {
    if (selector->type == PJSIP_TPSELECTOR_TRANSPORT && selector->u.transport) {
       pjsip_transport_dec_ref(selector->u.transport);
    }
 }
ast_sip_unregister_authenticator()
void ast_sip_unregister_authenticator (struct ast_sip_authenticator * auth)
Unregister a SIP authenticator.
When there is no authenticator registered, requests cannot be challenged or authenticated.
Parameters
auth The authenticator to unregister
Definition at line 3350 of file res_pjsip.c.
References ast_debug, ast_log, LOG_WARNING, and NULL.
Referenced by unload_module().
 {
    if (registered_authenticator != auth) {
       ast_log(LOG_WARNING, "Trying to unregister authenticator %p but authenticator %p registered\n",
             auth, registered_authenticator);
       return;
    }
    registered_authenticator = NULL;
    ast_debug(1, "Unregistered SIP authenticator %p\n", auth);
 }
ast_sip_unregister_endpoint_formatter()
void ast_sip_unregister_endpoint_formatter (struct ast_sip_endpoint_formatter * obj)
Unregister an endpoint formatter.
Parameters
obj the formatter to unregister
Definition at line 3685 of file res_pjsip.c.
References AST_RWLIST_REMOVE_CURRENT, AST_RWLIST_TRAVERSE_SAFE_BEGIN, AST_RWLIST_TRAVERSE_SAFE_END, AST_RWLIST_UNLOCK, AST_RWLIST_WRLOCK, lock, and SCOPED_LOCK.
Referenced by ast_res_pjsip_cleanup_options_handling(), ast_sip_destroy_sorcery_auth(), ast_sip_destroy_sorcery_location(), ast_sip_destroy_sorcery_transport(), and unload_module().
 {
    struct ast_sip_endpoint_formatter *i;
    SCOPED_LOCK(lock, &endpoint_formatters, AST_RWLIST_WRLOCK, AST_RWLIST_UNLOCK);
    AST_RWLIST_TRAVERSE_SAFE_BEGIN(&endpoint_formatters, i, next) {
       if (i == obj) {
          AST_RWLIST_REMOVE_CURRENT(next);
          break;
       }
    }
    AST_RWLIST_TRAVERSE_SAFE_END;
 }
ast_sip_unregister_endpoint_identifier()
void ast_sip_unregister_endpoint_identifier (struct ast_sip_endpoint_identifier * identifier)
Unregister a SIP endpoint identifier.
This stops an endpoint identifier from being used.
Parameters
identifier The SIP endoint identifier to unregister
Definition at line 3513 of file res_pjsip.c.
References ast_debug, ast_free, AST_RWLIST_REMOVE_CURRENT, AST_RWLIST_TRAVERSE_SAFE_BEGIN, AST_RWLIST_TRAVERSE_SAFE_END, AST_RWLIST_UNLOCK, AST_RWLIST_WRLOCK, endpoint_identifier_list::identifier, lock, and SCOPED_LOCK.
Referenced by unload_module().
 {
    struct endpoint_identifier_list *iter;
    SCOPED_LOCK(lock, &endpoint_identifiers, AST_RWLIST_WRLOCK, AST_RWLIST_UNLOCK);
    AST_RWLIST_TRAVERSE_SAFE_BEGIN(&endpoint_identifiers, iter, list) {
       if (iter->identifier == identifier) {
          AST_RWLIST_REMOVE_CURRENT(list);
          ast_free(iter);
          ast_debug(1, "Unregistered endpoint identifier %p\n", identifier);
          break;
       }
    }
    AST_RWLIST_TRAVERSE_SAFE_END;
 }
ast_sip_unregister_outbound_authenticator()
void ast_sip_unregister_outbound_authenticator (struct ast_sip_outbound_authenticator * auth)
Unregister an outbound SIP authenticator.
When there is no outbound authenticator registered, authentication challenges will be handled as any other final response would be.
Parameters
auth The authenticator to unregister
Definition at line 3401 of file res_pjsip.c.
References ast_debug, ast_log, LOG_WARNING, and NULL.
Referenced by unload_module().
 {
    if (registered_outbound_authenticator != auth) {
       ast_log(LOG_WARNING, "Trying to unregister outbound authenticator %p but outbound authenticator %p registered\n",
             auth, registered_outbound_authenticator);
       return;
    }
    registered_outbound_authenticator = NULL;
    ast_debug(1, "Unregistered SIP outbound authenticator %p\n", auth);
 }
ast_sip_unregister_service()
void ast_sip_unregister_service (pjsip_module * module)
This is the opposite of ast_sip_register_service(). Unregistering a service means that PJSIP will no longer call into the module any more. This will likely occur when an Asterisk module is unloaded.
Parameters
module The PJSIP module to unregister
Definition at line 3331 of file res_pjsip.c.
References ast_sip_push_task_wait_servant(), NULL, and unregister_service().
Referenced by ast_res_pjsip_cleanup_message_filter(), ast_sip_destroy_distributor(), ast_sip_destroy_global_headers(), ast_sip_destroy_transport_management(), load_module(), unload_module(), and unload_pjsip().
 {
    ast_sip_push_task_wait_servant(NULL, unregister_service, &module);
 }
ast_sip_unregister_supplement()
void ast_sip_unregister_supplement (struct ast_sip_supplement * supplement)
Unregister a an supplement to SIP out of dialog processing.
Parameters
supplement The supplement to unregister
Definition at line 4531 of file res_pjsip.c.
References AST_RWLIST_REMOVE_CURRENT, AST_RWLIST_TRAVERSE_SAFE_BEGIN, AST_RWLIST_TRAVERSE_SAFE_END, AST_RWLIST_UNLOCK, AST_RWLIST_WRLOCK, lock, ast_sip_supplement::next, and SCOPED_LOCK.
Referenced by ast_res_pjsip_cleanup_message_filter(), and unload_module().
 {
    struct ast_sip_supplement *iter;
    SCOPED_LOCK(lock, &supplements, AST_RWLIST_WRLOCK, AST_RWLIST_UNLOCK);
    AST_RWLIST_TRAVERSE_SAFE_BEGIN(&supplements, iter, next) {
       if (supplement == iter) {
          AST_RWLIST_REMOVE_CURRENT(next);
          break;
       }
    }
    AST_RWLIST_TRAVERSE_SAFE_END;
 }
ast_sip_will_uri_survive_restart()
int ast_sip_will_uri_survive_restart (pjsip_sip_uri * uri, struct ast_sip_endpoint * endpoint, pjsip_rx_data * rdata)
Definition at line 3723 of file res_pjsip.c.
References ast_sip_endpoint::nat, result, and ast_sip_endpoint_nat_configuration::rewrite_contact.
Referenced by register_aor_core(), and subscription_persistence_update().
 {
    pj_str_t host_name;
    int result = 1;
    /* Determine if the contact cannot survive a restart/boot. */
    if (uri->port == rdata->pkt_info.src_port
       && !pj_strcmp(&uri->host,
          pj_cstr(&host_name, rdata->pkt_info.src_name))
       /* We have already checked if the URI scheme is sip: or sips: */
       && PJSIP_TRANSPORT_IS_RELIABLE(rdata->tp_info.transport)) {
       pj_str_t type_name;
       /* Determine the transport parameter value */
       if (!strcasecmp("WSS", rdata->tp_info.transport->type_name)) {
          /* WSS is special, as it needs to be ws. */
          pj_cstr(&type_name, "ws");
       } else {
          pj_cstr(&type_name, rdata->tp_info.transport->type_name);
       }
       if (!pj_stricmp(&uri->transport_param, &type_name)
          && (endpoint->nat.rewrite_contact
             /* Websockets are always rewritten */
             || !pj_stricmp(&uri->transport_param,
                pj_cstr(&type_name, "ws")))) {
          /*
           * The contact was rewritten to the reliable transport's
           * source address.  Disconnecting the transport for any
           * reason invalidates the contact.
           */
          result = 0;
       }
    }
    return result;
 }
AST_TEST_DEFINE() [1/2]
AST_TEST_DEFINE (xml_sanitization_end_null)
Definition at line 5636 of file res_pjsip.c.
References ast_sip_sanitize_xml(), AST_TEST_FAIL, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_test_status_update, sip_to_pjsip::info(), TEST_EXECUTE, and TEST_INIT.
 {
    char sanitized[8];
    switch (cmd) {
    case TEST_INIT:
       info->name = "xml_sanitization_end_null";
       info->category = "/res/res_pjsip/";
       info->summary = "Ensure XML sanitization works as expected with a long string";
       info->description = "This test sanitizes a string which exceeds the output\n"
          "buffer size. Once done the string is confirmed to be NULL terminated.";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    ast_sip_sanitize_xml("aaaaaaaaaaaa", sanitized, sizeof(sanitized));
    if (sanitized[7] != '\0') {
       ast_test_status_update(test, "Sanitized XML string is not null-terminated when it should be\n");
       return AST_TEST_FAIL;
    }
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [2/2]
AST_TEST_DEFINE (xml_sanitization_exceeds_buffer)
Definition at line 5661 of file res_pjsip.c.
References ast_sip_sanitize_xml(), AST_TEST_FAIL, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_test_status_update, sip_to_pjsip::info(), TEST_EXECUTE, and TEST_INIT.
 {
    char sanitized[8];
    switch (cmd) {
    case TEST_INIT:
       info->name = "xml_sanitization_exceeds_buffer";
       info->category = "/res/res_pjsip/";
       info->summary = "Ensure XML sanitization does not exceed buffer when output won't fit";
       info->description = "This test sanitizes a string which before sanitization would\n"
          "fit within the output buffer. After sanitization, however, the string would\n"
          "exceed the buffer. Once done the string is confirmed to be NULL terminated.";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    ast_sip_sanitize_xml("<><><>&", sanitized, sizeof(sanitized));
    if (sanitized[7] != '\0') {
       ast_test_status_update(test, "Sanitized XML string is not null-terminated when it should be\n");
       return AST_TEST_FAIL;
    }
    return AST_TEST_PASS;
 }
check_request_status()
static int check_request_status (struct send_request_data * req_data, pjsip_event * e) static
Definition at line 4894 of file res_pjsip.c.
References ao2_bump, ao2_ref, ast_sip_create_request_with_auth(), ast_sip_failover_request(), send_request_data::challenge_count, send_request_data::endpoint, endpt_send_request(), MAX_RX_CHALLENGES, and ast_sip_endpoint::outbound_auths.
Referenced by send_request_cb().
 {
    struct ast_sip_endpoint *endpoint;
    pjsip_transaction *tsx;
    pjsip_tx_data *tdata;
    int res = 0;
    if (!(endpoint = ao2_bump(req_data->endpoint))) {
       return 0;
    }
    tsx = e->body.tsx_state.tsx;
    switch (tsx->status_code) {
    case 401:
    case 407:
       /* Resend the request with a challenge response if we are challenged. */
       res = ++req_data->challenge_count < MAX_RX_CHALLENGES /* Not in a challenge loop */
          && !ast_sip_create_request_with_auth(&endpoint->outbound_auths,
             e->body.tsx_state.src.rdata, tsx->last_tx, &tdata);
       break;
    case 408:
    case 503:
       if ((res = ast_sip_failover_request(tsx->last_tx))) {
          tdata = tsx->last_tx;
          /*
           * Bump the ref since it will be on a new transaction and
           * we don't want it to go away along with the old transaction.
           */
          pjsip_tx_data_add_ref(tdata);
       }
       break;
    }
    if (res) {
       res = endpt_send_request(endpoint, tdata, -1,
                 req_data, send_request_cb) == PJ_SUCCESS;
    }
    ao2_ref(endpoint, -1);
    return res;
 }
cli_dump_endpt()
static char* cli_dump_endpt (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) static
Definition at line 3569 of file res_pjsip.c.
References ast_cli_args::argc, ast_cli_args::argv, ast_sip_push_task_wait_servant(), CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::command, do_cli_dump_endpt(), NULL, and ast_cli_entry::usage.
 {
    switch (cmd) {
    case CLI_INIT:
 #ifdef AST_DEVMODE
       e->command = "pjsip dump endpt [details]";
       e->usage =
          "Usage: pjsip dump endpt [details]\n"
          "       Dump the res_pjsip endpt internals.\n"
          "\n"
          "Warning: PJPROJECT documents that the function used by this\n"
          "CLI command may cause a crash when asking for details because\n"
          "it tries to access all active memory pools.\n";
 #else
       /*
        * In non-developer mode we will not document or make easily accessible
        * the details option even though it is still available.  The user has
        * to know it exists to use it.  Presumably they would also be aware of
        * the potential crash warning.
        */
       e->command = "pjsip dump endpt";
       e->usage =
          "Usage: pjsip dump endpt\n"
          "       Dump the res_pjsip endpt internals.\n";
 #endif /* AST_DEVMODE */
       return NULL;
    case CLI_GENERATE:
       return NULL;
    }
    if (4 < a->argc
       || (a->argc == 4 && strcasecmp(a->argv[3], "details"))) {
       return CLI_SHOWUSAGE;
    }
    ast_sip_push_task_wait_servant(NULL, do_cli_dump_endpt, a);
    return CLI_SUCCESS;
 }
cli_show_endpoint_identifiers()
static char* cli_show_endpoint_identifiers (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) static
Definition at line 3609 of file res_pjsip.c.
References ast_cli_args::argc, ast_cli(), AST_RWLIST_RDLOCK, AST_RWLIST_TRAVERSE, AST_RWLIST_UNLOCK, CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::command, ENDPOINT_IDENTIFIER_FORMAT, ast_cli_args::fd, lock, endpoint_identifier_list::name, NULL, SCOPED_LOCK, and ast_cli_entry::usage.
 {
 #define ENDPOINT_IDENTIFIER_FORMAT "%-20.20s\n"
    struct endpoint_identifier_list *iter;
    switch (cmd) {
    case CLI_INIT:
       e->command = "pjsip show identifiers";
       e->usage = "Usage: pjsip show identifiers\n"
                   "      List all registered endpoint identifiers\n";
       return NULL;
    case CLI_GENERATE:
       return NULL;
    }
    if (a->argc != 3) {
                 return CLI_SHOWUSAGE;
         }
    ast_cli(a->fd, ENDPOINT_IDENTIFIER_FORMAT, "Identifier Names:");
    {
       SCOPED_LOCK(lock, &endpoint_identifiers, AST_RWLIST_RDLOCK, AST_RWLIST_UNLOCK);
       AST_RWLIST_TRAVERSE(&endpoint_identifiers, iter, list) {
          ast_cli(a->fd, ENDPOINT_IDENTIFIER_FORMAT,
             iter->name ? iter->name : "name not specified");
       }
    }
    return CLI_SUCCESS;
 #undef ENDPOINT_IDENTIFIER_FORMAT
 }
cli_show_settings()
static char* cli_show_settings (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) static
Definition at line 3640 of file res_pjsip.c.
References ast_cli(), ast_free, ast_str_buffer(), ast_str_create, CLI_FAILURE, CLI_GENERATE, CLI_INIT, CLI_SUCCESS, ast_cli_entry::command, ast_cli_args::fd, NULL, ast_sip_cli_context::output_buffer, sip_cli_print_global(), sip_cli_print_system(), and ast_cli_entry::usage.
 {
    struct ast_sip_cli_context context;
    switch (cmd) {
    case CLI_INIT:
       e->command = "pjsip show settings";
       e->usage = "Usage: pjsip show settings\n"
                   "      Show global and system configuration options\n";
       return NULL;
    case CLI_GENERATE:
       return NULL;
    }
    context.output_buffer = ast_str_create(256);
    if (!context.output_buffer) {
       ast_cli(a->fd, "Could not allocate output buffer.\n");
       return CLI_FAILURE;
    }
    if (sip_cli_print_global(&context) || sip_cli_print_system(&context)) {
       ast_free(context.output_buffer);
       ast_cli(a->fd, "Error retrieving settings.\n");
       return CLI_FAILURE;
    }
    ast_cli(a->fd, "%s", ast_str_buffer(context.output_buffer));
    ast_free(context.output_buffer);
    return CLI_SUCCESS;
 }
create_dialog_uas()
static pjsip_dialog* create_dialog_uas (const struct ast_sip_endpoint * endpoint, pjsip_rx_data * rdata, pj_status_t * status, create_dlg_uac create_fun) static
Definition at line 4177 of file res_pjsip.c.
References ast_assert, ast_log, ast_sip_set_tpselector_from_ep_or_uri(), ast_sip_tpselector_unref(), ast_sorcery_object_get_id(), LOG_ERROR, NULL, ast_sip_transport_state::transport, type, and uas_use_sips_contact().
Referenced by ast_sip_create_dialog_uas(), and ast_sip_create_dialog_uas_locked().
 {
    pjsip_dialog *dlg;
    pj_str_t contact;
    pjsip_transport_type_e type = rdata->tp_info.transport->key.type;
    pjsip_tpselector selector = { .type = PJSIP_TPSELECTOR_NONE, };
    pjsip_transport *transport;
    pjsip_contact_hdr *contact_hdr;
    ast_assert(status != NULL);
    contact_hdr = pjsip_msg_find_hdr(rdata->msg_info.msg, PJSIP_H_CONTACT, NULL);
    if (!contact_hdr || ast_sip_set_tpselector_from_ep_or_uri(endpoint, pjsip_uri_get_uri(contact_hdr->uri),
       &selector)) {
       return NULL;
    }
    transport = rdata->tp_info.transport;
    if (selector.type == PJSIP_TPSELECTOR_TRANSPORT) {
       transport = selector.u.transport;
    }
    type = transport->key.type;
    contact.ptr = pj_pool_alloc(rdata->tp_info.pool, PJSIP_MAX_URL_SIZE);
    contact.slen = pj_ansi_snprintf(contact.ptr, PJSIP_MAX_URL_SIZE,
          "<%s:%s%.*s%s:%d%s%s>",
          uas_use_sips_contact(rdata) ? "sips" : "sip",
          (type & PJSIP_TRANSPORT_IPV6) ? "[" : "",
          (int)transport->local_name.host.slen,
          transport->local_name.host.ptr,
          (type & PJSIP_TRANSPORT_IPV6) ? "]" : "",
          transport->local_name.port,
          (type != PJSIP_TRANSPORT_UDP && type != PJSIP_TRANSPORT_UDP6) ? ";transport=" : "",
          (type != PJSIP_TRANSPORT_UDP && type != PJSIP_TRANSPORT_UDP6) ? pjsip_transport_get_type_name(type) : "");
    *status = create_fun(pjsip_ua_instance(), rdata, &contact, &dlg);
    if (*status != PJ_SUCCESS) {
       char err[PJ_ERR_MSG_SIZE];
       pj_strerror(*status, err, sizeof(err));
       ast_log(LOG_ERROR, "Could not create dialog with endpoint %s. %s\n",
             ast_sorcery_object_get_id(endpoint), err);
       ast_sip_tpselector_unref(&selector);
       return NULL;
    }
    dlg->sess_count++;
    pjsip_dlg_set_transport(dlg, &selector);
    dlg->sess_count--;
    ast_sip_tpselector_unref(&selector);
    return dlg;
 }
create_in_dialog_request()
static int create_in_dialog_request (const pjsip_method * method, struct pjsip_dialog * dlg, pjsip_tx_data ** tdata) static
Definition at line 4362 of file res_pjsip.c.
References ast_log, LOG_WARNING, and supplement_on_rx_request().
Referenced by ast_sip_create_request().
 {
    if (pjsip_dlg_create_request(dlg, method, -1, tdata) != PJ_SUCCESS) {
       ast_log(LOG_WARNING, "Unable to create in-dialog request.\n");
       return -1;
    }
    return 0;
 }
create_out_of_dialog_request()
static int create_out_of_dialog_request (const pjsip_method * method, struct ast_sip_endpoint * endpoint, const char * uri, struct ast_sip_contact * provided_contact, pjsip_tx_data ** tdata) static
Definition at line 4380 of file res_pjsip.c.
References ao2_bump, ao2_cleanup, ast_sip_endpoint::aors, ast_log, ast_sip_add_usereqphone(), ast_sip_get_pjsip_endpoint(), ast_sip_location_retrieve_contact_from_aor_list(), ast_sip_mod_data_set, ast_sip_set_outbound_proxy(), ast_sip_set_tpselector_from_ep_or_uri(), ast_sip_tpselector_unref(), ast_sorcery_object_get_id(), ast_strlen_zero, ast_sip_endpoint::contact_user, ast_sip_endpoint::fromdomain, ast_sip_endpoint::fromuser, LOG_ERROR, LOG_WARNING, MOD_DATA_CONTACT, NULL, ast_sip_endpoint::outbound_proxy, pool, RAII_VAR, sip_dialog_create_from(), and supplement_module.
Referenced by ast_sip_create_request().
 {
    RAII_VAR(struct ast_sip_contact *, contact, ao2_bump(provided_contact), ao2_cleanup);
    pj_str_t remote_uri;
    pj_str_t from;
    pj_pool_t *pool;
    pjsip_tpselector selector = { .type = PJSIP_TPSELECTOR_NONE, };
    pjsip_uri *sip_uri;
    const char *fromuser;
    if (ast_strlen_zero(uri)) {
       if (!endpoint && (!contact || ast_strlen_zero(contact->uri))) {
          ast_log(LOG_ERROR, "An endpoint and/or uri must be specified\n");
          return -1;
       }
       if (!contact) {
          contact = ast_sip_location_retrieve_contact_from_aor_list(endpoint->aors);
       }
       if (!contact || ast_strlen_zero(contact->uri)) {
          ast_log(LOG_WARNING, "Unable to retrieve contact for endpoint %s\n",
                ast_sorcery_object_get_id(endpoint));
          return -1;
       }
       pj_cstr(&remote_uri, contact->uri);
    } else {
       pj_cstr(&remote_uri, uri);
    }
    pool = pjsip_endpt_create_pool(ast_sip_get_pjsip_endpoint(), "Outbound request", 256, 256);
    if (!pool) {
       ast_log(LOG_ERROR, "Unable to create PJLIB memory pool\n");
       return -1;
    }
    sip_uri = pjsip_parse_uri(pool, remote_uri.ptr, remote_uri.slen, 0);
    if (!sip_uri || (!PJSIP_URI_SCHEME_IS_SIP(sip_uri) && !PJSIP_URI_SCHEME_IS_SIPS(sip_uri))) {
       ast_log(LOG_ERROR, "Unable to create outbound %.*s request to endpoint %s as URI '%s' is not valid\n",
          (int) pj_strlen(&method->name), pj_strbuf(&method->name),
          endpoint ? ast_sorcery_object_get_id(endpoint) : "<none>",
          pj_strbuf(&remote_uri));
       pjsip_endpt_release_pool(ast_sip_get_pjsip_endpoint(), pool);
       return -1;
    }
    ast_sip_set_tpselector_from_ep_or_uri(endpoint, pjsip_uri_get_uri(sip_uri), &selector);
    fromuser = endpoint ? (!ast_strlen_zero(endpoint->fromuser) ? endpoint->fromuser : ast_sorcery_object_get_id(endpoint)) : NULL;
    if (sip_dialog_create_from(pool, &from, fromuser,
             endpoint ? endpoint->fromdomain : NULL, &remote_uri, &selector)) {
       ast_log(LOG_ERROR, "Unable to create From header for %.*s request to endpoint %s\n",
             (int) pj_strlen(&method->name), pj_strbuf(&method->name),
             endpoint ? ast_sorcery_object_get_id(endpoint) : "<none>");
       pjsip_endpt_release_pool(ast_sip_get_pjsip_endpoint(), pool);
       ast_sip_tpselector_unref(&selector);
       return -1;
    }
    if (pjsip_endpt_create_request(ast_sip_get_pjsip_endpoint(), method, &remote_uri,
          &from, &remote_uri, &from, NULL, -1, NULL, tdata) != PJ_SUCCESS) {
       ast_log(LOG_ERROR, "Unable to create outbound %.*s request to endpoint %s\n",
             (int) pj_strlen(&method->name), pj_strbuf(&method->name),
             endpoint ? ast_sorcery_object_get_id(endpoint) : "<none>");
       pjsip_endpt_release_pool(ast_sip_get_pjsip_endpoint(), pool);
       ast_sip_tpselector_unref(&selector);
       return -1;
    }
    pjsip_tx_data_set_transport(*tdata, &selector);
    ast_sip_tpselector_unref(&selector);
    if (endpoint && !ast_strlen_zero(endpoint->contact_user)){
       pjsip_contact_hdr *contact_hdr;
       pjsip_sip_uri *contact_uri;
       static const pj_str_t HCONTACT = { "Contact", 7 };
       static const pj_str_t HCONTACTSHORT = { "m", 1 };
       contact_hdr = pjsip_msg_find_hdr_by_names((*tdata)->msg, &HCONTACT, &HCONTACTSHORT, NULL);
       if (contact_hdr) {
          contact_uri = pjsip_uri_get_uri(contact_hdr->uri);
          pj_strdup2((*tdata)->pool, &contact_uri->user, endpoint->contact_user);
       }
    }
    /* Add the user=phone parameter if applicable */
    ast_sip_add_usereqphone(endpoint, (*tdata)->pool, (*tdata)->msg->line.req.uri);
    /* If an outbound proxy is specified on the endpoint apply it to this request */
    if (endpoint && !ast_strlen_zero(endpoint->outbound_proxy) &&
       ast_sip_set_outbound_proxy((*tdata), endpoint->outbound_proxy)) {
       ast_log(LOG_ERROR, "Unable to apply outbound proxy on request %.*s to endpoint %s as outbound proxy URI '%s' is not valid\n",
          (int) pj_strlen(&method->name), pj_strbuf(&method->name), ast_sorcery_object_get_id(endpoint),
          endpoint->outbound_proxy);
       pjsip_endpt_release_pool(ast_sip_get_pjsip_endpoint(), pool);
       return -1;
    }
    ast_sip_mod_data_set((*tdata)->pool, (*tdata)->mod_data, supplement_module.id, MOD_DATA_CONTACT, ao2_bump(contact));
    /* We can release this pool since request creation copied all the necessary
     * data into the outbound request's pool
     */
    pjsip_endpt_release_pool(ast_sip_get_pjsip_endpoint(), pool);
    return 0;
 }
do_cli_dump_endpt()
static int do_cli_dump_endpt (void * v_a) static
Definition at line 3558 of file res_pjsip.c.
References a, ast_cli_args::argc, ast_pjproject_log_intercept_begin(), ast_pjproject_log_intercept_end(), ast_sip_get_pjsip_endpoint(), and ast_cli_args::fd.
Referenced by cli_dump_endpt().
 {
    struct ast_cli_args *a = v_a;
    ast_pjproject_log_intercept_begin(a->fd);
    pjsip_endpt_dump(ast_sip_get_pjsip_endpoint(), a->argc == 4 ? PJ_TRUE : PJ_FALSE);
    ast_pjproject_log_intercept_end();
    return 0;
 }
does_method_match()
static pj_bool_t does_method_match (const pj_str_t * message_method, const char * supplement_method) static
Definition at line 4554 of file res_pjsip.c.
References ast_strlen_zero, and method.
Referenced by ast_sip_send_out_of_dialog_request(), send_request_cb(), supplement_on_rx_request(), and supplement_outgoing_response().
 {
    pj_str_t method;
    if (ast_strlen_zero(supplement_method)) {
       return PJ_TRUE;
    }
    pj_cstr(&method, supplement_method);
    return pj_stristr(&method, message_method) ? PJ_TRUE : PJ_FALSE;
 }
endpt_send_request()
static pj_status_t endpt_send_request (struct ast_sip_endpoint * endpoint, pjsip_tx_data * tdata, pj_int32_t timeout, void * token, pjsip_endpt_send_callback cb) static
Definition at line 4751 of file res_pjsip.c.
References ao2_alloc, ao2_lock, ao2_ref, ao2_t_ref, ao2_unlock, ast_debug, ast_log, ast_sip_get_pjsip_endpoint(), ast_sorcery_object_get_id(), send_request_wrapper::callback, send_request_wrapper::cb_called, endpt_send_request_cb(), LOG_ERROR, NULL, send_request_wrapper::send_cb_called, send_request_timer_callback(), send_request_wrapper_destructor(), send_request_wrapper::tdata, timeout, send_request_wrapper::timeout, send_request_wrapper::timeout_timer, TIMEOUT_TIMER2, TIMER_INACTIVE, and send_request_wrapper::token.
Referenced by ast_sip_send_out_of_dialog_request(), and check_request_status().
 {
    struct send_request_wrapper *req_wrapper;
    pj_status_t ret_val;
    pjsip_endpoint *endpt = ast_sip_get_pjsip_endpoint();
    if (!cb && token) {
       /* Silly.  Without a callback we cannot do anything with token. */
       pjsip_tx_data_dec_ref(tdata);
       return PJ_EINVAL;
    }
    /* Create wrapper to detect if the callback was actually called on an error. */
    req_wrapper = ao2_alloc(sizeof(*req_wrapper), send_request_wrapper_destructor);
    if (!req_wrapper) {
       pjsip_tx_data_dec_ref(tdata);
       return PJ_ENOMEM;
    }
    ast_debug(2, "%p: Wrapper created\n", req_wrapper);
    req_wrapper->token = token;
    req_wrapper->callback = cb;
    req_wrapper->timeout = timeout;
    req_wrapper->timeout_timer = NULL;
    req_wrapper->tdata = tdata;
    /* Add a reference to tdata.  The wrapper destructor cleans it up. */
    pjsip_tx_data_add_ref(tdata);
    if (timeout > 0) {
       pj_time_val timeout_timer_val = { timeout / 1000, timeout % 1000 };
       req_wrapper->timeout_timer = PJ_POOL_ALLOC_T(tdata->pool, pj_timer_entry);
       ast_debug(2, "%p: Set timer to %d msec\n", req_wrapper, timeout);
       pj_timer_entry_init(req_wrapper->timeout_timer, TIMEOUT_TIMER2,
          req_wrapper, send_request_timer_callback);
       /* We need to insure that the wrapper and tdata are available if/when the
        * timer callback is executed.
        */
       ao2_ref(req_wrapper, +1);
       ret_val = pj_timer_heap_schedule(pjsip_endpt_get_timer_heap(endpt),
          req_wrapper->timeout_timer, &timeout_timer_val);
       if (ret_val != PJ_SUCCESS) {
          ast_log(LOG_ERROR,
             "Failed to set timer.  Not sending %.*s request to endpoint %s.\n",
             (int) pj_strlen(&tdata->msg->line.req.method.name),
             pj_strbuf(&tdata->msg->line.req.method.name),
             endpoint ? ast_sorcery_object_get_id(endpoint) : "<unknown>");
          ao2_t_ref(req_wrapper, -2, "Drop timer and routine ref");
          pjsip_tx_data_dec_ref(tdata);
          return ret_val;
       }
    }
    /* We need to insure that the wrapper and tdata are available when the
     * transaction callback is executed.
     */
    ao2_ref(req_wrapper, +1);
    ret_val = pjsip_endpt_send_request(endpt, tdata, -1, req_wrapper, endpt_send_request_cb);
    if (ret_val != PJ_SUCCESS) {
       char errmsg[PJ_ERR_MSG_SIZE];
       if (!req_wrapper->send_cb_called) {
          /* endpt_send_request_cb is not expected to ever be called now. */
          ao2_ref(req_wrapper, -1);
       }
       /* Complain of failure to send the request. */
       pj_strerror(ret_val, errmsg, sizeof(errmsg));
       ast_log(LOG_ERROR, "Error %d '%s' sending %.*s request to endpoint %s\n",
          (int) ret_val, errmsg, (int) pj_strlen(&tdata->msg->line.req.method.name),
          pj_strbuf(&tdata->msg->line.req.method.name),
          endpoint ? ast_sorcery_object_get_id(endpoint) : "<unknown>");
       if (timeout > 0) {
          int timers_cancelled;
          ao2_lock(req_wrapper);
          timers_cancelled = pj_timer_heap_cancel_if_active(
             pjsip_endpt_get_timer_heap(endpt),
             req_wrapper->timeout_timer, TIMER_INACTIVE);
          if (timers_cancelled > 0) {
             ao2_ref(req_wrapper, -1);
          }
          /* Was the callback called? */
          if (req_wrapper->cb_called) {
             /*
              * Yes so we cannot report any error.  The callback
              * has already freed any resources associated with
              * token.
              */
             ret_val = PJ_SUCCESS;
          } else {
             /*
              * No so we claim it is called so our caller can free
              * any resources associated with token because of
              * failure.
              */
             req_wrapper->cb_called = 1;
          }
          ao2_unlock(req_wrapper);
       } else if (req_wrapper->cb_called) {
          /*
           * We cannot report any error.  The callback has
           * already freed any resources associated with
           * token.
           */
          ret_val = PJ_SUCCESS;
       }
    }
    ao2_ref(req_wrapper, -1);
    return ret_val;
 }
endpt_send_request_cb()
static void endpt_send_request_cb (void * token, pjsip_event * e) static
Definition at line 4628 of file res_pjsip.c.
References ao2_lock, ao2_ref, ao2_unlock, ast_debug, ast_sip_get_pjsip_endpoint(), send_request_wrapper::callback, send_request_wrapper::cb_called, send_request_wrapper::send_cb_called, send_request_wrapper::timeout_timer, TIMEOUT_TIMER2, TIMER_INACTIVE, and send_request_wrapper::token.
Referenced by endpt_send_request().
 {
    struct send_request_wrapper *req_wrapper = token;
    unsigned int cb_called;
    /*
     * Needed because we cannot otherwise tell if this callback was
     * called when pjsip_endpt_send_request() returns error.
     */
    req_wrapper->send_cb_called = 1;
    if (e->body.tsx_state.type == PJSIP_EVENT_TIMER) {
       ast_debug(2, "%p: PJSIP tsx timer expired\n", req_wrapper);
       if (req_wrapper->timeout_timer
          && req_wrapper->timeout_timer->id != TIMEOUT_TIMER2) {
          ast_debug(3, "%p: Timeout already handled\n", req_wrapper);
          ao2_ref(req_wrapper, -1);
          return;
       }
    } else {
       ast_debug(2, "%p: PJSIP tsx response received\n", req_wrapper);
    }
    ao2_lock(req_wrapper);
    /* It's possible that our own timer was already processing while
     * we were waiting on the lock so check the timer id.  If it's
     * still TIMER2 then we still need to process.
     */
    if (req_wrapper->timeout_timer
       && req_wrapper->timeout_timer->id == TIMEOUT_TIMER2) {
       int timers_cancelled = 0;
       ast_debug(3, "%p: Cancelling timer\n", req_wrapper);
       timers_cancelled = pj_timer_heap_cancel_if_active(
          pjsip_endpt_get_timer_heap(ast_sip_get_pjsip_endpoint()),
          req_wrapper->timeout_timer, TIMER_INACTIVE);
       if (timers_cancelled > 0) {
          /* If the timer was cancelled the callback will never run so
           * clean up its reference to the wrapper.
           */
          ast_debug(3, "%p: Timer cancelled\n", req_wrapper);
          ao2_ref(req_wrapper, -1);
       } else {
          /*
           * If it wasn't cancelled, it MAY be in the callback already
           * waiting on the lock.  When we release the lock, it will
           * now know not to proceed.
           */
          ast_debug(3, "%p: Timer already expired\n", req_wrapper);
       }
    }
    cb_called = req_wrapper->cb_called;
    req_wrapper->cb_called = 1;
    ao2_unlock(req_wrapper);
    /* It's possible that our own timer expired and called the callbacks
     * so no need to call them again.
     */
    if (!cb_called && req_wrapper->callback) {
       req_wrapper->callback(req_wrapper->token, e);
       ast_debug(2, "%p: Callbacks executed\n", req_wrapper);
    }
    ao2_ref(req_wrapper, -1);
 }
get_pjsip_method()
static const pjsip_method* get_pjsip_method (const char * method) static
Definition at line 4351 of file res_pjsip.c.
References ARRAY_LEN, methods, and NULL.
Referenced by ast_sip_create_request().
 {
    int i;
    for (i = 0; i < ARRAY_LEN(methods); ++i) {
       if (!strcmp(method, methods[i].method)) {
          return methods[i].pmethod;
       }
    }
    return NULL;
 }
load_module()
static int load_module (void) static
Definition at line 5810 of file res_pjsip.c.
References ARRAY_LEN, ast_cli_register_multiple, ast_log, AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, ast_res_pjsip_init_message_filter(), ast_res_pjsip_init_options_handling(), ast_res_pjsip_initialize_configuration(), ast_res_pjsip_preinit_options_handling(), ast_serializer_pool_create(), ast_serializer_pool_destroy(), ast_sip_destroy_scheduler(), ast_sip_initialize_distributor(), ast_sip_initialize_dns(), ast_sip_initialize_global_headers(), ast_sip_initialize_resolver(), ast_sip_initialize_scheduler(), ast_sip_initialize_system(), ast_sip_initialize_transport_events(), ast_sip_initialize_transport_management(), ast_sip_register_service(), AST_TEST_REGISTER, ast_threadpool_create(), ast_threadpool_shutdown(), error(), load_pjsip(), LOG_ERROR, LOG_WARNING, NULL, SERIALIZER_POOL_SIZE, sip_get_threadpool_options(), sip_thread_start(), supplement_module, ast_threadpool_options::thread_start, and unload_pjsip().
Referenced by unload_module().
 {
    struct ast_threadpool_options options;
    /* pjproject and config_system need to be initialized before all else */
    if (pj_init() != PJ_SUCCESS) {
       return AST_MODULE_LOAD_DECLINE;
    }
    if (pjlib_util_init() != PJ_SUCCESS) {
       goto error;
    }
    /* Register PJMEDIA error codes for SDP parsing errors */
    if (pj_register_strerror(PJMEDIA_ERRNO_START, PJ_ERRNO_SPACE_SIZE, pjmedia_strerror)
       != PJ_SUCCESS) {
       ast_log(LOG_WARNING, "Failed to register pjmedia error codes.  Codes will not be decoded.\n");
    }
    if (ast_sip_initialize_system()) {
       ast_log(LOG_ERROR, "Failed to initialize SIP 'system' configuration section. Aborting load\n");
       goto error;
    }
    /* The serializer needs threadpool and threadpool needs pjproject to be initialized so it's next */
    sip_get_threadpool_options(&options);
    options.thread_start = sip_thread_start;
    sip_threadpool = ast_threadpool_create("pjsip", NULL, &options);
    if (!sip_threadpool) {
       goto error;
    }
    sip_serializer_pool = ast_serializer_pool_create(
       "pjsip/default", SERIALIZER_POOL_SIZE, sip_threadpool, -1);
    if (!sip_serializer_pool) {
       ast_log(LOG_ERROR, "Failed to create SIP serializer pool. Aborting load\n");
       goto error;
    }
    if (ast_sip_initialize_scheduler()) {
       ast_log(LOG_ERROR, "Failed to start scheduler. Aborting load\n");
       goto error;
    }
    /* Now load all the pjproject infrastructure. */
    if (load_pjsip()) {
       goto error;
    }
    if (ast_sip_initialize_transport_events()) {
       ast_log(LOG_ERROR, "Failed to initialize SIP transport monitor. Aborting load\n");
       goto error;
    }
    ast_sip_initialize_dns();
    ast_sip_initialize_global_headers();
    if (ast_res_pjsip_preinit_options_handling()) {
       ast_log(LOG_ERROR, "Failed to pre-initialize OPTIONS handling. Aborting load\n");
       goto error;
    }
    if (ast_res_pjsip_initialize_configuration()) {
       ast_log(LOG_ERROR, "Failed to initialize SIP configuration. Aborting load\n");
       goto error;
    }
    ast_sip_initialize_resolver();
    ast_sip_initialize_dns();
    if (ast_sip_initialize_transport_management()) {
       ast_log(LOG_ERROR, "Failed to initialize SIP transport management. Aborting load\n");
       goto error;
    }
    if (ast_sip_initialize_distributor()) {
       ast_log(LOG_ERROR, "Failed to register distributor module. Aborting load\n");
       goto error;
    }
    if (ast_sip_register_service(&supplement_module)) {
       ast_log(LOG_ERROR, "Failed to initialize supplement hooks. Aborting load\n");
       goto error;
    }
    if (ast_res_pjsip_init_options_handling(0)) {
       ast_log(LOG_ERROR, "Failed to initialize OPTIONS handling. Aborting load\n");
       goto error;
    }
    if (ast_res_pjsip_init_message_filter()) {
       ast_log(LOG_ERROR, "Failed to initialize message IP updating. Aborting load\n");
       goto error;
    }
    ast_cli_register_multiple(cli_commands, ARRAY_LEN(cli_commands));
    AST_TEST_REGISTER(xml_sanitization_end_null);
    AST_TEST_REGISTER(xml_sanitization_exceeds_buffer);
    return AST_MODULE_LOAD_SUCCESS;
 error:
    unload_pjsip(NULL);
    /* These functions all check for NULLs and are safe to call at any time */
    ast_sip_destroy_scheduler();
    ast_serializer_pool_destroy(sip_serializer_pool);
    ast_threadpool_shutdown(sip_threadpool);
    return AST_MODULE_LOAD_DECLINE;
 }
load_pjsip()
static int load_pjsip (void) static
Definition at line 5744 of file res_pjsip.c.
References ast_log, AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, ast_pjproject_caching_pool_init(), ast_pjsip_endpoint, ast_verb, error(), host_ip_ipv4, host_ip_ipv4_string, host_ip_ipv6, host_ip_ipv6_string, LOG_ERROR, monitor_thread_exec(), never_called_res_pjsip(), NULL, remove_request_headers(), and status.
Referenced by load_module().
 {
    const unsigned int flags = 0; /* no port, no brackets */
    pj_status_t status;
    /* The third parameter is just copied from
     * example code from PJLIB. This can be adjusted
     * if necessary.
     */
    ast_pjproject_caching_pool_init(&caching_pool, NULL, 1024 * 1024);
    if (pjsip_endpt_create(&caching_pool.factory, "SIP", &ast_pjsip_endpoint) != PJ_SUCCESS) {
       ast_log(LOG_ERROR, "Failed to create PJSIP endpoint structure. Aborting load\n");
       goto error;
    }
    /* PJSIP will automatically try to add a Max-Forwards header. Since we want to control that,
     * we need to stop PJSIP from doing it automatically
     */
    remove_request_headers(ast_pjsip_endpoint);
    memory_pool = pj_pool_create(&caching_pool.factory, "SIP", 1024, 1024, NULL);
    if (!memory_pool) {
       ast_log(LOG_ERROR, "Failed to create memory pool for SIP. Aborting load\n");
       goto error;
    }
    if (!pj_gethostip(pj_AF_INET(), &host_ip_ipv4)) {
       pj_sockaddr_print(&host_ip_ipv4, host_ip_ipv4_string, sizeof(host_ip_ipv4_string), flags);
       ast_verb(3, "Local IPv4 address determined to be: %s\n", host_ip_ipv4_string);
    }
    if (!pj_gethostip(pj_AF_INET6(), &host_ip_ipv6)) {
       pj_sockaddr_print(&host_ip_ipv6, host_ip_ipv6_string, sizeof(host_ip_ipv6_string), flags);
       ast_verb(3, "Local IPv6 address determined to be: %s\n", host_ip_ipv6_string);
    }
    pjsip_tsx_layer_init_module(ast_pjsip_endpoint);
    pjsip_ua_init_module(ast_pjsip_endpoint, NULL);
    monitor_continue = 1;
    status = pj_thread_create(memory_pool, "SIP", (pj_thread_proc *) &monitor_thread_exec,
          NULL, PJ_THREAD_DEFAULT_STACK_SIZE * 2, 0, &monitor_thread);
    if (status != PJ_SUCCESS) {
       ast_log(LOG_ERROR, "Failed to start SIP monitor thread. Aborting load\n");
       goto error;
    }
    return AST_MODULE_LOAD_SUCCESS;
 error:
    return AST_MODULE_LOAD_DECLINE;
 }
monitor_thread_exec()
static void* monitor_thread_exec (void * endpt) static
Definition at line 5277 of file res_pjsip.c.
References ast_pjsip_endpoint, and NULL.
Referenced by load_pjsip().
 {
    while (monitor_continue) {
       const pj_time_val delay = {0, 10};
       pjsip_endpt_handle_events(ast_pjsip_endpoint, &delay);
    }
    return NULL;
 }
never_called_res_pjsip()
void never_called_res_pjsip (void)
Definition at line 5805 of file res_pjsip.c.
References NULL.
Referenced by load_pjsip().
 {
    pjmedia_strerror(0, NULL, 0);
 }
register_service()
static int register_service (void * data) static
Definition at line 3300 of file res_pjsip.c.
References ast_debug, ast_log, ast_pjsip_endpoint, and LOG_ERROR.
Referenced by ast_sip_register_service().
 {
    pjsip_module **module = data;
    if (!ast_pjsip_endpoint) {
       ast_log(LOG_ERROR, "There is no PJSIP endpoint. Unable to register services\n");
       return -1;
    }
    if (pjsip_endpt_register_module(ast_pjsip_endpoint, *module) != PJ_SUCCESS) {
       ast_log(LOG_ERROR, "Unable to register module %.*s\n", (int) pj_strlen(&(*module)->name), pj_strbuf(&(*module)->name));
       return -1;
    }
    ast_debug(1, "Registered SIP service %.*s (%p)\n", (int) pj_strlen(&(*module)->name), pj_strbuf(&(*module)->name), *module);
    return 0;
 }
reload_configuration_task()
static int reload_configuration_task (void * obj) static
Definition at line 5692 of file res_pjsip.c.
References ast_res_pjsip_init_options_handling(), ast_res_pjsip_reload_configuration(), and ast_sip_initialize_dns().
Referenced by reload_module().
 {
    ast_res_pjsip_reload_configuration();
    ast_res_pjsip_init_options_handling(1);
    ast_sip_initialize_dns();
    return 0;
 }
reload_module()
static int reload_module (void) static
Definition at line 5923 of file res_pjsip.c.
References ast_log, ast_sip_push_task_wait_servant(), LOG_WARNING, NULL, and reload_configuration_task().
Referenced by unload_module().
 {
    /*
     * We must wait for the reload to complete so multiple
     * reloads cannot happen at the same time.
     */
    if (ast_sip_push_task_wait_servant(NULL, reload_configuration_task, NULL)) {
       ast_log(LOG_WARNING, "Failed to reload PJSIP\n");
       return -1;
    }
    return 0;
 }
remove_request_headers()
static void remove_request_headers (pjsip_endpoint * endpt) static
Definition at line 5613 of file res_pjsip.c.
References request_headers.
Referenced by load_pjsip().
 {
    const pjsip_hdr *request_headers = pjsip_endpt_get_request_headers(endpt);
    pjsip_hdr *iter = request_headers->next;
    while (iter != request_headers) {
       pjsip_hdr *to_erase = iter;
       iter = iter->next;
       pj_list_erase(to_erase);
    }
 }
send_in_dialog_request()
static int send_in_dialog_request (pjsip_tx_data * tdata, struct pjsip_dialog * dlg) static
Definition at line 4545 of file res_pjsip.c.
References ast_log, LOG_WARNING, and NULL.
Referenced by ast_sip_send_request().
 {
    if (pjsip_dlg_send_request(dlg, tdata, -1, NULL) != PJ_SUCCESS) {
       ast_log(LOG_WARNING, "Unable to send in-dialog request.\n");
       return -1;
    }
    return 0;
 }
send_request_cb()
static void send_request_cb (void * token, pjsip_event * e) static
Definition at line 4937 of file res_pjsip.c.
References ao2_ref, AST_LIST_TRAVERSE, ast_log, AST_RWLIST_RDLOCK, AST_RWLIST_UNLOCK, send_request_data::callback, challenge(), check_request_status(), does_method_match(), send_request_data::endpoint, ast_sip_supplement::incoming_response, LOG_ERROR, ast_sip_supplement::method, ast_sip_supplement::next, and send_request_data::token.
Referenced by ast_sip_failover_request().
 {
    struct send_request_data *req_data = token;
    pjsip_rx_data *challenge;
    struct ast_sip_supplement *supplement;
    if (e->type == PJSIP_EVENT_TSX_STATE) {
       switch(e->body.tsx_state.type) {
       case PJSIP_EVENT_TRANSPORT_ERROR:
       case PJSIP_EVENT_TIMER:
          /*
           * Check the request status on transport error or timeout. A transport
           * error can occur when a TCP socket closes and that can be the result
           * of a 503. Also we may need to failover on a timeout (408).
           */
          if (check_request_status(req_data, e)) {
             return;
          }
          break;
       case PJSIP_EVENT_RX_MSG:
          challenge = e->body.tsx_state.src.rdata;
          /*
           * Call any supplements that want to know about a response
           * with any received data.
           */
          AST_RWLIST_RDLOCK(&supplements);
          AST_LIST_TRAVERSE(&supplements, supplement, next) {
             if (supplement->incoming_response
                && does_method_match(&challenge->msg_info.cseq->method.name,
                   supplement->method)) {
                supplement->incoming_response(req_data->endpoint, challenge);
             }
          }
          AST_RWLIST_UNLOCK(&supplements);
          if (check_request_status(req_data, e)) {
             /*
              * Request with challenge response or failover sent.
              * Passed our req_data ref to the new request.
              */
             return;
          }
          break;
       default:
          ast_log(LOG_ERROR, "Unexpected PJSIP event %u\n", e->body.tsx_state.type);
          break;
       }
    }
    if (req_data->callback) {
       req_data->callback(req_data->token, e);
    }
    ao2_ref(req_data, -1);
 }
send_request_data_alloc()
static struct send_request_data* send_request_data_alloc (struct ast_sip_endpoint * endpoint, void * token, void(*)(void *token, pjsip_event *e) callback) static
Definition at line 4589 of file res_pjsip.c.
References AO2_ALLOC_OPT_LOCK_NOLOCK, ao2_alloc_options, ao2_bump, send_request_data::callback, send_request_data::endpoint, NULL, send_request_data_destroy(), and send_request_data::token.
Referenced by ast_sip_send_out_of_dialog_request().
 {
    struct send_request_data *req_data;
    req_data = ao2_alloc_options(sizeof(*req_data), send_request_data_destroy,
       AO2_ALLOC_OPT_LOCK_NOLOCK);
    if (!req_data) {
       return NULL;
    }
    req_data->endpoint = ao2_bump(endpoint);
    req_data->token = token;
    req_data->callback = callback;
    return req_data;
 }
send_request_data_destroy()
static void send_request_data_destroy (void * obj) static
Definition at line 4582 of file res_pjsip.c.
References ao2_cleanup, and send_request_data::endpoint.
Referenced by send_request_data_alloc().
 {
    struct send_request_data *req_data = obj;
    ao2_cleanup(req_data->endpoint);
 }
send_request_timer_callback()
static void send_request_timer_callback (pj_timer_heap_t * theap, pj_timer_entry * entry) static
Definition at line 4703 of file res_pjsip.c.
References ao2_lock, ao2_ref, ao2_unlock, ast_debug, send_request_wrapper::callback, send_request_wrapper::cb_called, send_request_wrapper::tdata, send_request_wrapper::timeout, TIMEOUT_TIMER2, TIMER_INACTIVE, and send_request_wrapper::token.
Referenced by endpt_send_request().
 {
    struct send_request_wrapper *req_wrapper = entry->user_data;
    unsigned int cb_called;
    ast_debug(2, "%p: Internal tsx timer expired after %d msec\n",
       req_wrapper, req_wrapper->timeout);
    ao2_lock(req_wrapper);
    /*
     * If the id is not TIMEOUT_TIMER2 then the timer was cancelled
     * before we got the lock or it was already handled so just clean up.
     */
    if (entry->id != TIMEOUT_TIMER2) {
       ao2_unlock(req_wrapper);
       ast_debug(3, "%p: Timeout already handled\n", req_wrapper);
       ao2_ref(req_wrapper, -1);
       return;
    }
    entry->id = TIMER_INACTIVE;
    ast_debug(3, "%p: Timer handled here\n", req_wrapper);
    cb_called = req_wrapper->cb_called;
    req_wrapper->cb_called = 1;
    ao2_unlock(req_wrapper);
    if (!cb_called && req_wrapper->callback) {
       pjsip_event event;
       PJSIP_EVENT_INIT_TX_MSG(event, req_wrapper->tdata);
       event.body.tsx_state.type = PJSIP_EVENT_TIMER;
       req_wrapper->callback(req_wrapper->token, &event);
       ast_debug(2, "%p: Callbacks executed\n", req_wrapper);
    }
    ao2_ref(req_wrapper, -1);
 }
send_request_wrapper_destructor()
static void send_request_wrapper_destructor (void * obj) static
Definition at line 4743 of file res_pjsip.c.
References ast_debug, and send_request_wrapper::tdata.
Referenced by endpt_send_request().
 {
    struct send_request_wrapper *req_wrapper = obj;
    pjsip_tx_data_dec_ref(req_wrapper->tdata);
    ast_debug(2, "%p: wrapper destroyed\n", req_wrapper);
 }
sip_dialog_create_from()
static int sip_dialog_create_from (pj_pool_t * pool, pj_str_t * from, const char * user, const char * domain, const pj_str_t * target, pjsip_tpselector * selector) static
Definition at line 3813 of file res_pjsip.c.
References ast_sip_get_default_from_user(), ast_sip_get_disable_multi_domain(), ast_sip_get_pjsip_endpoint(), ast_strlen_zero, tmp(), and type.
Referenced by ast_sip_create_dialog_uac(), and create_out_of_dialog_request().
 {
    pj_str_t tmp, local_addr;
    pjsip_uri *uri;
    pjsip_sip_uri *sip_uri;
    pjsip_transport_type_e type;
    int local_port;
    char default_user[PJSIP_MAX_URL_SIZE];
    if (ast_strlen_zero(user)) {
       ast_sip_get_default_from_user(default_user, sizeof(default_user));
       user = default_user;
    }
    /* Parse the provided target URI so we can determine what transport it will end up using */
    pj_strdup_with_null(pool, &tmp, target);
    if (!(uri = pjsip_parse_uri(pool, tmp.ptr, tmp.slen, 0)) ||
        (!PJSIP_URI_SCHEME_IS_SIP(uri) && !PJSIP_URI_SCHEME_IS_SIPS(uri))) {
       return -1;
    }
    sip_uri = pjsip_uri_get_uri(uri);
    /* Determine the transport type to use */
    type = pjsip_transport_get_type_from_name(&sip_uri->transport_param);
    if (PJSIP_URI_SCHEME_IS_SIPS(sip_uri)) {
       if (type == PJSIP_TRANSPORT_UNSPECIFIED
          || !(pjsip_transport_get_flag_from_type(type) & PJSIP_TRANSPORT_SECURE)) {
          type = PJSIP_TRANSPORT_TLS;
       }
    } else if (!sip_uri->transport_param.slen) {
       type = PJSIP_TRANSPORT_UDP;
    } else if (type == PJSIP_TRANSPORT_UNSPECIFIED) {
       return -1;
    }
    /* If the host is IPv6 turn the transport into an IPv6 version */
    if (pj_strchr(&sip_uri->host, ':')) {
       type |= PJSIP_TRANSPORT_IPV6;
    }
    /* In multidomain scenario, username may contain @ with domain info */
    if (!ast_sip_get_disable_multi_domain() && strchr(user, '@')) {
       from->ptr = pj_pool_alloc(pool, PJSIP_MAX_URL_SIZE);
       from->slen = pj_ansi_snprintf(from->ptr, PJSIP_MAX_URL_SIZE,
             "<sip:%s%s%s>",
             user,
             (type != PJSIP_TRANSPORT_UDP && type != PJSIP_TRANSPORT_UDP6) ? ";transport=" : "",
             (type != PJSIP_TRANSPORT_UDP && type != PJSIP_TRANSPORT_UDP6) ? pjsip_transport_get_type_name(type) : "");
       return 0;
    }
    if (!ast_strlen_zero(domain)) {
       from->ptr = pj_pool_alloc(pool, PJSIP_MAX_URL_SIZE);
       from->slen = pj_ansi_snprintf(from->ptr, PJSIP_MAX_URL_SIZE,
             "<sip:%s@%s%s%s>",
             user,
             domain,
             (type != PJSIP_TRANSPORT_UDP && type != PJSIP_TRANSPORT_UDP6) ? ";transport=" : "",
             (type != PJSIP_TRANSPORT_UDP && type != PJSIP_TRANSPORT_UDP6) ? pjsip_transport_get_type_name(type) : "");
       return 0;
    }
    /* Get the local bound address for the transport that will be used when communicating with the provided URI */
    if (pjsip_tpmgr_find_local_addr(pjsip_endpt_get_tpmgr(ast_sip_get_pjsip_endpoint()), pool, type, selector,
                            &local_addr, &local_port) != PJ_SUCCESS) {
       /* If no local address can be retrieved using the transport manager use the host one */
       pj_strdup(pool, &local_addr, pj_gethostname());
       local_port = pjsip_transport_get_default_port_for_type(PJSIP_TRANSPORT_UDP);
    }
    /* If IPv6 was specified in the transport, set the proper type */
    if (pj_strchr(&local_addr, ':')) {
       type |= PJSIP_TRANSPORT_IPV6;
    }
    from->ptr = pj_pool_alloc(pool, PJSIP_MAX_URL_SIZE);
    from->slen = pj_ansi_snprintf(from->ptr, PJSIP_MAX_URL_SIZE,
                   "<sip:%s@%s%.*s%s:%d%s%s>",
                   user,
                   (type & PJSIP_TRANSPORT_IPV6) ? "[" : "",
                   (int)local_addr.slen,
                   local_addr.ptr,
                   (type & PJSIP_TRANSPORT_IPV6) ? "]" : "",
                   local_port,
                   (type != PJSIP_TRANSPORT_UDP && type != PJSIP_TRANSPORT_UDP6) ? ";transport=" : "",
                   (type != PJSIP_TRANSPORT_UDP && type != PJSIP_TRANSPORT_UDP6) ? pjsip_transport_get_type_name(type) : "");
    return 0;
 }
sip_thread_start()
static void sip_thread_start (void) static
Definition at line 5296 of file res_pjsip.c.
References ast_log, ast_threadstorage_get(), desc, LOG_ERROR, pj_thread_storage, servant_id_storage, SIP_SERVANT_ID, and thread.
Referenced by load_module().
 {
    pj_thread_desc *desc;
    pj_thread_t *thread;
    uint32_t *servant_id;
    servant_id = ast_threadstorage_get(&servant_id_storage, sizeof(*servant_id));
    if (!servant_id) {
       ast_log(LOG_ERROR, "Could not set SIP servant ID in thread-local storage.\n");
       return;
    }
    *servant_id = SIP_SERVANT_ID;
    desc = ast_threadstorage_get(&pj_thread_storage, sizeof(pj_thread_desc));
    if (!desc) {
       ast_log(LOG_ERROR, "Could not get thread desc from thread-local storage. Expect awful things to occur\n");
       return;
    }
    pj_bzero(*desc, sizeof(*desc));
    if (pj_thread_register("Asterisk Thread", *desc, &thread) != PJ_SUCCESS) {
       ast_log(LOG_ERROR, "Couldn't register thread with PJLIB.\n");
    }
 }
stop_monitor_thread()
static void stop_monitor_thread (void) static
Definition at line 5286 of file res_pjsip.c.
Referenced by unload_pjsip().
 {
    monitor_continue = 0;
    pj_thread_join(monitor_thread);
 }
supplement_on_rx_request()
static pj_bool_t supplement_on_rx_request (pjsip_rx_data * rdata) static
Definition at line 5361 of file res_pjsip.c.
References ao2_cleanup, AST_LIST_TRAVERSE, ast_pjsip_rdata_get_endpoint(), AST_RWLIST_RDLOCK, AST_RWLIST_UNLOCK, does_method_match(), ast_sip_supplement::incoming_request, ast_sip_supplement::method, and ast_sip_supplement::next.
Referenced by create_in_dialog_request().
 {
    struct ast_sip_supplement *supplement;
    if (pjsip_rdata_get_dlg(rdata)) {
       return PJ_FALSE;
    }
    AST_RWLIST_RDLOCK(&supplements);
    AST_LIST_TRAVERSE(&supplements, supplement, next) {
       if (supplement->incoming_request
          && does_method_match(&rdata->msg_info.msg->line.req.method.name, supplement->method)) {
          struct ast_sip_endpoint *endpoint;
          endpoint = ast_pjsip_rdata_get_endpoint(rdata);
          supplement->incoming_request(endpoint, rdata);
          ao2_cleanup(endpoint);
       }
    }
    AST_RWLIST_UNLOCK(&supplements);
    return PJ_FALSE;
 }
supplement_outgoing_response()
static void supplement_outgoing_response (pjsip_tx_data * tdata, struct ast_sip_endpoint * sip_endpoint) static
Definition at line 5385 of file res_pjsip.c.
References ao2_cleanup, AST_LIST_TRAVERSE, AST_RWLIST_RDLOCK, AST_RWLIST_UNLOCK, ast_sip_message_apply_transport(), ast_sip_mod_data_get, ast_sip_mod_data_set, does_method_match(), ast_sip_supplement::method, MOD_DATA_CONTACT, NULL, ast_sip_supplement::outgoing_response, supplement_module, and ast_sip_endpoint::transport.
Referenced by ast_sip_send_response(), and ast_sip_send_stateful_response().
 {
    struct ast_sip_supplement *supplement;
    pjsip_cseq_hdr *cseq = pjsip_msg_find_hdr(tdata->msg, PJSIP_H_CSEQ, NULL);
    struct ast_sip_contact *contact = ast_sip_mod_data_get(tdata->mod_data, supplement_module.id, MOD_DATA_CONTACT);
    if (sip_endpoint) {
       ast_sip_message_apply_transport(sip_endpoint->transport, tdata);
    }
    AST_RWLIST_RDLOCK(&supplements);
    AST_LIST_TRAVERSE(&supplements, supplement, next) {
       if (supplement->outgoing_response && does_method_match(&cseq->method.name, supplement->method)) {
          supplement->outgoing_response(sip_endpoint, contact, tdata);
       }
    }
    AST_RWLIST_UNLOCK(&supplements);
    ast_sip_mod_data_set(tdata->pool, tdata->mod_data, supplement_module.id, MOD_DATA_CONTACT, NULL);
    ao2_cleanup(contact);
 }
sync_task()
static int sync_task (void * data) static
Definition at line 5156 of file res_pjsip.c.
References ast_cond_signal, ast_mutex_lock, ast_mutex_unlock, sync_task_data::complete, sync_task_data::cond, sync_task_data::fail, sync_task_data::lock, sync_task_data::task, and sync_task_data::task_data.
Referenced by ast_sip_push_task_wait().
 {
    struct sync_task_data *std = data;
    int ret;
    std->fail = std->task(std->task_data);
    /*
     * Once we unlock std->lock after signaling, we cannot access
     * std again.  The thread waiting within ast_sip_push_task_wait()
     * is free to continue and release its local variable (std).
     */
    ast_mutex_lock(&std->lock);
    std->complete = 1;
    ast_cond_signal(&std->cond);
    ret = std->fail;
    ast_mutex_unlock(&std->lock);
    return ret;
 }
uas_use_sips_contact()
static int uas_use_sips_contact (pjsip_rx_data * rdata) static
Determine if a SIPS Contact header is required.
This uses the guideline provided in RFC 3261 Section 12.1.1 to determine if the Contact header must be a sips: URI.
Parameters
rdata The incoming dialog-starting request
Return values
0 SIPS not required
1 SIPS required
Definition at line 4148 of file res_pjsip.c.
References ast_assert, and NULL.
Referenced by create_dialog_uas().
 {
    pjsip_rr_hdr *record_route;
    if (PJSIP_URI_SCHEME_IS_SIPS(rdata->msg_info.msg->line.req.uri)) {
       return 1;
    }
    record_route = pjsip_msg_find_hdr(rdata->msg_info.msg, PJSIP_H_RECORD_ROUTE, NULL);
    if (record_route) {
       if (PJSIP_URI_SCHEME_IS_SIPS(&record_route->name_addr)) {
          return 1;
       }
    } else {
       pjsip_contact_hdr *contact;
       contact = pjsip_msg_find_hdr(rdata->msg_info.msg, PJSIP_H_CONTACT, NULL);
       ast_assert(contact != NULL);
       if (PJSIP_URI_SCHEME_IS_SIPS(contact->uri)) {
          return 1;
       }
    }
    return 0;
 }
unload_module()
static int unload_module (void) static
Definition at line 5937 of file res_pjsip.c.
References ARRAY_LEN, ast_cli_unregister_multiple(), AST_MODFLAG_GLOBAL_SYMBOLS, AST_MODFLAG_LOAD_ORDER, AST_MODPRI_CHANNEL_DEPEND, AST_MODULE_INFO(), AST_MODULE_SUPPORT_CORE, ast_serializer_pool_destroy(), ast_sip_destroy_scheduler(), ast_sip_push_task_wait_servant(), AST_TEST_UNREGISTER, ast_threadpool_shutdown(), ASTERISK_GPL_KEY, load_module(), NULL, reload(), reload_module(), and unload_pjsip().
 {
    AST_TEST_UNREGISTER(xml_sanitization_end_null);
    AST_TEST_UNREGISTER(xml_sanitization_exceeds_buffer);
    ast_cli_unregister_multiple(cli_commands, ARRAY_LEN(cli_commands));
    /* The thread this is called from cannot call PJSIP/PJLIB functions,
     * so we have to push the work to the threadpool to handle
     */
    ast_sip_push_task_wait_servant(NULL, unload_pjsip, NULL);
    ast_sip_destroy_scheduler();
    ast_serializer_pool_destroy(sip_serializer_pool);
    ast_threadpool_shutdown(sip_threadpool);
    return 0;
 }
unload_pjsip()
static int unload_pjsip (void * data) static
Definition at line 5700 of file res_pjsip.c.
References ast_pjproject_caching_pool_destroy(), ast_pjsip_endpoint, ast_res_pjsip_cleanup_message_filter(), ast_res_pjsip_cleanup_options_handling(), ast_res_pjsip_destroy_configuration(), ast_sip_destroy_distributor(), ast_sip_destroy_global_headers(), ast_sip_destroy_system(), ast_sip_destroy_transport_events(), ast_sip_destroy_transport_management(), ast_sip_unregister_service(), memory_pool, NULL, stop_monitor_thread(), and supplement_module.
Referenced by load_module(), and unload_module().
 {
    /*
     * These calls need the pjsip endpoint and serializer to clean up.
     * If they're not set, then there's nothing to clean up anyway.
     */
    if (ast_pjsip_endpoint && sip_serializer_pool) {
       ast_res_pjsip_cleanup_options_handling();
       ast_res_pjsip_cleanup_message_filter();
       ast_sip_destroy_distributor();
       ast_sip_destroy_transport_management();
       ast_res_pjsip_destroy_configuration();
       ast_sip_destroy_system();
       ast_sip_destroy_global_headers();
       ast_sip_unregister_service(&supplement_module);
       ast_sip_destroy_transport_events();
    }
    if (monitor_thread) {
       stop_monitor_thread();
       monitor_thread = NULL;
    }
    if (memory_pool) {
       /* This mimics the behavior of pj_pool_safe_release
        * which was introduced in pjproject 2.6.
        */
       pj_pool_t *temp_pool = memory_pool;
       memory_pool = NULL;
       pj_pool_release(temp_pool);
    }
    ast_pjsip_endpoint = NULL;
    if (caching_pool.lock) {
       ast_pjproject_caching_pool_destroy(&caching_pool);
    }
    pj_shutdown();
    return 0;
 }
unregister_service()
static int unregister_service (void * data) static
Definition at line 3320 of file res_pjsip.c.
References ast_debug, and ast_pjsip_endpoint.
Referenced by ast_sip_unregister_service().
 {
    pjsip_module **module = data;
    if (!ast_pjsip_endpoint) {
       return -1;
    }
    pjsip_endpt_unregister_module(ast_pjsip_endpoint, *module);
    ast_debug(1, "Unregistered SIP service %.*s\n", (int) pj_strlen(&(*module)->name), pj_strbuf(&(*module)->name));
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_GLOBAL_SYMBOLS | AST_MODFLAG_LOAD_ORDER , .description = "Basic SIP resource" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .reload = reload_module, .load_pri = AST_MODPRI_CHANNEL_DEPEND - 5, .requires = "dnsmgr,res_pjproject,res_sorcery_config,res_sorcery_memory,res_sorcery_astdb", .optional_modules = "res_statsd", } static
Definition at line 5962 of file res_pjsip.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 5962 of file res_pjsip.c.
ast_pjsip_endpoint
pjsip_endpoint* ast_pjsip_endpoint static
Definition at line 3272 of file res_pjsip.c.
Referenced by ast_sip_get_pjsip_endpoint(), load_pjsip(), monitor_thread_exec(), register_service(), unload_pjsip(), and unregister_service().
caching_pool
pj_caching_pool caching_pool
Definition at line 5272 of file res_pjsip.c.
cli_commands
struct ast_cli_entry cli_commands[] static
Initial value:
= {
   { .handler =  cli_dump_endpt , .summary =  "Dump the res_pjsip endpt internals" ,},
   { .handler =  cli_show_settings , .summary =  "Show global and system configuration options" ,},
   { .handler =  cli_show_endpoint_identifiers , .summary =  "List registered endpoint identifiers" ,}
}
Definition at line 3671 of file res_pjsip.c.
endpoint_formatters
struct endpoint_formatters endpoint_formatters = { .first = NULL, .last = NULL, .lock = { PTHREAD_RWLOCK_INITIALIZER , NULL, {1, 0} } , }
endpoint_identifiers
struct endpoint_identifiers endpoint_identifiers = { .first = NULL, .last = NULL, .lock = { PTHREAD_RWLOCK_INITIALIZER , NULL, {1, 0} } , } static
host_ip_ipv4
pj_sockaddr host_ip_ipv4 static
Local host address for IPv4
Definition at line 3277 of file res_pjsip.c.
Referenced by ast_sip_get_host_ip(), and load_pjsip().
host_ip_ipv4_string
char host_ip_ipv4_string[PJ_INET6_ADDRSTRLEN] static
Local host address for IPv4 (string form)
Definition at line 3280 of file res_pjsip.c.
Referenced by ast_sip_get_host_ip(), ast_sip_get_host_ip_string(), and load_pjsip().
host_ip_ipv6
pj_sockaddr host_ip_ipv6 static
Local host address for IPv6
Definition at line 3283 of file res_pjsip.c.
Referenced by ast_sip_get_host_ip(), and load_pjsip().
host_ip_ipv6_string
char host_ip_ipv6_string[PJ_INET6_ADDRSTRLEN] static
Local host address for IPv6 (string form)
Definition at line 3286 of file res_pjsip.c.
Referenced by ast_sip_get_host_ip(), ast_sip_get_host_ip_string(), and load_pjsip().
info_method
const pjsip_method info_method = {PJSIP_OTHER_METHOD, {"INFO", 4} } static
Definition at line 4331 of file res_pjsip.c.
memory_pool
pj_pool_t* memory_pool
Definition at line 5273 of file res_pjsip.c.
Referenced by unload_pjsip().
message_method
const pjsip_method message_method = {PJSIP_OTHER_METHOD, {"MESSAGE", 7} } static
Definition at line 4332 of file res_pjsip.c.
method
const char* method
Definition at line 4335 of file res_pjsip.c.
Referenced by __sip_pretend_ack(), ast_ari_invoke(), ast_websocket_uri_cb(), delayed_request_alloc(), does_method_match(), has_supplement(), httpd_process_request(), ident_handler(), ident_to_str(), mark_method_allowed(), mark_method_unallowed(), mark_parsed_methods(), misdn_cfg_is_group_method(), res_sdp_crypto_parse_offer(), sip_endpoint_identifier_str2type(), sorcery_function_read(), and update_connected_line_information().
methods
struct { ... } methods[]
Referenced by get_auth_methods(), get_pjsip_method(), ident_to_str(), parse_allowed_methods(), and sorcery_function_read().
monitor_continue
int monitor_continue static
Definition at line 5275 of file res_pjsip.c.
monitor_thread
pj_thread_t* monitor_thread
Definition at line 5274 of file res_pjsip.c.
pj_thread_storage
struct ast_threadstorage pj_thread_storage = { .once = PTHREAD_ONCE_INIT , .key_init = __init_pj_thread_storage , .custom_init = NULL , } static
Definition at line 5292 of file res_pjsip.c.
Referenced by sip_thread_start().
pmethod
const pjsip_method* pmethod
Definition at line 4336 of file res_pjsip.c.
Referenced by ast_sip_create_request().
registered_authenticator
struct ast_sip_authenticator* registered_authenticator static
Definition at line 3336 of file res_pjsip.c.
registered_outbound_authenticator
struct ast_sip_outbound_authenticator* registered_outbound_authenticator static
Definition at line 3387 of file res_pjsip.c.
servant_id_storage
struct ast_threadstorage servant_id_storage = { .once = PTHREAD_ONCE_INIT , .key_init = __init_servant_id_storage , .custom_init = NULL , } static
Definition at line 5293 of file res_pjsip.c.
Referenced by ast_sip_thread_is_servant(), and sip_thread_start().
sip_serializer_pool
struct ast_serializer_pool* sip_serializer_pool static
Pool of serializers to use if not supplied.
Definition at line 3270 of file res_pjsip.c.
sip_threadpool
struct ast_threadpool* sip_threadpool static
Definition at line 3274 of file res_pjsip.c.
Referenced by ast_sip_threadpool().
supplement_module
pjsip_module supplement_module static
Definition at line 4373 of file res_pjsip.c.
Referenced by ast_sip_create_response(), ast_sip_send_out_of_dialog_request(), ast_sip_send_stateful_response(), create_out_of_dialog_request(), load_module(), supplement_outgoing_response(), and unload_pjsip().
supplements
struct supplements supplements = { .first = NULL, .last = NULL, .lock = { PTHREAD_RWLOCK_INITIALIZER , NULL, {1, 0} } , }