Asterisk - The Open Source Telephony Project: test_scope_trace.c File Reference
test_scope_trace.c File Reference
Test for Scope Trace.
#include "asterisk.h"
#include "asterisk/utils.h"
#include "asterisk/module.h"
#include "asterisk/test.h"
#include "asterisk/logger.h"
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
AST_TEST_DEFINE (scope_test)
static int load_module (void)
static const char * str_appender (struct ast_str **buf, char *a)
static int test_scope_enter_function (void)
static void test_scope_trace (void)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Scope Trace Test" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, }
static const struct ast_module_info * ast_module_info = &__mod_info
Detailed Description
Test for Scope Trace.
Author
George Joseph <gjoseph@digium.com>
tests for Scope Trace
Definition in file test_scope_trace.c.
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 126 of file test_scope_trace.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 126 of file test_scope_trace.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 126 of file test_scope_trace.c.
AST_TEST_DEFINE()
AST_TEST_DEFINE (scope_test)
Definition at line 72 of file test_scope_trace.c.
References AST_TEST_FAIL, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_test_status_update, ast_trace, sip_to_pjsip::info(), SCOPE_ENTER, SCOPE_EXIT, SCOPE_EXIT_EXPR, SCOPE_EXIT_RTN_VALUE, SCOPE_TRACE, TEST_EXECUTE, TEST_INIT, and test_scope_enter_function().
 {
    SCOPE_ENTER(1, "top %s function\n", "scope_test");
    ast_trace(1, "%s\n", "test outer");
    switch (cmd) {
    case TEST_INIT:
    {
       SCOPE_ENTER(1, "TEST_INIT\n");
       info->name = "scope_test";
       info->category = "/main/logging/";
       info->summary = "Scope Trace Tests";
       info->description = "Scope Trace Tests";
       /* need to exit the case scope */
       SCOPE_EXIT("TEST_INIT\n");
       /* need to exit the function */
       SCOPE_EXIT_RTN_VALUE(AST_TEST_NOT_RUN, "BYE\n");
    }
    case TEST_EXECUTE:
    {
       SCOPE_ENTER(1, "TEST_EXECUTE\n");
       ast_trace(1, "%s\n", "test execute");
       SCOPE_EXIT_EXPR(break, "TEST_EXECUTE\n");
    }
    default:
       ast_test_status_update(test, "Shouldn't have gotten here\n");
       return AST_TEST_FAIL;
    }
    if (1) {
       SCOPE_TRACE(1, "IF block\n");
       test_scope_enter_function();
    }
    ast_trace(1);
    ast_trace(1, "test no variables\n");
    ast_trace(1, "%s\n", "test variable");
    SCOPE_EXIT_RTN_VALUE(AST_TEST_PASS, "Something: %d\n", AST_TEST_PASS);
 }
load_module()
static int load_module (void) static
Definition at line 120 of file test_scope_trace.c.
References AST_MODULE_LOAD_SUCCESS, and AST_TEST_REGISTER.
 {
    AST_TEST_REGISTER(scope_test);
    return AST_MODULE_LOAD_SUCCESS;
 }
str_appender()
static const char* str_appender (struct ast_str ** buf, char * a) static
Definition at line 42 of file test_scope_trace.c.
References ast_str_append(), and ast_str_buffer().
Referenced by test_scope_enter_function().
 {
    ast_str_append(buf, 0, "<append %s>", a);
    return ast_str_buffer(*buf);
 }
test_scope_enter_function()
static int test_scope_enter_function (void) static
Definition at line 54 of file test_scope_trace.c.
References ast_str_tmp, AST_TEST_PASS, SCOPE_ENTER, SCOPE_EXIT_RTN_VALUE, str_appender(), and test_scope_trace().
Referenced by AST_TEST_DEFINE().
 {
    SCOPE_ENTER(1, "%s %s %s %s %s %s %s\n",
       ast_str_tmp(12, str_appender(&STR_TMP, "str1")),
       ast_str_tmp(12, str_appender(&STR_TMP, "str2")),
       ast_str_tmp(32, str_appender(&STR_TMP, "AAAAAAAAAAAAAAAAAAAAAAAA")),
       ast_str_tmp(12, str_appender(&STR_TMP, "B")),
       "ccccccccccccc",
       ast_str_tmp(12, str_appender(&STR_TMP, "DDDDD")),
       ast_str_tmp(12, str_appender(&STR_TMP, "ww"))
       );
    test_scope_trace();
    SCOPE_EXIT_RTN_VALUE(AST_TEST_PASS, "test no variables\n");
 }
test_scope_trace()
static void test_scope_trace (void) static
Definition at line 48 of file test_scope_trace.c.
References SCOPE_ENTER, and SCOPE_EXIT_RTN.
Referenced by test_scope_enter_function().
 {
    SCOPE_ENTER(1, "subfunction\n");
    SCOPE_EXIT_RTN("got out\n");
 }
unload_module()
static int unload_module (void) static
Definition at line 114 of file test_scope_trace.c.
References AST_TEST_UNREGISTER.
 {
    AST_TEST_UNREGISTER(scope_test);
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Scope Trace Test" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, } static
Definition at line 126 of file test_scope_trace.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 126 of file test_scope_trace.c.