Asterisk - The Open Source Telephony Project: config_auth.c File Reference
config_auth.c File Reference
#include "asterisk.h"
#include <pjsip.h>
#include <pjlib.h>
#include "asterisk/res_pjsip.h"
#include "asterisk/logger.h"
#include "asterisk/sorcery.h"
#include "asterisk/cli.h"
#include "include/res_pjsip_private.h"
#include "asterisk/res_pjsip_cli.h"
Functions
static int ami_show_auths (struct mansession *s, const struct message *m)
const char * ast_sip_auth_type_to_str (enum ast_sip_auth_type type)
Converts the given auth type to a string.
int ast_sip_destroy_sorcery_auth (void)
int ast_sip_for_each_auth (const struct ast_sip_auth_vector *vector, ao2_callback_fn on_auth, void *arg)
For every auth in the array call the given 'on_auth' handler.
int ast_sip_format_auths_ami (const struct ast_sip_auth_vector *auths, struct ast_sip_ami *ami)
Format auth details for AMI.
int ast_sip_initialize_sorcery_auth (void)
Initialize sorcery with auth support.
static void * auth_alloc (const char *name)
static int auth_apply (const struct ast_sorcery *sorcery, void *obj)
static void auth_destroy (void *obj)
static int auth_type_handler (const struct aco_option *opt, struct ast_variable *var, void *obj)
static int auth_type_to_str (const void *obj, const intptr_t *args, char **buf)
static struct ao2_container * cli_get_auths (void)
static struct ao2_container * cli_get_container (const char *regex)
static int cli_iterator (void *container, ao2_callback_fn callback, void *args)
static int cli_print_body (void *obj, void *arg, int flags)
static int cli_print_header (void *obj, void *arg, int flags)
static void * cli_retrieve_by_id (const char *id)
static int format_ami_auth_handler (void *obj, void *arg, int flags)
static int format_ami_authlist_handler (void *obj, void *arg, int flags)
static int format_ami_endpoint_auth (const struct ast_sip_endpoint *endpoint, struct ast_sip_ami *ami)
static int sip_auth_to_ami (const struct ast_sip_auth *auth, struct ast_str **buf)
Variables
static const char * auth_types_map []
static struct ast_cli_entry cli_commands []
static struct ast_sip_cli_formatter_entry * cli_formatter
static struct ast_sip_endpoint_formatter endpoint_auth_formatter
Function Documentation
ami_show_auths()
static int ami_show_auths (struct mansession * s, const struct message * m) static
Definition at line 247 of file config_auth.c.
References ao2_callback, ao2_container_count(), ao2_ref, astman_get_header(), astman_send_error(), astman_send_list_complete_end(), astman_send_list_complete_start(), astman_send_listack(), cli_get_auths(), ast_sip_ami::count, format_ami_authlist_handler(), ast_sip_ami::m, OBJ_NODATA, and ast_sip_ami::s.
Referenced by ast_sip_initialize_sorcery_auth().
 {
    struct ast_sip_ami ami = { .s = s, .m = m, .action_id = astman_get_header(m, "ActionID"), };
    struct ao2_container *auths;
    auths = cli_get_auths();
    if (!auths) {
       astman_send_error(s, m, "Could not get Auths\n");
       return 0;
    }
    if (!ao2_container_count(auths)) {
       astman_send_error(s, m, "No Auths found\n");
       ao2_ref(auths, -1);
       return 0;
    }
    astman_send_listack(s, m, "A listing of Auths follows, presented as AuthList events",
          "start");
    ao2_callback(auths, OBJ_NODATA, format_ami_authlist_handler, &ami);
    astman_send_list_complete_start(s, m, "AuthListComplete", ami.count);
    astman_send_list_complete_end(s);
    ao2_ref(auths, -1);
    return 0;
 }
ast_sip_auth_type_to_str()
const char* ast_sip_auth_type_to_str (enum ast_sip_auth_type type)
Converts the given auth type to a string.
Parameters
type the auth type to convert
Return values
a string representative of the auth type
Definition at line 80 of file config_auth.c.
References ARRAY_IN_BOUNDS, auth_types_map, and type.
Referenced by auth_type_to_str().
 {
    return ARRAY_IN_BOUNDS(type, auth_types_map) ?
       auth_types_map[type] : "";
 }
ast_sip_destroy_sorcery_auth()
int ast_sip_destroy_sorcery_auth (void)
Definition at line 426 of file config_auth.c.
References ARRAY_LEN, ast_cli_unregister_multiple(), ast_manager_unregister(), ast_sip_unregister_cli_formatter(), and ast_sip_unregister_endpoint_formatter().
Referenced by ast_res_pjsip_destroy_configuration().
 {
    ast_cli_unregister_multiple(cli_commands, ARRAY_LEN(cli_commands));
    ast_sip_unregister_cli_formatter(cli_formatter);
    ast_sip_unregister_endpoint_formatter(&endpoint_auth_formatter);
    ast_manager_unregister("PJSIPShowAuths");
    return 0;
 }
ast_sip_for_each_auth()
int ast_sip_for_each_auth (const struct ast_sip_auth_vector * array, ao2_callback_fn on_auth, void * arg)
For every auth in the array call the given 'on_auth' handler.
Parameters
array an array of auths
on_auth callback for each auth
arg user data passed to handler
Return values
0 Success, non-zero on failure
Definition at line 135 of file config_auth.c.
References ao2_cleanup, ast_sip_get_sorcery(), ast_sorcery_retrieve_by_id(), AST_VECTOR_GET, AST_VECTOR_SIZE, and RAII_VAR.
Referenced by ast_sip_format_auths_ami(), and cli_iterator().
 {
    int i;
    if (!vector || !AST_VECTOR_SIZE(vector)) {
       return 0;
    }
    for (i = 0; i < AST_VECTOR_SIZE(vector); ++i) {
       /* AST_VECTOR_GET is safe to use since the vector is immutable */
       RAII_VAR(struct ast_sip_auth *, auth, ast_sorcery_retrieve_by_id(
              ast_sip_get_sorcery(), SIP_SORCERY_AUTH_TYPE,
              AST_VECTOR_GET(vector,i)), ao2_cleanup);
       if (!auth) {
          continue;
       }
       if (on_auth(auth, arg, 0)) {
          return -1;
       }
    }
    return 0;
 }
ast_sip_format_auths_ami()
int ast_sip_format_auths_ami (const struct ast_sip_auth_vector * auths, struct ast_sip_ami * ami)
Format auth details for AMI.
Parameters
auths an auth array
ami ami variable container
Return values
0 Success, non-zero on failure
Definition at line 195 of file config_auth.c.
References ast_sip_for_each_auth(), and format_ami_auth_handler().
Referenced by ami_outbound_registration_task(), and format_ami_endpoint_auth().
 {
    return ast_sip_for_each_auth(auths, format_ami_auth_handler, ami);
 }
ast_sip_initialize_sorcery_auth()
int ast_sip_initialize_sorcery_auth (void)
Initialize sorcery with auth support.
Definition at line 370 of file config_auth.c.
References ami_show_auths(), ao2_alloc, ARRAY_LEN, ast_cli_register_multiple, ast_log, ast_manager_register_xml, ast_sip_get_sorcery(), ast_sip_register_cli_formatter(), ast_sip_register_endpoint_formatter(), ast_sorcery_apply_default, ast_sorcery_object_field_register, ast_sorcery_object_field_register_custom, ast_sorcery_object_get_id(), ast_sorcery_object_register, auth_alloc(), auth_apply(), auth_type_handler(), auth_type_to_str(), cli_get_container(), cli_iterator(), cli_print_body(), cli_print_header(), cli_retrieve_by_id(), EVENT_FLAG_SYSTEM, FLDSET, ast_sip_cli_formatter_entry::get_container, ast_sip_cli_formatter_entry::get_id, ast_sip_cli_formatter_entry::iterate, LOG_ERROR, ast_sip_cli_formatter_entry::name, NULL, OPT_NOOP_T, OPT_STRINGFIELD_T, OPT_UINT_T, ast_sip_cli_formatter_entry::print_body, ast_sip_cli_formatter_entry::print_header, ast_sip_cli_formatter_entry::retrieve_by_id, sorcery, and STRFLDSET.
Referenced by ast_res_pjsip_initialize_configuration().
 {
    struct ast_sorcery *sorcery = ast_sip_get_sorcery();
    ast_sorcery_apply_default(sorcery, SIP_SORCERY_AUTH_TYPE, "config", "pjsip.conf,criteria=type=auth");
    if (ast_sorcery_object_register(sorcery, SIP_SORCERY_AUTH_TYPE, auth_alloc, NULL, auth_apply)) {
       return -1;
    }
    ast_sorcery_object_field_register(sorcery, SIP_SORCERY_AUTH_TYPE, "type", "",
          OPT_NOOP_T, 0, 0);
    ast_sorcery_object_field_register(sorcery, SIP_SORCERY_AUTH_TYPE, "username",
          "", OPT_STRINGFIELD_T, 0, STRFLDSET(struct ast_sip_auth, auth_user));
    ast_sorcery_object_field_register(sorcery, SIP_SORCERY_AUTH_TYPE, "password",
          "", OPT_STRINGFIELD_T, 0, STRFLDSET(struct ast_sip_auth, auth_pass));
    ast_sorcery_object_field_register(sorcery, SIP_SORCERY_AUTH_TYPE, "refresh_token",
          "", OPT_STRINGFIELD_T, 0, STRFLDSET(struct ast_sip_auth, refresh_token));
    ast_sorcery_object_field_register(sorcery, SIP_SORCERY_AUTH_TYPE, "oauth_clientid",
          "", OPT_STRINGFIELD_T, 0, STRFLDSET(struct ast_sip_auth, oauth_clientid));
    ast_sorcery_object_field_register(sorcery, SIP_SORCERY_AUTH_TYPE, "oauth_secret",
          "", OPT_STRINGFIELD_T, 0, STRFLDSET(struct ast_sip_auth, oauth_secret));
    ast_sorcery_object_field_register(sorcery, SIP_SORCERY_AUTH_TYPE, "md5_cred",
          "", OPT_STRINGFIELD_T, 0, STRFLDSET(struct ast_sip_auth, md5_creds));
    ast_sorcery_object_field_register(sorcery, SIP_SORCERY_AUTH_TYPE, "realm",
          "", OPT_STRINGFIELD_T, 0, STRFLDSET(struct ast_sip_auth, realm));
    ast_sorcery_object_field_register(sorcery, SIP_SORCERY_AUTH_TYPE, "nonce_lifetime",
          "32", OPT_UINT_T, 0, FLDSET(struct ast_sip_auth, nonce_lifetime));
    ast_sorcery_object_field_register_custom(sorcery, SIP_SORCERY_AUTH_TYPE, "auth_type",
          "userpass", auth_type_handler, auth_type_to_str, NULL, 0, 0);
    ast_sip_register_endpoint_formatter(&endpoint_auth_formatter);
    cli_formatter = ao2_alloc(sizeof(struct ast_sip_cli_formatter_entry), NULL);
    if (!cli_formatter) {
       ast_log(LOG_ERROR, "Unable to allocate memory for cli formatter\n");
       return -1;
    }
    cli_formatter->name = SIP_SORCERY_AUTH_TYPE;
    cli_formatter->print_header = cli_print_header;
    cli_formatter->print_body = cli_print_body;
    cli_formatter->get_container = cli_get_container;
    cli_formatter->iterate = cli_iterator;
    cli_formatter->get_id = ast_sorcery_object_get_id;
    cli_formatter->retrieve_by_id = cli_retrieve_by_id;
    ast_sip_register_cli_formatter(cli_formatter);
    ast_cli_register_multiple(cli_commands, ARRAY_LEN(cli_commands));
    if (ast_manager_register_xml("PJSIPShowAuths", EVENT_FLAG_SYSTEM, ami_show_auths)) {
       return -1;
    }
    return 0;
 }
auth_alloc()
static void* auth_alloc (const char * name) static
Definition at line 36 of file config_auth.c.
References ao2_cleanup, ast_sorcery_generic_alloc(), ast_string_field_init, auth_destroy(), and NULL.
Referenced by ast_sip_initialize_sorcery_auth().
 {
    struct ast_sip_auth *auth = ast_sorcery_generic_alloc(sizeof(*auth), auth_destroy);
    if (!auth) {
       return NULL;
    }
    if (ast_string_field_init(auth, 64)) {
       ao2_cleanup(auth);
       return NULL;
    }
    return auth;
 }
auth_apply()
static int auth_apply (const struct ast_sorcery * sorcery, void * obj) static
Definition at line 93 of file config_auth.c.
References ast_log, AST_SIP_AUTH_TYPE_ARTIFICIAL, AST_SIP_AUTH_TYPE_GOOGLE_OAUTH, AST_SIP_AUTH_TYPE_MD5, AST_SIP_AUTH_TYPE_USER_PASS, ast_sorcery_object_get_id(), ast_strlen_zero, ast_sip_auth::auth_user, LOG_ERROR, ast_sip_auth::md5_creds, ast_sip_auth::oauth_clientid, ast_sip_auth::oauth_secret, ast_sip_auth::refresh_token, and ast_sip_auth::type.
Referenced by ast_sip_initialize_sorcery_auth().
 {
    struct ast_sip_auth *auth = obj;
    int res = 0;
    if (ast_strlen_zero(auth->auth_user)) {
       ast_log(LOG_ERROR, "No authentication username for auth '%s'\n",
             ast_sorcery_object_get_id(auth));
       return -1;
    }
    switch (auth->type) {
    case AST_SIP_AUTH_TYPE_MD5:
       if (ast_strlen_zero(auth->md5_creds)) {
          ast_log(LOG_ERROR, "'md5' authentication specified but no md5_cred "
                "specified for auth '%s'\n", ast_sorcery_object_get_id(auth));
          res = -1;
       } else if (strlen(auth->md5_creds) != PJSIP_MD5STRLEN) {
          ast_log(LOG_ERROR, "'md5' authentication requires digest of size '%d', but "
             "digest is '%d' in size for auth '%s'\n", PJSIP_MD5STRLEN, (int)strlen(auth->md5_creds),
             ast_sorcery_object_get_id(auth));
          res = -1;
       }
       break;
    case AST_SIP_AUTH_TYPE_GOOGLE_OAUTH:
       if (ast_strlen_zero(auth->refresh_token)
          || ast_strlen_zero(auth->oauth_clientid)
          || ast_strlen_zero(auth->oauth_secret)) {
          ast_log(LOG_ERROR, "'google_oauth' authentication specified but refresh_token,"
             " oauth_clientid, or oauth_secret not specified for auth '%s'\n",
             ast_sorcery_object_get_id(auth));
          res = -1;
       }
       break;
    case AST_SIP_AUTH_TYPE_USER_PASS:
    case AST_SIP_AUTH_TYPE_ARTIFICIAL:
       break;
    }
    return res;
 }
auth_destroy()
static void auth_destroy (void * obj) static
Definition at line 30 of file config_auth.c.
References ast_string_field_free_memory.
Referenced by auth_alloc().
 {
    struct ast_sip_auth *auth = obj;
    ast_string_field_free_memory(auth);
 }
auth_type_handler()
static int auth_type_handler (const struct aco_option * opt, struct ast_variable * var, void * obj) static
Definition at line 52 of file config_auth.c.
References ast_log, AST_SIP_AUTH_TYPE_GOOGLE_OAUTH, AST_SIP_AUTH_TYPE_MD5, AST_SIP_AUTH_TYPE_USER_PASS, LOG_WARNING, ast_variable::name, ast_sip_auth::type, and ast_variable::value.
Referenced by ast_sip_initialize_sorcery_auth().
 {
    struct ast_sip_auth *auth = obj;
    if (!strcasecmp(var->value, "userpass")) {
       auth->type = AST_SIP_AUTH_TYPE_USER_PASS;
    } else if (!strcasecmp(var->value, "md5")) {
       auth->type = AST_SIP_AUTH_TYPE_MD5;
    } else if (!strcasecmp(var->value, "google_oauth")) {
 #ifdef HAVE_PJSIP_OAUTH_AUTHENTICATION
       auth->type = AST_SIP_AUTH_TYPE_GOOGLE_OAUTH;
 #else
       ast_log(LOG_WARNING, "OAuth support is not available in the version of PJSIP in use\n");
       return -1;
 #endif
    } else {
       ast_log(LOG_WARNING, "Unknown authentication storage type '%s' specified for %s\n",
             var->value, var->name);
       return -1;
    }
    return 0;
 }
auth_type_to_str()
static int auth_type_to_str (const void * obj, const intptr_t * args, char ** buf) static
Definition at line 86 of file config_auth.c.
References ast_sip_auth_type_to_str(), ast_strdup, and ast_sip_auth::type.
Referenced by ast_sip_initialize_sorcery_auth().
 {
    const struct ast_sip_auth *auth = obj;
    *buf = ast_strdup(ast_sip_auth_type_to_str(auth->type));
    return 0;
 }
cli_get_auths()
static struct ao2_container* cli_get_auths (void) static
Definition at line 216 of file config_auth.c.
References AST_RETRIEVE_FLAG_ALL, AST_RETRIEVE_FLAG_MULTIPLE, ast_sip_get_sorcery(), ast_sorcery_retrieve_by_fields(), and NULL.
Referenced by ami_show_auths().
 {
    struct ao2_container *auths;
    auths = ast_sorcery_retrieve_by_fields(ast_sip_get_sorcery(), "auth",
          AST_RETRIEVE_FLAG_MULTIPLE | AST_RETRIEVE_FLAG_ALL, NULL);
    return auths;
 }
cli_get_container()
static struct ao2_container* cli_get_container (const char * regex) static
Definition at line 277 of file config_auth.c.
References AO2_ALLOC_OPT_LOCK_NOLOCK, ao2_cleanup, ao2_container_alloc_list, ao2_container_dup(), ao2_ref, ast_sip_get_sorcery(), ast_sorcery_object_id_compare(), ast_sorcery_object_id_sort(), ast_sorcery_retrieve_by_regex(), container, NULL, and RAII_VAR.
Referenced by ast_sip_initialize_sorcery_auth().
 {
    RAII_VAR(struct ao2_container *, container, NULL, ao2_cleanup);
    struct ao2_container *s_container;
    container = ast_sorcery_retrieve_by_regex(ast_sip_get_sorcery(), "auth", regex);
    if (!container) {
       return NULL;
    }
    s_container = ao2_container_alloc_list(AO2_ALLOC_OPT_LOCK_NOLOCK, 0,
       ast_sorcery_object_id_sort, ast_sorcery_object_id_compare);
    if (!s_container) {
       return NULL;
    }
    if (ao2_container_dup(s_container, container, 0)) {
       ao2_ref(s_container, -1);
       return NULL;
    }
    return s_container;
 }
cli_iterator()
static int cli_iterator (void * container, ao2_callback_fn callback, void * args) static
Definition at line 301 of file config_auth.c.
References ast_sip_for_each_auth().
Referenced by ast_sip_initialize_sorcery_auth().
 {
    return ast_sip_for_each_auth(container, callback, args);
 }
cli_print_body()
static int cli_print_body (void * obj, void * arg, int flags) static
Definition at line 326 of file config_auth.c.
References ast_assert, ast_sip_cli_print_sorcery_objectset(), ast_sorcery_object_get_id(), ast_str_append(), ast_sip_cli_context::auth_direction, ast_sip_auth::auth_user, CLI_INDENT_TO_SPACES, context, ast_sip_cli_context::indent_level, NULL, ast_sip_cli_context::output_buffer, ast_sip_cli_context::show_details, and ast_sip_cli_context::show_details_only_level_0.
Referenced by ast_sip_initialize_sorcery_auth().
 {
    struct ast_sip_auth *auth = obj;
    struct ast_sip_cli_context *context = arg;
    char title[32];
    ast_assert(context->output_buffer != NULL);
    snprintf(title, sizeof(title), "%sAuth",
       context->auth_direction ? context->auth_direction : "");
    ast_str_append(&context->output_buffer, 0, "%*s:  %s/%s\n",
       CLI_INDENT_TO_SPACES(context->indent_level), title,
       ast_sorcery_object_get_id(auth), auth->auth_user);
    if (context->show_details
       || (context->show_details_only_level_0 && context->indent_level == 0)) {
       ast_str_append(&context->output_buffer, 0, "\n");
       ast_sip_cli_print_sorcery_objectset(auth, context, 0);
    }
    return 0;
 }
cli_print_header()
static int cli_print_header (void * obj, void * arg, int flags) static
Definition at line 311 of file config_auth.c.
References ast_assert, ast_str_append(), CLI_HEADER_FILLER, CLI_INDENT_TO_SPACES, CLI_MAX_WIDTH, context, ast_sip_cli_context::indent_level, NULL, and ast_sip_cli_context::output_buffer.
Referenced by ast_sip_initialize_sorcery_auth().
 {
    struct ast_sip_cli_context *context = arg;
    int indent = CLI_INDENT_TO_SPACES(context->indent_level);
    int filler = CLI_MAX_WIDTH - indent - 20;
    ast_assert(context->output_buffer != NULL);
    ast_str_append(&context->output_buffer, 0,
       "%*s:  <AuthId/UserName%*.*s>\n", indent, "I/OAuth", filler, filler,
       CLI_HEADER_FILLER);
    return 0;
 }
cli_retrieve_by_id()
static void* cli_retrieve_by_id (const char * id) static
Definition at line 306 of file config_auth.c.
References ast_sip_get_sorcery(), and ast_sorcery_retrieve_by_id().
Referenced by ast_sip_initialize_sorcery_auth().
 {
    return ast_sorcery_retrieve_by_id(ast_sip_get_sorcery(), SIP_SORCERY_AUTH_TYPE, id);
 }
format_ami_auth_handler()
static int format_ami_auth_handler (void * obj, void * arg, int flags) static
Definition at line 168 of file config_auth.c.
References ast_sip_ami::arg, ast_free, ast_sip_create_ami_event(), ast_sorcery_object_get_id(), ast_str_append(), ast_str_buffer(), astman_append(), buf, ast_sip_ami::count, RAII_VAR, ast_sip_ami::s, and sip_auth_to_ami().
Referenced by ast_sip_format_auths_ami().
 {
    const struct ast_sip_auth *auth = obj;
    struct ast_sip_ami *ami = arg;
    const struct ast_sip_endpoint *endpoint = ami->arg;
    RAII_VAR(struct ast_str *, buf,
        ast_sip_create_ami_event("AuthDetail", ami), ast_free);
    if (!buf) {
       return -1;
    }
    if (sip_auth_to_ami(auth, &buf)) {
       return -1;
    }
    if (endpoint) {
       ast_str_append(&buf, 0, "EndpointName: %s\r\n",
              ast_sorcery_object_get_id(endpoint));
    }
    astman_append(ami->s, "%s\r\n", ast_str_buffer(buf));
    ami->count++;
    return 0;
 }
format_ami_authlist_handler()
static int format_ami_authlist_handler (void * obj, void * arg, int flags) static
Definition at line 226 of file config_auth.c.
References ast_sip_ami::arg, ast_free, ast_sip_create_ami_event(), ast_str_buffer(), astman_append(), buf, CMP_STOP, ast_sip_ami::count, ast_sip_ami::s, and sip_auth_to_ami().
Referenced by ami_show_auths().
 {
    struct ast_sip_auth *auth = obj;
    struct ast_sip_ami *ami = arg;
    struct ast_str *buf;
    buf = ast_sip_create_ami_event("AuthList", ami);
    if (!buf) {
       return CMP_STOP;
    }
    sip_auth_to_ami(auth, &buf);
    astman_append(ami->s, "%s\r\n", ast_str_buffer(buf));
    ami->count++;
    ast_free(buf);
    return 0;
 }
format_ami_endpoint_auth()
static int format_ami_endpoint_auth (const struct ast_sip_endpoint * endpoint, struct ast_sip_ami * ami) static
Definition at line 201 of file config_auth.c.
References ast_sip_ami::arg, ast_sip_format_auths_ami(), ast_sip_endpoint::inbound_auths, and ast_sip_endpoint::outbound_auths.
 {
    ami->arg = (void *)endpoint;
    if (ast_sip_format_auths_ami(&endpoint->inbound_auths, ami)) {
       return -1;
    }
    return ast_sip_format_auths_ami(&endpoint->outbound_auths, ami);
 }
sip_auth_to_ami()
static int sip_auth_to_ami (const struct ast_sip_auth * auth, struct ast_str ** buf) static
Definition at line 162 of file config_auth.c.
References ast_sip_sorcery_object_to_ami().
Referenced by format_ami_auth_handler(), and format_ami_authlist_handler().
 {
    return ast_sip_sorcery_object_to_ami(auth, buf);
 }
Variable Documentation
auth_types_map
const char* auth_types_map[] static
Initial value:
= {
   [AST_SIP_AUTH_TYPE_USER_PASS] = "userpass",
   [AST_SIP_AUTH_TYPE_MD5] = "md5",
   [AST_SIP_AUTH_TYPE_GOOGLE_OAUTH] = "google_oauth"
}
Definition at line 74 of file config_auth.c.
Referenced by ast_sip_auth_type_to_str().
cli_commands
struct ast_cli_entry cli_commands[] static
Definition at line 350 of file config_auth.c.
cli_formatter
struct ast_sip_cli_formatter_entry* cli_formatter static
Definition at line 367 of file config_auth.c.
endpoint_auth_formatter
struct ast_sip_endpoint_formatter endpoint_auth_formatter static
Initial value:
= {
   .format_ami = format_ami_endpoint_auth
}
Definition at line 212 of file config_auth.c.