Asterisk - The Open Source Telephony Project: format_h263.c File Reference
format_h263.c File Reference
Module: Media File Formats
Save to raw, headerless h263 data.
#include "asterisk.h"
#include "asterisk/mod_format.h"
#include "asterisk/module.h"
#include "asterisk/endian.h"
#include "asterisk/format_cache.h"
Data Structures
struct h263_desc
Macros
#define BUF_SIZE 32768 /* Four real h.263 Frames */
#define FRAME_ENDED 0x8000
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int h263_open (struct ast_filestream *s)
static struct ast_frame * h263_read (struct ast_filestream *s, int *whennext)
static int h263_seek (struct ast_filestream *fs, off_t sample_offset, int whence)
static off_t h263_tell (struct ast_filestream *fs)
static int h263_trunc (struct ast_filestream *fs)
static int h263_write (struct ast_filestream *fs, struct ast_frame *f)
static int load_module (void)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Raw H.263 data" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_APP_DEPEND }
static const struct ast_module_info * ast_module_info = &__mod_info
static struct ast_format_def h263_f
Detailed Description
Save to raw, headerless h263 data.
File name extension: h263
See Video support in Asterisk
Definition in file format_h263.c.
Macro Definition Documentation
BUF_SIZE
#define BUF_SIZE 32768 /* Four real h.263 Frames */
Definition at line 48 of file format_h263.c.
Referenced by h263_read().
FRAME_ENDED
#define FRAME_ENDED 0x8000
Definition at line 50 of file format_h263.c.
Referenced by h263_read(), and h263_write().
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 190 of file format_h263.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 190 of file format_h263.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 190 of file format_h263.c.
h263_open()
static int h263_open (struct ast_filestream * s) static
Definition at line 57 of file format_h263.c.
References ast_log, ast_filestream::f, and LOG_WARNING.
 {
    unsigned int ts;
    if (fread(&ts, 1, sizeof(ts), s->f) != sizeof(ts)) {
       ast_log(LOG_WARNING, "Empty file!\n");
       return -1;
    }
    return 0;
 }
h263_read()
static struct ast_frame* h263_read (struct ast_filestream * s, int * whennext) static
Definition at line 68 of file format_h263.c.
References ast_filestream::_private, ast_format_get_name(), AST_FRAME_SET_BUFFER, AST_FRIENDLY_OFFSET, ast_log, ast_filestream::buf, BUF_SIZE, ast_frame::data, ast_frame::datalen, errno, ast_filestream::f, ast_frame_subclass::format, ast_filestream::fr, FRAME_ENDED, ast_frame_subclass::frame_ending, if(), h263_desc::lastts, len(), LOG_WARNING, NULL, ast_frame::ptr, ast_frame::samples, ast_frame::subclass, and ast_frame::ts.
 {
    size_t res;
    uint32_t mark;
    unsigned short len;
    unsigned int ts;
    struct h263_desc *fs = (struct h263_desc *)s->_private;
    /* Send a frame from the file to the appropriate channel */
    if ((res = fread(&len, 1, sizeof(len), s->f)) != sizeof(len))
       return NULL;
    len = ntohs(len);
    mark = (len & FRAME_ENDED) ? 1 : 0;
    len &= 0x7fff;
    if (len > BUF_SIZE) {
       ast_log(LOG_WARNING, "Length %d is too long\n", len);
       return NULL;
    }
    AST_FRAME_SET_BUFFER(&s->fr, s->buf, AST_FRIENDLY_OFFSET, len);
    if ((res = fread(s->fr.data.ptr, 1, s->fr.datalen, s->f)) != s->fr.datalen) {
       if (res) {
          ast_log(LOG_WARNING, "Short read of %s data (expected %d bytes, read %zu): %s\n",
                ast_format_get_name(s->fr.subclass.format), s->fr.datalen, res,
                strerror(errno));
       }
       return NULL;
    }
    s->fr.samples = fs->lastts;   /* XXX what ? */
    s->fr.datalen = len;
    s->fr.subclass.frame_ending = mark;
    if ((res = fread(&ts, 1, sizeof(ts), s->f)) == sizeof(ts)) {
       fs->lastts = ntohl(ts);
       *whennext = fs->lastts * 4/45;
    } else
       *whennext = 0;
    return &s->fr;
 }
h263_seek()
static int h263_seek (struct ast_filestream * fs, off_t sample_offset, int whence) static
Definition at line 130 of file format_h263.c.
 {
    /* No way Jose */
    return -1;
 }
h263_tell()
static off_t h263_tell (struct ast_filestream * fs) static
Definition at line 153 of file format_h263.c.
References ast_filestream::f.
 {
    off_t offset = ftello(fs->f);
    return offset; /* XXX totally bogus, needs fixing */
 }
h263_trunc()
static int h263_trunc (struct ast_filestream * fs) static
Definition at line 136 of file format_h263.c.
References ast_log, AST_LOG_WARNING, errno, and ast_filestream::f.
 {
    int fd;
    off_t cur;
    if ((fd = fileno(fs->f)) < 0) {
       ast_log(AST_LOG_WARNING, "Unable to determine file descriptor for h263 filestream %p: %s\n", fs, strerror(errno));
       return -1;
    }
    if ((cur = ftello(fs->f)) < 0) {
       ast_log(AST_LOG_WARNING, "Unable to determine current position in h263 filestream %p: %s\n", fs, strerror(errno));
       return -1;
    }
    /* Truncate file to current length */
    return ftruncate(fd, cur);
 }
h263_write()
static int h263_write (struct ast_filestream * fs, struct ast_frame * f) static
Definition at line 106 of file format_h263.c.
References ast_log, ast_frame::data, ast_frame::datalen, errno, ast_filestream::f, FRAME_ENDED, ast_frame_subclass::frame_ending, len(), LOG_WARNING, ast_frame::ptr, ast_frame::samples, and ast_frame::subclass.
 {
    int res;
    unsigned int ts;
    unsigned short len;
    uint32_t mark = 0;
    mark = f->subclass.frame_ending ? FRAME_ENDED : 0;
    ts = htonl(f->samples);
    if ((res = fwrite(&ts, 1, sizeof(ts), fs->f)) != sizeof(ts)) {
          ast_log(LOG_WARNING, "Bad write (%d/4): %s\n", res, strerror(errno));
          return -1;
    }
    len = htons(f->datalen | mark);
    if ((res = fwrite(&len, 1, sizeof(len), fs->f)) != sizeof(len)) {
          ast_log(LOG_WARNING, "Bad write (%d/2): %s\n", res, strerror(errno));
          return -1;
    }
    if ((res = fwrite(f->data.ptr, 1, f->datalen, fs->f)) != f->datalen) {
          ast_log(LOG_WARNING, "Bad write (%d/%d): %s\n", res, f->datalen, strerror(errno));
          return -1;
    }
    return 0;
 }
load_module()
static int load_module (void) static
Definition at line 172 of file format_h263.c.
References ast_format_def_register, ast_format_h263, AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, and ast_format_def::format.
Referenced by unload_module().
 {
    h263_f.format = ast_format_h263;
    if (ast_format_def_register(&h263_f))
       return AST_MODULE_LOAD_DECLINE;
    return AST_MODULE_LOAD_SUCCESS;
 }
unload_module()
static int unload_module (void) static
Definition at line 180 of file format_h263.c.
References ast_format_def_unregister(), AST_MODFLAG_LOAD_ORDER, AST_MODPRI_APP_DEPEND, AST_MODULE_INFO(), AST_MODULE_SUPPORT_CORE, ASTERISK_GPL_KEY, load_module(), and ast_format_def::name.
 {
    return ast_format_def_unregister(h263_f.name);
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Raw H.263 data" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_APP_DEPEND } static
Definition at line 190 of file format_h263.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 190 of file format_h263.c.
h263_f
struct ast_format_def h263_f static
Definition at line 159 of file format_h263.c.