Asterisk - The Open Source Telephony Project: codec_alaw.c File Reference
codec_alaw.c File Reference
Module: Codecs
codec_alaw.c - translate between signed linear and alaw
#include "asterisk.h"
#include "asterisk/module.h"
#include "asterisk/config.h"
#include "asterisk/translate.h"
#include "asterisk/alaw.h"
#include "asterisk/utils.h"
#include "asterisk/slin.h"
#include "ex_alaw.h"
Macros
#define BUFFER_SAMPLES 8096 /* size for the translation buffers */
Functions
static void __reg_module (void)
static void __unreg_module (void)
static int alawtolin_framein (struct ast_trans_pvt *pvt, struct ast_frame *f)
decode frame into lin and fill output buffer.
struct ast_module * AST_MODULE_SELF_SYM (void)
static int lintoalaw_framein (struct ast_trans_pvt *pvt, struct ast_frame *f)
convert and store input samples in output buffer
static int load_module (void)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_DEFAULT , .description = "A-law Coder/Decoder" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, }
static struct ast_translator alawtolin
static const struct ast_module_info * ast_module_info = &__mod_info
static struct ast_translator lintoalaw
Detailed Description
codec_alaw.c - translate between signed linear and alaw
Definition in file codec_alaw.c.
Macro Definition Documentation
BUFFER_SAMPLES
#define BUFFER_SAMPLES 8096 /* size for the translation buffers */
Definition at line 38 of file codec_alaw.c.
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 143 of file codec_alaw.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 143 of file codec_alaw.c.
alawtolin_framein()
static int alawtolin_framein (struct ast_trans_pvt * pvt, struct ast_frame * f) static
decode frame into lin and fill output buffer.
Definition at line 45 of file codec_alaw.c.
References AST_ALAW, ast_frame::data, ast_trans_pvt::datalen, ast_trans_pvt::i16, ast_trans_pvt::outbuf, ast_frame::ptr, ast_frame::samples, and ast_trans_pvt::samples.
 {
    int i = f->samples;
    unsigned char *src = f->data.ptr;
    int16_t *dst = pvt->outbuf.i16 + pvt->samples;
    pvt->samples += i;
    pvt->datalen += i * 2;  /* 2 bytes/sample */
    while (i--)
       *dst++ = AST_ALAW(*src++);
    return 0;
 }
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 143 of file codec_alaw.c.
lintoalaw_framein()
static int lintoalaw_framein (struct ast_trans_pvt * pvt, struct ast_frame * f) static
convert and store input samples in output buffer
Definition at line 61 of file codec_alaw.c.
References AST_LIN2A, ast_trans_pvt::c, ast_frame::data, ast_trans_pvt::datalen, ast_trans_pvt::outbuf, ast_frame::ptr, ast_frame::samples, and ast_trans_pvt::samples.
 {
    int i = f->samples;
    char *dst = pvt->outbuf.c + pvt->samples;
    int16_t *src = f->data.ptr;
    pvt->samples += i;
    pvt->datalen += i;   /* 1 byte/sample */
    while (i--)
       *dst++ = AST_LIN2A(*src++);
    return 0;
 }
load_module()
static int load_module (void) static
Definition at line 124 of file codec_alaw.c.
References AST_MODFLAG_DEFAULT, AST_MODULE_INFO(), AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, AST_MODULE_SUPPORT_CORE, ast_register_translator, ASTERISK_GPL_KEY, and unload_module().
 {
    int res;
    res = ast_register_translator(&alawtolin);
    res |= ast_register_translator(&lintoalaw);
    if (res) {
       unload_module();
       return AST_MODULE_LOAD_DECLINE;
    }
    return AST_MODULE_LOAD_SUCCESS;
 }
unload_module()
static int unload_module (void) static
Definition at line 114 of file codec_alaw.c.
References ast_unregister_translator().
Referenced by load_module().
 {
    int res;
    res = ast_unregister_translator(&lintoalaw);
    res |= ast_unregister_translator(&alawtolin);
    return res;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_DEFAULT , .description = "A-law Coder/Decoder" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, } static
Definition at line 143 of file codec_alaw.c.
alawtolin
struct ast_translator alawtolin static
Definition at line 76 of file codec_alaw.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 143 of file codec_alaw.c.
lintoalaw
struct ast_translator lintoalaw static
Definition at line 95 of file codec_alaw.c.