Asterisk - The Open Source Telephony Project: pjsip_transport_events.c File Reference
pjsip_transport_events.c File Reference
Manages the global transport event notification callbacks.
#include "asterisk.h"
#include "asterisk/res_pjsip.h"
#include "include/res_pjsip_private.h"
#include "asterisk/linkedlists.h"
#include "asterisk/vector.h"
Data Structures
struct callback_data
struct transport_monitor
Structure for transport to be monitored.
struct transport_monitor_notifier
Macros
#define ACTIVE_TRANSPORTS_BUCKETS 127
Number of buckets for monitored active transports.
Functions
static AO2_GLOBAL_OBJ_STATIC (active_transports)
Global container of active reliable transports.
AO2_STRING_FIELD_CMP_FN (transport_monitor, transport->obj_name)
Comparison function for struct transport_monitor.
AO2_STRING_FIELD_HASH_FN (transport_monitor, transport->obj_name)
Hashing function for struct transport_monitor.
void ast_sip_destroy_transport_events (void)
int ast_sip_initialize_transport_events (void)
enum ast_transport_monitor_reg ast_sip_transport_monitor_register (pjsip_transport *transport, ast_transport_monitor_shutdown_cb cb, void *ao2_data)
Register a reliable transport shutdown monitor callback.
enum ast_transport_monitor_reg ast_sip_transport_monitor_register_replace (pjsip_transport *transport, ast_transport_monitor_shutdown_cb cb, void *ao2_data, ast_transport_monitor_data_matcher matches)
Register a reliable transport shutdown monitor callback replacing any duplicate.
void ast_sip_transport_monitor_unregister (pjsip_transport *transport, ast_transport_monitor_shutdown_cb cb, void *data, ast_transport_monitor_data_matcher matches)
Unregister a reliable transport shutdown monitor.
void ast_sip_transport_monitor_unregister_all (ast_transport_monitor_shutdown_cb cb, void *data, ast_transport_monitor_data_matcher matches)
Unregister a transport shutdown monitor from all reliable transports.
void ast_sip_transport_state_register (struct ast_sip_tpmgr_state_callback *element)
Register a transport state notification callback element.
void ast_sip_transport_state_unregister (struct ast_sip_tpmgr_state_callback *element)
Unregister a transport state notification callback element.
static int ptr_matcher (void *a, void *b)
static void transport_monitor_dtor (void *vdoomed)
static int transport_monitor_unregister_cb (void *obj, void *arg, int flags)
static const char * transport_state2str (pjsip_transport_state state)
static void transport_state_callback (pjsip_transport *transport, pjsip_transport_state state, const pjsip_transport_state_info *info)
Callback invoked when transport state changes occur.
static void transport_state_do_reg_callbacks (struct ao2_container *transports, pjsip_transport *transport)
Variables
static pjsip_tp_state_callback tpmgr_state_callback
Existing transport events callback that we need to invoke.
struct {
struct ast_sip_tpmgr_state_callback * first
struct ast_sip_tpmgr_state_callback * last
ast_rwlock_t lock
} transport_state_list
Detailed Description
Manages the global transport event notification callbacks.
Author
Richard Mudgett rmudg.nosp@m.ett@.nosp@m.digiu.nosp@m.m.co.nosp@m.m See Also:
CREDITS
Definition in file pjsip_transport_events.c.
Macro Definition Documentation
ACTIVE_TRANSPORTS_BUCKETS
#define ACTIVE_TRANSPORTS_BUCKETS 127
Number of buckets for monitored active transports.
Definition at line 40 of file pjsip_transport_events.c.
Referenced by ast_sip_initialize_transport_events().
Function Documentation
AO2_GLOBAL_OBJ_STATIC()
static AO2_GLOBAL_OBJ_STATIC (active_transports) static
Global container of active reliable transports.
AO2_STRING_FIELD_CMP_FN()
AO2_STRING_FIELD_CMP_FN (transport_monitor , transport-> obj_name)
Comparison function for struct transport_monitor.
AO2_STRING_FIELD_HASH_FN()
AO2_STRING_FIELD_HASH_FN (transport_monitor , transport-> obj_name)
Hashing function for struct transport_monitor.
ast_sip_destroy_transport_events()
void ast_sip_destroy_transport_events (void)
Definition at line 382 of file pjsip_transport_events.c.
References ao2_global_obj_release, ast_sip_get_pjsip_endpoint(), and tpmgr_state_callback.
Referenced by unload_pjsip().
 {
    pjsip_tpmgr *tpmgr;
    tpmgr = pjsip_endpt_get_tpmgr(ast_sip_get_pjsip_endpoint());
    if (tpmgr) {
       pjsip_tpmgr_set_state_cb(tpmgr, tpmgr_state_callback);
    }
    ao2_global_obj_release(active_transports);
 }
ast_sip_initialize_transport_events()
int ast_sip_initialize_transport_events (void)
Definition at line 394 of file pjsip_transport_events.c.
References ACTIVE_TRANSPORTS_BUCKETS, AO2_ALLOC_OPT_LOCK_MUTEX, ao2_container_alloc_hash, ao2_global_obj_replace_unref, ao2_ref, ast_sip_get_pjsip_endpoint(), NULL, tpmgr_state_callback, and transport_state_callback().
Referenced by load_module().
 {
    pjsip_tpmgr *tpmgr;
    struct ao2_container *transports;
    tpmgr = pjsip_endpt_get_tpmgr(ast_sip_get_pjsip_endpoint());
    if (!tpmgr) {
       return -1;
    }
    transports = ao2_container_alloc_hash(AO2_ALLOC_OPT_LOCK_MUTEX, 0,
       ACTIVE_TRANSPORTS_BUCKETS, transport_monitor_hash_fn, NULL,
       transport_monitor_cmp_fn);
    if (!transports) {
       return -1;
    }
    ao2_global_obj_replace_unref(active_transports, transports);
    ao2_ref(transports, -1);
    tpmgr_state_callback = pjsip_tpmgr_get_state_cb(tpmgr);
    pjsip_tpmgr_set_state_cb(tpmgr, &transport_state_callback);
    return 0;
 }
ast_sip_transport_monitor_register()
enum ast_transport_monitor_reg ast_sip_transport_monitor_register (pjsip_transport * transport, ast_transport_monitor_shutdown_cb cb, void * ao2_data)
Register a reliable transport shutdown monitor callback.
Since
13.20.0
Parameters
transport Transport to monitor for shutdown.
cb Who to call when transport is shutdown.
ao2_data Data to pass with the callback.
Note
The data object passed will have its reference count automatically incremented by this call and automatically decremented after the callback runs or when the callback is unregistered.
There is no checking for duplicate registrations.
Returns
enum ast_transport_monitor_reg
Definition at line 306 of file pjsip_transport_events.c.
References ast_sip_transport_monitor_register_replace(), and NULL.
Referenced by registration_transport_monitor_setup(), and subscription_persistence_update().
 {
    return ast_sip_transport_monitor_register_replace(transport, cb, ao2_data, NULL);
 }
ast_sip_transport_monitor_register_replace()
enum ast_transport_monitor_reg ast_sip_transport_monitor_register_replace (pjsip_transport * transport, ast_transport_monitor_shutdown_cb cb, void * ao2_data, ast_transport_monitor_data_matcher matches)
Register a reliable transport shutdown monitor callback replacing any duplicate.
Since
13.26.0
16.3.0
Parameters
transport Transport to monitor for shutdown.
cb Who to call when transport is shutdown.
ao2_data Data to pass with the callback.
matches Matcher function that returns true if data matches a previously registered data object
Note
The data object passed will have its reference count automatically incremented by this call and automatically decremented after the callback runs or when the callback is unregistered.
This function checks for duplicates, and overwrites/replaces the old monitor with the given one.
Returns
enum ast_transport_monitor_reg
Definition at line 312 of file pjsip_transport_events.c.
References ao2_bump, ao2_cleanup, ao2_find, ao2_global_obj_ref, ao2_lock, ao2_ref, ao2_unlock, ast_assert, ast_debug, AST_TRANSPORT_MONITOR_REG_FAILED, AST_TRANSPORT_MONITOR_REG_NOT_FOUND, AST_TRANSPORT_MONITOR_REG_SUCCESS, AST_VECTOR_APPEND, transport_monitor_notifier::cb, callback_data::cb, transport_monitor_notifier::data, NULL, OBJ_NOLOCK, OBJ_SEARCH_KEY, ptr_matcher(), and transport_monitor_unregister_cb().
Referenced by ast_sip_transport_monitor_register(), and register_aor_core().
 {
    struct ao2_container *transports;
    struct transport_monitor *monitored;
    enum ast_transport_monitor_reg res = AST_TRANSPORT_MONITOR_REG_NOT_FOUND;
    ast_assert(transport != NULL && cb != NULL);
    transports = ao2_global_obj_ref(active_transports);
    if (!transports) {
       return res;
    }
    ao2_lock(transports);
    monitored = ao2_find(transports, transport->obj_name, OBJ_SEARCH_KEY | OBJ_NOLOCK);
    if (monitored) {
       struct transport_monitor_notifier new_monitor;
       struct callback_data cb_data = {
          .cb = cb,
          .data = ao2_data,
          .matches = matches ?: ptr_matcher,
       };
       transport_monitor_unregister_cb(monitored, &cb_data, 0);
       /* Add new monitor to vector */
       new_monitor.cb = cb;
       new_monitor.data = ao2_bump(ao2_data);
       if (AST_VECTOR_APPEND(&monitored->monitors, new_monitor)) {
          ao2_cleanup(ao2_data);
          res = AST_TRANSPORT_MONITOR_REG_FAILED;
          ast_debug(3, "Register monitor %p(%p) to transport %s FAILED\n",
             cb, ao2_data, transport->obj_name);
       } else {
          res = AST_TRANSPORT_MONITOR_REG_SUCCESS;
          ast_debug(3, "Registered monitor %p(%p) to transport %s\n",
             cb, ao2_data, transport->obj_name);
       }
       ao2_ref(monitored, -1);
    }
    ao2_unlock(transports);
    ao2_ref(transports, -1);
    return res;
 }
ast_sip_transport_monitor_unregister()
void ast_sip_transport_monitor_unregister (pjsip_transport * transport, ast_transport_monitor_shutdown_cb cb, void * data, ast_transport_monitor_data_matcher matches)
Unregister a reliable transport shutdown monitor.
Since
13.20.0
Parameters
transport Transport to monitor for shutdown.
cb The callback that was used for the original register.
data Data to pass to the matcher. May be NULL and does NOT need to be an ao2 object. If NULL, all monitors with the provided callbck are unregistered.
matches Matcher function that returns true if data matches the previously registered data object. If NULL, a simple pointer comparison is done.
Note
The data object passed into the original register will have its reference count automatically decremeneted.
Returns
Nothing
Definition at line 277 of file pjsip_transport_events.c.
References ao2_find, ao2_global_obj_ref, ao2_lock, ao2_ref, ao2_unlock, ast_assert, transport_monitor_notifier::cb, callback_data::cb, transport_monitor_notifier::data, NULL, OBJ_NOLOCK, OBJ_SEARCH_KEY, ptr_matcher(), and transport_monitor_unregister_cb().
Referenced by handle_registration_response(), registrar_contact_delete(), and subscription_persistence_remove().
 {
    struct ao2_container *transports;
    struct transport_monitor *monitored;
    ast_assert(transport != NULL && cb != NULL);
    transports = ao2_global_obj_ref(active_transports);
    if (!transports) {
       return;
    }
    ao2_lock(transports);
    monitored = ao2_find(transports, transport->obj_name, OBJ_SEARCH_KEY | OBJ_NOLOCK);
    if (monitored) {
       struct callback_data cb_data = {
          .cb = cb,
          .data = data,
          .matches = matches ?: ptr_matcher,
       };
       transport_monitor_unregister_cb(monitored, &cb_data, 0);
       ao2_ref(monitored, -1);
    }
    ao2_unlock(transports);
    ao2_ref(transports, -1);
 }
ast_sip_transport_monitor_unregister_all()
void ast_sip_transport_monitor_unregister_all (ast_transport_monitor_shutdown_cb cb, void * data, ast_transport_monitor_data_matcher matches)
Unregister a transport shutdown monitor from all reliable transports.
Since
13.20.0
Parameters
cb The callback that was used for the original register.
data Data to pass to the matcher. May be NULL and does NOT need to be an ao2 object. If NULL, all monitors with the provided callbck are unregistered.
matches Matcher function that returns true if ao2_data matches the previously registered data object. If NULL, a simple pointer comparison is done.
Note
The data object passed into the original register will have its reference count automatically decremeneted.
Returns
Nothing
Definition at line 257 of file pjsip_transport_events.c.
References ao2_callback, ao2_global_obj_ref, ao2_ref, ast_assert, transport_monitor_notifier::cb, callback_data::cb, transport_monitor_notifier::data, NULL, OBJ_MULTIPLE, OBJ_NODATA, ptr_matcher(), and transport_monitor_unregister_cb().
Referenced by registrar_contact_delete(), and unload_module().
 {
    struct ao2_container *transports;
    struct callback_data cb_data = {
       .cb = cb,
       .data = data,
       .matches = matches ?: ptr_matcher,
    };
    ast_assert(cb != NULL);
    transports = ao2_global_obj_ref(active_transports);
    if (!transports) {
       return;
    }
    ao2_callback(transports, OBJ_MULTIPLE | OBJ_NODATA, transport_monitor_unregister_cb, &cb_data);
    ao2_ref(transports, -1);
 }
ast_sip_transport_state_register()
void ast_sip_transport_state_register (struct ast_sip_tpmgr_state_callback * element)
Register a transport state notification callback element.
Since
13.18.0
Parameters
element What we are registering.
Returns
Nothing
Definition at line 366 of file pjsip_transport_events.c.
References AST_LIST_INSERT_HEAD, AST_LIST_TRAVERSE, AST_RWLIST_UNLOCK, AST_RWLIST_WRLOCK, and transport_state_list.
Referenced by ast_sip_initialize_transport_management().
 {
    struct ast_sip_tpmgr_state_callback *tpmgr_notifier;
    AST_RWLIST_WRLOCK(&transport_state_list);
    AST_LIST_TRAVERSE(&transport_state_list, tpmgr_notifier, node) {
       if (element == tpmgr_notifier) {
          /* Already registered. */
          AST_RWLIST_UNLOCK(&transport_state_list);
          return;
       }
    }
    AST_LIST_INSERT_HEAD(&transport_state_list, element, node);
    AST_RWLIST_UNLOCK(&transport_state_list);
 }
ast_sip_transport_state_unregister()
void ast_sip_transport_state_unregister (struct ast_sip_tpmgr_state_callback * element)
Unregister a transport state notification callback element.
Since
13.18.0
Parameters
element What we are unregistering.
Returns
Nothing
Definition at line 359 of file pjsip_transport_events.c.
References AST_LIST_REMOVE, AST_RWLIST_UNLOCK, AST_RWLIST_WRLOCK, and transport_state_list.
Referenced by ast_sip_destroy_transport_management().
 {
    AST_RWLIST_WRLOCK(&transport_state_list);
    AST_LIST_REMOVE(&transport_state_list, element, node);
    AST_RWLIST_UNLOCK(&transport_state_list);
 }
ptr_matcher()
static int ptr_matcher (void * a, void * b) static
Definition at line 252 of file pjsip_transport_events.c.
References b.
Referenced by ast_sip_transport_monitor_register_replace(), ast_sip_transport_monitor_unregister(), and ast_sip_transport_monitor_unregister_all().
 {
    return a == b;
 }
transport_monitor_dtor()
static void transport_monitor_dtor (void * vdoomed) static
Definition at line 103 of file pjsip_transport_events.c.
References ao2_cleanup, AST_VECTOR_FREE, AST_VECTOR_GET_ADDR, AST_VECTOR_SIZE, and transport_monitor_notifier::data.
Referenced by transport_state_callback().
 {
    struct transport_monitor *monitored = vdoomed;
    int idx;
    for (idx = AST_VECTOR_SIZE(&monitored->monitors); idx--;) {
       struct transport_monitor_notifier *notifier;
       notifier = AST_VECTOR_GET_ADDR(&monitored->monitors, idx);
       ao2_cleanup(notifier->data);
    }
    AST_VECTOR_FREE(&monitored->monitors);
 }
transport_monitor_unregister_cb()
static int transport_monitor_unregister_cb (void * obj, void * arg, int flags) static
Definition at line 231 of file pjsip_transport_events.c.
References ao2_cleanup, ast_debug, AST_VECTOR_GET_ADDR, AST_VECTOR_REMOVE_UNORDERED, AST_VECTOR_SIZE, transport_monitor_notifier::cb, callback_data::cb, transport_monitor_notifier::data, callback_data::data, callback_data::matches, and transport_monitor::transport.
Referenced by ast_sip_transport_monitor_register_replace(), ast_sip_transport_monitor_unregister(), and ast_sip_transport_monitor_unregister_all().
 {
    struct transport_monitor *monitored = obj;
    struct callback_data *cb_data = arg;
    int idx;
    for (idx = AST_VECTOR_SIZE(&monitored->monitors); idx--;) {
       struct transport_monitor_notifier *notifier;
       notifier = AST_VECTOR_GET_ADDR(&monitored->monitors, idx);
       if (notifier->cb == cb_data->cb && (!cb_data->data
          || cb_data->matches(cb_data->data, notifier->data))) {
          ao2_cleanup(notifier->data);
          AST_VECTOR_REMOVE_UNORDERED(&monitored->monitors, idx);
          ast_debug(3, "Unregistered monitor %p(%p) from transport %s\n",
             notifier->cb, notifier->data, monitored->transport->obj_name);
       }
    }
    return 0;
 }
transport_state2str()
static const char* transport_state2str (pjsip_transport_state state) static
Definition at line 74 of file pjsip_transport_events.c.
References ast_assert, and name.
Referenced by transport_state_callback().
 {
    const char *name;
    switch (state) {
    case PJSIP_TP_STATE_CONNECTED:
       name = "CONNECTED";
       break;
    case PJSIP_TP_STATE_DISCONNECTED:
       name = "DISCONNECTED";
       break;
    case PJSIP_TP_STATE_SHUTDOWN:
       name = "SHUTDOWN";
       break;
    case PJSIP_TP_STATE_DESTROY:
       name = "DESTROY";
       break;
    default:
       /*
        * We have to have a default case because the enum is
        * defined by a third-party library.
        */
       ast_assert(0);
       name = "<unknown>";
       break;
    }
    return name;
 }
transport_state_callback()
static void transport_state_callback (pjsip_transport * transport, pjsip_transport_state state, const pjsip_transport_state_info * info) static
Callback invoked when transport state changes occur.
Definition at line 148 of file pjsip_transport_events.c.
References AO2_ALLOC_OPT_LOCK_NOLOCK, ao2_alloc_options, ao2_global_obj_ref, ao2_link, ao2_ref, ast_assert, ast_debug, AST_LIST_EMPTY, AST_LIST_TRAVERSE, AST_RWLIST_RDLOCK, AST_RWLIST_UNLOCK, AST_VECTOR_INIT, ast_sip_tpmgr_state_callback::cb, tpmgr_state_callback, transport_monitor::transport, transport_monitor_dtor(), transport_state2str(), transport_state_do_reg_callbacks(), and transport_state_list.
Referenced by ast_sip_initialize_transport_events().
 {
    struct ao2_container *transports;
    /* We only care about monitoring reliable transports */
    if (PJSIP_TRANSPORT_IS_RELIABLE(transport)
       && (transports = ao2_global_obj_ref(active_transports))) {
       struct transport_monitor *monitored;
       ast_debug(3, "Reliable transport '%s' state:%s\n",
          transport->obj_name, transport_state2str(state));
       switch (state) {
       case PJSIP_TP_STATE_CONNECTED:
          monitored = ao2_alloc_options(sizeof(*monitored),
             transport_monitor_dtor, AO2_ALLOC_OPT_LOCK_NOLOCK);
          if (!monitored) {
             break;
          }
          monitored->transport = transport;
          if (AST_VECTOR_INIT(&monitored->monitors, 5)) {
             ao2_ref(monitored, -1);
             break;
          }
          ao2_link(transports, monitored);
          ao2_ref(monitored, -1);
          break;
       case PJSIP_TP_STATE_DISCONNECTED:
          if (!transport->is_shutdown) {
             pjsip_transport_shutdown(transport);
          }
          transport_state_do_reg_callbacks(transports, transport);
          break;
       case PJSIP_TP_STATE_SHUTDOWN:
          /*
           * Set shutdown flag early so we can force a new transport to be
           * created if a monitor callback needs to reestablish a link.
           * PJPROJECT sets the flag after this routine returns even though
           * it has already called the transport's shutdown routine.
           */
          transport->is_shutdown = PJ_TRUE;
          transport_state_do_reg_callbacks(transports, transport);
          break;
       case PJSIP_TP_STATE_DESTROY:
          transport_state_do_reg_callbacks(transports, transport);
          break;
       default:
          /*
           * We have to have a default case because the enum is
           * defined by a third-party library.
           */
          ast_assert(0);
          break;
       }
       ao2_ref(transports, -1);
    }
    /* Loop over other transport state callbacks registered with us. */
    if (!AST_LIST_EMPTY(&transport_state_list)) {
       struct ast_sip_tpmgr_state_callback *tpmgr_notifier;
       AST_RWLIST_RDLOCK(&transport_state_list);
       AST_LIST_TRAVERSE(&transport_state_list, tpmgr_notifier, node) {
          tpmgr_notifier->cb(transport, state, info);
       }
       AST_RWLIST_UNLOCK(&transport_state_list);
    }
    /* Forward to the old state callback if present */
    if (tpmgr_state_callback) {
       tpmgr_state_callback(transport, state, info);
    }
 }
transport_state_do_reg_callbacks()
static void transport_state_do_reg_callbacks (struct ao2_container * transports, pjsip_transport * transport) static
Definition at line 127 of file pjsip_transport_events.c.
References ao2_find, ao2_ref, ast_debug, AST_VECTOR_GET_ADDR, AST_VECTOR_SIZE, transport_monitor_notifier::cb, transport_monitor_notifier::data, OBJ_SEARCH_KEY, and OBJ_UNLINK.
Referenced by transport_state_callback().
 {
    struct transport_monitor *monitored;
    monitored = ao2_find(transports, transport->obj_name, OBJ_SEARCH_KEY | OBJ_UNLINK);
    if (monitored) {
       int idx;
       for (idx = AST_VECTOR_SIZE(&monitored->monitors); idx--;) {
          struct transport_monitor_notifier *notifier;
          notifier = AST_VECTOR_GET_ADDR(&monitored->monitors, idx);
          ast_debug(3, "running callback %p(%p) for transport %s\n",
             notifier->cb, notifier->data, transport->obj_name);
          notifier->cb(notifier->data);
       }
       ao2_ref(monitored, -1);
    }
 }
Variable Documentation
first
struct ast_sip_tpmgr_state_callback* first
Definition at line 65 of file pjsip_transport_events.c.
last
struct ast_sip_tpmgr_state_callback* last
Definition at line 65 of file pjsip_transport_events.c.
lock
ast_rwlock_t lock
Definition at line 65 of file pjsip_transport_events.c.
tpmgr_state_callback
pjsip_tp_state_callback tpmgr_state_callback static
Existing transport events callback that we need to invoke.
Definition at line 62 of file pjsip_transport_events.c.
Referenced by ast_sip_destroy_transport_events(), ast_sip_initialize_transport_events(), and transport_state_callback().
transport_state_list
struct { ... } transport_state_list
List of registered transport state callbacks.
Referenced by ast_sip_transport_state_register(), ast_sip_transport_state_unregister(), and transport_state_callback().