Asterisk - The Open Source Telephony Project: func_enum.c File Reference
func_enum.c File Reference
Module: Dial plan functions
ENUM Functions.
#include "asterisk.h"
#include "asterisk/module.h"
#include "asterisk/channel.h"
#include "asterisk/pbx.h"
#include "asterisk/utils.h"
#include "asterisk/lock.h"
#include "asterisk/file.h"
#include "asterisk/enum.h"
#include "asterisk/app.h"
Data Structures
struct enum_result_datastore
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int enum_query_read (struct ast_channel *chan, const char *cmd, char *data, char *buf, size_t len)
static int enum_result_read (struct ast_channel *chan, const char *cmd, char *data, char *buf, size_t len)
static void erds_destroy (struct enum_result_datastore *data)
static void erds_destroy_cb (void *data)
static int function_enum (struct ast_channel *chan, const char *cmd, char *data, char *buf, size_t len)
static int function_txtcidname (struct ast_channel *chan, const char *cmd, char *data, char *buf, size_t len)
static int load_module (void)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_DEFAULT , .description = "ENUM related dialplan functions" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .requires = "enum", }
static const struct ast_module_info * ast_module_info = &__mod_info
static unsigned int enum_datastore_id
static struct ast_custom_function enum_function
static struct ast_custom_function enum_query_function
static const struct ast_datastore_info enum_result_datastore_info
static struct ast_custom_function enum_result_function
static char * synopsis = "Syntax: ENUMLOOKUP(number[,Method-type[,options[,record#[,zone-suffix]]]])\n"
static struct ast_custom_function txtcidname_function
Detailed Description
ENUM Functions.
Author
Mark Spencer marks.nosp@m.ter@.nosp@m.digiu.nosp@m.m.co.nosp@m.m
Oleksiy Krivoshey oleks.nosp@m.iyk@.nosp@m.gmail.nosp@m..com
Russell Bryant russe.nosp@m.lb@c.nosp@m.lemso.nosp@m.n.ed.nosp@m.u
Brett Bryant bbrya.nosp@m.nt@d.nosp@m.igium.nosp@m..com
See also AstENUM
Definition in file func_enum.c.
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 480 of file func_enum.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 480 of file func_enum.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 480 of file func_enum.c.
enum_query_read()
static int enum_query_read (struct ast_channel * chan, const char * cmd, char * data, char * buf, size_t len) static
Definition at line 252 of file func_enum.c.
References args, AST_APP_ARG, ast_atomic_fetchadd_int(), ast_calloc, ast_channel_datastore_add(), ast_channel_lock, ast_channel_unlock, ast_copy_string(), ast_datastore_alloc, AST_DECLARE_APP_ARGS, ast_free, ast_get_enum(), ast_log, AST_STANDARD_APP_ARGS, ast_strdupa, ast_strlen_zero, enum_result_datastore::context, ast_datastore::data, enum_datastore_id, enum_result_datastore::id, LOG_ERROR, LOG_WARNING, and parse().
 {
    struct enum_result_datastore *erds;
    struct ast_datastore *datastore;
    char *parse, tech[128], dest[128];
    int res = -1;
    AST_DECLARE_APP_ARGS(args,
       AST_APP_ARG(number);
       AST_APP_ARG(tech);
       AST_APP_ARG(zone);
    );
    if (ast_strlen_zero(data)) {
       ast_log(LOG_WARNING, "ENUMQUERY requires at least a number as an argument...\n");
       goto finish;
    }
    parse = ast_strdupa(data);
    AST_STANDARD_APP_ARGS(args, parse);
    if (!chan) {
       ast_log(LOG_ERROR, "ENUMQUERY cannot be used without a channel!\n");
       goto finish;
    }
    if (!args.zone)
       args.zone = "e164.zone";
    ast_copy_string(tech, args.tech ? args.tech : "sip", sizeof(tech));
    if (!(erds = ast_calloc(1, sizeof(*erds))))
       goto finish;
    if (!(erds->context = ast_calloc(1, sizeof(*erds->context)))) {
       ast_free(erds);
       goto finish;
    }
    erds->id = ast_atomic_fetchadd_int((int *) &enum_datastore_id, 1);
    snprintf(buf, len, "%u", erds->id);
    if (!(datastore = ast_datastore_alloc(&enum_result_datastore_info, buf))) {
       ast_free(erds->context);
       ast_free(erds);
       goto finish;
    }
    ast_get_enum(chan, args.number, dest, sizeof(dest), tech, sizeof(tech), args.zone, "", 1, &erds->context);
    datastore->data = erds;
    ast_channel_lock(chan);
    ast_channel_datastore_add(chan, datastore);
    ast_channel_unlock(chan);
    res = 0;
 finish:
    return res;
 }
enum_result_read()
static int enum_result_read (struct ast_channel * chan, const char * cmd, char * data, char * buf, size_t len) static
Definition at line 317 of file func_enum.c.
References args, AST_APP_ARG, ast_channel_datastore_find(), ast_channel_lock, ast_channel_unlock, ast_copy_string(), AST_DECLARE_APP_ARGS, ast_log, AST_STANDARD_APP_ARGS, ast_strdupa, ast_strlen_zero, enum_result_datastore::context, ast_datastore::data, LOG_ERROR, LOG_WARNING, enum_context::naptr_rrs, enum_context::naptr_rrs_count, parse(), enum_naptr_rr::result, enum_naptr_rr::sort_pos, and enum_naptr_rr::tech.
 {
    struct enum_result_datastore *erds;
    struct ast_datastore *datastore;
    char *parse, *p;
    unsigned int num;
    int res = -1, k;
    AST_DECLARE_APP_ARGS(args,
       AST_APP_ARG(id);
       AST_APP_ARG(resultnum);
    );
    if (ast_strlen_zero(data)) {
       ast_log(LOG_WARNING, "ENUMRESULT requires two arguments (id and resultnum)\n");
       goto finish;
    }
    if (!chan) {
       ast_log(LOG_ERROR, "ENUMRESULT can not be used without a channel!\n");
       goto finish;
    }
    parse = ast_strdupa(data);
    AST_STANDARD_APP_ARGS(args, parse);
    if (ast_strlen_zero(args.id)) {
       ast_log(LOG_ERROR, "A result ID must be provided to ENUMRESULT\n");
       goto finish;
    }
    if (ast_strlen_zero(args.resultnum)) {
       ast_log(LOG_ERROR, "A result number must be given to ENUMRESULT!\n");
       goto finish;
    }
    ast_channel_lock(chan);
    datastore = ast_channel_datastore_find(chan, &enum_result_datastore_info, args.id);
    ast_channel_unlock(chan);
    if (!datastore) {
       ast_log(LOG_WARNING, "No ENUM results found for query id!\n");
       goto finish;
    }
    erds = datastore->data;
    if (!strcasecmp(args.resultnum, "getnum")) {
       snprintf(buf, len, "%d", erds->context->naptr_rrs_count);
       res = 0;
       goto finish;
    }
    if (sscanf(args.resultnum, "%30u", &num) != 1) {
       ast_log(LOG_ERROR, "Invalid value '%s' for resultnum to ENUMRESULT!\n", args.resultnum);
       goto finish;
    }
    if (!num || num > erds->context->naptr_rrs_count) {
       ast_log(LOG_WARNING, "Result number %u is not valid for ENUM query results for ID %s!\n", num, args.id);
       goto finish;
    }
    for (k = 0; k < erds->context->naptr_rrs_count; k++) {
       if (num - 1 != erds->context->naptr_rrs[k].sort_pos)
          continue;
       p = strchr(erds->context->naptr_rrs[k].result, ':');
       if (p && strcasecmp(erds->context->naptr_rrs[k].tech, "ALL"))
          ast_copy_string(buf, p + 1, len);
       else
          ast_copy_string(buf, erds->context->naptr_rrs[k].result, len);
       break;
    }
    res = 0;
 finish:
    return res;
 }
erds_destroy()
static void erds_destroy (struct enum_result_datastore * data) static
Definition at line 227 of file func_enum.c.
References ast_free, enum_result_datastore::context, enum_context::naptr_rrs, enum_context::naptr_rrs_count, enum_naptr_rr::result, and enum_naptr_rr::tech.
Referenced by erds_destroy_cb().
 {
    int k;
    for (k = 0; k < data->context->naptr_rrs_count; k++) {
       ast_free(data->context->naptr_rrs[k].result);
       ast_free(data->context->naptr_rrs[k].tech);
    }
    ast_free(data->context->naptr_rrs);
    ast_free(data->context);
    ast_free(data);
 }
erds_destroy_cb()
static void erds_destroy_cb (void * data) static
Definition at line 241 of file func_enum.c.
References erds_destroy().
 {
    struct enum_result_datastore *erds = data;
    erds_destroy(erds);
 }
function_enum()
static int function_enum (struct ast_channel * chan, const char * cmd, char * data, char * buf, size_t len) static
Definition at line 156 of file func_enum.c.
References args, AST_APP_ARG, ast_copy_string(), AST_DECLARE_APP_ARGS, ast_get_enum(), ast_log, AST_MAX_EXTENSION, AST_STANDARD_APP_ARGS, ast_strlen_zero, LOG_WARNING, NULL, options, synopsis, and tmp().
 {
    AST_DECLARE_APP_ARGS(args,
       AST_APP_ARG(number);
       AST_APP_ARG(tech);
       AST_APP_ARG(options);
       AST_APP_ARG(record);
       AST_APP_ARG(zone);
    );
    char tech[80];
    char dest[256] = "", tmp[2] = "", num[AST_MAX_EXTENSION] = "";
    char *s, *p;
    unsigned int record = 1;
    buf[0] = '\0';
    if (ast_strlen_zero(data)) {
       ast_log(LOG_WARNING, "%s", synopsis);
       return -1;
    }
    AST_STANDARD_APP_ARGS(args, data);
    if (args.argc < 1) {
       ast_log(LOG_WARNING, "%s", synopsis);
       return -1;
    }
    if (args.tech && !ast_strlen_zero(args.tech)) {
       ast_copy_string(tech,args.tech, sizeof(tech));
    } else {
       ast_copy_string(tech,"sip",sizeof(tech));
    }
    if (!args.zone) {
       args.zone = "e164.arpa";
    }
    if (!args.options) {
       args.options = "";
    }
    if (args.record) {
       record = atoi(args.record) ? atoi(args.record) : record;
    }
    /* strip any '-' signs from number */
    for (s = p = args.number; *s; s++) {
       if (*s != '-') {
          snprintf(tmp, sizeof(tmp), "%c", *s);
          strncat(num, tmp, sizeof(num) - strlen(num) - 1);
       }
    }
    ast_get_enum(chan, num, dest, sizeof(dest), tech, sizeof(tech), args.zone, args.options, record, NULL);
    p = strchr(dest, ':');
    if (p && strcasecmp(tech, "ALL") && !strchr(args.options, 'u')) {
       ast_copy_string(buf, p + 1, len);
    } else {
       ast_copy_string(buf, dest, len);
    }
    return 0;
 }
function_txtcidname()
static int function_txtcidname (struct ast_channel * chan, const char * cmd, char * data, char * buf, size_t len) static
Definition at line 415 of file func_enum.c.
References args, AST_APP_ARG, AST_DECLARE_APP_ARGS, ast_get_txt(), ast_log, AST_STANDARD_APP_ARGS, ast_strlen_zero, and LOG_WARNING.
 {
    AST_DECLARE_APP_ARGS(args,
       AST_APP_ARG(number);
       AST_APP_ARG(zone);
    );
    buf[0] = '\0';
    if (ast_strlen_zero(data)) {
       ast_log(LOG_WARNING, "Syntax: TXTCIDNAME(number[,zone-suffix])\n");
       return -1;
    }
    AST_STANDARD_APP_ARGS(args, data);
    if (args.argc < 1) {
       ast_log(LOG_WARNING, "Syntax: TXTCIDNAME(number[,zone-suffix])\n");
       return -1;
    }
    if (!args.zone) {
       args.zone = "e164.arpa";
    }
    ast_get_txt(chan, args.number, buf, len, args.zone);
    return 0;
 }
load_module()
static int load_module (void) static
Definition at line 463 of file func_enum.c.
References ast_custom_function_register, AST_MODFLAG_DEFAULT, AST_MODULE_INFO(), AST_MODULE_SUPPORT_CORE, ASTERISK_GPL_KEY, and unload_module().
 {
    int res = 0;
    res |= ast_custom_function_register(&enum_result_function);
    res |= ast_custom_function_register(&enum_query_function);
    res |= ast_custom_function_register(&enum_function);
    res |= ast_custom_function_register(&txtcidname_function);
    return res;
 }
unload_module()
static int unload_module (void) static
Definition at line 451 of file func_enum.c.
References ast_custom_function_unregister().
Referenced by load_module().
 {
    int res = 0;
    res |= ast_custom_function_unregister(&enum_result_function);
    res |= ast_custom_function_unregister(&enum_query_function);
    res |= ast_custom_function_unregister(&enum_function);
    res |= ast_custom_function_unregister(&txtcidname_function);
    return res;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_DEFAULT , .description = "ENUM related dialplan functions" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .requires = "enum", } static
Definition at line 480 of file func_enum.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 480 of file func_enum.c.
enum_datastore_id
unsigned int enum_datastore_id static
Definition at line 220 of file func_enum.c.
Referenced by enum_query_read().
enum_function
struct ast_custom_function enum_function static
Initial value:
= {
   .name = "ENUMLOOKUP",
   .read = function_enum,
}
Definition at line 410 of file func_enum.c.
enum_query_function
struct ast_custom_function enum_query_function static
Initial value:
= {
   .name = "ENUMQUERY",
   .read = enum_query_read,
}
Definition at line 400 of file func_enum.c.
enum_result_datastore_info
const struct ast_datastore_info enum_result_datastore_info static
Initial value:
= {
   .type = "ENUMQUERY",
   .destroy = erds_destroy_cb,
}
Definition at line 247 of file func_enum.c.
enum_result_function
struct ast_custom_function enum_result_function static
Initial value:
= {
   .name = "ENUMRESULT",
   .read = enum_result_read,
}
Definition at line 405 of file func_enum.c.
synopsis
char* synopsis = "Syntax: ENUMLOOKUP(number[,Method-type[,options[,record#[,zone-suffix]]]])\n" static
Definition at line 154 of file func_enum.c.
Referenced by function_enum().
txtcidname_function
struct ast_custom_function txtcidname_function static
Initial value:
= {
   .name = "TXTCIDNAME",
   .read = function_txtcidname,
}
Definition at line 446 of file func_enum.c.