Asterisk - The Open Source Telephony Project: chan_oss.c File Reference
chan_oss.c File Reference
Module: Asterisk Channel Drivers
Channel driver for OSS sound cards.
#include "asterisk.h"
#include <ctype.h>
#include <math.h>
#include <sys/ioctl.h>
#include <soundcard.h>
#include "asterisk/channel.h"
#include "asterisk/file.h"
#include "asterisk/callerid.h"
#include "asterisk/module.h"
#include "asterisk/pbx.h"
#include "asterisk/cli.h"
#include "asterisk/causes.h"
#include "asterisk/musiconhold.h"
#include "asterisk/app.h"
#include "asterisk/bridge.h"
#include "asterisk/format_cache.h"
#include "console_video.h"
Data Structures
struct chan_oss_pvt
descriptor for one of our channels.
Macros
#define BOOST_MAX 40
#define BOOST_SCALE (1<<9)
#define DEV_DSP "/dev/dsp"
#define FRAGS (((6 * 5) << 16) | 0x6)
#define FRAME_SIZE 160
#define O_CLOSE 0x444 /* special 'close' mode for device */
#define QUEUE_SIZE 10
#define TEXT_SIZE 256
#define WARN_frag 4
#define WARN_speed 2
#define WARN_used_blocks 1
Functions
static char * ast_ext_ctx (const char *src, char **ext, char **ctx)
AST_MODULE_INFO_STANDARD_DEPRECATED (ASTERISK_GPL_KEY, "OSS Console Channel Driver")
static char * console_active (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static char * console_answer (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
answer command from the console
static char * console_autoanswer (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static char * console_boost (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static char * console_cmd (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static char * console_dial (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static char * console_do_answer (int fd)
helper function for the answer key/cli command
static char * console_flash (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static char * console_hangup (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static char * console_mute (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static char * console_sendtext (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
Console send text CLI command.
static char * console_transfer (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static struct chan_oss_pvt * find_desc (const char *dev)
returns a pointer to the descriptor with the given name
struct video_desc * get_video_desc (struct ast_channel *c)
return the pointer to the video descriptor
static int load_module (void)
Load the module.
static int oss_answer (struct ast_channel *c)
remote side answered the phone
static int oss_call (struct ast_channel *c, const char *dest, int timeout)
handler for incoming calls. Either autoanswer, or start ringing
static int oss_digit_begin (struct ast_channel *c, char digit)
static int oss_digit_end (struct ast_channel *c, char digit, unsigned int duration)
static int oss_fixup (struct ast_channel *oldchan, struct ast_channel *newchan)
static int oss_hangup (struct ast_channel *c)
static int oss_indicate (struct ast_channel *chan, int cond, const void *data, size_t datalen)
static struct ast_channel * oss_new (struct chan_oss_pvt *o, char *ext, char *ctx, int state, const struct ast_assigned_ids *assignedids, const struct ast_channel *requestor)
allocate a new channel.
static struct ast_frame * oss_read (struct ast_channel *chan)
static struct ast_channel * oss_request (const char *type, struct ast_format_cap *cap, const struct ast_assigned_ids *assignedids, const struct ast_channel *requestor, const char *data, int *cause)
static int oss_text (struct ast_channel *c, const char *text)
static int oss_write (struct ast_channel *c, struct ast_frame *f)
used for data coming from the network
static int setformat (struct chan_oss_pvt *o, int mode)
static int soundcard_writeframe (struct chan_oss_pvt *o, short *data)
static void store_boost (struct chan_oss_pvt *o, const char *s)
store the boost factor
static void store_callerid (struct chan_oss_pvt *o, const char *s)
static struct chan_oss_pvt * store_config (struct ast_config *cfg, char *ctg)
static void store_config_core (struct chan_oss_pvt *o, const char *var, const char *value)
static void store_mixer (struct chan_oss_pvt *o, const char *s)
static int unload_module (void)
static int used_blocks (struct chan_oss_pvt *o)
Returns the number of blocks used in the audio output channel.
Variables
static struct ast_cli_entry cli_oss []
static char * config = "oss.conf"
static struct ast_jb_conf default_jbconf
static struct ast_jb_conf global_jbconf
static char * oss_active
static int oss_debug
static struct chan_oss_pvt oss_default
static struct ast_channel_tech oss_tech
static char tdesc [] = "OSS Console Channel Driver"
Detailed Description
Channel driver for OSS sound cards.
Author
Mark Spencer marks.nosp@m.ter@.nosp@m.digiu.nosp@m.m.co.nosp@m.m
Luigi Rizzo
Definition in file chan_oss.c.
Macro Definition Documentation
BOOST_MAX
#define BOOST_MAX 40
slightly less than 7 bits
Definition at line 285 of file chan_oss.c.
Referenced by store_boost().
BOOST_SCALE
#define BOOST_SCALE (1<<9)
boost support. BOOST_SCALE * 10 ^(BOOST_MAX/20) must be representable in 16 bits to avoid overflows.
Definition at line 284 of file chan_oss.c.
Referenced by console_boost(), oss_read(), and store_boost().
DEV_DSP
#define DEV_DSP "/dev/dsp"
Definition at line 237 of file chan_oss.c.
Referenced by store_config().
FRAGS
#define FRAGS (((6 * 5) << 16) | 0x6)
Definition at line 220 of file chan_oss.c.
FRAME_SIZE
#define FRAME_SIZE 160
Definition at line 214 of file chan_oss.c.
Referenced by oss_read(), and soundcard_writeframe().
O_CLOSE
#define O_CLOSE 0x444 /* special 'close' mode for device */
Definition at line 232 of file chan_oss.c.
Referenced by console_hangup(), oss_hangup(), and setformat().
QUEUE_SIZE
#define QUEUE_SIZE 10
Definition at line 215 of file chan_oss.c.
TEXT_SIZE
#define TEXT_SIZE 256
Definition at line 227 of file chan_oss.c.
Referenced by console_sendtext().
WARN_frag
#define WARN_frag 4
Definition at line 274 of file chan_oss.c.
Referenced by setformat().
WARN_speed
#define WARN_speed 2
Definition at line 273 of file chan_oss.c.
Referenced by setformat().
WARN_used_blocks
#define WARN_used_blocks 1
Definition at line 272 of file chan_oss.c.
Referenced by used_blocks().
Function Documentation
ast_ext_ctx()
static char* ast_ext_ctx (const char * src, char ** ext, char ** ctx) static
Definition at line 402 of file chan_oss.c.
References ast_strdup, chan_oss_pvt::ext, find_desc(), NULL, oss_active, and chan_oss_pvt::overridecontext.
Referenced by console_dial(), and console_transfer().
 {
    struct chan_oss_pvt *o = find_desc(oss_active);
    if (ext == NULL || ctx == NULL)
       return NULL;         /* error */
    *ext = *ctx = NULL;
    if (src && *src != '\0')
       *ext = ast_strdup(src);
    if (*ext == NULL)
       return NULL;
    if (!o->overridecontext) {
       /* parse from the right */
       *ctx = strrchr(*ext, '@');
       if (*ctx)
          *(*ctx)++ = '\0';
    }
    return *ext;
 }
AST_MODULE_INFO_STANDARD_DEPRECATED()
AST_MODULE_INFO_STANDARD_DEPRECATED (ASTERISK_GPL_KEY , "OSS Console Channel Driver")
Referenced by load_module().
console_active()
static char* console_active (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) static
Definition at line 1215 of file chan_oss.c.
References ast_cli_args::argc, ast_cli_args::argv, ast_cli(), CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::command, ast_cli_args::fd, find_desc(), chan_oss_pvt::name, chan_oss_pvt::next, NULL, oss_active, and ast_cli_entry::usage.
 {
    switch (cmd) {
    case CLI_INIT:
       e->command = "console {set|show} active [<device>]";
       e->usage =
          "Usage: console active [device]\n"
          "       If used without a parameter, displays which device is the current\n"
          "       console.  If a device is specified, the console sound device is changed to\n"
          "       the device specified.\n";
       return NULL;
    case CLI_GENERATE:
       return NULL;
    }
    if (a->argc == 3)
       ast_cli(a->fd, "active console is [%s]\n", oss_active);
    else if (a->argc != 4)
       return CLI_SHOWUSAGE;
    else {
       struct chan_oss_pvt *o;
       if (strcmp(a->argv[3], "show") == 0) {
          for (o = oss_default.next; o; o = o->next)
             ast_cli(a->fd, "device [%s] exists\n", o->name);
          return CLI_SUCCESS;
       }
       o = find_desc(a->argv[3]);
       if (o == NULL)
          ast_cli(a->fd, "No device [%s] exists\n", a->argv[3]);
       else
          oss_active = o->name;
    }
    return CLI_SUCCESS;
 }
console_answer()
static char* console_answer (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) static
answer command from the console
Definition at line 983 of file chan_oss.c.
References ast_cli_args::argc, ast_cli_entry::args, CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, ast_cli_entry::command, console_do_answer(), ast_cli_args::fd, NULL, and ast_cli_entry::usage.
 {
    switch (cmd) {
    case CLI_INIT:
       e->command = "console answer";
       e->usage =
          "Usage: console answer\n"
          "       Answers an incoming call on the console (OSS) channel.\n";
       return NULL;
    case CLI_GENERATE:
       return NULL;   /* no completion */
    }
    if (a->argc != e->args)
       return CLI_SHOWUSAGE;
    return console_do_answer(a->fd);
 }
console_autoanswer()
static char* console_autoanswer (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) static
Definition at line 927 of file chan_oss.c.
References ast_cli_args::argc, ast_cli_entry::args, ast_cli_args::argv, ast_cli(), ast_log, chan_oss_pvt::autoanswer, CLI_FAILURE, CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::command, ast_cli_args::fd, find_desc(), LOG_WARNING, NULL, oss_active, and ast_cli_entry::usage.
 {
    struct chan_oss_pvt *o = find_desc(oss_active);
    switch (cmd) {
    case CLI_INIT:
       e->command = "console {set|show} autoanswer [on|off]";
       e->usage =
          "Usage: console {set|show} autoanswer [on|off]\n"
          "       Enables or disables autoanswer feature.  If used without\n"
          "       argument, displays the current on/off status of autoanswer.\n"
          "       The default value of autoanswer is in 'oss.conf'.\n";
       return NULL;
    case CLI_GENERATE:
       return NULL;
    }
    if (a->argc == e->args - 1) {
       ast_cli(a->fd, "Auto answer is %s.\n", o->autoanswer ? "on" : "off");
       return CLI_SUCCESS;
    }
    if (a->argc != e->args)
       return CLI_SHOWUSAGE;
    if (o == NULL) {
       ast_log(LOG_WARNING, "Cannot find device %s (should not happen!)\n",
           oss_active);
       return CLI_FAILURE;
    }
    if (!strcasecmp(a->argv[e->args-1], "on"))
       o->autoanswer = 1;
    else if (!strcasecmp(a->argv[e->args - 1], "off"))
       o->autoanswer = 0;
    else
       return CLI_SHOWUSAGE;
    return CLI_SUCCESS;
 }
console_boost()
static char* console_boost (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) static
Definition at line 1272 of file chan_oss.c.
References ast_cli_args::argc, ast_cli_args::argv, ast_cli(), chan_oss_pvt::boost, BOOST_SCALE, CLI_GENERATE, CLI_INIT, CLI_SUCCESS, ast_cli_entry::command, ast_cli_args::fd, find_desc(), NULL, oss_active, store_boost(), and ast_cli_entry::usage.
 {
    struct chan_oss_pvt *o = find_desc(oss_active);
    switch (cmd) {
    case CLI_INIT:
       e->command = "console boost";
       e->usage =
          "Usage: console boost [boost in dB]\n"
          "       Sets or display mic boost in dB\n";
       return NULL;
    case CLI_GENERATE:
       return NULL;
    }
    if (a->argc == 2)
       ast_cli(a->fd, "boost currently %5.1f\n", 20 * log10(((double) o->boost / (double) BOOST_SCALE)));
    else if (a->argc == 3)
       store_boost(o, a->argv[2]);
    return CLI_SUCCESS;
 }
console_cmd()
static char* console_cmd (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) static
Generic console command handler. Basically a wrapper for a subset of config file options which are also available from the CLI
Definition at line 891 of file chan_oss.c.
References ast_cli_args::argc, ast_cli_entry::args, ast_cli_args::argv, ast_cli(), ast_log, CLI_FAILURE, CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::command, console_video_cli(), CONSOLE_VIDEO_CMDS, chan_oss_pvt::device, chan_oss_pvt::env, ast_cli_args::fd, find_desc(), LOG_WARNING, NULL, oss_active, store_config_core(), ast_cli_entry::usage, value, and var.
 {
    struct chan_oss_pvt *o = find_desc(oss_active);
    const char *var, *value;
    switch (cmd) {
    case CLI_INIT:
       e->command = CONSOLE_VIDEO_CMDS;
       e->usage =
          "Usage: " CONSOLE_VIDEO_CMDS "...\n"
          "       Generic handler for console commands.\n";
       return NULL;
    case CLI_GENERATE:
       return NULL;
    }
    if (a->argc < e->args)
       return CLI_SHOWUSAGE;
    if (o == NULL) {
       ast_log(LOG_WARNING, "Cannot find device %s (should not happen!)\n",
          oss_active);
       return CLI_FAILURE;
    }
    var = a->argv[e->args-1];
    value = a->argc > e->args ? a->argv[e->args] : NULL;
    if (value)      /* handle setting */
       store_config_core(o, var, value);
    if (!console_video_cli(o->env, var, a->fd))  /* print video-related values */
       return CLI_SUCCESS;
    /* handle other values */
    if (!strcasecmp(var, "device")) {
       ast_cli(a->fd, "device is [%s]\n", o->device);
    }
    return CLI_SUCCESS;
 }
console_dial()
static char* console_dial (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) static
Definition at line 1093 of file chan_oss.c.
References ast_cli_args::argc, ast_cli_entry::args, ast_cli_args::argv, ast_cli(), ast_exists_extension(), ast_ext_ctx(), AST_FRAME_DTMF, ast_free, ast_queue_frame(), AST_STATE_RINGING, CLI_FAILURE, CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::command, chan_oss_pvt::ctx, chan_oss_pvt::ext, ast_cli_args::fd, find_desc(), chan_oss_pvt::hookstate, ast_frame_subclass::integer, NULL, oss_active, oss_new(), chan_oss_pvt::owner, ast_frame::subclass, and ast_cli_entry::usage.
 {
    char *s = NULL;
    char *mye = NULL, *myc = NULL;
    struct chan_oss_pvt *o = find_desc(oss_active);
    if (cmd == CLI_INIT) {
       e->command = "console dial";
       e->usage =
          "Usage: console dial [extension[@context]]\n"
          "       Dials a given extension (and context if specified)\n";
       return NULL;
    } else if (cmd == CLI_GENERATE)
       return NULL;
    if (a->argc > e->args + 1)
       return CLI_SHOWUSAGE;
    if (o->owner) {   /* already in a call */
       int i;
       struct ast_frame f = { AST_FRAME_DTMF, { 0 } };
       const char *digits;
       if (a->argc == e->args) {  /* argument is mandatory here */
          ast_cli(a->fd, "Already in a call. You can only dial digits until you hangup.\n");
          return CLI_FAILURE;
       }
       digits = a->argv[e->args];
       /* send the string one char at a time */
       for (i = 0; i < strlen(digits); i++) {
          f.subclass.integer = digits[i];
          ast_queue_frame(o->owner, &f);
       }
       return CLI_SUCCESS;
    }
    /* if we have an argument split it into extension and context */
    if (a->argc == e->args + 1)
       s = ast_ext_ctx(a->argv[e->args], &mye, &myc);
    /* supply default values if needed */
    if (mye == NULL)
       mye = o->ext;
    if (myc == NULL)
       myc = o->ctx;
    if (ast_exists_extension(NULL, myc, mye, 1, NULL)) {
       o->hookstate = 1;
       oss_new(o, mye, myc, AST_STATE_RINGING, NULL, NULL);
    } else
       ast_cli(a->fd, "No such extension '%s' in context '%s'\n", mye, myc);
    if (s)
       ast_free(s);
    return CLI_SUCCESS;
 }
console_do_answer()
static char* console_do_answer (int fd) static
helper function for the answer key/cli command
Definition at line 966 of file chan_oss.c.
References ast_cli(), AST_CONTROL_ANSWER, AST_FRAME_CONTROL, ast_queue_frame(), CLI_FAILURE, CLI_SUCCESS, find_desc(), chan_oss_pvt::hookstate, oss_active, and chan_oss_pvt::owner.
Referenced by console_answer(), and keypad_cfg_read().
 {
    struct ast_frame f = { AST_FRAME_CONTROL, { AST_CONTROL_ANSWER } };
    struct chan_oss_pvt *o = find_desc(oss_active);
    if (!o->owner) {
       if (fd > -1)
          ast_cli(fd, "No one is calling us\n");
       return CLI_FAILURE;
    }
    o->hookstate = 1;
    ast_queue_frame(o->owner, &f);
    return CLI_SUCCESS;
 }
console_flash()
static char* console_flash (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) static
Definition at line 1067 of file chan_oss.c.
References ast_cli_args::argc, ast_cli_entry::args, ast_cli(), AST_CONTROL_FLASH, AST_FRAME_CONTROL, ast_queue_frame(), CLI_FAILURE, CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::command, ast_cli_args::fd, find_desc(), chan_oss_pvt::hookstate, NULL, oss_active, chan_oss_pvt::owner, and ast_cli_entry::usage.
 {
    struct ast_frame f = { AST_FRAME_CONTROL, { AST_CONTROL_FLASH } };
    struct chan_oss_pvt *o = find_desc(oss_active);
    if (cmd == CLI_INIT) {
       e->command = "console flash";
       e->usage =
          "Usage: console flash\n"
          "       Flashes the call currently placed on the console.\n";
       return NULL;
    } else if (cmd == CLI_GENERATE)
       return NULL;
    if (a->argc != e->args)
       return CLI_SHOWUSAGE;
    if (!o->owner) {        /* XXX maybe !o->hookstate too ? */
       ast_cli(a->fd, "No call to flash\n");
       return CLI_FAILURE;
    }
    o->hookstate = 0;
    if (o->owner)
       ast_queue_frame(o->owner, &f);
    return CLI_SUCCESS;
 }
console_hangup()
static char* console_hangup (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) static
Definition at line 1041 of file chan_oss.c.
References ast_cli_args::argc, ast_cli_entry::args, AST_CAUSE_NORMAL_CLEARING, ast_cli(), ast_queue_hangup_with_cause(), CLI_FAILURE, CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::command, ast_cli_args::fd, find_desc(), chan_oss_pvt::hookstate, NULL, O_CLOSE, oss_active, chan_oss_pvt::owner, setformat(), and ast_cli_entry::usage.
 {
    struct chan_oss_pvt *o = find_desc(oss_active);
    if (cmd == CLI_INIT) {
       e->command = "console hangup";
       e->usage =
          "Usage: console hangup\n"
          "       Hangs up any call currently placed on the console.\n";
       return NULL;
    } else if (cmd == CLI_GENERATE)
       return NULL;
    if (a->argc != e->args)
       return CLI_SHOWUSAGE;
    if (!o->owner && !o->hookstate) { /* XXX maybe only one ? */
       ast_cli(a->fd, "No call to hang up\n");
       return CLI_FAILURE;
    }
    o->hookstate = 0;
    if (o->owner)
       ast_queue_hangup_with_cause(o->owner, AST_CAUSE_NORMAL_CLEARING);
    setformat(o, O_CLOSE);
    return CLI_SUCCESS;
 }
console_mute()
static char* console_mute (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) static
Definition at line 1145 of file chan_oss.c.
References ast_cli_args::argc, ast_cli_entry::args, ast_cli_args::argv, ast_cli(), CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::command, ast_cli_args::fd, find_desc(), chan_oss_pvt::mute, NULL, oss_active, and ast_cli_entry::usage.
 {
    struct chan_oss_pvt *o = find_desc(oss_active);
    const char *s;
    int toggle = 0;
    if (cmd == CLI_INIT) {
       e->command = "console {mute|unmute} [toggle]";
       e->usage =
          "Usage: console {mute|unmute} [toggle]\n"
          "       Mute/unmute the microphone.\n";
       return NULL;
    } else if (cmd == CLI_GENERATE)
       return NULL;
    if (a->argc > e->args)
       return CLI_SHOWUSAGE;
    if (a->argc == e->args) {
       if (strcasecmp(a->argv[e->args-1], "toggle"))
          return CLI_SHOWUSAGE;
       toggle = 1;
    }
    s = a->argv[e->args-2];
    if (!strcasecmp(s, "mute"))
       o->mute = toggle ? !o->mute : 1;
    else if (!strcasecmp(s, "unmute"))
       o->mute = toggle ? !o->mute : 0;
    else
       return CLI_SHOWUSAGE;
    ast_cli(a->fd, "Console mic is %s\n", o->mute ? "off" : "on");
    return CLI_SUCCESS;
 }
console_sendtext()
static char* console_sendtext (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) static
Console send text CLI command.
Note
concatenate all arguments into a single string. argv is NULL-terminated so we can use it right away
Definition at line 1007 of file chan_oss.c.
References ast_cli_args::argc, ast_cli_entry::args, ast_cli_args::argv, ast_cli(), AST_FRAME_TEXT, ast_join, ast_queue_frame(), ast_strlen_zero, buf, CLI_FAILURE, CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::command, ast_frame::data, ast_frame::datalen, ast_cli_args::fd, find_desc(), ast_frame::frametype, ast_frame_subclass::integer, NULL, oss_active, chan_oss_pvt::owner, ast_frame::ptr, ast_frame::subclass, TEXT_SIZE, and ast_cli_entry::usage.
 {
    struct chan_oss_pvt *o = find_desc(oss_active);
    char buf[TEXT_SIZE];
    if (cmd == CLI_INIT) {
       e->command = "console send text";
       e->usage =
          "Usage: console send text <message>\n"
          "       Sends a text message for display on the remote terminal.\n";
       return NULL;
    } else if (cmd == CLI_GENERATE)
       return NULL;
    if (a->argc < e->args + 1)
       return CLI_SHOWUSAGE;
    if (!o->owner) {
       ast_cli(a->fd, "Not in a call\n");
       return CLI_FAILURE;
    }
    ast_join(buf, sizeof(buf) - 1, a->argv + e->args);
    if (!ast_strlen_zero(buf)) {
       struct ast_frame f = { 0, };
       int i = strlen(buf);
       buf[i] = '\n';
       f.frametype = AST_FRAME_TEXT;
       f.subclass.integer = 0;
       f.data.ptr = buf;
       f.datalen = i + 1;
       ast_queue_frame(o->owner, &f);
    }
    return CLI_SUCCESS;
 }
console_transfer()
static char* console_transfer (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) static
Definition at line 1178 of file chan_oss.c.
References ast_cli_args::argc, ast_cli_args::argv, ast_bridge_transfer_blind(), AST_BRIDGE_TRANSFER_SUCCESS, ast_channel_context(), ast_channel_is_bridged(), ast_channel_name(), ast_cli(), ast_ext_ctx(), ast_free, ast_log, ast_strdupa, CLI_FAILURE, CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::command, chan_oss_pvt::ctx, chan_oss_pvt::ext, ast_cli_args::fd, find_desc(), LOG_WARNING, NULL, oss_active, chan_oss_pvt::owner, tmp(), and ast_cli_entry::usage.
 {
    struct chan_oss_pvt *o = find_desc(oss_active);
    char *tmp, *ext, *ctx;
    switch (cmd) {
    case CLI_INIT:
       e->command = "console transfer";
       e->usage =
          "Usage: console transfer <extension>[@context]\n"
          "       Transfers the currently connected call to the given extension (and\n"
          "       context if specified)\n";
       return NULL;
    case CLI_GENERATE:
       return NULL;
    }
    if (a->argc != 3)
       return CLI_SHOWUSAGE;
    if (o == NULL)
       return CLI_FAILURE;
    if (o->owner == NULL || !ast_channel_is_bridged(o->owner)) {
       ast_cli(a->fd, "There is no call to transfer\n");
       return CLI_SUCCESS;
    }
    tmp = ast_ext_ctx(a->argv[2], &ext, &ctx);
    if (ctx == NULL) {         /* supply default context if needed */
       ctx = ast_strdupa(ast_channel_context(o->owner));
    }
    if (ast_bridge_transfer_blind(1, o->owner, ext, ctx, NULL, NULL) != AST_BRIDGE_TRANSFER_SUCCESS) {
       ast_log(LOG_WARNING, "Unable to transfer call from channel %s\n", ast_channel_name(o->owner));
    }
    ast_free(tmp);
    return CLI_SUCCESS;
 }
find_desc()
static struct chan_oss_pvt * find_desc (const char * dev) static
returns a pointer to the descriptor with the given name
forward declaration
Definition at line 376 of file chan_oss.c.
References ast_log, LOG_WARNING, chan_oss_pvt::name, chan_oss_pvt::next, and NULL.
Referenced by ast_ext_ctx(), console_active(), console_autoanswer(), console_boost(), console_cmd(), console_dial(), console_do_answer(), console_flash(), console_hangup(), console_mute(), console_sendtext(), console_transfer(), get_video_desc(), keypad_cfg_read(), load_module(), and oss_request().
 {
    struct chan_oss_pvt *o = NULL;
    if (!dev)
       ast_log(LOG_WARNING, "null dev\n");
    for (o = oss_default.next; o && o->name && dev && strcmp(o->name, dev) != 0; o = o->next);
    if (!o)
       ast_log(LOG_WARNING, "could not find <%s>\n", dev ? dev : "--no-device--");
    return o;
 }
get_video_desc()
struct video_desc* get_video_desc (struct ast_channel * c)
return the pointer to the video descriptor
Definition at line 319 of file chan_oss.c.
References ast_channel_tech_pvt(), chan_oss_pvt::env, find_desc(), NULL, and oss_active.
Referenced by oss_new().
 {
    struct chan_oss_pvt *o = c ? ast_channel_tech_pvt(c) : find_desc(oss_active);
    return o ? o->env : NULL;
 }
load_module()
static int load_module (void) static
Load the module.
Module loading including tests for configuration or dependencies. This function can return AST_MODULE_LOAD_FAILURE, AST_MODULE_LOAD_DECLINE, or AST_MODULE_LOAD_SUCCESS. If a dependency or environment variable fails tests return AST_MODULE_LOAD_FAILURE. If the module can not load the configuration file or other non-critical problem return AST_MODULE_LOAD_DECLINE. On success return AST_MODULE_LOAD_SUCCESS.
Definition at line 1478 of file chan_oss.c.
References ARRAY_LEN, ast_category_browse(), ast_channel_register(), ast_cli_register_multiple, ast_config_destroy(), ast_config_load, ast_format_cap_alloc, ast_format_cap_append, ast_format_slin, ast_log, AST_MODULE_INFO_STANDARD_DEPRECATED(), AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, ASTERISK_GPL_KEY, ast_channel_tech::capabilities, config, CONFIG_STATUS_FILEINVALID, find_desc(), global_jbconf, LOG_ERROR, LOG_NOTICE, NULL, oss_active, store_config(), and unload_module().
 {
    struct ast_config *cfg = NULL;
    char *ctg = NULL;
    struct ast_flags config_flags = { 0 };
    /* Copy the default jb config over global_jbconf */
    memcpy(&global_jbconf, &default_jbconf, sizeof(struct ast_jb_conf));
    /* load config file */
    if (!(cfg = ast_config_load(config, config_flags))) {
       ast_log(LOG_NOTICE, "Unable to load config %s\n", config);
       return AST_MODULE_LOAD_DECLINE;
    } else if (cfg == CONFIG_STATUS_FILEINVALID) {
       ast_log(LOG_ERROR, "Config file %s is in an invalid format.  Aborting.\n", config);
       return AST_MODULE_LOAD_DECLINE;
    }
    do {
       store_config(cfg, ctg);
    } while ( (ctg = ast_category_browse(cfg, ctg)) != NULL);
    ast_config_destroy(cfg);
    if (find_desc(oss_active) == NULL) {
       ast_log(LOG_NOTICE, "Device %s not found\n", oss_active);
       /* XXX we could default to 'dsp' perhaps ? */
       unload_module();
       return AST_MODULE_LOAD_DECLINE;
    }
    if (!(oss_tech.capabilities = ast_format_cap_alloc(0))) {
       return AST_MODULE_LOAD_DECLINE;
    }
    ast_format_cap_append(oss_tech.capabilities, ast_format_slin, 0);
    /* TODO XXX CONSOLE VIDEO IS DISABLE UNTIL IT HAS A MAINTAINER
     * add console_video_formats to oss_tech.capabilities once this occurs. */
    if (ast_channel_register(&oss_tech)) {
       ast_log(LOG_ERROR, "Unable to register channel type 'OSS'\n");
       return AST_MODULE_LOAD_DECLINE;
    }
    ast_cli_register_multiple(cli_oss, ARRAY_LEN(cli_oss));
    return AST_MODULE_LOAD_SUCCESS;
 }
oss_answer()
static int oss_answer (struct ast_channel * c) static
remote side answered the phone
Definition at line 645 of file chan_oss.c.
References ast_channel_tech_pvt(), ast_setstate(), AST_STATE_UP, ast_verbose(), and chan_oss_pvt::hookstate.
 {
    struct chan_oss_pvt *o = ast_channel_tech_pvt(c);
    ast_verbose(" << Console call has been answered >> \n");
    ast_setstate(c, AST_STATE_UP);
    o->hookstate = 1;
    return 0;
 }
oss_call()
static int oss_call (struct ast_channel * c, const char * dest, int timeout) static
handler for incoming calls. Either autoanswer, or start ringing
Definition at line 603 of file chan_oss.c.
References args, AST_APP_ARG, ast_channel_caller(), ast_channel_dialed(), ast_channel_redirecting(), ast_channel_tech_pvt(), AST_CONTROL_ANSWER, AST_CONTROL_RINGING, AST_DECLARE_APP_ARGS, AST_FRAME_CONTROL, ast_indicate(), AST_NONSTANDARD_APP_ARGS, ast_queue_frame(), ast_strdupa, ast_strlen_zero, ast_verbose(), chan_oss_pvt::autoanswer, ast_frame::flags, chan_oss_pvt::hookstate, ast_frame_subclass::integer, chan_oss_pvt::name, parse(), S_COR, S_OR, and ast_frame::subclass.
 {
    struct chan_oss_pvt *o = ast_channel_tech_pvt(c);
    struct ast_frame f = { AST_FRAME_CONTROL, };
    AST_DECLARE_APP_ARGS(args,
       AST_APP_ARG(name);
       AST_APP_ARG(flags);
    );
    char *parse = ast_strdupa(dest);
    AST_NONSTANDARD_APP_ARGS(args, parse, '/');
    ast_verbose(" << Call to device '%s' dnid '%s' rdnis '%s' on console from '%s' <%s> >>\n",
       dest,
       S_OR(ast_channel_dialed(c)->number.str, ""),
       S_COR(ast_channel_redirecting(c)->from.number.valid, ast_channel_redirecting(c)->from.number.str, ""),
       S_COR(ast_channel_caller(c)->id.name.valid, ast_channel_caller(c)->id.name.str, ""),
       S_COR(ast_channel_caller(c)->id.number.valid, ast_channel_caller(c)->id.number.str, ""));
    if (!ast_strlen_zero(args.flags) && strcasecmp(args.flags, "answer") == 0) {
       f.subclass.integer = AST_CONTROL_ANSWER;
       ast_queue_frame(c, &f);
    } else if (!ast_strlen_zero(args.flags) && strcasecmp(args.flags, "noanswer") == 0) {
       f.subclass.integer = AST_CONTROL_RINGING;
       ast_queue_frame(c, &f);
       ast_indicate(c, AST_CONTROL_RINGING);
    } else if (o->autoanswer) {
       ast_verbose(" << Auto-answered >> \n");
       f.subclass.integer = AST_CONTROL_ANSWER;
       ast_queue_frame(c, &f);
       o->hookstate = 1;
    } else {
       ast_verbose("<< Type 'answer' to answer, or use 'autoanswer' for future calls >> \n");
       f.subclass.integer = AST_CONTROL_RINGING;
       ast_queue_frame(c, &f);
       ast_indicate(c, AST_CONTROL_RINGING);
    }
    return 0;
 }
oss_digit_begin()
static int oss_digit_begin (struct ast_channel * c, char digit) static
Definition at line 580 of file chan_oss.c.
 {
    return 0;
 }
oss_digit_end()
static int oss_digit_end (struct ast_channel * c, char digit, unsigned int duration) static
Definition at line 585 of file chan_oss.c.
References ast_verbose().
 {
    /* no better use for received digits than print them */
    ast_verbose(" << Console Received digit %c of duration %u ms >> \n",
       digit, duration);
    return 0;
 }
oss_fixup()
static int oss_fixup (struct ast_channel * oldchan, struct ast_channel * newchan) static
Definition at line 754 of file chan_oss.c.
References ast_channel_tech_pvt(), and chan_oss_pvt::owner.
 {
    struct chan_oss_pvt *o = ast_channel_tech_pvt(newchan);
    o->owner = newchan;
    return 0;
 }
oss_hangup()
static int oss_hangup (struct ast_channel * c) static
Definition at line 654 of file chan_oss.c.
References ast_channel_tech_pvt(), ast_channel_tech_pvt_set(), ast_module_unref, ast_verbose(), chan_oss_pvt::autoanswer, chan_oss_pvt::autohangup, console_video_uninit(), chan_oss_pvt::env, chan_oss_pvt::hookstate, NULL, O_CLOSE, chan_oss_pvt::owner, ast_module_info::self, and setformat().
 {
    struct chan_oss_pvt *o = ast_channel_tech_pvt(c);
    ast_channel_tech_pvt_set(c, NULL);
    o->owner = NULL;
    ast_verbose(" << Hangup on console >> \n");
    console_video_uninit(o->env);
    ast_module_unref(ast_module_info->self);
    if (o->hookstate) {
       if (o->autoanswer || o->autohangup) {
          /* Assume auto-hangup too */
          o->hookstate = 0;
          setformat(o, O_CLOSE);
       }
    }
    return 0;
 }
oss_indicate()
static int oss_indicate (struct ast_channel * chan, int cond, const void * data, size_t datalen) static
Definition at line 761 of file chan_oss.c.
References ast_channel_name(), ast_channel_tech_pvt(), AST_CONTROL_BUSY, AST_CONTROL_CONGESTION, AST_CONTROL_HOLD, AST_CONTROL_INCOMPLETE, AST_CONTROL_PROCEEDING, AST_CONTROL_PROGRESS, AST_CONTROL_PVT_CAUSE_CODE, AST_CONTROL_RINGING, AST_CONTROL_SRCUPDATE, AST_CONTROL_UNHOLD, AST_CONTROL_VIDUPDATE, ast_log, ast_moh_start(), ast_moh_stop(), ast_verbose(), LOG_WARNING, and chan_oss_pvt::mohinterpret.
 {
    struct chan_oss_pvt *o = ast_channel_tech_pvt(c);
    int res = 0;
    switch (cond) {
    case AST_CONTROL_INCOMPLETE:
    case AST_CONTROL_BUSY:
    case AST_CONTROL_CONGESTION:
    case AST_CONTROL_RINGING:
    case AST_CONTROL_PVT_CAUSE_CODE:
    case -1:
       res = -1;
       break;
    case AST_CONTROL_PROGRESS:
    case AST_CONTROL_PROCEEDING:
    case AST_CONTROL_VIDUPDATE:
    case AST_CONTROL_SRCUPDATE:
       break;
    case AST_CONTROL_HOLD:
       ast_verbose(" << Console Has Been Placed on Hold >> \n");
       ast_moh_start(c, data, o->mohinterpret);
       break;
    case AST_CONTROL_UNHOLD:
       ast_verbose(" << Console Has Been Retrieved from Hold >> \n");
       ast_moh_stop(c);
       break;
    default:
       ast_log(LOG_WARNING, "Don't know how to display condition %d on %s\n", cond, ast_channel_name(c));
       return -1;
    }
    return res;
 }
oss_new()
static struct ast_channel* oss_new (struct chan_oss_pvt * o, char * ext, char * ctx, int state, const struct ast_assigned_ids * assignedids, const struct ast_channel * requestor) static
allocate a new channel.
Definition at line 799 of file chan_oss.c.
References ast_party_caller::ani, ast_channel_alloc, ast_channel_caller(), ast_channel_dialed(), ast_channel_name(), ast_channel_nativeformats_set(), ast_channel_set_fd(), ast_channel_set_readformat(), ast_channel_set_writeformat(), ast_channel_tech_pvt_set(), ast_channel_tech_set(), ast_channel_unlock, ast_format_slin, ast_hangup(), ast_jb_configure(), ast_log, ast_module_ref, ast_pbx_start(), AST_STATE_DOWN, ast_strdup, ast_strlen_zero, c, ast_channel_tech::capabilities, chan_oss_pvt::cid_name, chan_oss_pvt::cid_num, console_video_start(), chan_oss_pvt::device, get_video_desc(), global_jbconf, chan_oss_pvt::language, LOG_WARNING, NULL, ast_party_id::number, ast_party_dialed::number, chan_oss_pvt::owner, ast_module_info::self, setformat(), chan_oss_pvt::sounddev, ast_party_number::str, ast_party_dialed::str, and ast_party_number::valid.
Referenced by console_dial(), and oss_request().
 {
    struct ast_channel *c;
    c = ast_channel_alloc(1, state, o->cid_num, o->cid_name, "", ext, ctx, assignedids, requestor, 0, "Console/%s", o->device + 5);
    if (c == NULL)
       return NULL;
    ast_channel_tech_set(c, &oss_tech);
    if (o->sounddev < 0)
       setformat(o, O_RDWR);
    ast_channel_set_fd(c, 0, o->sounddev); /* -1 if device closed, override later */
    ast_channel_set_readformat(c, ast_format_slin);
    ast_channel_set_writeformat(c, ast_format_slin);
    ast_channel_nativeformats_set(c, oss_tech.capabilities);
    /* if the console makes the call, add video to the offer */
    /* if (state == AST_STATE_RINGING) TODO XXX CONSOLE VIDEO IS DISABLED UNTIL IT GETS A MAINTAINER
       c->nativeformats |= console_video_formats; */
    ast_channel_tech_pvt_set(c, o);
    if (!ast_strlen_zero(o->language))
       ast_channel_language_set(c, o->language);
    /* Don't use ast_set_callerid() here because it will
     * generate a needless NewCallerID event */
    if (!ast_strlen_zero(o->cid_num)) {
       ast_channel_caller(c)->ani.number.valid = 1;
       ast_channel_caller(c)->ani.number.str = ast_strdup(o->cid_num);
    }
    if (!ast_strlen_zero(ext)) {
       ast_channel_dialed(c)->number.str = ast_strdup(ext);
    }
    o->owner = c;
    ast_module_ref(ast_module_info->self);
    ast_jb_configure(c, &global_jbconf);
    ast_channel_unlock(c);
    if (state != AST_STATE_DOWN) {
       if (ast_pbx_start(c)) {
          ast_log(LOG_WARNING, "Unable to start PBX on %s\n", ast_channel_name(c));
          ast_hangup(c);
          o->owner = c = NULL;
       }
    }
    console_video_start(get_video_desc(c), c); /* XXX cleanup */
    return c;
 }
oss_read()
static struct ast_frame * oss_read (struct ast_channel * chan) static
Definition at line 705 of file chan_oss.c.
References ast_channel_tech_pvt(), ast_format_slin, AST_FRAME_NULL, AST_FRAME_VOICE, AST_FRIENDLY_OFFSET, AST_STATE_UP, chan_oss_pvt::boost, BOOST_SCALE, ast_frame::data, ast_frame::datalen, ast_frame_subclass::format, FRAME_SIZE, ast_frame::frametype, chan_oss_pvt::mute, ast_frame::offset, chan_oss_pvt::oss_read_buf, ast_frame::ptr, chan_oss_pvt::read_f, chan_oss_pvt::readpos, ast_frame::samples, chan_oss_pvt::sounddev, ast_frame::src, ast_frame::subclass, and ast_channel_tech::type.
 {
    int res;
    struct chan_oss_pvt *o = ast_channel_tech_pvt(c);
    struct ast_frame *f = &o->read_f;
    /* XXX can be simplified returning &ast_null_frame */
    /* prepare a NULL frame in case we don't have enough data to return */
    memset(f, '\0', sizeof(struct ast_frame));
    f->frametype = AST_FRAME_NULL;
    f->src = oss_tech.type;
    res = read(o->sounddev, o->oss_read_buf + o->readpos, sizeof(o->oss_read_buf) - o->readpos);
    if (res < 0)            /* audio data not ready, return a NULL frame */
       return f;
    o->readpos += res;
    if (o->readpos < sizeof(o->oss_read_buf)) /* not enough samples */
       return f;
    if (o->mute)
       return f;
    o->readpos = AST_FRIENDLY_OFFSET;   /* reset read pointer for next frame */
    if (ast_channel_state(c) != AST_STATE_UP) /* drop data if frame is not up */
       return f;
    /* ok we can build and deliver the frame to the caller */
    f->frametype = AST_FRAME_VOICE;
    f->subclass.format = ast_format_slin;
    f->samples = FRAME_SIZE;
    f->datalen = FRAME_SIZE * 2;
    f->data.ptr = o->oss_read_buf + AST_FRIENDLY_OFFSET;
    if (o->boost != BOOST_SCALE) {   /* scale and clip values */
       int i, x;
       int16_t *p = (int16_t *) f->data.ptr;
       for (i = 0; i < f->samples; i++) {
          x = (p[i] * o->boost) / BOOST_SCALE;
          if (x > 32767)
             x = 32767;
          else if (x < -32768)
             x = -32768;
          p[i] = x;
       }
    }
    f->offset = AST_FRIENDLY_OFFSET;
    return f;
 }
oss_request()
static struct ast_channel * oss_request (const char * type, struct ast_format_cap * cap, const struct ast_assigned_ids * assignedids, const struct ast_channel * requestor, const char * data, int * cause) static
Definition at line 849 of file chan_oss.c.
References args, AST_APP_ARG, AST_CAUSE_BUSY, AST_DECLARE_APP_ARGS, ast_format_cap_get_names(), ast_format_cap_iscompatible_format(), AST_FORMAT_CAP_NAMES_LEN, AST_FORMAT_CMP_NOT_EQUAL, ast_format_slin, ast_log, AST_NONSTANDARD_APP_ARGS, AST_STATE_DOWN, ast_str_alloca, ast_strdupa, c, find_desc(), LOG_NOTICE, LOG_WARNING, chan_oss_pvt::name, NULL, oss_new(), chan_oss_pvt::owner, parse(), store_config_core(), value, and var.
 {
    struct ast_channel *c;
    struct chan_oss_pvt *o;
    AST_DECLARE_APP_ARGS(args,
       AST_APP_ARG(name);
       AST_APP_ARG(flags);
    );
    char *parse = ast_strdupa(data);
    AST_NONSTANDARD_APP_ARGS(args, parse, '/');
    o = find_desc(args.name);
    ast_log(LOG_WARNING, "oss_request ty <%s> data 0x%p <%s>\n", type, data, data);
    if (o == NULL) {
       ast_log(LOG_NOTICE, "Device %s not found\n", args.name);
       /* XXX we could default to 'dsp' perhaps ? */
       return NULL;
    }
    if (ast_format_cap_iscompatible_format(cap, ast_format_slin) == AST_FORMAT_CMP_NOT_EQUAL) {
       struct ast_str *codec_buf = ast_str_alloca(AST_FORMAT_CAP_NAMES_LEN);
       ast_log(LOG_NOTICE, "Format %s unsupported\n", ast_format_cap_get_names(cap, &codec_buf));
       return NULL;
    }
    if (o->owner) {
       ast_log(LOG_NOTICE, "Already have a call (chan %p) on the OSS channel\n", o->owner);
       *cause = AST_CAUSE_BUSY;
       return NULL;
    }
    c = oss_new(o, NULL, NULL, AST_STATE_DOWN, assignedids, requestor);
    if (c == NULL) {
       ast_log(LOG_WARNING, "Unable to create new OSS channel\n");
       return NULL;
    }
    return c;
 }
oss_text()
static int oss_text (struct ast_channel * c, const char * text) static
Definition at line 593 of file chan_oss.c.
References ast_verbose().
 {
    /* print received messages */
    ast_verbose(" << Console Received text %s >> \n", text);
    return 0;
 }
oss_write()
static int oss_write (struct ast_channel * chan, struct ast_frame * f) static
used for data coming from the network
Definition at line 674 of file chan_oss.c.
References ast_channel_tech_pvt(), ast_frame::data, ast_frame::datalen, if(), chan_oss_pvt::oss_write_buf, chan_oss_pvt::oss_write_dst, ast_frame::ptr, and soundcard_writeframe().
 {
    int src;
    struct chan_oss_pvt *o = ast_channel_tech_pvt(c);
    /*
     * we could receive a block which is not a multiple of our
     * FRAME_SIZE, so buffer it locally and write to the device
     * in FRAME_SIZE chunks.
     * Keep the residue stored for future use.
     */
    src = 0;             /* read position into f->data */
    while (src < f->datalen) {
       /* Compute spare room in the buffer */
       int l = sizeof(o->oss_write_buf) - o->oss_write_dst;
       if (f->datalen - src >= l) {  /* enough to fill a frame */
          memcpy(o->oss_write_buf + o->oss_write_dst, f->data.ptr + src, l);
          soundcard_writeframe(o, (short *) o->oss_write_buf);
          src += l;
          o->oss_write_dst = 0;
       } else {          /* copy residue */
          l = f->datalen - src;
          memcpy(o->oss_write_buf + o->oss_write_dst, f->data.ptr + src, l);
          src += l;         /* but really, we are done */
          o->oss_write_dst += l;
       }
    }
    return 0;
 }
setformat()
static int setformat (struct chan_oss_pvt * o, int mode) static
reset and close the device if opened, then open and initialize it in the desired mode, trigger reads and writes so we can start using it.
Definition at line 481 of file chan_oss.c.
References ast_channel_set_fd(), ast_log, ast_tvdiff_ms(), ast_tvnow(), ast_verb, chan_oss_pvt::CHAN_OSS_DUPLEX_FULL, chan_oss_pvt::CHAN_OSS_DUPLEX_READ, chan_oss_pvt::CHAN_OSS_DUPLEX_UNSET, chan_oss_pvt::CHAN_OSS_DUPLEX_WRITE, DEFAULT_SAMPLE_RATE, chan_oss_pvt::device, chan_oss_pvt::duplex, errno, chan_oss_pvt::frags, chan_oss_pvt::lastopen, LOG_WARNING, O_CLOSE, chan_oss_pvt::owner, chan_oss_pvt::sounddev, WARN_frag, WARN_speed, and chan_oss_pvt::warned.
Referenced by console_hangup(), oss_hangup(), oss_new(), soundcard_writeframe(), and store_config().
 {
    int fmt, desired, res, fd;
    if (o->sounddev >= 0) {
       ioctl(o->sounddev, SNDCTL_DSP_RESET, 0);
       close(o->sounddev);
       o->duplex = CHAN_OSS_DUPLEX_UNSET;
       o->sounddev = -1;
    }
    if (mode == O_CLOSE)    /* we are done */
       return 0;
    if (ast_tvdiff_ms(ast_tvnow(), o->lastopen) < 1000)
       return -1;           /* don't open too often */
    o->lastopen = ast_tvnow();
    fd = o->sounddev = open(o->device, mode | O_NONBLOCK);
    if (fd < 0) {
       ast_log(LOG_WARNING, "Unable to re-open DSP device %s: %s\n", o->device, strerror(errno));
       return -1;
    }
    if (o->owner)
       ast_channel_set_fd(o->owner, 0, fd);
 #if __BYTE_ORDER == __LITTLE_ENDIAN
    fmt = AFMT_S16_LE;
 #else
    fmt = AFMT_S16_BE;
 #endif
    res = ioctl(fd, SNDCTL_DSP_SETFMT, &fmt);
    if (res < 0) {
       ast_log(LOG_WARNING, "Unable to set format to 16-bit signed\n");
       return -1;
    }
    switch (mode) {
    case O_RDWR:
       res = ioctl(fd, SNDCTL_DSP_SETDUPLEX, 0);
       /* Check to see if duplex set (FreeBSD Bug) */
       res = ioctl(fd, SNDCTL_DSP_GETCAPS, &fmt);
       if (res == 0 && (fmt & DSP_CAP_DUPLEX)) {
          ast_verb(2, "Console is full duplex\n");
          o->duplex = CHAN_OSS_DUPLEX_FULL;
       };
       break;
    case O_WRONLY:
       o->duplex = CHAN_OSS_DUPLEX_WRITE;
       break;
    case O_RDONLY:
       o->duplex = CHAN_OSS_DUPLEX_READ;
       break;
    }
    fmt = 0;
    res = ioctl(fd, SNDCTL_DSP_STEREO, &fmt);
    if (res < 0) {
       ast_log(LOG_WARNING, "Failed to set audio device to mono\n");
       return -1;
    }
    fmt = desired = DEFAULT_SAMPLE_RATE;   /* 8000 Hz desired */
    res = ioctl(fd, SNDCTL_DSP_SPEED, &fmt);
    if (res < 0) {
       ast_log(LOG_WARNING, "Failed to set sample rate to %d\n", desired);
       return -1;
    }
    if (fmt != desired) {
       if (!(o->warned & WARN_speed)) {
          ast_log(LOG_WARNING,
              "Requested %d Hz, got %d Hz -- sound may be choppy\n",
              desired, fmt);
          o->warned |= WARN_speed;
       }
    }
    /*
     * on Freebsd, SETFRAGMENT does not work very well on some cards.
     * Default to use 256 bytes, let the user override
     */
    if (o->frags) {
       fmt = o->frags;
       res = ioctl(fd, SNDCTL_DSP_SETFRAGMENT, &fmt);
       if (res < 0) {
          if (!(o->warned & WARN_frag)) {
             ast_log(LOG_WARNING,
                "Unable to set fragment size -- sound may be choppy\n");
             o->warned |= WARN_frag;
          }
       }
    }
    /* on some cards, we need SNDCTL_DSP_SETTRIGGER to start outputting */
    res = PCM_ENABLE_INPUT | PCM_ENABLE_OUTPUT;
    res = ioctl(fd, SNDCTL_DSP_SETTRIGGER, &res);
    /* it may fail if we are in half duplex, never mind */
    return 0;
 }
soundcard_writeframe()
static int soundcard_writeframe (struct chan_oss_pvt * o, short * data) static
Write an exactly FRAME_SIZE sized frame
Definition at line 452 of file chan_oss.c.
References ast_log, FRAME_SIZE, LOG_WARNING, oss_debug, chan_oss_pvt::queuesize, setformat(), chan_oss_pvt::sounddev, used_blocks(), and chan_oss_pvt::w_errors.
Referenced by oss_write().
 {
    int res;
    if (o->sounddev < 0)
       setformat(o, O_RDWR);
    if (o->sounddev < 0)
       return 0;            /* not fatal */
    /*
     * Nothing complex to manage the audio device queue.
     * If the buffer is full just drop the extra, otherwise write.
     * XXX in some cases it might be useful to write anyways after
     * a number of failures, to restart the output chain.
     */
    res = used_blocks(o);
    if (res > o->queuesize) {  /* no room to write a block */
       if (o->w_errors++ == 0 && (oss_debug & 0x4))
          ast_log(LOG_WARNING, "write: used %d blocks (%d)\n", res, o->w_errors);
       return 0;
    }
    o->w_errors = 0;
    return write(o->sounddev, (void *)data, FRAME_SIZE * 2);
 }
store_boost()
static void store_boost (struct chan_oss_pvt * o, const char * s) static
store the boost factor
Definition at line 1253 of file chan_oss.c.
References ast_log, chan_oss_pvt::boost, BOOST_MAX, BOOST_SCALE, and LOG_WARNING.
Referenced by console_boost(), and store_config_core().
 {
    double boost = 0;
    if (sscanf(s, "%30lf", &boost) != 1) {
       ast_log(LOG_WARNING, "invalid boost <%s>\n", s);
       return;
    }
    if (boost < -BOOST_MAX) {
       ast_log(LOG_WARNING, "boost %s too small, using %d\n", s, -BOOST_MAX);
       boost = -BOOST_MAX;
    } else if (boost > BOOST_MAX) {
       ast_log(LOG_WARNING, "boost %s too large, using %d\n", s, BOOST_MAX);
       boost = BOOST_MAX;
    }
    boost = exp(log(10) * boost / 20) * BOOST_SCALE;
    o->boost = boost;
    ast_log(LOG_WARNING, "setting boost %s to %d\n", s, o->boost);
 }
store_callerid()
static void store_callerid (struct chan_oss_pvt * o, const char * s) static
store the callerid components
Definition at line 1332 of file chan_oss.c.
References ast_callerid_split(), chan_oss_pvt::cid_name, and chan_oss_pvt::cid_num.
Referenced by store_config_core().
 {
    ast_callerid_split(s, o->cid_name, sizeof(o->cid_name), o->cid_num, sizeof(o->cid_num));
 }
store_config()
static struct chan_oss_pvt* store_config (struct ast_config * cfg, char * ctg) static
grab fields from the config file, init the descriptor and open the device.
Definition at line 1368 of file chan_oss.c.
References ast_asprintf, ast_calloc, ast_copy_string(), ast_free, ast_log, ast_strdup, ast_strlen_zero, ast_tvnow(), ast_variable_browse(), ast_verb, chan_oss_pvt::CHAN_OSS_DUPLEX_FULL, console_video_start(), DEV_DSP, chan_oss_pvt::device, chan_oss_pvt::duplex, chan_oss_pvt::env, errno, error(), get_gui_startup(), chan_oss_pvt::lastopen, LOG_WARNING, chan_oss_pvt::mixer_cmd, chan_oss_pvt::mohinterpret, ast_variable::name, chan_oss_pvt::name, ast_variable::next, chan_oss_pvt::next, NULL, oss_active, oss_default, setformat(), store_config_core(), and ast_variable::value.
Referenced by load_module().
 {
    struct ast_variable *v;
    struct chan_oss_pvt *o;
    if (ctg == NULL) {
       o = &oss_default;
       ctg = "general";
    } else {
       if (!(o = ast_calloc(1, sizeof(*o))))
          return NULL;
       *o = oss_default;
       /* "general" is also the default thing */
       if (strcmp(ctg, "general") == 0) {
          o->name = ast_strdup("dsp");
          oss_active = o->name;
          goto openit;
       }
       o->name = ast_strdup(ctg);
    }
    strcpy(o->mohinterpret, "default");
    o->lastopen = ast_tvnow(); /* don't leave it 0 or tvdiff may wrap */
    /* fill other fields from configuration */
    for (v = ast_variable_browse(cfg, ctg); v; v = v->next) {
       store_config_core(o, v->name, v->value);
    }
    if (ast_strlen_zero(o->device))
       ast_copy_string(o->device, DEV_DSP, sizeof(o->device));
    if (o->mixer_cmd) {
       char *cmd;
       if (ast_asprintf(&cmd, "mixer %s", o->mixer_cmd) >= 0) {
          ast_log(LOG_WARNING, "running [%s]\n", cmd);
          if (system(cmd) < 0) {
             ast_log(LOG_WARNING, "system() failed: %s\n", strerror(errno));
          }
          ast_free(cmd);
       }
    }
    /* if the config file requested to start the GUI, do it */
    if (get_gui_startup(o->env))
       console_video_start(o->env, NULL);
    if (o == &oss_default)     /* we are done with the default */
       return NULL;
 openit:
 #ifdef TRYOPEN
    if (setformat(o, O_RDWR) < 0) {  /* open device */
       ast_verb(1, "Device %s not detected\n", ctg);
       ast_verb(1, "Turn off OSS support by adding " "'noload=chan_oss.so' in /etc/asterisk/modules.conf\n");
       goto error;
    }
    if (o->duplex != CHAN_OSS_DUPLEX_FULL)
       ast_log(LOG_WARNING, "XXX I don't work right with non " "full-duplex sound cards XXX\n");
 #endif /* TRYOPEN */
    /* link into list of devices */
    if (o != &oss_default) {
       o->next = oss_default.next;
       oss_default.next = o;
    }
    return o;
 #ifdef TRYOPEN
 error:
    if (o != &oss_default)
       ast_free(o);
    return NULL;
 #endif
 }
store_config_core()
static void store_config_core (struct chan_oss_pvt * o, const char * var, const char * value) static
Definition at line 1337 of file chan_oss.c.
References ast_jb_read_conf(), chan_oss_pvt::autoanswer, chan_oss_pvt::autohangup, console_video_config(), chan_oss_pvt::ctx, CV_BOOL, CV_END, CV_F, CV_START, CV_STR, CV_UINT, chan_oss_pvt::device, chan_oss_pvt::env, chan_oss_pvt::ext, chan_oss_pvt::frags, global_jbconf, chan_oss_pvt::language, chan_oss_pvt::mohinterpret, oss_debug, chan_oss_pvt::overridecontext, chan_oss_pvt::queuesize, store_boost(), store_callerid(), and store_mixer().
Referenced by console_cmd(), oss_request(), and store_config().
 {
    CV_START(var, value);
    /* handle jb conf */
    if (!ast_jb_read_conf(&global_jbconf, var, value))
       return;
    if (!console_video_config(&o->env, var, value))
       return;  /* matched there */
    CV_BOOL("autoanswer", o->autoanswer);
    CV_BOOL("autohangup", o->autohangup);
    CV_BOOL("overridecontext", o->overridecontext);
    CV_STR("device", o->device);
    CV_UINT("frags", o->frags);
    CV_UINT("debug", oss_debug);
    CV_UINT("queuesize", o->queuesize);
    CV_STR("context", o->ctx);
    CV_STR("language", o->language);
    CV_STR("mohinterpret", o->mohinterpret);
    CV_STR("extension", o->ext);
    CV_F("mixer", store_mixer(o, value));
    CV_F("callerid", store_callerid(o, value))  ;
    CV_F("boost", store_boost(o, value));
    CV_END;
 }
store_mixer()
static void store_mixer (struct chan_oss_pvt * o, const char * s) static
store the mixer argument from the config file, filtering possibly invalid or dangerous values (the string is used as argument for system("mixer %s")
Definition at line 1313 of file chan_oss.c.
References ast_free, ast_log, ast_strdup, LOG_WARNING, chan_oss_pvt::mixer_cmd, and NULL.
Referenced by store_config_core().
 {
    int i;
    for (i = 0; i < strlen(s); i++) {
       if (!isalnum(s[i]) && strchr(" \t-/", s[i]) == NULL) {
          ast_log(LOG_WARNING, "Suspect char %c in mixer cmd, ignoring:\n\t%s\n", s[i], s);
          return;
       }
    }
    if (o->mixer_cmd)
       ast_free(o->mixer_cmd);
    o->mixer_cmd = ast_strdup(s);
    ast_log(LOG_WARNING, "setting mixer %s\n", s);
 }
unload_module()
static int unload_module (void) static
Definition at line 1443 of file chan_oss.c.
References ao2_cleanup, ARRAY_LEN, ast_channel_unregister(), ast_cli_unregister_multiple(), ast_free, ast_softhangup(), AST_SOFTHANGUP_APPUNLOAD, ast_channel_tech::capabilities, chan_oss_pvt::name, chan_oss_pvt::next, NULL, chan_oss_pvt::owner, and chan_oss_pvt::sounddev.
Referenced by load_module().
 {
    struct chan_oss_pvt *o, *next;
    ast_channel_unregister(&oss_tech);
    ast_cli_unregister_multiple(cli_oss, ARRAY_LEN(cli_oss));
    o = oss_default.next;
    while (o) {
       close(o->sounddev);
       if (o->owner)
          ast_softhangup(o->owner, AST_SOFTHANGUP_APPUNLOAD);
       if (o->owner)
          return -1;
       next = o->next;
       ast_free(o->name);
       ast_free(o);
       o = next;
    }
    ao2_cleanup(oss_tech.capabilities);
    oss_tech.capabilities = NULL;
    return 0;
 }
used_blocks()
static int used_blocks (struct chan_oss_pvt * o) static
Returns the number of blocks used in the audio output channel.
Definition at line 430 of file chan_oss.c.
References ast_log, LOG_WARNING, chan_oss_pvt::sounddev, chan_oss_pvt::total_blocks, WARN_used_blocks, and chan_oss_pvt::warned.
Referenced by soundcard_writeframe().
 {
    struct audio_buf_info info;
    if (ioctl(o->sounddev, SNDCTL_DSP_GETOSPACE, &info)) {
       if (!(o->warned & WARN_used_blocks)) {
          ast_log(LOG_WARNING, "Error reading output space\n");
          o->warned |= WARN_used_blocks;
       }
       return 1;
    }
    if (o->total_blocks == 0) {
       if (0)               /* debugging */
          ast_log(LOG_WARNING, "fragtotal %d size %d avail %d\n", info.fragstotal, info.fragsize, info.fragments);
       o->total_blocks = info.fragments;
    }
    return o->total_blocks - info.fragments;
 }
Variable Documentation
cli_oss
struct ast_cli_entry cli_oss[] static
Definition at line 1294 of file chan_oss.c.
config
char* config = "oss.conf" static
Definition at line 240 of file chan_oss.c.
Referenced by load_module().
default_jbconf
struct ast_jb_conf default_jbconf static
Global jitterbuffer configuration - by default, jb is disabled
Note
Values shown here match the defaults shown in oss.conf.sample
Definition at line 76 of file chan_oss.c.
global_jbconf
struct ast_jb_conf global_jbconf static
Definition at line 84 of file chan_oss.c.
Referenced by load_module(), oss_new(), and store_config_core().
oss_active
char* oss_active static
the active device
Definition at line 316 of file chan_oss.c.
Referenced by ast_ext_ctx(), console_active(), console_autoanswer(), console_boost(), console_cmd(), console_dial(), console_do_answer(), console_flash(), console_hangup(), console_mute(), console_sendtext(), console_transfer(), get_video_desc(), keypad_cfg_read(), load_module(), and store_config().
oss_debug
int oss_debug static
Definition at line 242 of file chan_oss.c.
Referenced by soundcard_writeframe(), and store_config_core().
oss_default
struct chan_oss_pvt oss_default static
Definition at line 324 of file chan_oss.c.
Referenced by store_config().
oss_tech
struct ast_channel_tech oss_tech static
Definition at line 356 of file chan_oss.c.
tdesc
char tdesc[] = "OSS Console Channel Driver" static
Definition at line 353 of file chan_oss.c.