Asterisk - The Open Source Telephony Project: smdi.h File Reference
smdi.h File Reference
SMDI support for Asterisk.
#include <termios.h>
#include <time.h>
#include "asterisk/config.h"
#include "asterisk/module.h"
#include "asterisk/optional_api.h"
Data Structures
struct ast_smdi_md_message
An SMDI message desk message.
struct ast_smdi_mwi_message
An SMDI message waiting indicator message.
Macros
#define SMDI_MAX_FILENAME_LEN 256
#define SMDI_MAX_STATION_NUM_LEN 10
#define SMDI_MESG_DESK_NUM_LEN 3
#define SMDI_MESG_DESK_TERM_LEN 4
#define SMDI_MESG_NAME_LEN 80
#define SMDI_MWI_FAIL_CAUSE_LEN 3
Functions
struct ast_smdi_interface * ast_smdi_interface_find (const char *iface_name)
Find an SMDI interface with the specified name.
struct ast_smdi_md_message * ast_smdi_md_message_pop (struct ast_smdi_interface *iface)
Get the next SMDI message from the queue.
struct ast_smdi_md_message * ast_smdi_md_message_wait (struct ast_smdi_interface *iface, int timeout)
Get the next SMDI message from the queue.
struct ast_smdi_mwi_message * ast_smdi_mwi_message_pop (struct ast_smdi_interface *iface)
Get the next SMDI message from the queue.
struct ast_smdi_mwi_message * ast_smdi_mwi_message_wait (struct ast_smdi_interface *iface, int timeout)
Get the next SMDI message from the queue.
struct ast_smdi_mwi_message * ast_smdi_mwi_message_wait_station (struct ast_smdi_interface *iface, int timeout, const char *station)
int ast_smdi_mwi_set (struct ast_smdi_interface *iface, const char *mailbox)
Set the MWI indicator for a mailbox.
int ast_smdi_mwi_unset (struct ast_smdi_interface *iface, const char *mailbox)
Unset the MWI indicator for a mailbox.
Detailed Description
SMDI support for Asterisk.
Author
Matthew A. Nicholson mnich.nosp@m.olso.nosp@m.n@dig.nosp@m.ium..nosp@m.com
Russell Bryant russe.nosp@m.ll@d.nosp@m.igium.nosp@m..com
Definition in file smdi.h.
Macro Definition Documentation
SMDI_MAX_FILENAME_LEN
#define SMDI_MAX_FILENAME_LEN 256
Definition at line 42 of file smdi.h.
SMDI_MAX_STATION_NUM_LEN
#define SMDI_MAX_STATION_NUM_LEN 10
Definition at line 41 of file smdi.h.
SMDI_MESG_DESK_NUM_LEN
#define SMDI_MESG_DESK_NUM_LEN 3
Definition at line 38 of file smdi.h.
Referenced by smdi_msg_find().
SMDI_MESG_DESK_TERM_LEN
#define SMDI_MESG_DESK_TERM_LEN 4
Definition at line 39 of file smdi.h.
Referenced by smdi_msg_find().
SMDI_MESG_NAME_LEN
#define SMDI_MESG_NAME_LEN 80
Definition at line 37 of file smdi.h.
SMDI_MWI_FAIL_CAUSE_LEN
#define SMDI_MWI_FAIL_CAUSE_LEN 3
Definition at line 40 of file smdi.h.
Function Documentation
ast_smdi_interface_find()
struct ast_smdi_interface* ast_smdi_interface_find (const char * iface_name)
Find an SMDI interface with the specified name.
Parameters
iface_name the name/port of the interface to search for.
Returns
an ao2 reference to the interface located or NULL if none was found.
Definition at line 563 of file res_smdi.c.
References ao2_find, ao2_global_obj_ref, ao2_ref, c, NULL, and OBJ_SEARCH_KEY.
Referenced by actual_load_config(), mkintf(), and smdi_msg_retrieve_read().
 {
    struct ao2_container *c;
    struct ast_smdi_interface *iface = NULL;
    c = ao2_global_obj_ref(smdi_ifaces);
    if (c) {
       iface = ao2_find(c, iface_name, OBJ_SEARCH_KEY);
       ao2_ref(c, -1);
    }
    return iface;
 }
ast_smdi_md_message_pop()
struct ast_smdi_md_message* ast_smdi_md_message_pop (struct ast_smdi_interface * iface)
Get the next SMDI message from the queue.
Parameters
iface a pointer to the interface to use.
This function pulls the first unexpired message from the SMDI message queue on the specified interface. It will purge all expired SMDI messages before returning.
Returns
the next SMDI message, or NULL if there were no pending messages.
Definition at line 534 of file res_smdi.c.
References SMDI_MD, and smdi_msg_pop().
 {
    return smdi_msg_pop(iface, SMDI_MD);
 }
ast_smdi_md_message_wait()
struct ast_smdi_md_message* ast_smdi_md_message_wait (struct ast_smdi_interface * iface, int timeout)
Get the next SMDI message from the queue.
Parameters
iface a pointer to the interface to use.
timeout the time to wait before returning in milliseconds.
This function pulls a message from the SMDI message queue on the specified interface. If no message is available this function will wait the specified amount of time before returning.
Returns
the next SMDI message, or NULL if there were no pending messages and the timeout has expired.
Definition at line 539 of file res_smdi.c.
References NULL, SMDI_MD, smdi_message_wait(), and timeout.
Referenced by __analog_ss_thread(), and analog_ss_thread().
 {
    struct ast_flags options = { 0 };
    return smdi_message_wait(iface, timeout, SMDI_MD, NULL, options);
 }
ast_smdi_mwi_message_pop()
struct ast_smdi_mwi_message* ast_smdi_mwi_message_pop (struct ast_smdi_interface * iface)
Get the next SMDI message from the queue.
Parameters
iface a pointer to the interface to use.
This function pulls the first unexpired message from the SMDI message queue on the specified interface. It will purge all expired SMDI messages before returning.
Returns
the next SMDI message, or NULL if there were no pending messages.
Definition at line 545 of file res_smdi.c.
References smdi_msg_pop(), and SMDI_MWI.
 {
    return smdi_msg_pop(iface, SMDI_MWI);
 }
ast_smdi_mwi_message_wait()
struct ast_smdi_mwi_message* ast_smdi_mwi_message_wait (struct ast_smdi_interface * iface, int timeout)
Get the next SMDI message from the queue.
Parameters
iface a pointer to the interface to use.
timeout the time to wait before returning in milliseconds.
This function pulls a message from the SMDI message queue on the specified interface. If no message is available this function will wait the specified amount of time before returning.
Returns
the next SMDI message, or NULL if there were no pending messages and the timeout has expired.
Definition at line 550 of file res_smdi.c.
References NULL, smdi_message_wait(), SMDI_MWI, and timeout.
 {
    struct ast_flags options = { 0 };
    return smdi_message_wait(iface, timeout, SMDI_MWI, NULL, options);
 }
ast_smdi_mwi_message_wait_station()
struct ast_smdi_mwi_message* ast_smdi_mwi_message_wait_station (struct ast_smdi_interface * iface, int timeout, const char * station)
Definition at line 556 of file res_smdi.c.
References smdi_message_wait(), and SMDI_MWI.
Referenced by run_externnotify().
 {
    struct ast_flags options = { 0 };
    return smdi_message_wait(iface, timeout, SMDI_MWI, station, options);
 }
ast_smdi_mwi_set()
int ast_smdi_mwi_set (struct ast_smdi_interface * iface, const char * mailbox)
Set the MWI indicator for a mailbox.
Parameters
iface the interface to use.
mailbox the mailbox to use.
Definition at line 309 of file res_smdi.c.
References mailbox, and smdi_toggle_mwi().
Referenced by poll_mailbox(), and run_externnotify().
 {
    return smdi_toggle_mwi(iface, mailbox, 1);
 }
ast_smdi_mwi_unset()
int ast_smdi_mwi_unset (struct ast_smdi_interface * iface, const char * mailbox)
Unset the MWI indicator for a mailbox.
Parameters
iface the interface to use.
mailbox the mailbox to use.
Definition at line 314 of file res_smdi.c.
References mailbox, and smdi_toggle_mwi().
Referenced by poll_mailbox(), and run_externnotify().
 {
    return smdi_toggle_mwi(iface, mailbox, 0);
 }