Asterisk - The Open Source Telephony Project: test_uri.c File Reference
test_uri.c File Reference
URI Unit Tests.
#include "asterisk.h"
#include "asterisk/test.h"
#include "asterisk/module.h"
#include "asterisk/uri.h"
Macros
#define CATEGORY "/main/uri/"
#define VALIDATE(value, expected_value)
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
AST_TEST_DEFINE (uri_parse)
AST_TEST_DEFINE (uri_default_http)
AST_TEST_DEFINE (uri_default_http_secure)
static int load_module (void)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "URI test module" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, }
static const struct ast_module_info * ast_module_info = &__mod_info
static const char * scenarios [][7]
Detailed Description
URI Unit Tests.
Author
Kevin Harwell kharw.nosp@m.ell@.nosp@m.digiu.nosp@m.m.co.nosp@m.m
Definition in file test_uri.c.
Macro Definition Documentation
CATEGORY
#define CATEGORY "/main/uri/"
Definition at line 38 of file test_uri.c.
Referenced by AST_TEST_DEFINE().
VALIDATE
#define VALIDATE (value, expected_value)
Value:
do { ast_test_validate(test, \
           (value == expected_value) || \
           (value && expected_value && \
            !strcmp(value, expected_value)));   \
   } while (0)
Referenced by AST_TEST_DEFINE().
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 152 of file test_uri.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 152 of file test_uri.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 152 of file test_uri.c.
AST_TEST_DEFINE() [1/3]
AST_TEST_DEFINE (uri_parse)
Definition at line 51 of file test_uri.c.
References ao2_cleanup, ARRAY_LEN, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_uri_host(), ast_uri_parse(), ast_uri_path(), ast_uri_port(), ast_uri_query(), ast_uri_scheme(), ast_uri_user_info(), CATEGORY, sip_to_pjsip::info(), NULL, RAII_VAR, scenarios, TEST_EXECUTE, TEST_INIT, and VALIDATE.
 {
 #define VALIDATE(value, expected_value) \
    do { ast_test_validate(test, \
            (value == expected_value) || \
            (value && expected_value && \
             !strcmp(value, expected_value)));   \
    } while (0)
    int i;
    switch (cmd) {
    case TEST_INIT:
       info->name = __func__;
       info->category = CATEGORY;
       info->summary = "Uri parsing scenarios";
       info->description = "For each scenario validate result(s)";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    for (i = 0; i < ARRAY_LEN(scenarios); ++i) {
       RAII_VAR(struct ast_uri *, uri, NULL, ao2_cleanup);
       const char **scenario = scenarios[i];
       ast_test_validate(test, (uri = ast_uri_parse(scenario[0])));
       VALIDATE(ast_uri_scheme(uri), scenario[1]);
       VALIDATE(ast_uri_user_info(uri), scenario[2]);
       VALIDATE(ast_uri_host(uri), scenario[3]);
       VALIDATE(ast_uri_port(uri), scenario[4]);
       VALIDATE(ast_uri_path(uri), scenario[5]);
       VALIDATE(ast_uri_query(uri), scenario[6]);
    }
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [2/3]
AST_TEST_DEFINE (uri_default_http)
Definition at line 88 of file test_uri.c.
References ao2_cleanup, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_uri_host(), ast_uri_is_secure(), ast_uri_parse_http(), ast_uri_port(), ast_uri_scheme(), CATEGORY, sip_to_pjsip::info(), NULL, RAII_VAR, TEST_EXECUTE, and TEST_INIT.
 {
    RAII_VAR(struct ast_uri *, uri, NULL, ao2_cleanup);
    switch (cmd) {
    case TEST_INIT:
       info->name = __func__;
       info->category = CATEGORY;
       info->summary = "parse an http uri with host only";
       info->description = info->summary;
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    ast_test_validate(test, (uri = ast_uri_parse_http("localhost")));
    ast_test_validate(test, !strcmp(ast_uri_scheme(uri), "http"));
    ast_test_validate(test, !strcmp(ast_uri_host(uri), "localhost"));
    ast_test_validate(test, !strcmp(ast_uri_port(uri), "80"));
    ast_test_validate(test, !ast_uri_is_secure(uri));
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [3/3]
AST_TEST_DEFINE (uri_default_http_secure)
Definition at line 112 of file test_uri.c.
References ao2_cleanup, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_uri_host(), ast_uri_is_secure(), ast_uri_parse_http(), ast_uri_port(), ast_uri_scheme(), CATEGORY, sip_to_pjsip::info(), NULL, RAII_VAR, TEST_EXECUTE, and TEST_INIT.
 {
    RAII_VAR(struct ast_uri *, uri, NULL, ao2_cleanup);
    switch (cmd) {
    case TEST_INIT:
       info->name = __func__;
       info->category = CATEGORY;
       info->summary = "parse an https uri with host only";
       info->description = info->summary;
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    ast_test_validate(test, (uri = ast_uri_parse_http("https://localhost")));
    ast_test_validate(test, !strcmp(ast_uri_scheme(uri), "https"));
    ast_test_validate(test, !strcmp(ast_uri_host(uri), "localhost"));
    ast_test_validate(test, !strcmp(ast_uri_port(uri), "443"));
    ast_test_validate(test, ast_uri_is_secure(uri));
    return AST_TEST_PASS;
 }
load_module()
static int load_module (void) static
Definition at line 136 of file test_uri.c.
References AST_MODULE_LOAD_SUCCESS, and AST_TEST_REGISTER.
 {
    AST_TEST_REGISTER(uri_parse);
    AST_TEST_REGISTER(uri_default_http);
    AST_TEST_REGISTER(uri_default_http_secure);
    return AST_MODULE_LOAD_SUCCESS;
 }
unload_module()
static int unload_module (void) static
Definition at line 144 of file test_uri.c.
References AST_TEST_UNREGISTER.
 {
    AST_TEST_UNREGISTER(uri_default_http_secure);
    AST_TEST_UNREGISTER(uri_default_http);
    AST_TEST_UNREGISTER(uri_parse);
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "URI test module" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, } static
Definition at line 152 of file test_uri.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 152 of file test_uri.c.
scenarios
const char* scenarios[][7] static
Definition at line 40 of file test_uri.c.
Referenced by AST_TEST_DEFINE().