Asterisk - The Open Source Telephony Project: epa_static_data Struct Reference
epa_static_data Struct Reference
#include <sip.h>
Data Fields
void(* destructor)(void *instance_data)
enum subscriptiontype event
void(* handle_error)(struct sip_pvt *, const int resp, struct sip_request *, struct sip_epa_entry *)
void(* handle_ok)(struct sip_pvt *, struct sip_request *, struct sip_epa_entry *)
const char * name
Detailed Description
Data which is the same for all instances of an EPA for a particular event package
Definition at line 1614 of file sip.h.
Field Documentation
destructor
void(* destructor) (void *instance_data)
Destructor to call to clean up instance data
Definition at line 1633 of file sip.h.
Referenced by create_epa_entry().
event
enum subscriptiontype event
The event type
Definition at line 1616 of file sip.h.
Referenced by transmit_invite().
handle_error
void(* handle_error) (struct sip_pvt *, const int resp, struct sip_request *, struct sip_epa_entry *)
The callback called when an error response is received on an outbound PUBLISH
Definition at line 1629 of file sip.h.
Referenced by handle_response_publish().
handle_ok
void(* handle_ok) (struct sip_pvt *, struct sip_request *, struct sip_epa_entry *)
The callback called when a 200 OK is received on an outbound PUBLISH
Definition at line 1625 of file sip.h.
Referenced by handle_response_publish().
name
const char* name
The name of the event as it would appear in a SIP message
Definition at line 1621 of file sip.h.
Referenced by find_static_data(), PathSegment::get_child(), Parameter::load(), SwaggerType::load(), and Property::load().
The documentation for this struct was generated from the following file:
sip.h