Asterisk - The Open Source Telephony Project: store.h File Reference
store.h File Reference
Functions
int stir_shaken_store_load (void)
Load time initialization for the stir/shaken 'store' configuration.
int stir_shaken_store_unload (void)
Unload time cleanup for the stir/shaken 'store' configuration.
Function Documentation
stir_shaken_store_load()
int stir_shaken_store_load (void)
Load time initialization for the stir/shaken 'store' configuration.
Return values
0 on success, -1 on error
Definition at line 180 of file store.c.
References ARRAY_LEN, ast_cli_register_multiple, ast_log, ast_sorcery_apply_default, ast_sorcery_object_field_register, ast_sorcery_object_field_register_custom, ast_sorcery_object_register, ast_stir_shaken_sorcery(), CONFIG_TYPE, LOG_ERROR, NULL, on_load_path(), on_load_public_cert_url(), OPT_NOOP_T, path_to_str(), public_cert_url_to_str(), sorcery, stir_shaken_store_alloc(), and stir_shaken_store_apply().
Referenced by load_module().
 {
    struct ast_sorcery *sorcery = ast_stir_shaken_sorcery();
    ast_sorcery_apply_default(sorcery, CONFIG_TYPE, "config", "stir_shaken.conf,criteria=type=store");
    if (ast_sorcery_object_register(sorcery, CONFIG_TYPE, stir_shaken_store_alloc,
          NULL, stir_shaken_store_apply)) {
       ast_log(LOG_ERROR, "stir/shaken - failed to register '%s' sorcery object\n", CONFIG_TYPE);
       return -1;
    }
    ast_sorcery_object_field_register(sorcery, CONFIG_TYPE, "type", "", OPT_NOOP_T, 0, 0);
    ast_sorcery_object_field_register_custom(sorcery, CONFIG_TYPE, "path", "",
       on_load_path, path_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register_custom(sorcery, CONFIG_TYPE, "public_cert_url", "",
       on_load_public_cert_url, public_cert_url_to_str, NULL, 0, 0);
    ast_cli_register_multiple(stir_shaken_store_cli,
       ARRAY_LEN(stir_shaken_store_cli));
    return 0;
 }
stir_shaken_store_unload()
int stir_shaken_store_unload (void)
Unload time cleanup for the stir/shaken 'store' configuration.
Return values
0 on success, -1 on error
Definition at line 172 of file store.c.
References ARRAY_LEN, and ast_cli_unregister_multiple().
Referenced by unload_module().
 {
    ast_cli_unregister_multiple(stir_shaken_store_cli,
       ARRAY_LEN(stir_shaken_store_cli));
    return 0;
 }