Asterisk - The Open Source Telephony Project: udptl.h File Reference
udptl.h File Reference
UDPTL support for T.38.
#include "asterisk/network.h"
#include "asterisk/frame.h"
#include "asterisk/io.h"
#include "asterisk/sched.h"
#include "asterisk/channel.h"
#include "asterisk/netsock2.h"
Typedefs
typedef int(* ast_udptl_callback) (struct ast_udptl *udptl, struct ast_frame *f, void *data)
Enumerations
enum ast_t38_ec_modes { UDPTL_ERROR_CORRECTION_NONE, UDPTL_ERROR_CORRECTION_FEC, UDPTL_ERROR_CORRECTION_REDUNDANCY }
Functions
void ast_udptl_destroy (struct ast_udptl *udptl)
int ast_udptl_fd (const struct ast_udptl *udptl)
enum ast_t38_ec_modes ast_udptl_get_error_correction_scheme (const struct ast_udptl *udptl)
unsigned int ast_udptl_get_far_max_datagram (const struct ast_udptl *udptl)
unsigned int ast_udptl_get_far_max_ifp (struct ast_udptl *udptl)
retrieves far max ifp
unsigned int ast_udptl_get_local_max_datagram (struct ast_udptl *udptl)
retrieves local_max_datagram.
void ast_udptl_get_peer (const struct ast_udptl *udptl, struct ast_sockaddr *them)
void ast_udptl_get_us (const struct ast_udptl *udptl, struct ast_sockaddr *us)
struct ast_udptl * ast_udptl_new_with_bindaddr (struct ast_sched_context *sched, struct io_context *io, int callbackmode, struct ast_sockaddr *in)
struct ast_frame * ast_udptl_read (struct ast_udptl *udptl)
void ast_udptl_reset (struct ast_udptl *udptl)
void ast_udptl_set_callback (struct ast_udptl *udptl, ast_udptl_callback callback)
void ast_udptl_set_data (struct ast_udptl *udptl, void *data)
void ast_udptl_set_error_correction_scheme (struct ast_udptl *udptl, enum ast_t38_ec_modes ec)
void ast_udptl_set_far_max_datagram (struct ast_udptl *udptl, unsigned int max_datagram)
sets far max datagram size. If max_datagram is = 0, the far max datagram size is set to a default value.
void ast_udptl_set_local_max_ifp (struct ast_udptl *udptl, unsigned int max_ifp)
void ast_udptl_set_m_type (struct ast_udptl *udptl, unsigned int pt)
void ast_udptl_set_peer (struct ast_udptl *udptl, const struct ast_sockaddr *them)
void ast_udptl_set_tag (struct ast_udptl *udptl, const char *format,...)
Associates a character string 'tag' with a UDPTL session.
void ast_udptl_set_udptlmap_type (struct ast_udptl *udptl, unsigned int pt, char *mimeType, char *mimeSubtype)
void ast_udptl_setnat (struct ast_udptl *udptl, int nat)
int ast_udptl_setqos (struct ast_udptl *udptl, unsigned int tos, unsigned int cos)
void ast_udptl_stop (struct ast_udptl *udptl)
int ast_udptl_write (struct ast_udptl *udptl, struct ast_frame *f)
Detailed Description
UDPTL support for T.38.
Author
Steve Underwood steve.nosp@m.u@co.nosp@m.ppice.nosp@m..org udptl.c
Todo:
add doxygen documentation to this file!
Definition in file udptl.h.
Typedef Documentation
ast_udptl_callback
typedef int(* ast_udptl_callback) (struct ast_udptl *udptl, struct ast_frame *f, void *data)
Definition at line 49 of file udptl.h.
Enumeration Type Documentation
ast_t38_ec_modes
enum ast_t38_ec_modes
Enumerator
UDPTL_ERROR_CORRECTION_NONE
UDPTL_ERROR_CORRECTION_FEC
UDPTL_ERROR_CORRECTION_REDUNDANCY
Definition at line 37 of file udptl.h.
                       {
     UDPTL_ERROR_CORRECTION_NONE,
     UDPTL_ERROR_CORRECTION_FEC,
     UDPTL_ERROR_CORRECTION_REDUNDANCY
 };
Function Documentation
ast_udptl_destroy()
void ast_udptl_destroy (struct ast_udptl * udptl)
Definition at line 1150 of file udptl.c.
References ast_free, ast_io_remove(), ast_udptl::fd, ast_udptl::io, ast_udptl::ioid, and ast_udptl::tag.
Referenced by ooh323_destroy(), sip_pvt_dtor(), and stream_destroy().
 {
    if (udptl->ioid)
       ast_io_remove(udptl->io, udptl->ioid);
    if (udptl->fd > -1)
       close(udptl->fd);
    if (udptl->tag)
       ast_free(udptl->tag);
    ast_free(udptl);
 }
ast_udptl_fd()
int ast_udptl_fd (const struct ast_udptl * udptl)
Definition at line 730 of file udptl.c.
References ast_udptl::fd.
Referenced by apply_negotiated_sdp_stream(), configure_local_rtp(), initialize_udptl(), and sip_new().
 {
    return udptl->fd;
 }
ast_udptl_get_error_correction_scheme()
enum ast_t38_ec_modes ast_udptl_get_error_correction_scheme (const struct ast_udptl * udptl)
Definition at line 940 of file udptl.c.
References ast_udptl::error_correction_scheme.
Referenced by add_sdp(), and create_outgoing_sdp_stream().
 {
    return udptl->error_correction_scheme;
 }
ast_udptl_get_far_max_datagram()
unsigned int ast_udptl_get_far_max_datagram (const struct ast_udptl * udptl)
Definition at line 1008 of file udptl.c.
References ast_udptl::far_max_datagram.
Referenced by process_sdp().
 {
    if (udptl->far_max_datagram < 0) {
       return 0;
    }
    return udptl->far_max_datagram;
 }
ast_udptl_get_far_max_ifp()
unsigned int ast_udptl_get_far_max_ifp (struct ast_udptl * udptl)
retrieves far max ifp
Return values
positive value representing max ifp size
0 if no value is present
Definition at line 1016 of file udptl.c.
References calculate_far_max_ifp(), and ast_udptl::far_max_ifp.
Referenced by change_t38_state(), interpret_t38_parameters(), onModeChanged(), ooh323_indicate(), setup_udptl_connection(), t38_change_state(), and t38_interpret_parameters().
 {
    if (udptl->far_max_ifp == -1) {
       calculate_far_max_ifp(udptl);
    }
    if (udptl->far_max_ifp < 0) {
       return 0;
    }
    return udptl->far_max_ifp;
 }
ast_udptl_get_local_max_datagram()
unsigned int ast_udptl_get_local_max_datagram (struct ast_udptl * udptl)
retrieves local_max_datagram.
Return values
positive value representing max datagram size.
0 if no value is present
Definition at line 984 of file udptl.c.
References calculate_local_max_datagram(), and ast_udptl::local_max_datagram.
Referenced by add_sdp(), and create_outgoing_sdp_stream().
 {
    if (udptl->local_max_datagram == -1) {
       calculate_local_max_datagram(udptl);
    }
    /* this function expects a unsigned value in return. */
    if (udptl->local_max_datagram < 0) {
       return 0;
    }
    return udptl->local_max_datagram;
 }
ast_udptl_get_peer()
void ast_udptl_get_peer (const struct ast_udptl * udptl, struct ast_sockaddr * them)
Definition at line 1135 of file udptl.c.
References ast_sockaddr_copy(), and ast_udptl::them.
 {
    ast_sockaddr_copy(them, &udptl->them);
 }
ast_udptl_get_us()
void ast_udptl_get_us (const struct ast_udptl * udptl, struct ast_sockaddr * us)
Definition at line 1140 of file udptl.c.
References ast_sockaddr_copy(), and ast_udptl::us.
Referenced by add_sdp(), configure_local_rtp(), and create_outgoing_sdp_stream().
 {
    ast_sockaddr_copy(us, &udptl->us);
 }
ast_udptl_new_with_bindaddr()
struct ast_udptl* ast_udptl_new_with_bindaddr (struct ast_sched_context * sched, struct io_context * io, int callbackmode, struct ast_sockaddr * in)
Definition at line 1028 of file udptl.c.
References ao2_cleanup, ao2_global_obj_ref, ast_bind(), ast_calloc, ast_free, ast_io_add(), AST_IO_IN, ast_log, ast_random(), ast_sockaddr_copy(), ast_sockaddr_is_ipv6(), ast_sockaddr_set_port, ast_socket_nonblock, udptl_fec_tx_buffer_t::buf_len, udptl_fec_rx_buffer_t::buf_len, errno, ast_udptl::error_correction_entries, ast_udptl::error_correction_span, ast_udptl::far_max_datagram, ast_udptl::far_max_ifp, ast_udptl::fd, globals, ast_udptl::io, io, ast_udptl::ioid, ast_udptl::local_max_datagram, ast_udptl::local_max_ifp, LOG_ERROR, LOG_WARNING, NULL, RAII_VAR, ast_udptl::rx, ast_udptl::sched, sched, ast_udptl::tx, UDPTL_BUF_MASK, udptlread(), and ast_udptl::us.
Referenced by configure_local_rtp(), initialize_udptl(), and t38_initialize_session().
 {
    struct ast_udptl *udptl;
    int x;
    int startplace;
    int i;
    RAII_VAR(struct udptl_config *, cfg, ao2_global_obj_ref(globals), ao2_cleanup);
    if (!cfg || !cfg->general) {
       ast_log(LOG_ERROR, "Could not access global udptl options!\n");
       return NULL;
    }
    if (!(udptl = ast_calloc(1, sizeof(*udptl)))) {
       return NULL;
    }
    udptl->error_correction_span = cfg->general->fecspan;
    udptl->error_correction_entries = cfg->general->fecentries;
    udptl->far_max_datagram = -1;
    udptl->far_max_ifp = -1;
    udptl->local_max_ifp = -1;
    udptl->local_max_datagram = -1;
    for (i = 0; i <= UDPTL_BUF_MASK; i++) {
       udptl->rx[i].buf_len = -1;
       udptl->tx[i].buf_len = -1;
    }
    if ((udptl->fd = ast_socket_nonblock(ast_sockaddr_is_ipv6(addr) ?
                AF_INET6 : AF_INET, SOCK_DGRAM, 0)) < 0) {
       ast_free(udptl);
       ast_log(LOG_WARNING, "Unable to allocate socket: %s\n", strerror(errno));
       return NULL;
    }
 #ifdef SO_NO_CHECK
    if (cfg->general->nochecksums)
       setsockopt(udptl->fd, SOL_SOCKET, SO_NO_CHECK, &cfg->general->nochecksums, sizeof(cfg->general->nochecksums));
 #endif
    /* Find us a place */
    x = (cfg->general->start == cfg->general->end) ? cfg->general->start : (ast_random() % (cfg->general->end - cfg->general->start)) + cfg->general->start;
    if (cfg->general->use_even_ports && (x & 1)) {
       ++x;
    }
    startplace = x;
    for (;;) {
       ast_sockaddr_copy(&udptl->us, addr);
       ast_sockaddr_set_port(&udptl->us, x);
       if (ast_bind(udptl->fd, &udptl->us) == 0) {
          break;
       }
       if (errno != EADDRINUSE && errno != EACCES) {
          ast_log(LOG_WARNING, "Unexpected bind error: %s\n", strerror(errno));
          close(udptl->fd);
          ast_free(udptl);
          return NULL;
       }
       if (cfg->general->use_even_ports) {
          x += 2;
       } else {
          ++x;
       }
       if (x > cfg->general->end)
          x = cfg->general->start;
       if (x == startplace) {
          ast_log(LOG_WARNING, "No UDPTL ports remaining\n");
          close(udptl->fd);
          ast_free(udptl);
          return NULL;
       }
    }
    if (io && sched && callbackmode) {
       /* Operate this one in a callback mode */
       udptl->sched = sched;
       udptl->io = io;
       udptl->ioid = ast_io_add(udptl->io, udptl->fd, udptlread, AST_IO_IN, udptl);
    }
    return udptl;
 }
ast_udptl_read()
struct ast_frame* ast_udptl_read (struct ast_udptl * udptl)
Definition at line 762 of file udptl.c.
References ast_assert, ast_debug, AST_FRIENDLY_OFFSET, ast_log, ast_null_frame, ast_recvfrom(), ast_sockaddr_cmp(), ast_sockaddr_copy(), ast_sockaddr_isnull(), ast_sockaddr_stringify(), ast_verb, buf, errno, ast_udptl::f, ast_udptl::fd, LOG_TAG, LOG_WARNING, ast_udptl::nat, NULL, ast_udptl::rawdata, ast_udptl::tag, ast_udptl::them, udptl_debug_test_addr(), and udptl_rx_packet().
Referenced by media_session_udptl_read_callback(), ooh323_rtp_read(), sip_rtp_read(), skinny_rtp_read(), and udptlread().
 {
    int res;
    struct ast_sockaddr addr;
    uint8_t *buf;
    buf = udptl->rawdata + AST_FRIENDLY_OFFSET;
    /* Cache where the header will go */
    res = ast_recvfrom(udptl->fd,
          buf,
          sizeof(udptl->rawdata) - AST_FRIENDLY_OFFSET,
          0,
          &addr);
    if (res < 0) {
       if (errno != EAGAIN)
          ast_log(LOG_WARNING, "UDPTL (%s): read error: %s\n",
             LOG_TAG(udptl), strerror(errno));
       ast_assert(errno != EBADF);
       return &ast_null_frame;
    }
    /* Ignore if the other side hasn't been given an address yet. */
    if (ast_sockaddr_isnull(&udptl->them)) {
       return &ast_null_frame;
    }
    /*
     * If early media isn't turned on for the channel driver, it's going to
     * drop this frame.  By that time though, udptl has already incremented
     * the expected sequence number so if the CPE re-sends, the second frame
     * will be dropped as a dup even though the first frame never went through.
     * So we drop the frame here if the channel isn't up. 'tag' is set by the
     * channel drivers on T38_ENABLED or T38_PEER_REINVITE.
     */
    if (udptl->tag == NULL) {
       return &ast_null_frame;
    }
    if (udptl->nat) {
       /* Send to whoever sent to us */
       if (ast_sockaddr_cmp(&udptl->them, &addr)) {
          ast_sockaddr_copy(&udptl->them, &addr);
          ast_debug(1, "UDPTL (%s): NAT, Using address %s\n",
               LOG_TAG(udptl), ast_sockaddr_stringify(&udptl->them));
       }
    }
    if (udptl_debug_test_addr(&addr)) {
       int seq_no;
       /* Decode sequence number just for verbose message. */
       if (res < 2) {
          /* Short packet. */
          seq_no = -1;
       } else {
          seq_no = (buf[0] << 8) | buf[1];
       }
       ast_verb(1, "UDPTL (%s): packet from %s (seq %d, len %d)\n",
          LOG_TAG(udptl), ast_sockaddr_stringify(&addr), seq_no, res);
    }
    if (udptl_rx_packet(udptl, buf, res) < 1) {
       return &ast_null_frame;
    }
    return &udptl->f[0];
 }
ast_udptl_reset()
void ast_udptl_reset (struct ast_udptl * udptl)
ast_udptl_set_callback()
void ast_udptl_set_callback (struct ast_udptl * udptl, ast_udptl_callback callback)
Definition at line 740 of file udptl.c.
References ast_udptl::callback.
 {
    udptl->callback = callback;
 }
ast_udptl_set_data()
void ast_udptl_set_data (struct ast_udptl * udptl, void * data)
Definition at line 735 of file udptl.c.
References ast_udptl::data.
 {
    udptl->data = data;
 }
ast_udptl_set_error_correction_scheme()
void ast_udptl_set_error_correction_scheme (struct ast_udptl * udptl, enum ast_t38_ec_modes ec)
Definition at line 945 of file udptl.c.
References ast_udptl::error_correction_entries, ast_udptl::error_correction_scheme, ast_udptl::error_correction_span, ast_udptl::far_max_ifp, ast_udptl::local_max_datagram, UDPTL_ERROR_CORRECTION_FEC, and UDPTL_ERROR_CORRECTION_REDUNDANCY.
Referenced by process_sdp(), process_sdp_a_image(), set_t38_capabilities(), t38_initialize_session(), and t38_interpret_sdp().
 {
    udptl->error_correction_scheme = ec;
    switch (ec) {
    case UDPTL_ERROR_CORRECTION_FEC:
       udptl->error_correction_scheme = UDPTL_ERROR_CORRECTION_FEC;
       if (udptl->error_correction_entries == 0) {
          udptl->error_correction_entries = 3;
       }
       if (udptl->error_correction_span == 0) {
          udptl->error_correction_span = 3;
       }
       break;
    case UDPTL_ERROR_CORRECTION_REDUNDANCY:
       udptl->error_correction_scheme = UDPTL_ERROR_CORRECTION_REDUNDANCY;
       if (udptl->error_correction_entries == 0) {
          udptl->error_correction_entries = 3;
       }
       break;
    default:
       /* nothing to do */
       break;
    };
    /* reset calculated values so they'll be computed again */
    udptl->local_max_datagram = -1;
    udptl->far_max_ifp = -1;
 }
ast_udptl_set_far_max_datagram()
void ast_udptl_set_far_max_datagram (struct ast_udptl * udptl, unsigned int max_datagram)
sets far max datagram size. If max_datagram is = 0, the far max datagram size is set to a default value.
Definition at line 997 of file udptl.c.
References DEFAULT_FAX_MAX_DATAGRAM, ast_udptl::far_max_datagram, ast_udptl::far_max_ifp, and FAX_MAX_DATAGRAM_LIMIT.
Referenced by configure_local_rtp(), onModeChanged(), process_sdp(), process_sdp_a_image(), t38_initialize_session(), and t38_interpret_sdp().
 {
    if (!max_datagram || (max_datagram > FAX_MAX_DATAGRAM_LIMIT)) {
       udptl->far_max_datagram = DEFAULT_FAX_MAX_DATAGRAM;
    } else {
       udptl->far_max_datagram = max_datagram;
    }
    /* reset calculated values so they'll be computed again */
    udptl->far_max_ifp = -1;
 }
ast_udptl_set_local_max_ifp()
void ast_udptl_set_local_max_ifp (struct ast_udptl * udptl, unsigned int max_ifp)
Definition at line 973 of file udptl.c.
References ast_udptl::local_max_datagram, and ast_udptl::local_max_ifp.
Referenced by interpret_t38_parameters(), and t38_interpret_parameters().
 {
    /* make sure max_ifp is a positive value since a cast will take place when
     * when setting local_max_ifp */
    if ((signed int) max_ifp > 0) {
       udptl->local_max_ifp = max_ifp;
       /* reset calculated values so they'll be computed again */
       udptl->local_max_datagram = -1;
    }
 }
ast_udptl_set_m_type()
void ast_udptl_set_m_type (struct ast_udptl * udptl, unsigned int pt)
ast_udptl_set_peer()
void ast_udptl_set_peer (struct ast_udptl * udptl, const struct ast_sockaddr * them)
Definition at line 1130 of file udptl.c.
References ast_sockaddr_copy(), and ast_udptl::them.
Referenced by apply_negotiated_sdp_stream(), process_sdp(), and setup_udptl_connection().
 {
    ast_sockaddr_copy(&udptl->them, them);
 }
ast_udptl_set_tag()
void ast_udptl_set_tag (struct ast_udptl * udptl, const char * format, ...)
Associates a character string 'tag' with a UDPTL session.
Parameters
udptl The UDPTL session.
format printf-style format string used to construct the tag
This function formats a tag for the specified UDPTL session, so that any log messages generated by the UDPTL stack related to that session will include the tag and the reader of the messages will be able to identify which endpoint caused them to be generated.
Return values
none
Definition at line 1112 of file udptl.c.
References ast_free, ast_vasprintf, NULL, and ast_udptl::tag.
Referenced by change_t38_state(), setup_udptl_connection(), and t38_change_state().
 {
    va_list ap;
    ast_free(udptl->tag);
    udptl->tag = NULL;
    va_start(ap, format);
    if (ast_vasprintf(&udptl->tag, format, ap) == -1) {
       udptl->tag = NULL;
    }
    va_end(ap);
 }
ast_udptl_set_udptlmap_type()
void ast_udptl_set_udptlmap_type (struct ast_udptl * udptl, unsigned int pt, char * mimeType, char * mimeSubtype)
ast_udptl_setnat()
void ast_udptl_setnat (struct ast_udptl * udptl, int nat)
Definition at line 745 of file udptl.c.
References ast_udptl::nat, and nat.
Referenced by do_setnat(), initialize_udptl(), and t38_initialize_session().
 {
    udptl->nat = nat;
 }
ast_udptl_setqos()
int ast_udptl_setqos (struct ast_udptl * udptl, unsigned int tos, unsigned int cos)
Definition at line 1125 of file udptl.c.
References ast_set_qos(), and ast_udptl::fd.
Referenced by initialize_udptl().
 {
    return ast_set_qos(udptl->fd, tos, cos, "UDPTL");
 }
ast_udptl_stop()
void ast_udptl_stop (struct ast_udptl * udptl)
Definition at line 1145 of file udptl.c.
References ast_sockaddr_setnull(), and ast_udptl::them.
Referenced by process_sdp(), and stop_media_flows().
 {
    ast_sockaddr_setnull(&udptl->them);
 }
ast_udptl_write()
int ast_udptl_write (struct ast_udptl * udptl, struct ast_frame * f)
Definition at line 1161 of file udptl.c.
References AST_FRAME_MODEM, ast_log, AST_MODEM_T38, ast_sendto(), ast_sockaddr_isnull(), ast_sockaddr_stringify(), ast_verb, buf, ast_frame::data, ast_frame::datalen, DEFAULT_FAX_MAX_DATAGRAM, errno, ast_udptl::far_max_datagram, ast_udptl::far_max_ifp, ast_udptl::fd, ast_frame::frametype, ast_frame_subclass::integer, ast_sockaddr::len, LOG_NOTICE, LOG_TAG, LOG_WARNING, ast_frame::ptr, seq, ast_frame::subclass, ast_udptl::them, ast_udptl::tx_seq_no, udptl_build_packet(), and udptl_debug_test_addr().
Referenced by media_session_udptl_write_callback(), ooh323_write(), and sip_write().
 {
    unsigned int seq;
    unsigned int len = f->datalen;
    /* if no max datagram size is provided, use default value */
    const int bufsize = (s->far_max_datagram > 0) ? s->far_max_datagram : DEFAULT_FAX_MAX_DATAGRAM;
    uint8_t buf[bufsize];
    memset(buf, 0, sizeof(buf));
    /* If we have no peer, return immediately */
    if (ast_sockaddr_isnull(&s->them)) {
       return 0;
    }
    /* If there is no data length, return immediately */
    if (f->datalen == 0)
       return 0;
    if ((f->frametype != AST_FRAME_MODEM) ||
        (f->subclass.integer != AST_MODEM_T38)) {
       ast_log(LOG_WARNING, "UDPTL (%s): UDPTL can only send T.38 data.\n",
          LOG_TAG(s));
       return -1;
    }
    if (len > s->far_max_ifp) {
       ast_log(LOG_WARNING,
          "UDPTL (%s): UDPTL asked to send %u bytes of IFP when far end only prepared to accept %d bytes; data loss will occur."
          "You may need to override the T38FaxMaxDatagram value for this endpoint in the channel driver configuration.\n",
          LOG_TAG(s), len, s->far_max_ifp);
       len = s->far_max_ifp;
    }
    /* Save seq_no for debug output because udptl_build_packet increments it */
    seq = s->tx_seq_no & 0xFFFF;
    /* Cook up the UDPTL packet, with the relevant EC info. */
    len = udptl_build_packet(s, buf, sizeof(buf), f->data.ptr, len);
    if ((signed int) len > 0 && !ast_sockaddr_isnull(&s->them)) {
       if (ast_sendto(s->fd, buf, len, 0, &s->them) < 0) {
          ast_log(LOG_NOTICE, "UDPTL (%s): Transmission error to %s: %s\n",
             LOG_TAG(s), ast_sockaddr_stringify(&s->them), strerror(errno));
       }
       if (udptl_debug_test_addr(&s->them)) {
          ast_verb(1, "UDPTL (%s): packet to %s (seq %u, len %u)\n",
             LOG_TAG(s), ast_sockaddr_stringify(&s->them), seq, len);
       }
    }
    return 0;
 }