Asterisk - The Open Source Telephony Project: res_pjproject.h File Reference
res_pjproject.h File Reference
#include <pj/types.h>
#include <pj/pool.h>
Functions
void ast_pjproject_caching_pool_destroy (pj_caching_pool *cp)
Destroy caching pool factory and all cached pools.
void ast_pjproject_caching_pool_init (pj_caching_pool *cp, const pj_pool_factory_policy *policy, pj_size_t max_capacity)
Initialize the caching pool factory.
int ast_pjproject_get_buildopt (char *option, char *format_string,...)
Retrieve a pjproject build option.
void ast_pjproject_log_intercept_begin (int fd)
Begin PJPROJECT log interception for CLI output.
void ast_pjproject_log_intercept_end (void)
End PJPROJECT log interception for CLI output.
int ast_sockaddr_from_pj_sockaddr (struct ast_sockaddr *addr, const pj_sockaddr *pjaddr)
Fill an ast_sockaddr from a pj_sockaddr.
int ast_sockaddr_to_pj_sockaddr (const struct ast_sockaddr *addr, pj_sockaddr *pjaddr)
Fill a pj_sockaddr from an ast_sockaddr.
Function Documentation
ast_pjproject_caching_pool_destroy()
void ast_pjproject_caching_pool_destroy (pj_caching_pool * cp)
Destroy caching pool factory and all cached pools.
Since
13.21.0
Parameters
cp Caching pool factory to destroy
Returns
Nothing
Definition at line 472 of file res_pjproject.c.
Referenced by rtp_terminate_pjproject(), unload_module(), and unload_pjsip().
 {
    pj_caching_pool_destroy(cp);
 }
ast_pjproject_caching_pool_init()
void ast_pjproject_caching_pool_init (pj_caching_pool * cp, const pj_pool_factory_policy * policy, pj_size_t max_capacity)
Initialize the caching pool factory.
Since
13.21.0
Parameters
cp Caching pool factory to initialize
policy Pool factory policy
max_capacity Total capacity to be retained in the cache. Zero disables caching.
Returns
Nothing
Definition at line 465 of file res_pjproject.c.
References ast_option_pjproject_cache_pools.
Referenced by load_module(), and load_pjsip().
 {
    /* Passing a max_capacity of zero disables caching pools */
    pj_caching_pool_init(cp, policy, ast_option_pjproject_cache_pools ? max_capacity : 0);
 }
ast_pjproject_get_buildopt()
int ast_pjproject_get_buildopt (char * option, char * format_string, ...)
Retrieve a pjproject build option.
Parameters
option The build option requested
format_string A scanf-style format string to parse the option value into
... Pointers to variables to receive the values parsed
Return values
The number of values parsed
Since
13.8.0
Note
The option requested must be from those returned by pj_dump_config() which can be displayed with the 'pjsip show buildopts' CLI command.
Sample Usage:
int max_hostname;
ast_sip_get_pjproject_buildopt("PJ_MAX_HOSTNAME", "%d", &max_hostname);
Definition at line 246 of file res_pjproject.c.
References ast_alloca, AST_VECTOR_GET, and AST_VECTOR_SIZE.
Referenced by ast_sip_initialize_sorcery_location(), and load_module().
 {
    int res = 0;
    char *format_temp;
    int i;
    format_temp = ast_alloca(strlen(option) + strlen(" : ") + strlen(format_string) + 1);
    sprintf(format_temp, "%s : %s", option, format_string);
    for (i = 0; i < AST_VECTOR_SIZE(&buildopts); i++) {
       va_list arg_ptr;
       va_start(arg_ptr, format_string);
       res = vsscanf(AST_VECTOR_GET(&buildopts, i), format_temp, arg_ptr);
       va_end(arg_ptr);
       if (res) {
          break;
       }
    }
    return res;
 }
ast_pjproject_log_intercept_begin()
void ast_pjproject_log_intercept_begin (int fd)
Begin PJPROJECT log interception for CLI output.
Since
13.8.0
Parameters
fd CLI file descriptior to send intercepted output.
Note
ast_pjproject_log_intercept_begin() and ast_pjproject_log_intercept_end() must always be called in pairs.
Returns
Nothing
Definition at line 269 of file res_pjproject.c.
References ast_mutex_lock, pjproject_log_intercept_data::fd, and pjproject_log_intercept_data::thread.
Referenced by do_cli_dump_endpt().
 {
    /* Protect from other CLI instances trying to do this at the same time. */
    ast_mutex_lock(&pjproject_log_intercept_lock);
    pjproject_log_intercept.thread = pthread_self();
    pjproject_log_intercept.fd = fd;
 }
ast_pjproject_log_intercept_end()
void ast_pjproject_log_intercept_end (void)
End PJPROJECT log interception for CLI output.
Since
13.8.0
Note
ast_pjproject_log_intercept_begin() and ast_pjproject_log_intercept_end() must always be called in pairs.
Returns
Nothing
Definition at line 278 of file res_pjproject.c.
References ast_mutex_unlock, AST_PTHREADT_NULL, pjproject_log_intercept_data::fd, and pjproject_log_intercept_data::thread.
Referenced by do_cli_dump_endpt().
 {
    pjproject_log_intercept.fd = -1;
    pjproject_log_intercept.thread = AST_PTHREADT_NULL;
    ast_mutex_unlock(&pjproject_log_intercept_lock);
 }
ast_sockaddr_from_pj_sockaddr()
int ast_sockaddr_from_pj_sockaddr (struct ast_sockaddr * addr, const pj_sockaddr * pjaddr)
Fill an ast_sockaddr from a pj_sockaddr.
Since
13.24.0
Parameters
addr The target address to receive the copied address
pjaddr The source address to copy
Return values
0 Success
-1 Failure
Definition at line 502 of file res_pjproject.c.
References HAVE_PJPROJECT_BUNDLED, ast_sockaddr::len, and ast_sockaddr::ss.
Referenced by AST_TEST_DEFINE().
 {
    if (pjaddr->addr.sa_family == pj_AF_INET()) {
       struct sockaddr_in *sin = (struct sockaddr_in *) &addr->ss;
       sin->sin_family = AF_INET;
 #ifdef HAVE_PJPROJECT_BUNDLED
       sin->sin_addr = pjaddr->ipv4.sin_addr;
 #else
       sin->sin_addr.s_addr = pjaddr->ipv4.sin_addr.s_addr;
 #endif
       sin->sin_port   = pjaddr->ipv4.sin_port;
       addr->len = sizeof(struct sockaddr_in);
    } else if (pjaddr->addr.sa_family == pj_AF_INET6()) {
       struct sockaddr_in6 *sin = (struct sockaddr_in6 *) &addr->ss;
       sin->sin6_family   = AF_INET6;
       sin->sin6_port     = pjaddr->ipv6.sin6_port;
       sin->sin6_flowinfo = pjaddr->ipv6.sin6_flowinfo;
       sin->sin6_scope_id = pjaddr->ipv6.sin6_scope_id;
       memcpy(&sin->sin6_addr, &pjaddr->ipv6.sin6_addr, sizeof(sin->sin6_addr));
       addr->len = sizeof(struct sockaddr_in6);
    } else {
       memset(addr, 0, sizeof(*addr));
       return -1;
    }
    return 0;
 }
ast_sockaddr_to_pj_sockaddr()
int ast_sockaddr_to_pj_sockaddr (const struct ast_sockaddr * addr, pj_sockaddr * pjaddr)
Fill a pj_sockaddr from an ast_sockaddr.
Since
13.24.0
Parameters
addr The source address to copy
pjaddr The target address to receive the copied address
Return values
0 Success
-1 Failure
Definition at line 477 of file res_pjproject.c.
References ast_sockaddr::ss.
Referenced by AST_TEST_DEFINE(), and rtp_add_candidates_to_ice().
 {
    if (addr->ss.ss_family == AF_INET) {
       struct sockaddr_in *sin = (struct sockaddr_in *) &addr->ss;
       pjaddr->ipv4.sin_family = pj_AF_INET();
 #ifdef HAVE_PJPROJECT_BUNDLED
       pjaddr->ipv4.sin_addr = sin->sin_addr;
 #else
       pjaddr->ipv4.sin_addr.s_addr = sin->sin_addr.s_addr;
 #endif
       pjaddr->ipv4.sin_port   = sin->sin_port;
    } else if (addr->ss.ss_family == AF_INET6) {
       struct sockaddr_in6 *sin = (struct sockaddr_in6 *) &addr->ss;
       pjaddr->ipv6.sin6_family   = pj_AF_INET6();
       pjaddr->ipv6.sin6_port     = sin->sin6_port;
       pjaddr->ipv6.sin6_flowinfo = sin->sin6_flowinfo;
       pjaddr->ipv6.sin6_scope_id = sin->sin6_scope_id;
       memcpy(&pjaddr->ipv6.sin6_addr, &sin->sin6_addr, sizeof(pjaddr->ipv6.sin6_addr));
    } else {
       memset(pjaddr, 0, sizeof(*pjaddr));
       return -1;
    }
    return 0;
 }