Asterisk - The Open Source Telephony Project: features.c File Reference
features.c File Reference
Routines implementing call features as call pickup, parking and transfer.
#include "asterisk.h"
#include "asterisk/_private.h"
#include "features_config.h"
#include <pthread.h>
#include <signal.h>
#include <sys/time.h>
#include <netinet/in.h>
#include "asterisk/lock.h"
#include "asterisk/file.h"
#include "asterisk/channel.h"
#include "asterisk/pbx.h"
#include "asterisk/causes.h"
#include "asterisk/module.h"
#include "asterisk/translate.h"
#include "asterisk/app.h"
#include "asterisk/say.h"
#include "asterisk/features.h"
#include "asterisk/musiconhold.h"
#include "asterisk/config.h"
#include "asterisk/cli.h"
#include "asterisk/manager.h"
#include "asterisk/utils.h"
#include "asterisk/devicestate.h"
#include "asterisk/audiohook.h"
#include "asterisk/global_datastores.h"
#include "asterisk/astobj2.h"
#include "asterisk/test.h"
#include "asterisk/bridge.h"
#include "asterisk/bridge_features.h"
#include "asterisk/bridge_basic.h"
#include "asterisk/bridge_after.h"
#include "asterisk/stasis.h"
#include "asterisk/stasis_channels.h"
#include "asterisk/features_config.h"
#include "asterisk/max_forwards.h"
#include "asterisk/stream.h"
Data Structures
struct ast_bridge_thread_obj
struct ast_dial_features
Enumerations
enum {
BRIDGE_OPT_PLAYTONE = (1 << 0), OPT_CALLEE_HANGUP = (1 << 1), OPT_CALLER_HANGUP = (1 << 2), OPT_DURATION_LIMIT = (1 << 3),
OPT_DURATION_STOP = (1 << 4), OPT_CALLEE_TRANSFER = (1 << 5), OPT_CALLER_TRANSFER = (1 << 6), OPT_CALLEE_MONITOR = (1 << 7),
OPT_CALLER_MONITOR = (1 << 8), OPT_CALLEE_PARK = (1 << 9), OPT_CALLER_PARK = (1 << 10), OPT_CALLEE_KILL = (1 << 11),
OPT_CALLEE_GO_ON = (1 << 12)
}
enum { OPT_ARG_DURATION_LIMIT = 0, OPT_ARG_DURATION_STOP, OPT_ARG_CALLEE_GO_ON, OPT_ARG_ARRAY_SIZE }
enum feature_interpret_op { FEATURE_INTERPRET_DETECT, FEATURE_INTERPRET_DO, FEATURE_INTERPRET_CHECK }
enum play_tone_action { PLAYTONE_NONE = 0, PLAYTONE_CHANNEL1 = (1 << 0), PLAYTONE_CHANNEL2 = (1 << 1), PLAYTONE_BOTH = PLAYTONE_CHANNEL1 | PLAYTONE_CHANNEL2 }
Functions
static void __reg_module (void)
static void __unreg_module (void)
static int action_bridge (struct mansession *s, const struct message *m)
Bridge channels together.
static int add_features_datastore (struct ast_channel *chan, const struct ast_flags *my_features, const struct ast_flags *peer_features)
static void add_features_datastores (struct ast_channel *caller, struct ast_channel *callee, struct ast_bridge_config *config)
int ast_bridge_call (struct ast_channel *chan, struct ast_channel *peer, struct ast_bridge_config *config)
bridge the call and set CDR
int ast_bridge_call_with_flags (struct ast_channel *chan, struct ast_channel *peer, struct ast_bridge_config *config, unsigned int flags)
Bridge a call, and add additional flags to the bridge.
int ast_bridge_timelimit (struct ast_channel *chan, struct ast_bridge_config *config, char *parse, struct timeval *calldurationlimit)
parse L option and read associated channel variables to set warning, warning frequency, and timelimit
void ast_channel_log (char *title, struct ast_channel *chan)
struct ast_module * AST_MODULE_SELF_SYM (void)
static void bridge_check_monitor (struct ast_channel *chan, struct ast_channel *peer)
static void bridge_config_set_limits (struct ast_bridge_config *config, struct ast_bridge_features_limits *caller_limits, struct ast_bridge_features_limits *callee_limits)
static void bridge_config_set_limits_warning_values (struct ast_bridge_config *config, struct ast_bridge_features_limits *limits)
static int bridge_exec (struct ast_channel *chan, const char *data)
Bridge channels.
static void bridge_failed_peer_goto (struct ast_channel *chan, struct ast_channel *peer)
static void * dial_features_duplicate (void *data)
static int load_module (void)
static enum play_tone_action parse_playtone (const char *playtone_val)
static int pre_bridge_setup (struct ast_channel *chan, struct ast_channel *peer, struct ast_bridge_config *config, struct ast_bridge_features *chan_features, struct ast_bridge_features *peer_features)
static void set_bridge_features_on_config (struct ast_bridge_config *config, const char *features)
static void set_config_flags (struct ast_channel *chan, struct ast_bridge_config *config)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_GLOBAL_SYMBOLS | AST_MODFLAG_LOAD_ORDER , .description = "Call Features" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .reload = reload_features_config, .load_pri = AST_MODPRI_CORE, .requires = "extconfig", }
static char * app_bridge = "Bridge"
static const struct ast_module_info * ast_module_info = &__mod_info
static const struct ast_app_option bridge_exec_options [128] = { [ 'p' ] = { .flag = BRIDGE_OPT_PLAYTONE }, [ 'F' ] = { .flag = OPT_CALLEE_GO_ON , .arg_index = OPT_ARG_CALLEE_GO_ON + 1 }, [ 'h' ] = { .flag = OPT_CALLEE_HANGUP }, [ 'H' ] = { .flag = OPT_CALLER_HANGUP }, [ 'k' ] = { .flag = OPT_CALLEE_PARK }, [ 'K' ] = { .flag = OPT_CALLER_PARK }, [ 'L' ] = { .flag = OPT_DURATION_LIMIT , .arg_index = OPT_ARG_DURATION_LIMIT + 1 }, [ 'S' ] = { .flag = OPT_DURATION_STOP , .arg_index = OPT_ARG_DURATION_STOP + 1 }, [ 't' ] = { .flag = OPT_CALLEE_TRANSFER }, [ 'T' ] = { .flag = OPT_CALLER_TRANSFER }, [ 'w' ] = { .flag = OPT_CALLEE_MONITOR }, [ 'W' ] = { .flag = OPT_CALLER_MONITOR }, [ 'x' ] = { .flag = OPT_CALLEE_KILL }, }
static const struct ast_datastore_info dial_features_info
Detailed Description
Routines implementing call features as call pickup, parking and transfer.
Author
Mark Spencer marks.nosp@m.ter@.nosp@m.digiu.nosp@m.m.co.nosp@m.m
Definition in file features.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
BRIDGE_OPT_PLAYTONE
OPT_CALLEE_HANGUP
OPT_CALLER_HANGUP
OPT_DURATION_LIMIT
OPT_DURATION_STOP
OPT_CALLEE_TRANSFER
OPT_CALLER_TRANSFER
OPT_CALLEE_MONITOR
OPT_CALLER_MONITOR
OPT_CALLEE_PARK
OPT_CALLER_PARK
OPT_CALLEE_KILL
OPT_CALLEE_GO_ON
Definition at line 846 of file features.c.
      {
    BRIDGE_OPT_PLAYTONE = (1 << 0),
    OPT_CALLEE_HANGUP =  (1 << 1),
    OPT_CALLER_HANGUP =  (1 << 2),
    OPT_DURATION_LIMIT = (1 << 3),
    OPT_DURATION_STOP =  (1 << 4),
    OPT_CALLEE_TRANSFER = (1 << 5),
    OPT_CALLER_TRANSFER = (1 << 6),
    OPT_CALLEE_MONITOR = (1 << 7),
    OPT_CALLER_MONITOR = (1 << 8),
    OPT_CALLEE_PARK = (1 << 9),
    OPT_CALLER_PARK = (1 << 10),
    OPT_CALLEE_KILL = (1 << 11),
    OPT_CALLEE_GO_ON = (1 << 12),
 };
anonymous enum
anonymous enum
Enumerator
OPT_ARG_DURATION_LIMIT
OPT_ARG_DURATION_STOP
OPT_ARG_CALLEE_GO_ON
OPT_ARG_ARRAY_SIZE
Definition at line 862 of file features.c.
      {
    OPT_ARG_DURATION_LIMIT = 0,
    OPT_ARG_DURATION_STOP,
    OPT_ARG_CALLEE_GO_ON,
    /* note: this entry _MUST_ be the last one in the enum */
    OPT_ARG_ARRAY_SIZE,
 };
feature_interpret_op
enum feature_interpret_op
Enumerator
FEATURE_INTERPRET_DETECT
FEATURE_INTERPRET_DO
FEATURE_INTERPRET_CHECK
Definition at line 249 of file features.c.
              {
    FEATURE_INTERPRET_DETECT, /* Used by ast_feature_detect */
    FEATURE_INTERPRET_DO,     /* Used by feature_interpret */
    FEATURE_INTERPRET_CHECK,  /* Used by feature_check */
 } feature_interpret_op;
play_tone_action
enum play_tone_action
Enumerator
PLAYTONE_NONE
PLAYTONE_CHANNEL1
PLAYTONE_CHANNEL2
PLAYTONE_BOTH
Definition at line 721 of file features.c.
                       {
    PLAYTONE_NONE = 0,
    PLAYTONE_CHANNEL1 = (1 << 0),
    PLAYTONE_CHANNEL2 = (1 << 1),
    PLAYTONE_BOTH = PLAYTONE_CHANNEL1 | PLAYTONE_CHANNEL2,
 };
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 1186 of file features.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 1186 of file features.c.
action_bridge()
static int action_bridge (struct mansession * s, const struct message * m) static
Bridge channels together.
Parameters
s
m Make sure valid channels were specified, send errors if any of the channels could not be found/locked, answer channels if needed, create the placeholder channels and grab the other channels make the channels compatible, send error if we fail doing so setup the bridge thread object and start the bridge.
Return values
0
Definition at line 757 of file features.c.
References ao2_cleanup, ast_bridge_add_channel(), ast_bridge_basic_new(), ast_bridge_destroy(), ast_bridge_set_after_goto(), ast_channel_context(), ast_channel_exten(), ast_channel_flags(), ast_channel_get_by_name_prefix(), ast_channel_lock, ast_channel_name(), ast_channel_priority(), ast_channel_unlock, ast_debug, AST_FLAG_IN_AUTOLOOP, ast_get_chan_features_xfer_config(), ast_strdupa, ast_strlen_zero, ast_test_flag, astman_get_header(), astman_send_ack(), astman_send_error(), buf, NULL, parse_playtone(), playtone(), PLAYTONE_CHANNEL1, PLAYTONE_CHANNEL2, and RAII_VAR.
Referenced by load_module().
 {
    const char *channela = astman_get_header(m, "Channel1");
    const char *channelb = astman_get_header(m, "Channel2");
    enum play_tone_action playtone = parse_playtone(astman_get_header(m, "Tone"));
    RAII_VAR(struct ast_channel *, chana, NULL, ao2_cleanup);
    RAII_VAR(struct ast_channel *, chanb, NULL, ao2_cleanup);
    const char *chana_exten;
    const char *chana_context;
    int chana_priority;
    const char *chanb_exten;
    const char *chanb_context;
    int chanb_priority;
    struct ast_bridge *bridge;
    char buf[256];
    RAII_VAR(struct ast_features_xfer_config *, xfer_cfg_a, NULL, ao2_cleanup);
    RAII_VAR(struct ast_features_xfer_config *, xfer_cfg_b, NULL, ao2_cleanup);
    /* make sure valid channels were specified */
    if (ast_strlen_zero(channela) || ast_strlen_zero(channelb)) {
       astman_send_error(s, m, "Missing channel parameter in request");
       return 0;
    }
    ast_debug(1, "Performing Bridge action on %s and %s\n", channela, channelb);
    /* Start with chana */
    chana = ast_channel_get_by_name_prefix(channela, strlen(channela));
    if (!chana) {
       snprintf(buf, sizeof(buf), "Channel1 does not exist: %s", channela);
       astman_send_error(s, m, buf);
       return 0;
    }
    ast_channel_lock(chana);
    xfer_cfg_a = ast_get_chan_features_xfer_config(chana);
    chana_exten = ast_strdupa(ast_channel_exten(chana));
    chana_context = ast_strdupa(ast_channel_context(chana));
    chana_priority = ast_channel_priority(chana);
    if (ast_test_flag(ast_channel_flags(chana), AST_FLAG_IN_AUTOLOOP)) {
       chana_priority++;
    }
    ast_channel_unlock(chana);
    chanb = ast_channel_get_by_name_prefix(channelb, strlen(channelb));
    if (!chanb) {
       snprintf(buf, sizeof(buf), "Channel2 does not exist: %s", channelb);
       astman_send_error(s, m, buf);
       return 0;
    }
    ast_channel_lock(chanb);
    xfer_cfg_b = ast_get_chan_features_xfer_config(chanb);
    chanb_exten = ast_strdupa(ast_channel_exten(chanb));
    chanb_context = ast_strdupa(ast_channel_context(chanb));
    chanb_priority = ast_channel_priority(chanb);
    if (ast_test_flag(ast_channel_flags(chanb), AST_FLAG_IN_AUTOLOOP)) {
       chanb_priority++;
    }
    ast_channel_unlock(chanb);
    bridge = ast_bridge_basic_new();
    if (!bridge) {
       astman_send_error(s, m, "Unable to create bridge\n");
       return 0;
    }
    ast_bridge_set_after_goto(chana, chana_context, chana_exten, chana_priority);
    if (ast_bridge_add_channel(bridge, chana, NULL, playtone & PLAYTONE_CHANNEL1, xfer_cfg_a ? xfer_cfg_a->xfersound : NULL)) {
       snprintf(buf, sizeof(buf), "Unable to add Channel1 to bridge: %s", ast_channel_name(chana));
       astman_send_error(s, m, buf);
       ast_bridge_destroy(bridge, 0);
       return 0;
    }
    ast_bridge_set_after_goto(chanb, chanb_context, chanb_exten, chanb_priority);
    if (ast_bridge_add_channel(bridge, chanb, NULL, playtone & PLAYTONE_CHANNEL2, xfer_cfg_b ? xfer_cfg_b->xfersound : NULL)) {
       snprintf(buf, sizeof(buf), "Unable to add Channel2 to bridge: %s", ast_channel_name(chanb));
       astman_send_error(s, m, buf);
       ast_bridge_destroy(bridge, 0);
       return 0;
    }
    astman_send_ack(s, m, "Channels have been bridged");
    ao2_cleanup(bridge);
    return 0;
 }
add_features_datastore()
static int add_features_datastore (struct ast_channel * chan, const struct ast_flags * my_features, const struct ast_flags * peer_features) static
Definition at line 291 of file features.c.
References ast_calloc, ast_channel_datastore_add(), ast_channel_datastore_find(), ast_channel_lock, ast_channel_unlock, ast_copy_flags, ast_datastore_alloc, ast_datastore_free(), AST_FLAGS_ALL, ast_log, ast_datastore::data, DATASTORE_INHERIT_FOREVER, ast_datastore::inheritance, LOG_WARNING, ast_dial_features::my_features, NULL, and ast_dial_features::peer_features.
Referenced by add_features_datastores().
 {
    struct ast_datastore *datastore;
    struct ast_dial_features *dialfeatures;
    ast_channel_lock(chan);
    datastore = ast_channel_datastore_find(chan, &dial_features_info, NULL);
    ast_channel_unlock(chan);
    if (datastore) {
       /* Already exists. */
       return 1;
    }
    /* Create a new datastore with specified feature flags. */
    datastore = ast_datastore_alloc(&dial_features_info, NULL);
    if (!datastore) {
       ast_log(LOG_WARNING, "Unable to create channel features datastore.\n");
       return 0;
    }
    dialfeatures = ast_calloc(1, sizeof(*dialfeatures));
    if (!dialfeatures) {
       ast_log(LOG_WARNING, "Unable to allocate memory for feature flags.\n");
       ast_datastore_free(datastore);
       return 0;
    }
    ast_copy_flags(&dialfeatures->my_features, my_features, AST_FLAGS_ALL);
    ast_copy_flags(&dialfeatures->peer_features, peer_features, AST_FLAGS_ALL);
    datastore->inheritance = DATASTORE_INHERIT_FOREVER;
    datastore->data = dialfeatures;
    ast_channel_lock(chan);
    ast_channel_datastore_add(chan, datastore);
    ast_channel_unlock(chan);
    return 0;
 }
add_features_datastores()
static void add_features_datastores (struct ast_channel * caller, struct ast_channel * callee, struct ast_bridge_config * config) static
Definition at line 423 of file features.c.
References add_features_datastore(), ast_bridge_config::features_callee, and ast_bridge_config::features_caller.
Referenced by pre_bridge_setup().
 {
    if (add_features_datastore(caller, &config->features_caller, &config->features_callee)) {
       /*
        * If we don't return here, then when we do a builtin_atxfer we
        * will copy the disconnect flags over from the atxfer to the
        * callee (Party C).
        */
       return;
    }
    add_features_datastore(callee, &config->features_callee, &config->features_caller);
 }
ast_bridge_call()
int ast_bridge_call (struct ast_channel * chan, struct ast_channel * peer, struct ast_bridge_config * config)
bridge the call and set CDR
Bridge a call, optionally allowing redirection.
Parameters
chan The bridge considers this channel the caller.
peer The bridge considers this channel the callee.
config Configuration for this bridge.
Set start time, check for two channels,check if monitor on check for feature activation, create new CDR
Return values
res on success.
-1 on failure to bridge.
Definition at line 716 of file features.c.
References ast_bridge_call_with_flags().
Referenced by app_exec(), and dial_exec_full().
 {
    return ast_bridge_call_with_flags(chan, peer, config, 0);
 }
ast_bridge_call_with_flags()
int ast_bridge_call_with_flags (struct ast_channel * chan, struct ast_channel * peer, struct ast_bridge_config * config, unsigned int flags)
Bridge a call, and add additional flags to the bridge.
This does the same thing as ast_bridge_call, except that once the bridge is created, the provided flags are set on the bridge. The provided flags are added to the bridge's flags; they will not clear any flags already set.
Parameters
chan The calling channel
peer The called channel
config Bridge configuration for the channels
flags Additional flags to set on the created bridge
Note
The function caller is assumed to have already done the COLP exchange for the initial bridging of the two channels if it was desired.
Definition at line 633 of file features.c.
References ast_bridge_basic_new(), ast_bridge_basic_set_flags(), ast_bridge_destroy(), ast_bridge_features_cleanup(), ast_bridge_features_destroy(), ast_bridge_features_init(), ast_bridge_features_new(), ast_bridge_impart(), AST_BRIDGE_IMPART_CHAN_INDEPENDENT, AST_BRIDGE_IMPART_INHIBIT_JOIN_COLP, ast_bridge_join(), AST_BRIDGE_JOIN_INHIBIT_JOIN_COLP, AST_BRIDGE_JOIN_PASS_REFERENCE, ast_channel_lock, ast_channel_name(), ast_channel_softhangup_internal_flag(), ast_channel_unlock, AST_SOFTHANGUP_ASYNCGOTO, bridge_failed_peer_goto(), ast_bridge_config::end_bridge_callback, ast_bridge_config::end_bridge_callback_data, NULL, ast_dial_features::peer_features, pre_bridge_setup(), and SCOPE_TRACE.
Referenced by ast_bridge_call(), and try_calling().
 {
    int res;
    struct ast_bridge *bridge;
    struct ast_bridge_features chan_features;
    struct ast_bridge_features *peer_features;
    SCOPE_TRACE(1, "%s Peer: %s\n", ast_channel_name(chan), ast_channel_name(peer));
    /* Setup features. */
    res = ast_bridge_features_init(&chan_features);
    peer_features = ast_bridge_features_new();
    if (res || !peer_features) {
       ast_bridge_features_destroy(peer_features);
       ast_bridge_features_cleanup(&chan_features);
       bridge_failed_peer_goto(chan, peer);
       return -1;
    }
    if (pre_bridge_setup(chan, peer, config, &chan_features, peer_features)) {
       ast_bridge_features_destroy(peer_features);
       ast_bridge_features_cleanup(&chan_features);
       bridge_failed_peer_goto(chan, peer);
       return -1;
    }
    /* Create bridge */
    bridge = ast_bridge_basic_new();
    if (!bridge) {
       ast_bridge_features_destroy(peer_features);
       ast_bridge_features_cleanup(&chan_features);
       bridge_failed_peer_goto(chan, peer);
       return -1;
    }
    ast_bridge_basic_set_flags(bridge, flags);
    /* Put peer into the bridge */
    if (ast_bridge_impart(bridge, peer, NULL, peer_features,
       AST_BRIDGE_IMPART_CHAN_INDEPENDENT | AST_BRIDGE_IMPART_INHIBIT_JOIN_COLP)) {
       ast_bridge_destroy(bridge, 0);
       ast_bridge_features_cleanup(&chan_features);
       bridge_failed_peer_goto(chan, peer);
       return -1;
    }
    /* Join bridge */
    ast_bridge_join(bridge, chan, NULL, &chan_features, NULL,
       AST_BRIDGE_JOIN_PASS_REFERENCE | AST_BRIDGE_JOIN_INHIBIT_JOIN_COLP);
    /*
     * If the bridge was broken for a hangup that isn't real, then
     * don't run the h extension, because the channel isn't really
     * hung up.  This should really only happen with
     * AST_SOFTHANGUP_ASYNCGOTO.
     */
    res = -1;
    ast_channel_lock(chan);
    if (ast_channel_softhangup_internal_flag(chan) & AST_SOFTHANGUP_ASYNCGOTO) {
       res = 0;
    }
    ast_channel_unlock(chan);
    ast_bridge_features_cleanup(&chan_features);
    if (res && config->end_bridge_callback) {
       config->end_bridge_callback(config->end_bridge_callback_data);
    }
    return res;
 }
ast_bridge_timelimit()
int ast_bridge_timelimit (struct ast_channel * chan, struct ast_bridge_config * config, char * parse, struct timeval * calldurationlimit)
parse L option and read associated channel variables to set warning, warning frequency, and timelimit
Note
caller must be aware of freeing memory for warning_sound, end_sound, and start_sound
Definition at line 886 of file features.c.
References ast_channel_lock, ast_channel_unlock, AST_FEATURE_PLAY_WARNING, ast_log, ast_set_flag, ast_strdup, ast_strdupa, ast_strlen_zero, ast_true(), ast_verb, ast_bridge_config::end_sound, ast_bridge_config::features_callee, ast_bridge_config::features_caller, LOG_WARNING, NULL, pbx_builtin_getvar_helper(), ast_bridge_config::play_warning, S_OR, ast_bridge_config::start_sound, strsep(), ast_bridge_config::timelimit, var, ast_bridge_config::warning_freq, and ast_bridge_config::warning_sound.
Referenced by bridge_exec(), and dial_exec_full().
 {
    char *stringp = ast_strdupa(parse);
    char *limit_str, *warning_str, *warnfreq_str;
    const char *var;
    int play_to_caller = 0, play_to_callee = 0;
    int delta;
    limit_str = strsep(&stringp, ":");
    warning_str = strsep(&stringp, ":");
    warnfreq_str = strsep(&stringp, ":");
    config->timelimit = atol(limit_str);
    if (warning_str)
       config->play_warning = atol(warning_str);
    if (warnfreq_str)
       config->warning_freq = atol(warnfreq_str);
    if (!config->timelimit) {
       ast_log(LOG_WARNING, "Bridge does not accept L(%s)\n", limit_str);
       config->timelimit = config->play_warning = config->warning_freq = 0;
       config->warning_sound = NULL;
       return -1; /* error */
    } else if ( (delta = config->play_warning - config->timelimit) > 0) {
       int w = config->warning_freq;
       /*
        * If the first warning is requested _after_ the entire call
        * would end, and no warning frequency is requested, then turn
        * off the warning. If a warning frequency is requested, reduce
        * the 'first warning' time by that frequency until it falls
        * within the call's total time limit.
        *
        * Graphically:
        *                timelim->|    delta        |<-playwarning
        *      0__________________|_________________|
        *                       | w  |    |    |    |
        *
        * so the number of intervals to cut is 1+(delta-1)/w
        */
       if (w == 0) {
          config->play_warning = 0;
       } else {
          config->play_warning -= w * ( 1 + (delta-1)/w );
          if (config->play_warning < 1)
             config->play_warning = config->warning_freq = 0;
       }
    }
    ast_channel_lock(chan);
    var = pbx_builtin_getvar_helper(chan, "LIMIT_PLAYAUDIO_CALLER");
    play_to_caller = var ? ast_true(var) : 1;
    var = pbx_builtin_getvar_helper(chan, "LIMIT_PLAYAUDIO_CALLEE");
    play_to_callee = var ? ast_true(var) : 0;
    if (!play_to_caller && !play_to_callee)
       play_to_caller = 1;
    var = pbx_builtin_getvar_helper(chan, "LIMIT_WARNING_FILE");
    config->warning_sound = !ast_strlen_zero(var) ? ast_strdup(var) : ast_strdup("timeleft");
    /* The code looking at config wants a NULL, not just "", to decide
     * that the message should not be played, so we replace "" with NULL.
     * Note, pbx_builtin_getvar_helper _can_ return NULL if the variable is
     * not found.
     */
    var = pbx_builtin_getvar_helper(chan, "LIMIT_TIMEOUT_FILE");
    config->end_sound = !ast_strlen_zero(var) ? ast_strdup(var) : NULL;
    var = pbx_builtin_getvar_helper(chan, "LIMIT_CONNECT_FILE");
    config->start_sound = !ast_strlen_zero(var) ? ast_strdup(var) : NULL;
    ast_channel_unlock(chan);
    /* undo effect of S(x) in case they are both used */
    calldurationlimit->tv_sec = 0;
    calldurationlimit->tv_usec = 0;
    /* more efficient to do it like S(x) does since no advanced opts */
    if (!config->play_warning && !config->start_sound && !config->end_sound && config->timelimit) {
       calldurationlimit->tv_sec = config->timelimit / 1000;
       calldurationlimit->tv_usec = (config->timelimit % 1000) * 1000;
       ast_verb(3, "Setting call duration limit to %.3lf seconds.\n",
          calldurationlimit->tv_sec + calldurationlimit->tv_usec / 1000000.0);
       play_to_caller = 0;
       play_to_callee = 0;
       config->timelimit = 0;
       config->play_warning = 0;
       config->warning_freq = 0;
    } else {
       ast_verb(4, "Limit Data for this call:\n");
       ast_verb(4, "timelimit      = %ld ms (%.3lf s)\n", config->timelimit, config->timelimit / 1000.0);
       ast_verb(4, "play_warning   = %ld ms (%.3lf s)\n", config->play_warning, config->play_warning / 1000.0);
       ast_verb(4, "play_to_caller = %s\n", play_to_caller ? "yes" : "no");
       ast_verb(4, "play_to_callee = %s\n", play_to_callee ? "yes" : "no");
       ast_verb(4, "warning_freq   = %ld ms (%.3lf s)\n", config->warning_freq, config->warning_freq / 1000.0);
       ast_verb(4, "start_sound    = %s\n", S_OR(config->start_sound, ""));
       ast_verb(4, "warning_sound  = %s\n", config->warning_sound);
       ast_verb(4, "end_sound      = %s\n", S_OR(config->end_sound, ""));
    }
    if (play_to_caller)
       ast_set_flag(&(config->features_caller), AST_FEATURE_PLAY_WARNING);
    if (play_to_callee)
       ast_set_flag(&(config->features_callee), AST_FEATURE_PLAY_WARNING);
    return 0;
 }
ast_channel_log()
void ast_channel_log (char * title, struct ast_channel * chan)
Definition at line 363 of file features.c.
References ast_channel_accountcode(), ast_channel_amaflags(), ast_channel_appl(), ast_channel_cdr(), ast_channel_context(), ast_channel_data(), ast_channel_dialcontext(), ast_channel_exten(), ast_channel_linkedid(), ast_channel_macrocontext(), ast_channel_macroexten(), ast_channel_macropriority(), ast_channel_masq(), ast_channel_masqr(), ast_channel_name(), ast_channel_priority(), ast_channel_uniqueid(), ast_log, and LOG_NOTICE.
Referenced by pre_bridge_setup(), and set_config_flags().
 {
    ast_log(LOG_NOTICE, "______ %s (%lx)______\n", title, (unsigned long) chan);
    ast_log(LOG_NOTICE, "CHAN: name: %s;  appl: %s; data: %s; contxt: %s;  exten: %s; pri: %d;\n",
       ast_channel_name(chan), ast_channel_appl(chan), ast_channel_data(chan),
       ast_channel_context(chan), ast_channel_exten(chan), ast_channel_priority(chan));
    ast_log(LOG_NOTICE, "CHAN: acctcode: %s;  dialcontext: %s; amaflags: %x; maccontxt: %s;  macexten: %s; macpri: %d;\n",
       ast_channel_accountcode(chan), ast_channel_dialcontext(chan), ast_channel_amaflags(chan),
       ast_channel_macrocontext(chan), ast_channel_macroexten(chan), ast_channel_macropriority(chan));
    ast_log(LOG_NOTICE, "CHAN: masq: %p;  masqr: %p; uniqueID: %s; linkedID:%s\n",
       ast_channel_masq(chan), ast_channel_masqr(chan),
       ast_channel_uniqueid(chan), ast_channel_linkedid(chan));
    if (ast_channel_masqr(chan)) {
       ast_log(LOG_NOTICE, "CHAN: masquerading as: %s;  cdr: %p;\n",
          ast_channel_name(ast_channel_masqr(chan)), ast_channel_cdr(ast_channel_masqr(chan)));
    }
    ast_log(LOG_NOTICE, "===== done ====\n");
 }
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 1186 of file features.c.
bridge_check_monitor()
static void bridge_check_monitor (struct ast_channel * chan, struct ast_channel * peer) static
Definition at line 486 of file features.c.
References ast_channel_lock, ast_channel_unlock, ast_strdupa, ast_strlen_zero, NULL, pbx_builtin_getvar_helper(), pbx_exec(), pbx_findapp(), and value.
Referenced by pre_bridge_setup().
 {
    const char *value;
    const char *monitor_args = NULL;
    struct ast_channel *monitor_chan = NULL;
    ast_channel_lock(chan);
    value = pbx_builtin_getvar_helper(chan, "AUTO_MONITOR");
    if (!ast_strlen_zero(value)) {
       monitor_args = ast_strdupa(value);
       monitor_chan = chan;
    }
    ast_channel_unlock(chan);
    if (!monitor_chan) {
       ast_channel_lock(peer);
       value = pbx_builtin_getvar_helper(peer, "AUTO_MONITOR");
       if (!ast_strlen_zero(value)) {
          monitor_args = ast_strdupa(value);
          monitor_chan = peer;
       }
       ast_channel_unlock(peer);
    }
    if (monitor_chan) {
       struct ast_app *monitor_app;
       monitor_app = pbx_findapp("Monitor");
       if (monitor_app) {
          pbx_exec(monitor_chan, monitor_app, monitor_args);
       }
    }
 }
bridge_config_set_limits()
static void bridge_config_set_limits (struct ast_bridge_config * config, struct ast_bridge_features_limits * caller_limits, struct ast_bridge_features_limits * callee_limits) static
Definition at line 462 of file features.c.
References AST_FEATURE_PLAY_WARNING, ast_test_flag, bridge_config_set_limits_warning_values(), ast_bridge_features_limits::duration, ast_bridge_config::features_callee, ast_bridge_config::features_caller, and ast_bridge_config::timelimit.
Referenced by pre_bridge_setup().
 {
    if (ast_test_flag(&config->features_caller, AST_FEATURE_PLAY_WARNING)) {
       bridge_config_set_limits_warning_values(config, caller_limits);
    }
    if (ast_test_flag(&config->features_callee, AST_FEATURE_PLAY_WARNING)) {
       bridge_config_set_limits_warning_values(config, callee_limits);
    }
    caller_limits->duration = config->timelimit;
    callee_limits->duration = config->timelimit;
 }
bridge_config_set_limits_warning_values()
static void bridge_config_set_limits_warning_values (struct ast_bridge_config * config, struct ast_bridge_features_limits * limits) static
Definition at line 437 of file features.c.
References ast_string_field_set, ast_bridge_config::end_sound, ast_bridge_features_limits::frequency, ast_bridge_config::play_warning, ast_bridge_config::start_sound, ast_bridge_features_limits::warning, ast_bridge_config::warning_freq, and ast_bridge_config::warning_sound.
Referenced by bridge_config_set_limits().
 {
    if (config->end_sound) {
       ast_string_field_set(limits, duration_sound, config->end_sound);
    }
    if (config->warning_sound) {
       ast_string_field_set(limits, warning_sound, config->warning_sound);
    }
    if (config->start_sound) {
       ast_string_field_set(limits, connect_sound, config->start_sound);
    }
    limits->frequency = config->warning_freq;
    limits->warning = config->play_warning;
 }
bridge_exec()
static int bridge_exec (struct ast_channel * chan, const char * data) static
Bridge channels.
Parameters
chan
data channel to bridge with.
Split data, check we aren't bridging with ourself, check valid channel, answer call if not already, check compatible channels, setup bridge config now bridge call, if transferred party hangs up return to PBX extension.
Definition at line 1007 of file features.c.
References ao2_cleanup, args, AST_APP_ARG, ast_app_parse_options(), ast_bridge_add_channel(), ast_bridge_basic_new(), ast_bridge_destroy(), ast_bridge_features_cleanup(), ast_bridge_features_destroy(), ast_bridge_features_init(), ast_bridge_features_new(), ast_bridge_join(), AST_BRIDGE_JOIN_PASS_REFERENCE, ast_bridge_set_after_go_on(), ast_bridge_timelimit(), ast_channel_cleanup, ast_channel_context(), ast_channel_exten(), ast_channel_get_by_name_prefix(), ast_channel_lock, ast_channel_name(), ast_channel_priority(), ast_channel_unlock, ast_channel_unref, AST_DECLARE_APP_ARGS, AST_FEATURE_AUTOMON, AST_FEATURE_DISCONNECT, AST_FEATURE_PARKCALL, AST_FEATURE_REDIRECT, ast_free, ast_get_chan_features_xfer_config(), ast_log, ast_set_flag, AST_STANDARD_APP_ARGS, ast_strdupa, ast_strlen_zero, ast_test_flag, ast_verb, bridge_exec_options, BRIDGE_OPT_PLAYTONE, context, done, ast_bridge_config::end_sound, ast_bridge_config::features_callee, ast_bridge_config::features_caller, LOG_WARNING, NULL, OPT_ARG_ARRAY_SIZE, OPT_ARG_CALLEE_GO_ON, OPT_ARG_DURATION_LIMIT, OPT_CALLEE_GO_ON, OPT_CALLEE_HANGUP, OPT_CALLEE_KILL, OPT_CALLEE_MONITOR, OPT_CALLEE_PARK, OPT_CALLEE_TRANSFER, OPT_CALLER_HANGUP, OPT_CALLER_MONITOR, OPT_CALLER_PARK, OPT_CALLER_TRANSFER, OPT_DURATION_LIMIT, options, pbx_builtin_setvar_helper(), ast_dial_features::peer_features, pre_bridge_setup(), priority, ast_bridge_config::start_sound, ast_bridge_config::warning_sound, and ast_features_xfer_config::xfersound.
Referenced by load_module().
 {
    struct ast_channel *current_dest_chan = NULL;
    char *tmp_data  = NULL;
    struct ast_flags opts = { 0, };
    struct ast_bridge_config bconfig = { { 0, }, };
    char *opt_args[OPT_ARG_ARRAY_SIZE];
    struct timeval calldurationlimit = { 0, };
    const char *context;
    const char *extension;
    int priority;
    int bridge_add_failed;
    int res = -1;
    struct ast_bridge_features chan_features;
    struct ast_bridge_features *peer_features;
    struct ast_bridge *bridge;
    struct ast_features_xfer_config *xfer_cfg;
    AST_DECLARE_APP_ARGS(args,
       AST_APP_ARG(dest_chan);
       AST_APP_ARG(options);
    );
    tmp_data = ast_strdupa(data ?: "");
    AST_STANDARD_APP_ARGS(args, tmp_data);
    if (!ast_strlen_zero(args.options)) {
       ast_app_parse_options(bridge_exec_options, &opts, opt_args, args.options);
    }
    /* make sure we have a valid end point */
    if (!ast_strlen_zero(args.dest_chan)) {
       current_dest_chan = ast_channel_get_by_name_prefix(args.dest_chan,
          strlen(args.dest_chan));
    }
    if (!current_dest_chan) {
       ast_verb(4, "Bridge failed because channel '%s' does not exist\n",
          args.dest_chan ?: "");
       pbx_builtin_setvar_helper(chan, "BRIDGERESULT", "NONEXISTENT");
       return 0;
    }
    /* avoid bridge with ourselves */
    if (chan == current_dest_chan) {
       ast_channel_unref(current_dest_chan);
       ast_log(LOG_WARNING, "Unable to bridge channel %s with itself\n", ast_channel_name(chan));
       pbx_builtin_setvar_helper(chan, "BRIDGERESULT", "LOOP");
       return 0;
    }
    if (ast_test_flag(&opts, OPT_DURATION_LIMIT)
       && !ast_strlen_zero(opt_args[OPT_ARG_DURATION_LIMIT])
       && ast_bridge_timelimit(chan, &bconfig, opt_args[OPT_ARG_DURATION_LIMIT], &calldurationlimit)) {
       goto done;
    }
    if (ast_test_flag(&opts, OPT_CALLEE_TRANSFER))
       ast_set_flag(&(bconfig.features_callee), AST_FEATURE_REDIRECT);
    if (ast_test_flag(&opts, OPT_CALLER_TRANSFER))
       ast_set_flag(&(bconfig.features_caller), AST_FEATURE_REDIRECT);
    if (ast_test_flag(&opts, OPT_CALLEE_HANGUP))
       ast_set_flag(&(bconfig.features_callee), AST_FEATURE_DISCONNECT);
    if (ast_test_flag(&opts, OPT_CALLER_HANGUP))
       ast_set_flag(&(bconfig.features_caller), AST_FEATURE_DISCONNECT);
    if (ast_test_flag(&opts, OPT_CALLEE_MONITOR))
       ast_set_flag(&(bconfig.features_callee), AST_FEATURE_AUTOMON);
    if (ast_test_flag(&opts, OPT_CALLER_MONITOR))
       ast_set_flag(&(bconfig.features_caller), AST_FEATURE_AUTOMON);
    if (ast_test_flag(&opts, OPT_CALLEE_PARK))
       ast_set_flag(&(bconfig.features_callee), AST_FEATURE_PARKCALL);
    if (ast_test_flag(&opts, OPT_CALLER_PARK))
       ast_set_flag(&(bconfig.features_caller), AST_FEATURE_PARKCALL);
    /* Setup after bridge goto location. */
    if (ast_test_flag(&opts, OPT_CALLEE_GO_ON)) {
       ast_channel_lock(chan);
       context = ast_strdupa(ast_channel_context(chan));
       extension = ast_strdupa(ast_channel_exten(chan));
       priority = ast_channel_priority(chan);
       ast_channel_unlock(chan);
       ast_bridge_set_after_go_on(current_dest_chan, context, extension, priority,
          opt_args[OPT_ARG_CALLEE_GO_ON]);
    } else if (!ast_test_flag(&opts, OPT_CALLEE_KILL)) {
       ast_channel_lock(current_dest_chan);
       context = ast_strdupa(ast_channel_context(current_dest_chan));
       extension = ast_strdupa(ast_channel_exten(current_dest_chan));
       priority = ast_channel_priority(current_dest_chan);
       ast_channel_unlock(current_dest_chan);
       ast_bridge_set_after_go_on(current_dest_chan, context, extension, priority, NULL);
    }
    if (ast_bridge_features_init(&chan_features)) {
       ast_bridge_features_cleanup(&chan_features);
       goto done;
    }
    peer_features = ast_bridge_features_new();
    if (!peer_features) {
       ast_bridge_features_cleanup(&chan_features);
       goto done;
    }
    if (pre_bridge_setup(chan, current_dest_chan, &bconfig, &chan_features, peer_features)) {
       ast_bridge_features_destroy(peer_features);
       ast_bridge_features_cleanup(&chan_features);
       goto done;
    }
    bridge = ast_bridge_basic_new();
    if (!bridge) {
       ast_bridge_features_destroy(peer_features);
       ast_bridge_features_cleanup(&chan_features);
       goto done;
    }
    ast_channel_lock(current_dest_chan);
    xfer_cfg = ast_get_chan_features_xfer_config(current_dest_chan);
    ast_channel_unlock(current_dest_chan);
    bridge_add_failed = ast_bridge_add_channel(bridge, current_dest_chan, peer_features,
       ast_test_flag(&opts, BRIDGE_OPT_PLAYTONE),
       xfer_cfg ? xfer_cfg->xfersound : NULL);
    ao2_cleanup(xfer_cfg);
    if (bridge_add_failed) {
       ast_bridge_features_cleanup(&chan_features);
       ast_bridge_destroy(bridge, 0);
       goto done;
    }
    /* Don't keep the channel ref in case it was not already in a bridge. */
    current_dest_chan = ast_channel_unref(current_dest_chan);
    res = ast_bridge_join(bridge, chan, NULL, &chan_features, NULL,
       AST_BRIDGE_JOIN_PASS_REFERENCE);
    ast_bridge_features_cleanup(&chan_features);
 done:
    if (res == -1) {
       pbx_builtin_setvar_helper(chan, "BRIDGERESULT", "FAILURE");
    } else {
       pbx_builtin_setvar_helper(chan, "BRIDGERESULT", "SUCCESS");
    }
    ast_free((char *) bconfig.warning_sound);
    ast_free((char *) bconfig.end_sound);
    ast_free((char *) bconfig.start_sound);
    ast_channel_cleanup(current_dest_chan);
    return 0;
 }
bridge_failed_peer_goto()
static void bridge_failed_peer_goto (struct ast_channel * chan, struct ast_channel * peer) static
Definition at line 528 of file features.c.
References ast_autoservice_chan_hangup_peer(), ast_bridge_setup_after_goto(), and ast_pbx_start().
Referenced by ast_bridge_call_with_flags().
 {
    if (ast_bridge_setup_after_goto(peer)
       || ast_pbx_start(peer)) {
       ast_autoservice_chan_hangup_peer(chan, peer);
    }
 }
dial_features_duplicate()
static void* dial_features_duplicate (void * data) static
Definition at line 262 of file features.c.
References ast_calloc, and NULL.
 {
    struct ast_dial_features *df = data, *df_copy;
    if (!(df_copy = ast_calloc(1, sizeof(*df)))) {
       return NULL;
    }
    memcpy(df_copy, df, sizeof(*df));
    return df_copy;
 }
load_module()
static int load_module (void) static
Definition at line 1168 of file features.c.
References action_bridge(), ast_manager_register_xml_core, AST_MODFLAG_GLOBAL_SYMBOLS, AST_MODFLAG_LOAD_ORDER, AST_MODPRI_CORE, AST_MODULE_INFO(), AST_MODULE_LOAD_FAILURE, AST_MODULE_LOAD_SUCCESS, AST_MODULE_SUPPORT_CORE, ast_register_application2(), ASTERISK_GPL_KEY, bridge_exec(), EVENT_FLAG_CALL, load_features_config(), NULL, reload(), reload_features_config(), and unload_module().
 {
    int res;
    res = load_features_config();
    res |= ast_register_application2(app_bridge, bridge_exec, NULL, NULL, NULL);
    res |= ast_manager_register_xml_core("Bridge", EVENT_FLAG_CALL, action_bridge);
    return res ? AST_MODULE_LOAD_FAILURE : AST_MODULE_LOAD_SUCCESS;
 }
parse_playtone()
static enum play_tone_action parse_playtone (const char * playtone_val) static
Definition at line 728 of file features.c.
References ast_false(), ast_strlen_zero, ast_true(), PLAYTONE_BOTH, PLAYTONE_CHANNEL1, PLAYTONE_CHANNEL2, and PLAYTONE_NONE.
Referenced by action_bridge().
 {
    if (ast_strlen_zero(playtone_val) || ast_false(playtone_val)) {
       return PLAYTONE_NONE;
    } if (!strcasecmp(playtone_val, "channel1")) {
       return PLAYTONE_CHANNEL1;
    } else if (!strcasecmp(playtone_val, "channel2") || ast_true(playtone_val)) {
       return PLAYTONE_CHANNEL2;
    } else if (!strcasecmp(playtone_val, "both")) {
       return PLAYTONE_BOTH;
    } else {
       /* Invalid input. Assume none */
       return PLAYTONE_NONE;
    }
 }
pre_bridge_setup()
static int pre_bridge_setup (struct ast_channel * chan, struct ast_channel * peer, struct ast_bridge_config * config, struct ast_bridge_features * chan_features, struct ast_bridge_features * peer_features) static
Definition at line 536 of file features.c.
References add_features_datastores(), ast_bridge_config::answer_topology, ast_bridge_features_ds_append(), ast_bridge_features_limits_construct(), ast_bridge_features_limits_destroy(), ast_bridge_features_set_limits(), ast_channel_lock, ast_channel_log(), ast_channel_name(), ast_channel_unlock, ast_channel_visible_indication(), AST_CONTROL_RINGING, ast_indicate(), ast_log, ast_max_forwards_reset(), ast_raw_answer_with_stream_topology(), AST_STATE_RINGING, AST_STATE_UP, bridge_check_monitor(), bridge_config_set_limits(), ast_bridge_config::features_callee, ast_bridge_config::features_caller, LOG_ERROR, pbx_builtin_getvar_helper(), SCOPE_TRACE, set_bridge_features_on_config(), set_config_flags(), and ast_bridge_config::timelimit.
Referenced by ast_bridge_call_with_flags(), and bridge_exec().
 {
    int res;
    SCOPE_TRACE(1, "%s Peer: %s\n", ast_channel_name(chan), ast_channel_name(peer));
    set_bridge_features_on_config(config, pbx_builtin_getvar_helper(chan, "BRIDGE_FEATURES"));
    add_features_datastores(chan, peer, config);
    /*
     * This is an interesting case.  One example is if a ringing
     * channel gets redirected to an extension that picks up a
     * parked call.  This will make sure that the call taken out of
     * parking gets told that the channel it just got bridged to is
     * still ringing.
     */
    if (ast_channel_state(chan) == AST_STATE_RINGING
       && ast_channel_visible_indication(peer) != AST_CONTROL_RINGING) {
       ast_indicate(peer, AST_CONTROL_RINGING);
    }
    bridge_check_monitor(chan, peer);
    set_config_flags(chan, config);
    /* Answer if need be */
    res = 0;
    if (ast_channel_state(chan) != AST_STATE_UP) {
       res = ast_raw_answer_with_stream_topology(chan, config->answer_topology);
       if (res != 0) {
          return -1;
       }
    }
 #ifdef FOR_DEBUG
    /* show the two channels and cdrs involved in the bridge for debug & devel purposes */
    ast_channel_log("Pre-bridge CHAN Channel info", chan);
    ast_channel_log("Pre-bridge PEER Channel info", peer);
 #endif
    res = 0;
    ast_channel_lock(chan);
    ast_max_forwards_reset(chan);
    res |= ast_bridge_features_ds_append(chan, &config->features_caller);
    ast_channel_unlock(chan);
    ast_channel_lock(peer);
    ast_max_forwards_reset(peer);
    res |= ast_bridge_features_ds_append(peer, &config->features_callee);
    ast_channel_unlock(peer);
    if (res) {
       return -1;
    }
    if (config->timelimit) {
       struct ast_bridge_features_limits call_duration_limits_chan;
       struct ast_bridge_features_limits call_duration_limits_peer;
       int abandon_call = 0; /* TRUE if set limits fails so we can abandon the call. */
       if (ast_bridge_features_limits_construct(&call_duration_limits_chan)) {
          ast_log(LOG_ERROR, "Could not construct caller duration limits. Bridge canceled.\n");
          return -1;
       }
       if (ast_bridge_features_limits_construct(&call_duration_limits_peer)) {
          ast_log(LOG_ERROR, "Could not construct callee duration limits. Bridge canceled.\n");
          ast_bridge_features_limits_destroy(&call_duration_limits_chan);
          return -1;
       }
       bridge_config_set_limits(config, &call_duration_limits_chan, &call_duration_limits_peer);
       if (ast_bridge_features_set_limits(chan_features, &call_duration_limits_chan, 0)) {
          abandon_call = 1;
       }
       if (ast_bridge_features_set_limits(peer_features, &call_duration_limits_peer, 0)) {
          abandon_call = 1;
       }
       /* At this point we are done with the limits structs since they have been copied to the individual feature sets. */
       ast_bridge_features_limits_destroy(&call_duration_limits_chan);
       ast_bridge_features_limits_destroy(&call_duration_limits_peer);
       if (abandon_call) {
          ast_log(LOG_ERROR, "Could not set duration limits on one or more sides of the call. Bridge canceled.\n");
          return -1;
       }
    }
    return 0;
 }
set_bridge_features_on_config()
static void set_bridge_features_on_config (struct ast_bridge_config * config, const char * features) static
Definition at line 383 of file features.c.
References AST_FEATURE_AUTOMIXMON, AST_FEATURE_AUTOMON, AST_FEATURE_DISCONNECT, AST_FEATURE_PARKCALL, AST_FEATURE_REDIRECT, ast_log, ast_set_flag, ast_strlen_zero, ast_bridge_config::features_callee, ast_bridge_config::features_caller, and LOG_WARNING.
Referenced by pre_bridge_setup().
 {
    const char *feature;
    if (ast_strlen_zero(features)) {
       return;
    }
    for (feature = features; *feature; feature++) {
       struct ast_flags *party;
       if (isupper(*feature)) {
          party = &config->features_caller;
       } else {
          party = &config->features_callee;
       }
       switch (tolower(*feature)) {
       case 't' :
          ast_set_flag(party, AST_FEATURE_REDIRECT);
          break;
       case 'k' :
          ast_set_flag(party, AST_FEATURE_PARKCALL);
          break;
       case 'h' :
          ast_set_flag(party, AST_FEATURE_DISCONNECT);
          break;
       case 'w' :
          ast_set_flag(party, AST_FEATURE_AUTOMON);
          break;
       case 'x' :
          ast_set_flag(party, AST_FEATURE_AUTOMIXMON);
          break;
       default :
          ast_log(LOG_WARNING, "Skipping unknown feature code '%c'\n", *feature);
          break;
       }
    }
 }
set_config_flags()
static void set_config_flags (struct ast_channel * chan, struct ast_bridge_config * config) static
Definition at line 334 of file features.c.
References ao2_cleanup, AST_BRIDGE_DTMF_CHANNEL_0, AST_BRIDGE_DTMF_CHANNEL_1, ast_channel_lock, ast_channel_log(), ast_channel_unlock, ast_clear_flag, AST_FEATURE_DTMF_MASK, AST_FLAGS_ALL, ast_get_chan_applicationmap(), ast_set_flag, ast_test_flag, ast_bridge_config::features_callee, ast_bridge_config::features_caller, NULL, and RAII_VAR.
Referenced by pre_bridge_setup().
 {
    ast_clear_flag(config, AST_FLAGS_ALL);
    if (ast_test_flag(&config->features_caller, AST_FEATURE_DTMF_MASK)) {
       ast_set_flag(config, AST_BRIDGE_DTMF_CHANNEL_0);
    }
    if (ast_test_flag(&config->features_callee, AST_FEATURE_DTMF_MASK)) {
       ast_set_flag(config, AST_BRIDGE_DTMF_CHANNEL_1);
    }
    if (!(ast_test_flag(config, AST_BRIDGE_DTMF_CHANNEL_0) && ast_test_flag(config, AST_BRIDGE_DTMF_CHANNEL_1))) {
       RAII_VAR(struct ao2_container *, applicationmap, NULL, ao2_cleanup);
       ast_channel_lock(chan);
       applicationmap = ast_get_chan_applicationmap(chan);
       ast_channel_unlock(chan);
       if (!applicationmap) {
          return;
       }
       /* If an applicationmap exists for this channel at all, then the channel needs the DTMF flag set */
       ast_set_flag(config, AST_BRIDGE_DTMF_CHANNEL_0);
    }
 }
unload_module()
static int unload_module (void) static
Definition at line 1157 of file features.c.
References ast_manager_unregister(), ast_unregister_application(), and unload_features_config().
Referenced by load_module().
 {
    unload_features_config();
    ast_manager_unregister("Bridge");
    ast_unregister_application(app_bridge);
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_GLOBAL_SYMBOLS | AST_MODFLAG_LOAD_ORDER , .description = "Call Features" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .reload = reload_features_config, .load_pri = AST_MODPRI_CORE, .requires = "extconfig", } static
Definition at line 1186 of file features.c.
app_bridge
char* app_bridge = "Bridge" static
Definition at line 844 of file features.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 1186 of file features.c.
bridge_exec_options
const struct ast_app_option bridge_exec_options[128] = { [ 'p' ] = { .flag = BRIDGE_OPT_PLAYTONE }, [ 'F' ] = { .flag = OPT_CALLEE_GO_ON , .arg_index = OPT_ARG_CALLEE_GO_ON + 1 }, [ 'h' ] = { .flag = OPT_CALLEE_HANGUP }, [ 'H' ] = { .flag = OPT_CALLER_HANGUP }, [ 'k' ] = { .flag = OPT_CALLEE_PARK }, [ 'K' ] = { .flag = OPT_CALLER_PARK }, [ 'L' ] = { .flag = OPT_DURATION_LIMIT , .arg_index = OPT_ARG_DURATION_LIMIT + 1 }, [ 'S' ] = { .flag = OPT_DURATION_STOP , .arg_index = OPT_ARG_DURATION_STOP + 1 }, [ 't' ] = { .flag = OPT_CALLEE_TRANSFER }, [ 'T' ] = { .flag = OPT_CALLER_TRANSFER }, [ 'w' ] = { .flag = OPT_CALLEE_MONITOR }, [ 'W' ] = { .flag = OPT_CALLER_MONITOR }, [ 'x' ] = { .flag = OPT_CALLEE_KILL }, } static
Definition at line 884 of file features.c.
Referenced by bridge_exec().
dial_features_info
const struct ast_datastore_info dial_features_info static
Initial value:
= {
   .type = "dial-features",
   .destroy = ast_free_ptr,
   .duplicate = dial_features_duplicate,
}
Definition at line 275 of file features.c.