Asterisk - The Open Source Telephony Project: threadstorage.c File Reference
threadstorage.c File Reference
Debugging support for thread-local-storage objects.
#include "asterisk.h"
#include "asterisk/_private.h"
Functions
void threadstorage_init (void)
Detailed Description
Debugging support for thread-local-storage objects.
Author
Kevin P. Fleming kpfle.nosp@m.ming.nosp@m.@digi.nosp@m.um.c.nosp@m.om
Definition in file threadstorage.c.
Function Documentation
threadstorage_init()
void threadstorage_init (void)
Provided by threadstorage.c
Definition at line 35 of file threadstorage.c.
References a, ast_cli_args::argc, ast_cli_args::argv, ARRAY_LEN, ast_alloca, ast_calloc, ast_cli(), AST_CLI_DEFINE, ast_cli_register_multiple, ast_cli_unregister_multiple(), ast_free, AST_LIST_ENTRY, AST_LIST_HEAD_NOLOCK_STATIC, AST_LIST_INSERT_TAIL, AST_LIST_REMOVE_CURRENT, AST_LIST_TRAVERSE, AST_LIST_TRAVERSE_SAFE_BEGIN, AST_LIST_TRAVERSE_SAFE_END, ast_register_cleanup(), CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::command, ast_cli_args::fd, make_ari_stubs::file, len(), name, NULL, pthread_mutex_init, pthread_mutex_lock, pthread_mutex_t, pthread_mutex_unlock, thread, and ast_cli_entry::usage.
Referenced by asterisk_daemon().
 {
 }