Asterisk - The Open Source Telephony Project: manager_system.c File Reference
manager_system.c File Reference
System AMI event handling.
#include "asterisk.h"
#include "asterisk/stasis.h"
#include "asterisk/stasis_message_router.h"
#include "asterisk/stasis_system.h"
Functions
int manager_system_init (void)
Initialize support for AMI system events.
static void manager_system_shutdown (void)
Variables
static struct stasis_forward * topic_forwarder
The Stasis Message Bus API subscription returned by the forwarding of the system topic to the manager topic.
Detailed Description
System AMI event handling.
Author
Jason Parker jpark.nosp@m.er@d.nosp@m.igium.nosp@m..com
Definition in file manager_system.c.
Function Documentation
manager_system_init()
int manager_system_init (void)
Initialize support for AMI system events.
Since
12
Return values
0 on success
non-zero on error
Definition at line 43 of file manager_system.c.
References ast_manager_get_message_router(), ast_manager_get_topic(), ast_register_cleanup(), ast_system_topic(), manager_system_shutdown(), manager_topic, stasis_forward_all(), and system_topic.
Referenced by subscribe_all().
 {
    struct stasis_topic *manager_topic;
    struct stasis_topic *system_topic;
    struct stasis_message_router *message_router;
    manager_topic = ast_manager_get_topic();
    if (!manager_topic) {
       return -1;
    }
    message_router = ast_manager_get_message_router();
    if (!message_router) {
       return -1;
    }
    system_topic = ast_system_topic();
    if (!system_topic) {
       return -1;
    }
    topic_forwarder = stasis_forward_all(system_topic, manager_topic);
    if (!topic_forwarder) {
       return -1;
    }
    ast_register_cleanup(manager_system_shutdown);
    return 0;
 }
manager_system_shutdown()
static void manager_system_shutdown (void) static
Definition at line 37 of file manager_system.c.
References NULL, and stasis_forward_cancel().
Referenced by manager_system_init().
 {
    stasis_forward_cancel(topic_forwarder);
    topic_forwarder = NULL;
 }
Variable Documentation
topic_forwarder
struct stasis_forward* topic_forwarder static
The Stasis Message Bus API subscription returned by the forwarding of the system topic to the manager topic.
Definition at line 35 of file manager_system.c.