Asterisk - The Open Source Telephony Project: app_stasis.c File Reference
app_stasis.c File Reference
Stasis dialplan application.
#include "asterisk.h"
#include "asterisk/app.h"
#include "asterisk/module.h"
#include "asterisk/pbx.h"
#include "asterisk/stasis.h"
#include "asterisk/stasis_app_impl.h"
Macros
#define MAX_ARGS 128
Maximum number of arguments for the Stasis dialplan application.
Functions
static void __reg_module (void)
static void __unreg_module (void)
static int app_exec (struct ast_channel *chan, const char *data)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int load_module (void)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_DEFAULT , .description = "Stasis dialplan application" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .requires = "res_stasis", }
static const struct ast_module_info * ast_module_info = &__mod_info
static const char * stasis = "Stasis"
Dialplan application name.
Detailed Description
Stasis dialplan application.
Author
David M. Lee, II dlee@.nosp@m.digi.nosp@m.um.co.nosp@m.m
Definition in file app_stasis.c.
Macro Definition Documentation
MAX_ARGS
#define MAX_ARGS 128
Maximum number of arguments for the Stasis dialplan application.
Definition at line 77 of file app_stasis.c.
Referenced by app_exec().
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 141 of file app_stasis.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 141 of file app_stasis.c.
app_exec()
static int app_exec (struct ast_channel * chan, const char * data) static
/brief Stasis dialplan application callback
Definition at line 83 of file app_stasis.c.
References app_name(), args, AST_APP_ARG, ast_assert, ast_check_hangup(), AST_DECLARE_APP_ARGS, ast_log, AST_STANDARD_APP_ARGS, ast_strdupa, LOG_WARNING, MAX_ARGS, NULL, parse(), pbx_builtin_setvar_helper(), and stasis_app_exec().
Referenced by load_module().
 {
    char *parse = NULL;
    int ret = -1;
    AST_DECLARE_APP_ARGS(args,
       AST_APP_ARG(app_name);
       AST_APP_ARG(app_argv)[MAX_ARGS];
    );
    ast_assert(chan != NULL);
    ast_assert(data != NULL);
    pbx_builtin_setvar_helper(chan, "STASISSTATUS", "");
    /* parse the arguments */
    parse = ast_strdupa(data);
    AST_STANDARD_APP_ARGS(args, parse);
    if (args.argc < 1) {
       ast_log(LOG_WARNING, "Stasis app_name argument missing\n");
    } else {
       ret = stasis_app_exec(chan,
                             args.app_name,
                             args.argc - 1,
                             args.app_argv);
    }
    if (ret) {
       /* set ret to 0 so pbx_core doesnt hangup the channel */
       if (!ast_check_hangup(chan)) {
          ret = 0;
       } else {
          ret = -1;
       }
       pbx_builtin_setvar_helper(chan, "STASISSTATUS", "FAILED");
    } else {
       pbx_builtin_setvar_helper(chan, "STASISSTATUS", "SUCCESS");
    }
    return ret;
 }
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 141 of file app_stasis.c.
load_module()
static int load_module (void) static
Definition at line 126 of file app_stasis.c.
References app_exec(), ast_register_application_xml, and stasis.
Referenced by unload_module().
 {
    return ast_register_application_xml(stasis, app_exec);
 }
unload_module()
static int unload_module (void) static
Definition at line 131 of file app_stasis.c.
References AST_MODFLAG_DEFAULT, AST_MODULE_INFO(), AST_MODULE_SUPPORT_CORE, ast_unregister_application(), ASTERISK_GPL_KEY, load_module(), and stasis.
 {
    return ast_unregister_application(stasis);
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_DEFAULT , .description = "Stasis dialplan application" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .requires = "res_stasis", } static
Definition at line 141 of file app_stasis.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 141 of file app_stasis.c.
stasis
const char* stasis = "Stasis" static
Dialplan application name.
Definition at line 80 of file app_stasis.c.
Referenced by ast_bridge_publish_blind_transfer(), load_module(), snoop_stasis_thread(), and unload_module().