Asterisk - The Open Source Telephony Project: test_stasis_channels.c File Reference
test_stasis_channels.c File Reference
Test Stasis Channel messages and objects.
#include "asterisk.h"
#include "asterisk/astobj2.h"
#include "asterisk/module.h"
#include "asterisk/stasis.h"
#include "asterisk/stasis_message_router.h"
#include "asterisk/test.h"
#include "asterisk/stasis_channels.h"
#include "asterisk/channel.h"
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
AST_TEST_DEFINE (channel_blob_create)
AST_TEST_DEFINE (null_blob)
AST_TEST_DEFINE (multi_channel_blob_create)
AST_TEST_DEFINE (multi_channel_blob_snapshots)
AST_TEST_DEFINE (channel_snapshot_json)
static int load_module (void)
static void safe_channel_release (struct ast_channel *chan)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = 0 , .description = "Stasis Channel Testing" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module }
static const struct ast_module_info * ast_module_info = &__mod_info
static const char * test_category = "/stasis/channels/"
Detailed Description
Test Stasis Channel messages and objects.
Author
Matt Jordan <mjordan@digium.com>
Definition in file test_stasis_channels.c.
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 335 of file test_stasis_channels.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 335 of file test_stasis_channels.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 335 of file test_stasis_channels.c.
AST_TEST_DEFINE() [1/5]
AST_TEST_DEFINE (channel_blob_create)
Definition at line 53 of file test_stasis_channels.c.
References ao2_cleanup, ao2_ref, ast_channel_alloc, ast_channel_blob_create(), ast_channel_lock, ast_channel_unlock, ast_json_pack(), ast_json_unref(), AST_STATE_DOWN, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_channel_blob::blob, sip_to_pjsip::info(), NULL, RAII_VAR, safe_channel_release(), ast_channel_blob::snapshot, stasis_message_data(), stasis_message_type(), stasis_message_type_create(), STASIS_MESSAGE_TYPE_SUCCESS, test_category, TEST_EXECUTE, TEST_INIT, and type.
 {
    struct ast_channel_blob *blob;
    RAII_VAR(struct stasis_message_type *, type, NULL, ao2_cleanup);
    RAII_VAR(struct stasis_message *, msg, NULL, ao2_cleanup);
    RAII_VAR(struct ast_channel *, chan, NULL, safe_channel_release);
    RAII_VAR(struct ast_json *, json, NULL, ast_json_unref);
    RAII_VAR(struct ast_json *, bad_json, NULL, ast_json_unref);
    switch (cmd) {
    case TEST_INIT:
       info->name = __func__;
       info->category = test_category;
       info->summary = "Test creation of ast_channel_blob objects";
       info->description = "Test creation of ast_channel_blob objects";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    ast_test_validate(test, stasis_message_type_create("test-type", NULL, &type) == STASIS_MESSAGE_TYPE_SUCCESS);
    chan = ast_channel_alloc(0, AST_STATE_DOWN, "100", "Alice", "100", "100", "default", NULL, NULL, 0, "TEST/Alice");
    ast_channel_unlock(chan);
    json = ast_json_pack("{s: s}",
            "foo", "bar");
    /* Off nominal creation */
    ast_channel_lock(chan);
    ast_test_validate(test, NULL == ast_channel_blob_create(chan, NULL, json));
    /* Test for single channel */
    msg = ast_channel_blob_create(chan, type, json);
    ast_channel_unlock(chan);
    ast_test_validate(test, NULL != msg);
    blob = stasis_message_data(msg);
    ast_test_validate(test, NULL != blob);
    ast_test_validate(test, NULL != blob->snapshot);
    ast_test_validate(test, NULL != blob->blob);
    ast_test_validate(test, type == stasis_message_type(msg));
    ast_test_validate(test, 1 == ao2_ref(msg, 0));
    ao2_cleanup(msg);
    /* Test for global channels */
    msg = ast_channel_blob_create(NULL, type, json);
    ast_test_validate(test, NULL != msg);
    blob = stasis_message_data(msg);
    ast_test_validate(test, NULL != blob);
    ast_test_validate(test, NULL == blob->snapshot);
    ast_test_validate(test, NULL != blob->blob);
    ast_test_validate(test, type == stasis_message_type(msg));
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [2/5]
AST_TEST_DEFINE (null_blob)
Definition at line 108 of file test_stasis_channels.c.
References ao2_cleanup, ast_channel_alloc, ast_channel_blob_create(), ast_channel_lock, ast_channel_unlock, ast_json_null(), ast_json_pack(), ast_json_unref(), AST_STATE_DOWN, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_channel_blob::blob, sip_to_pjsip::info(), NULL, RAII_VAR, safe_channel_release(), ast_channel_blob::snapshot, stasis_message_data(), stasis_message_type(), stasis_message_type_create(), STASIS_MESSAGE_TYPE_SUCCESS, test_category, TEST_EXECUTE, TEST_INIT, and type.
 {
    struct ast_channel_blob *blob;
    RAII_VAR(struct stasis_message_type *, type, NULL, ao2_cleanup);
    RAII_VAR(struct stasis_message *, msg, NULL, ao2_cleanup);
    RAII_VAR(struct ast_channel *, chan, NULL, safe_channel_release);
    RAII_VAR(struct ast_json *, json, NULL, ast_json_unref);
    RAII_VAR(struct ast_json *, bad_json, NULL, ast_json_unref);
    switch (cmd) {
    case TEST_INIT:
       info->name = __func__;
       info->category = test_category;
       info->summary = "Test creation of ast_channel_blob objects";
       info->description = "Test creation of ast_channel_blob objects";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    ast_test_validate(test, stasis_message_type_create("test-type", NULL, &type) == STASIS_MESSAGE_TYPE_SUCCESS);
    chan = ast_channel_alloc(0, AST_STATE_DOWN, "100", "Alice", "100", "100", "default", NULL, NULL, 0, "TEST/Alice");
    ast_channel_unlock(chan);
    json = ast_json_pack("{s: s}",
            "foo", "bar");
    /* Test for single channel */
    ast_channel_lock(chan);
    msg = ast_channel_blob_create(chan, type, NULL);
    ast_channel_unlock(chan);
    ast_test_validate(test, NULL != msg);
    blob = stasis_message_data(msg);
    ast_test_validate(test, NULL != blob);
    ast_test_validate(test, NULL != blob->snapshot);
    ast_test_validate(test, ast_json_null() == blob->blob);
    ast_test_validate(test, type == stasis_message_type(msg));
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [3/5]
AST_TEST_DEFINE (multi_channel_blob_create)
Definition at line 148 of file test_stasis_channels.c.
References ao2_cleanup, ast_json_pack(), ast_json_unref(), ast_multi_channel_blob_create(), ast_multi_channel_blob_get_json(), AST_TEST_NOT_RUN, AST_TEST_PASS, ast_channel_blob::blob, sip_to_pjsip::info(), NULL, RAII_VAR, test_category, TEST_EXECUTE, and TEST_INIT.
 {
    RAII_VAR(struct ast_multi_channel_blob *, blob, NULL, ao2_cleanup);
    RAII_VAR(struct ast_json *, json, NULL, ast_json_unref);
    RAII_VAR(struct ast_json *, bad_json, NULL, ast_json_unref);
    switch (cmd) {
    case TEST_INIT:
       info->name = __func__;
       info->category = test_category;
       info->summary = "Test creation of ast_multi_channel_blob objects";
       info->description = "Test creation of ast_multi_channel_blob objects";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    json = ast_json_pack("{s: s}",
            "foo", "bar");
    /* Test for single channel */
    blob = ast_multi_channel_blob_create(json);
    ast_test_validate(test, NULL != blob);
    ast_test_validate(test, NULL != ast_multi_channel_blob_get_json(blob));
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [4/5]
AST_TEST_DEFINE (multi_channel_blob_snapshots)
Definition at line 176 of file test_stasis_channels.c.
References ao2_cleanup, ao2_container_count(), ao2_find, ao2_ref, ast_channel_alloc, ast_channel_lock, ast_channel_snapshot_create(), ast_channel_unlock, ast_json_pack(), ast_json_unref(), ast_multi_channel_blob_add_channel(), ast_multi_channel_blob_create(), ast_multi_channel_blob_get_channel(), ast_multi_channel_blob_get_channels(), AST_STATE_DOWN, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_channel_snapshot::base, ast_channel_blob::blob, sip_to_pjsip::info(), ast_channel_snapshot_base::name, NULL, OBJ_KEY, RAII_VAR, safe_channel_release(), test_category, TEST_EXECUTE, and TEST_INIT.
 {
    RAII_VAR(struct ast_multi_channel_blob *, blob, NULL, ao2_cleanup);
    RAII_VAR(struct ast_json *, json, NULL, ast_json_unref);
    RAII_VAR(struct ast_channel *, chan_alice, NULL, safe_channel_release);
    RAII_VAR(struct ast_channel *, chan_bob, NULL, safe_channel_release);
    RAII_VAR(struct ast_channel *, chan_charlie, NULL, safe_channel_release);
    struct ast_channel_snapshot *snapshot;
    struct ao2_container *matches;
    switch (cmd) {
    case TEST_INIT:
       info->name = __func__;
       info->category = test_category;
       info->summary = "Test creation of ast_multi_channel_blob objects";
       info->description = "Test creation of ast_multi_channel_blob objects";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    json = ast_json_pack("{s: s}",
            "type", "test");
    chan_alice = ast_channel_alloc(0, AST_STATE_DOWN, "100", "Alice", "100", "100", "default", NULL, NULL, 0, "TEST/Alice");
    ast_channel_unlock(chan_alice);
    chan_bob = ast_channel_alloc(0, AST_STATE_DOWN, "200", "Bob", "200", "200", "default", NULL, NULL, 0, "TEST/Bob");
    ast_channel_unlock(chan_bob);
    chan_charlie = ast_channel_alloc(0, AST_STATE_DOWN, "300", "Bob", "300", "300", "default", NULL, NULL, 0, "TEST/Charlie");
    ast_channel_unlock(chan_charlie);
    blob = ast_multi_channel_blob_create(json);
    ast_channel_lock(chan_alice);
    ast_multi_channel_blob_add_channel(blob, "Caller", ast_channel_snapshot_create(chan_alice));
    ast_channel_unlock(chan_alice);
    ast_channel_lock(chan_bob);
    ast_multi_channel_blob_add_channel(blob, "Peer", ast_channel_snapshot_create(chan_bob));
    ast_channel_unlock(chan_bob);
    ast_channel_lock(chan_charlie);
    ast_multi_channel_blob_add_channel(blob, "Peer", ast_channel_snapshot_create(chan_charlie));
    ast_channel_unlock(chan_charlie);
    /* Test for unknown role */
    ast_test_validate(test, NULL == ast_multi_channel_blob_get_channel(blob, "Foobar"));
    /* Test for single match */
    snapshot = ast_multi_channel_blob_get_channel(blob, "Caller");
    ast_test_validate(test, NULL != snapshot);
    ast_test_validate(test, 0 == strcmp("TEST/Alice", snapshot->base->name));
    /* Test for single match, multiple possibilities */
    snapshot = ast_multi_channel_blob_get_channel(blob, "Peer");
    ast_test_validate(test, NULL != snapshot);
    ast_test_validate(test, 0 != strcmp("TEST/Alice", snapshot->base->name));
    /* Multi-match */
    matches = ast_multi_channel_blob_get_channels(blob, "Peer");
    ast_test_validate(test, NULL != matches);
    ast_test_validate(test, 2 == ao2_container_count(matches));
    snapshot = ao2_find(matches, "TEST/Bob", OBJ_KEY);
    ast_test_validate(test, NULL != snapshot);
    ao2_cleanup(snapshot);
    snapshot = ao2_find(matches, "TEST/Charlie", OBJ_KEY);
    ast_test_validate(test, NULL != snapshot);
    ao2_cleanup(snapshot);
    ast_test_validate(test, 1 == ao2_ref(matches, 0));
    ao2_cleanup(matches);
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [5/5]
AST_TEST_DEFINE (channel_snapshot_json)
Definition at line 246 of file test_stasis_channels.c.
References ao2_cleanup, ast_channel_alloc, ast_channel_creationtime(), ast_channel_lock, ast_channel_snapshot_create(), ast_channel_snapshot_to_json(), ast_channel_uniqueid(), ast_channel_unlock, ast_json_equal(), ast_json_pack(), ast_json_timeval(), ast_json_unref(), AST_STATE_DOWN, AST_TEST_NOT_RUN, AST_TEST_PASS, sip_to_pjsip::info(), NULL, RAII_VAR, safe_channel_release(), test_category, TEST_EXECUTE, and TEST_INIT.
 {
    RAII_VAR(struct stasis_message *, msg, NULL, ao2_cleanup);
    RAII_VAR(struct ast_channel *, chan, NULL, safe_channel_release);
    RAII_VAR(struct ast_channel_snapshot *, snapshot, NULL, ao2_cleanup);
    RAII_VAR(struct ast_json *, expected, NULL, ast_json_unref);
    RAII_VAR(struct ast_json *, actual, NULL, ast_json_unref);
    switch (cmd) {
    case TEST_INIT:
       info->name = __func__;
       info->category = test_category;
       info->summary = "Test creation of ast_channel_blob objects";
       info->description = "Test creation of ast_channel_blob objects";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    ast_test_validate(test, NULL == ast_channel_snapshot_to_json(NULL, NULL));
    chan = ast_channel_alloc(0, AST_STATE_DOWN, "cid_num", "cid_name", "acctcode", "exten", "context", NULL, NULL, 0, "TEST/name");
    ast_channel_unlock(chan);
    ast_test_validate(test, NULL != chan);
    ast_channel_lock(chan);
    snapshot = ast_channel_snapshot_create(chan);
    ast_channel_unlock(chan);
    ast_test_validate(test, NULL != snapshot);
    actual = ast_channel_snapshot_to_json(snapshot, NULL);
    expected = ast_json_pack("{ s: s, s: s, s: s, s: s,"
              "  s: { s: s, s: s, s: i, s: s, s: s },"
              "  s: { s: s, s: s },"
              "  s: { s: s, s: s },"
              "  s: s"
              "  s: o"
              "}",
              "name", "TEST/name",
              "state", "Down",
              "accountcode", "acctcode",
              "id", ast_channel_uniqueid(chan),
              "dialplan",
              "context", "context",
              "exten", "exten",
              "priority", 1,
              "app_name", "",
              "app_data", "",
              "caller",
              "name", "cid_name",
              "number", "cid_num",
              "connected",
              "name", "",
              "number", "",
              "language", "en",
              "creationtime",
              ast_json_timeval(
                 ast_channel_creationtime(chan), NULL));
    ast_test_validate(test, ast_json_equal(expected, actual));
    return AST_TEST_PASS;
 }
load_module()
static int load_module (void) static
Definition at line 320 of file test_stasis_channels.c.
References AST_MODULE_INFO(), AST_MODULE_LOAD_SUCCESS, AST_MODULE_SUPPORT_CORE, AST_TEST_REGISTER, ASTERISK_GPL_KEY, and unload_module().
 {
    AST_TEST_REGISTER(channel_blob_create);
    AST_TEST_REGISTER(null_blob);
    AST_TEST_REGISTER(multi_channel_blob_create);
    AST_TEST_REGISTER(multi_channel_blob_snapshots);
    AST_TEST_REGISTER(channel_snapshot_json);
    return AST_MODULE_LOAD_SUCCESS;
 }
safe_channel_release()
static void safe_channel_release (struct ast_channel * chan) static
Definition at line 45 of file test_stasis_channels.c.
References ast_channel_release().
Referenced by AST_TEST_DEFINE().
 {
    if (!chan) {
       return;
    }
    ast_channel_release(chan);
 }
unload_module()
static int unload_module (void) static
Definition at line 309 of file test_stasis_channels.c.
References AST_TEST_UNREGISTER.
Referenced by load_module().
 {
    AST_TEST_UNREGISTER(channel_blob_create);
    AST_TEST_UNREGISTER(null_blob);
    AST_TEST_UNREGISTER(multi_channel_blob_create);
    AST_TEST_UNREGISTER(multi_channel_blob_snapshots);
    AST_TEST_UNREGISTER(channel_snapshot_json);
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = 0 , .description = "Stasis Channel Testing" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module } static
Definition at line 335 of file test_stasis_channels.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 335 of file test_stasis_channels.c.
test_category
const char* test_category = "/stasis/channels/" static
Definition at line 43 of file test_stasis_channels.c.
Referenced by AST_TEST_DEFINE().