Asterisk - The Open Source Telephony Project: test_locale.c File Reference
test_locale.c File Reference
Locale Test.
#include "asterisk.h"
#include <sys/types.h>
#include <dirent.h>
#include <locale.h>
#include "asterisk/cli.h"
#include "asterisk/linkedlists.h"
#include "asterisk/localtime.h"
#include "asterisk/utils.h"
#include "asterisk/module.h"
Macros
#define __USE_GNU 1
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static char * handle_cli_test_locales (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static int load_module (void)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Locale tests" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, }
static const struct ast_module_info * ast_module_info = &__mod_info
static struct ast_cli_entry cli_locales []
Detailed Description
Locale Test.
Author
Tilghman Lesher <tlesher AT digium DOT com>
Definition in file test_locale.c.
Macro Definition Documentation
__USE_GNU
#define __USE_GNU 1
Definition at line 38 of file test_locale.c.
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 186 of file test_locale.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 186 of file test_locale.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 186 of file test_locale.c.
handle_cli_test_locales()
static char* handle_cli_test_locales (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) static
Definition at line 49 of file test_locale.c.
References __APPLE__, ast_cli_args::argc, ast_cli_entry::args, ast_calloc, ast_cli(), ast_copy_string(), ast_free, AST_LIST_ENTRY, AST_LIST_FIRST, AST_LIST_HEAD_NOLOCK(), AST_LIST_HEAD_SET_NOLOCK, AST_LIST_INSERT_TAIL, AST_LIST_REMOVE_HEAD, ast_localtime(), ast_setlocale(), ast_strftime(), ast_tvnow(), CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::command, ast_cli_args::fd, name, NULL, and ast_cli_entry::usage.
 {
    DIR *localedir;
    struct dirent *dent;
    struct ast_tm atm;
    struct timeval tv;
    const char *orig_locale;
    char origlocalformat[200] = "", localformat[200] = "";
    struct test_locales {
       AST_LIST_ENTRY(test_locales) list;
       char *localformat;
       char name[0];
    } *tl = NULL;
    AST_LIST_HEAD_NOLOCK(locales, test_locales) locales;
    int varies = 0, all_successful = 1, count = 0, count_fail = 0;
    switch (cmd) {
    case CLI_INIT:
       e->command = "test locale";
       e->usage = ""
          "Usage: test locale\n"
          "   Test thread safety of locale functions.\n";
       return NULL;
    case CLI_GENERATE:
       return NULL;
    }
    if (a->argc != e->args) {
       return CLI_SHOWUSAGE;
    }
    /* First we run a set of tests with the global locale, which isn't thread-safe. */
    if (!(localedir = opendir(
 #if defined(__FreeBSD__) || defined(__OpenBSD__) || defined( __NetBSD__ ) || defined(__APPLE__)
       "/usr/share/locale"
 #else /* Linux */
       "/usr/lib/locale"
 #endif
       ))) {
       ast_cli(a->fd, "No locales seem to exist on this platform.\n");
       return CLI_SUCCESS;
    }
    tv = ast_tvnow();
    ast_localtime(&tv, &atm, NULL);
    orig_locale = setlocale(LC_ALL, NULL);
    AST_LIST_HEAD_SET_NOLOCK(&locales, NULL);
    /* Get something different, to compare against. */
    ast_strftime(origlocalformat, sizeof(origlocalformat), "%c", &atm);
    while ((dent = readdir(localedir))) {
       size_t locallen;
       size_t namelen;
       if (dent->d_name[0] == '.') {
          continue;
       }
       setlocale(LC_ALL, dent->d_name);
       ast_strftime(localformat, sizeof(localformat), "%c", &atm);
       locallen = strlen(localformat) + 1;
       namelen = strlen(dent->d_name) + 1;
       /* Store values */
       if (!(tl = ast_calloc(1, sizeof(*tl) + locallen + namelen))) {
          continue;
       }
       ast_copy_string(tl->name, dent->d_name, namelen); /* SAFE */
       tl->localformat = tl->name + namelen;
       ast_copy_string(tl->localformat, localformat, locallen); /* SAFE */
       AST_LIST_INSERT_TAIL(&locales, tl, list);
       /* Ensure that at least two entries differ, otherwise this test doesn't mean much. */
       if (!varies && strcmp(AST_LIST_FIRST(&locales)->localformat, localformat)) {
          varies = 1;
       }
    }
    setlocale(LC_ALL, orig_locale);
    closedir(localedir);
    if (!varies) {
       if (!strcmp(origlocalformat, localformat)) {
          ast_cli(a->fd, "WARNING: the locales on your system don't differ.  Install more locales if you want this test to mean something.\n");
       }
    }
    orig_locale = ast_setlocale(AST_LIST_FIRST(&locales)->name);
    while ((tl = AST_LIST_REMOVE_HEAD(&locales, list))) {
       ast_setlocale(tl->name);
       ast_strftime(localformat, sizeof(localformat), "%c", &atm);
       if (strcmp(localformat, tl->localformat)) {
          ast_cli(a->fd, "WARNING: locale test fails for locale %s\n", tl->name);
          all_successful = 0;
          count_fail++;
       }
       ast_free(tl);
       count++;
    }
    ast_setlocale(orig_locale);
    if (all_successful) {
       ast_cli(a->fd, "All %d locale tests successful\n", count);
    } else if (count_fail == count && count > 0) {
       ast_cli(a->fd, "No locale tests successful out of %d tries\n", count);
    } else if (count > 0) {
       ast_cli(a->fd, "Partial failure (%d/%d) for a %.0f%% failure rate\n", count_fail, count, count_fail * 100.0 / count);
    } else {
       ast_cli(a->fd, "No locales tested.  Install more locales.\n");
    }
    return CLI_SUCCESS;
 }
load_module()
static int load_module (void) static
Definition at line 180 of file test_locale.c.
References ARRAY_LEN, ast_cli_register_multiple, and AST_MODULE_LOAD_SUCCESS.
 {
    ast_cli_register_multiple(cli_locales, ARRAY_LEN(cli_locales));
    return AST_MODULE_LOAD_SUCCESS;
 }
unload_module()
static int unload_module (void) static
Definition at line 174 of file test_locale.c.
References ARRAY_LEN, and ast_cli_unregister_multiple().
 {
    ast_cli_unregister_multiple(cli_locales, ARRAY_LEN(cli_locales));
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Locale tests" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, } static
Definition at line 186 of file test_locale.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 186 of file test_locale.c.
cli_locales
struct ast_cli_entry cli_locales[] static
Initial value:
= {
   { .handler =  handle_cli_test_locales , .summary =  "Test locales for thread-safety" ,},
}
Definition at line 170 of file test_locale.c.