Asterisk - The Open Source Telephony Project: res_timing_timerfd.c File Reference
res_timing_timerfd.c File Reference
timerfd timing interface
#include "asterisk.h"
#include <sys/timerfd.h>
#include "asterisk/module.h"
#include "asterisk/astobj2.h"
#include "asterisk/timing.h"
#include "asterisk/logger.h"
#include "asterisk/utils.h"
#include "asterisk/time.h"
Data Structures
struct timerfd_timer
Macros
#define TIMERFD_MAX_RATE 1000
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int load_module (void)
static void timer_destroy (void *obj)
static int timerfd_timer_ack (void *data, unsigned int quantity)
static void timerfd_timer_close (void *data)
static int timerfd_timer_disable_continuous (void *data)
static int timerfd_timer_enable_continuous (void *data)
static int timerfd_timer_fd (void *data)
static enum ast_timer_event timerfd_timer_get_event (void *data)
static unsigned int timerfd_timer_get_max_rate (void *data)
static void * timerfd_timer_open (void)
static int timerfd_timer_set_rate (void *data, unsigned int rate)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Timerfd Timing Interface" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_TIMING, }
static const struct ast_module_info * ast_module_info = &__mod_info
static struct ast_timing_interface timerfd_timing
static void * timing_funcs_handle
Detailed Description
timerfd timing interface
Author
Mark Michelson mmich.nosp@m.elso.nosp@m.n@dig.nosp@m.ium..nosp@m.com
Definition in file res_timing_timerfd.c.
Macro Definition Documentation
TIMERFD_MAX_RATE
#define TIMERFD_MAX_RATE 1000
Definition at line 68 of file res_timing_timerfd.c.
Referenced by timerfd_timer_get_max_rate().
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 280 of file res_timing_timerfd.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 280 of file res_timing_timerfd.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 280 of file res_timing_timerfd.c.
load_module()
static int load_module (void) static
Definition at line 251 of file res_timing_timerfd.c.
References ast_log, AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, ast_register_timing_interface, timerfd_timer::fd, LOG_ERROR, and timing_funcs_handle.
Referenced by unload_module().
 {
    int fd;
    /* Make sure we support the necessary clock type */
    if ((fd = timerfd_create(CLOCK_MONOTONIC, 0)) < 0) {
       ast_log(LOG_ERROR, "timerfd_create() not supported by the kernel.  Not loading.\n");
       return AST_MODULE_LOAD_DECLINE;
    }
    close(fd);
    if (!(timing_funcs_handle = ast_register_timing_interface(&timerfd_timing))) {
       return AST_MODULE_LOAD_DECLINE;
    }
    return AST_MODULE_LOAD_SUCCESS;
 }
timer_destroy()
static void timer_destroy (void * obj) static
Definition at line 76 of file res_timing_timerfd.c.
References timerfd_timer::fd, and timer.
Referenced by timerfd_timer_open().
 {
    struct timerfd_timer *timer = obj;
    if (timer->fd > -1) {
       close(timer->fd);
    }
 }
timerfd_timer_ack()
static int timerfd_timer_ack (void * data, unsigned int quantity) static
Definition at line 127 of file res_timing_timerfd.c.
References ao2_lock, ao2_unlock, ast_debug, ast_log, errno, timerfd_timer::fd, LOG_ERROR, and timer.
 {
    struct timerfd_timer *timer = data;
    uint64_t expirations;
    int read_result = 0;
    int res = 0;
    ao2_lock(timer);
    do {
       struct itimerspec timer_status;
       if (timerfd_gettime(timer->fd, &timer_status)) {
          ast_log(LOG_ERROR, "Call to timerfd_gettime() using handle %d error: %s\n", timer->fd, strerror(errno));
          expirations = 0;
          res = -1;
          break;
       }
       if (timer_status.it_value.tv_sec == 0 && timer_status.it_value.tv_nsec == 0) {
          ast_debug(1, "Avoiding read on disarmed timerfd %d\n", timer->fd);
          expirations = 0;
          break;
       }
       read_result = read(timer->fd, &expirations, sizeof(expirations));
       if (read_result == -1) {
          if (errno == EINTR || errno == EAGAIN) {
             continue;
          } else {
             ast_log(LOG_ERROR, "Read error: %s\n", strerror(errno));
             res = -1;
             break;
          }
       }
    } while (read_result != sizeof(expirations));
    ao2_unlock(timer);
    if (expirations != quantity) {
       ast_debug(2, "Expected to acknowledge %u ticks but got %llu instead\n", quantity, (unsigned long long) expirations);
    }
    return res;
 }
timerfd_timer_close()
static void timerfd_timer_close (void * data) static
Definition at line 101 of file res_timing_timerfd.c.
References ao2_ref.
 {
    ao2_ref(data, -1);
 }
timerfd_timer_disable_continuous()
static int timerfd_timer_disable_continuous (void * data) static
Definition at line 198 of file res_timing_timerfd.c.
References ao2_lock, ao2_unlock, timerfd_timer::fd, timerfd_timer::is_continuous, NULL, timerfd_timer::saved_timer, and timer.
 {
    struct timerfd_timer *timer = data;
    int res;
    ao2_lock(timer);
    if (!timer->is_continuous) {
       /* No reason to do anything if we're not
        * in continuous mode
        */
       ao2_unlock(timer);
       return 0;
    }
    res = timerfd_settime(timer->fd, 0, &timer->saved_timer, NULL);
    timer->is_continuous = 0;
    memset(&timer->saved_timer, 0, sizeof(timer->saved_timer));
    ao2_unlock(timer);
    return res;
 }
timerfd_timer_enable_continuous()
static int timerfd_timer_enable_continuous (void * data) static
Definition at line 173 of file res_timing_timerfd.c.
References ao2_lock, ao2_unlock, timerfd_timer::fd, timerfd_timer::is_continuous, timerfd_timer::saved_timer, and timer.
 {
    struct timerfd_timer *timer = data;
    int res;
    static const struct itimerspec continuous_timer = {
       .it_value.tv_nsec = 1L,
    };
    ao2_lock(timer);
    if (timer->is_continuous) {
       /*It's already in continous mode, no need to do
        * anything further
        */
       ao2_unlock(timer);
       return 0;
    }
    res = timerfd_settime(timer->fd, 0, &continuous_timer, &timer->saved_timer);
    timer->is_continuous = 1;
    ao2_unlock(timer);
    return res;
 }
timerfd_timer_fd()
static int timerfd_timer_fd (void * data) static
Definition at line 244 of file res_timing_timerfd.c.
References timerfd_timer::fd, and timer.
 {
    struct timerfd_timer *timer = data;
    return timer->fd;
 }
timerfd_timer_get_event()
static enum ast_timer_event timerfd_timer_get_event (void * data) static
Definition at line 221 of file res_timing_timerfd.c.
References ao2_lock, ao2_unlock, AST_TIMING_EVENT_CONTINUOUS, AST_TIMING_EVENT_EXPIRED, timerfd_timer::is_continuous, and timer.
 {
    struct timerfd_timer *timer = data;
    enum ast_timer_event res;
    ao2_lock(timer);
    if (timer->is_continuous) {
       res = AST_TIMING_EVENT_CONTINUOUS;
    } else {
       res = AST_TIMING_EVENT_EXPIRED;
    }
    ao2_unlock(timer);
    return res;
 }
timerfd_timer_get_max_rate()
static unsigned int timerfd_timer_get_max_rate (void * data) static
Definition at line 239 of file res_timing_timerfd.c.
References TIMERFD_MAX_RATE.
 {
    return TIMERFD_MAX_RATE;
 }
timerfd_timer_open()
static void * timerfd_timer_open (void) static
Definition at line 84 of file res_timing_timerfd.c.
References ao2_alloc, ao2_ref, ast_log, errno, timerfd_timer::fd, LOG_ERROR, NULL, timer, and timer_destroy().
 {
    struct timerfd_timer *timer;
    if (!(timer = ao2_alloc(sizeof(*timer), timer_destroy))) {
       ast_log(LOG_ERROR, "Could not allocate memory for timerfd_timer structure\n");
       return NULL;
    }
    if ((timer->fd = timerfd_create(CLOCK_MONOTONIC, 0)) < 0) {
       ast_log(LOG_ERROR, "Failed to create timerfd timer: %s\n", strerror(errno));
       ao2_ref(timer, -1);
       return NULL;
    }
    return timer;
 }
timerfd_timer_set_rate()
static int timerfd_timer_set_rate (void * data, unsigned int rate) static
Definition at line 106 of file res_timing_timerfd.c.
References ao2_lock, ao2_unlock, timerfd_timer::fd, timerfd_timer::is_continuous, NULL, timerfd_timer::saved_timer, and timer.
 {
    struct timerfd_timer *timer = data;
    int res = 0;
    ao2_lock(timer);
    timer->saved_timer.it_value.tv_sec = 0;
    timer->saved_timer.it_value.tv_nsec = rate ? (long) (1000000000 / rate) : 0L;
    timer->saved_timer.it_interval.tv_sec = timer->saved_timer.it_value.tv_sec;
    timer->saved_timer.it_interval.tv_nsec = timer->saved_timer.it_value.tv_nsec;
    if (!timer->is_continuous) {
       res = timerfd_settime(timer->fd, 0, &timer->saved_timer, NULL);
    }
    ao2_unlock(timer);
    return res;
 }
unload_module()
static int unload_module (void) static
Definition at line 270 of file res_timing_timerfd.c.
References AST_MODFLAG_LOAD_ORDER, AST_MODPRI_TIMING, AST_MODULE_INFO(), AST_MODULE_SUPPORT_CORE, ast_unregister_timing_interface(), ASTERISK_GPL_KEY, load_module(), and timing_funcs_handle.
 {
    return ast_unregister_timing_interface(timing_funcs_handle);
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Timerfd Timing Interface" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_TIMING, } static
Definition at line 280 of file res_timing_timerfd.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 280 of file res_timing_timerfd.c.
timerfd_timing
struct ast_timing_interface timerfd_timing static
Definition at line 54 of file res_timing_timerfd.c.
timing_funcs_handle
void* timing_funcs_handle static
Definition at line 42 of file res_timing_timerfd.c.
Referenced by load_module(), and unload_module().