Asterisk - The Open Source Telephony Project: res_hep_pjsip.c File Reference
res_hep_pjsip.c File Reference
PJSIP logging with Homer.
#include "asterisk.h"
#include <pjsip.h>
#include <pjsip_ua.h>
#include <pjlib.h>
#include "asterisk/res_pjsip.h"
#include "asterisk/res_pjsip_session.h"
#include "asterisk/res_hep.h"
#include "asterisk/module.h"
#include "asterisk/netsock2.h"
Functions
static void __reg_module (void)
static void __unreg_module (void)
static char * assign_uuid (const pj_str_t *call_id, const pj_str_t *local_tag, const pj_str_t *remote_tag)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int load_module (void)
static pj_bool_t logging_on_rx_msg (pjsip_rx_data *rdata)
static pj_status_t logging_on_tx_msg (pjsip_tx_data *tdata)
static int transport_to_protocol_id (pjsip_transport *tp)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_DEFAULT , .description = "PJSIP HEPv3 Logger" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_EXTENDED, .load = load_module, .unload = unload_module, .requires = "res_pjsip,res_pjsip_session,res_hep", }
static const struct ast_module_info * ast_module_info = &__mod_info
static pjsip_module logging_module
Detailed Description
PJSIP logging with Homer.
Author
Matt Jordan mjord.nosp@m.an@d.nosp@m.igium.nosp@m..com
Definition in file res_hep_pjsip.c.
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 255 of file res_hep_pjsip.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 255 of file res_hep_pjsip.c.
assign_uuid()
static char* assign_uuid (const pj_str_t * call_id, const pj_str_t * local_tag, const pj_str_t * remote_tag) static
Definition at line 47 of file res_hep_pjsip.c.
References ao2_cleanup, ast_channel_name(), ast_copy_pj_str(), ast_malloc, ast_sip_dialog_get_session(), ast_strdup, HEP_UUID_TYPE_CHANNEL, hepv3_get_uuid_type(), NULL, RAII_VAR, session, and hepv3_capture_info::uuid.
Referenced by logging_on_rx_msg(), and logging_on_tx_msg().
 {
    RAII_VAR(struct ast_sip_session *, session, NULL, ao2_cleanup);
    pjsip_dialog *dlg;
    char *uuid = NULL;
    enum hep_uuid_type uuid_type = hepv3_get_uuid_type();
    if ((uuid_type == HEP_UUID_TYPE_CHANNEL)
       && (dlg = pjsip_ua_find_dialog(call_id, local_tag, remote_tag, PJ_FALSE))
        && (session = ast_sip_dialog_get_session(dlg))
        && (session->channel)) {
       uuid = ast_strdup(ast_channel_name(session->channel));
    }
    /* If we couldn't get the channel or we never wanted it, default to the call-id */
    if (!uuid) {
       uuid = ast_malloc(pj_strlen(call_id) + 1);
       if (uuid) {
          ast_copy_pj_str(uuid, call_id, pj_strlen(call_id) + 1);
       }
    }
    return uuid;
 }
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 255 of file res_hep_pjsip.c.
load_module()
static int load_module (void) static
Definition at line 233 of file res_hep_pjsip.c.
References ast_log, AST_LOG_WARNING, AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, ast_sip_register_service(), hepv3_is_loaded(), and logging_module.
Referenced by unload_module().
 {
    if (!hepv3_is_loaded()) {
       ast_log(AST_LOG_WARNING, "res_hep is disabled; declining module load\n");
       return AST_MODULE_LOAD_DECLINE;
    }
    ast_sip_register_service(&logging_module);
    return AST_MODULE_LOAD_SUCCESS;
 }
logging_on_rx_msg()
static pj_bool_t logging_on_rx_msg (pjsip_rx_data * rdata) static
Definition at line 156 of file res_hep_pjsip.c.
References ao2_ref, assign_uuid(), ast_sip_get_pjsip_endpoint(), ast_sockaddr_parse(), hepv3_capture_info::capture_time, hepv3_capture_info::capture_type, hepv3_capture_info::dst_addr, HEPV3_CAPTURE_TYPE_SIP, hepv3_create_capture_info(), hepv3_send_packet(), PARSE_PORT_REQUIRE, hepv3_capture_info::protocol_id, hepv3_capture_info::src_addr, transport_to_protocol_id(), hepv3_capture_info::uuid, and hepv3_capture_info::zipped.
 {
    char local_buf[256];
    char remote_buf[256];
    char *uuid;
    struct hepv3_capture_info *capture_info;
    capture_info = hepv3_create_capture_info(&rdata->pkt_info.packet, rdata->pkt_info.len);
    if (!capture_info) {
       return PJ_SUCCESS;
    }
    if (!rdata->pkt_info.src_addr_len) {
       return PJ_SUCCESS;
    }
    pj_sockaddr_print(&rdata->pkt_info.src_addr, remote_buf, sizeof(remote_buf), 3);
    if (!(rdata->tp_info.transport->flag & PJSIP_TRANSPORT_RELIABLE)) {
       pjsip_tpmgr_fla2_param prm;
       /* Attempt to determine what IP address we probably received this packet on */
       pjsip_tpmgr_fla2_param_default(&prm);
       prm.tp_type = rdata->tp_info.transport->key.type;
       pj_strset2(&prm.dst_host, rdata->pkt_info.src_name);
       prm.local_if = PJ_TRUE;
       /* If we can't get the local address use what we have already */
       if (pjsip_tpmgr_find_local_addr2(pjsip_endpt_get_tpmgr(ast_sip_get_pjsip_endpoint()), rdata->tp_info.pool, &prm) != PJ_SUCCESS) {
          pj_sockaddr_print(&rdata->tp_info.transport->local_addr, local_buf, sizeof(local_buf), 3);
       } else {
          if (prm.tp_type & PJSIP_TRANSPORT_IPV6) {
             snprintf(local_buf, sizeof(local_buf), "[%.*s]:%hu",
                (int)pj_strlen(&prm.ret_addr),
                pj_strbuf(&prm.ret_addr),
                prm.ret_port);
          } else {
             snprintf(local_buf, sizeof(local_buf), "%.*s:%hu",
                (int)pj_strlen(&prm.ret_addr),
                pj_strbuf(&prm.ret_addr),
                prm.ret_port);
          }
       }
    } else {
       pj_sockaddr_print(&rdata->tp_info.transport->local_addr, local_buf, sizeof(local_buf), 3);
    }
    uuid = assign_uuid(&rdata->msg_info.cid->id, &rdata->msg_info.to->tag, &rdata->msg_info.from->tag);
    if (!uuid) {
       ao2_ref(capture_info, -1);
       return PJ_SUCCESS;
    }
    ast_sockaddr_parse(&capture_info->src_addr, remote_buf, PARSE_PORT_REQUIRE);
    ast_sockaddr_parse(&capture_info->dst_addr, local_buf, PARSE_PORT_REQUIRE);
    capture_info->protocol_id = transport_to_protocol_id(rdata->tp_info.transport);
    capture_info->capture_time.tv_sec = rdata->pkt_info.timestamp.sec;
    capture_info->capture_time.tv_usec = rdata->pkt_info.timestamp.msec * 1000;
    capture_info->capture_type = HEPV3_CAPTURE_TYPE_SIP;
    capture_info->uuid = uuid;
    capture_info->zipped = 0;
    hepv3_send_packet(capture_info);
    return PJ_FALSE;
 }
logging_on_tx_msg()
static pj_status_t logging_on_tx_msg (pjsip_tx_data * tdata) static
Definition at line 83 of file res_hep_pjsip.c.
References ao2_ref, assign_uuid(), ast_sip_get_pjsip_endpoint(), ast_sockaddr_parse(), ast_tvnow(), hepv3_capture_info::capture_time, hepv3_capture_info::capture_type, hepv3_capture_info::dst_addr, HEPV3_CAPTURE_TYPE_SIP, hepv3_create_capture_info(), hepv3_send_packet(), PARSE_PORT_REQUIRE, hepv3_capture_info::protocol_id, hepv3_capture_info::src_addr, transport_to_protocol_id(), hepv3_capture_info::uuid, and hepv3_capture_info::zipped.
 {
    char local_buf[256];
    char remote_buf[256];
    char *uuid;
    struct hepv3_capture_info *capture_info;
    pjsip_cid_hdr *cid_hdr;
    pjsip_from_hdr *from_hdr;
    pjsip_to_hdr *to_hdr;
    capture_info = hepv3_create_capture_info(tdata->buf.start, (size_t)(tdata->buf.cur - tdata->buf.start));
    if (!capture_info) {
       return PJ_SUCCESS;
    }
    if (!(tdata->tp_info.transport->flag & PJSIP_TRANSPORT_RELIABLE)) {
       pjsip_tpmgr_fla2_param prm;
       /* Attempt to determine what IP address will we send this packet out of */
       pjsip_tpmgr_fla2_param_default(&prm);
       prm.tp_type = tdata->tp_info.transport->key.type;
       pj_strset2(&prm.dst_host, tdata->tp_info.dst_name);
       prm.local_if = PJ_TRUE;
       /* If we can't get the local address use what we have already */
       if (pjsip_tpmgr_find_local_addr2(pjsip_endpt_get_tpmgr(ast_sip_get_pjsip_endpoint()), tdata->pool, &prm) != PJ_SUCCESS) {
          pj_sockaddr_print(&tdata->tp_info.transport->local_addr, local_buf, sizeof(local_buf), 3);
       } else {
          if (prm.tp_type & PJSIP_TRANSPORT_IPV6) {
             snprintf(local_buf, sizeof(local_buf), "[%.*s]:%hu",
                (int)pj_strlen(&prm.ret_addr),
                pj_strbuf(&prm.ret_addr),
                prm.ret_port);
          } else {
             snprintf(local_buf, sizeof(local_buf), "%.*s:%hu",
                (int)pj_strlen(&prm.ret_addr),
                pj_strbuf(&prm.ret_addr),
                prm.ret_port);
          }
       }
    } else {
       /* For reliable transports they can only ever come from the transport
        * local address.
        */
       pj_sockaddr_print(&tdata->tp_info.transport->local_addr, local_buf, sizeof(local_buf), 3);
    }
    pj_sockaddr_print(&tdata->tp_info.dst_addr, remote_buf, sizeof(remote_buf), 3);
    cid_hdr = PJSIP_MSG_CID_HDR(tdata->msg);
    from_hdr = PJSIP_MSG_FROM_HDR(tdata->msg);
    to_hdr = PJSIP_MSG_TO_HDR(tdata->msg);
    uuid = assign_uuid(&cid_hdr->id, &to_hdr->tag, &from_hdr->tag);
    if (!uuid) {
       ao2_ref(capture_info, -1);
       return PJ_SUCCESS;
    }
    ast_sockaddr_parse(&capture_info->src_addr, local_buf, PARSE_PORT_REQUIRE);
    ast_sockaddr_parse(&capture_info->dst_addr, remote_buf, PARSE_PORT_REQUIRE);
    capture_info->protocol_id = transport_to_protocol_id(tdata->tp_info.transport);
    capture_info->capture_time = ast_tvnow();
    capture_info->capture_type = HEPV3_CAPTURE_TYPE_SIP;
    capture_info->uuid = uuid;
    capture_info->zipped = 0;
    hepv3_send_packet(capture_info);
    return PJ_SUCCESS;
 }
transport_to_protocol_id()
static int transport_to_protocol_id (pjsip_transport * tp) static
Definition at line 74 of file res_hep_pjsip.c.
Referenced by logging_on_rx_msg(), and logging_on_tx_msg().
 {
    /* XXX If we ever add SCTP support, we'll need to revisit */
    if (tp->flag & PJSIP_TRANSPORT_RELIABLE) {
       return IPPROTO_TCP;
    }
    return IPPROTO_UDP;
 }
unload_module()
static int unload_module (void) static
Definition at line 244 of file res_hep_pjsip.c.
References AST_MODFLAG_DEFAULT, AST_MODULE_INFO(), AST_MODULE_SUPPORT_EXTENDED, ast_sip_unregister_service(), ASTERISK_GPL_KEY, load_module(), and logging_module.
 {
    ast_sip_unregister_service(&logging_module);
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_DEFAULT , .description = "PJSIP HEPv3 Logger" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_EXTENDED, .load = load_module, .unload = unload_module, .requires = "res_pjsip,res_pjsip_session,res_hep", } static
Definition at line 255 of file res_hep_pjsip.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 255 of file res_hep_pjsip.c.
logging_module
pjsip_module logging_module static
Definition at line 223 of file res_hep_pjsip.c.
Referenced by load_module(), and unload_module().