Asterisk - The Open Source Telephony Project: test_pbx.c File Reference
test_pbx.c File Reference
PBX Tests.
#include "asterisk.h"
#include "asterisk/module.h"
#include "asterisk/pbx.h"
#include "asterisk/test.h"
#include <signal.h>
Data Structures
struct exten_info
an extension to add to our context
struct pbx_test_pattern
Macros
#define MAX_PRIORITIES 10
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
AST_TEST_DEFINE (pattern_match_test)
AST_TEST_DEFINE (segv)
AST_TEST_DEFINE (call_assert)
AST_TEST_DEFINE (call_backtrace)
static int load_module (void)
static int test_exten (const struct pbx_test_pattern *test_pattern, struct ast_test *test, int new_engine)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "PBX test module" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, }
static const struct ast_module_info * ast_module_info = &__mod_info
Detailed Description
PBX Tests.
Author
Mark Michelson mmich.nosp@m.elso.nosp@m.n@dig.nosp@m.ium..nosp@m.com
This module will run some PBX tests.
Definition in file test_pbx.c.
Macro Definition Documentation
MAX_PRIORITIES
#define MAX_PRIORITIES 10
If we determine that we really need to be able to register more than 10 priorities for a single extension, then fine, we can do that later.
Definition at line 48 of file test_pbx.c.
Referenced by AST_TEST_DEFINE().
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 404 of file test_pbx.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 404 of file test_pbx.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 404 of file test_pbx.c.
AST_TEST_DEFINE() [1/4]
AST_TEST_DEFINE (pattern_match_test)
Definition at line 188 of file test_pbx.c.
References ARRAY_LEN, ast_add_extension(), ast_context_add_include(), ast_context_destroy(), ast_context_find_or_create(), AST_TEST_FAIL, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_test_status_update, exten_info::cid, cleanup(), exten_info::context, contexts, exten_info::exten, sip_to_pjsip::info(), MAX_PRIORITIES, NULL, exten_info::num_priorities, pbx_set_extenpatternmatchnew(), exten_info::priorities, priority, registrar, TEST_EXECUTE, test_exten(), and TEST_INIT.
 {
    static const char registrar[] = "test_pbx";
    enum ast_test_result_state res = AST_TEST_PASS;
    static const char TEST_PATTERN[] = "test_pattern";
    static const char TEST_PATTERN_INCLUDE[] = "test_pattern_include";
    int i, j;
    /* The array of contexts to register for our test.
     * To add more contexts, just add more rows to this array.
     */
    struct {
       const char * context_string;
    } contexts[] = {
       { TEST_PATTERN, },
       { TEST_PATTERN_INCLUDE, },
    };
    /*
     * Map to indicate which contexts should be included inside
     * other contexts. The first context listed will include
     * the second context listed.
     *
     * To add more inclusions, add new rows to this array.
     */
    const struct {
       const char *outer_context;
       const char *inner_context;
    } context_includes[] = {
       { TEST_PATTERN, TEST_PATTERN_INCLUDE },
    };
    /* The array of extensions to add to our test context.
     * For more information about the individual fields, see
     * the doxygen for struct exten_info.
     *
     * To add new extensions to the test, simply add new rows
     * to this array. All extensions will automatically be
     * added when the test is run.
     */
    const struct exten_info extens[] = {
       [0] = { TEST_PATTERN, "_2.", NULL, 1, { 1 } },
       [1] = { TEST_PATTERN, "2000", NULL, 1, { 1 } },
       [2] = { TEST_PATTERN_INCLUDE, "2000", NULL, 1, { 2 } },
    };
    /* This array contains our test material. See the doxygen
     * for struct pbx_test_pattern for more information on each
     * component.
     *
     * To add more test cases, add more lines to this array. Each
     * case will be tested automatically when the test is run.
     */
    const struct pbx_test_pattern tests[] = {
       { TEST_PATTERN, "200", NULL, 1, &extens[0] },
       { TEST_PATTERN, "2000", NULL, 1, &extens[1] },
       { TEST_PATTERN, "2000", NULL, 2, &extens[2] },
       { TEST_PATTERN_INCLUDE, "2000", NULL, 2, &extens[2] },
    };
    switch (cmd) {
    case TEST_INIT:
       info->name = "pattern_match_test";
       info->category = "/main/pbx/";
       info->summary = "Test pattern matching";
       info->description = "Create a context with a bunch of extensions within. Then attempt\n"
          "to match some strings to the extensions.";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    /* Step one is to build the dialplan.
     *
     * We iterate first through the contexts array to build
     * all the contexts we'll need. Then, we iterate over the
     * extens array to add all the extensions to the appropriate
     * contexts.
     */
    for (i = 0; i < ARRAY_LEN(contexts); ++i) {
       if (!ast_context_find_or_create(NULL, NULL, contexts[i].context_string, registrar)) {
          ast_test_status_update(test, "Failed to create context %s\n", contexts[i].context_string);
          res = AST_TEST_FAIL;
          goto cleanup;
       }
    }
    for (i = 0; i < ARRAY_LEN(context_includes); ++i) {
       if (ast_context_add_include(context_includes[i].outer_context,
                context_includes[i].inner_context, registrar)) {
          ast_test_status_update(test, "Failed to include context %s inside context %s\n",
                context_includes[i].inner_context, context_includes[i].outer_context);
          res = AST_TEST_FAIL;
          goto cleanup;
       }
    }
    for (i = 0; i < ARRAY_LEN(extens); ++i) {
       int priority;
       if (extens[i].num_priorities > MAX_PRIORITIES) {
          ast_test_status_update(test, "Invalid number of priorities specified for extension %s."
                "Max is %d, but we requested %d. Test failed\n",
                extens[i].exten, MAX_PRIORITIES, extens[i].num_priorities);
          res = AST_TEST_FAIL;
          goto cleanup;
       }
       for (priority = 0; priority < extens[i].num_priorities; ++priority) {
          if (ast_add_extension(extens[i].context, 0, extens[i].exten, extens[i].priorities[priority],
                   NULL, extens[i].cid, "Noop", (void *) extens[i].exten, NULL, registrar)) {
             ast_test_status_update(test, "Failed to add extension %s, priority %d, to context %s."
                   "Test failed\n", extens[i].exten, extens[i].priorities[priority], extens[i].context);
             res = AST_TEST_FAIL;
             goto cleanup;
          }
       }
    }
    /* At this stage, the dialplan is built. Now we iterate over
     * the tests array to attempt to find each of the specified
     * extensions with the old and new pattern matching engines.
     */
    for (j = 0; j < 2; j++) {
       pbx_set_extenpatternmatchnew(j);
       for (i = 0; i < ARRAY_LEN(tests); ++i) {
          if (test_exten(&tests[i], test, j)) {
             res = AST_TEST_FAIL;
             break;
          }
       }
    }
 cleanup:
    ast_context_destroy(NULL, registrar);
    return res;
 }
AST_TEST_DEFINE() [2/4]
AST_TEST_DEFINE (segv)
Definition at line 326 of file test_pbx.c.
References AST_TEST_FAIL, AST_TEST_NOT_RUN, sip_to_pjsip::info(), TEST_EXECUTE, and TEST_INIT.
 {
    switch (cmd) {
    case TEST_INIT:
       info->name = "RAISE_SEGV";
       info->category = "/DO_NOT_RUN/";
       info->summary = "RAISES SEGV!!! (will only be run if explicitly called)";
       info->description = "RAISES SEGV!!! (will only be run if explicitly called). "
          "This test is mainly used for testing CI and tool failure scenarios.";
       info->explicit_only = 1;
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    raise(SIGSEGV);
    return AST_TEST_FAIL;
 }
AST_TEST_DEFINE() [3/4]
AST_TEST_DEFINE (call_assert)
Definition at line 346 of file test_pbx.c.
References ast_assert, AST_TEST_NOT_RUN, AST_TEST_PASS, sip_to_pjsip::info(), TEST_EXECUTE, and TEST_INIT.
 {
    switch (cmd) {
    case TEST_INIT:
       info->name = "CALL_ASSERT";
       info->category = "/DO_NOT_RUN/";
       info->summary = "Calls ast_asert()!!! (will only be run if explicitly called)";
       info->description = "Calls ast_asert()!!! (will only be run if explicitly called). "
          "This test is mainly used for testing CI and tool failure scenarios.";
       info->explicit_only = 1;
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    ast_assert(0);
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [4/4]
AST_TEST_DEFINE (call_backtrace)
Definition at line 366 of file test_pbx.c.
References ast_log_backtrace(), AST_TEST_NOT_RUN, AST_TEST_PASS, sip_to_pjsip::info(), TEST_EXECUTE, and TEST_INIT.
 {
    switch (cmd) {
    case TEST_INIT:
       info->name = "CALL_BACKTRACE";
       info->category = "/DO_NOT_RUN/";
       info->summary = "Calls ast_log_backtrace()!!! (will only be run if explicitly called)";
       info->description = "Calls ast_log_backtrace()!!! (will only be run if explicitly called). "
          "This test is mainly used for testing CI and tool failure scenarios.";
       info->explicit_only = 1;
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    ast_log_backtrace();
    return AST_TEST_PASS;
 }
load_module()
static int load_module (void) static
Definition at line 395 of file test_pbx.c.
References AST_MODULE_LOAD_SUCCESS, and AST_TEST_REGISTER.
 {
    AST_TEST_REGISTER(pattern_match_test);
    AST_TEST_REGISTER(segv);
    AST_TEST_REGISTER(call_assert);
    AST_TEST_REGISTER(call_backtrace);
    return AST_MODULE_LOAD_SUCCESS;
 }
test_exten()
static int test_exten (const struct pbx_test_pattern * test_pattern, struct ast_test * test, int new_engine) static
Definition at line 156 of file test_pbx.c.
References ast_canmatch_extension(), ast_get_extension_cidmatch(), ast_get_extension_name(), ast_test_status_update, exten_info::cid, pbx_test_pattern::context, E_MATCH, exten_info::exten, pbx_test_pattern::exten, NULL, pbx_find_extension(), pbx_test_pattern::priority, pbx_test_pattern::test_cid, and pbx_test_pattern::test_exten.
Referenced by AST_TEST_DEFINE().
 {
    struct pbx_find_info pfi = { { 0 }, };
    struct ast_exten *exten;
    if (!(exten = pbx_find_extension(NULL, NULL, &pfi, test_pattern->context,
                test_pattern->test_exten, test_pattern->priority, NULL,
                test_pattern->test_cid, E_MATCH))) {
       ast_test_status_update(test, "Cannot find extension %s in context %s with the %s pattern match engine. "
             "Test failed.\n", test_pattern->test_exten, test_pattern->context, (new_engine ? "new" : "old"));
       return -1;
    }
    if (strcmp(ast_get_extension_name(exten), test_pattern->exten->exten)) {
       ast_test_status_update(test, "Expected extension %s but got extension %s instead with the %s pattern match engine. "
             "Test failed.\n", test_pattern->exten->exten, ast_get_extension_name(exten), (new_engine ? "new" : "old"));
       return -1;
    }
    if (test_pattern->test_cid && strcmp(ast_get_extension_cidmatch(exten), test_pattern->test_cid)) {
       ast_test_status_update(test, "Expected CID match %s but got CID match %s instead with the %s pattern match engine. "
             "Test failed.\n", test_pattern->exten->cid, ast_get_extension_cidmatch(exten), (new_engine ? "new" : "old"));
       return -1;
    }
    if (!ast_canmatch_extension(NULL, test_pattern->context, test_pattern->test_exten,
                test_pattern->priority, test_pattern->test_cid)) {
       ast_test_status_update(test, "Partial match failed for extension %s in context %s with the %s pattern match engine. "
             "Test failed.\n", test_pattern->test_exten, test_pattern->context, (new_engine ? "new" : "old"));
       return -1;
    }
    ast_test_status_update(test, "Successfully matched %s to exten %s in context %s with the %s pattern match engine\n",
          test_pattern->test_exten, test_pattern->exten->exten, test_pattern->context, (new_engine ? "new" : "old"));
    return 0;
 }
unload_module()
static int unload_module (void) static
Definition at line 386 of file test_pbx.c.
References AST_TEST_UNREGISTER.
 {
    AST_TEST_UNREGISTER(call_backtrace);
    AST_TEST_UNREGISTER(call_assert);
    AST_TEST_UNREGISTER(segv);
    AST_TEST_UNREGISTER(pattern_match_test);
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "PBX test module" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, } static
Definition at line 404 of file test_pbx.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 404 of file test_pbx.c.