Asterisk - The Open Source Telephony Project: ael_structs.h File Reference
ael_structs.h File Reference
Structures for AEL - the Asterisk extension language.
#include "asterisk/paths.h"
#include "pval.h"
Data Structures
struct ael_extension
struct ael_priority
struct parse_io
Macros
#define QUAD_MAX (0x7fffffffffffffffLL)
#define QUAD_MIN (-0x7fffffffffffffffLL-1)
#define YY_TYPEDEF_YY_SCANNER_T
Typedefs
typedef void * yyscan_t
Enumerations
enum ael_priority_type {
AEL_APPCALL, AEL_CONTROL1, AEL_FOR_CONTROL, AEL_IF_CONTROL,
AEL_IFTIME_CONTROL, AEL_RAND_CONTROL, AEL_LABEL, AEL_RETURN
}
Functions
struct pval * ael2_parse (char *fname, int *errs)
void ael2_print (char *fname, pval *tree)
void ael2_semantic_check (pval *item, int *errs, int *warns, int *notes)
void destroy_pval (pval *item)
pval * linku1 (pval *head, pval *tail)
pval * npval (pvaltype type, int first_line, int last_line, int first_column, int last_column)
Variables
char * prev_word
Detailed Description
Structures for AEL - the Asterisk extension language.
pbx_ael.c
Todo:
document this file (ael.h)
Definition in file ael_structs.h.
Macro Definition Documentation
QUAD_MAX
#define QUAD_MAX (0x7fffffffffffffffLL)
Definition at line 54 of file ael_structs.h.
QUAD_MIN
#define QUAD_MIN (-0x7fffffffffffffffLL-1)
Definition at line 51 of file ael_structs.h.
YY_TYPEDEF_YY_SCANNER_T
#define YY_TYPEDEF_YY_SCANNER_T
Definition at line 70 of file ael_structs.h.
Typedef Documentation
yyscan_t
typedef void* yyscan_t
Definition at line 71 of file ael_structs.h.
Enumeration Type Documentation
ael_priority_type
enum ael_priority_type
Enumerator
AEL_APPCALL
AEL_CONTROL1
AEL_FOR_CONTROL
AEL_IF_CONTROL
AEL_IFTIME_CONTROL
AEL_RAND_CONTROL
AEL_LABEL
AEL_RETURN
Definition at line 84 of file ael_structs.h.
 { AEL_APPCALL, AEL_CONTROL1, AEL_FOR_CONTROL, AEL_IF_CONTROL, AEL_IFTIME_CONTROL, AEL_RAND_CONTROL, AEL_LABEL, AEL_RETURN } ael_priority_type;
Function Documentation
ael2_parse()
struct pval* ael2_parse (char * fname, int * errs)
Definition at line 3360 of file ael_lex.c.
References ael_yy_scan_string(), ael_yylex_destroy(), ael_yylex_init(), ael_yyparse(), ael_yyset_lineno(), ast_log, calloc, errno, free(), include_stack_index, io, LOG_ERROR, LOG_WARNING, malloc(), my_col, my_file, my_lineno, prev_word, parse_io::pval, parse_io::scanner, strdup, and parse_io::syntax_error_count.
Referenced by pbx_load_module().
 {
    struct pval *pvalue;
    struct parse_io *io;
    char *buffer;
    struct stat stats;
    FILE *fin;
    /* extern int ael_yydebug; */
    io = calloc(sizeof(struct parse_io),1);
    /* reset the global counters */
    prev_word = 0;
    my_lineno = 1;
    include_stack_index=0;
    my_col = 0;
    /* ael_yydebug = 1; */
    ael_yylex_init(&io->scanner);
    fin = fopen(filename,"r");
    if ( !fin ) {
       ast_log(LOG_ERROR,"File %s could not be opened\n", filename);
       *errors = 1;
       return 0;
    }
    if (my_file)
       free(my_file);
    my_file = strdup(filename);
    if (stat(filename, &stats)) {
       ast_log(LOG_WARNING, "failed to populate stats from file '%s'\n", filename);
    }
    buffer = (char*)malloc(stats.st_size+2);
    if (fread(buffer, 1, stats.st_size, fin) != stats.st_size) {
       ast_log(LOG_ERROR, "fread() failed: %s\n", strerror(errno));
    }
    buffer[stats.st_size]=0;
    fclose(fin);
    ael_yy_scan_string (buffer ,io->scanner);
    ael_yyset_lineno(1 , io->scanner);
    /* ael_yyset_in (fin , io->scanner);   OLD WAY */
    ael_yyparse(io);
    pvalue = io->pval;
    *errors = io->syntax_error_count;
    ael_yylex_destroy(io->scanner);
    free(buffer);
    free(io);
    return pvalue;
 }
ael2_print()
void ael2_print (char * fname, pval * tree)
Definition at line 382 of file pval.c.
References ast_log, item, LOG_ERROR, print_pval_list(), traverse_pval_item_template(), and traverse_pval_template().
Referenced by main().
 {
    FILE *fin = fopen(fname,"w");
    if ( !fin ) {
       ast_log(LOG_ERROR, "Couldn't open %s for writing.\n", fname);
       return;
    }
    print_pval_list(fin, tree, 0);
    fclose(fin);
 }
ael2_semantic_check()
void ael2_semantic_check (pval * item, int * errs, int * warns, int * notes)
Definition at line 2885 of file pval.c.
References ast_alloca, ast_config_AST_VAR_DIR, check_context_names(), check_pval(), errs, item, notes, and warns.
Referenced by pbx_load_module().
 {
 #ifdef AAL_ARGCHECK
    int argapp_errs =0;
    char *rfilename;
 #endif
    struct argapp *apps=0;
    if (!item)
       return; /* don't check an empty tree */
 #ifdef AAL_ARGCHECK
    rfilename = ast_alloca(10 + strlen(ast_config_AST_VAR_DIR));
    sprintf(rfilename, "%s/applist", ast_config_AST_VAR_DIR);
    apps = argdesc_parse(rfilename, &argapp_errs); /* giveth */
 #endif
    current_db = item;
    errs = warns = notes = 0;
    check_context_names();
    check_pval(item, apps, 0);
 #ifdef AAL_ARGCHECK
    argdesc_destroy(apps);  /* taketh away */
 #endif
    current_db = 0;
    *arg_errs = errs;
    *arg_warns = warns;
    *arg_notes = notes;
 }
destroy_pval()
void destroy_pval (pval * item)
Definition at line 4940 of file pval.c.
Referenced by yydestruct(), and yyparse().
 {
    pval *i,*nxt;
    for (i=item; i; i=nxt) {
       nxt = i->next;
       destroy_pval_item(i);
    }
 }
linku1()
pval* linku1 (pval * head, pval * tail)
Definition at line 5922 of file pval.c.
 {
    if (!head)
       return tail;
    if (tail) {
       if (!head->next) {
          head->next = tail;
       } else {
          head->u1_last->next = tail;
       }
       head->u1_last = tail;
       tail->prev = head; /* the dad link only points to containers */
    }
    return head;
 }
npval()
struct pval * npval (pvaltype type, int first_line, int last_line, int first_column, int last_column)
Definition at line 3965 of file ael.tab.c.
References calloc, pval::endcol, pval::endline, pval::filename, my_file, S_OR, pval::startcol, pval::startline, strdup, pval::type, and type.
Referenced by npval2(), and yyparse().
 {
    pval *z = calloc(1, sizeof(struct pval));
    z->type = type;
    z->startline = first_line;
    z->endline = last_line;
    z->startcol = first_column;
    z->endcol = last_column;
    z->filename = strdup(S_OR(my_file, "<none>"));
    return z;
 }
Variable Documentation
prev_word
char* prev_word
Definition at line 889 of file ael_lex.c.
Referenced by ael2_parse(), c_prevword(), while(), yydestruct(), and yyparse().