Asterisk - The Open Source Telephony Project: res_stasis_mailbox.c File Reference
res_stasis_mailbox.c File Reference
#include "asterisk.h"
#include "asterisk/astdb.h"
#include "asterisk/astobj2.h"
#include "asterisk/module.h"
#include "asterisk/stasis_app_impl.h"
#include "asterisk/stasis_app_mailbox.h"
#include "asterisk/res_mwi_external.h"
Macros
#define MAILBOX_BUCKETS 37
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int load_module (void)
static struct ast_json * mailbox_to_json (const struct ast_mwi_mailbox_object *mailbox)
enum stasis_mailbox_result stasis_app_mailbox_delete (const char *name)
Delete a mailbox controlled by ARI.
enum stasis_mailbox_result stasis_app_mailbox_to_json (const char *name, struct ast_json **json)
Convert mailbox to JSON.
int stasis_app_mailbox_update (const char *name, int old_messages, int new_messages)
Changes the state of a mailbox.
struct ast_json * stasis_app_mailboxes_to_json ()
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_GLOBAL_SYMBOLS , .description = "Stasis application mailbox support" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .requires = "res_stasis,res_mwi_external" }
static const struct ast_module_info * ast_module_info = &__mod_info
Macro Definition Documentation
MAILBOX_BUCKETS
#define MAILBOX_BUCKETS 37
Number of hash buckets for mailboxes
Definition at line 35 of file res_stasis_mailbox.c.
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 159 of file res_stasis_mailbox.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 159 of file res_stasis_mailbox.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 159 of file res_stasis_mailbox.c.
load_module()
static int load_module (void) static
Definition at line 144 of file res_stasis_mailbox.c.
References AST_MODULE_LOAD_SUCCESS.
Referenced by unload_module().
 {
    return AST_MODULE_LOAD_SUCCESS;
 }
mailbox_to_json()
static struct ast_json* mailbox_to_json (const struct ast_mwi_mailbox_object * mailbox) static
Definition at line 37 of file res_stasis_mailbox.c.
References ast_json_pack(), ast_mwi_mailbox_get_id(), ast_mwi_mailbox_get_msgs_new(), and ast_mwi_mailbox_get_msgs_old().
Referenced by stasis_app_mailbox_to_json(), and stasis_app_mailboxes_to_json().
 {
    return ast_json_pack("{s: s, s: i, s: i}",
       "name", ast_mwi_mailbox_get_id(mailbox),
       "old_messages", ast_mwi_mailbox_get_msgs_old(mailbox),
       "new_messages", ast_mwi_mailbox_get_msgs_new(mailbox));
 }
stasis_app_mailbox_delete()
enum stasis_mailbox_result stasis_app_mailbox_delete (const char * name)
Delete a mailbox controlled by ARI.
Parameters
name the name of the ARI controlled mailbox
Returns
a stasis mailbox application result
Definition at line 122 of file res_stasis_mailbox.c.
References ast_mwi_mailbox_delete(), ast_mwi_mailbox_get(), ast_mwi_mailbox_unref, mailbox, NULL, STASIS_MAILBOX_ERROR, STASIS_MAILBOX_MISSING, and STASIS_MAILBOX_OK.
Referenced by ast_ari_mailboxes_delete().
 {
    const struct ast_mwi_mailbox_object *mailbox;
    /* Make sure the mailbox actually exists before we delete it */
    mailbox = ast_mwi_mailbox_get(name);
    if (!mailbox) {
       return STASIS_MAILBOX_MISSING;
    }
    ast_mwi_mailbox_unref(mailbox);
    mailbox = NULL;
    /* Now delete the mailbox */
    if (ast_mwi_mailbox_delete(name)) {
       return STASIS_MAILBOX_ERROR;
    }
    return STASIS_MAILBOX_OK;
 }
stasis_app_mailbox_to_json()
enum stasis_mailbox_result stasis_app_mailbox_to_json (const char * name, struct ast_json ** json)
Convert mailbox to JSON.
Parameters
name the name of the mailbox
json If the query is successful, this pointer at this address will be set to the JSON representation of the mailbox
Returns
stasis mailbox result code indicating success or failure and cause
NULL on error.
Definition at line 46 of file res_stasis_mailbox.c.
References ast_mwi_mailbox_get(), ast_mwi_mailbox_unref, mailbox, mailbox_to_json(), STASIS_MAILBOX_ERROR, STASIS_MAILBOX_MISSING, and STASIS_MAILBOX_OK.
Referenced by ast_ari_mailboxes_get().
 {
    struct ast_json *mailbox_json;
    const struct ast_mwi_mailbox_object *mailbox;
    mailbox = ast_mwi_mailbox_get(name);
    if (!mailbox) {
       return STASIS_MAILBOX_MISSING;
    }
    mailbox_json = mailbox_to_json(mailbox);
    if (!mailbox_json) {
       ast_mwi_mailbox_unref(mailbox);
       return STASIS_MAILBOX_ERROR;
    }
    *json = mailbox_json;
    return STASIS_MAILBOX_OK;
 }
stasis_app_mailbox_update()
int stasis_app_mailbox_update (const char * name, int old_messages, int new_messages)
Changes the state of a mailbox.
Note
Implicitly creates the mailbox.
Parameters
name The name of the ARI controlled mailbox
old_messages count of old (read) messages in the mailbox
new_messages count of new (unread) messages in the mailbox
Returns
0 if successful
-1 on internal error.
Definition at line 101 of file res_stasis_mailbox.c.
References ast_mwi_mailbox_alloc(), ast_mwi_mailbox_set_msgs_new(), ast_mwi_mailbox_set_msgs_old(), ast_mwi_mailbox_unref, ast_mwi_mailbox_update(), and mailbox.
Referenced by ast_ari_mailboxes_update().
 {
    struct ast_mwi_mailbox_object *mailbox;
    int res = 0;
    mailbox = ast_mwi_mailbox_alloc(name);
    if (!mailbox) {
       return -1;
    }
    ast_mwi_mailbox_set_msgs_new(mailbox, new_messages);
    ast_mwi_mailbox_set_msgs_old(mailbox, old_messages);
    if (ast_mwi_mailbox_update(mailbox)) {
       res = -1;
    }
    ast_mwi_mailbox_unref(mailbox);
    return res;
 }
stasis_app_mailboxes_to_json()
struct ast_json* stasis_app_mailboxes_to_json (void)
brief Convert mailboxes to json array
Returns
JSON representation of the mailboxes
NULL on error.
Definition at line 68 of file res_stasis_mailbox.c.
References ao2_iterator_destroy(), ao2_iterator_init(), ao2_iterator_next, ao2_ref, array(), ast_json_array_append(), ast_json_array_create(), ast_json_unref(), ast_mwi_mailbox_get_all(), ast_mwi_mailbox_unref, mailbox, mailbox_to_json(), mailboxes, and NULL.
Referenced by ast_ari_mailboxes_list().
 {
    struct ast_json *array = ast_json_array_create();
    struct ao2_container *mailboxes;
    struct ao2_iterator iter;
    const struct ast_mwi_mailbox_object *mailbox;
    if (!array) {
       return NULL;
    }
    mailboxes = ast_mwi_mailbox_get_all();
    if (!mailboxes) {
       ast_json_unref(array);
       return NULL;
    }
    iter = ao2_iterator_init(mailboxes, 0);
    for (; (mailbox = ao2_iterator_next(&iter)); ast_mwi_mailbox_unref(mailbox)) {
       struct ast_json *appending = mailbox_to_json(mailbox);
       if (!appending || ast_json_array_append(array, appending)) {
          /* Failed to append individual mailbox to the array. Abort. */
          ast_json_unref(array);
          array = NULL;
          break;
       }
    }
    ao2_iterator_destroy(&iter);
    ao2_ref(mailboxes, -1);
    return array;
 }
unload_module()
static int unload_module (void) static
Definition at line 149 of file res_stasis_mailbox.c.
References AST_MODFLAG_GLOBAL_SYMBOLS, AST_MODULE_INFO(), AST_MODULE_SUPPORT_CORE, ASTERISK_GPL_KEY, and load_module().
 {
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_GLOBAL_SYMBOLS , .description = "Stasis application mailbox support" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .requires = "res_stasis,res_mwi_external" } static
Definition at line 159 of file res_stasis_mailbox.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 159 of file res_stasis_mailbox.c.