Asterisk - The Open Source Telephony Project: astobj2_container_private.h File Reference
astobj2_container_private.h File Reference
Common, private definitions for astobj2 containers.
#include "asterisk/astobj2.h"
Data Structures
struct ao2_container
Generic container type.
struct ao2_container_methods
struct ao2_container_node
Generic container node.
Macros
#define __container_unlink_node(node, flags) __container_unlink_node_debug(node, flags, NULL, __FILE__, __LINE__, __PRETTY_FUNCTION__)
#define AO2_TRAVERSAL_STATE_SIZE 100
Typedefs
typedef struct ao2_container *(* ao2_container_alloc_empty_clone_fn) (struct ao2_container *self, const char *tag, const char *file, int line, const char *func)
Create an empty copy of this container.
typedef void(* ao2_container_destroy_fn) (struct ao2_container *self)
Destroy this container.
typedef void(* ao2_container_display) (struct ao2_container *self, void *where, ao2_prnt_fn *prnt, ao2_prnt_obj_fn *prnt_obj)
Display contents of the specified container.
typedef void(* ao2_container_find_cleanup_fn) (void *v_state)
Cleanup the container traversal state.
typedef struct ao2_container_node *(* ao2_container_find_first_fn) (struct ao2_container *self, enum search_flags flags, void *arg, void *v_state)
Find the first container node in a traversal.
typedef struct ao2_container_node *(* ao2_container_find_next_fn) (struct ao2_container *self, void *v_state, struct ao2_container_node *prev)
Find the next container node in a traversal.
typedef enum ao2_container_insert(* ao2_container_insert_fn) (struct ao2_container *self, struct ao2_container_node *node)
Insert a node into this container.
typedef int(* ao2_container_integrity) (struct ao2_container *self)
Perform an integrity check on the specified container.
typedef struct ao2_container_node *(* ao2_container_new_node_fn) (struct ao2_container *self, void *obj_new, const char *tag, const char *file, int line, const char *func)
Create a new container node.
typedef void(* ao2_container_statistics) (struct ao2_container *self, void *where, ao2_prnt_fn *prnt)
Display statistics of the specified container.
typedef struct ao2_container_node *(* ao2_iterator_next_fn) (struct ao2_container *self, struct ao2_container_node *prev, enum ao2_iterator_flags flags)
Find the next non-empty iteration node in the container.
typedef void(* ao2_link_node_stat_fn) (struct ao2_container *container, struct ao2_container_node *node)
typedef void(* ao2_unlink_node_stat_fn) (struct ao2_container *container, struct ao2_container_node *node)
Enumerations
enum ao2_callback_type { AO2_CALLBACK_DEFAULT, AO2_CALLBACK_WITH_DATA }
enum ao2_container_insert { AO2_CONTAINER_INSERT_NODE_INSERTED, AO2_CONTAINER_INSERT_NODE_OBJ_REPLACED, AO2_CONTAINER_INSERT_NODE_REJECTED }
enum ao2_unlink_node_flags { AO2_UNLINK_NODE_UNLINK_OBJECT = (1 << 0), AO2_UNLINK_NODE_NOUNREF_OBJECT = (1 << 1), AO2_UNLINK_NODE_UNREF_NODE = (1 << 2), AO2_UNLINK_NODE_DEC_COUNT = (1 << 3) }
Functions
int __container_unlink_node_debug (struct ao2_container_node *node, uint32_t flags, const char *tag, const char *file, int line, const char *func)
void container_destruct (void *_c)
int container_init (void)
Detailed Description
Common, private definitions for astobj2 containers.
Author
Richard Mudgett rmudg.nosp@m.ett@.nosp@m.digiu.nosp@m.m.co.nosp@m.m
Definition in file astobj2_container_private.h.
Macro Definition Documentation
__container_unlink_node
#define __container_unlink_node (node, flags) __container_unlink_node_debug(node, flags, NULL, __FILE__, __LINE__, __PRETTY_FUNCTION__)
Definition at line 325 of file astobj2_container_private.h.
Referenced by hash_ao2_node_destructor(), and rb_ao2_node_destructor().
AO2_TRAVERSAL_STATE_SIZE
#define AO2_TRAVERSAL_STATE_SIZE 100
Allow enough room for container specific traversal state structs
Definition at line 60 of file astobj2_container_private.h.
Referenced by internal_ao2_traverse().
Typedef Documentation
ao2_container_alloc_empty_clone_fn
typedef struct ao2_container*(* ao2_container_alloc_empty_clone_fn) (struct ao2_container *self, const char *tag, const char *file, int line, const char *func)
Create an empty copy of this container.
Parameters
self Container to operate upon.
tag used for debugging.
file Debug file name invoked from
line Debug line invoked from
func Debug function name invoked from
Return values
empty-container on success.
NULL on error.
Definition at line 98 of file astobj2_container_private.h.
ao2_container_destroy_fn
typedef void(* ao2_container_destroy_fn) (struct ao2_container *self)
Destroy this container.
Parameters
self Container to operate upon.
Returns
Nothing
Definition at line 84 of file astobj2_container_private.h.
ao2_container_display
typedef void(* ao2_container_display) (struct ao2_container *self, void *where, ao2_prnt_fn *prnt, ao2_prnt_obj_fn *prnt_obj)
Display contents of the specified container.
Parameters
self Container to dump.
where User data needed by prnt to determine where to put output.
prnt Print output callback function to use.
prnt_obj Callback function to print the given object's key. (NULL if not available)
Returns
Nothing
Definition at line 185 of file astobj2_container_private.h.
ao2_container_find_cleanup_fn
typedef void(* ao2_container_find_cleanup_fn) (void *v_state)
Cleanup the container traversal state.
Parameters
v_state Traversal state to cleanup.
Returns
Nothing
Definition at line 158 of file astobj2_container_private.h.
ao2_container_find_first_fn
typedef struct ao2_container_node*(* ao2_container_find_first_fn) (struct ao2_container *self, enum search_flags flags, void *arg, void *v_state)
Find the first container node in a traversal.
Parameters
self Container to operate upon.
flags search_flags to control traversing the container
arg Comparison callback arg parameter.
v_state Traversal state to restart container traversal.
Return values
node-ptr of found node (Reffed).
NULL when no node found.
Definition at line 136 of file astobj2_container_private.h.
ao2_container_find_next_fn
typedef struct ao2_container_node*(* ao2_container_find_next_fn) (struct ao2_container *self, void *v_state, struct ao2_container_node *prev)
Find the next container node in a traversal.
Parameters
self Container to operate upon.
v_state Traversal state to restart container traversal.
prev Previous node returned by the traversal search functions. The ref ownership is passed back to this function.
Return values
node-ptr of found node (Reffed).
NULL when no node found.
Definition at line 149 of file astobj2_container_private.h.
ao2_container_insert_fn
typedef enum ao2_container_insert(* ao2_container_insert_fn) (struct ao2_container *self, struct ao2_container_node *node)
Insert a node into this container.
Parameters
self Container to operate upon.
node Container node to insert into the container.
Returns
enum ao2_container_insert value.
Definition at line 123 of file astobj2_container_private.h.
ao2_container_integrity
typedef int(* ao2_container_integrity) (struct ao2_container *self)
Perform an integrity check on the specified container.
Parameters
self Container to check integrity.
Note
The container is already locked for reading.
Return values
0 on success.
-1 on error.
Definition at line 210 of file astobj2_container_private.h.
ao2_container_new_node_fn
typedef struct ao2_container_node*(* ao2_container_new_node_fn) (struct ao2_container *self, void *obj_new, const char *tag, const char *file, int line, const char *func)
Create a new container node.
Parameters
self Container to operate upon.
obj_new Object to put into the node.
tag used for debugging.
file Debug file name invoked from
line Debug line invoked from
func Debug function name invoked from
Return values
initialized-node on success.
NULL on error.
Definition at line 113 of file astobj2_container_private.h.
ao2_container_statistics
typedef void(* ao2_container_statistics) (struct ao2_container *self, void *where, ao2_prnt_fn *prnt)
Display statistics of the specified container.
Parameters
self Container to display statistics.
where User data needed by prnt to determine where to put output.
prnt Print output callback function to use.
Note
The container is already locked for reading.
Returns
Nothing
Definition at line 198 of file astobj2_container_private.h.
ao2_iterator_next_fn
typedef struct ao2_container_node*(* ao2_iterator_next_fn) (struct ao2_container *self, struct ao2_container_node *prev, enum ao2_iterator_flags flags)
Find the next non-empty iteration node in the container.
Parameters
self Container to operate upon.
prev Previous node returned by the iterator.
flags search_flags to control iterating the container. Only AO2_ITERATOR_DESCENDING is useful by the method.
Note
The container is already locked.
Return values
node on success.
NULL on error or no more nodes in the container.
Definition at line 173 of file astobj2_container_private.h.
ao2_link_node_stat_fn
typedef void(* ao2_link_node_stat_fn) (struct ao2_container *container, struct ao2_container_node *node)
Definition at line 222 of file astobj2_container_private.h.
ao2_unlink_node_stat_fn
typedef void(* ao2_unlink_node_stat_fn) (struct ao2_container *container, struct ao2_container_node *node)
Definition at line 234 of file astobj2_container_private.h.
Enumeration Type Documentation
ao2_callback_type
enum ao2_callback_type
Enumerator
AO2_CALLBACK_DEFAULT
AO2_CALLBACK_WITH_DATA
Definition at line 45 of file astobj2_container_private.h.
{
    AO2_CALLBACK_DEFAULT,
    AO2_CALLBACK_WITH_DATA,
 };
ao2_container_insert
enum ao2_container_insert
Enumerator
AO2_CONTAINER_INSERT_NODE_INSERTED
The node was inserted into the container.
AO2_CONTAINER_INSERT_NODE_OBJ_REPLACED
The node object replaced an existing node object.
AO2_CONTAINER_INSERT_NODE_REJECTED
The node was rejected (duplicate).
Definition at line 50 of file astobj2_container_private.h.
{
    /*! The node was inserted into the container. */
    AO2_CONTAINER_INSERT_NODE_INSERTED,
    /*! The node object replaced an existing node object. */
    AO2_CONTAINER_INSERT_NODE_OBJ_REPLACED,
    /*! The node was rejected (duplicate). */
    AO2_CONTAINER_INSERT_NODE_REJECTED,
 };
ao2_unlink_node_flags
enum ao2_unlink_node_flags
Enumerator
AO2_UNLINK_NODE_UNLINK_OBJECT
Remove the node from the object's weak link list OR unref the object if it's a strong reference.
AO2_UNLINK_NODE_NOUNREF_OBJECT
Modified unlink_object to skip the unref of the object.
AO2_UNLINK_NODE_UNREF_NODE
Unref the node.
AO2_UNLINK_NODE_DEC_COUNT
Decrement the container's element count.
Definition at line 33 of file astobj2_container_private.h.
{
    /*! Remove the node from the object's weak link list
     * OR unref the object if it's a strong reference. */
    AO2_UNLINK_NODE_UNLINK_OBJECT = (1 << 0),
    /*! Modified unlink_object to skip the unref of the object. */
    AO2_UNLINK_NODE_NOUNREF_OBJECT = (1 << 1),
    /*! Unref the node. */
    AO2_UNLINK_NODE_UNREF_NODE = (1 << 2),
    /*! Decrement the container's element count. */
    AO2_UNLINK_NODE_DEC_COUNT = (1 << 3),
 };
Function Documentation
__container_unlink_node_debug()
int __container_unlink_node_debug (struct ao2_container_node * node, uint32_t flags, const char * tag, const char * file, int line, const char * func)
Definition at line 39 of file astobj2_container.c.
References __ao2_ref(), ao2_ref, AO2_UNLINK_NODE_DEC_COUNT, AO2_UNLINK_NODE_NOUNREF_OBJECT, AO2_UNLINK_NODE_UNLINK_OBJECT, AO2_UNLINK_NODE_UNREF_NODE, ast_atomic_fetchadd_int(), container, ao2_container::elements, ao2_container_node::my_container, NULL, ao2_container_node::obj, and ao2_container::v_table.
Referenced by __ao2_iterator_next(), and internal_ao2_traverse().
 {
    struct ao2_container *container = node->my_container;
    if (container == NULL && (flags & AO2_UNLINK_NODE_DEC_COUNT)) {
       return 0;
    }
    if ((flags & AO2_UNLINK_NODE_UNLINK_OBJECT)
       && !(flags & AO2_UNLINK_NODE_NOUNREF_OBJECT)) {
       __ao2_ref(node->obj, -1, tag ?: "Remove obj from container", file, line, func);
    }
    node->obj = NULL;
    if (flags & AO2_UNLINK_NODE_DEC_COUNT) {
       ast_atomic_fetchadd_int(&container->elements, -1);
 #if defined(AO2_DEBUG)
       {
          int empty = container->nodes - container->elements;
          if (container->max_empty_nodes < empty) {
             container->max_empty_nodes = empty;
          }
          if (container->v_table->unlink_stat) {
             container->v_table->unlink_stat(container, node);
          }
       }
 #endif   /* defined(AO2_DEBUG) */
    }
    if (flags & AO2_UNLINK_NODE_UNREF_NODE) {
       /* Remove node from container */
       ao2_ref(node, -1);
    }
    return 1;
 }
container_destruct()
void container_destruct (void * _c)
Definition at line 635 of file astobj2_container.c.
References ao2_t_callback, ast_atomic_fetchadd_int(), ao2_container_methods::destroy, ao2_container::destroying, NULL, OBJ_MULTIPLE, OBJ_NODATA, OBJ_UNLINK, and ao2_container::v_table.
Referenced by __ao2_container_alloc_hash(), and __ao2_container_alloc_rbtree().
 {
    struct ao2_container *c = _c;
    /* Unlink any stored objects in the container. */
    c->destroying = 1;
    ao2_t_callback(c, OBJ_UNLINK | OBJ_NODATA | OBJ_MULTIPLE, NULL, NULL,
       "container_destruct called");
    /* Perform any extra container cleanup. */
    if (c->v_table && c->v_table->destroy) {
       c->v_table->destroy(c);
    }
 #if defined(AO2_DEBUG)
    ast_atomic_fetchadd_int(&ao2.total_containers, -1);
 #endif
 }
container_init()
int container_init (void)
Definition at line 1183 of file astobj2_container.c.
References AO2_ALLOC_OPT_LOCK_RWLOCK, AO2_CONTAINER_ALLOC_OPT_DUPS_REPLACE, ao2_t_container_alloc_list, ARRAY_LEN, ast_cli_register_multiple, ast_register_cleanup(), and NULL.
Referenced by astobj2_init().
 {
 #if defined(AO2_DEBUG)
    reg_containers = ao2_t_container_alloc_list(AO2_ALLOC_OPT_LOCK_RWLOCK,
       AO2_CONTAINER_ALLOC_OPT_DUPS_REPLACE, ao2_reg_sort_cb, NULL,
       "Container registration container.");
    if (!reg_containers) {
       return -1;
    }
    ast_cli_register_multiple(cli_astobj2, ARRAY_LEN(cli_astobj2));
    ast_register_cleanup(container_cleanup);
 #endif   /* defined(AO2_DEBUG) */
    return 0;
 }