Asterisk - The Open Source Telephony Project: format_g719.c File Reference
format_g719.c File Reference
Module: Media File Formats
ITU G.719 , 64kbps bitrate only.
#include "asterisk.h"
#include "asterisk/mod_format.h"
#include "asterisk/module.h"
#include "asterisk/endian.h"
#include "asterisk/format_cache.h"
Macros
#define BUF_SIZE 160 /* 20 milliseconds == 160 bytes, 960 samples */
#define BYTES_TO_SAMPLES(x) ((typeof(x)) x * ((float) 960 / 160))
#define SAMPLES_TO_BYTES(x) ((typeof(x)) x / ((float) 960 / 160))
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static struct ast_frame * g719read (struct ast_filestream *s, int *whennext)
static int g719seek (struct ast_filestream *fs, off_t sample_offset, int whence)
static off_t g719tell (struct ast_filestream *fs)
static int g719trunc (struct ast_filestream *fs)
static int g719write (struct ast_filestream *fs, struct ast_frame *f)
static int load_module (void)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "ITU G.719" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_APP_DEPEND }
static const struct ast_module_info * ast_module_info = &__mod_info
static struct ast_format_def g719_f
Detailed Description
ITU G.719 , 64kbps bitrate only.
File name extensions: g719
Definition in file format_g719.c.
Macro Definition Documentation
BUF_SIZE
#define BUF_SIZE 160 /* 20 milliseconds == 160 bytes, 960 samples */
Definition at line 37 of file format_g719.c.
Referenced by g719read().
BYTES_TO_SAMPLES
#define BYTES_TO_SAMPLES (x) ((typeof(x)) x * ((float) 960 / 160))
Definition at line 39 of file format_g719.c.
Referenced by g719read(), and g719tell().
SAMPLES_TO_BYTES
#define SAMPLES_TO_BYTES (x) ((typeof(x)) x / ((float) 960 / 160))
Definition at line 38 of file format_g719.c.
Referenced by g719seek().
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 158 of file format_g719.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 158 of file format_g719.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 158 of file format_g719.c.
g719read()
static struct ast_frame* g719read (struct ast_filestream * s, int * whennext) static
Definition at line 41 of file format_g719.c.
References ast_format_get_name(), AST_FRAME_SET_BUFFER, AST_FRIENDLY_OFFSET, ast_log, ast_filestream::buf, BUF_SIZE, BYTES_TO_SAMPLES, ast_frame::data, ast_frame::datalen, errno, ast_filestream::f, ast_frame_subclass::format, ast_filestream::fr, LOG_WARNING, NULL, ast_frame::ptr, ast_frame::samples, and ast_frame::subclass.
 {
    size_t res;
    /* Send a frame from the file to the appropriate channel */
    AST_FRAME_SET_BUFFER(&s->fr, s->buf, AST_FRIENDLY_OFFSET, BUF_SIZE);
    if ((res = fread(s->fr.data.ptr, 1, s->fr.datalen, s->f)) != s->fr.datalen) {
       if (res) {
          ast_log(LOG_WARNING, "Short read of %s data (expected %d bytes, read %zu): %s\n",
                ast_format_get_name(s->fr.subclass.format), s->fr.datalen, res,
                strerror(errno));
       }
       return NULL;
    }
    *whennext = s->fr.samples = BYTES_TO_SAMPLES(res);
    return &s->fr;
 }
g719seek()
static int g719seek (struct ast_filestream * fs, off_t sample_offset, int whence) static
Definition at line 70 of file format_g719.c.
References ast_log, AST_LOG_WARNING, errno, ast_filestream::f, max, min, ast_frame::offset, SAMPLES_TO_BYTES, and SEEK_FORCECUR.
 {
    off_t offset = 0, min = 0, cur, max;
    sample_offset = SAMPLES_TO_BYTES(sample_offset);
    if ((cur = ftello(fs->f)) < 0) {
       ast_log(AST_LOG_WARNING, "Unable to determine current position in g719 filestream %p: %s\n", fs, strerror(errno));
       return -1;
    }
    if (fseeko(fs->f, 0, SEEK_END) < 0) {
       ast_log(AST_LOG_WARNING, "Unable to seek to end of g719 filestream %p: %s\n", fs, strerror(errno));
       return -1;
    }
    if ((max = ftello(fs->f)) < 0) {
       ast_log(AST_LOG_WARNING, "Unable to determine max position in g719 filestream %p: %s\n", fs, strerror(errno));
       return -1;
    }
    if (whence == SEEK_SET)
       offset = sample_offset;
    else if (whence == SEEK_CUR || whence == SEEK_FORCECUR)
       offset = sample_offset + cur;
    else if (whence == SEEK_END)
       offset = max - sample_offset;
    if (whence != SEEK_FORCECUR)
       offset = (offset > max) ? max : offset;
    /* always protect against seeking past begining. */
    offset = (offset < min) ? min : offset;
    return fseeko(fs->f, offset, SEEK_SET);
 }
g719tell()
static off_t g719tell (struct ast_filestream * fs) static
Definition at line 123 of file format_g719.c.
References BYTES_TO_SAMPLES, and ast_filestream::f.
 {
    return BYTES_TO_SAMPLES(ftello(fs->f));
 }
g719trunc()
static int g719trunc (struct ast_filestream * fs) static
Definition at line 107 of file format_g719.c.
References ast_log, AST_LOG_WARNING, errno, and ast_filestream::f.
 {
    int fd;
    off_t cur;
    if ((fd = fileno(fs->f)) < 0) {
       ast_log(AST_LOG_WARNING, "Unable to determine file descriptor for g719 filestream %p: %s\n", fs, strerror(errno));
       return -1;
    }
    if ((cur = ftello(fs->f)) < 0) {
       ast_log(AST_LOG_WARNING, "Unable to determine current position in g719 filestream %p: %s\n", fs, strerror(errno));
       return -1;
    }
    return ftruncate(fd, cur);
 }
g719write()
static int g719write (struct ast_filestream * fs, struct ast_frame * f) static
Definition at line 59 of file format_g719.c.
References ast_log, ast_frame::data, ast_frame::datalen, errno, ast_filestream::f, LOG_WARNING, and ast_frame::ptr.
 {
    int res;
    if ((res = fwrite(f->data.ptr, 1, f->datalen, fs->f)) != f->datalen) {
       ast_log(LOG_WARNING, "Bad write (%d/%d): %s\n", res, f->datalen, strerror(errno));
       return -1;
    }
    return 0;
 }
load_module()
static int load_module (void) static
Definition at line 139 of file format_g719.c.
References ast_format_def_register, ast_format_g719, AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, and ast_format_def::format.
Referenced by unload_module().
 {
    g719_f.format = ast_format_g719;
    if (ast_format_def_register(&g719_f))
       return AST_MODULE_LOAD_DECLINE;
    return AST_MODULE_LOAD_SUCCESS;
 }
unload_module()
static int unload_module (void) static
Definition at line 148 of file format_g719.c.
References ast_format_def_unregister(), AST_MODFLAG_LOAD_ORDER, AST_MODPRI_APP_DEPEND, AST_MODULE_INFO(), AST_MODULE_SUPPORT_CORE, ASTERISK_GPL_KEY, load_module(), and ast_format_def::name.
 {
    return ast_format_def_unregister(g719_f.name);
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "ITU G.719" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_APP_DEPEND } static
Definition at line 158 of file format_g719.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 158 of file format_g719.c.
g719_f
struct ast_format_def g719_f static
Definition at line 128 of file format_g719.c.