Asterisk - The Open Source Telephony Project: chanwr.c File Reference
chanwr.c File Reference
#include <stdlib.h>
#include "f2c.h"
Functions
int chanrd_ (integer *order, integer *ipitv, integer *irms, integer *irc, integer *ibits)
int chanwr_ (integer *order, integer *ipitv, integer *irms, integer *irc, integer *ibits, struct lpc10_encoder_state *st)
int chanwr_0_ (int n__, integer *order, integer *ipitv, integer *irms, integer *irc, integer *ibits, struct lpc10_encoder_state *st)
Function Documentation
chanrd_()
int chanrd_ (integer * order, integer * ipitv, integer * irms, integer * irc, integer * ibits)
Definition at line 229 of file chanwr.c.
References chanwr_0_(), and NULL.
Referenced by lpc10_decode().
 {
     return chanwr_0_(1, order, ipitv, irms, irc, ibits, NULL);
     }
chanwr_()
int chanwr_ (integer * order, integer * ipitv, integer * irms, integer * irc, integer * ibits, struct lpc10_encoder_state * st)
Definition at line 223 of file chanwr.c.
References chanwr_0_().
Referenced by lpc10_encode().
 {
     return chanwr_0_(0, order, ipitv, irms, irc, ibits, st);
     }
chanwr_0_()
int chanwr_0_ (int n__, integer * order, integer * ipitv, integer * irms, integer * irc, integer * ibits, struct lpc10_encoder_state * st)
Definition at line 132 of file chanwr.c.
References lpc10_encoder_state::isync, and order.
Referenced by chanrd_(), and chanwr_().
 {
     /* Initialized data */
     integer *isync;
     static integer bit[10] = { 2,4,8,8,8,8,16,16,16,16 };
     static integer iblist[53] = { 13,12,11,1,2,13,12,11,1,2,13,10,11,2,1,10,
        13,12,11,10,2,13,12,11,10,2,1,12,7,6,1,10,9,8,7,4,6,9,8,7,5,1,9,8,
        4,6,1,5,9,8,7,5,6 };
     /* System generated locals */
     integer i__1;
     /* Local variables */
     integer itab[13], i__;
 /*       Arguments */
 /*       Parameters/constants */
 /*       These arrays are not Fortran PARAMETER's, but they are defined */
 /*       by DATA statements below, and their contents are never altered.
 */
 /*       Local variables that need not be saved */
 /*       Local state */
 /*       ISYNC is only used by CHANWR, not by ENTRY CHANRD. */
     /* Parameter adjustments */
     --irc;
     --ibits;
     /* Function Body */
     switch(n__) {
    case 1: goto L_chanrd;
    }
     isync = &(st->isync);
 /* ***********************************************************************
  */
 /*    Place quantized parameters into bitstream */
 /* ***********************************************************************
  */
 /*   Place parameters into ITAB */
     itab[0] = *ipitv;
     itab[1] = *irms;
     itab[2] = 0;
     i__1 = *order;
     for (i__ = 1; i__ <= i__1; ++i__) {
    itab[i__ + 2] = irc[*order + 1 - i__] & 32767;
     }
 /*   Put 54 bits into IBITS array */
     for (i__ = 1; i__ <= 53; ++i__) {
    ibits[i__] = itab[iblist[i__ - 1] - 1] & 1;
    itab[iblist[i__ - 1] - 1] /= 2;
     }
     ibits[54] = *isync & 1;
     *isync = 1 - *isync;
     return 0;
 /* ***********************************************************************
  */
 /*    Reconstruct parameters from bitstream */
 /* ***********************************************************************
  */
 L_chanrd:
 /*   Reconstruct ITAB */
     for (i__ = 1; i__ <= 13; ++i__) {
    itab[i__ - 1] = 0;
     }
     for (i__ = 1; i__ <= 53; ++i__) {
    itab[iblist[54 - i__ - 1] - 1] = (itab[iblist[54 - i__ - 1] - 1] << 1)
        + ibits[54 - i__];
     }
 /*   Sign extend RC's */
     i__1 = *order;
     for (i__ = 1; i__ <= i__1; ++i__) {
    if ((itab[i__ + 2] & bit[i__ - 1]) != 0) {
        itab[i__ + 2] -= bit[i__ - 1] << 1;
    }
     }
 /*   Restore variables */
     *ipitv = itab[0];
     *irms = itab[1];
     i__1 = *order;
     for (i__ = 1; i__ <= i__1; ++i__) {
    irc[i__] = itab[*order + 4 - i__ - 1];
     }
     return 0;
 } /* chanwr_ */