Asterisk - The Open Source Telephony Project: adsi_funcs Struct Reference
adsi_funcs Struct Reference
#include <adsi.h>
Data Fields
int(* available)(struct ast_channel *chan)
int(* begin_download)(struct ast_channel *chan, char *service, unsigned char *fdn, unsigned char *sec, int version)
int(* channel_restore)(struct ast_channel *chan)
int(* clear_screen)(unsigned char *buf)
int(* clear_soft_keys)(unsigned char *buf)
int(* connect_session)(unsigned char *buf, unsigned char *fdn, int ver)
int(* data_mode)(unsigned char *buf)
int(* disconnect_session)(unsigned char *buf)
int(* display)(unsigned char *buf, int page, int line, int just, int wrap, char *col1, char *col2)
int(* download_connect)(unsigned char *buf, char *service, unsigned char *fdn, unsigned char *sec, int ver)
int(* download_disconnect)(unsigned char *buf)
int(* end_download)(struct ast_channel *chan)
int(* get_cpeid)(struct ast_channel *chan, unsigned char *cpeid, int voice)
int(* get_cpeinfo)(struct ast_channel *chan, int *width, int *height, int *buttons, int voice)
int(* input_control)(unsigned char *buf, int page, int line, int display, int format, int just)
int(* input_format)(unsigned char *buf, int num, int dir, int wrap, char *format1, char *format2)
int(* load_session)(struct ast_channel *chan, unsigned char *app, int ver, int data)
int(* load_soft_key)(unsigned char *buf, int key, const char *llabel, const char *slabel, char *ret, int data)
int(* print)(struct ast_channel *chan, char **lines, int *align, int voice)
int(* query_cpeid)(unsigned char *buf)
int(* query_cpeinfo)(unsigned char *buf)
int(* read_encoded_dtmf)(struct ast_channel *chan, unsigned char *buf, int maxlen)
int(* set_keys)(unsigned char *buf, unsigned char *keys)
int(* set_line)(unsigned char *buf, int page, int line)
int(* transmit_message)(struct ast_channel *chan, unsigned char *msg, int msglen, int msgtype)
int(* transmit_message_full)(struct ast_channel *chan, unsigned char *msg, int msglen, int msgtype, int dowait)
int(* unload_session)(struct ast_channel *chan)
unsigned int version
int(* voice_mode)(unsigned char *buf, int when)
Detailed Description
Definition at line 345 of file adsi.h.
Field Documentation
available
int(* available) (struct ast_channel *chan)
Definition at line 368 of file adsi.h.
Referenced by ast_adsi_available().
begin_download
int(* begin_download) (struct ast_channel *chan, char *service, unsigned char *fdn, unsigned char *sec, int version)
Definition at line 347 of file adsi.h.
Referenced by ast_adsi_begin_download().
channel_restore
int(* channel_restore) (struct ast_channel *chan)
Definition at line 349 of file adsi.h.
Referenced by ast_adsi_channel_restore().
clear_screen
int(* clear_screen) (unsigned char *buf)
Definition at line 366 of file adsi.h.
Referenced by ast_adsi_clear_screen().
clear_soft_keys
int(* clear_soft_keys) (unsigned char *buf)
Definition at line 365 of file adsi.h.
Referenced by ast_adsi_clear_soft_keys().
connect_session
int(* connect_session) (unsigned char *buf, unsigned char *fdn, int ver)
Definition at line 356 of file adsi.h.
Referenced by ast_adsi_connect_session().
data_mode
int(* data_mode) (unsigned char *buf)
Definition at line 364 of file adsi.h.
Referenced by ast_adsi_data_mode().
disconnect_session
int(* disconnect_session) (unsigned char *buf)
Definition at line 362 of file adsi.h.
Referenced by ast_adsi_disconnect_session().
display
int(* display) (unsigned char *buf, int page, int line, int just, int wrap, char *col1, char *col2)
Definition at line 369 of file adsi.h.
Referenced by ast_adsi_display().
download_connect
int(* download_connect) (unsigned char *buf, char *service, unsigned char *fdn, unsigned char *sec, int ver)
Definition at line 361 of file adsi.h.
Referenced by ast_adsi_download_connect().
download_disconnect
int(* download_disconnect) (unsigned char *buf)
Definition at line 363 of file adsi.h.
Referenced by ast_adsi_download_disconnect().
end_download
int(* end_download) (struct ast_channel *chan)
Definition at line 348 of file adsi.h.
Referenced by ast_adsi_end_download().
get_cpeid
int(* get_cpeid) (struct ast_channel *chan, unsigned char *cpeid, int voice)
Definition at line 359 of file adsi.h.
Referenced by ast_adsi_get_cpeid().
get_cpeinfo
int(* get_cpeinfo) (struct ast_channel *chan, int *width, int *height, int *buttons, int voice)
Definition at line 360 of file adsi.h.
Referenced by ast_adsi_get_cpeinfo().
input_control
int(* input_control) (unsigned char *buf, int page, int line, int display, int format, int just)
Definition at line 373 of file adsi.h.
Referenced by ast_adsi_input_control().
input_format
int(* input_format) (unsigned char *buf, int num, int dir, int wrap, char *format1, char *format2)
Definition at line 374 of file adsi.h.
Referenced by ast_adsi_input_format().
load_session
int(* load_session) (struct ast_channel *chan, unsigned char *app, int ver, int data)
Definition at line 351 of file adsi.h.
Referenced by ast_adsi_load_session().
load_soft_key
int(* load_soft_key) (unsigned char *buf, int key, const char *llabel, const char *slabel, char *ret, int data)
Definition at line 371 of file adsi.h.
Referenced by ast_adsi_load_soft_key().
print
int(* print) (struct ast_channel *chan, char **lines, int *align, int voice)
Definition at line 350 of file adsi.h.
Referenced by ast_adsi_print().
query_cpeid
int(* query_cpeid) (unsigned char *buf)
Definition at line 357 of file adsi.h.
Referenced by ast_adsi_query_cpeid().
query_cpeinfo
int(* query_cpeinfo) (unsigned char *buf)
Definition at line 358 of file adsi.h.
Referenced by ast_adsi_query_cpeinfo().
read_encoded_dtmf
int(* read_encoded_dtmf) (struct ast_channel *chan, unsigned char *buf, int maxlen)
Definition at line 355 of file adsi.h.
Referenced by ast_adsi_read_encoded_dtmf().
set_keys
int(* set_keys) (unsigned char *buf, unsigned char *keys)
Definition at line 372 of file adsi.h.
Referenced by ast_adsi_set_keys().
set_line
int(* set_line) (unsigned char *buf, int page, int line)
Definition at line 370 of file adsi.h.
Referenced by ast_adsi_set_line().
transmit_message
int(* transmit_message) (struct ast_channel *chan, unsigned char *msg, int msglen, int msgtype)
Definition at line 353 of file adsi.h.
Referenced by ast_adsi_transmit_message().
transmit_message_full
int(* transmit_message_full) (struct ast_channel *chan, unsigned char *msg, int msglen, int msgtype, int dowait)
Definition at line 354 of file adsi.h.
Referenced by ast_adsi_transmit_message_full().
unload_session
int(* unload_session) (struct ast_channel *chan)
Definition at line 352 of file adsi.h.
Referenced by ast_adsi_unload_session().
version
unsigned int version
Definition at line 346 of file adsi.h.
Referenced by ast_adsi_install_funcs(), and ParsingContext::next().
voice_mode
int(* voice_mode) (unsigned char *buf, int when)
Definition at line 367 of file adsi.h.
Referenced by ast_adsi_voice_mode().
The documentation for this struct was generated from the following file:
adsi.h