Asterisk - The Open Source Telephony Project: bridge_after.c File Reference
bridge_after.c File Reference
After Bridge Execution API.
#include "asterisk.h"
#include "asterisk/logger.h"
#include "asterisk/channel.h"
#include "asterisk/pbx.h"
#include "asterisk/bridge_after.h"
Data Structures
struct after_bridge_cb_ds
struct after_bridge_cb_node
struct after_bridge_goto_ds
Functions
static void __after_bridge_set_goto (struct ast_channel *chan, int run_h_exten, int specific, const char *context, const char *exten, int priority, const char *parseable_goto)
static void after_bridge_cb_destroy (void *data)
static void after_bridge_cb_failed (struct after_bridge_cb_node *node)
static struct after_bridge_cb_ds * after_bridge_cb_find (struct ast_channel *chan)
static void after_bridge_cb_fixup (void *data, struct ast_channel *old_chan, struct ast_channel *new_chan)
static void after_bridge_cb_run_discard (struct after_bridge_cb_ds *after_bridge, enum ast_bridge_after_cb_reason reason)
static struct after_bridge_cb_ds * after_bridge_cb_setup (struct ast_channel *chan)
static void after_bridge_goto_destroy (void *data)
static void after_bridge_goto_fixup (void *data, struct ast_channel *old_chan, struct ast_channel *new_chan)
static struct ast_datastore * after_bridge_goto_remove (struct ast_channel *chan)
const char * ast_bridge_after_cb_reason_string (enum ast_bridge_after_cb_reason reason)
Get a string representation of an after bridge callback reason.
void ast_bridge_discard_after_callback (struct ast_channel *chan, enum ast_bridge_after_cb_reason reason)
Run discarding any after bridge callbacks.
void ast_bridge_discard_after_goto (struct ast_channel *chan)
Discard channel after bridge goto location.
void ast_bridge_read_after_goto (struct ast_channel *chan, char *buffer, size_t buf_size)
Read after bridge goto if it exists.
void ast_bridge_run_after_callback (struct ast_channel *chan)
Run any after bridge callback.
void ast_bridge_run_after_goto (struct ast_channel *chan)
Run a PBX on any after bridge goto location.
int ast_bridge_set_after_callback (struct ast_channel *chan, ast_bridge_after_cb callback, ast_bridge_after_cb_failed failed, void *data)
Setup an after bridge callback for when the channel leaves the bridging system.
void ast_bridge_set_after_go_on (struct ast_channel *chan, const char *context, const char *exten, int priority, const char *parseable_goto)
Set channel to go on in the dialplan after the bridge.
void ast_bridge_set_after_goto (struct ast_channel *chan, const char *context, const char *exten, int priority)
Set channel to goto specific location after the bridge.
void ast_bridge_set_after_h (struct ast_channel *chan, const char *context)
Set channel to run the h exten after the bridge.
int ast_bridge_setup_after_goto (struct ast_channel *chan)
Setup any after bridge goto location to begin execution.
Variables
static const struct ast_datastore_info after_bridge_cb_info
static const struct ast_datastore_info after_bridge_goto_info
Detailed Description
After Bridge Execution API.
Author
Richard Mudgett rmudg.nosp@m.ett@.nosp@m.digiu.nosp@m.m.co.nosp@m.m
See Also:
CREDITS
Definition in file bridge_after.c.
Function Documentation
__after_bridge_set_goto()
static void __after_bridge_set_goto (struct ast_channel * chan, int run_h_exten, int specific, const char * context, const char * exten, int priority, const char * parseable_goto) static
Definition at line 571 of file bridge_after.c.
References ast_assert, ast_bridge_discard_after_goto(), ast_calloc, ast_channel_datastore_add(), ast_channel_lock, ast_channel_unlock, ast_datastore_alloc, ast_datastore_free(), ast_strdup, after_bridge_goto_ds::context, ast_datastore::data, after_bridge_goto_ds::exten, NULL, after_bridge_goto_ds::parseable_goto, priority, after_bridge_goto_ds::priority, after_bridge_goto_ds::run_h_exten, and after_bridge_goto_ds::specific.
Referenced by ast_bridge_set_after_go_on(), ast_bridge_set_after_goto(), and ast_bridge_set_after_h().
 {
    struct ast_datastore *datastore;
    struct after_bridge_goto_ds *after_bridge;
    /* Sanity checks. */
    ast_assert(chan != NULL);
    if (!chan) {
       return;
    }
    if (run_h_exten) {
       ast_assert(run_h_exten && context);
       if (!context) {
          return;
       }
    } else {
       ast_assert(context && exten && 0 < priority);
       if (!context || !exten || priority < 1) {
          return;
       }
    }
    /* Create a new datastore. */
    datastore = ast_datastore_alloc(&after_bridge_goto_info, NULL);
    if (!datastore) {
       return;
    }
    after_bridge = ast_calloc(1, sizeof(*after_bridge));
    if (!after_bridge) {
       ast_datastore_free(datastore);
       return;
    }
    /* Initialize it. */
    after_bridge->parseable_goto = ast_strdup(parseable_goto);
    after_bridge->context = ast_strdup(context);
    after_bridge->exten = ast_strdup(exten);
    after_bridge->priority = priority;
    after_bridge->run_h_exten = run_h_exten ? 1 : 0;
    after_bridge->specific = specific ? 1 : 0;
    datastore->data = after_bridge;
    if ((parseable_goto && !after_bridge->parseable_goto)
       || (context && !after_bridge->context)
       || (exten && !after_bridge->exten)) {
       ast_datastore_free(datastore);
       return;
    }
    /* Put it on the channel replacing any existing one. */
    ast_channel_lock(chan);
    ast_bridge_discard_after_goto(chan);
    ast_channel_datastore_add(chan, datastore);
    ast_channel_unlock(chan);
 }
after_bridge_cb_destroy()
static void after_bridge_cb_destroy (void * data) static
Definition at line 113 of file bridge_after.c.
References after_bridge_cb_find(), after_bridge_cb_run_discard(), AST_BRIDGE_AFTER_CB_REASON_DESTROY, ast_free, AST_LIST_HEAD_DESTROY, after_bridge_cb_ds::callbacks, and after_bridge_cb_node::data.
 {
    struct after_bridge_cb_ds *after_bridge = data;
    after_bridge_cb_run_discard(after_bridge, AST_BRIDGE_AFTER_CB_REASON_DESTROY);
    AST_LIST_HEAD_DESTROY(&after_bridge->callbacks);
    ast_free(after_bridge);
 }
after_bridge_cb_failed()
static void after_bridge_cb_failed (struct after_bridge_cb_node * node) static
Definition at line 67 of file bridge_after.c.
References after_bridge_cb_node::data, after_bridge_cb_node::failed, NULL, and after_bridge_cb_node::reason.
Referenced by after_bridge_cb_run_discard(), and ast_bridge_run_after_callback().
 {
    if (node->failed) {
       node->failed(node->reason, node->data);
       node->failed = NULL;
    }
 }
after_bridge_cb_find()
static struct after_bridge_cb_ds * after_bridge_cb_find (struct ast_channel * chan) static
Definition at line 170 of file bridge_after.c.
References ast_channel_datastore_find(), ast_datastore::data, lock, NULL, and SCOPED_CHANNELLOCK.
Referenced by after_bridge_cb_destroy(), after_bridge_cb_fixup(), ast_bridge_discard_after_callback(), and ast_bridge_run_after_callback().
 {
    struct ast_datastore *datastore;
    SCOPED_CHANNELLOCK(lock, chan);
    datastore = ast_channel_datastore_find(chan, &after_bridge_cb_info, NULL);
    if (!datastore) {
       return NULL;
    }
    return datastore->data;
 }
after_bridge_cb_fixup()
static void after_bridge_cb_fixup (void * data, struct ast_channel * old_chan, struct ast_channel * new_chan) static
Definition at line 136 of file bridge_after.c.
References after_bridge_cb_find(), AST_BRIDGE_AFTER_CB_REASON_MASQUERADE, AST_LIST_LAST, AST_LIST_LOCK, AST_LIST_UNLOCK, after_bridge_cb_ds::callbacks, and after_bridge_cb_node::reason.
 {
    struct after_bridge_cb_ds *after_bridge;
    struct after_bridge_cb_node *node;
    after_bridge = after_bridge_cb_find(new_chan);
    if (!after_bridge) {
       return;
    }
    AST_LIST_LOCK(&after_bridge->callbacks);
    node = AST_LIST_LAST(&after_bridge->callbacks);
    if (node && !node->reason) {
       node->reason = AST_BRIDGE_AFTER_CB_REASON_MASQUERADE;
    }
    AST_LIST_UNLOCK(&after_bridge->callbacks);
 }
after_bridge_cb_run_discard()
static void after_bridge_cb_run_discard (struct after_bridge_cb_ds * after_bridge, enum ast_bridge_after_cb_reason reason) static
Definition at line 85 of file bridge_after.c.
References after_bridge_cb_failed(), ast_free, AST_LIST_LOCK, AST_LIST_REMOVE_HEAD, AST_LIST_UNLOCK, after_bridge_cb_ds::callbacks, after_bridge_cb_node::list, and after_bridge_cb_node::reason.
Referenced by after_bridge_cb_destroy(), and ast_bridge_discard_after_callback().
 {
    struct after_bridge_cb_node *node;
    for (;;) {
       AST_LIST_LOCK(&after_bridge->callbacks);
       node = AST_LIST_REMOVE_HEAD(&after_bridge->callbacks, list);
       AST_LIST_UNLOCK(&after_bridge->callbacks);
       if (!node) {
          break;
       }
       if (!node->reason) {
          node->reason = reason;
       }
       after_bridge_cb_failed(node);
       ast_free(node);
    }
 }
after_bridge_cb_setup()
static struct after_bridge_cb_ds* after_bridge_cb_setup (struct ast_channel * chan) static
Definition at line 192 of file bridge_after.c.
References ast_calloc, ast_channel_datastore_add(), ast_channel_datastore_find(), ast_datastore_alloc, ast_datastore_free(), AST_LIST_HEAD_INIT, after_bridge_cb_ds::callbacks, ast_datastore::data, lock, NULL, and SCOPED_CHANNELLOCK.
Referenced by ast_bridge_set_after_callback().
 {
    struct ast_datastore *datastore;
    struct after_bridge_cb_ds *after_bridge;
    SCOPED_CHANNELLOCK(lock, chan);
    datastore = ast_channel_datastore_find(chan, &after_bridge_cb_info, NULL);
    if (datastore) {
       return datastore->data;
    }
    /* Create a new datastore. */
    datastore = ast_datastore_alloc(&after_bridge_cb_info, NULL);
    if (!datastore) {
       return NULL;
    }
    after_bridge = ast_calloc(1, sizeof(*after_bridge));
    if (!after_bridge) {
       ast_datastore_free(datastore);
       return NULL;
    }
    AST_LIST_HEAD_INIT(&after_bridge->callbacks);
    datastore->data = after_bridge;
    ast_channel_datastore_add(chan, datastore);
    return datastore->data;
 }
after_bridge_goto_destroy()
static void after_bridge_goto_destroy (void * data) static
Definition at line 339 of file bridge_after.c.
References ast_free, after_bridge_goto_ds::context, after_bridge_cb_node::data, after_bridge_goto_ds::exten, and after_bridge_goto_ds::parseable_goto.
 {
    struct after_bridge_goto_ds *after_bridge = data;
    ast_free((char *) after_bridge->parseable_goto);
    ast_free((char *) after_bridge->context);
    ast_free((char *) after_bridge->exten);
    ast_free((char *) after_bridge);
 }
after_bridge_goto_fixup()
static void after_bridge_goto_fixup (void * data, struct ast_channel * old_chan, struct ast_channel * new_chan) static
Definition at line 360 of file bridge_after.c.
References ast_bridge_discard_after_goto().
 {
    /* There can be only one.  Discard any already on the new channel. */
    ast_bridge_discard_after_goto(new_chan);
 }
after_bridge_goto_remove()
static struct ast_datastore* after_bridge_goto_remove (struct ast_channel * chan) static
Definition at line 382 of file bridge_after.c.
References ast_channel_datastore_find(), ast_channel_datastore_remove(), ast_channel_lock, ast_channel_unlock, and NULL.
Referenced by ast_bridge_discard_after_goto(), and ast_bridge_setup_after_goto().
 {
    struct ast_datastore *datastore;
    ast_channel_lock(chan);
    datastore = ast_channel_datastore_find(chan, &after_bridge_goto_info, NULL);
    if (datastore && ast_channel_datastore_remove(chan, datastore)) {
       datastore = NULL;
    }
    ast_channel_unlock(chan);
    return datastore;
 }
ast_bridge_after_cb_reason_string()
const char* ast_bridge_after_cb_reason_string (enum ast_bridge_after_cb_reason reason)
Get a string representation of an after bridge callback reason.
Since
12.0.0
Parameters
reason The reason to interpret to a string
Return values
NULL Unrecognized reason
non-NULL String representation of reason
Definition at line 296 of file bridge_after.c.
References AST_BRIDGE_AFTER_CB_REASON_DEPART, AST_BRIDGE_AFTER_CB_REASON_DESTROY, AST_BRIDGE_AFTER_CB_REASON_IMPART_FAILED, AST_BRIDGE_AFTER_CB_REASON_MASQUERADE, AST_BRIDGE_AFTER_CB_REASON_REMOVED, and AST_BRIDGE_AFTER_CB_REASON_REPLACED.
Referenced by after_bridge_move_channel_fail(), agent_after_bridge_cb_failed(), bridge_after_cb_failed(), and internal_bridge_after_cb().
 {
    switch (reason) {
    case AST_BRIDGE_AFTER_CB_REASON_DESTROY:
       return "Channel destroyed (hungup)";
    case AST_BRIDGE_AFTER_CB_REASON_REPLACED:
       return "Callback was replaced";
    case AST_BRIDGE_AFTER_CB_REASON_MASQUERADE:
       return "Channel masqueraded";
    case AST_BRIDGE_AFTER_CB_REASON_DEPART:
       return "Channel was departed from bridge";
    case AST_BRIDGE_AFTER_CB_REASON_REMOVED:
       return "Callback was removed";
    case AST_BRIDGE_AFTER_CB_REASON_IMPART_FAILED:
       return "Channel failed joining the bridge";
    }
    return "Unknown";
 }
ast_bridge_discard_after_callback()
void ast_bridge_discard_after_callback (struct ast_channel * chan, enum ast_bridge_after_cb_reason reason)
Run discarding any after bridge callbacks.
Since
12.0.0
Parameters
chan Channel to run after bridge callback.
Returns
Nothing
Definition at line 247 of file bridge_after.c.
References after_bridge_cb_find(), and after_bridge_cb_run_discard().
Referenced by ast_bridge_impart(), and bridge_channel_depart_thread().
 {
    struct after_bridge_cb_ds *after_bridge;
    after_bridge = after_bridge_cb_find(chan);
    if (!after_bridge) {
       return;
    }
    after_bridge_cb_run_discard(after_bridge, reason);
 }
ast_bridge_discard_after_goto()
void ast_bridge_discard_after_goto (struct ast_channel * chan)
Discard channel after bridge goto location.
Since
12.0.0
Parameters
chan Channel to discard after bridge goto location.
Note
chan is locked by this function.
Returns
Nothing
Definition at line 396 of file bridge_after.c.
References after_bridge_goto_remove(), and ast_datastore_free().
Referenced by __after_bridge_set_goto(), after_bridge_goto_fixup(), bridge_channel_depart_thread(), feature_blind_transfer(), and func_channel_write_real().
 {
    struct ast_datastore *datastore;
    datastore = after_bridge_goto_remove(chan);
    if (datastore) {
       ast_datastore_free(datastore);
    }
 }
ast_bridge_read_after_goto()
void ast_bridge_read_after_goto (struct ast_channel * chan, char * buffer, size_t buf_size)
Read after bridge goto if it exists.
Since
12.0.0
Parameters
chan Channel to read the after bridge goto parseable goto string from
buffer Buffer to write the after bridge goto data to
buf_size size of the buffer being written to
Definition at line 406 of file bridge_after.c.
References ast_channel_datastore_find(), ast_strlen_zero, after_bridge_goto_ds::context, ast_datastore::data, after_bridge_goto_ds::exten, lock, NULL, after_bridge_goto_ds::parseable_goto, after_bridge_goto_ds::priority, after_bridge_goto_ds::run_h_exten, and SCOPED_CHANNELLOCK.
Referenced by func_channel_read().
 {
    struct ast_datastore *datastore;
    struct after_bridge_goto_ds *after_bridge;
    char *current_pos = buffer;
    size_t remaining_size = buf_size;
    SCOPED_CHANNELLOCK(lock, chan);
    datastore = ast_channel_datastore_find(chan, &after_bridge_goto_info, NULL);
    if (!datastore) {
       buffer[0] = '\0';
       return;
    }
    after_bridge = datastore->data;
    if (after_bridge->parseable_goto) {
       snprintf(buffer, buf_size, "%s", after_bridge->parseable_goto);
       return;
    }
    if (!ast_strlen_zero(after_bridge->context)) {
       snprintf(current_pos, remaining_size, "%s,", after_bridge->context);
       remaining_size = remaining_size - strlen(current_pos);
       current_pos += strlen(current_pos);
    }
    if (after_bridge->run_h_exten) {
       snprintf(current_pos, remaining_size, "h,");
       remaining_size = remaining_size - strlen(current_pos);
       current_pos += strlen(current_pos);
    } else if (!ast_strlen_zero(after_bridge->exten)) {
       snprintf(current_pos, remaining_size, "%s,", after_bridge->exten);
       remaining_size = remaining_size - strlen(current_pos);
       current_pos += strlen(current_pos);
    }
    snprintf(current_pos, remaining_size, "%d", after_bridge->priority);
 }
ast_bridge_run_after_callback()
void ast_bridge_run_after_callback (struct ast_channel * chan)
Run any after bridge callback.
Since
12.0.0
Parameters
chan Channel to run after bridge callback.
Returns
Nothing
Definition at line 220 of file bridge_after.c.
References after_bridge_cb_failed(), after_bridge_cb_find(), ast_free, AST_LIST_LOCK, AST_LIST_REMOVE_HEAD, AST_LIST_UNLOCK, after_bridge_cb_node::callback, after_bridge_cb_ds::callbacks, after_bridge_cb_node::data, after_bridge_cb_node::failed, after_bridge_cb_node::list, NULL, and after_bridge_cb_node::reason.
Referenced by ast_bridge_join(), and bridge_channel_ind_thread().
 {
    struct after_bridge_cb_ds *after_bridge;
    struct after_bridge_cb_node *node;
    after_bridge = after_bridge_cb_find(chan);
    if (!after_bridge) {
       return;
    }
    for (;;) {
       AST_LIST_LOCK(&after_bridge->callbacks);
       node = AST_LIST_REMOVE_HEAD(&after_bridge->callbacks, list);
       AST_LIST_UNLOCK(&after_bridge->callbacks);
       if (!node) {
          break;
       }
       if (node->reason) {
          after_bridge_cb_failed(node);
       } else {
          node->failed = NULL;
          node->callback(chan, node->data);
       }
       ast_free(node);
    }
 }
ast_bridge_run_after_goto()
void ast_bridge_run_after_goto (struct ast_channel * chan)
Run a PBX on any after bridge goto location.
Since
12.0.0
Parameters
chan Channel to execute after bridge goto location.
Note
chan is locked by this function.
Pull off any after bridge goto location datastore and run a PBX at that location.
Note
On return, the chan pointer is no longer valid because the channel has hung up.
Returns
Nothing
Definition at line 537 of file bridge_after.c.
References ast_bridge_setup_after_goto(), ast_hangup(), and ast_pbx_run().
Referenced by bridge_channel_ind_thread().
 {
    int goto_failed;
    goto_failed = ast_bridge_setup_after_goto(chan);
    if (goto_failed || ast_pbx_run(chan)) {
       ast_hangup(chan);
    }
 }
ast_bridge_set_after_callback()
int ast_bridge_set_after_callback (struct ast_channel * chan, ast_bridge_after_cb callback, ast_bridge_after_cb_failed failed, void * data)
Setup an after bridge callback for when the channel leaves the bridging system.
Since
12.0.0
Parameters
chan Channel to setup an after bridge callback on.
callback Function to call when the channel leaves the bridging system.
failed Function to call when it will not be calling the callback.
data Extra data to pass with the callback.
Note
chan is locked by this function.
failed is called when the channel leaves the bridging system or is destroyed.
Return values
0 on success.
-1 on error.
Definition at line 259 of file bridge_after.c.
References after_bridge_cb_setup(), ast_assert, AST_BRIDGE_AFTER_CB_REASON_REPLACED, ast_calloc, AST_LIST_INSERT_TAIL, AST_LIST_LAST, AST_LIST_LOCK, AST_LIST_UNLOCK, after_bridge_cb_node::callback, after_bridge_cb_ds::callbacks, after_bridge_cb_node::data, after_bridge_cb_node::failed, after_bridge_cb_node::list, NULL, and after_bridge_cb_node::reason.
Referenced by add_to_dial_bridge(), bridge_agent_hold_push(), bridge_channel_attended_transfer(), bridge_stasis_push(), control_swap_channel_in_bridge(), and stasis_app_bridge_playback_channel_add().
 {
    struct after_bridge_cb_ds *after_bridge;
    struct after_bridge_cb_node *new_node;
    struct after_bridge_cb_node *last_node;
    /* Sanity checks. */
    ast_assert(chan != NULL);
    if (!chan || !callback) {
       return -1;
    }
    after_bridge = after_bridge_cb_setup(chan);
    if (!after_bridge) {
       return -1;
    }
    /* Create a new callback node. */
    new_node = ast_calloc(1, sizeof(*new_node));
    if (!new_node) {
       return -1;
    }
    new_node->callback = callback;
    new_node->failed = failed;
    new_node->data = data;
    /* Put it in the container disabling any previously active one. */
    AST_LIST_LOCK(&after_bridge->callbacks);
    last_node = AST_LIST_LAST(&after_bridge->callbacks);
    if (last_node && !last_node->reason) {
       last_node->reason = AST_BRIDGE_AFTER_CB_REASON_REPLACED;
    }
    AST_LIST_INSERT_TAIL(&after_bridge->callbacks, new_node, list);
    AST_LIST_UNLOCK(&after_bridge->callbacks);
    return 0;
 }
ast_bridge_set_after_go_on()
void ast_bridge_set_after_go_on (struct ast_channel * chan, const char * context, const char * exten, int priority, const char * parseable_goto)
Set channel to go on in the dialplan after the bridge.
Since
12.0.0
Parameters
chan Channel to setup after bridge goto location.
context Current context of the caller channel.
exten Current exten of the caller channel.
priority Current priority of the caller channel
parseable_goto User specified goto string from dialplan.
Note
chan is locked by this function.
Add a channel datastore to setup the goto location when the channel leaves the bridge and run a PBX from there.
If parseable_goto then use the given context/exten/priority as the relative position for the parseable_goto. Else goto the given context/exten/priority+1.
Returns
Nothing
Definition at line 636 of file bridge_after.c.
References __after_bridge_set_goto(), ast_replace_subargument_delimiter(), ast_strdupa, ast_strlen_zero, and NULL.
Referenced by bridge_exec(), feature_blind_transfer(), func_channel_write_real(), and setup_peer_after_bridge_goto().
 {
    char *p_goto;
    if (!ast_strlen_zero(parseable_goto)) {
       p_goto = ast_strdupa(parseable_goto);
       ast_replace_subargument_delimiter(p_goto);
    } else {
       p_goto = NULL;
    }
    __after_bridge_set_goto(chan, 0, 0, context, exten, priority, p_goto);
 }
ast_bridge_set_after_goto()
void ast_bridge_set_after_goto (struct ast_channel * chan, const char * context, const char * exten, int priority)
Set channel to goto specific location after the bridge.
Since
12.0.0
Parameters
chan Channel to setup after bridge goto location.
context Context to goto after bridge.
exten Exten to goto after bridge.
priority Priority to goto after bridge.
Note
chan is locked by this function.
Add a channel datastore to setup the goto location when the channel leaves the bridge and run a PBX from there.
Returns
Nothing
Definition at line 626 of file bridge_after.c.
References __after_bridge_set_goto(), and NULL.
Referenced by action_bridge().
 {
    __after_bridge_set_goto(chan, 0, 1, context, exten, priority, NULL);
 }
ast_bridge_set_after_h()
void ast_bridge_set_after_h (struct ast_channel * chan, const char * context)
Set channel to run the h exten after the bridge.
Since
12.0.0
Parameters
chan Channel to setup after bridge goto location.
context Context to goto after bridge.
Note
chan is locked by this function.
Add a channel datastore to setup the goto location when the channel leaves the bridge and run a PBX from there.
Returns
Nothing
Definition at line 631 of file bridge_after.c.
References __after_bridge_set_goto(), and NULL.
Referenced by setup_peer_after_bridge_goto().
 {
    __after_bridge_set_goto(chan, 1, 0, context, NULL, 1, NULL);
 }
ast_bridge_setup_after_goto()
int ast_bridge_setup_after_goto (struct ast_channel * chan)
Setup any after bridge goto location to begin execution.
Since
12.0.0
Parameters
chan Channel to setup after bridge goto location.
Note
chan is locked by this function.
Pull off any after bridge goto location datastore and setup for dialplan execution there.
Return values
0 on success. The goto location is set for a PBX to run it.
non-zero on error or no goto location.
Note
If the after bridge goto is set to run an h exten it is run here immediately.
Definition at line 447 of file bridge_after.c.
References after_bridge_goto_remove(), ast_channel_caller(), ast_channel_clear_flag(), ast_channel_clear_softhangup(), ast_channel_context(), ast_channel_context_set(), ast_channel_exten(), ast_channel_exten_set(), ast_channel_flags(), ast_channel_priority(), ast_channel_priority_set(), ast_channel_set_unbridged(), ast_channel_softhangup_internal_flag(), ast_check_hangup(), ast_datastore_free(), ast_debug, ast_exists_extension(), ast_explicit_goto(), AST_FLAG_IN_AUTOLOOP, AST_FLAG_OUTGOING, ast_goto_if_exists(), ast_parseable_goto(), ast_pbx_h_exten_run(), AST_SOFTHANGUP_ASYNCGOTO, ast_strdupa, ast_strlen_zero, ast_test_flag, context, after_bridge_goto_ds::context, ast_datastore::data, exten, after_bridge_goto_ds::exten, NULL, after_bridge_goto_ds::parseable_goto, priority, after_bridge_goto_ds::priority, after_bridge_goto_ds::run_h_exten, S_COR, and after_bridge_goto_ds::specific.
Referenced by app_control_dial(), ast_bridge_join(), ast_bridge_run_after_goto(), bridge_failed_peer_goto(), dial_exec_full(), and internal_bridge_after_cb().
 {
    struct ast_datastore *datastore;
    struct after_bridge_goto_ds *after_bridge;
    int goto_failed = -1;
    /* We are going to be leaving the bridging system now;
     * clear any pending unbridge flags
     */
    ast_channel_set_unbridged(chan, 0);
    /* Determine if we are going to setup a dialplan location and where. */
    if (ast_channel_softhangup_internal_flag(chan) & AST_SOFTHANGUP_ASYNCGOTO) {
       /* An async goto has already setup a location. */
       ast_channel_clear_softhangup(chan, AST_SOFTHANGUP_ASYNCGOTO);
       if (!ast_check_hangup(chan)) {
          goto_failed = 0;
       }
       return goto_failed;
    }
    /* Get after bridge goto datastore. */
    datastore = after_bridge_goto_remove(chan);
    if (!datastore) {
       return goto_failed;
    }
    after_bridge = datastore->data;
    if (after_bridge->run_h_exten) {
       if (ast_exists_extension(chan, after_bridge->context, "h", 1,
          S_COR(ast_channel_caller(chan)->id.number.valid,
             ast_channel_caller(chan)->id.number.str, NULL))) {
          ast_debug(1, "Running after bridge goto h exten %s,h,1\n",
             ast_channel_context(chan));
          ast_pbx_h_exten_run(chan, after_bridge->context);
       }
    } else if (!ast_check_hangup(chan)) {
       /* Clear the outgoing flag */
       ast_channel_clear_flag(chan, AST_FLAG_OUTGOING);
       if (after_bridge->specific) {
          goto_failed = ast_explicit_goto(chan, after_bridge->context,
             after_bridge->exten, after_bridge->priority);
       } else if (!ast_strlen_zero(after_bridge->parseable_goto)) {
          char *context;
          char *exten;
          int priority;
          /* Option F(x) for Bridge(), Dial(), and Queue() */
          /* Save current dialplan location in case of failure. */
          context = ast_strdupa(ast_channel_context(chan));
          exten = ast_strdupa(ast_channel_exten(chan));
          priority = ast_channel_priority(chan);
          /* Set current dialplan position to default dialplan position */
          ast_explicit_goto(chan, after_bridge->context, after_bridge->exten,
             after_bridge->priority);
          /* Then perform the goto */
          goto_failed = ast_parseable_goto(chan, after_bridge->parseable_goto);
          if (goto_failed) {
             /* Restore original dialplan location. */
             ast_channel_context_set(chan, context);
             ast_channel_exten_set(chan, exten);
             ast_channel_priority_set(chan, priority);
          }
       } else {
          /* Option F() for Bridge(), Dial(), and Queue() */
          goto_failed = ast_goto_if_exists(chan, after_bridge->context,
             after_bridge->exten, after_bridge->priority + 1);
       }
       if (!goto_failed) {
          if (ast_test_flag(ast_channel_flags(chan), AST_FLAG_IN_AUTOLOOP)) {
             ast_channel_priority_set(chan, ast_channel_priority(chan) + 1);
          }
          ast_debug(1, "Setup after bridge goto location to %s,%s,%d.\n",
             ast_channel_context(chan),
             ast_channel_exten(chan),
             ast_channel_priority(chan));
       }
    }
    /* Discard after bridge goto datastore. */
    ast_datastore_free(datastore);
    return goto_failed;
 }
Variable Documentation
after_bridge_cb_info
const struct ast_datastore_info after_bridge_cb_info static
Initial value:
= {
   .type = "after-bridge-cb",
   .destroy = after_bridge_cb_destroy,
   .chan_fixup = after_bridge_cb_fixup,
}
Definition at line 154 of file bridge_after.c.
after_bridge_goto_info
const struct ast_datastore_info after_bridge_goto_info static
Initial value:
= {
   .type = "after-bridge-goto",
   .destroy = after_bridge_goto_destroy,
   .chan_fixup = after_bridge_goto_fixup,
}
Definition at line 366 of file bridge_after.c.