Asterisk - The Open Source Telephony Project: app_db.c File Reference
app_db.c File Reference
Dial plan applications
Database access functions.
#include "asterisk.h"
#include "asterisk/file.h"
#include "asterisk/channel.h"
#include "asterisk/pbx.h"
#include "asterisk/module.h"
#include "asterisk/astdb.h"
#include "asterisk/lock.h"
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int deltree_exec (struct ast_channel *chan, const char *data)
static int load_module (void)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Database Access Functions" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, }
static const struct ast_module_info * ast_module_info = &__mod_info
static const char dt_app [] = "DBdeltree"
Detailed Description
Database access functions.
Author
Mark Spencer marks.nosp@m.ter@.nosp@m.digiu.nosp@m.m.co.nosp@m.m
Jefferson Noxon jeff@.nosp@m.debi.nosp@m.an.or.nosp@m.g
Definition in file app_db.c.
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 109 of file app_db.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 109 of file app_db.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 109 of file app_db.c.
deltree_exec()
static int deltree_exec (struct ast_channel * chan, const char * data) static
Definition at line 66 of file app_db.c.
References ast_db_deltree(), ast_debug, ast_strdupa, ast_strlen_zero, ast_verb, and strsep().
Referenced by load_module().
 {
    char *argv, *family, *keytree;
    argv = ast_strdupa(data);
    if (strchr(argv, '/')) {
       family = strsep(&argv, "/");
       keytree = strsep(&argv, "\0");
       if (!family || !keytree) {
          ast_debug(1, "Ignoring; Syntax error in argument\n");
          return 0;
       }
       if (ast_strlen_zero(keytree))
          keytree = 0;
    } else {
       family = argv;
       keytree = 0;
    }
    if (keytree) {
       ast_verb(3, "DBdeltree: family=%s, keytree=%s\n", family, keytree);
    } else {
       ast_verb(3, "DBdeltree: family=%s\n", family);
    }
    if (ast_db_deltree(family, keytree) < 0) {
       ast_verb(3, "DBdeltree: Error deleting key from database.\n");
    }
    return 0;
 }
load_module()
static int load_module (void) static
Definition at line 104 of file app_db.c.
References ast_register_application_xml, deltree_exec(), and dt_app.
 {
    return ast_register_application_xml(dt_app, deltree_exec);
 }
unload_module()
static int unload_module (void) static
Definition at line 99 of file app_db.c.
References ast_unregister_application(), and dt_app.
 {
    return ast_unregister_application(dt_app);
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Database Access Functions" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, } static
Definition at line 109 of file app_db.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 109 of file app_db.c.
dt_app
const char dt_app[] = "DBdeltree" static
Definition at line 64 of file app_db.c.
Referenced by load_module(), and unload_module().