Asterisk - The Open Source Telephony Project: pbx_include.c File Reference
pbx_include.c File Reference
Dialplan context include routines.
#include "asterisk.h"
#include "asterisk/_private.h"
#include "asterisk/pbx.h"
#include "pbx_private.h"
Data Structures
struct ast_include
ast_include: include= support in extensions.conf
Functions
const char * ast_get_include_name (const struct ast_include *inc)
const char * ast_get_include_registrar (const struct ast_include *inc)
struct ast_include * include_alloc (const char *value, const char *registrar)
void include_free (struct ast_include *inc)
const char * include_rname (const struct ast_include *inc)
int include_valid (const struct ast_include *inc)
Detailed Description
Dialplan context include routines.
Author
Corey Farrell git@c.nosp@m.fwar.nosp@m.e.com
Definition in file pbx_include.c.
Function Documentation
ast_get_include_name()
const char* ast_get_include_name (const struct ast_include * inc)
Definition at line 50 of file pbx_include.c.
References ast_include::name, and NULL.
Referenced by ast_context_add_include2(), ast_context_remove_include2(), complete_dialplan_remove_include(), context_merge_incls_swits_igps_other_registrars(), find_matching_priority(), handle_cli_dialplan_save(), lookup_ci(), manager_show_dialplan_helper(), and show_dialplan_helper().
 {
    return inc ? inc->name : NULL;
 }
ast_get_include_registrar()
const char* ast_get_include_registrar (const struct ast_include * inc)
Definition at line 60 of file pbx_include.c.
References NULL, and ast_include::registrar.
Referenced by __ast_context_destroy(), ast_context_remove_include2(), context_merge_incls_swits_igps_other_registrars(), handle_cli_dialplan_save(), manager_show_dialplan_helper(), and show_dialplan_helper().
 {
    return inc ? inc->registrar : NULL;
 }
include_alloc()
struct ast_include* include_alloc (const char * value, const char * registrar)
Allocate and initialize an ast_include.
Definition at line 74 of file pbx_include.c.
References ast_build_timing(), ast_calloc, c, ast_include::hastime, ast_include::name, NULL, ast_include::registrar, ast_include::rname, ast_include::stuff, and ast_include::timing.
Referenced by ast_context_add_include2().
 {
    struct ast_include *new_include;
    char *c;
    int valuebufsz = strlen(value) + 1;
    char *p;
    /* allocate new include structure ... */
    new_include = ast_calloc(1, sizeof(*new_include) + (valuebufsz * 2));
    if (!new_include) {
       return NULL;
    }
    /* Fill in this structure. Use 'p' for assignments, as the fields
     * in the structure are 'const char *'
     */
    p = new_include->stuff;
    new_include->name = p;
    strcpy(p, value);
    p += valuebufsz;
    new_include->rname = p;
    strcpy(p, value);
    /* Strip off timing info, and process if it is there */
    if ((c = strchr(p, ',')) ) {
       *c++ = '\0';
       new_include->hastime = ast_build_timing(&(new_include->timing), c);
    }
    new_include->registrar = registrar;
    return new_include;
 }
include_free()
void include_free (struct ast_include * inc)
Free an ast_include and associated data.
Definition at line 106 of file pbx_include.c.
References ast_destroy_timing(), ast_free, and ast_include::timing.
Referenced by __ast_context_destroy(), __ast_internal_context_destroy(), ast_context_add_include2(), and ast_context_remove_include2().
 {
    ast_destroy_timing(&(inc->timing));
    ast_free(inc);
 }
include_rname()
const char* include_rname (const struct ast_include * inc)
Definition at line 55 of file pbx_include.c.
References NULL, and ast_include::rname.
Referenced by ast_context_verify_includes(), and pbx_find_extension().
 {
    return inc ? inc->rname : NULL;
 }
include_valid()
int include_valid (const struct ast_include * inc)
Definition at line 65 of file pbx_include.c.
References ast_check_timing(), ast_include::hastime, and ast_include::timing.
Referenced by pbx_find_extension().
 {
    if (!inc->hastime) {
       return 1;
    }
    return ast_check_timing(&(inc->timing));
 }