Asterisk - The Open Source Telephony Project: ast_rtp_engine_ice Struct Reference
ast_rtp_engine_ice Struct Reference
Structure that represents the optional ICE support within an RTP engine.
#include <rtp_engine.h>
Data Fields
void(* add_remote_candidate)(struct ast_rtp_instance *instance, const struct ast_rtp_engine_ice_candidate *candidate)
void(* change_components)(struct ast_rtp_instance *instance, int num_components)
struct ao2_container *(* get_local_candidates)(struct ast_rtp_instance *instance)
const char *(* get_password)(struct ast_rtp_instance *instance)
const char *(* get_ufrag)(struct ast_rtp_instance *instance)
void(* ice_lite)(struct ast_rtp_instance *instance)
void(* set_authentication)(struct ast_rtp_instance *instance, const char *ufrag, const char *password)
void(* set_role)(struct ast_rtp_instance *instance, enum ast_rtp_ice_role role)
void(* start)(struct ast_rtp_instance *instance)
void(* stop)(struct ast_rtp_instance *instance)
void(* turn_request)(struct ast_rtp_instance *instance, enum ast_rtp_ice_component_type component, enum ast_transport transport, const char *server, unsigned int port, const char *username, const char *password)
Detailed Description
Structure that represents the optional ICE support within an RTP engine.
Definition at line 485 of file rtp_engine.h.
Field Documentation
add_remote_candidate
void(* add_remote_candidate) (struct ast_rtp_instance *instance, const struct ast_rtp_engine_ice_candidate *candidate)
Callback for adding a remote candidate
Definition at line 489 of file rtp_engine.h.
Referenced by jingle_interpret_ice_udp_transport(), process_ice_attributes(), process_sdp_a_ice(), and rtp_ice_wrap_add_remote_candidate().
change_components
void(* change_components) (struct ast_rtp_instance *instance, int num_components)
Callback to alter the number of ICE components on a session
Definition at line 509 of file rtp_engine.h.
Referenced by rtp_ice_wrap_change_components(), and set_ice_components().
get_local_candidates
struct ao2_container*(* get_local_candidates) (struct ast_rtp_instance *instance)
Callback for getting local candidates
Definition at line 499 of file rtp_engine.h.
Referenced by add_ice_to_sdp(), add_ice_to_stream(), jingle_add_google_candidates_to_transport(), jingle_add_ice_udp_candidates_to_transport(), and rtp_ice_wrap_get_local_candidates().
get_password
const char*(* get_password) (struct ast_rtp_instance *instance)
Callback for getting local password
Definition at line 497 of file rtp_engine.h.
Referenced by add_ice_to_sdp(), add_ice_to_stream(), jingle_add_google_candidates_to_transport(), jingle_add_ice_udp_candidates_to_transport(), and rtp_ice_wrap_get_password().
get_ufrag
const char*(* get_ufrag) (struct ast_rtp_instance *instance)
Callback for getting local username
Definition at line 495 of file rtp_engine.h.
Referenced by add_ice_to_sdp(), add_ice_to_stream(), jingle_add_google_candidates_to_transport(), jingle_add_ice_udp_candidates_to_transport(), jingle_interpret_google_transport(), and rtp_ice_wrap_get_ufrag().
ice_lite
void(* ice_lite) (struct ast_rtp_instance *instance)
Callback for telling the ICE support that it is talking to an ice-lite implementation
Definition at line 501 of file rtp_engine.h.
Referenced by jingle_request(), process_ice_attributes(), process_sdp_a_ice(), and rtp_ice_wrap_ice_lite().
set_authentication
void(* set_authentication) (struct ast_rtp_instance *instance, const char *ufrag, const char *password)
Callback for setting received authentication information
Definition at line 487 of file rtp_engine.h.
Referenced by jingle_interpret_ice_udp_transport(), process_ice_attributes(), process_ice_auth_attrb(), process_sdp_a_ice(), and rtp_ice_wrap_set_authentication().
set_role
void(* set_role) (struct ast_rtp_instance *instance, enum ast_rtp_ice_role role)
Callback for changing our role in negotiation
Definition at line 503 of file rtp_engine.h.
Referenced by process_ice_attributes(), rtp_ice_wrap_set_role(), and start_ice().
start
void(* start) (struct ast_rtp_instance *instance)
Callback for starting ICE negotiation
Definition at line 491 of file rtp_engine.h.
Referenced by jingle_interpret_ice_udp_transport(), process_ice_attributes(), rtp_ice_wrap_start(), and start_ice().
stop
void(* stop) (struct ast_rtp_instance *instance)
Callback for stopping ICE support
Definition at line 493 of file rtp_engine.h.
Referenced by add_ice_to_stream(), create_rtp(), dialog_initialize_rtp(), jingle_enable_video(), jingle_interpret_google_transport(), jingle_new(), jingle_outgoing_hook(), and rtp_ice_wrap_stop().
turn_request
void(* turn_request) (struct ast_rtp_instance *instance, enum ast_rtp_ice_component_type component, enum ast_transport transport, const char *server, unsigned int port, const char *username, const char *password)
Callback for requesting a TURN session
Definition at line 505 of file rtp_engine.h.
Referenced by rtp_ice_wrap_turn_request().
The documentation for this struct was generated from the following file:
rtp_engine.h