Asterisk - The Open Source Telephony Project: channel_internal_api.c File Reference
channel_internal_api.c File Reference
Channel Accessor API.
#include "asterisk.h"
#include <unistd.h>
#include <fcntl.h>
#include "asterisk/alertpipe.h"
#include "asterisk/paths.h"
#include "asterisk/channel.h"
#include "asterisk/channel_internal.h"
#include "asterisk/endpoints.h"
#include "asterisk/indications.h"
#include "asterisk/stasis_channels.h"
#include "asterisk/stasis_endpoints.h"
#include "asterisk/stringfields.h"
#include "asterisk/stream.h"
#include "asterisk/test.h"
#include "asterisk/vector.h"
Data Structures
struct ast_channel
Main Channel structure associated with a channel.
struct ast_channel_id
Channel UniqueId structure.
Macros
#define DEFINE_STRINGFIELD_GETTER_FOR(field)
#define DEFINE_STRINGFIELD_SETTERS_AND_INVALIDATE_FOR(field, publish, assert_on_null, invalidate)
#define DEFINE_STRINGFIELD_SETTERS_FOR(field, assert_on_null)
#define DIALED_CAUSES_BUCKETS 37
Functions
struct ast_channel * __ast_channel_internal_alloc (void(*destructor)(void *obj), const struct ast_assigned_ids *assignedids, const struct ast_channel *requestor, const char *file, int line, const char *function)
static void __init_channel_errno (void)
enum ast_channel_adsicpe ast_channel_adsicpe (const struct ast_channel *chan)
void ast_channel_adsicpe_set (struct ast_channel *chan, enum ast_channel_adsicpe value)
int ast_channel_alert_writable (struct ast_channel *chan)
int ast_channel_alert_write (struct ast_channel *chan)
enum ama_flags ast_channel_amaflags (const struct ast_channel *chan)
void ast_channel_amaflags_set (struct ast_channel *chan, enum ama_flags value)
struct timeval ast_channel_answertime (struct ast_channel *chan)
void ast_channel_answertime_set (struct ast_channel *chan, struct timeval *value)
const char * ast_channel_appl (const struct ast_channel *chan)
void ast_channel_appl_set (struct ast_channel *chan, const char *value)
struct ast_audiohook_list * ast_channel_audiohooks (const struct ast_channel *chan)
void ast_channel_audiohooks_set (struct ast_channel *chan, struct ast_audiohook_list *value)
struct ast_autochan_list * ast_channel_autochans (struct ast_channel *chan)
pthread_t ast_channel_blocker (const struct ast_channel *chan)
void ast_channel_blocker_set (struct ast_channel *chan, pthread_t value)
int ast_channel_blocker_tid (const struct ast_channel *chan)
void ast_channel_blocker_tid_set (struct ast_channel *chan, int value)
const char * ast_channel_blockproc (const struct ast_channel *chan)
void ast_channel_blockproc_set (struct ast_channel *chan, const char *value)
struct ast_party_caller * ast_channel_caller (struct ast_channel *chan)
void ast_channel_caller_set (struct ast_channel *chan, struct ast_party_caller *value)
ast_group_t ast_channel_callgroup (const struct ast_channel *chan)
void ast_channel_callgroup_set (struct ast_channel *chan, ast_group_t value)
ast_callid ast_channel_callid (const struct ast_channel *chan)
void ast_channel_callid_cleanup (struct ast_channel *chan)
void ast_channel_callid_set (struct ast_channel *chan, ast_callid callid)
struct ast_cdr * ast_channel_cdr (const struct ast_channel *chan)
void ast_channel_cdr_set (struct ast_channel *chan, struct ast_cdr *value)
struct ast_party_connected_line * ast_channel_connected (struct ast_channel *chan)
struct ast_party_id ast_channel_connected_effective_id (struct ast_channel *chan)
struct ast_party_connected_line * ast_channel_connected_indicated (struct ast_channel *chan)
void ast_channel_connected_set (struct ast_channel *chan, struct ast_party_connected_line *value)
const char * ast_channel_context (const struct ast_channel *chan)
void ast_channel_context_set (struct ast_channel *chan, const char *value)
struct timeval ast_channel_creationtime (struct ast_channel *chan)
void ast_channel_creationtime_set (struct ast_channel *chan, struct timeval *value)
const char * ast_channel_data (const struct ast_channel *chan)
void ast_channel_data_set (struct ast_channel *chan, const char *value)
struct ast_datastore_list * ast_channel_datastores (struct ast_channel *chan)
struct ast_party_dialed * ast_channel_dialed (struct ast_channel *chan)
int ast_channel_dialed_causes_add (const struct ast_channel *chan, const struct ast_control_pvt_cause_code *cause_code, int datalen)
Add cause code information to the channel.
struct ast_str * ast_channel_dialed_causes_channels (const struct ast_channel *chan)
Retrieve a comma-separated list of channels for which dialed cause information is available.
void ast_channel_dialed_causes_clear (const struct ast_channel *chan)
Clear all cause information from the channel.
struct ast_control_pvt_cause_code * ast_channel_dialed_causes_find (const struct ast_channel *chan, const char *chan_name)
Retrieve a ref-counted cause code information structure.
void ast_channel_dialed_set (struct ast_channel *chan, struct ast_party_dialed *value)
char ast_channel_dtmf_digit_to_emulate (const struct ast_channel *chan)
void ast_channel_dtmf_digit_to_emulate_set (struct ast_channel *chan, char value)
struct timeval * ast_channel_dtmf_tv (struct ast_channel *chan)
void ast_channel_dtmf_tv_set (struct ast_channel *chan, struct timeval *value)
struct ast_frame * ast_channel_dtmff (struct ast_channel *chan)
void ast_channel_dtmff_set (struct ast_channel *chan, struct ast_frame *value)
unsigned int ast_channel_emulate_dtmf_duration (const struct ast_channel *chan)
void ast_channel_emulate_dtmf_duration_set (struct ast_channel *chan, unsigned int value)
const char * ast_channel_exten (const struct ast_channel *chan)
void ast_channel_exten_set (struct ast_channel *chan, const char *value)
int ast_channel_fd (const struct ast_channel *chan, int which)
int ast_channel_fd_add (struct ast_channel *chan, int value)
Add a file descriptor to the channel without a fixed position.
int ast_channel_fd_count (const struct ast_channel *chan)
Retrieve the number of file decriptor positions present on the channel.
int ast_channel_fd_isset (const struct ast_channel *chan, int which)
int ast_channel_fdno (const struct ast_channel *chan)
void ast_channel_fdno_set (struct ast_channel *chan, int value)
unsigned int ast_channel_fin (const struct ast_channel *chan)
void ast_channel_fin_set (struct ast_channel *chan, unsigned int value)
struct ast_flags * ast_channel_flags (struct ast_channel *chan)
int ast_channel_forward_endpoint (struct ast_channel *chan, struct ast_endpoint *endpoint)
Forward channel stasis messages to the given endpoint.
unsigned int ast_channel_fout (const struct ast_channel *chan)
void ast_channel_fout_set (struct ast_channel *chan, unsigned int value)
struct ast_framehook_list * ast_channel_framehooks (const struct ast_channel *chan)
void ast_channel_framehooks_set (struct ast_channel *chan, struct ast_framehook_list *value)
struct ast_generator * ast_channel_generator (const struct ast_channel *chan)
void ast_channel_generator_set (struct ast_channel *chan, struct ast_generator *value)
void * ast_channel_generatordata (const struct ast_channel *chan)
void ast_channel_generatordata_set (struct ast_channel *chan, void *value)
struct ast_stream * ast_channel_get_default_stream (struct ast_channel *chan, enum ast_media_type type)
Retrieve the default stream of a specific media type on a channel.
struct ast_stream_topology * ast_channel_get_stream_topology (const struct ast_channel *chan)
Retrieve the topology of streams on a channel.
void * ast_channel_get_stream_topology_change_source (struct ast_channel *chan)
Retrieve the source that initiated the last stream topology change.
struct ast_hangup_handler_list * ast_channel_hangup_handlers (struct ast_channel *chan)
int ast_channel_hangupcause (const struct ast_channel *chan)
void ast_channel_hangupcause_set (struct ast_channel *chan, int value)
int ast_channel_hold_state (const struct ast_channel *chan)
void ast_channel_hold_state_set (struct ast_channel *chan, int value)
unsigned long ast_channel_insmpl (const struct ast_channel *chan)
void ast_channel_insmpl_set (struct ast_channel *chan, unsigned long value)
ast_alert_status_t ast_channel_internal_alert_flush (struct ast_channel *chan)
ast_alert_status_t ast_channel_internal_alert_read (struct ast_channel *chan)
int ast_channel_internal_alert_readable (struct ast_channel *chan)
int ast_channel_internal_alert_readfd (struct ast_channel *chan)
void ast_channel_internal_alertpipe_clear (struct ast_channel *chan)
void ast_channel_internal_alertpipe_close (struct ast_channel *chan)
int ast_channel_internal_alertpipe_init (struct ast_channel *chan)
void ast_channel_internal_alertpipe_swap (struct ast_channel *chan1, struct ast_channel *chan2)
Swap the interal alertpipe between two channels.
struct ast_bridge * ast_channel_internal_bridge (const struct ast_channel *chan)
struct ast_bridge_channel * ast_channel_internal_bridge_channel (const struct ast_channel *chan)
void ast_channel_internal_bridge_channel_set (struct ast_channel *chan, struct ast_bridge_channel *value)
void ast_channel_internal_bridge_set (struct ast_channel *chan, struct ast_bridge *value)
void ast_channel_internal_cleanup (struct ast_channel *chan)
void ast_channel_internal_copy_linkedid (struct ast_channel *dest, struct ast_channel *source)
Copy the full linkedid channel id structure from one channel to another.
enum ast_channel_error ast_channel_internal_errno (void)
void ast_channel_internal_errno_set (enum ast_channel_error error)
void ast_channel_internal_fd_clear (struct ast_channel *chan, int which)
void ast_channel_internal_fd_clear_all (struct ast_channel *chan)
void ast_channel_internal_fd_set (struct ast_channel *chan, int which, int value)
void ast_channel_internal_finalize (struct ast_channel *chan)
int ast_channel_internal_is_finalized (struct ast_channel *chan)
struct ast_channel * ast_channel_internal_oldest_linkedid (struct ast_channel *a, struct ast_channel *b)
Determine which channel has an older linkedid.
void ast_channel_internal_set_fake_ids (struct ast_channel *chan, const char *uniqueid, const char *linkedid)
Set uniqueid and linkedid string value only (not time)
void ast_channel_internal_set_stream_topology (struct ast_channel *chan, struct ast_stream_topology *topology)
void ast_channel_internal_set_stream_topology_change_source (struct ast_channel *chan, void *change_source)
int ast_channel_internal_setup_topics (struct ast_channel *chan)
void ast_channel_internal_swap_endpoint_forward (struct ast_channel *a, struct ast_channel *b)
Swap endpoint_forward between two channels.
void ast_channel_internal_swap_snapshots (struct ast_channel *a, struct ast_channel *b)
Swap snapshots beteween two channels.
void ast_channel_internal_swap_stream_topology (struct ast_channel *chan1, struct ast_channel *chan2)
void ast_channel_internal_swap_topics (struct ast_channel *a, struct ast_channel *b)
Swap topics beteween two channels.
void ast_channel_internal_swap_uniqueid_and_linkedid (struct ast_channel *a, struct ast_channel *b)
Swap uniqueid and linkedid beteween two channels.
int ast_channel_is_multistream (struct ast_channel *chan)
Determine if a channel is multi-stream capable.
int ast_channel_is_t38_active (struct ast_channel *chan)
This function will check if T.38 is active on the channel.
int ast_channel_is_t38_active_nolock (struct ast_channel *chan)
ast_channel_is_t38_active variant. Use this if the channel is already locked prior to calling.
struct ast_jb * ast_channel_jb (struct ast_channel *chan)
void ast_channel_jb_set (struct ast_channel *chan, struct ast_jb *value)
const char * ast_channel_linkedid (const struct ast_channel *chan)
const char * ast_channel_macrocontext (const struct ast_channel *chan)
void ast_channel_macrocontext_set (struct ast_channel *chan, const char *value)
const char * ast_channel_macroexten (const struct ast_channel *chan)
void ast_channel_macroexten_set (struct ast_channel *chan, const char *value)
int ast_channel_macropriority (const struct ast_channel *chan)
void ast_channel_macropriority_set (struct ast_channel *chan, int value)
struct ast_channel * ast_channel_masq (const struct ast_channel *chan)
void ast_channel_masq_set (struct ast_channel *chan, struct ast_channel *value)
struct ast_channel * ast_channel_masqr (const struct ast_channel *chan)
void ast_channel_masqr_set (struct ast_channel *chan, struct ast_channel *value)
struct ast_channel_monitor * ast_channel_monitor (const struct ast_channel *chan)
void ast_channel_monitor_set (struct ast_channel *chan, struct ast_channel_monitor *value)
void * ast_channel_music_state (const struct ast_channel *chan)
void ast_channel_music_state_set (struct ast_channel *chan, void *value)
struct ast_namedgroups * ast_channel_named_callgroups (const struct ast_channel *chan)
void ast_channel_named_callgroups_set (struct ast_channel *chan, struct ast_namedgroups *value)
struct ast_namedgroups * ast_channel_named_pickupgroups (const struct ast_channel *chan)
void ast_channel_named_pickupgroups_set (struct ast_channel *chan, struct ast_namedgroups *value)
struct ast_format_cap * ast_channel_nativeformats (const struct ast_channel *chan)
void ast_channel_nativeformats_set (struct ast_channel *chan, struct ast_format_cap *value)
struct ast_format * ast_channel_oldwriteformat (struct ast_channel *chan)
unsigned long ast_channel_outsmpl (const struct ast_channel *chan)
void ast_channel_outsmpl_set (struct ast_channel *chan, unsigned long value)
struct ast_pbx * ast_channel_pbx (const struct ast_channel *chan)
void ast_channel_pbx_set (struct ast_channel *chan, struct ast_pbx *value)
ast_group_t ast_channel_pickupgroup (const struct ast_channel *chan)
void ast_channel_pickupgroup_set (struct ast_channel *chan, ast_group_t value)
int ast_channel_priority (const struct ast_channel *chan)
void ast_channel_priority_set (struct ast_channel *chan, int value)
struct ast_format * ast_channel_rawreadformat (struct ast_channel *chan)
struct ast_format * ast_channel_rawwriteformat (struct ast_channel *chan)
struct ast_format * ast_channel_readformat (struct ast_channel *chan)
struct ast_readq_list * ast_channel_readq (struct ast_channel *chan)
struct ast_trans_pvt * ast_channel_readtrans (const struct ast_channel *chan)
void ast_channel_readtrans_set (struct ast_channel *chan, struct ast_trans_pvt *value)
struct ast_party_redirecting * ast_channel_redirecting (struct ast_channel *chan)
struct ast_party_id ast_channel_redirecting_effective_from (struct ast_channel *chan)
struct ast_party_id ast_channel_redirecting_effective_orig (struct ast_channel *chan)
struct ast_party_id ast_channel_redirecting_effective_to (struct ast_channel *chan)
void ast_channel_redirecting_set (struct ast_channel *chan, struct ast_party_redirecting *value)
int ast_channel_rings (const struct ast_channel *chan)
void ast_channel_rings_set (struct ast_channel *chan, int value)
struct ast_sched_context * ast_channel_sched (const struct ast_channel *chan)
void ast_channel_sched_set (struct ast_channel *chan, struct ast_sched_context *value)
char ast_channel_sending_dtmf_digit (const struct ast_channel *chan)
void ast_channel_sending_dtmf_digit_set (struct ast_channel *chan, char value)
struct timeval ast_channel_sending_dtmf_tv (const struct ast_channel *chan)
void ast_channel_sending_dtmf_tv_set (struct ast_channel *chan, struct timeval value)
void ast_channel_set_is_t38_active (struct ast_channel *chan, int is_t38_active)
Sets the is_t38_active flag.
void ast_channel_set_is_t38_active_nolock (struct ast_channel *chan, int is_t38_active)
Variant of ast_channel_set_is_t38_active. Use this if the channel is already locked prior to calling.
void ast_channel_set_oldwriteformat (struct ast_channel *chan, struct ast_format *format)
void ast_channel_set_rawreadformat (struct ast_channel *chan, struct ast_format *format)
void ast_channel_set_rawwriteformat (struct ast_channel *chan, struct ast_format *format)
void ast_channel_set_readformat (struct ast_channel *chan, struct ast_format *format)
struct ast_stream_topology * ast_channel_set_stream_topology (struct ast_channel *chan, struct ast_stream_topology *topology)
Set the topology of streams on a channel.
void ast_channel_set_unbridged (struct ast_channel *chan, int value)
Sets the unbridged flag and queues a NULL frame on the channel to trigger a check by bridge_channel_wait.
void ast_channel_set_unbridged_nolock (struct ast_channel *chan, int value)
Variant of ast_channel_set_unbridged. Use this if the channel is already locked prior to calling.
void ast_channel_set_writeformat (struct ast_channel *chan, struct ast_format *format)
struct ast_channel_snapshot * ast_channel_snapshot (const struct ast_channel *chan)
struct ast_flags * ast_channel_snapshot_segment_flags (struct ast_channel *chan)
void ast_channel_snapshot_set (struct ast_channel *chan, struct ast_channel_snapshot *snapshot)
int ast_channel_softhangup_internal_flag (struct ast_channel *chan)
void ast_channel_softhangup_internal_flag_add (struct ast_channel *chan, int value)
void ast_channel_softhangup_internal_flag_clear (struct ast_channel *chan, int value)
void ast_channel_softhangup_internal_flag_set (struct ast_channel *chan, int value)
enum ast_channel_state ast_channel_state (const struct ast_channel *chan)
void ast_channel_state_set (struct ast_channel *chan, enum ast_channel_state value)
struct ast_filestream * ast_channel_stream (const struct ast_channel *chan)
void ast_channel_stream_set (struct ast_channel *chan, struct ast_filestream *value)
int ast_channel_streamid (const struct ast_channel *chan)
void ast_channel_streamid_set (struct ast_channel *chan, int value)
const struct ast_channel_tech * ast_channel_tech (const struct ast_channel *chan)
void * ast_channel_tech_pvt (const struct ast_channel *chan)
void ast_channel_tech_pvt_set (struct ast_channel *chan, void *value)
void ast_channel_tech_set (struct ast_channel *chan, const struct ast_channel_tech *value)
struct ast_timer * ast_channel_timer (const struct ast_channel *chan)
void ast_channel_timer_set (struct ast_channel *chan, struct ast_timer *value)
void * ast_channel_timingdata (const struct ast_channel *chan)
void ast_channel_timingdata_set (struct ast_channel *chan, void *value)
int ast_channel_timingfd (const struct ast_channel *chan)
void ast_channel_timingfd_set (struct ast_channel *chan, int value)
ast_timing_func_t ast_channel_timingfunc (const struct ast_channel *chan)
void ast_channel_timingfunc_set (struct ast_channel *chan, ast_timing_func_t value)
struct stasis_topic * ast_channel_topic (struct ast_channel *chan)
A topic which publishes the events for a particular channel.
unsigned short ast_channel_transfercapability (const struct ast_channel *chan)
void ast_channel_transfercapability_set (struct ast_channel *chan, unsigned short value)
int ast_channel_unbridged (struct ast_channel *chan)
This function will check if the bridge needs to be re-evaluated due to external changes.
int ast_channel_unbridged_nolock (struct ast_channel *chan)
ast_channel_unbridged variant. Use this if the channel is already locked prior to calling.
const char * ast_channel_uniqueid (const struct ast_channel *chan)
struct varshead * ast_channel_varshead (struct ast_channel *chan)
void ast_channel_varshead_set (struct ast_channel *chan, struct varshead *value)
int ast_channel_visible_indication (const struct ast_channel *chan)
void ast_channel_visible_indication_set (struct ast_channel *chan, int value)
struct ast_filestream * ast_channel_vstream (const struct ast_channel *chan)
void ast_channel_vstream_set (struct ast_channel *chan, struct ast_filestream *value)
int ast_channel_vstreamid (const struct ast_channel *chan)
void ast_channel_vstreamid_set (struct ast_channel *chan, int value)
struct timeval * ast_channel_whentohangup (struct ast_channel *chan)
void ast_channel_whentohangup_set (struct ast_channel *chan, struct timeval *value)
struct ast_format * ast_channel_writeformat (struct ast_channel *chan)
struct ast_trans_pvt * ast_channel_writetrans (const struct ast_channel *chan)
void ast_channel_writetrans_set (struct ast_channel *chan, struct ast_trans_pvt *value)
struct ast_tone_zone * ast_channel_zone (const struct ast_channel *chan)
void ast_channel_zone_set (struct ast_channel *chan, struct ast_tone_zone *value)
static void channel_set_default_streams (struct ast_channel *chan)
static int collect_names_cb (void *obj, void *arg, int flags)
DEFINE_STRINGFIELD_GETTER_FOR (name)
DEFINE_STRINGFIELD_GETTER_FOR (language)
DEFINE_STRINGFIELD_GETTER_FOR (musicclass)
DEFINE_STRINGFIELD_GETTER_FOR (latest_musicclass)
DEFINE_STRINGFIELD_GETTER_FOR (accountcode)
DEFINE_STRINGFIELD_GETTER_FOR (peeraccount)
DEFINE_STRINGFIELD_GETTER_FOR (userfield)
DEFINE_STRINGFIELD_GETTER_FOR (call_forward)
DEFINE_STRINGFIELD_GETTER_FOR (parkinglot)
DEFINE_STRINGFIELD_GETTER_FOR (hangupsource)
DEFINE_STRINGFIELD_GETTER_FOR (dialcontext)
DEFINE_STRINGFIELD_SETTERS_AND_INVALIDATE_FOR (name, 0, 1, AST_CHANNEL_SNAPSHOT_INVALIDATE_BASE)
DEFINE_STRINGFIELD_SETTERS_AND_INVALIDATE_FOR (language, 1, 0, AST_CHANNEL_SNAPSHOT_INVALIDATE_BASE)
DEFINE_STRINGFIELD_SETTERS_AND_INVALIDATE_FOR (accountcode, 1, 0, AST_CHANNEL_SNAPSHOT_INVALIDATE_BASE)
DEFINE_STRINGFIELD_SETTERS_AND_INVALIDATE_FOR (peeraccount, 1, 0, AST_CHANNEL_SNAPSHOT_INVALIDATE_PEER)
DEFINE_STRINGFIELD_SETTERS_AND_INVALIDATE_FOR (userfield, 0, 0, AST_CHANNEL_SNAPSHOT_INVALIDATE_BASE)
DEFINE_STRINGFIELD_SETTERS_AND_INVALIDATE_FOR (hangupsource, 0, 0, AST_CHANNEL_SNAPSHOT_INVALIDATE_HANGUP)
DEFINE_STRINGFIELD_SETTERS_FOR (musicclass, 0)
DEFINE_STRINGFIELD_SETTERS_FOR (latest_musicclass, 0)
DEFINE_STRINGFIELD_SETTERS_FOR (call_forward, 0)
DEFINE_STRINGFIELD_SETTERS_FOR (parkinglot, 0)
DEFINE_STRINGFIELD_SETTERS_FOR (dialcontext, 0)
static int pvt_cause_cmp_fn (void *obj, void *vstr, int flags)
static int pvt_cause_hash_fn (const void *vpc, const int flags)
Variables
static struct ast_threadstorage channel_errno = { .once = PTHREAD_ONCE_INIT , .key_init = __init_channel_errno , .custom_init = NULL , }
static int uniqueint
The monotonically increasing integer counter for channel uniqueids.
Detailed Description
Channel Accessor API.
This file is intended to be the only file that ever accesses the internals of an ast_channel. All other files should use the accessor functions defined here.
Author
Terry Wilson
Definition in file channel_internal_api.c.
Macro Definition Documentation
DEFINE_STRINGFIELD_GETTER_FOR
#define DEFINE_STRINGFIELD_GETTER_FOR (field)
Value:
const char *ast_channel_##field(const struct ast_channel *chan) \
{ \
   return chan->field; \
}
Definition at line 288 of file channel_internal_api.c.
DEFINE_STRINGFIELD_SETTERS_AND_INVALIDATE_FOR
#define DEFINE_STRINGFIELD_SETTERS_AND_INVALIDATE_FOR (field, publish, assert_on_null, invalidate)
Definition at line 252 of file channel_internal_api.c.
DEFINE_STRINGFIELD_SETTERS_FOR
#define DEFINE_STRINGFIELD_SETTERS_FOR (field, assert_on_null)
Definition at line 232 of file channel_internal_api.c.
DIALED_CAUSES_BUCKETS
#define DIALED_CAUSES_BUCKETS 37
Definition at line 1329 of file channel_internal_api.c.
Referenced by __ast_channel_internal_alloc().
Function Documentation
__ast_channel_internal_alloc()
struct ast_channel* __ast_channel_internal_alloc (void(*)(void *obj) destructor, const struct ast_assigned_ids * assignedids, const struct ast_channel * requestor, const char * file, int line, const char * function)
Definition at line 1331 of file channel_internal_api.c.
References __ao2_alloc(), AO2_ALLOC_OPT_LOCK_MUTEX, ao2_container_alloc_hash, ast_atomic_fetchadd_int(), ast_channel_unref, ast_config_AST_SYSTEM_NAME, ast_copy_string(), AST_FLAGS_ALL, AST_MAX_FDS, ast_set_flag, ast_string_field_init, ast_strlen_zero, AST_VECTOR_INIT, ast_channel_id::creation_time, ast_channel_id::creation_unique, ast_channel::dialed_causes, DIALED_CAUSES_BUCKETS, ast_channel::linkedid, NULL, pvt_cause_cmp_fn(), pvt_cause_hash_fn(), tmp(), ast_channel_id::unique_id, ast_channel::uniqueid, and ast_assigned_ids::uniqueid.
Referenced by __ast_channel_alloc_ap(), and __ast_dummy_channel_alloc().
 {
    struct ast_channel *tmp;
    tmp = __ao2_alloc(sizeof(*tmp), destructor,
       AO2_ALLOC_OPT_LOCK_MUTEX, "", file, line, function);
    if (!tmp) {
       return NULL;
    }
    if ((ast_string_field_init(tmp, 128))) {
       return ast_channel_unref(tmp);
    }
    tmp->dialed_causes = ao2_container_alloc_hash(AO2_ALLOC_OPT_LOCK_MUTEX, 0,
       DIALED_CAUSES_BUCKETS, pvt_cause_hash_fn, NULL, pvt_cause_cmp_fn);
    if (!tmp->dialed_causes) {
       return ast_channel_unref(tmp);
    }
    /* set the creation time in the uniqueid */
    tmp->uniqueid.creation_time = time(NULL);
    tmp->uniqueid.creation_unique = ast_atomic_fetchadd_int(&uniqueint, 1);
    /* use provided id or default to historical {system-}time.# format */
    if (assignedids && !ast_strlen_zero(assignedids->uniqueid)) {
       ast_copy_string(tmp->uniqueid.unique_id, assignedids->uniqueid, sizeof(tmp->uniqueid.unique_id));
    } else if (ast_strlen_zero(ast_config_AST_SYSTEM_NAME)) {
       snprintf(tmp->uniqueid.unique_id, sizeof(tmp->uniqueid.unique_id), "%li.%d",
          (long)(tmp->uniqueid.creation_time),
          tmp->uniqueid.creation_unique);
    } else {
       snprintf(tmp->uniqueid.unique_id, sizeof(tmp->uniqueid.unique_id), "%s-%li.%d",
          ast_config_AST_SYSTEM_NAME,
          (long)(tmp->uniqueid.creation_time),
          tmp->uniqueid.creation_unique);
    }
    /* copy linked id from parent channel if known */
    if (requestor) {
       tmp->linkedid = requestor->linkedid;
    } else {
       tmp->linkedid = tmp->uniqueid;
    }
    AST_VECTOR_INIT(&tmp->fds, AST_MAX_FDS);
    /* Force all channel snapshot segments to be created on first use, so we don't have to check if
     * an old snapshot exists.
     */
    ast_set_flag(&tmp->snapshot_segment_flags, AST_FLAGS_ALL);
    return tmp;
 }
__init_channel_errno()
static void __init_channel_errno (void) static
Definition at line 1561 of file channel_internal_api.c.
 {
ast_channel_adsicpe()
enum ast_channel_adsicpe ast_channel_adsicpe (const struct ast_channel * chan)
Definition at line 781 of file channel_internal_api.c.
 {
    return chan->adsicpe;
 }
ast_channel_adsicpe_set()
void ast_channel_adsicpe_set (struct ast_channel * chan, enum ast_channel_adsicpe value)
Definition at line 785 of file channel_internal_api.c.
References value.
Referenced by __adsi_transmit_messages(), adsi_transmit_message_full(), ast_ari_channels_dial(), ast_iax2_new(), AST_TEST_DEFINE(), begin_dial_prerun(), chan_pjsip_new(), channel_do_masquerade(), dahdi_new(), dial_exec_full(), jingle_new(), mgcp_new(), ooh323_new(), ring_entry(), sip_new(), skinny_new(), and unistim_new().
 {
    chan->adsicpe = value;
 }
ast_channel_alert_writable()
int ast_channel_alert_writable (struct ast_channel * chan)
Definition at line 1125 of file channel_internal_api.c.
References ast_alertpipe_writable().
Referenced by __ast_queue_frame().
 {
    return ast_alertpipe_writable(chan->alertpipe);
 }
ast_channel_alert_write()
int ast_channel_alert_write (struct ast_channel * chan)
Definition at line 1110 of file channel_internal_api.c.
References ast_alertpipe_write().
Referenced by __ast_queue_frame(), __ast_read(), and channel_do_masquerade().
 {
    return ast_alertpipe_write(chan->alertpipe);
 }
ast_channel_amaflags()
enum ama_flags ast_channel_amaflags (const struct ast_channel * chan)
Definition at line 406 of file channel_internal_api.c.
Referenced by ast_channel_log(), ast_channel_snapshot_create(), ast_channel_yank(), ast_var_channels_table(), and func_channel_read().
 {
    return chan->amaflags;
 }
ast_channel_amaflags_set()
void ast_channel_amaflags_set (struct ast_channel * chan, enum ama_flags value)
Precondition
chan is locked
Definition at line 411 of file channel_internal_api.c.
References ast_channel_publish_snapshot(), and value.
Referenced by __ast_channel_alloc_ap(), ast_cel_fabricate_channel_from_event(), ast_iax2_new(), AST_TEST_DEFINE(), cdr_write(), dahdi_new(), func_channel_write_real(), mgcp_new(), ooh323_new(), pbx_builtin_setamaflags(), sip_new(), and skinny_new().
 {
    if (chan->amaflags == value) {
       return;
    }
    chan->amaflags = value;
    ast_channel_publish_snapshot(chan);
 }
ast_channel_answertime()
struct timeval ast_channel_answertime (struct ast_channel * chan)
Definition at line 986 of file channel_internal_api.c.
Referenced by ast_channel_get_up_time_ms(), ospfinished_exec(), and set_channel_answer_time().
 {
    return chan->answertime;
 }
ast_channel_answertime_set()
void ast_channel_answertime_set (struct ast_channel * chan, struct timeval * value)
Definition at line 991 of file channel_internal_api.c.
References ast_channel::answertime, and value.
Referenced by set_channel_answer_time().
 {
    chan->answertime = *value;
 }
ast_channel_appl()
const char* ast_channel_appl (const struct ast_channel * chan)
Definition at line 317 of file channel_internal_api.c.
References ast_channel::appl.
Referenced by ast_bridge_transfer_attended(), ast_channel_log(), ast_var_channels_table(), attended_transfer_bridge(), channel_snapshot_dialplan_create(), func_channel_read(), generate_status(), handle_showchan(), pbx_exec(), realtime_exec(), and serialize_showchan().
 {
    return chan->appl;
 }
ast_channel_appl_set()
void ast_channel_appl_set (struct ast_channel * chan, const char * value)
Definition at line 321 of file channel_internal_api.c.
References ast_channel::appl, AST_CHANNEL_SNAPSHOT_INVALIDATE_DIALPLAN, ast_channel_snapshot_invalidate_segment(), and value.
Referenced by ast_cel_fabricate_channel_from_event(), AST_TEST_DEFINE(), begin_dial_prerun(), dial_exec_full(), do_forward(), pbx_exec(), realtime_exec(), and ring_entry().
 {
    chan->appl = value;
    ast_channel_snapshot_invalidate_segment(chan, AST_CHANNEL_SNAPSHOT_INVALIDATE_DIALPLAN);
 }
ast_channel_audiohooks()
struct ast_audiohook_list* ast_channel_audiohooks (const struct ast_channel * chan)
Definition at line 581 of file channel_internal_api.c.
References ast_channel::audiohooks.
Referenced by __ast_read(), ast_audiohook_attach(), ast_audiohook_detach_source(), ast_audiohook_move_all(), ast_audiohook_move_by_source(), ast_audiohook_remove(), ast_audiohook_set_mute(), ast_channel_audiohook_count_by_source(), ast_channel_audiohook_count_by_source_running(), ast_channel_has_audio_frame_or_monitor(), ast_channel_has_hook_requiring_audio(), ast_write_stream(), conf_run(), and destroy_hooks().
 {
    return chan->audiohooks;
 }
ast_channel_audiohooks_set()
void ast_channel_audiohooks_set (struct ast_channel * chan, struct ast_audiohook_list * value)
Definition at line 585 of file channel_internal_api.c.
References ast_channel::audiohooks, and value.
Referenced by __ast_read(), ast_audiohook_attach(), ast_write_stream(), and destroy_hooks().
 {
    chan->audiohooks = value;
 }
ast_channel_autochans()
struct ast_autochan_list* ast_channel_autochans (struct ast_channel * chan)
Definition at line 872 of file channel_internal_api.c.
References ast_channel::autochans.
Referenced by __ast_channel_alloc_ap(), ast_autochan_destroy(), ast_autochan_new_channel(), and ast_autochan_setup().
 {
    return &chan->autochans;
 }
ast_channel_blocker()
pthread_t ast_channel_blocker (const struct ast_channel * chan)
Definition at line 1213 of file channel_internal_api.c.
References ast_channel::blocker.
Referenced by __ast_queue_frame(), ast_softhangup_nolock(), and channel_do_masquerade().
 {
    return chan->blocker;
 }
ast_channel_blocker_set()
void ast_channel_blocker_set (struct ast_channel * chan, pthread_t value)
Definition at line 1217 of file channel_internal_api.c.
References ast_channel::blocker, and value.
 {
    chan->blocker = value;
 }
ast_channel_blocker_tid()
int ast_channel_blocker_tid (const struct ast_channel * chan)
Definition at line 1222 of file channel_internal_api.c.
References ast_channel::blocker_tid.
Referenced by ast_hangup().
 {
    return chan->blocker_tid;
 }
ast_channel_blocker_tid_set()
void ast_channel_blocker_tid_set (struct ast_channel * chan, int value)
Definition at line 1226 of file channel_internal_api.c.
References ast_channel::blocker_tid, and value.
 {
    chan->blocker_tid = value;
 }
ast_channel_blockproc()
const char* ast_channel_blockproc (const struct ast_channel * chan)
Definition at line 326 of file channel_internal_api.c.
References ast_channel::blockproc.
Referenced by ast_hangup(), and serialize_showchan().
 {
    return chan->blockproc;
 }
ast_channel_blockproc_set()
void ast_channel_blockproc_set (struct ast_channel * chan, const char * value)
Definition at line 330 of file channel_internal_api.c.
References ast_channel::blockproc, and value.
 {
    chan->blockproc = value;
 }
ast_channel_caller()
struct ast_party_caller* ast_channel_caller (struct ast_channel * chan)
Definition at line 888 of file channel_internal_api.c.
References ast_channel::caller.
Referenced by __analog_handle_event(), __analog_ss_thread(), __ast_channel_alloc_ap(), __ast_goto_if_exists(), __ast_pbx_run(), _macro_exec(), acf_isexten_exec(), action_meetmelist(), after_bridge_move_channel(), agent_request_exec(), analog_ss_thread(), app_exec(), ast_app_dtget(), ast_ari_channels_dial(), ast_bridge_setup_after_goto(), ast_cel_fabricate_channel_from_event(), ast_channel_destructor(), ast_channel_set_caller(), ast_channel_set_caller_event(), ast_do_pickup(), ast_dummy_channel_destructor(), ast_iax2_new(), ast_pbx_h_exten_run(), ast_set_callerid(), ast_str_retrieve_variable(), AST_TEST_DEFINE(), ast_unreal_call_setup(), ast_var_channels_table(), background_detect_exec(), begin_dial_prerun(), blacklist_read(), bridge_reconfigured_connected_line_update(), callerid_read(), callerid_write(), cb_events(), cc_generic_agent_init(), chan_pjsip_cng_tone_detected(), chan_pjsip_new(), channel_do_masquerade(), channel_snapshot_caller_create(), collect_digits(), console_call(), copy_caller_data(), copy_message(), dahdi_handle_dtmf(), dahdi_handle_event(), dahdi_new(), dial_exec_full(), dial_trunk(), dialog_info_generate_body_content(), disa_exec(), do_forward(), do_immediate_setup(), eval_exten_read(), fax_detect_framehook(), find_matching_endif(), find_matching_endwhile(), findmeexec(), forward_message(), get_pai(), get_rpid(), gosub_exec(), gosub_run(), handle_cli_confbridge_list_item(), handle_cli_misdn_show_channels(), handle_gosub(), handle_setpriority(), handle_showchan(), incoming_in_dialog_request(), isAnsweringMachine(), isexten_function_read(), leave_voicemail(), local_call(), manager_queues_status(), meetme_show_cmd(), mgcp_hangup(), mgcp_new(), mgcp_ss(), minivm_greet_exec(), minivm_notify_exec(), misdn_call(), misdn_hangup(), misdn_new(), misdn_update_caller_id(), misdn_write(), my_handle_dtmf(), onModeChanged(), ooh323_rtp_read(), originate_exec(), ospauth_exec(), osplookup_exec(), oss_call(), oss_new(), park_local_transfer(), parse_oli(), pbx_builtin_background(), pbx_builtin_waitexten(), pbx_outgoing_attempt(), pbx_parseable_goto(), phone_new(), print_bc_info(), privacy_exec(), process_ast_dsp(), process_sdp(), push_callinfo(), queue_connected_line_update(), queue_exec(), readexten_exec(), recalling_enter(), release_chan(), ring_entry(), run_externnotify(), send_callinfo(), serialize_showchan(), setup_env(), setup_privacy_args(), sip_call(), sip_new(), sip_read(), skinny_new(), skinny_newcall(), sla_ring_station(), sms_exec(), socket_process_helper(), start_automixmonitor(), start_automonitor(), state_notify_build_xml(), try_calling(), unistim_new(), unreal_colp_redirect_indicate(), update_connected_line_from_peer(), update_connectedline(), update_initial_connected_line(), valid_exit(), vm_allocate_dh(), vm_authenticate(), wait_for_answer(), waitstream_core(), write_metadata(), and zapateller_exec().
 {
    return &chan->caller;
 }
ast_channel_caller_set()
void ast_channel_caller_set (struct ast_channel * chan, struct ast_party_caller * value)
Definition at line 944 of file channel_internal_api.c.
References AST_CHANNEL_SNAPSHOT_INVALIDATE_CALLER, ast_channel_snapshot_invalidate_segment(), ast_channel::caller, and value.
Referenced by channel_do_masquerade(), dial_trunk(), and sla_ring_station().
 {
    chan->caller = *value;
    ast_channel_snapshot_invalidate_segment(chan, AST_CHANNEL_SNAPSHOT_INVALIDATE_CALLER);
 }
ast_channel_callgroup()
ast_group_t ast_channel_callgroup (const struct ast_channel * chan)
Definition at line 1074 of file channel_internal_api.c.
References ast_channel::callgroup.
Referenced by ast_var_channels_table(), find_channel_by_group(), func_channel_read(), generate_status(), handle_showchan(), and serialize_showchan().
 {
    return chan->callgroup;
 }
ast_channel_callgroup_set()
void ast_channel_callgroup_set (struct ast_channel * chan, ast_group_t value)
Precondition
chan is locked
Definition at line 1078 of file channel_internal_api.c.
References ast_channel::callgroup, and value.
Referenced by chan_pjsip_new(), dahdi_new(), func_channel_write_real(), jingle_new(), mgcp_new(), read_config(), sip_new(), skinny_new(), and unistim_new().
 {
    chan->callgroup = value;
 }
ast_channel_callid()
ast_callid ast_channel_callid (const struct ast_channel * chan)
Definition at line 793 of file channel_internal_api.c.
References ast_channel::callid.
Referenced by __analog_ss_thread(), __ast_pbx_run(), ast_channel_destructor(), ast_unreal_channel_push_to_bridge(), attended_transfer_monitor_thread(), autoservice_run(), bridge_channel_control_thread(), func_channel_read(), handle_showchan(), and request_channel().
 {
    return chan->callid;
 }
ast_channel_callid_cleanup()
void ast_channel_callid_cleanup (struct ast_channel * chan)
Definition at line 1068 of file channel_internal_api.c.
References ast_channel::callid.
Referenced by ast_channel_destructor().
 {
    chan->callid = 0;
 }
ast_channel_callid_set()
void ast_channel_callid_set (struct ast_channel * chan, ast_callid value)
Precondition
chan is locked
Definition at line 797 of file channel_internal_api.c.
References AST_CALLID_BUFFER_LENGTH, ast_callid_strnprint(), ast_channel_name(), ast_debug, ast_test_suite_event_notify, and ast_channel::callid.
Referenced by __ast_pbx_run(), ast_iax2_new(), ast_unreal_channel_push_to_bridge(), ast_unreal_new_channels(), common_recall_channel_setup(), dahdi_new(), iax2_request(), jingle_new(), request_channel(), and sip_new().
 {
    char call_identifier_from[AST_CALLID_BUFFER_LENGTH];
    char call_identifier_to[AST_CALLID_BUFFER_LENGTH];
    call_identifier_from[0] = '\0';
    ast_callid_strnprint(call_identifier_to, sizeof(call_identifier_to), callid);
    if (chan->callid) {
       ast_callid_strnprint(call_identifier_from, sizeof(call_identifier_from), chan->callid);
       ast_debug(3, "Channel Call ID changing from %s to %s\n", call_identifier_from, call_identifier_to);
    }
    chan->callid = callid;
    ast_test_suite_event_notify("CallIDChange",
       "State: CallIDChange\r\n"
       "Channel: %s\r\n"
       "CallID: %s\r\n"
       "PriorCallID: %s",
       ast_channel_name(chan),
       call_identifier_to,
       call_identifier_from);
 }
ast_channel_cdr()
struct ast_cdr* ast_channel_cdr (const struct ast_channel * chan)
Definition at line 589 of file channel_internal_api.c.
References ast_channel::cdr.
Referenced by ast_channel_destructor(), ast_channel_log(), ast_dummy_channel_destructor(), cdr_read_callback(), and cdr_retrieve_time().
 {
    return chan->cdr;
 }
ast_channel_cdr_set()
void ast_channel_cdr_set (struct ast_channel * chan, struct ast_cdr * value)
Definition at line 593 of file channel_internal_api.c.
References ast_channel::cdr, and value.
Referenced by ast_channel_destructor(), ast_dummy_channel_destructor(), custom_log(), load_values_config(), manager_log(), and syslog_log().
 {
    chan->cdr = value;
 }
ast_channel_connected()
struct ast_party_connected_line* ast_channel_connected (struct ast_channel * chan)
Definition at line 892 of file channel_internal_api.c.
References ast_channel::connected.
Referenced by __ast_channel_alloc_ap(), __ast_read(), __ast_request_and_dial(), action_meetmelist(), after_bridge_move_channel(), agent_login_channel_config(), analog_call(), ari_channels_handle_originate_with_id(), ast_ari_channels_dial(), ast_call_forward(), ast_channel_connected_line_macro(), ast_channel_connected_line_sub(), ast_channel_destructor(), ast_channel_set_connected_line(), ast_do_pickup(), ast_dummy_channel_destructor(), ast_unreal_call_setup(), attended_transfer_properties_alloc(), begin_dial_prerun(), channel_do_masquerade(), channel_snapshot_connected_create(), connectedline_read(), connectedline_write(), copy_caller_data(), dahdi_call(), dial_exec_full(), dialog_info_generate_body_content(), do_forward(), findmeexec(), handle_showchan(), iax2_call(), indicate_connected_line(), launch_monitor_thread(), manager_queues_status(), mgcp_call(), ooh323_call(), ooh323_indicate(), park_local_transfer(), pbx_outgoing_attempt(), phone_call(), push_callinfo(), recalling_enter(), retransfer_enter(), ring_entry(), send_callerid_screen(), send_callinfo(), serialize_showchan(), skinny_newcall(), state_notify_build_xml(), try_calling(), unistim_indicate(), unreal_colp_redirect_indicate(), update_config(), update_connectedline(), and wait_for_answer().
 {
    return &chan->connected;
 }
ast_channel_connected_effective_id()
struct ast_party_id ast_channel_connected_effective_id (struct ast_channel * chan)
Definition at line 900 of file channel_internal_api.c.
References ast_party_id_merge().
Referenced by add_rpid(), caller_id_outgoing_request(), caller_id_outgoing_response(), generate_status(), handle_showchan(), initreqprep(), is_colp_update_allowed(), misdn_call(), misdn_get_connected_line(), push_callinfo(), send_callinfo(), set_from_header(), setsubstate(), and update_connectedline().
 {
    return ast_party_id_merge(&chan->connected.id, &chan->connected.priv);
 }
ast_channel_connected_indicated()
struct ast_party_connected_line* ast_channel_connected_indicated (struct ast_channel * chan)
Definition at line 896 of file channel_internal_api.c.
References ast_channel::connected_indicated.
Referenced by __ast_channel_alloc_ap(), after_bridge_move_channel(), ast_channel_destructor(), ast_dummy_channel_destructor(), and indicate_connected_line().
 {
    return &chan->connected_indicated;
 }
ast_channel_connected_set()
void ast_channel_connected_set (struct ast_channel * chan, struct ast_party_connected_line * value)
Definition at line 949 of file channel_internal_api.c.
References AST_CHANNEL_SNAPSHOT_INVALIDATE_CONNECTED, ast_channel_snapshot_invalidate_segment(), ast_channel::connected, and value.
Referenced by channel_do_masquerade().
 {
    chan->connected = *value;
    ast_channel_snapshot_invalidate_segment(chan, AST_CHANNEL_SNAPSHOT_INVALIDATE_CONNECTED);
 }
ast_channel_context()
const char* ast_channel_context (const struct ast_channel * chan)
Definition at line 344 of file channel_internal_api.c.
Referenced by __analog_ss_thread(), __ast_goto_if_exists(), __ast_pbx_run(), _if_exec(), _macro_exec(), _while_exec(), acf_isexten_exec(), action_blind_transfer(), action_bridge(), action_dialplan_exec(), analog_ss_thread(), ast_app_exec_macro(), ast_bridge_setup_after_goto(), ast_call_forward(), ast_cc_call_init(), ast_channel_by_exten_cb(), ast_channel_log(), ast_channel_yank(), ast_pbx_h_exten_run(), ast_str_retrieve_variable(), AST_TEST_DEFINE(), ast_var_channels_table(), ast_waitstream_exten(), background_detect_exec(), blind_transfer_exec(), bridge_exec(), cc_generic_agent_init(), cc_interfaces_datastore_init(), chan_pjsip_cng_tone_detected(), channel_snapshot_dialplan_create(), collect_digits(), common_exec(), conf_run(), console_transfer(), dahdi_handle_dtmf(), dial_exec_full(), dialout(), do_forward(), do_immediate_setup(), eval_exten_read(), expand_gosub_args(), extenspy_exec(), fax_detect_framehook(), feature_blind_transfer(), find_matching_endif(), find_matching_endwhile(), forward_message(), func_channel_read(), func_channel_write_real(), get_cid_name(), get_transfer_context(), gosub_exec(), gosub_run(), goto_exten(), goto_parser(), handle_call_forward(), handle_gosub(), handle_setpriority(), handle_showchan(), iax2_call(), launch_monitor_thread(), leave_voicemail(), log_exec(), lua_pbx_exec(), mgcp_ss(), minivm_greet_exec(), misdn_call(), misdn_hangup(), my_handle_dtmf(), onedigit_goto(), onModeChanged(), ooh323_rtp_read(), pbx_builtin_background(), pbx_builtin_goto(), pbx_builtin_setvar_multiple(), pbx_builtin_waitexten(), pbx_extension_helper(), pbx_parseable_goto(), pickup_exec(), print_bc_info(), process_ast_dsp(), process_sdp(), raise_exception(), readexten_exec(), realtime_exec(), release_chan(), ring_entry(), serialize_showchan(), setsubstate(), setup_env(), setup_peer_after_bridge_goto(), sip_read(), skinny_dialer(), skinny_newcall(), try_calling(), vm_authenticate(), vm_execmain(), vmauthenticate(), and wait_for_answer().
 {
    return chan->context;
 }
ast_channel_context_set()
void ast_channel_context_set (struct ast_channel * chan, const char * value)
Definition at line 348 of file channel_internal_api.c.
References AST_CHANNEL_SNAPSHOT_INVALIDATE_DIALPLAN, ast_channel_snapshot_invalidate_segment(), and ast_copy_string().
Referenced by __ast_channel_alloc_ap(), __ast_request_and_dial(), _macro_exec(), action_dialplan_exec(), alsa_new(), analog_ss_thread(), ari_originate_dial(), ast_add_extension2_lockopt(), ast_bridge_setup_after_goto(), ast_cel_fabricate_channel_from_event(), ast_explicit_goto(), ast_iax2_new(), ast_pbx_h_exten_run(), AST_TEST_DEFINE(), dahdi_new(), dial_exec_full(), dialout(), do_notify(), eval_exten_read(), forward_message(), generic_recall(), gosub_exec(), gosub_run(), handle_gosub(), handle_setcontext(), iax2_call(), jingle_new(), leave_voicemail(), mgcp_new(), minivm_greet_exec(), my_distinctive_ring(), nbs_new(), ooh323_new(), pbx_builtin_background(), pbx_extension_helper(), pbx_outgoing_exec(), phone_new(), read_config(), return_exec(), setsubstate(), sip_new(), and skinny_new().
 {
    ast_copy_string(chan->context, value, sizeof(chan->context));
    ast_channel_snapshot_invalidate_segment(chan, AST_CHANNEL_SNAPSHOT_INVALIDATE_DIALPLAN);
 }
ast_channel_creationtime()
struct timeval ast_channel_creationtime (struct ast_channel * chan)
Definition at line 976 of file channel_internal_api.c.
Referenced by ast_channel_get_duration_ms(), ast_pickup_find_by_group(), AST_TEST_DEFINE(), channel_snapshot_base_create(), extensionstate_update(), find_ringing_channel(), generate_status(), get_device_state_causing_channels(), handle_request_subscribe(), handle_showchan(), ospfinished_exec(), and wait_for_answer().
 {
    return chan->creationtime;
 }
ast_channel_creationtime_set()
void ast_channel_creationtime_set (struct ast_channel * chan, struct timeval * value)
Definition at line 980 of file channel_internal_api.c.
References AST_CHANNEL_SNAPSHOT_INVALIDATE_BASE, ast_channel_snapshot_invalidate_segment(), ast_channel::creationtime, and value.
Referenced by __ast_channel_alloc_ap().
 {
    chan->creationtime = *value;
    ast_channel_snapshot_invalidate_segment(chan, AST_CHANNEL_SNAPSHOT_INVALIDATE_BASE);
 }
ast_channel_data()
const char* ast_channel_data (const struct ast_channel * chan)
Definition at line 334 of file channel_internal_api.c.
References ast_channel::data.
Referenced by ast_channel_log(), ast_var_channels_table(), channel_snapshot_dialplan_create(), func_channel_read(), generate_status(), handle_showchan(), handle_verbose(), pbx_exec(), realtime_exec(), and serialize_showchan().
 {
    return chan->data;
 }
ast_channel_data_set()
void ast_channel_data_set (struct ast_channel * chan, const char * value)
Definition at line 338 of file channel_internal_api.c.
References AST_CHANNEL_SNAPSHOT_INVALIDATE_DIALPLAN, ast_channel_snapshot_invalidate_segment(), ast_channel::data, and value.
Referenced by ast_cel_fabricate_channel_from_event(), AST_TEST_DEFINE(), begin_dial_prerun(), dial_exec_full(), do_forward(), pbx_exec(), realtime_exec(), retrydial_exec(), and ring_entry().
 {
    chan->data = value;
    ast_channel_snapshot_invalidate_segment(chan, AST_CHANNEL_SNAPSHOT_INVALIDATE_DIALPLAN);
 }
ast_channel_datastores()
struct ast_datastore_list* ast_channel_datastores (struct ast_channel * chan)
Definition at line 868 of file channel_internal_api.c.
References ast_channel::datastores.
Referenced by __ast_channel_alloc_ap(), __ast_dummy_channel_alloc(), ast_channel_datastore_add(), ast_channel_datastore_find(), ast_channel_datastore_inherit(), ast_channel_datastore_remove(), ast_channel_destructor(), ast_dummy_channel_destructor(), chan_cleanup(), channel_do_masquerade(), handle_cli_mixmonitor(), and stir_shaken_read().
 {
    return &chan->datastores;
 }
ast_channel_dialed()
struct ast_party_dialed* ast_channel_dialed (struct ast_channel * chan)
Definition at line 904 of file channel_internal_api.c.
References ast_channel::dialed.
Referenced by __ast_channel_alloc_ap(), ast_ari_channels_dial(), ast_cel_fabricate_channel_from_event(), ast_channel_destructor(), ast_dummy_channel_destructor(), ast_iax2_new(), ast_str_retrieve_variable(), AST_TEST_DEFINE(), ast_unreal_call_setup(), ast_var_channels_table(), begin_dial_prerun(), callerid_read(), callerid_write(), chan_pjsip_new(), channel_do_masquerade(), channel_snapshot_caller_create(), dahdi_new(), dial_exec_full(), do_forward(), generate_status(), handle_showchan(), iax2_call(), mgcp_ss(), oss_call(), oss_new(), ring_entry(), serialize_showchan(), setup_env(), sip_new(), wait_for_answer(), and wait_for_digits().
 {
    return &chan->dialed;
 }
ast_channel_dialed_causes_add()
int ast_channel_dialed_causes_add (const struct ast_channel * chan, const struct ast_control_pvt_cause_code * cause_code, int datalen)
Add cause code information to the channel.
Since
11
This function makes use of datastore operations on the channel, so it is important to lock the channel before calling this function. The passed in data is copied and so is still owned by the caller.
Parameters
chan The channel on which to add information
cause_code The cause information to be added to the channel
datalen The total length of the structure since its length is variable
Return values
0 on success
-1 on error
Definition at line 1292 of file channel_internal_api.c.
References ao2_alloc, ao2_find, ao2_link, ao2_ref, ast_control_pvt_cause_code::chan_name, ast_channel::dialed_causes, NULL, OBJ_KEY, OBJ_NODATA, and OBJ_UNLINK.
Referenced by ast_channel_hangupcause_hash_set().
 {
    struct ast_control_pvt_cause_code *ao2_cause_code;
    ao2_find(chan->dialed_causes, cause_code->chan_name, OBJ_KEY | OBJ_UNLINK | OBJ_NODATA);
    ao2_cause_code = ao2_alloc(datalen, NULL);
    if (ao2_cause_code) {
       memcpy(ao2_cause_code, cause_code, datalen);
       ao2_link(chan->dialed_causes, ao2_cause_code);
       ao2_ref(ao2_cause_code, -1);
       return 0;
    } else {
       return -1;
    }
 }
ast_channel_dialed_causes_channels()
struct ast_str* ast_channel_dialed_causes_channels (const struct ast_channel * chan)
Retrieve a comma-separated list of channels for which dialed cause information is available.
Since
11
This function makes use of datastore operations on the channel, so it is important to lock the channel before calling this function.
Parameters
chan The channel from which to retrieve information
Return values
NULL on allocation failure
Pointer to an ast_str object containing the desired information which must be freed
Definition at line 1274 of file channel_internal_api.c.
References ao2_callback, ast_str_create, collect_names_cb(), ast_channel::dialed_causes, and NULL.
Referenced by hangupcause_keys_read().
 {
    struct ast_str *chanlist = ast_str_create(128);
    if (!chanlist) {
       return NULL;
    }
    ao2_callback(chan->dialed_causes, 0, collect_names_cb, &chanlist);
    return chanlist;
 }
ast_channel_dialed_causes_clear()
void ast_channel_dialed_causes_clear (const struct ast_channel * chan)
Clear all cause information from the channel.
Since
11
This function makes use of datastore operations on the channel, so it is important to lock the channel before calling this function.
Parameters
chan The channel from which to clear information
Definition at line 1308 of file channel_internal_api.c.
References ao2_callback, ast_channel::dialed_causes, NULL, OBJ_MULTIPLE, OBJ_NODATA, and OBJ_UNLINK.
Referenced by hangupcause_clear_exec().
 {
    ao2_callback(chan->dialed_causes, OBJ_UNLINK | OBJ_NODATA | OBJ_MULTIPLE, NULL, NULL);
 }
ast_channel_dialed_causes_find()
struct ast_control_pvt_cause_code* ast_channel_dialed_causes_find (const struct ast_channel * chan, const char * chan_name)
Retrieve a ref-counted cause code information structure.
Since
11
This function makes use of datastore operations on the channel, so it is important to lock the channel before calling this function. This function increases the ref count of the returned object, so the calling function must decrease the reference count when it is finished with the object.
Parameters
chan The channel from which to retrieve information
chan_name The name of the channel about which to retrieve information
Return values
NULL on search failure
Pointer to a ref-counted ast_control_pvt_cause_code object containing the desired information
Definition at line 1287 of file channel_internal_api.c.
References ao2_find, ast_channel::dialed_causes, and OBJ_KEY.
Referenced by hangupcause_read().
 {
    return ao2_find(chan->dialed_causes, chan_name, OBJ_KEY);
 }
ast_channel_dialed_set()
void ast_channel_dialed_set (struct ast_channel * chan, struct ast_party_dialed * value)
Definition at line 954 of file channel_internal_api.c.
References AST_CHANNEL_SNAPSHOT_INVALIDATE_CALLER, ast_channel_snapshot_invalidate_segment(), ast_channel::dialed, and value.
Referenced by channel_do_masquerade().
 {
    chan->dialed = *value;
    ast_channel_snapshot_invalidate_segment(chan, AST_CHANNEL_SNAPSHOT_INVALIDATE_CALLER);
 }
ast_channel_dtmf_digit_to_emulate()
char ast_channel_dtmf_digit_to_emulate (const struct ast_channel * chan)
Definition at line 379 of file channel_internal_api.c.
Referenced by __ast_read().
 {
    return chan->dtmf_digit_to_emulate;
 }
ast_channel_dtmf_digit_to_emulate_set()
void ast_channel_dtmf_digit_to_emulate_set (struct ast_channel * chan, char value)
Definition at line 383 of file channel_internal_api.c.
References value.
Referenced by __ast_read().
 {
    chan->dtmf_digit_to_emulate = value;
 }
ast_channel_dtmf_tv()
struct timeval* ast_channel_dtmf_tv (struct ast_channel * chan)
Definition at line 924 of file channel_internal_api.c.
References ast_channel::dtmf_tv.
Referenced by __ast_read(), should_skip_dtmf(), and should_trigger_dtmf_emulating().
 {
    return &chan->dtmf_tv;
 }
ast_channel_dtmf_tv_set()
void ast_channel_dtmf_tv_set (struct ast_channel * chan, struct timeval * value)
Definition at line 964 of file channel_internal_api.c.
References ast_channel::dtmf_tv, and value.
Referenced by __ast_read().
 {
    chan->dtmf_tv = *value;
 }
ast_channel_dtmff()
struct ast_frame* ast_channel_dtmff (struct ast_channel * chan)
Definition at line 880 of file channel_internal_api.c.
References ast_channel::dtmff.
Referenced by __ast_read(), and queue_dtmf_readq().
 {
    return &chan->dtmff;
 }
ast_channel_dtmff_set()
void ast_channel_dtmff_set (struct ast_channel * chan, struct ast_frame * value)
Definition at line 936 of file channel_internal_api.c.
References ast_channel::dtmff, and value.
 {
    chan->dtmff = *value;
 }
ast_channel_emulate_dtmf_duration()
unsigned int ast_channel_emulate_dtmf_duration (const struct ast_channel * chan)
Definition at line 509 of file channel_internal_api.c.
Referenced by __ast_read().
 {
    return chan->emulate_dtmf_duration;
 }
ast_channel_emulate_dtmf_duration_set()
void ast_channel_emulate_dtmf_duration_set (struct ast_channel * chan, unsigned int value)
Definition at line 513 of file channel_internal_api.c.
References value.
Referenced by __ast_read().
 {
    chan->emulate_dtmf_duration = value;
 }
ast_channel_exten()
const char* ast_channel_exten (const struct ast_channel * chan)
Definition at line 353 of file channel_internal_api.c.
Referenced by __ast_goto_if_exists(), __ast_pbx_run(), _if_exec(), _macro_exec(), _while_exec(), action_bridge(), action_dialplan_exec(), ast_app_exec_macro(), ast_bridge_setup_after_goto(), ast_cc_call_init(), ast_channel_by_exten_cb(), ast_channel_log(), ast_channel_yank(), ast_pbx_h_exten_run(), ast_str_retrieve_variable(), AST_TEST_DEFINE(), ast_var_channels_table(), bridge_exec(), cb_events(), cc_generic_agent_init(), cc_interfaces_datastore_init(), chan_pjsip_cng_tone_detected(), channel_snapshot_dialplan_create(), dahdi_handle_dtmf(), dial_exec_full(), do_forward(), do_immediate_setup(), dundi_exec(), dundi_helper(), eval_exten_read(), expand_gosub_args(), fax_detect_framehook(), feature_blind_transfer(), find_matching_endif(), find_matching_endwhile(), forward_message(), func_channel_read(), func_channel_write_real(), get_cid_name(), gosub_exec(), gosub_run(), goto_parser(), handle_cli_misdn_show_channels(), handle_frame(), handle_gosub(), handle_setpriority(), handle_showchan(), launch_monitor_thread(), leave_voicemail(), log_exec(), lua_pbx_exec(), misdn_hangup(), misdn_update_redirecting(), misdn_write(), my_handle_dtmf(), onModeChanged(), ooh323_rtp_read(), ospauth_exec(), pbx_builtin_goto(), pbx_builtin_setvar_multiple(), pbx_builtin_waitexten(), pbx_extension_helper(), pbx_parseable_goto(), print_bc_info(), process_ast_dsp(), process_sdp(), raise_exception(), realtime_exec(), release_chan(), ring_entry(), serialize_showchan(), setup_env(), setup_peer_after_bridge_goto(), setup_privacy_args(), sip_read(), skinny_newcall(), try_calling(), and wait_for_answer().
 {
    return chan->exten;
 }
ast_channel_exten_set()
void ast_channel_exten_set (struct ast_channel * chan, const char * value)
Definition at line 357 of file channel_internal_api.c.
References AST_CHANNEL_SNAPSHOT_INVALIDATE_DIALPLAN, ast_channel_snapshot_invalidate_segment(), and ast_copy_string().
Referenced by __analog_ss_thread(), __ast_channel_alloc_ap(), __ast_request_and_dial(), _macro_exec(), action_dialplan_exec(), alsa_new(), analog_ss_thread(), ari_originate_dial(), ast_add_extension2_lockopt(), ast_bridge_setup_after_goto(), ast_cel_fabricate_channel_from_event(), ast_explicit_goto(), ast_iax2_new(), ast_pbx_h_exten_run(), AST_TEST_DEFINE(), cb_events(), dahdi_new(), dial_exec_full(), dialout(), do_immediate_setup(), do_monitor_headset(), do_notify(), eval_exten_read(), forward_message(), generic_recall(), gosub_exec(), gosub_run(), handle_gosub(), handle_response_cmgr(), handle_setextension(), jingle_new(), leave_voicemail(), mgcp_new(), mgcp_ss(), minivm_greet_exec(), misdn_call(), misdn_digit_end(), misdn_new(), misdn_overlap_dial_task(), nbs_new(), ooh323_new(), pbx_builtin_background(), pbx_extension_helper(), pbx_outgoing_exec(), phone_new(), read_config(), return_exec(), ring_entry(), select_entry(), set_ext_pri(), setsubstate(), sip_new(), skinny_new(), unistim_ss(), and wait_for_answer().
 {
    ast_copy_string(chan->exten, value, sizeof(chan->exten));
    ast_channel_snapshot_invalidate_segment(chan, AST_CHANNEL_SNAPSHOT_INVALIDATE_DIALPLAN);
 }
ast_channel_fd()
int ast_channel_fd (const struct ast_channel * chan, int which)
Definition at line 1186 of file channel_internal_api.c.
References AST_VECTOR_GET, and AST_VECTOR_SIZE.
Referenced by __dahdi_exception(), analog_exception(), ast_channel_fd_isset(), AST_TEST_DEFINE(), ast_waitfor_nandfds(), build_conf(), channel_do_masquerade(), conf_run(), dahdiras_exec(), flash_exec(), meetme_menu_admin_extended(), native_chan_changed(), native_start(), phone_call(), phone_new(), run_ras(), serialize_showchan(), spawn_ras(), and swap_subs().
 {
    return (which >= AST_VECTOR_SIZE(&chan->fds)) ? -1 : AST_VECTOR_GET(&chan->fds, which);
 }
ast_channel_fd_add()
int ast_channel_fd_add (struct ast_channel * chan, int value)
Add a file descriptor to the channel without a fixed position.
Since
15
Parameters
chan The channel to add the file descriptor to
value The file descriptor
Precondition
chan is locked
Returns
The position of the file descriptor
Definition at line 1200 of file channel_internal_api.c.
References ast_channel_fd_isset(), AST_EXTENDED_FDS, and AST_VECTOR_REPLACE.
Referenced by AST_TEST_DEFINE().
 {
    int pos = AST_EXTENDED_FDS;
    while (ast_channel_fd_isset(chan, pos)) {
       pos += 1;
    }
    AST_VECTOR_REPLACE(&chan->fds, pos, value);
    return pos;
 }
ast_channel_fd_count()
int ast_channel_fd_count (const struct ast_channel * chan)
Retrieve the number of file decriptor positions present on the channel.
Since
15
Parameters
chan The channel to get the count of
Precondition
chan is locked
Returns
The number of file descriptor positions
Definition at line 1195 of file channel_internal_api.c.
References AST_VECTOR_SIZE.
Referenced by AST_TEST_DEFINE(), ast_waitfor_nandfds(), and channel_do_masquerade().
 {
    return AST_VECTOR_SIZE(&chan->fds);
 }
ast_channel_fd_isset()
int ast_channel_fd_isset (const struct ast_channel * chan, int which)
Definition at line 1190 of file channel_internal_api.c.
References ast_channel_fd().
Referenced by __ast_read(), and ast_channel_fd_add().
 {
    return ast_channel_fd(chan, which) > -1;
 }
ast_channel_fdno()
int ast_channel_fdno (const struct ast_channel * chan)
Definition at line 419 of file channel_internal_api.c.
Referenced by __ast_read(), ast_settimeout_full(), chan_pjsip_read_stream(), channel_do_masquerade(), hook_event_cb(), jingle_read(), ooh323_rtp_read(), rtp_read(), sip_rtp_read(), skinny_rtp_read(), stasis_app_control_execute_until_exhausted(), stasis_app_exec(), and unistim_rtp_read().
 {
    return chan->fdno;
 }
ast_channel_fdno_set()
void ast_channel_fdno_set (struct ast_channel * chan, int value)
Definition at line 423 of file channel_internal_api.c.
References value.
Referenced by __ast_read(), ast_settimeout_full(), ast_waitfor_nandfds(), channel_do_masquerade(), and read_test().
 {
    chan->fdno = value;
 }
ast_channel_fin()
unsigned int ast_channel_fin (const struct ast_channel * chan)
Definition at line 517 of file channel_internal_api.c.
Referenced by __ast_read(), channel_set_debug(), and serialize_showchan().
 {
    return chan->fin;
 }
ast_channel_fin_set()
void ast_channel_fin_set (struct ast_channel * chan, unsigned int value)
Definition at line 521 of file channel_internal_api.c.
References value.
Referenced by __ast_channel_alloc_ap(), __ast_read(), and channel_set_debug().
 {
    chan->fin = value;
 }
ast_channel_flags()
struct ast_flags* ast_channel_flags (struct ast_channel * chan)
Definition at line 1260 of file channel_internal_api.c.
Referenced by __analog_ss_thread(), __ast_pbx_run(), __ast_queue_frame(), __ast_read(), __ast_request_and_dial(), _macro_exec(), action_bridge(), action_redirect(), agent_request_exec(), analog_ss_thread(), ari_channels_handle_originate_with_id(), ast_async_goto(), ast_audiohook_attach(), ast_autoservice_start(), ast_autoservice_stop(), ast_bridge_channel_playfile(), ast_bridge_join(), ast_bridge_setup_after_goto(), ast_call(), ast_can_pickup(), ast_channel_clear_flag(), ast_channel_defer_dtmf(), ast_channel_destructor(), ast_channel_end_dtmf(), ast_channel_move(), ast_channel_publish_snapshot(), ast_channel_set_flag(), ast_channel_snapshot_create(), ast_channel_stage_snapshot(), ast_channel_stage_snapshot_done(), ast_channel_yank(), ast_explicit_goto(), ast_hangup(), ast_iax2_new(), ast_indicate_data(), ast_pbx_h_exten_run(), ast_raw_answer_with_stream_topology(), ast_readstring_full(), ast_sendtext_data(), ast_setstate(), ast_settimeout_full(), ast_softhangup_nolock(), ast_streamfile(), AST_TEST_DEFINE(), ast_transfer_protocol(), ast_unreal_new_channels(), ast_var_channels_table(), ast_waitfor_nandfds(), ast_waitfordigit_full(), ast_write_stream(), bridge_channel_handle_control(), bridge_channel_internal_join(), bridge_channel_internal_pull(), bridge_impart_internal(), bridge_reconfigured_connected_line_update(), call_forward_inherit(), channel_do_masquerade(), channel_spy(), common_exec(), dahdi_new(), dahdi_read(), deactivate_generator_nolock(), dial_exec_full(), eivr_comm(), gosub_exec(), gosub_run(), handle_exec(), handle_gosub(), limits_interval_playback(), linear_alloc(), local_ast_moh_start(), local_ast_moh_stop(), optimize_lock_chan_stack(), optimize_lock_peer_stack(), pbx_builtin_background(), pbx_outgoing_attempt(), phone_read(), playtones_alloc(), retrydial_exec(), return_exec(), serialize_showchan(), should_skip_dtmf(), should_trigger_dtmf_emulating(), sip_fixup(), sip_new(), sip_peer_hold(), tonepair_alloc(), and waitstream_core().
 {
    return &chan->flags;
 }
ast_channel_forward_endpoint()
int ast_channel_forward_endpoint (struct ast_channel * chan, struct ast_endpoint * endpoint)
Forward channel stasis messages to the given endpoint.
Since
12
Parameters
chan The channel to forward from
endpoint The endpoint to forward to
Return values
0 Success
non-zero Failure
Definition at line 1511 of file channel_internal_api.c.
References ast_assert, ast_channel_topic(), ast_endpoint_topic(), NULL, and stasis_forward_all().
Referenced by ast_endpoint_add_channel().
 {
    ast_assert(chan != NULL);
    ast_assert(endpoint != NULL);
    chan->endpoint_forward =
       stasis_forward_all(ast_channel_topic(chan),
          ast_endpoint_topic(endpoint));
    if (!chan->endpoint_forward) {
       return -1;
    }
    return 0;
 }
ast_channel_fout()
unsigned int ast_channel_fout (const struct ast_channel * chan)
Definition at line 525 of file channel_internal_api.c.
Referenced by ast_write_stream(), channel_set_debug(), and serialize_showchan().
 {
    return chan->fout;
 }
ast_channel_fout_set()
void ast_channel_fout_set (struct ast_channel * chan, unsigned int value)
Definition at line 529 of file channel_internal_api.c.
References value.
Referenced by __ast_channel_alloc_ap(), ast_write_stream(), and channel_set_debug().
 {
    chan->fout = value;
 }
ast_channel_framehooks()
struct ast_framehook_list* ast_channel_framehooks (const struct ast_channel * chan)
Definition at line 705 of file channel_internal_api.c.
References ast_channel::framehooks.
Referenced by __ast_read(), ast_channel_has_audio_frame_or_monitor(), ast_channel_has_hook_requiring_audio(), ast_framehook_attach(), ast_framehook_detach(), ast_framehook_list_destroy(), ast_framehook_list_fixup(), ast_indicate_data(), and ast_write_stream().
 {
    return chan->framehooks;
 }
ast_channel_framehooks_set()
void ast_channel_framehooks_set (struct ast_channel * chan, struct ast_framehook_list * value)
Definition at line 709 of file channel_internal_api.c.
References ast_channel::framehooks, and value.
Referenced by ast_framehook_attach(), and ast_framehook_list_destroy().
 {
    chan->framehooks = value;
 }
ast_channel_generator()
struct ast_generator* ast_channel_generator (const struct ast_channel * chan)
Definition at line 713 of file channel_internal_api.c.
References ast_channel::generator.
Referenced by __ast_read(), ast_activate_generator(), ast_hangup(), ast_openstream_full(), ast_read_generator_actions(), ast_senddigit_end(), ast_senddigit_mf_end(), cb_events(), deactivate_generator_nolock(), deactivate_silence_generator(), generator_force(), generator_write_format_change(), and unreal_queue_frame().
 {
    return chan->generator;
 }
ast_channel_generator_set()
void ast_channel_generator_set (struct ast_channel * chan, struct ast_generator * value)
Definition at line 717 of file channel_internal_api.c.
References ast_channel::generator, and value.
Referenced by ast_activate_generator(), ast_hangup(), and deactivate_generator_nolock().
 {
    chan->generator = value;
 }
ast_channel_generatordata()
void* ast_channel_generatordata (const struct ast_channel * chan)
Definition at line 549 of file channel_internal_api.c.
References ast_channel::generatordata.
Referenced by __ast_read(), ast_activate_generator(), ast_hangup(), ast_read_generator_actions(), ast_tonepair(), ast_write_stream(), cb_events(), deactivate_generator_nolock(), deactivate_silence_generator(), generator_force(), generator_write_format_change(), safe_sleep_conditional(), and set_format().
 {
    return chan->generatordata;
 }
ast_channel_generatordata_set()
void ast_channel_generatordata_set (struct ast_channel * chan, void * value)
Definition at line 553 of file channel_internal_api.c.
References ast_channel::generatordata, and value.
Referenced by __ast_read(), ast_activate_generator(), ast_hangup(), ast_read_generator_actions(), cb_events(), deactivate_generator_nolock(), and generator_force().
 {
    chan->generatordata = value;
 }
ast_channel_get_default_stream()
struct ast_stream* ast_channel_get_default_stream (struct ast_channel * chan, enum ast_media_type type)
Retrieve the default stream of a specific media type on a channel.
Parameters
channel The channel to get the stream from
type The media type of the default stream
Precondition
chan is locked
Return values
non-NULL success
NULL failure
Definition at line 1619 of file channel_internal_api.c.
References ast_assert, AST_MEDIA_TYPE_END, NULL, and type.
Referenced by __ast_read(), ast_unreal_write_stream(), ast_write_stream(), and stream_echo_write_error().
 {
    ast_assert(chan != NULL);
    ast_assert(type < AST_MEDIA_TYPE_END);
    return chan->default_streams[type];
 }
ast_channel_get_stream_topology()
struct ast_stream_topology* ast_channel_get_stream_topology (const struct ast_channel * chan)
Retrieve the topology of streams on a channel.
Parameters
chan The channel to get the stream topology of
Precondition
chan is locked
Return values
non-NULL success
NULL failure
Definition at line 1583 of file channel_internal_api.c.
References ast_assert, and NULL.
Referenced by __ast_read(), ast_bridge_channel_stream_map(), ast_channel_request_stream_topology_change(), AST_TEST_DEFINE(), ast_unreal_indicate(), ast_write_stream(), dial_exec_full(), do_forward(), handle_showchan(), map_source_to_destinations(), native_rtp_bridge_join(), native_rtp_stream_topology_changed(), sfu_topologies_on_join(), sfu_topologies_on_source_change(), simple_bridge_join(), simple_bridge_stream_topology_changed(), softmix_bridge_stream_sources_update(), softmix_bridge_stream_topology_changed(), stream_echo_exec(), stream_echo_write(), and stream_echo_write_error().
 {
    ast_assert(chan != NULL);
    return chan->stream_topology;
 }
ast_channel_get_stream_topology_change_source()
void* ast_channel_get_stream_topology_change_source (struct ast_channel * chan)
Retrieve the source that initiated the last stream topology change.
Parameters
chan The channel
Return values
The channel's stream topology change source
Definition at line 672 of file channel_internal_api.c.
Referenced by native_rtp_stream_topology_changed(), and simple_bridge_stream_topology_changed().
 {
    return chan->stream_topology_change_source;
 }
ast_channel_hangup_handlers()
struct ast_hangup_handler_list* ast_channel_hangup_handlers (struct ast_channel * chan)
Definition at line 864 of file channel_internal_api.c.
References ast_channel::hangup_handlers.
Referenced by ast_pbx_hangup_handler_destroy(), ast_pbx_hangup_handler_init(), ast_pbx_hangup_handler_pop(), ast_pbx_hangup_handler_push(), ast_pbx_hangup_handler_run(), ast_pbx_hangup_handler_show(), and channel_do_masquerade().
 {
    return &chan->hangup_handlers;
 }
ast_channel_hangupcause()
int ast_channel_hangupcause (const struct ast_channel * chan)
Definition at line 427 of file channel_internal_api.c.
Referenced by __transmit_response(), ast_cc_call_failed(), ast_channel_softhangup_withcause_locked(), ast_queue_hangup_with_cause(), ast_str_retrieve_variable(), ast_unreal_call_setup(), ast_unreal_hangup(), ast_var_channels_table(), bridge_channel_dissolve_check(), chan_pjsip_hangup(), chan_pjsip_session_end(), channel_set_cause(), channel_snapshot_hangup_create(), dahdi_hangup(), dahdi_indicate(), dial_bridge_after_cb(), dial_exec_full(), handle_request_bye(), handle_request_cancel(), iax2_hangup(), jingle_hangup(), misdn_hangup(), monitor_dial(), ooh323_hangup(), pbx_builtin_hangup(), retrans_pkt(), rfc3326_add_reason_header(), session_inv_on_tsx_state_changed(), setsubstate(), sip_hangup(), try_calling(), unistim_hangup(), use_reason_header(), and wait_for_answer().
 {
    return chan->hangupcause;
 }
ast_channel_hangupcause_set()
void ast_channel_hangupcause_set (struct ast_channel * chan, int value)
Definition at line 431 of file channel_internal_api.c.
References AST_CHANNEL_SNAPSHOT_INVALIDATE_HANGUP, ast_channel_snapshot_invalidate_segment(), and value.
Referenced by __ast_read(), __ast_request_and_dial(), __attempt_transmit(), agent_run(), ast_ari_channels_hangup(), ast_channel_softhangup_withcause_locked(), ast_do_pickup(), AST_TEST_DEFINE(), ast_unreal_call_setup(), ast_unreal_hangup(), call_pickup_incoming_request(), cb_events(), channel_set_cause(), check_rtp_timeout(), console_new(), dahdi_indicate(), dial_exec_full(), disa_exec(), eivr_comm(), handle_call_outgoing(), handle_clear_alarms(), handle_request_invite(), handle_response(), handle_response_invite(), hangup_channel(), hangupcalls(), hanguptree(), iax2_call(), indicate_busy(), indicate_congestion(), jingle_indicate(), mbl_queue_hangup(), misdn_call(), onCallCleared(), pbx_builtin_hangup(), pbx_start_incoming_request(), receive_dtmf_digits(), refer_incoming_invite_request(), retrans_pkt(), rfc3326_use_reason_header(), ring_entry(), rtp_check_timeout(), send_cause2ast(), session_inv_on_media_update(), set_hangup_source_and_cause(), sip_call(), sip_pickup_thread(), socket_process_helper(), use_reason_header(), wait_for_answer(), and wait_for_winner().
 {
    chan->hangupcause = value;
    ast_channel_snapshot_invalidate_segment(chan, AST_CHANNEL_SNAPSHOT_INVALIDATE_HANGUP);
 }
ast_channel_hold_state()
int ast_channel_hold_state (const struct ast_channel * chan)
Definition at line 485 of file channel_internal_api.c.
Referenced by ast_parse_device_state(), bridge_channel_internal_join(), channel_do_masquerade(), func_channel_read(), and softmix_bridge_join().
 {
    return chan->hold_state;
 }
ast_channel_hold_state_set()
void ast_channel_hold_state_set (struct ast_channel * chan, int value)
Definition at line 489 of file channel_internal_api.c.
References value.
Referenced by __ast_channel_alloc_ap(), __ast_dummy_channel_alloc(), and indicate_data_internal().
 {
    chan->hold_state = value;
 }
ast_channel_insmpl()
unsigned long ast_channel_insmpl (const struct ast_channel * chan)
Definition at line 533 of file channel_internal_api.c.
References ast_channel::insmpl.
Referenced by __ast_read(), and ast_write_stream().
 {
    return chan->insmpl;
 }
ast_channel_insmpl_set()
void ast_channel_insmpl_set (struct ast_channel * chan, unsigned long value)
Definition at line 537 of file channel_internal_api.c.
References ast_channel::insmpl, and value.
Referenced by __ast_read(), and ast_monitor_start().
 {
    chan->insmpl = value;
 }
ast_channel_internal_alert_flush()
ast_alert_status_t ast_channel_internal_alert_flush (struct ast_channel * chan)
Definition at line 1115 of file channel_internal_api.c.
References ast_alertpipe_flush().
Referenced by chan_cleanup().
 {
    return ast_alertpipe_flush(chan->alertpipe);
 }
ast_channel_internal_alert_read()
ast_alert_status_t ast_channel_internal_alert_read (struct ast_channel * chan)
Definition at line 1120 of file channel_internal_api.c.
References ast_alertpipe_read().
Referenced by __ast_queue_frame(), and __ast_read().
 {
    return ast_alertpipe_read(chan->alertpipe);
 }
ast_channel_internal_alert_readable()
int ast_channel_internal_alert_readable (struct ast_channel * chan)
Definition at line 1130 of file channel_internal_api.c.
References ast_alertpipe_readable().
 {
    return ast_alertpipe_readable(chan->alertpipe);
 }
ast_channel_internal_alert_readfd()
int ast_channel_internal_alert_readfd (struct ast_channel * chan)
Definition at line 1150 of file channel_internal_api.c.
References ast_alertpipe_readfd().
Referenced by __ast_channel_alloc_ap().
 {
    return ast_alertpipe_readfd(chan->alertpipe);
 }
ast_channel_internal_alertpipe_clear()
void ast_channel_internal_alertpipe_clear (struct ast_channel * chan)
Definition at line 1135 of file channel_internal_api.c.
References ast_alertpipe_clear().
Referenced by __ast_channel_alloc_ap(), and __ast_dummy_channel_alloc().
 {
    ast_alertpipe_clear(chan->alertpipe);
 }
ast_channel_internal_alertpipe_close()
void ast_channel_internal_alertpipe_close (struct ast_channel * chan)
Definition at line 1140 of file channel_internal_api.c.
References ast_alertpipe_close().
Referenced by ast_channel_destructor().
 {
    ast_alertpipe_close(chan->alertpipe);
 }
ast_channel_internal_alertpipe_init()
int ast_channel_internal_alertpipe_init (struct ast_channel * chan)
Definition at line 1145 of file channel_internal_api.c.
References ast_alertpipe_init().
Referenced by __ast_channel_alloc_ap().
 {
    return ast_alertpipe_init(chan->alertpipe);
 }
ast_channel_internal_alertpipe_swap()
void ast_channel_internal_alertpipe_swap (struct ast_channel * chan1, struct ast_channel * chan2)
Swap the interal alertpipe between two channels.
Note
Handle all of the necessary locking before calling this
Definition at line 1155 of file channel_internal_api.c.
References ast_alertpipe_swap().
Referenced by channel_do_masquerade().
 {
    ast_alertpipe_swap(chan1->alertpipe, chan2->alertpipe);
 }
ast_channel_internal_bridge()
struct ast_bridge* ast_channel_internal_bridge (const struct ast_channel * chan)
Definition at line 1240 of file channel_internal_api.c.
Referenced by ast_channel_get_bridge(), ast_channel_is_bridged(), ast_unreal_fixup(), bridge_channel_internal_join(), and try_merge_optimize_out().
 {
    return chan->bridge;
 }
ast_channel_internal_bridge_channel()
struct ast_bridge_channel* ast_channel_internal_bridge_channel (const struct ast_channel * chan)
Definition at line 1251 of file channel_internal_api.c.
Referenced by ast_bridge_depart(), ast_bridge_unreal_optimize_out(), ast_channel_get_bridge_channel(), bridge_channel_depart(), optimize_lock_chan_stack(), optimize_lock_peer_stack(), and stasis_app_exec().
 {
    return chan->bridge_channel;
 }
ast_channel_internal_bridge_channel_set()
void ast_channel_internal_bridge_channel_set (struct ast_channel * chan, struct ast_bridge_channel * value)
Definition at line 1255 of file channel_internal_api.c.
References value.
Referenced by ast_bridge_depart(), ast_bridge_join(), bridge_channel_ind_thread(), and bridge_impart_internal().
 {
    chan->bridge_channel = value;
 }
ast_channel_internal_bridge_set()
void ast_channel_internal_bridge_set (struct ast_channel * chan, struct ast_bridge * value)
Precondition
chan is locked
Definition at line 1244 of file channel_internal_api.c.
References ast_channel_publish_snapshot(), AST_CHANNEL_SNAPSHOT_INVALIDATE_BRIDGE, ast_channel_snapshot_invalidate_segment(), and value.
Referenced by bridge_channel_change_bridge(), and bridge_channel_internal_join().
 {
    chan->bridge = value;
    ast_channel_snapshot_invalidate_segment(chan, AST_CHANNEL_SNAPSHOT_INVALIDATE_BRIDGE);
    ast_channel_publish_snapshot(chan);
 }
ast_channel_internal_cleanup()
void ast_channel_internal_cleanup (struct ast_channel * chan)
Definition at line 1471 of file channel_internal_api.c.
References ao2_cleanup, ao2_t_ref, ast_channel_internal_set_stream_topology(), ast_string_field_free_memory, AST_VECTOR_FREE, ast_channel::dialed_causes, NULL, and stasis_forward_cancel().
Referenced by ast_channel_destructor(), and ast_dummy_channel_destructor().
 {
    if (chan->dialed_causes) {
       ao2_t_ref(chan->dialed_causes, -1,
          "done with dialed causes since the channel is going away");
       chan->dialed_causes = NULL;
    }
    ast_string_field_free_memory(chan);
    chan->channel_forward = stasis_forward_cancel(chan->channel_forward);
    chan->endpoint_forward = stasis_forward_cancel(chan->endpoint_forward);
    ao2_cleanup(chan->topic);
    chan->topic = NULL;
    ast_channel_internal_set_stream_topology(chan, NULL);
    AST_VECTOR_FREE(&chan->fds);
 }
ast_channel_internal_copy_linkedid()
void ast_channel_internal_copy_linkedid (struct ast_channel * dest, struct ast_channel * source)
Copy the full linkedid channel id structure from one channel to another.
Parameters
dest Destination to copy linkedid to
source Source channel to copy linkedid from
Returns
void
Definition at line 1404 of file channel_internal_api.c.
References ast_channel_publish_snapshot(), AST_CHANNEL_SNAPSHOT_INVALIDATE_PEER, ast_channel_snapshot_invalidate_segment(), ast_channel_id::creation_time, ast_channel_id::creation_unique, ast_channel::linkedid, and ast_channel_id::unique_id.
Referenced by ast_bridge_channel_update_linkedids().
 {
    if (dest->linkedid.creation_time == source->linkedid.creation_time
       && dest->linkedid.creation_unique == source->linkedid.creation_unique
       && !strcmp(dest->linkedid.unique_id, source->linkedid.unique_id)) {
       return;
    }
    dest->linkedid = source->linkedid;
    ast_channel_snapshot_invalidate_segment(dest, AST_CHANNEL_SNAPSHOT_INVALIDATE_PEER);
    ast_channel_publish_snapshot(dest);
 }
ast_channel_internal_errno()
enum ast_channel_error ast_channel_internal_errno (void)
Definition at line 1573 of file channel_internal_api.c.
References AST_CHANNEL_ERROR_UNKNOWN, ast_threadstorage_get(), and channel_errno.
Referenced by ast_channel_errno().
 {
    enum ast_channel_error *error_code = ast_threadstorage_get(&channel_errno, sizeof(*error_code));
    if (!error_code) {
       return AST_CHANNEL_ERROR_UNKNOWN;
    }
    return *error_code;
 }
ast_channel_internal_errno_set()
void ast_channel_internal_errno_set (enum ast_channel_error error)
Definition at line 1563 of file channel_internal_api.c.
References ast_threadstorage_get(), channel_errno, and error().
Referenced by __ast_channel_alloc_ap().
 {
    enum ast_channel_error *error_code = ast_threadstorage_get(&channel_errno, sizeof(*error_code));
    if (!error_code) {
       return;
    }
    *error_code = error;
 }
ast_channel_internal_fd_clear()
void ast_channel_internal_fd_clear (struct ast_channel * chan, int which)
Definition at line 1174 of file channel_internal_api.c.
References AST_VECTOR_REPLACE, and AST_VECTOR_SIZE.
Referenced by handle_negotiated_sdp().
 {
    if (which >= AST_VECTOR_SIZE(&chan->fds)) {
       return;
    }
    AST_VECTOR_REPLACE(&chan->fds, which, -1);
 }
ast_channel_internal_fd_clear_all()
void ast_channel_internal_fd_clear_all (struct ast_channel * chan)
Definition at line 1182 of file channel_internal_api.c.
References AST_VECTOR_ELEM_CLEANUP_NOOP, and AST_VECTOR_RESET.
Referenced by __ast_channel_alloc_ap(), __ast_dummy_channel_alloc(), and channel_do_masquerade().
 {
    AST_VECTOR_RESET(&chan->fds, AST_VECTOR_ELEM_CLEANUP_NOOP);
 }
ast_channel_internal_fd_set()
void ast_channel_internal_fd_set (struct ast_channel * chan, int which, int value)
Definition at line 1161 of file channel_internal_api.c.
References AST_VECTOR_REPLACE, and AST_VECTOR_SIZE.
Referenced by ast_channel_set_fd(), handle_negotiated_sdp(), my_on_hook(), start_rtp(), swap_subs(), and unistim_new().
 {
    int pos;
    /* This ensures that if the vector has to grow with unused positions they will be
     * initialized to -1.
     */
    for (pos = AST_VECTOR_SIZE(&chan->fds); pos < which; pos++) {
       AST_VECTOR_REPLACE(&chan->fds, pos, -1);
    }
    AST_VECTOR_REPLACE(&chan->fds, which, value);
 }
ast_channel_internal_finalize()
void ast_channel_internal_finalize (struct ast_channel * chan)
Definition at line 1492 of file channel_internal_api.c.
Referenced by __ast_channel_alloc_ap().
 {
    chan->finalized = 1;
 }
ast_channel_internal_is_finalized()
int ast_channel_internal_is_finalized (struct ast_channel * chan)
Definition at line 1497 of file channel_internal_api.c.
Referenced by ast_channel_destructor().
 {
    return chan->finalized;
 }
ast_channel_internal_oldest_linkedid()
struct ast_channel* ast_channel_internal_oldest_linkedid (struct ast_channel * a, struct ast_channel * b)
Determine which channel has an older linkedid.
Parameters
a First channel
b Second channel
Returns
Returns an ast_channel structure that has oldest linkedid
Definition at line 1387 of file channel_internal_api.c.
References a, ast_assert, b, ast_channel_id::creation_time, ast_channel_id::creation_unique, and ast_channel::linkedid.
Referenced by ast_bridge_channel_update_linkedids().
 {
    ast_assert(a->linkedid.creation_time != 0);
    ast_assert(b->linkedid.creation_time != 0);
    if (a->linkedid.creation_time < b->linkedid.creation_time) {
       return a;
    }
    if (b->linkedid.creation_time < a->linkedid.creation_time) {
       return b;
    }
    if (a->linkedid.creation_unique < b->linkedid.creation_unique) {
       return a;
    }
    return b;
 }
ast_channel_internal_set_fake_ids()
void ast_channel_internal_set_fake_ids (struct ast_channel * chan, const char * uniqueid, const char * linkedid)
Set uniqueid and linkedid string value only (not time)
Parameters
chan The channel to set the uniqueid to
uniqueid The uniqueid to set
linkedid The linkedid to set
Returns
void
Note
This is used only by ast_cel_fabricate_channel_from_event() to create a temporary fake channel - time values are invalid
Definition at line 1465 of file channel_internal_api.c.
References ast_copy_string(), ast_channel::linkedid, ast_channel_id::unique_id, and ast_channel::uniqueid.
Referenced by ast_cel_fabricate_channel_from_event().
 {
    ast_copy_string(chan->uniqueid.unique_id, uniqueid, sizeof(chan->uniqueid.unique_id));
    ast_copy_string(chan->linkedid.unique_id, linkedid, sizeof(chan->linkedid.unique_id));
 }
ast_channel_internal_set_stream_topology()
void ast_channel_internal_set_stream_topology (struct ast_channel * chan, struct ast_stream_topology * topology)
Definition at line 658 of file channel_internal_api.c.
References ast_stream_topology_free(), and channel_set_default_streams().
Referenced by __ast_channel_alloc_ap(), ast_channel_internal_cleanup(), ast_channel_nativeformats_set(), and ast_channel_set_stream_topology().
 {
    ast_stream_topology_free(chan->stream_topology);
    chan->stream_topology = topology;
    channel_set_default_streams(chan);
 }
ast_channel_internal_set_stream_topology_change_source()
void ast_channel_internal_set_stream_topology_change_source (struct ast_channel * chan, void * change_source)
Definition at line 666 of file channel_internal_api.c.
Referenced by ast_channel_request_stream_topology_change(), and ast_channel_stream_topology_changed_externally().
 {
    chan->stream_topology_change_source = change_source;
 }
ast_channel_internal_setup_topics()
int ast_channel_internal_setup_topics (struct ast_channel * chan)
Definition at line 1527 of file channel_internal_api.c.
References ao2_ref, ast_asprintf, ast_assert, ast_atomic_fetchadd_int(), ast_channel_topic(), ast_channel_topic_all(), ast_free, ast_strlen_zero, NULL, stasis_forward_all(), stasis_topic_create(), ast_channel_id::unique_id, and ast_channel::uniqueid.
Referenced by __ast_channel_alloc_ap(), and __ast_dummy_channel_alloc().
 {
    char *topic_name;
    int ret;
    ast_assert(chan->topic == NULL);
    if (ast_strlen_zero(chan->uniqueid.unique_id)) {
       static int dummy_id;
       ret = ast_asprintf(&topic_name, "channel:dummy-%d", ast_atomic_fetchadd_int(&dummy_id, +1));
    } else {
       ret = ast_asprintf(&topic_name, "channel:%s", chan->uniqueid.unique_id);
    }
    if (ret < 0) {
       return -1;
    }
    chan->topic = stasis_topic_create(topic_name);
    ast_free(topic_name);
    if (!chan->topic) {
       return -1;
    }
    chan->channel_forward = stasis_forward_all(ast_channel_topic(chan),
       ast_channel_topic_all());
    if (!chan->channel_forward) {
       ao2_ref(chan->topic, -1);
       chan->topic = NULL;
       return -1;
    }
    return 0;
 }
ast_channel_internal_swap_endpoint_forward()
void ast_channel_internal_swap_endpoint_forward (struct ast_channel * a, struct ast_channel * b)
Swap endpoint_forward between two channels.
Parameters
a First channel
b Second channel
Returns
void
Note
This is used in masquerade to exchange endpoint details if one of the two or both the channels were created with endpoint
Definition at line 1447 of file channel_internal_api.c.
Referenced by channel_do_masquerade().
 {
    struct stasis_forward *temp;
    temp = a->endpoint_forward;
    a->endpoint_forward = b->endpoint_forward;
    b->endpoint_forward = temp;
 }
ast_channel_internal_swap_snapshots()
void ast_channel_internal_swap_snapshots (struct ast_channel * a, struct ast_channel * b)
Swap snapshots beteween two channels.
Parameters
a First channel
b Second channel
Returns
void
Note
This is used in masquerade to exchange snapshots
Definition at line 1456 of file channel_internal_api.c.
Referenced by channel_do_masquerade().
 {
    struct ast_channel_snapshot *snapshot;
    snapshot = a->snapshot;
    a->snapshot = b->snapshot;
    b->snapshot = snapshot;
 }
ast_channel_internal_swap_stream_topology()
void ast_channel_internal_swap_stream_topology (struct ast_channel * chan1, struct ast_channel * chan2)
Definition at line 1628 of file channel_internal_api.c.
References ast_assert, channel_set_default_streams(), and NULL.
Referenced by channel_do_masquerade().
 {
    struct ast_stream_topology *tmp_topology;
    ast_assert(chan1 != NULL && chan2 != NULL);
    tmp_topology = chan1->stream_topology;
    chan1->stream_topology = chan2->stream_topology;
    chan2->stream_topology = tmp_topology;
    channel_set_default_streams(chan1);
    channel_set_default_streams(chan2);
 }
ast_channel_internal_swap_topics()
void ast_channel_internal_swap_topics (struct ast_channel * a, struct ast_channel * b)
Swap topics beteween two channels.
Parameters
a First channel
b Second channel
Returns
void
Note
This is used in masquerade to exchange topics for message routing
Definition at line 1433 of file channel_internal_api.c.
Referenced by channel_do_masquerade().
 {
    struct stasis_topic *topic;
    struct stasis_forward *forward;
    topic = a->topic;
    a->topic = b->topic;
    b->topic = topic;
    forward = a->channel_forward;
    a->channel_forward = b->channel_forward;
    b->channel_forward = forward;
 }
ast_channel_internal_swap_uniqueid_and_linkedid()
void ast_channel_internal_swap_uniqueid_and_linkedid (struct ast_channel * a, struct ast_channel * b)
Swap uniqueid and linkedid beteween two channels.
Parameters
a First channel
b Second channel
Returns
void
Note
This is used in masquerade to exchange identities
Definition at line 1416 of file channel_internal_api.c.
References ast_channel::linkedid, and ast_channel::uniqueid.
Referenced by channel_do_masquerade().
 {
    struct ast_channel_id temp;
    /* This operation is used as part of masquerading and so does not invalidate the peer
     * segment. This is due to the masquerade process invalidating all segments.
     */
    temp = a->uniqueid;
    a->uniqueid = b->uniqueid;
    b->uniqueid = temp;
    temp = a->linkedid;
    a->linkedid = b->linkedid;
    b->linkedid = temp;
 }
ast_channel_is_multistream()
int ast_channel_is_multistream (struct ast_channel * chan)
Determine if a channel is multi-stream capable.
Parameters
channel The channel to test
Precondition
chan is locked
Returns
Returns true if the channel is multi-stream capable.
Definition at line 1643 of file channel_internal_api.c.
References ast_channel_tech::read_stream, ast_channel::tech, and ast_channel_tech::write_stream.
Referenced by ast_channel_nativeformats_set(), ast_channel_request_stream_topology_change(), ast_channel_set_stream_topology(), ast_channel_stream_topology_changed(), ast_channel_stream_topology_changed_externally(), ast_unreal_indicate(), ast_unreal_new_channels(), bridge_channel_write_frame(), bridge_handle_trip(), and stream_echo_write().
 {
    return (chan && chan->tech && chan->tech->read_stream && chan->tech->write_stream);
 }
ast_channel_is_t38_active()
int ast_channel_is_t38_active (struct ast_channel * chan)
This function will check if T.38 is active on the channel.
Parameters
chan Channel on which to check the unbridge_eval flag
Returns
Returns 0 if the flag is down or 1 if the flag is up.
Definition at line 1046 of file channel_internal_api.c.
References ast_channel_is_t38_active_nolock(), ast_channel_lock, and ast_channel_unlock.
Referenced by bridge_channel_internal_join().
 {
    int res;
    ast_channel_lock(chan);
    res = ast_channel_is_t38_active_nolock(chan);
    ast_channel_unlock(chan);
    return res;
 }
ast_channel_is_t38_active_nolock()
int ast_channel_is_t38_active_nolock (struct ast_channel * chan)
ast_channel_is_t38_active variant. Use this if the channel is already locked prior to calling.
Parameters
chan Channel on which to check the is_t38_active flag
Returns
Returns 0 if the flag is down or 1 if the flag is up.
Definition at line 1041 of file channel_internal_api.c.
Referenced by ast_channel_is_t38_active().
 {
    return chan->is_t38_active;
 }
ast_channel_jb()
struct ast_jb* ast_channel_jb (struct ast_channel * chan)
Definition at line 884 of file channel_internal_api.c.
References ast_channel::jb.
Referenced by ast_jb_configure(), ast_jb_destroy(), ast_jb_do_usecheck(), ast_jb_empty_and_reset(), ast_jb_enable_for_channel(), ast_jb_get_and_deliver(), ast_jb_get_config(), ast_jb_get_when_to_wakeup(), ast_jb_put(), create_jb(), jb_choose_impl(), and jb_get_and_deliver().
 {
    return &chan->jb;
 }
ast_channel_jb_set()
void ast_channel_jb_set (struct ast_channel * chan, struct ast_jb * value)
Definition at line 940 of file channel_internal_api.c.
References ast_channel::jb, and value.
 {
    chan->jb = *value;
 }
ast_channel_linkedid()
const char* ast_channel_linkedid (const struct ast_channel * chan)
Definition at line 311 of file channel_internal_api.c.
References ast_assert, ast_channel::linkedid, and ast_channel_id::unique_id.
Referenced by ast_channel_log(), AST_TEST_DEFINE(), channel_snapshot_peer_create(), func_channel_read(), func_mchan_read(), func_mchan_write(), handle_showchan(), and serialize_showchan().
 {
    ast_assert(chan->linkedid.unique_id[0] != '\0');
    return chan->linkedid.unique_id;
 }
ast_channel_macrocontext()
const char* ast_channel_macrocontext (const struct ast_channel * chan)
Definition at line 362 of file channel_internal_api.c.
Referenced by _macro_exec(), ast_cc_call_init(), ast_channel_by_exten_cb(), ast_channel_log(), ast_var_channels_table(), cc_generic_agent_init(), cc_interfaces_datastore_init(), chan_pjsip_cng_tone_detected(), common_exec(), conf_run(), dahdi_handle_dtmf(), dial_exec_full(), fax_detect_framehook(), get_also_info(), get_cid_name(), get_refer_info(), get_transfer_context(), goto_exten(), launch_monitor_thread(), leave_voicemail(), minivm_greet_exec(), my_handle_dtmf(), onedigit_goto(), onModeChanged(), ooh323_rtp_read(), process_ast_dsp(), process_sdp(), and sip_read().
 {
    return chan->macrocontext;
 }
ast_channel_macrocontext_set()
void ast_channel_macrocontext_set (struct ast_channel * chan, const char * value)
Definition at line 366 of file channel_internal_api.c.
References ast_copy_string().
Referenced by _macro_exec().
 {
    ast_copy_string(chan->macrocontext, value, sizeof(chan->macrocontext));
 }
ast_channel_macroexten()
const char* ast_channel_macroexten (const struct ast_channel * chan)
Definition at line 370 of file channel_internal_api.c.
Referenced by _macro_exec(), ast_cc_call_init(), ast_channel_by_exten_cb(), ast_channel_log(), ast_var_channels_table(), cc_generic_agent_init(), cc_interfaces_datastore_init(), dial_exec_full(), do_forward(), dundi_exec(), dundi_helper(), get_cid_name(), ring_entry(), and wait_for_answer().
 {
    return chan->macroexten;
 }
ast_channel_macroexten_set()
void ast_channel_macroexten_set (struct ast_channel * chan, const char * value)
Definition at line 374 of file channel_internal_api.c.
References ast_copy_string().
Referenced by _macro_exec().
 {
    ast_copy_string(chan->macroexten, value, sizeof(chan->macroexten));
 }
ast_channel_macropriority()
int ast_channel_macropriority (const struct ast_channel * chan)
Definition at line 436 of file channel_internal_api.c.
Referenced by ast_channel_log(), and ast_var_channels_table().
 {
    return chan->macropriority;
 }
ast_channel_macropriority_set()
void ast_channel_macropriority_set (struct ast_channel * chan, int value)
Definition at line 440 of file channel_internal_api.c.
References value.
Referenced by _macro_exec().
 {
    chan->macropriority = value;
 }
ast_channel_masq()
struct ast_channel* ast_channel_masq (const struct ast_channel * chan)
Definition at line 597 of file channel_internal_api.c.
References ast_channel::masq.
Referenced by ast_can_pickup(), ast_channel_log(), ast_hangup(), and ast_var_channels_table().
 {
    return chan->masq;
 }
ast_channel_masq_set()
void ast_channel_masq_set (struct ast_channel * chan, struct ast_channel * value)
Definition at line 601 of file channel_internal_api.c.
References ast_channel::masq, and value.
Referenced by ast_channel_move(), and channel_do_masquerade().
 {
    chan->masq = value;
 }
ast_channel_masqr()
struct ast_channel* ast_channel_masqr (const struct ast_channel * chan)
Definition at line 605 of file channel_internal_api.c.
References ast_channel::masqr.
Referenced by ast_channel_log(), ast_hangup(), and ast_var_channels_table().
 {
    return chan->masqr;
 }
ast_channel_masqr_set()
void ast_channel_masqr_set (struct ast_channel * chan, struct ast_channel * value)
Definition at line 609 of file channel_internal_api.c.
References ast_channel::masqr, and value.
Referenced by ast_channel_move(), and channel_do_masquerade().
 {
    chan->masqr = value;
 }
ast_channel_monitor()
struct ast_channel_monitor* ast_channel_monitor (const struct ast_channel * chan)
Definition at line 613 of file channel_internal_api.c.
References ast_channel::monitor.
Referenced by __ast_read(), ast_channel_destructor(), ast_channel_has_audio_frame_or_monitor(), ast_channel_has_hook_requiring_audio(), ast_monitor_change_fname(), ast_monitor_set_state(), ast_monitor_setjoinfiles(), ast_monitor_start(), ast_monitor_stop(), ast_write_stream(), channel_do_masquerade(), conf_run(), feature_automonitor(), and stop_automonitor().
 {
    return chan->monitor;
 }
ast_channel_monitor_set()
void ast_channel_monitor_set (struct ast_channel * chan, struct ast_channel_monitor * value)
Definition at line 617 of file channel_internal_api.c.
References ast_channel::monitor, and value.
Referenced by ast_monitor_start(), ast_monitor_stop(), and channel_do_masquerade().
 {
    chan->monitor = value;
 }
ast_channel_music_state()
void* ast_channel_music_state (const struct ast_channel * chan)
Definition at line 557 of file channel_internal_api.c.
References ast_channel::music_state.
Referenced by __ast_read(), ast_channel_destructor(), ast_moh_files_next(), local_ast_moh_cleanup(), local_ast_moh_start(), local_ast_moh_stop(), moh_alloc(), moh_files_alloc(), moh_files_generator(), moh_files_release(), moh_files_write_format_change(), and moh_release().
 {
    return chan->music_state;
 }
ast_channel_music_state_set()
void ast_channel_music_state_set (struct ast_channel * chan, void * value)
Definition at line 561 of file channel_internal_api.c.
References ast_channel::music_state, and value.
Referenced by local_ast_moh_cleanup(), moh_alloc(), and moh_files_alloc().
 {
    chan->music_state = value;
 }
ast_channel_named_callgroups()
struct ast_namedgroups* ast_channel_named_callgroups (const struct ast_channel * chan)
Definition at line 1090 of file channel_internal_api.c.
References ast_channel::named_callgroups.
Referenced by find_channel_by_group(), and func_channel_read().
 {
    return chan->named_callgroups;
 }
ast_channel_named_callgroups_set()
void ast_channel_named_callgroups_set (struct ast_channel * chan, struct ast_namedgroups * value)
Definition at line 1094 of file channel_internal_api.c.
References ast_ref_namedgroups(), ast_unref_namedgroups(), and ast_channel::named_callgroups.
Referenced by ast_channel_destructor(), chan_pjsip_new(), dahdi_new(), func_channel_write_real(), read_config(), sip_new(), and skinny_new().
 {
    ast_unref_namedgroups(chan->named_callgroups);
    chan->named_callgroups = ast_ref_namedgroups(value);
 }
ast_channel_named_pickupgroups()
struct ast_namedgroups* ast_channel_named_pickupgroups (const struct ast_channel * chan)
Definition at line 1099 of file channel_internal_api.c.
References ast_channel::named_pickupgroups.
Referenced by find_channel_by_group(), and func_channel_read().
 {
    return chan->named_pickupgroups;
 }
ast_channel_named_pickupgroups_set()
void ast_channel_named_pickupgroups_set (struct ast_channel * chan, struct ast_namedgroups * value)
Definition at line 1103 of file channel_internal_api.c.
References ast_ref_namedgroups(), ast_unref_namedgroups(), and ast_channel::named_pickupgroups.
Referenced by ast_channel_destructor(), chan_pjsip_new(), dahdi_new(), func_channel_write_real(), read_config(), sip_new(), and skinny_new().
 {
    ast_unref_namedgroups(chan->named_pickupgroups);
    chan->named_pickupgroups = ast_ref_namedgroups(value);
 }
ast_channel_nativeformats()
struct ast_format_cap* ast_channel_nativeformats (const struct ast_channel * chan)
Definition at line 637 of file channel_internal_api.c.
Referenced by ast_ari_channels_create(), ast_bridge_update_talker_src_video_mode(), ast_channel_make_compatible_helper(), ast_openvstream(), ast_sendtext_data(), ast_streamfile(), ast_write_stream(), attended_transfer_bridge(), begin_dial_prerun(), blind_transfer_bridge(), chan_pjsip_get_codec(), chan_pjsip_indicate(), chan_pjsip_read_stream(), chan_pjsip_write_stream(), chanavail_exec(), channel_do_masquerade(), create_addr(), dial_transfer(), findmeexec(), func_channel_read(), generate_status(), handle_showchan(), iax2_call(), iax2_key_rotate(), iax2_request(), jingle_read(), jingle_write(), mgcp_new(), mgcp_rtp_read(), mgcp_write(), mp3_exec(), ooh323_get_codec(), ooh323_rtp_read(), ooh323_set_write_format(), ooh323_write(), park_local_transfer(), process_sdp(), ring_entry(), serialize_showchan(), set_caps(), set_format(), show_channels_cb(), sip_get_codec(), sip_indicate(), sip_new(), sip_rtp_read(), sip_session_response_cb(), sip_show_channel(), sip_write(), skinny_new(), skinny_rtp_read(), skinny_write(), socket_process_helper(), speech_create(), start_rtp(), test_vm_api_create_mock_channel(), unistim_new(), unistim_rtp_read(), unistim_write(), and wait_for_answer().
 {
    return chan->nativeformats;
 }
ast_channel_nativeformats_set()
void ast_channel_nativeformats_set (struct ast_channel * chan, struct ast_format_cap * value)
Definition at line 677 of file channel_internal_api.c.
References ao2_replace, ast_assert, ast_channel_internal_set_stream_topology(), ast_channel_is_multistream(), ast_channel_name(), ast_format_cap_get_names(), ast_str_tmp, ast_stream_topology_create_from_format_cap(), NULL, S_COR, S_OR, SCOPE_ENTER, and SCOPE_EXIT_RTN.
Referenced by __ast_channel_alloc_ap(), alsa_new(), ast_channel_destructor(), ast_iax2_new(), AST_TEST_DEFINE(), ast_unreal_new_channels(), audiosocket_request(), chan_pjsip_new(), chan_pjsip_read_stream(), channel_do_masquerade(), console_new(), dahdi_new(), do_notify(), iax2_request(), jingle_interpret_content(), jingle_new(), jingle_read(), make_channel(), mbl_new(), mgcp_new(), mgcp_rtp_read(), misdn_new(), multicast_rtp_request(), nbs_new(), ooh323_new(), ooh323_rtp_read(), ooh323_set_read_format(), ooh323_set_write_format(), oss_new(), phone_new(), process_sdp(), rec_request(), set_caps(), set_format(), set_test_formats(), sip_new(), sip_rtp_read(), skinny_new(), skinny_rtp_read(), socket_process_helper(), stasis_app_control_snoop(), unicast_rtp_request(), unistim_new(), and unistim_rtp_read().
 {
    SCOPE_ENTER(2, "%s: %sFormats: %s\n", S_OR(ast_channel_name(chan), "<initializing>"),
       S_COR(ast_channel_is_multistream(chan), "Multistream", ""),
       ast_str_tmp(128, ast_format_cap_get_names(value, &STR_TMP)));
    ast_assert(chan != NULL);
    ao2_replace(chan->nativeformats, value);
    /* If chan->stream_topology is NULL, the channel is being destroyed
     * and topology is destroyed.
     */
    if (!chan->stream_topology) {
       SCOPE_EXIT_RTN("Channel is being initialized or destroyed\n");
    }
    if (!ast_channel_is_multistream(chan) || !value) {
       struct ast_stream_topology *new_topology;
       new_topology = ast_stream_topology_create_from_format_cap(value);
       ast_channel_internal_set_stream_topology(chan, new_topology);
       SCOPE_EXIT_RTN("New %stopology set\n", value ? "" : "empty ");
    }
    SCOPE_EXIT_RTN("Set native formats but not topology\n");
 }
ast_channel_oldwriteformat()
struct ast_format* ast_channel_oldwriteformat (struct ast_channel * chan)
Definition at line 844 of file channel_internal_api.c.
Referenced by ast_stopstream().
 {
    return chan->oldwriteformat;
 }
ast_channel_outsmpl()
unsigned long ast_channel_outsmpl (const struct ast_channel * chan)
Definition at line 541 of file channel_internal_api.c.
References ast_channel::outsmpl.
Referenced by __ast_read(), and ast_write_stream().
 {
    return chan->outsmpl;
 }
ast_channel_outsmpl_set()
void ast_channel_outsmpl_set (struct ast_channel * chan, unsigned long value)
Definition at line 545 of file channel_internal_api.c.
References ast_channel::outsmpl, and value.
Referenced by ast_monitor_start(), and ast_write_stream().
 {
    chan->outsmpl = value;
 }
ast_channel_pbx()
struct ast_pbx* ast_channel_pbx (const struct ast_channel * chan)
Definition at line 721 of file channel_internal_api.c.
References ast_channel::pbx.
Referenced by __analog_handle_event(), __ast_pbx_run(), action_dialplan_exec(), ast_app_dtget(), ast_app_getdata(), ast_async_goto(), ast_bridge_add_channel(), ast_can_pickup(), ast_channel_destructor(), bridge_impart_internal(), collect_digits(), control_swap_channel_in_bridge(), dahdi_handle_event(), depart_channel(), disa_exec(), handle_getoption(), handle_gosub(), ivr_dispatch(), pbx_builtin_waitexten(), read_exec(), read_newoption(), readexten_exec(), speech_background(), stasis_app_exec(), timeout_read(), and timeout_write().
 {
    return chan->pbx;
 }
ast_channel_pbx_set()
void ast_channel_pbx_set (struct ast_channel * chan, struct ast_pbx * value)
Definition at line 725 of file channel_internal_api.c.
References ast_channel::pbx, and value.
Referenced by __ast_pbx_run(), action_dialplan_exec(), control_swap_channel_in_bridge(), handle_gosub(), and internal_bridge_after_cb().
 {
    chan->pbx = value;
 }
ast_channel_pickupgroup()
ast_group_t ast_channel_pickupgroup (const struct ast_channel * chan)
Definition at line 1082 of file channel_internal_api.c.
References ast_channel::pickupgroup.
Referenced by ast_var_channels_table(), find_channel_by_group(), func_channel_read(), generate_status(), handle_showchan(), and serialize_showchan().
 {
    return chan->pickupgroup;
 }
ast_channel_pickupgroup_set()
void ast_channel_pickupgroup_set (struct ast_channel * chan, ast_group_t value)
Precondition
chan is locked
Definition at line 1086 of file channel_internal_api.c.
References ast_channel::pickupgroup, and value.
Referenced by chan_pjsip_new(), dahdi_new(), func_channel_write_real(), jingle_new(), mgcp_new(), read_config(), sip_new(), skinny_new(), and unistim_new().
 {
    chan->pickupgroup = value;
 }
ast_channel_priority()
int ast_channel_priority (const struct ast_channel * chan)
Definition at line 444 of file channel_internal_api.c.
Referenced by __ast_pbx_run(), _if_exec(), _macro_exec(), _while_exec(), action_bridge(), action_dialplan_exec(), ast_app_exec_macro(), ast_bridge_setup_after_goto(), ast_channel_log(), ast_channel_yank(), ast_pbx_h_exten_run(), ast_str_retrieve_variable(), ast_var_channels_table(), bridge_exec(), channel_snapshot_dialplan_create(), dial_exec_full(), eval_exten_read(), feature_blind_transfer(), find_matching_endif(), find_matching_endwhile(), forward_message(), func_channel_write_real(), gosub_exec(), gosub_run(), handle_gosub(), handle_showchan(), launch_monitor_thread(), leave_voicemail(), log_exec(), lua_pbx_exec(), make_email_file(), pbx_builtin_goto(), pbx_builtin_setvar_multiple(), pbx_builtin_waitexten(), pbx_parseable_goto(), raise_exception(), realtime_exec(), serialize_showchan(), setup_env(), and setup_peer_after_bridge_goto().
 {
    return chan->priority;
 }
ast_channel_priority_set()
void ast_channel_priority_set (struct ast_channel * chan, int value)
Definition at line 448 of file channel_internal_api.c.
References AST_CHANNEL_SNAPSHOT_INVALIDATE_DIALPLAN, ast_channel_snapshot_invalidate_segment(), and value.
Referenced by __ast_channel_alloc_ap(), __ast_pbx_run(), __ast_request_and_dial(), _if_exec(), _macro_exec(), _while_exec(), action_dialplan_exec(), ari_originate_dial(), ast_bridge_setup_after_goto(), ast_channel_yank(), ast_explicit_goto(), ast_pbx_h_exten_run(), AST_TEST_DEFINE(), chan_pjsip_new(), dial_exec_full(), dialout(), do_notify(), eval_exten_read(), forward_message(), generic_recall(), gosub_exec(), gosub_run(), handle_gosub(), jingle_new(), leave_voicemail(), mgcp_new(), minivm_greet_exec(), misdn_new(), ooh323_new(), pbx_builtin_background(), pbx_extension_helper(), pbx_outgoing_exec(), return_exec(), set_ext_pri(), sip_new(), skinny_new(), unistim_new(), and wait_for_digits().
 {
    chan->priority = value;
    ast_channel_snapshot_invalidate_segment(chan, AST_CHANNEL_SNAPSHOT_INVALIDATE_DIALPLAN);
 }
ast_channel_rawreadformat()
struct ast_format* ast_channel_rawreadformat (struct ast_channel * chan)
Definition at line 848 of file channel_internal_api.c.
Referenced by __ast_read(), ast_set_read_format_path(), chan_pjsip_write_stream(), channel_do_masquerade(), cli_channelstats_print_body(), dahdi_read(), gather_softmix_stats(), native_rtp_bridge_compatible_check(), phone_setup(), serialize_showchan(), set_softmix_bridge_data(), set_talk_detect(), and snoop_determine_format().
 {
    return chan->rawreadformat;
 }
ast_channel_rawwriteformat()
struct ast_format* ast_channel_rawwriteformat (struct ast_channel * chan)
Definition at line 852 of file channel_internal_api.c.
Referenced by ast_prod(), ast_set_write_format_path(), ast_write_stream(), chan_pjsip_read_stream(), chan_pjsip_write_stream(), channel_do_masquerade(), conf_run(), native_rtp_bridge_compatible_check(), serialize_showchan(), snoop_determine_format(), and softmix_mixing_loop().
 {
    return chan->rawwriteformat;
 }
ast_channel_readformat()
struct ast_format* ast_channel_readformat (struct ast_channel * chan)
Definition at line 856 of file channel_internal_api.c.
Referenced by __ast_read(), adsi_transmit_message_full(), agent_login_exec(), alarmreceiver_exec(), ast_bridge_channel_restore_formats(), ast_channel_yank(), ast_set_read_format_path(), audiosocket_exec(), background_detect_exec(), bridge_channel_internal_join(), chan_pjsip_read_stream(), chan_pjsip_write_stream(), channel_do_masquerade(), dictate_exec(), do_waiting(), eagi_exec(), fax_detect_framehook(), fax_gateway_framehook(), func_channel_read(), generate_status(), generic_fax_exec(), handle_recordfile(), handle_showchan(), ices_exec(), init_jack_data(), isAnsweringMachine(), jingle_read(), jingle_write(), measurenoise(), mgcp_rtp_read(), mgcp_write(), ooh323_rtp_read(), ooh323_set_read_format(), ooh323_set_write_format(), ooh323_write(), process_sdp(), record_exec(), send_start_rtp(), serialize_showchan(), set_caps(), set_read_to_slin(), sip_rtp_read(), sip_write(), skinny_rtp_read(), skinny_write(), socket_process_helper(), speech_background(), start_rtp(), transmit_audio(), unistim_rtp_read(), and unistim_write().
 {
    return chan->readformat;
 }
ast_channel_readq()
struct ast_readq_list* ast_channel_readq (struct ast_channel * chan)
Definition at line 876 of file channel_internal_api.c.
References ast_channel::readq.
Referenced by __ast_queue_frame(), __ast_read(), ast_channel_clear_softhangup(), ast_channel_destructor(), chan_cleanup(), channel_do_masquerade(), load_stream_readqueue(), optimize_lock_chan_stack(), optimize_lock_peer_stack(), and wait_for_empty_queue().
 {
    return &chan->readq;
 }
ast_channel_readtrans()
struct ast_trans_pvt* ast_channel_readtrans (const struct ast_channel * chan)
Definition at line 753 of file channel_internal_api.c.
References ast_channel::readtrans.
Referenced by __ast_read(), ast_channel_destructor(), ast_set_read_format_path(), chan_pjsip_write_stream(), fax_gateway_framehook(), free_translation(), generate_status(), handle_showchan(), and serialize_showchan().
 {
    return chan->readtrans;
 }
ast_channel_readtrans_set()
void ast_channel_readtrans_set (struct ast_channel * chan, struct ast_trans_pvt * value)
Definition at line 757 of file channel_internal_api.c.
References ast_channel::readtrans, and value.
Referenced by ast_set_read_format_path(), and free_translation().
 {
    chan->readtrans = value;
 }
ast_channel_redirecting()
struct ast_party_redirecting* ast_channel_redirecting (struct ast_channel * chan)
Definition at line 908 of file channel_internal_api.c.
References ast_channel::redirecting.
Referenced by __ast_channel_alloc_ap(), add_diversion(), ast_ari_channels_dial(), ast_call_forward(), ast_cel_fabricate_channel_from_event(), ast_channel_destructor(), ast_channel_redirecting_macro(), ast_channel_redirecting_sub(), ast_channel_set_redirecting(), ast_dummy_channel_destructor(), ast_iax2_new(), ast_unreal_call_setup(), ast_var_channels_table(), begin_dial_prerun(), call_forward_inherit(), callerid_read(), callerid_write(), cb_events(), channel_do_masquerade(), channel_snapshot_caller_create(), dahdi_new(), dial_exec_full(), do_forward(), get_redirecting_add_diversion(), handle_response_invite(), iax2_call(), indicate_redirecting(), isAnsweringMachine(), leave_voicemail(), misdn_copy_redirecting_from_ast(), misdn_copy_redirecting_to_ast(), misdn_facility_ie_handler(), oss_call(), redirecting_read(), redirecting_write(), ring_entry(), serialize_showchan(), setup_env(), sip_new(), unreal_colp_redirect_indicate(), and wait_for_answer().
 {
    return &chan->redirecting;
 }
ast_channel_redirecting_effective_from()
struct ast_party_id ast_channel_redirecting_effective_from (struct ast_channel * chan)
Definition at line 916 of file channel_internal_api.c.
References ast_party_id_merge().
Referenced by add_diversion(), and misdn_copy_redirecting_from_ast().
 {
    return ast_party_id_merge(&chan->redirecting.from, &chan->redirecting.priv_from);
 }
ast_channel_redirecting_effective_orig()
struct ast_party_id ast_channel_redirecting_effective_orig (struct ast_channel * chan)
Definition at line 912 of file channel_internal_api.c.
References ast_party_id_merge().
 {
    return ast_party_id_merge(&chan->redirecting.orig, &chan->redirecting.priv_orig);
 }
ast_channel_redirecting_effective_to()
struct ast_party_id ast_channel_redirecting_effective_to (struct ast_channel * chan)
Definition at line 920 of file channel_internal_api.c.
References ast_party_id_merge().
Referenced by misdn_copy_redirecting_from_ast().
 {
    return ast_party_id_merge(&chan->redirecting.to, &chan->redirecting.priv_to);
 }
ast_channel_redirecting_set()
void ast_channel_redirecting_set (struct ast_channel * chan, struct ast_party_redirecting * value)
Definition at line 959 of file channel_internal_api.c.
References AST_CHANNEL_SNAPSHOT_INVALIDATE_CALLER, ast_channel_snapshot_invalidate_segment(), ast_channel::redirecting, and value.
Referenced by channel_do_masquerade().
 {
    chan->redirecting = *value;
    ast_channel_snapshot_invalidate_segment(chan, AST_CHANNEL_SNAPSHOT_INVALIDATE_CALLER);
 }
ast_channel_rings()
int ast_channel_rings (const struct ast_channel * chan)
Definition at line 453 of file channel_internal_api.c.
Referenced by __analog_handle_event(), ast_var_channels_table(), and serialize_showchan().
 {
    return chan->rings;
 }
ast_channel_rings_set()
void ast_channel_rings_set (struct ast_channel * chan, int value)
Definition at line 457 of file channel_internal_api.c.
References value.
Referenced by __analog_handle_event(), __analog_ss_thread(), analog_ss_thread(), cb_events(), chan_pjsip_new(), dahdi_handle_event(), dahdi_new(), jingle_new(), mbl_new(), mgcp_new(), misdn_new(), nbs_new(), ooh323_new(), phone_answer(), phone_new(), sip_new(), skinny_new(), and unistim_new().
 {
    chan->rings = value;
 }
ast_channel_sched()
struct ast_sched_context* ast_channel_sched (const struct ast_channel * chan)
Definition at line 729 of file channel_internal_api.c.
References ast_channel::sched.
Referenced by ast_channel_destructor(), ast_hangup(), ast_readaudio_callback(), ast_readvideo_callback(), background_detect_exec(), dial_exec_full(), filestream_close(), handle_speechrecognize(), speech_background(), wait_for_winner(), and waitstream_core().
 {
    return chan->sched;
 }
ast_channel_sched_set()
void ast_channel_sched_set (struct ast_channel * chan, struct ast_sched_context * value)
Definition at line 733 of file channel_internal_api.c.
References ast_channel::sched, and value.
Referenced by __ast_channel_alloc_ap(), and ast_hangup().
 {
    chan->sched = value;
 }
ast_channel_sending_dtmf_digit()
char ast_channel_sending_dtmf_digit (const struct ast_channel * chan)
Definition at line 388 of file channel_internal_api.c.
Referenced by ast_senddigit_end(), bridge_channel_internal_join(), and channel_do_masquerade().
 {
    return chan->sending_dtmf_digit;
 }
ast_channel_sending_dtmf_digit_set()
void ast_channel_sending_dtmf_digit_set (struct ast_channel * chan, char value)
Definition at line 392 of file channel_internal_api.c.
References value.
Referenced by ast_senddigit_begin(), and ast_senddigit_end().
 {
    chan->sending_dtmf_digit = value;
 }
ast_channel_sending_dtmf_tv()
struct timeval ast_channel_sending_dtmf_tv (const struct ast_channel * chan)
Definition at line 397 of file channel_internal_api.c.
Referenced by bridge_channel_internal_join(), and channel_do_masquerade().
 {
    return chan->sending_dtmf_tv;
 }
ast_channel_sending_dtmf_tv_set()
void ast_channel_sending_dtmf_tv_set (struct ast_channel * chan, struct timeval value)
Definition at line 401 of file channel_internal_api.c.
References value.
Referenced by ast_senddigit_begin().
 {
    chan->sending_dtmf_tv = value;
 }
ast_channel_set_is_t38_active()
void ast_channel_set_is_t38_active (struct ast_channel * chan, int is_t38_active)
Sets the is_t38_active flag.
Parameters
chan Which channel is having its is_t38_active value set
is_t38_active Non-zero if T.38 is active
Definition at line 1061 of file channel_internal_api.c.
References ast_channel_lock, ast_channel_set_is_t38_active_nolock(), and ast_channel_unlock.
 {
    ast_channel_lock(chan);
    ast_channel_set_is_t38_active_nolock(chan, is_t38_active);
    ast_channel_unlock(chan);
 }
ast_channel_set_is_t38_active_nolock()
void ast_channel_set_is_t38_active_nolock (struct ast_channel * chan, int is_t38_active)
Variant of ast_channel_set_is_t38_active. Use this if the channel is already locked prior to calling.
Parameters
chan Which channel is having its is_t38_active value set
is_t38_active Non-zero if T.38 is active
Definition at line 1056 of file channel_internal_api.c.
Referenced by ast_channel_set_is_t38_active(), and indicate_data_internal().
 {
    chan->is_t38_active = !!is_t38_active;
 }
ast_channel_set_oldwriteformat()
void ast_channel_set_oldwriteformat (struct ast_channel * chan, struct ast_format * format)
Definition at line 824 of file channel_internal_api.c.
References ao2_replace.
Referenced by ast_channel_destructor(), and ast_openstream_full().
 {
    ao2_replace(chan->oldwriteformat, format);
 }
ast_channel_set_rawreadformat()
void ast_channel_set_rawreadformat (struct ast_channel * chan, struct ast_format * format)
Definition at line 828 of file channel_internal_api.c.
References ao2_replace.
Referenced by __ast_channel_alloc_ap(), ast_channel_destructor(), ast_iax2_new(), ast_set_read_format_path(), AST_TEST_DEFINE(), ast_unreal_new_channels(), audiosocket_request(), chan_pjsip_new(), channel_do_masquerade(), dahdi_new(), do_notify(), jingle_new(), mbl_new(), mgcp_new(), misdn_new(), multicast_rtp_request(), nbs_new(), ooh323_new(), phone_new(), rec_request(), set_test_formats(), sip_new(), sip_session_response_cb(), skinny_new(), stasis_app_control_snoop(), test_vm_api_create_mock_channel(), unicast_rtp_request(), and unistim_new().
 {
    ao2_replace(chan->rawreadformat, format);
 }
ast_channel_set_rawwriteformat()
void ast_channel_set_rawwriteformat (struct ast_channel * chan, struct ast_format * format)
Definition at line 832 of file channel_internal_api.c.
References ao2_replace.
Referenced by __ast_channel_alloc_ap(), ast_channel_destructor(), ast_iax2_new(), ast_set_write_format_path(), AST_TEST_DEFINE(), ast_unreal_new_channels(), audiosocket_request(), chan_pjsip_new(), channel_do_masquerade(), dahdi_new(), do_notify(), jingle_new(), mbl_new(), mgcp_new(), misdn_new(), multicast_rtp_request(), nbs_new(), ooh323_new(), phone_new(), rec_request(), set_test_formats(), sip_new(), sip_session_response_cb(), skinny_new(), stasis_app_control_snoop(), test_vm_api_create_mock_channel(), unicast_rtp_request(), and unistim_new().
 {
    ao2_replace(chan->rawwriteformat, format);
 }
ast_channel_set_readformat()
void ast_channel_set_readformat (struct ast_channel * chan, struct ast_format * format)
Definition at line 836 of file channel_internal_api.c.
References ao2_replace.
Referenced by __ast_channel_alloc_ap(), alsa_new(), ast_channel_destructor(), ast_channel_yank(), ast_iax2_new(), ast_set_read_format_path(), AST_TEST_DEFINE(), ast_unreal_new_channels(), audiosocket_request(), chan_pjsip_new(), console_new(), dahdi_new(), do_notify(), iax2_request(), jingle_new(), mbl_new(), mgcp_new(), misdn_new(), multicast_rtp_request(), nbs_new(), oss_new(), rec_request(), set_test_formats(), sip_new(), sip_session_response_cb(), skinny_new(), start_rtp(), stasis_app_control_snoop(), test_vm_api_create_mock_channel(), unicast_rtp_request(), and unistim_new().
 {
    ao2_replace(chan->readformat, format);
 }
ast_channel_set_stream_topology()
struct ast_stream_topology* ast_channel_set_stream_topology (struct ast_channel * chan, struct ast_stream_topology * topology)
Set the topology of streams on a channel.
Parameters
chan The channel to set the stream topology on
topology The stream topology to set
Precondition
chan is locked
Note
If topology is NULL a new empty topology will be created and returned.
Return values
non-NULL Success
NULL failure
Definition at line 1591 of file channel_internal_api.c.
References ast_assert, ast_channel_internal_set_stream_topology(), ast_channel_is_multistream(), ast_channel_name(), ast_str_tmp, ast_stream_topology_alloc(), ast_stream_topology_to_str(), NULL, SCOPE_ENTER, and SCOPE_EXIT_RTN_VALUE.
Referenced by AST_TEST_DEFINE(), ast_unreal_indicate(), ast_unreal_new_channels(), chan_pjsip_new(), handle_negotiated_sdp(), make_channel(), and unreal_colp_stream_topology_request_change().
 {
    struct ast_stream_topology *new_topology;
    SCOPE_ENTER(1, "%s: %s\n", ast_channel_name(chan),
       ast_str_tmp(256, ast_stream_topology_to_str(topology, &STR_TMP)));
    ast_assert(chan != NULL);
    /* A non-MULTISTREAM channel can't manipulate topology directly */
    ast_assert(ast_channel_is_multistream(chan));
    /* Unless the channel is being destroyed, we always want a topology on
     * it even if its empty.
     */
    if (!topology) {
       new_topology = ast_stream_topology_alloc();
    } else {
       new_topology = topology;
    }
    if (new_topology) {
       ast_channel_internal_set_stream_topology(chan, new_topology);
    }
    SCOPE_EXIT_RTN_VALUE(new_topology, "Used %s topology\n", topology ? "provided" : "empty");
 }
ast_channel_set_unbridged()
void ast_channel_set_unbridged (struct ast_channel * chan, int value)
Sets the unbridged flag and queues a NULL frame on the channel to trigger a check by bridge_channel_wait.
Parameters
chan Which channel is having its unbridged value set
value What the unbridge value is being set to
Definition at line 1034 of file channel_internal_api.c.
References ast_channel_lock, ast_channel_set_unbridged_nolock(), and ast_channel_unlock.
Referenced by ast_bridge_setup_after_goto(), bridge_channel_wait(), and t38_change_state().
 {
    ast_channel_lock(chan);
    ast_channel_set_unbridged_nolock(chan, value);
    ast_channel_unlock(chan);
 }
ast_channel_set_unbridged_nolock()
void ast_channel_set_unbridged_nolock (struct ast_channel * chan, int value)
Variant of ast_channel_set_unbridged. Use this if the channel is already locked prior to calling.
Parameters
chan Which channel is having its unbridged value set
value What the unbridge value is being set to
Definition at line 1028 of file channel_internal_api.c.
References ast_null_frame, ast_queue_frame(), and value.
Referenced by ast_audiohook_attach(), ast_audiohook_remove(), ast_channel_set_unbridged(), ast_framehook_attach(), ast_framehook_detach(), ast_framehook_list_fixup(), audio_audiohook_write_list(), chan_pjsip_read_stream(), dtmf_audiohook_write_list(), and set_caps().
 {
    chan->unbridged = !!value;
    ast_queue_frame(chan, &ast_null_frame);
 }
ast_channel_set_writeformat()
void ast_channel_set_writeformat (struct ast_channel * chan, struct ast_format * format)
Definition at line 840 of file channel_internal_api.c.
References ao2_replace.
Referenced by __ast_channel_alloc_ap(), alsa_new(), ast_channel_destructor(), ast_channel_yank(), ast_iax2_new(), ast_set_write_format_path(), AST_TEST_DEFINE(), ast_unreal_new_channels(), audiosocket_request(), chan_pjsip_new(), console_new(), dahdi_new(), do_notify(), iax2_request(), jingle_new(), mbl_new(), mgcp_new(), misdn_new(), multicast_rtp_request(), nbs_new(), oss_new(), rec_request(), set_test_formats(), sip_new(), sip_session_response_cb(), skinny_new(), start_rtp(), stasis_app_control_snoop(), test_vm_api_create_mock_channel(), unicast_rtp_request(), and unistim_new().
 {
    ao2_replace(chan->writeformat, format);
 }
ast_channel_snapshot()
struct ast_channel_snapshot* ast_channel_snapshot (const struct ast_channel * chan)
Definition at line 1648 of file channel_internal_api.c.
Referenced by aoc_publish_blob(), ast_channel_blob_create(), ast_channel_snapshot_create(), and channel_snapshot_update_create().
 {
    return chan->snapshot;
 }
ast_channel_snapshot_segment_flags()
struct ast_flags* ast_channel_snapshot_segment_flags (struct ast_channel * chan)
Definition at line 1659 of file channel_internal_api.c.
Referenced by ast_channel_publish_snapshot(), ast_channel_snapshot_create(), ast_channel_snapshot_invalidate_segment(), and channel_do_masquerade().
 {
    return &chan->snapshot_segment_flags;
 }
ast_channel_snapshot_set()
void ast_channel_snapshot_set (struct ast_channel * chan, struct ast_channel_snapshot * snapshot)
Definition at line 1653 of file channel_internal_api.c.
References ao2_bump, and ao2_cleanup.
Referenced by ast_channel_publish_final_snapshot(), and ast_channel_publish_snapshot().
 {
    ao2_cleanup(chan->snapshot);
    chan->snapshot = ao2_bump(snapshot);
 }
ast_channel_softhangup_internal_flag()
int ast_channel_softhangup_internal_flag (struct ast_channel * chan)
Definition at line 997 of file channel_internal_api.c.
Referenced by __ast_pbx_run(), __ast_read(), _macro_exec(), agent_request_exec(), ast_autoservice_stop(), ast_bridge_call_with_flags(), ast_bridge_join(), ast_bridge_setup_after_goto(), ast_channel_clear_softhangup(), ast_channel_end_dtmf(), ast_channel_is_leaving_bridge(), ast_channel_snapshot_create(), ast_check_hangup(), collect_digits(), gosub_run(), park_and_announce_app_exec(), park_app_exec(), and waitstream_core().
 {
    return chan->softhangup;
 }
ast_channel_softhangup_internal_flag_add()
void ast_channel_softhangup_internal_flag_add (struct ast_channel * chan, int value)
Definition at line 1005 of file channel_internal_api.c.
References value.
Referenced by __ast_read(), ast_check_hangup(), ast_dsp_process(), ast_queue_hangup(), ast_queue_hangup_with_cause(), ast_softhangup_nolock(), ast_waitfor_nandfds(), ast_write_stream(), attempt_transfer(), dahdi_handle_event(), handle_clear_alarms(), iax2_key_rotate(), onCallCleared(), and sip_pvt_dtor().
 {
    chan->softhangup |= value;
 }
ast_channel_softhangup_internal_flag_clear()
void ast_channel_softhangup_internal_flag_clear (struct ast_channel * chan, int value)
Definition at line 1009 of file channel_internal_api.c.
Referenced by ast_channel_clear_softhangup().
 {
    chan ->softhangup &= ~value;
 }
ast_channel_softhangup_internal_flag_set()
void ast_channel_softhangup_internal_flag_set (struct ast_channel * chan, int value)
Definition at line 1001 of file channel_internal_api.c.
References value.
Referenced by channel_do_masquerade().
 {
    chan->softhangup = value;
 }
ast_channel_state()
enum ast_channel_state ast_channel_state (const struct ast_channel * chan)
Definition at line 789 of file channel_internal_api.c.
 {
    return chan->state;
 }
ast_channel_state_set()
void ast_channel_state_set (struct ast_channel * chan, enum ast_channel_state value)
Definition at line 820 of file channel_internal_api.c.
References value.
Referenced by __ast_channel_alloc_ap(), ast_setstate(), AST_TEST_DEFINE(), and channel_do_masquerade().
 {
    chan->state = value;
 }
ast_channel_stream()
struct ast_filestream* ast_channel_stream (const struct ast_channel * chan)
Definition at line 621 of file channel_internal_api.c.
References ast_channel::stream.
Referenced by ast_hangup(), ast_moh_files_next(), ast_openstream_full(), ast_readstring_full(), ast_stopstream(), background_detect_exec(), control_streamfile(), dial_exec_full(), filehelper(), handle_getoption(), handle_speechrecognize(), handle_streamfile(), local_ast_moh_stop(), moh_files_readframe(), moh_files_release(), speech_background(), wait_for_winner(), waitstream_control(), and waitstream_core().
 {
    return chan->stream;
 }
ast_channel_stream_set()
void ast_channel_stream_set (struct ast_channel * chan, struct ast_filestream * value)
Definition at line 625 of file channel_internal_api.c.
References ast_channel::stream, and value.
Referenced by ast_hangup(), ast_moh_files_next(), ast_stopstream(), dictate_exec(), filehelper(), filestream_close(), gen_closestream(), handle_recordfile(), local_ast_moh_stop(), and moh_files_release().
 {
    chan->stream = value;
 }
ast_channel_streamid()
int ast_channel_streamid (const struct ast_channel * chan)
Definition at line 461 of file channel_internal_api.c.
Referenced by filestream_close(), handle_speechrecognize(), and speech_background().
 {
    return chan->streamid;
 }
ast_channel_streamid_set()
void ast_channel_streamid_set (struct ast_channel * chan, int value)
Definition at line 465 of file channel_internal_api.c.
References value.
Referenced by __ast_channel_alloc_ap(), ast_readaudio_callback(), and filestream_close().
 {
    chan->streamid = value;
 }
ast_channel_tech()
const struct ast_channel_tech* ast_channel_tech (const struct ast_channel * chan)
Definition at line 769 of file channel_internal_api.c.
References ast_channel::tech.
Referenced by __ast_read(), acf_channel_read(), action_dahdishowchannels(), analog_ss_thread(), ast_ari_channels_rtpstatistics(), ast_call(), ast_channel_early_bridge(), ast_channel_queryoption(), ast_channel_request_stream_topology_change(), ast_channel_sendhtml(), ast_channel_setoption(), ast_channel_snapshot_create(), ast_channel_stream_topology_changed(), ast_channel_supports_html(), ast_hangup(), ast_jb_do_usecheck(), ast_pre_call(), ast_raw_answer_with_stream_topology(), ast_rtp_dtmf_compatible(), ast_rtp_instance_early_bridge(), ast_rtp_instance_early_bridge_make_compatible(), ast_rtp_instance_make_compatible(), ast_send_image(), ast_senddigit(), ast_senddigit_begin(), ast_senddigit_end(), ast_senddigit_external(), ast_senddigit_mf(), ast_sendtext_data(), ast_supports_images(), ast_transfer_protocol(), ast_var_channel_types_table(), ast_var_channels_table(), ast_write_stream(), ast_write_video(), channel_do_masquerade(), channel_sanitizer(), channel_snapshot_base_create(), conf_run(), dahdi_setoption(), dahdiras_exec(), destroy_all_channels(), flash_exec(), func_channel_read(), func_channel_write_real(), func_header_read(), func_headers_read2(), function_iaxpeer(), function_ooh323_read(), function_ooh323_write(), generate_status(), handle_request_bye(), handle_showchan(), iax2_key_rotate(), iax2_prov_app(), indicate_data_internal(), misdn_facility_exec(), misdn_set_opt_exec(), my_get_sigpvt_bridged_channel(), native_bridge_is_capable(), pjsip_acf_channel_read(), pjsip_acf_dtmf_mode_read(), pjsip_acf_dtmf_mode_write(), pjsip_acf_media_offer_read(), pjsip_acf_media_offer_write(), pjsip_acf_moh_passthrough_read(), pjsip_acf_moh_passthrough_write(), pjsip_acf_session_refresh_write(), push_notify_channel(), reload(), rtp_glue_data_get(), sendtext_exec(), serialize_showchan(), setup_env(), sip_acf_channel_read(), sip_cc_agent_init(), sip_dtmfmode(), sipinfo_send(), softhangup_exec(), t38_masq(), tech_write(), transfer_exec(), and try_calling().
 {
    return chan->tech;
 }
ast_channel_tech_pvt()
void* ast_channel_tech_pvt (const struct ast_channel * chan)
Definition at line 565 of file channel_internal_api.c.
References ast_channel::tech_pvt.
Referenced by __analog_ss_thread(), __dahdi_exception(), acf_channel_read(), action_dahdishowchannels(), alsa_fixup(), analog_hangup(), analog_ss_thread(), announce_hangup(), ast_channel_destructor(), ast_local_get_peer(), ast_local_lock_all(), ast_local_setup_bridge(), ast_local_setup_masquerade(), AST_TEST_DEFINE(), ast_unreal_answer(), ast_unreal_channel_push_to_bridge(), ast_unreal_digit_begin(), ast_unreal_digit_end(), ast_unreal_fixup(), ast_unreal_indicate(), ast_unreal_queryoption(), ast_unreal_sendhtml(), ast_unreal_sendtext(), ast_unreal_setoption(), ast_unreal_write_stream(), audiosocket_call(), audiosocket_hangup(), audiosocket_read(), audiosocket_write(), chan_pjsip_answer(), chan_pjsip_call(), chan_pjsip_digit_begin(), chan_pjsip_digit_end(), chan_pjsip_fixup(), chan_pjsip_get_rtp_peer(), chan_pjsip_get_uniqueid(), chan_pjsip_get_vrtp_peer(), chan_pjsip_hangup(), chan_pjsip_indicate(), chan_pjsip_queryoption(), chan_pjsip_read_stream(), chan_pjsip_sendtext_data(), chan_pjsip_set_rtp_peer(), chan_pjsip_transfer(), chan_pjsip_write_stream(), channel_do_masquerade(), channel_read_pjsip(), channel_read_rtcp(), channel_read_rtp(), channel_to_session(), cli_channelstats_print_body(), conf_announce_channel_push(), console_answer(), console_call(), console_fixup(), console_hangup(), console_indicate(), console_write(), dahdi_answer(), dahdi_call(), dahdi_callwait(), dahdi_digit_begin(), dahdi_digit_end(), dahdi_exception(), dahdi_fixup(), dahdi_func_read(), dahdi_func_write(), dahdi_handle_dtmf(), dahdi_handle_event(), dahdi_hangup(), dahdi_indicate(), dahdi_queryoption(), dahdi_read(), dahdi_sendtext(), dahdi_setoption(), dahdi_write(), destroy_all_channels(), dialog_unlink_all(), func_header_read(), func_headers_read2(), func_read_header(), func_write_header(), function_iaxpeer(), function_ooh323_read(), function_ooh323_write(), get_video_desc(), handle_callforward_button(), handle_clear_alarms(), handle_enbloc_call_message(), handle_offhook_message(), handle_request_bye(), handle_soft_key_event_message(), handle_stimulus_message(), handle_transfer_button(), hangup(), iax2_answer(), iax2_call(), iax2_digit_begin(), iax2_digit_end(), iax2_fixup(), iax2_hangup(), iax2_indicate(), iax2_key_rotate(), iax2_prov_app(), iax2_queryoption(), iax2_sendhtml(), iax2_sendimage(), iax2_sendtext(), iax2_setoption(), iax2_transfer(), iax2_write(), jingle_answer(), jingle_call(), jingle_digit_begin(), jingle_digit_end(), jingle_fixup(), jingle_get_rtp_peer(), jingle_hangup(), jingle_indicate(), jingle_read(), jingle_sendtext(), jingle_write(), load_stream_readqueue(), local_call(), local_hangup(), manager_optimize_away(), mbl_answer(), mbl_call(), mbl_digit_end(), mbl_fixup(), mbl_hangup(), mbl_read(), mbl_write(), media_hangup(), mgcp_answer(), mgcp_call(), mgcp_fixup(), mgcp_get_codec(), mgcp_get_rtp_peer(), mgcp_hangup(), mgcp_indicate(), mgcp_read(), mgcp_senddigit_begin(), mgcp_senddigit_end(), mgcp_set_rtp_peer(), mgcp_ss(), mgcp_write(), mock_channel_hangup(), mock_channel_indicate(), mock_channel_read(), mock_channel_write(), mock_channel_write_stream(), my_get_sigpvt_bridged_channel(), native_bridge_is_capable(), native_chan_changed(), native_start(), native_stop(), nbs_call(), nbs_hangup(), nbs_xwrite(), ooh323_answer(), ooh323_call(), ooh323_digit_begin(), ooh323_digit_end(), ooh323_fixup(), ooh323_get_codec(), ooh323_get_rtp_peer(), ooh323_get_vrtp_peer(), ooh323_hangup(), ooh323_indicate(), ooh323_queryoption(), ooh323_read(), ooh323_set_rtp_peer(), ooh323_write(), oss_answer(), oss_call(), oss_fixup(), oss_hangup(), oss_indicate(), oss_read(), oss_write(), phone_answer(), phone_call(), phone_digit_end(), phone_exception(), phone_fixup(), phone_hangup(), phone_indicate(), phone_read(), phone_send_text(), phone_setup(), phone_write(), pjsip_acf_channel_read(), pjsip_acf_dtmf_mode_read(), pjsip_acf_dtmf_mode_write(), pjsip_acf_media_offer_read(), pjsip_acf_media_offer_write(), pjsip_acf_moh_passthrough_read(), pjsip_acf_moh_passthrough_write(), pjsip_acf_session_refresh_write(), push_notify_channel(), read_test(), rtp_call(), rtp_hangup(), rtp_read(), rtp_write(), send_direct_media_request(), sendtext_data_create(), sip_acf_channel_read(), sip_allow_anyrtp_remote(), sip_answer(), sip_call(), sip_cc_agent_init(), sip_dtmfmode(), sip_fixup(), sip_get_callid(), sip_get_rtp_peer(), sip_get_trtp_peer(), sip_get_vrtp_peer(), sip_hangup(), sip_indicate(), sip_queryoption(), sip_read(), sip_senddigit_begin(), sip_senddigit_end(), sip_sendhtml(), sip_sendtext(), sip_set_rtp_peer(), sip_setoption(), sip_transfer(), sip_write(), sipinfo_send(), skinny_answer(), skinny_call(), skinny_fixup(), skinny_get_rtp_peer(), skinny_get_vrtp_peer(), skinny_hangup(), skinny_indicate(), skinny_newcall(), skinny_read(), skinny_request(), skinny_set_rtp_peer(), skinny_write(), snoop_fixup(), snoop_hangup(), snoop_read(), snoop_write(), stasis_app_channel_unreal_set_internal(), t38_framehook(), test_bridging_chan_hangup(), test_bridging_chan_indicate(), unistim_answer(), unistim_call(), unistim_fixup(), unistim_get_rtp_peer(), unistim_hangup(), unistim_indicate(), unistim_read(), unistim_set_rtp_peer(), unistim_ss(), and unistim_write().
 {
    return chan->tech_pvt;
 }
ast_channel_tech_pvt_set()
void ast_channel_tech_pvt_set (struct ast_channel * chan, void * value)
Definition at line 569 of file channel_internal_api.c.
References ast_channel::tech_pvt, and value.
Referenced by alsa_hangup(), alsa_new(), ast_iax2_new(), AST_TEST_DEFINE(), ast_unreal_hangup(), ast_unreal_new_channels(), audiosocket_hangup(), audiosocket_request(), chan_pjsip_new(), channel_do_masquerade(), clear_session_and_channel(), console_hangup(), console_new(), dahdi_hangup(), dahdi_new(), destroy_dahdi_pvt(), dialog_unlink_all(), iax2_hangup(), iax2_predestroy(), jingle_hangup(), jingle_new(), kill_hangup(), make_channel(), mbl_hangup(), mbl_new(), mgcp_hangup(), mgcp_new(), mock_channel_hangup(), multicast_rtp_request(), my_on_hook(), nbs_hangup(), nbs_new(), onCallCleared(), ooh323_destroy(), ooh323_hangup(), ooh323_new(), oss_hangup(), oss_new(), phone_hangup(), phone_new(), rtp_hangup(), sip_hangup(), sip_new(), sip_pvt_dtor(), skinny_hangup(), skinny_new(), snoop_hangup(), stasis_app_control_snoop(), test_bridging_chan_hangup(), unicast_rtp_request(), unistim_hangup_clean(), and unistim_new().
 {
    chan->tech_pvt = value;
 }
ast_channel_tech_set()
void ast_channel_tech_set (struct ast_channel * chan, const struct ast_channel_tech * value)
Definition at line 773 of file channel_internal_api.c.
References ast_assert, ast_channel_tech::read_stream, ast_channel::tech, value, and ast_channel_tech::write_stream.
Referenced by __ast_channel_alloc_ap(), alsa_new(), ast_iax2_new(), AST_TEST_DEFINE(), ast_unreal_new_channels(), audiosocket_request(), chan_pjsip_new(), channel_do_masquerade(), console_new(), create_alice_channel(), create_msg_q_chan(), dahdi_new(), do_notify(), jingle_new(), make_channel(), mbl_new(), mgcp_new(), misdn_new(), multicast_rtp_request(), nbs_new(), ooh323_new(), oss_new(), phone_new(), rec_request(), sip_new(), skinny_new(), stasis_app_control_snoop(), test_vm_api_create_mock_channel(), unicast_rtp_request(), and unistim_new().
 {
    if (value->read_stream || value->write_stream) {
       ast_assert(value->read_stream && value->write_stream);
    }
    chan->tech = value;
 }
ast_channel_timer()
struct ast_timer* ast_channel_timer (const struct ast_channel * chan)
Definition at line 737 of file channel_internal_api.c.
Referenced by __ast_channel_alloc_ap(), __ast_queue_frame(), __ast_read(), ast_channel_destructor(), ast_deactivate_generator(), and ast_settimeout_full().
 {
    return chan->timer;
 }
ast_channel_timer_set()
void ast_channel_timer_set (struct ast_channel * chan, struct ast_timer * value)
Definition at line 741 of file channel_internal_api.c.
References value.
Referenced by __ast_channel_alloc_ap(), and ast_channel_destructor().
 {
    chan->timer = value;
 }
ast_channel_timingdata()
void* ast_channel_timingdata (const struct ast_channel * chan)
Definition at line 573 of file channel_internal_api.c.
References ast_channel::timingdata.
Referenced by __ast_read(), and ast_settimeout_full().
 {
    return chan->timingdata;
 }
ast_channel_timingdata_set()
void ast_channel_timingdata_set (struct ast_channel * chan, void * value)
Definition at line 577 of file channel_internal_api.c.
References ast_channel::timingdata, and value.
Referenced by ast_settimeout_full().
 {
    chan->timingdata = value;
 }
ast_channel_timingfd()
int ast_channel_timingfd (const struct ast_channel * chan)
Definition at line 469 of file channel_internal_api.c.
Referenced by __ast_channel_alloc_ap(), __ast_queue_frame(), __ast_read(), add_sdp(), ast_readaudio_callback(), ast_settimeout_full(), and channel_do_masquerade().
 {
    return chan->timingfd;
 }
ast_channel_timingfd_set()
void ast_channel_timingfd_set (struct ast_channel * chan, int value)
Definition at line 473 of file channel_internal_api.c.
References value.
Referenced by __ast_channel_alloc_ap(), and __ast_dummy_channel_alloc().
 {
    chan->timingfd = value;
 }
ast_channel_timingfunc()
ast_timing_func_t ast_channel_timingfunc (const struct ast_channel * chan)
Definition at line 1231 of file channel_internal_api.c.
References ast_channel::timingfunc.
Referenced by __ast_read(), ast_read_generator_actions(), background_detect_exec(), dial_exec_full(), handle_speechrecognize(), speech_background(), wait_for_winner(), and waitstream_core().
 {
    return chan->timingfunc;
 }
ast_channel_timingfunc_set()
void ast_channel_timingfunc_set (struct ast_channel * chan, ast_timing_func_t value)
Definition at line 1235 of file channel_internal_api.c.
References ast_channel::timingfunc, and value.
Referenced by ast_settimeout_full().
 {
    chan->timingfunc = value;
 }
ast_channel_topic()
struct stasis_topic* ast_channel_topic (struct ast_channel * chan)
A topic which publishes the events for a particular channel.
Since
12 If the given chan is NULL, ast_channel_topic_all() is returned.
Parameters
chan Channel, or NULL.
Return values
Topic for channel's events.
ast_channel_topic_all() if chan is NULL.
Definition at line 1502 of file channel_internal_api.c.
References ast_channel_topic_all().
Referenced by ari_bridges_play_new(), ast_ari_bridges_record(), ast_channel_forward_endpoint(), ast_channel_internal_setup_topics(), ast_channel_publish_blob(), ast_channel_publish_cached_blob(), ast_channel_publish_final_snapshot(), ast_channel_publish_snapshot(), ast_monitor_start(), ast_monitor_stop(), ast_multi_object_blob_single_channel_publish(), AST_TEST_DEFINE(), forwards_create_channel(), local_optimization_finished_cb(), local_optimization_started_cb(), manager_mute_mixmonitor(), meetme_stasis_generate_msg(), mixmonitor_exec(), moh_post_start(), moh_post_stop(), phase_e_handler(), publish_chanspy_message(), publish_local_bridge_message(), publish_message_for_channel_topics(), queue_publish_multi_channel_blob(), report_fax_status(), report_receive_fax_status(), report_send_fax_status(), send_call_pickup_stasis_message(), send_conf_stasis(), stasis_app_control_publish(), stop_mixmonitor_full(), and talk_detect_audiohook_cb().
 {
    if (!chan) {
       return ast_channel_topic_all();
    }
    return chan->topic;
 }
ast_channel_transfercapability()
unsigned short ast_channel_transfercapability (const struct ast_channel * chan)
Definition at line 501 of file channel_internal_api.c.
Referenced by ast_ari_channels_dial(), ast_var_channels_table(), begin_dial_prerun(), dahdi_call(), dial_exec_full(), func_channel_read(), misdn_call(), and ooh323_call().
 {
    return chan->transfercapability;
 }
ast_channel_transfercapability_set()
void ast_channel_transfercapability_set (struct ast_channel * chan, unsigned short value)
Definition at line 505 of file channel_internal_api.c.
References value.
Referenced by ast_ari_channels_dial(), begin_dial_prerun(), cb_events(), dial_exec_full(), and func_channel_write_real().
 {
    chan->transfercapability = value;
 }
ast_channel_unbridged()
int ast_channel_unbridged (struct ast_channel * chan)
This function will check if the bridge needs to be re-evaluated due to external changes.
Parameters
chan Channel on which to check the unbridge_eval flag
Returns
Returns 0 if the flag is down or 1 if the flag is up.
Definition at line 1019 of file channel_internal_api.c.
References ast_channel_lock, ast_channel_unbridged_nolock(), and ast_channel_unlock.
Referenced by ast_channel_is_leaving_bridge(), and bridge_channel_wait().
 {
    int res;
    ast_channel_lock(chan);
    res = ast_channel_unbridged_nolock(chan);
    ast_channel_unlock(chan);
    return res;
 }
ast_channel_unbridged_nolock()
int ast_channel_unbridged_nolock (struct ast_channel * chan)
ast_channel_unbridged variant. Use this if the channel is already locked prior to calling.
Parameters
chan Channel on which to check the unbridge flag
Returns
Returns 0 if the flag is down or 1 if the flag is up.
Definition at line 1014 of file channel_internal_api.c.
Referenced by ast_channel_unbridged().
 {
    return chan->unbridged;
 }
ast_channel_uniqueid()
const char* ast_channel_uniqueid (const struct ast_channel * chan)
Definition at line 305 of file channel_internal_api.c.
References ast_assert, ast_channel_id::unique_id, and ast_channel::uniqueid.
Referenced by __ast_change_name_nolink(), action_confbridgelist_item(), action_dahdishowchannels(), app_exec(), app_subscribe_channel(), app_unsubscribe_channel(), apply_negotiated_sdp_stream(), aqm_exec(), ari_channels_handle_originate_with_id(), ari_channels_handle_snoop_channel(), ast_ari_channels_create(), ast_attended_transfer_message_add_app(), ast_attended_transfer_message_add_link(), ast_attended_transfer_message_add_threeway(), ast_attended_transfer_message_create(), ast_blind_transfer_message_create(), ast_bridge_blob_create(), ast_bridge_publish_enter(), ast_bridge_set_single_src_video_mode(), ast_bridge_snapshot_create(), ast_bridge_transfer_blind(), ast_bridge_update_talker_src_video_mode(), ast_cel_publish_event(), ast_channel_by_uniqueid_cb(), ast_channel_log(), ast_channel_move(), ast_channel_publish_cached_blob(), ast_channel_publish_dial_internal(), ast_do_pickup(), ast_endpoint_add_channel(), ast_monitor_start(), ast_monitor_stop(), ast_str_retrieve_variable(), AST_TEST_DEFINE(), ast_var_channels_table(), blind_transfer_bridge(), bridge_channel_depart(), bridge_channel_snapshot_pair_init(), bridge_moh_create(), bridge_stasis_push_peek(), build_conf(), call(), chan_pjsip_fixup(), chan_pjsip_indicate(), chan_pjsip_new(), chan_pjsip_session_end(), channel_replaced_cb(), channel_snapshot_base_create(), conf_rec_name(), conf_run(), conf_send_event_to_participants(), create_parked_subscription_full(), fast_originate(), fax_session_new(), find_by_uniqueid(), find_conf_realtime(), forwards_create_channel(), func_channel_read(), generate_status(), handle_showchan(), internal_bridge_after_cb(), jingle_enable_video(), jingle_set_owner(), local_channel_optimization_blob(), local_optimization_started_cb(), manager_mute_mixmonitor(), manager_park(), manager_park_bridged(), manager_queues_status(), masq_match_cb(), meetme_menu_admin_extended(), meetmemute(), mgcp_set_owner(), minivm_mwi_exec(), mixmonitor_exec(), moh_post_start(), moh_post_stop(), multicast_rtp_request(), notify_new_message(), pack_channel_into_message(), park_and_announce_app_exec(), park_common_setup(), park_local_transfer(), parking_blind_transfer_park(), parking_park_bridge_channel(), phase_e_handler(), play_on_channel(), publish_chanspy_message(), publish_local_bridge_message(), queue_exec(), queue_stasis_data_alloc(), record_file(), refer_blind_callback(), report_fax_status(), report_receive_fax_status(), report_send_fax_status(), rna(), rqm_exec(), serialize_showchan(), setup_env(), setup_mixmonitor(), sfu_topologies_on_join(), sfu_topologies_on_source_change(), sip_set_owner(), skinny_set_owner(), softmix_bridge_stream_sources_update(), start_rtp(), stasis_app_bridge_playback_channel_add(), stasis_app_control_find_by_channel(), stasis_app_control_get_channel_id(), stasis_app_control_snoop(), stasis_app_exec(), stasis_app_subscribe_channel(), stop_mixmonitor_full(), talk_detect_audiohook_cb(), test_cel_generate_peer_str(), try_calling(), unicast_rtp_request(), unistim_set_owner(), vm_execmain(), wait_for_answer(), and wait_our_turn().
 {
    ast_assert(chan->uniqueid.unique_id[0] != '\0');
    return chan->uniqueid.unique_id;
 }
ast_channel_varshead()
struct varshead* ast_channel_varshead (struct ast_channel * chan)
Definition at line 932 of file channel_internal_api.c.
References ast_channel::varshead.
Referenced by __ast_channel_alloc_ap(), __ast_dummy_channel_alloc(), ast_cel_fabricate_channel_from_event(), ast_channel_destructor(), ast_channel_get_vars(), ast_channel_inherit_variables(), ast_dummy_channel_destructor(), ast_str_retrieve_variable(), ast_str_substitute_variables_full(), AST_TEST_DEFINE(), ast_unreal_call_setup(), chan_cleanup(), clearvar_prefix(), clone_variables(), external_media_audiosocket_tcp(), external_media_rtp_udp(), generate_status(), handle_show_chanvar(), handle_showchan(), hashkeys_read(), hashkeys_read2(), inherit_channel_vars_from_id(), lua_get_variable(), lua_get_variable_value(), ospauth_exec(), ospfinished_exec(), osplookup_exec(), ospnext_exec(), pbx_builtin_getvar_helper(), pbx_builtin_pushvar_helper(), pbx_builtin_serialize_variables(), pbx_builtin_setvar_helper(), pbx_substitute_variables_helper(), pbx_substitute_variables_helper_full(), peek_read(), sip_call(), sip_removeheader(), skinny_call(), and transmit_invite().
 {
    return &chan->varshead;
 }
ast_channel_varshead_set()
void ast_channel_varshead_set (struct ast_channel * chan, struct varshead * value)
Definition at line 972 of file channel_internal_api.c.
References value, and ast_channel::varshead.
 {
    chan->varshead = *value;
 }
ast_channel_visible_indication()
int ast_channel_visible_indication (const struct ast_channel * chan)
Definition at line 477 of file channel_internal_api.c.
Referenced by channel_do_masquerade(), and pre_bridge_setup().
 {
    return chan->visible_indication;
 }
ast_channel_visible_indication_set()
void ast_channel_visible_indication_set (struct ast_channel * chan, int value)
Definition at line 481 of file channel_internal_api.c.
References value.
Referenced by dial_exec_full(), and indicate_data_internal().
 {
    chan->visible_indication = value;
 }
ast_channel_vstream()
struct ast_filestream* ast_channel_vstream (const struct ast_channel * chan)
Definition at line 629 of file channel_internal_api.c.
References ast_channel::vstream.
Referenced by ast_hangup(), ast_openvstream(), ast_stopstream(), and filehelper().
 {
    return chan->vstream;
 }
ast_channel_vstream_set()
void ast_channel_vstream_set (struct ast_channel * chan, struct ast_filestream * value)
Definition at line 633 of file channel_internal_api.c.
References value, and ast_channel::vstream.
Referenced by ast_hangup(), ast_stopstream(), filehelper(), and filestream_close().
 {
    chan->vstream = value;
 }
ast_channel_vstreamid()
int ast_channel_vstreamid (const struct ast_channel * chan)
Definition at line 493 of file channel_internal_api.c.
Referenced by filestream_close().
 {
    return chan->vstreamid;
 }
ast_channel_vstreamid_set()
void ast_channel_vstreamid_set (struct ast_channel * chan, int value)
Definition at line 497 of file channel_internal_api.c.
References value.
Referenced by __ast_channel_alloc_ap(), ast_readvideo_callback(), and filestream_close().
 {
    chan->vstreamid = value;
 }
ast_channel_whentohangup()
struct timeval* ast_channel_whentohangup (struct ast_channel * chan)
Definition at line 928 of file channel_internal_api.c.
References ast_channel::whentohangup.
Referenced by __ast_pbx_run(), ast_channel_cmpwhentohangup_tv(), ast_check_hangup(), ast_var_channels_table(), ast_waitfor_nandfds(), begin_dial_prerun(), dial_exec_full(), generate_status(), handle_showchan(), ring_entry(), serialize_showchan(), timeout_read(), and timeout_write().
 {
    return &chan->whentohangup;
 }
ast_channel_whentohangup_set()
void ast_channel_whentohangup_set (struct ast_channel * chan, struct timeval * value)
Precondition
chan is locked
Definition at line 968 of file channel_internal_api.c.
References value, and ast_channel::whentohangup.
Referenced by ast_channel_setwhentohangup_tv(), and dial_exec_full().
 {
    chan->whentohangup = *value;
 }
ast_channel_writeformat()
struct ast_format* ast_channel_writeformat (struct ast_channel * chan)
Definition at line 860 of file channel_internal_api.c.
Referenced by adsi_transmit_message_full(), agent_login_exec(), alarmreceiver_exec(), ast_bridge_channel_restore_formats(), ast_channel_start_silence_generator(), ast_channel_yank(), ast_openstream_full(), ast_read_generator_actions(), ast_set_write_format_path(), ast_streamfile(), ast_write_stream(), audiosocket_exec(), bridge_channel_internal_join(), chan_pjsip_read_stream(), chan_pjsip_write_stream(), channel_do_masquerade(), chanspy_exec(), dahdiscan_exec(), extenspy_exec(), fax_gateway_framehook(), filehelper(), func_channel_read(), generate_status(), generator_force(), generic_fax_exec(), handle_showchan(), handle_streamfile(), jingle_read(), jingle_write(), linear_alloc(), mgcp_rtp_read(), mgcp_write(), moh_alloc(), moh_files_alloc(), moh_files_write_format_change(), mp3_exec(), NBScat_exec(), ooh323_rtp_read(), ooh323_set_rtp_peer(), ooh323_set_write_format(), ooh323_write(), playtones_alloc(), process_sdp(), send_waveform_to_channel(), serialize_showchan(), set_caps(), sip_rtp_read(), sip_write(), skinny_rtp_read(), skinny_write(), socket_process_helper(), test_vm_api_create_mock_channel(), tonepair_alloc(), transmit_audio(), unistim_rtp_read(), and unistim_write().
 {
    return chan->writeformat;
 }
ast_channel_writetrans()
struct ast_trans_pvt* ast_channel_writetrans (const struct ast_channel * chan)
Definition at line 761 of file channel_internal_api.c.
References ast_channel::writetrans.
Referenced by __ast_read(), ast_channel_destructor(), ast_set_write_format_path(), ast_write_stream(), chan_pjsip_write_stream(), free_translation(), generate_status(), handle_showchan(), and serialize_showchan().
 {
    return chan->writetrans;
 }
ast_channel_writetrans_set()
void ast_channel_writetrans_set (struct ast_channel * chan, struct ast_trans_pvt * value)
Definition at line 765 of file channel_internal_api.c.
References value, and ast_channel::writetrans.
Referenced by ast_set_write_format_path(), and free_translation().
 {
    chan->writetrans = value;
 }
ast_channel_zone()
struct ast_tone_zone* ast_channel_zone (const struct ast_channel * chan)
Definition at line 745 of file channel_internal_api.c.
References ast_channel::zone.
Referenced by ast_app_dtget(), ast_channel_destructor(), ast_control_tone(), ast_var_channels_table(), dial_handle_playtones(), dialtone_indicate(), func_channel_read(), func_channel_write_real(), handle_playtones(), indicate_data_internal(), pbx_builtin_waitexten(), play_dialtone(), read_exec(), and readexten_exec().
 {
    return chan->zone;
 }
ast_channel_zone_set()
void ast_channel_zone_set (struct ast_channel * chan, struct ast_tone_zone * value)
Definition at line 749 of file channel_internal_api.c.
References value, and ast_channel::zone.
Referenced by ast_channel_destructor(), chan_pjsip_new(), func_channel_write_real(), and sip_new().
 {
    chan->zone = value;
 }
channel_set_default_streams()
static void channel_set_default_streams (struct ast_channel * chan) static
Definition at line 642 of file channel_internal_api.c.
References ast_assert, AST_MEDIA_TYPE_END, AST_MEDIA_TYPE_UNKNOWN, ast_stream_topology_get_first_stream_by_type(), NULL, and type.
Referenced by ast_channel_internal_set_stream_topology(), and ast_channel_internal_swap_stream_topology().
 {
    enum ast_media_type type;
    ast_assert(chan != NULL);
    for (type = AST_MEDIA_TYPE_UNKNOWN; type < AST_MEDIA_TYPE_END; type++) {
       if (chan->stream_topology) {
          chan->default_streams[type] =
             ast_stream_topology_get_first_stream_by_type(chan->stream_topology, type);
       } else {
          chan->default_streams[type] = NULL;
       }
    }
 }
collect_names_cb()
static int collect_names_cb (void * obj, void * arg, int flags) static
Definition at line 1265 of file channel_internal_api.c.
References ast_str_append(), ast_str_strlen(), ast_control_pvt_cause_code::chan_name, and str.
Referenced by ast_channel_dialed_causes_channels().
{
    struct ast_control_pvt_cause_code *cause_code = obj;
    struct ast_str **str = arg;
    ast_str_append(str, 0, "%s%s", (ast_str_strlen(*str) ? "," : ""), cause_code->chan_name);
    return 0;
 }
DEFINE_STRINGFIELD_GETTER_FOR() [1/11]
DEFINE_STRINGFIELD_GETTER_FOR (name)
DEFINE_STRINGFIELD_GETTER_FOR() [2/11]
DEFINE_STRINGFIELD_GETTER_FOR (language)
DEFINE_STRINGFIELD_GETTER_FOR() [3/11]
DEFINE_STRINGFIELD_GETTER_FOR (musicclass)
DEFINE_STRINGFIELD_GETTER_FOR() [4/11]
DEFINE_STRINGFIELD_GETTER_FOR (latest_musicclass)
DEFINE_STRINGFIELD_GETTER_FOR() [5/11]
DEFINE_STRINGFIELD_GETTER_FOR (accountcode)
DEFINE_STRINGFIELD_GETTER_FOR() [6/11]
DEFINE_STRINGFIELD_GETTER_FOR (peeraccount)
DEFINE_STRINGFIELD_GETTER_FOR() [7/11]
DEFINE_STRINGFIELD_GETTER_FOR (userfield)
DEFINE_STRINGFIELD_GETTER_FOR() [8/11]
DEFINE_STRINGFIELD_GETTER_FOR (call_forward)
DEFINE_STRINGFIELD_GETTER_FOR() [9/11]
DEFINE_STRINGFIELD_GETTER_FOR (parkinglot)
DEFINE_STRINGFIELD_GETTER_FOR() [10/11]
DEFINE_STRINGFIELD_GETTER_FOR (hangupsource)
DEFINE_STRINGFIELD_GETTER_FOR() [11/11]
DEFINE_STRINGFIELD_GETTER_FOR (dialcontext)
DEFINE_STRINGFIELD_SETTERS_AND_INVALIDATE_FOR() [1/6]
DEFINE_STRINGFIELD_SETTERS_AND_INVALIDATE_FOR (name , 0 , 1 , AST_CHANNEL_SNAPSHOT_INVALIDATE_BASE)
DEFINE_STRINGFIELD_SETTERS_AND_INVALIDATE_FOR() [2/6]
DEFINE_STRINGFIELD_SETTERS_AND_INVALIDATE_FOR (language , 1 , 0 , AST_CHANNEL_SNAPSHOT_INVALIDATE_BASE)
DEFINE_STRINGFIELD_SETTERS_AND_INVALIDATE_FOR() [3/6]
DEFINE_STRINGFIELD_SETTERS_AND_INVALIDATE_FOR (accountcode , 1 , 0 , AST_CHANNEL_SNAPSHOT_INVALIDATE_BASE)
DEFINE_STRINGFIELD_SETTERS_AND_INVALIDATE_FOR() [4/6]
DEFINE_STRINGFIELD_SETTERS_AND_INVALIDATE_FOR (peeraccount , 1 , 0 , AST_CHANNEL_SNAPSHOT_INVALIDATE_PEER)
DEFINE_STRINGFIELD_SETTERS_AND_INVALIDATE_FOR() [5/6]
DEFINE_STRINGFIELD_SETTERS_AND_INVALIDATE_FOR (userfield , 0 , 0 , AST_CHANNEL_SNAPSHOT_INVALIDATE_BASE)
DEFINE_STRINGFIELD_SETTERS_AND_INVALIDATE_FOR() [6/6]
DEFINE_STRINGFIELD_SETTERS_AND_INVALIDATE_FOR (hangupsource , 0 , 0 , AST_CHANNEL_SNAPSHOT_INVALIDATE_HANGUP)
DEFINE_STRINGFIELD_SETTERS_FOR() [1/5]
DEFINE_STRINGFIELD_SETTERS_FOR (musicclass , 0)
DEFINE_STRINGFIELD_SETTERS_FOR() [2/5]
DEFINE_STRINGFIELD_SETTERS_FOR (latest_musicclass , 0)
DEFINE_STRINGFIELD_SETTERS_FOR() [3/5]
DEFINE_STRINGFIELD_SETTERS_FOR (call_forward , 0)
DEFINE_STRINGFIELD_SETTERS_FOR() [4/5]
DEFINE_STRINGFIELD_SETTERS_FOR (parkinglot , 0)
DEFINE_STRINGFIELD_SETTERS_FOR() [5/5]
DEFINE_STRINGFIELD_SETTERS_FOR (dialcontext , 0)
pvt_cause_cmp_fn()
static int pvt_cause_cmp_fn (void * obj, void * vstr, int flags) static
Definition at line 1321 of file channel_internal_api.c.
References ast_strdupa, ast_tech_to_upper(), ast_control_pvt_cause_code::chan_name, CMP_MATCH, CMP_STOP, and str.
Referenced by __ast_channel_internal_alloc().
 {
    struct ast_control_pvt_cause_code *pc = obj;
    char *str = ast_tech_to_upper(ast_strdupa(vstr));
    char *pc_str = ast_tech_to_upper(ast_strdupa(pc->chan_name));
    return !strcmp(pc_str, str) ? CMP_MATCH | CMP_STOP : 0;
 }
pvt_cause_hash_fn()
static int pvt_cause_hash_fn (const void * vpc, const int flags) static
Definition at line 1314 of file channel_internal_api.c.
References ast_str_hash(), ast_strdupa, ast_tech_to_upper(), and ast_control_pvt_cause_code::chan_name.
Referenced by __ast_channel_internal_alloc().
 {
    const struct ast_control_pvt_cause_code *pc = vpc;
    return ast_str_hash(ast_tech_to_upper(ast_strdupa(pc->chan_name)));
 }
Variable Documentation
channel_errno
struct ast_threadstorage channel_errno = { .once = PTHREAD_ONCE_INIT , .key_init = __init_channel_errno , .custom_init = NULL , } static
Definition at line 1561 of file channel_internal_api.c.
Referenced by ast_channel_internal_errno(), and ast_channel_internal_errno_set().
uniqueint
int uniqueint static
The monotonically increasing integer counter for channel uniqueids.
Definition at line 228 of file channel_internal_api.c.