Asterisk - The Open Source Telephony Project: pbx_hangup_handler.c File Reference
pbx_hangup_handler.c File Reference
PBX Hangup Handler management routines.
#include "asterisk.h"
#include "asterisk/_private.h"
#include "asterisk/app.h"
#include "asterisk/cli.h"
#include "asterisk/linkedlists.h"
#include "asterisk/pbx.h"
#include "asterisk/stasis_channels.h"
#include "asterisk/utils.h"
Macros
#define HANDLER_FORMAT "%-30s %s\n"
Functions
void ast_pbx_hangup_handler_destroy (struct ast_channel *chan)
Destroy the hangup handler container on a channel.
static void ast_pbx_hangup_handler_headers (int fd)
void ast_pbx_hangup_handler_init (struct ast_channel *chan)
Init the hangup handler container on a channel.
int ast_pbx_hangup_handler_pop (struct ast_channel *chan)
Pop the top of the channel hangup handler stack.
void ast_pbx_hangup_handler_push (struct ast_channel *chan, const char *handler)
Push the given hangup handler onto the channel hangup handler stack.
int ast_pbx_hangup_handler_run (struct ast_channel *chan)
Run all hangup handlers on the channel.
static void ast_pbx_hangup_handler_show (int fd, struct ast_channel *chan)
static char * handle_show_hangup_all (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static char * handle_show_hangup_channel (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
int load_pbx_hangup_handler (void)
static void publish_hangup_handler_message (const char *action, struct ast_channel *chan, const char *handler)
static void unload_pbx_hangup_handler (void)
Variables
static struct ast_cli_entry cli []
Detailed Description
PBX Hangup Handler management routines.
Author
Corey Farrell git@c.nosp@m.fwar.nosp@m.e.com
Definition in file pbx_hangup_handler.c.
Macro Definition Documentation
HANDLER_FORMAT
#define HANDLER_FORMAT "%-30s %s\n"
Definition at line 168 of file pbx_hangup_handler.c.
Referenced by ast_pbx_hangup_handler_headers(), and ast_pbx_hangup_handler_show().
Function Documentation
ast_pbx_hangup_handler_destroy()
void ast_pbx_hangup_handler_destroy (struct ast_channel * chan)
Destroy the hangup handler container on a channel.
Since
11.0
Parameters
chan Channel to destroy the hangup handler container on.
Returns
Nothing
Definition at line 103 of file pbx_hangup_handler.c.
References ast_channel_hangup_handlers(), ast_channel_lock, ast_channel_unlock, ast_free, and AST_LIST_REMOVE_HEAD.
Referenced by ast_channel_destructor(), and ast_dummy_channel_destructor().
 {
    struct ast_hangup_handler_list *handlers;
    struct ast_hangup_handler *h_handler;
    ast_channel_lock(chan);
    /* Get rid of each of the hangup handlers on the channel */
    handlers = ast_channel_hangup_handlers(chan);
    while ((h_handler = AST_LIST_REMOVE_HEAD(handlers, node))) {
       ast_free(h_handler);
    }
    ast_channel_unlock(chan);
 }
ast_pbx_hangup_handler_headers()
static void ast_pbx_hangup_handler_headers (int fd) static
Definition at line 179 of file pbx_hangup_handler.c.
References ast_cli(), and HANDLER_FORMAT.
Referenced by handle_show_hangup_all(), and handle_show_hangup_channel().
 {
    ast_cli(fd, HANDLER_FORMAT, "Channel", "Handler");
 }
ast_pbx_hangup_handler_init()
void ast_pbx_hangup_handler_init (struct ast_channel * chan)
Init the hangup handler container on a channel.
Since
11.0
Parameters
chan Channel to init the hangup handler container on.
Returns
Nothing
Definition at line 95 of file pbx_hangup_handler.c.
References ast_channel_hangup_handlers(), and AST_LIST_HEAD_INIT_NOLOCK.
Referenced by __ast_channel_alloc_ap(), and __ast_dummy_channel_alloc().
 {
    struct ast_hangup_handler_list *handlers;
    handlers = ast_channel_hangup_handlers(chan);
    AST_LIST_HEAD_INIT_NOLOCK(handlers);
 }
ast_pbx_hangup_handler_pop()
int ast_pbx_hangup_handler_pop (struct ast_channel * chan)
Pop the top of the channel hangup handler stack.
Since
11.0
Parameters
chan Channel to push the hangup handler onto.
Return values
TRUE if a handler was popped off of the stack.
Definition at line 119 of file pbx_hangup_handler.c.
References ast_hangup_handler::args, ast_channel_hangup_handlers(), ast_channel_lock, ast_channel_unlock, ast_free, AST_LIST_REMOVE_HEAD, and publish_hangup_handler_message().
Referenced by func_channel_write_real().
 {
    struct ast_hangup_handler_list *handlers;
    struct ast_hangup_handler *h_handler;
    ast_channel_lock(chan);
    handlers = ast_channel_hangup_handlers(chan);
    h_handler = AST_LIST_REMOVE_HEAD(handlers, node);
    if (h_handler) {
       publish_hangup_handler_message("pop", chan, h_handler->args);
    }
    ast_channel_unlock(chan);
    if (h_handler) {
       ast_free(h_handler);
       return 1;
    }
    return 0;
 }
ast_pbx_hangup_handler_push()
void ast_pbx_hangup_handler_push (struct ast_channel * chan, const char * handler)
Push the given hangup handler onto the channel hangup handler stack.
Since
11.0
Parameters
chan Channel to push the hangup handler onto.
handler Gosub application parameter string.
Returns
Nothing
Definition at line 138 of file pbx_hangup_handler.c.
References ast_hangup_handler::args, ast_app_expand_sub_args(), ast_channel_hangup_handlers(), ast_channel_lock, ast_channel_unlock, ast_free, AST_LIST_INSERT_HEAD, ast_malloc, ast_strlen_zero, and publish_hangup_handler_message().
Referenced by func_channel_write_real().
 {
    struct ast_hangup_handler_list *handlers;
    struct ast_hangup_handler *h_handler;
    const char *expanded_handler;
    if (ast_strlen_zero(handler)) {
       return;
    }
    expanded_handler = ast_app_expand_sub_args(chan, handler);
    if (!expanded_handler) {
       return;
    }
    h_handler = ast_malloc(sizeof(*h_handler) + 1 + strlen(expanded_handler));
    if (!h_handler) {
       ast_free((char *) expanded_handler);
       return;
    }
    strcpy(h_handler->args, expanded_handler);/* Safe */
    ast_free((char *) expanded_handler);
    ast_channel_lock(chan);
    handlers = ast_channel_hangup_handlers(chan);
    AST_LIST_INSERT_HEAD(handlers, h_handler, node);
    publish_hangup_handler_message("push", chan, h_handler->args);
    ast_channel_unlock(chan);
 }
ast_pbx_hangup_handler_run()
int ast_pbx_hangup_handler_run (struct ast_channel * chan)
Run all hangup handlers on the channel.
Since
11.0
Parameters
chan Channel to run the hangup handlers on.
Note
Absolutely NO channel locks should be held before calling this function.
Return values
Zero if no hangup handlers run.
non-zero if hangup handlers were run.
Definition at line 58 of file pbx_hangup_handler.c.
References ast_hangup_handler::args, ast_app_exec_sub(), ast_channel_hangup_handlers(), ast_channel_lock, ast_channel_unlock, ast_free, AST_LIST_EMPTY, AST_LIST_REMOVE_HEAD, AST_SOFTHANGUP_HANGUP_EXEC, ast_softhangup_nolock(), NULL, and publish_hangup_handler_message().
Referenced by __ast_pbx_run(), and ast_hangup().
 {
    struct ast_hangup_handler_list *handlers;
    struct ast_hangup_handler *h_handler;
    ast_channel_lock(chan);
    handlers = ast_channel_hangup_handlers(chan);
    if (AST_LIST_EMPTY(handlers)) {
       ast_channel_unlock(chan);
       return 0;
    }
    /*
     * Make sure that the channel is marked as hungup since we are
     * going to run the hangup handlers on it.
     */
    ast_softhangup_nolock(chan, AST_SOFTHANGUP_HANGUP_EXEC);
    for (;;) {
       handlers = ast_channel_hangup_handlers(chan);
       h_handler = AST_LIST_REMOVE_HEAD(handlers, node);
       if (!h_handler) {
          break;
       }
       publish_hangup_handler_message("run", chan, h_handler->args);
       ast_channel_unlock(chan);
       ast_app_exec_sub(NULL, chan, h_handler->args, 1);
       ast_free(h_handler);
       ast_channel_lock(chan);
    }
    ast_channel_unlock(chan);
    return 1;
 }
ast_pbx_hangup_handler_show()
static void ast_pbx_hangup_handler_show (int fd, struct ast_channel * chan) static
Definition at line 194 of file pbx_hangup_handler.c.
References ast_hangup_handler::args, ast_channel_hangup_handlers(), ast_channel_lock, ast_channel_name(), ast_channel_unlock, ast_cli(), AST_LIST_TRAVERSE, first, and HANDLER_FORMAT.
Referenced by handle_show_hangup_all(), and handle_show_hangup_channel().
 {
    struct ast_hangup_handler_list *handlers;
    struct ast_hangup_handler *h_handler;
    int first = 1;
    ast_channel_lock(chan);
    handlers = ast_channel_hangup_handlers(chan);
    AST_LIST_TRAVERSE(handlers, h_handler, node) {
       ast_cli(fd, HANDLER_FORMAT, first ? ast_channel_name(chan) : "", h_handler->args);
       first = 0;
    }
    ast_channel_unlock(chan);
 }
handle_show_hangup_all()
static char* handle_show_hangup_all (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) static
Definition at line 248 of file pbx_hangup_handler.c.
References ast_cli_args::argc, ast_channel_iterator_all_new(), ast_channel_iterator_destroy(), ast_channel_iterator_next(), ast_channel_unref, ast_pbx_hangup_handler_headers(), ast_pbx_hangup_handler_show(), CLI_FAILURE, CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::command, ast_cli_args::fd, NULL, and ast_cli_entry::usage.
 {
    struct ast_channel_iterator *iter;
    struct ast_channel *chan;
    switch (cmd) {
    case CLI_INIT:
       e->command = "core show hanguphandlers all";
       e->usage =
          "Usage: core show hanguphandlers all\n"
          "       Show hangup handlers for all channels.\n";
       return NULL;
    case CLI_GENERATE:
       return NULL;
    }
    if (a->argc < 4) {
       return CLI_SHOWUSAGE;
    }
    iter = ast_channel_iterator_all_new();
    if (!iter) {
       return CLI_FAILURE;
    }
    ast_pbx_hangup_handler_headers(a->fd);
    for (; (chan = ast_channel_iterator_next(iter)); ast_channel_unref(chan)) {
       ast_pbx_hangup_handler_show(a->fd, chan);
    }
    ast_channel_iterator_destroy(iter);
    return CLI_SUCCESS;
 }
handle_show_hangup_channel()
static char* handle_show_hangup_channel (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) static
Definition at line 212 of file pbx_hangup_handler.c.
References ast_cli_args::argc, ast_cli_entry::args, ast_cli_args::argv, ast_channel_get_by_name(), ast_channel_unref, ast_cli(), ast_complete_channels(), ast_pbx_hangup_handler_headers(), ast_pbx_hangup_handler_show(), CLI_FAILURE, CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::command, ast_cli_args::fd, ast_cli_args::line, ast_cli_args::n, NULL, ast_cli_args::pos, ast_cli_entry::usage, and ast_cli_args::word.
 {
    struct ast_channel *chan;
    switch (cmd) {
    case CLI_INIT:
       e->command = "core show hanguphandlers";
       e->usage =
          "Usage: core show hanguphandlers <channel>\n"
          "       Show hangup handlers of a specified channel.\n";
       return NULL;
    case CLI_GENERATE:
       return ast_complete_channels(a->line, a->word, a->pos, a->n, e->args);
    }
    if (a->argc < 4) {
       return CLI_SHOWUSAGE;
    }
    chan = ast_channel_get_by_name(a->argv[3]);
    if (!chan) {
       ast_cli(a->fd, "Channel does not exist.\n");
       return CLI_FAILURE;
    }
    ast_pbx_hangup_handler_headers(a->fd);
    ast_pbx_hangup_handler_show(a->fd, chan);
    ast_channel_unref(chan);
    return CLI_SUCCESS;
 }
load_pbx_hangup_handler()
int load_pbx_hangup_handler (void)
Provided by pbx_hangup_handler.c
Definition at line 292 of file pbx_hangup_handler.c.
References ARRAY_LEN, ast_cli_register_multiple, ast_register_cleanup(), and unload_pbx_hangup_handler().
Referenced by asterisk_daemon().
 {
    ast_cli_register_multiple(cli, ARRAY_LEN(cli));
    ast_register_cleanup(unload_pbx_hangup_handler);
    return 0;
 }
publish_hangup_handler_message()
static void publish_hangup_handler_message (const char * action, struct ast_channel * chan, const char * handler) static
Definition at line 44 of file pbx_hangup_handler.c.
References ast_channel_hangup_handler_type(), ast_channel_publish_blob(), ast_json_pack(), ast_json_unref(), NULL, RAII_VAR, and S_OR.
Referenced by ast_pbx_hangup_handler_pop(), ast_pbx_hangup_handler_push(), and ast_pbx_hangup_handler_run().
 {
    RAII_VAR(struct ast_json *, blob, NULL, ast_json_unref);
    blob = ast_json_pack("{s: s, s: s}",
          "type", action,
          "handler", S_OR(handler, ""));
    if (!blob) {
       return;
    }
    ast_channel_publish_blob(chan, ast_channel_hangup_handler_type(), blob);
 }
unload_pbx_hangup_handler()
static void unload_pbx_hangup_handler (void) static
Definition at line 287 of file pbx_hangup_handler.c.
References ARRAY_LEN, and ast_cli_unregister_multiple().
Referenced by load_pbx_hangup_handler().
 {
    ast_cli_unregister_multiple(cli, ARRAY_LEN(cli));
 }
Variable Documentation
cli
struct ast_cli_entry cli[] static
Initial value:
= {
   { .handler =  handle_show_hangup_all , .summary =  "Show hangup handlers of all channels" ,},
   { .handler =  handle_show_hangup_channel , .summary =  "Show hangup handlers of a specified channel" ,},
}
Definition at line 282 of file pbx_hangup_handler.c.