Asterisk - The Open Source Telephony Project: func_pjsip_endpoint.c File Reference
func_pjsip_endpoint.c File Reference
Module: Dial plan functions
Get information about a PJSIP endpoint.
#include "asterisk.h"
#include <pjsip.h>
#include <pjlib.h>
#include "asterisk/app.h"
#include "asterisk/pbx.h"
#include "asterisk/module.h"
#include "asterisk/channel.h"
#include "asterisk/sorcery.h"
#include "asterisk/res_pjsip.h"
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int load_module (void)
static int pjsip_endpoint_function_read (struct ast_channel *chan, const char *cmd, char *data, struct ast_str **buf, ssize_t len)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_DEFAULT , .description = "Get information about a PJSIP endpoint" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .requires = "res_pjsip", }
static const struct ast_module_info * ast_module_info = &__mod_info
static struct ast_custom_function pjsip_endpoint_function
Detailed Description
Get information about a PJSIP endpoint.
Author
Matt Jordan <mjordan@digium.com>
Definition in file func_pjsip_endpoint.c.
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 164 of file func_pjsip_endpoint.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 164 of file func_pjsip_endpoint.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 164 of file func_pjsip_endpoint.c.
load_module()
static int load_module (void) static
Definition at line 154 of file func_pjsip_endpoint.c.
References ast_custom_function_register, AST_MODFLAG_DEFAULT, AST_MODULE_INFO(), AST_MODULE_SUPPORT_CORE, ASTERISK_GPL_KEY, and unload_module().
 {
    return ast_custom_function_register(&pjsip_endpoint_function);
 }
pjsip_endpoint_function_read()
static int pjsip_endpoint_function_read (struct ast_channel * chan, const char * cmd, char * data, struct ast_str ** buf, ssize_t len) static
Definition at line 71 of file func_pjsip_endpoint.c.
References ao2_cleanup, args, AST_APP_ARG, AST_DECLARE_APP_ARGS, ast_log, AST_LOG_ERROR, AST_LOG_WARNING, ast_sip_get_sorcery(), ast_sorcery_objectset_create, ast_sorcery_retrieve_by_id(), AST_STANDARD_APP_ARGS, ast_str_set(), ast_strdupa, ast_strlen_zero, ast_variables_destroy(), ast_variable::name, ast_variable::next, NULL, RAII_VAR, and ast_variable::value.
 {
    struct ast_sorcery *pjsip_sorcery;
    char *parsed_data = ast_strdupa(data);
    RAII_VAR(void *, endpoint_obj, NULL, ao2_cleanup);
    struct ast_variable *change_set;
    struct ast_variable *it_change_set;
    int res;
    AST_DECLARE_APP_ARGS(args,
       AST_APP_ARG(endpoint_name);
       AST_APP_ARG(field_name);
    );
    /* Check for zero arguments */
    if (ast_strlen_zero(parsed_data)) {
       ast_log(AST_LOG_ERROR, "Cannot call %s without arguments\n", cmd);
       return -1;
    }
    AST_STANDARD_APP_ARGS(args, parsed_data);
    if (ast_strlen_zero(args.endpoint_name)) {
       ast_log(AST_LOG_ERROR, "Cannot call %s without an endpoint name to query\n", cmd);
       return -1;
    }
    if (ast_strlen_zero(args.field_name)) {
       ast_log(AST_LOG_ERROR, "Cannot call %s with an empty field name to query\n", cmd);
       return -1;
    }
    pjsip_sorcery = ast_sip_get_sorcery();
    if (!pjsip_sorcery) {
       ast_log(AST_LOG_ERROR, "Unable to retrieve PJSIP configuration: sorcery object is NULL\n");
       return -1;
    }
    endpoint_obj = ast_sorcery_retrieve_by_id(pjsip_sorcery, "endpoint", args.endpoint_name);
    if (!endpoint_obj) {
       ast_log(AST_LOG_WARNING, "Failed to retrieve information for endpoint '%s'\n", args.endpoint_name);
       return -1;
    }
    change_set = ast_sorcery_objectset_create(pjsip_sorcery, endpoint_obj);
    if (!change_set) {
       ast_log(AST_LOG_WARNING, "Failed to retrieve information for endpoint '%s': change set is NULL\n", args.endpoint_name);
       return -1;
    }
    for (it_change_set = change_set; it_change_set; it_change_set = it_change_set->next) {
       if (!strcmp(it_change_set->name, args.field_name)) {
          if (!strcmp(it_change_set->name, "disallow")) {
             ast_str_set(buf, len, "!%s", it_change_set->value);
          } else {
             ast_str_set(buf, len, "%s", it_change_set->value);
          }
          break;
       }
    }
    res = it_change_set ? 0 : 1;
    if (res) {
       ast_log(AST_LOG_WARNING, "Unknown property '%s' for PJSIP endpoint\n", args.field_name);
    }
    ast_variables_destroy(change_set);
    return res;
 }
unload_module()
static int unload_module (void) static
Definition at line 149 of file func_pjsip_endpoint.c.
References ast_custom_function_unregister().
Referenced by load_module().
 {
    return ast_custom_function_unregister(&pjsip_endpoint_function);
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_DEFAULT , .description = "Get information about a PJSIP endpoint" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .requires = "res_pjsip", } static
Definition at line 164 of file func_pjsip_endpoint.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 164 of file func_pjsip_endpoint.c.
pjsip_endpoint_function
struct ast_custom_function pjsip_endpoint_function static
Initial value:
= {
   .name = "PJSIP_ENDPOINT",
   .read2 = pjsip_endpoint_function_read,
}
Definition at line 144 of file func_pjsip_endpoint.c.