Asterisk - The Open Source Telephony Project: console_video.c File Reference
console_video.c File Reference
#include "asterisk.h"
#include <sys/ioctl.h>
#include "asterisk/cli.h"
#include "asterisk/file.h"
#include "asterisk/channel.h"
#include "console_video.h"
Functions
int console_video_cli (struct video_desc *env, const char *var, int fd)
int console_video_config (struct video_desc **penv, const char *var, const char *val)
void console_video_start (struct video_desc *env, struct ast_channel *owner)
void console_video_uninit (struct video_desc *env)
int console_write_video (struct ast_channel *chan, struct ast_frame *f)
int get_gui_startup (struct video_desc *env)
Variables
int console_video_formats = 0
Function Documentation
console_video_cli()
int console_video_cli (struct video_desc * env, const char * var, int fd)
Definition at line 124 of file console_video.c.
Referenced by console_cmd().
 {
    return 1;   /* nothing matched */
 }
console_video_config()
int console_video_config (struct video_desc ** penv, const char * var, const char * val)
Definition at line 129 of file console_video.c.
Referenced by store_config_core().
 {
    return 1;   /* no configuration */
 }
console_video_start()
void console_video_start (struct video_desc * env, struct ast_channel * owner)
Definition at line 134 of file console_video.c.
References ast_log, and LOG_NOTICE.
Referenced by oss_new(), and store_config().
 {
    ast_log(LOG_NOTICE, "voice only, console video support not present\n");
 }
console_video_uninit()
void console_video_uninit (struct video_desc * env)
Definition at line 139 of file console_video.c.
Referenced by oss_hangup().
 {
 }
console_write_video()
int console_write_video (struct ast_channel * chan, struct ast_frame * f)
Definition at line 119 of file console_video.c.
 {
    return 0;   /* writing video not supported */
 }
get_gui_startup()
int get_gui_startup (struct video_desc * env)
Definition at line 143 of file console_video.c.
Referenced by store_config().
 {
    return 0; /* no gui here */
 }
Variable Documentation
console_video_formats
int console_video_formats = 0
Definition at line 148 of file console_video.c.