Asterisk - The Open Source Telephony Project: app_controlplayback.c File Reference
app_controlplayback.c File Reference
Dial plan applications
Trivial application to control playback of a sound file.
#include "asterisk.h"
#include "asterisk/pbx.h"
#include "asterisk/app.h"
#include "asterisk/module.h"
#include "asterisk/manager.h"
#include "asterisk/utils.h"
#include "asterisk/astobj2.h"
Enumerations
enum { OPT_OFFSET = (1 << 1) }
enum { OPT_ARG_OFFSET = 0, OPT_ARG_ARRAY_LEN }
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int controlplayback_exec (struct ast_channel *chan, const char *data)
static int controlplayback_manager (struct mansession *s, const struct message *m)
static int is_argument (const char *haystack, int needle)
static int is_on_phonepad (char key)
static int load_module (void)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Control Playback Application" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, }
static const char app [] = "ControlPlayback"
static const struct ast_module_info * ast_module_info = &__mod_info
static const struct ast_app_option cpb_opts [128] = { [ 'o' ] = { .flag = OPT_OFFSET , .arg_index = OPT_ARG_OFFSET + 1 }, }
Detailed Description
Trivial application to control playback of a sound file.
Author
Mark Spencer marks.nosp@m.ter@.nosp@m.digiu.nosp@m.m.co.nosp@m.m
Definition in file app_controlplayback.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
OPT_OFFSET
Definition at line 166 of file app_controlplayback.c.
      {
    OPT_OFFSET = (1 << 1),
 };
anonymous enum
anonymous enum
Enumerator
OPT_ARG_OFFSET
OPT_ARG_ARRAY_LEN
Definition at line 170 of file app_controlplayback.c.
      {
    OPT_ARG_OFFSET = 0,
    /* must stay as the last entry ... */
    OPT_ARG_ARRAY_LEN,
 };
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 349 of file app_controlplayback.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 349 of file app_controlplayback.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 349 of file app_controlplayback.c.
controlplayback_exec()
static int controlplayback_exec (struct ast_channel * chan, const char * data) static
Definition at line 197 of file app_controlplayback.c.
References args, AST_APP_ARG, ast_app_parse_options(), AST_CONTROL_STREAM_STOP, ast_control_streamfile(), ast_debug, AST_DECLARE_APP_ARGS, ast_log, AST_STANDARD_APP_ARGS, ast_strdupa, ast_strlen_zero, ast_test_flag, cpb_opts, digit, is_argument(), is_on_phonepad(), LOG_WARNING, NULL, OPT_ARG_ARRAY_LEN, OPT_ARG_OFFSET, OPT_OFFSET, options, pbx_builtin_setvar_helper(), skipms, stop, and tmp().
Referenced by load_module().
 {
    int res = 0;
    int skipms = 0;
    long offsetms = 0;
    char offsetbuf[20];
    char stopkeybuf[2];
    char *tmp;
    struct ast_flags opts = { 0, };
    char *opt_args[OPT_ARG_ARRAY_LEN];
    AST_DECLARE_APP_ARGS(args,
       AST_APP_ARG(filename);
       AST_APP_ARG(skip);
       AST_APP_ARG(fwd);
       AST_APP_ARG(rev);
       AST_APP_ARG(stop);
       AST_APP_ARG(pause);
       AST_APP_ARG(restart);
       AST_APP_ARG(options);
    );
    if (ast_strlen_zero(data)) {
       ast_log(LOG_WARNING, "ControlPlayback requires an argument (filename)\n");
       return -1;
    }
    tmp = ast_strdupa(data);
    AST_STANDARD_APP_ARGS(args, tmp);
    if (args.argc < 1) {
       ast_log(LOG_WARNING, "ControlPlayback requires an argument (filename)\n");
       return -1;
    }
    skipms = args.skip ? (atoi(args.skip) ? atoi(args.skip) : 3000) : 3000;
    if (!args.fwd || !is_on_phonepad(*args.fwd)) {
       char *digit = "#";
       if (!is_argument(args.rev, *digit) && !is_argument(args.stop, *digit) && !is_argument(args.pause, *digit) && !is_argument(args.restart, *digit))
          args.fwd = digit;
       else
          args.fwd = NULL;
    }
    if (!args.rev || !is_on_phonepad(*args.rev)) {
       char *digit = "*";
       if (!is_argument(args.fwd, *digit) && !is_argument(args.stop, *digit) && !is_argument(args.pause, *digit) && !is_argument(args.restart, *digit))
          args.rev = digit;
       else
          args.rev = NULL;
    }
    ast_debug(1, "Forward key = %s, Rewind key = %s\n", args.fwd, args.rev);
    if (args.stop && !is_on_phonepad(*args.stop))
       args.stop = NULL;
    if (args.pause && !is_on_phonepad(*args.pause))
       args.pause = NULL;
    if (args.restart && !is_on_phonepad(*args.restart))
       args.restart = NULL;
    if (args.options) {
       ast_app_parse_options(cpb_opts, &opts, opt_args, args.options);
       if (ast_test_flag(&opts, OPT_OFFSET))
          offsetms = atol(opt_args[OPT_ARG_OFFSET]);
    }
    res = ast_control_streamfile(chan, args.filename, args.fwd, args.rev, args.stop, args.pause, args.restart, skipms, &offsetms);
    /* If we stopped on one of our stop keys, return 0  */
    if (res > 0 && args.stop && strchr(args.stop, res)) {
       pbx_builtin_setvar_helper(chan, "CPLAYBACKSTATUS", "USERSTOPPED");
       snprintf(stopkeybuf, sizeof(stopkeybuf), "%c", res);
       pbx_builtin_setvar_helper(chan, "CPLAYBACKSTOPKEY", stopkeybuf);
       res = 0;
    } else if (res > 0 && res == AST_CONTROL_STREAM_STOP) {
       pbx_builtin_setvar_helper(chan, "CPLAYBACKSTATUS", "REMOTESTOPPED");
       res = 0;
    } else {
       if (res < 0) {
          res = 0;
          pbx_builtin_setvar_helper(chan, "CPLAYBACKSTATUS", "ERROR");
       } else
          pbx_builtin_setvar_helper(chan, "CPLAYBACKSTATUS", "SUCCESS");
    }
    snprintf(offsetbuf, sizeof(offsetbuf), "%ld", offsetms);
    pbx_builtin_setvar_helper(chan, "CPLAYBACKOFFSET", offsetbuf);
    return res;
 }
controlplayback_manager()
static int controlplayback_manager (struct mansession * s, const struct message * m) static
Definition at line 286 of file app_controlplayback.c.
References ast_channel_get_by_name(), ast_channel_unref, AST_CONTROL_STREAM_FORWARD, AST_CONTROL_STREAM_RESTART, AST_CONTROL_STREAM_REVERSE, AST_CONTROL_STREAM_STOP, AST_CONTROL_STREAM_SUSPEND, ast_queue_control(), ast_strlen_zero, astman_get_header(), astman_send_ack(), astman_send_error(), and NULL.
Referenced by load_module().
 {
    const char *channel_name = astman_get_header(m, "Channel");
    const char *control_type = astman_get_header(m, "Control");
    struct ast_channel *chan;
    if (ast_strlen_zero(channel_name)) {
       astman_send_error(s, m, "Channel not specified");
       return 0;
    }
    if (ast_strlen_zero(control_type)) {
       astman_send_error(s, m, "Control not specified");
       return 0;
    }
    chan = ast_channel_get_by_name(channel_name);
    if (!chan) {
       astman_send_error(s, m, "No such channel");
       return 0;
    }
    if (!strcasecmp(control_type, "stop")) {
       ast_queue_control(chan, AST_CONTROL_STREAM_STOP);
    } else if (!strcasecmp(control_type, "forward")) {
       ast_queue_control(chan, AST_CONTROL_STREAM_FORWARD);
    } else if (!strcasecmp(control_type, "reverse")) {
       ast_queue_control(chan, AST_CONTROL_STREAM_REVERSE);
    } else if (!strcasecmp(control_type, "pause")) {
       ast_queue_control(chan, AST_CONTROL_STREAM_SUSPEND);
    } else if (!strcasecmp(control_type, "restart")) {
       ast_queue_control(chan, AST_CONTROL_STREAM_RESTART);
    } else {
       astman_send_error(s, m, "Unknown control type");
       chan = ast_channel_unref(chan);
       return 0;
    }
    chan = ast_channel_unref(chan);
    astman_send_ack(s, m, NULL);
    return 0;
 }
is_argument()
static int is_argument (const char * haystack, int needle) static
Definition at line 186 of file app_controlplayback.c.
References ast_strlen_zero.
Referenced by controlplayback_exec().
 {
    if (ast_strlen_zero(haystack))
       return 0;
    if (strchr(haystack, needle))
       return -1;
    return 0;
 }
is_on_phonepad()
static int is_on_phonepad (char key) static
Definition at line 181 of file app_controlplayback.c.
Referenced by controlplayback_exec().
 {
    return key == 35 || key == 42 || (key >= 48 && key <= 57);
 }
load_module()
static int load_module (void) static
Definition at line 339 of file app_controlplayback.c.
References app, ast_manager_register_xml, ast_register_application_xml, controlplayback_exec(), controlplayback_manager(), and EVENT_FLAG_CALL.
 {
    int res = 0;
    res |= ast_register_application_xml(app, controlplayback_exec);
    res |= ast_manager_register_xml("ControlPlayback", EVENT_FLAG_CALL, controlplayback_manager);
    return res;
 }
unload_module()
static int unload_module (void) static
Definition at line 329 of file app_controlplayback.c.
References app, ast_manager_unregister(), and ast_unregister_application().
 {
    int res = 0;
    res |= ast_unregister_application(app);
    res |= ast_manager_unregister("ControlPlayback");
    return res;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Control Playback Application" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, } static
Definition at line 349 of file app_controlplayback.c.
app
const char app[] = "ControlPlayback" static
Definition at line 164 of file app_controlplayback.c.
Referenced by load_module(), and unload_module().
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 349 of file app_controlplayback.c.
cpb_opts
const struct ast_app_option cpb_opts[128] = { [ 'o' ] = { .flag = OPT_OFFSET , .arg_index = OPT_ARG_OFFSET + 1 }, } static
Definition at line 179 of file app_controlplayback.c.
Referenced by controlplayback_exec().