Asterisk - The Open Source Telephony Project: func_module.c File Reference
func_module.c File Reference
Module: Dial plan functions
Simple module check function.
#include "asterisk.h"
#include "asterisk/module.h"
#include "asterisk/pbx.h"
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int ifmodule_read (struct ast_channel *chan, const char *cmd, char *data, char *buf, size_t len)
static int load_module (void)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Checks if Asterisk module is loaded in memory" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, }
static const struct ast_module_info * ast_module_info = &__mod_info
static struct ast_custom_function ifmodule_function
Detailed Description
Simple module check function.
Author
Olle E. Johansson, Edvina.net
Definition in file func_module.c.
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 85 of file func_module.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 85 of file func_module.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 85 of file func_module.c.
ifmodule_read()
static int ifmodule_read (struct ast_channel * chan, const char * cmd, char * data, char * buf, size_t len) static
Definition at line 52 of file func_module.c.
References ast_copy_string(), and ast_module_check().
 {
    char *ret = "0";
    *buf = '\0';
    if (data)
       if (ast_module_check(data))
          ret = "1";
    ast_copy_string(buf, ret, len);
    return 0;
 }
load_module()
static int load_module (void) static
Definition at line 80 of file func_module.c.
References ast_custom_function_register.
 {
    return ast_custom_function_register(&ifmodule_function);
 }
unload_module()
static int unload_module (void) static
Definition at line 75 of file func_module.c.
References ast_custom_function_unregister().
 {
    return ast_custom_function_unregister(&ifmodule_function);
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Checks if Asterisk module is loaded in memory" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, } static
Definition at line 85 of file func_module.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 85 of file func_module.c.
ifmodule_function
struct ast_custom_function ifmodule_function static
Initial value:
= {
   .name = "IFMODULE",
   .read = ifmodule_read,
   .read_max = 2,
}
Definition at line 68 of file func_module.c.