Asterisk - The Open Source Telephony Project: stasis_app_device_state.h File Reference
stasis_app_device_state.h File Reference
Stasis Application Device State API. See StasisApplication API" for detailed documentation.
#include "asterisk/app.h"
#include "asterisk/stasis_app.h"
enum stasis_device_state_result {
STASIS_DEVICE_STATE_OK, STASIS_DEVICE_STATE_NOT_CONTROLLED, STASIS_DEVICE_STATE_MISSING, STASIS_DEVICE_STATE_UNKNOWN,
STASIS_DEVICE_STATE_SUBSCRIBERS
}
struct ast_json * stasis_app_device_state_to_json (const char *name, enum ast_device_state state)
Convert device state to json.
struct ast_json * stasis_app_device_states_to_json (void)
Convert device states to json array.
enum stasis_device_state_result stasis_app_device_state_update (const char *name, const char *value)
Changes the state of a device controlled by ARI.
enum stasis_device_state_result stasis_app_device_state_delete (const char *name)
Delete a device controlled by ARI.
Detailed Description
Stasis Application Device State API. See StasisApplication API" for detailed documentation.
Author
Kevin Harwell kharw.nosp@m.ell@.nosp@m.digiu.nosp@m.m.co.nosp@m.m
Since
12
Definition in file stasis_app_device_state.h.
Enumeration Type Documentation
stasis_device_state_result
enum stasis_device_state_result
Stasis device state application result codes
Enumerator
STASIS_DEVICE_STATE_OK
Application controlled device state is okay
STASIS_DEVICE_STATE_NOT_CONTROLLED
The device name is not application controlled
STASIS_DEVICE_STATE_MISSING
The application controlled device name is missing
STASIS_DEVICE_STATE_UNKNOWN
The application controlled device is unknown
STASIS_DEVICE_STATE_SUBSCRIBERS
The application controlled device has subscribers
Definition at line 56 of file stasis_app_device_state.h.
{
    /*! Application controlled device state is okay */
    STASIS_DEVICE_STATE_OK,
    /*! The device name is not application controlled */
    STASIS_DEVICE_STATE_NOT_CONTROLLED,
    /*! The application controlled device name is missing */
    STASIS_DEVICE_STATE_MISSING,
    /*! The application controlled device is unknown */
    STASIS_DEVICE_STATE_UNKNOWN,
    /*! The application controlled device has subscribers */
    STASIS_DEVICE_STATE_SUBSCRIBERS
 };
Function Documentation
stasis_app_device_state_delete()
enum stasis_device_state_result stasis_app_device_state_delete (const char * name)
Delete a device controlled by ARI.
Parameters
name the name of the ARI controlled device
stasis device state application result.
Definition at line 244 of file res_stasis_device_state.c.
References ast_db_del(), ast_device_state_clear_cache(), AST_DEVICE_UNKNOWN, AST_DEVSTATE_CACHABLE, ast_devstate_changed(), ast_log, ast_strlen_zero, DEVICE_STATE_FAMILY, DEVICE_STATE_SCHEME_STASIS, LOG_ERROR, name, STASIS_DEVICE_STATE_MISSING, STASIS_DEVICE_STATE_NOT_CONTROLLED, STASIS_DEVICE_STATE_OK, and STASIS_DEVICE_STATE_UNKNOWN.
Referenced by ast_ari_device_states_delete().
 {
    const char *full_name = name;
    size_t size = strlen(DEVICE_STATE_SCHEME_STASIS);
    if (strncasecmp(name, DEVICE_STATE_SCHEME_STASIS, size)) {
       ast_log(LOG_ERROR, "Can only delete '%s' device states!\n",
          DEVICE_STATE_SCHEME_STASIS);
       return STASIS_DEVICE_STATE_NOT_CONTROLLED;
    }
    name += size;
    if (ast_strlen_zero(name)) {
       ast_log(LOG_ERROR, "Delete requires a device name!\n");
       return STASIS_DEVICE_STATE_MISSING;
    }
    if (ast_device_state_clear_cache(full_name)) {
       return STASIS_DEVICE_STATE_UNKNOWN;
    }
    ast_db_del(DEVICE_STATE_FAMILY, name);
    /* send state change for delete */
    ast_devstate_changed(
       AST_DEVICE_UNKNOWN, AST_DEVSTATE_CACHABLE, "%s%s",
       DEVICE_STATE_SCHEME_STASIS, name);
    return STASIS_DEVICE_STATE_OK;
 }
stasis_app_device_state_to_json()
struct ast_json* stasis_app_device_state_to_json (const char * name, enum ast_device_state state)
Convert device state to json.
Parameters
name the name of the device
state the device state
Returns
JSON representation.
NULL on error.
Definition at line 160 of file res_stasis_device_state.c.
References ast_devstate_str(), and ast_json_pack().
Referenced by ast_ari_device_states_get(), send_device_state(), and stasis_app_device_states_to_json().
 {
    return ast_json_pack("{s: s, s: s}",
               "name", name,
               "state", ast_devstate_str(state));
 }
stasis_app_device_state_update()
enum stasis_device_state_result stasis_app_device_state_update (const char * name, const char * value)
Changes the state of a device controlled by ARI.
Note
The controlled device must be prefixed with 'Stasis:'.
Implicitly creates the device state.
Parameters
name the name of the ARI controlled device
value a valid device state value
Returns
a stasis device state application result.
Definition at line 211 of file res_stasis_device_state.c.
References ast_db_put(), ast_debug, AST_DEVICE_UNKNOWN, AST_DEVSTATE_CACHABLE, ast_devstate_changed(), ast_devstate_val(), ast_log, ast_strlen_zero, DEVICE_STATE_FAMILY, DEVICE_STATE_SCHEME_STASIS, LOG_ERROR, STASIS_DEVICE_STATE_MISSING, STASIS_DEVICE_STATE_NOT_CONTROLLED, STASIS_DEVICE_STATE_OK, STASIS_DEVICE_STATE_UNKNOWN, and state.
Referenced by ast_ari_device_states_update().
 {
    size_t size = strlen(DEVICE_STATE_SCHEME_STASIS);
    enum ast_device_state state;
    ast_debug(3, "Updating device name = %s, value = %s", name, value);
    if (strncasecmp(name, DEVICE_STATE_SCHEME_STASIS, size)) {
       ast_log(LOG_ERROR, "Update can only be used to set "
          "'%s' device state!\n", DEVICE_STATE_SCHEME_STASIS);
       return STASIS_DEVICE_STATE_NOT_CONTROLLED;
    }
    name += size;
    if (ast_strlen_zero(name)) {
       ast_log(LOG_ERROR, "Update requires custom device name!\n");
       return STASIS_DEVICE_STATE_MISSING;
    }
    if (!value || (state = ast_devstate_val(value)) == AST_DEVICE_UNKNOWN) {
       ast_log(LOG_ERROR, "Unknown device state "
          "value '%s'\n", value);
       return STASIS_DEVICE_STATE_UNKNOWN;
    }
    ast_db_put(DEVICE_STATE_FAMILY, name, value);
    ast_devstate_changed(state, AST_DEVSTATE_CACHABLE, "%s%s",
               DEVICE_STATE_SCHEME_STASIS, name);
    return STASIS_DEVICE_STATE_OK;
 }
stasis_app_device_states_to_json()
struct ast_json* stasis_app_device_states_to_json (void)
Convert device states to json array.
Returns
JSON representation.
NULL on error.
Definition at line 168 of file res_stasis_device_state.c.
References array(), ast_db_freetree(), ast_db_gettree(), ast_json_array_append(), ast_json_array_create(), ast_strlen_zero, DEVICE_STATE_FAMILY, DEVICE_STATE_SCHEME_STASIS, DEVICE_STATE_SIZE, ast_db_entry::key, name, ast_db_entry::next, NULL, and stasis_app_device_state_to_json().
Referenced by ast_ari_device_states_list().
 {
    struct ast_json *array = ast_json_array_create();
    struct ast_db_entry *tree;
    struct ast_db_entry *entry;
    tree = ast_db_gettree(DEVICE_STATE_FAMILY, NULL);
    for (entry = tree; entry; entry = entry->next) {
       const char *name = strrchr(entry->key, '/');
       if (!ast_strlen_zero(name)) {
          char device[DEVICE_STATE_SIZE];
          snprintf(device, sizeof(device), "%s%s", DEVICE_STATE_SCHEME_STASIS, ++name);
          ast_json_array_append(array,
             stasis_app_device_state_to_json(device, ast_device_state(device)));
       }
    }
    ast_db_freetree(tree);
    return array;
 }