Asterisk - The Open Source Telephony Project: chan_audiosocket.c File Reference
chan_audiosocket.c File Reference
Module: Asterisk Channel Drivers
AudioSocket Channel.
#include "asterisk.h"
#include <uuid/uuid.h>
#include "asterisk/channel.h"
#include "asterisk/module.h"
#include "asterisk/res_audiosocket.h"
#include "asterisk/pbx.h"
#include "asterisk/acl.h"
#include "asterisk/app.h"
#include "asterisk/causes.h"
#include "asterisk/format_cache.h"
Data Structures
struct audiosocket_instance
Macros
#define FD_OUTPUT 1 /* A fd of -1 means an error, 0 is stdin */
Enumerations
enum { OPT_AUDIOSOCKET_CODEC = (1 << 0) }
enum { OPT_ARG_AUDIOSOCKET_CODEC = (1 << 0), OPT_ARG_ARRAY_SIZE }
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int audiosocket_call (struct ast_channel *ast, const char *dest, int timeout)
Function called when we should actually call the destination.
static int audiosocket_hangup (struct ast_channel *ast)
Function called when we should hang the channel up.
static struct ast_frame * audiosocket_read (struct ast_channel *ast)
Function called when we should read a frame from the channel.
static struct ast_channel * audiosocket_request (const char *type, struct ast_format_cap *cap, const struct ast_assigned_ids *assignedids, const struct ast_channel *requestor, const char *data, int *cause)
Function called when we should prepare to call the unicast destination.
static int audiosocket_write (struct ast_channel *ast, struct ast_frame *f)
Function called when we should write a frame to the channel.
static int load_module (void)
Function called when our module is loaded.
static int unload_module (void)
Function called when our module is unloaded.
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "AudioSocket Channel" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_EXTENDED, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_CHANNEL_DRIVER, .requires = "res_audiosocket", }
static const struct ast_module_info * ast_module_info = &__mod_info
static struct ast_channel_tech audiosocket_channel_tech
struct audiosocket_instance audiosocket_instance
static const struct ast_app_option audiosocket_options [128] = { [ 'c' ] = { .flag = OPT_AUDIOSOCKET_CODEC , .arg_index = OPT_ARG_AUDIOSOCKET_CODEC + 1 }, }
Detailed Description
AudioSocket Channel.
Author
Seán C McCord scm@c.nosp@m.ycor.nosp@m.esys..nosp@m.com
Definition in file chan_audiosocket.c.
Macro Definition Documentation
FD_OUTPUT
#define FD_OUTPUT 1 /* A fd of -1 means an error, 0 is stdin */
Definition at line 45 of file chan_audiosocket.c.
Referenced by audiosocket_read().
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
OPT_AUDIOSOCKET_CODEC
Definition at line 125 of file chan_audiosocket.c.
      {
    OPT_AUDIOSOCKET_CODEC = (1 << 0),
 };
anonymous enum
anonymous enum
Enumerator
OPT_ARG_AUDIOSOCKET_CODEC
OPT_ARG_ARRAY_SIZE
Definition at line 129 of file chan_audiosocket.c.
      {
    OPT_ARG_AUDIOSOCKET_CODEC = (1 << 0),
    OPT_ARG_ARRAY_SIZE
 };
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 301 of file chan_audiosocket.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 301 of file chan_audiosocket.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 301 of file chan_audiosocket.c.
audiosocket_call()
static int audiosocket_call (struct ast_channel * ast, const char * dest, int timeout) static
Function called when we should actually call the destination.
Definition at line 99 of file chan_audiosocket.c.
References ast_audiosocket_init(), ast_channel_tech_pvt(), AST_CONTROL_ANSWER, ast_queue_control(), audiosocket_instance::id, and audiosocket_instance::svc.
 {
    struct audiosocket_instance *instance = ast_channel_tech_pvt(ast);
    ast_queue_control(ast, AST_CONTROL_ANSWER);
    return ast_audiosocket_init(instance->svc, instance->id);
 }
audiosocket_hangup()
static int audiosocket_hangup (struct ast_channel * ast) static
Function called when we should hang the channel up.
Definition at line 109 of file chan_audiosocket.c.
References ast_channel_tech_pvt(), ast_channel_tech_pvt_set(), ast_free, NULL, and audiosocket_instance::svc.
 {
    struct audiosocket_instance *instance;
    /* The channel should always be present from the API */
    instance = ast_channel_tech_pvt(ast);
    if (instance != NULL && instance->svc > 0) {
       close(instance->svc);
    }
    ast_channel_tech_pvt_set(ast, NULL);
    ast_free(instance);
    return 0;
 }
audiosocket_read()
static struct ast_frame * audiosocket_read (struct ast_channel * ast) static
Function called when we should read a frame from the channel.
Definition at line 73 of file chan_audiosocket.c.
References ast_audiosocket_receive_frame(), ast_channel_tech_pvt(), FD_OUTPUT, NULL, and audiosocket_instance::svc.
 {
    struct audiosocket_instance *instance;
    /* The channel should always be present from the API */
    instance = ast_channel_tech_pvt(ast);
    if (instance == NULL || instance->svc < FD_OUTPUT) {
       return NULL;
    }
    return ast_audiosocket_receive_frame(instance->svc);
 }
audiosocket_request()
static struct ast_channel * audiosocket_request (const char * type, struct ast_format_cap * cap, const struct ast_assigned_ids * assignedids, const struct ast_channel * requestor, const char * data, int * cause) static
Function called when we should prepare to call the unicast destination.
Definition at line 139 of file chan_audiosocket.c.
References ao2_cleanup, ao2_ref, args, AST_AF_UNSPEC, AST_APP_ARG, ast_app_parse_options(), ast_audiosocket_connect(), ast_calloc, AST_CAUSE_FAILURE, ast_channel_alloc, ast_channel_nativeformats_set(), ast_channel_set_fd(), ast_channel_set_rawreadformat(), ast_channel_set_rawwriteformat(), ast_channel_set_readformat(), ast_channel_set_writeformat(), ast_channel_tech_pvt_set(), ast_channel_tech_set(), ast_channel_unlock, ast_copy_string(), AST_DECLARE_APP_ARGS, ast_format_cache_get, ast_format_cap_alloc, ast_format_cap_append, AST_FORMAT_CAP_FLAG_DEFAULT, ast_format_cap_get_format(), ast_free, ast_log, AST_NONSTANDARD_APP_ARGS, ast_sockaddr_resolve_first_af(), AST_STATE_DOWN, ast_strdupa, ast_strlen_zero, ast_test_flag, audiosocket_options, audiosocket_instance::id, LOG_ERROR, NULL, OPT_ARG_ARRAY_SIZE, OPT_ARG_AUDIOSOCKET_CODEC, OPT_AUDIOSOCKET_CODEC, options, parse(), PARSE_PORT_REQUIRE, pbx_builtin_setvar_helper(), and audiosocket_instance::svc.
 {
    char *parse;
    struct audiosocket_instance *instance = NULL;
    struct ast_sockaddr address;
    struct ast_channel *chan;
    struct ast_format_cap *caps = NULL;
    struct ast_format *fmt = NULL;
    uuid_t uu;
    int fd = -1;
    AST_DECLARE_APP_ARGS(args,
       AST_APP_ARG(destination);
       AST_APP_ARG(idStr);
       AST_APP_ARG(options);
    );
    struct ast_flags opts = { 0, };
    char *opt_args[OPT_ARG_ARRAY_SIZE];
    if (ast_strlen_zero(data)) {
       ast_log(LOG_ERROR, "Destination is required for the 'AudioSocket' channel\n");
       goto failure;
    }
    parse = ast_strdupa(data);
    AST_NONSTANDARD_APP_ARGS(args, parse, '/');
    if (ast_strlen_zero(args.destination)) {
       ast_log(LOG_ERROR, "Destination is required for the 'AudioSocket' channel\n");
       goto failure;
    }
    if (ast_sockaddr_resolve_first_af
       (&address, args.destination, PARSE_PORT_REQUIRE, AST_AF_UNSPEC)) {
       ast_log(LOG_ERROR, "Destination '%s' could not be parsed\n", args.destination);
       goto failure;
    }
    if (ast_strlen_zero(args.idStr)) {
       ast_log(LOG_ERROR, "UUID is required for the 'AudioSocket' channel\n");
       goto failure;
    }
    if (uuid_parse(args.idStr, uu)) {
       ast_log(LOG_ERROR, "Failed to parse UUID '%s'\n", args.idStr);
       goto failure;
    }
    if (!ast_strlen_zero(args.options)
       && ast_app_parse_options(audiosocket_options, &opts, opt_args,
          ast_strdupa(args.options))) {
       ast_log(LOG_ERROR, "'AudioSocket' channel options '%s' parse error\n",
          args.options);
       goto failure;
    }
    if (ast_test_flag(&opts, OPT_AUDIOSOCKET_CODEC)
       && !ast_strlen_zero(opt_args[OPT_ARG_AUDIOSOCKET_CODEC])) {
       fmt = ast_format_cache_get(opt_args[OPT_ARG_AUDIOSOCKET_CODEC]);
       if (!fmt) {
          ast_log(LOG_ERROR, "Codec '%s' not found for AudioSocket connection to '%s'\n",
             opt_args[OPT_ARG_AUDIOSOCKET_CODEC], args.destination);
          goto failure;
       }
    } else {
       fmt = ast_format_cap_get_format(cap, 0);
       if (!fmt) {
          ast_log(LOG_ERROR, "No codec available for AudioSocket connection to '%s'\n",
             args.destination);
          goto failure;
       }
    }
    caps = ast_format_cap_alloc(AST_FORMAT_CAP_FLAG_DEFAULT);
    if (!caps) {
       goto failure;
    }
    instance = ast_calloc(1, sizeof(*instance));
    if (!instance) {
       ast_log(LOG_ERROR, "Failed to allocate AudioSocket channel pvt\n");
       goto failure;
    }
    ast_copy_string(instance->id, args.idStr, sizeof(instance->id));
    if ((fd = ast_audiosocket_connect(args.destination, NULL)) < 0) {
       goto failure;
    }
    instance->svc = fd;
    chan = ast_channel_alloc(1, AST_STATE_DOWN, "", "", "", "", "", assignedids,
       requestor, 0, "AudioSocket/%s-%s", args.destination, args.idStr);
    if (!chan) {
       goto failure;
    }
    ast_channel_set_fd(chan, 0, fd);
    ast_channel_tech_set(chan, &audiosocket_channel_tech);
    ast_format_cap_append(caps, fmt, 0);
    ast_channel_nativeformats_set(chan, caps);
    ast_channel_set_writeformat(chan, fmt);
    ast_channel_set_rawwriteformat(chan, fmt);
    ast_channel_set_readformat(chan, fmt);
    ast_channel_set_rawreadformat(chan, fmt);
    ast_channel_tech_pvt_set(chan, instance);
    pbx_builtin_setvar_helper(chan, "AUDIOSOCKET_UUID", args.idStr);
    pbx_builtin_setvar_helper(chan, "AUDIOSOCKET_SERVICE", args.destination);
    ast_channel_unlock(chan);
    ao2_ref(fmt, -1);
    ao2_ref(caps, -1);
    return chan;
 failure:
    *cause = AST_CAUSE_FAILURE;
    ao2_cleanup(fmt);
    ao2_cleanup(caps);
    if (instance != NULL) {
       ast_free(instance);
       if (fd >= 0) {
          close(fd);
       }
    }
    return NULL;
 }
audiosocket_write()
static int audiosocket_write (struct ast_channel * ast, struct ast_frame * f) static
Function called when we should write a frame to the channel.
Definition at line 86 of file chan_audiosocket.c.
References ast_audiosocket_send_frame(), ast_channel_tech_pvt(), NULL, and audiosocket_instance::svc.
 {
    struct audiosocket_instance *instance;
    /* The channel should always be present from the API */
    instance = ast_channel_tech_pvt(ast);
    if (instance == NULL || instance->svc < 1) {
       return -1;
    }
    return ast_audiosocket_send_frame(instance->svc, f);
 }
load_module()
static int load_module (void) static
Function called when our module is loaded.
Definition at line 279 of file chan_audiosocket.c.
References ao2_ref, ast_channel_register(), ast_format_cap_alloc, ast_format_cap_append_by_type(), AST_FORMAT_CAP_FLAG_DEFAULT, ast_log, AST_MEDIA_TYPE_UNKNOWN, AST_MODFLAG_LOAD_ORDER, AST_MODPRI_CHANNEL_DRIVER, AST_MODULE_INFO(), AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, AST_MODULE_SUPPORT_EXTENDED, ASTERISK_GPL_KEY, ast_channel_tech::capabilities, LOG_ERROR, NULL, and unload_module().
 {
    if (!(audiosocket_channel_tech.capabilities = ast_format_cap_alloc(AST_FORMAT_CAP_FLAG_DEFAULT))) {
       return AST_MODULE_LOAD_DECLINE;
    }
    ast_format_cap_append_by_type(audiosocket_channel_tech.capabilities, AST_MEDIA_TYPE_UNKNOWN);
    if (ast_channel_register(&audiosocket_channel_tech)) {
       ast_log(LOG_ERROR, "Unable to register channel class AudioSocket");
       ao2_ref(audiosocket_channel_tech.capabilities, -1);
       audiosocket_channel_tech.capabilities = NULL;
       return AST_MODULE_LOAD_DECLINE;
    }
    return AST_MODULE_LOAD_SUCCESS;
 }
unload_module()
static int unload_module (void) static
Function called when our module is unloaded.
Definition at line 269 of file chan_audiosocket.c.
References ao2_cleanup, ast_channel_unregister(), ast_channel_tech::capabilities, and NULL.
Referenced by load_module().
 {
    ast_channel_unregister(&audiosocket_channel_tech);
    ao2_cleanup(audiosocket_channel_tech.capabilities);
    audiosocket_channel_tech.capabilities = NULL;
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "AudioSocket Channel" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_EXTENDED, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_CHANNEL_DRIVER, .requires = "res_audiosocket", } static
Definition at line 301 of file chan_audiosocket.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 301 of file chan_audiosocket.c.
audiosocket_channel_tech
struct ast_channel_tech audiosocket_channel_tech static
Definition at line 62 of file chan_audiosocket.c.
audiosocket_instance
struct audiosocket_instance audiosocket_instance
audiosocket_options
const struct ast_app_option audiosocket_options[128] = { [ 'c' ] = { .flag = OPT_AUDIOSOCKET_CODEC , .arg_index = OPT_ARG_AUDIOSOCKET_CODEC + 1 }, } static
Definition at line 136 of file chan_audiosocket.c.
Referenced by audiosocket_request().