Asterisk - The Open Source Telephony Project: uri.c File Reference
uri.c File Reference
#include "asterisk.h"
#include "asterisk/astobj2.h"
#include "asterisk/strings.h"
#include "asterisk/uri.h"
#include <uriparser/Uri.h>
Data Structures
struct ast_uri
Stores parsed uri information.
Macros
#define SET_VALUE(param, field, size)
Functions
struct ast_uri * ast_uri_copy_replace (const struct ast_uri *uri, const char *scheme, const char *user_info, const char *host, const char *port, const char *path, const char *query)
Copy the given uri replacing any value in the new uri with any given.
struct ast_uri * ast_uri_create (const char *scheme, const char *user_info, const char *host, const char *port, const char *path, const char *query)
Create a uri with the given parameters.
static struct ast_uri * ast_uri_create_ (const char *scheme, unsigned int scheme_size, const char *user_info, unsigned int user_info_size, const char *host, unsigned int host_size, const char *port, unsigned int port_size, const char *path, unsigned int path_size, const char *query, unsigned int query_size)
Construct a uri object with the given values.
const char * ast_uri_host (const struct ast_uri *uri)
Retrieve the uri host.
int ast_uri_is_secure (const struct ast_uri *uri)
Retrieve if the uri is of a secure type.
char * ast_uri_make_host_with_port (const struct ast_uri *uri)
Retrieve a string of the host and port.
struct ast_uri * ast_uri_parse (const char *uri)
Parse the given uri into a structure.
struct ast_uri * ast_uri_parse_http (const char *uri)
Parse the given http uri into a structure.
struct ast_uri * ast_uri_parse_websocket (const char *uri)
Parse the given websocket uri into a structure.
const char * ast_uri_path (const struct ast_uri *uri)
Retrieve the uri path.
const char * ast_uri_port (const struct ast_uri *uri)
Retrieve the uri port.
const char * ast_uri_query (const struct ast_uri *uri)
Retrieve the uri query parameters.
const char * ast_uri_scheme (const struct ast_uri *uri)
Retrieve the uri scheme.
const char * ast_uri_user_info (const struct ast_uri *uri)
Retrieve the uri user information.
static struct ast_uri * uri_parse_and_default (const char *uri, const char *scheme, const char *port, const char *secure_port)
Macro Definition Documentation
SET_VALUE
#define SET_VALUE (param, field, size)
Value:
do { if (param) { \
        ast_copy_string(p, param, size); \
        field = p; \
        p += size;   } } while (0)
Referenced by ast_uri_create_().
Function Documentation
ast_uri_copy_replace()
struct ast_uri* ast_uri_copy_replace (const struct ast_uri * uri, const char * scheme, const char * user_info, const char * host, const char * port, const char * path, const char * query)
Copy the given uri replacing any value in the new uri with any given.
Parameters
uri the uri object to copy
scheme the uri scheme (ex: http)
user_info user credentials (ex: <name><pass>)
host host name or ip address
port the port
path the path
query query parameters
Returns
a copy of the given uri with specified values replaced.
NULL on error
Since
13
Definition at line 101 of file uri.c.
References ast_uri_create(), ast_uri::host, ast_uri::path, ast_uri::port, ast_uri::query, ast_uri::scheme, and ast_uri::user_info.
Referenced by uri_parse_and_default().
 {
    return ast_uri_create(
       scheme ? scheme : uri->scheme,
       user_info ? user_info : uri->user_info,
       host ? host : uri->host,
       port ? port : uri->port,
       path ? path : uri->path,
       query ? query : uri->query);
 }
ast_uri_create()
struct ast_uri* ast_uri_create (const char * scheme, const char * user_info, const char * host, const char * port, const char * path, const char * query)
Create a uri with the given parameters.
Parameters
scheme the uri scheme (ex: http)
user_info user credentials (ex: <name><pass>)
host host name or ip address
port the port
path the path
query query parameters
Returns
a structure containing parsed uri data.
NULL on error
Since
13
Definition at line 88 of file uri.c.
References ast_uri_create_().
Referenced by ast_uri_copy_replace().
 {
    return ast_uri_create_(
       scheme, scheme ? strlen(scheme) + 1 : 0,
       user_info, user_info ? strlen(user_info) + 1 : 0,
       host, host ? strlen(host) + 1 : 0,
       port, port ? strlen(port) + 1 : 0,
       path, path ? strlen(path) + 1 : 0,
       query, query ? strlen(query) + 1 : 0);
 }
ast_uri_create_()
static struct ast_uri* ast_uri_create_ (const char * scheme, unsigned int scheme_size, const char * user_info, unsigned int user_info_size, const char * host, unsigned int host_size, const char * port, unsigned int port_size, const char * path, unsigned int path_size, const char * query, unsigned int query_size) static
Construct a uri object with the given values.
Note
The size parameters [should] include room for the string terminator (strlen(<param>) + 1). For instance, if a scheme of 'http' is given then the 'scheme_size' should be equal to 5.
Definition at line 54 of file uri.c.
References ao2_alloc, ast_log, ast_uri::host, LOG_ERROR, NULL, ast_uri::path, ast_uri::port, ast_uri::query, ast_uri::scheme, SET_VALUE, ast_uri::uri, and ast_uri::user_info.
Referenced by ast_uri_create(), and ast_uri_parse().
 {
 #define SET_VALUE(param, field, size) \
    do { if (param) { \
         ast_copy_string(p, param, size); \
         field = p; \
         p += size;   } } while (0)
    char *p;
    struct ast_uri *res = ao2_alloc(
       sizeof(*res) + scheme_size + user_info_size + host_size +
       port_size + path_size + query_size, NULL);
    if (!res) {
       ast_log(LOG_ERROR, "Unable to create URI object\n");
       return NULL;
    }
    p = res->uri;
    SET_VALUE(scheme, res->scheme, scheme_size);
    SET_VALUE(user_info, res->user_info, user_info_size);
    SET_VALUE(host, res->host, host_size);
    SET_VALUE(port, res->port, port_size);
    SET_VALUE(path, res->path, path_size);
    SET_VALUE(query, res->query, query_size);
    return res;
 }
ast_uri_host()
const char* ast_uri_host (const struct ast_uri * uri)
Retrieve the uri host.
Returns
the uri host.
Since
13
Definition at line 125 of file uri.c.
References ast_uri::host.
Referenced by AST_TEST_DEFINE(), and ast_uri_make_host_with_port().
 {
    return uri->host;
 }
ast_uri_is_secure()
int ast_uri_is_secure (const struct ast_uri * uri)
Retrieve if the uri is of a secure type.
Note
Secure types are recognized by an 's' at the end of the scheme.
Returns
True if secure, False otherwise.
Since
13
Definition at line 145 of file uri.c.
References ast_strlen_zero, and ast_uri::scheme.
Referenced by AST_TEST_DEFINE(), and uri_parse_and_default().
 {
    return ast_strlen_zero(uri->scheme) ? 0 :
       *(uri->scheme + strlen(uri->scheme) - 1) == 's';
 }
ast_uri_make_host_with_port()
char* ast_uri_make_host_with_port (const struct ast_uri * uri)
Retrieve a string of the host and port.
Combine the host and port (<host>:<port>) if the port is available, otherwise just return the host.
Note
Caller is responsible for release the returned string.
Parameters
uri the uri object
Returns
a string value of the host and optional port.
Since
13
Definition at line 300 of file uri.c.
References ast_malloc, ast_uri_host(), ast_uri_port(), and NULL.
Referenced by websocket_client_parse_uri().
 {
    int host_size = ast_uri_host(uri) ?
       strlen(ast_uri_host(uri)) : 0;
    /* if there is a port +1 for the colon */
    int port_size = ast_uri_port(uri) ?
       strlen(ast_uri_port(uri)) + 1 : 0;
    char *res = ast_malloc(host_size + port_size + 1);
    if (!res) {
       return NULL;
    }
    memcpy(res, ast_uri_host(uri), host_size);
    if (ast_uri_port(uri)) {
       res[host_size] = ':';
       memcpy(res + host_size + 1,
              ast_uri_port(uri), port_size - 1);
    }
    res[host_size + port_size] = '\0';
    return res;
 }
ast_uri_parse()
struct ast_uri* ast_uri_parse (const char * uri)
Parse the given uri into a structure.
Note
Expects the following form: <scheme>://[user:pass@]<host>[:port][/<path>]
Parameters
uri a string uri to parse
Returns
a structure containing parsed uri data.
NULL on error
Since
13
Definition at line 152 of file uri.c.
References ast_log, ast_uri_create_(), ast_uri::host, LOG_ERROR, NULL, ast_uri::path, ast_uri::port, ast_uri::query, ast_uri::scheme, state, ast_uri::uri, and ast_uri::user_info.
Referenced by AST_TEST_DEFINE(), and uri_parse_and_default().
 {
    UriParserStateA state;
    UriUriA uria;
    struct ast_uri *res;
    unsigned int scheme_size, user_info_size, host_size;
    unsigned int port_size, path_size, query_size;
    const char *path_start, *path_end;
    state.uri = &uria;
    if (uriParseUriA(&state, uri) != URI_SUCCESS) {
       ast_log(LOG_ERROR, "Unable to parse URI %s\n", uri);
       uriFreeUriMembersA(&uria);
       return NULL;
    }
    scheme_size = uria.scheme.first ?
       uria.scheme.afterLast - uria.scheme.first + 1 : 0;
    user_info_size = uria.userInfo.first ?
       uria.userInfo.afterLast - uria.userInfo.first + 1 : 0;
    host_size = uria.hostText.first ?
       uria.hostText.afterLast - uria.hostText.first + 1 : 0;
    port_size = uria.portText.first ?
       uria.portText.afterLast - uria.portText.first + 1 : 0;
    path_start = uria.pathHead && uria.pathHead->text.first ?
       uria.pathHead->text.first : NULL;
    path_end = path_start ? uria.pathTail->text.afterLast : NULL;
    path_size = path_end ? path_end - path_start + 1 : 0;
    query_size = uria.query.first ?
       uria.query.afterLast - uria.query.first + 1 : 0;
    res = ast_uri_create_(uria.scheme.first, scheme_size,
                uria.userInfo.first, user_info_size,
                uria.hostText.first, host_size,
                uria.portText.first, port_size,
                path_start, path_size,
                uria.query.first, query_size);
    uriFreeUriMembersA(&uria);
    return res;
 }
ast_uri_parse_http()
struct ast_uri* ast_uri_parse_http (const char * uri)
Parse the given http uri into a structure.
Note
Expects the following form:
If no scheme is given it defaults to 'http' and if no port is specified it will default to 443 if marked secure, otherwise to 80.
Parameters
uri an http string uri to parse
Returns
a structure containing parsed http uri data.
NULL on error
Since
13
Definition at line 290 of file uri.c.
References uri_parse_and_default().
Referenced by AST_TEST_DEFINE().
 {
    return uri_parse_and_default(uri, "http", "80", "443");
 }
ast_uri_parse_websocket()
struct ast_uri* ast_uri_parse_websocket (const char * uri)
Parse the given websocket uri into a structure.
Note
Expects the following form:
If no scheme is given it defaults to 'ws' and if no port is specified it will default to 443 if marked secure, otherwise to 80.
Parameters
uri a websocket string uri to parse
Returns
a structure containing parsed http uri data.
NULL on error
Since
13
Definition at line 295 of file uri.c.
References uri_parse_and_default().
Referenced by websocket_client_parse_uri().
 {
    return uri_parse_and_default(uri, "ws", "80", "443");
 }
ast_uri_path()
const char* ast_uri_path (const struct ast_uri * uri)
Retrieve the uri path.
Returns
the uri path.
Since
13
Definition at line 135 of file uri.c.
References ast_uri::path.
Referenced by AST_TEST_DEFINE(), and websocket_client_parse_uri().
 {
    return uri->path;
 }
ast_uri_port()
const char* ast_uri_port (const struct ast_uri * uri)
Retrieve the uri port.
Returns
the uri port.
Since
13
Definition at line 130 of file uri.c.
References ast_uri::port.
Referenced by AST_TEST_DEFINE(), ast_uri_make_host_with_port(), and uri_parse_and_default().
 {
    return uri->port;
 }
ast_uri_query()
const char* ast_uri_query (const struct ast_uri * uri)
Retrieve the uri query parameters.
Returns
the uri query parameters.
Since
13
Definition at line 140 of file uri.c.
References ast_uri::query.
Referenced by AST_TEST_DEFINE(), and websocket_client_parse_uri().
 {
    return uri->query;
 }
ast_uri_scheme()
const char* ast_uri_scheme (const struct ast_uri * uri)
Retrieve the uri scheme.
Returns
the uri scheme.
Since
13
Definition at line 115 of file uri.c.
References ast_uri::scheme.
Referenced by AST_TEST_DEFINE().
 {
    return uri->scheme;
 }
ast_uri_user_info()
const char* ast_uri_user_info (const struct ast_uri * uri)
Retrieve the uri user information.
Returns
the uri user information.
Since
13
Definition at line 120 of file uri.c.
References ast_uri::user_info.
Referenced by AST_TEST_DEFINE().
 {
    return uri->user_info;
 }
uri_parse_and_default()
static struct ast_uri* uri_parse_and_default (const char * uri, const char * scheme, const char * port, const char * secure_port) static
Definition at line 253 of file uri.c.
References ao2_ref, ast_free, ast_log, ast_malloc, ast_strlen_zero, ast_uri_copy_replace(), ast_uri_is_secure(), ast_uri_parse(), ast_uri_port(), len(), LOG_ERROR, NULL, and tmp().
Referenced by ast_uri_parse_http(), and ast_uri_parse_websocket().
 {
    struct ast_uri *res;
    int len = strlen(scheme);
    if (!strncmp(uri, scheme, len)) {
       res = ast_uri_parse(uri);
    } else {
       /* make room for <scheme>:// */
       char *with_scheme = ast_malloc(len + strlen(uri) + 4);
       if (!with_scheme) {
          ast_log(LOG_ERROR, "Unable to allocate uri '%s' with "
             "scheme '%s'", uri, scheme);
          return NULL;
       }
       /* safe - 'with_scheme' created with size equal to len of
          scheme plus length of uri plus space for extra characters
          '://' and terminator */
       sprintf(with_scheme, "%s://%s", scheme, uri);
       res = ast_uri_parse(with_scheme);
       ast_free(with_scheme);
    }
    if (res && ast_strlen_zero(ast_uri_port(res))) {
       /* default the port if not given */
       struct ast_uri *tmp = ast_uri_copy_replace(
          res, NULL, NULL, NULL,
          ast_uri_is_secure(res) ? secure_port : port,
          NULL, NULL);
       ao2_ref(res, -1);
       res = tmp;
    }
    return res;
 }