Asterisk - The Open Source Telephony Project: test_substitution.c File Reference
test_substitution.c File Reference
Substitution Test.
#include "asterisk.h"
#include "asterisk/file.h"
#include "asterisk/channel.h"
#include "asterisk/pbx.h"
#include "asterisk/module.h"
#include "asterisk/lock.h"
#include "asterisk/app.h"
#include "asterisk/strings.h"
#include "asterisk/stringfields.h"
#include "asterisk/threadstorage.h"
#include "asterisk/test.h"
#include "asterisk/vector.h"
Macros
#define TEST(t) if (t == AST_TEST_FAIL) { res = AST_TEST_FAIL; }
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
AST_TEST_DEFINE (test_substitution)
static int load_module (void)
static enum ast_test_result_state test_2way_function (struct ast_test *test, struct ast_channel *c, const char *encode1, const char *encode2, const char *decode1, const char *decode2)
static enum ast_test_result_state test_chan_function (struct ast_test *test, struct ast_channel *c, const char *expression)
static enum ast_test_result_state test_chan_integer (struct ast_test *test, struct ast_channel *c, int *ifield, const char *expression)
static enum ast_test_result_state test_chan_integer_accessor (struct ast_test *test, struct ast_channel *c, void(*setter)(struct ast_channel *, int), const char *expression)
static enum ast_test_result_state test_chan_string (struct ast_test *test, struct ast_channel *c, void(*setter)(struct ast_channel *, const char *), const char *(*getter)(const struct ast_channel *), const char *expression)
static enum ast_test_result_state test_chan_variable (struct ast_test *test, struct ast_channel *c, const char *varname)
static enum ast_test_result_state test_expected_result (struct ast_test *test, struct ast_channel *c, const char *expression, const char *result)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Substitution tests" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, }
static const struct ast_module_info * ast_module_info = &__mod_info
Detailed Description
Substitution Test.
Author
Tilghman Lesher <tlesher AT digium DOT com>
Definition in file test_substitution.c.
Macro Definition Documentation
TEST
#define TEST (t) if (t == AST_TEST_FAIL) { res = AST_TEST_FAIL; }
Referenced by AST_TEST_DEFINE().
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 350 of file test_substitution.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 350 of file test_substitution.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 350 of file test_substitution.c.
AST_TEST_DEFINE()
AST_TEST_DEFINE (test_substitution)
Definition at line 224 of file test_substitution.c.
References ast_channel_alloc, ast_channel_caller(), ast_channel_context(), ast_channel_context_set(), ast_channel_dialed(), ast_channel_exten(), ast_channel_exten_set(), ast_channel_hangupcause_set(), ast_channel_priority_set(), ast_channel_unlock, ast_cli_completion_vector(), ast_custom_function_find(), ast_free, ast_hangup(), AST_TEST_FAIL, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_test_status_update, AST_VECTOR_CALLBACK_VOID, AST_VECTOR_GET, AST_VECTOR_PTR_FREE, AST_VECTOR_SIZE, c, ast_channel::caller, ast_party_caller::id, sip_to_pjsip::info(), NULL, ast_party_id::number, pbx_builtin_setvar_helper(), ast_party_number::presentation, ast_custom_function::read, ast_custom_function::read2, TEST, test_2way_function(), test_chan_function(), test_chan_integer(), test_chan_integer_accessor(), test_chan_string(), test_chan_variable(), TEST_EXECUTE, test_expected_result(), and TEST_INIT.
 {
    struct ast_channel *c;
    int i;
    enum ast_test_result_state res = AST_TEST_PASS;
    struct ast_vector_string *funcs;
    switch (cmd) {
    case TEST_INIT:
       info->name = "test_substitution";
       info->category = "/main/pbx/";
       info->summary = "Test variable and function substitution";
       info->description =
          "This test executes a variety of variable and function substitutions "
          "and ensures that the expected results are received.";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    ast_test_status_update(test, "Testing variable substitution ...\n");
    c = ast_channel_alloc(0, 0, "", "", "", "", "", NULL, NULL, 0, "Test/substitution");
    ast_channel_unlock(c);
 #define TEST(t) if (t == AST_TEST_FAIL) { res = AST_TEST_FAIL; }
 #if 0
    /*
     * We can no longer test the CALLINGPRES value this way because it is now
     * a calculated value from the name and number presentation information to
     * get a combined presentation value.
     */
    TEST(test_chan_integer(test, c, &c->caller.id.number.presentation, "${CALLINGPRES}"));
 #endif
    TEST(test_chan_integer(test, c, &ast_channel_caller(c)->ani2, "${CALLINGANI2}"));
    TEST(test_chan_integer(test, c, &ast_channel_caller(c)->id.number.plan, "${CALLINGTON}"));
    TEST(test_chan_integer(test, c, &ast_channel_dialed(c)->transit_network_select, "${CALLINGTNS}"));
    TEST(test_chan_integer_accessor(test, c, ast_channel_hangupcause_set, "${HANGUPCAUSE}"));
    TEST(test_chan_integer_accessor(test, c, ast_channel_priority_set, "${PRIORITY}"));
    TEST(test_chan_string(test, c, ast_channel_context_set, ast_channel_context, "${CONTEXT}"));
    TEST(test_chan_string(test, c, ast_channel_exten_set, ast_channel_exten, "${EXTEN}"));
    TEST(test_chan_variable(test, c, "CHANNEL(language)"));
    TEST(test_chan_variable(test, c, "CHANNEL(musicclass)"));
    TEST(test_chan_variable(test, c, "CHANNEL(parkinglot)"));
    TEST(test_chan_variable(test, c, "CALLERID(name)"));
    TEST(test_chan_variable(test, c, "CURLOPT(proxyuserpwd)"));
    TEST(test_chan_variable(test, c, "CDR(foo)"));
    TEST(test_chan_variable(test, c, "ENV(foo)"));
    TEST(test_chan_variable(test, c, "GLOBAL(foo)"));
    TEST(test_chan_variable(test, c, "GROUP()"));
    TEST(test_2way_function(test, c, "${AES_ENCRYPT(abcdefghijklmnop,", ")}", "${AES_DECRYPT(abcdefghijklmnop,", ")}"));
    TEST(test_2way_function(test, c, "${BASE64_ENCODE(", ")}", "${BASE64_DECODE(", ")}"));
    pbx_builtin_setvar_helper(c, "foo", "123");
    pbx_builtin_setvar_helper(c, "bar", "foo");
    pbx_builtin_setvar_helper(c, "baz", "fo");
    TEST(test_expected_result(test, c, "${foo}${foo}", "123123"));
    TEST(test_expected_result(test, c, "A${foo}A${foo}A", "A123A123A"));
    TEST(test_expected_result(test, c, "A${${bar}}A", "A123A"));
    TEST(test_expected_result(test, c, "A${${baz}o}A", "A123A"));
    TEST(test_expected_result(test, c, "A${${baz}o:1}A", "A23A"));
    TEST(test_expected_result(test, c, "A${${baz}o:1:1}A", "A2A"));
    TEST(test_expected_result(test, c, "A${${baz}o:1:-1}A", "A2A"));
    TEST(test_expected_result(test, c, "A${${baz}o:-1:1}A", "A3A"));
    TEST(test_expected_result(test, c, "A${${baz}o:-2:1}A", "A2A"));
    TEST(test_expected_result(test, c, "A${${baz}o:-2:-1}A", "A2A"));
    pbx_builtin_setvar_helper(c, "list1", "ab&cd&ef");
    TEST(test_expected_result(test, c, "${LISTFILTER(list1,&,ab)}", "cd&ef"));
    TEST(test_expected_result(test, c, "${LISTFILTER(list1,&,cd)}", "ab&ef"));
    TEST(test_expected_result(test, c, "${LISTFILTER(list1,&,ef)}", "ab&cd"));
    TEST(test_expected_result(test, c, "${LISTFILTER(list1,&,gh)}", "ab&cd&ef"));
    TEST(test_expected_result(test, c, "${LISTFILTER(list1,&,c)}", "ab&cd&ef"));
    TEST(test_expected_result(test, c, "${LISTFILTER(list1,&,d)}", "ab&cd&ef"));
    pbx_builtin_setvar_helper(c, "list2", "ab");
    TEST(test_expected_result(test, c, "${LISTFILTER(list2,&,ab)}", ""));
    pbx_builtin_setvar_helper(c, "list_empty", "");
    TEST(test_expected_result(test, c, "${LISTFILTER(list_empty,&,ab)}", ""));
    TEST(test_expected_result(test, c, "${SHELL(printf '%d' 123)},${SHELL(printf '%d' 456)}", "123,456"));
    TEST(test_expected_result(test, c, "${foo},${CDR(answer)},${SHELL(printf '%d' 456)}", "123,,456"));
    TEST(test_expected_result(test, c, "${foo},${CDR(answer,u)},${SHELL(printf '%d' 456)}", "123,0.000000,456"));
    TEST(test_expected_result(test, c, "${foo},${this_does_not_exist},${THIS_DOES_NOT_EXIST(either)}", "123,,"));
 #undef TEST
    /* For testing dialplan functions */
    funcs = ast_cli_completion_vector("core show function", "");
    /* Skip "best match" element 0 */
    for (i = 1; funcs && i < AST_VECTOR_SIZE(funcs); i++) {
       char *cmd = AST_VECTOR_GET(funcs, i);
       if (strcmp(cmd, "CHANNEL") && strcmp(cmd, "CALLERID") && strncmp(cmd, "CURL", 4) &&
             strncmp(cmd, "AES", 3) && strncmp(cmd, "BASE64", 6) &&
             strcmp(cmd, "CDR") && strcmp(cmd, "ENV") && strcmp(cmd, "GLOBAL") &&
             strcmp(cmd, "GROUP") && strcmp(cmd, "CUT") && strcmp(cmd, "LISTFILTER") &&
             strcmp(cmd, "PP_EACH_EXTENSION") && strcmp(cmd, "SET")) {
          struct ast_custom_function *acf = ast_custom_function_find(cmd);
          if (acf->read && acf->read2) {
             char expression[80];
             snprintf(expression, sizeof(expression), "${%s(foo)}", cmd);
             if (AST_TEST_FAIL == test_chan_function(test, c, expression)) {
                res = AST_TEST_FAIL;
             }
          }
       }
    }
    if (funcs) {
       AST_VECTOR_CALLBACK_VOID(funcs, ast_free);
       AST_VECTOR_PTR_FREE(funcs);
    }
    ast_hangup(c);
    return res;
 }
load_module()
static int load_module (void) static
Definition at line 344 of file test_substitution.c.
References AST_MODULE_LOAD_SUCCESS, and AST_TEST_REGISTER.
 {
    AST_TEST_REGISTER(test_substitution);
    return AST_MODULE_LOAD_SUCCESS;
 }
test_2way_function()
static enum ast_test_result_state test_2way_function (struct ast_test * test, struct ast_channel * c, const char * encode1, const char * encode2, const char * decode1, const char * decode2) static
Definition at line 176 of file test_substitution.c.
References ast_free, ast_str_alloca, ast_str_buffer(), ast_str_create, ast_str_set(), ast_str_substitute_variables(), AST_TEST_FAIL, AST_TEST_PASS, ast_test_status_update, and str.
Referenced by AST_TEST_DEFINE().
 {
    struct ast_str *str = ast_str_create(16), *expression = ast_str_alloca(120);
    int okay;
    ast_str_set(&expression, 0, "%s%s%s", encode1, "foobarbaz", encode2);
    ast_str_substitute_variables(&str, 0, c, ast_str_buffer(expression));
    ast_str_set(&expression, 0, "%s%s%s", decode1, ast_str_buffer(str), decode2);
    ast_str_substitute_variables(&str, 0, c, ast_str_buffer(expression));
    okay = !strcmp(ast_str_buffer(str), "foobarbaz");
    if (!okay) {
       ast_test_status_update(test, "'%s' != 'foobarbaz'\n",
             ast_str_buffer(str));
    }
    ast_test_status_update(test, "Tested '%s%s' and '%s%s' . . . . . %s\n",
       encode1, encode2, decode1, decode2,
       okay ? "passed" : "FAILED");
    ast_free(str);
    return okay ? AST_TEST_PASS : AST_TEST_FAIL;
 }
test_chan_function()
static enum ast_test_result_state test_chan_function (struct ast_test * test, struct ast_channel * c, const char * expression) static
Definition at line 153 of file test_substitution.c.
References ast_free, ast_str_buffer(), ast_str_create, ast_str_substitute_variables(), AST_TEST_FAIL, AST_TEST_PASS, ast_test_status_update, pbx_substitute_variables_helper(), and str.
Referenced by AST_TEST_DEFINE().
 {
    int okay = 1;
    char workspace[4096];
    struct ast_str *str = ast_str_create(16);
    ast_str_substitute_variables(&str, 0, c, expression);
    pbx_substitute_variables_helper(c, expression, workspace, sizeof(workspace));
    if (strcmp(workspace, ast_str_buffer(str)) != 0) {
       ast_test_status_update(test, "expr: '%s' ... %s != %s\n",
             expression, ast_str_buffer(str), workspace);
       okay = 0;
    }
    ast_test_status_update(test, "Tested '%s' . . . . . %s\n",
       expression, okay ? "passed" : "FAILED");
    ast_free(str);
    return okay ? AST_TEST_PASS : AST_TEST_FAIL;
 }
test_chan_integer()
static enum ast_test_result_state test_chan_integer (struct ast_test * test, struct ast_channel * c, int * ifield, const char * expression) static
Definition at line 48 of file test_substitution.c.
References ast_free, ast_str_buffer(), ast_str_create, ast_str_substitute_variables(), AST_TEST_FAIL, AST_TEST_PASS, ast_test_status_update, pbx_substitute_variables_helper(), and str.
Referenced by AST_TEST_DEFINE().
 {
    int i, okay = 1, value1 = -1, value2 = -1;
    char workspace[4096];
    struct ast_str *str = ast_str_create(16);
    for (i = 0; i < 256; i++) {
       *ifield = i;
       ast_str_substitute_variables(&str, 0, c, expression);
       pbx_substitute_variables_helper(c, expression, workspace, sizeof(workspace));
       if (sscanf(workspace, "%d", &value1) != 1 || value1 != i || sscanf(ast_str_buffer(str), "%d", &value2) != 1 || value2 != i) {
          ast_test_status_update(test, "%s != %s and/or %d != %d != %d\n", ast_str_buffer(str), workspace, value1, value2, i);
          okay = 0;
       }
    }
    ast_test_status_update(test, "Tested '%s' . . . . . %s\n", expression, okay ? "passed" : "FAILED");
    ast_free(str);
    return okay ? AST_TEST_PASS : AST_TEST_FAIL;
 }
test_chan_integer_accessor()
static enum ast_test_result_state test_chan_integer_accessor (struct ast_test * test, struct ast_channel * c, void(*)(struct ast_channel *, int) setter, const char * expression) static
Definition at line 72 of file test_substitution.c.
References ast_free, ast_str_buffer(), ast_str_create, ast_str_substitute_variables(), AST_TEST_FAIL, AST_TEST_PASS, ast_test_status_update, pbx_substitute_variables_helper(), and str.
Referenced by AST_TEST_DEFINE().
 {
    int i, okay = 1, value1 = -1, value2 = -1;
    char workspace[4096];
    struct ast_str *str = ast_str_create(16);
    for (i = 0; i < 256; i++) {
       setter(c, i);
       ast_str_substitute_variables(&str, 0, c, expression);
       pbx_substitute_variables_helper(c, expression, workspace, sizeof(workspace));
       if (sscanf(workspace, "%d", &value1) != 1 || value1 != i || sscanf(ast_str_buffer(str), "%d", &value2) != 1 || value2 != i) {
          ast_test_status_update(test, "%s != %s and/or %d != %d != %d\n", ast_str_buffer(str), workspace, value1, value2, i);
          okay = 0;
       }
    }
    ast_test_status_update(test, "Tested '%s' . . . . . %s\n", expression, okay ? "passed" : "FAILED");
    ast_free(str);
    return okay ? AST_TEST_PASS : AST_TEST_FAIL;
 }
test_chan_string()
static enum ast_test_result_state test_chan_string (struct ast_test * test, struct ast_channel * c, void(*)(struct ast_channel *, const char *) setter, const char *(*)(const struct ast_channel *) getter, const char * expression) static
Definition at line 96 of file test_substitution.c.
References ARRAY_LEN, ast_free, ast_str_buffer(), ast_str_create, ast_str_substitute_variables(), AST_TEST_FAIL, AST_TEST_PASS, ast_test_status_update, pbx_substitute_variables_helper(), and str.
Referenced by AST_TEST_DEFINE().
 {
    const char *values[] = { "one", "three", "reallylongdinosaursoundingthingwithwordsinit" };
    int i, okay = 1;
    char workspace[4096];
    struct ast_str *str = ast_str_create(16);
    for (i = 0; i < ARRAY_LEN(values); i++) {
       setter(c, values[i]);
       ast_str_substitute_variables(&str, 0, c, expression);
       pbx_substitute_variables_helper(c, expression, workspace, sizeof(workspace));
       if (strcmp(getter(c), ast_str_buffer(str)) != 0 || strcmp(getter(c), workspace) != 0) {
          ast_test_status_update(test, "%s != %s != %s\n", getter(c), ast_str_buffer(str), workspace);
          okay = 0;
       }
    }
    ast_test_status_update(test, "Tested '%s' . . . . . %s\n",
       expression, okay ? "passed" : "FAILED");
    ast_free(str);
    return okay ? AST_TEST_PASS : AST_TEST_FAIL;
 }
test_chan_variable()
static enum ast_test_result_state test_chan_variable (struct ast_test * test, struct ast_channel * c, const char * varname) static
Definition at line 123 of file test_substitution.c.
References ARRAY_LEN, ast_free, ast_str_buffer(), ast_str_create, ast_str_set(), ast_str_substitute_variables(), AST_TEST_FAIL, AST_TEST_PASS, ast_test_status_update, pbx_builtin_setvar_helper(), pbx_substitute_variables_helper(), str, and var.
Referenced by AST_TEST_DEFINE().
 {
    const char *values[] = { "one", "three", "reallylongdinosaursoundingthingwithwordsinit" };
    int i, okay = 1;
    char workspace[4096];
    struct ast_str *str = ast_str_create(16);
    struct ast_str *var = ast_str_create(16);
    ast_str_set(&var, 0, "${%s}", varname);
    for (i = 0; i < ARRAY_LEN(values); i++) {
       pbx_builtin_setvar_helper(c, varname, values[i]);
       ast_str_substitute_variables(&str, 0, c, ast_str_buffer(var));
       pbx_substitute_variables_helper(c, ast_str_buffer(var), workspace, sizeof(workspace));
       if (strcmp(values[i], ast_str_buffer(str)) != 0 || strcmp(values[i], workspace) != 0) {
          ast_test_status_update(test, "%s != %s != %s\n",
                values[i], ast_str_buffer(str), workspace);
          okay = 0;
       }
    }
    ast_test_status_update(test, "Tested '%s' . . . . . %s\n",
       ast_str_buffer(var), okay ? "passed" : "FAILED");
    ast_free(str);
    ast_free(var);
    return okay ? AST_TEST_PASS : AST_TEST_FAIL;
 }
test_expected_result()
static enum ast_test_result_state test_expected_result (struct ast_test * test, struct ast_channel * c, const char * expression, const char * result) static
Definition at line 202 of file test_substitution.c.
References ast_free, ast_str_buffer(), ast_str_create, ast_str_substitute_variables(), AST_TEST_FAIL, AST_TEST_PASS, ast_test_status_update, and str.
Referenced by AST_TEST_DEFINE().
 {
    struct ast_str *str = ast_str_create(16);
    int okay;
    ast_str_substitute_variables(&str, 0, c, expression);
    okay = !strcmp(ast_str_buffer(str), result);
    if (!okay) {
       ast_test_status_update(test, "'%s' != '%s'\n",
             ast_str_buffer(str), result);
    }
    ast_test_status_update(test, "Tested '%s' ('%s') == '%s' . . . . . %s\n",
       ast_str_buffer(str), expression, result,
       okay ? "passed" : "FAILED");
    ast_free(str);
    return okay ? AST_TEST_PASS : AST_TEST_FAIL;
 }
unload_module()
static int unload_module (void) static
Definition at line 338 of file test_substitution.c.
References AST_TEST_UNREGISTER.
 {
    AST_TEST_UNREGISTER(test_substitution);
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Substitution tests" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, } static
Definition at line 350 of file test_substitution.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 350 of file test_substitution.c.