Asterisk - The Open Source Telephony Project: res_format_attr_vp8.c File Reference
res_format_attr_vp8.c File Reference
VP8 format attribute interface.
#include "asterisk.h"
#include <ctype.h>
#include "asterisk/module.h"
#include "asterisk/format.h"
#include "asterisk/logger.h"
#include "asterisk/strings.h"
#include "asterisk/utils.h"
Data Structures
struct vp8_attr
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int load_module (void)
static int unload_module (void)
static int vp8_clone (const struct ast_format *src, struct ast_format *dst)
static void vp8_destroy (struct ast_format *format)
static void vp8_generate_sdp_fmtp (const struct ast_format *format, unsigned int payload, struct ast_str **str)
static struct ast_format * vp8_getjoint (const struct ast_format *format1, const struct ast_format *format2)
static struct ast_format * vp8_parse_sdp_fmtp (const struct ast_format *format, const char *attributes)
static struct ast_format * vp8_set (const struct ast_format *format, const char *name, const char *value)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "VP8 Format Attribute Module" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_CHANNEL_DEPEND, }
static const struct ast_module_info * ast_module_info = &__mod_info
static struct vp8_attr default_vp8_attr
static struct ast_format_interface vp8_interface
Detailed Description
VP8 format attribute interface.
Author
Alexander Traud pabst.nosp@m.raud.nosp@m.@comp.nosp@m.user.nosp@m.ve.co.nosp@m.m
Note
http://tools.ietf.org/html/draft-ietf-payload-vp8
Definition in file res_format_attr_vp8.c.
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 234 of file res_format_attr_vp8.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 234 of file res_format_attr_vp8.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 234 of file res_format_attr_vp8.c.
load_module()
static int load_module (void) static
Definition at line 215 of file res_format_attr_vp8.c.
References ast_format_interface_register, AST_MODULE_LOAD_DECLINE, and AST_MODULE_LOAD_SUCCESS.
Referenced by unload_module().
 {
    if (ast_format_interface_register("vp8", &vp8_interface)) {
       return AST_MODULE_LOAD_DECLINE;
    }
    return AST_MODULE_LOAD_SUCCESS;
 }
unload_module()
static int unload_module (void) static
Definition at line 224 of file res_format_attr_vp8.c.
References AST_MODFLAG_LOAD_ORDER, AST_MODPRI_CHANNEL_DEPEND, AST_MODULE_INFO(), AST_MODULE_SUPPORT_CORE, ASTERISK_GPL_KEY, and load_module().
 {
    return 0;
 }
vp8_clone()
static int vp8_clone (const struct ast_format * src, struct ast_format * dst) static
Definition at line 59 of file res_format_attr_vp8.c.
References ast_format_get_attribute_data(), ast_format_set_attribute_data(), ast_malloc, and default_vp8_attr.
 {
    struct vp8_attr *original = ast_format_get_attribute_data(src);
    struct vp8_attr *attr = ast_malloc(sizeof(*attr));
    if (!attr) {
       return -1;
    }
    if (original) {
       *attr = *original;
    } else {
       *attr = default_vp8_attr;
    }
    ast_format_set_attribute_data(dst, attr);
    return 0;
 }
vp8_destroy()
static void vp8_destroy (struct ast_format * format) static
Definition at line 52 of file res_format_attr_vp8.c.
References ast_format_get_attribute_data(), and ast_free.
 {
    struct vp8_attr *attr = ast_format_get_attribute_data(format);
    ast_free(attr);
 }
vp8_generate_sdp_fmtp()
static void vp8_generate_sdp_fmtp (const struct ast_format * format, unsigned int payload, struct ast_str ** str) static
Definition at line 113 of file res_format_attr_vp8.c.
References ast_format_get_attribute_data(), ast_str_append(), default_vp8_attr, vp8_attr::maximum_frame_rate, and vp8_attr::maximum_frame_size.
 {
    struct vp8_attr *attr = ast_format_get_attribute_data(format);
    int added = 0;
    if (!attr) {
       /*
        * (Only) cached formats do not have attribute data assigned because
        * they were created before this attribute module was registered.
        * Therefore, we assume the default attribute values here.
        */
       attr = &default_vp8_attr;
    }
    if (UINT_MAX != attr->maximum_frame_rate) {
       if (added) {
          ast_str_append(str, 0, ";");
       } else if (0 < ast_str_append(str, 0, "a=fmtp:%u ", payload)) {
          added = 1;
       }
       ast_str_append(str, 0, "max-fr=%u", attr->maximum_frame_rate);
    }
    if (UINT_MAX != attr->maximum_frame_size) {
       if (added) {
          ast_str_append(str, 0, ";");
       } else if (0 < ast_str_append(str, 0, "a=fmtp:%u ", payload)) {
          added = 1;
       }
       ast_str_append(str, 0, "max-fs=%u", attr->maximum_frame_size);
    }
    if (added) {
       ast_str_append(str, 0, "\r\n");
    }
 }
vp8_getjoint()
static struct ast_format* vp8_getjoint (const struct ast_format * format1, const struct ast_format * format2) static
Definition at line 150 of file res_format_attr_vp8.c.
References ast_format_clone(), ast_format_get_attribute_data(), default_vp8_attr, vp8_attr::maximum_frame_rate, vp8_attr::maximum_frame_size, MIN, and NULL.
 {
    struct vp8_attr *attr1 = ast_format_get_attribute_data(format1);
    struct vp8_attr *attr2 = ast_format_get_attribute_data(format2);
    struct ast_format *jointformat;
    struct vp8_attr *attr_res;
    if (!attr1) {
       attr1 = &default_vp8_attr;
    }
    if (!attr2) {
       attr2 = &default_vp8_attr;
    }
    jointformat = ast_format_clone(format1);
    if (!jointformat) {
       return NULL;
    }
    attr_res = ast_format_get_attribute_data(jointformat);
    attr_res->maximum_frame_rate = MIN(attr1->maximum_frame_rate, attr2->maximum_frame_rate);
    attr_res->maximum_frame_size = MIN(attr1->maximum_frame_size, attr2->maximum_frame_size);
    return jointformat;
 }
vp8_parse_sdp_fmtp()
static struct ast_format* vp8_parse_sdp_fmtp (const struct ast_format * format, const char * attributes) static
Definition at line 79 of file res_format_attr_vp8.c.
References ast_format_clone(), ast_format_get_attribute_data(), ast_strdupa, vp8_attr::maximum_frame_rate, vp8_attr::maximum_frame_size, and NULL.
 {
    char *attribs = ast_strdupa(attributes), *attrib;
    struct ast_format *cloned;
    struct vp8_attr *attr;
    const char *kvp;
    unsigned int val;
    cloned = ast_format_clone(format);
    if (!cloned) {
       return NULL;
    }
    attr = ast_format_get_attribute_data(cloned);
    /* lower-case everything, so we are case-insensitive */
    for (attrib = attribs; *attrib; ++attrib) {
       *attrib = tolower(*attrib);
    } /* based on channels/chan_sip.c:process_a_sdp_image() */
    if ((kvp = strstr(attribs, "max-fr")) && sscanf(kvp, "max-fr=%30u", &val) == 1) {
       attr->maximum_frame_rate = val;
    } else {
       attr->maximum_frame_rate = UINT_MAX;
    }
    if ((kvp = strstr(attribs, "max-fs")) && sscanf(kvp, "max-fs=%30u", &val) == 1) {
       attr->maximum_frame_size = val;
    } else {
       attr->maximum_frame_size = UINT_MAX;
    }
    return cloned;
 }
vp8_set()
static struct ast_format* vp8_set (const struct ast_format * format, const char * name, const char * value) static
Definition at line 177 of file res_format_attr_vp8.c.
References ast_format_clone(), ast_format_get_attribute_data(), ast_log, LOG_WARNING, vp8_attr::maximum_frame_rate, vp8_attr::maximum_frame_size, and NULL.
 {
    struct ast_format *cloned;
    struct vp8_attr *attr;
    unsigned int val;
    if (sscanf(value, "%30u", &val) != 1) {
       ast_log(LOG_WARNING, "Unknown value '%s' for attribute type '%s'\n",
          value, name);
       return NULL;
    }
    cloned = ast_format_clone(format);
    if (!cloned) {
       return NULL;
    }
    attr = ast_format_get_attribute_data(cloned);
    if (!strcasecmp(name, "maximum_frame_rate")) {
       attr->maximum_frame_rate = val;
    } else if (!strcasecmp(name, "maximum_frame_size")) {
       attr->maximum_frame_size = val;
    } else {
       ast_log(LOG_WARNING, "unknown attribute type %s\n", name);
    }
    return cloned;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "VP8 Format Attribute Module" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_CHANNEL_DEPEND, } static
Definition at line 234 of file res_format_attr_vp8.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 234 of file res_format_attr_vp8.c.
default_vp8_attr
struct vp8_attr default_vp8_attr static
Initial value:
= {
   .maximum_frame_rate = UINT_MAX,
   .maximum_frame_size = UINT_MAX,
}
Definition at line 47 of file res_format_attr_vp8.c.
Referenced by vp8_clone(), vp8_generate_sdp_fmtp(), and vp8_getjoint().
vp8_interface
struct ast_format_interface vp8_interface static
Definition at line 206 of file res_format_attr_vp8.c.