Asterisk - The Open Source Telephony Project: image.c File Reference
image.c File Reference
Image Management.
#include "asterisk.h"
#include <sys/time.h>
#include <sys/stat.h>
#include <signal.h>
#include "asterisk/paths.h"
#include "asterisk/sched.h"
#include "asterisk/channel.h"
#include "asterisk/file.h"
#include "asterisk/image.h"
#include "asterisk/translate.h"
#include "asterisk/cli.h"
#include "asterisk/lock.h"
Data Structures
struct imagers
Macros
#define FORMAT "%10s %10s %50s %10s\n"
#define FORMAT2 "%10s %10s %50s %10s\n"
Functions
int ast_image_init (void)
Initialize image stuff Initializes all the various image stuff. Basically just registers the cli stuff.
int ast_image_register (struct ast_imager *img)
Register image format.
void ast_image_unregister (struct ast_imager *img)
Unregister an image format.
struct ast_frame * ast_read_image (const char *filename, const char *preflang, struct ast_format *format)
Make an image.
int ast_send_image (struct ast_channel *chan, const char *filename)
Sends an image.
int ast_supports_images (struct ast_channel *chan)
Check for image support on a channel.
static int file_exists (char *filename)
static char * handle_core_show_image_formats (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static void image_shutdown (void)
static void make_filename (char *buf, int len, const char *filename, const char *preflang, char *ext)
Variables
static struct ast_cli_entry cli_image []
static struct imagers imagers = { .first = NULL, .last = NULL, .lock = { PTHREAD_RWLOCK_INITIALIZER , NULL, {1, 0} } , }
Detailed Description
Image Management.
Author
Mark Spencer marks.nosp@m.ter@.nosp@m.digiu.nosp@m.m.co.nosp@m.m
Definition in file image.c.
Macro Definition Documentation
FORMAT
#define FORMAT "%10s %10s %50s %10s\n"
Referenced by handle_core_show_image_formats().
FORMAT2
#define FORMAT2 "%10s %10s %50s %10s\n"
Referenced by handle_core_show_image_formats().
Function Documentation
ast_image_init()
int ast_image_init (void)
Initialize image stuff Initializes all the various image stuff. Basically just registers the cli stuff.
Returns
0 all the time
Definition at line 212 of file image.c.
References ARRAY_LEN, ast_cli_register_multiple, ast_register_cleanup(), and image_shutdown().
Referenced by asterisk_daemon().
 {
    ast_cli_register_multiple(cli_image, ARRAY_LEN(cli_image));
    ast_register_cleanup(image_shutdown);
    return 0;
 }
ast_image_register()
int ast_image_register (struct ast_imager * imgdrv)
Register image format.
Parameters
imgdrv Populated ast_imager structure with info to register Registers an image format
Returns
0 regardless
Definition at line 48 of file image.c.
References AST_RWLIST_INSERT_HEAD, AST_RWLIST_UNLOCK, AST_RWLIST_WRLOCK, ast_verb, ast_imager::desc, and ast_imager::name.
 {
    AST_RWLIST_WRLOCK(&imagers);
    AST_RWLIST_INSERT_HEAD(&imagers, img, list);
    AST_RWLIST_UNLOCK(&imagers);
    ast_verb(2, "Registered format '%s' (%s)\n", img->name, img->desc);
    return 0;
 }
ast_image_unregister()
void ast_image_unregister (struct ast_imager * imgdrv)
Unregister an image format.
Parameters
imgdrv pointer to the ast_imager structure you wish to unregister Unregisters the image format passed in. Returns nothing
Definition at line 57 of file image.c.
References AST_RWLIST_REMOVE, AST_RWLIST_UNLOCK, AST_RWLIST_WRLOCK, ast_verb, ast_imager::desc, and ast_imager::name.
 {
    AST_RWLIST_WRLOCK(&imagers);
    img = AST_RWLIST_REMOVE(&imagers, img, list);
    AST_RWLIST_UNLOCK(&imagers);
    if (img)
       ast_verb(2, "Unregistered format '%s' (%s)\n", img->name, img->desc);
 }
ast_read_image()
struct ast_frame* ast_read_image (const char * filename, const char * preflang, struct ast_format * format)
Make an image.
Parameters
filename filename of image to prepare
preflang preferred language to get the image...?
format the format of the file, NULL for any image format Make an image from a filename ??? No estoy positivo
Return values
an ast_frame on success
NULL on failure
Definition at line 101 of file image.c.
References ast_copy_string(), ast_format_cmp(), AST_FORMAT_CMP_EQUAL, ast_log, AST_RWLIST_RDLOCK, AST_RWLIST_TRAVERSE, AST_RWLIST_UNLOCK, buf, errno, ast_imager::exts, file_exists(), ast_imager::format, ast_imager::identify, len(), LOG_WARNING, make_filename(), ast_imager::name, NULL, ast_imager::read_image, strsep(), and tmp().
Referenced by ast_send_image().
 {
    struct ast_imager *i;
    char buf[256];
    char tmp[80];
    char *e;
    struct ast_imager *found = NULL;
    int fd;
    int len=0;
    struct ast_frame *f = NULL;
    AST_RWLIST_RDLOCK(&imagers);
    AST_RWLIST_TRAVERSE(&imagers, i, list) {
       /* if NULL image format, just pick the first one, otherwise match it. */
       if (!format || (ast_format_cmp(i->format, format) == AST_FORMAT_CMP_EQUAL)) {
          char *stringp=NULL;
          ast_copy_string(tmp, i->exts, sizeof(tmp));
          stringp = tmp;
          e = strsep(&stringp, "|");
          while (e) {
             make_filename(buf, sizeof(buf), filename, preflang, e);
             if ((len = file_exists(buf))) {
                found = i;
                break;
             }
             make_filename(buf, sizeof(buf), filename, NULL, e);
             if ((len = file_exists(buf))) {
                found = i;
                break;
             }
             e = strsep(&stringp, "|");
          }
       }
       if (found)
          break;
    }
    if (found) {
       fd = open(buf, O_RDONLY);
       if (fd > -1) {
          if (!found->identify || found->identify(fd)) {
             /* Reset file pointer */
             lseek(fd, 0, SEEK_SET);
             f = found->read_image(fd, len);
          } else
             ast_log(LOG_WARNING, "%s does not appear to be a %s file\n", buf, found->name);
          close(fd);
       } else
          ast_log(LOG_WARNING, "Unable to open '%s': %s\n", buf, strerror(errno));
    } else
       ast_log(LOG_WARNING, "Image file '%s' not found\n", filename);
    AST_RWLIST_UNLOCK(&imagers);
    return f;
 }
ast_send_image()
int ast_send_image (struct ast_channel * chan, const char * filename)
Sends an image.
Parameters
chan channel to send image on
filename filename of image to send (minus extension) Sends an image on the given channel.
Return values
0 on success
-1 on error
Definition at line 158 of file image.c.
References ast_channel_language(), ast_channel_tech(), ast_frfree, ast_read_image(), NULL, and ast_channel_tech::send_image.
Referenced by handle_sendimage(), and sendimage_exec().
 {
    struct ast_frame *f;
    int res = -1;
    if (ast_channel_tech(chan)->send_image) {
       f = ast_read_image(filename, ast_channel_language(chan), NULL);
       if (f) {
          res = ast_channel_tech(chan)->send_image(chan, f);
          ast_frfree(f);
       }
    }
    return res;
 }
ast_supports_images()
int ast_supports_images (struct ast_channel * chan)
Check for image support on a channel.
Parameters
chan channel to check Checks the channel to see if it supports the transmission of images
Returns
non-zero if image transmission is supported
Definition at line 67 of file image.c.
References ast_channel_tech().
Referenced by sendimage_exec().
 {
    if (!chan || !ast_channel_tech(chan))
       return 0;
    if (!ast_channel_tech(chan)->send_image)
       return 0;
    return 1;
 }
file_exists()
static int file_exists (char * filename) static
Definition at line 76 of file image.c.
Referenced by ast_read_image().
 {
    int res;
    struct stat st;
    res = stat(filename, &st);
    if (!res)
       return st.st_size;
    return 0;
 }
handle_core_show_image_formats()
static char* handle_core_show_image_formats (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) static
Definition at line 172 of file image.c.
References ast_cli_args::argc, ast_cli(), ast_format_get_name(), AST_RWLIST_RDLOCK, AST_RWLIST_TRAVERSE, AST_RWLIST_UNLOCK, CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::command, ast_imager::desc, ast_imager::exts, ast_cli_args::fd, ast_imager::format, FORMAT, FORMAT2, ast_imager::name, NULL, and ast_cli_entry::usage.
 {
 #define FORMAT "%10s %10s %50s %10s\n"
 #define FORMAT2 "%10s %10s %50s %10s\n"
    struct ast_imager *i;
    int count_fmt = 0;
    switch (cmd) {
    case CLI_INIT:
       e->command = "core show image formats";
       e->usage =
          "Usage: core show image formats\n"
          "       Displays currently registered image formats (if any).\n";
       return NULL;
    case CLI_GENERATE:
       return NULL;
    }
    if (a->argc != 4)
       return CLI_SHOWUSAGE;
    ast_cli(a->fd, FORMAT, "Name", "Extensions", "Description", "Format");
    ast_cli(a->fd, FORMAT, "----", "----------", "-----------", "------");
    AST_RWLIST_RDLOCK(&imagers);
    AST_RWLIST_TRAVERSE(&imagers, i, list) {
       ast_cli(a->fd, FORMAT2, i->name, i->exts, i->desc, ast_format_get_name(i->format));
       count_fmt++;
    }
    AST_RWLIST_UNLOCK(&imagers);
    ast_cli(a->fd, "\n%d image format%s registered.\n", count_fmt, count_fmt == 1 ? "" : "s");
    return CLI_SUCCESS;
 }
image_shutdown()
static void image_shutdown (void) static
Definition at line 207 of file image.c.
References ARRAY_LEN, and ast_cli_unregister_multiple().
Referenced by ast_image_init().
 {
    ast_cli_unregister_multiple(cli_image, ARRAY_LEN(cli_image));
 }
make_filename()
static void make_filename (char * buf, int len, const char * filename, const char * preflang, char * ext) static
Definition at line 86 of file image.c.
References ast_config_AST_DATA_DIR, and ast_strlen_zero.
Referenced by ast_read_image().
 {
    if (filename[0] == '/') {
       if (!ast_strlen_zero(preflang))
          snprintf(buf, len, "%s-%s.%s", filename, preflang, ext);
       else
          snprintf(buf, len, "%s.%s", filename, ext);
    } else {
       if (!ast_strlen_zero(preflang))
          snprintf(buf, len, "%s/%s/%s-%s.%s", ast_config_AST_DATA_DIR, "images", filename, preflang, ext);
       else
          snprintf(buf, len, "%s/%s/%s.%s", ast_config_AST_DATA_DIR, "images", filename, ext);
    }
 }
Variable Documentation
cli_image
struct ast_cli_entry cli_image[] static
Initial value:
= {
   { .handler =  handle_core_show_image_formats , .summary =  "Displays image formats" ,}
}
Definition at line 203 of file image.c.
imagers
struct imagers imagers = { .first = NULL, .last = NULL, .lock = { PTHREAD_RWLOCK_INITIALIZER , NULL, {1, 0} } , } static