Asterisk - The Open Source Telephony Project: manager_channels.c File Reference
manager_channels.c File Reference
The Asterisk Management Interface - AMI (channel event handling)
#include "asterisk.h"
#include "asterisk/callerid.h"
#include "asterisk/channel.h"
#include "asterisk/manager.h"
#include "asterisk/stasis_message_router.h"
#include "asterisk/pbx.h"
#include "asterisk/stasis_channels.h"
Typedefs
typedef struct ast_manager_event_blob *(* channel_snapshot_monitor) (struct ast_channel_snapshot *old_snapshot, struct ast_channel_snapshot *new_snapshot)
Typedef for callbacks that get called on channel snapshot updates.
Functions
struct ast_str * ast_manager_build_channel_state_string (const struct ast_channel_snapshot *snapshot)
Generate the AMI message body from a channel snapshot.
struct ast_str * ast_manager_build_channel_state_string_prefix (const struct ast_channel_snapshot *snapshot, const char *prefix)
Generate the AMI message body from a channel snapshot.
static void channel_chanspy_start_cb (void *data, struct stasis_subscription *sub, struct stasis_message *message)
static void channel_chanspy_stop_cb (void *data, struct stasis_subscription *sub, struct stasis_message *message)
static void channel_dial_cb (void *data, struct stasis_subscription *sub, struct stasis_message *message)
Callback processing messages for channel dialing.
static void channel_dtmf_begin_cb (void *data, struct stasis_subscription *sub, struct stasis_message *message)
static void channel_dtmf_end_cb (void *data, struct stasis_subscription *sub, struct stasis_message *message)
static void channel_fax_cb (void *data, struct stasis_subscription *sub, struct stasis_message *message)
static void channel_flash_cb (void *data, struct stasis_subscription *sub, struct stasis_message *message)
static void channel_hangup_handler_cb (void *data, struct stasis_subscription *sub, struct stasis_message *message)
static void channel_hangup_request_cb (void *data, struct stasis_subscription *sub, struct stasis_message *message)
static void channel_hold_cb (void *data, struct stasis_subscription *sub, struct stasis_message *message)
static void channel_mixmonitor_mute_cb (void *data, struct stasis_subscription *sub, struct stasis_message *message)
static void channel_mixmonitor_start_cb (void *data, struct stasis_subscription *sub, struct stasis_message *message)
static void channel_mixmonitor_stop_cb (void *data, struct stasis_subscription *sub, struct stasis_message *message)
static void channel_moh_start_cb (void *data, struct stasis_subscription *sub, struct stasis_message *message)
static void channel_moh_stop_cb (void *data, struct stasis_subscription *sub, struct stasis_message *message)
static void channel_monitor_start_cb (void *data, struct stasis_subscription *sub, struct stasis_message *message)
static void channel_monitor_stop_cb (void *data, struct stasis_subscription *sub, struct stasis_message *message)
static struct ast_manager_event_blob * channel_new_accountcode (struct ast_channel_snapshot *old_snapshot, struct ast_channel_snapshot *new_snapshot)
static struct ast_manager_event_blob * channel_new_callerid (struct ast_channel_snapshot *old_snapshot, struct ast_channel_snapshot *new_snapshot)
static struct ast_manager_event_blob * channel_new_connected_line (struct ast_channel_snapshot *old_snapshot, struct ast_channel_snapshot *new_snapshot)
static struct ast_manager_event_blob * channel_newexten (struct ast_channel_snapshot *old_snapshot, struct ast_channel_snapshot *new_snapshot)
static void channel_snapshot_update (void *data, struct stasis_subscription *sub, struct stasis_message *message)
static struct ast_manager_event_blob * channel_state_change (struct ast_channel_snapshot *old_snapshot, struct ast_channel_snapshot *new_snapshot)
Handle channel state changes.
static void channel_unhold_cb (void *data, struct stasis_subscription *sub, struct stasis_message *message)
static int dial_status_end (const char *dialstatus)
int manager_channels_init (void)
Initialize support for AMI channel events.
static void manager_channels_shutdown (void)
static void publish_basic_channel_event (const char *event, int class, struct ast_channel_snapshot *snapshot)
Variables
channel_snapshot_monitor channel_monitors []
static struct stasis_forward * topic_forwarder
The Stasis Message Bus API subscription returned by the forwarding of the channel topic to the manager topic.
Detailed Description
The Asterisk Management Interface - AMI (channel event handling)
Author
David M. Lee, II dlee@.nosp@m.digi.nosp@m.um.co.nosp@m.m
AMI generated many per-channel and global-channel events by converting Stasis messages to AMI events. It makes sense to simply put them into a single file.
Definition in file manager_channels.c.
Typedef Documentation
channel_snapshot_monitor
typedef struct ast_manager_event_blob*(* channel_snapshot_monitor) (struct ast_channel_snapshot *old_snapshot, struct ast_channel_snapshot *new_snapshot)
Typedef for callbacks that get called on channel snapshot updates.
Definition at line 568 of file manager_channels.c.
Function Documentation
ast_manager_build_channel_state_string()
struct ast_str* ast_manager_build_channel_state_string (const struct ast_channel_snapshot * snapshot)
Generate the AMI message body from a channel snapshot.
Since
12
Parameters
snapshot the channel snapshot for which to generate an AMI message body
Return values
NULL on error
ast_str* on success (must be ast_freed by caller)
Definition at line 561 of file manager_channels.c.
References ast_manager_build_channel_state_string_prefix().
Referenced by action_agents(), action_confbridgelist_item(), agent_login_to_ami(), agent_logoff_to_ami(), agi_channel_to_ami(), aoc_to_ami(), call_pickup_to_ami(), channel_dial_cb(), channel_dtmf_begin_cb(), channel_dtmf_end_cb(), channel_enter_cb(), channel_fax_cb(), channel_flash_cb(), channel_hangup_handler_cb(), channel_hangup_request_cb(), channel_hold_cb(), channel_leave_cb(), channel_mixmonitor_mute_cb(), channel_moh_start_cb(), channel_snapshot_update(), channel_unhold_cb(), confbridge_publish_manager_event(), dahdichannel_to_ami(), generate_status(), meetme_stasis_cb(), mwi_app_event_cb(), mwi_update_cb(), publish_basic_channel_event(), queue_channel_to_ami(), queue_multi_channel_to_ami(), rtcp_report_to_ami(), send_bridge_info_item_cb(), session_timeout_to_ami(), talking_start_to_ami(), talking_stop_to_ami(), and varset_to_ami().
 {
    return ast_manager_build_channel_state_string_prefix(snapshot, "");
 }
ast_manager_build_channel_state_string_prefix()
struct ast_str* ast_manager_build_channel_state_string_prefix (const struct ast_channel_snapshot * snapshot, const char * prefix)
Generate the AMI message body from a channel snapshot.
Since
12
Parameters
snapshot the channel snapshot for which to generate an AMI message body
prefix What to prepend to the channel fields
Return values
NULL on error
ast_str* on success (must be ast_freed by caller)
Definition at line 487 of file manager_channels.c.
References ast_channel_snapshot_base::accountcode, AST_CHAN_TP_INTERNAL, ast_escape_c_alloc(), ast_free, AST_LIST_TRAVERSE, ast_state2str(), ast_str_append(), ast_str_create, ast_str_set(), ast_channel_snapshot::base, ast_channel_snapshot::caller, ast_channel_snapshot::connected, ast_channel_snapshot_dialplan::context, ast_channel_snapshot::dialplan, ast_var_t::entries, ast_channel_snapshot_dialplan::exten, ast_channel_snapshot_base::language, ast_channel_snapshot_peer::linkedid, ast_channel_snapshot::manager_vars, ast_var_t::name, ast_channel_snapshot_caller::name, ast_channel_snapshot_connected::name, ast_channel_snapshot_base::name, NULL, ast_channel_snapshot_caller::number, ast_channel_snapshot_connected::number, out, ast_channel_snapshot::peer, ast_channel_snapshot_dialplan::priority, S_OR, ast_channel_snapshot::state, ast_channel_snapshot_base::tech_properties, ast_channel_snapshot_base::uniqueid, ast_var_t::value, and var.
Referenced by action_coreshowchannels(), ast_manager_build_channel_state_string(), attended_transfer_to_ami(), blind_transfer_to_ami(), call_pickup_to_ami(), channel_chanspy_start_cb(), channel_chanspy_stop_cb(), channel_dial_cb(), local_message_to_ami(), manager_build_parked_call_string(), multi_object_blob_to_ami(), and queue_multi_channel_to_ami().
 {
    struct ast_str *out;
    char *caller_name;
    char *connected_name;
    int res;
    if (snapshot->base->tech_properties & AST_CHAN_TP_INTERNAL) {
       return NULL;
    }
    out = ast_str_create(1024);
    if (!out) {
       return NULL;
    }
    caller_name = ast_escape_c_alloc(snapshot->caller->name);
    connected_name = ast_escape_c_alloc(snapshot->connected->name);
    res = ast_str_set(&out, 0,
       "%sChannel: %s\r\n"
       "%sChannelState: %u\r\n"
       "%sChannelStateDesc: %s\r\n"
       "%sCallerIDNum: %s\r\n"
       "%sCallerIDName: %s\r\n"
       "%sConnectedLineNum: %s\r\n"
       "%sConnectedLineName: %s\r\n"
       "%sLanguage: %s\r\n"
       "%sAccountCode: %s\r\n"
       "%sContext: %s\r\n"
       "%sExten: %s\r\n"
       "%sPriority: %d\r\n"
       "%sUniqueid: %s\r\n"
       "%sLinkedid: %s\r\n",
       prefix, snapshot->base->name,
       prefix, snapshot->state,
       prefix, ast_state2str(snapshot->state),
       prefix, S_OR(snapshot->caller->number, "<unknown>"),
       prefix, S_OR(caller_name, "<unknown>"),
       prefix, S_OR(snapshot->connected->number, "<unknown>"),
       prefix, S_OR(connected_name, "<unknown>"),
       prefix, snapshot->base->language,
       prefix, snapshot->base->accountcode,
       prefix, snapshot->dialplan->context,
       prefix, snapshot->dialplan->exten,
       prefix, snapshot->dialplan->priority,
       prefix, snapshot->base->uniqueid,
       prefix, snapshot->peer->linkedid);
    ast_free(caller_name);
    ast_free(connected_name);
    if (!res) {
       ast_free(out);
       return NULL;
    }
    if (snapshot->manager_vars) {
       struct ast_var_t *var;
       char *val;
       AST_LIST_TRAVERSE(snapshot->manager_vars, var, entries) {
          val = ast_escape_c_alloc(var->value);
          ast_str_append(&out, 0, "%sChanVariable: %s=%s\r\n",
                    prefix,
                    var->name, S_OR(val, ""));
          ast_free(val);
       }
    }
    return out;
 }
channel_chanspy_start_cb()
static void channel_chanspy_start_cb (void * data, struct stasis_subscription * sub, struct stasis_message * message) static
Definition at line 842 of file manager_channels.c.
References ast_free, ast_log, AST_LOG_WARNING, ast_manager_build_channel_state_string_prefix(), ast_multi_channel_blob_get_channel(), ast_str_buffer(), EVENT_FLAG_CALL, manager_event, NULL, RAII_VAR, and stasis_message_data().
Referenced by manager_channels_init().
 {
    RAII_VAR(struct ast_str *, spyer_channel_string, NULL, ast_free);
    RAII_VAR(struct ast_str *, spyee_channel_string, NULL, ast_free);
    struct ast_channel_snapshot *spyer;
    struct ast_channel_snapshot *spyee;
    struct ast_multi_channel_blob *payload = stasis_message_data(message);
    spyer = ast_multi_channel_blob_get_channel(payload, "spyer_channel");
    if (!spyer) {
       ast_log(AST_LOG_WARNING, "Received ChanSpy Start event with no spyer channel!\n");
       return;
    }
    spyee = ast_multi_channel_blob_get_channel(payload, "spyee_channel");
    if (!spyee) {
       ast_log(AST_LOG_WARNING, "Received ChanSpy Start event with no spyee channel!\n");
       return;
    }
    spyer_channel_string = ast_manager_build_channel_state_string_prefix(spyer, "Spyer");
    if (!spyer_channel_string) {
       return;
    }
    spyee_channel_string = ast_manager_build_channel_state_string_prefix(spyee, "Spyee");
    if (!spyee_channel_string) {
       return;
    }
    manager_event(EVENT_FLAG_CALL, "ChanSpyStart",
             "%s%s",
             ast_str_buffer(spyer_channel_string),
             ast_str_buffer(spyee_channel_string));
 }
channel_chanspy_stop_cb()
static void channel_chanspy_stop_cb (void * data, struct stasis_subscription * sub, struct stasis_message * message) static
Definition at line 807 of file manager_channels.c.
References ast_free, ast_log, AST_LOG_WARNING, ast_manager_build_channel_state_string_prefix(), ast_multi_channel_blob_get_channel(), ast_str_buffer(), EVENT_FLAG_CALL, manager_event, NULL, RAII_VAR, and stasis_message_data().
Referenced by manager_channels_init().
 {
    RAII_VAR(struct ast_str *, spyer_channel_string, NULL, ast_free);
    RAII_VAR(struct ast_str *, spyee_channel_string, NULL, ast_free);
    struct ast_channel_snapshot *spyer;
    struct ast_channel_snapshot *spyee;
    const char *spyee_info = "";
    struct ast_multi_channel_blob *payload = stasis_message_data(message);
    spyer = ast_multi_channel_blob_get_channel(payload, "spyer_channel");
    if (!spyer) {
       ast_log(AST_LOG_WARNING, "Received ChanSpy Stop event with no spyer channel!\n");
       return;
    }
    spyer_channel_string = ast_manager_build_channel_state_string_prefix(spyer, "Spyer");
    if (!spyer_channel_string) {
       return;
    }
    spyee = ast_multi_channel_blob_get_channel(payload, "spyee_channel");
    if (spyee) {
       spyee_channel_string = ast_manager_build_channel_state_string_prefix(spyee, "Spyee");
       if (spyee_channel_string) {
          spyee_info = ast_str_buffer(spyee_channel_string);
       }
    }
    manager_event(EVENT_FLAG_CALL, "ChanSpyStop",
             "%s%s",
             ast_str_buffer(spyer_channel_string),
             spyee_info);
 }
channel_dial_cb()
static void channel_dial_cb (void * data, struct stasis_subscription * sub, struct stasis_message * message) static
Callback processing messages for channel dialing.
Definition at line 1194 of file manager_channels.c.
References ast_assert, ast_free, ast_json_object_get(), ast_json_string_get(), ast_manager_build_channel_state_string(), ast_manager_build_channel_state_string_prefix(), ast_multi_channel_blob_get_channel(), ast_multi_channel_blob_get_json(), ast_str_buffer(), ast_strlen_zero, ast_channel_snapshot::caller, dial_status_end(), EVENT_FLAG_CALL, manager_event, NULL, ast_channel_snapshot::peer, RAII_VAR, S_OR, and stasis_message_data().
Referenced by manager_channels_init().
 {
    struct ast_multi_channel_blob *obj = stasis_message_data(message);
    const char *dialstatus;
    const char *dialstring;
    const char *forward;
    struct ast_channel_snapshot *caller;
    struct ast_channel_snapshot *peer;
    RAII_VAR(struct ast_str *, caller_event_string, NULL, ast_free);
    RAII_VAR(struct ast_str *, peer_event_string, NULL, ast_free);
    caller = ast_multi_channel_blob_get_channel(obj, "caller");
    peer = ast_multi_channel_blob_get_channel(obj, "peer");
    /* Peer is required - otherwise, who are we dialing? */
    ast_assert(peer != NULL);
    peer_event_string = ast_manager_build_channel_state_string_prefix(peer, "Dest");
    if (!peer_event_string) {
       return;
    }
    if (caller && !(caller_event_string = ast_manager_build_channel_state_string(caller))) {
       return;
    }
    dialstatus = ast_json_string_get(ast_json_object_get(ast_multi_channel_blob_get_json(obj), "dialstatus"));
    dialstring = ast_json_string_get(ast_json_object_get(ast_multi_channel_blob_get_json(obj), "dialstring"));
    forward = ast_json_string_get(ast_json_object_get(ast_multi_channel_blob_get_json(obj), "forward"));
    if (ast_strlen_zero(dialstatus)) {
       manager_event(EVENT_FLAG_CALL, "DialBegin",
             "%s"
             "%s"
             "DialString: %s\r\n",
             caller_event_string ? ast_str_buffer(caller_event_string) : "",
             ast_str_buffer(peer_event_string),
             S_OR(dialstring, "unknown"));
    } else {
       int forwarded = !ast_strlen_zero(forward);
       manager_event(EVENT_FLAG_CALL, dial_status_end(dialstatus) ? "DialEnd" : "DialState",
             "%s"
             "%s"
             "%s%s%s"
             "DialStatus: %s\r\n",
             caller_event_string ? ast_str_buffer(caller_event_string) : "",
             ast_str_buffer(peer_event_string),
             forwarded ? "Forward: " : "", S_OR(forward, ""), forwarded ? "\r\n" : "",
             S_OR(dialstatus, "unknown"));
    }
 }
channel_dtmf_begin_cb()
static void channel_dtmf_begin_cb (void * data, struct stasis_subscription * sub, struct stasis_message * message) static
Definition at line 877 of file manager_channels.c.
References ast_free, ast_json_object_get(), ast_json_string_get(), ast_manager_build_channel_state_string(), ast_str_buffer(), ast_channel_blob::blob, digit, EVENT_FLAG_DTMF, manager_event, NULL, RAII_VAR, ast_channel_blob::snapshot, and stasis_message_data().
Referenced by manager_channels_init().
 {
    struct ast_channel_blob *obj = stasis_message_data(message);
    RAII_VAR(struct ast_str *, channel_event_string, NULL, ast_free);
    const char *digit =
       ast_json_string_get(ast_json_object_get(obj->blob, "digit"));
    const char *direction =
       ast_json_string_get(ast_json_object_get(obj->blob, "direction"));
    channel_event_string = ast_manager_build_channel_state_string(obj->snapshot);
    if (!channel_event_string) {
       return;
    }
    /*** DOCUMENTATION
       <managerEventInstance>
          <synopsis>Raised when a DTMF digit has started on a channel.</synopsis>
             <syntax>
                <channel_snapshot/>
                <parameter name="Digit">
                   <para>DTMF digit received or transmitted (0-9, A-E, # or *</para>
                </parameter>
                <parameter name="Direction">
                   <enumlist>
                      <enum name="Received"/>
                      <enum name="Sent"/>
                   </enumlist>
                </parameter>
             </syntax>
             <see-also>
                <ref type="managerEvent">DTMFEnd</ref>
             </see-also>
       </managerEventInstance>
    ***/
    manager_event(EVENT_FLAG_DTMF, "DTMFBegin",
       "%s"
       "Digit: %s\r\n"
       "Direction: %s\r\n",
       ast_str_buffer(channel_event_string),
       digit, direction);
 }
channel_dtmf_end_cb()
static void channel_dtmf_end_cb (void * data, struct stasis_subscription * sub, struct stasis_message * message) static
Definition at line 921 of file manager_channels.c.
References ast_free, ast_json_integer_get(), ast_json_object_get(), ast_json_string_get(), ast_manager_build_channel_state_string(), ast_str_buffer(), ast_channel_blob::blob, digit, EVENT_FLAG_DTMF, manager_event, NULL, RAII_VAR, ast_channel_blob::snapshot, and stasis_message_data().
Referenced by manager_channels_init().
 {
    struct ast_channel_blob *obj = stasis_message_data(message);
    RAII_VAR(struct ast_str *, channel_event_string, NULL, ast_free);
    const char *digit =
       ast_json_string_get(ast_json_object_get(obj->blob, "digit"));
    const char *direction =
       ast_json_string_get(ast_json_object_get(obj->blob, "direction"));
    long duration_ms =
       ast_json_integer_get(ast_json_object_get(obj->blob, "duration_ms"));
    channel_event_string = ast_manager_build_channel_state_string(obj->snapshot);
    if (!channel_event_string) {
       return;
    }
    /*** DOCUMENTATION
       <managerEventInstance>
          <synopsis>Raised when a DTMF digit has ended on a channel.</synopsis>
             <syntax>
                <channel_snapshot/>
                <parameter name="Digit">
                   <para>DTMF digit received or transmitted (0-9, A-E, # or *</para>
                </parameter>
                <parameter name="DurationMs">
                   <para>Duration (in milliseconds) DTMF was sent/received</para>
                </parameter>
                <parameter name="Direction">
                   <enumlist>
                      <enum name="Received"/>
                      <enum name="Sent"/>
                   </enumlist>
                </parameter>
             </syntax>
             <see-also>
                <ref type="managerEvent">DTMFBegin</ref>
             </see-also>
       </managerEventInstance>
    ***/
    manager_event(EVENT_FLAG_DTMF, "DTMFEnd",
       "%s"
       "Digit: %s\r\n"
       "DurationMs: %ld\r\n"
       "Direction: %s\r\n",
       ast_str_buffer(channel_event_string),
       digit, duration_ms, direction);
 }
channel_fax_cb()
static void channel_fax_cb (void * data, struct stasis_subscription * sub, struct stasis_message * message) static
Definition at line 1020 of file manager_channels.c.
References ast_free, ast_json_array_get(), ast_json_array_size(), ast_json_object_get(), ast_json_string_get(), ast_manager_build_channel_state_string(), ast_str_append(), ast_str_buffer(), ast_str_create, ast_channel_blob::blob, EVENT_FLAG_CALL, manager_event, NULL, RAII_VAR, ast_channel_blob::snapshot, stasis_message_data(), status, and type.
Referenced by manager_channels_init().
 {
    RAII_VAR(struct ast_str *, channel_event_string, NULL, ast_free);
    RAII_VAR(struct ast_str *, event_buffer, ast_str_create(256), ast_free);
    struct ast_channel_blob *payload = stasis_message_data(message);
    const char *type = ast_json_string_get(ast_json_object_get(payload->blob, "type"));
    struct ast_json *operation = ast_json_object_get(payload->blob, "operation");
    struct ast_json *status = ast_json_object_get(payload->blob, "status");
    struct ast_json *local_station_id = ast_json_object_get(payload->blob, "local_station_id");
    struct ast_json *remote_station_id = ast_json_object_get(payload->blob, "remote_station_id");
    struct ast_json *fax_pages = ast_json_object_get(payload->blob, "fax_pages");
    struct ast_json *fax_resolution = ast_json_object_get(payload->blob, "fax_resolution");
    struct ast_json *fax_bitrate = ast_json_object_get(payload->blob, "fax_bitrate");
    struct ast_json *filenames = ast_json_object_get(payload->blob, "filenames");
    const char *event;
    size_t array_len;
    size_t i;
    if (!event_buffer) {
       return;
    }
    channel_event_string = ast_manager_build_channel_state_string(payload->snapshot);
    if (!channel_event_string) {
       return;
    }
    if (!strcmp(type, "status")) {
       event = "FAXStatus";
    } else if (!strcmp(type, "receive")) {
       event = "ReceiveFAX";
    } else if (!strcmp(type, "send")) {
       event = "SendFAX";
    } else {
       return;
    }
    if (operation) {
       ast_str_append(&event_buffer, 0, "Operation: %s\r\n", ast_json_string_get(operation));
    }
    if (status) {
       ast_str_append(&event_buffer, 0, "Status: %s\r\n", ast_json_string_get(status));
    }
    if (local_station_id) {
       ast_str_append(&event_buffer, 0, "LocalStationID: %s\r\n", ast_json_string_get(local_station_id));
    }
    if (remote_station_id) {
       ast_str_append(&event_buffer, 0, "RemoteStationID: %s\r\n", ast_json_string_get(remote_station_id));
    }
    if (fax_pages) {
       ast_str_append(&event_buffer, 0, "PagesTransferred: %s\r\n", ast_json_string_get(fax_pages));
    }
    if (fax_resolution) {
       ast_str_append(&event_buffer, 0, "Resolution: %s\r\n", ast_json_string_get(fax_resolution));
    }
    if (fax_bitrate) {
       ast_str_append(&event_buffer, 0, "TransferRate: %s\r\n", ast_json_string_get(fax_bitrate));
    }
    if (filenames) {
       array_len = ast_json_array_size(filenames);
       for (i = 0; i < array_len; i++) {
          ast_str_append(&event_buffer, 0, "FileName: %s\r\n", ast_json_string_get(ast_json_array_get(filenames, i)));
       }
    }
    manager_event(EVENT_FLAG_CALL, event,
       "%s"
       "%s",
       ast_str_buffer(channel_event_string),
       ast_str_buffer(event_buffer));
 }
channel_flash_cb()
static void channel_flash_cb (void * data, struct stasis_subscription * sub, struct stasis_message * message) static
Definition at line 971 of file manager_channels.c.
References ast_free, ast_manager_build_channel_state_string(), ast_str_buffer(), EVENT_FLAG_CALL, manager_event, ast_channel_blob::snapshot, and stasis_message_data().
Referenced by manager_channels_init().
 {
    struct ast_channel_blob *obj = stasis_message_data(message);
    struct ast_str *channel_event_string;
    channel_event_string = ast_manager_build_channel_state_string(obj->snapshot);
    if (!channel_event_string) {
       return;
    }
    manager_event(EVENT_FLAG_CALL, "Flash",
       "%s",
       ast_str_buffer(channel_event_string));
    ast_free(channel_event_string);
 }
channel_hangup_handler_cb()
static void channel_hangup_handler_cb (void * data, struct stasis_subscription * sub, struct stasis_message * message) static
Definition at line 989 of file manager_channels.c.
References ast_free, ast_json_object_get(), ast_json_string_get(), ast_manager_build_channel_state_string(), ast_str_buffer(), ast_channel_blob::blob, EVENT_FLAG_DIALPLAN, handler(), manager_event, NULL, RAII_VAR, ast_channel_blob::snapshot, and stasis_message_data().
Referenced by manager_channels_init().
 {
    RAII_VAR(struct ast_str *, channel_event_string, NULL, ast_free);
    struct ast_channel_blob *payload = stasis_message_data(message);
    const char *action = ast_json_string_get(ast_json_object_get(payload->blob, "type"));
    const char *handler = ast_json_string_get(ast_json_object_get(payload->blob, "handler"));
    const char *event;
    channel_event_string = ast_manager_build_channel_state_string(payload->snapshot);
    if (!channel_event_string) {
       return;
    }
    if (!strcmp(action, "run")) {
       event = "HangupHandlerRun";
    } else if (!strcmp(action, "pop")) {
       event = "HangupHandlerPop";
    } else if (!strcmp(action, "push")) {
       event = "HangupHandlerPush";
    } else {
       return;
    }
    manager_event(EVENT_FLAG_DIALPLAN, event,
       "%s"
       "Handler: %s\r\n",
       ast_str_buffer(channel_event_string),
       handler);
 }
channel_hangup_request_cb()
static void channel_hangup_request_cb (void * data, struct stasis_subscription * sub, struct stasis_message * message) static
Definition at line 759 of file manager_channels.c.
References ast_free, ast_json_integer_get(), ast_json_is_true(), ast_json_object_get(), ast_manager_build_channel_state_string(), ast_str_append(), ast_str_buffer(), ast_str_create, ast_channel_blob::blob, EVENT_FLAG_CALL, manager_event, ast_channel_blob::snapshot, and stasis_message_data().
Referenced by manager_channels_init().
 {
    struct ast_channel_blob *obj = stasis_message_data(message);
    struct ast_str *extra;
    struct ast_str *channel_event_string;
    struct ast_json *cause;
    int is_soft;
    char *manager_event = "HangupRequest";
    if (!obj->snapshot) {
       /* No snapshot?  Likely an earlier allocation failure creating it. */
       return;
    }
    extra = ast_str_create(20);
    if (!extra) {
       return;
    }
    channel_event_string = ast_manager_build_channel_state_string(obj->snapshot);
    if (!channel_event_string) {
       ast_free(extra);
       return;
    }
    cause = ast_json_object_get(obj->blob, "cause");
    if (cause) {
       ast_str_append(&extra, 0,
          "Cause: %jd\r\n",
          ast_json_integer_get(cause));
    }
    is_soft = ast_json_is_true(ast_json_object_get(obj->blob, "soft"));
    if (is_soft) {
       manager_event = "SoftHangupRequest";
    }
    manager_event(EVENT_FLAG_CALL, manager_event,
       "%s%s",
       ast_str_buffer(channel_event_string),
       ast_str_buffer(extra));
    ast_free(channel_event_string);
    ast_free(extra);
 }
channel_hold_cb()
static void channel_hold_cb (void * data, struct stasis_subscription * sub, struct stasis_message * message) static
Definition at line 1247 of file manager_channels.c.
References ast_free, ast_json_object_get(), ast_json_string_get(), ast_manager_build_channel_state_string(), ast_str_buffer(), ast_str_create, ast_str_set(), ast_strlen_zero, ast_channel_blob::blob, EVENT_FLAG_CALL, manager_event, musicclass, ast_channel_blob::snapshot, and stasis_message_data().
Referenced by manager_channels_init().
 {
    struct ast_channel_blob *obj = stasis_message_data(message);
    struct ast_str *musicclass_string = ast_str_create(32);
    struct ast_str *channel_event_string;
    if (!musicclass_string) {
       return;
    }
    channel_event_string = ast_manager_build_channel_state_string(obj->snapshot);
    if (!channel_event_string) {
       ast_free(musicclass_string);
       return;
    }
    if (obj->blob) {
       const char *musicclass;
       musicclass = ast_json_string_get(ast_json_object_get(obj->blob, "musicclass"));
       if (!ast_strlen_zero(musicclass)) {
          ast_str_set(&musicclass_string, 0, "MusicClass: %s\r\n", musicclass);
       }
    }
    manager_event(EVENT_FLAG_CALL, "Hold",
       "%s"
       "%s",
       ast_str_buffer(channel_event_string),
       ast_str_buffer(musicclass_string));
    ast_free(musicclass_string);
    ast_free(channel_event_string);
 }
channel_mixmonitor_mute_cb()
static void channel_mixmonitor_mute_cb (void * data, struct stasis_subscription * sub, struct stasis_message * message) static
Definition at line 1153 of file manager_channels.c.
References ast_free, ast_json_is_true(), ast_json_object_get(), ast_json_string_get(), ast_manager_build_channel_state_string(), ast_str_append(), ast_str_buffer(), ast_str_create, ast_channel_blob::blob, EVENT_FLAG_CALL, manager_event, NULL, RAII_VAR, ast_channel_blob::snapshot, and stasis_message_data().
Referenced by manager_channels_init().
 {
    RAII_VAR(struct ast_str *, channel_event_string, NULL, ast_free);
    RAII_VAR(struct ast_str *, event_buffer, ast_str_create(64), ast_free);
    struct ast_channel_blob *payload = stasis_message_data(message);
    struct ast_json *direction = ast_json_object_get(payload->blob, "direction");
    const int state = ast_json_is_true(ast_json_object_get(payload->blob, "state"));
    if (!event_buffer) {
       return;
    }
    channel_event_string = ast_manager_build_channel_state_string(payload->snapshot);
    if (!channel_event_string) {
       return;
    }
    if (direction) {
       ast_str_append(&event_buffer, 0, "Direction: %s\r\n", ast_json_string_get(direction));
    }
    ast_str_append(&event_buffer, 0, "State: %s\r\n", state ? "1" : "0");
    manager_event(EVENT_FLAG_CALL, "MixMonitorMute",
       "%s"
       "%s",
       ast_str_buffer(channel_event_string),
       ast_str_buffer(event_buffer));
 }
channel_mixmonitor_start_cb()
static void channel_mixmonitor_start_cb (void * data, struct stasis_subscription * sub, struct stasis_message * message) static
Definition at line 1137 of file manager_channels.c.
References EVENT_FLAG_CALL, publish_basic_channel_event(), ast_channel_blob::snapshot, and stasis_message_data().
Referenced by manager_channels_init().
 {
    struct ast_channel_blob *payload = stasis_message_data(message);
    publish_basic_channel_event("MixMonitorStart", EVENT_FLAG_CALL, payload->snapshot);
 }
channel_mixmonitor_stop_cb()
static void channel_mixmonitor_stop_cb (void * data, struct stasis_subscription * sub, struct stasis_message * message) static
Definition at line 1145 of file manager_channels.c.
References EVENT_FLAG_CALL, publish_basic_channel_event(), ast_channel_blob::snapshot, and stasis_message_data().
Referenced by manager_channels_init().
 {
    struct ast_channel_blob *payload = stasis_message_data(message);
    publish_basic_channel_event("MixMonitorStop", EVENT_FLAG_CALL, payload->snapshot);
 }
channel_moh_start_cb()
static void channel_moh_start_cb (void * data, struct stasis_subscription * sub, struct stasis_message * message) static
Definition at line 1093 of file manager_channels.c.
References ast_free, ast_json_object_get(), ast_json_string_get(), ast_manager_build_channel_state_string(), ast_str_buffer(), ast_channel_blob::blob, EVENT_FLAG_CALL, manager_event, NULL, RAII_VAR, ast_channel_blob::snapshot, and stasis_message_data().
Referenced by manager_channels_init().
 {
    struct ast_channel_blob *payload = stasis_message_data(message);
    struct ast_json *blob = payload->blob;
    RAII_VAR(struct ast_str *, channel_event_string, NULL, ast_free);
    channel_event_string = ast_manager_build_channel_state_string(payload->snapshot);
    if (!channel_event_string) {
       return;
    }
    manager_event(EVENT_FLAG_CALL, "MusicOnHoldStart",
       "%s"
       "Class: %s\r\n",
       ast_str_buffer(channel_event_string),
       ast_json_string_get(ast_json_object_get(blob, "class")));
 }
channel_moh_stop_cb()
static void channel_moh_stop_cb (void * data, struct stasis_subscription * sub, struct stasis_message * message) static
Definition at line 1113 of file manager_channels.c.
References EVENT_FLAG_CALL, publish_basic_channel_event(), ast_channel_blob::snapshot, and stasis_message_data().
Referenced by manager_channels_init().
 {
    struct ast_channel_blob *payload = stasis_message_data(message);
    publish_basic_channel_event("MusicOnHoldStop", EVENT_FLAG_CALL, payload->snapshot);
 }
channel_monitor_start_cb()
static void channel_monitor_start_cb (void * data, struct stasis_subscription * sub, struct stasis_message * message) static
Definition at line 1121 of file manager_channels.c.
References EVENT_FLAG_CALL, publish_basic_channel_event(), ast_channel_blob::snapshot, and stasis_message_data().
Referenced by manager_channels_init().
 {
    struct ast_channel_blob *payload = stasis_message_data(message);
    publish_basic_channel_event("MonitorStart", EVENT_FLAG_CALL, payload->snapshot);
 }
channel_monitor_stop_cb()
static void channel_monitor_stop_cb (void * data, struct stasis_subscription * sub, struct stasis_message * message) static
Definition at line 1129 of file manager_channels.c.
References EVENT_FLAG_CALL, publish_basic_channel_event(), ast_channel_blob::snapshot, and stasis_message_data().
Referenced by manager_channels_init().
 {
    struct ast_channel_blob *payload = stasis_message_data(message);
    publish_basic_channel_event("MonitorStop", EVENT_FLAG_CALL, payload->snapshot);
 }
channel_new_accountcode()
static struct ast_manager_event_blob* channel_new_accountcode (struct ast_channel_snapshot * old_snapshot, struct ast_channel_snapshot * new_snapshot) static
Definition at line 688 of file manager_channels.c.
References ast_channel_snapshot_base::accountcode, ast_manager_event_blob_create(), ast_channel_snapshot::base, EVENT_FLAG_CALL, and NULL.
 {
    if (!old_snapshot) {
       return NULL;
    }
    if (!strcmp(old_snapshot->base->accountcode, new_snapshot->base->accountcode)) {
       return NULL;
    }
    return ast_manager_event_blob_create(
       EVENT_FLAG_CALL, "NewAccountCode",
       "OldAccountCode: %s\r\n", old_snapshot->base->accountcode);
 }
channel_new_callerid()
static struct ast_manager_event_blob* channel_new_callerid (struct ast_channel_snapshot * old_snapshot, struct ast_channel_snapshot * new_snapshot) static
Definition at line 640 of file manager_channels.c.
References ast_channel_snapshot_caller_id_equal(), ast_describe_caller_presentation(), ast_escape_c_alloc(), ast_free, ast_manager_event_blob_create(), ast_channel_snapshot::caller, EVENT_FLAG_CALL, NULL, and ast_channel_snapshot_caller::pres.
 {
    struct ast_manager_event_blob *res;
    char *callerid;
    /* No NewCallerid event on first channel snapshot */
    if (!old_snapshot) {
       return NULL;
    }
    if (ast_channel_snapshot_caller_id_equal(old_snapshot, new_snapshot)) {
       return NULL;
    }
    if (!(callerid = ast_escape_c_alloc(
             ast_describe_caller_presentation(new_snapshot->caller->pres)))) {
       return NULL;
    }
    res = ast_manager_event_blob_create(
       EVENT_FLAG_CALL, "NewCallerid",
       "CID-CallingPres: %d (%s)\r\n",
       new_snapshot->caller->pres,
       callerid);
    ast_free(callerid);
    return res;
 }
channel_new_connected_line()
static struct ast_manager_event_blob* channel_new_connected_line (struct ast_channel_snapshot * old_snapshot, struct ast_channel_snapshot * new_snapshot) static
Definition at line 671 of file manager_channels.c.
References ast_channel_snapshot_connected_line_equal(), ast_manager_event_blob_create(), EVENT_FLAG_CALL, and NULL.
 {
    /* No NewConnectedLine event on first channel snapshot */
    if (!old_snapshot) {
       return NULL;
    }
    if (ast_channel_snapshot_connected_line_equal(old_snapshot, new_snapshot)) {
       return NULL;
    }
    return ast_manager_event_blob_create(
       EVENT_FLAG_CALL, "NewConnectedLine", "%s", "");
 }
channel_newexten()
static struct ast_manager_event_blob* channel_newexten (struct ast_channel_snapshot * old_snapshot, struct ast_channel_snapshot * new_snapshot) static
Definition at line 610 of file manager_channels.c.
References ast_channel_snapshot_dialplan::appl, ast_channel_snapshot_cep_equal(), AST_FLAG_DEAD, ast_manager_event_blob_create(), ast_strlen_zero, ast_test_flag, ast_channel_snapshot_dialplan::data, ast_channel_snapshot::dialplan, EVENT_FLAG_DIALPLAN, ast_channel_snapshot_dialplan::exten, ast_channel_snapshot::flags, and NULL.
 {
    /* Empty application is not valid for a Newexten event */
    if (ast_strlen_zero(new_snapshot->dialplan->appl)) {
       return NULL;
    }
    /* Ignore any updates if we're hungup */
    if (ast_test_flag(&new_snapshot->flags, AST_FLAG_DEAD)) {
       return NULL;
    }
    /* Ignore updates if the CEP is unchanged */
    if (old_snapshot && ast_channel_snapshot_cep_equal(old_snapshot, new_snapshot)) {
       return NULL;
    }
    /* DEPRECATED: Extension field deprecated in 12; remove in 14 */
    return ast_manager_event_blob_create(
       EVENT_FLAG_DIALPLAN, "Newexten",
       "Extension: %s\r\n"
       "Application: %s\r\n"
       "AppData: %s\r\n",
       new_snapshot->dialplan->exten,
       new_snapshot->dialplan->appl,
       new_snapshot->dialplan->data);
 }
channel_snapshot_update()
static void channel_snapshot_update (void * data, struct stasis_subscription * sub, struct stasis_message * message) static
Definition at line 713 of file manager_channels.c.
References ao2_cleanup, ARRAY_LEN, ast_free, ast_manager_build_channel_state_string(), ast_str_buffer(), channel_monitors, manager_event, ast_channel_snapshot_update::new_snapshot, NULL, ast_channel_snapshot_update::old_snapshot, RAII_VAR, stasis_message_data(), and update().
Referenced by manager_channels_init().
 {
    RAII_VAR(struct ast_str *, channel_event_string, NULL, ast_free);
    struct ast_channel_snapshot_update *update;
    size_t i;
    update = stasis_message_data(message);
    for (i = 0; i < ARRAY_LEN(channel_monitors); ++i) {
       RAII_VAR(struct ast_manager_event_blob *, ev, NULL, ao2_cleanup);
       ev = channel_monitors[i](update->old_snapshot, update->new_snapshot);
       if (!ev) {
          continue;
       }
       /* If we haven't already, build the channel event string */
       if (!channel_event_string) {
          channel_event_string =
             ast_manager_build_channel_state_string(update->new_snapshot);
          if (!channel_event_string) {
             return;
          }
       }
       manager_event(ev->event_flags, ev->manager_event, "%s%s",
          ast_str_buffer(channel_event_string),
          ev->extra_fields);
    }
 }
channel_state_change()
static struct ast_manager_event_blob* channel_state_change (struct ast_channel_snapshot * old_snapshot, struct ast_channel_snapshot * new_snapshot) static
Handle channel state changes.
Definition at line 573 of file manager_channels.c.
References ast_cause2str(), AST_FLAG_DEAD, ast_manager_event_blob_create(), ast_test_flag, ast_channel_snapshot_hangup::cause, EVENT_FLAG_CALL, ast_channel_snapshot::flags, ast_channel_snapshot::hangup, NO_EXTRA_FIELDS, NULL, and ast_channel_snapshot::state.
 {
    int is_hungup, was_hungup;
    /* The Newchannel, Newstate and Hangup events are closely related, in
     * in that they are mutually exclusive, basically different flavors
     * of a new channel state event.
     */
    if (!old_snapshot) {
       return ast_manager_event_blob_create(
          EVENT_FLAG_CALL, "Newchannel", NO_EXTRA_FIELDS);
    }
    was_hungup = ast_test_flag(&old_snapshot->flags, AST_FLAG_DEAD) ? 1 : 0;
    is_hungup = ast_test_flag(&new_snapshot->flags, AST_FLAG_DEAD) ? 1 : 0;
    if (!was_hungup && is_hungup) {
       return ast_manager_event_blob_create(
          EVENT_FLAG_CALL, "Hangup",
          "Cause: %d\r\n"
          "Cause-txt: %s\r\n",
          new_snapshot->hangup->cause,
          ast_cause2str(new_snapshot->hangup->cause));
    }
    if (old_snapshot->state != new_snapshot->state) {
       return ast_manager_event_blob_create(
          EVENT_FLAG_CALL, "Newstate", NO_EXTRA_FIELDS);
    }
    /* No event */
    return NULL;
 }
channel_unhold_cb()
static void channel_unhold_cb (void * data, struct stasis_subscription * sub, struct stasis_message * message) static
Definition at line 1284 of file manager_channels.c.
References ast_free, ast_manager_build_channel_state_string(), ast_str_buffer(), EVENT_FLAG_CALL, manager_event, ast_channel_blob::snapshot, and stasis_message_data().
Referenced by manager_channels_init().
 {
    struct ast_channel_blob *obj = stasis_message_data(message);
    struct ast_str *channel_event_string;
    channel_event_string = ast_manager_build_channel_state_string(obj->snapshot);
    if (!channel_event_string) {
       return;
    }
    manager_event(EVENT_FLAG_CALL, "Unhold",
       "%s",
       ast_str_buffer(channel_event_string));
    ast_free(channel_event_string);
 }
dial_status_end()
static int dial_status_end (const char * dialstatus) static
Definition at line 1184 of file manager_channels.c.
Referenced by channel_dial_cb().
 {
    return (strcmp(dialstatus, "RINGING") &&
          strcmp(dialstatus, "PROCEEDING") &&
          strcmp(dialstatus, "PROGRESS"));
 }
manager_channels_init()
int manager_channels_init (void)
Initialize support for AMI channel events.
Return values
0 on success.
non-zero on error.
Since
12
Definition at line 1308 of file manager_channels.c.
References ast_channel_chanspy_start_type(), ast_channel_chanspy_stop_type(), ast_channel_dial_type(), ast_channel_dtmf_begin_type(), ast_channel_dtmf_end_type(), ast_channel_fax_type(), ast_channel_flash_type(), ast_channel_hangup_handler_type(), ast_channel_hangup_request_type(), ast_channel_hold_type(), ast_channel_mixmonitor_mute_type(), ast_channel_mixmonitor_start_type(), ast_channel_mixmonitor_stop_type(), ast_channel_moh_start_type(), ast_channel_moh_stop_type(), ast_channel_monitor_start_type(), ast_channel_monitor_stop_type(), ast_channel_snapshot_type(), ast_channel_topic_all(), ast_channel_unhold_type(), ast_manager_get_message_router(), ast_manager_get_topic(), ast_register_cleanup(), channel_chanspy_start_cb(), channel_chanspy_stop_cb(), channel_dial_cb(), channel_dtmf_begin_cb(), channel_dtmf_end_cb(), channel_fax_cb(), channel_flash_cb(), channel_hangup_handler_cb(), channel_hangup_request_cb(), channel_hold_cb(), channel_mixmonitor_mute_cb(), channel_mixmonitor_start_cb(), channel_mixmonitor_stop_cb(), channel_moh_start_cb(), channel_moh_stop_cb(), channel_monitor_start_cb(), channel_monitor_stop_cb(), channel_snapshot_update(), channel_unhold_cb(), manager_channels_shutdown(), manager_topic, NULL, stasis_forward_all(), and stasis_message_router_add().
Referenced by subscribe_all().
 {
    int ret = 0;
    struct stasis_topic *manager_topic;
    struct stasis_topic *channel_topic;
    struct stasis_message_router *message_router;
    manager_topic = ast_manager_get_topic();
    if (!manager_topic) {
       return -1;
    }
    message_router = ast_manager_get_message_router();
    if (!message_router) {
       return -1;
    }
    channel_topic = ast_channel_topic_all();
    if (!channel_topic) {
       return -1;
    }
    topic_forwarder = stasis_forward_all(channel_topic, manager_topic);
    if (!topic_forwarder) {
       return -1;
    }
    ast_register_cleanup(manager_channels_shutdown);
    /* The snapshot type has a special handler as it can result in multiple
     * manager events being queued due to aspects of the snapshot itself
     * changing.
     */
    ret |= stasis_message_router_add(message_router,
       ast_channel_snapshot_type(), channel_snapshot_update, NULL);
    ret |= stasis_message_router_add(message_router,
       ast_channel_dtmf_begin_type(), channel_dtmf_begin_cb, NULL);
    ret |= stasis_message_router_add(message_router,
       ast_channel_dtmf_end_type(), channel_dtmf_end_cb, NULL);
    ret |= stasis_message_router_add(message_router,
       ast_channel_flash_type(), channel_flash_cb, NULL);
    ret |= stasis_message_router_add(message_router,
       ast_channel_hangup_request_type(), channel_hangup_request_cb,
       NULL);
    ret |= stasis_message_router_add(message_router,
       ast_channel_dial_type(), channel_dial_cb, NULL);
    ret |= stasis_message_router_add(message_router,
       ast_channel_hold_type(), channel_hold_cb, NULL);
    ret |= stasis_message_router_add(message_router,
       ast_channel_unhold_type(), channel_unhold_cb, NULL);
    ret |= stasis_message_router_add(message_router,
       ast_channel_fax_type(), channel_fax_cb, NULL);
    ret |= stasis_message_router_add(message_router,
       ast_channel_chanspy_start_type(), channel_chanspy_start_cb,
       NULL);
    ret |= stasis_message_router_add(message_router,
       ast_channel_chanspy_stop_type(), channel_chanspy_stop_cb, NULL);
    ret |= stasis_message_router_add(message_router,
       ast_channel_hangup_handler_type(), channel_hangup_handler_cb,
       NULL);
    ret |= stasis_message_router_add(message_router,
       ast_channel_moh_start_type(), channel_moh_start_cb, NULL);
    ret |= stasis_message_router_add(message_router,
       ast_channel_moh_stop_type(), channel_moh_stop_cb, NULL);
    ret |= stasis_message_router_add(message_router,
       ast_channel_monitor_start_type(), channel_monitor_start_cb,
       NULL);
    ret |= stasis_message_router_add(message_router,
       ast_channel_monitor_stop_type(), channel_monitor_stop_cb, NULL);
    ret |= stasis_message_router_add(message_router,
       ast_channel_mixmonitor_start_type(), channel_mixmonitor_start_cb, NULL);
    ret |= stasis_message_router_add(message_router,
       ast_channel_mixmonitor_stop_type(), channel_mixmonitor_stop_cb, NULL);
    ret |= stasis_message_router_add(message_router,
       ast_channel_mixmonitor_mute_type(), channel_mixmonitor_mute_cb, NULL);
    /* If somehow we failed to add any routes, just shut down the whole
     * thing and fail it.
     */
    if (ret) {
       manager_channels_shutdown();
       return -1;
    }
    return 0;
 }
manager_channels_shutdown()
static void manager_channels_shutdown (void) static
Definition at line 1302 of file manager_channels.c.
References NULL, and stasis_forward_cancel().
Referenced by manager_channels_init().
 {
    stasis_forward_cancel(topic_forwarder);
    topic_forwarder = NULL;
 }
publish_basic_channel_event()
static void publish_basic_channel_event (const char * event, int class, struct ast_channel_snapshot * snapshot) static
Definition at line 745 of file manager_channels.c.
References ast_free, ast_manager_build_channel_state_string(), ast_str_buffer(), manager_event, NULL, and RAII_VAR.
Referenced by channel_mixmonitor_start_cb(), channel_mixmonitor_stop_cb(), channel_moh_stop_cb(), channel_monitor_start_cb(), and channel_monitor_stop_cb().
 {
    RAII_VAR(struct ast_str *, channel_event_string, NULL, ast_free);
    channel_event_string = ast_manager_build_channel_state_string(snapshot);
    if (!channel_event_string) {
       return;
    }
    manager_event(class, event,
       "%s",
       ast_str_buffer(channel_event_string));
 }
Variable Documentation
channel_monitors
channel_snapshot_monitor channel_monitors[]
Definition at line 705 of file manager_channels.c.
Referenced by channel_snapshot_update().
topic_forwarder
struct stasis_forward* topic_forwarder static
The Stasis Message Bus API subscription returned by the forwarding of the channel topic to the manager topic.
Definition at line 485 of file manager_channels.c.