Asterisk - The Open Source Telephony Project: res_stasis_playback.c File Reference
res_stasis_playback.c File Reference
res_stasis playback support.
#include "asterisk.h"
#include "asterisk/app.h"
#include "asterisk/astobj2.h"
#include "asterisk/bridge.h"
#include "asterisk/bridge_internal.h"
#include "asterisk/file.h"
#include "asterisk/logger.h"
#include "asterisk/module.h"
#include "asterisk/paths.h"
#include "asterisk/stasis_app_impl.h"
#include "asterisk/stasis_app_playback.h"
#include "asterisk/stasis_app_recording.h"
#include "asterisk/stasis_channels.h"
#include "asterisk/stringfields.h"
#include "asterisk/uuid.h"
#include "asterisk/say.h"
#include "asterisk/indications.h"
Data Structures
struct stasis_app_playback
Macros
#define CHARACTERS_URI_SCHEME "characters:"
#define DIGITS_URI_SCHEME "digits:"
#define NUMBER_URI_SCHEME "number:"
#define PLAYBACK_BUCKETS 127
#define PLAYBACK_DEFAULT_SKIPMS 3000
#define RECORDING_URI_SCHEME "recording:"
#define SOUND_URI_SCHEME "sound:"
#define TONE_URI_SCHEME "tone:"
Typedefs
typedef int(* playback_opreation_cb) (struct stasis_app_playback *playback)
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int load_module (void)
static void play_on_channel (struct stasis_app_playback *playback, struct ast_channel *chan)
static void play_on_channel_in_bridge (struct ast_bridge_channel *bridge_channel, const char *playback_id)
Special case code to play while a channel is in a bridge.
static int play_uri (struct stasis_app_control *control, struct ast_channel *chan, void *data)
static int playback_cancel (struct stasis_app_playback *playback)
static int playback_cmp (void *obj, void *arg, int flags)
static struct stasis_app_playback * playback_create (struct stasis_app_control *control, const char *id)
static void playback_dtor (void *obj)
static void playback_final_update (struct stasis_app_playback *playback, long playedms, int res, const char *uniqueid)
static int playback_first_update (struct stasis_app_playback *playback, const char *uniqueid)
static int playback_forward (struct stasis_app_playback *playback)
static int playback_hash (const void *obj, int flags)
static int playback_noop (struct stasis_app_playback *playback)
static int playback_pause (struct stasis_app_playback *playback)
static void playback_publish (struct stasis_app_playback *playback)
static int playback_restart (struct stasis_app_playback *playback)
static int playback_reverse (struct stasis_app_playback *playback)
static int playback_stop (struct stasis_app_playback *playback)
static struct ast_json * playback_to_json (struct stasis_message *message, const struct stasis_message_sanitizer *sanitize)
static int playback_unpause (struct stasis_app_playback *playback)
static void remove_from_playbacks (void *data)
RAII_VAR function to remove a playback from the global list when leaving scope.
static void set_target_uri (struct stasis_app_playback *playback, enum stasis_app_playback_target_type target_type, const char *target_id)
struct stasis_app_playback * stasis_app_control_play_uri (struct stasis_app_control *control, const char **media, size_t media_count, const char *language, const char *target_id, enum stasis_app_playback_target_type target_type, int skipms, long offsetms, const char *id)
Play a file to the control's channel.
struct stasis_app_playback * stasis_app_playback_find_by_id (const char *id)
Finds the playback object with the given id.
const char * stasis_app_playback_get_id (struct stasis_app_playback *control)
Gets the unique id of a playback object.
enum stasis_app_playback_state stasis_app_playback_get_state (struct stasis_app_playback *control)
Gets the current state of a playback operation.
enum stasis_playback_oper_results stasis_app_playback_operation (struct stasis_app_playback *playback, enum stasis_app_playback_media_operation operation)
Controls the media for a given playback operation.
struct ast_json * stasis_app_playback_to_json (const struct stasis_app_playback *playback)
Convert a playback to its JSON representation.
STASIS_MESSAGE_TYPE_DEFN (stasis_app_playback_snapshot_type,.to_json=playback_to_json,)
static const char * state_to_string (enum stasis_app_playback_state state)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_GLOBAL_SYMBOLS , .description = "Stasis application playback support" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .requires = "res_stasis,res_stasis_recording" }
static const struct ast_module_info * ast_module_info = &__mod_info
playback_opreation_cb operations [STASIS_PLAYBACK_STATE_MAX][STASIS_PLAYBACK_MEDIA_OP_MAX]
A sparse array detailing how commands should be handled in the various playback states. Unset entries imply invalid operations.
static struct ao2_container * playbacks
Detailed Description
res_stasis playback support.
Author
David M. Lee, II dlee@.nosp@m.digi.nosp@m.um.co.nosp@m.m
Definition in file res_stasis_playback.c.
Macro Definition Documentation
CHARACTERS_URI_SCHEME
#define CHARACTERS_URI_SCHEME "characters:"
Definition at line 61 of file res_stasis_playback.c.
Referenced by play_on_channel().
DIGITS_URI_SCHEME
#define DIGITS_URI_SCHEME "digits:"
Definition at line 60 of file res_stasis_playback.c.
Referenced by play_on_channel().
NUMBER_URI_SCHEME
#define NUMBER_URI_SCHEME "number:"
Definition at line 59 of file res_stasis_playback.c.
Referenced by play_on_channel().
PLAYBACK_BUCKETS
#define PLAYBACK_BUCKETS 127
Number of hash buckets for playback container. Keep it prime!
Definition at line 52 of file res_stasis_playback.c.
Referenced by load_module().
PLAYBACK_DEFAULT_SKIPMS
#define PLAYBACK_DEFAULT_SKIPMS 3000
Default number of milliseconds of media to skip
Definition at line 55 of file res_stasis_playback.c.
Referenced by stasis_app_control_play_uri().
RECORDING_URI_SCHEME
#define RECORDING_URI_SCHEME "recording:"
Definition at line 58 of file res_stasis_playback.c.
Referenced by play_on_channel().
SOUND_URI_SCHEME
#define SOUND_URI_SCHEME "sound:"
Definition at line 57 of file res_stasis_playback.c.
Referenced by play_on_channel().
TONE_URI_SCHEME
#define TONE_URI_SCHEME "tone:"
Definition at line 62 of file res_stasis_playback.c.
Referenced by play_on_channel().
Typedef Documentation
playback_opreation_cb
typedef int(* playback_opreation_cb) (struct stasis_app_playback *playback)
Definition at line 584 of file res_stasis_playback.c.
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 773 of file res_stasis_playback.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 773 of file res_stasis_playback.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 773 of file res_stasis_playback.c.
load_module()
static int load_module (void) static
Definition at line 742 of file res_stasis_playback.c.
References AO2_ALLOC_OPT_LOCK_MUTEX, ao2_container_alloc_hash, AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, NULL, PLAYBACK_BUCKETS, playback_cmp(), playback_hash(), stasis_app_playback_snapshot_type(), STASIS_MESSAGE_TYPE_CLEANUP, and STASIS_MESSAGE_TYPE_INIT.
Referenced by unload_module().
 {
    int r;
    r = STASIS_MESSAGE_TYPE_INIT(stasis_app_playback_snapshot_type);
    if (r != 0) {
       return AST_MODULE_LOAD_DECLINE;
    }
    playbacks = ao2_container_alloc_hash(AO2_ALLOC_OPT_LOCK_MUTEX, 0, PLAYBACK_BUCKETS,
       playback_hash, NULL, playback_cmp);
    if (!playbacks) {
       STASIS_MESSAGE_TYPE_CLEANUP(stasis_app_playback_snapshot_type);
       return AST_MODULE_LOAD_DECLINE;
    }
    return AST_MODULE_LOAD_SUCCESS;
 }
play_on_channel()
static void play_on_channel (struct stasis_app_playback * playback, struct ast_channel * chan) static
Definition at line 285 of file res_stasis_playback.c.
References ao2_cleanup, ast_assert, ast_begins_with(), ast_channel_name(), ast_channel_uniqueid(), AST_CONTROL_PROGRESS, AST_CONTROL_STREAM_STOP, ast_control_streamfile_lang(), ast_control_tone(), ast_indicate(), ast_log, AST_SAY_CASE_NONE, ast_say_character_str(), ast_say_digit_str(), ast_say_number(), AST_STATE_UP, ast_string_field_set, AST_VECTOR_GET, AST_VECTOR_SIZE, CHARACTERS_URI_SCHEME, DIGITS_URI_SCHEME, stasis_app_playback::language, LOG_ERROR, stasis_app_playback::media, NULL, NUMBER_URI_SCHEME, playback_final_update(), playback_first_update(), RAII_VAR, RECORDING_URI_SCHEME, SOUND_URI_SCHEME, stasis_app_stored_recording_find_by_name(), stasis_app_stored_recording_get_file(), stop, and TONE_URI_SCHEME.
Referenced by play_on_channel_in_bridge(), and play_uri().
 {
    int res;
    long offsetms;
    size_t index;
    /* Even though these local variables look fairly pointless, they avoid
     * having a bunch of NULL's passed directly into
     * ast_control_streamfile() */
    const char *fwd = NULL;
    const char *rev = NULL;
    const char *stop = NULL;
    const char *pause = NULL;
    const char *restart = NULL;
    ast_assert(playback != NULL);
    if (ast_channel_state(chan) != AST_STATE_UP) {
       ast_indicate(chan, AST_CONTROL_PROGRESS);
    }
    offsetms = playback->offsetms;
    for (index = 0; index < AST_VECTOR_SIZE(&playback->medias); index++) {
       playback->media_index = index;
       /* Set the current media to play */
       ast_string_field_set(playback, media, AST_VECTOR_GET(&playback->medias, playback->media_index));
       res = playback_first_update(playback, ast_channel_uniqueid(chan));
       if (res != 0) {
          return;
       }
       if (ast_begins_with(playback->media, SOUND_URI_SCHEME)) {
          playback->controllable = 1;
          /* Play sound */
          res = ast_control_streamfile_lang(chan, playback->media + strlen(SOUND_URI_SCHEME),
                fwd, rev, stop, pause, restart, playback->skipms, playback->language,
                &offsetms);
       } else if (ast_begins_with(playback->media, RECORDING_URI_SCHEME)) {
          /* Play recording */
          RAII_VAR(struct stasis_app_stored_recording *, recording, NULL,
             ao2_cleanup);
          const char *relname =
             playback->media + strlen(RECORDING_URI_SCHEME);
          recording = stasis_app_stored_recording_find_by_name(relname);
          if (!recording) {
             ast_log(LOG_ERROR, "Attempted to play recording '%s' on channel '%s' but recording does not exist",
                relname, ast_channel_name(chan));
             continue;
          }
          playback->controllable = 1;
          res = ast_control_streamfile_lang(chan,
             stasis_app_stored_recording_get_file(recording), fwd, rev, stop, pause,
             restart, playback->skipms, playback->language, &offsetms);
       } else if (ast_begins_with(playback->media, NUMBER_URI_SCHEME)) {
          int number;
          if (sscanf(playback->media + strlen(NUMBER_URI_SCHEME), "%30d", &number) != 1) {
             ast_log(LOG_ERROR, "Attempted to play number '%s' on channel '%s' but number is invalid",
                playback->media + strlen(NUMBER_URI_SCHEME), ast_channel_name(chan));
             continue;
          }
          res = ast_say_number(chan, number, stop, playback->language, NULL);
       } else if (ast_begins_with(playback->media, DIGITS_URI_SCHEME)) {
          res = ast_say_digit_str(chan, playback->media + strlen(DIGITS_URI_SCHEME),
             stop, playback->language);
       } else if (ast_begins_with(playback->media, CHARACTERS_URI_SCHEME)) {
          res = ast_say_character_str(chan, playback->media + strlen(CHARACTERS_URI_SCHEME),
             stop, playback->language, AST_SAY_CASE_NONE);
       } else if (ast_begins_with(playback->media, TONE_URI_SCHEME)) {
          playback->controllable = 1;
          res = ast_control_tone(chan, playback->media + strlen(TONE_URI_SCHEME));
       } else {
          /* Play URL */
          ast_log(LOG_ERROR, "Attempted to play URI '%s' on channel '%s' but scheme is unsupported\n",
             playback->media, ast_channel_name(chan));
          continue;
       }
       playback_final_update(playback, offsetms, res,
          ast_channel_uniqueid(chan));
       if (res == AST_CONTROL_STREAM_STOP) {
          break;
       }
       /* Reset offset for any subsequent media */
       offsetms = 0;
    }
    return;
 }
play_on_channel_in_bridge()
static void play_on_channel_in_bridge (struct ast_bridge_channel * bridge_channel, const char * playback_id) static
Special case code to play while a channel is in a bridge.
Parameters
bridge_channel The channel's bridge_channel.
playback_id Id of the playback to start.
Definition at line 390 of file res_stasis_playback.c.
References ao2_cleanup, ast_log, ast_bridge_channel::chan, LOG_ERROR, NULL, play_on_channel(), RAII_VAR, and stasis_app_playback_find_by_id().
Referenced by play_uri().
 {
    RAII_VAR(struct stasis_app_playback *, playback, NULL, ao2_cleanup);
    playback = stasis_app_playback_find_by_id(playback_id);
    if (!playback) {
       ast_log(LOG_ERROR, "Couldn't find playback %s\n",
          playback_id);
       return;
    }
    play_on_channel(playback, bridge_channel->chan);
 }
play_uri()
static int play_uri (struct stasis_app_control * control, struct ast_channel * chan, void * data) static
Definition at line 418 of file res_stasis_playback.c.
References ao2_bump, ao2_cleanup, ast_bridge_channel_queue_playfile_sync(), ast_bridge_lock, ast_bridge_unlock, bridge_find_channel(), stasis_app_playback::id, NULL, play_on_channel(), play_on_channel_in_bridge(), and stasis_app_get_bridge().
Referenced by stasis_app_control_play_uri().
 {
    struct stasis_app_playback *playback = data;
    struct ast_bridge *bridge;
    if (!control) {
       return -1;
    }
    bridge = stasis_app_get_bridge(control);
    if (bridge) {
       struct ast_bridge_channel *bridge_chan;
       /* Queue up playback on the bridge */
       ast_bridge_lock(bridge);
       bridge_chan = ao2_bump(bridge_find_channel(bridge, chan));
       ast_bridge_unlock(bridge);
       if (bridge_chan) {
          ast_bridge_channel_queue_playfile_sync(
             bridge_chan,
             play_on_channel_in_bridge,
             playback->id,
             NULL); /* moh_class */
       }
       ao2_cleanup(bridge_chan);
    } else {
       play_on_channel(playback, chan);
    }
    return 0;
 }
playback_cancel()
static int playback_cancel (struct stasis_app_playback * playback) static
Definition at line 591 of file res_stasis_playback.c.
References lock, SCOPED_AO2LOCK, and STASIS_PLAYBACK_STATE_CANCELED.
 {
    SCOPED_AO2LOCK(lock, playback);
    playback->state = STASIS_PLAYBACK_STATE_CANCELED;
    return 0;
 }
playback_cmp()
static int playback_cmp (void * obj, void * arg, int flags) static
Definition at line 181 of file res_stasis_playback.c.
References CMP_MATCH, CMP_STOP, stasis_app_playback::id, and OBJ_KEY.
Referenced by load_module().
 {
    struct stasis_app_playback *lhs = obj;
    struct stasis_app_playback *rhs = arg;
    const char *rhs_id = flags & OBJ_KEY ? arg : rhs->id;
    if (strcmp(lhs->id, rhs_id) == 0) {
       return CMP_MATCH | CMP_STOP;
    } else {
       return 0;
    }
 }
playback_create()
static struct stasis_app_playback* playback_create (struct stasis_app_control * control, const char * id) static
Definition at line 140 of file res_stasis_playback.c.
References ao2_alloc, ao2_cleanup, ao2_ref, ast_string_field_init, ast_string_field_set, ast_strlen_zero, ast_uuid_generate_str(), AST_UUID_STR_LEN, AST_VECTOR_INIT, NULL, playback_dtor(), and RAII_VAR.
Referenced by stasis_app_control_play_uri().
 {
    RAII_VAR(struct stasis_app_playback *, playback, NULL, ao2_cleanup);
    char uuid[AST_UUID_STR_LEN];
    if (!control) {
       return NULL;
    }
    playback = ao2_alloc(sizeof(*playback), playback_dtor);
    if (!playback || ast_string_field_init(playback, 128)) {
       return NULL;
    }
    if (AST_VECTOR_INIT(&playback->medias, 8)) {
       ao2_ref(playback, -1);
       return NULL;
    }
    if (!ast_strlen_zero(id)) {
       ast_string_field_set(playback, id, id);
    } else {
       ast_uuid_generate_str(uuid, sizeof(uuid));
       ast_string_field_set(playback, id, uuid);
    }
    ao2_ref(control, +1);
    playback->control = control;
    ao2_ref(playback, +1);
    return playback;
 }
playback_dtor()
static void playback_dtor (void * obj) static
Definition at line 124 of file res_stasis_playback.c.
References ao2_cleanup, ast_free, ast_string_field_free_memory, AST_VECTOR_FREE, AST_VECTOR_GET, AST_VECTOR_SIZE, and stasis_app_playback::media.
Referenced by playback_create().
 {
    struct stasis_app_playback *playback = obj;
    int i;
    for (i = 0; i < AST_VECTOR_SIZE(&playback->medias); i++) {
       char *media = AST_VECTOR_GET(&playback->medias, i);
       ast_free(media);
    }
    AST_VECTOR_FREE(&playback->medias);
    ao2_cleanup(playback->control);
    ast_string_field_free_memory(playback);
 }
playback_final_update()
static void playback_final_update (struct stasis_app_playback * playback, long playedms, int res, const char * uniqueid) static
Definition at line 259 of file res_stasis_playback.c.
References ast_log, AST_VECTOR_SIZE, lock, LOG_NOTICE, LOG_WARNING, stasis_app_playback::media, playback_publish(), SCOPED_AO2LOCK, STASIS_PLAYBACK_STATE_COMPLETE, STASIS_PLAYBACK_STATE_CONTINUING, and STASIS_PLAYBACK_STATE_STOPPED.
Referenced by play_on_channel().
 {
    SCOPED_AO2LOCK(lock, playback);
    playback->playedms = playedms;
    if (res == 0) {
       if (playback->media_index == AST_VECTOR_SIZE(&playback->medias) - 1) {
          playback->state = STASIS_PLAYBACK_STATE_COMPLETE;
       } else {
          playback->state = STASIS_PLAYBACK_STATE_CONTINUING;
       }
    } else {
       if (playback->state == STASIS_PLAYBACK_STATE_STOPPED) {
          ast_log(LOG_NOTICE, "%s: Playback stopped for %s\n",
             uniqueid, playback->media);
       } else {
          ast_log(LOG_WARNING, "%s: Playback failed for %s\n",
             uniqueid, playback->media);
          playback->state = STASIS_PLAYBACK_STATE_STOPPED;
       }
    }
    playback_publish(playback);
 }
playback_first_update()
static int playback_first_update (struct stasis_app_playback * playback, const char * uniqueid) static
Definition at line 240 of file res_stasis_playback.c.
References ast_log, lock, LOG_NOTICE, stasis_app_playback::media, playback_publish(), SCOPED_AO2LOCK, STASIS_PLAYBACK_STATE_CANCELED, and STASIS_PLAYBACK_STATE_PLAYING.
Referenced by play_on_channel().
 {
    int res;
    SCOPED_AO2LOCK(lock, playback);
    if (playback->state == STASIS_PLAYBACK_STATE_CANCELED) {
       ast_log(LOG_NOTICE, "%s: Playback canceled for %s\n",
          uniqueid, playback->media);
       res = -1;
    } else {
       res = 0;
       playback->state = STASIS_PLAYBACK_STATE_PLAYING;
    }
    playback_publish(playback);
    return res;
 }
playback_forward()
static int playback_forward (struct stasis_app_playback * playback) static
Definition at line 665 of file res_stasis_playback.c.
References AST_CONTROL_STREAM_FORWARD, lock, SCOPED_AO2LOCK, and stasis_app_control_queue_control().
 {
    SCOPED_AO2LOCK(lock, playback);
    if (!playback->controllable) {
       return -1;
    }
    return stasis_app_control_queue_control(playback->control,
       AST_CONTROL_STREAM_FORWARD);
 }
playback_hash()
static int playback_hash (const void * obj, int flags) static
Definition at line 174 of file res_stasis_playback.c.
References ast_str_hash(), stasis_app_playback::id, and OBJ_KEY.
Referenced by load_module().
 {
    const struct stasis_app_playback *playback = obj;
    const char *id = flags & OBJ_KEY ? obj : playback->id;
    return ast_str_hash(id);
 }
playback_noop()
static int playback_noop (struct stasis_app_playback * playback) static
Definition at line 586 of file res_stasis_playback.c.
 {
    return 0;
 }
playback_pause()
static int playback_pause (struct stasis_app_playback * playback) static
Definition at line 623 of file res_stasis_playback.c.
References AST_CONTROL_STREAM_SUSPEND, lock, playback_publish(), SCOPED_AO2LOCK, stasis_app_control_queue_control(), and STASIS_PLAYBACK_STATE_PAUSED.
 {
    SCOPED_AO2LOCK(lock, playback);
    if (!playback->controllable) {
       return -1;
    }
    playback->state = STASIS_PLAYBACK_STATE_PAUSED;
    playback_publish(playback);
    return stasis_app_control_queue_control(playback->control,
       AST_CONTROL_STREAM_SUSPEND);
 }
playback_publish()
static void playback_publish (struct stasis_app_playback * playback) static
Definition at line 218 of file res_stasis_playback.c.
References ao2_cleanup, ast_assert, ast_channel_blob_create_from_cache(), ast_json_unref(), NULL, RAII_VAR, stasis_app_control_get_channel_id(), stasis_app_control_publish(), stasis_app_playback_snapshot_type(), and stasis_app_playback_to_json().
Referenced by playback_final_update(), playback_first_update(), playback_pause(), playback_unpause(), and stasis_app_control_play_uri().
 {
    RAII_VAR(struct ast_json *, json, NULL, ast_json_unref);
    RAII_VAR(struct stasis_message *, message, NULL, ao2_cleanup);
    ast_assert(playback != NULL);
    json = stasis_app_playback_to_json(playback);
    if (json == NULL) {
       return;
    }
    message = ast_channel_blob_create_from_cache(
       stasis_app_control_get_channel_id(playback->control),
       stasis_app_playback_snapshot_type(), json);
    if (message == NULL) {
       return;
    }
    stasis_app_control_publish(playback->control, message);
 }
playback_restart()
static int playback_restart (struct stasis_app_playback * playback) static
Definition at line 611 of file res_stasis_playback.c.
References AST_CONTROL_STREAM_RESTART, lock, SCOPED_AO2LOCK, and stasis_app_control_queue_control().
 {
    SCOPED_AO2LOCK(lock, playback);
    if (!playback->controllable) {
       return -1;
    }
    return stasis_app_control_queue_control(playback->control,
       AST_CONTROL_STREAM_RESTART);
 }
playback_reverse()
static int playback_reverse (struct stasis_app_playback * playback) static
Definition at line 653 of file res_stasis_playback.c.
References AST_CONTROL_STREAM_REVERSE, lock, SCOPED_AO2LOCK, and stasis_app_control_queue_control().
 {
    SCOPED_AO2LOCK(lock, playback);
    if (!playback->controllable) {
       return -1;
    }
    return stasis_app_control_queue_control(playback->control,
       AST_CONTROL_STREAM_REVERSE);
 }
playback_stop()
static int playback_stop (struct stasis_app_playback * playback) static
Definition at line 598 of file res_stasis_playback.c.
References AST_CONTROL_STREAM_STOP, lock, SCOPED_AO2LOCK, stasis_app_control_queue_control(), and STASIS_PLAYBACK_STATE_STOPPED.
 {
    SCOPED_AO2LOCK(lock, playback);
    if (!playback->controllable) {
       return -1;
    }
    playback->state = STASIS_PLAYBACK_STATE_STOPPED;
    return stasis_app_control_queue_control(playback->control,
       AST_CONTROL_STREAM_STOP);
 }
playback_to_json()
static struct ast_json* playback_to_json (struct stasis_message * message, const struct stasis_message_sanitizer * sanitize) static
Definition at line 95 of file res_stasis_playback.c.
References ast_json_object_get(), ast_json_pack(), ast_json_string_get(), ast_json_timeval(), ast_channel_blob::blob, NULL, stasis_app_playback_snapshot_type(), stasis_message_data(), stasis_message_timestamp(), STASIS_MESSAGE_TYPE_DEFN(), and type.
 {
    struct ast_channel_blob *channel_blob = stasis_message_data(message);
    struct ast_json *blob = channel_blob->blob;
    const char *state =
       ast_json_string_get(ast_json_object_get(blob, "state"));
    const char *type;
    if (!strcmp(state, "playing")) {
       type = "PlaybackStarted";
    } else if (!strcmp(state, "continuing")) {
       type = "PlaybackContinuing";
    } else if (!strcmp(state, "done")) {
       type = "PlaybackFinished";
    } else {
       return NULL;
    }
    return ast_json_pack("{s: s, s: o?, s: O}",
       "type", type,
       "timestamp", ast_json_timeval(*stasis_message_timestamp(message), NULL),
       "playback", blob);
 }
playback_unpause()
static int playback_unpause (struct stasis_app_playback * playback) static
Definition at line 638 of file res_stasis_playback.c.
References AST_CONTROL_STREAM_SUSPEND, lock, playback_publish(), SCOPED_AO2LOCK, stasis_app_control_queue_control(), and STASIS_PLAYBACK_STATE_PLAYING.
 {
    SCOPED_AO2LOCK(lock, playback);
    if (!playback->controllable) {
       return -1;
    }
    playback->state = STASIS_PLAYBACK_STATE_PLAYING;
    playback_publish(playback);
    return stasis_app_control_queue_control(playback->control,
       AST_CONTROL_STREAM_SUSPEND);
 }
remove_from_playbacks()
static void remove_from_playbacks (void * data) static
RAII_VAR function to remove a playback from the global list when leaving scope.
Definition at line 409 of file res_stasis_playback.c.
References ao2_ref, ao2_unlink_flags, OBJ_NODATA, OBJ_POINTER, and OBJ_UNLINK.
Referenced by stasis_app_control_play_uri().
 {
    struct stasis_app_playback *playback = data;
    ao2_unlink_flags(playbacks, playback,
       OBJ_POINTER | OBJ_UNLINK | OBJ_NODATA);
    ao2_ref(playback, -1);
 }
set_target_uri()
static void set_target_uri (struct stasis_app_playback * playback, enum stasis_app_playback_target_type target_type, const char * target_id) static
Definition at line 451 of file res_stasis_playback.c.
References ast_assert, ast_string_field_build, NULL, STASIS_PLAYBACK_TARGET_BRIDGE, STASIS_PLAYBACK_TARGET_CHANNEL, stasis_app_playback::target, and type.
Referenced by stasis_app_control_play_uri().
 {
    const char *type = NULL;
    switch (target_type) {
    case STASIS_PLAYBACK_TARGET_CHANNEL:
       type = "channel";
       break;
    case STASIS_PLAYBACK_TARGET_BRIDGE:
       type = "bridge";
       break;
    }
    ast_assert(type != NULL);
    ast_string_field_build(playback, target, "%s:%s", type, target_id);
 }
stasis_app_control_play_uri()
struct stasis_app_playback* stasis_app_control_play_uri (struct stasis_app_control * control, const char ** media, size_t media_count, const char * language, const char * target_id, enum stasis_app_playback_target_type target_type, int skipms, long offsetms, const char * id)
Play a file to the control's channel.
Note that the file isn't the full path to the file. Asterisk's internal playback mechanism will automagically select the best format based on the available codecs for the channel.
Parameters
control Control for res_stasis.
media Array of const char * media files to play.
media_count The number of media files in media.
language Selects the file based on language.
target_id ID of the target bridge or channel.
target_type What the target type is
skipms Number of milliseconds to skip for forward/reverse operations.
offsetms Number of milliseconds to skip before playing.
id ID to assign the new playback or NULL for default.
Returns
Playback control object.
NULL on error.
Definition at line 471 of file res_stasis_playback.c.
References ao2_bump, ao2_link, ao2_ref, ast_debug, ast_free, ast_log, ast_malloc, ast_string_field_set, ast_strlen_zero, AST_VECTOR_APPEND, AST_VECTOR_GET, LOG_ERROR, NULL, play_uri(), playback_create(), PLAYBACK_DEFAULT_SKIPMS, playback_publish(), remove_from_playbacks(), set_target_uri(), skipms, stasis_app_control_get_channel_id(), stasis_app_send_command_async(), and STASIS_PLAYBACK_STATE_QUEUED.
Referenced by ari_bridges_play_helper(), and ari_channels_handle_play().
 {
    struct stasis_app_playback *playback;
    size_t i;
    if (skipms < 0 || offsetms < 0 || media_count == 0) {
       return NULL;
    }
    playback = playback_create(control, id);
    if (!playback) {
       return NULL;
    }
    for (i = 0; i < media_count; i++) {
       char *media_uri;
       if (ast_strlen_zero(media[i])) {
          ast_log(LOG_ERROR, "Attempted to play media on channel '%s' but no media URI was provided.\n",
             stasis_app_control_get_channel_id(control));
          ao2_ref(playback, -1);
          return NULL;
       }
       media_uri = ast_malloc(strlen(media[i]) + 1);
       if (!media_uri) {
          ao2_ref(playback, -1);
          return NULL;
       }
       ast_debug(3, "%s: Sending play(%s) command\n",
          stasis_app_control_get_channel_id(control), media[i]);
        /* safe */
       strcpy(media_uri, media[i]);
       if (AST_VECTOR_APPEND(&playback->medias, media_uri)) {
          ao2_ref(playback, -1);
          ast_free(media_uri);
          return NULL;
       }
    }
    if (skipms == 0) {
       skipms = PLAYBACK_DEFAULT_SKIPMS;
    }
    ast_string_field_set(playback, media, AST_VECTOR_GET(&playback->medias, 0));
    ast_string_field_set(playback, language, language);
    set_target_uri(playback, target_type, target_id);
    playback->skipms = skipms;
    playback->offsetms = offsetms;
    ao2_link(playbacks, playback);
    playback->state = STASIS_PLAYBACK_STATE_QUEUED;
    playback_publish(playback);
    stasis_app_send_command_async(control, play_uri, ao2_bump(playback), remove_from_playbacks);
    return playback;
 }
stasis_app_playback_find_by_id()
struct stasis_app_playback* stasis_app_playback_find_by_id (const char * id)
Finds the playback object with the given id.
Parameters
id Id of the playback object to find.
Returns
Associated stasis_app_playback object.
NULL if id not found.
Definition at line 550 of file res_stasis_playback.c.
References ao2_find, and OBJ_KEY.
Referenced by ast_ari_playbacks_control(), ast_ari_playbacks_get(), ast_ari_playbacks_stop(), and play_on_channel_in_bridge().
 {
    return ao2_find(playbacks, id, OBJ_KEY);
 }
stasis_app_playback_get_id()
const char* stasis_app_playback_get_id (struct stasis_app_playback * playback)
Gets the unique id of a playback object.
Parameters
playback Playback control object.
Returns
playback's id.
NULL if playback ic NULL
Definition at line 543 of file res_stasis_playback.c.
References stasis_app_playback::id.
Referenced by ari_bridges_play_helper(), and ari_channels_handle_play().
 {
    /* id is immutable; no lock needed */
    return control->id;
 }
stasis_app_playback_get_state()
enum stasis_app_playback_state stasis_app_playback_get_state (struct stasis_app_playback * playback)
Gets the current state of a playback operation.
Parameters
playback Playback control object.
Returns
The state of the playback object.
Definition at line 536 of file res_stasis_playback.c.
References lock, and SCOPED_AO2LOCK.
 {
    SCOPED_AO2LOCK(lock, control);
    return control->state;
 }
stasis_app_playback_operation()
enum stasis_playback_oper_results stasis_app_playback_operation (struct stasis_app_playback * playback, enum stasis_app_playback_media_operation operation)
Controls the media for a given playback operation.
Parameters
playback Playback control object.
control Media control operation.
Returns
STASIS_PLAYBACK_OPER_OK on success.
stasis_playback_oper_results indicating failure.
Definition at line 708 of file res_stasis_playback.c.
References ast_assert, ast_log, lock, LOG_ERROR, operations, SCOPED_AO2LOCK, STASIS_PLAYBACK_MEDIA_OP_MAX, STASIS_PLAYBACK_OPER_FAILED, STASIS_PLAYBACK_OPER_NOT_PLAYING, STASIS_PLAYBACK_OPER_OK, STASIS_PLAYBACK_STATE_MAX, and STASIS_PLAYBACK_STATE_PLAYING.
Referenced by ast_ari_playbacks_control(), and ast_ari_playbacks_stop().
 {
    playback_opreation_cb cb;
    SCOPED_AO2LOCK(lock, playback);
    ast_assert((unsigned int)playback->state < STASIS_PLAYBACK_STATE_MAX);
    if (operation >= STASIS_PLAYBACK_MEDIA_OP_MAX) {
       ast_log(LOG_ERROR, "Invalid playback operation %u\n", operation);
       return -1;
    }
    cb = operations[playback->state][operation];
    if (!cb) {
       if (playback->state != STASIS_PLAYBACK_STATE_PLAYING) {
          /* So we can be specific in our error message. */
          return STASIS_PLAYBACK_OPER_NOT_PLAYING;
       } else {
          /* And, really, all operations should be valid during
           * playback */
          ast_log(LOG_ERROR,
             "Unhandled operation during playback: %u\n",
             operation);
          return STASIS_PLAYBACK_OPER_FAILED;
       }
    }
    return cb(playback) ?
       STASIS_PLAYBACK_OPER_FAILED : STASIS_PLAYBACK_OPER_OK;
 }
stasis_app_playback_to_json()
struct ast_json* stasis_app_playback_to_json (const struct stasis_app_playback * playback)
Convert a playback to its JSON representation.
Parameters
playback The playback object to convert to JSON
Return values
Definition at line 555 of file res_stasis_playback.c.
References ast_json_pack(), ast_json_ref(), ast_json_unref(), AST_VECTOR_GET, AST_VECTOR_SIZE, stasis_app_playback::id, stasis_app_playback::language, stasis_app_playback::media, NULL, RAII_VAR, state_to_string(), and stasis_app_playback::target.
Referenced by ari_bridges_play_helper(), ari_channels_handle_play(), ast_ari_playbacks_get(), and playback_publish().
 {
    RAII_VAR(struct ast_json *, json, NULL, ast_json_unref);
    if (playback == NULL) {
       return NULL;
    }
    if (playback->media_index == AST_VECTOR_SIZE(&playback->medias) - 1) {
       json = ast_json_pack("{s: s, s: s, s: s, s: s, s: s}",
          "id", playback->id,
          "media_uri", playback->media,
          "target_uri", playback->target,
          "language", playback->language,
          "state", state_to_string(playback->state));
    } else {
       json = ast_json_pack("{s: s, s: s, s: s, s: s, s: s, s: s}",
          "id", playback->id,
          "media_uri", playback->media,
          "next_media_uri", AST_VECTOR_GET(&playback->medias, playback->media_index + 1),
          "target_uri", playback->target,
          "language", playback->language,
          "state", state_to_string(playback->state));
    }
    return ast_json_ref(json);
 }
STASIS_MESSAGE_TYPE_DEFN()
STASIS_MESSAGE_TYPE_DEFN (stasis_app_playback_snapshot_type , . to_json = playback_to_json)
Referenced by playback_to_json().
state_to_string()
static const char* state_to_string (enum stasis_app_playback_state state) static
Definition at line 194 of file res_stasis_playback.c.
References STASIS_PLAYBACK_STATE_CANCELED, STASIS_PLAYBACK_STATE_COMPLETE, STASIS_PLAYBACK_STATE_CONTINUING, STASIS_PLAYBACK_STATE_MAX, STASIS_PLAYBACK_STATE_PAUSED, STASIS_PLAYBACK_STATE_PLAYING, STASIS_PLAYBACK_STATE_QUEUED, and STASIS_PLAYBACK_STATE_STOPPED.
Referenced by stasis_app_playback_to_json().
 {
    switch (state) {
    case STASIS_PLAYBACK_STATE_QUEUED:
       return "queued";
    case STASIS_PLAYBACK_STATE_PLAYING:
       return "playing";
    case STASIS_PLAYBACK_STATE_PAUSED:
       return "paused";
    case STASIS_PLAYBACK_STATE_CONTINUING:
       return "continuing";
    case STASIS_PLAYBACK_STATE_STOPPED:
    case STASIS_PLAYBACK_STATE_COMPLETE:
    case STASIS_PLAYBACK_STATE_CANCELED:
       /* It doesn't really matter how we got here, but all of these
        * states really just mean 'done' */
       return "done";
    case STASIS_PLAYBACK_STATE_MAX:
       break;
    }
    return "?";
 }
unload_module()
static int unload_module (void) static
Definition at line 760 of file res_stasis_playback.c.
References ao2_cleanup, AST_MODFLAG_GLOBAL_SYMBOLS, AST_MODULE_INFO(), AST_MODULE_SUPPORT_CORE, ASTERISK_GPL_KEY, load_module(), NULL, stasis_app_playback_snapshot_type(), and STASIS_MESSAGE_TYPE_CLEANUP.
 {
    ao2_cleanup(playbacks);
    playbacks = NULL;
    STASIS_MESSAGE_TYPE_CLEANUP(stasis_app_playback_snapshot_type);
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_GLOBAL_SYMBOLS , .description = "Stasis application playback support" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .requires = "res_stasis,res_stasis_recording" } static
Definition at line 773 of file res_stasis_playback.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 773 of file res_stasis_playback.c.
operations
playback_opreation_cb operations[STASIS_PLAYBACK_STATE_MAX][STASIS_PLAYBACK_MEDIA_OP_MAX]
A sparse array detailing how commands should be handled in the various playback states. Unset entries imply invalid operations.
Definition at line 681 of file res_stasis_playback.c.
Referenced by stasis_app_playback_operation().
playbacks
struct ao2_container* playbacks static
Container of all current playbacks
Definition at line 65 of file res_stasis_playback.c.