Asterisk - The Open Source Telephony Project: test_event.c File Reference
test_event.c File Reference
Tests for the ast_event API.
#include "asterisk.h"
#include "asterisk/module.h"
#include "asterisk/utils.h"
#include "asterisk/test.h"
#include "asterisk/event.h"
Data Structures
struct event_sub_data
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
AST_TEST_DEFINE (event_new_test)
static int check_event (struct ast_event *event, struct ast_test *test, enum ast_event_type expected_type, const char *type_name, const char *str, uint32_t uint)
static int load_module (void)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "ast_event API Tests" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, }
static const struct ast_module_info * ast_module_info = &__mod_info
Detailed Description
Tests for the ast_event API.
Author
Russell Bryant russe.nosp@m.ll@d.nosp@m.igium.nosp@m..com
Todo:
API Calls not yet touched by a test: XXX TODO
ast_event_get_ie_type_name()
ast_event_get_ie_pltype()
ast_event_iterator_init()
ast_event_iterator_next()
ast_event_iterator_get_ie_type()
ast_event_iterator_get_ie_uint()
ast_event_iterator_get_ie_str()
Definition in file test_event.c.
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 208 of file test_event.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 208 of file test_event.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 208 of file test_event.c.
AST_TEST_DEFINE()
AST_TEST_DEFINE (event_new_test)
Definition at line 96 of file test_event.c.
References ast_event_append_ie_str(), ast_event_append_ie_uint(), AST_EVENT_CUSTOM, ast_event_destroy(), ast_event_get_size(), AST_EVENT_IE_CEL_AMAFLAGS, AST_EVENT_IE_CEL_USEREVENT_NAME, AST_EVENT_IE_END, AST_EVENT_IE_PLTYPE_STR, AST_EVENT_IE_PLTYPE_UINT, ast_event_new(), AST_TEST_FAIL, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_test_status_update, check_event(), sip_to_pjsip::info(), NULL, str, TEST_EXECUTE, TEST_INIT, and type.
 {
    enum ast_test_result_state res = AST_TEST_PASS;
    struct ast_event *event = NULL, *event2 = NULL;
    static const enum ast_event_type type = AST_EVENT_CUSTOM;
    static const char str[] = "SIP/alligatormittens";
    static const uint32_t uint = 0xb00bface;
    switch (cmd) {
    case TEST_INIT:
       info->name = "ast_event_new_test";
       info->category = "/main/event/";
       info->summary = "Test event creation";
       info->description =
          "This test exercises the API calls that allow allocation "
          "of an ast_event.";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    /*
     * Test 2 methods of event creation:
     *
     * 1) Dynamic via appending each IE individually.
     * 2) Statically, with all IEs in ast_event_new().
     */
    ast_test_status_update(test, "First, test dynamic event creation...\n");
    if (!(event = ast_event_new(type, AST_EVENT_IE_END))) {
       ast_test_status_update(test, "Failed to allocate ast_event object.\n");
       res = AST_TEST_FAIL;
       goto return_cleanup;
    }
    if (ast_event_append_ie_str(&event, AST_EVENT_IE_CEL_USEREVENT_NAME, str)) {
       ast_test_status_update(test, "Failed to append str IE\n");
       res = AST_TEST_FAIL;
       goto return_cleanup;
    }
    if (ast_event_append_ie_uint(&event, AST_EVENT_IE_CEL_AMAFLAGS, uint)) {
       ast_test_status_update(test, "Failed to append uint IE\n");
       res = AST_TEST_FAIL;
       goto return_cleanup;
    }
    if (check_event(event, test, type, "Custom", str, uint)) {
       ast_test_status_update(test, "Dynamically generated event broken\n");
       res = AST_TEST_FAIL;
       goto return_cleanup;
    }
    event2 = ast_event_new(type,
          AST_EVENT_IE_CEL_USEREVENT_NAME, AST_EVENT_IE_PLTYPE_STR, str,
          AST_EVENT_IE_CEL_AMAFLAGS, AST_EVENT_IE_PLTYPE_UINT, uint,
          AST_EVENT_IE_END);
    if (!event2) {
       ast_test_status_update(test, "Failed to allocate ast_event object.\n");
       res = AST_TEST_FAIL;
       goto return_cleanup;
    }
    if (check_event(event2, test, type, "Custom", str, uint)) {
       ast_test_status_update(test, "Statically generated event broken\n");
       res = AST_TEST_FAIL;
       goto return_cleanup;
    }
    if (ast_event_get_size(event) != ast_event_get_size(event2)) {
       ast_test_status_update(test, "Events expected to be identical have different size: %d != %d\n",
             (int) ast_event_get_size(event),
             (int) ast_event_get_size(event2));
       res = AST_TEST_FAIL;
       goto return_cleanup;
    }
 return_cleanup:
    if (event) {
       ast_event_destroy(event);
       event = NULL;
    }
    if (event2) {
       ast_event_destroy(event2);
       event2 = NULL;
    }
    return res;
 }
check_event()
static int check_event (struct ast_event * event, struct ast_test * test, enum ast_event_type expected_type, const char * type_name, const char * str, uint32_t uint) static
Definition at line 49 of file test_event.c.
References ast_event_get_ie_str(), ast_event_get_ie_uint(), ast_event_get_type(), AST_EVENT_IE_CEL_AMAFLAGS, AST_EVENT_IE_CEL_CIDNAME, AST_EVENT_IE_CEL_EVENT_TIME_USEC, AST_EVENT_IE_CEL_USEREVENT_NAME, ast_test_status_update, and type.
Referenced by AST_TEST_DEFINE().
 {
    enum ast_event_type type;
    const void *foo;
    /* Check #1: Ensure event type is set properly. */
    type = ast_event_get_type(event);
    if (ast_event_get_type(event) != type) {
       ast_test_status_update(test, "Expected event type: '%u', got '%u'\n",
             expected_type, type);
       return -1;
    }
    /* Check #4: Check for the string IE */
    if (strcmp(str, ast_event_get_ie_str(event, AST_EVENT_IE_CEL_USEREVENT_NAME))) {
       ast_test_status_update(test, "Failed to get string IE.\n");
       return -1;
    }
    /* Check #5: Check for the uint IE */
    if (uint != ast_event_get_ie_uint(event, AST_EVENT_IE_CEL_AMAFLAGS)) {
       ast_test_status_update(test, "Failed to get uint IE.\n");
       return -1;
    }
    /* Check #6: Check if a check for a str IE that isn't there works */
    if ((foo = ast_event_get_ie_str(event, AST_EVENT_IE_CEL_CIDNAME))) {
       ast_test_status_update(test, "CEL_CIDNAME IE check returned non-NULL %p\n", foo);
       return -1;
    }
    /* Check #7: Check if a check for a uint IE that isn't there returns 0 */
    if (ast_event_get_ie_uint(event, AST_EVENT_IE_CEL_EVENT_TIME_USEC)) {
       ast_test_status_update(test, "UNIQUEID IE should be 0\n");
       return -1;
    }
    ast_test_status_update(test, "Event looks good.\n");
    return 0;
 }
load_module()
static int load_module (void) static
Definition at line 201 of file test_event.c.
References AST_MODULE_LOAD_SUCCESS, and AST_TEST_REGISTER.
 {
    AST_TEST_REGISTER(event_new_test);
    return AST_MODULE_LOAD_SUCCESS;
 }
unload_module()
static int unload_module (void) static
Definition at line 194 of file test_event.c.
References AST_TEST_UNREGISTER.
 {
    AST_TEST_UNREGISTER(event_new_test);
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "ast_event API Tests" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, } static
Definition at line 208 of file test_event.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 208 of file test_event.c.