Asterisk - The Open Source Telephony Project: endpoints.c File Reference
main/endpoints.c File Reference
Asterisk endpoint API.
#include "asterisk.h"
#include "asterisk/astobj2.h"
#include "asterisk/endpoints.h"
#include "asterisk/stasis.h"
#include "asterisk/stasis_channels.h"
#include "asterisk/stasis_endpoints.h"
#include "asterisk/stasis_message_router.h"
#include "asterisk/stringfields.h"
#include "asterisk/_private.h"
Data Structures
struct ast_endpoint
Macros
#define ENDPOINT_BUCKETS 127
#define ENDPOINT_CHANNEL_BUCKETS 127
#define TECH_ENDPOINT_BUCKETS 11
Functions
int ast_endpoint_add_channel (struct ast_endpoint *endpoint, struct ast_channel *chan)
Adds a channel to the given endpoint.
struct ast_endpoint * ast_endpoint_create (const char *tech, const char *resource)
Create an endpoint struct.
struct ast_endpoint * ast_endpoint_find_by_id (const char *id)
Finds the endpoint with the given tech[/resource] id.
const char * ast_endpoint_get_id (const struct ast_endpoint *endpoint)
Gets the tech/resource id of the given endpoint.
const char * ast_endpoint_get_resource (const struct ast_endpoint *endpoint)
Gets the resource name of the given endpoint.
enum ast_endpoint_state ast_endpoint_get_state (const struct ast_endpoint *endpoint)
Gets the state of the given endpoint.
const char * ast_endpoint_get_tech (const struct ast_endpoint *endpoint)
Gets the technology of the given endpoint.
int ast_endpoint_init (void)
Endpoint support initialization.
void ast_endpoint_set_max_channels (struct ast_endpoint *endpoint, int max_channels)
Updates the maximum number of channels an endpoint supports.
void ast_endpoint_set_state (struct ast_endpoint *endpoint, enum ast_endpoint_state state)
Updates the state of the given endpoint.
void ast_endpoint_shutdown (struct ast_endpoint *endpoint)
Shutsdown an ast_endpoint.
struct ast_endpoint_snapshot * ast_endpoint_snapshot_create (struct ast_endpoint *endpoint)
Create a snapshot of an endpoint.
const char * ast_endpoint_state_to_string (enum ast_endpoint_state state)
Returns a string representation of the given endpoint state.
struct stasis_topic * ast_endpoint_topic (struct ast_endpoint *endpoint)
Returns the topic for a specific endpoint.
struct stasis_topic * ast_endpoint_topic_cached (struct ast_endpoint *endpoint)
Returns the topic for a specific endpoint.
static struct stasis_message * create_endpoint_snapshot_message (struct ast_endpoint *endpoint)
static void endpoint_cache_clear (void *data, struct stasis_subscription *sub, struct stasis_message *message)
Handler for channel snapshot update.
static void endpoint_cleanup (void)
static void endpoint_dtor (void *obj)
static struct ast_endpoint * endpoint_internal_create (const char *tech, const char *resource)
static void endpoint_publish_snapshot (struct ast_endpoint *endpoint)
static void endpoint_snapshot_dtor (void *obj)
static void endpoint_subscription_change (void *data, struct stasis_subscription *sub, struct stasis_message *message)
Variables
static struct ao2_container * endpoints
static struct ao2_container * tech_endpoints
Detailed Description
Asterisk endpoint API.
Author
David M. Lee, II dlee@.nosp@m.digi.nosp@m.um.co.nosp@m.m
Definition in file main/endpoints.c.
Macro Definition Documentation
ENDPOINT_BUCKETS
#define ENDPOINT_BUCKETS 127
Buckets for endpoint hash. Keep it prime!
Definition at line 45 of file main/endpoints.c.
Referenced by ast_endpoint_init().
ENDPOINT_CHANNEL_BUCKETS
#define ENDPOINT_CHANNEL_BUCKETS 127
Buckets for endpoint->channel mappings. Keep it prime!
Definition at line 42 of file main/endpoints.c.
Referenced by endpoint_internal_create().
TECH_ENDPOINT_BUCKETS
#define TECH_ENDPOINT_BUCKETS 11
Buckets for technology endpoints.
Definition at line 48 of file main/endpoints.c.
Referenced by ast_endpoint_init().
Function Documentation
ast_endpoint_add_channel()
int ast_endpoint_add_channel (struct ast_endpoint * endpoint, struct ast_channel * chan)
Adds a channel to the given endpoint.
Since
12 This updates the endpoint's statistics, as well as forwarding all of the channel's messages to the endpoint's topic.
The channel is automagically removed from the endpoint when it is disposed of.
Parameters
endpoint
chan Channel.
Return values
0 on success.
Non-zero on error.
Definition at line 164 of file main/endpoints.c.
References ao2_lock, ao2_unlock, ast_assert, ast_channel_forward_endpoint(), ast_channel_uniqueid(), ast_str_container_add(), ast_strlen_zero, ast_endpoint::channel_ids, endpoint_publish_snapshot(), NULL, and ast_endpoint::resource.
Referenced by __ast_channel_alloc_ap(), and AST_TEST_DEFINE().
 {
    ast_assert(chan != NULL);
    ast_assert(endpoint != NULL);
    ast_assert(!ast_strlen_zero(endpoint->resource));
    ast_channel_forward_endpoint(chan, endpoint);
    ao2_lock(endpoint);
    ast_str_container_add(endpoint->channel_ids, ast_channel_uniqueid(chan));
    ao2_unlock(endpoint);
    endpoint_publish_snapshot(endpoint);
    return 0;
 }
ast_endpoint_create()
struct ast_endpoint* ast_endpoint_create (const char * tech, const char * resource)
Create an endpoint struct.
The endpoint is created with a state of UNKNOWN and max_channels of -1 (unlimited). While ast_endpoint is AO2 managed, you have to shut it down with ast_endpoint_shutdown() to clean up references from subscriptions.
Parameters
tech Technology for this endpoint.
resource Name of this endpoint.
Returns
Newly created endpoint.
NULL on error.
Since
12
Definition at line 319 of file main/endpoints.c.
References ast_log, ast_strlen_zero, endpoint_internal_create(), LOG_ERROR, and NULL.
Referenced by AST_TEST_DEFINE(), build_peer(), persistent_endpoint_find_or_create(), register_verify(), skinny_device_alloc(), and xmpp_client_alloc().
 {
    if (ast_strlen_zero(tech)) {
       ast_log(LOG_ERROR, "Endpoint tech cannot be empty\n");
       return NULL;
    }
    if (ast_strlen_zero(resource)) {
       ast_log(LOG_ERROR, "Endpoint resource cannot be empty\n");
       return NULL;
    }
    return endpoint_internal_create(tech, resource);
 }
ast_endpoint_find_by_id()
struct ast_endpoint* ast_endpoint_find_by_id (const char * id)
Finds the endpoint with the given tech[/resource] id.
Endpoints are refcounted, so ao2_cleanup() when you're done.
Note
The resource portion of an ID is optional. If not provided, an aggregate endpoint for the entire technology is returned. These endpoints must not be modified, but can be subscribed to in order to receive updates for all endpoints of a given technology.
Parameters
id Tech[/resource] id to look for.
Returns
Associated endpoint.
NULL if not found.
Since
12
Definition at line 82 of file main/endpoints.c.
References ao2_find, and OBJ_KEY.
Referenced by ast_ari_endpoints_list_by_tech(), endpoint_find(), and messaging_app_unsubscribe_endpoint().
 {
    struct ast_endpoint *endpoint = ao2_find(endpoints, id, OBJ_KEY);
    if (!endpoint) {
       endpoint = ao2_find(tech_endpoints, id, OBJ_KEY);
    }
    return endpoint;
 }
ast_endpoint_get_id()
const char* ast_endpoint_get_id (const struct ast_endpoint * endpoint)
Gets the tech/resource id of the given endpoint.
This is unique across all endpoints, and immutable.
Parameters
endpoint The endpoint.
Returns
Tech/resource id of the endpoint.
NULL if endpoint is NULL.
Since
12
Definition at line 391 of file main/endpoints.c.
References ast_endpoint::id, and NULL.
Referenced by app_subscribe_endpoint(), forwards_create_endpoint(), get_or_create_subscription(), get_subscription(), messaging_app_subscribe_endpoint(), and messaging_app_unsubscribe_endpoint().
 {
    if (!endpoint) {
       return NULL;
    }
    return endpoint->id;
 }
ast_endpoint_get_resource()
const char* ast_endpoint_get_resource (const struct ast_endpoint * endpoint)
Gets the resource name of the given endpoint.
This is unique for the endpoint's technology, and immutable.
Note
If the endpoint being queried is a technology aggregate endpoint, this will be an empty string.
Parameters
endpoint The endpoint.
Returns
Resource name of the endpoint.
NULL if endpoint is NULL.
Since
12
Definition at line 383 of file main/endpoints.c.
References NULL, and ast_endpoint::resource.
Referenced by add_to_regcontext(), ast_sip_get_endpoint_snapshot(), ast_sip_persistent_endpoint_publish_contact_state(), ast_sip_persistent_endpoint_update_state(), AST_TEST_DEFINE(), chan_pjsip_devicestate(), endpoint_deleted_observer(), get_or_create_subscription(), get_subscription(), messaging_app_unsubscribe_endpoint(), persistent_endpoint_cmp(), and persistent_endpoint_hash().
 {
    if (!endpoint) {
       return NULL;
    }
    return endpoint->resource;
 }
ast_endpoint_get_state()
enum ast_endpoint_state ast_endpoint_get_state (const struct ast_endpoint * endpoint)
Gets the state of the given endpoint.
Parameters
endpoint The endpoint.
Returns
state.
AST_ENDPOINT_UNKNOWN if endpoint is NULL.
Since
13.4
Definition at line 399 of file main/endpoints.c.
References AST_ENDPOINT_UNKNOWN, and ast_endpoint::state.
Referenced by add_to_regcontext(), and ast_sip_persistent_endpoint_update_state().
 {
    if (!endpoint) {
       return AST_ENDPOINT_UNKNOWN;
    }
    return endpoint->state;
 }
ast_endpoint_get_tech()
const char* ast_endpoint_get_tech (const struct ast_endpoint * endpoint)
Gets the technology of the given endpoint.
This is an immutable string describing the channel provider technology (SIP, IAX2, etc.).
Parameters
endpoint The endpoint.
Returns
Tec of the endpoint.
NULL if endpoint is NULL.
Since
12
Definition at line 375 of file main/endpoints.c.
References NULL, and ast_endpoint::tech.
Referenced by ast_sip_get_endpoint_snapshot(), AST_TEST_DEFINE(), chan_pjsip_devicestate(), and get_subscription().
 {
    if (!endpoint) {
       return NULL;
    }
    return endpoint->tech;
 }
ast_endpoint_init()
int ast_endpoint_init (void)
Endpoint support initialization.
Returns
0 on success.
Non-zero on error.
Definition at line 496 of file main/endpoints.c.
References AO2_ALLOC_OPT_LOCK_MUTEX, ao2_container_alloc_hash, ast_register_cleanup(), ENDPOINT_BUCKETS, endpoint_cleanup(), NULL, and TECH_ENDPOINT_BUCKETS.
Referenced by asterisk_daemon().
 {
    ast_register_cleanup(endpoint_cleanup);
    endpoints = ao2_container_alloc_hash(AO2_ALLOC_OPT_LOCK_MUTEX, 0, ENDPOINT_BUCKETS,
       ast_endpoint_hash_fn, NULL, ast_endpoint_cmp_fn);
    if (!endpoints) {
       return -1;
    }
    tech_endpoints = ao2_container_alloc_hash(AO2_ALLOC_OPT_LOCK_MUTEX, 0,
       TECH_ENDPOINT_BUCKETS, ast_endpoint_hash_fn, NULL, ast_endpoint_cmp_fn);
    if (!tech_endpoints) {
       return -1;
    }
    return 0;
 }
ast_endpoint_set_max_channels()
void ast_endpoint_set_max_channels (struct ast_endpoint * endpoint, int max_channels)
Updates the maximum number of channels an endpoint supports.
Set to -1 for unlimited channels.
Parameters
endpoint Endpoint to modify.
max_channels Maximum number of concurrent channels this endpoint supports.
Definition at line 419 of file main/endpoints.c.
References ao2_lock, ao2_unlock, ast_assert, ast_strlen_zero, endpoint_publish_snapshot(), ast_endpoint::max_channels, NULL, and ast_endpoint::resource.
Referenced by AST_TEST_DEFINE().
 {
    ast_assert(endpoint != NULL);
    ast_assert(!ast_strlen_zero(endpoint->resource));
    ao2_lock(endpoint);
    endpoint->max_channels = max_channels;
    ao2_unlock(endpoint);
    endpoint_publish_snapshot(endpoint);
 }
ast_endpoint_set_state()
void ast_endpoint_set_state (struct ast_endpoint * endpoint, enum ast_endpoint_state state)
Updates the state of the given endpoint.
Parameters
endpoint Endpoint to modify.
state New state.
Since
12
Definition at line 407 of file main/endpoints.c.
References ao2_lock, ao2_unlock, ast_assert, ast_strlen_zero, endpoint_publish_snapshot(), NULL, ast_endpoint::resource, and ast_endpoint::state.
Referenced by __expire_registry(), __iax2_poke_noanswer(), ast_sip_persistent_endpoint_update_state(), AST_TEST_DEFINE(), expire_register(), handle_response_peerpoke(), parse_register_contact(), persistent_endpoint_find_or_create(), register_verify(), sip_poke_noanswer(), skinny_register(), skinny_session_cleanup(), socket_process_helper(), unload_module(), update_registry(), and xmpp_client_change_state().
 {
    ast_assert(endpoint != NULL);
    ast_assert(!ast_strlen_zero(endpoint->resource));
    ao2_lock(endpoint);
    endpoint->state = state;
    ao2_unlock(endpoint);
    endpoint_publish_snapshot(endpoint);
 }
ast_endpoint_shutdown()
void ast_endpoint_shutdown (struct ast_endpoint * endpoint)
Shutsdown an ast_endpoint.
Parameters
endpoint Endpoint to shut down.
Since
12
Definition at line 350 of file main/endpoints.c.
References ao2_cleanup, ao2_ref, ao2_unlink, ast_endpoint_topic(), create_endpoint_snapshot_message(), NULL, RAII_VAR, ast_endpoint::router, stasis_cache_clear_create(), stasis_forward_cancel(), stasis_message_router_unsubscribe(), stasis_publish(), and ast_endpoint::tech_forward.
Referenced by AST_TEST_DEFINE(), peer_destructor(), persistent_endpoint_destroy(), sip_destroy_peer(), skinny_device_destroy(), and xmpp_client_destructor().
 {
    RAII_VAR(struct stasis_message *, clear_msg, NULL, ao2_cleanup);
    if (endpoint == NULL) {
       return;
    }
    ao2_unlink(endpoints, endpoint);
    endpoint->tech_forward = stasis_forward_cancel(endpoint->tech_forward);
    clear_msg = create_endpoint_snapshot_message(endpoint);
    if (clear_msg) {
       RAII_VAR(struct stasis_message *, message, NULL, ao2_cleanup);
       message = stasis_cache_clear_create(clear_msg);
       if (message) {
          stasis_publish(ast_endpoint_topic(endpoint), message);
       }
    }
    /* Bump refcount to hold on to the router */
    ao2_ref(endpoint->router, +1);
    stasis_message_router_unsubscribe(endpoint->router);
 }
ast_endpoint_state_to_string()
const char* ast_endpoint_state_to_string (enum ast_endpoint_state state)
Returns a string representation of the given endpoint state.
Parameters
state Endpoint state.
Returns
String representation of state.
"?" if state isn't in ast_endpoint_state.
Definition at line 109 of file main/endpoints.c.
References AST_ENDPOINT_OFFLINE, AST_ENDPOINT_ONLINE, and AST_ENDPOINT_UNKNOWN.
Referenced by ast_endpoint_snapshot_to_json().
 {
    switch (state) {
    case AST_ENDPOINT_UNKNOWN:
       return "unknown";
    case AST_ENDPOINT_OFFLINE:
       return "offline";
    case AST_ENDPOINT_ONLINE:
       return "online";
    }
    return "?";
 }
create_endpoint_snapshot_message()
static struct stasis_message* create_endpoint_snapshot_message (struct ast_endpoint * endpoint) static
Definition at line 334 of file main/endpoints.c.
References ao2_cleanup, ast_endpoint_snapshot_create(), ast_endpoint_snapshot_type(), NULL, RAII_VAR, and stasis_message_create().
Referenced by ast_endpoint_shutdown().
 {
    RAII_VAR(struct ast_endpoint_snapshot *, snapshot, NULL, ao2_cleanup);
    if (!ast_endpoint_snapshot_type()) {
       return NULL;
    }
    snapshot = ast_endpoint_snapshot_create(endpoint);
    if (!snapshot) {
       return NULL;
    }
    return stasis_message_create(ast_endpoint_snapshot_type(), snapshot);
 }
endpoint_cache_clear()
static void endpoint_cache_clear (void * data, struct stasis_subscription * sub, struct stasis_message * message) static
Handler for channel snapshot update.
Definition at line 183 of file main/endpoints.c.
References ao2_lock, ao2_unlock, ast_assert, AST_FLAG_DEAD, ast_str_container_remove(), ast_test_flag, ast_channel_snapshot::base, ast_endpoint::channel_ids, endpoint_publish_snapshot(), ast_channel_snapshot::flags, ast_channel_snapshot_update::new_snapshot, NULL, stasis_message_data(), ast_channel_snapshot_base::uniqueid, and update().
Referenced by endpoint_internal_create().
 {
    struct ast_endpoint *endpoint = data;
    struct ast_channel_snapshot_update *update = stasis_message_data(message);
    /* Only when the channel is dead do we remove it */
    if (!ast_test_flag(&update->new_snapshot->flags, AST_FLAG_DEAD)) {
       return;
    }
    ast_assert(endpoint != NULL);
    ao2_lock(endpoint);
    ast_str_container_remove(endpoint->channel_ids, update->new_snapshot->base->uniqueid);
    ao2_unlock(endpoint);
    endpoint_publish_snapshot(endpoint);
 }
endpoint_cleanup()
static void endpoint_cleanup (void) static
Definition at line 487 of file main/endpoints.c.
References ao2_cleanup, and NULL.
Referenced by ast_endpoint_init().
 {
    ao2_cleanup(endpoints);
    endpoints = NULL;
    ao2_cleanup(tech_endpoints);
    tech_endpoints = NULL;
 }
endpoint_dtor()
static void endpoint_dtor (void * obj) static
Definition at line 145 of file main/endpoints.c.
References ao2_cleanup, ast_assert, ast_string_field_free_memory, ast_endpoint::channel_ids, NULL, ast_endpoint::router, stasis_cp_single_unsubscribe(), stasis_message_router_is_done(), and ast_endpoint::topics.
Referenced by endpoint_internal_create().
 {
    struct ast_endpoint *endpoint = obj;
    /* The router should be shut down already */
    ast_assert(stasis_message_router_is_done(endpoint->router));
    ao2_cleanup(endpoint->router);
    endpoint->router = NULL;
    stasis_cp_single_unsubscribe(endpoint->topics);
    endpoint->topics = NULL;
    ao2_cleanup(endpoint->channel_ids);
    endpoint->channel_ids = NULL;
    ast_string_field_free_memory(endpoint);
 }
endpoint_internal_create()
static struct ast_endpoint* endpoint_internal_create (const char * tech, const char * resource) static
Definition at line 214 of file main/endpoints.c.
References ao2_alloc, AO2_ALLOC_OPT_LOCK_NOLOCK, ao2_cleanup, ao2_find, ao2_link, ao2_ref, ast_asprintf, ast_channel_snapshot_type(), ast_endpoint_cache_all(), ast_endpoint_snapshot_type(), ast_endpoint_topic(), AST_ENDPOINT_UNKNOWN, ast_free, ast_str_container_alloc_options(), ast_string_field_build, ast_string_field_init, ast_string_field_set, ast_strlen_zero, endpoint_cache_clear(), ENDPOINT_CHANNEL_BUCKETS, endpoint_dtor(), endpoint_publish_snapshot(), endpoint_subscription_change(), NULL, OBJ_KEY, RAII_VAR, S_OR, stasis_cp_single_accept_message_type(), stasis_cp_single_create(), stasis_cp_single_set_filter(), stasis_cp_single_topic(), stasis_cp_sink_create(), stasis_forward_all(), stasis_message_router_add(), stasis_message_router_create_pool, stasis_subscription_change_type(), and STASIS_SUBSCRIPTION_FILTER_SELECTIVE.
Referenced by ast_endpoint_create().
 {
    RAII_VAR(struct ast_endpoint *, endpoint, NULL, ao2_cleanup);
    RAII_VAR(struct ast_endpoint *, tech_endpoint, NULL, ao2_cleanup);
    int r = 0;
    /* Get/create the technology endpoint */
    if (!ast_strlen_zero(resource)) {
       tech_endpoint = ao2_find(tech_endpoints, tech, OBJ_KEY);
       if (!tech_endpoint) {
          tech_endpoint = endpoint_internal_create(tech, NULL);
          if (!tech_endpoint) {
             return NULL;
          }
       }
    }
    endpoint = ao2_alloc(sizeof(*endpoint), endpoint_dtor);
    if (!endpoint) {
       return NULL;
    }
    endpoint->max_channels = -1;
    endpoint->state = AST_ENDPOINT_UNKNOWN;
    if (ast_string_field_init(endpoint, 80) != 0) {
       return NULL;
    }
    ast_string_field_set(endpoint, tech, tech);
    ast_string_field_set(endpoint, resource, S_OR(resource, ""));
    ast_string_field_build(endpoint, id, "%s%s%s",
       tech,
       !ast_strlen_zero(resource) ? "/" : "",
       S_OR(resource, ""));
    /* All access to channel_ids should be covered by the endpoint's
     * lock; no extra lock needed. */
    endpoint->channel_ids = ast_str_container_alloc_options(
       AO2_ALLOC_OPT_LOCK_NOLOCK, ENDPOINT_CHANNEL_BUCKETS);
    if (!endpoint->channel_ids) {
       return NULL;
    }
    if (!ast_strlen_zero(resource)) {
       char *topic_name;
       int ret;
       ret = ast_asprintf(&topic_name, "endpoint:%s", endpoint->id);
       if (ret < 0) {
          return NULL;
       }
       endpoint->topics = stasis_cp_single_create(ast_endpoint_cache_all(),
          topic_name);
       ast_free(topic_name);
       if (!endpoint->topics) {
          return NULL;
       }
       stasis_cp_single_accept_message_type(endpoint->topics, ast_endpoint_snapshot_type());
       stasis_cp_single_set_filter(endpoint->topics, STASIS_SUBSCRIPTION_FILTER_SELECTIVE);
       endpoint->router = stasis_message_router_create_pool(ast_endpoint_topic(endpoint));
       if (!endpoint->router) {
          return NULL;
       }
       r |= stasis_message_router_add(endpoint->router,
          ast_channel_snapshot_type(), endpoint_cache_clear,
          endpoint);
       r |= stasis_message_router_add(endpoint->router,
          stasis_subscription_change_type(), endpoint_subscription_change,
          endpoint);
       if (r) {
          return NULL;
       }
       endpoint->tech_forward = stasis_forward_all(stasis_cp_single_topic(endpoint->topics),
          stasis_cp_single_topic(tech_endpoint->topics));
       endpoint_publish_snapshot(endpoint);
       ao2_link(endpoints, endpoint);
    } else {
       char *topic_name;
       int ret;
       ret = ast_asprintf(&topic_name, "endpoint:%s", endpoint->id);
       if (ret < 0) {
          return NULL;
       }
       endpoint->topics = stasis_cp_sink_create(ast_endpoint_cache_all(),
          topic_name);
       ast_free(topic_name);
       if (!endpoint->topics) {
          return NULL;
       }
       stasis_cp_single_accept_message_type(endpoint->topics, ast_endpoint_snapshot_type());
       stasis_cp_single_set_filter(endpoint->topics, STASIS_SUBSCRIPTION_FILTER_SELECTIVE);
       ao2_link(tech_endpoints, endpoint);
    }
    ao2_ref(endpoint, +1);
    return endpoint;
 }
endpoint_publish_snapshot()
static void endpoint_publish_snapshot (struct ast_endpoint * endpoint) static
Definition at line 122 of file main/endpoints.c.
References ao2_cleanup, ast_assert, ast_endpoint_snapshot_create(), ast_endpoint_snapshot_type(), ast_endpoint_topic(), NULL, RAII_VAR, stasis_message_create(), stasis_publish(), and ast_endpoint::topics.
Referenced by ast_endpoint_add_channel(), ast_endpoint_set_max_channels(), ast_endpoint_set_state(), endpoint_cache_clear(), and endpoint_internal_create().
 {
    RAII_VAR(struct ast_endpoint_snapshot *, snapshot, NULL, ao2_cleanup);
    RAII_VAR(struct stasis_message *, message, NULL, ao2_cleanup);
    ast_assert(endpoint != NULL);
    ast_assert(endpoint->topics != NULL);
    if (!ast_endpoint_snapshot_type()) {
       return;
    }
    snapshot = ast_endpoint_snapshot_create(endpoint);
    if (!snapshot) {
       return;
    }
    message = stasis_message_create(ast_endpoint_snapshot_type(), snapshot);
    if (!message) {
       return;
    }
    stasis_publish(ast_endpoint_topic(endpoint), message);
 }
endpoint_snapshot_dtor()
static void endpoint_snapshot_dtor (void * obj) static
Definition at line 431 of file main/endpoints.c.
References ao2_ref, ast_assert, ast_string_field_free_memory, ast_endpoint_snapshot::channel_ids, NULL, and ast_endpoint_snapshot::num_channels.
Referenced by ast_endpoint_snapshot_create().
 {
    struct ast_endpoint_snapshot *snapshot = obj;
    int channel;
    ast_assert(snapshot != NULL);
    for (channel = 0; channel < snapshot->num_channels; channel++) {
       ao2_ref(snapshot->channel_ids[channel], -1);
    }
    ast_string_field_free_memory(snapshot);
 }
endpoint_subscription_change()
static void endpoint_subscription_change (void * data, struct stasis_subscription * sub, struct stasis_message * message) static
Definition at line 203 of file main/endpoints.c.
References ao2_cleanup, and stasis_subscription_final_message().
Referenced by endpoint_internal_create().
 {
    struct stasis_endpoint *endpoint = data;
    if (stasis_subscription_final_message(sub, message)) {
       ao2_cleanup(endpoint);
    }
 }
Variable Documentation
endpoints
struct ao2_container* endpoints static
Definition at line 50 of file main/endpoints.c.
Referenced by ami_registrations_endpoints(), ami_show_endpoints(), app_to_json(), ast_sip_get_endpoints(), cli_complete_endpoint(), create_mwi_subscriptions(), endpoints_scrape_cb(), load_all_endpoints(), load_module(), sip_options_aor_observer_modified_task(), stasis_app_to_cli(), and unload_module().
tech_endpoints
struct ao2_container* tech_endpoints static
Definition at line 52 of file main/endpoints.c.