Asterisk - The Open Source Telephony Project: log2comp.h File Reference
log2comp.h File Reference
log2comp.h - various base 2 log computation versions
Macros
#define inline __inline__
Functions
static int ilog2 (int val)
Detailed Description
log2comp.h - various base 2 log computation versions
Asterisk – An open source telephony toolkit.
Author
Alex Volkov codep.nosp@m.ro@u.nosp@m.sa.ne.nosp@m.t
Copyright (c) 2004 - 2005, Digium Inc.
This program is free software, distributed under the terms of the GNU General Public License
Define WANT_ASM before including this file to use assembly whenever possible
Definition in file log2comp.h.
Macro Definition Documentation
inline
#define inline __inline__
Definition at line 20 of file log2comp.h.
Function Documentation
ilog2()
static int ilog2 (int val) inline static
Definition at line 67 of file log2comp.h.
Referenced by fmult(), quantize(), and update().
 {
    int i;
    for (i = -1; val; ++i, val >>= 1)
       ;
    return (i);
 }