Asterisk - The Open Source Telephony Project: test_sched.c File Reference
test_sched.c File Reference
ast_sched performance test module
#include "asterisk.h"
#include <inttypes.h>
#include "asterisk/module.h"
#include "asterisk/utils.h"
#include "asterisk/sched.h"
#include "asterisk/test.h"
#include "asterisk/cli.h"
Macros
#define DELAYED_SAME_EXPIRE 300 /* ms */
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
AST_TEST_DEFINE (sched_test_order)
static char * handle_cli_sched_bench (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static int load_module (void)
static int sched_cb (const void *data)
static int sched_order_1_cb (const void *data)
static int sched_order_2_cb (const void *data)
static int sched_order_3_cb (const void *data)
static int sched_order_4_cb (const void *data)
static int sched_order_5_cb (const void *data)
static int sched_order_6_cb (const void *data)
static int sched_order_7_cb (const void *data)
static int sched_order_8_cb (const void *data)
static void sched_order_check (struct ast_test *test, int order)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "ast_sched performance test module" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, }
static const struct ast_module_info * ast_module_info = &__mod_info
static struct ast_cli_entry cli_sched []
static int order_check
static int order_check_failed
Detailed Description
ast_sched performance test module
Author
Russell Bryant russe.nosp@m.ll@d.nosp@m.igium.nosp@m..com
Definition in file test_sched.c.
Macro Definition Documentation
DELAYED_SAME_EXPIRE
#define DELAYED_SAME_EXPIRE 300 /* ms */
Referenced by AST_TEST_DEFINE().
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 357 of file test_sched.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 357 of file test_sched.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 357 of file test_sched.c.
AST_TEST_DEFINE()
AST_TEST_DEFINE (sched_test_order)
Definition at line 107 of file test_sched.c.
References ast_sched_add(), ast_sched_context_create(), ast_sched_context_destroy(), ast_sched_del(), ast_sched_runq(), ast_sched_wait(), AST_TEST_FAIL, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_test_status_update, DELAYED_SAME_EXPIRE, sip_to_pjsip::info(), NULL, order_check, order_check_failed, sched_cb(), sched_order_1_cb(), sched_order_2_cb(), sched_order_3_cb(), sched_order_4_cb(), sched_order_5_cb(), sched_order_6_cb(), sched_order_7_cb(), sched_order_8_cb(), TEST_EXECUTE, and TEST_INIT.
 {
    struct ast_sched_context *con;
    enum ast_test_result_state res = AST_TEST_FAIL;
    int id1, id2, id3, wait;
    switch (cmd) {
    case TEST_INIT:
       info->name = "sched_test_order";
       info->category = "/main/sched/";
       info->summary = "Test ordering of events in the scheduler API";
       info->description =
          "This test ensures that events are properly ordered by the "
          "time they are scheduled to execute in the scheduler API.";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    if (!(con = ast_sched_context_create())) {
       ast_test_status_update(test,
             "Test failed - could not create scheduler context\n");
       return AST_TEST_FAIL;
    }
    /* Add 3 scheduler entries, and then remove them, ensuring that the result
     * of ast_sched_wait() looks appropriate at each step along the way. */
    if ((wait = ast_sched_wait(con)) != -1) {
       ast_test_status_update(test,
             "ast_sched_wait() should have returned -1, returned '%d'\n",
             wait);
       goto return_cleanup;
    }
    if ((id1 = ast_sched_add(con, 100000, sched_cb, NULL)) == -1) {
       ast_test_status_update(test, "Failed to add scheduler entry\n");
       goto return_cleanup;
    }
    if ((wait = ast_sched_wait(con)) > 100000) {
       ast_test_status_update(test,
             "ast_sched_wait() should have returned <= 100000, returned '%d'\n",
             wait);
       goto return_cleanup;
    }
    if ((id2 = ast_sched_add(con, 10000, sched_cb, NULL)) == -1) {
       ast_test_status_update(test, "Failed to add scheduler entry\n");
       goto return_cleanup;
    }
    if ((wait = ast_sched_wait(con)) > 10000) {
       ast_test_status_update(test,
             "ast_sched_wait() should have returned <= 10000, returned '%d'\n",
             wait);
       goto return_cleanup;
    }
    if ((id3 = ast_sched_add(con, 1000, sched_cb, NULL)) == -1) {
       ast_test_status_update(test, "Failed to add scheduler entry\n");
       goto return_cleanup;
    }
    if ((wait = ast_sched_wait(con)) > 1000) {
       ast_test_status_update(test,
             "ast_sched_wait() should have returned <= 1000, returned '%d'\n",
             wait);
       goto return_cleanup;
    }
    if (ast_sched_del(con, id3) == -1) {
       ast_test_status_update(test, "Failed to remove scheduler entry\n");
       goto return_cleanup;
    }
    if ((wait = ast_sched_wait(con)) <= 1000) {
       ast_test_status_update(test,
             "ast_sched_wait() should have returned > 1000, returned '%d'\n",
             wait);
       goto return_cleanup;
    }
    if (ast_sched_del(con, id2) == -1) {
       ast_test_status_update(test, "Failed to remove scheduler entry\n");
       goto return_cleanup;
    }
    if ((wait = ast_sched_wait(con)) <= 10000) {
       ast_test_status_update(test,
             "ast_sched_wait() should have returned > 10000, returned '%d'\n",
             wait);
       goto return_cleanup;
    }
    if (ast_sched_del(con, id1) == -1) {
       ast_test_status_update(test, "Failed to remove scheduler entry\n");
       goto return_cleanup;
    }
    if ((wait = ast_sched_wait(con)) != -1) {
       ast_test_status_update(test,
             "ast_sched_wait() should have returned -1, returned '%d'\n",
             wait);
       goto return_cleanup;
    }
    /*
     * Schedule immediate and delayed entries to check the order
     * that they get executed.  They must get executed at the
     * time they expire in the order they were added.
     */
 #define DELAYED_SAME_EXPIRE      300 /* ms */
    ast_test_validate_cleanup(test, -1 < ast_sched_add(con, DELAYED_SAME_EXPIRE, sched_order_1_cb, test), res, return_cleanup);
    ast_test_validate_cleanup(test, -1 < ast_sched_add(con, 0, sched_order_1_cb, test), res, return_cleanup);
    ast_test_validate_cleanup(test, -1 < ast_sched_add(con, DELAYED_SAME_EXPIRE, sched_order_2_cb, test), res, return_cleanup);
    ast_test_validate_cleanup(test, -1 < ast_sched_add(con, 0, sched_order_2_cb, test), res, return_cleanup);
    ast_test_validate_cleanup(test, -1 < ast_sched_add(con, DELAYED_SAME_EXPIRE, sched_order_3_cb, test), res, return_cleanup);
    ast_test_validate_cleanup(test, -1 < ast_sched_add(con, 0, sched_order_3_cb, test), res, return_cleanup);
    ast_test_validate_cleanup(test, -1 < ast_sched_add(con, DELAYED_SAME_EXPIRE, sched_order_4_cb, test), res, return_cleanup);
    ast_test_validate_cleanup(test, -1 < ast_sched_add(con, 0, sched_order_4_cb, test), res, return_cleanup);
    ast_test_validate_cleanup(test, -1 < ast_sched_add(con, DELAYED_SAME_EXPIRE, sched_order_5_cb, test), res, return_cleanup);
    ast_test_validate_cleanup(test, -1 < ast_sched_add(con, 0, sched_order_5_cb, test), res, return_cleanup);
    ast_test_validate_cleanup(test, -1 < ast_sched_add(con, DELAYED_SAME_EXPIRE, sched_order_6_cb, test), res, return_cleanup);
    ast_test_validate_cleanup(test, -1 < ast_sched_add(con, 0, sched_order_6_cb, test), res, return_cleanup);
    ast_test_validate_cleanup(test, -1 < ast_sched_add(con, DELAYED_SAME_EXPIRE, sched_order_7_cb, test), res, return_cleanup);
    ast_test_validate_cleanup(test, -1 < ast_sched_add(con, 0, sched_order_7_cb, test), res, return_cleanup);
    ast_test_validate_cleanup(test, -1 < ast_sched_add(con, DELAYED_SAME_EXPIRE, sched_order_8_cb, test), res, return_cleanup);
    /* Check order of scheduled immediate entries. */
    order_check = 0;
    order_check_failed = 0;
    usleep(50 * 1000);/* Ensure that all the immediate entries are ready to expire */
    ast_test_validate_cleanup(test, 7 == ast_sched_runq(con), res, return_cleanup);
    ast_test_validate_cleanup(test, !order_check_failed, res, return_cleanup);
    /* Check order of scheduled entries expiring at the same time. */
    order_check = 0;
    order_check_failed = 0;
    usleep((DELAYED_SAME_EXPIRE + 50) * 1000);/* Ensure that all the delayed entries are ready to expire */
    ast_test_validate_cleanup(test, 8 == ast_sched_runq(con), res, return_cleanup);
    ast_test_validate_cleanup(test, !order_check_failed, res, return_cleanup);
    if ((wait = ast_sched_wait(con)) != -1) {
       ast_test_status_update(test,
             "ast_sched_wait() should have returned -1, returned '%d'\n",
             wait);
       goto return_cleanup;
    }
    res = AST_TEST_PASS;
 return_cleanup:
    ast_sched_context_destroy(con);
    return res;
 }
handle_cli_sched_bench()
static char* handle_cli_sched_bench (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) static
Definition at line 265 of file test_sched.c.
References ast_cli_args::argc, ast_cli_entry::args, ast_cli_args::argv, ast_cli(), ast_free, ast_malloc, ast_random(), ast_sched_add(), ast_sched_context_create(), ast_sched_context_destroy(), ast_sched_del(), ast_tvdiff_us(), ast_tvnow(), CLI_FAILURE, CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::command, ast_cli_args::fd, NULL, sched_cb(), and ast_cli_entry::usage.
 {
    struct ast_sched_context *con;
    struct timeval start;
    unsigned int num, i;
    int *sched_ids = NULL;
    switch (cmd) {
    case CLI_INIT:
       e->command = "sched benchmark";
       e->usage = ""
          "Usage: sched benchmark <num>\n"
          "";
       return NULL;
    case CLI_GENERATE:
       return NULL;
    }
    if (a->argc != e->args + 1) {
       return CLI_SHOWUSAGE;
    }
    if (sscanf(a->argv[e->args], "%u", &num) != 1) {
       return CLI_SHOWUSAGE;
    }
    if (!(con = ast_sched_context_create())) {
       ast_cli(a->fd, "Test failed - could not create scheduler context\n");
       return CLI_FAILURE;
    }
    if (!(sched_ids = ast_malloc(sizeof(*sched_ids) * num))) {
       ast_cli(a->fd, "Test failed - memory allocation failure\n");
       goto return_cleanup;
    }
    ast_cli(a->fd, "Testing ast_sched_add() performance - timing how long it takes "
          "to add %u entries at random time intervals from 0 to 60 seconds\n", num);
    start = ast_tvnow();
    for (i = 0; i < num; i++) {
       long when = labs(ast_random()) % 60000;
       if ((sched_ids[i] = ast_sched_add(con, when, sched_cb, NULL)) == -1) {
          ast_cli(a->fd, "Test failed - sched_add returned -1\n");
          goto return_cleanup;
       }
    }
    ast_cli(a->fd, "Test complete - %" PRIi64 " us\n", ast_tvdiff_us(ast_tvnow(), start));
    ast_cli(a->fd, "Testing ast_sched_del() performance - timing how long it takes "
          "to delete %u entries with random time intervals from 0 to 60 seconds\n", num);
    start = ast_tvnow();
    for (i = 0; i < num; i++) {
       if (ast_sched_del(con, sched_ids[i]) == -1) {
          ast_cli(a->fd, "Test failed - sched_del returned -1\n");
          goto return_cleanup;
       }
    }
    ast_cli(a->fd, "Test complete - %" PRIi64 " us\n", ast_tvdiff_us(ast_tvnow(), start));
 return_cleanup:
    ast_sched_context_destroy(con);
    if (sched_ids) {
       ast_free(sched_ids);
    }
    return CLI_SUCCESS;
 }
load_module()
static int load_module (void) static
Definition at line 350 of file test_sched.c.
References ARRAY_LEN, ast_cli_register_multiple, AST_MODULE_LOAD_SUCCESS, and AST_TEST_REGISTER.
 {
    AST_TEST_REGISTER(sched_test_order);
    ast_cli_register_multiple(cli_sched, ARRAY_LEN(cli_sched));
    return AST_MODULE_LOAD_SUCCESS;
 }
sched_cb()
static int sched_cb (const void * data) static
Definition at line 41 of file test_sched.c.
Referenced by AST_TEST_DEFINE(), and handle_cli_sched_bench().
 {
    return 0;
 }
sched_order_1_cb()
static int sched_order_1_cb (const void * data) static
Definition at line 59 of file test_sched.c.
References sched_order_check().
Referenced by AST_TEST_DEFINE().
 {
    sched_order_check((void *) data, 1);
    return 0;
 }
sched_order_2_cb()
static int sched_order_2_cb (const void * data) static
Definition at line 65 of file test_sched.c.
References sched_order_check().
Referenced by AST_TEST_DEFINE().
 {
    sched_order_check((void *) data, 2);
    return 0;
 }
sched_order_3_cb()
static int sched_order_3_cb (const void * data) static
Definition at line 71 of file test_sched.c.
References sched_order_check().
Referenced by AST_TEST_DEFINE().
 {
    sched_order_check((void *) data, 3);
    return 0;
 }
sched_order_4_cb()
static int sched_order_4_cb (const void * data) static
Definition at line 77 of file test_sched.c.
References sched_order_check().
Referenced by AST_TEST_DEFINE().
 {
    sched_order_check((void *) data, 4);
    return 0;
 }
sched_order_5_cb()
static int sched_order_5_cb (const void * data) static
Definition at line 83 of file test_sched.c.
References sched_order_check().
Referenced by AST_TEST_DEFINE().
 {
    sched_order_check((void *) data, 5);
    return 0;
 }
sched_order_6_cb()
static int sched_order_6_cb (const void * data) static
Definition at line 89 of file test_sched.c.
References sched_order_check().
Referenced by AST_TEST_DEFINE().
 {
    sched_order_check((void *) data, 6);
    return 0;
 }
sched_order_7_cb()
static int sched_order_7_cb (const void * data) static
Definition at line 95 of file test_sched.c.
References sched_order_check().
Referenced by AST_TEST_DEFINE().
 {
    sched_order_check((void *) data, 7);
    return 0;
 }
sched_order_8_cb()
static int sched_order_8_cb (const void * data) static
Definition at line 101 of file test_sched.c.
References sched_order_check().
Referenced by AST_TEST_DEFINE().
 {
    sched_order_check((void *) data, 8);
    return 0;
 }
sched_order_check()
static void sched_order_check (struct ast_test * test, int order) static
Definition at line 49 of file test_sched.c.
References ast_test_status_update, order_check, and order_check_failed.
Referenced by sched_order_1_cb(), sched_order_2_cb(), sched_order_3_cb(), sched_order_4_cb(), sched_order_5_cb(), sched_order_6_cb(), sched_order_7_cb(), and sched_order_8_cb().
 {
    ++order_check;
    if (order_check != order) {
       ast_test_status_update(test, "Unexpected execution order: expected:%d got:%d\n",
          order, order_check);
       order_check_failed = 1;
    }
 }
unload_module()
static int unload_module (void) static
Definition at line 343 of file test_sched.c.
References ARRAY_LEN, ast_cli_unregister_multiple(), and AST_TEST_UNREGISTER.
 {
    AST_TEST_UNREGISTER(sched_test_order);
    ast_cli_unregister_multiple(cli_sched, ARRAY_LEN(cli_sched));
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "ast_sched performance test module" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, } static
Definition at line 357 of file test_sched.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 357 of file test_sched.c.
cli_sched
struct ast_cli_entry cli_sched[] static
Initial value:
= {
   { .handler =  handle_cli_sched_bench , .summary =  "Benchmark ast_sched add/del performance" ,},
}
Definition at line 339 of file test_sched.c.
order_check
int order_check static
Definition at line 46 of file test_sched.c.
Referenced by AST_TEST_DEFINE(), and sched_order_check().
order_check_failed
int order_check_failed static
Definition at line 47 of file test_sched.c.
Referenced by AST_TEST_DEFINE(), and sched_order_check().