Asterisk - The Open Source Telephony Project: app_sendtext.c File Reference
app_sendtext.c File Reference
Dial plan applications
App to transmit a text message.
#include "asterisk.h"
#include "asterisk/file.h"
#include "asterisk/channel.h"
#include "asterisk/pbx.h"
#include "asterisk/module.h"
#include "asterisk/app.h"
#include "asterisk/message.h"
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int load_module (void)
static int sendtext_exec (struct ast_channel *chan, const char *data)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Send Text Applications" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, }
static const char *const app = "SendText"
static const struct ast_module_info * ast_module_info = &__mod_info
Detailed Description
App to transmit a text message.
Author
Mark Spencer marks.nosp@m.ter@.nosp@m.digiu.nosp@m.m.co.nosp@m.m
Note
Requires support of sending text messages from channel driver
Definition in file app_sendtext.c.
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 250 of file app_sendtext.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 250 of file app_sendtext.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 250 of file app_sendtext.c.
load_module()
static int load_module (void) static
Definition at line 245 of file app_sendtext.c.
References app, ast_register_application_xml, and sendtext_exec().
 {
    return ast_register_application_xml(app, sendtext_exec);
 }
sendtext_exec()
static int sendtext_exec (struct ast_channel * chan, const char * data) static
Definition at line 149 of file app_sendtext.c.
References ARRAY_LEN, ast_begins_with(), ast_channel_lock, ast_channel_tech(), ast_channel_unlock, ast_free, ast_msg_data_alloc(), AST_MSG_DATA_ATTR_BODY, AST_MSG_DATA_ATTR_CONTENT_TYPE, AST_MSG_DATA_ATTR_FROM, AST_MSG_DATA_ATTR_TO, AST_MSG_DATA_SOURCE_TYPE_IN_DIALOG, ast_sendtext(), ast_sendtext_data(), ast_str_alloca, ast_str_buffer(), ast_str_get_encoded_str(), ast_strlen_zero, cleanup(), NULL, pbx_builtin_getvar_helper(), pbx_builtin_setvar_helper(), S_OR, send_text(), status, str, and ast_msg_data_attribute::type.
Referenced by load_module().
 {
    char *status;
    char *msg_type;
    struct ast_str *str;
    const char *from;
    const char *to;
    const char *content_type;
    const char *body;
    int rc = 0;
    ast_channel_lock(chan);
    from = pbx_builtin_getvar_helper(chan, "SENDTEXT_FROM_DISPLAYNAME");
    to = pbx_builtin_getvar_helper(chan, "SENDTEXT_TO_DISPLAYNAME");
    content_type = pbx_builtin_getvar_helper(chan, "SENDTEXT_CONTENT_TYPE");
    body = S_OR(pbx_builtin_getvar_helper(chan, "SENDTEXT_BODY"), data);
    body = S_OR(body, "");
    if (!(str = ast_str_alloca(strlen(body) + 1))) {
       rc = -1;
       goto cleanup;
    }
    ast_str_get_encoded_str(&str, -1, body);
    body = ast_str_buffer(str);
    msg_type = "NONE";
    status = "UNSUPPORTED";
    if (ast_channel_tech(chan)->send_text_data) {
       struct ast_msg_data *msg;
       struct ast_msg_data_attribute attrs[] =
       {
          {
             .type = AST_MSG_DATA_ATTR_FROM,
             .value = (char *)S_OR(from, ""),
          },
          {
             .type = AST_MSG_DATA_ATTR_TO,
             .value = (char *)S_OR(to, ""),
          },
          {
             .type = AST_MSG_DATA_ATTR_CONTENT_TYPE,
             .value = (char *)S_OR(content_type, ""),
          },
          {
             .type = AST_MSG_DATA_ATTR_BODY,
             .value = (char *)S_OR(body, ""),
          },
       };
       msg_type = "ENHANCED";
       msg = ast_msg_data_alloc(AST_MSG_DATA_SOURCE_TYPE_IN_DIALOG, attrs, ARRAY_LEN(attrs));
       if (msg) {
          if (ast_sendtext_data(chan, msg) == 0) {
             status = "SUCCESS";
          } else {
             status = "FAILURE";
          }
          ast_free(msg);
       } else {
          rc = -1;
          goto cleanup;
       }
    } else if (ast_channel_tech(chan)->send_text) {
       if (!ast_strlen_zero(content_type) && !ast_begins_with(content_type, "text/")) {
          rc = -1;
          goto cleanup;
       }
       msg_type = "BASIC";
       if (ast_sendtext(chan, body) == 0) {
          status = "SUCCESS";
       } else {
          status = "FAILURE";
       }
    }
    pbx_builtin_setvar_helper(chan, "SENDTEXTTYPE", msg_type);
    pbx_builtin_setvar_helper(chan, "SENDTEXTSTATUS", status);
 cleanup:
    pbx_builtin_setvar_helper(chan, "SENDTEXT_FROM_DISPLAYNAME", NULL);
    pbx_builtin_setvar_helper(chan, "SENDTEXT_TO_DISPLAYNAME", NULL);
    pbx_builtin_setvar_helper(chan, "SENDTEXT_CONTENT_TYPE", NULL);
    pbx_builtin_setvar_helper(chan, "SENDTEXT_BODY", NULL);
    ast_channel_unlock(chan);
    return rc;
 }
unload_module()
static int unload_module (void) static
Definition at line 240 of file app_sendtext.c.
References app, and ast_unregister_application().
 {
    return ast_unregister_application(app);
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Send Text Applications" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, } static
Definition at line 250 of file app_sendtext.c.
app
const char* const app = "SendText" static
Definition at line 147 of file app_sendtext.c.
Referenced by load_module(), and unload_module().
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 250 of file app_sendtext.c.