Asterisk - The Open Source Telephony Project: rec_get.c File Reference
rec_get.c File Reference
#include <sys/types.h>
#include <errno.h>
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include "../include/db.h"
#include "recno.h"
Functions
int __rec_fmap (BTREE *t, recno_t top)
int __rec_fpipe (BTREE *t, recno_t top)
int __rec_get (DB *dbp, const DBT *key, DBT *data, u_int flags) const
int __rec_vmap (BTREE *t, recno_t top)
int __rec_vpipe (BTREE *t, recno_t top)
Function Documentation
__rec_fmap()
int __rec_fmap (BTREE * t, recno_t top)
Definition at line 235 of file rec_get.c.
References __rec_iput(), _btree::bt_bval, _btree::bt_cmap, _btree::bt_emap, _btree::bt_nrecs, _btree::bt_rdata, _btree::bt_reclen, DBT::data, F_SET, len(), malloc(), NULL, R_EOF, realloc, RET_ERROR, RET_SPECIAL, RET_SUCCESS, and DBT::size.
Referenced by __rec_open().
 {
    DBT data;
    recno_t nrec;
    u_char *sp, *ep, *p;
    size_t len;
    if (t->bt_rdata.size < t->bt_reclen) {
       t->bt_rdata.data = t->bt_rdata.data == NULL ?
           malloc(t->bt_reclen) :
           realloc(t->bt_rdata.data, t->bt_reclen);
       if (t->bt_rdata.data == NULL)
          return (RET_ERROR);
       t->bt_rdata.size = t->bt_reclen;
    }
    data.data = t->bt_rdata.data;
    data.size = t->bt_reclen;
    sp = (u_char *)t->bt_cmap;
    ep = (u_char *)t->bt_emap;
    for (nrec = t->bt_nrecs; nrec < top; ++nrec) {
       if (sp >= ep) {
          F_SET(t, R_EOF);
          return (RET_SPECIAL);
       }
       len = t->bt_reclen;
       for (p = t->bt_rdata.data;
           sp < ep && len > 0; *p++ = *sp++, --len);
       if (len != 0)
          memset(p, t->bt_bval, len);
       if (__rec_iput(t, nrec, &data, 0) != RET_SUCCESS)
          return (RET_ERROR);
    }
    t->bt_cmap = (caddr_t)sp;
    return (RET_SUCCESS);
 }
__rec_fpipe()
int __rec_fpipe (BTREE * t, recno_t top)
Definition at line 122 of file rec_get.c.
References __rec_iput(), _btree::bt_bval, _btree::bt_nrecs, _btree::bt_rdata, _btree::bt_reclen, _btree::bt_rfp, DBT::data, F_SET, len(), malloc(), NULL, R_EOF, realloc, RET_ERROR, RET_SPECIAL, RET_SUCCESS, and DBT::size.
Referenced by __rec_open().
 {
    DBT data;
    recno_t nrec;
    size_t len;
    int ch;
    u_char *p;
    if (t->bt_rdata.size < t->bt_reclen) {
       t->bt_rdata.data = t->bt_rdata.data == NULL ?
           malloc(t->bt_reclen) :
           realloc(t->bt_rdata.data, t->bt_reclen);
       if (t->bt_rdata.data == NULL)
          return (RET_ERROR);
       t->bt_rdata.size = t->bt_reclen;
    }
    data.data = t->bt_rdata.data;
    data.size = t->bt_reclen;
    for (nrec = t->bt_nrecs; nrec < top;) {
       len = t->bt_reclen;
       for (p = t->bt_rdata.data;; *p++ = ch)
          if ((ch = getc(t->bt_rfp)) == EOF || !--len) {
             if (ch != EOF)
                *p = ch;
             if (len != 0)
                memset(p, t->bt_bval, len);
             if (__rec_iput(t,
                 nrec, &data, 0) != RET_SUCCESS)
                return (RET_ERROR);
             ++nrec;
             break;
          }
       if (ch == EOF)
          break;
    }
    if (nrec < top) {
       F_SET(t, R_EOF);
       return (RET_SPECIAL);
    }
    return (RET_SUCCESS);
 }
__rec_get()
int __rec_get (DB * dbp, const DBT * key, DBT * data, u_int flags) const
Definition at line 63 of file rec_get.c.
References __rec_ret(), __rec_search(), B_DB_LOCK, _btree::bt_mp, _btree::bt_nrecs, _btree::bt_pinned, DBT::data, errno, F_ISSET, __db::internal, mpool_put(), NULL, _epg::page, R_EOF, R_INMEM, RET_ERROR, RET_SPECIAL, RET_SUCCESS, SEARCH, and status.
Referenced by __rec_open().
 {
    BTREE *t;
    EPG *e;
    recno_t nrec;
    int status;
    t = dbp->internal;
    /* Toss any page pinned across calls. */
    if (t->bt_pinned != NULL) {
       mpool_put(t->bt_mp, t->bt_pinned, 0);
       t->bt_pinned = NULL;
    }
    /* Get currently doesn't take any flags, and keys of 0 are illegal. */
    if (flags || (nrec = *(recno_t *)key->data) == 0) {
       errno = EINVAL;
       return (RET_ERROR);
    }
    /*
     * If we haven't seen this record yet, try to find it in the
     * original file.
     */
    if (nrec > t->bt_nrecs) {
       if (F_ISSET(t, R_EOF | R_INMEM))
          return (RET_SPECIAL);
       if ((status = t->bt_irec(t, nrec)) != RET_SUCCESS)
          return (status);
    }
    --nrec;
    if ((e = __rec_search(t, nrec, SEARCH)) == NULL)
       return (RET_ERROR);
    status = __rec_ret(t, e, 0, NULL, data);
    if (F_ISSET(t, B_DB_LOCK))
       mpool_put(t->bt_mp, e->page, 0);
    else
       t->bt_pinned = e->page;
    return (status);
 }
__rec_vmap()
int __rec_vmap (BTREE * t, recno_t top)
Definition at line 285 of file rec_get.c.
References __rec_iput(), _btree::bt_bval, _btree::bt_cmap, _btree::bt_emap, _btree::bt_nrecs, DBT::data, F_SET, if(), R_EOF, RET_ERROR, RET_SPECIAL, RET_SUCCESS, and DBT::size.
Referenced by __rec_open().
 {
    DBT data;
    u_char *sp, *ep;
    recno_t nrec;
    int bval;
    sp = (u_char *)t->bt_cmap;
    ep = (u_char *)t->bt_emap;
    bval = t->bt_bval;
    for (nrec = t->bt_nrecs; nrec < top; ++nrec) {
       if (sp >= ep) {
          F_SET(t, R_EOF);
          return (RET_SPECIAL);
       }
       for (data.data = sp; sp < ep && *sp != bval; ++sp);
       data.size = sp - (u_char *)data.data;
       if (__rec_iput(t, nrec, &data, 0) != RET_SUCCESS)
          return (RET_ERROR);
       ++sp;
    }
    t->bt_cmap = (caddr_t)sp;
    return (RET_SUCCESS);
 }
__rec_vpipe()
int __rec_vpipe (BTREE * t, recno_t top)
Definition at line 178 of file rec_get.c.
References __rec_iput(), _btree::bt_bval, _btree::bt_nrecs, _btree::bt_rdata, _btree::bt_rfp, DBT::data, F_SET, if(), len(), malloc(), NULL, R_EOF, realloc, RET_ERROR, RET_SPECIAL, RET_SUCCESS, and DBT::size.
Referenced by __rec_open().
 {
    DBT data;
    recno_t nrec;
    indx_t len;
    size_t sz;
    int bval, ch;
    u_char *p;
    bval = t->bt_bval;
    for (nrec = t->bt_nrecs; nrec < top; ++nrec) {
       for (p = t->bt_rdata.data,
           sz = t->bt_rdata.size;; *p++ = ch, --sz) {
          if ((ch = getc(t->bt_rfp)) == EOF || ch == bval) {
             data.data = t->bt_rdata.data;
             data.size = p - (u_char *)t->bt_rdata.data;
             if (ch == EOF && data.size == 0)
                break;
             if (__rec_iput(t, nrec, &data, 0)
                 != RET_SUCCESS)
                return (RET_ERROR);
             break;
          }
          if (sz == 0) {
             len = p - (u_char *)t->bt_rdata.data;
             t->bt_rdata.size += (sz = 256);
             t->bt_rdata.data = t->bt_rdata.data == NULL ?
                 malloc(t->bt_rdata.size) :
                 realloc(t->bt_rdata.data, t->bt_rdata.size);
             if (t->bt_rdata.data == NULL)
                return (RET_ERROR);
             p = (u_char *)t->bt_rdata.data + len;
          }
       }
       if (ch == EOF)
          break;
    }
    if (nrec < top) {
       F_SET(t, R_EOF);
       return (RET_SPECIAL);
    }
    return (RET_SUCCESS);
 }