Asterisk - The Open Source Telephony Project: astobj2_global.c File Reference
astobj2_global.c File Reference
Functions implementing ao2_global_obj routines.
#include "asterisk.h"
#include "asterisk/astobj2.h"
#include "asterisk/utils.h"
Functions
void * __ao2_global_obj_ref (struct ao2_global_obj *holder, const char *tag, const char *file, int line, const char *func, const char *name)
void * __ao2_global_obj_replace (struct ao2_global_obj *holder, void *obj, const char *tag, const char *file, int line, const char *func, const char *name)
int __ao2_global_obj_replace_unref (struct ao2_global_obj *holder, void *obj, const char *tag, const char *file, int line, const char *func, const char *name)
Detailed Description
Functions implementing ao2_global_obj routines.
Author
Richard Mudgett rmudg.nosp@m.ett@.nosp@m.digiu.nosp@m.m.co.nosp@m.m
Definition in file astobj2_global.c.
Function Documentation
__ao2_global_obj_ref()
void* __ao2_global_obj_ref (struct ao2_global_obj * holder, const char * tag, const char * file, int line, const char * func, const char * name)
Definition at line 72 of file astobj2_global.c.
References __ao2_ref(), __ast_rwlock_rdlock(), __ast_rwlock_unlock(), ast_assert, ast_log, ao2_global_obj::lock, LOG_ERROR, NULL, and ao2_global_obj::obj.
 {
    void *obj;
    if (!holder) {
       /* For sanity */
       ast_log(LOG_ERROR, "Must be called with a global object!\n");
       ast_assert(0);
       return NULL;
    }
    if (__ast_rwlock_rdlock(file, line, func, &holder->lock, name)) {
       /* Could not get the read lock. */
       ast_assert(0);
       return NULL;
    }
    obj = holder->obj;
    if (obj) {
       __ao2_ref(obj, +1, tag, file, line, func);
    }
    __ast_rwlock_unlock(file, line, func, &holder->lock, name);
    return obj;
 }
__ao2_global_obj_replace()
void* __ao2_global_obj_replace (struct ao2_global_obj * holder, void * obj, const char * tag, const char * file, int line, const char * func, const char * name)
Definition at line 33 of file astobj2_global.c.
References __ao2_ref(), __ast_rwlock_unlock(), __ast_rwlock_wrlock(), ast_assert, ast_log, ao2_global_obj::lock, LOG_ERROR, NULL, and ao2_global_obj::obj.
Referenced by __ao2_global_obj_replace_unref().
 {
    void *obj_old;
    if (!holder) {
       /* For sanity */
       ast_log(LOG_ERROR, "Must be called with a global object!\n");
       ast_assert(0);
       return NULL;
    }
    if (__ast_rwlock_wrlock(file, line, func, &holder->lock, name)) {
       /* Could not get the write lock. */
       ast_assert(0);
       return NULL;
    }
    if (obj) {
       __ao2_ref(obj, +1, tag, file, line, func);
    }
    obj_old = holder->obj;
    holder->obj = obj;
    __ast_rwlock_unlock(file, line, func, &holder->lock, name);
    return obj_old;
 }
__ao2_global_obj_replace_unref()
int __ao2_global_obj_replace_unref (struct ao2_global_obj * holder, void * obj, const char * tag, const char * file, int line, const char * func, const char * name)
Definition at line 60 of file astobj2_global.c.
References __ao2_global_obj_replace(), and __ao2_ref().
 {
    void *obj_old;
    obj_old = __ao2_global_obj_replace(holder, obj, tag, file, line, func, name);
    if (obj_old) {
       __ao2_ref(obj_old, -1, tag, file, line, func);
       return 1;
    }
    return 0;
 }