Asterisk - The Open Source Telephony Project: cdr_csv.c File Reference
cdr_csv.c File Reference
Module: CDR Drivers
Comma Separated Value CDR records.
#include "asterisk.h"
#include "asterisk/paths.h"
#include "asterisk/config.h"
#include "asterisk/channel.h"
#include "asterisk/cdr.h"
#include "asterisk/module.h"
#include "asterisk/utils.h"
#include "asterisk/lock.h"
Macros
#define CSV_LOG_DIR "/cdr-csv"
#define CSV_MASTER "/Master.csv"
#define DATE_FORMAT "%Y-%m-%d %T"
Functions
static void __reg_module (void)
static void __unreg_module (void)
static int append_date (char *buf, struct timeval when, size_t bufsize)
static int append_int (char *buf, int s, size_t bufsize)
static int append_string (char *buf, const char *s, size_t bufsize)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int build_csv_record (char *buf, size_t bufsize, struct ast_cdr *cdr)
static int csv_log (struct ast_cdr *cdr)
static int load_config (int reload)
static int load_module (void)
static int reload (void)
static int unload_module (void)
static int writefile (char *s, char *file_path)
static int writefile_account (char *s, char *acc)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Comma Separated Values CDR Backend" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_EXTENDED, .load = load_module, .unload = unload_module, .reload = reload, .load_pri = AST_MODPRI_CDR_DRIVER, .requires = "cdr", }
static int accountlogs = 1
static const struct ast_module_info * ast_module_info = &__mod_info
static const char config [] = "cdr.conf"
static ast_mutex_t f_lock = { PTHREAD_RECURSIVE_MUTEX_INITIALIZER_NP , NULL, {1, 0} }
static char file_csv_master [PATH_MAX]
static int loaded = 0
static int loguniqueid = 0
static int loguserfield = 0
static char * name = "csv"
static int newcdrcolumns = 0
static int usegmtime = 0
Detailed Description
Comma Separated Value CDR records.
Author
Mark Spencer marks.nosp@m.ter@.nosp@m.digiu.nosp@m.m.co.nosp@m.m
See also CDR - Call Data Records and billing
Definition in file cdr_csv.c.
Macro Definition Documentation
CSV_LOG_DIR
#define CSV_LOG_DIR "/cdr-csv"
Definition at line 49 of file cdr_csv.c.
Referenced by load_config(), and writefile_account().
CSV_MASTER
#define CSV_MASTER "/Master.csv"
Definition at line 50 of file cdr_csv.c.
Referenced by load_config().
DATE_FORMAT
#define DATE_FORMAT "%Y-%m-%d %T"
Definition at line 52 of file cdr_csv.c.
Referenced by append_date().
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 364 of file cdr_csv.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 364 of file cdr_csv.c.
append_date()
static int append_date (char * buf, struct timeval when, size_t bufsize) static
Definition at line 192 of file cdr_csv.c.
References append_string(), ast_localtime(), ast_strftime(), ast_tvzero(), DATE_FORMAT, NULL, tmp(), and usegmtime.
Referenced by build_csv_record().
 {
    char tmp[80] = "";
    struct ast_tm tm;
    if (strlen(buf) > bufsize - 3)
       return -1;
    if (ast_tvzero(when)) {
       strncat(buf, ",", bufsize - strlen(buf) - 1);
       return 0;
    }
    ast_localtime(&when, &tm, usegmtime ? "GMT" : NULL);
    ast_strftime(tmp, sizeof(tmp), DATE_FORMAT, &tm);
    return append_string(buf, tmp, bufsize);
 }
append_int()
static int append_int (char * buf, int s, size_t bufsize) static
Definition at line 174 of file cdr_csv.c.
References tmp().
Referenced by build_csv_record().
 {
    char tmp[32];
    int pos = strlen(buf);
    snprintf(tmp, sizeof(tmp), "%d", s);
    if (pos + strlen(tmp) > bufsize - 3)
       return -1;
    strncat(buf, tmp, bufsize - strlen(buf) - 1);
    pos = strlen(buf);
    buf[pos++] = ',';
    buf[pos++] = '\0';
    return 0;
 }
append_string()
static int append_string (char * buf, const char * s, size_t bufsize) static
Definition at line 147 of file cdr_csv.c.
References error().
Referenced by append_date(), and build_csv_record().
 {
    int pos = strlen(buf), spos = 0, error = -1;
    if (pos >= bufsize - 4)
       return -1;
    buf[pos++] = '\"';
    while(pos < bufsize - 3) {
       if (!s[spos]) {
          error = 0;
          break;
       }
       if (s[spos] == '\"')
          buf[pos++] = '\"';
       buf[pos++] = s[spos];
       spos++;
    }
    buf[pos++] = '\"';
    buf[pos++] = ',';
    buf[pos++] = '\0';
    return error;
 }
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 364 of file cdr_csv.c.
build_csv_record()
static int build_csv_record (char * buf, size_t bufsize, struct ast_cdr * cdr) static
Definition at line 211 of file cdr_csv.c.
References ast_cdr::accountcode, ast_cdr::amaflags, ast_cdr::answer, append_date(), append_int(), append_string(), ast_cdr_disp2str(), ast_channel_amaflags2string(), ast_cdr::billsec, ast_cdr::channel, ast_cdr::clid, ast_cdr::dcontext, ast_cdr::disposition, ast_cdr::dst, ast_cdr::dstchannel, ast_cdr::duration, ast_cdr::end, ast_cdr::lastapp, ast_cdr::lastdata, ast_cdr::linkedid, loguniqueid, loguserfield, newcdrcolumns, ast_cdr::peeraccount, ast_cdr::sequence, ast_cdr::src, ast_cdr::start, ast_cdr::uniqueid, and ast_cdr::userfield.
Referenced by csv_log().
 {
    buf[0] = '\0';
    /* Account code */
    append_string(buf, cdr->accountcode, bufsize);
    /* Source */
    append_string(buf, cdr->src, bufsize);
    /* Destination */
    append_string(buf, cdr->dst, bufsize);
    /* Destination context */
    append_string(buf, cdr->dcontext, bufsize);
    /* Caller*ID */
    append_string(buf, cdr->clid, bufsize);
    /* Channel */
    append_string(buf, cdr->channel, bufsize);
    /* Destination Channel */
    append_string(buf, cdr->dstchannel, bufsize);
    /* Last Application */
    append_string(buf, cdr->lastapp, bufsize);
    /* Last Data */
    append_string(buf, cdr->lastdata, bufsize);
    /* Start Time */
    append_date(buf, cdr->start, bufsize);
    /* Answer Time */
    append_date(buf, cdr->answer, bufsize);
    /* End Time */
    append_date(buf, cdr->end, bufsize);
    /* Duration */
    append_int(buf, cdr->duration, bufsize);
    /* Billable seconds */
    append_int(buf, cdr->billsec, bufsize);
    /* Disposition */
    append_string(buf, ast_cdr_disp2str(cdr->disposition), bufsize);
    /* AMA Flags */
    append_string(buf, ast_channel_amaflags2string(cdr->amaflags), bufsize);
    /* Unique ID */
    if (loguniqueid)
       append_string(buf, cdr->uniqueid, bufsize);
    /* append the user field */
    if(loguserfield)
       append_string(buf, cdr->userfield, bufsize);
    if (newcdrcolumns) {
       append_string(buf, cdr->peeraccount, bufsize);
       append_string(buf, cdr->linkedid, bufsize);
       append_int(buf, cdr->sequence, bufsize);
    }
    /* If we hit the end of our buffer, log an error */
    if (strlen(buf) < bufsize - 5) {
       /* Trim off trailing comma */
       buf[strlen(buf) - 1] = '\0';
       strncat(buf, "\n", bufsize - strlen(buf) - 1);
       return 0;
    }
    return -1;
 }
csv_log()
static int csv_log (struct ast_cdr * cdr) static
Definition at line 297 of file cdr_csv.c.
References ast_cdr::accountcode, accountlogs, ast_log, ast_mutex_lock, ast_mutex_unlock, ast_strlen_zero, buf, build_csv_record(), errno, f_lock, file_csv_master, LOG_WARNING, writefile(), and writefile_account().
Referenced by load_module().
 {
    /* Make sure we have a big enough buf */
    char buf[1024];
    if (build_csv_record(buf, sizeof(buf), cdr)) {
       ast_log(LOG_WARNING, "Unable to create CSV record in %d bytes.  CDR not recorded!\n", (int)sizeof(buf));
       return 0;
    }
    ast_mutex_lock(&f_lock);
    if (writefile(buf, file_csv_master))
       ast_log(LOG_WARNING, "Unable to write CSV record to master '%s' : %s\n", file_csv_master, strerror(errno));
    if (accountlogs && !ast_strlen_zero(cdr->accountcode)) {
       if (writefile_account(buf, cdr->accountcode))
          ast_log(LOG_WARNING, "Unable to write CSV record to account file '%s' : %s\n", cdr->accountcode, strerror(errno));
    }
    ast_mutex_unlock(&f_lock);
    return 0;
 }
load_config()
static int load_config (int reload) static
Definition at line 98 of file cdr_csv.c.
References accountlogs, ast_config_AST_LOG_DIR, ast_config_destroy(), ast_config_load, ast_log, ast_mutex_lock, ast_mutex_unlock, ast_true(), ast_variable_browse(), config, CONFIG_FLAG_FILEUNCHANGED, CONFIG_STATUS_FILEINVALID, CONFIG_STATUS_FILEUNCHANGED, CSV_LOG_DIR, CSV_MASTER, f_lock, file_csv_master, LOG_WARNING, loguniqueid, loguserfield, ast_variable::name, newcdrcolumns, ast_variable::next, usegmtime, and ast_variable::value.
Referenced by load_module(), and reload().
 {
    struct ast_config *cfg;
    struct ast_variable *v;
    struct ast_flags config_flags = { reload ? CONFIG_FLAG_FILEUNCHANGED : 0 };
    if (!(cfg = ast_config_load(config, config_flags)) || cfg == CONFIG_STATUS_FILEINVALID) {
       ast_log(LOG_WARNING, "unable to load config: %s\n", config);
       return 0;
    } else if (cfg == CONFIG_STATUS_FILEUNCHANGED) {
       return 1;
    }
    accountlogs = 1;
    usegmtime = 0;
    loguniqueid = 0;
    loguserfield = 0;
    newcdrcolumns = 0;
    if (!(v = ast_variable_browse(cfg, "csv"))) {
       ast_config_destroy(cfg);
       return 0;
    }
    /* compute the location of the csv master file */
    ast_mutex_lock(&f_lock);
    snprintf(file_csv_master, sizeof(file_csv_master),
       "%s/%s/%s", ast_config_AST_LOG_DIR, CSV_LOG_DIR, CSV_MASTER);
    ast_mutex_unlock(&f_lock);
    for (; v; v = v->next) {
       if (!strcasecmp(v->name, "usegmtime")) {
          usegmtime = ast_true(v->value);
       } else if (!strcasecmp(v->name, "accountlogs")) {
          /* Turn on/off separate files per accountcode. Default is on (as before) */
          accountlogs = ast_true(v->value);
       } else if (!strcasecmp(v->name, "loguniqueid")) {
          loguniqueid = ast_true(v->value);
       } else if (!strcasecmp(v->name, "loguserfield")) {
          loguserfield = ast_true(v->value);
       } else if (!strcasecmp(v->name, "newcdrcolumns")) {
          newcdrcolumns = ast_true(v->value);
       }
    }
    ast_config_destroy(cfg);
    return 1;
 }
load_module()
static int load_module (void) static
Definition at line 328 of file cdr_csv.c.
References ast_cdr_register(), ast_log, AST_MODULE_LOAD_DECLINE, csv_log(), ast_module_info::description, load_config(), loaded, LOG_ERROR, and name.
Referenced by reload().
 {
    int res;
    if (!load_config(0)) {
       return AST_MODULE_LOAD_DECLINE;
    }
    if ((res = ast_cdr_register(name, ast_module_info->description, csv_log))) {
       ast_log(LOG_ERROR, "Unable to register CSV CDR handling\n");
    } else {
       loaded = 1;
    }
    return res;
 }
reload()
static int reload (void) static
Definition at line 344 of file cdr_csv.c.
References ast_cdr_unregister(), ast_log, AST_MODFLAG_LOAD_ORDER, AST_MODPRI_CDR_DRIVER, AST_MODULE_INFO(), AST_MODULE_SUPPORT_EXTENDED, ASTERISK_GPL_KEY, load_config(), load_module(), loaded, LOG_WARNING, name, and unload_module().
 {
    if (load_config(1)) {
       loaded = 1;
    } else {
       loaded = 0;
       ast_log(LOG_WARNING, "No [csv] section in cdr.conf.  Unregistering backend.\n");
       ast_cdr_unregister(name);
    }
    return 0;
 }
unload_module()
static int unload_module (void) static
Definition at line 318 of file cdr_csv.c.
References ast_cdr_unregister(), loaded, and name.
Referenced by reload().
 {
    if (ast_cdr_unregister(name)) {
       return -1;
    }
    loaded = 0;
    return 0;
 }
writefile()
static int writefile (char * s, char * file_path) static
Definition at line 268 of file cdr_csv.c.
References ast_log, errno, and LOG_ERROR.
Referenced by csv_log(), and writefile_account().
 {
    FILE *f;
    /* because of the absolutely unconditional need for the
       highest reliability possible in writing billing records,
       we open write and close the log file each time */
    if (!(f = fopen(file_path, "a"))) {
       ast_log(LOG_ERROR, "Unable to open file %s : %s\n", file_path, strerror(errno));
       return -1;
    }
    fputs(s, f);
    fflush(f); /* be particularly anal here */
    fclose(f);
    return 0;
 }
writefile_account()
static int writefile_account (char * s, char * acc) static
Definition at line 286 of file cdr_csv.c.
References ast_config_AST_LOG_DIR, ast_log, CSV_LOG_DIR, LOG_WARNING, PATH_MAX, and writefile().
Referenced by csv_log().
 {
    char file_account[PATH_MAX];
    if (strchr(acc, '/') || (acc[0] == '.')) {
       ast_log(LOG_WARNING, "Account code '%s' insecure for writing file\n", acc);
       return -1;
    }
    snprintf(file_account, sizeof(file_account), "%s/%s/%s.csv", ast_config_AST_LOG_DIR,CSV_LOG_DIR, acc);
    return writefile(s, file_account);
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Comma Separated Values CDR Backend" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_EXTENDED, .load = load_module, .unload = unload_module, .reload = reload, .load_pri = AST_MODPRI_CDR_DRIVER, .requires = "cdr", } static
Definition at line 364 of file cdr_csv.c.
accountlogs
int accountlogs = 1 static
Definition at line 55 of file cdr_csv.c.
Referenced by csv_log(), and load_config().
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 364 of file cdr_csv.c.
config
const char config[] = "cdr.conf" static
Definition at line 60 of file cdr_csv.c.
Referenced by load_config().
f_lock
ast_mutex_t f_lock = { PTHREAD_RECURSIVE_MUTEX_INITIALIZER_NP , NULL, {1, 0} } static
Definition at line 96 of file cdr_csv.c.
Referenced by csv_log(), and load_config().
file_csv_master
char file_csv_master[PATH_MAX] static
Definition at line 61 of file cdr_csv.c.
Referenced by csv_log(), and load_config().
loaded
int loaded = 0 static
Definition at line 58 of file cdr_csv.c.
Referenced by load_module(), load_or_reload_lua_stuff(), reload(), and unload_module().
loguniqueid
int loguniqueid = 0 static
Definition at line 56 of file cdr_csv.c.
Referenced by build_csv_record(), and load_config().
loguserfield
int loguserfield = 0 static
Definition at line 57 of file cdr_csv.c.
Referenced by build_csv_record(), and load_config().
name
char* name = "csv" static
Definition at line 94 of file cdr_csv.c.
Referenced by load_module(), reload(), and unload_module().
newcdrcolumns
int newcdrcolumns = 0 static
Definition at line 59 of file cdr_csv.c.
Referenced by build_csv_record(), and load_config().
usegmtime
int usegmtime = 0 static
Definition at line 54 of file cdr_csv.c.
Referenced by append_date(), and load_config().