Asterisk - The Open Source Telephony Project: test_format_cache.c File Reference
test_format_cache.c File Reference
Format Cache API Unit Tests.
#include "asterisk.h"
#include "asterisk/test.h"
#include "asterisk/module.h"
#include "asterisk/codec.h"
#include "asterisk/format.h"
#include "asterisk/format_cache.h"
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
AST_TEST_DEFINE (format_cache_set)
AST_TEST_DEFINE (format_cache_set_duplicate)
AST_TEST_DEFINE (format_cache_set_null)
AST_TEST_DEFINE (format_cache_get)
AST_TEST_DEFINE (format_cache_get_nonexistent)
static int load_module (void)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Format cache API test module" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, }
static const struct ast_module_info * ast_module_info = &__mod_info
Detailed Description
Format Cache API Unit Tests.
Author
Joshua Colp jcolp.nosp@m.@dig.nosp@m.ium.c.nosp@m.om
Definition in file test_format_cache.c.
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 279 of file test_format_cache.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 279 of file test_format_cache.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 279 of file test_format_cache.c.
AST_TEST_DEFINE() [1/5]
AST_TEST_DEFINE (format_cache_set)
Definition at line 40 of file test_format_cache.c.
References ao2_cleanup, ast_codec_get(), ast_format_cache_set(), ast_format_create_named(), AST_MEDIA_TYPE_AUDIO, AST_TEST_FAIL, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_test_status_update, format, sip_to_pjsip::info(), NULL, RAII_VAR, TEST_EXECUTE, and TEST_INIT.
 {
    RAII_VAR(struct ast_codec *, codec, NULL, ao2_cleanup);
    RAII_VAR(struct ast_format *, format, NULL, ao2_cleanup);
    switch (cmd) {
    case TEST_INIT:
       info->name = "format_cache_set";
       info->category = "/main/format_cache/";
       info->summary = "format cache add unit test";
       info->description =
          "Test that adding of a cached format succeeds";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    codec = ast_codec_get("ulaw", AST_MEDIA_TYPE_AUDIO, 8000);
    if (!codec) {
       ast_test_status_update(test, "Could not retrieve built-in ulaw codec\n");
       return AST_TEST_FAIL;
    }
    format = ast_format_create_named("ulaw@20_1", codec);
    if (!format) {
       ast_test_status_update(test, "Could not create format using built-in codec\n");
       return AST_TEST_FAIL;
    }
    if (ast_format_cache_set(format)) {
       ast_test_status_update(test, "Could not add just created format to cache\n");
       return AST_TEST_FAIL;
    }
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [2/5]
AST_TEST_DEFINE (format_cache_set_duplicate)
Definition at line 77 of file test_format_cache.c.
References ao2_cleanup, ast_codec_get(), ast_format_cache_set(), ast_format_create_named(), AST_MEDIA_TYPE_AUDIO, AST_TEST_FAIL, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_test_status_update, format, sip_to_pjsip::info(), NULL, RAII_VAR, TEST_EXECUTE, and TEST_INIT.
 {
    RAII_VAR(struct ast_codec *, codec, NULL, ao2_cleanup);
    RAII_VAR(struct ast_format *, format, NULL, ao2_cleanup);
    switch (cmd) {
    case TEST_INIT:
       info->name = "format_cache_set_duplicate";
       info->category = "/main/format_cache/";
       info->summary = "format cache add unit test";
       info->description =
          "Test that adding of a cached format multiple times succeeds";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    codec = ast_codec_get("ulaw", AST_MEDIA_TYPE_AUDIO, 8000);
    if (!codec) {
       ast_test_status_update(test, "Could not retrieve built-in ulaw codec\n");
       return AST_TEST_FAIL;
    }
    format = ast_format_create_named("ulaw@20_2", codec);
    if (!format) {
       ast_test_status_update(test, "Could not create format using built-in codec\n");
       return AST_TEST_FAIL;
    }
    if (ast_format_cache_set(format)) {
       ast_test_status_update(test, "Could not add just created format to cache\n");
       return AST_TEST_FAIL;
    }
    if (ast_format_cache_set(format)) {
       ast_test_status_update(test, "Failed to update cached format\n");
       return AST_TEST_FAIL;
    }
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [3/5]
AST_TEST_DEFINE (format_cache_set_null)
Definition at line 119 of file test_format_cache.c.
References ao2_cleanup, ast_codec_get(), ast_format_cache_set(), ast_format_create_named(), AST_MEDIA_TYPE_AUDIO, AST_TEST_FAIL, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_test_status_update, format, sip_to_pjsip::info(), NULL, RAII_VAR, TEST_EXECUTE, and TEST_INIT.
 {
    RAII_VAR(struct ast_codec *, codec, NULL, ao2_cleanup);
    RAII_VAR(struct ast_format *, format, NULL, ao2_cleanup);
    switch (cmd) {
    case TEST_INIT:
       info->name = "format_cache_set_null";
       info->category = "/main/format_cache/";
       info->summary = "format cache add unit test";
       info->description =
          "Test that adding a NULL or empty format to the cache does not succeed";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    codec = ast_codec_get("ulaw", AST_MEDIA_TYPE_AUDIO, 8000);
    if (!codec) {
       ast_test_status_update(test, "Could not retrieve built-in ulaw codec\n");
       return AST_TEST_FAIL;
    }
    format = ast_format_create_named("", codec);
    if (!format) {
       ast_test_status_update(test, "Could not create format using built-in codec\n");
       return AST_TEST_FAIL;
    }
    if (!ast_format_cache_set(format)) {
       ast_test_status_update(test, "Successfully cached a format with an empty name\n");
       return AST_TEST_FAIL;
    }
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [4/5]
AST_TEST_DEFINE (format_cache_get)
Definition at line 156 of file test_format_cache.c.
References ao2_cleanup, ast_codec_get(), ast_format_cache_get, ast_format_cache_set(), ast_format_create_named(), AST_MEDIA_TYPE_AUDIO, AST_TEST_FAIL, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_test_status_update, format, sip_to_pjsip::info(), NULL, RAII_VAR, TEST_EXECUTE, and TEST_INIT.
 {
    RAII_VAR(struct ast_codec *, codec, NULL, ao2_cleanup);
    RAII_VAR(struct ast_format *, format, NULL, ao2_cleanup);
    RAII_VAR(struct ast_format *, cached, NULL, ao2_cleanup);
    switch (cmd) {
    case TEST_INIT:
       info->name = "format_cache_get";
       info->category = "/main/format_cache/";
       info->summary = "format cache get unit test";
       info->description =
          "Test that getting of a cached format succeeds";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    codec = ast_codec_get("ulaw", AST_MEDIA_TYPE_AUDIO, 8000);
    if (!codec) {
       ast_test_status_update(test, "Could not retrieve built-in ulaw codec\n");
       return AST_TEST_FAIL;
    }
    format = ast_format_create_named("ulaw@20", codec);
    if (!format) {
       ast_test_status_update(test, "Could not create format using built-in codec\n");
       return AST_TEST_FAIL;
    }
    if (ast_format_cache_set(format)) {
       ast_test_status_update(test, "Could not add just created format to cache\n");
       return AST_TEST_FAIL;
    }
    cached = ast_format_cache_get("ulaw@20");
    if (!cached) {
       ast_test_status_update(test, "Failed to retrieve a format we just cached\n");
       return AST_TEST_FAIL;
    } else if (cached != format) {
       ast_test_status_update(test, "Returned cached format does not match format we just added\n");
       return AST_TEST_FAIL;
    }
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [5/5]
AST_TEST_DEFINE (format_cache_get_nonexistent)
Definition at line 203 of file test_format_cache.c.
References ao2_cleanup, ast_codec_get(), ast_format_cache_get, ast_format_cache_set(), ast_format_create_named(), AST_MEDIA_TYPE_AUDIO, AST_TEST_FAIL, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_test_status_update, format, sip_to_pjsip::info(), NULL, RAII_VAR, TEST_EXECUTE, and TEST_INIT.
 {
    RAII_VAR(struct ast_codec *, codec, NULL, ao2_cleanup);
    RAII_VAR(struct ast_format *, format, NULL, ao2_cleanup);
    RAII_VAR(struct ast_format *, cached, NULL, ao2_cleanup);
    switch (cmd) {
    case TEST_INIT:
       info->name = "format_cache_get_nonxistent";
       info->category = "/main/format_cache/";
       info->summary = "format cache get unit test";
       info->description =
          "Test that getting of a non-existent cached format does not succeed";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    codec = ast_codec_get("ulaw", AST_MEDIA_TYPE_AUDIO, 8000);
    if (!codec) {
       ast_test_status_update(test, "Could not retrieve built-in ulaw codec\n");
       return AST_TEST_FAIL;
    }
    format = ast_format_create_named("ulaw@40", codec);
    if (!format) {
       ast_test_status_update(test, "Could not create format using built-in codec\n");
       return AST_TEST_FAIL;
    }
    if (ast_format_cache_set(format)) {
       ast_test_status_update(test, "Could not add just created format to cache\n");
       return AST_TEST_FAIL;
    }
    cached = ast_format_cache_get("ulaw@60");
    if (cached) {
       ast_test_status_update(test, "Retrieved a cached format when one should not have existed\n");
       return AST_TEST_FAIL;
    }
    cached = ast_format_cache_get("");
    if (cached) {
       ast_test_status_update(test, "Retrieved a cached format when we provided an empty name\n");
       return AST_TEST_FAIL;
    }
    cached = ast_format_cache_get(NULL);
    if (cached) {
       ast_test_status_update(test, "Retrieved a cached format when we provided a NULL name\n");
       return AST_TEST_FAIL;
    }
    return AST_TEST_PASS;
 }
load_module()
static int load_module (void) static
Definition at line 269 of file test_format_cache.c.
References AST_MODULE_LOAD_SUCCESS, and AST_TEST_REGISTER.
 {
    AST_TEST_REGISTER(format_cache_set);
    AST_TEST_REGISTER(format_cache_set_duplicate);
    AST_TEST_REGISTER(format_cache_set_null);
    AST_TEST_REGISTER(format_cache_get);
    AST_TEST_REGISTER(format_cache_get_nonexistent);
    return AST_MODULE_LOAD_SUCCESS;
 }
unload_module()
static int unload_module (void) static
Definition at line 259 of file test_format_cache.c.
References AST_TEST_UNREGISTER.
 {
    AST_TEST_UNREGISTER(format_cache_set);
    AST_TEST_UNREGISTER(format_cache_set_duplicate);
    AST_TEST_UNREGISTER(format_cache_set_null);
    AST_TEST_UNREGISTER(format_cache_get);
    AST_TEST_UNREGISTER(format_cache_get_nonexistent);
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Format cache API test module" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, } static
Definition at line 279 of file test_format_cache.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 279 of file test_format_cache.c.