Asterisk - The Open Source Telephony Project: test_uuid.c File Reference
test_uuid.c File Reference
Universally unique identifier tests.
#include "asterisk.h"
#include "asterisk/test.h"
#include "asterisk/uuid.h"
#include "asterisk/module.h"
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
AST_TEST_DEFINE (uuid)
static int load_module (void)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "UUID test module" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, }
static const struct ast_module_info * ast_module_info = &__mod_info
Detailed Description
Universally unique identifier tests.
Definition in file test_uuid.c.
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 152 of file test_uuid.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 152 of file test_uuid.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 152 of file test_uuid.c.
AST_TEST_DEFINE()
AST_TEST_DEFINE (uuid)
Definition at line 33 of file test_uuid.c.
References ast_free, ast_str_to_uuid(), AST_TEST_FAIL, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_test_status_update, ast_uuid_clear(), ast_uuid_compare(), ast_uuid_copy(), ast_uuid_generate(), ast_uuid_generate_str(), ast_uuid_is_nil(), AST_UUID_STR_LEN, ast_uuid_to_str(), end, sip_to_pjsip::info(), NULL, TEST_EXECUTE, and TEST_INIT.
 {
    struct ast_uuid *uuid1 = NULL;
    struct ast_uuid *uuid2 = NULL;
    struct ast_uuid *uuid3 = NULL;
    char uuid_str[AST_UUID_STR_LEN];
    enum ast_test_result_state res = AST_TEST_FAIL;
    switch (cmd) {
    case TEST_INIT:
       info->name = "uuid";
       info->category = "/main/uuid/";
       info->summary = "UUID unit test";
       info->description =
          "This tests basic UUID operations to ensure they work properly";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    /* Use method of generating UUID directly as a string. */
    ast_uuid_generate_str(uuid_str, sizeof(uuid_str));
    if (strlen(uuid_str) != (AST_UUID_STR_LEN - 1)) {
       ast_test_status_update(test, "Failed to directly generate UUID string\n");
       goto end;
    }
    ast_test_status_update(test, "Generate UUID direct to string, got %s\n", uuid_str);
    /* Now convert the direct UUID string to a UUID */
    uuid1 = ast_str_to_uuid(uuid_str);
    if (!uuid1) {
       ast_test_status_update(test, "Unable to convert direct UUID string %s to UUID\n", uuid_str);
       goto end;
    }
    ast_free(uuid1);
    /* Make sure that we can generate a UUID */
    uuid1 = ast_uuid_generate();
    if (!uuid1) {
       ast_test_status_update(test, "Unable to generate a UUID\n");
       goto end;
    }
    /* Make sure we're not generating nil UUIDs */
    if (ast_uuid_is_nil(uuid1)) {
       ast_test_status_update(test, "We generated a nil UUID. Something is wrong\n");
       goto end;
    }
    /* Convert it to a string */
    ast_uuid_to_str(uuid1, uuid_str, sizeof(uuid_str));
    if (strlen(uuid_str) != (AST_UUID_STR_LEN - 1)) {
       ast_test_status_update(test, "Failed to convert the UUID to a string\n");
       goto end;
    }
    ast_test_status_update(test, "Second generated UUID converted to string, got %s\n", uuid_str);
    /* Now convert the string back to a UUID */
    uuid2 = ast_str_to_uuid(uuid_str);
    if (!uuid2) {
       ast_test_status_update(test, "Unable to convert string %s to UUID\n", uuid_str);
       goto end;
    }
    /* Make sure the UUIDs are identical */
    if (ast_uuid_compare(uuid1, uuid2) != 0) {
       ast_test_status_update(test, "UUIDs that should be identical are different\n");
       goto end;
    }
    /* Try copying a UUID */
    uuid3 = ast_uuid_copy(uuid1);
    if (!uuid3) {
       ast_test_status_update(test, "Unable to copy UUID\n");
       goto end;
    }
    /* Make sure copied UUIDs are identical */
    if (ast_uuid_compare(uuid1, uuid3) != 0) {
       ast_test_status_update(test, "UUIDs that should be identical are different\n");
       goto end;
    }
    if (ast_uuid_compare(uuid2, uuid3) != 0) {
       ast_test_status_update(test, "UUIDs that should be identical are different\n");
       goto end;
    }
    /* Clear a UUID and ensure that it registers as nil */
    ast_uuid_clear(uuid1);
    if (!ast_uuid_is_nil(uuid1)) {
       ast_test_status_update(test, "UUID that was cleared does not appear to be nil\n");
       goto end;
    }
    res = AST_TEST_PASS;
 end:
    ast_free(uuid1);
    ast_free(uuid2);
    ast_free(uuid3);
    return res;
 }
load_module()
static int load_module (void) static
Definition at line 146 of file test_uuid.c.
References AST_MODULE_LOAD_SUCCESS, and AST_TEST_REGISTER.
 {
    AST_TEST_REGISTER(uuid);
    return AST_MODULE_LOAD_SUCCESS;
 }
unload_module()
static int unload_module (void) static
Definition at line 140 of file test_uuid.c.
References AST_TEST_UNREGISTER.
 {
    AST_TEST_UNREGISTER(uuid);
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "UUID test module" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, } static
Definition at line 152 of file test_uuid.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 152 of file test_uuid.c.