Asterisk - The Open Source Telephony Project: bridges.c File Reference
bridges.c File Reference
Prometheus Bridge Metrics.
#include "asterisk.h"
#include "asterisk/stasis_bridges.h"
#include "asterisk/res_prometheus.h"
#include "prometheus_internal.h"
Data Structures
struct bridge_metric_defs
Macros
#define BRIDGES_CHANNELS_COUNT_HELP "Number of channels in the bridge."
Functions
int bridge_metrics_init (void)
Initialize bridge metrics.
static void bridge_metrics_unload_cb (void)
static void bridges_scrape_cb (struct ast_str **response)
static void get_bridge_channel_count (struct prometheus_metric *metric, struct ast_bridge_snapshot *snapshot)
Variables
struct bridge_metric_defs bridge_metric_defs []
struct prometheus_callback bridges_callback
static struct prometheus_metrics_provider provider
Detailed Description
Prometheus Bridge Metrics.
Author
Matt Jordan mjord.nosp@m.an@d.nosp@m.igium.nosp@m..com
Definition in file bridges.c.
Macro Definition Documentation
BRIDGES_CHANNELS_COUNT_HELP
#define BRIDGES_CHANNELS_COUNT_HELP "Number of channels in the bridge."
Definition at line 33 of file bridges.c.
Function Documentation
bridge_metrics_init()
int bridge_metrics_init (void)
Initialize bridge metrics.
Return values
0 success
-1 error
Definition at line 183 of file bridges.c.
References prometheus_callback_register(), and prometheus_metrics_provider_register().
Referenced by load_module().
 {
    prometheus_metrics_provider_register(&provider);
    prometheus_callback_register(&bridges_callback);
    return 0;
 }
bridge_metrics_unload_cb()
static void bridge_metrics_unload_cb (void) static
Definition at line 169 of file bridges.c.
References prometheus_callback_unregister().
 {
    prometheus_callback_unregister(&bridges_callback);
 }
bridges_scrape_cb()
static void bridges_scrape_cb (struct ast_str ** response) static
Definition at line 78 of file bridges.c.
References ao2_container_clone, ao2_container_count(), ao2_iterator_destroy(), ao2_iterator_init(), ao2_iterator_next, ao2_ref, ARRAY_LEN, ast_bridge_get_snapshot(), ast_bridges(), ast_calloc, ast_copy_string(), ast_eid_default, ast_eid_to_str(), ast_free, AST_LIST_INSERT_TAIL, bridges, ast_bridge_snapshot::creator, bridge_metric_defs::get_value, bridge_metric_defs::help, prometheus_metric::help, bridge_metric_defs::name, ast_bridge_snapshot::name, NULL, PROMETHEUS_METRIC_GAUGE, PROMETHEUS_METRIC_SET_LABEL, PROMETHEUS_METRIC_STATIC_INITIALIZATION, prometheus_metric_to_string(), ast_bridge_snapshot::subclass, ast_bridge_snapshot::technology, prometheus_metric::type, ast_bridge_snapshot::uniqueid, and prometheus_metric::value.
 {
    struct ao2_container *bridge_cache;
    struct ao2_container *bridges;
    struct ao2_iterator it_bridges;
    struct ast_bridge *bridge;
    struct prometheus_metric *bridge_metrics;
    char eid_str[32];
    int i, j, num_bridges;
    struct prometheus_metric bridge_count = PROMETHEUS_METRIC_STATIC_INITIALIZATION(
       PROMETHEUS_METRIC_GAUGE,
       "asterisk_bridges_count",
       "Current bridge count.",
       NULL
    );
    ast_eid_to_str(eid_str, sizeof(eid_str), &ast_eid_default);
    bridge_cache = ast_bridges();
    if (!bridge_cache) {
       return;
    }
    bridges = ao2_container_clone(bridge_cache, 0);
    ao2_ref(bridge_cache, -1);
    if (!bridges) {
       return;
    }
    num_bridges = ao2_container_count(bridges);
    /* Current endpoint count */
    PROMETHEUS_METRIC_SET_LABEL(&bridge_count, 0, "eid", eid_str);
    snprintf(bridge_count.value, sizeof(bridge_count.value), "%d", num_bridges);
    prometheus_metric_to_string(&bridge_count, response);
    if (num_bridges == 0) {
       ao2_ref(bridges, -1);
       return;
    }
    bridge_metrics = ast_calloc(ARRAY_LEN(bridge_metric_defs) * num_bridges, sizeof(*bridge_metrics));
    if (!bridge_metrics) {
       ao2_ref(bridges, -1);
       return;
    }
    /* Bridge dependent values */
    it_bridges = ao2_iterator_init(bridges, 0);
    for (i = 0; (bridge = ao2_iterator_next(&it_bridges)); ao2_ref(bridge, -1), i++) {
       struct ast_bridge_snapshot *snapshot = ast_bridge_get_snapshot(bridge);
       for (j = 0; j < ARRAY_LEN(bridge_metric_defs); j++) {
          int index = i * ARRAY_LEN(bridge_metric_defs) + j;
          bridge_metrics[index].type = PROMETHEUS_METRIC_GAUGE;
          ast_copy_string(bridge_metrics[index].name, bridge_metric_defs[j].name, sizeof(bridge_metrics[index].name));
          bridge_metrics[index].help = bridge_metric_defs[j].help;
          PROMETHEUS_METRIC_SET_LABEL(&bridge_metrics[index], 0, "eid", eid_str);
          PROMETHEUS_METRIC_SET_LABEL(&bridge_metrics[index], 1, "id", (snapshot->uniqueid));
          PROMETHEUS_METRIC_SET_LABEL(&bridge_metrics[index], 2, "tech", (snapshot->technology));
          PROMETHEUS_METRIC_SET_LABEL(&bridge_metrics[index], 3, "subclass", (snapshot->subclass));
          PROMETHEUS_METRIC_SET_LABEL(&bridge_metrics[index], 4, "creator", (snapshot->creator));
          PROMETHEUS_METRIC_SET_LABEL(&bridge_metrics[index], 5, "name", (snapshot->name));
          bridge_metric_defs[j].get_value(&bridge_metrics[index], snapshot);
          if (i > 0) {
             AST_LIST_INSERT_TAIL(&bridge_metrics[j].children, &bridge_metrics[index], entry);
          }
       }
       ao2_ref(snapshot, -1);
    }
    ao2_iterator_destroy(&it_bridges);
    for (j = 0; j < ARRAY_LEN(bridge_metric_defs); j++) {
       prometheus_metric_to_string(&bridge_metrics[j], response);
    }
    ast_free(bridge_metrics);
    ao2_ref(bridges, -1);
 }
get_bridge_channel_count()
static void get_bridge_channel_count (struct prometheus_metric * metric, struct ast_bridge_snapshot * snapshot) static
Definition at line 42 of file bridges.c.
References ast_bridge_snapshot::num_channels, and prometheus_metric::value.
 {
    snprintf(metric->value, sizeof(metric->value), "%d", snapshot->num_channels);
 }
Variable Documentation
bridge_metric_defs
struct bridge_metric_defs bridge_metric_defs[]
bridges_callback
struct prometheus_callback bridges_callback
Initial value:
= {
   .name = "bridges callback",
   .callback_fn = bridges_scrape_cb,
}
Definition at line 160 of file bridges.c.
provider
struct prometheus_metrics_provider provider static
Initial value:
= {
   .name = "bridges",
   .unload_cb = bridge_metrics_unload_cb,
}
Definition at line 178 of file bridges.c.
Referenced by _ast_device_state(), action_presencestate(), ast_phoneprov_provider_register(), ast_presence_state_helper(), ast_presence_state_prov_add(), ast_presence_state_prov_del(), ast_sip_api_provider_register(), AST_TEST_DEFINE(), handle_cli_osp_show(), osp_auth(), osp_create_provider(), osp_create_transaction(), osp_lookup(), osp_next(), osp_unload(), ospauth_exec(), osplookup_exec(), ospnext_exec(), presence_read(), reload_module(), and unload_module().