Asterisk - The Open Source Telephony Project: config_domain_aliases.c File Reference
config_domain_aliases.c File Reference
#include "asterisk.h"
#include <pjsip.h>
#include <pjlib.h>
#include "asterisk/res_pjsip.h"
#include "include/res_pjsip_private.h"
#include "asterisk/logger.h"
#include "asterisk/sorcery.h"
Functions
int ast_sip_initialize_sorcery_domain_alias (void)
Initialize sorcery with domain alias support.
static void * domain_alias_alloc (const char *name)
static int domain_alias_apply (const struct ast_sorcery *sorcery, void *obj)
Apply handler for domain_alias type.
static void domain_alias_destroy (void *obj)
Function Documentation
ast_sip_initialize_sorcery_domain_alias()
int ast_sip_initialize_sorcery_domain_alias (void)
Initialize sorcery with domain alias support.
Definition at line 71 of file config_domain_aliases.c.
References ast_sip_get_sorcery(), ast_sorcery_apply_default, ast_sorcery_object_field_register, ast_sorcery_object_register, domain_alias_alloc(), domain_alias_apply(), NULL, OPT_NOOP_T, OPT_STRINGFIELD_T, SIP_SORCERY_DOMAIN_ALIAS_TYPE, sorcery, and STRFLDSET.
Referenced by ast_res_pjsip_initialize_configuration().
 {
    struct ast_sorcery *sorcery = ast_sip_get_sorcery();
    ast_sorcery_apply_default(sorcery, SIP_SORCERY_DOMAIN_ALIAS_TYPE, "config", "pjsip.conf,criteria=type=domain_alias");
    if (ast_sorcery_object_register(sorcery, SIP_SORCERY_DOMAIN_ALIAS_TYPE,
       domain_alias_alloc, NULL, domain_alias_apply)) {
       return -1;
    }
    ast_sorcery_object_field_register(sorcery, SIP_SORCERY_DOMAIN_ALIAS_TYPE, "type", "",
          OPT_NOOP_T, 0, 0);
    ast_sorcery_object_field_register(sorcery, SIP_SORCERY_DOMAIN_ALIAS_TYPE, "domain",
          "", OPT_STRINGFIELD_T, 0, STRFLDSET(struct ast_sip_domain_alias, domain));
    return 0;
 }
domain_alias_alloc()
static void* domain_alias_alloc (const char * name) static
Definition at line 36 of file config_domain_aliases.c.
References ao2_cleanup, ast_sorcery_generic_alloc(), ast_string_field_init, domain_alias_destroy(), and NULL.
Referenced by ast_sip_initialize_sorcery_domain_alias().
 {
    struct ast_sip_domain_alias *alias;
    alias = ast_sorcery_generic_alloc(sizeof(*alias), domain_alias_destroy);
    if (!alias) {
       return NULL;
    }
    if (ast_string_field_init(alias, 256)) {
       ao2_cleanup(alias);
       return NULL;
    }
    return alias;
 }
domain_alias_apply()
static int domain_alias_apply (const struct ast_sorcery * sorcery, void * obj) static
Apply handler for domain_alias type.
Definition at line 54 of file config_domain_aliases.c.
References ast_log, ast_sorcery_object_get_id(), ast_strlen_zero, ast_sip_domain_alias::domain, LOG_ERROR, and SIP_SORCERY_DOMAIN_ALIAS_TYPE.
Referenced by ast_sip_initialize_sorcery_domain_alias().
 {
    struct ast_sip_domain_alias *alias = obj;
    if (ast_strlen_zero(alias->domain)) {
       /*
        * What is the point of defining an alias and not saying
        * what is being aliased?
        */
       ast_log(LOG_ERROR, "%s '%s' missing required domain being aliased.\n",
          SIP_SORCERY_DOMAIN_ALIAS_TYPE, ast_sorcery_object_get_id(alias));
       return -1;
    }
    return 0;
 }
domain_alias_destroy()
static void domain_alias_destroy (void * obj) static
Definition at line 29 of file config_domain_aliases.c.
References ast_string_field_free_memory.
Referenced by domain_alias_alloc().
 {
    struct ast_sip_domain_alias *alias = obj;
    ast_string_field_free_memory(alias);
 }