Asterisk - The Open Source Telephony Project: zones2indications.c File Reference
zones2indications.c File Reference
print libtonozone data as Asterisk indications.conf
#include <stdio.h>
#include <stdlib.h>
#include <dahdi/tonezone.h>
#include <unistd.h>
Macros
#define PROGRAM "zones2indication"
Functions
int main (int argc, char *argv[])
int print_all ()
void print_indications (struct ind_tone_zone *zone_data)
void print_tone_zone_sound (struct ind_tone_zone *zone_data, const char *name, int toneid)
int print_zone_by_country (char *country)
int print_zone_by_id (int zone_num)
void usage ()
Detailed Description
print libtonozone data as Asterisk indications.conf
Definition in file zones2indications.c.
Macro Definition Documentation
PROGRAM
#define PROGRAM "zones2indication"
Definition at line 28 of file zones2indications.c.
Referenced by usage().
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 120 of file zones2indications.c.
References NULL, print_all(), print_zone_by_country(), print_zone_by_id(), and usage().
{
   int country_code = -1;
   int opt_print_all = 0;
   int opt;
   char* endptr = NULL;
   while((opt = getopt(argc, argv, "ac:hn:")) != -1) {
     switch(opt) {
       case 'a':
         return print_all();
       case 'c':
         return print_zone_by_country(optarg);
       case 'h':
         usage();
         return 0;
       case 'n':
         printf("number is %s.\n", optarg);
         country_code = strtol(optarg, &endptr, 10);
         return print_zone_by_id(country_code);
         /* FIXME: what if this is not a number?
         if (endptr != NULL) {
           fprintf(stderr, "Error: Invalid country code %s, %d.\n",optarg, country_code);
           usage();
           exit(1);
         }
         */
         break;
     }
   }
   /* If we got here, the user selected no option */
   usage();
   return 2;
 }
print_all()
int print_all ()
Definition at line 98 of file zones2indications.c.
References print_zone_by_id().
Referenced by main().
                 {
   int i;
   /* loop over all possible zones */
   for (i=0; ; i++) {
     if (print_zone_by_id(i))
       break;
   }
   return 0;
 }
print_indications()
void print_indications (struct ind_tone_zone * zone_data)
Definition at line 41 of file zones2indications.c.
References print_tone_zone_sound().
Referenced by print_zone_by_country(), and print_zone_by_id().
{
   int i;
   printf (
     "[%s]\n"
     "; Source: libtonezone.\n"
     "description = %s\n"
     "\n",
     zone_data->country, zone_data->description
   );
   printf(
     "ringcadence = "
   );
   for(i=0; ; i++) {
     if (zone_data->ringcadence[i] == 0)
       break;
     if (i != 0)
       putchar(',');
     printf("%d",zone_data->ringcadence[i]);
   }
   putchar('\n');
   print_tone_zone_sound(zone_data, "dial",        DAHDI_TONE_DIALTONE);
   print_tone_zone_sound(zone_data, "busy",        DAHDI_TONE_BUSY);
   print_tone_zone_sound(zone_data, "ring",        DAHDI_TONE_RINGTONE);
   print_tone_zone_sound(zone_data, "congestion",  DAHDI_TONE_CONGESTION);
   print_tone_zone_sound(zone_data, "callwaiting", DAHDI_TONE_CALLWAIT);
   print_tone_zone_sound(zone_data, "dialrecall",  DAHDI_TONE_DIALRECALL);
   print_tone_zone_sound(zone_data, "record",      DAHDI_TONE_RECORDTONE);
   print_tone_zone_sound(zone_data, "info",        DAHDI_TONE_INFO);
   print_tone_zone_sound(zone_data, "stutter",     DAHDI_TONE_STUTTER);
   printf("\n\n");
 }
print_tone_zone_sound()
void print_tone_zone_sound (struct ind_tone_zone * zone_data, const char * name, int toneid)
Definition at line 30 of file zones2indications.c.
Referenced by print_indications().
                 {
   int i;
   for (i=0; i<DAHDI_TONE_MAX; i++) {
     if (zone_data->tones[i].toneid == toneid){
       printf("%s = %s\n", name, zone_data->tones[i].data);
       break;
     }
   }
 }
print_zone_by_country()
int print_zone_by_country (char * country)
Definition at line 87 of file zones2indications.c.
References NULL, and print_indications().
Referenced by main().
{
   struct tone_zone *zone_data = tone_zone_find(country);
   if (zone_data == NULL)
     return 1;
   print_indications(zone_data);
   return 0;
 }
print_zone_by_id()
int print_zone_by_id (int zone_num)
Definition at line 76 of file zones2indications.c.
References NULL, and print_indications().
Referenced by main(), and print_all().
{
   struct tone_zone *zone_data = tone_zone_find_by_num(zone_num);
   if (zone_data == NULL)
     return 1;
   print_indications(zone_data);
   return 0;
 }
usage()
void usage (void)
Definition at line 108 of file zones2indications.c.
References PROGRAM.
Referenced by main().
              {
   fprintf(stderr,
       PROGRAM ": print libtonozone data as Asterisk indications.conf\n"
       "\n"
       "Usage:\n"
       "  " PROGRAM " -a         Print all countries\n"
       "  " PROGRAM " -c <code>  Select country by two-letter country code\n"
       "  " PROGRAM " -n <num>   Select country by its internal libtonezone number\n"
       "  " PROGRAM " -h         Print this text.\n"
   );
 }