Asterisk - The Open Source Telephony Project: func_presencestate.c File Reference
func_presencestate.c File Reference
Module: Dial plan functions
Custom presence provider.
#include "asterisk.h"
#include "asterisk/module.h"
#include "asterisk/channel.h"
#include "asterisk/pbx.h"
#include "asterisk/utils.h"
#include "asterisk/linkedlists.h"
#include "asterisk/presencestate.h"
#include "asterisk/cli.h"
#include "asterisk/astdb.h"
#include "asterisk/app.h"
#include "asterisk/test.h"
#include "asterisk/sem.h"
Data Structures
struct test_cb_data
struct test_string
Macros
#define PRES_MESSAGE "Quarterly financial meeting"
#define PRES_STATE "away"
#define PRES_SUBTYPE "down the hall"
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
AST_TEST_DEFINE (test_valid_parse_data)
AST_TEST_DEFINE (test_invalid_parse_data)
AST_TEST_DEFINE (test_presence_state_change)
AST_TEST_DEFINE (test_presence_state_base64_encode)
static enum ast_presence_state custom_presence_callback (const char *data, char **subtype, char **message)
static char * handle_cli_presencestate_change (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static char * handle_cli_presencestate_list (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static int load_module (void)
static int parse_data (char *data, enum ast_presence_state *state, char **subtype, char **message, char **options)
static enum ast_test_result_state presence_change_common (struct ast_test *test, const char *state, const char *subtype, const char *message, const char *options, char *out_state, size_t out_state_size, char *out_subtype, size_t out_subtype_size, char *out_message, size_t out_message_size)
static int presence_read (struct ast_channel *chan, const char *cmd, char *data, char *buf, size_t len)
static int presence_write (struct ast_channel *chan, const char *cmd, char *data, const char *value)
static void test_cb (void *userdata, struct stasis_subscription *sub, struct stasis_message *msg)
static struct test_cb_data * test_cb_data_alloc (void)
static void test_cb_data_destroy (struct test_cb_data *cb_data)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Gets or sets a presence state in the dialplan" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEVSTATE_PROVIDER, }
static const struct ast_module_info * ast_module_info = &__mod_info
static const char astdb_family [] = "CustomPresence"
static struct ast_cli_entry cli_funcpresencestate []
static struct ast_custom_function presence_function
Detailed Description
Custom presence provider.
Definition in file func_presencestate.c.
Macro Definition Documentation
PRES_MESSAGE
#define PRES_MESSAGE "Quarterly financial meeting"
Definition at line 662 of file func_presencestate.c.
Referenced by AST_TEST_DEFINE().
PRES_STATE
#define PRES_STATE "away"
Definition at line 660 of file func_presencestate.c.
Referenced by AST_TEST_DEFINE().
PRES_SUBTYPE
#define PRES_SUBTYPE "down the hall"
Definition at line 661 of file func_presencestate.c.
Referenced by AST_TEST_DEFINE().
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 884 of file func_presencestate.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 884 of file func_presencestate.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 884 of file func_presencestate.c.
AST_TEST_DEFINE() [1/4]
AST_TEST_DEFINE (test_valid_parse_data)
Definition at line 460 of file func_presencestate.c.
References ARRAY_LEN, ast_free, AST_PRESENCE_AVAILABLE, AST_PRESENCE_AWAY, AST_PRESENCE_CHAT, AST_PRESENCE_DND, AST_PRESENCE_NOT_SET, AST_PRESENCE_UNAVAILABLE, AST_PRESENCE_XA, ast_strdup, AST_TEST_FAIL, AST_TEST_NOT_RUN, AST_TEST_PASS, sip_to_pjsip::info(), test_string::message, test_string::options, test_string::outputs, parse_data(), test_string::parse_string, state, test_string::subtype, TEST_EXECUTE, and TEST_INIT.
 {
    int i;
    enum ast_presence_state state;
    char *subtype;
    char *message;
    char *options;
    enum ast_test_result_state res = AST_TEST_PASS;
    struct test_string tests [] = {
       { "away",
          { AST_PRESENCE_AWAY,
             "",
             "",
             ""
          }
       },
       { "not_set",
          { AST_PRESENCE_NOT_SET,
             "",
             "",
             ""
          }
       },
       { "unavailable",
          { AST_PRESENCE_UNAVAILABLE,
             "",
             "",
             ""
          }
       },
       { "available",
          { AST_PRESENCE_AVAILABLE,
             "",
             "",
             ""
          }
       },
       { "xa",
          { AST_PRESENCE_XA,
             "",
             "",
             ""
          }
       },
       { "chat",
          { AST_PRESENCE_CHAT,
             "",
             "",
             ""
          }
       },
       { "dnd",
          { AST_PRESENCE_DND,
             "",
             "",
             ""
          }
       },
       { "away,down the hall",
          { AST_PRESENCE_AWAY,
             "down the hall",
             "",
             ""
          }
       },
       { "away,down the hall,Quarterly financial meeting",
          { AST_PRESENCE_AWAY,
             "down the hall",
             "Quarterly financial meeting",
             ""
          }
       },
       { "away,,Quarterly financial meeting",
          { AST_PRESENCE_AWAY,
             "",
             "Quarterly financial meeting",
             ""
          }
       },
       { "away,,,e",
          { AST_PRESENCE_AWAY,
             "",
             "",
             "e",
          }
       },
       { "away,down the hall,,e",
          { AST_PRESENCE_AWAY,
             "down the hall",
             "",
             "e"
          }
       },
       { "away,down the hall,Quarterly financial meeting,e",
          { AST_PRESENCE_AWAY,
             "down the hall",
             "Quarterly financial meeting",
             "e"
          }
       },
       { "away,,Quarterly financial meeting,e",
          { AST_PRESENCE_AWAY,
             "",
             "Quarterly financial meeting",
             "e"
          }
       }
    };
    switch (cmd) {
    case TEST_INIT:
       info->name = "parse_valid_presence_data";
       info->category = "/funcs/func_presence/";
       info->summary = "PRESENCESTATE parsing test";
       info->description =
          "Ensure that parsing function accepts proper values, and gives proper outputs";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    for (i = 0; i < ARRAY_LEN(tests); ++i) {
       int parse_result;
       char *parse_string = ast_strdup(tests[i].parse_string);
       if (!parse_string) {
          res = AST_TEST_FAIL;
          break;
       }
       parse_result = parse_data(parse_string, &state, &subtype, &message, &options);
       if (parse_result == -1) {
          res = AST_TEST_FAIL;
          ast_free(parse_string);
          break;
       }
       if (tests[i].outputs.value != state ||
             strcmp(tests[i].outputs.subtype, subtype) ||
             strcmp(tests[i].outputs.message, message) ||
             strcmp(tests[i].outputs.options, options)) {
          res = AST_TEST_FAIL;
          ast_free(parse_string);
          break;
       }
       ast_free(parse_string);
    }
    return res;
 }
AST_TEST_DEFINE() [2/4]
AST_TEST_DEFINE (test_invalid_parse_data)
Definition at line 609 of file func_presencestate.c.
References ARRAY_LEN, ast_free, ast_log, ast_strdup, AST_TEST_FAIL, AST_TEST_NOT_RUN, AST_TEST_PASS, sip_to_pjsip::info(), LOG_WARNING, test_string::message, test_string::options, parse_data(), test_string::parse_string, state, test_string::subtype, TEST_EXECUTE, and TEST_INIT.
 {
    int i;
    enum ast_presence_state state;
    char *subtype;
    char *message;
    char *options;
    enum ast_test_result_state res = AST_TEST_PASS;
    char *tests[] = {
       "",
       "bored",
       "away,,,i",
       /* XXX The following actually is parsed correctly. Should that
        * be changed?
        * "away,,,,e",
        */
    };
    switch (cmd) {
    case TEST_INIT:
       info->name = "parse_invalid_presence_data";
       info->category = "/funcs/func_presence/";
       info->summary = "PRESENCESTATE parsing test";
       info->description =
          "Ensure that parsing function rejects improper values";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    for (i = 0; i < ARRAY_LEN(tests); ++i) {
       int parse_result;
       char *parse_string = ast_strdup(tests[i]);
       if (!parse_string) {
          res = AST_TEST_FAIL;
          break;
       }
       parse_result = parse_data(parse_string, &state, &subtype, &message, &options);
       if (parse_result == 0) {
          ast_log(LOG_WARNING, "Invalid string parsing failed on %s\n", tests[i]);
          res = AST_TEST_FAIL;
          ast_free(parse_string);
          break;
       }
       ast_free(parse_string);
    }
    return res;
 }
AST_TEST_DEFINE() [3/4]
AST_TEST_DEFINE (test_presence_state_change)
Definition at line 742 of file func_presencestate.c.
References AST_TEST_FAIL, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_test_status_update, sip_to_pjsip::info(), NULL, PRES_MESSAGE, PRES_STATE, PRES_SUBTYPE, presence_change_common(), TEST_EXECUTE, and TEST_INIT.
 {
    char out_state[32];
    char out_subtype[32];
    char out_message[32];
    switch (cmd) {
    case TEST_INIT:
       info->name = "test_presence_state_change";
       info->category = "/funcs/func_presence/";
       info->summary = "presence state change subscription";
       info->description =
          "Ensure that presence state changes are communicated to subscribers";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    if (presence_change_common(test, PRES_STATE, PRES_SUBTYPE, PRES_MESSAGE, NULL,
             out_state, sizeof(out_state),
             out_subtype, sizeof(out_subtype),
             out_message, sizeof(out_message)) == AST_TEST_FAIL) {
       return AST_TEST_FAIL;
    }
    if (strcmp(out_state, PRES_STATE) ||
          strcmp(out_subtype, PRES_SUBTYPE) ||
          strcmp(out_message, PRES_MESSAGE)) {
       ast_test_status_update(test, "Unexpected presence values, %s != %s, %s != %s, or %s != %s\n",
             PRES_STATE, out_state,
             PRES_SUBTYPE, out_subtype,
             PRES_MESSAGE, out_message);
       return AST_TEST_FAIL;
    }
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [4/4]
AST_TEST_DEFINE (test_presence_state_base64_encode)
Definition at line 780 of file func_presencestate.c.
References ast_base64encode(), AST_TEST_FAIL, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_test_status_update, sip_to_pjsip::info(), PRES_MESSAGE, PRES_STATE, PRES_SUBTYPE, presence_change_common(), TEST_EXECUTE, and TEST_INIT.
 {
    char out_state[32];
    char out_subtype[32];
    char out_message[32];
    char encoded_subtype[64];
    char encoded_message[64];
    switch (cmd) {
    case TEST_INIT:
       info->name = "test_presence_state_base64_encode";
       info->category = "/funcs/func_presence/";
       info->summary = "presence state base64 encoding";
       info->description =
          "Ensure that base64-encoded presence state is stored base64-encoded but\n"
          "is presented to consumers decoded.";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    ast_base64encode(encoded_subtype, (unsigned char *) PRES_SUBTYPE, strlen(PRES_SUBTYPE), sizeof(encoded_subtype) - 1);
    ast_base64encode(encoded_message, (unsigned char *) PRES_MESSAGE, strlen(PRES_MESSAGE), sizeof(encoded_message) - 1);
    if (presence_change_common(test, PRES_STATE, encoded_subtype, encoded_message, "e",
             out_state, sizeof(out_state),
             out_subtype, sizeof(out_subtype),
             out_message, sizeof(out_message)) == AST_TEST_FAIL) {
       return AST_TEST_FAIL;
    }
    if (strcmp(out_state, PRES_STATE) ||
          strcmp(out_subtype, PRES_SUBTYPE) ||
          strcmp(out_message, PRES_MESSAGE)) {
       ast_test_status_update(test, "Unexpected presence values, %s != %s, %s != %s, or %s != %s\n",
             PRES_STATE, out_state,
             PRES_SUBTYPE, out_subtype,
             PRES_MESSAGE, out_message);
       return AST_TEST_FAIL;
    }
    return AST_TEST_PASS;
 }
custom_presence_callback()
static enum ast_presence_state custom_presence_callback (const char * data, char ** subtype, char ** message) static
Definition at line 248 of file func_presencestate.c.
References ast_base64decode(), ast_db_get(), AST_PRESENCE_INVALID, AST_PRESENCE_NOT_SET, ast_strdup, ast_strlen_zero, astdb_family, buf, NULL, parse_data(), state, and tmp().
Referenced by load_module().
 {
    char buf[1301] = "";
    enum ast_presence_state state;
    char *_options;
    char *_message;
    char *_subtype;
    if (ast_db_get(astdb_family, data, buf, sizeof(buf))) {
       return AST_PRESENCE_NOT_SET;
    }
    if (parse_data(buf, &state, &_subtype, &_message, &_options)) {
       return AST_PRESENCE_INVALID;
    }
    if ((strchr(_options, 'e'))) {
       char tmp[1301];
       if (ast_strlen_zero(_subtype)) {
          *subtype = NULL;
       } else {
          memset(tmp, 0, sizeof(tmp));
          ast_base64decode((unsigned char *) tmp, _subtype, sizeof(tmp) - 1);
          *subtype = ast_strdup(tmp);
       }
       if (ast_strlen_zero(_message)) {
          *message = NULL;
       } else {
          memset(tmp, 0, sizeof(tmp));
          ast_base64decode((unsigned char *) tmp, _message, sizeof(tmp) - 1);
          *message = ast_strdup(tmp);
       }
    } else {
       *subtype = ast_strlen_zero(_subtype) ? NULL : ast_strdup(_subtype);
       *message = ast_strlen_zero(_message) ? NULL : ast_strdup(_message);
    }
    return state;
 }
handle_cli_presencestate_change()
static char* handle_cli_presencestate_change (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) static
Definition at line 366 of file func_presencestate.c.
References ast_cli_args::argc, args, ast_cli_entry::args, ast_cli_args::argv, ast_cli(), ast_cli_complete(), ast_db_put(), AST_PRESENCE_NOT_SET, ast_presence_state_changed_literal(), ast_strdupa, ast_strlen_zero, astdb_family, CLI_FAILURE, CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::command, ast_cli_args::fd, len(), ast_cli_args::n, NULL, options, parse_data(), ast_cli_args::pos, state, ast_cli_entry::usage, and ast_cli_args::word.
 {
     size_t len;
    const char *dev, *state, *full_dev;
    enum ast_presence_state state_val;
    char *message;
    char *subtype;
    char *options;
    char *args;
    switch (cmd) {
    case CLI_INIT:
       e->command = "presencestate change";
       e->usage =
          "Usage: presencestate change <entity> <state>[,<subtype>[,message[,options]]]\n"
          "       Change a custom presence to a new state.\n"
          "       The possible values for the state are:\n"
          "NOT_SET | UNAVAILABLE | AVAILABLE | AWAY | XA | CHAT | DND\n"
          "Optionally, a custom subtype and message may be provided, along with any options\n"
          "accepted by func_presencestate. If the subtype or message provided contain spaces,\n"
          "be sure to enclose the data in quotation marks (\"\")\n"
          "\n"
          "Examples:\n"
          "       presencestate change CustomPresence:mystate1 AWAY\n"
          "       presencestate change CustomPresence:mystate1 AVAILABLE\n"
          "       presencestate change CustomPresence:mystate1 \"Away,upstairs,eating lunch\"\n"
          "       \n";
       return NULL;
    case CLI_GENERATE:
    {
       static const char * const cmds[] = { "NOT_SET", "UNAVAILABLE", "AVAILABLE", "AWAY",
                        "XA", "CHAT", "DND", NULL };
       if (a->pos == e->args + 1) {
          return ast_cli_complete(a->word, cmds, a->n);
       }
       return NULL;
    }
    }
    if (a->argc != e->args + 2) {
       return CLI_SHOWUSAGE;
    }
    len = strlen("CustomPresence:");
    full_dev = dev = a->argv[e->args];
    state = a->argv[e->args + 1];
    if (strncasecmp(dev, "CustomPresence:", len)) {
       ast_cli(a->fd, "The presencestate command can only be used to set 'CustomPresence:' presence state!\n");
       return CLI_FAILURE;
    }
    dev += len;
    if (ast_strlen_zero(dev)) {
       return CLI_SHOWUSAGE;
    }
    args = ast_strdupa(state);
    if (parse_data(args, &state_val, &subtype, &message, &options)) {
       return CLI_SHOWUSAGE;
    }
    if (state_val == AST_PRESENCE_NOT_SET) {
       return CLI_SHOWUSAGE;
    }
    ast_cli(a->fd, "Changing %s to %s\n", dev, args);
    ast_db_put(astdb_family, dev, state);
    ast_presence_state_changed_literal(state_val, subtype, message, full_dev);
    return CLI_SUCCESS;
 }
handle_cli_presencestate_list()
static char* handle_cli_presencestate_list (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) static
Definition at line 295 of file func_presencestate.c.
References ast_cli_args::argc, ast_cli_entry::args, ast_cli(), AST_CLI_YESNO, ast_copy_string(), ast_db_freetree(), ast_db_gettree(), ast_log, ast_presence_state2str(), astdb_family, CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::command, ast_db_entry::data, ast_cli_args::fd, ast_db_entry::key, LOG_WARNING, ast_db_entry::next, NULL, options, parse_data(), state, and ast_cli_entry::usage.
 {
    struct ast_db_entry *db_entry, *db_tree;
    switch (cmd) {
    case CLI_INIT:
       e->command = "presencestate list";
       e->usage =
          "Usage: presencestate list\n"
          "       List all custom presence states that have been set by using\n"
          "       the PRESENCE_STATE dialplan function.\n";
       return NULL;
    case CLI_GENERATE:
       return NULL;
    }
    if (a->argc != e->args) {
       return CLI_SHOWUSAGE;
    }
    ast_cli(a->fd, "\n"
            "---------------------------------------------------------------------\n"
            "--- Custom Presence States ------------------------------------------\n"
            "---------------------------------------------------------------------\n"
            "---\n");
    db_entry = db_tree = ast_db_gettree(astdb_family, NULL);
    if (!db_entry) {
       ast_cli(a->fd, "No custom presence states defined\n");
       return CLI_SUCCESS;
    }
    for (; db_entry; db_entry = db_entry->next) {
       const char *object_name = strrchr(db_entry->key, '/') + 1;
       char state_info[1301];
       enum ast_presence_state state;
       char *subtype;
       char *message;
       char *options;
       ast_copy_string(state_info, db_entry->data, sizeof(state_info));
       if (parse_data(state_info, &state, &subtype, &message, &options)) {
          ast_log(LOG_WARNING, "Invalid CustomPresence entry %s encountered\n", db_entry->data);
          continue;
       }
       if (object_name <= (const char *) 1) {
          continue;
       }
       ast_cli(a->fd, "--- Name: 'CustomPresence:%s'\n"
                    "    --- State: '%s'\n"
                   "    --- Subtype: '%s'\n"
                   "    --- Message: '%s'\n"
                   "    --- Base64 Encoded: '%s'\n"
                      "---\n",
                   object_name,
                   ast_presence_state2str(state),
                   subtype,
                   message,
                   AST_CLI_YESNO(strchr(options, 'e')));
    }
    ast_db_freetree(db_tree);
    db_tree = NULL;
    ast_cli(a->fd,
            "---------------------------------------------------------------------\n"
            "---------------------------------------------------------------------\n"
            "\n");
    return CLI_SUCCESS;
 }
load_module()
static int load_module (void) static
Definition at line 842 of file func_presencestate.c.
References ARRAY_LEN, ast_cli_register_multiple, ast_custom_function_register, ast_db_freetree(), ast_db_gettree(), ast_free, AST_MODFLAG_LOAD_ORDER, AST_MODPRI_DEVSTATE_PROVIDER, AST_MODULE_INFO(), AST_MODULE_SUPPORT_CORE, ast_presence_state_changed(), ast_presence_state_prov_add(), AST_TEST_REGISTER, astdb_family, ASTERISK_GPL_KEY, custom_presence_callback(), ast_db_entry::key, test_string::message, ast_db_entry::next, NULL, state, test_string::subtype, and unload_module().
 {
    int res = 0;
    struct ast_db_entry *db_entry, *db_tree;
    /* Populate the presence state cache on the system with all of the currently
     * known custom presence states. */
    db_entry = db_tree = ast_db_gettree(astdb_family, NULL);
    for (; db_entry; db_entry = db_entry->next) {
       const char *dev_name = strrchr(db_entry->key, '/') + 1;
       enum ast_presence_state state;
       char *message;
       char *subtype;
       if (dev_name <= (const char *) 1) {
          continue;
       }
       state = custom_presence_callback(dev_name, &subtype, &message);
       ast_presence_state_changed(state, subtype, message, "CustomPresence:%s", dev_name);
       ast_free(subtype);
       ast_free(message);
    }
    ast_db_freetree(db_tree);
    db_tree = NULL;
    res |= ast_custom_function_register(&presence_function);
    res |= ast_presence_state_prov_add("CustomPresence", custom_presence_callback);
    res |= ast_cli_register_multiple(cli_funcpresencestate, ARRAY_LEN(cli_funcpresencestate));
 #ifdef TEST_FRAMEWORK
    AST_TEST_REGISTER(test_valid_parse_data);
    AST_TEST_REGISTER(test_invalid_parse_data);
    AST_TEST_REGISTER(test_presence_state_change);
    AST_TEST_REGISTER(test_presence_state_base64_encode);
 #endif
    return res;
 }
parse_data()
static int parse_data (char * data, enum ast_presence_state * state, char ** subtype, char ** message, char ** options) static
Definition at line 162 of file func_presencestate.c.
References ast_log, AST_PRESENCE_INVALID, ast_presence_state_val(), ast_strlen_zero, LOG_NOTICE, LOG_WARNING, and strsep().
Referenced by AST_TEST_DEFINE(), custom_presence_callback(), handle_cli_presencestate_change(), handle_cli_presencestate_list(), and presence_write().
 {
    char *state_str;
    /* data syntax is state,subtype,message,options */
    *subtype = "";
    *message = "";
    *options = "";
    state_str = strsep(&data, ",");
    if (ast_strlen_zero(state_str)) {
       return -1; /* state is required */
    }
    *state = ast_presence_state_val(state_str);
    /* not a valid state */
    if (*state == AST_PRESENCE_INVALID) {
       ast_log(LOG_WARNING, "Unknown presence state value %s\n", state_str);
       return -1;
    }
    if (!(*subtype = strsep(&data,","))) {
       *subtype = "";
       return 0;
    }
    if (!(*message = strsep(&data, ","))) {
       *message = "";
       return 0;
    }
    if (!(*options = strsep(&data, ","))) {
       *options = "";
       return 0;
    }
    if (!ast_strlen_zero(*options) && !(strchr(*options, 'e'))) {
       ast_log(LOG_NOTICE, "Invalid options  '%s'\n", *options);
       return -1;
    }
    return 0;
 }
presence_change_common()
static enum ast_test_result_state presence_change_common (struct ast_test * test, const char * state, const char * subtype, const char * message, const char * options, char * out_state, size_t out_state_size, char * out_subtype, size_t out_subtype_size, char * out_message, size_t out_message_size) static
Definition at line 705 of file func_presencestate.c.
References ast_copy_string(), ast_db_del(), ast_presence_state2str(), ast_presence_state_topic_all(), ast_sem_wait(), ast_strlen_zero, AST_TEST_FAIL, AST_TEST_PASS, NULL, presence_write(), RAII_VAR, stasis_subscribe, stasis_unsubscribe_and_join(), test_cb(), test_cb_data_alloc(), test_cb_data_destroy(), and test_sub().
Referenced by AST_TEST_DEFINE().
 {
    RAII_VAR(struct test_cb_data *, cb_data, test_cb_data_alloc(), test_cb_data_destroy);
    struct stasis_subscription *test_sub;
    char pres[1301];
    if (!(test_sub = stasis_subscribe(ast_presence_state_topic_all(), test_cb, cb_data))) {
       return AST_TEST_FAIL;
    }
    if (ast_strlen_zero(options)) {
       snprintf(pres, sizeof(pres), "%s,%s,%s", state, subtype, message);
    } else {
       snprintf(pres, sizeof(pres), "%s,%s,%s,%s", state, subtype, message, options);
    }
    if (presence_write(NULL, "PRESENCESTATE", "CustomPresence:TestPresenceStateChange", pres)) {
       test_sub = stasis_unsubscribe_and_join(test_sub);
       return AST_TEST_FAIL;
    }
    ast_sem_wait(&cb_data->sem);
    ast_copy_string(out_state, ast_presence_state2str(cb_data->presence_state->state), out_state_size);
    ast_copy_string(out_subtype, cb_data->presence_state->subtype, out_subtype_size);
    ast_copy_string(out_message, cb_data->presence_state->message, out_message_size);
    test_sub = stasis_unsubscribe_and_join(test_sub);
    ast_db_del("CustomPresence", "TestPresenceStateChange");
    return AST_TEST_PASS;
 }
presence_read()
static int presence_read (struct ast_channel * chan, const char * cmd, char * data, char * buf, size_t len) static
Definition at line 102 of file func_presencestate.c.
References args, AST_APP_ARG, ast_base64encode(), ast_copy_string(), AST_DECLARE_APP_ARGS, ast_free, ast_log, AST_PRESENCE_INVALID, ast_presence_state2str(), ast_presence_state_nocache(), AST_STANDARD_APP_ARGS, ast_strdupa, ast_strlen_zero, LOG_WARNING, NULL, options, parse(), provider, and state.
 {
    int state;
    char *message = NULL;
    char *subtype = NULL;
    char *parse;
    int base64encode = 0;
    AST_DECLARE_APP_ARGS(args,
       AST_APP_ARG(provider);
       AST_APP_ARG(field);
       AST_APP_ARG(options);
    );
    if (ast_strlen_zero(data)) {
       ast_log(LOG_WARNING, "PRESENCE_STATE reading requires an argument \n");
       return -1;
    }
    parse = ast_strdupa(data);
    AST_STANDARD_APP_ARGS(args, parse);
    if (ast_strlen_zero(args.provider) || ast_strlen_zero(args.field)) {
       ast_log(LOG_WARNING, "PRESENCE_STATE reading requires both presence provider and presence field arguments. \n");
       return -1;
    }
    state = ast_presence_state_nocache(args.provider, &subtype, &message);
    if (state == AST_PRESENCE_INVALID) {
       ast_log(LOG_WARNING, "PRESENCE_STATE unknown \n");
       return -1;
    }
    if (!(ast_strlen_zero(args.options)) && (strchr(args.options, 'e'))) {
       base64encode = 1;
    }
    if (!ast_strlen_zero(subtype) && !strcasecmp(args.field, "subtype")) {
       if (base64encode) {
          ast_base64encode(buf, (unsigned char *) subtype, strlen(subtype), len);
       } else {
          ast_copy_string(buf, subtype, len);
       }
    } else if (!ast_strlen_zero(message) && !strcasecmp(args.field, "message")) {
       if (base64encode) {
          ast_base64encode(buf, (unsigned char *) message, strlen(message), len);
       } else {
          ast_copy_string(buf, message, len);
       }
    } else if (!strcasecmp(args.field, "value")) {
       ast_copy_string(buf, ast_presence_state2str(state), len);
    }
    ast_free(message);
    ast_free(subtype);
    return 0;
 }
presence_write()
static int presence_write (struct ast_channel * chan, const char * cmd, char * data, const char * value) static
Definition at line 207 of file func_presencestate.c.
References args, ast_base64decode(), ast_db_put(), ast_log, ast_presence_state_changed_literal(), ast_strdupa, ast_strlen_zero, astdb_family, len(), LOG_WARNING, options, parse_data(), state, and tmp().
Referenced by presence_change_common().
 {
    size_t len = strlen("CustomPresence:");
    char *tmp = data;
    char *args = ast_strdupa(value);
    enum ast_presence_state state;
    char *options, *message, *subtype;
    if (strncasecmp(data, "CustomPresence:", len)) {
       ast_log(LOG_WARNING, "The PRESENCE_STATE function can only set CustomPresence: presence providers.\n");
       return -1;
    }
    data += len;
    if (ast_strlen_zero(data)) {
       ast_log(LOG_WARNING, "PRESENCE_STATE function called with no custom device name!\n");
       return -1;
    }
    if (parse_data(args, &state, &subtype, &message, &options)) {
       ast_log(LOG_WARNING, "Invalid arguments to PRESENCE_STATE\n");
       return -1;
    }
    ast_db_put(astdb_family, data, value);
    if (strchr(options, 'e')) {
       /* Let's decode the values before sending them to stasis, yes? */
       char decoded_subtype[256] = { 0, };
       char decoded_message[256] = { 0, };
       ast_base64decode((unsigned char *) decoded_subtype, subtype, sizeof(decoded_subtype) -1);
       ast_base64decode((unsigned char *) decoded_message, message, sizeof(decoded_message) -1);
       ast_presence_state_changed_literal(state, decoded_subtype, decoded_message, tmp);
    } else {
       ast_presence_state_changed_literal(state, subtype, message, tmp);
    }
    return 0;
 }
test_cb()
static void test_cb (void * userdata, struct stasis_subscription * sub, struct stasis_message * msg) static
Definition at line 693 of file func_presencestate.c.
References ao2_ref, ast_presence_state_message_type(), ast_sem_post(), test_cb_data::presence_state, test_cb_data::sem, stasis_message_data(), and stasis_message_type().
Referenced by presence_change_common().
 {
    struct test_cb_data *cb_data = userdata;
    if (stasis_message_type(msg) != ast_presence_state_message_type()) {
       return;
    }
    cb_data->presence_state = stasis_message_data(msg);
    ao2_ref(cb_data->presence_state, +1);
    ast_sem_post(&cb_data->sem);
 }
test_cb_data_alloc()
static struct test_cb_data* test_cb_data_alloc (void) static
Definition at line 670 of file func_presencestate.c.
References ast_calloc, ast_free, ast_sem_init(), NULL, and test_cb_data::sem.
Referenced by presence_change_common().
 {
    struct test_cb_data *cb_data = ast_calloc(1, sizeof(*cb_data));
    if (!cb_data) {
       return NULL;
    }
    if (ast_sem_init(&cb_data->sem, 0, 0)) {
       ast_free(cb_data);
       return NULL;
    }
    return cb_data;
 }
test_cb_data_destroy()
static void test_cb_data_destroy (struct test_cb_data * cb_data) static
Definition at line 686 of file func_presencestate.c.
References ao2_cleanup, ast_free, ast_sem_destroy(), test_cb_data::presence_state, and test_cb_data::sem.
Referenced by presence_change_common().
 {
    ao2_cleanup(cb_data->presence_state);
    ast_sem_destroy(&cb_data->sem);
    ast_free(cb_data);
 }
unload_module()
static int unload_module (void) static
Definition at line 826 of file func_presencestate.c.
References ARRAY_LEN, ast_cli_unregister_multiple(), ast_custom_function_unregister(), ast_presence_state_prov_del(), and AST_TEST_UNREGISTER.
Referenced by load_module().
 {
    int res = 0;
    res |= ast_custom_function_unregister(&presence_function);
    res |= ast_presence_state_prov_del("CustomPresence");
    res |= ast_cli_unregister_multiple(cli_funcpresencestate, ARRAY_LEN(cli_funcpresencestate));
 #ifdef TEST_FRAMEWORK
    AST_TEST_UNREGISTER(test_valid_parse_data);
    AST_TEST_UNREGISTER(test_invalid_parse_data);
    AST_TEST_UNREGISTER(test_presence_state_change);
    AST_TEST_UNREGISTER(test_presence_state_base64_encode);
 #endif
    return res;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Gets or sets a presence state in the dialplan" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEVSTATE_PROVIDER, } static
Definition at line 884 of file func_presencestate.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 884 of file func_presencestate.c.
astdb_family
const char astdb_family[] = "CustomPresence" static
Definition at line 100 of file func_presencestate.c.
Referenced by custom_presence_callback(), handle_cli_presencestate_change(), handle_cli_presencestate_list(), load_module(), and presence_write().
cli_funcpresencestate
struct ast_cli_entry cli_funcpresencestate[] static
Initial value:
= {
   { .handler =  handle_cli_presencestate_list , .summary =  "List currently know custom presence states" ,},
   { .handler =  handle_cli_presencestate_change , .summary =  "Change a custom presence state" ,},
}
Definition at line 443 of file func_presencestate.c.
presence_function
struct ast_custom_function presence_function static
Initial value:
= {
   .name = "PRESENCE_STATE",
   .read = presence_read,
   .write = presence_write,
}
Definition at line 289 of file func_presencestate.c.