Asterisk - The Open Source Telephony Project: ast_sorcery_wizard Struct Reference
ast_sorcery_wizard Struct Reference
Interface for a sorcery wizard.
#include <sorcery.h>
Data Fields
void(* close)(void *data)
Callback for closing a wizard.
int(* create)(const struct ast_sorcery *sorcery, void *data, void *object)
Callback for creating an object.
int(* delete)(const struct ast_sorcery *sorcery, void *data, void *object)
Callback for deleting an object.
void(* force_reload)(void *data, const struct ast_sorcery *sorcery, const char *type)
Optional callback for forcing a reload to occur, even if wizard has determined no changes.
int(* is_stale)(const struct ast_sorcery *sorcery, void *data, void *object)
void(* load)(void *data, const struct ast_sorcery *sorcery, const char *type)
Optional callback for loading persistent objects.
struct ast_module * module
Pointer to the Asterisk module this wizard is implemented by.
const char * name
Name of the wizard.
void *(* open)(const char *data)
Callback for opening a wizard.
void(* reload)(void *data, const struct ast_sorcery *sorcery, const char *type)
Optional callback for reloading persistent objects.
void *(* retrieve_fields)(const struct ast_sorcery *sorcery, void *data, const char *type, const struct ast_variable *fields)
Optional callback for retrieving an object using fields.
void *(* retrieve_id)(const struct ast_sorcery *sorcery, void *data, const char *type, const char *id)
Callback for retrieving an object using an id.
void(* retrieve_multiple)(const struct ast_sorcery *sorcery, void *data, const char *type, struct ao2_container *objects, const struct ast_variable *fields)
Optional callback for retrieving multiple objects using some optional field criteria.
void(* retrieve_prefix)(const struct ast_sorcery *sorcery, void *data, const char *type, struct ao2_container *objects, const char *prefix, const size_t prefix_len)
Optional callback for retrieving multiple objects by matching their id with a prefix.
void(* retrieve_regex)(const struct ast_sorcery *sorcery, void *data, const char *type, struct ao2_container *objects, const char *regex)
Callback for retrieving multiple objects using a regex on their id.
int(* update)(const struct ast_sorcery *sorcery, void *data, void *object)
Callback for updating an object.
Detailed Description
Interface for a sorcery wizard.
Definition at line 276 of file sorcery.h.
Field Documentation
close
void(* close) (void *data)
Callback for closing a wizard.
Definition at line 322 of file sorcery.h.
Referenced by AST_TEST_DEFINE(), and sorcery_object_wizard_destructor().
create
int(* create) (const struct ast_sorcery *sorcery, void *data, void *object)
Callback for creating an object.
Definition at line 293 of file sorcery.h.
Referenced by __ast_bucket_scheme_register(), bucket_file_wizard_create(), bucket_wizard_create(), handle_aor(), handle_auth(), handle_endpoint(), handle_identify(), handle_phoneprov(), handle_registrations(), sorcery_cache_create(), and sorcery_wizard_create().
delete
int(* delete) (const struct ast_sorcery *sorcery, void *data, void *object)
Callback for deleting an object.
Definition at line 319 of file sorcery.h.
Referenced by __ast_bucket_scheme_register(), bucket_file_wizard_delete(), bucket_wizard_delete(), delete_existing_cb(), handle_auth(), handle_identify(), handle_phoneprov(), and sorcery_wizard_delete().
force_reload
void(* force_reload) (void *data, const struct ast_sorcery *sorcery, const char *type)
Optional callback for forcing a reload to occur, even if wizard has determined no changes.
Definition at line 328 of file sorcery.h.
Referenced by sorcery_wizard_load().
is_stale
int(* is_stale) (const struct ast_sorcery *sorcery, void *data, void *object)
Definition at line 325 of file sorcery.h.
Referenced by ast_sorcery_is_stale(), bucket_file_wizard_is_stale(), and bucket_wizard_is_stale().
load
void(* load) (void *data, const struct ast_sorcery *sorcery, const char *type)
Optional callback for loading persistent objects.
Definition at line 287 of file sorcery.h.
Referenced by ApiDeclaration::load_file(), ResourceListing::load_file(), load_module(), and sorcery_wizard_load().
module
struct ast_module* module
Pointer to the Asterisk module this wizard is implemented by.
Definition at line 281 of file sorcery.h.
Referenced by __ast_sorcery_wizard_register(), and sorcery_object_wizard_destructor().
name
const char* name
Name of the wizard.
Definition at line 278 of file sorcery.h.
Referenced by __ast_sorcery_object_type_remove_wizard(), __ast_sorcery_wizard_register(), ast_sorcery_is_stale(), ast_sorcery_wizard_observer_add(), ast_sorcery_wizard_observer_remove(), ast_sorcery_wizard_unregister(), AST_TEST_DEFINE(), PathSegment::get_child(), Parameter::load(), SwaggerType::load(), Property::load(), sorcery_field_default_handler(), sorcery_wizard_create(), sorcery_wizard_delete(), sorcery_wizard_load(), sorcery_wizard_update(), wizard_mapped_observer(), and wizard_observer().
open
void*(* open) (const char *data)
Callback for opening a wizard.
Definition at line 284 of file sorcery.h.
reload
void(* reload) (void *data, const struct ast_sorcery *sorcery, const char *type)
Optional callback for reloading persistent objects.
Definition at line 290 of file sorcery.h.
Referenced by sorcery_wizard_load().
retrieve_fields
void*(* retrieve_fields) (const struct ast_sorcery *sorcery, void *data, const char *type, const struct ast_variable *fields)
Optional callback for retrieving an object using fields.
Definition at line 310 of file sorcery.h.
Referenced by ast_sorcery_retrieve_by_fields().
retrieve_id
void*(* retrieve_id) (const struct ast_sorcery *sorcery, void *data, const char *type, const char *id)
Callback for retrieving an object using an id.
Definition at line 296 of file sorcery.h.
Referenced by __ast_bucket_scheme_register(), ast_sorcery_retrieve_by_id(), handle_auth(), handle_identify(), and handle_phoneprov().
retrieve_multiple
void(* retrieve_multiple) (const struct ast_sorcery *sorcery, void *data, const char *type, struct ao2_container *objects, const struct ast_variable *fields)
Optional callback for retrieving multiple objects using some optional field criteria.
Definition at line 313 of file sorcery.h.
Referenced by ast_sorcery_retrieve_by_fields(), handle_registrations(), and object_type_loaded_observer().
retrieve_prefix
void(* retrieve_prefix) (const struct ast_sorcery *sorcery, void *data, const char *type, struct ao2_container *objects, const char *prefix, const size_t prefix_len)
Optional callback for retrieving multiple objects by matching their id with a prefix.
Definition at line 302 of file sorcery.h.
Referenced by ast_sorcery_retrieve_by_prefix().
retrieve_regex
void(* retrieve_regex) (const struct ast_sorcery *sorcery, void *data, const char *type, struct ao2_container *objects, const char *regex)
Callback for retrieving multiple objects using a regex on their id.
Definition at line 299 of file sorcery.h.
Referenced by ast_sorcery_retrieve_by_regex().
update
int(* update) (const struct ast_sorcery *sorcery, void *data, void *object)
Callback for updating an object.
Definition at line 316 of file sorcery.h.
Referenced by bucket_file_wizard_update(), handle_aor(), handle_auth(), handle_endpoint(), handle_identify(), handle_phoneprov(), handle_registrations(), and sorcery_wizard_update().
The documentation for this struct was generated from the following file:
sorcery.h