Asterisk - The Open Source Telephony Project: console_gui.c File Reference
console_gui.c File Reference
#include "asterisk.h"
#include "console_video.h"
#include "asterisk/lock.h"
#include "asterisk/frame.h"
#include "asterisk/utils.h"
#include <math.h>
Enumerations
enum {
WIN_LOCAL, WIN_REMOTE, WIN_KEYPAD, WIN_SRC1,
WIN_SRC2, WIN_SRC3, WIN_SRC4, WIN_SRC5,
WIN_SRC6, WIN_SRC7, WIN_SRC8, WIN_SRC9,
WIN_MAX
}
Functions
static struct gui_info * cleanup_sdl (struct gui_info *g, int n)
static void eventhandler (struct video_desc *env, const char *caption)
static int keypad_cfg_read (struct gui_info *gui, const char *val)
static void sdl_setup (struct video_desc *env)
static void show_frame (struct video_desc *env, int out)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
WIN_LOCAL
WIN_REMOTE
WIN_KEYPAD
WIN_SRC1
WIN_SRC2
WIN_SRC3
WIN_SRC4
WIN_SRC5
WIN_SRC6
WIN_SRC7
WIN_SRC8
WIN_SRC9
WIN_MAX
Definition at line 93 of file console_gui.c.
      { WIN_LOCAL, WIN_REMOTE, WIN_KEYPAD, WIN_SRC1,
    WIN_SRC2, WIN_SRC3, WIN_SRC4, WIN_SRC5,
    WIN_SRC6, WIN_SRC7, WIN_SRC8, WIN_SRC9, WIN_MAX };
Function Documentation
cleanup_sdl()
static struct gui_info* cleanup_sdl (struct gui_info * g, int n) static
Definition at line 100 of file console_gui.c.
References NULL.
Referenced by keypad_cfg_read().
 { return NULL; }
eventhandler()
static void eventhandler (struct video_desc * env, const char * caption) static
Definition at line 101 of file console_gui.c.
Referenced by keypad_cfg_read().
 {}
keypad_cfg_read()
static int keypad_cfg_read (struct gui_info * gui, const char * val) static
Definition at line 102 of file console_gui.c.
References a, ast_calloc, AST_FRAME_DTMF, ast_free, ast_log, ast_queue_frame(), ast_realloc, ast_skip_blanks(), ast_strlen_zero, ast_trim_blanks(), ast_tvdiff_ms(), ast_tvnow(), chan_oss_pvt::autoanswer, b, buf, c, cleanup_sdl(), console_do_answer(), console_grabbers, d, delete_board(), digit, DRAG_LOCAL, DRAG_MESSAGE, DRAG_NONE, DRAG_PIP, drag_info::drag_window, end, error(), eventhandler(), make_ari_stubs::file, find_desc(), fbuf_t::h, if(), sip_to_pjsip::info(), KEY_MUTE, KO_DIALED, KO_INPUT, KO_MESSAGE, LOG_ERROR, LOG_WARNING, MAX, move_message_board(), NULL, grab_desc::open, oss_active, out, fbuf_t::pix_fmt, print_message(), read_message(), reset_board(), sdl_setup(), show_frame(), SRC_WIN_H, SRC_WIN_W, ast_frame::subclass, text, type, fbuf_t::w, WIN_KEYPAD, WIN_LOCAL, WIN_MAX, WIN_REMOTE, WIN_SRC1, drag_info::x_start, and drag_info::y_start.
 { return 0; }
sdl_setup()
static void sdl_setup (struct video_desc * env) static
Definition at line 99 of file console_gui.c.
Referenced by keypad_cfg_read().
 {}
show_frame()
static void show_frame (struct video_desc * env, int out) static
Definition at line 98 of file console_gui.c.
Referenced by hook_event_cb(), and keypad_cfg_read().
 {}