Asterisk - The Open Source Telephony Project: resource_events.h File Reference
resource_events.h File Reference
Generated file - declares stubs to be implemented in res/ari/resource_events.c.
#include "asterisk/ari.h"
Data Structures
struct ast_ari_events_event_websocket_args
struct ast_ari_events_user_event_args
Functions
void ast_ari_events_user_event (struct ast_variable *headers, struct ast_ari_events_user_event_args *args, struct ast_ari_response *response)
Generate a user event.
int ast_ari_events_user_event_parse_body (struct ast_json *body, struct ast_ari_events_user_event_args *args)
Body parsing function for /events/user/{eventName}.
int ast_ari_websocket_events_event_websocket_attempted (struct ast_tcptls_session_instance *ser, struct ast_variable *headers, struct ast_ari_events_event_websocket_args *args, const char *session_id)
WebSocket connection for events.
void ast_ari_websocket_events_event_websocket_dtor (void)
WebSocket connection for events.
void ast_ari_websocket_events_event_websocket_established (struct ast_ari_websocket_session *session, struct ast_variable *headers, struct ast_ari_events_event_websocket_args *args)
WebSocket connection for events.
int ast_ari_websocket_events_event_websocket_init (void)
WebSocket connection for events.
Detailed Description
Generated file - declares stubs to be implemented in res/ari/resource_events.c.
WebSocket resource
Author
David M. Lee, II dlee@.nosp@m.digi.nosp@m.um.co.nosp@m.m
Definition in file resource_events.h.
Function Documentation
ast_ari_events_user_event()
void ast_ari_events_user_event (struct ast_variable * headers, struct ast_ari_events_user_event_args * args, struct ast_ari_response * response)
Generate a user event.
Parameters
headers HTTP headers
args Swagger parameters
[out] response HTTP response
Definition at line 532 of file resource_events.c.
References ast_ari_events_user_event_args::application, ast_ari_events_user_event_parse_body(), ast_ari_response_error(), ast_ari_response_no_content(), ast_json_object_get(), ast_strlen_zero, ast_ari_events_user_event_args::event_name, NULL, ast_ari_events_user_event_args::source, ast_ari_events_user_event_args::source_count, STASIS_APP_USER_APP_NOT_FOUND, stasis_app_user_event(), STASIS_APP_USER_EVENT_SOURCE_BAD_SCHEME, STASIS_APP_USER_EVENT_SOURCE_NOT_FOUND, STASIS_APP_USER_INTERNAL_ERROR, STASIS_APP_USER_OK, STASIS_APP_USER_USEREVENT_INVALID, and ast_ari_events_user_event_args::variables.
Referenced by ast_ari_events_user_event_cb().
 {
    enum stasis_app_user_event_res res;
    struct ast_json *json_variables = NULL;
    if (args->variables) {
       ast_ari_events_user_event_parse_body(args->variables, args);
       json_variables = ast_json_object_get(args->variables, "variables");
    }
    if (ast_strlen_zero(args->application)) {
       ast_ari_response_error(response, 400, "Bad Request",
          "Missing parameter application");
       return;
    }
    res = stasis_app_user_event(args->application,
       args->event_name,
       args->source, args->source_count,
       json_variables);
    switch (res) {
    case STASIS_APP_USER_OK:
       ast_ari_response_no_content(response);
       break;
    case STASIS_APP_USER_APP_NOT_FOUND:
       ast_ari_response_error(response, 404, "Not Found",
          "Application not found");
       break;
    case STASIS_APP_USER_EVENT_SOURCE_NOT_FOUND:
       ast_ari_response_error(response, 422, "Unprocessable Entity",
          "Event source was not found");
       break;
    case STASIS_APP_USER_EVENT_SOURCE_BAD_SCHEME:
       ast_ari_response_error(response, 400, "Bad Request",
          "Invalid event source URI scheme");
       break;
    case STASIS_APP_USER_USEREVENT_INVALID:
       ast_ari_response_error(response, 400, "Bad Request",
          "Invalid userevnet data");
       break;
    case STASIS_APP_USER_INTERNAL_ERROR:
    default:
       ast_ari_response_error(response, 500, "Internal Server Error",
          "Error processing request");
    }
 }
ast_ari_events_user_event_parse_body()
int ast_ari_events_user_event_parse_body (struct ast_json * body, struct ast_ari_events_user_event_args * args)
Body parsing function for /events/user/{eventName}.
Parameters
body The JSON body from which to parse parameters.
[out] args The args structure to parse into.
Return values
zero on success
non-zero on failure
Definition at line 241 of file res_ari_events.c.
References ast_ari_events_user_event_args::application, ast_free, AST_JSON_ARRAY, ast_json_array_get(), ast_json_array_size(), ast_json_object_get(), ast_json_string_get(), ast_json_typeof(), ast_malloc, ast_ari_events_user_event_args::source, and ast_ari_events_user_event_args::source_count.
Referenced by ast_ari_events_user_event().
 {
    struct ast_json *field;
    /* Parse query parameters out of it */
    field = ast_json_object_get(body, "application");
    if (field) {
       args->application = ast_json_string_get(field);
    }
    field = ast_json_object_get(body, "source");
    if (field) {
       /* If they were silly enough to both pass in a query param and a
        * JSON body, free up the query value.
        */
       ast_free(args->source);
       if (ast_json_typeof(field) == AST_JSON_ARRAY) {
          /* Multiple param passed as array */
          size_t i;
          args->source_count = ast_json_array_size(field);
          args->source = ast_malloc(sizeof(*args->source) * args->source_count);
          if (!args->source) {
             return -1;
          }
          for (i = 0; i < args->source_count; ++i) {
             args->source[i] = ast_json_string_get(ast_json_array_get(field, i));
          }
       } else {
          /* Multiple param passed as single value */
          args->source_count = 1;
          args->source = ast_malloc(sizeof(*args->source) * args->source_count);
          if (!args->source) {
             return -1;
          }
          args->source[0] = ast_json_string_get(field);
       }
    }
    return 0;
 }
ast_ari_websocket_events_event_websocket_attempted()
int ast_ari_websocket_events_event_websocket_attempted (struct ast_tcptls_session_instance * ser, struct ast_variable * headers, struct ast_ari_events_event_websocket_args * args, const char * session_id)
WebSocket connection for events.
Parameters
ser HTTP TCP/TLS Server Session
headers HTTP headers
args Swagger parameters
session_id The id of the current session.
Return values
0 success
non-zero error
Definition at line 488 of file resource_events.c.
References ast_debug, and event_session_alloc().
Referenced by ast_ari_events_event_websocket_ws_attempted_cb().
 {
    ast_debug(3, "/events WebSocket attempted\n");
    /* Create the event session */
    return event_session_alloc(ser, args, session_id);
 }
ast_ari_websocket_events_event_websocket_dtor()
void ast_ari_websocket_events_event_websocket_dtor (void)
WebSocket connection for events.
Returns
Nothing
Definition at line 465 of file resource_events.c.
References ao2_callback, ao2_cleanup, event_session_shutdown_cb(), NULL, OBJ_MULTIPLE, and OBJ_NODATA.
Referenced by load_module(), and unload_module().
 {
    ao2_callback(event_session_registry, OBJ_MULTIPLE | OBJ_NODATA, event_session_shutdown_cb, NULL);
    ao2_cleanup(event_session_registry);
    event_session_registry = NULL;
 }
ast_ari_websocket_events_event_websocket_established()
void ast_ari_websocket_events_event_websocket_established (struct ast_ari_websocket_session * session, struct ast_variable * headers, struct ast_ari_events_event_websocket_args * args)
WebSocket connection for events.
Parameters
session ARI WebSocket.
headers HTTP headers.
args Swagger parameters.
session_id The id of the current session.
Definition at line 498 of file resource_events.c.
References ao2_find, ao2_ref, ao2_unlink, ast_ari_websocket_session_id(), ast_ari_websocket_session_read(), ast_assert, ast_debug, ast_json_unref(), ast_log, event_session_cleanup(), event_session_update_websocket(), LOG_WARNING, NULL, OBJ_SEARCH_KEY, and session.
Referenced by ast_ari_events_event_websocket_ws_established_cb().
 {
    struct event_session *session;
    struct ast_json *msg;
    const char *session_id;
    ast_debug(3, "/events WebSocket established\n");
    ast_assert(ws_session != NULL);
    session_id = ast_ari_websocket_session_id(ws_session);
    /* Find the event_session and update its websocket  */
    session = ao2_find(event_session_registry, session_id, OBJ_SEARCH_KEY);
    if (session) {
       ao2_unlink(event_session_registry, session);
       event_session_update_websocket(session, ws_session);
    } else {
       ast_log(LOG_WARNING,
          "Failed to locate an event session for the provided websocket session\n");
    }
    /* We don't process any input, but we'll consume it waiting for EOF */
    while ((msg = ast_ari_websocket_session_read(ws_session))) {
       ast_json_unref(msg);
    }
    event_session_cleanup(session);
    ao2_ref(session, -1);
 }
ast_ari_websocket_events_event_websocket_init()
int ast_ari_websocket_events_event_websocket_init (void)
WebSocket connection for events.
Return values
0 success
-1 error
Definition at line 473 of file resource_events.c.
References AO2_ALLOC_OPT_LOCK_MUTEX, ao2_container_alloc_hash, ast_log, event_session_compare(), event_session_hash(), EVENT_SESSION_NUM_BUCKETS, LOG_WARNING, and NULL.
Referenced by load_module().
 {
    /* Try to instantiate the registry */
    event_session_registry = ao2_container_alloc_hash(AO2_ALLOC_OPT_LOCK_MUTEX, 0,
       EVENT_SESSION_NUM_BUCKETS, event_session_hash, NULL, event_session_compare);
    if (!event_session_registry) {
       /* This is bad, bad. */
       ast_log(LOG_WARNING,
              "Failed to allocate the local registry for websocket applications\n");
       return -1;
    }
    return 0;
 }