Asterisk - The Open Source Telephony Project: features_config.c File Reference
features_config.c File Reference
#include "asterisk.h"
#include "asterisk/features_config.h"
#include "asterisk/config_options.h"
#include "asterisk/datastore.h"
#include "asterisk/channel.h"
#include "asterisk/pbx.h"
#include "asterisk/app.h"
#include "asterisk/cli.h"
#include "features_config.h"
Data Structures
struct dummy_config
struct featuregroup
Featuregroup representation.
struct featuregroup_item
Entry in the container of featuregroups.
struct features_config
struct features_global_config
Configuration from the "general" section of features.conf.
Macros
#define DEFAULT_ATXFER_ABORT "*1"
#define DEFAULT_ATXFER_CALLBACK_RETRIES 2
#define DEFAULT_ATXFER_COMPLETE "*2"
#define DEFAULT_ATXFER_DROP_CALL 0
#define DEFAULT_ATXFER_LOOP_DELAY 10
#define DEFAULT_ATXFER_SWAP "*4"
#define DEFAULT_ATXFER_THREEWAY "*3"
#define DEFAULT_COURTESY_TONE ""
#define DEFAULT_FEATURE_DIGIT_TIMEOUT 1000
#define DEFAULT_FEATUREMAP_ATXFER ""
#define DEFAULT_FEATUREMAP_AUTOMIXMON ""
#define DEFAULT_FEATUREMAP_AUTOMON ""
#define DEFAULT_FEATUREMAP_BLINDXFER "#"
#define DEFAULT_FEATUREMAP_DISCONNECT "*"
#define DEFAULT_FEATUREMAP_PARKCALL ""
#define DEFAULT_NOANSWER_TIMEOUT_ATTENDED_TRANSFER 15
#define DEFAULT_PICKUPEXTEN "*8"
#define DEFAULT_PICKUPFAILSOUND ""
#define DEFAULT_PICKUPSOUND ""
#define DEFAULT_RECORDING_FAIL_SOUND ""
#define DEFAULT_TRANSFER_DIAL_ATTEMPTS 3
#define DEFAULT_TRANSFER_DIGIT_TIMEOUT 3
#define DEFAULT_TRANSFER_INVALID_SOUND "privacy-incorrect"
#define DEFAULT_TRANSFER_RETRY_SOUND "pbx-invalid"
#define DEFAULT_XFERFAILSOUND "beeperr"
#define DEFAULT_XFERSOUND "beep"
#define HFS_FORMAT "%-25s %-7s %-7s\n"
Functions
static struct features_config * __features_config_alloc (int allocate_applicationmap)
static int add_item (void *obj, void *arg, int flags)
AO2_GLOBAL_OBJ_STATIC (globals)
static struct ao2_container * applicationmap_alloc (int replace_duplicates)
static int applicationmap_handler (const struct aco_option *opt, struct ast_variable *var, void *obj)
static struct ast_applicationmap_item * applicationmap_item_alloc (const char *name, const char *app, const char *app_data, const char *moh_class, const char *dtmf, unsigned int activate_on_self)
static int applicationmap_sort (const void *obj, const void *arg, int flags)
static void ast_applicationmap_item_destructor (void *obj)
int ast_get_builtin_feature (struct ast_channel *chan, const char *feature, char *buf, size_t len)
Get the DTMF code for a builtin feature.
struct ao2_container * ast_get_chan_applicationmap (struct ast_channel *chan)
Get the applicationmap for a given channel.
struct ast_featuremap_config * ast_get_chan_featuremap_config (struct ast_channel *chan)
Get the featuremap configuration options for a channel.
char * ast_get_chan_features_atxferabort (struct ast_channel *chan)
Get the transfer configuration option atxferabort.
struct ast_features_general_config * ast_get_chan_features_general_config (struct ast_channel *chan)
Get the general configuration options for a channel.
struct ast_features_pickup_config * ast_get_chan_features_pickup_config (struct ast_channel *chan)
Get the pickup configuration options for a channel.
struct ast_features_xfer_config * ast_get_chan_features_xfer_config (struct ast_channel *chan)
Get the transfer configuration options for a channel.
char * ast_get_chan_features_xferfailsound (struct ast_channel *chan)
Get the transfer configuration option xferfailsound.
int ast_get_feature (struct ast_channel *chan, const char *feature, char *buf, size_t len)
Get the DTMF code for a call feature.
static int check_featuregroup (void *obj, void *arg, void *data, int flags)
static int check_featuregroup_item (void *obj, void *arg, void *data, int flags)
CONFIG_INFO_CORE ("features", cfg_info, globals, features_config_alloc,.files=ACO_FILES(&features_conf),.pre_apply_config=features_pre_apply_config,)
static void feature_ds_destroy (void *data)
static void * feature_ds_duplicate (void *data)
static int feature_read (struct ast_channel *chan, const char *cmd, char *data, char *buf, size_t len)
static int feature_write (struct ast_channel *chan, const char *cmd, char *data, const char *value)
static void * featuregroup_alloc (const char *cat)
static int featuregroup_cmp (void *obj, void *arg, int flags)
static void featuregroup_destructor (void *obj)
static void * featuregroup_find (struct ao2_container *group_container, const char *category)
static int featuregroup_handler (const struct aco_option *opt, struct ast_variable *var, void *obj)
static int featuregroup_hash (const void *obj, int flags)
static void featuregroup_item_destructor (void *obj)
static void featuremap_config_destructor (void *obj)
static void featuremap_copy (struct ast_featuremap_config *dest, const struct ast_featuremap_config *src)
static int featuremap_get (struct ast_featuremap_config *featuremap, const char *field, char *buf, size_t len)
static int featuremap_handler (const struct aco_option *opt, struct ast_variable *var, void *obj)
static int featuremap_read (struct ast_channel *chan, const char *cmd, char *data, char *buf, size_t len)
static int featuremap_set (struct ast_featuremap_config *featuremap, const char *name, const char *value)
static int featuremap_write (struct ast_channel *chan, const char *cmd, char *data, const char *value)
static void * features_config_alloc (void)
static void features_config_destructor (void *obj)
static struct features_config * features_config_dup (const struct features_config *orig)
static void features_copy (struct features_config *dest, const struct features_config *src)
static int features_pre_apply_config (void)
static void general_copy (struct ast_features_general_config *dest, const struct ast_features_general_config *src)
static void general_destructor (void *obj)
static int general_get (struct ast_features_general_config *general, const char *field, char *buf, size_t len)
static int general_handler (const struct aco_option *opt, struct ast_variable *var, void *obj)
static int general_set (struct ast_features_general_config *general, const char *name, const char *value)
static struct ast_datastore * get_feature_chan_ds (struct ast_channel *chan)
static struct features_config * get_feature_ds (struct ast_channel *chan)
static struct features_global_config * global_config_alloc (void)
static void global_config_destructor (void *obj)
static void global_copy (struct features_global_config *dest, const struct features_global_config *src)
static int group_item_sort (const void *obj, const void *arg, int flags)
static char * handle_feature_show (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
CLI command to list configured features.
static int internal_feature_read (struct ast_channel *chan, const char *cmd, char *data, char *buf, size_t len)
static int internal_feature_write (struct ast_channel *chan, const char *cmd, char *data, const char *value)
static int internal_featuremap_read (struct ast_channel *chan, const char *cmd, char *data, char *buf, size_t len)
static int internal_featuremap_write (struct ast_channel *chan, const char *cmd, char *data, const char *value)
static int load_config (void)
int load_features_config (void)
static void pickup_copy (struct ast_features_pickup_config *dest, const struct ast_features_pickup_config *src)
static void pickup_destructor (void *obj)
static int pickup_get (struct ast_features_pickup_config *pickup, const char *field, char *buf, size_t len)
static int pickup_handler (const struct aco_option *opt, struct ast_variable *var, void *obj)
static int pickup_set (struct ast_features_pickup_config *pickup, const char *name, const char *value)
static int print_applicationmap (void *obj, void *arg, int flags)
static int print_featuregroup (void *obj, void *arg, int flags)
static int print_featuregroups (void *obj, void *arg, int flags)
int reload_features_config (void)
void unload_features_config (void)
static int unsupported_handler (const struct aco_option *opt, struct ast_variable *var, void *obj)
static void xfer_copy (struct ast_features_xfer_config *dest, const struct ast_features_xfer_config *src)
static void xfer_destructor (void *obj)
static int xfer_get (struct ast_features_xfer_config *xfer, const char *field, char *buf, size_t len)
static int xfer_handler (const struct aco_option *opt, struct ast_variable *var, void *obj)
static int xfer_set (struct ast_features_xfer_config *xfer, const char *name, const char *value)
Variables
static struct aco_type applicationmap_option
static struct aco_type * applicationmap_options [] = ACO_TYPES(&applicationmap_option)
static struct ast_cli_entry cli_features_config []
static const struct ast_datastore_info feature_ds_info
static struct ast_custom_function feature_function
static struct aco_type featuregroup_option
static struct aco_type * featuregroup_options [] = ACO_TYPES(&featuregroup_option)
static struct ast_custom_function featuremap_function
static struct aco_type featuremap_option
static struct aco_type * featuremap_options [] = ACO_TYPES(&featuremap_option)
static struct aco_file features_conf
static struct aco_type global_option
static struct aco_type * global_options [] = ACO_TYPES(&global_option)
static int parking_warning = 0
static struct aco_type parkinglot_option
static struct aco_type * parkinglot_options [] = ACO_TYPES(&parkinglot_option)
Macro Definition Documentation
DEFAULT_ATXFER_ABORT
#define DEFAULT_ATXFER_ABORT "*1"
Definition at line 379 of file features_config.c.
Referenced by load_config().
DEFAULT_ATXFER_CALLBACK_RETRIES
#define DEFAULT_ATXFER_CALLBACK_RETRIES 2
Definition at line 376 of file features_config.c.
Referenced by load_config().
DEFAULT_ATXFER_COMPLETE
#define DEFAULT_ATXFER_COMPLETE "*2"
Definition at line 380 of file features_config.c.
Referenced by load_config().
DEFAULT_ATXFER_DROP_CALL
#define DEFAULT_ATXFER_DROP_CALL 0
Definition at line 374 of file features_config.c.
Referenced by load_config().
DEFAULT_ATXFER_LOOP_DELAY
#define DEFAULT_ATXFER_LOOP_DELAY 10
Definition at line 375 of file features_config.c.
Referenced by load_config().
DEFAULT_ATXFER_SWAP
#define DEFAULT_ATXFER_SWAP "*4"
Definition at line 382 of file features_config.c.
Referenced by load_config().
DEFAULT_ATXFER_THREEWAY
#define DEFAULT_ATXFER_THREEWAY "*3"
Definition at line 381 of file features_config.c.
Referenced by load_config().
DEFAULT_COURTESY_TONE
#define DEFAULT_COURTESY_TONE ""
Definition at line 368 of file features_config.c.
Referenced by load_config().
DEFAULT_FEATURE_DIGIT_TIMEOUT
#define DEFAULT_FEATURE_DIGIT_TIMEOUT 1000
Default general options
Definition at line 367 of file features_config.c.
Referenced by load_config().
DEFAULT_FEATUREMAP_ATXFER
#define DEFAULT_FEATUREMAP_ATXFER ""
Definition at line 396 of file features_config.c.
Referenced by handle_feature_show(), and load_config().
DEFAULT_FEATUREMAP_AUTOMIXMON
#define DEFAULT_FEATUREMAP_AUTOMIXMON ""
Definition at line 398 of file features_config.c.
Referenced by handle_feature_show(), and load_config().
DEFAULT_FEATUREMAP_AUTOMON
#define DEFAULT_FEATUREMAP_AUTOMON ""
Definition at line 395 of file features_config.c.
Referenced by handle_feature_show(), and load_config().
DEFAULT_FEATUREMAP_BLINDXFER
#define DEFAULT_FEATUREMAP_BLINDXFER "#"
Default featuremap options
Definition at line 393 of file features_config.c.
Referenced by handle_feature_show(), and load_config().
DEFAULT_FEATUREMAP_DISCONNECT
#define DEFAULT_FEATUREMAP_DISCONNECT "*"
Definition at line 394 of file features_config.c.
Referenced by handle_feature_show(), and load_config().
DEFAULT_FEATUREMAP_PARKCALL
#define DEFAULT_FEATUREMAP_PARKCALL ""
Definition at line 397 of file features_config.c.
Referenced by handle_feature_show(), and load_config().
DEFAULT_NOANSWER_TIMEOUT_ATTENDED_TRANSFER
#define DEFAULT_NOANSWER_TIMEOUT_ATTENDED_TRANSFER 15
Definition at line 373 of file features_config.c.
Referenced by load_config().
DEFAULT_PICKUPEXTEN
#define DEFAULT_PICKUPEXTEN "*8"
Default pickup options
Definition at line 388 of file features_config.c.
Referenced by handle_feature_show(), and load_config().
DEFAULT_PICKUPFAILSOUND
#define DEFAULT_PICKUPFAILSOUND ""
Definition at line 390 of file features_config.c.
Referenced by load_config().
DEFAULT_PICKUPSOUND
#define DEFAULT_PICKUPSOUND ""
Definition at line 389 of file features_config.c.
Referenced by load_config().
DEFAULT_RECORDING_FAIL_SOUND
#define DEFAULT_RECORDING_FAIL_SOUND ""
Definition at line 369 of file features_config.c.
Referenced by load_config().
DEFAULT_TRANSFER_DIAL_ATTEMPTS
#define DEFAULT_TRANSFER_DIAL_ATTEMPTS 3
Definition at line 383 of file features_config.c.
Referenced by load_config().
DEFAULT_TRANSFER_DIGIT_TIMEOUT
#define DEFAULT_TRANSFER_DIGIT_TIMEOUT 3
Default xfer options
Definition at line 372 of file features_config.c.
Referenced by load_config().
DEFAULT_TRANSFER_INVALID_SOUND
#define DEFAULT_TRANSFER_INVALID_SOUND "privacy-incorrect"
Definition at line 385 of file features_config.c.
Referenced by load_config().
DEFAULT_TRANSFER_RETRY_SOUND
#define DEFAULT_TRANSFER_RETRY_SOUND "pbx-invalid"
Definition at line 384 of file features_config.c.
Referenced by load_config().
DEFAULT_XFERFAILSOUND
#define DEFAULT_XFERFAILSOUND "beeperr"
Definition at line 378 of file features_config.c.
Referenced by load_config().
DEFAULT_XFERSOUND
#define DEFAULT_XFERSOUND "beep"
Definition at line 377 of file features_config.c.
Referenced by load_config().
HFS_FORMAT
#define HFS_FORMAT "%-25s %-7s %-7s\n"
Definition at line 1903 of file features_config.c.
Referenced by handle_feature_show(), and print_applicationmap().
Function Documentation
__features_config_alloc()
static struct features_config* __features_config_alloc (int allocate_applicationmap) static
Definition at line 732 of file features_config.c.
References ao2_alloc, AO2_ALLOC_OPT_LOCK_NOLOCK, ao2_cleanup, ao2_container_alloc_hash, ao2_ref, applicationmap_alloc(), ast_string_field_init, featuregroup_cmp(), featuregroup_hash(), featuremap_config_destructor(), features_config_destructor(), global_config_alloc(), NULL, and RAII_VAR.
Referenced by features_config_alloc(), and features_config_dup().
 {
    RAII_VAR(struct features_config *, cfg, NULL, ao2_cleanup);
    cfg = ao2_alloc(sizeof(*cfg), features_config_destructor);
    if (!cfg) {
       return NULL;
    }
    cfg->global = global_config_alloc();
    if (!cfg->global) {
       return NULL;
    }
    cfg->featuremap = ao2_alloc(sizeof(*cfg->featuremap), featuremap_config_destructor);
    if (!cfg->featuremap || ast_string_field_init(cfg->featuremap, 32)) {
       return NULL;
    }
    cfg->parkinglots = ao2_alloc(sizeof(*cfg->parkinglots), NULL);
    if (!cfg->parkinglots) {
       return NULL;
    }
    if (allocate_applicationmap) {
       cfg->applicationmap = applicationmap_alloc(1);
       if (!cfg->applicationmap) {
          return NULL;
       }
       cfg->featuregroups = ao2_container_alloc_hash(AO2_ALLOC_OPT_LOCK_NOLOCK, 0, 11,
          featuregroup_hash, NULL, featuregroup_cmp);
       if (!cfg->featuregroups) {
          return NULL;
       }
    }
    ao2_ref(cfg, +1);
    return cfg;
 }
add_item()
static int add_item (void * obj, void * arg, int flags) static
Definition at line 1296 of file features_config.c.
References ast_applicationmap_item::activate_on_self, ao2_cleanup, ao2_link, ao2_ref, ast_applicationmap_item::app, ast_applicationmap_item::app_data, applicationmap_item_alloc(), featuregroup_item::appmap_item, featuregroup_item::appmap_item_name, ast_strlen_zero, featuregroup_item::dtmf_override, ast_applicationmap_item::moh_class, NULL, and RAII_VAR.
Referenced by ast_get_chan_applicationmap().
 {
    struct featuregroup_item *fg_item = obj;
    struct ao2_container *applicationmap = arg;
    RAII_VAR(struct ast_applicationmap_item *, appmap_item, NULL, ao2_cleanup);
    /* If there's no DTMF override, then we can just link
     * the applicationmap item directly. Otherwise, we need
     * to create a copy with the DTMF override in place and
     * link that instead
     */
    if (ast_strlen_zero(fg_item->dtmf_override)) {
       ao2_ref(fg_item->appmap_item, +1);
       appmap_item = fg_item->appmap_item;
    } else {
       appmap_item = applicationmap_item_alloc(fg_item->appmap_item_name,
             fg_item->appmap_item->app, fg_item->appmap_item->app_data,
             fg_item->appmap_item->moh_class, fg_item->dtmf_override,
             fg_item->appmap_item->activate_on_self);
    }
    if (!appmap_item) {
       return 0;
    }
    ao2_link(applicationmap, appmap_item);
    return 0;
 }
AO2_GLOBAL_OBJ_STATIC()
AO2_GLOBAL_OBJ_STATIC (globals)
applicationmap_alloc()
static struct ao2_container* applicationmap_alloc (int replace_duplicates) static
Definition at line 712 of file features_config.c.
References AO2_ALLOC_OPT_LOCK_NOLOCK, ao2_container_alloc_list, AO2_CONTAINER_ALLOC_OPT_DUPS_ALLOW, AO2_CONTAINER_ALLOC_OPT_DUPS_REPLACE, applicationmap_sort(), and NULL.
Referenced by __features_config_alloc(), and ast_get_chan_applicationmap().
 {
    return ao2_container_alloc_list(AO2_ALLOC_OPT_LOCK_NOLOCK,
       replace_duplicates ? AO2_CONTAINER_ALLOC_OPT_DUPS_REPLACE : AO2_CONTAINER_ALLOC_OPT_DUPS_ALLOW,
       applicationmap_sort, NULL);
 }
applicationmap_handler()
static int applicationmap_handler (const struct aco_option * opt, struct ast_variable * var, void * obj) static
Definition at line 1382 of file features_config.c.
References ao2_cleanup, ao2_link, app, applicationmap_item_alloc(), args, AST_APP_ARG, ast_debug, AST_DECLARE_APP_ARGS, ast_log, AST_STANDARD_APP_ARGS, ast_strdupa, ast_strip_quoted(), ast_strlen_zero, item, LOG_WARNING, ast_variable::name, NULL, paren, parse(), RAII_VAR, and ast_variable::value.
Referenced by load_config().
 {
    RAII_VAR(struct ast_applicationmap_item *, item, NULL, ao2_cleanup);
    struct ao2_container *applicationmap = obj;
    AST_DECLARE_APP_ARGS(args,
       AST_APP_ARG(dtmf);
       AST_APP_ARG(activate_on);
       AST_APP_ARG(app);
       AST_APP_ARG(app_data);
       AST_APP_ARG(moh_class);
    );
    char *parse = ast_strdupa(var->value);
    char *slash;
    char *paren;
    unsigned int activate_on_self;
    AST_STANDARD_APP_ARGS(args, parse);
    if (ast_strlen_zero(args.dtmf) ||
          ast_strlen_zero(args.activate_on) ||
          ast_strlen_zero(args.app)) {
       ast_log(LOG_WARNING, "Invalid applicationmap syntax for '%s'. Missing required argument\n", var->name);
       return -1;
    }
    /* features.conf used to have an "activated_by" portion
     * in addition to activate_on. Get rid of whatever may be
     * there
     */
    slash = strchr(args.activate_on, '/');
    if (slash) {
       *slash = '\0';
    }
    /* Some applications do not require arguments. */
    if (!args.app_data) {
       args.app_data = "";
    }
    /* Two syntaxes allowed for applicationmap:
     * Old: foo = *1,self,NoOp,Boo!,default
     * New: foo = *1,self,NoOp(Boo!),default
     *
     * We need to handle both
     */
    paren = strchr(args.app, '(');
    if (paren) {
       /* New syntax */
       char *close_paren;
       args.moh_class = args.app_data;
       *paren++ = '\0';
       close_paren = strrchr(paren, ')');
       if (close_paren) {
          *close_paren = '\0';
       }
       args.app_data = paren;
       /* Re-check that the application is not empty */
       if (ast_strlen_zero(args.app)) {
          ast_log(LOG_WARNING, "Applicationmap item '%s' does not contain an application name.\n", var->name);
          return -1;
       }
    } else if (strchr(args.app_data, '"')) {
       args.app_data = ast_strip_quoted(args.app_data, "\"", "\"");
    }
    /* Allow caller and callee to be specified for backwards compatibility */
    if (!strcasecmp(args.activate_on, "self") || !strcasecmp(args.activate_on, "caller")) {
       activate_on_self = 1;
    } else if (!strcasecmp(args.activate_on, "peer") || !strcasecmp(args.activate_on, "callee")) {
       activate_on_self = 0;
    } else {
       ast_log(LOG_WARNING, "Invalid 'activate_on' value %s for applicationmap item %s\n",
          args.activate_on, var->name);
       return -1;
    }
    ast_debug(1, "Allocating applicationmap item: dtmf = %s, app = %s, app_data = %s, moh_class = %s\n",
          args.dtmf, args.app, args.app_data, args.moh_class);
    item = applicationmap_item_alloc(var->name, args.app, args.app_data,
          args.moh_class, args.dtmf, activate_on_self);
    if (!item) {
       return -1;
    }
    if (!ao2_link(applicationmap, item)) {
       return -1;
    }
    return 0;
 }
applicationmap_item_alloc()
static struct ast_applicationmap_item* applicationmap_item_alloc (const char * name, const char * app, const char * app_data, const char * moh_class, const char * dtmf, unsigned int activate_on_self) static
Definition at line 1274 of file features_config.c.
References ast_applicationmap_item::activate_on_self, ao2_alloc, ast_applicationmap_item_destructor(), ast_copy_string(), ast_string_field_init, ast_string_field_set, ast_applicationmap_item::dtmf, item, and NULL.
Referenced by add_item(), and applicationmap_handler().
 {
    struct ast_applicationmap_item *item;
    item = ao2_alloc(sizeof(*item), ast_applicationmap_item_destructor);
    if (!item || ast_string_field_init(item, 64)) {
       return NULL;
    }
    ast_string_field_set(item, name, name);
    ast_string_field_set(item, app, app);
    ast_string_field_set(item, app_data, app_data);
    ast_string_field_set(item, moh_class, moh_class);
    ast_copy_string(item->dtmf, dtmf, sizeof(item->dtmf));
    item->activate_on_self = activate_on_self;
    return item;
 }
applicationmap_sort()
static int applicationmap_sort (const void * obj, const void * arg, int flags) static
Definition at line 416 of file features_config.c.
References ast_applicationmap_item::name, OBJ_KEY, OBJ_PARTIAL_KEY, and OBJ_POINTER.
Referenced by applicationmap_alloc().
 {
    const struct ast_applicationmap_item *item1 = obj;
    const struct ast_applicationmap_item *item2;
    const char *key2;
    switch(flags & (OBJ_POINTER | OBJ_KEY | OBJ_PARTIAL_KEY)) {
    case OBJ_KEY:
       key2 = arg;
       return strcasecmp(item1->name, key2);
    case OBJ_PARTIAL_KEY:
       key2 = arg;
       return strncasecmp(item1->name, key2, strlen(key2));
    default:
    case OBJ_POINTER:
       item2 = arg;
       return strcasecmp(item1->name, item2->name);
    }
 }
ast_applicationmap_item_destructor()
static void ast_applicationmap_item_destructor (void * obj) static
Definition at line 409 of file features_config.c.
References ast_string_field_free_memory, and item.
Referenced by applicationmap_item_alloc().
 {
    struct ast_applicationmap_item *item = obj;
    ast_string_field_free_memory(item);
 }
ast_get_builtin_feature()
int ast_get_builtin_feature (struct ast_channel * chan, const char * feature, char * buf, size_t len)
Get the DTMF code for a builtin feature.
Note
The channel should be locked before calling this function
If no channel is provided, then the global setting for the option is returned.
Parameters
chan The channel to get the option from
feature The short name of the feature (as it appears in features.conf)
[out] buf The buffer to write the DTMF value into
size The size of the buffer in bytes
Return values
0 Success
non-zero Unrecognized builtin feature name
Definition at line 1233 of file features_config.c.
References ao2_cleanup, ao2_global_obj_ref, featuremap_get(), get_feature_ds(), globals, NULL, and RAII_VAR.
Referenced by action_atxfer(), ast_get_feature(), attended_transfer_exec(), builtin_feature_get_exten(), detect_disconnect(), and internal_featuremap_read().
 {
    RAII_VAR(struct features_config *, cfg, NULL, ao2_cleanup);
    if (chan) {
       cfg = get_feature_ds(chan);
    } else {
       cfg = ao2_global_obj_ref(globals);
    }
    if (!cfg) {
       return -1;
    }
    return featuremap_get(cfg->featuremap, feature, buf, len);
 }
ast_get_chan_applicationmap()
struct ao2_container* ast_get_chan_applicationmap (struct ast_channel * chan)
Get the applicationmap for a given channel.
Note
The channel should be locked before calling this function.
This uses the value of the DYNAMIC_FEATURES channel variable to build a custom applicationmap for this channel. The returned container has applicationmap_items inside.
Parameters
chan The channel for which applicationmap is being retrieved.
Return values
NULL An error occurred or the channel has no dynamic features.
non-NULL A container of applicationmap_items pertaining to the channel.
Definition at line 1325 of file features_config.c.
References add_item(), ao2_callback, ao2_cleanup, ao2_container_count(), ao2_find, ao2_global_obj_ref, ao2_link, ao2_ref, applicationmap_alloc(), ast_assert, ast_channel_name(), ast_log, ast_strdupa, ast_strlen_zero, globals, item, LOG_WARNING, name, NULL, OBJ_KEY, pbx_builtin_getvar_helper(), RAII_VAR, S_OR, and strsep().
Referenced by ast_get_feature(), set_config_flags(), and setup_bridge_features_dynamic().
 {
    RAII_VAR(struct features_config *, cfg, ao2_global_obj_ref(globals), ao2_cleanup);
    struct ao2_container *applicationmap;
    char *group_names;
    char *name;
    if (!cfg) {
       return NULL;
    }
    if (!chan) {
       if (!cfg->applicationmap || ao2_container_count(cfg->applicationmap) == 0) {
          return NULL;
       }
       ao2_ref(cfg->applicationmap, +1);
       return cfg->applicationmap;
    }
    group_names = ast_strdupa(S_OR(pbx_builtin_getvar_helper(chan, "DYNAMIC_FEATURES"), ""));
    if (ast_strlen_zero(group_names)) {
       return NULL;
    }
    applicationmap = applicationmap_alloc(0);
    if (!applicationmap) {
       return NULL;
    }
    /* global config must be initialized */
    ast_assert(cfg->featuregroups != NULL);
    ast_assert(cfg->applicationmap != NULL);
    while ((name = strsep(&group_names, "#"))) {
       RAII_VAR(struct featuregroup *, group, ao2_find(cfg->featuregroups, name, OBJ_KEY), ao2_cleanup);
       if (!group) {
          RAII_VAR(struct ast_applicationmap_item *, item, ao2_find(cfg->applicationmap, name, OBJ_KEY), ao2_cleanup);
          if (item) {
             ao2_link(applicationmap, item);
          } else {
             ast_log(LOG_WARNING, "Unknown DYNAMIC_FEATURES item '%s' on channel %s.\n",
                name, ast_channel_name(chan));
          }
       } else {
          ao2_callback(group->items, 0, add_item, applicationmap);
       }
    }
    if (ao2_container_count(applicationmap) == 0) {
       ao2_cleanup(applicationmap);
       return NULL;
    }
    return applicationmap;
 }
ast_get_chan_featuremap_config()
struct ast_featuremap_config* ast_get_chan_featuremap_config (struct ast_channel * chan)
Get the featuremap configuration options for a channel.
Note
The channel should be locked before calling this function.
The returned value has its reference count incremented.
If no channel is provided, then the global featuremap configuration is returned.
Parameters
chan The channel to get configuration options for
Return values
NULL Failed to get configuration
non-NULL The pickup features configuration
Definition at line 1213 of file features_config.c.
References ao2_cleanup, ao2_global_obj_ref, ao2_ref, ast_assert, get_feature_ds(), globals, NULL, and RAII_VAR.
Referenced by testsuite_notify_feature_success().
 {
    RAII_VAR(struct features_config *, cfg, NULL, ao2_cleanup);
    if (chan) {
       cfg = get_feature_ds(chan);
    } else {
       cfg = ao2_global_obj_ref(globals);
    }
    if (!cfg) {
       return NULL;
    }
    ast_assert(cfg->featuremap != NULL);
    ao2_ref(cfg->featuremap, +1);
    return cfg->featuremap;
 }
ast_get_chan_features_atxferabort()
char* ast_get_chan_features_atxferabort (struct ast_channel * chan)
Get the transfer configuration option atxferabort.
Note
The channel should be locked before calling this function.
The returned value has to be freed.
If no channel is provided, then option is pulled from the global transfer configuration.
Parameters
chan The channel to get configuration options for
Return values
NULL Failed to get configuration
non-NULL The atxferabort
Definition at line 1178 of file features_config.c.
References ao2_ref, ast_get_chan_features_xfer_config(), ast_strdup, ast_features_xfer_config::atxferabort, and NULL.
Referenced by action_cancel_atxfer().
 {
    char *res;
    struct ast_features_xfer_config *cfg = ast_get_chan_features_xfer_config(chan);
    if (!cfg) {
       return NULL;
    }
    res = ast_strdup(cfg->atxferabort);
    ao2_ref(cfg, -1);
    return res;
 }
ast_get_chan_features_general_config()
struct ast_features_general_config* ast_get_chan_features_general_config (struct ast_channel * chan)
Get the general configuration options for a channel.
Note
The channel should be locked before calling this function.
The returned value has its reference count incremented.
If no channel is provided, then the global features configuration is returned.
Parameters
chan The channel to get configuration options for
Return values
NULL Failed to get configuration
non-NULL The general features configuration
Definition at line 1123 of file features_config.c.
References ao2_cleanup, ao2_global_obj_ref, ao2_ref, ast_assert, get_feature_ds(), globals, NULL, and RAII_VAR.
Referenced by bridge_channel_feature_digit_timeout(), feature_automixmonitor(), and feature_automonitor().
 {
    RAII_VAR(struct features_config *, cfg, NULL, ao2_cleanup);
    if (chan) {
       cfg = get_feature_ds(chan);
    } else {
       cfg = ao2_global_obj_ref(globals);
    }
    if (!cfg) {
       return NULL;
    }
    ast_assert(cfg->global && cfg->global->general);
    ao2_ref(cfg->global->general, +1);
    return cfg->global->general;
 }
ast_get_chan_features_pickup_config()
struct ast_features_pickup_config* ast_get_chan_features_pickup_config (struct ast_channel * chan)
Get the pickup configuration options for a channel.
Note
The channel should be locked before calling this function.
The returned value has its reference count incremented.
If no channel is provided, then the global pickup configuration is returned.
Parameters
chan The channel to get configuration options for
Return values
NULL Failed to get configuration
non-NULL The pickup features configuration
Definition at line 1193 of file features_config.c.
References ao2_cleanup, ao2_global_obj_ref, ao2_ref, ast_assert, get_feature_ds(), globals, NULL, and RAII_VAR.
Referenced by __analog_ss_thread(), analog_ss_thread(), ast_pickup_call(), call_pickup_incoming_request(), cb_events(), get_destination(), handle_call_outgoing(), handle_request_invite(), key_main_page(), and mgcp_ss().
 {
    RAII_VAR(struct features_config *, cfg, NULL, ao2_cleanup);
    if (chan) {
       cfg = get_feature_ds(chan);
    } else {
       cfg = ao2_global_obj_ref(globals);
    }
    if (!cfg) {
       return NULL;
    }
    ast_assert(cfg->global && cfg->global->pickup);
    ao2_ref(cfg->global->pickup, +1);
    return cfg->global->pickup;
 }
ast_get_chan_features_xfer_config()
struct ast_features_xfer_config* ast_get_chan_features_xfer_config (struct ast_channel * chan)
Get the transfer configuration options for a channel.
Note
The channel should be locked before calling this function.
The returned value has its reference count incremented.
If no channel is provided, then the global transfer configuration is returned.
Parameters
chan The channel to get configuration options for
Return values
NULL Failed to get configuration
non-NULL The transfer features configuration
Definition at line 1143 of file features_config.c.
References ao2_cleanup, ao2_global_obj_ref, ao2_ref, ast_assert, get_feature_ds(), globals, NULL, and RAII_VAR.
Referenced by action_bridge(), add_transferer_role(), ast_get_chan_features_atxferabort(), ast_get_chan_features_xferfailsound(), attended_transfer_properties_alloc(), bridge_exec(), grab_transfer(), and testsuite_notify_feature_success().
 {
    RAII_VAR(struct features_config *, cfg, NULL, ao2_cleanup);
    if (chan) {
       cfg = get_feature_ds(chan);
    } else {
       cfg = ao2_global_obj_ref(globals);
    }
    if (!cfg) {
       return NULL;
    }
    ast_assert(cfg->global && cfg->global->xfer);
    ao2_ref(cfg->global->xfer, +1);
    return cfg->global->xfer;
 }
ast_get_chan_features_xferfailsound()
char* ast_get_chan_features_xferfailsound (struct ast_channel * chan)
Get the transfer configuration option xferfailsound.
Note
The channel should be locked before calling this function.
The returned value has to be freed.
If no channel is provided, then option is pulled from the global transfer configuration.
Parameters
chan The channel to get configuration options for
Return values
NULL Failed to get configuration
non-NULL The xferfailsound
Definition at line 1163 of file features_config.c.
References ao2_ref, ast_get_chan_features_xfer_config(), ast_strdup, NULL, and ast_features_xfer_config::xferfailsound.
Referenced by play_failsound(), and stream_failsound().
 {
    char *res;
    struct ast_features_xfer_config *cfg = ast_get_chan_features_xfer_config(chan);
    if (!cfg) {
       return NULL;
    }
    res = ast_strdup(cfg->xferfailsound);
    ao2_ref(cfg, -1);
    return res;
 }
ast_get_feature()
int ast_get_feature (struct ast_channel * chan, const char * feature, char * buf, size_t len)
Get the DTMF code for a call feature.
Note
The channel should be locked before calling this function
If no channel is provided, then the global setting for the option is returned.
This function is like ast_get_builtin_feature except that it will also check the applicationmap in addition to the builtin features.
Parameters
chan The channel to get the option from
feature The short name of the feature
[out] buf The buffer to write the DTMF value into
size The size of the buffer in bytes
Return values
0 Success
non-zero Unrecognized feature name
Definition at line 1250 of file features_config.c.
References ao2_cleanup, ao2_find, ast_copy_string(), ast_get_builtin_feature(), ast_get_chan_applicationmap(), item, NULL, OBJ_KEY, and RAII_VAR.
Referenced by handle_incoming_request(), and handle_request_info().
 {
    RAII_VAR(struct ao2_container *, applicationmap, NULL, ao2_cleanup);
    RAII_VAR(struct ast_applicationmap_item *, item, NULL, ao2_cleanup);
    if (!ast_get_builtin_feature(chan, feature, buf, len)) {
       return 0;
    }
    /* Dang, must be in the application map */
    applicationmap = ast_get_chan_applicationmap(chan);
    if (!applicationmap) {
       return -1;
    }
    item = ao2_find(applicationmap, feature, OBJ_KEY);
    if (!item) {
       return -1;
    }
    ast_copy_string(buf, item->dtmf, len);
    return 0;
 }
check_featuregroup()
static int check_featuregroup (void * obj, void * arg, void * data, int flags) static
Definition at line 1567 of file features_config.c.
References ACO_FILES, ao2_callback_data, ast_log, check_featuregroup_item(), CMP_STOP, CONFIG_INFO_CORE(), features_config_alloc(), features_pre_apply_config(), globals, featuregroup::items, LOG_WARNING, and featuregroup::name.
Referenced by features_pre_apply_config().
 {
    struct featuregroup *group = obj;
    int *err = arg;
    ao2_callback_data(group->items, 0, check_featuregroup_item, arg, data);
    if (*err) {
       ast_log(LOG_WARNING, "Featuregroup %s refers to non-existent applicationmap item\n",
             group->name);
    }
    return *err ? CMP_STOP : 0;
 }
check_featuregroup_item()
static int check_featuregroup_item (void * obj, void * arg, void * data, int flags) static
Definition at line 1549 of file features_config.c.
References ao2_find, featuregroup_item::appmap_item, featuregroup_item::appmap_item_name, CMP_STOP, and OBJ_KEY.
Referenced by check_featuregroup().
 {
    struct ast_applicationmap_item *appmap_item;
    struct featuregroup_item *fg_item = obj;
    int *err = arg;
    struct ao2_container *applicationmap = data;
    appmap_item = ao2_find(applicationmap, fg_item->appmap_item_name, OBJ_KEY);
    if (!appmap_item) {
       *err = 1;
       return CMP_STOP;
    }
    fg_item->appmap_item = appmap_item;
    return 0;
 }
CONFIG_INFO_CORE()
CONFIG_INFO_CORE ("features" , cfg_info , globals , features_config_alloc , . files = ACO_FILES(&features_conf), . pre_apply_config = features_pre_apply_config)
Referenced by check_featuregroup().
feature_ds_destroy()
static void feature_ds_destroy (void * data) static
Definition at line 1046 of file features_config.c.
References ao2_cleanup.
 {
    struct features_config *cfg = data;
    ao2_cleanup(cfg);
 }
feature_ds_duplicate()
static void* feature_ds_duplicate (void * data) static
Definition at line 1052 of file features_config.c.
References features_config_dup().
 {
    struct features_config *old_cfg = data;
    return features_config_dup(old_cfg);
 }
feature_read()
static int feature_read (struct ast_channel * chan, const char * cmd, char * data, char * buf, size_t len) static
Definition at line 1702 of file features_config.c.
References ast_log, internal_feature_read(), and LOG_WARNING.
 {
    if (!chan) {
       ast_log(LOG_WARNING, "No channel was provided to %s function.\n", cmd);
       return -1;
    }
    return internal_feature_read(chan, cmd, data, buf, len);
 }
feature_write()
static int feature_write (struct ast_channel * chan, const char * cmd, char * data, const char * value) static
Definition at line 1713 of file features_config.c.
References ast_log, internal_feature_write(), and LOG_WARNING.
 {
    if (!chan) {
       ast_log(LOG_WARNING, "No channel was provided to %s function.\n", cmd);
       return -1;
    }
    return internal_feature_write(chan, cmd, data, value);
 }
featuregroup_alloc()
static void* featuregroup_alloc (const char * cat) static
Definition at line 542 of file features_config.c.
References ao2_alloc, AO2_ALLOC_OPT_LOCK_NOLOCK, ao2_cleanup, ao2_container_alloc_list, AO2_CONTAINER_ALLOC_OPT_DUPS_REPLACE, ast_strdup, featuregroup_destructor(), group_item_sort(), featuregroup::items, featuregroup::name, and NULL.
 {
    struct featuregroup *group;
    group = ao2_alloc(sizeof(*group), featuregroup_destructor);
    if (!group) {
       return NULL;
    }
    group->name = ast_strdup(cat);
    if (!group->name) {
       ao2_cleanup(group);
       return NULL;
    }
    group->items = ao2_container_alloc_list(AO2_ALLOC_OPT_LOCK_NOLOCK,
       AO2_CONTAINER_ALLOC_OPT_DUPS_REPLACE, group_item_sort, NULL);
    if (!group->items) {
       ao2_cleanup(group);
       return NULL;
    }
    return group;
 }
featuregroup_cmp()
static int featuregroup_cmp (void * obj, void * arg, int flags) static
Definition at line 508 of file features_config.c.
References CMP_MATCH, CMP_STOP, featuregroup::name, OBJ_KEY, OBJ_PARTIAL_KEY, and OBJ_POINTER.
Referenced by __features_config_alloc().
 {
    struct featuregroup *group1 = obj;
    struct featuregroup *group2;
    const char *key2;
    switch(flags & (OBJ_POINTER | OBJ_KEY | OBJ_PARTIAL_KEY)) {
    case OBJ_KEY:
       key2 = arg;
       return strcasecmp(group1->name, key2) ? 0 : CMP_MATCH;
    case OBJ_PARTIAL_KEY:
       key2 = arg;
       return strncasecmp(group1->name, key2, strlen(key2)) ? 0 : CMP_MATCH;
    case OBJ_POINTER:
       group2 = arg;
       return strcasecmp(group1->name, group2->name) ? 0 : CMP_MATCH;
    default:
       return CMP_STOP;
    }
 }
featuregroup_destructor()
static void featuregroup_destructor (void * obj) static
Definition at line 534 of file features_config.c.
References ao2_cleanup, ast_free, featuregroup::items, and featuregroup::name.
Referenced by featuregroup_alloc().
 {
    struct featuregroup *group = obj;
    ast_free((char *) group->name);
    ao2_cleanup(group->items);
 }
featuregroup_find()
static void* featuregroup_find (struct ao2_container * group_container, const char * category) static
Definition at line 529 of file features_config.c.
References ao2_find, and OBJ_KEY.
 {
    return ao2_find(group_container, category, OBJ_KEY);
 }
featuregroup_handler()
static int featuregroup_handler (const struct aco_option * opt, struct ast_variable * var, void * obj) static
Definition at line 1478 of file features_config.c.
References ao2_alloc, ao2_cleanup, ao2_link, ast_string_field_init, ast_string_field_set, featuregroup_item_destructor(), item, featuregroup::items, ast_variable::name, NULL, RAII_VAR, and ast_variable::value.
Referenced by load_config().
 {
    RAII_VAR(struct featuregroup_item *, item, NULL, ao2_cleanup);
    struct featuregroup *group = obj;
    item = ao2_alloc(sizeof(*item), featuregroup_item_destructor);
    if (!item || ast_string_field_init(item, 32)) {
       return -1;
    }
    ast_string_field_set(item, appmap_item_name, var->name);
    ast_string_field_set(item, dtmf_override, var->value);
    if (!ao2_link(group->items, item)) {
       return -1;
    }
    /* We wait to look up the application map item in the preapply callback */
    return 0;
 }
featuregroup_hash()
static int featuregroup_hash (const void * obj, int flags) static
Definition at line 489 of file features_config.c.
References ast_assert, ast_str_case_hash(), featuregroup::name, OBJ_KEY, OBJ_PARTIAL_KEY, and OBJ_POINTER.
Referenced by __features_config_alloc().
 {
    const struct featuregroup *group;
    const char *key;
    switch (flags & (OBJ_POINTER | OBJ_KEY | OBJ_PARTIAL_KEY)) {
    case OBJ_KEY:
       key = obj;
       return ast_str_case_hash(key);
    case OBJ_PARTIAL_KEY:
       ast_assert(0);
       return 0;
    case OBJ_POINTER:
    default:
       group = obj;
       return ast_str_case_hash(group->name);
    }
 }
featuregroup_item_destructor()
static void featuregroup_item_destructor (void * obj) static
Definition at line 450 of file features_config.c.
References ao2_cleanup, featuregroup_item::appmap_item, ast_string_field_free_memory, and item.
Referenced by featuregroup_handler().
 {
    struct featuregroup_item *item = obj;
    ast_string_field_free_memory(item);
    ao2_cleanup(item->appmap_item);
 }
featuremap_config_destructor()
static void featuremap_config_destructor (void * obj) static
Definition at line 647 of file features_config.c.
References ast_string_field_free_memory.
Referenced by __features_config_alloc().
 {
    struct ast_featuremap_config *cfg = obj;
    ast_string_field_free_memory(cfg);
 }
featuremap_copy()
static void featuremap_copy (struct ast_featuremap_config * dest, const struct ast_featuremap_config * src) static
Definition at line 808 of file features_config.c.
References ast_string_fields_copy.
Referenced by features_copy().
 {
    ast_string_fields_copy(dest, src);
 }
featuremap_get()
static int featuremap_get (struct ast_featuremap_config * featuremap, const char * field, char * buf, size_t len) static
Definition at line 1021 of file features_config.c.
References ast_copy_string(), ast_featuremap_config::atxfer, ast_featuremap_config::automixmon, ast_featuremap_config::automon, ast_featuremap_config::blindxfer, ast_featuremap_config::disconnect, and ast_featuremap_config::parkcall.
Referenced by ast_get_builtin_feature().
 {
    int res = 0;
    if (!strcasecmp(field, "blindxfer")) {
       ast_copy_string(buf, featuremap->blindxfer, len);
    } else if (!strcasecmp(field, "disconnect")) {
       ast_copy_string(buf, featuremap->disconnect, len);
    } else if (!strcasecmp(field, "automon")) {
       ast_copy_string(buf, featuremap->automon, len);
    } else if (!strcasecmp(field, "atxfer")) {
       ast_copy_string(buf, featuremap->atxfer, len);
    } else if (!strcasecmp(field, "automixmon")) {
       ast_copy_string(buf, featuremap->automixmon, len);
    } else if (!strcasecmp(field, "parkcall")) {
       ast_copy_string(buf, featuremap->parkcall, len);
    } else {
       /* Unrecognized option */
       res = -1;
    }
    return res;
 }
featuremap_handler()
static int featuremap_handler (const struct aco_option * opt, struct ast_variable * var, void * obj) static
Definition at line 1541 of file features_config.c.
References featuremap_set(), ast_variable::name, and ast_variable::value.
Referenced by load_config().
 {
    struct ast_featuremap_config *featuremap = obj;
    return featuremap_set(featuremap, var->name, var->value);
 }
featuremap_read()
static int featuremap_read (struct ast_channel * chan, const char * cmd, char * data, char * buf, size_t len) static
Definition at line 1724 of file features_config.c.
References ast_log, internal_featuremap_read(), and LOG_WARNING.
 {
    if (!chan) {
       ast_log(LOG_WARNING, "No channel was provided to %s function.\n", cmd);
       return -1;
    }
    return internal_featuremap_read(chan, cmd, data, buf, len);
 }
featuremap_set()
static int featuremap_set (struct ast_featuremap_config * featuremap, const char * name, const char * value) static
Definition at line 996 of file features_config.c.
References ast_string_field_set.
Referenced by featuremap_handler(), and internal_featuremap_write().
 {
    int res = 0;
    if (!strcasecmp(name, "blindxfer")) {
       ast_string_field_set(featuremap, blindxfer, value);
    } else if (!strcasecmp(name, "disconnect")) {
       ast_string_field_set(featuremap, disconnect, value);
    } else if (!strcasecmp(name, "automon")) {
       ast_string_field_set(featuremap, automon, value);
    } else if (!strcasecmp(name, "atxfer")) {
       ast_string_field_set(featuremap, atxfer, value);
    } else if (!strcasecmp(name, "automixmon")) {
       ast_string_field_set(featuremap, automixmon, value);
    } else if (!strcasecmp(name, "parkcall")) {
       ast_string_field_set(featuremap, parkcall, value);
    } else {
       /* Unrecognized option */
       res = -1;
    }
    return res;
 }
featuremap_write()
static int featuremap_write (struct ast_channel * chan, const char * cmd, char * data, const char * value) static
Definition at line 1735 of file features_config.c.
References ast_log, internal_featuremap_write(), and LOG_WARNING.
 {
    if (!chan) {
       ast_log(LOG_WARNING, "No channel was provided to %s function.\n", cmd);
       return -1;
    }
    return internal_featuremap_write(chan, cmd, data, value);
 }
features_config_alloc()
static void* features_config_alloc (void) static
Definition at line 774 of file features_config.c.
References __features_config_alloc().
Referenced by check_featuregroup(), and load_config().
 {
    return __features_config_alloc(1);
 }
features_config_destructor()
static void features_config_destructor (void * obj) static
Definition at line 636 of file features_config.c.
References ao2_cleanup, features_config::applicationmap, features_config::featuregroups, features_config::featuremap, features_config::global, and features_config::parkinglots.
Referenced by __features_config_alloc().
 {
    struct features_config *cfg = obj;
    ao2_cleanup(cfg->global);
    ao2_cleanup(cfg->featuremap);
    ao2_cleanup(cfg->parkinglots);
    ao2_cleanup(cfg->applicationmap);
    ao2_cleanup(cfg->featuregroups);
 }
features_config_dup()
static struct features_config* features_config_dup (const struct features_config * orig) static
Definition at line 824 of file features_config.c.
References __features_config_alloc(), features_copy(), and NULL.
Referenced by feature_ds_duplicate(), and get_feature_ds().
 {
    struct features_config *dup;
    dup = __features_config_alloc(0);
    if (!dup) {
       return NULL;
    }
    features_copy(dup, orig);
    return dup;
 }
features_copy()
static void features_copy (struct features_config * dest, const struct features_config * src) static
Definition at line 813 of file features_config.c.
References features_config::featuremap, featuremap_copy(), features_config::global, and global_copy().
Referenced by features_config_dup().
 {
    global_copy(dest->global, src->global);
    featuremap_copy(dest->featuremap, src->featuremap);
    /* applicationmap and featuregroups are purposely not copied. A channel's applicationmap
     * is produced on the fly when ast_get_chan_applicationmap() is called
     * NOTE: This does not apply to the global cfg->applicationmap and cfg->featuresgroups
     */
 }
features_pre_apply_config()
static int features_pre_apply_config (void) static
Definition at line 1589 of file features_config.c.
References aco_pending_config(), ao2_callback_data, features_config::applicationmap, ast_assert, check_featuregroup(), features_config::featuregroups, and NULL.
Referenced by check_featuregroup().
 {
    struct features_config *cfg = aco_pending_config(&cfg_info);
    int err = 0;
    /* Now that the entire config has been processed, we can check that the featuregroup
     * items refer to actual applicationmap items.
     */
    /* global config must be initialized */
    ast_assert(cfg->featuregroups != NULL);
    ast_assert(cfg->applicationmap != NULL);
    ao2_callback_data(cfg->featuregroups, 0, check_featuregroup, &err, cfg->applicationmap);
    return err;
 }
general_copy()
static void general_copy (struct ast_features_general_config * dest, const struct ast_features_general_config * src) static
Definition at line 779 of file features_config.c.
References ast_string_fields_copy, and ast_features_general_config::featuredigittimeout.
Referenced by global_copy().
 {
    ast_string_fields_copy(dest, src);
    dest->featuredigittimeout = src->featuredigittimeout;
 }
general_destructor()
static void general_destructor (void * obj) static
Definition at line 663 of file features_config.c.
References ast_string_field_free_memory.
Referenced by global_config_alloc().
 {
    struct ast_features_general_config *cfg = obj;
    ast_string_field_free_memory(cfg);
 }
general_get()
static int general_get (struct ast_features_general_config * general, const char * field, char * buf, size_t len) static
Definition at line 857 of file features_config.c.
References ast_copy_string(), ast_features_general_config::courtesytone, ast_features_general_config::featuredigittimeout, and ast_features_general_config::recordingfailsound.
Referenced by internal_feature_read().
 {
    int res = 0;
    if (!strcasecmp(field, "featuredigittimeout")) {
       snprintf(buf, len, "%u", general->featuredigittimeout);
    } else if (!strcasecmp(field, "courtesytone")) {
       ast_copy_string(buf, general->courtesytone, len);
    } else if (!strcasecmp(field, "recordingfailsound")) {
       ast_copy_string(buf, general->recordingfailsound, len);
    } else {
       /* Unrecognized option */
       res = -1;
    }
    return res;
 }
general_handler()
static int general_handler (const struct aco_option * opt, struct ast_variable * var, void * obj) static
Definition at line 1501 of file features_config.c.
References features_global_config::general, general_set(), global, ast_variable::name, and ast_variable::value.
Referenced by load_config().
 {
    struct features_global_config *global = obj;
    struct ast_features_general_config *general = global->general;
    return general_set(general, var->name, var->value);
 }
general_set()
static int general_set (struct ast_features_general_config * general, const char * name, const char * value) static
Definition at line 838 of file features_config.c.
References ast_parse_arg(), ast_string_field_set, ast_features_general_config::featuredigittimeout, and PARSE_INT32.
Referenced by general_handler(), and internal_feature_write().
 {
    int res = 0;
    if (!strcasecmp(name, "featuredigittimeout")) {
       res = ast_parse_arg(value, PARSE_INT32, &general->featuredigittimeout);
    } else if (!strcasecmp(name, "courtesytone")) {
       ast_string_field_set(general, courtesytone, value);
    } else if (!strcasecmp(name, "recordingfailsound")) {
       ast_string_field_set(general, recordingfailsound, value);
    } else {
       /* Unrecognized option */
       res = -1;
    }
    return res;
 }
get_feature_chan_ds()
static struct ast_datastore* get_feature_chan_ds (struct ast_channel * chan) static
Definition at line 1109 of file features_config.c.
References ao2_cleanup, ast_channel_datastore_find(), get_feature_ds(), and NULL.
Referenced by internal_feature_read(), and internal_feature_write().
 {
    struct ast_datastore *ds;
    if (!(ds = ast_channel_datastore_find(chan, &feature_ds_info, NULL))) {
       /* Hasn't been created yet.  Trigger creation. */
       ao2_cleanup(get_feature_ds(chan));
       ds = ast_channel_datastore_find(chan, &feature_ds_info, NULL);
    }
    return ds;
 }
get_feature_ds()
static struct features_config* get_feature_ds (struct ast_channel * chan) static
Definition at line 1073 of file features_config.c.
References ao2_cleanup, ao2_global_obj_ref, ao2_ref, ast_channel_datastore_add(), ast_channel_datastore_find(), ast_datastore_alloc, ast_datastore::data, features_config_dup(), globals, NULL, and RAII_VAR.
Referenced by ast_get_builtin_feature(), ast_get_chan_featuremap_config(), ast_get_chan_features_general_config(), ast_get_chan_features_pickup_config(), ast_get_chan_features_xfer_config(), get_feature_chan_ds(), internal_feature_read(), internal_feature_write(), and internal_featuremap_write().
 {
    RAII_VAR(struct features_config *, orig, NULL, ao2_cleanup);
    struct features_config *cfg;
    struct ast_datastore *ds;
    if ((ds = ast_channel_datastore_find(chan, &feature_ds_info, NULL))) {
       cfg = ds->data;
       ao2_ref(cfg, +1);
       return cfg;
    }
    orig = ao2_global_obj_ref(globals);
    if (!orig) {
       return NULL;
    }
    cfg = features_config_dup(orig);
    if (!cfg) {
       return NULL;
    }
    if (!(ds = ast_datastore_alloc(&feature_ds_info, NULL))) {
       ao2_cleanup(cfg);
       return NULL;
    }
    /* Give the datastore a reference to the config */
    ao2_ref(cfg, +1);
    ds->data = cfg;
    ast_channel_datastore_add(chan, ds);
    return cfg;
 }
global_config_alloc()
static struct features_global_config* global_config_alloc (void) static
Definition at line 684 of file features_config.c.
References ao2_alloc, ao2_cleanup, ao2_ref, ast_string_field_init, general_destructor(), global_config_destructor(), NULL, pickup_destructor(), RAII_VAR, and xfer_destructor().
Referenced by __features_config_alloc().
 {
    RAII_VAR(struct features_global_config *, cfg, NULL, ao2_cleanup);
    cfg = ao2_alloc(sizeof(*cfg), global_config_destructor);
    if (!cfg) {
       return NULL;
    }
    cfg->general = ao2_alloc(sizeof(*cfg->general), general_destructor);
    if (!cfg->general || ast_string_field_init(cfg->general, 32)) {
       return NULL;
    }
    cfg->xfer = ao2_alloc(sizeof(*cfg->xfer), xfer_destructor);
    if (!cfg->xfer || ast_string_field_init(cfg->xfer, 32)) {
       return NULL;
    }
    cfg->pickup = ao2_alloc(sizeof(*cfg->pickup), pickup_destructor);
    if (!cfg->pickup || ast_string_field_init(cfg->pickup, 32)) {
       return NULL;
    }
    ao2_ref(cfg, +1);
    return cfg;
 }
global_config_destructor()
static void global_config_destructor (void * obj) static
Definition at line 654 of file features_config.c.
References ao2_cleanup, features_global_config::general, features_global_config::pickup, and features_global_config::xfer.
Referenced by global_config_alloc().
 {
    struct features_global_config *cfg = obj;
    ao2_cleanup(cfg->general);
    ao2_cleanup(cfg->xfer);
    ao2_cleanup(cfg->pickup);
 }
global_copy()
static void global_copy (struct features_global_config * dest, const struct features_global_config * src) static
Definition at line 801 of file features_config.c.
References features_global_config::general, general_copy(), features_global_config::pickup, pickup_copy(), features_global_config::xfer, and xfer_copy().
Referenced by features_copy().
 {
    general_copy(dest->general, src->general);
    xfer_copy(dest->xfer, src->xfer);
    pickup_copy(dest->pickup, src->pickup);
 }
group_item_sort()
static int group_item_sort (const void * obj, const void * arg, int flags) static
Definition at line 458 of file features_config.c.
References featuregroup_item::appmap_item_name, CMP_STOP, OBJ_KEY, OBJ_PARTIAL_KEY, and OBJ_POINTER.
Referenced by featuregroup_alloc().
 {
    const struct featuregroup_item *item1 = obj;
    const struct featuregroup_item *item2;
    const char *key2;
    switch(flags & (OBJ_POINTER | OBJ_KEY | OBJ_PARTIAL_KEY)) {
    case OBJ_KEY:
       key2 = arg;
       return strcasecmp(item1->appmap_item_name, key2);
    case OBJ_PARTIAL_KEY:
       key2 = arg;
       return strncasecmp(item1->appmap_item_name, key2, strlen(key2));
    case OBJ_POINTER:
       item2 = arg;
       return strcasecmp(item1->appmap_item_name, item2->appmap_item_name);
    default:
       return CMP_STOP;
    }
 }
handle_feature_show()
static char* handle_feature_show (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) static
CLI command to list configured features.
Parameters
e
cmd
a
Return values
CLI_SUCCESS on success.
NULL when tab completion is used.
Definition at line 1923 of file features_config.c.
References ao2_callback, ao2_cleanup, ao2_container_count(), ao2_global_obj_ref, ast_cli(), CLI_GENERATE, CLI_INIT, CLI_SUCCESS, ast_cli_entry::command, DEFAULT_FEATUREMAP_ATXFER, DEFAULT_FEATUREMAP_AUTOMIXMON, DEFAULT_FEATUREMAP_AUTOMON, DEFAULT_FEATUREMAP_BLINDXFER, DEFAULT_FEATUREMAP_DISCONNECT, DEFAULT_FEATUREMAP_PARKCALL, DEFAULT_PICKUPEXTEN, ast_cli_args::fd, globals, HFS_FORMAT, NULL, print_applicationmap(), print_featuregroups(), RAII_VAR, and ast_cli_entry::usage.
 {
    RAII_VAR(struct features_config *, cfg, NULL, ao2_cleanup);
    switch (cmd) {
    case CLI_INIT:
       e->command = "features show";
       e->usage =
          "Usage: features show\n"
          "       Lists configured features\n";
       return NULL;
    case CLI_GENERATE:
       return NULL;
    }
    cfg = ao2_global_obj_ref(globals);
    ast_cli(a->fd, HFS_FORMAT, "Builtin Feature", "Default", "Current");
    ast_cli(a->fd, HFS_FORMAT, "---------------", "-------", "-------");
    ast_cli(a->fd, HFS_FORMAT, "Pickup", DEFAULT_PICKUPEXTEN, cfg->global->pickup->pickupexten);
    ast_cli(a->fd, HFS_FORMAT, "Blind Transfer", DEFAULT_FEATUREMAP_BLINDXFER, cfg->featuremap->blindxfer);
    ast_cli(a->fd, HFS_FORMAT, "Attended Transfer", DEFAULT_FEATUREMAP_ATXFER, cfg->featuremap->atxfer);
    ast_cli(a->fd, HFS_FORMAT, "One Touch Monitor", DEFAULT_FEATUREMAP_AUTOMON, cfg->featuremap->automon);
    ast_cli(a->fd, HFS_FORMAT, "Disconnect Call", DEFAULT_FEATUREMAP_DISCONNECT, cfg->featuremap->disconnect);
    ast_cli(a->fd, HFS_FORMAT, "Park Call", DEFAULT_FEATUREMAP_PARKCALL, cfg->featuremap->parkcall);
    ast_cli(a->fd, HFS_FORMAT, "One Touch MixMonitor", DEFAULT_FEATUREMAP_AUTOMIXMON, cfg->featuremap->automixmon);
    ast_cli(a->fd, "\n");
    ast_cli(a->fd, HFS_FORMAT, "Dynamic Feature", "Default", "Current");
    ast_cli(a->fd, HFS_FORMAT, "---------------", "-------", "-------");
    if (!cfg->applicationmap || ao2_container_count(cfg->applicationmap) == 0) {
       ast_cli(a->fd, "(none)\n");
    } else {
       ao2_callback(cfg->applicationmap, 0, print_applicationmap, a);
    }
    ast_cli(a->fd, "\nFeature Groups:\n");
    ast_cli(a->fd, "---------------\n");
    if (!cfg->featuregroups || ao2_container_count(cfg->featuregroups) == 0) {
       ast_cli(a->fd, "(none)\n");
    } else {
       ao2_callback(cfg->featuregroups, 0, print_featuregroups, a);
    }
    return CLI_SUCCESS;
 }
internal_feature_read()
static int internal_feature_read (struct ast_channel * chan, const char * cmd, char * data, char * buf, size_t len) static
Definition at line 1606 of file features_config.c.
References ao2_cleanup, ast_log, general_get(), get_feature_chan_ds(), get_feature_ds(), ast_datastore::inheritance, lock, LOG_WARNING, NULL, pickup_get(), RAII_VAR, SCOPED_CHANNELLOCK, and xfer_get().
Referenced by feature_read().
 {
    int res;
    RAII_VAR(struct features_config *, cfg, NULL, ao2_cleanup);
    SCOPED_CHANNELLOCK(lock, chan);
    if (!strcasecmp(data, "inherit")) {
       struct ast_datastore *ds = get_feature_chan_ds(chan);
       unsigned int inherit = ds ? ds->inheritance : 0;
       snprintf(buf, len, "%s", inherit ? "yes" : "no");
       return 0;
    }
    cfg = get_feature_ds(chan);
    if (!cfg) {
       return -1;
    }
    res = general_get(cfg->global->general, data, buf, len) &&
       xfer_get(cfg->global->xfer, data, buf, len) &&
       pickup_get(cfg->global->pickup, data, buf, len);
    if (res) {
       ast_log(LOG_WARNING, "Invalid argument '%s' to FEATURE()\n", data);
    }
    return res;
 }
internal_feature_write()
static int internal_feature_write (struct ast_channel * chan, const char * cmd, char * data, const char * value) static
Definition at line 1637 of file features_config.c.
References ao2_cleanup, ast_log, ast_true(), DATASTORE_INHERIT_FOREVER, general_set(), get_feature_chan_ds(), get_feature_ds(), ast_datastore::inheritance, lock, LOG_WARNING, NULL, pickup_set(), RAII_VAR, SCOPED_CHANNELLOCK, and xfer_set().
Referenced by feature_write().
 {
    int res;
    RAII_VAR(struct features_config *, cfg, NULL, ao2_cleanup);
    SCOPED_CHANNELLOCK(lock, chan);
    if (!strcasecmp(data, "inherit")) {
       struct ast_datastore *ds = get_feature_chan_ds(chan);
       if (ds) {
          ds->inheritance = ast_true(value) ? DATASTORE_INHERIT_FOREVER : 0;
       }
       return 0;
    }
    if (!(cfg = get_feature_ds(chan))) {
       return -1;
    }
    res = general_set(cfg->global->general, data, value) &&
       xfer_set(cfg->global->xfer, data, value) &&
       pickup_set(cfg->global->pickup, data, value);
    if (res) {
       ast_log(LOG_WARNING, "Invalid argument '%s' to FEATURE()\n", data);
    }
    return res;
 }
internal_featuremap_read()
static int internal_featuremap_read (struct ast_channel * chan, const char * cmd, char * data, char * buf, size_t len) static
Definition at line 1667 of file features_config.c.
References ast_get_builtin_feature(), ast_log, lock, LOG_WARNING, and SCOPED_CHANNELLOCK.
Referenced by featuremap_read().
 {
    int res;
    SCOPED_CHANNELLOCK(lock, chan);
    res = ast_get_builtin_feature(chan, data, buf, len);
    if (res) {
       ast_log(LOG_WARNING, "Invalid argument '%s' to FEATUREMAP()\n", data);
    }
    return res;
 }
internal_featuremap_write()
static int internal_featuremap_write (struct ast_channel * chan, const char * cmd, char * data, const char * value) static
Definition at line 1682 of file features_config.c.
References ao2_cleanup, ast_log, featuremap_set(), get_feature_ds(), lock, LOG_WARNING, NULL, RAII_VAR, and SCOPED_CHANNELLOCK.
Referenced by featuremap_write().
 {
    int res;
    RAII_VAR(struct features_config *, cfg, NULL, ao2_cleanup);
    SCOPED_CHANNELLOCK(lock, chan);
    if (!(cfg = get_feature_ds(chan))) {
       return -1;
    }
    res = featuremap_set(cfg->featuremap, data, value);
    if (res) {
       ast_log(LOG_WARNING, "Invalid argument '%s' to FEATUREMAP()\n", data);
       return -1;
    }
    return 0;
 }
load_config()
static int load_config (void) static
Definition at line 1758 of file features_config.c.
References __stringify, ACO_EXACT, aco_info_init(), aco_option_register_custom, aco_option_register_custom_nodoc, ACO_PREFIX, aco_process_config(), ACO_PROCESS_ERROR, aco_set_defaults(), ao2_cleanup, ao2_global_obj_replace_unref, applicationmap_handler(), ast_log, DEFAULT_ATXFER_ABORT, DEFAULT_ATXFER_CALLBACK_RETRIES, DEFAULT_ATXFER_COMPLETE, DEFAULT_ATXFER_DROP_CALL, DEFAULT_ATXFER_LOOP_DELAY, DEFAULT_ATXFER_SWAP, DEFAULT_ATXFER_THREEWAY, DEFAULT_COURTESY_TONE, DEFAULT_FEATURE_DIGIT_TIMEOUT, DEFAULT_FEATUREMAP_ATXFER, DEFAULT_FEATUREMAP_AUTOMIXMON, DEFAULT_FEATUREMAP_AUTOMON, DEFAULT_FEATUREMAP_BLINDXFER, DEFAULT_FEATUREMAP_DISCONNECT, DEFAULT_FEATUREMAP_PARKCALL, DEFAULT_NOANSWER_TIMEOUT_ATTENDED_TRANSFER, DEFAULT_PICKUPEXTEN, DEFAULT_PICKUPFAILSOUND, DEFAULT_PICKUPSOUND, DEFAULT_RECORDING_FAIL_SOUND, DEFAULT_TRANSFER_DIAL_ATTEMPTS, DEFAULT_TRANSFER_DIGIT_TIMEOUT, DEFAULT_TRANSFER_INVALID_SOUND, DEFAULT_TRANSFER_RETRY_SOUND, DEFAULT_XFERFAILSOUND, DEFAULT_XFERSOUND, featuregroup_handler(), featuremap_handler(), features_config_alloc(), general_handler(), globals, LOG_ERROR, LOG_NOTICE, pickup_handler(), RAII_VAR, unsupported_handler(), and xfer_handler().
Referenced by load_features_config().
 {
    if (aco_info_init(&cfg_info)) {
       ast_log(LOG_ERROR, "Unable to initialize configuration info for features\n");
       return -1;
    }
    aco_option_register_custom(&cfg_info, "featuredigittimeout", ACO_EXACT, global_options,
          __stringify(DEFAULT_FEATURE_DIGIT_TIMEOUT), general_handler, 0);
    aco_option_register_custom(&cfg_info, "recordingfailsound", ACO_EXACT, global_options,
          DEFAULT_RECORDING_FAIL_SOUND, general_handler, 0);
    aco_option_register_custom(&cfg_info, "courtesytone", ACO_EXACT, global_options,
          DEFAULT_COURTESY_TONE, general_handler, 0);
    aco_option_register_custom(&cfg_info, "transferdigittimeout", ACO_EXACT, global_options,
          __stringify(DEFAULT_TRANSFER_DIGIT_TIMEOUT), xfer_handler, 0)
    aco_option_register_custom(&cfg_info, "atxfernoanswertimeout", ACO_EXACT, global_options,
          __stringify(DEFAULT_NOANSWER_TIMEOUT_ATTENDED_TRANSFER), xfer_handler, 0);
    aco_option_register_custom(&cfg_info, "atxferdropcall", ACO_EXACT, global_options,
          __stringify(DEFAULT_ATXFER_DROP_CALL), xfer_handler, 0);
    aco_option_register_custom(&cfg_info, "atxferloopdelay", ACO_EXACT, global_options,
          __stringify(DEFAULT_ATXFER_LOOP_DELAY), xfer_handler, 0);
    aco_option_register_custom(&cfg_info, "atxfercallbackretries", ACO_EXACT, global_options,
          __stringify(DEFAULT_ATXFER_CALLBACK_RETRIES), xfer_handler, 0);
    aco_option_register_custom(&cfg_info, "xfersound", ACO_EXACT, global_options,
          DEFAULT_XFERSOUND, xfer_handler, 0);
    aco_option_register_custom(&cfg_info, "xferfailsound", ACO_EXACT, global_options,
          DEFAULT_XFERFAILSOUND, xfer_handler, 0);
    aco_option_register_custom(&cfg_info, "atxferabort", ACO_EXACT, global_options,
          DEFAULT_ATXFER_ABORT, xfer_handler, 0);
    aco_option_register_custom(&cfg_info, "atxfercomplete", ACO_EXACT, global_options,
          DEFAULT_ATXFER_COMPLETE, xfer_handler, 0);
    aco_option_register_custom(&cfg_info, "atxferthreeway", ACO_EXACT, global_options,
          DEFAULT_ATXFER_THREEWAY, xfer_handler, 0);
    aco_option_register_custom(&cfg_info, "atxferswap", ACO_EXACT, global_options,
          DEFAULT_ATXFER_SWAP, xfer_handler, 0);
    aco_option_register_custom(&cfg_info, "transferdialattempts", ACO_EXACT, global_options,
          __stringify(DEFAULT_TRANSFER_DIAL_ATTEMPTS), xfer_handler, 0);
    aco_option_register_custom(&cfg_info, "transferretrysound", ACO_EXACT, global_options,
          DEFAULT_TRANSFER_RETRY_SOUND, xfer_handler, 0);
    aco_option_register_custom(&cfg_info, "transferinvalidsound", ACO_EXACT, global_options,
          DEFAULT_TRANSFER_INVALID_SOUND, xfer_handler, 0);
    aco_option_register_custom(&cfg_info, "pickupexten", ACO_EXACT, global_options,
          DEFAULT_PICKUPEXTEN, pickup_handler, 0);
    aco_option_register_custom(&cfg_info, "pickupsound", ACO_EXACT, global_options,
          DEFAULT_PICKUPSOUND, pickup_handler, 0);
    aco_option_register_custom(&cfg_info, "pickupfailsound", ACO_EXACT, global_options,
          DEFAULT_PICKUPFAILSOUND, pickup_handler, 0);
    aco_option_register_custom_nodoc(&cfg_info, "context", ACO_EXACT, global_options,
          "", unsupported_handler, 0);
    aco_option_register_custom_nodoc(&cfg_info, "parkext", ACO_EXACT, global_options,
          "", unsupported_handler, 0);
    aco_option_register_custom_nodoc(&cfg_info, "parkext_exclusive", ACO_EXACT, global_options,
          "", unsupported_handler, 0);
    aco_option_register_custom_nodoc(&cfg_info, "parkinghints", ACO_EXACT, global_options,
          "", unsupported_handler, 0);
    aco_option_register_custom_nodoc(&cfg_info, "parkedmusicclass", ACO_EXACT, global_options,
          "", unsupported_handler, 0);
    aco_option_register_custom_nodoc(&cfg_info, "parkingtime", ACO_EXACT, global_options,
          "", unsupported_handler, 0);
    aco_option_register_custom_nodoc(&cfg_info, "parkpos", ACO_EXACT, global_options,
          "", unsupported_handler, 0);
    aco_option_register_custom_nodoc(&cfg_info, "findslot", ACO_EXACT, global_options,
          "", unsupported_handler, 0);
    aco_option_register_custom_nodoc(&cfg_info, "parkedcalltransfers", ACO_EXACT, global_options,
          "", unsupported_handler, 0);
    aco_option_register_custom_nodoc(&cfg_info, "parkedcallreparking", ACO_EXACT, global_options,
          "", unsupported_handler, 0);
    aco_option_register_custom_nodoc(&cfg_info, "parkedcallhangup", ACO_EXACT, global_options,
          "", unsupported_handler, 0);
    aco_option_register_custom_nodoc(&cfg_info, "parkedcallrecording", ACO_EXACT, global_options,
          "", unsupported_handler, 0);
    aco_option_register_custom_nodoc(&cfg_info, "comebackcontext", ACO_EXACT, global_options,
          "", unsupported_handler, 0);
    aco_option_register_custom_nodoc(&cfg_info, "comebacktoorigin", ACO_EXACT, global_options,
          "", unsupported_handler, 0);
    aco_option_register_custom_nodoc(&cfg_info, "comebackdialtime", ACO_EXACT, global_options,
          "", unsupported_handler, 0);
    aco_option_register_custom_nodoc(&cfg_info, "parkeddynamic", ACO_EXACT, global_options,
          "", unsupported_handler, 0);
    aco_option_register_custom_nodoc(&cfg_info, "adsipark", ACO_EXACT, global_options,
          "", unsupported_handler, 0);
    aco_option_register_custom(&cfg_info, "blindxfer", ACO_EXACT, featuremap_options,
          DEFAULT_FEATUREMAP_BLINDXFER, featuremap_handler, 0);
    aco_option_register_custom(&cfg_info, "disconnect", ACO_EXACT, featuremap_options,
          DEFAULT_FEATUREMAP_DISCONNECT, featuremap_handler, 0);
    aco_option_register_custom(&cfg_info, "automon", ACO_EXACT, featuremap_options,
          DEFAULT_FEATUREMAP_AUTOMON, featuremap_handler, 0);
    aco_option_register_custom(&cfg_info, "atxfer", ACO_EXACT, featuremap_options,
          DEFAULT_FEATUREMAP_ATXFER, featuremap_handler, 0);
    aco_option_register_custom(&cfg_info, "parkcall", ACO_EXACT, featuremap_options,
          DEFAULT_FEATUREMAP_PARKCALL, featuremap_handler, 0);
    aco_option_register_custom(&cfg_info, "automixmon", ACO_EXACT, featuremap_options,
          DEFAULT_FEATUREMAP_AUTOMIXMON, featuremap_handler, 0);
    aco_option_register_custom(&cfg_info, "", ACO_PREFIX, applicationmap_options,
          "", applicationmap_handler, 0);
    aco_option_register_custom(&cfg_info, "", ACO_PREFIX, featuregroup_options,
          "", featuregroup_handler, 0);
    aco_option_register_custom_nodoc(&cfg_info, "", ACO_PREFIX, parkinglot_options,
          "", unsupported_handler, 0);
    if (aco_process_config(&cfg_info, 0) == ACO_PROCESS_ERROR) {
       RAII_VAR(struct features_config *, features_cfg, features_config_alloc(), ao2_cleanup);
       if (aco_set_defaults(&global_option, "general", features_cfg->global) ||
          aco_set_defaults(&featuremap_option, "featuremap", features_cfg->featuremap)) {
          ast_log(LOG_ERROR, "Failed to load features.conf and failed to initialize defaults.\n");
          return -1;
       }
       ast_log(LOG_NOTICE, "Could not load features config; using defaults\n");
       ao2_global_obj_replace_unref(globals, features_cfg);
    }
    return 0;
 }
load_features_config()
int load_features_config (void)
Definition at line 1996 of file features_config.c.
References __ast_custom_function_register(), ARRAY_LEN, ast_cli_register_multiple, load_config(), and NULL.
Referenced by load_module().
 {
    int res;
    res = load_config();
    res |= __ast_custom_function_register(&feature_function, NULL);
    res |= __ast_custom_function_register(&featuremap_function, NULL);
    res |= ast_cli_register_multiple(cli_features_config, ARRAY_LEN(cli_features_config));
    return res;
 }
pickup_copy()
static void pickup_copy (struct ast_features_pickup_config * dest, const struct ast_features_pickup_config * src) static
Definition at line 796 of file features_config.c.
References ast_string_fields_copy.
Referenced by global_copy().
 {
    ast_string_fields_copy(dest, src);
 }
pickup_destructor()
static void pickup_destructor (void * obj) static
Definition at line 677 of file features_config.c.
References ast_string_field_free_memory.
Referenced by global_config_alloc().
 {
    struct ast_features_pickup_config *cfg = obj;
    ast_string_field_free_memory(cfg);
 }
pickup_get()
static int pickup_get (struct ast_features_pickup_config * pickup, const char * field, char * buf, size_t len) static
Definition at line 977 of file features_config.c.
References ast_copy_string(), ast_features_pickup_config::pickupexten, ast_features_pickup_config::pickupfailsound, and ast_features_pickup_config::pickupsound.
Referenced by internal_feature_read().
 {
    int res = 0;
    if (!strcasecmp(field, "pickupsound")) {
       ast_copy_string(buf, pickup->pickupsound, len);
    } else if (!strcasecmp(field, "pickupfailsound")) {
       ast_copy_string(buf, pickup->pickupfailsound, len);
    } else if (!strcasecmp(field, "pickupexten")) {
       ast_copy_string(buf, pickup->pickupexten, len);
    } else {
       /* Unrecognized option */
       res = -1;
    }
    return res;
 }
pickup_handler()
static int pickup_handler (const struct aco_option * opt, struct ast_variable * var, void * obj) static
Definition at line 1519 of file features_config.c.
References global, ast_variable::name, features_global_config::pickup, pickup_set(), and ast_variable::value.
Referenced by load_config().
 {
    struct features_global_config *global = obj;
    struct ast_features_pickup_config *pickup = global->pickup;
    return pickup_set(pickup, var->name, var->value);
 }
pickup_set()
static int pickup_set (struct ast_features_pickup_config * pickup, const char * name, const char * value) static
Definition at line 958 of file features_config.c.
References ast_string_field_set.
Referenced by internal_feature_write(), and pickup_handler().
 {
    int res = 0;
    if (!strcasecmp(name, "pickupsound")) {
       ast_string_field_set(pickup, pickupsound, value);
    } else if (!strcasecmp(name, "pickupfailsound")) {
       ast_string_field_set(pickup, pickupfailsound, value);
    } else if (!strcasecmp(name, "pickupexten")) {
       ast_string_field_set(pickup, pickupexten, value);
    } else {
       /* Unrecognized option */
       res = -1;
    }
    return res;
 }
print_applicationmap()
static int print_applicationmap (void * obj, void * arg, int flags) static
Definition at line 1905 of file features_config.c.
References a, ast_cli(), ast_applicationmap_item::dtmf, ast_cli_args::fd, HFS_FORMAT, item, and ast_applicationmap_item::name.
Referenced by handle_feature_show().
 {
    struct ast_applicationmap_item *item = obj;
    struct ast_cli_args *a = arg;
    ast_cli(a->fd, HFS_FORMAT, item->name, "no def", item->dtmf);
    return 0;
 }
print_featuregroup()
static int print_featuregroup (void * obj, void * arg, int flags) static
Definition at line 1881 of file features_config.c.
References a, featuregroup_item::appmap_item, featuregroup_item::appmap_item_name, ast_cli(), ast_applicationmap_item::dtmf, featuregroup_item::dtmf_override, ast_cli_args::fd, item, and S_OR.
Referenced by print_featuregroups().
 {
    struct featuregroup_item *item = obj;
    struct ast_cli_args *a = arg;
    ast_cli(a->fd, "===> --> %s (%s)\n", item->appmap_item_name,
          S_OR(item->dtmf_override, item->appmap_item->dtmf));
    return 0;
 }
print_featuregroups()
static int print_featuregroups (void * obj, void * arg, int flags) static
Definition at line 1892 of file features_config.c.
References a, ao2_callback, ast_cli(), ast_cli_args::fd, featuregroup::items, featuregroup::name, and print_featuregroup().
Referenced by handle_feature_show().
 {
    struct featuregroup *group = obj;
    struct ast_cli_args *a = arg;
    ast_cli(a->fd, "===> Group: %s\n", group->name);
    ao2_callback(group->items, 0, print_featuregroup, a);
    return 0;
 }
reload_features_config()
int reload_features_config (void)
Definition at line 1985 of file features_config.c.
References aco_process_config(), ACO_PROCESS_ERROR, and parking_warning.
Referenced by load_module().
 {
    /* Rearm the parking config options have moved warning. */
    parking_warning = 0;
    if (aco_process_config(&cfg_info, 1) == ACO_PROCESS_ERROR) {
       return -1;
    }
    return 0;
 }
unload_features_config()
void unload_features_config (void)
Definition at line 1976 of file features_config.c.
References aco_info_destroy(), ao2_global_obj_release, ARRAY_LEN, ast_cli_unregister_multiple(), ast_custom_function_unregister(), and globals.
Referenced by unload_module().
 {
    ast_custom_function_unregister(&featuremap_function);
    ast_custom_function_unregister(&feature_function);
    ast_cli_unregister_multiple(cli_features_config, ARRAY_LEN(cli_features_config));
    aco_info_destroy(&cfg_info);
    ao2_global_obj_release(globals);
 }
unsupported_handler()
static int unsupported_handler (const struct aco_option * opt, struct ast_variable * var, void * obj) static
Definition at line 1529 of file features_config.c.
References ast_log, LOG_WARNING, ast_variable::name, and parking_warning.
Referenced by load_config().
 {
    if (!parking_warning) {
       ast_log(LOG_WARNING, "Parkinglots are no longer configurable in features.conf; "
          "parking is now handled by res_parking.conf\n");
       parking_warning = 1;
    }
    ast_log(LOG_WARNING, "The option '%s' is no longer configurable in features.conf.\n", var->name);
    return 0;
 }
xfer_copy()
static void xfer_copy (struct ast_features_xfer_config * dest, const struct ast_features_xfer_config * src) static
Definition at line 785 of file features_config.c.
References ast_string_fields_copy, ast_features_xfer_config::atxfercallbackretries, ast_features_xfer_config::atxferdropcall, ast_features_xfer_config::atxferloopdelay, ast_features_xfer_config::atxfernoanswertimeout, ast_features_xfer_config::transferdialattempts, and ast_features_xfer_config::transferdigittimeout.
Referenced by global_copy().
 {
    ast_string_fields_copy(dest, src);
    dest->transferdigittimeout = src->transferdigittimeout;
    dest->atxfernoanswertimeout = src->atxfernoanswertimeout;
    dest->atxferloopdelay = src->atxferloopdelay;
    dest->atxfercallbackretries = src->atxfercallbackretries;
    dest->atxferdropcall = src->atxferdropcall;
    dest->transferdialattempts = src->transferdialattempts;
 }
xfer_destructor()
static void xfer_destructor (void * obj) static
Definition at line 670 of file features_config.c.
References ast_string_field_free_memory.
Referenced by global_config_alloc().
 {
    struct ast_features_xfer_config *cfg = obj;
    ast_string_field_free_memory(cfg);
 }
xfer_get()
static int xfer_get (struct ast_features_xfer_config * xfer, const char * field, char * buf, size_t len) static
Definition at line 917 of file features_config.c.
References ast_copy_string(), ast_features_xfer_config::atxferabort, ast_features_xfer_config::atxfercallbackretries, ast_features_xfer_config::atxfercomplete, ast_features_xfer_config::atxferdropcall, ast_features_xfer_config::atxferloopdelay, ast_features_xfer_config::atxfernoanswertimeout, ast_features_xfer_config::atxferswap, ast_features_xfer_config::atxferthreeway, ast_features_xfer_config::transferdialattempts, ast_features_xfer_config::transferdigittimeout, ast_features_xfer_config::transferinvalidsound, ast_features_xfer_config::transferretrysound, ast_features_xfer_config::xferfailsound, and ast_features_xfer_config::xfersound.
Referenced by internal_feature_read().
 {
    int res = 0;
    if (!strcasecmp(field, "transferdigittimeout")) {
       snprintf(buf, len, "%u", xfer->transferdigittimeout);
    } else if (!strcasecmp(field, "atxfernoanswertimeout")) {
       snprintf(buf, len, "%u", xfer->atxfernoanswertimeout);
    } else if (!strcasecmp(field, "atxferloopdelay")) {
       snprintf(buf, len, "%u", xfer->atxferloopdelay);
    } else if (!strcasecmp(field, "atxfercallbackretries")) {
       snprintf(buf, len, "%u", xfer->atxfercallbackretries);
    } else if (!strcasecmp(field, "atxferdropcall")) {
       snprintf(buf, len, "%u", xfer->atxferdropcall);
    } else if (!strcasecmp(field, "xfersound")) {
       ast_copy_string(buf, xfer->xfersound, len);
    } else if (!strcasecmp(field, "xferfailsound")) {
       ast_copy_string(buf, xfer->xferfailsound, len);
    } else if (!strcasecmp(field, "atxferabort")) {
       ast_copy_string(buf, xfer->atxferabort, len);
    } else if (!strcasecmp(field, "atxfercomplete")) {
       ast_copy_string(buf, xfer->atxfercomplete, len);
    } else if (!strcasecmp(field, "atxferthreeway")) {
       ast_copy_string(buf, xfer->atxferthreeway, len);
    } else if (!strcasecmp(field, "atxferswap")) {
       ast_copy_string(buf, xfer->atxferswap, len);
    } else if (!strcasecmp(field, "transferdialattempts")) {
       snprintf(buf, len, "%u", xfer->transferdialattempts);
    } else if (!strcasecmp(field, "transferretrysound")) {
       ast_copy_string(buf, xfer->transferretrysound, len);
    } else if (!strcasecmp(field, "transferinvalidsound")) {
       ast_copy_string(buf, xfer->transferinvalidsound, len);
    } else {
       /* Unrecognized option */
       res = -1;
    }
    return res;
 }
xfer_handler()
static int xfer_handler (const struct aco_option * opt, struct ast_variable * var, void * obj) static
Definition at line 1510 of file features_config.c.
References global, ast_variable::name, ast_variable::value, features_global_config::xfer, and xfer_set().
Referenced by load_config().
 {
    struct features_global_config *global = obj;
    struct ast_features_xfer_config *xfer = global->xfer;
    return xfer_set(xfer, var->name, var->value);
 }
xfer_set()
static int xfer_set (struct ast_features_xfer_config * xfer, const char * name, const char * value) static
Definition at line 876 of file features_config.c.
References ast_parse_arg(), ast_string_field_set, ast_true(), ast_features_xfer_config::atxfercallbackretries, ast_features_xfer_config::atxferdropcall, ast_features_xfer_config::atxferloopdelay, ast_features_xfer_config::atxfernoanswertimeout, PARSE_INT32, ast_features_xfer_config::transferdialattempts, and ast_features_xfer_config::transferdigittimeout.
Referenced by internal_feature_write(), and xfer_handler().
 {
    int res = 0;
    if (!strcasecmp(name, "transferdigittimeout")) {
       res = ast_parse_arg(value, PARSE_INT32, &xfer->transferdigittimeout);
    } else if (!strcasecmp(name, "atxfernoanswertimeout")) {
       res = ast_parse_arg(value, PARSE_INT32, &xfer->atxfernoanswertimeout);
    } else if (!strcasecmp(name, "atxferloopdelay")) {
       res = ast_parse_arg(value, PARSE_INT32, &xfer->atxferloopdelay);
    } else if (!strcasecmp(name, "atxfercallbackretries")) {
       res = ast_parse_arg(value, PARSE_INT32, &xfer->atxfercallbackretries);
    } else if (!strcasecmp(name, "atxferdropcall")) {
       xfer->atxferdropcall = ast_true(value);
    } else if (!strcasecmp(name, "xfersound")) {
       ast_string_field_set(xfer, xfersound, value);
    } else if (!strcasecmp(name, "xferfailsound")) {
       ast_string_field_set(xfer, xferfailsound, value);
    } else if (!strcasecmp(name, "atxferabort")) {
       ast_string_field_set(xfer, atxferabort, value);
    } else if (!strcasecmp(name, "atxfercomplete")) {
       ast_string_field_set(xfer, atxfercomplete, value);
    } else if (!strcasecmp(name, "atxferthreeway")) {
       ast_string_field_set(xfer, atxferthreeway, value);
    } else if (!strcasecmp(name, "atxferswap")) {
       ast_string_field_set(xfer, atxferswap, value);
    } else if (!strcasecmp(name, "transferdialattempts")) {
       res = ast_parse_arg(value, PARSE_INT32, &xfer->transferdialattempts);
    } else if (!strcasecmp(name, "transferretrysound")) {
       ast_string_field_set(xfer, transferretrysound, value);
    } else if (!strcasecmp(name, "transferinvalidsound")) {
       ast_string_field_set(xfer, transferinvalidsound, value);
    } else {
       /* Unrecognized option */
       res = -1;
    }
    return res;
 }
Variable Documentation
applicationmap_option
struct aco_type applicationmap_option static
Definition at line 596 of file features_config.c.
applicationmap_options
struct aco_type* applicationmap_options[] = ACO_TYPES(&applicationmap_option) static
Definition at line 625 of file features_config.c.
cli_features_config
struct ast_cli_entry cli_features_config[] static
Initial value:
= {
   { .handler =  handle_feature_show , .summary =  "Lists configured features" ,},
}
Definition at line 1972 of file features_config.c.
feature_ds_info
const struct ast_datastore_info feature_ds_info static
Initial value:
= {
   .type = "FEATURE",
   .destroy = feature_ds_destroy,
   .duplicate = feature_ds_duplicate,
}
Definition at line 1059 of file features_config.c.
feature_function
struct ast_custom_function feature_function static
Initial value:
= {
   .name = "FEATURE",
   .read = feature_read,
   .write = feature_write
}
Definition at line 1746 of file features_config.c.
featuregroup_option
struct aco_type featuregroup_option static
Definition at line 604 of file features_config.c.
featuregroup_options
struct aco_type* featuregroup_options[] = ACO_TYPES(&featuregroup_option) static
Definition at line 626 of file features_config.c.
featuremap_function
struct ast_custom_function featuremap_function static
Initial value:
= {
   .name = "FEATUREMAP",
   .read = featuremap_read,
   .write = featuremap_write
}
Definition at line 1752 of file features_config.c.
featuremap_option
struct aco_type featuremap_option static
Definition at line 588 of file features_config.c.
featuremap_options
struct aco_type* featuremap_options[] = ACO_TYPES(&featuremap_option) static
Definition at line 624 of file features_config.c.
features_conf
struct aco_file features_conf static
Initial value:
= {
   .filename = "features.conf",
   .types = ACO_TYPES(&global_option, &featuremap_option, &applicationmap_option, &featuregroup_option, &parkinglot_option),
}
Definition at line 629 of file features_config.c.
global_option
struct aco_type global_option static
Definition at line 580 of file features_config.c.
global_options
struct aco_type* global_options[] = ACO_TYPES(&global_option) static
Definition at line 623 of file features_config.c.
parking_warning
int parking_warning = 0 static
Definition at line 1528 of file features_config.c.
Referenced by reload_features_config(), and unsupported_handler().
parkinglot_option
struct aco_type parkinglot_option static
Definition at line 614 of file features_config.c.
parkinglot_options
struct aco_type* parkinglot_options[] = ACO_TYPES(&parkinglot_option) static
Definition at line 627 of file features_config.c.