Asterisk - The Open Source Telephony Project: func_pjsip_aor.c File Reference
func_pjsip_aor.c File Reference
Module: Dial plan functions
Get information about a PJSIP AOR.
#include "asterisk.h"
#include <pjsip.h>
#include <pjlib.h>
#include "asterisk/app.h"
#include "asterisk/pbx.h"
#include "asterisk/module.h"
#include "asterisk/sorcery.h"
#include "asterisk/res_pjsip.h"
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int load_module (void)
static int pjsip_aor_function_read (struct ast_channel *chan, const char *cmd, char *data, struct ast_str **buf, ssize_t len)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_DEFAULT , .description = "Get information about a PJSIP AOR" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .requires = "res_pjsip", }
static const struct ast_module_info * ast_module_info = &__mod_info
static struct ast_custom_function pjsip_aor_function
Detailed Description
Get information about a PJSIP AOR.
Author
Joshua Colp <jcolp@digium.com>
Definition in file func_pjsip_aor.c.
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 189 of file func_pjsip_aor.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 189 of file func_pjsip_aor.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 189 of file func_pjsip_aor.c.
load_module()
static int load_module (void) static
Definition at line 179 of file func_pjsip_aor.c.
References ast_custom_function_register, AST_MODFLAG_DEFAULT, AST_MODULE_INFO(), AST_MODULE_SUPPORT_CORE, ASTERISK_GPL_KEY, and unload_module().
 {
    return ast_custom_function_register(&pjsip_aor_function);
 }
pjsip_aor_function_read()
static int pjsip_aor_function_read (struct ast_channel * chan, const char * cmd, char * data, struct ast_str ** buf, ssize_t len) static
Definition at line 70 of file func_pjsip_aor.c.
References ao2_cleanup, ao2_iterator_destroy(), ao2_iterator_init(), ao2_iterator_next, ao2_ref, args, AST_APP_ARG, AST_DECLARE_APP_ARGS, ast_log, AST_LOG_ERROR, AST_LOG_WARNING, ast_sip_get_sorcery(), ast_sip_location_retrieve_aor_contacts(), ast_sorcery_object_get_id(), ast_sorcery_objectset_create, ast_sorcery_retrieve_by_id(), AST_STANDARD_APP_ARGS, ast_str_append(), ast_str_set(), ast_strdupa, ast_strlen_zero, ast_variables_destroy(), first, LOG_WARNING, ast_variable::name, ast_variable::next, NULL, RAII_VAR, and ast_variable::value.
 {
    struct ast_sorcery *pjsip_sorcery;
    char *parsed_data = ast_strdupa(data);
    RAII_VAR(struct ast_sip_aor *, aor_obj, NULL, ao2_cleanup);
    int res = 0;
    AST_DECLARE_APP_ARGS(args,
       AST_APP_ARG(aor_name);
       AST_APP_ARG(field_name);
    );
    /* Check for zero arguments */
    if (ast_strlen_zero(parsed_data)) {
       ast_log(AST_LOG_ERROR, "Cannot call %s without arguments\n", cmd);
       return -1;
    }
    AST_STANDARD_APP_ARGS(args, parsed_data);
    if (ast_strlen_zero(args.aor_name)) {
       ast_log(AST_LOG_ERROR, "Cannot call %s without an AOR name to query\n", cmd);
       return -1;
    }
    if (ast_strlen_zero(args.field_name)) {
       ast_log(AST_LOG_ERROR, "Cannot call %s with an empty field name to query\n", cmd);
       return -1;
    }
    pjsip_sorcery = ast_sip_get_sorcery();
    if (!pjsip_sorcery) {
       ast_log(AST_LOG_ERROR, "Unable to retrieve PJSIP configuration: sorcery object is NULL\n");
       return -1;
    }
    aor_obj = ast_sorcery_retrieve_by_id(pjsip_sorcery, "aor", args.aor_name);
    if (!aor_obj) {
       ast_log(AST_LOG_WARNING, "Failed to retrieve information for AOR '%s'\n", args.aor_name);
       return -1;
    }
    if (!strcmp(args.field_name, "contact")) {
       /* The multiple fields handler for contact does not provide a list of contact object names, which is what we want, so we
        * handle contact specifically to provide this.
        */
       RAII_VAR(struct ao2_container *, contacts, NULL, ao2_cleanup);
       struct ao2_iterator i;
       struct ast_sip_contact *contact;
       int first = 1;
       contacts = ast_sip_location_retrieve_aor_contacts(aor_obj);
       if (!contacts) {
          ast_log(LOG_WARNING, "Failed to retrieve contacts for AOR '%s'\n", args.aor_name);
          return -1;
       }
       i = ao2_iterator_init(contacts, 0);
       while ((contact = ao2_iterator_next(&i))) {
          if (!first) {
             ast_str_append(buf, len, "%s", ",");
          }
          ast_str_append(buf, len, "%s", ast_sorcery_object_get_id(contact));
          first = 0;
          ao2_ref(contact, -1);
       }
       ao2_iterator_destroy(&i);
    } else {
       struct ast_variable *change_set;
       struct ast_variable *it_change_set;
       change_set = ast_sorcery_objectset_create(pjsip_sorcery, aor_obj);
       if (!change_set) {
          ast_log(AST_LOG_WARNING, "Failed to retrieve information for AOR '%s': change set is NULL\n", args.aor_name);
          return -1;
       }
       for (it_change_set = change_set; it_change_set; it_change_set = it_change_set->next) {
          if (!strcmp(it_change_set->name, args.field_name)) {
             ast_str_set(buf, len, "%s", it_change_set->value);
             break;
          }
       }
       if (!it_change_set) {
          ast_log(AST_LOG_WARNING, "Unknown property '%s' for PJSIP AOR\n", args.field_name);
          res = 1;
       }
       ast_variables_destroy(change_set);
    }
    return res;
 }
unload_module()
static int unload_module (void) static
Definition at line 174 of file func_pjsip_aor.c.
References ast_custom_function_unregister().
Referenced by load_module().
 {
    return ast_custom_function_unregister(&pjsip_aor_function);
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_DEFAULT , .description = "Get information about a PJSIP AOR" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .requires = "res_pjsip", } static
Definition at line 189 of file func_pjsip_aor.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 189 of file func_pjsip_aor.c.
pjsip_aor_function
struct ast_custom_function pjsip_aor_function static
Initial value:
= {
   .name = "PJSIP_AOR",
   .read2 = pjsip_aor_function_read,
}
Definition at line 169 of file func_pjsip_aor.c.