Asterisk - The Open Source Telephony Project: res_pjsip_stir_shaken.c File Reference
res_pjsip_stir_shaken.c File Reference
#include "asterisk.h"
#include "asterisk/res_pjsip.h"
#include "asterisk/res_pjsip_session.h"
#include "asterisk/module.h"
#include "asterisk/res_stir_shaken.h"
Macros
#define AST_BUILDOPT_SUM ""
Functions
static void __reg_module (void)
static void __unreg_module (void)
static void add_date_header (const struct ast_sip_session *session, pjsip_tx_data *tdata)
static int add_identity_header (const struct ast_sip_session *session, pjsip_tx_data *tdata)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int compare_caller_id (char *caller_id, const char *json_str)
Compare the caller ID from the INVITE with the one in the payload.
static int compare_timestamp (const char *json_str)
Compare the current timestamp with the one in the payload. If the difference is greater than the signature timeout, it's not valid anymore.
static char * get_attestation_from_payload (const char *json_str)
Get the attestation from the payload.
static int load_module (void)
static int stir_shaken_incoming_request (struct ast_sip_session *session, pjsip_rx_data *rdata)
static void stir_shaken_outgoing_request (struct ast_sip_session *session, pjsip_tx_data *tdata)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_GLOBAL_SYMBOLS | AST_MODFLAG_LOAD_ORDER , .description = "PJSIP STIR/SHAKEN Module for Asterisk" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .requires = "res_pjsip,res_pjsip_session,res_stir_shaken", }
static const struct ast_module_info * ast_module_info = &__mod_info
static struct ast_sip_session_supplement stir_shaken_supplement
Macro Definition Documentation
AST_BUILDOPT_SUM
#define AST_BUILDOPT_SUM ""
Definition at line 373 of file res_pjsip_stir_shaken.c.
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 381 of file res_pjsip_stir_shaken.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 381 of file res_pjsip_stir_shaken.c.
add_date_header()
static void add_date_header (const struct ast_sip_session * session, pjsip_tx_data * tdata) static
Definition at line 320 of file res_pjsip_stir_shaken.c.
References ast_debug, ast_sip_add_date_header(), and NULL.
Referenced by stir_shaken_outgoing_request().
 {
    static const pj_str_t date_str = { "Date", 4 };
    pjsip_fromto_hdr *old_date;
    old_date = pjsip_msg_find_hdr_by_name(tdata->msg, &date_str, NULL);
    if (old_date) {
       ast_debug(3, "Found old STIR/SHAKEN date header, no need to add one\n");
       return;
    }
    ast_sip_add_date_header(tdata);
 }
add_identity_header()
static int add_identity_header (const struct ast_sip_session * session, pjsip_tx_data * tdata) static
Definition at line 211 of file res_pjsip_stir_shaken.c.
References ast_base64url_encode_string(), ast_calloc, ast_copy_pj_str(), ast_free, ast_json_dump_string, ast_json_free(), ast_json_object_get(), ast_json_pack(), ast_log, ast_malloc, ast_stir_shaken_payload_free(), ast_stir_shaken_payload_get_public_cert_url(), ast_stir_shaken_payload_get_signature(), ast_stir_shaken_sign(), ast_sip_session::id, LOG_ERROR, NULL, ast_party_id::number, ast_stir_shaken_payload::public_cert_url, RAII_VAR, ast_stir_shaken_payload::signature, STIR_SHAKEN_ENCRYPTION_ALGORITHM, STIR_SHAKEN_PPT, and ast_party_number::str.
Referenced by stir_shaken_outgoing_request().
 {
    static const pj_str_t identity_str = { "Identity", 8 };
    pjsip_generic_string_hdr *identity_hdr;
    pj_str_t identity_val;
    pjsip_fromto_hdr *old_identity;
    pjsip_fromto_hdr *to;
    pjsip_sip_uri *uri;
    char *signature;
    char *public_cert_url;
    struct ast_json *header;
    struct ast_json *payload;
    char *dumped_string;
    RAII_VAR(char *, dest_tn, NULL, ast_free);
    RAII_VAR(struct ast_json *, json, NULL, ast_json_free);
    RAII_VAR(struct ast_stir_shaken_payload *, ss_payload, NULL, ast_stir_shaken_payload_free);
    RAII_VAR(char *, encoded_header, NULL, ast_free);
    RAII_VAR(char *, encoded_payload, NULL, ast_free);
    RAII_VAR(char *, combined_str, NULL, ast_free);
    size_t combined_size;
    old_identity = pjsip_msg_find_hdr_by_name(tdata->msg, &identity_str, NULL);
    if (old_identity) {
       return 0;
    }
    to = pjsip_msg_find_hdr(tdata->msg, PJSIP_H_TO, NULL);
    if (!to) {
       ast_log(LOG_ERROR, "Failed to find To header while adding STIR/SHAKEN Identity header\n");
       return -1;
    }
    uri = pjsip_uri_get_uri(to->uri);
    if (!uri) {
       ast_log(LOG_ERROR, "Failed to retrieve URI from To header while adding STIR/SHAKEN Identity header\n");
       return -1;
    }
    dest_tn = ast_malloc(uri->user.slen + 1);
    if (!dest_tn) {
       ast_log(LOG_ERROR, "Failed to allocate memory for STIR/SHAKEN dest->tn\n");
       return -1;
    }
    ast_copy_pj_str(dest_tn, &uri->user, uri->user.slen + 1);
    /* x5u (public key URL), attestation, and origid will be added by ast_stir_shaken_sign */
    json = ast_json_pack("{s: {s: s, s: s, s: s}, s: {s: {s: s}, s: {s: s}}}",
       "header", "alg", "ES256", "ppt", "shaken", "typ", "passport",
       "payload", "dest", "tn", dest_tn, "orig", "tn",
       session->id.number.str);
    if (!json) {
       ast_log(LOG_ERROR, "Failed to allocate memory for STIR/SHAKEN JSON\n");
       return -1;
    }
    ss_payload = ast_stir_shaken_sign(json);
    if (!ss_payload) {
       ast_log(LOG_ERROR, "Failed to allocate memory for STIR/SHAKEN payload\n");
       return -1;
    }
    header = ast_json_object_get(json, "header");
    dumped_string = ast_json_dump_string(header);
    encoded_header = ast_base64url_encode_string(dumped_string);
    ast_json_free(dumped_string);
    if (!encoded_header) {
       ast_log(LOG_ERROR, "Failed to encode STIR/SHAKEN header\n");
       return -1;
    }
    payload = ast_json_object_get(json, "payload");
    dumped_string = ast_json_dump_string(payload);
    encoded_payload = ast_base64url_encode_string(dumped_string);
    ast_json_free(dumped_string);
    if (!encoded_payload) {
       ast_log(LOG_ERROR, "Failed to encode STIR/SHAKEN payload\n");
       return -1;
    }
    signature = (char *)ast_stir_shaken_payload_get_signature(ss_payload);
    public_cert_url = ast_stir_shaken_payload_get_public_cert_url(ss_payload);
    /* The format for the identity header:
     * header.payload.signature;info=<public_cert_url>alg=STIR_SHAKEN_ENCRYPTION_ALGORITHM;ppt=STIR_SHAKEN_PPT
     */
    combined_size = strlen(encoded_header) + 1 + strlen(encoded_payload) + 1
       + strlen(signature) + strlen(";info=<>alg=;ppt=") + strlen(public_cert_url)
       + strlen(STIR_SHAKEN_ENCRYPTION_ALGORITHM) + strlen(STIR_SHAKEN_PPT) + 1;
    combined_str = ast_calloc(1, combined_size);
    if (!combined_str) {
       ast_log(LOG_ERROR, "Failed to allocate memory for STIR/SHAKEN identity string\n");
       return -1;
    }
    snprintf(combined_str, combined_size, "%s.%s.%s;info=<%s>alg=%s;ppt=%s", encoded_header,
       encoded_payload, signature, public_cert_url, STIR_SHAKEN_ENCRYPTION_ALGORITHM, STIR_SHAKEN_PPT);
    identity_val = pj_str(combined_str);
    identity_hdr = pjsip_generic_string_hdr_create(tdata->pool, &identity_str, &identity_val);
    if (!identity_hdr) {
       ast_log(LOG_ERROR, "Failed to create STIR/SHAKEN Identity header\n");
       return -1;
    }
    pjsip_msg_add_hdr(tdata->msg, (pjsip_hdr *)identity_hdr);
    return 0;
 }
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 381 of file res_pjsip_stir_shaken.c.
compare_caller_id()
static int compare_caller_id (char * caller_id, const char * json_str) static
Compare the caller ID from the INVITE with the one in the payload.
Parameters
json_str The JSON string represntation of the payload
Return values
-1 on failure
0 on success
Definition at line 66 of file res_pjsip_stir_shaken.c.
References ast_json_free(), ast_json_load_string(), ast_json_object_get(), ast_json_string_get(), NULL, and RAII_VAR.
Referenced by stir_shaken_incoming_request().
 {
    RAII_VAR(struct ast_json *, json, NULL, ast_json_free);
    char *caller_id_other;
    json = ast_json_load_string(json_str, NULL);
    caller_id_other = (char *)ast_json_string_get(ast_json_object_get(
       ast_json_object_get(json, "orig"), "tn"));
    if (strcmp(caller_id, caller_id_other)) {
       return -1;
    }
    return 0;
 }
compare_timestamp()
static int compare_timestamp (const char * json_str) static
Compare the current timestamp with the one in the payload. If the difference is greater than the signature timeout, it's not valid anymore.
Parameters
json_str The JSON string representation of the payload
Return values
-1 on failure
0 on success
Definition at line 91 of file res_pjsip_stir_shaken.c.
References ast_debug, ast_json_free(), ast_json_integer_get(), ast_json_load_string(), ast_json_object_get(), ast_stir_shaken_get_signature_timeout(), ast_tvnow(), NULL, and RAII_VAR.
Referenced by stir_shaken_incoming_request().
 {
    RAII_VAR(struct ast_json *, json, NULL, ast_json_free);
    long int timestamp;
    struct timeval now = ast_tvnow();
 #ifdef TEST_FRAMEWORK
    ast_debug(3, "Ignoring STIR/SHAKEN timestamp\n");
    return 0;
 #endif
    json = ast_json_load_string(json_str, NULL);
    timestamp = ast_json_integer_get(ast_json_object_get(json, "iat"));
    if (now.tv_sec - timestamp > ast_stir_shaken_get_signature_timeout()) {
       return -1;
    }
    return 0;
 }
get_attestation_from_payload()
static char* get_attestation_from_payload (const char * json_str) static
Get the attestation from the payload.
Parameters
json_str The JSON string representation of the payload
Return values
Empty string on failure
The attestation on success
Definition at line 43 of file res_pjsip_stir_shaken.c.
References ast_json_free(), ast_json_load_string(), ast_json_object_get(), ast_json_string_get(), ast_strlen_zero, NULL, and RAII_VAR.
Referenced by stir_shaken_incoming_request().
 {
    RAII_VAR(struct ast_json *, json, NULL, ast_json_free);
    char *attestation;
    json = ast_json_load_string(json_str, NULL);
    attestation = (char *)ast_json_string_get(ast_json_object_get(json, "attest"));
    if (!ast_strlen_zero(attestation)) {
       return attestation;
    }
    return "";
 }
load_module()
static int load_module (void) static
Definition at line 366 of file res_pjsip_stir_shaken.c.
References AST_MODULE_LOAD_SUCCESS, and ast_sip_session_register_supplement.
 {
    ast_sip_session_register_supplement(&stir_shaken_supplement);
    return AST_MODULE_LOAD_SUCCESS;
 }
stir_shaken_incoming_request()
static int stir_shaken_incoming_request (struct ast_sip_session * session, pjsip_rx_data * rdata) static
Definition at line 122 of file res_pjsip_stir_shaken.c.
References ast_base64url_decode_string(), ast_begins_with(), ast_free, ast_sip_rdata_get_header_value(), ast_stir_shaken_add_verification(), ast_stir_shaken_payload_free(), ast_stir_shaken_verify(), AST_STIR_SHAKEN_VERIFY_MISMATCH, AST_STIR_SHAKEN_VERIFY_NOT_PRESENT, AST_STIR_SHAKEN_VERIFY_PASSED, AST_STIR_SHAKEN_VERIFY_SIGNATURE_FAILED, ast_strlen_zero, ast_sip_session::channel, compare_caller_id(), compare_timestamp(), ast_sip_session::endpoint, get_attestation_from_payload(), ast_sip_session::id, NULL, ast_party_id::number, ast_stir_shaken_payload::payload, RAII_VAR, ast_sip_endpoint::stir_shaken, and ast_party_number::str.
 {
    static const pj_str_t identity_str = { "Identity", 8 };
    char *identity_hdr_val;
    char *encoded_val;
    struct ast_channel *chan = session->channel;
    char *caller_id = session->id.number.str;
    RAII_VAR(char *, header, NULL, ast_free);
    RAII_VAR(char *, payload, NULL, ast_free);
    char *signature;
    char *algorithm;
    char *public_cert_url;
    char *attestation;
    int mismatch = 0;
    struct ast_stir_shaken_payload *ss_payload;
    if (!session->endpoint->stir_shaken) {
       return 0;
    }
    identity_hdr_val = ast_sip_rdata_get_header_value(rdata, identity_str);
    if (ast_strlen_zero(identity_hdr_val)) {
       ast_stir_shaken_add_verification(chan, caller_id, "", AST_STIR_SHAKEN_VERIFY_NOT_PRESENT);
       return 0;
    }
    encoded_val = strtok_r(identity_hdr_val, ".", &identity_hdr_val);
    header = ast_base64url_decode_string(encoded_val);
    if (ast_strlen_zero(header)) {
       ast_stir_shaken_add_verification(chan, caller_id, "", AST_STIR_SHAKEN_VERIFY_SIGNATURE_FAILED);
       return 0;
    }
    encoded_val = strtok_r(identity_hdr_val, ".", &identity_hdr_val);
    payload = ast_base64url_decode_string(encoded_val);
    if (ast_strlen_zero(payload)) {
       ast_stir_shaken_add_verification(chan, caller_id, "", AST_STIR_SHAKEN_VERIFY_SIGNATURE_FAILED);
       return 0;
    }
    /* It's fine to leave the signature encoded */
    signature = strtok_r(identity_hdr_val, ";", &identity_hdr_val);
    if (ast_strlen_zero(signature)) {
       ast_stir_shaken_add_verification(chan, caller_id, "", AST_STIR_SHAKEN_VERIFY_SIGNATURE_FAILED);
       return 0;
    }
    /* Trim "info=<" to get public cert URL */
    strtok_r(identity_hdr_val, "<", &identity_hdr_val);
    public_cert_url = strtok_r(identity_hdr_val, ">", &identity_hdr_val);
    if (ast_strlen_zero(public_cert_url)) {
       ast_stir_shaken_add_verification(chan, caller_id, "", AST_STIR_SHAKEN_VERIFY_SIGNATURE_FAILED);
       return 0;
    }
    /* Make sure the public URL is actually a URL */
    if (!ast_begins_with(public_cert_url, "http")) {
       ast_stir_shaken_add_verification(chan, caller_id, "", AST_STIR_SHAKEN_VERIFY_SIGNATURE_FAILED);
       return 0;
    }
    algorithm = strtok_r(identity_hdr_val, ";", &identity_hdr_val);
    if (ast_strlen_zero(algorithm)) {
       ast_stir_shaken_add_verification(chan, caller_id, "", AST_STIR_SHAKEN_VERIFY_SIGNATURE_FAILED);
       return 0;
    }
    attestation = get_attestation_from_payload(payload);
    ss_payload = ast_stir_shaken_verify(header, payload, signature, algorithm, public_cert_url);
    if (!ss_payload) {
       ast_stir_shaken_add_verification(chan, caller_id, attestation, AST_STIR_SHAKEN_VERIFY_SIGNATURE_FAILED);
       return 0;
    }
    ast_stir_shaken_payload_free(ss_payload);
    mismatch |= compare_caller_id(caller_id, payload);
    mismatch |= compare_timestamp(payload);
    if (mismatch) {
       ast_stir_shaken_add_verification(chan, caller_id, attestation, AST_STIR_SHAKEN_VERIFY_MISMATCH);
       return 0;
    }
    ast_stir_shaken_add_verification(chan, caller_id, attestation, AST_STIR_SHAKEN_VERIFY_PASSED);
    return 0;
 }
stir_shaken_outgoing_request()
static void stir_shaken_outgoing_request (struct ast_sip_session * session, pjsip_tx_data * tdata) static
Definition at line 334 of file res_pjsip_stir_shaken.c.
References add_date_header(), add_identity_header(), ast_strlen_zero, ast_sip_session::endpoint, ast_sip_session::id, ast_party_id::number, ast_sip_endpoint::stir_shaken, ast_party_number::str, and ast_party_number::valid.
 {
    if (!session->endpoint->stir_shaken) {
       return;
    }
    if (ast_strlen_zero(session->id.number.str) && session->id.number.valid) {
       return;
    }
    /* If adding the Identity header fails for some reason, there's no point
     * adding the Date header.
     */
    if ((add_identity_header(session, tdata)) != 0) {
       return;
    }
    add_date_header(session, tdata);
 }
unload_module()
static int unload_module (void) static
Definition at line 360 of file res_pjsip_stir_shaken.c.
References ast_sip_session_unregister_supplement().
 {
    ast_sip_session_unregister_supplement(&stir_shaken_supplement);
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_GLOBAL_SYMBOLS | AST_MODFLAG_LOAD_ORDER , .description = "PJSIP STIR/SHAKEN Module for Asterisk" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .requires = "res_pjsip,res_pjsip_session,res_stir_shaken", } static
Definition at line 381 of file res_pjsip_stir_shaken.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 381 of file res_pjsip_stir_shaken.c.
stir_shaken_supplement
struct ast_sip_session_supplement stir_shaken_supplement static
Definition at line 353 of file res_pjsip_stir_shaken.c.