Asterisk - The Open Source Telephony Project: conf_state_multi_marked.c File Reference
conf_state_multi_marked.c File Reference
Dial plan applications
Confbridge state handling for the MULTI_MARKED state.
#include "asterisk.h"
#include "asterisk/utils.h"
#include "asterisk/linkedlists.h"
#include "include/confbridge.h"
#include "asterisk/musiconhold.h"
#include "include/conf_state.h"
#include "asterisk/pbx.h"
Functions
static void join_active (struct confbridge_user *user)
static void join_marked (struct confbridge_user *user)
static void leave_active (struct confbridge_user *user)
static void leave_marked (struct confbridge_user *user)
static int post_join_play_begin (struct confbridge_user *user)
static void transition_to_marked (struct confbridge_user *user)
Variables
struct confbridge_state * CONF_STATE_MULTI_MARKED = &STATE_MULTI_MARKED
Conference state with multiple active users and at least one marked user.
static struct confbridge_state STATE_MULTI_MARKED
Detailed Description
Confbridge state handling for the MULTI_MARKED state.
Author
Terry Wilson <twilson@digium.com>
Definition in file conf_state_multi_marked.c.
Function Documentation
join_active()
static void join_active (struct confbridge_user * user) static
Definition at line 61 of file conf_state_multi_marked.c.
References conf_add_user_active(), conf_update_user_mute(), and confbridge_user::conference.
 {
    conf_add_user_active(user->conference, user);
    conf_update_user_mute(user);
 }
join_marked()
static void join_marked (struct confbridge_user * user) static
Definition at line 67 of file conf_state_multi_marked.c.
References conf_add_user_marked(), conf_update_user_mute(), and confbridge_user::conference.
 {
    conf_add_user_marked(user->conference, user);
    conf_update_user_mute(user);
 }
leave_active()
static void leave_active (struct confbridge_user * user) static
Definition at line 73 of file conf_state_multi_marked.c.
References confbridge_conference::activeusers, conf_change_state(), conf_remove_user_active(), CONF_STATE_SINGLE_MARKED, and confbridge_user::conference.
 {
    conf_remove_user_active(user->conference, user);
    if (user->conference->activeusers == 1) {
       conf_change_state(user, CONF_STATE_SINGLE_MARKED);
    }
 }
leave_marked()
static void leave_marked (struct confbridge_user * user) static
Definition at line 81 of file conf_state_multi_marked.c.
References confbridge_conference::active_list, confbridge_conference::activeusers, ast_bridge_remove(), AST_LIST_INSERT_TAIL, AST_LIST_REMOVE_CURRENT, AST_LIST_TRAVERSE, AST_LIST_TRAVERSE_SAFE_BEGIN, AST_LIST_TRAVERSE_SAFE_END, ast_test_flag, async_play_sound_file(), confbridge_conference::b_profile, confbridge_conference::bridge, confbridge_user::chan, conf_change_state(), conf_get_sound(), conf_moh_start(), conf_remove_user_marked(), CONF_SOUND_LEADER_HAS_LEFT, CONF_STATE_EMPTY, CONF_STATE_INACTIVE, CONF_STATE_MULTI, CONF_STATE_SINGLE, CONF_STATE_SINGLE_MARKED, conf_update_user_mute(), confbridge_user::conference, confbridge_user::kicked, confbridge_user::list, confbridge_conference::markedusers, NULL, pbx_builtin_setvar_helper(), bridge_profile::sounds, confbridge_user::u_profile, USER_OPT_ENDMARKED, USER_OPT_MARKEDUSER, USER_OPT_MUSICONHOLD, USER_OPT_QUIET, USER_OPT_WAITMARKED, confbridge_conference::waiting_list, and confbridge_conference::waitingusers.
 {
    struct confbridge_user *user_iter;
    int need_prompt = 0;
    conf_remove_user_marked(user->conference, user);
    if (user->conference->markedusers == 0) {
       AST_LIST_TRAVERSE_SAFE_BEGIN(&user->conference->active_list, user_iter, list) {
          /* Kick ENDMARKED cbu_iters */
          if (ast_test_flag(&user_iter->u_profile, USER_OPT_ENDMARKED) && !user_iter->kicked) {
             if (ast_test_flag(&user_iter->u_profile, USER_OPT_WAITMARKED)
                && !ast_test_flag(&user_iter->u_profile, USER_OPT_MARKEDUSER)) {
                AST_LIST_REMOVE_CURRENT(list);
                user_iter->conference->activeusers--;
                AST_LIST_INSERT_TAIL(&user_iter->conference->waiting_list, user_iter, list);
                user_iter->conference->waitingusers++;
             }
             user_iter->kicked = 1;
             pbx_builtin_setvar_helper(user_iter->chan, "CONFBRIDGE_RESULT", "ENDMARKED");
             ast_bridge_remove(user_iter->conference->bridge, user_iter->chan);
          } else if (ast_test_flag(&user_iter->u_profile, USER_OPT_WAITMARKED)
             && !ast_test_flag(&user_iter->u_profile, USER_OPT_MARKEDUSER)) {
             need_prompt = 1;
             AST_LIST_REMOVE_CURRENT(list);
             user_iter->conference->activeusers--;
             AST_LIST_INSERT_TAIL(&user_iter->conference->waiting_list, user_iter, list);
             user_iter->conference->waitingusers++;
          } else {
             /* User is neither wait_marked nor end_marked; however, they
              * should still hear the prompt.
              */
             need_prompt = 1;
          }
       }
       AST_LIST_TRAVERSE_SAFE_END;
    }
    switch (user->conference->activeusers) {
    case 0:
       /* Implies markedusers == 0 */
       switch (user->conference->waitingusers) {
       case 0:
          conf_change_state(user, CONF_STATE_EMPTY);
          break;
       default:
          conf_change_state(user, CONF_STATE_INACTIVE);
          break;
       }
       break;
    case 1:
       switch (user->conference->markedusers) {
       case 0:
          conf_change_state(user, CONF_STATE_SINGLE);
          break;
       case 1:
          /* XXX I seem to remember doing this for a reason, but right now it escapes me
           * how we could possibly ever have a waiting user while we have a marked user */
          switch (user->conference->waitingusers) {
          case 0:
             conf_change_state(user, CONF_STATE_SINGLE_MARKED);
             break;
          case 1:
             break; /* Stay in marked */
          }
          break;
       }
       break;
    default:
       switch (user->conference->markedusers) {
       case 0:
          conf_change_state(user, CONF_STATE_MULTI);
          break;
       default:
          break; /* Stay in marked */
       }
    }
    if (need_prompt) {
       /* Play back the audio prompt saying the leader has left the conference */
       if (!ast_test_flag(&user->u_profile, USER_OPT_QUIET)) {
          async_play_sound_file(user->conference,
             conf_get_sound(CONF_SOUND_LEADER_HAS_LEFT, user->conference->b_profile.sounds),
             NULL);
       }
       AST_LIST_TRAVERSE(&user->conference->waiting_list, user_iter, list) {
          if (user_iter->kicked) {
             continue;
          }
          if (ast_test_flag(&user_iter->u_profile, USER_OPT_MUSICONHOLD)) {
             conf_moh_start(user_iter);
          }
          conf_update_user_mute(user_iter);
       }
    }
 }
post_join_play_begin()
static int post_join_play_begin (struct confbridge_user * user) static
Definition at line 182 of file conf_state_multi_marked.c.
References ast_autoservice_start(), ast_autoservice_stop(), confbridge_conference::b_profile, confbridge_user::chan, conf_get_sound(), CONF_SOUND_BEGIN, confbridge_user::conference, play_sound_file(), and bridge_profile::sounds.
Referenced by transition_to_marked().
 {
    int res;
    ast_autoservice_start(user->chan);
    res = play_sound_file(user->conference,
       conf_get_sound(CONF_SOUND_BEGIN, user->conference->b_profile.sounds));
    ast_autoservice_stop(user->chan);
    return res;
 }
transition_to_marked()
static void transition_to_marked (struct confbridge_user * user) static
Definition at line 193 of file conf_state_multi_marked.c.
References confbridge_conference::active_list, confbridge_conference::activeusers, AST_LIST_INSERT_TAIL, AST_LIST_REMOVE_CURRENT, AST_LIST_TRAVERSE_SAFE_BEGIN, AST_LIST_TRAVERSE_SAFE_END, ast_test_flag, conf_add_post_join_action(), conf_moh_stop(), conf_update_user_mute(), confbridge_user::conference, confbridge_user::list, confbridge_conference::markedusers, confbridge_user::playing_moh, post_join_play_begin(), confbridge_user::u_profile, USER_OPT_MARKEDUSER, USER_OPT_QUIET, confbridge_conference::waiting_list, and confbridge_conference::waitingusers.
 {
    struct confbridge_user *user_iter;
    int waitmarked_moved = 0;
    /* Move all waiting users to active, stopping MOH and unmuting if necessary */
    AST_LIST_TRAVERSE_SAFE_BEGIN(&user->conference->waiting_list, user_iter, list) {
       AST_LIST_REMOVE_CURRENT(list);
       user->conference->waitingusers--;
       AST_LIST_INSERT_TAIL(&user->conference->active_list, user_iter, list);
       user->conference->activeusers++;
       if (user_iter->playing_moh) {
          conf_moh_stop(user_iter);
       }
       conf_update_user_mute(user_iter);
       waitmarked_moved++;
    }
    AST_LIST_TRAVERSE_SAFE_END;
    /* Play the audio file stating that the conference is beginning */
    if (user->conference->markedusers == 1
       && ast_test_flag(&user->u_profile, USER_OPT_MARKEDUSER)
       && !ast_test_flag(&user->u_profile, USER_OPT_QUIET)
       && waitmarked_moved) {
       conf_add_post_join_action(user, post_join_play_begin);
    }
 }
Variable Documentation
CONF_STATE_MULTI_MARKED
struct confbridge_state* CONF_STATE_MULTI_MARKED = &STATE_MULTI_MARKED
Conference state with multiple active users and at least one marked user.
Definition at line 59 of file conf_state_multi_marked.c.
Referenced by join_active(), and join_marked().
STATE_MULTI_MARKED
struct confbridge_state STATE_MULTI_MARKED static
Definition at line 49 of file conf_state_multi_marked.c.