Asterisk - The Open Source Telephony Project: route.h File Reference
route.h File Reference
sip_route header file
#include "asterisk/linkedlists.h"
#include "asterisk/strings.h"
Data Structures
struct sip_route
Structure to store route information.
Macros
#define sip_route_empty(route) AST_LIST_EMPTY(&(route)->list)
Check if route has no URI's.
Enumerations
enum sip_route_type { route_loose = 0, route_strict, route_invalidated }
Functions
const char * sip_route_add (struct sip_route *route, const char *uri, size_t len, int inserthead)
Add a new hop to the route.
void sip_route_clear (struct sip_route *route)
Free all routes in the list.
void sip_route_copy (struct sip_route *dst, const struct sip_route *src)
copy route-set
void sip_route_dump (const struct sip_route *route)
Verbose dump of all hops for debugging.
const char * sip_route_first_uri (const struct sip_route *route)
Get the URI of the route's first hop.
int sip_route_is_strict (struct sip_route *route)
Check if the route is strict.
struct ast_str * sip_route_list (const struct sip_route *route, int formatcli, int skip)
Make the comma separated list of route hops.
void sip_route_process_header (struct sip_route *route, const char *header, int inserthead)
Add routes from header.
Detailed Description
sip_route header file
Definition in file route.h.
Macro Definition Documentation
sip_route_empty
#define sip_route_empty (route) AST_LIST_EMPTY(&(route)->list)
Check if route has no URI's.
Definition at line 118 of file route.h.
Referenced by add_route(), build_route(), create_addr_from_peer(), handle_response_invite(), parse_register_contact(), reqprep(), sip_poke_peer(), sip_route_add(), and sip_route_dump().
Enumeration Type Documentation
sip_route_type
enum sip_route_type
Enumerator
route_loose
The first hop contains ;lr or does not exist
route_strict
The first hop exists and does not contain ;lr
route_invalidated
strict/loose routing needs to be rechecked
Definition at line 36 of file route.h.
                     {
    route_loose = 0,    /*!< The first hop contains ;lr or does not exist */
    route_strict,       /*!< The first hop exists and does not contain ;lr */
    route_invalidated,  /*!< strict/loose routing needs to be rechecked */
 };
Function Documentation
sip_route_add()
const char* sip_route_add (struct sip_route * route, const char * uri, size_t len, int inserthead)
Add a new hop to the route.
Parameters
route Route
uri Address of this hop
len Length of hop not including null terminator
inserthead If true then inserted the new route to the top of the list
Return values
Pointer to null terminated copy of URI on success
NULL on error
Definition at line 47 of file route.c.
References ast_copy_string(), AST_LIST_INSERT_HEAD, AST_LIST_INSERT_TAIL, ast_malloc, sip_route_hop::list, sip_route::list, sip_route_hop::next, NULL, route_invalidated, sip_route_empty, sip_route::type, and sip_route_hop::uri.
Referenced by build_route(), sip_route_copy(), and sip_route_process_header().
 {
    struct sip_route_hop *hop;
    if (!uri || len < 1 || uri[0] == '\0') {
       return NULL;
    }
    /* Expand len to include null terminator */
    len++;
    /* ast_calloc is not needed because all fields are initialized in this block */
    hop = ast_malloc(sizeof(struct sip_route_hop) + len);
    if (!hop) {
       return NULL;
    }
    ast_copy_string(hop->uri, uri, len);
    if (inserthead) {
       AST_LIST_INSERT_HEAD(&route->list, hop, list);
       route->type = route_invalidated;
    } else {
       if (sip_route_empty(route)) {
          route->type = route_invalidated;
       }
       AST_LIST_INSERT_TAIL(&route->list, hop, list);
       hop->list.next = NULL;
    }
    return hop->uri;
 }
sip_route_clear()
void sip_route_clear (struct sip_route * route)
Free all routes in the list.
Definition at line 132 of file route.c.
References ast_free, AST_LIST_REMOVE_HEAD, sip_route_hop::list, sip_route::list, route_loose, and sip_route::type.
Referenced by build_path(), build_route(), sip_destroy_peer(), sip_pvt_dtor(), and sip_route_copy().
 {
    struct sip_route_hop *hop;
    while ((hop = AST_LIST_REMOVE_HEAD(&route->list, list))) {
       ast_free(hop);
    }
    route->type = route_loose;
 }
sip_route_copy()
void sip_route_copy (struct sip_route * dst, const struct sip_route * src)
copy route-set
Return values
non-zero on failure
0 on success
Definition at line 115 of file route.c.
References ast_debug, sip_route_add(), sip_route_clear(), sip_route_traverse, sip_route::type, and sip_route_hop::uri.
Referenced by create_addr_from_peer(), and sip_poke_peer().
 {
    struct sip_route_hop *hop;
    /* make sure dst is empty */
    sip_route_clear(dst);
    sip_route_traverse(src, hop) {
       const char *uri = sip_route_add(dst, hop->uri, strlen(hop->uri), 0);
       if (uri) {
          ast_debug(2, "sip_route_copy: copied hop: <%s>\n", uri);
       }
    }
    dst->type = src->type;
 }
sip_route_dump()
void sip_route_dump (const struct sip_route * route)
Verbose dump of all hops for debugging.
Definition at line 143 of file route.c.
References ast_verbose(), sip_route_empty, sip_route_traverse, and sip_route_hop::uri.
Referenced by build_path(), and build_route().
 {
    if (sip_route_empty(route)) {
       ast_verbose("sip_route_dump: no route/path\n");
    } else {
       struct sip_route_hop *hop;
       sip_route_traverse(route, hop) {
          ast_verbose("sip_route_dump: route/path hop: <%s>\n", hop->uri);
       }
    }
 }
sip_route_first_uri()
const char* sip_route_first_uri (const struct sip_route * route)
Get the URI of the route's first hop.
Definition at line 199 of file route.c.
References NULL, sip_route_first, and sip_route_hop::uri.
Referenced by build_route(), create_addr_from_peer(), reqprep(), and sip_poke_peer().
 {
    struct sip_route_hop *hop = sip_route_first(route);
    return hop ? hop->uri : NULL;
 }
sip_route_is_strict()
int sip_route_is_strict (struct sip_route * route)
Check if the route is strict.
Note
The result is cached in route->type
Definition at line 183 of file route.c.
References NULL, route_invalidated, route_loose, route_strict, sip_route_first, sip_route::type, and sip_route_hop::uri.
Referenced by build_path(), build_route(), and reqprep().
 {
    if (!route) {
       return 0;
    }
    if (route->type == route_invalidated) {
       struct sip_route_hop *hop = sip_route_first(route);
       int ret = hop && (strstr(hop->uri, ";lr") == NULL);
       route->type = ret ? route_strict : route_loose;
       return ret;
    }
    return (route->type == route_strict) ? 1 : 0;
 }
sip_route_list()
struct ast_str* sip_route_list (const struct sip_route * route, int formatcli, int skip)
Make the comma separated list of route hops.
Parameters
route Source of route list
formatcli Add's space after comma's, print's N/A if list is empty.
skip Number of hops to skip
Return values
an allocated struct ast_str on success
NULL on failure
Definition at line 155 of file route.c.
References ast_str_append(), ast_str_create, buf, NULL, sip_route_traverse, and sip_route_hop::uri.
Referenced by _sip_show_peer(), add_route(), parse_register_contact(), sip_show_channel(), and update_peer().
 {
    struct sip_route_hop *hop;
    const char *comma;
    struct ast_str *buf;
    int i = 0 - skip;
    buf = ast_str_create(64);
    if (!buf) {
       return NULL;
    }
    comma = formatcli ? ", " : ",";
    sip_route_traverse(route, hop) {
       if (i >= 0) {
          ast_str_append(&buf, 0, "%s<%s>", i ? comma : "", hop->uri);
       }
       i++;
    }
    if (formatcli && i <= 0) {
       ast_str_append(&buf, 0, "N/A");
    }
    return buf;
 }
sip_route_process_header()
void sip_route_process_header (struct sip_route * route, const char * header, int inserthead)
Add routes from header.
Note
This procedure is for headers that require use of <brackets>.
Definition at line 79 of file route.c.
References ast_debug, ast_do_crash(), ast_log, get_in_brackets_const(), len(), LOG_ERROR, NULL, sip_route_add(), and sip_route_hop::uri.
Referenced by build_path(), and build_route().
 {
    const char *hop;
    int len = 0;
    const char *uri;
    if (!route) {
       ast_log(LOG_ERROR, "sip_route_process_header requires non-null route");
       ast_do_crash();
       return;
    }
    while (!get_in_brackets_const(header, &uri, &len)) {
       header = strchr(header, ',');
       if (header >= uri && header <= (uri + len)) {
          /* comma inside brackets */
          const char *next_br = strchr(header, '<');
          if (next_br && next_br <= (uri + len)) {
             header++;
             continue;
          }
          continue;
       }
       if ((hop = sip_route_add(route, uri, len, inserthead))) {
          ast_debug(2, "sip_route_process_header: <%s>\n", hop);
       }
       header = strchr(uri + len + 1, ',');
       if (header == NULL) {
          /* No more field-values, we're done with this header */
          break;
       }
       /* Advance past comma */
       header++;
    }
 }