Asterisk - The Open Source Telephony Project: cel_custom.c File Reference
cel_custom.c File Reference
Custom Comma Separated Value CEL records.
#include "asterisk.h"
#include "asterisk/paths.h"
#include "asterisk/channel.h"
#include "asterisk/cel.h"
#include "asterisk/module.h"
#include "asterisk/config.h"
#include "asterisk/pbx.h"
#include "asterisk/utils.h"
#include "asterisk/lock.h"
#include "asterisk/threadstorage.h"
#include "asterisk/strings.h"
Data Structures
struct cel_config
A container that holds all config-related information.
struct sinks
Macros
#define CONFIG "cel_custom.conf"
#define CUSTOM_BACKEND_NAME "CEL Custom CSV Logging"
#define CUSTOM_LOG_DIR "/cel_custom"
Functions
static void __init_custom_buf (void)
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static void custom_log (struct ast_event *event)
static void free_config (void)
static int load_config (void)
static enum ast_module_load_result load_module (void)
static int reload (void)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Customizable Comma Separated Values CEL Backend" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .reload = reload, .load_pri = AST_MODPRI_CDR_DRIVER, .requires = "cel", }
static const struct ast_module_info * ast_module_info = &__mod_info
static struct ast_threadstorage custom_buf = { .once = PTHREAD_ONCE_INIT , .key_init = __init_custom_buf , .custom_init = NULL , }
static const char name [] = "cel-custom"
static struct sinks sinks = { .first = NULL, .last = NULL, .lock = { PTHREAD_RWLOCK_INITIALIZER , NULL, {1, 0} } , }
Detailed Description
Custom Comma Separated Value CEL records.
Author
Steve Murphy murf@.nosp@m.digi.nosp@m.um.co.nosp@m.m
See also AstCEL
Logs in LOG_DIR/cel_custom
Definition in file cel_custom.c.
Macro Definition Documentation
CONFIG
#define CONFIG "cel_custom.conf"
Definition at line 50 of file cel_custom.c.
Referenced by load_config().
CUSTOM_BACKEND_NAME
#define CUSTOM_BACKEND_NAME "CEL Custom CSV Logging"
Definition at line 65 of file cel_custom.c.
Referenced by load_module(), and unload_module().
CUSTOM_LOG_DIR
#define CUSTOM_LOG_DIR "/cel_custom"
Definition at line 49 of file cel_custom.c.
Function Documentation
__init_custom_buf()
static void __init_custom_buf (void) static
Definition at line 52 of file cel_custom.c.
 {
__reg_module()
static void __reg_module (void) static
Definition at line 227 of file cel_custom.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 227 of file cel_custom.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 227 of file cel_custom.c.
custom_log()
static void custom_log (struct ast_event * event) static
Definition at line 127 of file cel_custom.c.
References ast_cel_fabricate_channel_from_event(), ast_channel_unref, AST_LIST_TRAVERSE, ast_log, ast_mutex_lock, ast_mutex_unlock, AST_RWLIST_RDLOCK, AST_RWLIST_UNLOCK, ast_str_buffer(), ast_str_substitute_variables(), ast_str_thread_get(), config, custom_buf, dummy(), errno, cel_config::filename, cel_config::format, cel_config::lock, LOG_ERROR, out, and str.
Referenced by load_module().
 {
    struct ast_channel *dummy;
    struct ast_str *str;
    struct cel_config *config;
    /* Batching saves memory management here.  Otherwise, it's the same as doing an allocation and free each time. */
    if (!(str = ast_str_thread_get(&custom_buf, 16))) {
       return;
    }
    dummy = ast_cel_fabricate_channel_from_event(event);
    if (!dummy) {
       ast_log(LOG_ERROR, "Unable to fabricate channel from CEL event.\n");
       return;
    }
    AST_RWLIST_RDLOCK(&sinks);
    AST_LIST_TRAVERSE(&sinks, config, list) {
       FILE *out;
       ast_str_substitute_variables(&str, 0, dummy, config->format);
       /* Even though we have a lock on the list, we could be being chased by
          another thread and this lock ensures that we won't step on anyone's
          toes.  Once each CEL backend gets it's own thread, this lock can be
          removed. */
       ast_mutex_lock(&config->lock);
       /* Because of the absolutely unconditional need for the
          highest reliability possible in writing billing records,
          we open write and close the log file each time */
       if ((out = fopen(config->filename, "a"))) {
          fputs(ast_str_buffer(str), out);
          fflush(out); /* be particularly anal here */
          fclose(out);
       } else {
          ast_log(LOG_ERROR, "Unable to re-open master file %s : %s\n", config->filename, strerror(errno));
       }
       ast_mutex_unlock(&config->lock);
    }
    AST_RWLIST_UNLOCK(&sinks);
    ast_channel_unref(dummy);
 }
free_config()
static void free_config (void) static
Definition at line 69 of file cel_custom.c.
References ast_free, ast_mutex_destroy, AST_RWLIST_REMOVE_HEAD, ast_string_field_free_memory, and cel_config::lock.
Referenced by load_module(), reload(), and unload_module().
 {
    struct cel_config *sink;
    while ((sink = AST_RWLIST_REMOVE_HEAD(&sinks, list))) {
       ast_mutex_destroy(&sink->lock);
       ast_string_field_free_memory(sink);
       ast_free(sink);
    }
 }
load_config()
static int load_config (void) static
Definition at line 80 of file cel_custom.c.
References ast_calloc_with_stringfields, ast_config_AST_LOG_DIR, ast_config_destroy(), ast_config_load, ast_log, ast_mutex_init, AST_RWLIST_INSERT_TAIL, ast_string_field_build, ast_strlen_zero, ast_variable_browse(), ast_verb, CONFIG, CONFIG_STATUS_FILEINVALID, cel_config::filename, cel_config::format, ast_variable::lineno, cel_config::lock, LOG_ERROR, LOG_NOTICE, name, ast_variable::name, ast_variable::next, ast_variable::value, and var.
Referenced by load_module(), and reload().
 {
    struct ast_config *cfg;
    struct ast_variable *var;
    struct ast_flags config_flags = { 0 };
    int mappings = 0;
    int res = 0;
    cfg = ast_config_load(CONFIG, config_flags);
    if (!cfg || cfg == CONFIG_STATUS_FILEINVALID) {
       ast_log(LOG_ERROR, "Unable to load " CONFIG ". Not logging CEL to custom CSVs.\n");
       return -1;
    }
    if (!(var = ast_variable_browse(cfg, "mappings"))) {
       ast_log(LOG_NOTICE, "No mappings found in " CONFIG ". Not logging CEL to custom CSVs.\n");
    }
    while (var) {
       if (!ast_strlen_zero(var->name) && !ast_strlen_zero(var->value)) {
          struct cel_config *sink = ast_calloc_with_stringfields(1, struct cel_config, 1024);
          if (!sink) {
             ast_log(LOG_ERROR, "Unable to allocate memory for configuration settings.\n");
             res = -2;
             break;
          }
          ast_string_field_build(sink, format, "%s\n", var->value);
          ast_string_field_build(sink, filename, "%s/%s/%s", ast_config_AST_LOG_DIR, name, var->name);
          ast_mutex_init(&sink->lock);
          ast_verb(3, "Added CEL CSV mapping for '%s'.\n", sink->filename);
          mappings += 1;
          AST_RWLIST_INSERT_TAIL(&sinks, sink, list);
       } else {
          ast_log(LOG_NOTICE, "Mapping must have both a filename and a format at line %d\n", var->lineno);
       }
       var = var->next;
    }
    ast_config_destroy(cfg);
    ast_verb(1, "Added CEL CSV mapping for %d files.\n", mappings);
    return res;
 }
load_module()
static enum ast_module_load_result load_module (void) static
Definition at line 190 of file cel_custom.c.
References ast_cel_backend_register(), ast_log, AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, AST_RWLIST_UNLOCK, AST_RWLIST_WRLOCK, CUSTOM_BACKEND_NAME, custom_log(), free_config(), load_config(), and LOG_ERROR.
Referenced by reload().
 {
    if (AST_RWLIST_WRLOCK(&sinks)) {
       ast_log(LOG_ERROR, "Unable to lock sink list.  Load failed.\n");
       return AST_MODULE_LOAD_DECLINE;
    }
    load_config();
    AST_RWLIST_UNLOCK(&sinks);
    if (ast_cel_backend_register(CUSTOM_BACKEND_NAME, custom_log)) {
       free_config();
       return AST_MODULE_LOAD_DECLINE;
    }
    return AST_MODULE_LOAD_SUCCESS;
 }
reload()
static int reload (void) static
Definition at line 207 of file cel_custom.c.
References ast_log, AST_MODFLAG_LOAD_ORDER, AST_MODPRI_CDR_DRIVER, AST_MODULE_INFO(), AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, AST_MODULE_SUPPORT_CORE, AST_RWLIST_UNLOCK, AST_RWLIST_WRLOCK, ASTERISK_GPL_KEY, free_config(), load_config(), load_module(), LOG_ERROR, and unload_module().
 {
    if (AST_RWLIST_WRLOCK(&sinks)) {
       ast_log(LOG_ERROR, "Unable to lock sink list.  Load failed.\n");
       return AST_MODULE_LOAD_DECLINE;
    }
    free_config();
    load_config();
    AST_RWLIST_UNLOCK(&sinks);
    return AST_MODULE_LOAD_SUCCESS;
 }
unload_module()
static int unload_module (void) static
Definition at line 176 of file cel_custom.c.
References ast_cel_backend_unregister(), ast_log, AST_RWLIST_UNLOCK, AST_RWLIST_WRLOCK, CUSTOM_BACKEND_NAME, free_config(), and LOG_ERROR.
Referenced by reload().
 {
    if (AST_RWLIST_WRLOCK(&sinks)) {
       ast_log(LOG_ERROR, "Unable to lock sink list.  Unload failed.\n");
       return -1;
    }
    free_config();
    AST_RWLIST_UNLOCK(&sinks);
    ast_cel_backend_unregister(CUSTOM_BACKEND_NAME);
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Customizable Comma Separated Values CEL Backend" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .reload = reload, .load_pri = AST_MODPRI_CDR_DRIVER, .requires = "cel", } static
Definition at line 227 of file cel_custom.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 227 of file cel_custom.c.
custom_buf
struct ast_threadstorage custom_buf = { .once = PTHREAD_ONCE_INIT , .key_init = __init_custom_buf , .custom_init = NULL , } static
Definition at line 52 of file cel_custom.c.
Referenced by custom_log().
name
const char name[] = "cel-custom" static
Definition at line 54 of file cel_custom.c.
Referenced by load_config().
sinks
struct sinks sinks = { .first = NULL, .last = NULL, .lock = { PTHREAD_RWLOCK_INITIALIZER , NULL, {1, 0} } , } static