Asterisk - The Open Source Telephony Project: bridge_channel.h File Reference
bridge_channel.h File Reference
#include "asterisk/bridge_features.h"
#include "asterisk/bridge_technology.h"
Data Structures
struct ast_bridge_channel
Structure that contains information regarding a channel in a bridge.
Macros
#define ast_bridge_channel_lock(bridge_channel) _ast_bridge_channel_lock(bridge_channel, __FILE__, __PRETTY_FUNCTION__, __LINE__, #bridge_channel)
Lock the bridge_channel.
#define ast_bridge_channel_trylock(bridge_channel) _ast_bridge_channel_trylock(bridge_channel, __FILE__, __PRETTY_FUNCTION__, __LINE__, #bridge_channel)
Try locking the bridge_channel.
#define ast_bridge_channel_unlock(bridge_channel) _ast_bridge_channel_unlock(bridge_channel, __FILE__, __PRETTY_FUNCTION__, __LINE__, #bridge_channel)
Unlock the bridge_channel.
Typedefs
typedef void(* ast_bridge_custom_callback_fn) (struct ast_bridge_channel *bridge_channel, const void *payload, size_t payload_size)
Custom callback run on a bridge channel.
typedef void(* ast_bridge_custom_play_fn) (struct ast_bridge_channel *bridge_channel, const char *playfile)
Custom interpretation of the playfile name.
Enumerations
enum ast_bridge_channel_custom_callback_option { AST_BRIDGE_CHANNEL_CB_OPTION_MEDIA = (1 << 0) }
enum bridge_channel_state { BRIDGE_CHANNEL_STATE_WAIT = 0, BRIDGE_CHANNEL_STATE_END, BRIDGE_CHANNEL_STATE_END_NO_DISSOLVE }
State information about a bridged channel.
enum bridge_channel_thread_state { BRIDGE_CHANNEL_THREAD_IDLE, BRIDGE_CHANNEL_THREAD_SIMPLE, BRIDGE_CHANNEL_THREAD_FRAME }
Functions
static void _ast_bridge_channel_lock (struct ast_bridge_channel *bridge_channel, const char *file, const char *function, int line, const char *var)
static int _ast_bridge_channel_trylock (struct ast_bridge_channel *bridge_channel, const char *file, const char *function, int line, const char *var)
static void _ast_bridge_channel_unlock (struct ast_bridge_channel *bridge_channel, const char *file, const char *function, int line, const char *var)
void ast_bridge_channel_feature_digit (struct ast_bridge_channel *bridge_channel, int digit)
Add a DTMF digit to the collected digits to match against DTMF features.
void ast_bridge_channel_feature_digit_add (struct ast_bridge_channel *bridge_channel, int digit)
Add a DTMF digit to the collected digits.
struct ast_channel * ast_bridge_channel_get_chan (struct ast_bridge_channel *bridge_channel)
Get a ref to the bridge_channel's ast_channel.
void ast_bridge_channel_kick (struct ast_bridge_channel *bridge_channel, int cause)
Kick the channel out of the bridge.
void ast_bridge_channel_leave_bridge (struct ast_bridge_channel *bridge_channel, enum bridge_channel_state new_state, int cause)
Set bridge channel state to leave bridge (if not leaving already).
void ast_bridge_channel_leave_bridge_nolock (struct ast_bridge_channel *bridge_channel, enum bridge_channel_state new_state, int cause)
Set bridge channel state to leave bridge (if not leaving already).
void ast_bridge_channel_lock_bridge (struct ast_bridge_channel *bridge_channel)
Lock the bridge associated with the bridge channel.
struct ast_bridge * ast_bridge_channel_merge_inhibit (struct ast_bridge_channel *bridge_channel, int request)
Adjust the bridge_channel's bridge merge inhibit request count.
int ast_bridge_channel_notify_talking (struct ast_bridge_channel *bridge_channel, int started_talking)
Lets the bridging indicate when a bridge channel has stopped or started talking.
struct ast_bridge_channel * ast_bridge_channel_peer (struct ast_bridge_channel *bridge_channel)
Get the peer bridge channel of a two party bridge.
void ast_bridge_channel_playfile (struct ast_bridge_channel *bridge_channel, ast_bridge_custom_play_fn custom_play, const char *playfile, const char *moh_class)
Play a file on the bridge channel.
int ast_bridge_channel_queue_app (struct ast_bridge_channel *bridge_channel, const char *app_name, const char *app_args, const char *moh_class)
Queue a bridge action run application frame onto the bridge channel.
int ast_bridge_channel_queue_callback (struct ast_bridge_channel *bridge_channel, enum ast_bridge_channel_custom_callback_option flags, ast_bridge_custom_callback_fn callback, const void *payload, size_t payload_size)
Queue a bridge action custom callback frame onto the bridge channel.
int ast_bridge_channel_queue_control_data (struct ast_bridge_channel *bridge_channel, enum ast_control_frame_type control, const void *data, size_t datalen)
Queue a control frame onto the bridge channel with data.
int ast_bridge_channel_queue_frame (struct ast_bridge_channel *bridge_channel, struct ast_frame *fr)
Write a frame to the specified bridge_channel.
int ast_bridge_channel_queue_playfile (struct ast_bridge_channel *bridge_channel, ast_bridge_custom_play_fn custom_play, const char *playfile, const char *moh_class)
Queue a bridge action play file frame onto the bridge channel.
int ast_bridge_channel_queue_playfile_sync (struct ast_bridge_channel *bridge_channel, ast_bridge_custom_play_fn custom_play, const char *playfile, const char *moh_class)
Synchronously queue a bridge action play file frame onto the bridge channel.
void ast_bridge_channel_restore_formats (struct ast_bridge_channel *bridge_channel)
Restore the formats of a bridge channel's channel to how they were before bridge_channel_internal_join.
void ast_bridge_channel_run_app (struct ast_bridge_channel *bridge_channel, const char *app_name, const char *app_args, const char *moh_class)
Run an application on the bridge channel.
void ast_bridge_channel_stream_map (struct ast_bridge_channel *bridge_channel)
Maps a channel's stream topology to and from the bridge.
void ast_bridge_channel_update_accountcodes (struct ast_bridge_channel *joining, struct ast_bridge_channel *leaving)
void ast_bridge_channel_update_linkedids (struct ast_bridge_channel *bridge_channel, struct ast_bridge_channel *swap)
int ast_bridge_channel_write_app (struct ast_bridge_channel *bridge_channel, const char *app_name, const char *app_args, const char *moh_class)
Write a bridge action run application frame into the bridge.
int ast_bridge_channel_write_callback (struct ast_bridge_channel *bridge_channel, enum ast_bridge_channel_custom_callback_option flags, ast_bridge_custom_callback_fn callback, const void *payload, size_t payload_size)
Write a bridge action custom callback frame into the bridge.
int ast_bridge_channel_write_control_data (struct ast_bridge_channel *bridge_channel, enum ast_control_frame_type control, const void *data, size_t datalen)
Write a control frame into the bridge with data.
int ast_bridge_channel_write_hold (struct ast_bridge_channel *bridge_channel, const char *moh_class)
Write a hold frame into the bridge.
int ast_bridge_channel_write_park (struct ast_bridge_channel *bridge_channel, const char *parkee_uuid, const char *parker_uuid, const char *app_data)
Have a bridge channel park a channel in the bridge.
int ast_bridge_channel_write_playfile (struct ast_bridge_channel *bridge_channel, ast_bridge_custom_play_fn custom_play, const char *playfile, const char *moh_class)
Write a bridge action play file frame into the bridge.
int ast_bridge_channel_write_unhold (struct ast_bridge_channel *bridge_channel)
Write an unhold frame into the bridge.
Macro Definition Documentation
ast_bridge_channel_lock
#define ast_bridge_channel_lock (bridge_channel) _ast_bridge_channel_lock(bridge_channel, __FILE__, __PRETTY_FUNCTION__, __LINE__, #bridge_channel)
Lock the bridge_channel.
Parameters
bridge_channel What to lock
Returns
Nothing
Definition at line 231 of file bridge_channel.h.
Referenced by agent_bridge_channel_get_lock(), ast_bridge_channel_kick(), ast_bridge_channel_leave_bridge(), ast_bridge_channel_lock_bridge(), ast_bridge_channel_queue_frame(), ast_bridge_channel_stream_map(), bridge_channel_attended_transfer(), bridge_channel_change_bridge(), bridge_channel_handle_write(), bridge_channel_internal_unsuspend_nolock(), bridge_channel_queue_deferred_frames(), bridge_channel_wait(), bridge_channel_write_frame(), bridge_do_merge(), bridge_parking_push(), map_source_to_destinations(), remove_hooks_on_personality_change(), and softmix_bridge_stream_topology_changed().
ast_bridge_channel_trylock
#define ast_bridge_channel_trylock (bridge_channel) _ast_bridge_channel_trylock(bridge_channel, __FILE__, __PRETTY_FUNCTION__, __LINE__, #bridge_channel)
Try locking the bridge_channel.
Parameters
bridge_channel What to try locking
Return values
0 on success.
non-zero on error.
Definition at line 218 of file bridge_channel.h.
Referenced by optimize_lock_chan_stack(), and optimize_lock_peer_stack().
ast_bridge_channel_unlock
#define ast_bridge_channel_unlock (bridge_channel) _ast_bridge_channel_unlock(bridge_channel, __FILE__, __PRETTY_FUNCTION__, __LINE__, #bridge_channel)
Unlock the bridge_channel.
Parameters
bridge_channel What to unlock
Returns
Nothing
Definition at line 244 of file bridge_channel.h.
Referenced by agent_bridge_channel_get_lock(), agent_request_exec(), ast_bridge_channel_kick(), ast_bridge_channel_leave_bridge(), ast_bridge_channel_lock_bridge(), ast_bridge_channel_queue_frame(), ast_bridge_channel_stream_map(), ast_bridge_unreal_optimize_out(), bridge_channel_attended_transfer(), bridge_channel_change_bridge(), bridge_channel_handle_write(), bridge_channel_internal_unsuspend_nolock(), bridge_channel_queue_deferred_frames(), bridge_channel_wait(), bridge_channel_write_frame(), bridge_do_merge(), bridge_parking_push(), caller_abort_agent(), caller_joined_bridge(), map_source_to_destinations(), optimize_lock_chan_stack(), optimize_lock_peer_stack(), remove_hooks_on_personality_change(), and softmix_bridge_stream_topology_changed().
Typedef Documentation
ast_bridge_custom_callback_fn
typedef void(* ast_bridge_custom_callback_fn) (struct ast_bridge_channel *bridge_channel, const void *payload, size_t payload_size)
Custom callback run on a bridge channel.
Parameters
bridge_channel Which channel to operate on.
payload Data to pass to the callback. (NULL if none).
payload_size Size of the payload if payload is non-NULL. A number otherwise.
Note
The payload MUST NOT have any resources that need to be freed.
Returns
Nothing
Definition at line 612 of file bridge_channel.h.
ast_bridge_custom_play_fn
typedef void(* ast_bridge_custom_play_fn) (struct ast_bridge_channel *bridge_channel, const char *playfile)
Custom interpretation of the playfile name.
Parameters
bridge_channel Which channel to play the file on
playfile Sound filename to play.
Returns
Nothing
Definition at line 524 of file bridge_channel.h.
Enumeration Type Documentation
ast_bridge_channel_custom_callback_option
enum ast_bridge_channel_custom_callback_option
Enumerator
AST_BRIDGE_CHANNEL_CB_OPTION_MEDIA
The callback temporarily affects media. (Like a custom playfile.)
Definition at line 614 of file bridge_channel.h.
{
    /*! The callback temporarily affects media. (Like a custom playfile.) */
    AST_BRIDGE_CHANNEL_CB_OPTION_MEDIA = (1 << 0),
 };
bridge_channel_state
enum bridge_channel_state
State information about a bridged channel.
Enumerator
BRIDGE_CHANNEL_STATE_WAIT
Waiting for a signal (Channel in the bridge)
BRIDGE_CHANNEL_STATE_END
Bridged channel was forced out and should be hung up (Bridge may dissolve.)
BRIDGE_CHANNEL_STATE_END_NO_DISSOLVE
Bridged channel was forced out. Don't dissolve the bridge regardless
Definition at line 60 of file bridge_channel.h.
{
    /*! Waiting for a signal (Channel in the bridge) */
    BRIDGE_CHANNEL_STATE_WAIT = 0,
    /*! Bridged channel was forced out and should be hung up (Bridge may dissolve.) */
    BRIDGE_CHANNEL_STATE_END,
    /*! Bridged channel was forced out. Don't dissolve the bridge regardless */
    BRIDGE_CHANNEL_STATE_END_NO_DISSOLVE,
 };
bridge_channel_thread_state
enum bridge_channel_thread_state
Enumerator
BRIDGE_CHANNEL_THREAD_IDLE
Bridge channel thread is idle/waiting.
BRIDGE_CHANNEL_THREAD_SIMPLE
Bridge channel thread is writing a normal/simple frame.
BRIDGE_CHANNEL_THREAD_FRAME
Bridge channel thread is processing a frame.
Definition at line 69 of file bridge_channel.h.
{
    /*! Bridge channel thread is idle/waiting. */
    BRIDGE_CHANNEL_THREAD_IDLE,
    /*! Bridge channel thread is writing a normal/simple frame. */
    BRIDGE_CHANNEL_THREAD_SIMPLE,
    /*! Bridge channel thread is processing a frame. */
    BRIDGE_CHANNEL_THREAD_FRAME,
 };
Function Documentation
_ast_bridge_channel_lock()
static void _ast_bridge_channel_lock (struct ast_bridge_channel * bridge_channel, const char * file, const char * function, int line, const char * var) inline static
Definition at line 232 of file bridge_channel.h.
References __ao2_lock(), and AO2_LOCK_REQ_MUTEX.
 {
    __ao2_lock(bridge_channel, AO2_LOCK_REQ_MUTEX, file, function, line, var);
 }
_ast_bridge_channel_trylock()
static int _ast_bridge_channel_trylock (struct ast_bridge_channel * bridge_channel, const char * file, const char * function, int line, const char * var) inline static
Definition at line 219 of file bridge_channel.h.
References __ao2_trylock(), and AO2_LOCK_REQ_MUTEX.
 {
    return __ao2_trylock(bridge_channel, AO2_LOCK_REQ_MUTEX, file, function, line, var);
 }
_ast_bridge_channel_unlock()
static void _ast_bridge_channel_unlock (struct ast_bridge_channel * bridge_channel, const char * file, const char * function, int line, const char * var) inline static
Definition at line 245 of file bridge_channel.h.
References __ao2_unlock(), app_name(), ast_bridge_channel_leave_bridge(), ast_bridge_channel_leave_bridge_nolock(), ast_bridge_channel_lock_bridge(), ast_bridge_channel_merge_inhibit(), ast_bridge_channel_notify_talking(), ast_bridge_channel_peer(), ast_bridge_channel_queue_app(), ast_bridge_channel_queue_control_data(), ast_bridge_channel_queue_frame(), ast_bridge_channel_restore_formats(), ast_bridge_channel_run_app(), ast_bridge_channel_update_accountcodes(), ast_bridge_channel_update_linkedids(), ast_bridge_channel_write_app(), ast_bridge_channel_write_control_data(), ast_bridge_channel_write_hold(), ast_bridge_channel_write_unhold(), request(), and ast_bridge_channel::swap.
 {
    __ao2_unlock(bridge_channel, file, function, line, var);
 }
ast_bridge_channel_feature_digit()
void ast_bridge_channel_feature_digit (struct ast_bridge_channel * bridge_channel, int digit)
Add a DTMF digit to the collected digits to match against DTMF features.
Since
12.8.0
Parameters
bridge_channel Channel that received a DTMF digit.
digit DTMF digit to add to collected digits or 0 for timeout event.
clear_digits clear the digits array prior to calling hooks
Note
Neither the bridge nor the bridge_channel locks should be held when entering this function.
This is intended to be called by bridge hooks and the bridge channel thread.
This is intended to be called by non-DTMF bridge hooks and the bridge channel thread. Calling from a DTMF bridge hook can potentially cause unbounded recursion.
Returns
Nothing
Definition at line 1762 of file bridge_channel.c.
References ao2_find, ao2_ref, ao2_unlink, ARRAY_LEN, ast_bridge_channel_kick(), ast_bridge_channel_lock_bridge(), ast_bridge_unlock, ast_channel_name(), ast_check_hangup_locked(), AST_CONTROL_SRCUPDATE, ast_debug, ast_indicate(), ast_samp2tv(), ast_test_suite_event_notify, ast_tvadd(), ast_tvnow(), ast_bridge_channel::bridge, bridge_channel_feature_digit_add(), bridge_channel_feature_digit_timeout(), bridge_channel_internal_suspend_nolock(), bridge_channel_unsuspend(), bridge_channel_write_dtmf_stream(), ast_bridge_hook::callback, ast_bridge_channel::chan, ast_bridge_hook_dtmf_parms::code, ast_bridge_channel::collected, ast_bridge_hook_dtmf::dtmf, ast_bridge_channel::dtmf_hook_state, ast_bridge_features::dtmf_hooks, ast_bridge_features::dtmf_passthrough, ast_bridge_channel::features, ast_bridge_hook_dtmf::generic, ast_bridge_hook::hook_pvt, ast_bridge_channel::interdigit_timeout, NULL, OBJ_SEARCH_PARTIAL_KEY, ast_bridge_channel::suspended, and testsuite_notify_feature_success().
Referenced by agent_alert(), bridge_channel_handle_feature_timeout(), bridge_channel_internal_join(), and bridge_handle_dtmf().
 {
    struct ast_bridge_features *features = bridge_channel->features;
    struct ast_bridge_hook_dtmf *hook = NULL;
    size_t dtmf_len;
    struct sanity_check_of_dtmf_size {
       char check[1 / (ARRAY_LEN(bridge_channel->dtmf_hook_state.collected) == ARRAY_LEN(hook->dtmf.code))];
    };
    dtmf_len = strlen(bridge_channel->dtmf_hook_state.collected);
    if (!dtmf_len && !digit) {
       /* Nothing to do */
       return;
    }
    if (digit) {
       dtmf_len = bridge_channel_feature_digit_add(bridge_channel, digit, dtmf_len);
    }
    while (digit) {
       /* See if a DTMF feature hook matches or can match */
       hook = ao2_find(features->dtmf_hooks, bridge_channel->dtmf_hook_state.collected,
          OBJ_SEARCH_PARTIAL_KEY);
       if (!hook) {
          ast_debug(1, "No DTMF feature hooks on %p(%s) match '%s'\n",
             bridge_channel, ast_channel_name(bridge_channel->chan),
             bridge_channel->dtmf_hook_state.collected);
          break;
       } else if (dtmf_len != strlen(hook->dtmf.code)) {
          unsigned int digit_timeout;
          /* Need more digits to match */
          ao2_ref(hook, -1);
          digit_timeout = bridge_channel_feature_digit_timeout(bridge_channel);
          bridge_channel->dtmf_hook_state.interdigit_timeout =
             ast_tvadd(ast_tvnow(), ast_samp2tv(digit_timeout, 1000));
          return;
       } else {
          int remove_me;
          int already_suspended;
          ast_debug(1, "DTMF feature hook %p matched DTMF string '%s' on %p(%s)\n",
             hook, bridge_channel->dtmf_hook_state.collected, bridge_channel,
             ast_channel_name(bridge_channel->chan));
          /*
           * Clear the collected digits before executing the hook
           * in case the hook starts another sequence.
           */
          bridge_channel->dtmf_hook_state.collected[0] = '\0';
          ast_bridge_channel_lock_bridge(bridge_channel);
          already_suspended = bridge_channel->suspended;
          if (!already_suspended) {
             bridge_channel_internal_suspend_nolock(bridge_channel);
          }
          ast_bridge_unlock(bridge_channel->bridge);
          ast_indicate(bridge_channel->chan, AST_CONTROL_SRCUPDATE);
          /* Execute the matched hook on this channel. */
          remove_me = hook->generic.callback(bridge_channel, hook->generic.hook_pvt);
          if (remove_me) {
             ast_debug(1, "DTMF hook %p is being removed from %p(%s)\n",
                hook, bridge_channel, ast_channel_name(bridge_channel->chan));
             ao2_unlink(features->dtmf_hooks, hook);
          }
          testsuite_notify_feature_success(bridge_channel->chan, hook->dtmf.code);
          ao2_ref(hook, -1);
          ast_indicate(bridge_channel->chan, AST_CONTROL_SRCUPDATE);
          if (!already_suspended) {
             bridge_channel_unsuspend(bridge_channel);
          }
          /*
           * If we are handing the channel off to an external hook for
           * ownership, we are not guaranteed what kind of state it will
           * come back in.  If the channel hungup, we need to detect that
           * here if the hook did not already change the state.
           */
          if (bridge_channel->chan && ast_check_hangup_locked(bridge_channel->chan)) {
             ast_bridge_channel_kick(bridge_channel, 0);
             bridge_channel->dtmf_hook_state.collected[0] = '\0';
             return;
          }
          /* if there is dtmf that has been collected then loop back through,
             but set digit to -1 so it doesn't try to do an add since the dtmf
             is already in the buffer */
          dtmf_len = strlen(bridge_channel->dtmf_hook_state.collected);
          if (!dtmf_len) {
             return;
          }
       }
    }
    if (!digit) {
       ast_debug(1, "DTMF feature string collection on %p(%s) timed out\n",
          bridge_channel, ast_channel_name(bridge_channel->chan));
    }
    /* Timeout or DTMF digit didn't allow a match with any hooks. */
    if (features->dtmf_passthrough) {
       /* Stream the collected DTMF to the other channels. */
       bridge_channel_write_dtmf_stream(bridge_channel,
          bridge_channel->dtmf_hook_state.collected);
    }
    bridge_channel->dtmf_hook_state.collected[0] = '\0';
    ast_test_suite_event_notify("FEATURE_DETECTION", "Result: fail");
 }
ast_bridge_channel_feature_digit_add()
void ast_bridge_channel_feature_digit_add (struct ast_bridge_channel * bridge_channel, int digit)
Add a DTMF digit to the collected digits.
Since
13.3.0
Parameters
bridge_channel Channel that received a DTMF digit.
digit DTMF digit to add to collected digits
Note
Neither the bridge nor the bridge_channel locks should be held when entering this function.
This is can only be called from within DTMF bridge hooks.
Definition at line 1754 of file bridge_channel.c.
References bridge_channel_feature_digit_add(), ast_bridge_channel::collected, and ast_bridge_channel::dtmf_hook_state.
Referenced by play_file().
 {
    if (digit) {
       bridge_channel_feature_digit_add(
          bridge_channel, digit, strlen(bridge_channel->dtmf_hook_state.collected));
    }
 }
ast_bridge_channel_get_chan()
struct ast_channel* ast_bridge_channel_get_chan (struct ast_bridge_channel * bridge_channel)
Get a ref to the bridge_channel's ast_channel.
Parameters
bridge_channel The bridge channel
Note
The returned channel NEEDS to be unref'd once you are done with it. In general, this function is best used when accessing the bridge_channel chan from outside of a bridging thread.
Return values
ref'd ast_channel on success
NULL otherwise
Definition at line 211 of file bridge_channel.c.
References ao2_bump, ao2_lock, ao2_unlock, and ast_bridge_channel::chan.
Referenced by ast_bridge_channel_write_unhold().
 {
    struct ast_channel *chan;
    ao2_lock(bridge_channel);
    chan = ao2_bump(bridge_channel->chan);
    ao2_unlock(bridge_channel);
    return chan;
 }
ast_bridge_channel_kick()
void ast_bridge_channel_kick (struct ast_bridge_channel * bridge_channel, int cause)
Kick the channel out of the bridge.
Since
12.0.0
Parameters
bridge_channel Which channel is being kicked or hungup.
cause Cause of channel being kicked. If cause <= 0 then use cause on channel if cause still <= 0 use AST_CAUSE_NORMAL_CLEARING.
Note
This is intended to be called by bridge hooks and the bridge channel thread.
Returns
Nothing
Definition at line 605 of file bridge_channel.c.
References ao2_iterator_destroy(), ao2_iterator_init(), ao2_iterator_next, ao2_ref, ao2_unlink, ast_bridge_channel_leave_bridge(), ast_bridge_channel_lock, ast_bridge_channel_unlock, AST_BRIDGE_HOOK_TYPE_HANGUP, ast_channel_name(), ast_debug, BRIDGE_CHANNEL_STATE_END, BRIDGE_CHANNEL_STATE_WAIT, ast_bridge_hook::callback, ast_bridge_channel::chan, channel_set_cause(), ast_bridge_channel::features, ast_bridge_hook::hook_pvt, ast_bridge_features::other_hooks, ast_bridge_channel::state, and ast_bridge_hook::type.
Referenced by ast_bridge_channel_feature_digit(), ast_bridge_channel_run_app(), bridge_channel_attended_transfer(), bridge_channel_blind_transfer(), bridge_channel_handle_action(), bridge_channel_internal_join(), bridge_handle_trip(), and kick_it().
 {
    struct ast_bridge_features *features = bridge_channel->features;
    struct ast_bridge_hook *hook;
    struct ao2_iterator iter;
    ast_bridge_channel_lock(bridge_channel);
    if (bridge_channel->state == BRIDGE_CHANNEL_STATE_WAIT) {
       channel_set_cause(bridge_channel->chan, cause);
       cause = 0;
    }
    ast_bridge_channel_unlock(bridge_channel);
    /* Run any hangup hooks. */
    iter = ao2_iterator_init(features->other_hooks, 0);
    for (; (hook = ao2_iterator_next(&iter)); ao2_ref(hook, -1)) {
       int remove_me;
       if (hook->type != AST_BRIDGE_HOOK_TYPE_HANGUP) {
          continue;
       }
       remove_me = hook->callback(bridge_channel, hook->hook_pvt);
       if (remove_me) {
          ast_debug(1, "Hangup hook %p is being removed from %p(%s)\n",
             hook, bridge_channel, ast_channel_name(bridge_channel->chan));
          ao2_unlink(features->other_hooks, hook);
       }
    }
    ao2_iterator_destroy(&iter);
    /* Default hangup action. */
    ast_bridge_channel_leave_bridge(bridge_channel, BRIDGE_CHANNEL_STATE_END, cause);
 }
ast_bridge_channel_leave_bridge()
void ast_bridge_channel_leave_bridge (struct ast_bridge_channel * bridge_channel, enum bridge_channel_state new_state, int cause)
Set bridge channel state to leave bridge (if not leaving already).
Parameters
bridge_channel Channel to change the state on
new_state The new state to place the channel into
cause Cause of channel leaving bridge. If cause <= 0 then use cause on channel if cause still <= 0 use AST_CAUSE_NORMAL_CLEARING.
Example usage:
ast_bridge_channel_leave_bridge(bridge_channel, BRIDGE_CHANNEL_STATE_END, AST_CAUSE_NORMAL_CLEARING);
This places the channel pointed to by bridge_channel into the state BRIDGE_CHANNEL_STATE_END if it was BRIDGE_CHANNEL_STATE_WAIT before.
Definition at line 314 of file bridge_channel.c.
References ast_bridge_channel_leave_bridge_nolock(), ast_bridge_channel_lock, and ast_bridge_channel_unlock.
Referenced by _ast_bridge_channel_unlock(), agent_connect_caller(), ast_bridge_channel_kick(), ast_bridge_depart(), ast_bridge_remove(), basic_hangup_hook(), bridge_agent_hold_heartbeat(), bridge_agent_hold_push(), bridge_channel_complete_join(), bridge_channel_dissolve_check(), bridge_channel_internal_push_full(), bridge_dissolve(), bridge_do_merge(), bridge_do_move(), bridge_features_duration_callback(), bridge_swap_attended_transfer(), bridgewait_timeout_callback(), caller_joined_bridge(), caller_safety_timeout(), feature_hangup(), parking_duration_callback(), say_parking_space(), set_softmix_bridge_data(), try_swap_optimize_out(), and user_timeout().
 {
    ast_bridge_channel_lock(bridge_channel);
    ast_bridge_channel_leave_bridge_nolock(bridge_channel, new_state, cause);
    ast_bridge_channel_unlock(bridge_channel);
 }
ast_bridge_channel_leave_bridge_nolock()
void ast_bridge_channel_leave_bridge_nolock (struct ast_bridge_channel * bridge_channel, enum bridge_channel_state new_state, int cause)
Set bridge channel state to leave bridge (if not leaving already).
Parameters
bridge_channel Channel to change the state on
new_state The new state to place the channel into
cause Cause of channel leaving bridge. If cause <= 0 then use cause on channel if cause still <= 0 use AST_CAUSE_NORMAL_CLEARING.
Example usage:
ast_bridge_channel_leave_bridge(bridge_channel, BRIDGE_CHANNEL_STATE_END, AST_CAUSE_NORMAL_CLEARING);
This places the channel pointed to by bridge_channel into the state BRIDGE_CHANNEL_STATE_END if it was BRIDGE_CHANNEL_STATE_WAIT before.
Definition at line 292 of file bridge_channel.c.
References ast_bridge_vars_set(), ast_channel_lock, ast_channel_name(), ast_channel_unlock, ast_debug, bridge_channel_poke(), BRIDGE_CHANNEL_STATE_WAIT, ast_bridge_channel::chan, channel_set_cause(), NULL, and ast_bridge_channel::state.
Referenced by _ast_bridge_channel_unlock(), ast_bridge_channel_leave_bridge(), bridge_do_merge(), and caller_abort_agent().
 {
    if (bridge_channel->state != BRIDGE_CHANNEL_STATE_WAIT) {
       return;
    }
    ast_debug(1, "Setting %p(%s) state from:%u to:%u\n",
       bridge_channel, ast_channel_name(bridge_channel->chan), bridge_channel->state,
       new_state);
    channel_set_cause(bridge_channel->chan, cause);
    ast_channel_lock(bridge_channel->chan);
    ast_bridge_vars_set(bridge_channel->chan, NULL, NULL);
    ast_channel_unlock(bridge_channel->chan);
    /* Change the state on the bridge channel */
    bridge_channel->state = new_state;
    bridge_channel_poke(bridge_channel);
 }
ast_bridge_channel_lock_bridge()
void ast_bridge_channel_lock_bridge (struct ast_bridge_channel * bridge_channel)
Lock the bridge associated with the bridge channel.
Since
12.0.0
Parameters
bridge_channel Channel that wants to lock the bridge.
This is an upstream lock operation. The defined locking order is bridge then bridge_channel.
Note
On entry, neither the bridge nor bridge_channel is locked.
The bridge_channel->bridge pointer changes because of a bridge-merge/channel-move operation between bridges.
Returns
Nothing
Definition at line 222 of file bridge_channel.c.
References ao2_ref, ast_bridge_channel_lock, ast_bridge_channel_unlock, ast_bridge_lock, ast_bridge_unlock, and ast_bridge_channel::bridge.
Referenced by _ast_bridge_channel_unlock(), action_toggle_binaural(), agent_alert(), ast_bridge_channel_feature_digit(), ast_bridge_channel_merge_inhibit(), ast_bridge_notify_masquerade(), basic_hangup_hook(), bridge_channel_handle_control(), bridge_channel_internal_join(), bridge_channel_suspend(), bridge_channel_unsuspend(), bridge_channel_wait(), bridge_channel_write_frame(), bridge_handle_trip(), check_binaural_position_change(), deferred_action(), feature_automixmonitor(), feature_automonitor(), and parking_blind_transfer_park().
 {
    struct ast_bridge *bridge;
    for (;;) {
       /* Safely get the bridge pointer */
       ast_bridge_channel_lock(bridge_channel);
       bridge = bridge_channel->bridge;
       ao2_ref(bridge, +1);
       ast_bridge_channel_unlock(bridge_channel);
       /* Lock the bridge and see if it is still the bridge we need to lock. */
       ast_bridge_lock(bridge);
       if (bridge == bridge_channel->bridge) {
          ao2_ref(bridge, -1);
          return;
       }
       ast_bridge_unlock(bridge);
       ao2_ref(bridge, -1);
    }
 }
ast_bridge_channel_merge_inhibit()
struct ast_bridge* ast_bridge_channel_merge_inhibit (struct ast_bridge_channel * bridge_channel, int request)
Adjust the bridge_channel's bridge merge inhibit request count.
Since
12.0.0
Parameters
bridge_channel What to operate on.
request Inhibit request increment. (Positive to add requests. Negative to remove requests.)
Note
This API call is meant for internal bridging operations.
Return values
bridge adjusted merge inhibit with reference count.
Definition at line 369 of file bridge_channel.c.
References ao2_ref, ast_bridge_channel_lock_bridge(), ast_bridge_unlock, ast_bridge_channel::bridge, and bridge_merge_inhibit_nolock().
Referenced by _ast_bridge_channel_unlock(), and feature_attended_transfer().
 {
    struct ast_bridge *bridge;
    ast_bridge_channel_lock_bridge(bridge_channel);
    bridge = bridge_channel->bridge;
    ao2_ref(bridge, +1);
    bridge_merge_inhibit_nolock(bridge, request);
    ast_bridge_unlock(bridge);
    return bridge;
 }
ast_bridge_channel_notify_talking()
int ast_bridge_channel_notify_talking (struct ast_bridge_channel * bridge_channel, int started_talking)
Lets the bridging indicate when a bridge channel has stopped or started talking.
Note
All DSP functionality on the bridge has been pushed down to the lowest possible layer, which in this case is the specific bridging technology being used. Since it is necessary for the knowledge of which channels are talking to make its way up to the application, this function has been created to allow the bridging technology to communicate that information with the bridging core.
Parameters
bridge_channel The bridge channel that has either started or stopped talking.
started_talking set to 1 when this indicates the channel has started talking set to 0 when this indicates the channel has stopped talking.
Return values
0 on success.
-1 on error.
Definition at line 244 of file bridge_channel.c.
References ast_bridge_channel_queue_frame(), AST_FRAME_BRIDGE_ACTION, BRIDGE_CHANNEL_ACTION_TALKING_START, BRIDGE_CHANNEL_ACTION_TALKING_STOP, and ast_frame::frametype.
Referenced by _ast_bridge_channel_unlock(), clear_talking(), and softmix_bridge_write_voice().
 {
    struct ast_frame action = {
       .frametype = AST_FRAME_BRIDGE_ACTION,
       .subclass.integer = started_talking
          ? BRIDGE_CHANNEL_ACTION_TALKING_START : BRIDGE_CHANNEL_ACTION_TALKING_STOP,
    };
    return ast_bridge_channel_queue_frame(bridge_channel, &action);
 }
ast_bridge_channel_peer()
struct ast_bridge_channel* ast_bridge_channel_peer (struct ast_bridge_channel * bridge_channel)
Get the peer bridge channel of a two party bridge.
Since
12.0.0
Parameters
bridge_channel What to get the peer of.
Note
On entry, bridge_channel->bridge is already locked.
This is an internal bridge function.
Return values
peer on success.
NULL no peer channel.
Definition at line 321 of file bridge_channel.c.
References AST_LIST_TRAVERSE, ast_bridge_channel::bridge, ast_bridge::channels, ast_bridge_channel::in_bridge, NULL, and ast_bridge::num_channels.
Referenced by _ast_bridge_channel_unlock(), bridge_reconfigured_connected_line_update(), bridge_swap_attended_transfer(), parking_blind_transfer_park(), and try_swap_optimize_out().
 {
    struct ast_bridge *bridge = bridge_channel->bridge;
    struct ast_bridge_channel *other = NULL;
    if (bridge_channel->in_bridge && bridge->num_channels == 2) {
       AST_LIST_TRAVERSE(&bridge->channels, other, entry) {
          if (other != bridge_channel) {
             break;
          }
       }
    }
    return other;
 }
ast_bridge_channel_playfile()
void ast_bridge_channel_playfile (struct ast_bridge_channel * bridge_channel, ast_bridge_custom_play_fn custom_play, const char * playfile, const char * moh_class)
Play a file on the bridge channel.
Since
12.0.0
Parameters
bridge_channel Which channel to play the file on
custom_play Call this function to play the playfile. (NULL if normal sound file to play)
playfile Sound filename to play.
moh_class MOH class to request bridge peers to hear while file is played. NULL if no MOH. Empty if default MOH class.
Note
This is intended to be called by bridge hooks.
Returns
Nothing
Definition at line 1321 of file bridge_channel.c.
References ast_bridge_channel_write_hold(), ast_bridge_channel_write_unhold(), ast_channel_flags(), ast_channel_latest_musicclass(), ast_channel_lock, ast_channel_unlock, AST_DIGIT_NONE, AST_FLAG_MOH, ast_moh_start(), ast_strdupa, ast_stream_and_wait(), ast_test_flag, ast_bridge_channel::chan, and NULL.
Referenced by bridge_channel_playfile().
 {
    if (moh_class) {
       ast_bridge_channel_write_hold(bridge_channel, moh_class);
    }
    if (custom_play) {
       custom_play(bridge_channel, playfile);
    } else {
       ast_stream_and_wait(bridge_channel->chan, playfile, AST_DIGIT_NONE);
    }
    if (moh_class) {
       ast_bridge_channel_write_unhold(bridge_channel);
    }
    /*
     * It may be necessary to resume music on hold after we finish
     * playing the announcment.
     */
    if (ast_test_flag(ast_channel_flags(bridge_channel->chan), AST_FLAG_MOH)) {
       const char *latest_musicclass;
       ast_channel_lock(bridge_channel->chan);
       latest_musicclass = ast_strdupa(ast_channel_latest_musicclass(bridge_channel->chan));
       ast_channel_unlock(bridge_channel->chan);
       ast_moh_start(bridge_channel->chan, latest_musicclass, NULL);
    }
 }
ast_bridge_channel_queue_app()
int ast_bridge_channel_queue_app (struct ast_bridge_channel * bridge_channel, const char * app_name, const char * app_args, const char * moh_class)
Queue a bridge action run application frame onto the bridge channel.
Since
12.0.0
Parameters
bridge_channel Which channel to put the frame onto
app_name Dialplan application name.
app_args Arguments for the application. (NULL or empty for no arguments)
moh_class MOH class to request bridge peers to hear while application is running. NULL if no MOH. Empty if default MOH class.
Note
This is intended to be called by bridge hooks.
Return values
0 on success.
-1 on error.
Definition at line 1315 of file bridge_channel.c.
References bridge_channel_queue_action_data(), and payload_helper_app().
Referenced by _ast_bridge_channel_unlock().
 {
    return payload_helper_app(bridge_channel_queue_action_data,
       bridge_channel, app_name, app_args, moh_class);
 }
ast_bridge_channel_queue_callback()
int ast_bridge_channel_queue_callback (struct ast_bridge_channel * bridge_channel, enum ast_bridge_channel_custom_callback_option flags, ast_bridge_custom_callback_fn callback, const void * payload, size_t payload_size)
Queue a bridge action custom callback frame onto the bridge channel.
Since
12.0.0
Parameters
bridge_channel Which channel to put the frame onto.
flags Custom callback option flags.
callback Custom callback run on a bridge channel.
payload Data to pass to the callback. (NULL if none).
payload_size Size of the payload if payload is non-NULL. A number otherwise.
Note
The payload MUST NOT have any resources that need to be freed.
This is intended to be called by bridge hooks.
Return values
0 on success.
-1 on error.
Definition at line 1492 of file bridge_channel.c.
References bridge_channel_queue_action_data(), and payload_helper_cb().
Referenced by ast_bridge_kick(), defer_action(), handle_bridge_kick_channel(), and send_alert_to_agent().
 {
    return payload_helper_cb(bridge_channel_queue_action_data,
       bridge_channel, flags, callback, payload, payload_size);
 }
ast_bridge_channel_queue_control_data()
int ast_bridge_channel_queue_control_data (struct ast_bridge_channel * bridge_channel, enum ast_control_frame_type control, const void * data, size_t datalen)
Queue a control frame onto the bridge channel with data.
Since
12.0.0
Parameters
bridge_channel Which channel to queue the frame onto.
control Type of control frame.
data Frame payload data to pass.
datalen Frame payload data length to pass.
Return values
0 on success.
-1 on error.
Definition at line 1143 of file bridge_channel.c.
References ast_bridge_channel_queue_frame(), AST_FRAME_CONTROL, ast_frame::datalen, and ast_frame::frametype.
Referenced by _ast_bridge_channel_unlock(), bridge_reconfigured_connected_line_update(), and send_colp_to_agent().
 {
    struct ast_frame frame = {
       .frametype = AST_FRAME_CONTROL,
       .subclass.integer = control,
       .datalen = datalen,
       .data.ptr = (void *) data,
    };
    return ast_bridge_channel_queue_frame(bridge_channel, &frame);
 }
ast_bridge_channel_queue_frame()
int ast_bridge_channel_queue_frame (struct ast_bridge_channel * bridge_channel, struct ast_frame * fr)
Write a frame to the specified bridge_channel.
Since
12.0.0
Parameters
bridge_channel Channel to queue the frame.
fr Frame to write.
Return values
0 on success.
-1 on error.
Definition at line 1044 of file bridge_channel.c.
References ast_bridge_channel::alert_pipe, ast_alertpipe_write(), ast_bridge_channel_lock, ast_bridge_channel_unlock, ast_channel_name(), AST_FRAME_DTMF_BEGIN, AST_FRAME_DTMF_END, AST_FRAME_IMAGE, AST_FRAME_NULL, AST_FRAME_RTCP, AST_FRAME_TEXT, AST_FRAME_TEXT_DATA, AST_FRAME_VIDEO, AST_FRAME_VOICE, ast_frdup, ast_is_deferrable_frame(), AST_LIST_INSERT_TAIL, ast_log, AST_MSG_DATA_ATTR_BODY, AST_MSG_DATA_ATTR_FROM, AST_MSG_DATA_ATTR_TO, ast_msg_data_get_attribute(), AST_VECTOR_GET, AST_VECTOR_SIZE, BRIDGE_CHANNEL_STATE_WAIT, bridge_frame_free(), ast_bridge_channel::chan, ast_frame::data, ast_frame::datalen, DEBUG_ATLEAST, ast_bridge_channel::features, ast_frame::frametype, LOG_DEBUG, LOG_ERROR, ast_frame::ptr, ast_bridge_channel::state, ast_bridge_channel::stream_map, ast_frame::stream_num, ast_bridge_channel::suspended, ast_bridge_features::text_messaging, ast_bridge_channel::to_channel, and ast_bridge_channel::wr_queue.
Referenced by _ast_bridge_channel_unlock(), ast_bridge_channel_notify_talking(), ast_bridge_channel_queue_control_data(), ast_bridge_queue_everyone_else(), bridge_channel_queue_action_data(), bridge_channel_queue_action_data_sync(), remb_send_report(), send_message(), softmix_mixing_loop(), and softmix_pass_video_top_priority().
 {
    struct ast_frame *dup;
    if (bridge_channel->suspended
       /* Also defer DTMF frames. */
       && fr->frametype != AST_FRAME_DTMF_BEGIN
       && fr->frametype != AST_FRAME_DTMF_END
       && !ast_is_deferrable_frame(fr)) {
       /* Drop non-deferable frames when suspended. */
       return 0;
    }
    if (fr->frametype == AST_FRAME_NULL) {
       /* "Accept" the frame and discard it. */
       return 0;
    }
    if ((fr->frametype == AST_FRAME_VOICE || fr->frametype == AST_FRAME_VIDEO ||
       fr->frametype == AST_FRAME_TEXT || fr->frametype == AST_FRAME_IMAGE ||
       fr->frametype == AST_FRAME_RTCP) && fr->stream_num > -1) {
       int num = -1;
       ast_bridge_channel_lock(bridge_channel);
       if (fr->stream_num < (int)AST_VECTOR_SIZE(&bridge_channel->stream_map.to_channel)) {
          num = AST_VECTOR_GET(&bridge_channel->stream_map.to_channel, fr->stream_num);
       }
       ast_bridge_channel_unlock(bridge_channel);
       if (num == -1) {
          /* We don't have a mapped stream so just discard this frame. */
          return 0;
       }
    }
    dup = ast_frdup(fr);
    if (!dup) {
       return -1;
    }
    ast_bridge_channel_lock(bridge_channel);
    if (bridge_channel->state != BRIDGE_CHANNEL_STATE_WAIT) {
       /* Drop frames on channels leaving the bridge. */
       ast_bridge_channel_unlock(bridge_channel);
       bridge_frame_free(dup);
       return 0;
    }
    if ((fr->frametype == AST_FRAME_TEXT || fr->frametype == AST_FRAME_TEXT_DATA) &&
       !bridge_channel->features->text_messaging) {
       /* This channel is not accepting text messages. */
       ast_bridge_channel_unlock(bridge_channel);
       bridge_frame_free(dup);
       return 0;
    }
    if (DEBUG_ATLEAST(1)) {
       if (fr->frametype == AST_FRAME_TEXT) {
          ast_log(LOG_DEBUG, "Queuing TEXT frame to '%s': %*.s\n", ast_channel_name(bridge_channel->chan),
             fr->datalen, (char *)fr->data.ptr);
       } else if (fr->frametype == AST_FRAME_TEXT_DATA) {
          struct ast_msg_data *msg = fr->data.ptr;
          ast_log(LOG_DEBUG, "Queueing TEXT_DATA frame from '%s' to '%s:%s': %s\n",
             ast_msg_data_get_attribute(msg, AST_MSG_DATA_ATTR_FROM),
             ast_msg_data_get_attribute(msg, AST_MSG_DATA_ATTR_TO),
             ast_channel_name(bridge_channel->chan),
             ast_msg_data_get_attribute(msg, AST_MSG_DATA_ATTR_BODY));
       }
    }
    AST_LIST_INSERT_TAIL(&bridge_channel->wr_queue, dup, frame_list);
    if (ast_alertpipe_write(bridge_channel->alert_pipe)) {
       ast_log(LOG_ERROR, "We couldn't write alert pipe for %p(%s)... something is VERY wrong\n",
          bridge_channel, ast_channel_name(bridge_channel->chan));
    }
    ast_bridge_channel_unlock(bridge_channel);
    return 0;
 }
ast_bridge_channel_queue_playfile()
int ast_bridge_channel_queue_playfile (struct ast_bridge_channel * bridge_channel, ast_bridge_custom_play_fn custom_play, const char * playfile, const char * moh_class)
Queue a bridge action play file frame onto the bridge channel.
Since
12.0.0
Parameters
bridge_channel Which channel to put the frame onto.
custom_play Call this function to play the playfile. (NULL if normal sound file to play)
playfile Sound filename to play.
moh_class MOH class to request bridge peers to hear while file is played. NULL if no MOH. Empty if default MOH class.
Note
This is intended to be called by bridge hooks.
Return values
0 on success.
-1 on error.
Definition at line 1404 of file bridge_channel.c.
References bridge_channel_queue_action_data(), and payload_helper_playfile().
Referenced by ast_bridge_add_channel(), bridge_parking_pull(), bridge_parking_push(), check_bridge_play_sound(), feature_automixmonitor(), feature_automonitor(), parker_parked_call_message_response(), play_sound(), start_automixmonitor(), start_automonitor(), stop_automixmonitor(), and stop_automonitor().
 {
    return payload_helper_playfile(bridge_channel_queue_action_data,
       bridge_channel, custom_play, playfile, moh_class);
 }
ast_bridge_channel_queue_playfile_sync()
int ast_bridge_channel_queue_playfile_sync (struct ast_bridge_channel * bridge_channel, ast_bridge_custom_play_fn custom_play, const char * playfile, const char * moh_class)
Synchronously queue a bridge action play file frame onto the bridge channel.
Since
12.2.0
Parameters
bridge_channel Which channel to put the frame onto.
custom_play Call this function to play the playfile. (NULL if normal sound file to play)
playfile Sound filename to play.
moh_class MOH class to request bridge peers to hear while file is played. NULL if no MOH. Empty if default MOH class.
This function will block until the queued frame has been destroyed. This will happen either if an error occurs or if the queued playback finishes.
Note
No locks may be held when calling this function.
Return values
0 The playback was successfully queued.
-1 The playback could not be queued.
Definition at line 1410 of file bridge_channel.c.
References bridge_channel_queue_action_data_sync(), and payload_helper_playfile().
Referenced by parker_parked_call_message_response(), and play_uri().
 {
    return payload_helper_playfile(bridge_channel_queue_action_data_sync,
       bridge_channel, custom_play, playfile, moh_class);
 }
ast_bridge_channel_restore_formats()
void ast_bridge_channel_restore_formats (struct ast_bridge_channel * bridge_channel)
Restore the formats of a bridge channel's channel to how they were before bridge_channel_internal_join.
Since
12.0.0
Parameters
bridge_channel Channel to restore
Definition at line 337 of file bridge_channel.c.
References ast_assert, ast_channel_lock, ast_channel_name(), ast_channel_readformat(), ast_channel_unlock, ast_channel_writeformat(), ast_debug, ast_format_cmp(), AST_FORMAT_CMP_NOT_EQUAL, ast_format_get_name(), ast_set_read_format(), ast_set_write_format(), ast_bridge_channel::chan, NULL, ast_bridge_channel::read_format, and ast_bridge_channel::write_format.
Referenced by _ast_bridge_channel_unlock(), bridge_channel_internal_join(), and participant_reaction_announcer_leave().
 {
    ast_assert(bridge_channel->read_format != NULL);
    ast_assert(bridge_channel->write_format != NULL);
    ast_channel_lock(bridge_channel->chan);
    /* Restore original formats of the channel as they came in */
    if (ast_format_cmp(ast_channel_readformat(bridge_channel->chan), bridge_channel->read_format) == AST_FORMAT_CMP_NOT_EQUAL) {
       ast_debug(1, "Bridge is returning %p(%s) to read format %s\n",
          bridge_channel, ast_channel_name(bridge_channel->chan),
          ast_format_get_name(bridge_channel->read_format));
       if (ast_set_read_format(bridge_channel->chan, bridge_channel->read_format)) {
          ast_debug(1, "Bridge failed to return %p(%s) to read format %s\n",
             bridge_channel, ast_channel_name(bridge_channel->chan),
             ast_format_get_name(bridge_channel->read_format));
       }
    }
    if (ast_format_cmp(ast_channel_writeformat(bridge_channel->chan), bridge_channel->write_format) == AST_FORMAT_CMP_NOT_EQUAL) {
       ast_debug(1, "Bridge is returning %p(%s) to write format %s\n",
          bridge_channel, ast_channel_name(bridge_channel->chan),
          ast_format_get_name(bridge_channel->write_format));
       if (ast_set_write_format(bridge_channel->chan, bridge_channel->write_format)) {
          ast_debug(1, "Bridge failed to return %p(%s) to write format %s\n",
             bridge_channel, ast_channel_name(bridge_channel->chan),
             ast_format_get_name(bridge_channel->write_format));
       }
    }
    ast_channel_unlock(bridge_channel->chan);
 }
ast_bridge_channel_run_app()
void ast_bridge_channel_run_app (struct ast_bridge_channel * bridge_channel, const char * app_name, const char * app_args, const char * moh_class)
Run an application on the bridge channel.
Since
12.0.0
Parameters
bridge_channel Which channel to run the application on.
app_name Dialplan application name.
app_args Arguments for the application. (NULL tolerant)
moh_class MOH class to request bridge peers to hear while application is running. NULL if no MOH. Empty if default MOH class.
Note
This is intended to be called by bridge hooks.
Returns
Nothing
Definition at line 1241 of file bridge_channel.c.
References ast_bridge_channel_kick(), ast_bridge_channel_write_hold(), ast_bridge_channel_write_unhold(), AST_CAUSE_NORMAL_CLEARING, ast_bridge_channel::chan, run_app_helper(), and S_OR.
Referenced by _ast_bridge_channel_unlock(), bridge_channel_run_app(), and dynamic_dtmf_hook_callback().
 {
    if (moh_class) {
       ast_bridge_channel_write_hold(bridge_channel, moh_class);
    }
    if (run_app_helper(bridge_channel->chan, app_name, S_OR(app_args, ""))) {
       /* Break the bridge if the app returns non-zero. */
       ast_bridge_channel_kick(bridge_channel, AST_CAUSE_NORMAL_CLEARING);
    }
    if (moh_class) {
       ast_bridge_channel_write_unhold(bridge_channel);
    }
 }
ast_bridge_channel_stream_map()
void ast_bridge_channel_stream_map (struct ast_bridge_channel * bridge_channel)
Maps a channel's stream topology to and from the bridge.
Since
15.0.0
When a channel joins a bridge or its associated stream topology is updated, each stream in the topology needs to be mapped according to its media type to the bridge. Calling this method creates a mapping of each stream on the channel indexed to the bridge's supported media types and vice versa (i.e. bridge's media types indexed to channel streams).
The first channel to join the bridge creates the initial order for the bridge's media types (e.g. a one to one mapping is made). Subsequently added channels are mapped to that order adding more media types if/when the newly added channel has more streams and/or media types specified by the bridge.
Parameters
bridge_channel Channel to map
Note
The bridge_channel's bridge must be locked prior to calling this function.
Returns
Nothing
Definition at line 3174 of file bridge_channel.c.
References ast_bridge_channel_lock, ast_bridge_channel_unlock, ast_channel_get_stream_topology(), ast_channel_lock, ast_channel_unlock, ast_stream_topology_map(), ast_bridge_channel::bridge, ast_bridge_channel::chan, ast_bridge::media_types, ast_bridge_channel::stream_map, ast_bridge_channel::to_bridge, and ast_bridge_channel::to_channel.
Referenced by bridge_channel_complete_join(), bridge_handle_trip(), native_rtp_stream_topology_changed(), simple_bridge_stream_topology_changed(), and softmix_bridge_stream_topology_changed().
 {
    ast_bridge_channel_lock(bridge_channel);
    ast_channel_lock(bridge_channel->chan);
    ast_stream_topology_map(ast_channel_get_stream_topology(bridge_channel->chan),
       &bridge_channel->bridge->media_types, &bridge_channel->stream_map.to_bridge,
       &bridge_channel->stream_map.to_channel);
    ast_channel_unlock(bridge_channel->chan);
    ast_bridge_channel_unlock(bridge_channel);
 }
ast_bridge_channel_update_accountcodes()
void ast_bridge_channel_update_accountcodes (struct ast_bridge_channel * joining, struct ast_bridge_channel * leaving)
Definition at line 596 of file bridge_channel.c.
References bridge_channel_update_accountcodes_joining(), and bridge_channel_update_accountcodes_leaving().
Referenced by _ast_bridge_channel_unlock(), bridge_basic_pull(), bridge_basic_push(), bridge_stasis_pull(), and bridge_stasis_push().
 {
    if (joining) {
       bridge_channel_update_accountcodes_joining(joining, leaving);
    } else {
       bridge_channel_update_accountcodes_leaving(leaving);
    }
 }
ast_bridge_channel_update_linkedids()
void ast_bridge_channel_update_linkedids (struct ast_bridge_channel * bridge_channel, struct ast_bridge_channel * swap)
Definition at line 381 of file bridge_channel.c.
References ast_channel_internal_copy_linkedid(), ast_channel_internal_oldest_linkedid(), ast_channel_lock, ast_channel_unlock, AST_LIST_TRAVERSE, ast_bridge_channel::bridge, ast_bridge_channel::chan, and ast_bridge::channels.
Referenced by _ast_bridge_channel_unlock(), bridge_basic_push(), and bridge_stasis_push().
 {
    struct ast_bridge_channel *other;
    struct ast_bridge *bridge = bridge_channel->bridge;
    struct ast_channel *oldest_linkedid_chan = bridge_channel->chan;
    AST_LIST_TRAVERSE(&bridge->channels, other, entry) {
       if (other == swap) {
          continue;
       }
       oldest_linkedid_chan = ast_channel_internal_oldest_linkedid(
          oldest_linkedid_chan, other->chan);
    }
    ast_channel_lock(bridge_channel->chan);
    ast_channel_internal_copy_linkedid(bridge_channel->chan, oldest_linkedid_chan);
    ast_channel_unlock(bridge_channel->chan);
    AST_LIST_TRAVERSE(&bridge->channels, other, entry) {
       if (other == swap) {
          continue;
       }
       ast_channel_lock(other->chan);
       ast_channel_internal_copy_linkedid(other->chan, oldest_linkedid_chan);
       ast_channel_unlock(other->chan);
    }
 }
ast_bridge_channel_write_app()
int ast_bridge_channel_write_app (struct ast_bridge_channel * bridge_channel, const char * app_name, const char * app_args, const char * moh_class)
Write a bridge action run application frame into the bridge.
Since
12.0.0
Parameters
bridge_channel Which channel is putting the frame into the bridge
app_name Dialplan application name.
app_args Arguments for the application. (NULL or empty for no arguments)
moh_class MOH class to request bridge peers to hear while application is running. NULL if no MOH. Empty if default MOH class.
Note
This is intended to be called by bridge hooks.
Return values
0 on success.
-1 on error.
Definition at line 1309 of file bridge_channel.c.
References bridge_channel_write_action_data(), and payload_helper_app().
Referenced by _ast_bridge_channel_unlock().
 {
    return payload_helper_app(bridge_channel_write_action_data,
       bridge_channel, app_name, app_args, moh_class);
 }
ast_bridge_channel_write_callback()
int ast_bridge_channel_write_callback (struct ast_bridge_channel * bridge_channel, enum ast_bridge_channel_custom_callback_option flags, ast_bridge_custom_callback_fn callback, const void * payload, size_t payload_size)
Write a bridge action custom callback frame into the bridge.
Since
12.0.0
Parameters
bridge_channel Which channel is putting the frame into the bridge
flags Custom callback option flags.
callback Custom callback run on a bridge channel.
payload Data to pass to the callback. (NULL if none).
payload_size Size of the payload if payload is non-NULL. A number otherwise.
Note
The payload MUST NOT have any resources that need to be freed.
This is intended to be called by bridge hooks.
Return values
0 on success.
-1 on error.
Definition at line 1484 of file bridge_channel.c.
References bridge_channel_write_action_data(), and payload_helper_cb().
Referenced by agent_connect_caller(), and dynamic_dtmf_hook_trip().
 {
    return payload_helper_cb(bridge_channel_write_action_data,
       bridge_channel, flags, callback, payload, payload_size);
 }
ast_bridge_channel_write_control_data()
int ast_bridge_channel_write_control_data (struct ast_bridge_channel * bridge_channel, enum ast_control_frame_type control, const void * data, size_t datalen)
Write a control frame into the bridge with data.
Since
12.0.0
Parameters
bridge_channel Which channel is putting the frame into the bridge.
control Type of control frame.
data Frame payload data to pass.
datalen Frame payload data length to pass.
Return values
0 on success.
-1 on error.
Definition at line 1155 of file bridge_channel.c.
References AST_FRAME_CONTROL, bridge_channel_write_frame(), ast_frame::datalen, and ast_frame::frametype.
Referenced by _ast_bridge_channel_unlock(), agent_connect_caller(), ast_bridge_channel_write_hold(), ast_bridge_channel_write_unhold(), and ringing().
 {
    struct ast_frame frame = {
       .frametype = AST_FRAME_CONTROL,
       .subclass.integer = control,
       .datalen = datalen,
       .data.ptr = (void *) data,
    };
    return bridge_channel_write_frame(bridge_channel, &frame);
 }
ast_bridge_channel_write_hold()
int ast_bridge_channel_write_hold (struct ast_bridge_channel * bridge_channel, const char * moh_class)
Write a hold frame into the bridge.
Since
12.0.0
Parameters
bridge_channel Which channel is putting the hold into the bridge.
moh_class The suggested music class for the other end to use.
Return values
0 on success.
-1 on error.
Definition at line 1167 of file bridge_channel.c.
References ast_bridge_channel_write_control_data(), ast_channel_hold_type(), ast_channel_publish_cached_blob(), AST_CONTROL_HOLD, ast_json_pack(), ast_json_unref(), ast_strlen_zero, ast_bridge_channel::chan, and NULL.
Referenced by _ast_bridge_channel_unlock(), ast_bridge_channel_playfile(), ast_bridge_channel_run_app(), feature_attended_transfer(), feature_blind_transfer(), and hold().
 {
    struct ast_json *blob;
    int res;
    size_t datalen;
    if (!ast_strlen_zero(moh_class)) {
       datalen = strlen(moh_class) + 1;
       blob = ast_json_pack("{s: s}",
          "musicclass", moh_class);
    } else {
       moh_class = NULL;
       datalen = 0;
       blob = NULL;
    }
    ast_channel_publish_cached_blob(bridge_channel->chan, ast_channel_hold_type(), blob);
    res = ast_bridge_channel_write_control_data(bridge_channel, AST_CONTROL_HOLD,
       moh_class, datalen);
    ast_json_unref(blob);
    return res;
 }
ast_bridge_channel_write_park()
int ast_bridge_channel_write_park (struct ast_bridge_channel * bridge_channel, const char * parkee_uuid, const char * parker_uuid, const char * app_data)
Have a bridge channel park a channel in the bridge.
Since
12.0.0
Parameters
bridge_channel Bridge channel performing the parking
parkee_uuid Unique id of the channel we want to park
parker_uuid Unique id of the channel parking the call
app_data string indicating data used for park application (NULL allowed)
Note
This is intended to be called by bridge hooks.
Return values
0 on success.
-1 on error.
Definition at line 1555 of file bridge_channel.c.
References bridge_channel_write_action_data(), and payload_helper_park().
Referenced by manager_park_bridged(), and parking_blind_transfer_park().
 {
    return payload_helper_park(bridge_channel_write_action_data,
       bridge_channel, parkee_uuid, parker_uuid, app_data);
 }
ast_bridge_channel_write_playfile()
int ast_bridge_channel_write_playfile (struct ast_bridge_channel * bridge_channel, ast_bridge_custom_play_fn custom_play, const char * playfile, const char * moh_class)
Write a bridge action play file frame into the bridge.
Since
12.0.0
Parameters
bridge_channel Which channel is putting the frame into the bridge
custom_play Call this function to play the playfile. (NULL if normal sound file to play)
playfile Sound filename to play.
moh_class MOH class to request bridge peers to hear while file is played. NULL if no MOH. Empty if default MOH class.
Note
This is intended to be called by bridge hooks.
Return values
0 on success.
-1 on error.
Definition at line 1398 of file bridge_channel.c.
References bridge_channel_write_action_data(), and payload_helper_playfile().
Referenced by ast_bridge_transfer_attended(), start_automixmonitor(), start_automonitor(), stop_automixmonitor(), and stop_automonitor().
 {
    return payload_helper_playfile(bridge_channel_write_action_data,
       bridge_channel, custom_play, playfile, moh_class);
 }
ast_bridge_channel_write_unhold()
int ast_bridge_channel_write_unhold (struct ast_bridge_channel * bridge_channel)
Write an unhold frame into the bridge.
Since
12.0.0
Parameters
bridge_channel Which channel is putting the hold into the bridge.
Return values
0 on success.
-1 on error.
Definition at line 1193 of file bridge_channel.c.
References ao2_ref, ast_bridge_channel_get_chan(), ast_bridge_channel_write_control_data(), ast_channel_publish_cached_blob(), ast_channel_unhold_type(), AST_CONTROL_UNHOLD, and NULL.
Referenced by _ast_bridge_channel_unlock(), ast_bridge_channel_playfile(), ast_bridge_channel_run_app(), ast_bridge_transfer_attended(), ast_bridge_transfer_blind(), feature_attended_transfer(), feature_blind_transfer(), and unhold().
 {
    struct ast_channel *chan = ast_bridge_channel_get_chan(bridge_channel);
    if (!chan) {
       return -1;
    }
    ast_channel_publish_cached_blob(chan, ast_channel_unhold_type(), NULL);
    ao2_ref(chan, -1);
    return ast_bridge_channel_write_control_data(bridge_channel, AST_CONTROL_UNHOLD, NULL, 0);
 }