Asterisk - The Open Source Telephony Project: bt_search.c File Reference
bt_search.c File Reference
#include <sys/types.h>
#include <stdio.h>
#include "../include/db.h"
#include "btree.h"
Functions
EPG * __bt_search (BTREE *t, const DBT *key, int *exactp)
static int __bt_snext (BTREE *t, PAGE *h, const DBT *key, int *exactp)
static int __bt_sprev (BTREE *t, PAGE *h, const DBT *key, int *exactp)
static int __bt_snext __P ((BTREE *, PAGE *, const DBT *, int *))
Function Documentation
__bt_search()
EPG* __bt_search (BTREE * t, const DBT * key, int * exactp)
Definition at line 66 of file bt_search.c.
References __bt_cmp(), __bt_snext(), __bt_sprev(), B_NODUPS, BT_CLR, _btree::bt_cur, _btree::bt_mp, BT_PUSH, F_ISSET, _page::flags, GETBINTERNAL, _epg::index, mpool_get(), mpool_put(), NEXTINDEX, _page::nextpg, NULL, P_BLEAF, P_INVALID, P_ROOT, _epg::page, _page::pgno, and _page::prevpg.
Referenced by __bt_bdelete(), __bt_first(), __bt_get(), __bt_put(), and __bt_stkacq().
 {
    PAGE *h;
    indx_t base, index, lim;
    pgno_t pg;
    int cmp;
    BT_CLR(t);
    for (pg = P_ROOT;;) {
       if ((h = mpool_get(t->bt_mp, pg, 0)) == NULL)
          return (NULL);
       /* Do a binary search on the current page. */
       t->bt_cur.page = h;
       for (base = 0, lim = NEXTINDEX(h); lim; lim >>= 1) {
          t->bt_cur.index = index = base + (lim >> 1);
          if ((cmp = __bt_cmp(t, key, &t->bt_cur)) == 0) {
             if (h->flags & P_BLEAF) {
                *exactp = 1;
                return (&t->bt_cur);
             }
             goto next;
          }
          if (cmp > 0) {
             base = index + 1;
             --lim;
          }
       }
       /*
        * If it's a leaf page, we're almost done.  If no duplicates
        * are allowed, or we have an exact match, we're done.  Else,
        * it's possible that there were matching keys on this page,
        * which later deleted, and we're on a page with no matches
        * while there are matches on other pages.  If at the start or
        * end of a page, check the adjacent page.
        */
       if (h->flags & P_BLEAF) {
          if (!F_ISSET(t, B_NODUPS)) {
             if (base == 0 &&
                 h->prevpg != P_INVALID &&
                 __bt_sprev(t, h, key, exactp))
                return (&t->bt_cur);
             if (base == NEXTINDEX(h) &&
                 h->nextpg != P_INVALID &&
                 __bt_snext(t, h, key, exactp))
                return (&t->bt_cur);
          }
          *exactp = 0;
          t->bt_cur.index = base;
          return (&t->bt_cur);
       }
       /*
        * No match found.  Base is the smallest index greater than
        * key and may be zero or a last + 1 index.  If it's non-zero,
        * decrement by one, and record the internal page which should
        * be a parent page for the key.  If a split later occurs, the
        * inserted page will be to the right of the saved page.
        */
       index = base ? base - 1 : base;
 next:    BT_PUSH(t, h->pgno, index);
       pg = GETBINTERNAL(h, index)->pgno;
       mpool_put(t->bt_mp, h, 0);
    }
 }
__bt_snext()
static int __bt_snext (BTREE * t, PAGE * h, const DBT * key, int * exactp) static
Definition at line 151 of file bt_search.c.
References __bt_cmp(), _btree::bt_cur, _btree::bt_mp, _epg::index, mpool_get(), mpool_put(), _page::nextpg, NULL, and _epg::page.
Referenced by __bt_search().
 {
    EPG e;
    /*
     * Get the next page.  The key is either an exact
     * match, or not as good as the one we already have.
     */
    if ((e.page = mpool_get(t->bt_mp, h->nextpg, 0)) == NULL)
       return (0);
    e.index = 0;
    if (__bt_cmp(t, key, &e) == 0) {
       mpool_put(t->bt_mp, h, 0);
       t->bt_cur = e;
       *exactp = 1;
       return (1);
    }
    mpool_put(t->bt_mp, e.page, 0);
    return (0);
 }
__bt_sprev()
static int __bt_sprev (BTREE * t, PAGE * h, const DBT * key, int * exactp) static
Definition at line 190 of file bt_search.c.
References __bt_cmp(), _btree::bt_cur, _btree::bt_mp, _epg::index, mpool_get(), mpool_put(), NEXTINDEX, NULL, _epg::page, and _page::prevpg.
Referenced by __bt_search().
 {
    EPG e;
    /*
     * Get the previous page.  The key is either an exact
     * match, or not as good as the one we already have.
     */
    if ((e.page = mpool_get(t->bt_mp, h->prevpg, 0)) == NULL)
       return (0);
    e.index = NEXTINDEX(e.page) - 1;
    if (__bt_cmp(t, key, &e) == 0) {
       mpool_put(t->bt_mp, h, 0);
       t->bt_cur = e;
       *exactp = 1;
       return (1);
    }
    mpool_put(t->bt_mp, e.page, 0);
    return (0);
 }
__P()
static int __bt_sprev __P ((BTREE *, PAGE *, const DBT *, int *)) static