Asterisk - The Open Source Telephony Project: frame.c File Reference
main/frame.c File Reference
Frame and codec manipulation routines.
#include "asterisk.h"
#include "asterisk/_private.h"
#include "asterisk/lock.h"
#include "asterisk/frame.h"
#include "asterisk/format_cache.h"
#include "asterisk/channel.h"
#include "asterisk/cli.h"
#include "asterisk/term.h"
#include "asterisk/utils.h"
#include "asterisk/threadstorage.h"
#include "asterisk/linkedlists.h"
#include "asterisk/translate.h"
#include "asterisk/dsp.h"
#include "asterisk/file.h"
#include <math.h>
Data Structures
struct ast_frame_cache
struct ast_frames
This is just so ast_frames, a list head struct for holding a list of ast_frame structures, is defined.
Macros
#define FRAME_CACHE_MAX_SIZE 10
Maximum ast_frame cache size.
Functions
struct ast_frame * __ast_frdup (const struct ast_frame *f, const char *file, int line, const char *func)
struct ast_frame * __ast_frisolate (struct ast_frame *fr, const char *file, int line, const char *func)
'isolates' a frame by duplicating non-malloc'ed components (header, src, data). On return all components are malloc'ed
static void __frame_free (struct ast_frame *fr, int cache)
static void __init_frame_cache (void)
A per-thread cache of frame headers.
int ast_frame_adjust_volume (struct ast_frame *f, int adjustment)
Adjusts the volume of the audio samples contained in a frame.
int ast_frame_adjust_volume_float (struct ast_frame *f, float adjustment)
Adjusts the volume of the audio samples contained in a frame.
int ast_frame_clear (struct ast_frame *frame)
Clear all audio samples from an ast_frame. The frame must be AST_FRAME_VOICE and AST_FORMAT_SLINEAR.
void ast_frame_dtor (struct ast_frame *f)
NULL-safe wrapper for ast_frfree, good for RAII_VAR.
void ast_frame_dump (const char *name, struct ast_frame *f, char *prefix)
void ast_frame_free (struct ast_frame *frame, int cache)
Requests a frame to be allocated.
static struct ast_frame * ast_frame_header_new (const char *file, int line, const char *func)
int ast_frame_slinear_sum (struct ast_frame *f1, struct ast_frame *f2)
Sums two frames of audio samples.
char * ast_frame_subclass2str (struct ast_frame *f, char *subclass, size_t slen, char *moreinfo, size_t mlen)
Copy the discription of a frame's subclass into the provided string.
char * ast_frame_type2str (enum ast_frame_type frame_type, char *ftype, size_t len)
Copy the discription of a frame type into the provided string.
void ast_swapcopy_samples (void *dst, const void *src, int samples)
static void frame_cache_cleanup (void *data)
Variables
struct ast_frame ast_null_frame = { AST_FRAME_NULL, }
static struct ast_threadstorage frame_cache = { .once = PTHREAD_ONCE_INIT , .key_init = __init_frame_cache , .custom_init = NULL , }
Detailed Description
Frame and codec manipulation routines.
Author
Mark Spencer marks.nosp@m.ter@.nosp@m.digiu.nosp@m.m.co.nosp@m.m
Definition in file main/frame.c.
Macro Definition Documentation
FRAME_CACHE_MAX_SIZE
#define FRAME_CACHE_MAX_SIZE 10
Maximum ast_frame cache size.
In most cases where the frame header cache will be useful, the size of the cache will stay very small. However, it is not always the case that the same thread that allocates the frame will be the one freeing them, so sometimes a thread will never have any frames in its cache, or the cache will never be pulled from. For the latter case, we limit the maximum size.
Definition at line 67 of file main/frame.c.
Referenced by __frame_free().
Function Documentation
__ast_frdup()
struct ast_frame* __ast_frdup (const struct ast_frame * f, const char * file, int line, const char * func)
Definition at line 305 of file main/frame.c.
References __ast_calloc(), ao2_bump, AST_CONTROL_ANSWER, ast_copy_flags, AST_FLAGS_ALL, AST_FRAME_CONTROL, AST_FRAME_IMAGE, AST_FRAME_TEXT, AST_FRAME_VIDEO, AST_FRAME_VOICE, AST_FRIENDLY_OFFSET, AST_LIST_REMOVE_CURRENT, AST_LIST_TRAVERSE_SAFE_BEGIN, AST_LIST_TRAVERSE_SAFE_END, AST_MALLOCD_HDR, ast_threadstorage_get(), buf, ast_frame::data, ast_frame::datalen, ast_frame::delivery, ast_frame_subclass::format, frame_cache, frames, ast_frame::frametype, ast_frame_subclass::integer, ast_frame::len, len(), ast_frame_cache::list, ast_frame::mallocd, ast_frame::mallocd_hdr_len, NULL, ast_frame::offset, out, ast_frame::ptr, ast_frame::samples, ast_frame::seqno, ast_frame_cache::size, ast_frame::src, ast_frame::stream_num, ast_frame::subclass, ast_frame_subclass::topology, ast_frame::ts, and ast_frame::uint32.
Referenced by __ast_frisolate().
 {
    struct ast_frame *out = NULL;
    int len, srclen = 0;
    void *buf = NULL;
 #if !defined(NO_FRAME_CACHE)
    struct ast_frame_cache *frames;
 #endif
    /* Start with standard stuff */
    len = sizeof(*out) + AST_FRIENDLY_OFFSET + f->datalen;
    /* If we have a source, add space for it */
    /*
     * XXX Watch out here - if we receive a src which is not terminated
     * properly, we can be easily attacked. Should limit the size we deal with.
     */
    if (f->src)
       srclen = strlen(f->src);
    if (srclen > 0)
       len += srclen + 1;
 #if !defined(NO_FRAME_CACHE)
    if ((frames = ast_threadstorage_get(&frame_cache, sizeof(*frames)))) {
       AST_LIST_TRAVERSE_SAFE_BEGIN(&frames->list, out, frame_list) {
          if (out->mallocd_hdr_len >= len) {
             size_t mallocd_len = out->mallocd_hdr_len;
             AST_LIST_REMOVE_CURRENT(frame_list);
             memset(out, 0, sizeof(*out));
             out->mallocd_hdr_len = mallocd_len;
             buf = out;
             frames->size--;
             break;
          }
       }
       AST_LIST_TRAVERSE_SAFE_END;
    }
 #endif
    if (!buf) {
       if (!(buf = __ast_calloc(1, len, file, line, func)))
          return NULL;
       out = buf;
       out->mallocd_hdr_len = len;
    }
    out->frametype = f->frametype;
    out->subclass = f->subclass;
    if ((f->frametype == AST_FRAME_VOICE) || (f->frametype == AST_FRAME_VIDEO) ||
       (f->frametype == AST_FRAME_IMAGE)) {
       ao2_bump(out->subclass.format);
    } else if (f->frametype == AST_FRAME_CONTROL && f->subclass.integer == AST_CONTROL_ANSWER) {
       ao2_bump(out->subclass.topology);
    }
    out->datalen = f->datalen;
    out->samples = f->samples;
    out->delivery = f->delivery;
    /* Even though this new frame was allocated from the heap, we can't mark it
     * with AST_MALLOCD_HDR, AST_MALLOCD_DATA and AST_MALLOCD_SRC, because that
     * would cause ast_frfree() to attempt to individually free each of those
     * under the assumption that they were separately allocated. Since this frame
     * was allocated in a single allocation, we'll only mark it as if the header
     * was heap-allocated; this will result in the entire frame being properly freed.
     */
    out->mallocd = AST_MALLOCD_HDR;
    out->offset = AST_FRIENDLY_OFFSET;
    /* Make sure that empty text frames have a valid data.ptr */
    if (out->datalen || f->frametype == AST_FRAME_TEXT) {
       out->data.ptr = buf + sizeof(*out) + AST_FRIENDLY_OFFSET;
       memcpy(out->data.ptr, f->data.ptr, out->datalen);
    } else {
       out->data.uint32 = f->data.uint32;
    }
    if (srclen > 0) {
       /* This may seem a little strange, but it's to avoid a gcc (4.2.4) compiler warning */
       char *src;
       out->src = buf + sizeof(*out) + AST_FRIENDLY_OFFSET + f->datalen;
       src = (char *) out->src;
       /* Must have space since we allocated for it */
       strcpy(src, f->src);
    }
    ast_copy_flags(out, f, AST_FLAGS_ALL);
    out->ts = f->ts;
    out->len = f->len;
    out->seqno = f->seqno;
    out->stream_num = f->stream_num;
    return out;
 }
__ast_frisolate()
struct ast_frame* __ast_frisolate (struct ast_frame * fr, const char * file, int line, const char * func)
'isolates' a frame by duplicating non-malloc'ed components (header, src, data). On return all components are malloc'ed
Definition at line 197 of file main/frame.c.
References __ast_frdup(), ao2_bump, AST_CONTROL_ANSWER, ast_copy_flags, AST_FLAGS_ALL, ast_frame_free(), ast_frame_header_new(), AST_FRAME_IMAGE, AST_FRAME_TEXT, AST_FRAME_VIDEO, AST_FRAME_VOICE, AST_FRFLAG_HAS_TIMING_INFO, AST_FRIENDLY_OFFSET, ast_malloc, AST_MALLOCD_DATA, AST_MALLOCD_HDR, AST_MALLOCD_SRC, ast_strdup, ast_test_flag, ast_frame::data, ast_frame::datalen, ast_frame_subclass::format, ast_frame::frametype, ast_frame_subclass::integer, ast_frame::len, ast_frame::mallocd, NULL, ast_frame::offset, out, ast_frame::ptr, ast_frame::samples, ast_frame::seqno, ast_frame::src, ast_frame::stream_num, ast_frame::subclass, ast_frame_subclass::topology, ast_frame::ts, and ast_frame::uint32.
 {
    struct ast_frame *out;
    void *newdata;
    /* if none of the existing frame is malloc'd, let ast_frdup() do it
       since it is more efficient
    */
    if (fr->mallocd == 0) {
       return __ast_frdup(fr, file, line, func);
    }
    /* if everything is already malloc'd, we are done */
    if ((fr->mallocd & (AST_MALLOCD_HDR | AST_MALLOCD_SRC | AST_MALLOCD_DATA)) ==
        (AST_MALLOCD_HDR | AST_MALLOCD_SRC | AST_MALLOCD_DATA)) {
       return fr;
    }
    if (!(fr->mallocd & AST_MALLOCD_HDR)) {
       /* Allocate a new header if needed */
       if (!(out = ast_frame_header_new(file, line, func))) {
          return NULL;
       }
       out->frametype = fr->frametype;
       out->subclass = fr->subclass;
       if ((fr->frametype == AST_FRAME_VOICE) || (fr->frametype == AST_FRAME_VIDEO) ||
          (fr->frametype == AST_FRAME_IMAGE)) {
          ao2_bump(out->subclass.format);
       } else if (fr->frametype == AST_FRAME_VOICE && fr->subclass.integer == AST_CONTROL_ANSWER) {
          ao2_bump(out->subclass.topology);
       }
       out->datalen = fr->datalen;
       out->samples = fr->samples;
       out->mallocd = AST_MALLOCD_HDR;
       out->offset = fr->offset;
       /* Copy the timing data */
       ast_copy_flags(out, fr, AST_FLAGS_ALL);
       if (ast_test_flag(fr, AST_FRFLAG_HAS_TIMING_INFO)) {
          out->ts = fr->ts;
          out->len = fr->len;
          out->seqno = fr->seqno;
       }
       out->stream_num = fr->stream_num;
    } else {
       out = fr;
    }
    if (fr->src) {
       /* The original frame has a source string */
       if (!(fr->mallocd & AST_MALLOCD_SRC)) {
          /*
           * The original frame has a non-malloced source string.
           *
           * Duplicate the string and put it into the isolated frame
           * which may also be the original frame.
           */
          newdata = ast_strdup(fr->src);
          if (!newdata) {
             if (out != fr) {
                ast_frame_free(out, 0);
             }
             return NULL;
          }
          out->src = newdata;
          out->mallocd |= AST_MALLOCD_SRC;
       } else if (out != fr) {
          /* Steal the source string from the original frame. */
          out->src = fr->src;
          fr->src = NULL;
          fr->mallocd &= ~AST_MALLOCD_SRC;
          out->mallocd |= AST_MALLOCD_SRC;
       }
    }
    if (!(fr->mallocd & AST_MALLOCD_DATA))  {
       /* The original frame has a non-malloced data buffer. */
       if (!fr->datalen && fr->frametype != AST_FRAME_TEXT) {
          /* Actually it's just an int so we can simply copy it. */
          out->data.uint32 = fr->data.uint32;
          return out;
       }
       /*
        * Duplicate the data buffer and put it into the isolated frame
        * which may also be the original frame.
        */
       newdata = ast_malloc(fr->datalen + AST_FRIENDLY_OFFSET);
       if (!newdata) {
          if (out != fr) {
             ast_frame_free(out, 0);
          }
          return NULL;
       }
       newdata += AST_FRIENDLY_OFFSET;
       out->offset = AST_FRIENDLY_OFFSET;
       memcpy(newdata, fr->data.ptr, fr->datalen);
       out->data.ptr = newdata;
       out->mallocd |= AST_MALLOCD_DATA;
    } else if (out != fr) {
       /* Steal the data buffer from the original frame. */
       out->data = fr->data;
       memset(&fr->data, 0, sizeof(fr->data));
       fr->mallocd &= ~AST_MALLOCD_DATA;
       out->mallocd |= AST_MALLOCD_DATA;
    }
    return out;
 }
__frame_free()
static void __frame_free (struct ast_frame * fr, int cache) static
Definition at line 122 of file main/frame.c.
References ao2_cleanup, AST_CONTROL_ANSWER, AST_FRAME_CONTROL, AST_FRAME_IMAGE, AST_FRAME_VIDEO, AST_FRAME_VOICE, ast_free, AST_LIST_INSERT_HEAD, AST_MALLOCD_DATA, AST_MALLOCD_HDR, AST_MALLOCD_SRC, ast_opt_cache_media_frames, ast_threadstorage_get(), ast_frame::data, ast_frame_subclass::format, frame_cache, FRAME_CACHE_MAX_SIZE, frames, ast_frame::frametype, ast_frame_subclass::integer, ast_frame_cache::list, ast_frame::mallocd, ast_frame::offset, ast_frame::ptr, ast_frame_cache::size, ast_frame::src, ast_frame::subclass, and ast_frame_subclass::topology.
Referenced by ast_frame_free().
 {
    if (!fr->mallocd)
       return;
 #if !defined(NO_FRAME_CACHE)
    if (fr->mallocd == AST_MALLOCD_HDR
       && cache
       && ast_opt_cache_media_frames) {
       /* Cool, only the header is malloc'd, let's just cache those for now
        * to keep things simple... */
       struct ast_frame_cache *frames;
       frames = ast_threadstorage_get(&frame_cache, sizeof(*frames));
       if (frames && frames->size < FRAME_CACHE_MAX_SIZE) {
          if (fr->frametype == AST_FRAME_VOICE
             || fr->frametype == AST_FRAME_VIDEO
             || fr->frametype == AST_FRAME_IMAGE) {
             ao2_cleanup(fr->subclass.format);
          } else if (fr->frametype == AST_FRAME_CONTROL && fr->subclass.integer == AST_CONTROL_ANSWER) {
             ao2_cleanup(fr->subclass.topology);
          }
          AST_LIST_INSERT_HEAD(&frames->list, fr, frame_list);
          frames->size++;
          return;
       }
    }
 #endif
    if (fr->mallocd & AST_MALLOCD_DATA) {
       if (fr->data.ptr) {
          ast_free(fr->data.ptr - fr->offset);
       }
    }
    if (fr->mallocd & AST_MALLOCD_SRC) {
       ast_free((void *) fr->src);
    }
    if (fr->mallocd & AST_MALLOCD_HDR) {
       if (fr->frametype == AST_FRAME_VOICE
          || fr->frametype == AST_FRAME_VIDEO
          || fr->frametype == AST_FRAME_IMAGE) {
          ao2_cleanup(fr->subclass.format);
       } else if (fr->frametype == AST_FRAME_CONTROL && fr->subclass.integer == AST_CONTROL_ANSWER) {
          ao2_cleanup(fr->subclass.topology);
       }
       ast_free(fr);
    } else {
       fr->mallocd = 0;
    }
 }
__init_frame_cache()
static void __init_frame_cache (void) static
A per-thread cache of frame headers.
Definition at line 56 of file main/frame.c.
 {
ast_frame_adjust_volume()
int ast_frame_adjust_volume (struct ast_frame * f, int adjustment)
Adjusts the volume of the audio samples contained in a frame.
Parameters
f The frame containing the samples (must be AST_FRAME_VOICE and AST_FORMAT_SLINEAR)
adjustment The number of dB to adjust up or down.
Returns
0 for success, non-zero for an error
Definition at line 787 of file main/frame.c.
References abs, ast_format_cache_is_slinear(), AST_FRAME_VOICE, ast_slinear_saturated_divide(), ast_slinear_saturated_multiply(), ast_frame::data, ast_frame_subclass::format, ast_frame::frametype, ast_frame::ptr, ast_frame::samples, and ast_frame::subclass.
Referenced by audiohook_read_frame_single(), audiohook_volume_callback(), and conf_run().
 {
    int count;
    short *fdata = f->data.ptr;
    short adjust_value = abs(adjustment);
    if ((f->frametype != AST_FRAME_VOICE) || !(ast_format_cache_is_slinear(f->subclass.format))) {
       return -1;
    }
    if (!adjustment) {
       return 0;
    }
    for (count = 0; count < f->samples; count++) {
       if (adjustment > 0) {
          ast_slinear_saturated_multiply(&fdata[count], &adjust_value);
       } else if (adjustment < 0) {
          ast_slinear_saturated_divide(&fdata[count], &adjust_value);
       }
    }
    return 0;
 }
ast_frame_adjust_volume_float()
int ast_frame_adjust_volume_float (struct ast_frame * f, float adjustment)
Adjusts the volume of the audio samples contained in a frame.
Parameters
f The frame containing the samples (must be AST_FRAME_VOICE and AST_FORMAT_SLINEAR)
adjustment The number of dB to adjust up or down.
Returns
0 for success, non-zero for an error
Definition at line 812 of file main/frame.c.
References ast_format_cache_is_slinear(), AST_FRAME_VOICE, ast_slinear_saturated_divide_float(), ast_slinear_saturated_multiply_float(), ast_frame::data, ast_frame_subclass::format, ast_frame::frametype, ast_frame::ptr, ast_frame::samples, and ast_frame::subclass.
Referenced by volume_callback().
 {
    int count;
    short *fdata = f->data.ptr;
    float adjust_value = fabs(adjustment);
    if ((f->frametype != AST_FRAME_VOICE) || !(ast_format_cache_is_slinear(f->subclass.format))) {
       return -1;
    }
    if (!adjustment) {
       return 0;
    }
    for (count = 0; count < f->samples; count++) {
       if (adjustment > 0) {
          ast_slinear_saturated_multiply_float(&fdata[count], &adjust_value);
       } else if (adjustment < 0) {
          ast_slinear_saturated_divide_float(&fdata[count], &adjust_value);
       }
    }
    return 0;
 }
ast_frame_clear()
int ast_frame_clear (struct ast_frame * frame)
Clear all audio samples from an ast_frame. The frame must be AST_FRAME_VOICE and AST_FORMAT_SLINEAR.
Definition at line 859 of file main/frame.c.
References AST_LIST_NEXT, ast_frame::data, ast_frame::datalen, ast_frame::next, NULL, and ast_frame::ptr.
Referenced by audiohook_read_frame_single().
 {
    struct ast_frame *next;
    for (next = AST_LIST_NEXT(frame, frame_list);
        frame;
        frame = next, next = frame ? AST_LIST_NEXT(frame, frame_list) : NULL) {
       memset(frame->data.ptr, 0, frame->datalen);
    }
    return 0;
 }
ast_frame_dtor()
void ast_frame_dtor (struct ast_frame * frame)
NULL-safe wrapper for ast_frfree, good for RAII_VAR.
Parameters
frame Frame to free, or head of list to free.
Definition at line 187 of file main/frame.c.
References ast_frfree.
Referenced by __ast_play_and_record(), snoop_read(), and stasis_app_exec().
 {
    ast_frfree(f);
 }
ast_frame_dump()
void ast_frame_dump (const char * name, struct ast_frame * f, char * prefix)
Dump a frame for debugging purposes
Definition at line 731 of file main/frame.c.
References AST_FRAME_RTCP, ast_frame_subclass2str(), ast_frame_type2str(), AST_FRAME_VIDEO, AST_FRAME_VOICE, ast_strlen_zero, ast_verb, COLOR_BLACK, COLOR_BRCYAN, COLOR_BRGREEN, COLOR_BRMAGENTA, COLOR_BRRED, COLOR_YELLOW, ast_frame::frametype, ast_frame_subclass::integer, ast_frame::subclass, and term_color().
Referenced by __ast_read(), and ast_write_stream().
 {
    const char noname[] = "unknown";
    char ftype[40] = "Unknown Frametype";
    char cft[80];
    char subclass[40] = "Unknown Subclass";
    char csub[80];
    char moreinfo[40] = "";
    char cn[60];
    char cp[40];
    char cmn[40];
    if (!name) {
       name = noname;
    }
    if (!f) {
       ast_verb(-1, "%s [ %s (NULL) ] [%s]\n",
          term_color(cp, prefix, COLOR_BRMAGENTA, COLOR_BLACK, sizeof(cp)),
          term_color(cft, "HANGUP", COLOR_BRRED, COLOR_BLACK, sizeof(cft)),
          term_color(cn, name, COLOR_YELLOW, COLOR_BLACK, sizeof(cn)));
       return;
    }
    /* XXX We should probably print one each of voice and video when the format changes XXX */
    if (f->frametype == AST_FRAME_VOICE) {
       return;
    }
    if (f->frametype == AST_FRAME_VIDEO) {
       return;
    }
    if (f->frametype == AST_FRAME_RTCP) {
       return;
    }
    ast_frame_type2str(f->frametype, ftype, sizeof(ftype));
    ast_frame_subclass2str(f, subclass, sizeof(subclass), moreinfo, sizeof(moreinfo));
    if (!ast_strlen_zero(moreinfo))
       ast_verb(-1, "%s [ TYPE: %s (%u) SUBCLASS: %s (%d) '%s' ] [%s]\n",
              term_color(cp, prefix, COLOR_BRMAGENTA, COLOR_BLACK, sizeof(cp)),
              term_color(cft, ftype, COLOR_BRRED, COLOR_BLACK, sizeof(cft)),
              f->frametype,
              term_color(csub, subclass, COLOR_BRCYAN, COLOR_BLACK, sizeof(csub)),
              f->subclass.integer,
              term_color(cmn, moreinfo, COLOR_BRGREEN, COLOR_BLACK, sizeof(cmn)),
              term_color(cn, name, COLOR_YELLOW, COLOR_BLACK, sizeof(cn)));
    else
       ast_verb(-1, "%s [ TYPE: %s (%u) SUBCLASS: %s (%d) ] [%s]\n",
              term_color(cp, prefix, COLOR_BRMAGENTA, COLOR_BLACK, sizeof(cp)),
              term_color(cft, ftype, COLOR_BRRED, COLOR_BLACK, sizeof(cft)),
              f->frametype,
              term_color(csub, subclass, COLOR_BRCYAN, COLOR_BLACK, sizeof(csub)),
              f->subclass.integer,
              term_color(cn, name, COLOR_YELLOW, COLOR_BLACK, sizeof(cn)));
 }
ast_frame_free()
void ast_frame_free (struct ast_frame * fr, int cache)
Requests a frame to be allocated.
Parameters
source Request a frame be allocated. source is an optional source of the frame, len is the requested length, or "0" if the caller will supply the buffer
Frees a frame or list of frames
Parameters
fr Frame to free, or head of list to free
cache Whether to consider this frame for frame caching
Definition at line 176 of file main/frame.c.
References __frame_free(), AST_LIST_NEXT, and ast_frame::next.
Referenced by __ast_frisolate(), ast_rtp_read(), and mixmonitor_thread().
 {
    struct ast_frame *next;
    while (frame) {
       next = AST_LIST_NEXT(frame, frame_list);
       __frame_free(frame, cache);
       frame = next;
    }
 }
ast_frame_header_new()
static struct ast_frame* ast_frame_header_new (const char * file, int line, const char * func) static
Definition at line 81 of file main/frame.c.
References __ast_calloc(), AST_LIST_REMOVE_HEAD, ast_threadstorage_get(), frame_cache, frames, ast_frame_cache::list, ast_frame::mallocd_hdr_len, NULL, and ast_frame_cache::size.
Referenced by __ast_frisolate().
 {
    struct ast_frame *f;
 #if !defined(NO_FRAME_CACHE)
    struct ast_frame_cache *frames;
    if ((frames = ast_threadstorage_get(&frame_cache, sizeof(*frames)))) {
       if ((f = AST_LIST_REMOVE_HEAD(&frames->list, frame_list))) {
          size_t mallocd_len = f->mallocd_hdr_len;
          memset(f, 0, sizeof(*f));
          f->mallocd_hdr_len = mallocd_len;
          frames->size--;
          return f;
       }
    }
 #endif
    if (!(f = __ast_calloc(1, sizeof(*f), file, line, func))) {
       return NULL;
    }
    f->mallocd_hdr_len = sizeof(*f);
    return f;
 }
ast_frame_slinear_sum()
int ast_frame_slinear_sum (struct ast_frame * f1, struct ast_frame * f2)
Sums two frames of audio samples.
Parameters
f1 The first frame (which will contain the result)
f2 The second frame
Returns
0 for success, non-zero for an error
The frames must be AST_FRAME_VOICE and must contain AST_FORMAT_SLINEAR samples, and must contain the same number of samples.
Definition at line 837 of file main/frame.c.
References ast_format_cmp(), AST_FORMAT_CMP_NOT_EQUAL, ast_format_slin, AST_FRAME_VOICE, ast_slinear_saturated_add(), ast_frame::data, ast_frame_subclass::format, ast_frame::frametype, ast_frame::ptr, ast_frame::samples, and ast_frame::subclass.
 {
    int count;
    short *data1, *data2;
    if ((f1->frametype != AST_FRAME_VOICE) || (ast_format_cmp(f1->subclass.format, ast_format_slin) != AST_FORMAT_CMP_NOT_EQUAL))
       return -1;
    if ((f2->frametype != AST_FRAME_VOICE) || (ast_format_cmp(f2->subclass.format, ast_format_slin) != AST_FORMAT_CMP_NOT_EQUAL))
       return -1;
    if (f1->samples != f2->samples)
       return -1;
    for (count = 0, data1 = f1->data.ptr, data2 = f2->data.ptr;
         count < f1->samples;
         count++, data1++, data2++)
       ast_slinear_saturated_add(data1, data2);
    return 0;
 }
ast_frame_subclass2str()
char* ast_frame_subclass2str (struct ast_frame * f, char * subclass, size_t slen, char * moreinfo, size_t mlen)
Copy the discription of a frame's subclass into the provided string.
Parameters
f The frame to get the information from
subclass Buffer to fill with subclass information
slen Length of subclass buffer
moreinfo Buffer to fill with additional information
mlen Length of moreinfo buffer
Returns
Pointer to subclass
Since
11
Definition at line 406 of file main/frame.c.
References AST_CONTROL_ANSWER, AST_CONTROL_AOC, AST_CONTROL_BUSY, AST_CONTROL_CC, AST_CONTROL_CONGESTION, AST_CONTROL_CONNECTED_LINE, AST_CONTROL_END_OF_Q, AST_CONTROL_FLASH, AST_CONTROL_HANGUP, AST_CONTROL_HOLD, AST_CONTROL_INCOMPLETE, AST_CONTROL_MASQUERADE_NOTIFY, AST_CONTROL_MCID, AST_CONTROL_OFFHOOK, AST_CONTROL_OPTION, AST_CONTROL_PROCEEDING, AST_CONTROL_PROGRESS, AST_CONTROL_PVT_CAUSE_CODE, AST_CONTROL_RADIO_KEY, AST_CONTROL_RADIO_UNKEY, AST_CONTROL_READ_ACTION, AST_CONTROL_RECORD_CANCEL, AST_CONTROL_RECORD_MUTE, AST_CONTROL_RECORD_STOP, AST_CONTROL_RECORD_SUSPEND, AST_CONTROL_REDIRECTING, AST_CONTROL_RING, AST_CONTROL_RINGING, AST_CONTROL_SRCCHANGE, AST_CONTROL_SRCUPDATE, AST_CONTROL_STREAM_FORWARD, AST_CONTROL_STREAM_RESTART, AST_CONTROL_STREAM_REVERSE, AST_CONTROL_STREAM_STOP, AST_CONTROL_STREAM_SUSPEND, AST_CONTROL_STREAM_TOPOLOGY_CHANGED, AST_CONTROL_STREAM_TOPOLOGY_REQUEST_CHANGE, AST_CONTROL_STREAM_TOPOLOGY_SOURCE_CHANGED, AST_CONTROL_T38_PARAMETERS, AST_CONTROL_TAKEOFFHOOK, AST_CONTROL_TRANSFER, AST_CONTROL_UNHOLD, AST_CONTROL_UPDATE_RTP_PEER, AST_CONTROL_VIDUPDATE, AST_CONTROL_WINK, ast_copy_string(), ast_format_get_name(), AST_FRAME_BRIDGE_ACTION, AST_FRAME_BRIDGE_ACTION_SYNC, AST_FRAME_CONTROL, AST_FRAME_DTMF_BEGIN, AST_FRAME_DTMF_END, AST_FRAME_HTML, AST_FRAME_IAX, AST_FRAME_IMAGE, AST_FRAME_MODEM, AST_FRAME_NULL, AST_FRAME_RTCP, AST_FRAME_TEXT, AST_HTML_BEGIN, AST_HTML_DATA, AST_HTML_END, AST_HTML_LDCOMPLETE, AST_HTML_LINKREJECT, AST_HTML_LINKURL, AST_HTML_NOSUPPORT, AST_HTML_UNLINK, AST_HTML_URL, AST_MODEM_T38, AST_MODEM_V150, AST_T38_NEGOTIATED, AST_T38_REFUSED, AST_T38_REQUEST_NEGOTIATE, AST_T38_REQUEST_TERMINATE, AST_T38_TERMINATED, ast_frame::data, ast_frame::datalen, ast_frame_subclass::format, ast_frame::frametype, ast_frame_subclass::integer, ast_frame::ptr, ast_control_t38_parameters::request_response, and ast_frame::subclass.
Referenced by ast_frame_dump(), and chan_pjsip_indicate().
 {
    switch(f->frametype) {
    case AST_FRAME_DTMF_BEGIN:
       if (slen > 1) {
          subclass[0] = f->subclass.integer;
          subclass[1] = '\0';
       }
       break;
    case AST_FRAME_DTMF_END:
       if (slen > 1) {
          subclass[0] = f->subclass.integer;
          subclass[1] = '\0';
       }
       break;
    case AST_FRAME_CONTROL:
       switch (f->subclass.integer) {
       case AST_CONTROL_HANGUP:
          ast_copy_string(subclass, "Hangup", slen);
          break;
       case AST_CONTROL_RING:
          ast_copy_string(subclass, "Ring", slen);
          break;
       case AST_CONTROL_RINGING:
          ast_copy_string(subclass, "Ringing", slen);
          break;
       case AST_CONTROL_ANSWER:
          ast_copy_string(subclass, "Answer", slen);
          break;
       case AST_CONTROL_BUSY:
          ast_copy_string(subclass, "Busy", slen);
          break;
       case AST_CONTROL_TAKEOFFHOOK:
          ast_copy_string(subclass, "Take Off Hook", slen);
          break;
       case AST_CONTROL_OFFHOOK:
          ast_copy_string(subclass, "Line Off Hook", slen);
          break;
       case AST_CONTROL_CONGESTION:
          ast_copy_string(subclass, "Congestion", slen);
          break;
       case AST_CONTROL_FLASH:
          ast_copy_string(subclass, "Flash", slen);
          break;
       case AST_CONTROL_WINK:
          ast_copy_string(subclass, "Wink", slen);
          break;
       case AST_CONTROL_OPTION:
          ast_copy_string(subclass, "Option", slen);
          break;
       case AST_CONTROL_RADIO_KEY:
          ast_copy_string(subclass, "Key Radio", slen);
          break;
       case AST_CONTROL_RADIO_UNKEY:
          ast_copy_string(subclass, "Unkey Radio", slen);
          break;
       case AST_CONTROL_PROGRESS:
          ast_copy_string(subclass, "Progress", slen);
          break;
       case AST_CONTROL_PROCEEDING:
          ast_copy_string(subclass, "Proceeding", slen);
          break;
       case AST_CONTROL_HOLD:
          ast_copy_string(subclass, "Hold", slen);
          break;
       case AST_CONTROL_UNHOLD:
          ast_copy_string(subclass, "Unhold", slen);
          break;
       case AST_CONTROL_VIDUPDATE:
          ast_copy_string(subclass, "Video Update", slen);
          break;
       case AST_CONTROL_T38_PARAMETERS: {
          char *message = "Unknown";
          if (f->datalen != sizeof(struct ast_control_t38_parameters)) {
             message = "Invalid";
          } else {
             struct ast_control_t38_parameters *parameters = f->data.ptr;
             enum ast_control_t38 state = parameters->request_response;
             if (state == AST_T38_REQUEST_NEGOTIATE)
                message = "Negotiation Requested";
             else if (state == AST_T38_REQUEST_TERMINATE)
                message = "Negotiation Request Terminated";
             else if (state == AST_T38_NEGOTIATED)
                message = "Negotiated";
             else if (state == AST_T38_TERMINATED)
                message = "Terminated";
             else if (state == AST_T38_REFUSED)
                message = "Refused";
          }
          snprintf(subclass, slen, "T38_Parameters/%s", message);
          break;
       }
       case AST_CONTROL_STREAM_STOP:
          ast_copy_string(subclass, "Stop stream", slen);
          break;
       case AST_CONTROL_STREAM_SUSPEND:
          ast_copy_string(subclass, "Suspend stream", slen);
          break;
       case AST_CONTROL_STREAM_RESTART:
          ast_copy_string(subclass, "Restart stream", slen);
          break;
       case AST_CONTROL_STREAM_REVERSE:
          ast_copy_string(subclass, "Reverse stream", slen);
          break;
       case AST_CONTROL_STREAM_FORWARD:
          ast_copy_string(subclass, "Forward stream", slen);
          break;
       case AST_CONTROL_RECORD_CANCEL:
          ast_copy_string(subclass, "Cancel stream", slen);
          break;
       case AST_CONTROL_RECORD_STOP:
          ast_copy_string(subclass, "Record stop", slen);
          break;
       case AST_CONTROL_RECORD_SUSPEND:
          ast_copy_string(subclass, "Record suspend", slen);
          break;
       case AST_CONTROL_RECORD_MUTE:
          ast_copy_string(subclass, "Record mute", slen);
          break;
       case AST_CONTROL_SRCUPDATE:
          ast_copy_string(subclass, "Media source update", slen);
          break;
       case AST_CONTROL_TRANSFER:
          ast_copy_string(subclass, "Transfer", slen);
          break;
       case AST_CONTROL_CONNECTED_LINE:
          ast_copy_string(subclass, "Connected line update", slen);
          break;
       case AST_CONTROL_REDIRECTING:
          ast_copy_string(subclass, "Redirect", slen);
          break;
       case AST_CONTROL_CC:
          ast_copy_string(subclass, "CC", slen);
          break;
       case AST_CONTROL_SRCCHANGE:
          ast_copy_string(subclass, "Media SSRC change", slen);
          break;
       case AST_CONTROL_READ_ACTION:
          ast_copy_string(subclass, "Read action", slen);
          break;
       case AST_CONTROL_AOC:
          ast_copy_string(subclass, "AOC", slen);
          break;
       case AST_CONTROL_END_OF_Q:
          ast_copy_string(subclass, "Endof Q", slen);
          break;
       case AST_CONTROL_INCOMPLETE:
          ast_copy_string(subclass, "Incomplete", slen);
          break;
       case AST_CONTROL_MCID:
          ast_copy_string(subclass, "MCID", slen);
          break;
       case AST_CONTROL_UPDATE_RTP_PEER:
          ast_copy_string(subclass, "Update RTP peer", slen);
          break;
       case AST_CONTROL_PVT_CAUSE_CODE:
          ast_copy_string(subclass, "Private Cause Code", slen);
          break;
       case AST_CONTROL_MASQUERADE_NOTIFY:
          ast_copy_string(subclass, "Masquerade notify", slen);
          break;
       case AST_CONTROL_STREAM_TOPOLOGY_REQUEST_CHANGE:
          ast_copy_string(subclass, "Stream topology request change", slen);
          break;
       case AST_CONTROL_STREAM_TOPOLOGY_CHANGED:
          ast_copy_string(subclass, "Stream topology changed", slen);
          break;
       case AST_CONTROL_STREAM_TOPOLOGY_SOURCE_CHANGED:
          ast_copy_string(subclass, "Stream topology source changed", slen);
          break;
       case -1:
          ast_copy_string(subclass, "Stop generators", slen);
          break;
       default:
          snprintf(subclass, slen, "Unknown control '%d'", f->subclass.integer);
       }
       break;
    case AST_FRAME_NULL:
       ast_copy_string(subclass, "N/A", slen);
       break;
    case AST_FRAME_IAX:
       /* Should never happen */
       snprintf(subclass, slen, "IAX Frametype %d", f->subclass.integer);
       break;
    case AST_FRAME_BRIDGE_ACTION:
       /* Should never happen */
       snprintf(subclass, slen, "Bridge Frametype %d", f->subclass.integer);
       break;
    case AST_FRAME_BRIDGE_ACTION_SYNC:
       /* Should never happen */
       snprintf(subclass, slen, "Synchronous Bridge Frametype %d", f->subclass.integer);
       break;
    case AST_FRAME_TEXT:
       ast_copy_string(subclass, "N/A", slen);
       if (moreinfo) {
          ast_copy_string(moreinfo, f->data.ptr, mlen);
       }
       break;
    case AST_FRAME_IMAGE:
       snprintf(subclass, slen, "Image format %s\n", ast_format_get_name(f->subclass.format));
       break;
    case AST_FRAME_HTML:
       switch (f->subclass.integer) {
       case AST_HTML_URL:
          ast_copy_string(subclass, "URL", slen);
          if (moreinfo) {
             ast_copy_string(moreinfo, f->data.ptr, mlen);
          }
          break;
       case AST_HTML_DATA:
          ast_copy_string(subclass, "Data", slen);
          break;
       case AST_HTML_BEGIN:
          ast_copy_string(subclass, "Begin", slen);
          break;
       case AST_HTML_END:
          ast_copy_string(subclass, "End", slen);
          break;
       case AST_HTML_LDCOMPLETE:
          ast_copy_string(subclass, "Load Complete", slen);
          break;
       case AST_HTML_NOSUPPORT:
          ast_copy_string(subclass, "No Support", slen);
          break;
       case AST_HTML_LINKURL:
          ast_copy_string(subclass, "Link URL", slen);
          if (moreinfo) {
             ast_copy_string(moreinfo, f->data.ptr, mlen);
          }
          break;
       case AST_HTML_UNLINK:
          ast_copy_string(subclass, "Unlink", slen);
          break;
       case AST_HTML_LINKREJECT:
          ast_copy_string(subclass, "Link Reject", slen);
          break;
       default:
          snprintf(subclass, slen, "Unknown HTML frame '%d'\n", f->subclass.integer);
          break;
       }
       break;
    case AST_FRAME_MODEM:
       switch (f->subclass.integer) {
       case AST_MODEM_T38:
          ast_copy_string(subclass, "T.38", slen);
          break;
       case AST_MODEM_V150:
          ast_copy_string(subclass, "V.150", slen);
          break;
       default:
          snprintf(subclass, slen, "Unknown MODEM frame '%d'\n", f->subclass.integer);
          break;
       }
       break;
    case AST_FRAME_RTCP:
       ast_copy_string(subclass, "RTCP", slen);
    default:
       ast_copy_string(subclass, "Unknown Subclass", slen);
       break;
    }
    return subclass;
 }
ast_frame_type2str()
char* ast_frame_type2str (enum ast_frame_type frame_type, char * ftype, size_t len)
Copy the discription of a frame type into the provided string.
Parameters
frame_type The frame type to be described
ftype Buffer to fill with frame type description
len Length of subclass buffer
Returns
Pointer to ftype
Since
11
Definition at line 671 of file main/frame.c.
References ast_copy_string(), AST_FRAME_BRIDGE_ACTION, AST_FRAME_BRIDGE_ACTION_SYNC, AST_FRAME_CONTROL, AST_FRAME_DTMF_BEGIN, AST_FRAME_DTMF_END, AST_FRAME_HTML, AST_FRAME_IAX, AST_FRAME_IMAGE, AST_FRAME_MODEM, AST_FRAME_NULL, AST_FRAME_RTCP, AST_FRAME_TEXT, AST_FRAME_TEXT_DATA, AST_FRAME_VIDEO, and AST_FRAME_VOICE.
Referenced by ast_frame_dump(), softmix_bridge_write_text(), and stream_echo_write_error().
 {
    switch (frame_type) {
    case AST_FRAME_DTMF_BEGIN:
       ast_copy_string(ftype, "DTMF Begin", len);
       break;
    case AST_FRAME_DTMF_END:
       ast_copy_string(ftype, "DTMF End", len);
       break;
    case AST_FRAME_CONTROL:
       ast_copy_string(ftype, "Control", len);
       break;
    case AST_FRAME_NULL:
       ast_copy_string(ftype, "Null Frame", len);
       break;
    case AST_FRAME_IAX:
       /* Should never happen */
       ast_copy_string(ftype, "IAX Specific", len);
       break;
    case AST_FRAME_BRIDGE_ACTION:
       /* Should never happen */
       ast_copy_string(ftype, "Bridge Specific", len);
       break;
    case AST_FRAME_BRIDGE_ACTION_SYNC:
       /* Should never happen */
       ast_copy_string(ftype, "Bridge Specific", len);
       break;
    case AST_FRAME_TEXT:
       ast_copy_string(ftype, "Text", len);
       break;
    case AST_FRAME_TEXT_DATA:
       ast_copy_string(ftype, "Text Data", len);
       break;
    case AST_FRAME_IMAGE:
       ast_copy_string(ftype, "Image", len);
       break;
    case AST_FRAME_HTML:
       ast_copy_string(ftype, "HTML", len);
       break;
    case AST_FRAME_MODEM:
       ast_copy_string(ftype, "Modem", len);
       break;
    case AST_FRAME_VOICE:
       ast_copy_string(ftype, "Voice", len);
       break;
    case AST_FRAME_VIDEO:
       ast_copy_string(ftype, "Video", len);
       break;
    case AST_FRAME_RTCP:
       ast_copy_string(ftype, "RTCP", len);
       break;
    default:
       snprintf(ftype, len, "Unknown Frametype '%u'", frame_type);
       break;
    }
    return ftype;
 }
ast_swapcopy_samples()
void ast_swapcopy_samples (void * dst, const void * src, int samples)
Definition at line 396 of file main/frame.c.
Referenced by __ast_smoother_feed(), iax_frame_wrap(), phone_write_buf(), and smoother_frame_feed().
 {
    int i;
    unsigned short *dst_s = dst;
    const unsigned short *src_s = src;
    for (i = 0; i < samples; i++)
       dst_s[i] = (src_s[i]<<8) | (src_s[i]>>8);
 }
frame_cache_cleanup()
static void frame_cache_cleanup (void * data) static
Definition at line 110 of file main/frame.c.
References ast_free, AST_LIST_REMOVE_HEAD, frames, and ast_frame_cache::list.
 {
    struct ast_frame_cache *frames = data;
    struct ast_frame *f;
    while ((f = AST_LIST_REMOVE_HEAD(&frames->list, frame_list)))
       ast_free(f);
    ast_free(frames);
 }
Variable Documentation
ast_null_frame
struct ast_frame ast_null_frame = { AST_FRAME_NULL, }
Queueing a null frame is fairly common, so we declare a global null frame object for this purpose instead of having to declare one on the stack
Definition at line 79 of file main/frame.c.
Referenced by __analog_handle_event(), __ast_read(), apply_negotiated_sdp_stream(), ast_audiosocket_receive_frame(), ast_channel_set_unbridged_nolock(), ast_channel_setwhentohangup_tv(), ast_rtcp_interpret(), ast_rtcp_read(), ast_rtp_interpret(), ast_rtp_read(), ast_softhangup_nolock(), AST_TEST_DEFINE(), ast_translate(), ast_udptl_read(), ast_unreal_read(), bridge_channel_internal_push_full(), bridge_channel_poke(), chan_msg_read(), chan_pjsip_cng_tone_detected(), chan_pjsip_read_stream(), channel_do_masquerade(), conf_run(), console_read(), create_dtmf_frame(), dahdi_handle_event(), dahdi_read(), fake_read(), fax_detect_framehook(), fax_gateway_detect_t38(), fax_gateway_framehook(), handle_negotiated_sdp(), handle_request_invite(), handle_response_invite(), hold_intercept_framehook(), hook_event_cb(), iax2_read(), jb_get_adaptive(), jb_get_fixed(), jingle_read(), mbl_read(), media_session_rtcp_read_callback(), media_session_rtp_read_callback(), media_session_udptl_read_callback(), mgcp_rtp_read(), multicast_rtp_read(), nbs_xread(), ooh323_rtp_read(), parking_test_read(), process_sdp(), rec_read(), rtp_read(), set_interval_hook(), sip_read(), sip_rtp_read(), skinny_rtp_read(), snoop_read(), spandsp_fax_read(), stream_periodic_frames(), suppress_framehook_event_cb(), test_sip_rtpqos_1_read(), test_vm_api_mock_channel_read(), unistim_rtp_read(), and wakeup_sub().
frame_cache
struct ast_threadstorage frame_cache = { .once = PTHREAD_ONCE_INIT , .key_init = __init_frame_cache , .custom_init = NULL , } static
Definition at line 56 of file main/frame.c.
Referenced by __ast_frdup(), __frame_free(), and ast_frame_header_new().