Asterisk - The Open Source Telephony Project: stasis_app_mailbox.h File Reference
stasis_app_mailbox.h File Reference
Stasis Application Mailbox API. See StasisApplication API" for detailed documentation.
#include "asterisk/app.h"
#include "asterisk/stasis_app.h"
enum stasis_mailbox_result { STASIS_MAILBOX_OK, STASIS_MAILBOX_MISSING, STASIS_MAILBOX_ERROR }
enum stasis_mailbox_result stasis_app_mailbox_to_json (const char *name, struct ast_json **json)
Convert mailbox to JSON.
struct ast_json * stasis_app_mailboxes_to_json (void)
int stasis_app_mailbox_update (const char *name, int old_messages, int new_messages)
Changes the state of a mailbox.
enum stasis_mailbox_result stasis_app_mailbox_delete (const char *name)
Delete a mailbox controlled by ARI.
Detailed Description
Stasis Application Mailbox API. See StasisApplication API" for detailed documentation.
Author
Jonathan Rose kharw.nosp@m.ell@.nosp@m.digiu.nosp@m.m.co.nosp@m.m
Since
12
Definition in file stasis_app_mailbox.h.
Enumeration Type Documentation
stasis_mailbox_result
enum stasis_mailbox_result
Stasis mailbox operation result codes
Enumerator
STASIS_MAILBOX_OK
Mailbox operation completed successfully
STASIS_MAILBOX_MISSING
Mailbox of the requested name does not exist
STASIS_MAILBOX_ERROR
Mailbox operation failed internally
Definition at line 37 of file stasis_app_mailbox.h.
{
    /*! Mailbox operation completed successfully */
    STASIS_MAILBOX_OK,
    /*! Mailbox of the requested name does not exist */
    STASIS_MAILBOX_MISSING,
    /*! Mailbox operation failed internally */
    STASIS_MAILBOX_ERROR,
 };
Function Documentation
stasis_app_mailbox_delete()
enum stasis_mailbox_result stasis_app_mailbox_delete (const char * name)
Delete a mailbox controlled by ARI.
Parameters
name the name of the ARI controlled mailbox
Returns
a stasis mailbox application result
Definition at line 122 of file res_stasis_mailbox.c.
References ast_mwi_mailbox_delete(), ast_mwi_mailbox_get(), ast_mwi_mailbox_unref, mailbox, NULL, STASIS_MAILBOX_ERROR, STASIS_MAILBOX_MISSING, and STASIS_MAILBOX_OK.
Referenced by ast_ari_mailboxes_delete().
 {
    const struct ast_mwi_mailbox_object *mailbox;
    /* Make sure the mailbox actually exists before we delete it */
    mailbox = ast_mwi_mailbox_get(name);
    if (!mailbox) {
       return STASIS_MAILBOX_MISSING;
    }
    ast_mwi_mailbox_unref(mailbox);
    mailbox = NULL;
    /* Now delete the mailbox */
    if (ast_mwi_mailbox_delete(name)) {
       return STASIS_MAILBOX_ERROR;
    }
    return STASIS_MAILBOX_OK;
 }
stasis_app_mailbox_to_json()
enum stasis_mailbox_result stasis_app_mailbox_to_json (const char * name, struct ast_json ** json)
Convert mailbox to JSON.
Parameters
name the name of the mailbox
json If the query is successful, this pointer at this address will be set to the JSON representation of the mailbox
Returns
stasis mailbox result code indicating success or failure and cause
NULL on error.
Definition at line 46 of file res_stasis_mailbox.c.
References ast_mwi_mailbox_get(), ast_mwi_mailbox_unref, mailbox, mailbox_to_json(), STASIS_MAILBOX_ERROR, STASIS_MAILBOX_MISSING, and STASIS_MAILBOX_OK.
Referenced by ast_ari_mailboxes_get().
 {
    struct ast_json *mailbox_json;
    const struct ast_mwi_mailbox_object *mailbox;
    mailbox = ast_mwi_mailbox_get(name);
    if (!mailbox) {
       return STASIS_MAILBOX_MISSING;
    }
    mailbox_json = mailbox_to_json(mailbox);
    if (!mailbox_json) {
       ast_mwi_mailbox_unref(mailbox);
       return STASIS_MAILBOX_ERROR;
    }
    *json = mailbox_json;
    return STASIS_MAILBOX_OK;
 }
stasis_app_mailbox_update()
int stasis_app_mailbox_update (const char * name, int old_messages, int new_messages)
Changes the state of a mailbox.
Note
Implicitly creates the mailbox.
Parameters
name The name of the ARI controlled mailbox
old_messages count of old (read) messages in the mailbox
new_messages count of new (unread) messages in the mailbox
Returns
0 if successful
-1 on internal error.
Definition at line 101 of file res_stasis_mailbox.c.
References ast_mwi_mailbox_alloc(), ast_mwi_mailbox_set_msgs_new(), ast_mwi_mailbox_set_msgs_old(), ast_mwi_mailbox_unref, ast_mwi_mailbox_update(), and mailbox.
Referenced by ast_ari_mailboxes_update().
 {
    struct ast_mwi_mailbox_object *mailbox;
    int res = 0;
    mailbox = ast_mwi_mailbox_alloc(name);
    if (!mailbox) {
       return -1;
    }
    ast_mwi_mailbox_set_msgs_new(mailbox, new_messages);
    ast_mwi_mailbox_set_msgs_old(mailbox, old_messages);
    if (ast_mwi_mailbox_update(mailbox)) {
       res = -1;
    }
    ast_mwi_mailbox_unref(mailbox);
    return res;
 }
stasis_app_mailboxes_to_json()
struct ast_json* stasis_app_mailboxes_to_json (void)
brief Convert mailboxes to json array
Returns
JSON representation of the mailboxes
NULL on error.
Definition at line 68 of file res_stasis_mailbox.c.
References ao2_iterator_destroy(), ao2_iterator_init(), ao2_iterator_next, ao2_ref, array(), ast_json_array_append(), ast_json_array_create(), ast_json_unref(), ast_mwi_mailbox_get_all(), ast_mwi_mailbox_unref, mailbox, mailbox_to_json(), mailboxes, and NULL.
Referenced by ast_ari_mailboxes_list().
 {
    struct ast_json *array = ast_json_array_create();
    struct ao2_container *mailboxes;
    struct ao2_iterator iter;
    const struct ast_mwi_mailbox_object *mailbox;
    if (!array) {
       return NULL;
    }
    mailboxes = ast_mwi_mailbox_get_all();
    if (!mailboxes) {
       ast_json_unref(array);
       return NULL;
    }
    iter = ao2_iterator_init(mailboxes, 0);
    for (; (mailbox = ao2_iterator_next(&iter)); ast_mwi_mailbox_unref(mailbox)) {
       struct ast_json *appending = mailbox_to_json(mailbox);
       if (!appending || ast_json_array_append(array, appending)) {
          /* Failed to append individual mailbox to the array. Abort. */
          ast_json_unref(array);
          array = NULL;
          break;
       }
    }
    ao2_iterator_destroy(&iter);
    ao2_ref(mailboxes, -1);
    return array;
 }