Asterisk - The Open Source Telephony Project: resource_sounds.c File Reference
resource_sounds.c File Reference
/api-docs/sounds.{format} implementation- Sound resources
#include "asterisk.h"
#include "resource_sounds.h"
#include "asterisk/media_index.h"
#include "asterisk/sounds_index.h"
#include "asterisk/format.h"
#include "asterisk/format_cap.h"
#include "asterisk/json.h"
Data Structures
struct lang_format_info
arguments that are necessary for adding format/lang pairs
struct sounds_cb_data
Functions
static int add_format_information_cb (void *obj, void *arg, void *data, int flags)
Add format/lang pairs to the array embedded in the sound object.
static int append_sound_cb (void *obj, void *arg, void *data, int flags)
Generate a Sound structure and append it to the output blob.
void ast_ari_sounds_get (struct ast_variable *headers, struct ast_ari_sounds_get_args *args, struct ast_ari_response *response)
Get a sound's details.
void ast_ari_sounds_list (struct ast_variable *headers, struct ast_ari_sounds_list_args *args, struct ast_ari_response *response)
List all sounds.
static struct ast_json * create_sound_blob (const char *filename, struct ast_ari_sounds_list_args *args, struct ast_media_index *sounds_index)
Generate a Sound structure as documented in sounds.json for the specified filename.
static int filter_langs_cb (void *obj, void *arg, int flags)
Filter out all languages not matching the specified language.
Detailed Description
/api-docs/sounds.{format} implementation- Sound resources
Author
David M. Lee, II dlee@.nosp@m.digi.nosp@m.um.co.nosp@m.m
Definition in file resource_sounds.c.
Function Documentation
add_format_information_cb()
static int add_format_information_cb (void * obj, void * arg, void * data, int flags) static
Add format/lang pairs to the array embedded in the sound object.
Definition at line 43 of file resource_sounds.c.
References ao2_cleanup, ao2_ref, args, ast_format_cap_count(), ast_format_cap_get_format(), ast_format_get_name(), ast_json_array_append(), ast_json_pack(), ast_media_get_format_cap(), ast_strlen_zero, CMP_STOP, lang_format_info::filename, format, lang_format_info::format_filter, lang_format_info::format_list, language, NULL, and RAII_VAR.
Referenced by create_sound_blob().
 {
    char *language = obj;
    struct lang_format_info *args = arg;
    int idx;
    RAII_VAR(struct ast_format_cap *, cap, NULL, ao2_cleanup);
    struct ast_media_index *sounds_index = data;
    if (!sounds_index) {
       return CMP_STOP;
    }
    cap = ast_media_get_format_cap(sounds_index, args->filename, language);
    if (!cap) {
       return CMP_STOP;
    }
    for (idx = 0; idx < ast_format_cap_count(cap); idx++) {
       struct ast_format *format = ast_format_cap_get_format(cap, idx);
       struct ast_json *lang_format_pair;
       if (!ast_strlen_zero(args->format_filter)
          && strcmp(args->format_filter, ast_format_get_name(format))) {
          ao2_ref(format, -1);
          continue;
       }
       lang_format_pair = ast_json_pack("{s: s, s: s}",
          "language", language,
          "format", ast_format_get_name(format));
       if (!lang_format_pair) {
          ao2_ref(format, -1);
          return CMP_STOP;
       }
       ast_json_array_append(args->format_list, lang_format_pair);
       ao2_ref(format, -1);
    }
    return 0;
 }
append_sound_cb()
static int append_sound_cb (void * obj, void * arg, void * data, int flags) static
Generate a Sound structure and append it to the output blob.
Definition at line 166 of file resource_sounds.c.
References sounds_cb_data::args, ast_json_array_append(), create_sound_blob(), lang_format_info::filename, and sounds_cb_data::index.
Referenced by ast_ari_sounds_list().
 {
    struct ast_json *sounds_array = arg;
    char *filename = obj;
    struct sounds_cb_data *cb_data = data;
    struct ast_json *sound_blob = create_sound_blob(filename, cb_data->args, cb_data->index);
    if (!sound_blob) {
       return 0;
    }
    ast_json_array_append(sounds_array, sound_blob);
    return 0;
 }
ast_ari_sounds_get()
void ast_ari_sounds_get (struct ast_variable * headers, struct ast_ari_sounds_get_args * args, struct ast_ari_response * response)
Get a sound's details.
Parameters
headers HTTP headers
args Swagger parameters
[out] response HTTP response
Definition at line 220 of file resource_sounds.c.
References ao2_cleanup, ast_ari_response_error(), ast_ari_response_ok(), ast_sounds_get_index_for_file(), create_sound_blob(), NULL, and ast_ari_sounds_get_args::sound_id.
Referenced by ast_ari_sounds_get_cb().
 {
    struct ast_json *sound_blob;
    struct ast_media_index *sounds_index = ast_sounds_get_index_for_file(args->sound_id);
    sound_blob = create_sound_blob(args->sound_id, NULL, sounds_index);
    ao2_cleanup(sounds_index);
    if (!sound_blob) {
       ast_ari_response_error(response, 404, "Not Found", "Sound not found");
       return;
    }
    ast_ari_response_ok(response, sound_blob);
 }
ast_ari_sounds_list()
void ast_ari_sounds_list (struct ast_variable * headers, struct ast_ari_sounds_list_args * args, struct ast_ari_response * response)
List all sounds.
Parameters
headers HTTP headers
args Swagger parameters
[out] response HTTP response
Definition at line 180 of file resource_sounds.c.
References ao2_callback_data, ao2_cleanup, append_sound_cb(), args, sounds_cb_data::args, ast_ari_response_error(), ast_ari_response_ok(), ast_json_array_create(), ast_json_array_size(), ast_json_unref(), ast_media_get_media(), ast_sounds_get_index(), NULL, OBJ_NODATA, and RAII_VAR.
Referenced by ast_ari_sounds_list_cb().
 {
    RAII_VAR(struct ao2_container *, sound_files, NULL, ao2_cleanup);
    struct ast_json *sounds_blob;
    RAII_VAR(struct ast_media_index *, sounds_index, ast_sounds_get_index(), ao2_cleanup);
    struct sounds_cb_data cb_data = {
       .args = args,
       .index = sounds_index,
    };
    if (!sounds_index) {
       ast_ari_response_error(response, 500, "Internal Error", "Sounds index not available");
       return;
    }
    sound_files = ast_media_get_media(sounds_index);
    if (!sound_files) {
       ast_ari_response_error(response, 500, "Internal Error", "Allocation Error");
       return;
    }
    sounds_blob = ast_json_array_create();
    if (!sounds_blob) {
       ast_ari_response_error(response, 500, "Internal Error", "Allocation Error");
       return;
    }
    ao2_callback_data(sound_files, OBJ_NODATA, append_sound_cb, sounds_blob, &cb_data);
    if (!ast_json_array_size(sounds_blob)) {
       ast_ari_response_error(response, 404, "Not Found", "No sounds found that matched the query");
       ast_json_unref(sounds_blob);
       return;
    }
    ast_ari_response_ok(response, sounds_blob);
 }
create_sound_blob()
static struct ast_json* create_sound_blob (const char * filename, struct ast_ari_sounds_list_args * args, struct ast_media_index * sounds_index) static
Generate a Sound structure as documented in sounds.json for the specified filename.
Definition at line 97 of file resource_sounds.c.
References add_format_information_cb(), ao2_callback, ao2_callback_data, ao2_cleanup, ao2_container_count(), ast_json_array_size(), ast_json_object_get(), ast_json_pack(), ast_json_ref(), ast_json_unref(), ast_media_get_description(), ast_media_get_variants(), ast_strdupa, ast_strlen_zero, lang_format_info::filename, filter_langs_cb(), ast_ari_sounds_list_args::format, lang_format_info::format_filter, lang_format_info::format_list, ast_ari_sounds_list_args::lang, NULL, OBJ_MULTIPLE, OBJ_NODATA, OBJ_UNLINK, and RAII_VAR.
Referenced by append_sound_cb(), and ast_ari_sounds_get().
 {
    RAII_VAR(struct ast_json *, sound, NULL, ast_json_unref);
    RAII_VAR(struct ao2_container *, languages, NULL, ao2_cleanup);
    const char *description;
    struct ast_json *format_lang_list;
    struct lang_format_info info;
    if (!sounds_index) {
       return NULL;
    }
    description = ast_media_get_description(sounds_index, filename, "en");
    if (ast_strlen_zero(description)) {
       sound = ast_json_pack("{s: s, s: []}",
          "id", filename,
          "formats");
    } else {
       sound = ast_json_pack("{s: s, s: s, s: []}",
          "id", filename,
          "text", description,
          "formats");
    }
    if (!sound) {
       return NULL;
    }
    format_lang_list = ast_json_object_get(sound, "formats");
    if (!format_lang_list) {
       return NULL;
    }
    languages = ast_media_get_variants(sounds_index, filename);
    if (!languages || !ao2_container_count(languages)) {
       return NULL;
    }
    /* filter requested languages */
    if (args && !ast_strlen_zero(args->lang)) {
       char *lang_filter = ast_strdupa(args->lang);
       ao2_callback(languages, OBJ_NODATA | OBJ_MULTIPLE | OBJ_UNLINK, filter_langs_cb, lang_filter);
       if (!languages || !ao2_container_count(languages)) {
          return NULL;
       }
    }
    info.filename = filename;
    info.format_list = format_lang_list;
    info.format_filter = NULL;
    if (args) {
       info.format_filter = args->format;
    }
    ao2_callback_data(languages, OBJ_NODATA, add_format_information_cb, &info, sounds_index);
    /* no format/lang pairs for this sound so nothing to return */
    if (!ast_json_array_size(format_lang_list)) {
       return NULL;
    }
    return ast_json_ref(sound);
 }
filter_langs_cb()
static int filter_langs_cb (void * obj, void * arg, int flags) static
Filter out all languages not matching the specified language.
Definition at line 86 of file resource_sounds.c.
References CMP_MATCH.
Referenced by create_sound_blob().
 {
    char *lang_filter = arg;
    char *lang = obj;
    if (strcmp(lang, lang_filter)) {
       return CMP_MATCH;
    }
    return 0;
 }