Asterisk - The Open Source Telephony Project: resource_device_states.h File Reference
resource_device_states.h File Reference
Generated file - declares stubs to be implemented in res/ari/resource_deviceStates.c.
#include "asterisk/ari.h"
Data Structures
struct ast_ari_device_states_delete_args
struct ast_ari_device_states_get_args
struct ast_ari_device_states_list_args
struct ast_ari_device_states_update_args
Functions
void ast_ari_device_states_delete (struct ast_variable *headers, struct ast_ari_device_states_delete_args *args, struct ast_ari_response *response)
Destroy a device-state controlled by ARI.
void ast_ari_device_states_get (struct ast_variable *headers, struct ast_ari_device_states_get_args *args, struct ast_ari_response *response)
Retrieve the current state of a device.
void ast_ari_device_states_list (struct ast_variable *headers, struct ast_ari_device_states_list_args *args, struct ast_ari_response *response)
List all ARI controlled device states.
void ast_ari_device_states_update (struct ast_variable *headers, struct ast_ari_device_states_update_args *args, struct ast_ari_response *response)
Change the state of a device controlled by ARI. (Note - implicitly creates the device state).
int ast_ari_device_states_update_parse_body (struct ast_json *body, struct ast_ari_device_states_update_args *args)
Body parsing function for /deviceStates/{deviceName}.
Detailed Description
Generated file - declares stubs to be implemented in res/ari/resource_deviceStates.c.
Device state resources
Author
Kevin Harwell kharw.nosp@m.ell@.nosp@m.digiu.nosp@m.m.co.nosp@m.m
Definition in file resource_device_states.h.
Function Documentation
ast_ari_device_states_delete()
void ast_ari_device_states_delete (struct ast_variable * headers, struct ast_ari_device_states_delete_args * args, struct ast_ari_response * response)
Destroy a device-state controlled by ARI.
Parameters
headers HTTP headers
args Swagger parameters
[out] response HTTP response
Definition at line 91 of file resource_device_states.c.
References ast_ari_response_error(), ast_ari_response_no_content(), ast_ari_device_states_delete_args::device_name, stasis_app_device_state_delete(), STASIS_DEVICE_STATE_MISSING, STASIS_DEVICE_STATE_NOT_CONTROLLED, STASIS_DEVICE_STATE_OK, STASIS_DEVICE_STATE_SUBSCRIBERS, and STASIS_DEVICE_STATE_UNKNOWN.
Referenced by ast_ari_device_states_delete_cb().
 {
    switch (stasis_app_device_state_delete(args->device_name)) {
    case STASIS_DEVICE_STATE_NOT_CONTROLLED:
       ast_ari_response_error(response, 409,
          "Conflict", "Uncontrolled device specified");
       return;
    case STASIS_DEVICE_STATE_MISSING:
       ast_ari_response_error(response, 404,
          "Not Found", "Device name is missing");
       return;
    case STASIS_DEVICE_STATE_SUBSCRIBERS:
       ast_ari_response_error(response, 500,
          "Internal Server Error",
          "Cannot delete device with subscribers");
       return;
    case STASIS_DEVICE_STATE_OK:
    case STASIS_DEVICE_STATE_UNKNOWN:
       ast_ari_response_no_content(response);
    }
 }
ast_ari_device_states_get()
void ast_ari_device_states_get (struct ast_variable * headers, struct ast_ari_device_states_get_args * args, struct ast_ari_response * response)
Retrieve the current state of a device.
Parameters
headers HTTP headers
args Swagger parameters
[out] response HTTP response
Definition at line 51 of file resource_device_states.c.
References ast_ari_response_error(), ast_ari_response_ok(), ast_ari_device_states_get_args::device_name, and stasis_app_device_state_to_json().
Referenced by ast_ari_device_states_get_cb().
 {
    struct ast_json *json;
    if (!(json = stasis_app_device_state_to_json(
             args->device_name, ast_device_state(args->device_name)))) {
       ast_ari_response_error(response, 500,
          "Internal Server Error", "Error building response");
       return;
    }
    ast_ari_response_ok(response, json);
 }
ast_ari_device_states_list()
void ast_ari_device_states_list (struct ast_variable * headers, struct ast_ari_device_states_list_args * args, struct ast_ari_response * response)
List all ARI controlled device states.
Parameters
headers HTTP headers
args Swagger parameters
[out] response HTTP response
Definition at line 35 of file resource_device_states.c.
References ast_ari_response_error(), ast_ari_response_ok(), and stasis_app_device_states_to_json().
Referenced by ast_ari_device_states_list_cb().
 {
    struct ast_json *json;
    if (!(json = stasis_app_device_states_to_json())) {
       ast_ari_response_error(response, 500,
          "Internal Server Error", "Error building response");
       return;
    }
    ast_ari_response_ok(response, json);
 }
ast_ari_device_states_update()
void ast_ari_device_states_update (struct ast_variable * headers, struct ast_ari_device_states_update_args * args, struct ast_ari_response * response)
Change the state of a device controlled by ARI. (Note - implicitly creates the device state).
Parameters
headers HTTP headers
args Swagger parameters
[out] response HTTP response
Definition at line 67 of file resource_device_states.c.
References ast_ari_response_error(), ast_ari_response_no_content(), ast_ari_device_states_update_args::device_name, ast_ari_device_states_update_args::device_state, stasis_app_device_state_update(), STASIS_DEVICE_STATE_MISSING, STASIS_DEVICE_STATE_NOT_CONTROLLED, STASIS_DEVICE_STATE_OK, STASIS_DEVICE_STATE_SUBSCRIBERS, and STASIS_DEVICE_STATE_UNKNOWN.
Referenced by ast_ari_device_states_update_cb().
 {
    switch (stasis_app_device_state_update(
          args->device_name, args->device_state)) {
    case STASIS_DEVICE_STATE_NOT_CONTROLLED:
       ast_ari_response_error(response, 409,
          "Conflict", "Uncontrolled device specified");
       return;
    case STASIS_DEVICE_STATE_MISSING:
       ast_ari_response_error(response, 404,
          "Not Found", "Device name is missing");
       return;
    case STASIS_DEVICE_STATE_UNKNOWN:
       ast_ari_response_error(response, 500, "Internal Server Error",
                    "Unknown device");
       return;
    case STASIS_DEVICE_STATE_OK:
    case STASIS_DEVICE_STATE_SUBSCRIBERS: /* shouldn't be returned for update */
       ast_ari_response_no_content(response);
    }
 }
ast_ari_device_states_update_parse_body()
int ast_ari_device_states_update_parse_body (struct ast_json * body, struct ast_ari_device_states_update_args * args)
Body parsing function for /deviceStates/{deviceName}.
Parameters
body The JSON body from which to parse parameters.
[out] args The args structure to parse into.
Return values
zero on success
non-zero on failure
Definition at line 161 of file res_ari_device_states.c.
References ast_json_object_get(), ast_json_string_get(), and ast_ari_device_states_update_args::device_state.
Referenced by ast_ari_device_states_update_cb().
 {
    struct ast_json *field;
    /* Parse query parameters out of it */
    field = ast_json_object_get(body, "deviceState");
    if (field) {
       args->device_state = ast_json_string_get(field);
    }
    return 0;
 }