Asterisk - The Open Source Telephony Project: dns_srv.h File Reference
dns_srv.h File Reference
DNS SRV Record Parsing API.
Functions
const char * ast_dns_srv_get_host (const struct ast_dns_record *record)
Get the hostname from an SRV record.
unsigned short ast_dns_srv_get_port (const struct ast_dns_record *record)
Get the port from an SRV record.
unsigned short ast_dns_srv_get_priority (const struct ast_dns_record *record)
Get the priority from an SRV record.
unsigned short ast_dns_srv_get_weight (const struct ast_dns_record *record)
Get the weight from an SRV record.
Detailed Description
DNS SRV Record Parsing API.
Author
Joshua Colp jcolp.nosp@m.@dig.nosp@m.ium.c.nosp@m.om
Definition in file dns_srv.h.
Function Documentation
ast_dns_srv_get_host()
const char* ast_dns_srv_get_host (const struct ast_dns_record * record)
Get the hostname from an SRV record.
Parameters
record The DNS record
Returns
the hostname
Definition at line 188 of file dns_srv.c.
References ast_assert, ast_dns_record_get_rr_type(), and ast_dns_srv_record::host.
Referenced by AST_TEST_DEFINE(), nominal_test(), and sip_resolve_callback().
 {
    struct ast_dns_srv_record *srv = (struct ast_dns_srv_record *) record;
    ast_assert(ast_dns_record_get_rr_type(record) == T_SRV);
    return srv->host;
 }
ast_dns_srv_get_port()
unsigned short ast_dns_srv_get_port (const struct ast_dns_record * record)
Get the port from an SRV record.
Parameters
record The DNS record
Returns
the port
Definition at line 212 of file dns_srv.c.
References ast_assert, ast_dns_record_get_rr_type(), and ast_dns_srv_record::port.
Referenced by AST_TEST_DEFINE(), nominal_test(), and sip_resolve_callback().
 {
    struct ast_dns_srv_record *srv = (struct ast_dns_srv_record *) record;
    ast_assert(ast_dns_record_get_rr_type(record) == T_SRV);
    return srv->port;
 }
ast_dns_srv_get_priority()
unsigned short ast_dns_srv_get_priority (const struct ast_dns_record * record)
Get the priority from an SRV record.
Parameters
record The DNS record
Returns
the priority
Definition at line 196 of file dns_srv.c.
References ast_assert, ast_dns_record_get_rr_type(), and ast_dns_srv_record::priority.
Referenced by AST_TEST_DEFINE(), and nominal_test().
 {
    struct ast_dns_srv_record *srv = (struct ast_dns_srv_record *) record;
    ast_assert(ast_dns_record_get_rr_type(record) == T_SRV);
    return srv->priority;
 }
ast_dns_srv_get_weight()
unsigned short ast_dns_srv_get_weight (const struct ast_dns_record * record)
Get the weight from an SRV record.
Parameters
record The DNS record
Returns
the weight
Definition at line 204 of file dns_srv.c.
References ast_assert, ast_dns_record_get_rr_type(), and ast_dns_srv_record::weight.
Referenced by AST_TEST_DEFINE(), and nominal_test().
 {
    struct ast_dns_srv_record *srv = (struct ast_dns_srv_record *) record;
    ast_assert(ast_dns_record_get_rr_type(record) == T_SRV);
    return srv->weight;
 }