Asterisk - The Open Source Telephony Project: codec_speex.c File Reference
codec_speex.c File Reference
Module: Codecs
Translate between signed linear and Speex (Open Codec)
#include "asterisk.h"
#include <speex/speex.h>
#include "asterisk/translate.h"
#include "asterisk/module.h"
#include "asterisk/config.h"
#include "asterisk/utils.h"
#include "asterisk/frame.h"
#include "asterisk/linkedlists.h"
#include "asterisk/rtp_engine.h"
#include "asterisk/slin.h"
#include "ex_speex.h"
Data Structures
struct speex_coder_pvt
Macros
#define BUFFER_SAMPLES 8000
#define SPEEX_SAMPLES 160
#define TYPE_HIGH 0x0
#define TYPE_LOW 0x1
#define TYPE_MASK 0x3
#define TYPE_SILENCE 0x2
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int lin16tospeexwb_new (struct ast_trans_pvt *pvt)
static int lin32tospeexuwb_new (struct ast_trans_pvt *pvt)
static void lintospeex_destroy (struct ast_trans_pvt *arg)
static void lintospeex_feedback (struct ast_trans_pvt *pvt, struct ast_frame *feedback)
handle incoming RTCP feedback and possibly edit encoder settings
static int lintospeex_framein (struct ast_trans_pvt *pvt, struct ast_frame *f)
store input frame in work buffer
static struct ast_frame * lintospeex_frameout (struct ast_trans_pvt *pvt)
convert work buffer and produce output frame
static int lintospeex_new (struct ast_trans_pvt *pvt)
static int load_module (void)
static int parse_config (int reload)
static int reload (void)
static int speex_decoder_construct (struct ast_trans_pvt *pvt, const SpeexMode *profile)
static int speex_encoder_construct (struct ast_trans_pvt *pvt, const SpeexMode *profile, int sampling_rate)
static void speextolin_destroy (struct ast_trans_pvt *arg)
static int speextolin_framein (struct ast_trans_pvt *pvt, struct ast_frame *f)
convert and store into outbuf
static int speextolin_new (struct ast_trans_pvt *pvt)
static int speexuwbtolin32_new (struct ast_trans_pvt *pvt)
static int speexwbtolin16_new (struct ast_trans_pvt *pvt)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_DEFAULT , .description = "Speex Coder/Decoder" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .reload = reload, }
static int abr = 0
static const struct ast_module_info * ast_module_info = &__mod_info
static int complexity = 2
static int dtx = 0
static int enhancement = 0
static int exp_rtcp_fb = 0
static struct ast_translator lin16tospeexwb
static struct ast_translator lin32tospeexuwb
static struct ast_translator lintospeex
static int pp_agc = 0
static float pp_agc_level = 8000
static int pp_denoise = 0
static int pp_dereverb = 0
static float pp_dereverb_decay = 0.4
static float pp_dereverb_level = 0.3
static int pp_vad = 0
static int preproc = 0
static int quality = 3
static struct ast_translator speextolin
static struct ast_translator speexuwbtolin32
static struct ast_translator speexwbtolin16
static int vad = 0
static int vbr = 0
static float vbr_quality = 4
Detailed Description
Translate between signed linear and Speex (Open Codec)
Note
This work was motivated by Jeremy McNamara hacked to be configurable by anthm and bkw 9/28/2004
The Speex library - http://www.speex.org
Definition in file codec_speex.c.
Macro Definition Documentation
BUFFER_SAMPLES
#define BUFFER_SAMPLES 8000
Definition at line 86 of file codec_speex.c.
Referenced by speextolin_framein().
SPEEX_SAMPLES
#define SPEEX_SAMPLES 160
Definition at line 87 of file codec_speex.c.
Referenced by speex16_sample(), and speex_sample().
TYPE_HIGH
#define TYPE_HIGH 0x0
Definition at line 82 of file codec_speex.c.
TYPE_LOW
#define TYPE_LOW 0x1
Definition at line 83 of file codec_speex.c.
TYPE_MASK
#define TYPE_MASK 0x3
Definition at line 84 of file codec_speex.c.
TYPE_SILENCE
#define TYPE_SILENCE 0x2
Definition at line 81 of file codec_speex.c.
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 730 of file codec_speex.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 730 of file codec_speex.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 730 of file codec_speex.c.
lin16tospeexwb_new()
static int lin16tospeexwb_new (struct ast_trans_pvt * pvt) static
Definition at line 162 of file codec_speex.c.
References speex_encoder_construct().
 {
    return speex_encoder_construct(pvt, &speex_wb_mode, 16000);
 }
lin32tospeexuwb_new()
static int lin32tospeexuwb_new (struct ast_trans_pvt * pvt) static
Definition at line 167 of file codec_speex.c.
References speex_encoder_construct().
 {
    return speex_encoder_construct(pvt, &speex_uwb_mode, 32000);
 }
lintospeex_destroy()
static void lintospeex_destroy (struct ast_trans_pvt * arg) static
Definition at line 435 of file codec_speex.c.
References speex_coder_pvt::bits, preproc, ast_trans_pvt::pvt, and speex_coder_pvt::speex.
 {
    struct speex_coder_pvt *pvt = arg->pvt;
 #ifdef _SPEEX_TYPES_H
    if (preproc)
       speex_preprocess_state_destroy(pvt->pp);
 #endif
    speex_encoder_destroy(pvt->speex);
    speex_bits_destroy(&pvt->bits);
 }
lintospeex_feedback()
static void lintospeex_feedback (struct ast_trans_pvt * pvt, struct ast_frame * feedback) static
handle incoming RTCP feedback and possibly edit encoder settings
Definition at line 360 of file codec_speex.c.
References ast_debug, AST_RTP_RTCP_RR, AST_RTP_RTCP_SR, ast_frame::data, speex_coder_pvt::default_quality, exp_rtcp_fb, ast_rtp_rtcp_report_block::fraction, speex_coder_pvt::fraction_lost, if(), ast_frame_subclass::integer, ast_rtp_rtcp_report_block::lost_count, ast_frame::ptr, ast_trans_pvt::pvt, speex_coder_pvt::quality, ast_rtp_rtcp_report::reception_report_count, ast_rtp_rtcp_report::report_block, speex_coder_pvt::speex, ast_frame::subclass, tmp(), and vbr.
 {
    struct speex_coder_pvt *tmp = pvt->pvt;
    struct ast_rtp_rtcp_report *rtcp_report;
    struct ast_rtp_rtcp_report_block *report_block;
    int fraction_lost;
    int percent;
    int bitrate;
    int q;
    if(!exp_rtcp_fb)
       return;
    /* We only accept feedback information in the form of SR and RR reports */
    if (feedback->subclass.integer != AST_RTP_RTCP_SR && feedback->subclass.integer != AST_RTP_RTCP_RR) {
       return;
    }
    rtcp_report = (struct ast_rtp_rtcp_report *)feedback->data.ptr;
    if (rtcp_report->reception_report_count == 0)
       return;
    report_block = rtcp_report->report_block[0];
    fraction_lost = report_block->lost_count.fraction;
    if (fraction_lost == tmp->fraction_lost)
       return;
    /* Per RFC3550, fraction lost is defined to be the number of packets lost
     * divided by the number of packets expected. Since it's a 8-bit value,
     * and we want a percentage value, we multiply by 100 and divide by 256. */
    percent = (fraction_lost*100)/256;
    bitrate = 0;
    q = -1;
    ast_debug(3, "Fraction lost changed: %d --> %d percent loss\n", fraction_lost, percent);
    /* Handle change */
    speex_encoder_ctl(tmp->speex, SPEEX_GET_BITRATE, &bitrate);
    ast_debug(3, "Current bitrate: %d\n", bitrate);
    ast_debug(3, "Current quality: %d/%d\n", tmp->quality, tmp->default_quality);
    /* FIXME BADLY Very ugly example of how this could be handled: probably sucks */
    if (percent < 10) {
       /* Not that bad, default quality is fine */
       q = tmp->default_quality;
    } else if (percent < 20) {
       /* Quite bad, let's go down a bit */
       q = tmp->default_quality-1;
    } else if (percent < 30) {
       /* Very bad, let's go down even more */
       q = tmp->default_quality-2;
    } else {
       /* Really bad, use the lowest quality possible */
       q = 0;
    }
    if (q < 0)
       q = 0;
    if (q != tmp->quality) {
       ast_debug(3, "  -- Setting to %d\n", q);
       if (vbr) {
          float vbr_q = q;
          speex_encoder_ctl(tmp->speex, SPEEX_SET_VBR_QUALITY, &vbr_q);
       } else {
          speex_encoder_ctl(tmp->speex, SPEEX_SET_QUALITY, &q);
       }
       tmp->quality = q;
    }
    tmp->fraction_lost = fraction_lost;
 }
lintospeex_framein()
static int lintospeex_framein (struct ast_trans_pvt * pvt, struct ast_frame * f) static
store input frame in work buffer
Definition at line 260 of file codec_speex.c.
References speex_coder_pvt::buf, ast_frame::data, ast_frame::datalen, ast_frame::ptr, ast_trans_pvt::pvt, ast_frame::samples, ast_trans_pvt::samples, and tmp().
 {
    struct speex_coder_pvt *tmp = pvt->pvt;
    /* XXX We should look at how old the rest of our stream is, and if it
       is too old, then we should overwrite it entirely, otherwise we can
       get artifacts of earlier talk that do not belong */
    memcpy(tmp->buf + pvt->samples, f->data.ptr, f->datalen);
    pvt->samples += f->samples;
    return 0;
 }
lintospeex_frameout()
static struct ast_frame* lintospeex_frameout (struct ast_trans_pvt * pvt) static
convert work buffer and produce output frame
Definition at line 273 of file codec_speex.c.
References AST_FRAME_CNG, ast_frisolate, AST_LIST_NEXT, ast_trans_frameout(), speex_coder_pvt::bits, speex_coder_pvt::buf, ast_translator::buf_size, ast_trans_pvt::c, ast_frame::datalen, dtx, speex_coder_pvt::framesize, ast_frame::frametype, last, ast_translator::name, NULL, ast_trans_pvt::outbuf, preproc, ast_trans_pvt::pvt, result, ast_frame::samples, ast_trans_pvt::samples, speex_coder_pvt::silent_state, speex_coder_pvt::speex, ast_trans_pvt::t, and tmp().
 {
    struct speex_coder_pvt *tmp = pvt->pvt;
    struct ast_frame *result = NULL;
    struct ast_frame *last = NULL;
    int samples = 0; /* output samples */
    while (pvt->samples >= tmp->framesize) {
       struct ast_frame *current;
       int is_speech = 1;
       speex_bits_reset(&tmp->bits);
 #ifdef _SPEEX_TYPES_H
       /* Preprocess audio */
       if (preproc)
          is_speech = speex_preprocess(tmp->pp, tmp->buf + samples, NULL);
       /* Encode a frame of data */
       if (is_speech) {
          /* If DTX enabled speex_encode returns 0 during silence */
          is_speech = speex_encode_int(tmp->speex, tmp->buf + samples, &tmp->bits) || !dtx;
       } else {
          /* 5 zeros interpreted by Speex as silence (submode 0) */
          speex_bits_pack(&tmp->bits, 0, 5);
       }
 #else
       {
          float fbuf[1024];
          int x;
          /* Convert to floating point */
          for (x = 0; x < tmp->framesize; x++)
             fbuf[x] = tmp->buf[samples + x];
          /* Encode a frame of data */
          is_speech = speex_encode(tmp->speex, fbuf, &tmp->bits) || !dtx;
       }
 #endif
       samples += tmp->framesize;
       pvt->samples -= tmp->framesize;
       /* Use AST_FRAME_CNG to signify the start of any silence period */
       if (is_speech) {
          int datalen = 0; /* output bytes */
          tmp->silent_state = 0;
          /* Terminate bit stream */
          speex_bits_pack(&tmp->bits, 15, 5);
          datalen = speex_bits_write(&tmp->bits, pvt->outbuf.c, pvt->t->buf_size);
          current = ast_trans_frameout(pvt, datalen, tmp->framesize);
       } else if (tmp->silent_state) {
          current = NULL;
       } else {
          struct ast_frame frm = {
             .frametype = AST_FRAME_CNG,
             .src = pvt->t->name,
          };
          /*
           * XXX I don't think the AST_FRAME_CNG code has ever
           * really worked for speex.  There doesn't seem to be
           * any consumers of the frame type.  Everyone that
           * references the type seems to pass the frame on.
           */
          tmp->silent_state = 1;
          /* XXX what now ? format etc... */
          current = ast_frisolate(&frm);
       }
       if (!current) {
          continue;
       } else if (last) {
          AST_LIST_NEXT(last, frame_list) = current;
       } else {
          result = current;
       }
       last = current;
    }
    /* Move the data at the end of the buffer to the front */
    if (samples) {
       memmove(tmp->buf, tmp->buf + samples, pvt->samples * 2);
    }
    return result;
 }
lintospeex_new()
static int lintospeex_new (struct ast_trans_pvt * pvt) static
Definition at line 157 of file codec_speex.c.
References speex_encoder_construct().
 {
    return speex_encoder_construct(pvt, &speex_nb_mode, 8000);
 }
load_module()
static int load_module (void) static
Definition at line 702 of file codec_speex.c.
References AST_MODFLAG_DEFAULT, AST_MODULE_INFO(), AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, AST_MODULE_SUPPORT_CORE, ast_register_translator, ASTERISK_GPL_KEY, parse_config(), reload(), and unload_module().
 {
    int res = 0;
    if (parse_config(0)) {
       return AST_MODULE_LOAD_DECLINE;
    }
    /* XXX It is most likely a bug in this module if we fail to register a translator */
    res |= ast_register_translator(&speextolin);
    res |= ast_register_translator(&lintospeex);
    res |= ast_register_translator(&speexwbtolin16);
    res |= ast_register_translator(&lin16tospeexwb);
    res |= ast_register_translator(&speexuwbtolin32);
    res |= ast_register_translator(&lin32tospeexuwb);
    if (res) {
       unload_module();
       return AST_MODULE_LOAD_DECLINE;
    }
    return AST_MODULE_LOAD_SUCCESS;
 }
parse_config()
static int parse_config (int reload) static
Definition at line 585 of file codec_speex.c.
References abr, abs, ast_config_destroy(), ast_config_load, ast_log, ast_true(), ast_variable_browse(), ast_verb, complexity, CONFIG_FLAG_FILEUNCHANGED, CONFIG_STATUS_FILEINVALID, CONFIG_STATUS_FILEMISSING, CONFIG_STATUS_FILEUNCHANGED, dtx, enhancement, exp_rtcp_fb, LOG_ERROR, ast_variable::name, ast_variable::next, pp_agc, pp_agc_level, pp_denoise, pp_dereverb, pp_dereverb_decay, pp_dereverb_level, pp_vad, preproc, speex_coder_pvt::quality, vad, ast_variable::value, var, vbr, and vbr_quality.
Referenced by load_module(), and reload().
 {
    struct ast_flags config_flags = { reload ? CONFIG_FLAG_FILEUNCHANGED : 0 };
    struct ast_config *cfg = ast_config_load("codecs.conf", config_flags);
    struct ast_variable *var;
    int res;
    float res_f;
    if (cfg == CONFIG_STATUS_FILEMISSING || cfg == CONFIG_STATUS_FILEUNCHANGED || cfg == CONFIG_STATUS_FILEINVALID)
       return 0;
    for (var = ast_variable_browse(cfg, "speex"); var; var = var->next) {
       if (!strcasecmp(var->name, "quality")) {
          res = abs(atoi(var->value));
          if (res > -1 && res < 11) {
             ast_verb(3, "CODEC SPEEX: Setting Quality to %d\n",res);
             quality = res;
          } else
             ast_log(LOG_ERROR,"Error Quality must be 0-10\n");
       } else if (!strcasecmp(var->name, "complexity")) {
          res = abs(atoi(var->value));
          if (res > -1 && res < 11) {
             ast_verb(3, "CODEC SPEEX: Setting Complexity to %d\n",res);
             complexity = res;
          } else
             ast_log(LOG_ERROR,"Error! Complexity must be 0-10\n");
       } else if (!strcasecmp(var->name, "vbr_quality")) {
          if (sscanf(var->value, "%30f", &res_f) == 1 && res_f >= 0 && res_f <= 10) {
             ast_verb(3, "CODEC SPEEX: Setting VBR Quality to %f\n",res_f);
             vbr_quality = res_f;
          } else
             ast_log(LOG_ERROR,"Error! VBR Quality must be 0-10\n");
       } else if (!strcasecmp(var->name, "abr_quality")) {
          ast_log(LOG_ERROR,"Error! ABR Quality setting obsolete, set ABR to desired bitrate\n");
       } else if (!strcasecmp(var->name, "enhancement")) {
          enhancement = ast_true(var->value) ? 1 : 0;
          ast_verb(3, "CODEC SPEEX: Perceptual Enhancement Mode. [%s]\n",enhancement ? "on" : "off");
       } else if (!strcasecmp(var->name, "vbr")) {
          vbr = ast_true(var->value) ? 1 : 0;
          ast_verb(3, "CODEC SPEEX: VBR Mode. [%s]\n",vbr ? "on" : "off");
       } else if (!strcasecmp(var->name, "abr")) {
          res = abs(atoi(var->value));
          if (res >= 0) {
                if (res > 0)
                ast_verb(3, "CODEC SPEEX: Setting ABR target bitrate to %d\n",res);
                else
                ast_verb(3, "CODEC SPEEX: Disabling ABR\n");
             abr = res;
          } else
             ast_log(LOG_ERROR,"Error! ABR target bitrate must be >= 0\n");
       } else if (!strcasecmp(var->name, "vad")) {
          vad = ast_true(var->value) ? 1 : 0;
          ast_verb(3, "CODEC SPEEX: VAD Mode. [%s]\n",vad ? "on" : "off");
       } else if (!strcasecmp(var->name, "dtx")) {
          dtx = ast_true(var->value) ? 1 : 0;
          ast_verb(3, "CODEC SPEEX: DTX Mode. [%s]\n",dtx ? "on" : "off");
       } else if (!strcasecmp(var->name, "preprocess")) {
          preproc = ast_true(var->value) ? 1 : 0;
          ast_verb(3, "CODEC SPEEX: Preprocessing. [%s]\n",preproc ? "on" : "off");
       } else if (!strcasecmp(var->name, "pp_vad")) {
          pp_vad = ast_true(var->value) ? 1 : 0;
          ast_verb(3, "CODEC SPEEX: Preprocessor VAD. [%s]\n",pp_vad ? "on" : "off");
       } else if (!strcasecmp(var->name, "pp_agc")) {
          pp_agc = ast_true(var->value) ? 1 : 0;
          ast_verb(3, "CODEC SPEEX: Preprocessor AGC. [%s]\n",pp_agc ? "on" : "off");
       } else if (!strcasecmp(var->name, "pp_agc_level")) {
          if (sscanf(var->value, "%30f", &res_f) == 1 && res_f >= 0) {
             ast_verb(3, "CODEC SPEEX: Setting preprocessor AGC Level to %f\n",res_f);
             pp_agc_level = res_f;
          } else
             ast_log(LOG_ERROR,"Error! Preprocessor AGC Level must be >= 0\n");
       } else if (!strcasecmp(var->name, "pp_denoise")) {
          pp_denoise = ast_true(var->value) ? 1 : 0;
          ast_verb(3, "CODEC SPEEX: Preprocessor Denoise. [%s]\n",pp_denoise ? "on" : "off");
       } else if (!strcasecmp(var->name, "pp_dereverb")) {
          pp_dereverb = ast_true(var->value) ? 1 : 0;
          ast_verb(3, "CODEC SPEEX: Preprocessor Dereverb. [%s]\n",pp_dereverb ? "on" : "off");
       } else if (!strcasecmp(var->name, "pp_dereverb_decay")) {
          if (sscanf(var->value, "%30f", &res_f) == 1 && res_f >= 0) {
             ast_verb(3, "CODEC SPEEX: Setting preprocessor Dereverb Decay to %f\n",res_f);
             pp_dereverb_decay = res_f;
          } else
             ast_log(LOG_ERROR,"Error! Preprocessor Dereverb Decay must be >= 0\n");
       } else if (!strcasecmp(var->name, "pp_dereverb_level")) {
          if (sscanf(var->value, "%30f", &res_f) == 1 && res_f >= 0) {
             ast_verb(3, "CODEC SPEEX: Setting preprocessor Dereverb Level to %f\n",res_f);
             pp_dereverb_level = res_f;
          } else
             ast_log(LOG_ERROR,"Error! Preprocessor Dereverb Level must be >= 0\n");
       } else if (!strcasecmp(var->name, "experimental_rtcp_feedback")) {
          exp_rtcp_fb = ast_true(var->value) ? 1 : 0;
          ast_verb(3, "CODEC SPEEX: Experimental RTCP Feedback. [%s]\n",exp_rtcp_fb ? "on" : "off");
       }
    }
    ast_config_destroy(cfg);
    return 0;
 }
reload()
static int reload (void) static
Definition at line 683 of file codec_speex.c.
References AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, and parse_config().
Referenced by load_module().
 {
    if (parse_config(1))
       return AST_MODULE_LOAD_DECLINE;
    return AST_MODULE_LOAD_SUCCESS;
 }
speex_decoder_construct()
static int speex_decoder_construct (struct ast_trans_pvt * pvt, const SpeexMode * profile) static
Definition at line 172 of file codec_speex.c.
References speex_coder_pvt::bits, enhancement, speex_coder_pvt::framesize, ast_trans_pvt::pvt, speex_coder_pvt::speex, and tmp().
Referenced by speextolin_new(), speexuwbtolin32_new(), and speexwbtolin16_new().
 {
    struct speex_coder_pvt *tmp = pvt->pvt;
    if (!(tmp->speex = speex_decoder_init(profile)))
       return -1;
    speex_bits_init(&tmp->bits);
    speex_decoder_ctl(tmp->speex, SPEEX_GET_FRAME_SIZE, &tmp->framesize);
    if (enhancement)
       speex_decoder_ctl(tmp->speex, SPEEX_SET_ENH, &enhancement);
    return 0;
 }
speex_encoder_construct()
static int speex_encoder_construct (struct ast_trans_pvt * pvt, const SpeexMode * profile, int sampling_rate) static
Definition at line 111 of file codec_speex.c.
References abr, ast_debug, speex_coder_pvt::bits, complexity, speex_coder_pvt::default_quality, dtx, speex_coder_pvt::fraction_lost, speex_coder_pvt::framesize, pp_agc, pp_agc_level, pp_denoise, pp_dereverb, pp_dereverb_decay, pp_dereverb_level, pp_vad, preproc, ast_trans_pvt::pvt, speex_coder_pvt::quality, speex_coder_pvt::silent_state, speex_coder_pvt::speex, tmp(), vad, vbr, and vbr_quality.
Referenced by lin16tospeexwb_new(), lin32tospeexuwb_new(), and lintospeex_new().
 {
    struct speex_coder_pvt *tmp = pvt->pvt;
    if (!(tmp->speex = speex_encoder_init(profile)))
       return -1;
    speex_bits_init(&tmp->bits);
    speex_bits_reset(&tmp->bits);
    speex_encoder_ctl(tmp->speex, SPEEX_GET_FRAME_SIZE, &tmp->framesize);
    speex_encoder_ctl(tmp->speex, SPEEX_SET_COMPLEXITY, &complexity);
 #ifdef _SPEEX_TYPES_H
    if (preproc) {
       tmp->pp = speex_preprocess_state_init(tmp->framesize, sampling_rate);
       speex_preprocess_ctl(tmp->pp, SPEEX_PREPROCESS_SET_VAD, &pp_vad);
       speex_preprocess_ctl(tmp->pp, SPEEX_PREPROCESS_SET_AGC, &pp_agc);
       speex_preprocess_ctl(tmp->pp, SPEEX_PREPROCESS_SET_AGC_LEVEL, &pp_agc_level);
       speex_preprocess_ctl(tmp->pp, SPEEX_PREPROCESS_SET_DENOISE, &pp_denoise);
       speex_preprocess_ctl(tmp->pp, SPEEX_PREPROCESS_SET_DEREVERB, &pp_dereverb);
       speex_preprocess_ctl(tmp->pp, SPEEX_PREPROCESS_SET_DEREVERB_DECAY, &pp_dereverb_decay);
       speex_preprocess_ctl(tmp->pp, SPEEX_PREPROCESS_SET_DEREVERB_LEVEL, &pp_dereverb_level);
    }
 #endif
    if (!abr && !vbr) {
       speex_encoder_ctl(tmp->speex, SPEEX_SET_QUALITY, &quality);
       if (vad)
          speex_encoder_ctl(tmp->speex, SPEEX_SET_VAD, &vad);
    }
    if (vbr) {
       speex_encoder_ctl(tmp->speex, SPEEX_SET_VBR, &vbr);
       speex_encoder_ctl(tmp->speex, SPEEX_SET_VBR_QUALITY, &vbr_quality);
    }
    if (abr)
       speex_encoder_ctl(tmp->speex, SPEEX_SET_ABR, &abr);
    if (dtx)
       speex_encoder_ctl(tmp->speex, SPEEX_SET_DTX, &dtx);
    tmp->silent_state = 0;
    tmp->fraction_lost = 0;
    tmp->default_quality = vbr ? vbr_quality : quality;
    tmp->quality = tmp->default_quality;
    ast_debug(3, "Default quality (%s): %d\n", vbr ? "vbr" : "cbr", tmp->default_quality);
    return 0;
 }
speextolin_destroy()
static void speextolin_destroy (struct ast_trans_pvt * arg) static
Definition at line 427 of file codec_speex.c.
References speex_coder_pvt::bits, ast_trans_pvt::pvt, and speex_coder_pvt::speex.
 {
    struct speex_coder_pvt *pvt = arg->pvt;
    speex_decoder_destroy(pvt->speex);
    speex_bits_destroy(&pvt->bits);
 }
speextolin_framein()
static int speextolin_framein (struct ast_trans_pvt * pvt, struct ast_frame * f) static
convert and store into outbuf
Definition at line 203 of file codec_speex.c.
References ast_log, speex_coder_pvt::bits, BUFFER_SAMPLES, ast_frame::data, ast_frame::datalen, ast_trans_pvt::datalen, speex_coder_pvt::framesize, ast_trans_pvt::i16, LOG_WARNING, NULL, ast_trans_pvt::outbuf, ast_frame::ptr, ast_trans_pvt::pvt, ast_trans_pvt::samples, speex_coder_pvt::speex, and tmp().
 {
    struct speex_coder_pvt *tmp = pvt->pvt;
    /* Assuming there's space left, decode into the current buffer at
       the tail location.  Read in as many frames as there are */
    int x;
    int res;
    int16_t *dst = pvt->outbuf.i16;
    /* XXX fout is a temporary buffer, may have different types */
 #ifdef _SPEEX_TYPES_H
    spx_int16_t fout[1024];
 #else
    float fout[1024];
 #endif
    if (f->datalen == 0) {  /* Native PLC interpolation */
       if (pvt->samples + tmp->framesize > BUFFER_SAMPLES) {
          ast_log(LOG_WARNING, "Out of buffer space\n");
          return -1;
       }
 #ifdef _SPEEX_TYPES_H
       speex_decode_int(tmp->speex, NULL, dst + pvt->samples);
 #else
       speex_decode(tmp->speex, NULL, fout);
       for (x=0;x<tmp->framesize;x++) {
          dst[pvt->samples + x] = (int16_t)fout[x];
       }
 #endif
       pvt->samples += tmp->framesize;
       pvt->datalen += 2 * tmp->framesize; /* 2 bytes/sample */
       return 0;
    }
    /* Read in bits */
    speex_bits_read_from(&tmp->bits, f->data.ptr, f->datalen);
    for (;;) {
 #ifdef _SPEEX_TYPES_H
       res = speex_decode_int(tmp->speex, &tmp->bits, fout);
 #else
       res = speex_decode(tmp->speex, &tmp->bits, fout);
 #endif
       if (res < 0)
          break;
       if (pvt->samples + tmp->framesize > BUFFER_SAMPLES) {
          ast_log(LOG_WARNING, "Out of buffer space\n");
          return -1;
       }
       for (x = 0 ; x < tmp->framesize; x++)
          dst[pvt->samples + x] = (int16_t)fout[x];
       pvt->samples += tmp->framesize;
       pvt->datalen += 2 * tmp->framesize; /* 2 bytes/sample */
    }
    return 0;
 }
speextolin_new()
static int speextolin_new (struct ast_trans_pvt * pvt) static
Definition at line 187 of file codec_speex.c.
References speex_decoder_construct().
 {
    return speex_decoder_construct(pvt, &speex_nb_mode);
 }
speexuwbtolin32_new()
static int speexuwbtolin32_new (struct ast_trans_pvt * pvt) static
Definition at line 197 of file codec_speex.c.
References speex_decoder_construct().
 {
    return speex_decoder_construct(pvt, &speex_uwb_mode);
 }
speexwbtolin16_new()
static int speexwbtolin16_new (struct ast_trans_pvt * pvt) static
Definition at line 192 of file codec_speex.c.
References speex_decoder_construct().
 {
    return speex_decoder_construct(pvt, &speex_wb_mode);
 }
unload_module()
static int unload_module (void) static
Definition at line 690 of file codec_speex.c.
References ast_unregister_translator().
Referenced by load_module().
 {
    ast_unregister_translator(&speextolin);
    ast_unregister_translator(&lintospeex);
    ast_unregister_translator(&speexwbtolin16);
    ast_unregister_translator(&lin16tospeexwb);
    ast_unregister_translator(&speexuwbtolin32);
    ast_unregister_translator(&lin32tospeexuwb);
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_DEFAULT , .description = "Speex Coder/Decoder" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .reload = reload, } static
Definition at line 730 of file codec_speex.c.
abr
int abr = 0 static
Definition at line 68 of file codec_speex.c.
Referenced by parse_config(), and speex_encoder_construct().
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 730 of file codec_speex.c.
complexity
int complexity = 2 static
Definition at line 63 of file codec_speex.c.
Referenced by parse_config(), and speex_encoder_construct().
dtx
int dtx = 0 static
Definition at line 69 of file codec_speex.c.
Referenced by lintospeex_frameout(), parse_config(), and speex_encoder_construct().
enhancement
int enhancement = 0 static
Definition at line 64 of file codec_speex.c.
Referenced by parse_config(), and speex_decoder_construct().
exp_rtcp_fb
int exp_rtcp_fb = 0 static
Definition at line 70 of file codec_speex.c.
Referenced by lintospeex_feedback(), and parse_config().
lin16tospeexwb
struct ast_translator lin16tospeexwb static
Definition at line 516 of file codec_speex.c.
lin32tospeexuwb
struct ast_translator lin32tospeexuwb static
Definition at line 562 of file codec_speex.c.
lintospeex
struct ast_translator lintospeex static
Definition at line 469 of file codec_speex.c.
pp_agc
int pp_agc = 0 static
Definition at line 74 of file codec_speex.c.
Referenced by parse_config(), and speex_encoder_construct().
pp_agc_level
float pp_agc_level = 8000 static
Definition at line 75 of file codec_speex.c.
Referenced by parse_config(), and speex_encoder_construct().
pp_denoise
int pp_denoise = 0 static
Definition at line 76 of file codec_speex.c.
Referenced by parse_config(), and speex_encoder_construct().
pp_dereverb
int pp_dereverb = 0 static
Definition at line 77 of file codec_speex.c.
Referenced by parse_config(), and speex_encoder_construct().
pp_dereverb_decay
float pp_dereverb_decay = 0.4 static
Definition at line 78 of file codec_speex.c.
Referenced by parse_config(), and speex_encoder_construct().
pp_dereverb_level
float pp_dereverb_level = 0.3 static
Definition at line 79 of file codec_speex.c.
Referenced by parse_config(), and speex_encoder_construct().
pp_vad
int pp_vad = 0 static
Definition at line 73 of file codec_speex.c.
Referenced by parse_config(), and speex_encoder_construct().
preproc
int preproc = 0 static
Definition at line 72 of file codec_speex.c.
Referenced by lintospeex_destroy(), lintospeex_frameout(), parse_config(), and speex_encoder_construct().
quality
int quality = 3 static
Definition at line 62 of file codec_speex.c.
Referenced by ast_rtp_instance_set_stats_vars(), handle_request_bye(), and sip_hangup().
speextolin
struct ast_translator speextolin static
Definition at line 446 of file codec_speex.c.
speexuwbtolin32
struct ast_translator speexuwbtolin32 static
Definition at line 540 of file codec_speex.c.
speexwbtolin16
struct ast_translator speexwbtolin16 static
Definition at line 493 of file codec_speex.c.
vad
int vad = 0 static
Definition at line 65 of file codec_speex.c.
Referenced by parse_config(), and speex_encoder_construct().
vbr
int vbr = 0 static
Definition at line 66 of file codec_speex.c.
Referenced by lintospeex_feedback(), parse_config(), and speex_encoder_construct().
vbr_quality
float vbr_quality = 4 static
Definition at line 67 of file codec_speex.c.
Referenced by parse_config(), and speex_encoder_construct().