Asterisk - The Open Source Telephony Project: chan_console.c File Reference
chan_console.c File Reference
Module: Asterisk Channel Drivers
Cross-platform console channel driver.
#include "asterisk.h"
#include <signal.h>
#include <portaudio.h>
#include "asterisk/module.h"
#include "asterisk/channel.h"
#include "asterisk/pbx.h"
#include "asterisk/causes.h"
#include "asterisk/cli.h"
#include "asterisk/musiconhold.h"
#include "asterisk/callerid.h"
#include "asterisk/astobj2.h"
#include "asterisk/stasis_channels.h"
#include "asterisk/format_cache.h"
Data Structures
struct console_pvt
Console pvt structure.
Macros
#define console_pvt_lock(pvt) ao2_lock(pvt)
lock a console_pvt struct
#define console_pvt_unlock(pvt) ao2_unlock(pvt)
unlock a console_pvt struct
#define INPUT_CHANNELS 1
Mono Input.
#define NUM_PVT_BUCKETS 7
#define NUM_SAMPLES 320
The number of samples to configure the portaudio stream for.
#define OUTPUT_CHANNELS 1
Mono Output.
#define SAMPLE_RATE 16000
The sample rate to request from PortAudio.
#define TEXT_SIZE 256
Maximum text message length.
#define V_BEGIN " --- <(\"<) --- "
Dance, Kirby, Dance!
#define V_END " --- (>\")> ---\n"
Functions
static void __reg_module (void)
static void __unreg_module (void)
static char * ast_ext_ctx (struct console_pvt *pvt, const char *src, char **ext, char **ctx)
struct ast_module * AST_MODULE_SELF_SYM (void)
static void build_device (struct ast_config *cfg, const char *name)
static char * cli_console_active (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static char * cli_console_answer (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
answer command from the console
static char * cli_console_autoanswer (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static char * cli_console_dial (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static char * cli_console_flash (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static char * cli_console_hangup (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static char * cli_console_mute (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static char * cli_console_sendtext (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
Console send text CLI command.
static char * cli_list_available (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static char * cli_list_devices (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static struct ast_channel * console_new (struct console_pvt *pvt, const char *ext, const char *ctx, int state, const struct ast_assigned_ids *assignedids, const struct ast_channel *requestor)
static void destroy_pvts (void)
static struct console_pvt * find_pvt (const char *name)
static struct console_pvt * get_active_pvt (void)
static int init_pvt (struct console_pvt *pvt, const char *name)
static int load_config (int reload)
Load the configuration.
static int load_module (void)
Load the module.
static int open_stream (struct console_pvt *pvt)
static int pvt_cmp_cb (void *obj, void *arg, int flags)
static void pvt_destructor (void *obj)
static int pvt_hash_cb (const void *obj, const int flags)
static int pvt_mark_destroy_cb (void *obj, void *arg, int flags)
static struct console_pvt * ref_pvt (struct console_pvt *pvt)
static int reload (void)
static void set_active (struct console_pvt *pvt, const char *value)
static void set_pvt_defaults (struct console_pvt *pvt)
Set default values for a pvt struct.
static int start_stream (struct console_pvt *pvt)
static int stop_stream (struct console_pvt *pvt)
static void stop_streams (void)
static void store_callerid (struct console_pvt *pvt, const char *value)
static void store_config_core (struct console_pvt *pvt, const char *var, const char *value)
Store a configuration parameter in a pvt struct.
static void * stream_monitor (void *data)
Stream monitor thread.
static int unload_module (void)
static struct console_pvt * unref_pvt (struct console_pvt *pvt)
static struct ast_channel * console_request (const char *type, struct ast_format_cap *cap, const struct ast_assigned_ids *assignedids, const struct ast_channel *requestor, const char *data, int *cause)
static int console_digit_begin (struct ast_channel *c, char digit)
static int console_digit_end (struct ast_channel *c, char digit, unsigned int duration)
static int console_text (struct ast_channel *c, const char *text)
static int console_hangup (struct ast_channel *c)
static int console_answer (struct ast_channel *c)
static struct ast_frame * console_read (struct ast_channel *chan)
static int console_call (struct ast_channel *c, const char *dest, int timeout)
static int console_write (struct ast_channel *chan, struct ast_frame *f)
static int console_indicate (struct ast_channel *chan, int cond, const void *data, size_t datalen)
static int console_fixup (struct ast_channel *oldchan, struct ast_channel *newchan)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Console Channel Driver" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_EXTENDED, .load = load_module, .unload = unload_module, .reload = reload, .load_pri = AST_MODPRI_CHANNEL_DRIVER, }
static ast_rwlock_t active_lock = { PTHREAD_RWLOCK_INITIALIZER , NULL, {1, 0} }
static struct console_pvt * active_pvt
static const struct ast_module_info * ast_module_info = &__mod_info
static struct ast_cli_entry cli_console []
static const char config_file [] = "console.conf"
static struct ast_channel_tech console_tech
static struct ast_jb_conf default_jbconf
Global jitterbuffer configuration.
static struct ast_jb_conf global_jbconf
static struct console_pvt globals
static ast_mutex_t globals_lock = { PTHREAD_RECURSIVE_MUTEX_INITIALIZER_NP , NULL, {1, 0} }
static struct ao2_container * pvts
Detailed Description
Cross-platform console channel driver.
Author
Russell Bryant russe.nosp@m.ll@d.nosp@m.igium.nosp@m..com
Note
Some of the code in this file came from chan_oss and chan_alsa. chan_oss, Mark Spencer marks.nosp@m.ter@.nosp@m.digiu.nosp@m.m.co.nosp@m.m chan_oss, Luigi Rizzo chan_alsa, Matthew Fredrickson cresl.nosp@m.in@d.nosp@m.igium.nosp@m..com
Portaudio http://www.portaudio.com/
To install portaudio v19 from svn, check it out using the following command:
svn co https://www.portaudio.com/repos/portaudio/branches/v19-devel
Note
Since this works with any audio system that libportaudio supports, including ALSA and OSS, this may someday deprecate chan_alsa and chan_oss. However, before that can be done, it needs to at least have all of the features that these other channel drivers have. The features implemented in at least one of the other console channel drivers that are not yet implemented here are:
Set Auto-answer from the dialplan
transfer CLI command
boost CLI command and .conf option
console_video support
Definition in file chan_console.c.
Macro Definition Documentation
console_pvt_lock
#define console_pvt_lock (pvt) ao2_lock(pvt)
lock a console_pvt struct
Definition at line 228 of file chan_console.c.
Referenced by build_device(), cli_console_active(), cli_console_dial(), cli_list_devices(), console_call(), console_request(), console_write(), start_stream(), stop_stream(), and stream_monitor().
console_pvt_unlock
#define console_pvt_unlock (pvt) ao2_unlock(pvt)
unlock a console_pvt struct
Definition at line 231 of file chan_console.c.
Referenced by build_device(), cli_console_active(), cli_console_dial(), cli_list_devices(), console_call(), console_request(), console_write(), start_stream(), stop_stream(), and stream_monitor().
INPUT_CHANNELS
#define INPUT_CHANNELS 1
Mono Input.
Definition at line 101 of file chan_console.c.
Referenced by open_stream().
NUM_PVT_BUCKETS
#define NUM_PVT_BUCKETS 7
Definition at line 175 of file chan_console.c.
Referenced by load_module().
NUM_SAMPLES
#define NUM_SAMPLES 320
The number of samples to configure the portaudio stream for.
320 samples (20 ms) is the most common frame size in Asterisk. So, the code in this module reads 320 sample frames from the portaudio stream and queues them up on the Asterisk channel. Frames of any size can be written to a portaudio stream, but the portaudio documentation does say that for high performance applications, the data should be written to Pa_WriteStream in the same size as what is used to initialize the stream.
Definition at line 98 of file chan_console.c.
Referenced by open_stream(), and stream_monitor().
OUTPUT_CHANNELS
#define OUTPUT_CHANNELS 1
Mono Output.
Definition at line 104 of file chan_console.c.
Referenced by open_stream().
SAMPLE_RATE
#define SAMPLE_RATE 16000
The sample rate to request from PortAudio.
Todo:
Make this optional. If this is only going to talk to 8 kHz endpoints, then it makes sense to use 8 kHz natively.
Definition at line 86 of file chan_console.c.
Referenced by open_stream().
TEXT_SIZE
#define TEXT_SIZE 256
Maximum text message length.
Note
This should be changed if there is a common definition somewhere that defines the maximum length of a text message.
Definition at line 111 of file chan_console.c.
Referenced by cli_console_sendtext().
V_BEGIN
#define V_BEGIN " --- <(\"<) --- "
Dance, Kirby, Dance!
Definition at line 114 of file chan_console.c.
Referenced by cli_console_mute(), console_answer(), console_call(), console_digit_begin(), console_digit_end(), console_hangup(), console_indicate(), and console_text().
V_END
#define V_END " --- (>\")> ---\n"
Definition at line 115 of file chan_console.c.
Referenced by cli_console_mute(), console_answer(), console_call(), console_digit_begin(), console_digit_end(), console_hangup(), console_indicate(), and console_text().
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 1590 of file chan_console.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 1590 of file chan_console.c.
ast_ext_ctx()
static char* ast_ext_ctx (struct console_pvt * pvt, const char * src, char ** ext, char ** ctx) static
split a string in extension-context, returns pointers to malloc'ed strings. If we do not have 'overridecontext' then the last @ is considered as a context separator, and the context is overridden. This is usually not very necessary as you can play with the dialplan, and it is nice not to need it because you have '@' in SIP addresses. Return value is the buffer address.
Note
came from chan_oss
Definition at line 680 of file chan_console.c.
References ast_strdup, ext, NULL, and console_pvt::overridecontext.
Referenced by cli_console_dial().
 {
    if (ext == NULL || ctx == NULL)
       return NULL;         /* error */
    *ext = *ctx = NULL;
    if (src && *src != '\0')
       *ext = ast_strdup(src);
    if (*ext == NULL)
       return NULL;
    if (!pvt->overridecontext) {
       /* parse from the right */
       *ctx = strrchr(*ext, '@');
       if (*ctx)
          *(*ctx)++ = '\0';
    }
    return *ext;
 }
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 1590 of file chan_console.c.
build_device()
static void build_device (struct ast_config * cfg, const char * name) static
Definition at line 1368 of file chan_console.c.
References ao2_alloc, ao2_link, ast_variable_browse(), console_pvt_lock, console_pvt_unlock, console_pvt::destroy, find_pvt(), init_pvt(), ast_variable::name, ast_variable::next, pvt_destructor(), set_pvt_defaults(), store_config_core(), unref_pvt(), and ast_variable::value.
Referenced by load_config().
 {
    struct ast_variable *v;
    struct console_pvt *pvt;
    int new = 0;
    if ((pvt = find_pvt(name))) {
       console_pvt_lock(pvt);
       set_pvt_defaults(pvt);
       pvt->destroy = 0;
    } else {
       if (!(pvt = ao2_alloc(sizeof(*pvt), pvt_destructor)))
          return;
       init_pvt(pvt, name);
       set_pvt_defaults(pvt);
       new = 1;
    }
    for (v = ast_variable_browse(cfg, name); v; v = v->next)
       store_config_core(pvt, v->name, v->value);
    if (new)
       ao2_link(pvts, pvt);
    else
       console_pvt_unlock(pvt);
    unref_pvt(pvt);
 }
cli_console_active()
static char* cli_console_active (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) static
Definition at line 1191 of file chan_console.c.
References ao2_iterator_destroy(), ao2_iterator_init(), ao2_iterator_next, ast_cli_args::argc, ast_cli_entry::args, ast_cli_args::argv, ast_cli(), ast_strdup, CLI_FAILURE, CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::command, console_pvt_lock, console_pvt_unlock, ast_cli_args::fd, find_pvt(), get_active_pvt(), ast_cli_args::n, console_pvt::name, NULL, ast_cli_args::pos, set_active(), unref_pvt(), ast_cli_entry::usage, and ast_cli_args::word.
 {
    struct console_pvt *pvt;
    switch (cmd) {
    case CLI_INIT:
       e->command = "console {set|show} active";
       e->usage =
          "Usage: console {set|show} active [<device>]\n"
          "       Set or show the active console device for the Asterisk CLI.\n";
       return NULL;
    case CLI_GENERATE:
       if (a->pos == e->args) {
          struct ao2_iterator i;
          int x = 0;
          char *res = NULL;
          i = ao2_iterator_init(pvts, 0);
          while ((pvt = ao2_iterator_next(&i))) {
             if (++x > a->n && !strncasecmp(pvt->name, a->word, strlen(a->word)))
                res = ast_strdup(pvt->name);
             unref_pvt(pvt);
             if (res) {
                ao2_iterator_destroy(&i);
                return res;
             }
          }
          ao2_iterator_destroy(&i);
       }
       return NULL;
    }
    if (a->argc < e->args)
       return CLI_SHOWUSAGE;
    if (a->argc == 3) {
       pvt = get_active_pvt();
       if (!pvt)
          ast_cli(a->fd, "No device is currently set as the active console device.\n");
       else {
          console_pvt_lock(pvt);
          ast_cli(a->fd, "The active console device is '%s'.\n", pvt->name);
          console_pvt_unlock(pvt);
          pvt = unref_pvt(pvt);
       }
       return CLI_SUCCESS;
    }
    if (!(pvt = find_pvt(a->argv[e->args]))) {
       ast_cli(a->fd, "Could not find a device called '%s'.\n", a->argv[e->args]);
       return CLI_FAILURE;
    }
    set_active(pvt, "yes");
    console_pvt_lock(pvt);
    ast_cli(a->fd, "The active console device has been set to '%s'\n", pvt->name);
    console_pvt_unlock(pvt);
    unref_pvt(pvt);
    return CLI_SUCCESS;
 }
cli_console_answer()
static char* cli_console_answer (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) static
answer command from the console
Definition at line 1069 of file chan_console.c.
References ast_cli_args::argc, ast_cli_entry::args, ast_cli(), AST_CONTROL_ANSWER, ast_indicate(), ast_queue_control(), CLI_FAILURE, CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::command, ast_cli_args::fd, get_active_pvt(), console_pvt::hookstate, NULL, console_pvt::owner, unref_pvt(), and ast_cli_entry::usage.
 {
    struct console_pvt *pvt;
    switch (cmd) {
    case CLI_INIT:
       e->command = "console answer";
       e->usage =
          "Usage: console answer\n"
          "       Answers an incoming call on the console channel.\n";
       return NULL;
    case CLI_GENERATE:
       return NULL;   /* no completion */
    }
    pvt = get_active_pvt();
    if (!pvt) {
       ast_cli(a->fd, "No console device is set as active\n");
       return CLI_FAILURE;
    }
    if (a->argc != e->args) {
       unref_pvt(pvt);
       return CLI_SHOWUSAGE;
    }
    if (!pvt->owner) {
       ast_cli(a->fd, "No one is calling us\n");
       unref_pvt(pvt);
       return CLI_FAILURE;
    }
    pvt->hookstate = 1;
    ast_indicate(pvt->owner, -1);
    ast_queue_control(pvt->owner, AST_CONTROL_ANSWER);
    unref_pvt(pvt);
    return CLI_SUCCESS;
 }
cli_console_autoanswer()
static char* cli_console_autoanswer (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) static
Definition at line 714 of file chan_console.c.
References ast_cli_args::argc, ast_cli_entry::args, ast_cli_args::argv, ast_cli(), console_pvt::autoanswer, CLI_FAILURE, CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::command, ast_cli_args::fd, get_active_pvt(), NULL, unref_pvt(), and ast_cli_entry::usage.
 {
    struct console_pvt *pvt;
    char *res = CLI_SUCCESS;
    switch (cmd) {
    case CLI_INIT:
       e->command = "console {set|show} autoanswer [on|off]";
       e->usage =
          "Usage: console {set|show} autoanswer [on|off]\n"
          "       Enables or disables autoanswer feature.  If used without\n"
          "       argument, displays the current on/off status of autoanswer.\n"
          "       The default value of autoanswer is in 'oss.conf'.\n";
       return NULL;
    case CLI_GENERATE:
       return NULL;
    }
    pvt = get_active_pvt();
    if (!pvt) {
       ast_cli(a->fd, "No console device is set as active.\n");
       return CLI_FAILURE;
    }
    if (a->argc == e->args - 1) {
       ast_cli(a->fd, "Auto answer is %s.\n", pvt->autoanswer ? "on" : "off");
       unref_pvt(pvt);
       return CLI_SUCCESS;
    }
    if (a->argc != e->args) {
       unref_pvt(pvt);
       return CLI_SHOWUSAGE;
    }
    if (!strcasecmp(a->argv[e->args-1], "on"))
       pvt->autoanswer = 1;
    else if (!strcasecmp(a->argv[e->args - 1], "off"))
       pvt->autoanswer = 0;
    else
       res = CLI_SHOWUSAGE;
    unref_pvt(pvt);
    return res;
 }
cli_console_dial()
static char* cli_console_dial (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) static
Definition at line 802 of file chan_console.c.
References ast_cli_args::argc, ast_cli_entry::args, ast_cli_args::argv, ast_cli(), ast_debug, ast_exists_extension(), ast_ext_ctx(), AST_FRAME_DTMF, ast_free, ast_queue_frame(), AST_STATE_RINGING, ast_strlen_zero, CLI_FAILURE, CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::command, console_new(), console_pvt_lock, console_pvt_unlock, console_pvt::context, ext, console_pvt::exten, ast_cli_args::fd, get_active_pvt(), console_pvt::hookstate, ast_frame_subclass::integer, NULL, console_pvt::owner, ast_frame::subclass, unref_pvt(), and ast_cli_entry::usage.
 {
    char *s = NULL;
    const char *mye = NULL, *myc = NULL;
    struct console_pvt *pvt;
    if (cmd == CLI_INIT) {
       e->command = "console dial";
       e->usage =
          "Usage: console dial [extension[@context]]\n"
          "       Dials a given extension (and context if specified)\n";
       return NULL;
    } else if (cmd == CLI_GENERATE) {
       return NULL;
    }
    if (a->argc > e->args + 1) {
       return CLI_SHOWUSAGE;
    }
    pvt = get_active_pvt();
    if (!pvt) {
       ast_cli(a->fd, "No console device is currently set as active\n");
       return CLI_FAILURE;
    }
    if (pvt->owner) { /* already in a call */
       int i;
       struct ast_frame f = { AST_FRAME_DTMF };
       const char *s;
       if (a->argc == e->args) {  /* argument is mandatory here */
          ast_cli(a->fd, "Already in a call. You can only dial digits until you hangup.\n");
          unref_pvt(pvt);
          return CLI_FAILURE;
       }
       s = a->argv[e->args];
       /* send the string one char at a time */
       for (i = 0; i < strlen(s); i++) {
          f.subclass.integer = s[i];
          ast_queue_frame(pvt->owner, &f);
       }
       unref_pvt(pvt);
       return CLI_SUCCESS;
    }
    /* if we have an argument split it into extension and context */
    if (a->argc == e->args + 1) {
       char *ext = NULL, *con = NULL;
       s = ast_ext_ctx(pvt, a->argv[e->args], &ext, &con);
       mye = ext;
       myc = con;
       ast_debug(1, "provided '%s', exten '%s' context '%s'\n",
          a->argv[e->args], mye, myc);
    }
    /* supply default values if needed */
    if (ast_strlen_zero(mye))
       mye = pvt->exten;
    if (ast_strlen_zero(myc))
       myc = pvt->context;
    if (ast_exists_extension(NULL, myc, mye, 1, NULL)) {
       console_pvt_lock(pvt);
       pvt->hookstate = 1;
       console_new(pvt, mye, myc, AST_STATE_RINGING, NULL, NULL);
       console_pvt_unlock(pvt);
    } else
       ast_cli(a->fd, "No such extension '%s' in context '%s'\n", mye, myc);
    ast_free(s);
    unref_pvt(pvt);
    return CLI_SUCCESS;
 }
cli_console_flash()
static char* cli_console_flash (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) static
Definition at line 763 of file chan_console.c.
References ast_cli_args::argc, ast_cli_entry::args, ast_cli(), AST_CONTROL_FLASH, ast_queue_control(), CLI_FAILURE, CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::command, ast_cli_args::fd, get_active_pvt(), console_pvt::hookstate, NULL, console_pvt::owner, unref_pvt(), and ast_cli_entry::usage.
 {
    struct console_pvt *pvt;
    if (cmd == CLI_INIT) {
       e->command = "console flash";
       e->usage =
          "Usage: console flash\n"
          "       Flashes the call currently placed on the console.\n";
       return NULL;
    } else if (cmd == CLI_GENERATE) {
       return NULL;
    }
    if (a->argc != e->args) {
       return CLI_SHOWUSAGE;
    }
    pvt = get_active_pvt();
    if (!pvt) {
       ast_cli(a->fd, "No console device is set as active\n");
       return CLI_FAILURE;
    }
    if (!pvt->owner) {
       ast_cli(a->fd, "No call to flash\n");
       unref_pvt(pvt);
       return CLI_FAILURE;
    }
    pvt->hookstate = 0;
    ast_queue_control(pvt->owner, AST_CONTROL_FLASH);
    unref_pvt(pvt);
    return CLI_SUCCESS;
 }
cli_console_hangup()
static char* cli_console_hangup (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) static
Definition at line 879 of file chan_console.c.
References ast_cli_args::argc, ast_cli_entry::args, ast_cli(), ast_queue_hangup(), CLI_FAILURE, CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::command, ast_cli_args::fd, get_active_pvt(), console_pvt::hookstate, NULL, console_pvt::owner, unref_pvt(), and ast_cli_entry::usage.
 {
    struct console_pvt *pvt;
    if (cmd == CLI_INIT) {
       e->command = "console hangup";
       e->usage =
          "Usage: console hangup\n"
          "       Hangs up any call currently placed on the console.\n";
       return NULL;
    } else if (cmd == CLI_GENERATE) {
       return NULL;
    }
    if (a->argc != e->args) {
       return CLI_SHOWUSAGE;
    }
    pvt = get_active_pvt();
    if (!pvt) {
       ast_cli(a->fd, "No console device is set as active\n");
       return CLI_FAILURE;
    }
    if (!pvt->owner && !pvt->hookstate) {
       ast_cli(a->fd, "No call to hang up\n");
       unref_pvt(pvt);
       return CLI_FAILURE;
    }
    pvt->hookstate = 0;
    if (pvt->owner)
       ast_queue_hangup(pvt->owner);
    unref_pvt(pvt);
    return CLI_SUCCESS;
 }
cli_console_mute()
static char* cli_console_mute (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) static
Definition at line 918 of file chan_console.c.
References ast_cli_args::argc, ast_cli_entry::args, ast_cli_args::argv, ast_cli(), ast_verb, CLI_FAILURE, CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::command, ast_cli_args::fd, get_active_pvt(), console_pvt::muted, NULL, unref_pvt(), ast_cli_entry::usage, V_BEGIN, and V_END.
 {
    const char *s;
    struct console_pvt *pvt;
    char *res = CLI_SUCCESS;
    if (cmd == CLI_INIT) {
       e->command = "console {mute|unmute}";
       e->usage =
          "Usage: console {mute|unmute}\n"
          "       Mute/unmute the microphone.\n";
       return NULL;
    } else if (cmd == CLI_GENERATE) {
       return NULL;
    }
    if (a->argc != e->args) {
       return CLI_SHOWUSAGE;
    }
    pvt = get_active_pvt();
    if (!pvt) {
       ast_cli(a->fd, "No console device is set as active\n");
       return CLI_FAILURE;
    }
    s = a->argv[e->args-1];
    if (!strcasecmp(s, "mute"))
       pvt->muted = 1;
    else if (!strcasecmp(s, "unmute"))
       pvt->muted = 0;
    else
       res = CLI_SHOWUSAGE;
    ast_verb(1, V_BEGIN "The Console is now %s" V_END,
       pvt->muted ? "Muted" : "Unmuted");
    unref_pvt(pvt);
    return res;
 }
cli_console_sendtext()
static char* cli_console_sendtext (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) static
Console send text CLI command.
Note
concatenate all arguments into a single string. argv is NULL-terminated so we can use it right away
Definition at line 1119 of file chan_console.c.
References ast_cli_args::argc, ast_cli_entry::args, ast_cli_args::argv, ast_cli(), AST_FRAME_TEXT, ast_join, ast_queue_frame(), ast_strlen_zero, buf, CLI_FAILURE, CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::command, ast_frame::datalen, ast_cli_args::fd, ast_frame::frametype, get_active_pvt(), len(), NULL, console_pvt::owner, TEXT_SIZE, unref_pvt(), and ast_cli_entry::usage.
 {
    char buf[TEXT_SIZE];
    struct console_pvt *pvt;
    struct ast_frame f = {
       .frametype = AST_FRAME_TEXT,
       .data.ptr = buf,
       .src = "console_send_text",
    };
    int len;
    if (cmd == CLI_INIT) {
       e->command = "console send text";
       e->usage =
          "Usage: console send text <message>\n"
          "       Sends a text message for display on the remote terminal.\n";
       return NULL;
    } else if (cmd == CLI_GENERATE) {
       return NULL;
    }
    pvt = get_active_pvt();
    if (!pvt) {
       ast_cli(a->fd, "No console device is set as active\n");
       return CLI_FAILURE;
    }
    if (a->argc < e->args + 1) {
       unref_pvt(pvt);
       return CLI_SHOWUSAGE;
    }
    if (!pvt->owner) {
       ast_cli(a->fd, "Not in a call\n");
       unref_pvt(pvt);
       return CLI_FAILURE;
    }
    ast_join(buf, sizeof(buf) - 1, a->argv + e->args);
    if (ast_strlen_zero(buf)) {
       unref_pvt(pvt);
       return CLI_SHOWUSAGE;
    }
    len = strlen(buf);
    buf[len] = '\n';
    f.datalen = len + 1;
    ast_queue_frame(pvt->owner, &f);
    unref_pvt(pvt);
    return CLI_SUCCESS;
 }
cli_list_available()
static char* cli_list_available (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) static
Definition at line 960 of file chan_console.c.
References ast_cli_args::argc, ast_cli_entry::args, ast_cli(), CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::command, ast_cli_args::fd, NULL, and ast_cli_entry::usage.
 {
    PaDeviceIndex idx, num, def_input, def_output;
    if (cmd == CLI_INIT) {
       e->command = "console list available";
       e->usage =
          "Usage: console list available\n"
          "       List all available devices.\n";
       return NULL;
    } else if (cmd == CLI_GENERATE)
       return NULL;
    if (a->argc != e->args)
       return CLI_SHOWUSAGE;
    ast_cli(a->fd, "\n"
                "=============================================================\n"
                "=== Available Devices =======================================\n"
                "=============================================================\n"
                "===\n");
    num = Pa_GetDeviceCount();
    if (!num) {
       ast_cli(a->fd, "(None)\n");
       return CLI_SUCCESS;
    }
    def_input = Pa_GetDefaultInputDevice();
    def_output = Pa_GetDefaultOutputDevice();
    for (idx = 0; idx < num; idx++) {
       const PaDeviceInfo *dev = Pa_GetDeviceInfo(idx);
       if (!dev)
          continue;
       ast_cli(a->fd, "=== ---------------------------------------------------------\n"
                      "=== Device Name: %s\n", dev->name);
       if (dev->maxInputChannels)
          ast_cli(a->fd, "=== ---> %sInput Device\n", (idx == def_input) ? "Default " : "");
       if (dev->maxOutputChannels)
          ast_cli(a->fd, "=== ---> %sOutput Device\n", (idx == def_output) ? "Default " : "");
       ast_cli(a->fd, "=== ---------------------------------------------------------\n===\n");
    }
    ast_cli(a->fd, "=============================================================\n\n");
    return CLI_SUCCESS;
 }
cli_list_devices()
static char* cli_list_devices (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) static
Definition at line 1008 of file chan_console.c.
References ao2_iterator_destroy(), ao2_iterator_init(), ao2_iterator_next, ast_cli_args::argc, ast_cli_entry::args, ast_cli(), console_pvt::autoanswer, console_pvt::cid_name, console_pvt::cid_num, CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::command, console_pvt_lock, console_pvt_unlock, console_pvt::context, console_pvt::exten, ast_cli_args::fd, console_pvt::input_device, console_pvt::language, console_pvt::mohinterpret, console_pvt::muted, console_pvt::name, NULL, console_pvt::output_device, console_pvt::overridecontext, console_pvt::parkinglot, unref_pvt(), and ast_cli_entry::usage.
 {
    struct ao2_iterator i;
    struct console_pvt *pvt;
    if (cmd == CLI_INIT) {
       e->command = "console list devices";
       e->usage =
          "Usage: console list devices\n"
          "       List all configured devices.\n";
       return NULL;
    } else if (cmd == CLI_GENERATE)
       return NULL;
    if (a->argc != e->args)
       return CLI_SHOWUSAGE;
    ast_cli(a->fd, "\n"
                "=============================================================\n"
                "=== Configured Devices ======================================\n"
                "=============================================================\n"
                "===\n");
    i = ao2_iterator_init(pvts, 0);
    while ((pvt = ao2_iterator_next(&i))) {
       console_pvt_lock(pvt);
       ast_cli(a->fd, "=== ---------------------------------------------------------\n"
                      "=== Device Name: %s\n"
                      "=== ---> Active:           %s\n"
                      "=== ---> Input Device:     %s\n"
                      "=== ---> Output Device:    %s\n"
                      "=== ---> Context:          %s\n"
                      "=== ---> Extension:        %s\n"
                      "=== ---> CallerID Num:     %s\n"
                      "=== ---> CallerID Name:    %s\n"
                      "=== ---> MOH Interpret:    %s\n"
                      "=== ---> Language:         %s\n"
                      "=== ---> Parkinglot:       %s\n"
                      "=== ---> Muted:            %s\n"
                      "=== ---> Auto-Answer:      %s\n"
                      "=== ---> Override Context: %s\n"
                      "=== ---------------------------------------------------------\n===\n",
          pvt->name, (pvt == active_pvt) ? "Yes" : "No",
          pvt->input_device, pvt->output_device, pvt->context,
          pvt->exten, pvt->cid_num, pvt->cid_name, pvt->mohinterpret,
          pvt->language, pvt->parkinglot, pvt->muted ? "Yes" : "No", pvt->autoanswer ? "Yes" : "No",
          pvt->overridecontext ? "Yes" : "No");
       console_pvt_unlock(pvt);
       unref_pvt(pvt);
    }
    ao2_iterator_destroy(&i);
    ast_cli(a->fd, "=============================================================\n\n");
    return CLI_SUCCESS;
 }
console_answer()
static int console_answer (struct ast_channel * c) static
Definition at line 544 of file chan_console.c.
References ast_channel_tech_pvt(), ast_setstate(), AST_STATE_UP, ast_verb, start_stream(), V_BEGIN, and V_END.
 {
    struct console_pvt *pvt = ast_channel_tech_pvt(c);
    ast_verb(1, V_BEGIN "Call from Console has been Answered" V_END);
    ast_setstate(c, AST_STATE_UP);
    return start_stream(pvt);
 }
console_call()
static int console_call (struct ast_channel * c, const char * dest, int timeout) static
Definition at line 582 of file chan_console.c.
References ast_channel_caller(), ast_channel_tech_pvt(), AST_CONTROL_ANSWER, AST_CONTROL_RINGING, ast_indicate(), ast_queue_control(), ast_verb, console_pvt::autoanswer, console_pvt_lock, console_pvt_unlock, console_pvt::hookstate, console_pvt::name, S_COR, start_stream(), V_BEGIN, and V_END.
 {
    struct console_pvt *pvt = ast_channel_tech_pvt(c);
    enum ast_control_frame_type ctrl;
    ast_verb(1, V_BEGIN "Call to device '%s' on console from '%s' <%s>" V_END,
       dest,
       S_COR(ast_channel_caller(c)->id.name.valid, ast_channel_caller(c)->id.name.str, ""),
       S_COR(ast_channel_caller(c)->id.number.valid, ast_channel_caller(c)->id.number.str, ""));
    console_pvt_lock(pvt);
    if (pvt->autoanswer) {
       pvt->hookstate = 1;
       console_pvt_unlock(pvt);
       ast_verb(1, V_BEGIN "Auto-answered" V_END);
       ctrl = AST_CONTROL_ANSWER;
    } else {
       console_pvt_unlock(pvt);
       ast_verb(1, V_BEGIN "Type 'console answer' to answer, or use the 'autoanswer' option "
             "for future calls" V_END);
       ctrl = AST_CONTROL_RINGING;
       ast_indicate(c, AST_CONTROL_RINGING);
    }
    ast_queue_control(c, ctrl);
    return start_stream(pvt);
 }
console_digit_begin()
static int console_digit_begin (struct ast_channel * c, char digit) static
Definition at line 507 of file chan_console.c.
References ast_verb, V_BEGIN, and V_END.
 {
    ast_verb(1, V_BEGIN "Console Received Beginning of Digit %c" V_END, digit);
    return -1; /* non-zero to request inband audio */
 }
console_digit_end()
static int console_digit_end (struct ast_channel * c, char digit, unsigned int duration) static
Definition at line 514 of file chan_console.c.
References ast_verb, V_BEGIN, and V_END.
 {
    ast_verb(1, V_BEGIN "Console Received End of Digit %c (duration %u)" V_END,
       digit, duration);
    return -1; /* non-zero to request inband audio */
 }
console_fixup()
static int console_fixup (struct ast_channel * oldchan, struct ast_channel * newchan) static
Definition at line 660 of file chan_console.c.
References ast_channel_tech_pvt(), and console_pvt::owner.
 {
    struct console_pvt *pvt = ast_channel_tech_pvt(newchan);
    pvt->owner = newchan;
    return 0;
 }
console_hangup()
static int console_hangup (struct ast_channel * c) static
Definition at line 529 of file chan_console.c.
References ast_channel_tech_pvt(), ast_channel_tech_pvt_set(), ast_verb, console_pvt::hookstate, NULL, console_pvt::owner, stop_stream(), unref_pvt(), V_BEGIN, and V_END.
 {
    struct console_pvt *pvt = ast_channel_tech_pvt(c);
    ast_verb(1, V_BEGIN "Hangup on Console" V_END);
    pvt->hookstate = 0;
    pvt->owner = NULL;
    stop_stream(pvt);
    ast_channel_tech_pvt_set(c, unref_pvt(pvt));
    return 0;
 }
console_indicate()
static int console_indicate (struct ast_channel * chan, int cond, const void * data, size_t datalen) static
Definition at line 623 of file chan_console.c.
References ast_channel_name(), ast_channel_tech_pvt(), AST_CONTROL_BUSY, AST_CONTROL_CONGESTION, AST_CONTROL_HOLD, AST_CONTROL_INCOMPLETE, AST_CONTROL_PROCEEDING, AST_CONTROL_PROGRESS, AST_CONTROL_PVT_CAUSE_CODE, AST_CONTROL_RINGING, AST_CONTROL_SRCUPDATE, AST_CONTROL_UNHOLD, AST_CONTROL_VIDUPDATE, ast_log, ast_moh_start(), ast_moh_stop(), ast_verb, LOG_WARNING, console_pvt::mohinterpret, V_BEGIN, and V_END.
 {
    struct console_pvt *pvt = ast_channel_tech_pvt(chan);
    int res = 0;
    switch (cond) {
    case AST_CONTROL_BUSY:
    case AST_CONTROL_CONGESTION:
    case AST_CONTROL_RINGING:
    case AST_CONTROL_INCOMPLETE:
    case AST_CONTROL_PVT_CAUSE_CODE:
    case -1:
       res = -1;  /* Ask for inband indications */
       break;
    case AST_CONTROL_PROGRESS:
    case AST_CONTROL_PROCEEDING:
    case AST_CONTROL_VIDUPDATE:
    case AST_CONTROL_SRCUPDATE:
       break;
    case AST_CONTROL_HOLD:
       ast_verb(1, V_BEGIN "Console Has Been Placed on Hold" V_END);
       ast_moh_start(chan, data, pvt->mohinterpret);
       break;
    case AST_CONTROL_UNHOLD:
       ast_verb(1, V_BEGIN "Console Has Been Retrieved from Hold" V_END);
       ast_moh_stop(chan);
       break;
    default:
       ast_log(LOG_WARNING, "Don't know how to display condition %d on %s\n",
          cond, ast_channel_name(chan));
       /* The core will play inband indications for us if appropriate */
       res = -1;
    }
    return res;
 }
console_new()
static struct ast_channel* console_new (struct console_pvt * pvt, const char * ext, const char * ctx, int state, const struct ast_assigned_ids * assignedids, const struct ast_channel * requestor) static
Note
Called with the pvt struct locked
Definition at line 423 of file chan_console.c.
References ao2_ref, AST_CAUSE_SWITCH_CONGESTION, ast_channel_alloc, ast_channel_hangupcause_set(), ast_channel_nativeformats_set(), ast_channel_set_readformat(), ast_channel_set_writeformat(), ast_channel_stage_snapshot(), ast_channel_stage_snapshot_done(), ast_channel_tech_pvt_set(), ast_channel_tech_set(), ast_channel_unlock, ast_format_cap_alloc, ast_format_cap_append, AST_FORMAT_CAP_FLAG_DEFAULT, ast_format_slin16, ast_hangup(), ast_jb_configure(), ast_pbx_start(), AST_STATE_DOWN, ast_strlen_zero, console_pvt::cid_name, console_pvt::cid_num, global_jbconf, console_pvt::language, console_pvt::name, NULL, console_pvt::owner, ref_pvt(), and start_stream().
Referenced by cli_console_dial(), and console_request().
 {
    struct ast_format_cap *caps;
    struct ast_channel *chan;
    caps = ast_format_cap_alloc(AST_FORMAT_CAP_FLAG_DEFAULT);
    if (!caps) {
       return NULL;
    }
    if (!(chan = ast_channel_alloc(1, state, pvt->cid_num, pvt->cid_name, NULL,
       ext, ctx, assignedids, requestor, 0, "Console/%s", pvt->name))) {
       ao2_ref(caps, -1);
       return NULL;
    }
    ast_channel_stage_snapshot(chan);
    ast_channel_tech_set(chan, &console_tech);
    ast_channel_set_readformat(chan, ast_format_slin16);
    ast_channel_set_writeformat(chan, ast_format_slin16);
    ast_format_cap_append(caps, ast_format_slin16, 0);
    ast_channel_nativeformats_set(chan, caps);
    ao2_ref(caps, -1);
    ast_channel_tech_pvt_set(chan, ref_pvt(pvt));
    pvt->owner = chan;
    if (!ast_strlen_zero(pvt->language))
       ast_channel_language_set(chan, pvt->language);
    ast_jb_configure(chan, &global_jbconf);
    ast_channel_stage_snapshot_done(chan);
    ast_channel_unlock(chan);
    if (state != AST_STATE_DOWN) {
       if (ast_pbx_start(chan)) {
          ast_channel_hangupcause_set(chan, AST_CAUSE_SWITCH_CONGESTION);
          ast_hangup(chan);
          chan = NULL;
       } else
          start_stream(pvt);
    }
    return chan;
 }
console_read()
static struct ast_frame * console_read (struct ast_channel * chan) static
Definition at line 575 of file chan_console.c.
References ast_debug, and ast_null_frame.
 {
    ast_debug(1, "I should not be called ...\n");
    return &ast_null_frame;
 }
console_request()
static struct ast_channel * console_request (const char * type, struct ast_format_cap * cap, const struct ast_assigned_ids * assignedids, const struct ast_channel * requestor, const char * data, int * cause) static
Channel Technology Callbacks
Definition at line 471 of file chan_console.c.
References AST_CAUSE_BUSY, ast_format_cap_get_names(), ast_format_cap_iscompatible(), AST_FORMAT_CAP_NAMES_LEN, ast_log, AST_STATE_DOWN, ast_str_alloca, ast_channel_tech::capabilities, console_new(), console_pvt_lock, console_pvt_unlock, find_pvt(), LOG_ERROR, LOG_NOTICE, LOG_WARNING, NULL, console_pvt::owner, and unref_pvt().
 {
    struct ast_channel *chan = NULL;
    struct console_pvt *pvt;
    if (!(pvt = find_pvt(data))) {
       ast_log(LOG_ERROR, "Console device '%s' not found\n", data);
       return NULL;
    }
    if (!(ast_format_cap_iscompatible(cap, console_tech.capabilities))) {
       struct ast_str *cap_buf = ast_str_alloca(AST_FORMAT_CAP_NAMES_LEN);
       ast_log(LOG_NOTICE, "Channel requested with unsupported format(s): '%s'\n",
          ast_format_cap_get_names(cap, &cap_buf));
       goto return_unref;
    }
    if (pvt->owner) {
       ast_log(LOG_NOTICE, "Console channel already active!\n");
       *cause = AST_CAUSE_BUSY;
       goto return_unref;
    }
    console_pvt_lock(pvt);
    chan = console_new(pvt, NULL, NULL, AST_STATE_DOWN, assignedids, requestor);
    console_pvt_unlock(pvt);
    if (!chan)
       ast_log(LOG_WARNING, "Unable to create new Console channel!\n");
 return_unref:
    unref_pvt(pvt);
    return chan;
 }
console_text()
static int console_text (struct ast_channel * c, const char * text) static
Definition at line 522 of file chan_console.c.
References ast_verb, V_BEGIN, and V_END.
 {
    ast_verb(1, V_BEGIN "Console Received Text '%s'" V_END, text);
    return 0;
 }
console_write()
static int console_write (struct ast_channel * chan, struct ast_frame * f) static
Definition at line 612 of file chan_console.c.
References ast_channel_tech_pvt(), console_pvt_lock, console_pvt_unlock, ast_frame::data, ast_frame::ptr, ast_frame::samples, and console_pvt::stream.
 {
    struct console_pvt *pvt = ast_channel_tech_pvt(chan);
    console_pvt_lock(pvt);
    Pa_WriteStream(pvt->stream, f->data.ptr, f->samples);
    console_pvt_unlock(pvt);
    return 0;
 }
destroy_pvts()
static void destroy_pvts (void) static
Definition at line 1404 of file chan_console.c.
References active_lock, ao2_iterator_destroy(), ao2_iterator_init(), ao2_iterator_next, ao2_unlink, ast_rwlock_unlock, ast_rwlock_wrlock, console_pvt::destroy, and unref_pvt().
Referenced by load_config().
 {
    struct ao2_iterator i;
    struct console_pvt *pvt;
    i = ao2_iterator_init(pvts, 0);
    while ((pvt = ao2_iterator_next(&i))) {
       if (pvt->destroy) {
          ao2_unlink(pvts, pvt);
          ast_rwlock_wrlock(&active_lock);
          if (active_pvt == pvt)
             active_pvt = unref_pvt(pvt);
          ast_rwlock_unlock(&active_lock);
       }
       unref_pvt(pvt);
    }
    ao2_iterator_destroy(&i);
 }
find_pvt()
static struct console_pvt* find_pvt (const char * name) static
Definition at line 246 of file chan_console.c.
References ao2_find, console_pvt::name, and OBJ_POINTER.
Referenced by build_device(), cli_console_active(), and console_request().
 {
    struct console_pvt tmp_pvt = {
       .name = name,
    };
    return ao2_find(pvts, &tmp_pvt, OBJ_POINTER);
 }
get_active_pvt()
static struct console_pvt* get_active_pvt (void) static
Definition at line 703 of file chan_console.c.
References active_lock, ast_rwlock_rdlock, ast_rwlock_unlock, and ref_pvt().
Referenced by cli_console_active(), cli_console_answer(), cli_console_autoanswer(), cli_console_dial(), cli_console_flash(), cli_console_hangup(), cli_console_mute(), and cli_console_sendtext().
 {
    struct console_pvt *pvt;
    ast_rwlock_rdlock(&active_lock);
    pvt = ref_pvt(active_pvt);
    ast_rwlock_unlock(&active_lock);
    return pvt;
 }
init_pvt()
static int init_pvt (struct console_pvt * pvt, const char * name) static
Definition at line 1356 of file chan_console.c.
References AST_PTHREADT_NULL, ast_string_field_init, ast_string_field_set, S_OR, and console_pvt::thread.
Referenced by build_device(), and load_module().
 {
    pvt->thread = AST_PTHREADT_NULL;
    if (ast_string_field_init(pvt, 32))
       return -1;
    ast_string_field_set(pvt, name, S_OR(name, ""));
    return 0;
 }
load_config()
static int load_config (int reload) static
Load the configuration.
Parameters
reload if this was called due to a reload
Return values
0 success
-1 failure
Definition at line 1429 of file chan_console.c.
References ao2_callback, ast_category_browse(), ast_config_destroy(), ast_config_load, ast_log, ast_mutex_lock, ast_mutex_unlock, ast_variable_browse(), build_device(), config_file, CONFIG_STATUS_FILEINVALID, console_pvt::context, destroy_pvts(), global_jbconf, globals, globals_lock, LOG_NOTICE, ast_variable::name, ast_variable::next, NULL, OBJ_NODATA, pvt_mark_destroy_cb(), set_pvt_defaults(), store_config_core(), and ast_variable::value.
Referenced by load_module(), and reload().
 {
    struct ast_config *cfg;
    struct ast_variable *v;
    struct ast_flags config_flags = { 0 };
    char *context = NULL;
    /* default values */
    memcpy(&global_jbconf, &default_jbconf, sizeof(global_jbconf));
    ast_mutex_lock(&globals_lock);
    set_pvt_defaults(&globals);
    ast_mutex_unlock(&globals_lock);
    if (!(cfg = ast_config_load(config_file, config_flags))) {
       ast_log(LOG_NOTICE, "Unable to open configuration file %s!\n", config_file);
       return -1;
    } else if (cfg == CONFIG_STATUS_FILEINVALID) {
       ast_log(LOG_NOTICE, "Config file %s has an invalid format\n", config_file);
       return -1;
    }
    ao2_callback(pvts, OBJ_NODATA, pvt_mark_destroy_cb, NULL);
    ast_mutex_lock(&globals_lock);
    for (v = ast_variable_browse(cfg, "general"); v; v = v->next)
       store_config_core(&globals, v->name, v->value);
    ast_mutex_unlock(&globals_lock);
    while ((context = ast_category_browse(cfg, context))) {
       if (strcasecmp(context, "general"))
          build_device(cfg, context);
    }
    ast_config_destroy(cfg);
    destroy_pvts();
    return 0;
 }
load_module()
static int load_module (void) static
Load the module.
Module loading including tests for configuration or dependencies. This function can return AST_MODULE_LOAD_FAILURE, AST_MODULE_LOAD_DECLINE, or AST_MODULE_LOAD_SUCCESS. If a dependency or environment variable fails tests return AST_MODULE_LOAD_FAILURE. If the module can not load the configuration file or other non-critical problem return AST_MODULE_LOAD_DECLINE. On success return AST_MODULE_LOAD_SUCCESS.
Definition at line 1526 of file chan_console.c.
References AO2_ALLOC_OPT_LOCK_MUTEX, ao2_container_alloc_hash, ao2_ref, ARRAY_LEN, ast_channel_register(), ast_channel_unregister(), ast_cli_register_multiple, ast_cli_unregister_multiple(), ast_format_cap_alloc, ast_format_cap_append, AST_FORMAT_CAP_FLAG_DEFAULT, ast_format_slin16, ast_log, AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, ast_channel_tech::capabilities, globals, init_pvt(), load_config(), LOG_ERROR, LOG_WARNING, NULL, NUM_PVT_BUCKETS, pvt_cmp_cb(), pvt_destructor(), and pvt_hash_cb().
Referenced by reload().
 {
    PaError res;
    if (!(console_tech.capabilities = ast_format_cap_alloc(AST_FORMAT_CAP_FLAG_DEFAULT))) {
       return AST_MODULE_LOAD_DECLINE;
    }
    ast_format_cap_append(console_tech.capabilities, ast_format_slin16, 0);
    init_pvt(&globals, NULL);
    pvts = ao2_container_alloc_hash(AO2_ALLOC_OPT_LOCK_MUTEX, 0, NUM_PVT_BUCKETS,
       pvt_hash_cb, NULL, pvt_cmp_cb);
    if (!pvts)
       goto return_error;
    if (load_config(0))
       goto return_error;
    res = Pa_Initialize();
    if (res != paNoError) {
       ast_log(LOG_WARNING, "Failed to initialize audio system - (%d) %s\n",
          res, Pa_GetErrorText(res));
       goto return_error_pa_init;
    }
    if (ast_channel_register(&console_tech)) {
       ast_log(LOG_ERROR, "Unable to register channel type 'Console'\n");
       goto return_error_chan_reg;
    }
    if (ast_cli_register_multiple(cli_console, ARRAY_LEN(cli_console)))
       goto return_error_cli_reg;
    return AST_MODULE_LOAD_SUCCESS;
 return_error_cli_reg:
    ast_cli_unregister_multiple(cli_console, ARRAY_LEN(cli_console));
 return_error_chan_reg:
    ast_channel_unregister(&console_tech);
 return_error_pa_init:
    Pa_Terminate();
 return_error:
    if (pvts)
       ao2_ref(pvts, -1);
    pvts = NULL;
    ao2_ref(console_tech.capabilities, -1);
    console_tech.capabilities = NULL;
    pvt_destructor(&globals);
    return AST_MODULE_LOAD_DECLINE;
 }
open_stream()
static int open_stream (struct console_pvt * pvt) static
Definition at line 297 of file chan_console.c.
References ast_log, INPUT_CHANNELS, console_pvt::input_device, LOG_ERROR, console_pvt::name, NULL, NUM_SAMPLES, OUTPUT_CHANNELS, console_pvt::output_device, SAMPLE_RATE, and console_pvt::stream.
Referenced by start_stream().
 {
    int res = paInternalError;
    if (!strcasecmp(pvt->input_device, "default") &&
       !strcasecmp(pvt->output_device, "default")) {
       res = Pa_OpenDefaultStream(&pvt->stream, INPUT_CHANNELS, OUTPUT_CHANNELS,
          paInt16, SAMPLE_RATE, NUM_SAMPLES, NULL, NULL);
    } else {
       PaStreamParameters input_params = {
          .channelCount = 1,
          .sampleFormat = paInt16,
          .suggestedLatency = (1.0 / 50.0), /* 20 ms */
          .device = paNoDevice,
       };
       PaStreamParameters output_params = {
          .channelCount = 1,
          .sampleFormat = paInt16,
          .suggestedLatency = (1.0 / 50.0), /* 20 ms */
          .device = paNoDevice,
       };
       PaDeviceIndex idx, num_devices, def_input, def_output;
       if (!(num_devices = Pa_GetDeviceCount()))
          return res;
       def_input = Pa_GetDefaultInputDevice();
       def_output = Pa_GetDefaultOutputDevice();
       for (idx = 0;
          idx < num_devices && (input_params.device == paNoDevice
             || output_params.device == paNoDevice);
          idx++)
       {
          const PaDeviceInfo *dev = Pa_GetDeviceInfo(idx);
          if (dev->maxInputChannels) {
             if ( (idx == def_input && !strcasecmp(pvt->input_device, "default")) ||
                !strcasecmp(pvt->input_device, dev->name) )
                input_params.device = idx;
          }
          if (dev->maxOutputChannels) {
             if ( (idx == def_output && !strcasecmp(pvt->output_device, "default")) ||
                !strcasecmp(pvt->output_device, dev->name) )
                output_params.device = idx;
          }
       }
       if (input_params.device == paNoDevice)
          ast_log(LOG_ERROR, "No input device found for console device '%s'\n", pvt->name);
       if (output_params.device == paNoDevice)
          ast_log(LOG_ERROR, "No output device found for console device '%s'\n", pvt->name);
       res = Pa_OpenStream(&pvt->stream, &input_params, &output_params,
          SAMPLE_RATE, NUM_SAMPLES, paNoFlag, NULL, NULL);
    }
    return res;
 }
pvt_cmp_cb()
static int pvt_cmp_cb (void * obj, void * arg, int flags) static
Definition at line 1476 of file chan_console.c.
References CMP_MATCH, CMP_STOP, and console_pvt::name.
Referenced by load_module().
 {
    struct console_pvt *pvt = obj, *pvt2 = arg;
    return !strcasecmp(pvt->name, pvt2->name) ? CMP_MATCH | CMP_STOP : 0;
 }
pvt_destructor()
static void pvt_destructor (void * obj) static
Definition at line 1349 of file chan_console.c.
References ast_string_field_free_memory.
Referenced by build_device(), load_module(), and unload_module().
 {
    struct console_pvt *pvt = obj;
    ast_string_field_free_memory(pvt);
 }
pvt_hash_cb()
static int pvt_hash_cb (const void * obj, const int flags) static
Definition at line 1469 of file chan_console.c.
References ast_str_case_hash(), and console_pvt::name.
Referenced by load_module().
 {
    const struct console_pvt *pvt = obj;
    return ast_str_case_hash(pvt->name);
 }
pvt_mark_destroy_cb()
static int pvt_mark_destroy_cb (void * obj, void * arg, int flags) static
Definition at line 1397 of file chan_console.c.
References console_pvt::destroy.
Referenced by load_config().
 {
    struct console_pvt *pvt = obj;
    pvt->destroy = 1;
    return 0;
 }
ref_pvt()
static struct console_pvt* ref_pvt (struct console_pvt * pvt) static
Definition at line 233 of file chan_console.c.
References ao2_ref.
Referenced by console_new(), get_active_pvt(), and set_active().
 {
    if (pvt)
       ao2_ref(pvt, +1);
    return pvt;
 }
reload()
static int reload (void) static
Definition at line 1579 of file chan_console.c.
References AST_MODFLAG_LOAD_ORDER, AST_MODPRI_CHANNEL_DRIVER, AST_MODULE_INFO(), AST_MODULE_SUPPORT_EXTENDED, ASTERISK_GPL_KEY, load_config(), load_module(), and unload_module().
 {
    return load_config(1);
 }
set_active()
static void set_active (struct console_pvt * pvt, const char * value) static
Definition at line 1174 of file chan_console.c.
References active_lock, ast_log, ast_rwlock_unlock, ast_rwlock_wrlock, ast_true(), globals, LOG_ERROR, ref_pvt(), and unref_pvt().
Referenced by cli_console_active(), and store_config_core().
 {
    if (pvt == &globals) {
       ast_log(LOG_ERROR, "active is only valid as a per-device setting\n");
       return;
    }
    if (!ast_true(value))
       return;
    ast_rwlock_wrlock(&active_lock);
    if (active_pvt)
       unref_pvt(active_pvt);
    active_pvt = ref_pvt(pvt);
    ast_rwlock_unlock(&active_lock);
 }
set_pvt_defaults()
static void set_pvt_defaults (struct console_pvt * pvt) static
Set default values for a pvt struct.
Note
This function expects the pvt lock to be held.
Definition at line 1274 of file chan_console.c.
References ast_mutex_lock, ast_mutex_unlock, ast_string_field_set, console_pvt::autoanswer, console_pvt::cid_name, console_pvt::cid_num, console_pvt::context, console_pvt::exten, globals, globals_lock, console_pvt::language, console_pvt::mohinterpret, console_pvt::overridecontext, and console_pvt::parkinglot.
Referenced by build_device(), and load_config().
 {
    if (pvt == &globals) {
       ast_string_field_set(pvt, mohinterpret, "default");
       ast_string_field_set(pvt, context, "default");
       ast_string_field_set(pvt, exten, "s");
       ast_string_field_set(pvt, language, "");
       ast_string_field_set(pvt, cid_num, "");
       ast_string_field_set(pvt, cid_name, "");
       ast_string_field_set(pvt, parkinglot, "");
       pvt->overridecontext = 0;
       pvt->autoanswer = 0;
    } else {
       ast_mutex_lock(&globals_lock);
       ast_string_field_set(pvt, mohinterpret, globals.mohinterpret);
       ast_string_field_set(pvt, context, globals.context);
       ast_string_field_set(pvt, exten, globals.exten);
       ast_string_field_set(pvt, language, globals.language);
       ast_string_field_set(pvt, cid_num, globals.cid_num);
       ast_string_field_set(pvt, cid_name, globals.cid_name);
       ast_string_field_set(pvt, parkinglot, globals.parkinglot);
       pvt->overridecontext = globals.overridecontext;
       pvt->autoanswer = globals.autoanswer;
       ast_mutex_unlock(&globals_lock);
    }
 }
start_stream()
static int start_stream (struct console_pvt * pvt) static
Definition at line 358 of file chan_console.c.
References ast_debug, ast_log, ast_pthread_create_background, console_pvt_lock, console_pvt_unlock, LOG_ERROR, LOG_WARNING, NULL, open_stream(), console_pvt::owner, console_pvt::stream, stream_monitor(), console_pvt::streamstate, and console_pvt::thread.
Referenced by console_answer(), console_call(), and console_new().
 {
    PaError res;
    int ret_val = 0;
    console_pvt_lock(pvt);
    /* It is possible for console_hangup to be called before the
     * stream is started, if this is the case pvt->owner will be NULL
     * and start_stream should be aborted. */
    if (pvt->streamstate || !pvt->owner)
       goto return_unlock;
    pvt->streamstate = 1;
    ast_debug(1, "Starting stream\n");
    res = open_stream(pvt);
    if (res != paNoError) {
       ast_log(LOG_WARNING, "Failed to open stream - (%d) %s\n",
          res, Pa_GetErrorText(res));
       ret_val = -1;
       goto return_unlock;
    }
    res = Pa_StartStream(pvt->stream);
    if (res != paNoError) {
       ast_log(LOG_WARNING, "Failed to start stream - (%d) %s\n",
          res, Pa_GetErrorText(res));
       ret_val = -1;
       goto return_unlock;
    }
    if (ast_pthread_create_background(&pvt->thread, NULL, stream_monitor, pvt)) {
       ast_log(LOG_ERROR, "Failed to start stream monitor thread\n");
       ret_val = -1;
    }
 return_unlock:
    console_pvt_unlock(pvt);
    return ret_val;
 }
stop_stream()
static int stop_stream (struct console_pvt * pvt) static
Definition at line 401 of file chan_console.c.
References AST_PTHREADT_NULL, console_pvt_lock, console_pvt_unlock, NULL, console_pvt::stream, console_pvt::streamstate, and console_pvt::thread.
Referenced by console_hangup(), and stop_streams().
 {
    if (!pvt->streamstate || pvt->thread == AST_PTHREADT_NULL)
       return 0;
    pthread_cancel(pvt->thread);
    pthread_kill(pvt->thread, SIGURG);
    pthread_join(pvt->thread, NULL);
    console_pvt_lock(pvt);
    Pa_AbortStream(pvt->stream);
    Pa_CloseStream(pvt->stream);
    pvt->stream = NULL;
    pvt->streamstate = 0;
    console_pvt_unlock(pvt);
    return 0;
 }
stop_streams()
static void stop_streams (void) static
Definition at line 1483 of file chan_console.c.
References ao2_iterator_destroy(), ao2_iterator_init(), ao2_iterator_next, console_pvt::hookstate, stop_stream(), and unref_pvt().
Referenced by unload_module().
 {
    struct console_pvt *pvt;
    struct ao2_iterator i;
    i = ao2_iterator_init(pvts, 0);
    while ((pvt = ao2_iterator_next(&i))) {
       if (pvt->hookstate)
          stop_stream(pvt);
       unref_pvt(pvt);
    }
    ao2_iterator_destroy(&i);
 }
store_callerid()
static void store_callerid (struct console_pvt * pvt, const char * value) static
Definition at line 1305 of file chan_console.c.
References ast_callerid_split(), ast_string_field_set, console_pvt::cid_name, and console_pvt::cid_num.
Referenced by store_config_core().
 {
    char cid_name[256];
    char cid_num[256];
    ast_callerid_split(value, cid_name, sizeof(cid_name),
       cid_num, sizeof(cid_num));
    ast_string_field_set(pvt, cid_name, cid_name);
    ast_string_field_set(pvt, cid_num, cid_num);
 }
store_config_core()
static void store_config_core (struct console_pvt * pvt, const char * var, const char * value) static
Store a configuration parameter in a pvt struct.
Note
This function expects the pvt lock to be held.
Definition at line 1322 of file chan_console.c.
References ast_jb_read_conf(), ast_log, console_pvt::autoanswer, console_pvt::context, CV_BOOL, CV_END, CV_F, CV_START, CV_STRFIELD, console_pvt::exten, global_jbconf, globals, console_pvt::input_device, console_pvt::language, LOG_WARNING, console_pvt::mohinterpret, console_pvt::output_device, console_pvt::overridecontext, console_pvt::parkinglot, set_active(), and store_callerid().
Referenced by build_device(), and load_config().
 {
    if (pvt == &globals && !ast_jb_read_conf(&global_jbconf, var, value))
       return;
    CV_START(var, value);
    CV_STRFIELD("context", pvt, context);
    CV_STRFIELD("extension", pvt, exten);
    CV_STRFIELD("mohinterpret", pvt, mohinterpret);
    CV_STRFIELD("language", pvt, language);
    CV_F("callerid", store_callerid(pvt, value));
    CV_BOOL("overridecontext", pvt->overridecontext);
    CV_BOOL("autoanswer", pvt->autoanswer);
    CV_STRFIELD("parkinglot", pvt, parkinglot);
    if (pvt != &globals) {
       CV_F("active", set_active(pvt, value))
       CV_STRFIELD("input_device", pvt, input_device);
       CV_STRFIELD("output_device", pvt, output_device);
    }
    ast_log(LOG_WARNING, "Unknown option '%s'\n", var);
    CV_END;
 }
stream_monitor()
static void* stream_monitor (void * data) static
Stream monitor thread.
data A pointer to the console_pvt structure that contains the portaudio stream that needs to be monitored.
This function runs in its own thread to monitor data coming in from a portaudio stream. When enough data is available, it is queued up to be read from the Asterisk channel.
Definition at line 265 of file chan_console.c.
References ast_format_slin16, AST_FRAME_VOICE, ast_queue_frame(), buf, console_pvt_lock, console_pvt_unlock, ast_frame::frametype, NULL, NUM_SAMPLES, console_pvt::owner, ast_frame::samples, and console_pvt::stream.
Referenced by start_stream().
 {
    struct console_pvt *pvt = data;
    char buf[NUM_SAMPLES * sizeof(int16_t)];
    PaError res;
    struct ast_frame f = {
       .frametype = AST_FRAME_VOICE,
       .subclass.format = ast_format_slin16,
       .src = "console_stream_monitor",
       .data.ptr = buf,
       .datalen = sizeof(buf),
       .samples = sizeof(buf) / sizeof(int16_t),
    };
    for (;;) {
       pthread_testcancel();
       console_pvt_lock(pvt);
       res = Pa_ReadStream(pvt->stream, buf, sizeof(buf) / sizeof(int16_t));
       console_pvt_unlock(pvt);
       pthread_testcancel();
       if (!pvt->owner) {
          return NULL;
       }
       if (res == paNoError)
          ast_queue_frame(pvt->owner, &f);
    }
    return NULL;
 }
unload_module()
static int unload_module (void) static
Definition at line 1497 of file chan_console.c.
References ao2_ref, ARRAY_LEN, ast_channel_unregister(), ast_cli_unregister_multiple(), ast_channel_tech::capabilities, globals, NULL, pvt_destructor(), and stop_streams().
Referenced by reload().
 {
    ao2_ref(console_tech.capabilities, -1);
    console_tech.capabilities = NULL;
    ast_channel_unregister(&console_tech);
    ast_cli_unregister_multiple(cli_console, ARRAY_LEN(cli_console));
    stop_streams();
    Pa_Terminate();
    /* Will unref all the pvts so they will get destroyed, too */
    ao2_ref(pvts, -1);
    pvt_destructor(&globals);
    return 0;
 }
unref_pvt()
static struct console_pvt* unref_pvt (struct console_pvt * pvt) static
Definition at line 240 of file chan_console.c.
References ao2_ref, and NULL.
Referenced by build_device(), cli_console_active(), cli_console_answer(), cli_console_autoanswer(), cli_console_dial(), cli_console_flash(), cli_console_hangup(), cli_console_mute(), cli_console_sendtext(), cli_list_devices(), console_hangup(), console_request(), destroy_pvts(), set_active(), and stop_streams().
 {
    ao2_ref(pvt, -1);
    return NULL;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Console Channel Driver" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_EXTENDED, .load = load_module, .unload = unload_module, .reload = reload, .load_pri = AST_MODPRI_CHANNEL_DRIVER, } static
Definition at line 1590 of file chan_console.c.
active_lock
ast_rwlock_t active_lock = { PTHREAD_RWLOCK_INITIALIZER , NULL, {1, 0} } static
Definition at line 178 of file chan_console.c.
Referenced by destroy_pvts(), get_active_pvt(), and set_active().
active_pvt
struct console_pvt* active_pvt static
Definition at line 177 of file chan_console.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 1590 of file chan_console.c.
cli_console
struct ast_cli_entry cli_console[] static
Definition at line 1256 of file chan_console.c.
config_file
const char config_file[] = "console.conf" static
Definition at line 118 of file chan_console.c.
Referenced by load_config().
console_tech
struct ast_channel_tech console_tech static
Definition at line 211 of file chan_console.c.
default_jbconf
struct ast_jb_conf default_jbconf static
Global jitterbuffer configuration.
Note
Disabled by default.
Values shown here match the defaults shown in console.conf.sample
Definition at line 186 of file chan_console.c.
global_jbconf
struct ast_jb_conf global_jbconf static
Definition at line 193 of file chan_console.c.
Referenced by console_new(), load_config(), and store_config_core().
globals
struct console_pvt globals static
Referenced by __ast_udptl_reload(), acf_jabberreceive_read(), acf_jabberstatus_read(), app_exec(), ast_get_builtin_feature(), ast_get_chan_applicationmap(), ast_get_chan_featuremap_config(), ast_get_chan_features_general_config(), ast_get_chan_features_pickup_config(), ast_get_chan_features_xfer_config(), ast_named_acl_find(), AST_TEST_DEFINE(), ast_udptl_new_with_bindaddr(), ast_xmpp_client_find(), check_featuregroup(), cli_complete_notify(), cli_display_named_acl(), cli_display_named_acl_list(), cli_notify(), delete_old_messages(), generate_or_link_lots_to_configs(), get_feature_ds(), global_loaded_observer(), handle_cli_show_config(), handle_feature_show(), handle_show_named_acl_cmd(), handle_skel_show_config(), handle_skel_show_levels(), jingle_config_alloc(), jingle_endpoint_state_find_or_create(), jingle_request(), load_config(), load_module(), manager_jabber_send(), nominal_test(), off_nominal_test(), parking_dynamic_lots_enabled(), remove_all_configured_parking_lot_extensions(), set_active(), set_pvt_defaults(), skel_find_or_create_state(), stasis_cleanup(), stasis_init(), stasis_message_type_declined(), store_config_core(), unbound_config_apply_default(), unbound_resolver_resolve(), unload_features_config(), unload_module(), xmpp_action_hook(), xmpp_cli_create_collection(), xmpp_cli_create_leafnode(), xmpp_cli_delete_pubsub_node(), xmpp_cli_list_pubsub_nodes(), xmpp_cli_purge_pubsub_nodes(), xmpp_client_config_post_apply(), xmpp_client_find_or_create(), xmpp_client_reconnect(), xmpp_client_send_message(), xmpp_client_set_group_presence(), xmpp_client_set_presence(), xmpp_client_thread(), xmpp_component_register_get_hook(), xmpp_component_service_discovery_get_hook(), xmpp_component_service_discovery_items_hook(), xmpp_config_post_apply(), xmpp_config_prelink(), xmpp_connect_hook(), xmpp_init_event_distribution(), xmpp_join_exec(), xmpp_leave_exec(), xmpp_log_hook(), xmpp_pubsub_build_publish_skeleton(), xmpp_pubsub_handle_error(), xmpp_pubsub_iq_create(), xmpp_pubsub_publish_device_state(), xmpp_pubsub_subscribe(), xmpp_roster_hook(), xmpp_send_cb(), xmpp_send_exec(), xmpp_sendgroup_exec(), xmpp_show_buddies(), and xmpp_show_clients().
globals_lock
ast_mutex_t globals_lock = { PTHREAD_RECURSIVE_MUTEX_INITIALIZER_NP , NULL, {1, 0} } static
Definition at line 172 of file chan_console.c.
Referenced by load_config(), and set_pvt_defaults().
pvts
struct ao2_container* pvts static
Definition at line 174 of file chan_console.c.