Asterisk - The Open Source Telephony Project: app_senddtmf.c File Reference
app_senddtmf.c File Reference
Dial plan applications
App to send DTMF digits.
#include "asterisk.h"
#include "asterisk/pbx.h"
#include "asterisk/module.h"
#include "asterisk/app.h"
#include "asterisk/manager.h"
#include "asterisk/channel.h"
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int load_module (void)
static int manager_play_dtmf (struct mansession *s, const struct message *m)
static int senddtmf_exec (struct ast_channel *chan, const char *vdata)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Send DTMF digits Application" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, }
static const struct ast_module_info * ast_module_info = &__mod_info
static const char senddtmf_name [] = "SendDTMF"
Detailed Description
App to send DTMF digits.
Author
Mark Spencer marks.nosp@m.ter@.nosp@m.digiu.nosp@m.m.co.nosp@m.m
Definition in file app_senddtmf.c.
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 210 of file app_senddtmf.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 210 of file app_senddtmf.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 210 of file app_senddtmf.c.
load_module()
static int load_module (void) static
Definition at line 200 of file app_senddtmf.c.
References ast_manager_register_xml, ast_register_application_xml, EVENT_FLAG_CALL, manager_play_dtmf(), senddtmf_exec(), and senddtmf_name.
 {
    int res;
    res = ast_manager_register_xml("PlayDTMF", EVENT_FLAG_CALL, manager_play_dtmf);
    res |= ast_register_application_xml(senddtmf_name, senddtmf_exec);
    return res;
 }
manager_play_dtmf()
static int manager_play_dtmf (struct mansession * s, const struct message * m) static
Definition at line 148 of file app_senddtmf.c.
References ast_channel_get_by_name(), ast_channel_unref, AST_FRAME_DTMF, ast_queue_frame(), ast_senddigit_external(), ast_strlen_zero, ast_true(), astman_get_header(), astman_send_ack(), astman_send_error(), digit, ast_frame_subclass::integer, ast_frame::len, and ast_frame::subclass.
Referenced by load_module().
 {
    const char *channel = astman_get_header(m, "Channel");
    const char *digit = astman_get_header(m, "Digit");
    const char *duration = astman_get_header(m, "Duration");
    const char *receive_s = astman_get_header(m, "Receive");
    struct ast_channel *chan;
    unsigned int duration_ms = 0;
    if (!(chan = ast_channel_get_by_name(channel))) {
       astman_send_error(s, m, "Channel not found");
       return 0;
    }
    if (ast_strlen_zero(digit)) {
       astman_send_error(s, m, "No digit specified");
       chan = ast_channel_unref(chan);
       return 0;
    }
    if (!ast_strlen_zero(duration) && (sscanf(duration, "%30u", &duration_ms) != 1)) {
       astman_send_error(s, m, "Could not convert Duration parameter");
       chan = ast_channel_unref(chan);
       return 0;
    }
    if (ast_true(receive_s)) {
       struct ast_frame f = { AST_FRAME_DTMF, };
       f.len = duration_ms;
       f.subclass.integer = *digit;
       ast_queue_frame(chan, &f);
    } else {
       ast_senddigit_external(chan, *digit, duration_ms);
    }
    chan = ast_channel_unref(chan);
    astman_send_ack(s, m, "DTMF successfully queued");
    return 0;
 }
senddtmf_exec()
static int senddtmf_exec (struct ast_channel * chan, const char * vdata) static
Definition at line 95 of file app_senddtmf.c.
References args, AST_APP_ARG, ast_app_parse_timelen(), ast_channel_get_by_name(), ast_channel_unref, AST_DECLARE_APP_ARGS, ast_dtmf_stream(), ast_log, AST_STANDARD_APP_ARGS, ast_strdupa, ast_strlen_zero, LOG_WARNING, NULL, and TIMELEN_MILLISECONDS.
Referenced by load_module().
 {
    int res;
    char *data;
    int dinterval = 0, duration = 0;
    struct ast_channel *chan_found = NULL;
    struct ast_channel *chan_dest = chan;
    struct ast_channel *chan_autoservice = NULL;
    AST_DECLARE_APP_ARGS(args,
       AST_APP_ARG(digits);
       AST_APP_ARG(dinterval);
       AST_APP_ARG(duration);
       AST_APP_ARG(channel);
    );
    if (ast_strlen_zero(vdata)) {
       ast_log(LOG_WARNING, "SendDTMF requires an argument\n");
       return 0;
    }
    data = ast_strdupa(vdata);
    AST_STANDARD_APP_ARGS(args, data);
    if (ast_strlen_zero(args.digits)) {
       ast_log(LOG_WARNING, "The digits argument is required (0-9,*#,a-d,A-D,wfF)\n");
       return 0;
    }
    if (!ast_strlen_zero(args.dinterval)) {
       ast_app_parse_timelen(args.dinterval, &dinterval, TIMELEN_MILLISECONDS);
    }
    if (!ast_strlen_zero(args.duration)) {
       ast_app_parse_timelen(args.duration, &duration, TIMELEN_MILLISECONDS);
    }
    if (!ast_strlen_zero(args.channel)) {
       chan_found = ast_channel_get_by_name(args.channel);
       if (!chan_found) {
          ast_log(LOG_WARNING, "No such channel: %s\n", args.channel);
          return 0;
       }
       chan_dest = chan_found;
       if (chan_found != chan) {
          chan_autoservice = chan;
       }
    }
    res = ast_dtmf_stream(chan_dest, chan_autoservice, args.digits,
       dinterval <= 0 ? 250 : dinterval, duration);
    if (chan_found) {
       ast_channel_unref(chan_found);
    }
    return chan_autoservice ? 0 : res;
 }
unload_module()
static int unload_module (void) static
Definition at line 190 of file app_senddtmf.c.
References ast_manager_unregister(), ast_unregister_application(), and senddtmf_name.
 {
    int res;
    res = ast_unregister_application(senddtmf_name);
    res |= ast_manager_unregister("PlayDTMF");
    return res;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Send DTMF digits Application" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, } static
Definition at line 210 of file app_senddtmf.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 210 of file app_senddtmf.c.
senddtmf_name
const char senddtmf_name[] = "SendDTMF" static
Definition at line 93 of file app_senddtmf.c.
Referenced by load_module(), and unload_module().