Asterisk - The Open Source Telephony Project: app_url.c File Reference
app_url.c File Reference
Dial plan applications
App to transmit a URL.
#include "asterisk.h"
#include "asterisk/pbx.h"
#include "asterisk/module.h"
#include "asterisk/app.h"
#include "asterisk/channel.h"
Enumerations
enum option_flags { OPTION_CHEAT = (1 << 0), OPTION_NUMGAMES = (1 << 1), OPTION_WAIT = (1 << 0), OPTION_PATTERNS_DISABLED = (1 << 0) }
Functions
AST_MODULE_INFO_STANDARD_DEPRECATED (ASTERISK_GPL_KEY, "Send URL Applications")
static int load_module (void)
static int sendurl_exec (struct ast_channel *chan, const char *data)
static int unload_module (void)
Variables
static char * app = "SendURL"
static const struct ast_app_option app_opts [128] = { [ 'w' ] = { .flag = OPTION_WAIT }, }
Detailed Description
App to transmit a URL.
Author
Mark Spencer marks.nosp@m.ter@.nosp@m.digiu.nosp@m.m.co.nosp@m.m
Definition in file app_url.c.
Enumeration Type Documentation
option_flags
enum option_flags
Enumerator
OPTION_CHEAT
OPTION_NUMGAMES
OPTION_WAIT
OPTION_PATTERNS_DISABLED
Definition at line 87 of file app_url.c.
                   {
    OPTION_WAIT = (1 << 0),
 };
Function Documentation
AST_MODULE_INFO_STANDARD_DEPRECATED()
AST_MODULE_INFO_STANDARD_DEPRECATED (ASTERISK_GPL_KEY , "Send URL Applications")
Referenced by load_module().
load_module()
static int load_module (void) static
Definition at line 175 of file app_url.c.
References app, AST_MODULE_INFO_STANDARD_DEPRECATED(), ast_register_application_xml, ASTERISK_GPL_KEY, and sendurl_exec().
 {
    return ast_register_application_xml(app, sendurl_exec);
 }
sendurl_exec()
static int sendurl_exec (struct ast_channel * chan, const char * data) static
Definition at line 95 of file app_url.c.
References app_opts, args, AST_APP_ARG, ast_app_parse_options(), ast_channel_sendurl(), ast_channel_supports_html(), AST_DECLARE_APP_ARGS, AST_FRAME_HTML, ast_frfree, AST_HTML_LDCOMPLETE, AST_HTML_NOSUPPORT, ast_log, ast_read(), AST_STANDARD_APP_ARGS, ast_strdupa, ast_strlen_zero, ast_test_flag, ast_waitfor(), ast_frame::frametype, ast_frame_subclass::integer, LOG_WARNING, OPTION_WAIT, options, out, pbx_builtin_setvar_helper(), status, ast_frame::subclass, tmp(), and url.
Referenced by load_module().
 {
    int res = 0;
    char *tmp;
    struct ast_frame *f;
    char *status = "FAILURE";
    char *opts[0];
    struct ast_flags flags = { 0 };
    AST_DECLARE_APP_ARGS(args,
       AST_APP_ARG(url);
       AST_APP_ARG(options);
    );
    if (ast_strlen_zero(data)) {
       ast_log(LOG_WARNING, "SendURL requires an argument (URL)\n");
       pbx_builtin_setvar_helper(chan, "SENDURLSTATUS", status);
       return -1;
    }
    tmp = ast_strdupa(data);
    AST_STANDARD_APP_ARGS(args, tmp);
    if (args.argc == 2)
       ast_app_parse_options(app_opts, &flags, opts, args.options);
    if (!ast_channel_supports_html(chan)) {
       /* Does not support transport */
       pbx_builtin_setvar_helper(chan, "SENDURLSTATUS", "UNSUPPORTED");
       return 0;
    }
    res = ast_channel_sendurl(chan, args.url);
    if (res == -1) {
       pbx_builtin_setvar_helper(chan, "SENDURLSTATUS", "FAILURE");
       return res;
    }
    status = "SUCCESS";
    if (ast_test_flag(&flags, OPTION_WAIT)) {
       for(;;) {
          /* Wait for an event */
          res = ast_waitfor(chan, -1);
          if (res < 0)
             break;
          f = ast_read(chan);
          if (!f) {
             res = -1;
             status = "FAILURE";
             break;
          }
          if (f->frametype == AST_FRAME_HTML) {
             switch (f->subclass.integer) {
             case AST_HTML_LDCOMPLETE:
                res = 0;
                ast_frfree(f);
                status = "NOLOAD";
                goto out;
                break;
             case AST_HTML_NOSUPPORT:
                /* Does not support transport */
                status = "UNSUPPORTED";
                res = 0;
                ast_frfree(f);
                goto out;
                break;
             default:
                ast_log(LOG_WARNING, "Don't know what to do with HTML subclass %d\n", f->subclass.integer);
             };
          }
          ast_frfree(f);
       }
    }
 out:
    pbx_builtin_setvar_helper(chan, "SENDURLSTATUS", status);
    return res;
 }
unload_module()
static int unload_module (void) static
Definition at line 170 of file app_url.c.
References app, and ast_unregister_application().
 {
    return ast_unregister_application(app);
 }
Variable Documentation
app
char* app = "SendURL" static
Definition at line 85 of file app_url.c.
Referenced by load_module(), and unload_module().
app_opts
const struct ast_app_option app_opts[128] = { [ 'w' ] = { .flag = OPTION_WAIT }, } static
Definition at line 93 of file app_url.c.
Referenced by sendurl_exec().