Asterisk - The Open Source Telephony Project: codec_resample.c File Reference
codec_resample.c File Reference
Module: Codecs
Resample slinear audio.
#include "asterisk.h"
#include "speex/speex_resampler.h"
#include "asterisk/module.h"
#include "asterisk/translate.h"
#include "asterisk/slin.h"
Macros
#define OUTBUF_SAMPLES 11520
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int load_module (void)
static void resamp_destroy (struct ast_trans_pvt *pvt)
static int resamp_framein (struct ast_trans_pvt *pvt, struct ast_frame *f)
static int resamp_new (struct ast_trans_pvt *pvt)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "SLIN Resampling Codec" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, }
static const struct ast_module_info * ast_module_info = &__mod_info
static struct ast_codec codec_list []
static int trans_size
static struct ast_translator * translators
Detailed Description
Resample slinear audio.
Definition in file codec_resample.c.
Macro Definition Documentation
OUTBUF_SAMPLES
#define OUTBUF_SAMPLES 11520
Definition at line 39 of file codec_resample.c.
Referenced by load_module(), and resamp_framein().
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 189 of file codec_resample.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 189 of file codec_resample.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 189 of file codec_resample.c.
load_module()
static int load_module (void) static
Definition at line 149 of file codec_resample.c.
References ARRAY_LEN, ast_calloc, AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, ast_register_translator, ast_translator::buf_size, ast_translator::buffer_samples, ast_translator::desc_size, ast_translator::destroy, ast_translator::dst_codec, ast_translator::framein, name, ast_translator::newpvt, OUTBUF_SAMPLES, resamp_destroy(), resamp_framein(), resamp_new(), ast_codec::sample_rate, trans_size, and unload_module().
 {
    int res = 0;
    int x, y, idx = 0;
    trans_size = ARRAY_LEN(codec_list) * (ARRAY_LEN(codec_list) - 1);
    if (!(translators = ast_calloc(1, sizeof(struct ast_translator) * trans_size))) {
       return AST_MODULE_LOAD_DECLINE;
    }
    for (x = 0; x < ARRAY_LEN(codec_list); x++) {
       for (y = 0; y < ARRAY_LEN(codec_list); y++) {
          if (x == y) {
             continue;
          }
          translators[idx].newpvt = resamp_new;
          translators[idx].destroy = resamp_destroy;
          translators[idx].framein = resamp_framein;
          translators[idx].desc_size = 0;
          translators[idx].buffer_samples = OUTBUF_SAMPLES;
          translators[idx].buf_size = (OUTBUF_SAMPLES * sizeof(int16_t));
          memcpy(&translators[idx].src_codec, &codec_list[x], sizeof(struct ast_codec));
          memcpy(&translators[idx].dst_codec, &codec_list[y], sizeof(struct ast_codec));
          snprintf(translators[idx].name, sizeof(translators[idx].name), "slin %ukhz -> %ukhz",
             translators[idx].src_codec.sample_rate, translators[idx].dst_codec.sample_rate);
          res |= ast_register_translator(&translators[idx]);
          idx++;
       }
    }
    /* in case ast_register_translator() failed, we call unload_module() and
    ast_unregister_translator won't fail.*/
    if (res) {
       unload_module();
       return AST_MODULE_LOAD_DECLINE;
    }
    return AST_MODULE_LOAD_SUCCESS;
 }
resamp_destroy()
static void resamp_destroy (struct ast_trans_pvt * pvt) static
Definition at line 105 of file codec_resample.c.
References ast_trans_pvt::pvt, and speex_resampler_destroy().
Referenced by load_module().
 {
    SpeexResamplerState *resamp_pvt = pvt->pvt;
    speex_resampler_destroy(resamp_pvt);
 }
resamp_framein()
static int resamp_framein (struct ast_trans_pvt * pvt, struct ast_frame * f) static
Definition at line 112 of file codec_resample.c.
References ast_frame::data, ast_frame::datalen, ast_trans_pvt::datalen, ast_trans_pvt::i16, ast_trans_pvt::outbuf, OUTBUF_SAMPLES, ast_frame::ptr, ast_trans_pvt::pvt, ast_trans_pvt::samples, and speex_resampler_process_int().
Referenced by load_module().
 {
    SpeexResamplerState *resamp_pvt = pvt->pvt;
    unsigned int out_samples = OUTBUF_SAMPLES - pvt->samples;
    unsigned int in_samples;
    if (!f->datalen) {
       return -1;
    }
    in_samples = f->datalen / 2;
    speex_resampler_process_int(resamp_pvt,
       0,
       f->data.ptr,
       &in_samples,
       pvt->outbuf.i16 + pvt->samples,
       &out_samples);
    pvt->samples += out_samples;
    pvt->datalen += out_samples * 2;
    return 0;
 }
resamp_new()
static int resamp_new (struct ast_trans_pvt * pvt) static
Definition at line 91 of file codec_resample.c.
References ao2_bump, ast_assert, ast_format_cache_get_slin_by_rate(), ast_translator::dst_codec, ast_trans_pvt::f, ast_frame_subclass::format, NULL, ast_trans_pvt::pvt, ast_codec::sample_rate, speex_resampler_init(), ast_translator::src_codec, ast_frame::subclass, and ast_trans_pvt::t.
Referenced by load_module().
 {
    int err;
    if (!(pvt->pvt = speex_resampler_init(1, pvt->t->src_codec.sample_rate, pvt->t->dst_codec.sample_rate, 5, &err))) {
       return -1;
    }
    ast_assert(pvt->f.subclass.format == NULL);
    pvt->f.subclass.format = ao2_bump(ast_format_cache_get_slin_by_rate(pvt->t->dst_codec.sample_rate));
    return 0;
 }
unload_module()
static int unload_module (void) static
Definition at line 136 of file codec_resample.c.
References ast_free, ast_unregister_translator(), and trans_size.
Referenced by load_module().
 {
    int res = 0;
    int idx;
    for (idx = 0; idx < trans_size; idx++) {
       res |= ast_unregister_translator(&translators[idx]);
    }
    ast_free(translators);
    return res;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "SLIN Resampling Codec" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, } static
Definition at line 189 of file codec_resample.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 189 of file codec_resample.c.
codec_list
struct ast_codec codec_list[] static
Definition at line 43 of file codec_resample.c.
Referenced by try_suggested_sip_codec().
trans_size
int trans_size static
Definition at line 42 of file codec_resample.c.
Referenced by load_module(), and unload_module().
translators
struct ast_translator* translators static
Definition at line 41 of file codec_resample.c.