Asterisk - The Open Source Telephony Project: astobj2_private.h File Reference
astobj2_private.h File Reference
Common, private definitions for astobj2.
#include "asterisk/astobj2.h"
Macros
#define __is_ao2_object(user_data, file, line, func)
#define AO2_DEVMODE_STAT(stat)
#define is_ao2_object(user_data) __is_ao2_object(user_data, __FILE__, __LINE__, __PRETTY_FUNCTION__)
Functions
enum ao2_lock_req __adjust_lock (void *user_data, enum ao2_lock_req lock_how, int keep_stronger)
int internal_is_ao2_object (void *user_data)
void log_bad_ao2 (void *user_data, const char *file, int line, const char *func)
Detailed Description
Common, private definitions for astobj2.
Author
Richard Mudgett rmudg.nosp@m.ett@.nosp@m.digiu.nosp@m.m.co.nosp@m.m
Definition in file astobj2_private.h.
Macro Definition Documentation
__is_ao2_object
#define __is_ao2_object (user_data, file, line, func)
Definition at line 49 of file astobj2_private.h.
Referenced by __ao2_container_clone(), __ao2_iterator_next(), __ao2_link(), __ao2_unlink(), hash_ao2_alloc_empty_clone(), internal_ao2_traverse(), and rb_ao2_alloc_empty_clone().
AO2_DEVMODE_STAT
#define AO2_DEVMODE_STAT (stat)
Definition at line 32 of file astobj2_private.h.
Referenced by __ao2_link(), hash_ao2_node_destructor(), rb_delete_fixup(), rb_delete_node(), and rb_insert_fixup().
is_ao2_object
#define is_ao2_object (user_data) __is_ao2_object(user_data, __FILE__, __LINE__, __PRETTY_FUNCTION__)
Definition at line 61 of file astobj2_private.h.
Referenced by ao2_container_check(), ao2_container_dump(), ao2_container_stats(), ao2_iterator_restart(), hash_ao2_node_destructor(), and rb_ao2_node_destructor().
Function Documentation
__adjust_lock()
enum ao2_lock_req __adjust_lock (void * user_data, enum ao2_lock_req lock_how, int keep_stronger)
Definition at line 425 of file astobj2.c.
References __adjust_lock(), AO2_ALLOC_OPT_LOCK_MASK, AO2_ALLOC_OPT_LOCK_MUTEX, AO2_ALLOC_OPT_LOCK_NOLOCK, AO2_ALLOC_OPT_LOCK_OBJ, AO2_ALLOC_OPT_LOCK_RWLOCK, AO2_LOCK_REQ_MUTEX, AO2_LOCK_REQ_RDLOCK, AO2_LOCK_REQ_WRLOCK, ao2_rdlock, ao2_unlock, ao2_wrlock, ast_log, INTERNAL_OBJ, INTERNAL_OBJ_LOCKOBJ, INTERNAL_OBJ_RWLOCK, ao2_lockobj_priv::lock, astobj2_lockobj::lockobj, LOG_ERROR, ao2_rwlock_priv::num_lockers, __priv_data::options, astobj2::priv_data, and astobj2_rwlock::rwlock.
Referenced by __adjust_lock(), __ao2_iterator_next(), __ao2_link(), __ao2_weakproxy_find(), ao2_iterator_restart(), hash_ao2_node_destructor(), internal_ao2_traverse(), and rb_ao2_node_destructor().
 {
    struct astobj2 *obj = INTERNAL_OBJ(user_data);
    struct astobj2_rwlock *obj_rwlock;
    struct astobj2_lockobj *obj_lockobj;
    enum ao2_lock_req orig_lock;
    switch (obj->priv_data.options & AO2_ALLOC_OPT_LOCK_MASK) {
    case AO2_ALLOC_OPT_LOCK_RWLOCK:
       obj_rwlock = INTERNAL_OBJ_RWLOCK(user_data);
       if (obj_rwlock->rwlock.num_lockers < 0) {
          orig_lock = AO2_LOCK_REQ_WRLOCK;
       } else {
          orig_lock = AO2_LOCK_REQ_RDLOCK;
       }
       switch (lock_how) {
       case AO2_LOCK_REQ_MUTEX:
          lock_how = AO2_LOCK_REQ_WRLOCK;
          /* Fall through */
       case AO2_LOCK_REQ_WRLOCK:
          if (lock_how != orig_lock) {
             /* Switch from read lock to write lock. */
             ao2_unlock(user_data);
             ao2_wrlock(user_data);
          }
          break;
       case AO2_LOCK_REQ_RDLOCK:
          if (!keep_stronger && lock_how != orig_lock) {
             /* Switch from write lock to read lock. */
             ao2_unlock(user_data);
             ao2_rdlock(user_data);
          }
          break;
       }
       break;
    case AO2_ALLOC_OPT_LOCK_OBJ:
       obj_lockobj = INTERNAL_OBJ_LOCKOBJ(user_data);
       orig_lock = __adjust_lock(obj_lockobj->lockobj.lock, lock_how, keep_stronger);
       break;
    default:
       ast_log(LOG_ERROR, "Invalid lock option on ao2 object %p\n", user_data);
       /* Fall through */
    case AO2_ALLOC_OPT_LOCK_NOLOCK:
    case AO2_ALLOC_OPT_LOCK_MUTEX:
       orig_lock = AO2_LOCK_REQ_MUTEX;
       break;
    }
    return orig_lock;
 }
internal_is_ao2_object()
int internal_is_ao2_object (void * user_data)
Definition at line 193 of file astobj2.c.
References INTERNAL_OBJ, and IS_AO2_MAGIC_BAD.
 {
    struct astobj2 *p;
    if (!user_data) {
       return 0;
    }
    p = INTERNAL_OBJ(user_data);
    return !p || IS_AO2_MAGIC_BAD(p) ? 0 : 1;
 }
log_bad_ao2()
void log_bad_ao2 (void * user_data, const char * file, int line, const char * func)
Definition at line 206 of file astobj2.c.
References __ast_assert_failed(), INTERNAL_OBJ, __priv_data::magic, and astobj2::priv_data.
 {
    struct astobj2 *p;
    char bad_magic[100];
    if (!user_data) {
       __ast_assert_failed(0, "user_data is NULL", file, line, func);
       return;
    }
    p = INTERNAL_OBJ(user_data);
    snprintf(bad_magic, sizeof(bad_magic), "bad magic number 0x%x for object %p",
       p->priv_data.magic, user_data);
    __ast_assert_failed(0, bad_magic, file, line, func);
 }