Asterisk - The Open Source Telephony Project: test_ari.c File Reference
test_ari.c File Reference
Test ARI API.
Author
David M. Lee, II <dlee@digium.com>
.
#include "asterisk.h"
#include "asterisk/module.h"
#include "asterisk/test.h"
#include "asterisk/ari.h"
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
AST_TEST_DEFINE (get_docs)
AST_TEST_DEFINE (get_docs_nohost)
AST_TEST_DEFINE (get_docs_notfound)
AST_TEST_DEFINE (get_docs_hackerz)
AST_TEST_DEFINE (invoke_get)
AST_TEST_DEFINE (invoke_wildcard)
AST_TEST_DEFINE (invoke_delete)
AST_TEST_DEFINE (invoke_post)
AST_TEST_DEFINE (invoke_bad_post)
AST_TEST_DEFINE (invoke_not_found)
static int load_module (void)
static struct ast_ari_response * response_alloc (void)
static void response_free (struct ast_ari_response *resp)
static void * setup_invocation_test (void)
static void tear_down_invocation_test (void *ignore)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_DEFAULT , .description = "ARI testing" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .requires = "res_ari", }
static const struct ast_module_info * ast_module_info = &__mod_info
#define HANDLER(name, response_code)
static int invocation_count
static struct stasis_rest_handlers bang
static struct stasis_rest_handlers bar
static struct stasis_rest_handlers bam
static struct stasis_rest_handlers test_root
static void handler (const char *name, int response_code, struct ast_variable *get_params, struct ast_variable *path_vars, struct ast_variable *headers, struct ast_json *body, struct ast_ari_response *response)
Detailed Description
Test ARI API.
Author
David M. Lee, II <dlee@digium.com>
.
Definition in file test_ari.c.
Macro Definition Documentation
HANDLER
#define HANDLER (name, response_code)
Definition at line 97 of file test_ari.c.
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 578 of file test_ari.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 578 of file test_ari.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 578 of file test_ari.c.
AST_TEST_DEFINE() [1/10]
AST_TEST_DEFINE (get_docs)
Definition at line 201 of file test_ari.c.
References ast_ari_get_docs(), ast_json_object_get(), ast_json_string_get(), AST_TEST_NOT_RUN, AST_TEST_PASS, ast_variable_new, ast_variables_destroy(), ast_ari_response::headers, sip_to_pjsip::info(), NULL, RAII_VAR, response_alloc(), response_free(), TEST_EXECUTE, and TEST_INIT.
 {
    RAII_VAR(struct ast_ari_response *, response, NULL, response_free);
    RAII_VAR(struct ast_variable *, headers, NULL, ast_variables_destroy);
    struct ast_json *basePathJson;
    const char *basePath;
    switch (cmd) {
    case TEST_INIT:
       info->name = __func__;
       info->category = "/res/ari/";
       info->summary = "Test simple API get.";
       info->description = "Test ARI binding logic.";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    response = response_alloc();
    headers = ast_variable_new("Host", "stasis.asterisk.org", __FILE__);
    ast_ari_get_docs("resources.json", "", headers, response);
    ast_test_validate(test, 200 == response->response_code);
    /* basePath should be relative to the Host header */
    basePathJson = ast_json_object_get(response->message, "basePath");
    ast_test_validate(test, NULL != basePathJson);
    basePath = ast_json_string_get(basePathJson);
    ast_test_validate(test, 0 == strcmp("http://stasis.asterisk.org/ari", basePath));
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [2/10]
AST_TEST_DEFINE (get_docs_nohost)
Definition at line 233 of file test_ari.c.
References ast_ari_get_docs(), ast_json_object_get(), AST_TEST_NOT_RUN, AST_TEST_PASS, sip_to_pjsip::info(), NULL, RAII_VAR, response_alloc(), response_free(), TEST_EXECUTE, and TEST_INIT.
 {
    RAII_VAR(struct ast_ari_response *, response, NULL, response_free);
    struct ast_variable *headers = NULL;
    struct ast_json *basePathJson;
    switch (cmd) {
    case TEST_INIT:
       info->name = __func__;
       info->category = "/res/ari/";
       info->summary = "Test API get without a Host header";
       info->description = "Test ARI binding logic.";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    response = response_alloc();
    ast_ari_get_docs("resources.json",  "", headers, response);
    ast_test_validate(test, 200 == response->response_code);
    /* basePath should be relative to the Host header */
    basePathJson = ast_json_object_get(response->message, "basePath");
    ast_test_validate(test, NULL == basePathJson);
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [3/10]
AST_TEST_DEFINE (get_docs_notfound)
Definition at line 261 of file test_ari.c.
References ast_ari_get_docs(), AST_TEST_NOT_RUN, AST_TEST_PASS, sip_to_pjsip::info(), NULL, RAII_VAR, response_alloc(), response_free(), TEST_EXECUTE, and TEST_INIT.
 {
    RAII_VAR(struct ast_ari_response *, response, NULL, response_free);
    struct ast_variable *headers = NULL;
    switch (cmd) {
    case TEST_INIT:
       info->name = __func__;
       info->category = "/res/ari/";
       info->summary = "Test API get for invalid resource";
       info->description = "Test ARI binding logic.";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    response = response_alloc();
    ast_ari_get_docs("i-am-not-a-resource.json", "", headers, response);
    ast_test_validate(test, 404 == response->response_code);
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [4/10]
AST_TEST_DEFINE (get_docs_hackerz)
Definition at line 284 of file test_ari.c.
References ast_ari_get_docs(), AST_TEST_NOT_RUN, AST_TEST_PASS, sip_to_pjsip::info(), NULL, RAII_VAR, response_alloc(), response_free(), TEST_EXECUTE, and TEST_INIT.
 {
    RAII_VAR(struct ast_ari_response *, response, NULL, response_free);
    struct ast_variable *headers = NULL;
    switch (cmd) {
    case TEST_INIT:
       info->name = __func__;
       info->category = "/res/ari/";
       info->summary = "Test API get for a file outside the rest-api path";
       info->description = "Test ARI binding logic.";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    response = response_alloc();
    ast_ari_get_docs("../../../../sbin/asterisk", "", headers, response);
    ast_test_validate(test, 404 == response->response_code);
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [5/10]
AST_TEST_DEFINE (invoke_get)
Definition at line 307 of file test_ari.c.
References ast_ari_invoke(), ast_assert, AST_HTTP_GET, ast_json_equal(), ast_json_null(), ast_json_pack(), ast_json_unref(), AST_TEST_NOT_RUN, AST_TEST_PASS, ast_variable_new, sip_to_pjsip::info(), invocation_count, ast_variable::next, NULL, RAII_VAR, response_alloc(), response_free(), setup_invocation_test(), tear_down_invocation_test(), TEST_EXECUTE, and TEST_INIT.
 {
    RAII_VAR(void *, fixture, NULL, tear_down_invocation_test);
    RAII_VAR(struct ast_ari_response *, response, NULL, response_free);
    RAII_VAR(struct ast_json *, expected, NULL, ast_json_unref);
    struct ast_variable *get_params = NULL;
    struct ast_variable *headers = NULL;
    switch (cmd) {
    case TEST_INIT:
       info->name = __func__;
       info->category = "/res/ari/";
       info->summary = "Test simple GET of an HTTP resource.";
       info->description = "Test ARI binding logic.";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    fixture = setup_invocation_test();
    response = response_alloc();
    get_params = ast_variable_new("get1", "get-one", __FILE__);
    ast_assert(get_params != NULL);
    get_params->next = ast_variable_new("get2", "get-two", __FILE__);
    ast_assert(get_params->next != NULL);
    headers = ast_variable_new("head1", "head-one", __FILE__);
    ast_assert(headers != NULL);
    headers->next = ast_variable_new("head2", "head-two", __FILE__);
    ast_assert(headers->next != NULL);
    expected = ast_json_pack("{s: s, s: {s: s, s: s}, s: {s: s, s: s}, s: {}}",
              "name", "foo_get",
              "get_params",
              "get1", "get-one",
              "get2", "get-two",
              "headers",
              "head1", "head-one",
              "head2", "head-two",
              "path_vars");
    ast_ari_invoke(NULL, "foo", AST_HTTP_GET, get_params, headers,
       ast_json_null(), response);
    ast_test_validate(test, 1 == invocation_count);
    ast_test_validate(test, 200 == response->response_code);
    ast_test_validate(test, ast_json_equal(expected, response->message));
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [6/10]
AST_TEST_DEFINE (invoke_wildcard)
Definition at line 358 of file test_ari.c.
References ast_ari_invoke(), AST_HTTP_GET, ast_json_equal(), ast_json_null(), ast_json_pack(), ast_json_unref(), AST_TEST_NOT_RUN, AST_TEST_PASS, sip_to_pjsip::info(), invocation_count, NULL, RAII_VAR, response_alloc(), response_free(), setup_invocation_test(), tear_down_invocation_test(), TEST_EXECUTE, and TEST_INIT.
 {
    RAII_VAR(void *, fixture, NULL, tear_down_invocation_test);
    RAII_VAR(struct ast_ari_response *, response, NULL, response_free);
    RAII_VAR(struct ast_json *, expected, NULL, ast_json_unref);
    struct ast_variable *get_params = NULL;
    struct ast_variable *headers = NULL;
    switch (cmd) {
    case TEST_INIT:
       info->name = __func__;
       info->category = "/res/ari/";
       info->summary = "Test GET of a wildcard resource.";
       info->description = "Test ARI binding logic.";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    fixture = setup_invocation_test();
    response = response_alloc();
    expected = ast_json_pack("{s: s, s: {}, s: {}, s: {s: s}}",
              "name", "bam_get",
              "get_params",
              "headers",
              "path_vars",
              "bam", "foshizzle");
    ast_ari_invoke(NULL, "foo/foshizzle", AST_HTTP_GET, get_params, headers,
       ast_json_null(), response);
    ast_test_validate(test, 1 == invocation_count);
    ast_test_validate(test, 200 == response->response_code);
    ast_test_validate(test, ast_json_equal(expected, response->message));
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [7/10]
AST_TEST_DEFINE (invoke_delete)
Definition at line 396 of file test_ari.c.
References ast_ari_invoke(), AST_HTTP_DELETE, ast_json_equal(), ast_json_null(), ast_json_pack(), ast_json_unref(), AST_TEST_NOT_RUN, AST_TEST_PASS, sip_to_pjsip::info(), invocation_count, NULL, RAII_VAR, response_alloc(), response_free(), setup_invocation_test(), tear_down_invocation_test(), TEST_EXECUTE, and TEST_INIT.
 {
    RAII_VAR(void *, fixture, NULL, tear_down_invocation_test);
    RAII_VAR(struct ast_ari_response *, response, NULL, response_free);
    RAII_VAR(struct ast_json *, expected, NULL, ast_json_unref);
    struct ast_variable *get_params = NULL;
    struct ast_variable *headers = NULL;
    switch (cmd) {
    case TEST_INIT:
       info->name = __func__;
       info->category = "/res/ari/";
       info->summary = "Test DELETE of an HTTP resource.";
       info->description = "Test ARI binding logic.";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    fixture = setup_invocation_test();
    response = response_alloc();
    expected = ast_json_pack("{s: s, s: {}, s: {}, s: {s: s}}",
              "name", "bang_delete",
              "get_params",
              "headers",
              "path_vars",
              "bam", "foshizzle");
    ast_ari_invoke(NULL, "foo/foshizzle/bang", AST_HTTP_DELETE, get_params, headers,
       ast_json_null(), response);
    ast_test_validate(test, 1 == invocation_count);
    ast_test_validate(test, 204 == response->response_code);
    ast_test_validate(test, ast_json_equal(expected, response->message));
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [8/10]
AST_TEST_DEFINE (invoke_post)
Definition at line 434 of file test_ari.c.
References ast_ari_invoke(), ast_assert, AST_HTTP_POST, ast_json_equal(), ast_json_null(), ast_json_pack(), ast_json_unref(), AST_TEST_NOT_RUN, AST_TEST_PASS, ast_variable_new, sip_to_pjsip::info(), invocation_count, ast_variable::next, NULL, RAII_VAR, response_alloc(), response_free(), setup_invocation_test(), tear_down_invocation_test(), TEST_EXECUTE, and TEST_INIT.
 {
    RAII_VAR(void *, fixture, NULL, tear_down_invocation_test);
    RAII_VAR(struct ast_ari_response *, response, NULL, response_free);
    RAII_VAR(struct ast_json *, expected, NULL, ast_json_unref);
    struct ast_variable *get_params = NULL;
    struct ast_variable *headers = NULL;
    switch (cmd) {
    case TEST_INIT:
       info->name = __func__;
       info->category = "/res/ari/";
       info->summary = "Test POST of an HTTP resource.";
       info->description = "Test ARI binding logic.";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    fixture = setup_invocation_test();
    response = response_alloc();
    get_params = ast_variable_new("get1", "get-one", __FILE__);
    ast_assert(get_params != NULL);
    get_params->next = ast_variable_new("get2", "get-two", __FILE__);
    ast_assert(get_params->next != NULL);
    headers = ast_variable_new("head1", "head-one", __FILE__);
    ast_assert(headers != NULL);
    headers->next = ast_variable_new("head2", "head-two", __FILE__);
    ast_assert(headers->next != NULL);
    expected = ast_json_pack("{s: s, s: {s: s, s: s}, s: {s: s, s: s}, s: {}}",
              "name", "bar_post",
              "get_params",
              "get1", "get-one",
              "get2", "get-two",
              "headers",
              "head1", "head-one",
              "head2", "head-two",
              "path_vars");
    ast_ari_invoke(NULL, "foo/bar", AST_HTTP_POST, get_params, headers,
       ast_json_null(), response);
    ast_test_validate(test, 1 == invocation_count);
    ast_test_validate(test, 200 == response->response_code);
    ast_test_validate(test, ast_json_equal(expected, response->message));
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [9/10]
AST_TEST_DEFINE (invoke_bad_post)
Definition at line 485 of file test_ari.c.
References ast_ari_invoke(), AST_HTTP_POST, ast_json_null(), AST_TEST_NOT_RUN, AST_TEST_PASS, sip_to_pjsip::info(), invocation_count, NULL, RAII_VAR, response_alloc(), response_free(), setup_invocation_test(), tear_down_invocation_test(), TEST_EXECUTE, and TEST_INIT.
 {
    RAII_VAR(void *, fixture, NULL, tear_down_invocation_test);
    RAII_VAR(struct ast_ari_response *, response, NULL, response_free);
    struct ast_variable *get_params = NULL;
    struct ast_variable *headers = NULL;
    switch (cmd) {
    case TEST_INIT:
       info->name = __func__;
       info->category = "/res/ari/";
       info->summary = "Test POST on a resource that doesn't support it.";
       info->description = "Test ARI binding logic.";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    fixture = setup_invocation_test();
    response = response_alloc();
    ast_ari_invoke(NULL, "foo", AST_HTTP_POST, get_params, headers,
       ast_json_null(), response);
    ast_test_validate(test, 0 == invocation_count);
    ast_test_validate(test, 405 == response->response_code);
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [10/10]
AST_TEST_DEFINE (invoke_not_found)
Definition at line 514 of file test_ari.c.
References ast_ari_invoke(), AST_HTTP_GET, ast_json_null(), AST_TEST_NOT_RUN, AST_TEST_PASS, sip_to_pjsip::info(), invocation_count, NULL, RAII_VAR, response_alloc(), response_free(), setup_invocation_test(), tear_down_invocation_test(), TEST_EXECUTE, and TEST_INIT.
 {
    RAII_VAR(void *, fixture, NULL, tear_down_invocation_test);
    RAII_VAR(struct ast_ari_response *, response, NULL, response_free);
    struct ast_variable *get_params = NULL;
    struct ast_variable *headers = NULL;
    switch (cmd) {
    case TEST_INIT:
       info->name = __func__;
       info->category = "/res/ari/";
       info->summary = "Test GET on a resource that does not exist.";
       info->description = "Test ARI binding logic.";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    fixture = setup_invocation_test();
    response = response_alloc();
    ast_ari_invoke(NULL, "foo/fizzle/i-am-not-a-resource", AST_HTTP_GET, get_params, headers,
       ast_json_null(), response);
    ast_test_validate(test, 0 == invocation_count);
    ast_test_validate(test, 404 == response->response_code);
    return AST_TEST_PASS;
 }
handler()
static void handler (const char * name, int response_code, struct ast_variable * get_params, struct ast_variable * path_vars, struct ast_variable * headers, struct ast_json * body, struct ast_ari_response * response) static
Definition at line 59 of file test_ari.c.
References ast_json_object_get(), ast_json_object_set(), ast_json_pack(), ast_json_string_create(), invocation_count, ast_ari_response::message, ast_variable::name, ast_variable::next, NULL, ast_ari_response::response_code, and ast_variable::value.
Referenced by __aco_option_register(), add_sdp_streams(), allocate_subscription(), app_handle_subscriptions(), ast_ari_add_handler(), ast_ari_invoke(), ast_ari_remove_handler(), ast_msg_has_destination(), ast_mwi_state_callback_all(), ast_mwi_state_callback_subscribed(), channel_hangup_handler_cb(), event_session_alloc(), handle_conf_user_join(), handle_conf_user_leave(), handle_incoming_sdp(), handle_negotiated_sdp_session_media(), handle_stasis_state(), msg_q_cb(), publish_request_initial(), pubsub_on_rx_publish_request(), pubsub_on_rx_subscribe_request(), remove_handler(), root_handler_create(), sdp_requires_deferral(), session_media_set_handler(), session_outgoing_nat_hook(), sip_outbound_publish_synchronize(), stream_destroy(), sub_persistence_recreate(), subscription_get_handler_from_rdata(), and xmpp_action_hook().
 {
    struct ast_json *message = ast_json_pack("{s: s, s: {}, s: {}, s: {}}",
                    "name", name,
                    "get_params",
                    "path_vars",
                    "headers");
    struct ast_json *get_params_obj = ast_json_object_get(message, "get_params");
    struct ast_json *path_vars_obj = ast_json_object_get(message, "path_vars");
    struct ast_json *headers_obj = ast_json_object_get(message, "headers");
    for (; get_params != NULL; get_params = get_params->next) {
       ast_json_object_set(get_params_obj, get_params->name, ast_json_string_create(get_params->value));
    }
    for (; path_vars != NULL; path_vars = path_vars->next) {
       ast_json_object_set(path_vars_obj, path_vars->name, ast_json_string_create(path_vars->value));
    }
    for (; headers != NULL; headers = headers->next) {
       ast_json_object_set(headers_obj, headers->name, ast_json_string_create(headers->value));
    }
    ++invocation_count;
    response->response_code = response_code;
    response->message = message;
 }
load_module()
static int load_module (void) static
Definition at line 558 of file test_ari.c.
References AST_MODFLAG_DEFAULT, AST_MODULE_INFO(), AST_MODULE_LOAD_SUCCESS, AST_MODULE_SUPPORT_CORE, AST_TEST_REGISTER, ASTERISK_GPL_KEY, and unload_module().
 {
    AST_TEST_REGISTER(get_docs);
    AST_TEST_REGISTER(get_docs_nohost);
    AST_TEST_REGISTER(get_docs_notfound);
    AST_TEST_REGISTER(get_docs_hackerz);
    AST_TEST_REGISTER(invoke_get);
    AST_TEST_REGISTER(invoke_wildcard);
    AST_TEST_REGISTER(invoke_delete);
    AST_TEST_REGISTER(invoke_post);
    AST_TEST_REGISTER(invoke_bad_post);
    AST_TEST_REGISTER(invoke_not_found);
    return AST_MODULE_LOAD_SUCCESS;
 }
response_alloc()
static struct ast_ari_response* response_alloc (void) static
Definition at line 156 of file test_ari.c.
References ast_calloc, ast_str_create, and ast_ari_response::headers.
Referenced by AST_TEST_DEFINE().
 {
    struct ast_ari_response *resp = ast_calloc(1, sizeof(struct ast_ari_response));
    resp->headers = ast_str_create(24);
    return resp;
 }
response_free()
static void response_free (struct ast_ari_response * resp) static
Definition at line 167 of file test_ari.c.
References ast_free, ast_json_unref(), ast_ari_response::headers, and ast_ari_response::message.
Referenced by AST_TEST_DEFINE().
 {
    if (!resp) {
       return;
    }
    ast_free(resp->headers);
    ast_json_unref(resp->message);
    ast_free(resp);
 }
setup_invocation_test()
static void* setup_invocation_test (void) static
\ internal Setup test fixture for invocation tests.
Definition at line 181 of file test_ari.c.
References ast_ari_add_handler(), ast_assert, and invocation_count.
Referenced by AST_TEST_DEFINE().
{
    int r;
    invocation_count = 0;
    r = ast_ari_add_handler(&test_root);
    ast_assert(r == 0);
    return &invocation_count;
 }
tear_down_invocation_test()
static void tear_down_invocation_test (void * ignore) static
\ internal Tear down test fixture for invocation tests.
Definition at line 193 of file test_ari.c.
References ast_ari_remove_handler().
Referenced by AST_TEST_DEFINE().
{
    if (!ignore) {
       return;
    }
    ast_ari_remove_handler(&test_root);
 }
unload_module()
static int unload_module (void) static
Definition at line 543 of file test_ari.c.
References AST_TEST_UNREGISTER.
Referenced by load_module().
 {
    AST_TEST_UNREGISTER(get_docs);
    AST_TEST_UNREGISTER(get_docs_nohost);
    AST_TEST_UNREGISTER(get_docs_notfound);
    AST_TEST_UNREGISTER(get_docs_hackerz);
    AST_TEST_UNREGISTER(invoke_get);
    AST_TEST_UNREGISTER(invoke_wildcard);
    AST_TEST_UNREGISTER(invoke_delete);
    AST_TEST_UNREGISTER(invoke_post);
    AST_TEST_UNREGISTER(invoke_bad_post);
    AST_TEST_UNREGISTER(invoke_not_found);
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_DEFAULT , .description = "ARI testing" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .requires = "res_ari", } static
Definition at line 578 of file test_ari.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 578 of file test_ari.c.
bam
struct stasis_rest_handlers bam static
Definition at line 133 of file test_ari.c.
bang
struct stasis_rest_handlers bang static
Definition at line 116 of file test_ari.c.
bar
struct stasis_rest_handlers bar static
Definition at line 125 of file test_ari.c.
invocation_count
int invocation_count static
Definition at line 53 of file test_ari.c.
Referenced by AST_TEST_DEFINE(), handler(), and setup_invocation_test().
test_root
struct stasis_rest_handlers test_root static
Definition at line 142 of file test_ari.c.