Asterisk - The Open Source Telephony Project: curl.c File Reference
curl.c File Reference
#include "asterisk.h"
#include "asterisk/utils.h"
#include "asterisk/logger.h"
#include "curl.h"
#include "general.h"
#include "stir_shaken.h"
#include <curl/curl.h>
#include <sys/stat.h>
Data Structures
struct curl_cb_data
Macros
#define GLOBAL_USERAGENT "asterisk-libcurl-agent/1.0"
#define MAX_HEADER_LENGTH 1023
Functions
static int create_temp_file (const char *path, char **filename)
Create a temporary file located at path.
struct curl_cb_data * curl_cb_data_create (void)
Allocate memory for a curl_cb_data struct.
void curl_cb_data_free (struct curl_cb_data *data)
Free a curl_cb_data struct.
char * curl_cb_data_get_cache_control (const struct curl_cb_data *data)
Get the cache_control field from a curl_cb_data struct.
char * curl_cb_data_get_expires (const struct curl_cb_data *data)
Get the expires field from a curl_cb_data struct.
static size_t curl_header_callback (char *buffer, size_t size, size_t nitems, void *data)
Called when a CURL request completes.
char * curl_public_key (const char *public_cert_url, const char *path, struct curl_cb_data *data)
CURL the public key from the provided URL to the specified path.
static CURL * get_curl_instance (struct curl_cb_data *data)
Prepare a CURL instance to use.
Macro Definition Documentation
GLOBAL_USERAGENT
#define GLOBAL_USERAGENT "asterisk-libcurl-agent/1.0"
Definition at line 34 of file curl.c.
Referenced by get_curl_instance().
MAX_HEADER_LENGTH
#define MAX_HEADER_LENGTH 1023
Definition at line 31 of file curl.c.
Referenced by curl_header_callback().
Function Documentation
create_temp_file()
static int create_temp_file (const char * path, char ** filename) static
Create a temporary file located at path.
Note
This function assumes path does not end with a '/'
Parameters
path The directory path to create the file in
filename Function allocates memory and stores full filename (including path) here
Return values
-1 on failure
file descriptor on success
Definition at line 164 of file curl.c.
References ast_asprintf, ast_free, ast_log, ast_mkdir(), LOG_ERROR, and LOG_NOTICE.
Referenced by curl_public_key().
 {
    const char *template_name = "certXXXXXX";
    int fd;
    if (ast_asprintf(filename, "%s/%s", path, template_name) < 0) {
       ast_log(LOG_ERROR, "Failed to set up temporary file path for CURL\n");
       return -1;
    }
    ast_mkdir(path, 0644);
    if ((fd = mkstemp(*filename)) < 0) {
       ast_log(LOG_NOTICE, "Failed to create temporary file for CURL\n");
       ast_free(*filename);
       return -1;
    }
    return fd;
 }
curl_cb_data_create()
struct curl_cb_data* curl_cb_data_create (void)
Allocate memory for a curl_cb_data struct.
Note
This will need to be freed by the consumer using curl_cb_data_free
Return values
NULL on failure
curl_cb_struct on success
Definition at line 42 of file curl.c.
References ast_calloc.
Referenced by run_curl().
 {
    struct curl_cb_data *data;
    data = ast_calloc(1, sizeof(*data));
    return data;
 }
curl_cb_data_free()
void curl_cb_data_free (struct curl_cb_data * data)
Free a curl_cb_data struct.
Parameters
data The curl_cb_data struct to free
Definition at line 51 of file curl.c.
References ast_free, curl_cb_data::cache_control, and curl_cb_data::expires.
Referenced by run_curl().
 {
    if (!data) {
       return;
    }
    ast_free(data->cache_control);
    ast_free(data->expires);
    ast_free(data);
 }
curl_cb_data_get_cache_control()
char* curl_cb_data_get_cache_control (const struct curl_cb_data * data)
Get the cache_control field from a curl_cb_data struct.
Parameters
data The curl_cb_data
Return values
cache_control on success
NULL otherwise
Definition at line 63 of file curl.c.
References curl_cb_data::cache_control, and NULL.
Referenced by set_public_key_expiration().
 {
    if (!data) {
       return NULL;
    }
    return data->cache_control;
 }
curl_cb_data_get_expires()
char* curl_cb_data_get_expires (const struct curl_cb_data * data)
Get the expires field from a curl_cb_data struct.
Parameters
data The curl_cb_data
Return values
expires on success
NULL otherwise
Definition at line 72 of file curl.c.
References curl_cb_data::expires, and NULL.
Referenced by set_public_key_expiration().
 {
    if (!data) {
       return NULL;
    }
    return data->expires;
 }
curl_header_callback()
static size_t curl_header_callback (char * buffer, size_t size, size_t nitems, void * data) static
Called when a CURL request completes.
Parameters
data The curl_cb_data structure to store expiration info
Definition at line 86 of file curl.c.
References ast_alloca, ast_log, ast_skip_blanks(), ast_strdup, ast_trim_blanks(), curl_cb_data::cache_control, curl_cb_data::expires, LOG_WARNING, MAX_HEADER_LENGTH, and value.
Referenced by get_curl_instance().
 {
    struct curl_cb_data *cb_data = data;
    size_t realsize;
    char *header;
    char *value;
    realsize = size * nitems;
    if (realsize > MAX_HEADER_LENGTH) {
       ast_log(LOG_WARNING, "CURL header length is too large (size: '%zu' | max: '%d')\n",
          realsize, MAX_HEADER_LENGTH);
       return 0;
    }
    header = ast_alloca(realsize + 1);
    memcpy(header, buffer, realsize);
    header[realsize] = '\0';
    value = strchr(header, ':');
    if (!value) {
       return realsize;
    }
    *value++ = '\0';
    value = ast_trim_blanks(ast_skip_blanks(value));
    if (!strcasecmp(header, "Cache-Control")) {
       cb_data->cache_control = ast_strdup(value);
    } else if (!strcasecmp(header, "Expires")) {
       cb_data->expires = ast_strdup(value);
    }
    return realsize;
 }
curl_public_key()
char* curl_public_key (const char * public_cert_url, const char * path, struct curl_cb_data * data)
CURL the public key from the provided URL to the specified path.
Note
The returned string will need to be freed by the caller
Parameters
public_cert_url The public cert URL
path The path to download the file to
data The curl_cb_data
Return values
NULL on failure
full path filename on success
Definition at line 185 of file curl.c.
References ast_asprintf, ast_free, ast_log, create_temp_file(), errno, get_curl_instance(), LOG_ERROR, NULL, RAII_VAR, and stir_shaken_get_serial_number_x509().
Referenced by run_curl().
 {
    FILE *public_key_file;
    RAII_VAR(char *, tmp_filename, NULL, ast_free);
    char *filename;
    char *serial;
    int fd;
    long http_code;
    CURL *curl;
    char curl_errbuf[CURL_ERROR_SIZE + 1];
    curl_errbuf[CURL_ERROR_SIZE] = '\0';
    /* For now, it's fine to pass in path as is - it shouldn't end with a '/'. However,
     * if we decide to change how certificates are stored in the future (configurable paths),
     * then we will need to check to see if path ends with '/', copy everything up to the '/',
     * and use this new variable for create_temp_file as well as for ast_asprintf below.
     */
    fd = create_temp_file(path, &tmp_filename);
    if (fd == -1) {
       ast_log(LOG_ERROR, "Failed to get temporary file descriptor for CURL\n");
       return NULL;
    }
    public_key_file = fdopen(fd, "wb");
    if (!public_key_file) {
       ast_log(LOG_ERROR, "Failed to open file '%s' to write public key from '%s': %s (%d)\n",
          tmp_filename, public_cert_url, strerror(errno), errno);
       close(fd);
       remove(tmp_filename);
       return NULL;
    }
    curl = get_curl_instance(data);
    if (!curl) {
       ast_log(LOG_ERROR, "Failed to set up CURL isntance for '%s'\n", public_cert_url);
       fclose(public_key_file);
       remove(tmp_filename);
       return NULL;
    }
    curl_easy_setopt(curl, CURLOPT_URL, public_cert_url);
    curl_easy_setopt(curl, CURLOPT_WRITEDATA, public_key_file);
    curl_easy_setopt(curl, CURLOPT_ERRORBUFFER, curl_errbuf);
    if (curl_easy_perform(curl)) {
       ast_log(LOG_ERROR, "%s\n", curl_errbuf);
       curl_easy_cleanup(curl);
       fclose(public_key_file);
       remove(tmp_filename);
       return NULL;
    }
    curl_easy_getinfo(curl, CURLINFO_RESPONSE_CODE, &http_code);
    curl_easy_cleanup(curl);
    fclose(public_key_file);
    if (http_code / 100 != 2) {
       ast_log(LOG_ERROR, "Failed to retrieve URL '%s': code %ld\n", public_cert_url, http_code);
       remove(tmp_filename);
       return NULL;
    }
    serial = stir_shaken_get_serial_number_x509(tmp_filename);
    if (!serial) {
       ast_log(LOG_ERROR, "Failed to get serial from cert %s\n", tmp_filename);
       remove(tmp_filename);
       return NULL;
    }
    if (ast_asprintf(&filename, "%s/%s.pem", path, serial) < 0) {
       ast_log(LOG_ERROR, "Failed to allocate memory for new filename for temporary "
          "file %s after CURL\n", tmp_filename);
       ast_free(serial);
       remove(tmp_filename);
       return NULL;
    }
    ast_free(serial);
    if (rename(tmp_filename, filename)) {
       ast_log(LOG_ERROR, "Failed to rename temporary file %s to %s after CURL\n", tmp_filename, filename);
       ast_free(filename);
       remove(tmp_filename);
       return NULL;
    }
    return filename;
 }
get_curl_instance()
static CURL* get_curl_instance (struct curl_cb_data * data) static
Prepare a CURL instance to use.
Parameters
data The CURL callback data
Return values
NULL on failure
CURL instance on success
Definition at line 128 of file curl.c.
References ao2_cleanup, ast_stir_shaken_curl_timeout(), curl_header_callback(), stir_shaken_general::curl_timeout, GLOBAL_USERAGENT, NULL, and stir_shaken_general_get().
Referenced by curl_public_key().
 {
    CURL *curl;
    struct stir_shaken_general *cfg;
    unsigned int curl_timeout;
    cfg = stir_shaken_general_get();
    curl_timeout = ast_stir_shaken_curl_timeout(cfg);
    ao2_cleanup(cfg);
    curl = curl_easy_init();
    if (!curl) {
       return NULL;
    }
    curl_easy_setopt(curl, CURLOPT_NOSIGNAL, 1);
    curl_easy_setopt(curl, CURLOPT_TIMEOUT, curl_timeout);
    curl_easy_setopt(curl, CURLOPT_USERAGENT, GLOBAL_USERAGENT);
    curl_easy_setopt(curl, CURLOPT_FOLLOWLOCATION, 1);
    curl_easy_setopt(curl, CURLOPT_HEADERFUNCTION, curl_header_callback);
    curl_easy_setopt(curl, CURLOPT_HEADERDATA, data);
    return curl;
 }