Asterisk - The Open Source Telephony Project: res_format_attr_h263.c File Reference
res_format_attr_h263.c File Reference
Dial plan applications
H.263 Format Attribute Module.
#include "asterisk.h"
#include <ctype.h>
#include "asterisk/module.h"
#include "asterisk/format.h"
#include "asterisk/strings.h"
#include "asterisk/utils.h"
Data Structures
struct h263_attr
Macros
#define APPEND_IF_NONZERO(field, str, name)
#define APPEND_IF_NOT_H263_UNSET(field, str, name)
#define DETERMINE_JOINT(joint, attr1, attr2, field) (joint->field = (attr1 && attr1->field) ? attr1->field : (attr2 && attr2->field) ? attr2->field : 0)
#define H263_ATTR_KEY_UNSET UINT8_MAX
Value that indicates an attribute is actually unset.
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int h263_clone (const struct ast_format *src, struct ast_format *dst)
static enum ast_format_cmp_res h263_cmp (const struct ast_format *format1, const struct ast_format *format2)
static void h263_destroy (struct ast_format *format)
static void h263_generate_sdp_fmtp (const struct ast_format *format, unsigned int payload, struct ast_str **str)
static struct ast_format * h263_getjoint (const struct ast_format *format1, const struct ast_format *format2)
static struct ast_format * h263_parse_sdp_fmtp (const struct ast_format *format, const char *attributes)
static int load_module (void)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_DEFAULT , .description = "H.263 Format Attribute Module" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, }
static const struct ast_module_info * ast_module_info = &__mod_info
static struct ast_format_interface h263_interface
Detailed Description
H.263 Format Attribute Module.
Author
Joshua Colp <jcolp@digium.com>
This is a format attribute module for the H.263 codec.
Definition in file res_format_attr_h263.c.
Macro Definition Documentation
APPEND_IF_NONZERO
#define APPEND_IF_NONZERO (field, str, name)
Definition at line 277 of file res_format_attr_h263.c.
Referenced by h263_generate_sdp_fmtp().
APPEND_IF_NOT_H263_UNSET
#define APPEND_IF_NOT_H263_UNSET (field, str, name)
Definition at line 266 of file res_format_attr_h263.c.
Referenced by h263_generate_sdp_fmtp().
DETERMINE_JOINT
#define DETERMINE_JOINT (joint, attr1, attr2, field) (joint->field = (attr1 && attr1->field) ? attr1->field : (attr2 && attr2->field) ? attr2->field : 0)
Definition at line 117 of file res_format_attr_h263.c.
Referenced by h263_getjoint().
H263_ATTR_KEY_UNSET
#define H263_ATTR_KEY_UNSET UINT8_MAX
Value that indicates an attribute is actually unset.
Definition at line 44 of file res_format_attr_h263.c.
Referenced by h263_generate_sdp_fmtp(), and h263_parse_sdp_fmtp().
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 399 of file res_format_attr_h263.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 399 of file res_format_attr_h263.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 399 of file res_format_attr_h263.c.
h263_clone()
static int h263_clone (const struct ast_format * src, struct ast_format * dst) static
Definition at line 88 of file res_format_attr_h263.c.
References ast_calloc, ast_format_get_attribute_data(), and ast_format_set_attribute_data().
 {
    struct h263_attr *original = ast_format_get_attribute_data(src);
    struct h263_attr *attr = ast_calloc(1, sizeof(*attr));
    if (!attr) {
       return -1;
    }
    if (original) {
       *attr = *original;
    }
    ast_format_set_attribute_data(dst, attr);
    return 0;
 }
h263_cmp()
static enum ast_format_cmp_res h263_cmp (const struct ast_format * format1, const struct ast_format * format2) static
Definition at line 106 of file res_format_attr_h263.c.
References AST_FORMAT_CMP_EQUAL, AST_FORMAT_CMP_NOT_EQUAL, and ast_format_get_attribute_data().
 {
    struct h263_attr *attr1 = ast_format_get_attribute_data(format1);
    struct h263_attr *attr2 = ast_format_get_attribute_data(format2);
    if (!attr1 || !attr2 || (attr1 && attr2 && !memcmp(attr1, attr2, sizeof(*attr1)))) {
       return AST_FORMAT_CMP_EQUAL;
    }
    return AST_FORMAT_CMP_NOT_EQUAL;
 }
h263_destroy()
static void h263_destroy (struct ast_format * format) static
Definition at line 81 of file res_format_attr_h263.c.
References ast_format_get_attribute_data(), and ast_free.
 {
    struct h263_attr *attr = ast_format_get_attribute_data(format);
    ast_free(attr);
 }
h263_generate_sdp_fmtp()
static void h263_generate_sdp_fmtp (const struct ast_format * format, unsigned int payload, struct ast_str ** str) static
Definition at line 288 of file res_format_attr_h263.c.
References APPEND_IF_NONZERO, APPEND_IF_NOT_H263_UNSET, ast_format_get_attribute_data(), ast_str_append(), h263_attr::BPP, h263_attr::CIF, h263_attr::CIF16, h263_attr::CIF4, h263_attr::CPCF, h263_attr::CPCF_2, h263_attr::CPCF_3, h263_attr::CPCF_4, h263_attr::CPCF_5, h263_attr::CPCF_6, h263_attr::CPCF_7, h263_attr::CPCF_MPI, h263_attr::CUSTOM_MPI, h263_attr::CUSTOM_XMAX, h263_attr::CUSTOM_YMAX, h263_attr::F, H263_ATTR_KEY_UNSET, h263_attr::HRD, h263_attr::I, h263_attr::J, h263_attr::K, h263_attr::MaxBR, h263_attr::N, h263_attr::P_SUB1, h263_attr::P_SUB2, h263_attr::P_SUB3, h263_attr::P_SUB4, h263_attr::PAR_HEIGHT, h263_attr::PAR_WIDTH, h263_attr::QCIF, h263_attr::SQCIF, h263_attr::T, and h263_attr::VGA.
 {
    struct h263_attr *attr = ast_format_get_attribute_data(format);
    int added = 0;
    if (!attr) {
       return;
    }
    if (attr->CPCF) {
       if (added) {
          ast_str_append(str, 0, ";");
       } else if (0 < ast_str_append(str, 0, "a=fmtp:%u ", payload)) {
          added = 1;
       }
       ast_str_append(str, 0, "CPCF=%u,%u,%u,%u,%u,%u,%u,%u", attr->CPCF, attr->CPCF_2, attr->CPCF_3,
          attr->CPCF_4, attr->CPCF_5, attr->CPCF_6, attr->CPCF_7, attr->CPCF_MPI);
    }
    APPEND_IF_NONZERO(attr->CIF16, str, "CIF16");
    APPEND_IF_NONZERO(attr->CIF4,  str, "CIF4");
    APPEND_IF_NONZERO(attr->VGA,   str, "VGA");
    APPEND_IF_NONZERO(attr->CIF,   str, "CIF");
    APPEND_IF_NONZERO(attr->QCIF,  str, "QCIF");
    APPEND_IF_NONZERO(attr->SQCIF, str, "SQCIF");
    if (attr->CUSTOM_XMAX && attr->CUSTOM_YMAX && attr->CUSTOM_MPI) {
       if (added) {
          ast_str_append(str, 0, ";");
       } else if (0 < ast_str_append(str, 0, "a=fmtp:%u ", payload)) {
          added = 1;
       }
       ast_str_append(str, 0, "CUSTOM=%u,%u,%u", attr->CUSTOM_XMAX, attr->CUSTOM_YMAX, attr->CUSTOM_MPI);
    }
    APPEND_IF_NONZERO(attr->F, str, "F");
    APPEND_IF_NONZERO(attr->I, str, "I");
    APPEND_IF_NONZERO(attr->J, str, "J");
    APPEND_IF_NONZERO(attr->T, str, "T");
    APPEND_IF_NONZERO(attr->K, str, "K");
    APPEND_IF_NONZERO(attr->N, str, "N");
    if (attr->P_SUB1) {
       if (added) {
          ast_str_append(str, 0, ";");
       } else if (0 < ast_str_append(str, 0, "a=fmtp:%u ", payload)) {
          added = 1;
       }
       ast_str_append(str, 0, "P=%u", attr->P_SUB1);
       if (attr->P_SUB2) {
          ast_str_append(str, 0, ",%u", attr->P_SUB2);
       }
       if (attr->P_SUB3) {
          ast_str_append(str, 0, ",%u", attr->P_SUB3);
       }
       if (attr->P_SUB4) {
          ast_str_append(str, 0, ",%u", attr->P_SUB4);
       }
    }
    if (attr->PAR_WIDTH != H263_ATTR_KEY_UNSET && attr->PAR_HEIGHT != H263_ATTR_KEY_UNSET) {
       if (added) {
          ast_str_append(str, 0, ";");
       } else if (0 < ast_str_append(str, 0, "a=fmtp:%u ", payload)) {
          added = 1;  \
       }
       ast_str_append(str, 0, "PAR=%u:%u", attr->PAR_WIDTH, attr->PAR_HEIGHT);
    }
    APPEND_IF_NOT_H263_UNSET(attr->BPP, str, "BPP");
    APPEND_IF_NONZERO(attr->HRD, str, "HRD");
    APPEND_IF_NOT_H263_UNSET(attr->MaxBR, str, "MaxBR");
    ast_str_append(str, 0, "\r\n");
    return;
 }
h263_getjoint()
static struct ast_format* h263_getjoint (const struct ast_format * format1, const struct ast_format * format2) static
Definition at line 119 of file res_format_attr_h263.c.
References ast_format_clone(), ast_format_get_attribute_data(), h263_attr::BPP, h263_attr::CIF, h263_attr::CIF16, h263_attr::CIF4, h263_attr::CPCF, h263_attr::CPCF_2, h263_attr::CPCF_3, h263_attr::CPCF_4, h263_attr::CPCF_5, h263_attr::CPCF_6, h263_attr::CPCF_7, h263_attr::CPCF_MPI, h263_attr::CUSTOM_MPI, h263_attr::CUSTOM_XMAX, h263_attr::CUSTOM_YMAX, DETERMINE_JOINT, h263_attr::F, h263_attr::HRD, h263_attr::I, h263_attr::J, h263_attr::K, h263_attr::MaxBR, h263_attr::N, NULL, h263_attr::P_SUB1, h263_attr::P_SUB2, h263_attr::P_SUB3, h263_attr::P_SUB4, h263_attr::PAR_HEIGHT, h263_attr::PAR_WIDTH, h263_attr::QCIF, h263_attr::SQCIF, h263_attr::T, and h263_attr::VGA.
 {
    struct ast_format *cloned;
    struct h263_attr *attr, *attr1, *attr2;
    cloned = ast_format_clone(format1);
    if (!cloned) {
       return NULL;
    }
    attr = ast_format_get_attribute_data(cloned);
    attr1 = ast_format_get_attribute_data(format1);
    attr2 = ast_format_get_attribute_data(format2);
    DETERMINE_JOINT(attr, attr1, attr2, SQCIF);
    DETERMINE_JOINT(attr, attr1, attr2, QCIF);
    DETERMINE_JOINT(attr, attr1, attr2, CIF);
    DETERMINE_JOINT(attr, attr1, attr2, CIF4);
    DETERMINE_JOINT(attr, attr1, attr2, CIF16);
    DETERMINE_JOINT(attr, attr1, attr2, VGA);
    DETERMINE_JOINT(attr, attr1, attr2, CUSTOM_XMAX);
    DETERMINE_JOINT(attr, attr1, attr2, CUSTOM_YMAX);
    DETERMINE_JOINT(attr, attr1, attr2, CUSTOM_MPI);
    DETERMINE_JOINT(attr, attr1, attr2, CPCF);
    DETERMINE_JOINT(attr, attr1, attr2, CPCF_2);
    DETERMINE_JOINT(attr, attr1, attr2, CPCF_3);
    DETERMINE_JOINT(attr, attr1, attr2, CPCF_4);
    DETERMINE_JOINT(attr, attr1, attr2, CPCF_5);
    DETERMINE_JOINT(attr, attr1, attr2, CPCF_6);
    DETERMINE_JOINT(attr, attr1, attr2, CPCF_7);
    DETERMINE_JOINT(attr, attr1, attr2, CPCF_MPI);
    DETERMINE_JOINT(attr, attr1, attr2, F);
    DETERMINE_JOINT(attr, attr1, attr2, I);
    DETERMINE_JOINT(attr, attr1, attr2, J);
    DETERMINE_JOINT(attr, attr1, attr2, T);
    DETERMINE_JOINT(attr, attr1, attr2, K);
    DETERMINE_JOINT(attr, attr1, attr2, N);
    DETERMINE_JOINT(attr, attr1, attr2, P_SUB1);
    DETERMINE_JOINT(attr, attr1, attr2, P_SUB2);
    DETERMINE_JOINT(attr, attr1, attr2, P_SUB3);
    DETERMINE_JOINT(attr, attr1, attr2, P_SUB4);
    DETERMINE_JOINT(attr, attr1, attr2, PAR_WIDTH);
    DETERMINE_JOINT(attr, attr1, attr2, PAR_HEIGHT);
    DETERMINE_JOINT(attr, attr1, attr2, BPP);
    DETERMINE_JOINT(attr, attr1, attr2, HRD);
    DETERMINE_JOINT(attr, attr1, attr2, MaxBR);
    return cloned;
 }
h263_parse_sdp_fmtp()
static struct ast_format* h263_parse_sdp_fmtp (const struct ast_format * format, const char * attributes) static
Definition at line 169 of file res_format_attr_h263.c.
References ast_format_clone(), ast_format_get_attribute_data(), ast_strdupa, ast_strip(), h263_attr::BPP, h263_attr::CIF, h263_attr::CIF16, h263_attr::CIF4, h263_attr::CPCF, h263_attr::CPCF_2, h263_attr::CPCF_3, h263_attr::CPCF_4, h263_attr::CPCF_5, h263_attr::CPCF_6, h263_attr::CPCF_7, h263_attr::CPCF_MPI, h263_attr::CUSTOM_MPI, h263_attr::CUSTOM_XMAX, h263_attr::CUSTOM_YMAX, h263_attr::F, H263_ATTR_KEY_UNSET, h263_attr::HRD, h263_attr::I, h263_attr::J, h263_attr::K, h263_attr::MaxBR, h263_attr::N, NULL, h263_attr::P_SUB1, h263_attr::P_SUB2, h263_attr::P_SUB3, h263_attr::P_SUB4, h263_attr::PAR_HEIGHT, h263_attr::PAR_WIDTH, h263_attr::QCIF, h263_attr::SQCIF, strsep(), h263_attr::T, and h263_attr::VGA.
 {
    char *attribs = ast_strdupa(attributes), *attrib;
    struct ast_format *cloned;
    struct h263_attr *attr;
    cloned = ast_format_clone(format);
    if (!cloned) {
       return NULL;
    }
    attr = ast_format_get_attribute_data(cloned);
    /* upper-case everything, so we are case-insensitive */
    for (attrib = attribs; *attrib; ++attrib) {
       *attrib = toupper(*attrib);
    } /* based on channels/chan_sip.c:process_a_sdp_image() */
    attr->BPP = H263_ATTR_KEY_UNSET;
    attr->MaxBR = H263_ATTR_KEY_UNSET;
    attr->PAR_WIDTH = H263_ATTR_KEY_UNSET;
    attr->PAR_HEIGHT = H263_ATTR_KEY_UNSET;
    while ((attrib = strsep(&attribs, ";"))) {
       unsigned int val, val2 = 0, val3 = 0, val4 = 0, val5 = 0, val6 = 0, val7 = 0, val8 = 0;
       attrib = ast_strip(attrib);
       if (sscanf(attrib, "SQCIF=%30u", &val) == 1) {
          attr->SQCIF = val;
       } else if (strcmp(attrib, "SQCIF") == 0) {
          attr->SQCIF = 1;
       } else if (sscanf(attrib, "QCIF=%30u", &val) == 1) {
          attr->QCIF = val;
       } else if (strcmp(attrib, "QCIF") == 0) {
          attr->QCIF = 1;
       } else if (sscanf(attrib, "CIF=%30u", &val) == 1) {
          attr->CIF = val;
       } else if (strcmp(attrib, "CIF") == 0) {
          attr->CIF = 1;
       } else if (sscanf(attrib, "CIF4=%30u", &val) == 1) {
          attr->CIF4 = val;
       } else if (strcmp(attrib, "CIF4") == 0) {
          attr->CIF4 = 1;
       } else if (sscanf(attrib, "CIF16=%30u", &val) == 1) {
          attr->CIF16 = val;
       } else if (strcmp(attrib, "CIF16") == 0) {
          attr->CIF16 = 1;
       } else if (sscanf(attrib, "VGA=%30u", &val) == 1) {
          attr->VGA = val;
       } else if (strcmp(attrib, "VGA") == 0) {
          attr->VGA = 1;
       } else if (sscanf(attrib, "CUSTOM=%30u,%30u,%30u", &val, &val2, &val3) == 3) {
          attr->CUSTOM_XMAX = val;
          attr->CUSTOM_YMAX = val2;
          attr->CUSTOM_MPI = val3;
       } else if (sscanf(attrib, "CPCF=%30u,%30u,%30u,%30u,%30u,%30u,%30u,%30u",
             &val, &val2, &val3, &val4, &val5, &val6, &val7, &val8) == 8) {
          attr->CPCF = val;
          attr->CPCF_2 = val2;
          attr->CPCF_3 = val3;
          attr->CPCF_4 = val4;
          attr->CPCF_5 = val5;
          attr->CPCF_6 = val6;
          attr->CPCF_7 = val7;
          attr->CPCF_MPI = val8;
       } else if (sscanf(attrib, "F=%30u", &val) == 1) {
          attr->F = val;
       } else if (sscanf(attrib, "I=%30u", &val) == 1) {
          attr->I = val;
       } else if (sscanf(attrib, "J=%30u", &val) == 1) {
          attr->J = val;
       } else if (sscanf(attrib, "T=%30u", &val) == 1) {
          attr->T = val;
       } else if (sscanf(attrib, "K=%30u", &val) == 1) {
          attr->K = val;
       } else if (sscanf(attrib, "N=%30u", &val) == 1) {
          attr->N = val;
       } else if (sscanf(attrib, "PAR=%30u:%30u", &val, &val2) == 2) {
          attr->PAR_WIDTH = val;
          attr->PAR_HEIGHT = val2;
       } else if (sscanf(attrib, "BPP=%30u", &val) == 1) {
          attr->BPP = val;
       } else if (sscanf(attrib, "HRD=%30u", &val) == 1) {
          attr->HRD = val;
       } else if (sscanf(attrib, "P=%30u,%30u,%30u,%30u", &val, &val2, &val3, &val4) > 0) {
          attr->P_SUB1 = val;
          attr->P_SUB2 = val2;
          attr->P_SUB3 = val3;
          attr->P_SUB4 = val4;
       } else if (sscanf(attrib, "MAXBR=%30u", &val) == 1) {
          attr->MaxBR = val;
       }
    }
    return cloned;
 }
load_module()
static int load_module (void) static
Definition at line 382 of file res_format_attr_h263.c.
References ast_format_interface_register, AST_MODFLAG_DEFAULT, AST_MODULE_INFO(), AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, AST_MODULE_SUPPORT_CORE, ASTERISK_GPL_KEY, and unload_module().
 {
    if (ast_format_interface_register("h263", &h263_interface)) {
       return AST_MODULE_LOAD_DECLINE;
    }
    if (ast_format_interface_register("h263p", &h263_interface)) {
       return AST_MODULE_LOAD_DECLINE;
    }
    return AST_MODULE_LOAD_SUCCESS;
 }
unload_module()
static int unload_module (void) static
Definition at line 377 of file res_format_attr_h263.c.
Referenced by load_module().
 {
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_DEFAULT , .description = "H.263 Format Attribute Module" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, } static
Definition at line 399 of file res_format_attr_h263.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 399 of file res_format_attr_h263.c.
h263_interface
struct ast_format_interface h263_interface static
Definition at line 368 of file res_format_attr_h263.c.