Asterisk - The Open Source Telephony Project: format_cap.c File Reference
format_cap.c File Reference
Format Capabilities API.
#include "asterisk.h"
#include "asterisk/logger.h"
#include "asterisk/format.h"
#include "asterisk/format_cap.h"
#include "asterisk/format_cache.h"
#include "asterisk/codec.h"
#include "asterisk/astobj2.h"
#include "asterisk/strings.h"
#include "asterisk/vector.h"
#include "asterisk/linkedlists.h"
#include "asterisk/utils.h"
Data Structures
struct ast_format_cap
Format capabilities structure, holds formats + preference order + etc.
struct format_cap_framed
Structure used for capability formats, adds framing.
struct format_cap_framed_list
Linked list for formats.
Macros
#define FORMAT_CAP_FRAMED_ELEM_CLEANUP(elem) ao2_cleanup((elem))
format_cap_framed vector element cleanup.
#define FORMAT_CAP_FRAMED_ELEM_CMP(elem, value) ((elem)->format == (value))
format_cap_framed comparator for AST_VECTOR_REMOVE_CMP_ORDERED()
Functions
struct ast_format_cap * __ast_format_cap_alloc (enum ast_format_cap_flags flags, const char *tag, const char *file, int line, const char *func)
Allocate a new ast_format_cap structure.
int __ast_format_cap_append (struct ast_format_cap *cap, struct ast_format *format, unsigned int framing, const char *tag, const char *file, int line, const char *func)
Add format capability to capabilities structure.
static const char * __ast_format_cap_get_names (const struct ast_format_cap *cap, struct ast_str **buf, int append)
int ast_format_cap_append_by_type (struct ast_format_cap *cap, enum ast_media_type type)
Add all codecs Asterisk knows about for a specific type to the capabilities structure.
int ast_format_cap_append_from_cap (struct ast_format_cap *dst, const struct ast_format_cap *src, enum ast_media_type type)
Append the formats of provided type in src to dst.
const char * ast_format_cap_append_names (const struct ast_format_cap *cap, struct ast_str **buf)
Append the names of codecs of a set of formats to an ast_str buffer.
size_t ast_format_cap_count (const struct ast_format_cap *cap)
Get the number of formats present within the capabilities structure.
int ast_format_cap_empty (const struct ast_format_cap *cap)
Determine if a format cap has no formats in it.
struct ast_format * ast_format_cap_get_best_by_type (const struct ast_format_cap *cap, enum ast_media_type type)
Get the most preferred format for a particular media type.
int ast_format_cap_get_compatible (const struct ast_format_cap *cap1, const struct ast_format_cap *cap2, struct ast_format_cap *result)
Find the compatible formats between two capabilities structures.
struct ast_format * ast_format_cap_get_compatible_format (const struct ast_format_cap *cap, const struct ast_format *format)
Find if input ast_format is within the capabilities of the ast_format_cap object then return the compatible format from the capabilities structure in the result.
struct ast_format * ast_format_cap_get_format (const struct ast_format_cap *cap, int position)
Get the format at a specific index.
unsigned int ast_format_cap_get_format_framing (const struct ast_format_cap *cap, const struct ast_format *format)
Get the framing for a format.
unsigned int ast_format_cap_get_framing (const struct ast_format_cap *cap)
Get the global framing.
const char * ast_format_cap_get_names (const struct ast_format_cap *cap, struct ast_str **buf)
Get the names of codecs of a set of formats.
int ast_format_cap_has_type (const struct ast_format_cap *cap, enum ast_media_type type)
Find out if the capabilities structure has any formats of a specific type.
int ast_format_cap_identical (const struct ast_format_cap *cap1, const struct ast_format_cap *cap2)
Determine if two capabilities structures are identical.
int ast_format_cap_iscompatible (const struct ast_format_cap *cap1, const struct ast_format_cap *cap2)
Determine if any joint capabilities exist between two capabilities structures.
enum ast_format_cmp_res ast_format_cap_iscompatible_format (const struct ast_format_cap *cap, const struct ast_format *format)
Find if ast_format is within the capabilities of the ast_format_cap object.
int ast_format_cap_remove (struct ast_format_cap *cap, struct ast_format *format)
Remove format capability from capability structure.
void ast_format_cap_remove_by_type (struct ast_format_cap *cap, enum ast_media_type type)
Remove all formats matching a specific format type.
void ast_format_cap_replace_from_cap (struct ast_format_cap *dst, const struct ast_format_cap *src, enum ast_media_type type)
Replace the formats of provided type in dst with equivalent formats from src.
void ast_format_cap_set_framing (struct ast_format_cap *cap, unsigned int framing)
Set the global framing.
int ast_format_cap_update_by_allow_disallow (struct ast_format_cap *cap, const char *list, int allowing)
Parse an "allow" or "deny" list and modify a format capabilities structure accordingly.
static void format_cap_destroy (void *obj)
Destructor for format capabilities structure.
static void format_cap_framed_destroy (void *obj)
Destructor for format capabilities framed structure.
static int format_cap_framed_init (struct format_cap_framed *framed, struct ast_format_cap *cap, struct ast_format *format, unsigned int framing)
static int format_cap_init (struct ast_format_cap *cap, enum ast_format_cap_flags flags)
static int format_cap_replace (struct ast_format_cap *cap, struct ast_format *format, unsigned int framing)
static int format_in_format_cap (struct ast_format_cap *cap, struct ast_format *format)
static int internal_format_cap_identical (const struct ast_format_cap *cap1, const struct ast_format_cap *cap2)
Variables
static const struct format_cap_framed_list format_cap_framed_list_empty = AST_LIST_HEAD_NOLOCK_INIT_VALUE
Dummy empty list for when we are inserting a new list.
Detailed Description
Format Capabilities API.
Author
Joshua Colp jcolp.nosp@m.@dig.nosp@m.ium.c.nosp@m.om
Definition in file format_cap.c.
Macro Definition Documentation
FORMAT_CAP_FRAMED_ELEM_CLEANUP
#define FORMAT_CAP_FRAMED_ELEM_CLEANUP (elem) ao2_cleanup((elem))
format_cap_framed vector element cleanup.
Parameters
elem Element to cleanup
Returns
Nothing
Definition at line 495 of file format_cap.c.
Referenced by ast_format_cap_remove(), and ast_format_cap_remove_by_type().
FORMAT_CAP_FRAMED_ELEM_CMP
#define FORMAT_CAP_FRAMED_ELEM_CMP (elem, value) ((elem)->format == (value))
format_cap_framed comparator for AST_VECTOR_REMOVE_CMP_ORDERED()
Parameters
elem Element to compare against
value Value to compare with the vector element.
Returns
0 if element does not match.
Non-zero if element matches.
Definition at line 486 of file format_cap.c.
Referenced by ast_format_cap_remove(), and ast_format_cap_remove_by_type().
Function Documentation
__ast_format_cap_alloc()
struct ast_format_cap* __ast_format_cap_alloc (enum ast_format_cap_flags flags, const char * tag, const char * file, int line, const char * func)
Allocate a new ast_format_cap structure.
Parameters
flags Modifiers of struct behavior.
Return values
ast_format_cap object on success.
NULL on failure.
Definition at line 117 of file format_cap.c.
References __ao2_alloc(), AO2_ALLOC_OPT_LOCK_NOLOCK, ao2_ref, format_cap_destroy(), format_cap_init(), and NULL.
 {
    struct ast_format_cap *cap;
    cap = __ao2_alloc(sizeof(*cap), format_cap_destroy, AO2_ALLOC_OPT_LOCK_NOLOCK,
       tag, file, line, func);
    if (!cap) {
       return NULL;
    }
    if (format_cap_init(cap, flags)) {
       ao2_ref(cap, -1);
       return NULL;
    }
    return cap;
 }
__ast_format_cap_append()
int __ast_format_cap_append (struct ast_format_cap * cap, struct ast_format * format, unsigned int framing, const char * tag, const char * file, int line, const char * func)
Add format capability to capabilities structure.
Parameters
cap The capabilities structure to add to.
format The format to add.
framing The framing for the format (in milliseconds).
Return values
0 success
-1 failure
Note
A reference to the format is taken and used in the capabilities structure.
The order in which add is called determines the format preference order.
If framing is specified here it overrides any global framing that has been set.
Definition at line 195 of file format_cap.c.
References __ao2_ref(), AO2_ALLOC_OPT_LOCK_NOLOCK, ao2_alloc_options, ast_assert, format_cap_framed::format, format_cap_framed_destroy(), format_cap_framed_init(), format_in_format_cap(), and NULL.
 {
    struct format_cap_framed *framed;
    ast_assert(format != NULL);
    if (format_in_format_cap(cap, format)) {
       return 0;
    }
    framed = ao2_alloc_options(sizeof(*framed), format_cap_framed_destroy, AO2_ALLOC_OPT_LOCK_NOLOCK);
    if (!framed) {
       return -1;
    }
    __ao2_ref(format, +1, tag, file, line, func);
    framed->format = format;
    return format_cap_framed_init(framed, cap, format, framing);
 }
__ast_format_cap_get_names()
static const char* __ast_format_cap_get_names (const struct ast_format_cap * cap, struct ast_str ** buf, int append) static
Definition at line 702 of file format_cap.c.
References ast_format_get_name(), ast_str_append(), ast_str_buffer(), ast_str_set(), AST_VECTOR_GET, AST_VECTOR_SIZE, and format_cap_framed::format.
Referenced by ast_format_cap_append_names(), and ast_format_cap_get_names().
 {
    int i;
    if (!buf || !*buf) {
       return "";
    }
    if (append) {
       ast_str_append(buf, 0, "(");
    } else {
       ast_str_set(buf, 0, "(");
    }
    if (!cap || !AST_VECTOR_SIZE(&cap->preference_order)) {
       ast_str_append(buf, 0, "nothing)");
       return ast_str_buffer(*buf);
    }
    for (i = 0; i < AST_VECTOR_SIZE(&cap->preference_order); ++i) {
       int res;
       struct format_cap_framed *framed = AST_VECTOR_GET(&cap->preference_order, i);
       res = ast_str_append(buf, 0, "%s%s", ast_format_get_name(framed->format),
          i < AST_VECTOR_SIZE(&cap->preference_order) - 1 ? "|" : "");
       if (res < 0) {
          break;
       }
    }
    ast_str_append(buf, 0, ")");
    return ast_str_buffer(*buf);
 }
ast_format_cap_append_by_type()
int ast_format_cap_append_by_type (struct ast_format_cap * cap, enum ast_media_type type)
Add all codecs Asterisk knows about for a specific type to the capabilities structure.
Parameters
cap The capabilities structure to add to.
type The type of formats to add.
Return values
0 success
-1 failure
Note
A generic format with no attributes is created using the codec.
If AST_MEDIA_TYPE_UNKNOWN is passed as the type all known codecs will be added.
Definition at line 216 of file format_cap.c.
References ao2_cleanup, ao2_ref, ast_codec_get_by_id(), ast_codec_get_max(), ast_format_cache_get_by_codec(), ast_format_cap_append, ast_format_create(), ast_format_get_codec(), ast_format_none, AST_MEDIA_TYPE_UNKNOWN, codec2, format_cap_framed::format, id, NULL, and ast_codec::type.
Referenced by ast_ari_channels_create(), ast_format_cap_update_by_allow_disallow(), ast_local_init(), AST_TEST_DEFINE(), begin_dial_prerun(), load_module(), rec_request(), and register_channel_tech().
 {
    int id;
    for (id = 1; id < ast_codec_get_max(); ++id) {
       struct ast_codec *codec = ast_codec_get_by_id(id);
       struct ast_codec *codec2 = NULL;
       struct ast_format *format;
       int res;
       if (!codec) {
          continue;
       }
       if ((type != AST_MEDIA_TYPE_UNKNOWN) && codec->type != type) {
          ao2_ref(codec, -1);
          continue;
       }
       format = ast_format_cache_get_by_codec(codec);
       if (format == ast_format_none) {
          ao2_ref(format, -1);
          ao2_ref(codec, -1);
          continue;
       }
       if (format) {
          codec2 = ast_format_get_codec(format);
       }
       if (codec != codec2) {
          ao2_cleanup(format);
          format = ast_format_create(codec);
       }
       ao2_cleanup(codec2);
       ao2_ref(codec, -1);
       if (!format) {
          return -1;
       }
       /* Use the global framing or default framing of the codec */
       res = ast_format_cap_append(cap, format, 0);
       ao2_ref(format, -1);
       if (res) {
          return -1;
       }
    }
    return 0;
 }
ast_format_cap_append_from_cap()
int ast_format_cap_append_from_cap (struct ast_format_cap * dst, const struct ast_format_cap * src, enum ast_media_type type)
Append the formats of provided type in src to dst.
Parameters
dst The destination capabilities structure
src The source capabilities structure
type The type of formats to append.
Return values
0 success
-1 failure
Note
If AST_MEDIA_TYPE_UNKNOWN is passed as the type all known codecs will be added.
Definition at line 269 of file format_cap.c.
References ast_format_cap_append, ast_format_get_type(), AST_MEDIA_TYPE_UNKNOWN, AST_VECTOR_GET, AST_VECTOR_SIZE, format_cap_framed::format, and format_cap_framed::framing.
Referenced by __sip_alloc(), add_sdp(), ast_media_get_format_cap(), ast_sip_create_joint_call_cap(), ast_stream_clone(), ast_stream_create_resolved(), ast_stream_topology_create_from_format_cap(), ast_stream_topology_get_formats_by_type(), AST_TEST_DEFINE(), build_device(), build_gateway(), build_peer(), build_user(), chan_pjsip_get_codec(), chan_pjsip_new(), chan_pjsip_read_stream(), channel_do_masquerade(), check_peer_ok(), config_device(), config_line(), create_addr_from_peer(), create_outgoing_sdp_stream(), func_channel_read(), handle_request_invite(), jingle_alloc(), jingle_call(), jingle_interpret_content(), jingle_new(), load_module(), media_offer_write_av(), mgcp_get_codec(), mgcp_new(), ooh323_alloc(), ooh323_get_codec(), ooh323_onReceivedSetup(), ooh323_request(), phone_new(), process_sdp(), request_channel(), send_direct_media_request(), set_caps(), set_peer_defaults(), sip_get_codec(), sip_new(), sip_request_call(), sip_rtp_read(), sip_set_rtp_peer(), skinny_new(), try_suggested_sip_codec(), unistim_line_copy(), unistim_new(), and unistim_request().
 {
    int idx, res = 0;
    /* NOTE:  The streams API is dependent on the formats being in "preference" order */
    for (idx = 0; (idx < AST_VECTOR_SIZE(&src->preference_order)) && !res; ++idx) {
       struct format_cap_framed *framed = AST_VECTOR_GET(&src->preference_order, idx);
       if (type == AST_MEDIA_TYPE_UNKNOWN || ast_format_get_type(framed->format) == type) {
          res = ast_format_cap_append(dst, framed->format, framed->framing);
       }
    }
    return res;
 }
ast_format_cap_append_names()
const char* ast_format_cap_append_names (const struct ast_format_cap * cap, struct ast_str ** buf)
Append the names of codecs of a set of formats to an ast_str buffer.
Since
18
Parameters
cap The capabilities structure containing the formats
buf A ast_str buffer to append the names of the formats to
Returns
The contents of the buffer in buf
Definition at line 741 of file format_cap.c.
References __ast_format_cap_get_names().
Referenced by ast_stream_create_resolved(), and ast_stream_to_str().
 {
    return __ast_format_cap_get_names(cap, buf, 1);
 }
ast_format_cap_count()
size_t ast_format_cap_count (const struct ast_format_cap * cap)
Get the number of formats present within the capabilities structure.
Parameters
cap The capabilities structure
Returns
the number of formats
Definition at line 395 of file format_cap.c.
References AST_VECTOR_SIZE.
Referenced by add_format_information_cb(), add_sdp(), apply_cap_to_bundled(), ast_format_cap_empty(), ast_iax2_new(), ast_openvstream(), ast_rtp_instance_available_formats(), ast_rtp_lookup_mime_multiple2(), ast_stream_get_format_count(), ast_stream_topology_create_from_format_cap(), ast_stream_topology_equal(), AST_TEST_DEFINE(), ast_translate_available_formats(), ast_translator_best_choice(), begin_dial_prerun(), check_peer_ok(), check_translation_path(), configure_local_rtp(), create_addr(), create_outgoing_sdp_stream(), derive_format_from_cap(), handle_request_invite(), iax2_codec_pref_string(), iax2_format_compatibility_cap2bitfield(), iax2_parse_allow_disallow(), iax2_request(), jingle_add_payloads_to_description(), jingle_interpret_description(), jingle_new(), media_offer_read_av(), mgcp_new(), native_rtp_bridge_compatible_check(), ooh323_get_codec(), ooh323_write(), ooh323c_set_capability(), ooh323c_set_capability_for_call(), process_sdp(), send_direct_media_request(), set_caps(), show_sound_info_cb(), sip_new(), sip_session_refresh(), sip_set_rtp_peer(), skinny_new(), transmit_connect(), transmit_connect_with_sdp(), transmit_modify_request(), transmit_modify_with_sdp(), and unistim_new().
 {
    return AST_VECTOR_SIZE(&cap->preference_order);
 }
ast_format_cap_empty()
int ast_format_cap_empty (const struct ast_format_cap * cap)
Determine if a format cap has no formats in it.
Parameters
cap The format cap to check for emptiness
Return values
1 The format cap has zero formats or only ast_format_none
0 The format cap has at least one format
Definition at line 746 of file format_cap.c.
References ast_format_cap_count(), ast_format_none, and AST_VECTOR_GET.
Referenced by ast_sip_create_joint_call_cap(), ast_stream_create_resolved(), ast_translator_best_choice(), chan_pjsip_new(), request_channel(), set_format(), set_incoming_call_offer_cap(), sip_call(), and sip_request_call().
 {
    int count = ast_format_cap_count(cap);
    if (count > 1) {
       return 0;
    }
    if (count == 0 || AST_VECTOR_GET(&cap->preference_order, 0)->format == ast_format_none) {
       return 1;
    }
    return 0;
 }
ast_format_cap_get_best_by_type()
struct ast_format* ast_format_cap_get_best_by_type (const struct ast_format_cap * cap, enum ast_media_type type)
Get the most preferred format for a particular media type.
Parameters
cap The capabilities structure
type The type of media to get
Return values
non-NULL the preferred format
NULL no media of type present
Note
The reference count of the returned format is increased. It must be released using ao2_ref or ao2_cleanup.
Definition at line 417 of file format_cap.c.
References ao2_ref, ast_assert, ast_format_cap_get_format(), ast_format_get_type(), ast_format_none, AST_MEDIA_TYPE_UNKNOWN, AST_VECTOR_GET, AST_VECTOR_SIZE, format_cap_framed::format, and NULL.
Referenced by AST_TEST_DEFINE(), chan_pjsip_new(), set_caps(), set_format(), sip_new(), and sip_session_response_cb().
 {
    int i;
    if (type == AST_MEDIA_TYPE_UNKNOWN) {
       return ast_format_cap_get_format(cap, 0);
    }
    for (i = 0; i < AST_VECTOR_SIZE(&cap->preference_order); i++) {
       struct format_cap_framed *framed = AST_VECTOR_GET(&cap->preference_order, i);
       if (ast_format_get_type(framed->format) == type) {
          ao2_ref(framed->format, +1);
          ast_assert(framed->format != ast_format_none);
          return framed->format;
       }
    }
    return NULL;
 }
ast_format_cap_get_compatible()
int ast_format_cap_get_compatible (const struct ast_format_cap * cap1, const struct ast_format_cap * cap2, struct ast_format_cap * result)
Find the compatible formats between two capabilities structures.
Parameters
cap1 The first capabilities structure
cap2 The second capabilities structure
[out] result The capabilities structure to place the results into
Return values
0 success
-1 failure
Note
The preference order of cap1 is respected.
If failure occurs the result format capabilities structure may contain a partial result.
Definition at line 630 of file format_cap.c.
References ao2_ref, ast_format_cap_append, ast_format_cap_get_compatible_format(), AST_VECTOR_GET, AST_VECTOR_SIZE, format_cap_framed::format, and format_cap_framed::framing.
Referenced by add_sdp(), ast_sip_create_joint_call_cap(), ast_speech_new(), ast_stream_create_resolved(), AST_TEST_DEFINE(), ast_translator_best_choice(), check_peer_ok(), create_outgoing_sdp_stream(), handle_capabilities_res_message(), iax2_request(), jingle_interpret_description(), process_sdp(), set_caps(), sip_request_call(), sip_session_refresh(), and skinny_register().
 {
    int idx, res = 0;
    for (idx = 0; idx < AST_VECTOR_SIZE(&cap1->preference_order); ++idx) {
       struct format_cap_framed *framed = AST_VECTOR_GET(&cap1->preference_order, idx);
       struct ast_format *format;
       format = ast_format_cap_get_compatible_format(cap2, framed->format);
       if (!format) {
          continue;
       }
       res = ast_format_cap_append(result, format, framed->framing);
       ao2_ref(format, -1);
       if (res) {
          break;
       }
    }
    return res;
 }
ast_format_cap_get_compatible_format()
struct ast_format* ast_format_cap_get_compatible_format (const struct ast_format_cap * cap, const struct ast_format * format)
Find if input ast_format is within the capabilities of the ast_format_cap object then return the compatible format from the capabilities structure in the result.
Return values
non-NULL if format is compatible
NULL if not compatible
Note
The reference count of the returned format is increased. It must be released using ao2_ref or ao2_cleanup.
Definition at line 548 of file format_cap.c.
References ao2_cleanup, ast_assert, ast_format_cmp(), AST_FORMAT_CMP_EQUAL, AST_FORMAT_CMP_NOT_EQUAL, ast_format_get_codec_id(), ast_format_joint(), AST_LIST_TRAVERSE, AST_VECTOR_GET_ADDR, AST_VECTOR_SIZE, format_cap_framed::format, NULL, and result.
Referenced by ast_format_cap_get_compatible(), AST_TEST_DEFINE(), ast_translate_available_formats(), and codec_choose_from_prefs().
 {
    struct format_cap_framed_list *list;
    struct format_cap_framed *framed;
    struct ast_format *result = NULL;
    ast_assert(format != NULL);
    if (ast_format_get_codec_id(format) >= AST_VECTOR_SIZE(&cap->formats)) {
       return NULL;
    }
    list = AST_VECTOR_GET_ADDR(&cap->formats, ast_format_get_codec_id(format));
    AST_LIST_TRAVERSE(list, framed, entry) {
       enum ast_format_cmp_res res = ast_format_cmp(format, framed->format);
       if (res == AST_FORMAT_CMP_NOT_EQUAL) {
          continue;
       }
       /* Replace any current result, this one will also be a subset OR an exact match */
       ao2_cleanup(result);
       result = ast_format_joint(format, framed->format);
       /* If it's a match we can do no better so return asap */
       if (res == AST_FORMAT_CMP_EQUAL) {
          break;
       }
    }
    return result;
 }
ast_format_cap_get_format()
struct ast_format* ast_format_cap_get_format (const struct ast_format_cap * cap, int position)
Get the format at a specific index.
Parameters
cap The capabilities structure
position The position to get
Return values
non-NULL success
NULL failure
Note
This is a zero based index.
Formats are returned in order of preference.
The reference count of the returned format is increased. It must be released using ao2_ref or ao2_cleanup.
Definition at line 400 of file format_cap.c.
References ao2_ref, ast_assert, ast_format_none, AST_VECTOR_GET, AST_VECTOR_SIZE, format_cap_framed::format, and NULL.
Referenced by add_format_information_cb(), add_sdp(), apply_cap_to_bundled(), ast_format_cap_get_best_by_type(), ast_iax2_new(), ast_openvstream(), ast_rtp_lookup_mime_multiple2(), ast_sip_create_joint_call_cap(), ast_speech_new(), ast_stream_create_resolved(), AST_TEST_DEFINE(), ast_translate_available_formats(), ast_translator_best_choice(), ast_unreal_new_channels(), audiosocket_request(), chan_pjsip_new(), check_translation_path(), configure_local_rtp(), create_addr(), create_outgoing_sdp_stream(), derive_format_from_cap(), function_sippeer(), handle_open_receive_channel_ack_message(), iax2_codec_pref_string(), iax2_format_compatibility_cap2bitfield(), iax2_parse_allow_disallow(), iax2_request(), internal_format_cap_identical(), jingle_add_payloads_to_description(), jingle_interpret_content(), jingle_new(), media_offer_read_av(), mgcp_new(), misdn_new(), mp3_exec(), ooh323_new(), ooh323c_set_capability(), ooh323c_set_capability_for_call(), phone_new(), process_sdp(), set_caps(), show_sound_info_cb(), sip_new(), skinny_new(), skinny_set_rtp_peer(), start_rtp(), transmit_connect(), transmit_connect_with_sdp(), transmit_modify_request(), transmit_modify_with_sdp(), and unistim_new().
 {
    struct format_cap_framed *framed;
    ast_assert(position < AST_VECTOR_SIZE(&cap->preference_order));
    if (position >= AST_VECTOR_SIZE(&cap->preference_order)) {
       return NULL;
    }
    framed = AST_VECTOR_GET(&cap->preference_order, position);
    ast_assert(framed->format != ast_format_none);
    ao2_ref(framed->format, +1);
    return framed->format;
 }
ast_format_cap_get_format_framing()
unsigned int ast_format_cap_get_format_framing (const struct ast_format_cap * cap, const struct ast_format * format)
Get the framing for a format.
Parameters
cap The capabilities structure
format The format to retrieve
Returns
the framing (in milliseconds)
Definition at line 443 of file format_cap.c.
References ast_format_cmp(), AST_FORMAT_CMP_EQUAL, AST_FORMAT_CMP_NOT_EQUAL, ast_format_get_codec_id(), ast_format_get_default_ms(), AST_LIST_TRAVERSE, AST_VECTOR_GET_ADDR, AST_VECTOR_SIZE, format_cap_framed::format, format_cap_framed::framing, NULL, and result.
Referenced by add_codec_to_sdp(), AST_TEST_DEFINE(), create_addr(), handle_open_receive_channel_ack_message(), iax2_parse_allow_disallow(), native_rtp_bridge_compatible_check(), ooh323c_set_capability_for_call(), process_sdp(), sip_new(), skinny_set_rtp_peer(), and transmit_connect().
 {
    unsigned int framing;
    struct format_cap_framed_list *list;
    struct format_cap_framed *framed, *result = NULL;
    if (ast_format_get_codec_id(format) >= AST_VECTOR_SIZE(&cap->formats)) {
       return 0;
    }
    framing = cap->framing != UINT_MAX ? cap->framing : ast_format_get_default_ms(format);
    list = AST_VECTOR_GET_ADDR(&cap->formats, ast_format_get_codec_id(format));
    AST_LIST_TRAVERSE(list, framed, entry) {
       enum ast_format_cmp_res res = ast_format_cmp(format, framed->format);
       if (res == AST_FORMAT_CMP_NOT_EQUAL) {
          continue;
       }
       result = framed;
       if (res == AST_FORMAT_CMP_EQUAL) {
          break;
       }
    }
    if (result && result->framing) {
       framing = result->framing;
    }
    return framing;
 }
ast_format_cap_get_framing()
unsigned int ast_format_cap_get_framing (const struct ast_format_cap * cap)
Get the global framing.
Parameters
cap The capabilities structure.
Return values
0 if no formats are in the structure and no framing has been provided
The global framing value (in milliseconds)
Note
This will be the minimum framing allowed across all formats in the capabilities structure, or an overridden value
Definition at line 438 of file format_cap.c.
Referenced by ast_stream_create_resolved(), ast_stream_topology_create_from_format_cap(), AST_TEST_DEFINE(), check_peer_ok(), configure_local_rtp(), create_addr_from_peer(), create_outgoing_sdp_stream(), jingle_enable_video(), jingle_new(), set_caps(), and start_rtp().
 {
    return (cap->framing != UINT_MAX) ? cap->framing : 0;
 }
ast_format_cap_get_names()
const char* ast_format_cap_get_names (const struct ast_format_cap * cap, struct ast_str ** buf)
Get the names of codecs of a set of formats.
Parameters
cap The capabilities structure containing the formats
buf A ast_str buffer to populate with the names of the formats
Returns
The contents of the buffer in buf
Definition at line 736 of file format_cap.c.
References __ast_format_cap_get_names().
Referenced by _sip_show_peer(), _skinny_show_device(), _skinny_show_line(), add_sdp(), alsa_request(), ast_channel_nativeformats_set(), ast_streamfile(), AST_TEST_DEFINE(), ast_write_stream(), chan_pjsip_get_codec(), chan_pjsip_set_rtp_peer(), chan_pjsip_write_stream(), codec_handler_fn(), compatible_formats_exist(), console_request(), func_channel_read(), function_sippeer(), generate_status(), handle_capabilities_res_message(), handle_cli_core_show_channeltype(), handle_cli_ooh323_show_config(), handle_cli_ooh323_show_peers(), handle_cli_ooh323_show_users(), handle_showchan(), iax2_getformatname_multiple(), iax2_key_rotate(), iax2_request(), jingle_write(), local_request_with_stream_topology(), log_caps(), mbl_request(), mgcp_request(), mgcp_write(), native_rtp_bridge_compatible_check(), nbs_request(), onNewCallCreated(), ooh323_request(), ooh323_set_write_format(), ooh323_write(), oss_request(), phone_request(), process_sdp(), request_channel(), serialize_showchan(), set_caps(), set_format(), show_channels_cb(), sip_new(), sip_request_call(), sip_show_channel(), sip_show_settings(), sip_write(), skinny_new(), skinny_request(), skinny_write(), socket_process_helper(), start_rtp(), test_create_joint(), unistim_new(), unistim_request(), unistim_rtp_read(), unistim_show_info(), and unistim_write().
 {
    return __ast_format_cap_get_names(cap, buf, 0);
 }
ast_format_cap_has_type()
int ast_format_cap_has_type (const struct ast_format_cap * cap, enum ast_media_type type)
Find out if the capabilities structure has any formats of a specific type.
Return values
1 true
0 false, no formats of specific type.
Definition at line 615 of file format_cap.c.
References ast_format_get_type(), AST_VECTOR_GET, AST_VECTOR_SIZE, and format_cap_framed::format.
Referenced by add_sdp(), ast_bridge_update_talker_src_video_mode(), ast_channel_make_compatible_helper(), ast_openstream_full(), ast_openvstream(), ast_sendtext_data(), ast_stream_topology_create_from_format_cap(), AST_TEST_DEFINE(), dialog_initialize_rtp(), jingle_enable_video(), jingle_request(), negotiate_incoming_sdp_stream(), ooh323_request(), process_sdp(), sip_call(), sip_new(), and skinny_request().
 {
    int idx;
    for (idx = 0; idx < AST_VECTOR_SIZE(&cap->preference_order); ++idx) {
       struct format_cap_framed *framed = AST_VECTOR_GET(&cap->preference_order, idx);
       if (ast_format_get_type(framed->format) == type) {
          return 1;
       }
    }
    return 0;
 }
ast_format_cap_identical()
int ast_format_cap_identical (const struct ast_format_cap * cap1, const struct ast_format_cap * cap2)
Determine if two capabilities structures are identical.
Parameters
cap1 The first capabilities structure
cap2 The second capabilities structure
Return values
0 capabilities are not identical
1 capabilities are identical
Definition at line 689 of file format_cap.c.
References AST_VECTOR_SIZE, and internal_format_cap_identical().
Referenced by ast_stream_topology_equal(), AST_TEST_DEFINE(), iax2_key_rotate(), send_direct_media_request(), sip_set_rtp_peer(), and validate_stream().
 {
    if (AST_VECTOR_SIZE(&cap1->preference_order) != AST_VECTOR_SIZE(&cap2->preference_order)) {
       return 0; /* if they are not the same size, they are not identical */
    }
    if (!internal_format_cap_identical(cap1, cap2)) {
       return 0;
    }
    return internal_format_cap_identical(cap2, cap1);
 }
ast_format_cap_iscompatible()
int ast_format_cap_iscompatible (const struct ast_format_cap * cap1, const struct ast_format_cap * cap2)
Determine if any joint capabilities exist between two capabilities structures.
Parameters
cap1 The first capabilities structure
cap2 The second capabilities structure
Return values
0 no joint capabilities exist
1 joint capabilities exist
Definition at line 655 of file format_cap.c.
References ast_format_cap_iscompatible_format(), AST_FORMAT_CMP_NOT_EQUAL, AST_VECTOR_GET, AST_VECTOR_SIZE, and format_cap_framed::format.
Referenced by ast_openvstream(), ast_rtp_instance_early_bridge(), ast_rtp_instance_early_bridge_make_compatible(), AST_TEST_DEFINE(), compatible_formats_exist(), console_request(), mgcp_request(), native_rtp_bridge_compatible_check(), phone_request(), and unistim_request().
 {
    int idx;
    for (idx = 0; idx < AST_VECTOR_SIZE(&cap1->preference_order); ++idx) {
       struct format_cap_framed *framed = AST_VECTOR_GET(&cap1->preference_order, idx);
       if (ast_format_cap_iscompatible_format(cap2, framed->format) != AST_FORMAT_CMP_NOT_EQUAL) {
          return 1;
       }
    }
    return 0;
 }
ast_format_cap_iscompatible_format()
enum ast_format_cmp_res ast_format_cap_iscompatible_format (const struct ast_format_cap * cap, const struct ast_format * format)
Find if ast_format is within the capabilities of the ast_format_cap object.
Return values
ast_format_cmp_res representing the result of the compatibility check between cap and format.
Definition at line 583 of file format_cap.c.
References ast_assert, ast_format_cmp(), AST_FORMAT_CMP_EQUAL, AST_FORMAT_CMP_NOT_EQUAL, ast_format_get_codec_id(), AST_LIST_TRAVERSE, AST_VECTOR_GET_ADDR, AST_VECTOR_SIZE, format_cap_framed::format, and NULL.
Referenced by add_sdp(), alsa_request(), ast_format_cap_iscompatible(), ast_speech_new(), AST_TEST_DEFINE(), chan_pjsip_indicate(), chan_pjsip_read_stream(), chan_pjsip_write_stream(), check_translation_path(), internal_format_cap_identical(), is_compatible_format(), jingle_read(), jingle_write(), mbl_request(), mgcp_rtp_read(), mgcp_write(), nbs_request(), ooh323_rtp_read(), ooh323_write(), oss_request(), process_sdp(), sip_indicate(), sip_rtp_read(), sip_write(), skinny_rtp_read(), skinny_write(), start_rtp(), try_suggested_sip_codec(), unistim_rtp_read(), and unistim_write().
 {
    enum ast_format_cmp_res res = AST_FORMAT_CMP_NOT_EQUAL;
    struct format_cap_framed_list *list;
    struct format_cap_framed *framed;
    ast_assert(format != NULL);
    if (ast_format_get_codec_id(format) >= AST_VECTOR_SIZE(&cap->formats)) {
       return AST_FORMAT_CMP_NOT_EQUAL;
    }
    list = AST_VECTOR_GET_ADDR(&cap->formats, ast_format_get_codec_id(format));
    AST_LIST_TRAVERSE(list, framed, entry) {
       enum ast_format_cmp_res cmp = ast_format_cmp(format, framed->format);
       if (cmp == AST_FORMAT_CMP_NOT_EQUAL) {
          continue;
       }
       res = cmp;
       if (res == AST_FORMAT_CMP_EQUAL) {
          break;
       }
    }
    return res;
 }
ast_format_cap_remove()
int ast_format_cap_remove (struct ast_format_cap * cap, struct ast_format * format)
Remove format capability from capability structure.
Note
format must be an exact pointer match to remove from capabilities structure.
Return values
0,remove was successful
-1,remove failed. Could not find format to remove
Definition at line 497 of file format_cap.c.
References ast_assert, ast_format_get_codec_id(), AST_LIST_REMOVE_CURRENT, AST_LIST_TRAVERSE_SAFE_BEGIN, AST_LIST_TRAVERSE_SAFE_END, AST_VECTOR_GET_ADDR, AST_VECTOR_REMOVE_CMP_ORDERED, AST_VECTOR_SIZE, FORMAT_CAP_FRAMED_ELEM_CLEANUP, FORMAT_CAP_FRAMED_ELEM_CMP, and NULL.
Referenced by ast_format_cap_update_by_allow_disallow(), AST_TEST_DEFINE(), check_translation_path(), and phone_new().
 {
    struct format_cap_framed_list *list;
    struct format_cap_framed *framed;
    ast_assert(format != NULL);
    if (ast_format_get_codec_id(format) >= AST_VECTOR_SIZE(&cap->formats)) {
       return -1;
    }
    list = AST_VECTOR_GET_ADDR(&cap->formats, ast_format_get_codec_id(format));
    AST_LIST_TRAVERSE_SAFE_BEGIN(list, framed, entry) {
       if (!FORMAT_CAP_FRAMED_ELEM_CMP(framed, format)) {
          continue;
       }
       AST_LIST_REMOVE_CURRENT(entry);
       FORMAT_CAP_FRAMED_ELEM_CLEANUP(framed);
       break;
    }
    AST_LIST_TRAVERSE_SAFE_END;
    return AST_VECTOR_REMOVE_CMP_ORDERED(&cap->preference_order, format,
       FORMAT_CAP_FRAMED_ELEM_CMP, FORMAT_CAP_FRAMED_ELEM_CLEANUP);
 }
ast_format_cap_remove_by_type()
void ast_format_cap_remove_by_type (struct ast_format_cap * cap, enum ast_media_type type)
Remove all formats matching a specific format type.
Parameters
cap The capabilities structure
type The media type to remove formats of
Note
All formats can be removed by using the AST_MEDIA_TYPE_UNKNOWN type.
Definition at line 525 of file format_cap.c.
References ao2_ref, ast_format_get_type(), AST_LIST_REMOVE_CURRENT, AST_LIST_TRAVERSE_SAFE_BEGIN, AST_LIST_TRAVERSE_SAFE_END, AST_MEDIA_TYPE_UNKNOWN, AST_VECTOR_GET_ADDR, AST_VECTOR_REMOVE_CMP_ORDERED, AST_VECTOR_SIZE, format_cap_framed::format, FORMAT_CAP_FRAMED_ELEM_CLEANUP, and FORMAT_CAP_FRAMED_ELEM_CMP.
Referenced by action_originate(), ast_format_cap_update_by_allow_disallow(), ast_rtp_codecs_payload_formats(), ast_sip_create_joint_call_cap(), ast_stream_create_resolved(), AST_TEST_DEFINE(), build_peer(), chan_pjsip_read_stream(), check_peer_ok(), create_addr_from_peer(), handle_request_invite(), jingle_interpret_description(), load_module(), media_offer_write_av(), originate_exec(), process_sdp(), reload_config(), request_channel(), send_direct_media_request(), set_caps(), sip_new(), sip_rtp_read(), sip_set_default_format_capabilities(), sip_set_rtp_peer(), skinny_session_cleanup(), transmit_modify_request(), and try_suggested_sip_codec().
 {
    int idx;
    for (idx = 0; idx < AST_VECTOR_SIZE(&cap->formats); ++idx) {
       struct format_cap_framed_list *list = AST_VECTOR_GET_ADDR(&cap->formats, idx);
       struct format_cap_framed *framed;
       AST_LIST_TRAVERSE_SAFE_BEGIN(list, framed, entry) {
          if ((type != AST_MEDIA_TYPE_UNKNOWN) &&
             ast_format_get_type(framed->format) != type) {
             continue;
          }
          AST_LIST_REMOVE_CURRENT(entry);
          AST_VECTOR_REMOVE_CMP_ORDERED(&cap->preference_order, framed->format,
             FORMAT_CAP_FRAMED_ELEM_CMP, FORMAT_CAP_FRAMED_ELEM_CLEANUP);
          ao2_ref(framed, -1);
       }
       AST_LIST_TRAVERSE_SAFE_END;
    }
 }
ast_format_cap_replace_from_cap()
void ast_format_cap_replace_from_cap (struct ast_format_cap * dst, const struct ast_format_cap * src, enum ast_media_type type)
Replace the formats of provided type in dst with equivalent formats from src.
Parameters
dst The destination capabilities structure
src The source capabilities structure
type The type of formats to replace.
Note
If AST_MEDIA_TYPE_UNKNOWN is passed as the type all known codecs will be replaced.
Formats present in src but not dst will not be appended to dst.
Definition at line 306 of file format_cap.c.
References ast_format_get_type(), AST_MEDIA_TYPE_UNKNOWN, AST_VECTOR_GET, AST_VECTOR_SIZE, format_cap_framed::format, format_cap_replace(), and format_cap_framed::framing.
Referenced by AST_TEST_DEFINE(), and try_suggested_sip_codec().
 {
    int idx;
    for (idx = 0; (idx < AST_VECTOR_SIZE(&src->preference_order)); ++idx) {
       struct format_cap_framed *framed = AST_VECTOR_GET(&src->preference_order, idx);
       if (type == AST_MEDIA_TYPE_UNKNOWN || ast_format_get_type(framed->format) == type) {
          format_cap_replace(dst, framed->format, framed->framing);
       }
    }
 }
ast_format_cap_set_framing()
void ast_format_cap_set_framing (struct ast_format_cap * cap, unsigned int framing)
Set the global framing.
Parameters
cap The capabilities structure.
framing The framing value (in milliseconds).
Note
This is used if a format does not provide a framing itself. Note that adding subsequent formats to the ast_format_cap structure may override this value, if the framing they require is less than the value set by this function.
Definition at line 136 of file format_cap.c.
References format_cap_framed::framing.
Referenced by ast_rtp_codecs_payload_formats(), ast_stream_create_resolved(), ast_stream_topology_create_from_format_cap(), AST_TEST_DEFINE(), ooh323_set_write_format(), and process_sdp_a_audio().
 {
    cap->framing = framing;
 }
ast_format_cap_update_by_allow_disallow()
int ast_format_cap_update_by_allow_disallow (struct ast_format_cap * cap, const char * list, int allowing)
Parse an "allow" or "deny" list and modify a format capabilities structure accordingly.
Parameters
cap The capabilities structure to modify
list The list containing formats to append or remove
allowing If zero, start removing formats specified in the list. If non-zero, start appending formats specified in the list.
Return values
0 on success
-1 on failure
Definition at line 320 of file format_cap.c.
References ao2_cleanup, ast_debug, ast_format_cache_get, ast_format_cap_append, ast_format_cap_append_by_type(), ast_format_cap_remove(), ast_format_cap_remove_by_type(), ast_log, AST_MEDIA_TYPE_UNKNOWN, ast_strdupa, ast_strip(), ast_strlen_zero, format_cap_framed::format, LOG_WARNING, NULL, parse(), and strsep().
Referenced by action_originate(), AST_TEST_DEFINE(), build_peer(), build_topology(), build_user(), codec_handler_fn(), config_parse_variables(), iax2_parse_allow_disallow(), media_offer_write_av(), originate_exec(), parse_line(), reload_config(), skinny_session_cleanup(), test_create_joint(), and validate_stream().
 {
    int res = 0, all = 0, iter_allowing;
    char *parse = NULL, *this = NULL, *psize = NULL;
    if (!allowing && ast_strlen_zero(list)) {
       return 0;
    }
    parse = ast_strdupa(list);
    /* If the list is being fed to us as a result of ast_format_cap_get_names,
     * strip off the parenthesis and immediately apply the inverse of the
     * allowing option
     */
    if (parse[0] == '(' && parse[strlen(parse) - 1] == ')') {
       parse++;
       parse[strlen(parse) - 1] = '\0';
       if (allowing) {
          ast_format_cap_remove_by_type(cap, AST_MEDIA_TYPE_UNKNOWN);
       } else {
          ast_format_cap_append_by_type(cap, AST_MEDIA_TYPE_UNKNOWN);
       }
    }
    while ((this = ast_strip(strsep(&parse, ",|")))) {
       int framems = 0;
       struct ast_format *format = NULL;
       iter_allowing = allowing;
       if (*this == '!') {
          this++;
          iter_allowing = !allowing;
       }
       if ((psize = strrchr(this, ':'))) {
          *psize++ = '\0';
          ast_debug(1, "Packetization for codec: %s is %s\n", this, psize);
          if (!sscanf(psize, "%30d", &framems) || (framems < 0)) {
             framems = 0;
             res = -1;
             ast_log(LOG_WARNING, "Bad packetization value for codec %s\n", this);
             continue;
          }
       }
       all = strcasecmp(this, "all") ? 0 : 1;
       if (!all && !(format = ast_format_cache_get(this))) {
          ast_log(LOG_WARNING, "Cannot %s unknown format '%s'\n", iter_allowing ? "allow" : "disallow", this);
          res = -1;
          continue;
       }
       if (cap) {
          if (iter_allowing) {
             if (all) {
                ast_format_cap_append_by_type(cap, AST_MEDIA_TYPE_UNKNOWN);
             } else {
                ast_format_cap_append(cap, format, framems);
             }
          } else {
             if (all) {
                ast_format_cap_remove_by_type(cap, AST_MEDIA_TYPE_UNKNOWN);
             } else {
                ast_format_cap_remove(cap, format);
             }
          }
       }
       ao2_cleanup(format);
    }
    return res;
 }
format_cap_destroy()
static void format_cap_destroy (void * obj) static
Destructor for format capabilities structure.
Definition at line 70 of file format_cap.c.
References ao2_ref, AST_LIST_REMOVE_HEAD, AST_VECTOR_FREE, AST_VECTOR_GET, AST_VECTOR_GET_ADDR, and AST_VECTOR_SIZE.
Referenced by __ast_format_cap_alloc().
 {
    struct ast_format_cap *cap = obj;
    int idx;
    for (idx = 0; idx < AST_VECTOR_SIZE(&cap->formats); idx++) {
       struct format_cap_framed_list *list = AST_VECTOR_GET_ADDR(&cap->formats, idx);
       struct format_cap_framed *framed;
       while ((framed = AST_LIST_REMOVE_HEAD(list, entry))) {
          ao2_ref(framed, -1);
       }
    }
    AST_VECTOR_FREE(&cap->formats);
    for (idx = 0; idx < AST_VECTOR_SIZE(&cap->preference_order); idx++) {
       struct format_cap_framed *framed = AST_VECTOR_GET(&cap->preference_order, idx);
       /* This will always be non-null, unlike formats */
       ao2_ref(framed, -1);
    }
    AST_VECTOR_FREE(&cap->preference_order);
 }
format_cap_framed_destroy()
static void format_cap_framed_destroy (void * obj) static
Destructor for format capabilities framed structure.
Definition at line 142 of file format_cap.c.
References ao2_cleanup, and format_cap_framed::format.
Referenced by __ast_format_cap_append().
 {
    struct format_cap_framed *framed = obj;
    ao2_cleanup(framed->format);
 }
format_cap_framed_init()
static int format_cap_framed_init (struct format_cap_framed * framed, struct ast_format_cap * cap, struct ast_format * format, unsigned int framing) inline static
Definition at line 149 of file format_cap.c.
References ao2_ref, ast_format_get_codec_id(), ast_format_get_default_ms(), AST_LIST_INSERT_HEAD, AST_VECTOR_APPEND, AST_VECTOR_GET_ADDR, AST_VECTOR_REPLACE, AST_VECTOR_SIZE, format_cap_framed::framing, and MIN.
Referenced by __ast_format_cap_append().
 {
    struct format_cap_framed_list *list;
    framed->framing = framing;
    if (ast_format_get_codec_id(format) >= AST_VECTOR_SIZE(&cap->formats)) {
       if (AST_VECTOR_REPLACE(&cap->formats, ast_format_get_codec_id(format), format_cap_framed_list_empty)) {
          ao2_ref(framed, -1);
          return -1;
       }
    }
    list = AST_VECTOR_GET_ADDR(&cap->formats, ast_format_get_codec_id(format));
    /* This takes the allocation reference */
    if (AST_VECTOR_APPEND(&cap->preference_order, framed)) {
       ao2_ref(framed, -1);
       return -1;
    }
    /* Order doesn't matter for formats, so insert at the head for performance reasons */
    ao2_ref(framed, +1);
    AST_LIST_INSERT_HEAD(list, framed, entry);
    cap->framing = MIN(cap->framing, framing ? framing : ast_format_get_default_ms(format));
    return 0;
 }
format_cap_init()
static int format_cap_init (struct ast_format_cap * cap, enum ast_format_cap_flags flags) inline static
Definition at line 102 of file format_cap.c.
References AST_VECTOR_INIT.
Referenced by __ast_format_cap_alloc().
 {
    if (AST_VECTOR_INIT(&cap->formats, 0)) {
       return -1;
    }
    /* TODO: Look at common usage of this and determine a good starting point */
    if (AST_VECTOR_INIT(&cap->preference_order, 5)) {
       return -1;
    }
    cap->framing = UINT_MAX;
    return 0;
 }
format_cap_replace()
static int format_cap_replace (struct ast_format_cap * cap, struct ast_format * format, unsigned int framing) static
Definition at line 286 of file format_cap.c.
References ao2_t_replace, ast_assert, ast_format_get_codec_id(), AST_VECTOR_GET, AST_VECTOR_SIZE, format_cap_framed::format, format_cap_framed::framing, and NULL.
Referenced by ast_format_cap_replace_from_cap().
 {
    struct format_cap_framed *framed;
    int i;
    ast_assert(format != NULL);
    for (i = 0; i < AST_VECTOR_SIZE(&cap->preference_order); i++) {
       framed = AST_VECTOR_GET(&cap->preference_order, i);
       if (ast_format_get_codec_id(format) == ast_format_get_codec_id(framed->format)) {
          ao2_t_replace(framed->format, format, "replacing with new format");
          framed->framing = framing;
          return 0;
       }
    }
    return -1;
 }
format_in_format_cap()
static int format_in_format_cap (struct ast_format_cap * cap, struct ast_format * format) static
Definition at line 179 of file format_cap.c.
References ast_format_get_codec_id(), AST_VECTOR_GET, AST_VECTOR_SIZE, and format_cap_framed::format.
Referenced by __ast_format_cap_append().
 {
    struct format_cap_framed *framed;
    int i;
    for (i = 0; i < AST_VECTOR_SIZE(&cap->preference_order); i++) {
       framed = AST_VECTOR_GET(&cap->preference_order, i);
       if (ast_format_get_codec_id(format) == ast_format_get_codec_id(framed->format)) {
          return 1;
       }
    }
    return 0;
 }
internal_format_cap_identical()
static int internal_format_cap_identical (const struct ast_format_cap * cap1, const struct ast_format_cap * cap2) static
Definition at line 670 of file format_cap.c.
References ao2_ref, ast_format_cap_get_format(), ast_format_cap_iscompatible_format(), AST_FORMAT_CMP_EQUAL, AST_VECTOR_SIZE, and tmp().
Referenced by ast_format_cap_identical().
 {
    int idx;
    struct ast_format *tmp;
    for (idx = 0; idx < AST_VECTOR_SIZE(&cap1->preference_order); ++idx) {
       tmp = ast_format_cap_get_format(cap1, idx);
       if (ast_format_cap_iscompatible_format(cap2, tmp) != AST_FORMAT_CMP_EQUAL) {
          ao2_ref(tmp, -1);
          return 0;
       }
       ao2_ref(tmp, -1);
    }
    return 1;
 }
Variable Documentation
format_cap_framed_list_empty
const struct format_cap_framed_list format_cap_framed_list_empty = AST_LIST_HEAD_NOLOCK_INIT_VALUE static
Dummy empty list for when we are inserting a new list.
Definition at line 67 of file format_cap.c.