Asterisk - The Open Source Telephony Project: astconfigparser Namespace Reference
astconfigparser Namespace Reference
Data Structures
class MultiOrderedConfigParser
class Section
Functions
def find_dict (mdicts, key, val)
def merge_values (left, right, key)
def remove_comment (line, is_comment)
def try_include (line)
def try_option (line)
def try_section (line)
def write_dicts (config_file, mdicts)
Variables
string COMMENT = ';'
string COMMENT_END = '--;'
string COMMENT_START = ';--'
string DEFAULTSECT = 'general'
Detailed Description
Copyright (C) 2016, Digium, Inc.
This program is free software, distributed under the terms of
the GNU General Public License Version 2.
Function Documentation
find_dict()
def astconfigparser.find_dict (mdicts, key, val)
Given a list of mult-dicts, return the multi-dict that contains
the given key/value pair.
Definition at line 289 of file astconfigparser.py.
 def find_dict(mdicts, key, val):
     """
     Given a list of mult-dicts, return the multi-dict that contains
     the given key/value pair.
     """
     def found(d):
         return key in d and val in d[key]
     try:
         return [d for d in mdicts if found(d)][0]
     except IndexError:
         raise LookupError("Dictionary not located for key = %s, value = %s"
                           % (key, val))
merge_values()
def astconfigparser.merge_values (left, right, key)
Merges values from right into left.
Definition at line 16 of file astconfigparser.py.
Referenced by Section.get_merged().
 def merge_values(left, right, key):
     """Merges values from right into left."""
     if isinstance(left, list):
         vals0 = left
     else:  # assume dictionary
         vals0 = left[key] if key in left else []
     vals1 = right[key] if key in right else []
     return vals0 + [i for i in vals1 if i not in vals0]
remove_comment()
def astconfigparser.remove_comment (line, is_comment)
Remove any commented elements from the line.
Definition at line 195 of file astconfigparser.py.
Referenced by MultiOrderedConfigParser.read().
 def remove_comment(line, is_comment):
     """Remove any commented elements from the line."""
     if not line:
         return line, is_comment
     if is_comment:
         part = line.partition(COMMENT_END)
         if part[1]:
             # found multi-line comment end check string after it
             return remove_comment(part[2], False)
         return "", True
     part = line.partition(COMMENT_START)
     if part[1] and not part[2].startswith('-'):
         # found multi-line comment start check string before
         # it to make sure there wasn't an eol comment in it
         has_comment = part[0].partition(COMMENT)
         if has_comment[1]:
             # eol comment found return anything before it
             return has_comment[0], False
         # check string after it to see if the comment ends
         line, is_comment = remove_comment(part[2], True)
         if is_comment:
             # return possible string data before comment
             return part[0].strip(), True
         # otherwise it was an embedded comment so combine
         return ''.join([part[0].strip(), ' ', line]).rstrip(), False
     # find the first occurence of a comment that is not escaped
     match = re.match(r'.*?([^\\];)', line)
     if match:
          # the end of where the real string is is where the comment starts
          line = line[0:(match.end()-1)]
     if line.startswith(";"):
          # if the line is actually a comment just ignore it all
          line = ""
     return line.replace("\\", "").strip(), False
try_include()
def astconfigparser.try_include (line)
Checks to see if the given line is an include.  If so return the
included filename, otherwise None.
Definition at line 237 of file astconfigparser.py.
Referenced by process_text_line(), and MultiOrderedConfigParser.read().
 def try_include(line):
     """
     Checks to see if the given line is an include.  If so return the
     included filename, otherwise None.
     """
     match = re.match('^#include\s*([^;]+).*$', line)
     if match:
         trimmed = match.group(1).rstrip()
         quoted = re.match('^"([^"]+)"$', trimmed)
         if quoted:
             return quoted.group(1)
         bracketed = re.match('^<([^>]+)>$', trimmed)
         if bracketed:
             return bracketed.group(1)
         return trimmed
     return None
try_option()
def astconfigparser.try_option (line)
Parses the line as an option, returning the key/value pair.
Definition at line 280 of file astconfigparser.py.
Referenced by MultiOrderedConfigParser.read().
 def try_option(line):
     """Parses the line as an option, returning the key/value pair."""
     data = re.split('=>?', line, 1)
     # should split in two (key/val), but either way use first two elements
     return data[0].rstrip(), data[1].lstrip()
try_section()
def astconfigparser.try_section (line)
Checks to see if the given line is a section. If so return the section
name, otherwise return 'None'.
Definition at line 256 of file astconfigparser.py.
References replace().
Referenced by MultiOrderedConfigParser.read().
 def try_section(line):
     """
     Checks to see if the given line is a section. If so return the section
     name, otherwise return 'None'.
     """
     # leading spaces were stripped when checking for comments
     if not line.startswith('['):
         return None, False, []
     section, delim, templates = line.partition(']')
     if not templates:
         return section[1:], False, []
     # strip out the parens and parse into an array
     templates = templates.replace('(', "").replace(')', "").split(',')
     # go ahead and remove extra whitespace
     templates = [i.strip() for i in templates]
     try:
         templates.remove('!')
         return section[1:], True, templates
     except:
         return section[1:], False, templates
write_dicts()
def astconfigparser.write_dicts (config_file, mdicts)
Write the contents of the mdicts to the specified config file
Definition at line 305 of file astconfigparser.py.
References str.
Referenced by MultiOrderedConfigParser.write(), and sip_to_pjsip.write_pjsip().
 def write_dicts(config_file, mdicts):
     """Write the contents of the mdicts to the specified config file"""
     for section, sect_list in mdicts.iteritems():
         # every section contains a list of dictionaries
         for sect in sect_list:
             config_file.write("[%s]\n" % section)
             for key, val_list in sect.iteritems():
                 # every value is also a list
                 for v in val_list:
                     key_val = key
                     if v is not None:
                         key_val += " = " + str(v)
                         config_file.write("%s\n" % (key_val))
             config_file.write("\n")
Variable Documentation
COMMENT
string COMMENT = ';'
Definition at line 188 of file astconfigparser.py.
COMMENT_END
string COMMENT_END = '--;'
Definition at line 190 of file astconfigparser.py.
COMMENT_START
string COMMENT_START = ';--'
Definition at line 189 of file astconfigparser.py.
DEFAULTSECT
string DEFAULTSECT = 'general'
Definition at line 192 of file astconfigparser.py.