Asterisk - The Open Source Telephony Project: 10aedae86a32_add_outgoing_enum_va Namespace Reference
10aedae86a32_add_outgoing_enum_va Namespace Reference
Functions
def downgrade ()
def upgrade ()
Variables
string down_revision = '5950038a6ead'
list NEW_ENUM = ['yes', 'no', 'nonat', 'update', 'outgoing']
new_type = sa.Enum(*NEW_ENUM, name='sip_directmedia_values_v2')
list OLD_ENUM = ['yes', 'no', 'nonat', 'update']
old_type = sa.Enum(*OLD_ENUM, name='sip_directmedia_values')
string revision = '10aedae86a32'
tcr
Function Documentation
downgrade()
def 10aedae86a32_add_outgoing_enum_va.downgrade ()
Definition at line 63 of file 10aedae86a32_add_outgoing_enum_va.py.
 def downgrade():
     context = op.get_context()
     op.execute(tcr.update().where(tcr.c.directmedia==u'outgoing')
                .values(directmedia=None))
     if context.bind.dialect.name != 'postgresql':
         op.alter_column('sippeers', 'directmedia',
                         type_=old_type,
                         existing_type=new_type)
     else:
         enum = ENUM("yes", "no", "nonat", "update",
                     name="sip_directmedia_values")
         enum.create(op.get_bind(), checkfirst=False)
         op.execute('ALTER TABLE sippeers ALTER COLUMN directmedia TYPE'
                    ' sip_directmedia_values USING'
                    ' directmedia::text::sip_directmedia_values')
         ENUM(name="sip_directmedia_values_v2").drop(op.get_bind(),
                                                 checkfirst=False)
upgrade()
def 10aedae86a32_add_outgoing_enum_va.upgrade ()
Definition at line 44 of file 10aedae86a32_add_outgoing_enum_va.py.
 def upgrade():
     context = op.get_context()
     # Upgrading to this revision WILL clear your directmedia values.
     if context.bind.dialect.name != 'postgresql':
         op.alter_column('sippeers', 'directmedia',
                         type_=new_type,
                         existing_type=old_type)
     else:
         enum = ENUM("yes", "no", "nonat", "update", "outgoing",
                     name="sip_directmedia_values_v2")
         enum.create(op.get_bind(), checkfirst=False)
         op.execute('ALTER TABLE sippeers ALTER COLUMN directmedia TYPE'
                    ' sip_directmedia_values_v2 USING'
                    ' directmedia::text::sip_directmedia_values_v2')
         ENUM(name="sip_directmedia_values").drop(op.get_bind(), checkfirst=False)
Variable Documentation
down_revision
string down_revision = '5950038a6ead'
Definition at line 29 of file 10aedae86a32_add_outgoing_enum_va.py.
NEW_ENUM
list NEW_ENUM = ['yes', 'no', 'nonat', 'update', 'outgoing']
Definition at line 36 of file 10aedae86a32_add_outgoing_enum_va.py.
new_type
new_type = sa.Enum(*NEW_ENUM, name='sip_directmedia_values_v2')
Definition at line 39 of file 10aedae86a32_add_outgoing_enum_va.py.
Referenced by ast_rtp_codecs_payloads_set_m_type(), ast_rtp_codecs_payloads_set_rtpmap_type_rate(), payload_mapping_rx_clear_primary(), and rtp_codecs_assign_payload_code_rx().
OLD_ENUM
list OLD_ENUM = ['yes', 'no', 'nonat', 'update']
Definition at line 35 of file 10aedae86a32_add_outgoing_enum_va.py.
old_type
old_type = sa.Enum(*OLD_ENUM, name='sip_directmedia_values')
Definition at line 38 of file 10aedae86a32_add_outgoing_enum_va.py.
revision
string revision = '10aedae86a32'
Definition at line 28 of file 10aedae86a32_add_outgoing_enum_va.py.
tcr
tcr
Initial value:
 =  sa.sql.table('sippeers', sa.Column('directmedia', new_type,
                    nullable=True))
Definition at line 41 of file 10aedae86a32_add_outgoing_enum_va.py.