Asterisk - The Open Source Telephony Project: res_hep_rtcp.c File Reference
res_hep_rtcp.c File Reference
RTCP logging with Homer.
#include "asterisk.h"
#include "asterisk/res_hep.h"
#include "asterisk/module.h"
#include "asterisk/netsock2.h"
#include "asterisk/channel.h"
#include "asterisk/pbx.h"
#include "asterisk/stasis.h"
#include "asterisk/rtp_engine.h"
#include "asterisk/json.h"
#include "asterisk/config.h"
Functions
static void __reg_module (void)
static void __unreg_module (void)
static char * assign_uuid (struct ast_json *json_channel)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int load_module (void)
static void rtcp_message_handler (struct stasis_message *message)
static void rtp_topic_handler (void *data, struct stasis_subscription *sub, struct stasis_message *message)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_DEFAULT , .description = "RTCP HEPv3 Logger" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_EXTENDED, .load = load_module, .unload = unload_module, .requires = "res_hep", }
static const struct ast_module_info * ast_module_info = &__mod_info
static struct stasis_subscription * stasis_rtp_subscription
Detailed Description
RTCP logging with Homer.
Author
Matt Jordan mjord.nosp@m.an@d.nosp@m.igium.nosp@m..com
Definition in file res_hep_rtcp.c.
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 191 of file res_hep_rtcp.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 191 of file res_hep_rtcp.c.
assign_uuid()
static char* assign_uuid (struct ast_json * json_channel) static
Definition at line 46 of file res_hep_rtcp.c.
References ast_begins_with(), ast_channel_cleanup, ast_channel_get_by_name(), ast_func_read(), ast_json_object_get(), ast_json_string_get(), ast_strdup, buf, HEP_UUID_TYPE_CALL_ID, hepv3_get_uuid_type(), and NULL.
Referenced by rtcp_message_handler().
 {
    const char *channel_name = ast_json_string_get(ast_json_object_get(json_channel, "name"));
    enum hep_uuid_type uuid_type = hepv3_get_uuid_type();
    char *uuid = NULL;
    if (!channel_name) {
       return NULL;
    }
    if (uuid_type == HEP_UUID_TYPE_CALL_ID) {
       struct ast_channel *chan = NULL;
       char buf[128];
       if (ast_begins_with(channel_name, "PJSIP")) {
          chan = ast_channel_get_by_name(channel_name);
          if (chan && !ast_func_read(chan, "CHANNEL(pjsip,call-id)", buf, sizeof(buf))) {
             uuid = ast_strdup(buf);
          }
       } else if (ast_begins_with(channel_name, "SIP")) {
          chan = ast_channel_get_by_name(channel_name);
          if (chan && !ast_func_read(chan, "SIP_HEADER(call-id)", buf, sizeof(buf))) {
             uuid = ast_strdup(buf);
          }
       }
       ast_channel_cleanup(chan);
    }
    /* If we couldn't get the call-id or didn't want it, just use the channel name */
    if (!uuid) {
       uuid = ast_strdup(channel_name);
    }
    return uuid;
 }
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 191 of file res_hep_rtcp.c.
load_module()
static int load_module (void) static
Definition at line 158 of file res_hep_rtcp.c.
References ast_log, AST_LOG_WARNING, AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, ast_rtp_rtcp_received_type(), ast_rtp_rtcp_sent_type(), ast_rtp_topic(), hepv3_is_loaded(), NULL, rtp_topic_handler(), stasis_subscribe, stasis_subscription_accept_message_type(), STASIS_SUBSCRIPTION_FILTER_SELECTIVE, and stasis_subscription_set_filter().
Referenced by unload_module().
 {
    if (!hepv3_is_loaded()) {
       ast_log(AST_LOG_WARNING, "res_hep is disabled; declining module load\n");
       return AST_MODULE_LOAD_DECLINE;
    }
    stasis_rtp_subscription = stasis_subscribe(ast_rtp_topic(),
       rtp_topic_handler, NULL);
    if (!stasis_rtp_subscription) {
       return AST_MODULE_LOAD_DECLINE;
    }
    stasis_subscription_accept_message_type(stasis_rtp_subscription, ast_rtp_rtcp_sent_type());
    stasis_subscription_accept_message_type(stasis_rtp_subscription, ast_rtp_rtcp_received_type());
    stasis_subscription_set_filter(stasis_rtp_subscription, STASIS_SUBSCRIPTION_FILTER_SELECTIVE);
    return AST_MODULE_LOAD_SUCCESS;
 }
rtcp_message_handler()
static void rtcp_message_handler (struct stasis_message * message) static
Definition at line 85 of file res_hep_rtcp.c.
References ao2_ref, assign_uuid(), ast_json_dump_string, ast_json_free(), ast_json_object_get(), ast_json_string_get(), ast_json_unref(), ast_sockaddr_parse(), ast_strlen_zero, ast_tvnow(), hepv3_capture_info::capture_time, hepv3_capture_info::capture_type, hepv3_capture_info::dst_addr, HEPV3_CAPTURE_TYPE_RTCP, hepv3_create_capture_info(), hepv3_send_packet(), NULL, PARSE_PORT_REQUIRE, RAII_VAR, hepv3_capture_info::src_addr, stasis_message_to_json(), hepv3_capture_info::uuid, and hepv3_capture_info::zipped.
Referenced by rtp_topic_handler().
 {
    RAII_VAR(struct ast_json *, json_payload, NULL, ast_json_unref);
    RAII_VAR(char *,  payload, NULL, ast_json_free);
    struct ast_json *json_blob;
    struct ast_json *json_channel;
    struct ast_json *json_rtcp;
    struct hepv3_capture_info *capture_info;
    struct ast_json *from;
    struct ast_json *to;
    struct timeval current_time = ast_tvnow();
    json_payload = stasis_message_to_json(message, NULL);
    if (!json_payload) {
       return;
    }
    json_blob = ast_json_object_get(json_payload, "blob");
    if (!json_blob) {
       return;
    }
    json_channel = ast_json_object_get(json_payload, "channel");
    if (!json_channel) {
       return;
    }
    json_rtcp = ast_json_object_get(json_payload, "rtcp_report");
    if (!json_rtcp) {
       return;
    }
    from = ast_json_object_get(json_blob, "from");
    to = ast_json_object_get(json_blob, "to");
    if (!from || !to) {
       return;
    }
    payload = ast_json_dump_string(json_rtcp);
    if (ast_strlen_zero(payload)) {
       return;
    }
    capture_info = hepv3_create_capture_info(payload, strlen(payload));
    if (!capture_info) {
       return;
    }
    ast_sockaddr_parse(&capture_info->src_addr, ast_json_string_get(from), PARSE_PORT_REQUIRE);
    ast_sockaddr_parse(&capture_info->dst_addr, ast_json_string_get(to), PARSE_PORT_REQUIRE);
    capture_info->uuid = assign_uuid(json_channel);
    if (!capture_info->uuid) {
       ao2_ref(capture_info, -1);
       return;
    }
    capture_info->capture_time = current_time;
    capture_info->capture_type = HEPV3_CAPTURE_TYPE_RTCP;
    capture_info->zipped = 0;
    hepv3_send_packet(capture_info);
 }
rtp_topic_handler()
static void rtp_topic_handler (void * data, struct stasis_subscription * sub, struct stasis_message * message) static
Definition at line 148 of file res_hep_rtcp.c.
References ast_rtp_rtcp_received_type(), ast_rtp_rtcp_sent_type(), rtcp_message_handler(), and stasis_message_type().
Referenced by load_module().
 {
    struct stasis_message_type *message_type = stasis_message_type(message);
    if ((message_type == ast_rtp_rtcp_sent_type()) ||
       (message_type == ast_rtp_rtcp_received_type())) {
       rtcp_message_handler(message);
    }
 }
unload_module()
static int unload_module (void) static
Definition at line 177 of file res_hep_rtcp.c.
References AST_MODFLAG_DEFAULT, AST_MODULE_INFO(), AST_MODULE_SUPPORT_EXTENDED, ASTERISK_GPL_KEY, load_module(), and stasis_unsubscribe_and_join().
 {
    if (stasis_rtp_subscription) {
       stasis_rtp_subscription = stasis_unsubscribe_and_join(stasis_rtp_subscription);
    }
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_DEFAULT , .description = "RTCP HEPv3 Logger" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_EXTENDED, .load = load_module, .unload = unload_module, .requires = "res_hep", } static
Definition at line 191 of file res_hep_rtcp.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 191 of file res_hep_rtcp.c.
stasis_rtp_subscription
struct stasis_subscription* stasis_rtp_subscription static
Definition at line 44 of file res_hep_rtcp.c.