Asterisk - The Open Source Telephony Project: res_pjproject.c File Reference
res_pjproject.c File Reference
Bridge PJPROJECT logging to Asterisk logging.
#include "asterisk.h"
#include <stdarg.h>
#include <pjlib.h>
#include <pjsip.h>
#include <pj/log.h>
#include "asterisk/options.h"
#include "asterisk/logger.h"
#include "asterisk/module.h"
#include "asterisk/cli.h"
#include "asterisk/res_pjproject.h"
#include "asterisk/vector.h"
#include "asterisk/sorcery.h"
#include "asterisk/test.h"
#include "asterisk/netsock2.h"
Data Structures
struct log_mappings
struct max_pjproject_log_level_check
struct pjproject_log_intercept_data
Macros
#define __LOG_SUPPRESS -1
#define NOT_EQUALS(a, b) (a != b)
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
void ast_pjproject_caching_pool_destroy (pj_caching_pool *cp)
Destroy caching pool factory and all cached pools.
void ast_pjproject_caching_pool_init (pj_caching_pool *cp, const pj_pool_factory_policy *policy, pj_size_t max_capacity)
Initialize the caching pool factory.
int ast_pjproject_get_buildopt (char *option, char *format_string,...)
Retrieve a pjproject build option.
void ast_pjproject_log_intercept_begin (int fd)
Begin PJPROJECT log interception for CLI output.
void ast_pjproject_log_intercept_end (void)
End PJPROJECT log interception for CLI output.
int ast_sockaddr_from_pj_sockaddr (struct ast_sockaddr *addr, const pj_sockaddr *pjaddr)
Fill an ast_sockaddr from a pj_sockaddr.
int ast_sockaddr_to_pj_sockaddr (const struct ast_sockaddr *addr, pj_sockaddr *pjaddr)
Fill a pj_sockaddr from an ast_sockaddr.
AST_TEST_DEFINE (ast_sockaddr_to_pj_sockaddr_test)
AST_TEST_DEFINE (ast_sockaddr_from_pj_sockaddr_test)
static AST_VECTOR (buildopts, char *)
static void capture_buildopts_cb (int level, const char *data, int len)
static void fill_with_garbage (void *x, ssize_t len)
static int get_log_level (int pj_level)
static struct log_mappings * get_log_mappings (void)
static char * handle_pjproject_set_log_level (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static char * handle_pjproject_show_buildopts (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static char * handle_pjproject_show_log_level (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static char * handle_pjproject_show_log_mappings (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static int load_module (void)
static void log_forwarder (int level, const char *data, int len)
static void * mapping_alloc (const char *name)
static void mapping_destroy (void *object)
static int reload_module (void)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_GLOBAL_SYMBOLS | AST_MODFLAG_LOAD_ORDER , .description = "PJPROJECT Log and Utility Support" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .reload = reload_module, .load_pri = AST_MODPRI_CHANNEL_DEPEND - 6, .requires = "res_sorcery_config", }
static const struct ast_module_info * ast_module_info = &__mod_info
static unsigned decor_orig
static struct log_mappings * default_log_mappings
static pj_log_func * log_cb_orig
static struct ast_cli_entry pjproject_cli []
static struct pjproject_log_intercept_data pjproject_log_intercept
static struct ast_sorcery * pjproject_sorcery
Detailed Description
Bridge PJPROJECT logging to Asterisk logging.
Author
David M. Lee, II dlee@.nosp@m.digi.nosp@m.um.co.nosp@m.m
PJPROJECT logging doesn't exactly match Asterisk logging, but mapping the two is not too bad. PJPROJECT log levels are identified by a single int. Limits are not specified by PJPROJECT, but their implementation used 1 through 6.
The mapping is as follows:
0: LOG_ERROR
1: LOG_ERROR
2: LOG_WARNING
3 and above: equivalent to ast_debug(level, ...) for res_pjproject.so
Definition in file res_pjproject.c.
Macro Definition Documentation
__LOG_SUPPRESS
#define __LOG_SUPPRESS -1
Definition at line 168 of file res_pjproject.c.
Referenced by get_log_level(), and log_forwarder().
NOT_EQUALS
#define NOT_EQUALS (a, b) (a != b)
Definition at line 730 of file res_pjproject.c.
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 772 of file res_pjproject.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 772 of file res_pjproject.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 772 of file res_pjproject.c.
ast_pjproject_caching_pool_destroy()
void ast_pjproject_caching_pool_destroy (pj_caching_pool * cp)
Destroy caching pool factory and all cached pools.
Since
13.21.0
Parameters
cp Caching pool factory to destroy
Returns
Nothing
Definition at line 472 of file res_pjproject.c.
Referenced by rtp_terminate_pjproject(), unload_module(), and unload_pjsip().
 {
    pj_caching_pool_destroy(cp);
 }
ast_pjproject_caching_pool_init()
void ast_pjproject_caching_pool_init (pj_caching_pool * cp, const pj_pool_factory_policy * policy, pj_size_t max_capacity)
Initialize the caching pool factory.
Since
13.21.0
Parameters
cp Caching pool factory to initialize
policy Pool factory policy
max_capacity Total capacity to be retained in the cache. Zero disables caching.
Returns
Nothing
Definition at line 465 of file res_pjproject.c.
References ast_option_pjproject_cache_pools.
Referenced by load_module(), and load_pjsip().
 {
    /* Passing a max_capacity of zero disables caching pools */
    pj_caching_pool_init(cp, policy, ast_option_pjproject_cache_pools ? max_capacity : 0);
 }
ast_pjproject_get_buildopt()
int ast_pjproject_get_buildopt (char * option, char * format_string, ...)
Retrieve a pjproject build option.
Parameters
option The build option requested
format_string A scanf-style format string to parse the option value into
... Pointers to variables to receive the values parsed
Return values
The number of values parsed
Since
13.8.0
Note
The option requested must be from those returned by pj_dump_config() which can be displayed with the 'pjsip show buildopts' CLI command.
Sample Usage:
int max_hostname;
ast_sip_get_pjproject_buildopt("PJ_MAX_HOSTNAME", "%d", &max_hostname);
Definition at line 246 of file res_pjproject.c.
References ast_alloca, AST_VECTOR_GET, and AST_VECTOR_SIZE.
Referenced by ast_sip_initialize_sorcery_location(), and load_module().
 {
    int res = 0;
    char *format_temp;
    int i;
    format_temp = ast_alloca(strlen(option) + strlen(" : ") + strlen(format_string) + 1);
    sprintf(format_temp, "%s : %s", option, format_string);
    for (i = 0; i < AST_VECTOR_SIZE(&buildopts); i++) {
       va_list arg_ptr;
       va_start(arg_ptr, format_string);
       res = vsscanf(AST_VECTOR_GET(&buildopts, i), format_temp, arg_ptr);
       va_end(arg_ptr);
       if (res) {
          break;
       }
    }
    return res;
 }
ast_pjproject_log_intercept_begin()
void ast_pjproject_log_intercept_begin (int fd)
Begin PJPROJECT log interception for CLI output.
Since
13.8.0
Parameters
fd CLI file descriptior to send intercepted output.
Note
ast_pjproject_log_intercept_begin() and ast_pjproject_log_intercept_end() must always be called in pairs.
Returns
Nothing
Definition at line 269 of file res_pjproject.c.
References ast_mutex_lock, pjproject_log_intercept_data::fd, and pjproject_log_intercept_data::thread.
Referenced by do_cli_dump_endpt().
 {
    /* Protect from other CLI instances trying to do this at the same time. */
    ast_mutex_lock(&pjproject_log_intercept_lock);
    pjproject_log_intercept.thread = pthread_self();
    pjproject_log_intercept.fd = fd;
 }
ast_pjproject_log_intercept_end()
void ast_pjproject_log_intercept_end (void)
End PJPROJECT log interception for CLI output.
Since
13.8.0
Note
ast_pjproject_log_intercept_begin() and ast_pjproject_log_intercept_end() must always be called in pairs.
Returns
Nothing
Definition at line 278 of file res_pjproject.c.
References ast_mutex_unlock, AST_PTHREADT_NULL, pjproject_log_intercept_data::fd, and pjproject_log_intercept_data::thread.
Referenced by do_cli_dump_endpt().
 {
    pjproject_log_intercept.fd = -1;
    pjproject_log_intercept.thread = AST_PTHREADT_NULL;
    ast_mutex_unlock(&pjproject_log_intercept_lock);
 }
ast_sockaddr_from_pj_sockaddr()
int ast_sockaddr_from_pj_sockaddr (struct ast_sockaddr * addr, const pj_sockaddr * pjaddr)
Fill an ast_sockaddr from a pj_sockaddr.
Since
13.24.0
Parameters
addr The target address to receive the copied address
pjaddr The source address to copy
Return values
0 Success
-1 Failure
Definition at line 502 of file res_pjproject.c.
References HAVE_PJPROJECT_BUNDLED, ast_sockaddr::len, and ast_sockaddr::ss.
Referenced by AST_TEST_DEFINE().
 {
    if (pjaddr->addr.sa_family == pj_AF_INET()) {
       struct sockaddr_in *sin = (struct sockaddr_in *) &addr->ss;
       sin->sin_family = AF_INET;
 #ifdef HAVE_PJPROJECT_BUNDLED
       sin->sin_addr = pjaddr->ipv4.sin_addr;
 #else
       sin->sin_addr.s_addr = pjaddr->ipv4.sin_addr.s_addr;
 #endif
       sin->sin_port   = pjaddr->ipv4.sin_port;
       addr->len = sizeof(struct sockaddr_in);
    } else if (pjaddr->addr.sa_family == pj_AF_INET6()) {
       struct sockaddr_in6 *sin = (struct sockaddr_in6 *) &addr->ss;
       sin->sin6_family   = AF_INET6;
       sin->sin6_port     = pjaddr->ipv6.sin6_port;
       sin->sin6_flowinfo = pjaddr->ipv6.sin6_flowinfo;
       sin->sin6_scope_id = pjaddr->ipv6.sin6_scope_id;
       memcpy(&sin->sin6_addr, &pjaddr->ipv6.sin6_addr, sizeof(sin->sin6_addr));
       addr->len = sizeof(struct sockaddr_in6);
    } else {
       memset(addr, 0, sizeof(*addr));
       return -1;
    }
    return 0;
 }
ast_sockaddr_to_pj_sockaddr()
int ast_sockaddr_to_pj_sockaddr (const struct ast_sockaddr * addr, pj_sockaddr * pjaddr)
Fill a pj_sockaddr from an ast_sockaddr.
Since
13.24.0
Parameters
addr The source address to copy
pjaddr The target address to receive the copied address
Return values
0 Success
-1 Failure
Definition at line 477 of file res_pjproject.c.
References ast_sockaddr::ss.
Referenced by AST_TEST_DEFINE(), and rtp_add_candidates_to_ice().
 {
    if (addr->ss.ss_family == AF_INET) {
       struct sockaddr_in *sin = (struct sockaddr_in *) &addr->ss;
       pjaddr->ipv4.sin_family = pj_AF_INET();
 #ifdef HAVE_PJPROJECT_BUNDLED
       pjaddr->ipv4.sin_addr = sin->sin_addr;
 #else
       pjaddr->ipv4.sin_addr.s_addr = sin->sin_addr.s_addr;
 #endif
       pjaddr->ipv4.sin_port   = sin->sin_port;
    } else if (addr->ss.ss_family == AF_INET6) {
       struct sockaddr_in6 *sin = (struct sockaddr_in6 *) &addr->ss;
       pjaddr->ipv6.sin6_family   = pj_AF_INET6();
       pjaddr->ipv6.sin6_port     = sin->sin6_port;
       pjaddr->ipv6.sin6_flowinfo = sin->sin6_flowinfo;
       pjaddr->ipv6.sin6_scope_id = sin->sin6_scope_id;
       memcpy(&pjaddr->ipv6.sin6_addr, &sin->sin6_addr, sizeof(pjaddr->ipv6.sin6_addr));
    } else {
       memset(pjaddr, 0, sizeof(*pjaddr));
       return -1;
    }
    return 0;
 }
AST_TEST_DEFINE() [1/2]
AST_TEST_DEFINE (ast_sockaddr_to_pj_sockaddr_test)
Definition at line 541 of file res_pjproject.c.
References ast_sockaddr_parse(), ast_sockaddr_to_pj_sockaddr(), AST_TEST_FAIL, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_test_status_update, fill_with_garbage(), sip_to_pjsip::info(), NULL, TEST_EXECUTE, and TEST_INIT.
 {
    char *candidates[] = {
       "127.0.0.1:5555",
       "[::]:4444",
       "192.168.0.100:0",
       "[fec0::1:80]:0",
       "[fec0::1]:80",
       NULL,
    }, **candidate = candidates;
    switch (cmd) {
    case TEST_INIT:
       info->name = "ast_sockaddr_to_pj_sockaddr_test";
       info->category = "/res/res_pjproject/";
       info->summary = "Validate conversions from an ast_sockaddr to a pj_sockaddr";
       info->description = "This test converts an ast_sockaddr to a pj_sockaddr and validates\n"
          "that the two evaluate to the same string when formatted.";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    while (*candidate) {
       struct ast_sockaddr addr = {{0,}};
       pj_sockaddr pjaddr;
       char buffer[512];
       fill_with_garbage(&pjaddr, sizeof(pj_sockaddr));
       if (!ast_sockaddr_parse(&addr, *candidate, 0)) {
          ast_test_status_update(test, "Failed to parse candidate IP: %s\n", *candidate);
          return AST_TEST_FAIL;
       }
       if (ast_sockaddr_to_pj_sockaddr(&addr, &pjaddr)) {
          ast_test_status_update(test, "Failed to convert ast_sockaddr to pj_sockaddr: %s\n", *candidate);
          return AST_TEST_FAIL;
       }
       pj_sockaddr_print(&pjaddr, buffer, sizeof(buffer), 1 | 2);
       if (strcmp(*candidate, buffer)) {
          ast_test_status_update(test, "Converted sockaddrs do not match: \"%s\" and \"%s\"\n",
             *candidate,
             buffer);
          return AST_TEST_FAIL;
       }
       candidate++;
    }
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [2/2]
AST_TEST_DEFINE (ast_sockaddr_from_pj_sockaddr_test)
Definition at line 596 of file res_pjproject.c.
References ast_sockaddr_from_pj_sockaddr(), ast_sockaddr_stringify(), AST_TEST_FAIL, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_test_status_update, fill_with_garbage(), sip_to_pjsip::info(), NULL, TEST_EXECUTE, and TEST_INIT.
 {
    char *candidates[] = {
       "127.0.0.1:5555",
       "[::]:4444",
       "192.168.0.100:0",
       "[fec0::1:80]:0",
       "[fec0::1]:80",
       NULL,
    }, **candidate = candidates;
    switch (cmd) {
    case TEST_INIT:
       info->name = "ast_sockaddr_from_pj_sockaddr_test";
       info->category = "/res/res_pjproject/";
       info->summary = "Validate conversions from a pj_sockaddr to an ast_sockaddr";
       info->description = "This test converts a pj_sockaddr to an ast_sockaddr and validates\n"
          "that the two evaluate to the same string when formatted.";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    while (*candidate) {
       struct ast_sockaddr addr = {{0,}};
       pj_sockaddr pjaddr;
       pj_str_t t;
       char buffer[512];
       fill_with_garbage(&addr, sizeof(addr));
       pj_strset(&t, *candidate, strlen(*candidate));
       if (pj_sockaddr_parse(pj_AF_UNSPEC(), 0, &t, &pjaddr) != PJ_SUCCESS) {
          ast_test_status_update(test, "Failed to parse candidate IP: %s\n", *candidate);
          return AST_TEST_FAIL;
       }
       if (ast_sockaddr_from_pj_sockaddr(&addr, &pjaddr)) {
          ast_test_status_update(test, "Failed to convert pj_sockaddr to ast_sockaddr: %s\n", *candidate);
          return AST_TEST_FAIL;
       }
       snprintf(buffer, sizeof(buffer), "%s", ast_sockaddr_stringify(&addr));
       if (strcmp(*candidate, buffer)) {
          ast_test_status_update(test, "Converted sockaddrs do not match: \"%s\" and \"%s\"\n",
             *candidate,
             buffer);
          return AST_TEST_FAIL;
       }
       candidate++;
    }
    return AST_TEST_PASS;
 }
AST_VECTOR()
static AST_VECTOR (buildopts, char *) static
Protection from other log intercept instances. There can be only one at a time.
Definition at line 121 of file res_pjproject.c.
{
capture_buildopts_cb()
static void capture_buildopts_cb (int level, const char * data, int len) static
Definition at line 231 of file res_pjproject.c.
References ast_free, ast_skip_blanks(), ast_strdup, and AST_VECTOR_ADD_SORTED.
Referenced by load_module().
 {
    char *dup;
    if (strstr(data, "Teluu") || strstr(data, "Dumping")) {
       return;
    }
    dup = ast_strdup(ast_skip_blanks(data));
    if (dup && AST_VECTOR_ADD_SORTED(&buildopts, dup, strcmp)) {
       ast_free(dup);
    }
 }
fill_with_garbage()
static void fill_with_garbage (void * x, ssize_t len) static
Definition at line 530 of file res_pjproject.c.
References ast_random().
Referenced by AST_TEST_DEFINE().
 {
    unsigned char *w = x;
    while (len > 0) {
       int r = ast_random();
       memcpy(w, &r, len > sizeof(r) ? sizeof(r) : len);
       w += sizeof(r);
       len -= sizeof(r);
    }
 }
get_log_level()
static int get_log_level (int pj_level) static
Definition at line 170 of file res_pjproject.c.
References __LOG_DEBUG, __LOG_ERROR, __LOG_NOTICE, __LOG_SUPPRESS, __LOG_VERBOSE, __LOG_WARNING, ao2_ref, log_mappings::asterisk_debug, log_mappings::asterisk_error, log_mappings::asterisk_notice, log_mappings::asterisk_verbose, log_mappings::asterisk_warning, get_log_mappings(), and mappings.
Referenced by log_forwarder().
 {
    int mapped_level;
    unsigned char l;
    struct log_mappings *mappings;
    mappings = get_log_mappings();
    if (!mappings) {
       return __LOG_ERROR;
    }
    l = '0' + fmin(pj_level, 9);
    if (strchr(mappings->asterisk_error, l)) {
       mapped_level = __LOG_ERROR;
    } else if (strchr(mappings->asterisk_warning, l)) {
       mapped_level = __LOG_WARNING;
    } else if (strchr(mappings->asterisk_notice, l)) {
       mapped_level = __LOG_NOTICE;
    } else if (strchr(mappings->asterisk_verbose, l)) {
       mapped_level = __LOG_VERBOSE;
    } else if (strchr(mappings->asterisk_debug, l)) {
       mapped_level = __LOG_DEBUG;
    } else {
       mapped_level = __LOG_SUPPRESS;
    }
    ao2_ref(mappings, -1);
    return mapped_level;
 }
get_log_mappings()
static struct log_mappings* get_log_mappings (void) static
Definition at line 156 of file res_pjproject.c.
References ao2_bump, ast_sorcery_retrieve_by_id(), and mappings.
Referenced by get_log_level(), and handle_pjproject_show_log_mappings().
 {
    struct log_mappings *mappings;
    mappings = ast_sorcery_retrieve_by_id(pjproject_sorcery, "log_mappings", "log_mappings");
    if (!mappings) {
       return ao2_bump(default_log_mappings);
    }
    return mappings;
 }
handle_pjproject_set_log_level()
static char* handle_pjproject_set_log_level (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) static
Definition at line 378 of file res_pjproject.c.
References ast_cli_args::argc, ast_cli_args::argv, ast_cli(), ast_option_pjproject_log_level, ast_pjproject_max_log_level, CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::command, DEFAULT_PJ_LOG_MAX_LEVEL, ast_cli_args::fd, MAX_PJ_LOG_MAX_LEVEL, NULL, and ast_cli_entry::usage.
 {
    int level_new;
    int level_old;
    switch (cmd) {
    case CLI_INIT:
       e->command = "pjproject set log level {default|0|1|2|3|4|5|6}";
       e->usage =
          "Usage: pjproject set log level {default|<level>}\n"
          "\n"
          "       Set the maximum active pjproject logging level.\n"
          "       See pjproject.conf.sample for additional information\n"
          "       about the various levels pjproject uses.\n";
       return NULL;
    case CLI_GENERATE:
       return NULL;
    }
    if (a->argc != 5) {
       return CLI_SHOWUSAGE;
    }
    if (!strcasecmp(a->argv[4], "default")) {
       level_new = DEFAULT_PJ_LOG_MAX_LEVEL;
    } else {
       if (sscanf(a->argv[4], "%30d", &level_new) != 1
          || level_new < 0 || MAX_PJ_LOG_MAX_LEVEL < level_new) {
          return CLI_SHOWUSAGE;
       }
    }
    /* Update pjproject logging level */
    if (ast_pjproject_max_log_level < level_new) {
       level_new = ast_pjproject_max_log_level;
       ast_cli(a->fd,
          "Asterisk built or linked with pjproject PJ_LOG_MAX_LEVEL=%d.\n"
          "Lowering request to the max supported level.\n",
          ast_pjproject_max_log_level);
    }
    level_old = ast_option_pjproject_log_level;
    if (level_old == level_new) {
       ast_cli(a->fd, "pjproject log level is still %d.\n", level_old);
    } else {
       ast_cli(a->fd, "pjproject log level was %d and is now %d.\n",
          level_old, level_new);
       ast_option_pjproject_log_level = level_new;
       pj_log_set_level(level_new);
    }
    return CLI_SUCCESS;
 }
handle_pjproject_show_buildopts()
static char* handle_pjproject_show_buildopts (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) static
Definition at line 286 of file res_pjproject.c.
References ast_cli(), AST_VECTOR_GET, AST_VECTOR_SIZE, CLI_GENERATE, CLI_INIT, CLI_SUCCESS, ast_cli_entry::command, ast_cli_args::fd, NULL, and ast_cli_entry::usage.
 {
    int i;
    switch (cmd) {
    case CLI_INIT:
       e->command = "pjproject show buildopts";
       e->usage =
          "Usage: pjproject show buildopts\n"
          "       Show the compile time config of the pjproject that Asterisk is\n"
          "       running against.\n";
       return NULL;
    case CLI_GENERATE:
       return NULL;
    }
    ast_cli(a->fd, "PJPROJECT compile time config currently running against:\n");
    for (i = 0; i < AST_VECTOR_SIZE(&buildopts); i++) {
       ast_cli(a->fd, "%s\n", AST_VECTOR_GET(&buildopts, i));
    }
    return CLI_SUCCESS;
 }
handle_pjproject_show_log_level()
static char* handle_pjproject_show_log_level (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) static
Definition at line 431 of file res_pjproject.c.
References ast_cli_args::argc, ast_cli(), ast_option_pjproject_log_level, CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::command, DEFAULT_PJ_LOG_MAX_LEVEL, ast_cli_args::fd, NULL, and ast_cli_entry::usage.
 {
    switch (cmd) {
    case CLI_INIT:
       e->command = "pjproject show log level";
       e->usage =
          "Usage: pjproject show log level\n"
          "\n"
          "       Show the current maximum active pjproject logging level.\n"
          "       See pjproject.conf.sample for additional information\n"
          "       about the various levels pjproject uses.\n";
       return NULL;
    case CLI_GENERATE:
       return NULL;
    }
    if (a->argc != 4) {
       return CLI_SHOWUSAGE;
    }
    ast_cli(a->fd, "pjproject log level is %d.%s\n",
       ast_option_pjproject_log_level,
       ast_option_pjproject_log_level == DEFAULT_PJ_LOG_MAX_LEVEL ? " (default)" : "");
    return CLI_SUCCESS;
 }
handle_pjproject_show_log_mappings()
static char* handle_pjproject_show_log_mappings (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) static
Definition at line 329 of file res_pjproject.c.
References ao2_ref, ast_cli(), ast_log, ast_sorcery_objectset_create, ast_variables_destroy(), CLI_GENERATE, CLI_INIT, CLI_SUCCESS, ast_cli_entry::command, ast_cli_args::fd, get_log_mappings(), LOG_ERROR, mappings, ast_variable::name, ast_variable::next, NULL, ast_cli_entry::usage, and ast_variable::value.
 {
    struct ast_variable *objset;
    struct ast_variable *i;
    struct log_mappings *mappings;
    switch (cmd) {
    case CLI_INIT:
       e->command = "pjproject show log mappings";
       e->usage =
          "Usage: pjproject show log mappings\n"
          "       Show pjproject to Asterisk log mappings\n";
       return NULL;
    case CLI_GENERATE:
       return NULL;
    }
    ast_cli(a->fd, "PJPROJECT to Asterisk log mappings:\n");
    ast_cli(a->fd, "Asterisk Level   : PJPROJECT log levels\n");
    mappings = get_log_mappings();
    if (!mappings) {
       ast_log(LOG_ERROR, "Unable to retrieve pjproject log_mappings\n");
       return CLI_SUCCESS;
    }
    objset = ast_sorcery_objectset_create(pjproject_sorcery, mappings);
    if (!objset) {
       ao2_ref(mappings, -1);
       return CLI_SUCCESS;
    }
    for (i = objset; i; i = i->next) {
       ast_cli(a->fd, "%-16s : %s\n", i->name, i->value);
    }
    ast_variables_destroy(objset);
    ao2_ref(mappings, -1);
    return CLI_SUCCESS;
 }
load_module()
static int load_module (void) static
Definition at line 655 of file res_pjproject.c.
References ARRAY_LEN, ast_cli_register_multiple, ast_debug, ast_log, AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, ast_option_pjproject_log_level, AST_PJPROJECT_INIT_LOG_LEVEL, ast_pjproject_max_log_level, ast_sorcery_alloc(), ast_sorcery_apply_default, ast_sorcery_load(), ast_sorcery_object_field_register, ast_sorcery_object_register, ast_sorcery_open, ast_sorcery_unref, ast_string_field_set, AST_TEST_REGISTER, AST_VECTOR_INIT, AST_VECTOR_SIZE, capture_buildopts_cb(), decor_orig, log_cb_orig, LOG_ERROR, log_forwarder(), LOG_NOTICE, LOG_WARNING, mapping_alloc(), MAX_PJ_LOG_MAX_LEVEL, NULL, OPT_NOOP_T, OPT_STRINGFIELD_T, and STRFLDSET.
Referenced by reload_module().
 {
    ast_debug(3, "Starting PJPROJECT logging to Asterisk logger\n");
    if (!(pjproject_sorcery = ast_sorcery_open())) {
       ast_log(LOG_ERROR, "Failed to open SIP sorcery failed to open\n");
       return AST_MODULE_LOAD_DECLINE;
    }
    ast_sorcery_apply_default(pjproject_sorcery, "log_mappings", "config", "pjproject.conf,criteria=type=log_mappings");
    if (ast_sorcery_object_register(pjproject_sorcery, "log_mappings", mapping_alloc, NULL, NULL)) {
       ast_log(LOG_WARNING, "Failed to register pjproject log_mappings object with sorcery\n");
       ast_sorcery_unref(pjproject_sorcery);
       pjproject_sorcery = NULL;
       return AST_MODULE_LOAD_DECLINE;
    }
    ast_sorcery_object_field_register(pjproject_sorcery, "log_mappings", "type", "", OPT_NOOP_T, 0, 0);
    ast_sorcery_object_field_register(pjproject_sorcery, "log_mappings", "asterisk_debug", "", OPT_STRINGFIELD_T, 0, STRFLDSET(struct log_mappings, asterisk_debug));
    ast_sorcery_object_field_register(pjproject_sorcery, "log_mappings", "asterisk_error", "",  OPT_STRINGFIELD_T, 0, STRFLDSET(struct log_mappings, asterisk_error));
    ast_sorcery_object_field_register(pjproject_sorcery, "log_mappings", "asterisk_warning", "",  OPT_STRINGFIELD_T, 0, STRFLDSET(struct log_mappings, asterisk_warning));
    ast_sorcery_object_field_register(pjproject_sorcery, "log_mappings", "asterisk_notice", "",  OPT_STRINGFIELD_T, 0, STRFLDSET(struct log_mappings, asterisk_notice));
    ast_sorcery_object_field_register(pjproject_sorcery, "log_mappings", "asterisk_verbose", "",  OPT_STRINGFIELD_T, 0, STRFLDSET(struct log_mappings, asterisk_verbose));
    default_log_mappings = ast_sorcery_alloc(pjproject_sorcery, "log_mappings", "log_mappings");
    if (!default_log_mappings) {
       ast_log(LOG_ERROR, "Unable to allocate memory for pjproject log_mappings\n");
       return AST_MODULE_LOAD_DECLINE;
    }
    ast_string_field_set(default_log_mappings, asterisk_error, "0,1");
    ast_string_field_set(default_log_mappings, asterisk_warning, "2");
    ast_string_field_set(default_log_mappings, asterisk_debug, "3,4,5,6");
    ast_sorcery_load(pjproject_sorcery);
    AST_PJPROJECT_INIT_LOG_LEVEL();
    pj_init();
    decor_orig = pj_log_get_decor();
    log_cb_orig = pj_log_get_log_func();
    if (AST_VECTOR_INIT(&buildopts, 64)) {
       return AST_MODULE_LOAD_DECLINE;
    }
    /*
     * On startup, we want to capture the dump once and store it.
     */
    pj_log_set_log_func(capture_buildopts_cb);
    pj_log_set_decor(0);
    pj_log_set_level(MAX_PJ_LOG_MAX_LEVEL);/* Set level to guarantee the dump output. */
    pj_dump_config();
    pj_log_set_decor(PJ_LOG_HAS_SENDER | PJ_LOG_HAS_INDENT);
    pj_log_set_log_func(log_forwarder);
    if (ast_pjproject_max_log_level < ast_option_pjproject_log_level) {
       ast_log(LOG_WARNING,
          "Asterisk built or linked with pjproject PJ_LOG_MAX_LEVEL=%d which is too low for startup level: %d.\n",
          ast_pjproject_max_log_level, ast_option_pjproject_log_level);
       ast_option_pjproject_log_level = ast_pjproject_max_log_level;
    }
    pj_log_set_level(ast_option_pjproject_log_level);
    if (!AST_VECTOR_SIZE(&buildopts)) {
       ast_log(LOG_NOTICE,
          "Asterisk built or linked with pjproject PJ_LOG_MAX_LEVEL=%d which is too low to get buildopts.\n",
          ast_pjproject_max_log_level);
    }
    ast_cli_register_multiple(pjproject_cli, ARRAY_LEN(pjproject_cli));
    AST_TEST_REGISTER(ast_sockaddr_to_pj_sockaddr_test);
    AST_TEST_REGISTER(ast_sockaddr_from_pj_sockaddr_test);
    return AST_MODULE_LOAD_SUCCESS;
 }
log_forwarder()
static void log_forwarder (int level, const char * data, int len) static
Definition at line 201 of file res_pjproject.c.
References __LOG_SUPPRESS, ast_cli(), ast_log, pjproject_log_intercept_data::fd, get_log_level(), and pjproject_log_intercept_data::thread.
Referenced by load_module().
 {
    int ast_level;
    /* PJPROJECT doesn't provide much in the way of source info */
    const char * log_source = "pjproject";
    int log_line = 0;
    const char *log_func = "<?>";
    if (pjproject_log_intercept.fd != -1
       && pjproject_log_intercept.thread == pthread_self()) {
       /*
        * We are handling a CLI command intercepting PJPROJECT
        * log output.
        */
       ast_cli(pjproject_log_intercept.fd, "%s\n", data);
       return;
    }
    ast_level = get_log_level(level);
    if (ast_level == __LOG_SUPPRESS) {
       return;
    }
    /* PJPROJECT uses indention to indicate function call depth. We'll prepend
     * log statements with a tab so they'll have a better shot at lining
     * up */
    ast_log(ast_level, log_source, log_line, log_func, "\t%s\n", data);
 }
mapping_alloc()
static void* mapping_alloc (const char * name) static
Definition at line 318 of file res_pjproject.c.
References ast_sorcery_generic_alloc(), ast_string_field_init, mapping_destroy(), mappings, and NULL.
Referenced by load_module().
 {
    struct log_mappings *mappings = ast_sorcery_generic_alloc(sizeof(*mappings), mapping_destroy);
    if (!mappings) {
       return NULL;
    }
    ast_string_field_init(mappings, 128);
    return mappings;
 }
mapping_destroy()
static void mapping_destroy (void * object) static
Definition at line 311 of file res_pjproject.c.
References ast_string_field_free_memory.
Referenced by mapping_alloc().
 {
    struct log_mappings *mappings = object;
    ast_string_field_free_memory(mappings);
 }
reload_module()
static int reload_module (void) static
Definition at line 756 of file res_pjproject.c.
References AST_MODFLAG_GLOBAL_SYMBOLS, AST_MODFLAG_LOAD_ORDER, AST_MODPRI_CHANNEL_DEPEND, AST_MODULE_INFO(), AST_MODULE_LOAD_SUCCESS, AST_MODULE_SUPPORT_CORE, ast_sorcery_reload(), ASTERISK_GPL_KEY, load_module(), reload(), and unload_module().
 {
    if (pjproject_sorcery) {
       ast_sorcery_reload(pjproject_sorcery);
    }
    return AST_MODULE_LOAD_SUCCESS;
 }
unload_module()
static int unload_module (void) static
Definition at line 732 of file res_pjproject.c.
References ao2_cleanup, ARRAY_LEN, ast_cli_unregister_multiple(), ast_debug, ast_free, ast_sorcery_unref, AST_TEST_UNREGISTER, AST_VECTOR_CALLBACK_VOID, AST_VECTOR_FREE, decor_orig, log_cb_orig, and NULL.
Referenced by reload_module().
 {
    ast_cli_unregister_multiple(pjproject_cli, ARRAY_LEN(pjproject_cli));
    pj_log_set_log_func(log_cb_orig);
    pj_log_set_decor(decor_orig);
    AST_VECTOR_CALLBACK_VOID(&buildopts, ast_free);
    AST_VECTOR_FREE(&buildopts);
    ast_debug(3, "Stopped PJPROJECT logging to Asterisk logger\n");
    pj_shutdown();
    ao2_cleanup(default_log_mappings);
    default_log_mappings = NULL;
    ast_sorcery_unref(pjproject_sorcery);
    AST_TEST_UNREGISTER(ast_sockaddr_to_pj_sockaddr_test);
    AST_TEST_UNREGISTER(ast_sockaddr_from_pj_sockaddr_test);
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_GLOBAL_SYMBOLS | AST_MODFLAG_LOAD_ORDER , .description = "PJPROJECT Log and Utility Support" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .reload = reload_module, .load_pri = AST_MODPRI_CHANNEL_DEPEND - 6, .requires = "res_sorcery_config", } static
Definition at line 772 of file res_pjproject.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 772 of file res_pjproject.c.
decor_orig
unsigned decor_orig static
Definition at line 119 of file res_pjproject.c.
Referenced by load_module(), and unload_module().
default_log_mappings
struct log_mappings* default_log_mappings static
Definition at line 154 of file res_pjproject.c.
log_cb_orig
pj_log_func* log_cb_orig static
Definition at line 118 of file res_pjproject.c.
Referenced by load_module(), and unload_module().
pjproject_cli
struct ast_cli_entry pjproject_cli[] static
Definition at line 458 of file res_pjproject.c.
pjproject_log_intercept
struct pjproject_log_intercept_data pjproject_log_intercept static
Initial value:
= {
   .thread = AST_PTHREADT_NULL,
   .fd = -1,
}
Definition at line 131 of file res_pjproject.c.
pjproject_sorcery
struct ast_sorcery* pjproject_sorcery static
Definition at line 117 of file res_pjproject.c.