Asterisk - The Open Source Telephony Project: ulaw.c File Reference
ulaw.c File Reference
u-Law to Signed linear conversion
#include "asterisk.h"
#include "asterisk/ulaw.h"
#include "asterisk/logger.h"
Macros
#define BIAS 0x84
#define CLIP 32635
Functions
void ast_ulaw_init (void)
Set up mu-law conversion table.
static unsigned char linear2ulaw (short sample)
Variables
unsigned char __ast_lin2mu [16384]
converts signed linear to mulaw
short __ast_mulaw [256]
Detailed Description
u-Law to Signed linear conversion
Author
Mark Spencer marks.nosp@m.ter@.nosp@m.digiu.nosp@m.m.co.nosp@m.m
Definition in file ulaw.c.
Macro Definition Documentation
BIAS
#define BIAS 0x84
define the add-in bias for 16 bit samples
Definition at line 44 of file ulaw.c.
Referenced by linear2ulaw().
CLIP
#define CLIP 32635
Definition at line 45 of file ulaw.c.
Referenced by linear2ulaw().
Function Documentation
ast_ulaw_init()
void ast_ulaw_init (void)
Set up mu-law conversion table.
To init the ulaw to slinear conversion stuff, this needs to be run.
Definition at line 173 of file ulaw.c.
References __ast_lin2mu, __ast_mulaw, AST_LIN2MU, ast_log, AST_MULAW, AST_ULAW_STEP, ast_udptl::f, linear2ulaw(), LOG_NOTICE, and LOG_WARNING.
Referenced by asterisk_daemon().
 {
    int i;
    /*
     *  Set up mu-law conversion table
     */
 #ifndef G711_NEW_ALGORITHM
    for (i = 0;i < 256;i++) {
       short mu,e,f,y;
       static const short etab[]={0,132,396,924,1980,4092,8316,16764};
       mu = 255-i;
       e = (mu & 0x70)/16;
       f = mu & 0x0f;
       y = f * (1 << (e + 3));
       y += etab[e];
       if (mu & 0x80) y = -y;
       __ast_mulaw[i] = y;
    }
    /* set up the reverse (mu-law) conversion table */
    for (i = -32768; i < 32768; i++) {
       __ast_lin2mu[((unsigned short)i) >> 2] = linear2ulaw(i);
    }
 #else
    for (i = 0; i < 256; i++) {
       __ast_mulaw[i] = ulaw2linear(i);
    }
    /* set up the reverse (mu-law) conversion table */
    for (i = 0; i <= 32768; i += AST_ULAW_STEP) {
       AST_LIN2MU_LOOKUP(i) = linear2ulaw(i, 0 /* half-cooked */);
    }
 #endif
 #ifdef TEST_CODING_TABLES
    for (i = -32768; i < 32768; ++i) {
 #ifndef G711_NEW_ALGORITHM
       unsigned char e1 = linear2ulaw(i);
 #else
       unsigned char e1 = linear2ulaw(i, 1);
 #endif
       short d1 = ulaw2linear(e1);
       unsigned char e2 = AST_LIN2MU(i);
       short d2 = ulaw2linear(e2);
       short d3 = AST_MULAW(e1);
       if (e1 != e2 || d1 != d3 || d2 != d3) {
          ast_log(LOG_WARNING, "u-Law coding tables test failed on %d: e1=%u, e2=%u, d1=%d, d2=%d\n",
                i, (unsigned)e1, (unsigned)e2, (int)d1, (int)d2);
       }
    }
    ast_log(LOG_NOTICE, "u-Law coding table test complete.\n");
 #endif /* TEST_CODING_TABLES */
 #ifdef TEST_TANDEM_TRANSCODING
    /* tandem transcoding test */
    for (i = -32768; i < 32768; ++i) {
       unsigned char e1 = AST_LIN2MU(i);
       short d1 = AST_MULAW(e1);
       unsigned char e2 = AST_LIN2MU(d1);
       short d2 = AST_MULAW(e2);
       unsigned char e3 = AST_LIN2MU(d2);
       short d3 = AST_MULAW(e3);
       if (i < 0 && e1 == 0x7f && e2 == 0xff && e3 == 0xff)
          continue; /* known and normal negative 0 case */
       if (e1 != e2 || e2 != e3 || d1 != d2 || d2 != d3) {
          ast_log(LOG_WARNING, "u-Law tandem transcoding test failed on %d: e1=%u, e2=%u, d1=%d, d2=%d, d3=%d\n",
                i, (unsigned)e1, (unsigned)e2, (int)d1, (int)d2, (int)d3);
       }
    }
    ast_log(LOG_NOTICE, "u-Law tandem transcoding test complete.\n");
 #endif /* TEST_TANDEM_TRANSCODING */
 }
linear2ulaw()
static unsigned char linear2ulaw (short sample) static
Definition at line 52 of file ulaw.c.
References __ast_lin2mu, __ast_mulaw, AST_ULAW_TAB_SIZE, BIAS, and CLIP.
Referenced by ast_ulaw_init().
 {
    static int exp_lut[256] = {
       0,0,1,1,2,2,2,2,3,3,3,3,3,3,3,3,
       4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,
       5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,
       5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,
       6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,
       6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,
       6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,
       6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,
       7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,
       7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,
       7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,
       7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,
       7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,
       7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,
       7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,
       7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7 };
    int sign, exponent, mantissa;
    unsigned char ulawbyte;
    /* Get the sample into sign-magnitude. */
    sign = (sample >> 8) & 0x80;          /* set aside the sign */
    if (sign != 0)
       sample = -sample;              /* get magnitude */
    if (sample > CLIP)
       sample = CLIP;             /* clip the magnitude */
    /* Convert from 16 bit linear to ulaw. */
    sample = sample + BIAS;
    exponent = exp_lut[(sample >> 7) & 0xFF];
    mantissa = (sample >> (exponent + 3)) & 0x0F;
    ulawbyte = ~(sign | (exponent << 4) | mantissa);
 #ifdef ZEROTRAP
    if (ulawbyte == 0)
       ulawbyte = 0x02;   /* optional CCITT trap */
 #endif
    return ulawbyte;
 }
Variable Documentation
__ast_lin2mu
unsigned char __ast_lin2mu[16384]
converts signed linear to mulaw
Definition at line 49 of file ulaw.c.
Referenced by ast_ulaw_init(), and linear2ulaw().
__ast_mulaw
short __ast_mulaw[256]
help
Definition at line 50 of file ulaw.c.
Referenced by ast_ulaw_init(), and linear2ulaw().