Asterisk - The Open Source Telephony Project: cel.h File Reference
cel.h File Reference
Call Event Logging API.
#include "asterisk/event.h"
Data Structures
struct ast_cel_event_record
Helper struct for getting the fields out of a CEL event.
struct ast_cel_general_config
A structure to hold CEL global configuration options.
Macros
#define AST_CEL_EVENT_RECORD_VERSION 2
struct ABI version
Typedefs
typedef void(* ast_cel_backend_cb) (struct ast_event *event)
CEL backend callback.
Enumerations
enum ast_cel_event_type {
AST_CEL_INVALID_VALUE = -1, AST_CEL_ALL = 0, AST_CEL_CHANNEL_START = 1, AST_CEL_CHANNEL_END = 2,
AST_CEL_HANGUP = 3, AST_CEL_ANSWER = 4, AST_CEL_APP_START = 5, AST_CEL_APP_END = 6,
AST_CEL_BRIDGE_ENTER = 7, AST_CEL_BRIDGE_EXIT = 8, AST_CEL_PARK_START = 9, AST_CEL_PARK_END = 10,
AST_CEL_BLINDTRANSFER = 11, AST_CEL_ATTENDEDTRANSFER = 12, AST_CEL_USER_DEFINED = 13, AST_CEL_LINKEDID_END = 14,
AST_CEL_PICKUP = 15, AST_CEL_FORWARD = 16, AST_CEL_LOCAL_OPTIMIZE = 17
}
CEL event types.
Functions
int ast_cel_backend_register (const char *name, ast_cel_backend_cb backend_callback)
Register a CEL backend.
int ast_cel_backend_unregister (const char *name)
Unregister a CEL backend.
unsigned int ast_cel_check_enabled (void)
Check to see if CEL is enabled.
struct ast_event * ast_cel_create_event (struct ast_channel_snapshot *snapshot, enum ast_cel_event_type event_type, const char *userdefevname, struct ast_json *extra, const char *peer_str)
Allocate and populate a CEL event structure.
struct ast_event * ast_cel_create_event_with_time (struct ast_channel_snapshot *snapshot, enum ast_cel_event_type event_type, const struct timeval *event_time, const char *userdefevname, struct ast_json *extra, const char *peer_str)
Allocate and populate a CEL event structure.
struct ast_channel * ast_cel_fabricate_channel_from_event (const struct ast_event *event)
Create a fake channel from data in a CEL event.
int ast_cel_fill_record (const struct ast_event *event, struct ast_cel_event_record *r)
Fill in an ast_cel_event_record from a CEL event.
void * ast_cel_general_config_alloc (void)
Allocate a CEL configuration object.
struct ast_cel_general_config * ast_cel_get_config (void)
Obtain the current CEL configuration.
const char * ast_cel_get_type_name (enum ast_cel_event_type type)
Get the name of a CEL event type.
void ast_cel_publish_event (struct ast_channel *chan, enum ast_cel_event_type event_type, struct ast_json *blob)
Publish a CEL event.
void ast_cel_set_config (struct ast_cel_general_config *config)
Set the current CEL configuration.
enum ast_cel_event_type ast_cel_str_to_event_type (const char *name)
Get the event type from a string.
struct stasis_topic * ast_cel_topic (void)
Get the CEL topic.
Detailed Description
Call Event Logging API.
Todo:
TODO: There some event types that have been defined here, but are not yet used anywhere in the code. It would be really awesome if someone went through and had Asterisk generate these events where it is appropriate to do so. The defined, but unused events are: CONF_ENTER, CONF_EXIT, CONF_START, CONF_END, 3WAY_START, 3WAY_END, TRANSFER, and HOOKFLASH.
Definition in file cel.h.
Macro Definition Documentation
AST_CEL_EVENT_RECORD_VERSION
#define AST_CEL_EVENT_RECORD_VERSION 2
struct ABI version
Note
This must be incremented when the struct changes.
Definition at line 141 of file cel.h.
Referenced by ast_cel_fabricate_channel_from_event(), ast_cel_fill_record(), cel_bs_put(), manager_log(), odbc_log(), pgsql_log(), radius_log(), and tds_log().
Typedef Documentation
ast_cel_backend_cb
typedef void(* ast_cel_backend_cb) (struct ast_event *event)
CEL backend callback.
Definition at line 292 of file cel.h.
Enumeration Type Documentation
ast_cel_event_type
enum ast_cel_event_type
CEL event types.
Enumerator
AST_CEL_INVALID_VALUE
AST_CEL_ALL
AST_CEL_CHANNEL_START
channel birth
AST_CEL_CHANNEL_END
channel end
AST_CEL_HANGUP
hangup terminates connection
AST_CEL_ANSWER
A ringing phone is answered.
AST_CEL_APP_START
an app starts
AST_CEL_APP_END
an app ends
AST_CEL_BRIDGE_ENTER
channel enters a bridge
AST_CEL_BRIDGE_EXIT
channel exits a bridge
AST_CEL_PARK_START
a channel is parked
AST_CEL_PARK_END
channel out of the park
AST_CEL_BLINDTRANSFER
a transfer occurs
AST_CEL_ATTENDEDTRANSFER
a transfer occurs
AST_CEL_USER_DEFINED
a user-defined event, the event name field should be set
AST_CEL_LINKEDID_END
the last channel with the given linkedid is retired
AST_CEL_PICKUP
a directed pickup was performed on this channel
AST_CEL_FORWARD
this call was forwarded somewhere else
AST_CEL_LOCAL_OPTIMIZE
A local channel optimization occurred.
Definition at line 41 of file cel.h.
{
    AST_CEL_INVALID_VALUE = -1,
    AST_CEL_ALL = 0,
    /*! \brief channel birth */
    AST_CEL_CHANNEL_START = 1,
    /*! \brief channel end */
    AST_CEL_CHANNEL_END = 2,
    /*! \brief hangup terminates connection */
    AST_CEL_HANGUP = 3,
    /*! \brief A ringing phone is answered */
    AST_CEL_ANSWER = 4,
    /*! \brief an app starts */
    AST_CEL_APP_START = 5,
    /*! \brief an app ends */
    AST_CEL_APP_END = 6,
    /*! \brief channel enters a bridge */
    AST_CEL_BRIDGE_ENTER = 7,
    /*! \brief channel exits a bridge */
    AST_CEL_BRIDGE_EXIT = 8,
    /*! \brief a channel is parked */
    AST_CEL_PARK_START = 9,
    /*! \brief channel out of the park */
    AST_CEL_PARK_END = 10,
    /*! \brief a transfer occurs */
    AST_CEL_BLINDTRANSFER = 11,
    /*! \brief a transfer occurs */
    AST_CEL_ATTENDEDTRANSFER = 12,
    /*! \brief a user-defined event, the event name field should be set  */
    AST_CEL_USER_DEFINED = 13,
    /*! \brief the last channel with the given linkedid is retired  */
    AST_CEL_LINKEDID_END = 14,
    /*! \brief a directed pickup was performed on this channel  */
    AST_CEL_PICKUP = 15,
    /*! \brief this call was forwarded somewhere else  */
    AST_CEL_FORWARD = 16,
    /*! \brief A local channel optimization occurred */
    AST_CEL_LOCAL_OPTIMIZE = 17,
 };
Function Documentation
ast_cel_backend_register()
int ast_cel_backend_register (const char * name, ast_cel_backend_cb backend_callback)
Register a CEL backend.
Parameters
name Name of backend to register
backend_callback Callback to register
Return values
zero on success
non-zero on failure
Since
12
Definition at line 1740 of file cel.c.
References AO2_ALLOC_OPT_LOCK_NOLOCK, ao2_alloc_options, ao2_cleanup, ao2_global_obj_ref, ao2_link, ao2_ref, AST_MODFLAG_GLOBAL_SYMBOLS, AST_MODFLAG_LOAD_ORDER, AST_MODPRI_CORE, AST_MODULE_INFO(), AST_MODULE_SUPPORT_CORE, ast_strlen_zero, ASTERISK_GPL_KEY, cel_backend::callback, load_module(), cel_backend::name, NULL, RAII_VAR, reload(), reload_module(), and unload_module().
Referenced by load_config(), load_module(), my_load_module(), and test_cel_init_cb().
 {
    RAII_VAR(struct ao2_container *, backends, ao2_global_obj_ref(cel_backends), ao2_cleanup);
    struct cel_backend *backend;
    if (!backends || ast_strlen_zero(name) || !backend_callback) {
       return -1;
    }
    /* The backend object is immutable so it doesn't need a lock of its own. */
    backend = ao2_alloc_options(sizeof(*backend) + 1 + strlen(name), NULL,
       AO2_ALLOC_OPT_LOCK_NOLOCK);
    if (!backend) {
       return -1;
    }
    strcpy(backend->name, name);/* Safe */
    backend->callback = backend_callback;
    ao2_link(backends, backend);
    ao2_ref(backend, -1);
    return 0;
 }
ast_cel_backend_unregister()
int ast_cel_backend_unregister (const char * name)
Unregister a CEL backend.
Parameters
name Name of backend to unregister
Return values
zero on success
non-zero on failure
Since
12
Definition at line 1728 of file cel.c.
References ao2_find, ao2_global_obj_ref, ao2_ref, OBJ_NODATA, OBJ_SEARCH_KEY, and OBJ_UNLINK.
Referenced by cel_verify_and_cleanup_cb(), load_config(), my_unload_module(), tds_unload_module(), and unload_module().
 {
    struct ao2_container *backends = ao2_global_obj_ref(cel_backends);
    if (backends) {
       ao2_find(backends, name, OBJ_SEARCH_KEY | OBJ_NODATA | OBJ_UNLINK);
       ao2_ref(backends, -1);
    }
    return 0;
 }
ast_cel_check_enabled()
unsigned int ast_cel_check_enabled (void)
Check to see if CEL is enabled.
Since
1.8
Return values
zero not enabled
non-zero enabled
Check to see if CEL is enabled.
Comparator function for cel_backend
Hashing function for dialstatus container
Comparator function for dialstatus container
Definition at line 343 of file cel.c.
References ao2_cleanup, ao2_global_obj_ref, ast_cel_general_config::enable, enabled, and cel_config::general.
Referenced by ast_cel_set_config(), handle_cli_status(), load_module(), and reload_module().
 {
    unsigned int enabled;
    struct cel_config *cfg = ao2_global_obj_ref(cel_configs);
    enabled = (!cfg || !cfg->general) ? 0 : cfg->general->enable;
    ao2_cleanup(cfg);
    return enabled;
 }
ast_cel_create_event()
struct ast_event* ast_cel_create_event (struct ast_channel_snapshot * snapshot, enum ast_cel_event_type event_type, const char * userdefevname, struct ast_json * extra, const char * peer_str)
Allocate and populate a CEL event structure.
Parameters
snapshot An ast_channel_snapshot of the primary channel associated with this channel event.
event_type The type of call event being reported.
userdefevname Custom name for the call event. (optional)
extra An event-specific opaque JSON blob to be rendered and placed in the "CEL_EXTRA" information element of the call event. (optional)
peer_str A list of comma-separated peer channel names. (optional)
Since
12
Return values
The created ast_event structure
NULL on failure
Definition at line 517 of file cel.c.
References ast_cel_create_event_with_time(), and ast_tvnow().
Referenced by append_expected_event_snapshot().
 {
    struct timeval eventtime = ast_tvnow();
    return ast_cel_create_event_with_time(snapshot, event_type, &eventtime,
       userdefevname, extra, peer);
 }
ast_cel_create_event_with_time()
struct ast_event* ast_cel_create_event_with_time (struct ast_channel_snapshot * snapshot, enum ast_cel_event_type event_type, const struct timeval * event_time, const char * userdefevname, struct ast_json * extra, const char * peer_str)
Allocate and populate a CEL event structure.
Parameters
snapshot An ast_channel_snapshot of the primary channel associated with this channel event.
event_type The type of call event being reported.
event_time The time at which the event occurred.
userdefevname Custom name for the call event. (optional)
extra An event-specific opaque JSON blob to be rendered and placed in the "CEL_EXTRA" information element of the call event. (optional)
peer_str A list of comma-separated peer channel names. (optional)
Since
13.29.0
16.6.0
Return values
The created ast_event structure
NULL on failure
Definition at line 527 of file cel.c.
References ast_channel_snapshot_peer::account, ast_channel_snapshot_base::accountcode, ast_channel_snapshot::amaflags, ast_channel_snapshot_caller::ani, ast_channel_snapshot_dialplan::appl, AST_EVENT_CEL, AST_EVENT_IE_CEL_ACCTCODE, AST_EVENT_IE_CEL_AMAFLAGS, AST_EVENT_IE_CEL_APPDATA, AST_EVENT_IE_CEL_APPNAME, AST_EVENT_IE_CEL_CHANNAME, AST_EVENT_IE_CEL_CIDANI, AST_EVENT_IE_CEL_CIDDNID, AST_EVENT_IE_CEL_CIDNAME, AST_EVENT_IE_CEL_CIDNUM, AST_EVENT_IE_CEL_CIDRDNIS, AST_EVENT_IE_CEL_CONTEXT, AST_EVENT_IE_CEL_EVENT_TIME, AST_EVENT_IE_CEL_EVENT_TIME_USEC, AST_EVENT_IE_CEL_EVENT_TYPE, AST_EVENT_IE_CEL_EXTEN, AST_EVENT_IE_CEL_EXTRA, AST_EVENT_IE_CEL_LINKEDID, AST_EVENT_IE_CEL_PEER, AST_EVENT_IE_CEL_PEERACCT, AST_EVENT_IE_CEL_UNIQUEID, AST_EVENT_IE_CEL_USEREVENT_NAME, AST_EVENT_IE_CEL_USERFIELD, AST_EVENT_IE_END, AST_EVENT_IE_PLTYPE_STR, AST_EVENT_IE_PLTYPE_UINT, ast_event_new(), ast_json_dump_string, ast_json_free(), ast_channel_snapshot::base, ast_channel_snapshot::caller, ast_channel_snapshot_dialplan::context, ast_channel_snapshot_dialplan::data, ast_channel_snapshot::dialplan, ast_channel_snapshot_caller::dnid, ast_channel_snapshot_dialplan::exten, ast_channel_snapshot_peer::linkedid, ast_channel_snapshot_caller::name, ast_channel_snapshot_base::name, NULL, ast_channel_snapshot_caller::number, ast_channel_snapshot::peer, RAII_VAR, ast_channel_snapshot_caller::rdnis, S_OR, ast_channel_snapshot_base::uniqueid, and ast_channel_snapshot_base::userfield.
Referenced by ast_cel_create_event(), and cel_report_event().
 {
    RAII_VAR(char *, extra_txt, NULL, ast_json_free);
    if (extra) {
       extra_txt = ast_json_dump_string(extra);
    }
    return ast_event_new(AST_EVENT_CEL,
       AST_EVENT_IE_CEL_EVENT_TYPE, AST_EVENT_IE_PLTYPE_UINT, event_type,
       AST_EVENT_IE_CEL_EVENT_TIME, AST_EVENT_IE_PLTYPE_UINT, event_time->tv_sec,
       AST_EVENT_IE_CEL_EVENT_TIME_USEC, AST_EVENT_IE_PLTYPE_UINT, event_time->tv_usec,
       AST_EVENT_IE_CEL_USEREVENT_NAME, AST_EVENT_IE_PLTYPE_STR, S_OR(userdefevname, ""),
       AST_EVENT_IE_CEL_CIDNAME, AST_EVENT_IE_PLTYPE_STR, snapshot->caller->name,
       AST_EVENT_IE_CEL_CIDNUM, AST_EVENT_IE_PLTYPE_STR, snapshot->caller->number,
       AST_EVENT_IE_CEL_CIDANI, AST_EVENT_IE_PLTYPE_STR, snapshot->caller->ani,
       AST_EVENT_IE_CEL_CIDRDNIS, AST_EVENT_IE_PLTYPE_STR, snapshot->caller->rdnis,
       AST_EVENT_IE_CEL_CIDDNID, AST_EVENT_IE_PLTYPE_STR, snapshot->caller->dnid,
       AST_EVENT_IE_CEL_EXTEN, AST_EVENT_IE_PLTYPE_STR, snapshot->dialplan->exten,
       AST_EVENT_IE_CEL_CONTEXT, AST_EVENT_IE_PLTYPE_STR, snapshot->dialplan->context,
       AST_EVENT_IE_CEL_CHANNAME, AST_EVENT_IE_PLTYPE_STR, snapshot->base->name,
       AST_EVENT_IE_CEL_APPNAME, AST_EVENT_IE_PLTYPE_STR, snapshot->dialplan->appl,
       AST_EVENT_IE_CEL_APPDATA, AST_EVENT_IE_PLTYPE_STR, snapshot->dialplan->data,
       AST_EVENT_IE_CEL_AMAFLAGS, AST_EVENT_IE_PLTYPE_UINT, snapshot->amaflags,
       AST_EVENT_IE_CEL_ACCTCODE, AST_EVENT_IE_PLTYPE_STR, snapshot->base->accountcode,
       AST_EVENT_IE_CEL_PEERACCT, AST_EVENT_IE_PLTYPE_STR, snapshot->peer->account,
       AST_EVENT_IE_CEL_UNIQUEID, AST_EVENT_IE_PLTYPE_STR, snapshot->base->uniqueid,
       AST_EVENT_IE_CEL_LINKEDID, AST_EVENT_IE_PLTYPE_STR, snapshot->peer->linkedid,
       AST_EVENT_IE_CEL_USERFIELD, AST_EVENT_IE_PLTYPE_STR, snapshot->base->userfield,
       AST_EVENT_IE_CEL_EXTRA, AST_EVENT_IE_PLTYPE_STR, S_OR(extra_txt, ""),
       AST_EVENT_IE_CEL_PEER, AST_EVENT_IE_PLTYPE_STR, S_OR(peer, ""),
       AST_EVENT_IE_END);
 }
ast_cel_fabricate_channel_from_event()
struct ast_channel* ast_cel_fabricate_channel_from_event (const struct ast_event * event)
Create a fake channel from data in a CEL event.
Note
This function creates a fake channel containing the serialized channel data in the given cel event. It should be released with ast_channel_unref() but could be released with ast_channel_release().
Parameters
event the CEL event
Since
1.8
Returns
a channel with the data filled in, or NULL on error
Todo:
This function is very expensive, especially given that some CEL backends use it on every CEL event. This function really needs to go away at some point.
Definition at line 660 of file cel.c.
References ast_cel_event_record::account_code, ast_cel_event_record::amaflag, ast_party_caller::ani, ao2_cleanup, ao2_global_obj_ref, ast_cel_event_record::application_data, ast_cel_event_record::application_name, AST_CEL_EVENT_RECORD_VERSION, ast_cel_fill_record(), AST_CEL_USER_DEFINED, ast_channel_amaflags_set(), ast_channel_appl_set(), ast_channel_caller(), ast_channel_context_set(), ast_channel_data_set(), ast_channel_datastore_add(), ast_channel_dialed(), ast_channel_exten_set(), ast_channel_internal_set_fake_ids(), ast_channel_name_set(), ast_channel_redirecting(), ast_channel_unref, ast_channel_varshead(), ast_datastore_alloc, ast_datastore_free(), ast_dummy_channel_alloc, AST_LIST_INSERT_HEAD, ast_localtime(), ast_malloc, ast_strdup, ast_strftime(), ast_strlen_zero, ast_var_assign, ast_cel_event_record::caller_id_ani, ast_cel_event_record::caller_id_dnid, ast_cel_event_record::caller_id_name, ast_cel_event_record::caller_id_num, ast_cel_event_record::caller_id_rdnis, ast_cel_event_record::channel_name, ast_cel_event_record::context, ast_datastore::data, ast_cel_event_record::event_name, ast_cel_event_record::event_time, ast_cel_event_record::event_type, ast_cel_event_record::extension, ast_cel_event_record::extra, ast_party_redirecting::from, ast_party_caller::id, if(), ast_cel_event_record::linked_id, ast_party_id::name, NULL, ast_party_id::number, ast_party_dialed::number, ast_cel_event_record::peer, ast_cel_event_record::peer_account, RAII_VAR, ast_party_name::str, ast_party_number::str, ast_party_dialed::str, ast_cel_event_record::unique_id, ast_cel_event_record::user_defined_name, ast_cel_event_record::user_field, ast_party_name::valid, ast_party_number::valid, and ast_cel_event_record::version.
Referenced by custom_log(), and write_cel().
 {
    struct varshead *headp;
    struct ast_var_t *newvariable;
    const char *mixed_name;
    char timebuf[30];
    struct ast_channel *tchan;
    struct ast_cel_event_record record = {
       .version = AST_CEL_EVENT_RECORD_VERSION,
    };
    struct ast_datastore *datastore;
    char *app_data;
    RAII_VAR(struct cel_config *, cfg, ao2_global_obj_ref(cel_configs), ao2_cleanup);
    if (!cfg || !cfg->general) {
       return NULL;
    }
    /* do not call ast_channel_alloc because this is not really a real channel */
    if (!(tchan = ast_dummy_channel_alloc())) {
       return NULL;
    }
    headp = ast_channel_varshead(tchan);
    /* first, get the variables from the event */
    if (ast_cel_fill_record(event, &record)) {
       ast_channel_unref(tchan);
       return NULL;
    }
    /* next, fill the channel with their data */
    mixed_name = (record.event_type == AST_CEL_USER_DEFINED)
       ? record.user_defined_name : record.event_name;
    if ((newvariable = ast_var_assign("eventtype", mixed_name))) {
       AST_LIST_INSERT_HEAD(headp, newvariable, entries);
    }
    if (ast_strlen_zero(cfg->general->date_format)) {
       snprintf(timebuf, sizeof(timebuf), "%ld.%06ld", (long) record.event_time.tv_sec,
             (long) record.event_time.tv_usec);
    } else {
       struct ast_tm tm;
       ast_localtime(&record.event_time, &tm, NULL);
       ast_strftime(timebuf, sizeof(timebuf), cfg->general->date_format, &tm);
    }
    if ((newvariable = ast_var_assign("eventtime", timebuf))) {
       AST_LIST_INSERT_HEAD(headp, newvariable, entries);
    }
    if ((newvariable = ast_var_assign("eventenum", record.event_name))) {
       AST_LIST_INSERT_HEAD(headp, newvariable, entries);
    }
    if ((newvariable = ast_var_assign("userdeftype", record.user_defined_name))) {
       AST_LIST_INSERT_HEAD(headp, newvariable, entries);
    }
    if ((newvariable = ast_var_assign("eventextra", record.extra))) {
       AST_LIST_INSERT_HEAD(headp, newvariable, entries);
    }
    ast_channel_caller(tchan)->id.name.valid = 1;
    ast_channel_caller(tchan)->id.name.str = ast_strdup(record.caller_id_name);
    ast_channel_caller(tchan)->id.number.valid = 1;
    ast_channel_caller(tchan)->id.number.str = ast_strdup(record.caller_id_num);
    ast_channel_caller(tchan)->ani.number.valid = 1;
    ast_channel_caller(tchan)->ani.number.str = ast_strdup(record.caller_id_ani);
    ast_channel_redirecting(tchan)->from.number.valid = 1;
    ast_channel_redirecting(tchan)->from.number.str = ast_strdup(record.caller_id_rdnis);
    ast_channel_dialed(tchan)->number.str = ast_strdup(record.caller_id_dnid);
    ast_channel_exten_set(tchan, record.extension);
    ast_channel_context_set(tchan, record.context);
    ast_channel_name_set(tchan, record.channel_name);
    ast_channel_internal_set_fake_ids(tchan, record.unique_id, record.linked_id);
    ast_channel_accountcode_set(tchan, record.account_code);
    ast_channel_peeraccount_set(tchan, record.peer_account);
    ast_channel_userfield_set(tchan, record.user_field);
    if ((newvariable = ast_var_assign("BRIDGEPEER", record.peer))) {
       AST_LIST_INSERT_HEAD(headp, newvariable, entries);
    }
    ast_channel_amaflags_set(tchan, record.amaflag);
    /* We need to store an 'application name' and 'application
     * data' on the channel for logging purposes, but the channel
     * structure only provides a place to store pointers, and it
     * expects these pointers to be pointing to data that does not
     * need to be freed. This means that the channel's destructor
     * does not attempt to free any storage that these pointers
     * point to. However, we can't provide data in that form directly for
     * these structure members. In order to ensure that these data
     * elements have a lifetime that matches the channel's
     * lifetime, we'll put them in a datastore attached to the
     * channel, and set's the channel's pointers to point into the
     * datastore.  The datastore will then be automatically destroyed
     * when the channel is destroyed.
     */
    if (!(datastore = ast_datastore_alloc(&fabricated_channel_datastore, NULL))) {
       ast_channel_unref(tchan);
       return NULL;
    }
    if (!(app_data = ast_malloc(strlen(record.application_name) + strlen(record.application_data) + 2))) {
       ast_datastore_free(datastore);
       ast_channel_unref(tchan);
       return NULL;
    }
    ast_channel_appl_set(tchan, strcpy(app_data, record.application_name));
    ast_channel_data_set(tchan, strcpy(app_data + strlen(record.application_name) + 1,
       record.application_data));
    datastore->data = app_data;
    ast_channel_datastore_add(tchan, datastore);
    return tchan;
 }
ast_cel_fill_record()
int ast_cel_fill_record (const struct ast_event * event, struct ast_cel_event_record * r)
Fill in an ast_cel_event_record from a CEL event.
Parameters
[in] event the CEL event
[out] r the ast_cel_event_record to fill in
Since
1.8
Return values
0 success
non-zero failure
Definition at line 819 of file cel.c.
References ast_cel_event_record::account_code, ast_cel_event_record::amaflag, ast_cel_event_record::application_data, ast_cel_event_record::application_name, AST_CEL_EVENT_RECORD_VERSION, ast_cel_get_type_name(), AST_CEL_USER_DEFINED, ast_event_get_ie_str(), ast_event_get_ie_uint(), AST_EVENT_IE_CEL_ACCTCODE, AST_EVENT_IE_CEL_AMAFLAGS, AST_EVENT_IE_CEL_APPDATA, AST_EVENT_IE_CEL_APPNAME, AST_EVENT_IE_CEL_CHANNAME, AST_EVENT_IE_CEL_CIDANI, AST_EVENT_IE_CEL_CIDDNID, AST_EVENT_IE_CEL_CIDNAME, AST_EVENT_IE_CEL_CIDNUM, AST_EVENT_IE_CEL_CIDRDNIS, AST_EVENT_IE_CEL_CONTEXT, AST_EVENT_IE_CEL_EVENT_TIME, AST_EVENT_IE_CEL_EVENT_TIME_USEC, AST_EVENT_IE_CEL_EVENT_TYPE, AST_EVENT_IE_CEL_EXTEN, AST_EVENT_IE_CEL_EXTRA, AST_EVENT_IE_CEL_LINKEDID, AST_EVENT_IE_CEL_PEER, AST_EVENT_IE_CEL_PEERACCT, AST_EVENT_IE_CEL_UNIQUEID, AST_EVENT_IE_CEL_USEREVENT_NAME, AST_EVENT_IE_CEL_USERFIELD, ast_log, ast_cel_event_record::caller_id_ani, ast_cel_event_record::caller_id_dnid, ast_cel_event_record::caller_id_name, ast_cel_event_record::caller_id_num, ast_cel_event_record::caller_id_rdnis, ast_cel_event_record::channel_name, ast_cel_event_record::context, ast_cel_event_record::event_name, ast_cel_event_record::event_time, ast_cel_event_record::event_type, ast_cel_event_record::extension, ast_cel_event_record::extra, ast_cel_event_record::linked_id, LOG_ERROR, ast_cel_event_record::peer, ast_cel_event_record::peer_account, S_OR, ast_cel_event_record::unique_id, ast_cel_event_record::user_defined_name, ast_cel_event_record::user_field, and ast_cel_event_record::version.
Referenced by ast_cel_fabricate_channel_from_event(), cel_bs_put(), manager_log(), odbc_log(), pgsql_log(), radius_log(), and tds_log().
 {
    if (r->version != AST_CEL_EVENT_RECORD_VERSION) {
       ast_log(LOG_ERROR, "Module ABI mismatch for ast_cel_event_record.  "
             "Please ensure all modules were compiled for "
             "this version of Asterisk.\n");
       return -1;
    }
    r->event_type = ast_event_get_ie_uint(e, AST_EVENT_IE_CEL_EVENT_TYPE);
    r->event_time.tv_sec = ast_event_get_ie_uint(e, AST_EVENT_IE_CEL_EVENT_TIME);
    r->event_time.tv_usec = ast_event_get_ie_uint(e, AST_EVENT_IE_CEL_EVENT_TIME_USEC);
    r->event_name = ast_cel_get_type_name(r->event_type);
    if (r->event_type == AST_CEL_USER_DEFINED) {
       r->user_defined_name = ast_event_get_ie_str(e, AST_EVENT_IE_CEL_USEREVENT_NAME);
    } else {
       r->user_defined_name = "";
    }
    r->caller_id_name   = S_OR(ast_event_get_ie_str(e, AST_EVENT_IE_CEL_CIDNAME), "");
    r->caller_id_num    = S_OR(ast_event_get_ie_str(e, AST_EVENT_IE_CEL_CIDNUM), "");
    r->caller_id_ani    = S_OR(ast_event_get_ie_str(e, AST_EVENT_IE_CEL_CIDANI), "");
    r->caller_id_rdnis  = S_OR(ast_event_get_ie_str(e, AST_EVENT_IE_CEL_CIDRDNIS), "");
    r->caller_id_dnid   = S_OR(ast_event_get_ie_str(e, AST_EVENT_IE_CEL_CIDDNID), "");
    r->extension        = S_OR(ast_event_get_ie_str(e, AST_EVENT_IE_CEL_EXTEN), "");
    r->context          = S_OR(ast_event_get_ie_str(e, AST_EVENT_IE_CEL_CONTEXT), "");
    r->channel_name     = S_OR(ast_event_get_ie_str(e, AST_EVENT_IE_CEL_CHANNAME), "");
    r->application_name = S_OR(ast_event_get_ie_str(e, AST_EVENT_IE_CEL_APPNAME), "");
    r->application_data = S_OR(ast_event_get_ie_str(e, AST_EVENT_IE_CEL_APPDATA), "");
    r->account_code     = S_OR(ast_event_get_ie_str(e, AST_EVENT_IE_CEL_ACCTCODE), "");
    r->peer_account     = S_OR(ast_event_get_ie_str(e, AST_EVENT_IE_CEL_PEERACCT), "");
    r->unique_id        = S_OR(ast_event_get_ie_str(e, AST_EVENT_IE_CEL_UNIQUEID), "");
    r->linked_id        = S_OR(ast_event_get_ie_str(e, AST_EVENT_IE_CEL_LINKEDID), "");
    r->amaflag          = ast_event_get_ie_uint(e, AST_EVENT_IE_CEL_AMAFLAGS);
    r->user_field       = S_OR(ast_event_get_ie_str(e, AST_EVENT_IE_CEL_USERFIELD), "");
    r->peer             = S_OR(ast_event_get_ie_str(e, AST_EVENT_IE_CEL_PEER), "");
    r->extra            = S_OR(ast_event_get_ie_str(e, AST_EVENT_IE_CEL_EXTRA), "");
    return 0;
 }
ast_cel_general_config_alloc()
void* ast_cel_general_config_alloc (void)
Allocate a CEL configuration object.
Return values
NULL on error
The new CEL configuration object
Definition at line 188 of file cel.c.
References ao2_alloc, ao2_cleanup, ao2_ref, ast_str_container_alloc, ast_string_field_init, cel_general_config_dtor(), NULL, NUM_APP_BUCKETS, and RAII_VAR.
Referenced by cel_config_alloc(), and load_module().
 {
    RAII_VAR(struct ast_cel_general_config *, cfg, NULL, ao2_cleanup);
    if (!(cfg = ao2_alloc(sizeof(*cfg), cel_general_config_dtor))) {
       return NULL;
    }
    if (ast_string_field_init(cfg, 64)) {
       return NULL;
    }
    if (!(cfg->apps = ast_str_container_alloc(NUM_APP_BUCKETS))) {
       return NULL;
    }
    ao2_ref(cfg, +1);
    return cfg;
 }
ast_cel_get_config()
struct ast_cel_general_config* ast_cel_get_config (void)
Obtain the current CEL configuration.
Since
12 The configuration is a ref counted object. The caller of this function must decrement the ref count when finished with the configuration.
Return values
NULL on error
The current CEL configuration
Definition at line 1690 of file cel.c.
References ao2_cleanup, ao2_global_obj_ref, ao2_ref, NULL, and RAII_VAR.
Referenced by test_cel_init_cb().
 {
    RAII_VAR(struct cel_config *, mod_cfg, ao2_global_obj_ref(cel_configs), ao2_cleanup);
    if (!mod_cfg || !mod_cfg->general) {
       return NULL;
    }
    ao2_ref(mod_cfg->general, +1);
    return mod_cfg->general;
 }
ast_cel_get_type_name()
const char* ast_cel_get_type_name (enum ast_cel_event_type type)
Get the name of a CEL event type.
Parameters
type the type to get the name of
Since
1.8
Returns
the string representation of the type
Definition at line 491 of file cel.c.
References cel_event_types, and S_OR.
Referenced by ast_cel_fill_record(), cel_generic_cb(), dump_event(), and handle_cli_status().
 {
    return S_OR(cel_event_types[type], "Unknown");
 }
ast_cel_publish_event()
void ast_cel_publish_event (struct ast_channel * chan, enum ast_cel_event_type event_type, struct ast_json * blob)
Publish a CEL event.
Since
12
Parameters
chan This is the primary channel associated with this channel event.
event_type This is the type of call event being reported.
blob This contains any additional parameters that need to be conveyed for this event.
Definition at line 1666 of file cel.c.
References ao2_cleanup, ast_cel_topic(), ast_channel_blob_create_from_cache(), ast_channel_uniqueid(), ast_json_pack(), ast_json_ref(), ast_json_unref(), cel_generic_type(), and stasis_publish().
Referenced by celgenuserevent_exec().
 {
    struct ast_json *cel_blob;
    struct stasis_message *message;
    cel_blob = ast_json_pack("{s: i, s: o}",
       "event_type", event_type,
       "event_details", ast_json_ref(blob));
    message = ast_channel_blob_create_from_cache(ast_channel_uniqueid(chan), cel_generic_type(), cel_blob);
    if (message) {
       stasis_publish(ast_cel_topic(), message);
    }
    ao2_cleanup(message);
    ast_json_unref(cel_blob);
 }
ast_cel_set_config()
void ast_cel_set_config (struct ast_cel_general_config * config)
Set the current CEL configuration.
Since
12
Parameters
config The new CEL configuration
Definition at line 1702 of file cel.c.
References ao2_bump, ao2_cleanup, ao2_global_obj_ref, ao2_ref, ast_cel_check_enabled(), config, create_routes(), destroy_routes(), cel_config::general, and is_enabled().
Referenced by cel_verify_and_cleanup_cb(), and test_cel_init_cb().
 {
    int was_enabled;
    int is_enabled;
    struct ast_cel_general_config *cleanup_config;
    struct cel_config *mod_cfg = ao2_global_obj_ref(cel_configs);
    if (mod_cfg) {
       was_enabled = ast_cel_check_enabled();
       cleanup_config = mod_cfg->general;
       ao2_bump(config);
       mod_cfg->general = config;
       ao2_cleanup(cleanup_config);
       is_enabled = ast_cel_check_enabled();
       if (!was_enabled && is_enabled) {
          create_routes();
       } else if (was_enabled && !is_enabled) {
          destroy_routes();
       }
       ao2_ref(mod_cfg, -1);
    }
 }
ast_cel_str_to_event_type()
enum ast_cel_event_type ast_cel_str_to_event_type (const char * name)
Get the event type from a string.
Parameters
name the event type name as a string
Since
1.8
Returns
the ast_cel_event_type given by the string
Definition at line 418 of file cel.c.
References ARRAY_LEN, AST_CEL_INVALID_VALUE, ast_log, cel_event_types, and LOG_ERROR.
Referenced by events_handler().
 {
    unsigned int i;
    for (i = 0; i < ARRAY_LEN(cel_event_types); i++) {
       if (cel_event_types[i] && !strcasecmp(name, cel_event_types[i])) {
          return i;
       }
    }
    ast_log(LOG_ERROR, "Unknown event name '%s'\n", name);
    return AST_CEL_INVALID_VALUE;
 }
ast_cel_topic()
struct stasis_topic* ast_cel_topic (void)
Get the CEL topic.
Return values
The CEL topic
NULL if not allocated
Definition at line 1685 of file cel.c.
References cel_topic.
Referenced by ast_cel_publish_event(), and create_subscriptions().
 {
    return cel_topic;
 }