Asterisk - The Open Source Telephony Project: res_format_attr_ilbc.c File Reference
res_format_attr_ilbc.c File Reference
iLBC format attribute interface
#include "asterisk.h"
#include <ctype.h>
#include "asterisk/module.h"
#include "asterisk/format.h"
#include "asterisk/strings.h"
#include "asterisk/utils.h"
#include "asterisk/ilbc.h"
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int ilbc_clone (const struct ast_format *src, struct ast_format *dst)
static void ilbc_destroy (struct ast_format *format)
static void ilbc_generate_sdp_fmtp (const struct ast_format *format, unsigned int payload, struct ast_str **str)
static struct ast_format * ilbc_getjoint (const struct ast_format *format1, const struct ast_format *format2)
static struct ast_format * ilbc_parse_sdp_fmtp (const struct ast_format *format, const char *attributes)
static int load_module (void)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "iLBC Format Attribute Module" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_CHANNEL_DEPEND, }
static const struct ast_module_info * ast_module_info = &__mod_info
static struct ilbc_attr default_ilbc_attr
static struct ast_format_interface ilbc_interface
Detailed Description
iLBC format attribute interface
Author
Alexander Traud pabst.nosp@m.raud.nosp@m.@comp.nosp@m.user.nosp@m.ve.co.nosp@m.m
Note
http://tools.ietf.org/html/rfc3952
Definition in file res_format_attr_ilbc.c.
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 179 of file res_format_attr_ilbc.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 179 of file res_format_attr_ilbc.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 179 of file res_format_attr_ilbc.c.
ilbc_clone()
static int ilbc_clone (const struct ast_format * src, struct ast_format * dst) static
Definition at line 54 of file res_format_attr_ilbc.c.
References ast_format_get_attribute_data(), ast_format_set_attribute_data(), ast_malloc, and default_ilbc_attr.
 {
    struct ilbc_attr *original = ast_format_get_attribute_data(src);
    struct ilbc_attr *attr = ast_malloc(sizeof(*attr));
    if (!attr) {
       return -1;
    }
    if (original) {
       *attr = *original;
    } else {
       *attr = default_ilbc_attr;
    }
    ast_format_set_attribute_data(dst, attr);
    return 0;
 }
ilbc_destroy()
static void ilbc_destroy (struct ast_format * format) static
Definition at line 47 of file res_format_attr_ilbc.c.
References ast_format_get_attribute_data(), and ast_free.
 {
    struct ilbc_attr *attr = ast_format_get_attribute_data(format);
    ast_free(attr);
 }
ilbc_generate_sdp_fmtp()
static void ilbc_generate_sdp_fmtp (const struct ast_format * format, unsigned int payload, struct ast_str ** str) static
Definition at line 102 of file res_format_attr_ilbc.c.
References ast_format_get_attribute_data(), ast_str_append(), default_ilbc_attr, and ilbc_attr::mode.
 {
    struct ilbc_attr *attr = ast_format_get_attribute_data(format);
    if (!attr) {
       attr = &default_ilbc_attr;
    }
    /* When the VoIP/SIP client Zoiper calls Asterisk and its
     * iLBC 20 is disabled but iLBC 30 enabled, Zoiper still
     * falls back to iLBC 20, when there is no mode=30 in the
     * answer. Consequently, Zoiper defaults to iLBC 20. To
     * make that client happy, Asterisk sends mode always.
     * tested in June 2016, Zoiper Premium 1.13.2 for iPhone
     */
    /* if (attr->mode != 30) */ {
       ast_str_append(str, 0, "a=fmtp:%u mode=%u\r\n", payload, attr->mode);
    }
 }
ilbc_getjoint()
static struct ast_format* ilbc_getjoint (const struct ast_format * format1, const struct ast_format * format2) static
Definition at line 122 of file res_format_attr_ilbc.c.
References ast_format_clone(), ast_format_get_attribute_data(), default_ilbc_attr, ilbc_attr::mode, and NULL.
 {
    struct ast_format *jointformat;
    struct ilbc_attr *attr1 = ast_format_get_attribute_data(format1);
    struct ilbc_attr *attr2 = ast_format_get_attribute_data(format2);
    struct ilbc_attr *attr_res;
    if (!attr1) {
       attr1 = &default_ilbc_attr;
    }
    if (!attr2) {
       attr2 = &default_ilbc_attr;
    }
    jointformat = ast_format_clone(format1);
    if (!jointformat) {
       return NULL;
    }
    attr_res = ast_format_get_attribute_data(jointformat);
    if (attr1->mode != attr2->mode) {
       attr_res->mode = 30;
    }
    return jointformat;
 }
ilbc_parse_sdp_fmtp()
static struct ast_format* ilbc_parse_sdp_fmtp (const struct ast_format * format, const char * attributes) static
Definition at line 74 of file res_format_attr_ilbc.c.
References ast_format_clone(), ast_format_get_attribute_data(), ast_strdupa, ilbc_attr::mode, and NULL.
 {
    char *attribs = ast_strdupa(attributes), *attrib;
    struct ast_format *cloned;
    struct ilbc_attr *attr;
    const char *kvp;
    unsigned int val;
    cloned = ast_format_clone(format);
    if (!cloned) {
       return NULL;
    }
    attr = ast_format_get_attribute_data(cloned);
    /* lower-case everything, so we are case-insensitive */
    for (attrib = attribs; *attrib; ++attrib) {
       *attrib = tolower(*attrib);
    } /* based on channels/chan_sip.c:process_a_sdp_image() */
    if ((kvp = strstr(attribs, "mode")) && sscanf(kvp, "mode=%30u", &val) == 1) {
       attr->mode = val;
    } else {
       attr->mode = 30; /* optional attribute; 30 is default value */
    }
    return cloned;
 }
load_module()
static int load_module (void) static
Definition at line 160 of file res_format_attr_ilbc.c.
References ast_format_interface_register, AST_MODULE_LOAD_DECLINE, and AST_MODULE_LOAD_SUCCESS.
Referenced by unload_module().
 {
    if (ast_format_interface_register("ilbc", &ilbc_interface)) {
       return AST_MODULE_LOAD_DECLINE;
    }
    return AST_MODULE_LOAD_SUCCESS;
 }
unload_module()
static int unload_module (void) static
Definition at line 169 of file res_format_attr_ilbc.c.
References AST_MODFLAG_LOAD_ORDER, AST_MODPRI_CHANNEL_DEPEND, AST_MODULE_INFO(), AST_MODULE_SUPPORT_CORE, ASTERISK_GPL_KEY, and load_module().
 {
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "iLBC Format Attribute Module" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_CHANNEL_DEPEND, } static
Definition at line 179 of file res_format_attr_ilbc.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 179 of file res_format_attr_ilbc.c.
default_ilbc_attr
struct ilbc_attr default_ilbc_attr static
Initial value:
= {
   .mode = 20,
}
Definition at line 43 of file res_format_attr_ilbc.c.
Referenced by ilbc_clone(), ilbc_generate_sdp_fmtp(), and ilbc_getjoint().
ilbc_interface
struct ast_format_interface ilbc_interface static
Definition at line 150 of file res_format_attr_ilbc.c.