Asterisk - The Open Source Telephony Project: module.h File Reference
module.h File Reference
Asterisk module definitions.
#include "asterisk/utils.h"
Data Structures
struct ast_module_info
Macros
#define AST_MODULE_CONFIG "modules.conf"
Module configuration file.
#define AST_MODULE_INFO(keystr, flags_to_set, desc, fields...)
#define AST_MODULE_INFO_STANDARD(keystr, desc)
#define AST_MODULE_INFO_STANDARD_DEPRECATED(keystr, desc)
#define AST_MODULE_INFO_STANDARD_EXTENDED(keystr, desc)
#define ast_module_ref(mod) __ast_module_ref(mod, __FILE__, __LINE__, __PRETTY_FUNCTION__)
Hold a reference to the module.
#define ast_module_running_ref(mod) __ast_module_running_ref(mod, __FILE__, __LINE__, __PRETTY_FUNCTION__)
Hold a reference to the module if it is running.
#define ast_module_shutdown_ref(mod) __ast_module_shutdown_ref(mod, __FILE__, __LINE__, __PRETTY_FUNCTION__)
Prevent unload of the module before shutdown.
#define ast_module_unref(mod) __ast_module_unref(mod, __FILE__, __LINE__, __PRETTY_FUNCTION__)
Release a reference to the module.
#define ast_module_user_add(chan) __ast_module_user_add(AST_MODULE_SELF, chan)
#define ast_module_user_hangup_all() __ast_module_user_hangup_all(AST_MODULE_SELF)
#define ast_module_user_remove(user) __ast_module_user_remove(AST_MODULE_SELF, user)
#define ast_register_application(app, execute, synopsis, description) ast_register_application2(app, execute, synopsis, description, AST_MODULE_SELF)
Register an application.
#define ast_register_application_xml(app, execute) ast_register_application(app, execute, NULL, NULL)
Register an application using XML documentation.
#define ASTERISK_GPL_KEY "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n"
The text the key() function should return.
#define SCOPED_MODULE_USE(module) RAII_VAR(struct ast_module *, __self__ ## __LINE__, ast_module_ref(module), ast_module_unref)
Enumerations
enum ast_module_flags { AST_MODFLAG_DEFAULT = 0, AST_MODFLAG_GLOBAL_SYMBOLS = (1 << 0), AST_MODFLAG_LOAD_ORDER = (1 << 1) }
enum ast_module_helper_type {
AST_MODULE_HELPER_LOADED = 0, AST_MODULE_HELPER_RELOAD = 1, AST_MODULE_HELPER_LOAD, AST_MODULE_HELPER_UNLOAD,
AST_MODULE_HELPER_RUNNING
}
enum ast_module_load_priority {
AST_MODPRI_REALTIME_DEPEND = 10, AST_MODPRI_REALTIME_DEPEND2 = 20, AST_MODPRI_REALTIME_DRIVER = 30, AST_MODPRI_CORE = 40,
AST_MODPRI_TIMING = 50, AST_MODPRI_CHANNEL_DEPEND = 60, AST_MODPRI_CHANNEL_DRIVER = 70, AST_MODPRI_APP_DEPEND = 80,
AST_MODPRI_DEVSTATE_PROVIDER = 90, AST_MODPRI_DEVSTATE_PLUGIN = 100, AST_MODPRI_CDR_DRIVER = 110, AST_MODPRI_DEFAULT = 128,
AST_MODPRI_DEVSTATE_CONSUMER = 150
}
enum ast_module_load_result {
AST_MODULE_LOAD_SUCCESS = 0, AST_MODULE_LOAD_DECLINE = 1, AST_MODULE_LOAD_SKIP = 2, AST_MODULE_LOAD_PRIORITY = 3,
AST_MODULE_LOAD_FAILURE = -1
}
enum ast_module_reload_result {
AST_MODULE_RELOAD_SUCCESS = 0, AST_MODULE_RELOAD_QUEUED, AST_MODULE_RELOAD_NOT_FOUND, AST_MODULE_RELOAD_ERROR,
AST_MODULE_RELOAD_IN_PROGRESS, AST_MODULE_RELOAD_UNINITIALIZED, AST_MODULE_RELOAD_NOT_IMPLEMENTED
}
Possible return types for ast_module_reload.
enum ast_module_support_level { AST_MODULE_SUPPORT_UNKNOWN, AST_MODULE_SUPPORT_CORE, AST_MODULE_SUPPORT_EXTENDED, AST_MODULE_SUPPORT_DEPRECATED }
enum ast_module_unload_mode { AST_FORCE_SOFT = 0, AST_FORCE_FIRM = 1, AST_FORCE_HARD = 2 }
Functions
struct ast_module * __ast_module_ref (struct ast_module *mod, const char *file, int line, const char *func)
struct ast_module * __ast_module_running_ref (struct ast_module *mod, const char *file, int line, const char *func)
void __ast_module_shutdown_ref (struct ast_module *mod, const char *file, int line, const char *func)
void __ast_module_unref (struct ast_module *mod, const char *file, int line, const char *func)
struct ast_module_user * __ast_module_user_add (struct ast_module *, struct ast_channel *)
void __ast_module_user_hangup_all (struct ast_module *)
void __ast_module_user_remove (struct ast_module *, struct ast_module_user *)
enum ast_module_load_result ast_load_resource (const char *resource_name)
Load a module.
int ast_loader_register (int(*updater)(void))
Add a procedure to be run when modules have been updated.
int ast_loader_unregister (int(*updater)(void))
Remove a procedure to be run when modules are updated.
int ast_module_check (const char *name)
Check if module with the name given is loaded.
char * ast_module_helper (const char *line, const char *word, int pos, int state, int rpos, enum ast_module_helper_type type)
Match modules names for the Asterisk cli.
const char * ast_module_name (const struct ast_module *mod)
Get the name of a module.
void ast_module_register (const struct ast_module_info *)
enum ast_module_reload_result ast_module_reload (const char *name)
Reload asterisk modules.
const char * ast_module_support_level_to_string (enum ast_module_support_level support_level)
void ast_module_unregister (const struct ast_module_info *)
int ast_register_application2 (const char *app, int(*execute)(struct ast_channel *, const char *), const char *synopsis, const char *description, void *mod)
Register an application.
int ast_unload_resource (const char *resource_name, enum ast_module_unload_mode)
Unload a module.
int ast_unregister_application (const char *app)
Unregister an application.
int ast_update_module_list (int(*modentry)(const char *module, const char *description, int usecnt, const char *status, const char *like, enum ast_module_support_level support_level), const char *like)
Ask for a list of modules, descriptions, use counts and status.
int ast_update_module_list_condition (int(*modentry)(const char *module, const char *description, int usecnt, const char *status, const char *like, enum ast_module_support_level support_level, void *data, const char *condition), const char *like, void *data, const char *condition)
Ask for a list of modules, descriptions, use counts and status.
int ast_update_module_list_data (int(*modentry)(const char *module, const char *description, int usecnt, const char *status, const char *like, enum ast_module_support_level support_level, void *data), const char *like, void *data)
Ask for a list of modules, descriptions, use counts and status.
void ast_update_use_count (void)
Notify when usecount has been changed.
Variables
static const struct ast_module_info * ast_module_info
Detailed Description
Asterisk module definitions.
This file contains the definitons for functions Asterisk modules should provide and some other module related functions.
Definition in file module.h.
Macro Definition Documentation
AST_MODULE_CONFIG
#define AST_MODULE_CONFIG "modules.conf"
Module configuration file.
Definition at line 59 of file module.h.
Referenced by loader_config_init().
AST_MODULE_INFO
#define AST_MODULE_INFO (keystr, flags_to_set, desc, fields...)
Definition at line 543 of file module.h.
AST_MODULE_INFO_STANDARD
#define AST_MODULE_INFO_STANDARD (keystr, desc)
Definition at line 567 of file module.h.
AST_MODULE_INFO_STANDARD_DEPRECATED
#define AST_MODULE_INFO_STANDARD_DEPRECATED (keystr, desc)
Definition at line 583 of file module.h.
AST_MODULE_INFO_STANDARD_EXTENDED
#define AST_MODULE_INFO_STANDARD_EXTENDED (keystr, desc)
Definition at line 575 of file module.h.
ast_module_ref
#define ast_module_ref (mod) __ast_module_ref(mod, __FILE__, __LINE__, __PRETTY_FUNCTION__)
Hold a reference to the module.
Parameters
mod Module to reference
Returns
mod
Note
A module reference will prevent the module from being unloaded.
Definition at line 443 of file module.h.
Referenced by __ast_datastore_alloc(), action_dahdishowchannels(), allocate_subscription_tree(), alsa_new(), ast_iax2_new(), ast_sip_session_add_supplements(), ast_srtp_create(), bridge_builtin_set_limits(), dahdi_new(), get_lock(), instance_created_observer(), mgcp_new(), mixmonitor_exec(), module_reffed_deps_add(), moh_alloc(), moh_files_alloc(), my_on_hook(), newpvt(), ooh323_new(), ooh323c_start_call_thread(), oss_new(), phone_check_exception(), phone_new(), sdp_crypto_alloc(), sip_create_publication(), sip_handle_cc(), sip_new(), skinny_new(), and smdi_load().
ast_module_running_ref
#define ast_module_running_ref (mod) __ast_module_running_ref(mod, __FILE__, __LINE__, __PRETTY_FUNCTION__)
Hold a reference to the module if it is running.
Parameters
mod Module to reference
Return values
mod if running
NULL if not running
The returned pointer should be released with ast_module_unref.
Note
A module reference will prevent the module from being unloaded.
Examples:
/usr/src/asterisk-18.5.0/main/app.c.
Definition at line 455 of file module.h.
Referenced by __ast_cli_generator(), __ast_sorcery_object_type_insert_wizard(), agi_handle_command(), ast_app_exec_sub(), ast_app_expand_sub_args(), ast_cli_command_full(), ast_hook_send_action(), ast_rtp_instance_new(), ast_timer_open(), fax_session_new(), fax_session_reserve(), find_best_technology(), get_filestream(), and process_message().
ast_module_shutdown_ref
#define ast_module_shutdown_ref (mod) __ast_module_shutdown_ref(mod, __FILE__, __LINE__, __PRETTY_FUNCTION__)
Prevent unload of the module before shutdown.
Parameters
mod Module to hold
Note
This should not be balanced by a call to ast_module_unref.
Definition at line 464 of file module.h.
Referenced by __ast_bucket_scheme_register(), __ast_codec_register_with_format(), __ast_format_interface_register(), load_module(), and start_resource().
ast_module_unref
#define ast_module_unref (mod) __ast_module_unref(mod, __FILE__, __LINE__, __PRETTY_FUNCTION__)
Release a reference to the module.
Parameters
mod Module to release
Examples:
/usr/src/asterisk-18.5.0/main/app.c.
Definition at line 469 of file module.h.
Referenced by __ast_cli_generator(), __ast_sorcery_object_type_insert_wizard(), action_dahdishowchannels(), agi_handle_command(), alsa_hangup(), ast_app_exec_sub(), ast_app_expand_sub_args(), ast_cli_command_full(), ast_datastore_free(), ast_hook_send_action(), ast_rtp_instance_new(), ast_sip_session_remove_supplements(), ast_srtp_destroy(), ast_timer_close(), ast_timer_open(), bridge_builtin_set_limits(), bridge_features_limits_dtor(), bridge_tech_deferred_destroy(), codec_dtor(), dahdi_destroy_channel_range(), dahdi_hangup(), destroy(), destroy_bridge(), destroy_session(), fax_session_new(), filestream_destructor(), find_best_technology(), get_filestream(), iax2_predestroy(), instance_destroying_observer(), instance_destructor(), local_ast_moh_cleanup(), lock_free(), mgcp_hangup(), mixmonitor_exec(), mixmonitor_thread(), module_destroy(), modules_shutdown(), my_on_hook(), newpvt(), onCallCleared(), ooh323_destroy(), ooh323_hangup(), ooh323c_call_thread(), oss_hangup(), phone_check_exception(), phone_hangup(), process_message(), publication_destroy_fn(), res_sdp_crypto_dtor(), sip_cc_monitor_destructor(), sip_hangup(), skinny_hangup(), smart_bridge_operation(), smdi_interface_destroy(), sorcery_object_wizard_destructor(), and subscription_tree_destructor().
ast_module_user_add
#define ast_module_user_add (chan) __ast_module_user_add(AST_MODULE_SELF, chan)
Definition at line 426 of file module.h.
Referenced by ast_calendar_register(), canmatch(), exec(), exists(), matchmore(), nbs_new(), smdi_msg_read(), and smdi_msg_retrieve_read().
ast_module_user_hangup_all
#define ast_module_user_hangup_all () __ast_module_user_hangup_all(AST_MODULE_SELF)
Definition at line 428 of file module.h.
ast_module_user_remove
#define ast_module_user_remove (user) __ast_module_user_remove(AST_MODULE_SELF, user)
Definition at line 427 of file module.h.
Referenced by ast_calendar_unregister(), canmatch(), exec(), exists(), matchmore(), nbs_destroy(), smdi_msg_read(), and smdi_msg_retrieve_read().
ast_register_application
#define ast_register_application (app, execute, synopsis, description) ast_register_application2(app, execute, synopsis, description, AST_MODULE_SELF)
Register an application.
Parameters
app Short name of the application
execute a function callback to execute the application. It should return non-zero if the channel needs to be hung up.
synopsis a short description (one line synopsis) of the application
description long description with all of the details about the use of the application
This registers an application with Asterisk's internal application list.
Note
The individual applications themselves are responsible for registering and unregistering and unregistering their own CLI commands.
Return values
0 success
-1 failure.
Definition at line 610 of file module.h.
Referenced by load_module().
ast_register_application_xml
#define ast_register_application_xml (app, execute) ast_register_application(app, execute, NULL, NULL)
Register an application using XML documentation.
Parameters
app Short name of the application
execute a function callback to execute the application. It should return non-zero if the channel needs to be hung up.
This registers an application with Asterisk's internal application list.
Note
The individual applications themselves are responsible for registering and unregistering and unregistering their own CLI commands.
Return values
0 success
-1 failure.
Definition at line 626 of file module.h.
Referenced by load_module(), and load_parking_applications().
ASTERISK_GPL_KEY
#define ASTERISK_GPL_KEY "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n"
The text the key() function should return.
Definition at line 46 of file module.h.
Referenced by ast_beep_stop(), ast_cel_backend_register(), ast_manager_event_blob_create(), ast_sounds_get_index_for_file(), chan_misdn_log(), do_reload(), find_member_by_queuename_and_interface(), handle_cli_realtime_mysql_status(), handle_cli_realtime_pgsql_status(), load_module(), load_values_config(), ooh323_convert_hangupcause_h323ToAsterisk(), realtime_ldap_status(), reload(), reload_module(), unload_module(), and vm_msg_play().
SCOPED_MODULE_USE
#define SCOPED_MODULE_USE (module) RAII_VAR(struct ast_module *, __self__ ## __LINE__, ast_module_ref(module), ast_module_unref)
Macro to safely ref and unref the self module for the current scope
Definition at line 665 of file module.h.
Referenced by ast_ari_events_event_websocket_ws_established_cb(), ast_parking_blind_transfer_park(), ast_parking_is_exten_park(), ast_parking_park_bridge_channel(), ast_parking_park_call(), ast_websocket_uri_cb(), and feature_park_call().
Enumeration Type Documentation
ast_module_flags
enum ast_module_flags
Enumerator
AST_MODFLAG_DEFAULT
AST_MODFLAG_GLOBAL_SYMBOLS
AST_MODFLAG_LOAD_ORDER
Definition at line 314 of file module.h.
                       {
    AST_MODFLAG_DEFAULT = 0,
    AST_MODFLAG_GLOBAL_SYMBOLS = (1 << 0),
    AST_MODFLAG_LOAD_ORDER = (1 << 1),
 };
ast_module_helper_type
enum ast_module_helper_type
Used to specify which modules should be returned by ast_module_helper.
Enumerator
AST_MODULE_HELPER_LOADED
Modules that are loaded by dlopen.
AST_MODULE_HELPER_RELOAD
Running modules that include a reload callback.
AST_MODULE_HELPER_LOAD
Modules that can be loaded or started.
AST_MODULE_HELPER_UNLOAD
Modules that can be unloaded.
AST_MODULE_HELPER_RUNNING
Running modules
Definition at line 127 of file module.h.
{
    /*! Modules that are loaded by dlopen. */
    AST_MODULE_HELPER_LOADED = 0,
    /*! Running modules that include a reload callback. */
    AST_MODULE_HELPER_RELOAD = 1,
    /*! Modules that can be loaded or started. */
    AST_MODULE_HELPER_LOAD,
    /*! Modules that can be unloaded. */
    AST_MODULE_HELPER_UNLOAD,
    /*! Running modules */
    AST_MODULE_HELPER_RUNNING,
 };
ast_module_load_priority
enum ast_module_load_priority
Enumerator
AST_MODPRI_REALTIME_DEPEND
Dependency for a realtime driver
AST_MODPRI_REALTIME_DEPEND2
Second level dependency for a realtime driver (func_curl needs res_curl, but is needed by res_config_curl)
AST_MODPRI_REALTIME_DRIVER
A realtime driver, which provides configuration services for other modules
AST_MODPRI_CORE
A core module originally meant to start between preload and load.
AST_MODPRI_TIMING
Dependency for a channel (MOH needs timing interfaces to be fully loaded)
AST_MODPRI_CHANNEL_DEPEND
Channel driver dependency (may depend upon realtime, e.g. MOH)
AST_MODPRI_CHANNEL_DRIVER
Channel drivers (provide devicestate)
AST_MODPRI_APP_DEPEND
Dependency for an application
AST_MODPRI_DEVSTATE_PROVIDER
Applications and other modules that provide devicestate (e.g. meetme)
AST_MODPRI_DEVSTATE_PLUGIN
Plugin for a module that provides devstate (e.g. res_calendar_*)
AST_MODPRI_CDR_DRIVER
CDR or CEL backend
AST_MODPRI_DEFAULT
Modules not otherwise defined (such as most apps) will load here
AST_MODPRI_DEVSTATE_CONSUMER
Certain modules, which consume devstate, need to load after all others (e.g. app_queue)
Definition at line 320 of file module.h.
{
    AST_MODPRI_REALTIME_DEPEND =    10,  /*!< Dependency for a realtime driver */
    AST_MODPRI_REALTIME_DEPEND2 =   20,  /*!< Second level dependency for a realtime driver (func_curl needs res_curl, but is needed by res_config_curl) */
    AST_MODPRI_REALTIME_DRIVER =    30,  /*!< A realtime driver, which provides configuration services for other modules */
    AST_MODPRI_CORE =               40,  /*!< A core module originally meant to start between preload and load. */
    AST_MODPRI_TIMING =             50,  /*!< Dependency for a channel (MOH needs timing interfaces to be fully loaded) */
    AST_MODPRI_CHANNEL_DEPEND =     60,  /*!< Channel driver dependency (may depend upon realtime, e.g. MOH) */
    AST_MODPRI_CHANNEL_DRIVER =     70,  /*!< Channel drivers (provide devicestate) */
    AST_MODPRI_APP_DEPEND =         80,  /*!< Dependency for an application */
    AST_MODPRI_DEVSTATE_PROVIDER =  90,  /*!< Applications and other modules that _provide_ devicestate (e.g. meetme) */
    AST_MODPRI_DEVSTATE_PLUGIN =   100,  /*!< Plugin for a module that provides devstate (e.g. res_calendar_*) */
    AST_MODPRI_CDR_DRIVER =        110,  /*!< CDR or CEL backend */
    AST_MODPRI_DEFAULT =           128,  /*!< Modules not otherwise defined (such as most apps) will load here */
    AST_MODPRI_DEVSTATE_CONSUMER = 150,  /*!< Certain modules, which consume devstate, need to load after all others (e.g. app_queue) */
 };
ast_module_load_result
enum ast_module_load_result
Enumerator
AST_MODULE_LOAD_SUCCESS
Module is loaded and configured.
AST_MODULE_LOAD_DECLINE
Module has failed to load, may be in an inconsistent state.
This value is used when a module fails to start but does not risk system-wide stability. Declined modules will prevent any other dependent module from starting.
AST_MODULE_LOAD_SKIP
AST_MODULE_LOAD_PRIORITY
AST_MODULE_LOAD_FAILURE
Module could not be loaded properly.
This return should only be returned by modules for unrecoverable failures that cause the whole system to become unstable. In almost all cases AST_MODULE_LOAD_DECLINE should be used instead.
Warning
Returning this code from any module will cause startup to abort. If startup is already completed this code has the same effect as AST_MODULE_LOAD_DECLINE.
Definition at line 68 of file module.h.
{
    /*! Module is loaded and configured. */
    AST_MODULE_LOAD_SUCCESS = 0,
    /*!
     * \brief Module has failed to load, may be in an inconsistent state.
     *
     * This value is used when a module fails to start but does not risk
     * system-wide stability.  Declined modules will prevent any other
     * dependent module from starting.
     */
    AST_MODULE_LOAD_DECLINE = 1,
    /*! \internal
     * \brief Module was skipped for some reason.
     *
     * \note For loader.c use only. Should never be returned by modules.
     */
    AST_MODULE_LOAD_SKIP = 2,
    /*! \internal
     * \brief Module is not loaded yet, but is added to priority list.
     *
     * \note For loader.c use only. Should never be returned by modules.
     */
    AST_MODULE_LOAD_PRIORITY = 3,
    /*!
     * \brief Module could not be loaded properly.
     *
     * This return should only be returned by modules for unrecoverable
     * failures that cause the whole system to become unstable.  In almost
     * all cases \ref AST_MODULE_LOAD_DECLINE should be used instead.
     *
     * \warning Returning this code from any module will cause startup to abort.
     * If startup is already completed this code has the same effect as
     * \ref AST_MODULE_LOAD_DECLINE.
     */
    AST_MODULE_LOAD_FAILURE = -1,
 };
ast_module_reload_result
enum ast_module_reload_result
Possible return types for ast_module_reload.
Since
12
Enumerator
AST_MODULE_RELOAD_SUCCESS
The module was reloaded succesfully
AST_MODULE_RELOAD_QUEUED
The module reload request was queued
AST_MODULE_RELOAD_NOT_FOUND
The requested module was not found
AST_MODULE_RELOAD_ERROR
An error occurred while reloading the module
AST_MODULE_RELOAD_IN_PROGRESS
A module reload request is already in progress
AST_MODULE_RELOAD_UNINITIALIZED
The module has not been initialized
AST_MODULE_RELOAD_NOT_IMPLEMENTED
This module doesn't support reloading
Definition at line 109 of file module.h.
{
    AST_MODULE_RELOAD_SUCCESS = 0,      /*!< The module was reloaded succesfully */
    AST_MODULE_RELOAD_QUEUED,           /*!< The module reload request was queued */
    AST_MODULE_RELOAD_NOT_FOUND,        /*!< The requested module was not found */
    AST_MODULE_RELOAD_ERROR,            /*!< An error occurred while reloading the module */
    AST_MODULE_RELOAD_IN_PROGRESS,      /*!< A module reload request is already in progress */
    AST_MODULE_RELOAD_UNINITIALIZED,    /*!< The module has not been initialized */
    AST_MODULE_RELOAD_NOT_IMPLEMENTED,  /*!< This module doesn't support reloading */
 };
ast_module_support_level
enum ast_module_support_level
Enumerator
AST_MODULE_SUPPORT_UNKNOWN
AST_MODULE_SUPPORT_CORE
AST_MODULE_SUPPORT_EXTENDED
AST_MODULE_SUPPORT_DEPRECATED
Definition at line 119 of file module.h.
{
    AST_MODULE_SUPPORT_UNKNOWN,
    AST_MODULE_SUPPORT_CORE,
    AST_MODULE_SUPPORT_EXTENDED,
    AST_MODULE_SUPPORT_DEPRECATED,
 };
ast_module_unload_mode
enum ast_module_unload_mode
Enumerator
AST_FORCE_SOFT
Softly unload a module, only if not in use
AST_FORCE_FIRM
Firmly unload a module, even if in use
AST_FORCE_HARD
as FIRM, plus dlclose() on the module. Not recommended as it may cause crashes
Definition at line 61 of file module.h.
{
    AST_FORCE_SOFT = 0, /*!< Softly unload a module, only if not in use */
    AST_FORCE_FIRM = 1, /*!< Firmly unload a module, even if in use */
    AST_FORCE_HARD = 2, /*!< as FIRM, plus dlclose() on the module. Not recommended
             as it may cause crashes */
 };
Function Documentation
__ast_module_ref()
struct ast_module* __ast_module_ref (struct ast_module * mod, const char * file, int line, const char * func)
Definition at line 2698 of file loader.c.
References __ao2_ref(), ast_atomic_fetchadd_int(), ast_update_use_count(), NULL, ast_module::ref_debug, and ast_module::usecount.
Referenced by __ast_module_running_ref(), and __ast_module_shutdown_ref().
 {
    if (!mod) {
       return NULL;
    }
    if (mod->ref_debug) {
       __ao2_ref(mod->ref_debug, +1, "", file, line, func);
    }
    ast_atomic_fetchadd_int(&mod->usecount, +1);
    ast_update_use_count();
    return mod;
 }
__ast_module_running_ref()
struct ast_module* __ast_module_running_ref (struct ast_module * mod, const char * file, int line, const char * func)
Definition at line 2714 of file loader.c.
References __ast_module_ref(), ast_module::flags, NULL, and ast_module::running.
 {
    if (!mod || !mod->flags.running) {
       return NULL;
    }
    return __ast_module_ref(mod, file, line, func);
 }
__ast_module_shutdown_ref()
void __ast_module_shutdown_ref (struct ast_module * mod, const char * file, int line, const char * func)
Definition at line 2724 of file loader.c.
References __ast_module_ref(), ast_module::flags, and ast_module::keepuntilshutdown.
 {
    if (!mod || mod->flags.keepuntilshutdown) {
       return;
    }
    __ast_module_ref(mod, file, line, func);
    mod->flags.keepuntilshutdown = 1;
 }
__ast_module_unref()
void __ast_module_unref (struct ast_module * mod, const char * file, int line, const char * func)
Definition at line 2734 of file loader.c.
References __ao2_ref(), ast_atomic_fetchadd_int(), ast_update_use_count(), ast_module::ref_debug, and ast_module::usecount.
 {
    if (!mod) {
       return;
    }
    if (mod->ref_debug) {
       __ao2_ref(mod->ref_debug, -1, "", file, line, func);
    }
    ast_atomic_fetchadd_int(&mod->usecount, -1);
    ast_update_use_count();
 }
__ast_module_user_add()
struct ast_module_user* __ast_module_user_add (struct ast_module * , struct ast_channel *)
Definition at line 800 of file loader.c.
References ao2_ref, ast_atomic_fetchadd_int(), ast_calloc, AST_LIST_INSERT_HEAD, AST_LIST_LOCK, AST_LIST_UNLOCK, ast_update_use_count(), ast_module_user::chan, NULL, ast_module::ref_debug, ast_module::usecount, and ast_module::users.
Referenced by ast_func_read(), ast_func_read2(), ast_func_write(), and pbx_exec().
 {
    struct ast_module_user *u;
    u = ast_calloc(1, sizeof(*u));
    if (!u) {
       return NULL;
    }
    u->chan = chan;
    AST_LIST_LOCK(&mod->users);
    AST_LIST_INSERT_HEAD(&mod->users, u, entry);
    AST_LIST_UNLOCK(&mod->users);
    if (mod->ref_debug) {
       ao2_ref(mod->ref_debug, +1);
    }
    ast_atomic_fetchadd_int(&mod->usecount, +1);
    ast_update_use_count();
    return u;
 }
__ast_module_user_hangup_all()
void __ast_module_user_hangup_all (struct ast_module *)
Definition at line 853 of file loader.c.
References ao2_ref, ast_atomic_fetchadd_int(), ast_free, AST_LIST_LOCK, AST_LIST_REMOVE_HEAD, AST_LIST_UNLOCK, ast_softhangup(), AST_SOFTHANGUP_APPUNLOAD, ast_update_use_count(), ast_module_user::chan, ast_module::ref_debug, ast_module::usecount, and ast_module::users.
Referenced by ast_unload_resource().
 {
    struct ast_module_user *u;
    AST_LIST_LOCK(&mod->users);
    while ((u = AST_LIST_REMOVE_HEAD(&mod->users, entry))) {
       if (u->chan) {
          ast_softhangup(u->chan, AST_SOFTHANGUP_APPUNLOAD);
       }
       if (mod->ref_debug) {
          ao2_ref(mod->ref_debug, -1);
       }
       ast_atomic_fetchadd_int(&mod->usecount, -1);
       ast_free(u);
    }
    AST_LIST_UNLOCK(&mod->users);
    ast_update_use_count();
 }
__ast_module_user_remove()
void __ast_module_user_remove (struct ast_module * , struct ast_module_user *)
Definition at line 826 of file loader.c.
References ao2_ref, ast_atomic_fetchadd_int(), ast_free, AST_LIST_LOCK, AST_LIST_REMOVE, AST_LIST_UNLOCK, ast_update_use_count(), ast_module::ref_debug, ast_module::usecount, and ast_module::users.
Referenced by ast_func_read(), ast_func_read2(), ast_func_write(), and pbx_exec().
 {
    if (!u) {
       return;
    }
    AST_LIST_LOCK(&mod->users);
    u = AST_LIST_REMOVE(&mod->users, u, entry);
    AST_LIST_UNLOCK(&mod->users);
    if (!u) {
       /*
        * Was not in the list.  Either a bad pointer or
        * __ast_module_user_hangup_all() has been called.
        */
       return;
    }
    if (mod->ref_debug) {
       ao2_ref(mod->ref_debug, -1);
    }
    ast_atomic_fetchadd_int(&mod->usecount, -1);
    ast_free(u);
    ast_update_use_count();
 }
ast_load_resource()
enum ast_module_load_result ast_load_resource (const char * resource_name)
Load a module.
Parameters
resource_name The name of the module to load.
This function is run by the PBX to load the modules. It performs all loading and initialization tasks. Basically, to load a module, just give it the name of the module and it will do the rest.
Returns
See possible enum values for ast_module_load_result.
Definition at line 1819 of file loader.c.
References AST_DLLIST_LOCK, AST_DLLIST_UNLOCK, ast_test_suite_event_notify, load_resource(), and NULL.
Referenced by ast_ari_asterisk_load_module(), handle_load(), and manager_moduleload().
 {
    int res;
    AST_DLLIST_LOCK(&module_list);
    res = load_resource(resource_name, 0, NULL, 0, 0);
    if (!res) {
       ast_test_suite_event_notify("MODULE_LOAD", "Message: %s", resource_name);
    }
    AST_DLLIST_UNLOCK(&module_list);
    return res;
 }
ast_loader_register()
int ast_loader_register (int(*)(void) updater)
Add a procedure to be run when modules have been updated.
Parameters
updater The function to run when modules have been updated.
This function adds the given function to a linked list of functions to be run when the modules are updated.
Return values
0 on success
-1 on failure.
Definition at line 2666 of file loader.c.
References AST_LIST_INSERT_HEAD, AST_LIST_LOCK, AST_LIST_UNLOCK, ast_malloc, tmp(), and loadupdate::updater.
 {
    struct loadupdate *tmp;
    if (!(tmp = ast_malloc(sizeof(*tmp))))
       return -1;
    tmp->updater = v;
    AST_LIST_LOCK(&updaters);
    AST_LIST_INSERT_HEAD(&updaters, tmp, entry);
    AST_LIST_UNLOCK(&updaters);
    return 0;
 }
ast_loader_unregister()
int ast_loader_unregister (int(*)(void) updater)
Remove a procedure to be run when modules are updated.
Parameters
updater The updater function to unregister.
This removes the given function from the updater list.
Return values
0 on success
-1 on failure.
Definition at line 2681 of file loader.c.
References AST_LIST_LOCK, AST_LIST_REMOVE_CURRENT, AST_LIST_TRAVERSE_SAFE_BEGIN, AST_LIST_TRAVERSE_SAFE_END, AST_LIST_UNLOCK, and loadupdate::updater.
 {
    struct loadupdate *cur;
    AST_LIST_LOCK(&updaters);
    AST_LIST_TRAVERSE_SAFE_BEGIN(&updaters, cur, entry) {
       if (cur->updater == v)  {
          AST_LIST_REMOVE_CURRENT(entry);
          break;
       }
    }
    AST_LIST_TRAVERSE_SAFE_END;
    AST_LIST_UNLOCK(&updaters);
    return cur ? 0 : -1;
 }
ast_module_check()
int ast_module_check (const char * name)
Check if module with the name given is loaded.
Parameters
name Module name, like "chan_sip.so"
Return values
1 if true
0 if false
Check if module with the name given is loaded.
Definition at line 2653 of file loader.c.
References ast_strlen_zero, find_resource(), and NULL.
Referenced by ast_ari_asterisk_get_module(), ast_ari_asterisk_load_module(), ast_ari_asterisk_reload_module(), ast_ari_asterisk_unload_module(), AST_TEST_DEFINE(), ifmodule_read(), and manager_modulecheck().
 {
    struct ast_module *cur;
    if (ast_strlen_zero(name))
       return 0;       /* FALSE */
    cur = find_resource(name, 1);
    return (cur != NULL);
 }
ast_module_helper()
char* ast_module_helper (const char * line, const char * word, int pos, int state, int rpos, enum ast_module_helper_type type)
Match modules names for the Asterisk cli.
Parameters
line Unused by this function, but this should be the line we are matching.
word The partial name to match.
pos The position the word we are completing is in.
state The possible match to return.
rpos The position we should be matching. This should be the same as pos.
type The type of action that will be performed by CLI.
Return values
A possible completion of the partial match.
NULL if no matches were found.
Definition at line 1374 of file loader.c.
References AST_DLLIST_LOCK, AST_DLLIST_TRAVERSE, AST_DLLIST_UNLOCK, AST_MODULE_HELPER_LOAD, ast_strdup, module_load_helper(), module_matches_helper_type(), NULL, and ast_module::resource.
Referenced by handle_debug(), handle_load(), handle_modlist(), handle_reload(), handle_trace(), and handle_unload().
 {
    struct ast_module *mod;
    int which = 0;
    int wordlen = strlen(word);
    char *ret = NULL;
    if (pos != rpos) {
       return NULL;
    }
    if (type == AST_MODULE_HELPER_LOAD) {
       module_load_helper(word);
       return NULL;
    }
    AST_DLLIST_LOCK(&module_list);
    AST_DLLIST_TRAVERSE(&module_list, mod, entry) {
       if (!module_matches_helper_type(mod, type)) {
          continue;
       }
       if (!strncasecmp(word, mod->resource, wordlen) && ++which > state) {
          ret = ast_strdup(mod->resource);
          break;
       }
    }
    AST_DLLIST_UNLOCK(&module_list);
    return ret;
 }
ast_module_name()
const char* ast_module_name (const struct ast_module * mod)
Get the name of a module.
Parameters
mod A pointer to the module.
Returns
the name of the module
Return values
NULL if mod or mod->info is NULL
Definition at line 615 of file loader.c.
References ast_module::info, ast_module_info::name, and NULL.
Referenced by acf_retrieve_docs(), ast_register_application2(), resource_list_recursive_decline(), start_resource_list(), and unload_dynamic_module().
 {
    if (!mod || !mod->info) {
       return NULL;
    }
    return mod->info->name;
 }
ast_module_register()
void ast_module_register (const struct ast_module_info *)
Definition at line 659 of file loader.c.
References AO2_ALLOC_OPT_LOCK_NOLOCK, ao2_find, ao2_link, ao2_ref, ao2_t_alloc_options, ast_debug, AST_DLLIST_INSERT_TAIL, AST_DLLIST_LOCK, AST_DLLIST_UNLOCK, AST_LIST_HEAD_INIT, ast_opt_ref_debug, ast_std_calloc(), AST_VECTOR_INIT, ast_module::builtin, builtin_module_list, ast_module::enhances, ast_module::flags, ast_module::info, sip_to_pjsip::info(), loader_ready, ast_module_info::name, NULL, OBJ_SEARCH_KEY, ast_module::optional_modules, ast_module::ref_debug, ast_module::reffed_deps, ast_module::requires, ast_module::resource, resource_being_loaded, ast_module_info::self, and ast_module::users.
Referenced by get_name_from_resource(), and loader_builtin_init().
 {
    struct ast_module *mod;
    if (!loader_ready) {
       mod = ast_std_calloc(1, sizeof(*mod) + strlen(info->name) + 1);
       if (!mod) {
          /* We haven't even reached main() yet, if we can't
           * allocate memory at this point just give up. */
          fprintf(stderr, "Allocation failure during startup.\n");
          exit(2);
       }
       strcpy(mod->resource, info->name); /* safe */
       mod->info = info;
       mod->flags.builtin = 1;
       AST_DLLIST_INSERT_TAIL(&builtin_module_list, mod, entry);
       /* ast_module_register for built-in modules is run again during module preload. */
       return;
    }
    /*
     * This lock protects resource_being_loaded as well as the module
     * list.  Normally we already have a lock on module_list when we
     * begin the load but locking again from here prevents corruption
     * if an asterisk module is dlopen'ed from outside the module loader.
     */
    AST_DLLIST_LOCK(&module_list);
    mod = resource_being_loaded;
    if (!mod) {
       AST_DLLIST_UNLOCK(&module_list);
       return;
    }
    ast_debug(5, "Registering module %s\n", info->name);
    /* This tells load_dynamic_module that we're registered. */
    resource_being_loaded = NULL;
    mod->info = info;
    if (ast_opt_ref_debug) {
       mod->ref_debug = ao2_t_alloc_options(0, NULL, AO2_ALLOC_OPT_LOCK_NOLOCK, info->name);
    }
    AST_LIST_HEAD_INIT(&mod->users);
    AST_VECTOR_INIT(&mod->requires, 0);
    AST_VECTOR_INIT(&mod->optional_modules, 0);
    AST_VECTOR_INIT(&mod->enhances, 0);
    AST_VECTOR_INIT(&mod->reffed_deps, 0);
    AST_DLLIST_INSERT_TAIL(&module_list, mod, entry);
    AST_DLLIST_UNLOCK(&module_list);
    /* give the module a copy of its own handle, for later use in registrations and the like */
    *((struct ast_module **) &(info->self)) = mod;
 #if defined(HAVE_PERMANENT_DLOPEN)
    if (mod->flags.builtin != 1) {
       struct info_list_obj *obj_tmp = ao2_find(info_list, info->name,
          OBJ_SEARCH_KEY);
       if (!obj_tmp) {
          obj_tmp = info_list_obj_alloc(info->name, info);
          if (obj_tmp) {
             ao2_link(info_list, obj_tmp);
             ao2_ref(obj_tmp, -1);
          }
       } else {
          ao2_ref(obj_tmp, -1);
       }
    }
 #endif
 }
ast_module_reload()
enum ast_module_reload_result ast_module_reload (const char * name)
Reload asterisk modules.
Parameters
name the name of the module to reload
This function reloads the specified module, or if no modules are specified, it will reload all loaded modules.
Note
Modules are reloaded using their reload() functions, not unloading them and loading them again.
Return values
The ast_module_reload_result status of the module load request
Definition at line 1562 of file loader.c.
References ast_config_AST_CONFIG_DIR, AST_DLLIST_LOCK, AST_DLLIST_TRAVERSE, AST_DLLIST_UNLOCK, ast_lastreloadtime, ast_lock_path(), AST_LOCK_SUCCESS, AST_LOCK_TIMEOUT, ast_log, AST_LOG_WARNING, AST_MODULE_LOAD_SUCCESS, AST_MODULE_RELOAD_ERROR, AST_MODULE_RELOAD_IN_PROGRESS, AST_MODULE_RELOAD_NOT_FOUND, AST_MODULE_RELOAD_NOT_IMPLEMENTED, AST_MODULE_RELOAD_QUEUED, AST_MODULE_RELOAD_SUCCESS, AST_MODULE_RELOAD_UNINITIALIZED, ast_mutex_trylock, ast_mutex_unlock, ast_opt_lock_confdir, ast_sd_notify(), ast_tvnow(), ast_unlock_path(), ast_verb, ast_module::declined, ast_module_info::description, ast_module::flags, ast_module::info, LOG_WARNING, publish_reload_message(), queue_reload_request(), ast_module_info::reload, reloadlock, ast_module::resource, resource_name_baselen(), resource_name_match(), and ast_module::running.
Referenced by action_reload(), action_updateconfig(), ast_ari_asterisk_reload_module(), ast_process_pending_reloads(), handle_cli_moh_reload(), handle_core_reload(), handle_reload(), manager_moduleload(), and monitor_sig_flags().
 {
    struct ast_module *cur;
    enum ast_module_reload_result res = AST_MODULE_RELOAD_NOT_FOUND;
    size_t name_baselen = name ? resource_name_baselen(name) : 0;
    /* If we aren't fully booted, we just pretend we reloaded but we queue this
       up to run once we are booted up. */
    if (!modules_loaded) {
       queue_reload_request(name);
       res = AST_MODULE_RELOAD_QUEUED;
       goto module_reload_exit;
    }
    if (ast_mutex_trylock(&reloadlock)) {
       ast_verb(3, "The previous reload command didn't finish yet\n");
       res = AST_MODULE_RELOAD_IN_PROGRESS;
       goto module_reload_exit;
    }
    ast_sd_notify("RELOAD=1");
    ast_lastreloadtime = ast_tvnow();
    if (ast_opt_lock_confdir) {
       int try;
       int lockres;
       for (try = 1, lockres = AST_LOCK_TIMEOUT; try < 6 && (lockres == AST_LOCK_TIMEOUT); try++) {
          lockres = ast_lock_path(ast_config_AST_CONFIG_DIR);
          if (lockres == AST_LOCK_TIMEOUT) {
             ast_log(LOG_WARNING, "Failed to grab lock on %s, try %d\n", ast_config_AST_CONFIG_DIR, try);
          }
       }
       if (lockres != AST_LOCK_SUCCESS) {
          ast_log(AST_LOG_WARNING, "Cannot grab lock on %s\n", ast_config_AST_CONFIG_DIR);
          res = AST_MODULE_RELOAD_ERROR;
          goto module_reload_done;
       }
    }
    AST_DLLIST_LOCK(&module_list);
    AST_DLLIST_TRAVERSE(&module_list, cur, entry) {
       const struct ast_module_info *info = cur->info;
       if (name && resource_name_match(name, name_baselen, cur->resource)) {
          continue;
       }
       if (!cur->flags.running || cur->flags.declined) {
          if (res == AST_MODULE_RELOAD_NOT_FOUND) {
             res = AST_MODULE_RELOAD_UNINITIALIZED;
          }
          if (!name) {
             continue;
          }
          break;
       }
       if (!info->reload) { /* cannot be reloaded */
          if (res == AST_MODULE_RELOAD_NOT_FOUND) {
             res = AST_MODULE_RELOAD_NOT_IMPLEMENTED;
          }
          if (!name) {
             continue;
          }
          break;
       }
       ast_verb(3, "Reloading module '%s' (%s)\n", cur->resource, info->description);
       if (info->reload() == AST_MODULE_LOAD_SUCCESS) {
          res = AST_MODULE_RELOAD_SUCCESS;
       } else if (res == AST_MODULE_RELOAD_NOT_FOUND) {
          res = AST_MODULE_RELOAD_ERROR;
       }
       if (name) {
          break;
       }
    }
    AST_DLLIST_UNLOCK(&module_list);
    if (ast_opt_lock_confdir) {
       ast_unlock_path(ast_config_AST_CONFIG_DIR);
    }
 module_reload_done:
    ast_mutex_unlock(&reloadlock);
    ast_sd_notify("READY=1");
 module_reload_exit:
    publish_reload_message(name, res);
    return res;
 }
ast_module_support_level_to_string()
const char* ast_module_support_level_to_string (enum ast_module_support_level support_level)
Definition at line 2755 of file loader.c.
Referenced by identify_module(), modlist_modentry(), and process_module_list().
 {
    return support_level_map[support_level];
 }
ast_module_unregister()
void ast_module_unregister (const struct ast_module_info *)
Definition at line 768 of file loader.c.
References ast_cli_unregister_multiple(), ast_debug, AST_DLLIST_LOCK, AST_DLLIST_REMOVE_CURRENT, AST_DLLIST_TRAVERSE_BACKWARDS_SAFE_BEGIN, AST_DLLIST_TRAVERSE_BACKWARDS_SAFE_END, AST_DLLIST_UNLOCK, ast_module::info, module_destroy(), ast_module_info::name, NULL, and ast_module::usecount.
Referenced by get_name_from_resource().
 {
    struct ast_module *mod = NULL;
    /* it is assumed that the users list in the module structure
       will already be empty, or we cannot have gotten to this
       point
    */
    AST_DLLIST_LOCK(&module_list);
    AST_DLLIST_TRAVERSE_BACKWARDS_SAFE_BEGIN(&module_list, mod, entry) {
       if (mod->info == info) {
          AST_DLLIST_REMOVE_CURRENT(entry);
          break;
       }
    }
    AST_DLLIST_TRAVERSE_BACKWARDS_SAFE_END;
    AST_DLLIST_UNLOCK(&module_list);
    if (mod && !mod->usecount) {
       /*
        * We are intentionally leaking mod if usecount is not zero.
        * This is necessary if the module is being forcefully unloaded.
        * In addition module_destroy is not safe to run after exit()
        * is called.  ast_module_unregister is run during cleanup of
        * the process when libc releases each module's shared object
        * library.
        */
       ast_debug(5, "Unregistering module %s\n", info->name);
       module_destroy(mod);
    }
 }
ast_register_application2()
int ast_register_application2 (const char * app, int(*)(struct ast_channel *, const char *) execute, const char * synopsis, const char * description, void * mod)
Register an application.
Parameters
app Short name of the application
execute a function callback to execute the application. It should return non-zero if the channel needs to be hung up.
synopsis a short description (one line synopsis) of the application
description long description with all of the details about the use of the application
mod module this application belongs to
This registers an application with Asterisk's internal application list.
Note
The individual applications themselves are responsible for registering and unregistering and unregistering their own CLI commands.
Return values
0 success
-1 failure.
Register an application.
Definition at line 103 of file pbx_app.c.
References ast_app::arguments, ast_calloc, ast_free, ast_log, ast_module_name(), AST_RWLIST_INSERT_BEFORE_CURRENT, AST_RWLIST_INSERT_TAIL, AST_RWLIST_TRAVERSE_SAFE_BEGIN, AST_RWLIST_TRAVERSE_SAFE_END, AST_RWLIST_UNLOCK, AST_RWLIST_WRLOCK, AST_STATIC_DOC, ast_string_field_init, ast_string_field_set, ast_strlen_zero, ast_verb, AST_XML_DOC, ast_xmldoc_build_arguments(), ast_xmldoc_build_description(), ast_xmldoc_build_seealso(), ast_xmldoc_build_synopsis(), ast_xmldoc_build_syntax(), COLOR_BRCYAN, COLORIZE, COLORIZE_FMT, ast_app::docsrc, ast_app::execute, LOG_WARNING, pbx_findapp_nolock(), ast_app::seealso, ast_app::syntax, and tmp().
Referenced by ast_msg_init(), load_module(), load_pbx_builtins(), and load_pbx_variables().
 {
    struct ast_app *tmp;
    struct ast_app *cur;
    int length;
 #ifdef AST_XML_DOCS
    char *tmpxml;
 #endif
    AST_RWLIST_WRLOCK(&apps);
    cur = pbx_findapp_nolock(app);
    if (cur) {
       ast_log(LOG_WARNING, "Already have an application '%s'\n", app);
       AST_RWLIST_UNLOCK(&apps);
       return -1;
    }
    length = sizeof(*tmp) + strlen(app) + 1;
    if (!(tmp = ast_calloc(1, length))) {
       AST_RWLIST_UNLOCK(&apps);
       return -1;
    }
    if (ast_string_field_init(tmp, 128)) {
       AST_RWLIST_UNLOCK(&apps);
       ast_free(tmp);
       return -1;
    }
    strcpy(tmp->name, app);
    tmp->execute = execute;
    tmp->module = mod;
 #ifdef AST_XML_DOCS
    /* Try to lookup the docs in our XML documentation database */
    if (ast_strlen_zero(synopsis) && ast_strlen_zero(description)) {
       /* load synopsis */
       tmpxml = ast_xmldoc_build_synopsis("application", app, ast_module_name(tmp->module));
       ast_string_field_set(tmp, synopsis, tmpxml);
       ast_free(tmpxml);
       /* load description */
       tmpxml = ast_xmldoc_build_description("application", app, ast_module_name(tmp->module));
       ast_string_field_set(tmp, description, tmpxml);
       ast_free(tmpxml);
       /* load syntax */
       tmpxml = ast_xmldoc_build_syntax("application", app, ast_module_name(tmp->module));
       ast_string_field_set(tmp, syntax, tmpxml);
       ast_free(tmpxml);
       /* load arguments */
       tmpxml = ast_xmldoc_build_arguments("application", app, ast_module_name(tmp->module));
       ast_string_field_set(tmp, arguments, tmpxml);
       ast_free(tmpxml);
       /* load seealso */
       tmpxml = ast_xmldoc_build_seealso("application", app, ast_module_name(tmp->module));
       ast_string_field_set(tmp, seealso, tmpxml);
       ast_free(tmpxml);
       tmp->docsrc = AST_XML_DOC;
    } else {
 #endif
       ast_string_field_set(tmp, synopsis, synopsis);
       ast_string_field_set(tmp, description, description);
 #ifdef AST_XML_DOCS
       tmp->docsrc = AST_STATIC_DOC;
    }
 #endif
    /* Store in alphabetical order */
    AST_RWLIST_TRAVERSE_SAFE_BEGIN(&apps, cur, list) {
       if (strcasecmp(tmp->name, cur->name) < 0) {
          AST_RWLIST_INSERT_BEFORE_CURRENT(tmp, list);
          break;
       }
    }
    AST_RWLIST_TRAVERSE_SAFE_END;
    if (!cur)
       AST_RWLIST_INSERT_TAIL(&apps, tmp, list);
    ast_verb(2, "Registered application '" COLORIZE_FMT "'\n", COLORIZE(COLOR_BRCYAN, 0, tmp->name));
    AST_RWLIST_UNLOCK(&apps);
    return 0;
 }
ast_unload_resource()
int ast_unload_resource (const char * resource_name, enum ast_module_unload_mode)
Unload a module.
Parameters
resource_name The name of the module to unload.
ast_module_unload_mode The force flag. This should be set using one of the AST_FORCE flags.
This function unloads a module. It will only unload modules that are not in use (usecount not zero), unless AST_FORCE_FIRM or AST_FORCE_HARD is specified. Setting AST_FORCE_FIRM or AST_FORCE_HARD will unload the module regardless of consequences (NOT RECOMMENDED).
Return values
0 on success.
-1 on error.
Definition at line 1229 of file loader.c.
References __ast_module_user_hangup_all(), AST_DLLIST_LOCK, AST_DLLIST_UNLOCK, AST_FORCE_FIRM, ast_log, ast_test_suite_event_notify, ast_update_use_count(), ast_verb, ast_module::declined, error(), find_resource(), ast_module::flags, ast_module::info, LOG_WARNING, publish_unload_message(), ast_module::resource, ast_module::running, ast_module_info::unload, unload_dynamic_module(), and ast_module::usecount.
Referenced by ast_ari_asterisk_unload_module(), handle_unload(), manager_moduleload(), and unload_module().
 {
    struct ast_module *mod;
    int res = -1;
    int error = 0;
    AST_DLLIST_LOCK(&module_list);
    if (!(mod = find_resource(resource_name, 0))) {
       AST_DLLIST_UNLOCK(&module_list);
       ast_log(LOG_WARNING, "Unload failed, '%s' could not be found\n", resource_name);
       return -1;
    }
    if (!mod->flags.running || mod->flags.declined) {
       ast_log(LOG_WARNING, "Unload failed, '%s' is not loaded.\n", resource_name);
       error = 1;
    }
    if (!error && (mod->usecount > 0)) {
       if (force)
          ast_log(LOG_WARNING, "Warning:  Forcing removal of module '%s' with use count %d\n",
             resource_name, mod->usecount);
       else {
          ast_log(LOG_WARNING, "Soft unload failed, '%s' has use count %d\n", resource_name,
             mod->usecount);
          error = 1;
       }
    }
    if (!error) {
       /* Request any channels attached to the module to hangup. */
       __ast_module_user_hangup_all(mod);
       ast_verb(1, "Unloading %s\n", mod->resource);
       res = mod->info->unload();
       if (res) {
          ast_log(LOG_WARNING, "Firm unload failed for %s\n", resource_name);
          if (force <= AST_FORCE_FIRM) {
             error = 1;
          } else {
             ast_log(LOG_WARNING, "** Dangerous **: Unloading resource anyway, at user request\n");
          }
       }
       if (!error) {
          /*
           * Request hangup on any channels that managed to get attached
           * while we called the module unload function.
           */
          __ast_module_user_hangup_all(mod);
          sched_yield();
       }
    }
    if (!error)
       mod->flags.running = mod->flags.declined = 0;
    AST_DLLIST_UNLOCK(&module_list);
    if (!error) {
       unload_dynamic_module(mod);
       ast_test_suite_event_notify("MODULE_UNLOAD", "Message: %s", resource_name);
       ast_update_use_count();
       publish_unload_message(resource_name, "Success");
    }
    return res;
 }
ast_unregister_application()
int ast_unregister_application (const char * app)
Unregister an application.
Parameters
app name of the application (does not have to be the same string as the one that was registered)
This unregisters an application from Asterisk's internal application list.
Return values
0 success
-1 failure
Definition at line 392 of file pbx_app.c.
References ast_free, ast_rdlock_contexts(), AST_RWLIST_REMOVE_CURRENT, AST_RWLIST_TRAVERSE_SAFE_BEGIN, AST_RWLIST_TRAVERSE_SAFE_END, AST_RWLIST_UNLOCK, AST_RWLIST_WRLOCK, ast_string_field_free_memory, ast_unlock_contexts(), ast_verb, NULL, and unreference_cached_app().
Referenced by __unload_module(), load_module(), message_shutdown(), unload_module(), unload_parking_applications(), unload_pbx_builtins(), and unload_pbx_variables().
 {
    struct ast_app *cur;
    int cmp;
    /* Anticipate need for conlock in unreference_cached_app(), in order to avoid
     * possible deadlock with pbx_extension_helper()/pbx_findapp()
     */
    ast_rdlock_contexts();
    AST_RWLIST_WRLOCK(&apps);
    AST_RWLIST_TRAVERSE_SAFE_BEGIN(&apps, cur, list) {
       cmp = strcasecmp(app, cur->name);
       if (cmp > 0) {
          continue;
       }
       if (!cmp) {
          /* Found it. */
          unreference_cached_app(cur);
          AST_RWLIST_REMOVE_CURRENT(list);
          ast_verb(2, "Unregistered application '%s'\n", cur->name);
          ast_string_field_free_memory(cur);
          ast_free(cur);
          break;
       }
       /* Not in container. */
       cur = NULL;
       break;
    }
    AST_RWLIST_TRAVERSE_SAFE_END;
    AST_RWLIST_UNLOCK(&apps);
    ast_unlock_contexts();
    return cur ? 0 : -1;
 }
ast_update_module_list()
int ast_update_module_list (int(*)(const char *module, const char *description, int usecnt, const char *status, const char *like, enum ast_module_support_level support_level) modentry, const char * like)
Ask for a list of modules, descriptions, use counts and status.
Parameters
modentry A callback to an updater function.
like For each of the modules loaded, modentry will be executed with the resource, description, and usecount values of each particular module.
Returns
the number of modules loaded
Definition at line 2567 of file loader.c.
References alpha_module_list_create(), AST_DLLIST_LOCK, AST_DLLIST_UNLOCK, AST_VECTOR_FREE, AST_VECTOR_GET, AST_VECTOR_SIZE, ast_module_info::description, ast_module::flags, ast_module::info, ast_module::resource, ast_module::running, ast_module_info::support_level, and ast_module::usecount.
Referenced by ast_var_Modules(), and handle_modlist().
 {
    int total_mod_loaded = 0;
    struct module_vector alpha_module_list;
    AST_DLLIST_LOCK(&module_list);
    if (!alpha_module_list_create(&alpha_module_list)) {
       int idx;
       for (idx = 0; idx < AST_VECTOR_SIZE(&alpha_module_list); idx++) {
          struct ast_module *cur = AST_VECTOR_GET(&alpha_module_list, idx);
          total_mod_loaded += modentry(cur->resource, cur->info->description, cur->usecount,
             cur->flags.running ? "Running" : "Not Running", like, cur->info->support_level);
       }
    }
    AST_DLLIST_UNLOCK(&module_list);
    AST_VECTOR_FREE(&alpha_module_list);
    return total_mod_loaded;
 }
ast_update_module_list_condition()
int ast_update_module_list_condition (int(*)(const char *module, const char *description, int usecnt, const char *status, const char *like, enum ast_module_support_level support_level, void *data, const char *condition) modentry, const char * like, void * data, const char * condition)
Ask for a list of modules, descriptions, use counts and status.
Parameters
modentry A callback to an updater function
like
data Data passed into the callback for manipulation
condition The condition to meet
For each of the modules loaded, modentry will be executed with the resource, description, and usecount values of each particular module.
Returns
the number of conditions met
Since
13.5.0
Definition at line 2622 of file loader.c.
References alpha_module_list_create(), AST_DLLIST_LOCK, AST_DLLIST_UNLOCK, AST_VECTOR_FREE, AST_VECTOR_GET, AST_VECTOR_SIZE, ast_module_info::description, ast_module::flags, ast_module::info, ast_module::resource, ast_module::running, ast_module_info::support_level, and ast_module::usecount.
Referenced by ast_ari_asterisk_get_module().
 {
    int conditions_met = 0;
    struct module_vector alpha_module_list;
    AST_DLLIST_LOCK(&module_list);
    if (!alpha_module_list_create(&alpha_module_list)) {
       int idx;
       for (idx = 0; idx < AST_VECTOR_SIZE(&alpha_module_list); idx++) {
          struct ast_module *cur = AST_VECTOR_GET(&alpha_module_list, idx);
          conditions_met += modentry(cur->resource, cur->info->description, cur->usecount,
             cur->flags.running? "Running" : "Not Running", like, cur->info->support_level, data,
             condition);
       }
    }
    AST_DLLIST_UNLOCK(&module_list);
    AST_VECTOR_FREE(&alpha_module_list);
    return conditions_met;
 }
ast_update_module_list_data()
int ast_update_module_list_data (int(*)(const char *module, const char *description, int usecnt, const char *status, const char *like, enum ast_module_support_level support_level, void *data) modentry, const char * like, void * data)
Ask for a list of modules, descriptions, use counts and status.
Parameters
modentry A callback to an updater function
like
data Data passed into the callback for manipulation
For each of the modules loaded, modentry will be executed with the resource, description, and usecount values of each particular module.
Returns
the number of modules loaded
Since
13.5.0
Definition at line 2594 of file loader.c.
References alpha_module_list_create(), AST_DLLIST_LOCK, AST_DLLIST_UNLOCK, AST_VECTOR_FREE, AST_VECTOR_GET, AST_VECTOR_SIZE, ast_module_info::description, ast_module::flags, ast_module::info, ast_module::resource, ast_module::running, ast_module_info::support_level, and ast_module::usecount.
Referenced by ast_ari_asterisk_list_modules().
 {
    int total_mod_loaded = 0;
    struct module_vector alpha_module_list;
    AST_DLLIST_LOCK(&module_list);
    if (!alpha_module_list_create(&alpha_module_list)) {
       int idx;
       for (idx = 0; idx < AST_VECTOR_SIZE(&alpha_module_list); idx++) {
          struct ast_module *cur = AST_VECTOR_GET(&alpha_module_list, idx);
          total_mod_loaded += modentry(cur->resource, cur->info->description, cur->usecount,
             cur->flags.running? "Running" : "Not Running", like, cur->info->support_level, data);
       }
    }
    AST_DLLIST_UNLOCK(&module_list);
    AST_VECTOR_FREE(&alpha_module_list);
    return total_mod_loaded;
 }
ast_update_use_count()
void ast_update_use_count (void)
Notify when usecount has been changed.
This function calulates use counts and notifies anyone trying to keep track of them. It should be called whenever your module's usecount changes.
Note
The ast_module_user_* functions take care of calling this function for you.
Definition at line 2528 of file loader.c.
References AST_LIST_LOCK, AST_LIST_TRAVERSE, AST_LIST_UNLOCK, and loadupdate::updater.
Referenced by __ast_module_ref(), __ast_module_unref(), __ast_module_user_add(), __ast_module_user_hangup_all(), __ast_module_user_remove(), ast_unload_resource(), handle_request_do(), ooh323_hangup(), ooh323_new(), ooh323c_call_thread(), sip_request_call(), start_resource(), and unistim_new().
 {
    /* Notify any module monitors that the use count for a
       resource has changed */
    struct loadupdate *m;
    AST_LIST_LOCK(&updaters);
    AST_LIST_TRAVERSE(&updaters, m, entry)
       m->updater();
    AST_LIST_UNLOCK(&updaters);
 }
Variable Documentation
ast_module_info
const struct ast_module_info* ast_module_info static
Definition at line 540 of file module.h.