Asterisk - The Open Source Telephony Project: conf_state.h File Reference
conf_state.h File Reference
Confbridge state handling.
Data Structures
struct confbridge_state
A conference state object to hold the various state callback functions.
Typedefs
typedef void(* conference_entry_fn) (struct confbridge_user *user)
typedef void(* conference_event_fn) (struct confbridge_user *user)
typedef void(* conference_exit_fn) (struct confbridge_user *user)
Functions
void conf_change_state (struct confbridge_user *user, struct confbridge_state *newstate)
Execute conference state transition because of a user action.
void conf_default_join_waitmarked (struct confbridge_user *user)
Logic to execute every time a waitmarked user joins an unmarked conference.
void conf_default_leave_waitmarked (struct confbridge_user *user)
Logic to execute every time a waitmarked user leaves an unmarked conference.
void conf_invalid_event_fn (struct confbridge_user *user)
A handler for join/leave events that are invalid in a particular state.
Variables
struct confbridge_state * CONF_STATE_EMPTY
Conference state with no active or waiting users.
struct confbridge_state * CONF_STATE_INACTIVE
Conference state with only waiting users.
struct confbridge_state * CONF_STATE_MULTI
Conference state with multiple active users, but no marked users.
struct confbridge_state * CONF_STATE_MULTI_MARKED
Conference state with multiple active users and at least one marked user.
struct confbridge_state * CONF_STATE_SINGLE
Conference state with only a single unmarked active user.
struct confbridge_state * CONF_STATE_SINGLE_MARKED
Conference state with only a single marked active user.
Detailed Description
Confbridge state handling.
Author
Terry Wilson <twilson@digium.com>
See https://wiki.asterisk.org/wiki/display/AST/Confbridge+state+changes for a more complete description of how conference states work.
Definition in file conf_state.h.
Typedef Documentation
conference_entry_fn
typedef void(* conference_entry_fn) (struct confbridge_user *user)
Definition at line 44 of file conf_state.h.
conference_event_fn
typedef void(* conference_event_fn) (struct confbridge_user *user)
Definition at line 43 of file conf_state.h.
conference_exit_fn
typedef void(* conference_exit_fn) (struct confbridge_user *user)
Definition at line 45 of file conf_state.h.
Function Documentation
conf_change_state()
void conf_change_state (struct confbridge_user * user, struct confbridge_state * newstate)
Execute conference state transition because of a user action.
Parameters
user The user that joined/left
newstate The state to transition to
Definition at line 82 of file conf_state.c.
References ast_debug, ast_test_suite_event_notify, confbridge_user::conference, confbridge_state::entry, confbridge_state::exit, confbridge_state::name, confbridge_conference::name, and confbridge_conference::state.
Referenced by join_active(), join_marked(), join_unmarked(), join_waitmarked(), leave_active(), leave_marked(), leave_unmarked(), and leave_waitmarked().
 {
    ast_debug(1, "Changing conference '%s' state from %s to %s\n", user->conference->name, user->conference->state->name, newstate->name);
    ast_test_suite_event_notify("CONF_CHANGE_STATE", "Conference: %s\r\nOldState: %s\r\nNewState: %s\r\n",
          user->conference->name,
          user->conference->state->name,
          newstate->name);
    if (user->conference->state->exit) {
       user->conference->state->exit(user);
    }
    user->conference->state = newstate;
    if (user->conference->state->entry) {
       user->conference->state->entry(user);
    }
 }
conf_default_join_waitmarked()
void conf_default_join_waitmarked (struct confbridge_user * user)
Logic to execute every time a waitmarked user joins an unmarked conference.
Definition at line 67 of file conf_state.c.
References conf_add_post_join_action(), conf_add_user_waiting(), conf_handle_inactive_waitmarked(), conf_mute_moh_inactive_waitmarked(), and confbridge_user::conference.
Referenced by join_waitmarked().
 {
    conf_add_user_waiting(user->conference, user);
    conf_mute_moh_inactive_waitmarked(user);
    conf_add_post_join_action(user, conf_handle_inactive_waitmarked);
 }
conf_default_leave_waitmarked()
void conf_default_leave_waitmarked (struct confbridge_user * user)
Logic to execute every time a waitmarked user leaves an unmarked conference.
Definition at line 74 of file conf_state.c.
References conf_moh_stop(), conf_remove_user_waiting(), confbridge_user::conference, and confbridge_user::playing_moh.
Referenced by leave_waitmarked().
 {
    conf_remove_user_waiting(user->conference, user);
    if (user->playing_moh) {
       conf_moh_stop(user);
    }
 }
conf_invalid_event_fn()
void conf_invalid_event_fn (struct confbridge_user * user)
A handler for join/leave events that are invalid in a particular state.
Definition at line 45 of file conf_state.c.
References ast_log, LOG_ERROR, user_profile::name, and confbridge_user::u_profile.
Referenced by handle_conf_user_join(), and handle_conf_user_leave().
 {
    ast_log(LOG_ERROR, "Invalid event for confbridge user '%s'\n", user->u_profile.name);
 }
Variable Documentation
CONF_STATE_EMPTY
struct confbridge_state* CONF_STATE_EMPTY
Conference state with no active or waiting users.
Definition at line 53 of file conf_state_empty.c.
Referenced by join_conference_bridge(), leave_marked(), leave_unmarked(), and leave_waitmarked().
CONF_STATE_INACTIVE
struct confbridge_state* CONF_STATE_INACTIVE
Conference state with only waiting users.
Definition at line 49 of file conf_state_inactive.c.
Referenced by join_waitmarked(), leave_marked(), and leave_unmarked().
CONF_STATE_MULTI
struct confbridge_state* CONF_STATE_MULTI
Conference state with multiple active users, but no marked users.
Definition at line 50 of file conf_state_multi.c.
Referenced by join_unmarked(), and leave_marked().
CONF_STATE_MULTI_MARKED
struct confbridge_state* CONF_STATE_MULTI_MARKED
Conference state with multiple active users and at least one marked user.
Definition at line 59 of file conf_state_multi_marked.c.
Referenced by join_active(), and join_marked().
CONF_STATE_SINGLE
struct confbridge_state* CONF_STATE_SINGLE
Conference state with only a single unmarked active user.
Definition at line 52 of file conf_state_single.c.
Referenced by join_unmarked(), leave_marked(), and leave_unmarked().
CONF_STATE_SINGLE_MARKED
struct confbridge_state* CONF_STATE_SINGLE_MARKED
Conference state with only a single marked active user.
Definition at line 51 of file conf_state_single_marked.c.
Referenced by join_marked(), leave_active(), and leave_marked().