Asterisk - The Open Source Telephony Project: app_record.c File Reference
app_record.c File Reference
Dial plan applications
Trivial application to record a sound file.
#include "asterisk.h"
#include "asterisk/file.h"
#include "asterisk/pbx.h"
#include "asterisk/module.h"
#include "asterisk/app.h"
#include "asterisk/channel.h"
#include "asterisk/dsp.h"
#include "asterisk/format_cache.h"
#include "asterisk/paths.h"
Macros
#define OPERATOR_KEY '0'
Enumerations
enum {
OPTION_APPEND = (1 << 0), OPTION_NOANSWER = (1 << 1), OPTION_QUIET = (1 << 2), OPTION_SKIP = (1 << 3),
OPTION_STAR_TERMINATE = (1 << 4), OPTION_IGNORE_TERMINATE = (1 << 5), OPTION_KEEP = (1 << 6), OPTION_ANY_TERMINATE = (1 << 7),
OPTION_OPERATOR_EXIT = (1 << 8), OPTION_NO_TRUNCATE = (1 << 9)
}
enum dtmf_response { RESPONSE_NO_MATCH = 0, RESPONSE_OPERATOR, RESPONSE_DTMF }
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int create_destination_directory (const char *path)
static int load_module (void)
static enum dtmf_response record_dtmf_response (struct ast_channel *chan, struct ast_flags *flags, int dtmf_integer, int terminator)
static int record_exec (struct ast_channel *chan, const char *data)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Trivial Record Application" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, }
static char * app = "Record"
static const struct ast_app_option app_opts [128] = { [ 'a' ] = { .flag = OPTION_APPEND }, [ 'k' ] = { .flag = OPTION_KEEP }, [ 'n' ] = { .flag = OPTION_NOANSWER }, [ 'o' ] = { .flag = OPTION_OPERATOR_EXIT }, [ 'q' ] = { .flag = OPTION_QUIET }, [ 's' ] = { .flag = OPTION_SKIP }, [ 't' ] = { .flag = OPTION_STAR_TERMINATE }, [ 'u' ] = { .flag = OPTION_NO_TRUNCATE }, [ 'y' ] = { .flag = OPTION_ANY_TERMINATE }, [ 'x' ] = { .flag = OPTION_IGNORE_TERMINATE }, }
static const struct ast_module_info * ast_module_info = &__mod_info
Detailed Description
Trivial application to record a sound file.
Author
Matthew Fredrickson cresl.nosp@m.in@d.nosp@m.igium.nosp@m..com
Definition in file app_record.c.
Macro Definition Documentation
OPERATOR_KEY
#define OPERATOR_KEY '0'
Definition at line 123 of file app_record.c.
Referenced by record_dtmf_response().
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
OPTION_APPEND
OPTION_NOANSWER
OPTION_QUIET
OPTION_SKIP
OPTION_STAR_TERMINATE
OPTION_IGNORE_TERMINATE
OPTION_KEEP
OPTION_ANY_TERMINATE
OPTION_OPERATOR_EXIT
OPTION_NO_TRUNCATE
Definition at line 127 of file app_record.c.
      {
    OPTION_APPEND = (1 << 0),
    OPTION_NOANSWER = (1 << 1),
    OPTION_QUIET = (1 << 2),
    OPTION_SKIP = (1 << 3),
    OPTION_STAR_TERMINATE = (1 << 4),
    OPTION_IGNORE_TERMINATE = (1 << 5),
    OPTION_KEEP = (1 << 6),
    OPTION_ANY_TERMINATE = (1 << 7),
    OPTION_OPERATOR_EXIT = (1 << 8),
    OPTION_NO_TRUNCATE = (1 << 9),
 };
dtmf_response
enum dtmf_response
Enumerator
RESPONSE_NO_MATCH
RESPONSE_OPERATOR
RESPONSE_DTMF
Definition at line 140 of file app_record.c.
                    {
    RESPONSE_NO_MATCH = 0,
    RESPONSE_OPERATOR,
    RESPONSE_DTMF,
 };
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 543 of file app_record.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 543 of file app_record.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 543 of file app_record.c.
create_destination_directory()
static int create_destination_directory (const char * path) static
Definition at line 187 of file app_record.c.
References ast_config_AST_DATA_DIR, ast_mkdir(), and PATH_MAX.
Referenced by record_exec().
 {
    int res;
    char directory[PATH_MAX], *file_sep;
    if (!(file_sep = strrchr(path, '/'))) {
       /* No directory to create */
       return 0;
    }
    /* Overwrite temporarily */
    *file_sep = '\0';
    /* Absolute path? */
    if (path[0] == '/') {
       res = ast_mkdir(path, 0777);
       *file_sep = '/';
       return res;
    }
    /* Relative path */
    res = snprintf(directory, sizeof(directory), "%s/sounds/%s",
                ast_config_AST_DATA_DIR, path);
    *file_sep = '/';
    if (res >= sizeof(directory)) {
       /* We truncated, so we fail */
       return -1;
    }
    return ast_mkdir(directory, 0777);
 }
load_module()
static int load_module (void) static
Definition at line 538 of file app_record.c.
References app, ast_register_application_xml, and record_exec().
 {
    return ast_register_application_xml(app, record_exec);
 }
record_dtmf_response()
static enum dtmf_response record_dtmf_response (struct ast_channel * chan, struct ast_flags * flags, int dtmf_integer, int terminator) static
Definition at line 171 of file app_record.c.
References ast_test_flag, OPERATOR_KEY, OPTION_ANY_TERMINATE, OPTION_OPERATOR_EXIT, RESPONSE_DTMF, RESPONSE_NO_MATCH, and RESPONSE_OPERATOR.
Referenced by record_exec().
 {
    if ((dtmf_integer == OPERATOR_KEY) &&
       (ast_test_flag(flags, OPTION_OPERATOR_EXIT))) {
       return RESPONSE_OPERATOR;
    }
    if ((dtmf_integer == terminator) ||
       (ast_test_flag(flags, OPTION_ANY_TERMINATE))) {
       return RESPONSE_DTMF;
    }
    return RESPONSE_NO_MATCH;
 }
record_exec()
static int record_exec (struct ast_channel * chan, const char * data) static
Definition at line 221 of file app_record.c.
References ao2_bump, ao2_cleanup, app_opts, args, ast_answer(), AST_APP_ARG, ast_app_parse_options(), ast_channel_language(), ast_channel_name(), ast_channel_readformat(), ast_channel_start_silence_generator(), ast_channel_stop_silence_generator(), ast_closestream(), AST_CONTROL_VIDUPDATE, ast_copy_string(), ast_debug, AST_DECLARE_APP_ARGS, ast_dsp_free(), ast_dsp_get_threshold_from_settings(), ast_dsp_new(), ast_dsp_set_threshold(), ast_dsp_silence(), AST_FILE_MODE, ast_filedelete(), ast_fileexists(), ast_format_slin, AST_FRAME_DTMF, AST_FRAME_VIDEO, AST_FRAME_VOICE, ast_frfree, ast_indicate(), ast_log, ast_opt_transmit_silence, ast_read(), ast_remaining_ms(), ast_set_read_format(), AST_STANDARD_APP_ARGS, AST_STATE_UP, ast_stopstream(), ast_strdupa, ast_stream_rewind(), ast_streamfile(), ast_strlen_zero, ast_test_flag, ast_truncstream(), ast_tvnow(), ast_waitfor(), ast_waitstream(), ast_writefile(), ast_writestream(), create_destination_directory(), ext, ast_frame::frametype, ast_frame_subclass::integer, LOG_WARNING, NULL, OPTION_APPEND, OPTION_IGNORE_TERMINATE, OPTION_KEEP, OPTION_NO_TRUNCATE, OPTION_NOANSWER, OPTION_QUIET, OPTION_SKIP, OPTION_STAR_TERMINATE, options, out, parse(), PATH_MAX, pbx_builtin_setvar_helper(), RAII_VAR, record_dtmf_response(), RESPONSE_DTMF, RESPONSE_NO_MATCH, RESPONSE_OPERATOR, ast_frame::subclass, THRESHOLD_SILENCE, tmp(), and ast_dsp::totalsilence.
Referenced by load_module().
 {
    int res = 0;
    char *ext = NULL, *opts[0];
    char *parse;
    int i = 0;
    char tmp[PATH_MAX];
    struct ast_filestream *s = NULL;
    struct ast_frame *f = NULL;
    struct ast_dsp *sildet = NULL;      /* silence detector dsp */
    int totalsilence = 0;
    int dspsilence = 0;
    int silence = 0;     /* amount of silence to allow */
    int gotsilence = 0;     /* did we timeout for silence? */
    int truncate_silence = 1;  /* truncate on complete silence recording */
    int maxduration = 0;    /* max duration of recording in milliseconds */
    int gottimeout = 0;     /* did we timeout for maxduration exceeded? */
    int terminator = '#';
    RAII_VAR(struct ast_format *, rfmt, NULL, ao2_cleanup);
    int ioflags;
    struct ast_silence_generator *silgen = NULL;
    struct ast_flags flags = { 0, };
    AST_DECLARE_APP_ARGS(args,
       AST_APP_ARG(filename);
       AST_APP_ARG(silence);
       AST_APP_ARG(maxduration);
       AST_APP_ARG(options);
    );
    int ms;
    struct timeval start;
    const char *status_response = "ERROR";
    /* The next few lines of code parse out the filename and header from the input string */
    if (ast_strlen_zero(data)) { /* no data implies no filename or anything is present */
       ast_log(LOG_WARNING, "Record requires an argument (filename)\n");
       pbx_builtin_setvar_helper(chan, "RECORD_STATUS", "ERROR");
       return -1;
    }
    parse = ast_strdupa(data);
    AST_STANDARD_APP_ARGS(args, parse);
    if (args.argc == 4)
       ast_app_parse_options(app_opts, &flags, opts, args.options);
    if (!ast_strlen_zero(args.filename)) {
       ext = strrchr(args.filename, '.'); /* to support filename with a . in the filename, not format */
       if (!ext)
          ext = strchr(args.filename, ':');
       if (ext) {
          *ext = '\0';
          ext++;
       }
    }
    if (!ext) {
       ast_log(LOG_WARNING, "No extension specified to filename!\n");
       pbx_builtin_setvar_helper(chan, "RECORD_STATUS", "ERROR");
       return -1;
    }
    if (args.silence) {
       if ((sscanf(args.silence, "%30d", &i) == 1) && (i > -1)) {
          silence = i * 1000;
       } else if (!ast_strlen_zero(args.silence)) {
          ast_log(LOG_WARNING, "'%s' is not a valid silence duration\n", args.silence);
       }
    }
    if (ast_test_flag(&flags, OPTION_NO_TRUNCATE))
       truncate_silence = 0;
    if (args.maxduration) {
       if ((sscanf(args.maxduration, "%30d", &i) == 1) && (i > -1))
          /* Convert duration to milliseconds */
          maxduration = i * 1000;
       else if (!ast_strlen_zero(args.maxduration))
          ast_log(LOG_WARNING, "'%s' is not a valid maximum duration\n", args.maxduration);
    }
    if (ast_test_flag(&flags, OPTION_STAR_TERMINATE))
       terminator = '*';
    if (ast_test_flag(&flags, OPTION_IGNORE_TERMINATE))
       terminator = '\0';
    /*
      If a '%d' is specified as part of the filename, we replace that token with
      sequentially incrementing numbers until we find a unique filename.
    */
    if (strchr(args.filename, '%')) {
       size_t src, dst, count = 0;
       size_t src_len = strlen(args.filename);
       size_t dst_len = sizeof(tmp) - 1;
       do {
          for (src = 0, dst = 0; src < src_len && dst < dst_len; src++) {
             if (!strncmp(&args.filename[src], "%d", 2)) {
                int s = snprintf(&tmp[dst], PATH_MAX - dst, "%zu", count);
                if (s >= PATH_MAX - dst) {
                   /* We truncated, so we need to bail */
                   ast_log(LOG_WARNING, "Failed to create unique filename from template: %s\n", args.filename);
                   pbx_builtin_setvar_helper(chan, "RECORD_STATUS", "ERROR");
                   return -1;
                }
                dst += s;
                src++;
             } else {
                tmp[dst] = args.filename[src];
                tmp[++dst] = '\0';
             }
          }
          count++;
       } while (ast_fileexists(tmp, ext, ast_channel_language(chan)) > 0);
    } else
       ast_copy_string(tmp, args.filename, sizeof(tmp));
    pbx_builtin_setvar_helper(chan, "RECORDED_FILE", tmp);
    if (ast_channel_state(chan) != AST_STATE_UP) {
       if (ast_test_flag(&flags, OPTION_SKIP)) {
          /* At the user's option, skip if the line is not up */
          pbx_builtin_setvar_helper(chan, "RECORD_STATUS", "SKIP");
          return 0;
       } else if (!ast_test_flag(&flags, OPTION_NOANSWER)) {
          /* Otherwise answer unless we're supposed to record while on-hook */
          res = ast_answer(chan);
       }
    }
    if (res) {
       ast_log(LOG_WARNING, "Could not answer channel '%s'\n", ast_channel_name(chan));
       status_response = "ERROR";
       goto out;
    }
    if (!ast_test_flag(&flags, OPTION_QUIET)) {
       /* Some code to play a nice little beep to signify the start of the record operation */
       res = ast_streamfile(chan, "beep", ast_channel_language(chan));
       if (!res) {
          res = ast_waitstream(chan, "");
       } else {
          ast_log(LOG_WARNING, "ast_streamfile(beep) failed on %s\n", ast_channel_name(chan));
          res = 0;
       }
       ast_stopstream(chan);
    }
    /* The end of beep code.  Now the recording starts */
    if (silence > 0) {
       rfmt = ao2_bump(ast_channel_readformat(chan));
       res = ast_set_read_format(chan, ast_format_slin);
       if (res < 0) {
          ast_log(LOG_WARNING, "Unable to set to linear mode, giving up\n");
          pbx_builtin_setvar_helper(chan, "RECORD_STATUS", "ERROR");
          return -1;
       }
       sildet = ast_dsp_new();
       if (!sildet) {
          ast_log(LOG_WARNING, "Unable to create silence detector :(\n");
          pbx_builtin_setvar_helper(chan, "RECORD_STATUS", "ERROR");
          return -1;
       }
       ast_dsp_set_threshold(sildet, ast_dsp_get_threshold_from_settings(THRESHOLD_SILENCE));
    }
    if (create_destination_directory(tmp)) {
       ast_log(LOG_WARNING, "Could not create directory for file %s\n", args.filename);
       status_response = "ERROR";
       goto out;
    }
    ioflags = ast_test_flag(&flags, OPTION_APPEND) ? O_CREAT|O_APPEND|O_WRONLY : O_CREAT|O_TRUNC|O_WRONLY;
    s = ast_writefile(tmp, ext, NULL, ioflags, 0, AST_FILE_MODE);
    if (!s) {
       ast_log(LOG_WARNING, "Could not create file %s\n", args.filename);
       status_response = "ERROR";
       goto out;
    }
    if (ast_opt_transmit_silence)
       silgen = ast_channel_start_silence_generator(chan);
    /* Request a video update */
    ast_indicate(chan, AST_CONTROL_VIDUPDATE);
    if (maxduration <= 0)
       maxduration = -1;
    start = ast_tvnow();
    while ((ms = ast_remaining_ms(start, maxduration))) {
       ms = ast_waitfor(chan, ms);
       if (ms < 0) {
          break;
       }
       if (maxduration > 0 && ms == 0) {
          break;
       }
       f = ast_read(chan);
       if (!f) {
          res = -1;
          break;
       }
       if (f->frametype == AST_FRAME_VOICE) {
          res = ast_writestream(s, f);
          if (res) {
             ast_log(LOG_WARNING, "Problem writing frame\n");
             ast_frfree(f);
             status_response = "ERROR";
             break;
          }
          if (silence > 0) {
             dspsilence = 0;
             ast_dsp_silence(sildet, f, &dspsilence);
             if (dspsilence) {
                totalsilence = dspsilence;
             } else {
                totalsilence = 0;
             }
             if (totalsilence > silence) {
                /* Ended happily with silence */
                ast_frfree(f);
                gotsilence = 1;
                status_response = "SILENCE";
                break;
             }
          }
       } else if (f->frametype == AST_FRAME_VIDEO) {
          res = ast_writestream(s, f);
          if (res) {
             ast_log(LOG_WARNING, "Problem writing frame\n");
             status_response = "ERROR";
             ast_frfree(f);
             break;
          }
       } else if (f->frametype == AST_FRAME_DTMF) {
          enum dtmf_response rc =
             record_dtmf_response(chan, &flags, f->subclass.integer, terminator);
          switch(rc)  {
          case RESPONSE_NO_MATCH:
             break;
          case RESPONSE_OPERATOR:
             status_response = "OPERATOR";
             ast_debug(1, "Got OPERATOR\n");
             break;
          case RESPONSE_DTMF:
             status_response = "DTMF";
             ast_debug(1, "Got DTMF\n");
             break;
          }
          if (rc != RESPONSE_NO_MATCH) {
             ast_frfree(f);
             break;
          }
       }
       ast_frfree(f);
    }
    if (maxduration > 0 && !ms) {
       gottimeout = 1;
       status_response = "TIMEOUT";
    }
    if (!f) {
       ast_debug(1, "Got hangup\n");
       res = -1;
       status_response = "HANGUP";
       if (!ast_test_flag(&flags, OPTION_KEEP)) {
          ast_filedelete(args.filename, NULL);
       }
    }
    if (gotsilence && truncate_silence) {
       ast_stream_rewind(s, silence - 1000);
       ast_truncstream(s);
    } else if (!gottimeout && f) {
       /*
        * Strip off the last 1/4 second of it, if we didn't end because of a timeout,
        * or a hangup.  This must mean we ended because of a DTMF tone and while this
        * 1/4 second stripping is very old code the most likely explanation is that it
        * relates to stripping a partial DTMF tone.
        */
       ast_stream_rewind(s, 250);
       ast_truncstream(s);
    }
    ast_closestream(s);
    if (silgen)
       ast_channel_stop_silence_generator(chan, silgen);
 out:
    if ((silence > 0) && rfmt) {
       res = ast_set_read_format(chan, rfmt);
       if (res) {
          ast_log(LOG_WARNING, "Unable to restore read format on '%s'\n", ast_channel_name(chan));
       }
    }
    if (sildet) {
       ast_dsp_free(sildet);
    }
    pbx_builtin_setvar_helper(chan, "RECORD_STATUS", status_response);
    return res;
 }
unload_module()
static int unload_module (void) static
Definition at line 533 of file app_record.c.
References app, and ast_unregister_application().
 {
    return ast_unregister_application(app);
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Trivial Record Application" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, } static
Definition at line 543 of file app_record.c.
app
char* app = "Record" static
Definition at line 125 of file app_record.c.
Referenced by load_module(), and unload_module().
app_opts
const struct ast_app_option app_opts[128] = { [ 'a' ] = { .flag = OPTION_APPEND }, [ 'k' ] = { .flag = OPTION_KEEP }, [ 'n' ] = { .flag = OPTION_NOANSWER }, [ 'o' ] = { .flag = OPTION_OPERATOR_EXIT }, [ 'q' ] = { .flag = OPTION_QUIET }, [ 's' ] = { .flag = OPTION_SKIP }, [ 't' ] = { .flag = OPTION_STAR_TERMINATE }, [ 'u' ] = { .flag = OPTION_NO_TRUNCATE }, [ 'y' ] = { .flag = OPTION_ANY_TERMINATE }, [ 'x' ] = { .flag = OPTION_IGNORE_TERMINATE }, } static
Definition at line 157 of file app_record.c.
Referenced by record_exec().
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 543 of file app_record.c.