Asterisk - The Open Source Telephony Project: res_pjsip_logger.c File Reference
res_pjsip_logger.c File Reference
#include "asterisk.h"
#include <netinet/in.h>
#include <pjsip.h>
#include "asterisk/res_pjsip.h"
#include "asterisk/module.h"
#include "asterisk/logger.h"
#include "asterisk/cli.h"
#include "asterisk/netsock2.h"
#include "asterisk/acl.h"
Data Structures
struct pcap_ethernet_header
PCAP Ethernet Header.
struct pcap_header
PCAP Header.
struct pcap_ipv4_header
PCAP IPv4 Header.
struct pcap_ipv6_header
PCAP IPv6 Header.
struct pcap_record_header
PCAP Packet Record Header.
struct pcap_udp_header
PCAP UDP Header.
struct pjsip_logger_session
PJSIP Logging Session.
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static void check_debug (void)
static void global_reloaded (const char *object_type)
static int load_module (void)
static pj_bool_t logging_on_rx_msg (pjsip_rx_data *rdata)
static pj_status_t logging_on_tx_msg (pjsip_tx_data *tdata)
static char * pjsip_disable_logger (int fd)
static char * pjsip_enable_logger_all (int fd)
static char * pjsip_enable_logger_host (int fd, const char *arg, unsigned int add_host)
static int pjsip_log_test_addr (const struct pjsip_logger_session *session, const char *address, int port)
See if we pass debug IP filter.
static struct pjsip_logger_session * pjsip_logger_session_alloc (void)
Allocator for logger session.
static void pjsip_logger_session_destroy (void *obj)
Destructor for logger session.
static void pjsip_logger_write_to_pcap (struct pjsip_logger_session *session, const char *msg, size_t msg_len, pj_sockaddr *source, pj_sockaddr *destination)
static char * pjsip_set_logger (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static char * pjsip_set_logger_pcap (int fd, const char *arg)
static char * pjsip_set_logger_verbose (int fd, const char *arg)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "PJSIP Packet Logger" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_APP_DEPEND, .requires = "res_pjsip", }
static const struct ast_module_info * ast_module_info = &__mod_info
static struct ast_cli_entry cli_pjsip []
static struct pjsip_logger_session * default_logger
The default logger session.
static const struct ast_sorcery_observer global_observer
static pjsip_module logging_module
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 586 of file res_pjsip_logger.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 586 of file res_pjsip_logger.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 586 of file res_pjsip_logger.c.
check_debug()
static void check_debug (void) static
Definition at line 514 of file res_pjsip_logger.c.
References ast_false(), ast_free, ast_log, ast_sip_get_debug(), ast_true(), CLI_SUCCESS, debug, LOG_WARNING, pjsip_disable_logger(), pjsip_enable_logger_all(), pjsip_enable_logger_host(), and RAII_VAR.
Referenced by global_reloaded(), and load_module().
 {
    RAII_VAR(char *, debug, ast_sip_get_debug(), ast_free);
    if (ast_false(debug)) {
       pjsip_disable_logger(-1);
       return;
    }
    if (ast_true(debug)) {
       pjsip_enable_logger_all(-1);
       return;
    }
    if (pjsip_enable_logger_host(-1, debug, 0) != CLI_SUCCESS) {
       ast_log(LOG_WARNING, "Could not resolve host %s for debug "
          "logging\n", debug);
    }
 }
global_reloaded()
static void global_reloaded (const char * object_type) static
Definition at line 534 of file res_pjsip_logger.c.
References check_debug().
 {
    check_debug();
 }
load_module()
static int load_module (void) static
Definition at line 543 of file res_pjsip_logger.c.
References ARRAY_LEN, ast_cli_register_multiple, ast_log, AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, ast_sip_get_sorcery(), ast_sip_register_service(), ast_sorcery_observer_add(), ast_sorcery_observer_remove(), check_debug(), LOG_WARNING, and pjsip_logger_session_alloc().
Referenced by unload_module().
 {
    if (ast_sorcery_observer_add(ast_sip_get_sorcery(), "global", &global_observer)) {
       ast_log(LOG_WARNING, "Unable to add global observer\n");
       return AST_MODULE_LOAD_DECLINE;
    }
    default_logger = pjsip_logger_session_alloc();
    if (!default_logger) {
       ast_sorcery_observer_remove(
          ast_sip_get_sorcery(), "global", &global_observer);
       ast_log(LOG_WARNING, "Unable to create default logger\n");
       return AST_MODULE_LOAD_DECLINE;
    }
    check_debug();
    ast_sip_register_service(&logging_module);
    ast_cli_register_multiple(cli_pjsip, ARRAY_LEN(cli_pjsip));
    return AST_MODULE_LOAD_SUCCESS;
 }
logging_on_rx_msg()
static pj_bool_t logging_on_rx_msg (pjsip_rx_data * rdata) static
Definition at line 296 of file res_pjsip_logger.c.
References ao2_rdlock, ao2_unlock, AST_SOCKADDR_BUFLEN, ast_verbose(), pjsip_logger_session::log_to_pcap, pjsip_logger_session::log_to_verbose, NULL, pjsip_log_test_addr(), and pjsip_logger_write_to_pcap().
 {
    char buffer[AST_SOCKADDR_BUFLEN];
    if (!rdata->msg_info.msg) {
       return PJ_FALSE;
    }
    ao2_rdlock(default_logger);
    if (!pjsip_log_test_addr(default_logger, rdata->pkt_info.src_name, rdata->pkt_info.src_port)) {
       ao2_unlock(default_logger);
       return PJ_FALSE;
    }
    ao2_unlock(default_logger);
    if (default_logger->log_to_verbose) {
       ast_verbose("<--- Received SIP %s (%d bytes) from %s:%s --->\n%s\n",
          rdata->msg_info.msg->type == PJSIP_REQUEST_MSG ? "request" : "response",
          rdata->msg_info.len,
          rdata->tp_info.transport->type_name,
          pj_sockaddr_print(&rdata->pkt_info.src_addr, buffer, sizeof(buffer), 3),
          rdata->pkt_info.packet);
    }
    if (default_logger->log_to_pcap) {
       pjsip_logger_write_to_pcap(default_logger, rdata->pkt_info.packet, rdata->msg_info.len,
          &rdata->pkt_info.src_addr, NULL);
    }
    return PJ_FALSE;
 }
logging_on_tx_msg()
static pj_status_t logging_on_tx_msg (pjsip_tx_data * tdata) static
Definition at line 268 of file res_pjsip_logger.c.
References ao2_rdlock, ao2_unlock, AST_SOCKADDR_BUFLEN, ast_verbose(), pjsip_logger_session::log_to_pcap, pjsip_logger_session::log_to_verbose, NULL, pjsip_log_test_addr(), and pjsip_logger_write_to_pcap().
 {
    char buffer[AST_SOCKADDR_BUFLEN];
    ao2_rdlock(default_logger);
    if (!pjsip_log_test_addr(default_logger, tdata->tp_info.dst_name, tdata->tp_info.dst_port)) {
       ao2_unlock(default_logger);
       return PJ_SUCCESS;
    }
    ao2_unlock(default_logger);
    if (default_logger->log_to_verbose) {
       ast_verbose("<--- Transmitting SIP %s (%d bytes) to %s:%s --->\n%.*s\n",
          tdata->msg->type == PJSIP_REQUEST_MSG ? "request" : "response",
          (int) (tdata->buf.cur - tdata->buf.start),
          tdata->tp_info.transport->type_name,
          pj_sockaddr_print(&tdata->tp_info.dst_addr, buffer, sizeof(buffer), 3),
          (int) (tdata->buf.end - tdata->buf.start), tdata->buf.start);
    }
    if (default_logger->log_to_pcap) {
       pjsip_logger_write_to_pcap(default_logger, tdata->buf.start, (int) (tdata->buf.cur - tdata->buf.start),
          NULL, &tdata->tp_info.dst_addr);
    }
    return PJ_SUCCESS;
 }
pjsip_disable_logger()
static char* pjsip_disable_logger (int fd) static
Definition at line 396 of file res_pjsip_logger.c.
References ao2_unlock, ao2_wrlock, ast_cli(), ast_free_ha(), CLI_SUCCESS, pjsip_logger_session::enabled, pjsip_logger_session::log_all_traffic, pjsip_logger_session::log_to_pcap, pjsip_logger_session::log_to_verbose, pjsip_logger_session::matches, NULL, pjsip_logger_session::pcap_file, and pjsip_logger_session::pcap_filename.
Referenced by check_debug(), and pjsip_set_logger().
 {
    ao2_wrlock(default_logger);
    /* Default the settings back to the way they were */
    default_logger->enabled = 0;
    default_logger->log_all_traffic = 0;
    default_logger->pcap_filename[0] = '\0';
    default_logger->log_to_verbose = 1;
    default_logger->log_to_pcap = 0;
    /* Stop logging to the PCAP file if active */
    if (default_logger->pcap_file) {
       fclose(default_logger->pcap_file);
       default_logger->pcap_file = NULL;
    }
    ast_free_ha(default_logger->matches);
    default_logger->matches = NULL;
    ao2_unlock(default_logger);
    if (fd >= 0) {
       ast_cli(fd, "PJSIP Logging disabled\n");
    }
    return CLI_SUCCESS;
 }
pjsip_enable_logger_all()
static char* pjsip_enable_logger_all (int fd) static
Definition at line 337 of file res_pjsip_logger.c.
References ao2_unlock, ao2_wrlock, ast_cli(), CLI_SUCCESS, pjsip_logger_session::enabled, and pjsip_logger_session::log_all_traffic.
Referenced by check_debug(), and pjsip_set_logger().
 {
    ao2_wrlock(default_logger);
    default_logger->enabled = 1;
    default_logger->log_all_traffic = 1;
    ao2_unlock(default_logger);
    if (fd >= 0) {
       ast_cli(fd, "PJSIP Logging enabled\n");
    }
    return CLI_SUCCESS;
 }
pjsip_enable_logger_host()
static char* pjsip_enable_logger_host (int fd, const char * arg, unsigned int add_host) static
Definition at line 351 of file res_pjsip_logger.c.
References ao2_unlock, ao2_wrlock, AST_AF_UNSPEC, ast_append_ha_with_port(), ast_cli(), ast_free_ha(), ast_sockaddr_parse(), ast_sockaddr_resolve_first_af(), ast_sockaddr_stringify(), ast_sockaddr_stringify_addr(), CLI_SHOWUSAGE, CLI_SUCCESS, pjsip_logger_session::enabled, error(), host, pjsip_logger_session::matches, and NULL.
Referenced by check_debug(), and pjsip_set_logger().
 {
    const char *host = arg;
    char *mask;
    struct ast_sockaddr address;
    int error = 0;
    ao2_wrlock(default_logger);
    default_logger->enabled = 1;
    if (!add_host) {
       /* If this is not adding an additional host or subnet then we have to
        * remove what already exists.
        */
       ast_free_ha(default_logger->matches);
       default_logger->matches = NULL;
    }
    mask = strrchr(host, '/');
    if (!mask && !ast_sockaddr_parse(&address, arg, 0)) {
       if (ast_sockaddr_resolve_first_af(&address, arg, 0, AST_AF_UNSPEC)) {
          ao2_unlock(default_logger);
          return CLI_SHOWUSAGE;
       }
       host = ast_sockaddr_stringify(&address);
    }
    default_logger->matches = ast_append_ha_with_port("d", host, default_logger->matches, &error);
    if (!default_logger->matches || error) {
       if (fd >= 0) {
          ast_cli(fd, "Failed to add address '%s' for logging\n", host);
       }
       ao2_unlock(default_logger);
       return CLI_SUCCESS;
    }
    ao2_unlock(default_logger);
    if (fd >= 0) {
       ast_cli(fd, "PJSIP Logging Enabled for host: %s\n", ast_sockaddr_stringify_addr(&address));
    }
    return CLI_SUCCESS;
 }
pjsip_log_test_addr()
static int pjsip_log_test_addr (const struct pjsip_logger_session * session, const char * address, int port) inline static
See if we pass debug IP filter.
Definition at line 152 of file res_pjsip_logger.c.
References ast_apply_ha(), AST_SENSE_ALLOW, ast_sockaddr_parse(), ast_sockaddr_set_port, ast_strlen_zero, pjsip_logger_session::enabled, pjsip_logger_session::log_all_traffic, pjsip_logger_session::matches, and PARSE_PORT_IGNORE.
Referenced by logging_on_rx_msg(), and logging_on_tx_msg().
 {
    struct ast_sockaddr test_addr;
    if (!session->enabled) {
       return 0;
    }
    if (session->log_all_traffic) {
       return 1;
    }
    /* A null address was passed in or no explicit matches. Just reject it. */
    if (ast_strlen_zero(address) || !session->matches) {
       return 0;
    }
    ast_sockaddr_parse(&test_addr, address, PARSE_PORT_IGNORE);
    ast_sockaddr_set_port(&test_addr, port);
    /* Compare the address against the matches */
    if (ast_apply_ha(session->matches, &test_addr) != AST_SENSE_ALLOW) {
       return 1;
    } else {
       return 0;
    }
 }
pjsip_logger_session_alloc()
static struct pjsip_logger_session* pjsip_logger_session_alloc (void) static
Allocator for logger session.
Definition at line 136 of file res_pjsip_logger.c.
References AO2_ALLOC_OPT_LOCK_RWLOCK, ao2_alloc_options, pjsip_logger_session::log_to_verbose, NULL, pjsip_logger_session_destroy(), and session.
Referenced by load_module().
 {
    struct pjsip_logger_session *session;
    session = ao2_alloc_options(sizeof(struct pjsip_logger_session), pjsip_logger_session_destroy,
       AO2_ALLOC_OPT_LOCK_RWLOCK);
    if (!session) {
       return NULL;
    }
    session->log_to_verbose = 1;
    return session;
 }
pjsip_logger_session_destroy()
static void pjsip_logger_session_destroy (void * obj) static
Destructor for logger session.
Definition at line 124 of file res_pjsip_logger.c.
References ast_free_ha(), pjsip_logger_session::matches, pjsip_logger_session::pcap_file, and session.
Referenced by pjsip_logger_session_alloc().
 {
    struct pjsip_logger_session *session = obj;
    if (session->pcap_file) {
       fclose(session->pcap_file);
    }
    ast_free_ha(session->matches);
 }
pjsip_logger_write_to_pcap()
static void pjsip_logger_write_to_pcap (struct pjsip_logger_session * session, const char * msg, size_t msg_len, pj_sockaddr * source, pj_sockaddr * destination) static
Definition at line 180 of file res_pjsip_logger.c.
References ao2_unlock, ao2_wrlock, ast_log, ast_tvnow(), pcap_udp_header::dst, errno, pcap_record_header::incl_len, pcap_ipv6_header::ip6_ctlun, pcap_ipv6_header::ip6_dst, pcap_ipv6_header::ip6_src, pcap_ipv6_header::ip6_un1, pcap_ipv6_header::ip6_un2_vfc, pcap_ipv4_header::ip_dst, pcap_ipv4_header::ip_len, pcap_ipv4_header::ip_protocol, pcap_ipv4_header::ip_src, pcap_udp_header::length, LOG_WARNING, pcap_record_header::orig_len, pjsip_logger_session::pcap_file, pcap_udp_header::src, pcap_record_header::ts_sec, pcap_ethernet_header::type, and pcap_ipv4_header::ver_ihl.
Referenced by logging_on_rx_msg(), and logging_on_tx_msg().
 {
    struct timeval now = ast_tvnow();
    struct pcap_record_header pcap_record_header = {
       .ts_sec = now.tv_sec,
       .ts_usec = now.tv_usec,
    };
    struct pcap_ethernet_header pcap_ethernet_header = {
       .type = 0,
    };
    struct pcap_ipv4_header pcap_ipv4_header = {
       .ver_ihl = 0x45, /* IPv4 + 20 bytes of header */
       .ip_ttl = 128, /* We always put a TTL of 128 to keep Wireshark less blue */
    };
    struct pcap_ipv6_header pcap_ipv6_header = {
       .ip6_ctlun.ip6_un2_vfc = 0x60,
    };
    void *pcap_ip_header;
    size_t pcap_ip_header_len;
    struct pcap_udp_header pcap_udp_header;
    /* Packets are always stored as UDP to simplify this logic */
    if (source) {
       pcap_udp_header.src = ntohs(pj_sockaddr_get_port(source));
    } else {
       pcap_udp_header.src = ntohs(0);
    }
    if (destination) {
       pcap_udp_header.dst = ntohs(pj_sockaddr_get_port(destination));
    } else {
       pcap_udp_header.dst = ntohs(0);
    }
    pcap_udp_header.length = ntohs(sizeof(struct pcap_udp_header) + msg_len);
    /* Construct the appropriate IP header */
    if ((source && source->addr.sa_family == pj_AF_INET()) ||
       (destination && destination->addr.sa_family == pj_AF_INET())) {
       pcap_ethernet_header.type = htons(0x0800); /* We are providing an IPv4 packet */
       pcap_ip_header = &pcap_ipv4_header;
       pcap_ip_header_len = sizeof(struct pcap_ipv4_header);
       if (source) {
          memcpy(&pcap_ipv4_header.ip_src, pj_sockaddr_get_addr(source), pj_sockaddr_get_addr_len(source));
       }
       if (destination) {
          memcpy(&pcap_ipv4_header.ip_dst, pj_sockaddr_get_addr(destination), pj_sockaddr_get_addr_len(destination));
       }
       pcap_ipv4_header.ip_len = htons(sizeof(struct pcap_udp_header) + sizeof(struct pcap_ipv4_header) + msg_len);
       pcap_ipv4_header.ip_protocol = IPPROTO_UDP; /* We always provide UDP */
    } else {
       pcap_ethernet_header.type = htons(0x86DD); /* We are providing an IPv6 packet */
       pcap_ip_header = &pcap_ipv6_header;
       pcap_ip_header_len = sizeof(struct pcap_ipv6_header);
       if (source) {
          memcpy(&pcap_ipv6_header.ip6_src, pj_sockaddr_get_addr(source), pj_sockaddr_get_addr_len(source));
       }
       if (destination) {
          memcpy(&pcap_ipv6_header.ip6_dst, pj_sockaddr_get_addr(destination), pj_sockaddr_get_addr_len(destination));
       }
       pcap_ipv6_header.ip6_ctlun.ip6_un1.ip6_un1_plen = htons(sizeof(struct pcap_udp_header) + msg_len);
       pcap_ipv6_header.ip6_ctlun.ip6_un1.ip6_un1_nxt = IPPROTO_UDP;
    }
    /* Add up all the sizes for this record */
    pcap_record_header.incl_len = pcap_record_header.orig_len = sizeof(pcap_ethernet_header) + pcap_ip_header_len + sizeof(pcap_udp_header) + msg_len;
    /* We lock the logger session since we're writing these out in parts */
    ao2_wrlock(session);
    if (session->pcap_file) {
       if (fwrite(&pcap_record_header, sizeof(struct pcap_record_header), 1, session->pcap_file) != 1) {
          ast_log(LOG_WARNING, "Writing PCAP header failed: %s\n", strerror(errno));
       }
       if (fwrite(&pcap_ethernet_header, sizeof(struct pcap_ethernet_header), 1, session->pcap_file) != 1) {
          ast_log(LOG_WARNING, "Writing ethernet header to pcap failed: %s\n", strerror(errno));
       }
       if (fwrite(pcap_ip_header, pcap_ip_header_len, 1, session->pcap_file) != 1) {
          ast_log(LOG_WARNING, "Writing IP header to pcap failed: %s\n", strerror(errno));
       }
       if (fwrite(&pcap_udp_header, sizeof(struct pcap_udp_header), 1, session->pcap_file) != 1) {
          ast_log(LOG_WARNING, "Writing UDP header to pcap failed: %s\n", strerror(errno));
       }
       if (fwrite(msg, msg_len, 1, session->pcap_file) != 1) {
          ast_log(LOG_WARNING, "Writing UDP payload to pcap failed: %s\n", strerror(errno));
       }
    }
    ao2_unlock(session);
 }
pjsip_set_logger()
static char* pjsip_set_logger (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) static
Definition at line 470 of file res_pjsip_logger.c.
References ast_cli_args::argc, ast_cli_entry::args, ast_cli_args::argv, CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, ast_cli_entry::command, ast_cli_args::fd, NULL, pjsip_disable_logger(), pjsip_enable_logger_all(), pjsip_enable_logger_host(), pjsip_set_logger_pcap(), pjsip_set_logger_verbose(), and ast_cli_entry::usage.
 {
    const char *what;
    if (cmd == CLI_INIT) {
       e->command = "pjsip set logger {on|off|host|add|verbose|pcap}";
       e->usage =
          "Usage: pjsip set logger {on|off|host <name/subnet>|add <name/subnet>|verbose <on/off>|pcap <filename>}\n"
          "       Enables or disabling logging of SIP packets\n"
          "       read on ports bound to PJSIP transports either\n"
          "       globally or enables logging for an individual\n"
          "       host.\n";
       return NULL;
    } else if (cmd == CLI_GENERATE) {
       return NULL;
    }
    what = a->argv[e->args - 1];     /* Guaranteed to exist */
    if (a->argc == e->args) {        /* on/off */
       if (!strcasecmp(what, "on")) {
          return pjsip_enable_logger_all(a->fd);
       } else if (!strcasecmp(what, "off")) {
          return pjsip_disable_logger(a->fd);
       }
    } else if (a->argc == e->args + 1) {
       if (!strcasecmp(what, "host")) {
          return pjsip_enable_logger_host(a->fd, a->argv[e->args], 0);
       } else if (!strcasecmp(what, "add")) {
          return pjsip_enable_logger_host(a->fd, a->argv[e->args], 1);
       } else if (!strcasecmp(what, "verbose")) {
          return pjsip_set_logger_verbose(a->fd, a->argv[e->args]);
       } else if (!strcasecmp(what, "pcap")) {
          return pjsip_set_logger_pcap(a->fd, a->argv[e->args]);
       }
    }
    return CLI_SHOWUSAGE;
 }
pjsip_set_logger_pcap()
static char* pjsip_set_logger_pcap (int fd, const char * arg) static
Definition at line 436 of file res_pjsip_logger.c.
References ao2_unlock, ao2_wrlock, ast_cli(), ast_copy_string(), CLI_SUCCESS, pjsip_logger_session::log_to_pcap, pcap_header::magic_number, NULL, pjsip_logger_session::pcap_file, and pjsip_logger_session::pcap_filename.
Referenced by pjsip_set_logger().
 {
    struct pcap_header pcap_header = {
       .magic_number = 0xa1b2c3d4,
       .version_major = 2,
       .version_minor = 4,
       .snaplen = 65535,
       .network = 1, /* We always use ethernet so we can combine IPv4 and IPv6 in same pcap */
    };
    ao2_wrlock(default_logger);
    ast_copy_string(default_logger->pcap_filename, arg, sizeof(default_logger->pcap_filename));
    if (default_logger->pcap_file) {
       fclose(default_logger->pcap_file);
       default_logger->pcap_file = NULL;
    }
    default_logger->pcap_file = fopen(arg, "wb");
    if (!default_logger->pcap_file) {
       ao2_unlock(default_logger);
       ast_cli(fd, "Failed to open file '%s' for pcap writing\n", arg);
       return CLI_SUCCESS;
    }
    fwrite(&pcap_header, 1, sizeof(struct pcap_header), default_logger->pcap_file);
    default_logger->log_to_pcap = 1;
    ao2_unlock(default_logger);
    ast_cli(fd, "PJSIP logging to pcap file '%s'\n", arg);
    return CLI_SUCCESS;
 }
pjsip_set_logger_verbose()
static char* pjsip_set_logger_verbose (int fd, const char * arg) static
Definition at line 425 of file res_pjsip_logger.c.
References ao2_unlock, ao2_wrlock, ast_cli(), ast_true(), CLI_SUCCESS, and pjsip_logger_session::log_to_verbose.
Referenced by pjsip_set_logger().
 {
    ao2_wrlock(default_logger);
    default_logger->log_to_verbose = ast_true(arg);
    ao2_unlock(default_logger);
    ast_cli(fd, "PJSIP Logging to verbose has been %s\n", ast_true(arg) ? "enabled" : "disabled");
    return CLI_SUCCESS;
 }
unload_module()
static int unload_module (void) static
Definition at line 566 of file res_pjsip_logger.c.
References ao2_cleanup, ARRAY_LEN, ast_cli_unregister_multiple(), AST_MODFLAG_LOAD_ORDER, AST_MODPRI_APP_DEPEND, AST_MODULE_INFO(), AST_MODULE_SUPPORT_CORE, ast_sip_get_sorcery(), ast_sip_unregister_service(), ast_sorcery_observer_remove(), ASTERISK_GPL_KEY, load_module(), and NULL.
 {
    ast_cli_unregister_multiple(cli_pjsip, ARRAY_LEN(cli_pjsip));
    ast_sip_unregister_service(&logging_module);
    ast_sorcery_observer_remove(
       ast_sip_get_sorcery(), "global", &global_observer);
    ao2_cleanup(default_logger);
    default_logger = NULL;
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "PJSIP Packet Logger" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_APP_DEPEND, .requires = "res_pjsip", } static
Definition at line 586 of file res_pjsip_logger.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 586 of file res_pjsip_logger.c.
cli_pjsip
struct ast_cli_entry cli_pjsip[] static
Initial value:
= {
   { .handler =  pjsip_set_logger , .summary =  "Enable/Disable PJSIP Logger Output" ,}
}
Definition at line 510 of file res_pjsip_logger.c.
default_logger
struct pjsip_logger_session* default_logger static
The default logger session.
Definition at line 121 of file res_pjsip_logger.c.
global_observer
const struct ast_sorcery_observer global_observer static
Initial value:
= {
   .loaded = global_reloaded
}
Definition at line 539 of file res_pjsip_logger.c.
logging_module
pjsip_module logging_module static
Definition at line 328 of file res_pjsip_logger.c.