Asterisk - The Open Source Telephony Project: config.c File Reference
res/ari/config.c File Reference
Config framework stuffz for ARI.
#include "asterisk.h"
#include "asterisk/config_options.h"
#include "asterisk/http_websocket.h"
#include "asterisk/app.h"
#include "asterisk/channel.h"
#include "internal.h"
Macros
#define CONF_FILENAME "ari.conf"
#define MAX_VARS 128
Functions
static AO2_GLOBAL_OBJ_STATIC (confs)
Locking container for safe configuration access.
void ast_ari_config_destroy (void)
Destroy the ARI configuration.
struct ast_ari_conf * ast_ari_config_get (void)
Get the current ARI configuration.
int ast_ari_config_init (void)
Initialize the ARI configuration.
int ast_ari_config_reload (void)
Reload the ARI configuration.
struct ast_ari_conf_user * ast_ari_config_validate_user (const char *username, const char *password)
Validated a user's credentials.
static int channelvars_handler (const struct aco_option *opt, struct ast_variable *var, void *obj)
static void * conf_alloc (void)
Allocate an ast_ari_conf for config parsing.
static void conf_destructor (void *obj)
ast_ari_conf destructor.
static void conf_general_dtor (void *obj)
CONFIG_INFO_STANDARD (cfg_info, confs, conf_alloc,.files=ACO_FILES(&conf_file))
static int encoding_format_handler (const struct aco_option *opt, struct ast_variable *var, void *obj)
Encoding format handler converts from boolean to enum.
static int password_format_handler (const struct aco_option *opt, struct ast_variable *var, void *obj)
Parses the ast_ari_password_format enum from a config file.
static int process_config (int reload)
Load (or reload) configuration.
static void * user_alloc (const char *cat)
Allocate an ast_ari_conf_user for config parsing.
static void user_dtor (void *obj)
Destructor for ast_ari_conf_user.
static void * user_find (struct ao2_container *tmp_container, const char *cat)
aco_type item_find function
static int user_sort_cmp (const void *obj_left, const void *obj_right, int flags)
Sorting function for use with red/black tree.
static int validate_user_cb (void *obj, void *arg, int flags)
Callback to validate a user object.
Variables
static struct aco_file conf_file
The conf file that's processed for the module.
static struct aco_type general_option
Mapping of the ARI conf struct's globals to the general context in the config file.
static struct aco_type * general_options [] = ACO_TYPES(&general_option)
static struct aco_type * global_user [] = ACO_TYPES(&user_option)
static struct aco_type user_option
Detailed Description
Config framework stuffz for ARI.
Author
David M. Lee, II dlee@.nosp@m.digi.nosp@m.um.co.nosp@m.m
Definition in file res/ari/config.c.
Macro Definition Documentation
CONF_FILENAME
#define CONF_FILENAME "ari.conf"
Definition at line 214 of file res/ari/config.c.
Referenced by ast_ari_config_get().
MAX_VARS
#define MAX_VARS 128
Definition at line 321 of file res/ari/config.c.
Referenced by channelvars_handler().
Function Documentation
AO2_GLOBAL_OBJ_STATIC()
static AO2_GLOBAL_OBJ_STATIC (confs) static
Locking container for safe configuration access.
ast_ari_config_destroy()
void ast_ari_config_destroy (void)
Destroy the ARI configuration.
Definition at line 383 of file res/ari/config.c.
References aco_info_destroy(), and ao2_global_obj_release.
Referenced by unload_module().
 {
    aco_info_destroy(&cfg_info);
    ao2_global_obj_release(confs);
 }
ast_ari_config_get()
struct ast_ari_conf* ast_ari_config_get (void)
Get the current ARI configuration.
This is an immutable object, so don't modify it. It is AO2 managed, so ao2_cleanup() when you're done with it.
Returns
ARI configuration object.
NULL on error.
Definition at line 227 of file res/ari/config.c.
References ao2_global_obj_ref, ast_log, CONF_FILENAME, and LOG_ERROR.
Referenced by ari_show(), ari_show_user(), ari_show_users(), ast_ari_callback(), ast_ari_config_validate_user(), ast_ari_json_format(), ast_ari_websocket_session_create(), complete_ari_user(), is_enabled(), origin_allowed(), and process_config().
 {
    struct ast_ari_conf *res = ao2_global_obj_ref(confs);
    if (!res) {
       ast_log(LOG_ERROR,
          "Error obtaining config from " CONF_FILENAME "\n");
    }
    return res;
 }
ast_ari_config_init()
int ast_ari_config_init (void)
Initialize the ARI configuration.
Definition at line 337 of file res/ari/config.c.
References ACO_EXACT, aco_info_destroy(), aco_info_init(), aco_option_register, aco_option_register_custom, ARI_AUTH_REALM_LEN, ARI_PASSWORD_LEN, AST_DEFAULT_WEBSOCKET_WRITE_TIMEOUT_STR, channelvars_handler(), enabled, encoding_format_handler(), FLDSET, NULL, OPT_BOOL_T, OPT_CHAR_ARRAY_T, OPT_INT_T, OPT_NOOP_T, OPT_STRINGFIELD_T, PARSE_IN_RANGE, password, password_format_handler(), process_config(), ast_ari_conf_user::read_only, and STRFLDSET.
Referenced by load_module().
 {
    if (aco_info_init(&cfg_info)) {
       aco_info_destroy(&cfg_info);
       return -1;
    }
    /* ARI general category options */
    aco_option_register(&cfg_info, "enabled", ACO_EXACT, general_options,
       "yes", OPT_BOOL_T, 1,
       FLDSET(struct ast_ari_conf_general, enabled));
    aco_option_register_custom(&cfg_info, "pretty", ACO_EXACT,
       general_options, "no",  encoding_format_handler, 0);
    aco_option_register(&cfg_info, "auth_realm", ACO_EXACT, general_options,
       "Asterisk REST Interface", OPT_CHAR_ARRAY_T, 0,
       FLDSET(struct ast_ari_conf_general, auth_realm),
       ARI_AUTH_REALM_LEN);
    aco_option_register(&cfg_info, "allowed_origins", ACO_EXACT, general_options,
       "", OPT_STRINGFIELD_T, 0,
       STRFLDSET(struct ast_ari_conf_general, allowed_origins));
    aco_option_register(&cfg_info, "websocket_write_timeout", ACO_EXACT, general_options,
       AST_DEFAULT_WEBSOCKET_WRITE_TIMEOUT_STR, OPT_INT_T, PARSE_IN_RANGE,
       FLDSET(struct ast_ari_conf_general, write_timeout), 1, INT_MAX);
    aco_option_register_custom(&cfg_info, "channelvars", ACO_EXACT, general_options,
       "", channelvars_handler, 0);
    /* ARI type=user category options */
    aco_option_register(&cfg_info, "type", ACO_EXACT, global_user, NULL,
       OPT_NOOP_T, 0, 0);
    aco_option_register(&cfg_info, "read_only", ACO_EXACT, global_user,
       "no", OPT_BOOL_T, 1,
       FLDSET(struct ast_ari_conf_user, read_only));
    aco_option_register(&cfg_info, "password", ACO_EXACT, global_user,
       "", OPT_CHAR_ARRAY_T, 0,
       FLDSET(struct ast_ari_conf_user, password), ARI_PASSWORD_LEN);
    aco_option_register_custom(&cfg_info, "password_format", ACO_EXACT,
       global_user, "plain",  password_format_handler, 0);
    return process_config(0);
 }
ast_ari_config_reload()
int ast_ari_config_reload (void)
Reload the ARI configuration.
Definition at line 378 of file res/ari/config.c.
References process_config().
Referenced by reload_module().
 {
    return process_config(1);
 }
ast_ari_config_validate_user()
struct ast_ari_conf_user* ast_ari_config_validate_user (const char * username, const char * password)
Validated a user's credentials.
Parameters
username Name of the user.
password User's password.
Returns
User object.
NULL if username or password is invalid.
Definition at line 237 of file res/ari/config.c.
References ao2_cleanup, ao2_find, ao2_ref, ARI_PASSWORD_FORMAT_CRYPT, ARI_PASSWORD_FORMAT_PLAIN, ast_ari_config_get(), ast_crypt_validate(), ast_log, ast_strlen_zero, LOG_WARNING, NULL, OBJ_SEARCH_KEY, RAII_VAR, and user.
Referenced by authenticate_api_key(), and authenticate_user().
 {
    RAII_VAR(struct ast_ari_conf *, conf, NULL, ao2_cleanup);
    RAII_VAR(struct ast_ari_conf_user *, user, NULL, ao2_cleanup);
    int is_valid = 0;
    conf = ast_ari_config_get();
    if (!conf) {
       return NULL;
    }
    user = ao2_find(conf->users, username, OBJ_SEARCH_KEY);
    if (!user) {
       return NULL;
    }
    if (ast_strlen_zero(user->password)) {
       ast_log(LOG_WARNING,
          "User '%s' missing password; authentication failed\n",
          user->username);
       return NULL;
    }
    switch (user->password_format) {
    case ARI_PASSWORD_FORMAT_PLAIN:
       is_valid = strcmp(password, user->password) == 0;
       break;
    case ARI_PASSWORD_FORMAT_CRYPT:
       is_valid = ast_crypt_validate(password, user->password);
       break;
    }
    if (!is_valid) {
       return NULL;
    }
    ao2_ref(user, +1);
    return user;
 }
channelvars_handler()
static int channelvars_handler (const struct aco_option * opt, struct ast_variable * var, void * obj) static
Definition at line 323 of file res/ari/config.c.
References args, AST_APP_ARG, ast_channel_set_ari_vars(), AST_DECLARE_APP_ARGS, AST_STANDARD_APP_ARGS, ast_strdupa, MAX_VARS, NULL, parse(), and ast_variable::value.
Referenced by ast_ari_config_init().
 {
    char *parse = NULL;
    AST_DECLARE_APP_ARGS(args,
       AST_APP_ARG(vars)[MAX_VARS];
    );
    parse = ast_strdupa(var->value);
    AST_STANDARD_APP_ARGS(args, parse);
    ast_channel_set_ari_vars(args.argc, args.vars);
    return 0;
 }
conf_alloc()
static void* conf_alloc (void) static
Allocate an ast_ari_conf for config parsing.
Definition at line 187 of file res/ari/config.c.
References aco_set_defaults(), AO2_ALLOC_OPT_LOCK_NOLOCK, ao2_alloc_options, AO2_CONTAINER_ALLOC_OPT_DUPS_REPLACE, ao2_container_alloc_rbtree, ao2_ref, ast_string_field_init, conf_destructor(), conf_general_dtor(), ast_ari_conf::general, NULL, user_sort_cmp(), and ast_ari_conf::users.
 {
    struct ast_ari_conf *cfg;
    cfg = ao2_alloc_options(sizeof(*cfg), conf_destructor,
       AO2_ALLOC_OPT_LOCK_NOLOCK);
    if (!cfg) {
       return NULL;
    }
    cfg->general = ao2_alloc_options(sizeof(*cfg->general), conf_general_dtor,
       AO2_ALLOC_OPT_LOCK_NOLOCK);
    cfg->users = ao2_container_alloc_rbtree(AO2_ALLOC_OPT_LOCK_NOLOCK,
       AO2_CONTAINER_ALLOC_OPT_DUPS_REPLACE, user_sort_cmp, NULL);
    if (!cfg->users
       || !cfg->general
       || ast_string_field_init(cfg->general, 64)
       || aco_set_defaults(&general_option, "general", cfg->general)) {
       ao2_ref(cfg, -1);
       return NULL;
    }
    return cfg;
 }
conf_destructor()
static void conf_destructor (void * obj) static
ast_ari_conf destructor.
Definition at line 178 of file res/ari/config.c.
References ao2_cleanup, ast_ari_conf::general, and ast_ari_conf::users.
Referenced by conf_alloc().
 {
    struct ast_ari_conf *cfg = obj;
    ao2_cleanup(cfg->general);
    ao2_cleanup(cfg->users);
 }
conf_general_dtor()
static void conf_general_dtor (void * obj) static
Definition at line 170 of file res/ari/config.c.
References ast_string_field_free_memory.
Referenced by conf_alloc().
 {
    struct ast_ari_conf_general *general = obj;
    ast_string_field_free_memory(general);
 }
CONFIG_INFO_STANDARD()
CONFIG_INFO_STANDARD (cfg_info , confs , conf_alloc , . files = ACO_FILES(&conf_file))
encoding_format_handler()
static int encoding_format_handler (const struct aco_option * opt, struct ast_variable * var, void * obj) static
Encoding format handler converts from boolean to enum.
Definition at line 49 of file res/ari/config.c.
References AST_JSON_COMPACT, AST_JSON_PRETTY, ast_true(), ast_ari_conf_general::format, ast_variable::name, and ast_variable::value.
Referenced by ast_ari_config_init().
 {
    struct ast_ari_conf_general *general = obj;
    if (!strcasecmp(var->name, "pretty")) {
       general->format = ast_true(var->value) ?
          AST_JSON_PRETTY : AST_JSON_COMPACT;
    } else {
       return -1;
    }
    return 0;
 }
password_format_handler()
static int password_format_handler (const struct aco_option * opt, struct ast_variable * var, void * obj) static
Parses the ast_ari_password_format enum from a config file.
Definition at line 65 of file res/ari/config.c.
References ARI_PASSWORD_FORMAT_CRYPT, ARI_PASSWORD_FORMAT_PLAIN, ast_ari_conf_user::password_format, and ast_variable::value.
Referenced by ast_ari_config_init().
 {
    struct ast_ari_conf_user *user = obj;
    if (strcasecmp(var->value, "plain") == 0) {
       user->password_format = ARI_PASSWORD_FORMAT_PLAIN;
    } else if (strcasecmp(var->value, "crypt") == 0) {
       user->password_format = ARI_PASSWORD_FORMAT_CRYPT;
    } else {
       return -1;
    }
    return 0;
 }
process_config()
static int process_config (int reload) static
Load (or reload) configuration.
Definition at line 292 of file res/ari/config.c.
References aco_process_config(), ACO_PROCESS_ERROR, ACO_PROCESS_OK, ACO_PROCESS_UNCHANGED, ao2_callback, ao2_cleanup, ao2_container_count(), ast_ari_config_get(), ast_assert, ast_log, LOG_ERROR, NULL, OBJ_NODATA, RAII_VAR, and validate_user_cb().
Referenced by ast_ari_config_init(), and ast_ari_config_reload().
 {
    RAII_VAR(struct ast_ari_conf *, conf, NULL, ao2_cleanup);
    switch (aco_process_config(&cfg_info, reload)) {
    case ACO_PROCESS_ERROR:
       return -1;
    case ACO_PROCESS_OK:
    case ACO_PROCESS_UNCHANGED:
       break;
    }
    conf = ast_ari_config_get();
    if (!conf) {
       ast_assert(0); /* We just configured; it should be there */
       return -1;
    }
    if (conf->general->enabled) {
       if (ao2_container_count(conf->users) == 0) {
          ast_log(LOG_ERROR, "No configured users for ARI\n");
       } else {
          ao2_callback(conf->users, OBJ_NODATA, validate_user_cb, NULL);
       }
    }
    return 0;
 }
user_alloc()
static void* user_alloc (const char * cat) static
Allocate an ast_ari_conf_user for config parsing.
Definition at line 90 of file res/ari/config.c.
References AO2_ALLOC_OPT_LOCK_NOLOCK, ao2_alloc_options, ao2_cleanup, ao2_ref, ast_debug, ast_strdup, NULL, RAII_VAR, user, and user_dtor().
 {
    RAII_VAR(struct ast_ari_conf_user *, user, NULL, ao2_cleanup);
    if (!cat) {
       return NULL;
    }
    ast_debug(3, "Allocating user %s\n", cat);
    user = ao2_alloc_options(sizeof(*user), user_dtor,
       AO2_ALLOC_OPT_LOCK_NOLOCK);
    if (!user) {
       return NULL;
    }
    user->username = ast_strdup(cat);
    if (!user->username) {
       return NULL;
    }
    ao2_ref(user, +1);
    return user;
 }
user_dtor()
static void user_dtor (void * obj) static
Destructor for ast_ari_conf_user.
Definition at line 82 of file res/ari/config.c.
References ast_debug, ast_free, and ast_ari_conf_user::username.
Referenced by user_alloc().
 {
    struct ast_ari_conf_user *user = obj;
    ast_debug(3, "Disposing of user %s\n", user->username);
    ast_free(user->username);
 }
user_find()
static void* user_find (struct ao2_container * tmp_container, const char * cat) static
aco_type item_find function
Definition at line 147 of file res/ari/config.c.
References ao2_find, NULL, and OBJ_SEARCH_KEY.
 {
    if (!cat) {
       return NULL;
    }
    return ao2_find(tmp_container, cat, OBJ_SEARCH_KEY);
 }
user_sort_cmp()
static int user_sort_cmp (const void * obj_left, const void * obj_right, int flags) static
Sorting function for use with red/black tree.
Definition at line 116 of file res/ari/config.c.
References ast_assert, OBJ_SEARCH_KEY, OBJ_SEARCH_MASK, OBJ_SEARCH_OBJECT, OBJ_SEARCH_PARTIAL_KEY, and ast_ari_conf_user::username.
Referenced by conf_alloc().
 {
    const struct ast_ari_conf_user *user_left = obj_left;
    const struct ast_ari_conf_user *user_right = obj_right;
    const char *key_right = obj_right;
    int cmp;
    switch (flags & OBJ_SEARCH_MASK) {
    case OBJ_SEARCH_OBJECT:
       key_right = user_right->username;
       /* Fall through */
    case OBJ_SEARCH_KEY:
       cmp = strcasecmp(user_left->username, key_right);
       break;
    case OBJ_SEARCH_PARTIAL_KEY:
       /*
        * We could also use a partial key struct containing a length
        * so strlen() does not get called for every comparison instead.
        */
       cmp = strncasecmp(user_left->username, key_right, strlen(key_right));
       break;
    default:
       /* Sort can only work on something with a full or partial key. */
       ast_assert(0);
       cmp = 0;
       break;
    }
    return cmp;
 }
validate_user_cb()
static int validate_user_cb (void * obj, void * arg, int flags) static
Callback to validate a user object.
Definition at line 279 of file res/ari/config.c.
References ast_log, ast_strlen_zero, LOG_WARNING, ast_ari_conf_user::password, and ast_ari_conf_user::username.
Referenced by process_config().
 {
    struct ast_ari_conf_user *user = obj;
    if (ast_strlen_zero(user->password)) {
       ast_log(LOG_WARNING, "User '%s' missing password\n",
          user->username);
    }
    return 0;
 }
Variable Documentation
conf_file
struct aco_file conf_file static
The conf file that's processed for the module.
Definition at line 217 of file res/ari/config.c.
general_option
struct aco_type general_option static
Mapping of the ARI conf struct's globals to the general context in the config file.
Definition at line 38 of file res/ari/config.c.
general_options
struct aco_type* general_options[] = ACO_TYPES(&general_option) static
Definition at line 46 of file res/ari/config.c.
global_user
struct aco_type* global_user[] = ACO_TYPES(&user_option) static
Definition at line 168 of file res/ari/config.c.
user_option
struct aco_type user_option static
Definition at line 156 of file res/ari/config.c.