Asterisk - The Open Source Telephony Project: extconf.h File Reference
extconf.h File Reference
External configuration handlers (realtime and static configuration)
Data Structures
struct pbx_find_info
Macros
#define AST_PBX_MAX_STACK 512
#define STATUS_NO_CONTEXT 1
#define STATUS_NO_EXTENSION 2
#define STATUS_NO_LABEL 4
#define STATUS_NO_PRIORITY 3
#define STATUS_SUCCESS 5
Enumerations
enum ext_match_t {
E_MATCHMORE = 0x00, E_CANMATCH = 0x01, E_MATCH = 0x02, E_MATCH_MASK = 0x03,
E_SPAWN = 0x12, E_FINDLABEL = 0x22, E_MATCHMORE = 0x00, E_CANMATCH = 0x01,
E_MATCH = 0x02, E_MATCH_MASK = 0x03, E_SPAWN = 0x12, E_FINDLABEL = 0x22
}
Functions
int localized_add_extension2 (struct ast_context *con, int replace, const char *extension, int priority, const char *label, const char *callerid, const char *application, void *data, void(*datad)(void *), const char *registrar)
struct ast_category * localized_category_get (const struct ast_config *config, const char *category_name)
struct ast_config * localized_config_load (const char *filename)
struct ast_config * localized_config_load_with_comments (const char *filename)
int localized_config_text_file_save (const char *configfile, const struct ast_config *cfg, const char *generator)
int localized_context_add_ignorepat2 (struct ast_context *con, const char *value, const char *registrar)
int localized_context_add_include2 (struct ast_context *con, const char *value, const char *registrar)
int localized_context_add_switch2 (struct ast_context *con, const char *value, const char *data, int eval, const char *registrar)
void localized_context_destroy (struct ast_context *con, const char *registrar)
struct ast_context * localized_context_find_or_create (struct ast_context **extcontexts, void *tab, const char *name, const char *registrar)
int localized_context_verify_includes (struct ast_context *con)
struct ast_exten * localized_find_extension (struct ast_context *bypass, struct pbx_find_info *q, const char *context, const char *exten, int priority, const char *label, const char *callerid, enum ext_match_t action)
void localized_merge_contexts_and_delete (struct ast_context **extcontexts, void *tab, const char *registrar)
int localized_pbx_builtin_setvar (struct ast_channel *chan, const void *data)
int localized_pbx_load_module (void)
void localized_use_conf_dir (void)
void localized_use_local_dir (void)
struct ast_exten * localized_walk_context_extensions (struct ast_context *con, struct ast_exten *exten)
struct ast_include * localized_walk_context_includes (struct ast_context *con, struct ast_include *inc)
struct ast_sw * localized_walk_context_switches (struct ast_context *con, struct ast_sw *sw)
struct ast_context * localized_walk_contexts (struct ast_context *con)
struct ast_exten * localized_walk_extension_priorities (struct ast_exten *exten, struct ast_exten *priority)
Detailed Description
External configuration handlers (realtime and static configuration)
Author
Steve Murphy murf@.nosp@m.digi.nosp@m.um.co.nosp@m.m
Definition in file extconf.h.
Macro Definition Documentation
AST_PBX_MAX_STACK
#define AST_PBX_MAX_STACK 512
Definition at line 226 of file extconf.h.
Referenced by find_matching_priority(), handle_debug_dialplan(), handle_show_dialplan(), manager_show_dialplan(), manager_show_dialplan_helper(), pbx_find_extension(), and show_dialplan_helper().
STATUS_NO_CONTEXT
#define STATUS_NO_CONTEXT 1
Definition at line 245 of file extconf.h.
STATUS_NO_EXTENSION
#define STATUS_NO_EXTENSION 2
Definition at line 246 of file extconf.h.
STATUS_NO_LABEL
#define STATUS_NO_LABEL 4
Definition at line 248 of file extconf.h.
STATUS_NO_PRIORITY
#define STATUS_NO_PRIORITY 3
Definition at line 247 of file extconf.h.
STATUS_SUCCESS
#define STATUS_SUCCESS 5
Definition at line 249 of file extconf.h.
Referenced by check_goto(), and check_pval_item().
Enumeration Type Documentation
ext_match_t
enum ext_match_t
When looking up extensions, we can have different requests identified by the 'action' argument, as follows. Note that the coding is such that the low 4 bits are the third argument to extension_match_core.
Enumerator
E_MATCHMORE
E_CANMATCH
E_MATCH
E_MATCH_MASK
E_SPAWN
E_FINDLABEL
E_MATCHMORE
E_CANMATCH
E_MATCH
E_MATCH_MASK
E_SPAWN
E_FINDLABEL
Definition at line 215 of file extconf.h.
                  {
    E_MATCHMORE =  0x00, /* extension can match but only with more 'digits' */
    E_CANMATCH =   0x01, /* extension can match with or without more 'digits' */
    E_MATCH =   0x02, /* extension is an exact match */
    E_MATCH_MASK = 0x03, /* mask for the argument to extension_match_core() */
    E_SPAWN =   0x12, /* want to spawn an extension. Requires exact match */
    E_FINDLABEL =  0x22  /* returns the priority for a given label. Requires exact match */
 };
Function Documentation
localized_add_extension2()
int localized_add_extension2 (struct ast_context * con, int replace, const char * extension, int priority, const char * label, const char * callerid, const char * application, void * data, void(*)(void *) datad, const char * registrar)
Definition at line 4898 of file extconf.c.
References ast_add_extension2(), and ast_exten::datad.
Referenced by ast_add_extension2().
 {
    return ast_add_extension2(con, replace, extension, priority, label, callerid, application, data, datad, registrar);
 }
localized_category_get()
struct ast_category * localized_category_get (const struct ast_config * config, const char * category_name)
Definition at line 2803 of file extconf.c.
References category_get().
Referenced by ast_category_new().
 {
    return category_get(config, category_name, 0);
 }
localized_config_load()
struct ast_config * localized_config_load (const char * filename)
Definition at line 3287 of file extconf.c.
References ast_config_destroy(), ast_config_internal_load(), ast_config_new(), localized_config_load_with_comments(), NULL, and result.
Referenced by ast_config_new(), and pbx_load_config().
 {
    struct ast_config *cfg;
    struct ast_config *result;
    cfg = ast_config_new();
    if (!cfg)
       return NULL;
    result = ast_config_internal_load(filename, cfg, 0, "");
    if (!result)
       ast_config_destroy(cfg);
    return result;
 }
localized_config_load_with_comments()
struct ast_config * localized_config_load_with_comments (const char * filename)
Definition at line 3305 of file extconf.c.
References ast_config_destroy(), ast_config_internal_load(), ast_config_new(), NULL, and result.
Referenced by localized_config_load().
 {
    struct ast_config *cfg;
    struct ast_config *result;
    cfg = ast_config_new();
    if (!cfg)
       return NULL;
    result = ast_config_internal_load(filename, cfg, 1, "");
    if (!result)
       ast_config_destroy(cfg);
    return result;
 }
localized_config_text_file_save()
int localized_config_text_file_save (const char * configfile, const struct ast_config * cfg, const char * generator)
Definition at line 3423 of file extconf.c.
References ast_log(), ast_verbose(), ast_variable::blanklines, ast_comment::cmt, errno, ast_config_include::exec, ast_config_include::exec_file, ast_variable::file, ast_category::file, gen_header(), ast_config_include::include_location_file, ast_config_include::include_location_lineno, ast_config_include::included_file, ast_config::includes, ast_variable::lineno, ast_category::lineno, LOG_DEBUG, ast_variable::name, ast_category::name, ast_comment::next, ast_variable::next, ast_category::next, ast_config_include::next, ast_variable::object, ast_config_include::output, ast_variable::precomments, ast_category::precomments, ast_category::root, ast_config::root, ast_variable::sameline, ast_category::sameline, set_fn(), ast_variable::value, var, and VERBOSE_PREFIX_2.
Referenced by set_fn().
 {
    FILE *f;
    char fn[256];
    struct ast_variable *var;
    struct ast_category *cat;
    struct ast_comment *cmt;
    struct ast_config_include *incl;
    int blanklines = 0;
    /* reset all the output flags, in case this isn't our first time saving this data */
    for (incl=cfg->includes; incl; incl = incl->next)
       incl->output = 0;
    /* go thru all the inclusions and make sure all the files involved (configfile plus all its inclusions)
       are all truncated to zero bytes and have that nice header*/
    for (incl=cfg->includes; incl; incl = incl->next)
    {
       if (!incl->exec) { /* leave the execs alone -- we'll write out the #exec directives, but won't zero out the include files or exec files*/
          FILE *f1;
          set_fn(fn, sizeof(fn), incl->included_file, configfile); /* normally, fn is just set to incl->included_file, prepended with config dir if relative */
          f1 = fopen(fn,"w");
          if (f1) {
             gen_header(f1, configfile, fn, generator);
             fclose(f1); /* this should zero out the file */
          } else {
             ast_verbose(VERBOSE_PREFIX_2 "Unable to write %s (%s)", fn, strerror(errno));
          }
       }
    }
    set_fn(fn, sizeof(fn), 0, configfile); /* just set fn to absolute ver of configfile */
 #ifdef __CYGWIN__
    if ((f = fopen(fn, "w+"))) {
 #else
    if ((f = fopen(fn, "w"))) {
 #endif
       if (option_verbose > 1)
          ast_verbose(VERBOSE_PREFIX_2 "Saving '%s': ", fn);
       gen_header(f, configfile, fn, generator);
       cat = cfg->root;
       fclose(f);
       /* from here out, we open each involved file and concat the stuff we need to add to the end and immediately close... */
       /* since each var, cat, and associated comments can come from any file, we have to be
          mobile, and open each file, print, and close it on an entry-by-entry basis */
       while(cat) {
          set_fn(fn, sizeof(fn), cat->file, configfile);
          f = fopen(fn, "a");
          if (!f)
          {
             ast_verbose(VERBOSE_PREFIX_2 "Unable to write %s (%s)", fn, strerror(errno));
             return -1;
          }
          /* dump any includes that happen before this category header */
          for (incl=cfg->includes; incl; incl = incl->next) {
             if (strcmp(incl->include_location_file, cat->file) == 0){
                if (cat->lineno > incl->include_location_lineno && !incl->output) {
                   if (incl->exec)
                      fprintf(f,"#exec \"%s\"\n", incl->exec_file);
                   else
                      fprintf(f,"#include \"%s\"\n", incl->included_file);
                   incl->output = 1;
                }
             }
          }
          /* Dump section with any appropriate comment */
          for (cmt = cat->precomments; cmt; cmt=cmt->next) {
             if (cmt->cmt[0] != ';' || cmt->cmt[1] != '!')
                fprintf(f,"%s", cmt->cmt);
          }
          if (!cat->precomments)
             fprintf(f,"\n");
          fprintf(f, "[%s]", cat->name);
          for(cmt = cat->sameline; cmt; cmt=cmt->next) {
             fprintf(f,"%s", cmt->cmt);
          }
          if (!cat->sameline)
             fprintf(f,"\n");
          fclose(f);
          var = cat->root;
          while(var) {
             set_fn(fn, sizeof(fn), var->file, configfile);
             f = fopen(fn, "a");
             if (!f)
             {
                ast_verbose(VERBOSE_PREFIX_2 "Unable to write %s (%s)", fn, strerror(errno));
                return -1;
             }
             /* dump any includes that happen before this category header */
             for (incl=cfg->includes; incl; incl = incl->next) {
                if (strcmp(incl->include_location_file, var->file) == 0){
                   if (var->lineno > incl->include_location_lineno && !incl->output) {
                      if (incl->exec)
                         fprintf(f,"#exec \"%s\"\n", incl->exec_file);
                      else
                         fprintf(f,"#include \"%s\"\n", incl->included_file);
                      incl->output = 1;
                   }
                }
             }
             for (cmt = var->precomments; cmt; cmt=cmt->next) {
                if (cmt->cmt[0] != ';' || cmt->cmt[1] != '!')
                   fprintf(f,"%s", cmt->cmt);
             }
             if (var->sameline)
                fprintf(f, "%s %s %s  %s", var->name, (var->object ? "=>" : "="), var->value, var->sameline->cmt);
             else
                fprintf(f, "%s %s %s\n", var->name, (var->object ? "=>" : "="), var->value);
             if (var->blanklines) {
                blanklines = var->blanklines;
                while (blanklines--)
                   fprintf(f, "\n");
             }
             fclose(f);
             var = var->next;
          }
          cat = cat->next;
       }
       if ((option_verbose > 1) && !option_debug)
          ast_verbose("Saved\n");
    } else {
       if (option_debug)
          ast_log(LOG_DEBUG, "Unable to open for writing: %s\n", fn);
       if (option_verbose > 1)
          ast_verbose(VERBOSE_PREFIX_2 "Unable to write (%s)", strerror(errno));
       return -1;
    }
    /* Now, for files with trailing #include/#exec statements,
       we have to make sure every entry is output */
    for (incl=cfg->includes; incl; incl = incl->next) {
       if (!incl->output) {
          /* open the respective file */
          set_fn(fn, sizeof(fn), incl->include_location_file, configfile);
          f = fopen(fn, "a");
          if (!f)
          {
             ast_verbose(VERBOSE_PREFIX_2 "Unable to write %s (%s)", fn, strerror(errno));
             return -1;
          }
          /* output the respective include */
          if (incl->exec)
             fprintf(f,"#exec \"%s\"\n", incl->exec_file);
          else
             fprintf(f,"#include \"%s\"\n", incl->included_file);
          fclose(f);
          incl->output = 1;
       }
    }
    return 0;
 }
localized_context_add_ignorepat2()
int localized_context_add_ignorepat2 (struct ast_context * con, const char * value, const char * registrar)
Definition at line 4601 of file extconf.c.
References ast_context_add_ignorepat2().
Referenced by ast_context_add_ignorepat2().
 {
    return ast_context_add_ignorepat2(con, value, registrar);
 }
localized_context_add_include2()
int localized_context_add_include2 (struct ast_context * con, const char * value, const char * registrar)
Definition at line 4559 of file extconf.c.
References ast_context_add_ignorepat2(), and ast_context_add_include2().
Referenced by ast_context_add_include2().
 {
    return  ast_context_add_include2(con, value, registrar);
 }
localized_context_add_switch2()
int localized_context_add_switch2 (struct ast_context * con, const char * value, const char * data, int eval, const char * registrar)
Definition at line 4702 of file extconf.c.
References ast_context_add_switch2().
Referenced by ast_context_add_switch2().
 {
    return ast_context_add_switch2(con, value, data, eval, registrar);
 }
localized_context_destroy()
void localized_context_destroy (struct ast_context * con, const char * registrar)
Definition at line 5565 of file extconf.c.
References __ast_context_destroy(), ast_unlock_contexts(), and ast_wrlock_contexts().
Referenced by __ast_context_destroy(), and ast_context_destroy().
 {
    ast_wrlock_contexts();
    __ast_context_destroy(con,registrar);
    ast_unlock_contexts();
 }
localized_context_find_or_create()
struct ast_context * localized_context_find_or_create (struct ast_context ** extcontexts, void * tab, const char * name, const char * registrar)
Version
1.6.1 added tab parameter
1.6.1 renamed function from localized_context_create to localized_context_find_or_create
Definition at line 4989 of file extconf.c.
References __ast_context_create().
Referenced by ast_context_find_or_create().
 {
    return __ast_context_create(extcontexts, name, registrar, 1);
 }
localized_context_verify_includes()
int localized_context_verify_includes (struct ast_context * con)
Definition at line 5640 of file extconf.c.
References ast_context_verify_includes(), and localized_pbx_load_module().
Referenced by ast_context_verify_includes().
 {
    return ast_context_verify_includes(con);
 }
localized_find_extension()
struct ast_exten * localized_find_extension (struct ast_context * bypass, struct pbx_find_info * q, const char * context, const char * exten, int priority, const char * label, const char * callerid, enum ext_match_t action)
Definition at line 4470 of file extconf.c.
References NULL, and pbx_find_extension().
Referenced by pbx_find_extension().
 {
    return pbx_find_extension(NULL, bypass, q, context, exten, priority, label, callerid, action);
 }
localized_merge_contexts_and_delete()
void localized_merge_contexts_and_delete (struct ast_context ** extcontexts, void * tab, const char * registrar)
Version
1.6.1 added tab parameter
Definition at line 5618 of file extconf.c.
References ast_merge_contexts_and_delete().
Referenced by ast_merge_contexts_and_delete().
 {
    ast_merge_contexts_and_delete(extcontexts, registrar);
 }
localized_pbx_builtin_setvar()
int localized_pbx_builtin_setvar (struct ast_channel * chan, const void * data)
Definition at line 2607 of file extconf.c.
References pbx_builtin_setvar().
Referenced by pbx_builtin_setvar().
 {
    return pbx_builtin_setvar(chan, data);
 }
localized_pbx_load_module()
int localized_pbx_load_module (void)
Definition at line 5647 of file extconf.c.
Referenced by main().
 {
    struct ast_context *con;
    if(!pbx_load_config(config_filename))
       return -1 /* AST_MODULE_LOAD_DECLINE*/;
    /* pbx_load_users(); */ /* does this affect the dialplan? */
    ast_merge_contexts_and_delete(&local_contexts, global_registrar);
    for (con = NULL; (con = ast_walk_contexts(con));)
       ast_context_verify_includes(con);
    printf("=== Loading extensions.conf ===\n");
    con = 0;
    while ((con = ast_walk_contexts(con)) ) {
       printf("Context: %s\n", con->name);
    }
    printf("=========\n");
    return 0;
 }
localized_use_conf_dir()
void localized_use_conf_dir (void)
Definition at line 3115 of file extconf.c.
Referenced by main().
 {
    use_local_dir = 0;
 }
localized_use_local_dir()
void localized_use_local_dir (void)
Definition at line 3110 of file extconf.c.
Referenced by main().
 {
    use_local_dir = 1;
 }
localized_walk_context_extensions()
struct ast_exten * localized_walk_context_extensions (struct ast_context * con, struct ast_exten * exten)
Definition at line 4053 of file extconf.c.
References ast_walk_context_extensions(), and ast_walk_extension_priorities().
Referenced by ast_walk_context_extensions(), and main().
 {
    return ast_walk_context_extensions(con,exten);
 }
localized_walk_context_includes()
struct ast_include * localized_walk_context_includes (struct ast_context * con, struct ast_include * inc)
Definition at line 4106 of file extconf.c.
References ast_walk_context_ignorepats(), and ast_walk_context_includes().
Referenced by ast_context_includes_count().
 {
    return ast_walk_context_includes(con, inc);
 }
localized_walk_context_switches()
struct ast_sw * localized_walk_context_switches (struct ast_context * con, struct ast_sw * sw)
Definition at line 4152 of file extconf.c.
References ast_context_switches_count(), and ast_walk_context_switches().
Referenced by ast_walk_context_switches(), and main().
 {
    return ast_walk_context_switches(con, sw);
 }
localized_walk_contexts()
struct ast_context * localized_walk_contexts (struct ast_context * con)
Definition at line 4032 of file extconf.c.
References ast_walk_context_extensions(), and ast_walk_contexts().
Referenced by ast_walk_contexts(), and main().
 {
    return ast_walk_contexts(con);
 }
localized_walk_extension_priorities()
struct ast_exten * localized_walk_extension_priorities (struct ast_exten * exten, struct ast_exten * priority)
Definition at line 4071 of file extconf.c.
References ast_walk_context_includes(), and ast_walk_extension_priorities().
Referenced by ast_walk_extension_priorities(), and main().
 {
    return ast_walk_extension_priorities(exten, priority);
 }