Asterisk - The Open Source Telephony Project: res_format_attr_siren7.c File Reference
res_format_attr_siren7.c File Reference
Siren7 format attribute interface.
#include "asterisk.h"
#include <ctype.h>
#include "asterisk/module.h"
#include "asterisk/format.h"
#include "asterisk/astobj2.h"
#include "asterisk/logger.h"
#include "asterisk/strings.h"
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int load_module (void)
static int siren7_clone (const struct ast_format *src, struct ast_format *dst)
static void siren7_destroy (struct ast_format *format)
static void siren7_generate_sdp_fmtp (const struct ast_format *format, unsigned int payload, struct ast_str **str)
static struct ast_format * siren7_parse_sdp_fmtp (const struct ast_format *format, const char *attributes)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Siren7 Format Attribute Module" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_CHANNEL_DEPEND, }
static const struct ast_module_info * ast_module_info = &__mod_info
static struct ast_format_interface siren7_interface
Detailed Description
Siren7 format attribute interface.
Author
Joshua Colp jcolp.nosp@m.@dig.nosp@m.ium.c.nosp@m.om
Definition in file res_format_attr_siren7.c.
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 103 of file res_format_attr_siren7.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 103 of file res_format_attr_siren7.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 103 of file res_format_attr_siren7.c.
load_module()
static int load_module (void) static
Definition at line 84 of file res_format_attr_siren7.c.
References ast_format_interface_register, AST_MODULE_LOAD_DECLINE, and AST_MODULE_LOAD_SUCCESS.
Referenced by unload_module().
 {
    if (ast_format_interface_register("siren7", &siren7_interface)) {
       return AST_MODULE_LOAD_DECLINE;
    }
    return AST_MODULE_LOAD_SUCCESS;
 }
siren7_clone()
static int siren7_clone (const struct ast_format * src, struct ast_format * dst) static
Definition at line 46 of file res_format_attr_siren7.c.
 {
    return 0;
 }
siren7_destroy()
static void siren7_destroy (struct ast_format * format) static
Definition at line 41 of file res_format_attr_siren7.c.
 {
 }
siren7_generate_sdp_fmtp()
static void siren7_generate_sdp_fmtp (const struct ast_format * format, unsigned int payload, struct ast_str ** str) static
Definition at line 72 of file res_format_attr_siren7.c.
References ast_str_append().
 {
    ast_str_append(str, 0, "a=fmtp:%u bitrate=32000\r\n", payload);
 }
siren7_parse_sdp_fmtp()
static struct ast_format* siren7_parse_sdp_fmtp (const struct ast_format * format, const char * attributes) static
Definition at line 51 of file res_format_attr_siren7.c.
References ao2_bump, ast_log, ast_strdupa, LOG_WARNING, and NULL.
 {
    char *attribs = ast_strdupa(attributes), *attrib;
    unsigned int val;
    /* lower-case everything, so we are case-insensitive */
    for (attrib = attribs; *attrib; ++attrib) {
       *attrib = tolower(*attrib);
    } /* based on channels/chan_sip.c:process_a_sdp_image() */
    if (sscanf(attribs, "bitrate=%30u", &val) == 1) {
       if (val != 32000) {
          ast_log(LOG_WARNING, "Got Siren7 offer at %u bps, but only 32000 bps supported; ignoring.\n", val);
          return NULL;
       }
    }
    /* We aren't modifying the format and once passed back it won't be touched, so use what we were given */
    return ao2_bump((struct ast_format *)format);
 }
unload_module()
static int unload_module (void) static
Definition at line 93 of file res_format_attr_siren7.c.
References AST_MODFLAG_LOAD_ORDER, AST_MODPRI_CHANNEL_DEPEND, AST_MODULE_INFO(), AST_MODULE_SUPPORT_CORE, ASTERISK_GPL_KEY, and load_module().
 {
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Siren7 Format Attribute Module" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_CHANNEL_DEPEND, } static
Definition at line 103 of file res_format_attr_siren7.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 103 of file res_format_attr_siren7.c.
siren7_interface
struct ast_format_interface siren7_interface static
Definition at line 77 of file res_format_attr_siren7.c.