Asterisk - The Open Source Telephony Project: res_remb_modifier.c File Reference
res_remb_modifier.c File Reference
REMB Modifier Module.
#include "asterisk.h"
#include <math.h>
#include "asterisk/module.h"
#include "asterisk/cli.h"
#include "asterisk/channel.h"
#include "asterisk/framehook.h"
#include "asterisk/rtp_engine.h"
Data Structures
struct remb_values
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static char * handle_remb_set (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static int load_module (void)
static struct ast_frame * remb_hook_event_cb (struct ast_channel *chan, struct ast_frame *frame, enum ast_framehook_event event, void *data)
static void remb_values_free (void *data)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_DEFAULT , .description = "REMB Modifier Module" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .support_level = AST_MODULE_SUPPORT_EXTENDED, .load = load_module, .unload = unload_module, }
static const struct ast_module_info * ast_module_info = &__mod_info
static struct ast_cli_entry remb_cli []
static const struct ast_datastore_info remb_info
Detailed Description
REMB Modifier Module.
Author
Joshua Colp jcolp.nosp@m.@dig.nosp@m.ium.c.nosp@m.om
Definition in file res_remb_modifier.c.
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 268 of file res_remb_modifier.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 268 of file res_remb_modifier.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 268 of file res_remb_modifier.c.
handle_remb_set()
static char* handle_remb_set (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) static
Definition at line 155 of file res_remb_modifier.c.
References ast_cli_args::argc, ast_cli_args::argv, ast_calloc, ast_channel_datastore_add(), ast_channel_datastore_find(), ast_channel_get_by_name(), ast_channel_lock, ast_channel_unlock, ast_channel_unref, ast_cli(), ast_complete_channels(), ast_datastore_alloc, ast_framehook_attach(), ast_framehook_detach(), AST_FRAMEHOOK_INTERFACE_VERSION, ast_free, CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::command, ast_datastore::data, ast_cli_args::fd, ast_cli_args::line, ast_cli_args::n, NULL, ast_cli_args::pos, remb_values::receive_bitrate, remb_hook_event_cb(), remb_values::send_bitrate, ast_cli_entry::usage, ast_framehook_interface::version, and ast_cli_args::word.
 {
    struct ast_channel *chan;
    unsigned int bitrate;
    struct ast_datastore *remb_store;
    struct remb_values *remb_values;
    struct ast_framehook_interface interface = {
       .version = AST_FRAMEHOOK_INTERFACE_VERSION,
       .event_cb = remb_hook_event_cb,
    };
    switch(cmd) {
    case CLI_INIT:
       e->command = "remb set {send|receive}";
       e->usage =
          "Usage: remb set {send|receive} <channel> <bitrate in bits>\n"
          "       Set the REMB value which overwrites what we send or receive\n";
       return NULL;
    case CLI_GENERATE:
       return ast_complete_channels(a->line, a->word, a->pos, a->n, 3);
    }
    if (a->argc != 5) {
       return CLI_SHOWUSAGE;
    }
    if (sscanf(a->argv[4], "%30d", &bitrate) != 1) {
       ast_cli(a->fd, "%s is not a valid bitrate in bits\n", a->argv[4]);
       return CLI_SUCCESS;
    } else if (strcasecmp(a->argv[2], "send") && strcasecmp(a->argv[2], "receive")) {
       ast_cli(a->fd, "%s is not a valid direction for REMB\n", a->argv[2]);
       return CLI_SUCCESS;
    }
    chan = ast_channel_get_by_name(a->argv[3]);
    if (!chan) {
       ast_cli(a->fd, "%s is not a known channel\n", a->argv[3]);
       return CLI_SUCCESS;
    }
    ast_channel_lock(chan);
    remb_store = ast_channel_datastore_find(chan, &remb_info, NULL);
    if (!remb_store) {
       int framehook_id;
       framehook_id = ast_framehook_attach(chan, &interface);
       if (framehook_id < 0) {
          ast_cli(a->fd, "Could not attach framehook for modifying REMB\n");
          ast_channel_unlock(chan);
          ast_channel_unref(chan);
          return CLI_SUCCESS;
       }
       remb_values = ast_calloc(1, sizeof(*remb_values));
       if (!remb_values) {
          ast_cli(a->fd, "Could not create a place to store provided REMB value\n");
          ast_framehook_detach(chan, framehook_id);
          ast_channel_unlock(chan);
          ast_channel_unref(chan);
          return CLI_SUCCESS;
       }
       remb_store = ast_datastore_alloc(&remb_info, NULL);
       if (!remb_store) {
          ast_cli(a->fd, "Could not create a place to store provided REMB value\n");
          ast_framehook_detach(chan, framehook_id);
          ast_channel_unlock(chan);
          ast_channel_unref(chan);
          ast_free(remb_values);
          return CLI_SUCCESS;
       }
       remb_store->data = remb_values;
       ast_channel_datastore_add(chan, remb_store);
    } else {
       remb_values = remb_store->data;
    }
    if (!strcasecmp(a->argv[2], "send")) {
       remb_values->send_bitrate = bitrate;
    } else if (!strcasecmp(a->argv[2], "receive")) {
       remb_values->receive_bitrate = bitrate;
    }
    ast_channel_unlock(chan);
    ast_channel_unref(chan);
    ast_cli(a->fd, "Set REMB %s override to a bitrate of %s on %s\n", a->argv[2], a->argv[3], a->argv[4]);
    return CLI_SUCCESS;
 }
load_module()
static int load_module (void) static
Definition at line 252 of file res_remb_modifier.c.
References ARRAY_LEN, ast_cli_register_multiple, and AST_MODULE_LOAD_SUCCESS.
Referenced by unload_module().
 {
    ast_cli_register_multiple(remb_cli, ARRAY_LEN(remb_cli));
    return AST_MODULE_LOAD_SUCCESS;
 }
remb_hook_event_cb()
static struct ast_frame* remb_hook_event_cb (struct ast_channel * chan, struct ast_frame * frame, enum ast_framehook_event event, void * data) static
Definition at line 59 of file res_remb_modifier.c.
References ast_channel_datastore_find(), AST_FRAMEHOOK_EVENT_ATTACHED, AST_FRAMEHOOK_EVENT_DETACHED, AST_FRAMEHOOK_EVENT_READ, AST_FRAMEHOOK_EVENT_WRITE, AST_RTP_RTCP_FMT_REMB, AST_RTP_RTCP_PSFB, ast_rtp_rtcp_feedback_remb::br_exp, ast_rtp_rtcp_feedback_remb::br_mantissa, ast_datastore::data, ast_frame::data, ast_rtp_rtcp_feedback::fmt, ast_frame_subclass::integer, NULL, ast_frame::ptr, remb_values::receive_bitrate, ast_rtp_rtcp_feedback::remb, remb_values::send_bitrate, and ast_frame::subclass.
Referenced by handle_remb_set().
 {
    struct ast_rtp_rtcp_feedback *feedback;
    struct ast_datastore *remb_store;
    struct remb_values *remb_values;
    int exp;
    float bitrate = 0.0;
    if (!frame) {
       return NULL;
    }
    switch (event) {
    case AST_FRAMEHOOK_EVENT_READ:
    case AST_FRAMEHOOK_EVENT_WRITE:
       break;
    case AST_FRAMEHOOK_EVENT_ATTACHED:
    case AST_FRAMEHOOK_EVENT_DETACHED:
       return frame;
    }
    /* We only care about REMB frames, all others will be unmodified */
    if (frame->subclass.integer != AST_RTP_RTCP_PSFB) {
       return frame;
    }
    feedback = frame->data.ptr;
    if (feedback->fmt != AST_RTP_RTCP_FMT_REMB) {
       return frame;
    }
    remb_store = ast_channel_datastore_find(chan, &remb_info, NULL);
    if (!remb_store) {
       return frame;
    }
    remb_values = remb_store->data;
    /* If a bitrate override has been set apply it to the REMB Frame */
    if (event == AST_FRAMEHOOK_EVENT_READ && remb_values->receive_bitrate) {
       bitrate = remb_values->receive_bitrate;
    } else if (event == AST_FRAMEHOOK_EVENT_WRITE && remb_values->send_bitrate) {
       bitrate = remb_values->send_bitrate;
    } else {
       return frame;
    }
    /*
     * The mantissa only has 18 bits available, so make sure it fits. Adjust the
     * value and exponent for those values that don't.
     *
     * For example given the following:
     *
     * bitrate = 123456789.0
     * frexp(bitrate, &exp);
     *
     * 'exp' should now equal 27 (number of bits needed to represent the value). Since
     * the mantissa must fit into an 18-bit unsigned integer, and the given bitrate is
     * too large to fit, we must subtract 18 from the exponent in order to get the
     * number of times the bitrate will fit into that size integer.
     *
     * exp -= 18;
     *
     * 'exp' is now equal to 9. Now we can get the mantissa that fits into an 18-bit
     * unsigned integer by dividing the bitrate by 2^exp:
     *
     * mantissa = 123456789.0 / 2^9
     *
     * This makes the final mantissa equal to 241126 (implicitly cast), which is less
     * than 262143 (the max value that can be put into an unsigned 18-bit integer).
     * So now we have the following:
     *
     * exp = 9;
     * mantissa = 241126;
     *
     * If we multiply that back we should come up with something close to the original
     * bit rate:
     *
     * 241126 * 2^9 = 123456512
     *
     * Precision is lost due to the nature of floating point values. Easier to why from
     * the binary:
     *
     * 241126 * 2^9 = 241126 << 9 = 111010110111100110 << 9 = 111010110111100110000000000
     *
     * Precision on the "lower" end is lost due to zeros being shifted in. This loss is
     * both expected and acceptable.
     */
    frexp(bitrate, &exp);
    exp = exp > 18 ? exp - 18 : 0;
    feedback->remb.br_mantissa = bitrate / (1 << exp);
    feedback->remb.br_exp = exp;
    return frame;
 }
remb_values_free()
static void remb_values_free (void * data) static
Definition at line 49 of file res_remb_modifier.c.
References ast_free.
 {
    ast_free(data);
 }
unload_module()
static int unload_module (void) static
Definition at line 258 of file res_remb_modifier.c.
References ARRAY_LEN, ast_cli_unregister_multiple(), AST_MODFLAG_DEFAULT, AST_MODULE_INFO(), AST_MODULE_SUPPORT_EXTENDED, ASTERISK_GPL_KEY, and load_module().
 {
    ast_cli_unregister_multiple(remb_cli, ARRAY_LEN(remb_cli));
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_DEFAULT , .description = "REMB Modifier Module" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .support_level = AST_MODULE_SUPPORT_EXTENDED, .load = load_module, .unload = unload_module, } static
Definition at line 268 of file res_remb_modifier.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 268 of file res_remb_modifier.c.
remb_cli
struct ast_cli_entry remb_cli[] static
Initial value:
= {
   { .handler =  handle_remb_set , .summary =  "Set the REMB value which overwrites what is sent or received" ,},
}
Definition at line 248 of file res_remb_modifier.c.
remb_info
const struct ast_datastore_info remb_info static
Initial value:
= {
   .type = "REMB Values",
   .destroy = remb_values_free,
}
Definition at line 54 of file res_remb_modifier.c.