Asterisk - The Open Source Telephony Project: ast_timing_interface Struct Reference
ast_timing_interface Struct Reference
Timing module interface.
#include <timing.h>
Data Fields
const char * name
unsigned int priority
int(* timer_ack)(void *data, unsigned int quantity)
void(* timer_close)(void *data)
int(* timer_disable_continuous)(void *data)
int(* timer_enable_continuous)(void *data)
int(* timer_fd)(void *data)
enum ast_timer_event(* timer_get_event)(void *data)
unsigned int(* timer_get_max_rate)(void *data)
void *(* timer_open)(void)
int(* timer_set_rate)(void *data, unsigned int rate)
Detailed Description
Timing module interface.
The public API calls for the timing API directly map to this interface. So, the behavior of these calls should match the documentation of the public API calls.
Definition at line 69 of file timing.h.
Field Documentation
name
const char* name
Definition at line 70 of file timing.h.
Referenced by ast_timer_get_name(), PathSegment::get_child(), Parameter::load(), SwaggerType::load(), Property::load(), and timing_test().
priority
unsigned int priority
This handles the case where multiple timing modules are loaded. The highest priority timing interface available will be used.
Definition at line 73 of file timing.h.
Referenced by timing_holder_cmp().
timer_ack
int(* timer_ack) (void *data, unsigned int quantity)
Definition at line 77 of file timing.h.
Referenced by _ast_register_timing_interface(), and ast_timer_ack().
timer_close
void(* timer_close) (void *data)
Definition at line 75 of file timing.h.
Referenced by _ast_register_timing_interface(), ast_timer_close(), and ast_timer_open().
timer_disable_continuous
int(* timer_disable_continuous) (void *data)
Definition at line 79 of file timing.h.
Referenced by _ast_register_timing_interface(), and ast_timer_disable_continuous().
timer_enable_continuous
int(* timer_enable_continuous) (void *data)
Definition at line 78 of file timing.h.
Referenced by _ast_register_timing_interface(), and ast_timer_enable_continuous().
timer_fd
int(* timer_fd) (void *data)
Definition at line 82 of file timing.h.
Referenced by _ast_register_timing_interface(), and ast_timer_fd().
timer_get_event
enum ast_timer_event(* timer_get_event) (void *data)
Definition at line 80 of file timing.h.
Referenced by _ast_register_timing_interface(), and ast_timer_get_event().
timer_get_max_rate
unsigned int(* timer_get_max_rate) (void *data)
Definition at line 81 of file timing.h.
Referenced by _ast_register_timing_interface(), and ast_timer_get_max_rate().
timer_open
void*(* timer_open) (void)
Definition at line 74 of file timing.h.
Referenced by _ast_register_timing_interface(), and ast_timer_open().
timer_set_rate
int(* timer_set_rate) (void *data, unsigned int rate)
Definition at line 76 of file timing.h.
Referenced by _ast_register_timing_interface(), and ast_timer_set_rate().
The documentation for this struct was generated from the following file:
timing.h