Asterisk - The Open Source Telephony Project: func_dialgroup.c File Reference
func_dialgroup.c File Reference
Module: Dial plan functions
Dial group dialplan function.
#include "asterisk.h"
#include <sys/stat.h>
#include "asterisk/module.h"
#include "asterisk/channel.h"
#include "asterisk/pbx.h"
#include "asterisk/utils.h"
#include "asterisk/app.h"
#include "asterisk/astobj2.h"
#include "asterisk/astdb.h"
Data Structures
struct group
struct group_entry
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int dialgroup_read (struct ast_channel *chan, const char *cmd, char *data, char *buf, size_t len)
static int dialgroup_refreshdb (struct ast_channel *chan, const char *cdialgroup)
static int dialgroup_write (struct ast_channel *chan, const char *cmd, char *data, const char *cvalue)
static int entry_cmp_fn (void *obj1, void *name2, int flags)
static int entry_hash_fn (const void *obj, const int flags)
static int group_cmp_fn (void *obj1, void *name2, int flags)
static void group_destroy (void *vgroup)
static int group_hash_fn (const void *obj, const int flags)
static int load_module (void)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Dialgroup dialplan function" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, }
static const struct ast_module_info * ast_module_info = &__mod_info
static struct ast_custom_function dialgroup_function
static struct ao2_container * group_container = NULL
Detailed Description
Dial group dialplan function.
Author
Tilghman Lesher func_.nosp@m.dial.nosp@m.group.nosp@m.__20.nosp@m.0709@.nosp@m.the-.nosp@m.tilgh.nosp@m.man..nosp@m.com
Definition in file func_dialgroup.c.
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 323 of file func_dialgroup.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 323 of file func_dialgroup.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 323 of file func_dialgroup.c.
dialgroup_read()
static int dialgroup_read (struct ast_channel * chan, const char * cmd, char * data, char * buf, size_t len) static
Definition at line 127 of file func_dialgroup.c.
References ao2_find, ao2_iterator_destroy(), ao2_iterator_init(), ao2_iterator_next, ao2_ref, ast_copy_string(), ast_log, ast_strlen_zero, group::entries, LOG_WARNING, group_entry::name, and tmp().
Referenced by dialgroup_refreshdb().
 {
    struct ao2_iterator i;
    struct group *grhead = ao2_find(group_container, data, 0);
    struct group_entry *entry;
    size_t bufused = 0;
    int trunc_warning = 0;
    int res = 0;
    if (!grhead) {
       if (!ast_strlen_zero(cmd)) {
          ast_log(LOG_WARNING, "No such dialgroup '%s'\n", data);
       }
       return -1;
    }
    buf[0] = '\0';
    i = ao2_iterator_init(grhead->entries, 0);
    while ((entry = ao2_iterator_next(&i))) {
       int tmp = strlen(entry->name);
       /* Ensure that we copy only complete names, not partials */
       if (len - bufused > tmp + 2) {
          if (bufused != 0)
             buf[bufused++] = '&';
          ast_copy_string(buf + bufused, entry->name, len - bufused);
          bufused += tmp;
       } else if (trunc_warning++ == 0) {
          if (!ast_strlen_zero(cmd)) {
             ast_log(LOG_WARNING, "Dialgroup '%s' is too large.  Truncating list.\n", data);
          } else {
             res = 1;
             ao2_ref(entry, -1);
             break;
          }
       }
       ao2_ref(entry, -1);
    }
    ao2_iterator_destroy(&i);
    ao2_ref(grhead, -1);
    return res;
 }
dialgroup_refreshdb()
static int dialgroup_refreshdb (struct ast_channel * chan, const char * cdialgroup) static
Definition at line 171 of file func_dialgroup.c.
References ast_db_del(), ast_db_put(), ast_free, ast_realloc, ast_strdupa, ast_strlen_zero, buf, dialgroup_read(), len(), and NULL.
Referenced by dialgroup_write().
 {
    int len = 500, res = 0;
    char *buf = NULL;
    char *new_buf;
    char *dialgroup = ast_strdupa(cdialgroup);
    do {
       len *= 2;
       new_buf = ast_realloc(buf, len);
       if (!new_buf) {
          ast_free(buf);
          return -1;
       }
       buf = new_buf;
       if ((res = dialgroup_read(chan, "", dialgroup, buf, len)) < 0) {
          ast_free(buf);
          return -1;
       }
    } while (res == 1);
    if (ast_strlen_zero(buf)) {
       ast_db_del("dialgroup", cdialgroup);
    } else {
       ast_db_put("dialgroup", cdialgroup, buf);
    }
    ast_free(buf);
    return 0;
 }
dialgroup_write()
static int dialgroup_write (struct ast_channel * chan, const char * cmd, char * data, const char * cvalue) static
Definition at line 202 of file func_dialgroup.c.
References ao2_alloc, AO2_ALLOC_OPT_LOCK_MUTEX, ao2_container_alloc_hash, ao2_find, ao2_link, ao2_ref, ao2_unlink, args, AST_APP_ARG, ast_copy_string(), AST_DECLARE_APP_ARGS, ast_log, AST_NONSTANDARD_APP_ARGS, AST_STANDARD_APP_ARGS, ast_strdupa, ast_strlen_zero, dialgroup_refreshdb(), group::entries, entry_cmp_fn(), entry_hash_fn(), group_destroy(), LOG_ERROR, LOG_WARNING, group_entry::name, group::name, NULL, OBJ_UNLINK, and value.
Referenced by load_module().
 {
    struct group *grhead;
    struct group_entry *entry;
    int j, needrefresh = 1;
    AST_DECLARE_APP_ARGS(args,
       AST_APP_ARG(group);
       AST_APP_ARG(op);
    );
    AST_DECLARE_APP_ARGS(inter,
       AST_APP_ARG(faces)[100];
    );
    char *value = ast_strdupa(cvalue);
    AST_STANDARD_APP_ARGS(args, data);
    AST_NONSTANDARD_APP_ARGS(inter, value, '&');
    if (!(grhead = ao2_find(group_container, args.group, 0))) {
       /* Create group */
       grhead = ao2_alloc(sizeof(*grhead), group_destroy);
       if (!grhead)
          return -1;
       grhead->entries = ao2_container_alloc_hash(AO2_ALLOC_OPT_LOCK_MUTEX, 0, 37,
          entry_hash_fn, NULL, entry_cmp_fn);
       if (!grhead->entries) {
          ao2_ref(grhead, -1);
          return -1;
       }
       ast_copy_string(grhead->name, args.group, sizeof(grhead->name));
       ao2_link(group_container, grhead);
    }
    if (ast_strlen_zero(args.op)) {
       /* Wholesale replacement of the group */
       args.op = "add";
       /* Remove all existing */
       ao2_ref(grhead->entries, -1);
       grhead->entries = ao2_container_alloc_hash(AO2_ALLOC_OPT_LOCK_MUTEX, 0, 37,
          entry_hash_fn, NULL, entry_cmp_fn);
       if (!grhead->entries) {
          ao2_unlink(group_container, grhead);
          ao2_ref(grhead, -1);
          return -1;
       }
    }
    if (strcasecmp(args.op, "add") == 0) {
       for (j = 0; j < inter.argc; j++) {
          /* Eliminate duplicates */
          if ((entry = ao2_find(grhead->entries, inter.faces[j], 0))) {
             ao2_ref(entry, -1);
             continue;
          }
          if ((entry = ao2_alloc(sizeof(*entry), NULL))) {
             ast_copy_string(entry->name, inter.faces[j], sizeof(entry->name));
             ao2_link(grhead->entries, entry);
             ao2_ref(entry, -1);
          } else {
             ast_log(LOG_WARNING, "Unable to add '%s' to dialgroup '%s'\n", inter.faces[j], grhead->name);
          }
       }
    } else if (strncasecmp(args.op, "del", 3) == 0) {
       for (j = 0; j < inter.argc; j++) {
          if ((entry = ao2_find(grhead->entries, inter.faces[j], OBJ_UNLINK))) {
             ao2_ref(entry, -1);
          } else {
             ast_log(LOG_WARNING, "Interface '%s' not found in dialgroup '%s'\n", inter.faces[j], grhead->name);
          }
       }
    } else {
       ast_log(LOG_ERROR, "Unrecognized operation: %s\n", args.op);
       needrefresh = 0;
    }
    ao2_ref(grhead, -1);
    if (needrefresh) {
       dialgroup_refreshdb(chan, args.group);
    }
    return 0;
 }
entry_cmp_fn()
static int entry_cmp_fn (void * obj1, void * name2, int flags) static
Definition at line 117 of file func_dialgroup.c.
References CMP_MATCH, CMP_STOP, group_entry::name, and OBJ_POINTER.
Referenced by dialgroup_write().
 {
    struct group_entry *e1 = obj1, *e2 = name2;
    char *name = name2;
    if (flags & OBJ_POINTER)
       return strcmp(e1->name, e2->name) ? 0 : CMP_MATCH | CMP_STOP;
    else
       return strcmp(e1->name, name) ? 0 : CMP_MATCH | CMP_STOP;
 }
entry_hash_fn()
static int entry_hash_fn (const void * obj, const int flags) static
Definition at line 111 of file func_dialgroup.c.
References ast_str_hash(), and group_entry::name.
Referenced by dialgroup_write().
 {
    const struct group_entry *e = obj;
    return ast_str_hash(e->name);
 }
group_cmp_fn()
static int group_cmp_fn (void * obj1, void * name2, int flags) static
Definition at line 101 of file func_dialgroup.c.
References CMP_MATCH, CMP_STOP, group_entry::name, group::name, and OBJ_POINTER.
Referenced by load_module().
 {
    struct group *g1 = obj1, *g2 = name2;
    char *name = name2;
    if (flags & OBJ_POINTER)
       return strcmp(g1->name, g2->name) ? 0 : CMP_MATCH | CMP_STOP;
    else
       return strcmp(g1->name, name) ? 0 : CMP_MATCH | CMP_STOP;
 }
group_destroy()
static void group_destroy (void * vgroup) static
Definition at line 89 of file func_dialgroup.c.
References ao2_ref, and group::entries.
Referenced by dialgroup_write().
 {
    struct group *group = vgroup;
    ao2_ref(group->entries, -1);
 }
group_hash_fn()
static int group_hash_fn (const void * obj, const int flags) static
Definition at line 95 of file func_dialgroup.c.
References ast_str_hash(), and group::name.
Referenced by load_module().
 {
    const struct group *g = obj;
    return ast_str_hash(g->name);
 }
load_module()
static int load_module (void) static
Definition at line 298 of file func_dialgroup.c.
References AO2_ALLOC_OPT_LOCK_MUTEX, ao2_container_alloc_hash, ast_copy_string(), ast_custom_function_register, ast_db_freetree(), ast_db_gettree(), AST_MAX_EXTENSION, AST_MODULE_LOAD_DECLINE, ast_db_entry::data, dialgroup_write(), group_cmp_fn(), group_hash_fn(), ast_db_entry::key, ast_db_entry::next, NULL, and tmp().
 {
    struct ast_db_entry *dbtree, *tmp;
    char groupname[AST_MAX_EXTENSION], *ptr;
    group_container = ao2_container_alloc_hash(AO2_ALLOC_OPT_LOCK_MUTEX, 0, 37,
       group_hash_fn, NULL, group_cmp_fn);
    if (group_container) {
       /* Refresh groups from astdb */
       if ((dbtree = ast_db_gettree("dialgroup", NULL))) {
          for (tmp = dbtree; tmp; tmp = tmp->next) {
             ast_copy_string(groupname, tmp->key, sizeof(groupname));
             if ((ptr = strrchr(groupname, '/'))) {
                ptr++;
                dialgroup_write(NULL, "", ptr, tmp->data);
             }
          }
          ast_db_freetree(dbtree);
       }
       return ast_custom_function_register(&dialgroup_function);
    } else {
       return AST_MODULE_LOAD_DECLINE;
    }
 }
unload_module()
static int unload_module (void) static
Definition at line 291 of file func_dialgroup.c.
References ao2_ref, and ast_custom_function_unregister().
 {
    int res = ast_custom_function_unregister(&dialgroup_function);
    ao2_ref(group_container, -1);
    return res;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Dialgroup dialplan function" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, } static
Definition at line 323 of file func_dialgroup.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 323 of file func_dialgroup.c.
dialgroup_function
struct ast_custom_function dialgroup_function static
Initial value:
= {
   .name = "DIALGROUP",
   .read = dialgroup_read,
   .write = dialgroup_write,
}
Definition at line 285 of file func_dialgroup.c.
group_container
struct ao2_container* group_container = NULL static
Definition at line 78 of file func_dialgroup.c.