Asterisk - The Open Source Telephony Project: app_milliwatt.c File Reference
app_milliwatt.c File Reference
Dial plan applications
Digital Milliwatt Test.
#include "asterisk.h"
#include "asterisk/module.h"
#include "asterisk/channel.h"
#include "asterisk/pbx.h"
#include "asterisk/indications.h"
#include "asterisk/format_cache.h"
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int load_module (void)
static void * milliwatt_alloc (struct ast_channel *chan, void *params)
static int milliwatt_exec (struct ast_channel *chan, const char *data)
static int milliwatt_generate (struct ast_channel *chan, void *data, int len, int samples)
static void milliwatt_release (struct ast_channel *chan, void *data)
static int old_milliwatt_exec (struct ast_channel *chan)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Digital Milliwatt (mu-law) Test Application" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, }
static const char app [] = "Milliwatt"
static const struct ast_module_info * ast_module_info = &__mod_info
static const char digital_milliwatt [] = {0x1e,0x0b,0x0b,0x1e,0x9e,0x8b,0x8b,0x9e}
static struct ast_generator milliwattgen
Detailed Description
Digital Milliwatt Test.
Author
Mark Spencer marks.nosp@m.ter@.nosp@m.digiu.nosp@m.m.co.nosp@m.m
Definition in file app_milliwatt.c.
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 178 of file app_milliwatt.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 178 of file app_milliwatt.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 178 of file app_milliwatt.c.
load_module()
static int load_module (void) static
Definition at line 173 of file app_milliwatt.c.
References app, ast_register_application_xml, and milliwatt_exec().
 {
    return ast_register_application_xml(app, milliwatt_exec);
 }
milliwatt_alloc()
static void* milliwatt_alloc (struct ast_channel * chan, void * params) static
Definition at line 66 of file app_milliwatt.c.
References ast_calloc.
 {
    return ast_calloc(1, sizeof(int));
 }
milliwatt_exec()
static int milliwatt_exec (struct ast_channel * chan, const char * data) static
Definition at line 150 of file app_milliwatt.c.
References ast_playtones_start(), ast_safe_sleep(), ast_strlen_zero, old_milliwatt_exec(), and options.
Referenced by load_module().
 {
    const char *options = data;
    int res = -1;
    if (!ast_strlen_zero(options) && strchr(options, 'o')) {
       return old_milliwatt_exec(chan);
    }
    res = ast_playtones_start(chan, 23255, "1004/1000", 0);
    while (!res) {
       res = ast_safe_sleep(chan, 10000);
    }
    return res;
 }
milliwatt_generate()
static int milliwatt_generate (struct ast_channel * chan, void * data, int len, int samples) static
Definition at line 77 of file app_milliwatt.c.
References ARRAY_LEN, ast_channel_name(), ast_format_ulaw, AST_FRAME_VOICE, ast_frfree, AST_FRIENDLY_OFFSET, ast_log, ast_write(), buf, ast_frame::data, ast_frame::datalen, digital_milliwatt, errno, ast_frame_subclass::format, ast_frame::frametype, len(), LOG_WARNING, ast_frame::ptr, ast_frame::samples, and ast_frame::subclass.
 {
    unsigned char buf[AST_FRIENDLY_OFFSET + 640];
    const int maxsamples = ARRAY_LEN(buf) - (AST_FRIENDLY_OFFSET / sizeof(buf[0]));
    int i, *indexp = (int *) data, res;
    struct ast_frame wf = {
       .frametype = AST_FRAME_VOICE,
       .offset = AST_FRIENDLY_OFFSET,
       .src = __FUNCTION__,
    };
    wf.subclass.format = ast_format_ulaw;
    wf.data.ptr = buf + AST_FRIENDLY_OFFSET;
    /* Instead of len, use samples, because channel.c generator_force
    * generate(chan, tmp, 0, 160) ignores len. In any case, len is
    * a multiple of samples, given by number of samples times bytes per
    * sample. In the case of ulaw, len = samples. for signed linear
    * len = 2 * samples */
    if (samples > maxsamples) {
       ast_log(LOG_WARNING, "Only doing %d samples (%d requested)\n", maxsamples, samples);
       samples = maxsamples;
    }
    len = samples * sizeof (buf[0]);
    wf.datalen = len;
    wf.samples = samples;
    /* create a buffer containing the digital milliwatt pattern */
    for (i = 0; i < len; i++) {
       buf[AST_FRIENDLY_OFFSET + i] = digital_milliwatt[(*indexp)++];
       *indexp &= 7;
    }
    res = ast_write(chan, &wf);
    ast_frfree(&wf);
    if (res < 0) {
       ast_log(LOG_WARNING,"Failed to write frame to '%s': %s\n",ast_channel_name(chan),strerror(errno));
       return -1;
    }
    return 0;
 }
milliwatt_release()
static void milliwatt_release (struct ast_channel * chan, void * data) static
Definition at line 71 of file app_milliwatt.c.
References ast_free.
 {
    ast_free(data);
    return;
 }
old_milliwatt_exec()
static int old_milliwatt_exec (struct ast_channel * chan) static
Definition at line 128 of file app_milliwatt.c.
References ast_activate_generator(), ast_answer(), ast_channel_name(), ast_deactivate_generator(), ast_format_ulaw, ast_log, ast_safe_sleep(), ast_set_read_format(), ast_set_write_format(), AST_STATE_UP, and LOG_WARNING.
Referenced by milliwatt_exec().
 {
    ast_set_write_format(chan, ast_format_ulaw);
    ast_set_read_format(chan, ast_format_ulaw);
    if (ast_channel_state(chan) != AST_STATE_UP) {
       ast_answer(chan);
    }
    if (ast_activate_generator(chan,&milliwattgen,"milliwatt") < 0) {
       ast_log(LOG_WARNING,"Failed to activate generator on '%s'\n",ast_channel_name(chan));
       return -1;
    }
    while (!ast_safe_sleep(chan, 10000))
       ;
    ast_deactivate_generator(chan);
    return -1;
 }
unload_module()
static int unload_module (void) static
Definition at line 168 of file app_milliwatt.c.
References app, and ast_unregister_application().
 {
    return ast_unregister_application(app);
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Digital Milliwatt (mu-law) Test Application" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, } static
Definition at line 178 of file app_milliwatt.c.
app
const char app[] = "Milliwatt" static
Definition at line 62 of file app_milliwatt.c.
Referenced by load_module(), and unload_module().
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 178 of file app_milliwatt.c.
digital_milliwatt
const char digital_milliwatt[] = {0x1e,0x0b,0x0b,0x1e,0x9e,0x8b,0x8b,0x9e} static
Definition at line 64 of file app_milliwatt.c.
Referenced by milliwatt_generate().
milliwattgen
struct ast_generator milliwattgen static
Initial value:
= {
   .alloc = milliwatt_alloc,
   .release = milliwatt_release,
   .generate = milliwatt_generate,
}
Definition at line 122 of file app_milliwatt.c.