Asterisk - The Open Source Telephony Project: Stasis topics, and their messages.
Stasis topics, and their messages.
This group contains the topics, messages and corresponding message types found within Asterisk.
Data Structures
struct ast_channel_blob
Blob of data associated with a channel.
struct ast_channel_snapshot
Structure representing a snapshot of channel state.
struct ast_channel_snapshot_base
Structure containing base information for a channel snapshot.
struct ast_channel_snapshot_bridge
Structure containing bridge information for a channel snapshot.
struct ast_channel_snapshot_caller
Structure containing caller information for a channel snapshot.
struct ast_channel_snapshot_connected
Structure containing connected information for a channel snapshot.
struct ast_channel_snapshot_dialplan
Structure containing dialplan information for a channel snapshot.
struct ast_channel_snapshot_hangup
Structure containing hangup information for a channel snapshot.
struct ast_channel_snapshot_peer
Structure containing peer information for a channel snapshot.
struct ast_channel_snapshot_update
Structure representing a change of snapshot of channel state.
struct ast_endpoint_blob
Blob of data associated with an endpoint.
struct ast_endpoint_snapshot
A snapshot of an endpoint's state.
struct ast_mwi_blob
Object that represents an MWI update with some additional application defined data.
struct ast_mwi_state
The structure that contains MWI state.
struct stasis_cache_update
Cache update message.
struct stasis_subscription_change
Holds details about changes to subscriptions for the specified topic.
Macros
#define AST_DEBUG_CATEGORY_DTLS ast_debug_category_dtls_id() /* DTLS debug logging category id */
#define AST_DEBUG_CATEGORY_DTLS_PACKET ast_debug_category_dtls_packet_id() /* DTLS packet debug logging category id */
#define AST_DEBUG_CATEGORY_ICE ast_debug_category_ice_id() /* ICE debug logging category id */
#define AST_DEBUG_CATEGORY_RTCP ast_debug_category_rtcp_id() /* RTCP debug logging category id */
#define AST_DEBUG_CATEGORY_RTCP_PACKET ast_debug_category_rtcp_packet_id() /* RTCP packet debug logging category id */
#define AST_DEBUG_CATEGORY_RTP ast_debug_category_rtp_id() /* RTP debug logging category id */
#define AST_DEBUG_CATEGORY_RTP_PACKET ast_debug_category_rtp_packet_id() /* RTP packet debug logging category id */
#define ast_debug_dtls(sublevel, ...) ast_debug_category(sublevel, AST_DEBUG_CATEGORY_DTLS, __VA_ARGS__)
Log debug level DTLS information.
#define ast_debug_dtls_packet_is_allowed ast_debug_category_is_allowed(AST_LOG_CATEGORY_ENABLED, AST_DEBUG_CATEGORY_DTLS_PACKET)
#define ast_debug_ice(sublevel, ...) ast_debug_category(sublevel, AST_DEBUG_CATEGORY_ICE, __VA_ARGS__)
Log debug level ICE information.
#define ast_debug_rtcp(sublevel, ...) ast_debug_category(sublevel, AST_DEBUG_CATEGORY_RTCP, __VA_ARGS__)
Log debug level RTCP information.
#define ast_debug_rtcp_packet_is_allowed ast_debug_category_is_allowed(AST_LOG_CATEGORY_ENABLED, AST_DEBUG_CATEGORY_RTCP_PACKET)
#define ast_debug_rtp(sublevel, ...) ast_debug_category(sublevel, AST_DEBUG_CATEGORY_RTP, __VA_ARGS__)
Log debug level RTP information.
#define ast_debug_rtp_packet_is_allowed ast_debug_category_is_allowed(AST_LOG_CATEGORY_ENABLED, AST_DEBUG_CATEGORY_RTP_PACKET)
#define AST_LOG_CATEGORY_DTLS "dtls"
#define AST_LOG_CATEGORY_DTLS_PACKET "dtls_packet"
#define AST_LOG_CATEGORY_ICE "ice"
#define AST_LOG_CATEGORY_RTCP "rtcp"
#define AST_LOG_CATEGORY_RTCP_PACKET "rtcp_packet"
#define AST_LOG_CATEGORY_RTP "rtp"
#define AST_LOG_CATEGORY_RTP_PACKET "rtp_packet"
#define AST_MAX_MAILBOX_UNIQUEID (AST_MAX_EXTENSION + AST_MAX_CONTEXT + 2)
#define STASIS_UMOS_MAX (STASIS_UMOS_ENDPOINT + 1)
Number of snapshot types.
Enumerations
enum ast_channel_snapshot_segment_invalidation {
AST_CHANNEL_SNAPSHOT_INVALIDATE_BRIDGE = (1 << 1), AST_CHANNEL_SNAPSHOT_INVALIDATE_DIALPLAN = (1 << 2), AST_CHANNEL_SNAPSHOT_INVALIDATE_CONNECTED = (1 << 3), AST_CHANNEL_SNAPSHOT_INVALIDATE_CALLER = (1 << 4),
AST_CHANNEL_SNAPSHOT_INVALIDATE_HANGUP = (1 << 5), AST_CHANNEL_SNAPSHOT_INVALIDATE_PEER = (1 << 6), AST_CHANNEL_SNAPSHOT_INVALIDATE_BASE = (1 << 7)
}
Channel snapshot invalidation flags, used to force generation of segments.
enum stasis_user_multi_object_snapshot_type { STASIS_UMOS_CHANNEL = 0, STASIS_UMOS_BRIDGE, STASIS_UMOS_ENDPOINT }
Object type code for multi user object snapshots.
Functions
struct stasis_message_type * ast_channel_agent_login_type (void)
Message type for agent login on a channel.
struct stasis_message_type * ast_channel_agent_logoff_type (void)
Message type for agent logoff on a channel.
struct stasis_message * ast_channel_blob_create (struct ast_channel *chan, struct stasis_message_type *type, struct ast_json *blob)
Creates a ast_channel_blob message.
struct stasis_message * ast_channel_blob_create_from_cache (const char *uniqueid, struct stasis_message_type *type, struct ast_json *blob)
Create a ast_channel_blob message, pulling channel state from the cache.
struct ao2_container * ast_channel_cache_all (void)
struct ao2_container * ast_channel_cache_by_name (void)
Secondary channel cache, indexed by name.
struct stasis_message_type * ast_channel_chanspy_start_type (void)
Message type for when a channel starts spying on another channel.
struct stasis_message_type * ast_channel_chanspy_stop_type (void)
Message type for when a channel stops spying on another channel.
struct stasis_message_type * ast_channel_dial_type (void)
Message type for when a channel dials another channel.
struct stasis_message_type * ast_channel_dtmf_begin_type (void)
Message type for when DTMF begins on a channel.
struct stasis_message_type * ast_channel_dtmf_end_type (void)
Message type for when DTMF ends on a channel.
struct stasis_message_type * ast_channel_fax_type (void)
Message type for a fax operation.
struct stasis_message_type * ast_channel_flash_type (void)
Message type for when a hook flash occurs on a channel.
struct stasis_message_type * ast_channel_hangup_handler_type (void)
Message type for hangup handler related actions.
struct stasis_message_type * ast_channel_hangup_request_type (void)
Message type for when a hangup is requested on a channel.
struct stasis_message_type * ast_channel_hold_type (void)
Message type for when a channel is placed on hold.
struct stasis_message_type * ast_channel_masquerade_type (void)
Message type for when a channel is being masqueraded.
struct stasis_message_type * ast_channel_mixmonitor_mute_type (void)
Message type for muting or unmuting mixmonitor on a channel.
struct stasis_message_type * ast_channel_mixmonitor_start_type (void)
Message type for starting mixmonitor on a channel.
struct stasis_message_type * ast_channel_mixmonitor_stop_type (void)
Message type for stopping mixmonitor on a channel.
struct stasis_message_type * ast_channel_moh_start_type (void)
Message type for starting music on hold on a channel.
struct stasis_message_type * ast_channel_moh_stop_type (void)
Message type for stopping music on hold on a channel.
struct stasis_message_type * ast_channel_monitor_start_type (void)
Message type for starting monitor on a channel.
struct stasis_message_type * ast_channel_monitor_stop_type (void)
Message type for stopping monitor on a channel.
void ast_channel_publish_blob (struct ast_channel *chan, struct stasis_message_type *type, struct ast_json *blob)
Publish a channel blob message.
void ast_channel_publish_cached_blob (struct ast_channel *chan, struct stasis_message_type *type, struct ast_json *blob)
Publish a channel blob message using the latest snapshot from the cache.
void ast_channel_publish_dial (struct ast_channel *caller, struct ast_channel *peer, const char *dialstring, const char *dialstatus)
Publish in the ast_channel_topic or ast_channel_topic_all topics a stasis message for the channels involved in a dial operation.
void ast_channel_publish_dial_forward (struct ast_channel *caller, struct ast_channel *peer, struct ast_channel *forwarded, const char *dialstring, const char *dialstatus, const char *forward)
Publish in the ast_channel_topic or ast_channel_topic_all topics a stasis message for the channels involved in a dial operation that is forwarded.
void ast_channel_publish_final_snapshot (struct ast_channel *chan)
Send the final channel snapshot for a channel, thus removing it from cache.
void ast_channel_publish_snapshot (struct ast_channel *chan)
Publish a ast_channel_snapshot for a channel.
void ast_channel_publish_varset (struct ast_channel *chan, const char *variable, const char *value)
Publish a ast_channel_varset for a channel.
struct ast_channel_snapshot * ast_channel_snapshot_create (struct ast_channel *chan)
Generate a snapshot of the channel state. This is an ao2 object, so ao2_cleanup() to deallocate.
struct ast_channel_snapshot * ast_channel_snapshot_get_latest (const char *uniqueid)
Obtain the latest ast_channel_snapshot from the Stasis Message Bus API cache. This is an ao2 object, so use ao2_cleanup() to deallocate.
struct ast_channel_snapshot * ast_channel_snapshot_get_latest_by_name (const char *name)
Obtain the latest ast_channel_snapshot from the Stasis Message Bus API cache. This is an ao2 object, so use ao2_cleanup() to deallocate.
void ast_channel_snapshot_invalidate_segment (struct ast_channel *chan, enum ast_channel_snapshot_segment_invalidation segment)
Invalidate a channel snapshot segment from being reused.
struct stasis_message_type * ast_channel_snapshot_type (void)
Message type for ast_channel_snapshot_update.
void ast_channel_stage_snapshot (struct ast_channel *chan)
Set flag to indicate channel snapshot is being staged.
void ast_channel_stage_snapshot_done (struct ast_channel *chan)
Clear flag to indicate channel snapshot is being staged, and publish snapshot.
struct stasis_message_type * ast_channel_talking_start (void)
Message type for a channel starting talking.
struct stasis_message_type * ast_channel_talking_stop (void)
Message type for a channel stopping talking.
struct stasis_topic * ast_channel_topic_all (void)
A topic which publishes the events for all channels.
struct stasis_message_type * ast_channel_unhold_type (void)
Message type for when a channel is removed from hold.
struct stasis_message_type * ast_channel_varset_type (void)
Message type for when a variable is set on a channel.
uintmax_t ast_debug_category_dtls_id (void)
uintmax_t ast_debug_category_dtls_packet_id (void)
uintmax_t ast_debug_category_ice_id (void)
uintmax_t ast_debug_category_rtcp_id (void)
uintmax_t ast_debug_category_rtcp_packet_id (void)
uintmax_t ast_debug_category_rtp_id (void)
uintmax_t ast_debug_category_rtp_packet_id (void)
struct stasis_message * ast_endpoint_blob_create (struct ast_endpoint *endpoint, struct stasis_message_type *type, struct ast_json *blob)
Creates a ast_endpoint_blob message.
void ast_endpoint_blob_publish (struct ast_endpoint *endpoint, struct stasis_message_type *type, struct ast_json *blob)
Creates and publishes a ast_endpoint_blob message.
struct stasis_cache * ast_endpoint_cache (void)
Backend cache for ast_endpoint_topic_all_cached().
struct stasis_cp_all * ast_endpoint_cache_all (void)
struct stasis_message_type * ast_endpoint_contact_state_type (void)
Message type for endpoint contact state changes.
struct ast_endpoint_snapshot * ast_endpoint_latest_snapshot (const char *tech, const char *resource)
Retrieve the most recent snapshot for the endpoint with the given name.
struct ast_endpoint_snapshot * ast_endpoint_snapshot_create (struct ast_endpoint *endpoint)
Create a snapshot of an endpoint.
struct stasis_message_type * ast_endpoint_snapshot_type (void)
Message type for ast_endpoint_snapshot.
struct stasis_message_type * ast_endpoint_state_type (void)
Message type for endpoint state changes.
struct stasis_topic * ast_endpoint_topic (struct ast_endpoint *endpoint)
Returns the topic for a specific endpoint.
struct stasis_topic * ast_endpoint_topic_all (void)
Topic for all endpoint releated messages.
struct stasis_topic * ast_endpoint_topic_all_cached (void)
Cached topic for all endpoint related messages.
struct stasis_topic * ast_endpoint_topic_cached (struct ast_endpoint *endpoint)
Returns the topic for a specific endpoint.
void ast_multi_channel_blob_add_channel (struct ast_multi_channel_blob *obj, const char *role, struct ast_channel_snapshot *snapshot)
Add a ast_channel_snapshot to a ast_multi_channel_blob object.
struct ast_multi_channel_blob * ast_multi_channel_blob_create (struct ast_json *blob)
Create a ast_multi_channel_blob suitable for a stasis_message.
struct ast_channel_snapshot * ast_multi_channel_blob_get_channel (struct ast_multi_channel_blob *obj, const char *role)
Retrieve a channel snapshot associated with a specific role from a ast_multi_channel_blob.
struct ao2_container * ast_multi_channel_blob_get_channels (struct ast_multi_channel_blob *obj, const char *role)
Retrieve all channel snapshots associated with a specific role from a ast_multi_channel_blob.
struct ast_json * ast_multi_channel_blob_get_json (struct ast_multi_channel_blob *obj)
Retrieve the JSON blob from a ast_multi_channel_blob. Returned ast_json is still owned by obj.
void ast_multi_object_blob_add (struct ast_multi_object_blob *multi, enum stasis_user_multi_object_snapshot_type type, void *object)
Add an object to a multi object blob previously created.
struct ast_multi_object_blob * ast_multi_object_blob_create (struct ast_json *blob)
Create a stasis multi object blob.
void ast_multi_object_blob_single_channel_publish (struct ast_channel *chan, struct stasis_message_type *type, struct ast_json *blob)
Create and publish a stasis message blob on a channel with it's snapshot.
struct stasis_message_type * ast_multi_user_event_type (void)
Message type for custom user defined events with multi object blobs.
struct stasis_message * ast_mwi_blob_create (struct ast_mwi_state *mwi_state, struct stasis_message_type *message_type, struct ast_json *blob)
Creates a ast_mwi_blob message.
struct ast_mwi_state * ast_mwi_create (const char *mailbox, const char *context)
Create a ast_mwi_state object.
struct stasis_cache * ast_mwi_state_cache (void)
Backend cache for ast_mwi_topic_cached().
struct stasis_message_type * ast_mwi_state_type (void)
Get the Stasis Message Bus API message type for MWI messages.
struct stasis_topic * ast_mwi_topic (const char *uniqueid)
Get the Stasis Message Bus API topic for MWI messages on a unique ID.
struct stasis_topic * ast_mwi_topic_all (void)
Get the Stasis Message Bus API topic for MWI messages.
struct stasis_topic * ast_mwi_topic_cached (void)
Get the Stasis Message Bus API caching topic for MWI messages.
struct stasis_message_type * ast_mwi_vm_app_type (void)
Get the Stasis Message Bus API message type for voicemail application specific messages.
struct stasis_message_type * ast_parked_call_type (void)
accessor for the parked call stasis message type
struct stasis_topic * ast_parking_topic (void)
accessor for the parking stasis topic
struct ast_json * ast_rtp_convert_stats_json (const struct ast_rtp_instance_stats *stats)
Convert given stat instance into json format.
int ast_rtp_get_rate (const struct ast_format *format)
Retrieve the sample rate of a format according to RTP specifications.
void ast_rtp_instance_drop_packets (struct ast_rtp_instance *instance, int num)
Set the number of packets to drop on RTP read.
size_t ast_rtp_instance_get_recv_buffer_count (struct ast_rtp_instance *instance)
Get the current size of the receive buffer.
size_t ast_rtp_instance_get_recv_buffer_max (struct ast_rtp_instance *instance)
Get the maximum size of the receive buffer.
int ast_rtp_instance_get_sdes_received (struct ast_rtp_instance *instance)
Get the value of sdes_received on the test engine.
size_t ast_rtp_instance_get_send_buffer_count (struct ast_rtp_instance *instance)
Get the current size of the send buffer.
struct ast_json * ast_rtp_instance_get_stats_all_json (struct ast_rtp_instance *instance)
Retrieve statistics about an RTP instance in json format.
void ast_rtp_instance_queue_report (struct ast_rtp_instance *instance)
Sends a SR/RR report the next time RTP would be sent.
void ast_rtp_instance_reset_test_engine (struct ast_rtp_instance *instance)
Resets all the fields to default values for the test engine.
void ast_rtp_instance_set_schedid (struct ast_rtp_instance *instance, int id)
Set the schedid for RTCP.
struct stasis_message_type * ast_rtp_rtcp_received_type (void)
Message type for an RTCP message received from some external source.
struct stasis_message_type * ast_rtp_rtcp_sent_type (void)
Message type for an RTCP message sent from this Asterisk instance.
struct stasis_topic * ast_rtp_topic (void)
Stasis Message Bus API topic for RTP and RTCP related messages
int mwi_init (void)
Initialize the mwi core.
struct stasis_message_type * stasis_cache_clear_type (void)
Message type for clearing a message from a stasis cache.
struct stasis_message_type * stasis_cache_update_type (void)
Message type for cache update messages.
struct stasis_message_type * stasis_subscription_change_type (void)
Gets the message type for subscription change notices.
struct stasis_message * stasis_test_message_create (void)
Creates a test message.
struct stasis_message_type * stasis_test_message_type (void)
Gets the type of messages created by stasis_test_message_create().
Variables
struct ast_string_field_mgr __field_mgr
struct ast_string_field_pool * __field_mgr_pool
struct ast_json * blob
struct ast_eid eid
struct ast_mwi_state * mwi_state
int new_msgs
int old_msgs
void(* on_subscribe)(const char *mailbox, struct ast_mwi_subscriber *sub)
Raised when MWI is being subscribed.
void(* on_unsubscribe)(const char *mailbox, struct ast_mwi_subscriber *sub)
Raised when MWI is being unsubscribed.
struct ast_channel_snapshot * snapshot
const ast_string_field uniqueid
int urgent_msgs
Detailed Description
This group contains the topics, messages and corresponding message types found within Asterisk.
Macro Definition Documentation
AST_DEBUG_CATEGORY_DTLS
#define AST_DEBUG_CATEGORY_DTLS ast_debug_category_dtls_id() /* DTLS debug logging category id */
Definition at line 2850 of file rtp_engine.h.
Referenced by ast_rtp_ice_start_media().
AST_DEBUG_CATEGORY_DTLS_PACKET
#define AST_DEBUG_CATEGORY_DTLS_PACKET ast_debug_category_dtls_packet_id() /* DTLS packet debug logging category id */
Definition at line 2851 of file rtp_engine.h.
AST_DEBUG_CATEGORY_ICE
#define AST_DEBUG_CATEGORY_ICE ast_debug_category_ice_id() /* ICE debug logging category id */
Definition at line 2852 of file rtp_engine.h.
Referenced by ast_rtp_ice_start_media(), and rtp_add_candidates_to_ice().
AST_DEBUG_CATEGORY_RTCP
#define AST_DEBUG_CATEGORY_RTCP ast_debug_category_rtcp_id() /* RTCP debug logging category id */
Definition at line 2848 of file rtp_engine.h.
AST_DEBUG_CATEGORY_RTCP_PACKET
#define AST_DEBUG_CATEGORY_RTCP_PACKET ast_debug_category_rtcp_packet_id() /* RTCP packet debug logging category id */
Definition at line 2849 of file rtp_engine.h.
AST_DEBUG_CATEGORY_RTP
#define AST_DEBUG_CATEGORY_RTP ast_debug_category_rtp_id() /* RTP debug logging category id */
Definition at line 2846 of file rtp_engine.h.
AST_DEBUG_CATEGORY_RTP_PACKET
#define AST_DEBUG_CATEGORY_RTP_PACKET ast_debug_category_rtp_packet_id() /* RTP packet debug logging category id */
Definition at line 2847 of file rtp_engine.h.
ast_debug_dtls
#define ast_debug_dtls (sublevel, ...) ast_debug_category(sublevel, AST_DEBUG_CATEGORY_DTLS, __VA_ARGS__)
Log debug level DTLS information.
Parameters
sublevel Debug output sublevel (>= 0)
... String format and any associated arguments
Definition at line 2886 of file rtp_engine.h.
Referenced by __rtp_recvfrom(), ast_rtp_bundle(), and rtcp_debug_test_addr().
ast_debug_dtls_packet_is_allowed
#define ast_debug_dtls_packet_is_allowed ast_debug_category_is_allowed(AST_LOG_CATEGORY_ENABLED, AST_DEBUG_CATEGORY_DTLS_PACKET)
Definition at line 2890 of file rtp_engine.h.
ast_debug_ice
#define ast_debug_ice (sublevel, ...) ast_debug_category(sublevel, AST_DEBUG_CATEGORY_ICE, __VA_ARGS__)
Log debug level ICE information.
Parameters
sublevel Debug output sublevel (>= 0)
... String format and any associated arguments
Definition at line 2898 of file rtp_engine.h.
Referenced by ast_rtp_ice_add_cand(), ast_rtp_ice_add_remote_candidate(), ast_rtp_ice_change_components(), ast_rtp_ice_set_role(), ast_rtp_ice_start(), ast_rtp_ice_stop(), ast_rtp_ice_turn_request(), ast_rtp_on_ice_complete(), ast_rtp_on_valid_pair(), ice_create(), ice_reset_session(), process_ice_attributes(), rtp_add_candidates_to_ice(), rtp_allocate_transport(), and rtp_deallocate_transport().
ast_debug_rtcp
#define ast_debug_rtcp (sublevel, ...) ast_debug_category(sublevel, AST_DEBUG_CATEGORY_RTCP, __VA_ARGS__)
Log debug level RTCP information.
Parameters
sublevel Debug output sublevel (>= 0)
... String format and any associated arguments
Definition at line 2873 of file rtp_engine.h.
Referenced by ast_rtcp_generate_compound_prefix(), ast_rtcp_interpret(), ast_rtp_prop_set(), ast_rtp_read(), ast_rtp_remote_address_set(), ast_rtp_rtcp_handle_nack(), rtp_instance_parse_transport_wide_cc(), rtp_raw_write(), rtp_transport_wide_cc_feedback_produce(), and rtp_write_rtcp_psfb().
ast_debug_rtcp_packet_is_allowed
#define ast_debug_rtcp_packet_is_allowed ast_debug_category_is_allowed(AST_LOG_CATEGORY_ENABLED, AST_DEBUG_CATEGORY_RTCP_PACKET)
Definition at line 2877 of file rtp_engine.h.
Referenced by rtcp_debug_test_addr().
ast_debug_rtp
#define ast_debug_rtp (sublevel, ...) ast_debug_category(sublevel, AST_DEBUG_CATEGORY_RTP, __VA_ARGS__)
Log debug level RTP information.
Parameters
sublevel Debug output sublevel (>= 0)
... String format and any associated arguments
Definition at line 2860 of file rtp_engine.h.
Referenced by ast_rtp_change_source(), ast_rtp_dtmf_end_with_duration(), ast_rtp_read(), ast_rtp_update_source(), ast_rtp_write(), bridge_p2p_rtp_write(), create_dtmf_frame(), create_rtp(), process_dtmf_rfc2833(), rtp_allocate_transport(), rtp_check_timeout(), rtp_raw_write(), and send_keepalive().
ast_debug_rtp_packet_is_allowed
#define ast_debug_rtp_packet_is_allowed ast_debug_category_is_allowed(AST_LOG_CATEGORY_ENABLED, AST_DEBUG_CATEGORY_RTP_PACKET)
Definition at line 2864 of file rtp_engine.h.
Referenced by ast_rtcp_interpret(), ast_rtp_interpret(), ast_rtp_read(), bridge_p2p_rtp_write(), process_cn_rfc3389(), process_dtmf_cisco(), process_dtmf_rfc2833(), rtp_debug_test_addr(), and rtp_raw_write().
AST_LOG_CATEGORY_DTLS
#define AST_LOG_CATEGORY_DTLS "dtls"
Definition at line 2832 of file rtp_engine.h.
Referenced by ast_rtp_engine_init(), and rtp_engine_shutdown().
AST_LOG_CATEGORY_DTLS_PACKET
#define AST_LOG_CATEGORY_DTLS_PACKET "dtls_packet"
Definition at line 2834 of file rtp_engine.h.
Referenced by ast_rtp_engine_init(), and rtp_engine_shutdown().
AST_LOG_CATEGORY_ICE
#define AST_LOG_CATEGORY_ICE "ice"
Definition at line 2836 of file rtp_engine.h.
Referenced by ast_rtp_engine_init(), and rtp_engine_shutdown().
AST_LOG_CATEGORY_RTCP
#define AST_LOG_CATEGORY_RTCP "rtcp"
Definition at line 2828 of file rtp_engine.h.
Referenced by ast_rtp_engine_init(), and rtp_engine_shutdown().
AST_LOG_CATEGORY_RTCP_PACKET
#define AST_LOG_CATEGORY_RTCP_PACKET "rtcp_packet"
Definition at line 2830 of file rtp_engine.h.
Referenced by ast_rtp_engine_init(), handle_cli_rtcp_set_debug(), rtcp_do_debug_ip(), and rtp_engine_shutdown().
AST_LOG_CATEGORY_RTP
#define AST_LOG_CATEGORY_RTP "rtp"
Definition at line 2824 of file rtp_engine.h.
Referenced by ast_rtp_engine_init(), and rtp_engine_shutdown().
AST_LOG_CATEGORY_RTP_PACKET
#define AST_LOG_CATEGORY_RTP_PACKET "rtp_packet"
Definition at line 2826 of file rtp_engine.h.
Referenced by ast_rtp_engine_init(), handle_cli_rtp_set_debug(), rtp_do_debug_ip(), and rtp_engine_shutdown().
AST_MAX_MAILBOX_UNIQUEID
#define AST_MAX_MAILBOX_UNIQUEID (AST_MAX_EXTENSION + AST_MAX_CONTEXT + 2)
Definition at line 574 of file mwi.h.
Referenced by build_peer().
STASIS_UMOS_MAX
#define STASIS_UMOS_MAX (STASIS_UMOS_ENDPOINT + 1)
Number of snapshot types.
Definition at line 1364 of file stasis.h.
Referenced by ast_multi_object_blob_create(), multi_object_blob_dtor(), multi_object_blob_to_ami(), and multi_user_event_to_json().
Enumeration Type Documentation
ast_channel_snapshot_segment_invalidation
enum ast_channel_snapshot_segment_invalidation
Channel snapshot invalidation flags, used to force generation of segments.
Since
17
Enumerator
AST_CHANNEL_SNAPSHOT_INVALIDATE_BRIDGE
Invalidate the bridge segment
AST_CHANNEL_SNAPSHOT_INVALIDATE_DIALPLAN
Invalidate the dialplan segment
AST_CHANNEL_SNAPSHOT_INVALIDATE_CONNECTED
Invalidate the connected segment
AST_CHANNEL_SNAPSHOT_INVALIDATE_CALLER
Invalidate the caller segment
AST_CHANNEL_SNAPSHOT_INVALIDATE_HANGUP
Invalidate the hangup segment
AST_CHANNEL_SNAPSHOT_INVALIDATE_PEER
Invalidate the peer segment
AST_CHANNEL_SNAPSHOT_INVALIDATE_BASE
Invalidate the base segment
Definition at line 35 of file stasis_channels.h.
{
    /*! Invalidate the bridge segment */
    AST_CHANNEL_SNAPSHOT_INVALIDATE_BRIDGE = (1 << 1),
    /*! Invalidate the dialplan segment */
    AST_CHANNEL_SNAPSHOT_INVALIDATE_DIALPLAN = (1 << 2),
    /*! Invalidate the connected segment */
    AST_CHANNEL_SNAPSHOT_INVALIDATE_CONNECTED = (1 << 3),
    /*! Invalidate the caller segment */
    AST_CHANNEL_SNAPSHOT_INVALIDATE_CALLER = (1 << 4),
    /*! Invalidate the hangup segment */
    AST_CHANNEL_SNAPSHOT_INVALIDATE_HANGUP = (1 << 5),
    /*! Invalidate the peer segment */
    AST_CHANNEL_SNAPSHOT_INVALIDATE_PEER = (1 << 6),
    /*! Invalidate the base segment */
    AST_CHANNEL_SNAPSHOT_INVALIDATE_BASE = (1 << 7),
 };
stasis_user_multi_object_snapshot_type
enum stasis_user_multi_object_snapshot_type
Object type code for multi user object snapshots.
Enumerator
STASIS_UMOS_CHANNEL
Channel Snapshots
STASIS_UMOS_BRIDGE
Bridge Snapshots
STASIS_UMOS_ENDPOINT
Endpoint Snapshots
Definition at line 1357 of file stasis.h.
{
    STASIS_UMOS_CHANNEL = 0,     /*!< Channel Snapshots */
    STASIS_UMOS_BRIDGE,          /*!< Bridge Snapshots */
    STASIS_UMOS_ENDPOINT,        /*!< Endpoint Snapshots */
 };
Function Documentation
ast_channel_agent_login_type()
struct stasis_message_type* ast_channel_agent_login_type (void)
Message type for agent login on a channel.
Since
18.0.0
Return values
A stasis message type
Referenced by ast_stasis_channels_init(), load_module(), queue_agent_cb(), send_agent_login(), stasis_channels_cleanup(), and unhold_to_json().
ast_channel_agent_logoff_type()
struct stasis_message_type* ast_channel_agent_logoff_type (void)
Message type for agent logoff on a channel.
Since
12.0.0
Return values
A stasis message type
Referenced by ast_stasis_channels_init(), load_module(), queue_agent_cb(), send_agent_logoff(), stasis_channels_cleanup(), and unhold_to_json().
ast_channel_blob_create()
struct stasis_message* ast_channel_blob_create (struct ast_channel * chan, struct stasis_message_type * type, struct ast_json * blob)
Creates a ast_channel_blob message.
Since
12 The given blob should be treated as immutable and not modified after it is put into the message.
Precondition
chan is locked
Parameters
chan Channel blob is associated with, or NULL for global/all channels.
type Message type for this blob.
blob JSON object representing the data, or NULL for no data. If NULL, ast_json_null() is put into the object.
Returns
ast_channel_blob message.
NULL on error
Definition at line 788 of file stasis_channels.c.
References ao2_bump, ao2_cleanup, ast_channel_snapshot(), create_channel_blob_message(), and NULL.
Referenced by app_send_end_msg(), ast_channel_publish_blob(), AST_TEST_DEFINE(), and meetme_stasis_generate_msg().
 {
    struct ast_channel_snapshot *snapshot;
    struct stasis_message *msg;
    if (!type) {
       return NULL;
    }
    snapshot = chan ? ao2_bump(ast_channel_snapshot(chan)) : NULL;
    msg = create_channel_blob_message(snapshot, type, blob);
    ao2_cleanup(snapshot);
    return msg;
 }
ast_channel_blob_create_from_cache()
struct stasis_message* ast_channel_blob_create_from_cache (const char * uniqueid, struct stasis_message_type * type, struct ast_json * blob)
Create a ast_channel_blob message, pulling channel state from the cache.
Since
12
Parameters
uniqueid Uniqueid of the channel.
type Message type for this blob.
blob JSON object representing the data, or NULL for no data. If NULL, ast_json_null() is put into the object.
Returns
ast_channel_blob message.
NULL on error
Definition at line 771 of file stasis_channels.c.
References ao2_cleanup, ast_channel_snapshot_get_latest(), create_channel_blob_message(), and NULL.
Referenced by ast_cel_publish_event(), ast_channel_publish_cached_blob(), ast_monitor_start(), ast_monitor_stop(), manager_mute_mixmonitor(), mixmonitor_exec(), moh_post_start(), moh_post_stop(), phase_e_handler(), playback_publish(), recording_publish(), report_fax_status(), report_receive_fax_status(), report_send_fax_status(), stop_mixmonitor_full(), and talk_detect_audiohook_cb().
 {
    struct ast_channel_snapshot *snapshot;
    struct stasis_message *msg;
    if (!type) {
       return NULL;
    }
    snapshot = ast_channel_snapshot_get_latest(channel_id);
    msg = create_channel_blob_message(snapshot, type, blob);
    ao2_cleanup(snapshot);
    return msg;
 }
ast_channel_cache_all()
struct ao2_container* ast_channel_cache_all (void)
Definition at line 123 of file stasis_channels.c.
References ao2_bump.
Referenced by ast_ari_channels_list(), ast_complete_channels(), and channels_scrape_cb().
 {
    return ao2_bump(channel_cache);
 }
ast_channel_cache_by_name()
struct ao2_container* ast_channel_cache_by_name (void)
Secondary channel cache, indexed by name.
Since
12
Return values
Cache of ast_channel_snapshot.
Definition at line 133 of file stasis_channels.c.
References ao2_bump.
Referenced by action_coreshowchannels(), get_container(), and handle_chanlist().
 {
    return ao2_bump(channel_cache_by_name);
 }
ast_channel_chanspy_start_type()
struct stasis_message_type* ast_channel_chanspy_start_type (void)
Message type for when a channel starts spying on another channel.
Since
12
Return values
A stasis message type
Referenced by ast_stasis_channels_init(), manager_channels_init(), publish_chanspy_message(), stasis_channels_cleanup(), and unhold_to_json().
ast_channel_chanspy_stop_type()
struct stasis_message_type* ast_channel_chanspy_stop_type (void)
Message type for when a channel stops spying on another channel.
Since
12
Return values
A stasis message type
Referenced by ast_stasis_channels_init(), manager_channels_init(), publish_chanspy_message(), stasis_channels_cleanup(), and unhold_to_json().
ast_channel_dial_type()
struct stasis_message_type* ast_channel_dial_type (void)
Message type for when a channel dials another channel.
Since
12
Return values
A stasis message type
Referenced by ast_channel_publish_dial_internal(), ast_stasis_channels_init(), create_routes(), load_module(), manager_channels_init(), stasis_channels_cleanup(), sub_default_handler(), and unhold_to_json().
ast_channel_dtmf_begin_type()
struct stasis_message_type* ast_channel_dtmf_begin_type (void)
Message type for when DTMF begins on a channel.
Since
12
Return values
A stasis message type
Referenced by ast_stasis_channels_init(), manager_channels_init(), send_dtmf_begin_event(), stasis_channels_cleanup(), and unhold_to_json().
ast_channel_dtmf_end_type()
struct stasis_message_type* ast_channel_dtmf_end_type (void)
Message type for when DTMF ends on a channel.
Since
12
Return values
A stasis message type
Referenced by ast_stasis_channels_init(), manager_channels_init(), send_dtmf_end_event(), stasis_channels_cleanup(), and unhold_to_json().
ast_channel_fax_type()
struct stasis_message_type* ast_channel_fax_type (void)
Message type for a fax operation.
Since
12
Return values
A stasis message type
Referenced by ast_stasis_channels_init(), manager_channels_init(), phase_e_handler(), report_fax_status(), report_receive_fax_status(), report_send_fax_status(), stasis_channels_cleanup(), and unhold_to_json().
ast_channel_flash_type()
struct stasis_message_type* ast_channel_flash_type (void)
Message type for when a hook flash occurs on a channel.
Return values
A stasis message type
Referenced by ast_stasis_channels_init(), manager_channels_init(), send_flash_event(), stasis_channels_cleanup(), and unhold_to_json().
ast_channel_hangup_handler_type()
struct stasis_message_type* ast_channel_hangup_handler_type (void)
Message type for hangup handler related actions.
Since
12
Return values
A stasis message type
Referenced by ast_stasis_channels_init(), manager_channels_init(), publish_hangup_handler_message(), stasis_channels_cleanup(), and unhold_to_json().
ast_channel_hangup_request_type()
struct stasis_message_type* ast_channel_hangup_request_type (void)
Message type for when a hangup is requested on a channel.
Since
12
Return values
A stasis message type
Referenced by ast_queue_hangup(), ast_queue_hangup_with_cause(), ast_softhangup(), ast_stasis_channels_init(), manager_channels_init(), setup_stasis_subs(), stasis_channels_cleanup(), and unhold_to_json().
ast_channel_hold_type()
struct stasis_message_type* ast_channel_hold_type (void)
Message type for when a channel is placed on hold.
Since
12
Return values
A stasis message type
Referenced by ast_bridge_channel_write_hold(), ast_queue_hold(), ast_stasis_channels_init(), hold_intercept_framehook(), manager_channels_init(), stasis_channels_cleanup(), and unhold_to_json().
ast_channel_masquerade_type()
struct stasis_message_type* ast_channel_masquerade_type (void)
Message type for when a channel is being masqueraded.
Since
16
Return values
A stasis message type
Referenced by ast_channel_move(), ast_stasis_channels_init(), setup_stasis_subs(), stasis_channels_cleanup(), and unhold_to_json().
ast_channel_mixmonitor_mute_type()
struct stasis_message_type* ast_channel_mixmonitor_mute_type (void)
Message type for muting or unmuting mixmonitor on a channel.
Since
18
Return values
A stasis message type
Referenced by ast_stasis_channels_init(), manager_channels_init(), manager_mute_mixmonitor(), stasis_channels_cleanup(), and unhold_to_json().
ast_channel_mixmonitor_start_type()
struct stasis_message_type* ast_channel_mixmonitor_start_type (void)
Message type for starting mixmonitor on a channel.
Since
18
Return values
A stasis message type
Referenced by ast_stasis_channels_init(), manager_channels_init(), mixmonitor_exec(), stasis_channels_cleanup(), and unhold_to_json().
ast_channel_mixmonitor_stop_type()
struct stasis_message_type* ast_channel_mixmonitor_stop_type (void)
Message type for stopping mixmonitor on a channel.
Since
18
Return values
A stasis message type
Referenced by ast_stasis_channels_init(), manager_channels_init(), stasis_channels_cleanup(), stop_mixmonitor_full(), and unhold_to_json().
ast_channel_moh_start_type()
struct stasis_message_type* ast_channel_moh_start_type (void)
Message type for starting music on hold on a channel.
Since
12
Return values
A stasis message type
Referenced by ast_stasis_channels_init(), manager_channels_init(), moh_post_start(), stasis_channels_cleanup(), and unhold_to_json().
ast_channel_moh_stop_type()
struct stasis_message_type* ast_channel_moh_stop_type (void)
Message type for stopping music on hold on a channel.
Since
12
Return values
A stasis message type
Referenced by ast_stasis_channels_init(), manager_channels_init(), moh_post_stop(), stasis_channels_cleanup(), and unhold_to_json().
ast_channel_monitor_start_type()
struct stasis_message_type* ast_channel_monitor_start_type (void)
Message type for starting monitor on a channel.
Since
12
Return values
A stasis message type
Referenced by ast_monitor_start(), ast_stasis_channels_init(), manager_channels_init(), stasis_channels_cleanup(), and unhold_to_json().
ast_channel_monitor_stop_type()
struct stasis_message_type* ast_channel_monitor_stop_type (void)
Message type for stopping monitor on a channel.
Since
12
Return values
A stasis message type
Referenced by ast_monitor_stop(), ast_stasis_channels_init(), manager_channels_init(), stasis_channels_cleanup(), and unhold_to_json().
ast_channel_publish_blob()
void ast_channel_publish_blob (struct ast_channel * chan, struct stasis_message_type * type, struct ast_json * blob)
Publish a channel blob message.
Since
12.0.0
Precondition
chan is locked
Parameters
chan Channel publishing the blob.
type Type of stasis message.
blob The blob being published. (NULL if no blob)
Note
This will use the current snapshot on the channel and will not generate a new one.
Returns
Nothing
Definition at line 1135 of file stasis_channels.c.
References ao2_ref, ast_channel_blob_create(), ast_channel_topic(), ast_json_null(), and stasis_publish().
Referenced by ast_channel_move(), ast_channel_publish_varset(), ast_queue_hangup(), ast_queue_hangup_with_cause(), ast_queue_hold(), ast_queue_unhold(), ast_softhangup(), publish_dahdichannel(), publish_hangup_handler_message(), send_agent_login(), send_agent_logoff(), send_dtmf_begin_event(), send_dtmf_end_event(), send_flash_event(), and send_session_timeout().
 {
    struct stasis_message *message;
    if (!blob) {
       blob = ast_json_null();
    }
    message = ast_channel_blob_create(chan, type, blob);
    if (message) {
       stasis_publish(ast_channel_topic(chan), message);
       ao2_ref(message, -1);
    }
 }
ast_channel_publish_cached_blob()
void ast_channel_publish_cached_blob (struct ast_channel * chan, struct stasis_message_type * type, struct ast_json * blob)
Publish a channel blob message using the latest snapshot from the cache.
Since
12.4.0
Parameters
chan Channel publishing the blob.
type Type of stasis message.
blob The blob being published. (NULL if no blob)
Note
As this only accesses the uniqueid and topic of the channel - neither of which should ever be changed on a channel anyhow - a channel does not have to be locked when calling this function.
Returns
Nothing
Definition at line 1120 of file stasis_channels.c.
References ao2_ref, ast_channel_blob_create_from_cache(), ast_channel_topic(), ast_channel_uniqueid(), ast_json_null(), and stasis_publish().
Referenced by agi_handle_command(), ast_bridge_channel_write_hold(), ast_bridge_channel_write_unhold(), hold_intercept_framehook(), join_queue(), launch_asyncagi(), leave_queue(), publish_async_exec_end(), and record_abandoned().
 {
    struct stasis_message *message;
    if (!blob) {
       blob = ast_json_null();
    }
    message = ast_channel_blob_create_from_cache(ast_channel_uniqueid(chan), type, blob);
    if (message) {
       stasis_publish(ast_channel_topic(chan), message);
       ao2_ref(message, -1);
    }
 }
ast_channel_publish_dial()
void ast_channel_publish_dial (struct ast_channel * caller, struct ast_channel * peer, const char * dialstring, const char * dialstatus)
Publish in the ast_channel_topic or ast_channel_topic_all topics a stasis message for the channels involved in a dial operation.
Since
12
Parameters
caller The channel performing the dial operation
peer The channel being dialed
dialstring When beginning a dial, the information passed to the dialing application
dialstatus The current status of the dial operation (NULL if no status is known)
Definition at line 739 of file stasis_channels.c.
References ast_channel_publish_dial_forward(), and NULL.
Referenced by app_control_dial(), AST_TEST_DEFINE(), begin_dial_channel(), bridge_handle_trip(), dial_exec_full(), do_forward(), findmeexec(), handle_frame(), hangupcalls(), monitor_dial(), publish_dial_end_event(), ring_entry(), try_calling(), wait_for_answer(), and wait_for_winner().
 {
    ast_channel_publish_dial_forward(caller, peer, NULL, dialstring, dialstatus, NULL);
 }
ast_channel_publish_dial_forward()
void ast_channel_publish_dial_forward (struct ast_channel * caller, struct ast_channel * peer, struct ast_channel * forwarded, const char * dialstring, const char * dialstatus, const char * forward)
Publish in the ast_channel_topic or ast_channel_topic_all topics a stasis message for the channels involved in a dial operation that is forwarded.
Since
12
Parameters
caller The channel performing the dial operation
peer The channel being dialed
forwarded The channel created as a result of the call forwarding
dialstring The information passed to the dialing application when beginning a dial
dialstatus The current status of the dial operation
forward The call forward string provided by the dialed channel
Definition at line 689 of file stasis_channels.c.
References ast_assert, ast_channel_lock, ast_channel_publish_dial_internal(), ast_channel_trylock, ast_channel_unlock, ast_strlen_zero, NULL, remove_dial_masquerade(), remove_dial_masquerade_caller(), and set_dial_masquerade().
Referenced by ast_channel_publish_dial(), bridge_handle_trip(), do_forward(), handle_call_forward(), and wait_for_answer().
 {
    ast_assert(peer != NULL);
    /* XXX With an early bridge the below dial masquerade datastore code could, theoretically,
     * go away as the act of changing the channel during dialing would be done using the bridge
     * API itself and not a masquerade.
     */
    if (caller) {
       /*
        * Lock two or three channels.
        *
        * We need to hold the locks to hold off a potential masquerade
        * messing up the stasis dial event ordering.
        */
       for (;; ast_channel_unlock(caller), sched_yield()) {
          ast_channel_lock(caller);
          if (ast_channel_trylock(peer)) {
             continue;
          }
          if (forwarded && ast_channel_trylock(forwarded)) {
             ast_channel_unlock(peer);
             continue;
          }
          break;
       }
       if (ast_strlen_zero(dialstatus)) {
          set_dial_masquerade(caller, peer, dialstring);
       } else {
          remove_dial_masquerade(peer);
       }
    }
    ast_channel_publish_dial_internal(caller, peer, forwarded, dialstring, dialstatus,
       forward);
    if (caller) {
       if (forwarded) {
          ast_channel_unlock(forwarded);
       }
       ast_channel_unlock(peer);
       remove_dial_masquerade_caller(caller);
       ast_channel_unlock(caller);
    }
 }
ast_channel_publish_final_snapshot()
void ast_channel_publish_final_snapshot (struct ast_channel * chan)
Send the final channel snapshot for a channel, thus removing it from cache.
Since
17
Precondition
chan is locked
Parameters
chan The channel to send the final channel snapshot for
Note
This will also remove the cached snapshot from the channel itself
Definition at line 917 of file stasis_channels.c.
References ao2_ref, ao2_unlink, ast_channel_snapshot_set(), ast_channel_snapshot_type(), ast_channel_topic(), channel_snapshot_update_create(), NULL, ast_channel_snapshot_update::old_snapshot, stasis_message_create(), stasis_publish(), and update().
Referenced by ast_channel_destructor().
 {
    struct ast_channel_snapshot_update *update;
    struct stasis_message *message;
    if (!ast_channel_snapshot_type()) {
       return;
    }
    update = channel_snapshot_update_create(chan);
    if (!update) {
       return;
    }
    message = stasis_message_create(ast_channel_snapshot_type(), update);
    /* In the success path message holds a reference to update so it will be valid
     * for the lifetime of this function until the end.
     */
    ao2_ref(update, -1);
    if (!message) {
       return;
    }
    ao2_unlink(channel_cache, update->old_snapshot);
    ao2_unlink(channel_cache_by_name, update->old_snapshot);
    ast_channel_snapshot_set(chan, NULL);
    stasis_publish(ast_channel_topic(chan), message);
    ao2_ref(message, -1);
 }
ast_channel_publish_snapshot()
void ast_channel_publish_snapshot (struct ast_channel * chan)
Publish a ast_channel_snapshot for a channel.
Since
12
Precondition
chan is locked
Parameters
chan Channel to publish.
Definition at line 1055 of file stasis_channels.c.
References ao2_link_flags, ao2_ref, ao2_unlink_flags, ao2_unlock, ao2_wrlock, ast_assert, ast_channel_flags(), ast_channel_snapshot_segment_flags(), ast_channel_snapshot_set(), ast_channel_snapshot_type(), ast_channel_topic(), ast_clear_flag, AST_FLAG_SNAPSHOT_STAGE, AST_FLAGS_ALL, ast_test_flag, channel_snapshot_update_create(), ast_channel_snapshot_update::new_snapshot, NULL, OBJ_NOLOCK, ast_channel_snapshot_update::old_snapshot, stasis_message_create(), stasis_publish(), and update().
Referenced by ast_channel_amaflags_set(), ast_channel_internal_bridge_set(), ast_channel_internal_copy_linkedid(), ast_channel_publish_varset(), ast_channel_set_caller_event(), ast_channel_set_connected_line(), ast_channel_stage_snapshot_done(), ast_set_callerid(), ast_setstate(), AST_TEST_DEFINE(), channel_do_masquerade(), do_forward(), onCallEstablished(), pbx_exec(), and realtime_exec().
 {
    struct ast_channel_snapshot_update *update;
    struct stasis_message *message;
    if (!ast_channel_snapshot_type()) {
       return;
    }
    if (ast_test_flag(ast_channel_flags(chan), AST_FLAG_SNAPSHOT_STAGE)) {
       return;
    }
    update = channel_snapshot_update_create(chan);
    if (!update) {
       return;
    }
    /* If an old snapshot exists and is the same as this newly created one don't bother
     * raising a message as it hasn't changed.
     */
    if (update->old_snapshot && !memcmp(update->old_snapshot, update->new_snapshot, sizeof(struct ast_channel_snapshot))) {
       ao2_ref(update, -1);
       return;
    }
    message = stasis_message_create(ast_channel_snapshot_type(), update);
    /* In the success path message holds a reference to update so it will be valid
     * for the lifetime of this function until the end.
     */
    ao2_ref(update, -1);
    if (!message) {
       return;
    }
    /* We lock these ourselves so that the update is atomic and there isn't time where a
     * snapshot is not in the cache.
     */
    ao2_wrlock(channel_cache);
    if (update->old_snapshot) {
       ao2_unlink_flags(channel_cache, update->old_snapshot, OBJ_NOLOCK);
    }
    ao2_link_flags(channel_cache, update->new_snapshot, OBJ_NOLOCK);
    ao2_unlock(channel_cache);
    /* The same applies here. */
    ao2_wrlock(channel_cache_by_name);
    if (update->old_snapshot) {
       ao2_unlink_flags(channel_cache_by_name, update->old_snapshot, OBJ_NOLOCK);
    }
    ao2_link_flags(channel_cache_by_name, update->new_snapshot, OBJ_NOLOCK);
    ao2_unlock(channel_cache_by_name);
    ast_channel_snapshot_set(chan, update->new_snapshot);
    /* As this is now the new snapshot any existing invalidated segments have been
     * created fresh and are up to date.
     */
    ast_clear_flag(ast_channel_snapshot_segment_flags(chan), AST_FLAGS_ALL);
    ast_assert(ast_channel_topic(chan) != NULL);
    stasis_publish(ast_channel_topic(chan), message);
    ao2_ref(message, -1);
 }
ast_channel_publish_varset()
void ast_channel_publish_varset (struct ast_channel * chan, const char * variable, const char * value)
Publish a ast_channel_varset for a channel.
Since
12
Precondition
chan is locked
Parameters
chan Channel to publish the event for, or NULL for 'none'.
variable Name of the variable being set
value Value.
If there are manager variables, force a cache update
Definition at line 1150 of file stasis_channels.c.
References ast_assert, ast_channel_has_manager_vars(), ast_channel_publish_blob(), ast_channel_publish_snapshot(), ast_channel_varset_type(), ast_json_pack(), ast_json_unref(), ast_log, LOG_ERROR, and NULL.
Referenced by ast_channel_inherit_variables(), ast_unreal_call_setup(), frame_set_var(), pbx_builtin_setvar_helper(), and shared_write().
 {
    struct ast_json *blob;
    ast_assert(name != NULL);
    ast_assert(value != NULL);
    blob = ast_json_pack("{s: s, s: s}",
               "variable", name,
               "value", value);
    if (!blob) {
       ast_log(LOG_ERROR, "Error creating message\n");
       return;
    }
    /*! If there are manager variables, force a cache update */
    if (chan && ast_channel_has_manager_vars()) {
       ast_channel_publish_snapshot(chan);
    }
    /* This function is NULL safe for global variables */
    ast_channel_publish_blob(chan, ast_channel_varset_type(), blob);
    ast_json_unref(blob);
 }
ast_channel_snapshot_create()
struct ast_channel_snapshot* ast_channel_snapshot_create (struct ast_channel * chan)
Generate a snapshot of the channel state. This is an ao2 object, so ao2_cleanup() to deallocate.
Since
12
Precondition
chan is locked
Parameters
chan The channel from which to generate a snapshot
Return values
pointer on success (must be unreffed)
NULL on error
Definition at line 451 of file stasis_channels.c.
References ast_channel_snapshot::amaflags, AO2_ALLOC_OPT_LOCK_NOLOCK, ao2_alloc_options, ao2_bump, ao2_ref, ast_channel_snapshot::ari_vars, ast_channel_amaflags(), ast_channel_flags(), ast_channel_get_ari_vars(), ast_channel_get_manager_vars(), ast_channel_snapshot(), AST_CHANNEL_SNAPSHOT_INVALIDATE_BASE, AST_CHANNEL_SNAPSHOT_INVALIDATE_BRIDGE, AST_CHANNEL_SNAPSHOT_INVALIDATE_DIALPLAN, AST_CHANNEL_SNAPSHOT_INVALIDATE_HANGUP, AST_CHANNEL_SNAPSHOT_INVALIDATE_PEER, ast_channel_snapshot_segment_flags(), ast_channel_softhangup_internal_flag(), ast_channel_tech(), ast_copy_flags, ast_set_flag, ast_test_flag, ast_channel_snapshot::base, ast_channel_snapshot::bridge, ast_channel_snapshot::caller, channel_snapshot_base_create(), channel_snapshot_bridge_create(), channel_snapshot_caller_create(), channel_snapshot_connected_create(), channel_snapshot_dialplan_create(), channel_snapshot_dtor(), channel_snapshot_hangup_create(), channel_snapshot_peer_create(), ast_channel_snapshot::connected, ast_channel_snapshot::dialplan, ast_channel_snapshot::flags, ast_channel_snapshot::hangup, ast_channel_snapshot::manager_vars, NULL, ast_channel_snapshot::peer, ast_channel_snapshot::softhangup_flags, and ast_channel_snapshot::state.
Referenced by action_agents(), append_expected_event(), ast_channel_publish_dial_internal(), ast_do_pickup(), ast_multi_object_blob_single_channel_publish(), AST_TEST_DEFINE(), channel_snapshot_update_create(), parked_call_app_exec(), parked_call_payload_from_failure(), parked_call_payload_from_parked_user(), queue_publish_multi_channel_blob(), and send_start_msg().
 {
    struct ast_channel_snapshot *old_snapshot;
    struct ast_channel_snapshot *snapshot;
    /* no snapshots for dummy channels */
    if (!ast_channel_tech(chan)) {
       return NULL;
    }
    snapshot = ao2_alloc_options(sizeof(*snapshot), channel_snapshot_dtor,
       AO2_ALLOC_OPT_LOCK_NOLOCK);
    if (!snapshot) {
       return NULL;
    }
    old_snapshot = ast_channel_snapshot(chan);
    /* Channels automatically have all segments invalidated on them initially so a check for an old
     * snapshot existing before usage is not done here, as it can not happen. If the stored snapshot
     * on the channel is updated as a result of this then all segments marked as invalidated will be
     * cleared.
     */
    if (ast_test_flag(ast_channel_snapshot_segment_flags(chan), AST_CHANNEL_SNAPSHOT_INVALIDATE_BASE)) {
       /* The base information has changed so update our snapshot */
       snapshot->base = channel_snapshot_base_create(chan);
       if (!snapshot->base) {
          ao2_ref(snapshot, -1);
          return NULL;
       }
    } else {
       snapshot->base = ao2_bump(old_snapshot->base);
    }
    if (ast_test_flag(ast_channel_snapshot_segment_flags(chan), AST_CHANNEL_SNAPSHOT_INVALIDATE_PEER)) {
       /* The peer information has changed so update our snapshot */
       snapshot->peer = channel_snapshot_peer_create(chan);
       if (!snapshot->peer) {
          ao2_ref(snapshot, -1);
          return NULL;
       }
    } else {
       snapshot->peer = ao2_bump(old_snapshot->peer);
    }
    /* Unfortunately both caller and connected information do not have an enforced contract with
     * the channel API. This has allowed consumers to directly get the caller or connected structure
     * and manipulate it. Until such time as there is an enforced contract (which is being tracked under
     * ASTERISK-28164) they are each regenerated every time a channel snapshot is created.
     */
    snapshot->caller = channel_snapshot_caller_create(chan);
    if (!snapshot->caller) {
       ao2_ref(snapshot, -1);
       return NULL;
    }
    snapshot->connected = channel_snapshot_connected_create(chan);
    if (!snapshot->connected) {
       ao2_ref(snapshot, -1);
       return NULL;
    }
    if (ast_test_flag(ast_channel_snapshot_segment_flags(chan), AST_CHANNEL_SNAPSHOT_INVALIDATE_BRIDGE)) {
       /* The bridge has changed so update our snapshot */
       snapshot->bridge = channel_snapshot_bridge_create(chan);
       if (!snapshot->bridge) {
          ao2_ref(snapshot, -1);
          return NULL;
       }
    } else {
       snapshot->bridge = ao2_bump(old_snapshot->bridge);
    }
    if (ast_test_flag(ast_channel_snapshot_segment_flags(chan), AST_CHANNEL_SNAPSHOT_INVALIDATE_DIALPLAN)) {
       /* The dialplan information has changed so update our snapshot */
       snapshot->dialplan = channel_snapshot_dialplan_create(chan);
       if (!snapshot->dialplan) {
          ao2_ref(snapshot, -1);
          return NULL;
       }
    } else {
       snapshot->dialplan = ao2_bump(old_snapshot->dialplan);
    }
    if (ast_test_flag(ast_channel_snapshot_segment_flags(chan), AST_CHANNEL_SNAPSHOT_INVALIDATE_HANGUP)) {
       /* The hangup information has changed so update our snapshot */
       snapshot->hangup = channel_snapshot_hangup_create(chan);
       if (!snapshot->hangup) {
          ao2_ref(snapshot, -1);
          return NULL;
       }
    } else {
       snapshot->hangup = ao2_bump(old_snapshot->hangup);
    }
    snapshot->state = ast_channel_state(chan);
    snapshot->amaflags = ast_channel_amaflags(chan);
    ast_copy_flags(&snapshot->flags, ast_channel_flags(chan), 0xFFFFFFFF);
    ast_set_flag(&snapshot->softhangup_flags, ast_channel_softhangup_internal_flag(chan));
    /* These have to be recreated as they may have changed, unfortunately */
    snapshot->manager_vars = ast_channel_get_manager_vars(chan);
    snapshot->ari_vars = ast_channel_get_ari_vars(chan);
    return snapshot;
 }
ast_channel_snapshot_get_latest()
struct ast_channel_snapshot* ast_channel_snapshot_get_latest (const char * uniqueid)
Obtain the latest ast_channel_snapshot from the Stasis Message Bus API cache. This is an ao2 object, so use ao2_cleanup() to deallocate.
Since
12
Parameters
unique_id The channel's unique ID
Return values
A ast_channel_snapshot on success
NULL on error
Definition at line 903 of file stasis_channels.c.
References ao2_find, ast_assert, ast_strlen_zero, and OBJ_SEARCH_KEY.
Referenced by __test_cel_generate_peer_str(), action_confbridgelist_item(), ari_channels_handle_originate_with_id(), ari_channels_handle_snoop_channel(), ast_ari_channels_create(), ast_ari_channels_get(), ast_ari_channels_redirect(), ast_attended_transfer_message_add_app(), ast_attended_transfer_message_add_link(), ast_attended_transfer_message_create(), ast_blind_transfer_message_create(), ast_bridge_blob_create(), ast_bridge_transfer_blind(), ast_channel_blob_create_from_cache(), ast_channel_publish_dial_internal(), ast_do_pickup(), ast_rtp_publish_rtcp_message(), ast_sip_for_each_channel_snapshot(), blind_transfer_bridge(), bridge_channel_snapshot_pair_init(), bridge_parking_push(), bridge_show_specific_print_channel(), bridge_stasis_push_peek(), cel_generate_peer_str(), chan_pjsip_devicestate(), channel_id_sanitizer(), channel_replaced_cb(), conf_send_event_to_participants(), find_channel_control(), generate_status(), handle_attended_transfer(), handle_blind_transfer(), handle_hangup(), local_channel_optimization_blob(), local_optimization_started_cb(), mwi_state_create_message(), notify_new_message(), pack_channel_into_message(), publish_chanspy_message(), publish_local_bridge_message(), send_bridge_info_item_cb(), stasis_app_control_get_snapshot(), stasis_app_exec(), stasis_app_user_event(), and test_cel_generate_peer_str().
 {
    ast_assert(!ast_strlen_zero(uniqueid));
    return ao2_find(channel_cache, uniqueid, OBJ_SEARCH_KEY);
 }
ast_channel_snapshot_get_latest_by_name()
struct ast_channel_snapshot* ast_channel_snapshot_get_latest_by_name (const char * name)
Obtain the latest ast_channel_snapshot from the Stasis Message Bus API cache. This is an ao2 object, so use ao2_cleanup() to deallocate.
Since
12
Parameters
name The channel's name
Return values
A ast_channel_snapshot on success
NULL on error
Definition at line 910 of file stasis_channels.c.
References ao2_find, ast_assert, ast_strlen_zero, and OBJ_SEARCH_KEY.
Referenced by cli_channel_retrieve_by_id(), and handle_channelstatus().
 {
    ast_assert(!ast_strlen_zero(name));
    return ao2_find(channel_cache_by_name, name, OBJ_SEARCH_KEY);
 }
ast_channel_snapshot_invalidate_segment()
void ast_channel_snapshot_invalidate_segment (struct ast_channel * chan, enum ast_channel_snapshot_segment_invalidation segment)
Invalidate a channel snapshot segment from being reused.
Since
17
Precondition
chan is locked
Parameters
chan Channel to invalidate the segment on.
segment The segment to invalidate.
Definition at line 1049 of file stasis_channels.c.
References ast_channel_snapshot_segment_flags(), and ast_set_flag.
Referenced by ast_channel_appl_set(), ast_channel_caller_set(), ast_channel_connected_set(), ast_channel_context_set(), ast_channel_creationtime_set(), ast_channel_data_set(), ast_channel_dialed_set(), ast_channel_exten_set(), ast_channel_hangupcause_set(), ast_channel_internal_bridge_set(), ast_channel_internal_copy_linkedid(), ast_channel_priority_set(), ast_channel_redirecting_set(), ast_channel_set_caller(), ast_channel_set_caller_event(), ast_channel_set_connected_line(), ast_channel_set_redirecting(), and realtime_exec().
 {
    ast_set_flag(ast_channel_snapshot_segment_flags(chan), segment);
 }
ast_channel_snapshot_type()
struct stasis_message_type* ast_channel_snapshot_type (void)
Message type for ast_channel_snapshot_update.
Since
12
Return values
Message type for ast_channel_snapshot_update.
Referenced by app_create(), ast_channel_publish_final_snapshot(), ast_channel_publish_snapshot(), ast_stasis_channels_init(), AST_TEST_DEFINE(), create_routes(), endpoint_internal_create(), load_module(), manager_channels_init(), realtime_exec(), stasis_channels_cleanup(), and unhold_to_json().
ast_channel_stage_snapshot()
void ast_channel_stage_snapshot (struct ast_channel * chan)
Set flag to indicate channel snapshot is being staged.
Since
12
Precondition
chan is locked
Parameters
chan Channel being staged.
Definition at line 1038 of file stasis_channels.c.
References ast_channel_flags(), AST_FLAG_SNAPSHOT_STAGE, and ast_set_flag.
Referenced by __ast_channel_alloc_ap(), __ast_request_and_dial(), alsa_new(), ast_ari_channels_dial(), ast_bridge_vars_set(), ast_call_forward(), ast_iax2_new(), ast_rtp_instance_set_stats_vars(), ast_unreal_call_setup(), begin_dial_prerun(), chan_pjsip_new(), common_recall_channel_setup(), console_new(), dahdi_new(), dial_exec_full(), end_bridge_callback(), jingle_new(), mgcp_new(), parking_duration_callback(), pbx_outgoing_attempt(), sip_hangup(), sip_new(), skinny_new(), unistim_new(), and wait_for_answer().
 {
    ast_set_flag(ast_channel_flags(chan), AST_FLAG_SNAPSHOT_STAGE);
 }
ast_channel_stage_snapshot_done()
void ast_channel_stage_snapshot_done (struct ast_channel * chan)
Clear flag to indicate channel snapshot is being staged, and publish snapshot.
Since
12
Precondition
chan is locked
Parameters
chan Channel being staged.
Definition at line 1043 of file stasis_channels.c.
References ast_channel_flags(), ast_channel_publish_snapshot(), ast_clear_flag, and AST_FLAG_SNAPSHOT_STAGE.
Referenced by __ast_channel_alloc_ap(), __ast_request_and_dial(), alsa_new(), ast_ari_channels_dial(), ast_bridge_vars_set(), ast_call_forward(), ast_iax2_new(), ast_rtp_instance_set_stats_vars(), ast_unreal_call_setup(), begin_dial_prerun(), chan_pjsip_new(), common_recall_channel_setup(), console_new(), dahdi_new(), dial_exec_full(), end_bridge_callback(), jingle_new(), mgcp_new(), parking_duration_callback(), pbx_outgoing_attempt(), sip_hangup(), sip_new(), skinny_new(), unistim_new(), and wait_for_answer().
 {
    ast_clear_flag(ast_channel_flags(chan), AST_FLAG_SNAPSHOT_STAGE);
    ast_channel_publish_snapshot(chan);
 }
ast_channel_talking_start()
struct stasis_message_type* ast_channel_talking_start (void)
Message type for a channel starting talking.
Since
12.4.0
Return values
A stasis message type
Referenced by ast_stasis_channels_init(), stasis_channels_cleanup(), talk_detect_audiohook_cb(), and unhold_to_json().
ast_channel_talking_stop()
struct stasis_message_type* ast_channel_talking_stop (void)
Message type for a channel stopping talking.
Since
12.4.0
Return values
A stasis message type
Referenced by ast_stasis_channels_init(), stasis_channels_cleanup(), talk_detect_audiohook_cb(), and unhold_to_json().
ast_channel_topic_all()
struct stasis_topic* ast_channel_topic_all (void)
A topic which publishes the events for all channels.
Since
12
Return values
Topic for all channel events.
Definition at line 128 of file stasis_channels.c.
References channel_topic_all.
Referenced by ast_channel_internal_setup_topics(), ast_channel_topic(), create_subscriptions(), forwards_create_channel(), load_module(), manager_channels_init(), manager_confbridge_init(), meetme_stasis_init(), publish_message_for_channel_topics(), and setup_stasis_subs().
 {
    return channel_topic_all;
 }
ast_channel_unhold_type()
struct stasis_message_type* ast_channel_unhold_type (void)
Message type for when a channel is removed from hold.
Since
12
Return values
A stasis message type
Referenced by ast_bridge_channel_write_unhold(), ast_queue_unhold(), ast_stasis_channels_init(), hold_intercept_framehook(), manager_channels_init(), stasis_channels_cleanup(), and unhold_to_json().
ast_channel_varset_type()
struct stasis_message_type* ast_channel_varset_type (void)
Message type for when a variable is set on a channel.
Since
12
Return values
A stasis message type
Referenced by ast_channel_publish_varset(), ast_stasis_channels_init(), stasis_channels_cleanup(), and unhold_to_json().
ast_debug_category_dtls_id()
uintmax_t ast_debug_category_dtls_id (void)
Definition at line 3566 of file rtp_engine.c.
References debug_category_dtls_id.
 {
    return debug_category_dtls_id;
 }
ast_debug_category_dtls_packet_id()
uintmax_t ast_debug_category_dtls_packet_id (void)
Definition at line 3573 of file rtp_engine.c.
References debug_category_dtls_packet_id.
 {
    return debug_category_dtls_packet_id;
 }
ast_debug_category_ice_id()
uintmax_t ast_debug_category_ice_id (void)
Definition at line 3580 of file rtp_engine.c.
References debug_category_ice_id.
 {
    return debug_category_ice_id;
 }
ast_debug_category_rtcp_id()
uintmax_t ast_debug_category_rtcp_id (void)
Definition at line 3552 of file rtp_engine.c.
References debug_category_rtcp_id.
 {
    return debug_category_rtcp_id;
 }
ast_debug_category_rtcp_packet_id()
uintmax_t ast_debug_category_rtcp_packet_id (void)
Definition at line 3559 of file rtp_engine.c.
References debug_category_rtcp_packet_id.
 {
    return debug_category_rtcp_packet_id;
 }
ast_debug_category_rtp_id()
uintmax_t ast_debug_category_rtp_id (void)
Definition at line 3538 of file rtp_engine.c.
References debug_category_rtp_id.
 {
    return debug_category_rtp_id;
 }
ast_debug_category_rtp_packet_id()
uintmax_t ast_debug_category_rtp_packet_id (void)
Definition at line 3545 of file rtp_engine.c.
References debug_category_rtp_packet_id.
 {
    return debug_category_rtp_packet_id;
 }
ast_endpoint_blob_create()
struct stasis_message* ast_endpoint_blob_create (struct ast_endpoint * endpoint, struct stasis_message_type * type, struct ast_json * blob)
Creates a ast_endpoint_blob message.
Since
12 The given blob should be treated as immutable and not modified after it is put into the message.
Parameters
endpoint Endpoint blob is associated with.
type Message type for this blob.
blob JSON object representing the data, or NULL for no data. If NULL, ast_json_null() is put into the object.
Returns
ast_endpoint_blob message.
NULL on error
Definition at line 293 of file stasis_endpoints.c.
References ao2_alloc, ao2_ref, ast_endpoint_snapshot_create(), ast_json_null(), ast_json_ref(), ast_endpoint_blob::blob, endpoint_blob_dtor(), NULL, ast_endpoint_blob::snapshot, and stasis_message_create().
Referenced by ast_endpoint_blob_publish().
 {
    struct ast_endpoint_blob *obj;
    struct stasis_message *msg;
    if (!type) {
       return NULL;
    }
    if (!blob) {
       blob = ast_json_null();
    }
    if (!(obj = ao2_alloc(sizeof(*obj), endpoint_blob_dtor))) {
       return NULL;
    }
    if (endpoint) {
       if (!(obj->snapshot = ast_endpoint_snapshot_create(endpoint))) {
          ao2_ref(obj, -1);
          return NULL;
       }
    }
    obj->blob = ast_json_ref(blob);
    msg = stasis_message_create(type, obj);
    ao2_ref(obj, -1);
    return msg;
 }
ast_endpoint_blob_publish()
void ast_endpoint_blob_publish (struct ast_endpoint * endpoint, struct stasis_message_type * type, struct ast_json * blob)
Creates and publishes a ast_endpoint_blob message.
Since
12 The given blob should be treated as immutable and not modified after it is put into the message.
Parameters
endpoint Endpoint blob is associated with.
type Message type for this blob.
blob JSON object representing the data, or NULL for no data. If NULL, ast_json_null() is put into the object.
Definition at line 325 of file stasis_endpoints.c.
References ao2_ref, ast_endpoint_blob_create(), ast_endpoint_topic(), and stasis_publish().
Referenced by __expire_registry(), __iax2_poke_noanswer(), ast_sip_persistent_endpoint_publish_contact_state(), ast_sip_persistent_endpoint_update_state(), expire_register(), handle_response_peerpoke(), parse_register_contact(), register_verify(), sip_poke_noanswer(), skinny_register(), skinny_session_cleanup(), socket_process_helper(), unload_module(), and update_registry().
 {
    struct stasis_message *message;
    if (!blob) {
       return;
    }
    message = ast_endpoint_blob_create(endpoint, type, blob);
    if (message) {
       stasis_publish(ast_endpoint_topic(endpoint), message);
       ao2_ref(message, -1);
    }
 }
ast_endpoint_cache()
struct stasis_cache* ast_endpoint_cache (void)
Backend cache for ast_endpoint_topic_all_cached().
Returns
Cache of ast_endpoint_snapshot.
Since
12
Definition at line 111 of file stasis_endpoints.c.
References stasis_cp_all_cache().
Referenced by ast_ari_endpoints_list(), ast_ari_endpoints_list_by_tech(), ast_endpoint_latest_snapshot(), endpoints_scrape_cb(), load_module(), and unload_module().
 {
    return stasis_cp_all_cache(endpoint_cache_all);
 }
ast_endpoint_cache_all()
struct stasis_cp_all* ast_endpoint_cache_all (void)
Definition at line 106 of file stasis_endpoints.c.
References endpoint_cache_all.
Referenced by endpoint_internal_create().
 {
    return endpoint_cache_all;
 }
ast_endpoint_contact_state_type()
struct stasis_message_type* ast_endpoint_contact_state_type (void)
Message type for endpoint contact state changes.
Since
13.5
Referenced by ast_endpoint_stasis_init(), ast_sip_persistent_endpoint_publish_contact_state(), contactstatus_to_json(), endpoints_stasis_cleanup(), forwards_create_endpoint(), and manager_endpoints_init().
ast_endpoint_latest_snapshot()
struct ast_endpoint_snapshot* ast_endpoint_latest_snapshot (const char * tech, const char * resource)
Retrieve the most recent snapshot for the endpoint with the given name.
Parameters
tech Name of the endpoint's technology.
resource Resource name of the endpoint.
Returns
Snapshot of the endpoint with the given name.
NULL if endpoint is not found, or on error.
Since
12
Definition at line 341 of file stasis_endpoints.c.
References ao2_ref, ast_asprintf, ast_assert, ast_endpoint_cache(), ast_endpoint_snapshot_type(), ast_free, ast_strlen_zero, ast_tech_to_upper(), NULL, stasis_cache_get(), and stasis_message_data().
Referenced by ast_ari_endpoints_get(), ast_ari_endpoints_send_message_to_endpoint(), ast_sip_get_endpoint_snapshot(), chan_pjsip_devicestate(), message_received_handler(), and stasis_app_user_event().
 {
    char *id = NULL;
    struct stasis_message *msg;
    struct ast_endpoint_snapshot *snapshot;
    if (ast_strlen_zero(name)) {
       ast_asprintf(&id, "%s", tech);
    } else {
       ast_asprintf(&id, "%s/%s", tech, name);
    }
    if (!id) {
       return NULL;
    }
    ast_tech_to_upper(id);
    msg = stasis_cache_get(ast_endpoint_cache(), ast_endpoint_snapshot_type(), id);
    ast_free(id);
    if (!msg) {
       return NULL;
    }
    snapshot = stasis_message_data(msg);
    ast_assert(snapshot != NULL);
    ao2_ref(snapshot, +1);
    ao2_ref(msg, -1);
    return snapshot;
 }
ast_endpoint_snapshot_create()
struct ast_endpoint_snapshot* ast_endpoint_snapshot_create (struct ast_endpoint * endpoint)
Create a snapshot of an endpoint.
Parameters
endpoint Endpoint to snap a shot of.
Returns
Snapshot of the endpoint.
NULL on error.
Since
12
Definition at line 445 of file main/endpoints.c.
References AO2_ALLOC_OPT_LOCK_NOLOCK, ao2_alloc_options, ao2_cleanup, ao2_container_count(), ao2_iterator_destroy(), ao2_iterator_init(), ao2_iterator_next, ast_assert, ast_string_field_build, ast_string_field_init, ast_string_field_set, ast_strlen_zero, ast_endpoint_snapshot::channel_ids, ast_endpoint::channel_ids, endpoint_snapshot_dtor(), lock, ast_endpoint_snapshot::max_channels, ast_endpoint::max_channels, NULL, ast_endpoint_snapshot::num_channels, ast_endpoint::resource, SCOPED_AO2LOCK, ast_endpoint_snapshot::state, ast_endpoint::state, and ast_endpoint::tech.
Referenced by ast_endpoint_blob_create(), AST_TEST_DEFINE(), create_endpoint_snapshot_message(), and endpoint_publish_snapshot().
 {
    struct ast_endpoint_snapshot *snapshot;
    int channel_count;
    struct ao2_iterator i;
    void *obj;
    SCOPED_AO2LOCK(lock, endpoint);
    ast_assert(endpoint != NULL);
    ast_assert(!ast_strlen_zero(endpoint->resource));
    channel_count = ao2_container_count(endpoint->channel_ids);
    snapshot = ao2_alloc_options(
       sizeof(*snapshot) + channel_count * sizeof(char *),
       endpoint_snapshot_dtor,
       AO2_ALLOC_OPT_LOCK_NOLOCK);
    if (!snapshot || ast_string_field_init(snapshot, 80) != 0) {
       ao2_cleanup(snapshot);
       return NULL;
    }
    ast_string_field_build(snapshot, id, "%s/%s", endpoint->tech,
       endpoint->resource);
    ast_string_field_set(snapshot, tech, endpoint->tech);
    ast_string_field_set(snapshot, resource, endpoint->resource);
    snapshot->state = endpoint->state;
    snapshot->max_channels = endpoint->max_channels;
    i = ao2_iterator_init(endpoint->channel_ids, 0);
    while ((obj = ao2_iterator_next(&i))) {
       /* The reference is kept so the channel id does not go away until the snapshot is gone */
       snapshot->channel_ids[snapshot->num_channels++] = obj;
    }
    ao2_iterator_destroy(&i);
    return snapshot;
 }
ast_endpoint_snapshot_type()
struct stasis_message_type* ast_endpoint_snapshot_type (void)
Message type for ast_endpoint_snapshot.
Since
12
Referenced by app_create(), ast_ari_endpoints_list(), ast_ari_endpoints_list_by_tech(), ast_endpoint_latest_snapshot(), ast_endpoint_stasis_init(), ast_endpoint_topic_all_cached(), AST_TEST_DEFINE(), cache_update(), cache_update_cb(), create_endpoint_snapshot_message(), endpoint_internal_create(), endpoint_publish_snapshot(), endpoint_snapshot_get_id(), endpoints_scrape_cb(), endpoints_stasis_cleanup(), load_module(), sub_endpoint_update_handler(), and unload_module().
ast_endpoint_state_type()
struct stasis_message_type* ast_endpoint_state_type (void)
Message type for endpoint state changes.
Since
12
Referenced by __expire_registry(), __iax2_poke_noanswer(), ast_endpoint_stasis_init(), ast_sip_persistent_endpoint_update_state(), endpoints_stasis_cleanup(), expire_register(), forwards_create_endpoint(), handle_response_peerpoke(), manager_endpoints_init(), parse_register_contact(), peerstatus_to_json(), register_verify(), sip_poke_noanswer(), skinny_register(), skinny_session_cleanup(), socket_process_helper(), unload_module(), and update_registry().
ast_endpoint_topic()
struct stasis_topic* ast_endpoint_topic (struct ast_endpoint * endpoint)
Returns the topic for a specific endpoint.
Parameters
endpoint The endpoint.
Returns
The topic for the given endpoint.
ast_endpoint_topic_all() if endpoint is NULL.
Since
12
Definition at line 93 of file main/endpoints.c.
References ast_endpoint_topic_all(), stasis_cp_single_topic(), and ast_endpoint::topics.
Referenced by ast_channel_forward_endpoint(), ast_endpoint_blob_publish(), ast_endpoint_shutdown(), AST_TEST_DEFINE(), endpoint_internal_create(), endpoint_publish_snapshot(), and forwards_create_endpoint().
 {
    if (!endpoint) {
       return ast_endpoint_topic_all();
    }
    return stasis_cp_single_topic(endpoint->topics);
 }
ast_endpoint_topic_all()
struct stasis_topic* ast_endpoint_topic_all (void)
Topic for all endpoint releated messages.
Since
12
Definition at line 116 of file stasis_endpoints.c.
References stasis_cp_all_topic().
Referenced by ast_endpoint_topic().
 {
    return stasis_cp_all_topic(endpoint_cache_all);
 }
ast_endpoint_topic_all_cached()
struct stasis_topic* ast_endpoint_topic_all_cached (void)
Cached topic for all endpoint related messages.
Since
12
Definition at line 121 of file stasis_endpoints.c.
References ast_endpoint_snapshot_type(), stasis_cp_all_topic_cached(), and STASIS_MESSAGE_TYPE_DEFN().
Referenced by ast_endpoint_topic_cached(), AST_TEST_DEFINE(), forwards_create_endpoint(), load_module(), and manager_endpoints_init().
 {
    return stasis_cp_all_topic_cached(endpoint_cache_all);
 }
ast_endpoint_topic_cached()
struct stasis_topic* ast_endpoint_topic_cached (struct ast_endpoint * endpoint)
Returns the topic for a specific endpoint.
ast_endpoint_snapshot messages are replaced with stasis_cache_update
Parameters
endpoint The endpoint.
Returns
The topic for the given endpoint.
ast_endpoint_topic_all() if endpoint is NULL.
Since
12
Definition at line 101 of file main/endpoints.c.
References ast_endpoint_topic_all_cached(), stasis_cp_single_topic_cached(), and ast_endpoint::topics.
Referenced by forwards_create_endpoint().
 {
    if (!endpoint) {
       return ast_endpoint_topic_all_cached();
    }
    return stasis_cp_single_topic_cached(endpoint->topics);
 }
ast_multi_channel_blob_add_channel()
void ast_multi_channel_blob_add_channel (struct ast_multi_channel_blob * obj, const char * role, struct ast_channel_snapshot * snapshot)
Add a ast_channel_snapshot to a ast_multi_channel_blob object.
Since
12
Note
This will increase the reference count by 1 for the channel snapshot. It is assumed that the ast_multi_channel_blob will own a reference to the object.
Parameters
obj The ast_multi_channel_blob object that will reference the snapshot
role A role that the snapshot has in the multi channel relationship
snapshot The ast_channel_snapshot being added to the ast_multi_channel_blob object
Definition at line 956 of file stasis_channels.c.
References AO2_ALLOC_OPT_LOCK_NOLOCK, ao2_alloc_options, ao2_link, ao2_ref, ast_copy_string(), ast_strlen_zero, channel_role_snapshot_dtor(), ast_multi_channel_blob::channel_snapshots, channel_role_snapshot::role, and channel_role_snapshot::snapshot.
Referenced by ast_channel_publish_dial_internal(), AST_TEST_DEFINE(), local_channel_optimization_blob(), local_optimization_started_cb(), pack_channel_into_message(), publish_chanspy_message(), publish_local_bridge_message(), queue_publish_multi_channel_snapshot_blob(), and send_call_pickup_stasis_message().
 {
    struct channel_role_snapshot *role_snapshot;
    int role_len = strlen(role) + 1;
    if (!obj || ast_strlen_zero(role) || !snapshot) {
       return;
    }
    role_snapshot = ao2_alloc_options(sizeof(*role_snapshot) + role_len,
       channel_role_snapshot_dtor, AO2_ALLOC_OPT_LOCK_NOLOCK);
    if (!role_snapshot) {
       return;
    }
    ast_copy_string(role_snapshot->role, role, role_len);
    role_snapshot->snapshot = snapshot;
    ao2_ref(role_snapshot->snapshot, +1);
    ao2_link(obj->channel_snapshots, role_snapshot);
    ao2_ref(role_snapshot, -1);
 }
ast_multi_channel_blob_create()
struct ast_multi_channel_blob* ast_multi_channel_blob_create (struct ast_json * blob)
Create a ast_multi_channel_blob suitable for a stasis_message.
Since
12 The given blob should be treated as immutable and not modified after it is put into the message.
Parameters
blob The JSON blob that defines the data of this ast_multi_channel_blob
Returns
ast_multi_channel_blob object
NULL on error
Definition at line 881 of file stasis_channels.c.
References ao2_alloc, AO2_ALLOC_OPT_LOCK_MUTEX, ao2_container_alloc_hash, ao2_ref, ast_assert, ast_json_ref(), ast_multi_channel_blob::blob, channel_role_cmp_cb(), channel_role_hash_cb(), ast_multi_channel_blob::channel_snapshots, multi_channel_blob_dtor(), NULL, and NUM_MULTI_CHANNEL_BLOB_BUCKETS.
Referenced by ast_channel_publish_dial_internal(), AST_TEST_DEFINE(), local_channel_optimization_blob(), publish_chanspy_message(), publish_local_bridge_message(), queue_publish_multi_channel_snapshot_blob(), and send_call_pickup_stasis_message().
 {
    struct ast_multi_channel_blob *obj;
    ast_assert(blob != NULL);
    obj = ao2_alloc(sizeof(*obj), multi_channel_blob_dtor);
    if (!obj) {
       return NULL;
    }
    obj->channel_snapshots = ao2_container_alloc_hash(AO2_ALLOC_OPT_LOCK_MUTEX, 0,
       NUM_MULTI_CHANNEL_BLOB_BUCKETS, channel_role_hash_cb, NULL, channel_role_cmp_cb);
    if (!obj->channel_snapshots) {
       ao2_ref(obj, -1);
       return NULL;
    }
    obj->blob = ast_json_ref(blob);
    return obj;
 }
ast_multi_channel_blob_get_channel()
struct ast_channel_snapshot* ast_multi_channel_blob_get_channel (struct ast_multi_channel_blob * obj, const char * role)
Retrieve a channel snapshot associated with a specific role from a ast_multi_channel_blob.
Since
12
Note
The reference count of the ast_channel_snapshot returned from this function is not changed. The caller of this function does not own the reference to the snapshot.
Parameters
obj The ast_multi_channel_blob containing the channel snapshot to retrieve
role The role associated with the channel snapshot
Return values
Definition at line 977 of file stasis_channels.c.
References ao2_find, ao2_ref, ast_strlen_zero, ast_multi_channel_blob::channel_snapshots, NULL, OBJ_SEARCH_KEY, and channel_role_snapshot::snapshot.
Referenced by AST_TEST_DEFINE(), call_forwarded_handler(), call_pickup_to_ami(), cel_dial_cb(), cel_local_cb(), cel_pickup_cb(), channel_chanspy_start_cb(), channel_chanspy_stop_cb(), channel_dial_cb(), dial_to_json(), handle_dial_message(), handle_local_optimization_begin(), handle_local_optimization_end(), local_message_to_ami(), and queue_multi_channel_to_ami().
 {
    struct channel_role_snapshot *role_snapshot;
    struct ast_channel_snapshot *snapshot;
    if (!obj || ast_strlen_zero(role)) {
       return NULL;
    }
    role_snapshot = ao2_find(obj->channel_snapshots, role, OBJ_SEARCH_KEY);
    /* Note that this function does not increase the ref count on snapshot */
    if (!role_snapshot) {
       return NULL;
    }
    snapshot = role_snapshot->snapshot;
    ao2_ref(role_snapshot, -1);
    return snapshot;
 }
ast_multi_channel_blob_get_channels()
struct ao2_container* ast_multi_channel_blob_get_channels (struct ast_multi_channel_blob * obj, const char * role)
Retrieve all channel snapshots associated with a specific role from a ast_multi_channel_blob.
Since
12
Note
Because this function returns an ao2_container (hashed by channel name) of all channel snapshots that matched the passed in role, the reference of the snapshots is increased by this function. The caller of this function must release the reference to the snapshots by disposing of the container appropriately.
Parameters
obj The ast_multi_channel_blob containing the channel snapshots to retrieve
role The role associated with the channel snapshots
Return values
A container containing all ast_channel_snapshot objects matching the role on success.
NULL on error or not found for the role specified
Definition at line 995 of file stasis_channels.c.
References AO2_ALLOC_OPT_LOCK_MUTEX, ao2_callback, ao2_container_alloc_hash, ao2_iterator_destroy(), ao2_iterator_next, ao2_link, ao2_ref, ast_strdupa, ast_strlen_zero, channel_role_cmp_cb(), channel_snapshot_cmp_cb(), channel_snapshot_hash_cb(), ast_multi_channel_blob::channel_snapshots, NULL, NUM_MULTI_CHANNEL_BLOB_BUCKETS, OBJ_MULTIPLE, OBJ_SEARCH_KEY, and channel_role_snapshot::snapshot.
Referenced by AST_TEST_DEFINE().
 {
    struct ao2_container *ret_container;
    struct ao2_iterator *it_role_snapshots;
    struct channel_role_snapshot *role_snapshot;
    char *arg;
    if (!obj || ast_strlen_zero(role)) {
       return NULL;
    }
    ret_container = ao2_container_alloc_hash(AO2_ALLOC_OPT_LOCK_MUTEX, 0,
       NUM_MULTI_CHANNEL_BLOB_BUCKETS,
       channel_snapshot_hash_cb, NULL, channel_snapshot_cmp_cb);
    if (!ret_container) {
       return NULL;
    }
    arg = ast_strdupa(role);
    it_role_snapshots = ao2_callback(obj->channel_snapshots,
       OBJ_MULTIPLE | OBJ_SEARCH_KEY, channel_role_cmp_cb, arg);
    if (!it_role_snapshots) {
       ao2_ref(ret_container, -1);
       return NULL;
    }
    while ((role_snapshot = ao2_iterator_next(it_role_snapshots))) {
       ao2_link(ret_container, role_snapshot->snapshot);
       ao2_ref(role_snapshot, -1);
    }
    ao2_iterator_destroy(it_role_snapshots);
    return ret_container;
 }
ast_multi_channel_blob_get_json()
struct ast_json* ast_multi_channel_blob_get_json (struct ast_multi_channel_blob * obj)
Retrieve the JSON blob from a ast_multi_channel_blob. Returned ast_json is still owned by obj.
Since
12
Parameters
obj Channel blob object.
Returns
Type field value from the blob.
NULL on error.
Definition at line 1030 of file stasis_channels.c.
References ast_multi_channel_blob::blob, and NULL.
Referenced by AST_TEST_DEFINE(), channel_dial_cb(), dial_to_json(), get_blob_variable(), handle_dial_message(), handle_local_optimization_begin(), handle_local_optimization_end(), local_message_to_ami(), and queue_multi_channel_to_ami().
 {
    if (!obj) {
       return NULL;
    }
    return obj->blob;
 }
ast_multi_object_blob_add()
void ast_multi_object_blob_add (struct ast_multi_object_blob * multi, enum stasis_user_multi_object_snapshot_type type, void * object)
Add an object to a multi object blob previously created.
Since
12.3.0
Parameters
multi The multi object blob previously created
type Type code for the object such as channel, bridge, etc.
object Snapshot object of the type supplied to typename
Returns
Nothing
Add an object to a multi object blob previously created.
Definition at line 2001 of file stasis.c.
References ao2_cleanup, and AST_VECTOR_APPEND.
Referenced by ast_multi_object_blob_single_channel_publish(), and stasis_app_user_event().
 {
    if (!multi || !object || AST_VECTOR_APPEND(&multi->snapshots[type], object)) {
       ao2_cleanup(object);
    }
 }
ast_multi_object_blob_create()
struct ast_multi_object_blob* ast_multi_object_blob_create (struct ast_json * blob)
Create a stasis multi object blob.
Since
12.3.0
Multi object blob can store a combination of arbitrary json values (the blob) and also snapshots of various other system objects (such as channels, bridges, etc) for delivery through a stasis message. The multi object blob is first created, then optionally objects are added to it, before being attached to a message and delivered to stasis topic.
Parameters
blob Json blob
Note
When used for an ast_multi_user_event_type message, the json blob should contain at minimum {eventname: name}.
Return values
ast_multi_object_blob* if succeeded
NULL if creation failed
Create a stasis multi object blob.
Definition at line 1975 of file stasis.c.
References ao2_alloc, ao2_ref, ast_assert, ast_json_ref(), AST_VECTOR_INIT, ast_multi_object_blob::blob, multi_object_blob_dtor(), NULL, STASIS_UMOS_MAX, and type.
Referenced by ast_multi_object_blob_single_channel_publish(), and stasis_app_user_event().
 {
    int type;
    struct ast_multi_object_blob *multi;
    ast_assert(blob != NULL);
    multi = ao2_alloc(sizeof(*multi), multi_object_blob_dtor);
    if (!multi) {
       return NULL;
    }
    for (type = 0; type < STASIS_UMOS_MAX; ++type) {
       if (AST_VECTOR_INIT(&multi->snapshots[type], 0)) {
          ao2_ref(multi, -1);
          return NULL;
       }
    }
    multi->blob = ast_json_ref(blob);
    return multi;
 }
ast_multi_object_blob_single_channel_publish()
void ast_multi_object_blob_single_channel_publish (struct ast_channel * chan, struct stasis_message_type * type, struct ast_json * blob)
Create and publish a stasis message blob on a channel with it's snapshot.
Since
12.3.0
For compatibility with app_userevent, this creates a multi object blob message, attaches the channel snapshot to it, and publishes it to the channel's topic.
Parameters
chan The channel to snapshot and publish event to
type The message type
blob A json blob to publish with the snapshot
Returns
Nothing
Create and publish a stasis message blob on a channel with it's snapshot.
Definition at line 2010 of file stasis.c.
References ao2_ref, ast_channel_snapshot_create(), ast_channel_topic(), ast_multi_object_blob_add(), ast_multi_object_blob_create(), stasis_message_create(), stasis_publish(), and STASIS_UMOS_CHANNEL.
Referenced by userevent_exec().
 {
    struct stasis_message *message;
    struct ast_channel_snapshot *channel_snapshot;
    struct ast_multi_object_blob *multi;
    if (!type) {
       return;
    }
    multi = ast_multi_object_blob_create(blob);
    if (!multi) {
       return;
    }
    channel_snapshot = ast_channel_snapshot_create(chan);
    if (!channel_snapshot) {
       ao2_ref(multi, -1);
       return;
    }
    /* this call steals the channel_snapshot reference */
    ast_multi_object_blob_add(multi, STASIS_UMOS_CHANNEL, channel_snapshot);
    message = stasis_message_create(type, multi);
    ao2_ref(multi, -1);
    if (message) {
       /* app_userevent still publishes to channel */
       stasis_publish(ast_channel_topic(chan), message);
       ao2_ref(message, -1);
    }
 }
ast_multi_user_event_type()
struct stasis_message_type* ast_multi_user_event_type (void)
Message type for custom user defined events with multi object blobs.
Returns
The stasis_message_type for user event
Since
12.3.0
Referenced by declined_handler(), stasis_app_user_event(), stasis_cleanup(), stasis_init(), and userevent_exec().
ast_mwi_blob_create()
struct stasis_message* ast_mwi_blob_create (struct ast_mwi_state * mwi_state, struct stasis_message_type * message_type, struct ast_json * blob)
Creates a ast_mwi_blob message.
Since
12 The blob JSON object requires a "type" field describing the blob. It should also be treated as immutable and not modified after it is put into the message.
Parameters
mwi_state MWI state associated with the update
message_type The type of message to create
blob JSON object representing the data.
Returns
ast_mwi_blob message.
NULL on error
Definition at line 462 of file mwi.c.
References ao2_alloc, ao2_ref, ast_assert, ast_json_ref(), ast_mwi_blob::blob, mwi_blob_dtor(), ast_mwi_blob::mwi_state, NULL, and stasis_message_create().
Referenced by notify_new_message().
 {
    struct ast_mwi_blob *obj;
    struct stasis_message *msg;
    ast_assert(blob != NULL);
    if (!message_type) {
       return NULL;
    }
    obj = ao2_alloc(sizeof(*obj), mwi_blob_dtor);
    if (!obj) {
       return NULL;
    }
    obj->mwi_state = mwi_state;
    ao2_ref(obj->mwi_state, +1);
    obj->blob = ast_json_ref(blob);
    /* This is not a normal MWI event.  Only used by the MinivmNotify app. */
    msg = stasis_message_create(message_type, obj);
    ao2_ref(obj, -1);
    return msg;
 }
ast_mwi_create()
struct ast_mwi_state* ast_mwi_create (const char * mailbox, const char * context)
Create a ast_mwi_state object.
Since
12
Parameters
[in] mailbox The mailbox identifier string.
[in] context The context this mailbox resides in (NULL or "" if only using mailbox)
Return values
Definition at line 148 of file mwi.c.
References mwi_create_state().
Referenced by notify_new_message().
 {
    return mwi_create_state(mailbox, context, 0, 0, 0);
 }
ast_mwi_state_cache()
struct stasis_cache* ast_mwi_state_cache (void)
Backend cache for ast_mwi_topic_cached().
Return values
Cache of ast_mwi_state.
Definition at line 90 of file mwi.c.
References mwi_state_cache.
Referenced by ast_delete_mwi_state_full(), asterisk_publication_mwi_refresh(), asterisk_start_mwi_publishing(), get_cached_mwi(), has_voicemail(), load_module(), unistim_send_mwi_to_peer(), and update_registry().
 {
    return mwi_state_cache;
 }
ast_mwi_state_type()
struct stasis_message_type* ast_mwi_state_type (void)
Get the Stasis Message Bus API message type for MWI messages.
Return values
The message type structure for MWI messages
NULL on error
Since
12
Referenced by ast_delete_mwi_state_full(), ast_mwi_subscribe_pool(), asterisk_publisher_mwistate_cb(), asterisk_start_mwi_publishing(), get_cached_mwi(), has_voicemail(), load_module(), manager_mwi_init(), mwi_cleanup(), mwi_event_cb(), mwi_init(), mwi_stasis_cb(), mwi_state_create_message(), mwi_state_get_id(), mwi_to_event(), mwi_update_cb(), unistim_send_mwi_to_peer(), update_registry(), xmpp_init_event_distribution(), and xmpp_pubsub_mwi_cb().
ast_mwi_topic()
struct stasis_topic* ast_mwi_topic (const char * uniqueid)
Get the Stasis Message Bus API topic for MWI messages on a unique ID.
Parameters
uniqueid The unique id for which to get the topic
Return values
The topic structure for MWI messages for a given uniqueid
NULL if it failed to be found or allocated
Since
12
Definition at line 100 of file mwi.c.
References stasis_state_topic().
Referenced by notify_new_message().
 {
    return stasis_state_topic(mwi_state_manager, uniqueid);
 }
ast_mwi_topic_all()
struct stasis_topic* ast_mwi_topic_all (void)
Get the Stasis Message Bus API topic for MWI messages.
Return values
The topic structure for MWI messages
NULL if it has not been allocated
Since
12
Definition at line 85 of file mwi.c.
References stasis_state_all_topic().
Referenced by asterisk_start_mwi_publishing(), load_module(), manager_mwi_init(), mwi_init(), and xmpp_init_event_distribution().
 {
    return stasis_state_all_topic(mwi_state_manager);
 }
ast_mwi_topic_cached()
struct stasis_topic* ast_mwi_topic_cached (void)
Get the Stasis Message Bus API caching topic for MWI messages.
Return values
The caching topic structure for MWI messages
NULL if it has not been allocated
Since
12
Definition at line 95 of file mwi.c.
References stasis_caching_get_topic().
 {
    return stasis_caching_get_topic(mwi_topic_cached);
 }
ast_mwi_vm_app_type()
struct stasis_message_type* ast_mwi_vm_app_type (void)
Get the Stasis Message Bus API message type for voicemail application specific messages.
This message type exists for those messages a voicemail application may wish to send that have no logical relationship with other voicemail applications. Voicemail apps that use this message type must pass a ast_mwi_blob. Any extraneous information in the JSON blob must be packed as key/value pair tuples of strings.
At least one key/value tuple must have a key value of "Event".
Return values
The stasis_message_type for voicemail application specific messages
NULL on error
Since
12
Referenced by manager_mwi_init(), mwi_cleanup(), mwi_init(), mwi_to_event(), and notify_new_message().
ast_parked_call_type()
struct stasis_message_type* ast_parked_call_type (void)
accessor for the parked call stasis message type
Since
12
Return values
NULL if the parking topic hasn't been created or has been canceled
a pointer to the parked call message type
Referenced by ast_parking_stasis_init(), create_parked_subscription_full(), create_routes(), load_module(), park_and_announce_app_exec(), park_announce_update_cb(), parker_update_cb(), parking_event_cb(), parking_manager_enable_stasis(), parking_stasis_cleanup(), publish_parked_call(), and publish_parked_call_failure().
ast_parking_topic()
struct stasis_topic* ast_parking_topic (void)
accessor for the parking stasis topic
Since
12
Return values
NULL if the parking topic hasn't been created or has been disabled
a pointer to the parking topic
Definition at line 67 of file parking.c.
References parking_topic.
Referenced by create_parked_subscription_full(), create_subscriptions(), park_and_announce_app_exec(), parking_manager_enable_stasis(), publish_parked_call(), and publish_parked_call_failure().
 {
    return parking_topic;
 }
ast_rtp_convert_stats_json()
struct ast_json* ast_rtp_convert_stats_json (const struct ast_rtp_instance_stats * stats)
Convert given stat instance into json format.
Parameters
stats
Return values
A json format stat
Definition at line 3956 of file rtp_engine.c.
References ast_json_integer_create(), ast_json_object_create(), ast_json_object_set(), ast_json_real_create(), ast_json_string_create(), ast_json_unref(), ast_log, ast_rtp_instance_stats::channel_uniqueid, ast_rtp_instance_stats::local_maxjitter, ast_rtp_instance_stats::local_maxrxploss, ast_rtp_instance_stats::local_minjitter, ast_rtp_instance_stats::local_minrxploss, ast_rtp_instance_stats::local_normdevjitter, ast_rtp_instance_stats::local_normdevrxploss, ast_rtp_instance_stats::local_ssrc, ast_rtp_instance_stats::local_stdevjitter, ast_rtp_instance_stats::local_stdevrxploss, LOG_WARNING, ast_rtp_instance_stats::maxrtt, ast_rtp_instance_stats::minrtt, ast_rtp_instance_stats::normdevrtt, NULL, ast_rtp_instance_stats::remote_maxjitter, ast_rtp_instance_stats::remote_maxrxploss, ast_rtp_instance_stats::remote_minjitter, ast_rtp_instance_stats::remote_minrxploss, ast_rtp_instance_stats::remote_normdevjitter, ast_rtp_instance_stats::remote_normdevrxploss, ast_rtp_instance_stats::remote_ssrc, ast_rtp_instance_stats::remote_stdevjitter, ast_rtp_instance_stats::remote_stdevrxploss, ast_rtp_instance_stats::rtt, ast_rtp_instance_stats::rxcount, ast_rtp_instance_stats::rxjitter, ast_rtp_instance_stats::rxoctetcount, ast_rtp_instance_stats::rxploss, SET_AST_JSON_OBJ, ast_rtp_instance_stats::stdevrtt, ast_rtp_instance_stats::txcount, ast_rtp_instance_stats::txjitter, ast_rtp_instance_stats::txoctetcount, and ast_rtp_instance_stats::txploss.
Referenced by ast_rtp_instance_get_stats_all_json().
 {
    struct ast_json *j_res;
    int ret;
    j_res = ast_json_object_create();
    if (!j_res) {
       return NULL;
    }
    /* set mandatory items */
    ret = ast_json_object_set(j_res, "txcount", ast_json_integer_create(stats->txcount));
    ret |= ast_json_object_set(j_res, "rxcount", ast_json_integer_create(stats->rxcount));
    ret |= ast_json_object_set(j_res, "txploss", ast_json_integer_create(stats->txploss));
    ret |= ast_json_object_set(j_res, "rxploss", ast_json_integer_create(stats->rxploss));
    ret |= ast_json_object_set(j_res, "local_ssrc", ast_json_integer_create(stats->local_ssrc));
    ret |= ast_json_object_set(j_res, "remote_ssrc", ast_json_integer_create(stats->remote_ssrc));
    ret |= ast_json_object_set(j_res, "txoctetcount", ast_json_integer_create(stats->txoctetcount));
    ret |= ast_json_object_set(j_res, "rxoctetcount", ast_json_integer_create(stats->rxoctetcount));
    ret |= ast_json_object_set(j_res, "channel_uniqueid", ast_json_string_create(stats->channel_uniqueid));
    if (ret) {
       ast_log(LOG_WARNING, "Could not create rtp statistics info. channel: %s\n", stats->channel_uniqueid);
       ast_json_unref(j_res);
       return NULL;
    }
    /* set other items */
    SET_AST_JSON_OBJ(j_res, "txjitter", ast_json_real_create(stats->txjitter));
    SET_AST_JSON_OBJ(j_res, "rxjitter", ast_json_real_create(stats->rxjitter));
    SET_AST_JSON_OBJ(j_res, "remote_maxjitter", ast_json_real_create(stats->remote_maxjitter));
    SET_AST_JSON_OBJ(j_res, "remote_minjitter", ast_json_real_create(stats->remote_minjitter));
    SET_AST_JSON_OBJ(j_res, "remote_normdevjitter", ast_json_real_create(stats->remote_normdevjitter));
    SET_AST_JSON_OBJ(j_res, "remote_stdevjitter", ast_json_real_create(stats->remote_stdevjitter));
    SET_AST_JSON_OBJ(j_res, "local_maxjitter", ast_json_real_create(stats->local_maxjitter));
    SET_AST_JSON_OBJ(j_res, "local_minjitter", ast_json_real_create(stats->local_minjitter));
    SET_AST_JSON_OBJ(j_res, "local_normdevjitter", ast_json_real_create(stats->local_normdevjitter));
    SET_AST_JSON_OBJ(j_res, "local_stdevjitter", ast_json_real_create(stats->local_stdevjitter));
    SET_AST_JSON_OBJ(j_res, "remote_maxrxploss", ast_json_real_create(stats->remote_maxrxploss));
    SET_AST_JSON_OBJ(j_res, "remote_minrxploss", ast_json_real_create(stats->remote_minrxploss));
    SET_AST_JSON_OBJ(j_res, "remote_normdevrxploss", ast_json_real_create(stats->remote_normdevrxploss));
    SET_AST_JSON_OBJ(j_res, "remote_stdevrxploss", ast_json_real_create(stats->remote_stdevrxploss));
    SET_AST_JSON_OBJ(j_res, "local_maxrxploss", ast_json_real_create(stats->local_maxrxploss));
    SET_AST_JSON_OBJ(j_res, "local_minrxploss", ast_json_real_create(stats->local_minrxploss));
    SET_AST_JSON_OBJ(j_res, "local_normdevrxploss", ast_json_real_create(stats->local_normdevrxploss));
    SET_AST_JSON_OBJ(j_res, "local_stdevrxploss", ast_json_real_create(stats->local_stdevrxploss));
    SET_AST_JSON_OBJ(j_res, "rtt", ast_json_real_create(stats->rtt));
    SET_AST_JSON_OBJ(j_res, "maxrtt", ast_json_real_create(stats->maxrtt));
    SET_AST_JSON_OBJ(j_res, "minrtt", ast_json_real_create(stats->minrtt));
    SET_AST_JSON_OBJ(j_res, "normdevrtt", ast_json_real_create(stats->normdevrtt));
    SET_AST_JSON_OBJ(j_res, "stdevrtt", ast_json_real_create(stats->stdevrtt));
    return j_res;
 }
ast_rtp_get_rate()
int ast_rtp_get_rate (const struct ast_format * format)
Retrieve the sample rate of a format according to RTP specifications.
Since
16.7.0
17.1.0
Parameters
format The media format
Return values
The sample rate
Definition at line 4030 of file rtp_engine.c.
References ast_format_cmp(), AST_FORMAT_CMP_EQUAL, ast_format_g722, and ast_format_get_sample_rate().
Referenced by ast_rtcp_calculate_sr_rr_statistics(), ast_rtcp_generate_report(), ast_rtp_dtmf_end_with_duration(), ast_rtp_interpret(), calc_rxstamp(), jitterbuffer_frame_get_ntp_timestamp(), process_dtmf_cisco(), process_dtmf_rfc2833(), and rtp_raw_write().
 {
    /* For those wondering: due to a fluke in RFC publication, G.722 is advertised
     * as having a sample rate of 8kHz, while implementations must know that its
     * real rate is 16kHz. Seriously.
     */
         return (ast_format_cmp(format, ast_format_g722) == AST_FORMAT_CMP_EQUAL) ? 8000 : (int)ast_format_get_sample_rate(format);
 }
ast_rtp_instance_drop_packets()
void ast_rtp_instance_drop_packets (struct ast_rtp_instance * instance, int num)
Set the number of packets to drop on RTP read.
Parameters
instance The RTP instance
num The number of packets to drop
Definition at line 3905 of file rtp_engine.c.
References ast_log, ast_rtp_instance_get_test(), LOG_ERROR, and ast_rtp_engine_test::packets_to_drop.
Referenced by AST_TEST_DEFINE().
 {
    struct ast_rtp_engine_test *test = ast_rtp_instance_get_test(instance);
    if (!test) {
       ast_log(LOG_ERROR, "There is no test engine set up!\n");
       return;
    }
    test->packets_to_drop = num;
 }
ast_rtp_instance_get_recv_buffer_count()
size_t ast_rtp_instance_get_recv_buffer_count (struct ast_rtp_instance * instance)
Get the current size of the receive buffer.
Parameters
instance The RTP instance
Return values
The recv_buffer size if it exists, else 0
Definition at line 3857 of file rtp_engine.c.
References ao2_lock, ao2_unlock, ast_log, ast_rtp_instance_get_test(), LOG_ERROR, and ast_rtp_engine_test::recv_buffer_count.
Referenced by AST_TEST_DEFINE().
 {
    size_t res;
    struct ast_rtp_engine_test *test = ast_rtp_instance_get_test(instance);
    if (!test) {
       ast_log(LOG_ERROR, "There is no test engine set up!\n");
       return 0;
    }
    ao2_lock(instance);
    res = test->recv_buffer_count(instance);
    ao2_unlock(instance);
    return res;
 }
ast_rtp_instance_get_recv_buffer_max()
size_t ast_rtp_instance_get_recv_buffer_max (struct ast_rtp_instance * instance)
Get the maximum size of the receive buffer.
Parameters
instance The RTP instance
Return values
The recv_buffer max size if it exists, else 0
Definition at line 3840 of file rtp_engine.c.
References ao2_lock, ao2_unlock, ast_log, ast_rtp_instance_get_test(), LOG_ERROR, and ast_rtp_engine_test::recv_buffer_max.
Referenced by AST_TEST_DEFINE().
 {
    size_t res;
    struct ast_rtp_engine_test *test = ast_rtp_instance_get_test(instance);
    if (!test) {
       ast_log(LOG_ERROR, "There is no test engine set up!\n");
       return 0;
    }
    ao2_lock(instance);
    res = test->recv_buffer_max(instance);
    ao2_unlock(instance);
    return res;
 }
ast_rtp_instance_get_sdes_received()
int ast_rtp_instance_get_sdes_received (struct ast_rtp_instance * instance)
Get the value of sdes_received on the test engine.
Parameters
instance The RTP instance
Return values
1 if sdes_received, else 0
Definition at line 3929 of file rtp_engine.c.
References ast_log, ast_rtp_instance_get_test(), LOG_ERROR, and ast_rtp_engine_test::sdes_received.
Referenced by AST_TEST_DEFINE().
 {
    struct ast_rtp_engine_test *test = ast_rtp_instance_get_test(instance);
    if (!test) {
       ast_log(LOG_ERROR, "There is no test engine set up!\n");
       return 0;
    }
    return test->sdes_received;
 }
ast_rtp_instance_get_send_buffer_count()
size_t ast_rtp_instance_get_send_buffer_count (struct ast_rtp_instance * instance)
Get the current size of the send buffer.
Parameters
instance The RTP instance
Return values
The send_buffer size if it exists, else 0
Definition at line 3874 of file rtp_engine.c.
References ao2_lock, ao2_unlock, ast_log, ast_rtp_instance_get_test(), LOG_ERROR, and ast_rtp_engine_test::send_buffer_count.
Referenced by AST_TEST_DEFINE().
 {
    size_t res;
    struct ast_rtp_engine_test *test = ast_rtp_instance_get_test(instance);
    if (!test) {
       ast_log(LOG_ERROR, "There is no test engine set up!\n");
       return 0;
    }
    ao2_lock(instance);
    res = test->send_buffer_count(instance);
    ao2_unlock(instance);
    return res;
 }
ast_rtp_instance_get_stats_all_json()
struct ast_json* ast_rtp_instance_get_stats_all_json (struct ast_rtp_instance * instance)
Retrieve statistics about an RTP instance in json format.
Parameters
instance
Return values
json object of stats
Definition at line 4019 of file rtp_engine.c.
References ast_rtp_convert_stats_json(), ast_rtp_instance_get_stats(), AST_RTP_INSTANCE_STAT_ALL, and NULL.
Referenced by ast_ari_channels_rtpstatistics().
 {
    struct ast_rtp_instance_stats stats = {0,};
    if(ast_rtp_instance_get_stats(instance, &stats, AST_RTP_INSTANCE_STAT_ALL)) {
       return NULL;
    }
    return ast_rtp_convert_stats_json(&stats);
 }
ast_rtp_instance_queue_report()
void ast_rtp_instance_queue_report (struct ast_rtp_instance * instance)
Sends a SR/RR report the next time RTP would be sent.
Parameters
instance The RTP instance
Definition at line 3917 of file rtp_engine.c.
References ast_log, ast_rtp_instance_get_test(), LOG_ERROR, and ast_rtp_engine_test::send_report.
Referenced by AST_TEST_DEFINE().
 {
    struct ast_rtp_engine_test *test = ast_rtp_instance_get_test(instance);
    if (!test) {
       ast_log(LOG_ERROR, "There is no test engine set up!\n");
       return;
    }
    test->send_report = 1;
 }
ast_rtp_instance_reset_test_engine()
void ast_rtp_instance_reset_test_engine (struct ast_rtp_instance * instance)
Resets all the fields to default values for the test engine.
Parameters
instance The RTP instance
Definition at line 3941 of file rtp_engine.c.
References ast_log, ast_rtp_instance_get_test(), LOG_ERROR, ast_rtp_engine_test::packets_to_drop, ast_rtp_engine_test::sdes_received, and ast_rtp_engine_test::send_report.
Referenced by test_init_rtp_instances().
 {
    struct ast_rtp_engine_test *test = ast_rtp_instance_get_test(instance);
    if (!test) {
       ast_log(LOG_ERROR, "There is no test engine set up!\n");
       return;
    }
    test->packets_to_drop = 0;
    test->send_report = 0;
    test->sdes_received = 0;
 }
ast_rtp_instance_set_schedid()
void ast_rtp_instance_set_schedid (struct ast_rtp_instance * instance, int id)
Set the schedid for RTCP.
Parameters
instance The RTP instance
id The number to set schedid to
Definition at line 3891 of file rtp_engine.c.
References ao2_lock, ao2_unlock, ast_log, ast_rtp_instance_get_test(), LOG_ERROR, and ast_rtp_engine_test::set_schedid.
Referenced by AST_TEST_DEFINE().
 {
    struct ast_rtp_engine_test *test = ast_rtp_instance_get_test(instance);
    if (!test) {
       ast_log(LOG_ERROR, "There is no test engine set up!\n");
       return;
    }
    ao2_lock(instance);
    test->set_schedid(instance, id);
    ao2_unlock(instance);
 }
ast_rtp_rtcp_received_type()
struct stasis_message_type* ast_rtp_rtcp_received_type (void)
Message type for an RTCP message received from some external source.
Since
12
Return values
A stasis message type
Referenced by ast_rtcp_interpret(), ast_rtp_engine_init(), ast_rtp_publish_rtcp_message(), load_module(), rtcp_report_to_ami(), rtp_engine_shutdown(), and rtp_topic_handler().
ast_rtp_rtcp_sent_type()
struct stasis_message_type* ast_rtp_rtcp_sent_type (void)
Message type for an RTCP message sent from this Asterisk instance.
Since
12
Return values
A stasis message type
Referenced by ast_rtcp_calculate_sr_rr_statistics(), ast_rtp_engine_init(), ast_rtp_publish_rtcp_message(), load_module(), rtp_engine_shutdown(), and rtp_topic_handler().
ast_rtp_topic()
struct stasis_topic* ast_rtp_topic (void)
Stasis Message Bus API topic for RTP and RTCP related messages
Since
12
Return values
A Stasis Message Bus API topic
Definition at line 3531 of file rtp_engine.c.
References rtp_topic.
Referenced by ast_rtp_publish_rtcp_message(), load_module(), and manager_subscriptions_init().
 {
    return rtp_topic;
 }
mwi_init()
int mwi_init (void)
Initialize the mwi core.
Return values
0 Success
-1 Failure
Since
13.27.0
16.4.0
Definition at line 502 of file mwi.c.
References ast_mwi_state_type(), ast_mwi_topic_all(), ast_mwi_vm_app_type(), ast_register_cleanup(), mwi_cleanup(), mwi_state_get_id(), stasis_cache_create(), stasis_caching_topic_create(), STASIS_MESSAGE_TYPE_INIT, and stasis_state_manager_create().
Referenced by asterisk_daemon().
 {
    ast_register_cleanup(mwi_cleanup);
    if (STASIS_MESSAGE_TYPE_INIT(ast_mwi_state_type) != 0) {
       return -1;
    }
    if (STASIS_MESSAGE_TYPE_INIT(ast_mwi_vm_app_type) != 0) {
       return -1;
    }
    mwi_state_manager = stasis_state_manager_create("mwi:all");
    if (!mwi_state_manager) {
       return -1;
    }
    mwi_state_cache = stasis_cache_create(mwi_state_get_id);
    if (!mwi_state_cache) {
       return -1;
    }
    mwi_topic_cached = stasis_caching_topic_create(ast_mwi_topic_all(), mwi_state_cache);
    if (!mwi_topic_cached) {
       return -1;
    }
    return 0;
 }
stasis_cache_clear_type()
struct stasis_message_type* stasis_cache_clear_type (void)
Message type for clearing a message from a stasis cache.
Since
12
Referenced by caching_topic_exec(), stasis_cache_cleanup(), stasis_cache_clear_create(), stasis_cache_dump_all(), stasis_cache_init(), and stasis_caching_accept_message_type().
stasis_cache_update_type()
struct stasis_message_type* stasis_cache_update_type (void)
Message type for cache update messages.
Returns
Message type for cache update messages.
Since
12
Referenced by AST_TEST_DEFINE(), cache_update(), find_route(), load_module(), stasis_cache_cleanup(), stasis_cache_dump_all(), stasis_cache_init(), stasis_message_router_add_cache_update(), sub_endpoint_update_handler(), and update_create().
stasis_subscription_change_type()
struct stasis_message_type* stasis_subscription_change_type (void)
Gets the message type for subscription change notices.
Returns
The stasis_message_type for subscription change notices
Since
12
Referenced by add_peer_mwi_subs(), app_create(), AST_TEST_DEFINE(), asterisk_start_devicestate_publishing(), asterisk_start_mwi_publishing(), caching_topic_exec(), cc_generic_agent_start_monitoring(), consumer_exec(), consumer_exec_sync(), create_message_types(), create_parked_subscription_full(), endpoint_internal_create(), message_sink_cb(), mwi_stasis_subscription_alloc(), mwi_state_get_id(), park_and_announce_app_exec(), refer_blind_callback(), send_subscription_subscribe(), send_subscription_unsubscribe(), stasis_caching_accept_message_type(), stasis_cleanup(), stasis_init(), stasis_message_router_create_internal(), stasis_subscription_final_message(), subscribe_device_state(), and subscription_invoke().
stasis_test_message_create()
struct stasis_message* stasis_test_message_create (void)
Creates a test message.
Definition at line 236 of file res_stasis_test.c.
References ao2_alloc, ao2_cleanup, stasis_message::data, NULL, RAII_VAR, stasis_message_create(), and stasis_test_message_type().
 {
    RAII_VAR(void *, data, NULL, ao2_cleanup);
    if (!stasis_test_message_type()) {
       return NULL;
    }
    /* We just need the unique pointer; don't care what's in it */
    data = ao2_alloc(1, NULL);
    if (!data) {
       return NULL;
    }
    return stasis_message_create(stasis_test_message_type(), data);
 }
stasis_test_message_type()
struct stasis_message_type* stasis_test_message_type (void)
Gets the type of messages created by stasis_test_message_create().
Referenced by load_module(), stasis_test_message_create(), and unload_module().
Variable Documentation
__field_mgr
struct ast_string_field_mgr __field_mgr
Definition at line 460 of file mwi.h.
__field_mgr_pool
struct ast_string_field_pool* __field_mgr_pool
Definition at line 460 of file mwi.h.
blob
struct ast_json* blob
JSON blob of data
Definition at line 475 of file mwi.h.
Referenced by ast_mwi_blob_create(), mwi_app_event_cb(), and mwi_blob_dtor().
eid
struct ast_eid eid
The EID of the server where this message originated
Definition at line 465 of file mwi.h.
Referenced by asterisk_publisher_mwistate_cb(), mwi_state_create_message(), mwi_to_event(), and xmpp_pubsub_mwi_cb().
mwi_state
struct ast_mwi_state* mwi_state
MWI state
Definition at line 474 of file mwi.h.
Referenced by ast_mwi_blob_create(), mwi_app_event_cb(), and mwi_blob_dtor().
new_msgs
int new_msgs
The current number of new messages for this mailbox
Definition at line 461 of file mwi.h.
Referenced by asterisk_publisher_mwistate_cb(), get_cached_mwi(), get_message_count(), has_voicemail(), mwi_create_state(), mwi_event_cb(), mwi_retrieve_then_create_state(), mwi_to_event(), mwi_update_cb(), poll_subscribed_mailbox(), unistim_send_mwi_to_peer(), update_registry(), validate_data(), and xmpp_pubsub_mwi_cb().
old_msgs
int old_msgs
The current number of old messages for this mailbox
Definition at line 462 of file mwi.h.
Referenced by asterisk_publisher_mwistate_cb(), get_cached_mwi(), get_message_count(), mwi_create_state(), mwi_retrieve_then_create_state(), mwi_to_event(), mwi_update_cb(), poll_subscribed_mailbox(), update_registry(), validate_data(), and xmpp_pubsub_mwi_cb().
on_subscribe
void(* on_subscribe) (const char *mailbox, struct ast_mwi_subscriber *sub)
Raised when MWI is being subscribed.
Parameters
mailbox The mailbox id subscribed
sub The subscriber subscribed
Definition at line 259 of file mwi.h.
on_unsubscribe
void(* on_unsubscribe) (const char *mailbox, struct ast_mwi_subscriber *sub)
Raised when MWI is being unsubscribed.
Parameters
mailbox The mailbox id being unsubscribed
sub The subscriber to unsubscribe
Definition at line 267 of file mwi.h.
snapshot
struct ast_channel_snapshot* snapshot
If applicable, a snapshot of the channel that caused this MWI change
Definition at line 464 of file mwi.h.
Referenced by mwi_app_event_cb(), mwi_state_create_message(), mwi_state_dtor(), and mwi_update_cb().
uniqueid
const ast_string_field uniqueid
Unique identifier for this mailbox
Definition at line 460 of file mwi.h.
Referenced by ast_delete_mwi_state_full(), ast_mwi_publish_by_mailbox(), asterisk_publisher_mwistate_cb(), explicit_publish_cb(), handle_validate(), implicit_publish_cb(), manager_match_mailbox(), mb_poll_thread(), mwi_app_event_cb(), mwi_create_state(), mwi_handle_unsubscribe2(), mwi_state_get_id(), mwi_to_event(), mwi_update_cb(), poll_subscribed_mailbox(), validate_data(), and xmpp_pubsub_mwi_cb().
urgent_msgs
int urgent_msgs
The current number of urgent messages for this mailbox
Definition at line 466 of file mwi.h.
Referenced by mwi_create_state(), mwi_retrieve_then_create_state(), poll_subscribed_mailbox(), and validate_data().