Asterisk - The Open Source Telephony Project: resample_sse.h File Reference
resample_sse.h File Reference
Resampler functions (SSE version)
#include <xmmintrin.h>
Macros
#define OVERRIDE_INNER_PRODUCT_SINGLE
#define OVERRIDE_INTERPOLATE_PRODUCT_SINGLE
Functions
static float inner_product_single (const float *a, const float *b, unsigned int len)
static float interpolate_product_single (const float *a, const float *b, unsigned int len, const spx_uint32_t oversample, float *frac)
Detailed Description
Resampler functions (SSE version)
Definition in file resample_sse.h.
Macro Definition Documentation
OVERRIDE_INNER_PRODUCT_SINGLE
#define OVERRIDE_INNER_PRODUCT_SINGLE
Definition at line 39 of file resample_sse.h.
OVERRIDE_INTERPOLATE_PRODUCT_SINGLE
#define OVERRIDE_INTERPOLATE_PRODUCT_SINGLE
Definition at line 56 of file resample_sse.h.
Function Documentation
inner_product_single()
static float inner_product_single (const float * a, const float * b, unsigned int len) inline static
Definition at line 40 of file resample_sse.h.
References len().
Referenced by resampler_basic_direct_single().
 {
    int i;
    float ret;
    __m128 sum = _mm_setzero_ps();
    for (i=0;i<len;i+=8)
    {
       sum = _mm_add_ps(sum, _mm_mul_ps(_mm_loadu_ps(a+i), _mm_loadu_ps(b+i)));
       sum = _mm_add_ps(sum, _mm_mul_ps(_mm_loadu_ps(a+i+4), _mm_loadu_ps(b+i+4)));
    }
    sum = _mm_add_ps(sum, _mm_movehl_ps(sum, sum));
    sum = _mm_add_ss(sum, _mm_shuffle_ps(sum, sum, 0x55));
    _mm_store_ss(&ret, sum);
    return ret;
 }
interpolate_product_single()
static float interpolate_product_single (const float * a, const float * b, unsigned int len, const spx_uint32_t oversample, float * frac) inline static
Definition at line 57 of file resample_sse.h.
References a, b, len(), and QualityMapping::oversample.
Referenced by resampler_basic_interpolate_single().
{
   int i;
   float ret;
   __m128 sum = _mm_setzero_ps();
   __m128 f = _mm_loadu_ps(frac);
   for(i=0;i<len;i+=2)
   {
     sum = _mm_add_ps(sum, _mm_mul_ps(_mm_load1_ps(a+i), _mm_loadu_ps(b+i*oversample)));
     sum = _mm_add_ps(sum, _mm_mul_ps(_mm_load1_ps(a+i+1), _mm_loadu_ps(b+(i+1)*oversample)));
   }
    sum = _mm_mul_ps(f, sum);
    sum = _mm_add_ps(sum, _mm_movehl_ps(sum, sum));
    sum = _mm_add_ss(sum, _mm_shuffle_ps(sum, sum, 0x55));
    _mm_store_ss(&ret, sum);
    return ret;
 }