Asterisk - The Open Source Telephony Project: conversions.c File Reference
conversions.c File Reference
Conversion utility functions.
#include <ctype.h>
#include <errno.h>
#include <limits.h>
#include <inttypes.h>
#include <stdio.h>
#include "asterisk/conversions.h"
Functions
int ast_str_to_imax (const char *str, intmax_t *res)
Convert the given string to a signed max size integer.
int ast_str_to_int (const char *str, int *res)
Convert the given string to a signed integer.
int ast_str_to_long (const char *str, long *res)
Convert the given string to a signed long.
int ast_str_to_uint (const char *str, unsigned int *res)
Convert the given string to an unsigned integer.
int ast_str_to_ulong (const char *str, unsigned long *res)
Convert the given string to an unsigned long.
int ast_str_to_umax (const char *str, uintmax_t *res)
Convert the given string to an unsigned max size integer.
static int str_is_negative (const char **str)
Detailed Description
Conversion utility functions.
Definition in file conversions.c.
Function Documentation
ast_str_to_imax()
int ast_str_to_imax (const char * str, intmax_t * res)
Convert the given string to a signed max size integer.
This function will return failure for the following reasons:
The given string to convert is NULL The given string to convert is empty. The given string to convert contains non numeric values Once converted the number is out of range (less than INTMAX_MIN or greater than INTMAX_MAX)
Parameters
str The string to convert
res [out] The converted value
Returns
-1 if it fails to convert, 0 on success
Definition at line 92 of file conversions.c.
References end, and errno.
Referenced by ast_str_to_int(), ast_str_to_long(), and AST_TEST_DEFINE().
 {
    char *end;
    intmax_t val;
    if (!str) {
       return -1;
    }
    errno = 0;
    val = strtoimax(str, &end, 0);
    /*
     * If str equals end then no digits were found. If end is not pointing to
     * a null character then the string contained some numbers that could be
     * converted, but some characters that could not, which we'll consider
     * invalid.
     */
    if (str == end || *end != '\0' || (errno == ERANGE &&
          (val == INTMAX_MIN || val == INTMAX_MAX))) {
       return -1;
    }
    *res = val;
    return 0;
 }
ast_str_to_int()
int ast_str_to_int (const char * str, int * res)
Convert the given string to a signed integer.
This function will return failure for the following reasons:
The given string to convert is NULL The given string to convert is empty. The given string to convert contains non numeric values Once converted the number is out of range (less than INT_MIN or greater than INT_MAX)
Parameters
str The string to convert
res [out] The converted value
Returns
-1 if it fails to convert, 0 on success
Definition at line 44 of file conversions.c.
References ast_str_to_imax().
Referenced by AST_TEST_DEFINE(), category_set_sublevels(), detect_write(), dtmfstore_exec(), freq_parser(), read_sf_exec(), set_id_from_oli(), and wait_exec().
 {
    intmax_t val;
    if (ast_str_to_imax(str, &val) || val < INT_MIN || val > INT_MAX) {
       return -1;
    }
    *res = val;
    return 0;
 }
ast_str_to_long()
int ast_str_to_long (const char * str, long * res)
Convert the given string to a signed long.
This function will return failure for the following reasons:
The given string to convert is NULL The given string to convert is empty. The given string to convert contains non numeric values Once converted the number is out of range (less than LONG_MIN or greater than LONG_MAX)
Parameters
str The string to convert
res [out] The converted value
Returns
-1 if it fails to convert, 0 on success
Definition at line 68 of file conversions.c.
References ast_str_to_imax().
Referenced by AST_TEST_DEFINE().
 {
    intmax_t val;
    if (ast_str_to_imax(str, &val) || val < LONG_MIN || val > LONG_MAX) {
       return -1;
    }
    *res = val;
    return 0;
 }
ast_str_to_uint()
int ast_str_to_uint (const char * str, unsigned int * res)
Convert the given string to an unsigned integer.
This function will return failure for the following reasons:
The given string to convert is NULL The given string to convert is empty. The given string to convert is negative (starts with a '-') The given string to convert contains non numeric values Once converted the number is out of range (greater than UINT_MAX)
Parameters
str The string to convert
res [out] The converted value
Returns
-1 if it fails to convert, 0 on success
Definition at line 56 of file conversions.c.
References ast_str_to_umax().
Referenced by AST_TEST_DEFINE(), func_get_parkingslot_channel(), handle_cli_rtp_drop_incoming_packets(), set_public_key_expiration(), stir_shaken_read(), and stream_echo_exec().
 {
    uintmax_t val;
    if (ast_str_to_umax(str, &val) || val > UINT_MAX) {
       return -1;
    }
    *res = val;
    return 0;
 }
ast_str_to_ulong()
int ast_str_to_ulong (const char * str, unsigned long * res)
Convert the given string to an unsigned long.
This function will return failure for the following reasons:
The given string to convert is NULL The given string to convert is empty. The given string to convert is negative (starts with a '-') The given string to convert contains non numeric values Once converted the number is out of range (greater than ULONG_MAX)
Parameters
str The string to convert
res [out] The converted value
Returns
-1 if it fails to convert, 0 on success
Definition at line 80 of file conversions.c.
References ast_str_to_umax().
Referenced by AST_TEST_DEFINE(), and public_key_is_expired().
 {
    uintmax_t val;
    if (ast_str_to_umax(str, &val) || val > ULONG_MAX) {
       return -1;
    }
    *res = val;
    return 0;
 }
ast_str_to_umax()
int ast_str_to_umax (const char * str, uintmax_t * res)
Convert the given string to an unsigned max size integer.
This function will return failure for the following reasons:
The given string to convert is NULL The given string to convert is empty. The given string to convert is negative (starts with a '-') The given string to convert contains non numeric values Once converted the number is out of range (greater than UINTMAX_MAX)
Parameters
str The string to convert
res [out] The converted value
Returns
-1 if it fails to convert, 0 on success
Definition at line 119 of file conversions.c.
References end, errno, and str_is_negative().
Referenced by ast_str_to_uint(), ast_str_to_ulong(), AST_TEST_DEFINE(), create_foo_type_message(), mailbox_to_num(), and validate_data().
 {
    char *end;
    uintmax_t val;
    if (!str || str_is_negative(&str)) {
       return -1;
    }
    errno = 0;
    val = strtoumax(str, &end, 0);
    /*
     * If str equals end then no digits were found. If end is not pointing to
     * a null character then the string contained some numbers that could be
     * converted, but some characters that could not, which we'll consider
     * invalid.
     */
    if ((str == end || *end != '\0' || (errno == ERANGE && val == UINTMAX_MAX))) {
       return -1;
    }
    *res = val;
    return 0;
 }
str_is_negative()
static int str_is_negative (const char ** str) static
Definition at line 34 of file conversions.c.
References str.
Referenced by ast_str_to_umax().
 {
    /*
     * Ignore any preceding white space. It's okay to move the pointer here
     * since the converting function would do the same, i.e. skip white space.
     */
    while (isspace(**str)) ++*str;
    return **str == '-';
 }