Asterisk - The Open Source Telephony Project: test_named_lock.c File Reference
test_named_lock.c File Reference
Named Lock unit tests.
#include "asterisk.h"
#include <signal.h>
#include "asterisk/test.h"
#include "asterisk/utils.h"
#include "asterisk/module.h"
#include "asterisk/lock.h"
#include "asterisk/named_locks.h"
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
AST_TEST_DEFINE (named_lock_test)
static int load_module (void)
static void * lock_thread (void *data)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Named Lock test module" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, }
static const struct ast_module_info * ast_module_info = &__mod_info
Detailed Description
Named Lock unit tests.
Author
George Joseph georg.nosp@m.e.jo.nosp@m.seph@.nosp@m.fair.nosp@m.view5.nosp@m..com
Definition in file test_named_lock.c.
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 151 of file test_named_lock.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 151 of file test_named_lock.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 151 of file test_named_lock.c.
AST_TEST_DEFINE()
AST_TEST_DEFINE (named_lock_test)
Definition at line 58 of file test_named_lock.c.
References ao2_lock, ao2_trylock, ao2_unlock, ast_named_lock_get, ast_named_lock_put, AST_NAMED_LOCK_TYPE_MUTEX, ast_pthread_create, AST_TEST_FAIL, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_test_status_update, ast_tvdiff_ms(), ast_tvnow(), sip_to_pjsip::info(), lock_thread(), NULL, TEST_EXECUTE, and TEST_INIT.
 {
    enum ast_test_result_state res = AST_TEST_FAIL;
    struct ast_named_lock *lock1 = NULL;
    struct ast_named_lock *lock2 = NULL;
    pthread_t thread1;
    pthread_t thread2;
    struct timeval start_time;
    int64_t duration;
    switch(cmd) {
    case TEST_INIT:
       info->name = "named_lock_test";
       info->category = "/main/lock/";
       info->summary = "Named Lock test";
       info->description =
          "Tests that named locks operate as expected";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    ast_test_status_update(test, "This test should take about 3 seconds\n");
    /* 2 locks/threads to make sure they're independent */
    ast_pthread_create(&thread1, NULL, lock_thread, "lock_1");
    ast_pthread_create(&thread2, NULL, lock_thread, "lock_2");
    lock1 = ast_named_lock_get(AST_NAMED_LOCK_TYPE_MUTEX, "lock_test", "lock_1");
    ast_test_validate_cleanup(test, lock1 != NULL, res, fail);
    lock2 = ast_named_lock_get(AST_NAMED_LOCK_TYPE_MUTEX, "lock_test", "lock_2");
    ast_test_validate_cleanup(test, lock2 != NULL, res, fail);
    usleep(1000000);
    /* These should both fail */
    if (!ao2_trylock(lock1)) {
       ast_test_status_update(test, "ao2_trylock on lock1 succeeded when it should have failed\n");
       ao2_unlock(lock1);
       goto fail;
    }
    if (!ao2_trylock(lock2)) {
       ast_test_status_update(test, "ao2_trylock on lock2 succeeded when it should have failed\n");
       ao2_unlock(lock2);
       goto fail;
    }
    start_time = ast_tvnow();
    /* These should both succeed eventually */
    if (ao2_lock(lock1)) {
       ast_test_status_update(test, "ao2_lock on lock1 failed\n");
       goto fail;
    }
    ao2_unlock(lock1);
    if (ao2_lock(lock2)) {
       ast_test_status_update(test, "ao2_lock on lock2 failed\n");
       goto fail;
    }
    ao2_unlock(lock2);
    duration = ast_tvdiff_ms(ast_tvnow(), start_time);
    ast_test_validate_cleanup(test, duration > 1500 && duration < 3500, res, fail);
    res = AST_TEST_PASS;
 fail:
    ast_named_lock_put(lock1);
    ast_named_lock_put(lock2);
    pthread_join(thread1, NULL);
    pthread_join(thread2, NULL);
    return res;
 }
load_module()
static int load_module (void) static
Definition at line 145 of file test_named_lock.c.
References AST_MODULE_LOAD_SUCCESS, and AST_TEST_REGISTER.
 {
    AST_TEST_REGISTER(named_lock_test);
    return AST_MODULE_LOAD_SUCCESS;
 }
lock_thread()
static void* lock_thread (void * data) static
Definition at line 41 of file test_named_lock.c.
References ao2_lock, ao2_unlock, ast_named_lock_get, ast_named_lock_put, AST_NAMED_LOCK_TYPE_MUTEX, lock, and NULL.
Referenced by AST_TEST_DEFINE().
 {
    struct ast_named_lock *lock = ast_named_lock_get(AST_NAMED_LOCK_TYPE_MUTEX, "lock_test", data);
    if (!lock) {
       return NULL;
    }
    ao2_lock(lock);
    usleep(3000000);
    ao2_unlock(lock);
    ast_named_lock_put(lock);
    return NULL;
 }
unload_module()
static int unload_module (void) static
Definition at line 139 of file test_named_lock.c.
References AST_TEST_UNREGISTER.
 {
    AST_TEST_UNREGISTER(named_lock_test);
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Named Lock test module" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, } static
Definition at line 151 of file test_named_lock.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 151 of file test_named_lock.c.