Asterisk - The Open Source Telephony Project: test.c File Reference
test.c File Reference
Unit Test Framework.
#include "asterisk.h"
#include "asterisk/_private.h"
#include "asterisk/test.h"
#include "asterisk/logger.h"
#include "asterisk/linkedlists.h"
#include "asterisk/utils.h"
#include "asterisk/cli.h"
#include "asterisk/term.h"
#include "asterisk/ast_version.h"
#include "asterisk/paths.h"
#include "asterisk/time.h"
#include "asterisk/stasis.h"
#include "asterisk/json.h"
#include "asterisk/astobj2.h"
Data Structures
struct ast_test
struct ast_test_execute_results
struct ast_test_suite_message_payload
A wrapper object that can be ao2 ref counted around an ast_json blob.
struct tests
Macros
#define FORMAT "%-25.25s %-30.30s %-40.40s %-13.13s\n"
#define FORMAT_RES_ALL1 "%s%s %-30.30s %-25.25s %-10.10s\n"
#define FORMAT_RES_ALL2 "%s%s %-30.30s %-25.25s %s%ums\n"
Enumerations
enum test_mode { TEST_ALL = 0, TEST_CATEGORY = 1, TEST_NAME_CATEGORY = 2 }
Functions
int __ast_test_status_update (const char *file, const char *func, int line, struct ast_test *test, const char *fmt,...)
void __ast_test_suite_event_notify (const char *file, const char *func, int line, const char *state, const char *fmt,...)
void ast_test_debug (struct ast_test *test, const char *fmt,...)
AST_TEST_DEFINE (test_registrations)
int ast_test_init (void)
int ast_test_register (ast_test_cb_t *cb)
int ast_test_register_cleanup (const char *category, ast_test_cleanup_cb_t *cb)
int ast_test_register_init (const char *category, ast_test_init_cb_t *cb)
void ast_test_set_result (struct ast_test *test, enum ast_test_result_state state)
struct ast_json * ast_test_suite_get_blob (struct ast_test_suite_message_payload *payload)
struct stasis_topic * ast_test_suite_topic (void)
int ast_test_unregister (ast_test_cb_t *cb)
static char * complete_test_category (const char *word)
static char * complete_test_name (const char *word, const char *category)
static int is_reserved_word (const char *word)
STASIS_MESSAGE_TYPE_DEFN (ast_test_suite_message_type,.to_ami=test_suite_event_to_ami)
The message type for test suite messages.
static struct ast_test * test_alloc (ast_test_cb_t *cb)
static int test_cat_cmp (const char *cat1, const char *cat2)
compares two test categories to determine if cat1 resides in cat2
static void test_cleanup (void)
static char * test_cli_execute_registered (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static char * test_cli_generate_results (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static char * test_cli_show_registered (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static char * test_cli_show_results (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static void test_execute (struct ast_test *test)
static int test_execute_multiple (const char *name, const char *category, struct ast_cli_args *cli)
static struct ast_test * test_free (struct ast_test *test)
static int test_generate_results (const char *name, const char *category, const char *xml_path, const char *txt_path)
static int test_insert (struct ast_test *test)
static struct ast_test * test_remove (ast_test_cb_t *cb)
static struct ast_manager_event_blob * test_suite_event_to_ami (struct stasis_message *msg)
static void test_suite_message_payload_dtor (void *obj)
static void test_txt_entry (struct ast_test *test, FILE *f)
static void test_xml_entry (struct ast_test *test, FILE *f)
Variables
static struct ast_test_execute_results last_results
static int registration_errors = 0
static char * reserved_words []
static struct ast_cli_entry test_cli []
static const char *const test_result2str []
struct stasis_topic * test_suite_topic
The topic for test suite messages.
static struct tests tests = { .first = NULL, .last = NULL, .lock = { PTHREAD_RECURSIVE_MUTEX_INITIALIZER_NP , NULL, {1, 0} } , }
Detailed Description
Unit Test Framework.
Author
David Vossel dvoss.nosp@m.el@d.nosp@m.igium.nosp@m..com
Russell Bryant russe.nosp@m.ll@d.nosp@m.igium.nosp@m..com
Definition in file test.c.
Macro Definition Documentation
FORMAT
#define FORMAT "%-25.25s %-30.30s %-40.40s %-13.13s\n"
Referenced by test_cli_show_registered().
FORMAT_RES_ALL1
#define FORMAT_RES_ALL1 "%s%s %-30.30s %-25.25s %-10.10s\n"
Referenced by test_cli_show_results().
FORMAT_RES_ALL2
#define FORMAT_RES_ALL2 "%s%s %-30.30s %-25.25s %s%ums\n"
Referenced by test_cli_show_results().
Enumeration Type Documentation
test_mode
enum test_mode
Enumerator
TEST_ALL
TEST_CATEGORY
TEST_NAME_CATEGORY
Definition at line 97 of file test.c.
                {
    TEST_ALL = 0,
    TEST_CATEGORY = 1,
    TEST_NAME_CATEGORY = 2,
 };
Function Documentation
__ast_test_status_update()
int __ast_test_status_update (const char * file, const char * func, int line, struct ast_test * test, const char * fmt, ...)
Definition at line 134 of file test.c.
References ast_cli(), ast_free, ast_str_append(), ast_str_buffer(), ast_str_create, ast_str_set_va(), buf, ast_test::cli, ast_cli_args::fd, NULL, and ast_test::status_str.
 {
    struct ast_str *buf = NULL;
    va_list ap;
    if (!(buf = ast_str_create(128))) {
       return -1;
    }
    va_start(ap, fmt);
    ast_str_set_va(&buf, 0, fmt, ap);
    va_end(ap);
    if (test->cli) {
       ast_cli(test->cli->fd, "[%s:%s:%d]: %s",
             file, func, line, ast_str_buffer(buf));
    }
    ast_str_append(&test->status_str, 0, "[%s:%s:%d]: %s",
          file, func, line, ast_str_buffer(buf));
    ast_free(buf);
    return 0;
 }
__ast_test_suite_event_notify()
void __ast_test_suite_event_notify (const char * file, const char * func, int line, const char * state, const char * fmt, ...)
Definition at line 1145 of file test.c.
References ao2_alloc, ao2_cleanup, ast_free, ast_json_pack(), ast_str_buffer(), ast_str_create, ast_str_set_va(), ast_test_suite_topic(), buf, NULL, RAII_VAR, stasis_message_create(), stasis_publish(), and test_suite_message_payload_dtor().
 {
    RAII_VAR(struct ast_test_suite_message_payload *, payload,
          NULL,
          ao2_cleanup);
    RAII_VAR(struct stasis_message *, msg, NULL, ao2_cleanup);
    RAII_VAR(struct ast_str *, buf, NULL, ast_free);
    va_list ap;
    if (!ast_test_suite_message_type()) {
       return;
    }
    buf = ast_str_create(128);
    if (!buf) {
       return;
    }
    payload = ao2_alloc(sizeof(*payload), test_suite_message_payload_dtor);
    if (!payload) {
       return;
    }
    va_start(ap, fmt);
    ast_str_set_va(&buf, 0, fmt, ap);
    va_end(ap);
    payload->blob = ast_json_pack("{s: s, s: s, s: s, s: s, s: i, s: s}",
               "type", "testevent",
               "state", state,
               "appfile", file,
               "appfunction", func,
               "line", line,
               "data", ast_str_buffer(buf));
    if (!payload->blob) {
       return;
    }
    msg = stasis_message_create(ast_test_suite_message_type(), payload);
    if (!msg) {
       return;
    }
    stasis_publish(ast_test_suite_topic(), msg);
 }
ast_test_debug()
void ast_test_debug (struct ast_test * test, const char * fmt, ...)
Definition at line 113 of file test.c.
References ast_cli(), ast_free, ast_str_buffer(), ast_str_create, ast_str_set_va(), buf, ast_test::cli, ast_cli_args::fd, and NULL.
Referenced by astobj2_test_1_helper(), test_traversal_sorted(), and verify_mock_cdr_record().
 {
    struct ast_str *buf = NULL;
    va_list ap;
    buf = ast_str_create(128);
    if (!buf) {
       return;
    }
    va_start(ap, fmt);
    ast_str_set_va(&buf, 0, fmt, ap);
    va_end(ap);
    if (test->cli) {
       ast_cli(test->cli->fd, "%s", ast_str_buffer(buf));
    }
    ast_free(buf);
 }
AST_TEST_DEFINE()
AST_TEST_DEFINE (test_registrations)
Definition at line 1188 of file test.c.
References AST_TEST_FAIL, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_test_status_update, ast_test_info::category, ast_test_info::description, ast_test::info, ast_test_info::name, registration_errors, ast_test_info::summary, TEST_EXECUTE, and TEST_INIT.
 {
    switch (cmd) {
    case TEST_INIT:
       info->name = "registrations";
       info->category = "/main/test/";
       info->summary = "Validate Test Registration Data.";
       info->description = "Validate Test Registration Data.";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    if (registration_errors) {
       ast_test_status_update(test,
          "%d test registration error%s occurred.  See startup logs for details.\n",
          registration_errors, registration_errors > 1 ? "s" : "");
       return AST_TEST_FAIL;
    }
    return AST_TEST_PASS;
 }
ast_test_init()
int ast_test_init (void)
Provided by test.c
Definition at line 1221 of file test.c.
References ARRAY_LEN, ast_cli_register_multiple, ast_register_cleanup(), AST_TEST_REGISTER, STASIS_MESSAGE_TYPE_INIT, stasis_topic_create(), and test_cleanup().
Referenced by asterisk_daemon().
 {
 #ifdef TEST_FRAMEWORK
    ast_register_cleanup(test_cleanup);
    /* Create stasis topic */
    test_suite_topic = stasis_topic_create("testsuite:all");
    if (!test_suite_topic) {
       return -1;
    }
    if (STASIS_MESSAGE_TYPE_INIT(ast_test_suite_message_type) != 0) {
       return -1;
    }
    AST_TEST_REGISTER(test_registrations);
    /* Register cli commands */
    ast_cli_register_multiple(test_cli, ARRAY_LEN(test_cli));
 #endif
    return 0;
 }
ast_test_register()
int ast_test_register (ast_test_cb_t * cb)
Definition at line 194 of file test.c.
References ast_log, LOG_ERROR, registration_errors, test, test_alloc(), test_free(), and test_insert().
Referenced by load_module().
 {
    struct ast_test *test;
    if (!cb) {
       ast_log(LOG_ERROR, "Attempted to register test without all required information\n");
       registration_errors++;
       return -1;
    }
    if (!(test = test_alloc(cb))) {
       registration_errors++;
       return -1;
    }
    if (test_insert(test)) {
       test_free(test);
       registration_errors++;
       return -1;
    }
    return 0;
 }
ast_test_register_cleanup()
int ast_test_register_cleanup (const char * category, ast_test_cleanup_cb_t * cb)
Definition at line 177 of file test.c.
References AST_LIST_LOCK, AST_LIST_TRAVERSE, AST_LIST_UNLOCK, ast_test_info::category, ast_test::cb, ast_test::cleanup_cb, ast_test::info, test, and test_cat_cmp().
Referenced by load_module().
 {
    struct ast_test *test;
    int registered = 1;
    AST_LIST_LOCK(&tests);
    AST_LIST_TRAVERSE(&tests, test, entry) {
       if (!(test_cat_cmp(test->info.category, category))) {
          test->cleanup_cb = cb;
          registered = 0;
       }
    }
    AST_LIST_UNLOCK(&tests);
    return registered;
 }
ast_test_register_init()
int ast_test_register_init (const char * category, ast_test_init_cb_t * cb)
Definition at line 160 of file test.c.
References AST_LIST_LOCK, AST_LIST_TRAVERSE, AST_LIST_UNLOCK, ast_test_info::category, ast_test::cb, ast_test::info, ast_test::init_cb, test, and test_cat_cmp().
Referenced by load_module().
 {
    struct ast_test *test;
    int registered = 1;
    AST_LIST_LOCK(&tests);
    AST_LIST_TRAVERSE(&tests, test, entry) {
       if (!(test_cat_cmp(test->info.category, category))) {
          test->init_cb = cb;
          registered = 0;
       }
    }
    AST_LIST_UNLOCK(&tests);
    return registered;
 }
ast_test_set_result()
void ast_test_set_result (struct ast_test * test, enum ast_test_result_state state)
Definition at line 262 of file test.c.
References AST_TEST_FAIL, AST_TEST_NOT_RUN, and ast_test::state.
Referenced by AST_TEST_DEFINE(), handler_wait_for_message(), user_event_wait_for_events(), and verify_bad_headers().
 {
    if (test->state == AST_TEST_FAIL || state == AST_TEST_NOT_RUN) {
       return;
    }
    test->state = state;
 }
ast_test_suite_get_blob()
struct ast_json* ast_test_suite_get_blob (struct ast_test_suite_message_payload * payload)
Definition at line 1095 of file test.c.
References ast_test_suite_message_payload::blob.
Referenced by test_suite_event_to_ami().
 {
    return payload->blob;
 }
ast_test_suite_topic()
struct stasis_topic* ast_test_suite_topic (void)
Definition at line 1069 of file test.c.
References test_suite_topic.
Referenced by __ast_test_suite_event_notify(), and __init_manager().
 {
    return test_suite_topic;
 }
ast_test_unregister()
int ast_test_unregister (ast_test_cb_t * cb)
Definition at line 218 of file test.c.
References test, test_free(), and test_remove().
Referenced by unload_module().
 {
    struct ast_test *test;
    if (!(test = test_remove(cb))) {
       return -1; /* not found */
    }
    test_free(test);
    return 0;
 }
complete_test_category()
static char* complete_test_category (const char * word) static
Definition at line 755 of file test.c.
References ast_cli_completion_add(), AST_LIST_LOCK, AST_LIST_TRAVERSE, AST_LIST_UNLOCK, ast_strdup, ast_test_info::category, ast_test::info, NULL, and test.
Referenced by test_cli_execute_registered(), and test_cli_show_registered().
 {
    int wordlen = strlen(word);
    struct ast_test *test;
    AST_LIST_LOCK(&tests);
    AST_LIST_TRAVERSE(&tests, test, entry) {
       if (!strncasecmp(word, test->info.category, wordlen)) {
          if (ast_cli_completion_add(ast_strdup(test->info.category))) {
             break;
          }
       }
    }
    AST_LIST_UNLOCK(&tests);
    return NULL;
 }
complete_test_name()
static char* complete_test_name (const char * word, const char * category) static
Definition at line 773 of file test.c.
References ast_cli_completion_add(), AST_LIST_LOCK, AST_LIST_TRAVERSE, AST_LIST_UNLOCK, ast_strdup, ast_test_info::category, ast_test::info, ast_test_info::name, NULL, test, and test_cat_cmp().
Referenced by test_cli_execute_registered(), and test_cli_show_registered().
 {
    int wordlen = strlen(word);
    struct ast_test *test;
    AST_LIST_LOCK(&tests);
    AST_LIST_TRAVERSE(&tests, test, entry) {
       if (!test_cat_cmp(test->info.category, category) && !strncasecmp(word, test->info.name, wordlen)) {
          if (ast_cli_completion_add(ast_strdup(test->info.name))) {
             break;
          }
       }
    }
    AST_LIST_UNLOCK(&tests);
    return NULL;
 }
is_reserved_word()
static int is_reserved_word (const char * word) static
Definition at line 287 of file test.c.
References ARRAY_LEN, and reserved_words.
Referenced by test_xml_entry().
 {
    int i;
    for (i = 0; i < ARRAY_LEN(reserved_words); i++) {
       if (strcmp(word, reserved_words[i]) == 0) {
          return 1;
       }
    }
    return 0;
 }
STASIS_MESSAGE_TYPE_DEFN()
STASIS_MESSAGE_TYPE_DEFN (ast_test_suite_message_type , . to_ami = test_suite_event_to_ami)
The message type for test suite messages.
Since
12
Referenced by test_suite_event_to_ami().
test_alloc()
static struct ast_test * test_alloc (ast_test_cb_t * cb) static
Definition at line 681 of file test.c.
References ast_calloc, ast_log, ast_str_create, ast_strlen_zero, ast_test_info::category, ast_test::cb, ast_test_info::description, ast_test::info, LOG_ERROR, LOG_WARNING, ast_test_info::name, NULL, registration_errors, ast_test::status_str, ast_test_info::summary, test, test_free(), and TEST_INIT.
Referenced by ast_test_register().
 {
    struct ast_test *test;
    test = ast_calloc(1, sizeof(*test));
    if (!test) {
       ast_log(LOG_ERROR, "Failed to allocate test, registration failed.\n");
       return NULL;
    }
    test->cb = cb;
    test->cb(&test->info, TEST_INIT, test);
    if (ast_strlen_zero(test->info.name)) {
       ast_log(LOG_ERROR, "Test has no name, test registration refused.\n");
       return test_free(test);
    }
    if (ast_strlen_zero(test->info.category)) {
       ast_log(LOG_ERROR, "Test %s has no category, test registration refused.\n",
          test->info.name);
       return test_free(test);
    }
    if (test->info.category[0] != '/' || test->info.category[strlen(test->info.category) - 1] != '/') {
       ast_log(LOG_WARNING, "Test category '%s' for test '%s' is missing a leading or trailing slash.\n",
          test->info.category, test->info.name);
       /*
        * Flag an error anyways so test_registrations fails but allow the
        * test to be registered.
        */
       ++registration_errors;
    }
    if (ast_strlen_zero(test->info.summary)) {
       ast_log(LOG_ERROR, "Test %s%s has no summary, test registration refused.\n",
          test->info.category, test->info.name);
       return test_free(test);
    }
    if (test->info.summary[strlen(test->info.summary) - 1] == '\n') {
       ast_log(LOG_WARNING, "Test %s%s summary has a trailing newline.\n",
          test->info.category, test->info.name);
       /*
        * Flag an error anyways so test_registrations fails but allow the
        * test to be registered.
        */
       ++registration_errors;
    }
    if (ast_strlen_zero(test->info.description)) {
       ast_log(LOG_ERROR, "Test %s%s has no description, test registration refused.\n",
          test->info.category, test->info.name);
       return test_free(test);
    }
    if (test->info.description[strlen(test->info.description) - 1] == '\n') {
       ast_log(LOG_WARNING, "Test %s%s description has a trailing newline.\n",
          test->info.category, test->info.name);
       /*
        * Flag an error anyways so test_registrations fails but allow the
        * test to be registered.
        */
       ++registration_errors;
    }
    if (!(test->status_str = ast_str_create(128))) {
       ast_log(LOG_ERROR, "Failed to allocate status_str for %s%s, test registration failed.\n",
          test->info.category, test->info.name);
       return test_free(test);
    }
    return test;
 }
test_cat_cmp()
static int test_cat_cmp (const char * cat1, const char * cat2) static
compares two test categories to determine if cat1 resides in cat2
Definition at line 642 of file test.c.
Referenced by ast_test_register_cleanup(), ast_test_register_init(), complete_test_name(), test_cli_show_registered(), test_execute_multiple(), and test_generate_results().
 {
    int len1 = 0;
    int len2 = 0;
    if (!cat1 || !cat2) {
       return -1;
    }
    len1 = strlen(cat1);
    len2 = strlen(cat2);
    if (len2 > len1) {
       return -1;
    }
    return strncmp(cat1, cat2, len2) ? 1 : 0;
 }
test_cleanup()
static void test_cleanup (void) static
Definition at line 1211 of file test.c.
References ao2_cleanup, ARRAY_LEN, ast_cli_unregister_multiple(), AST_TEST_UNREGISTER, NULL, and STASIS_MESSAGE_TYPE_CLEANUP.
Referenced by AST_TEST_DEFINE(), ast_test_init(), test_performance(), test_traversal_nonsorted(), and test_traversal_sorted().
 {
    AST_TEST_UNREGISTER(test_registrations);
    ast_cli_unregister_multiple(test_cli, ARRAY_LEN(test_cli));
    ao2_cleanup(test_suite_topic);
    test_suite_topic = NULL;
    STASIS_MESSAGE_TYPE_CLEANUP(ast_test_suite_message_type);
 }
test_cli_execute_registered()
static char* test_cli_execute_registered (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) static
Definition at line 854 of file test.c.
References ast_cli_args::argc, ast_cli_args::argv, ast_cli(), ast_cli_complete(), AST_LIST_LOCK, AST_LIST_UNLOCK, CLI_GENERATE, CLI_HANDLER, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::command, complete_test_category(), complete_test_name(), ast_cli_args::fd, ast_test_execute_results::last_failed, ast_test_execute_results::last_passed, last_results, NULL, ast_cli_args::pos, test_execute_multiple(), ast_cli_entry::usage, and ast_cli_args::word.
 {
    static const char * const option1[] = { "all", "category", NULL };
    static const char * const option2[] = { "name", NULL };
    switch (cmd) {
    case CLI_INIT:
       e->command = "test execute";
       e->usage =
          "Usage: test execute can be used in three ways.\n"
          "       1. 'test execute all' runs all registered tests\n"
          "       2. 'test execute category [test category]' runs all tests in the given\n"
          "          category.\n"
          "       3. 'test execute category [test category] name [test name]' runs all\n"
          "           tests in a given category matching a given name\n";
       return NULL;
    case CLI_GENERATE:
       if (a->pos == 2) {
          return ast_cli_complete(a->word, option1, -1);
       }
       if (a->pos == 3 && !strcasecmp(a->argv[2], "category")) {
          return complete_test_category(a->word);
       }
       if (a->pos == 4) {
          return ast_cli_complete(a->word, option2, -1);
       }
       if (a->pos == 5) {
          return complete_test_name(a->word, a->argv[3]);
       }
       return NULL;
    case CLI_HANDLER:
       if (a->argc < 3|| a->argc > 6) {
          return CLI_SHOWUSAGE;
       }
       if ((a->argc == 3) && !strcasecmp(a->argv[2], "all")) { /* run all registered tests */
          ast_cli(a->fd, "Running all available tests...\n\n");
          test_execute_multiple(NULL, NULL, a);
       } else if (a->argc == 4) { /* run only tests within a category */
          ast_cli(a->fd, "Running all available tests matching category %s\n\n", a->argv[3]);
          test_execute_multiple(NULL, a->argv[3], a);
       } else if (a->argc == 6) { /* run only a single test matching the category and name */
          ast_cli(a->fd, "Running all available tests matching category %s and name %s\n\n", a->argv[3], a->argv[5]);
          test_execute_multiple(a->argv[5], a->argv[3], a);
       } else {
          return CLI_SHOWUSAGE;
       }
       AST_LIST_LOCK(&tests);
       if (!(last_results.last_passed + last_results.last_failed)) {
          ast_cli(a->fd, "--- No Tests Found! ---\n");
       }
       ast_cli(a->fd, "\n%u Test(s) Executed  %u Passed  %u Failed\n",
          (last_results.last_passed + last_results.last_failed),
          last_results.last_passed,
          last_results.last_failed);
       AST_LIST_UNLOCK(&tests);
    default:
       return NULL;
    }
    return CLI_SUCCESS;
 }
test_cli_generate_results()
static char* test_cli_generate_results (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) static
Definition at line 990 of file test.c.
References ast_cli_args::argc, ast_cli_args::argv, ast_cli(), ast_cli_complete(), ast_config_AST_LOG_DIR, ast_free, ast_str_buffer(), ast_str_create, ast_str_set(), ast_tvnow(), buf, CLI_GENERATE, CLI_HANDLER, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::command, ast_cli_args::fd, make_ari_stubs::file, NULL, ast_cli_args::pos, S_OR, test_generate_results(), type, ast_cli_entry::usage, and ast_cli_args::word.
 {
    static const char * const option[] = { "xml", "txt", NULL };
    const char *file = NULL;
    const char *type = "";
    int isxml = 0;
    int res = 0;
    struct ast_str *buf = NULL;
    struct timeval time = ast_tvnow();
    switch (cmd) {
    case CLI_INIT:
       e->command = "test generate results";
       e->usage =
          "Usage: 'test generate results'\n"
          "       Generates test results in either xml or txt format. An optional \n"
          "       file path may be provided to specify the location of the xml or\n"
          "       txt file\n"
          "       \nExample usage:\n"
          "       'test generate results xml' this writes to a default file\n"
          "       'test generate results xml /path/to/file.xml' writes to specified file\n";
       return NULL;
    case CLI_GENERATE:
       if (a->pos == 3) {
          return ast_cli_complete(a->word, option, -1);
       }
       return NULL;
    case CLI_HANDLER:
       /* verify input */
       if (a->argc < 4 || a->argc > 5) {
          return CLI_SHOWUSAGE;
       } else if (!strcasecmp(a->argv[3], "xml")) {
          type = "xml";
          isxml = 1;
       } else if (!strcasecmp(a->argv[3], "txt")) {
          type = "txt";
       } else {
          return CLI_SHOWUSAGE;
       }
       if (a->argc == 5) {
          file = a->argv[4];
       } else {
          if (!(buf = ast_str_create(256))) {
             return NULL;
          }
          ast_str_set(&buf, 0, "%s/asterisk_test_results-%ld.%s", ast_config_AST_LOG_DIR, (long) time.tv_sec, type);
          file = ast_str_buffer(buf);
       }
       if (isxml) {
          res = test_generate_results(NULL, NULL, file, NULL);
       } else {
          res = test_generate_results(NULL, NULL, NULL, file);
       }
       if (!res) {
          ast_cli(a->fd, "Results Generated Successfully: %s\n", S_OR(file, ""));
       } else {
          ast_cli(a->fd, "Results Could Not Be Generated: %s\n", S_OR(file, ""));
       }
       ast_free(buf);
    default:
       return NULL;
    }
    return CLI_SUCCESS;
 }
test_cli_show_registered()
static char* test_cli_show_registered (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) static
Definition at line 792 of file test.c.
References ast_cli_args::argc, ast_cli_args::argv, ast_cli(), ast_cli_complete(), AST_LIST_LOCK, AST_LIST_TRAVERSE, AST_LIST_UNLOCK, ast_test_info::category, CLI_GENERATE, CLI_HANDLER, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::command, complete_test_category(), complete_test_name(), ast_cli_args::fd, FORMAT, ast_test::info, ast_test_info::name, NULL, ast_cli_args::pos, ast_test::state, ast_test_info::summary, test_cat_cmp(), test_result2str, ast_cli_entry::usage, and ast_cli_args::word.
 {
 #define FORMAT "%-25.25s %-30.30s %-40.40s %-13.13s\n"
    static const char * const option1[] = { "all", "category", NULL };
    static const char * const option2[] = { "name", NULL };
    struct ast_test *test = NULL;
    int count = 0;
    switch (cmd) {
    case CLI_INIT:
       e->command = "test show registered";
       e->usage =
          "Usage: 'test show registered' can be used in three ways.\n"
          "       1. 'test show registered all' shows all registered tests\n"
          "       2. 'test show registered category [test category]' shows all tests in the given\n"
          "          category.\n"
          "       3. 'test show registered category [test category] name [test name]' shows all\n"
          "           tests in a given category matching a given name\n";
       return NULL;
    case CLI_GENERATE:
       if (a->pos == 3) {
          return ast_cli_complete(a->word, option1, -1);
       }
       if (a->pos == 4 && !strcasecmp(a->argv[3], "category")) {
          return complete_test_category(a->word);
       }
       if (a->pos == 5) {
          return ast_cli_complete(a->word, option2, -1);
       }
       if (a->pos == 6) {
          return complete_test_name(a->word, a->argv[4]);
       }
       return NULL;
    case CLI_HANDLER:
       if ((a->argc < 4) || (a->argc == 6) || (a->argc > 7) ||
          ((a->argc == 4) && strcasecmp(a->argv[3], "all")) ||
          ((a->argc == 7) && strcasecmp(a->argv[5], "name"))) {
          return CLI_SHOWUSAGE;
       }
       ast_cli(a->fd, FORMAT, "Category", "Name", "Summary", "Test Result");
       ast_cli(a->fd, FORMAT, "--------", "----", "-------", "-----------");
       AST_LIST_LOCK(&tests);
       AST_LIST_TRAVERSE(&tests, test, entry) {
          if ((a->argc == 4) ||
              ((a->argc == 5) && !test_cat_cmp(test->info.category, a->argv[4])) ||
              ((a->argc == 7) && !strcmp(test->info.category, a->argv[4]) && !strcmp(test->info.name, a->argv[6]))) {
             ast_cli(a->fd, FORMAT, test->info.category, test->info.name,
                   test->info.summary, test_result2str[test->state]);
             count++;
          }
       }
       AST_LIST_UNLOCK(&tests);
       ast_cli(a->fd, FORMAT, "--------", "----", "-------", "-----------");
       ast_cli(a->fd, "\n%d Registered Tests Matched\n", count);
    default:
       return NULL;
    }
    return CLI_SUCCESS;
 }
test_cli_show_results()
static char* test_cli_show_results (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) static
Definition at line 919 of file test.c.
References ast_cli_args::argc, ast_cli_args::argv, ast_cli(), ast_cli_complete(), AST_LIST_LOCK, AST_LIST_TRAVERSE, AST_LIST_UNLOCK, AST_TEST_FAIL, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_test_info::category, CLI_GENERATE, CLI_HANDLER, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, COLOR_GREEN, COLOR_RED, ast_cli_entry::command, ast_cli_args::fd, FORMAT_RES_ALL1, FORMAT_RES_ALL2, ast_test::info, ast_test_info::name, NULL, ast_cli_args::pos, result_buf, ast_test::state, term_color(), test_result2str, ast_test::time, ast_cli_entry::usage, and ast_cli_args::word.
 {
 #define FORMAT_RES_ALL1 "%s%s %-30.30s %-25.25s %-10.10s\n"
 #define FORMAT_RES_ALL2 "%s%s %-30.30s %-25.25s %s%ums\n"
    static const char * const option1[] = { "all", "failed", "passed", NULL };
    char result_buf[32] = { 0 };
    struct ast_test *test = NULL;
    int failed = 0;
    int passed = 0;
    int mode;  /* 0 for show all, 1 for show fail, 2 for show passed */
    switch (cmd) {
    case CLI_INIT:
       e->command = "test show results";
       e->usage =
          "Usage: test show results can be used in three ways\n"
          "       1. 'test show results all' Displays results for all executed tests.\n"
          "       2. 'test show results passed' Displays results for all passed tests.\n"
          "       3. 'test show results failed' Displays results for all failed tests.\n";
       return NULL;
    case CLI_GENERATE:
       if (a->pos == 3) {
          return ast_cli_complete(a->word, option1, -1);
       }
       return NULL;
    case CLI_HANDLER:
       /* verify input */
       if (a->argc != 4) {
          return CLI_SHOWUSAGE;
       } else if (!strcasecmp(a->argv[3], "passed")) {
          mode = 2;
       } else if (!strcasecmp(a->argv[3], "failed")) {
          mode = 1;
       } else if (!strcasecmp(a->argv[3], "all")) {
          mode = 0;
       } else {
          return CLI_SHOWUSAGE;
       }
       ast_cli(a->fd, FORMAT_RES_ALL1, "Result", "", "Name", "Category", "Time");
       AST_LIST_LOCK(&tests);
       AST_LIST_TRAVERSE(&tests, test, entry) {
          if (test->state == AST_TEST_NOT_RUN) {
             continue;
          }
          test->state == AST_TEST_FAIL ? failed++ : passed++;
          if (!mode || ((mode == 1) && (test->state == AST_TEST_FAIL)) || ((mode == 2) && (test->state == AST_TEST_PASS))) {
             /* give our results pretty colors */
             term_color(result_buf, test_result2str[test->state],
                (test->state == AST_TEST_FAIL) ? COLOR_RED : COLOR_GREEN,
                0, sizeof(result_buf));
             ast_cli(a->fd, FORMAT_RES_ALL2,
                result_buf,
                "  ",
                test->info.name,
                test->info.category,
                test->time ? " " : "<",
                test->time ? test->time : 1);
          }
       }
       AST_LIST_UNLOCK(&tests);
       ast_cli(a->fd, "%d Test(s) Executed  %d Passed  %d Failed\n", (failed + passed), passed, failed);
    default:
       return NULL;
    }
    return CLI_SUCCESS;
 }
test_execute()
static void test_execute (struct ast_test * test) static
Definition at line 238 of file test.c.
References ast_str_reset(), AST_TEST_FAIL, AST_TEST_NOT_RUN, ast_tvdiff_ms(), ast_tvnow(), ast_test::cb, ast_test::cleanup_cb, ast_test::info, ast_test::init_cb, result, ast_test::state, ast_test::status_str, TEST_EXECUTE, and ast_test::time.
Referenced by test_execute_multiple().
 {
    struct timeval begin;
    enum ast_test_result_state result;
    ast_str_reset(test->status_str);
    begin = ast_tvnow();
    if (test->init_cb && test->init_cb(&test->info, test)) {
       test->state = AST_TEST_FAIL;
       goto exit;
    }
    test->state = AST_TEST_NOT_RUN;
    result = test->cb(&test->info, TEST_EXECUTE, test);
    if (test->state != AST_TEST_FAIL) {
       test->state = result;
    }
    if (test->cleanup_cb && test->cleanup_cb(&test->info, test)) {
       test->state = AST_TEST_FAIL;
    }
 exit:
    test->time = ast_tvdiff_ms(ast_tvnow(), begin);
 }
test_execute_multiple()
static int test_execute_multiple (const char * name, const char * category, struct ast_cli_args * cli) static
Definition at line 382 of file test.c.
References ast_cli(), AST_LIST_LOCK, AST_LIST_TRAVERSE, AST_LIST_UNLOCK, ast_strlen_zero, AST_TEST_FAIL, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_test_info::category, ast_test::cli, COLOR_GREEN, COLOR_RED, execute(), ast_test_info::explicit_only, ast_cli_args::fd, ast_test::info, ast_test_execute_results::last_failed, ast_test_execute_results::last_passed, last_results, ast_test_execute_results::last_time, ast_test_info::name, NULL, result_buf, ast_test::state, term_color(), TEST_ALL, test_cat_cmp(), TEST_CATEGORY, test_execute(), TEST_NAME_CATEGORY, test_result2str, ast_test::time, ast_test_execute_results::total_failed, ast_test_execute_results::total_passed, ast_test_execute_results::total_tests, and ast_test_execute_results::total_time.
Referenced by test_cli_execute_registered().
 {
    char result_buf[32] = { 0 };
    struct ast_test *test = NULL;
    enum test_mode mode = TEST_ALL; /* 3 modes, 0 = run all, 1 = only by category, 2 = only by name and category */
    int execute = 0;
    int res = 0;
    if (!ast_strlen_zero(category)) {
       if (!ast_strlen_zero(name)) {
          mode = TEST_NAME_CATEGORY;
       } else {
          mode = TEST_CATEGORY;
       }
    }
    AST_LIST_LOCK(&tests);
    /* clear previous execution results */
    memset(&last_results, 0, sizeof(last_results));
    AST_LIST_TRAVERSE(&tests, test, entry) {
       execute = 0;
       switch (mode) {
       case TEST_CATEGORY:
          if (!test_cat_cmp(test->info.category, category) && !test->info.explicit_only) {
             execute = 1;
          }
          break;
       case TEST_NAME_CATEGORY:
          if (!(test_cat_cmp(test->info.category, category)) && !(strcmp(test->info.name, name))) {
             execute = 1;
          }
          break;
       case TEST_ALL:
          execute = !test->info.explicit_only;
       }
       if (execute) {
          if (cli) {
             ast_cli(cli->fd, "START  %s - %s \n", test->info.category, test->info.name);
          }
          /* set the test status update argument. it is ok if cli is NULL */
          test->cli = cli;
          /* execute the test and save results */
          test_execute(test);
          test->cli = NULL;
          /* update execution specific counts here */
          last_results.last_time += test->time;
          if (test->state == AST_TEST_PASS) {
             last_results.last_passed++;
          } else if (test->state == AST_TEST_FAIL) {
             last_results.last_failed++;
          }
          if (cli) {
             term_color(result_buf,
                test_result2str[test->state],
                (test->state == AST_TEST_FAIL) ? COLOR_RED : COLOR_GREEN,
                0,
                sizeof(result_buf));
             ast_cli(cli->fd, "END    %s - %s Time: %s%ums Result: %s\n",
                test->info.category,
                test->info.name,
                test->time ? "" : "<",
                test->time ? test->time : 1,
                result_buf);
          }
       }
       /* update total counts as well during this iteration
        * even if the current test did not execute this time */
       last_results.total_time += test->time;
       last_results.total_tests++;
       if (test->state != AST_TEST_NOT_RUN) {
          if (test->state == AST_TEST_PASS) {
             last_results.total_passed++;
          } else {
             last_results.total_failed++;
          }
       }
    }
    res = last_results.last_passed + last_results.last_failed;
    AST_LIST_UNLOCK(&tests);
    return res;
 }
test_free()
static struct ast_test * test_free (struct ast_test * test) static
Definition at line 665 of file test.c.
References ast_free, NULL, and ast_test::status_str.
Referenced by ast_test_register(), ast_test_unregister(), and test_alloc().
 {
    if (!test) {
       return NULL;
    }
    ast_free(test->status_str);
    ast_free(test);
    return NULL;
 }
test_generate_results()
static int test_generate_results (const char * name, const char * category, const char * xml_path, const char * txt_path) static
Definition at line 492 of file test.c.
References ast_get_version(), ast_get_version_num(), AST_LIST_LOCK, AST_LIST_TRAVERSE, AST_LIST_UNLOCK, ast_log, ast_strlen_zero, ast_test_info::category, done, ast_test::info, last_results, LOG_WARNING, ast_test_info::name, NULL, TEST_ALL, test_cat_cmp(), TEST_CATEGORY, TEST_NAME_CATEGORY, test_txt_entry(), test_xml_entry(), ast_test_execute_results::total_failed, ast_test_execute_results::total_passed, ast_test_execute_results::total_tests, and ast_test_execute_results::total_time.
Referenced by test_cli_generate_results().
 {
    enum test_mode mode = TEST_ALL;  /* 0 generate all, 1 generate by category only, 2 generate by name and category */
    FILE *f_xml = NULL, *f_txt = NULL;
    int res = 0;
    struct ast_test *test = NULL;
    /* verify at least one output file was given */
    if (ast_strlen_zero(xml_path) && ast_strlen_zero(txt_path)) {
       return -1;
    }
    /* define what mode is to be used */
    if (!ast_strlen_zero(category)) {
       if (!ast_strlen_zero(name)) {
          mode = TEST_NAME_CATEGORY;
       } else {
          mode = TEST_CATEGORY;
       }
    }
    /* open files for writing */
    if (!ast_strlen_zero(xml_path)) {
       if (!(f_xml = fopen(xml_path, "w"))) {
          ast_log(LOG_WARNING, "Could not open file %s for xml test results\n", xml_path);
          res = -1;
          goto done;
       }
    }
    if (!ast_strlen_zero(txt_path)) {
       if (!(f_txt = fopen(txt_path, "w"))) {
          ast_log(LOG_WARNING, "Could not open file %s for text output of test results\n", txt_path);
          res = -1;
          goto done;
       }
    }
    AST_LIST_LOCK(&tests);
    /* xml header information */
    if (f_xml) {
       /*
        * http://confluence.atlassian.com/display/BAMBOO/JUnit+parsing+in+Bamboo
        */
       fprintf(f_xml, "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n");
       fprintf(f_xml, "<testsuites>\n");
       fprintf(f_xml, "\t<testsuite errors=\"0\" time=\"%u.%u\" tests=\"%u\" "
             "name=\"AsteriskUnitTests\">\n",
             last_results.total_time / 1000, last_results.total_time % 1000,
             last_results.total_tests);
       fprintf(f_xml, "\t\t<properties>\n");
       fprintf(f_xml, "\t\t\t<property name=\"version\" value=\"%s\"/>\n", ast_get_version());
       fprintf(f_xml, "\t\t</properties>\n");
    }
    /* txt header information */
    if (f_txt) {
       fprintf(f_txt, "Asterisk Version:         %s\n", ast_get_version());
       fprintf(f_txt, "Asterisk Version Number:  %s\n", ast_get_version_num());
       fprintf(f_txt, "Number of Tests:          %u\n", last_results.total_tests);
       fprintf(f_txt, "Number of Tests Executed: %u\n", (last_results.total_passed + last_results.total_failed));
       fprintf(f_txt, "Passed Tests:             %u\n", last_results.total_passed);
       fprintf(f_txt, "Failed Tests:             %u\n", last_results.total_failed);
       fprintf(f_txt, "Total Execution Time:     %u\n", last_results.total_time);
    }
    /* export each individual test */
    AST_LIST_TRAVERSE(&tests, test, entry) {
       switch (mode) {
       case TEST_CATEGORY:
          if (!test_cat_cmp(test->info.category, category)) {
             test_xml_entry(test, f_xml);
             test_txt_entry(test, f_txt);
          }
          break;
       case TEST_NAME_CATEGORY:
          if (!(strcmp(test->info.category, category)) && !(strcmp(test->info.name, name))) {
             test_xml_entry(test, f_xml);
             test_txt_entry(test, f_txt);
          }
          break;
       case TEST_ALL:
          test_xml_entry(test, f_xml);
          test_txt_entry(test, f_txt);
       }
    }
    AST_LIST_UNLOCK(&tests);
 done:
    if (f_xml) {
       fprintf(f_xml, "\t</testsuite>\n");
       fprintf(f_xml, "</testsuites>\n");
       fclose(f_xml);
    }
    if (f_txt) {
       fclose(f_txt);
    }
    return res;
 }
test_insert()
static int test_insert (struct ast_test * test) static
Definition at line 598 of file test.c.
References AST_LIST_INSERT_SORTALPHA, AST_LIST_LOCK, AST_LIST_UNLOCK, ast_test_info::category, and ast_test::info.
Referenced by ast_test_register().
 {
    /* This is a slow operation that may need to be optimized in the future
     * as the test framework expands.  At the moment we are doing string
     * comparisons on every item within the list to insert in sorted order. */
    AST_LIST_LOCK(&tests);
    AST_LIST_INSERT_SORTALPHA(&tests, test, entry, info.category);
    AST_LIST_UNLOCK(&tests);
    return 0;
 }
test_remove()
static struct ast_test * test_remove (ast_test_cb_t * cb) static
Definition at line 617 of file test.c.
References AST_LIST_LOCK, AST_LIST_REMOVE_CURRENT, AST_LIST_TRAVERSE_SAFE_BEGIN, AST_LIST_TRAVERSE_SAFE_END, AST_LIST_UNLOCK, ast_test::cb, and NULL.
Referenced by ast_test_unregister().
 {
    struct ast_test *cur = NULL;
    AST_LIST_LOCK(&tests);
    AST_LIST_TRAVERSE_SAFE_BEGIN(&tests, cur, entry) {
       if (cur->cb == cb) {
          AST_LIST_REMOVE_CURRENT(entry);
          break;
       }
    }
    AST_LIST_TRAVERSE_SAFE_END;
    AST_LIST_UNLOCK(&tests);
    return cur;
 }
test_suite_event_to_ami()
static struct ast_manager_event_blob* test_suite_event_to_ami (struct stasis_message * msg) static
Definition at line 1100 of file test.c.
References ast_free, ast_json_integer_get(), ast_json_object_get(), ast_json_string_get(), ast_manager_event_blob_create(), ast_str_append(), ast_str_buffer(), ast_str_create, ast_strlen_zero, ast_test_suite_get_blob(), EVENT_FLAG_REPORTING, NULL, RAII_VAR, stasis_message_data(), STASIS_MESSAGE_TYPE_DEFN(), to_ami(), and type.
 {
    RAII_VAR(struct ast_str *, packet_string, ast_str_create(128), ast_free);
    struct ast_test_suite_message_payload *payload;
    struct ast_json *blob;
    const char *type;
    payload = stasis_message_data(msg);
    if (!payload) {
       return NULL;
    }
    blob = ast_test_suite_get_blob(payload);
    if (!blob) {
       return NULL;
    }
    type = ast_json_string_get(ast_json_object_get(blob, "type"));
    if (ast_strlen_zero(type) || strcmp("testevent", type)) {
       return NULL;
    }
    ast_str_append(&packet_string, 0, "Type: StateChange\r\n");
    ast_str_append(&packet_string, 0, "State: %s\r\n",
       ast_json_string_get(ast_json_object_get(blob, "state")));
    ast_str_append(&packet_string, 0, "AppFile: %s\r\n",
       ast_json_string_get(ast_json_object_get(blob, "appfile")));
    ast_str_append(&packet_string, 0, "AppFunction: %s\r\n",
       ast_json_string_get(ast_json_object_get(blob, "appfunction")));
    ast_str_append(&packet_string, 0, "AppLine: %jd\r\n",
       ast_json_integer_get(ast_json_object_get(blob, "line")));
    ast_str_append(&packet_string, 0, "%s\r\n",
       ast_json_string_get(ast_json_object_get(blob, "data")));
    return ast_manager_event_blob_create(EVENT_FLAG_REPORTING,
       "TestEvent",
       "%s",
       ast_str_buffer(packet_string));
 }
test_suite_message_payload_dtor()
static void test_suite_message_payload_dtor (void * obj) static
Definition at line 1086 of file test.c.
References ast_json_unref(), and ast_test_suite_message_payload::blob.
Referenced by __ast_test_suite_event_notify().
 {
    struct ast_test_suite_message_payload *payload = obj;
    if (payload->blob) {
       ast_json_unref(payload->blob);
    }
 }
test_txt_entry()
static void test_txt_entry (struct ast_test * test, FILE * f) static
Definition at line 348 of file test.c.
References ast_str_buffer(), AST_TEST_FAIL, AST_TEST_NOT_RUN, ast_test_info::category, ast_test_info::description, ast_test::info, ast_test_info::name, S_OR, ast_test::state, ast_test::status_str, ast_test_info::summary, test_result2str, and ast_test::time.
Referenced by test_generate_results().
 {
    if (!f || !test) {
       return;
    }
    fprintf(f, "\nName:              %s\n", test->info.name);
    fprintf(f,   "Category:          %s\n", test->info.category);
    fprintf(f,   "Summary:           %s\n", test->info.summary);
    fprintf(f,   "Description:       %s\n", test->info.description);
    fprintf(f,   "Result:            %s\n", test_result2str[test->state]);
    if (test->state != AST_TEST_NOT_RUN) {
       fprintf(f,   "Time:              %u\n", test->time);
    }
    if (test->state == AST_TEST_FAIL) {
       fprintf(f,   "Error Description: %s\n\n", S_OR(ast_str_buffer(test->status_str), "NA"));
    }
 }
test_xml_entry()
static void test_xml_entry (struct ast_test * test, FILE * f) static
Definition at line 300 of file test.c.
References ast_alloca, ast_free, ast_str_append(), ast_str_buffer(), ast_str_create, ast_strdupa, ast_strsep(), AST_STRSEP_TRIM, AST_TEST_FAIL, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_test_info::category, ast_test::info, is_reserved_word(), ast_test_info::name, prefix, S_OR, ast_test::state, ast_test::status_str, and ast_test::time.
Referenced by test_generate_results().
 {
    /* We need a copy of the category skipping past the initial '/' */
    char *test_cat = ast_strdupa(test->info.category + 1);
    char *next_cat;
    char *test_name = (char *)test->info.name;
    struct ast_str *category = ast_str_create(strlen(test->info.category) + 32);
    if (!category || test->state == AST_TEST_NOT_RUN) {
       ast_free(category);
       return;
    }
    while ((next_cat = ast_strsep(&test_cat, '/', AST_STRSEP_TRIM))) {
       char *prefix = "";
       if (is_reserved_word(next_cat)) {
          prefix = "_";
       }
       ast_str_append(&category, 0, ".%s%s", prefix, next_cat);
    }
    test_cat = ast_str_buffer(category);
    /* Skip past the initial '.' */
    test_cat++;
    if (is_reserved_word(test->info.name)) {
       size_t name_length = strlen(test->info.name) + 2;
       test_name = ast_alloca(name_length);
       snprintf(test_name, name_length, "_%s", test->info.name);
    }
    fprintf(f, "\t\t<testcase time=\"%u.%u\" classname=\"%s\" name=\"%s\"%s>\n",
          test->time / 1000, test->time % 1000,
          test_cat, test_name,
          test->state == AST_TEST_PASS ? "/" : "");
    ast_free(category);
    if (test->state == AST_TEST_FAIL) {
       fprintf(f, "\t\t\t<failure><![CDATA[\n%s\n\t\t]]></failure>\n",
             S_OR(ast_str_buffer(test->status_str), "NA"));
       fprintf(f, "\t\t</testcase>\n");
    }
 }
Variable Documentation
last_results
struct ast_test_execute_results last_results static
Referenced by test_cli_execute_registered(), test_execute_multiple(), and test_generate_results().
registration_errors
int registration_errors = 0 static
Definition at line 111 of file test.c.
Referenced by AST_TEST_DEFINE(), ast_test_register(), and test_alloc().
reserved_words
char* reserved_words[] static
Definition at line 274 of file test.c.
Referenced by is_reserved_word().
test_cli
struct ast_cli_entry test_cli[] static
Definition at line 1062 of file test.c.
test_result2str
const char* const test_result2str[] static
Initial value:
= {
   [AST_TEST_NOT_RUN] = "NOT RUN",
   [AST_TEST_PASS]    = "PASS",
   [AST_TEST_FAIL]    = "FAIL",
}
This array corresponds to the values defined in the ast_test_state enum
Definition at line 58 of file test.c.
Referenced by test_cli_show_registered(), test_cli_show_results(), test_execute_multiple(), and test_txt_entry().
test_suite_topic
struct stasis_topic* test_suite_topic
The topic for test suite messages.
Since
12
Definition at line 55 of file test.c.
Referenced by ast_test_suite_topic().
tests
struct tests tests = { .first = NULL, .last = NULL, .lock = { PTHREAD_RECURSIVE_MUTEX_INITIALIZER_NP , NULL, {1, 0} } , } static