Asterisk - The Open Source Telephony Project: pbx_loopback.c File Reference
pbx_loopback.c File Reference
Loopback PBX Module.
#include "asterisk.h"
#include "asterisk/file.h"
#include "asterisk/logger.h"
#include "asterisk/channel.h"
#include "asterisk/config.h"
#include "asterisk/pbx.h"
#include "asterisk/module.h"
#include "asterisk/frame.h"
#include "asterisk/cli.h"
#include "asterisk/lock.h"
#include "asterisk/md5.h"
#include "asterisk/linkedlists.h"
#include "asterisk/chanvars.h"
#include "asterisk/sched.h"
#include "asterisk/io.h"
#include "asterisk/utils.h"
#include "asterisk/astdb.h"
Macros
#define LOOPBACK_COMMON
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int load_module (void)
static int loopback_canmatch (struct ast_channel *chan, const char *context, const char *exten, int priority, const char *callerid, const char *data)
static int loopback_exec (struct ast_channel *chan, const char *context, const char *exten, int priority, const char *callerid, const char *data)
static int loopback_exists (struct ast_channel *chan, const char *context, const char *exten, int priority, const char *callerid, const char *data)
static int loopback_matchmore (struct ast_channel *chan, const char *context, const char *exten, int priority, const char *callerid, const char *data)
static void loopback_parse (char **newexten, char **newcontext, int *priority, char **newpattern, char *buf)
static char * loopback_subst (char *buf, int buflen, const char *exten, const char *context, int priority, const char *data)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Loopback Switch" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, }
static const struct ast_module_info * ast_module_info = &__mod_info
static struct ast_switch loopback_switch
Detailed Description
Loopback PBX Module.
Definition in file pbx_loopback.c.
Macro Definition Documentation
LOOPBACK_COMMON
#define LOOPBACK_COMMON
Definition at line 73 of file pbx_loopback.c.
Referenced by loopback_canmatch(), loopback_exec(), loopback_exists(), and loopback_matchmore().
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 191 of file pbx_loopback.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 191 of file pbx_loopback.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 191 of file pbx_loopback.c.
load_module()
static int load_module (void) static
Definition at line 184 of file pbx_loopback.c.
References AST_MODULE_LOAD_FAILURE, AST_MODULE_LOAD_SUCCESS, and ast_register_switch().
 {
    if (ast_register_switch(&loopback_switch))
       return AST_MODULE_LOAD_FAILURE;
    return AST_MODULE_LOAD_SUCCESS;
 }
loopback_canmatch()
static int loopback_canmatch (struct ast_channel * chan, const char * context, const char * exten, int priority, const char * callerid, const char * data) static
Definition at line 140 of file pbx_loopback.c.
References ast_canmatch_extension(), ast_extension_match(), and LOOPBACK_COMMON.
 {
    LOOPBACK_COMMON;
    if (newpattern && !ast_extension_match(newpattern, exten))
       res = 0;
    else
       res = ast_canmatch_extension(chan, newcontext, newexten, newpriority, callerid);
    return res;
 }
loopback_exec()
static int loopback_exec (struct ast_channel * chan, const char * context, const char * exten, int priority, const char * callerid, const char * data) static
Definition at line 150 of file pbx_loopback.c.
References ast_spawn_extension(), and LOOPBACK_COMMON.
 {
    int found;
    LOOPBACK_COMMON;
    res = ast_spawn_extension(chan, newcontext, newexten, newpriority, callerid, &found, 0);
    return res;
 }
loopback_exists()
static int loopback_exists (struct ast_channel * chan, const char * context, const char * exten, int priority, const char * callerid, const char * data) static
Definition at line 130 of file pbx_loopback.c.
References ast_exists_extension(), ast_extension_match(), and LOOPBACK_COMMON.
 {
    LOOPBACK_COMMON;
    if (newpattern && !ast_extension_match(newpattern, exten))
       res = 0;
    else
       res = ast_exists_extension(chan, newcontext, newexten, newpriority, callerid);
    return res;
 }
loopback_matchmore()
static int loopback_matchmore (struct ast_channel * chan, const char * context, const char * exten, int priority, const char * callerid, const char * data) static
Definition at line 158 of file pbx_loopback.c.
References ast_extension_match(), ast_matchmore_extension(), and LOOPBACK_COMMON.
 {
    LOOPBACK_COMMON;
    if (newpattern && !ast_extension_match(newpattern, exten))
       res = 0;
    else
       res = ast_matchmore_extension(chan, newcontext, newexten, newpriority, callerid);
    return res;
 }
loopback_parse()
static void loopback_parse (char ** newexten, char ** newcontext, int * priority, char ** newpattern, char * buf) static
Definition at line 109 of file pbx_loopback.c.
References ast_strlen_zero, and buf.
 {
    char *con;
    char *pri;
    *newpattern = strchr(buf, '/');
    if (*newpattern)
       *(*newpattern)++ = '\0';
    con = strchr(buf, '@');
    if (con) {
       *con++ = '\0';
       pri = strchr(con, ':');
    } else
       pri = strchr(buf, ':');
    if (!ast_strlen_zero(buf))
       *newexten = buf;
    if (!ast_strlen_zero(con))
       *newcontext = con;
    if (!ast_strlen_zero(pri))
       sscanf(pri, "%30d", priority);
 }
loopback_subst()
static char* loopback_subst (char * buf, int buflen, const char * exten, const char * context, int priority, const char * data) static
Definition at line 84 of file pbx_loopback.c.
References AST_LIST_HEAD_INIT_NOLOCK, AST_LIST_INSERT_HEAD, AST_LIST_REMOVE_HEAD, ast_var_assign, ast_var_delete(), buf, pbx_substitute_variables_varshead(), and tmp().
 {
    struct ast_var_t *newvariable;
    struct varshead headp;
    char tmp[80];
    snprintf(tmp, sizeof(tmp), "%d", priority);
    AST_LIST_HEAD_INIT_NOLOCK(&headp);
    if ((newvariable = ast_var_assign("EXTEN", exten))) {
       AST_LIST_INSERT_HEAD(&headp, newvariable, entries);
    }
    if ((newvariable = ast_var_assign("CONTEXT", context))) {
       AST_LIST_INSERT_HEAD(&headp, newvariable, entries);
    }
    if ((newvariable = ast_var_assign("PRIORITY", tmp))) {
       AST_LIST_INSERT_HEAD(&headp, newvariable, entries);
    }
    /* Substitute variables */
    pbx_substitute_variables_varshead(&headp, data, buf, buflen);
    /* free the list */
    while ((newvariable = AST_LIST_REMOVE_HEAD(&headp, entries)))
                 ast_var_delete(newvariable);
    return buf;
 }
unload_module()
static int unload_module (void) static
Definition at line 178 of file pbx_loopback.c.
References ast_unregister_switch().
 {
    ast_unregister_switch(&loopback_switch);
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Loopback Switch" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, } static
Definition at line 191 of file pbx_loopback.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 191 of file pbx_loopback.c.
loopback_switch
struct ast_switch loopback_switch static
Definition at line 168 of file pbx_loopback.c.