Asterisk - The Open Source Telephony Project: ast_atexit Struct Reference
ast_atexit Struct Reference
Data Fields
void(* func)(void)
int is_cleanup
struct {
struct ast_atexit * next
} list
Detailed Description
Definition at line 328 of file asterisk.c.
Field Documentation
func
void(* func) (void)
Definition at line 329 of file asterisk.c.
Referenced by __ast_unregister_atexit(), ast_register_atexit(), ast_register_cleanup(), ast_run_atexits(), ast_unregister_atexit(), and register_atexit().
is_cleanup
int is_cleanup
Definition at line 330 of file asterisk.c.
Referenced by ast_run_atexits(), and register_atexit().
list
struct { ... } list
Referenced by __ast_unregister_atexit(), ast_run_atexits(), and register_atexit().
next
struct ast_atexit* next
Definition at line 331 of file asterisk.c.
The documentation for this struct was generated from the following file:
asterisk.c