Asterisk - The Open Source Telephony Project: privacy.c File Reference
privacy.c File Reference
Privacy Routines.
#include "asterisk.h"
#include <sys/time.h>
#include <signal.h>
#include <dirent.h>
#include "asterisk/channel.h"
#include "asterisk/file.h"
#include "asterisk/app.h"
#include "asterisk/dsp.h"
#include "asterisk/astdb.h"
#include "asterisk/callerid.h"
#include "asterisk/privacy.h"
#include "asterisk/utils.h"
#include "asterisk/lock.h"
Functions
int ast_privacy_check (char *dest, char *cid)
int ast_privacy_reset (char *dest)
int ast_privacy_set (char *dest, char *cid, int status)
Detailed Description
Privacy Routines.
Author
Mark Spencer marks.nosp@m.ter@.nosp@m.digiu.nosp@m.m.co.nosp@m.m
Definition in file privacy.c.
Function Documentation
ast_privacy_check()
int ast_privacy_check (char * dest, char * cid)
Definition at line 46 of file privacy.c.
References ast_callerid_parse(), ast_copy_string(), ast_db_get(), AST_PRIVACY_ALLOW, AST_PRIVACY_DENY, AST_PRIVACY_KILL, AST_PRIVACY_TORTURE, AST_PRIVACY_UNKNOWN, ast_shrink_phone_number(), result, and tmp().
Referenced by setup_privacy_args().
 {
    char tmp[256] = "";
    char *trimcid = "";
    char *n, *l;
    int res;
    char key[256], result[256];
    if (cid)
       ast_copy_string(tmp, cid, sizeof(tmp));
    ast_callerid_parse(tmp, &n, &l);
    if (l) {
       ast_shrink_phone_number(l);
       trimcid = l;
    }
    snprintf(key, sizeof(key), "%s/%s", dest, trimcid);
    res = ast_db_get("privacy", key, result, sizeof(result));
    if (!res) {
       if (!strcasecmp(result, "allow"))
          return AST_PRIVACY_ALLOW;
       if (!strcasecmp(result, "deny"))
          return AST_PRIVACY_DENY;
       if (!strcasecmp(result, "kill"))
          return AST_PRIVACY_KILL;
       if (!strcasecmp(result, "torture"))
          return AST_PRIVACY_TORTURE;
    }
    return AST_PRIVACY_UNKNOWN;
 }
ast_privacy_reset()
int ast_privacy_reset (char * dest)
Definition at line 75 of file privacy.c.
References ast_db_deltree().
 {
    if (!dest)
       return -1;
    return ast_db_deltree("privacy", dest);
 }
ast_privacy_set()
int ast_privacy_set (char * dest, char * cid, int status)
Definition at line 82 of file privacy.c.
References ast_callerid_parse(), ast_copy_string(), ast_db_del(), ast_db_put(), AST_PRIVACY_ALLOW, AST_PRIVACY_DENY, AST_PRIVACY_KILL, AST_PRIVACY_TORTURE, AST_PRIVACY_UNKNOWN, ast_shrink_phone_number(), ast_strlen_zero, and tmp().
Referenced by valid_priv_reply().
 {
    char tmp[256] = "";
    char *trimcid = "";
    char *n, *l;
    int res;
    char key[256];
    if (cid)
       ast_copy_string(tmp, cid, sizeof(tmp));
    ast_callerid_parse(tmp, &n, &l);
    if (l) {
       ast_shrink_phone_number(l);
       trimcid = l;
    }
    if (ast_strlen_zero(trimcid)) {
       /* Don't store anything for empty Caller*ID */
       return 0;
    }
    snprintf(key, sizeof(key), "%s/%s", dest, trimcid);
    if (status == AST_PRIVACY_UNKNOWN)
       res = ast_db_del("privacy", key);
    else if (status == AST_PRIVACY_ALLOW)
       res = ast_db_put("privacy", key, "allow");
    else if (status == AST_PRIVACY_DENY)
       res = ast_db_put("privacy", key, "deny");
    else if (status == AST_PRIVACY_KILL)
       res = ast_db_put("privacy", key, "kill");
    else if (status == AST_PRIVACY_TORTURE)
       res = ast_db_put("privacy", key, "torture");
    else
       res = -1;
    return res;
 }