Asterisk - The Open Source Telephony Project: presencestate.c File Reference
presencestate.c File Reference
Presence state management.
#include "asterisk.h"
#include "asterisk/_private.h"
#include "asterisk/utils.h"
#include "asterisk/lock.h"
#include "asterisk/linkedlists.h"
#include "asterisk/presencestate.h"
#include "asterisk/pbx.h"
#include "asterisk/app.h"
#include "asterisk/test.h"
Data Structures
struct presence_state_provider
A presence state provider.
struct presence_state_providers
A list of providers.
Macros
#define TEST_CATEGORY "/main/presence/"
Functions
enum ast_presence_state ast_presence_state (const char *presence_provider, char **subtype, char **message)
Asks a presence state provider for the current presence state.
const char * ast_presence_state2str (enum ast_presence_state state)
Convert presence state to text string for output.
struct stasis_cache * ast_presence_state_cache (void)
Backend cache for ast_presence_state_topic_cached()
int ast_presence_state_changed (enum ast_presence_state state, const char *subtype, const char *message, const char *fmt,...)
Notify the world that a presence provider state changed.
int ast_presence_state_changed_literal (enum ast_presence_state state, const char *subtype, const char *message, const char *presence_provider)
Notify the world that a presence provider state changed.
int ast_presence_state_engine_init (void)
static enum ast_presence_state ast_presence_state_helper (const char *presence_provider, char **subtype, char **message, int check_cache)
enum ast_presence_state ast_presence_state_nocache (const char *presence_provider, char **subtype, char **message)
Asks a presence state provider for the current presence state, bypassing the event cache.
int ast_presence_state_prov_add (const char *label, ast_presence_state_prov_cb_type callback)
Add presence state provider.
int ast_presence_state_prov_del (const char *label)
Remove presence state provider.
struct stasis_topic * ast_presence_state_topic_all (void)
Get presence state topic.
struct stasis_topic * ast_presence_state_topic_cached (void)
Get caching presence state topic.
enum ast_presence_state ast_presence_state_val (const char *val)
Convert presence state from text to integer value.
AST_TEST_DEFINE (test_presence_chan)
static void do_presence_state_change (const char *provider)
static struct ast_presence_state_message * presence_state_alloc (const char *provider, enum ast_presence_state state, const char *subtype, const char *message)
static enum ast_presence_state presence_state_cached (const char *presence_provider, char **subtype, char **message)
static void presence_state_dtor (void *obj)
static void presence_state_engine_cleanup (void)
static void presence_state_event (const char *provider, enum ast_presence_state state, const char *subtype, const char *message)
static const char * presence_state_get_id (struct stasis_message *msg)
static struct ast_manager_event_blob * presence_state_to_ami (struct stasis_message *msg)
static int presence_test_presencestate (const char *label, char **subtype, char **message)
STASIS_MESSAGE_TYPE_DEFN (ast_presence_state_message_type,.to_ami=presence_state_to_ami,)
Variables
struct stasis_cache * presence_state_cache
static struct presence_state_providers presence_state_providers = { .first = NULL, .last = NULL, .lock = { PTHREAD_RWLOCK_INITIALIZER , NULL, {1, 0} } , }
struct stasis_topic * presence_state_topic_all
struct stasis_caching_topic * presence_state_topic_cached
static int presence_test_alice_state = AST_PRESENCE_UNAVAILABLE
static int presence_test_bob_state = AST_PRESENCE_UNAVAILABLE
static struct ast_channel_tech presence_test_tech
struct {
enum ast_presence_state state
const char * string
} state2string []
Device state strings for printing.
Detailed Description
Presence state management.
Definition in file presencestate.c.
Macro Definition Documentation
TEST_CATEGORY
#define TEST_CATEGORY "/main/presence/"
Definition at line 393 of file presencestate.c.
Referenced by AST_TEST_DEFINE().
Function Documentation
ast_presence_state()
enum ast_presence_state ast_presence_state (const char * presence_provider, char ** subtype, char ** message)
Asks a presence state provider for the current presence state.
Parameters
presence_provider The presence provider to retrieve the state from.
subtype The output paramenter to store the subtype string in. Must be freed if returned
message The output paramenter to store the message string in. Must be freed if returned
Return values
presence state value on success,
-1 on failure.
Definition at line 221 of file presencestate.c.
References ast_presence_state_helper().
 {
    return ast_presence_state_helper(presence_provider, subtype, message, 1);
 }
ast_presence_state2str()
const char* ast_presence_state2str (enum ast_presence_state state)
Convert presence state to text string for output.
Parameters
state Current presence state
Definition at line 103 of file presencestate.c.
References ARRAY_LEN, and state2string.
Referenced by action_presencestate(), AST_TEST_DEFINE(), exten_state_publisher_state_cb(), handle_cli_presencestate_list(), handle_show_hint(), handle_show_hints(), manager_state_cb(), pidf_supplement_body(), presence_change_common(), presence_read(), presence_state_to_ami(), and state_notify_build_xml().
 {
    int i;
    for (i = 0; i < ARRAY_LEN(state2string); i++) {
       if (state == state2string[i].state) {
          return state2string[i].string;
       }
    }
    return "";
 }
ast_presence_state_cache()
struct stasis_cache* ast_presence_state_cache (void)
Backend cache for ast_presence_state_topic_cached()
Return values
Cache of ast_presence_state_message.
Since
12
Definition at line 370 of file presencestate.c.
References presence_state_cache.
Referenced by action_presencestatelist(), and presence_state_cached().
 {
    return presence_state_cache;
 }
ast_presence_state_changed()
int ast_presence_state_changed (enum ast_presence_state state, const char * subtype, const char * message, const char * fmt, ...)
Notify the world that a presence provider state changed.
Parameters
state the new presence state
subtype the new presence subtype
message the new presence message
fmt Presence entity whose state has changed
The new state of the entity will be sent off to any subscribers of the presence state. It will also be stored in the internal event cache.
Return values
0 Success
-1 Failure
Definition at line 350 of file presencestate.c.
References AST_MAX_EXTENSION, ast_presence_state_changed_literal(), and buf.
Referenced by load_module().
 {
    char buf[AST_MAX_EXTENSION];
    va_list ap;
    va_start(ap, fmt);
    vsnprintf(buf, sizeof(buf), fmt, ap);
    va_end(ap);
    return ast_presence_state_changed_literal(state, subtype, message, buf);
 }
ast_presence_state_changed_literal()
int ast_presence_state_changed_literal (enum ast_presence_state state, const char * subtype, const char * message, const char * presence_provider)
Notify the world that a presence provider state changed.
Parameters
state the new presence state
subtype the new presence subtype
message the new presence message
presence_provider Presence entity whose state has changed
The new state of the entity will be sent off to any subscribers of the presence state. It will also be stored in the internal event cache.
Return values
0 Success
-1 Failure
Definition at line 336 of file presencestate.c.
References AST_PRESENCE_NOT_SET, do_presence_state_change(), and presence_state_event().
Referenced by ast_presence_state_changed(), handle_cli_presencestate_change(), and presence_write().
 {
    if (state == AST_PRESENCE_NOT_SET) {
       do_presence_state_change(presence_provider);
    } else {
       presence_state_event(presence_provider, state, subtype, message);
    }
    return 0;
 }
ast_presence_state_engine_init()
int ast_presence_state_engine_init (void)
Definition at line 495 of file presencestate.c.
References ast_presence_state_message_type(), ast_register_cleanup(), AST_TEST_REGISTER, presence_state_engine_cleanup(), presence_state_get_id(), stasis_cache_create(), stasis_caching_accept_message_type(), stasis_caching_set_filter(), stasis_caching_topic_create(), STASIS_MESSAGE_TYPE_INIT, STASIS_SUBSCRIPTION_FILTER_SELECTIVE, and stasis_topic_create().
Referenced by asterisk_daemon().
 {
    ast_register_cleanup(presence_state_engine_cleanup);
    if (STASIS_MESSAGE_TYPE_INIT(ast_presence_state_message_type) != 0) {
       return -1;
    }
    presence_state_topic_all = stasis_topic_create("presence_state:all");
    if (!presence_state_topic_all) {
       return -1;
    }
    presence_state_cache = stasis_cache_create(presence_state_get_id);
    if (!presence_state_cache) {
       return -1;
    }
    presence_state_topic_cached = stasis_caching_topic_create(presence_state_topic_all, presence_state_cache);
    if (!presence_state_topic_cached) {
       return -1;
    }
    stasis_caching_accept_message_type(presence_state_topic_cached, ast_presence_state_message_type());
    stasis_caching_set_filter(presence_state_topic_cached, STASIS_SUBSCRIPTION_FILTER_SELECTIVE);
    AST_TEST_REGISTER(test_presence_chan);
    return 0;
 }
ast_presence_state_helper()
static enum ast_presence_state ast_presence_state_helper (const char * presence_provider, char ** subtype, char ** message, int check_cache) static
Definition at line 146 of file presencestate.c.
References ast_debug, ast_free, ast_get_channel_tech(), ast_log, AST_PRESENCE_AVAILABLE, AST_PRESENCE_AWAY, AST_PRESENCE_CHAT, AST_PRESENCE_DND, AST_PRESENCE_INVALID, AST_PRESENCE_NOT_SET, AST_PRESENCE_UNAVAILABLE, AST_PRESENCE_XA, AST_RWLIST_RDLOCK, AST_RWLIST_TRAVERSE, AST_RWLIST_UNLOCK, ast_strdupa, presence_state_provider::callback, presence_state_provider::label, LOG_WARNING, NULL, presence_state_cached(), ast_channel_tech::presencestate, provider, state, and strsep().
Referenced by ast_presence_state(), ast_presence_state_nocache(), and do_presence_state_change().
 {
    char *labels = ast_strdupa(presence_provider);
    char *label;
    enum ast_presence_state state = AST_PRESENCE_INVALID;
    enum ast_presence_state state_order[] = {
       [AST_PRESENCE_INVALID]     = 0,
       [AST_PRESENCE_NOT_SET]     = 1,
       [AST_PRESENCE_AVAILABLE]   = 2,
       [AST_PRESENCE_UNAVAILABLE] = 3,
       [AST_PRESENCE_CHAT]        = 4,
       [AST_PRESENCE_AWAY]        = 5,
       [AST_PRESENCE_XA]          = 6,
       [AST_PRESENCE_DND]         = 7
    };
    *subtype = NULL;
    *message = NULL;
    while ((label = strsep(&labels, "&"))) {
       enum ast_presence_state next_state = AST_PRESENCE_INVALID;
       char *next_subtype = NULL;
       char *next_message = NULL;
       if (check_cache) {
          next_state = presence_state_cached(label, &next_subtype, &next_message);
       }
       if (next_state == AST_PRESENCE_INVALID) {
          struct presence_state_provider *provider;
          const struct ast_channel_tech *chan_tech;
          char *address;
          if ((address = strchr(label, '/'))) {
             *address++ = '\0';
             if ((chan_tech = ast_get_channel_tech(label)) && chan_tech->presencestate) {
                next_state = chan_tech->presencestate(address, &next_subtype, &next_message);
             }
          } else if ((address = strchr(label, ':'))) {
             *address++ = '\0';
             AST_RWLIST_RDLOCK(&presence_state_providers);
             AST_RWLIST_TRAVERSE(&presence_state_providers, provider, list) {
                ast_debug(5, "Checking provider %s with %s\n", provider->label, label);
                if (!strcasecmp(provider->label, label)) {
                   next_state = provider->callback(address, &next_subtype, &next_message);
                   break;
                }
             }
             AST_RWLIST_UNLOCK(&presence_state_providers);
             if (!provider) {
                ast_log(LOG_WARNING, "No provider found for label: %s\n", label);
             }
          } else {
             ast_log(LOG_WARNING, "No label found for presence state provider: %s\n", label);
          }
       }
       if (state_order[next_state] > state_order[state]) {
          state = next_state;
          ast_free(*subtype);
          ast_free(*message);
          *subtype = next_subtype;
          *message = next_message;
       }
    }
    return state;
 }
ast_presence_state_nocache()
enum ast_presence_state ast_presence_state_nocache (const char * presence_provider, char ** subtype, char ** message)
Asks a presence state provider for the current presence state, bypassing the event cache.
Some presence state providers may perform transformations on presence data when it is requested (such as a base64 decode). In such instances, use of the event cache is not suitable and should be bypassed.
Parameters
presence_provider The presence provider to retrieve the state from.
subtype The output paramenter to store the subtype string in. Must be freed if returned
message The output paramenter to store the message string in. Must be freed if returned
Return values
presence state value on success,
-1 on failure.
Definition at line 226 of file presencestate.c.
References ast_presence_state_helper().
Referenced by AST_TEST_DEFINE(), and presence_read().
 {
    return ast_presence_state_helper(presence_provider, subtype, message, 0);
 }
ast_presence_state_prov_add()
int ast_presence_state_prov_add (const char * label, ast_presence_state_prov_cb_type callback)
Add presence state provider.
Parameters
label to use in hint, like label:object
callback Callback
Return values
0 success
-1 failure
Definition at line 231 of file presencestate.c.
References ast_calloc, ast_copy_string(), AST_RWLIST_INSERT_HEAD, AST_RWLIST_UNLOCK, AST_RWLIST_WRLOCK, presence_state_provider::callback, presence_state_provider::label, and provider.
Referenced by load_module().
 {
    struct presence_state_provider *provider;
    if (!callback || !(provider = ast_calloc(1, sizeof(*provider)))) {
       return -1;
    }
    provider->callback = callback;
    ast_copy_string(provider->label, label, sizeof(provider->label));
    AST_RWLIST_WRLOCK(&presence_state_providers);
    AST_RWLIST_INSERT_HEAD(&presence_state_providers, provider, list);
    AST_RWLIST_UNLOCK(&presence_state_providers);
    return 0;
 }
ast_presence_state_prov_del()
int ast_presence_state_prov_del (const char * label)
Remove presence state provider.
Parameters
label to use in hint, like label:object
Return values
-1 on failure
0 on success
Definition at line 248 of file presencestate.c.
References ast_free, AST_RWLIST_REMOVE_CURRENT, AST_RWLIST_TRAVERSE_SAFE_BEGIN, AST_RWLIST_TRAVERSE_SAFE_END, AST_RWLIST_UNLOCK, AST_RWLIST_WRLOCK, presence_state_provider::label, and provider.
Referenced by unload_module().
 {
    struct presence_state_provider *provider;
    int res = -1;
    AST_RWLIST_WRLOCK(&presence_state_providers);
    AST_RWLIST_TRAVERSE_SAFE_BEGIN(&presence_state_providers, provider, list) {
       if (!strcasecmp(provider->label, label)) {
          AST_RWLIST_REMOVE_CURRENT(list);
          ast_free(provider);
          res = 0;
          break;
       }
    }
    AST_RWLIST_TRAVERSE_SAFE_END;
    AST_RWLIST_UNLOCK(&presence_state_providers);
    return res;
 }
ast_presence_state_topic_all()
struct stasis_topic* ast_presence_state_topic_all (void)
Get presence state topic.
Return values
Stasis topic for presence state messages
Since
12
Definition at line 365 of file presencestate.c.
References presence_state_topic_all.
Referenced by load_module(), load_pbx(), presence_change_common(), presence_state_event(), and publish_hint_change().
 {
    return presence_state_topic_all;
 }
ast_presence_state_topic_cached()
struct stasis_topic* ast_presence_state_topic_cached (void)
Get caching presence state topic.
Return values
Caching Stasis topic for presence state messages
Since
12
Definition at line 375 of file presencestate.c.
References stasis_caching_get_topic().
 {
    return stasis_caching_get_topic(presence_state_topic_cached);
 }
ast_presence_state_val()
enum ast_presence_state ast_presence_state_val (const char * val)
Convert presence state from text to integer value.
Parameters
val The text representing the presence state. Valid values are anything that comes after AST_PRESENCE_ in one of the defined values.
Returns
The AST_PRESENCE_ integer value
Definition at line 114 of file presencestate.c.
References ARRAY_LEN, AST_PRESENCE_INVALID, and state2string.
Referenced by parse_data().
 {
    int i;
    for (i = 0; i < ARRAY_LEN(state2string); i++) {
       if (!strcasecmp(val, state2string[i].string)) {
          return state2string[i].state;
       }
    }
    return AST_PRESENCE_INVALID;
 }
AST_TEST_DEFINE()
AST_TEST_DEFINE (test_presence_chan)
Definition at line 415 of file presencestate.c.
References ast_channel_register(), ast_channel_unregister(), ast_free, ast_log, AST_PRESENCE_AVAILABLE, AST_PRESENCE_DND, ast_presence_state2str(), ast_presence_state_nocache(), AST_PRESENCE_UNAVAILABLE, AST_TEST_FAIL, AST_TEST_NOT_RUN, AST_TEST_PASS, sip_to_pjsip::info(), LOG_WARNING, NULL, presence_test_alice_state, presence_test_bob_state, provider, state, TEST_CATEGORY, TEST_EXECUTE, TEST_INIT, and ast_channel_tech::type.
 {
    int res = AST_TEST_FAIL;
    char provider[80];
    enum ast_presence_state state;
    char *subtype = NULL, *message = NULL;
    switch (cmd) {
    case TEST_INIT:
       info->name = "channel_presence";
       info->category = TEST_CATEGORY;
       info->summary = "Channel presence state tests";
       info->description = "Creates test channel technology and then test the presence state callback";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    if (ast_channel_register(&presence_test_tech)) {
       ast_log(LOG_WARNING, "Unable to register channel type '%s'\n", presence_test_tech.type);
       goto presence_test_cleanup;
    }
    /* Check Alice's state */
    snprintf(provider, sizeof(provider), "%s/Alice", presence_test_tech.type);
    presence_test_alice_state = AST_PRESENCE_AVAILABLE;
    state = ast_presence_state_nocache(provider, &subtype, &message);
    if (state != presence_test_alice_state) {
       ast_log(LOG_WARNING, "Presence state of '%s' returned '%s' instead of the expected value '%s'\n",
          provider, ast_presence_state2str(state), ast_presence_state2str(presence_test_alice_state));
       goto presence_test_cleanup;
    }
    /* Check Alice's and Bob's state, Alice's should win as DND > AVAILABLE */
    snprintf(provider, sizeof(provider), "%s/Alice&%s/Bob", presence_test_tech.type, presence_test_tech.type);
    presence_test_alice_state = AST_PRESENCE_DND;
    presence_test_bob_state = AST_PRESENCE_UNAVAILABLE;
    state = ast_presence_state_nocache(provider, &subtype, &message);
    if (state != presence_test_alice_state) {
       ast_log(LOG_WARNING, "Presence state of '%s' returned '%s' instead of the expected value '%s'\n",
          provider, ast_presence_state2str(state), ast_presence_state2str(presence_test_alice_state));
       goto presence_test_cleanup;
         }
    /* Check Alice's and Bob's state, Bob's should now win as AVAILABLE < UNAVAILABLE */
    presence_test_alice_state = AST_PRESENCE_AVAILABLE;
    state = ast_presence_state_nocache(provider, &subtype, &message);
    if (state != presence_test_bob_state) {
       ast_log(LOG_WARNING, "Presence state of '%s' returned '%s' instead of the expected value '%s'\n",
          provider, ast_presence_state2str(state), ast_presence_state2str(presence_test_bob_state));
       goto presence_test_cleanup;
    }
    res = AST_TEST_PASS;
 presence_test_cleanup:
    ast_channel_unregister(&presence_test_tech);
    ast_free(subtype);
    ast_free(message);
    return res;
 }
do_presence_state_change()
static void do_presence_state_change (const char * provider) static
Definition at line 319 of file presencestate.c.
References ast_free, AST_PRESENCE_INVALID, ast_presence_state_helper(), NULL, presence_state_event(), and state.
Referenced by ast_presence_state_changed_literal().
 {
    char *subtype = NULL;
    char *message = NULL;
    enum ast_presence_state state;
    state = ast_presence_state_helper(provider, &subtype, &message, 0);
    if (state == AST_PRESENCE_INVALID) {
       return;
    }
    presence_state_event(provider, state, subtype, message);
    ast_free(subtype);
    ast_free(message);
 }
presence_state_alloc()
static struct ast_presence_state_message* presence_state_alloc (const char * provider, enum ast_presence_state state, const char * subtype, const char * message) static
Definition at line 274 of file presencestate.c.
References ao2_alloc, ao2_cleanup, ao2_ref, ast_string_field_init, ast_string_field_set, NULL, presence_state_dtor(), RAII_VAR, S_OR, and state.
Referenced by presence_state_event().
 {
    RAII_VAR(struct ast_presence_state_message *, presence_state, ao2_alloc(sizeof(*presence_state), presence_state_dtor), ao2_cleanup);
    if (!presence_state || ast_string_field_init(presence_state, 256)) {
       return NULL;
    }
    presence_state->state = state;
    ast_string_field_set(presence_state, provider, provider);
    ast_string_field_set(presence_state, subtype, S_OR(subtype, ""));
    ast_string_field_set(presence_state, message, S_OR(message, ""));
    ao2_ref(presence_state, +1);
    return presence_state;
 }
presence_state_cached()
static enum ast_presence_state presence_state_cached (const char * presence_provider, char ** subtype, char ** message) static
Definition at line 125 of file presencestate.c.
References ao2_cleanup, AST_PRESENCE_INVALID, ast_presence_state_cache(), ast_presence_state_message_type(), ast_strdup, ast_strlen_zero, NULL, RAII_VAR, stasis_cache_get(), stasis_message_data(), and ast_presence_state_message::state.
Referenced by ast_presence_state_helper().
 {
    enum ast_presence_state res = AST_PRESENCE_INVALID;
    RAII_VAR(struct stasis_message *, msg, NULL, ao2_cleanup);
    struct ast_presence_state_message *presence_state;
    msg = stasis_cache_get(ast_presence_state_cache(), ast_presence_state_message_type(), presence_provider);
    if (!msg) {
       return res;
    }
    presence_state = stasis_message_data(msg);
    res = presence_state->state;
    *subtype = !ast_strlen_zero(presence_state->subtype) ? ast_strdup(presence_state->subtype) : NULL;
    *message = !ast_strlen_zero(presence_state->message) ? ast_strdup(presence_state->message) : NULL;
    return res;
 }
presence_state_dtor()
static void presence_state_dtor (void * obj) static
Definition at line 268 of file presencestate.c.
References ast_string_field_free_memory.
Referenced by presence_state_alloc().
 {
    struct ast_presence_state_message *presence_state = obj;
    ast_string_field_free_memory(presence_state);
 }
presence_state_engine_cleanup()
static void presence_state_engine_cleanup (void) static
Definition at line 484 of file presencestate.c.
References ao2_cleanup, ast_presence_state_message_type(), AST_TEST_UNREGISTER, NULL, stasis_caching_unsubscribe_and_join(), and STASIS_MESSAGE_TYPE_CLEANUP.
Referenced by ast_presence_state_engine_init().
 {
    ao2_cleanup(presence_state_topic_all);
    presence_state_topic_all = NULL;
    ao2_cleanup(presence_state_cache);
    presence_state_cache = NULL;
    presence_state_topic_cached = stasis_caching_unsubscribe_and_join(presence_state_topic_cached);
    STASIS_MESSAGE_TYPE_CLEANUP(ast_presence_state_message_type);
    AST_TEST_UNREGISTER(test_presence_chan);
 }
presence_state_event()
static void presence_state_event (const char * provider, enum ast_presence_state state, const char * subtype, const char * message) static
Definition at line 294 of file presencestate.c.
References ao2_cleanup, ast_presence_state_message_type(), ast_presence_state_topic_all(), NULL, presence_state_alloc(), RAII_VAR, stasis_message_create(), and stasis_publish().
Referenced by ast_presence_state_changed_literal(), and do_presence_state_change().
 {
    RAII_VAR(struct stasis_message *, msg, NULL, ao2_cleanup);
    RAII_VAR(struct ast_presence_state_message *, presence_state, NULL, ao2_cleanup);
    if (!ast_presence_state_message_type()) {
       return;
    }
    presence_state = presence_state_alloc(provider, state, subtype, message);
    if (!presence_state) {
       return;
    }
    msg = stasis_message_create(ast_presence_state_message_type(), presence_state);
    if (!msg) {
       return;
    }
    stasis_publish(ast_presence_state_topic_all(), msg);
 }
presence_state_get_id()
static const char* presence_state_get_id (struct stasis_message * msg) static
Definition at line 380 of file presencestate.c.
References ast_presence_state_message_type(), NULL, stasis_message_data(), and stasis_message_type().
Referenced by ast_presence_state_engine_init().
 {
    struct ast_presence_state_message *presence_state = stasis_message_data(msg);
    if (stasis_message_type(msg) != ast_presence_state_message_type()) {
       return NULL;
    }
    return presence_state->provider;
 }
presence_state_to_ami()
static struct ast_manager_event_blob * presence_state_to_ami (struct stasis_message * msg) static
Definition at line 525 of file presencestate.c.
References ast_escape_c_alloc(), ast_free, ast_manager_event_blob_create(), ast_presence_state2str(), EVENT_FLAG_CALL, stasis_message_data(), and ast_presence_state_message::state.
 {
    struct ast_presence_state_message *presence_state = stasis_message_data(msg);
    struct ast_manager_event_blob *res;
    char *subtype = ast_escape_c_alloc(presence_state->subtype);
    char *message = ast_escape_c_alloc(presence_state->message);
    res = ast_manager_event_blob_create(EVENT_FLAG_CALL, "PresenceStateChange",
       "Presentity: %s\r\n"
       "Status: %s\r\n"
       "Subtype: %s\r\n"
       "Message: %s\r\n",
       presence_state->provider,
       ast_presence_state2str(presence_state->state),
       subtype ?: "",
                 message ?: "");
    ast_free(subtype);
    ast_free(message);
    return res;
 }
presence_test_presencestate()
static int presence_test_presencestate (const char * label, char ** subtype, char ** message) static
Definition at line 398 of file presencestate.c.
References AST_PRESENCE_UNAVAILABLE, presence_test_alice_state, and presence_test_bob_state.
 {
    if (!strcmp(label, "Alice")) {
       return presence_test_alice_state;
    } else if (!strcmp(label, "Bob")) {
       return presence_test_bob_state;
    } else {
       return AST_PRESENCE_UNAVAILABLE;
    }
 }
STASIS_MESSAGE_TYPE_DEFN()
STASIS_MESSAGE_TYPE_DEFN (ast_presence_state_message_type , . to_ami = presence_state_to_ami)
Variable Documentation
presence_state_cache
struct stasis_cache* presence_state_cache
Definition at line 90 of file presencestate.c.
Referenced by ast_presence_state_cache().
presence_state_providers
struct presence_state_providers presence_state_providers = { .first = NULL, .last = NULL, .lock = { PTHREAD_RWLOCK_INITIALIZER , NULL, {1, 0} } , } static
presence_state_topic_all
struct stasis_topic* presence_state_topic_all
Definition at line 89 of file presencestate.c.
Referenced by ast_presence_state_topic_all().
presence_state_topic_cached
struct stasis_caching_topic* presence_state_topic_cached
Definition at line 91 of file presencestate.c.
presence_test_alice_state
int presence_test_alice_state = AST_PRESENCE_UNAVAILABLE static
Definition at line 395 of file presencestate.c.
Referenced by AST_TEST_DEFINE(), and presence_test_presencestate().
presence_test_bob_state
int presence_test_bob_state = AST_PRESENCE_UNAVAILABLE static
Definition at line 396 of file presencestate.c.
Referenced by AST_TEST_DEFINE(), and presence_test_presencestate().
presence_test_tech
struct ast_channel_tech presence_test_tech static
Initial value:
= {
   .type = "PresenceTestChannel",
   .description = "Presence test technology",
   .presencestate = presence_test_presencestate,
}
Definition at line 409 of file presencestate.c.
state
enum ast_presence_state state
Definition at line 72 of file presencestate.c.
Referenced by ast_presence_state_helper(), AST_TEST_DEFINE(), do_presence_state_change(), and presence_state_alloc().
state2string
const { ... } state2string[]
Device state strings for printing.
Referenced by ast_presence_state2str(), and ast_presence_state_val().
string
const char* string
Definition at line 71 of file presencestate.c.
Referenced by ast_escape_quoted(), ast_escape_semicolons(), AST_TEST_DEFINE(), ast_uri_encode(), ast_xml_escape(), nword(), and private_enum_init().