Asterisk - The Open Source Telephony Project: test_app.c File Reference
test_app.c File Reference
App unit test.
#include "asterisk.h"
#include "asterisk/utils.h"
#include "asterisk/module.h"
#include "asterisk/test.h"
#include "asterisk/app.h"
#include "asterisk/channel.h"
Macros
#define BASE_GROUP "a group"
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
AST_TEST_DEFINE (options_parsing)
AST_TEST_DEFINE (app_group)
static int load_module (void)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "App unit tests" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, }
static const struct ast_module_info * ast_module_info = &__mod_info
Detailed Description
App unit test.
Author
Jeff Peeler jpeel.nosp@m.er@d.nosp@m.igium.nosp@m..com
Definition in file test_app.c.
Macro Definition Documentation
BASE_GROUP
#define BASE_GROUP "a group"
Definition at line 40 of file test_app.c.
Referenced by AST_TEST_DEFINE().
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 238 of file test_app.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 238 of file test_app.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 238 of file test_app.c.
AST_TEST_DEFINE() [1/2]
AST_TEST_DEFINE (options_parsing)
Definition at line 42 of file test_app.c.
References ARRAY_LEN, AST_APP_OPTION_ARG, AST_APP_OPTIONS, ast_app_parse_options(), ast_app_parse_options64(), ast_copy_string(), AST_TEST_FAIL, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_test_status_update, sip_to_pjsip::info(), OPT_ARG_ARRAY_SIZE, options, parse(), string, TEST_EXECUTE, and TEST_INIT.
 {
    enum test_option_flags {
       OPT_SIMPLE,
       OPT_WITHQUOTES,
       OPT_WITHBACKSLASH,
    };
    enum test_option_args {
       OPT_ARG_SIMPLE,
       OPT_ARG_WITHQUOTES,
       OPT_ARG_WITHBACKSLASH,
       OPT_ARG_ARRAY_SIZE,
    };
    AST_APP_OPTIONS(test_options, {
       AST_APP_OPTION_ARG('a', OPT_SIMPLE,        OPT_ARG_SIMPLE),
       AST_APP_OPTION_ARG('b', OPT_WITHQUOTES,    OPT_ARG_WITHQUOTES),
       AST_APP_OPTION_ARG('c', OPT_WITHBACKSLASH, OPT_ARG_WITHBACKSLASH),
    });
    struct ast_flags opts = { 0, };
    struct ast_flags64 opts64 = { 0, };
    char *opt_args[OPT_ARG_ARRAY_SIZE];
    struct {
       const char *string;
       const char *parse[3];
    } options[] = {
       { "a(simple)b(\"quoted\")c(back\\slash)", { "simple", "quoted", "backslash", }, },
       { "b(\"((())))\")a(simple)c(back\\)slash)", { "simple", "((())))", "back)slash", }, },
       { "b(\"((\\\"\\)\\(\")a(simple)c(back\\\"\\)\\(\\\"slash)", { "simple", "((\"\\)\\(", "back\")(\"slash", }, },
    };
    int i, j, res = AST_TEST_PASS;
    char buffer[256];
    switch (cmd) {
    case TEST_INIT:
       info->name = "options_parsing";
       info->category = "/main/app/";
       info->summary = "App options unit test";
       info->description =
          "This tests the options parsing code to ensure that it behaves as expected";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    for (i = 0; i < ARRAY_LEN(options); i++) {
       ast_copy_string(buffer, options[i].string, sizeof(buffer));
       if (ast_app_parse_options(test_options, &opts, opt_args, buffer)) {
          ast_test_status_update(test, "ast_app_parse_options() of '%s' failed\n", options[i].string);
          res = AST_TEST_FAIL;
       } else {
          /* Check arguments for success */
          for (j = 0; j < 3; j++) {
             if (strcmp(opt_args[j], options[i].parse[j])) {
                ast_test_status_update(test, "Parse of option %c from '%s' produced '%s', "
                   "but it should have produced '%s'\n",
                   'a' + j, options[i].string, opt_args[j], options[i].parse[j]);
                res = AST_TEST_FAIL;
             }
          }
       }
       ast_copy_string(buffer, options[i].string, sizeof(buffer));
       if (ast_app_parse_options64(test_options, &opts64, opt_args, buffer)) {
          ast_test_status_update(test, "ast_app_parse_options64() of '%s' failed\n", options[i].string);
          res = AST_TEST_FAIL;
       } else {
          /* Check arguments for success */
          for (j = 0; j < 3; j++) {
             if (strcmp(opt_args[j], options[i].parse[j])) {
                ast_test_status_update(test, "Parse of option %c from '%s' produced '%s', "
                   "but it should have produced '%s'\n",
                   'a' + j, options[i].string, opt_args[j], options[i].parse[j]);
                res = AST_TEST_FAIL;
             }
          }
       }
    }
    return res;
 }
AST_TEST_DEFINE() [2/2]
AST_TEST_DEFINE (app_group)
Definition at line 124 of file test_app.c.
References ARRAY_LEN, ast_app_group_match_get_count(), ast_app_group_set_channel(), ast_assert, ast_channel_alloc, ast_channel_unlock, ast_hangup(), AST_STATE_DOWN, AST_TEST_FAIL, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_test_status_update, BASE_GROUP, sip_to_pjsip::info(), NULL, TEST_EXECUTE, and TEST_INIT.
 {
    struct ast_channel *test_channel1 = NULL;
    struct ast_channel *test_channel2 = NULL;
    struct ast_channel *test_channel3 = NULL;
    struct ast_channel *test_channel4 = NULL;
    static const char group1_full[] = BASE_GROUP "groupgroup";
    static const char group2_full[] = BASE_GROUP "Groupgroup";
    static const char regex1[] = "gr"; /* matches everything */
    static const char regex2[] = "(group){2}$"; /* matches only group1_full */
    static const char regex3[] = "[:ascii:]"; /* matches everything */
    static const char regex4[] = "^(NOMATCH)"; /* matches nothing */
    static const char category1_full[] = BASE_GROUP "@a_category"; /* categories shouldn't have spaces */
    static const char category2_full[] = BASE_GROUP "@another!Category";
    static const char regex5[] = "(gory)$"; /* matches both categories */
    static const char regex6[] = "[A-Z]+"; /* matches only category2_full */
    static const char regex7[] = "[["; /* not valid syntax, yes an expected warning will be displayed */
    static enum ast_test_result_state res = AST_TEST_PASS;
    static const struct group_test_params {
       const char *groupmatch;
       const char *category;
       int expected;
    } subtests[] = {
       { regex1, "", 4 },
       { regex2, "", 1 },
       { regex3, "", 4 },
       { regex4, "", 0 },
       { BASE_GROUP, regex5, 2 },
       { BASE_GROUP, regex6, 1 },
       /* this test is expected to generate a warning message from the invalid regex */
       { BASE_GROUP, regex7, 0 }
    };
    int i;
    int returned_count;
    switch (cmd) {
    case TEST_INIT:
       info->name = "app_group";
       info->category = "/main/app/";
       info->summary = "App group unit test";
       info->description =
          "This tests various app group functionality";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    ast_test_status_update(test, "Creating test channels with the following groups:\n"
       "'%s', '%s', '%s', '%s'\n", group1_full, group2_full, category1_full, category2_full);
    if (!(test_channel1 = ast_channel_alloc(0, AST_STATE_DOWN, NULL, NULL, NULL,
       NULL, NULL, NULL, NULL, 0, "TestChannel1"))) {
       goto exit_group_test;
    }
    ast_channel_unlock(test_channel1);
    if (!(test_channel2 = ast_channel_alloc(0, AST_STATE_DOWN, NULL, NULL, NULL,
       NULL, NULL, NULL, NULL, 0, "TestChannel2"))) {
       goto exit_group_test;
    }
    ast_channel_unlock(test_channel2);
    if (!(test_channel3 = ast_channel_alloc(0, AST_STATE_DOWN, NULL, NULL, NULL,
       NULL, NULL, NULL, NULL, 0, "TestChannel3"))) {
       goto exit_group_test;
    }
    ast_channel_unlock(test_channel3);
    if (!(test_channel4 = ast_channel_alloc(0, AST_STATE_DOWN, NULL, NULL, NULL,
       NULL, NULL, NULL, NULL, 0, "TestChannel4"))) {
       goto exit_group_test;
    }
    ast_channel_unlock(test_channel4);
    ast_app_group_set_channel(test_channel1, group1_full);
    ast_app_group_set_channel(test_channel2, group2_full);
    ast_app_group_set_channel(test_channel3, category1_full);
    ast_app_group_set_channel(test_channel4, category2_full);
    for (i = 0; i < ARRAY_LEN(subtests); i++) {
       ast_assert(subtests[i].groupmatch != NULL || subtests[i].category != NULL);
       returned_count = ast_app_group_match_get_count(subtests[i].groupmatch, subtests[i].category);
       if (subtests[i].expected != returned_count) {
          ast_test_status_update(test, "(Subtest %d) Expected %d matches but found %d when examining group:'%s' category:'%s'\n",
             i + 1, subtests[i].expected, returned_count, subtests[i].groupmatch, subtests[i].category);
          res = AST_TEST_FAIL;
          goto exit_group_test;
       } else {
          ast_test_status_update(test, "(Subtest %d) Found %d matches as expected when examining group:'%s' category:'%s'\n",
             i + 1, subtests[i].expected, subtests[i].groupmatch, subtests[i].category);
       }
    }
 exit_group_test:
    ast_hangup(test_channel1);
    ast_hangup(test_channel2);
    ast_hangup(test_channel3);
    ast_hangup(test_channel4);
    return res;
 }
load_module()
static int load_module (void) static
Definition at line 231 of file test_app.c.
References AST_MODULE_LOAD_SUCCESS, and AST_TEST_REGISTER.
 {
    AST_TEST_REGISTER(app_group);
    AST_TEST_REGISTER(options_parsing);
    return AST_MODULE_LOAD_SUCCESS;
 }
unload_module()
static int unload_module (void) static
Definition at line 224 of file test_app.c.
References AST_TEST_UNREGISTER.
 {
    AST_TEST_UNREGISTER(app_group);
    AST_TEST_UNREGISTER(options_parsing);
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "App unit tests" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, } static
Definition at line 238 of file test_app.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 238 of file test_app.c.