Asterisk - The Open Source Telephony Project: res_ari_endpoints.c File Reference
res_ari_endpoints.c File Reference
Endpoint resources.
#include "asterisk.h"
#include "asterisk/app.h"
#include "asterisk/module.h"
#include "asterisk/stasis_app.h"
#include "ari/resource_endpoints.h"
#include "ari/ari_model_validators.h"
Macros
#define MAX_VALS 128
Functions
static void __reg_module (void)
static void __unreg_module (void)
static void ast_ari_endpoints_get_cb (struct ast_tcptls_session_instance *ser, struct ast_variable *get_params, struct ast_variable *path_vars, struct ast_variable *headers, struct ast_json *body, struct ast_ari_response *response)
Parameter parsing callback for /endpoints/{tech}/{resource}.
static void ast_ari_endpoints_list_by_tech_cb (struct ast_tcptls_session_instance *ser, struct ast_variable *get_params, struct ast_variable *path_vars, struct ast_variable *headers, struct ast_json *body, struct ast_ari_response *response)
Parameter parsing callback for /endpoints/{tech}.
static void ast_ari_endpoints_list_cb (struct ast_tcptls_session_instance *ser, struct ast_variable *get_params, struct ast_variable *path_vars, struct ast_variable *headers, struct ast_json *body, struct ast_ari_response *response)
Parameter parsing callback for /endpoints.
static void ast_ari_endpoints_send_message_cb (struct ast_tcptls_session_instance *ser, struct ast_variable *get_params, struct ast_variable *path_vars, struct ast_variable *headers, struct ast_json *body, struct ast_ari_response *response)
Parameter parsing callback for /endpoints/sendMessage.
int ast_ari_endpoints_send_message_parse_body (struct ast_json *body, struct ast_ari_endpoints_send_message_args *args)
Body parsing function for /endpoints/sendMessage.
static void ast_ari_endpoints_send_message_to_endpoint_cb (struct ast_tcptls_session_instance *ser, struct ast_variable *get_params, struct ast_variable *path_vars, struct ast_variable *headers, struct ast_json *body, struct ast_ari_response *response)
Parameter parsing callback for /endpoints/{tech}/{resource}/sendMessage.
int ast_ari_endpoints_send_message_to_endpoint_parse_body (struct ast_json *body, struct ast_ari_endpoints_send_message_to_endpoint_args *args)
Body parsing function for /endpoints/{tech}/{resource}/sendMessage.
struct ast_module * AST_MODULE_SELF_SYM (void)
static int load_module (void)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_DEFAULT , .description = "RESTful API module - Endpoint resources" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .requires = "res_ari,res_ari_model,res_stasis", }
static const struct ast_module_info * ast_module_info = &__mod_info
static struct stasis_rest_handlers endpoints
REST handler for /api-docs/endpoints.json.
static struct stasis_rest_handlers endpoints_sendMessage
REST handler for /api-docs/endpoints.json.
static struct stasis_rest_handlers endpoints_tech
REST handler for /api-docs/endpoints.json.
static struct stasis_rest_handlers endpoints_tech_resource
REST handler for /api-docs/endpoints.json.
static struct stasis_rest_handlers endpoints_tech_resource_sendMessage
REST handler for /api-docs/endpoints.json.
Detailed Description
Endpoint resources.
Author
David M. Lee, II dlee@.nosp@m.digi.nosp@m.um.co.nosp@m.m
Definition in file res_ari_endpoints.c.
Macro Definition Documentation
MAX_VALS
#define MAX_VALS 128
Definition at line 51 of file res_ari_endpoints.c.
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 473 of file res_ari_endpoints.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 473 of file res_ari_endpoints.c.
ast_ari_endpoints_get_cb()
static void ast_ari_endpoints_get_cb (struct ast_tcptls_session_instance * ser, struct ast_variable * get_params, struct ast_variable * path_vars, struct ast_variable * headers, struct ast_json * body, struct ast_ari_response * response) static
Parameter parsing callback for /endpoints/{tech}/{resource}.
Parameters
get_params GET parameters in the HTTP request.
path_vars Path variables extracted from the request.
headers HTTP headers.
[out] response Response to the HTTP request.
Definition at line 255 of file res_ari_endpoints.c.
References ast_ari_endpoints_get(), ast_ari_response_error(), ast_ari_validate_endpoint(), ast_log, LOG_ERROR, ast_ari_response::message, ast_variable::name, ast_variable::next, NULL, ast_ari_endpoints_get_args::resource, ast_ari_response::response_code, ast_ari_endpoints_get_args::tech, and ast_variable::value.
 {
    struct ast_ari_endpoints_get_args args = {};
    struct ast_variable *i;
 #if defined(AST_DEVMODE)
    int is_valid;
    int code;
 #endif /* AST_DEVMODE */
    for (i = path_vars; i; i = i->next) {
       if (strcmp(i->name, "tech") == 0) {
          args.tech = (i->value);
       } else
       if (strcmp(i->name, "resource") == 0) {
          args.resource = (i->value);
       } else
       {}
    }
    ast_ari_endpoints_get(headers, &args, response);
 #if defined(AST_DEVMODE)
    code = response->response_code;
    switch (code) {
    case 0: /* Implementation is still a stub, or the code wasn't set */
       is_valid = response->message == NULL;
       break;
    case 500: /* Internal Server Error */
    case 501: /* Not Implemented */
    case 400: /* Invalid parameters for sending a message. */
    case 404: /* Endpoints not found */
       is_valid = 1;
       break;
    default:
       if (200 <= code && code <= 299) {
          is_valid = ast_ari_validate_endpoint(
             response->message);
       } else {
          ast_log(LOG_ERROR, "Invalid error response %d for /endpoints/{tech}/{resource}\n", code);
          is_valid = 0;
       }
    }
    if (!is_valid) {
       ast_log(LOG_ERROR, "Response validation failed for /endpoints/{tech}/{resource}\n");
       ast_ari_response_error(response, 500,
          "Internal Server Error", "Response validation failed");
    }
 #endif /* AST_DEVMODE */
 fin: __attribute__((unused))
    return;
 }
ast_ari_endpoints_list_by_tech_cb()
static void ast_ari_endpoints_list_by_tech_cb (struct ast_tcptls_session_instance * ser, struct ast_variable * get_params, struct ast_variable * path_vars, struct ast_variable * headers, struct ast_json * body, struct ast_ari_response * response) static
Parameter parsing callback for /endpoints/{tech}.
Parameters
get_params GET parameters in the HTTP request.
path_vars Path variables extracted from the request.
headers HTTP headers.
[out] response Response to the HTTP request.
Definition at line 197 of file res_ari_endpoints.c.
References ast_ari_endpoints_list_by_tech(), ast_ari_response_error(), ast_ari_validate_endpoint_fn(), ast_ari_validate_list(), ast_log, LOG_ERROR, ast_ari_response::message, ast_variable::name, ast_variable::next, NULL, ast_ari_response::response_code, ast_ari_endpoints_list_by_tech_args::tech, and ast_variable::value.
 {
    struct ast_ari_endpoints_list_by_tech_args args = {};
    struct ast_variable *i;
 #if defined(AST_DEVMODE)
    int is_valid;
    int code;
 #endif /* AST_DEVMODE */
    for (i = path_vars; i; i = i->next) {
       if (strcmp(i->name, "tech") == 0) {
          args.tech = (i->value);
       } else
       {}
    }
    ast_ari_endpoints_list_by_tech(headers, &args, response);
 #if defined(AST_DEVMODE)
    code = response->response_code;
    switch (code) {
    case 0: /* Implementation is still a stub, or the code wasn't set */
       is_valid = response->message == NULL;
       break;
    case 500: /* Internal Server Error */
    case 501: /* Not Implemented */
    case 404: /* Endpoints not found */
       is_valid = 1;
       break;
    default:
       if (200 <= code && code <= 299) {
          is_valid = ast_ari_validate_list(response->message,
             ast_ari_validate_endpoint_fn());
       } else {
          ast_log(LOG_ERROR, "Invalid error response %d for /endpoints/{tech}\n", code);
          is_valid = 0;
       }
    }
    if (!is_valid) {
       ast_log(LOG_ERROR, "Response validation failed for /endpoints/{tech}\n");
       ast_ari_response_error(response, 500,
          "Internal Server Error", "Response validation failed");
    }
 #endif /* AST_DEVMODE */
 fin: __attribute__((unused))
    return;
 }
ast_ari_endpoints_list_cb()
static void ast_ari_endpoints_list_cb (struct ast_tcptls_session_instance * ser, struct ast_variable * get_params, struct ast_variable * path_vars, struct ast_variable * headers, struct ast_json * body, struct ast_ari_response * response) static
Parameter parsing callback for /endpoints.
Parameters
get_params GET parameters in the HTTP request.
path_vars Path variables extracted from the request.
headers HTTP headers.
[out] response Response to the HTTP request.
Definition at line 60 of file res_ari_endpoints.c.
References ast_ari_endpoints_list(), ast_ari_response_error(), ast_ari_validate_endpoint_fn(), ast_ari_validate_list(), ast_log, LOG_ERROR, ast_ari_response::message, NULL, and ast_ari_response::response_code.
 {
    struct ast_ari_endpoints_list_args args = {};
 #if defined(AST_DEVMODE)
    int is_valid;
    int code;
 #endif /* AST_DEVMODE */
    ast_ari_endpoints_list(headers, &args, response);
 #if defined(AST_DEVMODE)
    code = response->response_code;
    switch (code) {
    case 0: /* Implementation is still a stub, or the code wasn't set */
       is_valid = response->message == NULL;
       break;
    case 500: /* Internal Server Error */
    case 501: /* Not Implemented */
       is_valid = 1;
       break;
    default:
       if (200 <= code && code <= 299) {
          is_valid = ast_ari_validate_list(response->message,
             ast_ari_validate_endpoint_fn());
       } else {
          ast_log(LOG_ERROR, "Invalid error response %d for /endpoints\n", code);
          is_valid = 0;
       }
    }
    if (!is_valid) {
       ast_log(LOG_ERROR, "Response validation failed for /endpoints\n");
       ast_ari_response_error(response, 500,
          "Internal Server Error", "Response validation failed");
    }
 #endif /* AST_DEVMODE */
 fin: __attribute__((unused))
    return;
 }
ast_ari_endpoints_send_message_cb()
static void ast_ari_endpoints_send_message_cb (struct ast_tcptls_session_instance * ser, struct ast_variable * get_params, struct ast_variable * path_vars, struct ast_variable * headers, struct ast_json * body, struct ast_ari_response * response) static
Parameter parsing callback for /endpoints/sendMessage.
Parameters
get_params GET parameters in the HTTP request.
path_vars Path variables extracted from the request.
headers HTTP headers.
[out] response Response to the HTTP request.
Definition at line 131 of file res_ari_endpoints.c.
References ast_ari_endpoints_send_message(), ast_ari_response_error(), ast_ari_validate_void(), ast_log, ast_ari_endpoints_send_message_args::body, ast_ari_endpoints_send_message_args::from, LOG_ERROR, ast_ari_response::message, ast_variable::name, ast_variable::next, NULL, ast_ari_response::response_code, ast_ari_endpoints_send_message_args::to, ast_variable::value, and ast_ari_endpoints_send_message_args::variables.
 {
    struct ast_ari_endpoints_send_message_args args = {};
    struct ast_variable *i;
 #if defined(AST_DEVMODE)
    int is_valid;
    int code;
 #endif /* AST_DEVMODE */
    for (i = get_params; i; i = i->next) {
       if (strcmp(i->name, "to") == 0) {
          args.to = (i->value);
       } else
       if (strcmp(i->name, "from") == 0) {
          args.from = (i->value);
       } else
       if (strcmp(i->name, "body") == 0) {
          args.body = (i->value);
       } else
       {}
    }
    args.variables = body;
    ast_ari_endpoints_send_message(headers, &args, response);
 #if defined(AST_DEVMODE)
    code = response->response_code;
    switch (code) {
    case 0: /* Implementation is still a stub, or the code wasn't set */
       is_valid = response->message == NULL;
       break;
    case 500: /* Internal Server Error */
    case 501: /* Not Implemented */
    case 400: /* Invalid parameters for sending a message. */
    case 404: /* Endpoint not found */
       is_valid = 1;
       break;
    default:
       if (200 <= code && code <= 299) {
          is_valid = ast_ari_validate_void(
             response->message);
       } else {
          ast_log(LOG_ERROR, "Invalid error response %d for /endpoints/sendMessage\n", code);
          is_valid = 0;
       }
    }
    if (!is_valid) {
       ast_log(LOG_ERROR, "Response validation failed for /endpoints/sendMessage\n");
       ast_ari_response_error(response, 500,
          "Internal Server Error", "Response validation failed");
    }
 #endif /* AST_DEVMODE */
 fin: __attribute__((unused))
    return;
 }
ast_ari_endpoints_send_message_parse_body()
int ast_ari_endpoints_send_message_parse_body (struct ast_json * body, struct ast_ari_endpoints_send_message_args * args)
Body parsing function for /endpoints/sendMessage.
Parameters
body The JSON body from which to parse parameters.
[out] args The args structure to parse into.
Return values
zero on success
non-zero on failure
Definition at line 103 of file res_ari_endpoints.c.
References ast_json_object_get(), ast_json_string_get(), ast_ari_endpoints_send_message_args::body, ast_ari_endpoints_send_message_args::from, and ast_ari_endpoints_send_message_args::to.
Referenced by ast_ari_endpoints_send_message().
 {
    struct ast_json *field;
    /* Parse query parameters out of it */
    field = ast_json_object_get(body, "to");
    if (field) {
       args->to = ast_json_string_get(field);
    }
    field = ast_json_object_get(body, "from");
    if (field) {
       args->from = ast_json_string_get(field);
    }
    field = ast_json_object_get(body, "body");
    if (field) {
       args->body = ast_json_string_get(field);
    }
    return 0;
 }
ast_ari_endpoints_send_message_to_endpoint_cb()
static void ast_ari_endpoints_send_message_to_endpoint_cb (struct ast_tcptls_session_instance * ser, struct ast_variable * get_params, struct ast_variable * path_vars, struct ast_variable * headers, struct ast_json * body, struct ast_ari_response * response) static
Parameter parsing callback for /endpoints/{tech}/{resource}/sendMessage.
Parameters
get_params GET parameters in the HTTP request.
path_vars Path variables extracted from the request.
headers HTTP headers.
[out] response Response to the HTTP request.
Definition at line 334 of file res_ari_endpoints.c.
References ast_ari_endpoints_send_message_to_endpoint(), ast_ari_response_error(), ast_ari_validate_void(), ast_log, ast_ari_endpoints_send_message_to_endpoint_args::body, ast_ari_endpoints_send_message_to_endpoint_args::from, LOG_ERROR, ast_ari_response::message, ast_variable::name, ast_variable::next, NULL, ast_ari_endpoints_send_message_to_endpoint_args::resource, ast_ari_response::response_code, ast_ari_endpoints_send_message_to_endpoint_args::tech, ast_variable::value, and ast_ari_endpoints_send_message_to_endpoint_args::variables.
 {
    struct ast_ari_endpoints_send_message_to_endpoint_args args = {};
    struct ast_variable *i;
 #if defined(AST_DEVMODE)
    int is_valid;
    int code;
 #endif /* AST_DEVMODE */
    for (i = get_params; i; i = i->next) {
       if (strcmp(i->name, "from") == 0) {
          args.from = (i->value);
       } else
       if (strcmp(i->name, "body") == 0) {
          args.body = (i->value);
       } else
       {}
    }
    for (i = path_vars; i; i = i->next) {
       if (strcmp(i->name, "tech") == 0) {
          args.tech = (i->value);
       } else
       if (strcmp(i->name, "resource") == 0) {
          args.resource = (i->value);
       } else
       {}
    }
    args.variables = body;
    ast_ari_endpoints_send_message_to_endpoint(headers, &args, response);
 #if defined(AST_DEVMODE)
    code = response->response_code;
    switch (code) {
    case 0: /* Implementation is still a stub, or the code wasn't set */
       is_valid = response->message == NULL;
       break;
    case 500: /* Internal Server Error */
    case 501: /* Not Implemented */
    case 400: /* Invalid parameters for sending a message. */
    case 404: /* Endpoint not found */
       is_valid = 1;
       break;
    default:
       if (200 <= code && code <= 299) {
          is_valid = ast_ari_validate_void(
             response->message);
       } else {
          ast_log(LOG_ERROR, "Invalid error response %d for /endpoints/{tech}/{resource}/sendMessage\n", code);
          is_valid = 0;
       }
    }
    if (!is_valid) {
       ast_log(LOG_ERROR, "Response validation failed for /endpoints/{tech}/{resource}/sendMessage\n");
       ast_ari_response_error(response, 500,
          "Internal Server Error", "Response validation failed");
    }
 #endif /* AST_DEVMODE */
 fin: __attribute__((unused))
    return;
 }
ast_ari_endpoints_send_message_to_endpoint_parse_body()
int ast_ari_endpoints_send_message_to_endpoint_parse_body (struct ast_json * body, struct ast_ari_endpoints_send_message_to_endpoint_args * args)
Body parsing function for /endpoints/{tech}/{resource}/sendMessage.
Parameters
body The JSON body from which to parse parameters.
[out] args The args structure to parse into.
Return values
zero on success
non-zero on failure
Definition at line 310 of file res_ari_endpoints.c.
References ast_json_object_get(), ast_json_string_get(), ast_ari_endpoints_send_message_to_endpoint_args::body, and ast_ari_endpoints_send_message_to_endpoint_args::from.
Referenced by ast_ari_endpoints_send_message_to_endpoint().
 {
    struct ast_json *field;
    /* Parse query parameters out of it */
    field = ast_json_object_get(body, "from");
    if (field) {
       args->from = ast_json_string_get(field);
    }
    field = ast_json_object_get(body, "body");
    if (field) {
       args->body = ast_json_string_get(field);
    }
    return 0;
 }
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 473 of file res_ari_endpoints.c.
load_module()
static int load_module (void) static
Definition at line 454 of file res_ari_endpoints.c.
References ast_ari_add_handler(), AST_MODFLAG_DEFAULT, AST_MODULE_INFO(), AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, AST_MODULE_SUPPORT_CORE, ASTERISK_GPL_KEY, and unload_module().
 {
    int res = 0;
    res |= ast_ari_add_handler(&endpoints);
    if (res) {
       unload_module();
       return AST_MODULE_LOAD_DECLINE;
    }
    return AST_MODULE_LOAD_SUCCESS;
 }
unload_module()
static int unload_module (void) static
Definition at line 448 of file res_ari_endpoints.c.
References ast_ari_remove_handler().
Referenced by load_module().
 {
    ast_ari_remove_handler(&endpoints);
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_DEFAULT , .description = "RESTful API module - Endpoint resources" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .requires = "res_ari,res_ari_model,res_stasis", } static
Definition at line 473 of file res_ari_endpoints.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 473 of file res_ari_endpoints.c.
endpoints
struct stasis_rest_handlers endpoints static
REST handler for /api-docs/endpoints.json.
Definition at line 439 of file res_ari_endpoints.c.
endpoints_sendMessage
struct stasis_rest_handlers endpoints_sendMessage static
REST handler for /api-docs/endpoints.json.
Definition at line 401 of file res_ari_endpoints.c.
endpoints_tech
struct stasis_rest_handlers endpoints_tech static
REST handler for /api-docs/endpoints.json.
Definition at line 429 of file res_ari_endpoints.c.
endpoints_tech_resource
struct stasis_rest_handlers endpoints_tech_resource static
REST handler for /api-docs/endpoints.json.
Definition at line 419 of file res_ari_endpoints.c.
endpoints_tech_resource_sendMessage
struct stasis_rest_handlers endpoints_tech_resource_sendMessage static
REST handler for /api-docs/endpoints.json.
Definition at line 410 of file res_ari_endpoints.c.