Asterisk - The Open Source Telephony Project: musiconhold.h File Reference
musiconhold.h File Reference
Music on hold handling.
Functions
void ast_install_music_functions (int(*start_ptr)(struct ast_channel *, const char *, const char *), void(*stop_ptr)(struct ast_channel *), void(*cleanup_ptr)(struct ast_channel *))
void ast_moh_cleanup (struct ast_channel *chan)
int ast_moh_start (struct ast_channel *chan, const char *mclass, const char *interpclass)
Turn on music on hold on a given channel.
void ast_moh_stop (struct ast_channel *chan)
Turn off music on hold on a given channel.
void ast_uninstall_music_functions (void)
Detailed Description
Music on hold handling.
Definition in file musiconhold.h.
Function Documentation
ast_install_music_functions()
void ast_install_music_functions (int(*)(struct ast_channel *, const char *, const char *) start_ptr, void(*)(struct ast_channel *) stop_ptr, void(*)(struct ast_channel *) cleanup_ptr)
Definition at line 7850 of file channel.c.
References ast_moh_cleanup_ptr, ast_moh_start_ptr, and ast_moh_stop_ptr.
Referenced by load_module(), and reload().
 {
    ast_moh_start_ptr = start_ptr;
    ast_moh_stop_ptr = stop_ptr;
    ast_moh_cleanup_ptr = cleanup_ptr;
 }
ast_moh_cleanup()
void ast_moh_cleanup (struct ast_channel * chan)
Definition at line 7882 of file channel.c.
References ast_moh_cleanup_ptr.
Referenced by ast_channel_destructor().
 {
    if (ast_moh_cleanup_ptr)
       ast_moh_cleanup_ptr(chan);
 }
ast_moh_start()
int ast_moh_start (struct ast_channel * chan, const char * mclass, const char * interpclass)
Turn on music on hold on a given channel.
Parameters
chan The channel structure that will get music on hold
mclass The class to use if the musicclass is not currently set on the channel structure. NULL and the empty string are equivalent.
interpclass The class to use if the musicclass is not currently set on the channel structure or in the mclass argument. NULL and the empty string are equivalent.
Return values
Zero on success
non-zero on failure
Definition at line 7866 of file channel.c.
References ast_moh_start_ptr, and ast_verb.
Referenced by alsa_indicate(), app_control_moh_start(), app_exec(), ast_ari_bridges_start_moh(), ast_bridge_channel_playfile(), ast_unreal_indicate(), chan_pjsip_indicate(), channel_do_masquerade(), conf_moh_start(), conf_moh_unsuspend(), conf_start_moh(), console_indicate(), dahdi_indicate(), dial_exec_full(), handle_setmusic(), iax2_indicate(), jingle_indicate(), limits_interval_playback(), mgcp_indicate(), misdn_indication(), moh_handle_digit(), monitor_dial(), ooh323_indicate(), oss_indicate(), participant_entertainment_start(), phone_indicate(), play_moh_exec(), queue_exec(), retrydial_exec(), rna(), say_periodic_announcement(), say_position(), sip_indicate(), skinny_indicate(), start_moh_exec(), unistim_indicate(), and valid_priv_reply().
 {
    if (ast_moh_start_ptr)
       return ast_moh_start_ptr(chan, mclass, interpclass);
    ast_verb(3, "Music class %s requested but no musiconhold loaded.\n", mclass ? mclass : (interpclass ? interpclass : "default"));
    return -1;
 }
ast_moh_stop()
void ast_moh_stop (struct ast_channel * chan)
Turn off music on hold on a given channel.
Definition at line 7876 of file channel.c.
References ast_moh_stop_ptr.
Referenced by alsa_indicate(), app_control_moh_stop(), app_exec(), ast_bridge_add_channel(), ast_unreal_indicate(), chan_pjsip_indicate(), channel_do_masquerade(), conf_moh_stop(), conf_moh_suspend(), conf_run(), console_indicate(), dahdi_indicate(), dial_exec_full(), handle_setmusic(), iax2_indicate(), jingle_indicate(), mgcp_indicate(), misdn_indication(), moh_channel_thread(), moh_handle_digit(), monitor_dial(), ooh323_indicate(), oss_indicate(), participant_entertainment_stop(), phone_indicate(), play_moh_exec(), queue_exec(), retrydial_exec(), say_periodic_announcement(), say_position(), sip_indicate(), skinny_indicate(), stasis_app_bridge_moh_stop(), stop_moh_exec(), try_calling(), unistim_indicate(), valid_priv_reply(), and wait_for_answer().
 {
    if (ast_moh_stop_ptr)
       ast_moh_stop_ptr(chan);
 }
ast_uninstall_music_functions()
void ast_uninstall_music_functions (void)
Definition at line 7859 of file channel.c.
References ast_moh_cleanup_ptr, ast_moh_start_ptr, ast_moh_stop_ptr, and NULL.
Referenced by unload_module().
 {
    ast_moh_start_ptr = NULL;
    ast_moh_stop_ptr = NULL;
    ast_moh_cleanup_ptr = NULL;
 }