Asterisk - The Open Source Telephony Project: rec_close.c File Reference
rec_close.c File Reference
#include <sys/types.h>
#include <sys/uio.h>
#include <sys/mman.h>
#include <errno.h>
#include <limits.h>
#include <stdio.h>
#include <unistd.h>
#include "../include/db.h"
#include "recno.h"
Functions
int __rec_close (DB *dbp)
int __rec_sync (DB *dbp, u_int flags) const
Function Documentation
__rec_close()
int __rec_close (DB * dbp)
Definition at line 60 of file rec_close.c.
References __bt_close(), __rec_sync(), _btree::bt_mp, _btree::bt_msize, _btree::bt_pinned, _btree::bt_rfd, _btree::bt_rfp, _btree::bt_smap, F_ISSET, __db::internal, mpool_put(), NULL, R_CLOSEFP, R_INMEM, R_MEMMAPPED, RET_ERROR, RET_SUCCESS, and status.
Referenced by __rec_open().
 {
    BTREE *t;
    int status;
    t = dbp->internal;
    /* Toss any page pinned across calls. */
    if (t->bt_pinned != NULL) {
       mpool_put(t->bt_mp, t->bt_pinned, 0);
       t->bt_pinned = NULL;
    }
    if (__rec_sync(dbp, 0) == RET_ERROR)
       return (RET_ERROR);
    /* Committed to closing. */
    status = RET_SUCCESS;
    if (F_ISSET(t, R_MEMMAPPED) && munmap(t->bt_smap, t->bt_msize))
       status = RET_ERROR;
    if (!F_ISSET(t, R_INMEM)) {
       if (F_ISSET(t, R_CLOSEFP)) {
          if (fclose(t->bt_rfp))
             status = RET_ERROR;
       } else
          if (close(t->bt_rfd))
             status = RET_ERROR;
    }
    if (__bt_close(dbp) == RET_ERROR)
       status = RET_ERROR;
    return (status);
 }
__rec_sync()
int __rec_sync (DB * dbp, u_int flags) const
Definition at line 107 of file rec_close.c.
References __bt_sync(), DBT::data, F_CLR, F_ISSET, __db::internal, MAX_REC_NUMBER, mpool_put(), NULL, R_EOF, R_FIRST, R_FIXLEN, R_INMEM, R_MODIFIED, R_NEXT, R_RDONLY, R_RECNOSYNC, RET_ERROR, RET_SUCCESS, DBT::size, and status.
Referenced by __rec_close(), and __rec_open().
 {
    struct iovec iov[2];
    BTREE *t;
    DBT data, key;
    off_t off;
    recno_t scursor, trec;
    int status;
    t = dbp->internal;
    /* Toss any page pinned across calls. */
    if (t->bt_pinned != NULL) {
       mpool_put(t->bt_mp, t->bt_pinned, 0);
       t->bt_pinned = NULL;
    }
    if (flags == R_RECNOSYNC)
       return (__bt_sync(dbp, 0));
    if (F_ISSET(t, R_RDONLY | R_INMEM) || !F_ISSET(t, R_MODIFIED))
       return (RET_SUCCESS);
    /* Read any remaining records into the tree. */
    if (!F_ISSET(t, R_EOF) && t->bt_irec(t, MAX_REC_NUMBER) == RET_ERROR)
       return (RET_ERROR);
    /* Rewind the file descriptor. */
    if (lseek(t->bt_rfd, (off_t)0, SEEK_SET) != 0)
       return (RET_ERROR);
    /* Save the cursor. */
    scursor = t->bt_cursor.rcursor;
    key.size = sizeof(recno_t);
    key.data = &trec;
    if (F_ISSET(t, R_FIXLEN)) {
       /*
        * We assume that fixed length records are all fixed length.
        * Any that aren't are either EINVAL'd or corrected by the
        * record put code.
        */
       status = (dbp->seq)(dbp, &key, &data, R_FIRST);
       while (status == RET_SUCCESS) {
          if ((size_t) write(t->bt_rfd, data.data, data.size) != data.size)
             return (RET_ERROR);
          status = (dbp->seq)(dbp, &key, &data, R_NEXT);
       }
    } else {
       iov[1].iov_base = &t->bt_bval;
       iov[1].iov_len = 1;
       status = (dbp->seq)(dbp, &key, &data, R_FIRST);
       while (status == RET_SUCCESS) {
          iov[0].iov_base = data.data;
          iov[0].iov_len = data.size;
          if ((size_t) writev(t->bt_rfd, iov, 2) != data.size + 1)
             return (RET_ERROR);
          status = (dbp->seq)(dbp, &key, &data, R_NEXT);
       }
    }
    /* Restore the cursor. */
    t->bt_cursor.rcursor = scursor;
    if (status == RET_ERROR)
       return (RET_ERROR);
    if ((off = lseek(t->bt_rfd, (off_t)0, SEEK_CUR)) == -1)
       return (RET_ERROR);
    if (ftruncate(t->bt_rfd, off))
       return (RET_ERROR);
    F_CLR(t, R_MODIFIED);
    return (RET_SUCCESS);
 }