Asterisk - The Open Source Telephony Project: internal.h File Reference
internal.h File Reference
Internal API's for res_ari.
#include "asterisk/http.h"
#include "asterisk/json.h"
#include "asterisk/stringfields.h"
Data Structures
struct ast_ari_conf
All configuration options for ARI.
struct ast_ari_conf_general
Global configuration options for ARI.
struct ast_ari_conf_user
Per-user configuration options.
Functions
void ari_handle_websocket (struct ast_websocket_server *ws_server, struct ast_tcptls_session_instance *ser, const char *uri, enum ast_http_method method, struct ast_variable *get_params, struct ast_variable *headers)
Wrapper for invoking the websocket code for an incoming connection.
int ast_ari_cli_register (void)
Register CLI commands for ARI.
void ast_ari_cli_unregister (void)
Unregister CLI commands for ARI.
#define ARI_AUTH_REALM_LEN 80
#define ARI_PASSWORD_LEN 256
User's password mx length.
enum ast_ari_password_format { ARI_PASSWORD_FORMAT_PLAIN, ARI_PASSWORD_FORMAT_CRYPT }
Password format.
int ast_ari_config_init (void)
Initialize the ARI configuration.
int ast_ari_config_reload (void)
Reload the ARI configuration.
void ast_ari_config_destroy (void)
Destroy the ARI configuration.
struct ast_ari_conf * ast_ari_config_get (void)
Get the current ARI configuration.
struct ast_ari_conf_user * ast_ari_config_validate_user (const char *username, const char *password)
Validated a user's credentials.
Detailed Description
Internal API's for res_ari.
Author
David M. Lee, II dlee@.nosp@m.digi.nosp@m.um.co.nosp@m.m
Definition in file internal.h.
Macro Definition Documentation
ARI_AUTH_REALM_LEN
#define ARI_AUTH_REALM_LEN 80
Max length for auth_realm field
Definition at line 62 of file internal.h.
Referenced by ast_ari_config_init().
ARI_PASSWORD_LEN
#define ARI_PASSWORD_LEN 256
User's password mx length.
If 256 seems like a lot, a crypt SHA-512 has over 106 characters.
Definition at line 93 of file internal.h.
Referenced by ast_ari_config_init().
Enumeration Type Documentation
ast_ari_password_format
enum ast_ari_password_format
Password format.
Enumerator
ARI_PASSWORD_FORMAT_PLAIN
Plaintext password.
ARI_PASSWORD_FORMAT_CRYPT
crypt(3) password
Definition at line 81 of file internal.h.
{
    /*! \brief Plaintext password */
    ARI_PASSWORD_FORMAT_PLAIN,
    /*! crypt(3) password */
    ARI_PASSWORD_FORMAT_CRYPT,
 };
Function Documentation
ari_handle_websocket()
void ari_handle_websocket (struct ast_websocket_server * ws_server, struct ast_tcptls_session_instance * ser, const char * uri, enum ast_http_method method, struct ast_variable * get_params, struct ast_variable * headers)
Wrapper for invoking the websocket code for an incoming connection.
Parameters
ws_server WebSocket server to invoke.
ser HTTP session.
uri Requested URI.
method Requested HTTP method.
get_params Parsed query parameters.
headers Parsed HTTP headers.
Definition at line 191 of file ari_websockets.c.
References ast_websocket_uri_cb(), and ast_http_uri::data.
Referenced by ast_ari_invoke().
 {
    struct ast_http_uri fake_urih = {
       .data = ws_server,
    };
    ast_websocket_uri_cb(ser, &fake_urih, uri, method, get_params,
       headers);
 }
ast_ari_cli_register()
int ast_ari_cli_register (void)
Register CLI commands for ARI.
Returns
0 on success.
Non-zero on error.
Definition at line 434 of file res/ari/cli.c.
References ARRAY_LEN, and ast_cli_register_multiple.
Referenced by load_module().
{
    return ast_cli_register_multiple(cli_ari, ARRAY_LEN(cli_ari));
 }
ast_ari_cli_unregister()
void ast_ari_cli_unregister (void)
Unregister CLI commands for ARI.
Definition at line 438 of file res/ari/cli.c.
References ARRAY_LEN, and ast_cli_unregister_multiple().
Referenced by unload_module().
{
    ast_cli_unregister_multiple(cli_ari, ARRAY_LEN(cli_ari));
 }
ast_ari_config_destroy()
void ast_ari_config_destroy (void)
Destroy the ARI configuration.
Definition at line 383 of file res/ari/config.c.
References aco_info_destroy(), and ao2_global_obj_release.
Referenced by unload_module().
 {
    aco_info_destroy(&cfg_info);
    ao2_global_obj_release(confs);
 }
ast_ari_config_get()
struct ast_ari_conf* ast_ari_config_get (void)
Get the current ARI configuration.
This is an immutable object, so don't modify it. It is AO2 managed, so ao2_cleanup() when you're done with it.
Returns
ARI configuration object.
NULL on error.
Definition at line 227 of file res/ari/config.c.
References ao2_global_obj_ref, ast_log, CONF_FILENAME, and LOG_ERROR.
Referenced by ari_show(), ari_show_user(), ari_show_users(), ast_ari_callback(), ast_ari_config_validate_user(), ast_ari_json_format(), ast_ari_websocket_session_create(), complete_ari_user(), is_enabled(), origin_allowed(), and process_config().
 {
    struct ast_ari_conf *res = ao2_global_obj_ref(confs);
    if (!res) {
       ast_log(LOG_ERROR,
          "Error obtaining config from " CONF_FILENAME "\n");
    }
    return res;
 }
ast_ari_config_init()
int ast_ari_config_init (void)
Initialize the ARI configuration.
Definition at line 337 of file res/ari/config.c.
References ACO_EXACT, aco_info_destroy(), aco_info_init(), aco_option_register, aco_option_register_custom, ARI_AUTH_REALM_LEN, ARI_PASSWORD_LEN, AST_DEFAULT_WEBSOCKET_WRITE_TIMEOUT_STR, channelvars_handler(), enabled, encoding_format_handler(), FLDSET, NULL, OPT_BOOL_T, OPT_CHAR_ARRAY_T, OPT_INT_T, OPT_NOOP_T, OPT_STRINGFIELD_T, PARSE_IN_RANGE, password, password_format_handler(), process_config(), ast_ari_conf_user::read_only, and STRFLDSET.
Referenced by load_module().
 {
    if (aco_info_init(&cfg_info)) {
       aco_info_destroy(&cfg_info);
       return -1;
    }
    /* ARI general category options */
    aco_option_register(&cfg_info, "enabled", ACO_EXACT, general_options,
       "yes", OPT_BOOL_T, 1,
       FLDSET(struct ast_ari_conf_general, enabled));
    aco_option_register_custom(&cfg_info, "pretty", ACO_EXACT,
       general_options, "no",  encoding_format_handler, 0);
    aco_option_register(&cfg_info, "auth_realm", ACO_EXACT, general_options,
       "Asterisk REST Interface", OPT_CHAR_ARRAY_T, 0,
       FLDSET(struct ast_ari_conf_general, auth_realm),
       ARI_AUTH_REALM_LEN);
    aco_option_register(&cfg_info, "allowed_origins", ACO_EXACT, general_options,
       "", OPT_STRINGFIELD_T, 0,
       STRFLDSET(struct ast_ari_conf_general, allowed_origins));
    aco_option_register(&cfg_info, "websocket_write_timeout", ACO_EXACT, general_options,
       AST_DEFAULT_WEBSOCKET_WRITE_TIMEOUT_STR, OPT_INT_T, PARSE_IN_RANGE,
       FLDSET(struct ast_ari_conf_general, write_timeout), 1, INT_MAX);
    aco_option_register_custom(&cfg_info, "channelvars", ACO_EXACT, general_options,
       "", channelvars_handler, 0);
    /* ARI type=user category options */
    aco_option_register(&cfg_info, "type", ACO_EXACT, global_user, NULL,
       OPT_NOOP_T, 0, 0);
    aco_option_register(&cfg_info, "read_only", ACO_EXACT, global_user,
       "no", OPT_BOOL_T, 1,
       FLDSET(struct ast_ari_conf_user, read_only));
    aco_option_register(&cfg_info, "password", ACO_EXACT, global_user,
       "", OPT_CHAR_ARRAY_T, 0,
       FLDSET(struct ast_ari_conf_user, password), ARI_PASSWORD_LEN);
    aco_option_register_custom(&cfg_info, "password_format", ACO_EXACT,
       global_user, "plain",  password_format_handler, 0);
    return process_config(0);
 }
ast_ari_config_reload()
int ast_ari_config_reload (void)
Reload the ARI configuration.
Definition at line 378 of file res/ari/config.c.
References process_config().
Referenced by reload_module().
 {
    return process_config(1);
 }
ast_ari_config_validate_user()
struct ast_ari_conf_user* ast_ari_config_validate_user (const char * username, const char * password)
Validated a user's credentials.
Parameters
username Name of the user.
password User's password.
Returns
User object.
NULL if username or password is invalid.
Definition at line 237 of file res/ari/config.c.
References ao2_cleanup, ao2_find, ao2_ref, ARI_PASSWORD_FORMAT_CRYPT, ARI_PASSWORD_FORMAT_PLAIN, ast_ari_config_get(), ast_crypt_validate(), ast_log, ast_strlen_zero, LOG_WARNING, NULL, OBJ_SEARCH_KEY, RAII_VAR, and user.
Referenced by authenticate_api_key(), and authenticate_user().
 {
    RAII_VAR(struct ast_ari_conf *, conf, NULL, ao2_cleanup);
    RAII_VAR(struct ast_ari_conf_user *, user, NULL, ao2_cleanup);
    int is_valid = 0;
    conf = ast_ari_config_get();
    if (!conf) {
       return NULL;
    }
    user = ao2_find(conf->users, username, OBJ_SEARCH_KEY);
    if (!user) {
       return NULL;
    }
    if (ast_strlen_zero(user->password)) {
       ast_log(LOG_WARNING,
          "User '%s' missing password; authentication failed\n",
          user->username);
       return NULL;
    }
    switch (user->password_format) {
    case ARI_PASSWORD_FORMAT_PLAIN:
       is_valid = strcmp(password, user->password) == 0;
       break;
    case ARI_PASSWORD_FORMAT_CRYPT:
       is_valid = ast_crypt_validate(password, user->password);
       break;
    }
    if (!is_valid) {
       return NULL;
    }
    ao2_ref(user, +1);
    return user;
 }