Asterisk - The Open Source Telephony Project: res_pjsip_dlg_options.c File Reference
res_pjsip_dlg_options.c File Reference
#include "asterisk.h"
#include <pjsip.h>
#include <pjsip_ua.h>
#include <pjlib.h>
#include "asterisk/module.h"
#include "asterisk/res_pjsip.h"
#include "asterisk/res_pjsip_session.h"
Macros
#define DEFAULT_ENCODING "identity"
#define DEFAULT_LANGUAGE "en"
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int load_module (void)
static int options_incoming_request (struct ast_sip_session *session, pjsip_rx_data *rdata)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "SIP OPTIONS in dialog handler" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_APP_DEPEND, .requires = "res_pjsip,res_pjsip_session", }
static const struct ast_module_info * ast_module_info = &__mod_info
static struct ast_sip_session_supplement dlg_options_supplement
Macro Definition Documentation
DEFAULT_ENCODING
#define DEFAULT_ENCODING "identity"
Definition at line 37 of file res_pjsip_dlg_options.c.
Referenced by options_incoming_request().
DEFAULT_LANGUAGE
#define DEFAULT_LANGUAGE "en"
Definition at line 36 of file res_pjsip_dlg_options.c.
Referenced by options_incoming_request().
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 104 of file res_pjsip_dlg_options.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 104 of file res_pjsip_dlg_options.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 104 of file res_pjsip_dlg_options.c.
load_module()
static int load_module (void) static
Definition at line 85 of file res_pjsip_dlg_options.c.
References AST_MODULE_LOAD_SUCCESS, and ast_sip_session_register_supplement.
Referenced by unload_module().
 {
    ast_sip_session_register_supplement(&dlg_options_supplement);
    return AST_MODULE_LOAD_SUCCESS;
 }
options_incoming_request()
static int options_incoming_request (struct ast_sip_session * session, pjsip_rx_data * rdata) static
Definition at line 39 of file res_pjsip_dlg_options.c.
References ast_log, ast_sip_add_header(), ast_sip_get_pjsip_endpoint(), DEFAULT_ENCODING, DEFAULT_LANGUAGE, ast_sip_session::inv_session, LOG_ERROR, NULL, and status.
 {
    pjsip_tx_data *tdata;
         pj_status_t status;
    const pjsip_hdr *hdr;
    pjsip_endpoint *endpt = ast_sip_get_pjsip_endpoint();
    status = pjsip_dlg_create_response(session->inv_session->dlg, rdata, 200, NULL,&tdata);
    if (status != PJ_SUCCESS) {
       ast_log(LOG_ERROR, "Unable to create response (%d)\n", status);
       return status;
    }
    /* Add appropriate headers */
    if ((hdr = pjsip_endpt_get_capability(endpt, PJSIP_H_ACCEPT, NULL))) {
       pjsip_msg_add_hdr(tdata->msg, (pjsip_hdr*)pjsip_hdr_clone(tdata->pool, hdr));
    }
    if ((hdr = pjsip_endpt_get_capability(endpt, PJSIP_H_ALLOW, NULL))) {
       pjsip_msg_add_hdr(tdata->msg, (pjsip_hdr*)pjsip_hdr_clone(tdata->pool, hdr));
    }
    if ((hdr = pjsip_endpt_get_capability(endpt, PJSIP_H_SUPPORTED, NULL))) {
       pjsip_msg_add_hdr(tdata->msg, (pjsip_hdr*)pjsip_hdr_clone(tdata->pool, hdr));
    }
    /*
     * XXX TODO: pjsip doesn't care a lot about either of these headers -
     * while it provides specific methods to create them, they are defined
     * to be the standard string header creation. We never did add them
     * in chan_sip, although RFC 3261 says they SHOULD. Hard coded here.
    */
    ast_sip_add_header(tdata, "Accept-Encoding", DEFAULT_ENCODING);
    ast_sip_add_header(tdata, "Accept-Language", DEFAULT_LANGUAGE);
    status = pjsip_dlg_send_response(session->inv_session->dlg, pjsip_rdata_get_tsx(rdata), tdata);
    if (status != PJ_SUCCESS) {
       ast_log(LOG_ERROR, "Unable to send response (%d)\n", status);
    }
    return status;
 }
unload_module()
static int unload_module (void) static
Definition at line 92 of file res_pjsip_dlg_options.c.
References AST_MODFLAG_LOAD_ORDER, AST_MODPRI_APP_DEPEND, AST_MODULE_INFO(), AST_MODULE_SUPPORT_CORE, ast_sip_session_unregister_supplement(), ASTERISK_GPL_KEY, and load_module().
 {
    ast_sip_session_unregister_supplement(&dlg_options_supplement);
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "SIP OPTIONS in dialog handler" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_APP_DEPEND, .requires = "res_pjsip,res_pjsip_session", } static
Definition at line 104 of file res_pjsip_dlg_options.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 104 of file res_pjsip_dlg_options.c.
dlg_options_supplement
struct ast_sip_session_supplement dlg_options_supplement static
Initial value:
= {
   .method = "OPTIONS",
   .incoming_request = options_incoming_request,
}
Definition at line 80 of file res_pjsip_dlg_options.c.