Asterisk - The Open Source Telephony Project: sip_utils.h File Reference
sip_utils.h File Reference
sip utils header file
Macros
#define IS_SIP_TECH(t) ((t) == &sip_tech || (t) == &sip_tech_info)
Functions
const char * comedia_string (struct ast_flags *flags)
Return a string describing the comedia value for the given flags.
const char * find_closing_quote (const char *start, const char *lim)
Locate closing quote in a string, skipping escaped quotes. optionally with a limit on the search. start must be past the first quote.
const char * force_rport_string (struct ast_flags *flags)
Return a string describing the force_rport value for the given flags.
const char * hangup_cause2sip (int cause)
Convert Asterisk hangup causes to SIP codes.
int hangup_sip2cause (int cause)
Convert SIP hangup causes to Asterisk hangup causes.
unsigned int port_str2int (const char *pt, unsigned int standard)
converts ascii port to int representation.
Detailed Description
sip utils header file
Definition in file sip_utils.h.
Macro Definition Documentation
IS_SIP_TECH
#define IS_SIP_TECH (t) ((t) == &sip_tech || (t) == &sip_tech_info)
Definition at line 26 of file sip_utils.h.
Referenced by func_header_read(), func_headers_read2(), handle_request_bye(), sip_acf_channel_read(), and sip_dtmfmode().
Function Documentation
comedia_string()
const char* comedia_string (struct ast_flags * flags)
Return a string describing the comedia value for the given flags.
Definition at line 43 of file channels/sip/utils.c.
References AST_CLI_YESNO, ast_test_flag, SIP_PAGE2_SYMMETRICRTP, and SIP_PAGE3_NAT_AUTO_COMEDIA.
Referenced by _sip_show_peer(), _sip_show_peers_one(), and sip_show_settings().
 {
    if (ast_test_flag(&flags[2], SIP_PAGE3_NAT_AUTO_COMEDIA)) {
       return ast_test_flag(&flags[1], SIP_PAGE2_SYMMETRICRTP) ? "Auto (Yes)" : "Auto (No)";
    }
    return AST_CLI_YESNO(ast_test_flag(&flags[1], SIP_PAGE2_SYMMETRICRTP));
 }
find_closing_quote()
const char* find_closing_quote (const char * start, const char * lim)
Locate closing quote in a string, skipping escaped quotes. optionally with a limit on the search. start must be past the first quote.
Definition at line 5074 of file chan_sip.c.
Referenced by get_comma(), get_in_brackets_const(), get_in_brackets_full(), and parse_moved_contact().
 {
    char last_char = '\0';
    const char *s;
    for (s = start; *s && s != lim; last_char = *s++) {
       if (*s == '"' && last_char != '\\')
          break;
    }
    return s;
 }
force_rport_string()
const char* force_rport_string (struct ast_flags * flags)
Return a string describing the force_rport value for the given flags.
Definition at line 35 of file channels/sip/utils.c.
References AST_CLI_YESNO, ast_test_flag, SIP_NAT_FORCE_RPORT, and SIP_PAGE3_NAT_AUTO_RPORT.
Referenced by _sip_show_peer(), _sip_show_peers_one(), sip_show_channel(), and sip_show_settings().
 {
    if (ast_test_flag(&flags[2], SIP_PAGE3_NAT_AUTO_RPORT)) {
       return ast_test_flag(&flags[0], SIP_NAT_FORCE_RPORT) ? "Auto (Yes)" : "Auto (No)";
    }
    return AST_CLI_YESNO(ast_test_flag(&flags[0], SIP_NAT_FORCE_RPORT));
 }
hangup_cause2sip()
const char* hangup_cause2sip (int cause)
Convert Asterisk hangup causes to SIP codes.
 Possible values from causes.h
        AST_CAUSE_NOTDEFINED    AST_CAUSE_NORMAL        AST_CAUSE_BUSY
        AST_CAUSE_FAILURE       AST_CAUSE_CONGESTION    AST_CAUSE_UNALLOCATED
   In addition to these, a lot of PRI codes is defined in causes.h
   ...should we take care of them too ?
   Quote RFC 3398
   ISUP Cause value                        SIP response
   ----------------                        ------------
   1  unallocated number                   404 Not Found
   2  no route to network                  404 Not found
   3  no route to destination              404 Not found
   16 normal call clearing                 --- (*)
   17 user busy                            486 Busy here
   18 no user responding                   408 Request Timeout
   19 no answer from the user              480 Temporarily unavailable
   20 subscriber absent                    480 Temporarily unavailable
   21 call rejected                        403 Forbidden (+)
   22 number changed (w/o diagnostic)      410 Gone
   22 number changed (w/ diagnostic)       301 Moved Permanently
   23 redirection to new destination       410 Gone
   26 non-selected user clearing           404 Not Found (=)
   27 destination out of order             502 Bad Gateway
   28 address incomplete                   484 Address incomplete
   29 facility rejected                    501 Not implemented
   31 normal unspecified                   480 Temporarily unavailable
Definition at line 7108 of file chan_sip.c.
References AST_CAUSE_BEARERCAPABILITY_NOTAVAIL, AST_CAUSE_CALL_REJECTED, AST_CAUSE_CHAN_NOT_IMPLEMENTED, AST_CAUSE_CONGESTION, AST_CAUSE_DESTINATION_OUT_OF_ORDER, AST_CAUSE_FACILITY_REJECTED, AST_CAUSE_FAILURE, AST_CAUSE_INTERWORKING, AST_CAUSE_INVALID_NUMBER_FORMAT, AST_CAUSE_NO_ANSWER, AST_CAUSE_NO_ROUTE_DESTINATION, AST_CAUSE_NO_ROUTE_TRANSIT_NET, AST_CAUSE_NO_USER_RESPONSE, AST_CAUSE_NORMAL_UNSPECIFIED, AST_CAUSE_NOTDEFINED, AST_CAUSE_NUMBER_CHANGED, AST_CAUSE_SWITCH_CONGESTION, AST_CAUSE_UNALLOCATED, AST_CAUSE_UNREGISTERED, AST_CAUSE_USER_BUSY, ast_debug, and NULL.
Referenced by sip_hangup().
 {
    switch (cause) {
       case AST_CAUSE_UNALLOCATED:      /* 1 */
       case AST_CAUSE_NO_ROUTE_DESTINATION:   /* 3 IAX2: Can't find extension in context */
       case AST_CAUSE_NO_ROUTE_TRANSIT_NET:   /* 2 */
          return "404 Not Found";
       case AST_CAUSE_CONGESTION:    /* 34 */
       case AST_CAUSE_SWITCH_CONGESTION:   /* 42 */
          return "503 Service Unavailable";
       case AST_CAUSE_NO_USER_RESPONSE: /* 18 */
          return "408 Request Timeout";
       case AST_CAUSE_NO_ANSWER:     /* 19 */
       case AST_CAUSE_UNREGISTERED:        /* 20 */
          return "480 Temporarily unavailable";
       case AST_CAUSE_CALL_REJECTED:    /* 21 */
          return "403 Forbidden";
       case AST_CAUSE_NUMBER_CHANGED:      /* 22 */
          return "410 Gone";
       case AST_CAUSE_NORMAL_UNSPECIFIED:  /* 31 */
          return "480 Temporarily unavailable";
       case AST_CAUSE_INVALID_NUMBER_FORMAT:
          return "484 Address incomplete";
       case AST_CAUSE_USER_BUSY:
          return "486 Busy here";
       case AST_CAUSE_FAILURE:
          return "500 Server internal failure";
       case AST_CAUSE_FACILITY_REJECTED:   /* 29 */
          return "501 Not Implemented";
       case AST_CAUSE_CHAN_NOT_IMPLEMENTED:
          return "503 Service Unavailable";
       /* Used in chan_iax2 */
       case AST_CAUSE_DESTINATION_OUT_OF_ORDER:
          return "502 Bad Gateway";
       case AST_CAUSE_BEARERCAPABILITY_NOTAVAIL: /* Can't find codec to connect to host */
          return "488 Not Acceptable Here";
       case AST_CAUSE_INTERWORKING:  /* Unspecified Interworking issues */
          return "500 Network error";
       case AST_CAUSE_NOTDEFINED:
       default:
          ast_debug(1, "AST hangup cause %d (no match found in SIP)\n", cause);
          return NULL;
    }
    /* Never reached */
    return 0;
 }
hangup_sip2cause()
int hangup_sip2cause (int cause)
Convert SIP hangup causes to Asterisk hangup causes.
Definition at line 6986 of file chan_sip.c.
References AST_CAUSE_BEARERCAPABILITY_NOTAVAIL, AST_CAUSE_BUSY, AST_CAUSE_CALL_REJECTED, AST_CAUSE_CONGESTION, AST_CAUSE_DESTINATION_OUT_OF_ORDER, AST_CAUSE_FACILITY_REJECTED, AST_CAUSE_FAILURE, AST_CAUSE_INTERWORKING, AST_CAUSE_INVALID_NUMBER_FORMAT, AST_CAUSE_NO_ANSWER, AST_CAUSE_NO_ROUTE_DESTINATION, AST_CAUSE_NO_USER_RESPONSE, AST_CAUSE_NORMAL, AST_CAUSE_NORMAL_TEMPORARY_FAILURE, AST_CAUSE_NUMBER_CHANGED, AST_CAUSE_RECOVERY_ON_TIMER_EXPIRE, AST_CAUSE_UNALLOCATED, and AST_CAUSE_USER_BUSY.
Referenced by __transmit_response(), handle_incoming(), handle_response(), and handle_response_invite().
 {
    /* Possible values taken from causes.h */
    switch(cause) {
       case 401:   /* Unauthorized */
          return AST_CAUSE_CALL_REJECTED;
       case 403:   /* Not found */
          return AST_CAUSE_CALL_REJECTED;
       case 404:   /* Not found */
          return AST_CAUSE_UNALLOCATED;
       case 405:   /* Method not allowed */
          return AST_CAUSE_INTERWORKING;
       case 407:   /* Proxy authentication required */
          return AST_CAUSE_CALL_REJECTED;
       case 408:   /* No reaction */
          return AST_CAUSE_NO_USER_RESPONSE;
       case 409:   /* Conflict */
          return AST_CAUSE_NORMAL_TEMPORARY_FAILURE;
       case 410:   /* Gone */
          return AST_CAUSE_NUMBER_CHANGED;
       case 411:   /* Length required */
          return AST_CAUSE_INTERWORKING;
       case 413:   /* Request entity too large */
          return AST_CAUSE_INTERWORKING;
       case 414:   /* Request URI too large */
          return AST_CAUSE_INTERWORKING;
       case 415:   /* Unsupported media type */
          return AST_CAUSE_INTERWORKING;
       case 420:   /* Bad extension */
          return AST_CAUSE_NO_ROUTE_DESTINATION;
       case 480:   /* No answer */
          return AST_CAUSE_NO_ANSWER;
       case 481:   /* No answer */
          return AST_CAUSE_INTERWORKING;
       case 482:   /* Loop detected */
          return AST_CAUSE_INTERWORKING;
       case 483:   /* Too many hops */
          return AST_CAUSE_NO_ANSWER;
       case 484:   /* Address incomplete */
          return AST_CAUSE_INVALID_NUMBER_FORMAT;
       case 485:   /* Ambiguous */
          return AST_CAUSE_UNALLOCATED;
       case 486:   /* Busy everywhere */
          return AST_CAUSE_BUSY;
       case 487:   /* Request terminated */
          return AST_CAUSE_INTERWORKING;
       case 488:   /* No codecs approved */
          return AST_CAUSE_BEARERCAPABILITY_NOTAVAIL;
       case 491:   /* Request pending */
          return AST_CAUSE_INTERWORKING;
       case 493:   /* Undecipherable */
          return AST_CAUSE_INTERWORKING;
       case 500:   /* Server internal failure */
          return AST_CAUSE_FAILURE;
       case 501:   /* Call rejected */
          return AST_CAUSE_FACILITY_REJECTED;
       case 502:
          return AST_CAUSE_DESTINATION_OUT_OF_ORDER;
       case 503:   /* Service unavailable */
          return AST_CAUSE_CONGESTION;
       case 504:   /* Gateway timeout */
          return AST_CAUSE_RECOVERY_ON_TIMER_EXPIRE;
       case 505:   /* SIP version not supported */
          return AST_CAUSE_INTERWORKING;
       case 600:   /* Busy everywhere */
          return AST_CAUSE_USER_BUSY;
       case 603:   /* Decline */
          return AST_CAUSE_CALL_REJECTED;
       case 604:   /* Does not exist anywhere */
          return AST_CAUSE_UNALLOCATED;
       case 606:   /* Not acceptable */
          return AST_CAUSE_BEARERCAPABILITY_NOTAVAIL;
       default:
          if (cause < 500 && cause >= 400) {
             /* 4xx class error that is unknown - someting wrong with our request */
             return AST_CAUSE_INTERWORKING;
          } else if (cause < 600 && cause >= 500) {
             /* 5xx class error - problem in the remote end */
             return AST_CAUSE_CONGESTION;
          } else if (cause < 700 && cause >= 600) {
             /* 6xx - global errors in the 4xx class */
             return AST_CAUSE_INTERWORKING;
          }
          return AST_CAUSE_NORMAL;
    }
    /* Never reached */
    return 0;
 }
port_str2int()
unsigned int port_str2int (const char * pt, unsigned int standard)
converts ascii port to int representation.
pt[in] string that contains a port.
standard[in] port to return in case the port string input is NULL or if there is a parsing error.
Returns
An integer port representation.
converts ascii port to int representation.
Definition at line 3538 of file chan_sip.c.
References ast_strlen_zero.
Referenced by build_peer(), reload_config(), and sip_parse_register_line().
 {
    int port = standard;
    if (ast_strlen_zero(pt) || (sscanf(pt, "%30d", &port) != 1) || (port < 1) || (port > 65535)) {
       port = standard;
    }
    return port;
 }