Asterisk - The Open Source Telephony Project: test_dns_srv.c File Reference
test_dns_srv.c File Reference
#include "asterisk.h"
#include <arpa/nameser.h>
#include "asterisk/test.h"
#include "asterisk/module.h"
#include "asterisk/dns_core.h"
#include "asterisk/dns_resolver.h"
#include "asterisk/dns_srv.h"
#include "asterisk/dns_test.h"
Data Structures
struct srv_record
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
AST_TEST_DEFINE (srv_resolve_single_record)
AST_TEST_DEFINE (srv_resolve_sort_priority)
AST_TEST_DEFINE (srv_resolve_same_priority_zero_weight)
AST_TEST_DEFINE (srv_resolve_same_priority_different_weights)
AST_TEST_DEFINE (srv_resolve_different_priorities_different_weights)
AST_TEST_DEFINE (srv_resolve_record_missing_weight_port_host)
AST_TEST_DEFINE (srv_resolve_record_missing_port_host)
AST_TEST_DEFINE (srv_resolve_record_missing_host)
static int generate_srv_record (void *dns_record, char *buf)
static enum ast_test_result_state invalid_record_test (struct ast_test *test, struct srv_record *records, int num_records)
static int load_module (void)
static enum ast_test_result_state nominal_test (struct ast_test *test, struct srv_record *records, int *srv_record_order, int num_records)
static int srv_cancel (struct ast_dns_query *query)
static int srv_resolve (struct ast_dns_query *query)
static void * srv_thread (void *dns_query)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "DNS SRV Tests" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, }
static char ans_buffer [1024]
static const struct ast_module_info * ast_module_info = &__mod_info
static int num_test_records
static struct ast_dns_resolver srv_resolver
static struct srv_record * test_records
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 589 of file test_dns_srv.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 589 of file test_dns_srv.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 589 of file test_dns_srv.c.
AST_TEST_DEFINE() [1/8]
AST_TEST_DEFINE (srv_resolve_single_record)
Definition at line 188 of file test_dns_srv.c.
References ARRAY_LEN, AST_TEST_NOT_RUN, sip_to_pjsip::info(), nominal_test(), TEST_EXECUTE, and TEST_INIT.
 {
    struct srv_record records[] = {
       { 10, 10, 5060, "goose.down" },
    };
    int srv_record_order[] = { 0, };
    switch (cmd) {
    case TEST_INIT:
       info->name = "srv_resolve_single_record";
       info->category = "/main/dns/srv/";
       info->summary = "Test an SRV lookup which returns a single record";
       info->description = "This test defines a single SRV record and performs a\n"
          "resolution of the domain to which they belong. The test ensures that all\n"
          "fields of the SRV record are parsed correctly";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    return nominal_test(test, records, srv_record_order, ARRAY_LEN(records));
 }
AST_TEST_DEFINE() [2/8]
AST_TEST_DEFINE (srv_resolve_sort_priority)
Definition at line 212 of file test_dns_srv.c.
References ARRAY_LEN, AST_TEST_NOT_RUN, sip_to_pjsip::info(), nominal_test(), TEST_EXECUTE, and TEST_INIT.
 {
    struct srv_record records[] = {
       { 20, 10, 5060, "tacos" },
       { 10, 10, 5060, "goose.down" },
    };
    int srv_record_order[] = { 1, 0};
    switch (cmd) {
    case TEST_INIT:
       info->name = "srv_resolve_sort_priority";
       info->category = "/main/dns/srv/";
       info->summary = "Test an SRV lookup which returns two records with differing priorities";
       info->description = "This test defines two SRV records with differing priorities and\n"
          "performs a resolution of the domain to which they belong. The test ensures that\n"
          "the two records are sorted according to priority and that all fields of the SRV\n"
          "records are parsed correctly";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    return nominal_test(test, records, srv_record_order, ARRAY_LEN(records));
 }
AST_TEST_DEFINE() [3/8]
AST_TEST_DEFINE (srv_resolve_same_priority_zero_weight)
Definition at line 237 of file test_dns_srv.c.
References ARRAY_LEN, AST_TEST_NOT_RUN, sip_to_pjsip::info(), nominal_test(), TEST_EXECUTE, and TEST_INIT.
 {
    struct srv_record records[] = {
       { 10, 0, 5060, "tacos" },
       { 10, 10, 5060, "goose.down" },
    };
    int srv_record_order[] = { 1, 0};
    switch (cmd) {
    case TEST_INIT:
       info->name = "srv_resolve_same_priority_zero_weight";
       info->category = "/main/dns/srv/";
       info->summary = "Test an SRV lookup which returns two records with same priority but different weights";
       info->description = "This test defines two SRV records with same priority but different weights and\n"
          "performs a resolution of the domain to which they belong. The test ensures that\n"
          "the record with zero weight comes last and that all fields of the SRV\n"
          "records are parsed correctly";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    return nominal_test(test, records, srv_record_order, ARRAY_LEN(records));
 }
AST_TEST_DEFINE() [4/8]
AST_TEST_DEFINE (srv_resolve_same_priority_different_weights)
Definition at line 262 of file test_dns_srv.c.
References ans_buffer, ARRAY_LEN, ast_dns_resolve(), ast_dns_resolver_register(), ast_dns_resolver_unregister(), ast_dns_result_free(), ast_dns_result_get_records(), ast_dns_srv_get_host(), ast_dns_srv_get_port(), ast_dns_srv_get_priority(), ast_dns_srv_get_weight(), AST_TEST_FAIL, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_test_status_update, cleanup(), srv_record::host, sip_to_pjsip::info(), NULL, num_test_records, srv_record::port, srv_record::priority, records, result, TEST_EXECUTE, TEST_INIT, and srv_record::weight.
 {
    struct srv_record records[] = {
       { 10, 10, 5060, "tacos" },
       { 10, 20, 5060, "goose.down" },
    };
    int srv_record_occurence[2] = { 0, };
    enum ast_test_result_state res = AST_TEST_PASS;
    int count = 0;
    switch (cmd) {
    case TEST_INIT:
       info->name = "srv_resolve_same_priority_different_weights";
       info->category = "/main/dns/srv/";
       info->summary = "Test an SRV lookup which returns two records with same priority but different weights";
       info->description = "This test defines two SRV records with same priority but different weights and\n"
          "performs a resolution of the domain to which they belong. The test ensures that\n"
          "the record with higher weight occurs more often than the one of lesser weight";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    test_records = records;
    num_test_records = ARRAY_LEN(records);
    ast_dns_resolver_register(&srv_resolver);
    for (count = 0; count < 100; count++) {
       struct ast_dns_result *result;
       const struct ast_dns_record *record;
       int i;
       memset(ans_buffer, 0, sizeof(ans_buffer));
       if (ast_dns_resolve("goose.feathers", T_SRV, C_IN, &result)) {
          ast_test_status_update(test, "DNS resolution failed\n");
          res = AST_TEST_FAIL;
          goto cleanup;
       }
       if (!result) {
          ast_test_status_update(test, "DNS resolution returned no result\n");
          res = AST_TEST_FAIL;
          goto cleanup;
       }
       record = ast_dns_result_get_records(result);
       for (i = 0; i < ARRAY_LEN(records); i++) {
          if (ast_dns_srv_get_priority(record) != records[i].priority) {
             continue;
          }
          if (ast_dns_srv_get_weight(record) != records[i].weight) {
             continue;
          }
          if (ast_dns_srv_get_port(record) != records[i].port) {
             continue;
          }
          if (strcmp(ast_dns_srv_get_host(record), records[i].host)) {
             continue;
          }
          srv_record_occurence[i]++;
          break;
       }
       ast_dns_result_free(result);
    }
    if (srv_record_occurence[0] > srv_record_occurence[1]) {
       ast_test_status_update(test, "SRV sorting resulted in lesser weight being returned more often\n");
       res = AST_TEST_FAIL;
    }
 cleanup:
    ast_dns_resolver_unregister(&srv_resolver);
    test_records = NULL;
    num_test_records = 0;
    memset(ans_buffer, 0, sizeof(ans_buffer));
    return res;
 }
AST_TEST_DEFINE() [5/8]
AST_TEST_DEFINE (srv_resolve_different_priorities_different_weights)
Definition at line 348 of file test_dns_srv.c.
References ans_buffer, ARRAY_LEN, ast_dns_record_get_next(), ast_dns_resolve(), ast_dns_resolver_register(), ast_dns_resolver_unregister(), ast_dns_result_free(), ast_dns_result_get_records(), ast_dns_srv_get_host(), ast_dns_srv_get_port(), ast_dns_srv_get_priority(), ast_dns_srv_get_weight(), AST_TEST_FAIL, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_test_status_update, cleanup(), srv_record::host, sip_to_pjsip::info(), NULL, num_test_records, srv_record::port, srv_record::priority, records, result, TEST_EXECUTE, TEST_INIT, and srv_record::weight.
 {
    struct srv_record records[] = {
       { 10, 10, 5060, "tacos" },
       { 10, 20, 5060, "goose.down" },
       { 5, 80, 5060, "moo" },
       { 5, 10, 5060, "Canada" },
    };
    int srv_record_priority[4] = { 5, 5, 10, 10 };
    int srv_record_occurence[4] = { 0, };
    enum ast_test_result_state res = AST_TEST_PASS;
    int count = 0;
    switch (cmd) {
    case TEST_INIT:
       info->name = "srv_resolve_different_priorities_different_weights";
       info->category = "/main/dns/srv/";
       info->summary = "Test an SRV lookup which returns four records with different priority and different weights";
       info->description = "This test defines four SRV records, two with one priority and two with another priority,\n"
          "and different weights and performs a resolution of the domain to which they belong.\n"
          "The test ensures that the priorities are sorted properly and that the records with higher weight\n"
          "occur more often than the ones of less weight.";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    test_records = records;
    num_test_records = ARRAY_LEN(records);
    ast_dns_resolver_register(&srv_resolver);
    for (count = 0; count < 100; count++) {
       struct ast_dns_result *result;
       const struct ast_dns_record *record;
       int i;
       memset(ans_buffer, 0, sizeof(ans_buffer));
       if (ast_dns_resolve("goose.feathers", T_SRV, C_IN, &result)) {
          ast_test_status_update(test, "DNS resolution failed\n");
          res = AST_TEST_FAIL;
          goto cleanup;
       }
       if (!result) {
          ast_test_status_update(test, "DNS resolution returned no result\n");
          res = AST_TEST_FAIL;
          goto cleanup;
       }
       i = 0;
       for (record = ast_dns_result_get_records(result); record; record = ast_dns_record_get_next(record)) {
          if (ast_dns_srv_get_priority(record) != srv_record_priority[i]) {
             ast_test_status_update(test, "Unexpected priority in returned SRV record\n");
             res = AST_TEST_FAIL;
          }
          i++;
       }
       record = ast_dns_result_get_records(result);
       for (i = 0; i < ARRAY_LEN(records); i++) {
          if (ast_dns_srv_get_priority(record) != records[i].priority) {
             continue;
          }
          if (ast_dns_srv_get_weight(record) != records[i].weight) {
             continue;
          }
          if (ast_dns_srv_get_port(record) != records[i].port) {
             continue;
          }
          if (strcmp(ast_dns_srv_get_host(record), records[i].host)) {
             continue;
          }
          srv_record_occurence[i]++;
          break;
       }
       ast_dns_result_free(result);
    }
    if (srv_record_occurence[0] > srv_record_occurence[1]) {
       ast_test_status_update(test, "SRV sorting resulted in lesser weight being returned more often for priority 10\n");
       res = AST_TEST_FAIL;
    }
    if (srv_record_occurence[3] > srv_record_occurence[2]) {
       ast_test_status_update(test, "SRV sorting resulted in lesser weight being returned more often for priority 5\n");
       res = AST_TEST_FAIL;
    }
 cleanup:
    ast_dns_resolver_unregister(&srv_resolver);
    test_records = NULL;
    num_test_records = 0;
    memset(ans_buffer, 0, sizeof(ans_buffer));
    return res;
 }
AST_TEST_DEFINE() [6/8]
AST_TEST_DEFINE (srv_resolve_record_missing_weight_port_host)
Definition at line 494 of file test_dns_srv.c.
References ARRAY_LEN, AST_TEST_NOT_RUN, sip_to_pjsip::info(), invalid_record_test(), TEST_EXECUTE, and TEST_INIT.
 {
    struct srv_record records[] = {
       { 10, 10, 5060, "tacos.com", 0, 1, 1, 1 },
    };
    switch (cmd) {
    case TEST_INIT:
       info->name = "srv_resolve_record_missing_weight_port_host";
       info->category = "/main/dns/srv/";
       info->summary = "Test an SRV lookup which returns a single invalid record";
       info->description = "This test defines a single SRV record and performs a\n"
          "resolution of the domain to which they belong. The test ensures that the\n"
          "record is determined to be corrupt as it contains only a priority";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    return invalid_record_test(test, records, ARRAY_LEN(records));
 }
AST_TEST_DEFINE() [7/8]
AST_TEST_DEFINE (srv_resolve_record_missing_port_host)
Definition at line 516 of file test_dns_srv.c.
References ARRAY_LEN, AST_TEST_NOT_RUN, sip_to_pjsip::info(), invalid_record_test(), TEST_EXECUTE, and TEST_INIT.
 {
    struct srv_record records[] = {
       { 10, 10, 5060, "tacos.com", 0, 0, 1, 1 },
    };
    switch (cmd) {
    case TEST_INIT:
       info->name = "srv_resolve_record_missing_port_host";
       info->category = "/main/dns/srv/";
       info->summary = "Test an SRV lookup which returns a single invalid record";
       info->description = "This test defines a single SRV record and performs a\n"
          "resolution of the domain to which they belong. The test ensures that the\n"
          "record is determined to be corrupt as it contains only a priority and weight";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    return invalid_record_test(test, records, ARRAY_LEN(records));
 }
AST_TEST_DEFINE() [8/8]
AST_TEST_DEFINE (srv_resolve_record_missing_host)
Definition at line 538 of file test_dns_srv.c.
References ARRAY_LEN, AST_TEST_NOT_RUN, sip_to_pjsip::info(), invalid_record_test(), TEST_EXECUTE, and TEST_INIT.
 {
    struct srv_record records[] = {
       { 10, 10, 5060, "tacos.com", 0, 0, 0, 1 },
    };
    switch (cmd) {
    case TEST_INIT:
       info->name = "srv_resolve_record_missing_host";
       info->category = "/main/dns/srv/";
       info->summary = "Test an SRV lookup which returns a single invalid record";
       info->description = "This test defines a single SRV record and performs a\n"
          "resolution of the domain to which they belong. The test ensures that the\n"
          "record is determined to be corrupt as it contains only a priority, weight,\n"
          "and port";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    return invalid_record_test(test, records, ARRAY_LEN(records));
 }
generate_srv_record()
static int generate_srv_record (void * dns_record, char * buf) static
Definition at line 47 of file test_dns_srv.c.
References ast_dns_test_write_domain(), buf, srv_record::host, srv_record::ignore_host, srv_record::ignore_port, srv_record::ignore_priority, srv_record::ignore_weight, srv_record::port, srv_record::priority, and srv_record::weight.
Referenced by srv_thread().
 {
    struct srv_record *record = dns_record;
    uint16_t priority = htons(record->priority);
    uint16_t weight = htons(record->weight);
    uint16_t port = htons(record->port);
    char *ptr = buf;
    if (!record->ignore_priority) {
       memcpy(ptr, &priority, sizeof(priority));
       ptr += sizeof(priority);
    }
    if (!record->ignore_weight) {
       memcpy(ptr, &weight, sizeof(weight));
       ptr += sizeof(weight);
    }
    if (!record->ignore_port) {
       memcpy(ptr, &port, sizeof(port));
       ptr += sizeof(port);
    }
    if (!record->ignore_host) {
       ptr += ast_dns_test_write_domain(record->host, ptr);
    }
    return ptr - buf;
 }
invalid_record_test()
static enum ast_test_result_state invalid_record_test (struct ast_test * test, struct srv_record * records, int num_records) static
Definition at line 452 of file test_dns_srv.c.
References ans_buffer, ast_dns_resolve(), ast_dns_resolver_register(), ast_dns_resolver_unregister(), ast_dns_result_free(), ast_dns_result_get_records(), AST_TEST_FAIL, AST_TEST_PASS, ast_test_status_update, cleanup(), NULL, num_test_records, RAII_VAR, records, and result.
Referenced by AST_TEST_DEFINE().
 {
    RAII_VAR(struct ast_dns_result *, result, NULL, ast_dns_result_free);
    const struct ast_dns_record *record;
    enum ast_test_result_state res = AST_TEST_PASS;
    test_records = records;
    num_test_records = num_records;
    memset(ans_buffer, 0, sizeof(ans_buffer));
    ast_dns_resolver_register(&srv_resolver);
    if (ast_dns_resolve("goose.feathers", T_SRV, C_IN, &result)) {
       ast_test_status_update(test, "DNS resolution failed\n");
       res = AST_TEST_FAIL;
       goto cleanup;
    }
    if (!result) {
       ast_test_status_update(test, "DNS resolution returned no result\n");
       res = AST_TEST_FAIL;
       goto cleanup;
    }
    record = ast_dns_result_get_records(result);
    if (record) {
       ast_test_status_update(test, "Unexpected record returned from SRV query\n");
       res = AST_TEST_FAIL;
    }
 cleanup:
    ast_dns_resolver_unregister(&srv_resolver);
    test_records = NULL;
    num_test_records = 0;
    memset(ans_buffer, 0, sizeof(ans_buffer));
    return res;
 }
load_module()
static int load_module (void) static
Definition at line 575 of file test_dns_srv.c.
References AST_MODULE_LOAD_SUCCESS, and AST_TEST_REGISTER.
 {
    AST_TEST_REGISTER(srv_resolve_single_record);
    AST_TEST_REGISTER(srv_resolve_sort_priority);
    AST_TEST_REGISTER(srv_resolve_same_priority_zero_weight);
    AST_TEST_REGISTER(srv_resolve_same_priority_different_weights);
    AST_TEST_REGISTER(srv_resolve_different_priorities_different_weights);
    AST_TEST_REGISTER(srv_resolve_record_missing_weight_port_host);
    AST_TEST_REGISTER(srv_resolve_record_missing_port_host);
    AST_TEST_REGISTER(srv_resolve_record_missing_host);
    return AST_MODULE_LOAD_SUCCESS;
 }
nominal_test()
static enum ast_test_result_state nominal_test (struct ast_test * test, struct srv_record * records, int * srv_record_order, int num_records) static
Definition at line 125 of file test_dns_srv.c.
References ans_buffer, ast_dns_record_get_next(), ast_dns_resolve(), ast_dns_resolver_register(), ast_dns_resolver_unregister(), ast_dns_result_free(), ast_dns_result_get_records(), ast_dns_srv_get_host(), ast_dns_srv_get_port(), ast_dns_srv_get_priority(), ast_dns_srv_get_weight(), AST_TEST_FAIL, AST_TEST_PASS, ast_test_status_update, cleanup(), srv_record::host, NULL, num_test_records, srv_record::port, srv_record::priority, RAII_VAR, records, result, and srv_record::weight.
Referenced by AST_TEST_DEFINE().
 {
    RAII_VAR(struct ast_dns_result *, result, NULL, ast_dns_result_free);
    const struct ast_dns_record *record;
    enum ast_test_result_state res = AST_TEST_PASS;
    int i;
    test_records = records;
    num_test_records = num_records;
    memset(ans_buffer, 0, sizeof(ans_buffer));
    ast_dns_resolver_register(&srv_resolver);
    if (ast_dns_resolve("goose.feathers", T_SRV, C_IN, &result)) {
       ast_test_status_update(test, "DNS resolution failed\n");
       res = AST_TEST_FAIL;
       goto cleanup;
    }
    if (!result) {
       ast_test_status_update(test, "DNS resolution returned no result\n");
       res = AST_TEST_FAIL;
       goto cleanup;
    }
    i = 0;
    for (record = ast_dns_result_get_records(result); record; record = ast_dns_record_get_next(record)) {
       if (ast_dns_srv_get_priority(record) != records[srv_record_order[i]].priority) {
          ast_test_status_update(test, "Unexpected priority in returned SRV record\n");
          res = AST_TEST_FAIL;
       }
       if (ast_dns_srv_get_weight(record) != records[srv_record_order[i]].weight) {
          ast_test_status_update(test, "Unexpected weight in returned SRV record\n");
          res = AST_TEST_FAIL;
       }
       if (ast_dns_srv_get_port(record) != records[srv_record_order[i]].port) {
          ast_test_status_update(test, "Unexpected port in returned SRV record\n");
          res = AST_TEST_FAIL;
       }
       if (strcmp(ast_dns_srv_get_host(record), records[srv_record_order[i]].host)) {
          ast_test_status_update(test, "Unexpected host in returned SRV record\n");
          res = AST_TEST_FAIL;
       }
       ++i;
    }
    if (i != num_records) {
       ast_test_status_update(test, "Unexpected number of records returned in SRV lookup\n");
       res = AST_TEST_FAIL;
    }
 cleanup:
    ast_dns_resolver_unregister(&srv_resolver);
    test_records = NULL;
    num_test_records = 0;
    memset(ans_buffer, 0, sizeof(ans_buffer));
    return res;
 }
srv_cancel()
static int srv_cancel (struct ast_dns_query * query) static
Definition at line 113 of file test_dns_srv.c.
 {
    return -1;
 }
srv_resolve()
static int srv_resolve (struct ast_dns_query * query) static
Definition at line 106 of file test_dns_srv.c.
References ao2_bump, ast_pthread_create_detached, NULL, srv_thread(), and thread.
 {
    pthread_t thread;
    return ast_pthread_create_detached(&thread, NULL, srv_thread, ao2_bump(query));
 }
srv_thread()
static void* srv_thread (void * dns_query) static
Definition at line 81 of file test_dns_srv.c.
References ans_buffer, ao2_ref, ast_dns_resolver_add_record(), ast_dns_resolver_completed(), ast_dns_resolver_set_result(), ast_dns_test_generate_result(), generate_srv_record(), NULL, and num_test_records.
Referenced by srv_resolve().
 {
    struct ast_dns_query *query = dns_query;
    int i;
    int ans_size;
    ans_size = ast_dns_test_generate_result(query, test_records, num_test_records,
          sizeof(struct srv_record), generate_srv_record, ans_buffer);
    ast_dns_resolver_set_result(query, 0, 0, NOERROR, "goose.feathers", ans_buffer, ans_size);
    for (i = 0; i < num_test_records; ++i) {
       char record[128];
       int srv_size;
       srv_size = generate_srv_record(&test_records[i], record);
       ast_dns_resolver_add_record(query, T_SRV, C_IN, 12345, record, srv_size);
    }
    ast_dns_resolver_completed(query);
    ao2_ref(query, -1);
    return NULL;
 }
unload_module()
static int unload_module (void) static
Definition at line 561 of file test_dns_srv.c.
References AST_TEST_UNREGISTER.
 {
    AST_TEST_UNREGISTER(srv_resolve_single_record);
    AST_TEST_UNREGISTER(srv_resolve_sort_priority);
    AST_TEST_UNREGISTER(srv_resolve_same_priority_zero_weight);
    AST_TEST_UNREGISTER(srv_resolve_same_priority_different_weights);
    AST_TEST_UNREGISTER(srv_resolve_different_priorities_different_weights);
    AST_TEST_UNREGISTER(srv_resolve_record_missing_weight_port_host);
    AST_TEST_UNREGISTER(srv_resolve_record_missing_port_host);
    AST_TEST_UNREGISTER(srv_resolve_record_missing_host);
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "DNS SRV Tests" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, } static
Definition at line 589 of file test_dns_srv.c.
ans_buffer
char ans_buffer[1024] static
Definition at line 79 of file test_dns_srv.c.
Referenced by AST_TEST_DEFINE(), invalid_record_test(), nominal_test(), and srv_thread().
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 589 of file test_dns_srv.c.
num_test_records
int num_test_records static
Definition at line 78 of file test_dns_srv.c.
Referenced by AST_TEST_DEFINE(), invalid_record_test(), nominal_test(), and srv_thread().
srv_resolver
struct ast_dns_resolver srv_resolver static
Definition at line 118 of file test_dns_srv.c.
test_records
struct srv_record* test_records static
Definition at line 77 of file test_dns_srv.c.