Asterisk - The Open Source Telephony Project: io.c File Reference
io.c File Reference
I/O Managment (Derived from Cheops-NG)
#include "asterisk.h"
#include <termios.h>
#include <sys/ioctl.h>
#include "asterisk/io.h"
#include "asterisk/utils.h"
Data Structures
struct io_context
Global IO variables are now in a struct in order to be made threadsafe.
struct io_rec
Kept for each file descriptor.
Macros
#define DEBUG(a)
#define GROW_SHRINK_SIZE 512
Functions
int ast_get_termcols (int fd)
int ast_hide_password (int fd)
int * ast_io_add (struct io_context *ioc, int fd, ast_io_cb callback, short events, void *data)
Add a new I/O entry for this file descriptor with the given event mask, to call callback with data as an argument.
int * ast_io_change (struct io_context *ioc, int *id, int fd, ast_io_cb callback, short events, void *data)
Changes an IO handler.
void ast_io_dump (struct io_context *ioc)
Dumps the IO array. Debugging: Dump everything in the I/O array.
int ast_io_remove (struct io_context *ioc, int *_id)
Removes an IO context.
int ast_io_wait (struct io_context *ioc, int howlong)
Make the poll call, and call the callbacks for anything that needs to be handled.
int ast_restore_tty (int fd, int oldstate)
Restores TTY mode. Call with result from previous ast_hide_password.
int ast_sd_get_fd (int type, const struct ast_sockaddr *addr)
Find a listening file descriptor provided by socket activation.
int ast_sd_get_fd_un (int type, const char *path)
Find a listening AF_LOCAL file descriptor provided by socket activation.
int ast_sd_notify (const char *state)
a wrapper for sd_notify(): notify systemd of any state changes.
struct io_context * io_context_create (void)
Create an I/O context.
void io_context_destroy (struct io_context *ioc)
Destroys a context.
static int io_grow (struct io_context *ioc)
Grow the size of our arrays.
static int io_shrink (struct io_context *ioc)
Detailed Description
I/O Managment (Derived from Cheops-NG)
Author
Mark Spencer marks.nosp@m.ter@.nosp@m.digiu.nosp@m.m.co.nosp@m.m
Definition in file io.c.
Macro Definition Documentation
DEBUG
#define DEBUG (a)
Definition at line 48 of file io.c.
Referenced by ast_io_add(), ast_io_wait(), and io_grow().
GROW_SHRINK_SIZE
#define GROW_SHRINK_SIZE 512
Definition at line 67 of file io.c.
Referenced by io_context_create(), and io_grow().
Function Documentation
ast_get_termcols()
int ast_get_termcols (int fd)
Definition at line 373 of file io.c.
References isatty().
Referenced by ast_cli_display_match_list().
 {
    struct winsize win;
    int cols = 0;
    if (!isatty(fd))
       return -1;
    if ( ioctl(fd, TIOCGWINSZ, &win) != -1 ) {
       if ( !cols && win.ws_col > 0 )
          cols = (int) win.ws_col;
    } else {
       /* assume 80 characters if the ioctl fails for some reason */
       cols = 80;
    }
    return cols;
 }
ast_hide_password()
int ast_hide_password (int fd)
Set fd into non-echoing mode (if fd is a tty)
Definition at line 337 of file io.c.
References ECHO, and isatty().
Referenced by pw_cb().
 {
    struct termios tios;
    int res;
    int old;
    if (!isatty(fd))
       return -1;
    res = tcgetattr(fd, &tios);
    if (res < 0)
       return -1;
    old = tios.c_lflag & (ECHO | ECHONL);
    tios.c_lflag &= ~ECHO;
    tios.c_lflag |= ECHONL;
    res = tcsetattr(fd, TCSAFLUSH, &tios);
    if (res < 0)
       return -1;
    return old;
 }
ast_io_add()
int* ast_io_add (struct io_context * ioc, int fd, ast_io_cb callback, short events, void * data)
Add a new I/O entry for this file descriptor with the given event mask, to call callback with data as an argument.
Adds an IO context.
Returns
Returns NULL on failure.
Definition at line 162 of file io.c.
References ast_debug, ast_malloc, io_rec::callback, io_rec::data, DEBUG, events, io_context::fdcnt, io_context::fds, io_rec::id, io_grow(), io_context::ior, io_context::maxfdcnt, and NULL.
Referenced by ast_netsock_bindaddr(), ast_udptl_new_with_bindaddr(), do_monitor(), mbl_load_adapter(), and network_thread().
 {
    int *ret;
    DEBUG(ast_debug(1, "ast_io_add()\n"));
    if (ioc->fdcnt >= ioc->maxfdcnt) {
       /*
        * We don't have enough space for this entry.  We need to
        * reallocate maxfdcnt poll fd's and io_rec's, or back out now.
        */
       if (io_grow(ioc))
          return NULL;
    }
    /*
     * At this point, we've got sufficiently large arrays going
     * and we can make an entry for it in the pollfd and io_r
     * structures.
     */
    ioc->fds[ioc->fdcnt].fd = fd;
    ioc->fds[ioc->fdcnt].events = events;
    ioc->fds[ioc->fdcnt].revents = 0;
    ioc->ior[ioc->fdcnt].callback = callback;
    ioc->ior[ioc->fdcnt].data = data;
    if (!(ioc->ior[ioc->fdcnt].id = ast_malloc(sizeof(*ioc->ior[ioc->fdcnt].id)))) {
       /* Bonk if we couldn't allocate an int */
       return NULL;
    }
    *(ioc->ior[ioc->fdcnt].id) = ioc->fdcnt;
    ret = ioc->ior[ioc->fdcnt].id;
    ioc->fdcnt++;
    return ret;
 }
ast_io_change()
int* ast_io_change (struct io_context * ioc, int * id, int fd, ast_io_cb callback, short events, void * data)
Changes an IO handler.
Parameters
ioc which context to use
id
fd the fd you wish it to contain now
callback new callback function
events event mask to wait for
data data to pass to the callback function Change an I/O handler, updating fd if > -1, callback if non-null, and revents if >-1, and data if non-null.
Return values
a pointer to the ID of the IO event
NULL on failure
Definition at line 200 of file io.c.
References io_rec::callback, io_rec::data, events, io_context::fdcnt, io_context::fds, io_rec::id, io_context::ior, and NULL.
Referenced by do_monitor().
 {
    /* If this id exceeds our file descriptor count it doesn't exist here */
    if (*id > ioc->fdcnt)
       return NULL;
    if (fd > -1)
       ioc->fds[*id].fd = fd;
    if (callback)
       ioc->ior[*id].callback = callback;
    if (events)
       ioc->fds[*id].events = events;
    if (data)
       ioc->ior[*id].data = data;
    return id;
 }
ast_io_dump()
void ast_io_dump (struct io_context * ioc)
Dumps the IO array. Debugging: Dump everything in the I/O array.
Definition at line 312 of file io.c.
References ast_debug, io_rec::callback, io_rec::data, io_context::fdcnt, io_context::fds, io_rec::id, io_context::ior, and io_context::maxfdcnt.
 {
    /*
     * Print some debugging information via
     * the logger interface
     */
    int x;
    ast_debug(1, "Asterisk IO Dump: %u entries, %u max entries\n", ioc->fdcnt, ioc->maxfdcnt);
    ast_debug(1, "================================================\n");
    ast_debug(1, "| ID    FD     Callback    Data        Events  |\n");
    ast_debug(1, "+------+------+-----------+-----------+--------+\n");
    for (x = 0; x < ioc->fdcnt; x++) {
       ast_debug(1, "| %.4d | %.4d | %p | %p | %.6x |\n",
             *ioc->ior[x].id,
             ioc->fds[x].fd,
             ioc->ior[x].callback,
             ioc->ior[x].data,
             (unsigned)ioc->fds[x].events);
    }
    ast_debug(1, "================================================\n");
 }
ast_io_remove()
int ast_io_remove (struct io_context * ioc, int * id)
Removes an IO context.
Parameters
ioc which io_context to remove it from
id which ID to remove Remove an I/O id from consideration
Return values
0 on success
-1 on failure
Definition at line 245 of file io.c.
References ast_free, ast_log, io_context::current_ioc, io_context::fdcnt, io_context::fds, io_rec::id, io_shrink(), io_context::ior, LOG_NOTICE, LOG_WARNING, io_context::needshrink, and NULL.
Referenced by ast_io_wait(), ast_netsock_destroy(), ast_udptl_destroy(), do_monitor(), mbl_load_adapter(), network_thread(), reload_config(), and unload_module().
 {
    int x;
    if (!_id) {
       ast_log(LOG_WARNING, "Asked to remove NULL?\n");
       return -1;
    }
    for (x = 0; x < ioc->fdcnt; x++) {
       if (ioc->ior[x].id == _id) {
          /* Free the int immediately and set to NULL so we know it's unused now */
          ast_free(ioc->ior[x].id);
          ioc->ior[x].id = NULL;
          ioc->fds[x].events = 0;
          ioc->fds[x].revents = 0;
          ioc->needshrink = 1;
          if (ioc->current_ioc == -1)
             io_shrink(ioc);
          return 0;
       }
    }
    ast_log(LOG_NOTICE, "Unable to remove unknown id %p\n", _id);
    return -1;
 }
ast_io_wait()
int ast_io_wait (struct io_context * ioc, int howlong)
Make the poll call, and call the callbacks for anything that needs to be handled.
Waits for IO.
Definition at line 278 of file io.c.
References ast_debug, ast_io_remove(), ast_poll, io_rec::callback, io_context::current_ioc, io_rec::data, DEBUG, io_context::fdcnt, io_context::fds, io_rec::id, io_shrink(), io_context::ior, and io_context::needshrink.
Referenced by do_monitor(), do_sco_listen(), network_thread(), and reload_config().
 {
    int res, x, origcnt;
    DEBUG(ast_debug(1, "ast_io_wait()\n"));
    if ((res = ast_poll(ioc->fds, ioc->fdcnt, howlong)) <= 0) {
       return res;
    }
    /* At least one event tripped */
    origcnt = ioc->fdcnt;
    for (x = 0; x < origcnt; x++) {
       /* Yes, it is possible for an entry to be deleted and still have an
          event waiting if it occurs after the original calling id */
       if (ioc->fds[x].revents && ioc->ior[x].id) {
          /* There's an event waiting */
          ioc->current_ioc = *ioc->ior[x].id;
          if (ioc->ior[x].callback) {
             if (!ioc->ior[x].callback(ioc->ior[x].id, ioc->fds[x].fd, ioc->fds[x].revents, ioc->ior[x].data)) {
                /* Time to delete them since they returned a 0 */
                ast_io_remove(ioc, ioc->ior[x].id);
             }
          }
          ioc->current_ioc = -1;
       }
    }
    if (ioc->needshrink)
       io_shrink(ioc);
    return res;
 }
ast_restore_tty()
int ast_restore_tty (int fd, int oldstate)
Restores TTY mode. Call with result from previous ast_hide_password.
Definition at line 356 of file io.c.
References ECHO.
Referenced by pw_cb().
 {
    int res;
    struct termios tios;
    if (oldstate < 0)
       return 0;
    res = tcgetattr(fd, &tios);
    if (res < 0)
       return -1;
    tios.c_lflag &= ~(ECHO | ECHONL);
    tios.c_lflag |= oldstate;
    res = tcsetattr(fd, TCSAFLUSH, &tios);
    if (res < 0)
       return -1;
    return 0;
 }
ast_sd_get_fd()
int ast_sd_get_fd (int type, const struct ast_sockaddr * addr)
Find a listening file descriptor provided by socket activation.
Parameters
type SOCK_STREAM or SOCK_DGRAM
addr The socket address of the bound listener.
Return values
<0 No match.
>0 File Descriptor matching sockaddr.
Note
This function returns -1 if systemd's development headers were not detected on the system.
Definition at line 438 of file io.c.
Referenced by ast_tcptls_server_start().
 {
 #ifdef HAVE_SYSTEMD
    int count = sd_listen_fds(0);
    int idx;
    for (idx = 0; idx < count; idx++) {
       if (!ast_sd_is_socket_sockaddr(idx + SD_LISTEN_FDS_START, type, addr)) {
          return idx + SD_LISTEN_FDS_START;
       }
    }
 #endif
    return -1;
 }
ast_sd_get_fd_un()
int ast_sd_get_fd_un (int type, const char * path)
Find a listening AF_LOCAL file descriptor provided by socket activation.
Parameters
type SOCK_STREAM or SOCK_DGRAM
path The path of the listener.
Return values
<0 No match.
>0 File Descriptor matching path.
Note
This function returns -1 if systemd's development headers were not detected on the system.
Definition at line 454 of file io.c.
Referenced by ast_makesocket(), and main().
 {
 #ifdef HAVE_SYSTEMD
    int count = sd_listen_fds(0);
    int idx;
    for (idx = 0; idx < count; idx++) {
       if (sd_is_socket_unix(idx + SD_LISTEN_FDS_START, type, 1, path, 0) > 0) {
          return idx + SD_LISTEN_FDS_START;
       }
    }
 #endif
    return -1;
 }
ast_sd_notify()
int ast_sd_notify (const char * state)
a wrapper for sd_notify(): notify systemd of any state changes.
Parameters
state a string that states the changes. See sd_notify(3). The wrapper does nothing if systemd ('s development headers) was not detected on the system.
Returns
>=0 on success, negative value on error.
Definition at line 392 of file io.c.
References ast_sockaddr_cmp(), ast_sockaddr_copy_sockaddr(), and type.
Referenced by ast_module_reload(), asterisk_daemon(), and really_quit().
{
 #ifdef HAVE_SYSTEMD
    return sd_notify(0, state);
 #else
    return 0;
 #endif
 }
io_context_create()
struct io_context* io_context_create (void)
Create an I/O context.
Creates a context Create a context for I/O operations Basically mallocs an IO structure and sets up some default values.
Definition at line 81 of file io.c.
References ast_calloc, ast_free, ast_malloc, io_context::current_ioc, io_context::fdcnt, io_context::fds, GROW_SHRINK_SIZE, io_context::ior, io_context::maxfdcnt, io_context::needshrink, NULL, and tmp().
Referenced by load_module(), and mbl_load_adapter().
 {
    struct io_context *tmp = NULL;
    if (!(tmp = ast_malloc(sizeof(*tmp))))
       return NULL;
    tmp->needshrink = 0;
    tmp->fdcnt = 0;
    tmp->maxfdcnt = GROW_SHRINK_SIZE/2;
    tmp->current_ioc = -1;
    if (!(tmp->fds = ast_calloc(1, (GROW_SHRINK_SIZE / 2) * sizeof(*tmp->fds)))) {
       ast_free(tmp);
       tmp = NULL;
    } else {
       if (!(tmp->ior = ast_calloc(1, (GROW_SHRINK_SIZE / 2) * sizeof(*tmp->ior)))) {
          ast_free(tmp->fds);
          ast_free(tmp);
          tmp = NULL;
       }
    }
    return tmp;
 }
io_context_destroy()
void io_context_destroy (struct io_context * ioc)
Destroys a context.
Parameters
ioc structure to destroy Destroy a context for I/O operations Frees all memory associated with the given io_context structure along with the structure itself
Definition at line 107 of file io.c.
References ast_free, io_context::fds, and io_context::ior.
Referenced by load_module(), mbl_load_adapter(), and unload_module().
 {
    /* Free associated memory with an I/O context */
    if (ioc->fds)
       ast_free(ioc->fds);
    if (ioc->ior)
       ast_free(ioc->ior);
    ast_free(ioc);
 }
io_grow()
static int io_grow (struct io_context * ioc) static
Grow the size of our arrays.
Returns
0 on success or -1 on failure
Definition at line 122 of file io.c.
References ast_debug, ast_realloc, DEBUG, io_context::fds, GROW_SHRINK_SIZE, io_context::ior, io_context::maxfdcnt, and tmp().
Referenced by ast_io_add().
 {
    void *tmp;
    DEBUG(ast_debug(1, "io_grow()\n"));
    ioc->maxfdcnt += GROW_SHRINK_SIZE;
    if ((tmp = ast_realloc(ioc->ior, (ioc->maxfdcnt + 1) * sizeof(*ioc->ior)))) {
       ioc->ior = tmp;
       if ((tmp = ast_realloc(ioc->fds, (ioc->maxfdcnt + 1) * sizeof(*ioc->fds)))) {
          ioc->fds = tmp;
       } else {
          /*
           * Failed to allocate enough memory for the pollfd.  Not
           * really any need to shrink back the iorec's as we'll
           * probably want to grow them again soon when more memory
           * is available, and then they'll already be the right size
           */
          ioc->maxfdcnt -= GROW_SHRINK_SIZE;
          return -1;
       }
    } else {
       /*
        * Memory allocation failure.  We return to the old size, and
        * return a failure
        */
       ioc->maxfdcnt -= GROW_SHRINK_SIZE;
       return -1;
    }
    return 0;
 }
io_shrink()
static int io_shrink (struct io_context * ioc) static
Definition at line 218 of file io.c.
References io_context::fdcnt, io_context::fds, io_rec::id, io_context::ior, and io_context::needshrink.
Referenced by ast_io_remove(), and ast_io_wait().
 {
    int getfrom, putto = 0;
    /*
     * Bring the fields from the very last entry to cover over
     * the entry we are removing, then decrease the size of the
     * arrays by one.
     */
    for (getfrom = 0; getfrom < ioc->fdcnt; getfrom++) {
       if (ioc->ior[getfrom].id) {
          /* In use, save it */
          if (getfrom != putto) {
             ioc->fds[putto] = ioc->fds[getfrom];
             ioc->ior[putto] = ioc->ior[getfrom];
             *(ioc->ior[putto].id) = putto;
          }
          putto++;
       }
    }
    ioc->fdcnt = putto;
    ioc->needshrink = 0;
    /* FIXME: We should free some memory if we have lots of unused
       io structs */
    return 0;
 }