Asterisk - The Open Source Telephony Project: rpe.c File Reference
rpe.c File Reference
#include <stdio.h>
#include <assert.h>
#include "private.h"
#include "gsm.h"
#include "proto.h"
Macros
#define STEP(i, H) (e[ k + i ] * (longword)H)
#define STEP(m, i)
Functions
static void Weighting_filter P2 ((e, x), register word *e, word *x)
static void RPE_grid_selection P3 ((x, xM, Mc_out), word *x, word *xM, word *Mc_out)
static void APCM_quantization_xmaxc_to_exp_mant P3 ((xmaxc, exp_out, mant_out), word xmaxc, word *exp_out, word *mant_out)
static void RPE_grid_positioning P3 ((Mc, xMp, ep), word Mc, register word *xMp, register word *ep)
static void APCM_inverse_quantization P4 ((xMc, mant, exp, xMp), register word *xMc, word mant, word exp, register word *xMp)
static void APCM_quantization P5 ((xM, xMc, mant_out, exp_out, xmaxc_out), word *xM, word *xMc, word *mant_out, word *exp_out, word *xmaxc_out)
void Gsm_RPE_Encoding P5 ((S, e, xmaxc, Mc, xMc), struct gsm_state *S, word *e, word *xmaxc, word *Mc, word *xMc)
void Gsm_RPE_Decoding P5 ((S, xmaxcr, Mcr, xMcr, erp), struct gsm_state *S, word xmaxcr, word Mcr, word *xMcr, word *erp)
Macro Definition Documentation
STEP [1/2]
#define STEP (i, H) (e[ k + i ] * (longword)H)
Referenced by P2(), and P3().
STEP [2/2]
#define STEP (m, i)
Value:
L_temp = SASR(x[m + 3 * i], 2);   \
            L_result += L_temp * L_temp;
Function Documentation
P2()
static void Weighting_filter P2 ((e, x) , register word * e, word * x) static
Definition at line 24 of file rpe.c.
References MAX_WORD, MIN_WORD, SASR, and STEP.
 {
    /* word        wt[ 50 ]; */
    register longword L_result;
    register int      k /* , i */ ;
    /*  Initialization of a temporary working array wt[0...49]
     */
    /* for (k =  0; k <=  4; k++) wt[k] = 0;
     * for (k =  5; k <= 44; k++) wt[k] = *e++;
     * for (k = 45; k <= 49; k++) wt[k] = 0;
     *
     *  (e[-5..-1] and e[40..44] are allocated by the caller,
     *  are initially zero and are not written anywhere.)
     */
    e -= 5;
    /*  Compute the signal x[0..39]
     */
    for (k = 0; k <= 39; k++) {
       L_result = 8192 >> 1;
       /* for (i = 0; i <= 10; i++) {
        * L_temp   = GSM_L_MULT( wt[k+i], gsm_H[i] );
        * L_result = GSM_L_ADD( L_result, L_temp );
        * }
        */
 #undef   STEP
 #define  STEP( i, H )   (e[ k + i ] * (longword)H)
       /*  Every one of these multiplications is done twice --
        *  but I don't see an elegant way to optimize this.
        *  Do you?
        */
 #ifdef   STUPID_COMPILER
       L_result += STEP( 0,    -134 ) ;
       L_result += STEP( 1,    -374 )  ;
                   /* + STEP(  2,    0    )  */
       L_result += STEP( 3,    2054 ) ;
       L_result += STEP( 4,    5741 ) ;
       L_result += STEP( 5,    8192 ) ;
       L_result += STEP( 6,    5741 ) ;
       L_result += STEP( 7,    2054 ) ;
              /* + STEP( 8,    0    )  */
       L_result += STEP( 9,    -374 ) ;
       L_result += STEP( 10,   -134 ) ;
 #else
       L_result +=
         STEP(  0,    -134 )
       + STEP(  1,    -374 )
         /* + STEP(   2,    0    )  */
       + STEP(  3,    2054 )
       + STEP(  4,    5741 )
       + STEP(  5,    8192 )
       + STEP(  6,    5741 )
       + STEP(  7,    2054 )
         /* + STEP(   8,    0    )  */
       + STEP(  9,    -374 )
       + STEP(10,  -134 )
       ;
 #endif
       /* L_result = GSM_L_ADD( L_result, L_result ); (* scaling(x2) *)
        * L_result = GSM_L_ADD( L_result, L_result ); (* scaling(x4) *)
        *
        * x[k] = SASR( L_result, 16 );
        */
       /* 2 adds vs. >>16 => 14, minus one shift to compensate for
        * those we lost when replacing L_MULT by '*'.
        */
       L_result = SASR( L_result, 13 );
       x[k] =  (word)(  L_result < MIN_WORD ? MIN_WORD
          : (L_result > MAX_WORD ? MAX_WORD : L_result ));
    }
 }
P3() [1/3]
static void RPE_grid_selection P3 ((x, xM, Mc_out) , word * x, word * xM, word * Mc_out) static
Definition at line 119 of file rpe.c.
References Mc, and STEP.
Referenced by P3().
 {
    /* register word  temp1;   */
    register int      /* m, */  i;
    register longword L_result, L_temp;
    longword    EM;   /* xxx should be L_EM? */
    word        Mc;
    longword    L_common_0_3;
    EM = 0;
    Mc = 0;
    /* for (m = 0; m <= 3; m++) {
     * L_result = 0;
     *
     *
     * for (i = 0; i <= 12; i++) {
     *
     *    temp1    = SASR( x[m + 3*i], 2 );
     *
     *    assert(temp1 != MIN_WORD);
     *
     *    L_temp   = GSM_L_MULT( temp1, temp1 );
     *    L_result = GSM_L_ADD( L_temp, L_result );
     * }
     *
     * if (L_result > EM) {
     *    Mc = m;
     *    EM = L_result;
     * }
     * }
     */
 #undef   STEP
 #define  STEP( m, i )      L_temp = SASR( x[m + 3 * i], 2 );   \
             L_result += L_temp * L_temp;
    /* common part of 0 and 3 */
    L_result = 0;
    STEP( 0, 1 ); STEP( 0, 2 ); STEP( 0, 3 ); STEP( 0, 4 );
    STEP( 0, 5 ); STEP( 0, 6 ); STEP( 0, 7 ); STEP( 0, 8 );
    STEP( 0, 9 ); STEP( 0, 10); STEP( 0, 11); STEP( 0, 12);
    L_common_0_3 = L_result;
    /* i = 0 */
    STEP( 0, 0 );
    L_result <<= 1;   /* implicit in L_MULT */
    EM = L_result;
    /* i = 1 */
    L_result = 0;
    STEP( 1, 0 );
    STEP( 1, 1 ); STEP( 1, 2 ); STEP( 1, 3 ); STEP( 1, 4 );
    STEP( 1, 5 ); STEP( 1, 6 ); STEP( 1, 7 ); STEP( 1, 8 );
    STEP( 1, 9 ); STEP( 1, 10); STEP( 1, 11); STEP( 1, 12);
    L_result <<= 1;
    if (L_result > EM) {
       Mc = 1;
       EM = L_result;
    }
    /* i = 2 */
    L_result = 0;
    STEP( 2, 0 );
    STEP( 2, 1 ); STEP( 2, 2 ); STEP( 2, 3 ); STEP( 2, 4 );
    STEP( 2, 5 ); STEP( 2, 6 ); STEP( 2, 7 ); STEP( 2, 8 );
    STEP( 2, 9 ); STEP( 2, 10); STEP( 2, 11); STEP( 2, 12);
    L_result <<= 1;
    if (L_result > EM) {
       Mc = 2;
       EM = L_result;
    }
    /* i = 3 */
    L_result = L_common_0_3;
    STEP( 3, 12 );
    L_result <<= 1;
    if (L_result > EM) {
       Mc = 3;
       EM = L_result;
    }
    /**/
    /*  Down-sampling by a factor 3 to get the selected xM[0..12]
     *  RPE sequence.
     */
    for (i = 0; i <= 12; i ++) xM[i] = x[Mc + 3*i];
    *Mc_out = Mc;
 }
P3() [2/3]
static void APCM_quantization_xmaxc_to_exp_mant P3 ((xmaxc, exp_out, mant_out) , word xmaxc, word * exp_out, word * mant_out) static
Definition at line 226 of file rpe.c.
References SASR.
 {
    word  exp, mant;
    /* Compute exponent and mantissa of the decoded version of xmaxc
     */
    exp = 0;
    if (xmaxc > 15) exp = SASR(xmaxc, 3) - 1;
    mant = xmaxc - (exp << 3);
    if (mant == 0) {
       exp  = -4;
       mant = 7;
    }
    else {
       while (mant <= 7) {
          mant = mant << 1 | 1;
          exp--;
       }
       mant -= 8;
    }
    assert( exp  >= -4 && exp <= 6 );
    assert( mant >= 0 && mant <= 7 );
    *exp_out  = exp;
    *mant_out = mant;
 }
P3() [3/3]
static void RPE_grid_positioning P3 ((Mc, xMp, ep) , word Mc, register word * xMp, register word * ep) static
Definition at line 389 of file rpe.c.
References P3().
 {
    int   i = 13;
    assert(0 <= Mc && Mc <= 3);
         switch (Mc) {
                 case 3: *ep++ = 0;
                 case 2:  do {
                                 *ep++ = 0;
                 case 1:         *ep++ = 0;
                 case 0:         *ep++ = *xMp++;
                          } while (--i);
         }
         while (++Mc < 4) *ep++ = 0;
    /*
    int i, k;
    for (k = 0; k <= 39; k++) ep[k] = 0;
    for (i = 0; i <= 12; i++) {
       ep[ Mc + (3*i) ] = xMp[i];
    }
    */
 }
P4()
static void APCM_inverse_quantization P4 ((xMc, mant, exp, xMp) , register word * xMc, word mant, word exp, register word * xMp) static
Definition at line 352 of file rpe.c.
References GSM_ADD(), gsm_FAC, and GSM_MULT_R.
 {
    int   i;
    word  temp, temp1, temp2, temp3;
    assert( mant >= 0 && mant <= 7 );
    temp1 = gsm_FAC[ mant ];   /* see 4.2-15 for mant */
    temp2 = gsm_sub( 6, exp ); /* see 4.2-15 for exp  */
    temp3 = gsm_asl( 1, gsm_sub( temp2, 1 ));
    for (i = 13; i--;) {
       assert( *xMc <= 7 && *xMc >= 0 );   /* 3 bit unsigned */
       /* temp = gsm_sub( *xMc++ << 1, 7 ); */
       temp = (*xMc++ << 1) - 7;          /* restore sign   */
       assert( temp <= 7 && temp >= -7 );  /* 4 bit signed   */
       temp <<= 12;            /* 16 bit signed  */
       temp = (word)GSM_MULT_R( temp1, temp );
       temp = GSM_ADD( temp, temp3 );
       *xMp++ = gsm_asr( temp, temp2 );
    }
 }
P5() [1/3]
static void APCM_quantization P5 ((xM, xMc, mant_out, exp_out, xmaxc_out) , word * xM, word * xMc, word * mant_out, word * exp_out, word * xmaxc_out) static
Definition at line 259 of file rpe.c.
References GSM_ABS, GSM_MULT, gsm_NRFAC, SASR, and xmaxc.
 {
    int   i, itest;
    word  xmax, xmaxc, temp, temp1, temp2;
    word  exp, mant;
    /*  Find the maximum absolute value xmax of xM[0..12].
     */
    xmax = 0;
    for (i = 0; i <= 12; i++) {
       temp = xM[i];
       temp = GSM_ABS(temp);
       if (temp > xmax) xmax = temp;
    }
    /*  Qantizing and coding of xmax to get xmaxc.
     */
    exp   = 0;
    temp  = SASR( xmax, 9 );
    itest = 0;
    for (i = 0; i <= 5; i++) {
       itest |= (temp <= 0);
       temp = SASR( temp, 1 );
       assert(exp <= 5);
       if (itest == 0) exp++;     /* exp = add (exp, 1) */
    }
    assert(exp <= 6 && exp >= 0);
    temp = exp + 5;
    assert(temp <= 11 && temp >= 0);
    xmaxc = gsm_add( SASR(xmax, temp), exp << 3 );
    /*   Quantizing and coding of the xM[0..12] RPE sequence
     *   to get the xMc[0..12]
     */
    APCM_quantization_xmaxc_to_exp_mant( xmaxc, &exp, &mant );
    /*  This computation uses the fact that the decoded version of xmaxc
     *  can be calculated by using the exponent and the mantissa part of
     *  xmaxc (logarithmic table).
     *  So, this method avoids any division and uses only a scaling
     *  of the RPE samples by a function of the exponent.  A direct
     *  multiplication by the inverse of the mantissa (NRFAC[0..7]
     *  found in table 4.5) gives the 3 bit coded version xMc[0..12]
     *  of the RPE samples.
     */
    /* Direct computation of xMc[0..12] using table 4.5
     */
    assert( exp <= 4096 && exp >= -4096);
    assert( mant >= 0 && mant <= 7 );
    temp1 = 6 - exp;     /* normalization by the exponent */
    temp2 = gsm_NRFAC[ mant ];    /* inverse mantissa      */
    for (i = 0; i <= 12; i++) {
       assert(temp1 >= 0 && temp1 < 16);
       temp = xM[i] << temp1;
       temp = (word)GSM_MULT( temp, temp2 );
       temp = SASR(temp, 12);
       xMc[i] = temp + 4;      /* see note below */
    }
    /*  NOTE: This equation is used to make all the xMc[i] positive.
     */
    *mant_out  = mant;
    *exp_out   = exp;
    *xmaxc_out = xmaxc;
 }
P5() [2/3]
void Gsm_RPE_Encoding P5 ((S, e, xmaxc, Mc, xMc) , struct gsm_state * S, word * e, word * xmaxc, word * Mc, word * xMc)
Definition at line 451 of file rpe.c.
 {
    word  x[40];
    word  xM[13], xMp[13];
    word  mant, exp;
    Weighting_filter(e, x);
    RPE_grid_selection(x, xM, Mc);
    APCM_quantization(   xM, xMc, &mant, &exp, xmaxc);
    APCM_inverse_quantization(  xMc,  mant,  exp, xMp);
    RPE_grid_positioning( *Mc, xMp, e );
 }
P5() [3/3]
void Gsm_RPE_Decoding P5 ((S, xmaxcr, Mcr, xMcr, erp) , struct gsm_state * S, word xmaxcr, word Mcr, word * xMcr, word * erp)
Definition at line 474 of file rpe.c.
 {
    word  exp, mant;
    word  xMp[ 13 ];
    APCM_quantization_xmaxc_to_exp_mant( xmaxcr, &exp, &mant );
    APCM_inverse_quantization( xMcr, mant, exp, xMp );
    RPE_grid_positioning( Mcr, xMp, erp );
 }