Asterisk - The Open Source Telephony Project: pbx_private.h File Reference
pbx_private.h File Reference
Private include file for pbx.
Macros
#define VAR_BUF_SIZE 4096
Functions
const char * app_name (struct ast_app *app)
AST_VECTOR (ast_ignorepats, struct ast_ignorepat *)
AST_VECTOR (ast_includes, struct ast_include *)
AST_VECTOR (ast_sws, struct ast_sw *)
struct ast_ignorepat * ignorepat_alloc (const char *value, const char *registrar)
void ignorepat_free (struct ast_ignorepat *ip)
struct ast_include * include_alloc (const char *value, const char *registrar)
void include_free (struct ast_include *inc)
const char * include_rname (const struct ast_include *inc)
int include_valid (const struct ast_include *inc)
int indicate_busy (struct ast_channel *, const char *)
int indicate_congestion (struct ast_channel *, const char *)
struct ast_switch * pbx_findswitch (const char *sw)
int raise_exception (struct ast_channel *chan, const char *reason, int priority)
void set_ext_pri (struct ast_channel *c, const char *exten, int pri)
struct ast_sw * sw_alloc (const char *value, const char *data, int eval, const char *registrar)
void sw_free (struct ast_sw *sw)
void unreference_cached_app (struct ast_app *app)
void wait_for_hangup (struct ast_channel *chan, const void *data)
Detailed Description
Private include file for pbx.
Definition in file pbx_private.h.
Macro Definition Documentation
VAR_BUF_SIZE
#define VAR_BUF_SIZE 4096
Definition at line 68 of file pbx_private.h.
Referenced by ast_add_extension2_lockopt(), ast_func_read2(), pbx_builtin_importvar(), and pbx_substitute_variables_helper_full().
Function Documentation
app_name()
const char* app_name (struct ast_app * app)
pbx_app.c functions needed by pbx.c
Definition at line 463 of file pbx_app.c.
Referenced by _ast_bridge_channel_unlock(), app_exec(), app_subscribe(), app_unsubscribe(), ast_ari_callback(), AST_TEST_DEFINE(), bridge_stasis_run_cb(), lua_pbx_exec(), lua_pbx_findapp(), pbx_extension_helper(), and stasis_app_set_global_debug().
 {
    return app->name;
 }
AST_VECTOR() [1/3]
AST_VECTOR (ast_ignorepats , struct ast_ignorepat *)
AST_VECTOR() [2/3]
AST_VECTOR (ast_includes , struct ast_include *)
AST_VECTOR() [3/3]
AST_VECTOR (ast_sws , struct ast_sw *)
ignorepat_alloc()
struct ast_ignorepat* ignorepat_alloc (const char * value, const char * registrar)
Definition at line 52 of file pbx_ignorepat.c.
References ast_calloc, NULL, ast_ignorepat::pattern, and ast_ignorepat::registrar.
Referenced by ast_context_add_ignorepat2().
 {
    struct ast_ignorepat *ignorepat;
    int length = strlen(value) + 1;
    char *pattern;
    /* allocate new include structure ... */
    ignorepat = ast_calloc(1, sizeof(*ignorepat) + length);
    if (!ignorepat) {
       return NULL;
    }
    /* The cast to char * is because we need to write the initial value.
     * The field is not supposed to be modified otherwise.  Also, gcc 4.2
     * sees the cast as dereferencing a type-punned pointer and warns about
     * it.  This is the workaround (we're telling gcc, yes, that's really
     * what we wanted to do).
     */
    pattern = (char *) ignorepat->pattern;
    strcpy(pattern, value);
    ignorepat->registrar = registrar;
    return ignorepat;
 }
ignorepat_free()
void ignorepat_free (struct ast_ignorepat * ip)
Definition at line 77 of file pbx_ignorepat.c.
References ast_free.
Referenced by __ast_context_destroy(), __ast_internal_context_destroy(), ast_context_add_ignorepat2(), and ast_context_remove_ignorepat2().
 {
    ast_free(ip);
 }
include_alloc()
struct ast_include* include_alloc (const char * value, const char * registrar)
Allocate and initialize an ast_include.
Definition at line 74 of file pbx_include.c.
References ast_build_timing(), ast_calloc, c, ast_include::hastime, ast_include::name, NULL, ast_include::registrar, ast_include::rname, ast_include::stuff, and ast_include::timing.
Referenced by ast_context_add_include2().
 {
    struct ast_include *new_include;
    char *c;
    int valuebufsz = strlen(value) + 1;
    char *p;
    /* allocate new include structure ... */
    new_include = ast_calloc(1, sizeof(*new_include) + (valuebufsz * 2));
    if (!new_include) {
       return NULL;
    }
    /* Fill in this structure. Use 'p' for assignments, as the fields
     * in the structure are 'const char *'
     */
    p = new_include->stuff;
    new_include->name = p;
    strcpy(p, value);
    p += valuebufsz;
    new_include->rname = p;
    strcpy(p, value);
    /* Strip off timing info, and process if it is there */
    if ((c = strchr(p, ',')) ) {
       *c++ = '\0';
       new_include->hastime = ast_build_timing(&(new_include->timing), c);
    }
    new_include->registrar = registrar;
    return new_include;
 }
include_free()
void include_free (struct ast_include * inc)
Free an ast_include and associated data.
Definition at line 106 of file pbx_include.c.
References ast_destroy_timing(), ast_free, and ast_include::timing.
Referenced by __ast_context_destroy(), __ast_internal_context_destroy(), ast_context_add_include2(), and ast_context_remove_include2().
 {
    ast_destroy_timing(&(inc->timing));
    ast_free(inc);
 }
include_rname()
const char* include_rname (const struct ast_include * inc)
Definition at line 55 of file pbx_include.c.
References NULL, and ast_include::rname.
Referenced by ast_context_verify_includes(), and pbx_find_extension().
 {
    return inc ? inc->rname : NULL;
 }
include_valid()
int include_valid (const struct ast_include * inc)
Definition at line 65 of file pbx_include.c.
References ast_check_timing(), ast_include::hastime, and ast_include::timing.
Referenced by pbx_find_extension().
 {
    if (!inc->hastime) {
       return 1;
    }
    return ast_check_timing(&(inc->timing));
 }
pbx_findswitch()
struct ast_switch* pbx_findswitch (const char * sw)
pbx_switch.c functions needed by pbx.c
Definition at line 40 of file pbx_switch.c.
References AST_RWLIST_RDLOCK, AST_RWLIST_TRAVERSE, AST_RWLIST_UNLOCK, ast_switch::list, and ast_switch::name.
Referenced by ast_check_timing(), and pbx_find_extension().
 {
    struct ast_switch *asw;
    AST_RWLIST_RDLOCK(&switches);
    AST_RWLIST_TRAVERSE(&switches, asw, list) {
       if (!strcasecmp(asw->name, sw))
          break;
    }
    AST_RWLIST_UNLOCK(&switches);
    return asw;
 }
raise_exception()
int raise_exception (struct ast_channel * chan, const char * reason, int priority)
pbx.c functions needed by pbx_builtins.c
Definition at line 2806 of file pbx.c.
References ast_calloc_with_stringfields, ast_channel_context(), ast_channel_datastore_add(), ast_channel_datastore_find(), ast_channel_exten(), ast_channel_priority(), ast_datastore_alloc, ast_datastore_free(), ast_string_field_set, ast_datastore::data, ast_exten::exten, NULL, pbx_exception::priority, and set_ext_pri().
Referenced by __ast_pbx_run(), pbx_builtin_raise_exception(), and pbx_builtin_waitexten().
 {
    struct ast_datastore *ds = ast_channel_datastore_find(chan, &exception_store_info, NULL);
    struct pbx_exception *exception = NULL;
    if (!ds) {
       ds = ast_datastore_alloc(&exception_store_info, NULL);
       if (!ds)
          return -1;
       if (!(exception = ast_calloc_with_stringfields(1, struct pbx_exception, 128))) {
          ast_datastore_free(ds);
          return -1;
       }
       ds->data = exception;
       ast_channel_datastore_add(chan, ds);
    } else
       exception = ds->data;
    ast_string_field_set(exception, reason, reason);
    ast_string_field_set(exception, context, ast_channel_context(chan));
    ast_string_field_set(exception, exten, ast_channel_exten(chan));
    exception->priority = ast_channel_priority(chan);
    set_ext_pri(chan, "e", priority);
    return 0;
 }
set_ext_pri()
void set_ext_pri (struct ast_channel * c, const char * exten, int pri)
helper function to set extension and priority
Definition at line 4268 of file pbx.c.
References ast_channel_exten_set(), ast_channel_lock, ast_channel_priority_set(), and ast_channel_unlock.
Referenced by __ast_pbx_run(), pbx_builtin_waitexten(), and raise_exception().
 {
    ast_channel_lock(c);
    ast_channel_exten_set(c, exten);
    ast_channel_priority_set(c, pri);
    ast_channel_unlock(c);
 }
sw_alloc()
struct ast_sw* sw_alloc (const char * value, const char * data, int eval, const char * registrar)
Definition at line 68 of file pbx_sw.c.
References ast_calloc, ast_sw::data, ast_sw::eval, ast_sw::name, NULL, ast_sw::registrar, and ast_sw::stuff.
Referenced by ast_context_add_switch2().
 {
    struct ast_sw *new_sw;
    int length;
    char *p;
    if (!data) {
       data = "";
    }
    length = sizeof(struct ast_sw);
    length += strlen(value) + 1;
    length += strlen(data) + 1;
    /* allocate new sw structure ... */
    if (!(new_sw = ast_calloc(1, length))) {
       return NULL;
    }
    /* ... fill in this structure ... */
    p = new_sw->stuff;
    new_sw->name = p;
    strcpy(p, value);
    p += strlen(value) + 1;
    new_sw->data = p;
    strcpy(p, data);
    new_sw->eval     = eval;
    new_sw->registrar = registrar;
    return new_sw;
 }
sw_free()
void sw_free (struct ast_sw * sw)
Definition at line 101 of file pbx_sw.c.
References ast_free.
Referenced by __ast_context_destroy(), __ast_internal_context_destroy(), ast_context_add_switch2(), and ast_context_remove_switch2().
 {
    ast_free(sw);
 }
unreference_cached_app()
void unreference_cached_app (struct ast_app * app)
pbx.c function needed by pbx_app.c
Definition at line 6179 of file pbx.c.
References ast_rdlock_contexts(), ast_unlock_contexts(), ast_walk_context_extensions(), ast_walk_contexts(), ast_walk_extension_priorities(), and NULL.
Referenced by ast_unregister_application().
 {
    struct ast_context *context = NULL;
    struct ast_exten *eroot = NULL, *e = NULL;
    ast_rdlock_contexts();
    while ((context = ast_walk_contexts(context))) {
       while ((eroot = ast_walk_context_extensions(context, eroot))) {
          while ((e = ast_walk_extension_priorities(eroot, e))) {
             if (e->cached_app == app)
                e->cached_app = NULL;
          }
       }
    }
    ast_unlock_contexts();
    return;
 }
wait_for_hangup()
void wait_for_hangup (struct ast_channel * chan, const void * data)
Definition at line 8267 of file pbx.c.
References ast_frfree, ast_read(), ast_safe_sleep(), ast_strlen_zero, and ast_waitfor().
Referenced by indicate_busy(), and indicate_congestion().
 {
    int res;
    struct ast_frame *f;
    double waitsec;
    int waittime;
    if (ast_strlen_zero(data) || (sscanf(data, "%30lg", &waitsec) != 1) || (waitsec < 0))
       waitsec = -1;
    if (waitsec > -1) {
       waittime = waitsec * 1000.0;
       ast_safe_sleep(chan, waittime);
    } else do {
       res = ast_waitfor(chan, -1);
       if (res < 0)
          return;
       f = ast_read(chan);
       if (f)
          ast_frfree(f);
    } while(f);
 }