Asterisk - The Open Source Telephony Project: res_pjsip_caller_id.c File Reference
res_pjsip_caller_id.c File Reference
#include "asterisk.h"
#include <pjsip.h>
#include <pjsip_ua.h>
#include "asterisk/res_pjsip.h"
#include "asterisk/res_pjsip_session.h"
#include "asterisk/channel.h"
#include "asterisk/module.h"
#include "asterisk/callerid.h"
#include "asterisk/conversions.h"
Macros
#define MAX_OLI_DIGITS 2
Functions
static void __reg_module (void)
static void __unreg_module (void)
static void add_id_headers (const struct ast_sip_session *session, pjsip_tx_data *tdata, const struct ast_party_id *id)
static void add_pai_header (const struct ast_sip_session *session, pjsip_tx_data *tdata, const struct ast_party_id *id)
static void add_party_param (pjsip_tx_data *tdata, pjsip_fromto_hdr *hdr, const struct ast_sip_session *session)
static void add_privacy_header (pjsip_tx_data *tdata, const struct ast_party_id *id)
static void add_privacy_params (pjsip_tx_data *tdata, pjsip_fromto_hdr *hdr, const struct ast_party_id *id)
static void add_rpid_header (const struct ast_sip_session *session, pjsip_tx_data *tdata, const struct ast_party_id *id)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int caller_id_incoming_request (struct ast_sip_session *session, pjsip_rx_data *rdata)
static void caller_id_incoming_response (struct ast_sip_session *session, pjsip_rx_data *rdata)
static void caller_id_outgoing_request (struct ast_sip_session *session, pjsip_tx_data *tdata)
static void caller_id_outgoing_response (struct ast_sip_session *session, pjsip_tx_data *tdata)
static pjsip_fromto_hdr * create_new_id_hdr (const pj_str_t *hdr_name, pjsip_fromto_hdr *base, pjsip_tx_data *tdata, const struct ast_party_id *id)
static pjsip_fromto_hdr * get_id_header (pjsip_rx_data *rdata, const pj_str_t *header_name)
static int load_module (void)
static void queue_connected_line_update (struct ast_sip_session *session, const struct ast_party_id *id)
static int set_id_from_from (struct pjsip_rx_data *rdata, struct ast_party_id *id)
static void set_id_from_hdr (pjsip_fromto_hdr *hdr, struct ast_party_id *id)
static int set_id_from_oli (pjsip_rx_data *rdata, int *ani2)
static int set_id_from_pai (pjsip_rx_data *rdata, struct ast_party_id *id)
static int set_id_from_rpid (pjsip_rx_data *rdata, struct ast_party_id *id)
static int should_queue_connected_line_update (const struct ast_sip_session *session, const struct ast_party_id *id)
static int unload_module (void)
static void update_incoming_connected_line (struct ast_sip_session *session, pjsip_rx_data *rdata)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "PJSIP Caller ID Support" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_APP_DEPEND, .requires = "res_pjsip,res_pjsip_session", }
static const struct ast_module_info * ast_module_info = &__mod_info
static struct ast_sip_session_supplement caller_id_supplement
Macro Definition Documentation
MAX_OLI_DIGITS
#define MAX_OLI_DIGITS 2
Referenced by set_id_from_oli().
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 861 of file res_pjsip_caller_id.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 861 of file res_pjsip_caller_id.c.
add_id_headers()
static void add_id_headers (const struct ast_sip_session * session, pjsip_tx_data * tdata, const struct ast_party_id * id) static
Definition at line 756 of file res_pjsip_caller_id.c.
References add_pai_header(), add_rpid_header(), ast_party_id_presentation(), AST_PRES_ALLOWED, AST_PRES_RESTRICTION, ast_sip_session::endpoint, ast_sip_endpoint::id, ast_party_id::number, ast_sip_endpoint_id_configuration::send_pai, ast_sip_endpoint_id_configuration::send_rpid, ast_sip_endpoint_id_configuration::trust_outbound, and ast_party_number::valid.
Referenced by caller_id_outgoing_request(), and caller_id_outgoing_response().
 {
    if (!id->number.valid
       || (!session->endpoint->id.trust_outbound
          && (ast_party_id_presentation(id) & AST_PRES_RESTRICTION) != AST_PRES_ALLOWED)) {
       return;
    }
    if (session->endpoint->id.send_pai) {
       add_pai_header(session, tdata, id);
    }
    if (session->endpoint->id.send_rpid) {
       add_rpid_header(session, tdata, id);
    }
 }
add_pai_header()
static void add_pai_header (const struct ast_sip_session * session, pjsip_tx_data * tdata, const struct ast_party_id * id) static
Definition at line 563 of file res_pjsip_caller_id.c.
References add_privacy_header(), ast_sip_modify_id_header(), create_new_id_hdr(), NULL, and ast_sip_session::saved_from_hdr.
Referenced by add_id_headers().
 {
    static const pj_str_t pj_pai_name = { "P-Asserted-Identity", 19 };
    pjsip_fromto_hdr *base;
    pjsip_fromto_hdr *pai_hdr;
    pjsip_fromto_hdr *old_pai;
    /* Since inv_session reuses responses, we have to make sure there's not already
     * a P-Asserted-Identity present. If there is, we just modify the old one.
     */
    old_pai = pjsip_msg_find_hdr_by_name(tdata->msg, &pj_pai_name, NULL);
    if (old_pai) {
       /* If type is OTHER, then the existing header was most likely
        * added by the PJSIP_HEADER dial plan function as a simple
        * name/value pair.  We can't pass this to modify_id_header because
        * there are no virtual functions to get the uri.  We could parse
        * it into a pjsip_fromto_hdr but it isn't worth it since
        * modify_id_header is just going to overwrite the name and number
        * anyway.  We'll just remove it from the header list instead
        * and create a new one.
        */
       if (old_pai->type == PJSIP_H_OTHER) {
          pj_list_erase(old_pai);
       } else {
          ast_sip_modify_id_header(tdata->pool, old_pai, id);
          add_privacy_header(tdata, id);
          return;
       }
    }
    if (tdata->msg->type == PJSIP_REQUEST_MSG) {
       base = session->saved_from_hdr ? session->saved_from_hdr : PJSIP_MSG_FROM_HDR(tdata->msg);
    } else {
       base = PJSIP_MSG_TO_HDR(tdata->msg);
    }
    pai_hdr = create_new_id_hdr(&pj_pai_name, base, tdata, id);
    if (!pai_hdr) {
       return;
    }
    add_privacy_header(tdata, id);
    pjsip_msg_add_hdr(tdata->msg, (pjsip_hdr *)pai_hdr);
 }
add_party_param()
static void add_party_param (pjsip_tx_data * tdata, pjsip_fromto_hdr * hdr, const struct ast_sip_session * session) static
Definition at line 616 of file res_pjsip_caller_id.c.
References ast_sip_session::inv_session.
Referenced by add_rpid_header().
 {
    static const pj_str_t party_str = { "party", 5 };
    static const pj_str_t calling_str = { "calling", 7 };
    static const pj_str_t called_str = { "called", 6 };
    pjsip_param *party;
    /* The party value can't change throughout the lifetime, so it is set only once */
    party = pjsip_param_find(&hdr->other_param, &party_str);
    if (party) {
       return;
    }
    party = PJ_POOL_ALLOC_T(tdata->pool, pjsip_param);
    party->name = party_str;
    party->value = (session->inv_session->role == PJSIP_ROLE_UAC) ? calling_str : called_str;
    pj_list_insert_before(&hdr->other_param, party);
 }
add_privacy_header()
static void add_privacy_header (pjsip_tx_data * tdata, const struct ast_party_id * id) static
Definition at line 538 of file res_pjsip_caller_id.c.
References ast_party_id_presentation(), AST_PRES_ALLOWED, AST_PRES_RESTRICTION, and NULL.
Referenced by add_pai_header().
 {
    static const pj_str_t pj_privacy_name = { "Privacy", 7 };
    static const pj_str_t pj_privacy_value = { "id", 2 };
    pjsip_hdr *old_privacy;
    old_privacy = pjsip_msg_find_hdr_by_name(tdata->msg, &pj_privacy_name, NULL);
    if ((ast_party_id_presentation(id) & AST_PRES_RESTRICTION) == AST_PRES_ALLOWED) {
       if (old_privacy) {
          pj_list_erase(old_privacy);
       }
    } else if (!old_privacy) {
       pjsip_generic_string_hdr *privacy_hdr = pjsip_generic_string_hdr_create(
             tdata->pool, &pj_privacy_name, &pj_privacy_value);
       pjsip_msg_add_hdr(tdata->msg, (pjsip_hdr *)privacy_hdr);
    }
 }
add_privacy_params()
static void add_privacy_params (pjsip_tx_data * tdata, pjsip_fromto_hdr * hdr, const struct ast_party_id * id) static
Definition at line 647 of file res_pjsip_caller_id.c.
References ast_party_id_presentation(), AST_PRES_ALLOWED, AST_PRES_NUMBER_TYPE, AST_PRES_RESTRICTION, and AST_PRES_USER_NUMBER_PASSED_SCREEN.
Referenced by add_rpid_header().
 {
    static const pj_str_t privacy_str = { "privacy", 7 };
    static const pj_str_t screen_str = { "screen", 6 };
    static const pj_str_t privacy_full_str = { "full", 4 };
    static const pj_str_t privacy_off_str = { "off", 3 };
    static const pj_str_t screen_yes_str = { "yes", 3 };
    static const pj_str_t screen_no_str = { "no", 2 };
    pjsip_param *old_privacy;
    pjsip_param *old_screen;
    pjsip_param *privacy;
    pjsip_param *screen;
    int presentation;
    old_privacy = pjsip_param_find(&hdr->other_param, &privacy_str);
    old_screen = pjsip_param_find(&hdr->other_param, &screen_str);
    if (!old_privacy) {
       privacy = PJ_POOL_ALLOC_T(tdata->pool, pjsip_param);
       privacy->name = privacy_str;
       pj_list_insert_before(&hdr->other_param, privacy);
    } else {
       privacy = old_privacy;
    }
    if (!old_screen) {
       screen = PJ_POOL_ALLOC_T(tdata->pool, pjsip_param);
       screen->name = screen_str;
       pj_list_insert_before(&hdr->other_param, screen);
    } else {
       screen = old_screen;
    }
    presentation = ast_party_id_presentation(id);
    if ((presentation & AST_PRES_RESTRICTION) == AST_PRES_ALLOWED) {
       privacy->value = privacy_off_str;
    } else {
       privacy->value = privacy_full_str;
    }
    if ((presentation & AST_PRES_NUMBER_TYPE) == AST_PRES_USER_NUMBER_PASSED_SCREEN) {
       screen->value = screen_yes_str;
    } else {
       screen->value = screen_no_str;
    }
 }
add_rpid_header()
static void add_rpid_header (const struct ast_sip_session * session, pjsip_tx_data * tdata, const struct ast_party_id * id) static
Definition at line 699 of file res_pjsip_caller_id.c.
References add_party_param(), add_privacy_params(), ast_sip_modify_id_header(), create_new_id_hdr(), NULL, and ast_sip_session::saved_from_hdr.
Referenced by add_id_headers().
 {
    static const pj_str_t pj_rpid_name = { "Remote-Party-ID", 15 };
    pjsip_fromto_hdr *base;
    pjsip_fromto_hdr *rpid_hdr;
    pjsip_fromto_hdr *old_rpid;
    /* Since inv_session reuses responses, we have to make sure there's not already
     * a P-Asserted-Identity present. If there is, we just modify the old one.
     */
    old_rpid = pjsip_msg_find_hdr_by_name(tdata->msg, &pj_rpid_name, NULL);
    if (old_rpid) {
       /* If type is OTHER, then the existing header was most likely
        * added by the PJSIP_HEADER dial plan function as a simple
        * name/value pair.  We can't pass this to modify_id_header because
        * there are no virtual functions to get the uri.  We could parse
        * it into a pjsip_fromto_hdr but it isn't worth it since
        * modify_id_header is just going to overwrite the name and number
        * anyway.  We'll just remove it from the header list instead
        * and create a new one.
        */
       if (old_rpid->type == PJSIP_H_OTHER) {
          pj_list_erase(old_rpid);
       } else {
          ast_sip_modify_id_header(tdata->pool, old_rpid, id);
          add_party_param(tdata, old_rpid, session);
          add_privacy_params(tdata, old_rpid, id);
          return;
       }
    }
    if (tdata->msg->type == PJSIP_REQUEST_MSG) {
       base = session->saved_from_hdr ? session->saved_from_hdr : PJSIP_MSG_FROM_HDR(tdata->msg);
    } else {
       base = PJSIP_MSG_TO_HDR(tdata->msg);
    }
    rpid_hdr = create_new_id_hdr(&pj_rpid_name, base, tdata, id);
    if (!rpid_hdr) {
       return;
    }
    add_party_param(tdata, rpid_hdr, session);
    add_privacy_params(tdata, rpid_hdr, id);
    pjsip_msg_add_hdr(tdata->msg, (pjsip_hdr *)rpid_hdr);
 }
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 861 of file res_pjsip_caller_id.c.
caller_id_incoming_request()
static int caller_id_incoming_request (struct ast_sip_session * session, pjsip_rx_data * rdata) static
Definition at line 428 of file res_pjsip_caller_id.c.
References ast_sip_session::ani2, ast_free, ast_party_id_copy(), ast_strdup, ast_sip_session::channel, ast_sip_session::endpoint, ast_sip_session::id, ast_sip_endpoint::id, ast_party_id::number, ast_sip_endpoint_id_configuration::self, set_id_from_from(), set_id_from_oli(), set_id_from_pai(), set_id_from_rpid(), ast_party_id::tag, ast_sip_endpoint_id_configuration::trust_inbound, update_incoming_connected_line(), and ast_party_number::valid.
 {
    if (!session->channel) {
       int ani2;
       /*
        * Since we have no channel this must be the initial inbound
        * INVITE.  Set the session ID directly because the channel
        * has not been created yet.
        */
       if (session->endpoint->id.trust_inbound
          && (!set_id_from_pai(rdata, &session->id)
             || !set_id_from_rpid(rdata, &session->id))) {
          ast_free(session->id.tag);
          session->id.tag = ast_strdup(session->endpoint->id.self.tag);
          return 0;
       }
       ast_party_id_copy(&session->id, &session->endpoint->id.self);
       if (!session->endpoint->id.self.number.valid) {
          set_id_from_from(rdata, &session->id);
       }
       if (!set_id_from_oli(rdata, &ani2)) {
          session->ani2 = 0;
       }
    } else {
       /*
        * ReINVITE or UPDATE.  Check for changes to the ID and queue
        * a connected line update if necessary.
        */
       update_incoming_connected_line(session, rdata);
    }
    return 0;
 }
caller_id_incoming_response()
static void caller_id_incoming_response (struct ast_sip_session * session, pjsip_rx_data * rdata) static
Definition at line 471 of file res_pjsip_caller_id.c.
References ast_sip_session::channel, and update_incoming_connected_line().
 {
    if (!session->channel) {
       return;
    }
    update_incoming_connected_line(session, rdata);
 }
caller_id_outgoing_request()
static void caller_id_outgoing_request (struct ast_sip_session * session, pjsip_tx_data * tdata) static
Definition at line 782 of file res_pjsip_caller_id.c.
References add_id_headers(), ast_channel_connected_effective_id(), ast_channel_lock, ast_channel_unlock, ast_party_id_copy(), ast_party_id_free(), ast_party_id_init(), and ast_sip_session::channel.
 {
    struct ast_party_id effective_id;
    struct ast_party_id connected_id;
    if (!session->channel) {
       return;
    }
    ast_party_id_init(&connected_id);
    ast_channel_lock(session->channel);
    effective_id = ast_channel_connected_effective_id(session->channel);
    ast_party_id_copy(&connected_id, &effective_id);
    ast_channel_unlock(session->channel);
    add_id_headers(session, tdata, &connected_id);
    ast_party_id_free(&connected_id);
 }
caller_id_outgoing_response()
static void caller_id_outgoing_response (struct ast_sip_session * session, pjsip_tx_data * tdata) static
Definition at line 810 of file res_pjsip_caller_id.c.
References add_id_headers(), ast_channel_connected_effective_id(), ast_channel_lock, ast_channel_unlock, ast_party_id_copy(), ast_party_id_free(), ast_party_id_init(), ast_sip_session::channel, ast_sip_session::endpoint, ast_sip_endpoint::id, ast_sip_session::inv_session, and ast_sip_endpoint_id_configuration::send_connected_line.
 {
    struct ast_party_id effective_id;
    struct ast_party_id connected_id;
    if (!session->channel
       || (!session->endpoint->id.send_connected_line
          && session->inv_session
          && session->inv_session->state >= PJSIP_INV_STATE_EARLY)) {
       return;
    }
    /* Must do a deep copy unless we hold the channel lock the entire time. */
    ast_party_id_init(&connected_id);
    ast_channel_lock(session->channel);
    effective_id = ast_channel_connected_effective_id(session->channel);
    ast_party_id_copy(&connected_id, &effective_id);
    ast_channel_unlock(session->channel);
    add_id_headers(session, tdata, &connected_id);
    ast_party_id_free(&connected_id);
 }
create_new_id_hdr()
static pjsip_fromto_hdr* create_new_id_hdr (const pj_str_t * hdr_name, pjsip_fromto_hdr * base, pjsip_tx_data * tdata, const struct ast_party_id * id) static
Definition at line 488 of file res_pjsip_caller_id.c.
References ast_alloca, ast_escape_quoted(), ast_strlen_zero, ast_party_id::name, NULL, ast_party_id::number, ast_party_name::str, ast_party_number::str, ast_party_name::valid, and ast_party_number::valid.
Referenced by add_pai_header(), and add_rpid_header().
 {
    pjsip_fromto_hdr *id_hdr;
    pjsip_name_addr *id_name_addr;
    pjsip_sip_uri *id_uri;
    id_hdr = pjsip_from_hdr_create(tdata->pool);
    id_hdr->type = PJSIP_H_OTHER;
    id_hdr->sname = id_hdr->name = *hdr_name;
    id_name_addr = pjsip_uri_clone(tdata->pool, base->uri);
    id_uri = pjsip_uri_get_uri(id_name_addr->uri);
    if (id->name.valid && !ast_strlen_zero(id->name.str)) {
       int name_buf_len = strlen(id->name.str) * 2 + 1;
       char *name_buf = ast_alloca(name_buf_len);
       ast_escape_quoted(id->name.str, name_buf, name_buf_len);
       pj_strdup2(tdata->pool, &id_name_addr->display, name_buf);
    } else {
       /*
        * We need to clear the remnants of the clone or it'll be left set.
        * pj_strdup2 is safe to call with a NULL src and it resets both slen and ptr.
        */
       pj_strdup2(tdata->pool, &id_name_addr->display, NULL);
    }
    if (id->number.valid) {
       pj_strdup2(tdata->pool, &id_uri->user, id->number.str);
    } else {
       /* Similar to name, make sure the number is also cleared when invalid */
       pj_strdup2(tdata->pool, &id_uri->user, NULL);
    }
    id_hdr->uri = (pjsip_uri *) id_name_addr;
    return id_hdr;
 }
get_id_header()
static pjsip_fromto_hdr* get_id_header (pjsip_rx_data * rdata, const pj_str_t * header_name) static
Definition at line 98 of file res_pjsip_caller_id.c.
References ast_log, LOG_WARNING, and NULL.
Referenced by set_id_from_oli(), set_id_from_pai(), and set_id_from_rpid().
 {
    static const pj_str_t from = { "From", 4 };
    pj_str_t header_content;
    pjsip_fromto_hdr *parsed_hdr;
    pjsip_generic_string_hdr *ident = pjsip_msg_find_hdr_by_name(rdata->msg_info.msg,
          header_name, NULL);
    int parsed_len;
    if (!ident) {
       return NULL;
    }
    ast_log(LOG_WARNING, "Doing checks now\n");
    if (!(rdata)) {
       ast_log(LOG_WARNING, "NULL 1\n");
    }
    if (!ident) {
       ast_log(LOG_WARNING, "NULL 3\n");
    }
    if (!rdata->tp_info.pool) {
       ast_log(LOG_WARNING, "NULL 11\n");
    }
    if (!&ident->hvalue) {
       ast_log(LOG_WARNING, "NULL 13\n");
    }
    ast_log(LOG_WARNING, "strlens %lu %lu\n", pj_strlen(&header_content), pj_strlen(&ident->hvalue));
    pj_strdup_with_null(rdata->tp_info.pool, &header_content, &ident->hvalue);
    parsed_hdr = pjsip_parse_hdr(rdata->tp_info.pool, &from, header_content.ptr,
          pj_strlen(&header_content), &parsed_len);
    if (!parsed_hdr) {
       return NULL;
    }
    return parsed_hdr;
 }
load_module()
static int load_module (void) static
Definition at line 842 of file res_pjsip_caller_id.c.
References AST_MODULE_LOAD_SUCCESS, ast_module_shutdown_ref, and ast_sip_session_register_supplement.
Referenced by unload_module().
 {
    ast_module_shutdown_ref(AST_MODULE_SELF);
    ast_sip_session_register_supplement(&caller_id_supplement);
    return AST_MODULE_LOAD_SUCCESS;
 }
queue_connected_line_update()
static void queue_connected_line_update (struct ast_sip_session * session, const struct ast_party_id * id) static
Definition at line 362 of file res_pjsip_caller_id.c.
References ast_party_caller::ani, ast_party_caller::ani2, ast_channel_caller(), ast_channel_queue_connected_line_update(), ast_channel_set_caller_event(), AST_CONNECTED_LINE_UPDATE_SOURCE_ANSWER, ast_party_caller_init(), ast_party_connected_line_init(), ast_party_id_copy(), ast_sip_session::channel, ast_sip_session::endpoint, ast_sip_session::id, ast_party_caller::id, ast_party_connected_line::id, ast_sip_endpoint::id, id, NULL, ast_sip_endpoint_id_configuration::self, ast_party_connected_line::source, and ast_party_id::tag.
Referenced by update_incoming_connected_line().
 {
    struct ast_party_connected_line connected;
    struct ast_party_caller caller;
    /* Fill connected line information */
    ast_party_connected_line_init(&connected);
    connected.id = *id;
    connected.id.tag = session->endpoint->id.self.tag;
    connected.source = AST_CONNECTED_LINE_UPDATE_SOURCE_ANSWER;
    /* Save to channel driver copy */
    ast_party_id_copy(&session->id, &connected.id);
    /* Update our channel CALLERID() */
    ast_party_caller_init(&caller);
    caller.id = connected.id;
    caller.ani = connected.id;
    caller.ani2 = ast_channel_caller(session->channel)->ani2;
    ast_channel_set_caller_event(session->channel, &caller, NULL);
    /* Tell peer about the new connected line information. */
    ast_channel_queue_connected_line_update(session->channel, &connected, NULL);
 }
set_id_from_from()
static int set_id_from_from (struct pjsip_rx_data * rdata, struct ast_party_id * id) static
Definition at line 284 of file res_pjsip_caller_id.c.
References ast_party_id::number, set_id_from_hdr(), and ast_party_number::valid.
Referenced by caller_id_incoming_request().
 {
    pjsip_fromto_hdr *from = pjsip_msg_find_hdr(rdata->msg_info.msg,
          PJSIP_H_FROM, rdata->msg_info.msg->hdr.next);
    if (!from) {
       /* This had better not happen */
       return -1;
    }
    set_id_from_hdr(from, id);
    if (!id->number.valid) {
       return -1;
    }
    return 0;
 }
set_id_from_hdr()
static void set_id_from_hdr (pjsip_fromto_hdr * hdr, struct ast_party_id * id) static
Definition at line 44 of file res_pjsip_caller_id.c.
References AST_CHANNEL_NAME, ast_copy_pj_str(), ast_free, ast_strdup, ast_strlen_zero, cid_name, cid_num, ast_party_id::name, ast_party_id::number, ast_party_name::str, and ast_party_number::str.
Referenced by set_id_from_from(), set_id_from_pai(), and set_id_from_rpid().
 {
    char cid_name[AST_CHANNEL_NAME];
    char cid_num[AST_CHANNEL_NAME];
    pjsip_sip_uri *uri;
    pjsip_name_addr *id_name_addr = (pjsip_name_addr *) hdr->uri;
    char *semi;
    uri = pjsip_uri_get_uri(id_name_addr);
    ast_copy_pj_str(cid_name, &id_name_addr->display, sizeof(cid_name));
    ast_copy_pj_str(cid_num, &uri->user, sizeof(cid_num));
    /* Always truncate caller-id number at a semicolon. */
    semi = strchr(cid_num, ';');
    if (semi) {
       /*
        * We need to be able to handle URI's looking like
        * "sip:1235557890;phone-context=national@x.x.x.x;user=phone"
        *
        * Where the uri->user field will result in:
        * "1235557890;phone-context=national"
        *
        * People don't care about anything after the semicolon
        * showing up on their displays even though the RFC
        * allows the semicolon.
        */
       *semi = '\0';
    }
    ast_free(id->name.str);
    id->name.str = ast_strdup(cid_name);
    if (!ast_strlen_zero(cid_name)) {
       id->name.valid = 1;
    }
    ast_free(id->number.str);
    id->number.str = ast_strdup(cid_num);
    if (!ast_strlen_zero(cid_num)) {
       id->number.valid = 1;
    }
 }
set_id_from_oli()
static int set_id_from_oli (pjsip_rx_data * rdata, int * ani2) static
Definition at line 153 of file res_pjsip_caller_id.c.
References ast_copy_pj_str(), ast_str_to_int(), get_id_header(), and MAX_OLI_DIGITS.
Referenced by caller_id_incoming_request().
 {
    #define MAX_OLI_DIGITS 2
    char oli[MAX_OLI_DIGITS + 1];
    static const pj_str_t from = { "From", 4 };
    static const pj_str_t oli_str1 = { "oli", 3 };
    static const pj_str_t oli_str2 = { "isup-oli", 8 };
    static const pj_str_t oli_str3 = { "ss7-oli", 7 };
    const pjsip_param *oli1, *oli2, *oli3;
    pjsip_fromto_hdr *from_hdr = get_id_header(rdata, &from);
    if (!from_hdr) {
       return 0;
    }
    if ((oli1 = pjsip_param_find(&from_hdr->other_param, &oli_str1))) {
       ast_copy_pj_str(oli, &oli1->value, MAX_OLI_DIGITS);
       return ast_str_to_int(oli, ani2);
    } else if ((oli2 = pjsip_param_find(&from_hdr->other_param, &oli_str2))) {
       ast_copy_pj_str(oli, &oli2->value, MAX_OLI_DIGITS);
       return ast_str_to_int(oli, ani2);
    } else if ((oli3 = pjsip_param_find(&from_hdr->other_param, &oli_str3))) {
       ast_copy_pj_str(oli, &oli3->value, MAX_OLI_DIGITS);
       return ast_str_to_int(oli, ani2);
    }
    return 0;
 }
set_id_from_pai()
static int set_id_from_pai (pjsip_rx_data * rdata, struct ast_party_id * id) static
Definition at line 191 of file res_pjsip_caller_id.c.
References AST_PRES_ALLOWED_USER_NUMBER_NOT_SCREENED, AST_PRES_PROHIB_USER_NUMBER_NOT_SCREENED, get_id_header(), NULL, ast_party_id::number, set_id_from_hdr(), and ast_party_number::valid.
Referenced by caller_id_incoming_request(), and update_incoming_connected_line().
 {
    static const pj_str_t pai_str = { "P-Asserted-Identity", 19 };
    static const pj_str_t privacy_str = { "Privacy", 7 };
    pjsip_fromto_hdr *pai_hdr = get_id_header(rdata, &pai_str);
    pjsip_generic_string_hdr *privacy;
    if (!pai_hdr) {
       return -1;
    }
    set_id_from_hdr(pai_hdr, id);
    if (!id->number.valid) {
       return -1;
    }
    privacy = pjsip_msg_find_hdr_by_name(rdata->msg_info.msg, &privacy_str, NULL);
    if (!privacy || !pj_stricmp2(&privacy->hvalue, "none")) {
       id->number.presentation = AST_PRES_ALLOWED_USER_NUMBER_NOT_SCREENED;
       id->name.presentation = AST_PRES_ALLOWED_USER_NUMBER_NOT_SCREENED;
    } else {
       id->number.presentation = AST_PRES_PROHIB_USER_NUMBER_NOT_SCREENED;
       id->name.presentation = AST_PRES_PROHIB_USER_NUMBER_NOT_SCREENED;
    }
    return 0;
 }
set_id_from_rpid()
static int set_id_from_rpid (pjsip_rx_data * rdata, struct ast_party_id * id) static
Definition at line 232 of file res_pjsip_caller_id.c.
References AST_PRES_ALLOWED, AST_PRES_RESTRICTED, AST_PRES_USER_NUMBER_PASSED_SCREEN, AST_PRES_USER_NUMBER_UNSCREENED, get_id_header(), ast_party_id::number, set_id_from_hdr(), and ast_party_number::valid.
Referenced by caller_id_incoming_request(), and update_incoming_connected_line().
 {
    static const pj_str_t rpid_str = { "Remote-Party-ID", 15 };
    static const pj_str_t privacy_str = { "privacy", 7 };
    static const pj_str_t screen_str = { "screen", 6 };
    pjsip_fromto_hdr *rpid_hdr = get_id_header(rdata, &rpid_str);
    pjsip_param *screen;
    pjsip_param *privacy;
    if (!rpid_hdr) {
       return -1;
    }
    set_id_from_hdr(rpid_hdr, id);
    if (!id->number.valid) {
       return -1;
    }
    privacy = pjsip_param_find(&rpid_hdr->other_param, &privacy_str);
    screen = pjsip_param_find(&rpid_hdr->other_param, &screen_str);
    if (privacy && !pj_stricmp2(&privacy->value, "full")) {
       id->number.presentation = AST_PRES_RESTRICTED;
       id->name.presentation = AST_PRES_RESTRICTED;
    } else {
       id->number.presentation = AST_PRES_ALLOWED;
       id->name.presentation = AST_PRES_ALLOWED;
    }
    if (screen && !pj_stricmp2(&screen->value, "yes")) {
       id->number.presentation |= AST_PRES_USER_NUMBER_PASSED_SCREEN;
       id->name.presentation |= AST_PRES_USER_NUMBER_PASSED_SCREEN;
    } else {
       id->number.presentation |= AST_PRES_USER_NUMBER_UNSCREENED;
       id->name.presentation |= AST_PRES_USER_NUMBER_UNSCREENED;
    }
    return 0;
 }
should_queue_connected_line_update()
static int should_queue_connected_line_update (const struct ast_sip_session * session, const struct ast_party_id * id) static
Definition at line 316 of file res_pjsip_caller_id.c.
References ast_strlen_zero, ast_sip_session::id, ast_party_id::name, ast_party_id::number, ast_party_name::str, ast_party_number::str, ast_party_name::valid, and ast_party_number::valid.
Referenced by update_incoming_connected_line().
 {
    /* Invalid number means no update */
    if (!id->number.valid) {
       return 0;
    }
    /* If the session has never communicated an update or if the
     * new ID has a different number than the session, then we
     * should queue an update
     */
    if (ast_strlen_zero(session->id.number.str) ||
          strcmp(session->id.number.str, id->number.str)) {
       return 1;
    }
    /* By making it to this point, it means the number is not enough
     * to determine if an update should be sent. Now we look at
     * the name
     */
    /* If the number couldn't warrant an update and the name is
     * invalid, then no update
     */
    if (!id->name.valid) {
       return 0;
    }
    /* If the name has changed or we don't have a name set for the
     * session, then we should send an update
     */
    if (ast_strlen_zero(session->id.name.str) ||
          strcmp(session->id.name.str, id->name.str)) {
       return 1;
    }
    /* Neither the name nor the number have changed. No update */
    return 0;
 }
unload_module()
static int unload_module (void) static
Definition at line 849 of file res_pjsip_caller_id.c.
References AST_MODFLAG_LOAD_ORDER, AST_MODPRI_APP_DEPEND, AST_MODULE_INFO(), AST_MODULE_SUPPORT_CORE, ast_sip_session_unregister_supplement(), ASTERISK_GPL_KEY, and load_module().
 {
    ast_sip_session_unregister_supplement(&caller_id_supplement);
    return 0;
 }
update_incoming_connected_line()
static void update_incoming_connected_line (struct ast_sip_session * session, pjsip_rx_data * rdata) static
Definition at line 398 of file res_pjsip_caller_id.c.
References ast_party_id_free(), ast_party_id_init(), ast_sip_session::endpoint, ast_sip_endpoint::id, queue_connected_line_update(), set_id_from_pai(), set_id_from_rpid(), should_queue_connected_line_update(), ast_sip_endpoint_id_configuration::trust_connected_line, and ast_sip_endpoint_id_configuration::trust_inbound.
Referenced by caller_id_incoming_request(), and caller_id_incoming_response().
 {
    struct ast_party_id id;
    if (!session->endpoint->id.trust_connected_line
       || !session->endpoint->id.trust_inbound) {
       return;
    }
    ast_party_id_init(&id);
    if (!set_id_from_pai(rdata, &id) || !set_id_from_rpid(rdata, &id)) {
       if (should_queue_connected_line_update(session, &id)) {
          queue_connected_line_update(session, &id);
       }
    }
    ast_party_id_free(&id);
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "PJSIP Caller ID Support" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_APP_DEPEND, .requires = "res_pjsip,res_pjsip_session", } static
Definition at line 861 of file res_pjsip_caller_id.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 861 of file res_pjsip_caller_id.c.
caller_id_supplement
struct ast_sip_session_supplement caller_id_supplement static
Definition at line 833 of file res_pjsip_caller_id.c.