Asterisk - The Open Source Telephony Project: 20abce6d1e3c_add_pjsip_identify_by_ip Namespace Reference
20abce6d1e3c_add_pjsip_identify_by_ip Namespace Reference
Functions
def downgrade ()
def enum_update (table_name, column_name, enum_name, enum_values)
def upgrade ()
Variables
string down_revision = 'a1698e8bb9c5'
string revision = '20abce6d1e3c'
Function Documentation
downgrade()
def 20abce6d1e3c_add_pjsip_identify_by_ip.downgrade ()
Definition at line 44 of file 20abce6d1e3c_add_pjsip_identify_by_ip.py.
References enum_update().
 def downgrade():
     enum_update('ps_endpoints', 'identify_by', 'pjsip_identify_by_values',
                 ['username', 'auth_username'])
enum_update()
def 20abce6d1e3c_add_pjsip_identify_by_ip.enum_update (table_name, column_name, enum_name, enum_values)
Definition at line 17 of file 20abce6d1e3c_add_pjsip_identify_by_ip.py.
Referenced by downgrade(), and upgrade().
 def enum_update(table_name, column_name, enum_name, enum_values):
     if op.get_context().bind.dialect.name != 'postgresql':
         if op.get_context().bind.dialect.name == 'mssql':
             op.drop_constraint('ck_ps_endpoints_identify_by_pjsip_identify_by_values', 'ps_endpoints')
         op.alter_column(table_name, column_name,
                         type_=sa.Enum(*enum_values, name=enum_name))
         return
     # Postgres requires a few more steps
     tmp = enum_name + '_tmp'
     op.execute('ALTER TYPE ' + enum_name + ' RENAME TO ' + tmp)
     updated = sa.Enum(*enum_values, name=enum_name)
     updated.create(op.get_bind(), checkfirst=False)
     op.execute('ALTER TABLE ' + table_name + ' ALTER COLUMN ' + column_name +
                ' TYPE ' + enum_name + ' USING identify_by::text::' + enum_name)
     op.execute('DROP TYPE ' + tmp)
upgrade()
def 20abce6d1e3c_add_pjsip_identify_by_ip.upgrade ()
Definition at line 39 of file 20abce6d1e3c_add_pjsip_identify_by_ip.py.
References enum_update().
 def upgrade():
     enum_update('ps_endpoints', 'identify_by', 'pjsip_identify_by_values',
                 ['username', 'auth_username', 'ip'])
Variable Documentation
down_revision
string down_revision = 'a1698e8bb9c5'
Definition at line 11 of file 20abce6d1e3c_add_pjsip_identify_by_ip.py.
revision
string revision = '20abce6d1e3c'
Definition at line 10 of file 20abce6d1e3c_add_pjsip_identify_by_ip.py.