Asterisk - The Open Source Telephony Project: test_bucket.c File Reference
test_bucket.c File Reference
Bucket Unit Tests.
#include "asterisk.h"
#include <sys/stat.h>
#include "asterisk/test.h"
#include "asterisk/module.h"
#include "asterisk/bucket.h"
#include "asterisk/logger.h"
#include "asterisk/json.h"
#include "asterisk/file.h"
Data Structures
struct bucket_test_state
Test state structure for scheme wizards.
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
AST_TEST_DEFINE (bucket_scheme_register)
AST_TEST_DEFINE (bucket_alloc)
AST_TEST_DEFINE (bucket_create)
AST_TEST_DEFINE (bucket_clone)
AST_TEST_DEFINE (bucket_delete)
AST_TEST_DEFINE (bucket_is_stale)
AST_TEST_DEFINE (bucket_json)
AST_TEST_DEFINE (bucket_retrieve)
AST_TEST_DEFINE (bucket_file_alloc)
AST_TEST_DEFINE (bucket_file_create)
AST_TEST_DEFINE (bucket_file_clone)
AST_TEST_DEFINE (bucket_file_copy)
AST_TEST_DEFINE (bucket_file_retrieve)
AST_TEST_DEFINE (bucket_file_update)
AST_TEST_DEFINE (bucket_file_delete)
AST_TEST_DEFINE (bucket_file_is_stale)
AST_TEST_DEFINE (bucket_file_metadata_set)
AST_TEST_DEFINE (bucket_file_metadata_unset)
AST_TEST_DEFINE (bucket_file_metadata_get)
AST_TEST_DEFINE (bucket_file_json)
static void bucket_test_wizard_clear (void)
static int bucket_test_wizard_create (const struct ast_sorcery *sorcery, void *data, void *object)
static int bucket_test_wizard_delete (const struct ast_sorcery *sorcery, void *data, void *object)
static int bucket_test_wizard_is_stale (const struct ast_sorcery *sorcery, void *data, void *object)
static void * bucket_test_wizard_retrieve_id (const struct ast_sorcery *sorcery, void *data, const char *type, const char *id)
static int bucket_test_wizard_update (const struct ast_sorcery *sorcery, void *data, void *object)
static int load_module (void)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Bucket test module" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, }
static const struct ast_module_info * ast_module_info = &__mod_info
static struct ast_sorcery_wizard bucket_file_test_wizard
static struct ast_sorcery_wizard bucket_test_wizard
static struct bucket_test_state bucket_test_wizard_state
Global scope structure for testing bucket wizards.
Detailed Description
Bucket Unit Tests.
Author
Joshua Colp jcolp.nosp@m.@dig.nosp@m.ium.c.nosp@m.om
Definition in file test_bucket.c.
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 1041 of file test_bucket.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 1041 of file test_bucket.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 1041 of file test_bucket.c.
AST_TEST_DEFINE() [1/20]
AST_TEST_DEFINE (bucket_scheme_register)
Definition at line 133 of file test_bucket.c.
References ast_bucket_scheme_register, AST_TEST_FAIL, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_test_status_update, sip_to_pjsip::info(), NULL, TEST_EXECUTE, and TEST_INIT.
 {
    switch (cmd) {
    case TEST_INIT:
       info->name = "bucket_scheme_register_unregister";
       info->category = "/main/bucket/";
       info->summary = "bucket scheme registration/unregistration unit test";
       info->description =
          "Test registration and unregistration of bucket scheme";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    if (!ast_bucket_scheme_register("", NULL, NULL, NULL, NULL)) {
       ast_test_status_update(test, "Successfully registered a Bucket scheme without name or wizards\n");
       return AST_TEST_FAIL;
    }
    if (!ast_bucket_scheme_register("test", &bucket_test_wizard, &bucket_file_test_wizard, NULL, NULL)) {
       ast_test_status_update(test, "Successfully registered a Bucket scheme twice\n");
       return AST_TEST_FAIL;
    }
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [2/20]
AST_TEST_DEFINE (bucket_alloc)
Definition at line 160 of file test_bucket.c.
References ao2_cleanup, ast_bucket_alloc(), ast_sorcery_object_get_id(), AST_TEST_FAIL, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_test_status_update, sip_to_pjsip::info(), NULL, RAII_VAR, TEST_EXECUTE, and TEST_INIT.
 {
    RAII_VAR(struct ast_bucket *, bucket, NULL, ao2_cleanup);
    switch (cmd) {
    case TEST_INIT:
       info->name = "bucket_alloc";
       info->category = "/main/bucket/";
       info->summary = "bucket allocation unit test";
       info->description =
          "Test allocation of buckets";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    if ((bucket = ast_bucket_alloc(""))) {
       ast_test_status_update(test, "Allocated a bucket with no URI provided\n");
       return AST_TEST_FAIL;
    }
    if (!(bucket = ast_bucket_alloc("test:///tmp/bob"))) {
       ast_test_status_update(test, "Failed to allocate bucket\n");
       return AST_TEST_FAIL;
    }
    if (strcmp(ast_sorcery_object_get_id(bucket), "test:///tmp/bob")) {
       ast_test_status_update(test, "URI within allocated bucket is '%s' and should be test:///tmp/bob\n",
          ast_sorcery_object_get_id(bucket));
       return AST_TEST_FAIL;
    }
    if (strcmp(bucket->scheme, "test")) {
       ast_test_status_update(test, "Scheme within allocated bucket is '%s' and should be test\n",
          bucket->scheme);
       return AST_TEST_FAIL;
    }
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [3/20]
AST_TEST_DEFINE (bucket_create)
Definition at line 201 of file test_bucket.c.
References ao2_cleanup, ast_bucket_alloc(), ast_bucket_create(), ast_sorcery_object_get_id(), AST_TEST_FAIL, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_test_status_update, bucket_test_wizard_clear(), bucket_test_wizard_state, bucket_test_state::created, sip_to_pjsip::info(), NULL, RAII_VAR, TEST_EXECUTE, and TEST_INIT.
 {
    RAII_VAR(struct ast_bucket *, bucket, NULL, ao2_cleanup);
    switch (cmd) {
    case TEST_INIT:
       info->name = "bucket_create";
       info->category = "/main/bucket/";
       info->summary = "bucket creation unit test";
       info->description =
          "Test creation of buckets";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    if (!(bucket = ast_bucket_alloc("test:///tmp/bob"))) {
       ast_test_status_update(test, "Failed to allocate bucket\n");
       return AST_TEST_FAIL;
    }
    bucket_test_wizard_clear();
    if (ast_bucket_create(bucket)) {
       ast_test_status_update(test, "Failed to create bucket with URI '%s'\n",
          ast_sorcery_object_get_id(bucket));
       return AST_TEST_FAIL;
    }
    if (!bucket_test_wizard_state.created) {
       ast_test_status_update(test, "Bucket creation returned success but scheme implementation never actually created it\n");
       return AST_TEST_FAIL;
    }
    if (!ast_bucket_create(bucket)) {
       ast_test_status_update(test, "Successfully created bucket with URI '%s' twice\n",
          ast_sorcery_object_get_id(bucket));
       return AST_TEST_FAIL;
    }
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [4/20]
AST_TEST_DEFINE (bucket_clone)
Definition at line 244 of file test_bucket.c.
References ao2_cleanup, ast_bucket_alloc(), ast_bucket_clone(), ast_bucket_create(), ast_sorcery_object_get_id(), AST_TEST_FAIL, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_test_status_update, bucket_test_wizard_clear(), sip_to_pjsip::info(), NULL, RAII_VAR, TEST_EXECUTE, and TEST_INIT.
 {
    RAII_VAR(struct ast_bucket *, bucket, NULL, ao2_cleanup);
    RAII_VAR(struct ast_bucket *, clone, NULL, ao2_cleanup);
    switch (cmd) {
    case TEST_INIT:
       info->name = "bucket_clone";
       info->category = "/main/bucket/";
       info->summary = "bucket clone unit test";
       info->description =
          "Test cloning a bucket";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    if (!(bucket = ast_bucket_alloc("test:///tmp/bob"))) {
       ast_test_status_update(test, "Failed to allocate bucket\n");
       return AST_TEST_FAIL;
    }
    bucket_test_wizard_clear();
    if (ast_bucket_create(bucket)) {
       ast_test_status_update(test, "Failed to create bucket with URI '%s'\n",
          ast_sorcery_object_get_id(bucket));
       return AST_TEST_FAIL;
    }
    clone = ast_bucket_clone(bucket);
    if (!clone) {
       ast_test_status_update(test, "Failed to clone bucket with URI '%s'\n",
          ast_sorcery_object_get_id(bucket));
       return AST_TEST_FAIL;
    }
    ast_test_validate(test, strcmp(ast_sorcery_object_get_id(bucket), ast_sorcery_object_get_id(clone)) == 0);
    ast_test_validate(test, bucket->scheme_impl == clone->scheme_impl);
    ast_test_validate(test, strcmp(bucket->scheme, clone->scheme) == 0);
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [5/20]
AST_TEST_DEFINE (bucket_delete)
Definition at line 288 of file test_bucket.c.
References ao2_cleanup, ast_bucket_alloc(), ast_bucket_delete(), ast_sorcery_object_get_id(), AST_TEST_FAIL, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_test_status_update, bucket_test_wizard_clear(), bucket_test_wizard_state, bucket_test_state::deleted, sip_to_pjsip::info(), NULL, RAII_VAR, TEST_EXECUTE, and TEST_INIT.
 {
    RAII_VAR(struct ast_bucket *, bucket, NULL, ao2_cleanup);
    switch (cmd) {
    case TEST_INIT:
       info->name = "bucket_delete";
       info->category = "/main/bucket/";
       info->summary = "bucket deletion unit test";
       info->description =
          "Test deletion of buckets";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    if (!(bucket = ast_bucket_alloc("test:///tmp/bob"))) {
       ast_test_status_update(test, "Failed to allocate bucket\n");
       return AST_TEST_FAIL;
    }
    bucket_test_wizard_clear();
    if (ast_bucket_delete(bucket)) {
       ast_test_status_update(test, "Failed to delete bucket with URI '%s'\n",
          ast_sorcery_object_get_id(bucket));
       return AST_TEST_FAIL;
    }
    if (!bucket_test_wizard_state.deleted) {
       ast_test_status_update(test, "Bucket deletion returned success but scheme implementation never actually deleted it\n");
       return AST_TEST_FAIL;
    }
    if (!ast_bucket_delete(bucket)) {
       ast_test_status_update(test, "Successfully deleted bucket with URI '%s' twice\n",
          ast_sorcery_object_get_id(bucket));
       return AST_TEST_FAIL;
    }
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [6/20]
AST_TEST_DEFINE (bucket_is_stale)
Definition at line 331 of file test_bucket.c.
References ao2_cleanup, ast_bucket_alloc(), ast_bucket_is_stale(), AST_TEST_FAIL, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_test_status_update, bucket_test_wizard_clear(), bucket_test_wizard_state, sip_to_pjsip::info(), bucket_test_state::is_stale, NULL, RAII_VAR, TEST_EXECUTE, and TEST_INIT.
 {
    RAII_VAR(struct ast_bucket *, bucket, NULL, ao2_cleanup);
    switch (cmd) {
    case TEST_INIT:
       info->name = "bucket_is_stale";
       info->category = "/main/bucket/";
       info->summary = "bucket staleness unit test";
       info->description =
          "Test if staleness of a bucket is reported correctly";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    if (!(bucket = ast_bucket_alloc("test:///tmp/bob"))) {
       ast_test_status_update(test, "Failed to allocate bucket\n");
       return AST_TEST_FAIL;
    }
    bucket_test_wizard_clear();
    ast_test_validate(test, ast_bucket_is_stale(bucket) == 0);
    bucket_test_wizard_state.is_stale = 1;
    ast_test_validate(test, ast_bucket_is_stale(bucket) == 1);
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [7/20]
AST_TEST_DEFINE (bucket_json)
Definition at line 363 of file test_bucket.c.
References ao2_cleanup, ast_bucket_alloc(), ast_bucket_json(), ast_json_equal(), ast_json_pack(), ast_json_unref(), ast_str_container_add(), AST_TEST_FAIL, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_test_status_update, sip_to_pjsip::info(), NULL, RAII_VAR, TEST_EXECUTE, and TEST_INIT.
 {
    RAII_VAR(struct ast_bucket *, bucket, NULL, ao2_cleanup);
    RAII_VAR(struct ast_json *, expected, NULL, ast_json_unref);
    RAII_VAR(struct ast_json *, json, NULL, ast_json_unref);
    switch (cmd) {
    case TEST_INIT:
       info->name = "bucket_json";
       info->category = "/main/bucket/";
       info->summary = "bucket json unit test";
       info->description =
          "Test creation of JSON for a bucket";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    if (!(bucket = ast_bucket_alloc("test:///tmp/bob"))) {
       ast_test_status_update(test, "Failed to allocate bucket\n");
       return AST_TEST_FAIL;
    }
    ast_str_container_add(bucket->buckets, "test:///tmp/bob/joe");
    ast_str_container_add(bucket->files, "test:///tmp/bob/recording.wav");
    expected = ast_json_pack("{s: s, s: s, s: [s], s: s, s: [s], s: s}",
       "modified", "0.000000", "created", "0.000000",
       "buckets", "test:///tmp/bob/joe",
       "scheme", "test",
       "files", "test:///tmp/bob/recording.wav",
       "id", "test:///tmp/bob");
    if (!expected) {
       ast_test_status_update(test, "Could not produce JSON for expected bucket value\n");
       return AST_TEST_FAIL;
    }
    json = ast_bucket_json(bucket);
    if (!json) {
       ast_test_status_update(test, "Could not produce JSON for a valid bucket\n");
       return AST_TEST_FAIL;
    }
    if (!ast_json_equal(json, expected)) {
       ast_test_status_update(test, "Bucket JSON does not match expected output\n");
       return AST_TEST_FAIL;
    }
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [8/20]
AST_TEST_DEFINE (bucket_retrieve)
Definition at line 414 of file test_bucket.c.
References ao2_cleanup, ast_bucket_retrieve(), AST_TEST_FAIL, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_test_status_update, sip_to_pjsip::info(), NULL, RAII_VAR, TEST_EXECUTE, and TEST_INIT.
 {
    RAII_VAR(struct ast_bucket *, bucket, NULL, ao2_cleanup);
    switch (cmd) {
    case TEST_INIT:
       info->name = "bucket_retrieve";
       info->category = "/main/bucket/";
       info->summary = "bucket retrieval unit test";
       info->description =
          "Test retrieval of buckets";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    if (!(bucket = ast_bucket_retrieve("test://tmp/bob"))) {
       ast_test_status_update(test, "Failed to retrieve known valid bucket\n");
       return AST_TEST_FAIL;
    }
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [9/20]
AST_TEST_DEFINE (bucket_file_alloc)
Definition at line 438 of file test_bucket.c.
References ao2_cleanup, ast_bucket_file_alloc(), ast_sorcery_object_get_id(), ast_strlen_zero, AST_TEST_FAIL, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_test_status_update, make_ari_stubs::file, sip_to_pjsip::info(), NULL, RAII_VAR, TEST_EXECUTE, and TEST_INIT.
 {
    RAII_VAR(struct ast_bucket_file *, file, NULL, ao2_cleanup);
    switch (cmd) {
    case TEST_INIT:
       info->name = "bucket_file_alloc";
       info->category = "/main/bucket/";
       info->summary = "bucket file allocation unit test";
       info->description =
          "Test allocation of bucket files";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    if ((file = ast_bucket_file_alloc(""))) {
       ast_test_status_update(test, "Allocated a file with no URI provided\n");
       return AST_TEST_FAIL;
    }
    if (!(file = ast_bucket_file_alloc("test:///tmp/bob"))) {
       ast_test_status_update(test, "Failed to allocate file\n");
       return AST_TEST_FAIL;
    }
    if (ast_strlen_zero(file->path)) {
       ast_test_status_update(test, "Expected temporary path in allocated file");
       return AST_TEST_FAIL;
    }
    if (strcmp(ast_sorcery_object_get_id(file), "test:///tmp/bob")) {
       ast_test_status_update(test, "URI within allocated file is '%s' and should be test:///tmp/bob\n",
          ast_sorcery_object_get_id(file));
       return AST_TEST_FAIL;
    }
    if (strcmp(file->scheme, "test")) {
       ast_test_status_update(test, "Scheme within allocated file is '%s' and should be test\n",
          file->scheme);
       return AST_TEST_FAIL;
    }
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [10/20]
AST_TEST_DEFINE (bucket_file_create)
Definition at line 484 of file test_bucket.c.
References ao2_cleanup, ast_bucket_file_alloc(), ast_bucket_file_create(), ast_sorcery_object_get_id(), AST_TEST_FAIL, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_test_status_update, bucket_test_wizard_clear(), bucket_test_wizard_state, bucket_test_state::created, make_ari_stubs::file, sip_to_pjsip::info(), NULL, RAII_VAR, TEST_EXECUTE, and TEST_INIT.
 {
    RAII_VAR(struct ast_bucket_file *, file, NULL, ao2_cleanup);
    switch (cmd) {
    case TEST_INIT:
       info->name = "bucket_file_create";
       info->category = "/main/bucket/";
       info->summary = "file creation unit test";
       info->description =
          "Test creation of files";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    if (!(file = ast_bucket_file_alloc("test:///tmp/bob"))) {
       ast_test_status_update(test, "Failed to allocate file\n");
       return AST_TEST_FAIL;
    }
    bucket_test_wizard_clear();
    if (ast_bucket_file_create(file)) {
       ast_test_status_update(test, "Failed to create file with URI '%s'\n",
          ast_sorcery_object_get_id(file));
       return AST_TEST_FAIL;
    }
    if (!bucket_test_wizard_state.created) {
       ast_test_status_update(test, "Bucket file creation returned success but scheme implementation never actually created it\n");
       return AST_TEST_FAIL;
    }
    if (!ast_bucket_file_create(file)) {
       ast_test_status_update(test, "Successfully created file with URI '%s' twice\n",
          ast_sorcery_object_get_id(file));
       return AST_TEST_FAIL;
    }
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [11/20]
AST_TEST_DEFINE (bucket_file_clone)
Definition at line 527 of file test_bucket.c.
References ao2_cleanup, ao2_container_count(), ast_bucket_file_alloc(), ast_bucket_file_clone(), ast_bucket_file_create(), ast_bucket_file_metadata_set(), ast_sorcery_object_get_id(), AST_TEST_FAIL, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_test_status_update, bucket_test_wizard_clear(), make_ari_stubs::file, sip_to_pjsip::info(), NULL, RAII_VAR, TEST_EXECUTE, and TEST_INIT.
 {
    RAII_VAR(struct ast_bucket_file *, file, NULL, ao2_cleanup);
    RAII_VAR(struct ast_bucket_file *, clone, NULL, ao2_cleanup);
    switch (cmd) {
    case TEST_INIT:
       info->name = "bucket_file_clone";
       info->category = "/main/bucket/";
       info->summary = "file clone unit test";
       info->description =
          "Test cloning a file";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    if (!(file = ast_bucket_file_alloc("test:///tmp/bob"))) {
       ast_test_status_update(test, "Failed to allocate file\n");
       return AST_TEST_FAIL;
    }
    bucket_test_wizard_clear();
    if (ast_bucket_file_create(file)) {
       ast_test_status_update(test, "Failed to create file with URI '%s'\n",
          ast_sorcery_object_get_id(file));
       return AST_TEST_FAIL;
    }
    ast_bucket_file_metadata_set(file, "bob", "joe");
    clone = ast_bucket_file_clone(file);
    if (!clone) {
       ast_test_status_update(test, "Failed to clone file with URI '%s'\n",
          ast_sorcery_object_get_id(file));
       return AST_TEST_FAIL;
    }
    ast_test_validate(test, strcmp(ast_sorcery_object_get_id(file), ast_sorcery_object_get_id(clone)) == 0);
    ast_test_validate(test, file->scheme_impl == clone->scheme_impl);
    ast_test_validate(test, strcmp(file->scheme, clone->scheme) == 0);
    ast_test_validate(test, ao2_container_count(file->metadata) == ao2_container_count(clone->metadata));
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [12/20]
AST_TEST_DEFINE (bucket_file_copy)
Definition at line 573 of file test_bucket.c.
References ao2_cleanup, ao2_container_count(), ast_bucket_file_alloc(), ast_bucket_file_copy(), ast_bucket_file_metadata_get(), ast_bucket_file_metadata_set(), ast_sorcery_object_get_id(), AST_TEST_FAIL, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_test_status_update, copy(), make_ari_stubs::file, sip_to_pjsip::info(), NULL, RAII_VAR, TEST_EXECUTE, and TEST_INIT.
 {
    RAII_VAR(struct ast_bucket_file *, file, NULL, ao2_cleanup);
    RAII_VAR(struct ast_bucket_file *, copy, NULL, ao2_cleanup);
    FILE *temporary;
    struct stat old, new;
    RAII_VAR(struct ast_bucket_metadata *, metadata, NULL, ao2_cleanup);
    switch (cmd) {
    case TEST_INIT:
       info->name = "bucket_file_copy";
       info->category = "/main/bucket/";
       info->summary = "bucket file copying unit test";
       info->description =
          "Test copying of bucket files";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    if (!(file = ast_bucket_file_alloc("test:///tmp/bob"))) {
       ast_test_status_update(test, "Failed to allocate file\n");
       return AST_TEST_FAIL;
    }
    ast_bucket_file_metadata_set(file, "bob", "joe");
    if (!(temporary = fopen(file->path, "w"))) {
       ast_test_status_update(test, "Failed to open temporary file '%s'\n", file->path);
       return AST_TEST_FAIL;
    }
    fprintf(temporary, "bob");
    fclose(temporary);
    if (!(copy = ast_bucket_file_copy(file, "test:///tmp/bob2"))) {
       ast_test_status_update(test, "Failed to copy file '%s' to test:///tmp/bob2\n",
          ast_sorcery_object_get_id(file));
       return AST_TEST_FAIL;
    }
    if (stat(file->path, &old)) {
       ast_test_status_update(test, "Failed to retrieve information on old file '%s'\n", file->path);
       return AST_TEST_FAIL;
    }
    if (stat(copy->path, &new)) {
       ast_test_status_update(test, "Failed to retrieve information on copy file '%s'\n", copy->path);
       return AST_TEST_FAIL;
    }
    if (old.st_size != new.st_size) {
       ast_test_status_update(test, "Copying of underlying temporary file failed\n");
       return AST_TEST_FAIL;
    }
    if (ao2_container_count(file->metadata) != ao2_container_count(copy->metadata)) {
       ast_test_status_update(test, "Number of metadata entries does not match original\n");
       return AST_TEST_FAIL;
    }
    metadata = ast_bucket_file_metadata_get(copy, "bob");
    if (!metadata) {
       ast_test_status_update(test, "Copy of file does not have expected metadata\n");
       return AST_TEST_FAIL;
    }
    if (strcmp(metadata->value, "joe")) {
       ast_test_status_update(test, "Copy of file contains metadata for 'bob' but value is not what it should be\n");
       return AST_TEST_FAIL;
    }
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [13/20]
AST_TEST_DEFINE (bucket_file_retrieve)
Definition at line 648 of file test_bucket.c.
References ao2_cleanup, ast_bucket_file_retrieve(), AST_TEST_FAIL, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_test_status_update, make_ari_stubs::file, sip_to_pjsip::info(), NULL, RAII_VAR, TEST_EXECUTE, and TEST_INIT.
 {
    RAII_VAR(struct ast_bucket_file *, file, NULL, ao2_cleanup);
    switch (cmd) {
    case TEST_INIT:
       info->name = "bucket_file_retrieve";
       info->category = "/main/bucket/";
       info->summary = "file retrieval unit test";
       info->description =
          "Test retrieval of files";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    if (!(file = ast_bucket_file_retrieve("test://tmp/bob"))) {
       ast_test_status_update(test, "Failed to retrieve known valid file\n");
       return AST_TEST_FAIL;
    }
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [14/20]
AST_TEST_DEFINE (bucket_file_update)
Definition at line 672 of file test_bucket.c.
References ao2_cleanup, ast_bucket_file_alloc(), ast_bucket_file_update(), ast_sorcery_object_get_id(), AST_TEST_FAIL, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_test_status_update, bucket_test_wizard_clear(), bucket_test_wizard_state, make_ari_stubs::file, sip_to_pjsip::info(), NULL, RAII_VAR, TEST_EXECUTE, TEST_INIT, and bucket_test_state::updated.
 {
    RAII_VAR(struct ast_bucket_file *, file, NULL, ao2_cleanup);
    switch (cmd) {
    case TEST_INIT:
       info->name = "bucket_file_update";
       info->category = "/main/bucket/";
       info->summary = "file updating unit test";
       info->description =
          "Test updating of files";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    if (!(file = ast_bucket_file_alloc("test:///tmp/bob"))) {
       ast_test_status_update(test, "Failed to allocate file\n");
       return AST_TEST_FAIL;
    }
    bucket_test_wizard_clear();
    if (ast_bucket_file_update(file)) {
       ast_test_status_update(test, "Failed to update file with URI '%s'\n",
          ast_sorcery_object_get_id(file));
       return AST_TEST_FAIL;
    }
    if (!bucket_test_wizard_state.updated) {
       ast_test_status_update(test, "Successfully returned file was updated, but it was not\n");
       return AST_TEST_FAIL;
    }
    if (!ast_bucket_file_update(file)) {
       ast_test_status_update(test, "Successfully updated file with URI '%s' twice\n",
          ast_sorcery_object_get_id(file));
       return AST_TEST_FAIL;
    }
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [15/20]
AST_TEST_DEFINE (bucket_file_delete)
Definition at line 715 of file test_bucket.c.
References ao2_cleanup, ast_bucket_file_alloc(), ast_bucket_file_delete(), ast_sorcery_object_get_id(), AST_TEST_FAIL, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_test_status_update, bucket_test_wizard_clear(), bucket_test_wizard_state, bucket_test_state::deleted, make_ari_stubs::file, sip_to_pjsip::info(), NULL, RAII_VAR, TEST_EXECUTE, and TEST_INIT.
 {
    RAII_VAR(struct ast_bucket_file *, file, NULL, ao2_cleanup);
    switch (cmd) {
    case TEST_INIT:
       info->name = "bucket_file_delete";
       info->category = "/main/bucket/";
       info->summary = "file deletion unit test";
       info->description =
          "Test deletion of files";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    if (!(file = ast_bucket_file_alloc("test:///tmp/bob"))) {
       ast_test_status_update(test, "Failed to allocate file\n");
       return AST_TEST_FAIL;
    }
    bucket_test_wizard_clear();
    if (ast_bucket_file_delete(file)) {
       ast_test_status_update(test, "Failed to delete file with URI '%s'\n",
          ast_sorcery_object_get_id(file));
       return AST_TEST_FAIL;
    }
    if (!bucket_test_wizard_state.deleted) {
       ast_test_status_update(test, "Bucket file deletion returned success but scheme implementation never actually deleted it\n");
       return AST_TEST_FAIL;
    }
    if (!ast_bucket_file_delete(file)) {
       ast_test_status_update(test, "Successfully deleted file with URI '%s' twice\n",
          ast_sorcery_object_get_id(file));
       return AST_TEST_FAIL;
    }
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [16/20]
AST_TEST_DEFINE (bucket_file_is_stale)
Definition at line 758 of file test_bucket.c.
References ao2_cleanup, ast_bucket_file_alloc(), ast_bucket_file_is_stale(), AST_TEST_FAIL, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_test_status_update, bucket_test_wizard_clear(), bucket_test_wizard_state, make_ari_stubs::file, sip_to_pjsip::info(), bucket_test_state::is_stale, NULL, RAII_VAR, TEST_EXECUTE, and TEST_INIT.
 {
    RAII_VAR(struct ast_bucket_file *, file, NULL, ao2_cleanup);
    switch (cmd) {
    case TEST_INIT:
       info->name = "bucket_file_is_stale";
       info->category = "/main/bucket/";
       info->summary = "file staleness unit test";
       info->description =
          "Test if staleness of a bucket file is reported correctly";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    if (!(file = ast_bucket_file_alloc("test:///tmp/bob"))) {
       ast_test_status_update(test, "Failed to allocate file\n");
       return AST_TEST_FAIL;
    }
    bucket_test_wizard_clear();
    ast_test_validate(test, ast_bucket_file_is_stale(file) == 0);
    bucket_test_wizard_state.is_stale = 1;
    ast_test_validate(test, ast_bucket_file_is_stale(file) == 1);
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [17/20]
AST_TEST_DEFINE (bucket_file_metadata_set)
Definition at line 790 of file test_bucket.c.
References ao2_cleanup, ao2_container_count(), ao2_find, ast_bucket_file_alloc(), ast_bucket_file_metadata_set(), AST_TEST_FAIL, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_test_status_update, make_ari_stubs::file, sip_to_pjsip::info(), NULL, OBJ_KEY, RAII_VAR, TEST_EXECUTE, and TEST_INIT.
 {
    RAII_VAR(struct ast_bucket_file *, file, NULL, ao2_cleanup);
    RAII_VAR(struct ast_bucket_metadata *, metadata, NULL, ao2_cleanup);
    switch (cmd) {
    case TEST_INIT:
       info->name = "bucket_file_metadata_set";
       info->category = "/main/bucket/";
       info->summary = "file metadata setting unit test";
       info->description =
          "Test setting of metadata on files";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    if (!(file = ast_bucket_file_alloc("test:///tmp/bob"))) {
       ast_test_status_update(test, "Failed to allocate file\n");
       return AST_TEST_FAIL;
    }
    if (ao2_container_count(file->metadata) != 0) {
       ast_test_status_update(test, "Newly allocated file has metadata count of '%d' when should be 0\n",
          ao2_container_count(file->metadata));
       return AST_TEST_FAIL;
    }
    if (ast_bucket_file_metadata_set(file, "bob", "joe")) {
       ast_test_status_update(test, "Failed to set metadata 'bob' to 'joe' on newly allocated file\n");
       return AST_TEST_FAIL;
    }
    if (!(metadata = ao2_find(file->metadata, "bob", OBJ_KEY))) {
       ast_test_status_update(test, "Failed to find set metadata 'bob' on newly allocated file\n");
       return AST_TEST_FAIL;
    }
    if (strcmp(metadata->value, "joe")) {
       ast_test_status_update(test, "Metadata has value '%s' when should be 'joe'\n",
          metadata->value);
       return AST_TEST_FAIL;
    }
    ao2_cleanup(metadata);
    metadata = NULL;
    if (ast_bucket_file_metadata_set(file, "bob", "fred")) {
       ast_test_status_update(test, "Failed to overwrite metadata 'bob' with new value 'fred'\n");
       return AST_TEST_FAIL;
    }
    if (!(metadata = ao2_find(file->metadata, "bob", OBJ_KEY))) {
       ast_test_status_update(test, "Failed to find overwritten metadata 'bob' on newly allocated file\n");
       return AST_TEST_FAIL;
    }
    if (strcmp(metadata->value, "fred")) {
       ast_test_status_update(test, "Metadata has value '%s' when should be 'fred'\n",
          metadata->value);
       return AST_TEST_FAIL;
    }
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [18/20]
AST_TEST_DEFINE (bucket_file_metadata_unset)
Definition at line 856 of file test_bucket.c.
References ao2_cleanup, ao2_find, ast_bucket_file_alloc(), ast_bucket_file_metadata_set(), ast_bucket_file_metadata_unset(), AST_TEST_FAIL, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_test_status_update, make_ari_stubs::file, sip_to_pjsip::info(), NULL, OBJ_KEY, RAII_VAR, TEST_EXECUTE, and TEST_INIT.
 {
    RAII_VAR(struct ast_bucket_file *, file, NULL, ao2_cleanup);
    RAII_VAR(struct ast_bucket_metadata *, metadata, NULL, ao2_cleanup);
    switch (cmd) {
    case TEST_INIT:
       info->name = "bucket_file_metadata_unset";
       info->category = "/main/bucket/";
       info->summary = "file metadata unsetting unit test";
       info->description =
          "Test unsetting of metadata on files";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    if (!(file = ast_bucket_file_alloc("test:///tmp/bob"))) {
       ast_test_status_update(test, "Failed to allocate file\n");
       return AST_TEST_FAIL;
    }
    if (ast_bucket_file_metadata_set(file, "bob", "joe")) {
       ast_test_status_update(test, "Failed to set metadata 'bob' to 'joe' on newly allocated file\n");
       return AST_TEST_FAIL;
    }
    if (ast_bucket_file_metadata_unset(file, "bob")) {
       ast_test_status_update(test, "Failed to unset metadata 'bob' on newly allocated file\n");
       return AST_TEST_FAIL;
    }
    if ((metadata = ao2_find(file->metadata, "bob", OBJ_KEY))) {
       ast_test_status_update(test, "Metadata 'bob' was unset, but can still be found\n");
       return AST_TEST_FAIL;
    }
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [19/20]
AST_TEST_DEFINE (bucket_file_metadata_get)
Definition at line 896 of file test_bucket.c.
References ao2_cleanup, ast_bucket_file_alloc(), ast_bucket_file_metadata_get(), ast_bucket_file_metadata_set(), AST_TEST_FAIL, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_test_status_update, make_ari_stubs::file, sip_to_pjsip::info(), NULL, RAII_VAR, TEST_EXECUTE, and TEST_INIT.
 {
    RAII_VAR(struct ast_bucket_file *, file, NULL, ao2_cleanup);
    RAII_VAR(struct ast_bucket_metadata *, metadata, NULL, ao2_cleanup);
    switch (cmd) {
    case TEST_INIT:
       info->name = "bucket_file_metadata_get";
       info->category = "/main/bucket/";
       info->summary = "file metadata getting unit test";
       info->description =
          "Test getting of metadata on files";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    if (!(file = ast_bucket_file_alloc("test:///tmp/bob"))) {
       ast_test_status_update(test, "Failed to allocate file\n");
       return AST_TEST_FAIL;
    }
    if (ast_bucket_file_metadata_set(file, "bob", "joe")) {
       ast_test_status_update(test, "Failed to set metadata 'bob' to 'joe' on newly allocated file\n");
       return AST_TEST_FAIL;
    }
    if (!(metadata = ast_bucket_file_metadata_get(file, "bob"))) {
       ast_test_status_update(test, "Failed to retrieve metadata 'bob' that was just set\n");
       return AST_TEST_FAIL;
    }
    if (strcmp(metadata->value, "joe")) {
       ast_test_status_update(test, "Retrieved metadata value is '%s' while it should be 'joe'\n",
          metadata->value);
       return AST_TEST_FAIL;
    }
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [20/20]
AST_TEST_DEFINE (bucket_file_json)
Definition at line 937 of file test_bucket.c.
References ao2_cleanup, ast_bucket_file_alloc(), ast_bucket_file_json(), ast_bucket_file_metadata_set(), ast_json_equal(), ast_json_pack(), ast_json_unref(), AST_TEST_FAIL, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_test_status_update, make_ari_stubs::file, sip_to_pjsip::info(), NULL, RAII_VAR, TEST_EXECUTE, and TEST_INIT.
 {
    RAII_VAR(struct ast_bucket_file *, file, NULL, ao2_cleanup);
    RAII_VAR(struct ast_json *, expected, NULL, ast_json_unref);
    RAII_VAR(struct ast_json *, json, NULL, ast_json_unref);
    switch (cmd) {
    case TEST_INIT:
       info->name = "bucket_file_json";
       info->category = "/main/bucket/";
       info->summary = "file json unit test";
       info->description =
          "Test creation of JSON for a file";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    if (!(file = ast_bucket_file_alloc("test:///tmp/bob"))) {
       ast_test_status_update(test, "Failed to allocate bucket\n");
       return AST_TEST_FAIL;
    }
    if (ast_bucket_file_metadata_set(file, "bob", "joe")) {
       ast_test_status_update(test, "Failed to set metadata 'bob' to 'joe' on newly allocated file\n");
       return AST_TEST_FAIL;
    }
    expected = ast_json_pack("{s: s, s: s, s: s, s: s, s: {s :s}}",
       "modified", "0.000000", "created", "0.000000", "scheme", "test",
       "id", "test:///tmp/bob", "metadata", "bob", "joe");
    if (!expected) {
       ast_test_status_update(test, "Could not produce JSON for expected bucket file value\n");
       return AST_TEST_FAIL;
    }
    json = ast_bucket_file_json(file);
    if (!json) {
       ast_test_status_update(test, "Could not produce JSON for a valid file\n");
       return AST_TEST_FAIL;
    }
    if (!ast_json_equal(json, expected)) {
       ast_test_status_update(test, "Bucket file JSON does not match expected output\n");
       return AST_TEST_FAIL;
    }
    return AST_TEST_PASS;
 }
bucket_test_wizard_clear()
static void bucket_test_wizard_clear (void) static
Definition at line 58 of file test_bucket.c.
References bucket_test_wizard_state, bucket_test_state::created, bucket_test_state::deleted, bucket_test_state::is_stale, and bucket_test_state::updated.
Referenced by AST_TEST_DEFINE().
 {
    bucket_test_wizard_state.created = 0;
    bucket_test_wizard_state.updated = 0;
    bucket_test_wizard_state.deleted = 0;
    bucket_test_wizard_state.is_stale = 0;
 }
bucket_test_wizard_create()
static int bucket_test_wizard_create (const struct ast_sorcery * sorcery, void * data, void * object) static
Definition at line 66 of file test_bucket.c.
References bucket_test_wizard_state, and bucket_test_state::created.
 {
    if (bucket_test_wizard_state.created) {
       return -1;
    }
    bucket_test_wizard_state.created = 1;
    return 0;
 }
bucket_test_wizard_delete()
static int bucket_test_wizard_delete (const struct ast_sorcery * sorcery, void * data, void * object) static
Definition at line 100 of file test_bucket.c.
References bucket_test_wizard_state, and bucket_test_state::deleted.
 {
    if (bucket_test_wizard_state.deleted) {
       return -1;
    }
    bucket_test_wizard_state.deleted = 1;
    return 0;
 }
bucket_test_wizard_is_stale()
static int bucket_test_wizard_is_stale (const struct ast_sorcery * sorcery, void * data, void * object) static
Definition at line 111 of file test_bucket.c.
References bucket_test_wizard_state, and bucket_test_state::is_stale.
 {
    return bucket_test_wizard_state.is_stale;
 }
bucket_test_wizard_retrieve_id()
static void* bucket_test_wizard_retrieve_id (const struct ast_sorcery * sorcery, void * data, const char * type, const char * id) static
Definition at line 88 of file test_bucket.c.
References ast_bucket_alloc(), ast_bucket_file_alloc(), and NULL.
 {
    if (!strcmp(type, "bucket")) {
       return ast_bucket_alloc(id);
    } else if (!strcmp(type, "file")) {
       return ast_bucket_file_alloc(id);
    } else {
       return NULL;
    }
 }
bucket_test_wizard_update()
static int bucket_test_wizard_update (const struct ast_sorcery * sorcery, void * data, void * object) static
Definition at line 77 of file test_bucket.c.
References bucket_test_wizard_state, and bucket_test_state::updated.
 {
    if (bucket_test_wizard_state.updated) {
       return -1;
    }
    bucket_test_wizard_state.updated = 1;
    return 0;
 }
load_module()
static int load_module (void) static
Definition at line 1010 of file test_bucket.c.
References ast_bucket_file_temporary_create(), ast_bucket_file_temporary_destroy(), ast_bucket_scheme_register, ast_log, AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, AST_TEST_REGISTER, bucket_alloc(), bucket_file_alloc(), and LOG_ERROR.
 {
    if (ast_bucket_scheme_register("test", &bucket_test_wizard, &bucket_file_test_wizard,
       ast_bucket_file_temporary_create, ast_bucket_file_temporary_destroy)) {
       ast_log(LOG_ERROR, "Failed to register Bucket test wizard scheme implementation\n");
       return AST_MODULE_LOAD_DECLINE;
    }
    AST_TEST_REGISTER(bucket_scheme_register);
    AST_TEST_REGISTER(bucket_alloc);
    AST_TEST_REGISTER(bucket_create);
    AST_TEST_REGISTER(bucket_clone);
    AST_TEST_REGISTER(bucket_delete);
    AST_TEST_REGISTER(bucket_retrieve);
    AST_TEST_REGISTER(bucket_is_stale);
    AST_TEST_REGISTER(bucket_json);
    AST_TEST_REGISTER(bucket_file_alloc);
    AST_TEST_REGISTER(bucket_file_create);
    AST_TEST_REGISTER(bucket_file_clone);
    AST_TEST_REGISTER(bucket_file_copy);
    AST_TEST_REGISTER(bucket_file_retrieve);
    AST_TEST_REGISTER(bucket_file_update);
    AST_TEST_REGISTER(bucket_file_delete);
    AST_TEST_REGISTER(bucket_file_is_stale);
    AST_TEST_REGISTER(bucket_file_metadata_set);
    AST_TEST_REGISTER(bucket_file_metadata_unset);
    AST_TEST_REGISTER(bucket_file_metadata_get);
    AST_TEST_REGISTER(bucket_file_json);
    return AST_MODULE_LOAD_SUCCESS;
 }
unload_module()
static int unload_module (void) static
Definition at line 987 of file test_bucket.c.
References AST_TEST_UNREGISTER, bucket_alloc(), and bucket_file_alloc().
 {
    AST_TEST_UNREGISTER(bucket_scheme_register);
    AST_TEST_UNREGISTER(bucket_alloc);
    AST_TEST_UNREGISTER(bucket_create);
    AST_TEST_UNREGISTER(bucket_clone);
    AST_TEST_UNREGISTER(bucket_delete);
    AST_TEST_UNREGISTER(bucket_retrieve);
    AST_TEST_UNREGISTER(bucket_json);
    AST_TEST_UNREGISTER(bucket_file_alloc);
    AST_TEST_UNREGISTER(bucket_file_create);
    AST_TEST_UNREGISTER(bucket_file_clone);
    AST_TEST_UNREGISTER(bucket_file_copy);
    AST_TEST_UNREGISTER(bucket_file_retrieve);
    AST_TEST_UNREGISTER(bucket_file_update);
    AST_TEST_UNREGISTER(bucket_file_delete);
    AST_TEST_UNREGISTER(bucket_file_metadata_set);
    AST_TEST_UNREGISTER(bucket_file_metadata_unset);
    AST_TEST_UNREGISTER(bucket_file_metadata_get);
    AST_TEST_UNREGISTER(bucket_file_json);
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Bucket test module" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, } static
Definition at line 1041 of file test_bucket.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 1041 of file test_bucket.c.
bucket_file_test_wizard
struct ast_sorcery_wizard bucket_file_test_wizard static
Definition at line 124 of file test_bucket.c.
bucket_test_wizard
struct ast_sorcery_wizard bucket_test_wizard static
Definition at line 116 of file test_bucket.c.
bucket_test_wizard_state
struct bucket_test_state bucket_test_wizard_state static
Global scope structure for testing bucket wizards.
Definition at line 56 of file test_bucket.c.
Referenced by AST_TEST_DEFINE(), bucket_test_wizard_clear(), bucket_test_wizard_create(), bucket_test_wizard_delete(), bucket_test_wizard_is_stale(), and bucket_test_wizard_update().