Asterisk - The Open Source Telephony Project: app_dtmfstore.c File Reference
app_dtmfstore.c File Reference
Module: Dial plan functions
Technology independent asynchronous DTMF collection.
#include "asterisk.h"
#include "asterisk/module.h"
#include "asterisk/channel.h"
#include "asterisk/pbx.h"
#include "asterisk/framehook.h"
#include "asterisk/app.h"
#include "asterisk/conversions.h"
Data Structures
struct dtmf_store_data
Private data structure used with the function's datastore.
Functions
AST_MODULE_INFO_STANDARD_EXTENDED (ASTERISK_GPL_KEY, "Technology independent async DTMF storage")
static void datastore_destroy_cb (void *data)
static struct ast_frame * dtmf_store_framehook (struct ast_channel *chan, struct ast_frame *f, enum ast_framehook_event event, void *data)
Frame hook that is called to intercept digit/undigit.
static int dtmfstore_exec (struct ast_channel *chan, const char *appdata)
static int load_module (void)
static int remove_dtmf_store (struct ast_channel *chan)
static int unload_module (void)
Variables
static char * app = "StoreDTMF"
static const struct ast_datastore_info dtmf_store_datastore
The channel datastore the function uses to store state.
Detailed Description
Technology independent asynchronous DTMF collection.
Author
Naveen Albert aster.nosp@m.isk@.nosp@m.phrea.nosp@m.knet.nosp@m..org
Definition in file app_dtmfstore.c.
Function Documentation
AST_MODULE_INFO_STANDARD_EXTENDED()
AST_MODULE_INFO_STANDARD_EXTENDED (ASTERISK_GPL_KEY , "Technology independent async DTMF storage")
Referenced by load_module().
datastore_destroy_cb()
static void datastore_destroy_cb (void * data) static
Definition at line 79 of file app_dtmfstore.c.
References ast_free, d, dtmf_store_data::rx_var, and dtmf_store_data::tx_var.
{
    struct dtmf_store_data *d;
    d = data;
    if (d) {
       if (d->rx_var) {
          ast_free(d->rx_var);
       }
       if (d->tx_var) {
          ast_free(d->tx_var);
       }
       ast_free(data);
    }
 }
dtmf_store_framehook()
static struct ast_frame* dtmf_store_framehook (struct ast_channel * chan, struct ast_frame * f, enum ast_framehook_event event, void * data) static
Frame hook that is called to intercept digit/undigit.
Definition at line 131 of file app_dtmfstore.c.
References ast_copy_string(), ast_debug, AST_FRAME_DTMF_END, AST_FRAMEHOOK_EVENT_READ, AST_FRAMEHOOK_EVENT_WRITE, ast_strlen_zero, ast_frame::frametype, ast_frame_subclass::integer, len(), dtmf_store_data::maxdigits, NULL, pbx_builtin_setvar_helper(), pbx_substitute_variables_helper(), remove_dtmf_store(), dtmf_store_data::rx_var, ast_frame::subclass, and dtmf_store_data::tx_var.
Referenced by dtmfstore_exec().
 {
    char currentdata[512];
    char varnamesub[64];
    char *varname = NULL;
    struct dtmf_store_data *framedata = data;
    int len;
    if (!f || !framedata) {
       return f;
    }
    if ((event != AST_FRAMEHOOK_EVENT_WRITE) && (event != AST_FRAMEHOOK_EVENT_READ)) {
       return f;
    }
    if (f->frametype != AST_FRAME_DTMF_END) {
       return f;
    }
    /* If this is DTMF then store the digits */
    if (event == AST_FRAMEHOOK_EVENT_READ && framedata->rx_var) { /* coming from source */
       varname = framedata->rx_var;
    } else if (event == AST_FRAMEHOOK_EVENT_WRITE && framedata->tx_var) { /* going to source */
       varname = framedata->tx_var;
    }
    if (!varname) {
       return f;
    }
    sprintf(varnamesub, "${%s}", varname);
    pbx_substitute_variables_helper(chan, varnamesub, currentdata, 511);
    /* pbx_builtin_getvar_helper works for regular vars but not CDR vars */
    if (ast_strlen_zero(currentdata)) { /* var doesn't exist yet */
       ast_debug(3, "Creating new digit store: %s\n", varname);
    }
    len = strlen(currentdata);
    if (framedata->maxdigits > 0 && len >= framedata->maxdigits) {
       ast_debug(3, "Reached digit limit: %d\n", framedata->maxdigits);
       remove_dtmf_store(chan); /* reached max digit count, stop now */
       return f;
    } else {
       char newdata[len + 2]; /* one more char + terminator */
       if (len > 0) {
          ast_copy_string(newdata, currentdata, len + 2);
       }
       newdata[len] = (unsigned) f->subclass.integer;
       newdata[len + 1] = '\0';
       ast_debug(3, "Appending to digit store: now %s\n", newdata);
       pbx_builtin_setvar_helper(chan, varname, newdata);
    }
    return f;
 }
dtmfstore_exec()
static int dtmfstore_exec (struct ast_channel * chan, const char * appdata) static
Definition at line 188 of file app_dtmfstore.c.
References args, AST_APP_ARG, ast_calloc, ast_channel_datastore_add(), ast_channel_datastore_find(), ast_channel_name(), ast_datastore_alloc, ast_datastore_free(), AST_DECLARE_APP_ARGS, ast_framehook_attach(), AST_FRAMEHOOK_INTERFACE_VERSION, ast_free, ast_log, AST_LOG_WARNING, AST_STANDARD_APP_ARGS, ast_str_to_int(), ast_strdup, ast_strdupa, ast_strlen_zero, ast_datastore::data, ast_framehook_interface::data, dtmf_store_framehook(), dtmf_store_data::framehook_id, LOG_ERROR, LOG_WARNING, dtmf_store_data::maxdigits, NULL, parse(), remove_dtmf_store(), dtmf_store_data::rx_var, SCOPED_CHANNELLOCK, dtmf_store_data::tx_var, and ast_framehook_interface::version.
Referenced by load_module().
 {
    struct ast_datastore *datastore;
    struct dtmf_store_data *data;
    static struct ast_framehook_interface digit_framehook_interface = {
       .version = AST_FRAMEHOOK_INTERFACE_VERSION,
       .event_cb = dtmf_store_framehook,
       .disable_inheritance = 1,
    };
    char *parse = ast_strdupa(appdata);
    AST_DECLARE_APP_ARGS(args,
       AST_APP_ARG(direction);
       AST_APP_ARG(varname);
       AST_APP_ARG(maxdigits);
    );
    SCOPED_CHANNELLOCK(chan_lock, chan);
    AST_STANDARD_APP_ARGS(args, parse);
    if (ast_strlen_zero(appdata)) {
       ast_log(AST_LOG_WARNING, "StoreDTMF requires an argument\n");
       return -1;
    }
    if (!strcasecmp(args.direction, "remove")) {
       return remove_dtmf_store(chan);
    }
    datastore = ast_channel_datastore_find(chan, &dtmf_store_datastore, NULL);
    if (datastore) {
       ast_log(AST_LOG_WARNING, "StoreDTMF already set on '%s'\n",
               ast_channel_name(chan));
       return 0;
    }
    datastore = ast_datastore_alloc(&dtmf_store_datastore, NULL);
    if (!datastore) {
       return -1;
    }
    data = ast_calloc(1, sizeof(*data));
    if (!data) {
       ast_datastore_free(datastore);
       return -1;
    }
    digit_framehook_interface.data = data;
    data->rx_var = NULL;
    data->tx_var = NULL;
    data->maxdigits = 0;
    if (!strcasecmp(args.direction, "tx")) {
       data->tx_var = ast_strdup(args.varname);
    } else if (!strcasecmp(args.direction, "rx")) {
       data->rx_var = ast_strdup(args.varname);
    } else {
       ast_log(LOG_ERROR, "Direction must be either RX or TX\n");
       return -1;
    }
    if (!ast_strlen_zero(args.maxdigits)) {
       if (ast_str_to_int(args.maxdigits,&(data->maxdigits))) {
          ast_log(LOG_ERROR, "Invalid integer: %s\n", args.maxdigits);
          return -1;
       }
       if (data->maxdigits < 0) {
          ast_log(LOG_ERROR, "Invalid natural number: %d\n", data->maxdigits);
          return -1;
       } else if (data->maxdigits == 0) {
          ast_log(LOG_WARNING, "No maximum digit count set\n");
       }
    }
    data->framehook_id = ast_framehook_attach(chan, &digit_framehook_interface);
    if (data->framehook_id < 0) {
       ast_log(AST_LOG_WARNING, "Failed to attach StoreDTMF framehook to '%s'\n",
               ast_channel_name(chan));
       ast_datastore_free(datastore);
       ast_free(data);
       return -1;
    }
    datastore->data = data;
    ast_channel_datastore_add(chan, datastore);
    return 0;
 }
load_module()
static int load_module (void) static
Definition at line 281 of file app_dtmfstore.c.
References app, AST_MODULE_INFO_STANDARD_EXTENDED(), ast_register_application_xml, ASTERISK_GPL_KEY, and dtmfstore_exec().
 {
    return ast_register_application_xml(app, dtmfstore_exec);
 }
remove_dtmf_store()
static int remove_dtmf_store (struct ast_channel * chan) static
Definition at line 100 of file app_dtmfstore.c.
References ast_channel_datastore_find(), ast_channel_datastore_remove(), ast_channel_name(), ast_datastore_free(), ast_framehook_detach(), ast_log, AST_LOG_WARNING, ast_datastore::data, dtmf_store_data::framehook_id, NULL, and SCOPED_CHANNELLOCK.
Referenced by dtmf_store_framehook(), and dtmfstore_exec().
 {
    struct ast_datastore *datastore = NULL;
    struct dtmf_store_data *data;
    SCOPED_CHANNELLOCK(chan_lock, chan);
    datastore = ast_channel_datastore_find(chan, &dtmf_store_datastore, NULL);
    if (!datastore) {
       ast_log(AST_LOG_WARNING, "Cannot remove StoreDTMF from %s: StoreDTMF not currently enabled\n",
               ast_channel_name(chan));
       return -1;
    }
    data = datastore->data;
    if (ast_framehook_detach(chan, data->framehook_id)) {
       ast_log(AST_LOG_WARNING, "Failed to remove StoreDTMF framehook from channel %s\n",
               ast_channel_name(chan));
       return -1;
    }
    if (ast_channel_datastore_remove(chan, datastore)) {
       ast_log(AST_LOG_WARNING, "Failed to remove StoreDTMF datastore from channel %s\n",
               ast_channel_name(chan));
       return -1;
    }
    ast_datastore_free(datastore);
    return 0;
 }
unload_module()
static int unload_module (void) static
Definition at line 276 of file app_dtmfstore.c.
References app, and ast_unregister_application().
 {
    return ast_unregister_application(app);
 }
Variable Documentation
app
char* app = "StoreDTMF" static
Definition at line 69 of file app_dtmfstore.c.
Referenced by load_module(), and unload_module().
dtmf_store_datastore
const struct ast_datastore_info dtmf_store_datastore static
Initial value:
= {
   .type = "dtmf_store",
   .destroy = datastore_destroy_cb
}
The channel datastore the function uses to store state.
Definition at line 94 of file app_dtmfstore.c.