Asterisk - The Open Source Telephony Project: test_astobj2.c File Reference
test_astobj2.c File Reference
astobj2 test module
#include "asterisk.h"
#include "asterisk/utils.h"
#include "asterisk/module.h"
#include "asterisk/test.h"
#include "asterisk/astobj2.h"
Data Structures
struct test_obj
Macros
#define ITERATIONS 100000
#define OBJS 73
Enumerations
enum test_container_type { TEST_CONTAINER_LIST, TEST_CONTAINER_HASH, TEST_CONTAINER_RBTREE }
Functions
static void __reg_module (void)
static void __unreg_module (void)
static int all_but_one_cb (void *obj, void *arg, int flag)
static AO2_GLOBAL_OBJ_STATIC (astobj2_holder)
struct ast_module * AST_MODULE_SELF_SYM (void)
AST_TEST_DEFINE (astobj2_test_1)
AST_TEST_DEFINE (astobj2_test_2)
AST_TEST_DEFINE (astobj2_test_3)
AST_TEST_DEFINE (astobj2_test_4)
AST_TEST_DEFINE (astobj2_test_perf)
static int astobj2_test_1_helper (int tst_num, enum test_container_type type, int use_sort, unsigned int lim, struct ast_test *test)
static int increment_cb (void *obj, void *arg, int flag)
static int insert_test_duplicates (struct ao2_container *container, int *destroy_counter, int number, const char *prefix, struct ast_test *test)
static int insert_test_vector (struct ao2_container *container, int *destroy_counter, const int *vector, int count, const char *prefix, struct ast_test *test)
static int load_module (void)
static int multiple_cb (void *obj, void *arg, int flag)
static int test_ao2_callback_traversal (int res, struct ao2_container *container, enum search_flags flags, ao2_callback_fn *cmp_fn, void *arg, const int *vector, int count, const char *prefix, struct ast_test *test)
static int test_ao2_find_w_no_flags (int res, struct ao2_container *look_in, int limit, struct ast_test *test)
static int test_ao2_find_w_OBJ_KEY (int res, struct ao2_container *look_in, int limit, struct ast_test *test)
static int test_ao2_find_w_OBJ_PARTIAL_KEY (int res, struct ao2_container *look_in, int limit, struct ast_test *test)
static int test_ao2_find_w_OBJ_POINTER (int res, struct ao2_container *look_in, int limit, struct ast_test *test)
static int test_ao2_iteration (int res, struct ao2_container *container, enum ao2_iterator_flags flags, const int *vector, int count, const char *prefix, struct ast_test *test)
static int test_cmp_cb (void *obj, void *arg, int flags)
static const char * test_container2str (enum test_container_type type)
static int test_container_clone (int res, struct ao2_container *orig, struct ast_test *test)
static int test_expected_duplicates (int res, struct ao2_container *container, enum search_flags flags, int number, const int *vector, int count, const char *prefix, struct ast_test *test)
static int test_hash_cb (const void *obj, const int flags)
static struct ao2_container * test_make_nonsorted (enum test_container_type type, int options)
static struct ao2_container * test_make_sorted (enum test_container_type type, int options)
static void test_obj_destructor (void *v_obj)
static enum ast_test_result_state test_performance (struct ast_test *test, enum test_container_type type, unsigned int copt)
static int test_sort_cb (const void *obj_left, const void *obj_right, int flags)
static int test_traversal_nonsorted (int res, int tst_num, enum test_container_type type, struct ast_test *test)
static int test_traversal_sorted (int res, int tst_num, enum test_container_type type, struct ast_test *test)
static enum ast_test_result_state testloop (struct ast_test *test, enum test_container_type type, int copt, int iterations)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "ASTOBJ2 Unit Tests" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, }
static const struct ast_module_info * ast_module_info = &__mod_info
int partial_key_match_range
Detailed Description
astobj2 test module
Author
David Vossel dvoss.nosp@m.el@d.nosp@m.igium.nosp@m..com
Definition in file test_astobj2.c.
Macro Definition Documentation
ITERATIONS
#define ITERATIONS 100000
Referenced by AST_TEST_DEFINE().
OBJS
#define OBJS 73
Referenced by test_performance().
Enumeration Type Documentation
test_container_type
enum test_container_type
Enumerator
TEST_CONTAINER_LIST
TEST_CONTAINER_HASH
TEST_CONTAINER_RBTREE
Definition at line 41 of file test_astobj2.c.
{
    TEST_CONTAINER_LIST,
    TEST_CONTAINER_HASH,
    TEST_CONTAINER_RBTREE,
 };
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 2074 of file test_astobj2.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 2074 of file test_astobj2.c.
all_but_one_cb()
static int all_but_one_cb (void * obj, void * arg, int flag) static
Definition at line 104 of file test_astobj2.c.
References CMP_MATCH, and test_obj::i.
Referenced by astobj2_test_1_helper().
 {
    struct test_obj *cmp_obj = (struct test_obj *) obj;
    return (cmp_obj->i) ? CMP_MATCH : 0;
 }
AO2_GLOBAL_OBJ_STATIC()
static AO2_GLOBAL_OBJ_STATIC (astobj2_holder) static
Referenced by AST_TEST_DEFINE().
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 2074 of file test_astobj2.c.
AST_TEST_DEFINE() [1/5]
AST_TEST_DEFINE (astobj2_test_1)
Definition at line 648 of file test_astobj2.c.
References AST_TEST_FAIL, AST_TEST_NOT_RUN, AST_TEST_PASS, astobj2_test_1_helper(), sip_to_pjsip::info(), TEST_CONTAINER_HASH, TEST_CONTAINER_LIST, TEST_CONTAINER_RBTREE, TEST_EXECUTE, and TEST_INIT.
 {
    int res = AST_TEST_PASS;
    switch (cmd) {
    case TEST_INIT:
       info->name = "astobj2_test1";
       info->category = "/main/astobj2/";
       info->summary = "Test ao2 objects, containers, callbacks, and iterators";
       info->description =
          "Builds ao2_containers with various item numbers, bucket sizes, cmp and hash "
          "functions. Runs a series of tests to manipulate the container using callbacks "
          "and iterators.  Verifies expected behavior.";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    /* Test number, container_type, use_sort, number of objects. */
    if ((res = astobj2_test_1_helper(1, TEST_CONTAINER_LIST, 0, 50, test)) == AST_TEST_FAIL) {
       return res;
    }
    if ((res = astobj2_test_1_helper(2, TEST_CONTAINER_LIST, 1, 50, test)) == AST_TEST_FAIL) {
       return res;
    }
    if ((res = astobj2_test_1_helper(3, TEST_CONTAINER_HASH, 0, 1000, test)) == AST_TEST_FAIL) {
       return res;
    }
    if ((res = astobj2_test_1_helper(4, TEST_CONTAINER_HASH, 1, 1000, test)) == AST_TEST_FAIL) {
       return res;
    }
    if ((res = astobj2_test_1_helper(4, TEST_CONTAINER_RBTREE, 1, 1000, test)) == AST_TEST_FAIL) {
       return res;
    }
    return res;
 }
AST_TEST_DEFINE() [2/5]
AST_TEST_DEFINE (astobj2_test_2)
Definition at line 690 of file test_astobj2.c.
References ao2_alloc, AO2_ALLOC_OPT_LOCK_MUTEX, ao2_container_alloc_list, ao2_container_check(), ao2_container_count(), ao2_find, AO2_GLOBAL_OBJ_STATIC(), ao2_iterator_destroy(), ao2_iterator_init(), ao2_iterator_next, ao2_link, ao2_ref, AST_TEST_FAIL, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_test_status_update, c, cleanup(), test_obj::destructor_count, test_obj::i, sip_to_pjsip::info(), NULL, OBJ_POINTER, test_cmp_cb(), TEST_EXECUTE, TEST_INIT, and test_obj_destructor().
 {
    int res = AST_TEST_PASS;
    struct ao2_container *c;
    struct ao2_iterator i;
    struct test_obj *obj;
    int num;
    static const int NUM_OBJS = 5;
    int destructor_count = NUM_OBJS;
    struct test_obj tmp_obj = { 0, };
    switch (cmd) {
    case TEST_INIT:
       info->name = "astobj2_test2";
       info->category = "/main/astobj2/";
       info->summary = "Test a certain scenario using ao2 iterators";
       info->description =
          "This test is aimed at testing for a specific regression that occurred. "
          "Add some objects into a container.  Mix finds and iteration and make "
          "sure that the iterator still sees all objects.";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    c = ao2_container_alloc_list(AO2_ALLOC_OPT_LOCK_MUTEX, 0, NULL, test_cmp_cb);
    if (!c) {
       ast_test_status_update(test, "ao2_container_alloc_list failed.\n");
       res = AST_TEST_FAIL;
       goto cleanup;
    }
    for (num = 1; num <= NUM_OBJS; num++) {
       if (!(obj = ao2_alloc(sizeof(struct test_obj), test_obj_destructor))) {
          ast_test_status_update(test, "ao2_alloc failed.\n");
          res = AST_TEST_FAIL;
          goto cleanup;
       }
       obj->destructor_count = &destructor_count;
       obj->i = num;
       ao2_link(c, obj);
       ao2_ref(obj, -1);
       if (ao2_container_count(c) != num) {
          ast_test_status_update(test, "container did not link correctly\n");
          res = AST_TEST_FAIL;
       }
    }
    if (ao2_container_check(c, 0)) {
       ast_test_status_update(test, "container integrity check failed\n");
       res = AST_TEST_FAIL;
       goto cleanup;
    }
    /*
     * Iteration take 1.  Just make sure we see all NUM_OBJS objects.
     */
    num = 0;
    i = ao2_iterator_init(c, 0);
    while ((obj = ao2_iterator_next(&i))) {
       num++;
       ao2_ref(obj, -1);
    }
    ao2_iterator_destroy(&i);
    if (num != NUM_OBJS) {
       ast_test_status_update(test, "iterate take 1, expected '%d', only saw '%d' objects\n",
             NUM_OBJS, num);
       res = AST_TEST_FAIL;
    }
    /*
     * Iteration take 2.  Do a find for the last object, then iterate and make
     * sure we find all NUM_OBJS objects.
     */
    tmp_obj.i = NUM_OBJS;
    obj = ao2_find(c, &tmp_obj, OBJ_POINTER);
    if (!obj) {
       ast_test_status_update(test, "ao2_find() failed.\n");
       res = AST_TEST_FAIL;
    } else {
       ao2_ref(obj, -1);
    }
    num = 0;
    i = ao2_iterator_init(c, 0);
    while ((obj = ao2_iterator_next(&i))) {
       num++;
       ao2_ref(obj, -1);
    }
    ao2_iterator_destroy(&i);
    if (num != NUM_OBJS) {
       ast_test_status_update(test, "iterate take 2, expected '%d', only saw '%d' objects\n",
             NUM_OBJS, num);
       res = AST_TEST_FAIL;
    }
    /*
     * Iteration take 3.  Do a find for an object while in the middle
     * of iterating;
     */
    num = 0;
    i = ao2_iterator_init(c, 0);
    while ((obj = ao2_iterator_next(&i))) {
       if (num == 1) {
          struct test_obj *obj2;
          tmp_obj.i = NUM_OBJS - 1;
          obj2 = ao2_find(c, &tmp_obj, OBJ_POINTER);
          if (!obj2) {
             ast_test_status_update(test, "ao2_find() failed.\n");
             res = AST_TEST_FAIL;
          } else {
             ao2_ref(obj2, -1);
          }
       }
       num++;
       ao2_ref(obj, -1);
    }
    ao2_iterator_destroy(&i);
    if (num != NUM_OBJS) {
       ast_test_status_update(test, "iterate take 3, expected '%d', only saw '%d' objects\n",
             NUM_OBJS, num);
       res = AST_TEST_FAIL;
    }
 cleanup:
    if (c) {
       ao2_ref(c, -1);
    }
    return res;
 }
AST_TEST_DEFINE() [3/5]
AST_TEST_DEFINE (astobj2_test_3)
Definition at line 827 of file test_astobj2.c.
References ao2_alloc, ao2_ref, ao2_t_global_obj_ref, ao2_t_global_obj_release, ao2_t_global_obj_replace, ao2_t_global_obj_replace_unref, ao2_t_ref, AST_TEST_FAIL, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_test_status_update, cleanup(), test_obj::destructor_count, test_obj::i, sip_to_pjsip::info(), NULL, TEST_EXECUTE, TEST_INIT, and test_obj_destructor().
 {
    int res = AST_TEST_PASS;
    int destructor_count = 0;
    int num_objects = 0;
    struct test_obj *obj = NULL;
    struct test_obj *obj2 = NULL;
    struct test_obj *obj3 = NULL;
    switch (cmd) {
    case TEST_INIT:
       info->name = "astobj2_test3";
       info->category = "/main/astobj2/";
       info->summary = "Test global ao2 holder";
       info->description =
          "This test is to see if the global ao2 holder works as intended.";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    /* Put an object in the holder */
    obj = ao2_alloc(sizeof(struct test_obj), test_obj_destructor);
    if (!obj) {
       ast_test_status_update(test, "ao2_alloc failed.\n");
       res = AST_TEST_FAIL;
       goto cleanup;
    }
    obj->destructor_count = &destructor_count;
    obj->i = ++num_objects;
    obj2 = ao2_t_global_obj_replace(astobj2_holder, obj, "Save object in the holder");
    if (obj2) {
       ast_test_status_update(test, "Returned object not expected.\n");
       res = AST_TEST_FAIL;
       goto cleanup;
    }
    /* Save object for next check. */
    obj3 = obj;
    /* Replace an object in the holder */
    obj = ao2_alloc(sizeof(struct test_obj), test_obj_destructor);
    if (!obj) {
       ast_test_status_update(test, "ao2_alloc failed.\n");
       res = AST_TEST_FAIL;
       goto cleanup;
    }
    obj->destructor_count = &destructor_count;
    obj->i = ++num_objects;
    obj2 = ao2_t_global_obj_replace(astobj2_holder, obj, "Replace object in the holder");
    if (!obj2) {
       ast_test_status_update(test, "Expected an object.\n");
       res = AST_TEST_FAIL;
       goto cleanup;
    }
    if (obj2 != obj3) {
       ast_test_status_update(test, "Replaced object not expected object.\n");
       res = AST_TEST_FAIL;
       goto cleanup;
    }
    ao2_ref(obj3, -1);
    obj3 = NULL;
    ao2_ref(obj2, -1);
    obj2 = NULL;
    ao2_ref(obj, -1);
    /* Replace with unref of an object in the holder */
    obj = ao2_alloc(sizeof(struct test_obj), test_obj_destructor);
    if (!obj) {
       ast_test_status_update(test, "ao2_alloc failed.\n");
       res = AST_TEST_FAIL;
       goto cleanup;
    }
    obj->destructor_count = &destructor_count;
    obj->i = ++num_objects;
    if (!ao2_t_global_obj_replace_unref(astobj2_holder, obj, "Replace w/ unref object in the holder")) {
       ast_test_status_update(test, "Expected an object to be replaced.\n");
       res = AST_TEST_FAIL;
       goto cleanup;
    }
    /* Save object for next check. */
    obj3 = obj;
    /* Get reference to held object. */
    obj = ao2_t_global_obj_ref(astobj2_holder, "Get a held object reference");
    if (!obj) {
       ast_test_status_update(test, "Expected an object.\n");
       res = AST_TEST_FAIL;
       goto cleanup;
    }
    if (obj != obj3) {
       ast_test_status_update(test, "Referenced object not expected object.\n");
       res = AST_TEST_FAIL;
       goto cleanup;
    }
    ao2_ref(obj3, -1);
    obj3 = NULL;
    ao2_ref(obj, -1);
    obj = NULL;
    /* Release the object in the global holder. */
    ao2_t_global_obj_release(astobj2_holder, "Check release all objects");
    destructor_count += num_objects;
    if (0 < destructor_count) {
       ast_test_status_update(test,
          "all destructors were not called, destructor count is %d\n",
          destructor_count);
       res = AST_TEST_FAIL;
    } else if (destructor_count < 0) {
       ast_test_status_update(test,
          "Destructor was called too many times, destructor count is %d\n",
          destructor_count);
       res = AST_TEST_FAIL;
    }
 cleanup:
    if (obj) {
       ao2_t_ref(obj, -1, "Test cleanup external object 1");
    }
    if (obj2) {
       ao2_t_ref(obj2, -1, "Test cleanup external object 2");
    }
    if (obj3) {
       ao2_t_ref(obj3, -1, "Test cleanup external object 3");
    }
    ao2_t_global_obj_release(astobj2_holder, "Test cleanup holder");
    return res;
 }
AST_TEST_DEFINE() [4/5]
AST_TEST_DEFINE (astobj2_test_4)
Definition at line 1898 of file test_astobj2.c.
References AST_TEST_NOT_RUN, AST_TEST_PASS, sip_to_pjsip::info(), TEST_CONTAINER_HASH, TEST_CONTAINER_LIST, TEST_CONTAINER_RBTREE, TEST_EXECUTE, TEST_INIT, test_traversal_nonsorted(), and test_traversal_sorted().
 {
    int res = AST_TEST_PASS;
    switch (cmd) {
    case TEST_INIT:
       info->name = "astobj2_test4";
       info->category = "/main/astobj2/";
       info->summary = "Test container traversal/iteration";
       info->description =
          "This test is to see if the container traversal/iteration works "
          "as intended for each supported container type.";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    res = test_traversal_nonsorted(res, 1, TEST_CONTAINER_LIST, test);
    res = test_traversal_nonsorted(res, 2, TEST_CONTAINER_HASH, test);
    res = test_traversal_sorted(res, 3, TEST_CONTAINER_LIST, test);
    res = test_traversal_sorted(res, 4, TEST_CONTAINER_HASH, test);
    res = test_traversal_sorted(res, 5, TEST_CONTAINER_RBTREE, test);
    return res;
 }
AST_TEST_DEFINE() [5/5]
AST_TEST_DEFINE (astobj2_test_perf)
The number of iteration of testloop to be performed.
Note
In order to keep the elapsed time sane, if AO2_DEBUG is defined in menuselect, only 25000 iterations are performed. Otherwise 100000.
Definition at line 2013 of file test_astobj2.c.
References AST_TEST_NOT_RUN, AST_TEST_PASS, sip_to_pjsip::info(), ITERATIONS, TEST_CONTAINER_HASH, TEST_CONTAINER_LIST, TEST_CONTAINER_RBTREE, TEST_EXECUTE, TEST_INIT, and testloop().
 {
 /*!
  * \brief The number of iteration of testloop to be performed.
  * \note
  * In order to keep the elapsed time sane, if AO2_DEBUG is defined in menuselect,
  * only 25000 iterations are performed.   Otherwise 100000.
  */
 #ifdef AO2_DEBUG
 #define ITERATIONS 25000
 #else
 #define ITERATIONS 100000
 #endif
    int res = AST_TEST_PASS;
    switch (cmd) {
    case TEST_INIT:
       info->name = "astobj2_test_perf";
       info->category = "/main/astobj2/perf/";
       info->summary = "Test container performance";
       info->description =
          "Runs container traversal tests.";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    res = testloop(test, TEST_CONTAINER_LIST, 0, ITERATIONS);
    if (!res) {
       return res;
    }
    res = testloop(test, TEST_CONTAINER_HASH, 0, ITERATIONS);
    if (!res) {
       return res;
    }
    res = testloop(test, TEST_CONTAINER_RBTREE, 0, ITERATIONS);
    return res;
 }
astobj2_test_1_helper()
static int astobj2_test_1_helper (int tst_num, enum test_container_type type, int use_sort, unsigned int lim, struct ast_test * test) static
Definition at line 421 of file test_astobj2.c.
References all_but_one_cb(), AO2_ALLOC_OPT_LOCK_MUTEX, ao2_container_check(), ao2_container_count(), ao2_container_dump(), ao2_container_stats(), ao2_iterator_destroy(), ao2_iterator_init(), ao2_link, ao2_t_alloc, ao2_t_callback, ao2_t_container_alloc_hash, ao2_t_container_alloc_list, ao2_t_container_alloc_rbtree, ao2_t_iterator_next, ao2_t_link, ao2_t_ref, ao2_t_unlink, ast_random(), ast_test_debug(), AST_TEST_FAIL, AST_TEST_PASS, ast_test_status_update, cleanup(), test_obj::destructor_count, test_obj::i, increment_cb(), multiple_cb(), NULL, OBJ_MULTIPLE, OBJ_NODATA, OBJ_UNLINK, test_ao2_find_w_no_flags(), test_ao2_find_w_OBJ_KEY(), test_ao2_find_w_OBJ_PARTIAL_KEY(), test_ao2_find_w_OBJ_POINTER(), test_cmp_cb(), test_container2str(), test_container_clone(), TEST_CONTAINER_HASH, TEST_CONTAINER_LIST, TEST_CONTAINER_RBTREE, test_hash_cb(), test_obj_destructor(), and test_sort_cb().
Referenced by AST_TEST_DEFINE().
 {
    const char *c_type;
    struct ao2_container *c1;
    struct ao2_container *c2;
    struct ao2_iterator it;
    struct ao2_iterator *mult_it;
    struct test_obj *obj;
    int n_buckets = 0;
    int increment = 0;
    int destructor_count = 0;
    int num;
    int res = AST_TEST_PASS;
    c_type = test_container2str(type);
    ast_test_status_update(test, "Test %d, %s containers (%s).\n",
       tst_num, c_type, use_sort ? "sorted" : "non-sorted");
    c1 = NULL;
    switch (type) {
    case TEST_CONTAINER_LIST:
       /* Lists just have one bucket. */
       n_buckets = 1;
       c1 = ao2_t_container_alloc_list(AO2_ALLOC_OPT_LOCK_MUTEX, 0,
          use_sort ? test_sort_cb : NULL, test_cmp_cb, "test");
       break;
    case TEST_CONTAINER_HASH:
       n_buckets = (ast_random() % ((lim / 4) + 1)) + 1;
       c1 = ao2_t_container_alloc_hash(AO2_ALLOC_OPT_LOCK_MUTEX, 0, n_buckets,
          test_hash_cb, use_sort ? test_sort_cb : NULL, test_cmp_cb, "test");
       break;
    case TEST_CONTAINER_RBTREE:
       /* RBTrees just have one bucket. */
       n_buckets = 1;
       c1 = ao2_t_container_alloc_rbtree(AO2_ALLOC_OPT_LOCK_MUTEX, 0,
          test_sort_cb, test_cmp_cb, "test");
       break;
    }
    c2 = ao2_t_container_alloc_list(AO2_ALLOC_OPT_LOCK_MUTEX, 0, NULL, NULL, "test");
    if (!c1 || !c2) {
       ast_test_status_update(test, "ao2_container_alloc failed.\n");
       res = AST_TEST_FAIL;
       goto cleanup;
    }
    /* Create objects and link into container */
    for (num = 0; num < lim; ++num) {
       if (!(obj = ao2_t_alloc(sizeof(struct test_obj), test_obj_destructor, "making zombies"))) {
          ast_test_status_update(test, "ao2_alloc failed.\n");
          res = AST_TEST_FAIL;
          goto cleanup;
       }
       ++destructor_count;
       obj->destructor_count = &destructor_count;
       obj->i = num;
       ao2_link(c1, obj);
       ao2_t_ref(obj, -1, "test");
       if (ao2_container_check(c1, 0)) {
          ast_test_status_update(test, "container integrity check failed linking obj num:%d\n", num);
          res = AST_TEST_FAIL;
          goto cleanup;
       }
       if (ao2_container_count(c1) != num + 1) {
          ast_test_status_update(test, "container did not link correctly\n");
          res = AST_TEST_FAIL;
       }
    }
    ast_test_status_update(test, "%s container created: buckets: %d, items: %u\n",
       c_type, n_buckets, lim);
    /* Testing ao2_container_clone */
    res = test_container_clone(res, c1, test);
    /* Testing ao2_find with no flags */
    res = test_ao2_find_w_no_flags(res, c1, lim, test);
    /* Testing ao2_find with OBJ_POINTER */
    res = test_ao2_find_w_OBJ_POINTER(res, c1, lim, test);
    /* Testing ao2_find with OBJ_KEY */
    res = test_ao2_find_w_OBJ_KEY(res, c1, lim, test);
    /* Testing ao2_find with OBJ_PARTIAL_KEY */
    res = test_ao2_find_w_OBJ_PARTIAL_KEY(res, c1, lim, test);
    /* Test Callback with no flags. */
    increment = 0;
    ao2_t_callback(c1, 0, increment_cb, &increment, "test callback");
    if (increment != lim) {
       ast_test_status_update(test, "callback with no flags failed. Increment is %d\n", increment);
       res = AST_TEST_FAIL;
    }
    /* Test Callback with OBJ_NODATA. This should do nothing different than with no flags here. */
    increment = 0;
    ao2_t_callback(c1, OBJ_NODATA, increment_cb, &increment, "test callback");
    if (increment != lim) {
       ast_test_status_update(test, "callback with OBJ_NODATA failed. Increment is %d\n", increment);
       res = AST_TEST_FAIL;
    }
    /* Test OBJ_MULTIPLE with OBJ_UNLINK, add items back afterwards */
    num = lim < 25 ? lim : 25;
    if (!(mult_it = ao2_t_callback(c1, OBJ_MULTIPLE | OBJ_UNLINK, multiple_cb, &num, "test multiple"))) {
       ast_test_status_update(test, "OBJ_MULTIPLE with OBJ_UNLINK test failed.\n");
       res = AST_TEST_FAIL;
    } else {
       /* make sure num items unlinked is as expected */
       if ((lim - ao2_container_count(c1)) != num) {
          ast_test_status_update(test, "OBJ_MULTIPLE | OBJ_UNLINK test failed, did not unlink correct number of objects.\n");
          res = AST_TEST_FAIL;
       }
       if (ao2_container_check(c1, 0)) {
          ast_test_status_update(test, "container integrity check failed\n");
          res = AST_TEST_FAIL;
          goto cleanup;
       }
       /* link what was unlinked back into c1 */
       while ((obj = ao2_t_iterator_next(mult_it, "test"))) {
          ao2_t_link(c1, obj, "test");
          ao2_t_ref(obj, -1, "test"); /* remove ref from iterator */
       }
       ao2_iterator_destroy(mult_it);
       if (ao2_container_check(c1, 0)) {
          ast_test_status_update(test, "container integrity check failed\n");
          res = AST_TEST_FAIL;
          goto cleanup;
       }
    }
    /* Test OBJ_MULTIPLE without unlink and iterate the returned container */
    num = 5;
    if (!(mult_it = ao2_t_callback(c1, OBJ_MULTIPLE, multiple_cb, &num, "test multiple"))) {
       ast_test_status_update(test, "OBJ_MULTIPLE without OBJ_UNLINK test failed.\n");
       res = AST_TEST_FAIL;
    } else {
       while ((obj = ao2_t_iterator_next(mult_it, "test"))) {
          ao2_t_ref(obj, -1, "test"); /* remove ref from iterator */
       }
       ao2_iterator_destroy(mult_it);
    }
    /* Test OBJ_MULTIPLE without unlink and no iterating */
    num = 5;
    if (!(mult_it = ao2_t_callback(c1, OBJ_MULTIPLE, multiple_cb, &num, "test multiple"))) {
       ast_test_status_update(test, "OBJ_MULTIPLE with no OBJ_UNLINK and no iterating failed.\n");
       res = AST_TEST_FAIL;
    } else {
       ao2_iterator_destroy(mult_it);
    }
    /* Is the container count what we expect after all the finds and unlinks? */
    if (ao2_container_count(c1) != lim) {
       ast_test_status_update(test, "container count does not match what is expected after ao2_find tests.\n");
       res = AST_TEST_FAIL;
    }
    /* Testing iterator.  Unlink a single object and break. do not add item back */
    it = ao2_iterator_init(c1, 0);
    num = ast_random() % lim; /* remove a random object */
    if (!num) {
       /*
        * Well we cannot remove object zero because of test with
        * all_but_one_cb later.
        */
       num = 1;
    }
    while ((obj = ao2_t_iterator_next(&it, "test"))) {
       if (obj->i == num) {
          ao2_t_unlink(c1, obj, "test");
          ao2_t_ref(obj, -1, "test");
          break;
       }
       ao2_t_ref(obj, -1, "test");
    }
    ao2_iterator_destroy(&it);
    /* Is the container count what we expect after removing a single item? */
    if (ao2_container_count(c1) != (lim - 1)) {
       ast_test_status_update(test, "unlink during iterator failed. Number %d was not removed.\n", num);
       res = AST_TEST_FAIL;
    }
    if (ao2_container_check(c1, 0)) {
       ast_test_status_update(test, "container integrity check failed\n");
       res = AST_TEST_FAIL;
       goto cleanup;
    }
    /* Test unlink all with OBJ_MULTIPLE, leave a single object for the container to destroy */
    ao2_t_callback(c1, OBJ_MULTIPLE | OBJ_UNLINK | OBJ_NODATA, all_but_one_cb, NULL, "test multiple");
    /* check to make sure all test_obj destructors were called except for 1 */
    if (destructor_count != 1) {
       ast_test_status_update(test, "OBJ_MULTIPLE | OBJ_UNLINK | OBJ_NODATA failed. destructor count %d\n", destructor_count);
       res = AST_TEST_FAIL;
    }
    if (ao2_container_check(c1, 0)) {
       ast_test_status_update(test, "container integrity check failed\n");
       res = AST_TEST_FAIL;
    }
 #if defined(TEST_CONTAINER_DEBUG_DUMP)
    ao2_container_dump(c1, 0, "test_1 c1", (void *) test, (ao2_prnt_fn *) ast_test_debug, test_prnt_obj);
    ao2_container_stats(c1, 0, "test_1 c1", (void *) test, (ao2_prnt_fn *) ast_test_debug);
 #endif   /* defined(TEST_CONTAINER_DEBUG_DUMP) */
 cleanup:
    /* destroy containers */
    if (c1) {
       ao2_t_ref(c1, -1, "bye c1");
    }
    if (c2) {
       ao2_t_ref(c2, -1, "bye c2");
    }
    if (destructor_count > 0) {
       ast_test_status_update(test, "all destructors were not called, destructor count is %d\n", destructor_count);
       res = AST_TEST_FAIL;
    } else if (destructor_count < 0) {
       ast_test_status_update(test, "Destructor was called too many times, destructor count is %d\n", destructor_count);
       res = AST_TEST_FAIL;
    }
    return res;
 }
increment_cb()
static int increment_cb (void * obj, void * arg, int flag) static
Definition at line 96 of file test_astobj2.c.
References test_obj::i.
Referenced by astobj2_test_1_helper().
 {
    int *i = (int *) arg;
    *i = *i + 1;
    return 0;
 }
insert_test_duplicates()
static int insert_test_duplicates (struct ao2_container * container, int * destroy_counter, int number, const char * prefix, struct ast_test * test) static
Definition at line 1092 of file test_astobj2.c.
References ao2_alloc, ao2_container_check(), ao2_find, ao2_link, ao2_t_ref, ast_test_status_update, test_obj::destructor_count, test_obj::dup_number, test_obj::i, NULL, OBJ_KEY, and test_obj_destructor().
Referenced by test_traversal_sorted().
 {
    int count;
    struct test_obj *obj;
    struct test_obj *obj_dup;
    /* Check if object already exists in the container. */
    obj = ao2_find(container, &number, OBJ_KEY);
    if (obj) {
       ast_test_status_update(test, "%s: Object %d already exists.\n", prefix, number);
       ao2_t_ref(obj, -1, "test");
       return -1;
    }
    /* Add three duplicate keyed objects. */
    obj_dup = NULL;
    for (count = 0; count < 4; ++count) {
       obj = ao2_alloc(sizeof(struct test_obj), test_obj_destructor);
       if (!obj) {
          ast_test_status_update(test, "%s: ao2_alloc failed.\n", prefix);
          if (obj_dup) {
             ao2_t_ref(obj_dup, -1, "test");
          }
          return -1;
       }
       if (destroy_counter) {
          /* This object ultimately needs to be destroyed. */
          ++*destroy_counter;
       }
       obj->destructor_count = destroy_counter;
       obj->i = number;
       obj->dup_number = count;
       ao2_link(container, obj);
       if (count == 2) {
          /* Duplicate this object. */
          obj_dup = obj;
       } else {
          ao2_t_ref(obj, -1, "test");
       }
       if (ao2_container_check(container, 0)) {
          ast_test_status_update(test, "%s: Container integrity check failed linking num:%d dup:%d\n",
             prefix, number, count);
          if (obj_dup) {
             ao2_t_ref(obj_dup, -1, "test");
          }
          return -1;
       }
    }
    /* Add the duplicate object. */
    ao2_link(container, obj_dup);
    ao2_t_ref(obj_dup, -1, "test");
    if (ao2_container_check(container, 0)) {
       ast_test_status_update(test, "%s: Container integrity check failed linking obj_dup\n",
          prefix);
       return -1;
    }
    return 0;
 }
insert_test_vector()
static int insert_test_vector (struct ao2_container * container, int * destroy_counter, const int * vector, int count, const char * prefix, struct ast_test * test) static
Definition at line 1040 of file test_astobj2.c.
References ao2_alloc, ao2_container_check(), ao2_container_count(), ao2_link, ao2_t_ref, ast_test_status_update, test_obj::destructor_count, test_obj::i, and test_obj_destructor().
Referenced by test_traversal_nonsorted(), and test_traversal_sorted().
 {
    int idx;
    struct test_obj *obj;
    for (idx = 0; idx < count; ++idx) {
       obj = ao2_alloc(sizeof(struct test_obj), test_obj_destructor);
       if (!obj) {
          ast_test_status_update(test, "%s: ao2_alloc failed.\n", prefix);
          return -1;
       }
       if (destroy_counter) {
          /* This object ultimately needs to be destroyed. */
          ++*destroy_counter;
       }
       obj->destructor_count = destroy_counter;
       obj->i = vector[idx];
       ao2_link(container, obj);
       ao2_t_ref(obj, -1, "test");
       if (ao2_container_check(container, 0)) {
          ast_test_status_update(test, "%s: Container integrity check failed linking vector[%d]:%d\n",
             prefix, idx, vector[idx]);
          return -1;
       }
       if (ao2_container_count(container) != idx + 1) {
          ast_test_status_update(test,
             "%s: Unexpected container count.  Expected:%d Got:%d\n",
             prefix, idx + 1, ao2_container_count(container));
          return -1;
       }
    }
    return 0;
 }
load_module()
static int load_module (void) static
Definition at line 2064 of file test_astobj2.c.
References AST_MODULE_LOAD_SUCCESS, and AST_TEST_REGISTER.
 {
    AST_TEST_REGISTER(astobj2_test_1);
    AST_TEST_REGISTER(astobj2_test_2);
    AST_TEST_REGISTER(astobj2_test_3);
    AST_TEST_REGISTER(astobj2_test_4);
    AST_TEST_REGISTER(astobj2_test_perf);
    return AST_MODULE_LOAD_SUCCESS;
 }
multiple_cb()
static int multiple_cb (void * obj, void * arg, int flag) static
Definition at line 111 of file test_astobj2.c.
References CMP_MATCH, and test_obj::i.
Referenced by astobj2_test_1_helper().
 {
    int *i = (int *) arg;
    struct test_obj *cmp_obj = (struct test_obj *) obj;
    return (cmp_obj->i < *i) ? CMP_MATCH : 0;
 }
test_ao2_callback_traversal()
static int test_ao2_callback_traversal (int res, struct ao2_container * container, enum search_flags flags, ao2_callback_fn * cmp_fn, void * arg, const int * vector, int count, const char * prefix, struct ast_test * test) static
Definition at line 1232 of file test_astobj2.c.
References ao2_callback, ao2_iterator_destroy(), ao2_iterator_next, ao2_ref, AST_TEST_FAIL, ast_test_status_update, test_obj::i, and OBJ_MULTIPLE.
Referenced by test_traversal_nonsorted(), and test_traversal_sorted().
 {
    struct ao2_iterator *mult_iter;
    struct test_obj *obj;
    int idx;
    mult_iter = ao2_callback(container, flags | OBJ_MULTIPLE, cmp_fn, arg);
    if (!mult_iter) {
       ast_test_status_update(test, "%s: Did not return iterator.\n", prefix);
       return AST_TEST_FAIL;
    }
    /* Check matching objects against the given vector. */
    for (idx = 0; idx < count; ++idx) {
       obj = ao2_iterator_next(mult_iter);
       if (!obj) {
          ast_test_status_update(test, "%s: Too few objects found.\n", prefix);
          res = AST_TEST_FAIL;
          break;
       }
       if (vector[idx] != obj->i) {
          ast_test_status_update(test, "%s: Object %d != vector[%d] %d.\n",
             prefix, obj->i, idx, vector[idx]);
          res = AST_TEST_FAIL;
       }
       ao2_ref(obj, -1); /* remove ref from iterator */
    }
    obj = ao2_iterator_next(mult_iter);
    if (obj) {
       ast_test_status_update(test, "%s: Too many objects found.  Object %d\n",
          prefix, obj->i);
       ao2_ref(obj, -1); /* remove ref from iterator */
       res = AST_TEST_FAIL;
    }
    ao2_iterator_destroy(mult_iter);
    return res;
 }
test_ao2_find_w_no_flags()
static int test_ao2_find_w_no_flags (int res, struct ao2_container * look_in, int limit, struct ast_test * test) static
Definition at line 278 of file test_astobj2.c.
References ao2_find, ao2_t_ref, ast_random(), AST_TEST_FAIL, ast_test_status_update, and test_obj::i.
Referenced by astobj2_test_1_helper().
 {
    int i;
    int num;
    struct test_obj tmp_obj = { 0, };
    struct test_obj *obj;
    for (num = 100; num--;) {
       i = ast_random() % limit; /* find a random object */
       tmp_obj.i = i;
       obj = ao2_find(look_in, &tmp_obj, 0);
       if (!obj) {
          ast_test_status_update(test, "COULD NOT FIND:%d, ao2_find() with no flags failed.\n", i);
          res = AST_TEST_FAIL;
       } else {
          if (obj->i != i) {
             ast_test_status_update(test, "object %d does not match %d\n", obj->i, i);
             res = AST_TEST_FAIL;
          }
          ao2_t_ref(obj, -1, "test");
       }
    }
    return res;
 }
test_ao2_find_w_OBJ_KEY()
static int test_ao2_find_w_OBJ_KEY (int res, struct ao2_container * look_in, int limit, struct ast_test * test) static
Definition at line 356 of file test_astobj2.c.
References ao2_find, ao2_t_ref, ast_random(), AST_TEST_FAIL, ast_test_status_update, test_obj::i, and OBJ_KEY.
Referenced by astobj2_test_1_helper().
 {
    int i;
    int num;
    struct test_obj *obj;
    for (num = 75; num--;) {
       i = ast_random() % limit; /* find a random object */
       obj = ao2_find(look_in, &i, OBJ_KEY);
       if (!obj) {
          ast_test_status_update(test, "COULD NOT FIND:%d, ao2_find() with OBJ_KEY flag failed.\n", i);
          res = AST_TEST_FAIL;
       } else {
          if (obj->i != i) {
             ast_test_status_update(test, "object %d does not match %d\n", obj->i, i);
             res = AST_TEST_FAIL;
          }
          ao2_t_ref(obj, -1, "test");
       }
    }
    return res;
 }
test_ao2_find_w_OBJ_PARTIAL_KEY()
static int test_ao2_find_w_OBJ_PARTIAL_KEY (int res, struct ao2_container * look_in, int limit, struct ast_test * test) static
Definition at line 393 of file test_astobj2.c.
References ao2_find, ao2_t_ref, ast_random(), AST_TEST_FAIL, ast_test_status_update, test_obj::i, OBJ_PARTIAL_KEY, and partial_key_match_range.
Referenced by astobj2_test_1_helper().
 {
    int i;
    int num;
    struct test_obj *obj;
    /* Set partial match to find exactly. */
    partial_key_match_range = 0;
    for (num = 100; num--;) {
       i = ast_random() % limit; /* find a random object */
       obj = ao2_find(look_in, &i, OBJ_PARTIAL_KEY);
       if (!obj) {
          ast_test_status_update(test, "COULD NOT FIND:%d, ao2_find() with OBJ_PARTIAL_KEY flag failed.\n", i);
          res = AST_TEST_FAIL;
       } else {
          if (obj->i != i) {
             ast_test_status_update(test, "object %d does not match %d\n", obj->i, i);
             res = AST_TEST_FAIL;
          }
          ao2_t_ref(obj, -1, "test");
       }
    }
    return res;
 }
test_ao2_find_w_OBJ_POINTER()
static int test_ao2_find_w_OBJ_POINTER (int res, struct ao2_container * look_in, int limit, struct ast_test * test) static
Definition at line 317 of file test_astobj2.c.
References ao2_find, ao2_t_ref, ast_random(), AST_TEST_FAIL, ast_test_status_update, test_obj::i, and OBJ_POINTER.
Referenced by astobj2_test_1_helper().
 {
    int i;
    int num;
    struct test_obj tmp_obj = { 0, };
    struct test_obj *obj;
    for (num = 75; num--;) {
       i = ast_random() % limit; /* find a random object */
       tmp_obj.i = i;
       obj = ao2_find(look_in, &tmp_obj, OBJ_POINTER);
       if (!obj) {
          ast_test_status_update(test, "COULD NOT FIND:%d, ao2_find() with OBJ_POINTER flag failed.\n", i);
          res = AST_TEST_FAIL;
       } else {
          if (obj->i != i) {
             ast_test_status_update(test, "object %d does not match %d\n", obj->i, i);
             res = AST_TEST_FAIL;
          }
          ao2_t_ref(obj, -1, "test");
       }
    }
    return res;
 }
test_ao2_iteration()
static int test_ao2_iteration (int res, struct ao2_container * container, enum ao2_iterator_flags flags, const int * vector, int count, const char * prefix, struct ast_test * test) static
Definition at line 1171 of file test_astobj2.c.
References ao2_container_count(), ao2_iterator_destroy(), ao2_iterator_init(), ao2_iterator_next, ao2_ref, AST_TEST_FAIL, ast_test_status_update, and test_obj::i.
Referenced by test_traversal_nonsorted(), and test_traversal_sorted().
 {
    struct ao2_iterator iter;
    struct test_obj *obj;
    int idx;
    if (ao2_container_count(container) != count) {
       ast_test_status_update(test, "%s: Container count doesn't match vector count.\n",
          prefix);
       res = AST_TEST_FAIL;
    }
    iter = ao2_iterator_init(container, flags);
    /* Check iterated objects against the given vector. */
    for (idx = 0; idx < count; ++idx) {
       obj = ao2_iterator_next(&iter);
       if (!obj) {
          ast_test_status_update(test, "%s: Too few objects found.\n", prefix);
          res = AST_TEST_FAIL;
          break;
       }
       if (vector[idx] != obj->i) {
          ast_test_status_update(test, "%s: Object %d != vector[%d] %d.\n",
             prefix, obj->i, idx, vector[idx]);
          res = AST_TEST_FAIL;
       }
       ao2_ref(obj, -1); /* remove ref from iterator */
    }
    obj = ao2_iterator_next(&iter);
    if (obj) {
       ast_test_status_update(test, "%s: Too many objects found.  Object %d\n",
          prefix, obj->i);
       ao2_ref(obj, -1); /* remove ref from iterator */
       res = AST_TEST_FAIL;
    }
    ao2_iterator_destroy(&iter);
    return res;
 }
test_cmp_cb()
static int test_cmp_cb (void * obj, void * arg, int flags) static
Definition at line 119 of file test_astobj2.c.
References CMP_MATCH, test_obj::i, OBJ_KEY, OBJ_PARTIAL_KEY, and partial_key_match_range.
Referenced by AST_TEST_DEFINE(), astobj2_test_1_helper(), test_make_nonsorted(), test_make_sorted(), test_performance(), test_traversal_nonsorted(), and test_traversal_sorted().
 {
    struct test_obj *cmp_obj = (struct test_obj *) obj;
    if (flags & OBJ_KEY) {
       int *i = (int *) arg;
       return (cmp_obj->i == *i) ? CMP_MATCH : 0;
    } else if (flags & OBJ_PARTIAL_KEY) {
       int *i = (int *) arg;
       return (*i - partial_key_match_range <= cmp_obj->i
          && cmp_obj->i <= *i + partial_key_match_range) ? CMP_MATCH : 0;
    } else {
       struct test_obj *arg_obj = (struct test_obj *) arg;
       return (cmp_obj->i == arg_obj->i) ? CMP_MATCH : 0;
    }
 }
test_container2str()
static const char* test_container2str (enum test_container_type type) static
Definition at line 56 of file test_astobj2.c.
References TEST_CONTAINER_HASH, TEST_CONTAINER_LIST, and TEST_CONTAINER_RBTREE.
Referenced by astobj2_test_1_helper(), test_traversal_nonsorted(), test_traversal_sorted(), and testloop().
 {
    const char *c_type;
    c_type = "Unknown";
    switch (type) {
    case TEST_CONTAINER_LIST:
       c_type = "List";
       break;
    case TEST_CONTAINER_HASH:
       c_type = "Hash";
       break;
    case TEST_CONTAINER_RBTREE:
       c_type = "RBTree";
       break;
    }
    return c_type;
 }
test_container_clone()
static int test_container_clone (int res, struct ao2_container * orig, struct ast_test * test) static
Definition at line 216 of file test_astobj2.c.
References ao2_container_check(), ao2_container_clone, ao2_container_count(), ao2_iterator_destroy(), ao2_iterator_init(), ao2_match_by_addr(), ao2_t_callback, ao2_t_iterator_next, ao2_t_ref, AST_TEST_FAIL, ast_test_status_update, OBJ_POINTER, and OBJ_UNLINK.
Referenced by astobj2_test_1_helper().
 {
    struct ao2_container *clone;
    struct test_obj *obj;
    struct test_obj *obj2;
    struct ao2_iterator iter;
    clone = ao2_container_clone(orig, 0);
    if (!clone) {
       ast_test_status_update(test, "ao2_container_clone failed.\n");
       return AST_TEST_FAIL;
    }
    if (ao2_container_check(clone, 0)) {
       ast_test_status_update(test, "container integrity check failed\n");
       res = AST_TEST_FAIL;
    } else if (ao2_container_count(orig) != ao2_container_count(clone)) {
       ast_test_status_update(test, "Cloned container does not have the same number of objects.\n");
       res = AST_TEST_FAIL;
    } else {
       iter = ao2_iterator_init(orig, 0);
       for (; (obj = ao2_t_iterator_next(&iter, "test orig")); ao2_t_ref(obj, -1, "test orig")) {
          /*
           * Unlink the matching object from the cloned container to make
           * the next search faster.  This is a big speed optimization!
           */
          obj2 = ao2_t_callback(clone, OBJ_POINTER | OBJ_UNLINK, ao2_match_by_addr, obj,
             "test clone");
          if (obj2) {
             ao2_t_ref(obj2, -1, "test clone");
             continue;
          }
          ast_test_status_update(test,
             "Orig container has an object %p not in the clone container.\n", obj);
          res = AST_TEST_FAIL;
       }
       ao2_iterator_destroy(&iter);
       if (ao2_container_count(clone)) {
          ast_test_status_update(test, "Cloned container still has objects.\n");
          res = AST_TEST_FAIL;
       }
       if (ao2_container_check(clone, 0)) {
          ast_test_status_update(test, "container integrity check failed\n");
          res = AST_TEST_FAIL;
       }
    }
    ao2_t_ref(clone, -1, "bye clone");
    return res;
 }
test_expected_duplicates()
static int test_expected_duplicates (int res, struct ao2_container * container, enum search_flags flags, int number, const int * vector, int count, const char * prefix, struct ast_test * test) static
Definition at line 1289 of file test_astobj2.c.
References ao2_find, ao2_iterator_destroy(), ao2_iterator_next, ao2_ref, AST_TEST_FAIL, ast_test_status_update, test_obj::dup_number, test_obj::i, OBJ_KEY, and OBJ_MULTIPLE.
Referenced by test_traversal_sorted().
 {
    struct ao2_iterator *mult_iter;
    struct test_obj *obj;
    int idx;
    mult_iter = ao2_find(container, &number, flags | OBJ_MULTIPLE | OBJ_KEY);
    if (!mult_iter) {
       ast_test_status_update(test, "%s: Did not return iterator.\n", prefix);
       return AST_TEST_FAIL;
    }
    /* Check matching objects against the given vector. */
    for (idx = 0; idx < count; ++idx) {
       obj = ao2_iterator_next(mult_iter);
       if (!obj) {
          ast_test_status_update(test, "%s: Too few objects found.\n", prefix);
          res = AST_TEST_FAIL;
          break;
       }
       if (number != obj->i) {
          ast_test_status_update(test, "%s: Object %d != %d.\n",
             prefix, obj->i, number);
          res = AST_TEST_FAIL;
       }
       if (vector[idx] != obj->dup_number) {
          ast_test_status_update(test, "%s: Object dup id %d != vector[%d] %d.\n",
             prefix, obj->dup_number, idx, vector[idx]);
          res = AST_TEST_FAIL;
       }
       ao2_ref(obj, -1); /* remove ref from iterator */
    }
    obj = ao2_iterator_next(mult_iter);
    if (obj) {
       ast_test_status_update(test,
          "%s: Too many objects found.  Object %d, dup id %d\n",
          prefix, obj->i, obj->dup_number);
       ao2_ref(obj, -1); /* remove ref from iterator */
       res = AST_TEST_FAIL;
    }
    ao2_iterator_destroy(mult_iter);
    return res;
 }
test_hash_cb()
static int test_hash_cb (const void * obj, const int flags) static
Definition at line 139 of file test_astobj2.c.
References test_obj::i, OBJ_KEY, and OBJ_PARTIAL_KEY.
Referenced by astobj2_test_1_helper(), test_make_nonsorted(), test_make_sorted(), and test_performance().
 {
    if (flags & OBJ_KEY) {
       const int *i = obj;
       return *i;
    } else if (flags & OBJ_PARTIAL_KEY) {
       /* This is absolutely wrong to be called with this flag value. */
       abort();
       /* Just in case abort() doesn't work or something else super silly */
       *((int *) 0) = 0;
       return 0;
    } else {
       const struct test_obj *hash_obj = obj;
       return hash_obj->i;
    }
 }
test_make_nonsorted()
static struct ao2_container* test_make_nonsorted (enum test_container_type type, int options) static
Definition at line 967 of file test_astobj2.c.
References AO2_ALLOC_OPT_LOCK_MUTEX, ao2_container_alloc_hash, ao2_container_alloc_list, container, NULL, test_cmp_cb(), TEST_CONTAINER_HASH, TEST_CONTAINER_LIST, TEST_CONTAINER_RBTREE, and test_hash_cb().
Referenced by test_traversal_nonsorted().
 {
    struct ao2_container *container;
    container = NULL;
    switch (type) {
    case TEST_CONTAINER_LIST:
       container = ao2_container_alloc_list(AO2_ALLOC_OPT_LOCK_MUTEX, options,
          NULL, test_cmp_cb);
       break;
    case TEST_CONTAINER_HASH:
       container = ao2_container_alloc_hash(AO2_ALLOC_OPT_LOCK_MUTEX, options, 5,
          test_hash_cb, NULL, test_cmp_cb);
       break;
    case TEST_CONTAINER_RBTREE:
       /* Container type must be sorted. */
       break;
    }
    return container;
 }
test_make_sorted()
static struct ao2_container* test_make_sorted (enum test_container_type type, int options) static
Definition at line 1000 of file test_astobj2.c.
References AO2_ALLOC_OPT_LOCK_MUTEX, ao2_t_container_alloc_hash, ao2_t_container_alloc_list, ao2_t_container_alloc_rbtree, container, NULL, test_cmp_cb(), TEST_CONTAINER_HASH, TEST_CONTAINER_LIST, TEST_CONTAINER_RBTREE, test_hash_cb(), and test_sort_cb().
Referenced by test_traversal_sorted().
 {
    struct ao2_container *container;
    container = NULL;
    switch (type) {
    case TEST_CONTAINER_LIST:
       container = ao2_t_container_alloc_list(AO2_ALLOC_OPT_LOCK_MUTEX, options,
          test_sort_cb, test_cmp_cb, "test");
       break;
    case TEST_CONTAINER_HASH:
       container = ao2_t_container_alloc_hash(AO2_ALLOC_OPT_LOCK_MUTEX, options, 5,
          test_hash_cb, test_sort_cb, test_cmp_cb, "test");
       break;
    case TEST_CONTAINER_RBTREE:
       container = ao2_t_container_alloc_rbtree(AO2_ALLOC_OPT_LOCK_MUTEX, options,
          test_sort_cb, test_cmp_cb, "test");
       break;
    }
    return container;
 }
test_obj_destructor()
static void test_obj_destructor (void * v_obj) static
Definition at line 87 of file test_astobj2.c.
References test_obj::destructor_count.
Referenced by AST_TEST_DEFINE(), astobj2_test_1_helper(), insert_test_duplicates(), insert_test_vector(), and test_performance().
 {
    struct test_obj *obj = (struct test_obj *) v_obj;
    if (obj->destructor_count) {
       --*obj->destructor_count;
    }
 }
test_performance()
static enum ast_test_result_state test_performance (struct ast_test * test, enum test_container_type type, unsigned int copt) static
The number of objects inserted and searched for in the container under test.
Definition at line 1925 of file test_astobj2.c.
References ao2_alloc, AO2_ALLOC_OPT_LOCK_MUTEX, ao2_cleanup, ao2_container_alloc_hash, ao2_container_alloc_list, ao2_container_alloc_rbtree, ao2_find, ao2_link, ao2_ref, AST_TEST_FAIL, AST_TEST_PASS, ast_test_status_update, test_obj::i, NULL, OBJ_KEY, OBJS, test_cleanup(), test_cmp_cb(), TEST_CONTAINER_HASH, TEST_CONTAINER_LIST, TEST_CONTAINER_RBTREE, test_hash_cb(), test_obj_destructor(), and test_sort_cb().
Referenced by testloop().
 {
 /*!
  * \brief The number of objects inserted and searched for in the container under test.
  */
 #define OBJS 73
    int res = AST_TEST_PASS;
    struct ao2_container *c1 = NULL;
    struct test_obj *tobj[OBJS];
    struct test_obj *tobj2;
    int i;
    switch (type) {
    case TEST_CONTAINER_HASH:
       c1 = ao2_container_alloc_hash(AO2_ALLOC_OPT_LOCK_MUTEX, copt, 17,
          test_hash_cb, test_sort_cb, test_cmp_cb);
       break;
    case TEST_CONTAINER_LIST:
       c1 = ao2_container_alloc_list(AO2_ALLOC_OPT_LOCK_MUTEX, copt,
          test_sort_cb, test_cmp_cb);
       break;
    case TEST_CONTAINER_RBTREE:
       c1 = ao2_container_alloc_rbtree(AO2_ALLOC_OPT_LOCK_MUTEX, copt,
          test_sort_cb, test_cmp_cb);
       break;
    }
    for (i = 0; i < OBJS; i++) {
       tobj[i] = NULL;
    }
    if (!c1) {
       ast_test_status_update(test, "Container c1 creation failed.\n");
       res = AST_TEST_FAIL;
       goto test_cleanup;
    }
    for (i = 0; i < OBJS; i++) {
       tobj[i] = ao2_alloc(sizeof(struct test_obj), test_obj_destructor);
       if (!tobj[i]) {
          ast_test_status_update(test, "test object creation failed.\n");
          res = AST_TEST_FAIL;
          goto test_cleanup;
       }
       tobj[i]->i = i;
       ao2_link(c1, tobj[i]);
    }
    for (i = 0; i < OBJS; i++) {
       if ((!(tobj2 = ao2_find(c1, &i, OBJ_KEY)))) {
          ast_test_status_update(test, "Should have found object %d in container.\n", i);
          res = AST_TEST_FAIL;
          goto test_cleanup;
       }
       ao2_ref(tobj2, -1);
       tobj2 = NULL;
    }
 test_cleanup:
    for (i = 0; i < OBJS ; i++) {
       ao2_cleanup(tobj[i]);
    }
    ao2_cleanup(c1);
    return res;
 }
test_sort_cb()
static int test_sort_cb (const void * obj_left, const void * obj_right, int flags) static
Definition at line 158 of file test_astobj2.c.
References test_obj::dup_number, test_obj::i, OBJ_KEY, OBJ_PARTIAL_KEY, and partial_key_match_range.
Referenced by astobj2_test_1_helper(), test_make_sorted(), and test_performance().
 {
    const struct test_obj *test_left = obj_left;
    if (flags & OBJ_KEY) {
       const int *i = obj_right;
       return test_left->i - *i;
    } else if (flags & OBJ_PARTIAL_KEY) {
       int *i = (int *) obj_right;
       if (*i - partial_key_match_range <= test_left->i
          && test_left->i <= *i + partial_key_match_range) {
          return 0;
       }
       return test_left->i - *i;
    } else {
       const struct test_obj *test_right = obj_right;
       return test_left->i - test_right->i;
    }
 }
test_traversal_nonsorted()
static int test_traversal_nonsorted (int res, int tst_num, enum test_container_type type, struct ast_test * test) static
Container object insertion vector.
Container object insertion vector reversed.
Definition at line 1348 of file test_astobj2.c.
References AO2_CONTAINER_ALLOC_OPT_INSERT_BEGIN, AO2_ITERATOR_DESCENDING, ao2_t_ref, ARRAY_LEN, AST_TEST_FAIL, ast_test_status_update, test_obj::destructor_count, insert_test_vector(), NULL, OBJ_ORDER_ASCENDING, OBJ_ORDER_DESCENDING, OBJ_PARTIAL_KEY, partial_key_match_range, test_ao2_callback_traversal(), test_ao2_iteration(), test_cleanup(), test_cmp_cb(), test_container2str(), TEST_CONTAINER_HASH, TEST_CONTAINER_LIST, TEST_CONTAINER_RBTREE, and test_make_nonsorted().
Referenced by AST_TEST_DEFINE().
 {
    struct ao2_container *c1;
    struct ao2_container *c2 = NULL;
    int partial;
    int destructor_count = 0;
    /*! Container object insertion vector. */
    static const int test_initial[] = {
       1, 0, 2, 6, 4, 7, 5, 3, 9, 8
    };
    /*! Container object insertion vector reversed. */
    static const int test_reverse[] = {
       8, 9, 3, 5, 7, 4, 6, 2, 0, 1
    };
    static const int test_list_partial_forward[] = {
       6, 7, 5
    };
    static const int test_list_partial_backward[] = {
       5, 7, 6
    };
    /* The hash orders assume that there are 5 buckets. */
    static const int test_hash_end_forward[] = {
       0, 5, 1, 6, 2, 7, 3, 8, 4, 9
    };
    static const int test_hash_end_backward[] = {
       9, 4, 8, 3, 7, 2, 6, 1, 5, 0
    };
    static const int test_hash_begin_forward[] = {
       5, 0, 6, 1, 7, 2, 8, 3, 9, 4
    };
    static const int test_hash_begin_backward[] = {
       4, 9, 3, 8, 2, 7, 1, 6, 0, 5
    };
    static const int test_hash_partial_forward[] = {
       5, 6, 7
    };
    static const int test_hash_partial_backward[] = {
       7, 6, 5
    };
    ast_test_status_update(test, "Test %d, %s containers.\n",
       tst_num, test_container2str(type));
    /* Create container that inserts objects at the end. */
    c1 = test_make_nonsorted(type, 0);
    if (!c1) {
       ast_test_status_update(test, "Container c1 creation failed.\n");
       res = AST_TEST_FAIL;
       goto test_cleanup;
    }
    if (insert_test_vector(c1, &destructor_count, test_initial, ARRAY_LEN(test_initial), "c1", test)) {
       res = AST_TEST_FAIL;
       goto test_cleanup;
    }
    /* Create container that inserts objects at the beginning. */
    c2 = test_make_nonsorted(type, AO2_CONTAINER_ALLOC_OPT_INSERT_BEGIN);
    if (!c2) {
       ast_test_status_update(test, "Container c2 creation failed.\n");
       res = AST_TEST_FAIL;
       goto test_cleanup;
    }
    if (insert_test_vector(c2, &destructor_count, test_initial, ARRAY_LEN(test_initial), "c2", test)) {
       res = AST_TEST_FAIL;
       goto test_cleanup;
    }
    /* Check container iteration directions */
    switch (type) {
    case TEST_CONTAINER_LIST:
       res = test_ao2_iteration(res, c1, 0,
          test_initial, ARRAY_LEN(test_initial),
          "Iteration (ascending, insert end)", test);
       res = test_ao2_iteration(res, c1, AO2_ITERATOR_DESCENDING,
          test_reverse, ARRAY_LEN(test_reverse),
          "Iteration (descending, insert end)", test);
       res = test_ao2_iteration(res, c2, 0,
          test_reverse, ARRAY_LEN(test_reverse),
          "Iteration (ascending, insert begin)", test);
       res = test_ao2_iteration(res, c2, AO2_ITERATOR_DESCENDING,
          test_initial, ARRAY_LEN(test_initial),
          "Iteration (descending, insert begin)", test);
       break;
    case TEST_CONTAINER_HASH:
       res = test_ao2_iteration(res, c1, 0,
          test_hash_end_forward, ARRAY_LEN(test_hash_end_forward),
          "Iteration (ascending, insert end)", test);
       res = test_ao2_iteration(res, c1, AO2_ITERATOR_DESCENDING,
          test_hash_end_backward, ARRAY_LEN(test_hash_end_backward),
          "Iteration (descending, insert end)", test);
       res = test_ao2_iteration(res, c2, 0,
          test_hash_begin_forward, ARRAY_LEN(test_hash_begin_forward),
          "Iteration (ascending, insert begin)", test);
       res = test_ao2_iteration(res, c2, AO2_ITERATOR_DESCENDING,
          test_hash_begin_backward, ARRAY_LEN(test_hash_begin_backward),
          "Iteration (descending, insert begin)", test);
       break;
    case TEST_CONTAINER_RBTREE:
       break;
    }
    /* Check container traversal directions */
    switch (type) {
    case TEST_CONTAINER_LIST:
       res = test_ao2_callback_traversal(res, c1, OBJ_ORDER_ASCENDING, NULL, NULL,
          test_initial, ARRAY_LEN(test_initial),
          "Traversal (ascending, insert end)", test);
       res = test_ao2_callback_traversal(res, c1, OBJ_ORDER_DESCENDING, NULL, NULL,
          test_reverse, ARRAY_LEN(test_reverse),
          "Traversal (descending, insert end)", test);
       res = test_ao2_callback_traversal(res, c2, OBJ_ORDER_ASCENDING, NULL, NULL,
          test_reverse, ARRAY_LEN(test_reverse),
          "Traversal (ascending, insert begin)", test);
       res = test_ao2_callback_traversal(res, c2, OBJ_ORDER_DESCENDING, NULL, NULL,
          test_initial, ARRAY_LEN(test_initial),
          "Traversal (descending, insert begin)", test);
       break;
    case TEST_CONTAINER_HASH:
       res = test_ao2_callback_traversal(res, c1, OBJ_ORDER_ASCENDING, NULL, NULL,
          test_hash_end_forward, ARRAY_LEN(test_hash_end_forward),
          "Traversal (ascending, insert end)", test);
       res = test_ao2_callback_traversal(res, c1, OBJ_ORDER_DESCENDING, NULL, NULL,
          test_hash_end_backward, ARRAY_LEN(test_hash_end_backward),
          "Traversal (descending, insert end)", test);
       res = test_ao2_callback_traversal(res, c2, OBJ_ORDER_ASCENDING, NULL, NULL,
          test_hash_begin_forward, ARRAY_LEN(test_hash_begin_forward),
          "Traversal (ascending, insert begin)", test);
       res = test_ao2_callback_traversal(res, c2, OBJ_ORDER_DESCENDING, NULL, NULL,
          test_hash_begin_backward, ARRAY_LEN(test_hash_begin_backward),
          "Traversal (descending, insert begin)", test);
       break;
    case TEST_CONTAINER_RBTREE:
       break;
    }
    /* Check traversal with OBJ_PARTIAL_KEY search range. */
    partial = 6;
    partial_key_match_range = 1;
    switch (type) {
    case TEST_CONTAINER_LIST:
       res = test_ao2_callback_traversal(res, c1, OBJ_PARTIAL_KEY | OBJ_ORDER_ASCENDING,
          test_cmp_cb, &partial,
          test_list_partial_forward, ARRAY_LEN(test_list_partial_forward),
          "Traversal OBJ_PARTIAL_KEY (ascending)", test);
       res = test_ao2_callback_traversal(res, c1, OBJ_PARTIAL_KEY | OBJ_ORDER_DESCENDING,
          test_cmp_cb, &partial,
          test_list_partial_backward, ARRAY_LEN(test_list_partial_backward),
          "Traversal OBJ_PARTIAL_KEY (descending)", test);
       break;
    case TEST_CONTAINER_HASH:
       res = test_ao2_callback_traversal(res, c1, OBJ_PARTIAL_KEY | OBJ_ORDER_ASCENDING,
          test_cmp_cb, &partial,
          test_hash_partial_forward, ARRAY_LEN(test_hash_partial_forward),
          "Traversal OBJ_PARTIAL_KEY (ascending)", test);
       res = test_ao2_callback_traversal(res, c1, OBJ_PARTIAL_KEY | OBJ_ORDER_DESCENDING,
          test_cmp_cb, &partial,
          test_hash_partial_backward, ARRAY_LEN(test_hash_partial_backward),
          "Traversal OBJ_PARTIAL_KEY (descending)", test);
       break;
    case TEST_CONTAINER_RBTREE:
       break;
    }
 test_cleanup:
    /* destroy containers */
    if (c1) {
       ao2_t_ref(c1, -1, "bye c1");
    }
    if (c2) {
       ao2_t_ref(c2, -1, "bye c2");
    }
    if (destructor_count > 0) {
       ast_test_status_update(test,
          "all destructors were not called, destructor count is %d\n",
          destructor_count);
       res = AST_TEST_FAIL;
    } else if (destructor_count < 0) {
       ast_test_status_update(test,
          "Destructor was called too many times, destructor count is %d\n",
          destructor_count);
       res = AST_TEST_FAIL;
    }
    return res;
 }
test_traversal_sorted()
static int test_traversal_sorted (int res, int tst_num, enum test_container_type type, struct ast_test * test) static
Container object insertion vector.
Container forward traversal/iteration.
Container backward traversal/iteration.
Definition at line 1554 of file test_astobj2.c.
References AO2_CONTAINER_ALLOC_OPT_DUPS_ALLOW, AO2_CONTAINER_ALLOC_OPT_DUPS_OBJ_REJECT, AO2_CONTAINER_ALLOC_OPT_DUPS_REJECT, AO2_CONTAINER_ALLOC_OPT_DUPS_REPLACE, AO2_CONTAINER_ALLOC_OPT_INSERT_BEGIN, ao2_container_dump(), ao2_container_stats(), AO2_ITERATOR_DESCENDING, ao2_t_ref, ARRAY_LEN, ast_test_debug(), AST_TEST_FAIL, ast_test_status_update, test_obj::destructor_count, insert_test_duplicates(), insert_test_vector(), NULL, OBJ_ORDER_ASCENDING, OBJ_ORDER_DESCENDING, OBJ_PARTIAL_KEY, partial_key_match_range, test_ao2_callback_traversal(), test_ao2_iteration(), test_cleanup(), test_cmp_cb(), test_container2str(), TEST_CONTAINER_HASH, TEST_CONTAINER_LIST, TEST_CONTAINER_RBTREE, test_expected_duplicates(), and test_make_sorted().
Referenced by AST_TEST_DEFINE().
 {
    struct ao2_container *c1;
    struct ao2_container *c2 = NULL;
    int partial;
    int destructor_count = 0;
    int duplicate_number = 100;
    /*! Container object insertion vector. */
    static const int test_initial[] = {
       1, 0, 2, 6, 4, 7, 5, 3, 9, 8
    };
    /*! Container forward traversal/iteration. */
    static const int test_forward[] = {
       0, 1, 2, 3, 4, 5, 6, 7, 8, 9
    };
    /*! Container backward traversal/iteration. */
    static const int test_backward[] = {
       9, 8, 7, 6, 5, 4, 3, 2, 1, 0
    };
    static const int test_partial_forward[] = {
       5, 6, 7
    };
    static const int test_partial_backward[] = {
       7, 6, 5
    };
    /* The hash orders assume that there are 5 buckets. */
    static const int test_hash_forward[] = {
       0, 5, 1, 6, 2, 7, 3, 8, 4, 9
    };
    static const int test_hash_backward[] = {
       9, 4, 8, 3, 7, 2, 6, 1, 5, 0
    };
    static const int test_hash_partial_forward[] = {
       5, 6, 7
    };
    static const int test_hash_partial_backward[] = {
       7, 6, 5
    };
    /* Duplicate identifier order */
    static const int test_dup_allow_forward[] = {
       0, 1, 2, 3, 2
    };
    static const int test_dup_allow_backward[] = {
       2, 3, 2, 1, 0
    };
    static const int test_dup_reject[] = {
       0
    };
    static const int test_dup_obj_reject_forward[] = {
       0, 1, 2, 3
    };
    static const int test_dup_obj_reject_backward[] = {
       3, 2, 1, 0
    };
    static const int test_dup_replace[] = {
       2
    };
    ast_test_status_update(test, "Test %d, %s containers.\n",
       tst_num, test_container2str(type));
    /* Create container that inserts duplicate objects after matching objects. */
    c1 = test_make_sorted(type, AO2_CONTAINER_ALLOC_OPT_DUPS_ALLOW);
    if (!c1) {
       ast_test_status_update(test, "Container c1 creation failed.\n");
       res = AST_TEST_FAIL;
       goto test_cleanup;
    }
    if (insert_test_vector(c1, &destructor_count, test_initial, ARRAY_LEN(test_initial), "c1(DUPS_ALLOW)", test)) {
       res = AST_TEST_FAIL;
       goto test_cleanup;
    }
    /* Create container that inserts duplicate objects before matching objects. */
    c2 = test_make_sorted(type, AO2_CONTAINER_ALLOC_OPT_INSERT_BEGIN | AO2_CONTAINER_ALLOC_OPT_DUPS_ALLOW);
    if (!c2) {
       ast_test_status_update(test, "Container c2 creation failed.\n");
       res = AST_TEST_FAIL;
       goto test_cleanup;
    }
    if (insert_test_vector(c2, &destructor_count, test_initial, ARRAY_LEN(test_initial), "c2(DUPS_ALLOW)", test)) {
       res = AST_TEST_FAIL;
       goto test_cleanup;
    }
 #if defined(TEST_CONTAINER_DEBUG_DUMP)
    ao2_container_dump(c1, 0, "c1(DUPS_ALLOW)", (void *) test, (ao2_prnt_fn *) ast_test_debug, test_prnt_obj);
    ao2_container_stats(c1, 0, "c1(DUPS_ALLOW)", (void *) test, (ao2_prnt_fn *) ast_test_debug);
    ao2_container_dump(c2, 0, "c2(DUPS_ALLOW)", (void *) test, (ao2_prnt_fn *) ast_test_debug, test_prnt_obj);
    ao2_container_stats(c2, 0, "c2(DUPS_ALLOW)", (void *) test, (ao2_prnt_fn *) ast_test_debug);
 #endif   /* defined(TEST_CONTAINER_DEBUG_DUMP) */
    /* Check container iteration directions */
    switch (type) {
    case TEST_CONTAINER_RBTREE:
    case TEST_CONTAINER_LIST:
       res = test_ao2_iteration(res, c1, 0,
          test_forward, ARRAY_LEN(test_forward),
          "Iteration (ascending)", test);
       res = test_ao2_iteration(res, c1, AO2_ITERATOR_DESCENDING,
          test_backward, ARRAY_LEN(test_backward),
          "Iteration (descending)", test);
       break;
    case TEST_CONTAINER_HASH:
       res = test_ao2_iteration(res, c1, 0,
          test_hash_forward, ARRAY_LEN(test_hash_forward),
          "Iteration (ascending)", test);
       res = test_ao2_iteration(res, c1, AO2_ITERATOR_DESCENDING,
          test_hash_backward, ARRAY_LEN(test_hash_backward),
          "Iteration (descending)", test);
       break;
    }
    /* Check container traversal directions */
    switch (type) {
    case TEST_CONTAINER_RBTREE:
    case TEST_CONTAINER_LIST:
       res = test_ao2_callback_traversal(res, c1, OBJ_ORDER_ASCENDING, NULL, NULL,
          test_forward, ARRAY_LEN(test_forward),
          "Traversal (ascending)", test);
       res = test_ao2_callback_traversal(res, c1, OBJ_ORDER_DESCENDING, NULL, NULL,
          test_backward, ARRAY_LEN(test_backward),
          "Traversal (descending)", test);
       break;
    case TEST_CONTAINER_HASH:
       res = test_ao2_callback_traversal(res, c1, OBJ_ORDER_ASCENDING, NULL, NULL,
          test_hash_forward, ARRAY_LEN(test_hash_forward),
          "Traversal (ascending, insert end)", test);
       res = test_ao2_callback_traversal(res, c1, OBJ_ORDER_DESCENDING, NULL, NULL,
          test_hash_backward, ARRAY_LEN(test_hash_backward),
          "Traversal (descending)", test);
       break;
    }
    /* Check traversal with OBJ_PARTIAL_KEY search range. */
    partial = 6;
    partial_key_match_range = 1;
    switch (type) {
    case TEST_CONTAINER_RBTREE:
    case TEST_CONTAINER_LIST:
       res = test_ao2_callback_traversal(res, c1, OBJ_PARTIAL_KEY | OBJ_ORDER_ASCENDING,
          test_cmp_cb, &partial,
          test_partial_forward, ARRAY_LEN(test_partial_forward),
          "Traversal OBJ_PARTIAL_KEY (ascending)", test);
       res = test_ao2_callback_traversal(res, c1, OBJ_PARTIAL_KEY | OBJ_ORDER_DESCENDING,
          test_cmp_cb, &partial,
          test_partial_backward, ARRAY_LEN(test_partial_backward),
          "Traversal OBJ_PARTIAL_KEY (descending)", test);
       break;
    case TEST_CONTAINER_HASH:
       res = test_ao2_callback_traversal(res, c1, OBJ_PARTIAL_KEY | OBJ_ORDER_ASCENDING,
          test_cmp_cb, &partial,
          test_hash_partial_forward, ARRAY_LEN(test_hash_partial_forward),
          "Traversal OBJ_PARTIAL_KEY (ascending)", test);
       res = test_ao2_callback_traversal(res, c1, OBJ_PARTIAL_KEY | OBJ_ORDER_DESCENDING,
          test_cmp_cb, &partial,
          test_hash_partial_backward, ARRAY_LEN(test_hash_partial_backward),
          "Traversal OBJ_PARTIAL_KEY (descending)", test);
       break;
    }
    /* Add duplicates to initial containers that allow duplicates */
    if (insert_test_duplicates(c1, &destructor_count, duplicate_number, "c1(DUPS_ALLOW)", test)) {
       res = AST_TEST_FAIL;
       goto test_cleanup;
    }
    if (insert_test_duplicates(c2, &destructor_count, duplicate_number, "c2(DUPS_ALLOW)", test)) {
       res = AST_TEST_FAIL;
       goto test_cleanup;
    }
 #if defined(TEST_CONTAINER_DEBUG_DUMP)
    ao2_container_dump(c1, 0, "c1(DUPS_ALLOW) w/ dups", (void *) test, (ao2_prnt_fn *) ast_test_debug, test_prnt_obj);
    ao2_container_stats(c1, 0, "c1(DUPS_ALLOW) w/ dups", (void *) test, (ao2_prnt_fn *) ast_test_debug);
    ao2_container_dump(c2, 0, "c2(DUPS_ALLOW) w/ dups", (void *) test, (ao2_prnt_fn *) ast_test_debug, test_prnt_obj);
    ao2_container_stats(c2, 0, "c2(DUPS_ALLOW) w/ dups", (void *) test, (ao2_prnt_fn *) ast_test_debug);
 #endif   /* defined(TEST_CONTAINER_DEBUG_DUMP) */
    /* Check duplicates in containers that allow duplicates. */
    res = test_expected_duplicates(res, c1, OBJ_ORDER_ASCENDING, duplicate_number,
       test_dup_allow_forward, ARRAY_LEN(test_dup_allow_forward),
       "Duplicates (ascending, DUPS_ALLOW)", test);
    res = test_expected_duplicates(res, c1, OBJ_ORDER_DESCENDING, duplicate_number,
       test_dup_allow_backward, ARRAY_LEN(test_dup_allow_backward),
       "Duplicates (descending, DUPS_ALLOW)", test);
    ao2_t_ref(c1, -1, "bye c1");
    c1 = NULL;
    ao2_t_ref(c2, -1, "bye c2");
    c2 = NULL;
    /* Create containers that reject duplicate keyed objects. */
    c1 = test_make_sorted(type, AO2_CONTAINER_ALLOC_OPT_DUPS_REJECT);
    if (!c1) {
       ast_test_status_update(test, "Container c1 creation failed.\n");
       res = AST_TEST_FAIL;
       goto test_cleanup;
    }
    if (insert_test_vector(c1, &destructor_count, test_initial, ARRAY_LEN(test_initial), "c1(DUPS_REJECT)", test)) {
       res = AST_TEST_FAIL;
       goto test_cleanup;
    }
    if (insert_test_duplicates(c1, &destructor_count, duplicate_number, "c1(DUPS_REJECT)", test)) {
       res = AST_TEST_FAIL;
       goto test_cleanup;
    }
    c2 = test_make_sorted(type, AO2_CONTAINER_ALLOC_OPT_INSERT_BEGIN | AO2_CONTAINER_ALLOC_OPT_DUPS_REJECT);
    if (!c2) {
       ast_test_status_update(test, "Container c2 creation failed.\n");
       res = AST_TEST_FAIL;
       goto test_cleanup;
    }
    if (insert_test_vector(c2, &destructor_count, test_initial, ARRAY_LEN(test_initial), "c2(DUPS_REJECT)", test)) {
       res = AST_TEST_FAIL;
       goto test_cleanup;
    }
    if (insert_test_duplicates(c2, &destructor_count, duplicate_number, "c2(DUPS_REJECT)", test)) {
       res = AST_TEST_FAIL;
       goto test_cleanup;
    }
    /* Check duplicates in containers that reject duplicate keyed objects. */
    res = test_expected_duplicates(res, c1, OBJ_ORDER_ASCENDING, duplicate_number,
       test_dup_reject, ARRAY_LEN(test_dup_reject),
       "Duplicates (ascending, DUPS_REJECT)", test);
    res = test_expected_duplicates(res, c1, OBJ_ORDER_DESCENDING, duplicate_number,
       test_dup_reject, ARRAY_LEN(test_dup_reject),
       "Duplicates (descending, DUPS_REJECT)", test);
    ao2_t_ref(c1, -1, "bye c1");
    c1 = NULL;
    ao2_t_ref(c2, -1, "bye c2");
    c2 = NULL;
    /* Create containers that reject duplicate objects. */
    c1 = test_make_sorted(type, AO2_CONTAINER_ALLOC_OPT_DUPS_OBJ_REJECT);
    if (!c1) {
       ast_test_status_update(test, "Container c1 creation failed.\n");
       res = AST_TEST_FAIL;
       goto test_cleanup;
    }
    if (insert_test_vector(c1, &destructor_count, test_initial, ARRAY_LEN(test_initial), "c1(DUPS_OBJ_REJECT)", test)) {
       res = AST_TEST_FAIL;
       goto test_cleanup;
    }
    if (insert_test_duplicates(c1, &destructor_count, duplicate_number, "c1(DUPS_OBJ_REJECT)", test)) {
       res = AST_TEST_FAIL;
       goto test_cleanup;
    }
    c2 = test_make_sorted(type, AO2_CONTAINER_ALLOC_OPT_INSERT_BEGIN | AO2_CONTAINER_ALLOC_OPT_DUPS_OBJ_REJECT);
    if (!c2) {
       ast_test_status_update(test, "Container c2 creation failed.\n");
       res = AST_TEST_FAIL;
       goto test_cleanup;
    }
    if (insert_test_vector(c2, &destructor_count, test_initial, ARRAY_LEN(test_initial), "c2(DUPS_OBJ_REJECT)", test)) {
       res = AST_TEST_FAIL;
       goto test_cleanup;
    }
    if (insert_test_duplicates(c2, &destructor_count, duplicate_number, "c2(DUPS_OBJ_REJECT)", test)) {
       res = AST_TEST_FAIL;
       goto test_cleanup;
    }
    /* Check duplicates in containers that reject duplicate objects. */
    res = test_expected_duplicates(res, c1, OBJ_ORDER_ASCENDING, duplicate_number,
       test_dup_obj_reject_forward, ARRAY_LEN(test_dup_obj_reject_forward),
       "Duplicates (ascending, DUPS_OBJ_REJECT)", test);
    res = test_expected_duplicates(res, c1, OBJ_ORDER_DESCENDING, duplicate_number,
       test_dup_obj_reject_backward, ARRAY_LEN(test_dup_obj_reject_backward),
       "Duplicates (descending, DUPS_OBJ_REJECT)", test);
    ao2_t_ref(c1, -1, "bye c1");
    c1 = NULL;
    ao2_t_ref(c2, -1, "bye c2");
    c2 = NULL;
    /* Create container that replaces duplicate keyed objects. */
    c1 = test_make_sorted(type, AO2_CONTAINER_ALLOC_OPT_DUPS_REPLACE);
    if (!c1) {
       ast_test_status_update(test, "Container c1 creation failed.\n");
       res = AST_TEST_FAIL;
       goto test_cleanup;
    }
    if (insert_test_vector(c1, &destructor_count, test_initial, ARRAY_LEN(test_initial), "c1(DUPS_REJECT)", test)) {
       res = AST_TEST_FAIL;
       goto test_cleanup;
    }
    if (insert_test_duplicates(c1, &destructor_count, duplicate_number, "c1(DUPS_REJECT)", test)) {
       res = AST_TEST_FAIL;
       goto test_cleanup;
    }
    c2 = test_make_sorted(type, AO2_CONTAINER_ALLOC_OPT_INSERT_BEGIN | AO2_CONTAINER_ALLOC_OPT_DUPS_REPLACE);
    if (!c2) {
       ast_test_status_update(test, "Container c2 creation failed.\n");
       res = AST_TEST_FAIL;
       goto test_cleanup;
    }
    if (insert_test_vector(c2, &destructor_count, test_initial, ARRAY_LEN(test_initial), "c2(DUPS_REPLACE)", test)) {
       res = AST_TEST_FAIL;
       goto test_cleanup;
    }
    if (insert_test_duplicates(c2, &destructor_count, duplicate_number, "c2(DUPS_REPLACE)", test)) {
       res = AST_TEST_FAIL;
       goto test_cleanup;
    }
    /* Check duplicates in containers that replaces duplicate keyed objects. */
    res = test_expected_duplicates(res, c1, OBJ_ORDER_ASCENDING, duplicate_number,
       test_dup_replace, ARRAY_LEN(test_dup_replace),
       "Duplicates (ascending, DUPS_REPLACE)", test);
    res = test_expected_duplicates(res, c1, OBJ_ORDER_DESCENDING, duplicate_number,
       test_dup_replace, ARRAY_LEN(test_dup_replace),
       "Duplicates (descending, DUPS_REPLACE)", test);
 test_cleanup:
    /* destroy containers */
    if (c1) {
       ao2_t_ref(c1, -1, "bye c1");
    }
    if (c2) {
       ao2_t_ref(c2, -1, "bye c2");
    }
    if (destructor_count > 0) {
       ast_test_status_update(test,
          "all destructors were not called, destructor count is %d\n",
          destructor_count);
       res = AST_TEST_FAIL;
    } else if (destructor_count < 0) {
       ast_test_status_update(test,
          "Destructor was called too many times, destructor count is %d\n",
          destructor_count);
       res = AST_TEST_FAIL;
    }
    return res;
 }
testloop()
static enum ast_test_result_state testloop (struct ast_test * test, enum test_container_type type, int copt, int iterations) static
Definition at line 1992 of file test_astobj2.c.
References AST_TEST_PASS, ast_test_status_update, ast_tvdiff_ms(), ast_tvnow(), test_obj::i, test_container2str(), and test_performance().
Referenced by AST_TEST_DEFINE().
 {
    int res = AST_TEST_PASS;
    int i;
    int reportcount = iterations / 5;
    struct timeval start;
    start = ast_tvnow();
    for (i = 1 ; i <= iterations && res == AST_TEST_PASS ; i++) {
       if (i % reportcount == 0 && i != iterations) {
          ast_test_status_update(test, "%5.2fK traversals, %9s\n",
             i / 1000.0, test_container2str(type));
       }
       res = test_performance(test, type, copt);
    }
    ast_test_status_update(test, "%5.2fK traversals, %9s : %5lu ms\n",
       iterations / 1000.0, test_container2str(type), (unsigned long)ast_tvdiff_ms(ast_tvnow(), start));
    return res;
 }
unload_module()
static int unload_module (void) static
Definition at line 2054 of file test_astobj2.c.
References AST_TEST_UNREGISTER.
 {
    AST_TEST_UNREGISTER(astobj2_test_1);
    AST_TEST_UNREGISTER(astobj2_test_2);
    AST_TEST_UNREGISTER(astobj2_test_3);
    AST_TEST_UNREGISTER(astobj2_test_4);
    AST_TEST_UNREGISTER(astobj2_test_perf);
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "ASTOBJ2 Unit Tests" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, } static
Definition at line 2074 of file test_astobj2.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 2074 of file test_astobj2.c.
partial_key_match_range
int partial_key_match_range
Partial search key +/- matching range.
Definition at line 85 of file test_astobj2.c.
Referenced by test_ao2_find_w_OBJ_PARTIAL_KEY(), test_cmp_cb(), test_sort_cb(), test_traversal_nonsorted(), and test_traversal_sorted().