Asterisk - The Open Source Telephony Project: vparms.c File Reference
vparms.c File Reference
#include "f2c.h"
Functions
int vparms_ (integer *vwin, real *inbuf, real *lpbuf, integer *buflim, integer *half, real *dither, integer *mintau, integer *zc, integer *lbe, integer *fbe, real *qs, real *rc1, real *ar_b__, real *ar_f__)
Variables
static real c_b2 = 1.f
Function Documentation
vparms_()
int vparms_ (integer * vwin, real * inbuf, real * lpbuf, integer * buflim, integer * half, real * dither, integer * mintau, integer * zc, integer * lbe, integer * fbe, real * qs, real * rc1, real * ar_b__, real * ar_f__)
Definition at line 134 of file vparms.c.
References abs, c_b2, i_nint(), max, min, r_sign(), and stop.
Referenced by voicin_().
 {
     /* System generated locals */
     integer inbuf_offset, lpbuf_offset, i__1;
     real r__1, r__2;
     /* Builtin functions */
     double r_sign(real *, real *);
     integer i_nint(real *);
     /* Local variables */
     integer vlen, stop, i__;
     real e_pre__;
     integer start;
     real ap_rms__, e_0__, oldsgn, lp_rms__, e_b__, e_f__, r_b__, r_f__, e0ap;
 /*       Arguments */
 /*       Local variables that need not be saved */
 /*   Calculate zero crossings (ZC) and several energy and correlation */
 /*   measures on low band and full band speech.  Each measure is taken */
 /*   over either the first or the second half of the voicing window, */
 /*   depending on the variable HALF. */
     /* Parameter adjustments */
     --vwin;
     --buflim;
     lpbuf_offset = buflim[3];
     lpbuf -= lpbuf_offset;
     inbuf_offset = buflim[1];
     inbuf -= inbuf_offset;
     /* Function Body */
     lp_rms__ = 0.f;
     ap_rms__ = 0.f;
     e_pre__ = 0.f;
     e0ap = 0.f;
     *rc1 = 0.f;
     e_0__ = 0.f;
     e_b__ = 0.f;
     e_f__ = 0.f;
     r_f__ = 0.f;
     r_b__ = 0.f;
     *zc = 0;
     vlen = vwin[2] - vwin[1] + 1;
     start = vwin[1] + (*half - 1) * vlen / 2 + 1;
     stop = start + vlen / 2 - 1;
 /* I'll use the symbol HVL in the table below to represent the value */
 /* VLEN/2.  Note that if VLEN is odd, then HVL should be rounded down, */
 /* i.e., HVL = (VLEN-1)/2. */
 /* HALF  START          STOP */
 /* 1     VWIN(1)+1      VWIN(1)+HVL */
 /* 2     VWIN(1)+HVL+1  VWIN(1)+2*HVL */
 /* Note that if VLEN is even and HALF is 2, then STOP will be */
 /* VWIN(1)+VLEN = VWIN(2)+1.  That could be bad, if that index of INBUF */
 /* is undefined. */
     r__1 = inbuf[start - 1] - *dither;
     oldsgn = (real)r_sign(&c_b2, &r__1);
     i__1 = stop;
     for (i__ = start; i__ <= i__1; ++i__) {
    lp_rms__ += (r__1 = lpbuf[i__], abs(r__1));
    ap_rms__ += (r__1 = inbuf[i__], abs(r__1));
    e_pre__ += (r__1 = inbuf[i__] - inbuf[i__ - 1], abs(r__1));
 /* Computing 2nd power */
    r__1 = inbuf[i__];
    e0ap += r__1 * r__1;
    *rc1 += inbuf[i__] * inbuf[i__ - 1];
 /* Computing 2nd power */
    r__1 = lpbuf[i__];
    e_0__ += r__1 * r__1;
 /* Computing 2nd power */
    r__1 = lpbuf[i__ - *mintau];
    e_b__ += r__1 * r__1;
 /* Computing 2nd power */
    r__1 = lpbuf[i__ + *mintau];
    e_f__ += r__1 * r__1;
    r_f__ += lpbuf[i__] * lpbuf[i__ + *mintau];
    r_b__ += lpbuf[i__] * lpbuf[i__ - *mintau];
    r__1 = inbuf[i__] + *dither;
    if (r_sign(&c_b2, &r__1) != oldsgn) {
        ++(*zc);
        oldsgn = -oldsgn;
    }
    *dither = -(*dither);
     }
 /*   Normalized short-term autocovariance coefficient at unit sample delay
  */
     *rc1 /= max(e0ap,1.f);
 /*  Ratio of the energy of the first difference signal (6 dB/oct preemphas
 is)*/
 /*   to the energy of the full band signal */
 /* Computing MAX */
     r__1 = ap_rms__ * 2.f;
     *qs = e_pre__ / max(r__1,1.f);
 /*   aR_b is the product of the forward and reverse prediction gains, */
 /*   looking backward in time (the causal case). */
     *ar_b__ = r_b__ / max(e_b__,1.f) * (r_b__ / max(e_0__,1.f));
 /*  aR_f is the same as aR_b, but looking forward in time (non causal case
 ).*/
     *ar_f__ = r_f__ / max(e_f__,1.f) * (r_f__ / max(e_0__,1.f));
 /*   Normalize ZC, LBE, and FBE to old fixed window length of 180. */
 /*   (The fraction 90/VLEN has a range of .58 to 1) */
     r__2 = (real) (*zc << 1);
     r__1 = r__2 * (90.f / vlen);
     *zc = i_nint(&r__1);
 /* Computing MIN */
     r__1 = lp_rms__ / 4 * (90.f / vlen);
     i__1 = i_nint(&r__1);
     *lbe = min(i__1,32767);
 /* Computing MIN */
     r__1 = ap_rms__ / 4 * (90.f / vlen);
     i__1 = i_nint(&r__1);
     *fbe = min(i__1,32767);
     return 0;
 } /* vparms_ */
Variable Documentation
c_b2
real c_b2 = 1.f static
Definition at line 35 of file vparms.c.
Referenced by vparms_().