Asterisk - The Open Source Telephony Project: format_wav_gsm.c File Reference
format_wav_gsm.c File Reference
Module: Media File Formats
Save GSM in the proprietary Microsoft format.
#include "asterisk.h"
#include "asterisk/mod_format.h"
#include "asterisk/module.h"
#include "asterisk/endian.h"
#include "asterisk/format_cache.h"
#include "msgsm.h"
Data Structures
struct wavg_desc
Macros
#define GSM_FRAME_SIZE 33
#define GSM_SAMPLES 160 /* samples in a GSM block */
#define MSGSM_DATA_OFFSET 60 /* offset of data bytes */
#define MSGSM_FRAME_SIZE 65
#define MSGSM_SAMPLES (2*GSM_SAMPLES) /* samples in an MSGSM block */
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int check_header (FILE *f)
static int load_module (void)
static int unload_module (void)
static int update_header (FILE *f)
static void wav_close (struct ast_filestream *s)
static int wav_open (struct ast_filestream *s)
static struct ast_frame * wav_read (struct ast_filestream *s, int *whennext)
static int wav_rewrite (struct ast_filestream *s, const char *comment)
static int wav_seek (struct ast_filestream *fs, off_t sample_offset, int whence)
static off_t wav_tell (struct ast_filestream *fs)
static int wav_trunc (struct ast_filestream *fs)
static int wav_write (struct ast_filestream *s, struct ast_frame *f)
static int write_header (FILE *f)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Microsoft WAV format (Proprietary GSM)" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_APP_DEPEND }
static const struct ast_module_info * ast_module_info = &__mod_info
static char msgsm_silence []
static struct ast_format_def wav49_f
Detailed Description
Save GSM in the proprietary Microsoft format.
Microsoft WAV format (Proprietary GSM)
File name extension: WAV,wav49 (Upper case WAV, lower case is another format) This format can be played on Windows systems, used for e-mail attachments mainly.
Definition in file format_wav_gsm.c.
Macro Definition Documentation
GSM_FRAME_SIZE
#define GSM_FRAME_SIZE 33
Definition at line 47 of file format_wav_gsm.c.
Referenced by wav_read(), and wav_write().
GSM_SAMPLES
#define GSM_SAMPLES 160 /* samples in a GSM block */
Definition at line 50 of file format_wav_gsm.c.
Referenced by wav_read().
MSGSM_DATA_OFFSET
#define MSGSM_DATA_OFFSET 60 /* offset of data bytes */
Definition at line 49 of file format_wav_gsm.c.
Referenced by update_header(), wav_seek(), and wav_tell().
MSGSM_FRAME_SIZE
#define MSGSM_FRAME_SIZE 65
Definition at line 48 of file format_wav_gsm.c.
Referenced by update_header(), wav_read(), wav_seek(), wav_tell(), wav_write(), and write_header().
MSGSM_SAMPLES
#define MSGSM_SAMPLES (2*GSM_SAMPLES) /* samples in an MSGSM block */
Definition at line 51 of file format_wav_gsm.c.
Referenced by update_header(), wav_seek(), wav_tell(), and write_header().
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 588 of file format_wav_gsm.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 588 of file format_wav_gsm.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 588 of file format_wav_gsm.c.
check_header()
static int check_header (FILE * f) static
Definition at line 91 of file format_wav_gsm.c.
References ast_log, chans, DEFAULT_SAMPLE_RATE, format, LOG_WARNING, and type.
Referenced by wav_open().
 {
    int type, size, formtype;
    int fmt, hsize, fact;
    short format, chans;
    int freq;
    int data;
    if (fread(&type, 1, 4, f) != 4) {
       ast_log(LOG_WARNING, "Read failed (type)\n");
       return -1;
    }
    if (fread(&size, 1, 4, f) != 4) {
       ast_log(LOG_WARNING, "Read failed (size)\n");
       return -1;
    }
 #if __BYTE_ORDER == __BIG_ENDIAN
    size = ltohl(size);
 #endif
    if (fread(&formtype, 1, 4, f) != 4) {
       ast_log(LOG_WARNING, "Read failed (formtype)\n");
       return -1;
    }
    if (memcmp(&type, "RIFF", 4)) {
       ast_log(LOG_WARNING, "Does not begin with RIFF\n");
       return -1;
    }
    if (memcmp(&formtype, "WAVE", 4)) {
       ast_log(LOG_WARNING, "Does not contain WAVE\n");
       return -1;
    }
    if (fread(&fmt, 1, 4, f) != 4) {
       ast_log(LOG_WARNING, "Read failed (fmt)\n");
       return -1;
    }
    if (memcmp(&fmt, "fmt ", 4)) {
       ast_log(LOG_WARNING, "Does not say fmt\n");
       return -1;
    }
    if (fread(&hsize, 1, 4, f) != 4) {
       ast_log(LOG_WARNING, "Read failed (formtype)\n");
       return -1;
    }
    if (ltohl(hsize) != 20) {
       ast_log(LOG_WARNING, "Unexpected header size %d\n", ltohl(hsize));
       return -1;
    }
    if (fread(&format, 1, 2, f) != 2) {
       ast_log(LOG_WARNING, "Read failed (format)\n");
       return -1;
    }
    if (ltohs(format) != 49) {
       ast_log(LOG_WARNING, "Not a GSM file %d\n", ltohs(format));
       return -1;
    }
    if (fread(&chans, 1, 2, f) != 2) {
       ast_log(LOG_WARNING, "Read failed (format)\n");
       return -1;
    }
    if (ltohs(chans) != 1) {
       ast_log(LOG_WARNING, "Not in mono %d\n", ltohs(chans));
       return -1;
    }
    if (fread(&freq, 1, 4, f) != 4) {
       ast_log(LOG_WARNING, "Read failed (freq)\n");
       return -1;
    }
    if (ltohl(freq) != DEFAULT_SAMPLE_RATE) {
       ast_log(LOG_WARNING, "Unexpected frequency %d\n", ltohl(freq));
       return -1;
    }
    /* Ignore the byte frequency */
    if (fread(&freq, 1, 4, f) != 4) {
       ast_log(LOG_WARNING, "Read failed (X_1)\n");
       return -1;
    }
    /* Ignore the two weird fields */
    if (fread(&freq, 1, 4, f) != 4) {
       ast_log(LOG_WARNING, "Read failed (X_2/X_3)\n");
       return -1;
    }
    /* Ignore the byte frequency */
    if (fread(&freq, 1, 4, f) != 4) {
       ast_log(LOG_WARNING, "Read failed (Y_1)\n");
       return -1;
    }
    /* Check for the word fact */
    if (fread(&fact, 1, 4, f) != 4) {
       ast_log(LOG_WARNING, "Read failed (fact)\n");
       return -1;
    }
    if (memcmp(&fact, "fact", 4)) {
       ast_log(LOG_WARNING, "Does not say fact\n");
       return -1;
    }
    /* Ignore the "fact value" */
    if (fread(&fact, 1, 4, f) != 4) {
       ast_log(LOG_WARNING, "Read failed (fact header)\n");
       return -1;
    }
    if (fread(&fact, 1, 4, f) != 4) {
       ast_log(LOG_WARNING, "Read failed (fact value)\n");
       return -1;
    }
    /* Check for the word data */
    if (fread(&data, 1, 4, f) != 4) {
       ast_log(LOG_WARNING, "Read failed (data)\n");
       return -1;
    }
    if (memcmp(&data, "data", 4)) {
       ast_log(LOG_WARNING, "Does not say data\n");
       return -1;
    }
    /* Ignore the data length */
    if (fread(&data, 1, 4, f) != 4) {
       ast_log(LOG_WARNING, "Read failed (data)\n");
       return -1;
    }
    return 0;
 }
load_module()
static int load_module (void) static
Definition at line 570 of file format_wav_gsm.c.
References ast_format_def_register, ast_format_gsm, AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, and ast_format_def::format.
Referenced by unload_module().
 {
    wav49_f.format = ast_format_gsm;
    if (ast_format_def_register(&wav49_f))
       return AST_MODULE_LOAD_DECLINE;
    return AST_MODULE_LOAD_SUCCESS;
 }
unload_module()
static int unload_module (void) static
Definition at line 578 of file format_wav_gsm.c.
References ast_format_def_unregister(), AST_MODFLAG_LOAD_ORDER, AST_MODPRI_APP_DEPEND, AST_MODULE_INFO(), AST_MODULE_SUPPORT_CORE, ASTERISK_GPL_KEY, load_module(), and ast_format_def::name.
 {
    return ast_format_def_unregister(wav49_f.name);
 }
update_header()
static int update_header (FILE * f) static
Definition at line 211 of file format_wav_gsm.c.
References ast_log, end, LOG_WARNING, MSGSM_DATA_OFFSET, MSGSM_FRAME_SIZE, and MSGSM_SAMPLES.
Referenced by wav_close(), and wav_trunc().
 {
    off_t cur,end,bytes;
    int datalen, filelen, samples;
    cur = ftello(f);
    fseek(f, 0, SEEK_END);
    end = ftello(f);
    /* in a gsm WAV, data starts 60 bytes in */
    bytes = end - MSGSM_DATA_OFFSET;
    samples = htoll(bytes / MSGSM_FRAME_SIZE * MSGSM_SAMPLES);
    datalen = htoll(bytes);
    filelen = htoll(MSGSM_DATA_OFFSET - 8 + bytes);
    if (cur < 0) {
       ast_log(LOG_WARNING, "Unable to find our position\n");
       return -1;
    }
    if (fseek(f, 4, SEEK_SET)) {
       ast_log(LOG_WARNING, "Unable to set our position\n");
       return -1;
    }
    if (fwrite(&filelen, 1, 4, f) != 4) {
       ast_log(LOG_WARNING, "Unable to write file size\n");
       return -1;
    }
    if (fseek(f, 48, SEEK_SET)) {
       ast_log(LOG_WARNING, "Unable to set our position\n");
       return -1;
    }
    if (fwrite(&samples, 1, 4, f) != 4) {
       ast_log(LOG_WARNING, "Unable to write samples\n");
       return -1;
    }
    if (fseek(f, 56, SEEK_SET)) {
       ast_log(LOG_WARNING, "Unable to set our position\n");
       return -1;
    }
    if (fwrite(&datalen, 1, 4, f) != 4) {
       ast_log(LOG_WARNING, "Unable to write datalen\n");
       return -1;
    }
    if (fseeko(f, cur, SEEK_SET)) {
       ast_log(LOG_WARNING, "Unable to return to position\n");
       return -1;
    }
    return 0;
 }
wav_close()
static void wav_close (struct ast_filestream * s) static
Definition at line 397 of file format_wav_gsm.c.
References ast_filestream::f, ast_filestream::filename, ast_filestream::mode, and update_header().
 {
    if (s->mode == O_RDONLY) {
       return;
    }
    if (s->filename) {
       update_header(s->f);
    }
 }
wav_open()
static int wav_open (struct ast_filestream * s) static
Definition at line 373 of file format_wav_gsm.c.
References ast_filestream::_private, check_header(), ast_filestream::f, if(), and wavg_desc::secondhalf.
 {
    /* We don't have any header to read or anything really, but
       if we did, it would go here.  We also might want to check
       and be sure it's a valid file.  */
    struct wavg_desc *fs = (struct wavg_desc *)s->_private;
    if (check_header(s->f))
       return -1;
    fs->secondhalf = 0;  /* not strictly necessary */
    return 0;
 }
wav_read()
static struct ast_frame* wav_read (struct ast_filestream * s, int * whennext) static
Definition at line 408 of file format_wav_gsm.c.
References ast_filestream::_private, ast_format_get_name(), AST_FRAME_SET_BUFFER, AST_FRIENDLY_OFFSET, ast_log, ast_filestream::buf, conv65(), ast_frame::data, errno, ast_filestream::f, ast_frame_subclass::format, ast_filestream::fr, GSM_FRAME_SIZE, GSM_SAMPLES, LOG_WARNING, MSGSM_FRAME_SIZE, NULL, ast_frame::offset, ast_frame::ptr, ast_frame::samples, wavg_desc::secondhalf, and ast_frame::subclass.
 {
    /* Send a frame from the file to the appropriate channel */
    struct wavg_desc *fs = (struct wavg_desc *)s->_private;
    s->fr.samples = GSM_SAMPLES;
    AST_FRAME_SET_BUFFER(&s->fr, s->buf, AST_FRIENDLY_OFFSET, GSM_FRAME_SIZE);
    if (fs->secondhalf) {
       /* Just return a frame based on the second GSM frame */
       s->fr.data.ptr = (char *)s->fr.data.ptr + GSM_FRAME_SIZE;
       s->fr.offset += GSM_FRAME_SIZE;
    } else {
       /* read and convert */
       unsigned char msdata[MSGSM_FRAME_SIZE];
       size_t res;
       if ((res = fread(msdata, 1, MSGSM_FRAME_SIZE, s->f)) != MSGSM_FRAME_SIZE) {
          if (res && res != 1) {
             ast_log(LOG_WARNING, "Short read of %s data (expected %d bytes, read %zu): %s\n",
                   ast_format_get_name(s->fr.subclass.format), MSGSM_FRAME_SIZE, res,
                   strerror(errno));
          }
          return NULL;
       }
       /* Convert from MS format to two real GSM frames */
       conv65(msdata, s->fr.data.ptr);
    }
    fs->secondhalf = !fs->secondhalf;
    *whennext = GSM_SAMPLES;
    return &s->fr;
 }
wav_rewrite()
static int wav_rewrite (struct ast_filestream * s, const char * comment) static
Definition at line 386 of file format_wav_gsm.c.
References ast_filestream::f, and write_header().
 {
    /* We don't have any header to read or anything really, but
       if we did, it would go here.  We also might want to check
       and be sure it's a valid file.  */
    if (write_header(s->f))
       return -1;
    return 0;
 }
wav_seek()
static int wav_seek (struct ast_filestream * fs, off_t sample_offset, int whence) static
Definition at line 478 of file format_wav_gsm.c.
References ast_filestream::_private, ast_log, AST_LOG_WARNING, errno, ast_filestream::f, if(), LOG_WARNING, max, min, MSGSM_DATA_OFFSET, MSGSM_FRAME_SIZE, MSGSM_SAMPLES, msgsm_silence, wavg_desc::secondhalf, and SEEK_FORCECUR.
 {
    off_t offset = 0, min = MSGSM_DATA_OFFSET, distance, max, cur;
    struct wavg_desc *s = (struct wavg_desc *)fs->_private;
    if ((cur = ftello(fs->f)) < 0) {
       ast_log(AST_LOG_WARNING, "Unable to determine current position in WAV filestream %p: %s\n", fs, strerror(errno));
       return -1;
    }
    if (fseeko(fs->f, 0, SEEK_END) < 0) {
       ast_log(AST_LOG_WARNING, "Unable to seek to end of WAV filestream %p: %s\n", fs, strerror(errno));
       return -1;
    }
    /* XXX ideally, should round correctly */
    if ((max = ftello(fs->f)) < 0) {
       ast_log(AST_LOG_WARNING, "Unable to determine max position in WAV filestream %p: %s\n", fs, strerror(errno));
       return -1;
    }
    /* Compute the distance in bytes, rounded to the block size */
    distance = (sample_offset/MSGSM_SAMPLES) * MSGSM_FRAME_SIZE;
    if (whence == SEEK_SET)
       offset = distance + min;
    else if (whence == SEEK_CUR || whence == SEEK_FORCECUR)
       offset = distance + cur;
    else if (whence == SEEK_END)
       offset = max - distance;
    /* always protect against seeking past end of header */
    if (offset < min)
       offset = min;
    if (whence != SEEK_FORCECUR) {
       if (offset > max)
          offset = max;
    } else if (offset > max) {
       int i;
       fseek(fs->f, 0, SEEK_END);
       for (i=0; i< (offset - max) / MSGSM_FRAME_SIZE; i++) {
          if (fwrite(msgsm_silence, 1, MSGSM_FRAME_SIZE, fs->f) != MSGSM_FRAME_SIZE) {
             ast_log(LOG_WARNING, "fwrite() failed: %s\n", strerror(errno));
          }
       }
    }
    s->secondhalf = 0;
    return fseeko(fs->f, offset, SEEK_SET);
 }
wav_tell()
static off_t wav_tell (struct ast_filestream * fs) static
Definition at line 546 of file format_wav_gsm.c.
References ast_filestream::f, MSGSM_DATA_OFFSET, MSGSM_FRAME_SIZE, and MSGSM_SAMPLES.
 {
    off_t offset;
    offset = ftello(fs->f);
    /* since this will most likely be used later in play or record, lets stick
     * to that level of resolution, just even frames boundaries */
    return (offset - MSGSM_DATA_OFFSET)/MSGSM_FRAME_SIZE*MSGSM_SAMPLES;
 }
wav_trunc()
static int wav_trunc (struct ast_filestream * fs) static
Definition at line 526 of file format_wav_gsm.c.
References ast_log, AST_LOG_WARNING, errno, ast_filestream::f, and update_header().
 {
    int fd;
    off_t cur;
    if ((fd = fileno(fs->f)) < 0) {
       ast_log(AST_LOG_WARNING, "Unable to determine file descriptor for WAV filestream %p: %s\n", fs, strerror(errno));
       return -1;
    }
    if ((cur = ftello(fs->f)) < 0) {
       ast_log(AST_LOG_WARNING, "Unable to determine current position in WAV filestream %p: %s\n", fs, strerror(errno));
       return -1;
    }
    /* Truncate file to current length */
    if (ftruncate(fd, cur)) {
       return -1;
    }
    return update_header(fs->f);
 }
wav_write()
static int wav_write (struct ast_filestream * s, struct ast_frame * f) static
Definition at line 440 of file format_wav_gsm.c.
References ast_filestream::_private, ast_log, ast_filestream::buf, conv66(), ast_frame::data, ast_frame::datalen, errno, ast_filestream::f, GSM_FRAME_SIZE, if(), len(), LOG_WARNING, MSGSM_FRAME_SIZE, NULL, ast_frame::ptr, and wavg_desc::secondhalf.
 {
    int len;
    int size;
    struct wavg_desc *fs = (struct wavg_desc *)s->_private;
    /* XXX this might fail... if the input is a multiple of MSGSM_FRAME_SIZE
     * we assume it is already in the correct format.
     */
    if (!(f->datalen % MSGSM_FRAME_SIZE)) {
       size = MSGSM_FRAME_SIZE;
       fs->secondhalf = 0;
    } else {
       size = GSM_FRAME_SIZE;
    }
    for (len = 0; len < f->datalen ; len += size) {
       int res;
       unsigned char *src, msdata[MSGSM_FRAME_SIZE];
       if (fs->secondhalf) {   /* second half of raw gsm to be converted */
          memcpy(s->buf + GSM_FRAME_SIZE, f->data.ptr + len, GSM_FRAME_SIZE);
          conv66((unsigned char *) s->buf, msdata);
          src = msdata;
          fs->secondhalf = 0;
       } else if (size == GSM_FRAME_SIZE) {   /* first half of raw gsm */
          memcpy(s->buf, f->data.ptr + len, GSM_FRAME_SIZE);
          src = NULL; /* nothing to write */
          fs->secondhalf = 1;
       } else { /* raw msgsm data */
          src = f->data.ptr + len;
       }
       if (src && (res = fwrite(src, 1, MSGSM_FRAME_SIZE, s->f)) != MSGSM_FRAME_SIZE) {
          ast_log(LOG_WARNING, "Bad write (%d/65): %s\n", res, strerror(errno));
          return -1;
       }
    }
    return 0;
 }
write_header()
static int write_header (FILE * f) static
Definition at line 259 of file format_wav_gsm.c.
References ast_log, LOG_WARNING, MSGSM_FRAME_SIZE, and MSGSM_SAMPLES.
Referenced by wav_rewrite().
 {
    /* Samples per second (always 8000 for this format). */
    unsigned int sample_rate = htoll(8000);
    /* Bytes per second (always 1625 for this format). */
    unsigned int byte_sample_rate = htoll(1625);
    /* This is the size of the "fmt " subchunk */
    unsigned int fmtsize = htoll(20);
    /* WAV #49 */
    unsigned short fmt = htols(49);
    /* Mono = 1 channel */
    unsigned short chans = htols(1);
    /* Each block of data is exactly 65 bytes in size. */
    unsigned int block_align = htoll(MSGSM_FRAME_SIZE);
    /* Not actually 2, but rounded up to the nearest bit */
    unsigned short bits_per_sample = htols(2);
    /* Needed for compressed formats */
    unsigned short extra_format = htols(MSGSM_SAMPLES);
    /* This is the size of the "fact" subchunk */
    unsigned int factsize = htoll(4);
    /* Number of samples in the data chunk */
    unsigned int num_samples = htoll(0);
    /* Number of bytes in the data chunk */
    unsigned int size = htoll(0);
    /* Write a GSM header, ignoring sizes which will be filled in later */
    /*  0: Chunk ID */
    if (fwrite("RIFF", 1, 4, f) != 4) {
       ast_log(LOG_WARNING, "Unable to write header\n");
       return -1;
    }
    /*  4: Chunk Size */
    if (fwrite(&size, 1, 4, f) != 4) {
       ast_log(LOG_WARNING, "Unable to write header\n");
       return -1;
    }
    /*  8: Chunk Format */
    if (fwrite("WAVE", 1, 4, f) != 4) {
       ast_log(LOG_WARNING, "Unable to write header\n");
       return -1;
    }
    /* 12: Subchunk 1: ID */
    if (fwrite("fmt ", 1, 4, f) != 4) {
       ast_log(LOG_WARNING, "Unable to write header\n");
       return -1;
    }
    /* 16: Subchunk 1: Size (minus 8) */
    if (fwrite(&fmtsize, 1, 4, f) != 4) {
       ast_log(LOG_WARNING, "Unable to write header\n");
       return -1;
    }
    /* 20: Subchunk 1: Audio format (49) */
    if (fwrite(&fmt, 1, 2, f) != 2) {
       ast_log(LOG_WARNING, "Unable to write header\n");
       return -1;
    }
    /* 22: Subchunk 1: Number of channels */
    if (fwrite(&chans, 1, 2, f) != 2) {
       ast_log(LOG_WARNING, "Unable to write header\n");
       return -1;
    }
    /* 24: Subchunk 1: Sample rate */
    if (fwrite(&sample_rate, 1, 4, f) != 4) {
       ast_log(LOG_WARNING, "Unable to write header\n");
       return -1;
    }
    /* 28: Subchunk 1: Byte rate */
    if (fwrite(&byte_sample_rate, 1, 4, f) != 4) {
       ast_log(LOG_WARNING, "Unable to write header\n");
       return -1;
    }
    /* 32: Subchunk 1: Block align */
    if (fwrite(&block_align, 1, 4, f) != 4) {
       ast_log(LOG_WARNING, "Unable to write header\n");
       return -1;
    }
    /* 36: Subchunk 1: Bits per sample */
    if (fwrite(&bits_per_sample, 1, 2, f) != 2) {
       ast_log(LOG_WARNING, "Unable to write header\n");
       return -1;
    }
    /* 38: Subchunk 1: Extra format bytes */
    if (fwrite(&extra_format, 1, 2, f) != 2) {
       ast_log(LOG_WARNING, "Unable to write header\n");
       return -1;
    }
    /* 40: Subchunk 2: ID */
    if (fwrite("fact", 1, 4, f) != 4) {
       ast_log(LOG_WARNING, "Unable to write header\n");
       return -1;
    }
    /* 44: Subchunk 2: Size (minus 8) */
    if (fwrite(&factsize, 1, 4, f) != 4) {
       ast_log(LOG_WARNING, "Unable to write header\n");
       return -1;
    }
    /* 48: Subchunk 2: Number of samples */
    if (fwrite(&num_samples, 1, 4, f) != 4) {
       ast_log(LOG_WARNING, "Unable to write header\n");
       return -1;
    }
    /* 52: Subchunk 3: ID */
    if (fwrite("data", 1, 4, f) != 4) {
       ast_log(LOG_WARNING, "Unable to write header\n");
       return -1;
    }
    /* 56: Subchunk 3: Size */
    if (fwrite(&size, 1, 4, f) != 4) {
       ast_log(LOG_WARNING, "Unable to write header\n");
       return -1;
    }
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Microsoft WAV format (Proprietary GSM)" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_APP_DEPEND } static
Definition at line 588 of file format_wav_gsm.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 588 of file format_wav_gsm.c.
msgsm_silence
char msgsm_silence[] static
Definition at line 54 of file format_wav_gsm.c.
Referenced by wav_seek().
wav49_f
struct ast_format_def wav49_f static
Definition at line 555 of file format_wav_gsm.c.