Asterisk - The Open Source Telephony Project: certificate.h File Reference
certificate.h File Reference
#include <openssl/evp.h>
Functions
const char * stir_shaken_certificate_get_attestation (struct stir_shaken_certificate *cert)
Get the attestation level associated with a certificate.
struct stir_shaken_certificate * stir_shaken_certificate_get_by_caller_id_number (const char *caller_id_number)
Get a STIR/SHAKEN certificate by caller ID number.
EVP_PKEY * stir_shaken_certificate_get_private_key (struct stir_shaken_certificate *cert)
Get the private key associated with a certificate.
const char * stir_shaken_certificate_get_public_cert_url (struct stir_shaken_certificate *cert)
Get the public key URL associated with a certificate.
int stir_shaken_certificate_load (void)
Load time initialization for the stir/shaken 'certificate' configuration.
int stir_shaken_certificate_unload (void)
Unload time cleanup for the stir/shaken 'certificate' configuration.
Function Documentation
stir_shaken_certificate_get_attestation()
const char* stir_shaken_certificate_get_attestation (struct stir_shaken_certificate * cert)
Get the attestation level associated with a certificate.
Parameters
cert The certificate
Return values
NULL on failure
The attestation on success
Definition at line 101 of file certificate.c.
References stir_shaken_certificate::attestation, and NULL.
Referenced by ast_stir_shaken_sign().
 {
    return cert ? cert->attestation : NULL;
 }
stir_shaken_certificate_get_by_caller_id_number()
struct stir_shaken_certificate* stir_shaken_certificate_get_by_caller_id_number (const char * caller_id_number)
Get a STIR/SHAKEN certificate by caller ID number.
Parameters
callier_id_number The caller ID number
Return values
NULL if not found
The certificate on success
Definition at line 84 of file certificate.c.
References AST_RETRIEVE_FLAG_DEFAULT, ast_sorcery_retrieve_by_fields(), ast_stir_shaken_sorcery(), stir_shaken_certificate::caller_id_number, ast_variable::name, and NULL.
Referenced by ast_stir_shaken_sign(), and test_stir_shaken_cleanup_cert().
 {
    struct ast_variable fields = {
       .name = "caller_id_number",
       .value = caller_id_number,
       .next = NULL,
    };
    return ast_sorcery_retrieve_by_fields(ast_stir_shaken_sorcery(),
       "certificate", AST_RETRIEVE_FLAG_DEFAULT, &fields);
 }
stir_shaken_certificate_get_private_key()
EVP_PKEY* stir_shaken_certificate_get_private_key (struct stir_shaken_certificate * cert)
Get the private key associated with a certificate.
Parameters
cert The certificate to get the private key from
Return values
NULL on failure
The private key on success
Definition at line 106 of file certificate.c.
References NULL, and stir_shaken_certificate::private_key.
Referenced by ast_stir_shaken_sign().
 {
    return cert ? cert->private_key : NULL;
 }
stir_shaken_certificate_get_public_cert_url()
const char* stir_shaken_certificate_get_public_cert_url (struct stir_shaken_certificate * cert)
Get the public key URL associated with a certificate.
Parameters
cert The certificate to get the public key URL from
Return values
NULL on failure
The public key URL on success
Definition at line 96 of file certificate.c.
References NULL, and stir_shaken_certificate::public_cert_url.
Referenced by ast_stir_shaken_sign().
 {
    return cert ? cert->public_cert_url : NULL;
 }
stir_shaken_certificate_load()
int stir_shaken_certificate_load (void)
Load time initialization for the stir/shaken 'certificate' configuration.
Return values
0 on success, -1 on error
Definition at line 355 of file certificate.c.
References ARRAY_LEN, ast_cli_register_multiple, ast_log, ast_sorcery_apply_default, ast_sorcery_object_field_register, ast_sorcery_object_field_register_custom, ast_sorcery_object_register, ast_stir_shaken_sorcery(), attestation_to_str(), stir_shaken_certificate::caller_id_number, CONFIG_TYPE, LOG_ERROR, NULL, on_load_attestation(), on_load_path(), on_load_public_cert_url(), OPT_NOOP_T, OPT_STRINGFIELD_T, path_to_str(), public_cert_url_to_str(), sorcery, stir_shaken_certificate_alloc(), stir_shaken_certificate_apply(), and STRFLDSET.
Referenced by load_module().
 {
    struct ast_sorcery *sorcery = ast_stir_shaken_sorcery();
    ast_sorcery_apply_default(sorcery, CONFIG_TYPE, "config", "stir_shaken.conf,criteria=type=certificate");
    if (ast_sorcery_object_register(sorcery, CONFIG_TYPE, stir_shaken_certificate_alloc,
          NULL, stir_shaken_certificate_apply)) {
       ast_log(LOG_ERROR, "stir/shaken - failed to register '%s' sorcery object\n", CONFIG_TYPE);
       return -1;
    }
    ast_sorcery_object_field_register(sorcery, CONFIG_TYPE, "type", "", OPT_NOOP_T, 0, 0);
    ast_sorcery_object_field_register_custom(sorcery, CONFIG_TYPE, "path", "",
       on_load_path, path_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register_custom(sorcery, CONFIG_TYPE, "public_cert_url", "",
       on_load_public_cert_url, public_cert_url_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register_custom(sorcery, CONFIG_TYPE, "attestation", "",
       on_load_attestation, attestation_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register(sorcery, CONFIG_TYPE, "caller_id_number", "", OPT_STRINGFIELD_T, 0, STRFLDSET(struct stir_shaken_certificate, caller_id_number));
    ast_cli_register_multiple(stir_shaken_certificate_cli,
       ARRAY_LEN(stir_shaken_certificate_cli));
    return 0;
 }
stir_shaken_certificate_unload()
int stir_shaken_certificate_unload (void)
Unload time cleanup for the stir/shaken 'certificate' configuration.
Return values
0 on success, -1 on error
Definition at line 347 of file certificate.c.
References ARRAY_LEN, and ast_cli_unregister_multiple().
Referenced by unload_module().
 {
    ast_cli_unregister_multiple(stir_shaken_certificate_cli,
       ARRAY_LEN(stir_shaken_certificate_cli));
    return 0;
 }