Asterisk - The Open Source Telephony Project: dns_naptr.h File Reference
dns_naptr.h File Reference
DNS NAPTR Record Parsing API.
Functions
const char * ast_dns_naptr_get_flags (const struct ast_dns_record *record)
Get the flags from a NAPTR record.
unsigned short ast_dns_naptr_get_order (const struct ast_dns_record *record)
Get the order from a NAPTR record.
unsigned short ast_dns_naptr_get_preference (const struct ast_dns_record *record)
Get the preference from a NAPTR record.
const char * ast_dns_naptr_get_regexp (const struct ast_dns_record *record)
Get the regular expression from a NAPTR record.
const char * ast_dns_naptr_get_replacement (const struct ast_dns_record *record)
Get the replacement value from a NAPTR record.
const char * ast_dns_naptr_get_service (const struct ast_dns_record *record)
Get the service from a NAPTR record.
Detailed Description
DNS NAPTR Record Parsing API.
Author
Joshua Colp jcolp.nosp@m.@dig.nosp@m.ium.c.nosp@m.om
Definition in file dns_naptr.h.
Function Documentation
ast_dns_naptr_get_flags()
const char* ast_dns_naptr_get_flags (const struct ast_dns_record * record)
Get the flags from a NAPTR record.
Parameters
record The DNS record
Returns
the flags
Definition at line 600 of file dns_naptr.c.
References ast_assert, ast_dns_record_get_rr_type(), and ast_dns_naptr_record::flags.
Referenced by AST_TEST_DEFINE(), and sip_resolve_handle_naptr().
 {
    struct ast_dns_naptr_record *naptr = (struct ast_dns_naptr_record *) record;
    ast_assert(ast_dns_record_get_rr_type(record) == T_NAPTR);
    return naptr->flags;
 }
ast_dns_naptr_get_order()
unsigned short ast_dns_naptr_get_order (const struct ast_dns_record * record)
Get the order from a NAPTR record.
Parameters
record The DNS record
Returns
the order
Definition at line 632 of file dns_naptr.c.
References ast_assert, ast_dns_record_get_rr_type(), and ast_dns_naptr_record::order.
Referenced by AST_TEST_DEFINE(), and sip_resolve_callback().
 {
    struct ast_dns_naptr_record *naptr = (struct ast_dns_naptr_record *) record;
    ast_assert(ast_dns_record_get_rr_type(record) == T_NAPTR);
    return naptr->order;
 }
ast_dns_naptr_get_preference()
unsigned short ast_dns_naptr_get_preference (const struct ast_dns_record * record)
Get the preference from a NAPTR record.
Parameters
record The DNS record
Returns
the preference
Definition at line 640 of file dns_naptr.c.
References ast_assert, ast_dns_record_get_rr_type(), and ast_dns_naptr_record::preference.
Referenced by AST_TEST_DEFINE().
 {
    struct ast_dns_naptr_record *naptr = (struct ast_dns_naptr_record *) record;
    ast_assert(ast_dns_record_get_rr_type(record) == T_NAPTR);
    return naptr->preference;
 }
ast_dns_naptr_get_regexp()
const char* ast_dns_naptr_get_regexp (const struct ast_dns_record * record)
Get the regular expression from a NAPTR record.
Parameters
record The DNS record
Returns
the regular expression
Definition at line 616 of file dns_naptr.c.
References ast_assert, ast_dns_record_get_rr_type(), and ast_dns_naptr_record::regexp.
Referenced by AST_TEST_DEFINE().
 {
    struct ast_dns_naptr_record *naptr = (struct ast_dns_naptr_record *) record;
    ast_assert(ast_dns_record_get_rr_type(record) == T_NAPTR);
    return naptr->regexp;
 }
ast_dns_naptr_get_replacement()
const char* ast_dns_naptr_get_replacement (const struct ast_dns_record * record)
Get the replacement value from a NAPTR record.
Parameters
record The DNS record
Returns
the replacement value
Definition at line 624 of file dns_naptr.c.
References ast_assert, ast_dns_record_get_rr_type(), and ast_dns_naptr_record::replacement.
Referenced by AST_TEST_DEFINE(), and sip_resolve_handle_naptr().
 {
    struct ast_dns_naptr_record *naptr = (struct ast_dns_naptr_record *) record;
    ast_assert(ast_dns_record_get_rr_type(record) == T_NAPTR);
    return naptr->replacement;
 }
ast_dns_naptr_get_service()
const char* ast_dns_naptr_get_service (const struct ast_dns_record * record)
Get the service from a NAPTR record.
Parameters
record The DNS record
Returns
the service
Definition at line 608 of file dns_naptr.c.
References ast_assert, ast_dns_record_get_rr_type(), and ast_dns_naptr_record::service.
Referenced by AST_TEST_DEFINE(), and sip_resolve_handle_naptr().
 {
    struct ast_dns_naptr_record *naptr = (struct ast_dns_naptr_record *) record;
    ast_assert(ast_dns_record_get_rr_type(record) == T_NAPTR);
    return naptr->service;
 }