Asterisk - The Open Source Telephony Project: AsteriskProcessor Class Reference
AsteriskProcessor Class Reference
Public Member Functions
def __init__ (self, wiki_prefix)
def process_api (self, api, context)
def process_model (self, model, context)
def process_operation (self, operation, context)
def process_parameter (self, parameter, context)
def process_property (self, prop, context)
def process_resource_api (self, resource_api, context)
def process_type (self, swagger_type, context)
Public Member Functions inherited from SwaggerPostProcessor
def process_api (self, api, context)
def process_model (self, model, context)
def process_operation (self, operation, context)
def process_parameter (self, parameter, context)
def process_property (self, property, context)
def process_resource_api (self, resource_api, context)
def process_resource_listing (self, resource_listing, context)
def process_type (self, swagger_type, context)
Data Fields
wiki_prefix
Static Public Attributes
dictionary convert_mapping
dictionary json_convert_mapping
dictionary type_mapping
Detailed Description
A SwaggerPostProcessor which adds fields needed to generate Asterisk
RESTful HTTP binding code.
Definition at line 127 of file asterisk_processor.py.
Constructor & Destructor Documentation
__init__()
def __init__ (self, wiki_prefix)
Definition at line 161 of file asterisk_processor.py.
     def __init__(self, wiki_prefix):
         self.wiki_prefix = wiki_prefix
Member Function Documentation
process_api()
def process_api (self, api, context)
Definition at line 194 of file asterisk_processor.py.
References asterisk_processor.wikify().
     def process_api(self, api, context):
         api.wiki_path = wikify(api.path)
process_model()
def process_model (self, model, context)
Definition at line 236 of file asterisk_processor.py.
References asterisk_processor.snakify(), and asterisk_processor.wikify().
     def process_model(self, model, context):
         model.description_dox = model.description.replace('\n', '\n * ')
         model.description_dox = re.sub(' *\n', '\n', model.description_dox)
         model.wiki_description = wikify(model.description)
         model.c_id = snakify(model.id)
         return model
process_operation()
def process_operation (self, operation, context)
Definition at line 197 of file asterisk_processor.py.
References asterisk_processor.snakify(), and asterisk_processor.wikify().
     def process_operation(self, operation, context):
         # Nicknames are camelCase, Asterisk coding is snake case
         operation.c_nickname = snakify(operation.nickname)
         operation.c_http_method = 'AST_HTTP_' + operation.http_method
         if not operation.summary.endswith("."):
             raise SwaggerError("Summary should end with .", context)
         operation.wiki_summary = wikify(operation.summary or "")
         operation.wiki_notes = wikify(operation.notes or "")
         for error_response in operation.error_responses:
             error_response.wiki_reason = wikify(error_response.reason or "")
         operation.parse_body = (operation.body_parameter or operation.has_query_parameters) and True
process_parameter()
def process_parameter (self, parameter, context)
Definition at line 209 of file asterisk_processor.py.
References AsteriskProcessor.convert_mapping, AsteriskProcessor.json_convert_mapping, asterisk_processor.snakify(), AsteriskProcessor.type_mapping, and asterisk_processor.wikify().
     def process_parameter(self, parameter, context):
         if parameter.param_type == 'body':
             parameter.is_body_parameter = True;
             parameter.c_data_type = 'struct ast_json *'
         else:
             parameter.is_body_parameter = False;
             if not parameter.data_type in self.type_mapping:
                 raise SwaggerError(
                     "Invalid parameter type %s" % parameter.data_type, context)
             # Type conversions
             parameter.c_data_type = self.type_mapping[parameter.data_type]
             parameter.c_convert = self.convert_mapping[parameter.data_type]
             parameter.json_convert = self.json_convert_mapping[parameter.data_type]
         # Parameter names are camelcase, Asterisk convention is snake case
         parameter.c_name = snakify(parameter.name)
         # You shouldn't put a space between 'char *' and the variable
         if parameter.c_data_type.endswith('*'):
             parameter.c_space = ''
         else:
             parameter.c_space = ' '
         parameter.wiki_description = wikify(parameter.description)
         if parameter.allowable_values:
             parameter.wiki_allowable_values = parameter.allowable_values.to_wiki()
         else:
             parameter.wiki_allowable_values = None
process_property()
def process_property (self, prop, context)
Definition at line 243 of file asterisk_processor.py.
References asterisk_processor.wikify().
     def process_property(self, prop, context):
         if "-" in prop.name:
             raise SwaggerError("Property names cannot have dashes", context)
         if prop.name != prop.name.lower():
             raise SwaggerError("Property name should be all lowercase",
                                context)
         prop.wiki_description = wikify(prop.description)
process_resource_api()
def process_resource_api (self, resource_api, context)
Definition at line 164 of file asterisk_processor.py.
References asterisk_processor.snakify(), and AsteriskProcessor.wiki_prefix.
     def process_resource_api(self, resource_api, context):
         resource_api.wiki_prefix = self.wiki_prefix
         # Derive a resource name from the API declaration's filename
         resource_api.name = re.sub('\..*', '',
                                    os.path.basename(resource_api.path))
         # Now in all caps, for include guard
         resource_api.name_caps = resource_api.name.upper()
         resource_api.name_title = resource_api.name.capitalize()
         resource_api.c_name = snakify(resource_api.name)
         # Construct the PathSegement tree for the API.
         if resource_api.api_declaration:
             resource_api.root_path = PathSegment('', None)
             for api in resource_api.api_declaration.apis:
                 segment = resource_api.root_path.get_child(api.path.split('/'))
                 for operation in api.operations:
                     segment.operations.append(operation)
                 api.full_name = segment.full_name
             # Since every API path should start with /[resource], root should
             # have exactly one child.
             if resource_api.root_path.num_children() != 1:
                 raise SwaggerError(
                     "Should not mix resources in one API declaration", context)
             # root_path isn't needed any more
             resource_api.root_path = list(resource_api.root_path.children())[0]
             if resource_api.name != resource_api.root_path.name:
                 raise SwaggerError(
                     "API declaration name should match", context)
             resource_api.root_full_name = resource_api.root_path.full_name
process_type()
def process_type (self, swagger_type, context)
Definition at line 251 of file asterisk_processor.py.
References asterisk_processor.snakify(), and asterisk_processor.wikify().
     def process_type(self, swagger_type, context):
         swagger_type.c_name = snakify(swagger_type.name)
         swagger_type.c_singular_name = snakify(swagger_type.singular_name)
         swagger_type.wiki_name = wikify(swagger_type.name)
Field Documentation
convert_mapping
dictionary convert_mapping static
Definition at line 144 of file asterisk_processor.py.
Referenced by AsteriskProcessor.process_parameter().
json_convert_mapping
dictionary json_convert_mapping static
Definition at line 153 of file asterisk_processor.py.
Referenced by AsteriskProcessor.process_parameter().
type_mapping
dictionary type_mapping static
Definition at line 133 of file asterisk_processor.py.
Referenced by AsteriskProcessor.process_parameter().
wiki_prefix
wiki_prefix
Definition at line 162 of file asterisk_processor.py.
Referenced by AsteriskProcessor.process_resource_api().
The documentation for this class was generated from the following file:
asterisk_processor.py