Asterisk - The Open Source Telephony Project: privacy.h File Reference
privacy.h File Reference
Persistant data storage (akin to *doze registry)
Macros
#define AST_PRIVACY_ALLOW (1 << 1) /* Pass directly to me */
#define AST_PRIVACY_DENY (1 << 0) /* Don't bother ringing, send to voicemail */
#define AST_PRIVACY_KILL (1 << 2) /* Play anti-telemarketer message and hangup */
#define AST_PRIVACY_TORTURE (1 << 3) /* Send directly to tele-torture */
#define AST_PRIVACY_UNKNOWN (1 << 16)
Functions
int ast_privacy_check (char *dest, char *cid)
int ast_privacy_reset (char *dest)
int ast_privacy_set (char *dest, char *cid, int status)
Detailed Description
Persistant data storage (akin to *doze registry)
Definition in file privacy.h.
Macro Definition Documentation
AST_PRIVACY_ALLOW
#define AST_PRIVACY_ALLOW (1 << 1) /* Pass directly to me */
Definition at line 31 of file privacy.h.
Referenced by ast_privacy_check(), ast_privacy_set(), setup_privacy_args(), and valid_priv_reply().
AST_PRIVACY_DENY
#define AST_PRIVACY_DENY (1 << 0) /* Don't bother ringing, send to voicemail */
Definition at line 30 of file privacy.h.
Referenced by ast_privacy_check(), ast_privacy_set(), setup_privacy_args(), and valid_priv_reply().
AST_PRIVACY_KILL
#define AST_PRIVACY_KILL (1 << 2) /* Play anti-telemarketer message and hangup */
Definition at line 32 of file privacy.h.
Referenced by ast_privacy_check(), ast_privacy_set(), setup_privacy_args(), and valid_priv_reply().
AST_PRIVACY_TORTURE
#define AST_PRIVACY_TORTURE (1 << 3) /* Send directly to tele-torture */
Definition at line 33 of file privacy.h.
Referenced by ast_privacy_check(), ast_privacy_set(), setup_privacy_args(), and valid_priv_reply().
AST_PRIVACY_UNKNOWN
#define AST_PRIVACY_UNKNOWN (1 << 16)
Definition at line 34 of file privacy.h.
Referenced by ast_privacy_check(), ast_privacy_set(), dial_exec_full(), and setup_privacy_args().
Function Documentation
ast_privacy_check()
int ast_privacy_check (char * dest, char * cid)
Definition at line 46 of file privacy.c.
References ast_callerid_parse(), ast_copy_string(), ast_db_get(), AST_PRIVACY_ALLOW, AST_PRIVACY_DENY, AST_PRIVACY_KILL, AST_PRIVACY_TORTURE, AST_PRIVACY_UNKNOWN, ast_shrink_phone_number(), result, and tmp().
Referenced by setup_privacy_args().
 {
    char tmp[256] = "";
    char *trimcid = "";
    char *n, *l;
    int res;
    char key[256], result[256];
    if (cid)
       ast_copy_string(tmp, cid, sizeof(tmp));
    ast_callerid_parse(tmp, &n, &l);
    if (l) {
       ast_shrink_phone_number(l);
       trimcid = l;
    }
    snprintf(key, sizeof(key), "%s/%s", dest, trimcid);
    res = ast_db_get("privacy", key, result, sizeof(result));
    if (!res) {
       if (!strcasecmp(result, "allow"))
          return AST_PRIVACY_ALLOW;
       if (!strcasecmp(result, "deny"))
          return AST_PRIVACY_DENY;
       if (!strcasecmp(result, "kill"))
          return AST_PRIVACY_KILL;
       if (!strcasecmp(result, "torture"))
          return AST_PRIVACY_TORTURE;
    }
    return AST_PRIVACY_UNKNOWN;
 }
ast_privacy_reset()
int ast_privacy_reset (char * dest)
Definition at line 75 of file privacy.c.
References ast_db_deltree().
 {
    if (!dest)
       return -1;
    return ast_db_deltree("privacy", dest);
 }
ast_privacy_set()
int ast_privacy_set (char * dest, char * cid, int status)
Definition at line 82 of file privacy.c.
References ast_callerid_parse(), ast_copy_string(), ast_db_del(), ast_db_put(), AST_PRIVACY_ALLOW, AST_PRIVACY_DENY, AST_PRIVACY_KILL, AST_PRIVACY_TORTURE, AST_PRIVACY_UNKNOWN, ast_shrink_phone_number(), ast_strlen_zero, and tmp().
Referenced by valid_priv_reply().
 {
    char tmp[256] = "";
    char *trimcid = "";
    char *n, *l;
    int res;
    char key[256];
    if (cid)
       ast_copy_string(tmp, cid, sizeof(tmp));
    ast_callerid_parse(tmp, &n, &l);
    if (l) {
       ast_shrink_phone_number(l);
       trimcid = l;
    }
    if (ast_strlen_zero(trimcid)) {
       /* Don't store anything for empty Caller*ID */
       return 0;
    }
    snprintf(key, sizeof(key), "%s/%s", dest, trimcid);
    if (status == AST_PRIVACY_UNKNOWN)
       res = ast_db_del("privacy", key);
    else if (status == AST_PRIVACY_ALLOW)
       res = ast_db_put("privacy", key, "allow");
    else if (status == AST_PRIVACY_DENY)
       res = ast_db_put("privacy", key, "deny");
    else if (status == AST_PRIVACY_KILL)
       res = ast_db_put("privacy", key, "kill");
    else if (status == AST_PRIVACY_TORTURE)
       res = ast_db_put("privacy", key, "torture");
    else
       res = -1;
    return res;
 }