Asterisk - The Open Source Telephony Project: func_periodic_hook.c File Reference
func_periodic_hook.c File Reference
Module: Dial plan functions
Periodic dialplan hooks.
#include "asterisk.h"
#include "asterisk/module.h"
#include "asterisk/channel.h"
#include "asterisk/pbx.h"
#include "asterisk/app.h"
#include "asterisk/audiohook.h"
#include "asterisk/beep.h"
Data Structures
struct hook_state
struct hook_thread_arg
Macros
#define AST_API_MODULE
Functions
static void __reg_module (void)
static void __unreg_module (void)
int AST_OPTIONAL_API_NAME() ast_beep_start (struct ast_channel *chan, unsigned int interval, char *beep_id, size_t len)
int AST_OPTIONAL_API_NAME() ast_beep_stop (struct ast_channel *chan, const char *beep_id)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int do_hook (struct ast_channel *chan, struct hook_state *state)
static int hook_callback (struct ast_audiohook *audiohook, struct ast_channel *chan, struct ast_frame *frame, enum ast_audiohook_direction direction)
static void hook_datastore_destroy_callback (void *data)
static void * hook_launch_thread (void *data)
static int hook_off (struct ast_channel *chan, const char *hook_id)
static int hook_on (struct ast_channel *chan, const char *data, unsigned int hook_id)
static int hook_re_enable (struct ast_channel *chan, const char *uid)
static int hook_read (struct ast_channel *chan, const char *cmd, char *data, char *buf, size_t len)
static struct hook_state * hook_state_alloc (const char *context, const char *exten, unsigned int interval, unsigned int hook_id)
static struct hook_thread_arg * hook_thread_arg_alloc (struct ast_channel *chan, struct hook_state *state)
static void hook_thread_arg_destroy (struct hook_thread_arg *arg)
static int hook_write (struct ast_channel *chan, const char *cmd, char *data, const char *value)
static int init_hook (struct ast_channel *chan, const char *context, const char *exten, unsigned int interval, unsigned int hook_id)
static int load_module (void)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_GLOBAL_SYMBOLS , .description = "Periodic dialplan hooks." , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .requires = "app_chanspy,func_cut,func_groupcount,func_uri", }
static const struct ast_module_info * ast_module_info = &__mod_info
static const char beep_exten [] = "beep"
static const char context_name [] = "__func_periodic_hook_context__"
static const char exten_name [] = "hook"
static const char full_exten_name [] = "hook@__func_periodic_hook_context__"
static unsigned int global_hook_id
Last used hook ID.
static const struct ast_datastore_info hook_datastore
static struct ast_custom_function hook_function
Detailed Description
Periodic dialplan hooks.
Author
Russell Bryant russe.nosp@m.ll@r.nosp@m.ussel.nosp@m.lbry.nosp@m.ant.n.nosp@m.et
Definition in file func_periodic_hook.c.
Macro Definition Documentation
AST_API_MODULE
#define AST_API_MODULE
Definition at line 43 of file func_periodic_hook.c.
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 523 of file func_periodic_hook.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 523 of file func_periodic_hook.c.
ast_beep_start()
int AST_OPTIONAL_API_NAME() ast_beep_start (struct ast_channel * chan, unsigned int interval, char * beep_id, size_t len)
Definition at line 497 of file func_periodic_hook.c.
References args, ast_log, AST_MAX_CONTEXT, AST_MAX_EXTENSION, beep_exten, context_name, hook_read(), hook_state::interval, len(), LOG_WARNING, and NULL.
Referenced by mixmonitor_exec(), and start_monitor_exec().
 {
    char args[AST_MAX_EXTENSION + AST_MAX_CONTEXT + 32];
    snprintf(args, sizeof(args), "%s,%s,%u",
          context_name, beep_exten, interval);
    if (hook_read(chan, NULL, args, beep_id, len)) {
       ast_log(LOG_WARNING, "Failed to enable periodic beep.\n");
       return -1;
    }
    return 0;
 }
ast_beep_stop()
int AST_OPTIONAL_API_NAME() ast_beep_stop (struct ast_channel * chan, const char * beep_id)
Definition at line 513 of file func_periodic_hook.c.
References AST_MODFLAG_GLOBAL_SYMBOLS, AST_MODULE_INFO(), AST_MODULE_SUPPORT_CORE, ASTERISK_GPL_KEY, hook_write(), load_module(), NULL, and unload_module().
Referenced by __stub__ast_beep_start(), ast_monitor_stop(), and stop_mixmonitor_full().
 {
    return hook_write(chan, NULL, (char *) beep_id, "off");
 }
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 523 of file func_periodic_hook.c.
do_hook()
static int do_hook (struct ast_channel * chan, struct hook_state * state) static
Definition at line 225 of file func_periodic_hook.c.
References ast_pthread_create_detached_background, hook_launch_thread(), hook_thread_arg_alloc(), hook_thread_arg_destroy(), and NULL.
Referenced by hook_callback().
 {
    pthread_t t;
    struct hook_thread_arg *arg;
    int res;
    if (!(arg = hook_thread_arg_alloc(chan, state))) {
       return -1;
    }
    /*
     * We don't want to block normal frame processing *at all* while we kick
     * this off, so do it in a new thread.
     */
    res = ast_pthread_create_detached_background(&t, NULL, hook_launch_thread, arg);
    if (res != 0) {
       hook_thread_arg_destroy(arg);
    }
    return res;
 }
hook_callback()
static int hook_callback (struct ast_audiohook * audiohook, struct ast_channel * chan, struct ast_frame * frame, enum ast_audiohook_direction direction) static
Definition at line 247 of file func_periodic_hook.c.
References AST_AUDIOHOOK_STATUS_DONE, ast_channel_lock, ast_channel_name(), ast_channel_unlock, ast_log, ast_strdupa, ast_tvdiff_ms(), ast_tvnow(), hook_state::disabled, do_hook(), hook_state::interval, hook_state::last_hook, LOG_WARNING, name, and ast_audiohook::status.
Referenced by hook_state_alloc().
 {
    struct hook_state *state = (struct hook_state *) audiohook; /* trust me. */
    struct timeval now;
    int res = 0;
    if (audiohook->status == AST_AUDIOHOOK_STATUS_DONE || state->disabled) {
       return 0;
    }
    now = ast_tvnow();
    if (ast_tvdiff_ms(now, state->last_hook) > state->interval * 1000) {
       if ((res = do_hook(chan, state))) {
          const char *name;
          ast_channel_lock(chan);
          name = ast_strdupa(ast_channel_name(chan));
          ast_channel_unlock(chan);
          ast_log(LOG_WARNING, "Failed to run hook on '%s'\n", name);
       }
       state->last_hook = now;
    }
    return res;
 }
hook_datastore_destroy_callback()
static void hook_datastore_destroy_callback (void * data) static
Definition at line 128 of file func_periodic_hook.c.
References ast_audiohook_destroy(), ast_audiohook_detach(), ast_audiohook_lock, ast_audiohook_unlock, ast_free, hook_state::audiohook, hook_state::context, and hook_state::exten.
 {
    struct hook_state *state = data;
    ast_audiohook_lock(&state->audiohook);
    ast_audiohook_detach(&state->audiohook);
    ast_audiohook_unlock(&state->audiohook);
    ast_audiohook_destroy(&state->audiohook);
    ast_free(state->context);
    ast_free(state->exten);
    ast_free(state);
 }
hook_launch_thread()
static void* hook_launch_thread (void * data) static
Definition at line 168 of file func_periodic_hook.c.
References AST_OUTGOING_NO_WAIT, ast_pbx_outgoing_exten(), hook_thread_arg::chan_name, hook_thread_arg::context, hook_thread_arg::exten, full_exten_name, hook_state::hook_id, hook_thread_arg::hook_id, hook_thread_arg_destroy(), ast_variable::name, and NULL.
Referenced by do_hook().
 {
    struct hook_thread_arg *arg = data;
    struct ast_variable hook_id = {
       .name = "HOOK_ID",
       .value = arg->hook_id,
    };
    struct ast_variable chan_name_var = {
       .name = "HOOK_CHANNEL",
       .value = arg->chan_name,
       .next = &hook_id,
    };
    ast_pbx_outgoing_exten("Local", NULL, full_exten_name, 60,
          arg->context, arg->exten, 1, NULL, AST_OUTGOING_NO_WAIT,
          NULL, NULL, &chan_name_var, NULL, NULL, 1, NULL);
    hook_thread_arg_destroy(arg);
    return NULL;
 }
hook_off()
static int hook_off (struct ast_channel * chan, const char * hook_id) static
Definition at line 350 of file func_periodic_hook.c.
References ast_channel_datastore_find(), ast_channel_lock, ast_channel_name(), ast_channel_unlock, ast_log, ast_strlen_zero, ast_datastore::data, hook_state::disabled, LOG_WARNING, and state.
Referenced by hook_write().
 {
    struct ast_datastore *datastore;
    struct hook_state *state;
    if (ast_strlen_zero(hook_id)) {
       return -1;
    }
    ast_channel_lock(chan);
    if (!(datastore = ast_channel_datastore_find(chan, &hook_datastore, hook_id))) {
       ast_log(LOG_WARNING, "Hook with ID '%s' not found on channel '%s'\n", hook_id,
             ast_channel_name(chan));
       ast_channel_unlock(chan);
       return -1;
    }
    state = datastore->data;
    state->disabled = 1;
    ast_channel_unlock(chan);
    return 0;
 }
hook_on()
static int hook_on (struct ast_channel * chan, const char * data, unsigned int hook_id) static
Definition at line 321 of file func_periodic_hook.c.
References args, AST_APP_ARG, ast_channel_name(), ast_debug, AST_DECLARE_APP_ARGS, ast_log, AST_STANDARD_APP_ARGS, ast_strdupa, ast_strlen_zero, hook_state::context, hook_state::exten, init_hook(), hook_state::interval, LOG_WARNING, parse(), and S_OR.
Referenced by hook_read().
 {
    char *parse = ast_strdupa(S_OR(data, ""));
    AST_DECLARE_APP_ARGS(args,
       AST_APP_ARG(context);
       AST_APP_ARG(exten);
       AST_APP_ARG(interval);
    );
    unsigned int interval;
    AST_STANDARD_APP_ARGS(args, parse);
    if (ast_strlen_zero(args.interval) ||
          sscanf(args.interval, "%30u", &interval) != 1 || interval == 0) {
       ast_log(LOG_WARNING, "Invalid hook interval: '%s'\n", S_OR(args.interval, ""));
       return -1;
    }
    if (ast_strlen_zero(args.context) || ast_strlen_zero(args.exten)) {
       ast_log(LOG_WARNING, "A context and extension are required for PERIODIC_HOOK().\n");
       return -1;
    }
    ast_debug(1, "hook to %s@%s enabled on %s with interval of %u seconds\n",
          args.exten, args.context, ast_channel_name(chan), interval);
    return init_hook(chan, args.context, args.exten, interval, hook_id);
 }
hook_re_enable()
static int hook_re_enable (struct ast_channel * chan, const char * uid) static
Definition at line 392 of file func_periodic_hook.c.
References ast_channel_datastore_find(), ast_channel_lock, ast_channel_name(), ast_channel_unlock, ast_log, ast_strlen_zero, ast_datastore::data, hook_state::disabled, LOG_WARNING, and state.
Referenced by hook_write().
 {
    struct ast_datastore *datastore;
    struct hook_state *state;
    if (ast_strlen_zero(uid)) {
       return -1;
    }
    ast_channel_lock(chan);
    if (!(datastore = ast_channel_datastore_find(chan, &hook_datastore, uid))) {
       ast_log(LOG_WARNING, "Hook with ID '%s' not found on '%s'\n",
             uid, ast_channel_name(chan));
       ast_channel_unlock(chan);
       return -1;
    }
    state = datastore->data;
    state->disabled = 0;
    ast_channel_unlock(chan);
    return 0;
 }
hook_read()
static int hook_read (struct ast_channel * chan, const char * cmd, char * data, char * buf, size_t len) static
Definition at line 376 of file func_periodic_hook.c.
References ast_atomic_fetchadd_int(), global_hook_id, hook_state::hook_id, and hook_on().
Referenced by ast_beep_start().
 {
    unsigned int hook_id;
    if (!chan) {
       return -1;
    }
    hook_id = (unsigned int) ast_atomic_fetchadd_int((int *) &global_hook_id, 1);
    snprintf(buf, len, "%u", hook_id);
    return hook_on(chan, data, hook_id);
 }
hook_state_alloc()
static struct hook_state* hook_state_alloc (const char * context, const char * exten, unsigned int interval, unsigned int hook_id) static
Definition at line 273 of file func_periodic_hook.c.
References ast_audiohook_init(), AST_AUDIOHOOK_MANIPULATE_ALL_RATES, AST_AUDIOHOOK_TYPE_MANIPULATE, ast_calloc, AST_MODULE, ast_strdup, hook_state::audiohook, hook_state::context, hook_state::exten, hook_callback(), hook_state::hook_id, hook_state::interval, ast_audiohook::manipulate_callback, NULL, and state.
Referenced by init_hook().
 {
    struct hook_state *state;
    if (!(state = ast_calloc(1, sizeof(*state)))) {
       return NULL;
    }
    state->context = ast_strdup(context);
    state->exten = ast_strdup(exten);
    state->interval = interval;
    state->hook_id = hook_id;
    ast_audiohook_init(&state->audiohook, AST_AUDIOHOOK_TYPE_MANIPULATE,
          AST_MODULE, AST_AUDIOHOOK_MANIPULATE_ALL_RATES);
    state->audiohook.manipulate_callback = hook_callback;
    return state;
 }
hook_thread_arg_alloc()
static struct hook_thread_arg* hook_thread_arg_alloc (struct ast_channel * chan, struct hook_state * state) static
Definition at line 190 of file func_periodic_hook.c.
References ast_asprintf, ast_calloc, ast_channel_lock, ast_channel_name(), ast_channel_unlock, ast_strdup, hook_thread_arg::chan_name, hook_state::context, hook_thread_arg::context, hook_state::exten, hook_thread_arg::exten, hook_state::hook_id, hook_thread_arg::hook_id, hook_thread_arg_destroy(), and NULL.
Referenced by do_hook().
 {
    struct hook_thread_arg *arg;
    if (!(arg = ast_calloc(1, sizeof(*arg)))) {
       return NULL;
    }
    ast_channel_lock(chan);
    arg->chan_name = ast_strdup(ast_channel_name(chan));
    ast_channel_unlock(chan);
    if (!arg->chan_name) {
       hook_thread_arg_destroy(arg);
       return NULL;
    }
    if (ast_asprintf(&arg->hook_id, "%u", state->hook_id) == -1) {
       hook_thread_arg_destroy(arg);
       return NULL;
    }
    if (!(arg->context = ast_strdup(state->context))) {
       hook_thread_arg_destroy(arg);
       return NULL;
    }
    if (!(arg->exten = ast_strdup(state->exten))) {
       hook_thread_arg_destroy(arg);
       return NULL;
    }
    return arg;
 }
hook_thread_arg_destroy()
static void hook_thread_arg_destroy (struct hook_thread_arg * arg) static
Definition at line 159 of file func_periodic_hook.c.
References ast_free, hook_thread_arg::chan_name, hook_thread_arg::context, hook_thread_arg::exten, and hook_thread_arg::hook_id.
Referenced by do_hook(), hook_launch_thread(), and hook_thread_arg_alloc().
 {
    ast_free(arg->hook_id);
    ast_free(arg->chan_name);
    ast_free(arg->context);
    ast_free(arg->exten);
    ast_free(arg);
 }
hook_write()
static int hook_write (struct ast_channel * chan, const char * cmd, char * data, const char * value) static
Definition at line 418 of file func_periodic_hook.c.
References ast_false(), ast_log, ast_true(), hook_off(), hook_re_enable(), and LOG_WARNING.
Referenced by ast_beep_stop().
 {
    int res;
    if (!chan) {
       return -1;
    }
    if (ast_false(value)) {
       res = hook_off(chan, data);
    } else if (ast_true(value)) {
       res = hook_re_enable(chan, data);
    } else {
       ast_log(LOG_WARNING, "Invalid value for PERIODIC_HOOK function: '%s'\n", value);
       res = -1;
    }
    return res;
 }
init_hook()
static int init_hook (struct ast_channel * chan, const char * context, const char * exten, unsigned int interval, unsigned int hook_id) static
Definition at line 294 of file func_periodic_hook.c.
References ast_audiohook_attach(), ast_channel_datastore_add(), ast_channel_lock, ast_channel_unlock, ast_datastore_alloc, ast_datastore_free(), hook_state::audiohook, ast_datastore::data, hook_state_alloc(), state, and ast_datastore::uid.
Referenced by hook_on().
 {
    struct hook_state *state;
    struct ast_datastore *datastore;
    char uid[32];
    snprintf(uid, sizeof(uid), "%u", hook_id);
    if (!(datastore = ast_datastore_alloc(&hook_datastore, uid))) {
       return -1;
    }
    if (!(state = hook_state_alloc(context, exten, interval, hook_id))) {
       ast_datastore_free(datastore);
       return -1;
    }
    datastore->data = state;
    ast_channel_lock(chan);
    ast_channel_datastore_add(chan, datastore);
    ast_audiohook_attach(chan, &state->audiohook);
    ast_channel_unlock(chan);
    return 0;
 }
load_module()
static int load_module (void) static
Definition at line 453 of file func_periodic_hook.c.
References ast_add_extension(), AST_CFE_BOTH, ast_context_find_or_create(), ast_custom_function_register_escalating, ast_log, AST_MODULE, AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, beep_exten, context_name, exten_name, LOG_ERROR, NULL, and unload_module().
Referenced by ast_beep_stop().
 {
    int res;
    if (!ast_context_find_or_create(NULL, NULL, context_name, AST_MODULE)) {
       ast_log(LOG_ERROR, "Failed to create %s dialplan context.\n", context_name);
       return AST_MODULE_LOAD_DECLINE;
    }
    /*
     * Based on a handy recipe from the Asterisk Cookbook.
     */
    res = ast_add_extension(context_name, 1, exten_name, 1, "", "",
          "Set", "EncodedChannel=${CUT(HOOK_CHANNEL,-,1-2)}",
          NULL, AST_MODULE);
    res |= ast_add_extension(context_name, 1, exten_name, 2, "", "",
          "Set", "GROUP_NAME=${EncodedChannel}${HOOK_ID}",
          NULL, AST_MODULE);
    res |= ast_add_extension(context_name, 1, exten_name, 3, "", "",
          "Set", "GROUP(periodic-hook)=${GROUP_NAME}",
          NULL, AST_MODULE);
    res |= ast_add_extension(context_name, 1, exten_name, 4, "", "", "ExecIf",
          "$[${GROUP_COUNT(${GROUP_NAME}@periodic-hook)} > 1]?Hangup()",
          NULL, AST_MODULE);
    res |= ast_add_extension(context_name, 1, exten_name, 5, "", "",
          "Set", "ChannelToSpy=${URIDECODE(${EncodedChannel})}",
          NULL, AST_MODULE);
    res |= ast_add_extension(context_name, 1, exten_name, 6, "", "",
          "ChanSpy", "${ChannelToSpy},qEB", NULL, AST_MODULE);
    res |= ast_add_extension(context_name, 1, beep_exten, 1, "", "",
          "Answer", "", NULL, AST_MODULE);
    res |= ast_add_extension(context_name, 1, beep_exten, 2, "", "",
          "Playback", "beep", NULL, AST_MODULE);
    res |= ast_custom_function_register_escalating(&hook_function, AST_CFE_BOTH);
    if (res) {
       unload_module();
       return AST_MODULE_LOAD_DECLINE;
    }
    return AST_MODULE_LOAD_SUCCESS;
 }
unload_module()
static int unload_module (void) static
Definition at line 445 of file func_periodic_hook.c.
References ast_context_destroy(), ast_custom_function_unregister(), AST_MODULE, and NULL.
Referenced by ast_beep_stop(), and load_module().
 {
    ast_context_destroy(NULL, AST_MODULE);
    ast_custom_function_unregister(&hook_function);
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_GLOBAL_SYMBOLS , .description = "Periodic dialplan hooks." , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .requires = "app_chanspy,func_cut,func_groupcount,func_uri", } static
Definition at line 523 of file func_periodic_hook.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 523 of file func_periodic_hook.c.
beep_exten
const char beep_exten[] = "beep" static
Definition at line 96 of file func_periodic_hook.c.
Referenced by ast_beep_start(), and load_module().
context_name
const char context_name[] = "__func_periodic_hook_context__" static
Definition at line 92 of file func_periodic_hook.c.
Referenced by add_extension(), app_create(), app_dtor(), ast_beep_start(), device_state_notify_callbacks(), load_module(), lua_register_hints(), lua_register_switches(), lua_sort_extensions(), and presence_state_notify_callbacks().
exten_name
const char exten_name[] = "hook" static
Definition at line 93 of file func_periodic_hook.c.
Referenced by device_state_notify_callbacks(), hint_hash(), load_module(), and presence_state_notify_callbacks().
full_exten_name
const char full_exten_name[] = "hook@__func_periodic_hook_context__" static
Definition at line 94 of file func_periodic_hook.c.
Referenced by hook_launch_thread().
global_hook_id
unsigned int global_hook_id static
Last used hook ID.
This is incremented each time a hook is created to give each hook a unique ID.
Definition at line 104 of file func_periodic_hook.c.
Referenced by hook_read().
hook_datastore
const struct ast_datastore_info hook_datastore static
Initial value:
= {
   .type = AST_MODULE,
   .destroy = hook_datastore_destroy_callback,
}
Definition at line 142 of file func_periodic_hook.c.
hook_function
struct ast_custom_function hook_function static
Initial value:
= {
   .name = "PERIODIC_HOOK",
   .read = hook_read,
   .write = hook_write,
}
Definition at line 439 of file func_periodic_hook.c.