Asterisk - The Open Source Telephony Project: dnsmgr.h File Reference
dnsmgr.h File Reference
Background DNS update manager.
#include "asterisk/netsock2.h"
#include "asterisk/srv.h"
Typedefs
typedef void(* dns_update_func) (struct ast_sockaddr *old_addr, struct ast_sockaddr *new_addr, void *data)
Functions
int ast_dnsmgr_changed (struct ast_dnsmgr_entry *entry)
Check is see if a dnsmgr entry has changed.
struct ast_dnsmgr_entry * ast_dnsmgr_get (const char *name, struct ast_sockaddr *result, const char *service)
Allocate a new DNS manager entry.
struct ast_dnsmgr_entry * ast_dnsmgr_get_family (const char *name, struct ast_sockaddr *result, const char *service, unsigned int family)
Allocate a new DNS manager entry.
int ast_dnsmgr_lookup (const char *name, struct ast_sockaddr *result, struct ast_dnsmgr_entry **dnsmgr, const char *service)
Allocate and initialize a DNS manager entry.
int ast_dnsmgr_lookup_cb (const char *name, struct ast_sockaddr *result, struct ast_dnsmgr_entry **dnsmgr, const char *service, dns_update_func func, void *data)
Allocate and initialize a DNS manager entry, with update callback.
int ast_dnsmgr_refresh (struct ast_dnsmgr_entry *entry)
Force a refresh of a dnsmgr entry.
void ast_dnsmgr_release (struct ast_dnsmgr_entry *entry)
Free a DNS manager entry.
Detailed Description
Background DNS update manager.
Definition in file dnsmgr.h.
Typedef Documentation
dns_update_func
typedef void(* dns_update_func) (struct ast_sockaddr *old_addr, struct ast_sockaddr *new_addr, void *data)
Definition at line 40 of file dnsmgr.h.
Function Documentation
ast_dnsmgr_changed()
int ast_dnsmgr_changed (struct ast_dnsmgr_entry * entry)
Check is see if a dnsmgr entry has changed.
Return values
non-zero if the dnsmgr entry has changed since the last call to this function
zero if the dnsmgr entry has not changed since the last call to this function
Definition at line 247 of file dnsmgr.c.
References ast_mutex_lock, ast_mutex_unlock, ast_dnsmgr_entry::changed, and ast_dnsmgr_entry::lock.
Referenced by iax2_do_register().
 {
    int changed;
    ast_mutex_lock(&entry->lock);
    changed = entry->changed;
    entry->changed = 0;
    ast_mutex_unlock(&entry->lock);
    return changed;
 }
ast_dnsmgr_get()
struct ast_dnsmgr_entry* ast_dnsmgr_get (const char * name, struct ast_sockaddr * result, const char * service)
Allocate a new DNS manager entry.
Parameters
name the hostname
result where the DNS manager should store the IP address as it refreshes it.
service
This function allocates a new DNS manager entry object, and fills it with the provided hostname and IP address. This function does not force an initial lookup of the IP address. So, generally, this should be used when the initial address is already known.
Returns
a DNS manager entry
Version
1.6.1 result changed from struct in_addr to struct sockaddr_in to store port number
1.8.0 result changed from struct ast_sockaddr_in to ast_sockaddr for IPv6 support
Definition at line 131 of file dnsmgr.c.
References ast_dnsmgr_get_family().
 {
    return ast_dnsmgr_get_family(name, result, service, 0);
 }
ast_dnsmgr_get_family()
struct ast_dnsmgr_entry* ast_dnsmgr_get_family (const char * name, struct ast_sockaddr * result, const char * service, unsigned int family)
Allocate a new DNS manager entry.
Parameters
name the hostname
result where the DNS manager should store the IP address as it refreshes it.
service
family Address family to filter DNS addresses.
This function allocates a new DNS manager entry object, and fills it with the provided hostname and IP address. This function does not force an initial lookup of the IP address. So, generally, this should be used when the initial address is already known.
Returns
a DNS manager entry
Definition at line 106 of file dnsmgr.c.
References ast_calloc, ast_mutex_init, AST_RWLIST_INSERT_HEAD, AST_RWLIST_UNLOCK, AST_RWLIST_WRLOCK, ast_strlen_zero, ast_dnsmgr_entry::family, ast_dnsmgr_entry::lock, NULL, ast_dnsmgr_entry::result, and ast_dnsmgr_entry::service.
Referenced by ast_dnsmgr_get(), and internal_dnsmgr_lookup().
 {
    struct ast_dnsmgr_entry *entry;
    int total_size = sizeof(*entry) + strlen(name) + (service ? strlen(service) + 1 : 0);
    if (!result || ast_strlen_zero(name) || !(entry = ast_calloc(1, total_size))) {
       return NULL;
    }
    entry->result = result;
    ast_mutex_init(&entry->lock);
    strcpy(entry->name, name);
    if (service) {
       entry->service = ((char *) entry) + sizeof(*entry) + strlen(name);
       strcpy(entry->service, service);
    }
    entry->family = family;
    AST_RWLIST_WRLOCK(&entry_list);
    AST_RWLIST_INSERT_HEAD(&entry_list, entry, list);
    AST_RWLIST_UNLOCK(&entry_list);
    return entry;
 }
ast_dnsmgr_lookup()
int ast_dnsmgr_lookup (const char * name, struct ast_sockaddr * result, struct ast_dnsmgr_entry ** dnsmgr, const char * service)
Allocate and initialize a DNS manager entry.
Parameters
name the hostname
result where to store the IP address as the DNS manager refreshes it. The address family is used as an input parameter to filter the returned addresses. If it is 0, both IPv4 and IPv6 addresses can be returned.
dnsmgr Where to store the allocate DNS manager entry
service
Note
This function allocates a new DNS manager entry object, and fills it with the provided hostname and IP address. This function does force an initial lookup, so it may block for some period of time.
Return values
0 success
non-zero failure
Version
1.6.1 result changed from struct in_addr to struct aockaddr_in to store port number
Definition at line 191 of file dnsmgr.c.
References internal_dnsmgr_lookup(), and NULL.
Referenced by __iax2_do_register_s(), build_peer(), iax2_append_register(), and transport_apply().
 {
    return internal_dnsmgr_lookup(name, result, dnsmgr, service, NULL, NULL);
 }
ast_dnsmgr_lookup_cb()
int ast_dnsmgr_lookup_cb (const char * name, struct ast_sockaddr * result, struct ast_dnsmgr_entry ** dnsmgr, const char * service, dns_update_func func, void * data)
Allocate and initialize a DNS manager entry, with update callback.
Parameters
name the hostname
result The addr which is intended to be updated in the update callback when DNS manager calls it on refresh. The address family is used as an input parameter to filter the returned addresses. If it is 0, both IPv4 and IPv6 addresses can be returned.
dnsmgr Where to store the allocate DNS manager entry
service
func The update callback function The update callback will be called when DNS manager detects that an IP address has been changed. Instead of updating the addr itself, DNS manager will call this callback function with the old and new addresses. It is the responsibility of the callback to perform any updates
data A pointer to data that will be passed through to the callback function
Note
This function allocates a new DNS manager entry object, and fills it with the provided hostname and IP address. This function does force an initial lookup, so it may block for some period of time.
Return values
0 success
non-zero failure
Definition at line 196 of file dnsmgr.c.
References internal_dnsmgr_lookup().
Referenced by __sip_subscribe_mwi_do(), build_peer(), and transmit_register().
 {
    return internal_dnsmgr_lookup(name, result, dnsmgr, service, func, data);
 }
ast_dnsmgr_refresh()
int ast_dnsmgr_refresh (struct ast_dnsmgr_entry * entry)
Force a refresh of a dnsmgr entry.
Return values
non-zero if the result is different than the previous result
zero if the result is the same as the previous result
Definition at line 239 of file dnsmgr.c.
References dnsmgr_refresh().
Referenced by build_peer(), iax2_do_register(), and sip_reg_timeout().
 {
    return dnsmgr_refresh(entry, 0);
 }
ast_dnsmgr_release()
void ast_dnsmgr_release (struct ast_dnsmgr_entry * entry)
Free a DNS manager entry.
Parameters
entry the DNS manager entry to free
Returns
nothing
Definition at line 136 of file dnsmgr.c.
References ast_debug, ast_free, ast_mutex_destroy, AST_RWLIST_REMOVE, AST_RWLIST_UNLOCK, AST_RWLIST_WRLOCK, and ast_dnsmgr_entry::lock.
Referenced by __cleanup_registration(), __shutdown_mwi_subscription(), delete_users(), destroy_sip_transport_state(), match_and_cleanup_peer_sched(), and peer_destructor().
 {
    if (!entry) {
       return;
    }
    AST_RWLIST_WRLOCK(&entry_list);
    AST_RWLIST_REMOVE(&entry_list, entry, list);
    AST_RWLIST_UNLOCK(&entry_list);
    ast_debug(6, "removing dns manager for '%s'\n", entry->name);
    ast_mutex_destroy(&entry->lock);
    ast_free(entry);
 }