Asterisk - The Open Source Telephony Project: test_cel.c File Reference
test_cel.c File Reference
CEL unit tests.
#include "asterisk.h"
#include <math.h>
#include "asterisk/module.h"
#include "asterisk/test.h"
#include "asterisk/cel.h"
#include "asterisk/channel.h"
#include "asterisk/format_cache.h"
#include "asterisk/linkedlists.h"
#include "asterisk/chanvars.h"
#include "asterisk/utils.h"
#include "asterisk/causes.h"
#include "asterisk/time.h"
#include "asterisk/bridge.h"
#include "asterisk/bridge_basic.h"
#include "asterisk/pickup.h"
#include "asterisk/stasis_channels.h"
#include "asterisk/stasis_bridges.h"
#include "asterisk/json.h"
#include "asterisk/features.h"
#include "asterisk/core_local.h"
Macros
#define ALICE_CALLERID { .id.name.str = "Alice", .id.name.valid = 1, .id.number.str = "100", .id.number.valid = 1, }
Alice's Caller ID.
#define ANSWER_CHANNEL(chan)
#define ANSWER_NO_APP(chan)
#define APPEND_DUMMY_EVENT()
#define APPEND_EVENT(chan, ev_type, userevent, extra)
#define APPEND_EVENT_PEER(chan, ev_type, userevent, extra, peer)
#define APPEND_EVENT_SNAPSHOT(snapshot, ev_type, userevent, extra, peer)
#define ATTENDEDTRANSFER_BRIDGE(channel1, bridge1, channel2, bridge2, channel3, channel4)
#define BLINDTRANSFER_EVENT(channel, bridge, extension, context)
#define BOB_CALLERID { .id.name.str = "Bob", .id.name.valid = 1, .id.number.str = "200", .id.number.valid = 1, }
Bob's Caller ID.
#define BRIDGE_ENTER(channel, bridge)
#define BRIDGE_ENTER_EVENT(channel, bridge)
#define BRIDGE_ENTER_EVENT_PEER(channel, bridge, peer)
#define BRIDGE_EXIT(channel, bridge)
#define BRIDGE_EXIT_EVENT(channel, bridge)
#define BRIDGE_EXIT_EVENT_PEER(channel, bridge, peer)
#define BRIDGE_EXIT_SNAPSHOT(channel, bridge)
#define CHANNEL_TECH_NAME "CELTestChannel"
#define CHARLIE_CALLERID { .id.name.str = "Charlie", .id.name.valid = 1, .id.number.str = "300", .id.number.valid = 1, }
Charlie's Caller ID.
#define CREATE_ALICE_CHANNEL(channel_var, caller_id)
Create a test_cel_chan_tech for Alice.
#define CREATE_BOB_CHANNEL(channel_var, caller_id)
Create a test_cel_chan_tech for Bob.
#define CREATE_CHARLIE_CHANNEL(channel_var, caller_id)
Create a test_cel_chan_tech for Charlie.
#define CREATE_DAVID_CHANNEL(channel_var, caller_id)
Create a test_cel_chan_tech for David.
#define DAVID_CALLERID { .id.name.str = "David", .id.name.valid = 1, .id.number.str = "400", .id.number.valid = 1, }
David's Caller ID.
#define EMULATE_APP_DATA(channel, priority, application, data)
Emulate a channel entering into an application.
#define EMULATE_DIAL(channel, dialstring)
#define HANGUP_CHANNEL(channel, cause, dialstatus)
Hang up a test channel safely.
#define HANGUP_EVENT(channel, cause, dialstatus)
#define SET_FORMATS(chan)
Set ulaw format on channel.
#define START_DIALED(caller, callee) START_DIALED_FULL(caller, callee, "200", "Bob")
#define START_DIALED_FULL(caller, callee, number, name)
#define TEST_BACKEND_NAME "CEL Test Logging"
#define TEST_CATEGORY "/main/cel/"
Functions
static void __reg_module (void)
static struct ast_str * __test_cel_generate_peer_str (struct ast_channel_snapshot *chan, struct ast_bridge_snapshot *bridge)
static void __unreg_module (void)
static struct ast_event * ao2_dup_event (const struct ast_event *event)
static int append_event (struct ast_event *ev)
static int append_expected_event (struct ast_channel *chan, enum ast_cel_event_type type, const char *userdefevname, struct ast_json *extra, const char *peer)
static int append_expected_event_snapshot (struct ast_channel_snapshot *snapshot, enum ast_cel_event_type type, const char *userdefevname, struct ast_json *extra, const char *peer)
struct ast_module * AST_MODULE_SELF_SYM (void)
AST_TEST_DEFINE (test_cel_channel_creation)
AST_TEST_DEFINE (test_cel_unanswered_inbound_call)
AST_TEST_DEFINE (test_cel_unanswered_outbound_call)
AST_TEST_DEFINE (test_cel_single_party)
AST_TEST_DEFINE (test_cel_single_bridge)
AST_TEST_DEFINE (test_cel_single_bridge_continue)
AST_TEST_DEFINE (test_cel_single_twoparty_bridge_a)
AST_TEST_DEFINE (test_cel_single_twoparty_bridge_b)
AST_TEST_DEFINE (test_cel_dial_unanswered)
AST_TEST_DEFINE (test_cel_dial_unanswered_filter)
AST_TEST_DEFINE (test_cel_dial_busy)
AST_TEST_DEFINE (test_cel_dial_congestion)
AST_TEST_DEFINE (test_cel_dial_unavailable)
AST_TEST_DEFINE (test_cel_dial_caller_cancel)
AST_TEST_DEFINE (test_cel_dial_parallel_failed)
AST_TEST_DEFINE (test_cel_dial_answer_no_bridge)
AST_TEST_DEFINE (test_cel_dial_answer_twoparty_bridge_a)
AST_TEST_DEFINE (test_cel_dial_answer_twoparty_bridge_b)
AST_TEST_DEFINE (test_cel_blind_transfer)
AST_TEST_DEFINE (test_cel_attended_transfer_bridges_merge)
AST_TEST_DEFINE (test_cel_dial_pickup)
AST_TEST_DEFINE (test_cel_local_optimize)
static int cel_verify_and_cleanup_cb (struct ast_test_info *info, struct ast_test *test)
static int check_events (struct ast_test *test, struct ao2_container *local_expected, struct ao2_container *local_received)
static void do_sleep (void)
static int dump_event (struct ast_test *test, struct ast_event *event)
static int events_are_equal (struct ast_test *test, struct ast_event *received, struct ast_event *expected)
static int load_module (void)
static int match_ie_val (const struct ast_event *event1, const struct ast_event *event2, enum ast_event_ie_type type)
Check an IE value from two events.
static void mid_test_sync (void)
static void safe_bridge_destroy (struct ast_bridge *bridge)
static void safe_channel_release (struct ast_channel *chan)
static struct ast_str * test_cel_generate_peer_str (struct ast_channel *chan, struct ast_bridge *bridge)
static struct ast_str * test_cel_generate_peer_str_snapshot (struct ast_channel_snapshot *chan, struct ast_bridge *bridge)
static int test_cel_init_cb (struct ast_test_info *info, struct ast_test *test)
static int test_cel_peer_strings_match (const char *str1, const char *str2)
Check two peer strings for equality.
static void test_sub (struct ast_event *event)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "CEL unit tests" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, }
static const struct ast_module_info * ast_module_info = &__mod_info
static struct ao2_container * cel_expected_events = NULL
static struct ao2_container * cel_received_events = NULL
static struct ast_cel_general_config * cel_test_config
The CEL config used for CEL unit tests.
int do_mid_test_sync = 0
Flag used to trigger a mid-test synchronization, access controlled by mid_test_sync_lock.
ast_mutex_t mid_test_sync_lock
Lock used for synchronizing test execution stages with received events.
static struct ast_cel_general_config * saved_config
A placeholder for Asterisk's 'real' CEL configuration.
ast_mutex_t sync_lock
Lock used with sync_out for checking the end of test execution.
ast_cond_t sync_out
Condition used for checking the end of test execution.
static struct ast_channel_tech test_cel_chan_tech
A channel technology used for the unit tests.
static struct timespec to_sleep = {1, 0}
A 1 second sleep.
Detailed Description
CEL unit tests.
Author
Kinsey Moore kmoor.nosp@m.e@di.nosp@m.gium..nosp@m.com
Definition in file test_cel.c.
Macro Definition Documentation
ALICE_CALLERID
#define ALICE_CALLERID { .id.name.str = "Alice", .id.name.valid = 1, .id.number.str = "100", .id.number.valid = 1, }
Alice's Caller ID.
Definition at line 196 of file test_cel.c.
Referenced by AST_TEST_DEFINE().
ANSWER_CHANNEL
#define ANSWER_CHANNEL (chan)
Value:
do { \
   EMULATE_APP_DATA(chan, 1, "Answer", ""); \
   ANSWER_NO_APP(chan); \
   } while (0)
Definition at line 262 of file test_cel.c.
Referenced by AST_TEST_DEFINE().
ANSWER_NO_APP
#define ANSWER_NO_APP (chan)
Value:
do { \
   ast_setstate(chan, AST_STATE_UP); \
   APPEND_EVENT(chan, AST_CEL_ANSWER, NULL, NULL); \
   } while (0)
Definition at line 267 of file test_cel.c.
Referenced by AST_TEST_DEFINE().
APPEND_DUMMY_EVENT
#define APPEND_DUMMY_EVENT ()
Value:
do { \
   if (append_dummy_event()) { \
      return AST_TEST_FAIL; \
   } \
   } while (0)
Definition at line 111 of file test_cel.c.
Referenced by AST_TEST_DEFINE().
APPEND_EVENT
#define APPEND_EVENT (chan, ev_type, userevent, extra)
Value:
do { \
   if (append_expected_event(chan, ev_type, userevent, extra, NULL)) { \
      return AST_TEST_FAIL; \
   } \
   } while (0)
Definition at line 93 of file test_cel.c.
Referenced by AST_TEST_DEFINE().
APPEND_EVENT_PEER
#define APPEND_EVENT_PEER (chan, ev_type, userevent, extra, peer)
Value:
do { \
   if (append_expected_event(chan, ev_type, userevent, extra, peer)) { \
      return AST_TEST_FAIL; \
   } \
   } while (0)
Definition at line 99 of file test_cel.c.
APPEND_EVENT_SNAPSHOT
#define APPEND_EVENT_SNAPSHOT (snapshot, ev_type, userevent, extra, peer)
Value:
do { \
   if (append_expected_event_snapshot(snapshot, ev_type, userevent, extra, peer)) { \
      return AST_TEST_FAIL; \
   } \
   } while (0)
Definition at line 105 of file test_cel.c.
Referenced by AST_TEST_DEFINE().
ATTENDEDTRANSFER_BRIDGE
#define ATTENDEDTRANSFER_BRIDGE (channel1, bridge1, channel2, bridge2, channel3, channel4)
Definition at line 180 of file test_cel.c.
Referenced by AST_TEST_DEFINE().
BLINDTRANSFER_EVENT
#define BLINDTRANSFER_EVENT (channel, bridge, extension, context)
Definition at line 168 of file test_cel.c.
Referenced by AST_TEST_DEFINE().
BOB_CALLERID
#define BOB_CALLERID { .id.name.str = "Bob", .id.name.valid = 1, .id.number.str = "200", .id.number.valid = 1, }
Bob's Caller ID.
Definition at line 199 of file test_cel.c.
Referenced by AST_TEST_DEFINE().
BRIDGE_ENTER
#define BRIDGE_ENTER (channel, bridge)
Definition at line 147 of file test_cel.c.
Referenced by AST_TEST_DEFINE().
BRIDGE_ENTER_EVENT
#define BRIDGE_ENTER_EVENT (channel, bridge)
Definition at line 154 of file test_cel.c.
BRIDGE_ENTER_EVENT_PEER
#define BRIDGE_ENTER_EVENT_PEER (channel, bridge, peer)
Definition at line 161 of file test_cel.c.
Referenced by AST_TEST_DEFINE().
BRIDGE_EXIT
#define BRIDGE_EXIT (channel, bridge)
Value:
do { \
   ast_test_validate(test, !ast_bridge_depart(channel)); \
   BRIDGE_EXIT_EVENT(channel, bridge); \
   mid_test_sync(); \
   } while (0)
Definition at line 117 of file test_cel.c.
Referenced by AST_TEST_DEFINE().
BRIDGE_EXIT_EVENT
#define BRIDGE_EXIT_EVENT (channel, bridge)
Definition at line 123 of file test_cel.c.
Referenced by AST_TEST_DEFINE().
BRIDGE_EXIT_EVENT_PEER
#define BRIDGE_EXIT_EVENT_PEER (channel, bridge, peer)
Definition at line 130 of file test_cel.c.
Referenced by AST_TEST_DEFINE().
BRIDGE_EXIT_SNAPSHOT
#define BRIDGE_EXIT_SNAPSHOT (channel, bridge)
Definition at line 137 of file test_cel.c.
CHANNEL_TECH_NAME
#define CHANNEL_TECH_NAME "CELTestChannel"
Definition at line 56 of file test_cel.c.
Referenced by AST_TEST_DEFINE(), and test_sub().
CHARLIE_CALLERID
#define CHARLIE_CALLERID { .id.name.str = "Charlie", .id.name.valid = 1, .id.number.str = "300", .id.number.valid = 1, }
Charlie's Caller ID.
Definition at line 202 of file test_cel.c.
Referenced by AST_TEST_DEFINE().
CREATE_ALICE_CHANNEL
#define CREATE_ALICE_CHANNEL (channel_var, caller_id)
Create a test_cel_chan_tech for Alice.
Definition at line 221 of file test_cel.c.
Referenced by AST_TEST_DEFINE().
CREATE_BOB_CHANNEL
#define CREATE_BOB_CHANNEL (channel_var, caller_id)
Create a test_cel_chan_tech for Bob.
Definition at line 229 of file test_cel.c.
Referenced by AST_TEST_DEFINE().
CREATE_CHARLIE_CHANNEL
#define CREATE_CHARLIE_CHANNEL (channel_var, caller_id)
Create a test_cel_chan_tech for Charlie.
Definition at line 237 of file test_cel.c.
Referenced by AST_TEST_DEFINE().
CREATE_DAVID_CHANNEL
#define CREATE_DAVID_CHANNEL (channel_var, caller_id)
Create a test_cel_chan_tech for David.
Definition at line 245 of file test_cel.c.
Referenced by AST_TEST_DEFINE().
DAVID_CALLERID
#define DAVID_CALLERID { .id.name.str = "David", .id.name.valid = 1, .id.number.str = "400", .id.number.valid = 1, }
David's Caller ID.
Definition at line 205 of file test_cel.c.
EMULATE_APP_DATA
#define EMULATE_APP_DATA (channel, priority, application, data)
Emulate a channel entering into an application.
Definition at line 253 of file test_cel.c.
Referenced by AST_TEST_DEFINE().
EMULATE_DIAL
#define EMULATE_DIAL (channel, dialstring)
Definition at line 745 of file test_cel.c.
Referenced by AST_TEST_DEFINE().
HANGUP_CHANNEL
#define HANGUP_CHANNEL (channel, cause, dialstatus)
Hang up a test channel safely.
Definition at line 273 of file test_cel.c.
Referenced by AST_TEST_DEFINE().
HANGUP_EVENT
#define HANGUP_EVENT (channel, cause, dialstatus)
Definition at line 284 of file test_cel.c.
SET_FORMATS
#define SET_FORMATS (chan)
Set ulaw format on channel.
Definition at line 208 of file test_cel.c.
START_DIALED
#define START_DIALED (caller, callee) START_DIALED_FULL(caller, callee, "200", "Bob")
Definition at line 752 of file test_cel.c.
Referenced by AST_TEST_DEFINE().
START_DIALED_FULL
#define START_DIALED_FULL (caller, callee, number, name)
Definition at line 755 of file test_cel.c.
Referenced by AST_TEST_DEFINE().
TEST_BACKEND_NAME
#define TEST_BACKEND_NAME "CEL Test Logging"
Definition at line 58 of file test_cel.c.
Referenced by cel_verify_and_cleanup_cb(), and test_cel_init_cb().
TEST_CATEGORY
#define TEST_CATEGORY "/main/cel/"
Definition at line 54 of file test_cel.c.
Referenced by AST_TEST_DEFINE(), and load_module().
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 2231 of file test_cel.c.
__test_cel_generate_peer_str()
static struct ast_str* __test_cel_generate_peer_str (struct ast_channel_snapshot * chan, struct ast_bridge_snapshot * bridge) static
Definition at line 314 of file test_cel.c.
References ao2_cleanup, ao2_iterator_destroy(), ao2_iterator_init(), ao2_iterator_next, ast_channel_snapshot_get_latest(), ast_str_append(), ast_str_create, ast_str_truncate(), ast_channel_snapshot::base, ast_bridge_snapshot::channels, NULL, RAII_VAR, and ast_channel_snapshot_base::uniqueid.
Referenced by test_cel_generate_peer_str_snapshot().
 {
    struct ast_str *peer_str = ast_str_create(32);
    struct ao2_iterator i;
    char *current_chan = NULL;
    if (!peer_str) {
       return NULL;
    }
    for (i = ao2_iterator_init(bridge->channels, 0);
       (current_chan = ao2_iterator_next(&i));
       ao2_cleanup(current_chan)) {
       RAII_VAR(struct ast_channel_snapshot *, current_snapshot,
          NULL,
          ao2_cleanup);
       /* Don't add the channel for which this message is being generated */
       if (!strcmp(current_chan, chan->base->uniqueid)) {
          continue;
       }
       current_snapshot = ast_channel_snapshot_get_latest(current_chan);
       if (!current_snapshot) {
          continue;
       }
       ast_str_append(&peer_str, 0, "%s,", current_snapshot->base->name);
    }
    ao2_iterator_destroy(&i);
    /* Rip off the trailing comma */
    ast_str_truncate(peer_str, -1);
    return peer_str;
 }
__unreg_module()
static void __unreg_module (void) static
Definition at line 2231 of file test_cel.c.
ao2_dup_event()
static struct ast_event* ao2_dup_event (const struct ast_event * event) static
Definition at line 1689 of file test_cel.c.
References ao2_alloc, ast_event_get_size(), ast_event::event_len, and NULL.
Referenced by append_event(), and test_sub().
 {
    struct ast_event *event_dup;
    uint16_t event_len;
    event_len = ast_event_get_size(event);
    event_dup = ao2_alloc(event_len, NULL);
    if (!event_dup) {
       return NULL;
    }
    memcpy(event_dup, event, event_len);
    return event_dup;
 }
append_event()
static int append_event (struct ast_event * ev) static
Definition at line 1729 of file test_cel.c.
References ao2_cleanup, ao2_dup_event(), ao2_link, AST_EVENT_CUSTOM, AST_EVENT_IE_END, ast_event_new(), ast_free, NULL, and RAII_VAR.
Referenced by append_expected_event_snapshot().
 {
    RAII_VAR(struct ast_event *, ao2_ev, NULL, ao2_cleanup);
    ao2_ev = ao2_dup_event(ev);
    if (!ao2_ev) {
       return -1;
    }
    ao2_link(cel_expected_events, ao2_ev);
    return 0;
 }
append_expected_event()
static int append_expected_event (struct ast_channel * chan, enum ast_cel_event_type type, const char * userdefevname, struct ast_json * extra, const char * peer) static
Definition at line 1772 of file test_cel.c.
References ao2_cleanup, append_expected_event_snapshot(), ast_channel_lock, ast_channel_snapshot_create(), ast_channel_unlock, NULL, and RAII_VAR.
 {
    RAII_VAR(struct ast_channel_snapshot *, snapshot, NULL, ao2_cleanup);
    ast_channel_lock(chan);
    snapshot = ast_channel_snapshot_create(chan);
    ast_channel_unlock(chan);
    if (!snapshot) {
       return -1;
    }
    return append_expected_event_snapshot(snapshot, type, userdefevname, extra, peer);
 }
append_expected_event_snapshot()
static int append_expected_event_snapshot (struct ast_channel_snapshot * snapshot, enum ast_cel_event_type type, const char * userdefevname, struct ast_json * extra, const char * peer) static
Definition at line 1756 of file test_cel.c.
References append_event(), ast_cel_create_event(), ast_free, NULL, and RAII_VAR.
Referenced by append_expected_event().
 {
    RAII_VAR(struct ast_event *, ev, NULL, ast_free);
    ev = ast_cel_create_event(snapshot, type, userdefevname, extra, peer);
    if (!ev) {
       return -1;
    }
    return append_event(ev);
 }
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 2231 of file test_cel.c.
AST_TEST_DEFINE() [1/22]
AST_TEST_DEFINE (test_cel_channel_creation)
Definition at line 393 of file test_cel.c.
References ALICE_CALLERID, AST_CAUSE_NORMAL, AST_TEST_NOT_RUN, AST_TEST_PASS, CREATE_ALICE_CHANNEL, HANGUP_CHANNEL, sip_to_pjsip::info(), NULL, RAII_VAR, safe_channel_release(), TEST_CATEGORY, TEST_EXECUTE, and TEST_INIT.
Referenced by AST_TEST_DEFINE().
 {
    RAII_VAR(struct ast_channel *, chan, NULL, safe_channel_release);
    struct ast_party_caller caller = ALICE_CALLERID;
    switch (cmd) {
    case TEST_INIT:
       info->name = __func__;
       info->category = TEST_CATEGORY;
       info->summary = "Test the CEL records created when a channel is created";
       info->description =
          "Test the CEL records created when a channel is created";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    CREATE_ALICE_CHANNEL(chan, (&caller));
    HANGUP_CHANNEL(chan, AST_CAUSE_NORMAL, "");
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [2/22]
AST_TEST_DEFINE (test_cel_unanswered_inbound_call)
Definition at line 417 of file test_cel.c.
References ALICE_CALLERID, AST_CAUSE_NORMAL, AST_TEST_NOT_RUN, AST_TEST_PASS, CREATE_ALICE_CHANNEL, EMULATE_APP_DATA, HANGUP_CHANNEL, sip_to_pjsip::info(), NULL, RAII_VAR, safe_channel_release(), TEST_CATEGORY, TEST_EXECUTE, and TEST_INIT.
 {
    RAII_VAR(struct ast_channel *, chan, NULL, safe_channel_release);
    struct ast_party_caller caller = ALICE_CALLERID;
    switch (cmd) {
    case TEST_INIT:
       info->name = __func__;
       info->category = TEST_CATEGORY;
       info->summary = "Test inbound unanswered calls";
       info->description =
          "Test CEL records for a call that is\n"
          "inbound to Asterisk, executes some dialplan, but\n"
          "is never answered.";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    CREATE_ALICE_CHANNEL(chan, &caller);
    EMULATE_APP_DATA(chan, 1, "Wait", "1");
    HANGUP_CHANNEL(chan, AST_CAUSE_NORMAL, "");
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [3/22]
AST_TEST_DEFINE (test_cel_unanswered_outbound_call)
Definition at line 445 of file test_cel.c.
References AST_CAUSE_NORMAL, ast_channel_context_set(), ast_channel_exten_set(), ast_channel_flags(), AST_FLAG_ORIGINATED, ast_set_flag, AST_TEST_NOT_RUN, AST_TEST_PASS, CREATE_ALICE_CHANNEL, EMULATE_APP_DATA, HANGUP_CHANNEL, ast_party_caller::id, sip_to_pjsip::info(), ast_party_id::name, NULL, RAII_VAR, safe_channel_release(), ast_party_name::str, TEST_CATEGORY, TEST_EXECUTE, and TEST_INIT.
 {
    RAII_VAR(struct ast_channel *, chan, NULL, safe_channel_release);
    struct ast_party_caller caller = {
          .id.name.str = "",
          .id.name.valid = 1,
          .id.number.str = "",
          .id.number.valid = 1, };
    switch (cmd) {
    case TEST_INIT:
       info->name = __func__;
       info->category = TEST_CATEGORY;
       info->summary = "Test outbound unanswered calls";
       info->description =
          "Test CEL records for a call that is\n"
          "outbound to Asterisk but is never answered.";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    CREATE_ALICE_CHANNEL(chan, &caller);
    ast_channel_exten_set(chan, "s");
    ast_channel_context_set(chan, "default");
    ast_set_flag(ast_channel_flags(chan), AST_FLAG_ORIGINATED);
    EMULATE_APP_DATA(chan, 0, "AppDial", "(Outgoing Line)");
    HANGUP_CHANNEL(chan, AST_CAUSE_NORMAL, "");
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [4/22]
AST_TEST_DEFINE (test_cel_single_party)
Definition at line 478 of file test_cel.c.
References ALICE_CALLERID, ANSWER_CHANNEL, AST_CAUSE_NORMAL, AST_TEST_NOT_RUN, AST_TEST_PASS, CREATE_ALICE_CHANNEL, EMULATE_APP_DATA, HANGUP_CHANNEL, sip_to_pjsip::info(), NULL, RAII_VAR, safe_channel_release(), TEST_CATEGORY, TEST_EXECUTE, and TEST_INIT.
 {
    RAII_VAR(struct ast_channel *, chan, NULL, safe_channel_release);
    struct ast_party_caller caller = ALICE_CALLERID;
    switch (cmd) {
    case TEST_INIT:
       info->name = __func__;
       info->category = TEST_CATEGORY;
       info->summary = "Test CEL for a single party";
       info->description =
          "Test CEL records for a call that is\n"
          "answered, but only involves a single channel";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    CREATE_ALICE_CHANNEL(chan, &caller);
    ANSWER_CHANNEL(chan);
    EMULATE_APP_DATA(chan, 2, "VoiceMailMain", "1");
    HANGUP_CHANNEL(chan, AST_CAUSE_NORMAL, "");
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [5/22]
AST_TEST_DEFINE (test_cel_single_bridge)
Definition at line 505 of file test_cel.c.
References ALICE_CALLERID, ANSWER_CHANNEL, ast_bridge_basic_new(), AST_CAUSE_NORMAL, AST_TEST_NOT_RUN, AST_TEST_PASS, BRIDGE_ENTER, BRIDGE_EXIT, CREATE_ALICE_CHANNEL, do_sleep(), EMULATE_APP_DATA, HANGUP_CHANNEL, sip_to_pjsip::info(), NULL, RAII_VAR, safe_bridge_destroy(), safe_channel_release(), TEST_CATEGORY, TEST_EXECUTE, and TEST_INIT.
 {
    RAII_VAR(struct ast_channel *, chan, NULL, safe_channel_release);
    RAII_VAR(struct ast_bridge *, bridge, NULL, safe_bridge_destroy);
    struct ast_party_caller caller = ALICE_CALLERID;
    switch (cmd) {
    case TEST_INIT:
       info->name = __func__;
       info->category = TEST_CATEGORY;
       info->summary = "Test CEL for a single party entering/leaving a bridge";
       info->description =
          "Test CEL records for a call that is\n"
          "answered, enters a bridge, and leaves it.";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    bridge = ast_bridge_basic_new();
    ast_test_validate(test, bridge != NULL);
    CREATE_ALICE_CHANNEL(chan, &caller);
    ANSWER_CHANNEL(chan);
    EMULATE_APP_DATA(chan, 2, "Bridge", "");
    do_sleep();
    BRIDGE_ENTER(chan, bridge);
    do_sleep();
    BRIDGE_EXIT(chan, bridge);
    HANGUP_CHANNEL(chan, AST_CAUSE_NORMAL, "");
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [6/22]
AST_TEST_DEFINE (test_cel_single_bridge_continue)
Definition at line 544 of file test_cel.c.
References ALICE_CALLERID, ANSWER_CHANNEL, ast_bridge_basic_new(), AST_CAUSE_NORMAL, AST_TEST_NOT_RUN, AST_TEST_PASS, BRIDGE_ENTER, BRIDGE_EXIT, CREATE_ALICE_CHANNEL, do_sleep(), EMULATE_APP_DATA, HANGUP_CHANNEL, sip_to_pjsip::info(), NULL, RAII_VAR, safe_bridge_destroy(), safe_channel_release(), TEST_CATEGORY, TEST_EXECUTE, and TEST_INIT.
 {
    RAII_VAR(struct ast_channel *, chan, NULL, safe_channel_release);
    RAII_VAR(struct ast_bridge *, bridge, NULL, safe_bridge_destroy);
    struct ast_party_caller caller = ALICE_CALLERID;
    switch (cmd) {
    case TEST_INIT:
       info->name = __func__;
       info->category = TEST_CATEGORY;
       info->summary = "Test CEL for a single party entering/leaving a bridge";
       info->description =
          "Test CEL records for a call that is\n"
          "answered, enters a bridge, and leaves it.";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    bridge = ast_bridge_basic_new();
    ast_test_validate(test, bridge != NULL);
    CREATE_ALICE_CHANNEL(chan, &caller);
    ANSWER_CHANNEL(chan);
    EMULATE_APP_DATA(chan, 2, "Bridge", "");
    do_sleep();
    BRIDGE_ENTER(chan, bridge);
    do_sleep();
    BRIDGE_EXIT(chan, bridge);
    EMULATE_APP_DATA(chan, 3, "Wait", "");
    /* And then it hangs up */
    HANGUP_CHANNEL(chan, AST_CAUSE_NORMAL, "");
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [7/22]
AST_TEST_DEFINE (test_cel_single_twoparty_bridge_a)
Definition at line 585 of file test_cel.c.
References ALICE_CALLERID, ANSWER_CHANNEL, ast_bridge_basic_new(), AST_CAUSE_NORMAL, AST_TEST_NOT_RUN, AST_TEST_PASS, BOB_CALLERID, BRIDGE_ENTER, BRIDGE_EXIT, CREATE_ALICE_CHANNEL, CREATE_BOB_CHANNEL, do_sleep(), EMULATE_APP_DATA, HANGUP_CHANNEL, sip_to_pjsip::info(), NULL, RAII_VAR, safe_bridge_destroy(), safe_channel_release(), TEST_CATEGORY, TEST_EXECUTE, and TEST_INIT.
 {
    RAII_VAR(struct ast_channel *, chan_alice, NULL, safe_channel_release);
    RAII_VAR(struct ast_channel *, chan_bob, NULL, safe_channel_release);
    RAII_VAR(struct ast_bridge *, bridge, NULL, safe_bridge_destroy);
    struct ast_party_caller caller_alice = ALICE_CALLERID;
    struct ast_party_caller caller_bob = BOB_CALLERID;
    switch (cmd) {
    case TEST_INIT:
       info->name = __func__;
       info->category = TEST_CATEGORY;
       info->summary = "Test CEL for a single party entering/leaving a bridge";
       info->description =
          "Test CEL records for a call that is\n"
          "answered, enters a bridge, and leaves it. In this scenario, the\n"
          "Party A should answer the bridge first.";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    bridge = ast_bridge_basic_new();
    ast_test_validate(test, bridge != NULL);
    CREATE_ALICE_CHANNEL(chan_alice, &caller_alice);
    CREATE_BOB_CHANNEL(chan_bob, &caller_bob);
    ANSWER_CHANNEL(chan_alice);
    EMULATE_APP_DATA(chan_alice, 2, "Bridge", "");
    BRIDGE_ENTER(chan_alice, bridge);
    do_sleep();
    ANSWER_CHANNEL(chan_bob);
    EMULATE_APP_DATA(chan_bob, 2, "Bridge", "");
    BRIDGE_ENTER(chan_bob, bridge);
    BRIDGE_EXIT(chan_alice, bridge);
    BRIDGE_EXIT(chan_bob, bridge);
    HANGUP_CHANNEL(chan_alice, AST_CAUSE_NORMAL, "");
    HANGUP_CHANNEL(chan_bob, AST_CAUSE_NORMAL, "");
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [8/22]
AST_TEST_DEFINE (test_cel_single_twoparty_bridge_b)
Definition at line 633 of file test_cel.c.
References ALICE_CALLERID, ANSWER_CHANNEL, ast_bridge_basic_new(), AST_CAUSE_NORMAL, AST_TEST_DEFINE(), AST_TEST_NOT_RUN, AST_TEST_PASS, BOB_CALLERID, BRIDGE_ENTER, BRIDGE_EXIT, CHARLIE_CALLERID, CREATE_ALICE_CHANNEL, CREATE_BOB_CHANNEL, CREATE_CHARLIE_CHANNEL, do_sleep(), EMULATE_APP_DATA, HANGUP_CHANNEL, sip_to_pjsip::info(), NULL, RAII_VAR, safe_bridge_destroy(), safe_channel_release(), TEST_CATEGORY, TEST_EXECUTE, and TEST_INIT.
 {
    RAII_VAR(struct ast_channel *, chan_alice, NULL, safe_channel_release);
    RAII_VAR(struct ast_channel *, chan_bob, NULL, safe_channel_release);
    RAII_VAR(struct ast_bridge *, bridge, NULL, safe_bridge_destroy);
    struct ast_party_caller caller_alice = ALICE_CALLERID;
    struct ast_party_caller caller_bob = BOB_CALLERID;
    switch (cmd) {
    case TEST_INIT:
       info->name = __func__;
       info->category = TEST_CATEGORY;
       info->summary = "Test CEL for a single party entering/leaving a bridge";
       info->description =
          "Test CEL records for a call that is\n"
          "answered, enters a bridge, and leaves it. In this scenario, the\n"
          "Party B should answer the bridge first.";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    bridge = ast_bridge_basic_new();
    ast_test_validate(test, bridge != NULL);
    CREATE_ALICE_CHANNEL(chan_alice, &caller_alice);
    CREATE_BOB_CHANNEL(chan_bob, &caller_bob);
    ANSWER_CHANNEL(chan_alice);
    EMULATE_APP_DATA(chan_alice, 2, "Bridge", "");
    ANSWER_CHANNEL(chan_bob);
    EMULATE_APP_DATA(chan_bob, 2, "Bridge", "");
    do_sleep();
    BRIDGE_ENTER(chan_bob, bridge);
    BRIDGE_ENTER(chan_alice, bridge);
    BRIDGE_EXIT(chan_alice, bridge);
    BRIDGE_EXIT(chan_bob, bridge);
    HANGUP_CHANNEL(chan_alice, AST_CAUSE_NORMAL, "");
    HANGUP_CHANNEL(chan_bob, AST_CAUSE_NORMAL, "");
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [9/22]
AST_TEST_DEFINE (test_cel_dial_unanswered)
Definition at line 767 of file test_cel.c.
References ALICE_CALLERID, AST_CAUSE_NO_ANSWER, ast_channel_publish_dial(), ast_channel_state_set(), AST_STATE_RINGING, AST_TEST_NOT_RUN, AST_TEST_PASS, CHANNEL_TECH_NAME, CREATE_ALICE_CHANNEL, EMULATE_DIAL, HANGUP_CHANNEL, sip_to_pjsip::info(), NULL, RAII_VAR, safe_channel_release(), START_DIALED, TEST_CATEGORY, TEST_EXECUTE, and TEST_INIT.
 {
    RAII_VAR(struct ast_channel *, chan_caller, NULL, safe_channel_release);
    RAII_VAR(struct ast_channel *, chan_callee, NULL, safe_channel_release);
    struct ast_party_caller caller = ALICE_CALLERID;
    switch (cmd) {
    case TEST_INIT:
       info->name = __func__;
       info->category = TEST_CATEGORY;
       info->summary = "Test CEL for a dial that isn't answered";
       info->description =
          "Test CEL records for a channel that\n"
          "performs a dial operation that isn't answered";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    CREATE_ALICE_CHANNEL(chan_caller, &caller);
    EMULATE_DIAL(chan_caller, CHANNEL_TECH_NAME "/Bob");
    START_DIALED(chan_caller, chan_callee);
    ast_channel_state_set(chan_caller, AST_STATE_RINGING);
    ast_channel_publish_dial(chan_caller, chan_callee, NULL, "NOANSWER");
    HANGUP_CHANNEL(chan_caller, AST_CAUSE_NO_ANSWER, "NOANSWER");
    HANGUP_CHANNEL(chan_callee, AST_CAUSE_NO_ANSWER, "");
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [10/22]
AST_TEST_DEFINE (test_cel_dial_unanswered_filter)
Definition at line 801 of file test_cel.c.
References ALICE_CALLERID, AST_CAUSE_NO_ANSWER, ast_channel_publish_dial(), ast_channel_state_set(), AST_STATE_RINGING, AST_TEST_NOT_RUN, AST_TEST_PASS, CHANNEL_TECH_NAME, CREATE_ALICE_CHANNEL, EMULATE_DIAL, HANGUP_CHANNEL, sip_to_pjsip::info(), NULL, RAII_VAR, safe_channel_release(), START_DIALED, TEST_CATEGORY, TEST_EXECUTE, and TEST_INIT.
 {
    RAII_VAR(struct ast_channel *, chan_caller, NULL, safe_channel_release);
    RAII_VAR(struct ast_channel *, chan_callee, NULL, safe_channel_release);
    struct ast_party_caller caller = ALICE_CALLERID;
    switch (cmd) {
    case TEST_INIT:
       info->name = __func__;
       info->category = TEST_CATEGORY;
       info->summary = "Test CEL for a dial that isn't answered";
       info->description =
          "Test CEL records for a channel that\n"
          "performs a dial operation that isn't answered";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    CREATE_ALICE_CHANNEL(chan_caller, &caller);
    EMULATE_DIAL(chan_caller, CHANNEL_TECH_NAME "/Bob");
    START_DIALED(chan_caller, chan_callee);
    ast_channel_state_set(chan_caller, AST_STATE_RINGING);
    ast_channel_publish_dial(chan_caller, chan_callee, NULL, "NOT A VALID DIAL STATUS");
    ast_channel_publish_dial(chan_caller, chan_callee, NULL, "NOANSWER");
    HANGUP_CHANNEL(chan_caller, AST_CAUSE_NO_ANSWER, "NOANSWER");
    HANGUP_CHANNEL(chan_callee, AST_CAUSE_NO_ANSWER, "");
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [11/22]
AST_TEST_DEFINE (test_cel_dial_busy)
Definition at line 836 of file test_cel.c.
References ALICE_CALLERID, AST_CAUSE_BUSY, ast_channel_publish_dial(), ast_channel_state_set(), AST_STATE_RINGING, AST_TEST_NOT_RUN, AST_TEST_PASS, CHANNEL_TECH_NAME, CREATE_ALICE_CHANNEL, EMULATE_DIAL, HANGUP_CHANNEL, sip_to_pjsip::info(), NULL, RAII_VAR, safe_channel_release(), START_DIALED, TEST_CATEGORY, TEST_EXECUTE, and TEST_INIT.
 {
    RAII_VAR(struct ast_channel *, chan_caller, NULL, safe_channel_release);
    RAII_VAR(struct ast_channel *, chan_callee, NULL, safe_channel_release);
    struct ast_party_caller caller = ALICE_CALLERID;
    switch (cmd) {
    case TEST_INIT:
       info->name = __func__;
       info->category = TEST_CATEGORY;
       info->summary = "Test CEL for a dial that results in a busy";
       info->description =
          "Test CEL records for a channel that\n"
          "performs a dial operation to an endpoint that's busy";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    CREATE_ALICE_CHANNEL(chan_caller, &caller);
    EMULATE_DIAL(chan_caller, CHANNEL_TECH_NAME "/Bob");
    START_DIALED(chan_caller, chan_callee);
    ast_channel_state_set(chan_caller, AST_STATE_RINGING);
    ast_channel_publish_dial(chan_caller, chan_callee, NULL, "BUSY");
    HANGUP_CHANNEL(chan_caller, AST_CAUSE_BUSY, "BUSY");
    HANGUP_CHANNEL(chan_callee, AST_CAUSE_BUSY, "");
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [12/22]
AST_TEST_DEFINE (test_cel_dial_congestion)
Definition at line 870 of file test_cel.c.
References ALICE_CALLERID, AST_CAUSE_CONGESTION, ast_channel_publish_dial(), ast_channel_state_set(), AST_STATE_RINGING, AST_TEST_NOT_RUN, AST_TEST_PASS, CHANNEL_TECH_NAME, CREATE_ALICE_CHANNEL, EMULATE_DIAL, HANGUP_CHANNEL, sip_to_pjsip::info(), NULL, RAII_VAR, safe_channel_release(), START_DIALED, TEST_CATEGORY, TEST_EXECUTE, and TEST_INIT.
 {
    RAII_VAR(struct ast_channel *, chan_caller, NULL, safe_channel_release);
    RAII_VAR(struct ast_channel *, chan_callee, NULL, safe_channel_release);
    struct ast_party_caller caller = ALICE_CALLERID;
    switch (cmd) {
    case TEST_INIT:
       info->name = __func__;
       info->category = TEST_CATEGORY;
       info->summary = "Test CEL for a dial that results in congestion";
       info->description =
          "Test CEL records for a channel that\n"
          "performs a dial operation to an endpoint that's congested";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    CREATE_ALICE_CHANNEL(chan_caller, &caller);
    EMULATE_DIAL(chan_caller, CHANNEL_TECH_NAME "/Bob");
    START_DIALED(chan_caller, chan_callee);
    ast_channel_state_set(chan_caller, AST_STATE_RINGING);
    ast_channel_publish_dial(chan_caller, chan_callee, NULL, "CONGESTION");
    HANGUP_CHANNEL(chan_caller, AST_CAUSE_CONGESTION, "CONGESTION");
    HANGUP_CHANNEL(chan_callee, AST_CAUSE_CONGESTION, "");
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [13/22]
AST_TEST_DEFINE (test_cel_dial_unavailable)
Definition at line 904 of file test_cel.c.
References ALICE_CALLERID, AST_CAUSE_NO_ROUTE_DESTINATION, ast_channel_publish_dial(), ast_channel_state_set(), AST_STATE_RINGING, AST_TEST_NOT_RUN, AST_TEST_PASS, CHANNEL_TECH_NAME, CREATE_ALICE_CHANNEL, EMULATE_DIAL, HANGUP_CHANNEL, sip_to_pjsip::info(), NULL, RAII_VAR, safe_channel_release(), START_DIALED, TEST_CATEGORY, TEST_EXECUTE, and TEST_INIT.
 {
    RAII_VAR(struct ast_channel *, chan_caller, NULL, safe_channel_release);
    RAII_VAR(struct ast_channel *, chan_callee, NULL, safe_channel_release);
    struct ast_party_caller caller = ALICE_CALLERID;
    switch (cmd) {
    case TEST_INIT:
       info->name = __func__;
       info->category = TEST_CATEGORY;
       info->summary = "Test CEL for a dial that results in unavailable";
       info->description =
          "Test CEL records for a channel that\n"
          "performs a dial operation to an endpoint that's unavailable";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    CREATE_ALICE_CHANNEL(chan_caller, &caller);
    EMULATE_DIAL(chan_caller, CHANNEL_TECH_NAME "/Bob");
    START_DIALED(chan_caller, chan_callee);
    ast_channel_state_set(chan_caller, AST_STATE_RINGING);
    ast_channel_publish_dial(chan_caller, chan_callee, NULL, "CHANUNAVAIL");
    HANGUP_CHANNEL(chan_caller, AST_CAUSE_NO_ROUTE_DESTINATION, "CHANUNAVAIL");
    HANGUP_CHANNEL(chan_callee, AST_CAUSE_NO_ROUTE_DESTINATION, "");
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [14/22]
AST_TEST_DEFINE (test_cel_dial_caller_cancel)
Definition at line 938 of file test_cel.c.
References ALICE_CALLERID, AST_CAUSE_NORMAL, ast_channel_publish_dial(), ast_channel_state_set(), AST_STATE_RINGING, AST_TEST_NOT_RUN, AST_TEST_PASS, CHANNEL_TECH_NAME, CREATE_ALICE_CHANNEL, EMULATE_DIAL, HANGUP_CHANNEL, sip_to_pjsip::info(), NULL, RAII_VAR, safe_channel_release(), START_DIALED, TEST_CATEGORY, TEST_EXECUTE, and TEST_INIT.
 {
    RAII_VAR(struct ast_channel *, chan_caller, NULL, safe_channel_release);
    RAII_VAR(struct ast_channel *, chan_callee, NULL, safe_channel_release);
    struct ast_party_caller caller = ALICE_CALLERID;
    switch (cmd) {
    case TEST_INIT:
       info->name = __func__;
       info->category = TEST_CATEGORY;
       info->summary = "Test CEL for a dial where the caller cancels";
       info->description =
          "Test CEL records for a channel that\n"
          "performs a dial operation to an endpoint but then decides\n"
          "to hang up, cancelling the dial";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    CREATE_ALICE_CHANNEL(chan_caller, &caller);
    EMULATE_DIAL(chan_caller, CHANNEL_TECH_NAME "/Bob");
    START_DIALED(chan_caller, chan_callee);
    ast_channel_state_set(chan_caller, AST_STATE_RINGING);
    ast_channel_publish_dial(chan_caller, chan_callee, NULL, "CANCEL");
    HANGUP_CHANNEL(chan_callee, AST_CAUSE_NORMAL, "");
    HANGUP_CHANNEL(chan_caller, AST_CAUSE_NORMAL, "CANCEL");
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [15/22]
AST_TEST_DEFINE (test_cel_dial_parallel_failed)
Definition at line 973 of file test_cel.c.
References ALICE_CALLERID, AST_CAUSE_BUSY, AST_CAUSE_CONGESTION, AST_CAUSE_NORMAL, ast_channel_publish_dial(), ast_channel_state_set(), AST_STATE_RINGING, AST_TEST_NOT_RUN, AST_TEST_PASS, CHANNEL_TECH_NAME, CREATE_ALICE_CHANNEL, EMULATE_DIAL, HANGUP_CHANNEL, sip_to_pjsip::info(), NULL, RAII_VAR, safe_channel_release(), START_DIALED_FULL, TEST_CATEGORY, TEST_EXECUTE, and TEST_INIT.
 {
    RAII_VAR(struct ast_channel *, chan_caller, NULL, safe_channel_release);
    RAII_VAR(struct ast_channel *, chan_bob, NULL, safe_channel_release);
    RAII_VAR(struct ast_channel *, chan_charlie, NULL, safe_channel_release);
    RAII_VAR(struct ast_channel *, chan_david, NULL, safe_channel_release);
    struct ast_party_caller caller = ALICE_CALLERID;
    switch (cmd) {
    case TEST_INIT:
       info->name = __func__;
       info->category = TEST_CATEGORY;
       info->summary = "Test a parallel dial where all channels fail to answer";
       info->description =
          "This tests dialing three parties: Bob, Charlie, David. Charlie\n"
          "returns BUSY; David returns CONGESTION; Bob fails to answer and\n"
          "Alice hangs up. Three records are created for Alice as a result.";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    CREATE_ALICE_CHANNEL(chan_caller, &caller);
    /* Channel enters Dial app */
    EMULATE_DIAL(chan_caller, CHANNEL_TECH_NAME "/Bob&" CHANNEL_TECH_NAME "/Charlie&" CHANNEL_TECH_NAME "/David");
    /* Outbound channels are created */
    START_DIALED_FULL(chan_caller, chan_bob, "200", "Bob");
    START_DIALED_FULL(chan_caller, chan_charlie, "300", "Charlie");
    START_DIALED_FULL(chan_caller, chan_david, "400", "David");
    /* Dial starts */
    ast_channel_state_set(chan_caller, AST_STATE_RINGING);
    /* Charlie is busy */
    ast_channel_publish_dial(chan_caller, chan_charlie, NULL, "BUSY");
    HANGUP_CHANNEL(chan_charlie, AST_CAUSE_BUSY, "");
    /* David is congested */
    ast_channel_publish_dial(chan_caller, chan_david, NULL, "CONGESTION");
    HANGUP_CHANNEL(chan_david, AST_CAUSE_CONGESTION, "");
    /* Bob is canceled */
    ast_channel_publish_dial(chan_caller, chan_bob, NULL, "CANCEL");
    HANGUP_CHANNEL(chan_bob, AST_CAUSE_NORMAL, "");
    /* Alice hangs up */
    HANGUP_CHANNEL(chan_caller, AST_CAUSE_NORMAL, "BUSY");
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [16/22]
AST_TEST_DEFINE (test_cel_dial_answer_no_bridge)
Definition at line 1026 of file test_cel.c.
References ALICE_CALLERID, ANSWER_NO_APP, AST_CAUSE_NORMAL, ast_channel_flags(), ast_channel_publish_dial(), ast_channel_state_set(), ast_clear_flag, AST_FLAG_OUTGOING, AST_STATE_RINGING, AST_TEST_NOT_RUN, AST_TEST_PASS, CHANNEL_TECH_NAME, CREATE_ALICE_CHANNEL, EMULATE_APP_DATA, EMULATE_DIAL, HANGUP_CHANNEL, sip_to_pjsip::info(), NULL, RAII_VAR, safe_channel_release(), START_DIALED, TEST_CATEGORY, TEST_EXECUTE, and TEST_INIT.
 {
    RAII_VAR(struct ast_channel *, chan_caller, NULL, safe_channel_release);
    RAII_VAR(struct ast_channel *, chan_callee, NULL, safe_channel_release);
    struct ast_party_caller caller = ALICE_CALLERID;
    switch (cmd) {
    case TEST_INIT:
       info->name = __func__;
       info->category = TEST_CATEGORY;
       info->summary = "Test dialing, answering, and not going into a bridge.";
       info->description =
          "This is a weird one, but theoretically possible. You can perform\n"
          "a dial, then bounce both channels to different priorities and\n"
          "never have them enter a bridge together. Ew. This makes sure that\n"
          "when we answer, we get a CEL, it gets ended at that point, and\n"
          "that it gets finalized appropriately.";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    CREATE_ALICE_CHANNEL(chan_caller, &caller);
    EMULATE_DIAL(chan_caller, CHANNEL_TECH_NAME "/Bob");
    START_DIALED(chan_caller, chan_callee);
    ast_channel_state_set(chan_caller, AST_STATE_RINGING);
    ast_channel_publish_dial(chan_caller, chan_callee, NULL, "ANSWER");
    ANSWER_NO_APP(chan_caller);
    ast_clear_flag(ast_channel_flags(chan_callee), AST_FLAG_OUTGOING);
    ANSWER_NO_APP(chan_callee);
    EMULATE_APP_DATA(chan_caller, 2, "Wait", "1");
    EMULATE_APP_DATA(chan_callee, 1, "Wait", "1");
    HANGUP_CHANNEL(chan_caller, AST_CAUSE_NORMAL, "ANSWER");
    HANGUP_CHANNEL(chan_callee, AST_CAUSE_NORMAL, "");
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [17/22]
AST_TEST_DEFINE (test_cel_dial_answer_twoparty_bridge_a)
Definition at line 1070 of file test_cel.c.
References ALICE_CALLERID, ANSWER_NO_APP, ast_bridge_basic_new(), AST_CAUSE_NORMAL, ast_channel_publish_dial(), ast_channel_state_set(), AST_STATE_RINGING, AST_TEST_NOT_RUN, AST_TEST_PASS, BRIDGE_ENTER, BRIDGE_EXIT, CHANNEL_TECH_NAME, CREATE_ALICE_CHANNEL, do_sleep(), EMULATE_DIAL, HANGUP_CHANNEL, sip_to_pjsip::info(), NULL, RAII_VAR, safe_bridge_destroy(), safe_channel_release(), START_DIALED, TEST_CATEGORY, TEST_EXECUTE, and TEST_INIT.
 {
    RAII_VAR(struct ast_channel *, chan_caller, NULL, safe_channel_release);
    RAII_VAR(struct ast_channel *, chan_callee, NULL, safe_channel_release);
    RAII_VAR(struct ast_bridge *, bridge, NULL, safe_bridge_destroy);
    struct ast_party_caller caller = ALICE_CALLERID;
    switch (cmd) {
    case TEST_INIT:
       info->name = __func__;
       info->category = TEST_CATEGORY;
       info->summary = "Test dialing, answering, and going into a 2-party bridge";
       info->description =
          "The most 'basic' of scenarios";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    bridge = ast_bridge_basic_new();
    ast_test_validate(test, bridge != NULL);
    CREATE_ALICE_CHANNEL(chan_caller, &caller);
    EMULATE_DIAL(chan_caller, CHANNEL_TECH_NAME "/Bob");
    START_DIALED(chan_caller, chan_callee);
    ast_channel_state_set(chan_caller, AST_STATE_RINGING);
    ast_channel_publish_dial(chan_caller, chan_callee, NULL, "ANSWER");
    ANSWER_NO_APP(chan_caller);
    ANSWER_NO_APP(chan_callee);
    do_sleep();
    BRIDGE_ENTER(chan_caller, bridge);
    BRIDGE_ENTER(chan_callee, bridge);
    BRIDGE_EXIT(chan_caller, bridge);
    BRIDGE_EXIT(chan_callee, bridge);
    HANGUP_CHANNEL(chan_caller, AST_CAUSE_NORMAL, "ANSWER");
    HANGUP_CHANNEL(chan_callee, AST_CAUSE_NORMAL, "");
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [18/22]
AST_TEST_DEFINE (test_cel_dial_answer_twoparty_bridge_b)
Definition at line 1117 of file test_cel.c.
References ALICE_CALLERID, ANSWER_NO_APP, ast_bridge_basic_new(), AST_CAUSE_NORMAL, ast_channel_publish_dial(), ast_channel_state_set(), AST_STATE_RINGING, AST_TEST_DEFINE(), AST_TEST_NOT_RUN, AST_TEST_PASS, BRIDGE_ENTER, BRIDGE_EXIT, CHANNEL_TECH_NAME, CHARLIE_CALLERID, CREATE_ALICE_CHANNEL, CREATE_CHARLIE_CHANNEL, do_sleep(), EMULATE_DIAL, HANGUP_CHANNEL, sip_to_pjsip::info(), NULL, RAII_VAR, safe_bridge_destroy(), safe_channel_release(), START_DIALED, START_DIALED_FULL, TEST_CATEGORY, TEST_EXECUTE, and TEST_INIT.
 {
    RAII_VAR(struct ast_channel *, chan_caller, NULL, safe_channel_release);
    RAII_VAR(struct ast_channel *, chan_callee, NULL, safe_channel_release);
    RAII_VAR(struct ast_bridge *, bridge, NULL, safe_bridge_destroy);
    struct ast_party_caller caller = ALICE_CALLERID;
    switch (cmd) {
    case TEST_INIT:
       info->name = __func__;
       info->category = TEST_CATEGORY;
       info->summary = "Test dialing, answering, and going into a 2-party bridge";
       info->description =
          "The most 'basic' of scenarios";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    bridge = ast_bridge_basic_new();
    ast_test_validate(test, bridge != NULL);
    CREATE_ALICE_CHANNEL(chan_caller, &caller);
    EMULATE_DIAL(chan_caller, CHANNEL_TECH_NAME "/Bob");
    START_DIALED(chan_caller, chan_callee);
    ast_channel_state_set(chan_caller, AST_STATE_RINGING);
    ast_channel_publish_dial(chan_caller, chan_callee, NULL, "ANSWER");
    ANSWER_NO_APP(chan_caller);
    ANSWER_NO_APP(chan_callee);
    do_sleep();
    BRIDGE_ENTER(chan_callee, bridge);
    BRIDGE_ENTER(chan_caller, bridge);
    BRIDGE_EXIT(chan_caller, bridge);
    BRIDGE_EXIT(chan_callee, bridge);
    HANGUP_CHANNEL(chan_caller, AST_CAUSE_NORMAL, "ANSWER");
    HANGUP_CHANNEL(chan_callee, AST_CAUSE_NORMAL, "");
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [19/22]
AST_TEST_DEFINE (test_cel_blind_transfer)
Definition at line 1240 of file test_cel.c.
References ALICE_CALLERID, ANSWER_NO_APP, ao2_cleanup, ast_blind_transfer_message_create(), ast_bridge_basic_new(), ast_bridge_lock, ast_bridge_publish_blind_transfer(), ast_bridge_snapshot_create(), ast_bridge_transfer_attended(), AST_BRIDGE_TRANSFER_SUCCESS, ast_bridge_unlock, AST_CAUSE_NORMAL, AST_TEST_DEFINE(), AST_TEST_FAIL, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_test_status_update, ATTENDEDTRANSFER_BRIDGE, BLINDTRANSFER_EVENT, BOB_CALLERID, BRIDGE_ENTER, BRIDGE_ENTER_EVENT_PEER, BRIDGE_EXIT, BRIDGE_EXIT_EVENT, CHARLIE_CALLERID, CREATE_ALICE_CHANNEL, CREATE_BOB_CHANNEL, CREATE_CHARLIE_CHANNEL, CREATE_DAVID_CHANNEL, do_sleep(), HANGUP_CHANNEL, sip_to_pjsip::info(), NULL, RAII_VAR, safe_bridge_destroy(), safe_channel_release(), TEST_CATEGORY, TEST_EXECUTE, and TEST_INIT.
 {
    RAII_VAR(struct ast_channel *, chan_alice, NULL, safe_channel_release);
    RAII_VAR(struct ast_channel *, chan_bob, NULL, safe_channel_release);
    RAII_VAR(struct ast_bridge *, bridge, NULL, safe_bridge_destroy);
    RAII_VAR(struct ast_blind_transfer_message *, transfer_msg, NULL, ao2_cleanup);
    struct ast_party_caller alice_caller = ALICE_CALLERID;
    struct ast_party_caller bob_caller = BOB_CALLERID;
    switch (cmd) {
    case TEST_INIT:
       info->name = __func__;
       info->category = TEST_CATEGORY;
       info->summary = "Test blind transfers to an extension";
       info->description =
          "This test creates two channels, bridges them, and then"
          " blind transfers the bridge to an extension.";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    bridge = ast_bridge_basic_new();
    ast_test_validate(test, bridge != NULL);
    CREATE_ALICE_CHANNEL(chan_alice, &alice_caller);
    CREATE_BOB_CHANNEL(chan_bob, &bob_caller);
    ANSWER_NO_APP(chan_alice);
    ANSWER_NO_APP(chan_bob);
    BRIDGE_ENTER(chan_bob, bridge);
    BRIDGE_ENTER(chan_alice, bridge);
    ast_bridge_lock(bridge);
    transfer_msg = ast_blind_transfer_message_create(1, chan_alice,
          "transfer_extension", "transfer_context");
    if (!transfer_msg) {
       ast_bridge_unlock(bridge);
       ast_test_status_update(test, "Failed to create transfer Stasis message\n");
       return AST_TEST_FAIL;
    }
    transfer_msg->bridge = ast_bridge_snapshot_create(bridge);
    if (!transfer_msg->bridge) {
       ast_bridge_unlock(bridge);
       ast_test_status_update(test, "Failed to create bridge snapshot\n");
       return AST_TEST_FAIL;
    }
    ast_bridge_unlock(bridge);
    transfer_msg->result = AST_BRIDGE_TRANSFER_SUCCESS;
    ast_bridge_publish_blind_transfer(transfer_msg);
    BLINDTRANSFER_EVENT(chan_alice, bridge, "transfer_extension", "transfer_context");
    BRIDGE_EXIT(chan_alice, bridge);
    BRIDGE_EXIT(chan_bob, bridge);
    HANGUP_CHANNEL(chan_alice, AST_CAUSE_NORMAL, "");
    do_sleep();
    HANGUP_CHANNEL(chan_bob, AST_CAUSE_NORMAL, "");
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [20/22]
AST_TEST_DEFINE (test_cel_attended_transfer_bridges_merge)
Definition at line 1387 of file test_cel.c.
References ALICE_CALLERID, ANSWER_NO_APP, APPEND_DUMMY_EVENT, ast_bridge_base_new(), AST_BRIDGE_CAPABILITY_1TO1MIX, AST_BRIDGE_CAPABILITY_MULTIMIX, AST_BRIDGE_CAPABILITY_NATIVE, AST_BRIDGE_FLAG_MERGE_INHIBIT_FROM, AST_BRIDGE_FLAG_MERGE_INHIBIT_TO, AST_BRIDGE_FLAG_SMART, AST_BRIDGE_FLAG_SWAP_INHIBIT_FROM, AST_BRIDGE_FLAG_SWAP_INHIBIT_TO, AST_BRIDGE_FLAG_TRANSFER_PROHIBITED, ast_bridge_transfer_attended(), AST_CAUSE_NORMAL, AST_TEST_DEFINE(), AST_TEST_FAIL, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_test_status_update, ATTENDEDTRANSFER_BRIDGE, BOB_CALLERID, BRIDGE_ENTER, BRIDGE_ENTER_EVENT_PEER, BRIDGE_EXIT, BRIDGE_EXIT_EVENT, BRIDGE_EXIT_EVENT_PEER, CHARLIE_CALLERID, CREATE_ALICE_CHANNEL, CREATE_BOB_CHANNEL, CREATE_CHARLIE_CHANNEL, CREATE_DAVID_CHANNEL, do_sleep(), HANGUP_CHANNEL, sip_to_pjsip::info(), NULL, RAII_VAR, safe_bridge_destroy(), safe_channel_release(), TEST_CATEGORY, TEST_EXECUTE, and TEST_INIT.
 {
    RAII_VAR(struct ast_channel *, chan_alice, NULL, safe_channel_release);
    RAII_VAR(struct ast_channel *, chan_bob, NULL, safe_channel_release);
    RAII_VAR(struct ast_channel *, chan_charlie, NULL, safe_channel_release);
    RAII_VAR(struct ast_channel *, chan_david, NULL, safe_channel_release);
    RAII_VAR(struct ast_bridge *, bridge1, NULL, safe_bridge_destroy);
    RAII_VAR(struct ast_bridge *, bridge2, NULL, safe_bridge_destroy);
    struct ast_party_caller alice_caller = ALICE_CALLERID;
    struct ast_party_caller bob_caller = BOB_CALLERID;
    struct ast_party_caller charlie_caller = CHARLIE_CALLERID;
    struct ast_party_caller david_caller = ALICE_CALLERID;
    switch (cmd) {
    case TEST_INIT:
       info->name = __func__;
       info->category = TEST_CATEGORY;
       info->summary = "Test attended transfers between two pairs of"
          " bridged parties that results in a bridge merge";
       info->description =
          "This test creates four channels, places each pair"
          " in a bridge, and then attended transfers the bridges"
          " together causing a bridge merge.";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    /* Create first set of bridged parties */
    bridge1 = ast_bridge_base_new(AST_BRIDGE_CAPABILITY_1TO1MIX | AST_BRIDGE_CAPABILITY_NATIVE | AST_BRIDGE_CAPABILITY_MULTIMIX,
       AST_BRIDGE_FLAG_SWAP_INHIBIT_FROM | AST_BRIDGE_FLAG_TRANSFER_PROHIBITED | AST_BRIDGE_FLAG_SMART,
       "test_cel", "test_cel_atxfer_bridges_merge_1", NULL);
    ast_test_validate(test, bridge1 != NULL);
    CREATE_ALICE_CHANNEL(chan_alice, &alice_caller);
    CREATE_BOB_CHANNEL(chan_bob, &bob_caller);
    ANSWER_NO_APP(chan_alice);
    ANSWER_NO_APP(chan_bob);
    BRIDGE_ENTER(chan_bob, bridge1);
    BRIDGE_ENTER(chan_alice, bridge1);
    /* Create second set of bridged parties */
    bridge2 = ast_bridge_base_new(AST_BRIDGE_CAPABILITY_1TO1MIX | AST_BRIDGE_CAPABILITY_NATIVE | AST_BRIDGE_CAPABILITY_MULTIMIX,
       AST_BRIDGE_FLAG_SWAP_INHIBIT_FROM | AST_BRIDGE_FLAG_TRANSFER_PROHIBITED | AST_BRIDGE_FLAG_SMART,
       "test_cel", "test_cel_atxfer_bridges_merge_2", NULL);
    ast_test_validate(test, bridge2 != NULL);
    CREATE_DAVID_CHANNEL(chan_david, &david_caller);
    CREATE_CHARLIE_CHANNEL(chan_charlie, &charlie_caller);
    ANSWER_NO_APP(chan_david);
    ANSWER_NO_APP(chan_charlie);
    BRIDGE_ENTER(chan_charlie, bridge2);
    BRIDGE_ENTER(chan_david, bridge2);
    /* Perform attended transfer */
    if (ast_bridge_transfer_attended(chan_alice, chan_david)) {
       ast_test_status_update(test, "Attended transfer failed!\n");
       return AST_TEST_FAIL;
    }
    do_sleep();
    BRIDGE_EXIT_EVENT_PEER(chan_charlie, bridge2, "CELTestChannel/David");
    BRIDGE_ENTER_EVENT_PEER(chan_charlie, bridge1, "CELTestChannel/Bob,CELTestChannel/Alice");
    BRIDGE_EXIT_EVENT(chan_david, bridge2);
    BRIDGE_EXIT_EVENT(chan_alice, bridge1);
    ATTENDEDTRANSFER_BRIDGE(chan_alice, bridge1, chan_david, bridge2, chan_charlie, chan_bob);
    do_sleep();
    BRIDGE_EXIT(chan_bob, bridge1);
    BRIDGE_EXIT(chan_charlie, bridge1);
    HANGUP_CHANNEL(chan_alice, AST_CAUSE_NORMAL, "");
    do_sleep();
    HANGUP_CHANNEL(chan_bob, AST_CAUSE_NORMAL, "");
    do_sleep();
    HANGUP_CHANNEL(chan_david, AST_CAUSE_NORMAL, "");
    do_sleep();
    HANGUP_CHANNEL(chan_charlie, AST_CAUSE_NORMAL, "");
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [21/22]
AST_TEST_DEFINE (test_cel_dial_pickup)
Definition at line 1561 of file test_cel.c.
References ALICE_CALLERID, APPEND_EVENT, AST_CAUSE_NORMAL, AST_CEL_PICKUP, ast_channel_name(), ast_channel_publish_dial(), ast_channel_state_set(), ast_channel_uniqueid(), ast_do_pickup(), ast_json_pack(), ast_json_unref(), AST_STATE_RINGING, AST_TEST_NOT_RUN, AST_TEST_PASS, CHANNEL_TECH_NAME, CHARLIE_CALLERID, CREATE_ALICE_CHANNEL, CREATE_CHARLIE_CHANNEL, EMULATE_DIAL, HANGUP_CHANNEL, sip_to_pjsip::info(), lock, NULL, RAII_VAR, safe_channel_release(), SCOPED_CHANNELLOCK, START_DIALED, TEST_CATEGORY, TEST_EXECUTE, and TEST_INIT.
 {
    RAII_VAR(struct ast_channel *, chan_caller, NULL, safe_channel_release);
    RAII_VAR(struct ast_channel *, chan_callee, NULL, safe_channel_release);
    RAII_VAR(struct ast_channel *, chan_charlie, NULL, safe_channel_release);
    struct ast_party_caller caller = ALICE_CALLERID;
    struct ast_party_caller charlie_caller = CHARLIE_CALLERID;
    switch (cmd) {
    case TEST_INIT:
       info->name = __func__;
       info->category = TEST_CATEGORY;
       info->summary = "Test call pickup";
       info->description =
          "Test CEL records for a call that is\n"
          "inbound to Asterisk, executes some dialplan, and\n"
          "is picked up.";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    CREATE_ALICE_CHANNEL(chan_caller, &caller);
    EMULATE_DIAL(chan_caller, CHANNEL_TECH_NAME "/Bob");
    START_DIALED(chan_caller, chan_callee);
    ast_channel_state_set(chan_caller, AST_STATE_RINGING);
    CREATE_CHARLIE_CHANNEL(chan_charlie, &charlie_caller);
    {
       RAII_VAR(struct ast_json *, extra, NULL, ast_json_unref);
       SCOPED_CHANNELLOCK(lock, chan_callee);
       extra = ast_json_pack("{s: s, s: s}", "pickup_channel", ast_channel_name(chan_charlie),
          "pickup_channel_uniqueid", ast_channel_uniqueid(chan_charlie));
       ast_test_validate(test, extra != NULL);
       APPEND_EVENT(chan_callee, AST_CEL_PICKUP, NULL, extra);
       ast_test_validate(test, !ast_do_pickup(chan_charlie, chan_callee));
    }
    /* Hang up the masqueraded zombie */
    HANGUP_CHANNEL(chan_charlie, AST_CAUSE_NORMAL, "");
    ast_channel_publish_dial(chan_caller, chan_callee, NULL, "ANSWER");
    HANGUP_CHANNEL(chan_caller, AST_CAUSE_NORMAL, "ANSWER");
    HANGUP_CHANNEL(chan_callee, AST_CAUSE_NORMAL, "");
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [22/22]
AST_TEST_DEFINE (test_cel_local_optimize)
Definition at line 1616 of file test_cel.c.
References ALICE_CALLERID, ao2_cleanup, APPEND_EVENT_SNAPSHOT, AST_CAUSE_NORMAL, AST_CEL_LOCAL_OPTIMIZE, ast_channel_lock, ast_channel_snapshot_create(), ast_channel_topic(), ast_channel_unlock, ast_json_null(), ast_json_pack(), ast_json_unref(), ast_local_optimization_begin_type(), ast_local_optimization_end_type(), ast_multi_channel_blob_add_channel(), ast_multi_channel_blob_create(), AST_TEST_NOT_RUN, AST_TEST_PASS, BOB_CALLERID, CREATE_ALICE_CHANNEL, CREATE_BOB_CHANNEL, HANGUP_CHANNEL, sip_to_pjsip::info(), NULL, RAII_VAR, safe_channel_release(), stasis_message_create(), stasis_publish(), TEST_CATEGORY, TEST_EXECUTE, and TEST_INIT.
 {
    RAII_VAR(struct ast_channel *, chan_alice, NULL, safe_channel_release);
    RAII_VAR(struct ast_channel *, chan_bob, NULL, safe_channel_release);
    struct ast_party_caller alice_caller = ALICE_CALLERID;
    struct ast_party_caller bob_caller = BOB_CALLERID;
    RAII_VAR(struct ast_multi_channel_blob *, mc_blob, NULL, ao2_cleanup);
    RAII_VAR(struct ast_channel_snapshot *, alice_snapshot, NULL, ao2_cleanup);
    RAII_VAR(struct ast_channel_snapshot *, bob_snapshot, NULL, ao2_cleanup);
    RAII_VAR(struct stasis_message *, local_opt_begin, NULL, ao2_cleanup);
    RAII_VAR(struct stasis_message *, local_opt_end, NULL, ao2_cleanup);
    RAII_VAR(struct ast_json *, extra, NULL, ast_json_unref);
    switch (cmd) {
    case TEST_INIT:
       info->name = __func__;
       info->category = TEST_CATEGORY;
       info->summary = "Test local channel optimization record generation";
       info->description =
          "Test CEL records for two local channels being optimized\n"
          "out by sending a messages indicating local optimization\n"
          "begin and end";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    mc_blob = ast_multi_channel_blob_create(ast_json_null());
    ast_test_validate(test, mc_blob != NULL);
    CREATE_ALICE_CHANNEL(chan_alice, &alice_caller);
    CREATE_BOB_CHANNEL(chan_bob, &bob_caller);
    ast_channel_lock(chan_alice);
    alice_snapshot = ast_channel_snapshot_create(chan_alice);
    ast_channel_unlock(chan_alice);
    ast_test_validate(test, alice_snapshot != NULL);
    ast_channel_lock(chan_bob);
    bob_snapshot = ast_channel_snapshot_create(chan_bob);
    ast_channel_unlock(chan_bob);
    ast_test_validate(test, bob_snapshot != NULL);
    ast_multi_channel_blob_add_channel(mc_blob, "1", alice_snapshot);
    ast_multi_channel_blob_add_channel(mc_blob, "2", bob_snapshot);
    local_opt_begin = stasis_message_create(ast_local_optimization_begin_type(), mc_blob);
    ast_test_validate(test, local_opt_begin != NULL);
    local_opt_end = stasis_message_create(ast_local_optimization_end_type(), mc_blob);
    ast_test_validate(test, local_opt_end != NULL);
    stasis_publish(ast_channel_topic(chan_alice), local_opt_begin);
    stasis_publish(ast_channel_topic(chan_alice), local_opt_end);
    extra = ast_json_pack("{s: s, s: s}", "local_two", bob_snapshot->base->name,
       "local_two_uniqueid", bob_snapshot->base->uniqueid);
    ast_test_validate(test, extra != NULL);
    APPEND_EVENT_SNAPSHOT(alice_snapshot, AST_CEL_LOCAL_OPTIMIZE, NULL, extra, NULL);
    HANGUP_CHANNEL(chan_alice, AST_CAUSE_NORMAL, "");
    HANGUP_CHANNEL(chan_bob, AST_CAUSE_NORMAL, "");
    return AST_TEST_PASS;
 }
cel_verify_and_cleanup_cb()
static int cel_verify_and_cleanup_cb (struct ast_test_info * info, struct ast_test * test) static
Definition at line 2076 of file test_cel.c.
References ao2_cleanup, ast_assert, ast_cel_backend_unregister(), ast_cel_set_config(), ast_cond_destroy, ast_mutex_destroy, check_events(), do_sleep(), NULL, RAII_VAR, sync_out, and TEST_BACKEND_NAME.
Referenced by load_module().
 {
    RAII_VAR(struct ao2_container *, local_expected, cel_expected_events, ao2_cleanup);
    RAII_VAR(struct ao2_container *, local_received, cel_received_events, ao2_cleanup);
    ast_assert(cel_received_events != NULL);
    ast_assert(cel_expected_events != NULL);
    do_sleep();
    /* stop the CEL event callback and clean up storage structures*/
    ast_cel_backend_unregister(TEST_BACKEND_NAME);
    /* cleaned up by RAII_VAR's */
    cel_expected_events = NULL;
    cel_received_events = NULL;
    /* check events */
    ast_test_validate(test, !check_events(test, local_expected, local_received));
    /* Restore the real CEL config */
    ast_cel_set_config(saved_config);
    ao2_cleanup(saved_config);
    saved_config = NULL;
    /* clean up the locks */
    ast_mutex_destroy(&sync_lock);
    ast_mutex_destroy(&mid_test_sync_lock);
    ast_cond_destroy(&sync_out);
    return 0;
 }
check_events()
static int check_events (struct ast_test * test, struct ao2_container * local_expected, struct ao2_container * local_received) static
Definition at line 2010 of file test_cel.c.
References ao2_cleanup, ao2_container_count(), ao2_iterator_destroy(), ao2_iterator_init(), ao2_iterator_next, AST_EVENT_CUSTOM, ast_event_get_type(), ast_test_status_update, debug, dump_event(), events_are_equal(), NULL, and RAII_VAR.
Referenced by cel_verify_and_cleanup_cb().
 {
    struct ao2_iterator received_it;
    struct ao2_iterator expected_it;
    RAII_VAR(struct ast_event *, rx_event, NULL, ao2_cleanup);
    RAII_VAR(struct ast_event *, ex_event, NULL, ao2_cleanup);
    int debug = 0;
    if (ao2_container_count(local_expected) != ao2_container_count(local_received)) {
       ast_test_status_update(test, "Increasing verbosity since the number of expected events (%d)"
          " did not match number of received events (%d).\n",
          ao2_container_count(local_expected),
          ao2_container_count(local_received));
       debug = 1;
    }
    received_it = ao2_iterator_init(local_received, 0);
    expected_it = ao2_iterator_init(local_expected, 0);
    rx_event = ao2_iterator_next(&received_it);
    ex_event = ao2_iterator_next(&expected_it);
    while (rx_event && ex_event) {
       if (!events_are_equal(test, rx_event, ex_event)) {
          ao2_iterator_destroy(&received_it);
          ao2_iterator_destroy(&expected_it);
          ast_test_status_update(test, "Received event:\n");
          dump_event(test, rx_event);
          ast_test_status_update(test, "Expected event:\n");
          dump_event(test, ex_event);
          return -1;
       }
       if (debug) {
          ast_test_status_update(test, "Compared events successfully%s\n",
             ast_event_get_type(ex_event) == AST_EVENT_CUSTOM
                ? " (wildcard match)" : "");
          dump_event(test, rx_event);
       }
       ao2_cleanup(rx_event);
       ao2_cleanup(ex_event);
       rx_event = ao2_iterator_next(&received_it);
       ex_event = ao2_iterator_next(&expected_it);
    }
    ao2_iterator_destroy(&received_it);
    ao2_iterator_destroy(&expected_it);
    if (rx_event) {
       ast_test_status_update(test, "Received event:\n");
       dump_event(test, rx_event);
       return -1;
    }
    if (ex_event) {
       ast_test_status_update(test, "Expected event:\n");
       dump_event(test, ex_event);
       return -1;
    }
    return 0;
 }
do_sleep()
static void do_sleep (void) static
Definition at line 87 of file test_cel.c.
References errno, and to_sleep.
Referenced by AST_TEST_DEFINE(), and cel_verify_and_cleanup_cb().
 {
    while ((nanosleep(&to_sleep, &to_sleep) == -1) && (errno == EINTR)) {
    }
 }
dump_event()
static int dump_event (struct ast_test * test, struct ast_event * event) static
Definition at line 1969 of file test_cel.c.
References ast_cel_get_type_name(), ast_event_get_ie_pltype(), ast_event_get_ie_type_name(), ast_event_get_ie_uint(), AST_EVENT_IE_CEL_EVENT_TYPE, AST_EVENT_IE_PLTYPE_STR, AST_EVENT_IE_PLTYPE_UINT, AST_EVENT_IE_PLTYPE_UNKNOWN, ast_event_iterator_get_ie_str(), ast_event_iterator_get_ie_type(), ast_event_iterator_get_ie_uint(), ast_event_iterator_init(), ast_event_iterator_next(), and ast_test_status_update.
Referenced by check_events().
 {
    struct ast_event_iterator i;
    if (ast_event_iterator_init(&i, event)) {
       ast_test_status_update(test, "Failed to initialize event iterator.  :-(\n");
       return 0;
    }
    ast_test_status_update(test, "Event: %s\n",
       ast_cel_get_type_name(ast_event_get_ie_uint(event, AST_EVENT_IE_CEL_EVENT_TYPE)));
    do {
       enum ast_event_ie_type ie_type;
       enum ast_event_ie_pltype ie_pltype;
       const char *ie_type_name;
       ie_type = ast_event_iterator_get_ie_type(&i);
       ie_type_name = ast_event_get_ie_type_name(ie_type);
       ie_pltype = ast_event_get_ie_pltype(ie_type);
       switch (ie_pltype) {
       case AST_EVENT_IE_PLTYPE_UNKNOWN:
       case AST_EVENT_IE_PLTYPE_STR:
          ast_test_status_update(test, "%.30s: %s\n", ie_type_name,
                ast_event_iterator_get_ie_str(&i));
          break;
       case AST_EVENT_IE_PLTYPE_UINT:
          ast_test_status_update(test, "%.30s: %u\n", ie_type_name,
                ast_event_iterator_get_ie_uint(&i));
          break;
       default:
          break;
       }
    } while (!ast_event_iterator_next(&i));
    ast_test_status_update(test, "\n");
    return 0;
 }
events_are_equal()
static int events_are_equal (struct ast_test * test, struct ast_event * received, struct ast_event * expected) static
Definition at line 1948 of file test_cel.c.
References AST_EVENT_CUSTOM, ast_event_get_ie_type_name(), ast_event_get_type(), ast_event_iterator_get_ie_type(), ast_event_iterator_init(), ast_event_iterator_next(), ast_test_status_update, and match_ie_val().
Referenced by check_events().
 {
    struct ast_event_iterator iterator;
    int res;
    if (ast_event_get_type(expected) == AST_EVENT_CUSTOM) {
       /* this event is flagged as a wildcard match */
       return 1;
    }
    for (res = ast_event_iterator_init(&iterator, received); !res; res = ast_event_iterator_next(&iterator)) {
       int ie_type = ast_event_iterator_get_ie_type(&iterator);
       if (!match_ie_val(received, expected, ie_type)) {
          ast_test_status_update(test, "Failed matching on field %s\n", ast_event_get_ie_type_name(ie_type));
          return 0;
       }
    }
    return 1;
 }
load_module()
static int load_module (void) static
Definition at line 2156 of file test_cel.c.
References ast_cel_general_config::apps, AST_CEL_ANSWER, AST_CEL_APP_START, AST_CEL_ATTENDEDTRANSFER, AST_CEL_BLINDTRANSFER, AST_CEL_BRIDGE_ENTER, AST_CEL_BRIDGE_EXIT, AST_CEL_CHANNEL_END, AST_CEL_CHANNEL_START, ast_cel_general_config_alloc(), AST_CEL_HANGUP, AST_CEL_LOCAL_OPTIMIZE, AST_CEL_PICKUP, ast_channel_register(), AST_MODULE_LOAD_SUCCESS, ast_str_container_add(), AST_TEST_REGISTER, ast_test_register_cleanup(), ast_test_register_init(), cel_verify_and_cleanup_cb(), ast_cel_general_config::enable, ast_cel_general_config::events, TEST_CATEGORY, and test_cel_init_cb().
 {
    /* build the test config */
    cel_test_config = ast_cel_general_config_alloc();
    if (!cel_test_config) {
       return -1;
    }
    cel_test_config->enable = 1;
    if (ast_str_container_add(cel_test_config->apps, "dial")) {
       return -1;
    }
    if (ast_str_container_add(cel_test_config->apps, "park")) {
       return -1;
    }
    if (ast_str_container_add(cel_test_config->apps, "queue")) {
       return -1;
    }
    cel_test_config->events |= 1<<AST_CEL_APP_START;
    cel_test_config->events |= 1<<AST_CEL_CHANNEL_START;
    cel_test_config->events |= 1<<AST_CEL_CHANNEL_END;
    cel_test_config->events |= 1<<AST_CEL_ANSWER;
    cel_test_config->events |= 1<<AST_CEL_HANGUP;
    cel_test_config->events |= 1<<AST_CEL_BRIDGE_ENTER;
    cel_test_config->events |= 1<<AST_CEL_BRIDGE_EXIT;
    cel_test_config->events |= 1<<AST_CEL_BLINDTRANSFER;
    cel_test_config->events |= 1<<AST_CEL_ATTENDEDTRANSFER;
    cel_test_config->events |= 1<<AST_CEL_PICKUP;
    cel_test_config->events |= 1<<AST_CEL_LOCAL_OPTIMIZE;
    ast_channel_register(&test_cel_chan_tech);
    AST_TEST_REGISTER(test_cel_channel_creation);
    AST_TEST_REGISTER(test_cel_unanswered_inbound_call);
    AST_TEST_REGISTER(test_cel_unanswered_outbound_call);
    AST_TEST_REGISTER(test_cel_single_party);
    AST_TEST_REGISTER(test_cel_single_bridge);
    AST_TEST_REGISTER(test_cel_single_bridge_continue);
    AST_TEST_REGISTER(test_cel_single_twoparty_bridge_a);
    AST_TEST_REGISTER(test_cel_single_twoparty_bridge_b);
 #ifdef RACEY_TESTS
    AST_TEST_REGISTER(test_cel_single_multiparty_bridge);
 #endif
    AST_TEST_REGISTER(test_cel_dial_unanswered);
    AST_TEST_REGISTER(test_cel_dial_unanswered_filter);
    AST_TEST_REGISTER(test_cel_dial_congestion);
    AST_TEST_REGISTER(test_cel_dial_busy);
    AST_TEST_REGISTER(test_cel_dial_unavailable);
    AST_TEST_REGISTER(test_cel_dial_caller_cancel);
    AST_TEST_REGISTER(test_cel_dial_parallel_failed);
    AST_TEST_REGISTER(test_cel_dial_answer_no_bridge);
    AST_TEST_REGISTER(test_cel_dial_answer_twoparty_bridge_a);
    AST_TEST_REGISTER(test_cel_dial_answer_twoparty_bridge_b);
 #ifdef RACEY_TESTS
    AST_TEST_REGISTER(test_cel_dial_answer_multiparty);
    AST_TEST_REGISTER(test_cel_attended_transfer_bridges_swap);
    AST_TEST_REGISTER(test_cel_attended_transfer_bridges_link);
 #endif
    AST_TEST_REGISTER(test_cel_blind_transfer);
    AST_TEST_REGISTER(test_cel_attended_transfer_bridges_merge);
    AST_TEST_REGISTER(test_cel_dial_pickup);
    AST_TEST_REGISTER(test_cel_local_optimize);
    /* ast_test_register_* has to happen after AST_TEST_REGISTER */
    /* Verify received vs expected events and clean things up after every test */
    ast_test_register_init(TEST_CATEGORY, test_cel_init_cb);
    ast_test_register_cleanup(TEST_CATEGORY, cel_verify_and_cleanup_cb);
    return AST_MODULE_LOAD_SUCCESS;
 }
match_ie_val()
static int match_ie_val (const struct ast_event * event1, const struct ast_event * event2, enum ast_event_ie_type type) static
Check an IE value from two events.
Return values
zero if the IEs in the events of the specified type do not match
non-zero if the IEs in the events of the specified type match
Definition at line 1895 of file test_cel.c.
References ast_event_get_ie_pltype(), ast_event_get_ie_str(), ast_event_get_ie_uint(), AST_EVENT_IE_CEL_EVENT_TIME, AST_EVENT_IE_CEL_EVENT_TIME_USEC, AST_EVENT_IE_CEL_PEER, AST_EVENT_IE_PLTYPE_BITFLAGS, AST_EVENT_IE_PLTYPE_RAW, AST_EVENT_IE_PLTYPE_STR, AST_EVENT_IE_PLTYPE_UINT, and test_cel_peer_strings_match().
Referenced by events_are_equal().
 {
    enum ast_event_ie_pltype pltype = ast_event_get_ie_pltype(type);
    /* XXX ignore sec/usec for now */
    if (type == AST_EVENT_IE_CEL_EVENT_TIME_USEC) {
       return 1;
    }
    if (type == AST_EVENT_IE_CEL_EVENT_TIME) {
       return 1;
    }
    switch (pltype) {
    case AST_EVENT_IE_PLTYPE_UINT:
    {
       uint32_t val = ast_event_get_ie_uint(event2, type);
       return (val == ast_event_get_ie_uint(event1, type)) ? 1 : 0;
    }
    case AST_EVENT_IE_PLTYPE_STR:
    {
       const char *str1 = ast_event_get_ie_str(event1, type);
       const char *str2 = ast_event_get_ie_str(event2, type);
       if (!str1 && !str2) {
          return 1;
       } else if (!str1) {
          return 0;
       } else if (!str2) {
          return 0;
       }
       /* use special matching for CEL PEER field */
       if (type == AST_EVENT_IE_CEL_PEER) {
          return test_cel_peer_strings_match(str1, str2);
       }
       return !strcmp(str1, str2);
    }
    case AST_EVENT_IE_PLTYPE_RAW:
    case AST_EVENT_IE_PLTYPE_BITFLAGS:
       /* Fall through: just pass on these types */
       return 1;
    default:
       break;
    }
    return 0;
 }
mid_test_sync()
static void mid_test_sync (void) static
Definition at line 1706 of file test_cel.c.
References ao2_container_count(), ast_cond_timedwait, ast_mutex_lock, ast_mutex_unlock, ast_tvnow(), do_mid_test_sync, lock, SCOPED_MUTEX, and sync_out.
 {
    ast_mutex_lock(&mid_test_sync_lock);
    if (ao2_container_count(cel_expected_events) <= ao2_container_count(cel_received_events)) {
       ast_mutex_unlock(&mid_test_sync_lock);
       return;
    }
    do_mid_test_sync = 1;
    ast_mutex_unlock(&mid_test_sync_lock);
    {
       struct timeval start = ast_tvnow();
       struct timespec end = {
          .tv_sec = start.tv_sec + 15,
          .tv_nsec = start.tv_usec * 1000
       };
       SCOPED_MUTEX(lock, &sync_lock);
       ast_cond_timedwait(&sync_out, &sync_lock, &end);
    }
 }
safe_bridge_destroy()
static void safe_bridge_destroy (struct ast_bridge * bridge) static
Definition at line 385 of file test_cel.c.
References ast_bridge_destroy().
Referenced by AST_TEST_DEFINE().
 {
    if (!bridge) {
       return;
    }
    ast_bridge_destroy(bridge, 0);
 }
safe_channel_release()
static void safe_channel_release (struct ast_channel * chan) static
Definition at line 377 of file test_cel.c.
References ast_channel_release().
Referenced by AST_TEST_DEFINE().
 {
    if (!chan) {
       return;
    }
    ast_channel_release(chan);
 }
test_cel_generate_peer_str()
static struct ast_str* test_cel_generate_peer_str (struct ast_channel * chan, struct ast_bridge * bridge) static
Definition at line 364 of file test_cel.c.
References ao2_cleanup, ast_channel_snapshot_get_latest(), ast_channel_uniqueid(), NULL, RAII_VAR, and test_cel_generate_peer_str_snapshot().
 {
    RAII_VAR(struct ast_channel_snapshot *, snapshot,
       ast_channel_snapshot_get_latest(ast_channel_uniqueid(chan)),
       ao2_cleanup);
    if (!snapshot) {
       return NULL;
    }
    return test_cel_generate_peer_str_snapshot(snapshot, bridge);
 }
test_cel_generate_peer_str_snapshot()
static struct ast_str* test_cel_generate_peer_str_snapshot (struct ast_channel_snapshot * chan, struct ast_bridge * bridge) static
Definition at line 351 of file test_cel.c.
References __test_cel_generate_peer_str(), ao2_cleanup, ast_bridge_get_snapshot(), NULL, and RAII_VAR.
Referenced by test_cel_generate_peer_str().
 {
    RAII_VAR(struct ast_bridge_snapshot *, snapshot,
       ast_bridge_get_snapshot(bridge),
       ao2_cleanup);
    if (!snapshot) {
       return NULL;
    }
    return __test_cel_generate_peer_str(chan, snapshot);
 }
test_cel_init_cb()
static int test_cel_init_cb (struct ast_test_info * info, struct ast_test * test) static
Definition at line 1825 of file test_cel.c.
References AO2_ALLOC_OPT_LOCK_MUTEX, ao2_container_alloc_list, ast_assert, ast_cel_backend_register(), ast_cel_get_config(), ast_cel_set_config(), ast_cond_init, ast_mutex_init, NULL, sync_out, TEST_BACKEND_NAME, and test_sub().
Referenced by load_module().
 {
    ast_assert(cel_received_events == NULL);
    ast_assert(cel_expected_events == NULL);
    ast_mutex_init(&mid_test_sync_lock);
    ast_mutex_init(&sync_lock);
    ast_cond_init(&sync_out, NULL);
    /* Back up the real CEL config and insert the test's config */
    saved_config = ast_cel_get_config();
    ast_cel_set_config(cel_test_config);
    /* init CEL event storage (degenerate hash table becomes a linked list) */
    cel_received_events = ao2_container_alloc_list(AO2_ALLOC_OPT_LOCK_MUTEX, 0, NULL, NULL);
    cel_expected_events = ao2_container_alloc_list(AO2_ALLOC_OPT_LOCK_MUTEX, 0, NULL, NULL);
    /* start the CEL event callback */
    if (ast_cel_backend_register(TEST_BACKEND_NAME, test_sub)) {
       return -1;
    }
    return 0;
 }
test_cel_peer_strings_match()
static int test_cel_peer_strings_match (const char * str1, const char * str2) static
Check two peer strings for equality.
Return values
zero if the peer strings do not match
non-zero if the peer strings match
Definition at line 1855 of file test_cel.c.
References ao2_cleanup, ao2_container_count(), ao2_find, ast_free, ast_str_container_add(), ast_str_container_alloc, ast_str_container_remove(), ast_strdup, OBJ_SEARCH_KEY, RAII_VAR, and strsep().
Referenced by match_ie_val().
 {
    RAII_VAR(struct ao2_container *, intersection, ast_str_container_alloc(11), ao2_cleanup);
    RAII_VAR(char *, str1_dup, ast_strdup(str1), ast_free);
    RAII_VAR(char *, str2_dup, ast_strdup(str2), ast_free);
    char *chan;
    if (!intersection) {
       return 1;
    }
    while ((chan = strsep(&str1_dup, ","))) {
       ast_str_container_add(intersection, chan);
    }
    while ((chan = strsep(&str2_dup, ","))) {
       RAII_VAR(char *, ao2_chan, ao2_find(intersection, chan, OBJ_SEARCH_KEY), ao2_cleanup);
       /* item in str2 not in str1 */
       if (!ao2_chan) {
          return 0;
       }
       ast_str_container_remove(intersection, chan);
    }
    /* item in str1 not in str2 */
    if (ao2_container_count(intersection)) {
       return 0;
    }
    return 1;
 }
test_sub()
static void test_sub (struct ast_event * event) static
Definition at line 1790 of file test_cel.c.
References ao2_cleanup, ao2_container_count(), ao2_dup_event(), ao2_link, ast_cond_signal, ast_event_get_ie_str(), AST_EVENT_IE_CEL_CHANNAME, CHANNEL_TECH_NAME, do_mid_test_sync, lock, RAII_VAR, SCOPED_MUTEX, and sync_out.
Referenced by presence_change_common(), and test_cel_init_cb().
 {
    RAII_VAR(struct ast_event *, event_dup, ao2_dup_event(event), ao2_cleanup);
    const char *chan_name;
    SCOPED_MUTEX(mid_test_lock, &mid_test_sync_lock);
    if (!event_dup) {
       return;
    }
    chan_name = ast_event_get_ie_str(event_dup, AST_EVENT_IE_CEL_CHANNAME);
    if (chan_name && strncmp(chan_name, CHANNEL_TECH_NAME, 14)) {
       return;
    }
    /* save the event for later processing */
    ao2_link(cel_received_events, event_dup);
    if (do_mid_test_sync) {
       int expected = ao2_container_count(cel_expected_events);
       int received = ao2_container_count(cel_received_events);
       if (expected <= received) {
          {
          SCOPED_MUTEX(lock, &sync_lock);
          ast_cond_signal(&sync_out);
          do_mid_test_sync = 0;
          }
       }
    }
 }
unload_module()
static int unload_module (void) static
Definition at line 2107 of file test_cel.c.
References ao2_cleanup, ast_channel_unregister(), AST_TEST_UNREGISTER, and NULL.
 {
    AST_TEST_UNREGISTER(test_cel_channel_creation);
    AST_TEST_UNREGISTER(test_cel_unanswered_inbound_call);
    AST_TEST_UNREGISTER(test_cel_unanswered_outbound_call);
    AST_TEST_UNREGISTER(test_cel_single_party);
    AST_TEST_UNREGISTER(test_cel_single_bridge);
    AST_TEST_UNREGISTER(test_cel_single_bridge_continue);
    AST_TEST_UNREGISTER(test_cel_single_twoparty_bridge_a);
    AST_TEST_UNREGISTER(test_cel_single_twoparty_bridge_b);
 #ifdef RACEY_TESTS
    AST_TEST_UNREGISTER(test_cel_single_multiparty_bridge);
 #endif
    AST_TEST_UNREGISTER(test_cel_dial_unanswered);
    AST_TEST_UNREGISTER(test_cel_dial_unanswered_filter);
    AST_TEST_UNREGISTER(test_cel_dial_congestion);
    AST_TEST_UNREGISTER(test_cel_dial_busy);
    AST_TEST_UNREGISTER(test_cel_dial_unavailable);
    AST_TEST_UNREGISTER(test_cel_dial_caller_cancel);
    AST_TEST_UNREGISTER(test_cel_dial_parallel_failed);
    AST_TEST_UNREGISTER(test_cel_dial_answer_no_bridge);
    AST_TEST_UNREGISTER(test_cel_dial_answer_twoparty_bridge_a);
    AST_TEST_UNREGISTER(test_cel_dial_answer_twoparty_bridge_b);
 #ifdef RACEY_TESTS
    AST_TEST_UNREGISTER(test_cel_dial_answer_multiparty);
    AST_TEST_UNREGISTER(test_cel_attended_transfer_bridges_swap);
    AST_TEST_UNREGISTER(test_cel_attended_transfer_bridges_link);
 #endif
    AST_TEST_UNREGISTER(test_cel_blind_transfer);
    AST_TEST_UNREGISTER(test_cel_attended_transfer_bridges_merge);
    AST_TEST_UNREGISTER(test_cel_dial_pickup);
    AST_TEST_UNREGISTER(test_cel_local_optimize);
    ast_channel_unregister(&test_cel_chan_tech);
    ao2_cleanup(cel_expected_events);
    cel_expected_events = NULL;
    ao2_cleanup(cel_received_events);
    cel_received_events = NULL;
    ao2_cleanup(cel_test_config);
    cel_test_config = NULL;
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "CEL unit tests" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, } static
Definition at line 2231 of file test_cel.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 2231 of file test_cel.c.
cel_expected_events
struct ao2_container* cel_expected_events = NULL static
Container for expected CEL events
Definition at line 1687 of file test_cel.c.
cel_received_events
struct ao2_container* cel_received_events = NULL static
Container for astobj2 duplicated ast_events
Definition at line 1684 of file test_cel.c.
cel_test_config
struct ast_cel_general_config* cel_test_config static
The CEL config used for CEL unit tests.
Definition at line 64 of file test_cel.c.
do_mid_test_sync
int do_mid_test_sync = 0
Flag used to trigger a mid-test synchronization, access controlled by mid_test_sync_lock.
Definition at line 76 of file test_cel.c.
Referenced by mid_test_sync(), and test_sub().
mid_test_sync_lock
ast_mutex_t mid_test_sync_lock
Lock used for synchronizing test execution stages with received events.
Definition at line 67 of file test_cel.c.
saved_config
struct ast_cel_general_config* saved_config static
A placeholder for Asterisk's 'real' CEL configuration.
Definition at line 61 of file test_cel.c.
sync_lock
ast_mutex_t sync_lock
Lock used with sync_out for checking the end of test execution.
Definition at line 70 of file test_cel.c.
sync_out
ast_cond_t sync_out
Condition used for checking the end of test execution.
Definition at line 73 of file test_cel.c.
Referenced by cel_verify_and_cleanup_cb(), mid_test_sync(), test_cel_init_cb(), and test_sub().
test_cel_chan_tech
struct ast_channel_tech test_cel_chan_tech static
Initial value:
= {
   .type = CHANNEL_TECH_NAME,
   .description = "Mock channel technology for CEL tests",
}
A channel technology used for the unit tests.
Definition at line 79 of file test_cel.c.
to_sleep
struct timespec to_sleep = {1, 0} static
A 1 second sleep.
Definition at line 85 of file test_cel.c.
Referenced by do_sleep().