Asterisk - The Open Source Telephony Project: test_websocket_client.c File Reference
test_websocket_client.c File Reference
Websocket Client Unit Tests.
#include "asterisk.h"
#include "asterisk/test.h"
#include "asterisk/module.h"
#include "asterisk/astobj2.h"
#include "asterisk/pbx.h"
#include "asterisk/http_websocket.h"
Macros
#define CATEGORY "/res/websocket/"
#define REMOTE_URL "ws://127.0.0.1:8088/ws"
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
AST_TEST_DEFINE (websocket_client_create_and_connect)
AST_TEST_DEFINE (websocket_client_bad_url)
AST_TEST_DEFINE (websocket_client_unsupported_protocol)
AST_TEST_DEFINE (websocket_client_multiple_protocols)
static int load_module (void)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_DEFAULT , .description = "Websocket client test module" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .requires = "res_http_websocket", }
static const struct ast_module_info * ast_module_info = &__mod_info
Detailed Description
Websocket Client Unit Tests.
Author
Kevin Harwell kharw.nosp@m.ell@.nosp@m.digiu.nosp@m.m.co.nosp@m.m
Definition in file test_websocket_client.c.
Macro Definition Documentation
CATEGORY
#define CATEGORY "/res/websocket/"
Definition at line 41 of file test_websocket_client.c.
Referenced by AST_TEST_DEFINE().
REMOTE_URL
#define REMOTE_URL "ws://127.0.0.1:8088/ws"
Definition at line 42 of file test_websocket_client.c.
Referenced by AST_TEST_DEFINE().
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 165 of file test_websocket_client.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 165 of file test_websocket_client.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 165 of file test_websocket_client.c.
AST_TEST_DEFINE() [1/4]
AST_TEST_DEFINE (websocket_client_create_and_connect)
Definition at line 44 of file test_websocket_client.c.
References ao2_cleanup, ast_free, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_websocket_client_create(), ast_websocket_read_string(), ast_websocket_write_string(), CATEGORY, sip_to_pjsip::info(), NULL, RAII_VAR, REMOTE_URL, result, TEST_EXECUTE, TEST_INIT, and write_buf().
 {
    RAII_VAR(struct ast_websocket *, client, NULL, ao2_cleanup);
    enum ast_websocket_result result;
    const char write_buf[] = "this is only a test";
    RAII_VAR(char *, read_buf, NULL, ast_free);
    switch (cmd) {
    case TEST_INIT:
       info->name = __func__;
       info->explicit_only = 1;
       info->category = CATEGORY;
       info->summary = "test creation and connection of a client websocket";
       info->description = "test creation and connection of a client websocket";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    ast_test_validate(test, (client = ast_websocket_client_create(
                 REMOTE_URL, "echo", NULL, &result)));
    ast_test_validate(test, !ast_websocket_write_string(client, write_buf));
    ast_test_validate(test, ast_websocket_read_string(client, &read_buf) > 0);
    ast_test_validate(test, !strcmp(write_buf, read_buf));
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [2/4]
AST_TEST_DEFINE (websocket_client_bad_url)
Definition at line 74 of file test_websocket_client.c.
References ao2_cleanup, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_websocket_client_create(), CATEGORY, sip_to_pjsip::info(), NULL, RAII_VAR, result, TEST_EXECUTE, and TEST_INIT.
 {
    RAII_VAR(struct ast_websocket *, client, NULL, ao2_cleanup);
    enum ast_websocket_result result;
    switch (cmd) {
    case TEST_INIT:
       info->name = __func__;
       info->category = CATEGORY;
       info->summary = "websocket client - test bad url";
       info->description = "pass a bad url and make sure it fails";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    ast_test_validate(test, !(client = ast_websocket_client_create(
                  "invalid", NULL, NULL, &result)));
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [3/4]
AST_TEST_DEFINE (websocket_client_unsupported_protocol)
Definition at line 95 of file test_websocket_client.c.
References ao2_cleanup, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_websocket_client_create(), CATEGORY, sip_to_pjsip::info(), NULL, RAII_VAR, REMOTE_URL, result, TEST_EXECUTE, and TEST_INIT.
 {
    RAII_VAR(struct ast_websocket *, client, NULL, ao2_cleanup);
    enum ast_websocket_result result;
    switch (cmd) {
    case TEST_INIT:
       info->name = __func__;
       info->category = CATEGORY;
       info->summary = "websocket client - unsupported protocol";
       info->description = "fails on an unsupported protocol";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    ast_test_validate(test, !(client = ast_websocket_client_create(
                  REMOTE_URL, "unsupported", NULL, &result)));
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [4/4]
AST_TEST_DEFINE (websocket_client_multiple_protocols)
Definition at line 116 of file test_websocket_client.c.
References ao2_cleanup, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_websocket_client_accept_protocol(), ast_websocket_client_create(), CATEGORY, sip_to_pjsip::info(), NULL, RAII_VAR, REMOTE_URL, result, TEST_EXECUTE, and TEST_INIT.
 {
    RAII_VAR(struct ast_websocket *, client, NULL, ao2_cleanup);
    const char *accept_protocol;
    enum ast_websocket_result result;
    switch (cmd) {
    case TEST_INIT:
       info->name = __func__;
       info->category = CATEGORY;
       info->summary = "websocket client - test multiple protocols";
       info->description = "test multi-protocol client";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    ast_test_validate(test, (client = ast_websocket_client_create(
                 REMOTE_URL, "echo,unsupported", NULL, &result)));
    accept_protocol = ast_websocket_client_accept_protocol(client);
    ast_test_validate(test, accept_protocol && !strcmp(accept_protocol, "echo"));
    return AST_TEST_PASS;
 }
load_module()
static int load_module (void) static
Definition at line 142 of file test_websocket_client.c.
References AST_MODULE_LOAD_SUCCESS, and AST_TEST_REGISTER.
Referenced by unload_module().
 {
    AST_TEST_REGISTER(websocket_client_create_and_connect);
    AST_TEST_REGISTER(websocket_client_bad_url);
    AST_TEST_REGISTER(websocket_client_unsupported_protocol);
    AST_TEST_REGISTER(websocket_client_multiple_protocols);
    return AST_MODULE_LOAD_SUCCESS;
 }
unload_module()
static int unload_module (void) static
Definition at line 151 of file test_websocket_client.c.
References AST_MODFLAG_DEFAULT, AST_MODULE_INFO(), AST_MODULE_SUPPORT_CORE, AST_TEST_UNREGISTER, ASTERISK_GPL_KEY, and load_module().
 {
    AST_TEST_UNREGISTER(websocket_client_multiple_protocols);
    AST_TEST_UNREGISTER(websocket_client_unsupported_protocol);
    AST_TEST_UNREGISTER(websocket_client_bad_url);
    AST_TEST_UNREGISTER(websocket_client_create_and_connect);
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_DEFAULT , .description = "Websocket client test module" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .requires = "res_http_websocket", } static
Definition at line 165 of file test_websocket_client.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 165 of file test_websocket_client.c.