Asterisk - The Open Source Telephony Project: hash_page.c File Reference
hash_page.c File Reference
#include <sys/types.h>
#include <errno.h>
#include <fcntl.h>
#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include "../include/db.h"
#include "hash.h"
#include "page.h"
#include "extern.h"
Macros
#define BYTE_MASK ((1 << INT_BYTE_SHIFT) -1)
#define OVMSG "HASH: Out of overflow pages. Increase page size\n"
#define PAGE_INIT(P)
Functions
BUFHEAD * __add_ovflpage (HTAB *hashp, BUFHEAD *bufp)
int __addel (HTAB *hashp, BUFHEAD *bufp, const DBT *key, const DBT *val)
int __delpair (HTAB *hashp, BUFHEAD *bufp, int ndx)
void __free_ovflpage (HTAB *hashp, BUFHEAD *obufp)
int __get_page (HTAB *hashp, char *p, u_int32_t bucket, int is_bucket, int is_disk, int is_bitmap)
int __ibitmap (HTAB *hashp, int pnum, int nbits, int ndx)
static u_int32_t *fetch_bitmap __P ((HTAB *, int))
static u_int32_t first_free __P ((u_int32_t))
static int open_temp __P ((HTAB *))
static void putpair __P ((char *, const DBT *, const DBT *))
static void squeeze_key __P ((u_int16_t *, const DBT *, const DBT *))
static int ugly_split __P ((HTAB *, u_int32_t, BUFHEAD *, BUFHEAD *, int, int))
int __put_page (HTAB *hashp, char *p, u_int32_t bucket, int is_bucket, int is_bitmap)
int __split_page (HTAB *hashp, u_int32_t obucket, u_int32_t nbucket)
static u_int32_t * fetch_bitmap (HTAB *hashp, int ndx)
static u_int32_t first_free (u_int32_t map)
static int open_temp (HTAB *hashp)
static u_int16_t overflow_page (HTAB *hashp)
static void putpair (char *p, const DBT *key, const DBT *val)
static void squeeze_key (u_int16_t *sp, const DBT *key, const DBT *val)
static int ugly_split (HTAB *hashp, u_int32_t obucket, BUFHEAD *old_bufp, BUFHEAD *new_bufp, int copyto, int moved)
Macro Definition Documentation
BYTE_MASK
#define BYTE_MASK ((1 << INT_BYTE_SHIFT) -1)
Definition at line 621 of file hash_page.c.
Referenced by __ibitmap().
OVMSG
#define OVMSG "HASH: Out of overflow pages. Increase page size\n"
Referenced by overflow_page().
PAGE_INIT
#define PAGE_INIT (P)
Value:
{ \
   ((u_int16_t *)(P))[0] = 0; \
   ((u_int16_t *)(P))[1] = hashp->BSIZE - 3 * sizeof(u_int16_t); \
   ((u_int16_t *)(P))[2] = hashp->BSIZE; \
}
Definition at line 84 of file hash_page.c.
Referenced by __get_page().
Function Documentation
__add_ovflpage()
BUFHEAD* __add_ovflpage (HTAB * hashp, BUFHEAD * bufp)
Definition at line 465 of file hash_page.c.
References __get_buf(), _bufhead::addr, BUF_MOD, DEF_FFACTOR, _bufhead::flags, FREESPACE, if(), MIN_FFACTOR, NULL, OFFSET, overflow_page(), _bufhead::ovfl, OVFLPAGE, OVFLSIZE, and _bufhead::page.
Referenced by __addel(), __big_insert(), __big_split(), and ugly_split().
 {
    register u_int16_t *sp;
    u_int16_t ndx, ovfl_num;
 #ifdef DEBUG1
    int tmp1, tmp2;
 #endif
    sp = (u_int16_t *)bufp->page;
    /* Check if we are dynamically determining the fill factor */
    if (hashp->FFACTOR == DEF_FFACTOR) {
       hashp->FFACTOR = sp[0] >> 1;
       if (hashp->FFACTOR < MIN_FFACTOR)
          hashp->FFACTOR = MIN_FFACTOR;
    }
    bufp->flags |= BUF_MOD;
    ovfl_num = overflow_page(hashp);
 #ifdef DEBUG1
    tmp1 = bufp->addr;
    tmp2 = bufp->ovfl ? bufp->ovfl->addr : 0;
 #endif
    if (!ovfl_num || !(bufp->ovfl = __get_buf(hashp, ovfl_num, bufp, 1)))
       return (NULL);
    bufp->ovfl->flags |= BUF_MOD;
 #ifdef DEBUG1
    (void)fprintf(stderr, "ADDOVFLPAGE: %d->ovfl was %d is now %d\n",
        tmp1, tmp2, bufp->ovfl->addr);
 #endif
    ndx = sp[0];
    /*
     * Since a pair is allocated on a page only if there's room to add
     * an overflow page, we know that the OVFL information will fit on
     * the page.
     */
    sp[ndx + 4] = OFFSET(sp);
    sp[ndx + 3] = FREESPACE(sp) - OVFLSIZE;
    sp[ndx + 1] = ovfl_num;
    sp[ndx + 2] = OVFLPAGE;
    sp[0] = ndx + 2;
 #ifdef HASH_STATISTICS
    hash_overflows++;
 #endif
    return (bufp->ovfl);
 }
__addel()
int __addel (HTAB * hashp, BUFHEAD * bufp, const DBT * key, const DBT * val)
Definition at line 398 of file hash_page.c.
References __add_ovflpage(), __big_insert(), __expand_table(), __get_buf(), BUF_MOD, _bufhead::flags, FREESPACE, FULL_KEY_DATA, if(), OVFLPAGE, _bufhead::page, PAIRFITS, PAIRSIZE, putpair(), REAL_KEY, squeeze_key(), and while().
Referenced by hash_access().
 {
    register u_int16_t *bp, *sop;
    int do_expand;
    bp = (u_int16_t *)bufp->page;
    do_expand = 0;
    while (bp[0] && (bp[2] < REAL_KEY || bp[bp[0]] < REAL_KEY))
       /* Exception case */
       if (bp[2] == FULL_KEY_DATA && bp[0] == 2)
          /* This is the last page of a big key/data pair
             and we need to add another page */
          break;
       else if (bp[2] < REAL_KEY && bp[bp[0]] != OVFLPAGE) {
          bufp = __get_buf(hashp, bp[bp[0] - 1], bufp, 0);
          if (!bufp)
             return (-1);
          bp = (u_int16_t *)bufp->page;
       } else
          /* Try to squeeze key on this page */
          if (FREESPACE(bp) > PAIRSIZE(key, val)) {
             squeeze_key(bp, key, val);
             return (0);
          } else {
             bufp = __get_buf(hashp, bp[bp[0] - 1], bufp, 0);
             if (!bufp)
                return (-1);
             bp = (u_int16_t *)bufp->page;
          }
    if (PAIRFITS(bp, key, val))
       putpair(bufp->page, key, val);
    else {
       do_expand = 1;
       bufp = __add_ovflpage(hashp, bufp);
       if (!bufp)
          return (-1);
       sop = (u_int16_t *)bufp->page;
       if (PAIRFITS(sop, key, val))
          putpair((char *)sop, key, val);
       else
          if (__big_insert(hashp, bufp, key, val))
             return (-1);
    }
    bufp->flags |= BUF_MOD;
    /*
     * If the average number of keys per bucket exceeds the fill factor,
     * expand the table.
     */
    hashp->NKEYS++;
    if (do_expand ||
        (hashp->NKEYS / (hashp->MAX_BUCKET + 1) > hashp->FFACTOR))
       return (__expand_table(hashp));
    return (0);
 }
__delpair()
int __delpair (HTAB * hashp, BUFHEAD * bufp, int ndx)
Definition at line 128 of file hash_page.c.
References __big_delete(), BUF_MOD, _bufhead::flags, if(), OFFSET, OVFLPAGE, _bufhead::page, and REAL_KEY.
Referenced by hash_access().
 {
    register u_int16_t *bp, newoff;
    register int n;
    u_int16_t pairlen;
    bp = (u_int16_t *)bufp->page;
    n = bp[0];
    if (bp[ndx + 1] < REAL_KEY)
       return (__big_delete(hashp, bufp));
    if (ndx != 1)
       newoff = bp[ndx - 1];
    else
       newoff = hashp->BSIZE;
    pairlen = newoff - bp[ndx + 1];
    if (ndx != (n - 1)) {
       /* Hard Case -- need to shuffle keys */
       register int i;
       register char *src = bufp->page + (int)OFFSET(bp);
       register char *dst = src + (int)pairlen;
       memmove(dst, src, bp[ndx + 1] - OFFSET(bp));
       /* Now adjust the pointers */
       for (i = ndx + 2; i <= n; i += 2) {
          if (bp[i + 1] == OVFLPAGE) {
             bp[i - 2] = bp[i];
             bp[i - 1] = bp[i + 1];
          } else {
             bp[i - 2] = bp[i] + pairlen;
             bp[i - 1] = bp[i + 1] + pairlen;
          }
       }
    }
    /* Finally adjust the page data */
    bp[n] = OFFSET(bp) + pairlen;
    bp[n - 1] = bp[n + 1] + pairlen + 2 * sizeof(u_int16_t);
    bp[0] = n - 2;
    hashp->NKEYS--;
    bufp->flags |= BUF_MOD;
    return (0);
 }
__free_ovflpage()
void __free_ovflpage (HTAB * hashp, BUFHEAD * obufp)
Definition at line 815 of file hash_page.c.
References __reclaim_buf(), _bufhead::addr, BYTE_SHIFT, CLRBIT, fetch_bitmap(), LAST_FREED, htab::mapp, SPLITMASK, and SPLITSHIFT.
Referenced by __big_delete(), and ugly_split().
 {
    register u_int16_t addr;
    u_int32_t *freep;
    int bit_address, free_page, free_bit;
    u_int16_t ndx;
    addr = obufp->addr;
 #ifdef DEBUG1
    (void)fprintf(stderr, "Freeing %d\n", addr);
 #endif
    ndx = (((u_int16_t)addr) >> SPLITSHIFT);
    bit_address =
        (ndx ? hashp->SPARES[ndx - 1] : 0) + (addr & SPLITMASK) - 1;
     if (bit_address < hashp->LAST_FREED)
       hashp->LAST_FREED = bit_address;
    free_page = (bit_address >> (hashp->BSHIFT + BYTE_SHIFT));
    free_bit = bit_address & ((hashp->BSIZE << BYTE_SHIFT) - 1);
    if (!(freep = hashp->mapp[free_page]))
       freep = fetch_bitmap(hashp, free_page);
 #ifdef DEBUG
    /*
     * This had better never happen.  It means we tried to read a bitmap
     * that has already had overflow pages allocated off it, and we
     * failed to read it from the file.
     */
    if (!freep)
       assert(0);
 #endif
    CLRBIT(freep, free_bit);
 #ifdef DEBUG2
    (void)fprintf(stderr, "FREE_OVFLPAGE: ADDR: %d BIT: %d PAGE %d\n",
        obufp->addr, free_bit, free_page);
 #endif
    __reclaim_buf(hashp, obufp);
 }
__get_page()
int __get_page (HTAB * hashp, char * p, u_int32_t bucket, int is_bucket, int is_disk, int is_bitmap)
Definition at line 518 of file hash_page.c.
References BUCKET_TO_PAGE, BYTE_ORDER, EFTYPE, errno, htab::fp, max, OADDR_TO_PAGE, and PAGE_INIT.
Referenced by __get_buf(), and fetch_bitmap().
 {
    register int fd, page, size;
    int rsize;
    u_int16_t *bp;
    fd = hashp->fp;
    size = hashp->BSIZE;
    if ((fd == -1) || !is_disk) {
       PAGE_INIT(p);
       return (0);
    }
    if (is_bucket)
       page = BUCKET_TO_PAGE(bucket);
    else
       page = OADDR_TO_PAGE(bucket);
    if ((lseek(fd, (off_t)page << hashp->BSHIFT, SEEK_SET) == -1) ||
        ((rsize = read(fd, p, size)) == -1))
       return (-1);
    bp = (u_int16_t *)p;
    if (!rsize)
       bp[0] = 0;  /* We hit the EOF, so initialize a new page */
    else
       if (rsize != size) {
          errno = EFTYPE;
          return (-1);
       }
    if (!is_bitmap && !bp[0]) {
       PAGE_INIT(p);
    } else
       if (hashp->LORDER != BYTE_ORDER) {
          register int i, max;
          if (is_bitmap) {
             max = hashp->BSIZE >> 2; /* divide by 4 */
             for (i = 0; i < max; i++)
                M_32_SWAP(((int *)p)[i]);
          } else {
             M_16_SWAP(bp[0]);
             max = bp[0] + 2;
             for (i = 1; i <= max; i++)
                M_16_SWAP(bp[i]);
          }
       }
    return (0);
 }
__ibitmap()
int __ibitmap (HTAB * hashp, int pnum, int nbits, int ndx)
Definition at line 627 of file hash_page.c.
References ALL_SET, BYTE_MASK, INT_BYTE_SHIFT, INT_TO_BYTE, malloc(), htab::mapp, htab::nmaps, NULL, and SETBIT.
Referenced by init_htab(), and overflow_page().
 {
    u_int32_t *ip;
    int clearbytes, clearints;
    if ((ip = (u_int32_t *)malloc(hashp->BSIZE)) == NULL)
       return (1);
    hashp->nmaps++;
    clearints = ((nbits - 1) >> INT_BYTE_SHIFT) + 1;
    clearbytes = clearints << INT_TO_BYTE;
    (void)memset((char *)ip, 0, clearbytes);
    (void)memset(((char *)ip) + clearbytes, 0xFF,
        hashp->BSIZE - clearbytes);
    ip[clearints - 1] = ALL_SET << (nbits & BYTE_MASK);
    SETBIT(ip, 0);
    hashp->BITMAPS[ndx] = (u_int16_t)pnum;
    hashp->mapp[ndx] = ip;
    return (0);
 }
__P() [1/6]
static u_int32_t* fetch_bitmap __P ((HTAB *, int)) static
__P() [2/6]
static u_int32_t first_free __P ((u_int32_t)) static
__P() [3/6]
static int open_temp __P ((HTAB *)) static
__P() [4/6]
static void putpair __P ((char *, const DBT *, const DBT *)) static
__P() [5/6]
static void squeeze_key __P ((u_int16_t *, const DBT *, const DBT *)) static
__P() [6/6]
static int ugly_split __P ((HTAB *, u_int32_t, BUFHEAD *, BUFHEAD *, int, int)) static
__put_page()
int __put_page (HTAB * hashp, char * p, u_int32_t bucket, int is_bucket, int is_bitmap)
Definition at line 578 of file hash_page.c.
References BUCKET_TO_PAGE, BYTE_ORDER, EFTYPE, errno, htab::fp, max, OADDR_TO_PAGE, and open_temp().
Referenced by __buf_free(), flush_meta(), and newbuf().
 {
    register int fd, page, size;
    int wsize;
    size = hashp->BSIZE;
    if ((hashp->fp == -1) && open_temp(hashp))
       return (-1);
    fd = hashp->fp;
    if (hashp->LORDER != BYTE_ORDER) {
       register int i;
       register int max;
       if (is_bitmap) {
          max = hashp->BSIZE >> 2;   /* divide by 4 */
          for (i = 0; i < max; i++)
             M_32_SWAP(((int *)p)[i]);
       } else {
          max = ((u_int16_t *)p)[0] + 2;
          for (i = 0; i <= max; i++)
             M_16_SWAP(((u_int16_t *)p)[i]);
       }
    }
    if (is_bucket)
       page = BUCKET_TO_PAGE(bucket);
    else
       page = OADDR_TO_PAGE(bucket);
    if ((lseek(fd, (off_t)page << hashp->BSHIFT, SEEK_SET) == -1) ||
        ((wsize = write(fd, p, size)) == -1))
       /* Errno is set */
       return (-1);
    if (wsize != size) {
       errno = EFTYPE;
       return (-1);
    }
    return (0);
 }
__split_page()
int __split_page (HTAB * hashp, u_int32_t obucket, u_int32_t nbucket)
Definition at line 181 of file hash_page.c.
References __call_hash(), __get_buf(), BUF_MOD, BUF_PIN, DBT::data, _bufhead::flags, FREESPACE, NULL, OFFSET, _bufhead::page, putpair(), REAL_KEY, retval, DBT::size, and ugly_split().
Referenced by __expand_table().
 {
    register BUFHEAD *new_bufp, *old_bufp;
    register u_int16_t *ino;
    register char *np;
    DBT key, val;
    int n, ndx, retval;
    u_int16_t copyto, diff, off, moved;
    char *op;
    copyto = (u_int16_t)hashp->BSIZE;
    off = (u_int16_t)hashp->BSIZE;
    old_bufp = __get_buf(hashp, obucket, NULL, 0);
    if (old_bufp == NULL)
       return (-1);
    new_bufp = __get_buf(hashp, nbucket, NULL, 0);
    if (new_bufp == NULL)
       return (-1);
    old_bufp->flags |= (BUF_MOD | BUF_PIN);
    new_bufp->flags |= (BUF_MOD | BUF_PIN);
    ino = (u_int16_t *)(op = old_bufp->page);
    np = new_bufp->page;
    moved = 0;
    for (n = 1, ndx = 1; n < ino[0]; n += 2) {
       if (ino[n + 1] < REAL_KEY) {
          retval = ugly_split(hashp, obucket, old_bufp, new_bufp,
              (int)copyto, (int)moved);
          old_bufp->flags &= ~BUF_PIN;
          new_bufp->flags &= ~BUF_PIN;
          return (retval);
       }
       key.data = (u_char *)op + ino[n];
       key.size = off - ino[n];
       if (__call_hash(hashp, key.data, key.size) == obucket) {
          /* Don't switch page */
          diff = copyto - off;
          if (diff) {
             copyto = ino[n + 1] + diff;
             memmove(op + copyto, op + ino[n + 1],
                 off - ino[n + 1]);
             ino[ndx] = copyto + ino[n] - ino[n + 1];
             ino[ndx + 1] = copyto;
          } else
             copyto = ino[n + 1];
          ndx += 2;
       } else {
          /* Switch page */
          val.data = (u_char *)op + ino[n + 1];
          val.size = ino[n] - ino[n + 1];
          putpair(np, &key, &val);
          moved += 2;
       }
       off = ino[n + 1];
    }
    /* Now clean up the page */
    ino[0] -= moved;
    FREESPACE(ino) = copyto - sizeof(u_int16_t) * (ino[0] + 3);
    OFFSET(ino) = copyto;
 #ifdef DEBUG3
    (void)fprintf(stderr, "split %d/%d\n",
        ((u_int16_t *)np)[0] / 2,
        ((u_int16_t *)op)[0] / 2);
 #endif
    /* unpin both pages */
    old_bufp->flags &= ~BUF_PIN;
    new_bufp->flags &= ~BUF_PIN;
    return (0);
 }
fetch_bitmap()
static u_int32_t* fetch_bitmap (HTAB * hashp, int ndx) static
Definition at line 910 of file hash_page.c.
References __get_buf(), __get_page(), free(), malloc(), htab::mapp, htab::nmaps, NULL, OVFLPAGE, _bufhead::page, REAL_KEY, and while().
Referenced by __free_ovflpage(), and overflow_page().
 {
    if (ndx >= hashp->nmaps)
       return (NULL);
    if ((hashp->mapp[ndx] = (u_int32_t *)malloc(hashp->BSIZE)) == NULL)
       return (NULL);
    if (__get_page(hashp,
        (char *)hashp->mapp[ndx], hashp->BITMAPS[ndx], 0, 1, 1)) {
       free(hashp->mapp[ndx]);
       return (NULL);
    }
    return (hashp->mapp[ndx]);
 }
first_free()
static u_int32_t first_free (u_int32_t map) static
Definition at line 650 of file hash_page.c.
References BITS_PER_MAP.
Referenced by overflow_page().
 {
    register u_int32_t i, mask;
    mask = 0x1;
    for (i = 0; i < BITS_PER_MAP; i++) {
       if (!(mask & map))
          return (i);
       mask = mask << 1;
    }
    return (i);
 }
open_temp()
static int open_temp (HTAB * hashp) static
Definition at line 861 of file hash_page.c.
References htab::fp, and NULL.
Referenced by __put_page().
 {
    sigset_t set, oset;
    static char namestr[] = "_hashXXXXXX";
    /* Block signals; make sure file goes away at process exit. */
    (void)sigfillset(&set);
    (void)sigprocmask(SIG_BLOCK, &set, &oset);
    if ((hashp->fp = mkstemp(namestr)) != -1) {
       (void)unlink(namestr);
       (void)fcntl(hashp->fp, F_SETFD, 1);
    }
    (void)sigprocmask(SIG_SETMASK, &oset, (sigset_t *)NULL);
    return (hashp->fp != -1 ? 0 : -1);
 }
overflow_page()
static u_int16_t overflow_page (HTAB * hashp) static
Definition at line 665 of file hash_page.c.
References __ibitmap(), ALL_SET, BITS_PER_MAP, BYTE_SHIFT, fetch_bitmap(), first_free(), htab::mapp, NCACHED, OADDR_OF, OVMSG, SETBIT, and SPLITMASK.
Referenced by __add_ovflpage().
 {
    register u_int32_t *freep = 0;
    register int max_free, offset, splitnum;
    u_int16_t addr;
    int bit, first_page, free_bit, free_page, i, in_use_bits, j;
 #ifdef DEBUG2
    int tmp1, tmp2;
 #endif
    splitnum = hashp->OVFL_POINT;
    max_free = hashp->SPARES[splitnum];
    free_page = (max_free - 1) >> (hashp->BSHIFT + BYTE_SHIFT);
    free_bit = (max_free - 1) & ((hashp->BSIZE << BYTE_SHIFT) - 1);
    /* Look through all the free maps to find the first free block */
    first_page = hashp->LAST_FREED >>(hashp->BSHIFT + BYTE_SHIFT);
    for ( i = first_page; i <= free_page; i++ ) {
       if (!(freep = (u_int32_t *)hashp->mapp[i]) &&
           !(freep = fetch_bitmap(hashp, i)))
          return (0);
       if (i == free_page)
          in_use_bits = free_bit;
       else
          in_use_bits = (hashp->BSIZE << BYTE_SHIFT) - 1;
       if (i == first_page) {
          bit = hashp->LAST_FREED &
              ((hashp->BSIZE << BYTE_SHIFT) - 1);
          j = bit / BITS_PER_MAP;
          bit = bit & ~(BITS_PER_MAP - 1);
       } else {
          bit = 0;
          j = 0;
       }
       for (; bit <= in_use_bits; j++, bit += BITS_PER_MAP)
          if (freep[j] != ALL_SET)
             goto found;
    }
    /* No Free Page Found */
    hashp->LAST_FREED = hashp->SPARES[splitnum];
    hashp->SPARES[splitnum]++;
    offset = hashp->SPARES[splitnum] -
        (splitnum ? hashp->SPARES[splitnum - 1] : 0);
 #define  OVMSG "HASH: Out of overflow pages.  Increase page size\n"
    if (offset > SPLITMASK) {
       if (++splitnum >= NCACHED) {
          if (write(STDERR_FILENO, OVMSG, sizeof(OVMSG) - 1) < 0) {
          }
          return (0);
       }
       hashp->OVFL_POINT = splitnum;
       hashp->SPARES[splitnum] = hashp->SPARES[splitnum-1];
       hashp->SPARES[splitnum-1]--;
       offset = 1;
    }
    /* Check if we need to allocate a new bitmap page */
    if (free_bit == (hashp->BSIZE << BYTE_SHIFT) - 1) {
       free_page++;
       if (free_page >= NCACHED) {
          if (write(STDERR_FILENO, OVMSG, sizeof(OVMSG) - 1) < 0) {
          }
          return (0);
       }
       /*
        * This is tricky.  The 1 indicates that you want the new page
        * allocated with 1 clear bit.  Actually, you are going to
        * allocate 2 pages from this map.  The first is going to be
        * the map page, the second is the overflow page we were
        * looking for.  The init_bitmap routine automatically, sets
        * the first bit of itself to indicate that the bitmap itself
        * is in use.  We would explicitly set the second bit, but
        * don't have to if we tell init_bitmap not to leave it clear
        * in the first place.
        */
       if (__ibitmap(hashp,
           (int)OADDR_OF(splitnum, offset), 1, free_page))
          return (0);
       hashp->SPARES[splitnum]++;
 #ifdef DEBUG2
       free_bit = 2;
 #endif
       offset++;
       if (offset > SPLITMASK) {
          if (++splitnum >= NCACHED) {
             if (write(STDERR_FILENO, OVMSG, sizeof(OVMSG) - 1) < 0) {
             }
             return (0);
          }
          hashp->OVFL_POINT = splitnum;
          hashp->SPARES[splitnum] = hashp->SPARES[splitnum-1];
          hashp->SPARES[splitnum-1]--;
          offset = 0;
       }
    } else {
       /*
        * Free_bit addresses the last used bit.  Bump it to address
        * the first available bit.
        */
       free_bit++;
       SETBIT(freep, free_bit);
    }
    /* Calculate address of the new overflow page */
    addr = OADDR_OF(splitnum, offset);
 #ifdef DEBUG2
    (void)fprintf(stderr, "OVERFLOW_PAGE: ADDR: %d BIT: %d PAGE %d\n",
        addr, free_bit, free_page);
 #endif
    return (addr);
 found:
    bit = bit + first_free(freep[j]);
    SETBIT(freep, bit);
 #ifdef DEBUG2
    tmp1 = bit;
    tmp2 = i;
 #endif
    /*
     * Bits are addressed starting with 0, but overflow pages are addressed
     * beginning at 1. Bit is a bit addressnumber, so we need to increment
     * it to convert it to a page number.
     */
    bit = 1 + bit + (i * (hashp->BSIZE << BYTE_SHIFT));
    if (bit >= hashp->LAST_FREED)
       hashp->LAST_FREED = bit - 1;
    /* Calculate the split number for this page */
    for (i = 0; (i < splitnum) && (bit > hashp->SPARES[i]); i++);
    offset = (i ? bit - hashp->SPARES[i - 1] : bit);
    if (offset >= SPLITMASK)
       return (0); /* Out of overflow pages */
    addr = OADDR_OF(i, offset);
 #ifdef DEBUG2
    (void)fprintf(stderr, "OVERFLOW_PAGE: ADDR: %d BIT: %d PAGE %d\n",
        addr, tmp1, tmp2);
 #endif
    /* Allocate and return the overflow page */
    return (addr);
 }
putpair()
static void putpair (char * p, const DBT * key, const DBT * val) static
Definition at line 96 of file hash_page.c.
References DBT::data, OFFSET, and DBT::size.
Referenced by __addel(), __split_page(), and ugly_split().
 {
    register u_int16_t *bp, n, off;
    bp = (u_int16_t *)p;
    /* Enter the key first. */
    n = bp[0];
    off = OFFSET(bp) - key->size;
    memmove(p + off, key->data, key->size);
    bp[++n] = off;
    /* Now the data. */
    off -= val->size;
    memmove(p + off, val->data, val->size);
    bp[++n] = off;
    /* Adjust page info. */
    bp[0] = n;
    bp[n + 1] = off - ((n + 3) * sizeof(u_int16_t));
    bp[n + 2] = off;
 }
squeeze_key()
static void squeeze_key (u_int16_t * sp, const DBT * key, const DBT * val) static
Definition at line 883 of file hash_page.c.
References DBT::data, FREESPACE, OFFSET, OVFLPAGE, PAIRSIZE, and DBT::size.
Referenced by __addel().
 {
    register char *p;
    u_int16_t free_space, n, off, pageno;
    p = (char *)sp;
    n = sp[0];
    free_space = FREESPACE(sp);
    off = OFFSET(sp);
    pageno = sp[n - 1];
    off -= key->size;
    sp[n - 1] = off;
    memmove(p + off, key->data, key->size);
    off -= val->size;
    sp[n] = off;
    memmove(p + off, val->data, val->size);
    sp[0] = n + 2;
    sp[n + 1] = pageno;
    sp[n + 2] = OVFLPAGE;
    FREESPACE(sp) = free_space - PAIRSIZE(key, val);
    OFFSET(sp) = off;
 }
ugly_split()
static int ugly_split (HTAB * hashp, u_int32_t obucket, BUFHEAD * old_bufp, BUFHEAD * new_bufp, int copyto, int moved) static
Definition at line 277 of file hash_page.c.
References __add_ovflpage(), __big_split(), __call_hash(), __free_ovflpage(), __get_buf(), _bufhead::addr, BUF_MOD, DBT::data, _bufhead::flags, FREESPACE, if(), SPLIT_RETURN::newp, SPLIT_RETURN::nextp, NULL, OFFSET, SPLIT_RETURN::oldp, OVFLPAGE, _bufhead::page, PAIRFITS, putpair(), REAL_KEY, and DBT::size.
Referenced by __split_page().
 {
    register BUFHEAD *bufp; /* Buffer header for ino */
    register u_int16_t *ino;   /* Page keys come off of */
    register u_int16_t *np; /* New page */
    register u_int16_t *op; /* Page keys go on to if they aren't moving */
    BUFHEAD *last_bfp;   /* Last buf header OVFL needing to be freed */
    DBT key, val;
    SPLIT_RETURN ret;
    u_int16_t n, off, ov_addr, scopyto;
    char *cino;    /* Character value of ino */
    bufp = old_bufp;
    ino = (u_int16_t *)old_bufp->page;
    np = (u_int16_t *)new_bufp->page;
    op = (u_int16_t *)old_bufp->page;
    last_bfp = NULL;
    scopyto = (u_int16_t)copyto;  /* ANSI */
    n = ino[0] - 1;
    while (n < ino[0]) {
       if (ino[2] < REAL_KEY && ino[2] != OVFLPAGE) {
          if (__big_split(hashp, old_bufp,
              new_bufp, bufp, bufp->addr, obucket, &ret))
             return (-1);
          old_bufp = ret.oldp;
          if (!old_bufp)
             return (-1);
          op = (u_int16_t *)old_bufp->page;
          new_bufp = ret.newp;
          if (!new_bufp)
             return (-1);
          np = (u_int16_t *)new_bufp->page;
          bufp = ret.nextp;
          if (!bufp)
             return (0);
          cino = (char *)bufp->page;
          ino = (u_int16_t *)cino;
          last_bfp = ret.nextp;
       } else if (ino[n + 1] == OVFLPAGE) {
          ov_addr = ino[n];
          /*
           * Fix up the old page -- the extra 2 are the fields
           * which contained the overflow information.
           */
          ino[0] -= (moved + 2);
          FREESPACE(ino) =
              scopyto - sizeof(u_int16_t) * (ino[0] + 3);
          OFFSET(ino) = scopyto;
          bufp = __get_buf(hashp, ov_addr, bufp, 0);
          if (!bufp)
             return (-1);
          ino = (u_int16_t *)bufp->page;
          n = 1;
          scopyto = hashp->BSIZE;
          moved = 0;
          if (last_bfp)
             __free_ovflpage(hashp, last_bfp);
          last_bfp = bufp;
       }
       /* Move regular sized pairs of there are any */
       off = hashp->BSIZE;
       for (n = 1; (n < ino[0]) && (ino[n + 1] >= REAL_KEY); n += 2) {
          cino = (char *)ino;
          key.data = (u_char *)cino + ino[n];
          key.size = off - ino[n];
          val.data = (u_char *)cino + ino[n + 1];
          val.size = ino[n] - ino[n + 1];
          off = ino[n + 1];
          if (__call_hash(hashp, key.data, key.size) == obucket) {
             /* Keep on old page */
             if (PAIRFITS(op, (&key), (&val)))
                putpair((char *)op, &key, &val);
             else {
                old_bufp =
                    __add_ovflpage(hashp, old_bufp);
                if (!old_bufp)
                   return (-1);
                op = (u_int16_t *)old_bufp->page;
                putpair((char *)op, &key, &val);
             }
             old_bufp->flags |= BUF_MOD;
          } else {
             /* Move to new page */
             if (PAIRFITS(np, (&key), (&val)))
                putpair((char *)np, &key, &val);
             else {
                new_bufp =
                    __add_ovflpage(hashp, new_bufp);
                if (!new_bufp)
                   return (-1);
                np = (u_int16_t *)new_bufp->page;
                putpair((char *)np, &key, &val);
             }
             new_bufp->flags |= BUF_MOD;
          }
       }
    }
    if (last_bfp)
       __free_ovflpage(hashp, last_bfp);
    return (0);
 }