Asterisk - The Open Source Telephony Project: chan_nbs.c File Reference
chan_nbs.c File Reference
Module: Asterisk Channel Drivers
Network broadcast sound support channel driver.
#include "asterisk.h"
#include <sys/socket.h>
#include <sys/time.h>
#include <arpa/inet.h>
#include <fcntl.h>
#include <sys/ioctl.h>
#include <nbs.h>
#include "asterisk/lock.h"
#include "asterisk/channel.h"
#include "asterisk/config.h"
#include "asterisk/module.h"
#include "asterisk/pbx.h"
#include "asterisk/utils.h"
#include "asterisk/format_cache.h"
Data Structures
struct nbs_pvt
Functions
AST_MODULE_INFO_STANDARD_DEPRECATED (ASTERISK_GPL_KEY, "Network Broadcast Sound Support")
static int load_module (void)
static struct nbs_pvt * nbs_alloc (const char *data)
static int nbs_call (struct ast_channel *ast, const char *dest, int timeout)
static void nbs_destroy (struct nbs_pvt *p)
static int nbs_hangup (struct ast_channel *ast)
static struct ast_channel * nbs_new (struct nbs_pvt *i, int state, const struct ast_assigned_ids *assignedids, const struct ast_channel *requestor)
static struct ast_channel * nbs_request (const char *type, struct ast_format_cap *cap, const struct ast_assigned_ids *assignedids, const struct ast_channel *requestor, const char *data, int *cause)
static struct ast_frame * nbs_xread (struct ast_channel *ast)
static int nbs_xwrite (struct ast_channel *ast, struct ast_frame *frame)
static int unload_module (void)
Variables
static char context [AST_MAX_EXTENSION] = "default"
static struct ast_channel_tech nbs_tech
static const char tdesc [] = "Network Broadcast Sound Driver"
static const char type [] = "NBS"
Detailed Description
Network broadcast sound support channel driver.
Author
Mark Spencer marks.nosp@m.ter@.nosp@m.digiu.nosp@m.m.co.nosp@m.m
Definition in file chan_nbs.c.
Function Documentation
AST_MODULE_INFO_STANDARD_DEPRECATED()
AST_MODULE_INFO_STANDARD_DEPRECATED (ASTERISK_GPL_KEY , "Network Broadcast Sound Support")
Referenced by load_module().
load_module()
static int load_module (void) static
Definition at line 257 of file chan_nbs.c.
References ao2_ref, ast_channel_register(), ast_format_cap_alloc, ast_format_cap_append, AST_FORMAT_CAP_FLAG_DEFAULT, ast_format_slin, ast_log, AST_MODULE_INFO_STANDARD_DEPRECATED(), AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, ASTERISK_GPL_KEY, ast_channel_tech::capabilities, LOG_ERROR, NULL, and type.
 {
    if (!(nbs_tech.capabilities = ast_format_cap_alloc(AST_FORMAT_CAP_FLAG_DEFAULT))) {
       return AST_MODULE_LOAD_DECLINE;
    }
    ast_format_cap_append(nbs_tech.capabilities, ast_format_slin, 0);
    /* Make sure we can register our channel type */
    if (ast_channel_register(&nbs_tech)) {
       ast_log(LOG_ERROR, "Unable to register channel class %s\n", type);
       ao2_ref(nbs_tech.capabilities, -1);
       nbs_tech.capabilities = NULL;
       return AST_MODULE_LOAD_DECLINE;
    }
    return AST_MODULE_LOAD_SUCCESS;
 }
nbs_alloc()
static struct nbs_pvt* nbs_alloc (const char * data) static
Definition at line 115 of file chan_nbs.c.
References ast_calloc, ast_copy_string(), ast_free, ast_log, ast_strlen_zero, LOG_WARNING, nbs_pvt::nbs, NULL, and nbs_pvt::stream.
Referenced by nbs_request().
 {
    struct nbs_pvt *p;
    int flags = 0;
    char stream[256];
    char *opts;
    ast_copy_string(stream, data, sizeof(stream));
    if ((opts = strchr(stream, ':'))) {
       *opts = '\0';
       opts++;
    } else
       opts = "";
    p = ast_calloc(1, sizeof(*p));
    if (p) {
       if (!ast_strlen_zero(opts)) {
          if (strchr(opts, 'm'))
             flags |= NBS_FLAG_MUTE;
          if (strchr(opts, 'o'))
             flags |= NBS_FLAG_OVERSPEAK;
          if (strchr(opts, 'e'))
             flags |= NBS_FLAG_EMERGENCY;
          if (strchr(opts, 'O'))
             flags |= NBS_FLAG_OVERRIDE;
       } else
          flags = NBS_FLAG_OVERSPEAK;
       ast_copy_string(p->stream, stream, sizeof(p->stream));
       p->nbs = nbs_newstream("asterisk", stream, flags);
       if (!p->nbs) {
          ast_log(LOG_WARNING, "Unable to allocate new NBS stream '%s' with flags %d\n", stream, flags);
          ast_free(p);
          p = NULL;
       } else {
          /* Set for 8000 hz mono, 640 samples */
          nbs_setbitrate(p->nbs, 8000);
          nbs_setchannels(p->nbs, 1);
          nbs_setblocksize(p->nbs, 640);
          nbs_setblocking(p->nbs, 0);
       }
    }
    return p;
 }
nbs_call()
static int nbs_call (struct ast_channel * ast, const char * dest, int timeout) static
Definition at line 81 of file chan_nbs.c.
References ast_channel_name(), ast_channel_tech_pvt(), AST_CONTROL_ANSWER, AST_CONTROL_CONGESTION, ast_debug, ast_log, ast_queue_control(), ast_setstate(), AST_STATE_DOWN, AST_STATE_RESERVED, AST_STATE_RINGING, LOG_WARNING, and nbs_pvt::nbs.
 {
    struct nbs_pvt *p;
    p = ast_channel_tech_pvt(ast);
    if ((ast_channel_state(ast) != AST_STATE_DOWN) && (ast_channel_state(ast) != AST_STATE_RESERVED)) {
       ast_log(LOG_WARNING, "nbs_call called on %s, neither down nor reserved\n", ast_channel_name(ast));
       return -1;
    }
    /* When we call, it just works, really, there's no destination...  Just
       ring the phone and wait for someone to answer */
    ast_debug(1, "Calling %s on %s\n", dest, ast_channel_name(ast));
    /* If we can't connect, return congestion */
    if (nbs_connect(p->nbs)) {
       ast_log(LOG_WARNING, "NBS Connection failed on %s\n", ast_channel_name(ast));
       ast_queue_control(ast, AST_CONTROL_CONGESTION);
    } else {
       ast_setstate(ast, AST_STATE_RINGING);
       ast_queue_control(ast, AST_CONTROL_ANSWER);
    }
    return 0;
 }
nbs_destroy()
static void nbs_destroy (struct nbs_pvt * p) static
Definition at line 107 of file chan_nbs.c.
References ast_free, ast_module_user_remove, nbs_pvt::nbs, and nbs_pvt::u.
Referenced by nbs_hangup(), and nbs_request().
 {
    if (p->nbs)
       nbs_delstream(p->nbs);
    ast_module_user_remove(p->u);
    ast_free(p);
 }
nbs_hangup()
static int nbs_hangup (struct ast_channel * ast) static
Definition at line 159 of file chan_nbs.c.
References ast_channel_name(), ast_channel_tech_pvt(), ast_channel_tech_pvt_set(), ast_debug, ast_log, ast_setstate(), AST_STATE_DOWN, LOG_WARNING, nbs_destroy(), and NULL.
 {
    struct nbs_pvt *p;
    p = ast_channel_tech_pvt(ast);
    ast_debug(1, "nbs_hangup(%s)\n", ast_channel_name(ast));
    if (!ast_channel_tech_pvt(ast)) {
       ast_log(LOG_WARNING, "Asked to hangup channel not connected\n");
       return 0;
    }
    nbs_destroy(p);
    ast_channel_tech_pvt_set(ast, NULL);
    ast_setstate(ast, AST_STATE_DOWN);
    return 0;
 }
nbs_new()
static struct ast_channel* nbs_new (struct nbs_pvt * i, int state, const struct ast_assigned_ids * assignedids, const struct ast_channel * requestor) static
Definition at line 193 of file chan_nbs.c.
References ast_channel_alloc, ast_channel_context_set(), ast_channel_exten_set(), ast_channel_name(), ast_channel_nativeformats_set(), ast_channel_rings_set(), ast_channel_set_fd(), ast_channel_set_rawreadformat(), ast_channel_set_rawwriteformat(), ast_channel_set_readformat(), ast_channel_set_writeformat(), ast_channel_tech_pvt_set(), ast_channel_tech_set(), ast_channel_unlock, ast_format_slin, ast_hangup(), ast_log, ast_module_user_add, ast_pbx_start(), AST_STATE_DOWN, AST_STATE_RING, ast_channel_tech::capabilities, context, LOG_WARNING, nbs_pvt::nbs, nbs_pvt::owner, nbs_pvt::stream, tmp(), and nbs_pvt::u.
Referenced by nbs_request().
 {
    struct ast_channel *tmp;
    tmp = ast_channel_alloc(1, state, 0, 0, "", "s", context, assignedids, requestor, 0, "NBS/%s", i->stream);
    if (tmp) {
       ast_channel_tech_set(tmp, &nbs_tech);
       ast_channel_set_fd(tmp, 0, nbs_fd(i->nbs));
       ast_channel_nativeformats_set(tmp, nbs_tech.capabilities);
       ast_channel_set_rawreadformat(tmp, ast_format_slin);
       ast_channel_set_rawwriteformat(tmp, ast_format_slin);
       ast_channel_set_writeformat(tmp, ast_format_slin);
       ast_channel_set_readformat(tmp, ast_format_slin);
       if (state == AST_STATE_RING)
          ast_channel_rings_set(tmp, 1);
       ast_channel_tech_pvt_set(tmp, i);
       ast_channel_context_set(tmp, context);
       ast_channel_exten_set(tmp, "s");
       ast_channel_language_set(tmp, "");
       i->owner = tmp;
       i->u = ast_module_user_add(tmp);
       ast_channel_unlock(tmp);
       if (state != AST_STATE_DOWN) {
          if (ast_pbx_start(tmp)) {
             ast_log(LOG_WARNING, "Unable to start PBX on %s\n", ast_channel_name(tmp));
             ast_hangup(tmp);
          }
       }
    } else
       ast_log(LOG_WARNING, "Unable to allocate channel structure\n");
    return tmp;
 }
nbs_request()
static struct ast_channel * nbs_request (const char * type, struct ast_format_cap * cap, const struct ast_assigned_ids * assignedids, const struct ast_channel * requestor, const char * data, int * cause) static
Definition at line 227 of file chan_nbs.c.
References ast_format_cap_get_names(), ast_format_cap_iscompatible_format(), AST_FORMAT_CAP_NAMES_LEN, AST_FORMAT_CMP_NOT_EQUAL, ast_format_slin, ast_log, AST_STATE_DOWN, ast_str_alloca, LOG_NOTICE, nbs_alloc(), nbs_destroy(), nbs_new(), NULL, and tmp().
 {
    struct nbs_pvt *p;
    struct ast_channel *tmp = NULL;
    if (ast_format_cap_iscompatible_format(cap, ast_format_slin) == AST_FORMAT_CMP_NOT_EQUAL) {
       struct ast_str *cap_buf = ast_str_alloca(AST_FORMAT_CAP_NAMES_LEN);
       ast_log(LOG_NOTICE, "Asked to get a channel of unsupported format '%s'\n",
          ast_format_cap_get_names(cap, &cap_buf));
       return NULL;
    }
    p = nbs_alloc(data);
    if (p) {
       tmp = nbs_new(p, AST_STATE_DOWN, assignedids, requestor);
       if (!tmp)
          nbs_destroy(p);
    }
    return tmp;
 }
nbs_xread()
static struct ast_frame * nbs_xread (struct ast_channel * ast) static
Definition at line 174 of file chan_nbs.c.
References ast_channel_name(), ast_debug, and ast_null_frame.
 {
    ast_debug(1, "Returning null frame on %s\n", ast_channel_name(ast));
    return &ast_null_frame;
 }
nbs_xwrite()
static int nbs_xwrite (struct ast_channel * ast, struct ast_frame * frame) static
Definition at line 181 of file chan_nbs.c.
References ast_channel_tech_pvt(), AST_STATE_UP, ast_frame::data, ast_frame::datalen, nbs_pvt::nbs, and ast_frame::ptr.
 {
    struct nbs_pvt *p = ast_channel_tech_pvt(ast);
    if (ast_channel_state(ast) != AST_STATE_UP) {
       /* Don't try tos end audio on-hook */
       return 0;
    }
    if (nbs_write(p->nbs, frame->data.ptr, frame->datalen / 2) < 0)
       return -1;
    return 0;
 }
unload_module()
static int unload_module (void) static
Definition at line 248 of file chan_nbs.c.
References ao2_ref, ast_channel_unregister(), ast_channel_tech::capabilities, and NULL.
 {
    /* First, take us out of the channel loop */
    ast_channel_unregister(&nbs_tech);
    ao2_ref(nbs_tech.capabilities, -1);
    nbs_tech.capabilities = NULL;
    return 0;
 }
Variable Documentation
context
char context[AST_MAX_EXTENSION] = "default" static
Definition at line 52 of file chan_nbs.c.
Referenced by nbs_new().
nbs_tech
struct ast_channel_tech nbs_tech static
Definition at line 71 of file chan_nbs.c.
tdesc
const char tdesc[] = "Network Broadcast Sound Driver" static
Definition at line 50 of file chan_nbs.c.
type
const char type[] = "NBS" static
Definition at line 53 of file chan_nbs.c.
Referenced by load_module().