Asterisk - The Open Source Telephony Project: res_pjsip_presence_xml.h File Reference
res_pjsip_presence_xml.h File Reference
Macros
#define AST_PJSIP_XML_PROLOG_LEN 39
Length of the XML prolog when printing presence or other XML in PJSIP.
Enumerations
enum ast_sip_pidf_state { NOTIFY_OPEN, NOTIFY_INUSE, NOTIFY_CLOSED }
Functions
void ast_sip_presence_exten_state_to_str (int state, char **statestring, char **pidfstate, char **pidfnote, enum ast_sip_pidf_state *local_state, unsigned int notify_early_inuse_ringing)
Convert extension state to relevant PIDF strings.
pj_xml_attr * ast_sip_presence_xml_create_attr (pj_pool_t *pool, pj_xml_node *node, const char *name, const char *value)
Create XML attribute.
pj_xml_node * ast_sip_presence_xml_create_node (pj_pool_t *pool, pj_xml_node *parent, const char *name)
Create XML node.
void ast_sip_presence_xml_find_node_attr (pj_pool_t *pool, pj_xml_node *parent, const char *node_name, const char *attr_name, pj_xml_node **node, pj_xml_attr **attr)
Find an attribute within a given node.
void ast_sip_sanitize_xml (const char *input, char *output, size_t len)
Replace offensive XML characters with XML entities.
Macro Definition Documentation
AST_PJSIP_XML_PROLOG_LEN
#define AST_PJSIP_XML_PROLOG_LEN 39
Length of the XML prolog when printing presence or other XML in PJSIP.
When calling any variant of pj_xml_print(), the documentation claims that it will return -1 if the provided buffer is not large enough. However, if the XML prolog is requested to be printed and the buffer is not large enough, then it will return -1 only if the buffer is not large enough to hold the XML prolog or return the length of the XML prolog on failure instead of -1.
This constant is useful to check against when trying to determine if printing XML succeeded or failed.
Definition at line 36 of file res_pjsip_presence_xml.h.
Referenced by dialog_info_to_string(), pidf_to_string(), rlmi_print_body(), and xpidf_to_string().
Enumeration Type Documentation
ast_sip_pidf_state
enum ast_sip_pidf_state
PIDF state
Enumerator
NOTIFY_OPEN
Device is not in use
NOTIFY_INUSE
Device is in use or ringing
NOTIFY_CLOSED
Device is unavailable, on hold, or busy
Definition at line 41 of file res_pjsip_presence_xml.h.
{
    /*! Device is not in use */
    NOTIFY_OPEN,
    /*! Device is in use or ringing */
    NOTIFY_INUSE,
    /*! Device is unavailable, on hold, or busy */
    NOTIFY_CLOSED
 };
Function Documentation
ast_sip_presence_exten_state_to_str()
void ast_sip_presence_exten_state_to_str (int state, char ** statestring, char ** pidfstate, char ** pidfnote, enum ast_sip_pidf_state * local_state, unsigned int notify_early_inuse_ringing)
Convert extension state to relevant PIDF strings.
Parameters
state The extension state
[out] statestring
[out] pidfstate
[out] pidfnote
[out] local_state
Definition at line 84 of file presence_xml.c.
References AST_EXTENSION_BUSY, AST_EXTENSION_INUSE, AST_EXTENSION_NOT_INUSE, AST_EXTENSION_ONHOLD, AST_EXTENSION_RINGING, AST_EXTENSION_UNAVAILABLE, NOTIFY_CLOSED, NOTIFY_INUSE, and NOTIFY_OPEN.
Referenced by dialog_info_generate_body_content(), pidf_generate_body_content(), pidf_supplement_body(), and xpidf_generate_body_content().
 {
    switch (state) {
    case AST_EXTENSION_RINGING:
       *statestring = "early";
       *local_state = NOTIFY_INUSE;
       *pidfstate = "on-the-phone";
       *pidfnote = "Ringing";
       break;
    case (AST_EXTENSION_INUSE | AST_EXTENSION_RINGING):
       if (notify_early_inuse_ringing) {
          *statestring = "early";
       } else {
          *statestring = "confirmed";
       }
       *local_state = NOTIFY_INUSE;
       *pidfstate = "on-the-phone";
       *pidfnote = "Ringing";
       break;
    case AST_EXTENSION_INUSE:
       *statestring = "confirmed";
       *local_state = NOTIFY_INUSE;
       *pidfstate = "on-the-phone";
       *pidfnote = "On the phone";
       break;
    case AST_EXTENSION_BUSY:
       *statestring = "confirmed";
       *local_state = NOTIFY_INUSE;
       *pidfstate = "on-the-phone";
       *pidfnote = "On the phone";
       break;
    case AST_EXTENSION_UNAVAILABLE:
       *statestring = "terminated";
       *local_state = NOTIFY_CLOSED;
       *pidfstate = "--";
       *pidfnote = "Unavailable";
       break;
    case AST_EXTENSION_ONHOLD:
       *statestring = "confirmed";
       *local_state = NOTIFY_INUSE;
       *pidfstate = "on-the-phone";
       *pidfnote = "On hold";
       break;
    case AST_EXTENSION_NOT_INUSE:
    default:
       /* Default setting */
       *statestring = "terminated";
       *local_state = NOTIFY_OPEN;
       *pidfstate = "--";
       *pidfnote = "Ready";
       break;
    }
 }
ast_sip_presence_xml_create_attr()
pj_xml_attr* ast_sip_presence_xml_create_attr (pj_pool_t * pool, pj_xml_node * node, const char * name, const char * value)
Create XML attribute.
Parameters
pool Allocation pool
node Node to add attribute to
name The attribute name
value The attribute value
Returns
The created attribute
Definition at line 140 of file presence_xml.c.
Referenced by add_eyebeam(), add_rlmi_resource(), ast_sip_presence_xml_find_node_attr(), build_rlmi_body(), dialog_info_generate_body_content(), pidf_supplement_body(), and xpidf_generate_body_content().
 {
    pj_xml_attr *attr = PJ_POOL_ALLOC_T(pool, pj_xml_attr);
    pj_strdup2(pool, &attr->name, name);
    pj_strdup2(pool, &attr->value, value);
    pj_xml_add_attr(node, attr);
    return attr;
 }
ast_sip_presence_xml_create_node()
pj_xml_node* ast_sip_presence_xml_create_node (pj_pool_t * pool, pj_xml_node * parent, const char * name)
Create XML node.
Parameters
pool Allocation pool
parent Optional node that will be parent to the created node
name The name for the new node
Returns
The created node
Definition at line 152 of file presence_xml.c.
References NULL.
Referenced by add_eyebeam(), add_rlmi_resource(), ast_sip_presence_xml_find_node_attr(), build_rlmi_body(), dialog_info_allocate_body(), dialog_info_generate_body_content(), and pidf_supplement_body().
 {
    pj_xml_node *node = PJ_POOL_ALLOC_T(pool, pj_xml_node);
    pj_list_init(&node->attr_head);
    pj_list_init(&node->node_head);
    pj_strdup2(pool, &node->name, name);
    node->content.ptr = NULL;
    node->content.slen = 0;
    if (parent) {
       pj_xml_add_node(parent, node);
    }
    return node;
 }
ast_sip_presence_xml_find_node_attr()
void ast_sip_presence_xml_find_node_attr (pj_pool_t * pool, pj_xml_node * parent, const char * node_name, const char * attr_name, pj_xml_node ** node, pj_xml_attr ** attr)
Find an attribute within a given node.
Given a starting node, this will find an attribute that belongs to a specific node. If the node does not exist, it will be created under the passed-in parent. If the attribute does not exist, then it will be created on the node with an empty string as its value.
Parameters
pool Allocation pool
parent Starting node for search
node_name Name of node where to find attribute
attr_name Name of attribute to find
[out] node Node that was found or created
[out] attr Attribute that was found or created
Returns
The found attribute
Definition at line 172 of file presence_xml.c.
References ast_sip_presence_xml_create_attr(), ast_sip_presence_xml_create_node(), name, and NULL.
Referenced by xpidf_generate_body_content().
 {
    pj_str_t name;
    if (!(*node = pj_xml_find_node(parent, pj_cstr(&name, node_name)))) {
       *node = ast_sip_presence_xml_create_node(pool, parent, node_name);
    }
    if (!(*attr = pj_xml_find_attr(*node, pj_cstr(&name, attr_name), NULL))) {
       *attr = ast_sip_presence_xml_create_attr(pool, *node, attr_name, "");
    }
 }
ast_sip_sanitize_xml()
void ast_sip_sanitize_xml (const char * input, char * output, size_t len)
Replace offensive XML characters with XML entities.
" = " < = <
= >
' = ' & = &
Parameters
input String to sanitize
[out] output Sanitized string
len Size of output buffer
Definition at line 29 of file presence_xml.c.
References ast_strdupa, and copy().
Referenced by AST_TEST_DEFINE(), dialog_info_generate_body_content(), pidf_generate_body_content(), pidf_supplement_body(), and xpidf_generate_body_content().
 {
    char *copy = ast_strdupa(input);
    char *break_point;
    size_t remaining = len - 1;
    output[0] = '\0';
    while ((break_point = strpbrk(copy, "<>\"&'\n\r")) && remaining) {
       char to_escape = *break_point;
       *break_point = '\0';
       strncat(output, copy, remaining);
       /* The strncat function will write remaining+1 if the string length is
        * equal to or greater than the size provided to it. We take this into
        * account by subtracting 1, which ensures that the NULL byte is written
        * inside of the provided buffer.
        */
       remaining = len - strlen(output) - 1;
       switch (to_escape) {
       case '<':
          strncat(output, "&lt;", remaining);
          break;
       case '>':
          strncat(output, "&gt;", remaining);
          break;
       case '"':
          strncat(output, "&quot;", remaining);
          break;
       case '&':
          strncat(output, "&amp;", remaining);
          break;
       case '\'':
          strncat(output, "&apos;", remaining);
          break;
       case '\r':
          strncat(output, "&#13;", remaining);
          break;
       case '\n':
          strncat(output, "&#10;", remaining);
          break;
       };
       copy = break_point + 1;
       remaining = len - strlen(output) - 1;
    }
    /* Be sure to copy everything after the final bracket */
    if (*copy && remaining) {
       strncat(output, copy, remaining);
    }
 }