Asterisk - The Open Source Telephony Project: pjsip_cli.c File Reference
pjsip_cli.c File Reference
#include "asterisk.h"
#include <pjsip.h>
#include <pjsip_ua.h>
#include "asterisk/res_pjsip.h"
#include "include/res_pjsip_private.h"
#include "asterisk/res_pjsip_cli.h"
#include "asterisk/acl.h"
#include "asterisk/cli.h"
#include "asterisk/astobj2.h"
#include "asterisk/hashtab.h"
#include "asterisk/utils.h"
#include "asterisk/sorcery.h"
Functions
int ast_sip_cli_print_sorcery_objectset (void *obj, void *arg, int flags)
Prints a sorcery object's ast_variable list.
char * ast_sip_cli_traverse_objects (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
void ast_sip_destroy_cli (void)
int ast_sip_initialize_cli (void)
struct ast_sip_cli_formatter_entry * ast_sip_lookup_cli_formatter (const char *name)
Looks up a CLI formatter by type.
int ast_sip_register_cli_formatter (struct ast_sip_cli_formatter_entry *formatter)
Registers a CLI formatter.
int ast_sip_unregister_cli_formatter (struct ast_sip_cli_formatter_entry *formatter)
Unregisters a CLI formatter.
static void complete_show_sorcery_object (struct ao2_container *container, struct ast_sip_cli_formatter_entry *formatter_entry, const char *word)
static void dump_str_and_free (int fd, struct ast_str *buf)
static int formatter_compare (void *obj, void *arg, int flags)
static int formatter_hash (const void *obj, int flags)
static int formatter_sort (const void *obj, const void *arg, int flags)
static char * handle_pjsip_show_version (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
Variables
static struct ao2_container * formatter_registry
static struct ast_cli_entry pjsip_cli []
Function Documentation
ast_sip_cli_print_sorcery_objectset()
int ast_sip_cli_print_sorcery_objectset (void * obj, void * arg, int flags)
Prints a sorcery object's ast_variable list.
Parameters
obj The sorcery object
arg The ast_sip_cli_context.
Return values
0 Success, non-zero on failure
Definition at line 36 of file pjsip_cli.c.
References ast_alloca, ast_sip_get_sorcery(), ast_sorcery_objectset_create, ast_str_append(), ast_variable_list_sort(), ast_variables_destroy(), context, ast_variable::name, ast_variable::next, ast_sip_cli_context::output_buffer, and ast_variable::value.
Referenced by cli_aor_print_body(), cli_endpoint_print_body(), cli_print_body(), sip_cli_print_global(), and sip_cli_print_system().
 {
    struct ast_sip_cli_context *context = arg;
    struct ast_variable *i;
    int max_name_width = 13;
    int max_value_width = 14;
    int width;
    char *separator;
    struct ast_variable *objset;
    if (!context->output_buffer) {
       return -1;
    }
    objset = ast_sorcery_objectset_create(ast_sip_get_sorcery(),obj);
    if (!objset) {
       return -1;
    }
    for (i = objset; i; i = i->next) {
       if (i->name) {
          width = strlen(i->name);
          max_name_width = width > max_name_width ? width : max_name_width;
       }
       if (i->value) {
          width = strlen(i->value);
          max_value_width = width > max_value_width ? width : max_value_width;
       }
    }
    separator = ast_alloca(max_name_width + max_value_width + 8);
    memset(separator, '=', max_name_width + max_value_width + 3);
    separator[max_name_width + max_value_width + 3] = 0;
    ast_str_append(&context->output_buffer, 0, " %-*s : %s\n", max_name_width, "ParameterName", "ParameterValue");
    ast_str_append(&context->output_buffer, 0, " %s\n", separator);
    objset = ast_variable_list_sort(objset);
    for (i = objset; i; i = i->next) {
       ast_str_append(&context->output_buffer, 0, " %-*s : %s\n", max_name_width, i->name, i->value);
    }
    ast_variables_destroy(objset);
    return 0;
 }
ast_sip_cli_traverse_objects()
char* ast_sip_cli_traverse_objects (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a)
Definition at line 109 of file pjsip_cli.c.
References ao2_callback, ao2_cleanup, ao2_container_count(), ast_cli_args::argc, ast_cli_args::argv, ast_cli(), ast_copy_string(), ast_ends_with(), ast_free, ast_log, ast_sip_lookup_cli_formatter(), ast_str_append(), ast_str_create, ast_strlen_zero, CLI_FAILURE, CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::cmda, complete_show_sorcery_object(), container, dump_str_and_free(), ast_cli_args::fd, ast_sip_cli_context::indent_level, LOG_ERROR, NULL, OBJ_NODATA, ast_sip_cli_context::output_buffer, RAII_VAR, ast_sip_cli_context::recurse, regex(), ast_sip_cli_context::show_details_only_level_0, and ast_cli_args::word.
Referenced by my_cli_traverse_objects().
 {
    RAII_VAR(struct ao2_container *, container, NULL, ao2_cleanup);
    RAII_VAR(struct ast_sip_cli_formatter_entry *, formatter_entry, NULL, ao2_cleanup);
    RAII_VAR(void *, object, NULL, ao2_cleanup);
    int is_container = 0;
    const char *cmd1;
    const char *cmd2;
    const char *object_id;
    char formatter_type[64];
    const char *regex;
    struct ast_sip_cli_context context = {
       .indent_level = 0,
       .show_details = 0,
       .show_details_only_level_0 = 0,
       .recurse = 0,
    };
    if (cmd == CLI_INIT) {
       return NULL;
    }
    cmd1 = e->cmda[1];
    cmd2 = e->cmda[2];
    object_id = a->argv[3];
    if (!ast_ends_with(cmd2, "s")) {
       ast_copy_string(formatter_type, cmd2, sizeof(formatter_type));
       is_container = 0;
    } else if (ast_ends_with(cmd2, "ies")) {
       /* Take the plural "ies" off of the object name and re[place with "y". */
       int l = strlen(cmd2);
       snprintf(formatter_type, 64, "%*.*sy", l - 3, l - 3, cmd2);
       is_container = 1;
    } else {
       /* Take the plural "s" off of the object name. */
       ast_copy_string(formatter_type, cmd2, strlen(cmd2));
       is_container = 1;
    }
    if (!strcmp(cmd1, "show")) {
       context.show_details_only_level_0 = !is_container;
       context.recurse = 1;
    } else {
       is_container = 1;
    }
    if (cmd != CLI_GENERATE
       && is_container
       && a->argc >= 4
       && strcmp(object_id, "like") == 0) {
       if (ast_strlen_zero(a->argv[4])) {
          return CLI_SHOWUSAGE;
       }
       regex = a->argv[4];
    } else {
       regex = "";
    }
    if (cmd == CLI_GENERATE
       && (is_container
          || a->argc > 4
          || (a->argc == 4 && ast_strlen_zero(a->word)))) {
       return CLI_SUCCESS;
    }
    context.output_buffer = ast_str_create(256);
    if (!context.output_buffer) {
       return CLI_FAILURE;
    }
    formatter_entry = ast_sip_lookup_cli_formatter(formatter_type);
    if (!formatter_entry) {
       ast_log(LOG_ERROR, "No formatter registered for object type %s.\n",
          formatter_type);
       ast_free(context.output_buffer);
       return CLI_FAILURE;
    }
    ast_str_append(&context.output_buffer, 0, "\n");
    formatter_entry->print_header(NULL, &context, 0);
    ast_str_append(&context.output_buffer, 0,
       "==========================================================================================\n\n");
    if (is_container || cmd == CLI_GENERATE) {
       container = formatter_entry->get_container(regex);
       if (!container) {
          ast_cli(a->fd, "No container returned for object type %s.\n",
             formatter_type);
          ast_free(context.output_buffer);
          return CLI_FAILURE;
       }
    }
    if (cmd == CLI_GENERATE) {
       ast_free(context.output_buffer);
       complete_show_sorcery_object(container, formatter_entry, a->word);
       return NULL;
    }
    if (is_container) {
       if (!ao2_container_count(container)) {
          ast_free(context.output_buffer);
          ast_cli(a->fd, "No objects found.\n\n");
          return CLI_SUCCESS;
       }
       ao2_callback(container, OBJ_NODATA, formatter_entry->print_body, &context);
       ast_str_append(&context.output_buffer, 0, "\nObjects found: %d\n", ao2_container_count(container));
    } else {
       if (ast_strlen_zero(object_id)) {
          ast_free(context.output_buffer);
          ast_cli(a->fd, "No object specified.\n");
          return CLI_FAILURE;
       }
       object = formatter_entry->retrieve_by_id(object_id);
       if (!object) {
          ast_free(context.output_buffer);
          ast_cli(a->fd, "Unable to find object %s.\n\n", object_id);
          return CLI_SUCCESS;
       }
       formatter_entry->print_body(object, &context, 0);
    }
    ast_str_append(&context.output_buffer, 0, "\n");
    dump_str_and_free(a->fd, context.output_buffer);
    return CLI_SUCCESS;
 }
ast_sip_destroy_cli()
void ast_sip_destroy_cli (void)
Definition at line 375 of file pjsip_cli.c.
References ao2_ref, ARRAY_LEN, and ast_cli_unregister_multiple().
Referenced by ast_res_pjsip_destroy_configuration().
 {
    ast_cli_unregister_multiple(pjsip_cli, ARRAY_LEN(pjsip_cli));
    ao2_ref(formatter_registry, -1);
 }
ast_sip_initialize_cli()
int ast_sip_initialize_cli (void)
Definition at line 360 of file pjsip_cli.c.
References AO2_ALLOC_OPT_LOCK_NOLOCK, ao2_container_alloc_hash, ARRAY_LEN, ast_cli_register_multiple, ast_log, formatter_compare(), formatter_hash(), formatter_sort(), and LOG_ERROR.
Referenced by ast_res_pjsip_initialize_configuration().
 {
    formatter_registry = ao2_container_alloc_hash(AO2_ALLOC_OPT_LOCK_NOLOCK, 0, 17,
       formatter_hash, formatter_sort, formatter_compare);
    if (!formatter_registry) {
       ast_log(LOG_ERROR, "Unable to create formatter_registry.\n");
       return -1;
    }
    ast_cli_register_multiple(pjsip_cli, ARRAY_LEN(pjsip_cli));
    return 0;
 }
ast_sip_lookup_cli_formatter()
struct ast_sip_cli_formatter_entry* ast_sip_lookup_cli_formatter (const char * name)
Looks up a CLI formatter by type.
Parameters
name The name of the formatter, usually the sorcery object type.
Return values
Pointer to formatter entry structure
Definition at line 305 of file pjsip_cli.c.
References ao2_find, OBJ_NOLOCK, and OBJ_SEARCH_KEY.
Referenced by ast_sip_cli_traverse_objects(), cli_aor_print_body(), cli_aor_print_header(), cli_endpoint_print_child_body(), and cli_endpoint_print_child_header().
 {
    return ao2_find(formatter_registry, name, OBJ_SEARCH_KEY | OBJ_NOLOCK);
 }
ast_sip_register_cli_formatter()
int ast_sip_register_cli_formatter (struct ast_sip_cli_formatter_entry * formatter)
Registers a CLI formatter.
Parameters
name The name of the formatter, usually the sorcery object type.
formatter An ao2_callback_fn that outputs the formatted data.
Return values
0 Success, non-zero on failure
Definition at line 310 of file pjsip_cli.c.
References ao2_link, ast_assert, ast_sip_cli_formatter_entry::get_container, ast_sip_cli_formatter_entry::get_id, ast_sip_cli_formatter_entry::iterate, ast_sip_cli_formatter_entry::name, NULL, ast_sip_cli_formatter_entry::print_body, ast_sip_cli_formatter_entry::print_header, and ast_sip_cli_formatter_entry::retrieve_by_id.
Referenced by ast_res_pjsip_initialize_configuration(), ast_sip_initialize_distributor(), ast_sip_initialize_sorcery_auth(), ast_sip_initialize_sorcery_location(), ast_sip_initialize_sorcery_transport(), load_module(), and pjsip_channel_cli_register().
 {
    ast_assert(formatter != NULL);
    ast_assert(formatter->name != NULL);
    ast_assert(formatter->print_body != NULL);
    ast_assert(formatter->print_header != NULL);
    ast_assert(formatter->get_container != NULL);
    ast_assert(formatter->iterate != NULL);
    ast_assert(formatter->get_id != NULL);
    ast_assert(formatter->retrieve_by_id != NULL);
    ao2_link(formatter_registry, formatter);
    return 0;
 }
ast_sip_unregister_cli_formatter()
int ast_sip_unregister_cli_formatter (struct ast_sip_cli_formatter_entry * formatter)
Unregisters a CLI formatter.
Parameters
name The name of the formatter, usually the sorcery object type.
Return values
0 Success, non-zero on failure
Definition at line 326 of file pjsip_cli.c.
References ao2_ref, ao2_unlink_flags, ao2_unlock, ao2_wrlock, and OBJ_NOLOCK.
Referenced by ast_res_pjsip_destroy_configuration(), ast_sip_destroy_distributor(), ast_sip_destroy_sorcery_auth(), ast_sip_destroy_sorcery_location(), ast_sip_destroy_sorcery_transport(), pjsip_channel_cli_unregister(), and unload_module().
 {
    if (formatter) {
       ao2_wrlock(formatter_registry);
       if (ao2_ref(formatter, -1) == 2) {
          ao2_unlink_flags(formatter_registry, formatter, OBJ_NOLOCK);
       }
       ao2_unlock(formatter_registry);
    }
    return 0;
 }
complete_show_sorcery_object()
static void complete_show_sorcery_object (struct ao2_container * container, struct ast_sip_cli_formatter_entry * formatter_entry, const char * word) static
Definition at line 85 of file pjsip_cli.c.
References ao2_iterator_destroy(), ao2_iterator_init(), ao2_t_iterator_next, ao2_t_ref, ast_cli_completion_add(), ast_strdup, ast_sip_cli_formatter_entry::get_id, and ast_variable::object.
Referenced by ast_sip_cli_traverse_objects().
 {
    size_t wordlen = strlen(word);
    void *object;
    struct ao2_iterator i = ao2_iterator_init(container, 0);
    while ((object = ao2_t_iterator_next(&i, "iterate thru endpoints table"))) {
       const char *id = formatter_entry->get_id(object);
       if (!strncasecmp(word, id, wordlen)) {
          ast_cli_completion_add(ast_strdup(id));
       }
       ao2_t_ref(object, -1, "toss iterator endpoint ptr before break");
    }
    ao2_iterator_destroy(&i);
 }
dump_str_and_free()
static void dump_str_and_free (int fd, struct ast_str * buf) static
Definition at line 103 of file pjsip_cli.c.
References ast_cli(), ast_free, and ast_str_buffer().
Referenced by ast_sip_cli_traverse_objects().
 {
    ast_cli(fd, "%s", ast_str_buffer(buf));
    ast_free(buf);
 }
formatter_compare()
static int formatter_compare (void * obj, void * arg, int flags) static
Definition at line 264 of file pjsip_cli.c.
References CMP_MATCH, CMP_STOP, ast_sip_cli_formatter_entry::name, OBJ_SEARCH_KEY, OBJ_SEARCH_MASK, OBJ_SEARCH_OBJECT, and OBJ_SEARCH_PARTIAL_KEY.
Referenced by ast_sip_initialize_cli().
 {
    const struct ast_sip_cli_formatter_entry *left_obj = obj;
    const struct ast_sip_cli_formatter_entry *right_obj = arg;
    const char *right_key = arg;
    int cmp = 0;
    switch (flags & OBJ_SEARCH_MASK) {
    case OBJ_SEARCH_OBJECT:
       right_key = right_obj->name;
       /* Fall through */
    case OBJ_SEARCH_KEY:
       if (strcmp(left_obj->name, right_key) == 0) {;
          cmp = CMP_MATCH | CMP_STOP;
       }
       break;
    case OBJ_SEARCH_PARTIAL_KEY:
       if (strncmp(left_obj->name, right_key, strlen(right_key)) == 0) {
          cmp = CMP_MATCH;
       }
       break;
    default:
       cmp = 0;
       break;
    }
    return cmp;
 }
formatter_hash()
static int formatter_hash (const void * obj, int flags) static
Definition at line 293 of file pjsip_cli.c.
References ast_str_hash(), ast_sip_cli_formatter_entry::name, OBJ_SEARCH_KEY, and OBJ_SEARCH_OBJECT.
Referenced by ast_sip_initialize_cli().
 {
    const struct ast_sip_cli_formatter_entry *left_obj = obj;
    if (flags & OBJ_SEARCH_OBJECT) {
       return ast_str_hash(left_obj->name);
    } else if (flags & OBJ_SEARCH_KEY) {
       return ast_str_hash(obj);
    }
    return -1;
 }
formatter_sort()
static int formatter_sort (const void * obj, const void * arg, int flags) static
Definition at line 239 of file pjsip_cli.c.
References ast_sip_cli_formatter_entry::name, OBJ_SEARCH_KEY, OBJ_SEARCH_MASK, OBJ_SEARCH_OBJECT, and OBJ_SEARCH_PARTIAL_KEY.
Referenced by ast_sip_initialize_cli().
 {
    const struct ast_sip_cli_formatter_entry *left_obj = obj;
    const struct ast_sip_cli_formatter_entry *right_obj = arg;
    const char *right_key = arg;
    int cmp = 0;
    switch (flags & OBJ_SEARCH_MASK) {
    case OBJ_SEARCH_OBJECT:
       right_key = right_obj->name;
       /* Fall through */
    case OBJ_SEARCH_KEY:
       cmp = strcmp(left_obj->name, right_key);
       break;
    case OBJ_SEARCH_PARTIAL_KEY:
       cmp = strncmp(left_obj->name, right_key, strlen(right_key));
       break;
    default:
       cmp = 0;
       break;
    }
    return cmp;
 }
handle_pjsip_show_version()
static char* handle_pjsip_show_version (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) static
Definition at line 338 of file pjsip_cli.c.
References ast_cli(), CLI_GENERATE, CLI_INIT, CLI_SUCCESS, ast_cli_entry::command, ast_cli_args::fd, NULL, and ast_cli_entry::usage.
 {
    switch(cmd) {
    case CLI_INIT:
       e->command = "pjsip show version";
       e->usage =
          "Usage: pjsip show version\n"
          "       Show the version of pjproject that res_pjsip is running against\n";
       return NULL;
    case CLI_GENERATE:
       return NULL;
    }
    ast_cli(a->fd, "PJPROJECT version currently running against: %s\n", pj_get_version());
    return CLI_SUCCESS;
 }
Variable Documentation
formatter_registry
struct ao2_container* formatter_registry static
Definition at line 34 of file pjsip_cli.c.
pjsip_cli
struct ast_cli_entry pjsip_cli[] static
Initial value:
= {
   { .handler =  handle_pjsip_show_version , .summary =  "Show the version of pjproject in use" ,},
}
Definition at line 356 of file pjsip_cli.c.