Asterisk - The Open Source Telephony Project: ast_app_stack_funcs Struct Reference
ast_app_stack_funcs Struct Reference
Stack applications callback functions.
#include <app.h>
Data Fields
const char *(* expand_sub_args)(struct ast_channel *chan, const char *args)
Add missing context/exten to Gosub application argument string.
void * module
int(* run_sub)(struct ast_channel *chan, const char *args, int ignore_hangup)
Callback for the routine to run a subroutine on a channel.
Detailed Description
Stack applications callback functions.
Examples:
/usr/src/asterisk-18.5.0/main/app.c.
Definition at line 190 of file include/asterisk/app.h.
Field Documentation
expand_sub_args
const char*(* expand_sub_args) (struct ast_channel *chan, const char *args)
Add missing context/exten to Gosub application argument string.
Parameters
chan Channel to obtain context/exten.
args Gosub application argument string.
Fills in the optional context and exten from the given channel.
Return values
New-args Gosub argument string on success. Must be freed.
NULL on error.
Examples:
/usr/src/asterisk-18.5.0/main/app.c.
Definition at line 223 of file include/asterisk/app.h.
Referenced by ast_app_expand_sub_args().
module
void* module
Module reference pointer so the module will stick around while a callback is active.
Examples:
/usr/src/asterisk-18.5.0/main/app.c.
Definition at line 195 of file include/asterisk/app.h.
Referenced by ast_app_exec_sub(), ast_app_expand_sub_args(), and load_module().
run_sub
int(* run_sub) (struct ast_channel *chan, const char *args, int ignore_hangup)
Callback for the routine to run a subroutine on a channel.
Note
Absolutely NO channel locks should be held before calling this function.
Parameters
chan Channel to execute subroutine on.
args Gosub application argument string.
ignore_hangup TRUE if a hangup does not stop execution of the routine.
Return values
0 success
-1 on error
Examples:
/usr/src/asterisk-18.5.0/main/app.c.
Definition at line 209 of file include/asterisk/app.h.
Referenced by ast_app_exec_sub(), and load_module().
The documentation for this struct was generated from the following file:
include/asterisk/app.h