Asterisk - The Open Source Telephony Project: res_pjsip_pidf_eyebeam_body_supplement.c File Reference
res_pjsip_pidf_eyebeam_body_supplement.c File Reference
#include "asterisk.h"
#include <pjsip.h>
#include <pjsip_simple.h>
#include <pjlib.h>
#include "asterisk/module.h"
#include "asterisk/res_pjsip.h"
#include "asterisk/res_pjsip_pubsub.h"
#include "asterisk/res_pjsip_presence_xml.h"
#include "asterisk/res_pjsip_body_generator_types.h"
Functions
static void __reg_module (void)
static void __unreg_module (void)
static void add_eyebeam (pj_pool_t *pool, pj_xml_node *node, const char *pidfstate)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int load_module (void)
static int pidf_supplement_body (void *body, void *data)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "PJSIP PIDF Eyebeam supplement" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_CHANNEL_DEPEND, .requires = "res_pjsip,res_pjsip_pubsub", }
static const struct ast_module_info * ast_module_info = &__mod_info
static struct ast_sip_pubsub_body_supplement pidf_supplement
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 113 of file res_pjsip_pidf_eyebeam_body_supplement.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 113 of file res_pjsip_pidf_eyebeam_body_supplement.c.
add_eyebeam()
static void add_eyebeam (pj_pool_t * pool, pj_xml_node * node, const char * pidfstate) static
Definition at line 47 of file res_pjsip_pidf_eyebeam_body_supplement.c.
References ast_alloca, ast_sip_presence_xml_create_attr(), and ast_sip_presence_xml_create_node().
Referenced by pidf_supplement_body().
 {
    static const char *XMLNS_DM_PREFIX = "xmlns:dm";
    static const char *XMLNS_DM = "urn:ietf:params:xml:ns:pidf:data-model";
    static const char *XMLNS_RPID_PREFIX = "xmlns:rpid";
    static const char *XMLNS_RPID = "urn:ietf:params:xml:ns:pidf:rpid";
    pj_xml_node *person = ast_sip_presence_xml_create_node(pool, node, "dm:person");
    if (pidfstate[0] != '-') {
       pj_xml_node *activities = ast_sip_presence_xml_create_node(pool, person, "rpid:activities");
       size_t str_size = sizeof("rpid:") + strlen(pidfstate);
       char *act_str = ast_alloca(str_size);
       /* Safe */
       strcpy(act_str, "rpid:");
       strcat(act_str, pidfstate);
       ast_sip_presence_xml_create_node(pool, activities, act_str);
    }
    ast_sip_presence_xml_create_attr(pool, node, XMLNS_DM_PREFIX, XMLNS_DM);
    ast_sip_presence_xml_create_attr(pool, node, XMLNS_RPID_PREFIX, XMLNS_RPID);
 }
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 113 of file res_pjsip_pidf_eyebeam_body_supplement.c.
load_module()
static int load_module (void) static
Definition at line 93 of file res_pjsip_pidf_eyebeam_body_supplement.c.
References AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, and ast_sip_pubsub_register_body_supplement().
Referenced by unload_module().
 {
    if (ast_sip_pubsub_register_body_supplement(&pidf_supplement)) {
       return AST_MODULE_LOAD_DECLINE;
    }
    return AST_MODULE_LOAD_SUCCESS;
 }
pidf_supplement_body()
static int pidf_supplement_body (void * body, void * data) static
Definition at line 73 of file res_pjsip_pidf_eyebeam_body_supplement.c.
References add_eyebeam(), ast_sip_presence_exten_state_to_str(), ast_sip_exten_state_data::exten_state, NULL, and ast_sip_exten_state_data::pool.
 {
    pjpidf_pres *pres = body;
    struct ast_sip_exten_state_data *state_data = data;
    char *statestring = NULL, *pidfstate = NULL, *pidfnote = NULL;
    enum ast_sip_pidf_state local_state;
    ast_sip_presence_exten_state_to_str(state_data->exten_state, &statestring,
          &pidfstate, &pidfnote, &local_state, 0);
    add_eyebeam(state_data->pool, pres, pidfstate);
    return 0;
 }
unload_module()
static int unload_module (void) static
Definition at line 101 of file res_pjsip_pidf_eyebeam_body_supplement.c.
References AST_MODFLAG_LOAD_ORDER, AST_MODPRI_CHANNEL_DEPEND, AST_MODULE_INFO(), AST_MODULE_SUPPORT_CORE, ast_sip_pubsub_unregister_body_supplement(), ASTERISK_GPL_KEY, and load_module().
 {
    ast_sip_pubsub_unregister_body_supplement(&pidf_supplement);
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "PJSIP PIDF Eyebeam supplement" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_CHANNEL_DEPEND, .requires = "res_pjsip,res_pjsip_pubsub", } static
Definition at line 113 of file res_pjsip_pidf_eyebeam_body_supplement.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 113 of file res_pjsip_pidf_eyebeam_body_supplement.c.
pidf_supplement
struct ast_sip_pubsub_body_supplement pidf_supplement static
Initial value:
= {
   .type = "application",
   .subtype = "pidf+xml",
   .supplement_body = pidf_supplement_body,
}
Definition at line 87 of file res_pjsip_pidf_eyebeam_body_supplement.c.