Asterisk - The Open Source Telephony Project: utils.c File Reference
channels/sip/utils.c File Reference
Utility functions for chan_sip.
#include "asterisk.h"
#include "asterisk/utils.h"
#include "asterisk/cli.h"
#include "include/sip.h"
#include "include/sip_utils.h"
Functions
const char * comedia_string (struct ast_flags *flags)
Return a string describing the comedia value for the given flags.
const char * force_rport_string (struct ast_flags *flags)
Return a string describing the force_rport value for the given flags.
Detailed Description
Utility functions for chan_sip.
Author
Terry Wilson twils.nosp@m.on@d.nosp@m.igium.nosp@m..com
Definition in file channels/sip/utils.c.
Function Documentation
comedia_string()
const char* comedia_string (struct ast_flags * flags)
Return a string describing the comedia value for the given flags.
Definition at line 43 of file channels/sip/utils.c.
References AST_CLI_YESNO, ast_test_flag, SIP_PAGE2_SYMMETRICRTP, and SIP_PAGE3_NAT_AUTO_COMEDIA.
Referenced by _sip_show_peer(), _sip_show_peers_one(), and sip_show_settings().
 {
    if (ast_test_flag(&flags[2], SIP_PAGE3_NAT_AUTO_COMEDIA)) {
       return ast_test_flag(&flags[1], SIP_PAGE2_SYMMETRICRTP) ? "Auto (Yes)" : "Auto (No)";
    }
    return AST_CLI_YESNO(ast_test_flag(&flags[1], SIP_PAGE2_SYMMETRICRTP));
 }
force_rport_string()
const char* force_rport_string (struct ast_flags * flags)
Return a string describing the force_rport value for the given flags.
Definition at line 35 of file channels/sip/utils.c.
References AST_CLI_YESNO, ast_test_flag, SIP_NAT_FORCE_RPORT, and SIP_PAGE3_NAT_AUTO_RPORT.
Referenced by _sip_show_peer(), _sip_show_peers_one(), sip_show_channel(), and sip_show_settings().
 {
    if (ast_test_flag(&flags[2], SIP_PAGE3_NAT_AUTO_RPORT)) {
       return ast_test_flag(&flags[0], SIP_NAT_FORCE_RPORT) ? "Auto (Yes)" : "Auto (No)";
    }
    return AST_CLI_YESNO(ast_test_flag(&flags[0], SIP_NAT_FORCE_RPORT));
 }