Asterisk - The Open Source Telephony Project: test_callerid.c File Reference
test_callerid.c File Reference
Callerid Tests.
#include "asterisk.h"
#include "asterisk/callerid.h"
#include "asterisk/utils.h"
#include "asterisk/module.h"
#include "asterisk/test.h"
Data Structures
struct cid_set
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
AST_TEST_DEFINE (parse_nominal)
AST_TEST_DEFINE (parse_off_nominal)
static int load_module (void)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Callerid Parse Tests" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, }
static const struct ast_module_info * ast_module_info = &__mod_info
Detailed Description
Callerid Tests.
Author
Kinsey Moore <kmoore@digium.com>
This is an Asterisk test module for callerid functionality
Definition in file test_callerid.c.
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 167 of file test_callerid.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 167 of file test_callerid.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 167 of file test_callerid.c.
AST_TEST_DEFINE() [1/2]
AST_TEST_DEFINE (parse_nominal)
Definition at line 47 of file test_callerid.c.
References ARRAY_LEN, ast_callerid_parse(), ast_free, ast_strdup, ast_strlen_zero, AST_TEST_FAIL, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_test_status_update, cid_set::cid, sip_to_pjsip::info(), cid_set::name, NULL, cid_set::number, RAII_VAR, TEST_EXECUTE, and TEST_INIT.
 {
    static const struct cid_set cid_sets[] = {
       {"\"name\" <number>", "name", "number"},
       {"\"   name  \" <number>", "   name  ", "number"},
       {"name <number>", "name", "number"},
       {"         name     <number>", "name", "number"},
       {"\"\" <number>", NULL, "number"},
       {"<number>", NULL, "number"},
       {"name", "name", NULL},
       {" name", "name", NULL},
       {"\"name\"", "name", NULL},
       {"\"*10\"", "*10", NULL},
       {" \"*10\"", "*10", NULL},
       {"\"name\" <>", "name", NULL},
       {"name <>", "name", NULL},
       {"1234", NULL, "1234"},
       {" 1234", NULL, "1234"},
       {"\"na\\\"me\" <number>", "na\"me", "number"},
    };
    char *name;
    char *number;
    int i;
    switch (cmd) {
    case TEST_INIT:
       info->name = "parse_nominal";
       info->category = "/main/callerid/";
       info->summary = "Callerid nominal parse unit test";
       info->description =
          "This tests parsing of nominal callerid strings.";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    for (i = 0; i < ARRAY_LEN(cid_sets); i++) {
       RAII_VAR(char *, callerid, ast_strdup(cid_sets[i].cid), ast_free);
       ast_callerid_parse(callerid, &name, &number);
       if (!cid_sets[i].name == !ast_strlen_zero(name) || (cid_sets[i].name && strcmp(name, cid_sets[i].name))) {
          ast_test_status_update(test,
             "Expected callerid name '%s' instead of '%s'\n",
             cid_sets[i].name, name);
          return AST_TEST_FAIL;
       }
       if (!cid_sets[i].number == !ast_strlen_zero(number) || (cid_sets[i].number && strcmp(number, cid_sets[i].number))) {
          ast_test_status_update(test,
             "Expected callerid number '%s' instead of '%s'\n",
             cid_sets[i].number, number);
          return AST_TEST_FAIL;
       }
    }
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [2/2]
AST_TEST_DEFINE (parse_off_nominal)
Definition at line 105 of file test_callerid.c.
References ARRAY_LEN, ast_callerid_parse(), ast_free, ast_strdup, ast_strlen_zero, AST_TEST_FAIL, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_test_status_update, cid_set::cid, sip_to_pjsip::info(), cid_set::name, cid_set::number, RAII_VAR, TEST_EXECUTE, and TEST_INIT.
 {
    static const struct cid_set cid_sets[] = {
       {"na\\\"me <number>", "na\"me", "number"},
       {"\"na\"me\" <number>", "na\"me", "number"},
       {"na\"me <number>", "na\"me", "number"},
       {"\"name <number>", "\"name", "number"},
       {"name <number", "name", "number"},
       {"\"name <number>\"", "name", "number"},
    };
    char *name;
    char *number;
    int i;
    switch (cmd) {
    case TEST_INIT:
       info->name = "parse_off_nominal";
       info->category = "/main/callerid/";
       info->summary = "Callerid off-nominal parse unit test";
       info->description =
          "This tests parsing of off-nominal callerid strings.";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    for (i = 0; i < ARRAY_LEN(cid_sets); i++) {
       RAII_VAR(char *, callerid, ast_strdup(cid_sets[i].cid), ast_free);
       ast_callerid_parse(callerid, &name, &number);
       if (!cid_sets[i].name == !ast_strlen_zero(name) || (cid_sets[i].name && strcmp(name, cid_sets[i].name))) {
          ast_test_status_update(test,
             "Expected callerid name '%s' instead of '%s'\n",
             cid_sets[i].name, name);
          return AST_TEST_FAIL;
       }
       if (!cid_sets[i].number == !ast_strlen_zero(number) || (cid_sets[i].number && strcmp(number, cid_sets[i].number))) {
          ast_test_status_update(test,
             "Expected callerid number '%s' instead of '%s'\n",
             cid_sets[i].number, number);
          return AST_TEST_FAIL;
       }
    }
    return AST_TEST_PASS;
 }
load_module()
static int load_module (void) static
Definition at line 160 of file test_callerid.c.
References AST_MODULE_LOAD_SUCCESS, and AST_TEST_REGISTER.
 {
    AST_TEST_REGISTER(parse_nominal);
    AST_TEST_REGISTER(parse_off_nominal);
    return AST_MODULE_LOAD_SUCCESS;
 }
unload_module()
static int unload_module (void) static
Definition at line 153 of file test_callerid.c.
References AST_TEST_UNREGISTER.
 {
    AST_TEST_UNREGISTER(parse_nominal);
    AST_TEST_UNREGISTER(parse_off_nominal);
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Callerid Parse Tests" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, } static
Definition at line 167 of file test_callerid.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 167 of file test_callerid.c.