Asterisk - The Open Source Telephony Project: format_sln.c File Reference
format_sln.c File Reference
Module: Media File Formats
RAW SLINEAR Formats.
#include "asterisk.h"
#include "asterisk/mod_format.h"
#include "asterisk/module.h"
#include "asterisk/endian.h"
#include "asterisk/format_cache.h"
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static struct ast_frame * generic_read (struct ast_filestream *s, int *whennext, unsigned int buf_size)
static int load_module (void)
static struct ast_frame * slinear12_read (struct ast_filestream *s, int *whennext)
static struct ast_frame * slinear16_read (struct ast_filestream *s, int *whennext)
static struct ast_frame * slinear192_read (struct ast_filestream *s, int *whennext)
static struct ast_frame * slinear24_read (struct ast_filestream *s, int *whennext)
static struct ast_frame * slinear32_read (struct ast_filestream *s, int *whennext)
static struct ast_frame * slinear44_read (struct ast_filestream *s, int *whennext)
static struct ast_frame * slinear48_read (struct ast_filestream *s, int *whennext)
static struct ast_frame * slinear96_read (struct ast_filestream *s, int *whennext)
static struct ast_frame * slinear_read (struct ast_filestream *s, int *whennext)
static int slinear_seek (struct ast_filestream *fs, off_t sample_offset, int whence)
static off_t slinear_tell (struct ast_filestream *fs)
static int slinear_trunc (struct ast_filestream *fs)
static int slinear_write (struct ast_filestream *fs, struct ast_frame *f)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Raw Signed Linear Audio support (SLN) 8khz-192khz" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_APP_DEPEND }
static const struct ast_module_info * ast_module_info = &__mod_info
static struct ast_format_def slin12_f
static struct ast_format_def slin16_f
static struct ast_format_def slin192_f
static struct ast_format_def slin24_f
static struct ast_format_def slin32_f
static struct ast_format_def slin44_f
static struct ast_format_def slin48_f
static struct ast_format_def slin96_f
static struct ast_format_def slin_f
static struct ast_format_def * slin_list []
Detailed Description
RAW SLINEAR Formats.
Definition in file format_sln.c.
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 289 of file format_sln.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 289 of file format_sln.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 289 of file format_sln.c.
generic_read()
static struct ast_frame* generic_read (struct ast_filestream * s, int * whennext, unsigned int buf_size) static
Definition at line 35 of file format_sln.c.
References ast_format_get_name(), AST_FRAME_SET_BUFFER, AST_FRIENDLY_OFFSET, ast_log, ast_filestream::buf, ast_frame::data, ast_frame::datalen, errno, ast_filestream::f, ast_frame_subclass::format, ast_filestream::fr, LOG_WARNING, NULL, ast_frame::ptr, ast_frame::samples, and ast_frame::subclass.
Referenced by slinear12_read(), slinear16_read(), slinear192_read(), slinear24_read(), slinear32_read(), slinear44_read(), slinear48_read(), slinear96_read(), and slinear_read().
 {
    size_t res;
    /* Send a frame from the file to the appropriate channel */
    AST_FRAME_SET_BUFFER(&s->fr, s->buf, AST_FRIENDLY_OFFSET, buf_size);
    if ((res = fread(s->fr.data.ptr, 1, s->fr.datalen, s->f)) < 1) {
       if (res) {
          ast_log(LOG_WARNING, "Short read of %s data (expected %d bytes, read %zu): %s\n",
                ast_format_get_name(s->fr.subclass.format), s->fr.datalen, res,
                strerror(errno));
       }
       return NULL;
    }
    *whennext = s->fr.samples = res/2;
    s->fr.datalen = res;
    return &s->fr;
 }
load_module()
static int load_module (void) static
Definition at line 260 of file format_sln.c.
References ARRAY_LEN, ast_format_def_register, ast_format_slin, ast_format_slin12, ast_format_slin16, ast_format_slin192, ast_format_slin24, ast_format_slin32, ast_format_slin44, ast_format_slin48, ast_format_slin96, AST_MODFLAG_LOAD_ORDER, AST_MODPRI_APP_DEPEND, AST_MODULE_INFO(), AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, AST_MODULE_SUPPORT_CORE, ASTERISK_GPL_KEY, ast_format_def::format, and unload_module().
 {
    int i;
    slin_f.format = ast_format_slin;
    slin12_f.format = ast_format_slin12;
    slin16_f.format = ast_format_slin16;
    slin24_f.format = ast_format_slin24;
    slin32_f.format = ast_format_slin32;
    slin44_f.format = ast_format_slin44;
    slin48_f.format = ast_format_slin48;
    slin96_f.format = ast_format_slin96;
    slin192_f.format = ast_format_slin192;
    for (i = 0; i < ARRAY_LEN(slin_list); i++) {
       if (ast_format_def_register(slin_list[i])) {
          unload_module();
          return AST_MODULE_LOAD_DECLINE;
       }
    }
    return AST_MODULE_LOAD_SUCCESS;
 }
slinear12_read()
static struct ast_frame* slinear12_read (struct ast_filestream * s, int * whennext) static
Definition at line 139 of file format_sln.c.
References generic_read().
 {return generic_read(s, whennext, 480);}
slinear16_read()
static struct ast_frame* slinear16_read (struct ast_filestream * s, int * whennext) static
Definition at line 151 of file format_sln.c.
References generic_read().
 {return generic_read(s, whennext, 640);}
slinear192_read()
static struct ast_frame* slinear192_read (struct ast_filestream * s, int * whennext) static
Definition at line 223 of file format_sln.c.
References generic_read().
 {return generic_read(s, whennext, 7680);}
slinear24_read()
static struct ast_frame* slinear24_read (struct ast_filestream * s, int * whennext) static
Definition at line 163 of file format_sln.c.
References generic_read().
 {return generic_read(s, whennext, 960);}
slinear32_read()
static struct ast_frame* slinear32_read (struct ast_filestream * s, int * whennext) static
Definition at line 175 of file format_sln.c.
References generic_read().
 {return generic_read(s, whennext, 1280);}
slinear44_read()
static struct ast_frame* slinear44_read (struct ast_filestream * s, int * whennext) static
Definition at line 187 of file format_sln.c.
References generic_read().
 {return generic_read(s, whennext, 1764);}
slinear48_read()
static struct ast_frame* slinear48_read (struct ast_filestream * s, int * whennext) static
Definition at line 199 of file format_sln.c.
References generic_read().
 {return generic_read(s, whennext, 1920);}
slinear96_read()
static struct ast_frame* slinear96_read (struct ast_filestream * s, int * whennext) static
Definition at line 211 of file format_sln.c.
References generic_read().
 {return generic_read(s, whennext, 3840);}
slinear_read()
static struct ast_frame* slinear_read (struct ast_filestream * s, int * whennext) static
Definition at line 127 of file format_sln.c.
References generic_read().
 {return generic_read(s, whennext, 320);}
slinear_seek()
static int slinear_seek (struct ast_filestream * fs, off_t sample_offset, int whence) static
Definition at line 70 of file format_sln.c.
References ast_log, AST_LOG_WARNING, errno, ast_filestream::f, max, min, ast_frame::offset, and SEEK_FORCECUR.
 {
    off_t offset=0, min = 0, cur, max;
    sample_offset <<= 1;
    if ((cur = ftello(fs->f)) < 0) {
       ast_log(AST_LOG_WARNING, "Unable to determine current position in sln filestream %p: %s\n", fs, strerror(errno));
       return -1;
    }
    if (fseeko(fs->f, 0, SEEK_END) < 0) {
       ast_log(AST_LOG_WARNING, "Unable to seek to end of sln filestream %p: %s\n", fs, strerror(errno));
       return -1;
    }
    if ((max = ftello(fs->f)) < 0) {
       ast_log(AST_LOG_WARNING, "Unable to determine max position in sln filestream %p: %s\n", fs, strerror(errno));
       return -1;
    }
    if (whence == SEEK_SET)
       offset = sample_offset;
    else if (whence == SEEK_CUR || whence == SEEK_FORCECUR)
       offset = sample_offset + cur;
    else if (whence == SEEK_END)
       offset = max - sample_offset;
    if (whence != SEEK_FORCECUR) {
       offset = (offset > max)?max:offset;
    }
    /* always protect against seeking past begining. */
    offset = (offset < min)?min:offset;
    return fseeko(fs->f, offset, SEEK_SET);
 }
slinear_tell()
static off_t slinear_tell (struct ast_filestream * fs) static
Definition at line 122 of file format_sln.c.
References ast_filestream::f.
 {
    return ftello(fs->f) / 2;
 }
slinear_trunc()
static int slinear_trunc (struct ast_filestream * fs) static
Definition at line 105 of file format_sln.c.
References ast_log, AST_LOG_WARNING, errno, and ast_filestream::f.
 {
    int fd;
    off_t cur;
    if ((fd = fileno(fs->f)) < 0) {
       ast_log(AST_LOG_WARNING, "Unable to determine file descriptor for sln filestream %p: %s\n", fs, strerror(errno));
       return -1;
    }
    if ((cur = ftello(fs->f)) < 0) {
       ast_log(AST_LOG_WARNING, "Unable to determine current position in sln filestream %p: %s\n", fs, strerror(errno));
       return -1;
    }
    /* Truncate file to current length */
    return ftruncate(fd, cur);
 }
slinear_write()
static int slinear_write (struct ast_filestream * fs, struct ast_frame * f) static
Definition at line 54 of file format_sln.c.
References ast_log, ast_frame::data, ast_frame::datalen, errno, ast_filestream::f, LOG_WARNING, and ast_frame::ptr.
 {
    int res;
    /* Don't try to write an interpolated frame */
    if (f->datalen == 0) {
       return 0;
    }
    if ((res = fwrite(f->data.ptr, 1, f->datalen, fs->f)) != f->datalen) {
          ast_log(LOG_WARNING, "Bad write (%d/%d): %s\n", res, f->datalen, strerror(errno));
          return -1;
    }
    return 0;
 }
unload_module()
static int unload_module (void) static
Definition at line 247 of file format_sln.c.
References ARRAY_LEN, ast_format_def_unregister(), and name.
Referenced by load_module().
 {
    int res = 0;
    int i = 0;
    for (i = 0; i < ARRAY_LEN(slin_list); i++) {
       if (ast_format_def_unregister(slin_list[i]->name)) {
          res = -1;
       }
    }
    return res;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Raw Signed Linear Audio support (SLN) 8khz-192khz" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_APP_DEPEND } static
Definition at line 289 of file format_sln.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 289 of file format_sln.c.
slin12_f
struct ast_format_def slin12_f static
Definition at line 140 of file format_sln.c.
slin16_f
struct ast_format_def slin16_f static
Definition at line 152 of file format_sln.c.
slin192_f
struct ast_format_def slin192_f static
Definition at line 224 of file format_sln.c.
slin24_f
struct ast_format_def slin24_f static
Definition at line 164 of file format_sln.c.
slin32_f
struct ast_format_def slin32_f static
Definition at line 176 of file format_sln.c.
slin44_f
struct ast_format_def slin44_f static
Definition at line 188 of file format_sln.c.
slin48_f
struct ast_format_def slin48_f static
Definition at line 200 of file format_sln.c.
slin96_f
struct ast_format_def slin96_f static
Definition at line 212 of file format_sln.c.
slin_f
struct ast_format_def slin_f static
Definition at line 128 of file format_sln.c.
slin_list
struct ast_format_def* slin_list[] static
Definition at line 235 of file format_sln.c.