Asterisk - The Open Source Telephony Project: format_pcm.c File Reference
format_pcm.c File Reference
Module: Media File Formats
Flat, binary, ulaw PCM file format.
#include "asterisk.h"
#include "asterisk/mod_format.h"
#include "asterisk/module.h"
#include "asterisk/endian.h"
#include "asterisk/ulaw.h"
#include "asterisk/alaw.h"
#include "asterisk/format_cache.h"
Data Structures
struct au_desc
Macros
#define AU_ENC_8BIT_ULAW 1
#define AU_HDR_CHANNELS_OFF 5
#define AU_HDR_DATA_SIZE_OFF 2
#define AU_HDR_ENCODING_OFF 3
#define AU_HDR_HDR_SIZE_OFF 1
#define AU_HDR_MAGIC_OFF 0
#define AU_HDR_SAMPLE_RATE_OFF 4
#define AU_HEADER(var) uint32_t var[6]
#define AU_MAGIC 0x2e736e64
#define BUF_SIZE 160 /* 160 bytes, and same number of samples */
#define MIN_AU_HEADER_SIZE 24
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int au_open (struct ast_filestream *s)
static int au_rewrite (struct ast_filestream *s, const char *comment)
static int au_seek (struct ast_filestream *fs, off_t sample_offset, int whence)
static off_t au_tell (struct ast_filestream *fs)
static int au_trunc (struct ast_filestream *fs)
static int check_header (struct ast_filestream *fs)
static struct ast_frame * g722_read (struct ast_filestream *s, int *whennext)
static int g722_seek (struct ast_filestream *fs, off_t sample_offset, int whence)
static off_t g722_tell (struct ast_filestream *fs)
static int load_module (void)
static struct ast_frame * pcm_read (struct ast_filestream *s, int *whennext)
static int pcm_seek (struct ast_filestream *fs, off_t sample_offset, int whence)
static off_t pcm_tell (struct ast_filestream *fs)
static int pcm_trunc (struct ast_filestream *fs)
static int pcm_write (struct ast_filestream *fs, struct ast_frame *f)
static int unload_module (void)
static int update_header (struct ast_filestream *fs)
static int write_header (struct ast_filestream *fs)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Raw/Sun uLaw/ALaw 8KHz (PCM,PCMA,AU), G.722 16Khz" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_APP_DEPEND }
static struct ast_format_def alaw_f
static char alaw_silence [BUF_SIZE]
static const struct ast_module_info * ast_module_info = &__mod_info
static struct ast_format_def au_f
static struct ast_format_def g722_f
static struct ast_format_def pcm_f
static char ulaw_silence [BUF_SIZE]
Detailed Description
Flat, binary, ulaw PCM file format.
File name extension: alaw, al, alw, pcm, ulaw, ul, mu, ulw, g722, au
Definition in file format_pcm.c.
Macro Definition Documentation
AU_ENC_8BIT_ULAW
#define AU_ENC_8BIT_ULAW 1
Definition at line 247 of file format_pcm.c.
Referenced by check_header(), and write_header().
AU_HDR_CHANNELS_OFF
#define AU_HDR_CHANNELS_OFF 5
Definition at line 245 of file format_pcm.c.
Referenced by check_header(), and write_header().
AU_HDR_DATA_SIZE_OFF
#define AU_HDR_DATA_SIZE_OFF 2
Definition at line 242 of file format_pcm.c.
Referenced by update_header(), and write_header().
AU_HDR_ENCODING_OFF
#define AU_HDR_ENCODING_OFF 3
Definition at line 243 of file format_pcm.c.
Referenced by check_header(), and write_header().
AU_HDR_HDR_SIZE_OFF
#define AU_HDR_HDR_SIZE_OFF 1
Definition at line 241 of file format_pcm.c.
Referenced by check_header(), and write_header().
AU_HDR_MAGIC_OFF
#define AU_HDR_MAGIC_OFF 0
Definition at line 240 of file format_pcm.c.
Referenced by check_header(), and write_header().
AU_HDR_SAMPLE_RATE_OFF
#define AU_HDR_SAMPLE_RATE_OFF 4
Definition at line 244 of file format_pcm.c.
Referenced by check_header(), and write_header().
AU_HEADER
#define AU_HEADER (var) uint32_t var[6]
Definition at line 238 of file format_pcm.c.
Referenced by check_header(), and write_header().
AU_MAGIC
#define AU_MAGIC 0x2e736e64
Definition at line 249 of file format_pcm.c.
Referenced by check_header(), and write_header().
BUF_SIZE
#define BUF_SIZE 160 /* 160 bytes, and same number of samples */
Definition at line 40 of file format_pcm.c.
Referenced by pcm_read(), and pcm_seek().
MIN_AU_HEADER_SIZE
#define MIN_AU_HEADER_SIZE 24
Definition at line 237 of file format_pcm.c.
Referenced by au_rewrite(), check_header(), and write_header().
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 581 of file format_pcm.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 581 of file format_pcm.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 581 of file format_pcm.c.
au_open()
static int au_open (struct ast_filestream * s) static
Definition at line 388 of file format_pcm.c.
References check_header().
 {
    if (check_header(s) < 0)
       return -1;
    return 0;
 }
au_rewrite()
static int au_rewrite (struct ast_filestream * s, const char * comment) static
Definition at line 395 of file format_pcm.c.
References ast_filestream::_private, desc, au_desc::hdr_size, MIN_AU_HEADER_SIZE, and write_header().
 {
    struct au_desc *desc = s->_private;
    desc->hdr_size = MIN_AU_HEADER_SIZE;
    if (write_header(s))
       return -1;
    return 0;
 }
au_seek()
static int au_seek (struct ast_filestream * fs, off_t sample_offset, int whence) static
Definition at line 407 of file format_pcm.c.
References ast_filestream::_private, ast_log, AST_LOG_WARNING, desc, errno, ast_filestream::f, au_desc::hdr_size, max, min, and SEEK_FORCECUR.
 {
    off_t min, max, cur;
    long offset = 0;
    struct au_desc *desc = fs->_private;
    min = desc->hdr_size;
    if ((cur = ftello(fs->f)) < 0) {
       ast_log(AST_LOG_WARNING, "Unable to determine current position in au filestream %p: %s\n", fs, strerror(errno));
       return -1;
    }
    if (fseeko(fs->f, 0, SEEK_END) < 0) {
       ast_log(AST_LOG_WARNING, "Unable to seek to end of au filestream %p: %s\n", fs, strerror(errno));
       return -1;
    }
    if ((max = ftello(fs->f)) < 0) {
       ast_log(AST_LOG_WARNING, "Unable to determine max position in au filestream %p: %s\n", fs, strerror(errno));
       return -1;
    }
    if (whence == SEEK_SET)
       offset = sample_offset + min;
    else if (whence == SEEK_CUR || whence == SEEK_FORCECUR)
       offset = sample_offset + cur;
    else if (whence == SEEK_END)
       offset = max - sample_offset;
    if (whence != SEEK_FORCECUR) {
       offset = (offset > max) ? max : offset;
    }
    /* always protect the header space. */
    offset = (offset < min) ? min : offset;
    return fseeko(fs->f, offset, SEEK_SET);
 }
au_tell()
static off_t au_tell (struct ast_filestream * fs) static
Definition at line 467 of file format_pcm.c.
References ast_filestream::_private, desc, ast_filestream::f, and au_desc::hdr_size.
 {
    struct au_desc *desc = fs->_private;
    off_t offset = ftello(fs->f);
    return offset - desc->hdr_size;
 }
au_trunc()
static int au_trunc (struct ast_filestream * fs) static
Definition at line 447 of file format_pcm.c.
References ast_log, AST_LOG_WARNING, errno, ast_filestream::f, and update_header().
 {
    int fd;
    off_t cur;
    if ((fd = fileno(fs->f)) < 0) {
       ast_log(AST_LOG_WARNING, "Unable to determine file descriptor for au filestream %p: %s\n", fs, strerror(errno));
       return -1;
    }
    if ((cur = ftello(fs->f)) < 0) {
       ast_log(AST_LOG_WARNING, "Unable to determine current position in au filestream %p: %s\n", fs, strerror(errno));
       return -1;
    }
    /* Truncate file to current length */
    if (ftruncate(fd, cur)) {
       return -1;
    }
    return update_header(fs);
 }
check_header()
static int check_header (struct ast_filestream * fs) static
Definition at line 276 of file format_pcm.c.
References ast_filestream::_private, ast_log, AU_ENC_8BIT_ULAW, AU_HDR_CHANNELS_OFF, AU_HDR_ENCODING_OFF, AU_HDR_HDR_SIZE_OFF, AU_HDR_MAGIC_OFF, AU_HDR_SAMPLE_RATE_OFF, AU_HEADER, AU_MAGIC, channels, DEFAULT_SAMPLE_RATE, desc, encoding, ast_filestream::f, au_desc::hdr_size, LOG_WARNING, and MIN_AU_HEADER_SIZE.
Referenced by au_open().
 {
    AU_HEADER(header);
    uint32_t magic;
    uint32_t hdr_size;
    uint32_t data_size;
    uint32_t encoding;
    uint32_t sample_rate;
    uint32_t channels;
    struct au_desc *desc = fs->_private;
    FILE *f = fs->f;
    if (fread(header, 1, MIN_AU_HEADER_SIZE, f) != MIN_AU_HEADER_SIZE) {
       ast_log(LOG_WARNING, "Read failed (header)\n");
       return -1;
    }
    magic = ltohl(header[AU_HDR_MAGIC_OFF]);
    if (magic != (uint32_t) AU_MAGIC) {
       ast_log(LOG_WARNING, "Bad magic: 0x%x\n", magic);
    }
    hdr_size = ltohl(header[AU_HDR_HDR_SIZE_OFF]);
    if (hdr_size < MIN_AU_HEADER_SIZE) {
       hdr_size = MIN_AU_HEADER_SIZE;
    }
 /* data_size = ltohl(header[AU_HDR_DATA_SIZE_OFF]); */
    encoding = ltohl(header[AU_HDR_ENCODING_OFF]);
    if (encoding != AU_ENC_8BIT_ULAW) {
       ast_log(LOG_WARNING, "Unexpected format: %u. Only 8bit ULAW allowed (%d)\n", encoding, AU_ENC_8BIT_ULAW);
       return -1;
    }
    sample_rate = ltohl(header[AU_HDR_SAMPLE_RATE_OFF]);
    if (sample_rate != DEFAULT_SAMPLE_RATE) {
       ast_log(LOG_WARNING, "Sample rate can only be 8000 not %u\n", sample_rate);
       return -1;
    }
    channels = ltohl(header[AU_HDR_CHANNELS_OFF]);
    if (channels != 1) {
       ast_log(LOG_WARNING, "Not in mono: channels=%u\n", channels);
       return -1;
    }
    /* Skip to data */
    fseek(f, 0, SEEK_END);
    data_size = ftell(f) - hdr_size;
    if (fseek(f, hdr_size, SEEK_SET) == -1 ) {
       ast_log(LOG_WARNING, "Failed to skip to data: %u\n", hdr_size);
       return -1;
    }
    /* We'll need this later */
    desc->hdr_size = hdr_size;
    return data_size;
 }
g722_read()
static struct ast_frame* g722_read (struct ast_filestream * s, int * whennext) static
Definition at line 474 of file format_pcm.c.
References ast_filestream::fr, pcm_read(), and ast_frame::samples.
 {
    struct ast_frame *f = pcm_read(s, whennext);
    *whennext = s->fr.samples = (*whennext * 2);
    return f;
 }
g722_seek()
static int g722_seek (struct ast_filestream * fs, off_t sample_offset, int whence) static
Definition at line 481 of file format_pcm.c.
References pcm_seek().
 {
    return pcm_seek(fs, sample_offset / 2, whence);
 }
g722_tell()
static off_t g722_tell (struct ast_filestream * fs) static
Definition at line 486 of file format_pcm.c.
References pcm_tell().
 {
    return pcm_tell(fs) * 2;
 }
load_module()
static int load_module (void) static
Definition at line 552 of file format_pcm.c.
References alaw_silence, ARRAY_LEN, ast_format_alaw, ast_format_def_register, ast_format_g722, ast_format_ulaw, AST_LIN2A, AST_LIN2MU, AST_MODFLAG_LOAD_ORDER, AST_MODPRI_APP_DEPEND, AST_MODULE_INFO(), AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, AST_MODULE_SUPPORT_CORE, ASTERISK_GPL_KEY, ast_format_def::format, ulaw_silence, and unload_module().
 {
    int i;
    /* XXX better init ? */
    for (i = 0; i < ARRAY_LEN(ulaw_silence); i++)
       ulaw_silence[i] = AST_LIN2MU(0);
    for (i = 0; i < ARRAY_LEN(alaw_silence); i++)
       alaw_silence[i] = AST_LIN2A(0);
    pcm_f.format = ast_format_ulaw;
    alaw_f.format = ast_format_alaw;
    au_f.format = ast_format_ulaw;
    g722_f.format = ast_format_g722;
    if ( ast_format_def_register(&pcm_f)
       || ast_format_def_register(&alaw_f)
       || ast_format_def_register(&au_f)
       || ast_format_def_register(&g722_f) ) {
       unload_module();
       return AST_MODULE_LOAD_DECLINE;
    }
    return AST_MODULE_LOAD_SUCCESS;
 }
pcm_read()
static struct ast_frame* pcm_read (struct ast_filestream * s, int * whennext) static
Definition at line 79 of file format_pcm.c.
References ast_format_get_name(), AST_FRAME_SET_BUFFER, AST_FRIENDLY_OFFSET, ast_log, ast_filestream::buf, BUF_SIZE, ast_frame::data, ast_frame::datalen, errno, ast_filestream::f, ast_frame_subclass::format, ast_filestream::fr, LOG_WARNING, NULL, ast_frame::ptr, ast_frame::samples, and ast_frame::subclass.
Referenced by g722_read().
 {
    size_t res;
    /* Send a frame from the file to the appropriate channel */
    AST_FRAME_SET_BUFFER(&s->fr, s->buf, AST_FRIENDLY_OFFSET, BUF_SIZE);
    if ((res = fread(s->fr.data.ptr, 1, s->fr.datalen, s->f)) < 1) {
       if (res) {
          ast_log(LOG_WARNING, "Short read of %s data (expected %d bytes, read %zu): %s\n",
                ast_format_get_name(s->fr.subclass.format), s->fr.datalen, res,
                strerror(errno));
       }
       return NULL;
    }
    s->fr.datalen = res;
    *whennext = s->fr.samples = res;
    return &s->fr;
 }
pcm_seek()
static int pcm_seek (struct ast_filestream * fs, off_t sample_offset, int whence) static
Definition at line 98 of file format_pcm.c.
References alaw_silence, ast_format_alaw, ast_format_cmp(), AST_FORMAT_CMP_EQUAL, ast_log, AST_LOG_WARNING, BUF_SIZE, errno, ast_filestream::f, ast_filestream::fmt, ast_format_def::format, LOG_WARNING, max, MIN, ast_frame::offset, SEEK_FORCECUR, ast_frame::src, and ulaw_silence.
Referenced by g722_seek().
 {
    off_t cur, max, offset = 0;
    int ret = -1;  /* assume error */
    if ((cur = ftello(fs->f)) < 0) {
       ast_log(AST_LOG_WARNING, "Unable to determine current position in pcm filestream %p: %s\n", fs, strerror(errno));
       return -1;
    }
    if (fseeko(fs->f, 0, SEEK_END) < 0) {
       ast_log(AST_LOG_WARNING, "Unable to seek to end of pcm filestream %p: %s\n", fs, strerror(errno));
       return -1;
    }
    if ((max = ftello(fs->f)) < 0) {
       ast_log(AST_LOG_WARNING, "Unable to determine max position in pcm filestream %p: %s\n", fs, strerror(errno));
       return -1;
    }
    switch (whence) {
    case SEEK_SET:
       offset = sample_offset;
       break;
    case SEEK_END:
       offset = max - sample_offset;
       break;
    case SEEK_CUR:
    case SEEK_FORCECUR:
       offset = cur + sample_offset;
       break;
    default:
       ast_log(LOG_WARNING, "invalid whence %d, assuming SEEK_SET\n", whence);
       offset = sample_offset;
    }
    if (offset < 0) {
       ast_log(LOG_WARNING, "negative offset %ld, resetting to 0\n", (long) offset);
       offset = 0;
    }
    if (whence == SEEK_FORCECUR && offset > max) { /* extend the file */
       size_t left = offset - max;
       const char *src = (ast_format_cmp(fs->fmt->format, ast_format_alaw) == AST_FORMAT_CMP_EQUAL) ? alaw_silence : ulaw_silence;
       while (left) {
          size_t written = fwrite(src, 1, MIN(left, BUF_SIZE), fs->f);
          if (written < MIN(left, BUF_SIZE)) {
             break;   /* error */
          }
          left -= written;
       }
       ret = 0; /* successful */
    } else {
       if (offset > max) {
          ast_log(LOG_WARNING, "offset too large %ld, truncating to %ld\n", (long) offset, (long) max);
          offset = max;
       }
       ret = fseeko(fs->f, offset, SEEK_SET);
    }
    return ret;
 }
pcm_tell()
static off_t pcm_tell (struct ast_filestream * fs) static
Definition at line 175 of file format_pcm.c.
References ast_filestream::f.
Referenced by g722_tell().
 {
    return ftello(fs->f);
 }
pcm_trunc()
static int pcm_trunc (struct ast_filestream * fs) static
Definition at line 159 of file format_pcm.c.
References ast_log, AST_LOG_WARNING, errno, and ast_filestream::f.
 {
    int cur, fd;
    if ((fd = fileno(fs->f)) < 0) {
       ast_log(AST_LOG_WARNING, "Unable to determine file descriptor for pcm filestream %p: %s\n", fs, strerror(errno));
       return -1;
    }
    if ((cur = ftello(fs->f)) < 0) {
       ast_log(AST_LOG_WARNING, "Unable to determine current position in pcm filestream %p: %s\n", fs, strerror(errno));
       return -1;
    }
    /* Truncate file to current length */
    return ftruncate(fd, cur);
 }
pcm_write()
static int pcm_write (struct ast_filestream * fs, struct ast_frame * f) static
Definition at line 180 of file format_pcm.c.
References ast_filestream::_private, ast_format_alaw, ast_format_cmp(), AST_FORMAT_CMP_EQUAL, ast_log, buf, ast_frame::data, ast_frame::datalen, errno, ast_filestream::f, ast_filestream::fmt, ast_format_def::format, LOG_ERROR, LOG_WARNING, and ast_frame::ptr.
 {
    int res;
 #ifdef REALTIME_WRITE
    if (ast_format_cmp(s->fmt->format, ast_format_alaw) == AST_FORMAT_CMP_EQUAL) {
       struct pcm_desc *pd = (struct pcm_desc *)fs->_private;
       struct stat stat_buf;
       unsigned long cur_time = get_time();
       unsigned long fpos = ( cur_time - pd->start_time ) * 8;  /* 8 bytes per msec */
       /* Check if we have written to this position yet. If we have, then increment pos by one frame
       *  for some degree of protection against receiving packets in the same clock tick.
       */
       fstat(fileno(fs->f), &stat_buf );
       if (stat_buf.st_size > fpos )
          fpos += f->datalen;  /* Incrementing with the size of this current frame */
       if (stat_buf.st_size < fpos) {
          /* fill the gap with 0x55 rather than 0. */
          char buf[1024];
          unsigned long cur, to_write;
          cur = stat_buf.st_size;
          if (fseek(fs->f, cur, SEEK_SET) < 0) {
             ast_log( LOG_WARNING, "Cannot seek in file: %s\n", strerror(errno) );
             return -1;
          }
          memset(buf, 0x55, 512);
          while (cur < fpos) {
             to_write = fpos - cur;
             if (to_write > sizeof(buf))
                to_write = sizeof(buf);
             if (fwrite(buf, 1, to_write, fs->f) != to_write) {
                ast_log(LOG_ERROR, "Failed to write to file: %s\n", strerror(errno));
                return -1;
             }
             cur += to_write;
          }
       }
       if (fseek(s->f, fpos, SEEK_SET) < 0) {
          ast_log( LOG_WARNING, "Cannot seek in file: %s\n", strerror(errno) );
          return -1;
       }
    }
 #endif   /* REALTIME_WRITE */
    if ((res = fwrite(f->data.ptr, 1, f->datalen, fs->f)) != f->datalen) {
       ast_log(LOG_WARNING, "Bad write (%d/%d): %s\n", res, f->datalen, strerror(errno));
       return -1;
    }
    return 0;
 }
unload_module()
static int unload_module (void) static
Definition at line 544 of file format_pcm.c.
References ast_format_def_unregister(), and ast_format_def::name.
Referenced by load_module().
 {
    return ast_format_def_unregister(pcm_f.name)
       || ast_format_def_unregister(alaw_f.name)
       || ast_format_def_unregister(au_f.name)
       || ast_format_def_unregister(g722_f.name);
 }
update_header()
static int update_header (struct ast_filestream * fs) static
Definition at line 331 of file format_pcm.c.
References ast_filestream::_private, ast_log, AU_HDR_DATA_SIZE_OFF, desc, end, ast_filestream::f, au_desc::hdr_size, and LOG_WARNING.
Referenced by au_trunc().
 {
    off_t cur, end;
    uint32_t datalen;
    int bytes;
    struct au_desc *desc = fs->_private;
    FILE *f = fs->f;
    cur = ftell(f);
    fseek(f, 0, SEEK_END);
    end = ftell(f);
    /* data starts 24 bytes in */
    bytes = end - desc->hdr_size;
    datalen = htoll(bytes);
    if (cur < 0) {
       ast_log(LOG_WARNING, "Unable to find our position\n");
       return -1;
    }
    if (fseek(f, AU_HDR_DATA_SIZE_OFF * sizeof(uint32_t), SEEK_SET)) {
       ast_log(LOG_WARNING, "Unable to set our position\n");
       return -1;
    }
    if (fwrite(&datalen, 1, sizeof(datalen), f) != sizeof(datalen)) {
       ast_log(LOG_WARNING, "Unable to set write file size\n");
       return -1;
    }
    if (fseek(f, cur, SEEK_SET)) {
       ast_log(LOG_WARNING, "Unable to return to position\n");
       return -1;
    }
    return 0;
 }
write_header()
static int write_header (struct ast_filestream * fs) static
Definition at line 365 of file format_pcm.c.
References ast_filestream::_private, ast_log, AU_ENC_8BIT_ULAW, AU_HDR_CHANNELS_OFF, AU_HDR_DATA_SIZE_OFF, AU_HDR_ENCODING_OFF, AU_HDR_HDR_SIZE_OFF, AU_HDR_MAGIC_OFF, AU_HDR_SAMPLE_RATE_OFF, AU_HEADER, AU_MAGIC, DEFAULT_SAMPLE_RATE, desc, ast_filestream::f, au_desc::hdr_size, LOG_WARNING, and MIN_AU_HEADER_SIZE.
Referenced by au_rewrite().
 {
    struct au_desc *desc = fs->_private;
    FILE *f = fs->f;
    AU_HEADER(header);
    header[AU_HDR_MAGIC_OFF] = htoll((uint32_t) AU_MAGIC);
    header[AU_HDR_HDR_SIZE_OFF] = htoll(desc->hdr_size);
    header[AU_HDR_DATA_SIZE_OFF] = 0;
    header[AU_HDR_ENCODING_OFF] = htoll(AU_ENC_8BIT_ULAW);
    header[AU_HDR_SAMPLE_RATE_OFF] = htoll(DEFAULT_SAMPLE_RATE);
    header[AU_HDR_CHANNELS_OFF] = htoll(1);
    /* Write an au header, ignoring sizes which will be filled in later */
    fseek(f, 0, SEEK_SET);
    if (fwrite(header, 1, MIN_AU_HEADER_SIZE, f) != MIN_AU_HEADER_SIZE) {
       ast_log(LOG_WARNING, "Unable to write header\n");
       return -1;
    }
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Raw/Sun uLaw/ALaw 8KHz (PCM,PCMA,AU), G.722 16Khz" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_APP_DEPEND } static
Definition at line 581 of file format_pcm.c.
alaw_f
struct ast_format_def alaw_f static
Definition at line 491 of file format_pcm.c.
alaw_silence
char alaw_silence[BUF_SIZE] static
Definition at line 43 of file format_pcm.c.
Referenced by load_module(), and pcm_seek().
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 581 of file format_pcm.c.
au_f
struct ast_format_def au_f static
Definition at line 530 of file format_pcm.c.
g722_f
struct ast_format_def g722_f static
Definition at line 519 of file format_pcm.c.
pcm_f
struct ast_format_def pcm_f static
Definition at line 507 of file format_pcm.c.
ulaw_silence
char ulaw_silence[BUF_SIZE] static
Definition at line 42 of file format_pcm.c.
Referenced by load_module(), and pcm_seek().