Asterisk - The Open Source Telephony Project: backtrace.c File Reference
backtrace.c File Reference
Asterisk backtrace generation.
#include "asterisk.h"
#include "asterisk/backtrace.h"
#include "asterisk/vector.h"
#include <execinfo.h>
#include <pthread.h>
Macros
#define _ASTERISK_LOCK_H
#define ast_calloc(n, x) calloc(n, x)
#define ast_free(x) free(x)
#define ast_malloc(x) malloc(x)
#define ASTMM_LIBC ASTMM_IGNORE
#define S_OR(a, b) (a && a[0] != '\0') ? a : b
Functions
struct ast_bt * __ast_bt_create (void)
void * __ast_bt_destroy (struct ast_bt *bt)
void __ast_bt_free_symbols (struct ast_vector_string *symbols)
int __ast_bt_get_addresses (struct ast_bt *bt)
struct ast_vector_string * __ast_bt_get_symbols (void **addresses, size_t num_frames)
Detailed Description
Asterisk backtrace generation.
This file provides backtrace generation utilities
Definition in file backtrace.c.
Macro Definition Documentation
_ASTERISK_LOCK_H
#define _ASTERISK_LOCK_H
Definition at line 33 of file backtrace.c.
ast_calloc
#define ast_calloc (n, x) calloc(n, x)
Definition at line 52 of file backtrace.c.
ast_free
#define ast_free (x) free(x)
Definition at line 51 of file backtrace.c.
ast_malloc
#define ast_malloc (x) malloc(x)
Definition at line 53 of file backtrace.c.
ASTMM_LIBC
#define ASTMM_LIBC ASTMM_IGNORE
Definition at line 39 of file backtrace.c.
S_OR
#define S_OR (a, b) (a && a[0] != '\0') ? a : b
Definition at line 76 of file backtrace.c.
Referenced by __ast_bt_destroy().
Function Documentation
__ast_bt_create()
struct ast_bt* __ast_bt_create (void)
Definition at line 78 of file backtrace.c.
References ast_bt::alloced, ast_bt_get_addresses, calloc, and NULL.
 {
    struct ast_bt *bt = calloc(1, sizeof(*bt));
    if (!bt) {
       return NULL;
    }
    bt->alloced = 1;
    ast_bt_get_addresses(bt);
    return bt;
 }
__ast_bt_destroy()
void* __ast_bt_destroy (struct ast_bt * bt)
Definition at line 98 of file backtrace.c.
References __ast_bt_get_symbols(), ast_bt::alloced, AST_VECTOR_APPEND, AST_VECTOR_INIT, make_ari_stubs::file, free(), malloc(), NULL, pthread_mutex_lock, pthread_mutex_t, pthread_mutex_unlock, S_OR, and strdup.
 {
    if (bt && bt->alloced) {
       free(bt);
    }
    return NULL;
 }
__ast_bt_free_symbols()
void __ast_bt_free_symbols (struct ast_vector_string * symbols)
Definition at line 308 of file backtrace.c.
References AST_VECTOR_CALLBACK_VOID, AST_VECTOR_PTR_FREE, and free().
 {
    AST_VECTOR_CALLBACK_VOID(symbols, free);
    AST_VECTOR_PTR_FREE(symbols);
 }
__ast_bt_get_addresses()
int __ast_bt_get_addresses (struct ast_bt * bt)
Definition at line 92 of file backtrace.c.
References ast_bt::addresses, AST_MAX_BT_FRAMES, and ast_bt::num_frames.
 {
    bt->num_frames = backtrace(bt->addresses, AST_MAX_BT_FRAMES);
    return 0;
 }
__ast_bt_get_symbols()
struct ast_vector_string * __ast_bt_get_symbols (void ** addresses, size_t num_frames)
Definition at line 281 of file backtrace.c.
References AST_VECTOR_APPEND, AST_VECTOR_INIT, free(), malloc(), NULL, and strdup.
Referenced by __ast_bt_destroy().
 {
    char **strings;
    struct ast_vector_string *return_strings;
    int i;
    return_strings = malloc(sizeof(struct ast_vector_string));
    if (!return_strings) {
       return NULL;
    }
    if (AST_VECTOR_INIT(return_strings, num_frames)) {
       free(return_strings);
       return NULL;
    }
    strings = backtrace_symbols(addresses, num_frames);
    if (strings) {
       for (i = 0; i < num_frames; i++) {
          AST_VECTOR_APPEND(return_strings, strdup(strings[i]));
       }
       free(strings);
    }
    return return_strings;
 }