Asterisk - The Open Source Telephony Project: func_logic.c File Reference
func_logic.c File Reference
Module: Dial plan functions
Conditional logic dialplan functions.
#include "asterisk.h"
#include "asterisk/module.h"
#include "asterisk/channel.h"
#include "asterisk/pbx.h"
#include "asterisk/utils.h"
#include "asterisk/app.h"
Functions
static void __reg_module (void)
static void __unreg_module (void)
static int acf_if (struct ast_channel *chan, const char *cmd, char *data, char *buf, size_t len)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int exists (struct ast_channel *chan, const char *cmd, char *data, char *buf, size_t len)
static int iftime (struct ast_channel *chan, const char *cmd, char *data, char *buf, size_t len)
static int import_helper (struct ast_channel *chan, const char *cmd, char *data, char *buf, struct ast_str **str, ssize_t len)
static int import_read (struct ast_channel *chan, const char *cmd, char *data, char *buf, size_t len)
static int import_read2 (struct ast_channel *chan, const char *cmd, char *data, struct ast_str **str, ssize_t len)
static int isnull (struct ast_channel *chan, const char *cmd, char *data, char *buf, size_t len)
static int load_module (void)
static int set (struct ast_channel *chan, const char *cmd, char *data, char *buf, size_t len)
static int set2 (struct ast_channel *chan, const char *cmd, char *data, struct ast_str **str, ssize_t len)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Logical dialplan functions" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, }
static const struct ast_module_info * ast_module_info = &__mod_info
static struct ast_custom_function exists_function
static struct ast_custom_function if_function
static struct ast_custom_function if_time_function
static struct ast_custom_function import_function
static struct ast_custom_function isnull_function
static struct ast_custom_function set_function
Detailed Description
Conditional logic dialplan functions.
Author
Anthony Minessale II
Definition in file func_logic.c.
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 339 of file func_logic.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 339 of file func_logic.c.
acf_if()
static int acf_if (struct ast_channel * chan, const char * cmd, char * data, char * buf, size_t len) static
Definition at line 168 of file func_logic.c.
References AST_APP_ARG, ast_copy_string(), AST_DECLARE_APP_ARGS, ast_log, AST_NONSTANDARD_APP_ARGS, ast_strip(), ast_strlen_zero, LOG_WARNING, NULL, pbx_checkcondition(), and S_OR.
 {
    AST_DECLARE_APP_ARGS(args1,
       AST_APP_ARG(expr);
       AST_APP_ARG(remainder);
    );
    AST_DECLARE_APP_ARGS(args2,
       AST_APP_ARG(iftrue);
       AST_APP_ARG(iffalse);
    );
    args2.iftrue = args2.iffalse = NULL; /* you have to set these, because if there is nothing after the '?',
                                  then args1.remainder will be NULL, not a pointer to a null string, and
                                  then any garbage in args2.iffalse will not be cleared, and you'll crash.
                                   -- and if you mod the ast_app_separate_args func instead, you'll really
                                  mess things up badly, because the rest of everything depends on null args
                                  for non-specified stuff. */
    AST_NONSTANDARD_APP_ARGS(args1, data, '?');
    AST_NONSTANDARD_APP_ARGS(args2, args1.remainder, ':');
    if (ast_strlen_zero(args1.expr) || !(args2.iftrue || args2.iffalse)) {
       ast_log(LOG_WARNING, "Syntax IF(<expr>?[<true>][:<false>])  (expr must be non-null, and either <true> or <false> must be non-null)\n");
       ast_log(LOG_WARNING, "      In this case, <expr>='%s', <true>='%s', and <false>='%s'\n", args1.expr, args2.iftrue, args2.iffalse);
       return -1;
    }
    args1.expr = ast_strip(args1.expr);
    if (args2.iftrue)
       args2.iftrue = ast_strip(args2.iftrue);
    if (args2.iffalse)
       args2.iffalse = ast_strip(args2.iffalse);
    ast_copy_string(buf, pbx_checkcondition(args1.expr) ? (S_OR(args2.iftrue, "")) : (S_OR(args2.iffalse, "")), len);
    return 0;
 }
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 339 of file func_logic.c.
exists()
static int exists (struct ast_channel * chan, const char * cmd, char * data, char * buf, size_t len) static
Definition at line 124 of file func_logic.c.
Referenced by ast_mwi_mailbox_update(), AST_TEST_DEFINE(), chan_pjsip_cng_tone_detected(), and socket_process_helper().
 {
    strcpy(buf, data && *data ? "1" : "0");
    return 0;
 }
iftime()
static int iftime (struct ast_channel * chan, const char * cmd, char * data, char * buf, size_t len) static
Definition at line 132 of file func_logic.c.
References ast_build_timing(), ast_check_timing(), ast_copy_string(), ast_destroy_timing(), ast_log, ast_strip_quoted(), ast_strlen_zero, LOG_WARNING, S_OR, and strsep().
 {
    struct ast_timing timing;
    char *expr;
    char *iftrue;
    char *iffalse;
    data = ast_strip_quoted(data, "\"", "\"");
    expr = strsep(&data, "?");
    iftrue = strsep(&data, ":");
    iffalse = data;
    if (ast_strlen_zero(expr) || !(iftrue || iffalse)) {
       ast_log(LOG_WARNING,
             "Syntax IFTIME(<timespec>?[<true>][:<false>])\n");
       return -1;
    }
    if (!ast_build_timing(&timing, expr)) {
       ast_log(LOG_WARNING, "Invalid Time Spec.\n");
       ast_destroy_timing(&timing);
       return -1;
    }
    if (iftrue)
       iftrue = ast_strip_quoted(iftrue, "\"", "\"");
    if (iffalse)
       iffalse = ast_strip_quoted(iffalse, "\"", "\"");
    ast_copy_string(buf, ast_check_timing(&timing) ? S_OR(iftrue, "") : S_OR(iffalse, ""), len);
    ast_destroy_timing(&timing);
    return 0;
 }
import_helper()
static int import_helper (struct ast_channel * chan, const char * cmd, char * data, char * buf, struct ast_str ** str, ssize_t len) static
Definition at line 236 of file func_logic.c.
References args, ast_alloca, AST_APP_ARG, ast_channel_get_by_name(), ast_channel_lock, ast_channel_unlock, ast_channel_unref, AST_DECLARE_APP_ARGS, AST_STANDARD_APP_ARGS, ast_str_substitute_variables(), ast_strlen_zero, and pbx_substitute_variables_helper().
Referenced by import_read(), and import_read2().
 {
    AST_DECLARE_APP_ARGS(args,
       AST_APP_ARG(channel);
       AST_APP_ARG(varname);
    );
    AST_STANDARD_APP_ARGS(args, data);
    if (buf) {
       *buf = '\0';
    }
    if (!ast_strlen_zero(args.varname)) {
       struct ast_channel *chan2;
       if ((chan2 = ast_channel_get_by_name(args.channel))) {
          char *s = ast_alloca(strlen(args.varname) + 4);
          sprintf(s, "${%s}", args.varname);
          ast_channel_lock(chan2);
          if (buf) {
             pbx_substitute_variables_helper(chan2, s, buf, len);
          } else {
             ast_str_substitute_variables(str, len, chan2, s);
          }
          ast_channel_unlock(chan2);
          chan2 = ast_channel_unref(chan2);
       }
    }
    return 0;
 }
import_read()
static int import_read (struct ast_channel * chan, const char * cmd, char * data, char * buf, size_t len) static
Definition at line 267 of file func_logic.c.
References import_helper(), and NULL.
 {
    return import_helper(chan, cmd, data, buf, NULL, len);
 }
import_read2()
static int import_read2 (struct ast_channel * chan, const char * cmd, char * data, struct ast_str ** str, ssize_t len) static
Definition at line 272 of file func_logic.c.
References import_helper(), and NULL.
 {
    return import_helper(chan, cmd, data, NULL, str, len);
 }
isnull()
static int isnull (struct ast_channel * chan, const char * cmd, char * data, char * buf, size_t len) static
Definition at line 116 of file func_logic.c.
 {
    strcpy(buf, data && *data ? "0" : "1");
    return 0;
 }
load_module()
static int load_module (void) static
Definition at line 325 of file func_logic.c.
References ast_custom_function_register.
 {
    int res = 0;
    res |= ast_custom_function_register(&isnull_function);
    res |= ast_custom_function_register(&set_function);
    res |= ast_custom_function_register(&exists_function);
    res |= ast_custom_function_register(&if_function);
    res |= ast_custom_function_register(&if_time_function);
    res |= ast_custom_function_register(&import_function);
    return res;
 }
set()
static int set (struct ast_channel * chan, const char * cmd, char * data, char * buf, size_t len) static
Definition at line 206 of file func_logic.c.
References ast_copy_string(), ast_log, ast_strip(), ast_strlen_zero, buf, ast_channel::data, len(), LOG_WARNING, pbx_builtin_setvar_helper(), and strsep().
 {
    char *varname;
    char *val;
    varname = strsep(&data, "=");
    val = data;
    if (ast_strlen_zero(varname) || !val) {
       ast_log(LOG_WARNING, "Syntax SET(<varname>=[<value>])\n");
       return -1;
    }
    varname = ast_strip(varname);
    val = ast_strip(val);
    pbx_builtin_setvar_helper(chan, varname, val);
    ast_copy_string(buf, val, len);
    return 0;
 }
set2()
static int set2 (struct ast_channel * chan, const char * cmd, char * data, struct ast_str ** str, ssize_t len) static
Definition at line 228 of file func_logic.c.
References ast_str_buffer(), ast_str_make_space, ast_str_size(), and ast_channel::data.
 {
    if (len > -1) {
       ast_str_make_space(str, len == 0 ? strlen(data) : len);
    }
    return set(chan, cmd, data, ast_str_buffer(*str), ast_str_size(*str));
 }
unload_module()
static int unload_module (void) static
Definition at line 311 of file func_logic.c.
References ast_custom_function_unregister().
 {
    int res = 0;
    res |= ast_custom_function_unregister(&isnull_function);
    res |= ast_custom_function_unregister(&set_function);
    res |= ast_custom_function_unregister(&exists_function);
    res |= ast_custom_function_unregister(&if_function);
    res |= ast_custom_function_unregister(&if_time_function);
    res |= ast_custom_function_unregister(&import_function);
    return res;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Logical dialplan functions" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, } static
Definition at line 339 of file func_logic.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 339 of file func_logic.c.
exists_function
struct ast_custom_function exists_function static
Initial value:
= {
   .name = "EXISTS",
   .read = exists,
   .read_max = 2,
}
Definition at line 289 of file func_logic.c.
if_function
struct ast_custom_function if_function static
Initial value:
= {
   .name = "IF",
   .read = acf_if,
}
Definition at line 295 of file func_logic.c.
if_time_function
struct ast_custom_function if_time_function static
Initial value:
= {
   .name = "IFTIME",
   .read = iftime,
}
Definition at line 300 of file func_logic.c.
import_function
struct ast_custom_function import_function static
Initial value:
= {
   .name = "IMPORT",
   .read = import_read,
   .read2 = import_read2,
}
Definition at line 305 of file func_logic.c.
isnull_function
struct ast_custom_function isnull_function static
Initial value:
= {
   .name = "ISNULL",
   .read = isnull,
   .read_max = 2,
}
Definition at line 277 of file func_logic.c.
set_function
struct ast_custom_function set_function static
Initial value:
= {
   .name = "SET",
   .read = set,
   .read2 = set2,
}
Definition at line 283 of file func_logic.c.