Asterisk - The Open Source Telephony Project: app_directory.c File Reference
app_directory.c File Reference
Dial plan applications
Provide a directory of extensions.
#include "asterisk.h"
#include <ctype.h>
#include "asterisk/paths.h"
#include "asterisk/file.h"
#include "asterisk/pbx.h"
#include "asterisk/module.h"
#include "asterisk/say.h"
#include "asterisk/app.h"
#include "asterisk/utils.h"
Data Structures
struct directory_item
struct itemlist
Macros
#define VOICEMAIL_CONFIG "voicemail.conf"
Enumerations
enum {
OPT_LISTBYFIRSTNAME = (1 << 0), OPT_SAYEXTENSION = (1 << 1), OPT_FROMVOICEMAIL = (1 << 2), OPT_SELECTFROMMENU = (1 << 3),
OPT_LISTBYLASTNAME = (1 << 4), OPT_LISTBYEITHER = OPT_LISTBYFIRSTNAME | OPT_LISTBYLASTNAME, OPT_PAUSE = (1 << 5), OPT_NOANSWER = (1 << 6),
OPT_ALIAS = (1 << 7)
}
enum {
OPT_ARG_FIRSTNAME = 0, OPT_ARG_LASTNAME = 1, OPT_ARG_EITHER = 2, OPT_ARG_PAUSE = 3,
OPT_ARG_ARRAY_SIZE = 4
}
Functions
static void __init_commonbuf (void)
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int check_match (struct directory_item **result, const char *item_context, const char *item_fullname, const char *item_ext, const char *pattern_ext, int use_first_name)
static int compare (const char *text, const char *template)
static int directory_exec (struct ast_channel *chan, const char *data)
static int do_directory (struct ast_channel *chan, struct ast_config *vmcfg, struct ast_config *ucfg, char *context, char *dialcontext, char digit, int digits, struct ast_flags *flags, char *opts[])
static int goto_exten (struct ast_channel *chan, const char *dialcontext, char *ext)
static int load_module (void)
static int play_mailbox_owner (struct ast_channel *chan, const char *context, const char *ext, const char *name, struct ast_flags *flags)
static struct ast_config * realtime_directory (char *context)
static int search_directory (const char *context, struct ast_config *vmcfg, struct ast_config *ucfg, const char *ext, struct ast_flags flags, itemlist *alist)
static int search_directory_sub (const char *context, struct ast_config *vmcfg, struct ast_config *ucfg, const char *ext, struct ast_flags flags, itemlist *alist)
static int select_entry (struct ast_channel *chan, const char *dialcontext, const struct directory_item *item, struct ast_flags *flags)
static int select_item_menu (struct ast_channel *chan, struct directory_item **items, int count, const char *dialcontext, struct ast_flags *flags, char *opts[])
static int select_item_pause (struct ast_channel *chan, struct ast_flags *flags, char *opts[])
static int select_item_seq (struct ast_channel *chan, struct directory_item **items, int count, const char *dialcontext, struct ast_flags *flags, char *opts[])
static void sort_items (struct directory_item **sorted, int count)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Extension Directory" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, }
static const char app [] = "Directory"
static const struct ast_module_info * ast_module_info = &__mod_info
static struct ast_threadstorage commonbuf = { .once = PTHREAD_ONCE_INIT , .key_init = __init_commonbuf , .custom_init = NULL , }
static const struct ast_app_option directory_app_options [128] = { [ 'f' ] = { .flag = OPT_LISTBYFIRSTNAME , .arg_index = OPT_ARG_FIRSTNAME + 1 }, [ 'l' ] = { .flag = OPT_LISTBYLASTNAME , .arg_index = OPT_ARG_LASTNAME + 1 }, [ 'b' ] = { .flag = OPT_LISTBYEITHER , .arg_index = OPT_ARG_EITHER + 1 }, [ 'p' ] = { .flag = OPT_PAUSE , .arg_index = OPT_ARG_PAUSE + 1 }, [ 'e' ] = { .flag = OPT_SAYEXTENSION }, [ 'v' ] = { .flag = OPT_FROMVOICEMAIL }, [ 'm' ] = { .flag = OPT_SELECTFROMMENU }, [ 'n' ] = { .flag = OPT_NOANSWER }, [ 'a' ] = { .flag = OPT_ALIAS }, }
Detailed Description
Provide a directory of extensions.
Author
Mark Spencer marks.nosp@m.ter@.nosp@m.digiu.nosp@m.m.co.nosp@m.m
Definition in file app_directory.c.
Macro Definition Documentation
VOICEMAIL_CONFIG
#define VOICEMAIL_CONFIG "voicemail.conf"
Definition at line 144 of file app_directory.c.
Referenced by realtime_directory().
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
OPT_LISTBYFIRSTNAME
OPT_SAYEXTENSION
OPT_FROMVOICEMAIL
OPT_SELECTFROMMENU
OPT_LISTBYLASTNAME
OPT_LISTBYEITHER
OPT_PAUSE
OPT_NOANSWER
OPT_ALIAS
Definition at line 146 of file app_directory.c.
      {
    OPT_LISTBYFIRSTNAME = (1 << 0),
    OPT_SAYEXTENSION =    (1 << 1),
    OPT_FROMVOICEMAIL =   (1 << 2),
    OPT_SELECTFROMMENU =  (1 << 3),
    OPT_LISTBYLASTNAME =  (1 << 4),
    OPT_LISTBYEITHER =    OPT_LISTBYFIRSTNAME | OPT_LISTBYLASTNAME,
    OPT_PAUSE =           (1 << 5),
    OPT_NOANSWER =        (1 << 6),
    OPT_ALIAS =           (1 << 7),
 };
anonymous enum
anonymous enum
Enumerator
OPT_ARG_FIRSTNAME
OPT_ARG_LASTNAME
OPT_ARG_EITHER
OPT_ARG_PAUSE
OPT_ARG_ARRAY_SIZE
Definition at line 158 of file app_directory.c.
      {
    OPT_ARG_FIRSTNAME =   0,
    OPT_ARG_LASTNAME =    1,
    OPT_ARG_EITHER =      2,
    OPT_ARG_PAUSE =       3,
    /* This *must* be the last value in this enum! */
    OPT_ARG_ARRAY_SIZE =  4,
 };
Function Documentation
__init_commonbuf()
static void __init_commonbuf (void) static
Definition at line 459 of file app_directory.c.
 {
__reg_module()
static void __reg_module (void) static
Definition at line 992 of file app_directory.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 992 of file app_directory.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 992 of file app_directory.c.
check_match()
static int check_match (struct directory_item ** result, const char * item_context, const char * item_fullname, const char * item_ext, const char * pattern_ext, int use_first_name) static
Definition at line 559 of file app_directory.c.
References ast_calloc, ast_copy_string(), ast_debug, ast_strlen_zero, compare(), directory_item::context, directory_item::exten, item, directory_item::key, directory_item::name, and NULL.
Referenced by search_directory_sub().
 {
    struct directory_item *item;
    const char *key = NULL;
    int namelen;
    if (ast_strlen_zero(item_fullname)) {
       return 0;
    }
    /* Set key to last name or first name depending on search mode */
    if (!use_first_name)
       key = strchr(item_fullname, ' ');
    if (key)
       key++;
    else
       key = item_fullname;
    if (compare(key, pattern_ext))
       return 0;
    ast_debug(1, "Found match %s@%s\n", item_ext, item_context);
    /* Match */
    item = ast_calloc(1, sizeof(*item));
    if (!item)
       return -1;
    ast_copy_string(item->context, item_context, sizeof(item->context));
    ast_copy_string(item->name, item_fullname, sizeof(item->name));
    ast_copy_string(item->exten, item_ext, sizeof(item->exten));
    ast_copy_string(item->key, key, sizeof(item->key));
    if (key != item_fullname) {
       /* Key is the last name. Append first name to key in order to sort Last,First */
       namelen = key - item_fullname - 1;
       if (namelen > sizeof(item->key) - strlen(item->key) - 1)
          namelen = sizeof(item->key) - strlen(item->key) - 1;
       strncat(item->key, item_fullname, namelen);
    }
    *result = item;
    return 1;
 }
compare()
static int compare (const char * text, const char * template) static
Definition at line 188 of file app_directory.c.
References ast_strlen_zero, and digit.
Referenced by _ast_hashtab_create(), ast_sip_is_content_type(), and check_match().
 {
    char digit;
    if (ast_strlen_zero(text)) {
       return -1;
    }
    while (*template) {
       digit = toupper(*text++);
       switch (digit) {
       case 0:
          return -1;
       case '1':
          digit = '1';
          break;
       case '2':
       case 'A':
       case 'B':
       case 'C':
          digit = '2';
          break;
       case '3':
       case 'D':
       case 'E':
       case 'F':
          digit = '3';
          break;
       case '4':
       case 'G':
       case 'H':
       case 'I':
          digit = '4';
          break;
       case '5':
       case 'J':
       case 'K':
       case 'L':
          digit = '5';
          break;
       case '6':
       case 'M':
       case 'N':
       case 'O':
          digit = '6';
          break;
       case '7':
       case 'P':
       case 'Q':
       case 'R':
       case 'S':
          digit = '7';
          break;
       case '8':
       case 'T':
       case 'U':
       case 'V':
          digit = '8';
          break;
       case '9':
       case 'W':
       case 'X':
       case 'Y':
       case 'Z':
          digit = '9';
          break;
       default:
          if (digit > ' ')
             return -1;
          continue;
       }
       if (*template++ != digit)
          return -1;
    }
    return 0;
 }
directory_exec()
static int directory_exec (struct ast_channel * chan, const char * data) static
Definition at line 847 of file app_directory.c.
References args, ast_answer(), AST_APP_ARG, ast_app_parse_options(), ast_check_hangup(), ast_config_destroy(), ast_config_load, AST_DECLARE_APP_ARGS, AST_DIGIT_ANY, ast_log, ast_set_flag, AST_STANDARD_APP_ARGS, AST_STATE_UP, ast_stopstream(), ast_strdupa, ast_stream_and_wait(), ast_strlen_zero, ast_test_flag, ast_variable_retrieve(), ast_waitfordigit(), ast_waitstream(), CONFIG_STATUS_FILEINVALID, dialcontext, digit, directory_app_options, do_directory(), LOG_ERROR, NULL, OPT_ARG_ARRAY_SIZE, OPT_ARG_EITHER, OPT_ARG_FIRSTNAME, OPT_ARG_LASTNAME, OPT_LISTBYFIRSTNAME, OPT_LISTBYLASTNAME, OPT_NOANSWER, options, parse(), pbx_builtin_setvar_helper(), and realtime_directory().
Referenced by load_module().
 {
    int res = 0, digit = 3;
    struct ast_config *cfg, *ucfg;
    const char *dirintro;
    char *parse, *opts[OPT_ARG_ARRAY_SIZE] = { 0, };
    struct ast_flags flags = { 0 };
    struct ast_flags config_flags = { 0 };
    enum { FIRST, LAST, BOTH } which = LAST;
    char digits[9] = "digits/3";
    AST_DECLARE_APP_ARGS(args,
       AST_APP_ARG(vmcontext);
       AST_APP_ARG(dialcontext);
       AST_APP_ARG(options);
    );
    parse = ast_strdupa(data);
    AST_STANDARD_APP_ARGS(args, parse);
    if (args.options && ast_app_parse_options(directory_app_options, &flags, opts, args.options))
       return -1;
    if (!(cfg = realtime_directory(args.vmcontext))) {
       ast_log(LOG_ERROR, "Unable to read the configuration data!\n");
       return -1;
    }
    if ((ucfg = ast_config_load("users.conf", config_flags)) == CONFIG_STATUS_FILEINVALID) {
       ast_log(LOG_ERROR, "Config file users.conf is in an invalid format.  Aborting.\n");
       ucfg = NULL;
    }
    dirintro = ast_variable_retrieve(cfg, args.vmcontext, "directoryintro");
    if (ast_strlen_zero(dirintro))
       dirintro = ast_variable_retrieve(cfg, "general", "directoryintro");
    /* the above prompts probably should be modified to include 0 for dialing operator
       and # for exiting (continues in dialplan) */
    if (ast_test_flag(&flags, OPT_LISTBYFIRSTNAME) && ast_test_flag(&flags, OPT_LISTBYLASTNAME)) {
       if (!ast_strlen_zero(opts[OPT_ARG_EITHER])) {
          digit = atoi(opts[OPT_ARG_EITHER]);
       }
       which = BOTH;
    } else if (ast_test_flag(&flags, OPT_LISTBYFIRSTNAME)) {
       if (!ast_strlen_zero(opts[OPT_ARG_FIRSTNAME])) {
          digit = atoi(opts[OPT_ARG_FIRSTNAME]);
       }
       which = FIRST;
    } else {
       if (!ast_strlen_zero(opts[OPT_ARG_LASTNAME])) {
          digit = atoi(opts[OPT_ARG_LASTNAME]);
       }
       which = LAST;
    }
    /* If no options specified, search by last name */
    if (!ast_test_flag(&flags, OPT_LISTBYFIRSTNAME) && !ast_test_flag(&flags, OPT_LISTBYLASTNAME)) {
       ast_set_flag(&flags, OPT_LISTBYLASTNAME);
       which = LAST;
    }
    if (digit > 9) {
       digit = 9;
    } else if (digit < 1) {
       digit = 3;
    }
    digits[7] = digit + '0';
    if (ast_channel_state(chan) != AST_STATE_UP) {
       if (!ast_test_flag(&flags, OPT_NOANSWER)) {
          /* Otherwise answer unless we're supposed to read while on-hook */
          res = ast_answer(chan);
       }
    }
    for (;;) {
       if (!ast_strlen_zero(dirintro) && !res) {
          res = ast_stream_and_wait(chan, dirintro, AST_DIGIT_ANY);
       } else if (!res) {
          /* Stop playing sounds as soon as we have a digit. */
          res = ast_stream_and_wait(chan, "dir-welcome", AST_DIGIT_ANY);
          if (!res) {
             res = ast_stream_and_wait(chan, "dir-pls-enter", AST_DIGIT_ANY);
          }
          if (!res) {
             res = ast_stream_and_wait(chan, digits, AST_DIGIT_ANY);
          }
          if (!res) {
             res = ast_stream_and_wait(chan,
                which == FIRST ? "dir-first" :
                which == LAST ? "dir-last" :
                "dir-firstlast", AST_DIGIT_ANY);
          }
          if (!res) {
             res = ast_stream_and_wait(chan, "dir-usingkeypad", AST_DIGIT_ANY);
          }
       }
       ast_stopstream(chan);
       if (!res)
          res = ast_waitfordigit(chan, 5000);
       if (res <= 0) {
          if (res == 0) {
             pbx_builtin_setvar_helper(chan, "DIRECTORY_RESULT", "TIMEOUT");
          }
          break;
       }
       res = do_directory(chan, cfg, ucfg, args.vmcontext, args.dialcontext, res, digit, &flags, opts);
       if (res)
          break;
       res = ast_waitstream(chan, AST_DIGIT_ANY);
       ast_stopstream(chan);
       if (res < 0) {
          break;
       }
    }
    if (ucfg)
       ast_config_destroy(ucfg);
    ast_config_destroy(cfg);
    if (ast_check_hangup(chan)) {
       pbx_builtin_setvar_helper(chan, "DIRECTORY_RESULT", "HANGUP");
    } else if (res < 0) {
       /* If the res < 0 and we didn't hangup, an unaccounted for error must have happened. */
       pbx_builtin_setvar_helper(chan, "DIRECTORY_RESULT", "FAILED");
    }
    return res < 0 ? -1 : 0;
 }
do_directory()
static int do_directory (struct ast_channel * chan, struct ast_config * vmcfg, struct ast_config * ucfg, char * context, char * dialcontext, char digit, int digits, struct ast_flags * flags, char * opts[]) static
Definition at line 768 of file app_directory.c.
References ast_calloc, ast_channel_language(), ast_free, AST_LIST_HEAD_NOLOCK_INIT_VALUE, AST_LIST_REMOVE_HEAD, AST_LIST_TRAVERSE, ast_log, ast_readstring(), ast_streamfile(), ast_test_flag, DEBUG_ATLEAST, digit, ext, directory_item::exten, goto_exten(), item, LOG_DEBUG, directory_item::name, NULL, OPT_SELECTFROMMENU, pbx_builtin_setvar_helper(), search_directory(), select_item_menu(), select_item_seq(), and sort_items().
Referenced by directory_exec().
 {
    /* Read in the first three digits..  "digit" is the first digit, already read */
    int res = 0;
    itemlist alist = AST_LIST_HEAD_NOLOCK_INIT_VALUE;
    struct directory_item *item, **ptr, **sorted = NULL;
    int count, i;
    char ext[10] = "";
    if (digit == '0' && !goto_exten(chan, dialcontext, "o")) {
       pbx_builtin_setvar_helper(chan, "DIRECTORY_RESULT", "OPERATOR");
       return digit;
    }
    if (digit == '*' && !goto_exten(chan, dialcontext, "a")) {
       pbx_builtin_setvar_helper(chan, "DIRECTORY_RESULT", "ASSISTANT");
       return digit;
    }
    ext[0] = digit;
    if (ast_readstring(chan, ext + 1, digits - 1, 3000, 3000, "#") < 0)
       return -1;
    res = search_directory(context, vmcfg, ucfg, ext, *flags, &alist);
    if (res)
       goto exit;
    /* Count items in the list */
    count = 0;
    AST_LIST_TRAVERSE(&alist, item, entry) {
       count++;
    }
    if (count < 1) {
       res = ast_streamfile(chan, "dir-nomatch", ast_channel_language(chan));
       goto exit;
    }
    /* Create plain array of pointers to items (for sorting) */
    sorted = ast_calloc(count, sizeof(*sorted));
    ptr = sorted;
    AST_LIST_TRAVERSE(&alist, item, entry) {
       *ptr++ = item;
    }
    /* Sort items */
    sort_items(sorted, count);
    if (DEBUG_ATLEAST(2)) {
       ast_log(LOG_DEBUG, "Listing matching entries:\n");
       for (ptr = sorted, i = 0; i < count; i++, ptr++) {
          ast_log(LOG_DEBUG, "%s: %s\n", ptr[0]->exten, ptr[0]->name);
       }
    }
    if (ast_test_flag(flags, OPT_SELECTFROMMENU)) {
       /* Offer multiple entries at the same time */
       res = select_item_menu(chan, sorted, count, dialcontext, flags, opts);
    } else {
       /* Offer entries one by one */
       res = select_item_seq(chan, sorted, count, dialcontext, flags, opts);
    }
    if (!res) {
       res = ast_streamfile(chan, "dir-nomore", ast_channel_language(chan));
    }
 exit:
    if (sorted)
       ast_free(sorted);
    while ((item = AST_LIST_REMOVE_HEAD(&alist, entry)))
       ast_free(item);
    return res;
 }
goto_exten()
static int goto_exten (struct ast_channel * chan, const char * dialcontext, char * ext) static
Definition at line 268 of file app_directory.c.
References ast_channel_context(), ast_channel_macrocontext(), ast_goto_if_exists(), ast_log, ast_strlen_zero, LOG_WARNING, and S_OR.
Referenced by do_directory(), and select_item_seq().
 {
    if (!ast_goto_if_exists(chan, S_OR(dialcontext, ast_channel_context(chan)), ext, 1) ||
       (!ast_strlen_zero(ast_channel_macrocontext(chan)) &&
       !ast_goto_if_exists(chan, ast_channel_macrocontext(chan), ext, 1))) {
       return 0;
    } else {
       ast_log(LOG_WARNING, "Can't find extension '%s' in current context.  "
          "Not Exiting the Directory!\n", ext);
       return -1;
    }
 }
load_module()
static int load_module (void) static
Definition at line 987 of file app_directory.c.
References app, ast_register_application_xml, and directory_exec().
 {
    return ast_register_application_xml(app, directory_exec);
 }
play_mailbox_owner()
static int play_mailbox_owner (struct ast_channel * chan, const char * context, const char * ext, const char * name, struct ast_flags * flags) static
Definition at line 286 of file app_directory.c.
References ast_alloca, ast_app_sayname(), ast_channel_language(), AST_DIGIT_ANY, AST_SAY_CASE_NONE, ast_say_character_str(), ast_stopstream(), ast_stream_and_wait(), ast_strlen_zero, ast_test_flag, OPT_SAYEXTENSION, and S_OR.
Referenced by select_item_menu(), and select_item_seq().
 {
    int res = 0;
    char *mailbox_id;
    mailbox_id = ast_alloca(strlen(ext) + strlen(context) + 2);
    sprintf(mailbox_id, "%s@%s", ext, context); /* Safe */
    res = ast_app_sayname(chan, mailbox_id);
    if (res >= 0) {
       ast_stopstream(chan);
       /* If Option 'e' was specified, also read the extension number with the name */
       if (ast_test_flag(flags, OPT_SAYEXTENSION)) {
          ast_stream_and_wait(chan, "vm-extension", AST_DIGIT_ANY);
          res = ast_say_character_str(chan, ext, AST_DIGIT_ANY, ast_channel_language(chan), AST_SAY_CASE_NONE);
       }
    } else {
       res = ast_say_character_str(chan, S_OR(name, ext), AST_DIGIT_ANY, ast_channel_language(chan), AST_SAY_CASE_NONE);
       if (!ast_strlen_zero(name) && ast_test_flag(flags, OPT_SAYEXTENSION)) {
          ast_stream_and_wait(chan, "vm-extension", AST_DIGIT_ANY);
          res = ast_say_character_str(chan, ext, AST_DIGIT_ANY, ast_channel_language(chan), AST_SAY_CASE_NONE);
       }
    }
    return res;
 }
realtime_directory()
static struct ast_config* realtime_directory (char * context) static
Definition at line 461 of file app_directory.c.
References ast_category_append(), ast_category_browse(), ast_category_get(), ast_category_new_dynamic, ast_config_destroy(), ast_config_load, ast_debug, ast_load_realtime_multientry(), ast_log, ast_str_append(), ast_str_buffer(), ast_str_set(), ast_str_thread_get(), ast_strlen_zero, ast_true(), ast_variable_append(), ast_variable_browse(), ast_variable_new, ast_variable_retrieve(), CONFIG_STATUS_FILEINVALID, LOG_ERROR, LOG_WARNING, mailbox, ast_variable::name, ast_variable::next, NULL, S_OR, SENTINEL, tmp(), ast_variable::value, var, and VOICEMAIL_CONFIG.
Referenced by directory_exec().
 {
    struct ast_config *cfg;
    struct ast_config *rtdata = NULL;
    struct ast_category *cat;
    struct ast_variable *var;
    char *category = NULL;
    const char *fullname;
    const char *hidefromdir, *searchcontexts = NULL;
    struct ast_flags config_flags = { 0 };
    struct ast_str *tmp = ast_str_thread_get(&commonbuf, 100);
    if (!tmp) {
       return NULL;
    }
    /* Load flat file config. */
    cfg = ast_config_load(VOICEMAIL_CONFIG, config_flags);
    if (!cfg) {
       /* Loading config failed. */
       ast_log(LOG_WARNING, "Loading config failed.\n");
       return NULL;
    } else if (cfg == CONFIG_STATUS_FILEINVALID) {
       ast_log(LOG_ERROR, "Config file %s is in an invalid format.  Aborting.\n", VOICEMAIL_CONFIG);
       return NULL;
    }
    /* Get realtime entries, categorized by their mailbox number
       and present in the requested context */
    if (ast_strlen_zero(context) && (searchcontexts = ast_variable_retrieve(cfg, "general", "searchcontexts"))) {
       if (ast_true(searchcontexts)) {
          rtdata = ast_load_realtime_multientry("voicemail", "mailbox LIKE", "%", SENTINEL);
          context = NULL;
       } else {
          rtdata = ast_load_realtime_multientry("voicemail", "mailbox LIKE", "%", "context", "default", SENTINEL);
          context = "default";
       }
    } else if (!ast_strlen_zero(context)) {
       rtdata = ast_load_realtime_multientry("voicemail", "mailbox LIKE", "%", "context", context, SENTINEL);
    }
    /* if there are no results, just return the entries from the config file */
    if (!rtdata) {
       return cfg;
    }
    while ((category = ast_category_browse(rtdata, category))) {
       const char *mailbox = ast_variable_retrieve(rtdata, category, "mailbox");
       const char *ctx = ast_variable_retrieve(rtdata, category, "context");
       if (ast_strlen_zero(mailbox)) {
          ast_debug(3, "Skipping result with missing or empty mailbox\n");
          continue;
       }
       fullname = ast_variable_retrieve(rtdata, category, "fullname");
       hidefromdir = ast_variable_retrieve(rtdata, category, "hidefromdir");
       if (ast_true(hidefromdir)) {
          /* Skip hidden */
          continue;
       }
       /* password,Full Name,email,pager,options */
       ast_str_set(&tmp, 0, "no-password,%s,,,", S_OR(fullname, ""));
       if (ast_variable_retrieve(rtdata, category, "alias")) {
          struct ast_variable *alias;
          for (alias = ast_variable_browse(rtdata, category); alias; alias = alias->next) {
             if (!strcasecmp(alias->name, "alias")) {
                ast_str_append(&tmp, 0, "|alias=%s", alias->value);
             }
          }
       }
       /* Does the context exist within the config file? If not, make one */
       if (!(cat = ast_category_get(cfg, ctx, NULL))) {
          if (!(cat = ast_category_new_dynamic(ctx))) {
             ast_log(LOG_WARNING, "Out of memory\n");
             ast_config_destroy(cfg);
             if (rtdata) {
                ast_config_destroy(rtdata);
             }
             return NULL;
          }
          ast_category_append(cfg, cat);
       }
       if ((var = ast_variable_new(mailbox, ast_str_buffer(tmp), ""))) {
          ast_variable_append(cat, var);
       } else {
          ast_log(LOG_WARNING, "Out of memory adding mailbox '%s'\n", mailbox);
       }
    }
    ast_config_destroy(rtdata);
    return cfg;
 }
search_directory()
static int search_directory (const char * context, struct ast_config * vmcfg, struct ast_config * ucfg, const char * ext, struct ast_flags flags, itemlist * alist) static
Definition at line 717 of file app_directory.c.
References ast_category_browse(), ast_debug, ast_strlen_zero, ast_true(), ast_variable_retrieve(), NULL, and search_directory_sub().
Referenced by do_directory().
 {
    const char *searchcontexts = ast_variable_retrieve(vmcfg, "general", "searchcontexts");
    if (ast_strlen_zero(context)) {
       if (!ast_strlen_zero(searchcontexts) && ast_true(searchcontexts)) {
          /* Browse each context for a match */
          int res;
          const char *catg;
          for (catg = ast_category_browse(vmcfg, NULL); catg; catg = ast_category_browse(vmcfg, catg)) {
             if (!strcmp(catg, "general") || !strcmp(catg, "zonemessages")) {
                continue;
             }
             if ((res = search_directory_sub(catg, vmcfg, ucfg, ext, flags, alist))) {
                return res;
             }
          }
          return 0;
       } else {
          ast_debug(1, "Searching by category default\n");
          return search_directory_sub("default", vmcfg, ucfg, ext, flags, alist);
       }
    } else {
       /* Browse only the listed context for a match */
       ast_debug(1, "Searching by category %s\n", context);
       return search_directory_sub(context, vmcfg, ucfg, ext, flags, alist);
    }
 }
search_directory_sub()
static int search_directory_sub (const char * context, struct ast_config * vmcfg, struct ast_config * ucfg, const char * ext, struct ast_flags flags, itemlist * alist) static
Definition at line 606 of file app_directory.c.
References a, ast_category_browse(), ast_config_option(), ast_debug, AST_LIST_INSERT_TAIL, ast_str_buffer(), ast_str_set(), ast_str_thread_get(), ast_strlen_zero, ast_test_flag, ast_true(), ast_variable_browse(), ast_variable_retrieve(), buf, check_match(), item, ast_variable::name, directory_item::name, ast_variable::next, NULL, OPT_ALIAS, OPT_LISTBYFIRSTNAME, OPT_LISTBYLASTNAME, options, strcasestr(), strsep(), and ast_variable::value.
Referenced by search_directory().
 {
    struct ast_variable *v;
    struct ast_str *buf = ast_str_thread_get(&commonbuf, 100);
    char *name;
    char *options;
    char *alias;
    char *cat;
    struct directory_item *item;
    int res;
    if (!buf) {
       return -1;
    }
    ast_debug(2, "Pattern: %s\n", ext);
    for (v = ast_variable_browse(vmcfg, context); v; v = v->next) {
       ast_str_set(&buf, 0, "%s", v->value);
       options = ast_str_buffer(buf);
       /* password,Full Name,email,pager,options */
       strsep(&options, ",");          /* Skip password */
       name = strsep(&options, ",");   /* Save full name */
       strsep(&options, ",");          /* Skip email */
       strsep(&options, ",");          /* Skip pager */
       /* options is now the options field if it exists. */
       if (options && strcasestr(options, "hidefromdir=yes")) {
          /* Ignore hidden */
          continue;
       }
       if (ast_strlen_zero(name)) {
          /* No name to compare against */
          continue;
       }
       res = 0;
       if (ast_test_flag(&flags, OPT_LISTBYLASTNAME)) {
          res = check_match(&item, context, name, v->name, ext, 0 /* use_first_name */);
       }
       if (!res && ast_test_flag(&flags, OPT_LISTBYFIRSTNAME)) {
          res = check_match(&item, context, name, v->name, ext, 1 /* use_first_name */);
       }
       if (!res && ast_test_flag(&flags, OPT_ALIAS)
          && options && (alias = strcasestr(options, "alias="))) {
          char *a;
          ast_debug(1, "Found alias: %s\n", alias);
          while ((a = strsep(&alias, "|"))) {
             if (!strncasecmp(a, "alias=", 6)) {
                if ((res = check_match(&item, context, a + 6, v->name, ext, 1))) {
                   break;
                }
             }
          }
       }
       if (!res) {
          continue;
       } else if (res < 0) {
          return -1;
       }
       AST_LIST_INSERT_TAIL(alist, item, entry);
    }
    if (ucfg) {
       for (cat = ast_category_browse(ucfg, NULL); cat ; cat = ast_category_browse(ucfg, cat)) {
          const char *position;
          if (!strcasecmp(cat, "general")) {
             continue;
          }
          if (!ast_true(ast_config_option(ucfg, cat, "hasdirectory"))) {
             continue;
          }
          /* Find all candidate extensions */
          if (!(position = ast_variable_retrieve(ucfg, cat, "fullname"))) {
             continue;
          }
          res = 0;
          if (ast_test_flag(&flags, OPT_LISTBYLASTNAME)) {
             res = check_match(&item, context, position, cat, ext, 0 /* use_first_name */);
          }
          if (!res && ast_test_flag(&flags, OPT_LISTBYFIRSTNAME)) {
             res = check_match(&item, context, position, cat, ext, 1 /* use_first_name */);
          }
          if (!res && ast_test_flag(&flags, OPT_ALIAS)) {
             for (v = ast_variable_browse(ucfg, cat); v; v = v->next) {
                if (!strcasecmp(v->name, "alias")
                   && (res = check_match(&item, context, v->value, cat, ext, 1))) {
                   break;
                }
             }
          }
          if (!res) {
             continue;
          } else if (res < 0) {
             return -1;
          }
          AST_LIST_INSERT_TAIL(alist, item, entry);
       }
    }
    return 0;
 }
select_entry()
static int select_entry (struct ast_channel * chan, const char * dialcontext, const struct directory_item * item, struct ast_flags * flags) static
Definition at line 314 of file app_directory.c.
References ast_channel_exten_set(), ast_debug, ast_goto_if_exists(), ast_log, ast_test_flag, directory_item::context, directory_item::exten, LOG_WARNING, directory_item::name, OPT_FROMVOICEMAIL, pbx_builtin_setvar_helper(), and S_OR.
Referenced by select_item_menu(), and select_item_seq().
 {
    ast_debug(1, "Selecting '%s' - %s@%s\n", item->name, item->exten, S_OR(dialcontext, item->context));
    if (ast_test_flag(flags, OPT_FROMVOICEMAIL)) {
       /* We still want to set the exten though */
       ast_channel_exten_set(chan, item->exten);
    } else if (ast_goto_if_exists(chan, S_OR(dialcontext, item->context), item->exten, 1)) {
       ast_log(LOG_WARNING,
          "Can't find extension '%s' in context '%s'.  "
          "Did you pass the wrong context to Directory?\n",
          item->exten, S_OR(dialcontext, item->context));
       return -1;
    }
    pbx_builtin_setvar_helper(chan, "DIRECTORY_RESULT", "SELECTED");
    return 0;
 }
select_item_menu()
static int select_item_menu (struct ast_channel * chan, struct directory_item ** items, int count, const char * dialcontext, struct ast_flags * flags, char * opts[]) static
Definition at line 395 of file app_directory.c.
References ast_channel_language(), AST_DIGIT_ANY, ast_streamfile(), ast_waitfordigit(), ast_waitstream(), buf, directory_item::context, directory_item::exten, item, directory_item::name, pbx_builtin_setvar_helper(), play_mailbox_owner(), select_entry(), and select_item_pause().
Referenced by do_directory().
 {
    struct directory_item **block, *item;
    int i, limit, res = 0;
    char buf[7+12]; /* INT_MIN has a length of 12 chars */
    /* option p(n): cellphone pause option */
    select_item_pause(chan, flags, opts);
    for (block = items; count; block += limit, count -= limit) {
       limit = count;
       if (limit > 8)
          limit = 8;
       for (i = 0; i < limit && !res; i++) {
          item = block[i];
          snprintf(buf, sizeof(buf), "digits/%d", i + 1);
          /* Press <num> for <name>, [ extension <ext> ] */
          res = ast_streamfile(chan, "dir-multi1", ast_channel_language(chan));
          if (!res)
             res = ast_waitstream(chan, AST_DIGIT_ANY);
          if (!res)
             res = ast_streamfile(chan, buf, ast_channel_language(chan));
          if (!res)
             res = ast_waitstream(chan, AST_DIGIT_ANY);
          if (!res)
             res = ast_streamfile(chan, "dir-multi2", ast_channel_language(chan));
          if (!res)
             res = ast_waitstream(chan, AST_DIGIT_ANY);
          if (!res)
             res = play_mailbox_owner(chan, item->context, item->exten, item->name, flags);
          if (!res)
             res = ast_waitstream(chan, AST_DIGIT_ANY);
          if (!res)
             res = ast_waitfordigit(chan, 800);
       }
       /* Press "9" for more names. */
       if (!res && count > limit) {
          res = ast_streamfile(chan, "dir-multi9", ast_channel_language(chan));
          if (!res)
             res = ast_waitstream(chan, AST_DIGIT_ANY);
       }
       if (!res) {
          res = ast_waitfordigit(chan, 3000);
       }
       if (res && res > '0' && res < '1' + limit) {
          pbx_builtin_setvar_helper(chan, "DIRECTORY_RESULT", "SELECTED");
          return select_entry(chan, dialcontext, block[res - '1'], flags) ? -1 : 1;
       }
       if (res < 0)
          return -1;
       res = 0;
    }
    /* Nothing was selected */
    return 0;
 }
select_item_pause()
static int select_item_pause (struct ast_channel * chan, struct ast_flags * flags, char * opts[]) static
Definition at line 333 of file app_directory.c.
References ast_strlen_zero, ast_test_flag, ast_waitfordigit(), OPT_ARG_PAUSE, and OPT_PAUSE.
Referenced by select_item_menu(), and select_item_seq().
 {
    int res = 0, opt_pause = 0;
    if (ast_test_flag(flags, OPT_PAUSE) && !ast_strlen_zero(opts[OPT_ARG_PAUSE])) {
       opt_pause = atoi(opts[OPT_ARG_PAUSE]);
       if (opt_pause > 3000) {
          opt_pause = 3000;
       }
       res = ast_waitfordigit(chan, opt_pause);
    }
    return res;
 }
select_item_seq()
static int select_item_seq (struct ast_channel * chan, struct directory_item ** items, int count, const char * dialcontext, struct ast_flags * flags, char * opts[]) static
Definition at line 347 of file app_directory.c.
References AST_DIGIT_ANY, ast_stopstream(), ast_stream_and_wait(), ast_waitfordigit(), directory_item::context, directory_item::exten, goto_exten(), item, directory_item::name, pbx_builtin_setvar_helper(), play_mailbox_owner(), select_entry(), and select_item_pause().
Referenced by do_directory().
 {
    struct directory_item *item, **ptr;
    int i, res, loop;
    /* option p(n): cellphone pause option */
    /* allow early press of selection key */
    res = select_item_pause(chan, flags, opts);
    for (ptr = items, i = 0; i < count; i++, ptr++) {
       item = *ptr;
       for (loop = 3 ; loop > 0; loop--) {
          if (!res)
             res = play_mailbox_owner(chan, item->context, item->exten, item->name, flags);
          if (!res)
             res = ast_stream_and_wait(chan, "dir-instr", AST_DIGIT_ANY);
          if (!res)
             res = ast_waitfordigit(chan, 3000);
          ast_stopstream(chan);
          if (res == '0') { /* operator selected */
             goto_exten(chan, dialcontext, "o");
             pbx_builtin_setvar_helper(chan, "DIRECTORY_RESULT", "OPERATOR");
             return '0';
          } else if (res == '1') { /* Name selected */
             return select_entry(chan, dialcontext, item, flags) ? -1 : 1;
          } else if (res == '*') {
             /* Skip to next match in list */
             break;
          } else if (res == '#') {
             /* Exit reading, continue in dialplan */
             pbx_builtin_setvar_helper(chan, "DIRECTORY_RESULT", "USEREXIT");
             return res;
          }
          if (res < 0)
             return -1;
          res = 0;
       }
       res = 0;
    }
    /* Nothing was selected */
    return 0;
 }
sort_items()
static void sort_items (struct directory_item ** sorted, int count) static
Definition at line 746 of file app_directory.c.
References directory_item::key, and tmp().
Referenced by do_directory().
 {
    int reordered, i;
    struct directory_item **ptr, *tmp;
    if (count < 2)
       return;
    /* Bubble-sort items by the key */
    do {
       reordered = 0;
       for (ptr = sorted, i = 0; i < count - 1; i++, ptr++) {
          if (strcasecmp(ptr[0]->key, ptr[1]->key) > 0) {
             tmp = ptr[0];
             ptr[0] = ptr[1];
             ptr[1] = tmp;
             reordered++;
          }
       }
    } while (reordered);
 }
unload_module()
static int unload_module (void) static
Definition at line 980 of file app_directory.c.
References app, and ast_unregister_application().
 {
    int res;
    res = ast_unregister_application(app);
    return res;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Extension Directory" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, } static
Definition at line 992 of file app_directory.c.
app
const char app[] = "Directory" static
Definition at line 139 of file app_directory.c.
Referenced by load_module(), and unload_module().
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 992 of file app_directory.c.
commonbuf
struct ast_threadstorage commonbuf = { .once = PTHREAD_ONCE_INIT , .key_init = __init_commonbuf , .custom_init = NULL , } static
Definition at line 459 of file app_directory.c.
directory_app_options
const struct ast_app_option directory_app_options[128] = { [ 'f' ] = { .flag = OPT_LISTBYFIRSTNAME , .arg_index = OPT_ARG_FIRSTNAME + 1 }, [ 'l' ] = { .flag = OPT_LISTBYLASTNAME , .arg_index = OPT_ARG_LASTNAME + 1 }, [ 'b' ] = { .flag = OPT_LISTBYEITHER , .arg_index = OPT_ARG_EITHER + 1 }, [ 'p' ] = { .flag = OPT_PAUSE , .arg_index = OPT_ARG_PAUSE + 1 }, [ 'e' ] = { .flag = OPT_SAYEXTENSION }, [ 'v' ] = { .flag = OPT_FROMVOICEMAIL }, [ 'm' ] = { .flag = OPT_SELECTFROMMENU }, [ 'n' ] = { .flag = OPT_NOANSWER }, [ 'a' ] = { .flag = OPT_ALIAS }, } static
Definition at line 186 of file app_directory.c.
Referenced by directory_exec().