Asterisk - The Open Source Telephony Project: dns_system_resolver.c File Reference
dns_system_resolver.c File Reference
The default DNS resolver for Asterisk.
#include "asterisk.h"
#include "asterisk/_private.h"
#include "asterisk/astobj2.h"
#include "asterisk/dns.h"
#include "asterisk/dns_core.h"
#include "asterisk/dns_resolver.h"
#include "asterisk/linkedlists.h"
#include "asterisk/taskprocessor.h"
#include "asterisk/utils.h"
Macros
#define DNS_SYSTEM_RESOLVER_FAILURE -1
Resolver return code upon failure.
#define DNS_SYSTEM_RESOLVER_PRIORITY INT_MAX
The consideration priority for this resolver implementation.
#define DNS_SYSTEM_RESOLVER_SUCCESS 0
Resolver return code upon success.
Functions
int ast_dns_system_resolver_init (void)
Initializes the resolver.
static int dns_system_resolver_add_record (void *context, unsigned char *record, int record_len, int ttl)
Callback to handle processing resource records.
static int dns_system_resolver_cancel (struct ast_dns_query *query)
Cancels processing resolution for a given query.
static void dns_system_resolver_destroy (void)
Destructor.
static int dns_system_resolver_process_query (void *data)
Callback to handle processing the query from the ast_taskprocessor instance.
static int dns_system_resolver_resolve (struct ast_dns_query *query)
Resolves a DNS query.
static int dns_system_resolver_set_response (void *context, unsigned char *dns_response, int dns_response_len, int rcode)
Callback to handle initializing the results field.
Variables
struct ast_dns_resolver dns_system_resolver_base
The base definition for the dns_system_resolver.
static struct ast_taskprocessor * dns_system_resolver_tp
The task processor to use for making DNS searches asynchronous.
Detailed Description
The default DNS resolver for Asterisk.
See also res_resolver_unbound
Author
Ashley Sanders asand.nosp@m.ers@.nosp@m.digiu.nosp@m.m.co.nosp@m.m
Definition in file dns_system_resolver.c.
Macro Definition Documentation
DNS_SYSTEM_RESOLVER_FAILURE
#define DNS_SYSTEM_RESOLVER_FAILURE -1
Resolver return code upon failure.
Definition at line 46 of file dns_system_resolver.c.
Referenced by ast_dns_system_resolver_init(), and dns_system_resolver_cancel().
DNS_SYSTEM_RESOLVER_PRIORITY
#define DNS_SYSTEM_RESOLVER_PRIORITY INT_MAX
The consideration priority for this resolver implementation.
Definition at line 40 of file dns_system_resolver.c.
DNS_SYSTEM_RESOLVER_SUCCESS
#define DNS_SYSTEM_RESOLVER_SUCCESS 0
Resolver return code upon success.
Definition at line 43 of file dns_system_resolver.c.
Referenced by ast_dns_system_resolver_init(), and dns_system_resolver_set_response().
Function Documentation
ast_dns_system_resolver_init()
int ast_dns_system_resolver_init (void)
Initializes the resolver.
Return values
0 on success
-1 on failure
Definition at line 243 of file dns_system_resolver.c.
References ast_dns_resolver_register(), ast_register_cleanup(), ast_taskprocessor_get(), dns_system_resolver_destroy(), DNS_SYSTEM_RESOLVER_FAILURE, DNS_SYSTEM_RESOLVER_SUCCESS, and TPS_REF_DEFAULT.
Referenced by asterisk_daemon().
 {
    /* Register the base resolver */
    int res = ast_dns_resolver_register(&dns_system_resolver_base);
    if (res) {
       return DNS_SYSTEM_RESOLVER_FAILURE;
    }
    /* Instantiate the task processor */
    dns_system_resolver_tp = ast_taskprocessor_get("dns_system_resolver_tp",
                                                    TPS_REF_DEFAULT);
    /* Return error if the task processor failed to instantiate */
    if (!dns_system_resolver_tp) {
       return DNS_SYSTEM_RESOLVER_FAILURE;
    }
    /* Register the cleanup function */
    ast_register_cleanup(dns_system_resolver_destroy);
    return DNS_SYSTEM_RESOLVER_SUCCESS;
 }
dns_system_resolver_add_record()
static int dns_system_resolver_add_record (void * context, unsigned char * record, int record_len, int ttl) static
Callback to handle processing resource records.
Adds an individual resource record discovered with ast_search_dns_ex to the ast_dns_query currently being resolved.
Definition at line 84 of file dns_system_resolver.c.
References ast_dns_query_get_rr_class(), ast_dns_query_get_rr_type(), ast_dns_resolver_add_record(), and context.
Referenced by dns_system_resolver_process_query().
 {
    struct ast_dns_query *query = context;
    /* Add the record to the query.*/
    return ast_dns_resolver_add_record(query,
                                       ast_dns_query_get_rr_type(query),
                                       ast_dns_query_get_rr_class(query),
                                       ttl,
                                       (const char*) record,
                                       record_len);
 }
dns_system_resolver_cancel()
static int dns_system_resolver_cancel (struct ast_dns_query * query) static
Cancels processing resolution for a given query.
Note
The system API calls block so there is no way to cancel them. Therefore, this function always returns failure when invoked.
Definition at line 110 of file dns_system_resolver.c.
References DNS_SYSTEM_RESOLVER_FAILURE.
 {
    return DNS_SYSTEM_RESOLVER_FAILURE;
 }
dns_system_resolver_destroy()
static void dns_system_resolver_destroy (void) static
Destructor.
Definition at line 120 of file dns_system_resolver.c.
References ast_dns_resolver_unregister(), and ast_taskprocessor_unreference().
Referenced by ast_dns_system_resolver_init().
 {
    /* Unreference the task processor */
    dns_system_resolver_tp = ast_taskprocessor_unreference(dns_system_resolver_tp);
    /* Unregister the base resolver */
    ast_dns_resolver_unregister(&dns_system_resolver_base);
 }
dns_system_resolver_process_query()
static int dns_system_resolver_process_query (void * data) static
Callback to handle processing the query from the ast_taskprocessor instance.
Definition at line 140 of file dns_system_resolver.c.
References ao2_ref, ast_debug, ast_dns_query_get_name(), ast_dns_query_get_rr_class(), ast_dns_query_get_rr_type(), ast_dns_resolver_completed(), AST_DNS_SEARCH_FAILURE, AST_DNS_SEARCH_NO_RECORDS, ast_search_dns_ex(), dns_system_resolver_add_record(), and dns_system_resolver_set_response().
Referenced by dns_system_resolver_resolve().
 {
    struct ast_dns_query *query = data;
    /* Perform the DNS search */
    enum ast_dns_search_result res = ast_search_dns_ex(query,
                                                       ast_dns_query_get_name(query),
                                                       ast_dns_query_get_rr_class(query),
                                                       ast_dns_query_get_rr_type(query),
                                                       dns_system_resolver_set_response,
                                                       dns_system_resolver_add_record);
    /* Handle the possible return values from the DNS search */
    if (res == AST_DNS_SEARCH_FAILURE) {
       ast_debug(1, "DNS search failed for query: '%s'\n",
               ast_dns_query_get_name(query));
    } else if (res == AST_DNS_SEARCH_NO_RECORDS) {
       ast_debug(1, "DNS search failed to yield any results for query: '%s'\n",
               ast_dns_query_get_name(query));
    }
    /* Mark the query as complete */
    ast_dns_resolver_completed(query);
    /* Reduce the reference count on the query object */
    ao2_ref(query, -1);
    return res;
 }
dns_system_resolver_resolve()
static int dns_system_resolver_resolve (struct ast_dns_query * query) static
Resolves a DNS query.
Definition at line 180 of file dns_system_resolver.c.
References ao2_bump, ao2_ref, ast_dns_query_get_name(), ast_log, ast_taskprocessor_push(), dns_system_resolver_process_query(), and LOG_ERROR.
 {
    /* Add query processing handler to the task processor */
    int res = ast_taskprocessor_push(dns_system_resolver_tp,
                                     dns_system_resolver_process_query,
                                     ao2_bump(query));
    /* The query processing handler was not added to the task processor */
    if (res < 0) {
       ast_log(LOG_ERROR, "Failed to perform async DNS resolution of '%s'\n",
               ast_dns_query_get_name(query));
       ao2_ref(query, -1);
    }
    /* Return the result of adding the query processing handler to the task processor */
    return res;
 }
dns_system_resolver_set_response()
static int dns_system_resolver_set_response (void * context, unsigned char * dns_response, int dns_response_len, int rcode) static
Callback to handle initializing the results field.
Definition at line 210 of file dns_system_resolver.c.
References ast_dns_query_get_name(), ast_dns_query_get_result(), ast_dns_resolver_set_result(), ast_log, context, DNS_SYSTEM_RESOLVER_SUCCESS, and LOG_ERROR.
Referenced by dns_system_resolver_process_query().
 {
    struct ast_dns_query *query = context;
    int res;
    /* Instantiate the query's result field (if necessary). */
    if (!ast_dns_query_get_result(query)) {
       res = ast_dns_resolver_set_result(query,
                                         0,
                                         0,
                                         rcode,
                                         ast_dns_query_get_name(query),
                                         (const char*) dns_response,
                                         dns_response_len);
       if (res) {
          /* There was a problem instantiating the results field. */
          ast_log(LOG_ERROR, "Could not instantiate the results field for query: '%s'\n",
                  ast_dns_query_get_name(query));
       }
    } else {
       res = DNS_SYSTEM_RESOLVER_SUCCESS;
    }
    return res;
 }
Variable Documentation
dns_system_resolver_base
struct ast_dns_resolver dns_system_resolver_base
The base definition for the dns_system_resolver.
Definition at line 61 of file dns_system_resolver.c.
dns_system_resolver_tp
struct ast_taskprocessor* dns_system_resolver_tp static
The task processor to use for making DNS searches asynchronous.
Definition at line 58 of file dns_system_resolver.c.