Asterisk - The Open Source Telephony Project: ast_sorcery_observer Struct Reference
ast_sorcery_observer Struct Reference
Interface for a sorcery object type observer.
#include <sorcery.h>
Data Fields
void(* created)(const void *object)
Callback for when an object is created.
void(* deleted)(const void *object)
Callback for when an object is deleted.
void(* loaded)(const char *object_type)
Callback for when an object type is loaded/reloaded.
void(* updated)(const void *object)
Callback for when an object is updated.
Detailed Description
Interface for a sorcery object type observer.
Definition at line 332 of file sorcery.h.
Field Documentation
created
void(* created) (const void *object)
Callback for when an object is created.
Definition at line 334 of file sorcery.h.
Referenced by sorcery_observer_notify_create().
deleted
void(* deleted) (const void *object)
Callback for when an object is deleted.
Definition at line 340 of file sorcery.h.
Referenced by sorcery_observer_notify_delete().
loaded
void(* loaded) (const char *object_type)
Callback for when an object type is loaded/reloaded.
Definition at line 343 of file sorcery.h.
Referenced by sorcery_observer_notify_loaded().
updated
void(* updated) (const void *object)
Callback for when an object is updated.
Definition at line 337 of file sorcery.h.
Referenced by sorcery_observer_notify_update().
The documentation for this struct was generated from the following file:
sorcery.h