Asterisk - The Open Source Telephony Project: func_callcompletion.c File Reference
func_callcompletion.c File Reference
Call Completion Supplementary Services implementation.
#include "asterisk.h"
#include "asterisk/module.h"
#include "asterisk/channel.h"
#include "asterisk/ccss.h"
#include "asterisk/pbx.h"
Functions
static void __reg_module (void)
static void __unreg_module (void)
static int acf_cc_read (struct ast_channel *chan, const char *name, char *data, char *buf, size_t buf_len)
static int acf_cc_write (struct ast_channel *chan, const char *cmd, char *data, const char *value)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int load_module (void)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_DEFAULT , .description = "Call Control Configuration Function" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .requires = "ccss", }
static const struct ast_module_info * ast_module_info = &__mod_info
static struct ast_custom_function cc_function
Detailed Description
Call Completion Supplementary Services implementation.
Author
Mark Michelson mmich.nosp@m.elso.nosp@m.n@dig.nosp@m.ium..nosp@m.com
Definition in file func_callcompletion.c.
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 134 of file func_callcompletion.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 134 of file func_callcompletion.c.
acf_cc_read()
static int acf_cc_read (struct ast_channel * chan, const char * name, char * data, char * buf, size_t buf_len) static
Definition at line 69 of file func_callcompletion.c.
References ast_cc_get_param(), ast_channel_get_cc_config_params(), ast_channel_lock, ast_channel_unlock, ast_log, and LOG_WARNING.
 {
    struct ast_cc_config_params *cc_params;
    int res;
    if (!chan) {
       ast_log(LOG_WARNING, "No channel was provided to %s function.\n", name);
       return -1;
    }
    ast_channel_lock(chan);
    if (!(cc_params = ast_channel_get_cc_config_params(chan))) {
       ast_channel_unlock(chan);
       return -1;
    }
    res = ast_cc_get_param(cc_params, data, buf, buf_len);
    ast_channel_unlock(chan);
    return res;
 }
acf_cc_write()
static int acf_cc_write (struct ast_channel * chan, const char * cmd, char * data, const char * value) static
Definition at line 91 of file func_callcompletion.c.
References ast_cc_set_param(), ast_channel_get_cc_config_params(), ast_channel_lock, ast_channel_unlock, ast_log, and LOG_WARNING.
 {
    struct ast_cc_config_params *cc_params;
    int res;
    if (!chan) {
       ast_log(LOG_WARNING, "No channel was provided to %s function.\n", cmd);
       return -1;
    }
    ast_channel_lock(chan);
    if (!(cc_params = ast_channel_get_cc_config_params(chan))) {
       ast_channel_unlock(chan);
       return -1;
    }
    res = ast_cc_set_param(cc_params, data, value);
    ast_channel_unlock(chan);
    return res;
 }
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 134 of file func_callcompletion.c.
load_module()
static int load_module (void) static
Definition at line 124 of file func_callcompletion.c.
References ast_custom_function_register, AST_MODFLAG_DEFAULT, AST_MODULE_INFO(), AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, AST_MODULE_SUPPORT_CORE, ASTERISK_GPL_KEY, and unload_module().
 {
    return ast_custom_function_register(&cc_function) == 0 ? AST_MODULE_LOAD_SUCCESS : AST_MODULE_LOAD_DECLINE;
 }
unload_module()
static int unload_module (void) static
Definition at line 119 of file func_callcompletion.c.
References ast_custom_function_unregister().
Referenced by load_module().
 {
    return ast_custom_function_unregister(&cc_function);
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_DEFAULT , .description = "Call Control Configuration Function" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .requires = "ccss", } static
Definition at line 134 of file func_callcompletion.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 134 of file func_callcompletion.c.
cc_function
struct ast_custom_function cc_function static
Initial value:
= {
   .name = "CALLCOMPLETION",
   .read = acf_cc_read,
   .write = acf_cc_write,
}
Definition at line 113 of file func_callcompletion.c.