Asterisk - The Open Source Telephony Project: bt_seq.c File Reference
bt_seq.c File Reference
#include <sys/types.h>
#include <errno.h>
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include "../include/db.h"
#include "btree.h"
Functions
static int __bt_first (BTREE *t, const DBT *key, EPG *erval, int *exactp)
int __bt_seq (DB *dbp, DBT *key, DBT *data, u_int flags) const
static int __bt_seqadv (BTREE *t, EPG *ep, int flags)
static int __bt_seqset (BTREE *t, EPG *ep, DBT *key, int flags)
void __bt_setcur (BTREE *t, pgno_t pgno, u_int index)
static int __bt_first __P ((BTREE *, const DBT *, EPG *, int *))
static int __bt_seqadv __P ((BTREE *, EPG *, int))
static int __bt_seqset __P ((BTREE *, EPG *, DBT *, int))
Function Documentation
__bt_first()
static int __bt_first (BTREE * t, const DBT * key, EPG * erval, int * exactp) static
Definition at line 342 of file bt_seq.c.
References __bt_cmp(), __bt_search(), B_NODUPS, _btree::bt_mp, F_ISSET, _epg::index, mpool_get(), mpool_put(), NEXTINDEX, _page::nextpg, NULL, P_INVALID, _epg::page, _page::pgno, _page::prevpg, RET_ERROR, RET_SPECIAL, and RET_SUCCESS.
Referenced by __bt_seqadv(), and __bt_seqset().
 {
    PAGE *h;
    EPG *ep, save;
    pgno_t pg;
    /*
     * Find any matching record; __bt_search pins the page.
     *
     * If it's an exact match and duplicates are possible, walk backwards
     * in the tree until we find the first one.  Otherwise, make sure it's
     * a valid key (__bt_search may return an index just past the end of a
     * page) and return it.
     */
    if ((ep = __bt_search(t, key, exactp)) == NULL)
       return (RET_SPECIAL);
    if (*exactp) {
       if (F_ISSET(t, B_NODUPS)) {
          *erval = *ep;
          return (RET_SUCCESS);
       }
       /*
        * Walk backwards, as long as the entry matches and there are
        * keys left in the tree.  Save a copy of each match in case
        * we go too far.
        */
       save = *ep;
       h = ep->page;
       do {
          if (save.page->pgno != ep->page->pgno) {
             mpool_put(t->bt_mp, save.page, 0);
             save = *ep;
          } else
             save.index = ep->index;
          /*
           * Don't unpin the page the last (or original) match
           * was on, but make sure it's unpinned if an error
           * occurs.
           */
          if (ep->index == 0) {
             if (h->prevpg == P_INVALID)
                break;
             if (h->pgno != save.page->pgno)
                mpool_put(t->bt_mp, h, 0);
             if ((h = mpool_get(t->bt_mp,
                 h->prevpg, 0)) == NULL) {
                if (h->pgno == save.page->pgno)
                   mpool_put(t->bt_mp,
                       save.page, 0);
                return (RET_ERROR);
             }
             ep->page = h;
             ep->index = NEXTINDEX(h);
          }
          --ep->index;
       } while (__bt_cmp(t, key, ep) == 0);
       /*
        * Reach here with the last page that was looked at pinned,
        * which may or may not be the same as the last (or original)
        * match page.  If it's not useful, release it.
        */
       if (h->pgno != save.page->pgno)
          mpool_put(t->bt_mp, h, 0);
       *erval = save;
       return (RET_SUCCESS);
    }
    /* If at the end of a page, find the next entry. */
    if (ep->index == NEXTINDEX(ep->page)) {
       h = ep->page;
       pg = h->nextpg;
       mpool_put(t->bt_mp, h, 0);
       if (pg == P_INVALID)
          return (RET_SPECIAL);
       if ((h = mpool_get(t->bt_mp, pg, 0)) == NULL)
          return (RET_ERROR);
       ep->index = 0;
       ep->page = h;
    }
    *erval = *ep;
    return (RET_SUCCESS);
 }
__bt_seq()
int __bt_seq (DB * dbp, DBT * key, DBT * data, u_int flags) const
Definition at line 77 of file bt_seq.c.
References __bt_ret(), __bt_seqadv(), __bt_seqset(), __bt_setcur(), B_DB_LOCK, _btree::bt_cursor, _btree::bt_mp, _btree::bt_pinned, _btree::bt_rdata, _btree::bt_rkey, CURS_INIT, errno, F_ISSET, _epg::index, __db::internal, mpool_put(), NULL, _epg::page, _page::pgno, R_CURSOR, R_FIRST, R_LAST, R_NEXT, R_PREV, RET_ERROR, RET_SUCCESS, and status.
Referenced by __bt_open().
 {
    BTREE *t;
    EPG e;
    int status;
    t = dbp->internal;
    /* Toss any page pinned across calls. */
    if (t->bt_pinned != NULL) {
       mpool_put(t->bt_mp, t->bt_pinned, 0);
       t->bt_pinned = NULL;
    }
    /*
     * If scan uninitialized as yet, or starting at a specific record, set
     * the scan to a specific key.  Both __bt_seqset and __bt_seqadv pin
     * the page the cursor references if they're successful.
     */
    switch (flags) {
    case R_NEXT:
    case R_PREV:
       if (F_ISSET(&t->bt_cursor, CURS_INIT)) {
          status = __bt_seqadv(t, &e, flags);
          break;
       }
       /* FALLTHROUGH */
    case R_FIRST:
    case R_LAST:
    case R_CURSOR:
       status = __bt_seqset(t, &e, key, flags);
       break;
    default:
       errno = EINVAL;
       return (RET_ERROR);
    }
    if (status == RET_SUCCESS) {
       __bt_setcur(t, e.page->pgno, e.index);
       status =
           __bt_ret(t, &e, key, &t->bt_rkey, data, &t->bt_rdata, 0);
       /*
        * If the user is doing concurrent access, we copied the
        * key/data, toss the page.
        */
       if (F_ISSET(t, B_DB_LOCK))
          mpool_put(t->bt_mp, e.page, 0);
       else
          t->bt_pinned = e.page;
    }
    return (status);
 }
__bt_seqadv()
static int __bt_seqadv (BTREE * t, EPG * ep, int flags) static
Definition at line 240 of file bt_seq.c.
References __bt_first(), _btree::bt_cursor, _btree::bt_mp, c, CURS_ACQUIRE, CURS_AFTER, CURS_BEFORE, F_CLR, F_ISSET, _epgno::index, _epg::index, _cursor::key, mpool_get(), mpool_put(), NEXTINDEX, _page::nextpg, NULL, P_INVALID, _epg::page, _cursor::pg, _epgno::pgno, _page::prevpg, R_NEXT, R_PREV, RET_ERROR, RET_SPECIAL, and RET_SUCCESS.
Referenced by __bt_seq().
 {
    CURSOR *c;
    PAGE *h;
    indx_t index = 0;
    pgno_t pg;
    int exact;
    /*
     * There are a couple of states that we can be in.  The cursor has
     * been initialized by the time we get here, but that's all we know.
     */
    c = &t->bt_cursor;
    /*
     * The cursor was deleted where there weren't any duplicate records,
     * so the key was saved.  Find out where that key would go in the
     * current tree.  It doesn't matter if the returned key is an exact
     * match or not -- if it's an exact match, the record was added after
     * the delete so we can just return it.  If not, as long as there's
     * a record there, return it.
     */
    if (F_ISSET(c, CURS_ACQUIRE))
       return (__bt_first(t, &c->key, ep, &exact));
    /* Get the page referenced by the cursor. */
    if ((h = mpool_get(t->bt_mp, c->pg.pgno, 0)) == NULL)
       return (RET_ERROR);
    /*
     * Find the next/previous record in the tree and point the cursor at
     * it.  The cursor may not be moved until a new key has been found.
     */
    switch (flags) {
    case R_NEXT:         /* Next record. */
       /*
        * The cursor was deleted in duplicate records, and moved
        * forward to a record that has yet to be returned.  Clear
        * that flag, and return the record.
        */
       if (F_ISSET(c, CURS_AFTER))
          goto usecurrent;
       index = c->pg.index;
       if (++index == NEXTINDEX(h)) {
          pg = h->nextpg;
          mpool_put(t->bt_mp, h, 0);
          if (pg == P_INVALID)
             return (RET_SPECIAL);
          if ((h = mpool_get(t->bt_mp, pg, 0)) == NULL)
             return (RET_ERROR);
          index = 0;
       }
       break;
    case R_PREV:         /* Previous record. */
       /*
        * The cursor was deleted in duplicate records, and moved
        * backward to a record that has yet to be returned.  Clear
        * that flag, and return the record.
        */
       if (F_ISSET(c, CURS_BEFORE)) {
 usecurrent:    F_CLR(c, CURS_AFTER | CURS_BEFORE);
          ep->page = h;
          ep->index = c->pg.index;
          return (RET_SUCCESS);
       }
       index = c->pg.index;
       if (index == 0) {
          pg = h->prevpg;
          mpool_put(t->bt_mp, h, 0);
          if (pg == P_INVALID)
             return (RET_SPECIAL);
          if ((h = mpool_get(t->bt_mp, pg, 0)) == NULL)
             return (RET_ERROR);
          index = NEXTINDEX(h) - 1;
       } else
          --index;
       break;
    }
    ep->page = h;
    ep->index = index;
    return (RET_SUCCESS);
 }
__bt_seqset()
static int __bt_seqset (BTREE * t, EPG * ep, DBT * key, int flags) static
Definition at line 152 of file bt_seq.c.
References __bt_first(), _btree::bt_mp, DBT::data, errno, _page::flags, GETBINTERNAL, _epg::index, mpool_get(), mpool_put(), NEXTINDEX, NULL, P_BLEAF, P_RLEAF, P_ROOT, _epg::page, R_CURSOR, R_FIRST, R_LAST, R_NEXT, R_PREV, RET_ERROR, RET_SPECIAL, RET_SUCCESS, and DBT::size.
Referenced by __bt_seq().
 {
    PAGE *h;
    pgno_t pg;
    int exact;
    /*
     * Find the first, last or specific key in the tree and point the
     * cursor at it.  The cursor may not be moved until a new key has
     * been found.
     */
    switch (flags) {
    case R_CURSOR:          /* Keyed scan. */
       /*
        * Find the first instance of the key or the smallest key
        * which is greater than or equal to the specified key.
        */
       if (key->data == NULL || key->size == 0) {
          errno = EINVAL;
          return (RET_ERROR);
       }
       return (__bt_first(t, key, ep, &exact));
    case R_FIRST:           /* First record. */
    case R_NEXT:
       /* Walk down the left-hand side of the tree. */
       for (pg = P_ROOT;;) {
          if ((h = mpool_get(t->bt_mp, pg, 0)) == NULL)
             return (RET_ERROR);
          /* Check for an empty tree. */
          if (NEXTINDEX(h) == 0) {
             mpool_put(t->bt_mp, h, 0);
             return (RET_SPECIAL);
          }
          if (h->flags & (P_BLEAF | P_RLEAF))
             break;
          pg = GETBINTERNAL(h, 0)->pgno;
          mpool_put(t->bt_mp, h, 0);
       }
       ep->page = h;
       ep->index = 0;
       break;
    case R_LAST:            /* Last record. */
    case R_PREV:
       /* Walk down the right-hand side of the tree. */
       for (pg = P_ROOT;;) {
          if ((h = mpool_get(t->bt_mp, pg, 0)) == NULL)
             return (RET_ERROR);
          /* Check for an empty tree. */
          if (NEXTINDEX(h) == 0) {
             mpool_put(t->bt_mp, h, 0);
             return (RET_SPECIAL);
          }
          if (h->flags & (P_BLEAF | P_RLEAF))
             break;
          pg = GETBINTERNAL(h, NEXTINDEX(h) - 1)->pgno;
          mpool_put(t->bt_mp, h, 0);
       }
       ep->page = h;
       ep->index = NEXTINDEX(h) - 1;
       break;
    }
    return (RET_SUCCESS);
 }
__bt_setcur()
void __bt_setcur (BTREE * t, pgno_t pgno, u_int index)
Definition at line 443 of file bt_seq.c.
References _btree::bt_cursor, CURS_ACQUIRE, CURS_AFTER, CURS_BEFORE, CURS_INIT, DBT::data, F_CLR, F_SET, free(), _epgno::index, _cursor::key, NULL, _cursor::pg, _epgno::pgno, and DBT::size.
Referenced by __bt_put(), and __bt_seq().
 {
    /* Lose any already deleted key. */
    if (t->bt_cursor.key.data != NULL) {
       free(t->bt_cursor.key.data);
       t->bt_cursor.key.size = 0;
       t->bt_cursor.key.data = NULL;
    }
    F_CLR(&t->bt_cursor, CURS_ACQUIRE | CURS_AFTER | CURS_BEFORE);
    /* Update the cursor. */
    t->bt_cursor.pg.pgno = pgno;
    t->bt_cursor.pg.index = index;
    F_SET(&t->bt_cursor, CURS_INIT);
 }
__P() [1/3]
static int __bt_first __P ((BTREE *, const DBT *, EPG *, int *)) static
__P() [2/3]
static int __bt_seqadv __P ((BTREE *, EPG *, int)) static
__P() [3/3]
static int __bt_seqset __P ((BTREE *, EPG *, DBT *, int)) static