Asterisk - The Open Source Telephony Project: res_sorcery_realtime.c File Reference
res_sorcery_realtime.c File Reference
Sorcery Realtime Object Wizard.
#include "asterisk.h"
#include <regex.h>
#include "asterisk/module.h"
#include "asterisk/sorcery.h"
Data Structures
struct sorcery_config
Structure for storing configuration file sourced objects.
Macros
#define UUID_FIELD "id"
They key field used to store the unique identifier for the object.
Enumerations
enum unqualified_fetch { UNQUALIFIED_FETCH_NO, UNQUALIFIED_FETCH_WARN, UNQUALIFIED_FETCH_YES, UNQUALIFIED_FETCH_ERROR }
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int load_module (void)
static void sorcery_realtime_close (void *data)
static int sorcery_realtime_create (const struct ast_sorcery *sorcery, void *data, void *object)
static int sorcery_realtime_delete (const struct ast_sorcery *sorcery, void *data, void *object)
static struct ast_variable * sorcery_realtime_filter_objectset (struct ast_variable *objectset, struct ast_variable **id, const struct ast_sorcery *sorcery, const char *type)
Internal helper function which returns a filtered objectset.
static void * sorcery_realtime_open (const char *data)
static void * sorcery_realtime_retrieve_fields (const struct ast_sorcery *sorcery, void *data, const char *type, const struct ast_variable *fields)
static void * sorcery_realtime_retrieve_id (const struct ast_sorcery *sorcery, void *data, const char *type, const char *id)
static void sorcery_realtime_retrieve_multiple (const struct ast_sorcery *sorcery, void *data, const char *type, struct ao2_container *objects, const struct ast_variable *fields)
static void sorcery_realtime_retrieve_prefix (const struct ast_sorcery *sorcery, void *data, const char *type, struct ao2_container *objects, const char *prefix, const size_t prefix_len)
static void sorcery_realtime_retrieve_regex (const struct ast_sorcery *sorcery, void *data, const char *type, struct ao2_container *objects, const char *regex)
static int sorcery_realtime_update (const struct ast_sorcery *sorcery, void *data, void *object)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_GLOBAL_SYMBOLS | AST_MODFLAG_LOAD_ORDER , .description = "Sorcery Realtime Object Wizard" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_REALTIME_DRIVER, }
static const struct ast_module_info * ast_module_info = &__mod_info
static struct ast_sorcery_wizard realtime_object_wizard
Detailed Description
Sorcery Realtime Object Wizard.
Author
Joshua Colp jcolp.nosp@m.@dig.nosp@m.ium.c.nosp@m.om
Definition in file res_sorcery_realtime.c.
Macro Definition Documentation
UUID_FIELD
#define UUID_FIELD "id"
They key field used to store the unique identifier for the object.
Definition at line 39 of file res_sorcery_realtime.c.
Referenced by sorcery_realtime_create(), sorcery_realtime_delete(), sorcery_realtime_filter_objectset(), sorcery_realtime_retrieve_id(), sorcery_realtime_retrieve_multiple(), sorcery_realtime_retrieve_prefix(), sorcery_realtime_retrieve_regex(), and sorcery_realtime_update().
Enumeration Type Documentation
unqualified_fetch
enum unqualified_fetch
Enumerator
UNQUALIFIED_FETCH_NO
UNQUALIFIED_FETCH_WARN
UNQUALIFIED_FETCH_YES
UNQUALIFIED_FETCH_ERROR
Definition at line 41 of file res_sorcery_realtime.c.
{
    UNQUALIFIED_FETCH_NO,
    UNQUALIFIED_FETCH_WARN,
    UNQUALIFIED_FETCH_YES,
    UNQUALIFIED_FETCH_ERROR,
 };
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 382 of file res_sorcery_realtime.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 382 of file res_sorcery_realtime.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 382 of file res_sorcery_realtime.c.
load_module()
static int load_module (void) static
Definition at line 362 of file res_sorcery_realtime.c.
References AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, and ast_sorcery_wizard_register.
Referenced by unload_module().
 {
    if (ast_sorcery_wizard_register(&realtime_object_wizard)) {
       return AST_MODULE_LOAD_DECLINE;
    }
    return AST_MODULE_LOAD_SUCCESS;
 }
sorcery_realtime_close()
static void sorcery_realtime_close (void * data) static
Definition at line 357 of file res_sorcery_realtime.c.
References ast_free.
 {
    ast_free(data);
 }
sorcery_realtime_create()
static int sorcery_realtime_create (const struct ast_sorcery * sorcery, void * data, void * object) static
Definition at line 80 of file res_sorcery_realtime.c.
References ast_sorcery_object_get_id(), ast_sorcery_objectset_create, ast_store_realtime_fields(), ast_variable_new, ast_variables_destroy(), config, sorcery_config::family, id, RAII_VAR, and UUID_FIELD.
 {
    struct sorcery_config *config = data;
    RAII_VAR(struct ast_variable *, fields, ast_sorcery_objectset_create(sorcery, object), ast_variables_destroy);
    struct ast_variable *id = ast_variable_new(UUID_FIELD, ast_sorcery_object_get_id(object), "");
    if (!fields || !id) {
       ast_variables_destroy(id);
       return -1;
    }
    /* Place the identifier at the front for sanity sake */
    id->next = fields;
    fields = id;
    return (ast_store_realtime_fields(config->family, fields) <= 0) ? -1 : 0;
 }
sorcery_realtime_delete()
static int sorcery_realtime_delete (const struct ast_sorcery * sorcery, void * data, void * object) static
Definition at line 297 of file res_sorcery_realtime.c.
References ast_destroy_realtime_fields(), ast_sorcery_object_get_id(), config, sorcery_config::family, NULL, and UUID_FIELD.
 {
    struct sorcery_config *config = data;
    return (ast_destroy_realtime_fields(config->family, UUID_FIELD, ast_sorcery_object_get_id(object), NULL) <= 0) ? -1 : 0;
 }
sorcery_realtime_filter_objectset()
static struct ast_variable* sorcery_realtime_filter_objectset (struct ast_variable * objectset, struct ast_variable ** id, const struct ast_sorcery * sorcery, const char * type) static
Internal helper function which returns a filtered objectset.
The following are filtered out of the objectset:
The id field. This is returned to the caller in an out parameter.
Fields that are not registered with sorcery.
Parameters
objectset Objectset to filter.
[out] id The ID of the sorcery object, as found in the objectset.
sorcery The sorcery instance that is requesting an objectset.
type The object type
Returns
The filtered objectset
Definition at line 111 of file res_sorcery_realtime.c.
References ao2_cleanup, ast_debug, ast_log, ast_sorcery_get_object_type(), ast_sorcery_is_object_field_registered(), ast_variables_destroy(), LOG_WARNING, ast_sorcery_object_type::name, ast_variable::next, NULL, and UUID_FIELD.
Referenced by sorcery_realtime_retrieve_fields(), and sorcery_realtime_retrieve_multiple().
 {
    struct ast_variable *previous = NULL, *field = objectset;
    struct ast_sorcery_object_type *object_type;
    object_type = ast_sorcery_get_object_type(sorcery, type);
    if (!object_type) {
       ast_log(LOG_WARNING, "Unknown sorcery object type %s. Expect errors\n", type);
       /* Continue since we still want to filter out the id */
    }
    while (field) {
       int remove_field = 0;
       int delete_field = 0;
       if (!strcmp(field->name, UUID_FIELD)) {
          *id = field;
          remove_field = 1;
       } else if (object_type &&
             !ast_sorcery_is_object_field_registered(object_type, field->name)) {
          ast_debug(1, "Filtering out realtime field '%s' from retrieval\n", field->name);
          remove_field = 1;
          delete_field = 1;
       }
       if (remove_field) {
          struct ast_variable *removed;
          if (previous) {
             previous->next = field->next;
          } else {
             objectset = field->next;
          }
          removed = field;
          field = field->next;
          removed->next = NULL;
          if (delete_field) {
             ast_variables_destroy(removed);
          }
       } else {
          previous = field;
          field = field->next;
       }
    }
    ao2_cleanup(object_type);
    return objectset;
 }
sorcery_realtime_open()
static void * sorcery_realtime_open (const char * data) static
Definition at line 304 of file res_sorcery_realtime.c.
References ast_calloc, ast_log, ast_realtime_is_mapping_defined(), ast_strdupa, ast_strlen_zero, config, sorcery_config::family, sorcery_config::fetch, LOG_ERROR, name, NULL, strsep(), tmp(), UNQUALIFIED_FETCH_ERROR, UNQUALIFIED_FETCH_NO, UNQUALIFIED_FETCH_WARN, UNQUALIFIED_FETCH_YES, and value.
 {
    struct sorcery_config *config;
    char *tmp;
    char *family;
    char *option;
    /* We require a prefix for family string generation, or else stuff could mix together */
    if (ast_strlen_zero(data)) {
       return NULL;
    }
    tmp = ast_strdupa(data);
    family = strsep(&tmp, ",");
    if (!ast_realtime_is_mapping_defined(family)) {
       return NULL;
    }
    config = ast_calloc(1, sizeof(*config) + strlen(family) + 1);
    if (!config) {
       return NULL;
    }
    strcpy(config->family, family); /* Safe */
    config->fetch = UNQUALIFIED_FETCH_YES;
    while ((option = strsep(&tmp, ","))) {
       char *name = strsep(&option, "=");
       char *value = option;
       if (!strcasecmp(name, "allow_unqualified_fetch")) {
          if (ast_strlen_zero(value) || !strcasecmp(value, "yes")) {
             config->fetch = UNQUALIFIED_FETCH_YES;
          } else if (!strcasecmp(value, "no")) {
             config->fetch = UNQUALIFIED_FETCH_NO;
          } else if (!strcasecmp(value, "warn")) {
             config->fetch = UNQUALIFIED_FETCH_WARN;
          } else if (!strcasecmp(value, "error")) {
             config->fetch = UNQUALIFIED_FETCH_ERROR;
          } else {
             ast_log(LOG_ERROR, "Unrecognized value in %s:%s: '%s'\n", family, name, value);
             return NULL;
          }
       } else {
          ast_log(LOG_ERROR, "Unrecognized option in %s: '%s'\n", family, name);
          return NULL;
       }
    }
    return config;
 }
sorcery_realtime_retrieve_fields()
static void * sorcery_realtime_retrieve_fields (const struct ast_sorcery * sorcery, void * data, const char * type, const struct ast_variable * fields) static
Definition at line 163 of file res_sorcery_realtime.c.
References ao2_cleanup, ast_load_realtime_fields(), ast_sorcery_alloc(), ast_sorcery_objectset_apply(), ast_variables_destroy(), config, sorcery_config::family, id, NULL, RAII_VAR, and sorcery_realtime_filter_objectset().
Referenced by sorcery_realtime_retrieve_id().
 {
    struct sorcery_config *config = data;
    RAII_VAR(struct ast_variable *, objectset, NULL, ast_variables_destroy);
    RAII_VAR(struct ast_variable *, id, NULL, ast_variables_destroy);
    void *object = NULL;
    if (!(objectset = ast_load_realtime_fields(config->family, fields))) {
       return NULL;
    }
    objectset = sorcery_realtime_filter_objectset(objectset, &id, sorcery, type);
    if (!id
       || !(object = ast_sorcery_alloc(sorcery, type, id->value))
       || ast_sorcery_objectset_apply(sorcery, object, objectset)) {
       ao2_cleanup(object);
       return NULL;
    }
    return object;
 }
sorcery_realtime_retrieve_id()
static void * sorcery_realtime_retrieve_id (const struct ast_sorcery * sorcery, void * data, const char * type, const char * id) static
Definition at line 186 of file res_sorcery_realtime.c.
References ast_variable_new, ast_variables_destroy(), RAII_VAR, sorcery_realtime_retrieve_fields(), and UUID_FIELD.
 {
    RAII_VAR(struct ast_variable *, fields, ast_variable_new(UUID_FIELD, id, ""), ast_variables_destroy);
    return sorcery_realtime_retrieve_fields(sorcery, data, type, fields);
 }
sorcery_realtime_retrieve_multiple()
static void sorcery_realtime_retrieve_multiple (const struct ast_sorcery * sorcery, void * data, const char * type, struct ao2_container * objects, const struct ast_variable * fields) static
Definition at line 193 of file res_sorcery_realtime.c.
References ao2_cleanup, ao2_link, ast_category_browse_filtered(), ast_category_detach_variables(), ast_config_destroy(), ast_load_realtime_multientry_fields(), ast_log, ast_sorcery_alloc(), ast_sorcery_objectset_apply(), ast_variable_new, ast_variables_destroy(), config, sorcery_config::family, sorcery_config::fetch, id, LOG_ERROR, LOG_WARNING, NULL, RAII_VAR, sorcery_realtime_filter_objectset(), UNQUALIFIED_FETCH_ERROR, UNQUALIFIED_FETCH_NO, UNQUALIFIED_FETCH_WARN, UUID_FIELD, and value.
Referenced by sorcery_realtime_retrieve_prefix(), and sorcery_realtime_retrieve_regex().
 {
    struct sorcery_config *config = data;
    RAII_VAR(struct ast_config *, rows, NULL, ast_config_destroy);
    RAII_VAR(struct ast_variable *, all, NULL, ast_variables_destroy);
    struct ast_category *row = NULL;
    if (!fields) {
       char field[strlen(UUID_FIELD) + 6], value[2];
       if (config->fetch == UNQUALIFIED_FETCH_NO) {
          return;
       }
       if (config->fetch == UNQUALIFIED_FETCH_ERROR) {
          ast_log(LOG_ERROR, "Unqualified fetch prevented on %s\n", config->family);
          return;
       }
       if (config->fetch == UNQUALIFIED_FETCH_WARN) {
          ast_log(LOG_WARNING, "Unqualified fetch requested on %s\n", config->family);
       }
       /* If no fields have been specified we want all rows, so trick realtime into doing it */
       snprintf(field, sizeof(field), "%s LIKE", UUID_FIELD);
       snprintf(value, sizeof(value), "%%");
       if (!(all = ast_variable_new(field, value, ""))) {
          return;
       }
       fields = all;
    }
    if (!(rows = ast_load_realtime_multientry_fields(config->family, fields))) {
       return;
    }
    while ((row = ast_category_browse_filtered(rows, NULL, row, NULL))) {
       struct ast_variable *objectset = ast_category_detach_variables(row);
       RAII_VAR(struct ast_variable *, id, NULL, ast_variables_destroy);
       RAII_VAR(void *, object, NULL, ao2_cleanup);
       objectset = sorcery_realtime_filter_objectset(objectset, &id, sorcery, type);
       if (id
          && (object = ast_sorcery_alloc(sorcery, type, id->value))
          && !ast_sorcery_objectset_apply(sorcery, object, objectset)) {
          ao2_link(objects, object);
       }
       ast_variables_destroy(objectset);
    }
 }
sorcery_realtime_retrieve_prefix()
static void sorcery_realtime_retrieve_prefix (const struct ast_sorcery * sorcery, void * data, const char * type, struct ao2_container * objects, const char * prefix, const size_t prefix_len) static
Definition at line 268 of file res_sorcery_realtime.c.
References ast_variable_new, ast_variables_destroy(), NULL, RAII_VAR, sorcery_realtime_retrieve_multiple(), UUID_FIELD, and value.
 {
    char field[strlen(UUID_FIELD) + 6], value[prefix_len + 2];
    RAII_VAR(struct ast_variable *, fields, NULL, ast_variables_destroy);
    if (prefix_len) {
       snprintf(field, sizeof(field), "%s LIKE", UUID_FIELD);
       snprintf(value, sizeof(value), "%.*s%%", (int) prefix_len, prefix);
       if (!(fields = ast_variable_new(field, value, ""))) {
          return;
       }
    }
    sorcery_realtime_retrieve_multiple(sorcery, data, type, objects, fields);
 }
sorcery_realtime_retrieve_regex()
static void sorcery_realtime_retrieve_regex (const struct ast_sorcery * sorcery, void * data, const char * type, struct ao2_container * objects, const char * regex) static
Definition at line 246 of file res_sorcery_realtime.c.
References ast_strlen_zero, ast_variable_new, ast_variables_destroy(), NULL, RAII_VAR, sorcery_realtime_retrieve_multiple(), UUID_FIELD, and value.
 {
    char field[strlen(UUID_FIELD) + 6], value[strlen(regex) + 3];
    RAII_VAR(struct ast_variable *, fields, NULL, ast_variables_destroy);
    if (!ast_strlen_zero(regex)) {
       /* The realtime API provides no direct ability to do regex so for now we support a limited subset using pattern matching */
       snprintf(field, sizeof(field), "%s LIKE", UUID_FIELD);
       if (regex[0] == '^') {
          snprintf(value, sizeof(value), "%s%%", regex + 1);
       } else {
          snprintf(value, sizeof(value), "%%%s%%", regex);
       }
       if (!(fields = ast_variable_new(field, value, ""))) {
          return;
       }
    }
    sorcery_realtime_retrieve_multiple(sorcery, data, type, objects, fields);
 }
sorcery_realtime_update()
static int sorcery_realtime_update (const struct ast_sorcery * sorcery, void * data, void * object) static
Definition at line 285 of file res_sorcery_realtime.c.
References ast_sorcery_object_get_id(), ast_sorcery_objectset_create, ast_update_realtime_fields(), ast_variables_destroy(), config, sorcery_config::family, RAII_VAR, and UUID_FIELD.
 {
    struct sorcery_config *config = data;
    RAII_VAR(struct ast_variable *, fields, ast_sorcery_objectset_create(sorcery, object), ast_variables_destroy);
    if (!fields) {
       return -1;
    }
    return (ast_update_realtime_fields(config->family, UUID_FIELD, ast_sorcery_object_get_id(object), fields) < 0) ? -1 : 0;
 }
unload_module()
static int unload_module (void) static
Definition at line 371 of file res_sorcery_realtime.c.
References AST_MODFLAG_GLOBAL_SYMBOLS, AST_MODFLAG_LOAD_ORDER, AST_MODPRI_REALTIME_DRIVER, AST_MODULE_INFO(), AST_MODULE_SUPPORT_CORE, ast_sorcery_wizard_unregister(), ASTERISK_GPL_KEY, and load_module().
 {
    ast_sorcery_wizard_unregister(&realtime_object_wizard);
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_GLOBAL_SYMBOLS | AST_MODFLAG_LOAD_ORDER , .description = "Sorcery Realtime Object Wizard" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_REALTIME_DRIVER, } static
Definition at line 382 of file res_sorcery_realtime.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 382 of file res_sorcery_realtime.c.
realtime_object_wizard
struct ast_sorcery_wizard realtime_object_wizard static
Definition at line 66 of file res_sorcery_realtime.c.