Asterisk - The Open Source Telephony Project: func_version.c File Reference
func_version.c File Reference
Module: Dial plan functions
Return the current Version strings.
#include "asterisk.h"
#include "asterisk/module.h"
#include "asterisk/channel.h"
#include "asterisk/pbx.h"
#include "asterisk/utils.h"
#include "asterisk/app.h"
#include "asterisk/ast_version.h"
#include "asterisk/build.h"
Functions
static void __reg_module (void)
static void __unreg_module (void)
static int acf_version_exec (struct ast_channel *chan, const char *cmd, char *parse, char *buffer, size_t buflen)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int load_module (void)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Get Asterisk Version/Build Info" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, }
static struct ast_custom_function acf_version
static const struct ast_module_info * ast_module_info = &__mod_info
Detailed Description
Return the current Version strings.
Author
Steve Murphy (murf@.nosp@m.digi.nosp@m.um.co.nosp@m.m)
Definition in file func_version.c.
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 134 of file func_version.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 134 of file func_version.c.
acf_version_exec()
static int acf_version_exec (struct ast_channel * chan, const char * cmd, char * parse, char * buffer, size_t buflen) static
Definition at line 83 of file func_version.c.
References args, AST_APP_ARG, ast_copy_string(), ast_debug, AST_DECLARE_APP_ARGS, ast_get_version(), ast_get_version_num(), AST_STANDARD_APP_ARGS, ast_strlen_zero, BUILD_DATE, BUILD_HOSTNAME, BUILD_KERNEL, BUILD_MACHINE, BUILD_OS, BUILD_USER, and sip_to_pjsip::info().
 {
    const char *response_char = ast_get_version();
    AST_DECLARE_APP_ARGS(args,
       AST_APP_ARG(info);
    );
    AST_STANDARD_APP_ARGS(args, parse);
    if (!ast_strlen_zero(args.info) ) {
       if (!strcasecmp(args.info,"ASTERISK_VERSION_NUM"))
          response_char = ast_get_version_num();
       else if (!strcasecmp(args.info,"BUILD_USER"))
          response_char = BUILD_USER;
       else if (!strcasecmp(args.info,"BUILD_HOSTNAME"))
          response_char = BUILD_HOSTNAME;
       else if (!strcasecmp(args.info,"BUILD_MACHINE"))
          response_char = BUILD_MACHINE;
       else if (!strcasecmp(args.info,"BUILD_KERNEL"))
          response_char = BUILD_KERNEL;
       else if (!strcasecmp(args.info,"BUILD_OS"))
          response_char = BUILD_OS;
       else if (!strcasecmp(args.info,"BUILD_DATE"))
          response_char = BUILD_DATE;
    }
    ast_debug(1, "VERSION returns %s result, given %s argument\n", response_char, args.info);
    ast_copy_string(buffer, response_char, buflen);
    return 0;
 }
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 134 of file func_version.c.
load_module()
static int load_module (void) static
Definition at line 129 of file func_version.c.
References ast_custom_function_register.
 {
    return ast_custom_function_register(&acf_version);
 }
unload_module()
static int unload_module (void) static
Definition at line 122 of file func_version.c.
References ast_custom_function_unregister().
 {
    ast_custom_function_unregister(&acf_version);
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Get Asterisk Version/Build Info" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, } static
Definition at line 134 of file func_version.c.
acf_version
struct ast_custom_function acf_version static
Initial value:
= {
   .name = "VERSION",
   .read = acf_version_exec,
}
Definition at line 117 of file func_version.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 134 of file func_version.c.