Asterisk - The Open Source Telephony Project: bridge_features.h File Reference
bridge_features.h File Reference
Channel Bridging API.
#include "asterisk/channel.h"
Data Structures
struct ast_bridge_features
Structure that contains features information.
struct ast_bridge_features_attended_transfer
Structure that contains configuration information for the attended transfer built in feature.
struct ast_bridge_features_automixmonitor
struct ast_bridge_features_automonitor
struct ast_bridge_features_blind_transfer
Structure that contains configuration information for the blind transfer built in feature.
struct ast_bridge_features_limits
Structure that contains configuration information for the limits feature.
struct ast_bridge_hook
Structure that is the essence of a feature hook.
struct ast_bridge_hook_dtmf
struct ast_bridge_hook_dtmf_parms
struct ast_bridge_hook_timer
struct ast_bridge_hook_timer_parms
Macros
#define MAXIMUM_DTMF_FEATURE_STRING (11 + 1)
Maximum length of a DTMF feature string.
Typedefs
typedef int(* ast_bridge_builtin_set_limits_fn) (struct ast_bridge_features *features, struct ast_bridge_features_limits *limits, enum ast_bridge_hook_remove_flags remove_flags)
Attach interval hooks to a bridge features structure.
typedef int(* ast_bridge_hook_callback) (struct ast_bridge_channel *bridge_channel, void *hook_pvt)
Hook callback type.
typedef void(* ast_bridge_hook_pvt_destructor) (void *hook_pvt)
Hook pvt destructor callback.
typedef int(* ast_bridge_move_indicate_callback) (struct ast_bridge_channel *bridge_channel, void *hook_pvt, struct ast_bridge *src, struct ast_bridge *dst)
Move indicator callback.
typedef int(* ast_bridge_talking_indicate_callback) (struct ast_bridge_channel *bridge_channel, void *hook_pvt, int talking)
Talking indicator callback.
Enumerations
enum ast_bridge_builtin_feature {
AST_BRIDGE_BUILTIN_BLINDTRANSFER, AST_BRIDGE_BUILTIN_ATTENDEDTRANSFER, AST_BRIDGE_BUILTIN_HANGUP, AST_BRIDGE_BUILTIN_PARKCALL,
AST_BRIDGE_BUILTIN_AUTOMON, AST_BRIDGE_BUILTIN_AUTOMIXMON, AST_BRIDGE_BUILTIN_END
}
Built in DTMF features.
enum ast_bridge_builtin_interval { AST_BRIDGE_BUILTIN_INTERVAL_LIMITS, AST_BRIDGE_BUILTIN_INTERVAL_END }
enum ast_bridge_channel_feature_flags { AST_BRIDGE_CHANNEL_FLAG_DISSOLVE_HANGUP = (1 << 0), AST_BRIDGE_CHANNEL_FLAG_LONELY = (1 << 1), AST_BRIDGE_CHANNEL_FLAG_IMMOVABLE = (1 << 2) }
Flags used for per bridge channel features.
enum ast_bridge_feature_flags {
AST_BRIDGE_FLAG_DISSOLVE_HANGUP = (1 << 0), AST_BRIDGE_FLAG_DISSOLVE_EMPTY = (1 << 1), AST_BRIDGE_FLAG_SMART = (1 << 2), AST_BRIDGE_FLAG_MERGE_INHIBIT_FROM = (1 << 3),
AST_BRIDGE_FLAG_MERGE_INHIBIT_TO = (1 << 4), AST_BRIDGE_FLAG_SWAP_INHIBIT_FROM = (1 << 5), AST_BRIDGE_FLAG_SWAP_INHIBIT_TO = (1 << 6), AST_BRIDGE_FLAG_MASQUERADE_ONLY = (1 << 7),
AST_BRIDGE_FLAG_TRANSFER_PROHIBITED = (1 << 8), AST_BRIDGE_FLAG_TRANSFER_BRIDGE_ONLY = (1 << 9), AST_BRIDGE_FLAG_INVISIBLE = (1 << 10)
}
Flags used for bridge features.
enum ast_bridge_features_monitor { AUTO_MONITOR_TOGGLE, AUTO_MONITOR_START, AUTO_MONITOR_STOP }
enum ast_bridge_hook_remove_flags { AST_BRIDGE_HOOK_REMOVE_ON_PULL = (1 << 0), AST_BRIDGE_HOOK_REMOVE_ON_PERSONALITY_CHANGE = (1 << 1) }
enum ast_bridge_hook_timer_option { AST_BRIDGE_HOOK_TIMER_OPTION_MEDIA = (1 << 0) }
enum ast_bridge_hook_type {
AST_BRIDGE_HOOK_TYPE_NONE, AST_BRIDGE_HOOK_TYPE_DTMF, AST_BRIDGE_HOOK_TYPE_TIMER, AST_BRIDGE_HOOK_TYPE_HANGUP,
AST_BRIDGE_HOOK_TYPE_JOIN, AST_BRIDGE_HOOK_TYPE_LEAVE, AST_BRIDGE_HOOK_TYPE_TALK, AST_BRIDGE_HOOK_TYPE_MOVE
}
Functions
int ast_bridge_dtmf_hook (struct ast_bridge_features *features, const char *dtmf, ast_bridge_hook_callback callback, void *hook_pvt, ast_bridge_hook_pvt_destructor destructor, enum ast_bridge_hook_remove_flags remove_flags)
Attach a DTMF hook to a bridge features structure.
void ast_bridge_features_cleanup (struct ast_bridge_features *features)
Clean up the contents of a bridge features structure.
void ast_bridge_features_destroy (struct ast_bridge_features *features)
Destroy an allocated bridge features struct.
int ast_bridge_features_do (enum ast_bridge_builtin_feature feature, struct ast_bridge_channel *bridge_channel, void *hook_pvt)
Invoke a built in feature hook now.
int ast_bridge_features_enable (struct ast_bridge_features *features, enum ast_bridge_builtin_feature feature, const char *dtmf, void *config, ast_bridge_hook_pvt_destructor destructor, enum ast_bridge_hook_remove_flags remove_flags)
Enable a built in feature on a bridge features structure.
int ast_bridge_features_init (struct ast_bridge_features *features)
Initialize bridge features structure.
int ast_bridge_features_limits_construct (struct ast_bridge_features_limits *limits)
Constructor function for ast_bridge_features_limits.
void ast_bridge_features_limits_destroy (struct ast_bridge_features_limits *limits)
Destructor function for ast_bridge_features_limits.
void ast_bridge_features_merge (struct ast_bridge_features *into, const struct ast_bridge_features *from)
Merge one ast_bridge_features into another.
struct ast_bridge_features * ast_bridge_features_new (void)
Allocate a new bridge features struct.
int ast_bridge_features_register (enum ast_bridge_builtin_feature feature, ast_bridge_hook_callback callback, const char *dtmf)
Register a handler for a built in feature.
void ast_bridge_features_set_flag (struct ast_bridge_features *features, unsigned int flag)
Set a flag on a bridge channel features structure.
int ast_bridge_features_set_limits (struct ast_bridge_features *features, struct ast_bridge_features_limits *limits, enum ast_bridge_hook_remove_flags remove_flags)
Limit the amount of time a channel may stay in the bridge and optionally play warning messages as time runs out.
int ast_bridge_features_unregister (enum ast_bridge_builtin_feature feature)
Unregister a handler for a built in feature.
int ast_bridge_hangup_hook (struct ast_bridge_features *features, ast_bridge_hook_callback callback, void *hook_pvt, ast_bridge_hook_pvt_destructor destructor, enum ast_bridge_hook_remove_flags remove_flags)
Attach a hangup hook to a bridge features structure.
int ast_bridge_interval_hook (struct ast_bridge_features *features, enum ast_bridge_hook_timer_option flags, unsigned int interval, ast_bridge_hook_callback callback, void *hook_pvt, ast_bridge_hook_pvt_destructor destructor, enum ast_bridge_hook_remove_flags remove_flags)
Attach an interval hook to a bridge features structure.
int ast_bridge_interval_register (enum ast_bridge_builtin_interval interval, ast_bridge_builtin_set_limits_fn callback)
Register a handler for a built in interval feature.
int ast_bridge_join_hook (struct ast_bridge_features *features, ast_bridge_hook_callback callback, void *hook_pvt, ast_bridge_hook_pvt_destructor destructor, enum ast_bridge_hook_remove_flags remove_flags)
Unregisters a handler for a built in interval feature.
int ast_bridge_leave_hook (struct ast_bridge_features *features, ast_bridge_hook_callback callback, void *hook_pvt, ast_bridge_hook_pvt_destructor destructor, enum ast_bridge_hook_remove_flags remove_flags)
Attach a bridge channel leave hook to a bridge features structure.
int ast_bridge_move_hook (struct ast_bridge_features *features, ast_bridge_move_indicate_callback callback, void *hook_pvt, ast_bridge_hook_pvt_destructor destructor, enum ast_bridge_hook_remove_flags remove_flags)
Attach a bridge channel move detection hook to a bridge features structure.
int ast_bridge_talk_detector_hook (struct ast_bridge_features *features, ast_bridge_talking_indicate_callback callback, void *hook_pvt, ast_bridge_hook_pvt_destructor destructor, enum ast_bridge_hook_remove_flags remove_flags)
Attach a bridge channel talk detection hook to a bridge features structure.
Detailed Description
Channel Bridging API.
Author
Joshua Colp jcolp.nosp@m.@dig.nosp@m.ium.c.nosp@m.om
Definition in file bridge_features.h.
Macro Definition Documentation
MAXIMUM_DTMF_FEATURE_STRING
#define MAXIMUM_DTMF_FEATURE_STRING (11 + 1)
Maximum length of a DTMF feature string.
Definition at line 217 of file bridge_features.h.
Referenced by action_playback_and_continue().
Typedef Documentation
ast_bridge_builtin_set_limits_fn
typedef int(* ast_bridge_builtin_set_limits_fn) (struct ast_bridge_features *features, struct ast_bridge_features_limits *limits, enum ast_bridge_hook_remove_flags remove_flags)
Attach interval hooks to a bridge features structure.
Parameters
features Bridge features structure
limits Configured limits applicable to the channel
remove_flags Dictates what situations the hook should be removed.
Return values
0 on success
-1 on failure
Definition at line 422 of file bridge_features.h.
ast_bridge_hook_callback
typedef int(* ast_bridge_hook_callback) (struct ast_bridge_channel *bridge_channel, void *hook_pvt)
Hook callback type.
Parameters
bridge_channel Channel executing the feature
hook_pvt Private data passed in when the hook was created
For interval hooks:
Return values
0 Setup to fire again at the last interval.
positive Setup to fire again at the new interval returned.
-1 Remove the callback hook.
For other hooks:
Return values
0 Keep the callback hook.
-1 Remove the callback hook.
Definition at line 136 of file bridge_features.h.
ast_bridge_hook_pvt_destructor
typedef void(* ast_bridge_hook_pvt_destructor) (void *hook_pvt)
Hook pvt destructor callback.
Parameters
hook_pvt Private data passed in when the hook was created to destroy
Definition at line 143 of file bridge_features.h.
ast_bridge_move_indicate_callback
typedef int(* ast_bridge_move_indicate_callback) (struct ast_bridge_channel *bridge_channel, void *hook_pvt, struct ast_bridge *src, struct ast_bridge *dst)
Move indicator callback.
This callback can be registered with the bridge channel in order to be notified when the bridge channel is being moved from one bridge to another.
Parameters
bridge_channel The channel executing the feature
hook_pvt Private data passed in when the hook was created
src The bridge from which the bridge channel is moving
dst The bridge into which the bridge channel is moving
Return values
0 Keep the callback hook.
-1 Remove the callback hook.
Definition at line 178 of file bridge_features.h.
ast_bridge_talking_indicate_callback
typedef int(* ast_bridge_talking_indicate_callback) (struct ast_bridge_channel *bridge_channel, void *hook_pvt, int talking)
Talking indicator callback.
This callback can be registered with the bridge channel in order to receive updates when the bridge_channel has started and stopped talking.
Parameters
bridge_channel Channel executing the feature
hook_pvt Private data passed in when the hook was created
talking TRUE if the channel is now talking
Return values
0 Keep the callback hook.
-1 Remove the callback hook.
Definition at line 160 of file bridge_features.h.
Enumeration Type Documentation
ast_bridge_builtin_feature
enum ast_bridge_builtin_feature
Built in DTMF features.
Enumerator
AST_BRIDGE_BUILTIN_BLINDTRANSFER
DTMF based Blind Transfer
AST_BRIDGE_BUILTIN_ATTENDEDTRANSFER
DTMF based Attended Transfer
AST_BRIDGE_BUILTIN_HANGUP
DTMF based depart bridge feature
Note
Imparted channels are optionally hangup depending upon how it was imparted.
Joined channels exit the bridge with BRIDGE_CHANNEL_STATE_END_WITH_DISSOLVE.
AST_BRIDGE_BUILTIN_PARKCALL
DTMF based Park
The bridge is parked and the channel hears the parking slot to which it was parked.
AST_BRIDGE_BUILTIN_AUTOMON
DTMF one-touch-record toggle using Monitor app.
Note
Only valid on two party bridges.
AST_BRIDGE_BUILTIN_AUTOMIXMON
DTMF one-touch-record toggle using MixMonitor app.
Note
Only valid on two party bridges.
AST_BRIDGE_BUILTIN_END
End terminator for list of built in features. Must remain last.
Definition at line 71 of file bridge_features.h.
{
    /*! DTMF based Blind Transfer */
    AST_BRIDGE_BUILTIN_BLINDTRANSFER,
    /*! DTMF based Attended Transfer */
    AST_BRIDGE_BUILTIN_ATTENDEDTRANSFER,
    /*!
     * DTMF based depart bridge feature
     *
     * \note Imparted channels are optionally hangup depending upon
     * how it was imparted.
     *
     * \note Joined channels exit the bridge with
     * BRIDGE_CHANNEL_STATE_END_WITH_DISSOLVE.
     */
    AST_BRIDGE_BUILTIN_HANGUP,
    /*!
     * DTMF based Park
     *
     * \details The bridge is parked and the channel hears the
     * parking slot to which it was parked.
     */
    AST_BRIDGE_BUILTIN_PARKCALL,
    /*!
     * DTMF one-touch-record toggle using Monitor app.
     *
     * \note Only valid on two party bridges.
     */
    AST_BRIDGE_BUILTIN_AUTOMON,
    /*!
     * DTMF one-touch-record toggle using MixMonitor app.
     *
     * \note Only valid on two party bridges.
     */
    AST_BRIDGE_BUILTIN_AUTOMIXMON,
    /*! End terminator for list of built in features. Must remain last. */
    AST_BRIDGE_BUILTIN_END
 };
ast_bridge_builtin_interval
enum ast_bridge_builtin_interval
Enumerator
AST_BRIDGE_BUILTIN_INTERVAL_LIMITS
Apply Call Duration Limits
AST_BRIDGE_BUILTIN_INTERVAL_END
End terminator for list of built in interval features. Must remain last.
Definition at line 110 of file bridge_features.h.
{
    /*! Apply Call Duration Limits */
    AST_BRIDGE_BUILTIN_INTERVAL_LIMITS,
    /*! End terminator for list of built in interval features. Must remain last. */
    AST_BRIDGE_BUILTIN_INTERVAL_END
 };
ast_bridge_channel_feature_flags
enum ast_bridge_channel_feature_flags
Flags used for per bridge channel features.
Enumerator
AST_BRIDGE_CHANNEL_FLAG_DISSOLVE_HANGUP
Upon channel hangup all bridge participants should be kicked out.
AST_BRIDGE_CHANNEL_FLAG_LONELY
This channel leaves the bridge if all participants have this flag set.
AST_BRIDGE_CHANNEL_FLAG_IMMOVABLE
This channel cannot be moved to another bridge.
Definition at line 61 of file bridge_features.h.
{
    /*! Upon channel hangup all bridge participants should be kicked out. */
    AST_BRIDGE_CHANNEL_FLAG_DISSOLVE_HANGUP = (1 << 0),
    /*! This channel leaves the bridge if all participants have this flag set. */
    AST_BRIDGE_CHANNEL_FLAG_LONELY = (1 << 1),
    /*! This channel cannot be moved to another bridge. */
    AST_BRIDGE_CHANNEL_FLAG_IMMOVABLE = (1 << 2),
 };
ast_bridge_feature_flags
enum ast_bridge_feature_flags
Flags used for bridge features.
Enumerator
AST_BRIDGE_FLAG_DISSOLVE_HANGUP
Upon channel hangup all bridge participants should be kicked out.
AST_BRIDGE_FLAG_DISSOLVE_EMPTY
The last channel to leave the bridge dissolves it.
AST_BRIDGE_FLAG_SMART
Move between bridging technologies as needed.
AST_BRIDGE_FLAG_MERGE_INHIBIT_FROM
Bridge channels cannot be merged from this bridge.
AST_BRIDGE_FLAG_MERGE_INHIBIT_TO
Bridge channels cannot be merged to this bridge.
AST_BRIDGE_FLAG_SWAP_INHIBIT_FROM
Bridge channels cannot be local channel swap optimized from this bridge.
AST_BRIDGE_FLAG_SWAP_INHIBIT_TO
Bridge channels cannot be local channel swap optimized to this bridge.
AST_BRIDGE_FLAG_MASQUERADE_ONLY
Bridge channels can be moved to another bridge only by masquerade (ConfBridge)
AST_BRIDGE_FLAG_TRANSFER_PROHIBITED
Bridge does not allow transfers of channels out
AST_BRIDGE_FLAG_TRANSFER_BRIDGE_ONLY
Bridge transfers require transfer of entire bridge rather than individual channels
AST_BRIDGE_FLAG_INVISIBLE
Bridge is invisible to AMI/CLI/ARI/etc.
Definition at line 35 of file bridge_features.h.
{
    /*! Upon channel hangup all bridge participants should be kicked out. */
    AST_BRIDGE_FLAG_DISSOLVE_HANGUP = (1 << 0),
    /*! The last channel to leave the bridge dissolves it. */
    AST_BRIDGE_FLAG_DISSOLVE_EMPTY = (1 << 1),
    /*! Move between bridging technologies as needed. */
    AST_BRIDGE_FLAG_SMART = (1 << 2),
    /*! Bridge channels cannot be merged from this bridge. */
    AST_BRIDGE_FLAG_MERGE_INHIBIT_FROM = (1 << 3),
    /*! Bridge channels cannot be merged to this bridge. */
    AST_BRIDGE_FLAG_MERGE_INHIBIT_TO = (1 << 4),
    /*! Bridge channels cannot be local channel swap optimized from this bridge. */
    AST_BRIDGE_FLAG_SWAP_INHIBIT_FROM = (1 << 5),
    /*! Bridge channels cannot be local channel swap optimized to this bridge. */
    AST_BRIDGE_FLAG_SWAP_INHIBIT_TO = (1 << 6),
    /*! Bridge channels can be moved to another bridge only by masquerade (ConfBridge) */
    AST_BRIDGE_FLAG_MASQUERADE_ONLY = (1 << 7),
    /*! Bridge does not allow transfers of channels out */
    AST_BRIDGE_FLAG_TRANSFER_PROHIBITED = (1 << 8),
    /*! Bridge transfers require transfer of entire bridge rather than individual channels */
    AST_BRIDGE_FLAG_TRANSFER_BRIDGE_ONLY = (1 << 9),
    /*! Bridge is invisible to AMI/CLI/ARI/etc. */
    AST_BRIDGE_FLAG_INVISIBLE = (1 << 10),
 };
ast_bridge_features_monitor
enum ast_bridge_features_monitor
Enumerator
AUTO_MONITOR_TOGGLE
Toggle start/stop of Monitor/MixMonitor.
AUTO_MONITOR_START
Start Monitor/MixMonitor if not already started.
AUTO_MONITOR_STOP
Stop Monitor/MixMonitor if not already stopped.
Definition at line 310 of file bridge_features.h.
{
    /*! Toggle start/stop of Monitor/MixMonitor. */
    AUTO_MONITOR_TOGGLE,
    /*! Start Monitor/MixMonitor if not already started. */
    AUTO_MONITOR_START,
    /*! Stop Monitor/MixMonitor if not already stopped. */
    AUTO_MONITOR_STOP,
 };
ast_bridge_hook_remove_flags
enum ast_bridge_hook_remove_flags
Enumerator
AST_BRIDGE_HOOK_REMOVE_ON_PULL
The hook is removed when the channel is pulled from the bridge.
AST_BRIDGE_HOOK_REMOVE_ON_PERSONALITY_CHANGE
The hook is removed when the bridge's personality changes.
Definition at line 181 of file bridge_features.h.
{
    /*! The hook is removed when the channel is pulled from the bridge. */
    AST_BRIDGE_HOOK_REMOVE_ON_PULL = (1 << 0),
    /*! The hook is removed when the bridge's personality changes. */
    AST_BRIDGE_HOOK_REMOVE_ON_PERSONALITY_CHANGE = (1 << 1),
 };
ast_bridge_hook_timer_option
enum ast_bridge_hook_timer_option
Enumerator
AST_BRIDGE_HOOK_TIMER_OPTION_MEDIA
The timer temporarily affects media. (Like a custom playfile.)
Definition at line 233 of file bridge_features.h.
{
    /*! The timer temporarily affects media. (Like a custom playfile.) */
    AST_BRIDGE_HOOK_TIMER_OPTION_MEDIA = (1 << 0),
 };
ast_bridge_hook_type
enum ast_bridge_hook_type
Enumerator
AST_BRIDGE_HOOK_TYPE_NONE
The hook type has not been specified.
AST_BRIDGE_HOOK_TYPE_DTMF
AST_BRIDGE_HOOK_TYPE_TIMER
AST_BRIDGE_HOOK_TYPE_HANGUP
AST_BRIDGE_HOOK_TYPE_JOIN
AST_BRIDGE_HOOK_TYPE_LEAVE
AST_BRIDGE_HOOK_TYPE_TALK
AST_BRIDGE_HOOK_TYPE_MOVE
Definition at line 188 of file bridge_features.h.
{
    /*! The hook type has not been specified. */
    AST_BRIDGE_HOOK_TYPE_NONE,
    AST_BRIDGE_HOOK_TYPE_DTMF,
    AST_BRIDGE_HOOK_TYPE_TIMER,
    AST_BRIDGE_HOOK_TYPE_HANGUP,
    AST_BRIDGE_HOOK_TYPE_JOIN,
    AST_BRIDGE_HOOK_TYPE_LEAVE,
    AST_BRIDGE_HOOK_TYPE_TALK,
    AST_BRIDGE_HOOK_TYPE_MOVE,
 };
Function Documentation
ast_bridge_dtmf_hook()
int ast_bridge_dtmf_hook (struct ast_bridge_features * features, const char * dtmf, ast_bridge_hook_callback callback, void * hook_pvt, ast_bridge_hook_pvt_destructor destructor, enum ast_bridge_hook_remove_flags remove_flags)
Attach a DTMF hook to a bridge features structure.
Parameters
features Bridge features structure
dtmf DTMF string to be activated upon
callback Function to execute upon activation
hook_pvt Unique data
destructor Optional destructor callback for hook_pvt data
remove_flags Dictates what situations the hook should be removed.
Return values
0 on success
-1 on failure (The caller must cleanup any hook_pvt resources.)
Example usage:
struct ast_bridge_features features;
ast_bridge_features_init(&features);
ast_bridge_dtmf_hook(&features, "#", pound_callback, NULL, NULL, 0);
This makes the bridging core call pound_callback if a channel that has this feature structure inputs the DTMF string '#'. A pointer to useful data may be provided to the hook_pvt parameter.
Definition at line 3245 of file bridge.c.
References ao2_link, ao2_ref, AST_BRIDGE_HOOK_TYPE_DTMF, ast_copy_string(), bridge_hook_generic(), ast_bridge_hook_dtmf_parms::code, ast_bridge_hook::destructor, ast_bridge_hook_dtmf::dtmf, ast_bridge_features::dtmf_hooks, ast_bridge_hook_dtmf::generic, NULL, and ast_bridge_hook::type.
Referenced by apply_menu_to_user(), ast_bridge_features_enable(), AST_TEST_DEFINE(), bridge_agent_hold_push(), bridge_personality_atxfer_push(), and dynamic_dtmf_hook_add().
 {
    struct ast_bridge_hook_dtmf *hook;
    int res;
    /* Allocate new hook and setup it's various variables */
    hook = (struct ast_bridge_hook_dtmf *) bridge_hook_generic(sizeof(*hook), callback,
       hook_pvt, destructor, remove_flags);
    if (!hook) {
       return -1;
    }
    hook->generic.type = AST_BRIDGE_HOOK_TYPE_DTMF;
    ast_copy_string(hook->dtmf.code, dtmf, sizeof(hook->dtmf.code));
    /* Once done we put it in the container. */
    res = ao2_link(features->dtmf_hooks, hook) ? 0 : -1;
    if (res) {
       /*
        * Could not link the hook into the container.
        *
        * Remove the hook_pvt destructor call from the hook since we
        * are returning failure to install the hook.
        */
       hook->generic.destructor = NULL;
    }
    ao2_ref(hook, -1);
    return res;
 }
ast_bridge_features_cleanup()
void ast_bridge_features_cleanup (struct ast_bridge_features * features)
Clean up the contents of a bridge features structure.
Parameters
features Bridge features structure
Returns
Nothing
Example usage:
struct ast_bridge_features features;
ast_bridge_features_init(&features);
ast_bridge_features_cleanup(&features);
This cleans up the feature structure 'features'.
Note
This MUST be called after the features structure is done being used or a memory leak may occur.
Definition at line 3720 of file bridge.c.
References ao2_cleanup, ao2_ref, ast_heap_destroy(), ast_heap_pop(), ast_bridge_features::dtmf_hooks, ast_bridge_features::interval_hooks, NULL, and ast_bridge_features::other_hooks.
Referenced by agent_request_exec(), agent_run(), ast_bridge_call_with_flags(), ast_bridge_features_destroy(), AST_TEST_DEFINE(), bridge_exec(), bridgeadd_exec(), bridgewait_exec(), channel_feature_hooks_set_full(), confbridge_exec(), park_and_announce_app_exec(), park_app_exec(), and parked_call_app_exec().
 {
    struct ast_bridge_hook_timer *hook;
    /* Destroy the interval hooks heap. */
    if (features->interval_hooks) {
       while ((hook = ast_heap_pop(features->interval_hooks))) {
          ao2_ref(hook, -1);
       }
       features->interval_hooks = ast_heap_destroy(features->interval_hooks);
    }
    /* Destroy the miscellaneous other hooks container. */
    ao2_cleanup(features->other_hooks);
    features->other_hooks = NULL;
    /* Destroy the DTMF hooks container. */
    ao2_cleanup(features->dtmf_hooks);
    features->dtmf_hooks = NULL;
 }
ast_bridge_features_destroy()
void ast_bridge_features_destroy (struct ast_bridge_features * features)
Destroy an allocated bridge features struct.
Since
12.0.0
Parameters
features Bridge features structure
Example usage:
struct ast_bridge_features *features;
features = ast_bridge_features_new();
ast_bridge_features_destroy(features);
Returns
Nothing
Definition at line 3741 of file bridge.c.
References ast_bridge_features_cleanup(), and ast_free.
Referenced by ast_bridge_add_channel(), ast_bridge_call_with_flags(), ast_bridge_features_new(), ast_local_setup_bridge(), bridge_channel_depart_thread(), bridge_channel_ind_thread(), bridge_exec(), bridge_impart_internal(), conf_start_record(), control_dtor(), features_destroy(), and local_pvt_destructor().
 {
    if (!features) {
       return;
    }
    ast_bridge_features_cleanup(features);
    ast_free(features);
 }
ast_bridge_features_do()
int ast_bridge_features_do (enum ast_bridge_builtin_feature feature, struct ast_bridge_channel * bridge_channel, void * hook_pvt)
Invoke a built in feature hook now.
Parameters
feature The feature to invoke
bridge_channel Channel executing the feature
hook_pvt Private data passed in when the hook was created
Note
This API call is only meant to be used by bridge subclasses and hook callbacks to request a builtin feature hook to be executed.
Return values
0 on success
-1 on failure
Example usage:
ast_bridge_features_do(AST_BRIDGE_BUILTIN_ATTENDED_TRANSFER, bridge_channel, hook_pvt);
Definition at line 3151 of file bridge.c.
References ARRAY_LEN, and builtin_features_handlers.
Referenced by agent_connect_caller().
 {
    ast_bridge_hook_callback callback;
    if (ARRAY_LEN(builtin_features_handlers) <= feature) {
       return -1;
    }
    callback = builtin_features_handlers[feature];
    if (!callback) {
       return -1;
    }
    callback(bridge_channel, hook_pvt);
    return 0;
 }
ast_bridge_features_enable()
int ast_bridge_features_enable (struct ast_bridge_features * features, enum ast_bridge_builtin_feature feature, const char * dtmf, void * config, ast_bridge_hook_pvt_destructor destructor, enum ast_bridge_hook_remove_flags remove_flags)
Enable a built in feature on a bridge features structure.
Parameters
features Bridge features structure
feature Feature to enable
dtmf Optionally the DTMF stream to trigger the feature, if not specified it will be the default
config Configuration structure unique to the built in type
destructor Optional destructor callback for config data
remove_flags Dictates what situations the hook should be removed.
Return values
0 on success
-1 on failure
Example usage:
struct ast_bridge_features features;
ast_bridge_features_init(&features);
ast_bridge_features_enable(&features, AST_BRIDGE_BUILTIN_ATTENDEDTRANSFER, NULL, NULL, 0);
This enables the attended transfer DTMF option using the default DTMF string. An alternate string may be provided using the dtmf parameter. Internally this is simply setting up a hook to a built in feature callback function.
Definition at line 3428 of file bridge.c.
References ARRAY_LEN, ast_bridge_dtmf_hook(), ast_debug, ast_strlen_zero, builtin_features_dtmf, and builtin_features_handlers.
Referenced by builtin_features_helper().
 {
    if (ARRAY_LEN(builtin_features_handlers) <= feature
       || !builtin_features_handlers[feature]) {
       return -1;
    }
    /* If no alternate DTMF stream was provided use the default one */
    if (ast_strlen_zero(dtmf)) {
       dtmf = builtin_features_dtmf[feature];
       /* If no DTMF is still available (ie: it has been disabled) then error out now */
       if (ast_strlen_zero(dtmf)) {
          ast_debug(1, "Failed to enable built in feature %u on %p, no DTMF string is available for it.\n",
             feature, features);
          return -1;
       }
    }
    /*
     * The rest is basically pretty easy.  We create another hook
     * using the built in feature's DTMF callback.  Easy as pie.
     */
    return ast_bridge_dtmf_hook(features, dtmf, builtin_features_handlers[feature],
       config, destructor, remove_flags);
 }
ast_bridge_features_init()
int ast_bridge_features_init (struct ast_bridge_features * features)
Initialize bridge features structure.
Parameters
features Bridge featues structure
Return values
0 on success
-1 on failure
Example usage:
struct ast_bridge_features features;
ast_bridge_features_init(&features);
This initializes the feature structure 'features' to have nothing enabled.
Note
This MUST be called before enabling features or flags. Failure to do so may result in a crash.
Definition at line 3687 of file bridge.c.
References AO2_ALLOC_OPT_LOCK_MUTEX, ao2_container_alloc_list, AO2_CONTAINER_ALLOC_OPT_DUPS_REPLACE, ast_heap_create, bridge_dtmf_hook_sort(), ast_bridge_features::dtmf_hooks, ast_bridge_features::dtmf_passthrough, interval_hook_time_cmp(), ast_bridge_features::interval_hooks, NULL, ast_bridge_features::other_hooks, ast_bridge_features::text_messaging, and timer.
Referenced by agent_request_exec(), agent_run(), ast_bridge_call_with_flags(), ast_bridge_features_new(), AST_TEST_DEFINE(), bridge_exec(), bridgeadd_exec(), bridgewait_exec(), channel_feature_hooks_set_full(), confbridge_exec(), park_and_announce_app_exec(), park_app_exec(), and parked_call_app_exec().
 {
    /* Zero out the structure */
    memset(features, 0, sizeof(*features));
    /* Initialize the DTMF hooks container */
    features->dtmf_hooks = ao2_container_alloc_list(AO2_ALLOC_OPT_LOCK_MUTEX,
       AO2_CONTAINER_ALLOC_OPT_DUPS_REPLACE, bridge_dtmf_hook_sort, NULL);
    if (!features->dtmf_hooks) {
       return -1;
    }
    /* Initialize the miscellaneous other hooks container */
    features->other_hooks = ao2_container_alloc_list(AO2_ALLOC_OPT_LOCK_MUTEX, 0, NULL,
       NULL);
    if (!features->other_hooks) {
       return -1;
    }
    /* Initialize the interval hooks heap */
    features->interval_hooks = ast_heap_create(8, interval_hook_time_cmp,
       offsetof(struct ast_bridge_hook_timer, timer.heap_index));
    if (!features->interval_hooks) {
       return -1;
    }
    features->dtmf_passthrough = 1;
    features->text_messaging = 1;
    return 0;
 }
ast_bridge_features_limits_construct()
int ast_bridge_features_limits_construct (struct ast_bridge_features_limits * limits)
Constructor function for ast_bridge_features_limits.
Parameters
limits pointer to a ast_bridge_features_limits struct that has been allocted, but not initialized
Return values
0 on success
-1 on failure
Definition at line 3459 of file bridge.c.
References ast_string_field_init.
Referenced by bridge_builtin_set_limits(), and pre_bridge_setup().
 {
    memset(limits, 0, sizeof(*limits));
    if (ast_string_field_init(limits, 256)) {
       return -1;
    }
    return 0;
 }
ast_bridge_features_limits_destroy()
void ast_bridge_features_limits_destroy (struct ast_bridge_features_limits * limits)
Destructor function for ast_bridge_features_limits.
Parameters
limits pointer to an ast_bridge_features_limits struct that needs to be destroyed
This function does not free memory allocated to the ast_bridge_features_limits struct, it only frees elements within the struct. You must still call ast_free on the struct if you allocated it with malloc.
Definition at line 3470 of file bridge.c.
References ast_string_field_free_memory.
Referenced by bridge_features_limits_dtor(), and pre_bridge_setup().
 {
    ast_string_field_free_memory(limits);
 }
ast_bridge_features_merge()
void ast_bridge_features_merge (struct ast_bridge_features * into, const struct ast_bridge_features * from)
Merge one ast_bridge_features into another.
Parameters
into The ast_bridge_features that will be merged into
from The ast_bridge_features that will be merged from
Definition at line 3662 of file bridge.c.
References ao2_callback, ast_heap_peek(), ast_heap_unlock, ast_heap_wrlock, ast_bridge_features::dtmf_hooks, ast_bridge_features::dtmf_passthrough, ast_bridge_features::feature_flags, ast_flags::flags, ast_bridge_features::interval_hooks, merge_container_cb(), ast_bridge_features::mute, ast_bridge_features::other_hooks, ast_bridge_features::usable, and wrap_hook().
Referenced by bridge_channel_internal_join(), and channel_feature_hooks_set_full().
 {
    struct ast_bridge_hook_timer *hook;
    int idx;
    /* Merge hook containers */
    ao2_callback(from->dtmf_hooks, 0, merge_container_cb, into->dtmf_hooks);
    ao2_callback(from->other_hooks, 0, merge_container_cb, into->other_hooks);
    /* Merge hook heaps */
    ast_heap_wrlock(from->interval_hooks);
    for (idx = 1; (hook = ast_heap_peek(from->interval_hooks, idx)); idx++) {
       wrap_hook(into, hook);
    }
    ast_heap_unlock(from->interval_hooks);
    /* Merge feature flags */
    into->feature_flags.flags |= from->feature_flags.flags;
    into->usable |= from->usable;
    into->mute |= from->mute;
    into->dtmf_passthrough |= from->dtmf_passthrough;
 }
ast_bridge_features_new()
struct ast_bridge_features* ast_bridge_features_new (void)
Allocate a new bridge features struct.
Since
12.0.0
Example usage:
struct ast_bridge_features *features;
features = ast_bridge_features_new();
ast_bridge_features_destroy(features);
Return values
features New allocated features struct.
NULL on error.
Definition at line 3750 of file bridge.c.
References ast_bridge_features_destroy(), ast_bridge_features_init(), ast_malloc, and NULL.
Referenced by ast_bridge_call_with_flags(), ast_unreal_channel_push_to_bridge(), bridge_exec(), bridge_impart_internal(), channel_feature_hooks_set_full(), conf_announce_channel_push(), conf_start_record(), and stasis_app_control_bridge_features_init().
 {
    struct ast_bridge_features *features;
    features = ast_malloc(sizeof(*features));
    if (features) {
       if (ast_bridge_features_init(features)) {
          ast_bridge_features_destroy(features);
          features = NULL;
       }
    }
    return features;
 }
ast_bridge_features_register()
int ast_bridge_features_register (enum ast_bridge_builtin_feature feature, ast_bridge_hook_callback callback, const char * dtmf)
Register a handler for a built in feature.
Parameters
feature The feature that the handler will be responsible for
callback The callback function that will handle it
dtmf Default DTMF string used to activate the feature
Return values
0 on success
-1 on failure
Example usage:
ast_bridge_features_register(AST_BRIDGE_BUILTIN_ATTENDED_TRANSFER, bridge_builtin_attended_transfer, "*1");
This registers the function bridge_builtin_attended_transfer as the function responsible for the built in attended transfer feature.
Definition at line 3123 of file bridge.c.
References ARRAY_LEN, ast_copy_string(), ast_strlen_zero, builtin_features_dtmf, and builtin_features_handlers.
Referenced by ast_bridging_init_basic(), load_module(), and load_parking_bridge_features().
 {
    if (ARRAY_LEN(builtin_features_handlers) <= feature
       || builtin_features_handlers[feature]) {
       return -1;
    }
    if (!ast_strlen_zero(dtmf)) {
       ast_copy_string(builtin_features_dtmf[feature], dtmf, sizeof(builtin_features_dtmf[feature]));
    }
    builtin_features_handlers[feature] = callback;
    return 0;
 }
ast_bridge_features_set_flag()
void ast_bridge_features_set_flag (struct ast_bridge_features * features, unsigned int flag)
Set a flag on a bridge channel features structure.
Parameters
features Bridge channel features structure
flag Flag to enable
Returns
Nothing
Example usage:
struct ast_bridge_features features;
ast_bridge_features_init(&features);
ast_bridge_features_set_flag(&features, AST_BRIDGE_CHANNEL_FLAG_DISSOLVE_HANGUP);
This sets the AST_BRIDGE_CHANNEL_FLAG_DISSOLVE_HANGUP feature to be enabled on the features structure 'features'.
Definition at line 3490 of file bridge.c.
References ast_set_flag, ast_bridge_features::feature_flags, and ast_bridge_features::usable.
 {
    ast_set_flag(&features->feature_flags, flag);
    features->usable = 1;
 }
ast_bridge_features_set_limits()
int ast_bridge_features_set_limits (struct ast_bridge_features * features, struct ast_bridge_features_limits * limits, enum ast_bridge_hook_remove_flags remove_flags)
Limit the amount of time a channel may stay in the bridge and optionally play warning messages as time runs out.
Parameters
features Bridge features structure
limits Configured limits applicable to the channel
remove_flags Dictates what situations the hook should be removed.
Return values
0 on success
-1 on failure
Example usage:
struct ast_bridge_features features;
struct ast_bridge_features_limits limits;
ast_bridge_features_init(&features);
ast_bridge_features_limits_construct(&limits);
ast_bridge_features_set_limits(&features, &limits, 0);
ast_bridge_features_limits_destroy(&limits);
This sets the maximum time the channel can be in the bridge to 10 seconds and does not play any warnings.
Note
This API call can only be used on a features structure that will be used in association with a bridge channel.
The ast_bridge_features_limits structure must remain accessible for the lifetime of the features structure.
Definition at line 3475 of file bridge.c.
References AST_BRIDGE_BUILTIN_INTERVAL_LIMITS, ast_log, builtin_interval_handlers, and LOG_ERROR.
Referenced by pre_bridge_setup().
 {
    if (builtin_interval_handlers[AST_BRIDGE_BUILTIN_INTERVAL_LIMITS]) {
       ast_bridge_builtin_set_limits_fn callback;
       callback = builtin_interval_handlers[AST_BRIDGE_BUILTIN_INTERVAL_LIMITS];
       return callback(features, limits, remove_flags);
    }
    ast_log(LOG_ERROR, "Attempted to set limits without an AST_BRIDGE_BUILTIN_INTERVAL_LIMITS callback registered.\n");
    return -1;
 }
ast_bridge_features_unregister()
int ast_bridge_features_unregister (enum ast_bridge_builtin_feature feature)
Unregister a handler for a built in feature.
Parameters
feature The feature to unregister
Return values
0 on success
-1 on failure
Example usage:
ast_bridge_features_unregister(AST_BRIDGE_BUILTIN_ATTENDED_TRANSFER);
This unregisters the function that is handling the built in attended transfer feature.
Definition at line 3139 of file bridge.c.
References ARRAY_LEN, builtin_features_handlers, and NULL.
Referenced by unload_module(), and unload_parking_bridge_features().
 {
    if (ARRAY_LEN(builtin_features_handlers) <= feature
       || !builtin_features_handlers[feature]) {
       return -1;
    }
    builtin_features_handlers[feature] = NULL;
    return 0;
 }
ast_bridge_hangup_hook()
int ast_bridge_hangup_hook (struct ast_bridge_features * features, ast_bridge_hook_callback callback, void * hook_pvt, ast_bridge_hook_pvt_destructor destructor, enum ast_bridge_hook_remove_flags remove_flags)
Attach a hangup hook to a bridge features structure.
Parameters
features Bridge features structure
callback Function to execute upon activation
hook_pvt Unique data
destructor Optional destructor callback for hook_pvt data
remove_flags Dictates what situations the hook should be removed.
Return values
0 on success
-1 on failure (The caller must cleanup any hook_pvt resources.)
Example usage:
struct ast_bridge_features features;
ast_bridge_features_init(&features);
ast_bridge_hangup_hook(&features, hangup_callback, NULL, NULL, 0);
This makes the bridging core call hangup_callback if a channel that has this hook hangs up. A pointer to useful data may be provided to the hook_pvt parameter.
Definition at line 3328 of file bridge.c.
References AST_BRIDGE_HOOK_TYPE_HANGUP, and bridge_other_hook().
Referenced by add_normal_hooks(), and bridge_personality_atxfer_push().
 {
    return bridge_other_hook(features, callback, hook_pvt, destructor, remove_flags,
       AST_BRIDGE_HOOK_TYPE_HANGUP);
 }
ast_bridge_interval_hook()
int ast_bridge_interval_hook (struct ast_bridge_features * features, enum ast_bridge_hook_timer_option flags, unsigned int interval, ast_bridge_hook_callback callback, void * hook_pvt, ast_bridge_hook_pvt_destructor destructor, enum ast_bridge_hook_remove_flags remove_flags)
Attach an interval hook to a bridge features structure.
Parameters
features Bridge features structure
flags Interval timer callback option flags.
interval The interval that the hook should execute at in milliseconds
callback Function to execute upon activation
hook_pvt Unique data
destructor Optional destructor callback for hook_pvt data
remove_flags Dictates what situations the hook should be removed.
Return values
0 on success
-1 on failure (The caller must cleanup any hook_pvt resources.)
struct ast_bridge_features features;
ast_bridge_features_init(&features);
ast_bridge_interval_hook(&features, 1000, playback_callback, NULL, NULL, 0);
This makes the bridging core call playback_callback every second. A pointer to useful data may be provided to the hook_pvt parameter.
Definition at line 3382 of file bridge.c.
References ao2_ref, ast_atomic_fetchadd_int(), AST_BRIDGE_HOOK_TYPE_TIMER, ast_debug, ast_heap_push, ast_heap_unlock, ast_heap_wrlock, ast_samp2tv(), ast_tvadd(), ast_tvnow(), bridge_hook_generic(), ast_bridge_hook::destructor, ast_bridge_hook_timer_parms::flags, ast_bridge_hook_timer::generic, ast_bridge_hook_timer_parms::interval, ast_bridge_features::interval_hooks, ast_bridge_features::interval_sequence, NULL, ast_bridge_hook_timer_parms::seqno, ast_bridge_hook_timer::timer, ast_bridge_hook_timer_parms::trip_time, and ast_bridge_hook::type.
Referenced by agent_request_exec(), apply_option_timeout(), AST_TEST_DEFINE(), bridge_agent_hold_push(), bridge_builtin_set_limits(), confbridge_exec(), parking_set_duration(), set_interval_hook(), and wrap_hook().
 {
    struct ast_bridge_hook_timer *hook;
    int res;
    if (!features ||!interval || !callback) {
       return -1;
    }
    /* Allocate new hook and setup it's various variables */
    hook = (struct ast_bridge_hook_timer *) bridge_hook_generic(sizeof(*hook), callback,
       hook_pvt, destructor, remove_flags);
    if (!hook) {
       return -1;
    }
    hook->generic.type = AST_BRIDGE_HOOK_TYPE_TIMER;
    hook->timer.interval = interval;
    hook->timer.trip_time = ast_tvadd(ast_tvnow(), ast_samp2tv(interval, 1000));
    hook->timer.seqno = ast_atomic_fetchadd_int((int *) &features->interval_sequence, +1);
    hook->timer.flags = flags;
    ast_debug(1, "Putting interval hook %p with interval %u in the heap on features %p\n",
       hook, hook->timer.interval, features);
    ast_heap_wrlock(features->interval_hooks);
    res = ast_heap_push(features->interval_hooks, hook);
    ast_heap_unlock(features->interval_hooks);
    if (res) {
       /*
        * Could not push the hook into the heap
        *
        * Remove the hook_pvt destructor call from the hook since we
        * are returning failure to install the hook.
        */
       hook->generic.destructor = NULL;
       ao2_ref(hook, -1);
    }
    return res ? -1 : 0;
 }
ast_bridge_interval_register()
int ast_bridge_interval_register (enum ast_bridge_builtin_interval interval, ast_bridge_builtin_set_limits_fn callback)
Register a handler for a built in interval feature.
Parameters
interval The interval feature that the handler will be responsible for
callback the Callback function that will handle it
Return values
0 on success
-1 on failure
Example usage:
ast_bridge_interval_register(AST_BRIDGE_BUILTIN_INTERVAL_LIMITS, bridge_builtin_set_limits);
This registers the function bridge_builtin_set_limits as the function responsible for the built in duration limit feature.
Definition at line 3168 of file bridge.c.
References ARRAY_LEN, and builtin_interval_handlers.
Referenced by load_module().
 {
    if (ARRAY_LEN(builtin_interval_handlers) <= interval
       || builtin_interval_handlers[interval]) {
       return -1;
    }
    builtin_interval_handlers[interval] = callback;
    return 0;
 }
ast_bridge_join_hook()
int ast_bridge_join_hook (struct ast_bridge_features * features, ast_bridge_hook_callback callback, void * hook_pvt, ast_bridge_hook_pvt_destructor destructor, enum ast_bridge_hook_remove_flags remove_flags)
Unregisters a handler for a built in interval feature.
Parameters
interval the interval feature to unregister
Return values
0 on success
-1 on failure
Example usage:
   ast_bridge_interval_unregister(AST_BRIDGE_BULTIN_INTERVAL_LIMITS)
   /endcode
   This unregisters the function that is handling the built in duration limit feature.
  /
int ast_bridge_interval_unregister(enum ast_bridge_builtin_interval interval);
/*!
 * \brief Attach a bridge channel join hook to a bridge features structure
 * \param features Bridge features structure
 * \param callback Function to execute upon activation
 * \param hook_pvt Unique data
 * \param destructor Optional destructor callback for hook_pvt data
 * \param remove_flags Dictates what situations the hook should be removed.
 * \retval 0 on success
 * \retval -1 on failure (The caller must cleanup any hook_pvt resources.)
 * Example usage:
 * \code
 * struct ast_bridge_features features;
 * ast_bridge_features_init(&features);
 * ast_bridge_join_hook(&features, join_callback, NULL, NULL, 0);
 *
This makes the bridging core call join_callback when a channel successfully joins the bridging system. A pointer to useful data may be provided to the hook_pvt parameter.
Definition at line 3338 of file bridge.c.
References AST_BRIDGE_HOOK_TYPE_JOIN, and bridge_other_hook().
Referenced by agent_request_exec(), and confbridge_exec().
 {
    return bridge_other_hook(features, callback, hook_pvt, destructor, remove_flags,
       AST_BRIDGE_HOOK_TYPE_JOIN);
 }
ast_bridge_leave_hook()
int ast_bridge_leave_hook (struct ast_bridge_features * features, ast_bridge_hook_callback callback, void * hook_pvt, ast_bridge_hook_pvt_destructor destructor, enum ast_bridge_hook_remove_flags remove_flags)
Attach a bridge channel leave hook to a bridge features structure.
Parameters
features Bridge features structure
callback Function to execute upon activation
hook_pvt Unique data
destructor Optional destructor callback for hook_pvt data
remove_flags Dictates what situations the hook should be removed.
Return values
0 on success
-1 on failure (The caller must cleanup any hook_pvt resources.)
Example usage:
struct ast_bridge_features features;
ast_bridge_features_init(&features);
ast_bridge_leave_hook(&features, leave_callback, NULL, NULL, 0);
This makes the bridging core call leave_callback when a channel successfully leaves the bridging system. A pointer to useful data may be provided to the hook_pvt parameter.
Definition at line 3348 of file bridge.c.
References AST_BRIDGE_HOOK_TYPE_LEAVE, and bridge_other_hook().
Referenced by confbridge_exec().
 {
    return bridge_other_hook(features, callback, hook_pvt, destructor, remove_flags,
       AST_BRIDGE_HOOK_TYPE_LEAVE);
 }
ast_bridge_move_hook()
int ast_bridge_move_hook (struct ast_bridge_features * features, ast_bridge_move_indicate_callback callback, void * hook_pvt, ast_bridge_hook_pvt_destructor destructor, enum ast_bridge_hook_remove_flags remove_flags)
Attach a bridge channel move detection hook to a bridge features structure.
Parameters
features Bridge features structure
callback Function to execute upon activation
hook_pvt Unique data
destructor Optional destructor callback for hook_pvt data
remove_flags Dictates what situations the hook should be removed.
Return values
0 on success
-1 on failure (The caller must cleanup any hook_pvt resources.)
Example usage:
struct ast_bridge_features features;
ast_bridge_features_init(&features);
ast_bridge_move_hook(&features, move_callback, NULL, NULL, 0);
This makes the bridging core call callback when a channel is moved from one bridge to another. A pointer to useful data may be provided to the hook_pvt parameter.
Definition at line 3370 of file bridge.c.
References AST_BRIDGE_HOOK_TYPE_MOVE, bridge_other_hook(), and hook_cb().
Referenced by bridge_stasis_pull().
 {
    ast_bridge_hook_callback hook_cb = (ast_bridge_hook_callback) callback;
    return bridge_other_hook(features, hook_cb, hook_pvt, destructor, remove_flags,
       AST_BRIDGE_HOOK_TYPE_MOVE);
 }
ast_bridge_talk_detector_hook()
int ast_bridge_talk_detector_hook (struct ast_bridge_features * features, ast_bridge_talking_indicate_callback callback, void * hook_pvt, ast_bridge_hook_pvt_destructor destructor, enum ast_bridge_hook_remove_flags remove_flags)
Attach a bridge channel talk detection hook to a bridge features structure.
Parameters
features Bridge features structure
callback Function to execute upon activation
hook_pvt Unique data
destructor Optional destructor callback for hook_pvt data
remove_flags Dictates what situations the hook should be removed.
Return values
0 on success
-1 on failure (The caller must cleanup any hook_pvt resources.)
Example usage:
struct ast_bridge_features features;
ast_bridge_features_init(&features);
ast_bridge_talk_hook(&features, talk_callback, NULL, NULL, 0);
This makes the bridging technology call talk_callback when a channel is recognized as starting and stopping talking. A pointer to useful data may be provided to the hook_pvt parameter.
Note
This hook is currently only supported by softmix.
Definition at line 3358 of file bridge.c.
References AST_BRIDGE_HOOK_TYPE_TALK, bridge_other_hook(), and hook_cb().
Referenced by confbridge_exec().
 {
    ast_bridge_hook_callback hook_cb = (ast_bridge_hook_callback) callback;
    return bridge_other_hook(features, hook_cb, hook_pvt, destructor, remove_flags,
       AST_BRIDGE_HOOK_TYPE_TALK);
 }