Asterisk - The Open Source Telephony Project: res_pjsip_publish_asterisk.c File Reference
res_pjsip_publish_asterisk.c File Reference
#include "asterisk.h"
#include <regex.h>
#include <pjsip.h>
#include <pjsip_simple.h>
#include "asterisk/res_pjsip.h"
#include "asterisk/res_pjsip_outbound_publish.h"
#include "asterisk/res_pjsip_pubsub.h"
#include "asterisk/module.h"
#include "asterisk/logger.h"
#include "asterisk/mwi.h"
Data Structures
struct asterisk_devicestate_publisher_state
Structure which contains Asterisk device state publisher state information.
struct asterisk_mwi_publisher_state
Structure which contains Asterisk mailbox publisher state information.
struct asterisk_publication_config
Structure which contains Asterisk publication information.
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static void asterisk_devicestate_publisher_state_destroy (void *obj)
Destroy callback for Asterisk devicestate publisher state information from datastore.
static void asterisk_mwi_publisher_state_destroy (void *obj)
Destroy callback for Asterisk mwi publisher state information from datastore.
static void * asterisk_publication_config_alloc (const char *name)
Allocator function for Asterisk publication configuration.
static void asterisk_publication_config_destroy (void *obj)
Destructor function for Asterisk publication configuration.
static int asterisk_publication_devicestate (struct ast_sip_publication *pub, struct asterisk_publication_config *config, struct ast_eid *pubsub_eid, struct ast_json *json)
static int asterisk_publication_devicestate_refresh (struct ast_sip_publication *pub, struct asterisk_publication_config *config, struct ast_eid *pubsub_eid, struct ast_json *json)
static int asterisk_publication_devicestate_state_change (struct ast_sip_publication *pub, pjsip_msg_body *body, enum ast_sip_publish_state state)
static int asterisk_publication_mailboxstate (struct ast_sip_publication *pub, struct asterisk_publication_config *config, struct ast_eid *pubsub_eid, struct ast_json *json)
static int asterisk_publication_mwi_refresh (struct ast_sip_publication *pub, struct asterisk_publication_config *config, struct ast_eid *pubsub_eid, struct ast_json *json)
static int asterisk_publication_mwi_state_change (struct ast_sip_publication *pub, pjsip_msg_body *body, enum ast_sip_publish_state state)
static int asterisk_publication_new (struct ast_sip_endpoint *endpoint, const char *resource, const char *event_configuration)
static void asterisk_publication_send_refresh (void)
Internal function to send refresh requests to all publications.
static void asterisk_publisher_devstate_cb (void *data, struct stasis_subscription *sub, struct stasis_message *msg)
Callback function for device state events.
static void asterisk_publisher_mwistate_cb (void *data, struct stasis_subscription *sub, struct stasis_message *msg)
Callback function for mailbox state events.
static int asterisk_start_devicestate_publishing (struct ast_sip_outbound_publish *configuration, struct ast_sip_outbound_publish_client *client)
static int asterisk_start_mwi_publishing (struct ast_sip_outbound_publish *configuration, struct ast_sip_outbound_publish_client *client)
static int asterisk_stop_devicestate_publishing (struct ast_sip_outbound_publish_client *client)
static int asterisk_stop_mwi_publishing (struct ast_sip_outbound_publish_client *client)
static int build_regex (regex_t *regex, const char *text)
static int cached_devstate_cb (void *obj, void *arg, int flags)
static int cached_mwistate_cb (void *obj, void *arg, int flags)
static int load_module (void)
static int regex_filter_handler (const struct aco_option *opt, struct ast_variable *var, void *obj)
static int reload_module (void)
static int send_refresh_cb (void *obj, void *arg, int flags)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "PJSIP Asterisk Event PUBLISH Support" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .reload = reload_module, .unload = unload_module, .load_pri = AST_MODPRI_CHANNEL_DEPEND + 5, .requires = "res_pjsip,res_pjsip_outbound_publish,res_pjsip_pubsub", }
static const struct ast_module_info * ast_module_info = &__mod_info
struct ast_sip_publish_handler asterisk_devicestate_publication_handler
struct ast_sip_event_publisher_handler asterisk_devicestate_publisher_handler
static const struct ast_datastore_info asterisk_devicestate_publisher_state_datastore
Datastore for attaching devicestate publisher state information.
struct ast_sip_publish_handler asterisk_mwi_publication_handler
struct ast_sip_event_publisher_handler asterisk_mwi_publisher_handler
static const struct ast_datastore_info asterisk_mwi_publisher_state_datastore
Datastore for attaching devicestate publisher state information.
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 942 of file res_pjsip_publish_asterisk.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 942 of file res_pjsip_publish_asterisk.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 942 of file res_pjsip_publish_asterisk.c.
asterisk_devicestate_publisher_state_destroy()
static void asterisk_devicestate_publisher_state_destroy (void * obj) static
Destroy callback for Asterisk devicestate publisher state information from datastore.
Definition at line 132 of file res_pjsip_publish_asterisk.c.
References ao2_cleanup, asterisk_devicestate_publisher_state::client, asterisk_devicestate_publisher_state::device_state_filter, and asterisk_devicestate_publisher_state::device_state_regex.
 {
    struct asterisk_devicestate_publisher_state *publisher_state = obj;
    ao2_cleanup(publisher_state->client);
    if (publisher_state->device_state_filter) {
       regfree(&publisher_state->device_state_regex);
    }
 }
asterisk_mwi_publisher_state_destroy()
static void asterisk_mwi_publisher_state_destroy (void * obj) static
Destroy callback for Asterisk mwi publisher state information from datastore.
Definition at line 150 of file res_pjsip_publish_asterisk.c.
References ao2_cleanup, asterisk_mwi_publisher_state::client, asterisk_mwi_publisher_state::mailbox_state_filter, and asterisk_mwi_publisher_state::mailbox_state_regex.
 {
    struct asterisk_mwi_publisher_state *publisher_state = obj;
    ao2_cleanup(publisher_state->client);
    if (publisher_state->mailbox_state_filter) {
       regfree(&publisher_state->mailbox_state_regex);
    }
 }
asterisk_publication_config_alloc()
static void* asterisk_publication_config_alloc (const char * name) static
Allocator function for Asterisk publication configuration.
Definition at line 827 of file res_pjsip_publish_asterisk.c.
References ao2_cleanup, ast_sorcery_generic_alloc(), ast_string_field_init, asterisk_publication_config_destroy(), config, and NULL.
Referenced by load_module().
 {
    struct asterisk_publication_config *config = ast_sorcery_generic_alloc(sizeof(*config),
       asterisk_publication_config_destroy);
    if (!config || ast_string_field_init(config, 256)) {
       ao2_cleanup(config);
       return NULL;
    }
    return config;
 }
asterisk_publication_config_destroy()
static void asterisk_publication_config_destroy (void * obj) static
Destructor function for Asterisk publication configuration.
Definition at line 819 of file res_pjsip_publish_asterisk.c.
References ast_string_field_free_memory, and config.
Referenced by asterisk_publication_config_alloc().
 {
    struct asterisk_publication_config *config = obj;
    ast_string_field_free_memory(config);
 }
asterisk_publication_devicestate()
static int asterisk_publication_devicestate (struct ast_sip_publication * pub, struct asterisk_publication_config * config, struct ast_eid * pubsub_eid, struct ast_json * json) static
Definition at line 492 of file res_pjsip_publish_asterisk.c.
References ast_debug, AST_DEVSTATE_CACHABLE, AST_DEVSTATE_NOT_CACHABLE, ast_devstate_val(), ast_json_integer_get(), ast_json_object_get(), ast_json_string_get(), ast_publish_device_state_full(), ast_sorcery_object_get_id(), ast_strlen_zero, asterisk_publication_config::device_state, asterisk_publication_config::device_state_filter, asterisk_publication_config::device_state_regex, and NULL.
Referenced by asterisk_publication_devicestate_state_change().
 {
    const char *device = ast_json_string_get(ast_json_object_get(json, "device"));
    const char *state = ast_json_string_get(ast_json_object_get(json, "state"));
    int cachable = ast_json_integer_get(ast_json_object_get(json, "cachable"));
    if (!config->device_state) {
       ast_debug(2, "Received device state event for resource '%s' but it is not configured to accept them\n",
          ast_sorcery_object_get_id(config));
       return 0;
    }
    if (ast_strlen_zero(device) || ast_strlen_zero(state)) {
       ast_debug(1, "Received incomplete device state event for resource '%s'\n",
          ast_sorcery_object_get_id(config));
       return -1;
    }
    if (config->device_state_filter && regexec(&config->device_state_regex, device, 0, NULL, 0)) {
       ast_debug(2, "Received device state on resource '%s' for device '%s' but it has been filtered out\n",
          ast_sorcery_object_get_id(config), device);
       return 0;
    }
    ast_publish_device_state_full(device, ast_devstate_val(state),
       cachable == AST_DEVSTATE_CACHABLE ? AST_DEVSTATE_CACHABLE : AST_DEVSTATE_NOT_CACHABLE,
       pubsub_eid);
    return 0;
 }
asterisk_publication_devicestate_refresh()
static int asterisk_publication_devicestate_refresh (struct ast_sip_publication * pub, struct asterisk_publication_config * config, struct ast_eid * pubsub_eid, struct ast_json * json) static
Definition at line 559 of file res_pjsip_publish_asterisk.c.
References ao2_callback, ao2_ref, ast_device_state_cache(), ast_log, ast_sip_publish_client_get(), ast_sip_publish_client_get_datastore(), ast_sorcery_object_get_id(), ast_strlen_zero, cached_devstate_cb(), asterisk_devicestate_publisher_state::client, asterisk_publication_config::devicestate_publish, LOG_ERROR, NULL, OBJ_NODATA, and stasis_cache_dump().
Referenced by asterisk_publication_devicestate_state_change().
 {
    struct ast_sip_outbound_publish_client *client;
    struct ast_datastore *datastore;
    struct ao2_container *cached;
    if (ast_strlen_zero(config->devicestate_publish)) {
       return 0;
    }
    client = ast_sip_publish_client_get(config->devicestate_publish);
    if (!client) {
       ast_log(LOG_ERROR, "Received refresh request for devicestate on publication '%s' but publish '%s' is not available\n",
          ast_sorcery_object_get_id(config), config->devicestate_publish);
       return 0;
    }
    datastore = ast_sip_publish_client_get_datastore(client, "asterisk-devicestate-publisher");
    if (!datastore) {
       ao2_ref(client, -1);
       return 0;
    }
    cached = stasis_cache_dump(ast_device_state_cache(), NULL);
    if (cached) {
       ao2_callback(cached, OBJ_NODATA, cached_devstate_cb, datastore);
       ao2_ref(cached, -1);
    }
    ao2_ref(client, -1);
    ao2_ref(datastore, -1);
    return 0;
 }
asterisk_publication_devicestate_state_change()
static int asterisk_publication_devicestate_state_change (struct ast_sip_publication * pub, pjsip_msg_body * body, enum ast_sip_publish_state state) static
Definition at line 594 of file res_pjsip_publish_asterisk.c.
References ao2_cleanup, ast_debug, ast_json_load_buf(), ast_json_object_get(), ast_json_string_get(), ast_json_unref(), ast_sip_get_sorcery(), ast_sip_is_content_type(), ast_sip_publication_get_event_configuration(), ast_sorcery_object_get_id(), ast_sorcery_retrieve_by_id(), ast_str_to_eid(), asterisk_publication_devicestate(), asterisk_publication_devicestate_refresh(), config, NULL, RAII_VAR, and type.
 {
    RAII_VAR(struct asterisk_publication_config *, config, ast_sorcery_retrieve_by_id(ast_sip_get_sorcery(), "asterisk-publication",
       ast_sip_publication_get_event_configuration(pub)), ao2_cleanup);
    RAII_VAR(struct ast_json *, json, NULL, ast_json_unref);
    const char *eid, *type;
    struct ast_eid pubsub_eid;
    int res = -1;
    /* If no configuration exists for this publication it has most likely been removed, so drop this immediately */
    if (!config) {
       return -1;
    }
    /* If no body exists this is a refresh and can be ignored */
    if (!body) {
       return 0;
    }
    /* We only accept JSON for content */
    if (!ast_sip_is_content_type(&body->content_type, "application", "json")) {
       ast_debug(2, "Received unsupported content type for Asterisk event on resource '%s'\n",
          ast_sorcery_object_get_id(config));
       return -1;
    }
    json = ast_json_load_buf(body->data, body->len, NULL);
    if (!json) {
       ast_debug(1, "Received unparseable JSON event for resource '%s'\n",
          ast_sorcery_object_get_id(config));
       return -1;
    }
    eid = ast_json_string_get(ast_json_object_get(json, "eid"));
    if (!eid) {
       ast_debug(1, "Received event without eid for resource '%s'\n",
          ast_sorcery_object_get_id(config));
       return -1;
    }
    ast_str_to_eid(&pubsub_eid, eid);
    type = ast_json_string_get(ast_json_object_get(json, "type"));
    if (!type) {
       ast_debug(1, "Received event without type for resource '%s'\n",
          ast_sorcery_object_get_id(config));
       return -1;
    } else if (!strcmp(type, "devicestate")) {
       res = asterisk_publication_devicestate(pub, config, &pubsub_eid, json);
    } else if (!strcmp(type, "refresh")) {
       res = asterisk_publication_devicestate_refresh(pub, config, &pubsub_eid, json);
    }
    return res;
 }
asterisk_publication_mailboxstate()
static int asterisk_publication_mailboxstate (struct ast_sip_publication * pub, struct asterisk_publication_config * config, struct ast_eid * pubsub_eid, struct ast_json * json) static
Definition at line 524 of file res_pjsip_publish_asterisk.c.
References ast_debug, ast_json_integer_get(), ast_json_object_get(), ast_json_string_get(), ast_publish_mwi_state_full(), ast_sorcery_object_get_id(), ast_strdupa, ast_strlen_zero, mailbox, asterisk_publication_config::mailbox_state, asterisk_publication_config::mailbox_state_filter, asterisk_publication_config::mailbox_state_regex, NULL, and strsep().
Referenced by asterisk_publication_mwi_state_change().
 {
    const char *uniqueid = ast_json_string_get(ast_json_object_get(json, "uniqueid"));
    int old_msgs = ast_json_integer_get(ast_json_object_get(json, "old"));
    int new_msgs = ast_json_integer_get(ast_json_object_get(json, "new"));
    char *item_id;
    const char *mailbox;
    if (!config->mailbox_state) {
       ast_debug(2, "Received mailbox state event for resource '%s' but it is not configured to accept them\n",
          ast_sorcery_object_get_id(config));
       return 0;
    }
    if (ast_strlen_zero(uniqueid)) {
       ast_debug(1, "Received incomplete mailbox state event for resource '%s'\n",
          ast_sorcery_object_get_id(config));
       return -1;
    }
    if (config->mailbox_state_filter && regexec(&config->mailbox_state_regex, uniqueid, 0, NULL, 0)) {
       ast_debug(2, "Received mailbox state on resource '%s' for uniqueid '%s' but it has been filtered out\n",
          ast_sorcery_object_get_id(config), uniqueid);
       return 0;
    }
    item_id = ast_strdupa(uniqueid);
    mailbox = strsep(&item_id, "@");
    ast_publish_mwi_state_full(mailbox, item_id, new_msgs, old_msgs, NULL, pubsub_eid);
    return 0;
 }
asterisk_publication_mwi_refresh()
static int asterisk_publication_mwi_refresh (struct ast_sip_publication * pub, struct asterisk_publication_config * config, struct ast_eid * pubsub_eid, struct ast_json * json) static
Definition at line 650 of file res_pjsip_publish_asterisk.c.
References ao2_callback, ao2_ref, ast_log, ast_mwi_state_cache(), ast_sip_publish_client_get(), ast_sip_publish_client_get_datastore(), ast_sorcery_object_get_id(), ast_strlen_zero, cached_mwistate_cb(), asterisk_devicestate_publisher_state::client, LOG_ERROR, asterisk_publication_config::mailboxstate_publish, NULL, OBJ_NODATA, and stasis_cache_dump().
Referenced by asterisk_publication_mwi_state_change().
 {
    struct ast_sip_outbound_publish_client *client;
    struct ast_datastore *datastore;
    struct ao2_container *cached;
    if (ast_strlen_zero(config->mailboxstate_publish)) {
       return 0;
    }
    client = ast_sip_publish_client_get(config->mailboxstate_publish);
    if (!client) {
       ast_log(LOG_ERROR, "Received refresh request for mwi state on publication '%s' but publish '%s' is not available\n",
          ast_sorcery_object_get_id(config), config->mailboxstate_publish);
       return 0;
    }
    datastore = ast_sip_publish_client_get_datastore(client, "asterisk-mwi-publisher");
    if (!datastore) {
       ao2_ref(client, -1);
       return 0;
    }
    cached = stasis_cache_dump(ast_mwi_state_cache(), NULL);
    if (cached) {
       ao2_callback(cached, OBJ_NODATA, cached_mwistate_cb, datastore);
       ao2_ref(cached, -1);
    }
    ao2_ref(client, -1);
    ao2_ref(datastore, -1);
    return 0;
 }
asterisk_publication_mwi_state_change()
static int asterisk_publication_mwi_state_change (struct ast_sip_publication * pub, pjsip_msg_body * body, enum ast_sip_publish_state state) static
Definition at line 685 of file res_pjsip_publish_asterisk.c.
References ao2_cleanup, ast_debug, ast_json_load_buf(), ast_json_object_get(), ast_json_string_get(), ast_json_unref(), ast_sip_get_sorcery(), ast_sip_is_content_type(), ast_sip_publication_get_event_configuration(), ast_sorcery_object_get_id(), ast_sorcery_retrieve_by_id(), ast_str_to_eid(), asterisk_publication_mailboxstate(), asterisk_publication_mwi_refresh(), config, NULL, RAII_VAR, and type.
 {
    RAII_VAR(struct asterisk_publication_config *, config, ast_sorcery_retrieve_by_id(ast_sip_get_sorcery(), "asterisk-publication",
       ast_sip_publication_get_event_configuration(pub)), ao2_cleanup);
    RAII_VAR(struct ast_json *, json, NULL, ast_json_unref);
    const char *eid, *type;
    struct ast_eid pubsub_eid;
    int res = -1;
    /* If no configuration exists for this publication it has most likely been removed, so drop this immediately */
    if (!config) {
       return -1;
    }
    /* If no body exists this is a refresh and can be ignored */
    if (!body) {
       return 0;
    }
    /* We only accept JSON for content */
    if (!ast_sip_is_content_type(&body->content_type, "application", "json")) {
       ast_debug(2, "Received unsupported content type for Asterisk event on resource '%s'\n",
          ast_sorcery_object_get_id(config));
       return -1;
    }
    json = ast_json_load_buf(body->data, body->len, NULL);
    if (!json) {
       ast_debug(1, "Received unparseable JSON event for resource '%s'\n",
          ast_sorcery_object_get_id(config));
       return -1;
    }
    eid = ast_json_string_get(ast_json_object_get(json, "eid"));
    if (!eid) {
       ast_debug(1, "Received event without eid for resource '%s'\n",
          ast_sorcery_object_get_id(config));
       return -1;
    }
    ast_str_to_eid(&pubsub_eid, eid);
    type = ast_json_string_get(ast_json_object_get(json, "type"));
    if (!type) {
       ast_debug(1, "Received event without type for resource '%s'\n",
          ast_sorcery_object_get_id(config));
       return -1;
    } else if (!strcmp(type, "mailboxstate")) {
       res = asterisk_publication_mailboxstate(pub, config, &pubsub_eid, json);
    } else if (!strcmp(type, "refresh")) {
       res = asterisk_publication_mwi_refresh(pub, config, &pubsub_eid, json);
    }
    return res;
 }
asterisk_publication_new()
static int asterisk_publication_new (struct ast_sip_endpoint * endpoint, const char * resource, const char * event_configuration) static
Definition at line 479 of file res_pjsip_publish_asterisk.c.
References ao2_cleanup, ast_sip_get_sorcery(), ast_sorcery_retrieve_by_id(), config, and RAII_VAR.
 {
    RAII_VAR(struct asterisk_publication_config *, config, ast_sorcery_retrieve_by_id(ast_sip_get_sorcery(), "asterisk-publication",
       event_configuration), ao2_cleanup);
    /* If no inbound Asterisk publication configuration exists reject the PUBLISH */
    if (!config) {
       return 404;
    }
    return 200;
 }
asterisk_publication_send_refresh()
static void asterisk_publication_send_refresh (void) static
Internal function to send refresh requests to all publications.
Definition at line 766 of file res_pjsip_publish_asterisk.c.
References ao2_callback, ao2_ref, ast_eid_default, ast_eid_to_str(), ast_json_dump_string, ast_json_free(), ast_json_pack(), ast_json_unref(), AST_RETRIEVE_FLAG_ALL, AST_RETRIEVE_FLAG_MULTIPLE, ast_sip_get_sorcery(), ast_sorcery_retrieve_by_fields(), ast_sip_body::body_text, NULL, OBJ_NODATA, send_refresh_cb(), text, and ast_sip_body::type.
Referenced by load_module(), and reload_module().
 {
    struct ao2_container *publications = ast_sorcery_retrieve_by_fields(ast_sip_get_sorcery(), "asterisk-publication", AST_RETRIEVE_FLAG_MULTIPLE | AST_RETRIEVE_FLAG_ALL, NULL);
    char eid_str[20];
    struct ast_json *json;
    char *text;
    struct ast_sip_body body = {
       .type = "application",
       .subtype = "json",
    };
    if (!publications) {
       return;
    }
    ast_eid_to_str(eid_str, sizeof(eid_str), &ast_eid_default);
    json = ast_json_pack(
       "{ s: s, s: s }",
       "type", "refresh",
       "eid", eid_str);
    if (!json) {
       ao2_ref(publications, -1);
       return;
    }
    text = ast_json_dump_string(json);
    if (!text) {
       ast_json_unref(json);
       ao2_ref(publications, -1);
       return;
    }
    body.body_text = text;
    ao2_callback(publications, OBJ_NODATA, send_refresh_cb, &body);
    ast_json_free(text);
    ast_json_unref(json);
    ao2_ref(publications, -1);
 }
asterisk_publisher_devstate_cb()
static void asterisk_publisher_devstate_cb (void * data, struct stasis_subscription * sub, struct stasis_message * msg) static
Callback function for device state events.
Parameters
ast_event
data void pointer to ast_client structure
Returns
void
Definition at line 173 of file res_pjsip_publish_asterisk.c.
References ast_device_state_message_type(), ast_devstate_str(), ast_eid_cmp(), ast_eid_default, ast_eid_to_str(), ast_json_dump_string, ast_json_free(), ast_json_pack(), ast_json_unref(), ast_sip_publish_client_send(), ast_sip_body::body_text, ast_device_state_message::cachable, asterisk_devicestate_publisher_state::client, ast_datastore::data, ast_device_state_message::device, asterisk_devicestate_publisher_state::device_state_filter, asterisk_devicestate_publisher_state::device_state_regex, ast_device_state_message::eid, NULL, stasis_message_data(), stasis_message_type(), stasis_subscription_is_subscribed(), ast_device_state_message::state, text, and ast_sip_body::type.
Referenced by asterisk_start_devicestate_publishing(), and cached_devstate_cb().
 {
    struct ast_datastore *datastore = data;
    struct asterisk_devicestate_publisher_state *publisher_state = datastore->data;
    struct ast_device_state_message *dev_state;
    char eid_str[20];
    struct ast_json *json;
    char *text;
    struct ast_sip_body body = {
       .type = "application",
       .subtype = "json",
    };
    if (!stasis_subscription_is_subscribed(sub) || ast_device_state_message_type() != stasis_message_type(msg)) {
       return;
    }
    dev_state = stasis_message_data(msg);
    if (!dev_state->eid || ast_eid_cmp(&ast_eid_default, dev_state->eid)) {
       /* If the event is aggregate or didn't originate from this server, don't send it out. */
       return;
    }
    if (publisher_state->device_state_filter && regexec(&publisher_state->device_state_regex, dev_state->device, 0, NULL, 0)) {
       /* Outgoing device state has been filtered and the device name does not match */
       return;
    }
    ast_eid_to_str(eid_str, sizeof(eid_str), &ast_eid_default);
    json = ast_json_pack(
       "{ s: s, s: s, s: s, s: i, s:s }",
       "type", "devicestate",
       "device", dev_state->device,
       "state", ast_devstate_str(dev_state->state),
       "cachable", dev_state->cachable,
       "eid", eid_str);
    if (!json) {
       return;
    }
    text = ast_json_dump_string(json);
    if (!text) {
       ast_json_unref(json);
       return;
    }
    body.body_text = text;
    ast_sip_publish_client_send(publisher_state->client, &body);
    ast_json_free(text);
    ast_json_unref(json);
 }
asterisk_publisher_mwistate_cb()
static void asterisk_publisher_mwistate_cb (void * data, struct stasis_subscription * sub, struct stasis_message * msg) static
Callback function for mailbox state events.
Parameters
ast_event
data void pointer to ast_client structure
Returns
void
Definition at line 232 of file res_pjsip_publish_asterisk.c.
References ast_eid_cmp(), ast_eid_default, ast_eid_to_str(), ast_json_dump_string, ast_json_free(), ast_json_pack(), ast_json_unref(), ast_mwi_state_type(), ast_sip_publish_client_send(), ast_sip_body::body_text, asterisk_mwi_publisher_state::client, ast_datastore::data, ast_mwi_state::eid, asterisk_mwi_publisher_state::mailbox_state_filter, asterisk_mwi_publisher_state::mailbox_state_regex, ast_mwi_state::new_msgs, NULL, ast_mwi_state::old_msgs, stasis_message_data(), stasis_message_type(), stasis_subscription_is_subscribed(), text, ast_sip_body::type, and ast_mwi_state::uniqueid.
Referenced by asterisk_start_mwi_publishing(), and cached_mwistate_cb().
 {
    struct ast_datastore *datastore = data;
    struct asterisk_mwi_publisher_state *publisher_state = datastore->data;
    struct ast_mwi_state *mwi_state;
    char eid_str[20];
    struct ast_json *json;
    char *text;
    struct ast_sip_body body = {
       .type = "application",
       .subtype = "json",
    };
    if (!stasis_subscription_is_subscribed(sub) || ast_mwi_state_type() != stasis_message_type(msg)) {
       return;
    }
    mwi_state = stasis_message_data(msg);
    if (ast_eid_cmp(&ast_eid_default, &mwi_state->eid)) {
       /* If the event is aggregate or didn't originate from this server, don't send it out. */
       return;
    }
    if (publisher_state->mailbox_state_filter && regexec(&publisher_state->mailbox_state_regex, mwi_state->uniqueid, 0, NULL, 0)) {
       /* Outgoing mailbox state has been filtered and the uniqueid does not match */
       return;
    }
    ast_eid_to_str(eid_str, sizeof(eid_str), &ast_eid_default);
    json = ast_json_pack(
       "{ s: s, s: s, s: i, s: i, s:s }",
       "type", "mailboxstate",
       "uniqueid", mwi_state->uniqueid,
       "old", mwi_state->old_msgs,
       "new", mwi_state->new_msgs,
       "eid", eid_str);
    if (!json) {
       return;
    }
    text = ast_json_dump_string(json);
    if (!text) {
       ast_json_unref(json);
       return;
    }
    body.body_text = text;
    ast_sip_publish_client_send(publisher_state->client, &body);
    ast_json_free(text);
    ast_json_unref(json);
 }
asterisk_start_devicestate_publishing()
static int asterisk_start_devicestate_publishing (struct ast_sip_outbound_publish * configuration, struct ast_sip_outbound_publish_client * client) static
Definition at line 322 of file res_pjsip_publish_asterisk.c.
References ao2_bump, ao2_callback, ao2_cleanup, ao2_ref, ast_calloc, ast_device_state_cache(), ast_device_state_message_type(), ast_device_state_topic_all(), ast_sip_publish_client_add_datastore(), ast_sip_publish_client_alloc_datastore(), ast_sip_publish_client_remove_datastore(), ast_sorcery_object_get_extended(), ast_strlen_zero, asterisk_publisher_devstate_cb(), build_regex(), cached_devstate_cb(), asterisk_devicestate_publisher_state::client, asterisk_devicestate_publisher_state::device_state_filter, asterisk_devicestate_publisher_state::device_state_regex, asterisk_devicestate_publisher_state::device_state_subscription, NULL, OBJ_NODATA, RAII_VAR, stasis_cache_dump(), stasis_subscribe, stasis_subscription_accept_message_type(), stasis_subscription_change_type(), STASIS_SUBSCRIPTION_FILTER_SELECTIVE, stasis_subscription_set_filter(), and value.
 {
    RAII_VAR(struct ast_datastore *, datastore, NULL, ao2_cleanup);
    struct asterisk_devicestate_publisher_state *publisher_state;
    const char *value;
    struct ao2_container *cached;
    datastore = ast_sip_publish_client_alloc_datastore(&asterisk_devicestate_publisher_state_datastore,
       "asterisk-devicestate-publisher");
    if (!datastore) {
       return -1;
    }
    publisher_state = ast_calloc(1, sizeof(struct asterisk_devicestate_publisher_state));
    if (!publisher_state) {
       return -1;
    }
    datastore->data = publisher_state;
    value = ast_sorcery_object_get_extended(configuration, "device_state_filter");
    if (!ast_strlen_zero(value)) {
       if (build_regex(&publisher_state->device_state_regex, value)) {
          return -1;
       }
       publisher_state->device_state_filter = 1;
    }
    publisher_state->client = ao2_bump(client);
    if (ast_sip_publish_client_add_datastore(client, datastore)) {
       return -1;
    }
    publisher_state->device_state_subscription = stasis_subscribe(ast_device_state_topic_all(),
       asterisk_publisher_devstate_cb, ao2_bump(datastore));
    if (!publisher_state->device_state_subscription) {
       ast_sip_publish_client_remove_datastore(client, "asterisk-devicestate-publisher");
       ao2_ref(datastore, -1);
       return -1;
    }
    stasis_subscription_accept_message_type(publisher_state->device_state_subscription, ast_device_state_message_type());
    stasis_subscription_accept_message_type(publisher_state->device_state_subscription, stasis_subscription_change_type());
    stasis_subscription_set_filter(publisher_state->device_state_subscription, STASIS_SUBSCRIPTION_FILTER_SELECTIVE);
    cached = stasis_cache_dump(ast_device_state_cache(), NULL);
    ao2_callback(cached, OBJ_NODATA, cached_devstate_cb, datastore);
    ao2_ref(cached, -1);
    return 0;
 }
asterisk_start_mwi_publishing()
static int asterisk_start_mwi_publishing (struct ast_sip_outbound_publish * configuration, struct ast_sip_outbound_publish_client * client) static
Definition at line 401 of file res_pjsip_publish_asterisk.c.
References ao2_bump, ao2_callback, ao2_cleanup, ao2_ref, ast_calloc, ast_mwi_state_cache(), ast_mwi_state_type(), ast_mwi_topic_all(), ast_sip_publish_client_add_datastore(), ast_sip_publish_client_alloc_datastore(), ast_sip_publish_client_remove_datastore(), ast_sorcery_object_get_extended(), ast_strlen_zero, asterisk_publisher_mwistate_cb(), build_regex(), cached_mwistate_cb(), asterisk_mwi_publisher_state::client, asterisk_mwi_publisher_state::mailbox_state_filter, asterisk_mwi_publisher_state::mailbox_state_regex, asterisk_mwi_publisher_state::mailbox_state_subscription, NULL, OBJ_NODATA, RAII_VAR, stasis_cache_dump(), stasis_subscribe, stasis_subscription_accept_message_type(), stasis_subscription_change_type(), STASIS_SUBSCRIPTION_FILTER_SELECTIVE, stasis_subscription_set_filter(), and value.
 {
    RAII_VAR(struct ast_datastore *, datastore, NULL, ao2_cleanup);
    struct asterisk_mwi_publisher_state *publisher_state;
    const char *value;
    struct ao2_container *cached;
    datastore = ast_sip_publish_client_alloc_datastore(&asterisk_mwi_publisher_state_datastore, "asterisk-mwi-publisher");
    if (!datastore) {
       return -1;
    }
    publisher_state = ast_calloc(1, sizeof(struct asterisk_mwi_publisher_state));
    if (!publisher_state) {
       return -1;
    }
    datastore->data = publisher_state;
    value = ast_sorcery_object_get_extended(configuration, "mailbox_state_filter");
    if (!ast_strlen_zero(value)) {
       if (build_regex(&publisher_state->mailbox_state_regex, value)) {
          return -1;
       }
       publisher_state->mailbox_state_filter = 1;
    }
    publisher_state->client = ao2_bump(client);
    if (ast_sip_publish_client_add_datastore(client, datastore)) {
       return -1;
    }
    publisher_state->mailbox_state_subscription = stasis_subscribe(ast_mwi_topic_all(),
       asterisk_publisher_mwistate_cb, ao2_bump(datastore));
    if (!publisher_state->mailbox_state_subscription) {
       ast_sip_publish_client_remove_datastore(client, "asterisk-mwi-publisher");
       ao2_ref(datastore, -1);
       return -1;
    }
    stasis_subscription_accept_message_type(publisher_state->mailbox_state_subscription, ast_mwi_state_type());
    stasis_subscription_accept_message_type(publisher_state->mailbox_state_subscription, stasis_subscription_change_type());
    stasis_subscription_set_filter(publisher_state->mailbox_state_subscription, STASIS_SUBSCRIPTION_FILTER_SELECTIVE);
    cached = stasis_cache_dump(ast_mwi_state_cache(), NULL);
    ao2_callback(cached, OBJ_NODATA, cached_mwistate_cb, datastore);
    ao2_ref(cached, -1);
    return 0;
 }
asterisk_stop_devicestate_publishing()
static int asterisk_stop_devicestate_publishing (struct ast_sip_outbound_publish_client * client) static
Definition at line 374 of file res_pjsip_publish_asterisk.c.
References ao2_cleanup, ao2_ref, ast_sip_publish_client_get_datastore(), ast_sip_publish_client_remove_datastore(), asterisk_devicestate_publisher_state::device_state_subscription, RAII_VAR, and stasis_unsubscribe_and_join().
 {
    RAII_VAR(struct ast_datastore *, datastore, ast_sip_publish_client_get_datastore(client, "asterisk-devicestate-publisher"),
       ao2_cleanup);
    struct asterisk_devicestate_publisher_state *publisher_state;
    if (!datastore) {
       return 0;
    }
    publisher_state = datastore->data;
    if (publisher_state->device_state_subscription) {
       stasis_unsubscribe_and_join(publisher_state->device_state_subscription);
       ao2_ref(datastore, -1);
    }
    ast_sip_publish_client_remove_datastore(client, "asterisk-devicestate-publisher");
    return 0;
 }
asterisk_stop_mwi_publishing()
static int asterisk_stop_mwi_publishing (struct ast_sip_outbound_publish_client * client) static
Definition at line 452 of file res_pjsip_publish_asterisk.c.
References ao2_cleanup, ao2_ref, ast_sip_publish_client_get_datastore(), ast_sip_publish_client_remove_datastore(), asterisk_mwi_publisher_state::mailbox_state_subscription, RAII_VAR, and stasis_unsubscribe_and_join().
 {
    RAII_VAR(struct ast_datastore *, datastore, ast_sip_publish_client_get_datastore(client, "asterisk-mwi-publisher"),
       ao2_cleanup);
    struct asterisk_mwi_publisher_state *publisher_state;
    if (!datastore) {
       return 0;
    }
    publisher_state = datastore->data;
    if (publisher_state->mailbox_state_subscription) {
       stasis_unsubscribe_and_join(publisher_state->mailbox_state_subscription);
       ao2_ref(datastore, -1);
    }
    ast_sip_publish_client_remove_datastore(client, "asterisk-mwi-publisher");
    return 0;
 }
build_regex()
static int build_regex (regex_t * regex, const char * text) static
Definition at line 307 of file res_pjsip_publish_asterisk.c.
References ast_log, buf, len(), LOG_ERROR, and NULL.
Referenced by asterisk_start_devicestate_publishing(), asterisk_start_mwi_publishing(), and regex_filter_handler().
 {
    int res;
    if ((res = regcomp(regex, text, REG_EXTENDED | REG_ICASE | REG_NOSUB))) {
       size_t len = regerror(res, regex, NULL, 0);
       char buf[len];
       regerror(res, regex, buf, len);
       ast_log(LOG_ERROR, "Could not compile regex '%s': %s\n", text, buf);
       return -1;
    }
    return 0;
 }
cached_devstate_cb()
static int cached_devstate_cb (void * obj, void * arg, int flags) static
Definition at line 285 of file res_pjsip_publish_asterisk.c.
References asterisk_publisher_devstate_cb(), ast_datastore::data, and asterisk_devicestate_publisher_state::device_state_subscription.
Referenced by asterisk_publication_devicestate_refresh(), and asterisk_start_devicestate_publishing().
 {
    struct stasis_message *msg = obj;
    struct ast_datastore *datastore = arg;
    struct asterisk_devicestate_publisher_state *publisher_state = datastore->data;
    asterisk_publisher_devstate_cb(arg, publisher_state->device_state_subscription, msg);
    return 0;
 }
cached_mwistate_cb()
static int cached_mwistate_cb (void * obj, void * arg, int flags) static
Definition at line 296 of file res_pjsip_publish_asterisk.c.
References asterisk_publisher_mwistate_cb(), ast_datastore::data, and asterisk_mwi_publisher_state::mailbox_state_subscription.
Referenced by asterisk_publication_mwi_refresh(), and asterisk_start_mwi_publishing().
 {
    struct stasis_message *msg = obj;
    struct ast_datastore *datastore = arg;
    struct asterisk_mwi_publisher_state *publisher_state = datastore->data;
    asterisk_publisher_mwistate_cb(arg, publisher_state->mailbox_state_subscription, msg);
    return 0;
 }
load_module()
static int load_module (void) static
Definition at line 862 of file res_pjsip_publish_asterisk.c.
References ast_eid_default, ast_eid_is_empty(), ast_log, AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, ast_sip_get_sorcery(), ast_sip_register_event_publisher_handler(), ast_sip_register_publish_handler(), ast_sip_unregister_event_publisher_handler(), ast_sip_unregister_publish_handler(), ast_sorcery_apply_config, ast_sorcery_apply_default, ast_sorcery_object_field_register, ast_sorcery_object_field_register_custom, ast_sorcery_object_register, ast_sorcery_reload_object(), asterisk_publication_config_alloc(), asterisk_publication_send_refresh(), asterisk_publication_config::device_state, asterisk_publication_config::devicestate_publish, ast_sip_event_publisher_handler::event_name, ast_sip_publish_handler::event_name, FLDSET, LOG_ERROR, LOG_WARNING, asterisk_publication_config::mailbox_state, asterisk_publication_config::mailboxstate_publish, NULL, OPT_BOOL_T, OPT_NOOP_T, OPT_STRINGFIELD_T, regex_filter_handler(), and STRFLDSET.
Referenced by unload_module().
 {
    if (ast_eid_is_empty(&ast_eid_default)) {
       ast_log(LOG_ERROR, "Entity ID is not set.\n");
       return AST_MODULE_LOAD_DECLINE;
    }
    ast_sorcery_apply_config(ast_sip_get_sorcery(), "res_pjsip_publish_asterisk");
    ast_sorcery_apply_default(ast_sip_get_sorcery(), "asterisk-publication", "config", "pjsip.conf,criteria=type=asterisk-publication");
    if (ast_sorcery_object_register(ast_sip_get_sorcery(), "asterisk-publication", asterisk_publication_config_alloc, NULL, NULL)) {
       ast_log(LOG_ERROR, "Unable to register 'asterisk-publication' type with sorcery\n");
       return AST_MODULE_LOAD_DECLINE;
    }
    ast_sorcery_object_field_register(ast_sip_get_sorcery(), "asterisk-publication", "type", "", OPT_NOOP_T, 0, 0);
    ast_sorcery_object_field_register(ast_sip_get_sorcery(), "asterisk-publication", "devicestate_publish", "", OPT_STRINGFIELD_T, 0, STRFLDSET(struct asterisk_publication_config, devicestate_publish));
    ast_sorcery_object_field_register(ast_sip_get_sorcery(), "asterisk-publication", "mailboxstate_publish", "", OPT_STRINGFIELD_T, 0, STRFLDSET(struct asterisk_publication_config, mailboxstate_publish));
    ast_sorcery_object_field_register(ast_sip_get_sorcery(), "asterisk-publication", "device_state", "no", OPT_BOOL_T, 1, FLDSET(struct asterisk_publication_config, device_state));
    ast_sorcery_object_field_register_custom(ast_sip_get_sorcery(), "asterisk-publication", "device_state_filter", "", regex_filter_handler, NULL, NULL, 0, 0);
    ast_sorcery_object_field_register(ast_sip_get_sorcery(), "asterisk-publication", "mailbox_state", "no", OPT_BOOL_T, 1, FLDSET(struct asterisk_publication_config, mailbox_state));
    ast_sorcery_object_field_register_custom(ast_sip_get_sorcery(), "asterisk-publication", "mailbox_state_filter", "", regex_filter_handler, NULL, NULL, 0, 0);
    ast_sorcery_reload_object(ast_sip_get_sorcery(), "asterisk-publication");
    if (ast_sip_register_publish_handler(&asterisk_devicestate_publication_handler)) {
       ast_log(LOG_WARNING, "Unable to register event publication handler %s\n",
          asterisk_devicestate_publication_handler.event_name);
       return AST_MODULE_LOAD_DECLINE;
    }
    if (ast_sip_register_publish_handler(&asterisk_mwi_publication_handler)) {
       ast_log(LOG_WARNING, "Unable to register event publication handler %s\n",
          asterisk_mwi_publication_handler.event_name);
       ast_sip_unregister_publish_handler(&asterisk_devicestate_publication_handler);
       return AST_MODULE_LOAD_DECLINE;
    }
    if (ast_sip_register_event_publisher_handler(&asterisk_devicestate_publisher_handler)) {
       ast_log(LOG_WARNING, "Unable to register event publisher handler %s\n",
          asterisk_devicestate_publisher_handler.event_name);
       ast_sip_unregister_publish_handler(&asterisk_devicestate_publication_handler);
       ast_sip_unregister_publish_handler(&asterisk_mwi_publication_handler);
       return AST_MODULE_LOAD_DECLINE;
    }
    if (ast_sip_register_event_publisher_handler(&asterisk_mwi_publisher_handler)) {
       ast_log(LOG_WARNING, "Unable to register event publisher handler %s\n",
          asterisk_mwi_publisher_handler.event_name);
       ast_sip_unregister_event_publisher_handler(&asterisk_mwi_publisher_handler);
       ast_sip_unregister_publish_handler(&asterisk_devicestate_publication_handler);
       ast_sip_unregister_publish_handler(&asterisk_mwi_publication_handler);
       return AST_MODULE_LOAD_DECLINE;
    }
    asterisk_publication_send_refresh();
    return AST_MODULE_LOAD_SUCCESS;
 }
regex_filter_handler()
static int regex_filter_handler (const struct aco_option * opt, struct ast_variable * var, void * obj) static
Definition at line 840 of file res_pjsip_publish_asterisk.c.
References ast_strlen_zero, build_regex(), config, asterisk_publication_config::device_state_filter, asterisk_publication_config::device_state_regex, asterisk_publication_config::mailbox_state_filter, asterisk_publication_config::mailbox_state_regex, ast_variable::name, and ast_variable::value.
Referenced by load_module().
 {
    struct asterisk_publication_config *config = obj;
    int res = -1;
    if (ast_strlen_zero(var->value)) {
       return 0;
    }
    if (!strcmp(var->name, "device_state_filter")) {
       if (!(res = build_regex(&config->device_state_regex, var->value))) {
          config->device_state_filter = 1;
       }
    } else if (!strcmp(var->name, "mailbox_state_filter")) {
       if (!(res = build_regex(&config->mailbox_state_regex, var->value))) {
          config->mailbox_state_filter = 1;
       }
    }
    return res;
 }
reload_module()
static int reload_module (void) static
Definition at line 918 of file res_pjsip_publish_asterisk.c.
References ast_sip_get_sorcery(), ast_sorcery_reload_object(), and asterisk_publication_send_refresh().
Referenced by unload_module().
 {
    ast_sorcery_reload_object(ast_sip_get_sorcery(), "asterisk-publication");
    asterisk_publication_send_refresh();
    return 0;
 }
send_refresh_cb()
static int send_refresh_cb (void * obj, void * arg, int flags) static
Definition at line 741 of file res_pjsip_publish_asterisk.c.
References ao2_ref, ast_sip_publish_client_get(), ast_sip_publish_client_send(), ast_strlen_zero, asterisk_devicestate_publisher_state::client, config, asterisk_publication_config::devicestate_publish, and asterisk_publication_config::mailboxstate_publish.
Referenced by asterisk_publication_send_refresh().
 {
    struct asterisk_publication_config *config = obj;
    struct ast_sip_outbound_publish_client *client;
    if (!ast_strlen_zero(config->devicestate_publish)) {
       client = ast_sip_publish_client_get(config->devicestate_publish);
       if (client) {
          ast_sip_publish_client_send(client, arg);
          ao2_ref(client, -1);
       }
    }
    if (!ast_strlen_zero(config->mailboxstate_publish)) {
       client = ast_sip_publish_client_get(config->mailboxstate_publish);
       if (client) {
          ast_sip_publish_client_send(client, arg);
          ao2_ref(client, -1);
       }
    }
    return 0;
 }
unload_module()
static int unload_module (void) static
Definition at line 925 of file res_pjsip_publish_asterisk.c.
References AST_MODFLAG_LOAD_ORDER, AST_MODPRI_CHANNEL_DEPEND, AST_MODULE_INFO(), AST_MODULE_SUPPORT_CORE, ast_sip_get_sorcery(), ast_sip_unregister_event_publisher_handler(), ast_sip_unregister_publish_handler(), ast_sorcery_object_unregister(), ASTERISK_GPL_KEY, load_module(), reload(), and reload_module().
 {
    ast_sip_unregister_publish_handler(&asterisk_devicestate_publication_handler);
    ast_sip_unregister_publish_handler(&asterisk_mwi_publication_handler);
    ast_sip_unregister_event_publisher_handler(&asterisk_devicestate_publisher_handler);
    ast_sip_unregister_event_publisher_handler(&asterisk_mwi_publisher_handler);
    ast_sorcery_object_unregister(ast_sip_get_sorcery(), "asterisk-publication");
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "PJSIP Asterisk Event PUBLISH Support" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .reload = reload_module, .unload = unload_module, .load_pri = AST_MODPRI_CHANNEL_DEPEND + 5, .requires = "res_pjsip,res_pjsip_outbound_publish,res_pjsip_pubsub", } static
Definition at line 942 of file res_pjsip_publish_asterisk.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 942 of file res_pjsip_publish_asterisk.c.
asterisk_devicestate_publication_handler
struct ast_sip_publish_handler asterisk_devicestate_publication_handler
Initial value:
= {
   .event_name = "asterisk-devicestate",
   .new_publication = asterisk_publication_new,
   .publication_state_change = asterisk_publication_devicestate_state_change,
}
Definition at line 806 of file res_pjsip_publish_asterisk.c.
asterisk_devicestate_publisher_handler
struct ast_sip_event_publisher_handler asterisk_devicestate_publisher_handler
Initial value:
= {
   .event_name = "asterisk-devicestate",
   .start_publishing = asterisk_start_devicestate_publishing,
   .stop_publishing = asterisk_stop_devicestate_publishing,
}
Definition at line 395 of file res_pjsip_publish_asterisk.c.
asterisk_devicestate_publisher_state_datastore
const struct ast_datastore_info asterisk_devicestate_publisher_state_datastore static
Initial value:
= {
   .type = "asterisk-devicestate-publisher",
   .destroy = asterisk_devicestate_publisher_state_destroy,
}
Datastore for attaching devicestate publisher state information.
Definition at line 144 of file res_pjsip_publish_asterisk.c.
asterisk_mwi_publication_handler
struct ast_sip_publish_handler asterisk_mwi_publication_handler
Initial value:
= {
   .event_name = "asterisk-mwi",
   .new_publication = asterisk_publication_new,
   .publication_state_change = asterisk_publication_mwi_state_change,
}
Definition at line 812 of file res_pjsip_publish_asterisk.c.
asterisk_mwi_publisher_handler
struct ast_sip_event_publisher_handler asterisk_mwi_publisher_handler
Initial value:
= {
   .event_name = "asterisk-mwi",
   .start_publishing = asterisk_start_mwi_publishing,
   .stop_publishing = asterisk_stop_mwi_publishing,
}
Definition at line 473 of file res_pjsip_publish_asterisk.c.
asterisk_mwi_publisher_state_datastore
const struct ast_datastore_info asterisk_mwi_publisher_state_datastore static
Initial value:
= {
   .type = "asterisk-mwi-publisher",
   .destroy = asterisk_mwi_publisher_state_destroy,
}
Datastore for attaching devicestate publisher state information.
Definition at line 162 of file res_pjsip_publish_asterisk.c.