Asterisk - The Open Source Telephony Project: resource_mailboxes.h File Reference
resource_mailboxes.h File Reference
Generated file - declares stubs to be implemented in res/ari/resource_mailboxes.c.
#include "asterisk/ari.h"
Data Structures
struct ast_ari_mailboxes_delete_args
struct ast_ari_mailboxes_get_args
struct ast_ari_mailboxes_list_args
struct ast_ari_mailboxes_update_args
Functions
void ast_ari_mailboxes_delete (struct ast_variable *headers, struct ast_ari_mailboxes_delete_args *args, struct ast_ari_response *response)
Destroy a mailbox.
void ast_ari_mailboxes_get (struct ast_variable *headers, struct ast_ari_mailboxes_get_args *args, struct ast_ari_response *response)
Retrieve the current state of a mailbox.
void ast_ari_mailboxes_list (struct ast_variable *headers, struct ast_ari_mailboxes_list_args *args, struct ast_ari_response *response)
List all mailboxes.
void ast_ari_mailboxes_update (struct ast_variable *headers, struct ast_ari_mailboxes_update_args *args, struct ast_ari_response *response)
Change the state of a mailbox. (Note - implicitly creates the mailbox).
int ast_ari_mailboxes_update_parse_body (struct ast_json *body, struct ast_ari_mailboxes_update_args *args)
Body parsing function for /mailboxes/{mailboxName}.
Detailed Description
Generated file - declares stubs to be implemented in res/ari/resource_mailboxes.c.
Mailboxes resources
Author
Jonathan Rose jrose.nosp@m.@dig.nosp@m.ium.c.nosp@m.om
Definition in file resource_mailboxes.h.
Function Documentation
ast_ari_mailboxes_delete()
void ast_ari_mailboxes_delete (struct ast_variable * headers, struct ast_ari_mailboxes_delete_args * args, struct ast_ari_response * response)
Destroy a mailbox.
Parameters
headers HTTP headers
args Swagger parameters
[out] response HTTP response
Definition at line 79 of file resource_mailboxes.c.
References ast_ari_response_error(), ast_ari_response_no_content(), ast_ari_mailboxes_delete_args::mailbox_name, stasis_app_mailbox_delete(), STASIS_MAILBOX_ERROR, STASIS_MAILBOX_MISSING, and STASIS_MAILBOX_OK.
Referenced by ast_ari_mailboxes_delete_cb().
 {
    switch (stasis_app_mailbox_delete(args->mailbox_name)) {
    case STASIS_MAILBOX_MISSING:
       ast_ari_response_error(response, 404,
          "Not Found", "Mailbox does not exist");
       return;
    case STASIS_MAILBOX_ERROR:
       ast_ari_response_error(response, 500,
          "INternal Server Error", "Failed to delete the mailbox");
       return;
    case STASIS_MAILBOX_OK:
       ast_ari_response_no_content(response);
    }
 }
ast_ari_mailboxes_get()
void ast_ari_mailboxes_get (struct ast_variable * headers, struct ast_ari_mailboxes_get_args * args, struct ast_ari_response * response)
Retrieve the current state of a mailbox.
Parameters
headers HTTP headers
args Swagger parameters
[out] response HTTP response
Definition at line 49 of file resource_mailboxes.c.
References ast_ari_response_error(), ast_ari_response_ok(), ast_ari_mailboxes_get_args::mailbox_name, stasis_app_mailbox_to_json(), STASIS_MAILBOX_ERROR, STASIS_MAILBOX_MISSING, and STASIS_MAILBOX_OK.
Referenced by ast_ari_mailboxes_get_cb().
 {
    struct ast_json *json;
    switch (stasis_app_mailbox_to_json(args->mailbox_name, &json)) {
    case STASIS_MAILBOX_MISSING:
       ast_ari_response_error(response, 404,
          "Not Found", "Mailbox is does not exist");
       return;
    case STASIS_MAILBOX_ERROR:
       ast_ari_response_error(response, 500,
          "Internal Server Error", "Error building response");
       return;
    case STASIS_MAILBOX_OK:
       ast_ari_response_ok(response, json);
    }
 }
ast_ari_mailboxes_list()
void ast_ari_mailboxes_list (struct ast_variable * headers, struct ast_ari_mailboxes_list_args * args, struct ast_ari_response * response)
List all mailboxes.
Parameters
headers HTTP headers
args Swagger parameters
[out] response HTTP response
Definition at line 35 of file resource_mailboxes.c.
References ast_ari_response_error(), ast_ari_response_ok(), and stasis_app_mailboxes_to_json().
Referenced by ast_ari_mailboxes_list_cb().
 {
    struct ast_json *json;
    if (!(json = stasis_app_mailboxes_to_json())) {
       ast_ari_response_error(response, 500,
          "Internal Server Error", "Error building response");
       return;
    }
    ast_ari_response_ok(response, json);
 }
ast_ari_mailboxes_update()
void ast_ari_mailboxes_update (struct ast_variable * headers, struct ast_ari_mailboxes_update_args * args, struct ast_ari_response * response)
Change the state of a mailbox. (Note - implicitly creates the mailbox).
Parameters
headers HTTP headers
args Swagger parameters
[out] response HTTP response
Definition at line 68 of file resource_mailboxes.c.
References ast_ari_response_error(), ast_ari_response_no_content(), ast_ari_mailboxes_update_args::mailbox_name, ast_ari_mailboxes_update_args::new_messages, ast_ari_mailboxes_update_args::old_messages, and stasis_app_mailbox_update().
Referenced by ast_ari_mailboxes_update_cb().
 {
    if (stasis_app_mailbox_update(args->mailbox_name, args->old_messages, args->new_messages)) {
       ast_ari_response_error(response, 500, "Internal Server Error", "Error updating mailbox");
       return;
    }
    ast_ari_response_no_content(response);
 }
ast_ari_mailboxes_update_parse_body()
int ast_ari_mailboxes_update_parse_body (struct ast_json * body, struct ast_ari_mailboxes_update_args * args)
Body parsing function for /mailboxes/{mailboxName}.
Parameters
body The JSON body from which to parse parameters.
[out] args The args structure to parse into.
Return values
zero on success
non-zero on failure
Definition at line 162 of file res_ari_mailboxes.c.
References ast_json_integer_get(), ast_json_object_get(), ast_ari_mailboxes_update_args::new_messages, and ast_ari_mailboxes_update_args::old_messages.
Referenced by ast_ari_mailboxes_update_cb().
 {
    struct ast_json *field;
    /* Parse query parameters out of it */
    field = ast_json_object_get(body, "oldMessages");
    if (field) {
       args->old_messages = ast_json_integer_get(field);
    }
    field = ast_json_object_get(body, "newMessages");
    if (field) {
       args->new_messages = ast_json_integer_get(field);
    }
    return 0;
 }