Asterisk - The Open Source Telephony Project: stasis_system.c File Reference
stasis_system.c File Reference
Stasis Messages and Data Types for System events.
#include "asterisk.h"
#include "asterisk/astobj2.h"
#include "asterisk/stasis.h"
#include "asterisk/stasis_system.h"
Functions
int ast_stasis_system_init (void)
Initialize the system level items for Stasis Message Bus API.
void ast_system_publish_registry (const char *channeltype, const char *username, const char *domain, const char *status, const char *cause)
Publish a channel driver outgoing registration message.
struct stasis_topic * ast_system_topic (void)
A Stasis Message Bus API topic which publishes messages regarding system changes.
static struct ast_manager_event_blob * cc_available_to_ami (struct stasis_message *message)
static struct ast_manager_event_blob * cc_callerrecalling_to_ami (struct stasis_message *message)
static struct ast_manager_event_blob * cc_callerstartmonitoring_to_ami (struct stasis_message *message)
static struct ast_manager_event_blob * cc_callerstopmonitoring_to_ami (struct stasis_message *message)
static struct ast_manager_event_blob * cc_failure_to_ami (struct stasis_message *message)
static struct ast_manager_event_blob * cc_monitorfailed_to_ami (struct stasis_message *message)
static struct ast_manager_event_blob * cc_offertimerstart_to_ami (struct stasis_message *message)
static struct ast_manager_event_blob * cc_recallcomplete_to_ami (struct stasis_message *message)
static struct ast_manager_event_blob * cc_requestacknowledged_to_ami (struct stasis_message *message)
static struct ast_manager_event_blob * cc_requested_to_ami (struct stasis_message *message)
STASIS_MESSAGE_TYPE_DEFN (ast_network_change_type)
STASIS_MESSAGE_TYPE_DEFN (ast_system_registry_type,.to_ami=system_registry_to_ami,)
STASIS_MESSAGE_TYPE_DEFN (ast_cc_available_type,.to_ami=cc_available_to_ami,)
STASIS_MESSAGE_TYPE_DEFN (ast_cc_offertimerstart_type,.to_ami=cc_offertimerstart_to_ami,)
STASIS_MESSAGE_TYPE_DEFN (ast_cc_requested_type,.to_ami=cc_requested_to_ami,)
STASIS_MESSAGE_TYPE_DEFN (ast_cc_requestacknowledged_type,.to_ami=cc_requestacknowledged_to_ami,)
STASIS_MESSAGE_TYPE_DEFN (ast_cc_callerstopmonitoring_type,.to_ami=cc_callerstopmonitoring_to_ami,)
STASIS_MESSAGE_TYPE_DEFN (ast_cc_callerstartmonitoring_type,.to_ami=cc_callerstartmonitoring_to_ami,)
STASIS_MESSAGE_TYPE_DEFN (ast_cc_callerrecalling_type,.to_ami=cc_callerrecalling_to_ami,)
STASIS_MESSAGE_TYPE_DEFN (ast_cc_recallcomplete_type,.to_ami=cc_recallcomplete_to_ami,)
STASIS_MESSAGE_TYPE_DEFN (ast_cc_failure_type,.to_ami=cc_failure_to_ami,)
STASIS_MESSAGE_TYPE_DEFN (ast_cc_monitorfailed_type,.to_ami=cc_monitorfailed_to_ami,)
STASIS_MESSAGE_TYPE_DEFN (ast_cluster_discovery_type)
static void stasis_system_cleanup (void)
Cleanup the Stasis Message Bus API system level items.
static struct ast_manager_event_blob * system_registry_to_ami (struct stasis_message *message)
Variables
static struct stasis_topic * system_topic
The Stasis Message Bus API topic for system level changes.
Detailed Description
Stasis Messages and Data Types for System events.
Author
Jason Parker jpark.nosp@m.er@d.nosp@m.igium.nosp@m..com
Definition in file stasis_system.c.
Function Documentation
ast_stasis_system_init()
int ast_stasis_system_init (void)
Initialize the system level items for Stasis Message Bus API.
Initialize the stasis system topic and message types.
Definition at line 373 of file stasis_system.c.
References ast_cc_available_type(), ast_cc_callerrecalling_type(), ast_cc_callerstartmonitoring_type(), ast_cc_callerstopmonitoring_type(), ast_cc_failure_type(), ast_cc_monitorfailed_type(), ast_cc_offertimerstart_type(), ast_cc_recallcomplete_type(), ast_cc_requestacknowledged_type(), ast_cc_requested_type(), ast_cluster_discovery_type(), ast_network_change_type(), ast_register_cleanup(), ast_system_registry_type(), STASIS_MESSAGE_TYPE_INIT, stasis_system_cleanup(), and stasis_topic_create().
Referenced by asterisk_daemon().
 {
    ast_register_cleanup(stasis_system_cleanup);
    system_topic = stasis_topic_create("system:all");
    if (!system_topic) {
       return 1;
    }
    if (STASIS_MESSAGE_TYPE_INIT(ast_network_change_type) != 0) {
       return -1;
    }
    if (STASIS_MESSAGE_TYPE_INIT(ast_system_registry_type) != 0) {
       return -1;
    }
    if (STASIS_MESSAGE_TYPE_INIT(ast_cc_available_type) != 0) {
       return -1;
    }
    if (STASIS_MESSAGE_TYPE_INIT(ast_cc_offertimerstart_type) != 0) {
       return -1;
    }
    if (STASIS_MESSAGE_TYPE_INIT(ast_cc_requested_type) != 0) {
       return -1;
    }
    if (STASIS_MESSAGE_TYPE_INIT(ast_cc_requestacknowledged_type) != 0) {
       return -1;
    }
    if (STASIS_MESSAGE_TYPE_INIT(ast_cc_callerstopmonitoring_type) != 0) {
       return -1;
    }
    if (STASIS_MESSAGE_TYPE_INIT(ast_cc_callerstartmonitoring_type) != 0) {
       return -1;
    }
    if (STASIS_MESSAGE_TYPE_INIT(ast_cc_callerrecalling_type) != 0) {
       return -1;
    }
    if (STASIS_MESSAGE_TYPE_INIT(ast_cc_recallcomplete_type) != 0) {
       return -1;
    }
    if (STASIS_MESSAGE_TYPE_INIT(ast_cc_failure_type) != 0) {
       return -1;
    }
    if (STASIS_MESSAGE_TYPE_INIT(ast_cc_monitorfailed_type) != 0) {
       return -1;
    }
    if (STASIS_MESSAGE_TYPE_INIT(ast_cluster_discovery_type) != 0) {
       return -1;
    }
    return 0;
 }
ast_system_publish_registry()
void ast_system_publish_registry (const char * channeltype, const char * username, const char * domain, const char * status, const char * cause)
Publish a channel driver outgoing registration message.
Since
12
Parameters
channeltype The channel driver that published the message
username The username that was used to register
domain The domain that was used to register
status The result of the registration
cause The reason for the result
Definition at line 118 of file stasis_system.c.
References ao2_ref, ast_json_pack(), ast_json_payload_create(), ast_json_unref(), ast_system_registry_type(), ast_system_topic(), S_OR, stasis_message_create(), and stasis_publish().
Referenced by handle_registration_response(), iax2_publish_registry(), and sip_publish_registry().
 {
    struct ast_json *registry;
    struct ast_json_payload *payload;
    struct stasis_message *message;
    if (!ast_system_registry_type()) {
       return;
    }
    registry = ast_json_pack("{s: s, s: s, s: s, s: s, s: s, s: s}",
       "type", "registry",
       "channeltype", channeltype,
       "username", username,
       "domain", domain,
       "status", status,
       "cause", S_OR(cause, ""));
    payload = ast_json_payload_create(registry);
    ast_json_unref(registry);
    if (!payload) {
       return;
    }
    message = stasis_message_create(ast_system_registry_type(), payload);
    ao2_ref(payload, -1);
    if (!message) {
       return;
    }
    stasis_publish(ast_system_topic(), message);
    ao2_ref(message, -1);
 }
ast_system_topic()
struct stasis_topic* ast_system_topic (void)
A Stasis Message Bus API topic which publishes messages regarding system changes.
Since
12
Return values
Definition at line 347 of file stasis_system.c.
References system_topic.
Referenced by ast_system_publish_registry(), cc_publish(), load_module(), manager_system_init(), network_change_stasis_subscribe(), pjsip_outbound_registration_metrics_init(), publish_cluster_discovery_to_stasis_full(), publish_format_update(), and stun_monitor_request().
 {
    return system_topic;
 }
cc_available_to_ami()
static struct ast_manager_event_blob * cc_available_to_ami (struct stasis_message * message) static
Definition at line 185 of file stasis_system.c.
References ast_json_integer_get(), ast_json_object_get(), ast_json_string_get(), ast_manager_event_blob_create(), EVENT_FLAG_CC, ast_json_payload::json, service, and stasis_message_data().
 {
    struct ast_json_payload *payload = stasis_message_data(message);
    int core_id;
    const char *callee;
    const char *service;
    core_id = ast_json_integer_get(ast_json_object_get(payload->json, "core_id"));
    callee = ast_json_string_get(ast_json_object_get(payload->json, "callee"));
    service = ast_json_string_get(ast_json_object_get(payload->json, "service"));
    return ast_manager_event_blob_create(EVENT_FLAG_CC, "CCAvailable",
       "CoreID: %d\r\n"
       "Callee: %s\r\n"
       "Service: %s\r\n",
       core_id, callee, service);
 }
cc_callerrecalling_to_ami()
static struct ast_manager_event_blob * cc_callerrecalling_to_ami (struct stasis_message * message) static
Definition at line 284 of file stasis_system.c.
References ast_json_integer_get(), ast_json_object_get(), ast_json_string_get(), ast_manager_event_blob_create(), EVENT_FLAG_CC, ast_json_payload::json, and stasis_message_data().
 {
    struct ast_json_payload *payload = stasis_message_data(message);
    int core_id;
    const char *caller;
    core_id = ast_json_integer_get(ast_json_object_get(payload->json, "core_id"));
    caller = ast_json_string_get(ast_json_object_get(payload->json, "caller"));
    return ast_manager_event_blob_create(EVENT_FLAG_CC, "CCCallerRecalling",
       "CoreID: %d\r\n"
       "Caller: %s\r\n",
       core_id, caller);
 }
cc_callerstartmonitoring_to_ami()
static struct ast_manager_event_blob * cc_callerstartmonitoring_to_ami (struct stasis_message * message) static
Definition at line 269 of file stasis_system.c.
References ast_json_integer_get(), ast_json_object_get(), ast_json_string_get(), ast_manager_event_blob_create(), EVENT_FLAG_CC, ast_json_payload::json, and stasis_message_data().
 {
    struct ast_json_payload *payload = stasis_message_data(message);
    int core_id;
    const char *caller;
    core_id = ast_json_integer_get(ast_json_object_get(payload->json, "core_id"));
    caller = ast_json_string_get(ast_json_object_get(payload->json, "caller"));
    return ast_manager_event_blob_create(EVENT_FLAG_CC, "CCCallerStartMonitoring",
       "CoreID: %d\r\n"
       "Caller: %s\r\n",
       core_id, caller);
 }
cc_callerstopmonitoring_to_ami()
static struct ast_manager_event_blob * cc_callerstopmonitoring_to_ami (struct stasis_message * message) static
Definition at line 254 of file stasis_system.c.
References ast_json_integer_get(), ast_json_object_get(), ast_json_string_get(), ast_manager_event_blob_create(), EVENT_FLAG_CC, ast_json_payload::json, and stasis_message_data().
 {
    struct ast_json_payload *payload = stasis_message_data(message);
    int core_id;
    const char *caller;
    core_id = ast_json_integer_get(ast_json_object_get(payload->json, "core_id"));
    caller = ast_json_string_get(ast_json_object_get(payload->json, "caller"));
    return ast_manager_event_blob_create(EVENT_FLAG_CC, "CCCallerStopMonitoring",
       "CoreID: %d\r\n"
       "Caller: %s\r\n",
       core_id, caller);
 }
cc_failure_to_ami()
static struct ast_manager_event_blob * cc_failure_to_ami (struct stasis_message * message) static
Definition at line 314 of file stasis_system.c.
References ast_json_integer_get(), ast_json_object_get(), ast_json_string_get(), ast_manager_event_blob_create(), EVENT_FLAG_CC, ast_json_payload::json, and stasis_message_data().
 {
    struct ast_json_payload *payload = stasis_message_data(message);
    int core_id;
    const char *caller;
    const char *reason;
    core_id = ast_json_integer_get(ast_json_object_get(payload->json, "core_id"));
    caller = ast_json_string_get(ast_json_object_get(payload->json, "caller"));
    reason = ast_json_string_get(ast_json_object_get(payload->json, "reason"));
    return ast_manager_event_blob_create(EVENT_FLAG_CC, "CCFailure",
       "CoreID: %d\r\n"
       "Caller: %s\r\n"
       "Reason: %s\r\n",
       core_id, caller, reason);
 }
cc_monitorfailed_to_ami()
static struct ast_manager_event_blob * cc_monitorfailed_to_ami (struct stasis_message * message) static
Definition at line 332 of file stasis_system.c.
References ast_json_integer_get(), ast_json_object_get(), ast_json_string_get(), ast_manager_event_blob_create(), EVENT_FLAG_CC, ast_json_payload::json, and stasis_message_data().
 {
    struct ast_json_payload *payload = stasis_message_data(message);
    int core_id;
    const char *callee;
    core_id = ast_json_integer_get(ast_json_object_get(payload->json, "core_id"));
    callee = ast_json_string_get(ast_json_object_get(payload->json, "callee"));
    return ast_manager_event_blob_create(EVENT_FLAG_CC, "CCMonitorFailed",
       "CoreID: %d\r\n"
       "Callee: %s\r\n",
       core_id, callee);
 }
cc_offertimerstart_to_ami()
static struct ast_manager_event_blob * cc_offertimerstart_to_ami (struct stasis_message * message) static
Definition at line 203 of file stasis_system.c.
References ast_json_integer_get(), ast_json_object_get(), ast_json_string_get(), ast_manager_event_blob_create(), EVENT_FLAG_CC, ast_json_payload::json, and stasis_message_data().
 {
    struct ast_json_payload *payload = stasis_message_data(message);
    int core_id;
    const char *caller;
    unsigned int expires;
    core_id = ast_json_integer_get(ast_json_object_get(payload->json, "core_id"));
    caller = ast_json_string_get(ast_json_object_get(payload->json, "caller"));
    expires = ast_json_integer_get(ast_json_object_get(payload->json, "expires"));
    return ast_manager_event_blob_create(EVENT_FLAG_CC, "CCOfferTimerStart",
       "CoreID: %d\r\n"
       "Caller: %s\r\n"
       "Expires: %u\r\n",
       core_id, caller, expires);
 }
cc_recallcomplete_to_ami()
static struct ast_manager_event_blob * cc_recallcomplete_to_ami (struct stasis_message * message) static
Definition at line 299 of file stasis_system.c.
References ast_json_integer_get(), ast_json_object_get(), ast_json_string_get(), ast_manager_event_blob_create(), EVENT_FLAG_CC, ast_json_payload::json, and stasis_message_data().
 {
    struct ast_json_payload *payload = stasis_message_data(message);
    int core_id;
    const char *caller;
    core_id = ast_json_integer_get(ast_json_object_get(payload->json, "core_id"));
    caller = ast_json_string_get(ast_json_object_get(payload->json, "caller"));
    return ast_manager_event_blob_create(EVENT_FLAG_CC, "CCRecallComplete",
       "CoreID: %d\r\n"
       "Caller: %s\r\n",
       core_id, caller);
 }
cc_requestacknowledged_to_ami()
static struct ast_manager_event_blob * cc_requestacknowledged_to_ami (struct stasis_message * message) static
Definition at line 239 of file stasis_system.c.
References ast_json_integer_get(), ast_json_object_get(), ast_json_string_get(), ast_manager_event_blob_create(), EVENT_FLAG_CC, ast_json_payload::json, and stasis_message_data().
 {
    struct ast_json_payload *payload = stasis_message_data(message);
    int core_id;
    const char *caller;
    core_id = ast_json_integer_get(ast_json_object_get(payload->json, "core_id"));
    caller = ast_json_string_get(ast_json_object_get(payload->json, "caller"));
    return ast_manager_event_blob_create(EVENT_FLAG_CC, "CCRequestAcknowledged",
       "CoreID: %d\r\n"
       "Caller: %s\r\n",
       core_id, caller);
 }
cc_requested_to_ami()
static struct ast_manager_event_blob * cc_requested_to_ami (struct stasis_message * message) static
Definition at line 221 of file stasis_system.c.
References ast_json_integer_get(), ast_json_object_get(), ast_json_string_get(), ast_manager_event_blob_create(), EVENT_FLAG_CC, ast_json_payload::json, and stasis_message_data().
 {
    struct ast_json_payload *payload = stasis_message_data(message);
    int core_id;
    const char *caller;
    const char *callee;
    core_id = ast_json_integer_get(ast_json_object_get(payload->json, "core_id"));
    caller = ast_json_string_get(ast_json_object_get(payload->json, "caller"));
    callee = ast_json_string_get(ast_json_object_get(payload->json, "callee"));
    return ast_manager_event_blob_create(EVENT_FLAG_CC, "CCRequested",
       "CoreID: %d\r\n"
       "Caller: %s\r\n"
       "Callee: %s\r\n",
       core_id, caller, callee);
 }
STASIS_MESSAGE_TYPE_DEFN() [1/13]
STASIS_MESSAGE_TYPE_DEFN (ast_network_change_type)
STASIS_MESSAGE_TYPE_DEFN() [2/13]
STASIS_MESSAGE_TYPE_DEFN (ast_system_registry_type , . to_ami = system_registry_to_ami)
STASIS_MESSAGE_TYPE_DEFN() [3/13]
STASIS_MESSAGE_TYPE_DEFN (ast_cc_available_type , . to_ami = cc_available_to_ami)
STASIS_MESSAGE_TYPE_DEFN() [4/13]
STASIS_MESSAGE_TYPE_DEFN (ast_cc_offertimerstart_type , . to_ami = cc_offertimerstart_to_ami)
STASIS_MESSAGE_TYPE_DEFN() [5/13]
STASIS_MESSAGE_TYPE_DEFN (ast_cc_requested_type , . to_ami = cc_requested_to_ami)
STASIS_MESSAGE_TYPE_DEFN() [6/13]
STASIS_MESSAGE_TYPE_DEFN (ast_cc_requestacknowledged_type , . to_ami = cc_requestacknowledged_to_ami)
STASIS_MESSAGE_TYPE_DEFN() [7/13]
STASIS_MESSAGE_TYPE_DEFN (ast_cc_callerstopmonitoring_type , . to_ami = cc_callerstopmonitoring_to_ami)
STASIS_MESSAGE_TYPE_DEFN() [8/13]
STASIS_MESSAGE_TYPE_DEFN (ast_cc_callerstartmonitoring_type , . to_ami = cc_callerstartmonitoring_to_ami)
STASIS_MESSAGE_TYPE_DEFN() [9/13]
STASIS_MESSAGE_TYPE_DEFN (ast_cc_callerrecalling_type , . to_ami = cc_callerrecalling_to_ami)
STASIS_MESSAGE_TYPE_DEFN() [10/13]
STASIS_MESSAGE_TYPE_DEFN (ast_cc_recallcomplete_type , . to_ami = cc_recallcomplete_to_ami)
STASIS_MESSAGE_TYPE_DEFN() [11/13]
STASIS_MESSAGE_TYPE_DEFN (ast_cc_failure_type , . to_ami = cc_failure_to_ami)
STASIS_MESSAGE_TYPE_DEFN() [12/13]
STASIS_MESSAGE_TYPE_DEFN (ast_cc_monitorfailed_type , . to_ami = cc_monitorfailed_to_ami)
STASIS_MESSAGE_TYPE_DEFN() [13/13]
STASIS_MESSAGE_TYPE_DEFN (ast_cluster_discovery_type)
stasis_system_cleanup()
static void stasis_system_cleanup (void) static
Cleanup the Stasis Message Bus API system level items.
Definition at line 353 of file stasis_system.c.
References ao2_cleanup, ast_cc_available_type(), ast_cc_callerrecalling_type(), ast_cc_callerstartmonitoring_type(), ast_cc_callerstopmonitoring_type(), ast_cc_failure_type(), ast_cc_monitorfailed_type(), ast_cc_offertimerstart_type(), ast_cc_recallcomplete_type(), ast_cc_requestacknowledged_type(), ast_cc_requested_type(), ast_cluster_discovery_type(), ast_network_change_type(), ast_system_registry_type(), NULL, and STASIS_MESSAGE_TYPE_CLEANUP.
Referenced by ast_stasis_system_init().
 {
    ao2_cleanup(system_topic);
    system_topic = NULL;
    STASIS_MESSAGE_TYPE_CLEANUP(ast_network_change_type);
    STASIS_MESSAGE_TYPE_CLEANUP(ast_system_registry_type);
    STASIS_MESSAGE_TYPE_CLEANUP(ast_cc_available_type);
    STASIS_MESSAGE_TYPE_CLEANUP(ast_cc_offertimerstart_type);
    STASIS_MESSAGE_TYPE_CLEANUP(ast_cc_requested_type);
    STASIS_MESSAGE_TYPE_CLEANUP(ast_cc_requestacknowledged_type);
    STASIS_MESSAGE_TYPE_CLEANUP(ast_cc_callerstopmonitoring_type);
    STASIS_MESSAGE_TYPE_CLEANUP(ast_cc_callerstartmonitoring_type);
    STASIS_MESSAGE_TYPE_CLEANUP(ast_cc_callerrecalling_type);
    STASIS_MESSAGE_TYPE_CLEANUP(ast_cc_recallcomplete_type);
    STASIS_MESSAGE_TYPE_CLEANUP(ast_cc_failure_type);
    STASIS_MESSAGE_TYPE_CLEANUP(ast_cc_monitorfailed_type);
    STASIS_MESSAGE_TYPE_CLEANUP(ast_cluster_discovery_type);
 }
system_registry_to_ami()
static struct ast_manager_event_blob * system_registry_to_ami (struct stasis_message * message) static
Definition at line 152 of file stasis_system.c.
References ast_free, ast_json_object_get(), ast_json_string_get(), ast_manager_event_blob_create(), ast_str_buffer(), ast_str_create, ast_str_set(), ast_strlen_zero, EVENT_FLAG_SYSTEM, ast_json_payload::json, NULL, RAII_VAR, stasis_message_data(), and status.
 {
    struct ast_json_payload *payload = stasis_message_data(message);
    const char *channeltype;
    const char *username;
    const char *domain;
    const char *status;
    const char *cause;
    RAII_VAR(struct ast_str *, cause_string, ast_str_create(32), ast_free);
    if (!cause_string) {
       return NULL;
    }
    channeltype = ast_json_string_get(ast_json_object_get(payload->json, "channeltype"));
    username = ast_json_string_get(ast_json_object_get(payload->json, "username"));
    domain = ast_json_string_get(ast_json_object_get(payload->json, "domain"));
    status = ast_json_string_get(ast_json_object_get(payload->json, "status"));
    cause = ast_json_string_get(ast_json_object_get(payload->json, "cause"));
    if (!ast_strlen_zero(cause)) {
       ast_str_set(&cause_string, 0, "Cause: %s\r\n", cause);
    }
    return ast_manager_event_blob_create(EVENT_FLAG_SYSTEM, "Registry",
       "ChannelType: %s\r\n"
       "Username: %s\r\n"
       "Domain: %s\r\n"
       "Status: %s\r\n"
       "%s",
       channeltype, username, domain, status, ast_str_buffer(cause_string));
 }
Variable Documentation
system_topic
struct stasis_topic* system_topic static
The Stasis Message Bus API topic for system level changes.
Definition at line 68 of file stasis_system.c.
Referenced by ast_system_topic(), and manager_system_init().