Asterisk - The Open Source Telephony Project: ari_websockets.c File Reference
ari_websockets.c File Reference
WebSocket support for RESTful API's.
#include "asterisk.h"
#include "asterisk/ari.h"
#include "asterisk/astobj2.h"
#include "asterisk/http_websocket.h"
#include "asterisk/stasis_app.h"
#include "internal.h"
Data Structures
struct ast_ari_websocket_session
Macros
#define VALIDATION_FAILED
Functions
void ari_handle_websocket (struct ast_websocket_server *ws_server, struct ast_tcptls_session_instance *ser, const char *uri, enum ast_http_method method, struct ast_variable *get_params, struct ast_variable *headers)
Wrapper for invoking the websocket code for an incoming connection.
struct ast_ari_websocket_session * ast_ari_websocket_session_create (struct ast_websocket *ws_session, int(*validator)(struct ast_json *))
Create an ARI WebSocket session.
struct ast_sockaddr * ast_ari_websocket_session_get_remote_addr (struct ast_ari_websocket_session *session)
Get the remote address from an ARI WebSocket.
const char * ast_ari_websocket_session_id (const struct ast_ari_websocket_session *session)
Get the Session ID for an ARI WebSocket.
struct ast_json * ast_ari_websocket_session_read (struct ast_ari_websocket_session *session)
Read a message from an ARI WebSocket.
int ast_ari_websocket_session_write (struct ast_ari_websocket_session *session, struct ast_json *message)
Send a message to an ARI WebSocket.
static int null_validator (struct ast_json *json)
Validator that always succeeds.
static void websocket_session_dtor (void *obj)
Detailed Description
WebSocket support for RESTful API's.
Author
David M. Lee, II dlee@.nosp@m.digi.nosp@m.um.co.nosp@m.m
Definition in file ari_websockets.c.
Macro Definition Documentation
VALIDATION_FAILED
#define VALIDATION_FAILED
Value:
"{"                  \
   "  \"error\": \"InvalidMessage\","     \
   "  \"message\": \"Message validation failed\""  \
   "}"
Definition at line 152 of file ari_websockets.c.
Referenced by ast_ari_websocket_session_write().
Function Documentation
ari_handle_websocket()
void ari_handle_websocket (struct ast_websocket_server * ws_server, struct ast_tcptls_session_instance * ser, const char * uri, enum ast_http_method method, struct ast_variable * get_params, struct ast_variable * headers)
Wrapper for invoking the websocket code for an incoming connection.
Parameters
ws_server WebSocket server to invoke.
ser HTTP session.
uri Requested URI.
method Requested HTTP method.
get_params Parsed query parameters.
headers Parsed HTTP headers.
Definition at line 191 of file ari_websockets.c.
References ast_websocket_uri_cb(), and ast_http_uri::data.
Referenced by ast_ari_invoke().
 {
    struct ast_http_uri fake_urih = {
       .data = ws_server,
    };
    ast_websocket_uri_cb(ser, &fake_urih, uri, method, get_params,
       headers);
 }
ast_ari_websocket_session_create()
struct ast_ari_websocket_session* ast_ari_websocket_session_create (struct ast_websocket * ws_session, int(*)(struct ast_json *) validator)
Create an ARI WebSocket session.
If NULL is given for the validator function, no validation will be performed.
Parameters
ws_session Underlying WebSocket session.
validator Function to validate outgoing messages.
Returns
New ARI WebSocket session.
NULL on error.
Definition at line 54 of file ari_websockets.c.
References ao2_alloc, ao2_cleanup, ao2_ref, ast_ari_config_get(), ast_log, ast_websocket_set_nonblock(), ast_websocket_set_timeout(), config, errno, LOG_ERROR, LOG_WARNING, NULL, null_validator(), RAII_VAR, session, ast_ari_websocket_session::validator, websocket_session_dtor(), and ast_ari_websocket_session::ws_session.
Referenced by ast_ari_events_event_websocket_ws_established_cb().
 {
    RAII_VAR(struct ast_ari_websocket_session *, session, NULL, ao2_cleanup);
    RAII_VAR(struct ast_ari_conf *, config, ast_ari_config_get(), ao2_cleanup);
    if (ws_session == NULL) {
       return NULL;
    }
    if (config == NULL || config->general == NULL) {
       return NULL;
    }
    if (validator == NULL) {
       validator = null_validator;
    }
    if (ast_websocket_set_nonblock(ws_session) != 0) {
       ast_log(LOG_ERROR,
          "ARI web socket failed to set nonblock; closing: %s\n",
          strerror(errno));
       return NULL;
    }
    if (ast_websocket_set_timeout(ws_session, config->general->write_timeout)) {
       ast_log(LOG_WARNING, "Failed to set write timeout %d on ARI web socket\n",
          config->general->write_timeout);
    }
    session = ao2_alloc(sizeof(*session), websocket_session_dtor);
    if (!session) {
       return NULL;
    }
    ao2_ref(ws_session, +1);
    session->ws_session = ws_session;
    session->validator = validator;
    ao2_ref(session, +1);
    return session;
 }
ast_ari_websocket_session_get_remote_addr()
struct ast_sockaddr* ast_ari_websocket_session_get_remote_addr (struct ast_ari_websocket_session * session)
Get the remote address from an ARI WebSocket.
Parameters
session Session to write to.
Returns
ast_sockaddr (does not have to be freed)
Definition at line 185 of file ari_websockets.c.
References ast_websocket_remote_address(), and ast_ari_websocket_session::ws_session.
Referenced by ast_ari_websocket_session_write(), and stasis_app_message_handler().
 {
    return ast_websocket_remote_address(session->ws_session);
 }
ast_ari_websocket_session_id()
const char* ast_ari_websocket_session_id (const struct ast_ari_websocket_session * session)
Get the Session ID for an ARI WebSocket.
Parameters
session Session to query.
Returns
Session ID.
NULL on error.
Definition at line 203 of file ari_websockets.c.
References ast_websocket_session_id(), and ast_ari_websocket_session::ws_session.
Referenced by ast_ari_websocket_events_event_websocket_established().
 {
    return ast_websocket_session_id(session->ws_session);
 }
ast_ari_websocket_session_read()
struct ast_json* ast_ari_websocket_session_read (struct ast_ari_websocket_session * session)
Read a message from an ARI WebSocket.
Parameters
session Session to read from.
Returns
Message received.
NULL if WebSocket could not be read.
Definition at line 97 of file ari_websockets.c.
References ast_debug, ast_json_load_buf(), ast_json_ref(), ast_json_unref(), ast_log, ast_wait_for_input(), ast_websocket_fd(), AST_WEBSOCKET_OPCODE_CLOSE, AST_WEBSOCKET_OPCODE_TEXT, ast_websocket_read(), errno, LOG_WARNING, NULL, RAII_VAR, and ast_ari_websocket_session::ws_session.
Referenced by ast_ari_websocket_events_event_websocket_established().
 {
    RAII_VAR(struct ast_json *, message, NULL, ast_json_unref);
    if (ast_websocket_fd(session->ws_session) < 0) {
       return NULL;
    }
    while (!message) {
       int res;
       char *payload;
       uint64_t payload_len;
       enum ast_websocket_opcode opcode;
       int fragmented;
       res = ast_wait_for_input(
          ast_websocket_fd(session->ws_session), -1);
       if (res <= 0) {
          ast_log(LOG_WARNING, "WebSocket poll error: %s\n",
             strerror(errno));
          return NULL;
       }
       res = ast_websocket_read(session->ws_session, &payload,
          &payload_len, &opcode, &fragmented);
       if (res != 0) {
          ast_log(LOG_WARNING, "WebSocket read error: %s\n",
             strerror(errno));
          return NULL;
       }
       switch (opcode) {
       case AST_WEBSOCKET_OPCODE_CLOSE:
          ast_debug(1, "WebSocket closed\n");
          return NULL;
       case AST_WEBSOCKET_OPCODE_TEXT:
          message = ast_json_load_buf(payload, payload_len, NULL);
          if (message == NULL) {
             ast_log(LOG_WARNING,
                "WebSocket input failed to parse\n");
          }
          break;
       default:
          /* Ignore all other message types */
          break;
       }
    }
    return ast_json_ref(message);
 }
ast_ari_websocket_session_write()
int ast_ari_websocket_session_write (struct ast_ari_websocket_session * session, struct ast_json * message)
Send a message to an ARI WebSocket.
Parameters
session Session to write to.
message Message to send.
Returns
0 on success.
Non-zero on error.
Definition at line 158 of file ari_websockets.c.
References ast_ari_json_format(), ast_ari_websocket_session_get_remote_addr(), ast_json_dump_string_format(), ast_json_free(), ast_log, ast_sockaddr_stringify(), ast_websocket_write_string(), LOG_ERROR, LOG_NOTICE, NULL, RAII_VAR, str, VALIDATION_FAILED, ast_ari_websocket_session::validator, and ast_ari_websocket_session::ws_session.
Referenced by event_session_update_websocket(), and stasis_app_message_handler().
 {
    RAII_VAR(char *, str, NULL, ast_json_free);
 #ifdef AST_DEVMODE
    if (!session->validator(message)) {
       ast_log(LOG_ERROR, "Outgoing message failed validation\n");
       return ast_websocket_write_string(session->ws_session, VALIDATION_FAILED);
    }
 #endif
    str = ast_json_dump_string_format(message, ast_ari_json_format());
    if (str == NULL) {
       ast_log(LOG_ERROR, "Failed to encode JSON object\n");
       return -1;
    }
    if (ast_websocket_write_string(session->ws_session, str)) {
       ast_log(LOG_NOTICE, "Problem occurred during websocket write to %s, websocket closed\n",
          ast_sockaddr_stringify(ast_ari_websocket_session_get_remote_addr(session)));
       return -1;
    }
    return 0;
 }
null_validator()
static int null_validator (struct ast_json * json) static
Validator that always succeeds.
Definition at line 49 of file ari_websockets.c.
Referenced by ast_ari_websocket_session_create().
 {
    return 1;
 }
websocket_session_dtor()
static void websocket_session_dtor (void * obj) static
Definition at line 38 of file ari_websockets.c.
References ast_websocket_unref(), NULL, session, and ast_ari_websocket_session::ws_session.
Referenced by ast_ari_websocket_session_create().
 {
    struct ast_ari_websocket_session *session = obj;
    ast_websocket_unref(session->ws_session);
    session->ws_session = NULL;
 }