Asterisk - The Open Source Telephony Project: codec_adpcm.c File Reference
codec_adpcm.c File Reference
Module: Codecs
codec_adpcm.c - translate between signed linear and Dialogic ADPCM
#include "asterisk.h"
#include "asterisk/lock.h"
#include "asterisk/linkedlists.h"
#include "asterisk/module.h"
#include "asterisk/config.h"
#include "asterisk/translate.h"
#include "asterisk/utils.h"
#include "asterisk/slin.h"
#include "ex_adpcm.h"
Data Structures
struct adpcm_decoder_pvt
Workspace for translating ADPCM signals to signed linear.
struct adpcm_encoder_pvt
Workspace for translating signed linear signals to ADPCM.
struct adpcm_state
Macros
#define BUFFER_SAMPLES 8096 /* size for the translation buffers */
Functions
static void __reg_module (void)
static void __unreg_module (void)
static int adpcm (short csig, struct adpcm_state *state)
static int adpcmtolin_framein (struct ast_trans_pvt *pvt, struct ast_frame *f)
decode 4-bit adpcm frame data and store in output buffer
struct ast_module * AST_MODULE_SELF_SYM (void)
static short decode (int encoded, struct adpcm_state *state)
static int lintoadpcm_framein (struct ast_trans_pvt *pvt, struct ast_frame *f)
fill input buffer with 16-bit signed linear PCM values.
static struct ast_frame * lintoadpcm_frameout (struct ast_trans_pvt *pvt)
convert inbuf and store into frame
static int load_module (void)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_DEFAULT , .description = "Adaptive Differential PCM Coder/Decoder" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, }
static struct ast_translator adpcmtolin
static const struct ast_module_info * ast_module_info = &__mod_info
static int indsft [8] = { -1, -1, -1, -1, 2, 4, 6, 8 }
static struct ast_translator lintoadpcm
static int stpsz [49]
Detailed Description
codec_adpcm.c - translate between signed linear and Dialogic ADPCM
Definition in file codec_adpcm.c.
Macro Definition Documentation
BUFFER_SAMPLES
#define BUFFER_SAMPLES 8096 /* size for the translation buffers */
Definition at line 46 of file codec_adpcm.c.
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 359 of file codec_adpcm.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 359 of file codec_adpcm.c.
adpcm()
static int adpcm (short csig, struct adpcm_state * state) inline static
Definition at line 164 of file codec_adpcm.c.
References decode(), adpcm_state::signal, adpcm_state::ssindex, and stpsz.
Referenced by lintoadpcm_frameout().
 {
    int diff;
    int step;
    int encoded;
    /*
     * Clip csig if too large or too small
     */
    csig >>= 4;
    step = stpsz[state->ssindex];
    diff = csig - state->signal;
 #ifdef NOT_BLI
    if (diff < 0) {
       encoded = (-diff << 2) / step;
       if (encoded > 7)
          encoded = 7;
       encoded |= 0x08;
    } else {
       encoded = (diff << 2) / step;
       if (encoded > 7)
          encoded = 7;
    }
 #else /* BLI code */
    if (diff < 0) {
       encoded = 8;
       diff = -diff;
    } else
       encoded = 0;
    if (diff >= step) {
       encoded |= 4;
       diff -= step;
    }
    step >>= 1;
    if (diff >= step) {
       encoded |= 2;
       diff -= step;
    }
    step >>= 1;
    if (diff >= step)
       encoded |= 1;
 #endif /* NOT_BLI */
    /* feedback to state */
    decode(encoded, state);
    return encoded;
 }
adpcmtolin_framein()
static int adpcmtolin_framein (struct ast_trans_pvt * pvt, struct ast_frame * f) static
decode 4-bit adpcm frame data and store in output buffer
Definition at line 229 of file codec_adpcm.c.
References ast_frame::data, ast_frame::datalen, ast_trans_pvt::datalen, decode(), ast_trans_pvt::i16, ast_trans_pvt::outbuf, ast_frame::ptr, ast_trans_pvt::pvt, ast_frame::samples, ast_trans_pvt::samples, adpcm_decoder_pvt::state, and tmp().
 {
    struct adpcm_decoder_pvt *tmp = pvt->pvt;
    int x = f->datalen;
    unsigned char *src = f->data.ptr;
    int16_t *dst = pvt->outbuf.i16 + pvt->samples;
    while (x--) {
       *dst++ = decode((*src >> 4) & 0xf, &tmp->state);
       *dst++ = decode(*src++ & 0x0f, &tmp->state);
    }
    pvt->samples += f->samples;
    pvt->datalen += 2*f->samples;
    return 0;
 }
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 359 of file codec_adpcm.c.
decode()
static short decode (int encoded, struct adpcm_state * state) inline static
Definition at line 91 of file codec_adpcm.c.
References indsft, adpcm_state::next_flag, adpcm_state::signal, adpcm_state::ssindex, stpsz, and adpcm_state::zero_count.
Referenced by adpcm(), and adpcmtolin_framein().
 {
    int diff;
    int step;
    int sign;
    step = stpsz[state->ssindex];
    sign = encoded & 0x08;
    encoded &= 0x07;
 #ifdef NOT_BLI
    diff = (((encoded << 1) + 1) * step) >> 3;
 #else /* BLI code */
    diff = step >> 3;
    if (encoded & 4)
       diff += step;
    if (encoded & 2)
       diff += step >> 1;
    if (encoded & 1)
       diff += step >> 2;
    if ((encoded >> 1) & step & 0x1)
       diff++;
 #endif
    if (sign)
       diff = -diff;
    if (state->next_flag & 0x1)
       state->signal -= 8;
    else if (state->next_flag & 0x2)
       state->signal += 8;
    state->signal += diff;
    if (state->signal > 2047)
       state->signal = 2047;
    else if (state->signal < -2047)
       state->signal = -2047;
    state->next_flag = 0;
 #ifdef AUTO_RETURN
    if (encoded)
       state->zero_count = 0;
    else if (++(state->zero_count) == 24) {
       state->zero_count = 0;
       if (state->signal > 0)
          state->next_flag = 0x1;
       else if (state->signal < 0)
          state->next_flag = 0x2;
    }
 #endif
    state->ssindex += indsft[encoded];
    if (state->ssindex < 0)
       state->ssindex = 0;
    else if (state->ssindex > 48)
       state->ssindex = 48;
    return state->signal << 4;
 }
lintoadpcm_framein()
static int lintoadpcm_framein (struct ast_trans_pvt * pvt, struct ast_frame * f) static
fill input buffer with 16-bit signed linear PCM values.
Definition at line 246 of file codec_adpcm.c.
References ast_frame::data, ast_frame::datalen, adpcm_encoder_pvt::inbuf, ast_frame::ptr, ast_trans_pvt::pvt, ast_frame::samples, ast_trans_pvt::samples, and tmp().
 {
    struct adpcm_encoder_pvt *tmp = pvt->pvt;
    memcpy(&tmp->inbuf[pvt->samples], f->data.ptr, f->datalen);
    pvt->samples += f->samples;
    return 0;
 }
lintoadpcm_frameout()
static struct ast_frame* lintoadpcm_frameout (struct ast_trans_pvt * pvt) static
convert inbuf and store into frame
Definition at line 256 of file codec_adpcm.c.
References adpcm(), ast_trans_frameout(), ast_trans_pvt::c, adpcm_encoder_pvt::inbuf, NULL, ast_trans_pvt::outbuf, ast_trans_pvt::pvt, ast_frame::samples, ast_trans_pvt::samples, adpcm_encoder_pvt::state, and tmp().
 {
    struct adpcm_encoder_pvt *tmp = pvt->pvt;
    struct ast_frame *f;
    int i;
    int samples = pvt->samples;   /* save original number */
    if (samples < 2)
       return NULL;
    pvt->samples &= ~1; /* atomic size is 2 samples */
    for (i = 0; i < pvt->samples; i += 2) {
       pvt->outbuf.c[i/2] =
          (adpcm(tmp->inbuf[i  ], &tmp->state) << 4) |
          (adpcm(tmp->inbuf[i+1], &tmp->state)     );
    };
    f = ast_trans_frameout(pvt, pvt->samples/2, 0);
    /*
     * If there is a left over sample, move it to the beginning
     * of the input buffer.
     */
    if (samples & 1) {   /* move the leftover sample at beginning */
       tmp->inbuf[0] = tmp->inbuf[samples - 1];
       pvt->samples = 1;
    }
    return f;
 }
load_module()
static int load_module (void) static
Definition at line 340 of file codec_adpcm.c.
References AST_MODFLAG_DEFAULT, AST_MODULE_INFO(), AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, AST_MODULE_SUPPORT_CORE, ast_register_translator, ASTERISK_GPL_KEY, and unload_module().
 {
    int res = 0;
    res = ast_register_translator(&adpcmtolin);
    res |= ast_register_translator(&lintoadpcm);
    if (res) {
       unload_module();
       return AST_MODULE_LOAD_DECLINE;
    }
    return AST_MODULE_LOAD_SUCCESS;
 }
unload_module()
static int unload_module (void) static
Definition at line 330 of file codec_adpcm.c.
References ast_unregister_translator().
Referenced by load_module().
 {
    int res;
    res = ast_unregister_translator(&lintoadpcm);
    res |= ast_unregister_translator(&adpcmtolin);
    return res;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_DEFAULT , .description = "Adaptive Differential PCM Coder/Decoder" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, } static
Definition at line 359 of file codec_adpcm.c.
adpcmtolin
struct ast_translator adpcmtolin static
Definition at line 289 of file codec_adpcm.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 359 of file codec_adpcm.c.
indsft
int indsft[8] = { -1, -1, -1, -1, 2, 4, 6, 8 } static
Definition at line 56 of file codec_adpcm.c.
Referenced by decode().
lintoadpcm
struct ast_translator lintoadpcm static
Definition at line 309 of file codec_adpcm.c.
stpsz
int stpsz[49] static
Definition at line 62 of file codec_adpcm.c.
Referenced by adpcm(), and decode().