Asterisk - The Open Source Telephony Project: res_ari_mailboxes.c File Reference
res_ari_mailboxes.c File Reference
Mailboxes resources.
#include "asterisk.h"
#include "asterisk/app.h"
#include "asterisk/module.h"
#include "asterisk/stasis_app.h"
#include "ari/resource_mailboxes.h"
#include "ari/ari_model_validators.h"
Macros
#define MAX_VALS 128
Functions
static void __reg_module (void)
static void __unreg_module (void)
static void ast_ari_mailboxes_delete_cb (struct ast_tcptls_session_instance *ser, struct ast_variable *get_params, struct ast_variable *path_vars, struct ast_variable *headers, struct ast_json *body, struct ast_ari_response *response)
Parameter parsing callback for /mailboxes/{mailboxName}.
static void ast_ari_mailboxes_get_cb (struct ast_tcptls_session_instance *ser, struct ast_variable *get_params, struct ast_variable *path_vars, struct ast_variable *headers, struct ast_json *body, struct ast_ari_response *response)
Parameter parsing callback for /mailboxes/{mailboxName}.
static void ast_ari_mailboxes_list_cb (struct ast_tcptls_session_instance *ser, struct ast_variable *get_params, struct ast_variable *path_vars, struct ast_variable *headers, struct ast_json *body, struct ast_ari_response *response)
Parameter parsing callback for /mailboxes.
static void ast_ari_mailboxes_update_cb (struct ast_tcptls_session_instance *ser, struct ast_variable *get_params, struct ast_variable *path_vars, struct ast_variable *headers, struct ast_json *body, struct ast_ari_response *response)
Parameter parsing callback for /mailboxes/{mailboxName}.
int ast_ari_mailboxes_update_parse_body (struct ast_json *body, struct ast_ari_mailboxes_update_args *args)
Body parsing function for /mailboxes/{mailboxName}.
struct ast_module * AST_MODULE_SELF_SYM (void)
static int load_module (void)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_DEFAULT , .description = "RESTful API module - Mailboxes resources" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .requires = "res_ari,res_ari_model,res_stasis,res_stasis_mailbox", }
static const struct ast_module_info * ast_module_info = &__mod_info
static struct stasis_rest_handlers mailboxes
REST handler for /api-docs/mailboxes.json.
static struct stasis_rest_handlers mailboxes_mailboxName
REST handler for /api-docs/mailboxes.json.
Detailed Description
Mailboxes resources.
Author
Jonathan Rose jrose.nosp@m.@dig.nosp@m.ium.c.nosp@m.om
Definition in file res_ari_mailboxes.c.
Macro Definition Documentation
MAX_VALS
#define MAX_VALS 128
Definition at line 52 of file res_ari_mailboxes.c.
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 356 of file res_ari_mailboxes.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 356 of file res_ari_mailboxes.c.
ast_ari_mailboxes_delete_cb()
static void ast_ari_mailboxes_delete_cb (struct ast_tcptls_session_instance * ser, struct ast_variable * get_params, struct ast_variable * path_vars, struct ast_variable * headers, struct ast_json * body, struct ast_ari_response * response) static
Parameter parsing callback for /mailboxes/{mailboxName}.
Parameters
get_params GET parameters in the HTTP request.
path_vars Path variables extracted from the request.
headers HTTP headers.
[out] response Response to the HTTP request.
Definition at line 257 of file res_ari_mailboxes.c.
References ast_ari_mailboxes_delete(), ast_ari_response_error(), ast_ari_validate_void(), ast_log, LOG_ERROR, ast_ari_mailboxes_delete_args::mailbox_name, ast_ari_response::message, ast_variable::name, ast_variable::next, NULL, ast_ari_response::response_code, and ast_variable::value.
 {
    struct ast_ari_mailboxes_delete_args args = {};
    struct ast_variable *i;
 #if defined(AST_DEVMODE)
    int is_valid;
    int code;
 #endif /* AST_DEVMODE */
    for (i = path_vars; i; i = i->next) {
       if (strcmp(i->name, "mailboxName") == 0) {
          args.mailbox_name = (i->value);
       } else
       {}
    }
    ast_ari_mailboxes_delete(headers, &args, response);
 #if defined(AST_DEVMODE)
    code = response->response_code;
    switch (code) {
    case 0: /* Implementation is still a stub, or the code wasn't set */
       is_valid = response->message == NULL;
       break;
    case 500: /* Internal Server Error */
    case 501: /* Not Implemented */
    case 404: /* Mailbox not found */
       is_valid = 1;
       break;
    default:
       if (200 <= code && code <= 299) {
          is_valid = ast_ari_validate_void(
             response->message);
       } else {
          ast_log(LOG_ERROR, "Invalid error response %d for /mailboxes/{mailboxName}\n", code);
          is_valid = 0;
       }
    }
    if (!is_valid) {
       ast_log(LOG_ERROR, "Response validation failed for /mailboxes/{mailboxName}\n");
       ast_ari_response_error(response, 500,
          "Internal Server Error", "Response validation failed");
    }
 #endif /* AST_DEVMODE */
 fin: __attribute__((unused))
    return;
 }
ast_ari_mailboxes_get_cb()
static void ast_ari_mailboxes_get_cb (struct ast_tcptls_session_instance * ser, struct ast_variable * get_params, struct ast_variable * path_vars, struct ast_variable * headers, struct ast_json * body, struct ast_ari_response * response) static
Parameter parsing callback for /mailboxes/{mailboxName}.
Parameters
get_params GET parameters in the HTTP request.
path_vars Path variables extracted from the request.
headers HTTP headers.
[out] response Response to the HTTP request.
Definition at line 111 of file res_ari_mailboxes.c.
References ast_ari_mailboxes_get(), ast_ari_response_error(), ast_ari_validate_mailbox(), ast_log, LOG_ERROR, ast_ari_mailboxes_get_args::mailbox_name, ast_ari_response::message, ast_variable::name, ast_variable::next, NULL, ast_ari_response::response_code, and ast_variable::value.
 {
    struct ast_ari_mailboxes_get_args args = {};
    struct ast_variable *i;
 #if defined(AST_DEVMODE)
    int is_valid;
    int code;
 #endif /* AST_DEVMODE */
    for (i = path_vars; i; i = i->next) {
       if (strcmp(i->name, "mailboxName") == 0) {
          args.mailbox_name = (i->value);
       } else
       {}
    }
    ast_ari_mailboxes_get(headers, &args, response);
 #if defined(AST_DEVMODE)
    code = response->response_code;
    switch (code) {
    case 0: /* Implementation is still a stub, or the code wasn't set */
       is_valid = response->message == NULL;
       break;
    case 500: /* Internal Server Error */
    case 501: /* Not Implemented */
    case 404: /* Mailbox not found */
       is_valid = 1;
       break;
    default:
       if (200 <= code && code <= 299) {
          is_valid = ast_ari_validate_mailbox(
             response->message);
       } else {
          ast_log(LOG_ERROR, "Invalid error response %d for /mailboxes/{mailboxName}\n", code);
          is_valid = 0;
       }
    }
    if (!is_valid) {
       ast_log(LOG_ERROR, "Response validation failed for /mailboxes/{mailboxName}\n");
       ast_ari_response_error(response, 500,
          "Internal Server Error", "Response validation failed");
    }
 #endif /* AST_DEVMODE */
 fin: __attribute__((unused))
    return;
 }
ast_ari_mailboxes_list_cb()
static void ast_ari_mailboxes_list_cb (struct ast_tcptls_session_instance * ser, struct ast_variable * get_params, struct ast_variable * path_vars, struct ast_variable * headers, struct ast_json * body, struct ast_ari_response * response) static
Parameter parsing callback for /mailboxes.
Parameters
get_params GET parameters in the HTTP request.
path_vars Path variables extracted from the request.
headers HTTP headers.
[out] response Response to the HTTP request.
Definition at line 61 of file res_ari_mailboxes.c.
References ast_ari_mailboxes_list(), ast_ari_response_error(), ast_ari_validate_list(), ast_ari_validate_mailbox_fn(), ast_log, LOG_ERROR, ast_ari_response::message, NULL, and ast_ari_response::response_code.
 {
    struct ast_ari_mailboxes_list_args args = {};
 #if defined(AST_DEVMODE)
    int is_valid;
    int code;
 #endif /* AST_DEVMODE */
    ast_ari_mailboxes_list(headers, &args, response);
 #if defined(AST_DEVMODE)
    code = response->response_code;
    switch (code) {
    case 0: /* Implementation is still a stub, or the code wasn't set */
       is_valid = response->message == NULL;
       break;
    case 500: /* Internal Server Error */
    case 501: /* Not Implemented */
       is_valid = 1;
       break;
    default:
       if (200 <= code && code <= 299) {
          is_valid = ast_ari_validate_list(response->message,
             ast_ari_validate_mailbox_fn());
       } else {
          ast_log(LOG_ERROR, "Invalid error response %d for /mailboxes\n", code);
          is_valid = 0;
       }
    }
    if (!is_valid) {
       ast_log(LOG_ERROR, "Response validation failed for /mailboxes\n");
       ast_ari_response_error(response, 500,
          "Internal Server Error", "Response validation failed");
    }
 #endif /* AST_DEVMODE */
 fin: __attribute__((unused))
    return;
 }
ast_ari_mailboxes_update_cb()
static void ast_ari_mailboxes_update_cb (struct ast_tcptls_session_instance * ser, struct ast_variable * get_params, struct ast_variable * path_vars, struct ast_variable * headers, struct ast_json * body, struct ast_ari_response * response) static
Parameter parsing callback for /mailboxes/{mailboxName}.
Parameters
get_params GET parameters in the HTTP request.
path_vars Path variables extracted from the request.
headers HTTP headers.
[out] response Response to the HTTP request.
Definition at line 186 of file res_ari_mailboxes.c.
References ast_ari_mailboxes_update(), ast_ari_mailboxes_update_parse_body(), ast_ari_response_alloc_failed(), ast_ari_response_error(), ast_ari_validate_void(), ast_log, LOG_ERROR, ast_ari_mailboxes_update_args::mailbox_name, ast_ari_response::message, ast_variable::name, ast_ari_mailboxes_update_args::new_messages, ast_variable::next, NULL, ast_ari_mailboxes_update_args::old_messages, ast_ari_response::response_code, and ast_variable::value.
 {
    struct ast_ari_mailboxes_update_args args = {};
    struct ast_variable *i;
 #if defined(AST_DEVMODE)
    int is_valid;
    int code;
 #endif /* AST_DEVMODE */
    for (i = get_params; i; i = i->next) {
       if (strcmp(i->name, "oldMessages") == 0) {
          args.old_messages = atoi(i->value);
       } else
       if (strcmp(i->name, "newMessages") == 0) {
          args.new_messages = atoi(i->value);
       } else
       {}
    }
    for (i = path_vars; i; i = i->next) {
       if (strcmp(i->name, "mailboxName") == 0) {
          args.mailbox_name = (i->value);
       } else
       {}
    }
    if (ast_ari_mailboxes_update_parse_body(body, &args)) {
       ast_ari_response_alloc_failed(response);
       goto fin;
    }
    ast_ari_mailboxes_update(headers, &args, response);
 #if defined(AST_DEVMODE)
    code = response->response_code;
    switch (code) {
    case 0: /* Implementation is still a stub, or the code wasn't set */
       is_valid = response->message == NULL;
       break;
    case 500: /* Internal Server Error */
    case 501: /* Not Implemented */
    case 404: /* Mailbox not found */
       is_valid = 1;
       break;
    default:
       if (200 <= code && code <= 299) {
          is_valid = ast_ari_validate_void(
             response->message);
       } else {
          ast_log(LOG_ERROR, "Invalid error response %d for /mailboxes/{mailboxName}\n", code);
          is_valid = 0;
       }
    }
    if (!is_valid) {
       ast_log(LOG_ERROR, "Response validation failed for /mailboxes/{mailboxName}\n");
       ast_ari_response_error(response, 500,
          "Internal Server Error", "Response validation failed");
    }
 #endif /* AST_DEVMODE */
 fin: __attribute__((unused))
    return;
 }
ast_ari_mailboxes_update_parse_body()
int ast_ari_mailboxes_update_parse_body (struct ast_json * body, struct ast_ari_mailboxes_update_args * args)
Body parsing function for /mailboxes/{mailboxName}.
Parameters
body The JSON body from which to parse parameters.
[out] args The args structure to parse into.
Return values
zero on success
non-zero on failure
Definition at line 162 of file res_ari_mailboxes.c.
References ast_json_integer_get(), ast_json_object_get(), ast_ari_mailboxes_update_args::new_messages, and ast_ari_mailboxes_update_args::old_messages.
Referenced by ast_ari_mailboxes_update_cb().
 {
    struct ast_json *field;
    /* Parse query parameters out of it */
    field = ast_json_object_get(body, "oldMessages");
    if (field) {
       args->old_messages = ast_json_integer_get(field);
    }
    field = ast_json_object_get(body, "newMessages");
    if (field) {
       args->new_messages = ast_json_integer_get(field);
    }
    return 0;
 }
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 356 of file res_ari_mailboxes.c.
load_module()
static int load_module (void) static
Definition at line 337 of file res_ari_mailboxes.c.
References ast_ari_add_handler(), AST_MODFLAG_DEFAULT, AST_MODULE_INFO(), AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, AST_MODULE_SUPPORT_CORE, ASTERISK_GPL_KEY, and unload_module().
 {
    int res = 0;
    res |= ast_ari_add_handler(&mailboxes);
    if (res) {
       unload_module();
       return AST_MODULE_LOAD_DECLINE;
    }
    return AST_MODULE_LOAD_SUCCESS;
 }
unload_module()
static int unload_module (void) static
Definition at line 331 of file res_ari_mailboxes.c.
References ast_ari_remove_handler().
Referenced by load_module().
 {
    ast_ari_remove_handler(&mailboxes);
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_DEFAULT , .description = "RESTful API module - Mailboxes resources" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .requires = "res_ari,res_ari_model,res_stasis,res_stasis_mailbox", } static
Definition at line 356 of file res_ari_mailboxes.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 356 of file res_ari_mailboxes.c.
mailboxes
struct stasis_rest_handlers mailboxes static
REST handler for /api-docs/mailboxes.json.
Examples:
/usr/src/asterisk-18.5.0/main/app.c.
Definition at line 322 of file res_ari_mailboxes.c.
Referenced by ast_mwi_mailbox_delete_all(), ast_mwi_mailbox_delete_by_regex(), ast_sip_initialize_sorcery_location(), create_unsolicited_mwi_subscriptions(), free_zone(), mwi_initial_events(), mwi_mailbox_get(), mwi_on_aor(), mwi_validate_for_aor(), and stasis_app_mailboxes_to_json().
mailboxes_mailboxName
struct stasis_rest_handlers mailboxes_mailboxName static
REST handler for /api-docs/mailboxes.json.
Definition at line 310 of file res_ari_mailboxes.c.