Asterisk - The Open Source Telephony Project: test_file.c File Reference
test_file.c File Reference
#include "asterisk.h"
#include <sys/stat.h>
#include <stdio.h>
#include "asterisk/file.h"
#include "asterisk/paths.h"
#include "asterisk/test.h"
#include "asterisk/module.h"
#include "asterisk/strings.h"
#include "asterisk/vector.h"
Macros
#define FOUND -7
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
AST_TEST_DEFINE (read_dirs_test)
AST_VECTOR (_filenames, struct ast_str *)
static int handle_find_file (const char *dir_name, const char *filename, void *obj)
static int load_module (void)
static void rm_file (struct ast_str *filename)
static int test_files_create (struct ast_test *test, char *dir_name, struct _filenames *filenames, int num)
static int test_files_destroy (struct ast_test *test, char *dir_name, struct _filenames *filenames)
static char * test_files_get_one (struct _filenames *filenames, int num)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "File test module" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, }
static const struct ast_module_info * ast_module_info = &__mod_info
Macro Definition Documentation
FOUND
#define FOUND -7
Definition at line 36 of file test_file.c.
Referenced by AST_TEST_DEFINE(), and handle_find_file().
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 195 of file test_file.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 195 of file test_file.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 195 of file test_file.c.
AST_TEST_DEFINE()
AST_TEST_DEFINE (read_dirs_test)
Definition at line 136 of file test_file.c.
References ast_file_read_dirs(), ast_random(), ast_str_alloca, ast_str_buffer(), ast_str_set(), AST_TEST_FAIL, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_test_status_update, FOUND, handle_find_file(), sip_to_pjsip::info(), mkdtemp(), NULL, TEST_EXECUTE, test_files_create(), test_files_destroy(), test_files_get_one(), and TEST_INIT.
 {
    char tmp_dir[] = "/tmp/tmpdir.XXXXXX";
    struct ast_str *tmp_sub_dir;
    struct _filenames filenames;
    enum ast_test_result_state res;
    const int num_files = 10 + (ast_random() % 10); /* 10-19 random files */
    switch (cmd) {
    case TEST_INIT:
       info->name = "read_dir_test";
       info->category = "/main/file/";
       info->summary = "Read a directory's content";
       info->description = "Iterate over directories looking for a file.";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    /*
     * We want to test recursively searching into a subdirectory, so
     * create a top level tmp directory where we will start the search.
     */
    if (!(mkdtemp(tmp_dir))) {
       ast_test_status_update(test, "Failed to create directory: %s\n", tmp_dir);
       return AST_TEST_FAIL;
    }
    tmp_sub_dir = ast_str_alloca(32);
    ast_str_set(&tmp_sub_dir, 0, "%s/XXXXXX", tmp_dir);
    if (test_files_create(test, ast_str_buffer(tmp_sub_dir), &filenames, num_files)) {
       test_files_destroy(test, tmp_dir, NULL);
       return AST_TEST_FAIL;
    }
    res = ast_file_read_dirs(tmp_dir, handle_find_file, test_files_get_one(
        &filenames, num_files), 2) == FOUND ? AST_TEST_PASS : AST_TEST_FAIL;
    if (test_files_destroy(test, ast_str_buffer(tmp_sub_dir), &filenames) ||
        test_files_destroy(test, tmp_dir, NULL)) {
       res = AST_TEST_FAIL;
    }
    return res;
 }
AST_VECTOR()
AST_VECTOR (_filenames , struct ast_str *)
handle_find_file()
static int handle_find_file (const char * dir_name, const char * filename, void * obj) static
Definition at line 119 of file test_file.c.
References ast_alloca, ast_log, errno, FOUND, and LOG_ERROR.
Referenced by AST_TEST_DEFINE().
 {
    struct stat statbuf;
    char *full_path = ast_alloca(strlen(dir_name) + strlen(filename) + 2);
    sprintf(full_path, "%s/%s", dir_name, filename);
    errno = 0;
    if (stat(full_path, &statbuf)) {
       ast_log(LOG_ERROR, "Error reading path stats - %s: %s\n",
          full_path, strerror(errno));
       return 0;
    }
    /* obj contains the name of the file we are looking for */
    return strcmp(obj, filename) ? 0 : FOUND;
 }
load_module()
static int load_module (void) static
Definition at line 189 of file test_file.c.
References AST_MODULE_LOAD_SUCCESS, and AST_TEST_REGISTER.
 {
    AST_TEST_REGISTER(read_dirs_test);
    return AST_MODULE_LOAD_SUCCESS;
 }
rm_file()
static void rm_file (struct ast_str * filename) static
Definition at line 40 of file test_file.c.
References ast_free, ast_log, ast_str_buffer(), and LOG_ERROR.
Referenced by test_files_destroy().
 {
    if (unlink(ast_str_buffer(filename))) {
       ast_log(LOG_ERROR, "Unable to remove file: %s\n", ast_str_buffer(filename));
    }
    ast_free(filename);
 }
test_files_create()
static int test_files_create (struct ast_test * test, char * dir_name, struct _filenames * filenames, int num) static
Definition at line 66 of file test_file.c.
References ast_free, ast_str_buffer(), ast_str_create, ast_str_set(), ast_test_status_update, AST_VECTOR_APPEND, AST_VECTOR_INIT, mkdtemp(), and test_files_destroy().
Referenced by AST_TEST_DEFINE().
 {
    int i;
    if (!(mkdtemp(dir_name))) {
       ast_test_status_update(test, "Failed to create directory: %s\n", dir_name);
       return -1;
    }
    AST_VECTOR_INIT(filenames, num);
    /*
     * Create "num" files under the specified directory
     */
    for (i = 0; i < num; ++i) {
       int fd;
       struct ast_str *filename = ast_str_create(32);
       if (!filename) {
          break;
       }
       ast_str_set(&filename, 0, "%s/XXXXXX", dir_name);
       fd = mkstemp(ast_str_buffer(filename));
       if (fd < 0) {
          ast_test_status_update(test, "Failed to create file: %s\n",
                       ast_str_buffer(filename));
          ast_free(filename);
          break;
       }
       close(fd);
       AST_VECTOR_APPEND(filenames, filename);
    }
    if (i != num) {
       test_files_destroy(test, dir_name, filenames);
       return -1;
    }
    return 0;
 }
test_files_destroy()
static int test_files_destroy (struct ast_test * test, char * dir_name, struct _filenames * filenames) static
Definition at line 49 of file test_file.c.
References ast_test_status_update, AST_VECTOR_CALLBACK_VOID, AST_VECTOR_FREE, and rm_file().
Referenced by AST_TEST_DEFINE(), and test_files_create().
 {
    int res;
    if (filenames) {
       AST_VECTOR_CALLBACK_VOID(filenames, rm_file);
       AST_VECTOR_FREE(filenames);
    }
    if ((res = rmdir(dir_name)) < 0) {
       ast_test_status_update(test, "Failed to remove directory: %s\n", dir_name);
    }
    return res;
 }
test_files_get_one()
static char* test_files_get_one (struct _filenames * filenames, int num) static
Definition at line 112 of file test_file.c.
References ast_random(), ast_str_buffer(), and AST_VECTOR_GET.
Referenced by AST_TEST_DEFINE().
 {
    /* Every file is in a directory and contains a '/' so okay to do this */
    return strrchr(ast_str_buffer(
              AST_VECTOR_GET(filenames, ast_random() % (num - 1))), '/') + 1;
 }
unload_module()
static int unload_module (void) static
Definition at line 183 of file test_file.c.
References AST_TEST_UNREGISTER.
 {
    AST_TEST_UNREGISTER(read_dirs_test);
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "File test module" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, } static
Definition at line 195 of file test_file.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 195 of file test_file.c.