Asterisk - The Open Source Telephony Project: test_bridging.c File Reference
test_bridging.c File Reference
Bridging unit tests.
#include "asterisk.h"
#include "asterisk/module.h"
#include "asterisk/test.h"
#include "asterisk/channel.h"
#include "asterisk/time.h"
#include "asterisk/bridge.h"
#include "asterisk/bridge_basic.h"
#include "asterisk/features.h"
#include "asterisk/format_cache.h"
Data Structures
struct test_bridging_chan_pvt
A private structure for the test channel.
Macros
#define CHANNEL_TECH_NAME "BridgingTestChannel"
#define HANGUP_CHANNEL(channel)
Hang up a test channel safely.
#define START_ALICE(channel, pvt) START_CHANNEL(channel, pvt, "Alice", "100")
Create a test_bridging_chan_tech for Alice.
#define START_BOB(channel, pvt) START_CHANNEL(channel, pvt, "Bob", "200")
Create a test_bridging_chan_tech for Bob.
#define START_CHANNEL(channel, pvt, name, number)
#define TEST_CATEGORY "/main/bridging/"
#define TEST_CHANNEL_FORMAT ast_format_slin
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
AST_TEST_DEFINE (test_bridging_deferred_queue)
static int load_module (void)
static void safe_bridge_destroy (struct ast_bridge *bridge)
static void safe_channel_release (struct ast_channel *chan)
static void stream_periodic_frames (struct ast_channel *chan, int ms, int interval_ms)
static int test_bridging_chan_hangup (struct ast_channel *chan)
Callback function for when a channel is hung up.
static int test_bridging_chan_indicate (struct ast_channel *chan, int condition, const void *data, size_t datalen)
Callback function for when a frame is written to a channel.
static void test_nanosleep (int secs, long nanosecs)
static int unload_module (void)
static void wait_for_bridged (struct ast_channel *channel)
Wait until a channel is bridged.
static void wait_for_empty_queue (struct ast_channel *channel)
Wait until a channel has no frames on its read queue.
static void wait_for_unbridged (struct ast_channel *channel)
Wait until a channel is not bridged.
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Bridging Unit Tests" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, }
static const struct ast_module_info * ast_module_info = &__mod_info
static struct ast_channel_tech test_bridging_chan_tech
A channel technology used for the unit tests.
Detailed Description
Bridging unit tests.
Author
Joshua Colp jcolp.nosp@m.@dig.nosp@m.ium.c.nosp@m.om
Definition in file test_bridging.c.
Macro Definition Documentation
CHANNEL_TECH_NAME
#define CHANNEL_TECH_NAME "BridgingTestChannel"
Definition at line 45 of file test_bridging.c.
HANGUP_CHANNEL
#define HANGUP_CHANNEL (channel)
Hang up a test channel safely.
Definition at line 153 of file test_bridging.c.
Referenced by AST_TEST_DEFINE().
START_ALICE
#define START_ALICE (channel, pvt) START_CHANNEL(channel, pvt, "Alice", "100")
Create a test_bridging_chan_tech for Alice.
Definition at line 134 of file test_bridging.c.
Referenced by AST_TEST_DEFINE().
START_BOB
#define START_BOB (channel, pvt) START_CHANNEL(channel, pvt, "Bob", "200")
Create a test_bridging_chan_tech for Bob.
Definition at line 137 of file test_bridging.c.
Referenced by AST_TEST_DEFINE().
START_CHANNEL
#define START_CHANNEL (channel, pvt, name, number)
Definition at line 139 of file test_bridging.c.
TEST_CATEGORY
#define TEST_CATEGORY "/main/bridging/"
Definition at line 43 of file test_bridging.c.
Referenced by AST_TEST_DEFINE().
TEST_CHANNEL_FORMAT
#define TEST_CHANNEL_FORMAT ast_format_slin
Definition at line 47 of file test_bridging.c.
Referenced by load_module().
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 290 of file test_bridging.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 290 of file test_bridging.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 290 of file test_bridging.c.
AST_TEST_DEFINE()
AST_TEST_DEFINE (test_bridging_deferred_queue)
Definition at line 198 of file test_bridging.c.
References ast_bridge_basic_new(), ast_bridge_depart(), ast_bridge_impart(), AST_BRIDGE_IMPART_CHAN_DEPARTABLE, AST_CONTROL_T38_PARAMETERS, AST_FRAME_CONTROL, ast_queue_frame(), AST_T38_REQUEST_NEGOTIATE, AST_TEST_NOT_RUN, AST_TEST_PASS, test_bridging_chan_pvt::condition, ast_frame::frametype, HANGUP_CHANNEL, test_bridging_chan_pvt::indicated, sip_to_pjsip::info(), NULL, RAII_VAR, ast_control_t38_parameters::request_response, safe_bridge_destroy(), safe_channel_release(), START_ALICE, START_BOB, stream_periodic_frames(), TEST_CATEGORY, TEST_EXECUTE, TEST_INIT, wait_for_bridged(), wait_for_empty_queue(), and wait_for_unbridged().
 {
    RAII_VAR(struct ast_channel *, chan_alice, NULL, safe_channel_release);
    struct test_bridging_chan_pvt *alice_pvt;
       struct ast_control_t38_parameters t38_parameters = {
          .request_response = AST_T38_REQUEST_NEGOTIATE,
       };
       struct ast_frame frame = {
          .frametype = AST_FRAME_CONTROL,
          .subclass.integer = AST_CONTROL_T38_PARAMETERS,
          .data.ptr = &t38_parameters,
          .datalen = sizeof(t38_parameters),
       };
    RAII_VAR(struct ast_channel *, chan_bob, NULL, safe_channel_release);
    struct test_bridging_chan_pvt *bob_pvt;
    RAII_VAR(struct ast_bridge *, bridge1, NULL, safe_bridge_destroy);
    switch (cmd) {
    case TEST_INIT:
       info->name = __func__;
       info->category = TEST_CATEGORY;
       info->summary = "Test that deferred frames from a channel in a bridge get written";
       info->description =
          "This test creates two channels, queues a deferrable frame on one, places it into\n"
          "a bridge, confirms the frame was read by the bridge, adds the second channel to the\n"
          "bridge, and makes sure the deferred frame is written to it.";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    /* Create the bridges */
    bridge1 = ast_bridge_basic_new();
    ast_test_validate(test, bridge1 != NULL);
    /* Create channels that will go into the bridge */
    START_ALICE(chan_alice, alice_pvt);
    START_BOB(chan_bob, bob_pvt);
    bob_pvt->condition = AST_CONTROL_T38_PARAMETERS;
    /* Bridge alice and wait for the frame to be deferred */
    ast_test_validate(test, !ast_bridge_impart(bridge1, chan_alice, NULL, NULL, AST_BRIDGE_IMPART_CHAN_DEPARTABLE));
    wait_for_bridged(chan_alice);
    ast_queue_frame(chan_alice, &frame);
    wait_for_empty_queue(chan_alice);
    /* Bridge bob for a second so it can receive the deferred T.38 request negotiate frame */
    ast_test_validate(test, !ast_bridge_impart(bridge1, chan_bob, NULL, NULL, AST_BRIDGE_IMPART_CHAN_DEPARTABLE));
    wait_for_bridged(chan_bob);
    stream_periodic_frames(chan_alice, 1000, 20);
    ast_test_validate(test, !ast_bridge_depart(chan_bob));
    wait_for_unbridged(chan_bob);
    /* Ensure that we received the expected indications while it was in there (request to negotiate, and to terminate) */
    ast_test_validate(test, bob_pvt->indicated == 2);
    /* Now remove alice since we are done */
    ast_test_validate(test, !ast_bridge_depart(chan_alice));
    wait_for_unbridged(chan_alice);
    /* Hangup the channels */
    HANGUP_CHANNEL(chan_alice);
    HANGUP_CHANNEL(chan_bob);
    return AST_TEST_PASS;
 }
load_module()
static int load_module (void) static
Definition at line 276 of file test_bridging.c.
References ast_channel_register(), ast_format_cap_alloc, ast_format_cap_append, AST_FORMAT_CAP_FLAG_DEFAULT, AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, AST_TEST_REGISTER, ast_channel_tech::capabilities, and TEST_CHANNEL_FORMAT.
 {
    test_bridging_chan_tech.capabilities = ast_format_cap_alloc(AST_FORMAT_CAP_FLAG_DEFAULT);
    if (!test_bridging_chan_tech.capabilities) {
       return AST_MODULE_LOAD_DECLINE;
    }
    ast_format_cap_append(test_bridging_chan_tech.capabilities, TEST_CHANNEL_FORMAT, 0);
    ast_channel_register(&test_bridging_chan_tech);
    AST_TEST_REGISTER(test_bridging_deferred_queue);
    return AST_MODULE_LOAD_SUCCESS;
 }
safe_bridge_destroy()
static void safe_bridge_destroy (struct ast_bridge * bridge) static
Definition at line 168 of file test_bridging.c.
References ast_bridge_destroy().
Referenced by AST_TEST_DEFINE().
 {
    if (!bridge) {
       return;
    }
    ast_bridge_destroy(bridge, 0);
 }
safe_channel_release()
static void safe_channel_release (struct ast_channel * chan) static
Definition at line 160 of file test_bridging.c.
References ast_channel_release().
Referenced by AST_TEST_DEFINE().
 {
    if (!chan) {
       return;
    }
    ast_channel_release(chan);
 }
stream_periodic_frames()
static void stream_periodic_frames (struct ast_channel * chan, int ms, int interval_ms) static
Definition at line 176 of file test_bridging.c.
References ast_assert, ast_null_frame, ast_queue_frame(), NULL, and test_nanosleep().
Referenced by AST_TEST_DEFINE().
 {
    long nanosecs;
    ast_assert(chan != NULL);
    ast_assert(0 < ms);
    ast_assert(0 < interval_ms);
    nanosecs = interval_ms * 1000000L;
    while (0 < ms) {
       ast_queue_frame(chan, &ast_null_frame);
       if (interval_ms < ms) {
          ms -= interval_ms;
       } else {
          nanosecs = ms * 1000000L;
          ms = 0;
       }
       test_nanosleep(0, nanosecs);
    }
 }
test_bridging_chan_hangup()
static int test_bridging_chan_hangup (struct ast_channel * chan) static
Callback function for when a channel is hung up.
Definition at line 70 of file test_bridging.c.
References ast_channel_tech_pvt(), ast_channel_tech_pvt_set(), ast_free, and NULL.
 {
    struct test_bridging_chan_pvt *test_pvt = ast_channel_tech_pvt(chan);
    ast_free(test_pvt);
    ast_channel_tech_pvt_set(chan, NULL);
    return 0;
 }
test_bridging_chan_indicate()
static int test_bridging_chan_indicate (struct ast_channel * chan, int condition, const void * data, size_t datalen) static
Callback function for when a frame is written to a channel.
Definition at line 58 of file test_bridging.c.
References ast_channel_tech_pvt(), test_bridging_chan_pvt::condition, and test_bridging_chan_pvt::indicated.
 {
    struct test_bridging_chan_pvt *test_pvt = ast_channel_tech_pvt(chan);
    if (condition == test_pvt->condition) {
       test_pvt->indicated++;
    }
    return 0;
 }
test_nanosleep()
static void test_nanosleep (int secs, long nanosecs) static
Definition at line 89 of file test_bridging.c.
References errno.
Referenced by stream_periodic_frames(), wait_for_bridged(), wait_for_empty_queue(), and wait_for_unbridged().
 {
    struct timespec sleep_time = {secs, nanosecs};
    while ((nanosleep(&sleep_time, &sleep_time) == -1) && (errno == EINTR)) {
    }
 }
unload_module()
static int unload_module (void) static
Definition at line 265 of file test_bridging.c.
References ao2_cleanup, ast_channel_unregister(), AST_TEST_UNREGISTER, ast_channel_tech::capabilities, and NULL.
 {
    AST_TEST_UNREGISTER(test_bridging_deferred_queue);
    ast_channel_unregister(&test_bridging_chan_tech);
    ao2_cleanup(test_bridging_chan_tech.capabilities);
    test_bridging_chan_tech.capabilities = NULL;
    return 0;
 }
wait_for_bridged()
static void wait_for_bridged (struct ast_channel * channel) static
Wait until a channel is bridged.
Definition at line 98 of file test_bridging.c.
References ast_channel_is_bridged(), ast_channel_lock, ast_channel_unlock, and test_nanosleep().
Referenced by AST_TEST_DEFINE().
 {
    ast_channel_lock(channel);
    while (!ast_channel_is_bridged(channel)) {
       ast_channel_unlock(channel);
       test_nanosleep(0, 1000000);
       ast_channel_lock(channel);
    }
    ast_channel_unlock(channel);
 }
wait_for_empty_queue()
static void wait_for_empty_queue (struct ast_channel * channel) static
Wait until a channel has no frames on its read queue.
Definition at line 122 of file test_bridging.c.
References ast_channel_lock, ast_channel_readq(), ast_channel_unlock, AST_LIST_EMPTY, and test_nanosleep().
Referenced by AST_TEST_DEFINE().
 {
    ast_channel_lock(channel);
    while (!AST_LIST_EMPTY(ast_channel_readq(channel))) {
       ast_channel_unlock(channel);
       test_nanosleep(0, 1000000);
       ast_channel_lock(channel);
    }
    ast_channel_unlock(channel);
 }
wait_for_unbridged()
static void wait_for_unbridged (struct ast_channel * channel) static
Wait until a channel is not bridged.
Definition at line 110 of file test_bridging.c.
References ast_channel_is_bridged(), ast_channel_lock, ast_channel_unlock, and test_nanosleep().
Referenced by AST_TEST_DEFINE().
 {
    ast_channel_lock(channel);
    while (ast_channel_is_bridged(channel)) {
       ast_channel_unlock(channel);
       test_nanosleep(0, 1000000);
       ast_channel_lock(channel);
    }
    ast_channel_unlock(channel);
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Bridging Unit Tests" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, } static
Definition at line 290 of file test_bridging.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 290 of file test_bridging.c.
test_bridging_chan_tech
struct ast_channel_tech test_bridging_chan_tech static
A channel technology used for the unit tests.
Definition at line 81 of file test_bridging.c.