Asterisk - The Open Source Telephony Project: isdn_lib.c File Reference
isdn_lib.c File Reference
Interface to mISDN.
#include <syslog.h>
#include <sys/time.h>
#include <mISDNuser/isdn_debug.h>
#include "isdn_lib_intern.h"
#include "isdn_lib.h"
#include "asterisk/causes.h"
#include <mISDNuser/net_l2.h>
#include <mISDNuser/tone.h>
#include <unistd.h>
#include <semaphore.h>
#include <pthread.h>
#include <signal.h>
Data Structures
struct misdn_lib
Macros
#define ARRAY_LEN(a) (sizeof(a) / sizeof(a[0]))
#define ECHOCAN_OFF 124
#define ECHOCAN_ON 123
#define ISDN_PID_L3_B_USER 0x430000ff
#define ISDN_PID_L4_B_USER 0x440000ff
#define MISDN_DEBUG 0
#define MISDN_DSP
#define MISDN_GEN_SILENCE
#define MISDN_IBUF_SIZE 512
#define RETURN(a, b) {retval=a; goto b;}
#define TONE_ALERT_CNT 41 /* 1 Sec */
#define TONE_ALERT_SILENCE_CNT 200 /* 4 Sec */
#define TONE_BUSY_CNT 20 /* ? */
#define TONE_BUSY_SILENCE_CNT 48 /* ? */
Enumerations
enum global_states { MISDN_INITIALIZING, MISDN_INITIALIZED }
Functions
static void bc_next_state_change (struct misdn_bchannel *bc, enum bchannel_state state)
char * bc_state2str (enum bchannel_state state)
void bc_state_change (struct misdn_bchannel *bc, enum bchannel_state state)
int bchdev_echocancel_activate (struct misdn_bchannel *dev)
void bchdev_echocancel_deactivate (struct misdn_bchannel *dev)
static char * bearer2str (int cap)
static int clean_up_bc (struct misdn_bchannel *bc)
static void clear_l3 (struct misdn_stack *stack)
static msg_t * create_l2msg (int prim, int dinfo, int size)
msg_t * create_l3msg (int prim, int mt, int dinfo, int size, int ntmode)
static int create_process (int midev, struct misdn_bchannel *bc)
static int do_tone (struct misdn_bchannel *bc, int len)
static void dump_chan_list (struct misdn_stack *stack)
void ec_chunk (struct misdn_bchannel *bc, unsigned char *rxchunk, unsigned char *txchunk, int chunk_size)
static void empty_bc (struct misdn_bchannel *bc)
static void empty_chan_in_stack (struct misdn_stack *stack, int channel)
static const char * fac2str (enum FacFunction facility)
static msg_t * fetch_msg (int midev)
static struct misdn_bchannel * find_bc_by_addr (unsigned long addr)
static struct misdn_bchannel * find_bc_by_confid (unsigned long confid)
struct misdn_bchannel * find_bc_by_l3id (struct misdn_stack *stack, unsigned long l3id)
static struct misdn_bchannel * find_bc_by_masked_l3id (struct misdn_stack *stack, unsigned long l3id, unsigned long mask)
static int find_free_chan_in_stack (struct misdn_stack *stack, struct misdn_bchannel *bc, int channel, int dec)
static struct misdn_stack * find_stack_by_addr (int addr)
static struct misdn_stack * find_stack_by_mgr (manager_t *mgr_nt)
static struct misdn_stack * find_stack_by_port (int port)
static char * flip_buf_bits (char *buf, int len)
struct misdn_stack * get_misdn_stack (void)
void get_show_stack_details (int port, char *buf)
struct misdn_stack * get_stack_by_bc (struct misdn_bchannel *bc)
static int handle_bchan (msg_t *msg)
static int handle_cr (struct misdn_stack *stack, iframe_t *frm)
static int handle_err (msg_t *msg)
static int handle_event_nt (void *dat, void *arg)
static int handle_event_te (struct misdn_bchannel *bc, enum event_e event, iframe_t *frm)
static int handle_frm_nt (msg_t *msg)
static int handle_frm_te (msg_t *msg)
static int handle_l1 (msg_t *msg)
static int handle_l2 (msg_t *msg)
static int handle_mgmt (msg_t *msg)
static int handle_timers (msg_t *msg)
static int init_bc (struct misdn_stack *stack, struct misdn_bchannel *bc, int midev, int port, int bidx)
static void init_flip_bits (void)
void isdn_lib_stop_dtmf (struct misdn_bchannel *bc)
void isdn_lib_update_ec (struct misdn_bchannel *bc)
void isdn_lib_update_rxgain (struct misdn_bchannel *bc)
void isdn_lib_update_txgain (struct misdn_bchannel *bc)
void manager_bchannel_activate (struct misdn_bchannel *bc)
void manager_bchannel_cleanup (struct misdn_bchannel *bc)
void manager_bchannel_deactivate (struct misdn_bchannel *bc)
void manager_bchannel_setup (struct misdn_bchannel *bc)
void manager_clean_bc (struct misdn_bchannel *bc)
void manager_ec_disable (struct misdn_bchannel *bc)
void manager_ec_enable (struct misdn_bchannel *bc)
static void manager_event_handler (void *arg)
struct misdn_bchannel * manager_find_bc_by_pid (int pid)
char * manager_isdn_get_info (enum event_e event)
int manager_isdn_handler (iframe_t *frm, msg_t *msg)
void manager_ph_control (struct misdn_bchannel *bc, int c1, int c2)
void manager_ph_control_block (struct misdn_bchannel *bc, int c1, void *c2, int c2_len)
int misdn_cap_is_speech (int cap)
void misdn_dump_chanlist (void)
int misdn_inband_avail (struct misdn_bchannel *bc)
void misdn_join_conf (struct misdn_bchannel *bc, int conf_id)
void misdn_lib_bridge (struct misdn_bchannel *bc1, struct misdn_bchannel *bc2)
void misdn_lib_destroy (void)
void misdn_lib_echo (struct misdn_bchannel *bc, int onoff)
struct misdn_bchannel * misdn_lib_find_held_bc (int port, int l3_id)
Find a held call's B channel record.
struct misdn_bchannel * misdn_lib_get_free_bc (int port, int channel, int inout, int dec)
static int misdn_lib_get_l1_down (struct misdn_stack *stack)
static int misdn_lib_get_l1_up (struct misdn_stack *stack)
static int misdn_lib_get_l2_down (struct misdn_stack *stack)
int misdn_lib_get_l2_up (struct misdn_stack *stack)
int misdn_lib_get_maxchans (int port)
int misdn_lib_get_port_down (int port)
int misdn_lib_get_port_info (int port)
int misdn_lib_get_port_up (int port)
static int misdn_lib_get_short_status (struct misdn_stack *stack)
int misdn_lib_init (char *portlist, struct misdn_lib_iface *iface, void *user_data)
int misdn_lib_is_port_blocked (int port)
int misdn_lib_is_ptp (int port)
static void misdn_lib_isdn_event_catcher (void *arg)
void misdn_lib_isdn_l1watcher (int port)
void misdn_lib_log_ies (struct misdn_bchannel *bc)
int misdn_lib_maxports_get (void)
void misdn_lib_nt_debug_init (int flags, char *file)
void misdn_lib_nt_keepcalls (int kc)
int misdn_lib_pid_restart (int pid)
int misdn_lib_port_block (int port)
int misdn_lib_port_is_nt (int port)
int misdn_lib_port_is_pri (int port)
int misdn_lib_port_restart (int port)
int misdn_lib_port_unblock (int port)
int misdn_lib_port_up (int port, int check)
void misdn_lib_reinit_nt_stack (int port)
void misdn_lib_release (struct misdn_bchannel *bc)
int misdn_lib_send_event (struct misdn_bchannel *bc, enum event_e event)
int misdn_lib_send_restart (int port, int channel)
void misdn_lib_send_tone (struct misdn_bchannel *bc, enum tone_e tone)
void misdn_lib_split_bridge (struct misdn_bchannel *bc1, struct misdn_bchannel *bc2)
void misdn_lib_tone_generator_start (struct misdn_bchannel *bc)
void misdn_lib_tone_generator_stop (struct misdn_bchannel *bc)
int misdn_lib_tx2misdn_frm (struct misdn_bchannel *bc, void *data, int len)
void misdn_make_dummy (struct misdn_bchannel *dummybc, int port, int l3id, int nt, int channel)
static void misdn_send_lock (struct misdn_bchannel *bc)
static void misdn_send_unlock (struct misdn_bchannel *bc)
void misdn_split_conf (struct misdn_bchannel *bc, int conf_id)
void misdn_tx_jitter (struct misdn_bchannel *bc, int len)
static void prepare_bc (struct misdn_bchannel *bc, int channel)
static int release_cr (struct misdn_stack *stack, mISDNuser_head_t *hh)
static int send_msg (int midev, struct misdn_bchannel *bc, msg_t *dmsg)
static int set_chan_in_stack (struct misdn_stack *stack, int channel)
static int setup_bc (struct misdn_bchannel *bc)
static void stack_destroy (struct misdn_stack *stack)
void stack_holder_add (struct misdn_stack *stack, struct misdn_bchannel *holder)
struct misdn_bchannel * stack_holder_find (struct misdn_stack *stack, unsigned long l3id)
void stack_holder_remove (struct misdn_stack *stack, struct misdn_bchannel *holder)
static struct misdn_stack * stack_init (int midev, int port, int ptp)
void te_lib_destroy (int midev)
static int te_lib_init (void)
static int test_inuse (struct misdn_bchannel *bc)
Variables
enum event_response_e(* cb_event)(enum event_e event, struct misdn_bchannel *bc, void *user_data)
int(* cb_jb_empty)(struct misdn_bchannel *bc, char *buffer, int len)
void(* cb_log)(int level, int port, char *tmpl,...)
static int entity
static char flip_table [256]
static struct misdn_lib * glob_mgr
static enum global_states global_state =MISDN_INITIALIZING
static sem_t handler_started
struct isdn_msg msgs_g []
static int mypid =1
static int new_te_id = 0
static int nt_err_cnt =0
static char tone_425_flip [TONE_425_SIZE]
static char tone_silence_flip [TONE_SILENCE_SIZE]
Detailed Description
Interface to mISDN.
Author
Christian Richter crich.nosp@m.@ber.nosp@m.onet..nosp@m.com
Definition in file isdn_lib.c.
Macro Definition Documentation
ARRAY_LEN
#define ARRAY_LEN (a) (sizeof(a) / sizeof(a[0]))
Definition at line 42 of file isdn_lib.c.
Referenced by __analog_ss_thread(), __ast_cli_generator(), __init_manager(), __unload_module(), _sip_show_peer(), aco_init(), action_dahdishowchannels(), action_events(), add_exten_to_pattern_tree(), add_required_respheader(), add_static_payload(), ademco_verify_checksum(), adpcm_sample(), alarm2str(), alaw_sample(), allocate_dns_record(), analog_cidtype_to_str(), analog_sigtype_to_str(), analog_ss_thread(), analog_str_to_cidtype(), analog_str_to_sigtype(), analyse_softmix_stats(), ao2_container_unregister(), aoc_s_add_entry(), aoc_shutdown(), ast_aoc_add_unit_entry(), ast_aoc_cli_init(), ast_ari_applications_subscribe_cb(), ast_ari_applications_unsubscribe_cb(), ast_ari_asterisk_get_info_cb(), ast_ari_bridges_add_channel_cb(), ast_ari_bridges_play_cb(), ast_ari_bridges_play_with_id_cb(), ast_ari_bridges_remove_channel_cb(), ast_ari_channels_play_cb(), ast_ari_channels_play_with_id_cb(), ast_ari_cli_register(), ast_ari_cli_unregister(), ast_ari_events_event_websocket_ws_attempted_cb(), ast_ari_events_event_websocket_ws_established_cb(), ast_ari_events_user_event_cb(), ast_bridge_channel_feature_digit(), ast_bridge_features_do(), ast_bridge_features_enable(), ast_bridge_features_register(), ast_bridge_features_unregister(), ast_bridge_interval_register(), ast_bridge_interval_unregister(), ast_bridging_init(), ast_builtins_init(), ast_cause2str(), ast_cel_str_to_event_type(), ast_channels_init(), ast_cli_netstats(), ast_codec_init(), ast_compile_ael2(), ast_connected_line_source_describe(), ast_connected_line_source_name(), ast_connected_line_source_parse(), ast_describe_caller_presentation(), ast_dsp_set_call_progress_zone(), ast_dynamic_logger_level(), ast_event_get_ie_pltype(), ast_event_get_ie_type_name(), ast_event_get_type_name(), ast_extension_state2str(), ast_file_init(), ast_get_http_method(), ast_hook_send_action(), ast_http_ftype2mtype(), ast_image_init(), ast_jb_get_impl(), ast_local_init(), ast_logger_get_channels(), ast_logger_unregister_level(), ast_media_cache_init(), ast_msg_data_alloc2(), ast_named_caller_presentation(), ast_parse_caller_presentation(), ast_party_name_charset_describe(), ast_party_name_charset_parse(), ast_party_name_charset_str(), ast_presence_state2str(), ast_presence_state_val(), ast_redirecting_reason_describe(), ast_redirecting_reason_name(), ast_redirecting_reason_parse(), ast_res_pjsip_cleanup_options_handling(), ast_res_pjsip_destroy_configuration(), ast_res_pjsip_init_options_handling(), ast_res_pjsip_initialize_configuration(), ast_rtp_instance_extmap_get_uri(), ast_rtp_instance_extmap_negotiate(), ast_security_event_severity_get_name(), ast_sendtext(), ast_sip_destroy_cli(), ast_sip_destroy_distributor(), ast_sip_destroy_scheduler(), ast_sip_destroy_sorcery_auth(), ast_sip_destroy_sorcery_location(), ast_sip_destroy_sorcery_transport(), ast_sip_get_contact_short_status_label(), ast_sip_get_contact_status_label(), ast_sip_get_distributor_serializer(), ast_sip_initialize_cli(), ast_sip_initialize_distributor(), ast_sip_initialize_scheduler(), ast_sip_initialize_sorcery_auth(), ast_sip_initialize_sorcery_location(), ast_sip_initialize_sorcery_transport(), ast_state_chan2dev(), ast_str2cause(), ast_str2tos(), ast_str_retrieve_variable(), ast_syslog_facility(), ast_syslog_facility_name(), ast_syslog_priority(), ast_syslog_priority_from_loglevel(), ast_syslog_priority_name(), AST_TEST_DEFINE(), ast_test_init(), ast_timing_init(), ast_to_misdn_reason(), ast_tos2str(), ast_tps_init(), ast_translate_init(), ast_utils_init(), ast_xmldoc_printable(), astdb_atexit(), astdb_init(), asterisk_daemon(), astman_append_headers(), astobj2_cleanup(), astobj2_init(), attended_transfer_dtor(), authority_to_str(), autopause2int(), available(), bearer2str(), block_msg_header(), bridge_channel_feature_digit_add(), bridge_cleanup(), bridge_snapshot_update(), bridges_scrape_cb(), build_cfg(), build_expression_queue(), cache_get_callno_locked(), callerid_read(), callerid_write(), cb_events(), cdr_engine_shutdown(), cel_snapshot_update_cb(), chan_pjsip_sendtext(), channel_snapshot_update(), channels_scrape_cb(), channels_shutdown(), check_blacklist(), cleanup_module(), clear_l3(), cli_init(), cli_shutdown(), cli_unload_cb(), close_logger(), codec_choose_from_prefs(), codec_pref_remove(), codec_pref_remove_index(), codec_shutdown(), common_exec(), complete_dpreply(), complete_ulimit(), conf_destroy_config(), conf_exec(), conf_load_config(), config_shutdown(), connectedline_read(), connectedline_write(), container_init(), convert_attribute_name_from_ldap(), convert_attribute_name_to_ldap(), corosync_show_config(), corosync_show_members(), cpg_confchg_cb(), crypto_init(), destroy_escs(), destroy_peer(), determine_starting_point(), dispatch_thread_handler(), distributor_pool_setup(), distributor_pool_shutdown(), do_message(), dtmf_features_flags_to_string(), dump_cause(), dump_chan_list(), dump_ies(), dundi_eid_zero(), dundi_ie2str(), dundi_query_read(), dundi_showframe(), empty_chan_in_stack(), endpoints_scrape_cb(), event2str(), exceptional_accept(), ext_cmp_pattern(), fac2str(), file_shutdown(), fill_rxgain(), fill_txgain(), find_alias(), find_bc_by_l3id(), find_bc_by_masked_l3id(), find_cache(), find_free_chan_in_stack(), find_full_alias(), find_sip_method(), find_subscription_type(), frame_drop_helper(), frame_trace_helper(), g722_sample(), g726_sample(), gather_softmix_stats(), gen_events(), generate_dns_answer(), generate_dns_header(), generate_dns_question(), get_allowed_field(), get_chan_by_ast_name(), get_esc(), get_folder_by_name(), get_perm(), get_pjsip_method(), geteventbyname(), getjustifybyname(), handle_cli_dynamic_level_test(), handle_cli_iax2_show_cache(), handle_cli_iax2_show_channels(), handle_cli_iax2_show_stats(), handle_cli_misdn_send_facility(), handle_cli_performance_test(), handle_cli_ulimit(), handle_input(), handle_jack_audio(), handle_logger_set_level(), handle_logger_show_channels(), handle_request_bye(), handle_request_invite(), hfp_parse_ciev(), hfp_parse_cind_indicator(), hfp_parse_clip(), hook_event_cb(), iax2_codec_pref_append_bitfield(), iax2_codec_pref_best_bitfield2cap(), iax2_codec_pref_convert(), iax2_codec_pref_format_bitfield_to_order_value(), iax2_codec_pref_index(), iax2_codec_pref_order_value_to_format_bitfield(), iax2_codec_pref_prepend(), iax2_codec_pref_remove_missing(), iax2_codec_pref_to_cap(), iax2_format_compatibility_best(), iax_ie2str(), iax_provflags2str(), iax_showframe(), iax_str2flags(), image_shutdown(), init_logger(), initialize_escs(), int2strat(), is_digest_algorithm_supported(), is_msg_var_blocked(), is_reserved_word(), jack_status_to_str(), jb_choose_impl(), jingle_action_hook(), jingle_action_session_terminate(), jingle_hangup(), keyset_translatebitmask(), load_features_config(), load_general_config(), load_module(), load_parking_ui(), load_pbx(), load_pbx_app(), load_pbx_builtins(), load_pbx_functions_cli(), load_pbx_hangup_handler(), load_pbx_switch(), load_pbx_variables(), loadresult2str(), local_ast_moh_start(), local_shutdown(), logger_register_level(), main(), main_atexit(), make_components(), manager_shutdown(), mbox(), media_cache_shutdown(), milliwatt_generate(), minivm_accmess_exec(), minivm_greet_exec(), minivm_mwi_exec(), minivm_notify_exec(), minivm_record_exec(), misdn_get_ch_state(), misdn_lib_get_free_bc(), misdn_lib_init(), mkintf(), mute_fragment(), nominal_test(), not_allowed(), off_nominal_test(), parse_naptr(), parse_sip_options(), pjsip_channel_cli_register(), pjsip_channel_cli_unregister(), play_message_by_id(), process_dahdi(), process_echocancel(), process_opcode(), process_returncode(), prometheus_config_post_apply(), queue_voice_frame(), rb_ao2_destroy(), reason_code_to_cause(), reason_code_to_str(), redirecting_read(), redirecting_write(), register_config_cli(), reload(), res_sdp_srtp_get_attr(), rotate_file(), send_message(), sendtext_exec(), set_chan_in_stack(), set_event(), set_next_mime_type(), set_queue_result(), sip_reason_code_to_str(), sip_show_channel(), slin16_sample(), slin8_sample(), stasis_cleanup(), stasis_init(), stir_shaken_certificate_load(), stir_shaken_certificate_unload(), stir_shaken_general_load(), stir_shaken_general_unload(), stir_shaken_store_load(), stir_shaken_store_unload(), str2desc(), str2limit(), strat2int(), strings_to_mask(), sub_channel_update_handler(), subscription_type2str(), test_chan_string(), test_chan_variable(), test_cleanup(), test_config_validity(), test_dtmf_amplitude_sweep(), test_dtmf_twist_sweep(), test_new_subscribe(), test_tone_amplitude_sweep(), test_traversal_nonsorted(), test_traversal_sorted(), threadstorage_init(), timing_shutdown(), tls_method_to_str(), tps_shutdown(), translate_shutdown(), transmit_softkeysetres(), try_merge_optimize_out(), two_bridge_attended_transfer(), udptl_rx_packet(), ulaw_sample(), unload_features_config(), unload_module(), unload_parking_ui(), unload_pbx(), unload_pbx_app(), unload_pbx_builtins(), unload_pbx_functions_cli(), unload_pbx_hangup_handler(), unload_pbx_switch(), unload_pbx_variables(), update_modem_bits(), user_authority_to_str(), utils_shutdown(), validate_metric(), vm_mailbox_snapshot_create(), wait_for_winner(), write_config_file(), xmldoc_get_syntax_type(), xmldoc_has_specialtags(), xmldoc_parse_specialtags(), xmldoc_update_config_option(), and xmpp_action_hook().
ECHOCAN_OFF
#define ECHOCAN_OFF 124
Definition at line 230 of file isdn_lib.c.
Referenced by manager_ec_disable().
ECHOCAN_ON
#define ECHOCAN_ON 123
Definition at line 229 of file isdn_lib.c.
Referenced by manager_ec_enable().
ISDN_PID_L3_B_USER
#define ISDN_PID_L3_B_USER 0x430000ff
Definition at line 246 of file isdn_lib.c.
Referenced by setup_bc().
ISDN_PID_L4_B_USER
#define ISDN_PID_L4_B_USER 0x440000ff
Definition at line 247 of file isdn_lib.c.
Referenced by setup_bc().
MISDN_DEBUG
#define MISDN_DEBUG 0
Definition at line 233 of file isdn_lib.c.
MISDN_DSP
#define MISDN_DSP
MISDN_GEN_SILENCE
#define MISDN_GEN_SILENCE
MISDN_IBUF_SIZE
#define MISDN_IBUF_SIZE 512
Definition at line 250 of file isdn_lib.c.
Referenced by init_bc().
RETURN
#define RETURN (a, b) {retval=a; goto b;}
Definition at line 3507 of file isdn_lib.c.
Referenced by misdn_lib_send_event().
TONE_ALERT_CNT
#define TONE_ALERT_CNT 41 /* 1 Sec */
Definition at line 253 of file isdn_lib.c.
TONE_ALERT_SILENCE_CNT
#define TONE_ALERT_SILENCE_CNT 200 /* 4 Sec */
Definition at line 254 of file isdn_lib.c.
TONE_BUSY_CNT
#define TONE_BUSY_CNT 20 /* ? */
Definition at line 256 of file isdn_lib.c.
TONE_BUSY_SILENCE_CNT
#define TONE_BUSY_SILENCE_CNT 48 /* ? */
Definition at line 257 of file isdn_lib.c.
Enumeration Type Documentation
global_states
enum global_states
Enumerator
MISDN_INITIALIZING
MISDN_INITIALIZED
Definition at line 194 of file isdn_lib.c.
                    {
    MISDN_INITIALIZING,
    MISDN_INITIALIZED
 } ;
Function Documentation
bc_next_state_change()
static void bc_next_state_change (struct misdn_bchannel * bc, enum bchannel_state state) static
Definition at line 659 of file isdn_lib.c.
References bc_state2str(), cb_log, misdn_bchannel::next_bc_state, misdn_bchannel::port, and state.
Referenced by misdn_lib_bridge().
 {
    cb_log(5,bc->port,"BC_NEXT_STATE_CHANGE: from:%s to:%s\n",
           bc_state2str(bc->next_bc_state),
           bc_state2str(state) );
    bc->next_bc_state=state;
 }
bc_state2str()
char* bc_state2str (enum bchannel_state state)
Definition at line 617 of file isdn_lib.c.
References BCHAN_ACTIVATED, BCHAN_BRIDGED, BCHAN_CLEANED, BCHAN_EMPTY, BCHAN_ERROR, and BCHAN_RELEASE.
Referenced by bc_next_state_change(), bc_state_change(), cb_events(), misdn_lib_send_event(), misdn_lib_split_bridge(), misdn_lib_tx2misdn_frm(), print_bc_info(), and setup_bc().
{
    int i;
    struct bchan_state_s {
       char *n;
       enum bchannel_state s;
    } states[] = {
       {"BCHAN_CLEANED", BCHAN_CLEANED },
       {"BCHAN_EMPTY", BCHAN_EMPTY},
       {"BCHAN_ACTIVATED", BCHAN_ACTIVATED},
       {"BCHAN_BRIDGED", BCHAN_BRIDGED},
       {"BCHAN_RELEASE", BCHAN_RELEASE},
       {"BCHAN_ERROR", BCHAN_ERROR}
    };
    for (i=0; i< sizeof(states)/sizeof(struct bchan_state_s); i++)
       if ( states[i].s == state)
          return states[i].n;
    return "UNKNOWN";
 }
bc_state_change()
void bc_state_change (struct misdn_bchannel * bc, enum bchannel_state state)
Definition at line 639 of file isdn_lib.c.
References misdn_bchannel::bc_state, bc_state2str(), BCHAN_ACTIVATED, BCHAN_BRIDGED, BCHAN_EMPTY, cb_log, misdn_bchannel::conf_id, misdn_bchannel::l3_id, misdn_join_conf(), misdn_bchannel::next_bc_state, misdn_bchannel::port, and state.
Referenced by clean_up_bc(), init_bc(), manager_bchannel_deactivate(), misdn_join_conf(), misdn_lib_send_event(), misdn_split_conf(), and setup_bc().
 {
    cb_log(5,bc->port,"BC_STATE_CHANGE: l3id:%x from:%s to:%s\n",
       bc->l3_id,
           bc_state2str(bc->bc_state),
           bc_state2str(state) );
    switch (state) {
       case BCHAN_ACTIVATED:
          if (bc->next_bc_state ==  BCHAN_BRIDGED) {
             misdn_join_conf(bc, bc->conf_id);
             bc->next_bc_state = BCHAN_EMPTY;
             return;
          }
       default:
          bc->bc_state=state;
          break;
    }
 }
bchdev_echocancel_activate()
int bchdev_echocancel_activate (struct misdn_bchannel * dev)
bchdev_echocancel_deactivate()
void bchdev_echocancel_deactivate (struct misdn_bchannel * dev)
bearer2str()
static char* bearer2str (int cap) static
Definition at line 290 of file isdn_lib.c.
References INFO_CAPABILITY_AUDIO_3_1K, INFO_CAPABILITY_DIGITAL_RESTRICTED, INFO_CAPABILITY_DIGITAL_UNRESTRICTED, and INFO_CAPABILITY_SPEECH.
Referenced by misdn_lib_log_ies().
{
    static char *bearers[]={
       "Speech",
       "Audio 3.1k",
       "Unres Digital",
       "Res Digital",
       "Unknown Bearer"
    };
    switch (cap) {
    case INFO_CAPABILITY_SPEECH:
       return bearers[0];
       break;
    case INFO_CAPABILITY_AUDIO_3_1K:
       return bearers[1];
       break;
    case INFO_CAPABILITY_DIGITAL_UNRESTRICTED:
       return bearers[2];
       break;
    case INFO_CAPABILITY_DIGITAL_RESTRICTED:
       return bearers[3];
       break;
    default:
       return bearers[4];
       break;
    }
 }
clean_up_bc()
static int clean_up_bc (struct misdn_bchannel * bc) static
Definition at line 815 of file isdn_lib.c.
References misdn_bchannel::b_stid, misdn_bchannel::bc_state, bc_state_change(), BCHAN_CLEANED, buff, cb_log, get_stack_by_bc(), misdn_bchannel::layer_id, manager_bchannel_deactivate(), manager_ec_disable(), misdn_stack::midev, NULL, misdn_bchannel::pid, misdn_stack::port, and misdn_bchannel::port.
Referenced by clear_l3(), handle_cr(), handle_event_nt(), handle_frm_te(), misdn_lib_release(), misdn_lib_send_event(), and misdn_lib_send_restart().
 {
    int ret=0;
    unsigned char buff[32];
    struct misdn_stack * stack;
    cb_log(3, bc->port, "$$$ CLEANUP CALLED pid:%d\n", bc->pid);
    stack=get_stack_by_bc(bc);
    if (!stack) return -1;
    switch (bc->bc_state ) {
    case BCHAN_CLEANED:
       cb_log(5, stack->port, "$$$ Already cleaned up bc with stid :%x\n", bc->b_stid);
       return -1;
    default:
       break;
    }
    cb_log(2, stack->port, "$$$ Cleaning up bc with stid :%x pid:%d\n", bc->b_stid, bc->pid);
    manager_ec_disable(bc);
    manager_bchannel_deactivate(bc);
    mISDN_write_frame(stack->midev, buff, bc->layer_id|FLG_MSG_TARGET|FLG_MSG_DOWN, MGR_DELLAYER | REQUEST, 0, 0, NULL, TIMEOUT_1SEC);
    bc->b_stid = 0;
    bc_state_change(bc, BCHAN_CLEANED);
    return ret;
 }
clear_l3()
static void clear_l3 (struct misdn_stack * stack) static
Definition at line 852 of file isdn_lib.c.
References ARRAY_LEN, misdn_stack::b_num, misdn_stack::bc, cb_event, clean_up_bc(), empty_bc(), empty_chan_in_stack(), EVENT_CLEANUP, misdn_bchannel::in_use, MAX_BCHANS, MISDN_INITIALIZED, and NULL.
Referenced by handle_mgmt(), and misdn_lib_port_restart().
 {
    int i;
    if (global_state == MISDN_INITIALIZED) {
       for (i = 0; i <= stack->b_num; ++i) {
          cb_event(EVENT_CLEANUP, &stack->bc[i], NULL);
          empty_bc(&stack->bc[i]);
          clean_up_bc(&stack->bc[i]);
          empty_chan_in_stack(stack, i + 1);
          stack->bc[i].in_use = 0;
       }
 #if defined(AST_MISDN_ENHANCEMENTS)
       for (i = MAX_BCHANS + 1; i < ARRAY_LEN(stack->bc); ++i) {
          empty_bc(&stack->bc[i]);
          empty_chan_in_stack(stack, i + 1);
          stack->bc[i].in_use = 0;
       }
 #endif   /* defined(AST_MISDN_ENHANCEMENTS) */
    }
 }
create_l2msg()
static msg_t* create_l2msg (int prim, int dinfo, int size) static
Definition at line 349 of file isdn_lib.c.
References NULL.
Referenced by misdn_lib_get_l2_down(), and misdn_lib_get_l2_up().
 {
    int i = 0;
    msg_t *dmsg;
    while(i < 10)
    {
       dmsg = prep_l3data_msg(prim, dinfo, size, 256, NULL);
       if (dmsg)
          return(dmsg);
       if (!i)
          printf("cannot allocate memory, trying again...\n");
       i++;
       usleep(300000);
    }
    printf("cannot allocate memory, system overloaded.\n");
    exit(-1);
 }
create_l3msg()
msg_t* create_l3msg (int prim, int mt, int dinfo, int size, int ntmode)
Definition at line 371 of file isdn_lib.c.
References NULL.
Referenced by build_alerting(), build_connect(), build_connect_acknowledge(), build_disconnect(), build_facility(), build_hold(), build_hold_acknowledge(), build_hold_reject(), build_information(), build_notify(), build_proceeding(), build_progress(), build_release(), build_release_complete(), build_restart(), build_resume(), build_resume_acknowledge(), build_resume_reject(), build_retrieve(), build_retrieve_acknowledge(), build_retrieve_reject(), build_setup(), build_setup_acknowledge(), build_status(), build_status_enquiry(), build_suspend(), build_suspend_acknowledge(), build_suspend_reject(), build_timeout(), build_user_information(), and handle_event_nt().
 {
    int i = 0;
    msg_t *dmsg;
    Q931_info_t *qi;
    iframe_t *frm;
    if (!ntmode)
       size = sizeof(Q931_info_t)+2;
    while(i < 10) {
       if (ntmode) {
          dmsg = prep_l3data_msg(prim, dinfo, size, 256, NULL);
          if (dmsg) {
             return(dmsg);
          }
       } else {
          dmsg = alloc_msg(size+256+mISDN_HEADER_LEN+DEFAULT_HEADROOM);
          if (dmsg)
          {
             memset(msg_put(dmsg,size+mISDN_HEADER_LEN), 0, size+mISDN_HEADER_LEN);
             frm = (iframe_t *)dmsg->data;
             frm->prim = prim;
             frm->dinfo = dinfo;
             qi = (Q931_info_t *)(dmsg->data + mISDN_HEADER_LEN);
             qi->type = mt;
             return(dmsg);
          }
       }
       if (!i) printf("cannot allocate memory, trying again...\n");
       i++;
       usleep(300000);
    }
    printf("cannot allocate memory, system overloaded.\n");
    exit(-1);
 }
create_process()
static int create_process (int midev, struct misdn_bchannel * bc) static
Definition at line 976 of file isdn_lib.c.
References cb_log, misdn_bchannel::channel, misdn_bchannel::channel_preselected, misdn_bchannel::dec, find_free_chan_in_stack(), get_stack_by_bc(), misdn_bchannel::l3_id, MAXPROCS, misdn_stack::nt, misdn_stack::port, misdn_stack::pri, misdn_stack::procids, misdn_stack::ptp, misdn_bchannel::te_choose_channel, and misdn_stack::upper_id.
Referenced by misdn_lib_send_event().
 {
    iframe_t ncr;
    int l3_id;
    int proc_id;
    struct misdn_stack *stack;
    stack = get_stack_by_bc(bc);
    if (stack->nt) {
       if (find_free_chan_in_stack(stack, bc, bc->channel_preselected ? bc->channel : 0, 0) < 0) {
          return -1;
       }
       cb_log(4, stack->port, " -->  found channel: %d\n", bc->channel);
       for (proc_id = 0; proc_id < MAXPROCS; ++proc_id) {
          if (stack->procids[proc_id] == 0) {
             break;
          }
       }
       if (proc_id == MAXPROCS) {
          cb_log(0, stack->port, "Couldn't Create New ProcId.\n");
          return -1;
       }
       stack->procids[proc_id] = 1;
       l3_id = 0xff00 | proc_id;
       bc->l3_id = l3_id;
       cb_log(3, stack->port, " --> new_l3id %x\n", l3_id);
    } else {
       if ((stack->pri && stack->ptp) || bc->te_choose_channel) {
          /* we know exactly which channels are in use */
          if (find_free_chan_in_stack(stack, bc, bc->channel_preselected ? bc->channel : 0, bc->dec) < 0) {
             return -1;
          }
          cb_log(2, stack->port, " -->  found channel: %d\n", bc->channel);
       } else {
          /* other phones could have made a call also on this port (ptmp) */
          bc->channel = 0xff;
       }
       /* if we are in te-mode, we need to create a process first */
       if (++new_te_id > 0xffff) {
          new_te_id = 0x0001;
       }
       l3_id = (entity << 16) | new_te_id;
       bc->l3_id = l3_id;
       cb_log(3, stack->port, "--> new_l3id %x\n", l3_id);
       /* send message */
       ncr.prim = CC_NEW_CR | REQUEST;
       ncr.addr = (stack->upper_id | FLG_MSG_DOWN);
       ncr.dinfo = l3_id;
       ncr.len = 0;
       mISDN_write(midev, &ncr, mISDN_HEADER_LEN + ncr.len, TIMEOUT_1SEC);
    }
    return l3_id;
 }
do_tone()
static int do_tone (struct misdn_bchannel * bc, int len) static
Definition at line 2282 of file isdn_lib.c.
References cb_event, cb_log, errno, EVENT_TONE_GENERATE, misdn_bchannel::generate_tone, len(), misdn_tx_jitter(), misdn_bchannel::nojitter, misdn_bchannel::tone_cnt, and misdn_lib::user_data.
Referenced by handle_bchan().
 {
    bc->tone_cnt=len;
    if (bc->generate_tone) {
       cb_event(EVENT_TONE_GENERATE, bc, glob_mgr->user_data);
       if ( !bc->nojitter ) {
          misdn_tx_jitter(bc,len);
       }
       return 1;
    }
    return 0;
 }
dump_chan_list()
static void dump_chan_list (struct misdn_stack * stack) static
Definition at line 464 of file isdn_lib.c.
References ARRAY_LEN, misdn_stack::b_num, misdn_stack::bc, cb_log, misdn_stack::channels, misdn_bchannel::in_use, MAX_BCHANS, and misdn_stack::port.
Referenced by empty_chan_in_stack(), find_free_chan_in_stack(), handle_cr(), misdn_dump_chanlist(), and set_chan_in_stack().
 {
    int i;
    for (i = 0; i <= stack->b_num; ++i) {
       cb_log(6, stack->port, "Idx:%d stack->cchan:%d in_use:%d Chan:%d\n",
          i, stack->channels[i], stack->bc[i].in_use, i + 1);
    }
 #if defined(AST_MISDN_ENHANCEMENTS)
    for (i = MAX_BCHANS + 1; i < ARRAY_LEN(stack->bc); ++i) {
       if (stack->bc[i].in_use) {
          cb_log(6, stack->port, "Idx:%d stack->cchan:%d REGISTER Chan:%d in_use\n",
             i, stack->channels[i], i + 1);
       }
    }
 #endif   /* defined(AST_MISDN_ENHANCEMENTS) */
 }
ec_chunk()
void ec_chunk (struct misdn_bchannel * bc, unsigned char * rxchunk, unsigned char * txchunk, int chunk_size)
empty_bc()
static void empty_bc (struct misdn_bchannel * bc) static
Set Default Bearer Caps
Definition at line 679 of file isdn_lib.c.
References misdn_bchannel::active, misdn_bchannel::AOCD_need_export, AST_CAUSE_NORMAL_CLEARING, misdn_bchannel::bframe_len, misdn_bchannel::caller, misdn_bchannel::capability, misdn_bchannel::cause, misdn_bchannel::channel, misdn_bchannel::channel_found, misdn_bchannel::conf_id, misdn_bchannel::connected, misdn_party_redirecting::count, misdn_bchannel::crypt, misdn_bchannel::crypt_key, misdn_bchannel::curprx, misdn_bchannel::curptx, misdn_bchannel::cw, misdn_bchannel::dec, misdn_bchannel::dialed, misdn_bchannel::display, misdn_bchannel::display_connected, misdn_bchannel::display_setup, misdn_bchannel::dummy, misdn_bchannel::early_bconnect, misdn_bchannel::ec_deftaps, misdn_bchannel::ec_enable, misdn_bchannel::fac_in, misdn_bchannel::fac_out, misdn_party_redirecting::from, misdn_bchannel::generate_tone, misdn_bchannel::hdlc, INFO_CAPABILITY_SPEECH, INFO_CODEC_ALAW, misdn_bchannel::info_dad, misdn_bchannel::infos_pending, misdn_bchannel::last_used, misdn_bchannel::law, mISDN_NOTIFY_CODE_INVALID, mISDN_REDIRECTING_REASON_UNKNOWN, misdn_bchannel::mode, misdn_party_id::name, misdn_bchannel::need_more_infos, misdn_bchannel::nodsp, misdn_bchannel::nojitter, misdn_bchannel::notify_description_code, NULL, misdn_party_dialing::number, misdn_party_id::number, misdn_party_id::number_plan, misdn_party_dialing::number_plan, misdn_party_id::number_type, misdn_party_dialing::number_type, NUMPLAN_ISDN, NUMTYPE_UNKNOWN, misdn_bchannel::orig, misdn_bchannel::out_cause, misdn_bchannel::outgoing_colp, misdn_party_id::presentation, misdn_bchannel::presentation, misdn_bchannel::progress_coding, misdn_bchannel::progress_indicator, misdn_bchannel::progress_location, misdn_bchannel::rate, misdn_party_redirecting::reason, misdn_bchannel::redirecting, misdn_bchannel::restart_channel, misdn_bchannel::rxgain, misdn_bchannel::send_dtmf, misdn_bchannel::sending_complete, misdn_bchannel::set_presentation, misdn_party_dialing::subaddress, misdn_party_id::subaddress, misdn_bchannel::te_choose_channel, misdn_bchannel::time_usec, misdn_party_redirecting::to, misdn_party_redirecting::to_changed, misdn_bchannel::tone_cnt, misdn_bchannel::txgain, misdn_bchannel::urate, misdn_bchannel::user1, misdn_bchannel::uu, and misdn_bchannel::uulen.
Referenced by clear_l3(), handle_cr(), handle_event_nt(), handle_frm_te(), init_bc(), manager_clean_bc(), misdn_lib_release(), misdn_lib_send_event(), and misdn_lib_send_restart().
 {
    bc->caller.presentation = 0;  /* allowed */
    bc->caller.number_plan = NUMPLAN_ISDN;
    bc->caller.number_type = NUMTYPE_UNKNOWN;
    bc->caller.name[0] = 0;
    bc->caller.number[0] = 0;
    bc->caller.subaddress[0] = 0;
    bc->connected.presentation = 0;  /* allowed */
    bc->connected.number_plan = NUMPLAN_ISDN;
    bc->connected.number_type = NUMTYPE_UNKNOWN;
    bc->connected.name[0] = 0;
    bc->connected.number[0] = 0;
    bc->connected.subaddress[0] = 0;
    bc->redirecting.from.presentation = 0; /* allowed */
    bc->redirecting.from.number_plan = NUMPLAN_ISDN;
    bc->redirecting.from.number_type = NUMTYPE_UNKNOWN;
    bc->redirecting.from.name[0] = 0;
    bc->redirecting.from.number[0] = 0;
    bc->redirecting.from.subaddress[0] = 0;
    bc->redirecting.to.presentation = 0;   /* allowed */
    bc->redirecting.to.number_plan = NUMPLAN_ISDN;
    bc->redirecting.to.number_type = NUMTYPE_UNKNOWN;
    bc->redirecting.to.name[0] = 0;
    bc->redirecting.to.number[0] = 0;
    bc->redirecting.to.subaddress[0] = 0;
    bc->redirecting.reason = mISDN_REDIRECTING_REASON_UNKNOWN;
    bc->redirecting.count = 0;
    bc->redirecting.to_changed = 0;
    bc->dummy=0;
    bc->bframe_len=0;
    bc->cw= 0;
    bc->dec=0;
    bc->channel = 0;
    bc->sending_complete = 0;
    bc->restart_channel=0;
    bc->conf_id = 0;
    bc->need_more_infos = 0;
    bc->send_dtmf=0;
    bc->nodsp=0;
    bc->nojitter=0;
    bc->time_usec=0;
    bc->rxgain=0;
    bc->txgain=0;
    bc->crypt=0;
    bc->curptx=0; bc->curprx=0;
    bc->crypt_key[0] = 0;
    bc->generate_tone=0;
    bc->tone_cnt=0;
    bc->active = 0;
    bc->early_bconnect = 1;
 #ifdef MISDN_1_2
    *bc->pipeline = 0;
 #else
    bc->ec_enable = 0;
    bc->ec_deftaps = 128;
 #endif
    bc->AOCD_need_export = 0;
    bc->orig=0;
    bc->cause = AST_CAUSE_NORMAL_CLEARING;
    bc->out_cause = AST_CAUSE_NORMAL_CLEARING;
    bc->display_connected = 0; /* none */
    bc->display_setup = 0;  /* none */
    bc->outgoing_colp = 0;/* pass */
    bc->presentation = 0;   /* allowed */
    bc->set_presentation = 0;
    bc->notify_description_code = mISDN_NOTIFY_CODE_INVALID;
    bc->progress_coding=0;
    bc->progress_location=0;
    bc->progress_indicator=0;
 #if defined(AST_MISDN_ENHANCEMENTS)
    bc->div_leg_3_rx_wanted = 0;
    bc->div_leg_3_tx_pending = 0;
 #endif   /* defined(AST_MISDN_ENHANCEMENTS) */
 /** Set Default Bearer Caps **/
    bc->capability=INFO_CAPABILITY_SPEECH;
    bc->law=INFO_CODEC_ALAW;
    bc->mode=0;
    bc->rate=0x10;
    bc->user1=0;
    bc->urate=0;
    bc->hdlc=0;
    bc->dialed.number_plan = NUMPLAN_ISDN;
    bc->dialed.number_type = NUMTYPE_UNKNOWN;
    bc->dialed.number[0] = 0;
    bc->dialed.subaddress[0] = 0;
    bc->info_dad[0] = 0;
    bc->display[0] = 0;
    bc->infos_pending[0] = 0;
    bc->uu[0]=0;
    bc->uulen=0;
    bc->fac_in.Function = Fac_None;
    bc->fac_out.Function = Fac_None;
    bc->te_choose_channel = 0;
    bc->channel_found= 0;
    gettimeofday(&bc->last_used, NULL);
 }
empty_chan_in_stack()
static void empty_chan_in_stack (struct misdn_stack * stack, int channel) static
Definition at line 605 of file isdn_lib.c.
References ARRAY_LEN, cb_log, misdn_stack::channels, dump_chan_list(), and misdn_stack::port.
Referenced by clear_l3(), handle_cr(), handle_event_nt(), handle_frm_te(), manager_clean_bc(), misdn_lib_release(), and misdn_lib_send_event().
 {
    if (channel < 1 || ARRAY_LEN(stack->channels) < channel) {
       cb_log(0, stack->port, "empty_chan_in_stack: cannot empty channel %d\n", channel);
       return;
    }
    cb_log(4, stack->port, "empty_chan_in_stack: %d\n", channel);
    stack->channels[channel - 1] = 0;
    dump_chan_list(stack);
 }
fac2str()
static const char* fac2str (enum FacFunction facility) static
Definition at line 3338 of file isdn_lib.c.
References ARRAY_LEN, and name.
Referenced by misdn_lib_log_ies().
 {
    static const struct {
       enum FacFunction facility;
       char *name;
    } arr[] = {
 /* *INDENT-OFF* */
       { Fac_None, "Fac_None" },
 #if defined(AST_MISDN_ENHANCEMENTS)
       { Fac_ERROR, "Fac_ERROR" },
       { Fac_RESULT, "Fac_RESULT" },
       { Fac_REJECT, "Fac_REJECT" },
       { Fac_ActivationDiversion, "Fac_ActivationDiversion" },
       { Fac_DeactivationDiversion, "Fac_DeactivationDiversion" },
       { Fac_ActivationStatusNotificationDiv, "Fac_ActivationStatusNotificationDiv" },
       { Fac_DeactivationStatusNotificationDiv, "Fac_DeactivationStatusNotificationDiv" },
       { Fac_InterrogationDiversion, "Fac_InterrogationDiversion" },
       { Fac_DiversionInformation, "Fac_DiversionInformation" },
       { Fac_CallDeflection, "Fac_CallDeflection" },
       { Fac_CallRerouteing, "Fac_CallRerouteing" },
       { Fac_DivertingLegInformation2, "Fac_DivertingLegInformation2" },
       { Fac_InterrogateServedUserNumbers, "Fac_InterrogateServedUserNumbers" },
       { Fac_DivertingLegInformation1, "Fac_DivertingLegInformation1" },
       { Fac_DivertingLegInformation3, "Fac_DivertingLegInformation3" },
       { Fac_EctExecute, "Fac_EctExecute" },
       { Fac_ExplicitEctExecute, "Fac_ExplicitEctExecute" },
       { Fac_RequestSubaddress, "Fac_RequestSubaddress" },
       { Fac_SubaddressTransfer, "Fac_SubaddressTransfer" },
       { Fac_EctLinkIdRequest, "Fac_EctLinkIdRequest" },
       { Fac_EctInform, "Fac_EctInform" },
       { Fac_EctLoopTest, "Fac_EctLoopTest" },
       { Fac_ChargingRequest, "Fac_ChargingRequest" },
       { Fac_AOCSCurrency, "Fac_AOCSCurrency" },
       { Fac_AOCSSpecialArr, "Fac_AOCSSpecialArr" },
       { Fac_AOCDCurrency, "Fac_AOCDCurrency" },
       { Fac_AOCDChargingUnit, "Fac_AOCDChargingUnit" },
       { Fac_AOCECurrency, "Fac_AOCECurrency" },
       { Fac_AOCEChargingUnit, "Fac_AOCEChargingUnit" },
       { Fac_StatusRequest, "Fac_StatusRequest" },
       { Fac_CallInfoRetain, "Fac_CallInfoRetain" },
       { Fac_EraseCallLinkageID, "Fac_EraseCallLinkageID" },
       { Fac_CCBSDeactivate, "Fac_CCBSDeactivate" },
       { Fac_CCBSErase, "Fac_CCBSErase" },
       { Fac_CCBSRemoteUserFree, "Fac_CCBSRemoteUserFree" },
       { Fac_CCBSCall, "Fac_CCBSCall" },
       { Fac_CCBSStatusRequest, "Fac_CCBSStatusRequest" },
       { Fac_CCBSBFree, "Fac_CCBSBFree" },
       { Fac_CCBSStopAlerting, "Fac_CCBSStopAlerting" },
       { Fac_CCBSRequest, "Fac_CCBSRequest" },
       { Fac_CCBSInterrogate, "Fac_CCBSInterrogate" },
       { Fac_CCNRRequest, "Fac_CCNRRequest" },
       { Fac_CCNRInterrogate, "Fac_CCNRInterrogate" },
       { Fac_CCBS_T_Call, "Fac_CCBS_T_Call" },
       { Fac_CCBS_T_Suspend, "Fac_CCBS_T_Suspend" },
       { Fac_CCBS_T_Resume, "Fac_CCBS_T_Resume" },
       { Fac_CCBS_T_RemoteUserFree, "Fac_CCBS_T_RemoteUserFree" },
       { Fac_CCBS_T_Available, "Fac_CCBS_T_Available" },
       { Fac_CCBS_T_Request, "Fac_CCBS_T_Request" },
       { Fac_CCNR_T_Request, "Fac_CCNR_T_Request" },
 #else
       { Fac_CFActivate, "Fac_CFActivate" },
       { Fac_CFDeactivate, "Fac_CFDeactivate" },
       { Fac_CD, "Fac_CD" },
       { Fac_AOCDCurrency, "Fac_AOCDCurrency" },
       { Fac_AOCDChargingUnit, "Fac_AOCDChargingUnit" },
 #endif   /* defined(AST_MISDN_ENHANCEMENTS) */
 /* *INDENT-ON* */
    };
    unsigned index;
    for (index = 0; index < ARRAY_LEN(arr); ++index) {
       if (arr[index].facility == facility) {
          return arr[index].name;
       }
    }
    return "unknown";
 }
fetch_msg()
static msg_t* fetch_msg (int midev) static
Definition at line 3011 of file isdn_lib.c.
References cb_log, errno, and NULL.
Referenced by misdn_lib_isdn_event_catcher().
 {
    msg_t *msg=alloc_msg(MAX_MSG_SIZE);
    int r;
    if (!msg) {
       cb_log(0, 0, "fetch_msg: alloc msg failed !!");
       return NULL;
    }
    AGAIN:
       r=mISDN_read(midev,msg->data,MAX_MSG_SIZE, TIMEOUT_10SEC);
       msg->len=r;
       if (r==0) {
          free_msg(msg); /* danger, cause usually freeing in main_loop */
          cb_log(6,0,"Got empty Msg..\n");
          return NULL;
       }
       if (r<0) {
          if (errno == EAGAIN) {
             /*we wait for mISDN here*/
             cb_log(4,0,"mISDN_read wants us to wait\n");
             usleep(5000);
             goto AGAIN;
          }
          cb_log(0,0,"mISDN_read returned :%d error:%s (%d)\n",r,strerror(errno),errno);
       }
 #if 0
                if  (!(frm->prim == (DL_DATA|INDICATION) )|| (frm->prim == (PH_DATA|INDICATION)))
                        cb_log(0,0,"prim: %x dinfo:%x addr:%x msglen:%d frm->len:%d\n",frm->prim, frm->dinfo, frm->addr, msg->len,frm->len );
 #endif
       return msg;
 }
find_bc_by_addr()
static struct misdn_bchannel* find_bc_by_addr (unsigned long addr) static
Definition at line 1556 of file isdn_lib.c.
References misdn_bchannel::addr, misdn_stack::b_num, misdn_stack::bc, misdn_bchannel::in_use, misdn_bchannel::layer_id, misdn_stack::next, NULL, and misdn_lib::stack_list.
Referenced by handle_bchan().
 {
    struct misdn_stack *stack;
    int i;
    for (stack = glob_mgr->stack_list; stack; stack = stack->next) {
       for (i = 0; i <= stack->b_num; i++) {
          if (stack->bc[i].in_use
             && ((stack->bc[i].addr & STACK_ID_MASK) == (addr & STACK_ID_MASK)
                || stack->bc[i].layer_id == addr)) {
             return &stack->bc[i];
          }
       }
    }
    return NULL;
 }
find_bc_by_confid()
static struct misdn_bchannel* find_bc_by_confid (unsigned long confid) static
Definition at line 1574 of file isdn_lib.c.
References misdn_stack::b_num, misdn_stack::bc, misdn_bchannel::conf_id, misdn_bchannel::in_use, misdn_stack::next, NULL, and misdn_lib::stack_list.
Referenced by misdn_lib_send_event().
 {
    struct misdn_stack *stack;
    int i;
    for (stack = glob_mgr->stack_list; stack; stack = stack->next) {
       for (i = 0; i <= stack->b_num; i++) {
          if (stack->bc[i].in_use && stack->bc[i].conf_id == confid) {
             return &stack->bc[i];
          }
       }
    }
    return NULL;
 }
find_bc_by_l3id()
struct misdn_bchannel * find_bc_by_l3id (struct misdn_stack * stack, unsigned long l3id)
Definition at line 1536 of file isdn_lib.c.
References ARRAY_LEN, misdn_stack::b_num, misdn_stack::bc, misdn_bchannel::in_use, misdn_bchannel::l3_id, MAX_BCHANS, and stack_holder_find().
Referenced by handle_cr(), handle_event_nt(), handle_frm_te(), manager_event_handler(), and release_cr().
 {
    int i;
    for (i = 0; i <= stack->b_num; ++i) {
       if (stack->bc[i].in_use && stack->bc[i].l3_id == l3id) {
          return &stack->bc[i];
       }
    }
 #if defined(AST_MISDN_ENHANCEMENTS)
    /* Search the B channel records for a REGISTER signaling link. */
    for (i = MAX_BCHANS + 1; i < ARRAY_LEN(stack->bc); ++i) {
       if (stack->bc[i].in_use && stack->bc[i].l3_id == l3id) {
          return &stack->bc[i];
       }
    }
 #endif   /* defined(AST_MISDN_ENHANCEMENTS) */
    return stack_holder_find(stack, l3id);
 }
find_bc_by_masked_l3id()
static struct misdn_bchannel* find_bc_by_masked_l3id (struct misdn_stack * stack, unsigned long l3id, unsigned long mask) static
Definition at line 1515 of file isdn_lib.c.
References ARRAY_LEN, misdn_stack::b_num, misdn_stack::bc, misdn_bchannel::in_use, misdn_bchannel::l3_id, MAX_BCHANS, and stack_holder_find().
Referenced by handle_event_nt().
 {
    int i;
    for (i = 0; i <= stack->b_num; ++i) {
       if (stack->bc[i].in_use && (stack->bc[i].l3_id & mask) == (l3id & mask)) {
          return &stack->bc[i];
       }
    }
 #if defined(AST_MISDN_ENHANCEMENTS)
    /* Search the B channel records for a REGISTER signaling link. */
    for (i = MAX_BCHANS + 1; i < ARRAY_LEN(stack->bc); ++i) {
       if (stack->bc[i].in_use && (stack->bc[i].l3_id & mask) == (l3id & mask)) {
          return &stack->bc[i];
       }
    }
 #endif   /* defined(AST_MISDN_ENHANCEMENTS) */
    return stack_holder_find(stack, l3id);
 }
find_free_chan_in_stack()
static int find_free_chan_in_stack (struct misdn_stack * stack, struct misdn_bchannel * bc, int channel, int dec) static
Definition at line 513 of file isdn_lib.c.
References ARRAY_LEN, AST_CAUSE_NORMAL_CIRCUIT_CONGESTION, AST_CAUSE_REQUESTED_CHAN_UNAVAIL, misdn_stack::b_num, cb_log, misdn_bchannel::channel, misdn_bchannel::channel_found, misdn_stack::channels, dump_chan_list(), misdn_bchannel::is_register_pool, MAX_BCHANS, misdn_bchannel::out_cause, misdn_stack::port, misdn_stack::pri, pthread_mutex_lock, pthread_mutex_unlock, set_chan_in_stack(), and misdn_stack::st_lock.
Referenced by create_process(), handle_event_nt(), handle_event_te(), and misdn_lib_send_event().
 {
    int i;
    int chan = 0;
    int bnums;
    if (bc->channel_found) {
       return 0;
    }
    bc->channel_found = 1;
 #if defined(AST_MISDN_ENHANCEMENTS)
    if (bc->is_register_pool) {
       pthread_mutex_lock(&stack->st_lock);
       for (i = MAX_BCHANS + 1; i < ARRAY_LEN(stack->channels); ++i) {
          if (!stack->channels[i]) {
             chan = i + 1;
             cb_log(3, stack->port, " --> found REGISTER chan: %d\n", chan);
             break;
          }
       }
    } else
 #endif   /* defined(AST_MISDN_ENHANCEMENTS) */
    {
       cb_log(5, stack->port, "find_free_chan: req_chan:%d\n", channel);
       if (channel < 0 || channel > MAX_BCHANS) {
          cb_log(0, stack->port, " !! out of bound call to find_free_chan_in_stack! (ch:%d)\n", channel);
          return 0;
       }
       --channel;
       pthread_mutex_lock(&stack->st_lock);
       bnums = stack->pri ? stack->b_num : stack->b_num - 1;
       if (dec) {
          for (i = bnums; i >= 0; --i) {
             if (i != 15 && (channel < 0 || i == channel)) { /* skip E1 D channel ;) and work with chan preselection */
                if (!stack->channels[i]) {
                   chan = i + 1;
                   cb_log(3, stack->port, " --> found chan%s: %d\n", channel >= 0 ? " (preselected)" : "", chan);
                   break;
                }
             }
          }
       } else {
          for (i = 0; i <= bnums; ++i) {
             if (i != 15 && (channel < 0 || i == channel)) { /* skip E1 D channel ;) and work with chan preselection */
                if (!stack->channels[i]) {
                   chan = i + 1;
                   cb_log(3, stack->port, " --> found chan%s: %d\n", channel >= 0 ? " (preselected)" : "", chan);
                   break;
                }
             }
          }
       }
    }
    if (!chan) {
       pthread_mutex_unlock(&stack->st_lock);
       cb_log(1, stack->port, " !! NO FREE CHAN IN STACK\n");
       dump_chan_list(stack);
       bc->out_cause = AST_CAUSE_NORMAL_CIRCUIT_CONGESTION;
       return -1;
    }
    if (set_chan_in_stack(stack, chan) < 0) {
       pthread_mutex_unlock(&stack->st_lock);
       cb_log(0, stack->port, "Channel Already in use:%d\n", chan);
       bc->out_cause = AST_CAUSE_REQUESTED_CHAN_UNAVAIL;
       return -1;
    }
    pthread_mutex_unlock(&stack->st_lock);
    bc->channel = chan;
    return 0;
 }
find_stack_by_addr()
static struct misdn_stack* find_stack_by_addr (int addr) static
Definition at line 1472 of file isdn_lib.c.
References misdn_stack::next, misdn_lib::stack_list, and misdn_stack::upper_id.
Referenced by handle_frm_nt(), handle_frm_te(), handle_l1(), handle_l2(), and handle_mgmt().
 {
    struct misdn_stack *stack;
    for (stack = glob_mgr->stack_list; stack; stack = stack->next) {
       if ((stack->upper_id & STACK_ID_MASK) == (addr & STACK_ID_MASK)) {
          /* Found the stack */
          break;
       }
    }
    return stack;
 }
find_stack_by_mgr()
static struct misdn_stack* find_stack_by_mgr (manager_t * mgr_nt) static
Definition at line 1501 of file isdn_lib.c.
References misdn_stack::mgr, misdn_stack::next, and misdn_lib::stack_list.
Referenced by handle_event_nt().
 {
    struct misdn_stack *stack;
    for (stack = glob_mgr->stack_list; stack; stack = stack->next) {
       if (&stack->mgr == mgr_nt) {
          /* Found the stack */
          break;
       }
    }
    return stack;
 }
find_stack_by_port()
static struct misdn_stack* find_stack_by_port (int port) static
Definition at line 1487 of file isdn_lib.c.
References misdn_stack::next, misdn_stack::port, and misdn_lib::stack_list.
Referenced by misdn_lib_get_free_bc(), misdn_lib_get_port_info(), misdn_lib_port_restart(), misdn_lib_reinit_nt_stack(), and misdn_lib_send_restart().
 {
    struct misdn_stack *stack;
    for (stack = glob_mgr->stack_list; stack; stack = stack->next) {
       if (stack->port == port) {
          /* Found the stack */
          break;
       }
    }
    return stack;
 }
flip_buf_bits()
static char* flip_buf_bits (char * buf, int len) static
Definition at line 334 of file isdn_lib.c.
References buf, and len().
Referenced by handle_bchan(), misdn_lib_init(), misdn_lib_tx2misdn_frm(), and misdn_tx_jitter().
 {
    int i;
    char * start = buf;
    for (i = 0 ; i < len; i++) {
       buf[i] = flip_table[(unsigned char)buf[i]];
    }
    return start;
 }
get_misdn_stack()
struct misdn_stack * get_misdn_stack (void)
Definition at line 4698 of file isdn_lib.c.
References misdn_lib::stack_list.
Referenced by get_show_stack_details(), get_stack_by_bc(), misdn_dump_chanlist(), misdn_lib_find_held_bc(), misdn_lib_get_maxchans(), misdn_lib_is_port_blocked(), misdn_lib_is_ptp(), misdn_lib_nt_keepcalls(), misdn_lib_port_block(), misdn_lib_port_is_nt(), misdn_lib_port_is_pri(), and misdn_lib_port_unblock().
 {
    return glob_mgr->stack_list;
 }
get_show_stack_details()
void get_show_stack_details (int port, char * buf)
Definition at line 168 of file isdn_lib.c.
References misdn_stack::blocked, get_misdn_stack(), misdn_stack::l1link, misdn_stack::l2link, misdn_stack::next, misdn_stack::nt, misdn_stack::port, and misdn_stack::ptp.
Referenced by handle_cli_misdn_show_port(), and handle_cli_misdn_show_stacks().
 {
    struct misdn_stack *stack = get_misdn_stack();
    for (; stack; stack = stack->next) {
       if (stack->port == port) {
          break;
       }
    }
    if (stack) {
       sprintf(buf, "* Port %2d Type %s Prot. %s L2Link %s L1Link:%s Blocked:%d",
          stack->port,
          stack->nt ? "NT" : "TE",
          stack->ptp ? "PTP" : "PMP",
          (stack->nt && !stack->ptp) ? "UNKN" : stack->l2link ? "UP  " : "DOWN",
          stack->l1link ? "UP  " : "DOWN",
          stack->blocked);
    } else {
       buf[0] = 0;
    }
 }
get_stack_by_bc()
struct misdn_stack* get_stack_by_bc (struct misdn_bchannel * bc)
Definition at line 152 of file isdn_lib.c.
References get_misdn_stack(), misdn_stack::next, NULL, misdn_stack::port, and misdn_bchannel::port.
Referenced by clean_up_bc(), create_process(), dec_ie_channel_id(), enc_ie_channel_id(), handle_bchan(), handle_event_te(), manager_bchannel_activate(), manager_bchannel_deactivate(), manager_clean_bc(), manager_ec_disable(), manager_ec_enable(), misdn_lib_log_ies(), misdn_lib_release(), misdn_lib_send_event(), misdn_lib_tx2misdn_frm(), parse_release_complete(), parse_restart(), send_msg(), and setup_bc().
 {
    struct misdn_stack *stack = get_misdn_stack();
    if (!bc)
       return NULL;
    for ( ; stack; stack = stack->next) {
       if (bc->port == stack->port)
          return stack;
    }
    return NULL;
 }
handle_bchan()
static int handle_bchan (msg_t * msg) static
Anyway flip the bufbits
Definition at line 2395 of file isdn_lib.c.
References misdn_bchannel::addr, misdn_bchannel::bc_state, BCHAN_ACTIVATED, misdn_bchannel::bframe, misdn_bchannel::bframe_len, buf, misdn_bchannel::caller, misdn_bchannel::capability, cb_event, cb_log, misdn_bchannel::channel, misdn_bchannel::dialed, do_tone(), misdn_bchannel::dtmf, EVENT_BCHAN_DATA, EVENT_DTMF_TONE, find_bc_by_addr(), flip_buf_bits(), get_stack_by_bc(), if(), misdn_stack::midev, misdn_cap_is_speech(), misdn_tx_jitter(), misdn_party_id::name, misdn_bchannel::nojitter, NULL, misdn_party_dialing::number, misdn_party_id::number, misdn_party_id::number_type, misdn_party_dialing::number_type, misdn_bchannel::pid, misdn_stack::port, misdn_bchannel::port, and misdn_lib::user_data.
Referenced by handle_err(), and manager_isdn_handler().
 {
    iframe_t *frm= (iframe_t*)msg->data;
    struct misdn_bchannel *bc=find_bc_by_addr(frm->addr);
    struct misdn_stack *stack;
    if (!bc) {
       cb_log(1,0,"handle_bchan: BC not found for prim:%x with addr:%x dinfo:%x\n", frm->prim, frm->addr, frm->dinfo);
       return 0 ;
    }
    stack = get_stack_by_bc(bc);
    if (!stack) {
       cb_log(0, bc->port,"handle_bchan: STACK not found for prim:%x with addr:%x dinfo:%x\n", frm->prim, frm->addr, frm->dinfo);
       return 0;
    }
    switch (frm->prim) {
    case MGR_SETSTACK| CONFIRM:
       cb_log(3, stack->port, "BCHAN: MGR_SETSTACK|CONFIRM pid:%d\n",bc->pid);
       break;
    case MGR_SETSTACK| INDICATION:
       cb_log(3, stack->port, "BCHAN: MGR_SETSTACK|IND pid:%d\n",bc->pid);
    break;
    case MGR_DELLAYER| INDICATION:
       cb_log(3, stack->port, "BCHAN: MGR_DELLAYER|IND pid:%d\n",bc->pid);
       break;
    case MGR_DELLAYER| CONFIRM:
       cb_log(3, stack->port, "BCHAN: MGR_DELLAYER|CNF pid:%d\n",bc->pid);
       bc->pid=0;
       bc->addr=0;
       free_msg(msg);
       return 1;
    case PH_ACTIVATE | INDICATION:
    case DL_ESTABLISH | INDICATION:
       cb_log(3, stack->port, "BCHAN: ACT Ind pid:%d\n", bc->pid);
       free_msg(msg);
       return 1;
    case PH_ACTIVATE | CONFIRM:
    case DL_ESTABLISH | CONFIRM:
       cb_log(3, stack->port, "BCHAN: bchan ACT Confirm pid:%d\n",bc->pid);
       free_msg(msg);
       return 1;
    case DL_ESTABLISH | REQUEST:
       {
          char buf[128];
          mISDN_write_frame(stack->midev, buf, bc->addr | FLG_MSG_TARGET | FLG_MSG_DOWN,  DL_ESTABLISH | CONFIRM, 0,0, NULL, TIMEOUT_1SEC);
       }
       free_msg(msg);
       return 1;
    case DL_RELEASE|REQUEST:
       {
          char buf[128];
          mISDN_write_frame(stack->midev, buf, bc->addr | FLG_MSG_TARGET | FLG_MSG_DOWN,  DL_RELEASE| CONFIRM, 0,0, NULL, TIMEOUT_1SEC);
       }
       free_msg(msg);
       return 1;
    case PH_DEACTIVATE | INDICATION:
    case DL_RELEASE | INDICATION:
       cb_log (3, stack->port, "BCHAN: DeACT Ind pid:%d\n",bc->pid);
       free_msg(msg);
       return 1;
    case PH_DEACTIVATE | CONFIRM:
    case DL_RELEASE | CONFIRM:
       cb_log(3, stack->port, "BCHAN: DeACT Conf pid:%d\n",bc->pid);
       free_msg(msg);
       return 1;
    case PH_CONTROL|INDICATION:
    {
       unsigned int *cont = (unsigned int *) &frm->data.p;
       cb_log(4, stack->port,
          "PH_CONTROL: channel:%d caller%d:\"%s\" <%s> dialed%d:%s \n",
          bc->channel,
          bc->caller.number_type,
          bc->caller.name,
          bc->caller.number,
          bc->dialed.number_type,
          bc->dialed.number);
       if ((*cont & ~DTMF_TONE_MASK) == DTMF_TONE_VAL) {
          int dtmf = *cont & DTMF_TONE_MASK;
          cb_log(4, stack->port, " --> DTMF TONE: %c\n",dtmf);
          bc->dtmf=dtmf;
          cb_event(EVENT_DTMF_TONE, bc, glob_mgr->user_data);
          free_msg(msg);
          return 1;
       }
       if (*cont == BF_REJECT) {
          cb_log(4, stack->port, " --> BF REJECT\n");
          free_msg(msg);
          return 1;
       }
       if (*cont == BF_ACCEPT) {
          cb_log(4, stack->port, " --> BF ACCEPT\n");
          free_msg(msg);
          return 1;
       }
    }
    break;
    case PH_DATA|REQUEST:
    case DL_DATA|REQUEST:
       cb_log(0, stack->port, "DL_DATA REQUEST \n");
       do_tone(bc, 64);
       free_msg(msg);
       return 1;
    case PH_DATA|INDICATION:
    case DL_DATA|INDICATION:
    {
       bc->bframe = (void*)&frm->data.i;
       bc->bframe_len = frm->len;
       /** Anyway flip the bufbits **/
       if ( misdn_cap_is_speech(bc->capability) )
          flip_buf_bits(bc->bframe, bc->bframe_len);
       if (!bc->bframe_len) {
          cb_log(2, stack->port, "DL_DATA INDICATION bc->addr:%x frm->addr:%x\n", bc->addr, frm->addr);
          free_msg(msg);
          return 1;
       }
       if ( (bc->addr&STACK_ID_MASK) != (frm->addr&STACK_ID_MASK) ) {
          cb_log(2, stack->port, "DL_DATA INDICATION bc->addr:%x frm->addr:%x\n", bc->addr, frm->addr);
          free_msg(msg);
          return 1;
       }
 #if MISDN_DEBUG
       cb_log(0, stack->port, "DL_DATA INDICATION Len %d\n", frm->len);
 #endif
       if ( (bc->bc_state == BCHAN_ACTIVATED) && frm->len > 0) {
          int t;
 #ifdef MISDN_B_DEBUG
          cb_log(0,bc->port,"do_tone START\n");
 #endif
          t=do_tone(bc,frm->len);
 #ifdef MISDN_B_DEBUG
          cb_log(0,bc->port,"do_tone STOP (%d)\n",t);
 #endif
          if (  !t ) {
             int i;
             if ( misdn_cap_is_speech(bc->capability)) {
                if ( !bc->nojitter ) {
 #ifdef MISDN_B_DEBUG
                   cb_log(0,bc->port,"tx_jitter START\n");
 #endif
                   misdn_tx_jitter(bc,frm->len);
 #ifdef MISDN_B_DEBUG
                   cb_log(0,bc->port,"tx_jitter STOP\n");
 #endif
                }
             }
 #ifdef MISDN_B_DEBUG
             cb_log(0,bc->port,"EVENT_B_DATA START\n");
 #endif
             i = cb_event(EVENT_BCHAN_DATA, bc, glob_mgr->user_data);
 #ifdef MISDN_B_DEBUG
             cb_log(0,bc->port,"EVENT_B_DATA STOP\n");
 #endif
             if (i<0) {
                cb_log(10,stack->port,"cb_event returned <0\n");
                /*clean_up_bc(bc);*/
             }
          }
       }
       free_msg(msg);
       return 1;
    }
    case PH_CONTROL | CONFIRM:
       cb_log(4, stack->port, "PH_CONTROL|CNF bc->addr:%x\n", frm->addr);
       free_msg(msg);
       return 1;
    case PH_DATA | CONFIRM:
    case DL_DATA|CONFIRM:
 #if MISDN_DEBUG
       cb_log(0, stack->port, "Data confirmed\n");
 #endif
       free_msg(msg);
       return 1;
    case DL_DATA|RESPONSE:
 #if MISDN_DEBUG
       cb_log(0, stack->port, "Data response\n");
 #endif
       break;
    }
    return 0;
 }
handle_cr()
static int handle_cr (struct misdn_stack * stack, iframe_t * frm) static
Definition at line 1686 of file isdn_lib.c.
References bc, cb_event, cb_log, misdn_bchannel::channel, clean_up_bc(), dump_chan_list(), empty_bc(), empty_chan_in_stack(), EVENT_CLEANUP, find_bc_by_l3id(), free(), misdn_bchannel::in_use, misdn_bchannel::l3_id, misdn_lib_get_free_bc(), misdn_make_dummy(), misdn_bchannel::need_disconnect, misdn_bchannel::need_release, misdn_bchannel::need_release_complete, misdn_stack::nt, misdn_stack::port, misdn_bchannel::stack_holder, stack_holder_remove(), and misdn_lib::user_data.
Referenced by handle_event_nt(), handle_frm_te(), and release_cr().
 {
    struct misdn_bchannel dummybc;
    struct misdn_bchannel *bc;
    int channel;
    if (!stack) return -1;
    switch (frm->prim) {
    case CC_NEW_CR|INDICATION:
       cb_log(7, stack->port, " --> lib: NEW_CR Ind with l3id:%x on this port.\n",frm->dinfo);
       bc = misdn_lib_get_free_bc(stack->port, 0, 1, 0);
       if (!bc) {
          cb_log(0, stack->port, " --> !! lib: No free channel!\n");
          return -1;
       }
       cb_log(7, stack->port, " --> new_process: New L3Id: %x\n",frm->dinfo);
       bc->l3_id=frm->dinfo;
       return 1;
    case CC_NEW_CR|CONFIRM:
       return 1;
    case CC_NEW_CR|REQUEST:
       return 1;
    case CC_RELEASE_CR|REQUEST:
       return 1;
    case CC_RELEASE_CR|CONFIRM:
       break;
    case CC_RELEASE_CR|INDICATION:
       cb_log(4, stack->port, " --> lib: RELEASE_CR Ind with l3id:%x\n", frm->dinfo);
       bc = find_bc_by_l3id(stack, frm->dinfo);
       if (!bc) {
          cb_log(4, stack->port, " --> Didn't find BC so temporarily creating dummy BC (l3id:%x) on this port.\n", frm->dinfo);
          misdn_make_dummy(&dummybc, stack->port, frm->dinfo, stack->nt, 0);
          bc = &dummybc;
       }
       channel = bc->channel;
       cb_log(4, stack->port, " --> lib: CLEANING UP l3id: %x\n", frm->dinfo);
       /* bc->pid = 0; */
       bc->need_disconnect = 0;
       bc->need_release = 0;
       bc->need_release_complete = 0;
       cb_event(EVENT_CLEANUP, bc, glob_mgr->user_data);
       empty_bc(bc);
       clean_up_bc(bc);
       if (channel > 0)
          empty_chan_in_stack(stack, channel);
       bc->in_use = 0;
       dump_chan_list(stack);
       if (bc->stack_holder) {
          cb_log(4, stack->port, "REMOVING Holder\n");
          stack_holder_remove(stack, bc);
          free(bc);
       }
       return 1;
    default:
       break;
    }
    return 0;
 }
handle_err()
static int handle_err (msg_t * msg) static
Definition at line 3779 of file isdn_lib.c.
References cb_log, handle_bchan(), and if().
Referenced by manager_isdn_handler().
 {
    iframe_t *frm = (iframe_t*) msg->data;
    if (!frm->addr) {
       static int cnt=0;
       if (!cnt)
          cb_log(0,0,"mISDN Msg without Address pr:%x dinfo:%x\n",frm->prim,frm->dinfo);
       cnt++;
       if (cnt>100) {
          cb_log(0,0,"mISDN Msg without Address pr:%x dinfo:%x (already more than 100 of them)\n",frm->prim,frm->dinfo);
          cnt=0;
       }
       free_msg(msg);
       return 1;
    }
    switch (frm->prim) {
       case MGR_SETSTACK|INDICATION:
          return handle_bchan(msg);
       break;
       case MGR_SETSTACK|CONFIRM:
       case MGR_CLEARSTACK|CONFIRM:
          free_msg(msg) ;
          return 1;
       break;
       case DL_DATA|CONFIRM:
          cb_log(4,0,"DL_DATA|CONFIRM\n");
          free_msg(msg);
          return 1;
       case PH_CONTROL|CONFIRM:
          cb_log(4,0,"PH_CONTROL|CONFIRM\n");
          free_msg(msg);
          return 1;
       case DL_DATA|INDICATION:
       {
          int port=(frm->addr&MASTER_ID_MASK) >> 8;
          int channel=(frm->addr&CHILD_ID_MASK) >> 16;
          /*we flush the read buffer here*/
          cb_log(9,0,"BCHAN DATA without BC: addr:%x port:%d channel:%d\n",frm->addr, port,channel);
          free_msg(msg);
          return 1;
       }
    }
    return 0;
 }
handle_event_nt()
static int handle_event_nt (void * dat, void * arg) static
Definition at line 1890 of file isdn_lib.c.
References misdn_bchannel::addr, AST_CAUSE_USER_BUSY, misdn_bchannel::b_stid, bc, misdn_stack::bc, misdn_bchannel::cause, cb_event, cb_log, misdn_bchannel::channel, clean_up_bc(), create_l3msg(), empty_bc(), empty_chan_in_stack(), EVENT_NEW_L3ID, EVENT_PORT_ALARM, EVENT_RELEASE, EVENT_RELEASE_COMPLETE, EVENT_SETUP, find_bc_by_l3id(), find_bc_by_masked_l3id(), find_free_chan_in_stack(), find_stack_by_mgr(), free(), handle_cr(), misdn_bchannel::holded, misdn_bchannel::in_use, misdn_bchannel::is_register_pool, isdn_get_info(), isdn_msg_get_event(), isdn_msg_parse_event(), misdn_stack::l1link, misdn_stack::l2link, misdn_stack::l2upcnt, misdn_bchannel::l3_id, misdn_lib_get_free_bc(), misdn_lib_get_l2_up(), misdn_lib_send_event(), misdn_lib_send_restart(), misdn_make_dummy(), mISDNUSER_HEAD_SIZE, msgs_g, misdn_stack::nst, misdn_stack::nstlock, misdn_stack::nt, misdn_stack::port, misdn_bchannel::port, misdn_stack::procids, pthread_mutex_lock, pthread_mutex_unlock, misdn_stack::ptp, release_cr(), misdn_stack::restart_sent, stack_holder_find(), stack_holder_remove(), misdn_stack::upper_id, and misdn_lib::user_data.
Referenced by misdn_lib_reinit_nt_stack(), and stack_init().
 {
    struct misdn_bchannel dummybc;
    struct misdn_bchannel *bc;
    manager_t *mgr = (manager_t *)dat;
    msg_t *msg = (msg_t *)arg;
    msg_t *dmsg;
    mISDNuser_head_t *hh;
    struct misdn_stack *stack;
    enum event_e event;
    int reject=0;
    int l3id;
    int channel;
    int tmpcause;
    if (!msg || !mgr)
       return(-EINVAL);
    stack = find_stack_by_mgr(mgr);
    hh=(mISDNuser_head_t*)msg->data;
    /*
     * When we are called from the mISDNuser lib, the nstlock is held and it
     * must be held when we return.  We unlock here because the lib may be
     * entered again recursively.
     */
    pthread_mutex_unlock(&stack->nstlock);
    cb_log(5, stack->port, " --> lib: prim %x dinfo %x\n",hh->prim, hh->dinfo);
    switch(hh->prim) {
    case CC_RETRIEVE|INDICATION:
    {
       struct misdn_bchannel *hold_bc;
       iframe_t frm; /* fake te frm to add callref to global callreflist */
       frm.dinfo = hh->dinfo;
       frm.addr=stack->upper_id | FLG_MSG_DOWN;
       frm.prim = CC_NEW_CR|INDICATION;
       if (handle_cr( stack, &frm)< 0) {
          goto ERR_NO_CHANNEL;
       }
       bc = find_bc_by_l3id(stack, hh->dinfo);
       hold_bc = stack_holder_find(stack, bc->l3_id);
       cb_log(4, stack->port, "bc_l3id:%x holded_bc_l3id:%x\n",bc->l3_id, hold_bc->l3_id);
       if (hold_bc) {
          cb_log(4, stack->port, "REMOVING Holder\n");
          /* swap the backup to our new channel back */
          stack_holder_remove(stack, hold_bc);
          memcpy(bc, hold_bc, sizeof(*bc));
          free(hold_bc);
          bc->holded=0;
          bc->b_stid=0;
       }
       break;
    }
    case CC_SETUP | CONFIRM:
       l3id = *((int *) (msg->data + mISDNUSER_HEAD_SIZE));
       cb_log(4, stack->port, " --> lib: Event_ind:SETUP CONFIRM [NT] : new L3ID is %x\n", l3id);
       bc = find_bc_by_l3id(stack, hh->dinfo);
       if (bc) {
          cb_log (2, bc->port, "I IND :CC_SETUP|CONFIRM: old l3id:%x new l3id:%x\n", bc->l3_id, l3id);
          bc->l3_id = l3id;
          cb_event(EVENT_NEW_L3ID, bc, glob_mgr->user_data);
       } else {
          cb_log(4, stack->port, "Bc Not found (after SETUP CONFIRM)\n");
       }
       free_msg(msg);
       pthread_mutex_lock(&stack->nstlock);
       return 0;
    case CC_SETUP | INDICATION:
       bc = misdn_lib_get_free_bc(stack->port, 0, 1, 0);
       if (!bc) {
          goto ERR_NO_CHANNEL;
       }
       cb_log(4, stack->port, " --> new_process: New L3Id: %x\n",hh->dinfo);
       bc->l3_id=hh->dinfo;
       break;
 #if defined(AST_MISDN_ENHANCEMENTS)
    case CC_REGISTER | CONFIRM:
       l3id = *((int *) (msg->data + mISDNUSER_HEAD_SIZE));
       cb_log(4, stack->port, " --> lib: Event_ind:REGISTER CONFIRM [NT] : new L3ID is %x\n", l3id);
       bc = find_bc_by_l3id(stack, hh->dinfo);
       if (bc) {
          cb_log (2, bc->port, "I IND :CC_REGISTER|CONFIRM: old l3id:%x new l3id:%x\n", bc->l3_id, l3id);
          bc->l3_id = l3id;
       } else {
          cb_log(4, stack->port, "Bc Not found (after REGISTER CONFIRM)\n");
       }
       free_msg(msg);
       pthread_mutex_lock(&stack->nstlock);
       return 0;
 #endif   /* defined(AST_MISDN_ENHANCEMENTS) */
 #if defined(AST_MISDN_ENHANCEMENTS)
    case CC_REGISTER | INDICATION:
       bc = misdn_lib_get_register_bc(stack->port);
       if (!bc) {
          goto ERR_NO_CHANNEL;
       }
       cb_log(4, stack->port, " --> new_process: New L3Id: %x\n",hh->dinfo);
       bc->l3_id=hh->dinfo;
       break;
 #endif   /* defined(AST_MISDN_ENHANCEMENTS) */
    case CC_CONNECT_ACKNOWLEDGE|INDICATION:
       break;
    case CC_ALERTING|INDICATION:
    case CC_PROCEEDING|INDICATION:
    case CC_SETUP_ACKNOWLEDGE|INDICATION:
    case CC_CONNECT|INDICATION:
       break;
    case CC_DISCONNECT|INDICATION:
       bc = find_bc_by_l3id(stack, hh->dinfo);
       if (!bc) {
          bc=find_bc_by_masked_l3id(stack, hh->dinfo, 0xffff0000);
          if (bc) {
             int myprocid=bc->l3_id&0x0000ffff;
             hh->dinfo=(hh->dinfo&0xffff0000)|myprocid;
             cb_log(3,stack->port,"Reject dinfo: %x cause:%d\n",hh->dinfo,bc->cause);
             reject=1;
          }
       }
       break;
    case CC_FACILITY|INDICATION:
       bc = find_bc_by_l3id(stack, hh->dinfo);
       if (!bc) {
          bc=find_bc_by_masked_l3id(stack, hh->dinfo, 0xffff0000);
          if (bc) {
             int myprocid=bc->l3_id&0x0000ffff;
             hh->dinfo=(hh->dinfo&0xffff0000)|myprocid;
             cb_log(4,bc->port,"Repaired reject Bug, new dinfo: %x\n",hh->dinfo);
          }
       }
       break;
    case CC_RELEASE_COMPLETE|INDICATION:
       break;
    case CC_SUSPEND|INDICATION:
       cb_log(4, stack->port, " --> Got Suspend, sending Reject for now\n");
       dmsg = create_l3msg(CC_SUSPEND_REJECT | REQUEST,MT_SUSPEND_REJECT, hh->dinfo,sizeof(RELEASE_COMPLETE_t), 1);
       pthread_mutex_lock(&stack->nstlock);
       stack->nst.manager_l3(&stack->nst, dmsg);
       free_msg(msg);
       return 0;
    case CC_RESUME|INDICATION:
       break;
    case CC_RELEASE|CONFIRM:
       bc = find_bc_by_l3id(stack, hh->dinfo);
       if (bc) {
          cb_log(1, stack->port, "CC_RELEASE|CONFIRM (l3id:%x), sending RELEASE_COMPLETE\n", hh->dinfo);
          misdn_lib_send_event(bc, EVENT_RELEASE_COMPLETE);
       }
       break;
    case CC_RELEASE|INDICATION:
       break;
    case CC_RELEASE_CR|INDICATION:
       release_cr(stack, hh);
       free_msg(msg);
       pthread_mutex_lock(&stack->nstlock);
       return 0;
    case CC_NEW_CR|INDICATION:
       /*  Got New CR for bchan, for now I handle this one in */
       /*  connect_ack, Need to be changed */
       l3id = *((int *) (msg->data + mISDNUSER_HEAD_SIZE));
       bc = find_bc_by_l3id(stack, hh->dinfo);
       if (!bc) {
          cb_log(0, stack->port, " --> In NEW_CR: didn't found bc ??\n");
          pthread_mutex_lock(&stack->nstlock);
          return -1;
       }
       if (((l3id&0xff00)!=0xff00) && ((bc->l3_id&0xff00)==0xff00)) {
          cb_log(4, stack->port, " --> Removing Process Id:%x on this port.\n", 0xff&bc->l3_id);
          stack->procids[bc->l3_id&0xff] = 0 ;
       }
       cb_log(4, stack->port, "lib: Event_ind:CC_NEW_CR : very new L3ID  is %x\n",l3id );
       bc->l3_id =l3id;
       if (!bc->is_register_pool) {
          cb_event(EVENT_NEW_L3ID, bc, glob_mgr->user_data);
       }
       free_msg(msg);
       pthread_mutex_lock(&stack->nstlock);
       return 0;
    case DL_ESTABLISH | INDICATION:
    case DL_ESTABLISH | CONFIRM:
       cb_log(3, stack->port, "%% GOT L2 Activate Info.\n");
       if (stack->ptp && stack->l2link) {
          cb_log(0, stack->port, "%% GOT L2 Activate Info. but we're activated already.. this l2 is faulty, blocking port\n");
          cb_event(EVENT_PORT_ALARM, &stack->bc[0], glob_mgr->user_data);
       }
       if (stack->ptp && !stack->restart_sent) {
          /* make sure we restart the interface of the
           * other side */
          stack->restart_sent=1;
          misdn_lib_send_restart(stack->port, -1);
       }
       /* when we get the L2 UP, the L1 is UP definitely too*/
       stack->l2link = 1;
       stack->l2upcnt=0;
       free_msg(msg);
       pthread_mutex_lock(&stack->nstlock);
       return 0;
    case DL_RELEASE | INDICATION:
    case DL_RELEASE | CONFIRM:
       cb_log(3, stack->port, "%% GOT L2 DeActivate Info.\n");
       if (stack->ptp) {
          if (stack->l2upcnt>3) {
             cb_log(0 , stack->port, "!!! Could not Get the L2 up after 3 Attempts!!!\n");
          } else {
             if (stack->l1link) {
                misdn_lib_get_l2_up(stack);
                stack->l2upcnt++;
             }
          }
       }
       stack->l2link = 0;
       free_msg(msg);
       pthread_mutex_lock(&stack->nstlock);
       return 0;
    default:
       break;
    }
    /*  Parse Events and fire_up to App. */
    event = isdn_msg_get_event(msgs_g, msg, 1);
    bc = find_bc_by_l3id(stack, hh->dinfo);
    if (!bc) {
       cb_log(4, stack->port, " --> Didn't find BC so temporarily creating dummy BC (l3id:%x).\n", hh->dinfo);
       misdn_make_dummy(&dummybc, stack->port,  hh->dinfo, stack->nt, 0);
       bc = &dummybc;
    }
    isdn_msg_parse_event(msgs_g, msg, bc, 1);
    switch (event) {
    case EVENT_SETUP:
       if (bc->channel <= 0 || bc->channel == 0xff) {
          bc->channel = 0;
       }
       if (find_free_chan_in_stack(stack, bc, bc->channel, 0) < 0) {
          goto ERR_NO_CHANNEL;
       }
       break;
    case EVENT_RELEASE:
    case EVENT_RELEASE_COMPLETE:
       channel = bc->channel;
       tmpcause = bc->cause;
       empty_bc(bc);
       bc->cause = tmpcause;
       clean_up_bc(bc);
       if (channel > 0)
          empty_chan_in_stack(stack, channel);
       bc->in_use = 0;
       break;
    default:
       break;
    }
    if(!isdn_get_info(msgs_g, event, 1)) {
       cb_log(4, stack->port, "Unknown Event Ind: prim %x dinfo %x\n", hh->prim, hh->dinfo);
    } else {
       if (reject) {
          switch(bc->cause) {
          case AST_CAUSE_USER_BUSY:
             cb_log(1, stack->port, "Siemens Busy reject..\n");
             break;
          default:
             break;
          }
       }
       cb_event(event, bc, glob_mgr->user_data);
    }
    free_msg(msg);
    pthread_mutex_lock(&stack->nstlock);
    return 0;
 ERR_NO_CHANNEL:
    cb_log(4, stack->port, "Patch from MEIDANIS:Sending RELEASE_COMPLETE %x (No free Chan for you..)\n", hh->dinfo);
    dmsg = create_l3msg(CC_RELEASE_COMPLETE | REQUEST, MT_RELEASE_COMPLETE, hh->dinfo, sizeof(RELEASE_COMPLETE_t), 1);
    pthread_mutex_lock(&stack->nstlock);
    stack->nst.manager_l3(&stack->nst, dmsg);
    free_msg(msg);
    return 0;
 }
handle_event_te()
static int handle_event_te (struct misdn_bchannel * bc, enum event_e event, iframe_t * frm) static
Definition at line 1590 of file isdn_lib.c.
References misdn_bchannel::caller, misdn_bchannel::capability, cb_log, misdn_bchannel::channel, misdn_bchannel::crypt_key, misdn_bchannel::cw, misdn_bchannel::dialed, EVENT_ALERTING, EVENT_CONNECT, EVENT_CONNECT_ACKNOWLEDGE, EVENT_PROCEEDING, EVENT_PROGRESS, EVENT_RELEASE, EVENT_RELEASE_COMPLETE, EVENT_SETUP, EVENT_SETUP_ACKNOWLEDGE, find_free_chan_in_stack(), get_stack_by_bc(), manager_ec_enable(), manager_ph_control(), manager_ph_control_block(), misdn_cap_is_speech(), misdn_lib_send_event(), misdn_party_id::name, misdn_bchannel::nodsp, misdn_party_dialing::number, misdn_party_id::number, misdn_party_id::number_type, misdn_party_dialing::number_type, misdn_bchannel::out_cause, misdn_stack::port, misdn_stack::pri, misdn_stack::ptp, misdn_bchannel::rxgain, setup_bc(), and misdn_bchannel::txgain.
Referenced by handle_frm_te().
 {
    struct misdn_stack *stack=get_stack_by_bc(bc);
    switch (event) {
       case EVENT_CONNECT_ACKNOWLEDGE:
          setup_bc(bc);
          if ( *bc->crypt_key ) {
             cb_log(4, stack->port,
                "ENABLING BLOWFISH channel:%d caller%d:\"%s\" <%s> dialed%d:%s\n",
                bc->channel,
                bc->caller.number_type,
                bc->caller.name,
                bc->caller.number,
                bc->dialed.number_type,
                bc->dialed.number);
             manager_ph_control_block(bc,  BF_ENABLE_KEY, bc->crypt_key, strlen(bc->crypt_key) );
          }
          if (misdn_cap_is_speech(bc->capability)) {
             if (  !bc->nodsp) manager_ph_control(bc,  DTMF_TONE_START, 0);
             manager_ec_enable(bc);
             if ( bc->txgain != 0 ) {
                cb_log(4, stack->port, "--> Changing txgain to %d\n", bc->txgain);
                manager_ph_control(bc, VOL_CHANGE_TX, bc->txgain);
             }
             if ( bc->rxgain != 0 ) {
                cb_log(4, stack->port, "--> Changing rxgain to %d\n", bc->rxgain);
                manager_ph_control(bc, VOL_CHANGE_RX, bc->rxgain);
             }
          }
          break;
       case EVENT_CONNECT:
          if ( *bc->crypt_key ) {
             cb_log(4, stack->port,
                "ENABLING BLOWFISH channel:%d caller%d:\"%s\" <%s> dialed%d:%s\n",
                bc->channel,
                bc->caller.number_type,
                bc->caller.name,
                bc->caller.number,
                bc->dialed.number_type,
                bc->dialed.number);
             manager_ph_control_block(bc,  BF_ENABLE_KEY, bc->crypt_key, strlen(bc->crypt_key) );
          }
       case EVENT_ALERTING:
       case EVENT_PROGRESS:
       case EVENT_PROCEEDING:
       case EVENT_SETUP_ACKNOWLEDGE:
       case EVENT_SETUP:
       {
          if (bc->channel == 0xff || bc->channel<=0)
             bc->channel=0;
          if (find_free_chan_in_stack(stack, bc, bc->channel, 0)<0){
             if (!stack->pri && !stack->ptp)  {
                bc->cw=1;
                break;
             }
             if (!bc->channel) {
                cb_log(0, stack->port, "Any Channel Requested, but we have no more!!\n");
             } else {
                cb_log(0, stack->port,
                   "Requested Channel Already in Use releasing this call with cause %d!!!!\n",
                   bc->out_cause);
             }
             /* when the channel is already in use, we can't
              * simply clear it, we need to make sure that
              * it will still be marked as in_use in the
              * available channels list.*/
             bc->channel=0;
             misdn_lib_send_event(bc,EVENT_RELEASE_COMPLETE);
             return -1;
          }
          if (event != EVENT_SETUP) {
             setup_bc(bc);
          }
          break;
       }
       case EVENT_RELEASE_COMPLETE:
       case EVENT_RELEASE:
          break;
       default:
          break;
    }
    return 0;
 }
handle_frm_nt()
static int handle_frm_nt (msg_t * msg) static
Definition at line 2626 of file isdn_lib.c.
References cb_log, find_stack_by_addr(), pthread_mutex_lock, and pthread_mutex_unlock.
Referenced by manager_isdn_handler().
 {
    iframe_t *frm= (iframe_t*)msg->data;
    struct misdn_stack *stack;
    int err=0;
    stack=find_stack_by_addr( frm->addr );
    if (!stack || !stack->nt) {
       return 0;
    }
    pthread_mutex_lock(&stack->nstlock);
    if ((err=stack->nst.l1_l2(&stack->nst,msg))) {
       pthread_mutex_unlock(&stack->nstlock);
       if (nt_err_cnt > 0 ) {
          if (nt_err_cnt < 100) {
             nt_err_cnt++;
             cb_log(0, stack->port, "NT Stack sends us error: %d \n", err);
          } else if (nt_err_cnt < 105){
             cb_log(0, stack->port, "NT Stack sends us error: %d over 100 times, so I'll stop this message\n", err);
             nt_err_cnt = - 1;
          }
       }
       free_msg(msg);
       return 1;
    }
    pthread_mutex_unlock(&stack->nstlock);
    return 1;
 }
handle_frm_te()
static int handle_frm_te (msg_t * msg) static
Definition at line 2661 of file isdn_lib.c.
References AST_CAUSE_NORMAL_CLEARING, AST_CAUSE_REQUESTED_CHAN_UNAVAIL, bc, misdn_bchannel::cause, cb_event, cb_log, misdn_bchannel::channel, clean_up_bc(), empty_bc(), empty_chan_in_stack(), EVENT_RELEASE_COMPLETE, EVENT_RESTART, EVENT_SETUP, find_bc_by_l3id(), find_stack_by_addr(), handle_cr(), handle_event_te(), misdn_bchannel::in_use, isdn_get_info(), isdn_msg_get_event(), isdn_msg_parse_event(), misdn_bchannel::l3_id, misdn_lib_send_event(), misdn_lib_send_restart(), misdn_make_dummy(), msgs_g, misdn_bchannel::need_release_complete, misdn_stack::nt, misdn_bchannel::out_cause, misdn_stack::port, RESPONSE_IGNORE_SETUP, RESPONSE_IGNORE_SETUP_WITHOUT_CLOSE, RESPONSE_OK, RESPONSE_RELEASE_SETUP, misdn_bchannel::restart_channel, and misdn_lib::user_data.
Referenced by manager_isdn_handler().
 {
    struct misdn_bchannel dummybc;
    struct misdn_bchannel *bc;
    iframe_t *frm;
    struct misdn_stack *stack;
    enum event_e event;
    enum event_response_e response;
    int ret;
    int channel;
    int tmpcause;
    int tmp_out_cause;
    frm = (iframe_t*) msg->data;
    stack = find_stack_by_addr(frm->addr);
    if (!stack || stack->nt) {
       return 0;
    }
    cb_log(4, stack->port, "handle_frm_te: frm->addr:%x frm->prim:%x\n", frm->addr, frm->prim);
    ret = handle_cr(stack, frm);
    if (ret < 0) {
       cb_log(3, stack->port, "handle_frm_te: handle_cr <0 prim:%x addr:%x\n", frm->prim, frm->addr);
    }
    if (ret) {
       free_msg(msg);
       return 1;
    }
    bc = find_bc_by_l3id(stack, frm->dinfo);
    if (!bc) {
       misdn_make_dummy(&dummybc, stack->port, 0, stack->nt, 0);
       switch (frm->prim) {
       case CC_RESTART | CONFIRM:
          dummybc.l3_id = MISDN_ID_GLOBAL;
          bc = &dummybc;
          break;
       case CC_SETUP | INDICATION:
          dummybc.l3_id = frm->dinfo;
          bc = &dummybc;
          /* set a reasonable cause */
          bc->out_cause = AST_CAUSE_REQUESTED_CHAN_UNAVAIL;
          /* if we want to send something the flag must be set! */
          bc->need_release_complete = 1;
          misdn_lib_send_event(bc, EVENT_RELEASE_COMPLETE);
          free_msg(msg);
          return 1;
       default:
          if (frm->prim == (CC_FACILITY | INDICATION)) {
             cb_log(5, stack->port, " --> Using Dummy BC for FACILITY\n");
          } else {
             cb_log(0, stack->port, " --> Didn't find BC so temporarily creating dummy BC (l3id:%x) on this port.\n", frm->dinfo);
             dummybc.l3_id = frm->dinfo;
          }
          bc = &dummybc;
          break;
       }
    }
    event = isdn_msg_get_event(msgs_g, msg, 0);
    isdn_msg_parse_event(msgs_g, msg, bc, 0);
    /* Preprocess some Events */
    ret = handle_event_te(bc, event, frm);
    if (ret < 0) {
       cb_log(0, stack->port, "couldn't handle event\n");
       free_msg(msg);
       return 1;
    }
    /* shoot up event to App: */
    cb_log(5, stack->port, "lib Got Prim: Addr %x prim %x dinfo %x\n", frm->addr, frm->prim, frm->dinfo);
    if (!isdn_get_info(msgs_g, event, 0)) {
       cb_log(0, stack->port, "Unknown Event Ind: Addr:%x prim %x dinfo %x\n", frm->addr, frm->prim, frm->dinfo);
       response = RESPONSE_OK;
    } else {
       response = cb_event(event, bc, glob_mgr->user_data);
    }
    switch (event) {
    case EVENT_SETUP:
       switch (response) {
       case RESPONSE_IGNORE_SETUP_WITHOUT_CLOSE:
          cb_log(0, stack->port, "TOTALLY IGNORING SETUP\n");
          break;
       case RESPONSE_IGNORE_SETUP:
          cb_log(0, stack->port, "GOT IGNORE SETUP\n");
          /* I think we should send CC_RELEASE_CR, but am not sure*/
          bc->out_cause = AST_CAUSE_NORMAL_CLEARING;
          /* fall through */
       case RESPONSE_RELEASE_SETUP:
          if (response == RESPONSE_RELEASE_SETUP) {
             cb_log(0, stack->port, "GOT RELEASE SETUP\n");
          }
          misdn_lib_send_event(bc, EVENT_RELEASE_COMPLETE);
          break;
       case RESPONSE_OK:
          cb_log(4, stack->port, "GOT SETUP OK\n");
          break;
       default:
          cb_log(0, stack->port, "GOT UNKNOWN SETUP RESPONSE\n");
          break;
       }
       break;
    case EVENT_RELEASE_COMPLETE:
       /* release bchannel only after we've announced the RELEASE_COMPLETE */
       channel = bc->channel;
       tmpcause = bc->cause;
       tmp_out_cause = bc->out_cause;
       empty_bc(bc);
       bc->cause = tmpcause;
       bc->out_cause = tmp_out_cause;
       clean_up_bc(bc);
       bc->in_use = 0;
       if (tmpcause == AST_CAUSE_REQUESTED_CHAN_UNAVAIL) {
          cb_log(0, stack->port, "**** Received CAUSE:%d, restarting channel %d\n", AST_CAUSE_REQUESTED_CHAN_UNAVAIL, channel);
          misdn_lib_send_restart(stack->port, channel);
       }
       if (channel > 0) {
          empty_chan_in_stack(stack, channel);
       }
       break;
    case EVENT_RESTART:
       cb_log(0, stack->port, "**** Received RESTART channel:%d\n", bc->restart_channel);
       empty_chan_in_stack(stack, bc->restart_channel);
       break;
    default:
       break;
    }
    cb_log(5, stack->port, "Freeing Msg on prim:%x \n", frm->prim);
    free_msg(msg);
    return 1;
 }
handle_l1()
static int handle_l1 (msg_t * msg) static
Definition at line 2803 of file isdn_lib.c.
References cb_event, cb_log, EVENT_CLEANUP, find_stack_by_addr(), MISDN_INITIALIZED, misdn_lib_get_l2_up(), pthread_mutex_lock, pthread_mutex_unlock, and misdn_lib::user_data.
Referenced by manager_isdn_handler().
 {
    iframe_t *frm = (iframe_t*) msg->data;
    struct misdn_stack *stack = find_stack_by_addr(frm->addr);
    if (!stack) return 0 ;
    switch (frm->prim) {
    case PH_ACTIVATE | CONFIRM:
       /* we have to check for errors! */
       if (frm->len) {
          cb_log (3, stack->port, "L1: PH_ACTIVATE|REQUEST returned error!\n");
          free_msg(msg);
          return 1;
       }
       /* fall through */
    case PH_ACTIVATE | INDICATION:
       cb_log (3, stack->port, "L1: PH L1Link Up!\n");
       stack->l1link=1;
       if (stack->nt) {
          pthread_mutex_lock(&stack->nstlock);
          if (stack->nst.l1_l2(&stack->nst, msg))
             free_msg(msg);
          pthread_mutex_unlock(&stack->nstlock);
          if (stack->ptp)
             misdn_lib_get_l2_up(stack);
       } else {
          free_msg(msg);
       }
       return 1;
    case PH_ACTIVATE | REQUEST:
       free_msg(msg);
       cb_log(3,stack->port,"L1: PH_ACTIVATE|REQUEST \n");
       return 1;
    case PH_DEACTIVATE | REQUEST:
       free_msg(msg);
       cb_log(3,stack->port,"L1: PH_DEACTIVATE|REQUEST \n");
       return 1;
    case PH_DEACTIVATE | CONFIRM:
       /* we have to check for errors! */
       if (frm->len) {
          cb_log (3, stack->port, "L1: PH_DEACTIVATE|REQUEST returned error!\n");
          free_msg(msg);
          return 1;
       }
       /* fall through */
    case PH_DEACTIVATE | INDICATION:
       cb_log (3, stack->port, "L1: PH L1Link Down! \n");
 #if 0
       for (i=0; i<=stack->b_num; i++) {
          if (global_state == MISDN_INITIALIZED)  {
             cb_event(EVENT_CLEANUP, &stack->bc[i], glob_mgr->user_data);
          }
       }
 #endif
       if (stack->nt) {
          pthread_mutex_lock(&stack->nstlock);
          if (stack->nst.l1_l2(&stack->nst, msg))
             free_msg(msg);
          pthread_mutex_unlock(&stack->nstlock);
       } else {
          free_msg(msg);
       }
       stack->l1link=0;
       stack->l2link=0;
       return 1;
    }
    return 0;
 }
handle_l2()
static int handle_l2 (msg_t * msg) static
Definition at line 2883 of file isdn_lib.c.
References cb_event, cb_log, EVENT_PORT_ALARM, find_stack_by_addr(), and misdn_lib::user_data.
Referenced by manager_isdn_handler().
 {
    iframe_t *frm = (iframe_t*) msg->data;
    struct misdn_stack *stack = find_stack_by_addr(frm->addr);
    if (!stack) {
       return 0 ;
    }
    switch(frm->prim) {
    case DL_ESTABLISH | REQUEST:
       cb_log(1,stack->port,"DL_ESTABLISH|REQUEST \n");
       free_msg(msg);
       return 1;
    case DL_RELEASE | REQUEST:
       cb_log(1,stack->port,"DL_RELEASE|REQUEST \n");
       free_msg(msg);
       return 1;
    case DL_ESTABLISH | INDICATION:
    case DL_ESTABLISH | CONFIRM:
    {
       cb_log (3, stack->port, "L2: L2Link Up! \n");
       if (stack->ptp && stack->l2link) {
          cb_log (-1, stack->port, "L2: L2Link Up! but it's already UP.. must be faulty, blocking port\n");
          cb_event(EVENT_PORT_ALARM, &stack->bc[0], glob_mgr->user_data);
       }
       stack->l2link=1;
       free_msg(msg);
       return 1;
    }
    break;
    case DL_RELEASE | INDICATION:
    case DL_RELEASE | CONFIRM:
    {
       cb_log (3, stack->port, "L2: L2Link Down! \n");
       stack->l2link=0;
       free_msg(msg);
       return 1;
    }
    break;
    }
    return 0;
 }
handle_mgmt()
static int handle_mgmt (msg_t * msg) static
Definition at line 2932 of file isdn_lib.c.
References cb_log, clear_l3(), find_stack_by_addr(), and if().
Referenced by manager_isdn_handler().
 {
    iframe_t *frm = (iframe_t*) msg->data;
    struct misdn_stack *stack;
    if ( (frm->addr == 0) && (frm->prim == (MGR_DELLAYER|CONFIRM)) ) {
       cb_log(2, 0, "MGMT: DELLAYER|CONFIRM Addr: 0 !\n") ;
       free_msg(msg);
       return 1;
    }
    stack = find_stack_by_addr(frm->addr);
    if (!stack) {
       if (frm->prim == (MGR_DELLAYER|CONFIRM)) {
          cb_log(2, 0, "MGMT: DELLAYER|CONFIRM Addr: %x !\n",
                frm->addr) ;
          free_msg(msg);
          return 1;
       }
       return 0;
    }
    switch(frm->prim) {
    case MGR_SHORTSTATUS | INDICATION:
    case MGR_SHORTSTATUS | CONFIRM:
       cb_log(5, stack->port, "MGMT: Short status dinfo %x\n",frm->dinfo);
       switch (frm->dinfo) {
       case SSTATUS_L1_ACTIVATED:
          cb_log(3, stack->port, "MGMT: SSTATUS: L1_ACTIVATED \n");
          stack->l1link=1;
          break;
       case SSTATUS_L1_DEACTIVATED:
          cb_log(3, stack->port, "MGMT: SSTATUS: L1_DEACTIVATED \n");
          stack->l1link=0;
 #if 0
          clear_l3(stack);
 #endif
          break;
       case SSTATUS_L2_ESTABLISHED:
          cb_log(3, stack->port, "MGMT: SSTATUS: L2_ESTABLISH \n");
          stack->l2link=1;
          break;
       case SSTATUS_L2_RELEASED:
          cb_log(3, stack->port, "MGMT: SSTATUS: L2_RELEASED \n");
          stack->l2link=0;
          break;
       }
       free_msg(msg);
       return 1;
    case MGR_SETSTACK | INDICATION:
       cb_log(4, stack->port, "MGMT: SETSTACK|IND dinfo %x\n",frm->dinfo);
       free_msg(msg);
       return 1;
    case MGR_DELLAYER | CONFIRM:
       cb_log(4, stack->port, "MGMT: DELLAYER|CNF dinfo %x\n",frm->dinfo) ;
       free_msg(msg);
       return 1;
    }
    /*
    if ( (frm->prim & 0x0f0000) ==  0x0f0000) {
    cb_log(5, 0, "$$$ MGMT FRAME: prim %x addr %x dinfo %x\n",frm->prim, frm->addr, frm->dinfo) ;
    free_msg(msg);
    return 1;
    } */
    return 0;
 }
handle_timers()
static int handle_timers (msg_t * msg) static
Definition at line 2216 of file isdn_lib.c.
References cb_log, misdn_stack::next, NULL, pthread_mutex_lock, pthread_mutex_unlock, and misdn_lib::stack_list.
Referenced by manager_isdn_handler().
 {
    iframe_t *frm= (iframe_t*)msg->data;
    struct misdn_stack *stack;
    /* Timer Stuff */
    switch (frm->prim) {
    case MGR_INITTIMER | CONFIRM:
    case MGR_ADDTIMER | CONFIRM:
    case MGR_DELTIMER | CONFIRM:
    case MGR_REMOVETIMER | CONFIRM:
       free_msg(msg);
       return(1);
    }
    if (frm->prim==(MGR_TIMER | INDICATION) ) {
       for (stack = glob_mgr->stack_list;
            stack;
            stack = stack->next) {
          itimer_t *it;
          if (!stack->nt) continue;
          it = stack->nst.tlist;
          /* find timer */
          for(it=stack->nst.tlist;
              it;
              it=it->next) {
             if (it->id == (int)frm->addr)
                break;
          }
          if (it) {
             mISDN_write_frame(stack->midev, msg->data, frm->addr,
                     MGR_TIMER | RESPONSE, 0, 0, NULL, TIMEOUT_1SEC);
             test_and_clear_bit(FLG_TIMER_RUNING, (long unsigned int *)&it->Flags);
             pthread_mutex_lock(&stack->nstlock);
             it->function(it->data);
             pthread_mutex_unlock(&stack->nstlock);
             free_msg(msg);
             return 1;
          }
       }
       cb_log(0, 0, "Timer Msg without Timer ??\n");
       free_msg(msg);
       return 1;
    }
    return 0;
 }
init_bc()
static int init_bc (struct misdn_stack * stack, struct misdn_bchannel * bc, int midev, int port, int bidx) static
IFACE
Definition at line 1210 of file isdn_lib.c.
References misdn_bchannel::astbuf, misdn_stack::b_num, bc_state_change(), BCHAN_CLEANED, buff, cb_log, empty_bc(), send_lock::lock, malloc(), MISDN_IBUF_SIZE, misdn_stack::nt, misdn_bchannel::nt, NULL, misdn_stack::port, misdn_bchannel::port, misdn_stack::pri, misdn_bchannel::pri, pthread_mutex_init, and misdn_bchannel::send_lock.
Referenced by misdn_lib_init().
 {
    if (!bc) {
       return -1;
    }
    cb_log(8, port, "Init.BC %d.\n",bidx);
    bc->send_lock = malloc(sizeof(struct send_lock)); /* XXX BUG! memory leak never freed */
    if (!bc->send_lock) {
       return -1;
    }
    pthread_mutex_init(&bc->send_lock->lock, NULL);
    empty_bc(bc);
    bc->port=stack->port;
    bc_state_change(bc, BCHAN_CLEANED);
    bc->nt=stack->nt?1:0;
    bc->pri=stack->pri;
    {
       ibuffer_t* ibuf= init_ibuffer(MISDN_IBUF_SIZE);
       if (!ibuf) return -1;
       clear_ibuffer( ibuf);
       ibuf->rsem=malloc(sizeof(sem_t));
       if (!ibuf->rsem) {
          return -1;
       }
       bc->astbuf=ibuf;
       if (sem_init(ibuf->rsem,1,0)<0)
          sem_init(ibuf->rsem,0,0);
    }
 #if 0 /* This code does not seem to do anything useful */
    if (bidx <= stack->b_num) {
       unsigned char buff[1025];
       iframe_t *frm = (iframe_t *) buff;
       stack_info_t *stinf;
       int ret;
       ret = mISDN_get_stack_info(midev, stack->port, buff, sizeof(buff));
       if (ret < 0) {
          cb_log(0, port, "%s: Cannot get stack info for this port. (ret=%d)\n", __FUNCTION__, ret);
          return -1;
       }
       stinf = (stack_info_t *)&frm->data.p;
       cb_log(8, port, " --> Child %x\n",stinf->child[bidx]);
    }
 #endif
    return 0;
 }
init_flip_bits()
static void init_flip_bits (void) static
Definition at line 321 of file isdn_lib.c.
Referenced by misdn_lib_init().
 {
    int i,k;
    for (i = 0 ; i < 256 ; i++) {
       unsigned char sample = 0 ;
       for (k = 0; k<8; k++) {
          if ( i & 1 << k ) sample |= 0x80 >>  k;
       }
       flip_table[i] = sample;
    }
 }
isdn_lib_stop_dtmf()
void isdn_lib_stop_dtmf (struct misdn_bchannel * bc)
Definition at line 4462 of file isdn_lib.c.
References manager_ph_control().
Referenced by process_ast_dsp().
 {
    manager_ph_control(bc, DTMF_TONE_STOP, 0);
 }
isdn_lib_update_ec()
void isdn_lib_update_ec (struct misdn_bchannel * bc)
Definition at line 4450 of file isdn_lib.c.
References misdn_bchannel::ec_enable, manager_ec_disable(), and manager_ec_enable().
Referenced by process_ast_dsp().
 {
 #ifdef MISDN_1_2
    if (*bc->pipeline)
 #else
    if (bc->ec_enable)
 #endif
       manager_ec_enable(bc);
    else
       manager_ec_disable(bc);
 }
isdn_lib_update_rxgain()
void isdn_lib_update_rxgain (struct misdn_bchannel * bc)
Definition at line 4440 of file isdn_lib.c.
References manager_ph_control(), and misdn_bchannel::rxgain.
Referenced by process_ast_dsp().
 {
    manager_ph_control(bc, VOL_CHANGE_RX, bc->rxgain);
 }
isdn_lib_update_txgain()
void isdn_lib_update_txgain (struct misdn_bchannel * bc)
Definition at line 4445 of file isdn_lib.c.
References manager_ph_control(), and misdn_bchannel::txgain.
Referenced by process_ast_dsp().
 {
    manager_ph_control(bc, VOL_CHANGE_TX, bc->txgain);
 }
manager_bchannel_activate()
void manager_bchannel_activate (struct misdn_bchannel * bc)
Definition at line 4329 of file isdn_lib.c.
References misdn_bchannel::addr, misdn_bchannel::astbuf, buf, cb_log, get_stack_by_bc(), misdn_stack::midev, NULL, misdn_stack::port, and misdn_bchannel::port.
Referenced by setup_bc().
 {
    char buf[128];
    struct misdn_stack *stack=get_stack_by_bc(bc);
    if (!stack) {
       cb_log(0, bc->port, "bchannel_activate: Stack not found !");
       return ;
    }
    /* we must activate if we are deactivated */
    clear_ibuffer(bc->astbuf);
    cb_log(5, stack->port, "$$$ Bchan Activated addr %x\n", bc->addr);
    mISDN_write_frame(stack->midev, buf, bc->addr | FLG_MSG_DOWN,  DL_ESTABLISH | REQUEST, 0,0, NULL, TIMEOUT_1SEC);
    return ;
 }
manager_bchannel_cleanup()
void manager_bchannel_cleanup (struct misdn_bchannel * bc)
manager_bchannel_deactivate()
void manager_bchannel_deactivate (struct misdn_bchannel * bc)
Definition at line 4351 of file isdn_lib.c.
References misdn_bchannel::addr, misdn_bchannel::astbuf, misdn_bchannel::bc_state, bc_state_change(), BCHAN_ACTIVATED, BCHAN_BRIDGED, BCHAN_RELEASE, buf, cb_log, misdn_bchannel::conf_id, misdn_bchannel::generate_tone, get_stack_by_bc(), misdn_stack::midev, misdn_split_conf(), NULL, misdn_stack::port, and misdn_bchannel::port.
Referenced by clean_up_bc().
 {
    struct misdn_stack *stack=get_stack_by_bc(bc);
    char buf[128];
    switch (bc->bc_state) {
       case BCHAN_ACTIVATED:
          break;
       case BCHAN_BRIDGED:
          misdn_split_conf(bc,bc->conf_id);
          break;
       default:
          cb_log( 4, bc->port,"bchan_deactivate: called but not activated\n");
          return ;
    }
    cb_log(5, stack->port, "$$$ Bchan deActivated addr %x\n", bc->addr);
    bc->generate_tone=0;
    mISDN_write_frame(stack->midev, buf, bc->addr | FLG_MSG_DOWN, DL_RELEASE|REQUEST,0,0,NULL, TIMEOUT_1SEC);
    clear_ibuffer(bc->astbuf);
    bc_state_change(bc,BCHAN_RELEASE);
    return;
 }
manager_bchannel_setup()
void manager_bchannel_setup (struct misdn_bchannel * bc)
manager_clean_bc()
void manager_clean_bc (struct misdn_bchannel * bc)
Definition at line 4489 of file isdn_lib.c.
References cb_event, misdn_bchannel::channel, empty_bc(), empty_chan_in_stack(), EVENT_CLEANUP, get_stack_by_bc(), misdn_bchannel::in_use, and NULL.
Referenced by misdn_lib_pid_restart().
 {
    struct misdn_stack *stack=get_stack_by_bc(bc);
    if (stack && bc->channel > 0) {
       empty_chan_in_stack(stack, bc->channel);
    }
    empty_bc(bc);
    bc->in_use=0;
    cb_event(EVENT_CLEANUP, bc, NULL);
 }
manager_ec_disable()
void manager_ec_disable (struct misdn_bchannel * bc)
Definition at line 4677 of file isdn_lib.c.
References misdn_bchannel::capability, cb_log, misdn_bchannel::ec_enable, ECHOCAN_OFF, get_stack_by_bc(), manager_ph_control(), manager_ph_control_block(), misdn_cap_is_speech(), and misdn_stack::port.
Referenced by clean_up_bc(), handle_cli_misdn_toggle_echocancel(), and isdn_lib_update_ec().
 {
    struct misdn_stack *stack=get_stack_by_bc(bc);
    cb_log(4, stack?stack->port:0," --> ec_disable\n");
    if (!misdn_cap_is_speech(bc->capability)) {
       cb_log(1, stack?stack->port:0, " --> no speech? cannot disable EC\n");
       return;
    }
 #ifdef MISDN_1_2
    manager_ph_control_block(bc, PIPELINE_CFG, "", 0);
 #else
    if ( ! bc->ec_enable) {
       cb_log(3, stack?stack->port:0, "Sending Control ECHOCAN_OFF\n");
       manager_ph_control(bc,  ECHOCAN_OFF, 0);
    }
 #endif
 }
manager_ec_enable()
void manager_ec_enable (struct misdn_bchannel * bc)
Definition at line 4628 of file isdn_lib.c.
References misdn_bchannel::capability, cb_log, misdn_bchannel::ec_deftaps, misdn_bchannel::ec_enable, ECHOCAN_ON, get_stack_by_bc(), manager_ph_control_block(), misdn_cap_is_speech(), and misdn_stack::port.
Referenced by handle_cli_misdn_toggle_echocancel(), handle_event_te(), isdn_lib_update_ec(), and misdn_lib_send_event().
 {
    struct misdn_stack *stack=get_stack_by_bc(bc);
    cb_log(4, stack?stack->port:0,"ec_enable\n");
    if (!misdn_cap_is_speech(bc->capability)) {
       cb_log(1, stack?stack->port:0, " --> no speech? cannot enable EC\n");
    } else {
 #ifdef MISDN_1_2
    if (*bc->pipeline) {
       cb_log(3, stack?stack->port:0,"Sending Control PIPELINE_CFG %s\n",bc->pipeline);
       manager_ph_control_block(bc, PIPELINE_CFG, bc->pipeline, strlen(bc->pipeline) + 1);
    }
 #else
    int ec_arr[2];
    if (bc->ec_enable) {
       cb_log(3, stack?stack->port:0,"Sending Control ECHOCAN_ON taps:%d\n",bc->ec_deftaps);
       switch (bc->ec_deftaps) {
       case 4:
       case 8:
       case 16:
       case 32:
       case 64:
       case 128:
       case 256:
       case 512:
       case 1024:
          cb_log(4, stack->port, "Taps is %d\n",bc->ec_deftaps);
          break;
       default:
          cb_log(0, stack->port, "Taps should be power of 2\n");
          bc->ec_deftaps=128;
       }
       ec_arr[0]=bc->ec_deftaps;
       ec_arr[1]=0;
       manager_ph_control_block(bc,  ECHOCAN_ON,  ec_arr, sizeof(ec_arr));
    }
 #endif
    }
 }
manager_event_handler()
static void manager_event_handler (void * arg) static
wait for events
Definition at line 4025 of file isdn_lib.c.
References misdn_lib::activatequeue, cb_log, misdn_stack::downqueue, find_bc_by_l3id(), misdn_lib::midev, misdn_make_dummy(), misdn_lib::new_msg, misdn_stack::next, misdn_stack::nst, misdn_stack::nstlock, misdn_stack::nt, misdn_stack::port, pthread_mutex_lock, pthread_mutex_unlock, send_msg(), and misdn_lib::stack_list.
Referenced by misdn_lib_init().
 {
    sem_post(&handler_started);
    while (1) {
       struct misdn_stack *stack;
       msg_t *msg;
       /** wait for events **/
       sem_wait(&glob_mgr->new_msg);
       for (msg=msg_dequeue(&glob_mgr->activatequeue);
            msg;
            msg=msg_dequeue(&glob_mgr->activatequeue)
          )
       {
          iframe_t *frm =  (iframe_t*) msg->data ;
          switch ( frm->prim) {
          case MGR_SETSTACK | REQUEST :
             free_msg(msg);
             break;
          default:
             mISDN_write(glob_mgr->midev, frm, mISDN_HEADER_LEN+frm->len, TIMEOUT_1SEC);
             free_msg(msg);
          }
       }
       for (stack=glob_mgr->stack_list;
            stack;
            stack=stack->next ) {
          /* Here we should check if we really want to
             send all the messages we've queued, lets
             assume we've queued a Disconnect, but
             received it already from the other side!*/
          while ( (msg=msg_dequeue(&stack->downqueue)) ) {
             if (stack->nt ) {
                pthread_mutex_lock(&stack->nstlock);
                if (stack->nst.manager_l3(&stack->nst, msg))
                   cb_log(0, stack->port, "Error@ Sending Message in NT-Stack.\n");
                pthread_mutex_unlock(&stack->nstlock);
             } else {
                iframe_t *frm = (iframe_t *)msg->data;
                struct misdn_bchannel *bc = find_bc_by_l3id(stack, frm->dinfo);
                if (bc)
                   send_msg(glob_mgr->midev, bc, msg);
                else  {
                   struct misdn_bchannel dummybc;
                   misdn_make_dummy(&dummybc, stack->port, frm->dinfo, stack->nt, 0);
                   if (frm->dinfo == MISDN_ID_GLOBAL || frm->dinfo == MISDN_ID_DUMMY ) {
                      cb_log(5,0," --> GLOBAL/DUMMY\n");
                   } else {
                      /*
                       * We need to be able to at least answer with RELEASE_COMPLETE
                       * on SETUP|INDICATION errors so use a dummy bc.
                       */
                      cb_log(0,0,"No bc for Message.  Using dummy_bc\n");
                   }
                   send_msg(glob_mgr->midev, &dummybc, msg);
                }
             }
          }
       }
    }
 }
manager_find_bc_by_pid()
struct misdn_bchannel * manager_find_bc_by_pid (int pid)
Definition at line 3152 of file isdn_lib.c.
References misdn_stack::b_num, misdn_stack::bc, misdn_bchannel::in_use, misdn_stack::next, NULL, misdn_bchannel::pid, and misdn_lib::stack_list.
Referenced by misdn_lib_pid_restart().
 {
    struct misdn_stack *stack;
    int i;
    for (stack = glob_mgr->stack_list; stack; stack = stack->next) {
       for (i = 0; i <= stack->b_num; i++) {
          if (stack->bc[i].in_use && stack->bc[i].pid == pid) {
             return &stack->bc[i];
          }
       }
    }
    return NULL;
 }
manager_isdn_get_info()
char* manager_isdn_get_info (enum event_e event)
Definition at line 4324 of file isdn_lib.c.
References isdn_get_info(), and msgs_g.
Referenced by cb_events().
 {
    return isdn_get_info(msgs_g , event, 0);
 }
manager_isdn_handler()
int manager_isdn_handler (iframe_t * frm, msg_t * msg)
Definition at line 3837 of file isdn_lib.c.
References cb_log, handle_bchan(), handle_err(), handle_frm_nt(), handle_frm_te(), handle_l1(), handle_l2(), handle_mgmt(), handle_timers(), and LOG_NOTICE.
Referenced by misdn_lib_isdn_event_catcher().
 {
    if (frm->dinfo==0xffffffff && frm->prim==(PH_DATA|CONFIRM)) {
       cb_log(0,0,"SERIOUS BUG, dinfo == 0xffffffff, prim == PH_DATA | CONFIRM !!!!\n");
    }
    /* Timer primitives must be handled first, because the frm->addr is a different
     * "address space" than the stack/instance address of other Lx primitives.
     */
    if (handle_timers(msg)) {
       return 0;
    }
    if ( ((frm->addr | ISDN_PID_BCHANNEL_BIT )>> 28 ) == 0x5) {
       static int unhandled_bmsg_count=1000;
       if (handle_bchan(msg)) {
          return 0 ;
       }
       if (unhandled_bmsg_count==1000) {
          cb_log(0, 0, "received 1k Unhandled Bchannel Messages: prim %x len %d from addr %x, dinfo %x on this port.\n",frm->prim, frm->len, frm->addr, frm->dinfo);
          unhandled_bmsg_count=0;
       }
       unhandled_bmsg_count++;
       free_msg(msg);
       return 0;
    }
 #ifdef RECV_FRM_SYSLOG_DEBUG
    syslog(LOG_NOTICE,"mISDN recv: ADDR:%x PRIM:%x DINFO:%x\n", frm->addr, frm->prim, frm->dinfo);
 #endif
    if (handle_mgmt(msg))
       return 0 ;
    if (handle_l2(msg))
       return 0 ;
    /* Its important to handle l1 AFTER l2  */
    if (handle_l1(msg))
       return 0 ;
    if (handle_frm_nt(msg)) {
       return 0;
    }
    if (handle_frm_te(msg)) {
       return 0;
    }
    if (handle_err(msg)) {
       return 0 ;
    }
    cb_log(0, 0, "Unhandled Message: prim %x len %d from addr %x, dinfo %x on this port.\n",frm->prim, frm->len, frm->addr, frm->dinfo);
    free_msg(msg);
    return 0;
 }
manager_ph_control()
void manager_ph_control (struct misdn_bchannel * bc, int c1, int c2)
Definition at line 4419 of file isdn_lib.c.
References misdn_bchannel::addr, cb_log, d, misdn_lib::midev, and misdn_bchannel::port.
Referenced by handle_event_te(), isdn_lib_stop_dtmf(), isdn_lib_update_rxgain(), isdn_lib_update_txgain(), manager_ec_disable(), misdn_join_conf(), misdn_lib_echo(), misdn_lib_send_event(), misdn_lib_send_tone(), and misdn_split_conf().
 {
    unsigned char buffer[mISDN_HEADER_LEN+2*sizeof(int)];
    iframe_t *ctrl = (iframe_t *)buffer; /* preload data */
    unsigned int *d = (unsigned int*)&ctrl->data.p;
    /*struct misdn_stack *stack=get_stack_by_bc(bc);*/
    cb_log(4,bc->port,"ph_control: c1:%x c2:%x\n",c1,c2);
    ctrl->prim = PH_CONTROL | REQUEST;
    ctrl->addr = bc->addr | FLG_MSG_DOWN;
    ctrl->dinfo = 0;
    ctrl->len = sizeof(unsigned int)*2;
    *d++ = c1;
    *d++ = c2;
    mISDN_write(glob_mgr->midev, ctrl, mISDN_HEADER_LEN+ctrl->len, TIMEOUT_1SEC);
 }
manager_ph_control_block()
void manager_ph_control_block (struct misdn_bchannel * bc, int c1, void * c2, int c2_len)
Definition at line 4470 of file isdn_lib.c.
References misdn_bchannel::addr, d, and misdn_lib::midev.
Referenced by handle_event_te(), manager_ec_disable(), manager_ec_enable(), and misdn_lib_send_event().
 {
    unsigned char buffer[mISDN_HEADER_LEN+sizeof(int)+c2_len];
    iframe_t *ctrl = (iframe_t *)buffer;
    unsigned int *d = (unsigned int *)&ctrl->data.p;
    /*struct misdn_stack *stack=get_stack_by_bc(bc);*/
    ctrl->prim = PH_CONTROL | REQUEST;
    ctrl->addr = bc->addr | FLG_MSG_DOWN;
    ctrl->dinfo = 0;
    ctrl->len = sizeof(unsigned int) + c2_len;
    *d++ = c1;
    memcpy(d, c2, c2_len);
    mISDN_write(glob_mgr->midev, ctrl, mISDN_HEADER_LEN+ctrl->len, TIMEOUT_1SEC);
 }
misdn_cap_is_speech()
int misdn_cap_is_speech (int cap)
Poor mans version
Definition at line 436 of file isdn_lib.c.
References INFO_CAPABILITY_DIGITAL_RESTRICTED, and INFO_CAPABILITY_DIGITAL_UNRESTRICTED.
Referenced by cb_events(), handle_bchan(), handle_event_te(), manager_ec_disable(), manager_ec_enable(), misdn_lib_send_event(), misdn_lib_tx2misdn_frm(), and misdn_write().
 {
    if ( (cap != INFO_CAPABILITY_DIGITAL_UNRESTRICTED) &&
         (cap != INFO_CAPABILITY_DIGITAL_RESTRICTED) ) return 1;
    return 0;
 }
misdn_dump_chanlist()
void misdn_dump_chanlist (void)
Definition at line 483 of file isdn_lib.c.
References dump_chan_list(), get_misdn_stack(), and misdn_stack::next.
Referenced by handle_cli_misdn_show_channels().
 {
    struct misdn_stack *stack=get_misdn_stack();
    for ( ; stack; stack=stack->next) {
       dump_chan_list(stack);
    }
 }
misdn_inband_avail()
int misdn_inband_avail (struct misdn_bchannel * bc)
Definition at line 444 of file isdn_lib.c.
References misdn_bchannel::early_bconnect, INFO_PI_CALL_NOT_E2E_ISDN, INFO_PI_CALLED_NOT_ISDN, INFO_PI_INBAND_AVAILABLE, and misdn_bchannel::progress_indicator.
Referenced by cb_events().
 {
    if (!bc->early_bconnect) {
       /* We have opted to never receive any available inband recorded messages */
       return 0;
    }
    switch (bc->progress_indicator) {
    case INFO_PI_INBAND_AVAILABLE:
    case INFO_PI_CALL_NOT_E2E_ISDN:
    case INFO_PI_CALLED_NOT_ISDN:
       return 1;
    default:
       return 0;
    }
    return 0;
 }
misdn_join_conf()
void misdn_join_conf (struct misdn_bchannel * bc, int conf_id)
Definition at line 4705 of file isdn_lib.c.
References misdn_bchannel::addr, bc_state_change(), BCHAN_BRIDGED, cb_log, manager_ph_control(), misdn_lib_tx2misdn_frm(), and misdn_bchannel::port.
Referenced by bc_state_change(), and misdn_lib_bridge().
 {
    char data[16] = "";
    bc_state_change(bc,BCHAN_BRIDGED);
    manager_ph_control(bc, CMX_RECEIVE_OFF, 0);
    manager_ph_control(bc, CMX_CONF_JOIN, conf_id);
    cb_log(3,bc->port, "Joining bc:%x in conf:%d\n",bc->addr,conf_id);
    misdn_lib_tx2misdn_frm(bc, data, sizeof(data) - 1);
 }
misdn_lib_bridge()
void misdn_lib_bridge (struct misdn_bchannel * bc1, struct misdn_bchannel * bc2)
Definition at line 4728 of file isdn_lib.c.
References bc, bc_next_state_change(), BCHAN_ACTIVATED, BCHAN_BRIDGED, cb_log, misdn_bchannel::conf_id, misdn_join_conf(), NULL, misdn_bchannel::pid, and misdn_bchannel::port.
Referenced by misdn_write().
 {
    int conf_id = bc1->pid + 1;
    struct misdn_bchannel *bc_list[] = { bc1, bc2, NULL };
    struct misdn_bchannel **bc;
    cb_log(4, bc1->port, "I Send: BRIDGE from:%d to:%d\n",bc1->port,bc2->port);
    for (bc=bc_list; *bc;  bc++) {
       (*bc)->conf_id=conf_id;
       cb_log(4, (*bc)->port, " --> bc_addr:%x\n",(*bc)->addr);
       switch((*bc)->bc_state) {
          case BCHAN_ACTIVATED:
             misdn_join_conf(*bc,conf_id);
             break;
          default:
             bc_next_state_change(*bc,BCHAN_BRIDGED);
             break;
       }
    }
 }
misdn_lib_destroy()
void misdn_lib_destroy (void)
Definition at line 4285 of file isdn_lib.c.
References misdn_bchannel::addr, misdn_stack::b_num, misdn_stack::bc, buf, cb_log, misdn_lib::event_handler_thread, misdn_lib::event_thread, free(), misdn_stack::midev, misdn_lib::midev, MISDN_INITIALIZED, misdn_stack::next, NULL, misdn_stack::port, stack_destroy(), misdn_lib::stack_list, and te_lib_destroy().
Referenced by unload_module().
 {
    struct misdn_stack *help;
    int i;
    for ( help=glob_mgr->stack_list; help; help=help->next ) {
       for(i=0;i<=help->b_num; i++) {
          char buf[1024];
          mISDN_write_frame(help->midev, buf, help->bc[i].addr, MGR_DELLAYER | REQUEST, 0, 0, NULL, TIMEOUT_1SEC);
          help->bc[i].addr = 0;
       }
       cb_log (1, help->port, "Destroying this port.\n");
       stack_destroy(help);
    }
    if (global_state == MISDN_INITIALIZED) {
       cb_log(4, 0, "Killing Handler Thread\n");
       if ( pthread_cancel(glob_mgr->event_handler_thread) == 0 ) {
          cb_log(4, 0, "Joining Handler Thread\n");
          pthread_join(glob_mgr->event_handler_thread, NULL);
       }
       cb_log(4, 0, "Killing Main Thread\n");
       if ( pthread_cancel(glob_mgr->event_thread) == 0 ) {
          cb_log(4, 0, "Joining Main Thread\n");
          pthread_join(glob_mgr->event_thread, NULL);
       }
    }
    cb_log(1, 0, "Closing mISDN device\n");
    te_lib_destroy(glob_mgr->midev);
    while ((help = glob_mgr->stack_list)) {
       glob_mgr->stack_list = help->next;
       free(help);
    }
    free(glob_mgr);
    glob_mgr = NULL;
 }
misdn_lib_echo()
void misdn_lib_echo (struct misdn_bchannel * bc, int onoff)
Definition at line 4771 of file isdn_lib.c.
References cb_log, manager_ph_control(), and misdn_bchannel::port.
 {
    cb_log(3,bc->port, " --> ECHO %s\n", onoff?"ON":"OFF");
    manager_ph_control(bc, onoff?CMX_ECHO_ON:CMX_ECHO_OFF, 0);
 }
misdn_lib_find_held_bc()
struct misdn_bchannel* misdn_lib_find_held_bc (int port, int l3_id)
Find a held call's B channel record.
Parameters
port Port the call is on.
l3_id mISDN Layer 3 ID of held call.
Returns
Found bc-record or NULL.
Definition at line 4580 of file isdn_lib.c.
References bc, get_misdn_stack(), misdn_stack::next, NULL, misdn_stack::port, and stack_holder_find().
Referenced by misdn_hangup().
 {
    struct misdn_bchannel *bc;
    struct misdn_stack *stack;
    bc = NULL;
    for (stack = get_misdn_stack(); stack; stack = stack->next) {
       if (stack->port == port) {
          bc = stack_holder_find(stack, l3_id);
          break;
       }
    }
    return bc;
 }
misdn_lib_get_free_bc()
struct misdn_bchannel* misdn_lib_get_free_bc (int port, int channel, int inout, int dec)
Definition at line 3205 of file isdn_lib.c.
References ARRAY_LEN, misdn_stack::b_num, bc, misdn_stack::bc, misdn_stack::blocked, cb_log, misdn_bchannel::channel, misdn_bchannel::cw, misdn_bchannel::dec, find_stack_by_port(), if(), MAX_BCHANS, misdn_bchannel::need_disconnect, misdn_bchannel::need_release, NULL, misdn_bchannel::port, prepare_bc(), misdn_stack::pri, pthread_mutex_lock, pthread_mutex_unlock, misdn_stack::ptp, misdn_stack::st_lock, and test_inuse().
Referenced by handle_cr(), handle_event_nt(), and misdn_request().
 {
    struct misdn_stack *stack;
    int i;
    int maxnum;
    if (channel < 0 || channel > MAX_BCHANS) {
       cb_log(0, port, "Requested channel out of bounds (%d)\n", channel);
       return NULL;
    }
    /* Find the port stack structure */
    stack = find_stack_by_port(port);
    if (!stack) {
       cb_log(0, port, "Port is not configured (%d)\n", port);
       return NULL;
    }
    if (stack->blocked) {
       cb_log(0, port, "Port is blocked\n");
       return NULL;
    }
    pthread_mutex_lock(&stack->st_lock);
    if (channel > 0) {
       if (channel <= stack->b_num) {
          for (i = 0; i < stack->b_num; i++) {
             if (stack->bc[i].channel == channel) {
                if (test_inuse(&stack->bc[i])) {
                   pthread_mutex_unlock(&stack->st_lock);
                   cb_log(0, port, "Requested channel:%d on port:%d is already in use\n", channel, port);
                   return NULL;
                } else {
                   prepare_bc(&stack->bc[i], channel);
                   pthread_mutex_unlock(&stack->st_lock);
                   return &stack->bc[i];
                }
             }
          }
       } else {
          pthread_mutex_unlock(&stack->st_lock);
          cb_log(0, port, "Requested channel:%d is out of bounds on port:%d\n", channel, port);
          return NULL;
       }
    }
    /* Note: channel == 0 here */
    maxnum = (inout && !stack->pri && !stack->ptp) ? stack->b_num + 1 : stack->b_num;
    if (dec) {
       for (i = maxnum - 1; i >= 0; --i) {
          if (!test_inuse(&stack->bc[i])) {
             /* 3. channel on bri means CW*/
             if (!stack->pri && i == stack->b_num) {
                stack->bc[i].cw = 1;
             }
             prepare_bc(&stack->bc[i], channel);
             stack->bc[i].dec = 1;
             pthread_mutex_unlock(&stack->st_lock);
             return &stack->bc[i];
          }
       }
    } else {
       for (i = 0; i < maxnum; ++i) {
          if (!test_inuse(&stack->bc[i])) {
             /* 3. channel on bri means CW */
             if (!stack->pri && i == stack->b_num) {
                stack->bc[i].cw = 1;
             }
             prepare_bc(&stack->bc[i], channel);
             pthread_mutex_unlock(&stack->st_lock);
             return &stack->bc[i];
          }
       }
    }
    pthread_mutex_unlock(&stack->st_lock);
    cb_log(1, port, "There is no free channel on port (%d)\n", port);
    return NULL;
 }
misdn_lib_get_l1_down()
static int misdn_lib_get_l1_down (struct misdn_stack * stack) static
Definition at line 876 of file isdn_lib.c.
References cb_log, misdn_stack::midev, misdn_stack::port, and misdn_stack::upper_id.
Referenced by misdn_lib_get_port_down().
 {
    /* Pull Up L1 */
    iframe_t act;
    act.prim = PH_DEACTIVATE | REQUEST;
    act.addr = stack->upper_id | FLG_MSG_DOWN;
    act.dinfo = 0;
    act.len = 0;
    cb_log(1, stack->port, "SENDING PH_DEACTIVATE | REQ\n");
    return mISDN_write(stack->midev, &act, mISDN_HEADER_LEN+act.len, TIMEOUT_1SEC);
 }
misdn_lib_get_l1_up()
static int misdn_lib_get_l1_up (struct misdn_stack * stack) static
Definition at line 918 of file isdn_lib.c.
References cb_log, misdn_stack::midev, misdn_stack::port, and misdn_stack::upper_id.
Referenced by misdn_lib_get_port_up(), misdn_lib_isdn_l1watcher(), misdn_lib_reinit_nt_stack(), misdn_lib_send_event(), and stack_init().
 {
    /* Pull Up L1 */
    iframe_t act;
    act.prim = PH_ACTIVATE | REQUEST;
    act.addr = stack->upper_id | FLG_MSG_DOWN;
    act.dinfo = 0;
    act.len = 0;
    cb_log(1, stack->port, "SENDING PH_ACTIVATE | REQ\n");
    return mISDN_write(stack->midev, &act, mISDN_HEADER_LEN+act.len, TIMEOUT_1SEC);
 }
misdn_lib_get_l2_down()
static int misdn_lib_get_l2_down (struct misdn_stack * stack) static
Definition at line 890 of file isdn_lib.c.
References create_l2msg(), misdn_stack::midev, misdn_stack::nst, misdn_stack::nstlock, misdn_stack::nt, pthread_mutex_lock, pthread_mutex_unlock, misdn_stack::ptp, and misdn_stack::upper_id.
Referenced by misdn_lib_get_port_down().
 {
    if (stack->ptp && stack->nt) {
       msg_t *dmsg;
       /* L2 */
       dmsg = create_l2msg(DL_RELEASE| REQUEST, 0, 0);
       pthread_mutex_lock(&stack->nstlock);
       if (stack->nst.manager_l3(&stack->nst, dmsg))
          free_msg(dmsg);
       pthread_mutex_unlock(&stack->nstlock);
    } else if (!stack->nt) {
       iframe_t act;
       act.prim = DL_RELEASE| REQUEST;
       act.addr = (stack->upper_id |FLG_MSG_DOWN)  ;
       act.dinfo = 0;
       act.len = 0;
       return mISDN_write(stack->midev, &act, mISDN_HEADER_LEN+act.len, TIMEOUT_1SEC);
    }
    /* cannot deestablish L2 for NT PTMP to unknown TE TEIs */
    return 0;
 }
misdn_lib_get_l2_up()
int misdn_lib_get_l2_up (struct misdn_stack * stack)
Definition at line 932 of file isdn_lib.c.
References create_l2msg(), misdn_stack::midev, misdn_stack::nst, misdn_stack::nstlock, misdn_stack::nt, pthread_mutex_lock, pthread_mutex_unlock, misdn_stack::ptp, and misdn_stack::upper_id.
Referenced by handle_event_nt(), handle_l1(), misdn_lib_get_port_up(), misdn_lib_isdn_l1watcher(), and stack_init().
 {
    if (stack->ptp && stack->nt) {
       msg_t *dmsg;
       /* L2 */
       dmsg = create_l2msg(DL_ESTABLISH | REQUEST, 0, 0);
       pthread_mutex_lock(&stack->nstlock);
       if (stack->nst.manager_l3(&stack->nst, dmsg))
          free_msg(dmsg);
       pthread_mutex_unlock(&stack->nstlock);
    } else if (!stack->nt) {
       iframe_t act;
       act.prim = DL_ESTABLISH | REQUEST;
       act.addr = (stack->upper_id |FLG_MSG_DOWN)  ;
       act.dinfo = 0;
       act.len = 0;
       return mISDN_write(stack->midev, &act, mISDN_HEADER_LEN+act.len, TIMEOUT_1SEC);
    }
    /* cannot establish L2 for NT PTMP to unknown TE TEIs */
    return 0;
 }
misdn_lib_get_maxchans()
int misdn_lib_get_maxchans (int port)
Definition at line 137 of file isdn_lib.c.
References get_misdn_stack(), misdn_stack::next, misdn_stack::port, and misdn_stack::pri.
Referenced by misdn_request().
 {
    struct misdn_stack *stack=get_misdn_stack();
    for ( ; stack; stack=stack->next) {
       if (stack->port == port) {
          if (stack->pri)
             return 30;
          else
             return 2;
       }
    }
    return -1;
 }
misdn_lib_get_port_down()
int misdn_lib_get_port_down (int port)
Definition at line 1805 of file isdn_lib.c.
References misdn_stack::l2link, misdn_lib_get_l1_down(), misdn_lib_get_l2_down(), misdn_stack::next, misdn_stack::port, and misdn_lib::stack_list.
Referenced by handle_cli_misdn_port_down().
 { /* Pull Down L1 */
    struct misdn_stack *stack;
    for (stack=glob_mgr->stack_list;
         stack;
         stack=stack->next) {
       if (stack->port == port) {
             if (stack->l2link)
                misdn_lib_get_l2_down(stack);
             misdn_lib_get_l1_down(stack);
          return 0;
       }
    }
    return 0;
 }
misdn_lib_get_port_info()
int misdn_lib_get_port_info (int port)
Definition at line 3903 of file isdn_lib.c.
References misdn_lib::activatequeue, cb_log, find_stack_by_port(), if(), misdn_lib::new_msg, and misdn_stack::upper_id.
 {
    msg_t *msg=alloc_msg(MAX_MSG_SIZE);
    iframe_t *frm;
    struct misdn_stack *stack=find_stack_by_port(port);
    if (!msg) {
       cb_log(0, port, "misdn_lib_get_port_info: alloc_msg failed!\n");
       return -1;
    }
    frm=(iframe_t*)msg->data;
    if (!stack ) {
       cb_log(0, port, "There is no Stack for this port.\n");
       return -1;
    }
    /* activate bchannel */
    frm->prim = CC_STATUS_ENQUIRY | REQUEST;
    frm->addr = stack->upper_id| FLG_MSG_DOWN;
    frm->dinfo = 0;
    frm->len = 0;
    msg_queue_tail(&glob_mgr->activatequeue, msg);
    sem_post(&glob_mgr->new_msg);
    return 0;
 }
misdn_lib_get_port_up()
int misdn_lib_get_port_up (int port)
Definition at line 1781 of file isdn_lib.c.
References misdn_stack::l1link, misdn_stack::l2link, misdn_lib_get_l1_up(), misdn_lib_get_l2_up(), misdn_stack::next, misdn_stack::nt, misdn_stack::port, and misdn_lib::stack_list.
Referenced by handle_cli_misdn_port_up(), and misdn_check_l2l1().
 { /* Pull Up L1 */
    struct misdn_stack *stack;
    for (stack=glob_mgr->stack_list;
         stack;
         stack=stack->next) {
       if (stack->port == port) {
          if (!stack->l1link)
             misdn_lib_get_l1_up(stack);
          /* handle_l1 will start L2 for NT. */
          if (!stack->l2link && !stack->nt) {
             misdn_lib_get_l2_up(stack);
          }
          return 0;
       }
    }
    return 0;
 }
misdn_lib_get_short_status()
static int misdn_lib_get_short_status (struct misdn_stack * stack) static
Definition at line 959 of file isdn_lib.c.
References misdn_stack::midev, and misdn_stack::upper_id.
Referenced by misdn_lib_isdn_l1watcher(), and stack_init().
 {
    iframe_t act;
    act.prim = MGR_SHORTSTATUS | REQUEST;
    act.addr = (stack->upper_id | MSG_BROADCAST)  ;
    act.dinfo = SSTATUS_BROADCAST_BIT | SSTATUS_ALL;
    act.len = 0;
    return mISDN_write(stack->midev, &act, mISDN_HEADER_LEN+act.len, TIMEOUT_1SEC);
 }
misdn_lib_init()
int misdn_lib_init (char * portlist, struct misdn_lib_iface * iface, void * user_data)
Definition at line 4143 of file isdn_lib.c.
References misdn_lib::activatequeue, ARRAY_LEN, misdn_stack::b_num, misdn_stack::bc, calloc, misdn_lib_iface::cb_event, cb_event, cb_jb_empty, misdn_lib_iface::cb_jb_empty, cb_log, misdn_lib_iface::cb_log, misdn_lib::event_handler_thread, misdn_lib::event_thread, flip_buf_bits(), free(), init_bc(), init_flip_bits(), misdn_bchannel::is_register_pool, manager_event_handler(), MAX_BCHANS, misdn_stack::midev, misdn_lib::midev, MISDN_INITIALIZED, misdn_lib_isdn_event_catcher(), misdn_lib_nt_debug_init(), misdn_lib::new_msg, misdn_stack::next, NULL, pthread_create, ptp, stack_destroy(), stack_init(), misdn_lib::stack_list, te_lib_destroy(), and te_lib_init().
Referenced by load_module().
 {
    struct misdn_lib *mgr;
    char *tok, *tokb;
    char plist[1024];
    int midev;
    int port_count=0;
    cb_log = iface->cb_log;
    cb_event = iface->cb_event;
    cb_jb_empty = iface->cb_jb_empty;
    if (!portlist || (*portlist == 0)) {
       return 1;
    }
    mgr = calloc(1, sizeof(*mgr));
    if (!mgr) {
       return 1;
    }
    glob_mgr = mgr;
    msg_init();
    misdn_lib_nt_debug_init(0,NULL);
    init_flip_bits();
    strncpy(plist, portlist, 1024);
    plist[1023] = 0;
    memcpy(tone_425_flip,tone_425,TONE_425_SIZE);
    flip_buf_bits(tone_425_flip,TONE_425_SIZE);
    memcpy(tone_silence_flip,tone_SILENCE,TONE_SILENCE_SIZE);
    flip_buf_bits(tone_silence_flip,TONE_SILENCE_SIZE);
    midev=te_lib_init();
    if (midev <= 0) {
       free(glob_mgr);
       glob_mgr = NULL;
       return 1;
    }
    mgr->midev=midev;
    port_count=mISDN_get_stack_count(midev);
    msg_queue_init(&mgr->activatequeue);
    if (sem_init(&mgr->new_msg, 1, 0)<0)
       sem_init(&mgr->new_msg, 0, 0);
    for (tok=strtok_r(plist," ,",&tokb );
         tok;
         tok=strtok_r(NULL," ,",&tokb)) {
       int port = atoi(tok);
       struct misdn_stack *stack;
       struct misdn_stack *help;
       int ptp=0;
       int i;
       int r;
       if (strstr(tok, "ptp"))
          ptp=1;
       if (port > port_count) {
          cb_log(0, port, "Couldn't Initialize this port since we have only %d ports\n", port_count);
          continue;
       }
       stack = stack_init(midev, port, ptp);
       if (!stack) {
          cb_log(0, port, "stack_init() failed for this port\n");
          continue;
       }
       /* Initialize the B channel records for real B channels. */
       for (i = 0; i <= stack->b_num; i++) {
          r = init_bc(stack, &stack->bc[i], stack->midev, port, i);
          if (r < 0) {
             cb_log(0, port, "Got Err @ init_bc :%d\n", r);
             break;
          }
       }
       if (i <= stack->b_num) {
          stack_destroy(stack);
          free(stack);
          continue;
       }
 #if defined(AST_MISDN_ENHANCEMENTS)
       /* Initialize the B channel records for REGISTER signaling links. */
       for (i = MAX_BCHANS + 1; i < ARRAY_LEN(stack->bc); ++i) {
          r = init_bc(stack, &stack->bc[i], stack->midev, port, i);
          if (r < 0) {
             cb_log(0, port, "Got Err @ init_bc :%d\n", r);
             break;
          }
          stack->bc[i].is_register_pool = 1;
       }
       if (i < ARRAY_LEN(stack->bc)) {
          stack_destroy(stack);
          free(stack);
          continue;
       }
 #endif   /* defined(AST_MISDN_ENHANCEMENTS) */
       /* Add the new stack to the end of the list */
       help = mgr->stack_list;
       if (!help) {
          mgr->stack_list = stack;
       } else {
          while (help->next) {
             help = help->next;
          }
          help->next = stack;
       }
    }
    if (!mgr->stack_list) {
       /* no stacks were successfully initialized !? */
       te_lib_destroy(midev);
       free(glob_mgr);
       glob_mgr = NULL;
       return 1;
    }
    if (sem_init(&handler_started, 1, 0)<0)
       sem_init(&handler_started, 0, 0);
    cb_log(8, 0, "Starting Event Handler\n");
    pthread_create( &mgr->event_handler_thread, NULL,(void*)manager_event_handler, mgr);
    sem_wait(&handler_started) ;
    cb_log(8, 0, "Starting Event Catcher\n");
    pthread_create( &mgr->event_thread, NULL, (void*)misdn_lib_isdn_event_catcher, mgr);
    cb_log(8, 0, "Event Catcher started\n");
    global_state= MISDN_INITIALIZED;
    return (mgr == NULL);
 }
misdn_lib_is_port_blocked()
int misdn_lib_is_port_blocked (int port)
Definition at line 117 of file isdn_lib.c.
References misdn_stack::blocked, get_misdn_stack(), misdn_stack::next, and misdn_stack::port.
 {
    struct misdn_stack *stack=get_misdn_stack();
    for ( ; stack; stack=stack->next) {
       if (stack->port == port) {
          return stack->blocked;
       }
    }
    return -1;
 }
misdn_lib_is_ptp()
int misdn_lib_is_ptp (int port)
Definition at line 128 of file isdn_lib.c.
References get_misdn_stack(), misdn_stack::next, misdn_stack::port, and misdn_stack::ptp.
Referenced by build_setup(), cb_events(), do_immediate_setup(), misdn_call(), misdn_update_connected_line(), and misdn_update_redirecting().
 {
    struct misdn_stack *stack=get_misdn_stack();
    for ( ; stack; stack=stack->next) {
       if (stack->port == port) return stack->ptp;
    }
    return -1;
 }
misdn_lib_isdn_event_catcher()
static void misdn_lib_isdn_event_catcher (void * arg) static
When we make a call from NT2Ast we get these frames
I get this sometimes after setup_bc
Definition at line 3068 of file isdn_lib.c.
References cb_log, fetch_msg(), if(), manager_isdn_handler(), and misdn_lib::midev.
Referenced by misdn_lib_init().
 {
    struct misdn_lib *mgr = arg;
    int zero_frm=0 , fff_frm=0 ;
    int midev= mgr->midev;
    int port=0;
    while (1) {
       msg_t *msg = fetch_msg(midev);
       iframe_t *frm;
       if (!msg) continue;
       frm = (iframe_t*) msg->data;
       /** When we make a call from NT2Ast we get these frames **/
       if (frm->len == 0 && frm->addr == 0 && frm->dinfo == 0 && frm->prim == 0 ) {
          zero_frm++;
          free_msg(msg);
          continue;
       } else {
          if (zero_frm) {
             cb_log(0, port, "*** Alert: %d zero_frms caught\n", zero_frm);
             zero_frm = 0 ;
          }
       }
       /** I get this sometimes after setup_bc **/
       if (frm->len == 0 &&  frm->dinfo == 0 && frm->prim == 0xffffffff ) {
          fff_frm++;
          free_msg(msg);
          continue;
       } else {
          if (fff_frm) {
             cb_log(0, port, "*** Alert: %d fff_frms caught\n", fff_frm);
             fff_frm = 0 ;
          }
       }
       manager_isdn_handler(frm, msg);
    }
 }
misdn_lib_isdn_l1watcher()
void misdn_lib_isdn_l1watcher (int port)
Definition at line 3049 of file isdn_lib.c.
References cb_log, misdn_stack::l1link, misdn_lib_get_l1_up(), misdn_lib_get_l2_up(), misdn_lib_get_short_status(), misdn_stack::next, misdn_stack::port, and misdn_lib::stack_list.
Referenced by misdn_l1_task().
 {
    struct misdn_stack *stack;
    for (stack = glob_mgr->stack_list; stack && (stack->port != port); stack = stack->next)
       ;
    if (stack) {
       cb_log(4, port, "Checking L1 State\n");
       if (!stack->l1link) {
          cb_log(4, port, "L1 State Down, trying to get it up again\n");
          misdn_lib_get_short_status(stack);
          misdn_lib_get_l1_up(stack);
          misdn_lib_get_l2_up(stack);
       }
    }
 }
misdn_lib_log_ies()
void misdn_lib_log_ies (struct misdn_bchannel * bc)
Definition at line 3431 of file isdn_lib.c.
References misdn_bchannel::addr, misdn_bchannel::b_stid, bearer2str(), misdn_bchannel::caller, misdn_bchannel::capability, misdn_bchannel::cause, cb_log, misdn_bchannel::channel, misdn_bchannel::connected, misdn_party_redirecting::count, misdn_bchannel::dialed, fac2str(), misdn_bchannel::fac_in, misdn_bchannel::fac_out, misdn_party_redirecting::from, get_stack_by_bc(), misdn_bchannel::holded, misdn_bchannel::info_dad, misdn_bchannel::keypad, misdn_bchannel::l3_id, misdn_bchannel::layer_id, misdn_bchannel::mode, misdn_party_id::name, misdn_stack::nt, misdn_party_id::number, misdn_party_id::number_plan, misdn_party_dialing::number_plan, misdn_party_id::number_type, misdn_party_dialing::number_type, misdn_bchannel::out_cause, misdn_stack::port, misdn_party_id::presentation, misdn_bchannel::presentation, misdn_bchannel::progress_indicator, misdn_bchannel::rate, misdn_party_redirecting::reason, misdn_bchannel::redirecting, misdn_party_id::screening, misdn_bchannel::sending_complete, misdn_bchannel::set_presentation, misdn_bchannel::stack_holder, misdn_party_redirecting::to, misdn_bchannel::urate, and misdn_bchannel::user1.
Referenced by cb_events(), and misdn_lib_send_event().
 {
    struct misdn_stack *stack;
    if (!bc) return;
    stack = get_stack_by_bc(bc);
    if (!stack) return;
    cb_log(2, stack->port,
       " --> channel:%d mode:%s cause:%d ocause:%d\n",
       bc->channel,
       stack->nt ? "NT" : "TE",
       bc->cause,
       bc->out_cause);
    cb_log(2, stack->port,
       " --> info_dad:%s dialed numtype:%d plan:%d\n",
       bc->info_dad,
       bc->dialed.number_type,
       bc->dialed.number_plan);
    cb_log(2, stack->port,
       " --> caller:\"%s\" <%s> type:%d plan:%d pres:%d screen:%d\n",
       bc->caller.name,
       bc->caller.number,
       bc->caller.number_type,
       bc->caller.number_plan,
       bc->caller.presentation,
       bc->caller.screening);
    cb_log(2, stack->port,
       " --> redirecting-from:\"%s\" <%s> type:%d plan:%d pres:%d screen:%d\n",
       bc->redirecting.from.name,
       bc->redirecting.from.number,
       bc->redirecting.from.number_type,
       bc->redirecting.from.number_plan,
       bc->redirecting.from.presentation,
       bc->redirecting.from.screening);
    cb_log(2, stack->port,
       " --> redirecting-to:\"%s\" <%s> type:%d plan:%d pres:%d screen:%d\n",
       bc->redirecting.to.name,
       bc->redirecting.to.number,
       bc->redirecting.to.number_type,
       bc->redirecting.to.number_plan,
       bc->redirecting.to.presentation,
       bc->redirecting.to.screening);
    cb_log(2, stack->port,
       " --> redirecting reason:%d count:%d\n",
       bc->redirecting.reason,
       bc->redirecting.count);
    cb_log(2, stack->port,
       " --> connected:\"%s\" <%s> type:%d plan:%d pres:%d screen:%d\n",
       bc->connected.name,
       bc->connected.number,
       bc->connected.number_type,
       bc->connected.number_plan,
       bc->connected.presentation,
       bc->connected.screening);
    cb_log(3, stack->port, " --> caps:%s pi:%x keypad:%s sending_complete:%d\n", bearer2str(bc->capability),bc->progress_indicator, bc->keypad, bc->sending_complete);
    cb_log(4, stack->port, " --> set_pres:%d pres:%d\n", bc->set_presentation, bc->presentation);
    cb_log(4, stack->port, " --> addr:%x l3id:%x b_stid:%x layer_id:%x\n", bc->addr, bc->l3_id, bc->b_stid, bc->layer_id);
    cb_log(4, stack->port, " --> facility in:%s out:%s\n", fac2str(bc->fac_in.Function), fac2str(bc->fac_out.Function));
    cb_log(5, stack->port, " --> urate:%d rate:%d mode:%d user1:%d\n", bc->urate, bc->rate, bc->mode,bc->user1);
    cb_log(5, stack->port, " --> bc:%p h:%d sh:%d\n", bc, bc->holded, bc->stack_holder);
 }
misdn_lib_maxports_get()
int misdn_lib_maxports_get (void)
Definition at line 4094 of file isdn_lib.c.
References max.
Referenced by load_module().
 {
    /* BE AWARE WE HAVE NO cb_log() HERE! */
    int i = mISDN_open();
    int max=0;
    if (i<0)
       return -1;
    max = mISDN_get_stack_count(i);
    mISDN_close(i);
    return max;
 }
misdn_lib_nt_debug_init()
void misdn_lib_nt_debug_init (int flags, char * file)
Definition at line 4124 of file isdn_lib.c.
References make_ari_stubs::file, and NULL.
Referenced by load_module(), and misdn_lib_init().
 {
    static int init=0;
    char *f;
    if (!flags)
       f=NULL;
    else
       f=file;
    if (!init) {
       debug_init( flags , f, f, f);
       init=1;
    } else {
       debug_close();
       debug_init( flags , f, f, f);
    }
 }
misdn_lib_nt_keepcalls()
void misdn_lib_nt_keepcalls (int kc)
Definition at line 4112 of file isdn_lib.c.
References get_misdn_stack(), misdn_stack::next, and misdn_stack::nst.
Referenced by load_module().
 {
 #ifdef FEATURE_NET_KEEPCALLS
    if (kc) {
       struct misdn_stack *stack=get_misdn_stack();
       for ( ; stack; stack=stack->next) {
          stack->nst.feature |= FEATURE_NET_KEEPCALLS;
       }
    }
 #endif
 }
misdn_lib_pid_restart()
int misdn_lib_pid_restart (int pid)
Definition at line 3932 of file isdn_lib.c.
References manager_clean_bc(), and manager_find_bc_by_pid().
Referenced by handle_cli_misdn_restart_pid().
 {
    struct misdn_bchannel *bc=manager_find_bc_by_pid(pid);
    if (bc) {
       manager_clean_bc(bc);
    }
    return 0;
 }
misdn_lib_port_block()
int misdn_lib_port_block (int port)
Definition at line 91 of file isdn_lib.c.
References misdn_stack::blocked, get_misdn_stack(), misdn_stack::next, and misdn_stack::port.
Referenced by cb_events(), and handle_cli_misdn_port_block().
 {
    struct misdn_stack *stack=get_misdn_stack();
    for ( ; stack; stack=stack->next) {
       if (stack->port == port) {
          stack->blocked=1;
          return 0;
       }
    }
    return -1;
 }
misdn_lib_port_is_nt()
int misdn_lib_port_is_nt (int port)
Definition at line 65 of file isdn_lib.c.
References get_misdn_stack(), misdn_stack::next, misdn_stack::nt, and misdn_stack::port.
Referenced by handle_cli_misdn_send_facility(), misdn_update_connected_line(), misdn_update_redirecting(), reload(), and wait_for_digits().
 {
    struct misdn_stack *stack=get_misdn_stack();
    for ( ; stack; stack=stack->next) {
       if (stack->port == port) {
          return stack->nt;
       }
    }
    return -1;
 }
misdn_lib_port_is_pri()
int misdn_lib_port_is_pri (int port)
Definition at line 53 of file isdn_lib.c.
References get_misdn_stack(), misdn_stack::next, misdn_stack::port, and misdn_stack::pri.
Referenced by misdn_new(), test_inuse(), and update_name().
 {
    struct misdn_stack *stack=get_misdn_stack();
    for ( ; stack; stack=stack->next) {
       if (stack->port == port) {
          return stack->pri;
       }
    }
    return -1;
 }
misdn_lib_port_restart()
int misdn_lib_port_restart (int port)
Definition at line 3982 of file isdn_lib.c.
References misdn_lib::activatequeue, cb_log, clear_l3(), find_stack_by_port(), misdn_lib_reinit_nt_stack(), misdn_lib::new_msg, misdn_stack::nt, misdn_stack::port, and misdn_stack::upper_id.
Referenced by handle_cli_misdn_restart_port().
 {
    struct misdn_stack *stack=find_stack_by_port(port);
    cb_log(0, port, "Restarting this port.\n");
    if (stack) {
       cb_log(0, port, "Stack:%p\n",stack);
       clear_l3(stack);
       {
          msg_t *msg=alloc_msg(MAX_MSG_SIZE);
          iframe_t *frm;
          if (!msg) {
             cb_log(0, port, "port_restart: alloc_msg failed\n");
             return -1;
          }
          frm=(iframe_t*)msg->data;
          /* we must activate if we are deactivated */
          /* activate bchannel */
          frm->prim = DL_RELEASE | REQUEST;
          frm->addr = stack->upper_id | FLG_MSG_DOWN;
          frm->dinfo = 0;
          frm->len = 0;
          msg_queue_tail(&glob_mgr->activatequeue, msg);
          sem_post(&glob_mgr->new_msg);
       }
       if (stack->nt)
          misdn_lib_reinit_nt_stack(stack->port);
    }
    return 0;
 }
misdn_lib_port_unblock()
int misdn_lib_port_unblock (int port)
Definition at line 104 of file isdn_lib.c.
References misdn_stack::blocked, get_misdn_stack(), misdn_stack::next, and misdn_stack::port.
Referenced by handle_cli_misdn_port_unblock().
 {
    struct misdn_stack *stack=get_misdn_stack();
    for ( ; stack; stack=stack->next) {
       if (stack->port == port) {
          stack->blocked=0;
          return 0;
       }
    }
    return -1;
 }
misdn_lib_port_up()
int misdn_lib_port_up (int port, int check)
Definition at line 1821 of file isdn_lib.c.
References misdn_stack::blocked, cb_log, misdn_stack::l1link, misdn_stack::l2link, misdn_stack::next, misdn_stack::port, misdn_stack::ptp, and misdn_lib::stack_list.
Referenced by misdn_check_l2l1(), and misdn_request().
 {
    struct misdn_stack *stack;
    for (stack=glob_mgr->stack_list;
         stack;
         stack=stack->next) {
       if (stack->port == port) {
          if (stack->blocked) {
             cb_log(0,port, "Port Blocked:%d L2:%d L1:%d\n", stack->blocked, stack->l2link, stack->l1link);
             return -1;
          }
          if (stack->ptp ) {
             if (stack->l1link && stack->l2link) {
                return 1;
             } else {
                cb_log(1,port, "Port Down L2:%d L1:%d\n",
                   stack->l2link, stack->l1link);
                return 0;
             }
          } else {
             if ( !check || stack->l1link )
                return 1;
             else {
                cb_log(1,port, "Port down PMP\n");
                return 0;
             }
          }
       }
    }
    return -1;
 }
misdn_lib_reinit_nt_stack()
void misdn_lib_reinit_nt_stack (int port)
Definition at line 4779 of file isdn_lib.c.
References misdn_stack::blocked, misdn_stack::d_stid, find_stack_by_port(), handle_event_nt(), misdn_stack::l2link, misdn_stack::lower_id, misdn_stack::mgr, misdn_lib::midev, misdn_lib_get_l1_up(), misdn_stack::nst, misdn_stack::port, misdn_stack::pri, misdn_stack::ptp, and misdn_stack::upper_id.
Referenced by misdn_lib_port_restart().
 {
    struct misdn_stack *stack=find_stack_by_port(port);
    if (stack) {
       stack->l2link=0;
       stack->blocked=0;
       cleanup_Isdnl3(&stack->nst);
       cleanup_Isdnl2(&stack->nst);
       memset(&stack->nst, 0, sizeof(net_stack_t));
       memset(&stack->mgr, 0, sizeof(manager_t));
       stack->mgr.nst = &stack->nst;
       stack->nst.manager = &stack->mgr;
       stack->nst.l3_manager = handle_event_nt;
       stack->nst.device = glob_mgr->midev;
       stack->nst.cardnr = port;
       stack->nst.d_stid = stack->d_stid;
       stack->nst.feature = FEATURE_NET_HOLD;
       if (stack->ptp)
          stack->nst.feature |= FEATURE_NET_PTP;
       if (stack->pri)
          stack->nst.feature |= FEATURE_NET_CRLEN2 | FEATURE_NET_EXTCID;
       stack->nst.l1_id = stack->lower_id; /* never used */
       stack->nst.l2_id = stack->upper_id;
       msg_queue_init(&stack->nst.down_queue);
       Isdnl2Init(&stack->nst);
       Isdnl3Init(&stack->nst);
       if (!stack->ptp)
          misdn_lib_get_l1_up(stack);
    }
 }
misdn_lib_release()
void misdn_lib_release (struct misdn_bchannel * bc)
Definition at line 1759 of file isdn_lib.c.
References cb_log, misdn_bchannel::channel, clean_up_bc(), empty_bc(), empty_chan_in_stack(), get_stack_by_bc(), and misdn_bchannel::in_use.
Referenced by misdn_hangup(), and misdn_request().
 {
    int channel;
    struct misdn_stack *stack=get_stack_by_bc(bc);
    if (!stack) {
       cb_log(1,0,"misdn_release: No Stack found\n");
       return;
    }
    channel = bc->channel;
    empty_bc(bc);
    clean_up_bc(bc);
    if (channel > 0) {
       empty_chan_in_stack(stack, channel);
    }
    bc->in_use=0;
 }
misdn_lib_send_event()
int misdn_lib_send_event (struct misdn_bchannel * bc, enum event_e event)
Definition at line 3523 of file isdn_lib.c.
References bc, misdn_bchannel::bc_state, bc_state2str(), bc_state_change(), BCHAN_BRIDGED, BCHAN_CLEANED, misdn_bchannel::caller, misdn_bchannel::capability, misdn_bchannel::cause, cb_log, misdn_bchannel::channel, misdn_bchannel::channel_found, misdn_bchannel::channel_preselected, clean_up_bc(), misdn_bchannel::conf_id, create_process(), misdn_bchannel::crypt_key, misdn_bchannel::dialed, misdn_stack::downqueue, empty_bc(), empty_chan_in_stack(), ENOCHAN, EVENT_ALERTING, EVENT_CONNECT, EVENT_CONNECT_ACKNOWLEDGE, EVENT_DISCONNECT, EVENT_HOLD_ACKNOWLEDGE, EVENT_PROCEEDING, EVENT_PROGRESS, EVENT_REGISTER, EVENT_RELEASE, EVENT_RELEASE_COMPLETE, EVENT_RETRIEVE_ACKNOWLEDGE, EVENT_SETUP, EVENT_SETUP_ACKNOWLEDGE, find_bc_by_confid(), find_free_chan_in_stack(), get_stack_by_bc(), misdn_bchannel::holded, misdn_bchannel::in_use, isdn_get_info(), isdn_msg_build_event(), misdn_stack::l1link, malloc(), manager_ec_enable(), manager_ph_control(), manager_ph_control_block(), misdn_lib::midev, misdn_cap_is_speech(), misdn_lib_get_l1_up(), misdn_lib_log_ies(), misdn_send_lock(), misdn_send_unlock(), misdn_split_conf(), msgs_g, misdn_party_id::name, misdn_bchannel::need_disconnect, misdn_bchannel::need_release, misdn_bchannel::need_release_complete, misdn_lib::new_msg, misdn_bchannel::nodsp, misdn_stack::nt, misdn_bchannel::nt, misdn_party_dialing::number, misdn_party_id::number, misdn_party_id::number_type, misdn_party_dialing::number_type, misdn_bchannel::out_cause, misdn_bchannel::pid, misdn_stack::port, misdn_bchannel::port, misdn_stack::ptp, RETURN, retval, misdn_bchannel::rxgain, setup_bc(), stack_holder_add(), misdn_bchannel::txgain, and misdn_stack::upper_id.
Referenced by cb_events(), do_immediate_setup(), get_chan_by_ast_name(), handle_cli_misdn_send_display(), handle_cli_misdn_send_facility(), handle_event_nt(), handle_event_te(), handle_frm_te(), misdn_answer(), misdn_call(), misdn_digit_end(), misdn_facility_exec(), misdn_facility_ie_handler(), misdn_hangup(), misdn_indication(), misdn_lib_send_restart(), misdn_overlap_dial_task(), misdn_send_text(), misdn_update_connected_line(), misdn_update_redirecting(), reload(), start_pbx(), and wait_for_digits().
 {
    msg_t *msg;
    struct misdn_bchannel *bc2;
    struct misdn_bchannel *held_bc;
    struct misdn_stack *stack;
    int retval = 0;
    int channel;
    int tmpcause;
    int tmp_out_cause;
    if (!bc)
       RETURN(-1,OUT_POST_UNLOCK);
    stack = get_stack_by_bc(bc);
    if (!stack) {
       cb_log(0,bc->port,
          "SENDEVENT: no Stack for event:%s caller:\"%s\" <%s> dialed:%s \n",
          isdn_get_info(msgs_g, event, 0),
          bc->caller.name,
          bc->caller.number,
          bc->dialed.number);
       RETURN(-1,OUT);
    }
    misdn_send_lock(bc);
    cb_log(6,stack->port,"SENDEVENT: stack->nt:%d stack->upperid:%x\n",stack->nt, stack->upper_id);
    if ( stack->nt && !stack->l1link) {
       misdn_lib_get_l1_up(stack);
    }
    cb_log(1, stack->port,
       "I SEND:%s caller:\"%s\" <%s> dialed:%s pid:%d\n",
       isdn_get_info(msgs_g, event, 0),
       bc->caller.name,
       bc->caller.number,
       bc->dialed.number,
       bc->pid);
    cb_log(4, stack->port, " --> bc_state:%s\n",bc_state2str(bc->bc_state));
    misdn_lib_log_ies(bc);
    switch (event) {
    case EVENT_REGISTER:
    case EVENT_SETUP:
       if (create_process(glob_mgr->midev, bc) < 0) {
          cb_log(0, stack->port, " No free channel at the moment @ send_event\n");
          RETURN(-ENOCHAN,OUT);
       }
       break;
    case EVENT_PROGRESS:
    case EVENT_ALERTING:
    case EVENT_PROCEEDING:
    case EVENT_SETUP_ACKNOWLEDGE:
    case EVENT_CONNECT:
       if (!stack->nt) {
          if (stack->ptp) {
             setup_bc(bc);
          }
          break;
       }
       /* fall through */
    case EVENT_RETRIEVE_ACKNOWLEDGE:
       if (stack->nt) {
          if (bc->channel <=0 ) { /*  else we have the channel already */
             if (find_free_chan_in_stack(stack, bc, 0, 0)<0) {
                cb_log(0, stack->port, " No free channel at the moment\n");
                /*FIXME: add disconnect*/
                RETURN(-ENOCHAN,OUT);
             }
          }
          /* Its that i generate channels */
       }
       retval=setup_bc(bc);
       if (retval == -EINVAL) {
          cb_log(0,bc->port,"send_event: setup_bc failed\n");
       }
       if (misdn_cap_is_speech(bc->capability)) {
          if ((event==EVENT_CONNECT)||(event==EVENT_RETRIEVE_ACKNOWLEDGE)) {
             if ( *bc->crypt_key ) {
                cb_log(4, stack->port,
                   " --> ENABLING BLOWFISH channel:%d caller%d:\"%s\" <%s> dialed%d:%s\n",
                   bc->channel,
                   bc->caller.number_type,
                   bc->caller.name,
                   bc->caller.number,
                   bc->dialed.number_type,
                   bc->dialed.number);
                manager_ph_control_block(bc,  BF_ENABLE_KEY, bc->crypt_key, strlen(bc->crypt_key) );
             }
             if (!bc->nodsp) manager_ph_control(bc,  DTMF_TONE_START, 0);
             manager_ec_enable(bc);
             if (bc->txgain != 0) {
                cb_log(4, stack->port,  "--> Changing txgain to %d\n", bc->txgain);
                manager_ph_control(bc, VOL_CHANGE_TX, bc->txgain);
             }
             if ( bc->rxgain != 0 ) {
                cb_log(4, stack->port,  "--> Changing rxgain to %d\n", bc->rxgain);
                manager_ph_control(bc, VOL_CHANGE_RX, bc->rxgain);
             }
          }
       }
       break;
    case EVENT_HOLD_ACKNOWLEDGE:
       held_bc = malloc(sizeof(struct misdn_bchannel));
       if (!held_bc) {
          cb_log(0, bc->port, "Could not allocate held_bc!!!\n");
          RETURN(-1,OUT);
       }
       /* backup the bc and put it in storage */
       *held_bc = *bc;
       held_bc->holded = 1;
       held_bc->channel = 0;/* A held call does not have a channel anymore. */
       held_bc->channel_preselected = 0;
       held_bc->channel_found = 0;
       bc_state_change(held_bc, BCHAN_CLEANED);
       stack_holder_add(stack, held_bc);
       /* kill the bridge and clean the real b-channel record */
       if (stack->nt) {
          if (bc->bc_state == BCHAN_BRIDGED) {
             misdn_split_conf(bc,bc->conf_id);
             bc2 = find_bc_by_confid(bc->conf_id);
             if (!bc2) {
                cb_log(0,bc->port,"We have no second bc in bridge???\n");
             } else {
                misdn_split_conf(bc2,bc->conf_id);
             }
          }
          channel = bc->channel;
          empty_bc(bc);
          clean_up_bc(bc);
          if (channel>0)
             empty_chan_in_stack(stack,channel);
          bc->in_use=0;
       }
       break;
    /* finishing the channel eh ? */
    case EVENT_DISCONNECT:
       if (!bc->need_disconnect) {
          cb_log(0, bc->port, " --> we have already sent DISCONNECT\n");
          RETURN(-1,OUT);
       }
       /* IE cause is mandatory for DISCONNECT, but optional for the answers to DISCONNECT.
        * We must initialize cause, so it is later correctly indicated to ast_channel
        * in case the answer does not include one!
        */
       bc->cause = bc->out_cause;
       bc->need_disconnect=0;
       break;
    case EVENT_RELEASE:
       if (!bc->need_release) {
          cb_log(0, bc->port, " --> we have already sent RELEASE\n");
          RETURN(-1,OUT);
       }
       bc->need_disconnect=0;
       bc->need_release=0;
       break;
    case EVENT_RELEASE_COMPLETE:
       if (!bc->need_release_complete) {
          cb_log(0, bc->port, " --> we have already sent RELEASE_COMPLETE\n");
          RETURN(-1,OUT);
       }
       bc->need_disconnect=0;
       bc->need_release=0;
       bc->need_release_complete=0;
       if (!stack->nt) {
          /* create cleanup in TE */
          channel = bc->channel;
          tmpcause = bc->cause;
          tmp_out_cause = bc->out_cause;
          empty_bc(bc);
          bc->cause=tmpcause;
          bc->out_cause=tmp_out_cause;
          clean_up_bc(bc);
          if (channel>0)
             empty_chan_in_stack(stack,channel);
          bc->in_use=0;
       }
       break;
    case EVENT_CONNECT_ACKNOWLEDGE:
       if ( bc->nt || misdn_cap_is_speech(bc->capability)) {
          int retval=setup_bc(bc);
          if (retval == -EINVAL){
             cb_log(0,bc->port,"send_event: setup_bc failed\n");
          }
       }
       if (misdn_cap_is_speech(bc->capability)) {
          if (  !bc->nodsp) manager_ph_control(bc,  DTMF_TONE_START, 0);
          manager_ec_enable(bc);
          if ( bc->txgain != 0 ) {
             cb_log(4, stack->port, "--> Changing txgain to %d\n", bc->txgain);
             manager_ph_control(bc, VOL_CHANGE_TX, bc->txgain);
          }
          if ( bc->rxgain != 0 ) {
             cb_log(4, stack->port, "--> Changing rxgain to %d\n", bc->rxgain);
             manager_ph_control(bc, VOL_CHANGE_RX, bc->rxgain);
          }
       }
       break;
    default:
       break;
    }
    /* Later we should think about sending bchannel data directly to misdn. */
    msg = isdn_msg_build_event(msgs_g, bc, event, stack->nt);
    if (!msg) {
       /*
        * The message was not built.
        *
        * NOTE:  The only time that the message will fail to build
        * is because the requested FACILITY message is not supported.
        * A failed malloc() results in exit() being called.
        */
       RETURN(-1, OUT);
    } else {
       msg_queue_tail(&stack->downqueue, msg);
       sem_post(&glob_mgr->new_msg);
    }
 OUT:
    misdn_send_unlock(bc);
 OUT_POST_UNLOCK:
    return retval;
 }
misdn_lib_send_restart()
int misdn_lib_send_restart (int port, int channel)
Definition at line 3943 of file isdn_lib.c.
References misdn_stack::b_num, misdn_stack::bc, cb_log, misdn_bchannel::channel, clean_up_bc(), empty_bc(), EVENT_RESTART, find_stack_by_port(), misdn_bchannel::in_use, misdn_lib_send_event(), misdn_make_dummy(), misdn_stack::nt, and misdn_stack::port.
Referenced by handle_cli_misdn_send_restart(), handle_event_nt(), and handle_frm_te().
 {
    struct misdn_stack *stack=find_stack_by_port(port);
    struct misdn_bchannel dummybc;
    /*default is all channels*/
    cb_log(0, port, "Sending Restarts on this port.\n");
    misdn_make_dummy(&dummybc, stack->port, MISDN_ID_GLOBAL, stack->nt, 0);
    /*default is all channels*/
    if (channel <0) {
       dummybc.channel=-1;
       cb_log(0, port, "Restarting and all Interfaces\n");
       misdn_lib_send_event(&dummybc, EVENT_RESTART);
       return 0;
    }
    /*if a channel is specified we restart only this one*/
    if (channel >0) {
       int cnt;
       dummybc.channel=channel;
       cb_log(0, port, "Restarting and cleaning channel %d\n",channel);
       misdn_lib_send_event(&dummybc, EVENT_RESTART);
       /* clean up chan in stack, to be sure we don't think it's
        * in use anymore */
       for (cnt=0; cnt<=stack->b_num; cnt++) {
          if (stack->bc[cnt].in_use && stack->bc[cnt].channel == channel) {
             empty_bc(&stack->bc[cnt]);
             clean_up_bc(&stack->bc[cnt]);
             stack->bc[cnt].in_use=0;
          }
       }
    }
    return 0;
 }
misdn_lib_send_tone()
void misdn_lib_send_tone (struct misdn_bchannel * bc, enum tone_e tone)
Definition at line 4596 of file isdn_lib.c.
References misdn_bchannel::addr, buf, manager_ph_control(), misdn_lib::midev, TONE_ALERTING, TONE_DIAL, TONE_HANGUP, and TONE_NONE.
Referenced by hanguptone_indicate().
 {
    char buf[mISDN_HEADER_LEN + 128] = "";
    iframe_t *frm = (iframe_t*)buf;
    switch(tone) {
    case TONE_DIAL:
       manager_ph_control(bc, TONE_PATT_ON, TONE_GERMAN_DIALTONE);
    break;
    case TONE_ALERTING:
       manager_ph_control(bc, TONE_PATT_ON, TONE_GERMAN_RINGING);
    break;
    case TONE_HANGUP:
       manager_ph_control(bc, TONE_PATT_ON, TONE_GERMAN_HANGUP);
    break;
    case TONE_NONE:
    default:
       manager_ph_control(bc, TONE_PATT_OFF, TONE_GERMAN_HANGUP);
    }
    frm->prim=DL_DATA|REQUEST;
    frm->addr=bc->addr|FLG_MSG_DOWN;
    frm->dinfo=0;
    frm->len=128;
    mISDN_write(glob_mgr->midev, frm, mISDN_HEADER_LEN+frm->len, TIMEOUT_1SEC);
 }
misdn_lib_split_bridge()
void misdn_lib_split_bridge (struct misdn_bchannel * bc1, struct misdn_bchannel * bc2)
Definition at line 4751 of file isdn_lib.c.
References bc, bc_state2str(), BCHAN_BRIDGED, cb_log, misdn_bchannel::conf_id, misdn_split_conf(), and NULL.
Referenced by misdn_write().
 {
    struct misdn_bchannel *bc_list[]={
       bc1,bc2,NULL
    };
    struct misdn_bchannel **bc;
    for (bc=bc_list; *bc;  bc++) {
       if ( (*bc)->bc_state == BCHAN_BRIDGED){
          misdn_split_conf( *bc, (*bc)->conf_id);
       } else {
          cb_log( 2, (*bc)->port, "BC not bridged (state:%s) so not splitting it\n",bc_state2str((*bc)->bc_state));
       }
    }
 }
misdn_lib_tone_generator_start()
void misdn_lib_tone_generator_start (struct misdn_bchannel * bc)
Definition at line 2271 of file isdn_lib.c.
References misdn_bchannel::generate_tone.
Referenced by misdn_write().
 {
    bc->generate_tone=1;
 }
misdn_lib_tone_generator_stop()
void misdn_lib_tone_generator_stop (struct misdn_bchannel * bc)
Definition at line 2276 of file isdn_lib.c.
References misdn_bchannel::generate_tone.
Referenced by start_bc_tones(), and stop_indicate().
 {
    bc->generate_tone=0;
 }
misdn_lib_tx2misdn_frm()
int misdn_lib_tx2misdn_frm (struct misdn_bchannel * bc, void * data, int len)
Definition at line 4382 of file isdn_lib.c.
References misdn_bchannel::addr, misdn_bchannel::bc_state, bc_state2str(), BCHAN_ACTIVATED, BCHAN_BRIDGED, buf, misdn_bchannel::capability, cb_log, flip_buf_bits(), get_stack_by_bc(), len(), misdn_stack::midev, misdn_cap_is_speech(), misdn_stack::port, and misdn_bchannel::port.
Referenced by misdn_join_conf(), and misdn_write().
 {
    struct misdn_stack *stack=get_stack_by_bc(bc);
    char buf[4096 + mISDN_HEADER_LEN];
    iframe_t *frm = (iframe_t*)buf;
    switch (bc->bc_state) {
       case BCHAN_ACTIVATED:
       case BCHAN_BRIDGED:
          break;
       default:
          cb_log(3, bc->port, "BC not yet activated (state:%s)\n",bc_state2str(bc->bc_state));
          return -1;
    }
    frm->prim = DL_DATA|REQUEST;
    frm->dinfo = 0;
    frm->addr = bc->addr | FLG_MSG_DOWN ;
    frm->len = len;
    memcpy(&buf[mISDN_HEADER_LEN], data,len);
    if ( misdn_cap_is_speech(bc->capability) )
       flip_buf_bits( &buf[mISDN_HEADER_LEN], len);
    else
       cb_log(6, stack->port, "Writing %d data bytes\n",len);
    cb_log(9, stack->port, "Writing %d bytes 2 mISDN\n",len);
    mISDN_write(stack->midev, buf, frm->len + mISDN_HEADER_LEN, TIMEOUT_INFINIT);
    return 0;
 }
misdn_make_dummy()
void misdn_make_dummy (struct misdn_bchannel * dummybc, int port, int l3id, int nt, int channel)
Definition at line 77 of file isdn_lib.c.
References misdn_bchannel::channel, misdn_bchannel::dummy, misdn_bchannel::l3_id, misdn_stack::nt, misdn_bchannel::nt, misdn_stack::port, and misdn_bchannel::port.
Referenced by handle_cli_misdn_send_facility(), handle_cr(), handle_event_nt(), handle_frm_te(), manager_event_handler(), misdn_lib_send_restart(), release_cr(), reload(), and wait_for_digits().
 {
    memset (dummybc,0,sizeof(struct misdn_bchannel));
    dummybc->port=port;
    if (l3id==0)
       dummybc->l3_id = MISDN_ID_DUMMY;
    else
       dummybc->l3_id=l3id;
    dummybc->nt=nt;
    dummybc->dummy=1;
    dummybc->channel=channel;
 }
misdn_send_lock()
static void misdn_send_lock (struct misdn_bchannel * bc) static
Definition at line 3509 of file isdn_lib.c.
References send_lock::lock, pthread_mutex_lock, and misdn_bchannel::send_lock.
Referenced by misdn_lib_send_event().
 {
    //cb_log(0,bc->port,"Locking bc->pid:%d\n", bc->pid);
    if (bc->send_lock)
       pthread_mutex_lock(&bc->send_lock->lock);
 }
misdn_send_unlock()
static void misdn_send_unlock (struct misdn_bchannel * bc) static
Definition at line 3516 of file isdn_lib.c.
References send_lock::lock, pthread_mutex_unlock, and misdn_bchannel::send_lock.
Referenced by misdn_lib_send_event().
 {
    //cb_log(0,bc->port,"UnLocking bc->pid:%d\n", bc->pid);
    if (bc->send_lock)
       pthread_mutex_unlock(&bc->send_lock->lock);
 }
misdn_split_conf()
void misdn_split_conf (struct misdn_bchannel * bc, int conf_id)
Definition at line 4719 of file isdn_lib.c.
References misdn_bchannel::addr, bc_state_change(), BCHAN_ACTIVATED, cb_log, manager_ph_control(), and misdn_bchannel::port.
Referenced by manager_bchannel_deactivate(), misdn_lib_send_event(), and misdn_lib_split_bridge().
 {
    bc_state_change(bc,BCHAN_ACTIVATED);
    manager_ph_control(bc, CMX_RECEIVE_ON, 0);
    manager_ph_control(bc, CMX_CONF_SPLIT, conf_id);
    cb_log(4,bc->port, "Splitting bc:%x in conf:%d\n",bc->addr,conf_id);
 }
misdn_tx_jitter()
void misdn_tx_jitter (struct misdn_bchannel * bc, int len)
Definition at line 2330 of file isdn_lib.c.
References misdn_bchannel::addr, misdn_bchannel::bframe, misdn_bchannel::bframe_len, buf, cb_jb_empty, cb_log, misdn_bchannel::channel, errno, flip_buf_bits(), len(), misdn_lib::midev, and misdn_bchannel::port.
Referenced by do_tone(), and handle_bchan().
 {
    char buf[4096 + mISDN_HEADER_LEN];
    char *data=&buf[mISDN_HEADER_LEN];
    iframe_t *txfrm= (iframe_t*)buf;
    int jlen, r;
    jlen=cb_jb_empty(bc,data,len);
    if (jlen) {
 #ifdef MISDN_SAVE_DATA
       misdn_save_data((bc->port*100+bc->channel), data, jlen, bc->bframe, bc->bframe_len);
 #endif
       flip_buf_bits( data, jlen);
       if (jlen < len) {
          cb_log(1, bc->port, "Jitterbuffer Underrun. Got %d of expected %d\n", jlen, len);
       }
       txfrm->prim = DL_DATA|REQUEST;
       txfrm->dinfo = 0;
       txfrm->addr = bc->addr|FLG_MSG_DOWN; /*  | IF_DOWN; */
       txfrm->len =jlen;
       cb_log(9, bc->port, "Transmitting %d samples 2 misdn\n", txfrm->len);
       r=mISDN_write( glob_mgr->midev, buf, txfrm->len + mISDN_HEADER_LEN, 8000 );
    } else {
 #define MISDN_GEN_SILENCE
 #ifdef MISDN_GEN_SILENCE
       int cnt=len/TONE_SILENCE_SIZE;
       int rest=len%TONE_SILENCE_SIZE;
       int i;
       for (i=0; i<cnt; i++) {
          memcpy(data, tone_silence_flip, TONE_SILENCE_SIZE );
          data +=TONE_SILENCE_SIZE;
       }
       if (rest) {
          memcpy(data, tone_silence_flip, rest);
       }
       txfrm->prim = DL_DATA|REQUEST;
       txfrm->dinfo = 0;
       txfrm->addr = bc->addr|FLG_MSG_DOWN; /*  | IF_DOWN; */
       txfrm->len =len;
       cb_log(5, bc->port, "Transmitting %d samples of silence to misdn\n", len);
       r=mISDN_write( glob_mgr->midev, buf, txfrm->len + mISDN_HEADER_LEN, 8000 );
 #else
       r = 0;
 #endif
    }
    if (r < 0) {
       cb_log(1, bc->port, "Error in mISDN_write (%s)\n", strerror(errno));
    }
 }
prepare_bc()
static void prepare_bc (struct misdn_bchannel * bc, int channel) static
Definition at line 3190 of file isdn_lib.c.
References AST_CAUSE_NORMAL_CLEARING, misdn_bchannel::cause, misdn_bchannel::channel, misdn_bchannel::channel_preselected, misdn_bchannel::in_use, mypid, misdn_bchannel::need_disconnect, misdn_bchannel::need_release, misdn_bchannel::need_release_complete, and misdn_bchannel::pid.
Referenced by misdn_lib_get_free_bc().
 {
    bc->channel = channel;
    bc->channel_preselected = channel?1:0;
    bc->need_disconnect=1;
    bc->need_release=1;
    bc->need_release_complete=1;
    bc->cause = AST_CAUSE_NORMAL_CLEARING;
    if (++mypid>5000) mypid=1;
    bc->pid=mypid;
    bc->in_use = 1;
 }
release_cr()
static int release_cr (struct misdn_stack * stack, mISDNuser_head_t * hh) static
removing procid
Definition at line 1861 of file isdn_lib.c.
References misdn_bchannel::addr, cb_log, find_bc_by_l3id(), handle_cr(), misdn_bchannel::l3_id, misdn_make_dummy(), misdn_stack::nt, misdn_stack::port, misdn_stack::procids, and misdn_stack::upper_id.
Referenced by handle_event_nt().
 {
    struct misdn_bchannel *bc=find_bc_by_l3id(stack, hh->dinfo);
    struct misdn_bchannel dummybc;
    iframe_t frm; /* fake te frm to remove callref from global callreflist */
    frm.dinfo = hh->dinfo;
    frm.addr=stack->upper_id | FLG_MSG_DOWN;
    frm.prim = CC_RELEASE_CR|INDICATION;
    cb_log(4, stack->port, " --> CC_RELEASE_CR: Faking Release_cr for %x l3id:%x\n",frm.addr, frm.dinfo);
    /** removing procid **/
    if (!bc) {
       cb_log(4, stack->port, " --> Didn't find BC so temporarily creating dummy BC (l3id:%x) on this port.\n", hh->dinfo);
       misdn_make_dummy(&dummybc, stack->port, hh->dinfo, stack->nt, 0);
       bc=&dummybc;
    }
    if ((bc->l3_id & 0xff00) == 0xff00) {
       cb_log(4, stack->port, " --> Removing Process Id:%x on this port.\n", bc->l3_id & 0xff);
       stack->procids[bc->l3_id & 0xff] = 0;
    }
    if (handle_cr(stack, &frm)<0) {
    }
    return 0 ;
 }
send_msg()
static int send_msg (int midev, struct misdn_bchannel * bc, msg_t * dmsg) static
Definition at line 410 of file isdn_lib.c.
References cb_log, get_stack_by_bc(), misdn_bchannel::l3_id, and misdn_bchannel::port.
Referenced by manager_event_handler().
 {
    iframe_t *frm = (iframe_t *)dmsg->data;
    struct misdn_stack *stack=get_stack_by_bc(bc);
    if (!stack) {
       cb_log(0,bc->port,"send_msg: IEK!! no stack\n ");
       return -1;
    }
    frm->addr = (stack->upper_id | FLG_MSG_DOWN);
    frm->dinfo = bc->l3_id;
    frm->len = (dmsg->len) - mISDN_HEADER_LEN;
    cb_log(4,stack->port,"Sending msg, prim:%x addr:%x dinfo:%x\n",frm->prim,frm->addr,frm->dinfo);
    mISDN_write(midev, dmsg->data, dmsg->len, TIMEOUT_1SEC);
    free_msg(dmsg);
    return 0;
 }
set_chan_in_stack()
static int set_chan_in_stack (struct misdn_stack * stack, int channel) static
Definition at line 492 of file isdn_lib.c.
References ARRAY_LEN, cb_log, misdn_stack::channels, dump_chan_list(), and misdn_stack::port.
Referenced by find_free_chan_in_stack().
 {
    cb_log(4,stack->port,"set_chan_in_stack: %d\n",channel);
    dump_chan_list(stack);
    if (1 <= channel && channel <= ARRAY_LEN(stack->channels)) {
       if (!stack->channels[channel-1])
          stack->channels[channel-1] = 1;
       else {
          cb_log(4,stack->port,"channel already in use:%d\n", channel );
          return -1;
       }
    } else {
       cb_log(0,stack->port,"couldn't set channel %d in\n", channel );
       return -1;
    }
    return 0;
 }
setup_bc()
static int setup_bc (struct misdn_bchannel * bc) static
Definition at line 1038 of file isdn_lib.c.
References misdn_bchannel::addr, misdn_stack::b_num, misdn_bchannel::b_stid, misdn_stack::b_stids, misdn_stack::bc, misdn_bchannel::bc_state, bc_state2str(), bc_state_change(), BCHAN_ACTIVATED, BCHAN_CLEANED, BCHAN_ERROR, buff, cb_event, cb_log, misdn_bchannel::channel, errno, EVENT_BCHAN_ERROR, get_stack_by_bc(), misdn_bchannel::hdlc, ISDN_PID_L3_B_USER, ISDN_PID_L4_B_USER, misdn_bchannel::layer, misdn_bchannel::layer_id, manager_bchannel_activate(), misdn_stack::midev, misdn_lib::midev, misdn_bchannel::nodsp, NULL, misdn_stack::port, misdn_bchannel::port, and misdn_lib::user_data.
Referenced by handle_event_te(), and misdn_lib_send_event().
 {
    unsigned char buff[1025];
    int midev;
    int channel;
    int b_stid;
    int i;
    mISDN_pid_t pid;
    int ret;
    struct misdn_stack *stack=get_stack_by_bc(bc);
    if (!stack) {
       cb_log(0, bc->port, "setup_bc: NO STACK FOUND!!\n");
       return -1;
    }
    midev = stack->midev;
    channel = bc->channel - 1 - (bc->channel > 16);
    b_stid = stack->b_stids[channel >= 0 ? channel : 0];
    switch (bc->bc_state) {
       case BCHAN_CLEANED:
          break;
       default:
          cb_log(4, stack->port, "$$$ bc already setup stid :%x (state:%s)\n", b_stid, bc_state2str(bc->bc_state) );
          return -1;
    }
    cb_log(5, stack->port, "$$$ Setting up bc with stid :%x\n", b_stid);
    /*check if the b_stid is already initialized*/
    for (i=0; i <= stack->b_num; i++) {
       if (stack->bc[i].b_stid == b_stid) {
          cb_log(0, bc->port, "setup_bc: b_stid:%x already in use !!!\n", b_stid);
          return -1;
       }
    }
    if (b_stid <= 0) {
       cb_log(0, stack->port," -- Stid <=0 at the moment in channel:%d\n",channel);
       bc_state_change(bc,BCHAN_ERROR);
       return 1;
    }
    bc->b_stid = b_stid;
    {
       layer_info_t li;
       memset(&li, 0, sizeof(li));
       li.object_id = -1;
       li.extentions = 0;
       li.st = bc->b_stid; /*  given idx */
 #define MISDN_DSP
 #ifndef MISDN_DSP
       bc->nodsp=1;
 #endif
       if ( bc->hdlc || bc->nodsp) {
          cb_log(4, stack->port,"setup_bc: without dsp\n");
          {
             int l = sizeof(li.name);
             strncpy(li.name, "B L3", l);
             li.name[l-1] = 0;
          }
          li.pid.layermask = ISDN_LAYER((3));
          li.pid.protocol[3] = ISDN_PID_L3_B_USER;
          bc->layer=3;
       } else {
          cb_log(4, stack->port,"setup_bc: with dsp\n");
          {
             int l = sizeof(li.name);
             strncpy(li.name, "B L4", l);
             li.name[l-1] = 0;
          }
          li.pid.layermask = ISDN_LAYER((4));
          li.pid.protocol[4] = ISDN_PID_L4_B_USER;
          bc->layer=4;
       }
       ret = mISDN_new_layer(midev, &li);
       if (ret ) {
          cb_log(0, stack->port,"New Layer Err: %d %s\n",ret,strerror(errno));
          bc_state_change(bc,BCHAN_ERROR);
          return(-EINVAL);
       }
       bc->layer_id = li.id;
    }
    memset(&pid, 0, sizeof(pid));
    cb_log(4, stack->port," --> Channel is %d\n", bc->channel);
    if (bc->nodsp && !bc->hdlc) {
       cb_log(2, stack->port," --> TRANSPARENT Mode (no DSP, no HDLC)\n");
       pid.protocol[1] = ISDN_PID_L1_B_64TRANS;
       pid.protocol[2] = ISDN_PID_L2_B_TRANS;
       pid.protocol[3] = ISDN_PID_L3_B_USER;
       pid.layermask = ISDN_LAYER((1)) | ISDN_LAYER((2)) | ISDN_LAYER((3));
    } else if ( bc->hdlc ) {
       cb_log(2, stack->port," --> HDLC Mode\n");
       pid.protocol[1] = ISDN_PID_L1_B_64HDLC ;
       pid.protocol[2] = ISDN_PID_L2_B_TRANS  ;
       pid.protocol[3] = ISDN_PID_L3_B_USER;
       pid.layermask = ISDN_LAYER((1)) | ISDN_LAYER((2)) | ISDN_LAYER((3)) ;
    } else {
       cb_log(2, stack->port," --> TRANSPARENT Mode\n");
       pid.protocol[1] = ISDN_PID_L1_B_64TRANS;
       pid.protocol[2] = ISDN_PID_L2_B_TRANS;
       pid.protocol[3] = ISDN_PID_L3_B_DSP;
       pid.protocol[4] = ISDN_PID_L4_B_USER;
       pid.layermask = ISDN_LAYER((1)) | ISDN_LAYER((2)) | ISDN_LAYER((3)) | ISDN_LAYER((4));
    }
    ret = mISDN_set_stack(midev, bc->b_stid, &pid);
    if (ret){
       cb_log(0, stack->port,"$$$ Set Stack Err: %d %s\n",ret,strerror(errno));
       mISDN_write_frame(midev, buff, bc->layer_id, MGR_DELLAYER | REQUEST, 0, 0, NULL, TIMEOUT_1SEC);
       bc_state_change(bc,BCHAN_ERROR);
       cb_event(EVENT_BCHAN_ERROR, bc, glob_mgr->user_data);
       return(-EINVAL);
    }
    ret = mISDN_get_setstack_ind(midev, bc->layer_id);
    if (ret) {
       cb_log(0, stack->port,"$$$ Set StackIND Err: %d %s\n",ret,strerror(errno));
       mISDN_write_frame(midev, buff, bc->layer_id, MGR_DELLAYER | REQUEST, 0, 0, NULL, TIMEOUT_1SEC);
       bc_state_change(bc,BCHAN_ERROR);
       cb_event(EVENT_BCHAN_ERROR, bc, glob_mgr->user_data);
       return(-EINVAL);
    }
    ret = mISDN_get_layerid(midev, bc->b_stid, bc->layer) ;
    bc->addr = ret>0? ret : 0;
    if (!bc->addr) {
       cb_log(0, stack->port,"$$$ Get Layerid Err: %d %s\n",ret,strerror(errno));
       mISDN_write_frame(midev, buff, bc->layer_id, MGR_DELLAYER | REQUEST, 0, 0, NULL, TIMEOUT_1SEC);
       bc_state_change(bc,BCHAN_ERROR);
       cb_event(EVENT_BCHAN_ERROR, bc, glob_mgr->user_data);
       return (-EINVAL);
    }
    manager_bchannel_activate(bc);
    bc_state_change(bc,BCHAN_ACTIVATED);
    return 0;
 }
stack_destroy()
static void stack_destroy (struct misdn_stack * stack) static
Definition at line 1454 of file isdn_lib.c.
References buf, misdn_stack::midev, misdn_stack::nst, misdn_stack::nstlock, misdn_stack::nt, NULL, pthread_mutex_destroy, misdn_stack::st_lock, and misdn_stack::upper_id.
Referenced by misdn_lib_destroy(), and misdn_lib_init().
 {
    char buf[1024];
    if (!stack) return;
    if (stack->nt) {
       pthread_mutex_destroy(&stack->nstlock);
       cleanup_Isdnl2(&stack->nst);
       cleanup_Isdnl3(&stack->nst);
    }
    if (stack->upper_id)
       mISDN_write_frame(stack->midev, buf, stack->upper_id, MGR_DELLAYER | REQUEST, 0, 0, NULL, TIMEOUT_1SEC);
    pthread_mutex_destroy(&stack->st_lock);
 }
stack_holder_add()
void stack_holder_add (struct misdn_stack * stack, struct misdn_bchannel * holder)
Definition at line 4503 of file isdn_lib.c.
References cb_log, misdn_stack::holding, misdn_bchannel::l3_id, misdn_bchannel::next, NULL, misdn_stack::port, and misdn_bchannel::stack_holder.
Referenced by misdn_lib_send_event().
 {
    struct misdn_bchannel *help;
    cb_log(4,stack->port, "*HOLDER: add %x\n",holder->l3_id);
    holder->stack_holder=1;
    holder->next=NULL;
    if (!stack->holding) {
       stack->holding = holder;
       return;
    }
    for (help=stack->holding;
         help;
         help=help->next) {
       if (!help->next) {
          help->next=holder;
          break;
       }
    }
 }
stack_holder_find()
struct misdn_bchannel * stack_holder_find (struct misdn_stack * stack, unsigned long l3id)
Definition at line 4553 of file isdn_lib.c.
References cb_log, misdn_stack::holding, misdn_bchannel::l3_id, misdn_bchannel::next, NULL, and misdn_stack::port.
Referenced by find_bc_by_l3id(), find_bc_by_masked_l3id(), handle_event_nt(), and misdn_lib_find_held_bc().
 {
    struct misdn_bchannel *help;
    cb_log(4, stack->port, "*HOLDER: find %lx\n",l3id);
    for (help=stack->holding;
         help;
         help=help->next) {
       if (help->l3_id == l3id) {
          cb_log(4,stack->port, "*HOLDER: found bc\n");
          return help;
       }
    }
    cb_log(4,stack->port, "*HOLDER: find nothing\n");
    return NULL;
 }
stack_holder_remove()
void stack_holder_remove (struct misdn_stack * stack, struct misdn_bchannel * holder)
Definition at line 4527 of file isdn_lib.c.
References cb_log, misdn_stack::holding, misdn_bchannel::l3_id, misdn_bchannel::next, misdn_stack::port, and misdn_bchannel::stack_holder.
Referenced by handle_cr(), and handle_event_nt().
 {
    struct misdn_bchannel *h1;
    if (!holder->stack_holder) return;
    holder->stack_holder=0;
    cb_log(4,stack->port, "*HOLDER: remove %x\n",holder->l3_id);
    if (!stack || ! stack->holding) return;
    if (holder == stack->holding) {
       stack->holding = stack->holding->next;
       return;
    }
    for (h1=stack->holding;
         h1;
         h1=h1->next) {
       if (h1->next == holder) {
          h1->next=h1->next->next;
          return ;
       }
    }
 }
stack_init()
static struct misdn_stack* stack_init (int midev, int port, int ptp) static
Definition at line 1274 of file isdn_lib.c.
References misdn_stack::b_num, misdn_stack::b_stids, buff, calloc, cb_log, misdn_stack::d_stid, misdn_stack::downqueue, free(), handle_event_nt(), misdn_stack::holding, misdn_stack::l1link, misdn_stack::l2link, misdn_stack::lower_id, misdn_stack::mgr, misdn_stack::midev, misdn_lib::midev, misdn_lib_get_l1_up(), misdn_lib_get_l2_up(), misdn_lib_get_short_status(), misdn_stack::nst, misdn_stack::nstlock, misdn_stack::nt, NULL, misdn_stack::port, misdn_stack::pri, pthread_mutex_init, misdn_stack::ptp, ptp, misdn_stack::st_lock, and misdn_stack::upper_id.
Referenced by misdn_lib_init().
 {
    int ret;
    unsigned char buff[1025];
    iframe_t *frm = (iframe_t *)buff;
    stack_info_t *stinf;
    struct misdn_stack *stack;
    int i;
    layer_info_t li;
    stack = calloc(1, sizeof(struct misdn_stack));
    if (!stack) {
       return NULL;
    }
    cb_log(8, port, "Init. Stack.\n");
    stack->port=port;
    stack->midev=midev;
    stack->ptp=ptp;
    stack->holding=NULL;
    stack->pri=0;
    msg_queue_init(&stack->downqueue);
    pthread_mutex_init(&stack->st_lock, NULL);
    /* query port's requirements */
    ret = mISDN_get_stack_info(midev, port, buff, sizeof(buff));
    if (ret < 0) {
       cb_log(0, port, "%s: Cannot get stack info for this port. (ret=%d)\n", __FUNCTION__, ret);
       free(stack);
       return(NULL);
    }
    stinf = (stack_info_t *)&frm->data.p;
    stack->d_stid = stinf->id;
    stack->b_num = stinf->childcnt;
    for (i=0; i<=stinf->childcnt; i++)
       stack->b_stids[i] = stinf->child[i];
    switch(stinf->pid.protocol[0] & ~ISDN_PID_FEATURE_MASK) {
    case ISDN_PID_L0_TE_S0:
       cb_log(8, port, "TE Stack\n");
       stack->nt=0;
       break;
    case ISDN_PID_L0_NT_S0:
       cb_log(8, port, "NT Stack\n");
       stack->nt=1;
       break;
    case ISDN_PID_L0_TE_E1:
       cb_log(8, port, "TE S2M Stack\n");
       stack->nt=0;
       stack->pri=1;
       break;
    case ISDN_PID_L0_NT_E1:
       cb_log(8, port, "NT S2M Stack\n");
       stack->nt=1;
       stack->pri=1;
       break;
    default:
       cb_log(0, port, "this is a unknown port type 0x%08x\n", stinf->pid.protocol[0]);
    }
    if (!stack->nt) {
       if (stinf->pid.protocol[2] & ISDN_PID_L2_DF_PTP ) {
          stack->ptp = 1;
       } else {
          stack->ptp = 0;
       }
    }
    {
       int ret;
       int nt=stack->nt;
       memset(&li, 0, sizeof(li));
       {
          int l = sizeof(li.name);
          strncpy(li.name,nt?"net l2":"user l4", l);
          li.name[l-1] = 0;
       }
       li.object_id = -1;
       li.extentions = 0;
       li.pid.protocol[nt?2:4] = nt?ISDN_PID_L2_LAPD_NET:ISDN_PID_L4_CAPI20;
       li.pid.layermask = ISDN_LAYER((nt?2:4));
       li.st = stack->d_stid;
       ret = mISDN_new_layer(midev, &li);
       if (ret) {
          cb_log(0, port, "%s: Cannot add layer %d to this port.\n", __FUNCTION__, nt?2:4);
          free(stack);
          return(NULL);
       }
       ret = mISDN_register_layer(midev, stack->d_stid, li.id);
       if (ret)
       {
          cb_log(0,port,"Cannot register layer %d of this port.\n", nt?2:4);
          free(stack);
          return(NULL);
       }
       stack->lower_id = mISDN_get_layerid(midev, stack->d_stid, nt?1:3);
       if (stack->lower_id < 0) {
          cb_log(0, port, "%s: Cannot get layer(%d) id of this port.\n", __FUNCTION__, nt?1:3);
          free(stack);
          return(NULL);
       }
       stack->upper_id = mISDN_get_layerid(midev, stack->d_stid, nt?2:4);
       if (stack->upper_id < 0) {
          cb_log(0, port, "%s: Cannot get layer(%d) id of this port.\n", __FUNCTION__, nt?2:4);
          free(stack);
          return(NULL);
       }
       /* create nst (nt-mode only) */
       if (nt) {
          memset(&stack->nst, 0, sizeof(net_stack_t));
          memset(&stack->mgr, 0, sizeof(manager_t));
          stack->mgr.nst = &stack->nst;
          stack->nst.manager = &stack->mgr;
          stack->nst.l3_manager = handle_event_nt;
          stack->nst.device = midev;
          stack->nst.cardnr = port;
          stack->nst.d_stid = stack->d_stid;
          stack->nst.feature = FEATURE_NET_HOLD;
          if (stack->ptp)
             stack->nst.feature |= FEATURE_NET_PTP;
          if (stack->pri)
             stack->nst.feature |= FEATURE_NET_CRLEN2 | FEATURE_NET_EXTCID;
          stack->nst.l1_id = stack->lower_id; /* never used */
          stack->nst.l2_id = stack->upper_id;
          msg_queue_init(&stack->nst.down_queue);
          pthread_mutex_init(&stack->nstlock, NULL);
          Isdnl2Init(&stack->nst);
          Isdnl3Init(&stack->nst);
       }
       stack->l1link=0;
       stack->l2link=0;
 #if 0
       if (!stack->nt) {
          misdn_lib_get_short_status(stack);
       } else {
          misdn_lib_get_l1_up(stack);
          if (!stack->ptp) misdn_lib_get_l1_up(stack);
          misdn_lib_get_l2_up(stack);
       }
 #endif
       misdn_lib_get_short_status(stack);
       misdn_lib_get_l1_up(stack);
       /* handle_l1 will start L2 for NT. */
       if (!stack->nt) {
          misdn_lib_get_l2_up(stack);
       }
    }
    cb_log(8, port, "stack_init: lowerId:%x upperId:%x\n", stack->lower_id, stack->upper_id);
    return stack;
 }
te_lib_destroy()
void te_lib_destroy (int midev)
Definition at line 3142 of file isdn_lib.c.
References buf, cb_log, and NULL.
Referenced by misdn_lib_destroy(), and misdn_lib_init().
 {
    char buf[1024];
    mISDN_write_frame(midev, buf, 0, MGR_DELENTITY | REQUEST, entity, 0, NULL, TIMEOUT_1SEC);
    cb_log(4, 0, "Entity deleted\n");
    mISDN_close(midev);
    cb_log(4, 0, "midev closed\n");
 }
te_lib_init()
static int te_lib_init (void) static
App Interface
Definition at line 3116 of file isdn_lib.c.
References buff, errno, misdn_lib::midev, and NULL.
Referenced by misdn_lib_init().
 {
    char buff[1025] = "";
    iframe_t *frm = (iframe_t *) buff;
    int midev;
    int ret;
    midev = mISDN_open();
    if (midev <= 0) {
       return midev;
    }
    /* create entity for layer 3 TE-mode */
    mISDN_write_frame(midev, buff, 0, MGR_NEWENTITY | REQUEST, 0, 0, NULL, TIMEOUT_1SEC);
    ret = mISDN_read_frame(midev, frm, sizeof(iframe_t), 0, MGR_NEWENTITY | CONFIRM, TIMEOUT_1SEC);
    entity = frm->dinfo & 0xffff;
    if (ret < mISDN_HEADER_LEN || !entity) {
       fprintf(stderr, "cannot request MGR_NEWENTITY from mISDN: %s\n", strerror(errno));
       mISDN_close(midev);
       return -1;
    }
    return midev;
 }
test_inuse()
static int test_inuse (struct misdn_bchannel * bc) static
Definition at line 3168 of file isdn_lib.c.
References misdn_bchannel::b_stid, cb_log, misdn_bchannel::in_use, misdn_bchannel::last_used, misdn_lib_port_is_pri(), NULL, and misdn_bchannel::port.
Referenced by misdn_lib_get_free_bc().
 {
    struct timeval now;
    if (!bc->in_use) {
       gettimeofday(&now, NULL);
       if (bc->last_used.tv_sec == now.tv_sec
          && misdn_lib_port_is_pri(bc->port)) {
          cb_log(2, bc->port, "channel with stid:%x for one second still in use! (n:%d lu:%d)\n",
             bc->b_stid, (int) now.tv_sec, (int) bc->last_used.tv_sec);
          return 1;
       }
       cb_log(3,bc->port, "channel with stid:%x not in use!\n", bc->b_stid);
       return 0;
    }
    cb_log(2,bc->port, "channel with stid:%x in use!\n", bc->b_stid);
    return 1;
 }
Variable Documentation
cb_event
enum event_response_e(* cb_event) (enum event_e event, struct misdn_bchannel *bc, void *user_data)
Definition at line 30 of file isdn_lib.c.
Referenced by clear_l3(), do_tone(), handle_bchan(), handle_cr(), handle_event_nt(), handle_frm_te(), handle_l1(), handle_l2(), manager_clean_bc(), misdn_lib_init(), set_channel(), and setup_bc().
cb_jb_empty
int(* cb_jb_empty) (struct misdn_bchannel *bc, char *buffer, int len)
Definition at line 35 of file isdn_lib.c.
Referenced by misdn_lib_init(), and misdn_tx_jitter().
cb_log
void(* cb_log) (int level, int port, char *tmpl,...)
Definition at line 32 of file isdn_lib.c.
Referenced by bc_next_state_change(), bc_state_change(), build_connect(), build_disconnect(), build_release(), build_release_complete(), build_restart(), build_setup(), cb_events(), clean_up_bc(), config_jitterbuffer(), create_process(), dec_ie_facility(), do_tone(), dump_chan_list(), empty_chan_in_stack(), fetch_msg(), find_free_chan_in_stack(), handle_bchan(), handle_cr(), handle_err(), handle_event_nt(), handle_event_te(), handle_frm_nt(), handle_frm_te(), handle_l1(), handle_l2(), handle_mgmt(), handle_timers(), hangup_chan(), init_bc(), isdn_msg_get_index_by_event(), manager_bchannel_activate(), manager_bchannel_deactivate(), manager_ec_disable(), manager_ec_enable(), manager_event_handler(), manager_isdn_handler(), manager_ph_control(), misdn_join_conf(), misdn_lib_bridge(), misdn_lib_destroy(), misdn_lib_echo(), misdn_lib_get_free_bc(), misdn_lib_get_l1_down(), misdn_lib_get_l1_up(), misdn_lib_get_port_info(), misdn_lib_init(), misdn_lib_isdn_event_catcher(), misdn_lib_isdn_l1watcher(), misdn_lib_log_ies(), misdn_lib_port_restart(), misdn_lib_port_up(), misdn_lib_release(), misdn_lib_send_event(), misdn_lib_send_restart(), misdn_lib_split_bridge(), misdn_lib_tx2misdn_frm(), misdn_split_conf(), misdn_tasks_destroy(), misdn_tx_jitter(), misdn_write(), parse_facility(), parse_release_complete(), parse_restart(), parse_setup(), release_cr(), send_msg(), set_chan_in_stack(), set_channel(), setup_bc(), stack_holder_add(), stack_holder_find(), stack_holder_remove(), stack_init(), te_lib_destroy(), and test_inuse().
entity
int entity static
Definition at line 259 of file isdn_lib.c.
Referenced by ast_xml_escape(), pidf_allocate_body(), and pidf_validate_presence().
flip_table
char flip_table[256] static
Definition at line 319 of file isdn_lib.c.
glob_mgr
struct misdn_lib* glob_mgr static
Definition at line 261 of file isdn_lib.c.
global_state
enum global_states global_state =MISDN_INITIALIZING static
Definition at line 199 of file isdn_lib.c.
handler_started
sem_t handler_started static
Definition at line 4022 of file isdn_lib.c.
msgs_g
struct isdn_msg msgs_g[]
Msg Array
Definition at line 1633 of file isdn_msg_parser.c.
Referenced by handle_event_nt(), handle_frm_te(), manager_isdn_get_info(), and misdn_lib_send_event().
mypid
int mypid =1 static
Definition at line 433 of file isdn_lib.c.
Referenced by prepare_bc().
new_te_id
int new_te_id = 0 static
Definition at line 874 of file isdn_lib.c.
nt_err_cnt
int nt_err_cnt =0 static
Definition at line 192 of file isdn_lib.c.
tone_425_flip
char tone_425_flip[TONE_425_SIZE] static
Definition at line 263 of file isdn_lib.c.
tone_silence_flip
char tone_silence_flip[TONE_SILENCE_SIZE] static
Definition at line 264 of file isdn_lib.c.