Asterisk - The Open Source Telephony Project: console_video.h File Reference
console_video.h File Reference
Data Structures
struct drag_info
support for drag actions
struct fbuf_t
struct grab_desc
Macros
#define CONSOLE_VIDEO_CMDS "console {device}"
#define MAX_VIDEO_SOURCES 9
#define SRC_WIN_H 60 /* height of video thumbnails */
#define SRC_WIN_W 80 /* width of video thumbnails */
Enumerations
enum drag_window {
DRAG_NONE, DRAG_LOCAL, DRAG_REMOTE, DRAG_DIALED,
DRAG_INPUT, DRAG_MESSAGE, DRAG_PIP
}
enum kb_output { KO_NONE, KO_INPUT, KO_DIALED, KO_MESSAGE }
Functions
int console_video_cli (struct video_desc *env, const char *var, int fd)
int console_video_config (struct video_desc **penv, const char *var, const char *val)
void console_video_start (struct video_desc *env, struct ast_channel *owner)
void console_video_uninit (struct video_desc *env)
int console_write_video (struct ast_channel *chan, struct ast_frame *f)
void delete_board (struct board *b)
deallocates memory space for a board
void fbuf_free (struct fbuf_t *)
int get_gui_startup (struct video_desc *env)
struct video_desc * get_video_desc (struct ast_channel *c)
return the pointer to the video descriptor
void move_message_board (struct board *b, int dy)
int print_message (struct board *b, const char *s)
const char * read_message (const struct board *b)
return the whole text from a board
int reset_board (struct board *b)
reset the board to blank
Variables
struct grab_desc * console_grabbers []
int console_video_formats
Macro Definition Documentation
CONSOLE_VIDEO_CMDS
#define CONSOLE_VIDEO_CMDS "console {device}"
Definition at line 27 of file console_video.h.
Referenced by console_cmd().
MAX_VIDEO_SOURCES
#define MAX_VIDEO_SOURCES 9
Definition at line 51 of file console_video.h.
SRC_WIN_H
#define SRC_WIN_H 60 /* height of video thumbnails */
Definition at line 47 of file console_video.h.
Referenced by keypad_cfg_read().
SRC_WIN_W
#define SRC_WIN_W 80 /* width of video thumbnails */
Definition at line 46 of file console_video.h.
Referenced by keypad_cfg_read().
Enumeration Type Documentation
drag_window
enum drag_window
Enumerator
DRAG_NONE
DRAG_LOCAL
DRAG_REMOTE
DRAG_DIALED
DRAG_INPUT
DRAG_MESSAGE
DRAG_PIP
Definition at line 112 of file console_video.h.
                  {   /* which window are we dragging */
    DRAG_NONE,
    DRAG_LOCAL, /* local video */
    DRAG_REMOTE,   /* remote video */
    DRAG_DIALED,   /* dialed number */
    DRAG_INPUT, /* input window */
    DRAG_MESSAGE,  /* message window */
    DRAG_PIP,   /* picture in picture */
 };
kb_output
enum kb_output
Enumerator
KO_NONE
KO_INPUT
KO_DIALED
KO_MESSAGE
Definition at line 105 of file console_video.h.
                {
    KO_NONE,
    KO_INPUT,   /* the local input window */
    KO_DIALED,  /* the 'dialed number' window */
    KO_MESSAGE, /* the 'message' window */
 };
Function Documentation
console_video_cli()
int console_video_cli (struct video_desc * env, const char * var, int fd)
Definition at line 124 of file console_video.c.
Referenced by console_cmd().
 {
    return 1;   /* nothing matched */
 }
console_video_config()
int console_video_config (struct video_desc ** penv, const char * var, const char * val)
Definition at line 129 of file console_video.c.
Referenced by store_config_core().
 {
    return 1;   /* no configuration */
 }
console_video_start()
void console_video_start (struct video_desc * env, struct ast_channel * owner)
Definition at line 134 of file console_video.c.
References ast_log, and LOG_NOTICE.
Referenced by oss_new(), and store_config().
 {
    ast_log(LOG_NOTICE, "voice only, console video support not present\n");
 }
console_video_uninit()
void console_video_uninit (struct video_desc * env)
Definition at line 139 of file console_video.c.
Referenced by oss_hangup().
 {
 }
console_write_video()
int console_write_video (struct ast_channel * chan, struct ast_frame * f)
Definition at line 119 of file console_video.c.
 {
    return 0;   /* writing video not supported */
 }
delete_board()
void delete_board (struct board * b)
deallocates memory space for a board
Referenced by keypad_cfg_read().
fbuf_free()
void fbuf_free (struct fbuf_t *)
Referenced by dec_uninit().
get_gui_startup()
int get_gui_startup (struct video_desc * env)
Definition at line 143 of file console_video.c.
Referenced by store_config().
 {
    return 0; /* no gui here */
 }
get_video_desc()
struct video_desc* get_video_desc (struct ast_channel * c)
return the pointer to the video descriptor
Definition at line 319 of file chan_oss.c.
References ast_channel_tech_pvt(), chan_oss_pvt::env, find_desc(), NULL, and oss_active.
Referenced by oss_new().
 {
    struct chan_oss_pvt *o = c ? ast_channel_tech_pvt(c) : find_desc(oss_active);
    return o ? o->env : NULL;
 }
move_message_board()
void move_message_board (struct board * b, int dy)
Referenced by keypad_cfg_read().
print_message()
int print_message (struct board * b, const char * s)
Referenced by keypad_cfg_read().
read_message()
const char* read_message (const struct board * b)
return the whole text from a board
Referenced by keypad_cfg_read().
reset_board()
int reset_board (struct board * b)
reset the board to blank
Referenced by keypad_cfg_read().
Variable Documentation
console_grabbers
struct grab_desc* console_grabbers[]
Referenced by keypad_cfg_read().
console_video_formats
int console_video_formats
Definition at line 148 of file console_video.c.