Asterisk - The Open Source Telephony Project: test_dlinklists.c File Reference
test_dlinklists.c File Reference
Doubly-Linked List Tests.
#include "asterisk.h"
#include "asterisk/file.h"
#include "asterisk/channel.h"
#include "asterisk/pbx.h"
#include "asterisk/module.h"
#include "asterisk/lock.h"
#include "asterisk/app.h"
#include "asterisk/dlinkedlists.h"
Data Structures
struct test_container::entries
struct test1
struct test_container
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static void destroy_test_container (struct test_container *x)
static void dll_tests (void)
static int load_module (void)
static struct test_container * make_cont (void)
static struct test1 * make_test1 (char *name)
static void print_list (struct test_container *x, char *expect)
static void print_list_backwards (struct test_container *x, char *expect)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Test Doubly-Linked Lists" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, }
static const struct ast_module_info * ast_module_info = &__mod_info
Detailed Description
Doubly-Linked List Tests.
Author
Steve Murphy <murf@digium.com>
This module will run some DLL tests at load time
Definition in file test_dlinklists.c.
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 364 of file test_dlinklists.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 364 of file test_dlinklists.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 364 of file test_dlinklists.c.
destroy_test_container()
static void destroy_test_container (struct test_container * x) static
Definition at line 101 of file test_dlinklists.c.
References AST_DLLIST_REMOVE_CURRENT, AST_DLLIST_TRAVERSE_BACKWARDS_SAFE_BEGIN, AST_DLLIST_TRAVERSE_BACKWARDS_SAFE_END, ast_free, test_container::entries, test1::list, and t1.
Referenced by dll_tests().
 {
    /* remove all the test1's */
    struct test1 *t1;
    AST_DLLIST_TRAVERSE_BACKWARDS_SAFE_BEGIN(&x->entries, t1, list) {
       AST_DLLIST_REMOVE_CURRENT(list);
       ast_free(t1);
    }
    AST_DLLIST_TRAVERSE_BACKWARDS_SAFE_END;
    ast_free(x);
 }
dll_tests()
static void dll_tests (void) static
Definition at line 172 of file test_dlinklists.c.
References a, ast_debug, AST_DLLIST_EMPTY, AST_DLLIST_FIRST, AST_DLLIST_INSERT_AFTER, AST_DLLIST_INSERT_BEFORE_CURRENT, AST_DLLIST_INSERT_BEFORE_CURRENT_BACKWARDS, AST_DLLIST_INSERT_HEAD, AST_DLLIST_INSERT_TAIL, AST_DLLIST_LAST, AST_DLLIST_MOVE_CURRENT, AST_DLLIST_MOVE_CURRENT_BACKWARDS, AST_DLLIST_NEXT, AST_DLLIST_PREV, AST_DLLIST_REMOVE, AST_DLLIST_REMOVE_CURRENT, AST_DLLIST_REMOVE_HEAD, AST_DLLIST_TRAVERSE_BACKWARDS_SAFE_BEGIN, AST_DLLIST_TRAVERSE_SAFE_BEGIN, AST_DLLIST_TRAVERSE_SAFE_END, ast_free, ast_log, b, c, d, destroy_test_container(), test_container::entries, test1::list, LOG_ERROR, make_cont(), make_test1(), print_list(), and print_list_backwards().
Referenced by load_module().
 {
    struct test_container *tc;
    struct test1 *a;
    struct test1 *b;
    struct test1 *c;
    struct test1 *d;
    struct test1 *e;
    ast_debug(1,"Test AST_DLLIST_INSERT_HEAD, AST_DLLIST_TRAVERSE, AST_DLLIST_TRAVERSE_BACKWARDS_SAFE_BEGIN, AST_DLLIST_TRAVERSE_BACKWARDS_SAFE_END\n");
    tc = make_cont();
    a = make_test1("A");
    b = make_test1("B");
    c = make_test1("C");
    d = make_test1("D");
    AST_DLLIST_INSERT_HEAD(&tc->entries, d, list);
    AST_DLLIST_INSERT_HEAD(&tc->entries, c, list);
    AST_DLLIST_INSERT_HEAD(&tc->entries, b, list);
    AST_DLLIST_INSERT_HEAD(&tc->entries, a, list);
    print_list(tc, "A <=> B <=> C <=> D");
    destroy_test_container(tc);
    tc = make_cont();
    if (AST_DLLIST_EMPTY(&tc->entries))
       ast_debug(1,"Test AST_DLLIST_EMPTY....OK\n");
    else
       ast_log(LOG_ERROR,"Test AST_DLLIST_EMPTY....PROBLEM!!\n");
    a = make_test1("A");
    b = make_test1("B");
    c = make_test1("C");
    d = make_test1("D");
    ast_debug(1,"Test AST_DLLIST_INSERT_TAIL\n");
    AST_DLLIST_INSERT_TAIL(&tc->entries, a, list);
    AST_DLLIST_INSERT_TAIL(&tc->entries, b, list);
    AST_DLLIST_INSERT_TAIL(&tc->entries, c, list);
    AST_DLLIST_INSERT_TAIL(&tc->entries, d, list);
    print_list(tc, "A <=> B <=> C <=> D");
    if (AST_DLLIST_FIRST(&tc->entries) == a)
       ast_debug(1,"Test AST_DLLIST_FIRST....OK\n");
    else
       ast_log(LOG_ERROR,"Test AST_DLLIST_FIRST....PROBLEM\n");
    if (AST_DLLIST_LAST(&tc->entries) == d)
       ast_debug(1,"Test AST_DLLIST_LAST....OK\n");
    else
       ast_log(LOG_ERROR,"Test AST_DLLIST_LAST....PROBLEM\n");
    if (AST_DLLIST_NEXT(a,list) == b)
       ast_debug(1,"Test AST_DLLIST_NEXT....OK\n");
    else
       ast_log(LOG_ERROR,"Test AST_DLLIST_NEXT....PROBLEM\n");
    if (AST_DLLIST_PREV(d,list) == c)
       ast_debug(1,"Test AST_DLLIST_PREV....OK\n");
    else
       ast_log(LOG_ERROR,"Test AST_DLLIST_PREV....PROBLEM\n");
    destroy_test_container(tc);
    tc = make_cont();
    a = make_test1("A");
    b = make_test1("B");
    c = make_test1("C");
    d = make_test1("D");
    ast_debug(1,"Test AST_DLLIST_INSERT_AFTER, AST_DLLIST_TRAVERSE_BACKWARDS\n");
    AST_DLLIST_INSERT_HEAD(&tc->entries, a, list);
    AST_DLLIST_INSERT_AFTER(&tc->entries, a, b, list);
    AST_DLLIST_INSERT_AFTER(&tc->entries, b, c, list);
    AST_DLLIST_INSERT_AFTER(&tc->entries, c, d, list);
    print_list_backwards(tc, "D <=> C <=> B <=> A");
    ast_debug(1,"Test AST_DLLIST_REMOVE_HEAD\n");
    AST_DLLIST_REMOVE_HEAD(&tc->entries, list);
    print_list_backwards(tc, "D <=> C <=> B");
    ast_debug(1,"Test AST_DLLIST_REMOVE_HEAD\n");
    AST_DLLIST_REMOVE_HEAD(&tc->entries, list);
    print_list_backwards(tc, "D <=> C");
    ast_debug(1,"Test AST_DLLIST_REMOVE_HEAD\n");
    AST_DLLIST_REMOVE_HEAD(&tc->entries, list);
    print_list_backwards(tc, "D");
    AST_DLLIST_REMOVE_HEAD(&tc->entries, list);
    if (AST_DLLIST_EMPTY(&tc->entries))
       ast_debug(1,"Test AST_DLLIST_REMOVE_HEAD....OK\n");
    else
       ast_log(LOG_ERROR,"Test AST_DLLIST_REMOVE_HEAD....PROBLEM!!\n");
    AST_DLLIST_INSERT_HEAD(&tc->entries, a, list);
    AST_DLLIST_INSERT_AFTER(&tc->entries, a, b, list);
    AST_DLLIST_INSERT_AFTER(&tc->entries, b, c, list);
    AST_DLLIST_INSERT_AFTER(&tc->entries, c, d, list);
    ast_debug(1,"Test AST_DLLIST_REMOVE\n");
    AST_DLLIST_REMOVE(&tc->entries, c, list);
    print_list(tc, "A <=> B <=> D");
    AST_DLLIST_REMOVE(&tc->entries, a, list);
    print_list(tc, "B <=> D");
    AST_DLLIST_REMOVE(&tc->entries, d, list);
    print_list(tc, "B");
    AST_DLLIST_REMOVE(&tc->entries, b, list);
    if (AST_DLLIST_EMPTY(&tc->entries))
       ast_debug(1,"Test AST_DLLIST_REMOVE....OK\n");
    else
       ast_log(LOG_ERROR,"Test AST_DLLIST_REMOVE....PROBLEM!!\n");
    AST_DLLIST_INSERT_HEAD(&tc->entries, a, list);
    AST_DLLIST_INSERT_AFTER(&tc->entries, a, b, list);
    AST_DLLIST_INSERT_AFTER(&tc->entries, b, c, list);
    AST_DLLIST_INSERT_AFTER(&tc->entries, c, d, list);
    AST_DLLIST_TRAVERSE_SAFE_BEGIN(&tc->entries, e, list) {
       AST_DLLIST_REMOVE_CURRENT(list);
    }
    AST_DLLIST_TRAVERSE_SAFE_END;
    if (AST_DLLIST_EMPTY(&tc->entries))
       ast_debug(1,"Test AST_DLLIST_REMOVE_CURRENT... OK\n");
    else
       ast_log(LOG_ERROR,"Test AST_DLLIST_REMOVE_CURRENT... PROBLEM\n");
    ast_debug(1,"Test AST_DLLIST_MOVE_CURRENT, AST_DLLIST_INSERT_BEFORE_CURRENT\n");
    AST_DLLIST_INSERT_HEAD(&tc->entries, a, list);
    AST_DLLIST_INSERT_AFTER(&tc->entries, a, b, list);
    AST_DLLIST_INSERT_AFTER(&tc->entries, b, c, list);
    AST_DLLIST_TRAVERSE_SAFE_BEGIN(&tc->entries, e, list) {
       if (e == a) {
          AST_DLLIST_INSERT_BEFORE_CURRENT(d, list);  /* D A B C */
       }
       if (e == b) {
          AST_DLLIST_MOVE_CURRENT(&tc->entries, list); /* D A C B */
       }
    }
    AST_DLLIST_TRAVERSE_SAFE_END;
    print_list(tc, "D <=> A <=> C <=> B");
    destroy_test_container(tc);
    tc = make_cont();
    a = make_test1("A");
    b = make_test1("B");
    c = make_test1("C");
    d = make_test1("D");
    ast_debug(1,"Test: AST_DLLIST_MOVE_CURRENT_BACKWARDS and AST_DLLIST_INSERT_BEFORE_CURRENT_BACKWARDS\n");
    AST_DLLIST_INSERT_HEAD(&tc->entries, a, list);
    AST_DLLIST_INSERT_AFTER(&tc->entries, a, b, list);
    AST_DLLIST_INSERT_AFTER(&tc->entries, b, c, list);
    AST_DLLIST_TRAVERSE_BACKWARDS_SAFE_BEGIN(&tc->entries, e, list) {
       if (e == c && AST_DLLIST_FIRST(&tc->entries) != c) {
          AST_DLLIST_MOVE_CURRENT_BACKWARDS(&tc->entries, list); /* C A B */
          print_list(tc, "C <=> A <=> B");
       }
       if (e == b) {
          AST_DLLIST_REMOVE_CURRENT(list);  /* C A */
          ast_free(b);
          print_list(tc, "C <=> A");
       }
       if (e == a) {
          AST_DLLIST_INSERT_BEFORE_CURRENT_BACKWARDS(d, list); /* C A D */
          print_list(tc, "C <=> A <=> D");
       }
    }
    AST_DLLIST_TRAVERSE_SAFE_END;
    print_list(tc, "C <=> A <=> D");
    destroy_test_container(tc);
 }
load_module()
static int load_module (void) static
Definition at line 358 of file test_dlinklists.c.
References AST_MODULE_LOAD_SUCCESS, and dll_tests().
 {
    dll_tests();
    return AST_MODULE_LOAD_SUCCESS;
 }
make_cont()
static struct test_container* make_cont (void) static
Definition at line 88 of file test_dlinklists.c.
References ast_calloc.
Referenced by dll_tests().
 {
    struct test_container *t = ast_calloc(sizeof(struct test_container),1);
    return t;
 }
make_test1()
static struct test1* make_test1 (char * name) static
Definition at line 94 of file test_dlinklists.c.
References ast_calloc, test1::name, and t1.
Referenced by dll_tests().
 {
    struct test1 *t1 = ast_calloc(sizeof(struct test1),1);
    strcpy(t1->name, name);
    return t1;
 }
print_list()
static void print_list (struct test_container * x, char * expect) static
Definition at line 60 of file test_dlinklists.c.
References ast_debug, AST_DLLIST_LAST, AST_DLLIST_TRAVERSE, buff, test_container::entries, test1::list, test1::name, and t1.
Referenced by dll_tests().
 {
    struct test1 *t1;
    char buff[1000];
    buff[0] = 0;
    AST_DLLIST_TRAVERSE(&x->entries, t1, list) {
       strcat(buff,t1->name);
       if (t1 != AST_DLLIST_LAST(&x->entries))
          strcat(buff," <=> ");
    }
    ast_debug(1,"Got: %s  [expect %s]\n", buff, expect);
 }
print_list_backwards()
static void print_list_backwards (struct test_container * x, char * expect) static
Definition at line 74 of file test_dlinklists.c.
References ast_debug, AST_DLLIST_FIRST, AST_DLLIST_TRAVERSE_BACKWARDS, buff, test_container::entries, test1::list, test1::name, and t1.
Referenced by dll_tests().
 {
    struct test1 *t1;
    char buff[1000];
    buff[0] = 0;
    AST_DLLIST_TRAVERSE_BACKWARDS(&x->entries, t1, list) {
       strcat(buff,t1->name);
       if (t1 != AST_DLLIST_FIRST(&x->entries))
          strcat(buff," <=> ");
    }
    ast_debug(1,"Got: %s  [expect %s]\n", buff, expect);
 }
unload_module()
static int unload_module (void) static
Definition at line 353 of file test_dlinklists.c.
 {
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Test Doubly-Linked Lists" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, } static
Definition at line 364 of file test_dlinklists.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 364 of file test_dlinklists.c.