Asterisk - The Open Source Telephony Project: bt_get.c File Reference
bt_get.c File Reference
#include <sys/types.h>
#include <errno.h>
#include <stddef.h>
#include <stdio.h>
#include "../include/db.h"
#include "btree.h"
Functions
int __bt_get (DB *dbp, const DBT *key, DBT *data, u_int flags) const
Function Documentation
__bt_get()
int __bt_get (DB * dbp, const DBT * key, DBT * data, u_int flags) const
Definition at line 63 of file bt_get.c.
References __bt_ret(), __bt_search(), B_DB_LOCK, _btree::bt_mp, _btree::bt_pinned, _btree::bt_rdata, errno, F_ISSET, __db::internal, mpool_put(), NULL, _epg::page, RET_ERROR, RET_SPECIAL, and status.
Referenced by __bt_open().
 {
    BTREE *t;
    EPG *e;
    int exact, status;
    t = dbp->internal;
    /* Toss any page pinned across calls. */
    if (t->bt_pinned != NULL) {
       mpool_put(t->bt_mp, t->bt_pinned, 0);
       t->bt_pinned = NULL;
    }
    /* Get currently doesn't take any flags. */
    if (flags) {
       errno = EINVAL;
       return (RET_ERROR);
    }
    if ((e = __bt_search(t, key, &exact)) == NULL)
       return (RET_ERROR);
    if (!exact) {
       mpool_put(t->bt_mp, e->page, 0);
       return (RET_SPECIAL);
    }
    status = __bt_ret(t, e, NULL, NULL, data, &t->bt_rdata, 0);
    /*
     * If the user is doing concurrent access, we copied the
     * key/data, toss the page.
     */
    if (F_ISSET(t, B_DB_LOCK))
       mpool_put(t->bt_mp, e->page, 0);
    else
       t->bt_pinned = e->page;
    return (status);
 }