Asterisk - The Open Source Telephony Project: app_channelredirect.c File Reference
app_channelredirect.c File Reference
Dial plan applications
ChannelRedirect application.
#include "asterisk.h"
#include "asterisk/file.h"
#include "asterisk/channel.h"
#include "asterisk/pbx.h"
#include "asterisk/module.h"
#include "asterisk/lock.h"
#include "asterisk/app.h"
#include "asterisk/features.h"
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int asyncgoto_exec (struct ast_channel *chan, const char *data)
static int load_module (void)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Redirects a given channel to a dialplan target" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, }
static const char app [] = "ChannelRedirect"
static const struct ast_module_info * ast_module_info = &__mod_info
Detailed Description
ChannelRedirect application.
Author
Sergey Basmanov serge.nosp@m.y_ba.nosp@m.smano.nosp@m.v@ma.nosp@m.il.ru
Definition in file app_channelredirect.c.
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 117 of file app_channelredirect.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 117 of file app_channelredirect.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 117 of file app_channelredirect.c.
asyncgoto_exec()
static int asyncgoto_exec (struct ast_channel * chan, const char * data) static
Definition at line 67 of file app_channelredirect.c.
References app, args, AST_APP_ARG, ast_async_parseable_goto(), ast_channel_get_by_name(), ast_channel_unref, AST_DECLARE_APP_ARGS, ast_log, AST_STANDARD_APP_ARGS, ast_strdupa, ast_strlen_zero, sip_to_pjsip::info(), LOG_WARNING, NULL, and pbx_builtin_setvar_helper().
Referenced by load_module().
 {
    int res = -1;
    char *info;
    struct ast_channel *chan2 = NULL;
    AST_DECLARE_APP_ARGS(args,
       AST_APP_ARG(channel);
       AST_APP_ARG(label);
    );
    if (ast_strlen_zero(data)) {
       ast_log(LOG_WARNING, "%s requires an argument (channel,[[context,]exten,]priority)\n", app);
       return -1;
    }
    info = ast_strdupa(data);
    AST_STANDARD_APP_ARGS(args, info);
    if (ast_strlen_zero(args.channel) || ast_strlen_zero(args.label)) {
       ast_log(LOG_WARNING, "%s requires an argument (channel,[[context,]exten,]priority)\n", app);
       return -1;
    }
    if (!(chan2 = ast_channel_get_by_name(args.channel))) {
       ast_log(LOG_WARNING, "No such channel: %s\n", args.channel);
       pbx_builtin_setvar_helper(chan, "CHANNELREDIRECT_STATUS", "NOCHANNEL");
       return 0;
    }
    res = ast_async_parseable_goto(chan2, args.label);
    chan2 = ast_channel_unref(chan2);
    pbx_builtin_setvar_helper(chan, "CHANNELREDIRECT_STATUS", "SUCCESS");
    return res;
 }
load_module()
static int load_module (void) static
Definition at line 111 of file app_channelredirect.c.
References app, AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, ast_register_application_xml, and asyncgoto_exec().
 {
    return ast_register_application_xml(app, asyncgoto_exec) ?
       AST_MODULE_LOAD_DECLINE : AST_MODULE_LOAD_SUCCESS;
 }
unload_module()
static int unload_module (void) static
Definition at line 106 of file app_channelredirect.c.
References app, and ast_unregister_application().
 {
    return ast_unregister_application(app);
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Redirects a given channel to a dialplan target" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, } static
Definition at line 117 of file app_channelredirect.c.
app
const char app[] = "ChannelRedirect" static
Definition at line 65 of file app_channelredirect.c.
Referenced by asyncgoto_exec(), load_module(), and unload_module().
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 117 of file app_channelredirect.c.