Asterisk - The Open Source Telephony Project: plc.h File Reference
plc.h File Reference
SpanDSP - a series of DSP components for telephony.
Data Structures
struct plc_state_t
Macros
#define CORRELATION_SPAN 160
#define PLC_HISTORY_LEN (CORRELATION_SPAN + PLC_PITCH_MIN)
#define PLC_PITCH_MAX 40
#define PLC_PITCH_MIN 120
#define PLC_PITCH_OVERLAP_MAX (PLC_PITCH_MIN >> 2)
Functions
int plc_fillin (plc_state_t *s, int16_t amp[], int len)
Fill-in a block of missing audio samples.
plc_state_t * plc_init (plc_state_t *s)
Process a block of received V.29 modem audio samples.
int plc_rx (plc_state_t *s, int16_t amp[], int len)
Process a block of received audio samples.
Detailed Description
SpanDSP - a series of DSP components for telephony.
plc.h
Author
Steve Underwood steve.nosp@m.u@co.nosp@m.ppice.nosp@m..org
Copyright (C) 2004 Steve Underwood
All rights reserved.
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
This version may be optionally licenced under the GNU LGPL licence.
A license has been granted to Digium (via disclaimer) for the use of this code.
Definition in file plc.h.
Macro Definition Documentation
CORRELATION_SPAN
#define CORRELATION_SPAN 160
The length over which the AMDF function looks for similarity (20 ms)
Definition at line 99 of file plc.h.
Referenced by plc_fillin().
PLC_HISTORY_LEN
#define PLC_HISTORY_LEN (CORRELATION_SPAN + PLC_PITCH_MIN)
History buffer length. The buffer much also be at leat 1.25 times PLC_PITCH_MIN, but that is much smaller than the buffer needs to be for the pitch assessment.
Definition at line 103 of file plc.h.
Referenced by normalise_history(), plc_fillin(), and save_history().
PLC_PITCH_MAX
#define PLC_PITCH_MAX 40
Maximum allowed pitch (200 Hz)
Definition at line 95 of file plc.h.
Referenced by plc_fillin().
PLC_PITCH_MIN
#define PLC_PITCH_MIN 120
Minimum allowed pitch (66 Hz)
Definition at line 93 of file plc.h.
Referenced by plc_fillin().
PLC_PITCH_OVERLAP_MAX
#define PLC_PITCH_OVERLAP_MAX (PLC_PITCH_MIN >> 2)
Maximum pitch OLA window
Definition at line 97 of file plc.h.
Function Documentation
plc_fillin()
int plc_fillin (plc_state_t * s, int16_t amp[], int len)
Fill-in a block of missing audio samples.
Fill-in a block of missing audio samples.
Parameters
s The packet loss concealer context.
amp The audio sample buffer.
len The number of samples to be synthesised.
Returns
The number of samples synthesized.
Definition at line 175 of file plc.c.
References amdf_pitch(), ATTENUATION_INCREMENT, CORRELATION_SPAN, fsaturate(), plc_state_t::history, len(), plc_state_t::missing_samples, normalise_history(), plc_state_t::pitch, plc_state_t::pitch_offset, plc_state_t::pitchbuf, PLC_HISTORY_LEN, PLC_PITCH_MAX, PLC_PITCH_MIN, and save_history().
Referenced by adjust_frame_for_plc().
 {
    int i;
    int pitch_overlap;
    float old_step;
    float new_step;
    float old_weight;
    float new_weight;
    float gain;
    int orig_len;
    orig_len = len;
    if (s->missing_samples == 0) {
       /* As the gap in real speech starts we need to assess the last known pitch,
       and prepare the synthetic data we will use for fill-in */
       normalise_history(s);
       s->pitch = amdf_pitch(PLC_PITCH_MIN, PLC_PITCH_MAX, s->history + PLC_HISTORY_LEN - CORRELATION_SPAN - PLC_PITCH_MIN, CORRELATION_SPAN);
       /* We overlap a 1/4 wavelength */
       pitch_overlap = s->pitch >> 2;
       /* Cook up a single cycle of pitch, using a single of the real signal with 1/4
       cycle OLA'ed to make the ends join up nicely */
       /* The first 3/4 of the cycle is a simple copy */
       for (i = 0;  i < s->pitch - pitch_overlap;  i++)
          s->pitchbuf[i] = s->history[PLC_HISTORY_LEN - s->pitch + i];
       /* The last 1/4 of the cycle is overlapped with the end of the previous cycle */
       new_step = 1.0/pitch_overlap;
       new_weight = new_step;
       for ( ; i < s->pitch; i++) {
          s->pitchbuf[i] = s->history[PLC_HISTORY_LEN - s->pitch + i] * (1.0 - new_weight) + s->history[PLC_HISTORY_LEN - 2 * s->pitch + i]*new_weight;
          new_weight += new_step;
       }
       /* We should now be ready to fill in the gap with repeated, decaying cycles
       of what is in pitchbuf */
       /* We need to OLA the first 1/4 wavelength of the synthetic data, to smooth
       it into the previous real data. To avoid the need to introduce a delay
       in the stream, reverse the last 1/4 wavelength, and OLA with that. */
       gain = 1.0;
       new_step = 1.0 / pitch_overlap;
       old_step = new_step;
       new_weight = new_step;
       old_weight = 1.0 - new_step;
       for (i = 0; i < pitch_overlap; i++) {
          amp[i] = fsaturate(old_weight * s->history[PLC_HISTORY_LEN - 1 - i] + new_weight * s->pitchbuf[i]);
          new_weight += new_step;
          old_weight -= old_step;
          if (old_weight < 0.0)
             old_weight = 0.0;
       }
       s->pitch_offset = i;
    } else {
       gain = 1.0 - s->missing_samples*ATTENUATION_INCREMENT;
       i = 0;
    }
    for ( ; gain > 0.0 && i < len; i++) {
       amp[i] = s->pitchbuf[s->pitch_offset] * gain;
       gain -= ATTENUATION_INCREMENT;
       if (++s->pitch_offset >= s->pitch)
          s->pitch_offset = 0;
    }
    for ( ; i < len; i++)
       amp[i] = 0;
    s->missing_samples += orig_len;
    save_history(s, amp, len);
    return len;
 }
plc_init()
plc_state_t* plc_init (plc_state_t * s)
Process a block of received V.29 modem audio samples.
Process a block of received V.29 modem audio samples.
Parameters
s The packet loss concealer context.
Returns
A pointer to the he packet loss concealer context.
Definition at line 244 of file plc.c.
 {
    memset(s, 0, sizeof(*s));
    return s;
 }
plc_rx()
int plc_rx (plc_state_t * s, int16_t amp[], int len)
Process a block of received audio samples.
Process a block of received audio samples.
Parameters
s The packet loss concealer context.
amp The audio sample buffer.
len The number of samples in the buffer.
Returns
The number of samples in the buffer.
Definition at line 132 of file plc.c.
References ATTENUATION_INCREMENT, fsaturate(), len(), plc_state_t::missing_samples, plc_state_t::pitch, plc_state_t::pitch_offset, plc_state_t::pitchbuf, and save_history().
Referenced by adjust_frame_for_plc().
 {
    int i;
    int pitch_overlap;
    float old_step;
    float new_step;
    float old_weight;
    float new_weight;
    float gain;
    if (s->missing_samples) {
       /* Although we have a real signal, we need to smooth it to fit well
       with the synthetic signal we used for the previous block */
       /* The start of the real data is overlapped with the next 1/4 cycle
          of the synthetic data. */
       pitch_overlap = s->pitch >> 2;
       if (pitch_overlap > len)
          pitch_overlap = len;
       gain = 1.0 - s->missing_samples*ATTENUATION_INCREMENT;
       if (gain < 0.0)
          gain = 0.0;
       new_step = 1.0/pitch_overlap;
       old_step = new_step*gain;
       new_weight = new_step;
       old_weight = (1.0 - new_step)*gain;
       for (i = 0; i < pitch_overlap; i++) {
          amp[i] = fsaturate(old_weight * s->pitchbuf[s->pitch_offset] + new_weight * amp[i]);
          if (++s->pitch_offset >= s->pitch)
             s->pitch_offset = 0;
          new_weight += new_step;
          old_weight -= old_step;
          if (old_weight < 0.0)
             old_weight = 0.0;
       }
       s->missing_samples = 0;
    }
    save_history(s, amp, len);
    return len;
 }