Asterisk - The Open Source Telephony Project: prometheus_internal.h File Reference
prometheus_internal.h File Reference
Functions
int bridge_metrics_init (void)
Initialize bridge metrics.
int channel_metrics_init (void)
Initialize channel metrics.
int cli_init (void)
Initialize CLI command.
int endpoint_metrics_init (void)
Initialize endpoint metrics.
int pjsip_outbound_registration_metrics_init (void)
Initialize PJSIP outbound registration metrics.
int64_t prometheus_last_scrape_duration_get (void)
Retrieve the amount of time it took to perform the last scrape.
struct timeval prometheus_last_scrape_time_get (void)
Retrieve the timestamp when the last scrape occurred.
struct ast_str * prometheus_scrape_to_string (void)
Get the raw output of what a scrape would produce.
Function Documentation
bridge_metrics_init()
int bridge_metrics_init (void)
Initialize bridge metrics.
Return values
0 success
-1 error
Definition at line 183 of file bridges.c.
References prometheus_callback_register(), and prometheus_metrics_provider_register().
Referenced by load_module().
 {
    prometheus_metrics_provider_register(&provider);
    prometheus_callback_register(&bridges_callback);
    return 0;
 }
channel_metrics_init()
int channel_metrics_init (void)
Initialize channel metrics.
Return values
0 success
-1 error
Definition at line 241 of file channels.c.
References prometheus_callback_register(), and prometheus_metrics_provider_register().
Referenced by load_module().
 {
    prometheus_metrics_provider_register(&provider);
    prometheus_callback_register(&channels_callback);
    return 0;
 }
cli_init()
int cli_init (void)
Initialize CLI command.
Return values
0 success
-1 error
Definition at line 137 of file res/prometheus/cli.c.
References ARRAY_LEN, ast_cli_register_multiple, and prometheus_metrics_provider_register().
Referenced by load_module().
 {
    prometheus_metrics_provider_register(&provider);
    ast_cli_register_multiple(cli_prometheus, ARRAY_LEN(cli_prometheus));
    return 0;
 }
endpoint_metrics_init()
int endpoint_metrics_init (void)
Initialize endpoint metrics.
Return values
0 success
-1 error
Definition at line 198 of file res/prometheus/endpoints.c.
References prometheus_callback_register(), and prometheus_metrics_provider_register().
Referenced by load_module().
 {
    prometheus_metrics_provider_register(&provider);
    prometheus_callback_register(&endpoints_callback);
    return 0;
 }
pjsip_outbound_registration_metrics_init()
int pjsip_outbound_registration_metrics_init (void)
Initialize PJSIP outbound registration metrics.
Return values
0 success
-1 error
Definition at line 342 of file pjsip_outbound_registrations.c.
References ao2_cleanup, ast_sip_get_sorcery(), ast_sorcery_instance_observer_add(), ast_sorcery_instance_observer_remove(), ast_sorcery_observer_add(), ast_sorcery_observer_remove(), ast_system_registry_type(), ast_system_topic(), cleanup(), NULL, prometheus_metrics_provider_register(), registry_message_cb(), stasis_message_router_add(), and stasis_message_router_create.
Referenced by load_module().
 {
    prometheus_metrics_provider_register(&provider);
 #ifdef HAVE_PJPROJECT
    router = stasis_message_router_create(ast_system_topic());
    if (!router) {
       goto cleanup;
    }
    if (stasis_message_router_add(router, ast_system_registry_type(), registry_message_cb, NULL)) {
       goto cleanup;
    }
    if (ast_sorcery_instance_observer_add(ast_sip_get_sorcery(), &observer_callbacks_registrations)) {
       goto cleanup;
    }
    if (ast_sorcery_observer_add(ast_sip_get_sorcery(), "registration", &registration_observer)) {
       goto cleanup;
    }
 #endif /* HAVE_PJPROJECT */
    return 0;
 #ifdef HAVE_PJPROJECT
 cleanup:
    ao2_cleanup(router);
    router = NULL;
    ast_sorcery_instance_observer_remove(ast_sip_get_sorcery(), &observer_callbacks_registrations);
    ast_sorcery_observer_remove(ast_sip_get_sorcery(), "registration", &registration_observer);
    return -1;
 #endif /* HAVE_PJPROJECT */
 }
prometheus_last_scrape_duration_get()
int64_t prometheus_last_scrape_duration_get (void)
Retrieve the amount of time it took to perform the last scrape.
Time returned is in milliseconds
Return values
The scrape duration, in milliseconds
Definition at line 701 of file res_prometheus.c.
References prometheus_metric::value.
Referenced by prometheus_show_status().
 {
    int64_t duration;
    if (sscanf(core_scrape_metric.value, "%" PRIu64, &duration) != 1) {
       return -1;
    }
    return duration;
 }
prometheus_last_scrape_time_get()
struct timeval prometheus_last_scrape_time_get (void)
Retrieve the timestamp when the last scrape occurred.
Return values
The time when the last scrape occurred
Definition at line 712 of file res_prometheus.c.
References lock, SCOPED_MUTEX, and scrape_lock.
Referenced by prometheus_show_status().
 {
    SCOPED_MUTEX(lock, &scrape_lock);
    return last_scrape;
 }
prometheus_scrape_to_string()
struct ast_str* prometheus_scrape_to_string (void)
Get the raw output of what a scrape would produce.
It can be useful to dump what a scrape will look like. This function returns the raw string representation of the metrics.
Return values
NULL on error
Malloc'd ast_str on success
Definition at line 685 of file res_prometheus.c.
References ast_mutex_lock, ast_mutex_unlock, ast_str_create, NULL, scrape_lock, and scrape_metrics().
Referenced by prometheus_show_metrics().
 {
    struct ast_str *response;
    response = ast_str_create(512);
    if (!response) {
       return NULL;
    }
    ast_mutex_lock(&scrape_lock);
    scrape_metrics(&response);
    ast_mutex_unlock(&scrape_lock);
    return response;
 }