Asterisk - The Open Source Telephony Project: func_frame_drop.c File Reference
func_frame_drop.c File Reference
Module: Dial plan functions
Function that drops specified frames from channels.
#include "asterisk.h"
#include "asterisk/module.h"
#include "asterisk/channel.h"
#include "asterisk/pbx.h"
#include "asterisk/framehook.h"
Data Structures
struct frame_drop_data
Enumerations
enum direction { TX = 0, RX }
Functions
AST_MODULE_INFO_STANDARD_EXTENDED (ASTERISK_GPL_KEY, "Function to drop frames on a channel.")
static void datastore_destroy_cb (void *data)
static int frame_drop_helper (struct ast_channel *chan, const char *cmd, char *data, const char *value)
static void hook_destroy_cb (void *framedata)
static struct ast_frame * hook_event_cb (struct ast_channel *chan, struct ast_frame *frame, enum ast_framehook_event event, void *data)
static int load_module (void)
static int unload_module (void)
Variables
struct {
const char * str
int type
} controlframetype2str []
static const struct ast_datastore_info frame_drop_datastore
static struct ast_custom_function frame_drop_function
struct {
const char * str
enum ast_frame_type type
} frametype2str []
Detailed Description
Function that drops specified frames from channels.
Author
Naveen Albert aster.nosp@m.isk@.nosp@m.phrea.nosp@m.knet.nosp@m..org
Definition in file func_frame_drop.c.
Enumeration Type Documentation
direction
enum direction
Enumerator
TX
RX
Definition at line 137 of file func_frame_drop.c.
                {
     TX = 0,
     RX,
 };
Function Documentation
AST_MODULE_INFO_STANDARD_EXTENDED()
AST_MODULE_INFO_STANDARD_EXTENDED (ASTERISK_GPL_KEY , "Function to drop frames on a channel.")
Referenced by load_module().
datastore_destroy_cb()
static void datastore_destroy_cb (void * data) static
Definition at line 148 of file func_frame_drop.c.
References ast_free.
{
    ast_free(data);
 }
frame_drop_helper()
static int frame_drop_helper (struct ast_channel * chan, const char * cmd, char * data, const char * value) static
Definition at line 203 of file func_frame_drop.c.
References ARRAY_LEN, ast_calloc, ast_channel_datastore_add(), ast_channel_datastore_find(), ast_channel_datastore_remove(), ast_channel_lock, ast_channel_unlock, ast_datastore_alloc, ast_datastore_free(), ast_framehook_attach(), ast_framehook_detach(), AST_FRAMEHOOK_INTERFACE_VERSION, ast_free, ast_malloc, controlframetype2str, frame_drop_data::controlvalues, ast_datastore::data, ast_framehook_interface::data, frametype2str, hook_destroy_cb(), hook_event_cb(), id, frame_drop_data::list_type, NULL, RX, str, strcasestr(), TX, frame_drop_data::values, and ast_framehook_interface::version.
 {
    char *buffer;
    struct frame_drop_data *framedata;
    struct ast_datastore *datastore = NULL;
    struct ast_framehook_interface interface = {
       .version = AST_FRAMEHOOK_INTERFACE_VERSION,
       .event_cb = hook_event_cb,
       .destroy_cb = hook_destroy_cb,
    };
    int i = 0;
    if (!(framedata = ast_calloc(1, sizeof(*framedata)))) {
       return 0;
    }
    interface.data = framedata;
    if (!strcasecmp(data, "RX")) {
       framedata->list_type = RX;
    } else {
       framedata->list_type = TX;
    }
    buffer = ast_malloc(sizeof(value) + 3); /* leading and trailing comma and null terminator */
    snprintf(buffer, sizeof(value) + 2, ",%s,", value);
    for (i = 0; i < ARRAY_LEN(frametype2str); i++) {
       if (strcasestr(value, frametype2str[i].str)) {
          framedata->values[i] = 1;
       }
    }
    for (i = 0; i < ARRAY_LEN(controlframetype2str); i++) {
       if (strcasestr(value, controlframetype2str[i].str)) {
          framedata->controlvalues[i] = 1;
       }
    }
    ast_free(buffer);
    ast_channel_lock(chan);
    i = ast_framehook_attach(chan, &interface);
    if (i >= 0) {
       int *id;
       if ((datastore = ast_channel_datastore_find(chan, &frame_drop_datastore, NULL))) {
          id = datastore->data;
          ast_framehook_detach(chan, *id);
          ast_channel_datastore_remove(chan, datastore);
          ast_datastore_free(datastore);
       }
       if (!(datastore = ast_datastore_alloc(&frame_drop_datastore, NULL))) {
          ast_framehook_detach(chan, i);
          ast_channel_unlock(chan);
          return 0;
       }
       if (!(id = ast_calloc(1, sizeof(int)))) {
          ast_datastore_free(datastore);
          ast_framehook_detach(chan, i);
          ast_channel_unlock(chan);
          return 0;
       }
       *id = i; /* Store off the id. The channel is still locked so it is safe to access this ptr. */
       datastore->data = id;
       ast_channel_datastore_add(chan, datastore);
    }
    ast_channel_unlock(chan);
    return 0;
 }
hook_destroy_cb()
static void hook_destroy_cb (void * framedata) static
Definition at line 157 of file func_frame_drop.c.
References ast_free.
Referenced by frame_drop_helper().
 {
    ast_free(framedata);
 }
hook_event_cb()
static struct ast_frame* hook_event_cb (struct ast_channel * chan, struct ast_frame * frame, enum ast_framehook_event event, void * data) static
Definition at line 162 of file func_frame_drop.c.
References ARRAY_LEN, AST_FRAME_CONTROL, AST_FRAMEHOOK_EVENT_READ, AST_FRAMEHOOK_EVENT_WRITE, ast_frfree, ast_null_frame, controlframetype2str, frame_drop_data::controlvalues, ast_frame::frametype, frametype2str, ast_frame_subclass::integer, frame_drop_data::list_type, RX, ast_frame::subclass, TX, and frame_drop_data::values.
Referenced by frame_drop_helper().
 {
    int i;
    int drop_frame = 0;
    struct frame_drop_data *framedata = data;
    if (!frame) {
       return frame;
    }
    if (!((event == AST_FRAMEHOOK_EVENT_WRITE && framedata->list_type == TX) ||
       (event == AST_FRAMEHOOK_EVENT_READ && framedata->list_type == RX))) {
       return frame;
    }
    if (frame->frametype == AST_FRAME_CONTROL) {
       for (i = 0; i < ARRAY_LEN(controlframetype2str); i++) {
          if (frame->subclass.integer == controlframetype2str[i].type) {
             if (framedata->controlvalues[i]) {
                drop_frame = 1;
             }
             break;
          }
       }
    } else {
       for (i = 0; i < ARRAY_LEN(frametype2str); i++) {
          if (frame->frametype == frametype2str[i].type) {
             if (framedata->values[i]) {
                drop_frame = 1;
             }
             break;
          }
       }
    }
    if (drop_frame) {
       ast_frfree(frame);
       frame = &ast_null_frame;
    }
    return frame;
 }
load_module()
static int load_module (void) static
Definition at line 285 of file func_frame_drop.c.
References ast_custom_function_register, AST_MODULE_INFO_STANDARD_EXTENDED(), AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, and ASTERISK_GPL_KEY.
 {
    int res = ast_custom_function_register(&frame_drop_function);
    return res ? AST_MODULE_LOAD_DECLINE : AST_MODULE_LOAD_SUCCESS;
 }
unload_module()
static int unload_module (void) static
Definition at line 280 of file func_frame_drop.c.
References ast_custom_function_unregister().
 {
    return ast_custom_function_unregister(&frame_drop_function);
 }
Variable Documentation
controlframetype2str
struct { ... } controlframetype2str[]
Referenced by frame_drop_helper(), and hook_event_cb().
frame_drop_datastore
const struct ast_datastore_info frame_drop_datastore static
Initial value:
= {
   .type = "framedrop",
   .destroy = datastore_destroy_cb
}
Definition at line 152 of file func_frame_drop.c.
frame_drop_function
struct ast_custom_function frame_drop_function static
Initial value:
= {
   .name = "FRAME_DROP",
   .write = frame_drop_helper,
}
Definition at line 275 of file func_frame_drop.c.
frametype2str
struct { ... } frametype2str[]
Referenced by frame_drop_helper(), and hook_event_cb().
str
const char* str
Definition at line 98 of file func_frame_drop.c.
Referenced by frame_drop_helper().
type
int type
Definition at line 97 of file func_frame_drop.c.