Asterisk - The Open Source Telephony Project: sounds.c File Reference
sounds.c File Reference
Sound file format and description index.
#include "asterisk.h"
#include <dirent.h>
#include <sys/stat.h>
#include "asterisk/utils.h"
#include "asterisk/lock.h"
#include "asterisk/format.h"
#include "asterisk/format_cap.h"
#include "asterisk/paths.h"
#include "asterisk/media_index.h"
#include "asterisk/sounds_index.h"
#include "asterisk/file.h"
#include "asterisk/cli.h"
#include "asterisk/module.h"
#include "asterisk/stasis_message_router.h"
#include "asterisk/stasis_system.h"
Macros
#define LANGUAGE_BUCKETS 7
The number of buckets to be used for storing language-keyed objects.
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
struct ast_media_index * ast_sounds_get_index (void)
Get the sounds index.
struct ast_media_index * ast_sounds_get_index_for_file (const char *filename)
Get the index for a specific sound file.
static struct ao2_container * get_languages (void)
Get the languages in which sound files are available.
static char * handle_cli_sound_show (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
Show details about a sound available in the system.
static char * handle_cli_sounds_show (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
Show a list of sounds available on the system.
static int load_module (void)
static int show_sound_info_cb (void *obj, void *arg, void *data, int flags)
static int show_sounds_cb (void *obj, void *arg, int flags)
static int sound_sorter (const void *obj_left, const void *obj_right, int flags)
static int unload_module (void)
static int update_index_cb (void *obj, void *arg, void *data, int flags)
Callback to process an individual language directory or subdirectory.
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_GLOBAL_SYMBOLS | AST_MODFLAG_LOAD_ORDER , .description = "Sounds Index" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_APP_DEPEND + 1, }
static const struct ast_module_info * ast_module_info = &__mod_info
static struct ast_cli_entry cli_sounds []
Struct for registering CLI commands.
Detailed Description
Sound file format and description index.
Definition in file sounds.c.
Macro Definition Documentation
LANGUAGE_BUCKETS
#define LANGUAGE_BUCKETS 7
The number of buckets to be used for storing language-keyed objects.
Definition at line 46 of file sounds.c.
Referenced by get_languages().
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 354 of file sounds.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 354 of file sounds.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 354 of file sounds.c.
ast_sounds_get_index()
struct ast_media_index* ast_sounds_get_index (void)
Get the sounds index.
Return values
sounds index (must be ao2_cleanup()'ed)
NULL on failure
Definition at line 308 of file sounds.c.
References ast_sounds_get_index_for_file(), and NULL.
Referenced by ast_ari_sounds_list(), handle_cli_sound_show(), and handle_cli_sounds_show().
 {
    return ast_sounds_get_index_for_file(NULL);
 }
ast_sounds_get_index_for_file()
struct ast_media_index* ast_sounds_get_index_for_file (const char * filename)
Get the index for a specific sound file.
Since
13.25.0
16.2.0
Parameters
filename Sound file name without extension
Return values
sounds index (must be ao2_cleanup()'ed)
NULL on failure
Definition at line 313 of file sounds.c.
References ao2_callback_data, ao2_ref, ast_config_AST_DATA_DIR, ast_free, ast_media_index_create(), AST_MODFLAG_GLOBAL_SYMBOLS, AST_MODFLAG_LOAD_ORDER, AST_MODPRI_APP_DEPEND, AST_MODULE_INFO(), AST_MODULE_SUPPORT_CORE, ast_str_buffer(), ast_str_create, ast_str_set(), ASTERISK_GPL_KEY, get_languages(), load_module(), NULL, unload_module(), and update_index_cb().
Referenced by ast_ari_sounds_get(), ast_sounds_get_index(), and handle_cli_sound_show().
 {
    struct ast_str *sounds_dir = ast_str_create(64);
    struct ao2_container *languages;
    char *failed_index;
    struct ast_media_index *new_index;
    if (!sounds_dir) {
       return NULL;
    }
    ast_str_set(&sounds_dir, 0, "%s/sounds", ast_config_AST_DATA_DIR);
    new_index = ast_media_index_create(ast_str_buffer(sounds_dir));
    ast_free(sounds_dir);
    if (!new_index) {
       return NULL;
    }
    languages = get_languages();
    if (!languages) {
       ao2_ref(new_index, -1);
       return NULL;
    }
    failed_index = ao2_callback_data(languages, 0, update_index_cb, new_index, (void *)filename);
    ao2_ref(languages, -1);
    if (failed_index) {
       ao2_ref(failed_index, -1);
       ao2_ref(new_index, -1);
       new_index = NULL;
    }
    return new_index;
 }
get_languages()
static struct ao2_container* get_languages (void) static
Get the languages in which sound files are available.
Definition at line 49 of file sounds.c.
References ao2_cleanup, ao2_ref, ast_config_AST_DATA_DIR, ast_free, ast_log, ast_str_buffer(), ast_str_container_add(), ast_str_container_alloc, ast_str_create, ast_str_reset(), ast_str_set(), LANGUAGE_BUCKETS, LOG_ERROR, NULL, and RAII_VAR.
Referenced by ast_sounds_get_index_for_file().
 {
    RAII_VAR(struct ao2_container *, lang_dirs, NULL, ao2_cleanup);
    struct dirent* dent;
    DIR* srcdir;
    RAII_VAR(struct ast_str *, media_dir, ast_str_create(64), ast_free);
    RAII_VAR(struct ast_str *, variant_dir, ast_str_create(64), ast_free);
    lang_dirs = ast_str_container_alloc(LANGUAGE_BUCKETS);
    if (!media_dir || !lang_dirs) {
       return NULL;
    }
    ast_str_set(&media_dir, 0, "%s/sounds", ast_config_AST_DATA_DIR);
    srcdir = opendir(ast_str_buffer(media_dir));
    if (srcdir == NULL) {
       ast_log(LOG_ERROR, "Failed to open %s\n", ast_str_buffer(media_dir));
       return NULL;
    }
    while((dent = readdir(srcdir)) != NULL) {
       struct stat st;
       if(!strcmp(dent->d_name, ".") || !strcmp(dent->d_name, "..")) {
          continue;
       }
       ast_str_reset(variant_dir);
       ast_str_set(&variant_dir, 0, "%s/%s", ast_str_buffer(media_dir), dent->d_name);
       if (stat(ast_str_buffer(variant_dir), &st) < 0) {
          ast_log(LOG_ERROR, "Failed to stat %s\n", ast_str_buffer(variant_dir));
          continue;
       }
       if (S_ISDIR(st.st_mode)) {
          ast_str_container_add(lang_dirs, dent->d_name);
       }
    }
    closedir(srcdir);
    ao2_ref(lang_dirs, +1);
    return lang_dirs;
 }
handle_cli_sound_show()
static char* handle_cli_sound_show (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) static
Show details about a sound available in the system.
Definition at line 193 of file sounds.c.
References ao2_callback_data, ao2_cleanup, ao2_container_count(), ao2_iterator_destroy(), ao2_iterator_init(), ao2_iterator_next, ao2_ref, ast_cli_args::argc, ast_cli_args::argv, ast_cli(), ast_cli_completion_add(), ast_media_get_media(), ast_media_get_variants(), ast_sounds_get_index(), ast_sounds_get_index_for_file(), ast_strdup, CLI_FAILURE, CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::command, ast_cli_args::fd, NULL, OBJ_MULTIPLE, OBJ_NODATA, ast_cli_args::pos, show_sound_info_cb(), ast_cli_entry::usage, and ast_cli_args::word.
 {
    int length;
    struct ao2_iterator it_sounds;
    char *filename;
    struct ast_media_index *sounds_index;
    struct ao2_container *sound_files;
    switch (cmd) {
    case CLI_INIT:
       e->command = "core show sound";
       e->usage =
          "Usage: core show sound [soundid]\n"
          "       Shows information about the specified sound.\n";
       return NULL;
    case CLI_GENERATE:
       if (a->pos != 3) {
          return NULL;
       }
       sounds_index = ast_sounds_get_index();
       if (!sounds_index) {
          return NULL;
       }
       sound_files = ast_media_get_media(sounds_index);
       ao2_ref(sounds_index, -1);
       if (!sound_files) {
          return NULL;
       }
       length = strlen(a->word);
       it_sounds = ao2_iterator_init(sound_files, 0);
       while ((filename = ao2_iterator_next(&it_sounds))) {
          if (!strncasecmp(a->word, filename, length)) {
             if (ast_cli_completion_add(ast_strdup(filename))) {
                ao2_ref(filename, -1);
                break;
             }
          }
          ao2_ref(filename, -1);
       }
       ao2_iterator_destroy(&it_sounds);
       ao2_ref(sound_files, -1);
       return NULL;
    }
    if (a->argc == 4) {
       struct ao2_container *variants;
       sounds_index = ast_sounds_get_index_for_file(a->argv[3]);
       if (!sounds_index) {
          return NULL;
       }
       variants = ast_media_get_variants(sounds_index, a->argv[3]);
       if (!variants || !ao2_container_count(variants)) {
          ao2_ref(sounds_index, -1);
          ao2_cleanup(variants);
          ast_cli(a->fd, "ERROR: File %s not found in index\n", a->argv[3]);
          return CLI_FAILURE;
       }
       ast_cli(a->fd, "Indexed Information for %s:\n", a->argv[3]);
       ao2_callback_data(variants, OBJ_MULTIPLE | OBJ_NODATA, show_sound_info_cb, a, sounds_index);
       ao2_ref(sounds_index, -1);
       ao2_ref(variants, -1);
       return CLI_SUCCESS;
    }
    return CLI_SHOWUSAGE;
 }
handle_cli_sounds_show()
static char* handle_cli_sounds_show (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) static
Show a list of sounds available on the system.
Definition at line 144 of file sounds.c.
References AO2_ALLOC_OPT_LOCK_NOLOCK, ao2_callback, ao2_cleanup, ao2_container_alloc_rbtree, ao2_container_dup(), ao2_ref, ast_cli_args::argc, ast_cli(), ast_media_get_media(), ast_sounds_get_index(), CLI_FAILURE, CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::command, ast_cli_args::fd, NULL, OBJ_MULTIPLE, OBJ_NODATA, show_sounds_cb(), sound_sorter(), and ast_cli_entry::usage.
 {
    switch (cmd) {
    case CLI_INIT:
       e->command = "core show sounds";
       e->usage =
          "Usage: core show sounds\n"
          "       Shows a listing of sound files available on the system.\n";
       return NULL;
    case CLI_GENERATE:
       return NULL;
    }
    if (a->argc == 3) {
       struct ast_media_index *sounds_index = ast_sounds_get_index();
       struct ao2_container *sound_files;
       struct ao2_container *sorted;
       if (!sounds_index) {
          return CLI_FAILURE;
       }
       sound_files = ast_media_get_media(sounds_index);
       ao2_ref(sounds_index, -1);
       if (!sound_files) {
          return CLI_FAILURE;
       }
       sorted = ao2_container_alloc_rbtree(AO2_ALLOC_OPT_LOCK_NOLOCK, 0,
          sound_sorter, NULL);
       if (!sorted
          || ao2_container_dup(sorted, sound_files, 0)) {
          ao2_cleanup(sorted);
          ao2_cleanup(sound_files);
          return CLI_FAILURE;
       }
       ast_cli(a->fd, "Available audio files:\n");
       ao2_callback(sorted, OBJ_MULTIPLE | OBJ_NODATA, show_sounds_cb, a);
       ao2_ref(sorted, -1);
       ao2_ref(sound_files, -1);
       return CLI_SUCCESS;
    }
    return CLI_SHOWUSAGE;
 }
load_module()
static int load_module (void) static
Definition at line 282 of file sounds.c.
References ARRAY_LEN, ast_cli_register_multiple, AST_MODULE_LOAD_DECLINE, and AST_MODULE_LOAD_SUCCESS.
Referenced by ast_sounds_get_index_for_file().
 {
    int res;
    res = ast_cli_register_multiple(cli_sounds, ARRAY_LEN(cli_sounds));
    if (res) {
       return AST_MODULE_LOAD_DECLINE;
    }
    return AST_MODULE_LOAD_SUCCESS;
 }
show_sound_info_cb()
static int show_sound_info_cb (void * obj, void * arg, void * data, int flags) static
Definition at line 104 of file sounds.c.
References a, ao2_ref, ast_cli_args::argv, ast_cli(), ast_format_cap_count(), ast_format_cap_get_format(), ast_format_get_name(), ast_media_get_description(), ast_media_get_format_cap(), ast_strlen_zero, ast_cli_args::fd, format, and language.
Referenced by handle_cli_sound_show().
 {
    char *language = obj;
    struct ast_cli_args *a = arg;
    struct ast_format *format;
    int formats_shown = 0;
    struct ast_media_index *local_index = data;
    struct ast_format_cap *cap;
    const char *description = ast_media_get_description(local_index, a->argv[3], language);
    ast_cli(a->fd, "  Language %s:\n", language);
    if (!ast_strlen_zero(description)) {
       ast_cli(a->fd, "    Description: %s\n", description);
    }
    cap = ast_media_get_format_cap(local_index, a->argv[3], language);
    if (cap) {
       int x;
       for (x = 0; x < ast_format_cap_count(cap); x++) {
          format = ast_format_cap_get_format(cap, x);
          ast_cli(a->fd, "    Format: %s\n", ast_format_get_name(format));
          ao2_ref(format, -1);
          formats_shown = 1;
       }
       ao2_ref(cap, -1);
    }
    if (!formats_shown) {
       ast_cli(a->fd, "    No Formats Available\n");
    }
    return 0;
 }
show_sounds_cb()
static int show_sounds_cb (void * obj, void * arg, int flags) static
Definition at line 96 of file sounds.c.
References a, ast_cli(), ast_cli_args::fd, and name.
Referenced by handle_cli_sounds_show().
 {
    char *name = obj;
    struct ast_cli_args *a = arg;
    ast_cli(a->fd, "%s\n", name);
    return 0;
 }
sound_sorter()
static int sound_sorter (const void * obj_left, const void * obj_right, int flags) static
Definition at line 138 of file sounds.c.
Referenced by handle_cli_sounds_show().
 {
    return strcmp(obj_left, obj_right);
 }
unload_module()
static int unload_module (void) static
Definition at line 275 of file sounds.c.
References ARRAY_LEN, and ast_cli_unregister_multiple().
Referenced by ast_sounds_get_index_for_file().
 {
    ast_cli_unregister_multiple(cli_sounds, ARRAY_LEN(cli_sounds));
    return 0;
 }
update_index_cb()
static int update_index_cb (void * obj, void * arg, void * data, int flags) static
Callback to process an individual language directory or subdirectory.
Definition at line 295 of file sounds.c.
References ast_media_index_update_for_file(), CMP_MATCH, and ast_media_index::index.
Referenced by ast_sounds_get_index_for_file().
 {
    char *lang = obj;
    char *filename = data;
    struct ast_media_index *index = arg;
    if (ast_media_index_update_for_file(index, lang, filename)) {
       return CMP_MATCH;
    }
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_GLOBAL_SYMBOLS | AST_MODFLAG_LOAD_ORDER , .description = "Sounds Index" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_APP_DEPEND + 1, } static
Definition at line 354 of file sounds.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 354 of file sounds.c.
cli_sounds
struct ast_cli_entry cli_sounds[] static
Initial value:
= {
   { .handler =  handle_cli_sounds_show , .summary =  "Shows available sounds" ,},
   { .handler =  handle_cli_sound_show , .summary =  "Shows details about a specific sound" ,},
}
Struct for registering CLI commands.
Definition at line 270 of file sounds.c.