Asterisk - The Open Source Telephony Project: sounds_index.h File Reference
sounds_index.h File Reference
Sound file format and description indexer.
Functions
struct ast_media_index * ast_sounds_get_index (void)
Get the sounds index.
struct ast_media_index * ast_sounds_get_index_for_file (const char *filename)
Get the index for a specific sound file.
Detailed Description
Sound file format and description indexer.
Definition in file sounds_index.h.
Function Documentation
ast_sounds_get_index()
struct ast_media_index* ast_sounds_get_index (void)
Get the sounds index.
Return values
sounds index (must be ao2_cleanup()'ed)
NULL on failure
Definition at line 308 of file sounds.c.
References ast_sounds_get_index_for_file(), and NULL.
Referenced by ast_ari_sounds_list(), handle_cli_sound_show(), and handle_cli_sounds_show().
 {
    return ast_sounds_get_index_for_file(NULL);
 }
ast_sounds_get_index_for_file()
struct ast_media_index* ast_sounds_get_index_for_file (const char * filename)
Get the index for a specific sound file.
Since
13.25.0
16.2.0
Parameters
filename Sound file name without extension
Return values
sounds index (must be ao2_cleanup()'ed)
NULL on failure
Definition at line 313 of file sounds.c.
References ao2_callback_data, ao2_ref, ast_config_AST_DATA_DIR, ast_free, ast_media_index_create(), AST_MODFLAG_GLOBAL_SYMBOLS, AST_MODFLAG_LOAD_ORDER, AST_MODPRI_APP_DEPEND, AST_MODULE_INFO(), AST_MODULE_SUPPORT_CORE, ast_str_buffer(), ast_str_create, ast_str_set(), ASTERISK_GPL_KEY, get_languages(), load_module(), NULL, unload_module(), and update_index_cb().
Referenced by ast_ari_sounds_get(), ast_sounds_get_index(), and handle_cli_sound_show().
 {
    struct ast_str *sounds_dir = ast_str_create(64);
    struct ao2_container *languages;
    char *failed_index;
    struct ast_media_index *new_index;
    if (!sounds_dir) {
       return NULL;
    }
    ast_str_set(&sounds_dir, 0, "%s/sounds", ast_config_AST_DATA_DIR);
    new_index = ast_media_index_create(ast_str_buffer(sounds_dir));
    ast_free(sounds_dir);
    if (!new_index) {
       return NULL;
    }
    languages = get_languages();
    if (!languages) {
       ao2_ref(new_index, -1);
       return NULL;
    }
    failed_index = ao2_callback_data(languages, 0, update_index_cb, new_index, (void *)filename);
    ao2_ref(languages, -1);
    if (failed_index) {
       ao2_ref(failed_index, -1);
       ao2_ref(new_index, -1);
       new_index = NULL;
    }
    return new_index;
 }