Asterisk - The Open Source Telephony Project: res_sorcery_memory.c File Reference
res_sorcery_memory.c File Reference
Sorcery In-Memory Object Wizard.
#include "asterisk.h"
#include <regex.h>
#include "asterisk/module.h"
#include "asterisk/sorcery.h"
#include "asterisk/astobj2.h"
Data Structures
struct sorcery_memory_fields_cmp_params
Structure used for fields comparison.
Macros
#define OBJECT_BUCKETS 53
Number of buckets for sorcery objects.
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int load_module (void)
static void sorcery_memory_close (void *data)
static int sorcery_memory_cmp (void *obj, void *arg, int flags)
Comparator function for sorcery objects.
static int sorcery_memory_create (const struct ast_sorcery *sorcery, void *data, void *object)
static int sorcery_memory_delete (const struct ast_sorcery *sorcery, void *data, void *object)
static int sorcery_memory_fields_cmp (void *obj, void *arg, int flags)
static int sorcery_memory_hash (const void *obj, const int flags)
Hashing function for sorcery objects.
static void * sorcery_memory_open (const char *data)
static void * sorcery_memory_retrieve_fields (const struct ast_sorcery *sorcery, void *data, const char *type, const struct ast_variable *fields)
static void * sorcery_memory_retrieve_id (const struct ast_sorcery *sorcery, void *data, const char *type, const char *id)
static void sorcery_memory_retrieve_multiple (const struct ast_sorcery *sorcery, void *data, const char *type, struct ao2_container *objects, const struct ast_variable *fields)
static void sorcery_memory_retrieve_prefix (const struct ast_sorcery *sorcery, void *data, const char *type, struct ao2_container *objects, const char *prefix, const size_t prefix_len)
static void sorcery_memory_retrieve_regex (const struct ast_sorcery *sorcery, void *data, const char *type, struct ao2_container *objects, const char *regex)
static int sorcery_memory_update (const struct ast_sorcery *sorcery, void *data, void *object)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_GLOBAL_SYMBOLS | AST_MODFLAG_LOAD_ORDER , .description = "Sorcery In-Memory Object Wizard" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_REALTIME_DRIVER, }
static const struct ast_module_info * ast_module_info = &__mod_info
static struct ast_sorcery_wizard memory_object_wizard
Detailed Description
Sorcery In-Memory Object Wizard.
Author
Joshua Colp jcolp.nosp@m.@dig.nosp@m.ium.c.nosp@m.om
Definition in file res_sorcery_memory.c.
Macro Definition Documentation
OBJECT_BUCKETS
#define OBJECT_BUCKETS 53
Number of buckets for sorcery objects.
Definition at line 40 of file res_sorcery_memory.c.
Referenced by sorcery_memory_open().
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 282 of file res_sorcery_memory.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 282 of file res_sorcery_memory.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 282 of file res_sorcery_memory.c.
load_module()
static int load_module (void) static
Definition at line 262 of file res_sorcery_memory.c.
References AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, and ast_sorcery_wizard_register.
Referenced by unload_module().
 {
    if (ast_sorcery_wizard_register(&memory_object_wizard)) {
       return AST_MODULE_LOAD_DECLINE;
    }
    return AST_MODULE_LOAD_SUCCESS;
 }
sorcery_memory_close()
static void sorcery_memory_close (void * data) static
Definition at line 257 of file res_sorcery_memory.c.
References ao2_ref.
 {
    ao2_ref(data, -1);
 }
sorcery_memory_cmp()
static int sorcery_memory_cmp (void * obj, void * arg, int flags) static
Comparator function for sorcery objects.
Definition at line 98 of file res_sorcery_memory.c.
References ast_sorcery_object_get_id(), CMP_MATCH, CMP_STOP, and OBJ_KEY.
Referenced by sorcery_memory_open().
 {
    const char *id = arg;
    return !strcmp(ast_sorcery_object_get_id(obj), flags & OBJ_KEY ? id : ast_sorcery_object_get_id(arg)) ? CMP_MATCH | CMP_STOP : 0;
 }
sorcery_memory_create()
static int sorcery_memory_create (const struct ast_sorcery * sorcery, void * data, void * object) static
Definition at line 105 of file res_sorcery_memory.c.
References ao2_find, ao2_link_flags, ao2_lock, ao2_ref, ao2_unlock, ast_sorcery_object_get_id(), OBJ_KEY, and OBJ_NOLOCK.
 {
    void *existing;
    ao2_lock(data);
    existing = ao2_find(data, ast_sorcery_object_get_id(object), OBJ_KEY | OBJ_NOLOCK);
    if (existing) {
       ao2_ref(existing, -1);
       ao2_unlock(data);
       return -1;
    }
    ao2_link_flags(data, object, OBJ_NOLOCK);
    ao2_unlock(data);
    return 0;
 }
sorcery_memory_delete()
static int sorcery_memory_delete (const struct ast_sorcery * sorcery, void * data, void * object) static
Definition at line 244 of file res_sorcery_memory.c.
References ao2_cleanup, ao2_find, ast_sorcery_object_get_id(), OBJ_KEY, OBJ_UNLINK, and RAII_VAR.
 {
    RAII_VAR(void *, existing, ao2_find(data, ast_sorcery_object_get_id(object), OBJ_KEY | OBJ_UNLINK), ao2_cleanup);
    return existing ? 0 : -1;
 }
sorcery_memory_fields_cmp()
static int sorcery_memory_fields_cmp (void * obj, void * arg, int flags) static
Definition at line 125 of file res_sorcery_memory.c.
References ao2_link, ast_sorcery_object_get_id(), ast_sorcery_objectset_create, ast_variable_lists_match(), ast_variables_destroy(), CMP_MATCH, CMP_STOP, sorcery_memory_fields_cmp_params::container, sorcery_memory_fields_cmp_params::fields, NULL, sorcery_memory_fields_cmp_params::prefix, sorcery_memory_fields_cmp_params::prefix_len, RAII_VAR, sorcery_memory_fields_cmp_params::regex, and sorcery_memory_fields_cmp_params::sorcery.
Referenced by sorcery_memory_retrieve_fields(), sorcery_memory_retrieve_multiple(), sorcery_memory_retrieve_prefix(), and sorcery_memory_retrieve_regex().
 {
    const struct sorcery_memory_fields_cmp_params *params = arg;
    RAII_VAR(struct ast_variable *, objset, NULL, ast_variables_destroy);
    if (params->regex) {
       /* If a regular expression has been provided see if it matches, otherwise move on */
       if (!regexec(params->regex, ast_sorcery_object_get_id(obj), 0, NULL, 0)) {
          ao2_link(params->container, obj);
       }
       return 0;
    } else if (params->prefix) {
       if (!strncmp(params->prefix, ast_sorcery_object_get_id(obj), params->prefix_len)) {
          ao2_link(params->container, obj);
       }
       return 0;
    } else if (params->fields &&
        (!(objset = ast_sorcery_objectset_create(params->sorcery, obj)) ||
         (!ast_variable_lists_match(objset, params->fields, 0)))) {
       /* If we can't turn the object into an object set OR if differences exist between the fields
        * passed in and what are present on the object they are not a match.
        */
       return 0;
    }
    if (params->container) {
       ao2_link(params->container, obj);
       /* As multiple objects are being returned keep going */
       return 0;
    } else {
       /* Immediately stop and return, we only want a single object */
       return CMP_MATCH | CMP_STOP;
    }
 }
sorcery_memory_hash()
static int sorcery_memory_hash (const void * obj, const int flags) static
Hashing function for sorcery objects.
Definition at line 90 of file res_sorcery_memory.c.
References ast_sorcery_object_get_id(), ast_str_hash(), and OBJ_KEY.
Referenced by sorcery_memory_open().
 {
    const char *id = obj;
    return ast_str_hash(flags & OBJ_KEY ? id : ast_sorcery_object_get_id(obj));
 }
sorcery_memory_open()
static void * sorcery_memory_open (const char * data) static
Definition at line 251 of file res_sorcery_memory.c.
References AO2_ALLOC_OPT_LOCK_MUTEX, ao2_container_alloc_hash, NULL, OBJECT_BUCKETS, sorcery_memory_cmp(), and sorcery_memory_hash().
 {
    return ao2_container_alloc_hash(AO2_ALLOC_OPT_LOCK_MUTEX, 0, OBJECT_BUCKETS,
       sorcery_memory_hash, NULL, sorcery_memory_cmp);
 }
sorcery_memory_retrieve_fields()
static void * sorcery_memory_retrieve_fields (const struct ast_sorcery * sorcery, void * data, const char * type, const struct ast_variable * fields) static
Definition at line 161 of file res_sorcery_memory.c.
References ao2_callback, sorcery_memory_fields_cmp_params::fields, NULL, sorcery_memory_fields_cmp_params::sorcery, and sorcery_memory_fields_cmp().
 {
    struct sorcery_memory_fields_cmp_params params = {
       .sorcery = sorcery,
       .fields = fields,
       .container = NULL,
    };
    /* If no fields are present return nothing, we require *something* */
    if (!fields) {
       return NULL;
    }
    return ao2_callback(data, 0, sorcery_memory_fields_cmp, &params);
 }
sorcery_memory_retrieve_id()
static void * sorcery_memory_retrieve_id (const struct ast_sorcery * sorcery, void * data, const char * type, const char * id) static
Definition at line 177 of file res_sorcery_memory.c.
References ao2_find, and OBJ_KEY.
 {
    return ao2_find(data, id, OBJ_KEY);
 }
sorcery_memory_retrieve_multiple()
static void sorcery_memory_retrieve_multiple (const struct ast_sorcery * sorcery, void * data, const char * type, struct ao2_container * objects, const struct ast_variable * fields) static
Definition at line 182 of file res_sorcery_memory.c.
References ao2_callback, sorcery_memory_fields_cmp_params::fields, sorcery_memory_fields_cmp_params::sorcery, and sorcery_memory_fields_cmp().
 {
    struct sorcery_memory_fields_cmp_params params = {
       .sorcery = sorcery,
       .fields = fields,
       .container = objects,
    };
    ao2_callback(data, 0, sorcery_memory_fields_cmp, &params);
 }
sorcery_memory_retrieve_prefix()
static void sorcery_memory_retrieve_prefix (const struct ast_sorcery * sorcery, void * data, const char * type, struct ao2_container * objects, const char * prefix, const size_t prefix_len) static
Definition at line 214 of file res_sorcery_memory.c.
References ao2_callback, sorcery_memory_fields_cmp_params::prefix, sorcery_memory_fields_cmp_params::prefix_len, sorcery_memory_fields_cmp_params::sorcery, and sorcery_memory_fields_cmp().
 {
    struct sorcery_memory_fields_cmp_params params = {
       .sorcery = sorcery,
       .container = objects,
       .prefix = prefix,
       .prefix_len = prefix_len,
    };
    ao2_callback(data, 0, sorcery_memory_fields_cmp, &params);
 }
sorcery_memory_retrieve_regex()
static void sorcery_memory_retrieve_regex (const struct ast_sorcery * sorcery, void * data, const char * type, struct ao2_container * objects, const char * regex) static
Definition at line 193 of file res_sorcery_memory.c.
References ao2_callback, ast_strlen_zero, sorcery_memory_fields_cmp_params::sorcery, and sorcery_memory_fields_cmp().
 {
    regex_t expression;
    struct sorcery_memory_fields_cmp_params params = {
       .sorcery = sorcery,
       .container = objects,
       .regex = &expression,
    };
    if (ast_strlen_zero(regex)) {
       regex = ".";
    }
    if (regcomp(&expression, regex, REG_EXTENDED | REG_NOSUB)) {
       return;
    }
    ao2_callback(data, 0, sorcery_memory_fields_cmp, &params);
    regfree(&expression);
 }
sorcery_memory_update()
static int sorcery_memory_update (const struct ast_sorcery * sorcery, void * data, void * object) static
Definition at line 226 of file res_sorcery_memory.c.
References ao2_cleanup, ao2_find, ao2_link, ao2_lock, ao2_unlock, ast_sorcery_object_get_id(), NULL, OBJ_KEY, OBJ_UNLINK, and RAII_VAR.
 {
    RAII_VAR(void *, existing, NULL, ao2_cleanup);
    ao2_lock(data);
    if (!(existing = ao2_find(data, ast_sorcery_object_get_id(object), OBJ_KEY | OBJ_UNLINK))) {
       ao2_unlock(data);
       return -1;
    }
    ao2_link(data, object);
    ao2_unlock(data);
    return 0;
 }
unload_module()
static int unload_module (void) static
Definition at line 271 of file res_sorcery_memory.c.
References AST_MODFLAG_GLOBAL_SYMBOLS, AST_MODFLAG_LOAD_ORDER, AST_MODPRI_REALTIME_DRIVER, AST_MODULE_INFO(), AST_MODULE_SUPPORT_CORE, ast_sorcery_wizard_unregister(), ASTERISK_GPL_KEY, and load_module().
 {
    ast_sorcery_wizard_unregister(&memory_object_wizard);
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_GLOBAL_SYMBOLS | AST_MODFLAG_LOAD_ORDER , .description = "Sorcery In-Memory Object Wizard" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_REALTIME_DRIVER, } static
Definition at line 282 of file res_sorcery_memory.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 282 of file res_sorcery_memory.c.
memory_object_wizard
struct ast_sorcery_wizard memory_object_wizard static
Definition at line 54 of file res_sorcery_memory.c.