Asterisk - The Open Source Telephony Project: bridge.h File Reference
bridge.h File Reference
Bridging API.
#include "asterisk/bridge_features.h"
#include "asterisk/bridge_channel.h"
#include "asterisk/bridge_roles.h"
#include "asterisk/dsp.h"
#include "asterisk/uuid.h"
Data Structures
struct ast_bridge
Structure that contains information about a bridge.
struct ast_bridge_channels_list
struct ast_bridge_methods
Bridge virtual methods table definition.
struct ast_bridge_snapshot
Structure that contains a snapshot of information about a bridge.
struct ast_bridge_softmix
struct ast_bridge_video_mode
Data structure that defines a video source mode.
struct ast_bridge_video_sfu_data
This is used for selective forwarding unit configuration.
struct ast_bridge_video_single_src_data
This is used for both SINGLE_SRC mode to set what channel should be the current single video feed.
struct ast_bridge_video_talker_src_data
This is used for both SINGLE_SRC_TALKER mode to set what channel should be the current single video feed.
struct transfer_channel_data
AO2 object that wraps data for transfer_channel_cb.
Macros
#define ast_bridge_lock(bridge) _ast_bridge_lock(bridge, __FILE__, __PRETTY_FUNCTION__, __LINE__, #bridge)
Lock the bridge.
#define ast_bridge_lock_both(bridge1, bridge2)
Lock two bridges.
#define ast_bridge_trylock(bridge) _ast_bridge_trylock(bridge, __FILE__, __PRETTY_FUNCTION__, __LINE__, #bridge)
Try locking the bridge.
#define ast_bridge_unlock(bridge) _ast_bridge_unlock(bridge, __FILE__, __PRETTY_FUNCTION__, __LINE__, #bridge)
Unlock the bridge.
Typedefs
typedef void(* ast_bridge_destructor_fn) (struct ast_bridge *self)
Destroy the bridge.
typedef void(* ast_bridge_dissolving_fn) (struct ast_bridge *self)
The bridge is being dissolved.
typedef int(* ast_bridge_merge_priority_fn) (struct ast_bridge *self)
Get the merge priority of this bridge.
typedef void(* ast_bridge_notify_masquerade_fn) (struct ast_bridge *self, struct ast_bridge_channel *bridge_channel)
Notify the bridge that this channel was just masqueraded.
typedef void(* ast_bridge_pull_channel_fn) (struct ast_bridge *self, struct ast_bridge_channel *bridge_channel)
Pull this channel from the bridge.
typedef int(* ast_bridge_push_channel_fn) (struct ast_bridge *self, struct ast_bridge_channel *bridge_channel, struct ast_bridge_channel *swap)
Push this channel into the bridge.
typedef void(* transfer_channel_cb) (struct ast_channel *chan, struct transfer_channel_data *user_data, enum ast_transfer_type transfer_type)
Callback function type called during blind transfers.
Enumerations
enum ast_bridge_capability {
AST_BRIDGE_CAPABILITY_HOLDING = (1 << 0), AST_BRIDGE_CAPABILITY_EARLY = (1 << 1), AST_BRIDGE_CAPABILITY_NATIVE = (1 << 2), AST_BRIDGE_CAPABILITY_1TO1MIX = (1 << 3),
AST_BRIDGE_CAPABILITY_MULTIMIX = (1 << 4)
}
Capabilities for a bridge technology.
enum ast_bridge_impart_flags { AST_BRIDGE_IMPART_CHAN_MASK = (1 << 0), AST_BRIDGE_IMPART_CHAN_DEPARTABLE = (0 << 0), AST_BRIDGE_IMPART_CHAN_INDEPENDENT = (1 << 0), AST_BRIDGE_IMPART_INHIBIT_JOIN_COLP = (1 << 1) }
enum ast_bridge_join_flags { AST_BRIDGE_JOIN_PASS_REFERENCE = (1 << 0), AST_BRIDGE_JOIN_INHIBIT_JOIN_COLP = (1 << 1) }
enum ast_bridge_optimization {
AST_BRIDGE_OPTIMIZE_SWAP_TO_CHAN_BRIDGE, AST_BRIDGE_OPTIMIZE_SWAP_TO_PEER_BRIDGE, AST_BRIDGE_OPTIMIZE_MERGE_TO_CHAN_BRIDGE, AST_BRIDGE_OPTIMIZE_MERGE_TO_PEER_BRIDGE,
AST_BRIDGE_OPTIMIZE_PROHIBITED
}
Tells, if optimization is allowed, how the optimization would be performed.
enum ast_bridge_video_mode_type { AST_BRIDGE_VIDEO_MODE_NONE = 0, AST_BRIDGE_VIDEO_MODE_SINGLE_SRC, AST_BRIDGE_VIDEO_MODE_TALKER_SRC, AST_BRIDGE_VIDEO_MODE_SFU }
Video source modes.
enum ast_bridge_video_sfu_remb_behavior {
AST_BRIDGE_VIDEO_SFU_REMB_AVERAGE = 0, AST_BRIDGE_VIDEO_SFU_REMB_LOWEST, AST_BRIDGE_VIDEO_SFU_REMB_HIGHEST, AST_BRIDGE_VIDEO_SFU_REMB_AVERAGE_ALL,
AST_BRIDGE_VIDEO_SFU_REMB_LOWEST_ALL, AST_BRIDGE_VIDEO_SFU_REMB_HIGHEST_ALL, AST_BRIDGE_VIDEO_SFU_REMB_FORCE
}
REMB report behaviors.
enum ast_transfer_result { AST_BRIDGE_TRANSFER_SUCCESS, AST_BRIDGE_TRANSFER_NOT_PERMITTED, AST_BRIDGE_TRANSFER_INVALID, AST_BRIDGE_TRANSFER_FAIL }
enum ast_transfer_type { AST_BRIDGE_TRANSFER_SINGLE_PARTY, AST_BRIDGE_TRANSFER_MULTI_PARTY }
Functions
static void _ast_bridge_lock (struct ast_bridge *bridge, const char *file, const char *function, int line, const char *var)
static int _ast_bridge_trylock (struct ast_bridge *bridge, const char *file, const char *function, int line, const char *var)
static void _ast_bridge_unlock (struct ast_bridge *bridge, const char *file, const char *function, int line, const char *var)
struct ast_bridge * ast_bridge_base_new (uint32_t capabilities, unsigned int flags, const char *creator, const char *name, const char *id)
Create a new base class bridge.
int ast_bridge_depart (struct ast_channel *chan)
Depart a channel from a bridge.
int ast_bridge_destroy (struct ast_bridge *bridge, int cause)
Destroy a bridge.
void ast_bridge_features_remove (struct ast_bridge_features *features, enum ast_bridge_hook_remove_flags flags)
Remove marked bridge channel feature hooks.
struct ast_bridge * ast_bridge_find_by_id (const char *bridge_id)
Find bridge by id.
int ast_bridge_impart (struct ast_bridge *bridge, struct ast_channel *chan, struct ast_channel *swap, struct ast_bridge_features *features, enum ast_bridge_impart_flags flags) attribute_warn_unused_result
Impart a channel to a bridge (non-blocking)
int ast_bridge_is_video_src (struct ast_bridge *bridge, struct ast_channel *chan)
Determine if a channel is a video src for the bridge.
int ast_bridge_join (struct ast_bridge *bridge, struct ast_channel *chan, struct ast_channel *swap, struct ast_bridge_features *features, struct ast_bridge_tech_optimizations *tech_args, enum ast_bridge_join_flags flags)
Join a channel to a bridge (blocking)
int ast_bridge_kick (struct ast_bridge *bridge, struct ast_channel *chan)
Kick a channel from a bridge.
int ast_bridge_merge (struct ast_bridge *dst_bridge, struct ast_bridge *src_bridge, int merge_best_direction, struct ast_channel **kick_me, unsigned int num_kick)
Merge two bridges together.
void ast_bridge_merge_inhibit (struct ast_bridge *bridge, int request)
Adjust the bridge merge inhibit request count.
int ast_bridge_move (struct ast_bridge *dst_bridge, struct ast_bridge *src_bridge, struct ast_channel *chan, struct ast_channel *swap, int attempt_recovery)
Move a channel from one bridge to another.
void ast_bridge_notify_masquerade (struct ast_channel *chan)
Notify bridging that this channel was just masqueraded.
int ast_bridge_number_video_src (struct ast_bridge *bridge)
Returns the number of video sources currently active in the bridge.
struct ast_channel * ast_bridge_peer (struct ast_bridge *bridge, struct ast_channel *chan)
Get the channel's bridge peer only if the bridge is two-party.
struct ast_channel * ast_bridge_peer_nolock (struct ast_bridge *bridge, struct ast_channel *chan)
Get the channel's bridge peer only if the bridge is two-party.
struct ao2_container * ast_bridge_peers (struct ast_bridge *bridge)
Get a container of all channels in the bridge.
struct ao2_container * ast_bridge_peers_nolock (struct ast_bridge *bridge)
Get a container of all channels in the bridge.
int ast_bridge_queue_action (struct ast_bridge *bridge, struct ast_frame *action)
Put an action onto the specified bridge.
int ast_bridge_queue_everyone_else (struct ast_bridge *bridge, struct ast_bridge_channel *bridge_channel, struct ast_frame *frame)
Queue the given frame to everyone else.
int ast_bridge_remove (struct ast_bridge *bridge, struct ast_channel *chan)
Remove a channel from a bridge.
void ast_bridge_remove_video_src (struct ast_bridge *bridge, struct ast_channel *chan)
remove a channel as a source of video for the bridge.
void ast_bridge_set_binaural_active (struct ast_bridge *bridge, unsigned int binaural_active)
Activates the use of binaural signals in a conference bridge.
void ast_bridge_set_internal_sample_rate (struct ast_bridge *bridge, unsigned int sample_rate)
Adjust the internal mixing sample rate of a bridge used during multimix mode.
void ast_bridge_set_maximum_sample_rate (struct ast_bridge *bridge, unsigned int sample_rate)
Adjust the maximum mixing sample rate of a bridge used during multimix mode.
void ast_bridge_set_mixing_interval (struct ast_bridge *bridge, unsigned int mixing_interval)
Adjust the internal mixing interval of a bridge used during multimix mode.
void ast_bridge_set_remb_estimated_bitrate (struct ast_bridge *bridge, float estimated_bitrate)
Force the REMB report estimated bitrate to a specific max value.
void ast_bridge_set_remb_send_interval (struct ast_bridge *bridge, unsigned int remb_send_interval)
Set the interval at which a combined REMB frame will be sent to video sources.
void ast_bridge_set_send_sdp_label (struct ast_bridge *bridge, unsigned int send_sdp_label)
Controls whether to send a "label" attribute in each stream in an SDP.
void ast_bridge_set_sfu_video_mode (struct ast_bridge *bridge)
Set the bridge to be a selective forwarding unit.
void ast_bridge_set_single_src_video_mode (struct ast_bridge *bridge, struct ast_channel *video_src_chan)
Set a bridge to feed a single video source to all participants.
void ast_bridge_set_talker_src_video_mode (struct ast_bridge *bridge)
Set the bridge to pick the strongest talker supporting video as the single source video feed.
void ast_bridge_set_transfer_variables (struct ast_channel *chan, const char *value, int is_attended)
Set the relevant transfer variables for a single channel.
void ast_bridge_set_video_update_discard (struct ast_bridge *bridge, unsigned int video_update_discard)
Set the amount of time to discard subsequent video updates after a video update has been sent.
int ast_bridge_suspend (struct ast_bridge *bridge, struct ast_channel *chan)
Suspend a channel temporarily from a bridge.
struct ast_bridge * ast_bridge_transfer_acquire_bridge (struct ast_channel *chan)
Acquire the channel's bridge for transfer purposes.
enum ast_transfer_result ast_bridge_transfer_attended (struct ast_channel *to_transferee, struct ast_channel *to_transfer_target)
Attended transfer.
enum ast_transfer_result ast_bridge_transfer_blind (int is_external, struct ast_channel *transferer, const char *exten, const char *context, transfer_channel_cb new_channel_cb, void *user_data)
Blind transfer target to the extension and context provided.
int ast_bridge_unreal_optimize_out (struct ast_channel *chan, struct ast_channel *peer, struct ast_unreal_pvt *pvt)
Check and optimize out the unreal channels between bridges.
int ast_bridge_unsuspend (struct ast_bridge *bridge, struct ast_channel *chan)
Unsuspend a channel from a bridge.
void ast_bridge_update_talker_src_video_mode (struct ast_bridge *bridge, struct ast_channel *chan, int talker_energy, int is_keyfame)
Update information about talker energy for talker src video mode.
void ast_bridge_vars_set (struct ast_channel *chan, const char *name, const char *pvtid)
Sets BRIDGECHANNEL and BRIDGEPVTCALLID for a channel.
const char * ast_bridge_video_mode_to_string (enum ast_bridge_video_mode_type video_mode)
Converts an enum representation of a bridge video mode to string.
struct ao2_container * ast_bridges (void)
Returns the global bridges container.
enum ast_bridge_optimization ast_bridges_allow_optimization (struct ast_bridge *chan_bridge, struct ast_bridge *peer_bridge)
Determine if bridges allow for optimization to occur betweem them.
void ast_brige_set_remb_behavior (struct ast_bridge *bridge, enum ast_bridge_video_sfu_remb_behavior behavior)
Set the REMB report generation behavior on a bridge.
Variables
struct ast_bridge_methods ast_bridge_base_v_table
Bridge base class virtual method table.
Detailed Description
Bridging API.
Author
Richard Mudgett rmudg.nosp@m.ett@.nosp@m.digiu.nosp@m.m.co.nosp@m.m
Joshua Colp jcolp.nosp@m.@dig.nosp@m.ium.c.nosp@m.om Bridging API
See Also:
CREDITS
Definition in file bridge.h.
Macro Definition Documentation
ast_bridge_lock
#define ast_bridge_lock (bridge) _ast_bridge_lock(bridge, __FILE__, __PRETTY_FUNCTION__, __LINE__, #bridge)
Lock the bridge.
Parameters
bridge Bridge to lock
Returns
Nothing
Definition at line 480 of file bridge.h.
Referenced by ast_ari_bridges_clear_video_source(), ast_ari_bridges_create(), ast_ari_bridges_create_with_id(), ast_bridge_basic_set_flags(), ast_bridge_channel_lock_bridge(), ast_bridge_destroy(), ast_bridge_get_snapshot(), ast_bridge_get_snapshot_by_uniqueid(), ast_bridge_is_video_src(), ast_bridge_join(), ast_bridge_kick(), ast_bridge_merge_inhibit(), ast_bridge_number_video_src(), ast_bridge_peer(), ast_bridge_peers(), ast_bridge_remove(), ast_bridge_remove_video_src(), ast_bridge_set_binaural_active(), ast_bridge_set_internal_sample_rate(), ast_bridge_set_maximum_sample_rate(), ast_bridge_set_mixing_interval(), ast_bridge_set_remb_estimated_bitrate(), ast_bridge_set_remb_send_interval(), ast_bridge_set_send_sdp_label(), ast_bridge_set_sfu_video_mode(), ast_bridge_set_single_src_video_mode(), ast_bridge_set_talker_src_video_mode(), ast_bridge_set_video_update_discard(), ast_bridge_suspend(), ast_bridge_transfer_attended(), ast_bridge_transfer_blind(), ast_bridge_unsuspend(), ast_bridge_update_talker_src_video_mode(), ast_brige_set_remb_behavior(), AST_TEST_DEFINE(), ast_unreal_channel_push_to_bridge(), bridge_action_bridge(), bridge_basic_change_personality(), bridge_channel_internal_join(), bridge_channel_snapshot_pair_init(), bridge_impart_internal(), bridge_manager_service(), bridge_queue_action_nodup(), bridge_register(), bridge_set_video_source_cb(), complete_bridge_participant(), conf_moh_start(), conf_moh_stop(), destroy_bridge(), handle_bridge_kick_channel(), native_rtp_framehook(), play_uri(), send_conf_stasis(), send_conf_stasis_snapshots(), softmix_mixing_loop(), and softmix_mixing_thread().
ast_bridge_lock_both
#define ast_bridge_lock_both (bridge1, bridge2)
Lock two bridges.
Definition at line 500 of file bridge.h.
Referenced by ast_bridge_add_channel(), ast_bridge_merge(), ast_bridge_move(), ast_bridge_transfer_attended(), bridge_merge(), and bridge_move().
ast_bridge_trylock
#define ast_bridge_trylock (bridge) _ast_bridge_trylock(bridge, __FILE__, __PRETTY_FUNCTION__, __LINE__, #bridge)
Try locking the bridge.
Parameters
bridge Bridge to try locking
Return values
0 on success.
non-zero on error.
Definition at line 467 of file bridge.h.
Referenced by optimize_lock_chan_stack(), and optimize_lock_peer_stack().
ast_bridge_unlock
#define ast_bridge_unlock (bridge) _ast_bridge_unlock(bridge, __FILE__, __PRETTY_FUNCTION__, __LINE__, #bridge)
Unlock the bridge.
Parameters
bridge Bridge to unlock
Returns
Nothing
Definition at line 493 of file bridge.h.
Referenced by action_toggle_binaural(), agent_alert(), ast_ari_bridges_clear_video_source(), ast_ari_bridges_create(), ast_ari_bridges_create_with_id(), ast_bridge_add_channel(), ast_bridge_basic_set_flags(), ast_bridge_channel_feature_digit(), ast_bridge_channel_lock_bridge(), ast_bridge_channel_merge_inhibit(), ast_bridge_destroy(), ast_bridge_get_snapshot(), ast_bridge_get_snapshot_by_uniqueid(), ast_bridge_is_video_src(), ast_bridge_join(), ast_bridge_kick(), ast_bridge_merge(), ast_bridge_merge_inhibit(), ast_bridge_move(), ast_bridge_notify_masquerade(), ast_bridge_number_video_src(), ast_bridge_peer(), ast_bridge_peers(), ast_bridge_remove(), ast_bridge_remove_video_src(), ast_bridge_set_binaural_active(), ast_bridge_set_internal_sample_rate(), ast_bridge_set_maximum_sample_rate(), ast_bridge_set_mixing_interval(), ast_bridge_set_remb_estimated_bitrate(), ast_bridge_set_remb_send_interval(), ast_bridge_set_send_sdp_label(), ast_bridge_set_sfu_video_mode(), ast_bridge_set_single_src_video_mode(), ast_bridge_set_talker_src_video_mode(), ast_bridge_set_video_update_discard(), ast_bridge_suspend(), ast_bridge_transfer_attended(), ast_bridge_transfer_blind(), ast_bridge_unreal_optimize_out(), ast_bridge_unsuspend(), ast_bridge_update_talker_src_video_mode(), ast_brige_set_remb_behavior(), AST_TEST_DEFINE(), ast_unreal_channel_push_to_bridge(), attended_transfer_bridge(), basic_hangup_hook(), bridge_action_bridge(), bridge_basic_change_personality(), bridge_channel_handle_control(), bridge_channel_internal_join(), bridge_channel_snapshot_pair_init(), bridge_channel_suspend(), bridge_channel_unsuspend(), bridge_channel_wait(), bridge_channel_write_frame(), bridge_handle_trip(), bridge_impart_internal(), bridge_manager_service(), bridge_merge(), bridge_move(), bridge_queue_action_nodup(), bridge_register(), bridge_set_video_source_cb(), check_binaural_position_change(), complete_bridge_participant(), conf_moh_start(), conf_moh_stop(), deferred_action(), destroy_bridge(), feature_automixmonitor(), feature_automonitor(), handle_bridge_kick_channel(), native_rtp_framehook(), optimize_lock_chan_stack(), optimize_lock_peer_stack(), parking_blind_transfer_park(), play_uri(), send_conf_stasis(), send_conf_stasis_snapshots(), softmix_mixing_loop(), and softmix_mixing_thread().
Typedef Documentation
ast_bridge_destructor_fn
typedef void(* ast_bridge_destructor_fn) (struct ast_bridge *self)
Destroy the bridge.
Parameters
self Bridge to operate upon.
Returns
Nothing
Definition at line 178 of file bridge.h.
ast_bridge_dissolving_fn
typedef void(* ast_bridge_dissolving_fn) (struct ast_bridge *self)
The bridge is being dissolved.
Parameters
self Bridge to operate upon.
The bridge is being dissolved. Remove any external references to the bridge so it can be destroyed.
Note
On entry, self must NOT be locked.
Returns
Nothing
Definition at line 193 of file bridge.h.
ast_bridge_merge_priority_fn
typedef int(* ast_bridge_merge_priority_fn) (struct ast_bridge *self)
Get the merge priority of this bridge.
Parameters
self Bridge to operate upon.
Note
On entry, self is already locked.
Returns
Merge priority
Definition at line 257 of file bridge.h.
ast_bridge_notify_masquerade_fn
typedef void(* ast_bridge_notify_masquerade_fn) (struct ast_bridge *self, struct ast_bridge_channel *bridge_channel)
Notify the bridge that this channel was just masqueraded.
Parameters
self Bridge to operate upon.
bridge_channel Bridge channel that was masqueraded.
A masquerade just happened to this channel. The bridge needs to re-evaluate this a channel in the bridge.
Note
On entry, self is already locked.
Returns
Nothing
Definition at line 246 of file bridge.h.
ast_bridge_pull_channel_fn
typedef void(* ast_bridge_pull_channel_fn) (struct ast_bridge *self, struct ast_bridge_channel *bridge_channel)
Pull this channel from the bridge.
Parameters
self Bridge to operate upon.
bridge_channel Bridge channel to pull.
Remove any channel hooks controlled by the bridge. Release any resources held by bridge_channel->bridge_pvt and release bridge_channel->bridge_pvt.
Note
On entry, self is already locked.
Returns
Nothing
Definition at line 230 of file bridge.h.
ast_bridge_push_channel_fn
typedef int(* ast_bridge_push_channel_fn) (struct ast_bridge *self, struct ast_bridge_channel *bridge_channel, struct ast_bridge_channel *swap)
Push this channel into the bridge.
Parameters
self Bridge to operate upon.
bridge_channel Bridge channel to push.
swap Bridge channel to swap places with if not NULL.
Setup any channel hooks controlled by the bridge. Allocate bridge_channel->bridge_pvt and initialize any resources put in bridge_channel->bridge_pvt if needed. If there is a swap channel, use it as a guide to setting up the bridge_channel.
Note
On entry, self is already locked.
Return values
0 on success.
-1 on failure. The channel did not get pushed.
Definition at line 213 of file bridge.h.
transfer_channel_cb
typedef void(* transfer_channel_cb) (struct ast_channel *chan, struct transfer_channel_data *user_data, enum ast_transfer_type transfer_type)
Callback function type called during blind transfers.
A caller of ast_bridge_transfer_blind() may wish to set data on the channel that ends up running dialplan. For instance, it may be useful to set channel variables on the channel.
Parameters
chan The involved channel
user_data User-provided data needed in the callback
transfer_type The type of transfer being completed
Definition at line 1160 of file bridge.h.
Enumeration Type Documentation
ast_bridge_capability
enum ast_bridge_capability
Capabilities for a bridge technology.
Enumerator
AST_BRIDGE_CAPABILITY_HOLDING
Bridge technology can service calls on hold.
AST_BRIDGE_CAPABILITY_EARLY
Bridge waits for channel to answer. Passes early media. (XXX Not supported yet)
AST_BRIDGE_CAPABILITY_NATIVE
Bridge is capable of natively bridging two channels. (Smart bridge only)
AST_BRIDGE_CAPABILITY_1TO1MIX
Bridge is capable of mixing at most two channels. (Smart bridgeable)
AST_BRIDGE_CAPABILITY_MULTIMIX
Bridge is capable of mixing an arbitrary number of channels. (Smart bridgeable)
Definition at line 84 of file bridge.h.
{
    /*! Bridge technology can service calls on hold. */
    AST_BRIDGE_CAPABILITY_HOLDING = (1 << 0),
    /*! Bridge waits for channel to answer.  Passes early media. (XXX Not supported yet) */
    AST_BRIDGE_CAPABILITY_EARLY = (1 << 1),
    /*! Bridge is capable of natively bridging two channels. (Smart bridge only) */
    AST_BRIDGE_CAPABILITY_NATIVE = (1 << 2),
    /*! Bridge is capable of mixing at most two channels. (Smart bridgeable) */
    AST_BRIDGE_CAPABILITY_1TO1MIX = (1 << 3),
    /*! Bridge is capable of mixing an arbitrary number of channels. (Smart bridgeable) */
    AST_BRIDGE_CAPABILITY_MULTIMIX = (1 << 4),
 };
ast_bridge_impart_flags
enum ast_bridge_impart_flags
Enumerator
AST_BRIDGE_IMPART_CHAN_MASK
Field describing what the caller can do with the channel after it is imparted.
AST_BRIDGE_IMPART_CHAN_DEPARTABLE
The caller wants to reclaim the channel using ast_bridge_depart().
AST_BRIDGE_IMPART_CHAN_INDEPENDENT
The caller is passing channel control entirely to the bridging system.
AST_BRIDGE_IMPART_INHIBIT_JOIN_COLP
The initial bridge join does not cause a COLP exchange.
Definition at line 598 of file bridge.h.
{
    /*! Field describing what the caller can do with the channel after it is imparted. */
    AST_BRIDGE_IMPART_CHAN_MASK = (1 << 0),
    /*! The caller wants to reclaim the channel using ast_bridge_depart(). */
    AST_BRIDGE_IMPART_CHAN_DEPARTABLE = (0 << 0),
    /*! The caller is passing channel control entirely to the bridging system. */
    AST_BRIDGE_IMPART_CHAN_INDEPENDENT = (1 << 0),
    /*! The initial bridge join does not cause a COLP exchange. */
    AST_BRIDGE_IMPART_INHIBIT_JOIN_COLP = (1 << 1),
 };
ast_bridge_join_flags
enum ast_bridge_join_flags
Enumerator
AST_BRIDGE_JOIN_PASS_REFERENCE
The bridge reference is being passed by the caller.
AST_BRIDGE_JOIN_INHIBIT_JOIN_COLP
The initial bridge join does not cause a COLP exchange.
Definition at line 547 of file bridge.h.
{
    /*! The bridge reference is being passed by the caller. */
    AST_BRIDGE_JOIN_PASS_REFERENCE = (1 << 0),
    /*! The initial bridge join does not cause a COLP exchange. */
    AST_BRIDGE_JOIN_INHIBIT_JOIN_COLP = (1 << 1),
 };
ast_bridge_optimization
enum ast_bridge_optimization
Tells, if optimization is allowed, how the optimization would be performed.
Enumerator
AST_BRIDGE_OPTIMIZE_SWAP_TO_CHAN_BRIDGE
Optimization would swap peer into the chan_bridge
AST_BRIDGE_OPTIMIZE_SWAP_TO_PEER_BRIDGE
Optimization would swap chan into the peer_bridge
AST_BRIDGE_OPTIMIZE_MERGE_TO_CHAN_BRIDGE
Optimization would merge peer_bridge into chan_bridge
AST_BRIDGE_OPTIMIZE_MERGE_TO_PEER_BRIDGE
Optimization would merge chan_bridge into peer_bridge
AST_BRIDGE_OPTIMIZE_PROHIBITED
Optimization is not permitted on one or both bridges
Definition at line 891 of file bridge.h.
{
    /*! Optimization would swap peer into the chan_bridge */
    AST_BRIDGE_OPTIMIZE_SWAP_TO_CHAN_BRIDGE,
    /*! Optimization would swap chan into the peer_bridge */
    AST_BRIDGE_OPTIMIZE_SWAP_TO_PEER_BRIDGE,
    /*! Optimization would merge peer_bridge into chan_bridge */
    AST_BRIDGE_OPTIMIZE_MERGE_TO_CHAN_BRIDGE,
    /*! Optimization would merge chan_bridge into peer_bridge */
    AST_BRIDGE_OPTIMIZE_MERGE_TO_PEER_BRIDGE,
    /*! Optimization is not permitted on one or both bridges */
    AST_BRIDGE_OPTIMIZE_PROHIBITED,
 };
ast_bridge_video_mode_type
enum ast_bridge_video_mode_type
Video source modes.
Enumerator
AST_BRIDGE_VIDEO_MODE_NONE
Video is not allowed in the bridge
AST_BRIDGE_VIDEO_MODE_SINGLE_SRC
A single user is picked as the only distributed of video across the bridge
AST_BRIDGE_VIDEO_MODE_TALKER_SRC
A single user's video feed is distributed to all bridge channels, but that feed is automatically picked based on who is talking the most.
AST_BRIDGE_VIDEO_MODE_SFU
Operate as a selective forwarding unit. Video from each participant is cloned to a dedicated stream on a subset of the remaining participants.
Definition at line 98 of file bridge.h.
{
    /*! Video is not allowed in the bridge */
    AST_BRIDGE_VIDEO_MODE_NONE = 0,
    /*! A single user is picked as the only distributed of video across the bridge */
    AST_BRIDGE_VIDEO_MODE_SINGLE_SRC,
    /*! A single user's video feed is distributed to all bridge channels, but
     *  that feed is automatically picked based on who is talking the most. */
    AST_BRIDGE_VIDEO_MODE_TALKER_SRC,
    /*! Operate as a selective forwarding unit. Video from each participant is
     * cloned to a dedicated stream on a subset of the remaining participants.
     */
    AST_BRIDGE_VIDEO_MODE_SFU,
 };
ast_bridge_video_sfu_remb_behavior
enum ast_bridge_video_sfu_remb_behavior
REMB report behaviors.
Enumerator
AST_BRIDGE_VIDEO_SFU_REMB_AVERAGE
The average of all reports is sent to the sender
AST_BRIDGE_VIDEO_SFU_REMB_LOWEST
The lowest reported bitrate is forwarded to the sender
AST_BRIDGE_VIDEO_SFU_REMB_HIGHEST
The highest reported bitrate is forwarded to the sender
AST_BRIDGE_VIDEO_SFU_REMB_AVERAGE_ALL
The average of all reports WITHIN the bridge is sent to each sender
AST_BRIDGE_VIDEO_SFU_REMB_LOWEST_ALL
The lowest reported bitrate from all channels in the bridge is forwarded to each sender
AST_BRIDGE_VIDEO_SFU_REMB_HIGHEST_ALL
The highest reported bitrate from all channels in the bridge is forwarded to each sender
AST_BRIDGE_VIDEO_SFU_REMB_FORCE
Force the REMB estimated bitrate to a specified value
Definition at line 131 of file bridge.h.
{
    /*! The average of all reports is sent to the sender */
    AST_BRIDGE_VIDEO_SFU_REMB_AVERAGE = 0,
    /*! The lowest reported bitrate is forwarded to the sender */
    AST_BRIDGE_VIDEO_SFU_REMB_LOWEST,
    /*! The highest reported bitrate is forwarded to the sender */
    AST_BRIDGE_VIDEO_SFU_REMB_HIGHEST,
    /*! The average of all reports WITHIN the bridge is sent to each sender */
    AST_BRIDGE_VIDEO_SFU_REMB_AVERAGE_ALL,
    /*! The lowest reported bitrate from all channels in the bridge is forwarded to each sender */
    AST_BRIDGE_VIDEO_SFU_REMB_LOWEST_ALL,
    /*! The highest reported bitrate from all channels in the bridge is forwarded to each sender */
    AST_BRIDGE_VIDEO_SFU_REMB_HIGHEST_ALL,
    /*! Force the REMB estimated bitrate to a specified value */
    AST_BRIDGE_VIDEO_SFU_REMB_FORCE,
 };
ast_transfer_result
enum ast_transfer_result
Enumerator
AST_BRIDGE_TRANSFER_SUCCESS
The transfer completed successfully
AST_BRIDGE_TRANSFER_NOT_PERMITTED
A bridge involved does not permit transferring
AST_BRIDGE_TRANSFER_INVALID
The current bridge setup makes transferring an invalid operation
AST_BRIDGE_TRANSFER_FAIL
The transfer operation failed for a miscellaneous reason
Definition at line 1115 of file bridge.h.
{
    /*! The transfer completed successfully */
    AST_BRIDGE_TRANSFER_SUCCESS,
    /*! A bridge involved does not permit transferring */
    AST_BRIDGE_TRANSFER_NOT_PERMITTED,
    /*! The current bridge setup makes transferring an invalid operation */
    AST_BRIDGE_TRANSFER_INVALID,
    /*! The transfer operation failed for a miscellaneous reason */
    AST_BRIDGE_TRANSFER_FAIL,
 };
ast_transfer_type
enum ast_transfer_type
Enumerator
AST_BRIDGE_TRANSFER_SINGLE_PARTY
Transfer of a single party
AST_BRIDGE_TRANSFER_MULTI_PARTY
Transfer of multiple parties
Definition at line 1126 of file bridge.h.
{
    /*! Transfer of a single party */
    AST_BRIDGE_TRANSFER_SINGLE_PARTY,
    /*! Transfer of multiple parties */
    AST_BRIDGE_TRANSFER_MULTI_PARTY,
 };
Function Documentation
_ast_bridge_lock()
static void _ast_bridge_lock (struct ast_bridge * bridge, const char * file, const char * function, int line, const char * var) inline static
Definition at line 481 of file bridge.h.
References __ao2_lock(), and AO2_LOCK_REQ_MUTEX.
 {
    __ao2_lock(bridge, AO2_LOCK_REQ_MUTEX, file, function, line, var);
 }
_ast_bridge_trylock()
static int _ast_bridge_trylock (struct ast_bridge * bridge, const char * file, const char * function, int line, const char * var) inline static
Definition at line 468 of file bridge.h.
References __ao2_trylock(), and AO2_LOCK_REQ_MUTEX.
 {
    return __ao2_trylock(bridge, AO2_LOCK_REQ_MUTEX, file, function, line, var);
 }
_ast_bridge_unlock()
static void _ast_bridge_unlock (struct ast_bridge * bridge, const char * file, const char * function, int line, const char * var) inline static
Definition at line 494 of file bridge.h.
References __ao2_unlock().
 {
    __ao2_unlock(bridge, file, function, line, var);
 }
ast_bridge_base_new()
struct ast_bridge* ast_bridge_base_new (uint32_t capabilities, unsigned int flags, const char * creator, const char * name, const char * id)
Create a new base class bridge.
Parameters
capabilities The capabilities that we require to be used on the bridge
flags Flags that will alter the behavior of the bridge
creator Entity that created the bridge (optional)
name Name given to the bridge by its creator (optional, requires named creator)
id Unique ID given to the bridge by its creator (optional)
Return values
a pointer to a new bridge on success
NULL on failure
Example usage:
struct ast_bridge *bridge;
bridge = ast_bridge_base_new(AST_BRIDGE_CAPABILITY_1TO1MIX, AST_BRIDGE_FLAG_DISSOLVE_HANGUP);
This creates a no frills two party bridge that will be destroyed once one of the channels hangs up.
Definition at line 960 of file bridge.c.
References bridge_manager_request::bridge, bridge_alloc(), bridge_base_init(), and bridge_register().
Referenced by AST_TEST_DEFINE(), get_wait_bridge_wrapper(), and join_conference_bridge().
 {
    void *bridge;
    bridge = bridge_alloc(sizeof(struct ast_bridge), &ast_bridge_base_v_table);
    bridge = bridge_base_init(bridge, capabilities, flags, creator, name, id);
    bridge = bridge_register(bridge);
    return bridge;
 }
ast_bridge_depart()
int ast_bridge_depart (struct ast_channel * chan)
Depart a channel from a bridge.
Parameters
chan Channel to depart
Note
chan is locked by this function.
Return values
0 on success
-1 on failure
Example usage:
ast_bridge_depart(chan);
This removes the channel pointed to by the chan pointer from any bridge it may be in and gives control to the calling thread. This does not hang up the channel.
Note
This API call can only be used on channels that were added to the bridge using the ast_bridge_impart API call with the AST_BRIDGE_IMPART_CHAN_DEPARTABLE flag.
Definition at line 1952 of file bridge.c.
References ao2_ref, ast_assert, ast_bridge_channel_leave_bridge(), AST_CAUSE_NORMAL_CLEARING, ast_channel_internal_bridge_channel(), ast_channel_internal_bridge_channel_set(), ast_channel_lock, ast_channel_name(), ast_channel_unlock, ast_debug, ast_log, BRIDGE_CHANNEL_STATE_END_NO_DISSOLVE, ast_bridge_channel::chan, ast_bridge_channel::depart_wait, LOG_ERROR, NULL, SCOPE_TRACE, and ast_bridge_channel::thread.
Referenced by app_control_continue(), AST_TEST_DEFINE(), control_swap_channel_in_bridge(), depart_channel(), and stasis_app_exec().
 {
    struct ast_bridge_channel *bridge_channel;
    int departable;
    SCOPE_TRACE(1, "%s\n", ast_channel_name(chan));
    ast_channel_lock(chan);
    bridge_channel = ast_channel_internal_bridge_channel(chan);
    departable = bridge_channel && bridge_channel->depart_wait;
    ast_channel_unlock(chan);
    if (!departable) {
       ast_log(LOG_ERROR, "Channel %s cannot be departed.\n",
          ast_channel_name(chan));
       /*
        * Should never happen.  It likely means that
        * ast_bridge_depart() is called by two threads for the same
        * channel, the channel was never imparted to be departed, or it
        * has already been departed.
        */
       ast_assert(0);
       return -1;
    }
    /*
     * We are claiming the bridge_channel reference held by
     * bridge_channel_depart_thread().
     */
    ast_bridge_channel_leave_bridge(bridge_channel,
       BRIDGE_CHANNEL_STATE_END_NO_DISSOLVE, AST_CAUSE_NORMAL_CLEARING);
    /* Wait for the depart thread to die */
    ast_debug(1, "Waiting for %p(%s) bridge thread to die.\n",
       bridge_channel, ast_channel_name(bridge_channel->chan));
    pthread_join(bridge_channel->thread, NULL);
    ast_channel_lock(chan);
    ast_channel_internal_bridge_channel_set(chan, NULL);
    ast_channel_unlock(chan);
    /* We can get rid of the bridge_channel after the depart thread has died. */
    ao2_ref(bridge_channel, -1);
    return 0;
 }
ast_bridge_destroy()
int ast_bridge_destroy (struct ast_bridge * bridge, int cause)
Destroy a bridge.
Parameters
bridge Bridge to destroy
cause Cause of bridge being destroyed. (If cause <= 0 then use AST_CAUSE_NORMAL_CLEARING)
Return values
0 on success
-1 on failure
Example usage:
ast_bridge_destroy(bridge, AST_CAUSE_NORMAL_CLEARING);
This destroys a bridge that was previously created.
Note
While this function will kick all channels out of the bridge, channels that were added to the bridge using ast_bridge_impart() with the flag AST_BRIDGE_IMPART_CHAN_DEPARTABLE set must have ast_bridge_depart() called on them.
Definition at line 970 of file bridge.c.
References ao2_ref, ast_bridge_lock, ast_bridge_unlock, ast_debug, bridge_dissolve(), and ast_bridge::uniqueid.
Referenced by action_bridge(), agent_connect_caller(), agent_logout(), agent_pvt_destructor(), agent_request_exec(), agent_run(), ast_bridge_call_with_flags(), attended_transfer_properties_shutdown(), bridge_create_common(), bridge_exec(), bridge_register(), caller_abort_agent(), destroy_conference_bridge(), fail_enter(), handle_bridge_destroy_specific(), manager_bridge_destroy(), parked_call_app_exec(), parking_lot_destructor(), safe_bridge_destroy(), stasis_app_bridge_destroy(), stasis_app_control_shutdown(), unload_module(), wait_bridge_wrapper_alloc(), and wait_bridge_wrapper_destructor().
 {
    ast_debug(1, "Bridge %s: telling all channels to leave the party\n", bridge->uniqueid);
    ast_bridge_lock(bridge);
    bridge_dissolve(bridge, cause);
    ast_bridge_unlock(bridge);
    ao2_ref(bridge, -1);
    return 0;
 }
ast_bridge_features_remove()
void ast_bridge_features_remove (struct ast_bridge_features * features, enum ast_bridge_hook_remove_flags flags)
Remove marked bridge channel feature hooks.
Since
12.0.0
Parameters
features Bridge features structure
flags Determinator for whether hook is removed.
Returns
Nothing
Definition at line 3568 of file bridge.c.
References ast_bridge_features::dtmf_hooks, hooks_remove_container(), hooks_remove_heap(), ast_bridge_features::interval_hooks, and ast_bridge_features::other_hooks.
Referenced by bridge_base_pull(), bridge_channel_internal_join(), bridge_do_merge(), bridge_do_move(), and remove_hooks_on_personality_change().
 {
    hooks_remove_container(features->dtmf_hooks, remove_flags);
    hooks_remove_container(features->other_hooks, remove_flags);
    hooks_remove_heap(features->interval_hooks, remove_flags);
 }
ast_bridge_find_by_id()
struct ast_bridge* ast_bridge_find_by_id (const char * bridge_id)
Find bridge by id.
Since
12.0.0
Parameters
bridge_id Bridge identifier
Returns
NULL bridge not found
non-NULL reference to bridge
Definition at line 5070 of file bridge.c.
References ao2_find, and OBJ_SEARCH_KEY.
Referenced by ast_bridge_get_snapshot_by_uniqueid(), complete_bridge_participant(), handle_bridge_destroy_specific(), handle_bridge_kick_channel(), manager_bridge_destroy(), and manager_bridge_kick().
 {
    return ao2_find(bridges, bridge_id, OBJ_SEARCH_KEY);
 }
ast_bridge_impart()
int ast_bridge_impart (struct ast_bridge * bridge, struct ast_channel * chan, struct ast_channel * swap, struct ast_bridge_features * features, enum ast_bridge_impart_flags flags)
Impart a channel to a bridge (non-blocking)
Parameters
bridge Bridge to impart on
chan Channel to impart (The channel reference is stolen if impart successful.)
swap Channel to swap out if swapping. NULL if not swapping.
features Bridge features structure.
flags defined by enum ast_bridge_impart_flags.
Note
The given bridge must be unlocked when calling this function.
The features parameter must be NULL or obtained by ast_bridge_features_new(). You must not dereference features after calling even if the call fails.
chan is locked by this function.
Return values
0 on success
-1 on failure (Caller still has ownership of chan)
Example usage:
ast_bridge_impart(bridge, chan, NULL, NULL, AST_BRIDGE_IMPART_CHAN_INDEPENDENT);
This adds a channel pointed to by the chan pointer to the bridge pointed to by the bridge pointer. This function will return immediately and will not wait until the channel is no longer part of the bridge.
If this channel will be replacing another channel the other channel can be specified in the swap parameter. The other channel will be thrown out of the bridge in an atomic fashion.
If channel specific features are enabled, a pointer to the features structure can be specified in the features parameter.
Note
If you impart a channel with AST_BRIDGE_IMPART_CHAN_DEPARTABLE you MUST ast_bridge_depart() the channel if this call succeeds. The bridge channel thread is created join-able. The implication is that the channel is special and will not behave like a normal channel.
If you impart a channel with AST_BRIDGE_IMPART_CHAN_INDEPENDENT you must not ast_bridge_depart() the channel. The bridge channel thread is created non-join-able. The channel must be treated as if it were placed into the bridge by ast_bridge_join(). Channels placed into a bridge by ast_bridge_join() are removed by a third party using ast_bridge_remove().
Any callbacks on the channel will be invoked on failure with the reason as AST_BRIDGE_AFTER_CB_REASON_IMPART_FAILED.
Definition at line 1924 of file bridge.c.
References AST_BRIDGE_AFTER_CB_REASON_IMPART_FAILED, ast_bridge_discard_after_callback(), ast_channel_name(), ast_cond_destroy, ast_cond_init, ast_mutex_destroy, ast_mutex_init, bridge_channel_impart_signal(), bridge_impart_internal(), bridge_channel_impart_cond::cond, bridge_channel_impart_cond::done, bridge_channel_impart_cond::lock, NULL, SCOPE_TRACE, and ast_bridge::uniqueid.
Referenced by add_to_dial_bridge(), ast_bridge_add_channel(), ast_bridge_call_with_flags(), AST_TEST_DEFINE(), ast_unreal_channel_push_to_bridge(), attended_transfer_bridge(), blind_transfer_bridge(), conf_announce_channel_push(), conf_start_record(), control_swap_channel_in_bridge(), feature_attended_transfer(), handle_invite_replaces(), local_call(), parking_blind_transfer_park(), recalling_exit(), refer_incoming_invite_request(), and retransfer_enter().
 {
    struct bridge_channel_impart_cond cond = {
       .done = 0,
    };
    int res;
    SCOPE_TRACE(1, "%s Bridge: %s\n", ast_channel_name(chan), bridge->uniqueid);
    ast_mutex_init(&cond.lock);
    ast_cond_init(&cond.cond, NULL);
    res = bridge_impart_internal(bridge, chan, swap, features, flags, &cond);
    if (res) {
       /* Impart failed.  Signal any other waiting impart threads */
       ast_bridge_discard_after_callback(chan, AST_BRIDGE_AFTER_CB_REASON_IMPART_FAILED);
       bridge_channel_impart_signal(chan);
    }
    ast_cond_destroy(&cond.cond);
    ast_mutex_destroy(&cond.lock);
    return res;
 }
ast_bridge_is_video_src()
int ast_bridge_is_video_src (struct ast_bridge * bridge, struct ast_channel * chan)
Determine if a channel is a video src for the bridge.
Return values
0 Not a current video source of the bridge.
None 0, is a video source of the bridge, The number returned represents the priority this video stream has on the bridge where 1 is the highest priority.
Definition at line 3958 of file bridge.c.
References ast_bridge_lock, ast_bridge_unlock, AST_BRIDGE_VIDEO_MODE_NONE, AST_BRIDGE_VIDEO_MODE_SFU, AST_BRIDGE_VIDEO_MODE_SINGLE_SRC, AST_BRIDGE_VIDEO_MODE_TALKER_SRC, ast_bridge_video_talker_src_data::chan_old_vsrc, ast_bridge_video_single_src_data::chan_vsrc, ast_bridge_video_talker_src_data::chan_vsrc, ast_bridge_video_mode::mode, ast_bridge_video_mode::mode_data, ast_bridge_video_mode::single_src_data, ast_bridge::softmix, ast_bridge_video_mode::talker_src_data, and ast_bridge_softmix::video_mode.
Referenced by handle_video_on_exit(), handle_video_on_join(), softmix_bridge_write_video(), and softmix_pass_video_top_priority().
 {
    int res = 0;
    ast_bridge_lock(bridge);
    switch (bridge->softmix.video_mode.mode) {
    case AST_BRIDGE_VIDEO_MODE_NONE:
       break;
    case AST_BRIDGE_VIDEO_MODE_SINGLE_SRC:
       if (bridge->softmix.video_mode.mode_data.single_src_data.chan_vsrc == chan) {
          res = 1;
       }
       break;
    case AST_BRIDGE_VIDEO_MODE_TALKER_SRC:
       if (bridge->softmix.video_mode.mode_data.talker_src_data.chan_vsrc == chan) {
          res = 1;
       } else if (bridge->softmix.video_mode.mode_data.talker_src_data.chan_old_vsrc == chan) {
          res = 2;
       }
    case AST_BRIDGE_VIDEO_MODE_SFU:
       break;
    }
    ast_bridge_unlock(bridge);
    return res;
 }
ast_bridge_join()
int ast_bridge_join (struct ast_bridge * bridge, struct ast_channel * chan, struct ast_channel * swap, struct ast_bridge_features * features, struct ast_bridge_tech_optimizations * tech_args, enum ast_bridge_join_flags flags)
Join a channel to a bridge (blocking)
Parameters
bridge Bridge to join
chan Channel to join
swap Channel to swap out if swapping (A channel reference is stolen.)
features Bridge features structure
tech_args Optional Bridging tech optimization parameters for this channel.
flags defined by enum ast_bridge_join_flags.
Note
The passed in swap channel is always unreffed on return. It is not a good idea to access the swap channel on return or for the caller to keep a reference to it.
Absolutely NO locks should be held before calling this function since it blocks.
Return values
0 if the channel successfully joined the bridge before it exited.
-1 if the channel failed to join the bridge
Example usage:
ast_bridge_join(bridge, chan, NULL, NULL, NULL, AST_BRIDGE_JOIN_PASS_REFERENCE);
This adds a channel pointed to by the chan pointer to the bridge pointed to by the bridge pointer. This function will not return until the channel has been removed from the bridge, swapped out for another channel, or has hung up.
If this channel will be replacing another channel the other channel can be specified in the swap parameter. The other channel will be thrown out of the bridge in an atomic fashion.
If channel specific features are enabled a pointer to the features structure can be specified in the features parameter.
Definition at line 1667 of file bridge.c.
References ao2_lock, ao2_ref, ao2_t_cleanup, ao2_unlock, ast_assert, AST_BRIDGE_JOIN_INHIBIT_JOIN_COLP, AST_BRIDGE_JOIN_PASS_REFERENCE, ast_bridge_lock, ast_bridge_run_after_callback(), ast_bridge_setup_after_goto(), ast_bridge_unlock, ast_channel_flags(), ast_channel_internal_bridge_channel_set(), ast_channel_lock, ast_channel_name(), ast_channel_softhangup_internal_flag(), ast_channel_unlock, AST_FLAG_ZOMBIE, AST_SOFTHANGUP_ASYNCGOTO, ast_softhangup_nolock(), ast_test_flag, bridge_channel_impart_signal(), bridge_channel_internal_alloc(), bridge_channel_internal_join(), bridge_find_channel(), ast_bridge_channel::chan, ast_bridge_channel::features, ast_bridge_channel::inhibit_colp, NULL, ast_bridge_methods::push_peek, SCOPE_TRACE, ast_bridge_channel::swap, ast_bridge_channel::tech_args, ast_bridge_channel::thread, ast_bridge::uniqueid, and ast_bridge::v_table.
Referenced by agent_request_exec(), agent_run(), ast_bridge_call_with_flags(), bridge_exec(), bridgeadd_exec(), bridgewait_exec(), confbridge_exec(), park_and_announce_app_exec(), park_app_exec(), and parked_call_app_exec().
 {
    struct ast_bridge_channel *bridge_channel;
    int res = 0;
    SCOPE_TRACE(1, "%s Bridge: %s\n", ast_channel_name(chan), bridge->uniqueid);
    bridge_channel = bridge_channel_internal_alloc(bridge);
    if (flags & AST_BRIDGE_JOIN_PASS_REFERENCE) {
       ao2_ref(bridge, -1);
    }
    if (!bridge_channel) {
       ao2_t_cleanup(swap, "Error exit: bridge_channel alloc failed");
       res = -1;
       goto join_exit;
    }
 /* XXX ASTERISK-21271 features cannot be NULL when passed in. When it is changed to allocated we can do like ast_bridge_impart() and allocate one. */
    ast_assert(features != NULL);
    if (!features) {
       ao2_ref(bridge_channel, -1);
       ao2_t_cleanup(swap, "Error exit: features is NULL");
       res = -1;
       goto join_exit;
    }
    if (tech_args) {
       bridge_channel->tech_args = *tech_args;
    }
    ast_channel_lock(chan);
    if (ast_test_flag(ast_channel_flags(chan), AST_FLAG_ZOMBIE)) {
       res = -1;
    } else {
       ast_channel_internal_bridge_channel_set(chan, bridge_channel);
    }
    ast_channel_unlock(chan);
    bridge_channel->thread = pthread_self();
    bridge_channel->chan = chan;
    bridge_channel->swap = swap;
    bridge_channel->features = features;
    bridge_channel->inhibit_colp = !!(flags & AST_BRIDGE_JOIN_INHIBIT_JOIN_COLP);
    /* allow subclass to peek at upcoming push operation */
    if (bridge->v_table->push_peek && !res) {
       struct ast_bridge_channel *bcswap = NULL;
       ast_bridge_lock(bridge);
       if (bridge_channel->swap) {
          bcswap = bridge_find_channel(bridge, bridge_channel->swap);
       }
       res = bridge->v_table->push_peek(bridge, bridge_channel, bcswap);
       ast_bridge_unlock(bridge);
    }
    if (!res) {
       res = bridge_channel_internal_join(bridge_channel);
    }
    /* Cleanup all the data in the bridge channel after it leaves the bridge. */
    ast_channel_lock(chan);
    ast_channel_internal_bridge_channel_set(chan, NULL);
    ast_channel_unlock(chan);
    /* Due to a race condition, we lock the bridge channel here for ast_bridge_channel_get_chan */
    ao2_lock(bridge_channel);
    bridge_channel->chan = NULL;
    ao2_unlock(bridge_channel);
    /* If bridge_channel->swap is not NULL then the join failed. */
    ao2_t_cleanup(bridge_channel->swap, "Bridge complete: join failed");
    bridge_channel->swap = NULL;
    bridge_channel->features = NULL;
    ao2_ref(bridge_channel, -1);
 join_exit:
    ast_bridge_run_after_callback(chan);
    bridge_channel_impart_signal(chan);
    if (!(ast_channel_softhangup_internal_flag(chan) & AST_SOFTHANGUP_ASYNCGOTO)
       && !ast_bridge_setup_after_goto(chan)) {
       /* Claim the after bridge goto is an async goto destination. */
       ast_channel_lock(chan);
       ast_softhangup_nolock(chan, AST_SOFTHANGUP_ASYNCGOTO);
       ast_channel_unlock(chan);
    }
    return res;
 }
ast_bridge_kick()
int ast_bridge_kick (struct ast_bridge * bridge, struct ast_channel * chan)
Kick a channel from a bridge.
Parameters
bridge Bridge that the channel is to be kicked from
chan Channel to kick
Return values
0 on success
-1 on failure
Example usage:
ast_bridge_kick(bridge, chan);
This kicks the channel pointed to by the chan pointer from the bridge pointed to by the bridge pointer and requests that it be hung up. Control over the channel will NOT be given to the calling thread.
Note
The functional difference between ast_bridge_kick() and ast_bridge_remove() is that the bridge may dissolve as a result of the channel being kicked.
This API call can be used on channels that were added to the bridge using both ast_bridge_join and ast_bridge_impart.
Definition at line 2025 of file bridge.c.
References ast_bridge_channel_queue_callback(), ast_bridge_lock, ast_bridge_unlock, bridge_find_channel(), kick_it(), and NULL.
Referenced by handle_bridge_kick_channel(), and manager_bridge_kick().
 {
    struct ast_bridge_channel *bridge_channel;
    int res;
    ast_bridge_lock(bridge);
    /* Try to find the channel that we want to kick. */
    if (!(bridge_channel = bridge_find_channel(bridge, chan))) {
       ast_bridge_unlock(bridge);
       return -1;
    }
    res = ast_bridge_channel_queue_callback(bridge_channel, 0, kick_it, NULL, 0);
    ast_bridge_unlock(bridge);
    return res;
 }
ast_bridge_merge()
int ast_bridge_merge (struct ast_bridge * dst_bridge, struct ast_bridge * src_bridge, int merge_best_direction, struct ast_channel ** kick_me, unsigned int num_kick)
Merge two bridges together.
Parameters
dst_bridge Destination bridge of merge.
src_bridge Source bridge of merge.
merge_best_direction TRUE if don't care about which bridge merges into the other.
kick_me Array of channels to kick from the bridges.
num_kick Number of channels in the kick_me array.
Note
Absolutely NO bridge or channel locks should be held before calling this function.
Return values
0 on success
-1 on failure
Example usage:
ast_bridge_merge(dst_bridge, src_bridge, 0, NULL, 0);
This moves the channels in src_bridge into the bridge pointed to by dst_bridge.
Definition at line 2348 of file bridge.c.
References ast_assert, ast_bridge_lock_both, ast_bridge_unlock, and bridge_merge_locked().
 {
    int res;
    /* Sanity check. */
    ast_assert(dst_bridge && src_bridge);
    ast_bridge_lock_both(dst_bridge, src_bridge);
    res = bridge_merge_locked(dst_bridge, src_bridge, merge_best_direction, kick_me, num_kick);
    ast_bridge_unlock(src_bridge);
    ast_bridge_unlock(dst_bridge);
    return res;
 }
ast_bridge_merge_inhibit()
void ast_bridge_merge_inhibit (struct ast_bridge * bridge, int request)
Adjust the bridge merge inhibit request count.
Since
12.0.0
Parameters
bridge What to operate on.
request Inhibit request increment. (Positive to add requests. Negative to remove requests.)
Returns
Nothing
Definition at line 3061 of file bridge.c.
References ast_bridge_lock, ast_bridge_unlock, and bridge_merge_inhibit_nolock().
Referenced by attended_transfer_properties_shutdown(), consulting_exit(), and feature_attended_transfer().
 {
    ast_bridge_lock(bridge);
    bridge_merge_inhibit_nolock(bridge, request);
    ast_bridge_unlock(bridge);
 }
ast_bridge_move()
int ast_bridge_move (struct ast_bridge * dst_bridge, struct ast_bridge * src_bridge, struct ast_channel * chan, struct ast_channel * swap, int attempt_recovery)
Move a channel from one bridge to another.
Since
12.0.0
Parameters
dst_bridge Destination bridge of bridge channel move.
src_bridge Source bridge of bridge channel move.
chan Channel to move.
swap Channel to replace in dst_bridge.
attempt_recovery TRUE if failure attempts to push channel back into original bridge.
Note
Absolutely NO bridge or channel locks should be held before calling this function.
Return values
0 on success.
-1 on failure.
Definition at line 2508 of file bridge.c.
References ast_bridge_lock_both, ast_bridge_unlock, and bridge_move_locked().
Referenced by agent_connect_caller(), parked_call_app_exec(), and parking_park_bridge_channel().
 {
    int res;
    ast_bridge_lock_both(dst_bridge, src_bridge);
    res = bridge_move_locked(dst_bridge, src_bridge, chan, swap, attempt_recovery);
    ast_bridge_unlock(src_bridge);
    ast_bridge_unlock(dst_bridge);
    return res;
 }
ast_bridge_notify_masquerade()
void ast_bridge_notify_masquerade (struct ast_channel * chan)
Notify bridging that this channel was just masqueraded.
Since
12.0.0
Parameters
chan Channel just involved in a masquerade
Returns
Nothing
Definition at line 1482 of file bridge.c.
References ao2_ref, ast_bridge_channel_lock_bridge(), ast_bridge_unlock, ast_channel_get_bridge_channel(), ast_channel_lock, ast_channel_unlock, ast_bridge_channel::bridge, bridge_manager_request::bridge, bridge_find_channel(), bridge_reconfigured(), ast_bridge_methods::notify_masquerade, and ast_bridge::v_table.
Referenced by channel_do_masquerade().
 {
    struct ast_bridge_channel *bridge_channel;
    struct ast_bridge *bridge;
    /* Safely get the bridge_channel pointer for the chan. */
    ast_channel_lock(chan);
    bridge_channel = ast_channel_get_bridge_channel(chan);
    ast_channel_unlock(chan);
    if (!bridge_channel) {
       /* Not in a bridge */
       return;
    }
    ast_bridge_channel_lock_bridge(bridge_channel);
    bridge = bridge_channel->bridge;
    if (bridge_channel == bridge_find_channel(bridge, chan)) {
 /*
  * XXX ASTERISK-22366 this needs more work.  The channels need
  * to be made compatible again if the formats change. The
  * bridge_channel thread needs to monitor for this case.
  */
       /* The channel we want to notify is still in a bridge. */
       bridge->v_table->notify_masquerade(bridge, bridge_channel);
       bridge_reconfigured(bridge, 1);
    }
    ast_bridge_unlock(bridge);
    ao2_ref(bridge_channel, -1);
 }
ast_bridge_number_video_src()
int ast_bridge_number_video_src (struct ast_bridge * bridge)
Returns the number of video sources currently active in the bridge.
Definition at line 3931 of file bridge.c.
References ast_bridge_lock, ast_bridge_unlock, AST_BRIDGE_VIDEO_MODE_NONE, AST_BRIDGE_VIDEO_MODE_SFU, AST_BRIDGE_VIDEO_MODE_SINGLE_SRC, AST_BRIDGE_VIDEO_MODE_TALKER_SRC, ast_bridge_video_talker_src_data::chan_old_vsrc, ast_bridge_video_single_src_data::chan_vsrc, ast_bridge_video_talker_src_data::chan_vsrc, ast_bridge_video_mode::mode, ast_bridge_video_mode::mode_data, ast_bridge_video_mode::single_src_data, ast_bridge::softmix, ast_bridge_video_mode::talker_src_data, and ast_bridge_softmix::video_mode.
Referenced by softmix_bridge_write_video().
 {
    int res = 0;
    ast_bridge_lock(bridge);
    switch (bridge->softmix.video_mode.mode) {
    case AST_BRIDGE_VIDEO_MODE_NONE:
       break;
    case AST_BRIDGE_VIDEO_MODE_SINGLE_SRC:
       if (bridge->softmix.video_mode.mode_data.single_src_data.chan_vsrc) {
          res = 1;
       }
       break;
    case AST_BRIDGE_VIDEO_MODE_TALKER_SRC:
       if (bridge->softmix.video_mode.mode_data.talker_src_data.chan_vsrc) {
          res++;
       }
       if (bridge->softmix.video_mode.mode_data.talker_src_data.chan_old_vsrc) {
          res++;
       }
    case AST_BRIDGE_VIDEO_MODE_SFU:
       break;
    }
    ast_bridge_unlock(bridge);
    return res;
 }
ast_bridge_peer()
struct ast_channel* ast_bridge_peer (struct ast_bridge * bridge, struct ast_channel * chan)
Get the channel's bridge peer only if the bridge is two-party.
Since
12.0.0
Parameters
bridge The bridge
chan Channel desiring the bridge peer channel.
Note
The returned peer channel is the current peer in the bridge when called.
Return values
NULL Channel not in a bridge or the bridge is not two-party.
non-NULL Reffed peer channel at time of calling.
Definition at line 4142 of file bridge.c.
References ast_bridge_lock, ast_bridge_peer_nolock(), and ast_bridge_unlock.
Referenced by ast_attended_transfer_message_create(), ast_bridge_transfer_blind(), ast_channel_bridge_peer(), and get_transfer_parties_transferer_bridge().
 {
    struct ast_channel *peer;
    ast_bridge_lock(bridge);
    peer = ast_bridge_peer_nolock(bridge, chan);
    ast_bridge_unlock(bridge);
    return peer;
 }
ast_bridge_peer_nolock()
struct ast_channel* ast_bridge_peer_nolock (struct ast_bridge * bridge, struct ast_channel * chan)
Get the channel's bridge peer only if the bridge is two-party.
Since
12.0.0
Parameters
bridge The bridge which is already locked.
chan Channel desiring the bridge peer channel.
Note
The returned peer channel is the current peer in the bridge when called.
Return values
NULL Channel not in a bridge or the bridge is not two-party.
non-NULL Reffed peer channel at time of calling.
Definition at line 4114 of file bridge.c.
References AST_BRIDGE_CAPABILITY_1TO1MIX, AST_BRIDGE_CAPABILITY_NATIVE, ast_channel_ref, AST_LIST_TRAVERSE, ast_bridge_technology::capabilities, ast_bridge_channel::chan, ast_bridge::channels, ast_bridge_channel::in_bridge, NULL, ast_bridge::num_channels, and ast_bridge::technology.
Referenced by ast_bridge_peer(), feature_automixmonitor(), and feature_automonitor().
 {
    struct ast_channel *peer = NULL;
    struct ast_bridge_channel *iter;
    /* Asking for the peer channel only makes sense on a two-party bridge. */
    if (bridge->num_channels == 2
       && bridge->technology->capabilities
          & (AST_BRIDGE_CAPABILITY_NATIVE | AST_BRIDGE_CAPABILITY_1TO1MIX)) {
       int in_bridge = 0;
       AST_LIST_TRAVERSE(&bridge->channels, iter, entry) {
          if (iter->chan != chan) {
             peer = iter->chan;
          } else {
             in_bridge = 1;
          }
       }
       if (in_bridge && peer) {
          ast_channel_ref(peer);
       } else {
          peer = NULL;
       }
    }
    return peer;
 }
ast_bridge_peers()
struct ao2_container* ast_bridge_peers (struct ast_bridge * bridge)
Get a container of all channels in the bridge.
Since
12.0.0
Parameters
bridge The bridge
Note
The returned container is a snapshot of channels in the bridge when called.
Return values
NULL Failed to create container
non-NULL Container of channels in the bridge
Definition at line 4103 of file bridge.c.
References ast_bridge_lock, ast_bridge_peers_nolock(), ast_bridge_unlock, and channels.
 {
    struct ao2_container *channels;
    ast_bridge_lock(bridge);
    channels = ast_bridge_peers_nolock(bridge);
    ast_bridge_unlock(bridge);
    return channels;
 }
ast_bridge_peers_nolock()
struct ao2_container* ast_bridge_peers_nolock (struct ast_bridge * bridge)
Get a container of all channels in the bridge.
Since
12.0.0
Parameters
bridge The bridge which is already locked.
Return values
NULL Failed to create container
non-NULL Container of channels in the bridge
Definition at line 4085 of file bridge.c.
References AO2_ALLOC_OPT_LOCK_NOLOCK, ao2_container_alloc_hash, ao2_link, AST_LIST_TRAVERSE, ast_bridge_channel::chan, channel_cmp(), channel_hash(), channels, ast_bridge::channels, and NULL.
Referenced by ast_bridge_peers(), ast_bridge_transfer_attended(), ast_bridge_transfer_blind(), and two_bridge_attended_transfer().
 {
    struct ao2_container *channels;
    struct ast_bridge_channel *iter;
    channels = ao2_container_alloc_hash(AO2_ALLOC_OPT_LOCK_NOLOCK, 0,
       13, channel_hash, NULL, channel_cmp);
    if (!channels) {
       return NULL;
    }
    AST_LIST_TRAVERSE(&bridge->channels, iter, entry) {
       ao2_link(channels, iter->chan);
    }
    return channels;
 }
ast_bridge_queue_action()
int ast_bridge_queue_action (struct ast_bridge * bridge, struct ast_frame * action)
Put an action onto the specified bridge.
Since
12.0.0
Parameters
bridge What to queue the action on.
action What to do.
Return values
0 on success.
-1 on error.
Note
This API call is meant for internal bridging operations.
Definition at line 307 of file bridge.c.
References ast_frdup, and bridge_queue_action_nodup().
Referenced by bridge_dissolve().
 {
    struct ast_frame *dup;
    dup = ast_frdup(action);
    if (!dup) {
       return -1;
    }
    bridge_queue_action_nodup(bridge, dup);
    return 0;
 }
ast_bridge_queue_everyone_else()
int ast_bridge_queue_everyone_else (struct ast_bridge * bridge, struct ast_bridge_channel * bridge_channel, struct ast_frame * frame)
Queue the given frame to everyone else.
Since
12.0.0
Parameters
bridge What bridge to distribute frame.
bridge_channel Channel to optionally not pass frame to. (NULL to pass to everyone)
frame Frame to pass.
Note
This is intended to be called by bridge hooks and bridge technologies.
Return values
0 Frame written to at least one channel.
-1 Frame written to no channels.
Definition at line 1122 of file bridge_channel.c.
References ast_bridge_channel_queue_frame(), AST_FRAME_NULL, AST_LIST_TRAVERSE, ast_bridge::channels, and ast_frame::frametype.
Referenced by bridge_hold(), bridge_ringing(), bridge_unhold(), holding_bridge_write(), native_bridge_write(), native_rtp_bridge_write(), simple_bridge_write(), softmix_bridge_write(), softmix_bridge_write_control(), softmix_bridge_write_text(), and softmix_bridge_write_video().
 {
    struct ast_bridge_channel *cur;
    int not_written = -1;
    if (frame->frametype == AST_FRAME_NULL) {
       /* "Accept" the frame and discard it. */
       return 0;
    }
    AST_LIST_TRAVERSE(&bridge->channels, cur, entry) {
       if (cur == bridge_channel) {
          continue;
       }
       if (!ast_bridge_channel_queue_frame(cur, frame)) {
          not_written = 0;
       }
    }
    return not_written;
 }
ast_bridge_remove()
int ast_bridge_remove (struct ast_bridge * bridge, struct ast_channel * chan)
Remove a channel from a bridge.
Parameters
bridge Bridge that the channel is to be removed from
chan Channel to remove
Return values
0 on success
-1 on failure
Example usage:
ast_bridge_remove(bridge, chan);
This removes the channel pointed to by the chan pointer from the bridge pointed to by the bridge pointer and requests that it be hung up. Control over the channel will NOT be given to the calling thread.
Note
This API call can be used on channels that were added to the bridge using both ast_bridge_join and ast_bridge_impart.
Definition at line 1997 of file bridge.c.
References ast_bridge_channel_leave_bridge(), ast_bridge_lock, ast_bridge_unlock, AST_CAUSE_NORMAL_CLEARING, ast_channel_name(), ast_debug, BRIDGE_CHANNEL_STATE_END_NO_DISSOLVE, bridge_find_channel(), and ast_bridge::uniqueid.
Referenced by action_kick_last(), ast_bridge_transfer_attended(), ast_bridge_transfer_blind(), execute_menu_entry(), kick_conference_participant(), and leave_marked().
 {
    struct ast_bridge_channel *bridge_channel;
    ast_debug(1, "Removing channel %s from bridge %s\n",
       ast_channel_name(chan), bridge->uniqueid);
    ast_bridge_lock(bridge);
    /* Try to find the channel that we want to remove */
    if (!(bridge_channel = bridge_find_channel(bridge, chan))) {
       ast_bridge_unlock(bridge);
       return -1;
    }
    ast_bridge_channel_leave_bridge(bridge_channel,
       BRIDGE_CHANNEL_STATE_END_NO_DISSOLVE, AST_CAUSE_NORMAL_CLEARING);
    ast_bridge_unlock(bridge);
    return 0;
 }
ast_bridge_remove_video_src()
void ast_bridge_remove_video_src (struct ast_bridge * bridge, struct ast_channel * chan)
remove a channel as a source of video for the bridge.
Definition at line 3984 of file bridge.c.
References ast_bridge_lock, ast_bridge_unlock, AST_BRIDGE_VIDEO_MODE_NONE, AST_BRIDGE_VIDEO_MODE_SFU, AST_BRIDGE_VIDEO_MODE_SINGLE_SRC, AST_BRIDGE_VIDEO_MODE_TALKER_SRC, ast_channel_unref, ast_bridge_video_talker_src_data::average_talking_energy, ast_bridge_video_talker_src_data::chan_old_vsrc, ast_bridge_video_single_src_data::chan_vsrc, ast_bridge_video_talker_src_data::chan_vsrc, ast_bridge_video_mode::mode, ast_bridge_video_mode::mode_data, NULL, ast_bridge_video_mode::single_src_data, ast_bridge::softmix, ast_bridge_video_mode::talker_src_data, and ast_bridge_softmix::video_mode.
Referenced by bridge_channel_internal_join(), and handle_video_on_exit().
 {
    ast_bridge_lock(bridge);
    switch (bridge->softmix.video_mode.mode) {
    case AST_BRIDGE_VIDEO_MODE_NONE:
       break;
    case AST_BRIDGE_VIDEO_MODE_SINGLE_SRC:
       if (bridge->softmix.video_mode.mode_data.single_src_data.chan_vsrc == chan) {
          if (bridge->softmix.video_mode.mode_data.single_src_data.chan_vsrc) {
             ast_channel_unref(bridge->softmix.video_mode.mode_data.single_src_data.chan_vsrc);
          }
          bridge->softmix.video_mode.mode_data.single_src_data.chan_vsrc = NULL;
       }
       break;
    case AST_BRIDGE_VIDEO_MODE_TALKER_SRC:
       if (bridge->softmix.video_mode.mode_data.talker_src_data.chan_vsrc == chan) {
          if (bridge->softmix.video_mode.mode_data.talker_src_data.chan_vsrc) {
             ast_channel_unref(bridge->softmix.video_mode.mode_data.talker_src_data.chan_vsrc);
          }
          bridge->softmix.video_mode.mode_data.talker_src_data.chan_vsrc = NULL;
          bridge->softmix.video_mode.mode_data.talker_src_data.average_talking_energy = 0;
       }
       if (bridge->softmix.video_mode.mode_data.talker_src_data.chan_old_vsrc == chan) {
          if (bridge->softmix.video_mode.mode_data.talker_src_data.chan_old_vsrc) {
             ast_channel_unref(bridge->softmix.video_mode.mode_data.talker_src_data.chan_old_vsrc);
          }
          bridge->softmix.video_mode.mode_data.talker_src_data.chan_old_vsrc = NULL;
       }
    case AST_BRIDGE_VIDEO_MODE_SFU:
       break;
    }
    ast_bridge_unlock(bridge);
 }
ast_bridge_set_binaural_active()
void ast_bridge_set_binaural_active (struct ast_bridge * bridge, unsigned int binaural_active)
Activates the use of binaural signals in a conference bridge.
Parameters
bridge Channel to activate the binaural signals.
binaural_active If true binaural signal processing will be active for the bridge.
Definition at line 3772 of file bridge.c.
References ast_bridge_lock, ast_bridge_unlock, ast_bridge_softmix::binaural_active, and ast_bridge::softmix.
Referenced by join_conference_bridge().
 {
    ast_bridge_lock(bridge);
    bridge->softmix.binaural_active = binaural_active;
    ast_bridge_unlock(bridge);
 }
ast_bridge_set_internal_sample_rate()
void ast_bridge_set_internal_sample_rate (struct ast_bridge * bridge, unsigned int sample_rate)
Adjust the internal mixing sample rate of a bridge used during multimix mode.
Parameters
bridge Channel to change the sample rate on.
sample_rate the sample rate to change to. If a value of 0 is passed here, the bridge will be free to pick what ever sample rate it chooses.
Definition at line 3779 of file bridge.c.
References ast_bridge_lock, ast_bridge_unlock, ast_bridge_softmix::internal_sample_rate, and ast_bridge::softmix.
Referenced by join_conference_bridge().
 {
    ast_bridge_lock(bridge);
    bridge->softmix.internal_sample_rate = sample_rate;
    ast_bridge_unlock(bridge);
 }
ast_bridge_set_maximum_sample_rate()
void ast_bridge_set_maximum_sample_rate (struct ast_bridge * bridge, unsigned int sample_rate)
Adjust the maximum mixing sample rate of a bridge used during multimix mode.
Since
13.31.0
16.8.0
17.2.0
Parameters
bridge Channel to change the sample rate on.
sample_rate the maximum sample rate to use. If a value of 0 is passed here, the bridge will be free to pick what ever sample rate it chooses.
Definition at line 3786 of file bridge.c.
References ast_bridge_lock, ast_bridge_unlock, ast_bridge_softmix::maximum_sample_rate, and ast_bridge::softmix.
Referenced by join_conference_bridge().
 {
    ast_bridge_lock(bridge);
    bridge->softmix.maximum_sample_rate = sample_rate;
    ast_bridge_unlock(bridge);
 }
ast_bridge_set_mixing_interval()
void ast_bridge_set_mixing_interval (struct ast_bridge * bridge, unsigned int mixing_interval)
Adjust the internal mixing interval of a bridge used during multimix mode.
Parameters
bridge Channel to change the sample rate on.
mixing_interval the sample rate to change to. If 0 is set the bridge tech is free to choose any mixing interval it uses by default.
Definition at line 3765 of file bridge.c.
References ast_bridge_lock, ast_bridge_unlock, ast_bridge_softmix::internal_mixing_interval, and ast_bridge::softmix.
Referenced by join_conference_bridge().
 {
    ast_bridge_lock(bridge);
    bridge->softmix.internal_mixing_interval = mixing_interval;
    ast_bridge_unlock(bridge);
 }
ast_bridge_set_remb_estimated_bitrate()
void ast_bridge_set_remb_estimated_bitrate (struct ast_bridge * bridge, float estimated_bitrate)
Force the REMB report estimated bitrate to a specific max value.
Parameters
bridge Bridge to set the REMB behavior on
estimated_bitrate The estimated bitrate in bits per second
Note
This can only be called when the bridge has been set to the SFU video mode.
Definition at line 3874 of file bridge.c.
References ast_assert, ast_bridge_lock, ast_bridge_unlock, AST_BRIDGE_VIDEO_MODE_SFU, ast_bridge_video_sfu_data::estimated_bitrate, ast_bridge_video_mode::mode, ast_bridge_video_mode::mode_data, ast_bridge_video_mode::sfu_data, ast_bridge::softmix, and ast_bridge_softmix::video_mode.
Referenced by join_conference_bridge().
 {
    ast_assert(bridge->softmix.video_mode.mode == AST_BRIDGE_VIDEO_MODE_SFU);
    ast_bridge_lock(bridge);
    bridge->softmix.video_mode.mode_data.sfu_data.estimated_bitrate = estimated_bitrate;
    ast_bridge_unlock(bridge);
 }
ast_bridge_set_remb_send_interval()
void ast_bridge_set_remb_send_interval (struct ast_bridge * bridge, unsigned int remb_send_interval)
Set the interval at which a combined REMB frame will be sent to video sources.
Parameters
bridge Bridge to set the REMB send interval on
remb_send_interval The REMB send interval
Note
This can only be called when the bridge has been set to the SFU video mode.
Definition at line 3856 of file bridge.c.
References ast_assert, ast_bridge_lock, ast_bridge_unlock, AST_BRIDGE_VIDEO_MODE_SFU, ast_bridge_video_mode::mode, ast_bridge_video_mode::mode_data, ast_bridge_video_sfu_data::remb_send_interval, ast_bridge_video_mode::sfu_data, ast_bridge::softmix, and ast_bridge_softmix::video_mode.
Referenced by join_conference_bridge().
 {
    ast_assert(bridge->softmix.video_mode.mode == AST_BRIDGE_VIDEO_MODE_SFU);
    ast_bridge_lock(bridge);
    bridge->softmix.video_mode.mode_data.sfu_data.remb_send_interval = remb_send_interval;
    ast_bridge_unlock(bridge);
 }
ast_bridge_set_send_sdp_label()
void ast_bridge_set_send_sdp_label (struct ast_bridge * bridge, unsigned int send_sdp_label)
Controls whether to send a "label" attribute in each stream in an SDP.
Since
16.1.0
Parameters
bridge The bridge
send_sdp_label Whether to send the labels or not
Note
The label will contain the uniqueid of the channel related to the stream. This is used to allow the recipient to correlate the stream to the participant information events sent by app_confbridge. The bridge will be locked in this function.
Definition at line 4033 of file bridge.c.
References ast_bridge_lock, ast_bridge_unlock, ast_bridge_softmix::send_sdp_label, and ast_bridge::softmix.
Referenced by join_conference_bridge().
 {
    ast_bridge_lock(bridge);
    bridge->softmix.send_sdp_label = send_sdp_label;
    ast_bridge_unlock(bridge);
 }
ast_bridge_set_sfu_video_mode()
void ast_bridge_set_sfu_video_mode (struct ast_bridge * bridge)
Set the bridge to be a selective forwarding unit.
Definition at line 3841 of file bridge.c.
References ast_bridge_lock, ast_bridge_unlock, AST_BRIDGE_VIDEO_MODE_SFU, cleanup_video_mode(), ast_bridge_video_mode::mode, ast_bridge::softmix, and ast_bridge_softmix::video_mode.
Referenced by bridge_stasis_new(), and join_conference_bridge().
 {
    ast_bridge_lock(bridge);
    cleanup_video_mode(bridge);
    bridge->softmix.video_mode.mode = AST_BRIDGE_VIDEO_MODE_SFU;
    ast_bridge_unlock(bridge);
 }
ast_bridge_set_single_src_video_mode()
void ast_bridge_set_single_src_video_mode (struct ast_bridge * bridge, struct ast_channel * video_src_chan)
Set a bridge to feed a single video source to all participants.
Definition at line 3816 of file bridge.c.
References ast_bridge_lock, ast_bridge_publish_state(), ast_bridge_unlock, AST_BRIDGE_VIDEO_MODE_SINGLE_SRC, ast_channel_name(), ast_channel_ref, ast_channel_uniqueid(), AST_CONTROL_VIDUPDATE, ast_indicate(), ast_verb, ast_bridge_video_single_src_data::chan_vsrc, cleanup_video_mode(), ast_bridge_video_mode::mode, ast_bridge_video_mode::mode_data, ast_bridge::name, ast_bridge_video_mode::single_src_data, ast_bridge::softmix, ast_bridge::uniqueid, and ast_bridge_softmix::video_mode.
Referenced by action_confbridgesetsinglevideosrc(), bridge_set_video_source_cb(), bridge_stasis_new(), execute_menu_entry(), handle_video_on_exit(), and handle_video_on_join().
 {
    ast_bridge_lock(bridge);
    cleanup_video_mode(bridge);
    bridge->softmix.video_mode.mode = AST_BRIDGE_VIDEO_MODE_SINGLE_SRC;
    if (video_src_chan) {
       bridge->softmix.video_mode.mode_data.single_src_data.chan_vsrc = ast_channel_ref(video_src_chan);
       ast_verb(5, "Video source in bridge '%s' (%s) is now '%s' (%s)\n",
          bridge->name, bridge->uniqueid,
          ast_channel_name(video_src_chan),
          ast_channel_uniqueid(video_src_chan));
       ast_indicate(video_src_chan, AST_CONTROL_VIDUPDATE);
    }
    ast_bridge_publish_state(bridge);
    ast_bridge_unlock(bridge);
 }
ast_bridge_set_talker_src_video_mode()
void ast_bridge_set_talker_src_video_mode (struct ast_bridge * bridge)
Set the bridge to pick the strongest talker supporting video as the single source video feed.
Definition at line 3833 of file bridge.c.
References ast_bridge_lock, ast_bridge_unlock, AST_BRIDGE_VIDEO_MODE_TALKER_SRC, cleanup_video_mode(), ast_bridge_video_mode::mode, ast_bridge::softmix, and ast_bridge_softmix::video_mode.
Referenced by ast_ari_bridges_clear_video_source(), bridge_stasis_new(), handle_video_on_exit(), and join_conference_bridge().
 {
    ast_bridge_lock(bridge);
    cleanup_video_mode(bridge);
    bridge->softmix.video_mode.mode = AST_BRIDGE_VIDEO_MODE_TALKER_SRC;
    ast_bridge_unlock(bridge);
 }
ast_bridge_set_transfer_variables()
void ast_bridge_set_transfer_variables (struct ast_channel * chan, const char * value, int is_attended)
Set the relevant transfer variables for a single channel.
Sets either the ATTENDEDTRANSFER or BLINDTRANSFER variable for a channel while clearing the opposite.
Parameters
chan Channel the variable is being set for
value Value the variable is being set to
is_attended false set BLINDTRANSFER and unset ATTENDEDTRANSFER true set ATTENDEDTRANSFER and unset BLINDTRANSFER
Definition at line 4404 of file bridge.c.
References ATTENDEDTRANSFER, BLINDTRANSFER, NULL, and pbx_builtin_setvar_helper().
Referenced by dial_transfer(), manager_park(), park_local_transfer(), parking_park_bridge_channel(), and set_transfer_variables_all().
 {
    char *writevar;
    char *erasevar;
    if (attended) {
       writevar = ATTENDEDTRANSFER;
       erasevar = BLINDTRANSFER;
    } else {
       writevar = BLINDTRANSFER;
       erasevar = ATTENDEDTRANSFER;
    }
    pbx_builtin_setvar_helper(chan, writevar, value);
    pbx_builtin_setvar_helper(chan, erasevar, NULL);
 }
ast_bridge_set_video_update_discard()
void ast_bridge_set_video_update_discard (struct ast_bridge * bridge, unsigned int video_update_discard)
Set the amount of time to discard subsequent video updates after a video update has been sent.
Parameters
bridge Bridge to set the minimum video update wait time on
video_update_discard Amount of time after sending a video update that others should be discarded
Definition at line 3849 of file bridge.c.
References ast_bridge_lock, ast_bridge_unlock, ast_bridge::softmix, ast_bridge_softmix::video_mode, and ast_bridge_video_mode::video_update_discard.
Referenced by bridge_stasis_new(), and join_conference_bridge().
 {
    ast_bridge_lock(bridge);
    bridge->softmix.video_mode.video_update_discard = video_update_discard;
    ast_bridge_unlock(bridge);
 }
ast_bridge_suspend()
int ast_bridge_suspend (struct ast_bridge * bridge, struct ast_channel * chan)
Suspend a channel temporarily from a bridge.
Parameters
bridge Bridge to suspend the channel from
chan Channel to suspend
Return values
0 on success
-1 on failure
Example usage:
ast_bridge_suspend(bridge, chan);
This suspends the channel pointed to by chan from the bridge pointed to by bridge temporarily. Control of the channel is given to the calling thread. This differs from ast_bridge_depart as the channel will not be removed from the bridge.
Note
This API call can be used on channels that were added to the bridge using both ast_bridge_join and ast_bridge_impart.
Definition at line 3068 of file bridge.c.
References ast_bridge_lock, ast_bridge_unlock, bridge_channel_internal_suspend_nolock(), and bridge_find_channel().
Referenced by conf_moh_start(), and conf_moh_stop().
 {
    struct ast_bridge_channel *bridge_channel;
 /* XXX ASTERISK-21271 the case of a disolved bridge while channel is suspended is not handled. */
 /* XXX ASTERISK-21271 suspend/unsuspend needs to be rethought. The caller must block until it has successfully suspended the channel for temporary control. */
 /* XXX ASTERISK-21271 external suspend/unsuspend needs to be eliminated. The channel may be playing a file at the time and stealing it then is not good. */
    ast_bridge_lock(bridge);
    if (!(bridge_channel = bridge_find_channel(bridge, chan))) {
       ast_bridge_unlock(bridge);
       return -1;
    }
    bridge_channel_internal_suspend_nolock(bridge_channel);
    ast_bridge_unlock(bridge);
    return 0;
 }
ast_bridge_transfer_acquire_bridge()
struct ast_bridge* ast_bridge_transfer_acquire_bridge (struct ast_channel * chan)
Acquire the channel's bridge for transfer purposes.
Since
13.21.0
Parameters
chan Channel involved in a transfer.
Returns
The bridge the channel is in or NULL if it either isn't in a bridge or should not be considered to be in a bridge.
Definition at line 4460 of file bridge.c.
References ao2_ref, AST_BRIDGE_FLAG_INVISIBLE, AST_BRIDGE_FLAG_MASQUERADE_ONLY, ast_channel_get_bridge(), ast_channel_lock, ast_channel_unlock, ast_test_flag, bridge_manager_request::bridge, ast_bridge::feature_flags, and NULL.
Referenced by ast_bridge_transfer_attended(), ast_bridge_transfer_blind(), handle_invite_replaces(), and invite_replaces().
 {
    struct ast_bridge *bridge;
    ast_channel_lock(chan);
    bridge = ast_channel_get_bridge(chan);
    ast_channel_unlock(chan);
    if (bridge && ast_test_flag(&bridge->feature_flags,
          (AST_BRIDGE_FLAG_MASQUERADE_ONLY | AST_BRIDGE_FLAG_INVISIBLE))) {
       ao2_ref(bridge, -1);
       bridge = NULL;
    }
    return bridge;
 }
ast_bridge_transfer_attended()
enum ast_transfer_result ast_bridge_transfer_attended (struct ast_channel * to_transferee, struct ast_channel * to_transfer_target)
Attended transfer.
The two channels are both transferer channels. The first is the channel that is bridged to the transferee (or if unbridged, the 'first' call of the transfer). The second is the channel that is bridged to the transfer target (or if unbridged, the 'second' call of the transfer).
Note
Absolutely NO channel locks should be held before calling this function.
Parameters
to_transferee Transferer channel on initial call (presumably bridged to transferee)
to_transfer_target Transferer channel on consultation call (presumably bridged to transfer target)
Returns
The success or failure of the attended transfer
Definition at line 4729 of file bridge.c.
References ao2_cleanup, ao2_container_count(), app, ast_attended_transfer_message_add_app(), ast_attended_transfer_message_create(), ast_bridge_channel_write_playfile(), ast_bridge_channel_write_unhold(), AST_BRIDGE_FLAG_TRANSFER_BRIDGE_ONLY, AST_BRIDGE_FLAG_TRANSFER_PROHIBITED, ast_bridge_lock, ast_bridge_lock_both, ast_bridge_peers_nolock(), ast_bridge_publish_attended_transfer(), ast_bridge_remove(), ast_bridge_transfer_acquire_bridge(), AST_BRIDGE_TRANSFER_FAIL, AST_BRIDGE_TRANSFER_INVALID, AST_BRIDGE_TRANSFER_NOT_PERMITTED, AST_BRIDGE_TRANSFER_SUCCESS, ast_bridge_unlock, ast_channel_appl(), ast_channel_get_bridge_channel(), ast_channel_lock, ast_channel_name(), ast_channel_unlock, ast_log, ast_softhangup(), AST_SOFTHANGUP_DEV, ast_strdupa, ast_strlen_zero, ast_test_flag, attended_transfer_bridge(), bridge_channel_internal_queue_attended_transfer(), channels, end, ast_bridge::feature_flags, get_transferee(), lock, LOG_ERROR, NULL, pbx_builtin_getvar_helper(), RAII_VAR, SCOPED_LOCK, set_transfer_variables_all(), and two_bridge_attended_transfer().
Referenced by analog_attempt_transfer(), AST_TEST_DEFINE(), attempt_transfer(), local_attended_transfer(), misdn_attempt_transfer(), refer_attended_task(), and skinny_transfer_attended().
 {
    RAII_VAR(struct ast_bridge *, to_transferee_bridge, NULL, ao2_cleanup);
    RAII_VAR(struct ast_bridge *, to_target_bridge, NULL, ao2_cleanup);
    RAII_VAR(struct ast_bridge_channel *, to_transferee_bridge_channel, NULL, ao2_cleanup);
    RAII_VAR(struct ast_bridge_channel *, to_target_bridge_channel, NULL, ao2_cleanup);
    RAII_VAR(struct ao2_container *, channels, NULL, ao2_cleanup);
    RAII_VAR(struct ast_channel *, transferee, NULL, ao2_cleanup);
    RAII_VAR(struct ast_attended_transfer_message *, transfer_msg, NULL, ao2_cleanup);
    struct ast_bridge *the_bridge = NULL;
    struct ast_channel *chan_bridged;
    struct ast_channel *chan_unbridged;
    int transfer_prohibited;
    int do_bridge_transfer;
    enum ast_transfer_result res;
    const char *app = NULL;
    int hangup_target = 0;
    to_transferee_bridge = ast_bridge_transfer_acquire_bridge(to_transferee);
    to_target_bridge = ast_bridge_transfer_acquire_bridge(to_transfer_target);
    transfer_msg = ast_attended_transfer_message_create(1, to_transferee, to_transferee_bridge,
          to_transfer_target, to_target_bridge, NULL, NULL);
    if (!transfer_msg) {
       ast_log(LOG_ERROR, "Unable to create Stasis publication for attended transfer from %s\n",
             ast_channel_name(to_transferee));
       return AST_BRIDGE_TRANSFER_FAIL;
    }
    /* They can't both be unbridged, you silly goose! */
    if (!to_transferee_bridge && !to_target_bridge) {
       res = AST_BRIDGE_TRANSFER_INVALID;
       goto end;
    }
    ast_channel_lock(to_transferee);
    to_transferee_bridge_channel = ast_channel_get_bridge_channel(to_transferee);
    ast_channel_unlock(to_transferee);
    ast_channel_lock(to_transfer_target);
    to_target_bridge_channel = ast_channel_get_bridge_channel(to_transfer_target);
    ast_channel_unlock(to_transfer_target);
    if (to_transferee_bridge_channel) {
       /* Take off hold if they are on hold. */
       if (ast_bridge_channel_write_unhold(to_transferee_bridge_channel)) {
          ast_log(LOG_ERROR, "Transferee channel disappeared during transfer!\n");
          res = AST_BRIDGE_TRANSFER_FAIL;
          goto end;
       }
    }
    if (to_target_bridge_channel) {
       const char *target_complete_sound;
       /* Take off hold if they are on hold. */
       if (ast_bridge_channel_write_unhold(to_target_bridge_channel)) {
          ast_log(LOG_ERROR, "Target channel disappeared during transfer!\n");
          res = AST_BRIDGE_TRANSFER_FAIL;
          goto end;
       }
       /* Is there a courtesy sound to play to the target? */
       ast_channel_lock(to_transfer_target);
       target_complete_sound = pbx_builtin_getvar_helper(to_transfer_target,
          "ATTENDED_TRANSFER_COMPLETE_SOUND");
       if (!ast_strlen_zero(target_complete_sound)) {
          target_complete_sound = ast_strdupa(target_complete_sound);
       } else {
          target_complete_sound = NULL;
       }
       ast_channel_unlock(to_transfer_target);
       if (!target_complete_sound) {
          ast_channel_lock(to_transferee);
          target_complete_sound = pbx_builtin_getvar_helper(to_transferee,
             "ATTENDED_TRANSFER_COMPLETE_SOUND");
          if (!ast_strlen_zero(target_complete_sound)) {
             target_complete_sound = ast_strdupa(target_complete_sound);
          } else {
             target_complete_sound = NULL;
          }
          ast_channel_unlock(to_transferee);
       }
       if (target_complete_sound) {
          ast_bridge_channel_write_playfile(to_target_bridge_channel, NULL,
             target_complete_sound, NULL);
       }
    }
    /* Let's get the easy one out of the way first */
    if (to_transferee_bridge && to_target_bridge) {
       if (!to_transferee_bridge_channel || !to_target_bridge_channel) {
          res = AST_BRIDGE_TRANSFER_INVALID;
          goto end;
       }
       ast_bridge_lock_both(to_transferee_bridge, to_target_bridge);
       res = two_bridge_attended_transfer(to_transferee, to_transferee_bridge_channel,
             to_transfer_target, to_target_bridge_channel,
             to_transferee_bridge, to_target_bridge, transfer_msg);
       ast_bridge_unlock(to_transferee_bridge);
       ast_bridge_unlock(to_target_bridge);
       hangup_target = 1;
       goto end;
    }
    the_bridge = to_transferee_bridge ?: to_target_bridge;
    chan_bridged = to_transferee_bridge ? to_transferee : to_transfer_target;
    chan_unbridged = to_transferee_bridge ? to_transfer_target : to_transferee;
    /*
     * Race condition makes it possible for app to be NULL, so get the app prior to
     * transferring with a fallback of "unknown".
     */
    app = ast_strdupa(ast_channel_appl(chan_unbridged) ?: "unknown");
    {
       int chan_count;
       SCOPED_LOCK(lock, the_bridge, ast_bridge_lock, ast_bridge_unlock);
       channels = ast_bridge_peers_nolock(the_bridge);
       if (!channels) {
          res = AST_BRIDGE_TRANSFER_FAIL;
          goto end;
       }
       chan_count = ao2_container_count(channels);
       if (chan_count <= 1) {
          res = AST_BRIDGE_TRANSFER_INVALID;
          goto end;
       }
       transfer_prohibited = ast_test_flag(&the_bridge->feature_flags,
             AST_BRIDGE_FLAG_TRANSFER_PROHIBITED);
       do_bridge_transfer = ast_test_flag(&the_bridge->feature_flags,
             AST_BRIDGE_FLAG_TRANSFER_BRIDGE_ONLY) ||
             chan_count > 2;
    }
    if (transfer_prohibited) {
       res = AST_BRIDGE_TRANSFER_NOT_PERMITTED;
       goto end;
    }
    set_transfer_variables_all(to_transferee, channels, 1);
    if (do_bridge_transfer) {
       /*
        * Hang up the target if it was bridged. Note, if it is not bridged
        * it is hung up during the masquerade.
        */
       hangup_target = chan_bridged == to_transfer_target;
       ast_bridge_lock(the_bridge);
       res = attended_transfer_bridge(chan_bridged, chan_unbridged, the_bridge, NULL, transfer_msg);
       ast_bridge_unlock(the_bridge);
       goto end;
    }
    transferee = get_transferee(channels, chan_bridged);
    if (!transferee) {
       res = AST_BRIDGE_TRANSFER_FAIL;
       goto end;
    }
    if (bridge_channel_internal_queue_attended_transfer(transferee, chan_unbridged)) {
       res = AST_BRIDGE_TRANSFER_FAIL;
       goto end;
    }
    ast_bridge_remove(the_bridge, chan_bridged);
    ast_attended_transfer_message_add_app(transfer_msg, app, NULL);
    res = AST_BRIDGE_TRANSFER_SUCCESS;
 end:
    if ((res == AST_BRIDGE_TRANSFER_SUCCESS && hangup_target) || res == AST_BRIDGE_TRANSFER_FAIL) {
       ast_softhangup(to_transfer_target, AST_SOFTHANGUP_DEV);
    }
    transfer_msg->result = res;
    ast_bridge_publish_attended_transfer(transfer_msg);
    return res;
 }
ast_bridge_transfer_blind()
enum ast_transfer_result ast_bridge_transfer_blind (int is_external, struct ast_channel * transferer, const char * exten, const char * context, transfer_channel_cb new_channel_cb, void * user_data)
Blind transfer target to the extension and context provided.
The channel given is bridged to one or multiple channels. Depending on the bridge and the number of participants, the entire bridge could be transferred to the given destination, or a single channel may be redirected.
Callers may also provide a callback to be called on the channel that will be running dialplan. The user data passed into ast_bridge_transfer_blind will be given as the argument to the callback to be interpreted as desired. This callback is guaranteed to be called in the same thread as ast_bridge_transfer_blind() and before ast_bridge_transfer_blind() returns.
Note
Absolutely NO channel locks should be held before calling this function.
Parameters
is_external Indicates that transfer was initiated externally
transferer The channel performing the blind transfer
exten The dialplan extension to send the call to
context The dialplan context to send the call to
new_channel_cb A callback to be called on the channel that will be executing dialplan
user_data Argument for new_channel_cb
Returns
The success or failure result of the blind transfer
Definition at line 4477 of file bridge.c.
References ao2_alloc, ao2_cleanup, ao2_container_count(), ast_blind_transfer_message_create(), ast_bridge_channel_write_unhold(), AST_BRIDGE_FLAG_TRANSFER_BRIDGE_ONLY, AST_BRIDGE_FLAG_TRANSFER_PROHIBITED, ast_bridge_lock, ast_bridge_peer(), ast_bridge_peers_nolock(), ast_bridge_publish_blind_transfer(), ast_bridge_remove(), ast_bridge_snapshot_create(), ast_bridge_transfer_acquire_bridge(), AST_BRIDGE_TRANSFER_FAIL, AST_BRIDGE_TRANSFER_INVALID, AST_BRIDGE_TRANSFER_NOT_PERMITTED, AST_BRIDGE_TRANSFER_SUCCESS, ast_bridge_unlock, ast_channel_cleanup, ast_channel_get_bridge_channel(), ast_channel_lock, ast_channel_name(), ast_channel_snapshot_get_latest(), ast_channel_uniqueid(), ast_channel_unlock, ast_log, ast_test_flag, blind_transfer_bridge(), bridge_manager_request::bridge, bridge_channel_internal_queue_blind_transfer(), channels, ast_bridge::feature_flags, lock, LOG_ERROR, NULL, publish, RAII_VAR, SCOPED_LOCK, set_transfer_variables_all(), and try_parking().
Referenced by action_blind_transfer(), blind_transfer_exec(), console_transfer(), feature_blind_transfer(), handle_request_refer(), refer_incoming_attended_request(), refer_incoming_blind_request(), skinny_transfer_blind(), and socket_process_helper().
 {
    RAII_VAR(struct ast_bridge *, bridge, NULL, ao2_cleanup);
    RAII_VAR(struct ast_bridge_channel *, bridge_channel, NULL, ao2_cleanup);
    RAII_VAR(struct ao2_container *, channels, NULL, ao2_cleanup);
    RAII_VAR(struct ast_channel *, transferee, NULL, ast_channel_cleanup);
    RAII_VAR(struct transfer_channel_data *, user_data_wrapper, NULL, ao2_cleanup);
    RAII_VAR(struct ast_blind_transfer_message *, transfer_message, NULL, ao2_cleanup);
    int do_bridge_transfer;
    int transfer_prohibited;
    enum ast_transfer_result transfer_result;
    transfer_message = ast_blind_transfer_message_create(is_external, transferer, exten, context);
    if (!transfer_message) {
       /* Out of memory. Not even possible to publish a Stasis message about the
        * failure
        */
       ast_log(LOG_ERROR, "Unable to allocate memory for blind transfer publication from %s\n",
             ast_channel_name(transferer));
       return AST_BRIDGE_TRANSFER_FAIL;
    }
    bridge = ast_bridge_transfer_acquire_bridge(transferer);
    if (!bridge) {
       transfer_result = AST_BRIDGE_TRANSFER_INVALID;
       goto publish;
    }
    ast_bridge_lock(bridge);
    transfer_message->bridge = ast_bridge_snapshot_create(bridge);
    ast_bridge_unlock(bridge);
    if (!transfer_message->bridge) {
       transfer_result = AST_BRIDGE_TRANSFER_FAIL;
       goto publish;
    }
    transferee = ast_bridge_peer(bridge, transferer);
    if (transferee) {
       transfer_message->transferee = ast_channel_snapshot_get_latest(ast_channel_uniqueid(transferee));
       if (!transfer_message->transferee) {
          transfer_result = AST_BRIDGE_TRANSFER_FAIL;
          goto publish;
       }
    }
    ast_channel_lock(transferer);
    bridge_channel = ast_channel_get_bridge_channel(transferer);
    ast_channel_unlock(transferer);
    if (!bridge_channel) {
       transfer_result = AST_BRIDGE_TRANSFER_INVALID;
       goto publish;
    }
    user_data_wrapper = ao2_alloc(sizeof(*user_data_wrapper), NULL);
    if (!user_data_wrapper) {
       transfer_result = AST_BRIDGE_TRANSFER_FAIL;
       goto publish;
    }
    user_data_wrapper->data = user_data;
    /* Take off hold if they are on hold. */
    ast_bridge_channel_write_unhold(bridge_channel);
    transfer_result = try_parking(transferer, context, exten, new_channel_cb, user_data_wrapper);
    if (transfer_result == AST_BRIDGE_TRANSFER_SUCCESS) {
       goto publish;
    }
    /* Since parking didn't take control of the user_data_wrapper, we are just going to raise the completed flag now. */
    user_data_wrapper->completed = 1;
    {
       SCOPED_LOCK(lock, bridge, ast_bridge_lock, ast_bridge_unlock);
       channels = ast_bridge_peers_nolock(bridge);
       if (!channels) {
          transfer_result = AST_BRIDGE_TRANSFER_FAIL;
          goto publish;
       }
       if (ao2_container_count(channels) <= 1) {
          transfer_result = AST_BRIDGE_TRANSFER_INVALID;
          goto publish;
       }
       transfer_prohibited = ast_test_flag(&bridge->feature_flags,
             AST_BRIDGE_FLAG_TRANSFER_PROHIBITED);
       do_bridge_transfer = ast_test_flag(&bridge->feature_flags,
             AST_BRIDGE_FLAG_TRANSFER_BRIDGE_ONLY) ||
             ao2_container_count(channels) > 2;
    }
    if (transfer_prohibited) {
       transfer_result = AST_BRIDGE_TRANSFER_NOT_PERMITTED;
       goto publish;
    }
    set_transfer_variables_all(transferer, channels, 0);
    if (do_bridge_transfer) {
       transfer_result = blind_transfer_bridge(is_external, transferer, bridge,
          exten, context, transferee, new_channel_cb, user_data_wrapper, transfer_message);
       goto publish;
    }
    /* Reaching this portion means that we're dealing with a two-party bridge */
    if (!transferee) {
       transfer_result = AST_BRIDGE_TRANSFER_FAIL;
       goto publish;
    }
    if (bridge_channel_internal_queue_blind_transfer(transferee, exten, context,
             new_channel_cb, user_data_wrapper)) {
       transfer_result = AST_BRIDGE_TRANSFER_FAIL;
       goto publish;
    }
    ast_bridge_remove(bridge, transferer);
    transfer_result = AST_BRIDGE_TRANSFER_SUCCESS;
 publish:
    transfer_message->result = transfer_result;
    ast_bridge_publish_blind_transfer(transfer_message);
    return transfer_result;
 }
ast_bridge_unreal_optimize_out()
int ast_bridge_unreal_optimize_out (struct ast_channel * chan, struct ast_channel * peer, struct ast_unreal_pvt * pvt)
Check and optimize out the unreal channels between bridges.
Since
12.0.0
Parameters
chan Unreal channel writing a frame into the channel driver.
peer Other unreal channel in the pair.
pvt Private data provided by an implementation of the unreal driver that contains the callbacks that should be called when optimization begins/ends
Note
It is assumed that chan is already locked.
Return values
0 if unreal channels were not optimized out.
non-zero if unreal channels were optimized out.
Definition at line 2968 of file bridge.c.
References ast_bridge_channel_unlock, ast_bridge_unlock, ast_channel_internal_bridge_channel(), ast_channel_unlock, optimize_lock_chan_stack(), optimize_lock_peer_stack(), try_merge_optimize_out(), and try_swap_optimize_out().
Referenced by got_optimized_out().
 {
    struct ast_bridge *chan_bridge;
    struct ast_bridge *peer_bridge;
    struct ast_bridge_channel *chan_bridge_channel;
    struct ast_bridge_channel *peer_bridge_channel;
    int res = 0;
    chan_bridge = optimize_lock_chan_stack(chan);
    if (!chan_bridge) {
       return res;
    }
    chan_bridge_channel = ast_channel_internal_bridge_channel(chan);
    peer_bridge = optimize_lock_peer_stack(peer);
    if (peer_bridge) {
       peer_bridge_channel = ast_channel_internal_bridge_channel(peer);
       res = try_swap_optimize_out(chan_bridge, chan_bridge_channel,
          peer_bridge, peer_bridge_channel, pvt);
       if (!res) {
          res = try_merge_optimize_out(chan_bridge, chan_bridge_channel,
             peer_bridge, peer_bridge_channel, pvt);
       } else if (0 < res) {
          res = 0;
       }
       /* Release peer locks. */
       ast_bridge_unlock(peer_bridge);
       ast_bridge_channel_unlock(peer_bridge_channel);
       ast_channel_unlock(peer);
    }
    /* Release chan locks. */
    ast_bridge_unlock(chan_bridge);
    ast_bridge_channel_unlock(chan_bridge_channel);
    return res;
 }
ast_bridge_unsuspend()
int ast_bridge_unsuspend (struct ast_bridge * bridge, struct ast_channel * chan)
Unsuspend a channel from a bridge.
Parameters
bridge Bridge to unsuspend the channel from
chan Channel to unsuspend
Return values
0 on success
-1 on failure
Example usage:
ast_bridge_unsuspend(bridge, chan);
This unsuspends the channel pointed to by chan from the bridge pointed to by bridge. The bridge will go back to handling the channel once this function returns.
Note
You must not mess with the channel once this function returns. Doing so may result in bad things happening.
Definition at line 3089 of file bridge.c.
References ast_bridge_lock, ast_bridge_unlock, bridge_channel_internal_unsuspend_nolock(), and bridge_find_channel().
Referenced by conf_moh_start(), and conf_moh_stop().
 {
    struct ast_bridge_channel *bridge_channel;
 /* XXX ASTERISK-21271 the case of a disolved bridge while channel is suspended is not handled. */
    ast_bridge_lock(bridge);
    if (!(bridge_channel = bridge_find_channel(bridge, chan))) {
       ast_bridge_unlock(bridge);
       return -1;
    }
    bridge_channel_internal_unsuspend_nolock(bridge_channel);
    ast_bridge_unlock(bridge);
    return 0;
 }
ast_bridge_update_talker_src_video_mode()
void ast_bridge_update_talker_src_video_mode (struct ast_bridge * bridge, struct ast_channel * chan, int talker_energy, int is_keyfame)
Update information about talker energy for talker src video mode.
Definition at line 3883 of file bridge.c.
References ast_bridge_lock, ast_bridge_publish_state(), ast_bridge_unlock, ast_channel_name(), ast_channel_nativeformats(), ast_channel_ref, ast_channel_uniqueid(), ast_channel_unref, AST_CONTROL_VIDUPDATE, ast_format_cap_has_type(), ast_indicate(), AST_MEDIA_TYPE_VIDEO, ast_verb, ast_bridge_video_talker_src_data::average_talking_energy, ast_bridge_video_talker_src_data::chan_old_vsrc, ast_bridge_video_talker_src_data::chan_vsrc, ast_bridge_video_mode::mode_data, ast_bridge::name, ast_bridge::softmix, ast_bridge_video_mode::talker_src_data, ast_bridge::uniqueid, and ast_bridge_softmix::video_mode.
Referenced by softmix_bridge_write_video().
 {
    struct ast_bridge_video_talker_src_data *data;
    /* If the channel doesn't support video, we don't care about it */
    if (!ast_format_cap_has_type(ast_channel_nativeformats(chan), AST_MEDIA_TYPE_VIDEO)) {
       return;
    }
    ast_bridge_lock(bridge);
    data = &bridge->softmix.video_mode.mode_data.talker_src_data;
    if (data->chan_vsrc == chan) {
       data->average_talking_energy = talker_energy;
    } else if ((data->average_talking_energy < talker_energy) && is_keyframe) {
       if (data->chan_old_vsrc) {
          data->chan_old_vsrc = ast_channel_unref(data->chan_old_vsrc);
       }
       if (data->chan_vsrc) {
          data->chan_old_vsrc = data->chan_vsrc;
          ast_indicate(data->chan_old_vsrc, AST_CONTROL_VIDUPDATE);
       }
       data->chan_vsrc = ast_channel_ref(chan);
       data->average_talking_energy = talker_energy;
       ast_verb(5, "Video source in bridge '%s' (%s) is now '%s' (%s)\n",
          bridge->name, bridge->uniqueid,
          ast_channel_name(data->chan_vsrc),
          ast_channel_uniqueid(data->chan_vsrc));
       ast_bridge_publish_state(bridge);
       ast_indicate(data->chan_vsrc, AST_CONTROL_VIDUPDATE);
    } else if ((data->average_talking_energy < talker_energy) && !is_keyframe) {
       ast_indicate(chan, AST_CONTROL_VIDUPDATE);
    } else if (!data->chan_vsrc && is_keyframe) {
       data->chan_vsrc = ast_channel_ref(chan);
       data->average_talking_energy = talker_energy;
       ast_verb(5, "Video source in bridge '%s' (%s) is now '%s' (%s)\n",
          bridge->name, bridge->uniqueid,
          ast_channel_name(data->chan_vsrc),
          ast_channel_uniqueid(data->chan_vsrc));
       ast_bridge_publish_state(bridge);
       ast_indicate(chan, AST_CONTROL_VIDUPDATE);
    } else if (!data->chan_old_vsrc && is_keyframe) {
       data->chan_old_vsrc = ast_channel_ref(chan);
       ast_indicate(chan, AST_CONTROL_VIDUPDATE);
    }
    ast_bridge_unlock(bridge);
 }
ast_bridge_vars_set()
void ast_bridge_vars_set (struct ast_channel * chan, const char * name, const char * pvtid)
Sets BRIDGECHANNEL and BRIDGEPVTCALLID for a channel.
Precondition
chan must be locked before calling
Parameters
name channel name of the bridged peer
pvtid Private CallID of the bridged peer
Returns
nothing
Definition at line 1242 of file bridge.c.
References ast_channel_stage_snapshot(), ast_channel_stage_snapshot_done(), and pbx_builtin_setvar_helper().
Referenced by ast_bridge_channel_leave_bridge_nolock(), set_bridge_peer_vars_2party(), set_bridge_peer_vars_holding(), and set_bridge_peer_vars_multiparty().
 {
    ast_channel_stage_snapshot(chan);
    pbx_builtin_setvar_helper(chan, "BRIDGEPEER", name);
    pbx_builtin_setvar_helper(chan, "BRIDGEPVTCALLID", pvtid);
    ast_channel_stage_snapshot_done(chan);
 }
ast_bridge_video_mode_to_string()
const char* ast_bridge_video_mode_to_string (enum ast_bridge_video_mode_type video_mode)
Converts an enum representation of a bridge video mode to string.
Parameters
video_mode The video mode
Return values
A string representation of video_mode
Definition at line 4018 of file bridge.c.
References AST_BRIDGE_VIDEO_MODE_NONE, AST_BRIDGE_VIDEO_MODE_SFU, AST_BRIDGE_VIDEO_MODE_SINGLE_SRC, and AST_BRIDGE_VIDEO_MODE_TALKER_SRC.
Referenced by ast_bridge_snapshot_to_json(), ast_manager_build_bridge_state_string_prefix(), and handle_bridge_show_specific().
 {
    switch (video_mode) {
    case AST_BRIDGE_VIDEO_MODE_TALKER_SRC:
       return "talker";
    case AST_BRIDGE_VIDEO_MODE_SINGLE_SRC:
       return "single";
    case AST_BRIDGE_VIDEO_MODE_SFU:
       return "sfu";
    case AST_BRIDGE_VIDEO_MODE_NONE:
    default:
       return "none";
    }
 }
ast_bridges()
struct ao2_container* ast_bridges (void)
Returns the global bridges container.
Since
17.0
Return values
a pointer to the bridges container success
NULL on failure
Note
You must use ao2_ref(<container>, -1) when done with it
Warning
You must not attempt to modify the container returned.
Definition at line 174 of file bridge.c.
References ao2_bump.
Referenced by ast_ari_bridges_list(), bridges_scrape_cb(), and manager_bridges_list().
 {
    return ao2_bump(bridges);
 }
ast_bridges_allow_optimization()
enum ast_bridge_optimization ast_bridges_allow_optimization (struct ast_bridge * chan_bridge, struct ast_bridge * peer_bridge)
Determine if bridges allow for optimization to occur betweem them.
Since
12.0.0
Parameters
chan_bridge First bridge being tested
peer_bridge Second bridge being tested
This determines if two bridges allow for unreal channel optimization to occur between them. The function does not require for unreal channels to already be in the bridges when called.
Note
It is assumed that both bridges are locked prior to calling this function
A return other than AST_BRIDGE_OPTIMIZE_PROHIBITED does not guarantee that an optimization attempt will succeed. However, a return of AST_BRIDGE_OPTIMIZE_PROHIBITED guarantees that an optimization attempt will never succeed.
Returns
Optimization allowability for the bridges
Definition at line 3008 of file bridge.c.
References AST_BRIDGE_OPTIMIZE_MERGE_TO_CHAN_BRIDGE, AST_BRIDGE_OPTIMIZE_MERGE_TO_PEER_BRIDGE, AST_BRIDGE_OPTIMIZE_PROHIBITED, AST_BRIDGE_OPTIMIZE_SWAP_TO_CHAN_BRIDGE, AST_BRIDGE_OPTIMIZE_SWAP_TO_PEER_BRIDGE, bridge_allows_optimization(), bridges_allow_merge_optimization(), bridges_allow_swap_optimization(), merge_direction::dest, MERGE_ALLOWED, SWAP_PROHIBITED, SWAP_TO_CHAN_BRIDGE, and SWAP_TO_PEER_BRIDGE.
Referenced by two_bridge_attended_transfer().
 {
    struct merge_direction merge;
    if (!bridge_allows_optimization(chan_bridge) || !bridge_allows_optimization(peer_bridge)) {
       return AST_BRIDGE_OPTIMIZE_PROHIBITED;
    }
    switch (bridges_allow_swap_optimization(chan_bridge, peer_bridge)) {
    case SWAP_TO_CHAN_BRIDGE:
       return AST_BRIDGE_OPTIMIZE_SWAP_TO_CHAN_BRIDGE;
    case SWAP_TO_PEER_BRIDGE:
       return AST_BRIDGE_OPTIMIZE_SWAP_TO_PEER_BRIDGE;
    case SWAP_PROHIBITED:
    default:
       break;
    }
    /* Two channels will be kicked from the bridges, the unreal;1 and unreal;2 channels */
    if (bridges_allow_merge_optimization(chan_bridge, peer_bridge, 2, &merge) != MERGE_ALLOWED) {
       return AST_BRIDGE_OPTIMIZE_PROHIBITED;
    }
    if (merge.dest == chan_bridge) {
       return AST_BRIDGE_OPTIMIZE_MERGE_TO_CHAN_BRIDGE;
    } else {
       return AST_BRIDGE_OPTIMIZE_MERGE_TO_PEER_BRIDGE;
    }
 }
ast_brige_set_remb_behavior()
void ast_brige_set_remb_behavior (struct ast_bridge * bridge, enum ast_bridge_video_sfu_remb_behavior behavior)
Set the REMB report generation behavior on a bridge.
Parameters
bridge Bridge to set the REMB behavior on
behavior How REMB reports are generated
Note
This can only be called when the bridge has been set to the SFU video mode.
Definition at line 3865 of file bridge.c.
References ast_assert, ast_bridge_lock, ast_bridge_unlock, AST_BRIDGE_VIDEO_MODE_SFU, ast_bridge_video_mode::mode, ast_bridge_video_mode::mode_data, ast_bridge_video_sfu_data::remb_behavior, ast_bridge_video_mode::sfu_data, ast_bridge::softmix, and ast_bridge_softmix::video_mode.
Referenced by join_conference_bridge().
 {
    ast_assert(bridge->softmix.video_mode.mode == AST_BRIDGE_VIDEO_MODE_SFU);
    ast_bridge_lock(bridge);
    bridge->softmix.video_mode.mode_data.sfu_data.remb_behavior = behavior;
    ast_bridge_unlock(bridge);
 }
Variable Documentation
ast_bridge_base_v_table
struct ast_bridge_methods ast_bridge_base_v_table
Bridge base class virtual method table.
Definition at line 949 of file bridge.c.
Referenced by ast_bridging_init_basic(), bridge_agent_hold_dissolving(), bridge_agent_hold_pull(), bridge_agent_hold_push(), bridge_basic_destroy(), bridge_basic_pull(), bridge_basic_push(), bridge_init_agent_hold(), bridge_parking_destroy(), bridge_parking_dissolving(), bridge_parking_get_merge_priority(), bridge_parking_notify_masquerade(), bridge_parking_pull(), bridge_parking_push(), bridge_stasis_init(), bridge_stasis_pull(), bridge_stasis_push(), and bridge_stasis_push_peek().