Asterisk - The Open Source Telephony Project: func_talkdetect.c File Reference
func_talkdetect.c File Reference
Module: Dial plan functions
Function that raises events when talking is detected on a channel.
#include "asterisk.h"
#include "asterisk/module.h"
#include "asterisk/channel.h"
#include "asterisk/pbx.h"
#include "asterisk/app.h"
#include "asterisk/dsp.h"
#include "asterisk/audiohook.h"
#include "asterisk/stasis.h"
#include "asterisk/stasis_channels.h"
Data Structures
struct talk_detect_params
Private data structure used with the function's datastore.
Macros
#define DEFAULT_SILENCE_THRESHOLD 2500
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static void datastore_destroy_cb (void *data)
static int load_module (void)
static int remove_talk_detect (struct ast_channel *chan)
static int set_talk_detect (struct ast_channel *chan, int dsp_silence_threshold, int dsp_talking_threshold)
static int talk_detect_audiohook_cb (struct ast_audiohook *audiohook, struct ast_channel *chan, struct ast_frame *frame, enum ast_audiohook_direction direction)
static int talk_detect_fn_write (struct ast_channel *chan, const char *function, char *data, const char *value)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Talk detection dialplan function" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, }
static const struct ast_module_info * ast_module_info = &__mod_info
static const struct ast_datastore_info talk_detect_datastore
The channel datastore the function uses to store state.
static struct ast_custom_function talk_detect_function
Definition of the TALK_DETECT function.
Detailed Description
Function that raises events when talking is detected on a channel.
Author
Matt Jordan mjord.nosp@m.an@d.nosp@m.igium.nosp@m..com
Definition in file func_talkdetect.c.
Macro Definition Documentation
DEFAULT_SILENCE_THRESHOLD
#define DEFAULT_SILENCE_THRESHOLD 2500
Definition at line 115 of file func_talkdetect.c.
Referenced by talk_detect_fn_write().
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 403 of file func_talkdetect.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 403 of file func_talkdetect.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 403 of file func_talkdetect.c.
datastore_destroy_cb()
static void datastore_destroy_cb (void * data) static
Definition at line 134 of file func_talkdetect.c.
References ast_audiohook_destroy(), ast_dsp_free(), ast_free, talk_detect_params::audiohook, and talk_detect_params::dsp.
{
    struct talk_detect_params *td_params = data;
    ast_audiohook_destroy(&td_params->audiohook);
    if (td_params->dsp) {
       ast_dsp_free(td_params->dsp);
    }
    ast_free(data);
 }
load_module()
static int load_module (void) static
Definition at line 394 of file func_talkdetect.c.
References ast_custom_function_register, AST_MODULE_LOAD_DECLINE, and AST_MODULE_LOAD_SUCCESS.
 {
    int res = 0;
    res |= ast_custom_function_register(&talk_detect_function);
    return res ? AST_MODULE_LOAD_DECLINE : AST_MODULE_LOAD_SUCCESS;
 }
remove_talk_detect()
static int remove_talk_detect (struct ast_channel * chan) static
Definition at line 229 of file func_talkdetect.c.
References ast_audiohook_remove(), ast_channel_datastore_find(), ast_channel_datastore_remove(), ast_channel_name(), ast_datastore_free(), ast_log, AST_LOG_WARNING, talk_detect_params::audiohook, ast_datastore::data, NULL, and SCOPED_CHANNELLOCK.
Referenced by talk_detect_fn_write().
 {
    struct ast_datastore *datastore = NULL;
    struct talk_detect_params *td_params;
    SCOPED_CHANNELLOCK(chan_lock, chan);
    datastore = ast_channel_datastore_find(chan, &talk_detect_datastore, NULL);
    if (!datastore) {
       ast_log(AST_LOG_WARNING, "Cannot remove TALK_DETECT from %s: TALK_DETECT not currently enabled\n",
               ast_channel_name(chan));
       return -1;
    }
    td_params = datastore->data;
    if (ast_audiohook_remove(chan, &td_params->audiohook)) {
       ast_log(AST_LOG_WARNING, "Failed to remove TALK_DETECT audiohook from channel %s\n",
               ast_channel_name(chan));
       return -1;
    }
    if (ast_channel_datastore_remove(chan, datastore)) {
       ast_log(AST_LOG_WARNING, "Failed to remove TALK_DETECT datastore from channel %s\n",
               ast_channel_name(chan));
       return -1;
    }
    ast_datastore_free(datastore);
    return 0;
 }
set_talk_detect()
static int set_talk_detect (struct ast_channel * chan, int dsp_silence_threshold, int dsp_talking_threshold) static
Definition at line 260 of file func_talkdetect.c.
References ast_audiohook_attach(), ast_audiohook_init(), AST_AUDIOHOOK_MANIPULATE_ALL_RATES, AST_AUDIOHOOK_TRIGGER_READ, AST_AUDIOHOOK_TYPE_MANIPULATE, ast_calloc, ast_channel_datastore_add(), ast_channel_datastore_find(), ast_channel_rawreadformat(), ast_datastore_alloc, ast_datastore_free(), ast_dsp_new_with_rate(), ast_dsp_set_threshold(), ast_format_get_sample_rate(), ast_free, ast_set_flag, talk_detect_params::audiohook, ast_datastore::data, talk_detect_params::dsp, talk_detect_params::dsp_silence_threshold, talk_detect_params::dsp_talking_threshold, ast_audiohook::manipulate_callback, NULL, SCOPED_CHANNELLOCK, and talk_detect_audiohook_cb().
Referenced by talk_detect_fn_write().
 {
    struct ast_datastore *datastore = NULL;
    struct talk_detect_params *td_params;
    SCOPED_CHANNELLOCK(chan_lock, chan);
    datastore = ast_channel_datastore_find(chan, &talk_detect_datastore, NULL);
    if (!datastore) {
       datastore = ast_datastore_alloc(&talk_detect_datastore, NULL);
       if (!datastore) {
          return -1;
       }
       td_params = ast_calloc(1, sizeof(*td_params));
       if (!td_params) {
          ast_datastore_free(datastore);
          return -1;
       }
       ast_audiohook_init(&td_params->audiohook,
                          AST_AUDIOHOOK_TYPE_MANIPULATE,
                          "TALK_DETECT",
                          AST_AUDIOHOOK_MANIPULATE_ALL_RATES);
       td_params->audiohook.manipulate_callback = talk_detect_audiohook_cb;
       ast_set_flag(&td_params->audiohook, AST_AUDIOHOOK_TRIGGER_READ);
       td_params->dsp = ast_dsp_new_with_rate(ast_format_get_sample_rate(ast_channel_rawreadformat(chan)));
       if (!td_params->dsp) {
          ast_datastore_free(datastore);
          ast_free(td_params);
          return -1;
       }
       datastore->data = td_params;
       ast_channel_datastore_add(chan, datastore);
       ast_audiohook_attach(chan, &td_params->audiohook);
    } else {
       /* Talk detection already enabled; update existing settings */
       td_params = datastore->data;
    }
    td_params->dsp_talking_threshold = dsp_talking_threshold;
    td_params->dsp_silence_threshold = dsp_silence_threshold;
    ast_dsp_set_threshold(td_params->dsp, td_params->dsp_talking_threshold);
    return 0;
 }
talk_detect_audiohook_cb()
static int talk_detect_audiohook_cb (struct ast_audiohook * audiohook, struct ast_channel * chan, struct ast_frame * frame, enum ast_audiohook_direction direction) static
Definition at line 159 of file func_talkdetect.c.
References ao2_ref, AST_AUDIOHOOK_DIRECTION_READ, AST_AUDIOHOOK_STATUS_DONE, ast_channel_blob_create_from_cache(), ast_channel_datastore_find(), ast_channel_name(), ast_channel_talking_start(), ast_channel_talking_stop(), ast_channel_topic(), ast_channel_uniqueid(), ast_dsp_silence(), AST_FRAME_VOICE, ast_json_pack(), ast_json_unref(), ast_tvdiff_ms(), ast_tvnow(), ast_verb, ast_datastore::data, talk_detect_params::dsp, talk_detect_params::dsp_silence_threshold, ast_frame::frametype, NULL, stasis_publish(), ast_audiohook::status, talk_detect_params::talking, and talk_detect_params::talking_start.
Referenced by set_talk_detect().
 {
    int total_silence;
    int update_talking = 0;
    struct ast_datastore *datastore;
    struct talk_detect_params *td_params;
    struct stasis_message *message;
    if (audiohook->status == AST_AUDIOHOOK_STATUS_DONE) {
       return 1;
    }
    if (direction != AST_AUDIOHOOK_DIRECTION_READ) {
       return 1;
    }
    if (frame->frametype != AST_FRAME_VOICE) {
       return 1;
    }
    if (!(datastore = ast_channel_datastore_find(chan, &talk_detect_datastore, NULL))) {
       return 1;
    }
    td_params = datastore->data;
    ast_dsp_silence(td_params->dsp, frame, &total_silence);
    if (total_silence < td_params->dsp_silence_threshold) {
       if (!td_params->talking) {
          update_talking = 1;
          td_params->talking_start = ast_tvnow();
       }
       td_params->talking = 1;
    } else {
       if (td_params->talking) {
          update_talking = 1;
       }
       td_params->talking = 0;
    }
    if (update_talking) {
       struct ast_json *blob = NULL;
       if (!td_params->talking) {
          int64_t diff_ms = ast_tvdiff_ms(ast_tvnow(), td_params->talking_start);
          diff_ms -= td_params->dsp_silence_threshold;
          blob = ast_json_pack("{s: I}", "duration", (ast_json_int_t)diff_ms);
          if (!blob) {
             return 1;
          }
       }
       ast_verb(4, "%s is now %s\n", ast_channel_name(chan),
                   td_params->talking ? "talking" : "silent");
       message = ast_channel_blob_create_from_cache(ast_channel_uniqueid(chan),
                       td_params->talking ? ast_channel_talking_start() : ast_channel_talking_stop(),
                       blob);
       if (message) {
          stasis_publish(ast_channel_topic(chan), message);
          ao2_ref(message, -1);
       }
       ast_json_unref(blob);
    }
    return 1;
 }
talk_detect_fn_write()
static int talk_detect_fn_write (struct ast_channel * chan, const char * function, char * data, const char * value) static
Definition at line 310 of file func_talkdetect.c.
References args, AST_APP_ARG, AST_DECLARE_APP_ARGS, ast_dsp_get_threshold_from_settings(), ast_log, AST_LOG_WARNING, AST_STANDARD_APP_ARGS, ast_strdupa, ast_strlen_zero, DEFAULT_SILENCE_THRESHOLD, talk_detect_params::dsp_silence_threshold, talk_detect_params::dsp_talking_threshold, parse(), remove_talk_detect(), set_talk_detect(), and THRESHOLD_SILENCE.
 {
    int res;
    if (!chan) {
       return -1;
    }
    if (ast_strlen_zero(data)) {
       ast_log(AST_LOG_WARNING, "TALK_DETECT requires an argument\n");
       return -1;
    }
    if (!strcasecmp(data, "set")) {
       int dsp_silence_threshold = DEFAULT_SILENCE_THRESHOLD;
       int dsp_talking_threshold = ast_dsp_get_threshold_from_settings(THRESHOLD_SILENCE);
       if (!ast_strlen_zero(value)) {
          char *parse = ast_strdupa(value);
          AST_DECLARE_APP_ARGS(args,
             AST_APP_ARG(silence_threshold);
             AST_APP_ARG(talking_threshold);
          );
          AST_STANDARD_APP_ARGS(args, parse);
          if (!ast_strlen_zero(args.silence_threshold)) {
             if (sscanf(args.silence_threshold, "%30d", &dsp_silence_threshold) != 1) {
                ast_log(AST_LOG_WARNING, "Failed to parse %s for dsp_silence_threshold\n",
                        args.silence_threshold);
                return -1;
             }
             if (dsp_silence_threshold < 1) {
                ast_log(AST_LOG_WARNING, "Invalid value %d for dsp_silence_threshold\n",
                        dsp_silence_threshold);
                return -1;
             }
          }
          if (!ast_strlen_zero(args.talking_threshold)) {
             if (sscanf(args.talking_threshold, "%30d", &dsp_talking_threshold) != 1) {
                ast_log(AST_LOG_WARNING, "Failed to parse %s for dsp_talking_threshold\n",
                        args.talking_threshold);
                return -1;
             }
             if (dsp_talking_threshold < 1) {
                ast_log(AST_LOG_WARNING, "Invalid value %d for dsp_talking_threshold\n",
                        dsp_silence_threshold);
                return -1;
             }
          }
       }
       res = set_talk_detect(chan, dsp_silence_threshold, dsp_talking_threshold);
    } else if (!strcasecmp(data, "remove")) {
       res = remove_talk_detect(chan);
    } else {
       ast_log(AST_LOG_WARNING, "TALK_DETECT: unknown option %s\n", data);
       res = -1;
    }
    return res;
 }
unload_module()
static int unload_module (void) static
Definition at line 384 of file func_talkdetect.c.
References ast_custom_function_unregister().
 {
    int res = 0;
    res |= ast_custom_function_unregister(&talk_detect_function);
    return res;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Talk detection dialplan function" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, } static
Definition at line 403 of file func_talkdetect.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 403 of file func_talkdetect.c.
talk_detect_datastore
const struct ast_datastore_info talk_detect_datastore static
Initial value:
= {
   .type = "talk_detect",
   .destroy = datastore_destroy_cb
}
The channel datastore the function uses to store state.
Definition at line 146 of file func_talkdetect.c.
talk_detect_function
struct ast_custom_function talk_detect_function static
Initial value:
= {
   .name = "TALK_DETECT",
   .write = talk_detect_fn_write,
}
Definition of the TALK_DETECT function.
Definition at line 378 of file func_talkdetect.c.