Asterisk - The Open Source Telephony Project: test_optional_api.c File Reference
test_optional_api.c File Reference
Test optional API.
#include "asterisk.h"
#include "asterisk/module.h"
#include "asterisk/optional_api.h"
#include "asterisk/test.h"
Macros
#define CATEGORY "/main/optional_api/"
#define SYMNAME "test_option"
Enumerations
enum was_called { NONE, STUB, IMPL }
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
AST_TEST_DEFINE (test_provide_first)
AST_TEST_DEFINE (test_provide_last)
static int load_module (void)
static void test_optional (void)
static void test_optional_impl (void)
static void test_optional_stub (void)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_DEFAULT , .description = "ARI testing" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, }
static const struct ast_module_info * ast_module_info = &__mod_info
ast_optional_fn test_optional_ref
enum was_called was_called_result
Detailed Description
Test optional API.
This tests exercise the underlying implementation functions. Acutal usage won't look anything like this; it would use the wrapper macros.
Author
David M. Lee, II <dlee@digium.com>
Definition in file test_optional_api.c.
Macro Definition Documentation
CATEGORY
#define CATEGORY "/main/optional_api/"
Definition at line 43 of file test_optional_api.c.
Referenced by AST_TEST_DEFINE().
SYMNAME
#define SYMNAME "test_option"
Definition at line 73 of file test_optional_api.c.
Referenced by AST_TEST_DEFINE().
Enumeration Type Documentation
was_called
enum was_called
Enumerator
NONE
STUB
IMPL
Definition at line 45 of file test_optional_api.c.
                 {
    NONE,
    STUB,
    IMPL
 };
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 187 of file test_optional_api.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 187 of file test_optional_api.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 187 of file test_optional_api.c.
AST_TEST_DEFINE() [1/2]
AST_TEST_DEFINE (test_provide_first)
Definition at line 75 of file test_optional_api.c.
References AST_MODULE, ast_optional_api_provide(), ast_optional_api_unprovide(), ast_optional_api_unuse(), ast_optional_api_use(), AST_TEST_FAIL, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_test_status_update, CATEGORY, done, IMPL, sip_to_pjsip::info(), SYMNAME, TEST_EXECUTE, TEST_INIT, test_optional(), test_optional_impl(), test_optional_ref, test_optional_stub(), and was_called_result.
 {
    enum ast_test_result_state res;
    switch (cmd) {
    case TEST_INIT:
       info->name = __func__;
       info->category = CATEGORY;
       info->summary = "Test optional API publishing.";
       info->description = "Test optional API publishing.";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    res = AST_TEST_FAIL;
    test_optional_ref = 0;
    ast_optional_api_provide(SYMNAME, test_optional_impl);
    ast_optional_api_use(SYMNAME, &test_optional_ref, test_optional_stub,
       AST_MODULE);
    test_optional();
    if (was_called_result != IMPL) {
       ast_test_status_update(test, "Expected %d, was %u",
          IMPL, was_called_result);
       goto done;
    }
    res = AST_TEST_PASS;
  done:
    ast_optional_api_unuse(SYMNAME, &test_optional_ref, AST_MODULE);
    ast_optional_api_unprovide(SYMNAME, test_optional_impl);
    return res;
 }
AST_TEST_DEFINE() [2/2]
AST_TEST_DEFINE (test_provide_last)
Definition at line 114 of file test_optional_api.c.
References AST_MODULE, ast_optional_api_provide(), ast_optional_api_unprovide(), ast_optional_api_unuse(), ast_optional_api_use(), AST_TEST_FAIL, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_test_status_update, CATEGORY, done, IMPL, sip_to_pjsip::info(), STUB, SYMNAME, TEST_EXECUTE, TEST_INIT, test_optional(), test_optional_impl(), test_optional_ref, test_optional_stub(), and was_called_result.
 {
    enum ast_test_result_state res;
    switch (cmd) {
    case TEST_INIT:
       info->name = __func__;
       info->category = CATEGORY;
       info->summary = "Test optional API publishing.";
       info->description = "Test optional API publishing.";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    res = AST_TEST_FAIL;
    test_optional_ref = 0;
    ast_optional_api_use(SYMNAME, &test_optional_ref, test_optional_stub,
       AST_MODULE);
    test_optional();
    if (was_called_result != STUB) {
       ast_test_status_update(test, "Expected %d, was %u",
          STUB, was_called_result);
       goto done;
    }
    ast_optional_api_provide(SYMNAME, test_optional_impl);
    test_optional();
    if (was_called_result != IMPL) {
       ast_test_status_update(test, "Expected %d, was %u",
          IMPL, was_called_result);
       ast_optional_api_unprovide(SYMNAME, test_optional_impl);
       goto done;
    }
    ast_optional_api_unprovide(SYMNAME, test_optional_impl);
    test_optional();
    if (was_called_result != STUB) {
       ast_test_status_update(test, "Expected %d, was %u",
          STUB, was_called_result);
       ast_optional_api_unprovide(SYMNAME, test_optional_impl);
       goto done;
    }
    res = AST_TEST_PASS;
  done:
    ast_optional_api_unuse(SYMNAME, &test_optional_ref, AST_MODULE);
    return res;
 }
load_module()
static int load_module (void) static
Definition at line 176 of file test_optional_api.c.
References AST_MODFLAG_DEFAULT, AST_MODULE_INFO(), AST_MODULE_LOAD_SUCCESS, AST_MODULE_SUPPORT_CORE, AST_TEST_REGISTER, ASTERISK_GPL_KEY, and unload_module().
 {
    AST_TEST_REGISTER(test_provide_first);
    AST_TEST_REGISTER(test_provide_last);
    return AST_MODULE_LOAD_SUCCESS;
 }
test_optional()
static void test_optional (void) static
Definition at line 65 of file test_optional_api.c.
References NONE, test_optional_ref, and was_called_result.
Referenced by AST_TEST_DEFINE().
 {
    was_called_result = NONE;
    if (test_optional_ref) {
       test_optional_ref();
    }
 }
test_optional_impl()
static void test_optional_impl (void) static
Definition at line 60 of file test_optional_api.c.
References IMPL, and was_called_result.
Referenced by AST_TEST_DEFINE().
 {
    was_called_result = IMPL;
 }
test_optional_stub()
static void test_optional_stub (void) static
Definition at line 55 of file test_optional_api.c.
References STUB, and was_called_result.
Referenced by AST_TEST_DEFINE().
 {
    was_called_result = STUB;
 }
unload_module()
static int unload_module (void) static
Definition at line 169 of file test_optional_api.c.
References AST_TEST_UNREGISTER.
Referenced by load_module().
 {
    AST_TEST_UNREGISTER(test_provide_first);
    AST_TEST_UNREGISTER(test_provide_last);
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_DEFAULT , .description = "ARI testing" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, } static
Definition at line 187 of file test_optional_api.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 187 of file test_optional_api.c.
test_optional_ref
ast_optional_fn test_optional_ref
Definition at line 53 of file test_optional_api.c.
Referenced by AST_TEST_DEFINE(), and test_optional().
was_called_result
enum was_called was_called_result
Definition at line 51 of file test_optional_api.c.
Referenced by AST_TEST_DEFINE(), test_optional(), test_optional_impl(), and test_optional_stub().