Asterisk - The Open Source Telephony Project: test_xml_escape.c File Reference
test_xml_escape.c File Reference
Test ast_xml_escape.
#include "asterisk.h"
#include "asterisk/utils.h"
#include "asterisk/module.h"
#include "asterisk/test.h"
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
AST_TEST_DEFINE (xml_escape_test)
static int load_module (void)
static void test_xml (struct ast_test *test, const char *input, const char *expected, int max_len, int expected_res)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Skeleton (sample) Test" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, }
static const struct ast_module_info * ast_module_info = &__mod_info
static enum ast_test_result_state test_res = AST_TEST_PASS
Detailed Description
Test ast_xml_escape.
Author
David M. Lee, II <dlee@digium.com>
Definition in file test_xml_escape.c.
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 116 of file test_xml_escape.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 116 of file test_xml_escape.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 116 of file test_xml_escape.c.
AST_TEST_DEFINE()
AST_TEST_DEFINE (xml_escape_test)
Definition at line 62 of file test_xml_escape.c.
References AST_TEST_NOT_RUN, AST_TEST_PASS, sip_to_pjsip::info(), input(), TEST_EXECUTE, TEST_INIT, test_res, and test_xml().
 {
    char *input;
    char *expected;
    switch (cmd) {
    case TEST_INIT:
       info->name = "xml_escape_test";
       info->category = "/main/xml_escape/";
       info->summary = "Test XML escaping";
       info->description =
          "Test XML escaping";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    test_res = AST_TEST_PASS;
    /* happy path */
    input = "encode me: <&>'\"";
    expected = "encode me: &lt;&amp;&gt;&apos;&quot;";
    test_xml(test, input, expected, -1, 0);
    /* size 0 should fail without changing anything */
    input = "foo";
    expected = "";
    test_xml(test, input, expected, 0, -1);
    /* truncate chars */
    input = "<truncated>";
    expected = "&lt;trunc";
    test_xml(test, input, expected, 10, -1);
    /* truncate entity */
    input = "trunc<";
    expected = "trunc";
    test_xml(test, input, expected, 9, -1);
    return test_res;
 }
load_module()
static int load_module (void) static
Definition at line 110 of file test_xml_escape.c.
References AST_MODULE_LOAD_SUCCESS, and AST_TEST_REGISTER.
 {
    AST_TEST_REGISTER(xml_escape_test);
    return AST_MODULE_LOAD_SUCCESS;
 }
test_xml()
static void test_xml (struct ast_test * test, const char * input, const char * expected, int max_len, int expected_res) static
Definition at line 41 of file test_xml_escape.c.
References AST_TEST_FAIL, ast_test_status_update, ast_xml_escape(), and test_res.
Referenced by AST_TEST_DEFINE().
 {
    char actual[256] = "";
    int res;
    if (max_len == -1) {
       max_len = sizeof(actual);
    }
    res = ast_xml_escape(input, actual, max_len);
    if (res != expected_res) {
       ast_test_status_update(test, "Expected result '%d', got '%d'\n", expected_res, res);
       test_res = AST_TEST_FAIL;
    }
    if (strcmp(expected, actual) != 0) {
       ast_test_status_update(test, "Expected output '%s', got '%s'\n", expected, actual);
       test_res = AST_TEST_FAIL;
    }
 }
unload_module()
static int unload_module (void) static
Definition at line 104 of file test_xml_escape.c.
References AST_TEST_UNREGISTER.
 {
    AST_TEST_UNREGISTER(xml_escape_test);
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Skeleton (sample) Test" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, } static
Definition at line 116 of file test_xml_escape.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 116 of file test_xml_escape.c.
test_res
enum ast_test_result_state test_res = AST_TEST_PASS static
Definition at line 39 of file test_xml_escape.c.
Referenced by AST_TEST_DEFINE(), and test_xml().