Asterisk - The Open Source Telephony Project: json.c File Reference
json.c File Reference
JSON abstraction layer.
#include "asterisk.h"
#include "asterisk/json.h"
#include "asterisk/localtime.h"
#include "asterisk/module.h"
#include "asterisk/utils.h"
#include "asterisk/astobj2.h"
#include "asterisk/channel.h"
#include "asterisk/callerid.h"
#include <jansson.h>
#include <time.h>
Functions
int ast_json_array_append (struct ast_json *array, struct ast_json *value)
Append to an array.
int ast_json_array_clear (struct ast_json *array)
Remove all elements from an array.
struct ast_json * ast_json_array_create (void)
Create a empty JSON array.
int ast_json_array_extend (struct ast_json *array, struct ast_json *tail)
Append all elements from tail to array.
struct ast_json * ast_json_array_get (const struct ast_json *array, size_t index)
Get an element from an array.
int ast_json_array_insert (struct ast_json *array, size_t index, struct ast_json *value)
Insert into an array.
int ast_json_array_remove (struct ast_json *array, size_t index)
Remove an element from an array.
int ast_json_array_set (struct ast_json *array, size_t index, struct ast_json *value)
Change an element in an array.
size_t ast_json_array_size (const struct ast_json *array)
Get the size of a JSON array.
struct ast_json * ast_json_boolean (int value)
Get the JSON boolean corresponding to value.
struct ast_json * ast_json_channel_vars (struct varshead *channelvars)
Construct a JSON object from a ast_var_t list.
struct ast_json * ast_json_copy (const struct ast_json *value)
Copy a JSON value, but not its children.
struct ast_json * ast_json_deep_copy (const struct ast_json *value)
Copy a JSON value, and its children.
struct ast_json * ast_json_dialplan_cep (const char *context, const char *exten, int priority)
Construct a context/exten/priority as JSON.
struct ast_json * ast_json_dialplan_cep_app (const char *context, const char *exten, int priority, const char *app_name, const char *app_data)
Construct a context/exten/priority/application/application_data as JSON.
int ast_json_dump_file_format (struct ast_json *root, FILE *output, enum ast_json_encoding_format format)
Encode a JSON value to a FILE.
int ast_json_dump_new_file_format (struct ast_json *root, const char *path, enum ast_json_encoding_format format)
Encode a JSON value to a file at the given location.
int ast_json_dump_str_format (struct ast_json *root, struct ast_str **dst, enum ast_json_encoding_format format)
Encode a JSON value to an ast_str.
char * ast_json_dump_string_format (struct ast_json *root, enum ast_json_encoding_format format)
Encode a JSON value to a string.
int ast_json_equal (const struct ast_json *lhs, const struct ast_json *rhs)
Compare two JSON objects.
struct ast_json * ast_json_false (void)
Get the JSON false value.
void ast_json_free (void *p)
Asterisk's custom JSON allocator. Exposed for use by unit tests.
int ast_json_init (void)
Initialize the JSON library.
struct ast_json * ast_json_integer_create (intmax_t value)
Create a JSON integer.
intmax_t ast_json_integer_get (const struct ast_json *integer)
Get the value from a JSON integer.
int ast_json_integer_set (struct ast_json *integer, intmax_t value)
Set the value of a JSON integer.
struct ast_json * ast_json_ipaddr (const struct ast_sockaddr *addr, enum ast_transport transport_type)
Construct an IP address as JSON.
int ast_json_is_false (const struct ast_json *json)
Check if value is JSON false.
int ast_json_is_null (const struct ast_json *json)
Check if value is JSON null.
int ast_json_is_true (const struct ast_json *json)
Check if value is JSON true.
struct ast_json * ast_json_load_buf (const char *buffer, size_t buflen, struct ast_json_error *error)
Parse buffer with known length into a JSON object or array.
struct ast_json * ast_json_load_file (FILE *input, struct ast_json_error *error)
Parse a FILE into JSON object or array.
struct ast_json * ast_json_load_new_file (const char *path, struct ast_json_error *error)
Parse file at path into JSON object or array.
struct ast_json * ast_json_load_str (const struct ast_str *input, struct ast_json_error *error)
Parse ast_str into a JSON object or array.
struct ast_json * ast_json_load_string (const char *input, struct ast_json_error *error)
Parse null terminated string into a JSON object or array.
void * ast_json_malloc (size_t size)
Asterisk's custom JSON allocator. Exposed for use by unit tests.
struct ast_json * ast_json_name_number (const char *name, const char *number)
Common JSON rendering functions for common 'objects'.
struct ast_json * ast_json_null (void)
Get the JSON null value.
int ast_json_object_clear (struct ast_json *object)
Delete all elements from a JSON object.
struct ast_json * ast_json_object_create (void)
Create a new JSON object.
int ast_json_object_del (struct ast_json *object, const char *key)
Delete a field from a JSON object.
struct ast_json * ast_json_object_get (struct ast_json *object, const char *key)
Get a field from a JSON object.
struct ast_json_iter * ast_json_object_iter (struct ast_json *object)
Get an iterator pointing to the first field in a JSON object.
struct ast_json_iter * ast_json_object_iter_at (struct ast_json *object, const char *key)
Get an iterator pointing to a specified key in object.
const char * ast_json_object_iter_key (struct ast_json_iter *iter)
Get the key from an iterator.
struct ast_json_iter * ast_json_object_iter_next (struct ast_json *object, struct ast_json_iter *iter)
Get the next iterator.
int ast_json_object_iter_set (struct ast_json *object, struct ast_json_iter *iter, struct ast_json *value)
Set the value of the field pointed to by an iterator.
struct ast_json * ast_json_object_iter_value (struct ast_json_iter *iter)
Get the value from an iterator.
int ast_json_object_set (struct ast_json *object, const char *key, struct ast_json *value)
Set a field in a JSON object.
size_t ast_json_object_size (struct ast_json *object)
Get size of JSON object.
int ast_json_object_update (struct ast_json *object, struct ast_json *other)
Update object with all of the fields of other.
int ast_json_object_update_existing (struct ast_json *object, struct ast_json *other)
Update existing fields in object with the fields of other.
int ast_json_object_update_missing (struct ast_json *object, struct ast_json *other)
Add new fields to object with the fields of other.
struct ast_json * ast_json_pack (char const *format,...)
Helper for creating complex JSON values.
struct ast_json * ast_json_party_id (struct ast_party_id *party)
Construct an ast_party_id as JSON.
struct ast_json_payload * ast_json_payload_create (struct ast_json *json)
Create an ao2 object to pass json blobs as data payloads for stasis.
struct ast_json * ast_json_real_create (double value)
Create a JSON real number.
double ast_json_real_get (const struct ast_json *real)
Get the value from a JSON real number.
int ast_json_real_set (struct ast_json *real, double value)
Set the value of a JSON real number.
struct ast_json * ast_json_ref (struct ast_json *json)
Increase refcount on value.
void ast_json_reset_alloc_funcs (void)
Change alloc funcs back to the resource module defaults.
void ast_json_set_alloc_funcs (void *(*malloc_fn)(size_t), void(*free_fn)(void *))
Set custom allocators instead of the standard ast_malloc() and ast_free().
struct ast_json * ast_json_string_create (const char *value)
Construct a JSON string from value.
const char * ast_json_string_get (const struct ast_json *string)
Get the value of a JSON string.
int ast_json_string_set (struct ast_json *string, const char *value)
Change the value of a JSON string.
struct ast_json * ast_json_stringf (const char *format,...)
Create a JSON string, printf style.
struct ast_json * ast_json_timeval (const struct timeval tv, const char *zone)
Construct a timeval as JSON.
enum ast_json_to_ast_vars_code ast_json_to_ast_variables (struct ast_json *json_variables, struct ast_variable **variables)
Convert a ast_json list of key/value pair tuples into a ast_variable list.
struct ast_json * ast_json_true (void)
Get the JSON true value.
const char * ast_json_typename (enum ast_json_type type)
Get the string name for the given type.
enum ast_json_type ast_json_typeof (const struct ast_json *json)
Get the type of value.
void ast_json_unref (struct ast_json *json)
Decrease refcount on value. If refcount reaches zero, value is freed.
int ast_json_utf8_check (const char *str)
Check the nul terminated string for UTF-8 format.
int ast_json_utf8_check_len (const char *str, size_t len)
Check the string of the given length for UTF-8 format.
struct ast_json * ast_json_vpack (char const *format, va_list ap)
Helper for creating complex JSON values simply.
struct ast_json * ast_json_vstringf (const char *format, va_list args)
Create a JSON string, vprintf style.
static void copy_error (struct ast_json_error *error, const json_error_t *jansson_error)
Copy Jansson error struct to ours.
static size_t dump_flags (enum ast_json_encoding_format format)
Default flags for JSON encoding.
static struct ast_json * json_party_name (struct ast_party_name *name)
static struct ast_json * json_party_number (struct ast_party_number *number)
static struct ast_json * json_party_subaddress (struct ast_party_subaddress *subaddress)
static void json_payload_destructor (void *obj)
static size_t json_utf8_check_first (char byte)
static size_t json_utf8_check_full (const char *str, size_t len)
static void parse_error (struct ast_json_error *error, const char *text, const char *source)
static int write_to_ast_str (const char *buffer, size_t size, void *data)
Detailed Description
JSON abstraction layer.
This is a very thin wrapper around the Jansson API. For more details on it, see its docs at http://www.digip.org/jansson/doc/2.11/apiref.html.
Author
David M. Lee, II dlee@.nosp@m.digi.nosp@m.um.co.nosp@m.m
Definition in file json.c.
Function Documentation
ast_json_array_append()
int ast_json_array_append (struct ast_json * array, struct ast_json * value)
Append to an array.
Since
12.0.0
Note
The array steals the value reference even if it returns error; use ast_json_ref() to safely keep a pointer to it.
Parameters
array JSON array to modify.
value New JSON value to store at the end of array.
Returns
0 on success.
-1 on error.
Definition at line 368 of file json.c.
Referenced by add_format_information_cb(), app_to_json(), append_json(), append_sound_cb(), ast_ari_bridges_list(), ast_ari_channels_list(), ast_ari_endpoints_list(), ast_ari_endpoints_list_by_tech(), ast_ari_recordings_list_stored(), ast_bucket_json(), ast_endpoint_snapshot_to_json(), AST_TEST_DEFINE(), conf_send_event_to_participants(), container_to_json_array(), device_to_json_cb(), generate_filenames_json(), json_array_from_list(), process_log_list(), process_module_list(), report_receive_fax_status(), return_sorcery_object(), rtcp_report_to_json(), s_to_json(), send_start_msg_snapshots(), stasis_app_device_states_to_json(), stasis_app_exec(), stasis_app_mailboxes_to_json(), test_handler(), and units_to_json().
 {
    return json_array_append_new((json_t *)array, (json_t *)value);
 }
ast_json_array_clear()
int ast_json_array_clear (struct ast_json * array)
Remove all elements from an array.
Since
12.0.0
Parameters
array JSON array to clear.
Returns
0 on success.
-1 on error.
Definition at line 380 of file json.c.
Referenced by AST_TEST_DEFINE().
 {
    return json_array_clear((json_t *)array);
 }
ast_json_array_create()
struct ast_json* ast_json_array_create (void)
Create a empty JSON array.
Since
12.0.0
Returns
Newly allocated array.
NULL on error.
Definition at line 352 of file json.c.
Referenced by app_data_create(), ast_ari_applications_list(), ast_ari_asterisk_list_log_channels(), ast_ari_asterisk_list_modules(), ast_ari_bridges_list(), ast_ari_channels_list(), ast_ari_endpoints_list(), ast_ari_endpoints_list_by_tech(), ast_ari_recordings_list_stored(), ast_ari_sounds_list(), ast_bucket_json(), AST_TEST_DEFINE(), conf_send_event_to_participants(), container_to_json_array(), devices_to_json(), generate_filenames_json(), json_array_from_list(), report_receive_fax_status(), return_sorcery_object(), rtcp_report_to_json(), s_to_json(), stasis_app_device_states_to_json(), stasis_app_event_filter_to_json(), stasis_app_mailboxes_to_json(), and units_to_json().
 {
    return (struct ast_json *)json_array();
 }
ast_json_array_extend()
int ast_json_array_extend (struct ast_json * array, struct ast_json * tail)
Append all elements from tail to array.
Since
12.0.0
The tail argument is not changed, so ast_json_unref() it when you are done with it.
Parameters
array JSON array to modify.
tail JSON array with contents to append to array.
Returns
0 on success.
-1 on error.
Definition at line 384 of file json.c.
Referenced by AST_TEST_DEFINE().
 {
    return json_array_extend((json_t *)array, (json_t *)tail);
 }
ast_json_array_get()
struct ast_json* ast_json_array_get (const struct ast_json * array, size_t index)
Get an element from an array.
Since
12.0.0
The returned element is a borrowed reference; use ast_json_ref() to safely keep a pointer to it.
Parameters
array JSON array.
index Zero-based index into array.
Returns
The specified element.
NULL if array not an array.
NULL if index is out of bounds.
Definition at line 360 of file json.c.
Referenced by app_event_filter_matched(), app_event_filter_set(), ast_ari_applications_subscribe_parse_body(), ast_ari_applications_unsubscribe_parse_body(), ast_ari_asterisk_get_info_parse_body(), ast_ari_asterisk_update_object(), ast_ari_bridges_add_channel_parse_body(), ast_ari_bridges_play_parse_body(), ast_ari_bridges_play_with_id_parse_body(), ast_ari_bridges_remove_channel_parse_body(), ast_ari_channels_play_parse_body(), ast_ari_channels_play_with_id_parse_body(), ast_ari_events_user_event_parse_body(), ast_ari_validate_list(), AST_TEST_DEFINE(), channel_fax_cb(), and manager_json_to_ast_str().
 {
    return (struct ast_json *)json_array_get((json_t *)array, index);
 }
ast_json_array_insert()
int ast_json_array_insert (struct ast_json * array, size_t index, struct ast_json * value)
Insert into an array.
Since
12.0.0
Note
The array steals the value reference even if it returns error; use ast_json_ref() to safely keep a pointer to it.
Parameters
array JSON array to modify.
index Zero-based index into array.
value New JSON value to store in array at index.
Returns
0 on success.
-1 on error.
Definition at line 372 of file json.c.
Referenced by AST_TEST_DEFINE().
 {
    return json_array_insert_new((json_t *)array, index, (json_t *)value);
 }
ast_json_array_remove()
int ast_json_array_remove (struct ast_json * array, size_t index)
Remove an element from an array.
Since
12.0.0
Parameters
array JSON array to modify.
index Zero-based index into array.
Returns
0 on success.
-1 on error.
Definition at line 376 of file json.c.
Referenced by AST_TEST_DEFINE().
 {
    return json_array_remove((json_t *)array, index);
 }
ast_json_array_set()
int ast_json_array_set (struct ast_json * array, size_t index, struct ast_json * value)
Change an element in an array.
Since
12.0.0
Note
The array steals the value reference even if it returns error; use ast_json_ref() to safely keep a pointer to it.
Parameters
array JSON array to modify.
index Zero-based index into array.
value New JSON value to store in array at index.
Returns
0 on success.
-1 on error.
Definition at line 364 of file json.c.
Referenced by AST_TEST_DEFINE().
 {
    return json_array_set_new((json_t *)array, index, (json_t *)value);
 }
ast_json_array_size()
size_t ast_json_array_size (const struct ast_json * array)
Get the size of a JSON array.
Since
12.0.0
Parameters
array JSON array.
Returns
Size of array.
0 if array is not a JSON array.
Definition at line 356 of file json.c.
Referenced by app_event_filter_matched(), app_event_filter_set(), ast_ari_applications_list(), ast_ari_applications_subscribe_parse_body(), ast_ari_applications_unsubscribe_parse_body(), ast_ari_asterisk_get_info_parse_body(), ast_ari_asterisk_update_object(), ast_ari_bridges_add_channel_parse_body(), ast_ari_bridges_play_parse_body(), ast_ari_bridges_play_with_id_parse_body(), ast_ari_bridges_remove_channel_parse_body(), ast_ari_channels_play_parse_body(), ast_ari_channels_play_with_id_parse_body(), ast_ari_events_user_event_parse_body(), ast_ari_sounds_list(), ast_ari_validate_list(), AST_TEST_DEFINE(), channel_fax_cb(), create_sound_blob(), and manager_json_to_ast_str().
 {
    return json_array_size((json_t *)array);
 }
ast_json_boolean()
struct ast_json* ast_json_boolean (int value)
Get the JSON boolean corresponding to value.
Since
12.0.0
Returns
JSON true if value is true (non-zero).
JSON false if value is false (zero).
Definition at line 243 of file json.c.
Referenced by AST_TEST_DEFINE(), attended_transfer_to_json(), and blind_transfer_to_json().
 {
    return (struct ast_json *)json_boolean(value);
 }
ast_json_channel_vars()
struct ast_json* ast_json_channel_vars (struct varshead * channelvars)
Construct a JSON object from a ast_var_t list.
Since
14.2.0
Parameters
channelvars The list of ast_var_t to represent as JSON
Returns
JSON object with variable names as keys and variable values as values
Definition at line 843 of file json.c.
References ast_json_object_create(), ast_json_object_set(), ast_json_string_create(), AST_LIST_TRAVERSE, ast_var_t::entries, ast_var_t::name, ast_var_t::value, and var.
Referenced by ast_channel_snapshot_to_json(), external_media_audiosocket_tcp(), and external_media_rtp_udp().
 {
    struct ast_json *ret;
    struct ast_var_t *var;
    ret = ast_json_object_create();
    AST_LIST_TRAVERSE(channelvars, var, entries) {
       ast_json_object_set(ret, var->name, ast_json_string_create(var->value));
    }
    return ret;
 }
ast_json_copy()
struct ast_json* ast_json_copy (const struct ast_json * value)
Copy a JSON value, but not its children.
Since
12.0.0
If value is a JSON object or array, its children are shared with the returned copy.
Parameters
value JSON value to copy.
Returns
Shallow copy of value.
NULL on error.
Definition at line 616 of file json.c.
Referenced by AST_TEST_DEFINE(), channel_blob_to_json(), channel_to_json(), and test_handler().
 {
    return (struct ast_json *)json_copy((json_t *)value);
 }
ast_json_deep_copy()
struct ast_json* ast_json_deep_copy (const struct ast_json * value)
Copy a JSON value, and its children.
Since
12.0.0
If value is a JSON object or array, they are also copied.
Parameters
value JSON value to copy.
Returns
Deep copy of value.
NULL on error.
Definition at line 620 of file json.c.
Referenced by AST_TEST_DEFINE(), and stir_shaken_verify_json().
 {
    return (struct ast_json *)json_deep_copy((json_t *)value);
 }
ast_json_dialplan_cep()
struct ast_json* ast_json_dialplan_cep (const char * context, const char * exten, int priority)
Construct a context/exten/priority as JSON.
If a NULL is passed for context or exten, or -1 for priority, the fields is set to ast_json_null().
Parameters
context Context name.
exten Extension.
priority Dialplan priority.
Returns
JSON object with context, exten and priority fields
Definition at line 644 of file json.c.
References ast_json_dialplan_cep_app().
 {
    return ast_json_dialplan_cep_app(context, exten, priority, "", "");
 }
ast_json_dialplan_cep_app()
struct ast_json* ast_json_dialplan_cep_app (const char * context, const char * exten, int priority, const char * app_name, const char * app_data)
Construct a context/exten/priority/application/application_data as JSON.
If a NULL is passed for context or exten or app_name or app_data, or -1 for priority, the fields is set to ast_json_null().
Parameters
context Context name.
exten Extension.
priority Dialplan priority.
app_name Application name.
app_data Application argument.
Returns
JSON object with context, exten and priority app_name app_data fields
Definition at line 632 of file json.c.
References ast_json_integer_create(), ast_json_null(), and ast_json_pack().
Referenced by ast_channel_snapshot_to_json(), ast_json_dialplan_cep(), and AST_TEST_DEFINE().
 {
    return ast_json_pack("{s: s?, s: s?, s: o, s: s?, s: s?}",
       "context", context,
       "exten", exten,
       "priority", priority != -1 ? ast_json_integer_create(priority) : ast_json_null(),
       "app_name", app_name,
       "app_data", app_data
       );
 }
ast_json_dump_file_format()
int ast_json_dump_file_format (struct ast_json * root, FILE * output, enum ast_json_encoding_format format)
Encode a JSON value to a FILE.
Since
12.0.0
Parameters
root JSON value.
output File to write JSON encoding to.
format encoding format type.
Returns
0 on success.
-1 on error. The contents of output are undefined.
Definition at line 505 of file json.c.
References dump_flags().
 {
    if (!root || !output) {
       return -1;
    }
    return json_dumpf((json_t *)root, output, dump_flags(format));
 }
ast_json_dump_new_file_format()
int ast_json_dump_new_file_format (struct ast_json * root, const char * path, enum ast_json_encoding_format format)
Encode a JSON value to a file at the given location.
Since
12.0.0
Parameters
root JSON value.
path Path to file to write JSON encoding to.
format encoding format type.
Returns
0 on success.
-1 on error. The contents of output are undefined.
Definition at line 512 of file json.c.
References dump_flags().
 {
    if (!root || !path) {
       return -1;
    }
    return json_dump_file((json_t *)root, path, dump_flags(format));
 }
ast_json_dump_str_format()
int ast_json_dump_str_format (struct ast_json * root, struct ast_str ** dst, enum ast_json_encoding_format format)
Encode a JSON value to an ast_str.
Since
12.0.0
If dst is too small, it will be grown as needed.
Parameters
root JSON value.
dst ast_str to store JSON encoding.
format encoding format type.
Returns
0 on success.
-1 on error. The contents of dst are undefined.
Definition at line 499 of file json.c.
References dump_flags(), and write_to_ast_str().
Referenced by ast_ari_callback().
 {
    return json_dump_callback((json_t *)root, write_to_ast_str, dst, dump_flags(format));
 }
ast_json_dump_string_format()
char* ast_json_dump_string_format (struct ast_json * root, enum ast_json_encoding_format format)
Encode a JSON value to a string.
Since
12.0.0
Returned string must be freed by calling ast_json_free().
Parameters
root JSON value.
format encoding format type.
Returns
String encoding of root.
NULL on error.
Definition at line 463 of file json.c.
References dump_flags().
Referenced by ast_ari_callback(), ast_ari_websocket_session_write(), send_message(), and stasis_app_message_handler().
 {
    return json_dumps((json_t *)root, dump_flags(format));
 }
ast_json_equal()
int ast_json_equal (const struct ast_json * lhs, const struct ast_json * rhs)
Compare two JSON objects.
Since
12.0.0
Two JSON objects are equal if they are of the same type, and their contents are equal.
Parameters
lhs Value to compare.
rhs Other value to compare.
Returns
True (non-zero) if lhs and rhs are equal.
False (zero) if they are not.
Definition at line 347 of file json.c.
Referenced by AST_TEST_DEFINE(), and test_name_number().
 {
    return json_equal((json_t *)lhs, (json_t *)rhs);
 }
ast_json_false()
struct ast_json* ast_json_false (void)
Get the JSON false value.
Since
12.0.0
The returned value is a singleton, and does not need to be ast_json_unref()'ed.
Returns
JSON false.
Definition at line 238 of file json.c.
Referenced by AST_TEST_DEFINE().
 {
    return (struct ast_json *)json_false();
 }
ast_json_free()
void ast_json_free (void * p)
Asterisk's custom JSON allocator. Exposed for use by unit tests.
Since
12.0.0
Definition at line 52 of file json.c.
References ast_free.
Referenced by add_identity_header(), ast_ari_callback(), ast_ari_events_event_websocket_ws_attempted_cb(), ast_ari_events_event_websocket_ws_established_cb(), ast_ari_websocket_session_write(), ast_cel_create_event_with_time(), ast_json_reset_alloc_funcs(), AST_TEST_DEFINE(), asterisk_publication_send_refresh(), asterisk_publisher_devstate_cb(), asterisk_publisher_mwistate_cb(), beanstalk_put(), cel_bs_put(), compare_caller_id(), compare_timestamp(), format_log_json(), get_attestation_from_payload(), json_debug_free(), persistence_generator_data_struct2str(), rtcp_message_handler(), send_message(), sorcery_astdb_create(), and stasis_app_message_handler().
 {
    ast_free(p);
 }
ast_json_init()
int ast_json_init (void)
Initialize the JSON library.
Definition at line 705 of file json.c.
References ast_json_reset_alloc_funcs(), ast_log, LOG_ERROR, and NULL.
Referenced by asterisk_daemon().
 {
    json_t *version_check;
    /* Setup to use Asterisk custom allocators */
    ast_json_reset_alloc_funcs();
    /* We depend on functionality of jansson-2.11 but don't actually use
     * any symbols.  If we link at runtime to less than 2.11 this json_pack
     * will return NULL. */
    version_check = json_pack("{s: o?, s: o*}",
       "JSON", NULL,
       "Bourne", NULL);
    if (!version_check) {
       ast_log(LOG_ERROR, "There was a problem finding jansson 2.11 runtime libraries.\n"
          "Please rebuild Asterisk using ./configure --with-jansson-bundled.\n");
       return -1;
    }
    json_decref(version_check);
    return 0;
 }
ast_json_integer_create()
struct ast_json* ast_json_integer_create (intmax_t value)
Create a JSON integer.
Since
12.0.0
Parameters
value Value of the new JSON integer.
Returns
Newly allocated integer.
NULL on error.
Definition at line 317 of file json.c.
Referenced by alloc_security_event_json_object(), ast_ari_asterisk_get_info(), ast_endpoint_snapshot_to_json(), ast_json_dialplan_cep_app(), ast_rtp_convert_stats_json(), AST_TEST_DEFINE(), dialog_info_generate_body_content(), identify_module(), meetme_stasis_generate_msg(), stasis_app_recording_to_json(), and stir_shaken_add_iat().
 {
    return (struct ast_json *)json_integer(value);
 }
ast_json_integer_get()
intmax_t ast_json_integer_get (const struct ast_json * integer)
Get the value from a JSON integer.
Since
12.0.0
Parameters
integer JSON integer.
Returns
Value of a JSON integer.
0 if integer is not a JSON integer.
Definition at line 322 of file json.c.
Referenced by agent_logoff_to_ami(), ast_ari_bridges_play_parse_body(), ast_ari_bridges_play_with_id_parse_body(), ast_ari_bridges_record_parse_body(), ast_ari_channels_continue_in_dialplan_parse_body(), ast_ari_channels_dial_parse_body(), ast_ari_channels_originate_parse_body(), ast_ari_channels_originate_with_id_parse_body(), ast_ari_channels_play_parse_body(), ast_ari_channels_play_with_id_parse_body(), ast_ari_channels_record_parse_body(), ast_ari_channels_send_dtmf_parse_body(), ast_ari_mailboxes_update_parse_body(), AST_TEST_DEFINE(), asterisk_publication_devicestate(), asterisk_publication_mailboxstate(), cc_available_to_ami(), cc_callerrecalling_to_ami(), cc_callerstartmonitoring_to_ami(), cc_callerstopmonitoring_to_ami(), cc_failure_to_ami(), cc_monitorfailed_to_ami(), cc_offertimerstart_to_ami(), cc_recallcomplete_to_ami(), cc_requestacknowledged_to_ami(), cc_requested_to_ami(), cel_generic_cb(), channel_dtmf_end_cb(), channel_hangup_request_cb(), check_range(), compare_timestamp(), dahdichannel_to_ami(), dialog_info_generate_body_content(), dtmf_end_to_json(), handle_local_optimization_begin(), handle_local_optimization_end(), local_message_to_ami(), manager_generic_msg_cb(), manager_json_value_str_append(), meetme_stasis_cb(), queue_agent_cb(), security_event_stasis_cb(), security_event_to_ami_blob(), talking_stop_to_ami(), and test_suite_event_to_ami().
 {
    return json_integer_value((json_t *)integer);
 }
ast_json_integer_set()
int ast_json_integer_set (struct ast_json * integer, intmax_t value)
Set the value of a JSON integer.
Since
12.0.0
Parameters
integer JSON integer to modify.
value New value for integer.
Returns
0 on success.
-1 on error.
Definition at line 327 of file json.c.
Referenced by AST_TEST_DEFINE().
 {
    return json_integer_set((json_t *)integer, value);
 }
ast_json_ipaddr()
struct ast_json* ast_json_ipaddr (const struct ast_sockaddr * addr, enum ast_transport transport_type)
Construct an IP address as JSON.
XXX some comments describing the need for this here
Parameters
addr ast_sockaddr to encode
transport_type ast_transport to include in the address string if any. Should just be one.
Returns
JSON string containing the IP address with optional transport information
NULL on error.
Definition at line 661 of file json.c.
References ast_json_string_create(), ast_sockaddr_is_ipv4(), ast_sockaddr_is_ipv4_mapped(), ast_sockaddr_stringify_addr(), ast_sockaddr_stringify_port(), ast_str_alloca, ast_str_append(), ast_str_buffer(), ast_str_set(), AST_TRANSPORT_TCP, AST_TRANSPORT_TLS, AST_TRANSPORT_UDP, AST_TRANSPORT_WS, AST_TRANSPORT_WSS, and NULL.
Referenced by add_ip_json_object().
 {
    struct ast_str *string = ast_str_alloca(64);
    if (!string) {
       return NULL;
    }
    ast_str_set(&string, 0, (ast_sockaddr_is_ipv4(addr) ||
       ast_sockaddr_is_ipv4_mapped(addr)) ? "IPV4/" : "IPV6/");
    if (transport_type) {
       char *transport_string = NULL;
       /* NOTE: None will be applied if multiple transport types are specified in transport_type */
       switch(transport_type) {
       case AST_TRANSPORT_UDP:
          transport_string = "UDP";
          break;
       case AST_TRANSPORT_TCP:
          transport_string = "TCP";
          break;
       case AST_TRANSPORT_TLS:
          transport_string = "TLS";
          break;
       case AST_TRANSPORT_WS:
          transport_string = "WS";
          break;
       case AST_TRANSPORT_WSS:
          transport_string = "WSS";
          break;
       }
       if (transport_string) {
          ast_str_append(&string, 0, "%s/", transport_string);
       }
    }
    ast_str_append(&string, 0, "%s", ast_sockaddr_stringify_addr(addr));
    ast_str_append(&string, 0, "/%s", ast_sockaddr_stringify_port(addr));
    return ast_json_string_create(ast_str_buffer(string));
 }
ast_json_is_false()
int ast_json_is_false (const struct ast_json * value)
Check if value is JSON false.
Since
12.0.0
Returns
True (non-zero) if value == ast_json_false().
False (zero) otherwise.
Definition at line 258 of file json.c.
Referenced by AST_TEST_DEFINE().
 {
    return json_is_false((const json_t *)json);
 }
ast_json_is_null()
int ast_json_is_null (const struct ast_json * value)
Check if value is JSON null.
Since
12.0.0
Returns
True (non-zero) if value == ast_json_false().
False (zero) otherwise.
Definition at line 263 of file json.c.
Referenced by aoc_publish_blob(), ast_ari_callback(), ast_manager_str_from_json_object(), AST_TEST_DEFINE(), and channel_blob_to_json().
 {
    return json_is_null((const json_t *)json);
 }
ast_json_is_true()
int ast_json_is_true (const struct ast_json * value)
Check if value is JSON true.
Since
12.0.0
Returns
True (non-zero) if value == ast_json_true().
False (zero) otherwise..
Definition at line 253 of file json.c.
Referenced by ast_ari_bridges_add_channel_parse_body(), ast_ari_bridges_record_parse_body(), ast_ari_channels_record_parse_body(), AST_TEST_DEFINE(), channel_hangup_request_cb(), channel_mixmonitor_mute_cb(), get_bool_header(), and local_message_to_ami().
 {
    return json_is_true((const json_t *)json);
 }
ast_json_load_buf()
struct ast_json* ast_json_load_buf (const char * buffer, size_t buflen, struct ast_json_error * error)
Parse buffer with known length into a JSON object or array.
Since
12.0.0
Parameters
buffer Buffer to parse.
buflen Length of buffer.
[out] error Filled with information on error.
Returns
Parsed JSON element.
NULL on error.
Definition at line 564 of file json.c.
References copy_error().
Referenced by ast_ari_websocket_session_read(), ast_http_get_json(), AST_TEST_DEFINE(), asterisk_publication_devicestate_state_change(), and asterisk_publication_mwi_state_change().
 {
    json_error_t jansson_error = {};
    struct ast_json *r = (struct ast_json *)json_loadb(buffer, buflen, 0, &jansson_error);
    copy_error(error, &jansson_error);
    return r;
 }
ast_json_load_file()
struct ast_json* ast_json_load_file (FILE * input, struct ast_json_error * error)
Parse a FILE into JSON object or array.
Since
12.0.0
Parameters
input FILE to parse.
[out] error Filled with information on error.
Returns
Parsed JSON element.
NULL on error.
Definition at line 571 of file json.c.
References copy_error(), NULL, and parse_error().
Referenced by AST_TEST_DEFINE().
 {
    json_error_t jansson_error = {};
    struct ast_json *r = NULL;
    if (input != NULL) {
       r = (struct ast_json *)json_loadf(input, 0, &jansson_error);
       copy_error(error, &jansson_error);
    } else {
       parse_error(error, "NULL input file", "<null>");
    }
    return r;
 }
ast_json_load_new_file()
struct ast_json* ast_json_load_new_file (const char * path, struct ast_json_error * error)
Parse file at path into JSON object or array.
Since
12.0.0
Parameters
path Path of file to parse.
[out] error Filled with information on error.
Returns
Parsed JSON element.
NULL on error.
Definition at line 583 of file json.c.
References copy_error().
Referenced by ast_ari_get_docs(), and AST_TEST_DEFINE().
 {
    json_error_t jansson_error = {};
    struct ast_json *r = (struct ast_json *)json_load_file(path, 0, &jansson_error);
    copy_error(error, &jansson_error);
    return r;
 }
ast_json_load_str()
struct ast_json* ast_json_load_str (const struct ast_str * input, struct ast_json_error * error)
Parse ast_str into a JSON object or array.
Since
12.0.0
Parameters
input ast_str to parse.
[out] error Filled with information on error.
Returns
Parsed JSON element.
NULL on error.
Definition at line 559 of file json.c.
References ast_json_load_string(), and ast_str_buffer().
Referenced by AST_TEST_DEFINE().
 {
    return ast_json_load_string(ast_str_buffer(input), error);
 }
ast_json_load_string()
struct ast_json* ast_json_load_string (const char * input, struct ast_json_error * error)
Parse null terminated string into a JSON object or array.
Since
12.0.0
Parameters
input String to parse.
[out] error Filled with information on error.
Returns
Parsed JSON element.
NULL on error.
Definition at line 546 of file json.c.
References copy_error(), NULL, and parse_error().
Referenced by ast_json_load_str(), ast_stir_shaken_verify(), AST_TEST_DEFINE(), compare_caller_id(), compare_timestamp(), fetch_access_token(), fetch_google_access_token(), get_attestation_from_payload(), persistence_generator_data_str2struct(), sorcery_astdb_retrieve_fields_common(), sorcery_astdb_retrieve_id(), sorcery_astdb_retrieve_prefix(), and sorcery_astdb_retrieve_regex().
 {
    json_error_t jansson_error = {};
    struct ast_json *r = NULL;
    if (input != NULL) {
       r = (struct ast_json *)json_loads(input, 0, &jansson_error);
       copy_error(error, &jansson_error);
    } else {
       parse_error(error, "NULL input string", "<null>");
    }
    return r;
 }
ast_json_malloc()
void* ast_json_malloc (size_t size)
Asterisk's custom JSON allocator. Exposed for use by unit tests.
Since
12.0.0
Definition at line 47 of file json.c.
References ast_malloc.
Referenced by ast_json_reset_alloc_funcs(), and json_debug_malloc().
 {
    return ast_malloc(size);
 }
ast_json_name_number()
struct ast_json* ast_json_name_number (const char * name, const char * number)
Common JSON rendering functions for common 'objects'.
Simple name/number pair.
Parameters
name Name
number Number
Returns
NULL if error (non-UTF8 characters, NULL inputs, etc.)
JSON object with name and number fields
Definition at line 625 of file json.c.
References ast_json_pack(), and AST_JSON_UTF8_VALIDATE.
Referenced by ast_channel_snapshot_to_json(), and test_name_number().
 {
    return ast_json_pack("{s: s, s: s}",
       "name", AST_JSON_UTF8_VALIDATE(name),
       "number", AST_JSON_UTF8_VALIDATE(number));
 }
ast_json_null()
struct ast_json* ast_json_null (void)
Get the JSON null value.
Since
12.0.0
The returned value is a singleton, and does not need to be ast_json_unref()'ed.
Returns
JSON null.
Definition at line 248 of file json.c.
Referenced by association_to_json(), ast_ari_callback(), ast_ari_recordings_get_stored_file(), ast_ari_response_accepted(), ast_ari_response_no_content(), ast_channel_publish_blob(), ast_channel_publish_cached_blob(), ast_endpoint_blob_create(), ast_json_dialplan_cep_app(), AST_TEST_DEFINE(), create_channel_blob_message(), local_optimization_finished_cb(), local_optimization_started_cb(), publish_chanspy_message(), rtcp_report_to_json(), s_to_json(), send_call_pickup_stasis_message(), send_message(), and units_to_json().
 {
    return (struct ast_json *)json_null();
 }
ast_json_object_clear()
int ast_json_object_clear (struct ast_json * object)
Delete all elements from a JSON object.
Since
12.0.0
Parameters
object JSON object to clear.
Returns
0 on success.
-1 on error.
Definition at line 412 of file json.c.
Referenced by AST_TEST_DEFINE().
 {
    return json_object_clear((json_t *)object);
 }
ast_json_object_create()
struct ast_json* ast_json_object_create (void)
Create a new JSON object.
Since
12.0.0
Returns
Newly allocated object.
NULL on error.
Definition at line 389 of file json.c.
Referenced by alloc_security_event_json_object(), ast_ari_asterisk_get_info(), ast_ari_asterisk_get_module(), ast_bucket_file_json(), ast_json_channel_vars(), ast_rtp_convert_stats_json(), ast_sip_subscription_set_persistence_data(), ast_sorcery_objectset_json_create(), AST_TEST_DEFINE(), channel_blob_to_json(), msg_to_json(), multi_user_event_to_json(), peerstatus_to_json(), publish_acl_change(), stun_monitor_request(), and units_to_json().
 {
    return (struct ast_json *)json_object();
 }
ast_json_object_del()
int ast_json_object_del (struct ast_json * object, const char * key)
Delete a field from a JSON object.
Since
12.0.0
Parameters
object JSON object to modify.
key Key of field to delete.
Returns
0 on success, or -1 if key does not exist.
Definition at line 408 of file json.c.
Referenced by ast_ari_get_docs(), AST_TEST_DEFINE(), bridge_to_json(), and channel_to_json().
 {
    return json_object_del((json_t *)object, key);
 }
ast_json_object_get()
struct ast_json* ast_json_object_get (struct ast_json * object, const char * key)
Get a field from a JSON object.
Since
12.0.0
The returned element is a borrowed reference; use ast_json_ref() to safely keep a pointer to it.
Parameters
object JSON object.
key Key of field to look up.
Returns
Value with given key.
NULL on error.
Definition at line 397 of file json.c.
References NULL.
Referenced by add_identity_header(), agent_login_to_ami(), agent_logoff_to_ami(), allocate_subscription(), app_event_filter_set(), app_send(), app_to_json(), append_event_str_single(), append_json_single(), assign_uuid(), ast_ari_applications_subscribe_parse_body(), ast_ari_applications_unsubscribe_parse_body(), ast_ari_asterisk_add_log_parse_body(), ast_ari_asterisk_get_global_var_parse_body(), ast_ari_asterisk_get_info_parse_body(), ast_ari_asterisk_set_global_var_parse_body(), ast_ari_asterisk_update_object(), ast_ari_bridges_add_channel_parse_body(), ast_ari_bridges_create_parse_body(), ast_ari_bridges_create_with_id_parse_body(), ast_ari_bridges_play_parse_body(), ast_ari_bridges_play_with_id_parse_body(), ast_ari_bridges_record_parse_body(), ast_ari_bridges_remove_channel_parse_body(), ast_ari_bridges_start_moh_parse_body(), ast_ari_callback(), ast_ari_channels_continue_in_dialplan_parse_body(), ast_ari_channels_create(), ast_ari_channels_create_parse_body(), ast_ari_channels_dial_parse_body(), ast_ari_channels_external_media(), ast_ari_channels_external_media_parse_body(), ast_ari_channels_get_channel_var_parse_body(), ast_ari_channels_hangup_parse_body(), ast_ari_channels_move_parse_body(), ast_ari_channels_mute_parse_body(), ast_ari_channels_originate(), ast_ari_channels_originate_parse_body(), ast_ari_channels_originate_with_id(), ast_ari_channels_originate_with_id_parse_body(), ast_ari_channels_play_parse_body(), ast_ari_channels_play_with_id_parse_body(), ast_ari_channels_record_parse_body(), ast_ari_channels_redirect_parse_body(), ast_ari_channels_send_dtmf_parse_body(), ast_ari_channels_set_channel_var_parse_body(), ast_ari_channels_snoop_channel_parse_body(), ast_ari_channels_snoop_channel_with_id_parse_body(), ast_ari_channels_start_moh_parse_body(), ast_ari_channels_unmute_parse_body(), ast_ari_device_states_update_parse_body(), ast_ari_endpoints_send_message(), ast_ari_endpoints_send_message_parse_body(), ast_ari_endpoints_send_message_to_endpoint(), ast_ari_endpoints_send_message_to_endpoint_parse_body(), ast_ari_events_user_event(), ast_ari_events_user_event_parse_body(), ast_ari_get_docs(), ast_ari_mailboxes_update_parse_body(), ast_ari_playbacks_control_parse_body(), ast_ari_recordings_copy_stored_parse_body(), ast_ari_sounds_list_parse_body(), ast_ari_validate_event(), ast_ari_validate_message(), ast_endpoint_snapshot_to_json(), ast_stir_shaken_sign(), AST_TEST_DEFINE(), asterisk_publication_devicestate(), asterisk_publication_devicestate_state_change(), asterisk_publication_mailboxstate(), asterisk_publication_mwi_state_change(), cc_available_to_ami(), cc_callerrecalling_to_ami(), cc_callerstartmonitoring_to_ami(), cc_callerstopmonitoring_to_ami(), cc_failure_to_ami(), cc_monitorfailed_to_ami(), cc_offertimerstart_to_ami(), cc_recallcomplete_to_ami(), cc_requestacknowledged_to_ami(), cc_requested_to_ami(), cel_generic_cb(), channel_dial_cb(), channel_dtmf_begin_cb(), channel_dtmf_end_cb(), channel_enter_cb(), channel_fax_cb(), channel_hangup_handler_cb(), channel_hangup_request_cb(), channel_hold_cb(), channel_mixmonitor_mute_cb(), channel_moh_start_cb(), compare_caller_id(), compare_timestamp(), conf_send_event_to_participants(), confbridge_publish_manager_event(), confbridge_talking_cb(), contactstatus_to_ami(), contactstatus_to_json(), create_sound_blob(), dahdichannel_to_ami(), dial_to_json(), dtmf_end_to_json(), fetch_access_token(), fetch_google_access_token(), get_attestation_from_payload(), get_blob_variable(), get_bool_header(), handle_dial_message(), handle_local_optimization_begin(), handle_local_optimization_end(), handle_masquerade(), handler(), hold_to_json(), local_message_to_ami(), manager_generic_msg_cb(), meetme_stasis_cb(), multi_user_event_to_ami(), multi_user_event_to_json(), mwi_app_event_cb(), mwi_startup_event_cb(), peerstatus_to_ami(), playback_to_json(), queue_agent_cb(), recording_to_json(), registry_message_cb(), rtcp_message_handler(), rtcp_report_to_ami(), security_event_stasis_cb(), security_event_to_ami_blob(), send_start_msg_snapshots(), session_timeout_to_ami(), startup_event_cb(), stasis_app_exec(), stasis_app_message_handler(), stasis_end_to_json(), stasis_start_to_json(), stir_shaken_add_attest(), stir_shaken_add_iat(), stir_shaken_add_origid(), stir_shaken_add_x5u(), stir_shaken_verify_json(), subscription_persistence_event_cb(), system_registry_to_ami(), talking_stop_to_ami(), test_suite_event_to_ami(), and varset_to_ami().
 {
    if (!key) {
       return NULL;
    }
    return (struct ast_json *)json_object_get((json_t *)object, key);
 }
ast_json_object_iter()
struct ast_json_iter* ast_json_object_iter (struct ast_json * object)
Get an iterator pointing to the first field in a JSON object.
Since
12.0.0
The order of the fields in an object are not specified. However, iterating forward from this iterator will cover all fields in object. Adding or removing fields from object may invalidate its iterators.
Parameters
object JSON object.
Returns
Iterator to the first field in object.
NULL object is empty.
NULL on error.
Definition at line 429 of file json.c.
Referenced by ast_ari_validate_application(), ast_ari_validate_application_move_failed(), ast_ari_validate_application_replaced(), ast_ari_validate_asterisk_info(), ast_ari_validate_asterisk_ping(), ast_ari_validate_bridge(), ast_ari_validate_bridge_attended_transfer(), ast_ari_validate_bridge_blind_transfer(), ast_ari_validate_bridge_created(), ast_ari_validate_bridge_destroyed(), ast_ari_validate_bridge_merged(), ast_ari_validate_bridge_video_source_changed(), ast_ari_validate_build_info(), ast_ari_validate_caller_id(), ast_ari_validate_channel(), ast_ari_validate_channel_caller_id(), ast_ari_validate_channel_connected_line(), ast_ari_validate_channel_created(), ast_ari_validate_channel_destroyed(), ast_ari_validate_channel_dialplan(), ast_ari_validate_channel_dtmf_received(), ast_ari_validate_channel_entered_bridge(), ast_ari_validate_channel_hangup_request(), ast_ari_validate_channel_hold(), ast_ari_validate_channel_left_bridge(), ast_ari_validate_channel_state_change(), ast_ari_validate_channel_talking_finished(), ast_ari_validate_channel_talking_started(), ast_ari_validate_channel_unhold(), ast_ari_validate_channel_userevent(), ast_ari_validate_channel_varset(), ast_ari_validate_config_info(), ast_ari_validate_config_tuple(), ast_ari_validate_contact_info(), ast_ari_validate_contact_status_change(), ast_ari_validate_device_state(), ast_ari_validate_device_state_changed(), ast_ari_validate_dial(), ast_ari_validate_dialed(), ast_ari_validate_dialplan_cep(), ast_ari_validate_endpoint(), ast_ari_validate_endpoint_state_change(), ast_ari_validate_event(), ast_ari_validate_format_lang_pair(), ast_ari_validate_live_recording(), ast_ari_validate_log_channel(), ast_ari_validate_mailbox(), ast_ari_validate_message(), ast_ari_validate_missing_params(), ast_ari_validate_module(), ast_ari_validate_peer(), ast_ari_validate_peer_status_change(), ast_ari_validate_playback(), ast_ari_validate_playback_continuing(), ast_ari_validate_playback_finished(), ast_ari_validate_playback_started(), ast_ari_validate_recording_failed(), ast_ari_validate_recording_finished(), ast_ari_validate_recording_started(), ast_ari_validate_rtpstat(), ast_ari_validate_set_id(), ast_ari_validate_sound(), ast_ari_validate_stasis_end(), ast_ari_validate_stasis_start(), ast_ari_validate_status_info(), ast_ari_validate_stored_recording(), ast_ari_validate_system_info(), ast_ari_validate_text_message(), ast_ari_validate_text_message_received(), ast_ari_validate_variable(), ast_json_to_ast_variables(), AST_TEST_DEFINE(), and manager_json_to_ast_str().
 {
    return json_object_iter((json_t *)object);
 }
ast_json_object_iter_at()
struct ast_json_iter* ast_json_object_iter_at (struct ast_json * object, const char * key)
Get an iterator pointing to a specified key in object.
Since
12.0.0
Iterating forward from this iterator may not to cover all elements in object.
Parameters
object JSON object to iterate.
key Key of field to lookup.
Returns
Iterator pointing to the field with the given key.
NULL if key does not exist.
NULL on error.
Definition at line 433 of file json.c.
Referenced by AST_TEST_DEFINE().
 {
    return json_object_iter_at((json_t *)object, key);
 }
ast_json_object_iter_key()
const char* ast_json_object_iter_key (struct ast_json_iter * iter)
Get the key from an iterator.
Since
12.0.0
Parameters
iter JSON object iterator.
Returns
Key of the field iter points to.
Definition at line 441 of file json.c.
Referenced by ast_ari_validate_application(), ast_ari_validate_application_move_failed(), ast_ari_validate_application_replaced(), ast_ari_validate_asterisk_info(), ast_ari_validate_asterisk_ping(), ast_ari_validate_bridge(), ast_ari_validate_bridge_attended_transfer(), ast_ari_validate_bridge_blind_transfer(), ast_ari_validate_bridge_created(), ast_ari_validate_bridge_destroyed(), ast_ari_validate_bridge_merged(), ast_ari_validate_bridge_video_source_changed(), ast_ari_validate_build_info(), ast_ari_validate_caller_id(), ast_ari_validate_channel(), ast_ari_validate_channel_caller_id(), ast_ari_validate_channel_connected_line(), ast_ari_validate_channel_created(), ast_ari_validate_channel_destroyed(), ast_ari_validate_channel_dialplan(), ast_ari_validate_channel_dtmf_received(), ast_ari_validate_channel_entered_bridge(), ast_ari_validate_channel_hangup_request(), ast_ari_validate_channel_hold(), ast_ari_validate_channel_left_bridge(), ast_ari_validate_channel_state_change(), ast_ari_validate_channel_talking_finished(), ast_ari_validate_channel_talking_started(), ast_ari_validate_channel_unhold(), ast_ari_validate_channel_userevent(), ast_ari_validate_channel_varset(), ast_ari_validate_config_info(), ast_ari_validate_config_tuple(), ast_ari_validate_contact_info(), ast_ari_validate_contact_status_change(), ast_ari_validate_device_state(), ast_ari_validate_device_state_changed(), ast_ari_validate_dial(), ast_ari_validate_dialed(), ast_ari_validate_dialplan_cep(), ast_ari_validate_endpoint(), ast_ari_validate_endpoint_state_change(), ast_ari_validate_event(), ast_ari_validate_format_lang_pair(), ast_ari_validate_live_recording(), ast_ari_validate_log_channel(), ast_ari_validate_mailbox(), ast_ari_validate_message(), ast_ari_validate_missing_params(), ast_ari_validate_module(), ast_ari_validate_peer(), ast_ari_validate_peer_status_change(), ast_ari_validate_playback(), ast_ari_validate_playback_continuing(), ast_ari_validate_playback_finished(), ast_ari_validate_playback_started(), ast_ari_validate_recording_failed(), ast_ari_validate_recording_finished(), ast_ari_validate_recording_started(), ast_ari_validate_rtpstat(), ast_ari_validate_set_id(), ast_ari_validate_sound(), ast_ari_validate_stasis_end(), ast_ari_validate_stasis_start(), ast_ari_validate_status_info(), ast_ari_validate_stored_recording(), ast_ari_validate_system_info(), ast_ari_validate_text_message(), ast_ari_validate_text_message_received(), ast_ari_validate_variable(), ast_json_to_ast_variables(), AST_TEST_DEFINE(), and manager_json_to_ast_str().
 {
    return json_object_iter_key(iter);
 }
ast_json_object_iter_next()
struct ast_json_iter* ast_json_object_iter_next (struct ast_json * object, struct ast_json_iter * iter)
Get the next iterator.
Since
12.0.0
Parameters
object JSON object iter was obtained from.
iter JSON object iterator.
Returns
Iterator to next field in object.
NULL if iter was the last field.
Definition at line 437 of file json.c.
Referenced by ast_ari_validate_application(), ast_ari_validate_application_move_failed(), ast_ari_validate_application_replaced(), ast_ari_validate_asterisk_info(), ast_ari_validate_asterisk_ping(), ast_ari_validate_bridge(), ast_ari_validate_bridge_attended_transfer(), ast_ari_validate_bridge_blind_transfer(), ast_ari_validate_bridge_created(), ast_ari_validate_bridge_destroyed(), ast_ari_validate_bridge_merged(), ast_ari_validate_bridge_video_source_changed(), ast_ari_validate_build_info(), ast_ari_validate_caller_id(), ast_ari_validate_channel(), ast_ari_validate_channel_caller_id(), ast_ari_validate_channel_connected_line(), ast_ari_validate_channel_created(), ast_ari_validate_channel_destroyed(), ast_ari_validate_channel_dialplan(), ast_ari_validate_channel_dtmf_received(), ast_ari_validate_channel_entered_bridge(), ast_ari_validate_channel_hangup_request(), ast_ari_validate_channel_hold(), ast_ari_validate_channel_left_bridge(), ast_ari_validate_channel_state_change(), ast_ari_validate_channel_talking_finished(), ast_ari_validate_channel_talking_started(), ast_ari_validate_channel_unhold(), ast_ari_validate_channel_userevent(), ast_ari_validate_channel_varset(), ast_ari_validate_config_info(), ast_ari_validate_config_tuple(), ast_ari_validate_contact_info(), ast_ari_validate_contact_status_change(), ast_ari_validate_device_state(), ast_ari_validate_device_state_changed(), ast_ari_validate_dial(), ast_ari_validate_dialed(), ast_ari_validate_dialplan_cep(), ast_ari_validate_endpoint(), ast_ari_validate_endpoint_state_change(), ast_ari_validate_event(), ast_ari_validate_format_lang_pair(), ast_ari_validate_live_recording(), ast_ari_validate_log_channel(), ast_ari_validate_mailbox(), ast_ari_validate_message(), ast_ari_validate_missing_params(), ast_ari_validate_module(), ast_ari_validate_peer(), ast_ari_validate_peer_status_change(), ast_ari_validate_playback(), ast_ari_validate_playback_continuing(), ast_ari_validate_playback_finished(), ast_ari_validate_playback_started(), ast_ari_validate_recording_failed(), ast_ari_validate_recording_finished(), ast_ari_validate_recording_started(), ast_ari_validate_rtpstat(), ast_ari_validate_set_id(), ast_ari_validate_sound(), ast_ari_validate_stasis_end(), ast_ari_validate_stasis_start(), ast_ari_validate_status_info(), ast_ari_validate_stored_recording(), ast_ari_validate_system_info(), ast_ari_validate_text_message(), ast_ari_validate_text_message_received(), ast_ari_validate_variable(), ast_json_to_ast_variables(), AST_TEST_DEFINE(), and manager_json_to_ast_str().
 {
    return json_object_iter_next((json_t *)object, iter);
 }
ast_json_object_iter_set()
int ast_json_object_iter_set (struct ast_json * object, struct ast_json_iter * iter, struct ast_json * value)
Set the value of the field pointed to by an iterator.
Since
12.0.0
Note
The object steals the value reference even if it returns error; use ast_json_ref() to safely keep a pointer to it.
Parameters
object JSON object iter was obtained from.
iter JSON object iterator.
value JSON value to store in 's field.
Returns
0 on success.
-1 on error.
Definition at line 449 of file json.c.
Referenced by AST_TEST_DEFINE().
 {
    return json_object_iter_set_new((json_t *)object, iter, (json_t *)value);
 }
ast_json_object_iter_value()
struct ast_json* ast_json_object_iter_value (struct ast_json_iter * iter)
Get the value from an iterator.
Since
12.0.0
The returned element is a borrowed reference; use ast_json_ref() to safely keep a pointer to it.
Parameters
iter JSON object iterator.
Returns
Value of the field iter points to.
Definition at line 445 of file json.c.
Referenced by ast_ari_validate_application(), ast_ari_validate_application_move_failed(), ast_ari_validate_application_replaced(), ast_ari_validate_asterisk_info(), ast_ari_validate_asterisk_ping(), ast_ari_validate_bridge(), ast_ari_validate_bridge_attended_transfer(), ast_ari_validate_bridge_blind_transfer(), ast_ari_validate_bridge_created(), ast_ari_validate_bridge_destroyed(), ast_ari_validate_bridge_merged(), ast_ari_validate_bridge_video_source_changed(), ast_ari_validate_build_info(), ast_ari_validate_caller_id(), ast_ari_validate_channel(), ast_ari_validate_channel_caller_id(), ast_ari_validate_channel_connected_line(), ast_ari_validate_channel_created(), ast_ari_validate_channel_destroyed(), ast_ari_validate_channel_dialplan(), ast_ari_validate_channel_dtmf_received(), ast_ari_validate_channel_entered_bridge(), ast_ari_validate_channel_hangup_request(), ast_ari_validate_channel_hold(), ast_ari_validate_channel_left_bridge(), ast_ari_validate_channel_state_change(), ast_ari_validate_channel_talking_finished(), ast_ari_validate_channel_talking_started(), ast_ari_validate_channel_unhold(), ast_ari_validate_channel_userevent(), ast_ari_validate_channel_varset(), ast_ari_validate_config_info(), ast_ari_validate_config_tuple(), ast_ari_validate_contact_info(), ast_ari_validate_contact_status_change(), ast_ari_validate_device_state(), ast_ari_validate_device_state_changed(), ast_ari_validate_dial(), ast_ari_validate_dialplan_cep(), ast_ari_validate_endpoint(), ast_ari_validate_endpoint_state_change(), ast_ari_validate_event(), ast_ari_validate_format_lang_pair(), ast_ari_validate_live_recording(), ast_ari_validate_log_channel(), ast_ari_validate_mailbox(), ast_ari_validate_message(), ast_ari_validate_missing_params(), ast_ari_validate_module(), ast_ari_validate_peer(), ast_ari_validate_peer_status_change(), ast_ari_validate_playback(), ast_ari_validate_playback_continuing(), ast_ari_validate_playback_finished(), ast_ari_validate_playback_started(), ast_ari_validate_recording_failed(), ast_ari_validate_recording_finished(), ast_ari_validate_recording_started(), ast_ari_validate_rtpstat(), ast_ari_validate_set_id(), ast_ari_validate_sound(), ast_ari_validate_stasis_end(), ast_ari_validate_stasis_start(), ast_ari_validate_status_info(), ast_ari_validate_stored_recording(), ast_ari_validate_system_info(), ast_ari_validate_text_message(), ast_ari_validate_text_message_received(), ast_ari_validate_variable(), ast_json_to_ast_variables(), AST_TEST_DEFINE(), and manager_json_to_ast_str().
 {
    return (struct ast_json *)json_object_iter_value(iter);
 }
ast_json_object_set()
int ast_json_object_set (struct ast_json * object, const char * key, struct ast_json * value)
Set a field in a JSON object.
Since
12.0.0
Note
The object steals the value reference even if it returns error; use ast_json_ref() to safely keep a pointer to it.
Parameters
object JSON object to modify.
key Key of field to set.
value JSON value to set for field.
Returns
0 on success.
-1 on error.
Definition at line 404 of file json.c.
Referenced by add_ip_json_object(), add_json_object(), alloc_security_event_json_object(), app_send(), ast_ari_asterisk_get_info(), ast_ari_get_docs(), ast_bridge_snapshot_to_json(), ast_bucket_file_json(), ast_bucket_json(), ast_channel_snapshot_to_json(), ast_endpoint_snapshot_to_json(), ast_json_channel_vars(), ast_rtp_convert_stats_json(), ast_sip_subscription_set_persistence_data(), ast_sorcery_objectset_json_create(), AST_TEST_DEFINE(), attended_transfer_to_json(), blind_transfer_to_json(), channel_blob_to_json(), devices_to_json(), dial_to_json(), external_media_audiosocket_tcp(), external_media_rtp_udp(), handler(), identify_module(), launch_asyncagi(), meetme_stasis_generate_msg(), msg_to_json(), multi_user_event_to_json(), publish_acl_change(), recording_publish(), stasis_app_event_filter_to_json(), stasis_app_message_handler(), stasis_app_recording_to_json(), stasis_app_user_event(), stasis_start_to_json(), stir_shaken_add_attest(), stir_shaken_add_iat(), stir_shaken_add_origid(), stir_shaken_add_x5u(), sub_bridge_update_handler(), units_to_json(), and userevent_exec().
 {
    return json_object_set_new((json_t *)object, key, (json_t *)value);
 }
ast_json_object_size()
size_t ast_json_object_size (struct ast_json * object)
Get size of JSON object.
Since
12.0.0
Parameters
object JSON object.
Returns
Size of object.
Zero of object is not a JSON object.
Definition at line 393 of file json.c.
Referenced by app_event_filter_set(), and AST_TEST_DEFINE().
 {
    return json_object_size((json_t *)object);
 }
ast_json_object_update()
int ast_json_object_update (struct ast_json * object, struct ast_json * other)
Update object with all of the fields of other.
Since
12.0.0
All of the fields of other are copied into object, overwriting existing keys. The other object is not changed, so ast_json_unref() it when you are done with it.
Parameters
object JSON object to modify.
other JSON object to copy into object.
Returns
0 on success.
-1 on error.
Definition at line 416 of file json.c.
Referenced by AST_TEST_DEFINE(), cc_publish(), channel_to_json(), meetme_stasis_generate_msg(), peerstatus_to_json(), send_conf_stasis(), and send_conf_stasis_snapshots().
 {
    return json_object_update((json_t *)object, (json_t *)other);
 }
ast_json_object_update_existing()
int ast_json_object_update_existing (struct ast_json * object, struct ast_json * other)
Update existing fields in object with the fields of other.
Since
12.0.0
Like ast_json_object_update(), but only existing fields are updated. No new fields will get added. The other object is not changed, so ast_json_unref() it when you are done with it.
Parameters
object JSON object to modify.
other JSON object to copy into object.
Returns
0 on success.
-1 on error.
Definition at line 420 of file json.c.
Referenced by AST_TEST_DEFINE().
 {
    return json_object_update_existing((json_t *)object, (json_t *)other);
 }
ast_json_object_update_missing()
int ast_json_object_update_missing (struct ast_json * object, struct ast_json * other)
Add new fields to object with the fields of other.
Since
12.0.0
Like ast_json_object_update(), but only missing fields are added. No existing fields will be modified. The other object is not changed, so ast_json_unref() it when you are done with it.
Parameters
object JSON object to modify.
other JSON object to copy into object.
Returns
0 on success.
-1 on error.
Definition at line 424 of file json.c.
Referenced by AST_TEST_DEFINE().
 {
    return json_object_update_missing((json_t *)object, (json_t *)other);
 }
ast_json_pack()
struct ast_json* ast_json_pack (char const * format, ...)
Helper for creating complex JSON values.
Since
12.0.0
See original Jansson docs at http://www.digip.org/jansson/doc/2.11/apiref.html#apiref-pack for more details.
Definition at line 591 of file json.c.
References args, and ast_json_vpack().
Referenced by __ast_test_suite_event_notify(), __expire_registry(), __iax2_poke_noanswer(), add_format_information_cb(), add_identity_header(), agi_handle_command(), analog_publish_channel_alarm_clear(), analog_publish_dnd_state(), app_send_end_msg(), app_to_json(), app_update(), association_to_json(), ast_ari_asterisk_get_global_var(), ast_ari_asterisk_get_info(), ast_ari_asterisk_ping(), ast_ari_channels_get_channel_var(), ast_ari_response_error(), ast_bridge_channel_write_hold(), ast_bridge_merge_message_to_json(), ast_bridge_publish_enter(), ast_bridge_snapshot_to_json(), ast_cel_publish_event(), ast_channel_move(), ast_channel_publish_dial_internal(), ast_channel_publish_varset(), ast_channel_snapshot_to_json(), ast_endpoint_snapshot_to_json(), ast_json_dialplan_cep_app(), ast_json_name_number(), ast_json_party_id(), ast_manager_publish_event(), ast_queue_hangup_with_cause(), ast_queue_hold(), ast_rtcp_calculate_sr_rr_statistics(), ast_rtcp_interpret(), ast_sip_persistent_endpoint_publish_contact_state(), ast_sip_persistent_endpoint_update_state(), ast_softhangup(), ast_system_publish_registry(), AST_TEST_DEFINE(), asterisk_publication_send_refresh(), asterisk_publisher_devstate_cb(), asterisk_publisher_mwistate_cb(), attended_transfer_to_json(), beanstalk_put(), blind_transfer_to_json(), cc_publish(), cc_publish_available(), cc_publish_callerrecalling(), cc_publish_callerstartmonitoring(), cc_publish_callerstopmonitoring(), cc_publish_failure(), cc_publish_monitorfailed(), cc_publish_offertimerstart(), cc_publish_recallcomplete(), cc_publish_requestacknowledged(), cc_publish_requested(), cel_attended_transfer_cb(), cel_blind_transfer_cb(), cel_bridge_enter_cb(), cel_bridge_leave_cb(), cel_bs_put(), cel_channel_state_change(), cel_dial_cb(), cel_local_cb(), cel_parking_cb(), cel_pickup_cb(), celgenuserevent_exec(), channel_callerid(), channel_connected_line(), channel_destroyed_event(), channel_dialplan(), charge_to_json(), conf_handle_talker_cb(), confbridge_handle_atxfer(), contactstatus_to_json(), create_sound_blob(), currency_to_json(), d_to_json(), dial_to_json(), dtmf_end_to_json(), e_to_json(), expire_register(), format_log_json(), handle_response_peerpoke(), handler(), hold_to_json(), join_queue(), json_party_name(), json_party_number(), json_party_subaddress(), launch_asyncagi(), leave_queue(), load_module(), local_optimization_finished_cb(), local_optimization_started_cb(), mailbox_to_json(), manager_mute_mixmonitor(), meetme_stasis_generate_msg(), message_received_handler(), moh_post_start(), msg_to_json(), notify_new_message(), pack_bridge_and_channels(), parse_register_contact(), peerstatus_to_json(), phase_e_handler(), playback_to_json(), process_log_list(), process_module_list(), publish_async_exec_end(), publish_channel_alarm(), publish_channel_alarm_clear(), publish_cluster_discovery_to_stasis_full(), publish_dahdichannel(), publish_dnd_state(), publish_format_update(), publish_fully_booted(), publish_hangup_handler_message(), publish_load_message_type(), publish_local_bridge_message(), publish_qualify_peer_done(), publish_span_alarm(), publish_span_alarm_clear(), queue_member_blob_create(), really_quit(), record_abandoned(), recording_to_json(), register_verify(), report_fax_status(), report_receive_fax_status(), report_send_fax_status(), return_sorcery_object(), ring_entry(), rna(), rtcp_report_to_json(), s_to_json(), send_agent_complete(), send_agent_login(), send_agent_logoff(), send_conf_stasis(), send_conf_stasis_snapshots(), send_device_state(), send_dtmf_begin_event(), send_dtmf_end_event(), send_join_event(), send_leave_event(), send_mute_event(), send_session_timeout(), send_start_msg_snapshots(), send_unmute_event(), simple_bridge_channel_event(), simple_bridge_event(), simple_channel_event(), simple_endpoint_event(), sip_poke_noanswer(), skinny_register(), skinny_session_cleanup(), socket_process_helper(), stasis_app_device_state_to_json(), stasis_app_exec(), stasis_app_playback_to_json(), stasis_app_recording_to_json(), stasis_app_stored_recording_to_json(), stasis_app_user_event(), stasis_end_to_json(), stasis_start_to_json(), status_to_json(), talk_detect_audiohook_cb(), test_name_number(), try_calling(), unhold_to_json(), unload_module(), update_registry(), and userevent_exec().
 {
    struct ast_json *ret;
    va_list args;
    va_start(args, format);
    ret = ast_json_vpack(format, args);
    va_end(args);
    return ret;
 }
ast_json_party_id()
struct ast_json* ast_json_party_id (struct ast_party_id * party)
Construct an ast_party_id as JSON.
Since
12.0.0
Parameters
party The party ID to represent as JSON.
Returns
JSON object with name, number and subaddress objects for those that are valid in the party ID
Definition at line 784 of file json.c.
References ast_describe_caller_presentation(), ast_json_pack(), ast_party_id_presentation(), json_party_name(), json_party_number(), json_party_subaddress(), ast_party_id::name, ast_party_id::number, and ast_party_id::subaddress.
 {
    int pres = ast_party_id_presentation(party);
    /* Combined party presentation */
    return ast_json_pack("{s: i, s: s, s: o*, s: o*, s: o*}",
       "presentation", pres,
       "presentation_txt", ast_describe_caller_presentation(pres),
       "number", json_party_number(&party->number),
       "name", json_party_name(&party->name),
       "subaddress", json_party_subaddress(&party->subaddress));
 }
ast_json_payload_create()
struct ast_json_payload* ast_json_payload_create (struct ast_json * json)
Create an ao2 object to pass json blobs as data payloads for stasis.
Since
12.0.0
Parameters
json the ast_json blob we are loading
Return values
NULL if we fail to alloc it
pointer to the ast_json_payload created
Definition at line 735 of file json.c.
References ao2_alloc, ast_json_ref(), ast_json_payload::json, json_payload_destructor(), and NULL.
Referenced by ast_manager_publish_event(), ast_system_publish_registry(), cc_publish(), handle_security_event(), publish_acl_change(), publish_cluster_discovery_to_stasis_full(), publish_format_update(), publish_load_message_type(), queue_publish_member_blob(), and stun_monitor_request().
 {
    struct ast_json_payload *payload;
    if (!(payload = ao2_alloc(sizeof(*payload), json_payload_destructor))) {
       return NULL;
    }
    ast_json_ref(json);
    payload->json = json;
    return payload;
 }
ast_json_real_create()
struct ast_json* ast_json_real_create (double value)
Create a JSON real number.
Since
12.0.0
Parameters
value Value of the new JSON real number.
Returns
Newly allocated real number.
NULL on error.
Definition at line 332 of file json.c.
Referenced by ast_ari_asterisk_get_info(), and ast_rtp_convert_stats_json().
 {
    return (struct ast_json *)json_real(value);
 }
ast_json_real_get()
double ast_json_real_get (const struct ast_json * real)
Get the value from a JSON real number.
Since
12.0.0
Parameters
real JSON real number.
Returns
Value of a JSON real number.
0 if real is not a JSON real number.
Definition at line 337 of file json.c.
Referenced by rtcp_report_to_ami().
 {
    return json_real_value((json_t *)real);
 }
ast_json_real_set()
int ast_json_real_set (struct ast_json * real, double value)
Set the value of a JSON real number.
Since
12.0.0
Parameters
integer JSON real number to modify.
value New value for real.
Returns
0 on success.
-1 on error.
Definition at line 342 of file json.c.
 {
    return json_real_set((json_t *)real, value);
 }
ast_json_ref()
struct ast_json* ast_json_ref (struct ast_json * value)
Increase refcount on value.
Since
12.0.0
Parameters
value JSON value to reference.
Returns
The given value.
Definition at line 67 of file json.c.
Referenced by alloc_security_event_json_object(), allocate_subscription(), aoc_publish_blob(), app_event_filter_set(), ari_bridges_play_found(), ari_bridges_play_new(), ast_ari_applications_list(), ast_ari_applications_subscribe(), ast_ari_applications_unsubscribe(), ast_ari_asterisk_get_global_var(), ast_ari_asterisk_get_info(), ast_ari_bridges_list(), ast_ari_bridges_record(), ast_ari_channels_get_channel_var(), ast_ari_channels_list(), ast_ari_endpoints_list(), ast_ari_endpoints_list_by_tech(), ast_ari_recordings_list_stored(), ast_ari_response_alloc_failed(), ast_ari_response_error(), ast_ari_websocket_session_read(), ast_bridge_blob_create(), ast_bridge_blob_create_from_snapshots(), ast_bucket_file_json(), ast_bucket_json(), ast_cel_publish_event(), ast_endpoint_blob_create(), ast_json_payload_create(), ast_manager_publish_event(), ast_multi_channel_blob_create(), ast_multi_object_blob_create(), ast_mwi_blob_create(), ast_rtp_publish_rtcp_message(), ast_sip_subscription_set_persistence_data(), AST_TEST_DEFINE(), attended_transfer_to_json(), create_channel_blob_message(), create_sound_blob(), generate_filenames_json(), json_array_from_list(), message_received_handler(), multi_user_event_to_json(), phase_e_handler(), publish_load_message_type(), report_receive_fax_status(), return_sorcery_object(), stasis_app_event_filter_to_json(), stasis_app_message_handler(), stasis_app_playback_to_json(), stasis_app_recording_to_json(), and stasis_app_user_event().
 {
    json_incref((json_t *)json);
    return json;
 }
ast_json_reset_alloc_funcs()
void ast_json_reset_alloc_funcs (void)
Change alloc funcs back to the resource module defaults.
Since
12.0.0
If you use ast_json_set_alloc_funcs() to temporarily change the allocator functions (i.e., from in a unit test), this function sets them back to ast_malloc() and ast_free().
Definition at line 62 of file json.c.
References ast_json_free(), and ast_json_malloc().
Referenced by ast_json_init(), and json_test_cleanup().
 {
    json_set_alloc_funcs(ast_json_malloc, ast_json_free);
 }
ast_json_set_alloc_funcs()
void ast_json_set_alloc_funcs (void *(*)(size_t) malloc_fn, void(*)(void *) free_fn)
Set custom allocators instead of the standard ast_malloc() and ast_free().
Since
12.0.0
This is used by the unit tests to do JSON specific memory leak detection. Since it affects all users of the JSON library, shouldn't normally be used.
Parameters
malloc_fn Custom allocation function.
free_fn Matching free function.
Definition at line 57 of file json.c.
Referenced by json_test_init().
 {
    json_set_alloc_funcs(malloc_fn, free_fn);
 }
ast_json_string_create()
struct ast_json* ast_json_string_create (const char * value)
Construct a JSON string from value.
Since
12.0.0
The given value must be a valid ASCII or UTF-8 encoded string.
Parameters
value Value of new JSON string.
Returns
Newly constructed string element.
NULL on error.
Definition at line 268 of file json.c.
Referenced by add_json_object(), alloc_security_event_json_object(), app_send(), app_to_json(), ast_bridge_snapshot_to_json(), ast_bucket_file_json(), ast_bucket_json(), ast_endpoint_snapshot_to_json(), ast_json_channel_vars(), ast_json_ipaddr(), ast_json_timeval(), ast_rtp_convert_stats_json(), ast_sorcery_objectset_json_create(), AST_TEST_DEFINE(), attended_transfer_to_json(), channel_blob_to_json(), container_to_json_array(), device_to_json_cb(), fake_json(), generate_filenames_json(), handler(), identify_module(), json_array_from_list(), launch_asyncagi(), msg_to_json(), multi_user_event_to_json(), publish_acl_change(), recording_publish(), report_receive_fax_status(), send_start_msg_snapshots(), stasis_app_exec(), stasis_app_message_handler(), stasis_app_user_event(), stir_shaken_add_attest(), stir_shaken_add_origid(), stir_shaken_add_x5u(), sub_bridge_update_handler(), and userevent_exec().
 {
    return (struct ast_json *)json_string(value);
 }
ast_json_string_get()
const char* ast_json_string_get (const struct ast_json * string)
Get the value of a JSON string.
Since
12.0.0
Parameters
string JSON string.
Returns
Value of the string.
NULL on error.
Definition at line 273 of file json.c.
Referenced by agent_login_to_ami(), agent_logoff_to_ami(), app_send(), append_event_str_single(), append_json_single(), assign_uuid(), ast_ari_applications_subscribe_parse_body(), ast_ari_applications_unsubscribe_parse_body(), ast_ari_asterisk_add_log_parse_body(), ast_ari_asterisk_get_global_var_parse_body(), ast_ari_asterisk_get_info_parse_body(), ast_ari_asterisk_set_global_var_parse_body(), ast_ari_asterisk_update_object(), ast_ari_bridges_add_channel_parse_body(), ast_ari_bridges_create_parse_body(), ast_ari_bridges_create_with_id_parse_body(), ast_ari_bridges_play_parse_body(), ast_ari_bridges_play_with_id_parse_body(), ast_ari_bridges_record_parse_body(), ast_ari_bridges_remove_channel_parse_body(), ast_ari_bridges_start_moh_parse_body(), ast_ari_callback(), ast_ari_channels_continue_in_dialplan_parse_body(), ast_ari_channels_create_parse_body(), ast_ari_channels_dial_parse_body(), ast_ari_channels_external_media_parse_body(), ast_ari_channels_get_channel_var_parse_body(), ast_ari_channels_hangup_parse_body(), ast_ari_channels_move_parse_body(), ast_ari_channels_mute_parse_body(), ast_ari_channels_originate_parse_body(), ast_ari_channels_originate_with_id_parse_body(), ast_ari_channels_play_parse_body(), ast_ari_channels_play_with_id_parse_body(), ast_ari_channels_record_parse_body(), ast_ari_channels_redirect_parse_body(), ast_ari_channels_send_dtmf_parse_body(), ast_ari_channels_set_channel_var_parse_body(), ast_ari_channels_snoop_channel_parse_body(), ast_ari_channels_snoop_channel_with_id_parse_body(), ast_ari_channels_start_moh_parse_body(), ast_ari_channels_unmute_parse_body(), ast_ari_device_states_update_parse_body(), ast_ari_endpoints_send_message_parse_body(), ast_ari_endpoints_send_message_to_endpoint_parse_body(), ast_ari_events_user_event_parse_body(), ast_ari_playbacks_control_parse_body(), ast_ari_recordings_copy_stored_parse_body(), ast_ari_sounds_list_parse_body(), ast_ari_validate_date(), ast_ari_validate_event(), ast_ari_validate_message(), ast_json_to_ast_variables(), ast_stir_shaken_sign(), AST_TEST_DEFINE(), asterisk_publication_devicestate(), asterisk_publication_devicestate_state_change(), asterisk_publication_mailboxstate(), asterisk_publication_mwi_state_change(), cc_available_to_ami(), cc_callerrecalling_to_ami(), cc_callerstartmonitoring_to_ami(), cc_callerstopmonitoring_to_ami(), cc_failure_to_ami(), cc_monitorfailed_to_ami(), cc_offertimerstart_to_ami(), cc_recallcomplete_to_ami(), cc_requestacknowledged_to_ami(), cc_requested_to_ami(), cel_generic_cb(), channel_dial_cb(), channel_dtmf_begin_cb(), channel_dtmf_end_cb(), channel_enter_cb(), channel_fax_cb(), channel_hangup_handler_cb(), channel_hold_cb(), channel_mixmonitor_mute_cb(), channel_moh_start_cb(), compare_caller_id(), confbridge_publish_manager_event(), confbridge_talking_cb(), contactstatus_to_ami(), contactstatus_to_json(), dahdichannel_to_ami(), dial_to_json(), dtmf_end_to_json(), fetch_access_token(), fetch_google_access_token(), get_attestation_from_payload(), get_blob_variable(), handle_dial_message(), handle_masquerade(), hold_to_json(), local_message_to_ami(), manager_generic_msg_cb(), manager_json_value_str_append(), meetme_stasis_cb(), multi_user_event_to_ami(), mwi_app_event_cb(), mwi_startup_event_cb(), peerstatus_to_ami(), playback_to_json(), queue_agent_cb(), recording_to_json(), registry_message_cb(), rtcp_message_handler(), rtcp_report_to_ami(), session_timeout_to_ami(), startup_event_cb(), stasis_app_message_handler(), stir_shaken_verify_json(), subscription_persistence_event_cb(), system_registry_to_ami(), test_suite_event_to_ami(), and varset_to_ami().
 {
    return json_string_value((json_t *)string);
 }
ast_json_string_set()
int ast_json_string_set (struct ast_json * string, const char * value)
Change the value of a JSON string.
Since
12.0.0
The given value must be a valid ASCII or UTF-8 encoded string.
Parameters
string JSON string to modify.
value New value to store in string.
Returns
0 on success.
-1 on error.
Definition at line 278 of file json.c.
Referenced by AST_TEST_DEFINE(), and conf_send_event_to_participants().
 {
    return json_string_set((json_t *)string, value);
 }
ast_json_stringf()
struct ast_json* ast_json_stringf (const char * format, ...)
Create a JSON string, printf style.
Since
12.0.0
The formatted value must be a valid ASCII or UTF-8 encoded string.
Parameters
format printf style format string.
Returns
Newly allocated string.
NULL on error.
Definition at line 283 of file json.c.
References args, and ast_json_vstringf().
Referenced by add_json_object(), alloc_security_event_json_object(), ast_ari_get_docs(), AST_TEST_DEFINE(), and units_to_json().
 {
    struct ast_json *ret;
    va_list args;
    va_start(args, format);
    ret = ast_json_vstringf(format, args);
    va_end(args);
    return ret;
 }
ast_json_timeval()
struct ast_json* ast_json_timeval (const struct timeval tv, const char * zone)
Construct a timeval as JSON.
JSON does not define a standard date format (boo), but the de facto standard is to use ISO 8601 formatted string. We build a millisecond resolution string from the timeval
Parameters
tv timeval to encode.
zone Text string of a standard system zoneinfo file. If NULL, the system localtime will be used.
Returns
JSON string with ISO 8601 formatted date/time.
NULL on error.
Definition at line 649 of file json.c.
References AST_ISO8601_FORMAT, AST_ISO8601_LEN, ast_json_string_create(), ast_localtime(), ast_strftime(), and buf.
Referenced by add_json_object(), alloc_security_event_json_object(), app_send_end_msg(), app_update(), ast_ari_asterisk_get_info(), ast_ari_asterisk_ping(), ast_bridge_merge_message_to_json(), ast_bridge_snapshot_to_json(), ast_channel_snapshot_to_json(), AST_TEST_DEFINE(), attended_transfer_to_json(), blind_transfer_to_json(), channel_blob_to_json(), channel_callerid(), channel_connected_line(), channel_destroyed_event(), channel_dialplan(), contactstatus_to_json(), dial_to_json(), dtmf_end_to_json(), hold_to_json(), message_received_handler(), multi_user_event_to_json(), pack_bridge_and_channels(), peerstatus_to_json(), playback_to_json(), recording_to_json(), send_device_state(), send_start_msg_snapshots(), simple_bridge_channel_event(), simple_bridge_event(), simple_channel_event(), simple_endpoint_event(), stasis_app_exec(), and unhold_to_json().
 {
    char buf[AST_ISO8601_LEN];
    struct ast_tm tm = {};
    ast_localtime(&tv, &tm, zone);
    ast_strftime(buf, sizeof(buf),AST_ISO8601_FORMAT, &tm);
    return ast_json_string_create(buf);
 }
ast_json_to_ast_variables()
enum ast_json_to_ast_vars_code ast_json_to_ast_variables (struct ast_json * json_variables, struct ast_variable ** variables)
Convert a ast_json list of key/value pair tuples into a ast_variable list.
Since
12.5.0
Parameters
json_variables The JSON blob containing the variable
variables An out reference to the variables to populate.
struct ast_json *json_variables = ast_json_pack("[ { s: s } ]", "foo", "bar");
struct ast_variable *variables = NULL;
int res;
res = ast_json_to_ast_variables(json_variables, &variables);
Returns
Conversion enum ast_json_to_ast_vars_code status
Definition at line 797 of file json.c.
References ast_assert, ast_json_object_iter(), ast_json_object_iter_key(), ast_json_object_iter_next(), ast_json_object_iter_value(), AST_JSON_STRING, ast_json_string_get(), AST_JSON_TO_AST_VARS_CODE_INVALID_TYPE, AST_JSON_TO_AST_VARS_CODE_OOM, AST_JSON_TO_AST_VARS_CODE_SUCCESS, ast_json_typeof(), ast_strlen_zero, ast_variable_list_append_hint(), ast_variable_new, ast_variables_destroy(), NULL, and value.
Referenced by json_to_ast_variables(), sorcery_astdb_retrieve_fields_common(), sorcery_astdb_retrieve_id(), sorcery_astdb_retrieve_prefix(), and sorcery_astdb_retrieve_regex().
 {
    struct ast_json_iter *it_json_var;
    struct ast_variable *tail = NULL;
    *variables = NULL;
    for (it_json_var = ast_json_object_iter(json_variables); it_json_var;
       it_json_var = ast_json_object_iter_next(json_variables, it_json_var)) {
       struct ast_variable *new_var;
       const char *key = ast_json_object_iter_key(it_json_var);
       const char *value;
       struct ast_json *json_value;
       if (ast_strlen_zero(key)) {
          continue;
       }
       json_value = ast_json_object_iter_value(it_json_var);
       if (ast_json_typeof(json_value) != AST_JSON_STRING) {
          /* Error: Only strings allowed */
          ast_variables_destroy(*variables);
          *variables = NULL;
          return AST_JSON_TO_AST_VARS_CODE_INVALID_TYPE;
       }
       value = ast_json_string_get(json_value);
       /* Should never be NULL.  Otherwise, how could it be a string type? */
       ast_assert(value != NULL);
       if (!value) {
          /* To be safe. */
          continue;
       }
       new_var = ast_variable_new(key, value, "");
       if (!new_var) {
          /* Error: OOM */
          ast_variables_destroy(*variables);
          *variables = NULL;
          return AST_JSON_TO_AST_VARS_CODE_OOM;
       }
       tail = ast_variable_list_append_hint(variables, tail, new_var);
    }
    return AST_JSON_TO_AST_VARS_CODE_SUCCESS;
 }
ast_json_true()
struct ast_json* ast_json_true (void)
Get the JSON true value.
Since
12.0.0
The returned value is a singleton, and does not need to be ast_json_unref()'ed.
Returns
JSON true.
Definition at line 233 of file json.c.
Referenced by AST_TEST_DEFINE().
 {
    return (struct ast_json *)json_true();
 }
ast_json_typename()
const char* ast_json_typename (enum ast_json_type type)
Get the string name for the given type.
Since
12.0.0
Parameters
type Type to convert to string.
Returns
Simple string for the type name (object, array, string, etc.)
"?" for invalid types.
Definition at line 95 of file json.c.
References ast_assert, AST_JSON_ARRAY, AST_JSON_FALSE, AST_JSON_INTEGER, AST_JSON_NULL, AST_JSON_OBJECT, AST_JSON_REAL, AST_JSON_STRING, and AST_JSON_TRUE.
Referenced by ast_ari_validate_boolean(), and check_type().
 {
    switch (type) {
    case AST_JSON_OBJECT: return "object";
    case AST_JSON_ARRAY: return "array";
    case AST_JSON_STRING: return "string";
    case AST_JSON_INTEGER: return "integer";
    case AST_JSON_REAL: return "real";
    case AST_JSON_TRUE: return "boolean";
    case AST_JSON_FALSE: return "boolean";
    case AST_JSON_NULL: return "null";
    }
    ast_assert(0);
    return "?";
 }
ast_json_typeof()
enum ast_json_type ast_json_typeof (const struct ast_json * value)
Get the type of value.
Since
12.0.0
Parameters
value Value to query.
Returns
Type of value.
Definition at line 78 of file json.c.
References ast_assert, AST_JSON_ARRAY, AST_JSON_FALSE, AST_JSON_INTEGER, AST_JSON_NULL, AST_JSON_OBJECT, AST_JSON_REAL, AST_JSON_STRING, and AST_JSON_TRUE.
Referenced by app_event_filter_set(), ast_ari_applications_subscribe_parse_body(), ast_ari_applications_unsubscribe_parse_body(), ast_ari_asterisk_get_info_parse_body(), ast_ari_bridges_add_channel_parse_body(), ast_ari_bridges_play_parse_body(), ast_ari_bridges_play_with_id_parse_body(), ast_ari_bridges_remove_channel_parse_body(), ast_ari_channels_play_parse_body(), ast_ari_channels_play_with_id_parse_body(), ast_ari_events_user_event_parse_body(), ast_ari_validate_boolean(), ast_json_to_ast_variables(), AST_TEST_DEFINE(), check_type(), manager_json_to_ast_str(), manager_json_value_str_append(), and pack_bridge_and_channels().
 {
    int r = json_typeof((json_t*)json);
    switch(r) {
    case JSON_OBJECT: return AST_JSON_OBJECT;
    case JSON_ARRAY: return AST_JSON_ARRAY;
    case JSON_STRING: return AST_JSON_STRING;
    case JSON_INTEGER: return AST_JSON_INTEGER;
    case JSON_REAL: return AST_JSON_REAL;
    case JSON_TRUE: return AST_JSON_TRUE;
    case JSON_FALSE: return AST_JSON_FALSE;
    case JSON_NULL: return AST_JSON_NULL;
    }
    ast_assert(0); /* Unexpect return from json_typeof */
    return r;
 }
ast_json_unref()
void ast_json_unref (struct ast_json * value)
Decrease refcount on value. If refcount reaches zero, value is freed.
Since
12.0.0
Note
It is safe to pass NULL to this function.
Definition at line 73 of file json.c.
Referenced by __expire_registry(), __iax2_poke_noanswer(), agi_handle_command(), alloc_security_event_json_object(), analog_publish_channel_alarm_clear(), analog_publish_dnd_state(), aoc_event_blob_dtor(), app_data_dtor(), app_dtor(), app_event_filter_set(), app_send_end_msg(), app_to_json(), app_update(), ari_bridges_play_found(), ari_bridges_play_new(), ast_aoc_manager_event(), ast_ari_applications_list(), ast_ari_applications_subscribe(), ast_ari_applications_unsubscribe(), ast_ari_asterisk_get_global_var(), ast_ari_asterisk_get_info(), ast_ari_asterisk_get_module(), ast_ari_asterisk_list_log_channels(), ast_ari_bridges_list(), ast_ari_bridges_record(), ast_ari_callback(), ast_ari_channels_get_channel_var(), ast_ari_channels_list(), ast_ari_endpoints_list(), ast_ari_endpoints_list_by_tech(), ast_ari_recordings_list_stored(), ast_ari_response_error(), ast_ari_sounds_list(), ast_ari_websocket_events_event_websocket_established(), ast_ari_websocket_session_read(), ast_bridge_channel_write_hold(), ast_bridge_merge_message_to_json(), ast_bridge_publish_enter(), ast_bucket_file_json(), ast_bucket_json(), ast_cel_publish_event(), ast_channel_move(), ast_channel_publish_dial_internal(), ast_channel_publish_varset(), ast_endpoint_snapshot_to_json(), ast_manager_publish_event(), ast_queue_hangup_with_cause(), ast_queue_hold(), ast_rtcp_calculate_sr_rr_statistics(), ast_rtcp_interpret(), ast_rtp_convert_stats_json(), ast_sip_persistent_endpoint_publish_contact_state(), ast_sip_persistent_endpoint_update_state(), ast_sip_subscription_set_persistence_data(), ast_softhangup(), ast_sorcery_objectset_json_create(), ast_stir_shaken_payload_free(), ast_system_publish_registry(), AST_TEST_DEFINE(), asterisk_publication_devicestate_state_change(), asterisk_publication_mwi_state_change(), asterisk_publication_send_refresh(), asterisk_publisher_devstate_cb(), asterisk_publisher_mwistate_cb(), attended_transfer_to_json(), beanstalk_put(), blind_transfer_to_json(), bridge_blob_dtor(), cc_publish(), cc_publish_available(), cc_publish_callerrecalling(), cc_publish_callerstartmonitoring(), cc_publish_callerstopmonitoring(), cc_publish_failure(), cc_publish_monitorfailed(), cc_publish_offertimerstart(), cc_publish_recallcomplete(), cc_publish_requestacknowledged(), cc_publish_requested(), cel_attended_transfer_cb(), cel_blind_transfer_cb(), cel_bridge_enter_cb(), cel_bridge_leave_cb(), cel_bs_put(), cel_channel_state_change(), cel_dial_cb(), cel_local_cb(), cel_parking_cb(), cel_pickup_cb(), celgenuserevent_exec(), channel_blob_dtor(), channel_blob_to_json(), channel_to_json(), conf_handle_talker_cb(), conf_run(), conf_send_event_to_participants(), confbridge_handle_atxfer(), contactstatus_to_json(), container_to_json_array(), create_sound_blob(), destroy_subscription(), dial_to_json(), endpoint_blob_dtor(), event_session_shutdown(), event_session_update_websocket(), expire_register(), fetch_access_token(), fetch_google_access_token(), format_log_json(), generate_filenames_json(), handle_msg_cb(), handle_response_peerpoke(), handle_security_event(), join_queue(), json_array_from_list(), json_payload_destructor(), launch_asyncagi(), leave_queue(), local_optimization_finished_cb(), local_optimization_started_cb(), manager_mute_mixmonitor(), meetme_stasis_generate_msg(), message_received_handler(), moh_post_start(), msg_to_json(), multi_channel_blob_dtor(), multi_object_blob_dtor(), mwi_blob_dtor(), notify_new_message(), parse_register_contact(), peerstatus_to_json(), phase_e_handler(), playback_publish(), publish_acl_change(), publish_async_exec_end(), publish_channel_alarm(), publish_channel_alarm_clear(), publish_chanspy_message(), publish_cluster_discovery_to_stasis_full(), publish_dahdichannel(), publish_dnd_state(), publish_format_update(), publish_fully_booted(), publish_hangup_handler_message(), publish_load_message_type(), publish_local_bridge_message(), publish_qualify_peer_done(), publish_span_alarm(), publish_span_alarm_clear(), queue_publish_member_blob(), really_quit(), record_abandoned(), recording_publish(), register_verify(), report_fax_status(), report_receive_fax_status(), report_send_fax_status(), response_free(), return_sorcery_object(), ring_entry(), rna(), rtcp_message_handler(), rtcp_message_payload_dtor(), rtcp_report_to_json(), send_agent_complete(), send_agent_login(), send_agent_logoff(), send_conf_stasis(), send_conf_stasis_snapshots(), send_device_state(), send_dtmf_begin_event(), send_dtmf_end_event(), send_join_event(), send_leave_event(), send_mute_event(), send_session_timeout(), send_talking_event(), send_unmute_event(), simple_bridge_channel_event(), sip_poke_noanswer(), skinny_register(), skinny_session_cleanup(), socket_process_helper(), sorcery_astdb_create(), sorcery_astdb_retrieve_fields_common(), sorcery_astdb_retrieve_id(), sorcery_astdb_retrieve_prefix(), sorcery_astdb_retrieve_regex(), start_message_blob_dtor(), stasis_app_exec(), stasis_app_mailboxes_to_json(), stasis_app_playback_to_json(), stasis_app_recording_to_json(), stasis_app_user_event(), stasis_start_to_json(), stun_monitor_request(), sub_bridge_update_handler(), sub_channel_update_handler(), sub_default_handler(), sub_endpoint_update_handler(), subscription_persistence_destroy(), talk_detect_audiohook_cb(), test_name_number(), test_suite_message_payload_dtor(), try_calling(), unload_module(), update_registry(), and userevent_exec().
 {
    json_decref((json_t *) json);
 }
ast_json_utf8_check()
int ast_json_utf8_check (const char * str)
Check the nul terminated string for UTF-8 format.
Since
13.12.0
Parameters
str String to check.
Return values
0 if not UTF-8 encoded or str is NULL.
1 if UTF-8 encoded.
Definition at line 228 of file json.c.
References ast_json_utf8_check_len().
 {
    return str ? ast_json_utf8_check_len(str, strlen(str)) : 0;
 }
ast_json_utf8_check_len()
int ast_json_utf8_check_len (const char * str, size_t len)
Check the string of the given length for UTF-8 format.
Since
13.12.0
Parameters
str String to check.
len Length of string to check.
Return values
0 if not UTF-8 encoded or str is NULL.
1 if UTF-8 encoded.
Definition at line 186 of file json.c.
References ast_debug, json_utf8_check_first(), json_utf8_check_full(), and len().
Referenced by ast_json_utf8_check().
 {
    size_t pos;
    size_t count;
    int res = 1;
    if (!str) {
       return 0;
    }
    /*
     * Since the json library does not make the check function
     * public we recreate/copy the function in our interface
     * module.
     *
     * Loop ported from libjansson utf.c:utf8_check_string()
     */
    for (pos = 0; pos < len; pos += count) {
       count = json_utf8_check_first(str[pos]);
       if (count == 0) {
          res = 0;
          break;
       } else if (count > 1) {
          if (count > len - pos) {
             /* UTF-8 needs more than we have left in the string. */
             res = 0;
             break;
          }
          if (!json_utf8_check_full(&str[pos], count)) {
             res = 0;
             break;
          }
       }
    }
    if (!res) {
       ast_debug(1, "String '%.*s' is not UTF-8 for json conversion\n", (int) len, str);
    }
    return res;
 }
ast_json_vpack()
struct ast_json* ast_json_vpack (char const * format, va_list ap)
Helper for creating complex JSON values simply.
Since
12.0.0
See original Jansson docs at http://www.digip.org/jansson/doc/2.11/apiref.html#apiref-pack for more details.
Definition at line 600 of file json.c.
References ast_log, ast_log_backtrace(), ast_strlen_zero, error(), LOG_ERROR, and NULL.
Referenced by ast_json_pack().
 {
    json_error_t error;
    struct ast_json *r = NULL;
    if (format) {
       r = (struct ast_json *)json_vpack_ex(&error, 0, format, ap);
       if (!r && !ast_strlen_zero(error.text)) {
          ast_log(LOG_ERROR,
             "Error building JSON from '%s': %s.\n",
             format, error.text);
          ast_log_backtrace();
       }
    }
    return r;
 }
ast_json_vstringf()
struct ast_json* ast_json_vstringf (const char * format, va_list args)
Create a JSON string, vprintf style.
Since
12.0.0
The formatted value must be a valid ASCII or UTF-8 encoded string.
Parameters
format printf style format string.
Returns
Newly allocated string.
NULL on error.
Definition at line 293 of file json.c.
References ast_free, ast_vasprintf, NULL, and str.
Referenced by ast_ari_response_error(), and ast_json_stringf().
 {
    json_t *ret = NULL;
    if (format) {
       /* json_pack was not introduced until jansson-2.0 so Asterisk could never
        * be compiled against older versions.  The version check can never match
        * anything older than 2.12. */
 #if defined(HAVE_JANSSON_BUNDLED) || JANSSON_MAJOR_VERSION > 2 || JANSSON_MINOR_VERSION > 11
       ret = json_vsprintf(format, args);
 #else
       char *str = NULL;
       int err = ast_vasprintf(&str, format, args);
       if (err >= 0) {
          ret = json_string(str);
          ast_free(str);
       }
 #endif
    }
    return (struct ast_json *)ret;
 }
copy_error()
static void copy_error (struct ast_json_error * error, const json_error_t * jansson_error) static
Copy Jansson error struct to ours.
Definition at line 523 of file json.c.
References ast_copy_string(), ast_json_error::column, ast_json_error::line, ast_json_error::position, ast_json_error::source, and ast_json_error::text.
Referenced by ast_json_load_buf(), ast_json_load_file(), ast_json_load_new_file(), and ast_json_load_string().
 {
    if (error && jansson_error) {
       error->line = jansson_error->line;
       error->column = jansson_error->column;
       error->position = jansson_error->position;
       ast_copy_string(error->text, jansson_error->text, sizeof(error->text));
       ast_copy_string(error->source, jansson_error->source, sizeof(error->source));
    }
 }
dump_flags()
static size_t dump_flags (enum ast_json_encoding_format format) static
Default flags for JSON encoding.
Definition at line 457 of file json.c.
References AST_JSON_PRETTY.
Referenced by ast_json_dump_file_format(), ast_json_dump_new_file_format(), ast_json_dump_str_format(), and ast_json_dump_string_format().
 {
    return format == AST_JSON_PRETTY ?
       JSON_INDENT(2) | JSON_PRESERVE_ORDER : JSON_COMPACT;
 }
json_party_name()
static struct ast_json* json_party_name (struct ast_party_name * name) static
Definition at line 761 of file json.c.
References ast_describe_caller_presentation(), ast_json_pack(), AST_JSON_UTF8_VALIDATE, ast_party_name_charset_describe(), ast_party_name::char_set, NULL, ast_party_name::presentation, ast_party_name::str, and ast_party_name::valid.
Referenced by ast_json_party_id().
 {
    if (!name->valid) {
       return NULL;
    }
    return ast_json_pack("{s: s, s: s, s: i, s: s}",
       "name", AST_JSON_UTF8_VALIDATE(name->str),
       "character_set", ast_party_name_charset_describe(name->char_set),
       "presentation", name->presentation,
       "presentation_txt", ast_describe_caller_presentation(name->presentation));
 }
json_party_number()
static struct ast_json* json_party_number (struct ast_party_number * number) static
Definition at line 749 of file json.c.
References ast_describe_caller_presentation(), ast_json_pack(), AST_JSON_UTF8_VALIDATE, NULL, ast_party_number::plan, ast_party_number::presentation, ast_party_number::str, and ast_party_number::valid.
Referenced by ast_json_party_id().
 {
    if (!number->valid) {
       return NULL;
    }
    return ast_json_pack("{s: s, s: i, s: i, s: s}",
       "number", AST_JSON_UTF8_VALIDATE(number->str),
       "plan", number->plan,
       "presentation", number->presentation,
       "presentation_txt", ast_describe_caller_presentation(number->presentation));
 }
json_party_subaddress()
static struct ast_json* json_party_subaddress (struct ast_party_subaddress * subaddress) static
Definition at line 773 of file json.c.
References ast_json_pack(), AST_JSON_UTF8_VALIDATE, NULL, ast_party_subaddress::odd_even_indicator, ast_party_subaddress::str, ast_party_subaddress::type, and ast_party_subaddress::valid.
Referenced by ast_json_party_id().
 {
    if (!subaddress->valid) {
       return NULL;
    }
    return ast_json_pack("{s: s, s: i, s: b}",
       "subaddress", AST_JSON_UTF8_VALIDATE(subaddress->str),
       "type", subaddress->type,
       "odd", subaddress->odd_even_indicator);
 }
json_payload_destructor()
static void json_payload_destructor (void * obj) static
Definition at line 729 of file json.c.
References ast_json_unref(), and ast_json_payload::json.
Referenced by ast_json_payload_create().
 {
    struct ast_json_payload *payload = obj;
    ast_json_unref(payload->json);
 }
json_utf8_check_first()
static size_t json_utf8_check_first (char byte) static
Definition at line 112 of file json.c.
Referenced by ast_json_utf8_check_len().
 {
    unsigned char ch = (unsigned char) byte;
    if (ch < 0x80) {
       return 1;
    }
    if (0x80 <= ch && ch <= 0xBF) {
       /* second, third or fourth byte of a multi-byte
          sequence, i.e. a "continuation byte" */
       return 0;
    } else if (ch == 0xC0 || ch == 0xC1) {
       /* overlong encoding of an ASCII byte */
       return 0;
    } else if (0xC2 <= ch && ch <= 0xDF) {
       /* 2-byte sequence */
       return 2;
    } else if (0xE0 <= ch && ch <= 0xEF) {
       /* 3-byte sequence */
       return 3;
    } else if (0xF0 <= ch && ch <= 0xF4) {
       /* 4-byte sequence */
       return 4;
    } else { /* ch >= 0xF5 */
       /* Restricted (start of 4-, 5- or 6-byte sequence) or invalid
          UTF-8 */
       return 0;
    }
 }
json_utf8_check_full()
static size_t json_utf8_check_full (const char * str, size_t len) static
Definition at line 144 of file json.c.
References len(), and value.
Referenced by ast_json_utf8_check_len().
 {
    size_t pos;
    int32_t value;
    unsigned char ch = (unsigned char) str[0];
    if (len == 2) {
       value = ch & 0x1F;
    } else if (len == 3) {
       value = ch & 0xF;
    } else if (len == 4) {
       value = ch & 0x7;
    } else {
       return 0;
    }
    for (pos = 1; pos < len; ++pos) {
       ch = (unsigned char) str[pos];
       if (ch < 0x80 || ch > 0xBF) {
          /* not a continuation byte */
          return 0;
       }
       value = (value << 6) + (ch & 0x3F);
    }
    if (value > 0x10FFFF) {
       /* not in Unicode range */
       return 0;
    } else if (0xD800 <= value && value <= 0xDFFF) {
       /* invalid code point (UTF-16 surrogate halves) */
       return 0;
    } else if ((len == 2 && value < 0x80)
       || (len == 3 && value < 0x800)
       || (len == 4 && value < 0x10000)) {
       /* overlong encoding */
       return 0;
    }
    return 1;
 }
parse_error()
static void parse_error (struct ast_json_error * error, const char * text, const char * source) static
Definition at line 535 of file json.c.
References ast_json_error::column, ast_json_error::line, NULL, ast_json_error::position, ast_json_error::source, and ast_json_error::text.
Referenced by ast_json_load_file(), and ast_json_load_string().
 {
    if (error != NULL) {
       error->line = 0;
       error->column = 0;
       error->position = 0;
       strncpy(error->text, text, sizeof(error->text));
       strncpy(error->source, source, sizeof(error->text));
    }
 }
write_to_ast_str()
static int write_to_ast_str (const char * buffer, size_t size, void * data) static
Definition at line 468 of file json.c.
References ast_str_append_substr(), ast_str_make_space, ast_str_size(), and ast_str_strlen().
Referenced by ast_json_dump_str_format().
 {
    struct ast_str **dst = data;
    size_t str_size = ast_str_size(*dst);
    size_t remaining = str_size - ast_str_strlen(*dst);
    int ret;
    /* While ast_str_append will grow the ast_str, it won't report
     * allocation errors. Fortunately, it's not that hard.
     */
    /* Remaining needs to be big enough for buffer, plus null char */
    while (remaining < size + 1) {
       /* doubling the size of the buffer gives us 'amortized
        * constant' time.
        * See http://stackoverflow.com/a/249695/115478 for info.
        */
       str_size *= 2;
       remaining = str_size - ast_str_strlen(*dst);
    }
    ret = ast_str_make_space(dst, str_size);
    if (ret == -1) {
       /* Could not alloc; fail */
       return -1;
    }
    ast_str_append_substr(dst, -1, buffer, size);
    return 0;
 }