Asterisk - The Open Source Telephony Project: datastore.h File Reference
datastore.h File Reference
Asterisk datastore objects.
#include "asterisk/linkedlists.h"
Data Structures
struct ast_datastore
Structure for a data store object.
struct ast_datastore_info
Structure for a data store type.
Macros
#define ast_datastore_alloc(info, uid) __ast_datastore_alloc(info, uid, AST_MODULE_SELF, __FILE__, __LINE__, __PRETTY_FUNCTION__)
Functions
struct ast_datastore * __ast_datastore_alloc (const struct ast_datastore_info *info, const char *uid, struct ast_module *mod, const char *file, int line, const char *function)
Create a data store object.
int ast_datastore_free (struct ast_datastore *datastore)
Free a data store object.
int ast_datastores_add (struct ao2_container *datastores, struct ast_datastore *datastore)
Add a data store to a container.
struct ao2_container * ast_datastores_alloc (void)
Allocate a specialized data stores container.
struct ast_datastore * ast_datastores_alloc_datastore (const struct ast_datastore_info *info, const char *uid)
Allocate a datastore for use with the datastores container.
struct ast_datastore * ast_datastores_find (struct ao2_container *datastores, const char *name)
Find a data store in a container.
void ast_datastores_remove (struct ao2_container *datastores, const char *name)
Remove a data store from a container.
Detailed Description
Asterisk datastore objects.
Definition in file datastore.h.
Macro Definition Documentation
ast_datastore_alloc
#define ast_datastore_alloc (info, uid) __ast_datastore_alloc(info, uid, AST_MODULE_SELF, __FILE__, __LINE__, __PRETTY_FUNCTION__)
Definition at line 89 of file datastore.h.
Referenced by __after_bridge_set_goto(), _macro_exec(), acf_curlopt_write(), acf_iaxvar_write(), acf_odbc_read(), add_features_datastore(), add_masquerade_store(), add_to_agi(), after_bridge_cb_setup(), apply_plc(), ast_cel_fabricate_channel_from_event(), ast_channel_cc_params_init(), ast_channel_datastore_inherit(), ast_channel_suppress(), ast_do_pickup(), ast_iax2_new(), ast_jb_create_framehook(), ast_setup_cc_recall_datastore(), ast_stir_shaken_add_verification(), audiohook_volume_get(), authenticate_reply(), bridge_channel_impart_add(), bridge_features_ds_set_full(), calendar_query_exec(), cc_interfaces_datastore_init(), channel_feature_hooks_set_full(), command_prestart_queue_command(), create_msg_q_chan(), create_parked_subscription_full(), create_transaction(), detect_write(), dial_masquerade_datastore_add(), do_notify(), dtmfstore_exec(), dundi_query_read(), enable_jack_hook(), enum_query_read(), find_or_create_details(), frame_drop_helper(), frame_trace_helper(), func_channel_write_real(), func_confbridge_helper(), get_feature_ds(), get_lock(), get_replace_channel_store(), gosub_exec(), handle_remb_set(), init_hook(), lua_get_state(), max_forwards_datastore_alloc(), msg_datastore_find_or_create(), MYSQL_exec(), pitchshift_helper(), raise_exception(), reload(), save_dialstring(), scramble_write(), set_hold_intercept(), set_internal_datastore(), set_talk_detect(), set_timeout(), setup_async_playback_datastore(), setup_bridge_roles_datastore(), setup_mixmonitor_ds(), setup_park_common_datastore(), shared_write(), smdi_msg_retrieve_read(), socket_process_helper(), speech_create(), speex_write(), srv_datastore_setup(), stasis_app_channel_set_stasis_end_published(), t38_attach_framehook(), and volume_write().
Function Documentation
__ast_datastore_alloc()
struct ast_datastore* __ast_datastore_alloc (const struct ast_datastore_info * info, const char * uid, struct ast_module * mod, const char * file, int line, const char * function)
Create a data store object.
Parameters
[in] info information describing the data store object
[in] uid unique identifer
[in] mod The module to hold until this datastore is freed.
file,line,function
Version
1.6.1 moved here and renamed from ast_channel_datastore_alloc
Definition at line 39 of file datastore.c.
References __ast_calloc(), ast_free, ast_module_ref, ast_strdup, ast_strlen_zero, ast_datastore::info, sip_to_pjsip::info(), ast_datastore::mod, NULL, and ast_datastore::uid.
 {
    struct ast_datastore *datastore = NULL;
    /* Make sure we at least have type so we can identify this */
    if (!info) {
       return NULL;
    }
    datastore = __ast_calloc(1, sizeof(*datastore), file, line, function);
    if (!datastore) {
       return NULL;
    }
    datastore->info = info;
    datastore->mod = mod;
    if (!ast_strlen_zero(uid) && !(datastore->uid = ast_strdup(uid))) {
       ast_free(datastore);
       datastore = NULL;
    }
    ast_module_ref(mod);
    return datastore;
 }
ast_datastore_free()
int ast_datastore_free (struct ast_datastore * datastore)
Free a data store object.
Parameters
[in] datastore datastore to free
Version
1.6.1 moved here and renamed from ast_channel_datastore_free
Definition at line 68 of file datastore.c.
References AO2_STRING_FIELD_CMP_FN(), AO2_STRING_FIELD_HASH_FN(), ast_free, ast_module_unref, ast_datastore::data, ast_datastore_info::destroy, ast_datastore::info, ast_datastore::mod, NULL, and ast_datastore::uid.
Referenced by __after_bridge_set_goto(), acf_curlopt_write(), acf_fetch(), acf_iaxvar_write(), acf_odbc_read(), add_features_datastore(), add_to_agi(), adjust_frame_for_plc(), after_bridge_cb_setup(), apply_plc(), ast_bridge_discard_after_goto(), ast_bridge_setup_after_goto(), ast_cel_fabricate_channel_from_event(), ast_channel_destructor(), ast_channel_unsuppress(), ast_do_pickup(), ast_dummy_channel_destructor(), ast_iax2_new(), ast_jb_create_framehook(), ast_setup_cc_recall_datastore(), audiohook_volume_get(), authenticate_reply(), bridge_channel_impart_add(), bridge_features_ds_set_full(), bridge_timeout(), cc_interfaces_datastore_init(), chan_cleanup(), channel_feature_hooks_set_full(), create_parked_subscription_full(), create_transaction(), detect_write(), dial_masquerade_datastore_add(), dial_masquerade_fixup(), disable_jack_hook(), dtmfstore_exec(), enable_jack_hook(), exec_odbcfinish(), fixup_callback(), frame_drop_helper(), frame_trace_helper(), func_confbridge_helper(), get_lock(), gosub_exec(), init_hook(), lua_get_state(), max_forwards_datastore_alloc(), mixmonitor_ds_remove_and_free(), msg_datastore_find_or_create(), pitchshift_helper(), raise_exception(), remove_detect(), remove_dial_masquerade(), remove_dial_masquerade_caller(), remove_dtmf_store(), remove_hold_intercept(), remove_masquerade_store(), remove_scrambler(), remove_stasis_end_published(), remove_talk_detect(), save_dialstring(), scramble_write(), session_destructor(), set_dial_masquerade(), set_hold_intercept(), set_talk_detect(), setup_async_playback_datastore(), setup_bridge_roles_datastore(), setup_park_common_datastore(), shared_write(), socket_process_helper(), speech_datastore_destroy(), speex_write(), srv_query_read(), stop_mixmonitor_full(), volume_write(), wipe_park_common_datastore(), and wipe_subscription_datastore().
 {
    int res = 0;
    /* Using the destroy function (if present) destroy the data */
    if (datastore->info->destroy != NULL && datastore->data != NULL) {
       datastore->info->destroy(datastore->data);
       datastore->data = NULL;
    }
    /* Free allocated UID memory */
    if (datastore->uid != NULL) {
       ast_free((void *) datastore->uid);
       datastore->uid = NULL;
    }
    ast_module_unref(datastore->mod);
    /* Finally free memory used by ourselves */
    ast_free(datastore);
    return res;
 }
ast_datastores_add()
int ast_datastores_add (struct ao2_container * datastores, struct ast_datastore * datastore)
Add a data store to a container.
Parameters
[in] datastores container to store datastore in
[in] datastore datastore to add
Return values
0 success
-1 failure
Since
14.0.0
Definition at line 101 of file datastore.c.
References ao2_link, ast_assert, ast_strlen_zero, ast_datastore::info, NULL, and ast_datastore::uid.
Referenced by ast_sip_publication_add_datastore(), ast_sip_subscription_add_datastore(), and dialog_info_generate_body_content().
 {
    ast_assert(datastore != NULL);
    ast_assert(datastore->info != NULL);
    ast_assert(!ast_strlen_zero(datastore->uid));
    if (!ao2_link(datastores, datastore)) {
       return -1;
    }
    return 0;
 }
ast_datastores_alloc()
struct ao2_container* ast_datastores_alloc (void)
Allocate a specialized data stores container.
Returns
a container for storing data stores
Since
14.0.0
Definition at line 95 of file datastore.c.
References AO2_ALLOC_OPT_LOCK_MUTEX, ao2_container_alloc_hash, DATASTORE_BUCKETS, and NULL.
Referenced by allocate_subscription(), publisher_start(), and sip_create_publication().
 {
    return ao2_container_alloc_hash(AO2_ALLOC_OPT_LOCK_MUTEX, 0,
       DATASTORE_BUCKETS, ast_datastore_hash_fn, NULL, ast_datastore_cmp_fn);
 }
ast_datastores_alloc_datastore()
struct ast_datastore* ast_datastores_alloc_datastore (const struct ast_datastore_info * info, const char * uid)
Allocate a datastore for use with the datastores container.
Parameters
[in] info information about the datastore
[in] uid unique identifier for the datastore
Return values
non-NULL success
NULL failure
Since
14.0.0
Definition at line 138 of file datastore.c.
References ao2_alloc, ao2_ref, ast_strdup, ast_strlen_zero, ast_uuid_generate_str(), AST_UUID_STR_LEN, datastore_destroy(), ast_datastore::info, sip_to_pjsip::info(), NULL, and ast_datastore::uid.
Referenced by ast_sip_subscription_alloc_datastore(), and dialog_info_generate_body_content().
 {
    struct ast_datastore *datastore;
    char uuid_buf[AST_UUID_STR_LEN];
    const char *uid_ptr = uid;
    if (!info) {
       return NULL;
    }
    datastore = ao2_alloc(sizeof(*datastore), datastore_destroy);
    if (!datastore) {
       return NULL;
    }
    datastore->info = info;
    if (ast_strlen_zero(uid)) {
       /* They didn't provide an ID so we'll provide one ourself */
       uid_ptr = ast_uuid_generate_str(uuid_buf, sizeof(uuid_buf));
    }
    datastore->uid = ast_strdup(uid_ptr);
    if (!datastore->uid) {
       ao2_ref(datastore, -1);
       return NULL;
    }
    return datastore;
 }
ast_datastores_find()
struct ast_datastore* ast_datastores_find (struct ao2_container * datastores, const char * name)
Find a data store in a container.
Parameters
[in] datastores container to find datastore in
[in] name name of the data store to find
Return values
non-NULL success
NULL failure
Since
14.0.0
Definition at line 119 of file datastore.c.
References ao2_find, and OBJ_SEARCH_KEY.
Referenced by ast_sip_publication_get_datastore(), ast_sip_subscription_get_datastore(), and dialog_info_generate_body_content().
 {
    return ao2_find(datastores, name, OBJ_SEARCH_KEY);
 }
ast_datastores_remove()
void ast_datastores_remove (struct ao2_container * datastores, const char * name)
Remove a data store from a container.
Parameters
[in] datastores container to remove datastore from
[in] name name of the data store to remove
Since
14.0.0
Definition at line 114 of file datastore.c.
References ao2_find, OBJ_NODATA, OBJ_SEARCH_KEY, and OBJ_UNLINK.
Referenced by ast_sip_publication_remove_datastore(), and ast_sip_subscription_remove_datastore().
 {
    ao2_find(datastores, name, OBJ_SEARCH_KEY | OBJ_UNLINK | OBJ_NODATA);
 }