Asterisk - The Open Source Telephony Project: SqlConfigParser Class Reference
SqlConfigParser Class Reference
Public Member Functions
def __init__ (self, tablename="sippeers")
def connect (self, user, password, host, port, database)
def read (self, filename, sect=None)
def write (self, config_file)
def write_dicts (self, config_file, mdicts)
Public Member Functions inherited from MultiOrderedConfigParser
def __init__ (self, parent=None)
def add_default (self, key, template_keys=None)
def add_include (self, filename, parser=None)
def add_section (self, key, template_keys=None, mdicts=None)
def default (self, key)
def defaults (self)
def find_value (self, sections, key)
def get (self, section, key)
def get_defaults (self, key)
def get_sections (self, key, attr='_sections', searched=None)
def includes (self)
def multi_get (self, section, key_list)
def read (self, filename, sect=None)
def section (self, key)
def sections (self)
def set (self, section, key, val)
def write (self, config_file)
Data Fields
cnx
Detailed Description
Definition at line 13 of file sqlconfigparser.py.
Constructor & Destructor Documentation
__init__()
def __init__ (self, tablename = "sippeers")
Definition at line 17 of file sqlconfigparser.py.
References SqlConfigParser._tablename.
     def __init__(self,tablename="sippeers"):
         self._tablename=tablename
         MultiOrderedConfigParser.__init__(self)
Member Function Documentation
connect()
def connect (self, user, password, host, port, database)
Definition at line 21 of file sqlconfigparser.py.
     def connect(self, user, password, host, port, database):
         self.cnx = MySQLdb.connect(user=user,passwd=password,host=host,port=int(port),db=database)
read()
def read (self, filename, sect = None)
Definition at line 24 of file sqlconfigparser.py.
References SqlConfigParser._tablename, MultiOrderedConfigParser.add_section(), SqlConfigParser.cnx, and str.
     def read(self, filename, sect=None):
         MultiOrderedConfigParser.read(self, filename, sect)
         # cursor = self.cnx.cursor(dictionary=True)
         cursor = self.cnx.cursor(cursorclass=MySQLdb.cursors.DictCursor)
         cursor.execute("SELECT * from `" + MySQLdb.escape_string(self._tablename) + "`")
         rows = cursor.fetchall()
         for row in rows:
             sect = self.add_section(row['name'])
             for key in row:
                 if (row[key] != None):
                     for elem in str(row[key]).split(";"):
                         sect[key] = elem
                     #sect[key] = str(row[key]).split(";")
write()
def write (self, config_file)
Write configuration information out to a file
Definition at line 67 of file sqlconfigparser.py.
References MultiOrderedConfigParser._sections, and SqlConfigParser.write_dicts().
     def write(self, config_file):
         """Write configuration information out to a file"""
         try:
             self.write_dicts(config_file, self._sections)
         except:
                 print("Could not open file " + config_file + " for writing")
                 traceback.print_exc()
write_dicts()
def write_dicts (self, config_file, mdicts)
Write the contents of the mdicts to the specified config file
Definition at line 39 of file sqlconfigparser.py.
Referenced by SqlConfigParser.write().
     def write_dicts(self, config_file, mdicts):
         """Write the contents of the mdicts to the specified config file"""
         for section, sect_list in mdicts.iteritems():
             # every section contains a list of dictionaries
             for sect in sect_list:
                 sql = "INSERT INTO "
                 if (sect.get('type')[0] == "endpoint"):
                     sql += "ps_endpoints "
                 elif (sect.get('type')[0] == "aor" and section != "sbc"):
                     sql += "ps_aors "
                 elif (sect.get('type')[0] == "identify"):
                     sql += "ps_endpoint_id_ips"
                 else:
                     continue
                 sql += " SET `id` = " + "\"" + MySQLdb.escape_string(section) + "\""
                 for key, val_list in sect.iteritems():
                     if key == "type":
                         continue
                     # every value is also a list
                     key_val = " `" + key + "`"
                     key_val += " = " + "\"" + MySQLdb.escape_string(";".join(val_list)) + "\""
                     sql += ","
                     sql += key_val
                 config_file.write("%s;\n" % (sql))
Field Documentation
cnx
cnx
Definition at line 22 of file sqlconfigparser.py.
Referenced by SqlConfigParser.read().
The documentation for this class was generated from the following file:
sqlconfigparser.py