Asterisk - The Open Source Telephony Project: res_pjsip_outbound_authenticator_digest.c File Reference
res_pjsip_outbound_authenticator_digest.c File Reference
#include "asterisk.h"
#include <pjsip.h>
#include "asterisk/res_pjsip.h"
#include "asterisk/logger.h"
#include "asterisk/module.h"
#include "asterisk/strings.h"
#include "asterisk/vector.h"
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int digest_create_request_with_auth (const struct ast_sip_auth_vector *auth_ids_vector, pjsip_rx_data *challenge, pjsip_tx_data *old_request, pjsip_tx_data **new_request)
static pjsip_hdr_e get_auth_search_type (pjsip_rx_data *challenge)
static int is_digest_algorithm_supported (pjsip_www_authenticate_hdr *auth_hdr)
static int load_module (void)
static pj_status_t set_outbound_authentication_credentials (pjsip_auth_clt_sess *auth_sess, const struct ast_sip_auth_objects_vector *auth_objects_vector, pjsip_rx_data *challenge, struct ast_str **realms)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "PJSIP authentication resource" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_CHANNEL_DEPEND, .requires = "res_pjsip", }
static const struct ast_module_info * ast_module_info = &__mod_info
static struct ast_sip_outbound_authenticator digest_authenticator
pj_str_t supported_digest_algorithms []
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 601 of file res_pjsip_outbound_authenticator_digest.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 601 of file res_pjsip_outbound_authenticator_digest.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 601 of file res_pjsip_outbound_authenticator_digest.c.
digest_create_request_with_auth()
static int digest_create_request_with_auth (const struct ast_sip_auth_vector * auth_ids_vector, pjsip_rx_data * challenge, pjsip_tx_data * old_request, pjsip_tx_data ** new_request) static
Definition at line 410 of file res_pjsip_outbound_authenticator_digest.c.
References ao2_cleanup, ast_alloca, ast_assert, ast_free, ast_log, ast_sip_cleanup_auth_objects_vector, ast_sip_dialog_get_endpoint(), ast_sip_get_pjsip_endpoint(), ast_sip_retrieve_auths_vector(), AST_SOCKADDR_BUFLEN, ast_sorcery_object_get_id(), ast_str_buffer(), ast_str_create, ast_strdupa, AST_VECTOR_FREE, AST_VECTOR_INIT, AST_VECTOR_SIZE, cleanup(), LOG_ERROR, LOG_WARNING, NULL, set_outbound_authentication_credentials(), and status.
 {
    pjsip_auth_clt_sess auth_sess;
    pjsip_cseq_hdr *cseq;
    pj_status_t status;
    struct ast_sip_auth_objects_vector auth_objects_vector;
    size_t auth_object_count = 0;
    struct ast_sip_endpoint *endpoint;
    char *id = NULL;
    const char *id_type;
    struct ast_str *realms = NULL;
    pjsip_dialog *dlg;
    int res = -1;
    /*
     * Some older compilers have an issue with initializing structures with
     * pjsip_auth_clt_sess auth_sess = { 0, };
     * so we'll just do it the old fashioned way.
     */
    memset(&auth_sess, 0, sizeof(auth_sess));
    dlg = pjsip_rdata_get_dlg(challenge);
    if (dlg) {
       /* The only thing we use endpoint for is to get an id for error/debug messages */
       endpoint = ast_sip_dialog_get_endpoint(dlg);
       id = endpoint ? ast_strdupa(ast_sorcery_object_get_id(endpoint)) : NULL;
       ao2_cleanup(endpoint);
       id_type = "Endpoint";
    }
    /* If there was no dialog, then this is probably a REGISTER so no endpoint */
    if (!id) {
       /* The only thing we use the address for is to get an id for error/debug messages */
       id = ast_alloca(AST_SOCKADDR_BUFLEN);
       pj_sockaddr_print(&challenge->pkt_info.src_addr, id, AST_SOCKADDR_BUFLEN, 3);
       id_type = "Host";
    }
    if (!auth_ids_vector || AST_VECTOR_SIZE(auth_ids_vector) == 0) {
       ast_log(LOG_ERROR, "%s: '%s': There were no auth ids available\n", id_type, id);
       return -1;
    }
    if (AST_VECTOR_INIT(&auth_objects_vector, AST_VECTOR_SIZE(auth_ids_vector)) != 0) {
       ast_log(LOG_ERROR, "%s: '%s': Couldn't initialize auth object vector\n", id_type, id);
       return -1;
    }
    /*
     * We don't really care about ast_sip_retrieve_auths_vector()'s return code
     * because we're checking the count of objects in the vector.
     *
     * Don't forget to call
     *    ast_sip_cleanup_auth_objects_vector(&auth_objects_vector);
     *  AST_VECTOR_FREE(&auth_objects_vector);
     * when you're done with the vector
     */
    ast_sip_retrieve_auths_vector(auth_ids_vector, &auth_objects_vector);
    auth_object_count = AST_VECTOR_SIZE(&auth_objects_vector);
    if (auth_object_count == 0) {
       /*
        * If none of the auth ids were found, we can't continue.
        * We're OK if there's at least one left.
        * ast_sip_retrieve_auths_vector() will print a warning for every
        * id that wasn't found.
        */
       res = -1;
       goto cleanup;
    }
    if (pjsip_auth_clt_init(&auth_sess, ast_sip_get_pjsip_endpoint(),
             old_request->pool, 0) != PJ_SUCCESS) {
       ast_log(LOG_ERROR, "%s: '%s': Failed to initialize client authentication session\n",
          id_type, id);
       res = -1;
       goto cleanup;
    }
    /*
     * realms is used only for displaying good error messages.
     */
    realms = ast_str_create(32);
    if (!realms) {
       res = -1;
       goto cleanup;
    }
    /*
     * Load pjproject with the valid credentials for the Authentication headers
     * received on the 401 or 407 response.
     */
    status = set_outbound_authentication_credentials(&auth_sess, &auth_objects_vector, challenge, &realms);
    switch (status) {
    case PJ_SUCCESS:
       break;
    case PJSIP_ENOCREDENTIAL:
       ast_log(LOG_WARNING,
          "%s: '%s': No auth objects matching realm(s) '%s' from challenge found.\n", id_type, id,
          realms ? ast_str_buffer(realms) : "<none>");
       res = -1;
       goto cleanup;
    default:
       ast_log(LOG_WARNING, "%s: '%s': Failed to set authentication credentials\n", id_type, id);
       res = -1;
       goto cleanup;
    }
    /*
     * reinit_req actually creates the Authorization headers to send on
     * the next request.  If reinit_req already has a cached credential
     * from an earlier successful authorization, it'll use it. Otherwise
     * it'll create a new authorization and cache it.
     */
    status = pjsip_auth_clt_reinit_req(&auth_sess, challenge, old_request, new_request);
    switch (status) {
    case PJ_SUCCESS:
       /* PJSIP creates a new transaction for new_request (meaning it creates a new
        * branch). However, it recycles the Call-ID, from-tag, and CSeq from the
        * original request. Some SIP implementations will not process the new request
        * since the CSeq is the same as the original request. Incrementing it here
        * fixes the interop issue
        */
       cseq = pjsip_msg_find_hdr((*new_request)->msg, PJSIP_H_CSEQ, NULL);
       ast_assert(cseq != NULL);
       ++cseq->cseq;
       res = 0;
       goto cleanup;
    case PJSIP_ENOCREDENTIAL:
       /*
        * This should be rare since set_outbound_authentication_credentials()
        * did the matching but you never know.
        */
       ast_log(LOG_WARNING,
          "%s: '%s': No auth objects matching realm(s) '%s' from challenge found.\n", id_type, id,
          realms ? ast_str_buffer(realms) : "<none>");
       break;
    case PJSIP_EAUTHSTALECOUNT:
       ast_log(LOG_WARNING,
          "%s: '%s': Unable to create request with auth.  Number of stale retries exceeded.\n",
          id_type, id);
       break;
    case PJSIP_EFAILEDCREDENTIAL:
       ast_log(LOG_WARNING, "%s: '%s': Authentication credentials not accepted by server.\n",
          id_type, id);
       break;
    default:
       ast_log(LOG_WARNING, "%s: '%s': Unable to create request with auth. Unknown failure.\n",
          id_type, id);
       break;
    }
    res = -1;
 cleanup:
 #if defined(HAVE_PJSIP_AUTH_CLT_DEINIT)
    /* Release any cached auths */
    pjsip_auth_clt_deinit(&auth_sess);
 #endif
    ast_sip_cleanup_auth_objects_vector(&auth_objects_vector);
    AST_VECTOR_FREE(&auth_objects_vector);
    ast_free(realms);
    return res;
 }
get_auth_search_type()
static pjsip_hdr_e get_auth_search_type (pjsip_rx_data * challenge) static
Definition at line 46 of file res_pjsip_outbound_authenticator_digest.c.
References ast_log, and LOG_ERROR.
Referenced by set_outbound_authentication_credentials().
 {
    if (challenge->msg_info.msg->line.status.code == PJSIP_SC_UNAUTHORIZED) {
       return PJSIP_H_WWW_AUTHENTICATE;
    } else if (challenge->msg_info.msg->line.status.code == PJSIP_SC_PROXY_AUTHENTICATION_REQUIRED) {
       return PJSIP_H_PROXY_AUTHENTICATE;
    } else {
       ast_log(LOG_ERROR,
             "Status code %d was received when it should have been 401 or 407.\n",
             challenge->msg_info.msg->line.status.code);
       return PJSIP_H_OTHER;
    }
 }
is_digest_algorithm_supported()
static int is_digest_algorithm_supported (pjsip_www_authenticate_hdr * auth_hdr) static
Definition at line 68 of file res_pjsip_outbound_authenticator_digest.c.
References ARRAY_LEN, and supported_digest_algorithms.
Referenced by set_outbound_authentication_credentials().
 {
    int digest;
    /* An empty digest is assumed to be md5 */
    if (pj_strlen(&auth_hdr->challenge.digest.algorithm) == 0) {
       return 1;
    }
    for (digest = 0; digest < ARRAY_LEN(supported_digest_algorithms); digest++) {
       if (pj_stricmp(&auth_hdr->challenge.digest.algorithm, &supported_digest_algorithms[digest]) == 0) {
          return 1;
       }
    }
    return 0;
 }
load_module()
static int load_module (void) static
Definition at line 581 of file res_pjsip_outbound_authenticator_digest.c.
References AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, and ast_sip_register_outbound_authenticator().
Referenced by unload_module().
 {
    if (ast_sip_register_outbound_authenticator(&digest_authenticator)) {
       return AST_MODULE_LOAD_DECLINE;
    }
    return AST_MODULE_LOAD_SUCCESS;
 }
set_outbound_authentication_credentials()
static pj_status_t set_outbound_authentication_credentials (pjsip_auth_clt_sess * auth_sess, const struct ast_sip_auth_objects_vector * auth_objects_vector, pjsip_rx_data * challenge, struct ast_str ** realms) static
Definition at line 127 of file res_pjsip_outbound_authenticator_digest.c.
References ast_debug, ast_free, ast_log, AST_SIP_AUTH_TYPE_ARTIFICIAL, AST_SIP_AUTH_TYPE_GOOGLE_OAUTH, AST_SIP_AUTH_TYPE_MD5, AST_SIP_AUTH_TYPE_USER_PASS, ast_sorcery_object_get_id(), ast_str_append(), ast_str_strlen(), ast_str_truncate(), ast_strings_equal(), ast_strlen_zero, AST_VECTOR, AST_VECTOR_APPEND, AST_VECTOR_FREE, AST_VECTOR_GET, AST_VECTOR_INIT, AST_VECTOR_SIZE, AST_VECTOR_STEAL_ELEMENTS, ast_sip_auth::auth_pass, ast_sip_auth::auth_user, cleanup(), get_auth_search_type(), is_digest_algorithm_supported(), LOG_ERROR, ast_sip_auth::md5_creds, NULL, ast_sip_auth::realm, and ast_sip_auth::type.
Referenced by digest_create_request_with_auth().
 {
    int i;
    size_t auth_object_count;
    pjsip_www_authenticate_hdr *auth_hdr = NULL;
    pj_status_t res = PJ_SUCCESS;
    pjsip_hdr_e search_type;
    size_t cred_count;
    pjsip_cred_info *creds_array;
    /*
     * Normally vector elements are pointers to something else, usually
     * structures. In this case however, the elements are the
     * structures themselves instead of pointers to them.  This is due
     * to the fact that pjsip_auth_clt_set_credentials() expects an
     * array of structues, not an array of pointers to structures.
     * Thankfully, vectors allow you to "steal" their underlying
     * arrays, in this case an array of pjsip_cred_info structures,
     * which we'll pass to pjsip_auth_clt_set_credentials() at the
     * end.
     */
    AST_VECTOR(cred_info, pjsip_cred_info) auth_creds;
    search_type = get_auth_search_type(challenge);
    if (search_type == PJSIP_H_OTHER) {
       /*
        * The status code on the response wasn't 401 or 407
        * so there are no WWW-Authenticate or Proxy-Authenticate
        * headers to process.
        */
       return PJ_ENOTSUP;
    }
    auth_object_count = AST_VECTOR_SIZE(auth_objects_vector);
    if (auth_object_count == 0) {
       /* This shouldn't happen but we'll check anyway. */
       return PJ_EINVAL;
    }
    /*
     * The number of pjsip_cred_infos we send to pjproject can
     * vary based on the number of acceptable headers received
     * and the number of acceptable auth objects on the endpoint
     * so we just use a vector to accumulate them.
     *
     * NOTE: You have to call AST_VECTOR_FREE() on the vector
     * but you don't have to free the elements because they're
     * actual structures, not pointers to structures.
     */
    if (AST_VECTOR_INIT(&auth_creds, 5) != 0) {
       return PJ_ENOMEM;
    }
    /*
     * It's going to be rare that we actually have more than one
     * WWW-Authentication header or more than one auth object to
     * match to it so the following nested loop should be fine.
     */
    while ((auth_hdr = pjsip_msg_find_hdr(challenge->msg_info.msg,
       search_type, auth_hdr ? auth_hdr->next : NULL))) {
       int exact_match_index = -1;
       int wildcard_match_index = -1;
       int match_index = 0;
       pjsip_cred_info auth_cred;
       struct ast_sip_auth *auth = NULL;
       memset(&auth_cred, 0, sizeof(auth_cred));
       /*
        * Since we only support the MD5 algorithm at the current time,
        * there's no sense searching for auth objects that match the algorithm.
        * In fact, the auth_object structure doesn't even have a member
        * for it.
        *
        * When we do support more algorithms, this check will need to be
        * moved inside the auth object loop below.
        *
        * Note: The header may not have specified an algorithm at all in which
        * case it's assumed to be MD5. is_digest_algorithm_supported() returns
        * true for that case.
        */
       if (!is_digest_algorithm_supported(auth_hdr)) {
          ast_debug(3, "Skipping header with realm '%.*s' and unsupported '%.*s' algorithm \n",
             (int)auth_hdr->challenge.digest.realm.slen, auth_hdr->challenge.digest.realm.ptr,
             (int)auth_hdr->challenge.digest.algorithm.slen, auth_hdr->challenge.digest.algorithm.ptr);
          continue;
       }
       /*
        * Appending the realms is strictly so digest_create_request_with_auth()
        * can display good error messages.  Since we only support one algorithm,
        * there can't be more than one header with the same realm.  No need to worry
        * about duplicate realms until then.
        */
       if (*realms) {
          ast_str_append(realms, 0, "%.*s, ",
             (int)auth_hdr->challenge.digest.realm.slen, auth_hdr->challenge.digest.realm.ptr);
       }
       ast_debug(3, "Searching auths to find matching ones for header with realm '%.*s' and algorithm '%.*s'\n",
          (int)auth_hdr->challenge.digest.realm.slen, auth_hdr->challenge.digest.realm.ptr,
          (int)auth_hdr->challenge.digest.algorithm.slen, auth_hdr->challenge.digest.algorithm.ptr);
       /*
        * Now that we have a valid header, we can loop over the auths available to
        * find either an exact realm match or, failing that, a wildcard auth (an
        * auth with an empty or "*" realm).
        *
        * NOTE: We never use the global default realm when we're the UAC responding
        * to a 401 or 407.  We only use that when we're the UAS (handled elsewhere)
        * and the auth object didn't have a realm.
        */
       for (i = 0; i < auth_object_count; ++i) {
          auth = AST_VECTOR_GET(auth_objects_vector, i);
          /*
           * If this auth object's realm exactly matches the one
           * from the header, we can just break out and use it.
           *
           * NOTE: If there's more than one auth object for an endpoint with
           * a matching realm it's a misconfiguration.  We'll only use the first.
           */
          if (pj_stricmp2(&auth_hdr->challenge.digest.realm, auth->realm) == 0) {
             ast_debug(3, "Found matching auth '%s' with realm '%s'\n", ast_sorcery_object_get_id(auth),
                auth->realm);
             exact_match_index = i;
             /*
              * If we found an exact realm match, there's no need to keep
              * looking for a wildcard.
              */
             break;
          }
          /*
           * If this auth object's realm is empty or a "*", it's a wildcard
           * auth object.  We going to save its index but keep iterating over
           * the vector in case we find an exact match later.
           *
           * NOTE: If there's more than one wildcard auth object for an endpoint
           * it's a misconfiguration.  We'll only use the first.
           */
          if (wildcard_match_index < 0
             && (ast_strlen_zero(auth->realm) || ast_strings_equal(auth->realm, "*"))) {
             ast_debug(3, "Found wildcard auth '%s' for realm '%.*s'\n", ast_sorcery_object_get_id(auth),
                (int)auth_hdr->challenge.digest.realm.slen, auth_hdr->challenge.digest.realm.ptr);
             wildcard_match_index = i;
          }
       }
       if (exact_match_index < 0 && wildcard_match_index < 0) {
          /*
           * Didn't find either a wildcard or an exact realm match.
           * Move on to the next header.
           */
          ast_debug(3, "No auth matching realm or no wildcard found for realm '%.*s'\n",
             (int)auth_hdr->challenge.digest.realm.slen, auth_hdr->challenge.digest.realm.ptr);
          continue;
       }
       if (exact_match_index >= 0) {
          /*
           * If we found an exact match, we'll always prefer that.
           */
          match_index = exact_match_index;
          auth = AST_VECTOR_GET(auth_objects_vector, match_index);
          ast_debug(3, "Using matched auth '%s' with realm '%.*s'\n", ast_sorcery_object_get_id(auth),
             (int)auth_hdr->challenge.digest.realm.slen, auth_hdr->challenge.digest.realm.ptr);
       } else {
          /*
           * We'll only use the wildcard if we didn't find an exact match.
           */
          match_index = wildcard_match_index;
          auth = AST_VECTOR_GET(auth_objects_vector, match_index);
          ast_debug(3, "Using wildcard auth '%s' for realm '%.*s'\n", ast_sorcery_object_get_id(auth),
             (int)auth_hdr->challenge.digest.realm.slen, auth_hdr->challenge.digest.realm.ptr);
       }
       /*
        * Copy the fields from the auth_object to the
        * pjsip_cred_info structure.
        */
       auth_cred.realm = auth_hdr->challenge.common.realm;
       pj_cstr(&auth_cred.username, auth->auth_user);
       pj_cstr(&auth_cred.scheme, "digest");
       switch (auth->type) {
       case AST_SIP_AUTH_TYPE_USER_PASS:
          pj_cstr(&auth_cred.data, auth->auth_pass);
          auth_cred.data_type = PJSIP_CRED_DATA_PLAIN_PASSWD;
          break;
       case AST_SIP_AUTH_TYPE_MD5:
          pj_cstr(&auth_cred.data, auth->md5_creds);
          auth_cred.data_type = PJSIP_CRED_DATA_DIGEST;
          break;
       case AST_SIP_AUTH_TYPE_GOOGLE_OAUTH:
          /* nothing to do. handled seperately in res_pjsip_outbound_registration */
          break;
       case AST_SIP_AUTH_TYPE_ARTIFICIAL:
          ast_log(LOG_ERROR,
             "Trying to set artificial outbound auth credentials shouldn't happen.\n");
          continue;
       } /* End auth object loop */
       /*
        * Because the vector contains actual structures and not pointers
        * to structures, the call to AST_VECTOR_APPEND results in a simple
        * assign of one structure to another, effectively copying the auth_cred
        * structure contents to the array element.
        *
        * Also note that the calls to pj_cstr above set their respective
        * auth_cred fields to the _pointers_ of their corresponding auth
        * object fields.  This is safe because the call to
        * pjsip_auth_clt_set_credentials() below strdups them before we
        * return to the calling function which decrements the reference
        * counts.
        */
       res = AST_VECTOR_APPEND(&auth_creds, auth_cred);
       if (res != PJ_SUCCESS) {
          res = PJ_ENOMEM;
          goto cleanup;
       }
    } /* End header loop */
    if (*realms && ast_str_strlen(*realms)) {
       /*
        * Again, this is strictly so digest_create_request_with_auth()
        * can display good error messages.
        *
        * Chop off the trailing ", " on the last realm.
        */
       ast_str_truncate(*realms, ast_str_strlen(*realms) - 2);
    }
    if (AST_VECTOR_SIZE(&auth_creds) == 0) {
       /* No matching auth objects were found. */
       res = PJSIP_ENOCREDENTIAL;
       goto cleanup;
    }
    /*
     * Here's where we steal the cred info structures from the vector.
     *
     * The steal effectively returns a pointer to the underlying
     * array of pjsip_cred_info structures which is exactly what we need
     * to pass to pjsip_auth_clt_set_credentials().
     *
     * <struct cred info><struct cred info>...<struct cred info>
     * ^pointer
     *
     * Since we stole the array from the vector, we have to free it ourselves.
     *
     * We also have to copy the size before we steal because stealing
     * resets the vector size to 0.
     */
    cred_count = AST_VECTOR_SIZE(&auth_creds);
    creds_array = AST_VECTOR_STEAL_ELEMENTS(&auth_creds);
    res = pjsip_auth_clt_set_credentials(auth_sess, cred_count, creds_array);
    ast_free(creds_array);
    if (res == PJ_SUCCESS) {
       ast_debug(3, "Set %"PRIu64" credentials in auth session\n", cred_count);
    } else {
       ast_log(LOG_ERROR, "Failed to set %"PRIu64" credentials in auth session\n", cred_count);
    }
 cleanup:
    AST_VECTOR_FREE(&auth_creds);
    return res;
 }
unload_module()
static int unload_module (void) static
Definition at line 589 of file res_pjsip_outbound_authenticator_digest.c.
References AST_MODFLAG_LOAD_ORDER, AST_MODPRI_CHANNEL_DEPEND, AST_MODULE_INFO(), AST_MODULE_SUPPORT_CORE, ast_sip_unregister_outbound_authenticator(), ASTERISK_GPL_KEY, and load_module().
 {
    ast_sip_unregister_outbound_authenticator(&digest_authenticator);
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "PJSIP authentication resource" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_CHANNEL_DEPEND, .requires = "res_pjsip", } static
Definition at line 601 of file res_pjsip_outbound_authenticator_digest.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 601 of file res_pjsip_outbound_authenticator_digest.c.
digest_authenticator
struct ast_sip_outbound_authenticator digest_authenticator static
Initial value:
= {
   .create_request_with_auth = digest_create_request_with_auth,
}
Definition at line 577 of file res_pjsip_outbound_authenticator_digest.c.
supported_digest_algorithms
pj_str_t supported_digest_algorithms[]
Initial value:
= {
   { "MD5", 3}
}
Definition at line 35 of file res_pjsip_outbound_authenticator_digest.c.
Referenced by is_digest_algorithm_supported().