Asterisk - The Open Source Telephony Project: func_sorcery.c File Reference
func_sorcery.c File Reference
Module: Dial plan functions
Get a field from a sorcery object.
#include "asterisk.h"
#include "asterisk/app.h"
#include "asterisk/pbx.h"
#include "asterisk/module.h"
#include "asterisk/sorcery.h"
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int load_module (void)
static int sorcery_function_read (struct ast_channel *chan, const char *cmd, char *data, struct ast_str **buf, ssize_t len)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Get a field from a sorcery object" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, }
static const struct ast_module_info * ast_module_info = &__mod_info
static struct ast_custom_function sorcery_function
Detailed Description
Get a field from a sorcery object.
Author
George Joseph <george.joseph@fairview5.com>
Definition in file func_sorcery.c.
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 218 of file func_sorcery.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 218 of file func_sorcery.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 218 of file func_sorcery.c.
load_module()
static int load_module (void) static
Definition at line 213 of file func_sorcery.c.
References ast_custom_function_register.
 {
    return ast_custom_function_register(&sorcery_function);
 }
sorcery_function_read()
static int sorcery_function_read (struct ast_channel * chan, const char * cmd, char * data, struct ast_str ** buf, ssize_t len) static
Definition at line 79 of file func_sorcery.c.
References ao2_cleanup, args, AST_APP_ARG, AST_DECLARE_APP_ARGS, ast_log, AST_LOG_ERROR, ast_sorcery_objectset_create, ast_sorcery_retrieve_by_id(), ast_sorcery_retrieve_by_module_name(), ast_sorcery_unref, AST_STANDARD_APP_ARGS, ast_str_append(), ast_str_set(), ast_str_truncate(), ast_strdupa, ast_strlen_zero, ast_variables_destroy(), method, methods, ast_variable::name, ast_variable::next, NULL, RAII_VAR, sorcery, and ast_variable::value.
 {
    char *parsed_data = ast_strdupa(data);
    RAII_VAR(struct ast_sorcery *, sorcery, NULL, ast_sorcery_unref);
    RAII_VAR(void *, sorcery_obj, NULL, ao2_cleanup);
    struct ast_variable *change_set;
    struct ast_variable *it_change_set;
    int found, field_number = 1, ix, method;
    char *separator = ",";
    enum methods {
       CONCAT,
       SINGLE,
    };
    AST_DECLARE_APP_ARGS(args,
       AST_APP_ARG(module_name);
       AST_APP_ARG(object_type);
       AST_APP_ARG(object_id);
       AST_APP_ARG(field_name);
       AST_APP_ARG(method);
       AST_APP_ARG(method_arg);
    );
    /* Check for zero arguments */
    if (ast_strlen_zero(parsed_data)) {
       ast_log(AST_LOG_ERROR, "Cannot call %s without arguments\n", cmd);
       return -1;
    }
    AST_STANDARD_APP_ARGS(args, parsed_data);
    if (ast_strlen_zero(args.module_name)) {
       ast_log(AST_LOG_ERROR, "Cannot call %s without a module name to query\n", cmd);
       return -1;
    }
    if (ast_strlen_zero(args.object_type)) {
       ast_log(AST_LOG_ERROR, "Cannot call %s with an empty object type\n", cmd);
       return -1;
    }
    if (ast_strlen_zero(args.object_id)) {
       ast_log(AST_LOG_ERROR, "Cannot call %s with an empty object name\n", cmd);
       return -1;
    }
    if (ast_strlen_zero(args.field_name)) {
       ast_log(AST_LOG_ERROR, "Cannot call %s with an empty field name\n", cmd);
       return -1;
    }
    if (ast_strlen_zero(args.method)) {
       method = CONCAT;
    } else {
       if (strcmp(args.method, "concat") == 0) {
          method = CONCAT;
          if (ast_strlen_zero(args.method_arg)) {
             separator = ",";
          } else {
             separator = args.method_arg;
          }
       } else if (strcmp(args.method, "single") == 0) {
          method = SINGLE;
          if (!ast_strlen_zero(args.method_arg)) {
             if (sscanf(args.method_arg, "%30d", &field_number) <= 0 || field_number <= 0 ) {
                ast_log(AST_LOG_ERROR, "occurrence_number must be a positive integer\n");
                return -1;
             }
          }
       } else {
          ast_log(AST_LOG_ERROR, "Retrieval method must be 'concat' or 'single'\n");
          return -1;
       }
    }
    sorcery = ast_sorcery_retrieve_by_module_name(args.module_name);
    if (!sorcery) {
       ast_log(AST_LOG_ERROR, "Failed to retrieve sorcery instance for module %s\n", args.module_name);
       return -1;
    }
    sorcery_obj = ast_sorcery_retrieve_by_id(sorcery, args.object_type, args.object_id);
    if (!sorcery_obj) {
       return -1;
    }
    change_set = ast_sorcery_objectset_create(sorcery, sorcery_obj);
    if (!change_set) {
       return -1;
    }
    ix=1;
    found = 0;
    for (it_change_set = change_set; it_change_set; it_change_set = it_change_set->next) {
       if (method == CONCAT && strcmp(it_change_set->name, args.field_name) == 0) {
          ast_str_append(buf, 0, "%s%s", it_change_set->value, separator);
          found = 1;
          continue;
       }
       if (method == SINGLE && strcmp(it_change_set->name, args.field_name) == 0  && ix++ == field_number) {
          ast_str_set(buf, len, "%s", it_change_set->value);
          found = 1;
          break;
       }
    }
    ast_variables_destroy(change_set);
    if (!found) {
       return -1;
    }
    if (method == CONCAT) {
       ast_str_truncate(*buf, -1);
    }
    return 0;
 }
unload_module()
static int unload_module (void) static
Definition at line 208 of file func_sorcery.c.
References ast_custom_function_unregister().
 {
    return ast_custom_function_unregister(&sorcery_function);
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Get a field from a sorcery object" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, } static
Definition at line 218 of file func_sorcery.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 218 of file func_sorcery.c.
sorcery_function
struct ast_custom_function sorcery_function static
Initial value:
= {
   .name = "AST_SORCERY",
   .read2 = sorcery_function_read,
}
Definition at line 203 of file func_sorcery.c.