Asterisk - The Open Source Telephony Project: cdr_odbc.c File Reference
cdr_odbc.c File Reference
Module: CDR Drivers
ODBC CDR Backend.
#include "asterisk.h"
#include "asterisk/config.h"
#include "asterisk/channel.h"
#include "asterisk/cdr.h"
#include "asterisk/module.h"
#include "asterisk/res_odbc.h"
Macros
#define DATE_FORMAT "%Y-%m-%d %T"
Enumerations
enum {
CONFIG_LOGUNIQUEID = 1 << 0, CONFIG_USEGMTIME = 1 << 1, CONFIG_DISPOSITIONSTRING = 1 << 2, CONFIG_HRTIME = 1 << 3,
CONFIG_REGISTERED = 1 << 4, CONFIG_NEWCDRCOLUMNS = 1 << 5
}
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static SQLHSTMT execute_cb (struct odbc_obj *obj, void *data)
static int load_module (void)
static int odbc_load_module (int reload)
static int odbc_log (struct ast_cdr *cdr)
static int reload (void)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "ODBC CDR Backend" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_EXTENDED, .load = load_module, .unload = unload_module, .reload = reload, .load_pri = AST_MODPRI_CDR_DRIVER, .requires = "cdr,res_odbc", }
static const struct ast_module_info * ast_module_info = &__mod_info
static struct ast_flags config = { 0 }
static const char config_file [] = "cdr_odbc.conf"
static char * dsn = NULL
static const char name [] = "ODBC"
static char * table = NULL
Detailed Description
ODBC CDR Backend.
Author
Brian K. West brian.nosp@m.@bkw.nosp@m..org
See also:
http://www.unixodbc.org
Config_cdr
Definition in file cdr_odbc.c.
Macro Definition Documentation
DATE_FORMAT
#define DATE_FORMAT "%Y-%m-%d %T"
Definition at line 54 of file cdr_odbc.c.
Referenced by execute_cb().
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
CONFIG_LOGUNIQUEID
CONFIG_USEGMTIME
CONFIG_DISPOSITIONSTRING
CONFIG_HRTIME
CONFIG_REGISTERED
CONFIG_NEWCDRCOLUMNS
Definition at line 60 of file cdr_odbc.c.
      {
    CONFIG_LOGUNIQUEID =       1 << 0,
    CONFIG_USEGMTIME =         1 << 1,
    CONFIG_DISPOSITIONSTRING = 1 << 2,
    CONFIG_HRTIME =            1 << 3,
    CONFIG_REGISTERED =        1 << 4,
    CONFIG_NEWCDRCOLUMNS =     1 << 5,
 };
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 332 of file cdr_odbc.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 332 of file cdr_odbc.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 332 of file cdr_odbc.c.
execute_cb()
static SQLHSTMT execute_cb (struct odbc_obj * obj, void * data) static
Definition at line 71 of file cdr_odbc.c.
References ast_cdr::accountcode, ast_cdr::amaflags, ast_cdr::answer, ast_cdr_disp2str(), ast_localtime(), ast_log, ast_odbc_execute_sql(), ast_strdupa, ast_strftime(), ast_test_flag, ast_tvdiff_us(), ast_tvzero(), ast_cdr::billsec, ast_cdr::channel, ast_cdr::clid, odbc_obj::con, CONFIG_DISPOSITIONSTRING, CONFIG_HRTIME, CONFIG_LOGUNIQUEID, CONFIG_NEWCDRCOLUMNS, CONFIG_USEGMTIME, DATE_FORMAT, ast_cdr::dcontext, ast_cdr::disposition, ast_cdr::dst, ast_cdr::dstchannel, ast_cdr::duration, ast_cdr::end, ast_cdr::lastapp, ast_cdr::lastdata, ast_cdr::linkedid, LOG_WARNING, NULL, ast_cdr::peeraccount, ast_cdr::sequence, ast_cdr::src, ast_cdr::start, table, ast_cdr::uniqueid, and ast_cdr::userfield.
Referenced by odbc_log().
 {
    struct ast_cdr *cdr = data;
    SQLRETURN ODBC_res;
    char sqlcmd[2048] = "", timestr[128], new_columns[120] = "", new_values[7] = "";
    struct ast_tm tm;
    SQLHSTMT stmt;
    int i = 0;
    ast_localtime(&cdr->start, &tm, ast_test_flag(&config, CONFIG_USEGMTIME) ? "GMT" : NULL);
    ast_strftime(timestr, sizeof(timestr), DATE_FORMAT, &tm);
    if (ast_test_flag(&config, CONFIG_NEWCDRCOLUMNS)) {
       snprintf(new_columns, sizeof(new_columns), "%s", ",peeraccount,linkedid,sequence");
       snprintf(new_values, sizeof(new_values), "%s", ",?,?,?");
    }
    if (ast_test_flag(&config, CONFIG_LOGUNIQUEID)) {
       snprintf(sqlcmd,sizeof(sqlcmd),"INSERT INTO %s "
       "(calldate,clid,src,dst,dcontext,channel,dstchannel,lastapp,"
       "lastdata,duration,billsec,disposition,amaflags,accountcode,uniqueid,userfield%s) "
       "VALUES ({ts '%s'},?,?,?,?,?,?,?,?,?,?,?,?,?,?,?%s)", table, new_columns, timestr, new_values);
    } else {
       snprintf(sqlcmd,sizeof(sqlcmd),"INSERT INTO %s "
       "(calldate,clid,src,dst,dcontext,channel,dstchannel,lastapp,lastdata,"
       "duration,billsec,disposition,amaflags,accountcode%s) "
       "VALUES ({ts '%s'},?,?,?,?,?,?,?,?,?,?,?,?,?%s)", table, new_columns, timestr, new_values);
    }
    ODBC_res = SQLAllocHandle(SQL_HANDLE_STMT, obj->con, &stmt);
    if ((ODBC_res != SQL_SUCCESS) && (ODBC_res != SQL_SUCCESS_WITH_INFO)) {
       ast_log(LOG_WARNING, "cdr_odbc: Failure in AllocStatement %d\n", ODBC_res);
       SQLFreeHandle(SQL_HANDLE_STMT, stmt);
       return NULL;
    }
    SQLBindParameter(stmt, 1, SQL_PARAM_INPUT, SQL_C_CHAR, SQL_CHAR, sizeof(cdr->clid), 0, cdr->clid, 0, NULL);
    SQLBindParameter(stmt, 2, SQL_PARAM_INPUT, SQL_C_CHAR, SQL_CHAR, sizeof(cdr->src), 0, cdr->src, 0, NULL);
    SQLBindParameter(stmt, 3, SQL_PARAM_INPUT, SQL_C_CHAR, SQL_CHAR, sizeof(cdr->dst), 0, cdr->dst, 0, NULL);
    SQLBindParameter(stmt, 4, SQL_PARAM_INPUT, SQL_C_CHAR, SQL_CHAR, sizeof(cdr->dcontext), 0, cdr->dcontext, 0, NULL);
    SQLBindParameter(stmt, 5, SQL_PARAM_INPUT, SQL_C_CHAR, SQL_CHAR, sizeof(cdr->channel), 0, cdr->channel, 0, NULL);
    SQLBindParameter(stmt, 6, SQL_PARAM_INPUT, SQL_C_CHAR, SQL_CHAR, sizeof(cdr->dstchannel), 0, cdr->dstchannel, 0, NULL);
    SQLBindParameter(stmt, 7, SQL_PARAM_INPUT, SQL_C_CHAR, SQL_CHAR, sizeof(cdr->lastapp), 0, cdr->lastapp, 0, NULL);
    SQLBindParameter(stmt, 8, SQL_PARAM_INPUT, SQL_C_CHAR, SQL_CHAR, sizeof(cdr->lastdata), 0, cdr->lastdata, 0, NULL);
    if (ast_test_flag(&config, CONFIG_HRTIME)) {
       double hrbillsec = 0.0;
       double hrduration;
       if (!ast_tvzero(cdr->answer)) {
          hrbillsec = (double) ast_tvdiff_us(cdr->end, cdr->answer) / 1000000.0;
       }
       hrduration = (double) ast_tvdiff_us(cdr->end, cdr->start) / 1000000.0;
       SQLBindParameter(stmt, 9, SQL_PARAM_INPUT, SQL_C_DOUBLE, SQL_FLOAT, 0, 0, &hrduration, 0, NULL);
       SQLBindParameter(stmt, 10, SQL_PARAM_INPUT, SQL_C_DOUBLE, SQL_FLOAT, 0, 0, &hrbillsec, 0, NULL);
    } else {
       SQLBindParameter(stmt, 9, SQL_PARAM_INPUT, SQL_C_SLONG, SQL_INTEGER, 0, 0, &cdr->duration, 0, NULL);
       SQLBindParameter(stmt, 10, SQL_PARAM_INPUT, SQL_C_SLONG, SQL_INTEGER, 0, 0, &cdr->billsec, 0, NULL);
    }
    if (ast_test_flag(&config, CONFIG_DISPOSITIONSTRING)) {
       char *disposition;
       disposition = ast_strdupa(ast_cdr_disp2str(cdr->disposition));
       SQLBindParameter(stmt, 11, SQL_PARAM_INPUT, SQL_C_CHAR, SQL_CHAR, strlen(disposition) + 1, 0, disposition, 0, NULL);
    } else {
       SQLBindParameter(stmt, 11, SQL_PARAM_INPUT, SQL_C_SLONG, SQL_INTEGER, 0, 0, &cdr->disposition, 0, NULL);
    }
    SQLBindParameter(stmt, 12, SQL_PARAM_INPUT, SQL_C_SLONG, SQL_INTEGER, 0, 0, &cdr->amaflags, 0, NULL);
    SQLBindParameter(stmt, 13, SQL_PARAM_INPUT, SQL_C_CHAR, SQL_CHAR, sizeof(cdr->accountcode), 0, cdr->accountcode, 0, NULL);
    i = 14;
    if (ast_test_flag(&config, CONFIG_LOGUNIQUEID)) {
       SQLBindParameter(stmt, 14, SQL_PARAM_INPUT, SQL_C_CHAR, SQL_CHAR, sizeof(cdr->uniqueid), 0, cdr->uniqueid, 0, NULL);
       SQLBindParameter(stmt, 15, SQL_PARAM_INPUT, SQL_C_CHAR, SQL_CHAR, sizeof(cdr->userfield), 0, cdr->userfield, 0, NULL);
       i = 16;
    }
    if (ast_test_flag(&config, CONFIG_NEWCDRCOLUMNS)) {
       SQLBindParameter(stmt, i, SQL_PARAM_INPUT, SQL_C_CHAR, SQL_CHAR, sizeof(cdr->peeraccount), 0, cdr->peeraccount, 0, NULL);
       SQLBindParameter(stmt, i + 1, SQL_PARAM_INPUT, SQL_C_CHAR, SQL_CHAR, sizeof(cdr->linkedid), 0, cdr->linkedid, 0, NULL);
       SQLBindParameter(stmt, i + 2, SQL_PARAM_INPUT, SQL_C_SLONG, SQL_INTEGER, 0, 0, &cdr->sequence, 0, NULL);
    }
    ODBC_res = ast_odbc_execute_sql(obj, stmt, sqlcmd);
    if ((ODBC_res != SQL_SUCCESS) && (ODBC_res != SQL_SUCCESS_WITH_INFO)) {
       ast_log(LOG_WARNING, "cdr_odbc: Error in ExecDirect: %d, query is: %s\n", ODBC_res, sqlcmd);
       SQLFreeHandle(SQL_HANDLE_STMT, stmt);
       return NULL;
    }
    return stmt;
 }
load_module()
static int load_module (void) static
Definition at line 299 of file cdr_odbc.c.
References odbc_load_module().
Referenced by reload().
 {
    return odbc_load_module(0);
 }
odbc_load_module()
static int odbc_load_module (int reload) static
Definition at line 193 of file cdr_odbc.c.
References ast_cdr_backend_suspend(), ast_cdr_backend_unsuspend(), ast_cdr_register(), ast_clear_flag, ast_config_destroy(), ast_config_load, ast_debug, ast_free, ast_log, AST_MODULE_LOAD_DECLINE, ast_set_flag, ast_strdup, ast_test_flag, ast_true(), ast_variable_browse(), ast_variable_retrieve(), CONFIG_DISPOSITIONSTRING, config_file, CONFIG_FLAG_FILEUNCHANGED, CONFIG_HRTIME, CONFIG_LOGUNIQUEID, CONFIG_NEWCDRCOLUMNS, CONFIG_REGISTERED, CONFIG_STATUS_FILEINVALID, CONFIG_STATUS_FILEUNCHANGED, CONFIG_USEGMTIME, ast_module_info::description, LOG_ERROR, LOG_WARNING, name, NULL, odbc_log(), table, tmp(), and var.
Referenced by load_module(), and reload().
 {
    int res = 0;
    struct ast_config *cfg;
    struct ast_variable *var;
    const char *tmp;
    struct ast_flags config_flags = { reload ? CONFIG_FLAG_FILEUNCHANGED : 0 };
    do {
       cfg = ast_config_load(config_file, config_flags);
       if (!cfg || cfg == CONFIG_STATUS_FILEINVALID) {
          ast_log(LOG_WARNING, "cdr_odbc: Unable to load config for ODBC CDR's: %s\n", config_file);
          res = AST_MODULE_LOAD_DECLINE;
          break;
       } else if (cfg == CONFIG_STATUS_FILEUNCHANGED)
          break;
       var = ast_variable_browse(cfg, "global");
       if (!var) {
          /* nothing configured */
          break;
       }
       if ((tmp = ast_variable_retrieve(cfg, "global", "dsn")) == NULL) {
          ast_log(LOG_WARNING, "cdr_odbc: dsn not specified.  Assuming asteriskdb\n");
          tmp = "asteriskdb";
       }
       if (dsn)
          ast_free(dsn);
       dsn = ast_strdup(tmp);
       if (dsn == NULL) {
          res = -1;
          break;
       }
       if (((tmp = ast_variable_retrieve(cfg, "global", "dispositionstring"))) && ast_true(tmp))
          ast_set_flag(&config, CONFIG_DISPOSITIONSTRING);
       else
          ast_clear_flag(&config, CONFIG_DISPOSITIONSTRING);
       if (((tmp = ast_variable_retrieve(cfg, "global", "loguniqueid"))) && ast_true(tmp)) {
          ast_set_flag(&config, CONFIG_LOGUNIQUEID);
          ast_debug(1, "cdr_odbc: Logging uniqueid\n");
       } else {
          ast_clear_flag(&config, CONFIG_LOGUNIQUEID);
          ast_debug(1, "cdr_odbc: Not logging uniqueid\n");
       }
       if (((tmp = ast_variable_retrieve(cfg, "global", "usegmtime"))) && ast_true(tmp)) {
          ast_set_flag(&config, CONFIG_USEGMTIME);
          ast_debug(1, "cdr_odbc: Logging in GMT\n");
       } else {
          ast_clear_flag(&config, CONFIG_USEGMTIME);
          ast_debug(1, "cdr_odbc: Logging in local time\n");
       }
       if (((tmp = ast_variable_retrieve(cfg, "global", "hrtime"))) && ast_true(tmp)) {
          ast_set_flag(&config, CONFIG_HRTIME);
          ast_debug(1, "cdr_odbc: Logging billsec and duration fields as floats\n");
       } else {
          ast_clear_flag(&config, CONFIG_HRTIME);
          ast_debug(1, "cdr_odbc: Logging billsec and duration fields as integers\n");
       }
       if ((tmp = ast_variable_retrieve(cfg, "global", "table")) == NULL) {
          ast_log(LOG_WARNING, "cdr_odbc: table not specified.  Assuming cdr\n");
          tmp = "cdr";
       }
       if (table)
          ast_free(table);
       table = ast_strdup(tmp);
       if (table == NULL) {
          res = -1;
          break;
       }
       if (!ast_test_flag(&config, CONFIG_REGISTERED)) {
          res = ast_cdr_register(name, ast_module_info->description, odbc_log);
          if (res) {
             ast_log(LOG_ERROR, "cdr_odbc: Unable to register ODBC CDR handling\n");
          } else {
             ast_set_flag(&config, CONFIG_REGISTERED);
          }
       }
       if (((tmp = ast_variable_retrieve(cfg, "global", "newcdrcolumns"))) && ast_true(tmp)) {
          ast_set_flag(&config, CONFIG_NEWCDRCOLUMNS);
          ast_debug(1, "cdr_odbc: Add new cdr columns\n");
       } else {
          ast_clear_flag(&config, CONFIG_NEWCDRCOLUMNS);
          ast_debug(1, "cdr_odbc: Not add new cdr columns\n");
       }
    } while (0);
    if (ast_test_flag(&config, CONFIG_REGISTERED) && (!cfg || dsn == NULL || table == NULL)) {
       ast_cdr_backend_suspend(name);
       ast_clear_flag(&config, CONFIG_REGISTERED);
    } else {
       ast_cdr_backend_unsuspend(name);
    }
    if (cfg && cfg != CONFIG_STATUS_FILEUNCHANGED && cfg != CONFIG_STATUS_FILEINVALID) {
       ast_config_destroy(cfg);
    }
    return res;
 }
odbc_log()
static int odbc_log (struct ast_cdr * cdr) static
Definition at line 168 of file cdr_odbc.c.
References ast_log, ast_odbc_direct_execute(), ast_odbc_release_obj(), ast_odbc_request_obj, execute_cb(), LOG_ERROR, and LOG_WARNING.
Referenced by odbc_load_module().
 {
    struct odbc_obj *obj = ast_odbc_request_obj(dsn, 0);
    SQLHSTMT stmt;
    if (!obj) {
       ast_log(LOG_ERROR, "Unable to retrieve database handle.  CDR failed.\n");
       return -1;
    }
    stmt = ast_odbc_direct_execute(obj, execute_cb, cdr);
    if (stmt) {
       SQLLEN rows = 0;
       SQLRowCount(stmt, &rows);
       SQLFreeHandle(SQL_HANDLE_STMT, stmt);
       if (rows == 0)
          ast_log(LOG_WARNING, "CDR successfully ran, but inserted 0 rows?\n");
    } else
       ast_log(LOG_ERROR, "CDR direct execute failed\n");
    ast_odbc_release_obj(obj);
    return 0;
 }
reload()
static int reload (void) static
Definition at line 320 of file cdr_odbc.c.
References AST_MODFLAG_LOAD_ORDER, AST_MODPRI_CDR_DRIVER, AST_MODULE_INFO(), AST_MODULE_SUPPORT_EXTENDED, ASTERISK_GPL_KEY, load_module(), odbc_load_module(), and unload_module().
 {
    return odbc_load_module(1);
 }
unload_module()
static int unload_module (void) static
Definition at line 304 of file cdr_odbc.c.
References ast_cdr_unregister(), ast_free, name, and table.
Referenced by reload().
 {
    if (ast_cdr_unregister(name)) {
       return -1;
    }
    if (dsn) {
       ast_free(dsn);
    }
    if (table) {
       ast_free(table);
    }
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "ODBC CDR Backend" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_EXTENDED, .load = load_module, .unload = unload_module, .reload = reload, .load_pri = AST_MODPRI_CDR_DRIVER, .requires = "cdr,res_odbc", } static
Definition at line 332 of file cdr_odbc.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 332 of file cdr_odbc.c.
config
struct ast_flags config = { 0 } static
Definition at line 69 of file cdr_odbc.c.
config_file
const char config_file[] = "cdr_odbc.conf" static
Definition at line 57 of file cdr_odbc.c.
Referenced by AST_TEST_DEFINE(), odbc_load_module(), pbx_load_config(), pbx_substitute_variables_helper(), and write_config_file().
dsn
char* dsn = NULL static
Definition at line 58 of file cdr_odbc.c.
Referenced by create_dsn(), and get_dsn().
name
const char name[] = "ODBC" static
Definition at line 56 of file cdr_odbc.c.
Referenced by odbc_load_module(), and unload_module().
table
char * table = NULL static
Examples:
/usr/src/asterisk-18.5.0/main/app.c.
Definition at line 58 of file cdr_odbc.c.
Referenced by __ast_vm_greeter_register(), __ast_vm_register(), ast_config_internal_load(), ast_parking_blind_transfer_park(), ast_parking_is_exten_park(), ast_parking_park_bridge_channel(), ast_parking_park_call(), ast_parking_provider_registered(), ast_vm_greeter_is_registered(), ast_vm_greeter_unregister(), ast_vm_is_registered(), ast_vm_unregister(), execute_cb(), find_table(), free_config(), load_config(), odbc_load_module(), quan(), realtime_common(), reload(), reload_module(), require_mysql(), require_pgsql(), unload_module(), update2_mysql(), update2_odbc(), update2_pgsql(), update_mysql(), and update_pgsql().