Asterisk - The Open Source Telephony Project: app_chanisavail.c File Reference
app_chanisavail.c File Reference
Dial plan applications
Check if Channel is Available.
#include "asterisk.h"
#include <sys/ioctl.h>
#include "asterisk/lock.h"
#include "asterisk/file.h"
#include "asterisk/channel.h"
#include "asterisk/pbx.h"
#include "asterisk/module.h"
#include "asterisk/app.h"
#include "asterisk/devicestate.h"
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int chanavail_exec (struct ast_channel *chan, const char *data)
static int load_module (void)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_DEFAULT , .description = "Check channel availability" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_EXTENDED, .load = load_module, .unload = unload_module, .optional_modules = "func_cdr" }
static const char app [] = "ChanIsAvail"
static const struct ast_module_info * ast_module_info = &__mod_info
Detailed Description
Check if Channel is Available.
Author
Mark Spencer marks.nosp@m.ter@.nosp@m.digiu.nosp@m.m.co.nosp@m.m
James Golovich james.nosp@m.@gnu.nosp@m.inter.nosp@m..net
Definition in file app_chanisavail.c.
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 229 of file app_chanisavail.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 229 of file app_chanisavail.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 229 of file app_chanisavail.c.
chanavail_exec()
static int chanavail_exec (struct ast_channel * chan, const char * data) static
Definition at line 102 of file app_chanisavail.c.
References args, AST_APP_ARG, ast_channel_name(), ast_channel_nativeformats(), ast_custom_function_find(), AST_DECLARE_APP_ARGS, AST_DEVICE_INVALID, AST_DEVICE_NOT_INUSE, AST_DEVICE_UNKNOWN, ast_func_write(), ast_hangup(), ast_log, ast_parse_device_state(), ast_request(), AST_STANDARD_APP_ARGS, ast_str_alloca, ast_str_append(), ast_str_buffer(), ast_str_strlen(), ast_strdupa, ast_strip(), ast_strlen_zero, sip_to_pjsip::info(), LOG_WARNING, NULL, options, pbx_builtin_setvar_helper(), status, and strsep().
Referenced by load_module().
 {
    int inuse = -1;
    int option_state = 0;
    int string_compare = 0;
    int option_all_avail = 0;
    int status;
    char *info;
    char trychan[512];
    char *rest;
    char *tech;
    char *number;
    struct ast_str *tmp_availchan = ast_str_alloca(2048);
    struct ast_str *tmp_availorig = ast_str_alloca(2048);
    struct ast_str *tmp_availstat = ast_str_alloca(2048);
    struct ast_str *tmp_availcause = ast_str_alloca(2048);
    struct ast_channel *tempchan;
    struct ast_custom_function *cdr_prop_func = ast_custom_function_find("CDR_PROP");
    AST_DECLARE_APP_ARGS(args,
       AST_APP_ARG(reqchans);
       AST_APP_ARG(options);
    );
    info = ast_strdupa(data ?: "");
    AST_STANDARD_APP_ARGS(args, info);
    if (args.options) {
       if (strchr(args.options, 'a')) {
          option_all_avail = 1;
       }
       if (strchr(args.options, 's')) {
          option_state = 1;
       }
       if (strchr(args.options, 't')) {
          string_compare = 1;
       }
    }
    rest = args.reqchans;
    if (!rest) {
       rest = "";
    }
    while ((tech = strsep(&rest, "&"))) {
       tech = ast_strip(tech);
       number = strchr(tech, '/');
       if (!number) {
          if (!ast_strlen_zero(tech)) {
             ast_log(LOG_WARNING, "Invalid ChanIsAvail technology/resource argument: '%s'\n",
                tech);
          }
          ast_str_append(&tmp_availstat, 0, "%s%d",
             ast_str_strlen(tmp_availstat) ? "&" : "", AST_DEVICE_INVALID);
          continue;
       }
       *number++ = '\0';
       status = AST_DEVICE_UNKNOWN;
       if (string_compare) {
          /* ast_parse_device_state checks for "SIP/1234" as a channel name.
             ast_device_state will ask the SIP driver for the channel state. */
          snprintf(trychan, sizeof(trychan), "%s/%s", tech, number);
          status = inuse = ast_parse_device_state(trychan);
       } else if (option_state) {
          /* If the pbx says in use then don't bother trying further.
             This is to permit testing if someone's on a call, even if the
             channel can permit more calls (ie callwaiting, sip calls, etc).  */
          snprintf(trychan, sizeof(trychan), "%s/%s", tech, number);
          status = inuse = ast_device_state(trychan);
       }
       ast_str_append(&tmp_availstat, 0, "%s%d",
          ast_str_strlen(tmp_availstat) ? "&" : "", status);
       if ((inuse <= (int) AST_DEVICE_NOT_INUSE)
          && (tempchan = ast_request(tech, ast_channel_nativeformats(chan), NULL, chan, number, &status))) {
          ast_str_append(&tmp_availchan, 0, "%s%s",
             ast_str_strlen(tmp_availchan) ? "&" : "", ast_channel_name(tempchan));
          ast_str_append(&tmp_availorig, 0, "%s%s/%s",
             ast_str_strlen(tmp_availorig) ? "&" : "", tech, number);
          ast_str_append(&tmp_availcause, 0, "%s%d",
             ast_str_strlen(tmp_availcause) ? "&" : "", status);
          /* Disable CDR for this temporary channel. */
          if (cdr_prop_func) {
             ast_func_write(tempchan, "CDR_PROP(disable)", "1");
          }
          ast_hangup(tempchan);
          tempchan = NULL;
          if (!option_all_avail) {
             break;
          }
       }
    }
    pbx_builtin_setvar_helper(chan, "AVAILCHAN", ast_str_buffer(tmp_availchan));
    /* Store the originally used channel too */
    pbx_builtin_setvar_helper(chan, "AVAILORIGCHAN", ast_str_buffer(tmp_availorig));
    pbx_builtin_setvar_helper(chan, "AVAILSTATUS", ast_str_buffer(tmp_availstat));
    pbx_builtin_setvar_helper(chan, "AVAILCAUSECODE", ast_str_buffer(tmp_availcause));
    return 0;
 }
load_module()
static int load_module (void) static
Definition at line 218 of file app_chanisavail.c.
References app, AST_MODFLAG_DEFAULT, AST_MODULE_INFO(), AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, AST_MODULE_SUPPORT_EXTENDED, ast_register_application_xml, ASTERISK_GPL_KEY, chanavail_exec(), and unload_module().
 {
    return ast_register_application_xml(app, chanavail_exec) ?
       AST_MODULE_LOAD_DECLINE : AST_MODULE_LOAD_SUCCESS;
 }
unload_module()
static int unload_module (void) static
Definition at line 213 of file app_chanisavail.c.
References app, and ast_unregister_application().
Referenced by load_module().
 {
    return ast_unregister_application(app);
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_DEFAULT , .description = "Check channel availability" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_EXTENDED, .load = load_module, .unload = unload_module, .optional_modules = "func_cdr" } static
Definition at line 229 of file app_chanisavail.c.
app
const char app[] = "ChanIsAvail" static
Definition at line 46 of file app_chanisavail.c.
Referenced by load_module(), and unload_module().
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 229 of file app_chanisavail.c.