Asterisk - The Open Source Telephony Project: res_http_media_cache.c File Reference
res_http_media_cache.c File Reference
#include "asterisk.h"
#include <curl/curl.h>
#include "asterisk/module.h"
#include "asterisk/bucket.h"
#include "asterisk/sorcery.h"
#include "asterisk/threadstorage.h"
Data Structures
struct curl_bucket_file_data
Data passed to cURL callbacks.
Macros
#define GLOBAL_USERAGENT "asterisk-libcurl-agent/1.0"
#define MAX_HEADER_LENGTH 1023
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int bucket_file_always_revalidate (struct ast_bucket_file *bucket_file)
static int bucket_file_expired (struct ast_bucket_file *bucket_file)
static int bucket_file_run_curl (struct ast_bucket_file *bucket_file)
static void bucket_file_set_expiration (struct ast_bucket_file *bucket_file)
static int bucket_http_wizard_create (const struct ast_sorcery *sorcery, void *data, void *object)
static int bucket_http_wizard_delete (const struct ast_sorcery *sorcery, void *data, void *object)
static int bucket_http_wizard_is_stale (const struct ast_sorcery *sorcery, void *data, void *object)
static void * bucket_http_wizard_retrieve_id (const struct ast_sorcery *sorcery, void *data, const char *type, const char *id)
static size_t curl_body_callback (void *ptr, size_t size, size_t nitems, void *data)
static size_t curl_header_callback (char *buffer, size_t size, size_t nitems, void *data)
static long execute_curl_instance (CURL *curl)
Execute the CURL.
static CURL * get_curl_instance (struct curl_bucket_file_data *cb_data)
static int load_module (void)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_DEFAULT , .description = "HTTP Media Cache Backend" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .requires = "res_curl", }
static const struct ast_module_info * ast_module_info = &__mod_info
static struct ast_sorcery_wizard http_bucket_file_wizard
static struct ast_sorcery_wizard http_bucket_wizard
static struct ast_sorcery_wizard https_bucket_file_wizard
static struct ast_sorcery_wizard https_bucket_wizard
Detailed Description
Author
Matt Jordan <mjordan@digium.com>
HTTP backend for the core media cache
Definition in file res_http_media_cache.c.
Macro Definition Documentation
GLOBAL_USERAGENT
#define GLOBAL_USERAGENT "asterisk-libcurl-agent/1.0"
Definition at line 43 of file res_http_media_cache.c.
Referenced by get_curl_instance().
MAX_HEADER_LENGTH
#define MAX_HEADER_LENGTH 1023
Definition at line 45 of file res_http_media_cache.c.
Referenced by curl_header_callback().
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 447 of file res_http_media_cache.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 447 of file res_http_media_cache.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 447 of file res_http_media_cache.c.
bucket_file_always_revalidate()
static int bucket_file_always_revalidate (struct ast_bucket_file * bucket_file) static
Definition at line 161 of file res_http_media_cache.c.
References ao2_cleanup, ast_bucket_file_metadata_get(), and RAII_VAR.
Referenced by bucket_http_wizard_is_stale().
 {
    RAII_VAR(struct ast_bucket_metadata *, metadata,
       ast_bucket_file_metadata_get(bucket_file, "cache-control"),
       ao2_cleanup);
    if (!metadata) {
       return 0;
    }
    if (strstr(metadata->value, "no-cache")
       || strstr(metadata->value, "must-revalidate")) {
       return 1;
    }
    return 0;
 }
bucket_file_expired()
static int bucket_file_expired (struct ast_bucket_file * bucket_file) static
Definition at line 182 of file res_http_media_cache.c.
References ao2_cleanup, ast_bucket_file_metadata_get(), ast_tvcmp(), ast_tvnow(), and RAII_VAR.
Referenced by bucket_http_wizard_is_stale().
 {
    RAII_VAR(struct ast_bucket_metadata *, metadata,
       ast_bucket_file_metadata_get(bucket_file, "__actual_expires"),
       ao2_cleanup);
    struct timeval current_time = ast_tvnow();
    struct timeval expires = { .tv_sec = 0, .tv_usec = 0 };
    if (!metadata) {
       return 1;
    }
    if (sscanf(metadata->value, "%lu", &expires.tv_sec) != 1) {
       return 1;
    }
    return ast_tvcmp(current_time, expires) == -1 ? 0 : 1;
 }
bucket_file_run_curl()
static int bucket_file_run_curl (struct ast_bucket_file * bucket_file) static
Definition at line 251 of file res_http_media_cache.c.
References ast_log, ast_sorcery_object_get_id(), curl_bucket_file_data::bucket_file, bucket_file_set_expiration(), curl_body_callback(), errno, execute_curl_instance(), get_curl_instance(), LOG_WARNING, curl_bucket_file_data::out_file, and ast_bucket_file::path.
Referenced by bucket_http_wizard_create(), and bucket_http_wizard_retrieve_id().
 {
    struct curl_bucket_file_data cb_data = {
       .bucket_file = bucket_file,
    };
    long http_code;
    CURL *curl;
    cb_data.out_file = fopen(bucket_file->path, "wb");
    if (!cb_data.out_file) {
       ast_log(LOG_WARNING, "Failed to open file '%s' for writing: %s (%d)\n",
          bucket_file->path, strerror(errno), errno);
       return -1;
    }
    curl = get_curl_instance(&cb_data);
    if (!curl) {
       fclose(cb_data.out_file);
       return -1;
    }
    curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, curl_body_callback);
    curl_easy_setopt(curl, CURLOPT_WRITEDATA, (void*)&cb_data);
    http_code = execute_curl_instance(curl);
    fclose(cb_data.out_file);
    if (http_code / 100 == 2) {
       bucket_file_set_expiration(bucket_file);
       return 0;
    } else {
       ast_log(LOG_WARNING, "Failed to retrieve URL '%s': server returned %ld\n",
          ast_sorcery_object_get_id(bucket_file), http_code);
    }
    return -1;
 }
bucket_file_set_expiration()
static void bucket_file_set_expiration (struct ast_bucket_file * bucket_file) static
Definition at line 116 of file res_http_media_cache.c.
References ao2_ref, ast_bucket_file_metadata_get(), ast_bucket_file_metadata_set(), ast_tvnow(), and ast_bucket_metadata::value.
Referenced by bucket_file_run_curl(), and bucket_http_wizard_is_stale().
 {
    struct ast_bucket_metadata *metadata;
    char time_buf[32];
    struct timeval actual_expires = ast_tvnow();
    metadata = ast_bucket_file_metadata_get(bucket_file, "cache-control");
    if (metadata) {
       char *str_max_age;
       str_max_age = strstr(metadata->value, "s-maxage");
       if (!str_max_age) {
          str_max_age = strstr(metadata->value, "max-age");
       }
       if (str_max_age) {
          unsigned int max_age;
          char *equal = strchr(str_max_age, '=');
          if (equal && (sscanf(equal + 1, "%30u", &max_age) == 1)) {
             actual_expires.tv_sec += max_age;
          }
       }
       ao2_ref(metadata, -1);
    } else {
       metadata = ast_bucket_file_metadata_get(bucket_file, "expires");
       if (metadata) {
          struct tm expires_time;
          strptime(metadata->value, "%a, %d %b %Y %T %z", &expires_time);
          expires_time.tm_isdst = -1;
          actual_expires.tv_sec = mktime(&expires_time);
          ao2_ref(metadata, -1);
       }
    }
    /* Use 'now' if we didn't get an expiration time */
    snprintf(time_buf, sizeof(time_buf), "%30lu", actual_expires.tv_sec);
    ast_bucket_file_metadata_set(bucket_file, "__actual_expires", time_buf);
 }
bucket_http_wizard_create()
static int bucket_http_wizard_create (const struct ast_sorcery * sorcery, void * data, void * object) static
Definition at line 333 of file res_http_media_cache.c.
References curl_bucket_file_data::bucket_file, and bucket_file_run_curl().
 {
    struct ast_bucket_file *bucket_file = object;
    return bucket_file_run_curl(bucket_file);
 }
bucket_http_wizard_delete()
static int bucket_http_wizard_delete (const struct ast_sorcery * sorcery, void * data, void * object) static
Definition at line 378 of file res_http_media_cache.c.
References curl_bucket_file_data::bucket_file, and ast_bucket_file::path.
 {
    struct ast_bucket_file *bucket_file = object;
    unlink(bucket_file->path);
    return 0;
 }
bucket_http_wizard_is_stale()
static int bucket_http_wizard_is_stale (const struct ast_sorcery * sorcery, void * data, void * object) static
Definition at line 290 of file res_http_media_cache.c.
References ao2_ref, ast_bucket_file_metadata_get(), curl_bucket_file_data::bucket_file, bucket_file_always_revalidate(), bucket_file_expired(), bucket_file_set_expiration(), execute_curl_instance(), get_curl_instance(), NULL, and ast_bucket_metadata::value.
 {
    struct ast_bucket_file *bucket_file = object;
    struct ast_bucket_metadata *metadata;
    struct curl_slist *header_list = NULL;
    long http_code;
    CURL *curl;
    struct curl_bucket_file_data cb_data = {
       .bucket_file = bucket_file
    };
    char etag_buf[256];
    if (!bucket_file_expired(bucket_file) && !bucket_file_always_revalidate(bucket_file)) {
       return 0;
    }
    /* See if we have an ETag for this item. If not, it's stale. */
    metadata = ast_bucket_file_metadata_get(bucket_file, "etag");
    if (!metadata) {
       return 1;
    }
    curl = get_curl_instance(&cb_data);
    /* Set the ETag header on our outgoing request */
    snprintf(etag_buf, sizeof(etag_buf), "If-None-Match: %s", metadata->value);
    header_list = curl_slist_append(header_list, etag_buf);
    curl_easy_setopt(curl, CURLOPT_HTTPHEADER, header_list);
    curl_easy_setopt(curl, CURLOPT_NOBODY, 1L);
    ao2_ref(metadata, -1);
    http_code = execute_curl_instance(curl);
    curl_slist_free_all(header_list);
    if (http_code == 304) {
       bucket_file_set_expiration(bucket_file);
       return 0;
    }
    return 1;
 }
bucket_http_wizard_retrieve_id()
static void* bucket_http_wizard_retrieve_id (const struct ast_sorcery * sorcery, void * data, const char * type, const char * id) static
Definition at line 341 of file res_http_media_cache.c.
References ao2_ref, ast_bucket_file_alloc(), ast_bucket_file_temporary_create(), ast_log, ast_sorcery_delete(), ast_strlen_zero, curl_bucket_file_data::bucket_file, bucket_file_run_curl(), LOG_WARNING, and NULL.
 {
    struct ast_bucket_file *bucket_file;
    if (strcmp(type, "file")) {
       ast_log(LOG_WARNING, "Failed to create storage: invalid bucket type '%s'\n", type);
       return NULL;
    }
    if (ast_strlen_zero(id)) {
       ast_log(LOG_WARNING, "Failed to create storage: no URI\n");
       return NULL;
    }
    bucket_file = ast_bucket_file_alloc(id);
    if (!bucket_file) {
       ast_log(LOG_WARNING, "Failed to create storage for '%s'\n", id);
       return NULL;
    }
    if (ast_bucket_file_temporary_create(bucket_file)) {
       ast_log(LOG_WARNING, "Failed to create temporary storage for '%s'\n", id);
       ast_sorcery_delete(sorcery, bucket_file);
       ao2_ref(bucket_file, -1);
       return NULL;
    }
    if (bucket_file_run_curl(bucket_file)) {
       ast_sorcery_delete(sorcery, bucket_file);
       ao2_ref(bucket_file, -1);
       return NULL;
    }
    return bucket_file;
 }
curl_body_callback()
static size_t curl_body_callback (void * ptr, size_t size, size_t nitems, void * data) static
Definition at line 103 of file res_http_media_cache.c.
References curl_bucket_file_data::out_file.
Referenced by bucket_file_run_curl().
 {
    struct curl_bucket_file_data *cb_data = data;
    size_t realsize;
    realsize = fwrite(ptr, size, nitems, cb_data->out_file);
    return realsize;
 }
curl_header_callback()
static size_t curl_header_callback (char * buffer, size_t size, size_t nitems, void * data) static
Definition at line 58 of file res_http_media_cache.c.
References ast_alloca, ast_bucket_file_metadata_set(), ast_log, ast_skip_blanks(), ast_str_to_lower(), ast_trim_blanks(), curl_bucket_file_data::bucket_file, LOG_WARNING, MAX_HEADER_LENGTH, and value.
Referenced by get_curl_instance().
 {
    struct curl_bucket_file_data *cb_data = data;
    size_t realsize;
    char *value;
    char *header;
    realsize = size * nitems;
    if (realsize > MAX_HEADER_LENGTH) {
       ast_log(LOG_WARNING, "cURL header length of '%zu' is too large: max %d\n",
          realsize, MAX_HEADER_LENGTH);
       return 0;
    }
    /* buffer may not be NULL terminated */
    header = ast_alloca(realsize + 1);
    memcpy(header, buffer, realsize);
    header[realsize] = '\0';
    value = strchr(header, ':');
    if (!value) {
       /* Not a header we care about; bail */
       return realsize;
    }
    *value++ = '\0';
    if (strcasecmp(header, "ETag")
       && strcasecmp(header, "Cache-Control")
       && strcasecmp(header, "Last-Modified")
       && strcasecmp(header, "Content-Type")
       && strcasecmp(header, "Expires")) {
       return realsize;
    }
    value = ast_trim_blanks(ast_skip_blanks(value));
    header = ast_str_to_lower(header);
    ast_bucket_file_metadata_set(cb_data->bucket_file, header, value);
    return realsize;
 }
execute_curl_instance()
static long execute_curl_instance (CURL * curl) static
Execute the CURL.
Definition at line 228 of file res_http_media_cache.c.
References ast_log, and LOG_WARNING.
Referenced by bucket_file_run_curl(), and bucket_http_wizard_is_stale().
 {
    char curl_errbuf[CURL_ERROR_SIZE + 1];
    long http_code;
    curl_errbuf[CURL_ERROR_SIZE] = '\0';
    curl_easy_setopt(curl, CURLOPT_ERRORBUFFER, curl_errbuf);
    if (curl_easy_perform(curl)) {
       ast_log(LOG_WARNING, "%s\n", curl_errbuf);
       return -1;
    }
    curl_easy_getinfo(curl, CURLINFO_RESPONSE_CODE, &http_code);
    curl_easy_cleanup(curl);
    return http_code;
 }
get_curl_instance()
static CURL* get_curl_instance (struct curl_bucket_file_data * cb_data) static
Definition at line 204 of file res_http_media_cache.c.
References ast_sorcery_object_get_id(), curl_bucket_file_data::bucket_file, curl_header_callback(), GLOBAL_USERAGENT, and NULL.
Referenced by bucket_file_run_curl(), and bucket_http_wizard_is_stale().
 {
    CURL *curl;
    curl = curl_easy_init();
    if (!curl) {
       return NULL;
    }
    curl_easy_setopt(curl, CURLOPT_NOSIGNAL, 1);
    curl_easy_setopt(curl, CURLOPT_TIMEOUT, 180);
    curl_easy_setopt(curl, CURLOPT_HEADERFUNCTION, curl_header_callback);
    curl_easy_setopt(curl, CURLOPT_USERAGENT, GLOBAL_USERAGENT);
    curl_easy_setopt(curl, CURLOPT_FOLLOWLOCATION, 1);
    curl_easy_setopt(curl, CURLOPT_MAXREDIRS, 8);
    curl_easy_setopt(curl, CURLOPT_URL, ast_sorcery_object_get_id(cb_data->bucket_file));
    curl_easy_setopt(curl, CURLOPT_HEADERDATA, cb_data);
    return curl;
 }
load_module()
static int load_module (void) static
Definition at line 425 of file res_http_media_cache.c.
References ast_bucket_scheme_register, ast_log, AST_MODFLAG_DEFAULT, AST_MODULE_INFO(), AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, AST_MODULE_SUPPORT_CORE, ASTERISK_GPL_KEY, ast_sorcery_wizard::load, LOG_ERROR, NULL, and unload_module().
 {
    if (ast_bucket_scheme_register("http", &http_bucket_wizard, &http_bucket_file_wizard,
          NULL, NULL)) {
       ast_log(LOG_ERROR, "Failed to register Bucket HTTP wizard scheme implementation\n");
       return AST_MODULE_LOAD_DECLINE;
    }
    if (ast_bucket_scheme_register("https", &https_bucket_wizard, &https_bucket_file_wizard,
          NULL, NULL)) {
       ast_log(LOG_ERROR, "Failed to register Bucket HTTPS wizard scheme implementation\n");
       return AST_MODULE_LOAD_DECLINE;
    }
    return AST_MODULE_LOAD_SUCCESS;
 }
unload_module()
static int unload_module (void) static
Definition at line 420 of file res_http_media_cache.c.
Referenced by load_module().
 {
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_DEFAULT , .description = "HTTP Media Cache Backend" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .requires = "res_curl", } static
Definition at line 447 of file res_http_media_cache.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 447 of file res_http_media_cache.c.
http_bucket_file_wizard
struct ast_sorcery_wizard http_bucket_file_wizard static
Definition at line 396 of file res_http_media_cache.c.
http_bucket_wizard
struct ast_sorcery_wizard http_bucket_wizard static
Definition at line 388 of file res_http_media_cache.c.
https_bucket_file_wizard
struct ast_sorcery_wizard https_bucket_file_wizard static
Definition at line 412 of file res_http_media_cache.c.
https_bucket_wizard
struct ast_sorcery_wizard https_bucket_wizard static
Definition at line 404 of file res_http_media_cache.c.