Asterisk - The Open Source Telephony Project: dialplan_functions.c File Reference
pjsip/dialplan_functions.c File Reference
Module: Dial plan functions
PJSIP channel dialplan functions.
#include "asterisk.h"
#include <pjsip.h>
#include <pjlib.h>
#include <pjsip_ua.h>
#include "asterisk/astobj2.h"
#include "asterisk/module.h"
#include "asterisk/acl.h"
#include "asterisk/app.h"
#include "asterisk/channel.h"
#include "asterisk/stream.h"
#include "asterisk/format.h"
#include "asterisk/dsp.h"
#include "asterisk/pbx.h"
#include "asterisk/res_pjsip.h"
#include "asterisk/res_pjsip_session.h"
#include "include/chan_pjsip.h"
#include "include/dialplan_functions.h"
Data Structures
struct media_offer_data
struct parse_uri_args
Struct used to push PJSIP_PARSE_URI function arguments to task processor.
struct pjsip_func_args
Struct used to push function arguments to task processor.
struct refresh_data
struct session_refresh_state
Session refresh state information.
Functions
static int channel_read_pjsip (struct ast_channel *chan, const char *type, const char *field, char *buf, size_t buflen)
static int channel_read_rtcp (struct ast_channel *chan, const char *type, const char *field, char *buf, size_t buflen)
static int channel_read_rtp (struct ast_channel *chan, const char *type, const char *field, char *buf, size_t buflen)
static int dtmf_mode_refresh_cb (void *obj)
static int media_offer_read_av (struct ast_sip_session *session, char *buf, size_t len, enum ast_media_type media_type)
static int media_offer_write_av (void *obj)
static int parse_uri_cb (void *data)
int pjsip_acf_channel_read (struct ast_channel *chan, const char *cmd, char *data, char *buf, size_t len)
CHANNEL function read callback.
int pjsip_acf_dial_contacts_read (struct ast_channel *chan, const char *cmd, char *data, char *buf, size_t len)
PJSIP_DIAL_CONTACTS function read callback.
int pjsip_acf_dtmf_mode_read (struct ast_channel *chan, const char *cmd, char *data, char *buf, size_t len)
PJSIP_DTMF_MODE function read callback.
int pjsip_acf_dtmf_mode_write (struct ast_channel *chan, const char *cmd, char *data, const char *value)
PJSIP_DTMF_MODE function write callback.
int pjsip_acf_media_offer_read (struct ast_channel *chan, const char *cmd, char *data, char *buf, size_t len)
PJSIP_MEDIA_OFFER function read callback.
int pjsip_acf_media_offer_write (struct ast_channel *chan, const char *cmd, char *data, const char *value)
PJSIP_MEDIA_OFFER function write callback.
int pjsip_acf_moh_passthrough_read (struct ast_channel *chan, const char *cmd, char *data, char *buf, size_t len)
PJSIP_MOH_PASSTHROUGH function read callback.
int pjsip_acf_moh_passthrough_write (struct ast_channel *chan, const char *cmd, char *data, const char *value)
PJSIP_MOH_PASSTHROUGH function write callback.
int pjsip_acf_parse_uri_read (struct ast_channel *chan, const char *cmd, char *data, char *buf, size_t buflen)
PJSIP_PARSE_URI function read callback.
int pjsip_acf_session_refresh_write (struct ast_channel *chan, const char *cmd, char *data, const char *value)
PJSIP_SEND_SESSION_REFRESH function write callback.
static int print_escaped_uri (struct ast_channel *chan, const char *type, pjsip_uri_context_e context, const void *uri, char *buf, size_t size)
static int read_pjsip (void *data)
static int refresh_write_cb (void *obj)
static void session_refresh_state_destroy (void *obj)
Destructor for session refresh information.
static struct session_refresh_state * session_refresh_state_get_or_alloc (struct ast_sip_session *session)
Helper function which retrieves or allocates a session refresh state information datastore.
static int sip_session_response_cb (struct ast_sip_session *session, pjsip_rx_data *rdata)
Variables
static const struct ast_datastore_info session_refresh_datastore
Datastore for attaching session refresh state information.
static const char * t38state_to_string [T38_MAX_ENUM]
String representations of the T.38 state enum.
Detailed Description
PJSIP channel dialplan functions.
Author
Joshua Colp <jcolp@digium.com>
Matt Jordan <mjordan@digium.com>
Definition in file pjsip/dialplan_functions.c.
Function Documentation
channel_read_pjsip()
static int channel_read_pjsip (struct ast_channel * chan, const char * type, const char * field, char * buf, size_t buflen) static
Definition at line 760 of file pjsip/dialplan_functions.c.
References ao2_cleanup, ast_channel_name(), ast_channel_tech_pvt(), ast_copy_pj_str(), ast_copy_string(), ast_escape_quoted(), ast_log, AST_LOG_WARNING, ast_sip_get_pjsip_endpoint(), ast_sip_session_get_datastore(), ast_strdupa, ast_strlen_zero, ast_sip_session::inv_session, transport_info_data::local_addr, LOG_WARNING, NULL, pool, print_escaped_uri(), RAII_VAR, transport_info_data::remote_addr, ast_sip_session::request_uri, ast_sip_channel_pvt::session, ast_sip_session::t38state, and t38state_to_string.
Referenced by read_pjsip().
 {
    struct ast_sip_channel_pvt *channel = ast_channel_tech_pvt(chan);
    char *buf_copy;
    pjsip_dialog *dlg;
    int res = 0;
    if (!channel) {
       ast_log(AST_LOG_WARNING, "Channel %s has no pvt!\n", ast_channel_name(chan));
       return -1;
    }
    dlg = channel->session->inv_session->dlg;
    if (ast_strlen_zero(type)) {
       ast_log(LOG_WARNING, "You must supply a type field for 'pjsip' information\n");
       return -1;
    } else if (!strcmp(type, "call-id")) {
       snprintf(buf, buflen, "%.*s", (int) pj_strlen(&dlg->call_id->id), pj_strbuf(&dlg->call_id->id));
    } else if (!strcmp(type, "secure")) {
 #ifdef HAVE_PJSIP_GET_DEST_INFO
       pjsip_host_info dest;
       pj_pool_t *pool = pjsip_endpt_create_pool(ast_sip_get_pjsip_endpoint(), "secure-check", 128, 128);
       pjsip_get_dest_info(dlg->target, NULL, pool, &dest);
       snprintf(buf, buflen, "%d", dest.flag & PJSIP_TRANSPORT_SECURE ? 1 : 0);
       pjsip_endpt_release_pool(ast_sip_get_pjsip_endpoint(), pool);
 #else
       ast_log(LOG_WARNING, "Asterisk has been built against a version of pjproject which does not have the required functionality to support the 'secure' argument. Please upgrade to version 2.3 or later.\n");
       return -1;
 #endif
    } else if (!strcmp(type, "target_uri")) {
       res = print_escaped_uri(chan, type, PJSIP_URI_IN_REQ_URI, dlg->target, buf,
          buflen);
    } else if (!strcmp(type, "local_uri")) {
       res = print_escaped_uri(chan, type, PJSIP_URI_IN_FROMTO_HDR, dlg->local.info->uri,
          buf, buflen);
    } else if (!strcmp(type, "local_tag")) {
       ast_copy_pj_str(buf, &dlg->local.info->tag, buflen);
       buf_copy = ast_strdupa(buf);
       ast_escape_quoted(buf_copy, buf, buflen);
    } else if (!strcmp(type, "remote_uri")) {
       res = print_escaped_uri(chan, type, PJSIP_URI_IN_FROMTO_HDR,
          dlg->remote.info->uri, buf, buflen);
    } else if (!strcmp(type, "remote_tag")) {
       ast_copy_pj_str(buf, &dlg->remote.info->tag, buflen);
       buf_copy = ast_strdupa(buf);
       ast_escape_quoted(buf_copy, buf, buflen);
    } else if (!strcmp(type, "request_uri")) {
       if (channel->session->request_uri) {
          res = print_escaped_uri(chan, type, PJSIP_URI_IN_REQ_URI,
             channel->session->request_uri, buf, buflen);
       }
    } else if (!strcmp(type, "t38state")) {
       ast_copy_string(buf, t38state_to_string[channel->session->t38state], buflen);
    } else if (!strcmp(type, "local_addr")) {
       RAII_VAR(struct ast_datastore *, datastore, NULL, ao2_cleanup);
       struct transport_info_data *transport_data;
       datastore = ast_sip_session_get_datastore(channel->session, "transport_info");
       if (!datastore) {
          ast_log(AST_LOG_WARNING, "No transport information for channel %s\n", ast_channel_name(chan));
          return -1;
       }
       transport_data = datastore->data;
       if (pj_sockaddr_has_addr(&transport_data->local_addr)) {
          pj_sockaddr_print(&transport_data->local_addr, buf, buflen, 3);
       }
    } else if (!strcmp(type, "remote_addr")) {
       RAII_VAR(struct ast_datastore *, datastore, NULL, ao2_cleanup);
       struct transport_info_data *transport_data;
       datastore = ast_sip_session_get_datastore(channel->session, "transport_info");
       if (!datastore) {
          ast_log(AST_LOG_WARNING, "No transport information for channel %s\n", ast_channel_name(chan));
          return -1;
       }
       transport_data = datastore->data;
       if (pj_sockaddr_has_addr(&transport_data->remote_addr)) {
          pj_sockaddr_print(&transport_data->remote_addr, buf, buflen, 3);
       }
    } else {
       ast_log(AST_LOG_WARNING, "Unrecognized argument '%s' for 'pjsip' information\n", type);
       return -1;
    }
    return res;
 }
channel_read_rtcp()
static int channel_read_rtcp (struct ast_channel * chan, const char * type, const char * field, char * buf, size_t buflen) static
Definition at line 619 of file pjsip/dialplan_functions.c.
References ast_sip_session::active_media_state, ast_channel_name(), ast_channel_tech_pvt(), ast_log, AST_LOG_WARNING, AST_MEDIA_TYPE_AUDIO, AST_MEDIA_TYPE_VIDEO, ast_rtp_instance_get_quality(), ast_rtp_instance_get_stats(), AST_RTP_INSTANCE_STAT_ALL, AST_RTP_INSTANCE_STAT_FIELD_QUALITY, AST_RTP_INSTANCE_STAT_FIELD_QUALITY_JITTER, AST_RTP_INSTANCE_STAT_FIELD_QUALITY_LOSS, AST_RTP_INSTANCE_STAT_FIELD_QUALITY_RTT, ast_strlen_zero, ast_sip_session_media_state::default_session, ast_rtp_instance_stats::local_maxjitter, ast_rtp_instance_stats::local_maxrxploss, ast_rtp_instance_stats::local_minjitter, ast_rtp_instance_stats::local_minrxploss, ast_rtp_instance_stats::local_normdevjitter, ast_rtp_instance_stats::local_normdevrxploss, ast_rtp_instance_stats::local_ssrc, ast_rtp_instance_stats::local_stdevjitter, ast_rtp_instance_stats::local_stdevrxploss, ast_rtp_instance_stats::maxrtt, ast_rtp_instance_stats::minrtt, name, ast_rtp_instance_stats::normdevrtt, NULL, ast_rtp_instance_stats::remote_maxjitter, ast_rtp_instance_stats::remote_maxrxploss, ast_rtp_instance_stats::remote_minjitter, ast_rtp_instance_stats::remote_minrxploss, ast_rtp_instance_stats::remote_normdevjitter, ast_rtp_instance_stats::remote_normdevrxploss, ast_rtp_instance_stats::remote_ssrc, ast_rtp_instance_stats::remote_stdevjitter, ast_rtp_instance_stats::remote_stdevrxploss, ast_sip_session_media::rtp, ast_rtp_instance_stats::rtt, ast_rtp_instance_stats::rxcount, ast_rtp_instance_stats::rxjitter, ast_rtp_instance_stats::rxploss, S_OR, session, ast_sip_channel_pvt::session, ast_rtp_instance_stats::stdevrtt, ast_rtp_instance_stats::txcount, ast_rtp_instance_stats::txjitter, ast_rtp_instance_stats::txploss, and type.
Referenced by read_pjsip().
 {
    struct ast_sip_channel_pvt *channel = ast_channel_tech_pvt(chan);
    struct ast_sip_session *session;
    struct ast_sip_session_media *media;
    if (!channel) {
       ast_log(AST_LOG_WARNING, "Channel %s has no pvt!\n", ast_channel_name(chan));
       return -1;
    }
    session = channel->session;
    if (!session) {
       ast_log(AST_LOG_WARNING, "Channel %s has no session!\n", ast_channel_name(chan));
       return -1;
    }
    if (ast_strlen_zero(type)) {
       ast_log(AST_LOG_WARNING, "You must supply a type field for 'rtcp' information\n");
       return -1;
    }
    if (ast_strlen_zero(field) || !strcmp(field, "audio")) {
       media = session->active_media_state->default_session[AST_MEDIA_TYPE_AUDIO];
    } else if (!strcmp(field, "video")) {
       media = session->active_media_state->default_session[AST_MEDIA_TYPE_VIDEO];
    } else {
       ast_log(AST_LOG_WARNING, "Unknown media type field '%s' for 'rtcp' information\n", field);
       return -1;
    }
    if (!media || !media->rtp) {
       ast_log(AST_LOG_WARNING, "Channel %s has no %s media/RTP session\n",
          ast_channel_name(chan), S_OR(field, "audio"));
       return -1;
    }
    if (!strncasecmp(type, "all", 3)) {
       enum ast_rtp_instance_stat_field stat_field = AST_RTP_INSTANCE_STAT_FIELD_QUALITY;
       if (!strcasecmp(type, "all_jitter")) {
          stat_field = AST_RTP_INSTANCE_STAT_FIELD_QUALITY_JITTER;
       } else if (!strcasecmp(type, "all_rtt")) {
          stat_field = AST_RTP_INSTANCE_STAT_FIELD_QUALITY_RTT;
       } else if (!strcasecmp(type, "all_loss")) {
          stat_field = AST_RTP_INSTANCE_STAT_FIELD_QUALITY_LOSS;
       }
       if (!ast_rtp_instance_get_quality(media->rtp, stat_field, buf, buflen)) {
          ast_log(AST_LOG_WARNING, "Unable to retrieve 'rtcp' statistics for %s\n", ast_channel_name(chan));
          return -1;
       }
    } else {
       struct ast_rtp_instance_stats stats;
       int i;
       struct {
          const char *name;
          enum { INT, DBL } type;
          union {
             unsigned int *i4;
             double *d8;
          };
       } lookup[] = {
          { "txcount",               INT, { .i4 = &stats.txcount, }, },
          { "rxcount",               INT, { .i4 = &stats.rxcount, }, },
          { "txjitter",              DBL, { .d8 = &stats.txjitter, }, },
          { "rxjitter",              DBL, { .d8 = &stats.rxjitter, }, },
          { "remote_maxjitter",      DBL, { .d8 = &stats.remote_maxjitter, }, },
          { "remote_minjitter",      DBL, { .d8 = &stats.remote_minjitter, }, },
          { "remote_normdevjitter",  DBL, { .d8 = &stats.remote_normdevjitter, }, },
          { "remote_stdevjitter",    DBL, { .d8 = &stats.remote_stdevjitter, }, },
          { "local_maxjitter",       DBL, { .d8 = &stats.local_maxjitter, }, },
          { "local_minjitter",       DBL, { .d8 = &stats.local_minjitter, }, },
          { "local_normdevjitter",   DBL, { .d8 = &stats.local_normdevjitter, }, },
          { "local_stdevjitter",     DBL, { .d8 = &stats.local_stdevjitter, }, },
          { "txploss",               INT, { .i4 = &stats.txploss, }, },
          { "rxploss",               INT, { .i4 = &stats.rxploss, }, },
          { "remote_maxrxploss",     DBL, { .d8 = &stats.remote_maxrxploss, }, },
          { "remote_minrxploss",     DBL, { .d8 = &stats.remote_minrxploss, }, },
          { "remote_normdevrxploss", DBL, { .d8 = &stats.remote_normdevrxploss, }, },
          { "remote_stdevrxploss",   DBL, { .d8 = &stats.remote_stdevrxploss, }, },
          { "local_maxrxploss",      DBL, { .d8 = &stats.local_maxrxploss, }, },
          { "local_minrxploss",      DBL, { .d8 = &stats.local_minrxploss, }, },
          { "local_normdevrxploss",  DBL, { .d8 = &stats.local_normdevrxploss, }, },
          { "local_stdevrxploss",    DBL, { .d8 = &stats.local_stdevrxploss, }, },
          { "rtt",                   DBL, { .d8 = &stats.rtt, }, },
          { "maxrtt",                DBL, { .d8 = &stats.maxrtt, }, },
          { "minrtt",                DBL, { .d8 = &stats.minrtt, }, },
          { "normdevrtt",            DBL, { .d8 = &stats.normdevrtt, }, },
          { "stdevrtt",              DBL, { .d8 = &stats.stdevrtt, }, },
          { "local_ssrc",            INT, { .i4 = &stats.local_ssrc, }, },
          { "remote_ssrc",           INT, { .i4 = &stats.remote_ssrc, }, },
          { NULL, },
       };
       if (ast_rtp_instance_get_stats(media->rtp, &stats, AST_RTP_INSTANCE_STAT_ALL)) {
          ast_log(AST_LOG_WARNING, "Unable to retrieve 'rtcp' statistics for %s\n", ast_channel_name(chan));
          return -1;
       }
       for (i = 0; !ast_strlen_zero(lookup[i].name); i++) {
          if (!strcasecmp(type, lookup[i].name)) {
             if (lookup[i].type == INT) {
                snprintf(buf, buflen, "%u", *lookup[i].i4);
             } else {
                snprintf(buf, buflen, "%f", *lookup[i].d8);
             }
             return 0;
          }
       }
       ast_log(AST_LOG_WARNING, "Unrecognized argument '%s' for 'rtcp' information\n", type);
       return -1;
    }
    return 0;
 }
channel_read_rtp()
static int channel_read_rtp (struct ast_channel * chan, const char * type, const char * field, char * buf, size_t buflen) static
Definition at line 552 of file pjsip/dialplan_functions.c.
References ast_sip_session::active_media_state, ast_channel_name(), ast_channel_tech_pvt(), ast_copy_string(), ast_log, AST_LOG_WARNING, AST_MEDIA_TYPE_AUDIO, AST_MEDIA_TYPE_VIDEO, ast_rtp_instance_get_local_address(), ast_rtp_instance_get_remote_address, ast_sockaddr_stringify(), AST_SRTP_CRYPTO_OFFER_OK, ast_strlen_zero, ast_test_flag, ast_sip_session_media_state::default_session, ast_sip_session_media::direct_media_addr, ast_sip_session_media::remotely_held, ast_sip_session_media::rtp, S_OR, session, ast_sip_channel_pvt::session, and ast_sip_session_media::srtp.
Referenced by read_pjsip().
 {
    struct ast_sip_channel_pvt *channel = ast_channel_tech_pvt(chan);
    struct ast_sip_session *session;
    struct ast_sip_session_media *media;
    struct ast_sockaddr addr;
    if (!channel) {
       ast_log(AST_LOG_WARNING, "Channel %s has no pvt!\n", ast_channel_name(chan));
       return -1;
    }
    session = channel->session;
    if (!session) {
       ast_log(AST_LOG_WARNING, "Channel %s has no session!\n", ast_channel_name(chan));
       return -1;
    }
    if (ast_strlen_zero(type)) {
       ast_log(AST_LOG_WARNING, "You must supply a type field for 'rtp' information\n");
       return -1;
    }
    if (ast_strlen_zero(field) || !strcmp(field, "audio")) {
       media = session->active_media_state->default_session[AST_MEDIA_TYPE_AUDIO];
    } else if (!strcmp(field, "video")) {
       media = session->active_media_state->default_session[AST_MEDIA_TYPE_VIDEO];
    } else {
       ast_log(AST_LOG_WARNING, "Unknown media type field '%s' for 'rtp' information\n", field);
       return -1;
    }
    if (!media || !media->rtp) {
       ast_log(AST_LOG_WARNING, "Channel %s has no %s media/RTP session\n",
          ast_channel_name(chan), S_OR(field, "audio"));
       return -1;
    }
    if (!strcmp(type, "src")) {
       ast_rtp_instance_get_local_address(media->rtp, &addr);
       ast_copy_string(buf, ast_sockaddr_stringify(&addr), buflen);
    } else if (!strcmp(type, "dest")) {
       ast_rtp_instance_get_remote_address(media->rtp, &addr);
       ast_copy_string(buf, ast_sockaddr_stringify(&addr), buflen);
    } else if (!strcmp(type, "direct")) {
       ast_copy_string(buf, ast_sockaddr_stringify(&media->direct_media_addr), buflen);
    } else if (!strcmp(type, "secure")) {
       if (media->srtp) {
          struct ast_sdp_srtp *srtp = media->srtp;
          int flag = ast_test_flag(srtp, AST_SRTP_CRYPTO_OFFER_OK);
          snprintf(buf, buflen, "%d", flag ? 1 : 0);
       } else {
          snprintf(buf, buflen, "%d", 0);
       }
    } else if (!strcmp(type, "hold")) {
       snprintf(buf, buflen, "%d", media->remotely_held ? 1 : 0);
    } else {
       ast_log(AST_LOG_WARNING, "Unknown type field '%s' specified for 'rtp' information\n", type);
       return -1;
    }
    return 0;
 }
dtmf_mode_refresh_cb()
static int dtmf_mode_refresh_cb (void * obj) static
Definition at line 1513 of file pjsip/dialplan_functions.c.
References ast_channel_name(), ast_debug, ast_sip_session_refresh(), ast_sip_session_regenerate_answer(), ast_sip_session::channel, ast_sip_session::inv_session, refresh_data::method, NULL, refresh_data::session, and sip_session_response_cb().
Referenced by pjsip_acf_dtmf_mode_write().
 {
    struct refresh_data *data = obj;
    if (data->session->inv_session->state == PJSIP_INV_STATE_CONFIRMED) {
       ast_debug(3, "Changing DTMF mode on channel %s after OFFER/ANSWER completion. Sending session refresh\n", ast_channel_name(data->session->channel));
       ast_sip_session_refresh(data->session, NULL, NULL,
          sip_session_response_cb, data->method, 1, NULL);
    } else if (data->session->inv_session->state == PJSIP_INV_STATE_INCOMING) {
       ast_debug(3, "Changing DTMF mode on channel %s during OFFER/ANSWER exchange. Updating SDP answer\n", ast_channel_name(data->session->channel));
       ast_sip_session_regenerate_answer(data->session, NULL);
    }
    return 0;
 }
media_offer_read_av()
static int media_offer_read_av (struct ast_sip_session * session, char * buf, size_t len, enum ast_media_type media_type) static
Definition at line 1232 of file pjsip/dialplan_functions.c.
References ao2_ref, ast_format_cap_count(), ast_format_cap_get_format(), ast_format_get_name(), ast_stream_get_formats(), ast_stream_get_state(), ast_stream_get_type(), AST_STREAM_STATE_REMOVED, ast_stream_topology_clone(), ast_stream_topology_get_count(), ast_stream_topology_get_stream(), ast_sip_session::endpoint, ast_sip_session::inv_session, ast_sip_endpoint::media, session_refresh_state::media_state, NULL, ast_sip_session::pending_media_state, session_refresh_state_get_or_alloc(), state, ast_sip_session_media_state::topology, and ast_sip_endpoint_media_configuration::topology.
Referenced by pjsip_acf_media_offer_read().
 {
    struct ast_stream_topology *topology;
    int idx;
    struct ast_stream *stream = NULL;
    const struct ast_format_cap *caps;
    size_t accum = 0;
    if (session->inv_session->dlg->state == PJSIP_DIALOG_STATE_ESTABLISHED) {
       struct session_refresh_state *state;
       /* As we've already answered we need to store our media state until we are ready to send it */
       state = session_refresh_state_get_or_alloc(session);
       if (!state) {
          return -1;
       }
       topology = state->media_state->topology;
    } else {
       /* The session is not yet up so we are initially answering or offering */
       if (!session->pending_media_state->topology) {
          session->pending_media_state->topology = ast_stream_topology_clone(session->endpoint->media.topology);
          if (!session->pending_media_state->topology) {
             return -1;
          }
       }
       topology = session->pending_media_state->topology;
    }
    /* Find the first suitable stream */
    for (idx = 0; idx < ast_stream_topology_get_count(topology); ++idx) {
       stream = ast_stream_topology_get_stream(topology, idx);
       if (ast_stream_get_type(stream) != media_type ||
          ast_stream_get_state(stream) == AST_STREAM_STATE_REMOVED) {
          stream = NULL;
          continue;
       }
       break;
    }
    /* If no suitable stream then exit early */
    if (!stream) {
       buf[0] = '\0';
       return 0;
    }
    caps = ast_stream_get_formats(stream);
    /* Note: buf is not terminated while the string is being built. */
    for (idx = 0; idx < ast_format_cap_count(caps); ++idx) {
       struct ast_format *fmt;
       size_t size;
       fmt = ast_format_cap_get_format(caps, idx);
       /* Add one for a comma or terminator */
       size = strlen(ast_format_get_name(fmt)) + 1;
       if (len < size) {
          ao2_ref(fmt, -1);
          break;
       }
       /* Append the format name */
       strcpy(buf + accum, ast_format_get_name(fmt));/* Safe */
       ao2_ref(fmt, -1);
       accum += size;
       len -= size;
       /* The last comma on the built string will be set to the terminator. */
       buf[accum - 1] = ',';
    }
    /* Remove the trailing comma or terminate an empty buffer. */
    buf[accum ? accum - 1 : 0] = '\0';
    return 0;
 }
media_offer_write_av()
static int media_offer_write_av (void * obj) static
Definition at line 1318 of file pjsip/dialplan_functions.c.
References ao2_ref, ast_format_cap_alloc, ast_format_cap_append_from_cap(), AST_FORMAT_CAP_FLAG_DEFAULT, ast_format_cap_remove_by_type(), ast_format_cap_update_by_allow_disallow(), AST_MEDIA_TYPE_UNKNOWN, ast_stream_get_formats(), ast_stream_set_formats(), ast_stream_set_metadata(), ast_stream_topology_clone(), ast_stream_topology_get_first_stream_by_type(), ast_sip_session::endpoint, ast_sip_session::inv_session, ast_sip_endpoint::media, session_refresh_state::media_state, media_offer_data::media_type, ast_sip_session::pending_media_state, media_offer_data::session, session_refresh_state_get_or_alloc(), state, ast_sip_session_media_state::topology, ast_sip_endpoint_media_configuration::topology, and media_offer_data::value.
Referenced by pjsip_acf_media_offer_write().
 {
    struct media_offer_data *data = obj;
    struct ast_stream_topology *topology;
    struct ast_stream *stream;
    struct ast_format_cap *caps;
    if (data->session->inv_session->dlg->state == PJSIP_DIALOG_STATE_ESTABLISHED) {
       struct session_refresh_state *state;
       /* As we've already answered we need to store our media state until we are ready to send it */
       state = session_refresh_state_get_or_alloc(data->session);
       if (!state) {
          return -1;
       }
       topology = state->media_state->topology;
    } else {
       /* The session is not yet up so we are initially answering or offering */
       if (!data->session->pending_media_state->topology) {
          data->session->pending_media_state->topology = ast_stream_topology_clone(data->session->endpoint->media.topology);
          if (!data->session->pending_media_state->topology) {
             return -1;
          }
       }
       topology = data->session->pending_media_state->topology;
    }
    /* XXX This method won't work when it comes time to do multistream support. The proper way to do this
     * will either be to
     * a) Alter all media streams of a particular type.
     * b) Change the dialplan function to be able to specify which stream to alter and alter only that
     * one stream
     */
    stream = ast_stream_topology_get_first_stream_by_type(topology, data->media_type);
    if (!stream) {
       return 0;
    }
    caps = ast_format_cap_alloc(AST_FORMAT_CAP_FLAG_DEFAULT);
    if (!caps) {
       return -1;
    }
    ast_format_cap_append_from_cap(caps, ast_stream_get_formats(stream),
       AST_MEDIA_TYPE_UNKNOWN);
    ast_format_cap_remove_by_type(caps, data->media_type);
    ast_format_cap_update_by_allow_disallow(caps, data->value, 1);
    ast_stream_set_formats(stream, caps);
    ast_stream_set_metadata(stream, "pjsip_session_refresh", "force");
    ao2_ref(caps, -1);
    return 0;
 }
parse_uri_cb()
static int parse_uri_cb (void * data) static
Definition at line 1121 of file pjsip/dialplan_functions.c.
References args, ast_copy_pj_str(), ast_log, AST_LOG_WARNING, ast_sip_get_pjsip_endpoint(), parse_uri_args::buf, parse_uri_args::buflen, LOG_ERROR, LOG_WARNING, pool, parse_uri_args::ret, tmp(), parse_uri_args::type, and parse_uri_args::uri.
Referenced by pjsip_acf_parse_uri_read().
 {
    struct parse_uri_args *args = data;
    pj_pool_t *pool;
    pjsip_name_addr *uri;
    pjsip_sip_uri *sip_uri;
    pj_str_t tmp;
    args->ret = 0;
    pool = pjsip_endpt_create_pool(ast_sip_get_pjsip_endpoint(), "ParseUri", 128, 128);
    if (!pool) {
       ast_log(LOG_ERROR, "Failed to allocate ParseUri endpoint pool.\n");
       args->ret = -1;
       return 0;
    }
    pj_strdup2_with_null(pool, &tmp, args->uri);
    uri = (pjsip_name_addr *)pjsip_parse_uri(pool, tmp.ptr, tmp.slen, PJSIP_PARSE_URI_AS_NAMEADDR);
    if (!uri || (!PJSIP_URI_SCHEME_IS_SIP(uri) && !PJSIP_URI_SCHEME_IS_SIPS(uri))) {
       ast_log(LOG_WARNING, "Failed to parse URI '%s'\n", args->uri);
       pjsip_endpt_release_pool(ast_sip_get_pjsip_endpoint(), pool);
       args->ret = -1;
       return 0;
    }
    if (!strcmp(args->type, "scheme")) {
       ast_copy_pj_str(args->buf, pjsip_uri_get_scheme(uri), args->buflen);
       pjsip_endpt_release_pool(ast_sip_get_pjsip_endpoint(), pool);
       return 0;
    } else if (!strcmp(args->type, "display")) {
       ast_copy_pj_str(args->buf, &uri->display, args->buflen);
       pjsip_endpt_release_pool(ast_sip_get_pjsip_endpoint(), pool);
       return 0;
    }
    sip_uri = pjsip_uri_get_uri(uri);
    if (!sip_uri) {
       ast_log(LOG_ERROR, "Failed to get an URI object for '%s'\n", args->uri);
       pjsip_endpt_release_pool(ast_sip_get_pjsip_endpoint(), pool);
       args->ret = -1;
       return 0;
    }
    if (!strcmp(args->type, "user")) {
       ast_copy_pj_str(args->buf, &sip_uri->user, args->buflen);
    } else if (!strcmp(args->type, "passwd")) {
       ast_copy_pj_str(args->buf, &sip_uri->passwd, args->buflen);
    } else if (!strcmp(args->type, "host")) {
       ast_copy_pj_str(args->buf, &sip_uri->host, args->buflen);
    } else if (!strcmp(args->type, "port")) {
       snprintf(args->buf, args->buflen, "%d", sip_uri->port);
    } else if (!strcmp(args->type, "user_param")) {
       ast_copy_pj_str(args->buf, &sip_uri->user_param, args->buflen);
    } else if (!strcmp(args->type, "method_param")) {
       ast_copy_pj_str(args->buf, &sip_uri->method_param, args->buflen);
    } else if (!strcmp(args->type, "transport_param")) {
       ast_copy_pj_str(args->buf, &sip_uri->transport_param, args->buflen);
    } else if (!strcmp(args->type, "ttl_param")) {
       snprintf(args->buf, args->buflen, "%d", sip_uri->ttl_param);
    } else if (!strcmp(args->type, "lr_param")) {
       snprintf(args->buf, args->buflen, "%d", sip_uri->lr_param);
    } else if (!strcmp(args->type, "maddr_param")) {
       ast_copy_pj_str(args->buf, &sip_uri->maddr_param, args->buflen);
    } else {
       ast_log(AST_LOG_WARNING, "Unknown type part '%s' specified\n", args->type);
       pjsip_endpt_release_pool(ast_sip_get_pjsip_endpoint(), pool);
       args->ret = -1;
       return 0;
    }
    pjsip_endpt_release_pool(ast_sip_get_pjsip_endpoint(), pool);
    return 0;
 }
pjsip_acf_channel_read()
int pjsip_acf_channel_read (struct ast_channel * chan, const char * cmd, char * data, char * buf, size_t len)
CHANNEL function read callback.
Parameters
chan The channel the function is called on
cmd The name of the function
data Arguments passed to the function
buf Out buffer that should be populated with the data
len Size of the buffer
Return values
0 on success
-1 on failure
Definition at line 916 of file pjsip/dialplan_functions.c.
References ao2_bump, ao2_ref, args, AST_APP_ARG, ast_channel_lock, ast_channel_name(), ast_channel_tech(), ast_channel_tech_pvt(), ast_channel_unlock, AST_DECLARE_APP_ARGS, ast_log, ast_sip_push_task_wait_serializer(), AST_STANDARD_APP_ARGS, ast_strdupa, ast_strlen_zero, buf, pjsip_func_args::buf, pjsip_func_args::field, pjsip_func_args::len, len(), LOG_ERROR, LOG_WARNING, pjsip_func_args::param, parse(), read_pjsip(), pjsip_func_args::ret, ast_sip_session::serializer, ast_sip_channel_pvt::session, pjsip_func_args::session, type, and pjsip_func_args::type.
 {
    struct pjsip_func_args func_args = { 0, };
    struct ast_sip_channel_pvt *channel;
    char *parse = ast_strdupa(data);
    AST_DECLARE_APP_ARGS(args,
       AST_APP_ARG(param);
       AST_APP_ARG(type);
       AST_APP_ARG(field);
    );
    if (!chan) {
       ast_log(LOG_WARNING, "No channel was provided to %s function.\n", cmd);
       return -1;
    }
    /* Check for zero arguments */
    if (ast_strlen_zero(parse)) {
       ast_log(LOG_ERROR, "Cannot call %s without arguments\n", cmd);
       return -1;
    }
    AST_STANDARD_APP_ARGS(args, parse);
    ast_channel_lock(chan);
    /* Sanity check */
    if (strcmp(ast_channel_tech(chan)->type, "PJSIP")) {
       ast_log(LOG_WARNING, "Cannot call %s on a non-PJSIP channel\n", cmd);
       ast_channel_unlock(chan);
       return 0;
    }
    channel = ast_channel_tech_pvt(chan);
    if (!channel) {
       ast_log(LOG_WARNING, "Channel %s has no pvt!\n", ast_channel_name(chan));
       ast_channel_unlock(chan);
       return -1;
    }
    if (!channel->session) {
       ast_log(LOG_WARNING, "Channel %s has no session\n", ast_channel_name(chan));
       ast_channel_unlock(chan);
       return -1;
    }
    func_args.session = ao2_bump(channel->session);
    ast_channel_unlock(chan);
    memset(buf, 0, len);
    func_args.param = args.param;
    func_args.type = args.type;
    func_args.field = args.field;
    func_args.buf = buf;
    func_args.len = len;
    if (ast_sip_push_task_wait_serializer(func_args.session->serializer, read_pjsip, &func_args)) {
       ast_log(LOG_WARNING, "Unable to read properties of channel %s: failed to push task\n", ast_channel_name(chan));
       ao2_ref(func_args.session, -1);
       return -1;
    }
    ao2_ref(func_args.session, -1);
    return func_args.ret;
 }
pjsip_acf_dial_contacts_read()
int pjsip_acf_dial_contacts_read (struct ast_channel * chan, const char * cmd, char * data, char * buf, size_t len)
PJSIP_DIAL_CONTACTS function read callback.
Parameters
chan The channel the function is called on
cmd The name of the function
data Arguments passed to the function
buf Out buffer that should be populated with the data
len Size of the buffer
Return values
0 on success
-1 on failure
Definition at line 983 of file pjsip/dialplan_functions.c.
References ao2_cleanup, ao2_container_count(), ao2_iterator_destroy(), ao2_iterator_init(), ao2_iterator_next, ao2_ref, ast_sip_contact::aor, args, AST_APP_ARG, ast_copy_string(), AST_DECLARE_APP_ARGS, ast_free_ptr(), ast_log, AST_SIP_CONTACT_FILTER_REACHABLE, ast_sip_get_sorcery(), ast_sip_location_retrieve_aor(), ast_sip_location_retrieve_aor_contacts_filtered(), ast_sorcery_retrieve_by_id(), AST_STANDARD_APP_ARGS, ast_str_append(), ast_str_buffer(), ast_str_create, ast_str_strlen(), ast_str_truncate(), ast_strdupa, ast_strip(), ast_strlen_zero, LOG_WARNING, NULL, RAII_VAR, S_OR, strsep(), and ast_sip_contact::uri.
 {
    RAII_VAR(struct ast_sip_endpoint *, endpoint, NULL, ao2_cleanup);
    RAII_VAR(struct ast_str *, dial, NULL, ast_free_ptr);
    const char *aor_name;
    char *rest;
    AST_DECLARE_APP_ARGS(args,
       AST_APP_ARG(endpoint_name);
       AST_APP_ARG(aor_name);
       AST_APP_ARG(request_user);
    );
    AST_STANDARD_APP_ARGS(args, data);
    if (ast_strlen_zero(args.endpoint_name)) {
       ast_log(LOG_WARNING, "An endpoint name must be specified when using the '%s' dialplan function\n", cmd);
       return -1;
    } else if (!(endpoint = ast_sorcery_retrieve_by_id(ast_sip_get_sorcery(), "endpoint", args.endpoint_name))) {
       ast_log(LOG_WARNING, "Specified endpoint '%s' was not found\n", args.endpoint_name);
       return -1;
    }
    aor_name = S_OR(args.aor_name, endpoint->aors);
    if (ast_strlen_zero(aor_name)) {
       ast_log(LOG_WARNING, "No AOR has been provided and no AORs are configured on endpoint '%s'\n", args.endpoint_name);
       return -1;
    } else if (!(dial = ast_str_create(len))) {
       ast_log(LOG_WARNING, "Could not get enough buffer space for dialing contacts\n");
       return -1;
    } else if (!(rest = ast_strdupa(aor_name))) {
       ast_log(LOG_WARNING, "Could not duplicate provided AORs\n");
       return -1;
    }
    while ((aor_name = ast_strip(strsep(&rest, ",")))) {
       RAII_VAR(struct ast_sip_aor *, aor, ast_sip_location_retrieve_aor(aor_name), ao2_cleanup);
       RAII_VAR(struct ao2_container *, contacts, NULL, ao2_cleanup);
       struct ao2_iterator it_contacts;
       struct ast_sip_contact *contact;
       if (!aor) {
          /* If the AOR provided is not found skip it, there may be more */
          continue;
       } else if (!(contacts = ast_sip_location_retrieve_aor_contacts_filtered(aor, AST_SIP_CONTACT_FILTER_REACHABLE))) {
          /* No contacts are available, skip it as well */
          continue;
       } else if (!ao2_container_count(contacts)) {
          /* We were given a container but no contacts are in it... */
          continue;
       }
       it_contacts = ao2_iterator_init(contacts, 0);
       for (; (contact = ao2_iterator_next(&it_contacts)); ao2_ref(contact, -1)) {
          ast_str_append(&dial, -1, "PJSIP/");
          if (!ast_strlen_zero(args.request_user)) {
             ast_str_append(&dial, -1, "%s@", args.request_user);
          }
          ast_str_append(&dial, -1, "%s/%s&", args.endpoint_name, contact->uri);
       }
       ao2_iterator_destroy(&it_contacts);
    }
    /* Trim the '&' at the end off */
    ast_str_truncate(dial, ast_str_strlen(dial) - 1);
    ast_copy_string(buf, ast_str_buffer(dial), len);
    return 0;
 }
pjsip_acf_dtmf_mode_read()
int pjsip_acf_dtmf_mode_read (struct ast_channel * chan, const char * cmd, char * data, char * buf, size_t len)
PJSIP_DTMF_MODE function read callback.
Parameters
chan The channel the function is called on
cmd The name of the function
data Arguments passed to the function
buf Out buffer that should be populated with the data
len Size of the buffer
Return values
0 on success
-1 on failure
Definition at line 1429 of file pjsip/dialplan_functions.c.
References ast_channel_lock, ast_channel_name(), ast_channel_tech(), ast_channel_tech_pvt(), ast_channel_unlock, ast_log, ast_sip_dtmf_to_str(), ast_sip_session::dtmf, LOG_WARNING, ast_sip_channel_pvt::session, and type.
 {
    struct ast_sip_channel_pvt *channel;
    if (!chan) {
       ast_log(LOG_WARNING, "No channel was provided to %s function.\n", cmd);
       return -1;
    }
    ast_channel_lock(chan);
    if (strcmp(ast_channel_tech(chan)->type, "PJSIP")) {
       ast_log(LOG_WARNING, "Cannot call %s on a non-PJSIP channel\n", cmd);
       ast_channel_unlock(chan);
       return -1;
    }
    channel = ast_channel_tech_pvt(chan);
    if (ast_sip_dtmf_to_str(channel->session->dtmf, buf, len) < 0) {
       ast_log(LOG_WARNING, "Unknown DTMF mode %d on PJSIP channel %s\n", channel->session->dtmf, ast_channel_name(chan));
       ast_channel_unlock(chan);
       return -1;
    }
    ast_channel_unlock(chan);
    return 0;
 }
pjsip_acf_dtmf_mode_write()
int pjsip_acf_dtmf_mode_write (struct ast_channel * chan, const char * cmd, char * data, const char * value)
PJSIP_DTMF_MODE function write callback.
Parameters
chan The channel the function is called on
cmd The name of the function
data Arguments passed to the function
value Value to be set by the function
Return values
0 on success
-1 on failure
Definition at line 1530 of file pjsip/dialplan_functions.c.
References ast_sip_session::active_media_state, ast_channel_lock, ast_channel_name(), ast_channel_tech(), ast_channel_tech_pvt(), ast_channel_unlock, ast_dsp_free(), ast_dsp_get_features(), ast_dsp_new(), ast_dsp_set_features(), ast_log, AST_MEDIA_TYPE_AUDIO, AST_RTP_DTMF_MODE_INBAND, AST_RTP_DTMF_MODE_NONE, AST_RTP_DTMF_MODE_RFC2833, ast_rtp_instance_dtmf_mode_get(), ast_rtp_instance_dtmf_mode_set(), ast_rtp_instance_set_prop(), AST_RTP_PROPERTY_DTMF, AST_SIP_DTMF_AUTO, AST_SIP_DTMF_AUTO_INFO, AST_SIP_DTMF_INBAND, AST_SIP_DTMF_INFO, AST_SIP_DTMF_NONE, AST_SIP_DTMF_RFC_4733, ast_sip_push_task_wait_serializer(), AST_SIP_SESSION_REFRESH_METHOD_INVITE, ast_sip_str_to_dtmf(), ast_sip_session_media_state::default_session, ast_sip_session::dsp, DSP_FEATURE_DIGIT_DETECT, ast_sip_session::dtmf, dtmf_mode_refresh_cb(), LOG_WARNING, refresh_data::method, NULL, ast_sip_session_media::rtp, ast_sip_session::serializer, ast_sip_channel_pvt::session, refresh_data::session, and type.
 {
    struct ast_sip_channel_pvt *channel;
    struct ast_sip_session_media *media;
    int dsp_features = 0;
    int dtmf = -1;
    struct refresh_data rdata = {
          .method = AST_SIP_SESSION_REFRESH_METHOD_INVITE,
       };
    if (!chan) {
       ast_log(LOG_WARNING, "No channel was provided to %s function.\n", cmd);
       return -1;
    }
    ast_channel_lock(chan);
    if (strcmp(ast_channel_tech(chan)->type, "PJSIP")) {
       ast_log(LOG_WARNING, "Cannot call %s on a non-PJSIP channel\n", cmd);
       ast_channel_unlock(chan);
       return -1;
    }
    channel = ast_channel_tech_pvt(chan);
    rdata.session = channel->session;
    dtmf = ast_sip_str_to_dtmf(value);
    if (dtmf == -1) {
       ast_log(LOG_WARNING, "Cannot set DTMF mode to '%s' on channel '%s' as value is invalid.\n", value,
          ast_channel_name(chan));
       ast_channel_unlock(chan);
       return -1;
    }
    if (channel->session->dtmf == dtmf) {
       /* DTMF mode unchanged, nothing to do! */
       ast_channel_unlock(chan);
       return 0;
    }
    channel->session->dtmf = dtmf;
    media = channel->session->active_media_state->default_session[AST_MEDIA_TYPE_AUDIO];
    if (media && media->rtp) {
       if (channel->session->dtmf == AST_SIP_DTMF_RFC_4733) {
          ast_rtp_instance_set_prop(media->rtp, AST_RTP_PROPERTY_DTMF, 1);
          ast_rtp_instance_dtmf_mode_set(media->rtp, AST_RTP_DTMF_MODE_RFC2833);
       } else if (channel->session->dtmf == AST_SIP_DTMF_INFO) {
          ast_rtp_instance_set_prop(media->rtp, AST_RTP_PROPERTY_DTMF, 0);
          ast_rtp_instance_dtmf_mode_set(media->rtp, AST_RTP_DTMF_MODE_NONE);
       } else if (channel->session->dtmf == AST_SIP_DTMF_INBAND) {
          ast_rtp_instance_set_prop(media->rtp, AST_RTP_PROPERTY_DTMF, 0);
          ast_rtp_instance_dtmf_mode_set(media->rtp, AST_RTP_DTMF_MODE_INBAND);
       } else if (channel->session->dtmf == AST_SIP_DTMF_NONE) {
          ast_rtp_instance_set_prop(media->rtp, AST_RTP_PROPERTY_DTMF, 0);
          ast_rtp_instance_dtmf_mode_set(media->rtp, AST_RTP_DTMF_MODE_NONE);
       } else if (channel->session->dtmf == AST_SIP_DTMF_AUTO) {
          if (ast_rtp_instance_dtmf_mode_get(media->rtp) != AST_RTP_DTMF_MODE_RFC2833) {
             /* no RFC4733 negotiated, enable inband */
             ast_rtp_instance_dtmf_mode_set(media->rtp, AST_RTP_DTMF_MODE_INBAND);
          }
       } else if (channel->session->dtmf == AST_SIP_DTMF_AUTO_INFO) {
          ast_rtp_instance_set_prop(media->rtp, AST_RTP_PROPERTY_DTMF, 0);
          if (ast_rtp_instance_dtmf_mode_get(media->rtp) == AST_RTP_DTMF_MODE_INBAND) {
             /* if inband, switch to INFO */
             ast_rtp_instance_dtmf_mode_set(media->rtp, AST_RTP_DTMF_MODE_NONE);
          }
       }
    }
    if (channel->session->dsp) {
       dsp_features = ast_dsp_get_features(channel->session->dsp);
    }
    if (channel->session->dtmf == AST_SIP_DTMF_INBAND ||
       channel->session->dtmf == AST_SIP_DTMF_AUTO) {
       dsp_features |= DSP_FEATURE_DIGIT_DETECT;
    } else {
       dsp_features &= ~DSP_FEATURE_DIGIT_DETECT;
    }
    if (dsp_features) {
       if (!channel->session->dsp) {
          if (!(channel->session->dsp = ast_dsp_new())) {
             ast_channel_unlock(chan);
             return 0;
          }
       }
       ast_dsp_set_features(channel->session->dsp, dsp_features);
    } else if (channel->session->dsp) {
       ast_dsp_free(channel->session->dsp);
       channel->session->dsp = NULL;
    }
    ast_channel_unlock(chan);
    return ast_sip_push_task_wait_serializer(channel->session->serializer, dtmf_mode_refresh_cb, &rdata);
 }
pjsip_acf_media_offer_read()
int pjsip_acf_media_offer_read (struct ast_channel * chan, const char * cmd, char * data, char * buf, size_t len)
PJSIP_MEDIA_OFFER function read callback.
Parameters
chan The channel the function is called on
cmd The name of the function
data Arguments passed to the function
buf Out buffer that should be populated with the data
len Size of the buffer
Return values
0 on success
-1 on failure
Definition at line 1372 of file pjsip/dialplan_functions.c.
References ast_channel_tech(), ast_channel_tech_pvt(), ast_log, AST_MEDIA_TYPE_AUDIO, AST_MEDIA_TYPE_VIDEO, LOG_WARNING, media_offer_read_av(), ast_sip_channel_pvt::session, and type.
 {
    struct ast_sip_channel_pvt *channel;
    if (!chan) {
       ast_log(LOG_WARNING, "No channel was provided to %s function.\n", cmd);
       return -1;
    }
    if (strcmp(ast_channel_tech(chan)->type, "PJSIP")) {
       ast_log(LOG_WARNING, "Cannot call %s on a non-PJSIP channel\n", cmd);
       return -1;
    }
    channel = ast_channel_tech_pvt(chan);
    if (!strcmp(data, "audio")) {
       return media_offer_read_av(channel->session, buf, len, AST_MEDIA_TYPE_AUDIO);
    } else if (!strcmp(data, "video")) {
       return media_offer_read_av(channel->session, buf, len, AST_MEDIA_TYPE_VIDEO);
    } else {
       /* Ensure that the buffer is empty */
       buf[0] = '\0';
    }
    return 0;
 }
pjsip_acf_media_offer_write()
int pjsip_acf_media_offer_write (struct ast_channel * chan, const char * cmd, char * data, const char * value)
PJSIP_MEDIA_OFFER function write callback.
Parameters
chan The channel the function is called on
cmd The name of the function
data Arguments passed to the function
value Value to be set by the function
Return values
0 on success
-1 on failure
Definition at line 1400 of file pjsip/dialplan_functions.c.
References ast_channel_tech(), ast_channel_tech_pvt(), ast_log, AST_MEDIA_TYPE_AUDIO, AST_MEDIA_TYPE_VIDEO, ast_sip_push_task_wait_serializer(), LOG_WARNING, media_offer_write_av(), media_offer_data::media_type, ast_sip_session::serializer, ast_sip_channel_pvt::session, media_offer_data::session, type, and media_offer_data::value.
 {
    struct ast_sip_channel_pvt *channel;
    struct media_offer_data mdata = {
       .value = value
    };
    if (!chan) {
       ast_log(LOG_WARNING, "No channel was provided to %s function.\n", cmd);
       return -1;
    }
    if (strcmp(ast_channel_tech(chan)->type, "PJSIP")) {
       ast_log(LOG_WARNING, "Cannot call %s on a non-PJSIP channel\n", cmd);
       return -1;
    }
    channel = ast_channel_tech_pvt(chan);
    mdata.session = channel->session;
    if (!strcmp(data, "audio")) {
       mdata.media_type = AST_MEDIA_TYPE_AUDIO;
    } else if (!strcmp(data, "video")) {
       mdata.media_type = AST_MEDIA_TYPE_VIDEO;
    }
    return ast_sip_push_task_wait_serializer(channel->session->serializer, media_offer_write_av, &mdata);
 }
pjsip_acf_moh_passthrough_read()
int pjsip_acf_moh_passthrough_read (struct ast_channel * chan, const char * cmd, char * data, char * buf, size_t len)
PJSIP_MOH_PASSTHROUGH function read callback.
Parameters
chan The channel the function is called on
cmd The name of the function
data Arguments passed to the function
buf Out buffer that should be populated with the data
len Size of the buffer
Return values
0 on success
-1 on failure
Definition at line 1457 of file pjsip/dialplan_functions.c.
References ast_channel_lock, ast_channel_tech(), ast_channel_tech_pvt(), ast_channel_unlock, ast_log, AST_YESNO, LOG_WARNING, ast_sip_session::moh_passthrough, ast_sip_channel_pvt::session, and type.
 {
    struct ast_sip_channel_pvt *channel;
    if (!chan) {
       ast_log(LOG_WARNING, "No channel was provided to %s function.\n", cmd);
       return -1;
    }
    if (len < 3) {
       ast_log(LOG_WARNING, "%s: buffer too small\n", cmd);
       return -1;
    }
    ast_channel_lock(chan);
    if (strcmp(ast_channel_tech(chan)->type, "PJSIP")) {
       ast_log(LOG_WARNING, "Cannot call %s on a non-PJSIP channel\n", cmd);
       ast_channel_unlock(chan);
       return -1;
    }
    channel = ast_channel_tech_pvt(chan);
    strncpy(buf, AST_YESNO(channel->session->moh_passthrough), len);
    ast_channel_unlock(chan);
    return 0;
 }
pjsip_acf_moh_passthrough_write()
int pjsip_acf_moh_passthrough_write (struct ast_channel * chan, const char * cmd, char * data, const char * value)
PJSIP_MOH_PASSTHROUGH function write callback.
Parameters
chan The channel the function is called on
cmd The name of the function
data Arguments passed to the function
value Value to be set by the function
Return values
0 on success
-1 on failure
Definition at line 1628 of file pjsip/dialplan_functions.c.
References ast_channel_lock, ast_channel_tech(), ast_channel_tech_pvt(), ast_channel_unlock, ast_log, ast_true(), LOG_WARNING, ast_sip_session::moh_passthrough, ast_sip_channel_pvt::session, and type.
 {
    struct ast_sip_channel_pvt *channel;
    if (!chan) {
       ast_log(LOG_WARNING, "No channel was provided to %s function.\n", cmd);
       return -1;
    }
    ast_channel_lock(chan);
    if (strcmp(ast_channel_tech(chan)->type, "PJSIP")) {
       ast_log(LOG_WARNING, "Cannot call %s on a non-PJSIP channel\n", cmd);
       ast_channel_unlock(chan);
       return -1;
    }
    channel = ast_channel_tech_pvt(chan);
    channel->session->moh_passthrough = ast_true(value);
    ast_channel_unlock(chan);
    return 0;
 }
pjsip_acf_parse_uri_read()
int pjsip_acf_parse_uri_read (struct ast_channel * chan, const char * cmd, char * data, char * buf, size_t len)
PJSIP_PARSE_URI function read callback.
Parameters
chan The channel the function is called on
cmd The name of the function
data Arguments passed to the function
buf Out buffer that should be populated with the data
len Size of the buffer
Return values
0 on success
-1 on failure
Definition at line 1197 of file pjsip/dialplan_functions.c.
References args, AST_APP_ARG, AST_DECLARE_APP_ARGS, ast_log, ast_sip_push_task_wait_serializer(), AST_STANDARD_APP_ARGS, ast_strlen_zero, buf, parse_uri_args::buf, parse_uri_args::buflen, LOG_WARNING, NULL, parse_uri_cb(), parse_uri_args::ret, type, parse_uri_args::type, and parse_uri_args::uri.
 {
    struct parse_uri_args func_args = { 0, };
    AST_DECLARE_APP_ARGS(args,
       AST_APP_ARG(uri_str);
       AST_APP_ARG(type);
    );
    AST_STANDARD_APP_ARGS(args, data);
    if (ast_strlen_zero(args.uri_str)) {
       ast_log(LOG_WARNING, "An URI must be specified when using the '%s' dialplan function\n", cmd);
       return -1;
    }
    if (ast_strlen_zero(args.type)) {
       ast_log(LOG_WARNING, "A type part of the URI must be specified when using the '%s' dialplan function\n", cmd);
       return -1;
    }
    memset(buf, 0, buflen);
    func_args.uri = args.uri_str;
    func_args.type = args.type;
    func_args.buf = buf;
    func_args.buflen = buflen;
    if (ast_sip_push_task_wait_serializer(NULL, parse_uri_cb, &func_args)) {
       ast_log(LOG_WARNING, "Unable to parse URI: failed to push task\n");
       return -1;
    }
    return func_args.ret;
 }
pjsip_acf_session_refresh_write()
int pjsip_acf_session_refresh_write (struct ast_channel * chan, const char * cmd, char * data, const char * value)
PJSIP_SEND_SESSION_REFRESH function write callback.
Parameters
chan The channel the function is called on
cmd the Name of the function
data Arguments passed to the function
value Value to be set by the function
Return values
0 on success
-1 on failure
Definition at line 1671 of file pjsip/dialplan_functions.c.
References ast_channel_name(), ast_channel_tech(), ast_channel_tech_pvt(), ast_log, ast_sip_push_task_wait_serializer(), AST_SIP_SESSION_REFRESH_METHOD_INVITE, AST_SIP_SESSION_REFRESH_METHOD_UPDATE, AST_STATE_UP, LOG_WARNING, refresh_data::method, refresh_write_cb(), ast_sip_session::serializer, ast_sip_channel_pvt::session, refresh_data::session, and type.
 {
    struct ast_sip_channel_pvt *channel;
    struct refresh_data rdata = {
       .method = AST_SIP_SESSION_REFRESH_METHOD_INVITE,
    };
    if (!chan) {
       ast_log(LOG_WARNING, "No channel was provided to %s function.\n", cmd);
       return -1;
    }
    if (ast_channel_state(chan) != AST_STATE_UP) {
       ast_log(LOG_WARNING, "'%s' not allowed on unanswered channel '%s'.\n", cmd, ast_channel_name(chan));
       return -1;
    }
    if (strcmp(ast_channel_tech(chan)->type, "PJSIP")) {
       ast_log(LOG_WARNING, "Cannot call %s on a non-PJSIP channel\n", cmd);
       return -1;
    }
    channel = ast_channel_tech_pvt(chan);
    rdata.session = channel->session;
    if (!strcmp(value, "invite")) {
       rdata.method = AST_SIP_SESSION_REFRESH_METHOD_INVITE;
    } else if (!strcmp(value, "update")) {
       rdata.method = AST_SIP_SESSION_REFRESH_METHOD_UPDATE;
    }
    return ast_sip_push_task_wait_serializer(channel->session->serializer, refresh_write_cb, &rdata);
 }
print_escaped_uri()
static int print_escaped_uri (struct ast_channel * chan, const char * type, pjsip_uri_context_e context, const void * uri, char * buf, size_t size) static
Definition at line 736 of file pjsip/dialplan_functions.c.
References ast_channel_name(), ast_escape_quoted(), ast_log, ast_strdupa, and LOG_ERROR.
Referenced by channel_read_pjsip().
 {
    int res;
    char *buf_copy;
    res = pjsip_uri_print(context, uri, buf, size);
    if (res < 0) {
       ast_log(LOG_ERROR, "Channel %s: Unescaped %s too long for %d byte buffer\n",
          ast_channel_name(chan), type, (int) size);
       /* Empty buffer that likely is not terminated. */
       buf[0] = '\0';
       return -1;
    }
    buf_copy = ast_strdupa(buf);
    ast_escape_quoted(buf_copy, buf, size);
    return 0;
 }
read_pjsip()
static int read_pjsip (void * data) static
Definition at line 862 of file pjsip/dialplan_functions.c.
References ast_sip_session::aor, ast_channel_name(), ast_log, AST_LOG_WARNING, ast_sorcery_object_get_id(), pjsip_func_args::buf, ast_sip_session::channel, channel_read_pjsip(), channel_read_rtcp(), channel_read_rtp(), ast_sip_session::contact, ast_sip_session::endpoint, pjsip_func_args::field, func_args(), pjsip_func_args::len, pjsip_func_args::param, pjsip_func_args::ret, pjsip_func_args::session, and pjsip_func_args::type.
Referenced by pjsip_acf_channel_read().
 {
    struct pjsip_func_args *func_args = data;
    if (!strcmp(func_args->param, "rtp")) {
       if (!func_args->session->channel) {
          func_args->ret = -1;
          return 0;
       }
       func_args->ret = channel_read_rtp(func_args->session->channel, func_args->type,
                                         func_args->field, func_args->buf,
                                         func_args->len);
    } else if (!strcmp(func_args->param, "rtcp")) {
       if (!func_args->session->channel) {
          func_args->ret = -1;
          return 0;
       }
       func_args->ret = channel_read_rtcp(func_args->session->channel, func_args->type,
                                          func_args->field, func_args->buf,
                                          func_args->len);
    } else if (!strcmp(func_args->param, "endpoint")) {
       if (!func_args->session->endpoint) {
          ast_log(AST_LOG_WARNING, "Channel %s has no endpoint!\n", func_args->session->channel ?
             ast_channel_name(func_args->session->channel) : "<unknown>");
          func_args->ret = -1;
          return 0;
       }
       snprintf(func_args->buf, func_args->len, "%s", ast_sorcery_object_get_id(func_args->session->endpoint));
    } else if (!strcmp(func_args->param, "contact")) {
       if (!func_args->session->contact) {
          return 0;
       }
       snprintf(func_args->buf, func_args->len, "%s", ast_sorcery_object_get_id(func_args->session->contact));
    } else if (!strcmp(func_args->param, "aor")) {
       if (!func_args->session->aor) {
          return 0;
       }
       snprintf(func_args->buf, func_args->len, "%s", ast_sorcery_object_get_id(func_args->session->aor));
    } else if (!strcmp(func_args->param, "pjsip")) {
       if (!func_args->session->channel) {
          func_args->ret = -1;
          return 0;
       }
       func_args->ret = channel_read_pjsip(func_args->session->channel, func_args->type,
                                           func_args->field, func_args->buf,
                                           func_args->len);
    } else {
       func_args->ret = -1;
    }
    return 0;
 }
refresh_write_cb()
static int refresh_write_cb (void * obj) static
Definition at line 1652 of file pjsip/dialplan_functions.c.
References ast_sip_session_refresh(), ast_sip_session_remove_datastore(), session_refresh_state::media_state, refresh_data::method, NULL, refresh_data::session, session_refresh_state_get_or_alloc(), sip_session_response_cb(), and state.
Referenced by pjsip_acf_session_refresh_write().
 {
    struct refresh_data *data = obj;
    struct session_refresh_state *state;
    state = session_refresh_state_get_or_alloc(data->session);
    if (!state) {
       return -1;
    }
    ast_sip_session_refresh(data->session, NULL, NULL,
       sip_session_response_cb, data->method, 1, state->media_state);
    state->media_state = NULL;
    ast_sip_session_remove_datastore(data->session, "pjsip_session_refresh");
    return 0;
 }
session_refresh_state_destroy()
static void session_refresh_state_destroy (void * obj) static
Destructor for session refresh information.
Definition at line 1063 of file pjsip/dialplan_functions.c.
References ast_free, ast_sip_session_media_state_free(), and session_refresh_state::media_state.
 {
    struct session_refresh_state *state = obj;
    ast_sip_session_media_state_free(state->media_state);
    ast_free(obj);
 }
session_refresh_state_get_or_alloc()
static struct session_refresh_state* session_refresh_state_get_or_alloc (struct ast_sip_session * session) static
Helper function which retrieves or allocates a session refresh state information datastore.
Definition at line 1078 of file pjsip/dialplan_functions.c.
References ao2_cleanup, ast_calloc, ast_sip_session_add_datastore(), ast_sip_session_alloc_datastore(), ast_sip_session_get_datastore(), ast_sip_session_media_state_alloc(), ast_sip_session_remove_datastore(), ast_stream_topology_clone(), ast_sip_session::endpoint, ast_sip_endpoint::media, session_refresh_state::media_state, NULL, RAII_VAR, state, ast_sip_session_media_state::topology, and ast_sip_endpoint_media_configuration::topology.
Referenced by media_offer_read_av(), media_offer_write_av(), and refresh_write_cb().
 {
    RAII_VAR(struct ast_datastore *, datastore, ast_sip_session_get_datastore(session, "pjsip_session_refresh"), ao2_cleanup);
    struct session_refresh_state *state;
    /* While the datastore refcount is decremented this is operating in the serializer so it will remain valid regardless */
    if (datastore) {
       return datastore->data;
    }
    if (!(datastore = ast_sip_session_alloc_datastore(&session_refresh_datastore, "pjsip_session_refresh"))
       || !(datastore->data = ast_calloc(1, sizeof(struct session_refresh_state)))
       || ast_sip_session_add_datastore(session, datastore)) {
       return NULL;
    }
    state = datastore->data;
    state->media_state = ast_sip_session_media_state_alloc();
    if (!state->media_state) {
       ast_sip_session_remove_datastore(session, "pjsip_session_refresh");
       return NULL;
    }
    state->media_state->topology = ast_stream_topology_clone(session->endpoint->media.topology);
    if (!state->media_state->topology) {
       ast_sip_session_remove_datastore(session, "pjsip_session_refresh");
       return NULL;
    }
    datastore->data = state;
    return state;
 }
sip_session_response_cb()
static int sip_session_response_cb (struct ast_sip_session * session, pjsip_rx_data * rdata) static
Definition at line 1490 of file pjsip/dialplan_functions.c.
References ao2_ref, ast_channel_nativeformats(), ast_channel_set_rawreadformat(), ast_channel_set_rawwriteformat(), ast_channel_set_readformat(), ast_channel_set_writeformat(), ast_format_cap_get_best_by_type(), AST_MEDIA_TYPE_AUDIO, and ast_sip_session::channel.
Referenced by dtmf_mode_refresh_cb(), and refresh_write_cb().
 {
    struct ast_format *fmt;
    if (!session->channel) {
       /* Egads! */
       return 0;
    }
    fmt = ast_format_cap_get_best_by_type(ast_channel_nativeformats(session->channel), AST_MEDIA_TYPE_AUDIO);
    if (!fmt) {
       /* No format? That's weird. */
       return 0;
    }
    ast_channel_set_writeformat(session->channel, fmt);
    ast_channel_set_rawwriteformat(session->channel, fmt);
    ast_channel_set_readformat(session->channel, fmt);
    ast_channel_set_rawreadformat(session->channel, fmt);
    ao2_ref(fmt, -1);
    return 0;
 }
Variable Documentation
session_refresh_datastore
const struct ast_datastore_info session_refresh_datastore static
Initial value:
= {
   .type = "pjsip_session_refresh",
   .destroy = session_refresh_state_destroy,
}
Datastore for attaching session refresh state information.
Definition at line 1072 of file pjsip/dialplan_functions.c.
t38state_to_string
const char* t38state_to_string[T38_MAX_ENUM] static
String representations of the T.38 state enum.
Definition at line 541 of file pjsip/dialplan_functions.c.
Referenced by channel_read_pjsip().