Asterisk - The Open Source Telephony Project: mixmonitor.h File Reference
mixmonitor.h File Reference
loadable MixMonitor functionality
Data Structures
struct ast_mixmonitor_methods
MixMonitor virtual methods table definition.
Typedefs
typedef int(* ast_mixmonitor_start_fn) (struct ast_channel *chan, const char *filename, const char *options)
Start a mixmonitor on a channel.
typedef int(* ast_mixmonitor_stop_fn) (struct ast_channel *chan, const char *mixmon_id)
Stop a mixmonitor on a channel.
Functions
int ast_clear_mixmonitor_methods (void)
Clear the MixMonitor virtual methods table. Use this to cleanup function pointers provided by a module that set.
int ast_set_mixmonitor_methods (struct ast_mixmonitor_methods *vmethod_table)
Setup MixMonitor virtual methods table. Use this to provide the MixMonitor functionality from a loadable module.
int ast_start_mixmonitor (struct ast_channel *chan, const char *filename, const char *options)
Start a mixmonitor on a channel with the given parameters.
int ast_stop_mixmonitor (struct ast_channel *chan, const char *mixmon_id)
Stop a mixmonitor on a channel with the given parameters.
Detailed Description
loadable MixMonitor functionality
Author
Jonathan Rose jrose.nosp@m.@dig.nosp@m.ium.c.nosp@m.om
Definition in file mixmonitor.h.
Typedef Documentation
ast_mixmonitor_start_fn
typedef int(* ast_mixmonitor_start_fn) (struct ast_channel *chan, const char *filename, const char *options)
Start a mixmonitor on a channel.
Since
12.0.0
Parameters
chan Which channel to put the MixMonitor on
filename What the name of the file should be
options What options should be used for the mixmonitor
Return values
0 on success
non-zero on failure
Definition at line 40 of file mixmonitor.h.
ast_mixmonitor_stop_fn
typedef int(* ast_mixmonitor_stop_fn) (struct ast_channel *chan, const char *mixmon_id)
Stop a mixmonitor on a channel.
Since
12.0.0
Parameters
chan Which channel to stop a MixMonitor on
mixmon_id Stop the MixMonitor with this mixmonid if it is on the channel (may be NULL)
Return values
0 on success
non-zero on failure
Definition at line 52 of file mixmonitor.h.
Function Documentation
ast_clear_mixmonitor_methods()
int ast_clear_mixmonitor_methods (void)
Clear the MixMonitor virtual methods table. Use this to cleanup function pointers provided by a module that set.
Since
12.0.0
Return values
0 if successful
non-zero on failure (occurs when methods aren't loaded)
Definition at line 59 of file mixmonitor.c.
References ast_log, lock, LOG_ERROR, mixmonitor_lock, mixmonitor_methods, SCOPED_WRLOCK, and table_loaded.
Referenced by clear_mixmonitor_methods().
 {
    SCOPED_WRLOCK(lock, &mixmonitor_lock);
    if (!table_loaded) {
       ast_log(LOG_ERROR, "Tried to clear mixmonitor methods, but none are currently loaded.\n");
       return -1;
    }
    memset(&mixmonitor_methods, 0, sizeof(mixmonitor_methods));
    table_loaded = 0;
    return 0;
 }
ast_set_mixmonitor_methods()
int ast_set_mixmonitor_methods (struct ast_mixmonitor_methods * vmethod_table)
Setup MixMonitor virtual methods table. Use this to provide the MixMonitor functionality from a loadable module.
Since
12.0.0
Parameters
vmethod_table pointer to vmethod table providing mixmonitor functions
Return values
0 if successful
non-zero on failure
Definition at line 43 of file mixmonitor.c.
References ast_log, lock, LOG_ERROR, mixmonitor_lock, mixmonitor_methods, SCOPED_WRLOCK, and table_loaded.
Referenced by set_mixmonitor_methods().
 {
    SCOPED_WRLOCK(lock, &mixmonitor_lock);
    if (table_loaded) {
       /* If mixmonitor methods have already been provided, reject the new set */
       ast_log(LOG_ERROR, "Tried to set mixmonitor methods, but something else has already provided them.\n");
       return -1;
    }
    mixmonitor_methods = *method_table;
    table_loaded = 1;
    return 0;
 }
ast_start_mixmonitor()
int ast_start_mixmonitor (struct ast_channel * chan, const char * filename, const char * options)
Start a mixmonitor on a channel with the given parameters.
Since
12.0.0
Parameters
chan Which channel to apply the MixMonitor to
filename filename to use for the recording
options Optional arguments to be interpreted by the MixMonitor start function
Return values
0 if successful
non-zero on failure
Note
This function will always fail is nothing has set the mixmonitor methods
Definition at line 74 of file mixmonitor.c.
References ast_log, lock, LOG_ERROR, mixmonitor_lock, mixmonitor_methods, SCOPED_RDLOCK, and ast_mixmonitor_methods::start.
Referenced by setup_mixmonitor(), and start_automixmonitor().
 {
    SCOPED_RDLOCK(lock, &mixmonitor_lock);
    if (!mixmonitor_methods.start) {
       ast_log(LOG_ERROR, "No loaded module currently provides MixMonitor starting functionality.\n");
       return -1;
    }
    return mixmonitor_methods.start(chan, filename, options);
 }
ast_stop_mixmonitor()
int ast_stop_mixmonitor (struct ast_channel * chan, const char * mixmon_id)
Stop a mixmonitor on a channel with the given parameters.
Since
12.0.0
Parameters
chan Which channel to stop a MixMonitor on (may be NULL if mixmon_id is provided)
mixmon_id Which mixmon_id should be stopped (may be NULL if chan is provided)
Return values
0 if successful
non-zero on failure
Definition at line 86 of file mixmonitor.c.
References ast_log, lock, LOG_ERROR, mixmonitor_lock, mixmonitor_methods, SCOPED_RDLOCK, and ast_mixmonitor_methods::stop.
Referenced by stop_automixmonitor().
 {
    SCOPED_RDLOCK(lock, &mixmonitor_lock);
    if (!mixmonitor_methods.stop) {
       ast_log(LOG_ERROR, "No loaded module currently provides MixMonitor stopping functionality.\n");
       return -1;
    }
    return mixmonitor_methods.stop(chan, mixmon_id);
 }