Asterisk - The Open Source Telephony Project: res_pjsip_diversion.c File Reference
res_pjsip_diversion.c File Reference
#include "asterisk.h"
#include <pjsip.h>
#include <pjsip_ua.h>
#include "asterisk/res_pjsip.h"
#include "asterisk/res_pjsip_session.h"
#include "asterisk/callerid.h"
#include "asterisk/channel.h"
#include "asterisk/module.h"
#include "asterisk/strings.h"
Data Structures
struct reasons
Diversion header reasons.
Functions
static void __reg_module (void)
static void __unreg_module (void)
static void add_diversion_header (pjsip_tx_data *tdata, struct ast_party_redirecting *data)
static void add_history_info_header (pjsip_tx_data *tdata, struct ast_party_redirecting *data)
static int add_supported (pjsip_tx_data *tdata)
struct ast_module * AST_MODULE_SELF_SYM (void)
static enum AST_REDIRECTING_REASON cause_to_reason (const unsigned long cause)
static void copy_redirecting_id (struct ast_party_id *dst, const struct ast_party_id *src, struct ast_set_party_id *update)
static int diversion_incoming_request (struct ast_sip_session *session, pjsip_rx_data *rdata)
static void diversion_incoming_response (struct ast_sip_session *session, pjsip_rx_data *rdata)
static void diversion_outgoing_request (struct ast_sip_session *session, pjsip_tx_data *tdata)
static void diversion_outgoing_response (struct ast_sip_session *session, pjsip_tx_data *tdata)
static pjsip_fromto_hdr * get_diversion_header (pjsip_rx_data *rdata)
static pjsip_fromto_hdr * get_history_info_header (pjsip_rx_data *rdata, const unsigned int first)
static void get_redirecting_add_diversion (struct ast_sip_session *session, pjsip_tx_data *tdata)
static int load_module (void)
static const unsigned int reason_code_to_cause (const struct ast_party_redirecting_reason *reason)
static const char * reason_code_to_str (const struct ast_party_redirecting_reason *reason)
static void set_redirecting (struct ast_sip_session *session, pjsip_fromto_hdr *from_info, pjsip_name_addr *to_info)
static void set_redirecting_id (pjsip_name_addr *name_addr, struct ast_party_id *data, struct ast_set_party_id *update)
static void set_redirecting_reason (pjsip_fromto_hdr *from_info, pjsip_name_addr *to_info, struct ast_party_redirecting_reason *data)
static void set_redirecting_reason_by_cause (pjsip_name_addr *name_addr, struct ast_party_redirecting_reason *data)
static void set_redirecting_value (char **dst, const pj_str_t *src)
static int sip_is_token (const char *str)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "PJSIP Add Diversion Header Support" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_APP_DEPEND, .requires = "res_pjsip,res_pjsip_session", }
static const struct ast_module_info * ast_module_info = &__mod_info
static const pj_str_t diversion_name = { "Diversion", 9 }
static struct ast_sip_session_supplement diversion_supplement
static pj_str_t HISTINFO_SUPPORTED_NAME = { "histinfo", 8 }
static const pj_str_t history_info_name = { "History-Info", 12 }
static const struct reasons reason_table []
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 730 of file res_pjsip_diversion.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 730 of file res_pjsip_diversion.c.
add_diversion_header()
static void add_diversion_header (pjsip_tx_data * tdata, struct ast_party_redirecting * data) static
Definition at line 504 of file res_pjsip_diversion.c.
References ast_strlen_zero, diversion_name, ast_party_redirecting::from, ast_party_id::name, NULL, ast_party_id::number, ast_party_redirecting::reason, reason_code_to_str(), sip_is_token(), ast_party_name::str, ast_party_number::str, ast_party_redirecting::to, and ast_party_number::valid.
Referenced by get_redirecting_add_diversion().
 {
    static const pj_str_t reason_name = { "reason", 6 };
    pjsip_fromto_hdr *hdr;
    pjsip_name_addr *name_addr;
    pjsip_sip_uri *uri;
    pjsip_param *param;
    pjsip_fromto_hdr *old_hdr;
    const char *reason_str;
    const char *quote_str;
    char *reason_buf;
    pjsip_uri *base;
    struct ast_party_id *id = NULL;
    if (tdata->msg->type == PJSIP_REQUEST_MSG) {
       id = &data->from;
    } else {
       /* In responses indicate the new destination */
       id = &data->to;
    }
    base = PJSIP_MSG_FROM_HDR(tdata->msg)->uri;
    if (!id->number.valid || ast_strlen_zero(id->number.str)) {
       return;
    }
    hdr = pjsip_from_hdr_create(tdata->pool);
    hdr->type = PJSIP_H_OTHER;
    hdr->sname = hdr->name = diversion_name;
    name_addr = pjsip_uri_clone(tdata->pool, base);
    uri = pjsip_uri_get_uri(name_addr->uri);
    pj_strdup2(tdata->pool, &name_addr->display, id->name.str);
    pj_strdup2(tdata->pool, &uri->user, id->number.str);
    param = PJ_POOL_ALLOC_T(tdata->pool, pjsip_param);
    param->name = reason_name;
    reason_str = reason_code_to_str(&data->reason);
    /* Reason is either already quoted or it is a token to not need quotes added. */
    quote_str = *reason_str == '\"' || sip_is_token(reason_str) ? "" : "\"";
    reason_buf = pj_pool_alloc(tdata->pool, strlen(reason_str) + 3);
    sprintf(reason_buf, "%s%s%s", quote_str, reason_str, quote_str);/* Safe */
    param->value = pj_str(reason_buf);
    pj_list_insert_before(&hdr->other_param, param);
    hdr->uri = (pjsip_uri *) name_addr;
    old_hdr = pjsip_msg_find_hdr_by_name(tdata->msg, &diversion_name, NULL);
    if (old_hdr) {
       pj_list_erase(old_hdr);
    }
    pjsip_msg_add_hdr(tdata->msg, (pjsip_hdr *)hdr);
 }
add_history_info_header()
static void add_history_info_header (pjsip_tx_data * tdata, struct ast_party_redirecting * data) static
Definition at line 572 of file res_pjsip_diversion.c.
References ast_strlen_zero, reasons::cause, ast_party_redirecting::from, history_info_name, ast_party_id::name, NULL, ast_party_id::number, ast_party_redirecting::reason, reason_code_to_cause(), ast_party_name::str, ast_party_number::str, ast_party_redirecting::to, and ast_party_number::valid.
Referenced by get_redirecting_add_diversion().
 {
    static const pj_str_t index_name = { "index", 5 };
    static const pj_str_t cause_name = { "cause", 5 };
    static const pj_str_t first_index = { "1", 1 };
    static const pj_str_t last_index = { "1.1", 3 };
    pjsip_fromto_hdr *hdr;
    pjsip_name_addr *name_addr;
    pjsip_sip_uri *uri;
    pjsip_param *param;
    pjsip_fromto_hdr *old_hdr;
    unsigned int cause;
    char *cause_buf;
    struct ast_party_id *to = &data->to;
    struct ast_party_id *from = &data->from;
    pjsip_uri *base = PJSIP_MSG_TO_HDR(tdata->msg)->uri;
    hdr = pjsip_from_hdr_create(tdata->pool);
    hdr->type = PJSIP_H_OTHER;
    hdr->sname = hdr->name = history_info_name;
    name_addr = pjsip_uri_clone(tdata->pool, base);
    uri = pjsip_uri_get_uri(name_addr->uri);
    /* if no redirecting information, then TO is the original destination */
    if (from->number.valid && !ast_strlen_zero(from->number.str)) {
       pj_strdup2(tdata->pool, &name_addr->display, from->name.str);
       pj_strdup2(tdata->pool, &uri->user, from->number.str);
    }
    param = PJ_POOL_ALLOC_T(tdata->pool, pjsip_param);
    param->name = index_name;
    param->value = first_index;
    pj_list_insert_before(&hdr->other_param, param);
    hdr->uri = (pjsip_uri *) name_addr;
    while ((old_hdr = pjsip_msg_find_hdr_by_name(tdata->msg, &history_info_name, NULL)) != NULL) {
       pj_list_erase(old_hdr);
    }
    pjsip_msg_add_hdr(tdata->msg, (pjsip_hdr *)hdr);
    if (!to->number.valid || ast_strlen_zero(to->number.str)) {
       return;
    }
    hdr = pjsip_from_hdr_create(tdata->pool);
    hdr->type = PJSIP_H_OTHER;
    hdr->sname = hdr->name = history_info_name;
    name_addr = pjsip_uri_clone(tdata->pool, base);
    uri = pjsip_uri_get_uri(name_addr->uri);
    pj_strdup2(tdata->pool, &name_addr->display, to->name.str);
    pj_strdup2(tdata->pool, &uri->user, to->number.str);
    param = PJ_POOL_ALLOC_T(tdata->pool, pjsip_param);
    param->name = index_name;
    param->value = last_index;
    pj_list_insert_before(&hdr->other_param, param);
    param = PJ_POOL_ALLOC_T(tdata->pool, pjsip_param);
    param->name = cause_name;
    cause = reason_code_to_cause(&data->reason);
    cause_buf = pj_pool_alloc(tdata->pool, 4);
    snprintf(cause_buf, 4, "%ud", cause);
    param->value = pj_str(cause_buf);
    pj_list_insert_before(&uri->other_param, param);
    hdr->uri = (pjsip_uri *) name_addr;
    pjsip_msg_add_hdr(tdata->msg, (pjsip_hdr *)hdr);
 }
add_supported()
static int add_supported (pjsip_tx_data * tdata) static
Definition at line 120 of file res_pjsip_diversion.c.
References HISTINFO_SUPPORTED_NAME, and NULL.
Referenced by get_redirecting_add_diversion().
 {
    pjsip_supported_hdr *hdr;
    unsigned int i;
    hdr = pjsip_msg_find_hdr(tdata->msg, PJSIP_H_SUPPORTED, NULL);
    if (!hdr) {
       /* insert a new Supported header */
       hdr = pjsip_supported_hdr_create(tdata->pool);
       if (!hdr) {
          return -1;
       }
       pjsip_msg_add_hdr(tdata->msg, (pjsip_hdr *)hdr);
    }
    /* Asterisk can send multiple "181 Call forwarded" in a single session,
     * we might have already modified Supported before
     */
    for (i = 0; i < hdr->count; ++i) {
       if (pj_stricmp(&hdr->values[i], &HISTINFO_SUPPORTED_NAME) == 0) {
          return 0;
       }
    }
    if (hdr->count >= PJSIP_GENERIC_ARRAY_MAX_COUNT) {
       return -1;
    }
    /* add on to the existing Supported header */
    pj_strassign(&hdr->values[hdr->count++], &HISTINFO_SUPPORTED_NAME);
    return 0;
 }
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 730 of file res_pjsip_diversion.c.
cause_to_reason()
static enum AST_REDIRECTING_REASON cause_to_reason (const unsigned long cause) static
Definition at line 102 of file res_pjsip_diversion.c.
References AST_REDIRECTING_REASON_DEFLECTION, AST_REDIRECTING_REASON_NO_ANSWER, AST_REDIRECTING_REASON_UNAVAILABLE, AST_REDIRECTING_REASON_UNCONDITIONAL, AST_REDIRECTING_REASON_UNKNOWN, and AST_REDIRECTING_REASON_USER_BUSY.
Referenced by set_redirecting_reason_by_cause().
{
    switch(cause) {
       case 302:
          return AST_REDIRECTING_REASON_UNCONDITIONAL;
       case 486:
          return AST_REDIRECTING_REASON_USER_BUSY;
       case 408:
          return AST_REDIRECTING_REASON_NO_ANSWER;
       case 480:
       case 487:
          return AST_REDIRECTING_REASON_DEFLECTION;
       case 503:
          return AST_REDIRECTING_REASON_UNAVAILABLE;
       default:
          return AST_REDIRECTING_REASON_UNKNOWN;
    }
 }
copy_redirecting_id()
static void copy_redirecting_id (struct ast_party_id * dst, const struct ast_party_id * src, struct ast_set_party_id * update) static
Definition at line 312 of file res_pjsip_diversion.c.
References ast_party_id_copy(), ast_party_id::name, ast_set_party_id::name, ast_party_id::number, ast_set_party_id::number, ast_party_name::valid, and ast_party_number::valid.
Referenced by set_redirecting().
 {
    ast_party_id_copy(dst, src);
    if (dst->number.valid) {
       update->number = 1;
    }
    if (dst->name.valid) {
       update->name = 1;
    }
 }
diversion_incoming_request()
static int diversion_incoming_request (struct ast_sip_session * session, pjsip_rx_data * rdata) static
Definition at line 427 of file res_pjsip_diversion.c.
References get_diversion_header(), get_history_info_header(), and set_redirecting().
 {
    pjsip_fromto_hdr *hdr = get_diversion_header(rdata);
    if (hdr) {
       set_redirecting(session, hdr, (pjsip_name_addr*)
             PJSIP_MSG_TO_HDR(rdata->msg_info.msg)->uri);
    } else {
       pjsip_fromto_hdr *history_info_to;
       pjsip_fromto_hdr *history_info_from;
       history_info_to  = get_history_info_header(rdata, 0);
       if (history_info_to) {
          /* If History-Info is present, then it will also include the original
             redirected-from in addition to the redirected-to */
          history_info_from = get_history_info_header(rdata, 1);
          set_redirecting(session, history_info_from, (pjsip_name_addr*)history_info_to->uri);
       }
    }
    return 0;
 }
diversion_incoming_response()
static void diversion_incoming_response (struct ast_sip_session * session, pjsip_rx_data * rdata) static
Definition at line 450 of file res_pjsip_diversion.c.
References get_diversion_header(), get_history_info_header(), ast_sip_session::id, NULL, ast_party_id::number, set_redirecting(), status, and ast_party_number::valid.
 {
    static const pj_str_t contact_name = { "Contact", 7 };
    static const pj_str_t contact_name_s = { "m", 1 };
    pjsip_status_line status = rdata->msg_info.msg->line.status;
    pjsip_fromto_hdr *div_hdr;
    pjsip_fromto_hdr *history_info_to;
    pjsip_fromto_hdr *history_info_from;
    pjsip_contact_hdr *contact_hdr;
    if ((status.code != 302) && (status.code != 181)) {
       return;
    }
    /* use the diversion header info if there is one. if not one then use the
       the history-info, if that doesn't exist, use session caller id info. if
       that doesn't exist use info from the To hdr*/
    if (!(div_hdr = get_diversion_header(rdata))) {
       history_info_to  = get_history_info_header(rdata, 0);
       if (history_info_to) {
          /* If History-Info is present, then it will also include the original
             redirected-from in addition to the redirected-to */
          history_info_from = get_history_info_header(rdata, 1);
          set_redirecting(session, history_info_from, (pjsip_name_addr*)history_info_to->uri);
          return;
       }
       if (!div_hdr && !session->id.number.valid) {
          div_hdr = PJSIP_MSG_TO_HDR(rdata->msg_info.msg);
       }
    }
    if (status.code == 302) {
       /* With 302, Contact indicates the final destination and possibly Diversion indicates the hop before */
       contact_hdr = pjsip_msg_find_hdr_by_names(rdata->msg_info.msg, &contact_name, &contact_name_s, NULL);
       set_redirecting(session, div_hdr, contact_hdr ? (pjsip_name_addr*)contact_hdr->uri :
             (pjsip_name_addr*)PJSIP_MSG_FROM_HDR(rdata->msg_info.msg)->uri);
    } else {
       /* With 181, Diversion is non-standard, but if present indicates the new final destination, and To indicating the original */
       set_redirecting(session, PJSIP_MSG_TO_HDR(rdata->msg_info.msg),
             div_hdr ? (pjsip_name_addr*)div_hdr->uri : NULL);
    }
 }
diversion_outgoing_request()
static void diversion_outgoing_request (struct ast_sip_session * session, pjsip_tx_data * tdata) static
Definition at line 675 of file res_pjsip_diversion.c.
References get_redirecting_add_diversion().
 {
    get_redirecting_add_diversion(session, tdata);
 }
diversion_outgoing_response()
static void diversion_outgoing_response (struct ast_sip_session * session, pjsip_tx_data * tdata) static
Definition at line 687 of file res_pjsip_diversion.c.
References get_redirecting_add_diversion().
 {
    struct pjsip_status_line status = tdata->msg->line.status;
    /* add to 302 and 181 */
    if (PJSIP_IS_STATUS_IN_CLASS(status.code, 300) || (status.code == 181)) {
       get_redirecting_add_diversion(session, tdata);
    }
 }
get_diversion_header()
static pjsip_fromto_hdr* get_diversion_header (pjsip_rx_data * rdata) static
Definition at line 190 of file res_pjsip_diversion.c.
References diversion_name, NULL, and value.
Referenced by diversion_incoming_request(), and diversion_incoming_response().
 {
    static const pj_str_t from_name = { "From", 4 };
    pjsip_generic_string_hdr *hdr;
    pj_str_t value;
    int size;
    if (!(hdr = pjsip_msg_find_hdr_by_name(rdata->msg_info.msg, &diversion_name, NULL))) {
       return NULL;
    }
    pj_strdup_with_null(rdata->tp_info.pool, &value, &hdr->hvalue);
    /* parse as a fromto header */
    return pjsip_parse_hdr(rdata->tp_info.pool, &from_name, value.ptr,
                 pj_strlen(&value), &size);
 }
get_history_info_header()
static pjsip_fromto_hdr* get_history_info_header (pjsip_rx_data * rdata, const unsigned int first) static
Definition at line 215 of file res_pjsip_diversion.c.
References history_info_name, NULL, and value.
Referenced by diversion_incoming_request(), and diversion_incoming_response().
 {
    static const pj_str_t from_name = { "From", 4 };
    pjsip_fromto_hdr * result_hdr = NULL;
    pjsip_generic_string_hdr *hdr = NULL;
    hdr = pjsip_msg_find_hdr_by_name(rdata->msg_info.msg, &history_info_name, NULL);
    if (!hdr) {
       return NULL;
    }
    do {
       static const pj_str_t index_name = { "index", 5 };
       pj_str_t value;
       int size;
       pjsip_fromto_hdr * fromto_hdr = NULL;
       pjsip_param * index = NULL;
       pj_strdup_with_null(rdata->tp_info.pool, &value, &hdr->hvalue);
       /* parse as a fromto header */
       fromto_hdr =  pjsip_parse_hdr(rdata->tp_info.pool, &from_name, value.ptr,
                    pj_strlen(&value), &size);
       if (fromto_hdr == NULL) {
          continue;
       }
       index = pjsip_param_find(&fromto_hdr->other_param, &index_name);
       if (index) {
          if (!pj_strcmp2(&index->value, "1")) {
             if (!first) {
                continue;
             } else {
                return fromto_hdr;
             }
          }
       }
       result_hdr = fromto_hdr;
    } while ((hdr = pjsip_msg_find_hdr_by_name(rdata->msg_info.msg, &history_info_name, hdr->next)));
    return result_hdr;
 }
get_redirecting_add_diversion()
static void get_redirecting_add_diversion (struct ast_sip_session * session, pjsip_tx_data * tdata) static
Definition at line 651 of file res_pjsip_diversion.c.
References add_diversion_header(), add_history_info_header(), add_supported(), ast_channel_redirecting(), ast_sip_session::channel, ast_sip_session::endpoint, ast_sip_endpoint::id, ast_sip_endpoint_id_configuration::send_diversion, and ast_sip_endpoint_id_configuration::send_history_info.
Referenced by diversion_outgoing_request(), and diversion_outgoing_response().
 {
    struct ast_party_redirecting *data;
    add_supported(tdata);
    if (session->channel && session->endpoint->id.send_diversion &&
        (data = ast_channel_redirecting(session->channel))->count) {
       add_diversion_header(tdata, data);
    }
    if (session->channel && session->endpoint->id.send_history_info) {
       data = ast_channel_redirecting(session->channel);
       add_history_info_header(tdata, data);
    }
 }
load_module()
static int load_module (void) static
Definition at line 709 of file res_pjsip_diversion.c.
References AST_MODULE_LOAD_SUCCESS, ast_module_shutdown_ref, ast_sip_session_register_supplement, and ast_module_info::self.
Referenced by unload_module().
 {
    /* Because we are passing static memory to pjsip, we need to make sure it
     * stays valid while we potentially have active sessions */
    ast_module_shutdown_ref(ast_module_info->self);
    ast_sip_session_register_supplement(&diversion_supplement);
    return AST_MODULE_LOAD_SUCCESS;
 }
reason_code_to_cause()
static const unsigned int reason_code_to_cause (const struct ast_party_redirecting_reason * reason) static
Definition at line 175 of file res_pjsip_diversion.c.
References ARRAY_LEN, reasons::cause, ast_party_redirecting_reason::code, reasons::code, and reason_table.
Referenced by add_history_info_header().
 {
    int idx;
    int code;
    code = reason->code;
    for (idx = 0; idx < ARRAY_LEN(reason_table); ++idx) {
       if (code == reason_table[idx].code) {
          return reason_table[idx].cause;
       }
    }
    return 404;
 }
reason_code_to_str()
static const char* reason_code_to_str (const struct ast_party_redirecting_reason * reason) static
Definition at line 155 of file res_pjsip_diversion.c.
References ARRAY_LEN, ast_strlen_zero, ast_party_redirecting_reason::code, reasons::code, reason_table, ast_party_redirecting_reason::str, and reasons::text.
Referenced by add_diversion_header().
 {
    int idx;
    int code;
    /* use specific string if given */
    if (!ast_strlen_zero(reason->str)) {
       return reason->str;
    }
    code = reason->code;
    for (idx = 0; idx < ARRAY_LEN(reason_table); ++idx) {
       if (code == reason_table[idx].code) {
          return reason_table[idx].text;
       }
    }
    return "unknown";
 }
set_redirecting()
static void set_redirecting (struct ast_sip_session * session, pjsip_fromto_hdr * from_info, pjsip_name_addr * to_info) static
Definition at line 386 of file res_pjsip_diversion.c.
References ast_channel_queue_redirecting_update(), ast_channel_set_redirecting(), ast_party_redirecting_free(), ast_party_redirecting_init(), AST_REDIRECTING_REASON_UNKNOWN, ast_set_party_id_all(), ast_sip_session::channel, ast_party_redirecting_reason::code, copy_redirecting_id(), ast_party_redirecting::count, ast_party_redirecting::from, ast_set_party_redirecting::from, ast_sip_session::id, ast_sip_session::inv_session, ast_set_party_redirecting::priv_from, ast_set_party_redirecting::priv_orig, ast_set_party_redirecting::priv_to, ast_party_redirecting::reason, set_redirecting_id(), set_redirecting_reason(), ast_party_redirecting::to, and ast_set_party_redirecting::to.
Referenced by diversion_incoming_request(), and diversion_incoming_response().
 {
    struct ast_party_redirecting data;
    struct ast_set_party_redirecting update;
    if (!session->channel) {
       return;
    }
    ast_party_redirecting_init(&data);
    memset(&update, 0, sizeof(update));
    data.reason.code = AST_REDIRECTING_REASON_UNKNOWN;
    if (from_info) {
       set_redirecting_id((pjsip_name_addr*)from_info->uri,
          &data.from, &update.from);
       set_redirecting_reason(from_info, to_info, &data.reason);
       ast_set_party_id_all(&update.priv_to);
    } else {
       copy_redirecting_id(&data.from, &session->id, &update.from);
    }
    if (to_info) {
       set_redirecting_id(to_info, &data.to, &update.to);
    }
    ast_set_party_id_all(&update.priv_orig);
    ast_set_party_id_all(&update.priv_from);
    ast_set_party_id_all(&update.priv_to);
    ++data.count;
    ast_channel_set_redirecting(session->channel, &data, &update);
    /* Only queue an indication if it was due to a response */
    if (session->inv_session->role == PJSIP_ROLE_UAC) {
       ast_channel_queue_redirecting_update(session->channel, &data, &update);
    }
    ast_party_redirecting_free(&data);
 }
set_redirecting_id()
static void set_redirecting_id (pjsip_name_addr * name_addr, struct ast_party_id * data, struct ast_set_party_id * update) static
Definition at line 273 of file res_pjsip_diversion.c.
References ast_party_id::name, ast_set_party_id::name, ast_party_id::number, ast_set_party_id::number, set_redirecting_value(), ast_party_name::str, ast_party_number::str, ast_party_name::valid, and ast_party_number::valid.
Referenced by set_redirecting().
 {
    pjsip_sip_uri *uri = pjsip_uri_get_uri(name_addr->uri);
    char *semi;
    pj_str_t uri_user;
    uri_user = uri->user;
    /* Always truncate redirecting number at a semicolon. */
    semi = pj_strchr(&uri_user, ';');
    if (semi) {
       /*
        * We need to be able to handle URI's looking like
        * "sip:1235557890;phone-context=national@x.x.x.x;user=phone"
        *
        * Where the uri->user field will result in:
        * "1235557890;phone-context=national"
        *
        * People don't care about anything after the semicolon
        * showing up on their displays even though the RFC
        * allows the semicolon.
        */
       pj_strset(&uri_user, (char *) pj_strbuf(&uri_user), semi - pj_strbuf(&uri_user));
    }
    if (pj_strlen(&uri_user)) {
       update->number = 1;
       data->number.valid = 1;
       set_redirecting_value(&data->number.str, &uri_user);
    }
    if (pj_strlen(&name_addr->display)) {
       update->name = 1;
       data->name.valid = 1;
       set_redirecting_value(&data->name.str, &name_addr->display);
    }
 }
set_redirecting_reason()
static void set_redirecting_reason (pjsip_fromto_hdr * from_info, pjsip_name_addr * to_info, struct ast_party_redirecting_reason * data) static
Definition at line 351 of file res_pjsip_diversion.c.
References ast_free, ast_redirecting_reason_parse(), AST_REDIRECTING_REASON_UNKNOWN, ast_strdup, ast_strdupa, ast_strip_quoted(), ast_party_redirecting_reason::code, set_redirecting_reason_by_cause(), set_redirecting_value(), and ast_party_redirecting_reason::str.
Referenced by set_redirecting().
 {
    static const pj_str_t reason_name = { "reason", 6 };
    pjsip_param *reason = pjsip_param_find(&from_info->other_param, &reason_name);
    char *reason_str;
    if (!reason) {
       if (to_info) {
          set_redirecting_reason_by_cause(to_info, data);
       }
       return;
    }
    set_redirecting_value(&data->str, &reason->value);
    if (!data->str) {
       /* Oops, allocation failure */
       return;
    }
    reason_str = ast_strdupa(data->str);
    /* Remove any enclosing double-quotes */
    if (*reason_str == '"') {
       reason_str = ast_strip_quoted(reason_str, "\"", "\"");
    }
    data->code = ast_redirecting_reason_parse(reason_str);
    if (data->code < 0) {
       data->code = AST_REDIRECTING_REASON_UNKNOWN;
    } else {
       ast_free(data->str);
       data->str = ast_strdup("");
    }
 }
set_redirecting_reason_by_cause()
static void set_redirecting_reason_by_cause (pjsip_name_addr * name_addr, struct ast_party_redirecting_reason * data) static
Definition at line 326 of file res_pjsip_diversion.c.
References ast_free, ast_strdup, reasons::cause, cause_to_reason(), ast_party_redirecting_reason::code, NULL, and ast_party_redirecting_reason::str.
Referenced by set_redirecting_reason().
 {
    static const pj_str_t cause_name = { "cause", 5 };
    pjsip_sip_uri *uri = pjsip_uri_get_uri(name_addr);
    pjsip_param *cause = NULL;
    unsigned long cause_value = 0;
    if (!PJSIP_URI_SCHEME_IS_SIP(uri) && !PJSIP_URI_SCHEME_IS_SIPS(uri)) {
       return;
    }
    cause = pjsip_param_find(&uri->other_param, &cause_name);
    if (!cause) {
       return;
    }
    cause_value = pj_strtoul(&cause->value);
    data->code = cause_to_reason(cause_value);
    ast_free(data->str);
    data->str = ast_strdup("");
 }
set_redirecting_value()
static void set_redirecting_value (char ** dst, const pj_str_t * src) static
Definition at line 264 of file res_pjsip_diversion.c.
References ast_copy_pj_str(), ast_free, and ast_malloc.
Referenced by set_redirecting_id(), and set_redirecting_reason().
 {
    ast_free(*dst);
    *dst = ast_malloc(pj_strlen(src) + 1);
    if (*dst) {
       ast_copy_pj_str(*dst, src, pj_strlen(src) + 1);
    }
 }
sip_is_token()
static int sip_is_token (const char * str) static
Definition at line 53 of file res_pjsip_diversion.c.
References ast_strlen_zero.
Referenced by add_diversion_header().
 {
    int is_token;
    if (ast_strlen_zero(str)) {
       /* An empty string is not a token. */
       return 0;
    }
    is_token = 1;
    do {
       if (!isalnum(*str)
          && !strchr("-.!%*_+`'~", *str)) {
          /* The character is not allowed in a token. */
          is_token = 0;
          break;
       }
    } while (*++str);
    return is_token;
 }
unload_module()
static int unload_module (void) static
Definition at line 718 of file res_pjsip_diversion.c.
References AST_MODFLAG_LOAD_ORDER, AST_MODPRI_APP_DEPEND, AST_MODULE_INFO(), AST_MODULE_SUPPORT_CORE, ast_sip_session_unregister_supplement(), ASTERISK_GPL_KEY, and load_module().
 {
    ast_sip_session_unregister_supplement(&diversion_supplement);
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "PJSIP Add Diversion Header Support" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_APP_DEPEND, .requires = "res_pjsip,res_pjsip_session", } static
Definition at line 730 of file res_pjsip_diversion.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 730 of file res_pjsip_diversion.c.
diversion_name
const pj_str_t diversion_name = { "Diversion", 9 } static
Definition at line 38 of file res_pjsip_diversion.c.
Referenced by add_diversion_header(), and get_diversion_header().
diversion_supplement
struct ast_sip_session_supplement diversion_supplement static
Definition at line 697 of file res_pjsip_diversion.c.
HISTINFO_SUPPORTED_NAME
pj_str_t HISTINFO_SUPPORTED_NAME = { "histinfo", 8 } static
Definition at line 40 of file res_pjsip_diversion.c.
Referenced by add_supported().
history_info_name
const pj_str_t history_info_name = { "History-Info", 12 } static
Definition at line 39 of file res_pjsip_diversion.c.
Referenced by add_history_info_header(), and get_history_info_header().
reason_table
const struct reasons reason_table[] static
Referenced by reason_code_to_cause(), and reason_code_to_str().