Asterisk - The Open Source Telephony Project: func_aes.c File Reference
func_aes.c File Reference
Module: Dial plan functions
AES encryption/decryption dialplan functions.
#include "asterisk.h"
#include "asterisk/module.h"
#include "asterisk/pbx.h"
#include "asterisk/app.h"
#include "asterisk/crypto.h"
Macros
#define AES_BLOCK_SIZE 16
Functions
static void __reg_module (void)
static void __unreg_module (void)
static int aes_helper (struct ast_channel *chan, const char *cmd, char *data, char *buf, size_t len)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int load_module (void)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_DEFAULT , .description = "AES dialplan functions" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .requires = "res_crypto", }
static struct ast_custom_function aes_decrypt_function
static struct ast_custom_function aes_encrypt_function
static const struct ast_module_info * ast_module_info = &__mod_info
Detailed Description
AES encryption/decryption dialplan functions.
Author
David Vossel dvoss.nosp@m.el@d.nosp@m.igium.nosp@m..com
Definition in file func_aes.c.
Macro Definition Documentation
AES_BLOCK_SIZE
#define AES_BLOCK_SIZE 16
Definition at line 38 of file func_aes.c.
Referenced by aes_helper().
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 185 of file func_aes.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 185 of file func_aes.c.
aes_helper()
static int aes_helper (struct ast_channel * chan, const char * cmd, char * data, char * buf, size_t len) static
Definition at line 86 of file func_aes.c.
References AES_BLOCK_SIZE, args, ast_aes_decrypt(), ast_aes_encrypt(), ast_aes_set_decrypt_key(), ast_aes_set_encrypt_key(), AST_APP_ARG, ast_base64decode(), ast_base64encode(), ast_calloc, ast_copy_string(), AST_DECLARE_APP_ARGS, ast_free, ast_log, AST_STANDARD_APP_ARGS, ast_strlen_zero, LOG_ERROR, LOG_WARNING, and tmp().
 {
    unsigned char curblock[AES_BLOCK_SIZE] = { 0, };
    char *tmp;
    char *tmpP;
    int data_len, encrypt;
    ast_aes_encrypt_key ecx;                        /*  AES 128 Encryption context */
    ast_aes_decrypt_key dcx;
    AST_DECLARE_APP_ARGS(args,
       AST_APP_ARG(key);
       AST_APP_ARG(data);
    );
    AST_STANDARD_APP_ARGS(args, data);
    if (ast_strlen_zero(args.data) || ast_strlen_zero(args.key)) {
       ast_log(LOG_WARNING, "Syntax: %s(<key>,<data>) - missing argument!\n", cmd);
       return -1;
    }
    if (strlen(args.key) != AES_BLOCK_SIZE) {        /* key must be of 16 characters in length, 128 bits */
       ast_log(LOG_WARNING, "Syntax: %s(<key>,<data>) - <key> parameter must be exactly 16 characters!\n", cmd);
       return -1;
    }
    ast_aes_set_encrypt_key((unsigned char *) args.key, &ecx);   /* encryption:  plaintext -> encryptedtext -> base64 */
    ast_aes_set_decrypt_key((unsigned char *) args.key, &dcx);   /* decryption:  base64 -> encryptedtext -> plaintext */
    tmp = ast_calloc(1, len);                     /* requires a tmp buffer for the base64 decode */
    if (!tmp) {
       ast_log(LOG_ERROR, "Unable to allocate memory for data\n");
       return -1;
    }
    tmpP = tmp;
    encrypt = strcmp("AES_DECRYPT", cmd);           /* -1 if encrypting, 0 if decrypting */
    if (encrypt) {                                  /* if decrypting first decode src to base64 */
       ast_copy_string(tmp, args.data, len);
       data_len = strlen(tmp);
    } else {
       data_len = ast_base64decode((unsigned char *) tmp, args.data, len);
    }
    if (data_len >= len) {                        /* make sure to not go over buffer len */
       ast_log(LOG_WARNING, "Syntax: %s(<keys>,<data>) - <data> exceeds buffer length.  Result may be truncated!\n", cmd);
       data_len = len - 1;
    }
    while (data_len > 0) {
       memset(curblock, 0, AES_BLOCK_SIZE);
       memcpy(curblock, tmpP, (data_len < AES_BLOCK_SIZE) ? data_len : AES_BLOCK_SIZE);
       if (encrypt) {
          ast_aes_encrypt(curblock, (unsigned char *) tmpP, &ecx);
       } else {
          ast_aes_decrypt(curblock, (unsigned char *) tmpP, &dcx);
       }
       tmpP += AES_BLOCK_SIZE;
       data_len -= AES_BLOCK_SIZE;
    }
    if (encrypt) {                            /* if encrypting encode result to base64 */
       ast_base64encode(buf, (unsigned char *) tmp, tmpP - tmp, len);
    } else {
       memcpy(buf, tmp, len);
    }
    ast_free(tmp);
    return 0;
 }
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 185 of file func_aes.c.
load_module()
static int load_module (void) static
Definition at line 173 of file func_aes.c.
References ast_custom_function_register, AST_MODFLAG_DEFAULT, AST_MODULE_INFO(), AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, AST_MODULE_SUPPORT_CORE, ASTERISK_GPL_KEY, and unload_module().
 {
    int res = ast_custom_function_register(&aes_decrypt_function);
    res |= ast_custom_function_register(&aes_encrypt_function);
    return res ? AST_MODULE_LOAD_DECLINE : AST_MODULE_LOAD_SUCCESS;
 }
unload_module()
static int unload_module (void) static
Definition at line 167 of file func_aes.c.
References ast_custom_function_unregister().
Referenced by load_module().
 {
    int res = ast_custom_function_unregister(&aes_decrypt_function);
    return res | ast_custom_function_unregister(&aes_encrypt_function);
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_DEFAULT , .description = "AES dialplan functions" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .requires = "res_crypto", } static
Definition at line 185 of file func_aes.c.
aes_decrypt_function
struct ast_custom_function aes_decrypt_function static
Initial value:
= {
   .name = "AES_DECRYPT",
   .read = aes_helper,
}
Definition at line 162 of file func_aes.c.
aes_encrypt_function
struct ast_custom_function aes_encrypt_function static
Initial value:
= {
   .name = "AES_ENCRYPT",
   .read = aes_helper,
}
Definition at line 157 of file func_aes.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 185 of file func_aes.c.