Asterisk - The Open Source Telephony Project: res_pjsip_dialog_info_body_generator.c File Reference
res_pjsip_dialog_info_body_generator.c File Reference
#include "asterisk.h"
#include <pjsip.h>
#include <pjsip_simple.h>
#include <pjlib.h>
#include "asterisk/module.h"
#include "asterisk/callerid.h"
#include "asterisk/res_pjsip.h"
#include "asterisk/res_pjsip_pubsub.h"
#include "asterisk/res_pjsip_presence_xml.h"
#include "asterisk/res_pjsip_body_generator_types.h"
Data Structures
struct dialog_info_xml_state
Structure which contains dialog-info+xml state information.
Macros
#define MAX_STRING_GROWTHS 6
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static void * dialog_info_allocate_body (void *data)
static int dialog_info_generate_body_content (void *body, void *data)
static void dialog_info_to_string (void *body, struct ast_str **str)
static void dialog_info_xml_state_destroy (void *obj)
Destructor for dialog-info+xml information.
static struct ast_channel * find_ringing_channel (struct ao2_container *device_state_info)
static int load_module (void)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "PJSIP Extension State Dialog Info+XML Provider" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_CHANNEL_DEPEND, .requires = "res_pjsip,res_pjsip_pubsub", }
static const struct ast_module_info * ast_module_info = &__mod_info
static struct ast_sip_pubsub_body_generator dialog_info_body_generator
static const struct ast_datastore_info dialog_info_xml_datastore
Datastore for attaching dialog-info+xml state information.
Macro Definition Documentation
MAX_STRING_GROWTHS
#define MAX_STRING_GROWTHS 6
Definition at line 278 of file res_pjsip_dialog_info_body_generator.c.
Referenced by dialog_info_to_string().
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 333 of file res_pjsip_dialog_info_body_generator.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 333 of file res_pjsip_dialog_info_body_generator.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 333 of file res_pjsip_dialog_info_body_generator.c.
dialog_info_allocate_body()
static void* dialog_info_allocate_body (void * data) static
Definition at line 57 of file res_pjsip_dialog_info_body_generator.c.
References ast_sip_presence_xml_create_node(), NULL, and ast_sip_exten_state_data::pool.
 {
    struct ast_sip_exten_state_data *state_data = data;
    return ast_sip_presence_xml_create_node(state_data->pool, NULL, "dialog-info");
 }
dialog_info_generate_body_content()
static int dialog_info_generate_body_content (void * body, void * data) static
Definition at line 93 of file res_pjsip_dialog_info_body_generator.c.
References ao2_cleanup, ao2_ref, ast_calloc, ast_channel_caller(), ast_channel_connected(), ast_channel_lock, ast_channel_unlock, ast_channel_unref, ast_copy_pj_str(), ast_datastores_add(), ast_datastores_alloc_datastore(), ast_datastores_find(), AST_EXTENSION_ONHOLD, ast_json_integer_create(), ast_json_integer_get(), AST_PRES_RESTRICTED, AST_PRES_RESTRICTION, ast_sip_presence_exten_state_to_str(), ast_sip_presence_xml_create_attr(), ast_sip_presence_xml_create_node(), ast_sip_sanitize_xml(), ast_sip_subscription_get_dialog(), ast_sip_subscription_get_endpoint(), ast_sip_subscription_get_persistence_data(), ast_sip_subscription_set_persistence_data(), ast_strdupa, ast_strip_quoted(), ast_strlen_zero, ast_datastore::data, ast_sip_exten_state_data::datastores, ast_sip_exten_state_data::device_state_info, ast_sip_exten_state_data::exten, ast_sip_exten_state_data::exten_state, find_ringing_channel(), ast_party_connected_line::id, ast_sip_exten_state_data::local, name, ast_sip_endpoint::notify_early_inuse_ringing, NULL, ast_party_id::number, ast_sip_exten_state_data::pool, ast_party_number::presentation, ast_sip_exten_state_data::remote, S_COR, S_OR, state, ast_sip_exten_state_data::sub, and dialog_info_xml_state::version.
 {
    pj_xml_node *dialog_info = body, *dialog, *state;
    struct ast_datastore *datastore;
    struct dialog_info_xml_state *datastore_state;
    struct ast_sip_exten_state_data *state_data = data;
    char *local = ast_strdupa(state_data->local), *stripped, *statestring = NULL;
    char *remote = ast_strdupa(state_data->remote);
    char *pidfstate = NULL, *pidfnote = NULL;
    enum ast_sip_pidf_state local_state;
    char version_str[32], sanitized[PJSIP_MAX_URL_SIZE];
    struct ast_sip_endpoint *endpoint = NULL;
    unsigned int notify_early_inuse_ringing = 0;
    if (!local || !remote || !state_data->datastores) {
       return -1;
    }
    datastore = ast_datastores_find(state_data->datastores, "dialog-info+xml");
    if (!datastore) {
       const struct ast_json *version_json = NULL;
       datastore = ast_datastores_alloc_datastore(&dialog_info_xml_datastore, "dialog-info+xml");
       if (!datastore) {
          return -1;
       }
       datastore->data = ast_calloc(1, sizeof(struct dialog_info_xml_state));
       if (!datastore->data || ast_datastores_add(state_data->datastores, datastore)) {
          ao2_ref(datastore, -1);
          return -1;
       }
       datastore_state = datastore->data;
       if (state_data->sub) {
          version_json = ast_sip_subscription_get_persistence_data(state_data->sub);
       }
       if (version_json) {
          datastore_state->version = ast_json_integer_get(version_json);
          datastore_state->version++;
       } else {
          datastore_state->version = 0;
       }
    } else {
       datastore_state = datastore->data;
       datastore_state->version++;
    }
    stripped = ast_strip_quoted(local, "<", ">");
    ast_sip_sanitize_xml(stripped, sanitized, sizeof(sanitized));
    if (state_data->sub && (endpoint = ast_sip_subscription_get_endpoint(state_data->sub))) {
        notify_early_inuse_ringing = endpoint->notify_early_inuse_ringing;
        ao2_cleanup(endpoint);
    }
    ast_sip_presence_exten_state_to_str(state_data->exten_state, &statestring,
          &pidfstate, &pidfnote, &local_state, notify_early_inuse_ringing);
    ast_sip_presence_xml_create_attr(state_data->pool, dialog_info, "xmlns", "urn:ietf:params:xml:ns:dialog-info");
    snprintf(version_str, sizeof(version_str), "%u", datastore_state->version);
    ast_sip_presence_xml_create_attr(state_data->pool, dialog_info, "version", version_str);
    if (state_data->sub) {
       ast_sip_subscription_set_persistence_data(state_data->sub, ast_json_integer_create(datastore_state->version));
    }
    ast_sip_presence_xml_create_attr(state_data->pool, dialog_info, "state", "full");
    ast_sip_presence_xml_create_attr(state_data->pool, dialog_info, "entity", sanitized);
    dialog = ast_sip_presence_xml_create_node(state_data->pool, dialog_info, "dialog");
    ast_sip_presence_xml_create_attr(state_data->pool, dialog, "id", state_data->exten);
    if (!ast_strlen_zero(statestring) && !strcmp(statestring, "early")) {
       struct ast_channel *callee = NULL;
       char local_target[PJSIP_MAX_URL_SIZE + 32] = "";
       char *local_cid_name = NULL;
       pj_xml_node *local_node, *local_identity_node, *local_target_node;
       ast_sip_presence_xml_create_attr(state_data->pool, dialog, "direction", "recipient");
       if (state_data->device_state_info) {
          callee = find_ringing_channel(state_data->device_state_info);
       }
       if (callee) {
          static char *anonymous = "anonymous";
          static char *invalid = "anonymous.invalid";
          char *remote_cid_name;
          char *remote_connected_num;
          int remote_connected_num_restricted;
          char *local_caller_num;
          pjsip_dialog *dlg = ast_sip_subscription_get_dialog(state_data->sub);
          pjsip_sip_uri *dlg_remote_fromhdr = pjsip_uri_get_uri(dlg->local.info->uri);
          char remote_target[PJSIP_MAX_URL_SIZE + 32];
          char dlg_remote_uri[PJSIP_MAX_URL_SIZE];
          char *from_domain_stripped;
          char from_domain_sanitized[PJSIP_MAX_URL_SIZE];
          pj_xml_node *remote_node, *remote_identity_node, *remote_target_node;
          /* We use the local dialog URI to determine the domain to use in the XML itself */
          ast_copy_pj_str(dlg_remote_uri, &dlg_remote_fromhdr->host, sizeof(dlg_remote_uri));
          from_domain_stripped = ast_strip_quoted(dlg_remote_uri, "<", ">");
          ast_sip_sanitize_xml(from_domain_stripped, from_domain_sanitized, sizeof(from_domain_sanitized));
          ast_channel_lock(callee);
          /* The remote node uses the connected line information, so who is calling the
           * monitored endpoint.
           */
          remote_cid_name = S_COR(ast_channel_connected(callee)->id.name.valid,
             S_COR((ast_channel_connected(callee)->id.name.presentation &
                   AST_PRES_RESTRICTION) == AST_PRES_RESTRICTED, anonymous,
                ast_channel_connected(callee)->id.name.str), "");
          remote_connected_num_restricted = (ast_channel_connected(callee)->id.number.presentation &
             AST_PRES_RESTRICTION) == AST_PRES_RESTRICTED;
          remote_connected_num = S_COR(ast_channel_connected(callee)->id.number.valid,
             S_COR(remote_connected_num_restricted, anonymous,
                ast_channel_connected(callee)->id.number.str), "invalid");
          snprintf(remote_target, sizeof(remote_target), "sip:%s@%s", remote_connected_num,
             remote_connected_num_restricted ? invalid : from_domain_sanitized);
          /* The local node uses the callerid information, so what the callerid would be
           * if the monitored endpoint was calling.
           */
          local_cid_name = S_COR(ast_channel_caller(callee)->id.name.valid,
             ast_channel_caller(callee)->id.name.str, "");
          local_caller_num = S_COR(ast_channel_caller(callee)->id.number.valid,
             ast_channel_caller(callee)->id.number.str, "invalid");
          snprintf(local_target, sizeof(local_target), "sip:%s@%s", local_caller_num,
             from_domain_sanitized);
          ast_channel_unlock(callee);
          callee = ast_channel_unref(callee);
          remote_node = ast_sip_presence_xml_create_node(state_data->pool, dialog, "remote");
          remote_identity_node = ast_sip_presence_xml_create_node(state_data->pool, remote_node, "identity");
          remote_target_node = ast_sip_presence_xml_create_node(state_data->pool, remote_node, "target");
          pj_strdup2(state_data->pool, &remote_identity_node->content, remote_target);
          if (!ast_strlen_zero(remote_cid_name)) {
             ast_sip_presence_xml_create_attr(state_data->pool, remote_identity_node, "display", remote_cid_name);
          }
          ast_sip_presence_xml_create_attr(state_data->pool, remote_target_node, "uri", remote_target);
       }
       if (state_data->device_state_info) {
          local_node = ast_sip_presence_xml_create_node(state_data->pool, dialog, "local");
          local_identity_node = ast_sip_presence_xml_create_node(state_data->pool, local_node, "identity");
          local_target_node = ast_sip_presence_xml_create_node(state_data->pool, local_node, "target");
          /* If a channel is not available we fall back to the sanitized local URI instead */
          pj_strdup2(state_data->pool, &local_identity_node->content, S_OR(local_target, sanitized));
          if (!ast_strlen_zero(local_cid_name)) {
             ast_sip_presence_xml_create_attr(state_data->pool, local_identity_node, "display", local_cid_name);
          }
          ast_sip_presence_xml_create_attr(state_data->pool, local_target_node, "uri", S_OR(local_target, sanitized));
       }
    }
    state = ast_sip_presence_xml_create_node(state_data->pool, dialog, "state");
    pj_strdup2(state_data->pool, &state->content, statestring);
    if (state_data->exten_state == AST_EXTENSION_ONHOLD) {
       pj_xml_node *local_node, *target, *param;
       local_node = ast_sip_presence_xml_create_node(state_data->pool, dialog, "local");
       target = ast_sip_presence_xml_create_node(state_data->pool, local_node, "target");
       ast_sip_presence_xml_create_attr(state_data->pool, target, "uri", sanitized);
       param = ast_sip_presence_xml_create_node(state_data->pool, target, "param");
       ast_sip_presence_xml_create_attr(state_data->pool, param, "pname", "+sip.rendering");
       ast_sip_presence_xml_create_attr(state_data->pool, param, "pvalue", "no");
    }
    ao2_ref(datastore, -1);
    return 0;
 }
dialog_info_to_string()
static void dialog_info_to_string (void * body, struct ast_str ** str) static
Definition at line 280 of file res_pjsip_dialog_info_body_generator.c.
References ast_log, AST_PJSIP_XML_PROLOG_LEN, ast_str_buffer(), ast_str_make_space, ast_str_size(), ast_str_update(), LOG_WARNING, and MAX_STRING_GROWTHS.
 {
    pj_xml_node *dialog_info = body;
    int growths = 0;
    int size;
    do {
       size = pj_xml_print(dialog_info, ast_str_buffer(*str), ast_str_size(*str) - 1, PJ_TRUE);
       if (size <= AST_PJSIP_XML_PROLOG_LEN) {
          ast_str_make_space(str, ast_str_size(*str) * 2);
          ++growths;
       }
    } while (size <= AST_PJSIP_XML_PROLOG_LEN && growths < MAX_STRING_GROWTHS);
    if (size <= AST_PJSIP_XML_PROLOG_LEN) {
       ast_log(LOG_WARNING, "dialog-info+xml body text too large\n");
       return;
    }
    *(ast_str_buffer(*str) + size) = '\0';
    ast_str_update(*str);
 }
dialog_info_xml_state_destroy()
static void dialog_info_xml_state_destroy (void * obj) static
Destructor for dialog-info+xml information.
Definition at line 46 of file res_pjsip_dialog_info_body_generator.c.
References ast_free.
 {
    ast_free(obj);
 }
find_ringing_channel()
static struct ast_channel* find_ringing_channel (struct ao2_container * device_state_info) static
Definition at line 68 of file res_pjsip_dialog_info_body_generator.c.
References ao2_iterator_destroy(), ao2_iterator_init(), ao2_iterator_next, ao2_ref, ast_channel_creationtime(), ast_channel_lock, ast_channel_ref, ast_channel_unlock, AST_DEVICE_RINGING, AST_DEVICE_RINGINUSE, ast_tvcmp(), ast_tvzero(), c, ast_device_state_info::causing_channel, ast_device_state_info::device_state, and NULL.
Referenced by dialog_info_generate_body_content().
 {
    struct ao2_iterator citer;
    struct ast_device_state_info *device_state;
    struct ast_channel *c = NULL;
    struct timeval tv = {0,};
    /* iterate ringing devices and get the oldest of all causing channels */
    citer = ao2_iterator_init(device_state_info, 0);
    for (; (device_state = ao2_iterator_next(&citer)); ao2_ref(device_state, -1)) {
       if (!device_state->causing_channel || (device_state->device_state != AST_DEVICE_RINGING &&
             device_state->device_state != AST_DEVICE_RINGINUSE)) {
          continue;
       }
       ast_channel_lock(device_state->causing_channel);
       if (ast_tvzero(tv) || ast_tvcmp(ast_channel_creationtime(device_state->causing_channel), tv) < 0) {
          c = device_state->causing_channel;
          tv = ast_channel_creationtime(c);
       }
       ast_channel_unlock(device_state->causing_channel);
    }
    ao2_iterator_destroy(&citer);
    return c ? ast_channel_ref(c) : NULL;
 }
load_module()
static int load_module (void) static
Definition at line 312 of file res_pjsip_dialog_info_body_generator.c.
References AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, and ast_sip_pubsub_register_body_generator().
Referenced by unload_module().
 {
    if (ast_sip_pubsub_register_body_generator(&dialog_info_body_generator)) {
       return AST_MODULE_LOAD_DECLINE;
    }
    return AST_MODULE_LOAD_SUCCESS;
 }
unload_module()
static int unload_module (void) static
Definition at line 321 of file res_pjsip_dialog_info_body_generator.c.
References AST_MODFLAG_LOAD_ORDER, AST_MODPRI_CHANNEL_DEPEND, AST_MODULE_INFO(), AST_MODULE_SUPPORT_CORE, ast_sip_pubsub_unregister_body_generator(), ASTERISK_GPL_KEY, and load_module().
 {
    ast_sip_pubsub_unregister_body_generator(&dialog_info_body_generator);
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "PJSIP Extension State Dialog Info+XML Provider" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_CHANNEL_DEPEND, .requires = "res_pjsip,res_pjsip_pubsub", } static
Definition at line 333 of file res_pjsip_dialog_info_body_generator.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 333 of file res_pjsip_dialog_info_body_generator.c.
dialog_info_body_generator
struct ast_sip_pubsub_body_generator dialog_info_body_generator static
Definition at line 302 of file res_pjsip_dialog_info_body_generator.c.
dialog_info_xml_datastore
const struct ast_datastore_info dialog_info_xml_datastore static
Initial value:
= {
   .type = "dialog-info+xml",
   .destroy = dialog_info_xml_state_destroy,
}
Datastore for attaching dialog-info+xml state information.
Definition at line 52 of file res_pjsip_dialog_info_body_generator.c.