Asterisk - The Open Source Telephony Project: func_rand.c File Reference
func_rand.c File Reference
Module: Dial plan functions
Generate Random Number.
#include "asterisk.h"
#include "asterisk/module.h"
#include "asterisk/channel.h"
#include "asterisk/pbx.h"
#include "asterisk/utils.h"
#include "asterisk/app.h"
Functions
static void __reg_module (void)
static void __unreg_module (void)
static int acf_rand_exec (struct ast_channel *chan, const char *cmd, char *parse, char *buffer, size_t buflen)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int load_module (void)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Random number dialplan function" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, }
static struct ast_custom_function acf_rand
static const struct ast_module_info * ast_module_info = &__mod_info
Detailed Description
Generate Random Number.
Author
Claude Patry cpatr.nosp@m.y@gm.nosp@m.ail.c.nosp@m.om
Tilghman Lesher (http://asterisk.drunkcoder.com/)
Definition in file func_rand.c.
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 107 of file func_rand.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 107 of file func_rand.c.
acf_rand_exec()
static int acf_rand_exec (struct ast_channel * chan, const char * cmd, char * parse, char * buffer, size_t buflen) static
Definition at line 57 of file func_rand.c.
References args, AST_APP_ARG, ast_debug, AST_DECLARE_APP_ARGS, ast_random(), AST_STANDARD_APP_ARGS, ast_strlen_zero, max, min, and tmp().
 {
    int min_int, response_int, max_int;
    AST_DECLARE_APP_ARGS(args,
               AST_APP_ARG(min);
               AST_APP_ARG(max);
    );
    AST_STANDARD_APP_ARGS(args, parse);
    if (ast_strlen_zero(args.min) || sscanf(args.min, "%30d", &min_int) != 1)
       min_int = 0;
    if (ast_strlen_zero(args.max) || sscanf(args.max, "%30d", &max_int) != 1)
       max_int = RAND_MAX;
    if (max_int < min_int) {
       int tmp = max_int;
       max_int = min_int;
       min_int = tmp;
       ast_debug(1, "max<min\n");
    }
    response_int = min_int + (ast_random() % (max_int - min_int + 1));
    ast_debug(1, "%d was the lucky number in range [%d,%d]\n", response_int, min_int, max_int);
    snprintf(buffer, buflen, "%d", response_int);
    return 0;
 }
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 107 of file func_rand.c.
load_module()
static int load_module (void) static
Definition at line 102 of file func_rand.c.
References ast_custom_function_register.
 {
    return ast_custom_function_register(&acf_rand);
 }
unload_module()
static int unload_module (void) static
Definition at line 95 of file func_rand.c.
References ast_custom_function_unregister().
 {
    ast_custom_function_unregister(&acf_rand);
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Random number dialplan function" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, } static
Definition at line 107 of file func_rand.c.
acf_rand
struct ast_custom_function acf_rand static
Initial value:
= {
   .name = "RAND",
   .read = acf_rand_exec,
   .read_max = 12,
}
Definition at line 89 of file func_rand.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 107 of file func_rand.c.