Asterisk - The Open Source Telephony Project: rec_utils.c File Reference
rec_utils.c File Reference
#include <sys/param.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "../include/db.h"
#include "recno.h"
Functions
int __rec_ret (BTREE *t, EPG *e, recno_t nrec, DBT *key, DBT *data)
Function Documentation
__rec_ret()
int __rec_ret (BTREE * t, EPG * e, recno_t nrec, DBT * key, DBT * data)
Definition at line 62 of file rec_utils.c.
References __ovfl_get(), B_DB_LOCK, _btree::bt_rdata, _btree::bt_rkey, _rleaf::bytes, DBT::data, _rleaf::dsize, F_ISSET, _rleaf::flags, GETRLEAF, _epg::index, malloc(), NULL, P_BIGDATA, _epg::page, realloc, RET_ERROR, RET_SUCCESS, and DBT::size.
Referenced by __rec_get(), __rec_put(), and __rec_seq().
 {
    RLEAF *rl;
    void *p;
    if (key == NULL)
       goto dataonly;
    /* We have to copy the key, it's not on the page. */
    if (sizeof(recno_t) > t->bt_rkey.size) {
       p = (void *)(t->bt_rkey.data == NULL ?
           malloc(sizeof(recno_t)) :
           realloc(t->bt_rkey.data, sizeof(recno_t)));
       if (p == NULL)
          return (RET_ERROR);
       t->bt_rkey.data = p;
       t->bt_rkey.size = sizeof(recno_t);
    }
    memmove(t->bt_rkey.data, &nrec, sizeof(recno_t));
    key->size = sizeof(recno_t);
    key->data = t->bt_rkey.data;
 dataonly:
    if (data == NULL)
       return (RET_SUCCESS);
    /*
     * We must copy big keys/data to make them contiguous.  Otherwise,
     * leave the page pinned and don't copy unless the user specified
     * concurrent access.
     */
    rl = GETRLEAF(e->page, e->index);
    if (rl->flags & P_BIGDATA) {
       if (__ovfl_get(t, rl->bytes,
           &data->size, &t->bt_rdata.data, &t->bt_rdata.size))
          return (RET_ERROR);
       data->data = t->bt_rdata.data;
    } else if (F_ISSET(t, B_DB_LOCK)) {
       /* Use +1 in case the first record retrieved is 0 length. */
       if (rl->dsize + 1 > t->bt_rdata.size) {
          p = (void *)(t->bt_rdata.data == NULL ?
              malloc(rl->dsize + 1) :
              realloc(t->bt_rdata.data, rl->dsize + 1));
          if (p == NULL)
             return (RET_ERROR);
          t->bt_rdata.data = p;
          t->bt_rdata.size = rl->dsize + 1;
       }
       memmove(t->bt_rdata.data, rl->bytes, rl->dsize);
       data->size = rl->dsize;
       data->data = t->bt_rdata.data;
    } else {
       data->size = rl->dsize;
       data->data = rl->bytes;
    }
    return (RET_SUCCESS);
 }