Asterisk - The Open Source Telephony Project: Dial plan applications
Dial plan applications
Applications support the dialplan. They register dynamically with.
Files
file app_adsiprog.c
Program Asterisk ADSI Scripts into phone.
file app_alarmreceiver.c
Central Station Alarm receiver for Ademco Contact ID.
file app_amd.c
Answering machine detection.
file app_attended_transfer.c
Attended transfer by caller channel.
file app_audiosocket.c
AudioSocket application – transmit and receive audio through a TCP socket.
file app_authenticate.c
Execute arbitrary authenticate commands.
file app_blind_transfer.c
Blind transfer by caller channel.
file app_bridgeaddchan.c
Application to place the channel into an existing Bridge.
file app_bridgewait.c
Application to place the channel into a holding Bridge.
file app_cdr.c
Applications connected with CDR engine.
file app_celgenuserevent.c
Generate User-Defined CEL event.
file app_chanisavail.c
Check if Channel is Available.
file app_channelredirect.c
ChannelRedirect application.
file app_chanspy.c
ChanSpy: Listen in on any channel.
file app_confbridge.c
Conference Bridge application.
file app_controlplayback.c
Trivial application to control playback of a sound file.
file app_dahdiras.c
Execute an ISDN RAS.
file app_db.c
Database access functions.
file app_dial.c
dial() & retrydial() - Trivial application to dial a channel and send an URL on answer
file app_dictate.c
Virtual Dictation Machine Application For Asterisk.
file app_directed_pickup.c
Directed Call Pickup Support.
file app_directory.c
Provide a directory of extensions.
file app_disa.c
DISA – Direct Inward System Access Application.
file app_dumpchan.c
Application to dump channel variables.
file app_echo.c
Echo application – play back what you hear to evaluate latency.
file app_exec.c
Exec application.
file app_externalivr.c
External IVR application interface.
file app_festival.c
Connect to festival.
file app_flash.c
App to flash a DAHDI trunk.
file app_followme.c
Find-Me Follow-Me application.
file app_forkcdr.c
Fork CDR application.
file app_getcpeid.c
Get ADSI CPE ID.
file app_ices.c
Stream to an icecast server via ICES (see contrib/asterisk-ices.xml)
file app_if.c
If Branch Implementation.
file app_image.c
App to transmit an image.
file app_ivrdemo.c
IVR Demo application.
file app_jack.c
Jack Application.
file app_macro.c
Dial plan macro Implementation.
file app_meetme.c
Meet me conference bridge and Shared Line Appearances.
file app_mf.c
MF sender and receiver applications.
file app_milliwatt.c
Digital Milliwatt Test.
file app_minivm.c
MiniVoiceMail - A Minimal Voicemail System for Asterisk.
file app_mixmonitor.c
MixMonitor() - Record a call and mix the audio during the recording.
file app_morsecode.c
Morsecode application.
file app_mp3.c
Silly application to play an MP3 file – uses mpg123.
file app_mysql.c
MYSQL dialplan application.
file app_nbscat.c
Silly application to play an NBScat file – uses nbscat8k.
file app_originate.c
Originate application.
file app_osplookup.c
Open Settlement Protocol (OSP) Applications.
file app_page.c
page() - Paging application
file app_playback.c
Trivial application to playback a sound file.
file app_playtones.c
Playtones application.
file app_privacy.c
Block all calls without Caller*ID, require phone # to be entered.
file app_queue.c
True call queues with optional send URL on answer.
file app_read.c
Trivial application to read a variable.
file app_readexten.c
Trivial application to read an extension into a variable.
file app_record.c
Trivial application to record a sound file.
file app_saycounted.c
Applications to decline words according to current language.
file app_sayunixtime.c
SayUnixTime application.
file app_senddtmf.c
App to send DTMF digits.
file app_sendtext.c
App to transmit a text message.
file app_skel.c
Skeleton application.
file app_sms.c
SMS application - ETSI ES 201 912 protocol 1 implementation.
file app_softhangup.c
SoftHangup application.
file app_speech_utils.c
Speech Recognition Utility Applications.
file app_stack.c
Stack applications Gosub, Return, etc.
file app_system.c
Execute arbitrary system commands.
file app_talkdetect.c
Playback a file with audio detect.
file app_test.c
Applications to test connection and produce report in text file.
file app_tonedetect.c
Tone detection module.
file app_transfer.c
Transfer a caller.
file app_url.c
App to transmit a URL.
file app_userevent.c
UserEvent application – send manager event.
file app_verbose.c
Verbose logging application.
file app_voicemail.c
Comedian Mail - Voicemail System.
file app_waitforring.c
Wait for Ring Application.
file app_waitforsilence.c
Wait for Silence.
file app_waituntil.c
Sleep until the given epoch.
file app_while.c
While Loop Implementation.
file app_zapateller.c
Playback the special information tone to get rid of telemarketers.
file conf_state.c
Confbridge state handling.
file conf_state_empty.c
Confbridge state handling for the EMPTY state.
file conf_state_inactive.c
Confbridge state handling for the INACTIVE state.
file conf_state_multi.c
Confbridge state handling for the MULTI state.
file conf_state_multi_marked.c
Confbridge state handling for the MULTI_MARKED state.
file conf_state_single.c
Confbridge state handling for the SINGLE state.
file conf_state_single_marked.c
Confbridge state handling for the SINGLE_MARKED state.
file res_ael_share.c
Shareable AEL code – mainly between internal and external modules.
file res_fax.c
Generic FAX Resource for FAX technology resource modules.
file res_format_attr_h263.c
H.263 Format Attribute Module.
file res_format_attr_h264.c
H.264 Format Attribute Module.
file res_realtime.c
RealTime CLI.
Functions
static int iax2_prov_app (struct ast_channel *chan, const char *data)
int indicate_busy (struct ast_channel *chan, const char *data)
int indicate_congestion (struct ast_channel *chan, const char *data)
static int pbx_builtin_answer (struct ast_channel *chan, const char *data)
static int pbx_builtin_background (struct ast_channel *chan, const char *data)
static int pbx_builtin_execiftime (struct ast_channel *chan, const char *data)
static int pbx_builtin_goto (struct ast_channel *chan, const char *data)
static int pbx_builtin_gotoiftime (struct ast_channel *chan, const char *data)
static int pbx_builtin_hangup (struct ast_channel *chan, const char *data)
static int pbx_builtin_proceeding (struct ast_channel *chan, const char *data)
static int pbx_builtin_progress (struct ast_channel *chan, const char *data)
static int pbx_builtin_ringing (struct ast_channel *chan, const char *data)
static int pbx_builtin_setamaflags (struct ast_channel *chan, const char *data)
static int pbx_builtin_wait (struct ast_channel *chan, const char *data)
static int pbx_builtin_waitdigit (struct ast_channel *chan, const char *data)
static int pbx_builtin_waitexten (struct ast_channel *chan, const char *data)
Detailed Description
Applications support the dialplan. They register dynamically with.
Asterisk Dial Plan Applications
See also
ast_register_application() and unregister with
ast_unregister_application()
See also
Module: Dial plan functions
Function Documentation
iax2_prov_app()
static int iax2_prov_app (struct ast_channel * chan, const char * data) static
iax2provision
Definition at line 12249 of file chan_iax2.c.
References ast_channel_tech(), ast_channel_tech_pvt(), ast_log, ast_sockaddr_isnull(), ast_sockaddr_stringify(), ast_strdupa, ast_strlen_zero, ast_verb, iax2_provision(), LOG_NOTICE, NULL, and PTR_TO_CALLNO.
Referenced by load_module().
 {
    int res;
    char *sdata;
    char *opts;
    int force =0;
    unsigned short callno = PTR_TO_CALLNO(ast_channel_tech_pvt(chan));
    if (ast_strlen_zero(data))
       data = "default";
    sdata = ast_strdupa(data);
    opts = strchr(sdata, '|');
    if (opts)
       *opts='\0';
    if (ast_channel_tech(chan) != &iax2_tech) {
       ast_log(LOG_NOTICE, "Can't provision a non-IAX device!\n");
       return -1;
    }
    if (!callno || !iaxs[callno] || ast_sockaddr_isnull(&iaxs[callno]->addr)) {
       ast_log(LOG_NOTICE, "Can't provision something with no IP?\n");
       return -1;
    }
    res = iax2_provision(&iaxs[callno]->addr, iaxs[callno]->sockfd, NULL, sdata, force);
    ast_verb(3, "Provisioned IAXY at '%s' with '%s'= %d\n",
       ast_sockaddr_stringify(&iaxs[callno]->addr),
       sdata, res);
    return res;
 }
indicate_busy()
int indicate_busy (struct ast_channel * chan, const char * data)
Definition at line 739 of file pbx_builtins.c.
References AST_CAUSE_BUSY, ast_channel_hangupcause_set(), ast_channel_lock, ast_channel_unlock, AST_CONTROL_BUSY, ast_indicate(), ast_setstate(), AST_STATE_BUSY, AST_STATE_UP, and wait_for_hangup().
Referenced by __ast_pbx_run().
 {
    ast_indicate(chan, AST_CONTROL_BUSY);
    /* Don't change state of an UP channel, just indicate
       busy in audio */
    ast_channel_lock(chan);
    if (ast_channel_state(chan) != AST_STATE_UP) {
       ast_channel_hangupcause_set(chan, AST_CAUSE_BUSY);
       ast_setstate(chan, AST_STATE_BUSY);
    }
    ast_channel_unlock(chan);
    wait_for_hangup(chan, data);
    return -1;
 }
indicate_congestion()
int indicate_congestion (struct ast_channel * , const char *)
pbx_builtins.c functions needed by pbx.c
Definition at line 757 of file pbx_builtins.c.
References AST_CAUSE_CONGESTION, ast_channel_hangupcause_set(), ast_channel_lock, ast_channel_unlock, AST_CONTROL_CONGESTION, ast_indicate(), ast_setstate(), AST_STATE_BUSY, AST_STATE_UP, and wait_for_hangup().
Referenced by __ast_pbx_run().
 {
    ast_indicate(chan, AST_CONTROL_CONGESTION);
    /* Don't change state of an UP channel, just indicate
       congestion in audio */
    ast_channel_lock(chan);
    if (ast_channel_state(chan) != AST_STATE_UP) {
       ast_channel_hangupcause_set(chan, AST_CAUSE_CONGESTION);
       ast_setstate(chan, AST_STATE_BUSY);
    }
    ast_channel_unlock(chan);
    wait_for_hangup(chan, data);
    return -1;
 }
pbx_builtin_answer()
static int pbx_builtin_answer (struct ast_channel * chan, const char * data) static
Definition at line 775 of file pbx_builtins.c.
References __ast_answer(), args, AST_APP_ARG, AST_DECLARE_APP_ARGS, ast_log, AST_LOG_WARNING, AST_STANDARD_APP_ARGS, AST_STATE_UP, ast_strdupa, ast_strlen_zero, and parse().
 {
    int delay = 0;
    char *parse;
    AST_DECLARE_APP_ARGS(args,
       AST_APP_ARG(delay);
       AST_APP_ARG(answer_cdr);
    );
    if (ast_strlen_zero(data)) {
       return __ast_answer(chan, 0);
    }
    parse = ast_strdupa(data);
    AST_STANDARD_APP_ARGS(args, parse);
    if (!ast_strlen_zero(args.delay) && (ast_channel_state(chan) != AST_STATE_UP))
       delay = atoi(data);
    if (delay < 0) {
       delay = 0;
    }
    if (!ast_strlen_zero(args.answer_cdr) && !strcasecmp(args.answer_cdr, "nocdr")) {
       ast_log(AST_LOG_WARNING, "The nocdr option for the Answer application has been removed and is no longer supported.\n");
    }
    return __ast_answer(chan, delay);
 }
pbx_builtin_background()
static int pbx_builtin_background (struct ast_channel * chan, const char * data) static
Definition at line 1144 of file pbx_builtins.c.
References args, ast_answer(), AST_APP_ARG, ast_app_parse_options(), ast_canmatch_extension(), ast_channel_caller(), ast_channel_context(), ast_channel_context_set(), ast_channel_exten_set(), ast_channel_flags(), ast_channel_language(), ast_channel_lock, ast_channel_name(), ast_channel_priority_set(), ast_channel_unlock, AST_DECLARE_APP_ARGS, AST_DIGIT_ANY, AST_FLAG_DISABLE_WORKAROUNDS, ast_log, ast_matchmore_extension(), AST_STANDARD_APP_ARGS, AST_STATE_UP, ast_stopstream(), ast_strdupa, ast_streamfile(), ast_strip(), ast_strlen_zero, ast_test_flag, ast_waitstream(), ast_waitstream_exten(), BACKGROUND_MATCHEXTEN, BACKGROUND_NOANSWER, background_opts, BACKGROUND_PLAYBACK, BACKGROUND_SKIP, buf, context, done, exten, ast_flags::flags, LOG_WARNING, NULL, options, parse(), pbx_builtin_getvar_helper(), pbx_builtin_setvar_helper(), S_COR, and strsep().
 {
    int res = 0;
    int mres = 0;
    struct ast_flags flags = {0};
    char *parse, exten[2] = "";
    AST_DECLARE_APP_ARGS(args,
       AST_APP_ARG(filename);
       AST_APP_ARG(options);
       AST_APP_ARG(lang);
       AST_APP_ARG(context);
    );
    if (ast_strlen_zero(data)) {
       ast_log(LOG_WARNING, "Background requires an argument (filename)\n");
       return -1;
    }
    parse = ast_strdupa(data);
    AST_STANDARD_APP_ARGS(args, parse);
    if (ast_strlen_zero(args.lang))
       args.lang = (char *)ast_channel_language(chan); /* XXX this is const */
    if (ast_strlen_zero(args.context)) {
       const char *context;
       ast_channel_lock(chan);
       if ((context = pbx_builtin_getvar_helper(chan, "MACRO_CONTEXT"))) {
          args.context = ast_strdupa(context);
       } else {
          args.context = ast_strdupa(ast_channel_context(chan));
       }
       ast_channel_unlock(chan);
    }
    if (args.options) {
       if (!strcasecmp(args.options, "skip"))
          flags.flags = BACKGROUND_SKIP;
       else if (!strcasecmp(args.options, "noanswer"))
          flags.flags = BACKGROUND_NOANSWER;
       else
          ast_app_parse_options(background_opts, &flags, NULL, args.options);
    }
    /* Answer if need be */
    if (ast_channel_state(chan) != AST_STATE_UP) {
       if (ast_test_flag(&flags, BACKGROUND_SKIP)) {
          goto done;
       } else if (!ast_test_flag(&flags, BACKGROUND_NOANSWER)) {
          res = ast_answer(chan);
       }
    }
    if (!res) {
       char *back = ast_strip(args.filename);
       char *front;
       ast_stopstream(chan);      /* Stop anything playing */
       /* Stream the list of files */
       while (!res && (front = strsep(&back, "&")) ) {
          if ( (res = ast_streamfile(chan, front, args.lang)) ) {
             ast_log(LOG_WARNING, "ast_streamfile failed on %s for %s\n", ast_channel_name(chan), (char*)data);
             res = 0;
             mres = 1;
             break;
          }
          if (ast_test_flag(&flags, BACKGROUND_PLAYBACK)) {
             res = ast_waitstream(chan, "");
          } else if (ast_test_flag(&flags, BACKGROUND_MATCHEXTEN)) {
             res = ast_waitstream_exten(chan, args.context);
          } else {
             res = ast_waitstream(chan, AST_DIGIT_ANY);
          }
          ast_stopstream(chan);
       }
    }
    /* If ast_waitstream didn't give us back a digit, there is nothing else to do */
    if (res <= 0) {
       goto done;
    }
    exten[0] = res;
    /*
     * If the single digit DTMF is an extension in the specified context, then
     * go there and signal no DTMF.  Otherwise, we should exit with that DTMF.
     * If we're in Macro, we'll exit and seek that DTMF as the beginning of an
     * extension in the Macro's calling context.  If we're not in Macro, then
     * we'll simply seek that extension in the calling context.  Previously,
     * someone complained about the behavior as it related to the interior of a
     * Gosub routine, and the fix (#14011) inadvertently broke FreePBX
     * (#14940).  This change should fix both of these situations, but with the
     * possible incompatibility that if a single digit extension does not exist
     * (but a longer extension COULD have matched), it would have previously
     * gone immediately to the "i" extension, but will now need to wait for a
     * timeout.
     *
     * Later, we had to add a flag to disable this workaround, because AGI
     * users can EXEC Background and reasonably expect that the DTMF code will
     * be returned (see #16434).
     */
    if (!ast_test_flag(ast_channel_flags(chan), AST_FLAG_DISABLE_WORKAROUNDS)
       && ast_canmatch_extension(chan, args.context, exten, 1,
          S_COR(ast_channel_caller(chan)->id.number.valid, ast_channel_caller(chan)->id.number.str, NULL))
       && !ast_matchmore_extension(chan, args.context, exten, 1,
          S_COR(ast_channel_caller(chan)->id.number.valid, ast_channel_caller(chan)->id.number.str, NULL))) {
       char buf[2] = { 0, };
       snprintf(buf, sizeof(buf), "%c", res);
       ast_channel_exten_set(chan, buf);
       ast_channel_context_set(chan, args.context);
       ast_channel_priority_set(chan, 0);
       res = 0;
    }
 done:
    pbx_builtin_setvar_helper(chan, "BACKGROUNDSTATUS", mres ? "FAILED" : "SUCCESS");
    return res;
 }
pbx_builtin_execiftime()
static int pbx_builtin_execiftime (struct ast_channel * chan, const char * data) static
Definition at line 959 of file pbx_builtins.c.
References app, ast_build_timing(), ast_check_timing(), ast_destroy_timing(), ast_log, ast_strdupa, ast_strlen_zero, LOG_WARNING, pbx_exec(), pbx_findapp(), S_OR, strsep(), and usage.
 {
    char *s, *appname;
    struct ast_timing timing;
    struct ast_app *app;
    static const char * const usage = "ExecIfTime requires an argument:\n  <time range>,<days of week>,<days of month>,<months>[,<timezone>]?<appname>[(<appargs>)]";
    if (ast_strlen_zero(data)) {
       ast_log(LOG_WARNING, "%s\n", usage);
       return -1;
    }
    appname = ast_strdupa(data);
    s = strsep(&appname, "?"); /* Separate the timerange and application name/data */
    if (!appname) {   /* missing application */
       ast_log(LOG_WARNING, "%s\n", usage);
       return -1;
    }
    if (!ast_build_timing(&timing, s)) {
       ast_log(LOG_WARNING, "Invalid Time Spec: %s\nCorrect usage: %s\n", s, usage);
       ast_destroy_timing(&timing);
       return -1;
    }
    if (!ast_check_timing(&timing))  { /* outside the valid time window, just return */
       ast_destroy_timing(&timing);
       return 0;
    }
    ast_destroy_timing(&timing);
    /* now split appname(appargs) */
    if ((s = strchr(appname, '('))) {
       char *e;
       *s++ = '\0';
       if ((e = strrchr(s, ')')))
          *e = '\0';
       else
          ast_log(LOG_WARNING, "Failed to find closing parenthesis\n");
    }
    if ((app = pbx_findapp(appname))) {
       return pbx_exec(chan, app, S_OR(s, ""));
    } else {
       ast_log(LOG_WARNING, "Cannot locate application %s\n", appname);
       return -1;
    }
 }
pbx_builtin_goto()
static int pbx_builtin_goto (struct ast_channel * chan, const char * data) static
Goto
Definition at line 894 of file pbx_builtins.c.
References ast_channel_context(), ast_channel_exten(), ast_channel_priority(), ast_parseable_goto(), and ast_verb.
Referenced by pbx_builtin_gotoif(), and pbx_builtin_gotoiftime().
 {
    int res = ast_parseable_goto(chan, data);
    if (!res)
       ast_verb(3, "Goto (%s,%s,%d)\n", ast_channel_context(chan), ast_channel_exten(chan), ast_channel_priority(chan) + 1);
    return res;
 }
pbx_builtin_gotoiftime()
static int pbx_builtin_gotoiftime (struct ast_channel * chan, const char * data) static
Definition at line 905 of file pbx_builtins.c.
References ast_build_timing(), ast_channel_lock, ast_channel_unlock, ast_check_timing2(), ast_debug, ast_destroy_timing(), ast_log, ast_strdupa, ast_strlen_zero, ast_tvnow(), LOG_WARNING, NULL, pbx_builtin_getvar_helper(), pbx_builtin_goto(), pbx_builtin_setvar_helper(), and strsep().
 {
    char *s, *ts, *branch1, *branch2, *branch;
    struct ast_timing timing;
    const char *ctime;
    struct timeval tv = ast_tvnow();
    long timesecs;
    if (!chan) {
       ast_log(LOG_WARNING, "GotoIfTime requires a channel on which to operate\n");
       return -1;
    }
    if (ast_strlen_zero(data)) {
       ast_log(LOG_WARNING, "GotoIfTime requires an argument:\n  <time range>,<days of week>,<days of month>,<months>[,<timezone>]?'labeliftrue':'labeliffalse'\n");
       return -1;
    }
    ts = s = ast_strdupa(data);
    ast_channel_lock(chan);
    if ((ctime = pbx_builtin_getvar_helper(chan, "TESTTIME")) && sscanf(ctime, "%ld", &timesecs) == 1) {
       tv.tv_sec = timesecs;
    } else if (ctime) {
       ast_log(LOG_WARNING, "Using current time to evaluate\n");
       /* Reset when unparseable */
       pbx_builtin_setvar_helper(chan, "TESTTIME", NULL);
    }
    ast_channel_unlock(chan);
    /* Separate the Goto path */
    strsep(&ts, "?");
    branch1 = strsep(&ts,":");
    branch2 = strsep(&ts,"");
    /* struct ast_include include contained garbage here, fixed by zeroing it on get_timerange */
    if (ast_build_timing(&timing, s) && ast_check_timing2(&timing, tv)) {
       branch = branch1;
    } else {
       branch = branch2;
    }
    ast_destroy_timing(&timing);
    if (ast_strlen_zero(branch)) {
       ast_debug(1, "Not taking any branch\n");
       return 0;
    }
    return pbx_builtin_goto(chan, branch);
 }
pbx_builtin_hangup()
static int pbx_builtin_hangup (struct ast_channel * chan, const char * data) static
Definition at line 859 of file pbx_builtins.c.
References AST_CAUSE_NORMAL_CLEARING, ast_channel_hangupcause(), ast_channel_hangupcause_set(), ast_channel_lock, ast_channel_unlock, ast_log, ast_set_hangupsource(), AST_SOFTHANGUP_EXPLICIT, ast_softhangup_nolock(), ast_str2cause(), ast_strlen_zero, and LOG_WARNING.
 {
    int cause;
    ast_set_hangupsource(chan, "dialplan/builtin", 0);
    if (!ast_strlen_zero(data)) {
       cause = ast_str2cause(data);
       if (cause <= 0) {
          if (sscanf(data, "%30d", &cause) != 1 || cause <= 0) {
             ast_log(LOG_WARNING, "Invalid cause given to Hangup(): \"%s\"\n", data);
             cause = 0;
          }
       }
    } else {
       cause = 0;
    }
    ast_channel_lock(chan);
    if (cause <= 0) {
       cause = ast_channel_hangupcause(chan);
       if (cause <= 0) {
          cause = AST_CAUSE_NORMAL_CLEARING;
       }
    }
    ast_channel_hangupcause_set(chan, cause);
    ast_softhangup_nolock(chan, AST_SOFTHANGUP_EXPLICIT);
    ast_channel_unlock(chan);
    return -1;
 }
pbx_builtin_proceeding()
static int pbx_builtin_proceeding (struct ast_channel * chan, const char * data) static
Definition at line 712 of file pbx_builtins.c.
References AST_CONTROL_PROCEEDING, and ast_indicate().
 {
    ast_indicate(chan, AST_CONTROL_PROCEEDING);
    return 0;
 }
pbx_builtin_progress()
static int pbx_builtin_progress (struct ast_channel * chan, const char * data) static
Definition at line 721 of file pbx_builtins.c.
References AST_CONTROL_PROGRESS, and ast_indicate().
 {
    ast_indicate(chan, AST_CONTROL_PROGRESS);
    return 0;
 }
pbx_builtin_ringing()
static int pbx_builtin_ringing (struct ast_channel * chan, const char * data) static
Definition at line 730 of file pbx_builtins.c.
References AST_CONTROL_RINGING, and ast_indicate().
 {
    ast_indicate(chan, AST_CONTROL_RINGING);
    return 0;
 }
pbx_builtin_setamaflags()
static int pbx_builtin_setamaflags (struct ast_channel * chan, const char * data) static
Definition at line 831 of file pbx_builtins.c.
References amaflags, ast_channel_amaflags_set(), ast_channel_lock, ast_channel_name(), ast_channel_string2amaflag(), ast_channel_unlock, ast_log, AST_LOG_WARNING, and ast_strlen_zero.
 {
    ast_log(AST_LOG_WARNING, "The SetAMAFlags application is deprecated. Please use the CHANNEL function instead.\n");
    if (ast_strlen_zero(data)) {
       ast_log(AST_LOG_WARNING, "No parameter passed to SetAMAFlags\n");
       return 0;
    }
    /* Copy the AMA Flags as specified */
    ast_channel_lock(chan);
    if (isdigit(data[0])) {
       int amaflags;
       if (sscanf(data, "%30d", &amaflags) != 1) {
          ast_log(AST_LOG_WARNING, "Unable to set AMA flags on channel %s\n", ast_channel_name(chan));
          ast_channel_unlock(chan);
          return 0;
       }
       ast_channel_amaflags_set(chan, amaflags);
    } else {
       ast_channel_amaflags_set(chan, ast_channel_string2amaflag(data));
    }
    ast_channel_unlock(chan);
    return 0;
 }
pbx_builtin_wait()
static int pbx_builtin_wait (struct ast_channel * chan, const char * data) static
Definition at line 1013 of file pbx_builtins.c.
References ast_app_parse_timelen(), ast_safe_sleep(), and TIMELEN_SECONDS.
 {
    int ms;
    /* Wait for "n" seconds */
    if (!ast_app_parse_timelen(data, &ms, TIMELEN_SECONDS) && ms > 0) {
       return ast_safe_sleep(chan, ms);
    }
    return 0;
 }
pbx_builtin_waitdigit()
static int pbx_builtin_waitdigit (struct ast_channel * chan, const char * data) static
Definition at line 1027 of file pbx_builtins.c.
References args, AST_APP_ARG, ast_app_parse_timelen(), AST_DECLARE_APP_ARGS, AST_DIGIT_ANY, AST_STANDARD_APP_ARGS, ast_strdupa, ast_waitfordigit_full(), parse(), pbx_builtin_setvar_helper(), S_OR, TIMELEN_SECONDS, and timeout.
 {
    int res;
    int ms;
    char *parse;
    AST_DECLARE_APP_ARGS(args,
       AST_APP_ARG(timeout);
       AST_APP_ARG(digits);
    );
    parse = ast_strdupa(data);
    AST_STANDARD_APP_ARGS(args, parse);
    if (ast_app_parse_timelen(args.timeout, &ms, TIMELEN_SECONDS) || ms < 0) {
       pbx_builtin_setvar_helper(chan, "WAITDIGITSTATUS", "ERROR");
       return 0;
    }
    /* Wait for "n" seconds */
    res = ast_waitfordigit_full(chan, ms, S_OR(args.digits, AST_DIGIT_ANY), -1, -1);
    if (res < 0) {
       pbx_builtin_setvar_helper(chan, "WAITDIGITSTATUS", "CANCEL");
       return -1;
    }
    if (res == 0) {
       pbx_builtin_setvar_helper(chan, "WAITDIGITSTATUS", "TIMEOUT");
    } else {
       char key[2];
       snprintf(key, sizeof(key), "%c", res);
       pbx_builtin_setvar_helper(chan, "WAITDIGITRESULT", key);
       pbx_builtin_setvar_helper(chan, "WAITDIGITSTATUS", "DTMF");
    }
    return 0;
 }
pbx_builtin_waitexten()
static int pbx_builtin_waitexten (struct ast_channel * chan, const char * data) static
Definition at line 1068 of file pbx_builtins.c.
References args, AST_APP_ARG, ast_app_parse_options(), ast_app_parse_timelen(), ast_channel_caller(), ast_channel_context(), ast_channel_exten(), ast_channel_name(), ast_channel_pbx(), ast_channel_priority(), ast_channel_zone(), ast_check_hangup(), AST_CONTROL_HOLD, AST_CONTROL_UNHOLD, AST_DECLARE_APP_ARGS, ast_exists_extension(), ast_get_indication_tone(), ast_indicate(), ast_indicate_data(), ast_log, ast_playtones_start(), ast_playtones_stop(), AST_STANDARD_APP_ARGS, ast_strdupa, ast_strlen_zero, ast_test_flag, ast_tone_zone_sound_unref(), ast_tonepair_start(), ast_verb, ast_waitfordigit(), ast_tone_zone_sound::data, LOG_WARNING, NULL, options, parse(), raise_exception(), ast_pbx::rtimeoutms, S_COR, S_OR, set_ext_pri(), TIMELEN_SECONDS, timeout, WAITEXTEN_DIALTONE, WAITEXTEN_MOH, and waitexten_opts.
 {
    int ms, res;
    struct ast_flags flags = {0};
    char *opts[1] = { NULL };
    char *parse;
    AST_DECLARE_APP_ARGS(args,
       AST_APP_ARG(timeout);
       AST_APP_ARG(options);
    );
    if (!ast_strlen_zero(data)) {
       parse = ast_strdupa(data);
       AST_STANDARD_APP_ARGS(args, parse);
    } else
       memset(&args, 0, sizeof(args));
    if (args.options)
       ast_app_parse_options(waitexten_opts, &flags, opts, args.options);
    if (ast_test_flag(&flags, WAITEXTEN_MOH) && !opts[0] ) {
       ast_log(LOG_WARNING, "The 'm' option has been specified for WaitExten without a class.\n");
    } else if (ast_test_flag(&flags, WAITEXTEN_MOH)) {
       ast_indicate_data(chan, AST_CONTROL_HOLD, S_OR(opts[0], NULL),
          !ast_strlen_zero(opts[0]) ? strlen(opts[0]) + 1 : 0);
    } else if (ast_test_flag(&flags, WAITEXTEN_DIALTONE)) {
       struct ast_tone_zone_sound *ts = ast_get_indication_tone(ast_channel_zone(chan), "dial");
       if (ts) {
          ast_playtones_start(chan, 0, ts->data, 0);
          ts = ast_tone_zone_sound_unref(ts);
       } else {
          ast_tonepair_start(chan, 350, 440, 0, 0);
       }
    }
    /* Wait for "n" seconds */
    if (!ast_app_parse_timelen(args.timeout, &ms, TIMELEN_SECONDS) && ms > 0) {
       /* Yay! */
    } else if (ast_channel_pbx(chan)) {
       ms = ast_channel_pbx(chan)->rtimeoutms;
    } else {
       ms = 10000;
    }
    res = ast_waitfordigit(chan, ms);
    if (!res) {
       if (ast_check_hangup(chan)) {
          /* Call is hungup for some reason. */
          res = -1;
       } else if (ast_exists_extension(chan, ast_channel_context(chan), ast_channel_exten(chan), ast_channel_priority(chan) + 1,
          S_COR(ast_channel_caller(chan)->id.number.valid, ast_channel_caller(chan)->id.number.str, NULL))) {
          ast_verb(3, "Timeout on %s, continuing...\n", ast_channel_name(chan));
       } else if (ast_exists_extension(chan, ast_channel_context(chan), "t", 1,
          S_COR(ast_channel_caller(chan)->id.number.valid, ast_channel_caller(chan)->id.number.str, NULL))) {
          ast_verb(3, "Timeout on %s, going to 't'\n", ast_channel_name(chan));
          set_ext_pri(chan, "t", 0); /* 0 will become 1, next time through the loop */
       } else if (ast_exists_extension(chan, ast_channel_context(chan), "e", 1,
          S_COR(ast_channel_caller(chan)->id.number.valid, ast_channel_caller(chan)->id.number.str, NULL))) {
          raise_exception(chan, "RESPONSETIMEOUT", 0); /* 0 will become 1, next time through the loop */
       } else {
          ast_log(LOG_WARNING, "Timeout but no rule 't' or 'e' in context '%s'\n",
             ast_channel_context(chan));
          res = -1;
       }
    }
    if (ast_test_flag(&flags, WAITEXTEN_MOH))
       ast_indicate(chan, AST_CONTROL_UNHOLD);
    else if (ast_test_flag(&flags, WAITEXTEN_DIALTONE))
       ast_playtones_stop(chan);
    return res;
 }