Asterisk - The Open Source Telephony Project: parser.h File Reference
parser.h File Reference
Implementation of the IAX2 protocol.
#include "asterisk/frame.h"
#include "asterisk/linkedlists.h"
#include "asterisk/crypto.h"
#include "asterisk/netsock2.h"
#include "iax2.h"
Data Structures
struct iax_frame
struct iax_ie_data
struct iax_ies
Macros
#define DIRECTION_INGRESS 1
#define DIRECTION_OUTGRESS 2
Functions
void iax_frame_free (struct iax_frame *fr)
struct iax_frame * iax_frame_new (int direction, int datalen, unsigned int cacheable)
void iax_frame_subclass2str (enum iax_frame_subclass subclass, char *str, size_t len)
void iax_frame_wrap (struct iax_frame *fr, struct ast_frame *f)
int iax_get_frames (void)
int iax_get_iframes (void)
int iax_get_oframes (void)
const char * iax_ie2str (int ie)
int iax_ie_append (struct iax_ie_data *ied, unsigned char ie)
int iax_ie_append_addr (struct iax_ie_data *ied, unsigned char ie, const struct ast_sockaddr *addr)
int iax_ie_append_byte (struct iax_ie_data *ied, unsigned char ie, unsigned char dat)
int iax_ie_append_int (struct iax_ie_data *ied, unsigned char ie, unsigned int value)
int iax_ie_append_raw (struct iax_ie_data *ied, unsigned char ie, const void *data, int datalen)
int iax_ie_append_short (struct iax_ie_data *ied, unsigned char ie, unsigned short value)
int iax_ie_append_str (struct iax_ie_data *ied, unsigned char ie, const char *str)
int iax_ie_append_versioned_uint64 (struct iax_ie_data *ied, unsigned char ie, unsigned char version, uint64_t value)
int iax_parse_ies (struct iax_ies *ies, unsigned char *data, int datalen)
void iax_set_error (void(*output)(const char *data))
void iax_set_output (void(*output)(const char *data))
void iax_showframe (struct iax_frame *f, struct ast_iax2_full_hdr *fhi, int rx, struct ast_sockaddr *addr, int datalen)
Detailed Description
Implementation of the IAX2 protocol.
Definition in file parser.h.
Macro Definition Documentation
DIRECTION_INGRESS
#define DIRECTION_INGRESS 1
Definition at line 87 of file parser.h.
Referenced by iax_frame_free(), iax_frame_new(), and iaxfrdup2().
DIRECTION_OUTGRESS
#define DIRECTION_OUTGRESS 2
Definition at line 88 of file parser.h.
Referenced by iax2_send(), iax_frame_free(), and send_trunk().
Function Documentation
iax_frame_free()
void iax_frame_free (struct iax_frame * fr)
Definition at line 1285 of file parser.c.
References iax_frame::afdatalen, ast_atomic_fetchadd_int(), ast_free, AST_LIST_FIRST, AST_LIST_INSERT_HEAD, AST_LIST_INSERT_TAIL, ast_opt_cache_media_frames, ast_threadstorage_get(), iax_frame::cacheable, iax_frame::direction, DIRECTION_INGRESS, DIRECTION_OUTGRESS, errorf, frame_cache, FRAME_CACHE_MAX_SIZE, frames, iframes, iax_frames::list, NULL, oframes, and iax_frames::size.
Referenced by iax2_frame_free(), and transmit_frame().
 {
 #if !defined(NO_FRAME_CACHE)
    struct iax_frames *iax_frames = NULL;
 #endif
    /* Note: does not remove from scheduler! */
    if (fr->direction == DIRECTION_INGRESS)
       ast_atomic_fetchadd_int(&iframes, -1);
    else if (fr->direction == DIRECTION_OUTGRESS)
       ast_atomic_fetchadd_int(&oframes, -1);
    else {
       errorf("Attempt to double free frame detected\n");
       return;
    }
    ast_atomic_fetchadd_int(&frames, -1);
 #if !defined(NO_FRAME_CACHE)
    if (!fr->cacheable
       || !ast_opt_cache_media_frames
       || !(iax_frames = ast_threadstorage_get(&frame_cache, sizeof(*iax_frames)))) {
       ast_free(fr);
       return;
    }
    if (iax_frames->size < FRAME_CACHE_MAX_SIZE) {
       fr->direction = 0;
       /* Pseudo-sort: keep smaller frames at the top of the list. This should
        * increase the chance that we pick the smallest applicable frame for use. */
       if (AST_LIST_FIRST(&iax_frames->list) && AST_LIST_FIRST(&iax_frames->list)->afdatalen < fr->afdatalen) {
          AST_LIST_INSERT_TAIL(&iax_frames->list, fr, list);
       } else {
          AST_LIST_INSERT_HEAD(&iax_frames->list, fr, list);
       }
       iax_frames->size++;
       return;
    }
 #endif
    ast_free(fr);
 }
iax_frame_new()
struct iax_frame* iax_frame_new (int direction, int datalen, unsigned int cacheable)
Definition at line 1218 of file parser.c.
References iax_frame::afdatalen, ast_atomic_fetchadd_int(), ast_calloc, ast_free, AST_LIST_FIRST, AST_LIST_REMOVE, AST_LIST_REMOVE_CURRENT, AST_LIST_TRAVERSE_SAFE_BEGIN, AST_LIST_TRAVERSE_SAFE_END, ast_threadstorage_get(), iax_frame::cacheable, iax_frame::datalen, iax_frame::direction, DIRECTION_INGRESS, frame_cache, FRAME_CACHE_MAX_SIZE, frames, iframes, iax_frames::list, NULL, oframes, iax_frame::retrans, and iax_frames::size.
Referenced by iax2_send(), and iaxfrdup2().
 {
    struct iax_frame *fr;
 #if !defined(NO_FRAME_CACHE)
    if (cacheable) {
       struct iax_frames *iax_frames;
       struct iax_frame *smallest;
       /* Attempt to get a frame from this thread's cache */
       if ((iax_frames = ast_threadstorage_get(&frame_cache, sizeof(*iax_frames)))) {
          smallest = AST_LIST_FIRST(&iax_frames->list);
          AST_LIST_TRAVERSE_SAFE_BEGIN(&iax_frames->list, fr, list) {
             if (fr->afdatalen >= datalen) {
                size_t afdatalen = fr->afdatalen;
                AST_LIST_REMOVE_CURRENT(list);
                iax_frames->size--;
                memset(fr, 0, sizeof(*fr));
                fr->afdatalen = afdatalen;
                break;
             } else if (smallest->afdatalen > fr->afdatalen) {
                smallest = fr;
             }
          }
          AST_LIST_TRAVERSE_SAFE_END;
          if (!fr) {
             if (iax_frames->size >= FRAME_CACHE_MAX_SIZE && smallest) {
                /* Make useless cache into something more useful */
                AST_LIST_REMOVE(&iax_frames->list, smallest, list);
                iax_frames->size--;
                ast_free(smallest);
             }
             if (!(fr = ast_calloc(1, sizeof(*fr) + datalen))) {
                return NULL;
             }
             fr->afdatalen = datalen;
          }
       } else {
          if (!(fr = ast_calloc(1, sizeof(*fr) + datalen))) {
             return NULL;
          }
          fr->afdatalen = datalen;
       }
       fr->cacheable = 1;
    } else
 #endif
    {
       if (!(fr = ast_calloc(1, sizeof(*fr) + datalen))) {
          return NULL;
       }
       fr->afdatalen = datalen;
    }
    fr->direction = direction;
    fr->retrans = -1;
    if (fr->direction == DIRECTION_INGRESS)
       ast_atomic_fetchadd_int(&iframes, 1);
    else
       ast_atomic_fetchadd_int(&oframes, 1);
    ast_atomic_fetchadd_int(&frames, 1);
    return fr;
 }
iax_frame_subclass2str()
void iax_frame_subclass2str (enum iax_frame_subclass subclass, char * str, size_t len)
Definition at line 462 of file parser.c.
References ast_copy_string(), IAX_COMMAND_ACCEPT, IAX_COMMAND_ACK, IAX_COMMAND_AUTHREP, IAX_COMMAND_AUTHREQ, IAX_COMMAND_CALLTOKEN, IAX_COMMAND_DIAL, IAX_COMMAND_DPREP, IAX_COMMAND_DPREQ, IAX_COMMAND_FWDATA, IAX_COMMAND_FWDOWNL, IAX_COMMAND_HANGUP, IAX_COMMAND_INVAL, IAX_COMMAND_LAGRP, IAX_COMMAND_LAGRQ, IAX_COMMAND_MWI, IAX_COMMAND_NEW, IAX_COMMAND_PAGE, IAX_COMMAND_PING, IAX_COMMAND_POKE, IAX_COMMAND_PONG, IAX_COMMAND_PROVISION, IAX_COMMAND_QUELCH, IAX_COMMAND_REGACK, IAX_COMMAND_REGAUTH, IAX_COMMAND_REGREJ, IAX_COMMAND_REGREL, IAX_COMMAND_REGREQ, IAX_COMMAND_REJECT, IAX_COMMAND_RTKEY, IAX_COMMAND_TRANSFER, IAX_COMMAND_TXACC, IAX_COMMAND_TXCNT, IAX_COMMAND_TXMEDIA, IAX_COMMAND_TXREADY, IAX_COMMAND_TXREJ, IAX_COMMAND_TXREL, IAX_COMMAND_TXREQ, IAX_COMMAND_UNQUELCH, IAX_COMMAND_UNSUPPORT, and IAX_COMMAND_VNAK.
Referenced by ast_cli_netstats(), handle_cli_iax2_show_channels(), iax_showframe(), and socket_process_helper().
 {
    const char *cmd = "Unknown";
    /* if an error occurs here during compile, that means a new iax frame subclass
     * has been added to the iax_frame_subclass enum.  Add the new subclass to the
     * switch case and make sure to update it with a new string representation. */
    switch (subclass) {
    case IAX_COMMAND_NEW:
       cmd = "NEW    ";
       break;
    case IAX_COMMAND_PING:
       cmd = "PING   ";
       break;
    case IAX_COMMAND_PONG:
       cmd = "PONG   ";
       break;
    case IAX_COMMAND_ACK:
       cmd = "ACK    ";
       break;
    case IAX_COMMAND_HANGUP:
       cmd = "HANGUP ";
       break;
    case IAX_COMMAND_REJECT:
       cmd = "REJECT ";
       break;
    case IAX_COMMAND_ACCEPT:
       cmd = "ACCEPT ";
       break;
    case IAX_COMMAND_AUTHREQ:
       cmd = "AUTHREQ";
       break;
    case IAX_COMMAND_AUTHREP:
       cmd = "AUTHREP";
       break;
    case IAX_COMMAND_INVAL:
       cmd = "INVAL  ";
       break;
    case IAX_COMMAND_LAGRQ:
       cmd = "LAGRQ  ";
       break;
    case IAX_COMMAND_LAGRP:
       cmd = "LAGRP  ";
       break;
    case IAX_COMMAND_REGREQ:
       cmd = "REGREQ ";
       break;
    case IAX_COMMAND_REGAUTH:
       cmd = "REGAUTH";
       break;
    case IAX_COMMAND_REGACK:
       cmd = "REGACK ";
       break;
    case IAX_COMMAND_REGREJ:
       cmd = "REGREJ ";
       break;
    case IAX_COMMAND_REGREL:
       cmd = "REGREL ";
       break;
    case IAX_COMMAND_VNAK:
       cmd = "VNAK   ";
       break;
    case IAX_COMMAND_DPREQ:
       cmd = "DPREQ  ";
       break;
    case IAX_COMMAND_DPREP:
       cmd = "DPREP  ";
       break;
    case IAX_COMMAND_DIAL:
       cmd = "DIAL   ";
       break;
    case IAX_COMMAND_TXREQ:
       cmd = "TXREQ  ";
       break;
    case IAX_COMMAND_TXCNT:
       cmd = "TXCNT  ";
       break;
    case IAX_COMMAND_TXACC:
       cmd = "TXACC  ";
       break;
    case IAX_COMMAND_TXREADY:
       cmd = "TXREADY";
       break;
    case IAX_COMMAND_TXREL:
       cmd = "TXREL  ";
       break;
    case IAX_COMMAND_TXREJ:
       cmd = "TXREJ  ";
       break;
    case IAX_COMMAND_QUELCH:
       cmd = "QUELCH ";
       break;
    case IAX_COMMAND_UNQUELCH:
       cmd = "UNQULCH";
       break;
    case IAX_COMMAND_POKE:
       cmd = "POKE   ";
       break;
    case IAX_COMMAND_PAGE:
       cmd = "PAGE   ";
       break;
    case IAX_COMMAND_MWI:
       cmd = "MWI    ";
       break;
    case IAX_COMMAND_UNSUPPORT:
       cmd = "UNSPRTD";
       break;
    case IAX_COMMAND_TRANSFER:
       cmd = "TRANSFR";
       break;
    case IAX_COMMAND_PROVISION:
       cmd = "PROVISN";
       break;
    case IAX_COMMAND_FWDOWNL:
       cmd = "FWDWNLD";
       break;
    case IAX_COMMAND_FWDATA:
       cmd = "FWDATA ";
       break;
    case IAX_COMMAND_TXMEDIA:
       cmd = "TXMEDIA";
       break;
    case IAX_COMMAND_RTKEY:
       cmd = "RTKEY  ";
       break;
    case IAX_COMMAND_CALLTOKEN:
       cmd = "CTOKEN ";
       break;
    }
    ast_copy_string(str, cmd, len);
 }
iax_frame_wrap()
void iax_frame_wrap (struct iax_frame * fr, struct ast_frame * f)
Definition at line 1185 of file parser.c.
References iax_frame::af, iax_frame::afdata, iax_frame::afdatalen, ast_format_cmp(), AST_FORMAT_CMP_EQUAL, ast_format_slin, AST_FRAME_VOICE, AST_FRIENDLY_OFFSET, ast_log, ast_swapcopy_samples(), ast_frame::data, ast_frame::datalen, ast_frame::delivery, ast_frame_subclass::format, ast_frame::frametype, ast_frame_subclass::integer, ast_frame::len, LOG_ERROR, ast_frame::mallocd, ast_frame::offset, ast_frame::ptr, ast_frame::samples, ast_frame::src, and ast_frame::subclass.
Referenced by iax2_send(), iaxfrdup2(), socket_process_helper(), and socket_process_meta().
 {
    fr->af.frametype = f->frametype;
    fr->af.subclass.format = f->subclass.format;
    fr->af.subclass.integer = f->subclass.integer;
    fr->af.mallocd = 0;           /* Our frame is static relative to the container */
    fr->af.datalen = f->datalen;
    fr->af.samples = f->samples;
    fr->af.offset = AST_FRIENDLY_OFFSET;
    fr->af.src = f->src;
    fr->af.delivery.tv_sec = 0;
    fr->af.delivery.tv_usec = 0;
    fr->af.data.ptr = fr->afdata;
    fr->af.len = f->len;
    if (fr->af.datalen) {
       size_t copy_len = fr->af.datalen;
       if (copy_len > fr->afdatalen) {
          ast_log(LOG_ERROR, "Losing frame data because destination buffer size '%d' bytes not big enough for '%d' bytes in the frame\n",
             (int) fr->afdatalen, (int) fr->af.datalen);
          copy_len = fr->afdatalen;
       }
 #if __BYTE_ORDER == __LITTLE_ENDIAN
       /* We need to byte-swap slinear samples from network byte order */
       if ((fr->af.frametype == AST_FRAME_VOICE) &&
          (ast_format_cmp(fr->af.subclass.format, ast_format_slin) == AST_FORMAT_CMP_EQUAL)) {
          /* 2 bytes / sample for SLINEAR */
          ast_swapcopy_samples(fr->af.data.ptr, f->data.ptr, copy_len / 2);
       } else
 #endif
          memcpy(fr->af.data.ptr, f->data.ptr, copy_len);
    }
 }
iax_get_frames()
int iax_get_frames (void)
Definition at line 1339 of file parser.c.
References frames.
Referenced by handle_cli_iax2_show_stats().
 { return frames; }
iax_get_iframes()
int iax_get_iframes (void)
Definition at line 1340 of file parser.c.
References iframes.
Referenced by handle_cli_iax2_show_stats().
 { return iframes; }
iax_get_oframes()
int iax_get_oframes (void)
Definition at line 1341 of file parser.c.
References oframes.
Referenced by handle_cli_iax2_show_stats().
 { return oframes; }
iax_ie2str()
const char* iax_ie2str (int ie)
Definition at line 352 of file parser.c.
References ARRAY_LEN, and iax2_ie::name.
Referenced by iax_ie_append_raw(), and iax_parse_ies().
 {
    int x;
    for (x = 0; x < ARRAY_LEN(infoelts); x++) {
       if (infoelts[x].ie == ie)
          return infoelts[x].name;
    }
    return "Unknown IE";
 }
iax_ie_append()
int iax_ie_append (struct iax_ie_data * ied, unsigned char ie)
Definition at line 779 of file parser.c.
References iax_ie_append_raw(), and NULL.
Referenced by iax2_call(), and iax_firmware_append().
 {
    return iax_ie_append_raw(ied, ie, NULL, 0);
 }
iax_ie_append_addr()
int iax_ie_append_addr (struct iax_ie_data * ied, unsigned char ie, const struct ast_sockaddr * addr)
Definition at line 740 of file parser.c.
References iax_ie_append_raw(), and ast_sockaddr::len.
Referenced by iax2_key_rotate(), and update_registry().
 {
    return iax_ie_append_raw(ied, ie, addr, addr->len);
 }
iax_ie_append_byte()
int iax_ie_append_byte (struct iax_ie_data * ied, unsigned char ie, unsigned char dat)
Definition at line 774 of file parser.c.
References iax_ie_append_raw().
Referenced by __auth_reject(), __auto_hangup(), authenticate_request(), iax2_call(), iax2_hangup(), iax_provision_build(), and socket_process_helper().
 {
    return iax_ie_append_raw(ied, ie, &dat, 1);
 }
iax_ie_append_int()
int iax_ie_append_int (struct iax_ie_data * ied, unsigned char ie, unsigned int value)
Definition at line 755 of file parser.c.
References iax_ie_append_raw().
Referenced by cache_get_callno_locked(), construct_rr(), iax2_call(), iax2_key_rotate(), iax_firmware_append(), iax_provision_build(), socket_process_helper(), try_transfer(), and update_registry().
 {
    unsigned int newval;
    newval = htonl(value);
    return iax_ie_append_raw(ied, ie, &newval, (int)sizeof(newval));
 }
iax_ie_append_raw()
int iax_ie_append_raw (struct iax_ie_data * ied, unsigned char ie, const void * data, int datalen)
Definition at line 725 of file parser.c.
References iax_ie_data::buf, errorf, iax_ie2str(), iax_ie_data::pos, and tmp().
Referenced by iax2_call(), iax2_key_rotate(), iax2_provision(), iax_firmware_append(), iax_ie_append(), iax_ie_append_addr(), iax_ie_append_byte(), iax_ie_append_int(), iax_ie_append_short(), iax_ie_append_str(), and iax_ie_append_versioned_uint64().
 {
    char tmp[256];
    if (datalen > ((int)sizeof(ied->buf) - ied->pos)) {
       snprintf(tmp, (int)sizeof(tmp), "Out of space for ie '%s' (%d), need %d have %d\n", iax_ie2str(ie), ie, datalen, (int)sizeof(ied->buf) - ied->pos);
       errorf(tmp);
       return -1;
    }
    ied->buf[ied->pos++] = ie;
    ied->buf[ied->pos++] = datalen;
    memcpy(ied->buf + ied->pos, data, datalen);
    ied->pos += datalen;
    return 0;
 }
iax_ie_append_short()
int iax_ie_append_short (struct iax_ie_data * ied, unsigned char ie, unsigned short value)
Definition at line 762 of file parser.c.
References iax_ie_append_raw().
Referenced by authenticate_request(), cache_get_callno_locked(), construct_rr(), dp_lookup(), iax2_call(), iax2_do_register(), iax2_key_rotate(), iax_provision_build(), registry_authrequest(), registry_rerequest(), socket_process_helper(), and update_registry().
 {
    unsigned short newval;
    newval = htons(value);
    return iax_ie_append_raw(ied, ie, &newval, (int)sizeof(newval));
 }
iax_ie_append_str()
int iax_ie_append_str (struct iax_ie_data * ied, unsigned char ie, const char * str)
Definition at line 769 of file parser.c.
References iax_ie_append_raw().
Referenced by __auth_reject(), __auto_hangup(), authenticate(), authenticate_request(), cache_get_callno_locked(), dp_lookup(), handle_call_token(), iax2_call(), iax2_do_register(), iax2_dprequest(), iax2_transfer(), iax_provision_build(), registry_authrequest(), registry_rerequest(), resend_with_token(), socket_process_helper(), and update_registry().
 {
    return iax_ie_append_raw(ied, ie, str, strlen(str));
 }
iax_ie_append_versioned_uint64()
int iax_ie_append_versioned_uint64 (struct iax_ie_data * ied, unsigned char ie, unsigned char version, uint64_t value)
Definition at line 745 of file parser.c.
References htonll(), iax_ie_append_raw(), put_unaligned_uint64(), value, and version.
Referenced by iax2_call(), and socket_process_helper().
 {
    struct _local {
       unsigned char version;
       uint64_t value;
    } __attribute__((packed)) newval = { version, };
    put_unaligned_uint64(&newval.value, htonll(value));
    return iax_ie_append_raw(ied, ie, &newval, (int) sizeof(newval));
 }
iax_parse_ies()
int iax_parse_ies (struct iax_ies * ies, unsigned char * data, int datalen)
Definition at line 794 of file parser.c.
References iax_ies::adsicpe, iax_ies::apparent_addr, ast_copy_string(), ast_free, ast_str_buffer(), ast_str_create, ast_str_set(), ast_variable_new, iax_ies::authmethods, iax_ies::autoanswer, iax_ies::called_context, iax_ies::called_number, iax_ies::calling_ani, iax_ies::calling_name, iax_ies::calling_number, iax_ies::calling_pres, iax_ies::calling_tns, iax_ies::calling_ton, iax_ies::callno, iax_ies::calltoken, iax_ies::calltokendata, iax_ies::capability, iax_ies::cause, iax_ies::causecode, iax_ies::challenge, iax_ies::codec_prefs, iax_ies::datetime, iax_ies::devicetype, iax_ies::dnid, iax_ies::dpstatus, iax_ies::enckey, iax_ies::enckeylen, iax_ies::encmethods, errorf, ast_variable::file, iax_ies::firmwarever, iax_ies::format, iax_ies::fwdata, iax_ies::fwdatalen, iax_ies::fwdesc, get_unaligned_uint16(), get_unaligned_uint32(), get_unaligned_uint64(), iax_ie2str(), IAX_IE_ADSICPE, IAX_IE_APPARENT_ADDR, IAX_IE_AUTHMETHODS, IAX_IE_AUTOANSWER, IAX_IE_CALLED_CONTEXT, IAX_IE_CALLED_NUMBER, IAX_IE_CALLING_ANI, IAX_IE_CALLING_NAME, IAX_IE_CALLING_NUMBER, IAX_IE_CALLINGPRES, IAX_IE_CALLINGTNS, IAX_IE_CALLINGTON, IAX_IE_CALLNO, IAX_IE_CALLTOKEN, IAX_IE_CAPABILITY, IAX_IE_CAPABILITY2, IAX_IE_CAUSE, IAX_IE_CAUSECODE, IAX_IE_CHALLENGE, IAX_IE_CODEC_PREFS, IAX_IE_DATETIME, IAX_IE_DEVICETYPE, IAX_IE_DNID, IAX_IE_DPSTATUS, IAX_IE_ENCKEY, IAX_IE_ENCRYPTION, IAX_IE_FIRMWAREVER, IAX_IE_FORMAT, IAX_IE_FORMAT2, IAX_IE_FWBLOCKDATA, IAX_IE_FWBLOCKDESC, IAX_IE_IAX_UNKNOWN, IAX_IE_LANGUAGE, IAX_IE_MD5_RESULT, IAX_IE_MSGCOUNT, IAX_IE_MUSICONHOLD, IAX_IE_OSPTOKEN, IAX_IE_PASSWORD, IAX_IE_PROVVER, IAX_IE_RDNIS, IAX_IE_REFRESH, IAX_IE_RR_DELAY, IAX_IE_RR_DROPPED, IAX_IE_RR_JITTER, IAX_IE_RR_LOSS, IAX_IE_RR_OOO, IAX_IE_RR_PKTS, IAX_IE_RSA_RESULT, IAX_IE_SAMPLINGRATE, IAX_IE_SERVICEIDENT, IAX_IE_TRANSFERID, IAX_IE_USERNAME, IAX_IE_VARIABLE, IAX_IE_VERSION, IAX_MAX_OSPBLOCK_NUM, IAX_RATE_8KHZ, iax_ies::iax_unknown, iax_ies::language, ast_sockaddr::len, len(), iax_ies::md5_result, iax_ies::msgcount, iax_ies::musiconhold, ast_variable::name, ast_variable::next, ntohll(), NULL, iax_ies::ospblocklength, iax_ies::osptokenblock, outputf, iax_ies::password, iax_ies::provver, iax_ies::provverpres, iax_ies::rdnis, iax_ies::refresh, iax_ies::rr_delay, iax_ies::rr_dropped, iax_ies::rr_jitter, iax_ies::rr_loss, iax_ies::rr_ooo, iax_ies::rr_pkts, iax_ies::rsa_result, iax_ies::samprate, iax_ies::serviceident, str, tmp(), iax_ies::transferid, iax_ies::username, ast_variable::value, var, iax_ies::vars, iax_ies::version, and version.
Referenced by socket_process_helper().
 {
    /* Parse data into information elements */
    int len;
    int ie;
    char tmp[256], *tmp2;
    struct ast_variable *var, *var2, *prev;
    unsigned int count;
    memset(ies, 0, (int)sizeof(struct iax_ies));
    ies->msgcount = -1;
    ies->firmwarever = -1;
    ies->calling_ton = -1;
    ies->calling_tns = -1;
    ies->calling_pres = -1;
    ies->samprate = IAX_RATE_8KHZ;
    while(datalen >= 2) {
       ie = data[0];
       len = data[1];
       if (len > datalen - 2) {
          errorf("Information element length exceeds message size\n");
          return -1;
       }
       switch(ie) {
       case IAX_IE_CALLED_NUMBER:
          ies->called_number = (char *)data + 2;
          break;
       case IAX_IE_CALLING_NUMBER:
          ies->calling_number = (char *)data + 2;
          break;
       case IAX_IE_CALLING_ANI:
          ies->calling_ani = (char *)data + 2;
          break;
       case IAX_IE_CALLING_NAME:
          ies->calling_name = (char *)data + 2;
          break;
       case IAX_IE_CALLED_CONTEXT:
          ies->called_context = (char *)data + 2;
          break;
       case IAX_IE_USERNAME:
          ies->username = (char *)data + 2;
          break;
       case IAX_IE_PASSWORD:
          ies->password = (char *)data + 2;
          break;
       case IAX_IE_CODEC_PREFS:
          ies->codec_prefs = (char *)data + 2;
          break;
       case IAX_IE_CAPABILITY:
          if (len != (int)sizeof(unsigned int)) {
             snprintf(tmp, (int)sizeof(tmp), "Expecting capability to be %d bytes long but was %d\n", (int)sizeof(unsigned int), len);
             errorf(tmp);
          } else if (ies->capability == 0) { /* Don't overwrite capability2, if specified */
             ies->capability = ntohl(get_unaligned_uint32(data + 2));
          }
          break;
       case IAX_IE_CAPABILITY2:
          {
             int version = data[2];
             if (version == 0) {
                if (len != (int)sizeof(char) + sizeof(iax2_format)) {
                   snprintf(tmp, (int)sizeof(tmp), "Expecting capability to be %d bytes long but was %d\n", (int) (sizeof(iax2_format) + sizeof(char)), len);
                   errorf(tmp);
                } else {
                   ies->capability = (iax2_format) ntohll(get_unaligned_uint64(data + 3));
                }
             } /* else unknown version */
          }
          break;
       case IAX_IE_FORMAT:
          if (len != (int)sizeof(unsigned int)) {
             snprintf(tmp, (int)sizeof(tmp), "Expecting format to be %d bytes long but was %d\n", (int)sizeof(unsigned int), len);
             errorf(tmp);
          } else if (ies->format == 0) { /* Don't overwrite format2, if specified */
             ies->format = ntohl(get_unaligned_uint32(data + 2));
          }
          break;
       case IAX_IE_FORMAT2:
          {
             int version = data[2];
             if (version == 0) {
                if (len != (int)sizeof(char) + sizeof(iax2_format)) {
                   snprintf(tmp, (int)sizeof(tmp), "Expecting format to be %d bytes long but was %d\n", (int) (sizeof(iax2_format) + sizeof(char)), len);
                   errorf(tmp);
                } else {
                   ies->format = (iax2_format) ntohll(get_unaligned_uint64(data + 3));
                }
             } /* else unknown version */
          }
          break;
       case IAX_IE_LANGUAGE:
          ies->language = (char *)data + 2;
          break;
       case IAX_IE_VERSION:
          if (len != (int)sizeof(unsigned short)) {
             snprintf(tmp, (int)sizeof(tmp),  "Expecting version to be %d bytes long but was %d\n", (int)sizeof(unsigned short), len);
             errorf(tmp);
          } else
             ies->version = ntohs(get_unaligned_uint16(data + 2));
          break;
       case IAX_IE_ADSICPE:
          if (len != (int)sizeof(unsigned short)) {
             snprintf(tmp, (int)sizeof(tmp), "Expecting adsicpe to be %d bytes long but was %d\n", (int)sizeof(unsigned short), len);
             errorf(tmp);
          } else
             ies->adsicpe = ntohs(get_unaligned_uint16(data + 2));
          break;
       case IAX_IE_SAMPLINGRATE:
          if (len != (int)sizeof(unsigned short)) {
             snprintf(tmp, (int)sizeof(tmp), "Expecting samplingrate to be %d bytes long but was %d\n", (int)sizeof(unsigned short), len);
             errorf(tmp);
          } else
             ies->samprate = ntohs(get_unaligned_uint16(data + 2));
          break;
       case IAX_IE_DNID:
          ies->dnid = (char *)data + 2;
          break;
       case IAX_IE_RDNIS:
          ies->rdnis = (char *)data + 2;
          break;
       case IAX_IE_AUTHMETHODS:
          if (len != (int)sizeof(unsigned short))  {
             snprintf(tmp, (int)sizeof(tmp), "Expecting authmethods to be %d bytes long but was %d\n", (int)sizeof(unsigned short), len);
             errorf(tmp);
          } else
             ies->authmethods = ntohs(get_unaligned_uint16(data + 2));
          break;
       case IAX_IE_ENCRYPTION:
          if (len != (int)sizeof(unsigned short))  {
             snprintf(tmp, (int)sizeof(tmp), "Expecting encryption to be %d bytes long but was %d\n", (int)sizeof(unsigned short), len);
             errorf(tmp);
          } else
             ies->encmethods = ntohs(get_unaligned_uint16(data + 2));
          break;
       case IAX_IE_CHALLENGE:
          ies->challenge = (char *)data + 2;
          break;
       case IAX_IE_MD5_RESULT:
          ies->md5_result = (char *)data + 2;
          break;
       case IAX_IE_RSA_RESULT:
          ies->rsa_result = (char *)data + 2;
          break;
       case IAX_IE_APPARENT_ADDR:
          memcpy(&ies->apparent_addr , (struct ast_sockaddr *) (data + 2), len);
          ies->apparent_addr.len = len;
          break;
       case IAX_IE_REFRESH:
          if (len != (int)sizeof(unsigned short)) {
             snprintf(tmp, (int)sizeof(tmp),  "Expecting refresh to be %d bytes long but was %d\n", (int)sizeof(unsigned short), len);
             errorf(tmp);
          } else
             ies->refresh = ntohs(get_unaligned_uint16(data + 2));
          break;
       case IAX_IE_DPSTATUS:
          if (len != (int)sizeof(unsigned short)) {
             snprintf(tmp, (int)sizeof(tmp),  "Expecting dpstatus to be %d bytes long but was %d\n", (int)sizeof(unsigned short), len);
             errorf(tmp);
          } else
             ies->dpstatus = ntohs(get_unaligned_uint16(data + 2));
          break;
       case IAX_IE_CALLNO:
          if (len != (int)sizeof(unsigned short)) {
             snprintf(tmp, (int)sizeof(tmp),  "Expecting callno to be %d bytes long but was %d\n", (int)sizeof(unsigned short), len);
             errorf(tmp);
          } else
             ies->callno = ntohs(get_unaligned_uint16(data + 2));
          break;
       case IAX_IE_CAUSE:
          ies->cause = (char *)data + 2;
          break;
       case IAX_IE_CAUSECODE:
          if (len != 1) {
             snprintf(tmp, (int)sizeof(tmp), "Expecting causecode to be single byte but was %d\n", len);
             errorf(tmp);
          } else {
             ies->causecode = data[2];
          }
          break;
       case IAX_IE_IAX_UNKNOWN:
          if (len == 1)
             ies->iax_unknown = data[2];
          else {
             snprintf(tmp, (int)sizeof(tmp), "Expected single byte Unknown command, but was %d long\n", len);
             errorf(tmp);
          }
          break;
       case IAX_IE_MSGCOUNT:
          if (len != (int)sizeof(unsigned short)) {
             snprintf(tmp, (int)sizeof(tmp), "Expecting msgcount to be %d bytes long but was %d\n", (int)sizeof(unsigned short), len);
             errorf(tmp);
          } else
             ies->msgcount = ntohs(get_unaligned_uint16(data + 2));
          break;
       case IAX_IE_AUTOANSWER:
          ies->autoanswer = 1;
          break;
       case IAX_IE_MUSICONHOLD:
          ies->musiconhold = 1;
          break;
       case IAX_IE_TRANSFERID:
          if (len != (int)sizeof(unsigned int)) {
             snprintf(tmp, (int)sizeof(tmp), "Expecting transferid to be %d bytes long but was %d\n", (int)sizeof(unsigned int), len);
             errorf(tmp);
          } else
             ies->transferid = ntohl(get_unaligned_uint32(data + 2));
          break;
       case IAX_IE_DATETIME:
          if (len != (int)sizeof(unsigned int)) {
             snprintf(tmp, (int)sizeof(tmp), "Expecting date/time to be %d bytes long but was %d\n", (int)sizeof(unsigned int), len);
             errorf(tmp);
          } else
             ies->datetime = ntohl(get_unaligned_uint32(data + 2));
          break;
       case IAX_IE_FIRMWAREVER:
          if (len != (int)sizeof(unsigned short)) {
             snprintf(tmp, (int)sizeof(tmp), "Expecting firmwarever to be %d bytes long but was %d\n", (int)sizeof(unsigned short), len);
             errorf(tmp);
          } else
             ies->firmwarever = ntohs(get_unaligned_uint16(data + 2));
          break;
       case IAX_IE_DEVICETYPE:
          ies->devicetype = (char *)data + 2;
          break;
       case IAX_IE_SERVICEIDENT:
          ies->serviceident = (char *)data + 2;
          break;
       case IAX_IE_FWBLOCKDESC:
          if (len != (int)sizeof(unsigned int)) {
             snprintf(tmp, (int)sizeof(tmp), "Expected block desc to be %d bytes long but was %d\n", (int)sizeof(unsigned int), len);
             errorf(tmp);
          } else
             ies->fwdesc = ntohl(get_unaligned_uint32(data + 2));
          break;
       case IAX_IE_FWBLOCKDATA:
          ies->fwdata = data + 2;
          ies->fwdatalen = len;
          break;
       case IAX_IE_ENCKEY:
          ies->enckey = data + 2;
          ies->enckeylen = len;
          break;
       case IAX_IE_PROVVER:
          if (len != (int)sizeof(unsigned int)) {
             snprintf(tmp, (int)sizeof(tmp), "Expected provisioning version to be %d bytes long but was %d\n", (int)sizeof(unsigned int), len);
             errorf(tmp);
          } else {
             ies->provverpres = 1;
             ies->provver = ntohl(get_unaligned_uint32(data + 2));
          }
          break;
       case IAX_IE_CALLINGPRES:
          if (len == 1)
             ies->calling_pres = data[2];
          else {
             snprintf(tmp, (int)sizeof(tmp), "Expected single byte callingpres, but was %d long\n", len);
             errorf(tmp);
          }
          break;
       case IAX_IE_CALLINGTON:
          if (len == 1)
             ies->calling_ton = data[2];
          else {
             snprintf(tmp, (int)sizeof(tmp), "Expected single byte callington, but was %d long\n", len);
             errorf(tmp);
          }
          break;
       case IAX_IE_CALLINGTNS:
          if (len != (int)sizeof(unsigned short)) {
             snprintf(tmp, (int)sizeof(tmp), "Expecting callingtns to be %d bytes long but was %d\n", (int)sizeof(unsigned short), len);
             errorf(tmp);
          } else
             ies->calling_tns = ntohs(get_unaligned_uint16(data + 2));
          break;
                case IAX_IE_RR_JITTER:
                        if (len != (int)sizeof(unsigned int)) {
                                snprintf(tmp, (int)sizeof(tmp), "Expected jitter rr to be %d bytes long but was %d\n", (int)sizeof(unsigned int), len);
                                errorf(tmp);
                        } else {
                                ies->rr_jitter = ntohl(get_unaligned_uint32(data + 2));
                        }
                        break;
                case IAX_IE_RR_LOSS:
                        if (len != (int)sizeof(unsigned int)) {
                                snprintf(tmp, (int)sizeof(tmp), "Expected loss rr to be %d bytes long but was %d\n", (int)sizeof(unsigned int), len);
                                errorf(tmp);
                        } else {
                                ies->rr_loss = ntohl(get_unaligned_uint32(data + 2));
                        }
                        break;
                case IAX_IE_RR_PKTS:
                        if (len != (int)sizeof(unsigned int)) {
                                snprintf(tmp, (int)sizeof(tmp), "Expected packets rr to be %d bytes long but was %d\n", (int)sizeof(unsigned int), len);
                                errorf(tmp);
                        } else {
                                ies->rr_pkts = ntohl(get_unaligned_uint32(data + 2));
                        }
                        break;
                case IAX_IE_RR_DELAY:
                        if (len != (int)sizeof(unsigned short)) {
                                snprintf(tmp, (int)sizeof(tmp), "Expected loss rr to be %d bytes long but was %d\n", (int)sizeof(unsigned short), len);
                         errorf(tmp);
                        } else {
                                ies->rr_delay = ntohs(get_unaligned_uint16(data + 2));
                        }
                        break;
       case IAX_IE_RR_DROPPED:
          if (len != (int)sizeof(unsigned int)) {
             snprintf(tmp, (int)sizeof(tmp), "Expected packets rr to be %d bytes long but was %d\n", (int)sizeof(unsigned int), len);
             errorf(tmp);
          } else {
             ies->rr_dropped = ntohl(get_unaligned_uint32(data + 2));
          }
          break;
       case IAX_IE_RR_OOO:
          if (len != (int)sizeof(unsigned int)) {
             snprintf(tmp, (int)sizeof(tmp), "Expected packets rr to be %d bytes long but was %d\n", (int)sizeof(unsigned int), len);
             errorf(tmp);
          } else {
             ies->rr_ooo = ntohl(get_unaligned_uint32(data + 2));
          }
          break;
       case IAX_IE_VARIABLE:
          ast_copy_string(tmp, (char *)data + 2, len + 1);
          tmp2 = strchr(tmp, '=');
          if (tmp2)
             *tmp2++ = '\0';
          else
             tmp2 = "";
          {
             struct ast_str *str = ast_str_create(16);
             /* Existing variable or new variable? */
             for (var2 = ies->vars, prev = NULL; var2; prev = var2, var2 = var2->next) {
                if (strcmp(tmp, var2->name) == 0) {
                   ast_str_set(&str, 0, "%s%s", var2->value, tmp2);
                   var = ast_variable_new(tmp, ast_str_buffer(str), var2->file);
                   var->next = var2->next;
                   if (prev) {
                      prev->next = var;
                   } else {
                      ies->vars = var;
                   }
                   snprintf(tmp, sizeof(tmp), "Assigned (%p)%s to (%p)%s\n", var->name, var->name, var->value, var->value);
                   outputf(tmp);
                   ast_free(var2);
                   break;
                }
             }
             ast_free(str);
          }
          if (!var2) {
             var = ast_variable_new(tmp, tmp2, "");
             snprintf(tmp, sizeof(tmp), "Assigned (%p)%s to (%p)%s\n", var->name, var->name, var->value, var->value);
             outputf(tmp);
             var->next = ies->vars;
             ies->vars = var;
          }
          break;
       case IAX_IE_OSPTOKEN:
          if ((count = data[2]) < IAX_MAX_OSPBLOCK_NUM) {
             ies->osptokenblock[count] = (char *)data + 2 + 1;
             ies->ospblocklength[count] = len - 1;
          } else {
             snprintf(tmp, (int)sizeof(tmp), "Expected OSP token block index to be 0~%d but was %u\n", IAX_MAX_OSPBLOCK_NUM - 1, count);
             errorf(tmp);
          }
          break;
       case IAX_IE_CALLTOKEN:
          if (len) {
             ies->calltokendata = (unsigned char *) data + 2;
          }
          ies->calltoken = 1;
          break;
       default:
          snprintf(tmp, (int)sizeof(tmp), "Ignoring unknown information element '%s' (%d) of length %d\n", iax_ie2str(ie), ie, len);
          outputf(tmp);
       }
       /* Overwrite information element with 0, to null terminate previous portion */
       data[0] = 0;
       datalen -= (len + 2);
       data += (len + 2);
    }
    /* Null-terminate last field */
    *data = '\0';
    if (datalen) {
       errorf("Invalid information element contents, strange boundary\n");
       return -1;
    }
    return 0;
 }
iax_set_error()
void iax_set_error (void(*)(const char *data) output)
Referenced by load_module().
iax_set_output()
void iax_set_output (void(*)(const char *data) output)
Referenced by load_module().
iax_showframe()
void iax_showframe (struct iax_frame * f, struct ast_iax2_full_hdr * fhi, int rx, struct ast_sockaddr * addr, int datalen)
Definition at line 594 of file parser.c.
References ARRAY_LEN, AST_FRAME_CONTROL, AST_FRAME_DTMF_BEGIN, AST_FRAME_DTMF_END, AST_FRAME_IAX, ast_sockaddr_stringify(), ast_iax2_full_hdr::csub, iax_frame::data, ast_iax2_full_hdr::dcallno, dump_ies(), IAX_FLAG_FULL, IAX_FLAG_RETRANS, iax_frame_subclass2str(), ast_iax2_full_hdr::iedata, ast_iax2_full_hdr::iseqno, ast_iax2_full_hdr::oseqno, outputf, iax_frame::retries, ast_iax2_full_hdr::scallno, tmp(), ast_iax2_full_hdr::ts, and ast_iax2_full_hdr::type.
Referenced by iax_outputframe().
 {
    const char *framelist[] = {
       "(0?)",
       "DTMF_E ",
       "VOICE  ",
       "VIDEO  ",
       "CONTROL",
       "NULL   ",
       "IAX    ",
       "TEXT   ",
       "IMAGE  ",
       "HTML   ",
       "CNG    ",
       "MODEM  ",
       "DTMF_B ",
    };
    const char *cmds[] = {
       "(0?)",
       "HANGUP ",
       "RING   ",
       "RINGING",
       "ANSWER ",
       "BUSY   ",
       "TKOFFHK",
       "OFFHOOK",
       "CONGSTN",
       "FLASH  ",
       "WINK   ",
       "OPTION ",
       "RDKEY  ",
       "RDUNKEY",
       "PROGRES",
       "PROCDNG",
       "HOLD   ",
       "UNHOLD ",
       "VIDUPDT",
       "T38    ",
       "SRCUPDT",
       "TXFER  ",
       "CNLINE ",
       "REDIR  ",
       "T38PARM",
       "CC ERR!",/* This must never go across an IAX link. */
       "SRCCHG ",
       "READACT",
       "AOC    ",
       "ENDOFQ ",
       "INCOMPL",
       "MCID   ",
       "UPDRTPP",
       "PCAUSEC",
    };
    struct ast_iax2_full_hdr *fh;
    char retries[20];
    char class2[20];
    char subclass2[20];
    const char *class;
    const char *subclass;
    char *dir;
    char tmp[512];
    switch(rx) {
    case 0:
       dir = "Tx";
       break;
    case 2:
       dir = "TE";
       break;
    case 3:
       dir = "RD";
       break;
    default:
       dir = "Rx";
       break;
    }
    if (f) {
       fh = f->data;
       snprintf(retries, sizeof(retries), "%03d", f->retries);
    } else {
       fh = fhi;
       if (ntohs(fh->dcallno) & IAX_FLAG_RETRANS)
          strcpy(retries, "Yes");
       else
          strcpy(retries, " No");
    }
    if (!(ntohs(fh->scallno) & IAX_FLAG_FULL)) {
       /* Don't mess with mini-frames */
       return;
    }
    if (fh->type >= ARRAY_LEN(framelist)) {
       snprintf(class2, sizeof(class2), "(%d?)", fh->type);
       class = class2;
    } else {
       class = framelist[(int)fh->type];
    }
    if (fh->type == AST_FRAME_DTMF_BEGIN || fh->type == AST_FRAME_DTMF_END) {
       sprintf(subclass2, "%c", fh->csub);
       subclass = subclass2;
    } else if (fh->type == AST_FRAME_IAX) {
          iax_frame_subclass2str((int)fh->csub, subclass2, sizeof(subclass2));
          subclass = subclass2;
    } else if (fh->type == AST_FRAME_CONTROL) {
       if (fh->csub >= ARRAY_LEN(cmds)) {
          snprintf(subclass2, sizeof(subclass2), "(%d?)", fh->csub);
          subclass = subclass2;
       } else {
          subclass = cmds[(int)fh->csub];
       }
    } else {
       snprintf(subclass2, sizeof(subclass2), "%d", fh->csub);
       subclass = subclass2;
    }
    snprintf(tmp, sizeof(tmp),
       "%s-Frame Retry[%s] -- OSeqno: %3.3d ISeqno: %3.3d Type: %s Subclass: %s\n",
        dir,
        retries, fh->oseqno, fh->iseqno, class, subclass);
    outputf(tmp);
    snprintf(tmp, sizeof(tmp), "   Timestamp: %05lums  SCall: %5.5d  DCall: %5.5d %s\n",
          (unsigned long)ntohl(fh->ts),
          ntohs(fh->scallno) & ~IAX_FLAG_FULL,
          ntohs(fh->dcallno) & ~IAX_FLAG_RETRANS,
          ast_sockaddr_stringify(addr));
    outputf(tmp);
    if (fh->type == AST_FRAME_IAX)
       dump_ies(fh->iedata, datalen);
 }