Asterisk - The Open Source Telephony Project: resource_bridges.h File Reference
resource_bridges.h File Reference
Generated file - declares stubs to be implemented in res/ari/resource_bridges.c.
#include "asterisk/ari.h"
Data Structures
struct ast_ari_bridges_add_channel_args
struct ast_ari_bridges_clear_video_source_args
struct ast_ari_bridges_create_args
struct ast_ari_bridges_create_with_id_args
struct ast_ari_bridges_destroy_args
struct ast_ari_bridges_get_args
struct ast_ari_bridges_list_args
struct ast_ari_bridges_play_args
struct ast_ari_bridges_play_with_id_args
struct ast_ari_bridges_record_args
struct ast_ari_bridges_remove_channel_args
struct ast_ari_bridges_set_video_source_args
struct ast_ari_bridges_start_moh_args
struct ast_ari_bridges_stop_moh_args
Functions
void ast_ari_bridges_add_channel (struct ast_variable *headers, struct ast_ari_bridges_add_channel_args *args, struct ast_ari_response *response)
Add a channel to a bridge.
int ast_ari_bridges_add_channel_parse_body (struct ast_json *body, struct ast_ari_bridges_add_channel_args *args)
Body parsing function for /bridges/{bridgeId}/addChannel.
void ast_ari_bridges_clear_video_source (struct ast_variable *headers, struct ast_ari_bridges_clear_video_source_args *args, struct ast_ari_response *response)
Removes any explicit video source in a multi-party mixing bridge. This operation has no effect on bridges with two or fewer participants. When no explicit video source is set, talk detection will be used to determine the active video stream.
void ast_ari_bridges_create (struct ast_variable *headers, struct ast_ari_bridges_create_args *args, struct ast_ari_response *response)
Create a new bridge.
int ast_ari_bridges_create_parse_body (struct ast_json *body, struct ast_ari_bridges_create_args *args)
Body parsing function for /bridges.
void ast_ari_bridges_create_with_id (struct ast_variable *headers, struct ast_ari_bridges_create_with_id_args *args, struct ast_ari_response *response)
Create a new bridge or updates an existing one.
int ast_ari_bridges_create_with_id_parse_body (struct ast_json *body, struct ast_ari_bridges_create_with_id_args *args)
Body parsing function for /bridges/{bridgeId}.
void ast_ari_bridges_destroy (struct ast_variable *headers, struct ast_ari_bridges_destroy_args *args, struct ast_ari_response *response)
Shut down a bridge.
void ast_ari_bridges_get (struct ast_variable *headers, struct ast_ari_bridges_get_args *args, struct ast_ari_response *response)
Get bridge details.
void ast_ari_bridges_list (struct ast_variable *headers, struct ast_ari_bridges_list_args *args, struct ast_ari_response *response)
List all active bridges in Asterisk.
void ast_ari_bridges_play (struct ast_variable *headers, struct ast_ari_bridges_play_args *args, struct ast_ari_response *response)
Start playback of media on a bridge.
int ast_ari_bridges_play_parse_body (struct ast_json *body, struct ast_ari_bridges_play_args *args)
Body parsing function for /bridges/{bridgeId}/play.
void ast_ari_bridges_play_with_id (struct ast_variable *headers, struct ast_ari_bridges_play_with_id_args *args, struct ast_ari_response *response)
Start playback of media on a bridge.
int ast_ari_bridges_play_with_id_parse_body (struct ast_json *body, struct ast_ari_bridges_play_with_id_args *args)
Body parsing function for /bridges/{bridgeId}/play/{playbackId}.
void ast_ari_bridges_record (struct ast_variable *headers, struct ast_ari_bridges_record_args *args, struct ast_ari_response *response)
Start a recording.
int ast_ari_bridges_record_parse_body (struct ast_json *body, struct ast_ari_bridges_record_args *args)
Body parsing function for /bridges/{bridgeId}/record.
void ast_ari_bridges_remove_channel (struct ast_variable *headers, struct ast_ari_bridges_remove_channel_args *args, struct ast_ari_response *response)
Remove a channel from a bridge.
int ast_ari_bridges_remove_channel_parse_body (struct ast_json *body, struct ast_ari_bridges_remove_channel_args *args)
Body parsing function for /bridges/{bridgeId}/removeChannel.
void ast_ari_bridges_set_video_source (struct ast_variable *headers, struct ast_ari_bridges_set_video_source_args *args, struct ast_ari_response *response)
Set a channel as the video source in a multi-party mixing bridge. This operation has no effect on bridges with two or fewer participants.
void ast_ari_bridges_start_moh (struct ast_variable *headers, struct ast_ari_bridges_start_moh_args *args, struct ast_ari_response *response)
Play music on hold to a bridge or change the MOH class that is playing.
int ast_ari_bridges_start_moh_parse_body (struct ast_json *body, struct ast_ari_bridges_start_moh_args *args)
Body parsing function for /bridges/{bridgeId}/moh.
void ast_ari_bridges_stop_moh (struct ast_variable *headers, struct ast_ari_bridges_stop_moh_args *args, struct ast_ari_response *response)
Stop playing music on hold to a bridge.
Detailed Description
Generated file - declares stubs to be implemented in res/ari/resource_bridges.c.
Bridge resources
Author
David M. Lee, II dlee@.nosp@m.digi.nosp@m.um.co.nosp@m.m
Definition in file resource_bridges.h.
Function Documentation
ast_ari_bridges_add_channel()
void ast_ari_bridges_add_channel (struct ast_variable * headers, struct ast_ari_bridges_add_channel_args * args, struct ast_ari_response * response)
Add a channel to a bridge.
Parameters
headers HTTP headers
args Swagger parameters
[out] response HTTP response
Definition at line 191 of file resource_bridges.c.
References ast_ari_bridges_add_channel_args::absorb_dtmf, ao2_cleanup, ast_ari_response_alloc_failed(), ast_ari_response_no_content(), ast_strlen_zero, ast_ari_bridges_add_channel_args::bridge_id, ast_ari_bridges_add_channel_args::channel, ast_ari_bridges_add_channel_args::channel_count, check_add_remove_channel(), control_list_create(), find_bridge(), ast_ari_bridges_add_channel_args::inhibit_connected_line_updates, ast_ari_bridges_add_channel_args::mute, NULL, RAII_VAR, ast_ari_bridges_add_channel_args::role, stasis_app_control_absorb_dtmf_in_bridge(), stasis_app_control_add_channel_to_bridge(), stasis_app_control_add_role(), stasis_app_control_bridge_features_init(), stasis_app_control_clear_roles(), stasis_app_control_inhibit_colp_in_bridge(), and stasis_app_control_mute_in_bridge().
Referenced by ast_ari_bridges_add_channel_cb().
 {
    RAII_VAR(struct ast_bridge *, bridge, find_bridge(response, args->bridge_id), ao2_cleanup);
    RAII_VAR(struct control_list *, list, NULL, ao2_cleanup);
    size_t i;
    int has_error = 0;
    if (!bridge) {
       /* Response filled in by find_bridge() */
       return;
    }
    list = control_list_create(response, args->channel_count, args->channel);
    if (!list) {
       /* Response filled in by control_list_create() */
       return;
    }
    for (i = 0; i < list->count; ++i) {
       stasis_app_control_clear_roles(list->controls[i]);
       if (!ast_strlen_zero(args->role)) {
          if (stasis_app_control_add_role(list->controls[i], args->role)) {
             ast_ari_response_alloc_failed(response);
             return;
          }
       }
       /* Apply bridge features to each of the channel controls */
       if (!stasis_app_control_bridge_features_init(list->controls[i])) {
          stasis_app_control_absorb_dtmf_in_bridge(list->controls[i], args->absorb_dtmf);
          stasis_app_control_mute_in_bridge(list->controls[i], args->mute);
          stasis_app_control_inhibit_colp_in_bridge(list->controls[i], args->inhibit_connected_line_updates);
       }
    }
    for (i = 0; i < list->count; ++i) {
       if ((has_error = check_add_remove_channel(response, list->controls[i],
               stasis_app_control_add_channel_to_bridge(
                 list->controls[i], bridge)))) {
          break;
       }
    }
    if (!has_error) {
       ast_ari_response_no_content(response);
    }
 }
ast_ari_bridges_add_channel_parse_body()
int ast_ari_bridges_add_channel_parse_body (struct ast_json * body, struct ast_ari_bridges_add_channel_args * args)
Body parsing function for /bridges/{bridgeId}/addChannel.
Parameters
body The JSON body from which to parse parameters.
[out] args The args structure to parse into.
Return values
zero on success
non-zero on failure
Definition at line 396 of file res_ari_bridges.c.
References ast_ari_bridges_add_channel_args::absorb_dtmf, ast_free, AST_JSON_ARRAY, ast_json_array_get(), ast_json_array_size(), ast_json_is_true(), ast_json_object_get(), ast_json_string_get(), ast_json_typeof(), ast_malloc, ast_ari_bridges_add_channel_args::channel, ast_ari_bridges_add_channel_args::channel_count, ast_ari_bridges_add_channel_args::inhibit_connected_line_updates, ast_ari_bridges_add_channel_args::mute, and ast_ari_bridges_add_channel_args::role.
Referenced by ast_ari_bridges_add_channel_cb().
 {
    struct ast_json *field;
    /* Parse query parameters out of it */
    field = ast_json_object_get(body, "channel");
    if (field) {
       /* If they were silly enough to both pass in a query param and a
        * JSON body, free up the query value.
        */
       ast_free(args->channel);
       if (ast_json_typeof(field) == AST_JSON_ARRAY) {
          /* Multiple param passed as array */
          size_t i;
          args->channel_count = ast_json_array_size(field);
          args->channel = ast_malloc(sizeof(*args->channel) * args->channel_count);
          if (!args->channel) {
             return -1;
          }
          for (i = 0; i < args->channel_count; ++i) {
             args->channel[i] = ast_json_string_get(ast_json_array_get(field, i));
          }
       } else {
          /* Multiple param passed as single value */
          args->channel_count = 1;
          args->channel = ast_malloc(sizeof(*args->channel) * args->channel_count);
          if (!args->channel) {
             return -1;
          }
          args->channel[0] = ast_json_string_get(field);
       }
    }
    field = ast_json_object_get(body, "role");
    if (field) {
       args->role = ast_json_string_get(field);
    }
    field = ast_json_object_get(body, "absorbDTMF");
    if (field) {
       args->absorb_dtmf = ast_json_is_true(field);
    }
    field = ast_json_object_get(body, "mute");
    if (field) {
       args->mute = ast_json_is_true(field);
    }
    field = ast_json_object_get(body, "inhibitConnectedLineUpdates");
    if (field) {
       args->inhibit_connected_line_updates = ast_json_is_true(field);
    }
    return 0;
 }
ast_ari_bridges_clear_video_source()
void ast_ari_bridges_clear_video_source (struct ast_variable * headers, struct ast_ari_bridges_clear_video_source_args * args, struct ast_ari_response * response)
Removes any explicit video source in a multi-party mixing bridge. This operation has no effect on bridges with two or fewer participants. When no explicit video source is set, talk detection will be used to determine the active video stream.
Parameters
headers HTTP headers
args Swagger parameters
[out] response HTTP response
Definition at line 1051 of file resource_bridges.c.
References ao2_ref, ast_ari_response_no_content(), ast_bridge_lock, ast_bridge_set_talker_src_video_mode(), ast_bridge_unlock, ast_ari_bridges_clear_video_source_args::bridge_id, and find_bridge().
Referenced by ast_ari_bridges_clear_video_source_cb().
 {
    struct ast_bridge *bridge;
    bridge = find_bridge(response, args->bridge_id);
    if (!bridge) {
       return;
    }
    ast_bridge_lock(bridge);
    ast_bridge_set_talker_src_video_mode(bridge);
    ast_bridge_unlock(bridge);
    ao2_ref(bridge, -1);
    ast_ari_response_no_content(response);
 }
ast_ari_bridges_create()
void ast_ari_bridges_create (struct ast_variable * headers, struct ast_ari_bridges_create_args * args, struct ast_ari_response * response)
Create a new bridge.
This bridge persists until it has been shut down, or Asterisk has been shut down.
Parameters
headers HTTP headers
args Swagger parameters
[out] response HTTP response
Definition at line 925 of file resource_bridges.c.
References ao2_cleanup, ast_ari_response_error(), ast_ari_response_ok(), ast_bridge_lock, ast_bridge_snapshot_create(), ast_bridge_snapshot_to_json(), ast_bridge_unlock, ast_ari_bridges_create_args::bridge_id, ast_ari_bridges_create_args::name, NULL, RAII_VAR, stasis_app_bridge_create(), stasis_app_get_sanitizer(), and ast_ari_bridges_create_args::type.
Referenced by ast_ari_bridges_create_cb().
 {
    RAII_VAR(struct ast_bridge *, bridge, stasis_app_bridge_create(args->type, args->name, args->bridge_id), ao2_cleanup);
    RAII_VAR(struct ast_bridge_snapshot *, snapshot, NULL, ao2_cleanup);
    if (!bridge) {
       ast_ari_response_error(
          response, 500, "Internal Error",
          "Unable to create bridge");
       return;
    }
    ast_bridge_lock(bridge);
    snapshot = ast_bridge_snapshot_create(bridge);
    ast_bridge_unlock(bridge);
    if (!snapshot) {
       ast_ari_response_error(
          response, 500, "Internal Error",
          "Unable to create snapshot for new bridge");
       return;
    }
    ast_ari_response_ok(response,
       ast_bridge_snapshot_to_json(snapshot, stasis_app_get_sanitizer()));
 }
ast_ari_bridges_create_parse_body()
int ast_ari_bridges_create_parse_body (struct ast_json * body, struct ast_ari_bridges_create_args * args)
Body parsing function for /bridges.
Parameters
body The JSON body from which to parse parameters.
[out] args The args structure to parse into.
Return values
zero on success
non-zero on failure
Definition at line 105 of file res_ari_bridges.c.
References ast_json_object_get(), ast_json_string_get(), ast_ari_bridges_create_args::bridge_id, ast_ari_bridges_create_args::name, and ast_ari_bridges_create_args::type.
Referenced by ast_ari_bridges_create_cb().
 {
    struct ast_json *field;
    /* Parse query parameters out of it */
    field = ast_json_object_get(body, "type");
    if (field) {
       args->type = ast_json_string_get(field);
    }
    field = ast_json_object_get(body, "bridgeId");
    if (field) {
       args->bridge_id = ast_json_string_get(field);
    }
    field = ast_json_object_get(body, "name");
    if (field) {
       args->name = ast_json_string_get(field);
    }
    return 0;
 }
ast_ari_bridges_create_with_id()
void ast_ari_bridges_create_with_id (struct ast_variable * headers, struct ast_ari_bridges_create_with_id_args * args, struct ast_ari_response * response)
Create a new bridge or updates an existing one.
This bridge persists until it has been shut down, or Asterisk has been shut down.
Parameters
headers HTTP headers
args Swagger parameters
[out] response HTTP response
Definition at line 954 of file resource_bridges.c.
References ao2_cleanup, ast_ari_response_error(), ast_ari_response_ok(), ast_bridge_lock, ast_bridge_snapshot_create(), ast_bridge_snapshot_to_json(), ast_bridge_unlock, ast_strlen_zero, ast_ari_bridges_create_with_id_args::bridge_id, find_bridge(), ast_ari_bridges_create_with_id_args::name, NULL, RAII_VAR, stasis_app_bridge_create(), stasis_app_get_sanitizer(), and ast_ari_bridges_create_with_id_args::type.
Referenced by ast_ari_bridges_create_with_id_cb().
 {
    RAII_VAR(struct ast_bridge *, bridge, find_bridge(response, args->bridge_id), ao2_cleanup);
    RAII_VAR(struct ast_bridge_snapshot *, snapshot, NULL, ao2_cleanup);
    if (bridge) {
       /* update */
       if (!ast_strlen_zero(args->name)
          && strcmp(args->name, bridge->name)) {
          ast_ari_response_error(
             response, 500, "Internal Error",
             "Changing bridge name is not implemented");
          return;
       }
       if (!ast_strlen_zero(args->type)) {
          ast_ari_response_error(
             response, 500, "Internal Error",
             "Supplying a bridge type when updating a bridge is not allowed.");
          return;
       }
       ast_ari_response_ok(response,
          ast_bridge_snapshot_to_json(snapshot, stasis_app_get_sanitizer()));
       return;
    }
    bridge = stasis_app_bridge_create(args->type, args->name, args->bridge_id);
    if (!bridge) {
       ast_ari_response_error(
          response, 500, "Internal Error",
          "Unable to create bridge");
       return;
    }
    ast_bridge_lock(bridge);
    snapshot = ast_bridge_snapshot_create(bridge);
    ast_bridge_unlock(bridge);
    if (!snapshot) {
       ast_ari_response_error(
          response, 500, "Internal Error",
          "Unable to create snapshot for new bridge");
       return;
    }
    ast_ari_response_ok(response,
       ast_bridge_snapshot_to_json(snapshot, stasis_app_get_sanitizer()));
 }
ast_ari_bridges_create_with_id_parse_body()
int ast_ari_bridges_create_with_id_parse_body (struct ast_json * body, struct ast_ari_bridges_create_with_id_args * args)
Body parsing function for /bridges/{bridgeId}.
Parameters
body The JSON body from which to parse parameters.
[out] args The args structure to parse into.
Return values
zero on success
non-zero on failure
Definition at line 193 of file res_ari_bridges.c.
References ast_json_object_get(), ast_json_string_get(), ast_ari_bridges_create_with_id_args::name, and ast_ari_bridges_create_with_id_args::type.
Referenced by ast_ari_bridges_create_with_id_cb().
 {
    struct ast_json *field;
    /* Parse query parameters out of it */
    field = ast_json_object_get(body, "type");
    if (field) {
       args->type = ast_json_string_get(field);
    }
    field = ast_json_object_get(body, "name");
    if (field) {
       args->name = ast_json_string_get(field);
    }
    return 0;
 }
ast_ari_bridges_destroy()
void ast_ari_bridges_destroy (struct ast_variable * headers, struct ast_ari_bridges_destroy_args * args, struct ast_ari_response * response)
Shut down a bridge.
If any channels are in this bridge, they will be removed and resume whatever they were doing beforehand.
Parameters
headers HTTP headers
args Swagger parameters
[out] response HTTP response
Definition at line 872 of file resource_bridges.c.
References ao2_cleanup, ast_ari_response_no_content(), ast_ari_bridges_destroy_args::bridge_id, find_bridge(), RAII_VAR, and stasis_app_bridge_destroy().
Referenced by ast_ari_bridges_destroy_cb().
 {
    RAII_VAR(struct ast_bridge *, bridge, find_bridge(response, args->bridge_id), ao2_cleanup);
    if (!bridge) {
       return;
    }
    stasis_app_bridge_destroy(args->bridge_id);
    ast_ari_response_no_content(response);
 }
ast_ari_bridges_get()
void ast_ari_bridges_get (struct ast_variable * headers, struct ast_ari_bridges_get_args * args, struct ast_ari_response * response)
Get bridge details.
Parameters
headers HTTP headers
args Swagger parameters
[out] response HTTP response
Definition at line 856 of file resource_bridges.c.
References ao2_cleanup, ast_ari_response_error(), ast_ari_response_ok(), ast_bridge_get_snapshot_by_uniqueid(), ast_bridge_snapshot_to_json(), ast_ari_bridges_get_args::bridge_id, RAII_VAR, and stasis_app_get_sanitizer().
Referenced by ast_ari_bridges_get_cb().
 {
    RAII_VAR(struct ast_bridge_snapshot *, snapshot, ast_bridge_get_snapshot_by_uniqueid(args->bridge_id), ao2_cleanup);
    if (!snapshot) {
       ast_ari_response_error(
          response, 404, "Not Found",
          "Bridge not found");
       return;
    }
    ast_ari_response_ok(response,
       ast_bridge_snapshot_to_json(snapshot, stasis_app_get_sanitizer()));
 }
ast_ari_bridges_list()
void ast_ari_bridges_list (struct ast_variable * headers, struct ast_ari_bridges_list_args * args, struct ast_ari_response * response)
List all active bridges in Asterisk.
Parameters
headers HTTP headers
args Swagger parameters
[out] response HTTP response
Definition at line 885 of file resource_bridges.c.
References ao2_cleanup, ao2_iterator_destroy(), ao2_iterator_init(), ao2_iterator_next, ao2_ref, ast_ari_response_alloc_failed(), ast_ari_response_ok(), ast_bridge_get_snapshot(), ast_bridge_snapshot_to_json(), ast_bridges(), ast_json_array_append(), ast_json_array_create(), ast_json_ref(), ast_json_unref(), bridges, NULL, RAII_VAR, and stasis_app_get_sanitizer().
Referenced by ast_ari_bridges_list_cb().
 {
    RAII_VAR(struct ao2_container *, bridges, NULL, ao2_cleanup);
    RAII_VAR(struct ast_json *, json, NULL, ast_json_unref);
    struct ao2_iterator i;
    struct ast_bridge *bridge;
    bridges = ast_bridges();
    if (!bridges) {
       ast_ari_response_alloc_failed(response);
       return;
    }
    json = ast_json_array_create();
    if (!json) {
       ast_ari_response_alloc_failed(response);
       return;
    }
    i = ao2_iterator_init(bridges, 0);
    while ((bridge = ao2_iterator_next(&i))) {
       struct ast_bridge_snapshot *snapshot = ast_bridge_get_snapshot(bridge);
       /* ast_bridge_snapshot_to_json will return NULL if snapshot is NULL */
       struct ast_json *json_bridge = ast_bridge_snapshot_to_json(snapshot, stasis_app_get_sanitizer());
       ao2_ref(bridge, -1);
       ao2_cleanup(snapshot);
       if (!json_bridge || ast_json_array_append(json, json_bridge)) {
          ao2_iterator_destroy(&i);
          ast_ari_response_alloc_failed(response);
          return;
       }
    }
    ao2_iterator_destroy(&i);
    ast_ari_response_ok(response, ast_json_ref(json));
 }
ast_ari_bridges_play()
void ast_ari_bridges_play (struct ast_variable * headers, struct ast_ari_bridges_play_args * args, struct ast_ari_response * response)
Start playback of media on a bridge.
The media URI may be any of a number of URI's. Currently sound:, recording:, number:, digits:, characters:, and tone: URI's are supported. This operation creates a playback resource that can be used to control the playback of media (pause, rewind, fast forward, etc.)
Parameters
headers HTTP headers
args Swagger parameters
[out] response HTTP response
Definition at line 606 of file resource_bridges.c.
References ari_bridges_handle_play(), ast_ari_bridges_play_args::bridge_id, ast_ari_bridges_play_args::lang, ast_ari_bridges_play_args::media, ast_ari_bridges_play_args::media_count, ast_ari_bridges_play_args::offsetms, ast_ari_bridges_play_args::playback_id, and ast_ari_bridges_play_args::skipms.
Referenced by ast_ari_bridges_play_cb().
 {
    ari_bridges_handle_play(args->bridge_id,
    args->media,
    args->media_count,
    args->lang,
    args->offsetms,
    args->skipms,
    args->playback_id,
    response);
 }
ast_ari_bridges_play_parse_body()
int ast_ari_bridges_play_parse_body (struct ast_json * body, struct ast_ari_bridges_play_args * args)
Body parsing function for /bridges/{bridgeId}/play.
Parameters
body The JSON body from which to parse parameters.
[out] args The args structure to parse into.
Return values
zero on success
non-zero on failure
Definition at line 988 of file res_ari_bridges.c.
References ast_free, AST_JSON_ARRAY, ast_json_array_get(), ast_json_array_size(), ast_json_integer_get(), ast_json_object_get(), ast_json_string_get(), ast_json_typeof(), ast_malloc, ast_ari_bridges_play_args::lang, ast_ari_bridges_play_args::media, ast_ari_bridges_play_args::media_count, ast_ari_bridges_play_args::offsetms, ast_ari_bridges_play_args::playback_id, and ast_ari_bridges_play_args::skipms.
Referenced by ast_ari_bridges_play_cb().
 {
    struct ast_json *field;
    /* Parse query parameters out of it */
    field = ast_json_object_get(body, "media");
    if (field) {
       /* If they were silly enough to both pass in a query param and a
        * JSON body, free up the query value.
        */
       ast_free(args->media);
       if (ast_json_typeof(field) == AST_JSON_ARRAY) {
          /* Multiple param passed as array */
          size_t i;
          args->media_count = ast_json_array_size(field);
          args->media = ast_malloc(sizeof(*args->media) * args->media_count);
          if (!args->media) {
             return -1;
          }
          for (i = 0; i < args->media_count; ++i) {
             args->media[i] = ast_json_string_get(ast_json_array_get(field, i));
          }
       } else {
          /* Multiple param passed as single value */
          args->media_count = 1;
          args->media = ast_malloc(sizeof(*args->media) * args->media_count);
          if (!args->media) {
             return -1;
          }
          args->media[0] = ast_json_string_get(field);
       }
    }
    field = ast_json_object_get(body, "lang");
    if (field) {
       args->lang = ast_json_string_get(field);
    }
    field = ast_json_object_get(body, "offsetms");
    if (field) {
       args->offsetms = ast_json_integer_get(field);
    }
    field = ast_json_object_get(body, "skipms");
    if (field) {
       args->skipms = ast_json_integer_get(field);
    }
    field = ast_json_object_get(body, "playbackId");
    if (field) {
       args->playback_id = ast_json_string_get(field);
    }
    return 0;
 }
ast_ari_bridges_play_with_id()
void ast_ari_bridges_play_with_id (struct ast_variable * headers, struct ast_ari_bridges_play_with_id_args * args, struct ast_ari_response * response)
Start playback of media on a bridge.
The media URI may be any of a number of URI's. Currently sound:, recording:, number:, digits:, characters:, and tone: URI's are supported. This operation creates a playback resource that can be used to control the playback of media (pause, rewind, fast forward, etc.)
Parameters
headers HTTP headers
args Swagger parameters
[out] response HTTP response
Definition at line 620 of file resource_bridges.c.
References ari_bridges_handle_play(), ast_ari_bridges_play_with_id_args::bridge_id, ast_ari_bridges_play_with_id_args::lang, ast_ari_bridges_play_with_id_args::media, ast_ari_bridges_play_with_id_args::media_count, ast_ari_bridges_play_with_id_args::offsetms, ast_ari_bridges_play_with_id_args::playback_id, and ast_ari_bridges_play_with_id_args::skipms.
Referenced by ast_ari_bridges_play_with_id_cb().
 {
    ari_bridges_handle_play(args->bridge_id,
    args->media,
    args->media_count,
    args->lang,
    args->offsetms,
    args->skipms,
    args->playback_id,
    response);
 }
ast_ari_bridges_play_with_id_parse_body()
int ast_ari_bridges_play_with_id_parse_body (struct ast_json * body, struct ast_ari_bridges_play_with_id_args * args)
Body parsing function for /bridges/{bridgeId}/play/{playbackId}.
Parameters
body The JSON body from which to parse parameters.
[out] args The args structure to parse into.
Return values
zero on success
non-zero on failure
Definition at line 1165 of file res_ari_bridges.c.
References ast_free, AST_JSON_ARRAY, ast_json_array_get(), ast_json_array_size(), ast_json_integer_get(), ast_json_object_get(), ast_json_string_get(), ast_json_typeof(), ast_malloc, ast_ari_bridges_play_with_id_args::lang, ast_ari_bridges_play_with_id_args::media, ast_ari_bridges_play_with_id_args::media_count, ast_ari_bridges_play_with_id_args::offsetms, and ast_ari_bridges_play_with_id_args::skipms.
Referenced by ast_ari_bridges_play_with_id_cb().
 {
    struct ast_json *field;
    /* Parse query parameters out of it */
    field = ast_json_object_get(body, "media");
    if (field) {
       /* If they were silly enough to both pass in a query param and a
        * JSON body, free up the query value.
        */
       ast_free(args->media);
       if (ast_json_typeof(field) == AST_JSON_ARRAY) {
          /* Multiple param passed as array */
          size_t i;
          args->media_count = ast_json_array_size(field);
          args->media = ast_malloc(sizeof(*args->media) * args->media_count);
          if (!args->media) {
             return -1;
          }
          for (i = 0; i < args->media_count; ++i) {
             args->media[i] = ast_json_string_get(ast_json_array_get(field, i));
          }
       } else {
          /* Multiple param passed as single value */
          args->media_count = 1;
          args->media = ast_malloc(sizeof(*args->media) * args->media_count);
          if (!args->media) {
             return -1;
          }
          args->media[0] = ast_json_string_get(field);
       }
    }
    field = ast_json_object_get(body, "lang");
    if (field) {
       args->lang = ast_json_string_get(field);
    }
    field = ast_json_object_get(body, "offsetms");
    if (field) {
       args->offsetms = ast_json_integer_get(field);
    }
    field = ast_json_object_get(body, "skipms");
    if (field) {
       args->skipms = ast_json_integer_get(field);
    }
    return 0;
 }
ast_ari_bridges_record()
void ast_ari_bridges_record (struct ast_variable * headers, struct ast_ari_bridges_record_args * args, struct ast_ari_response * response)
Start a recording.
This records the mixed audio from all channels participating in this bridge.
Parameters
headers HTTP headers
args Swagger parameters
[out] response HTTP response
Definition at line 634 of file resource_bridges.c.
References ao2_cleanup, ast_ari_response_alloc_failed(), ast_ari_response_created(), ast_ari_response_error(), ast_asprintf, ast_assert, AST_BRIDGE_CHANNEL_FLAG_IMMOVABLE, AST_BRIDGE_CHANNEL_FLAG_LONELY, ast_bridge_topic(), ast_calloc, ast_channel_topic(), ast_free, ast_get_format_for_file_ext(), ast_hangup(), ast_json_ref(), ast_json_unref(), ast_log, ast_malloc, ast_pthread_create_detached, AST_RECORD_IF_EXISTS_ERROR, ast_string_field_build, ast_unreal_channel_push_to_bridge(), ast_uri_encode(), ast_uri_http, ast_ari_bridges_record_args::beep, bridge_channel_control_thread_data::bridge_channel, bridge_channel_control_thread(), ast_ari_bridges_record_args::bridge_id, bridge_channel_control_thread_data::control, errno, find_bridge(), ast_ari_bridges_record_args::format, bridge_channel_control_thread_data::forward, ast_ari_bridges_record_args::if_exists, LOG_WARNING, ast_ari_bridges_record_args::max_duration_seconds, ast_ari_bridges_record_args::max_silence_seconds, ast_ari_bridges_record_args::name, NULL, options, prepare_bridge_media_channel(), RAII_VAR, stasis_app_control_create(), stasis_app_control_record(), stasis_app_recording_if_exists_parse(), stasis_app_recording_options_create(), STASIS_APP_RECORDING_TERMINATE_INVALID, stasis_app_recording_termination_parse(), stasis_app_recording_to_json(), stasis_forward_all(), stasis_forward_cancel(), and ast_ari_bridges_record_args::terminate_on.
Referenced by ast_ari_bridges_record_cb().
 {
    RAII_VAR(struct ast_bridge *, bridge, find_bridge(response, args->bridge_id), ao2_cleanup);
    RAII_VAR(struct ast_channel *, record_channel, NULL, ast_hangup);
    RAII_VAR(struct stasis_app_control *, control, NULL, ao2_cleanup);
    RAII_VAR(struct stasis_app_recording *, recording, NULL, ao2_cleanup);
    RAII_VAR(char *, recording_url, NULL, ast_free);
    RAII_VAR(struct ast_json *, json, NULL, ast_json_unref);
    RAII_VAR(struct stasis_app_recording_options *, options, NULL, ao2_cleanup);
    RAII_VAR(char *, uri_encoded_name, NULL, ast_free);
    RAII_VAR(struct stasis_forward *, channel_forward, NULL, stasis_forward_cancel);
    struct stasis_topic *channel_topic;
    struct stasis_topic *bridge_topic;
    size_t uri_name_maxlen;
    struct bridge_channel_control_thread_data *thread_data;
    pthread_t threadid;
    ast_assert(response != NULL);
    if (bridge == NULL) {
       return;
    }
    if (!(record_channel = prepare_bridge_media_channel("Recorder"))) {
       ast_ari_response_error(
          response, 500, "Internal Server Error", "Failed to create recording channel");
       return;
    }
    bridge_topic = ast_bridge_topic(bridge);
    channel_topic = ast_channel_topic(record_channel);
    /* Forward messages from the recording channel topic to the bridge topic so that anything listening for
     * messages on the bridge topic will receive the recording start/stop messages. Other messages that would
     * go to this channel will be suppressed since the channel is marked as internal.
     */
    if (!bridge_topic || !channel_topic || !(channel_forward = stasis_forward_all(channel_topic, bridge_topic))) {
       ast_ari_response_error(
          response, 500, "Internal Error", "Could not forward record channel stasis messages to bridge topic");
       return;
    }
    if (ast_unreal_channel_push_to_bridge(record_channel, bridge,
       AST_BRIDGE_CHANNEL_FLAG_IMMOVABLE | AST_BRIDGE_CHANNEL_FLAG_LONELY)) {
       ast_ari_response_error(
          response, 500, "Internal Error", "Failed to put recording channel into the bridge");
       return;
    }
    control = stasis_app_control_create(record_channel);
    if (control == NULL) {
       ast_ari_response_alloc_failed(response);
       return;
    }
    options = stasis_app_recording_options_create(args->name, args->format);
    if (options == NULL) {
       ast_ari_response_alloc_failed(response);
       return;
    }
    ast_string_field_build(options, target, "bridge:%s", args->bridge_id);
    options->max_silence_seconds = args->max_silence_seconds;
    options->max_duration_seconds = args->max_duration_seconds;
    options->terminate_on =
       stasis_app_recording_termination_parse(args->terminate_on);
    options->if_exists =
       stasis_app_recording_if_exists_parse(args->if_exists);
    options->beep = args->beep;
    if (options->terminate_on == STASIS_APP_RECORDING_TERMINATE_INVALID) {
       ast_ari_response_error(
          response, 400, "Bad Request",
          "terminateOn invalid");
       return;
    }
    if (options->if_exists == AST_RECORD_IF_EXISTS_ERROR) {
       ast_ari_response_error(
          response, 400, "Bad Request",
          "ifExists invalid");
       return;
    }
    if (!ast_get_format_for_file_ext(options->format)) {
       ast_ari_response_error(
          response, 422, "Unprocessable Entity",
          "specified format is unknown on this system");
       return;
    }
    recording = stasis_app_control_record(control, options);
    if (recording == NULL) {
       switch(errno) {
       case EINVAL:
          /* While the arguments are invalid, we should have
           * caught them prior to calling record.
           */
          ast_ari_response_error(
             response, 500, "Internal Server Error",
             "Error parsing request");
          break;
       case EEXIST:
          ast_ari_response_error(response, 409, "Conflict",
             "Recording '%s' already exists and can not be overwritten",
             args->name);
          break;
       case ENOMEM:
          ast_ari_response_alloc_failed(response);
          break;
       case EPERM:
          ast_ari_response_error(
             response, 400, "Bad Request",
             "Recording name invalid");
          break;
       default:
          ast_log(LOG_WARNING,
             "Unrecognized recording error: %s\n",
             strerror(errno));
          ast_ari_response_error(
             response, 500, "Internal Server Error",
             "Internal Server Error");
          break;
       }
       return;
    }
    uri_name_maxlen = strlen(args->name) * 3;
    uri_encoded_name = ast_malloc(uri_name_maxlen);
    if (!uri_encoded_name) {
       ast_ari_response_alloc_failed(response);
       return;
    }
    ast_uri_encode(args->name, uri_encoded_name, uri_name_maxlen, ast_uri_http);
    if (ast_asprintf(&recording_url, "/recordings/live/%s",
          uri_encoded_name) == -1) {
       recording_url = NULL;
       ast_ari_response_alloc_failed(response);
       return;
    }
    json = stasis_app_recording_to_json(recording);
    if (!json) {
       ast_ari_response_alloc_failed(response);
       return;
    }
    thread_data = ast_calloc(1, sizeof(*thread_data));
    if (!thread_data) {
       ast_ari_response_alloc_failed(response);
       return;
    }
    thread_data->bridge_channel = record_channel;
    thread_data->control = control;
    thread_data->forward = channel_forward;
    if (ast_pthread_create_detached(&threadid, NULL, bridge_channel_control_thread, thread_data)) {
       ast_ari_response_alloc_failed(response);
       ast_free(thread_data);
       return;
    }
    /* These are owned by the other thread now, so we don't want RAII_VAR disposing of them. */
    record_channel = NULL;
    control = NULL;
    channel_forward = NULL;
    ast_ari_response_created(response, recording_url, ast_json_ref(json));
 }
ast_ari_bridges_record_parse_body()
int ast_ari_bridges_record_parse_body (struct ast_json * body, struct ast_ari_bridges_record_args * args)
Body parsing function for /bridges/{bridgeId}/record.
Parameters
body The JSON body from which to parse parameters.
[out] args The args structure to parse into.
Return values
zero on success
non-zero on failure
Definition at line 1338 of file res_ari_bridges.c.
References ast_json_integer_get(), ast_json_is_true(), ast_json_object_get(), ast_json_string_get(), ast_ari_bridges_record_args::beep, ast_ari_bridges_record_args::format, ast_ari_bridges_record_args::if_exists, ast_ari_bridges_record_args::max_duration_seconds, ast_ari_bridges_record_args::max_silence_seconds, ast_ari_bridges_record_args::name, and ast_ari_bridges_record_args::terminate_on.
Referenced by ast_ari_bridges_record_cb().
 {
    struct ast_json *field;
    /* Parse query parameters out of it */
    field = ast_json_object_get(body, "name");
    if (field) {
       args->name = ast_json_string_get(field);
    }
    field = ast_json_object_get(body, "format");
    if (field) {
       args->format = ast_json_string_get(field);
    }
    field = ast_json_object_get(body, "maxDurationSeconds");
    if (field) {
       args->max_duration_seconds = ast_json_integer_get(field);
    }
    field = ast_json_object_get(body, "maxSilenceSeconds");
    if (field) {
       args->max_silence_seconds = ast_json_integer_get(field);
    }
    field = ast_json_object_get(body, "ifExists");
    if (field) {
       args->if_exists = ast_json_string_get(field);
    }
    field = ast_json_object_get(body, "beep");
    if (field) {
       args->beep = ast_json_is_true(field);
    }
    field = ast_json_object_get(body, "terminateOn");
    if (field) {
       args->terminate_on = ast_json_string_get(field);
    }
    return 0;
 }
ast_ari_bridges_remove_channel()
void ast_ari_bridges_remove_channel (struct ast_variable * headers, struct ast_ari_bridges_remove_channel_args * args, struct ast_ari_response * response)
Remove a channel from a bridge.
Parameters
headers HTTP headers
args Swagger parameters
[out] response HTTP response
Definition at line 241 of file resource_bridges.c.
References ao2_cleanup, ast_ari_response_error(), ast_ari_response_no_content(), ast_log, ast_ari_bridges_remove_channel_args::bridge_id, ast_ari_bridges_remove_channel_args::channel, ast_ari_bridges_remove_channel_args::channel_count, control_list_create(), find_bridge(), LOG_WARNING, NULL, RAII_VAR, stasis_app_control_remove_channel_from_bridge(), and stasis_app_get_bridge().
Referenced by ast_ari_bridges_remove_channel_cb().
 {
    RAII_VAR(struct ast_bridge *, bridge, find_bridge(response, args->bridge_id), ao2_cleanup);
    RAII_VAR(struct control_list *, list, NULL, ao2_cleanup);
    size_t i;
    if (!bridge) {
       /* Response filled in by find_bridge() */
       return;
    }
    list = control_list_create(response, args->channel_count, args->channel);
    if (!list) {
       /* Response filled in by control_list_create() */
       return;
    }
    /* Make sure all of the channels are in this bridge */
    for (i = 0; i < list->count; ++i) {
       if (stasis_app_get_bridge(list->controls[i]) != bridge) {
          ast_log(LOG_WARNING, "Channel %s not in bridge %s\n",
             args->channel[i], args->bridge_id);
          ast_ari_response_error(response, 422,
             "Unprocessable Entity",
             "Channel not in this bridge");
          return;
       }
    }
    /* Now actually remove it */
    for (i = 0; i < list->count; ++i) {
       stasis_app_control_remove_channel_from_bridge(list->controls[i],
          bridge);
    }
    ast_ari_response_no_content(response);
 }
ast_ari_bridges_remove_channel_parse_body()
int ast_ari_bridges_remove_channel_parse_body (struct ast_json * body, struct ast_ari_bridges_remove_channel_args * args)
Body parsing function for /bridges/{bridgeId}/removeChannel.
Parameters
body The JSON body from which to parse parameters.
[out] args The args structure to parse into.
Return values
zero on success
non-zero on failure
Definition at line 575 of file res_ari_bridges.c.
References ast_free, AST_JSON_ARRAY, ast_json_array_get(), ast_json_array_size(), ast_json_object_get(), ast_json_string_get(), ast_json_typeof(), ast_malloc, ast_ari_bridges_remove_channel_args::channel, and ast_ari_bridges_remove_channel_args::channel_count.
Referenced by ast_ari_bridges_remove_channel_cb().
 {
    struct ast_json *field;
    /* Parse query parameters out of it */
    field = ast_json_object_get(body, "channel");
    if (field) {
       /* If they were silly enough to both pass in a query param and a
        * JSON body, free up the query value.
        */
       ast_free(args->channel);
       if (ast_json_typeof(field) == AST_JSON_ARRAY) {
          /* Multiple param passed as array */
          size_t i;
          args->channel_count = ast_json_array_size(field);
          args->channel = ast_malloc(sizeof(*args->channel) * args->channel_count);
          if (!args->channel) {
             return -1;
          }
          for (i = 0; i < args->channel_count; ++i) {
             args->channel[i] = ast_json_string_get(ast_json_array_get(field, i));
          }
       } else {
          /* Multiple param passed as single value */
          args->channel_count = 1;
          args->channel = ast_malloc(sizeof(*args->channel) * args->channel_count);
          if (!args->channel) {
             return -1;
          }
          args->channel[0] = ast_json_string_get(field);
       }
    }
    return 0;
 }
ast_ari_bridges_set_video_source()
void ast_ari_bridges_set_video_source (struct ast_variable * headers, struct ast_ari_bridges_set_video_source_args * args, struct ast_ari_response * response)
Set a channel as the video source in a multi-party mixing bridge. This operation has no effect on bridges with two or fewer participants.
Parameters
headers HTTP headers
args Swagger parameters
[out] response HTTP response
Definition at line 1016 of file resource_bridges.c.
References __ao2_cleanup(), ao2_bump, ao2_ref, ast_ari_response_error(), ast_ari_response_no_content(), ast_ari_bridges_set_video_source_args::bridge_id, bridge_set_video_source_cb(), ast_ari_bridges_set_video_source_args::channel_id, find_bridge(), find_channel_control(), stasis_app_get_bridge(), and stasis_app_send_command().
Referenced by ast_ari_bridges_set_video_source_cb().
 {
    struct ast_bridge *bridge;
    struct stasis_app_control *control;
    bridge = find_bridge(response, args->bridge_id);
    if (!bridge) {
       return;
    }
    control = find_channel_control(response, args->channel_id);
    if (!control) {
       ao2_ref(bridge, -1);
       return;
    }
    if (stasis_app_get_bridge(control) != bridge) {
       ast_ari_response_error(response, 422,
          "Unprocessable Entity",
          "Channel not in this bridge");
       ao2_ref(bridge, -1);
       ao2_ref(control, -1);
       return;
    }
    stasis_app_send_command(control, bridge_set_video_source_cb,
       ao2_bump(bridge), __ao2_cleanup);
    ao2_ref(bridge, -1);
    ao2_ref(control, -1);
    ast_ari_response_no_content(response);
 }
ast_ari_bridges_start_moh()
void ast_ari_bridges_start_moh (struct ast_variable * headers, struct ast_ari_bridges_start_moh_args * args, struct ast_ari_response * response)
Play music on hold to a bridge or change the MOH class that is playing.
Parameters
headers HTTP headers
args Swagger parameters
[out] response HTTP response
Definition at line 809 of file resource_bridges.c.
References ao2_cleanup, ast_ari_response_alloc_failed(), ast_ari_response_no_content(), ast_channel_cleanup, ast_moh_start(), ast_ari_bridges_start_moh_args::bridge_id, find_bridge(), ast_ari_bridges_start_moh_args::moh_class, NULL, RAII_VAR, and stasis_app_bridge_moh_channel().
Referenced by ast_ari_bridges_start_moh_cb().
 {
    RAII_VAR(struct ast_bridge *, bridge, find_bridge(response, args->bridge_id), ao2_cleanup);
    struct ast_channel *moh_channel;
    const char *moh_class = args->moh_class;
    if (!bridge) {
       /* The response is provided by find_bridge() */
       return;
    }
    moh_channel = stasis_app_bridge_moh_channel(bridge);
    if (!moh_channel) {
       ast_ari_response_alloc_failed(response);
       return;
    }
    ast_moh_start(moh_channel, moh_class, NULL);
    ast_channel_cleanup(moh_channel);
    ast_ari_response_no_content(response);
 }
ast_ari_bridges_start_moh_parse_body()
int ast_ari_bridges_start_moh_parse_body (struct ast_json * body, struct ast_ari_bridges_start_moh_args * args)
Body parsing function for /bridges/{bridgeId}/moh.
Parameters
body The JSON body from which to parse parameters.
[out] args The args structure to parse into.
Return values
zero on success
non-zero on failure
Definition at line 847 of file res_ari_bridges.c.
References ast_json_object_get(), ast_json_string_get(), and ast_ari_bridges_start_moh_args::moh_class.
Referenced by ast_ari_bridges_start_moh_cb().
 {
    struct ast_json *field;
    /* Parse query parameters out of it */
    field = ast_json_object_get(body, "mohClass");
    if (field) {
       args->moh_class = ast_json_string_get(field);
    }
    return 0;
 }
ast_ari_bridges_stop_moh()
void ast_ari_bridges_stop_moh (struct ast_variable * headers, struct ast_ari_bridges_stop_moh_args * args, struct ast_ari_response * response)
Stop playing music on hold to a bridge.
This will only stop music on hold being played via POST bridges/{bridgeId}/moh.
Parameters
headers HTTP headers
args Swagger parameters
[out] response HTTP response
Definition at line 835 of file resource_bridges.c.
References ao2_cleanup, ast_ari_response_error(), ast_ari_response_no_content(), ast_ari_bridges_stop_moh_args::bridge_id, find_bridge(), RAII_VAR, and stasis_app_bridge_moh_stop().
Referenced by ast_ari_bridges_stop_moh_cb().
 {
    RAII_VAR(struct ast_bridge *, bridge, find_bridge(response, args->bridge_id), ao2_cleanup);
    if (!bridge) {
       /* the response is provided by find_bridge() */
       return;
    }
    if (stasis_app_bridge_moh_stop(bridge)) {
       ast_ari_response_error(
          response, 409, "Conflict",
          "Bridge isn't playing music");
       return;
    }
    ast_ari_response_no_content(response);
 }