Asterisk - The Open Source Telephony Project: res_pjsip_header_funcs.c File Reference
res_pjsip_header_funcs.c File Reference
#include "asterisk.h"
#include <pjsip.h>
#include <pjsip_ua.h>
#include "asterisk/res_pjsip.h"
#include "asterisk/res_pjsip_session.h"
#include "asterisk/channel.h"
#include "asterisk/pbx.h"
#include "asterisk/app.h"
#include "asterisk/module.h"
#include "asterisk/utils.h"
Data Structures
struct hdr_list
struct hdr_list_entry
Linked list for accumulating headers.
struct header_data
Data structure used for ast_sip_push_task_wait_serializer.
Functions
static void __reg_module (void)
static void __unreg_module (void)
static int add_header (void *obj)
struct ast_module * AST_MODULE_SELF_SYM (void)
static pjsip_hdr * find_header (struct hdr_list *list, const char *header_name, int header_number)
static int func_read_header (struct ast_channel *chan, const char *function, char *data, char *buf, size_t len)
Implements function 'read' callback.
static int func_write_header (struct ast_channel *chan, const char *cmd, char *data, const char *value)
Implements function 'write' callback.
static int incoming_request (struct ast_sip_session *session, pjsip_rx_data *rdata)
static int insert_headers (pj_pool_t *pool, struct hdr_list *list, pjsip_msg *msg)
static int load_module (void)
static void outgoing_request (struct ast_sip_session *session, pjsip_tx_data *tdata)
static int read_header (void *obj)
static int remove_header (void *obj)
static int unload_module (void)
static int update_header (void *obj)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "PJSIP Header Functions" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_APP_DEPEND, .requires = "res_pjsip,res_pjsip_session", }
static const struct ast_module_info * ast_module_info = &__mod_info
static const struct ast_datastore_info header_datastore
Datastore for saving headers.
static struct ast_sip_session_supplement header_funcs_supplement
static struct ast_custom_function pjsip_header_function
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 624 of file res_pjsip_header_funcs.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 624 of file res_pjsip_header_funcs.c.
add_header()
static int add_header (void * obj) static
Definition at line 315 of file res_pjsip_header_funcs.c.
References ao2_cleanup, ast_debug, AST_LIST_HEAD_INIT_NOLOCK, AST_LIST_INSERT_TAIL, ast_log, AST_LOG_ERROR, ast_sip_session_add_datastore(), ast_sip_session_alloc_datastore(), ast_sip_session_get_datastore(), header_data::channel, hdr_list_entry::hdr, header_data::header_name, header_data::header_value, ast_sip_session::inv_session, hdr_list_entry::nextptr, pool, RAII_VAR, session, ast_sip_channel_pvt::session, and ast_datastore_info::type.
Referenced by func_write_header().
 {
    struct header_data *data = obj;
    struct ast_sip_session *session = data->channel->session;
    pj_pool_t *pool = session->inv_session->dlg->pool;
    pj_str_t pj_header_name;
    pj_str_t pj_header_value;
    struct hdr_list_entry *le;
    struct hdr_list *list;
    RAII_VAR(struct ast_datastore *, datastore,
           ast_sip_session_get_datastore(session, header_datastore.type), ao2_cleanup);
    if (!datastore) {
       if (!(datastore = ast_sip_session_alloc_datastore(&header_datastore,
                                             header_datastore.type))
          || !(datastore->data = pj_pool_alloc(pool, sizeof(struct hdr_list)))
          || ast_sip_session_add_datastore(session, datastore)) {
          ast_log(AST_LOG_ERROR, "Unable to create datastore for header functions.\n");
          return -1;
       }
       AST_LIST_HEAD_INIT_NOLOCK((struct hdr_list *) datastore->data);
    }
    ast_debug(1, "Adding header %s with value %s\n", data->header_name,
            data->header_value);
    pj_cstr(&pj_header_name, data->header_name);
    pj_cstr(&pj_header_value, data->header_value);
    le = pj_pool_zalloc(pool, sizeof(struct hdr_list_entry));
    le->hdr = (pjsip_hdr *) pjsip_generic_string_hdr_create(pool, &pj_header_name,
                                              &pj_header_value);
    list = datastore->data;
    AST_LIST_INSERT_TAIL(list, le, nextptr);
    return 0;
 }
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 624 of file res_pjsip_header_funcs.c.
find_header()
static pjsip_hdr* find_header (struct hdr_list * list, const char * header_name, int header_number) static
Definition at line 222 of file res_pjsip_header_funcs.c.
References AST_LIST_TRAVERSE, ast_strlen_zero, hdr_list_entry::hdr, hdr_list_entry::nextptr, and NULL.
Referenced by read_header(), and update_header().
 {
    struct hdr_list_entry *le;
    pjsip_hdr *hdr = NULL;
    int i = 1;
    if (!list || ast_strlen_zero(header_name) || header_number < 1) {
       return NULL;
    }
    AST_LIST_TRAVERSE(list, le, nextptr) {
       if (pj_stricmp2(&le->hdr->name, header_name) == 0 && i++ == header_number) {
          hdr = le->hdr;
          break;
       }
    }
    return hdr;
 }
func_read_header()
static int func_read_header (struct ast_channel * chan, const char * function, char * data, char * buf, size_t len) static
Implements function 'read' callback.
Valid actions are 'read' and 'remove'.
Definition at line 442 of file res_pjsip_header_funcs.c.
References args, AST_APP_ARG, ast_channel_name(), ast_channel_tech_pvt(), AST_DECLARE_APP_ARGS, ast_log, AST_LOG_ERROR, ast_sip_push_task_wait_serializer(), AST_STANDARD_APP_ARGS, ast_strlen_zero, buf, header_data::buf, header_data::channel, header_data::header_name, header_data::header_number, header_data::header_value, header_data::len, len(), LOG_ERROR, NULL, read_header(), remove_header(), ast_sip_session::serializer, and ast_sip_channel_pvt::session.
 {
    struct ast_sip_channel_pvt *channel = chan ? ast_channel_tech_pvt(chan) : NULL;
    struct header_data header_data;
    int number;
    AST_DECLARE_APP_ARGS(args,
                    AST_APP_ARG(action);
                    AST_APP_ARG(header_name); AST_APP_ARG(header_number););
    AST_STANDARD_APP_ARGS(args, data);
    if (!channel || strncmp(ast_channel_name(chan), "PJSIP/", 6)) {
       ast_log(LOG_ERROR, "This function requires a PJSIP channel.\n");
       return -1;
    }
    if (ast_strlen_zero(args.action)) {
       ast_log(AST_LOG_ERROR, "This function requires an action.\n");
       return -1;
    }
    if (ast_strlen_zero(args.header_name)) {
       ast_log(AST_LOG_ERROR, "This function requires a header name.\n");
       return -1;
    }
    if (!args.header_number) {
       number = 1;
    } else {
       sscanf(args.header_number, "%30d", &number);
       if (number < 1) {
          number = 1;
       }
    }
    header_data.channel = channel;
    header_data.header_name = args.header_name;
    header_data.header_number = number;
    header_data.header_value = NULL;
    header_data.buf = buf;
    header_data.len = len;
    if (!strcasecmp(args.action, "read")) {
       return ast_sip_push_task_wait_serializer(channel->session->serializer,
          read_header, &header_data);
    } else if (!strcasecmp(args.action, "remove")) {
       return ast_sip_push_task_wait_serializer(channel->session->serializer,
          remove_header, &header_data);
    } else {
       ast_log(AST_LOG_ERROR,
             "Unknown action '%s' is not valid, must be 'read' or 'remove'.\n",
             args.action);
       return -1;
    }
 }
func_write_header()
static int func_write_header (struct ast_channel * chan, const char * cmd, char * data, const char * value) static
Implements function 'write' callback.
Valid actions are 'add', 'update' and 'remove'.
Definition at line 501 of file res_pjsip_header_funcs.c.
References add_header(), args, AST_APP_ARG, ast_channel_name(), ast_channel_tech_pvt(), AST_DECLARE_APP_ARGS, ast_log, AST_LOG_ERROR, ast_sip_push_task_wait_serializer(), AST_STANDARD_APP_ARGS, ast_strlen_zero, header_data::buf, header_data::channel, header_data::header_name, header_data::header_number, header_data::header_value, header_data::len, LOG_ERROR, NULL, remove_header(), ast_sip_session::serializer, ast_sip_channel_pvt::session, update_header(), and value.
 {
    struct ast_sip_channel_pvt *channel = chan ? ast_channel_tech_pvt(chan) : NULL;
    struct header_data header_data;
    int header_number;
    AST_DECLARE_APP_ARGS(args,
                    AST_APP_ARG(action);
                    AST_APP_ARG(header_name); AST_APP_ARG(header_number););
    AST_STANDARD_APP_ARGS(args, data);
    if (!channel || strncmp(ast_channel_name(chan), "PJSIP/", 6)) {
       ast_log(LOG_ERROR, "This function requires a PJSIP channel.\n");
       return -1;
    }
    if (ast_strlen_zero(args.action)) {
       ast_log(AST_LOG_ERROR, "This function requires an action.\n");
       return -1;
    }
    if (ast_strlen_zero(args.header_name)) {
       ast_log(AST_LOG_ERROR, "This function requires a header name.\n");
       return -1;
    }
    if (!args.header_number) {
       header_number = 1;
    } else {
       sscanf(args.header_number, "%30d", &header_number);
       if (header_number < 1) {
          header_number = 1;
       }
    }
    header_data.channel = channel;
    header_data.header_name = args.header_name;
    header_data.header_number = header_number;
    header_data.header_value = value;
    header_data.buf = NULL;
    header_data.len = 0;
    if (!strcasecmp(args.action, "add")) {
       return ast_sip_push_task_wait_serializer(channel->session->serializer,
          add_header, &header_data);
    } else if (!strcasecmp(args.action, "update")) {
       return ast_sip_push_task_wait_serializer(channel->session->serializer,
          update_header, &header_data);
    } else if (!strcasecmp(args.action, "remove")) {
       return ast_sip_push_task_wait_serializer(channel->session->serializer,
          remove_header, &header_data);
    } else {
       ast_log(AST_LOG_ERROR,
             "Unknown action '%s' is not valid, must be 'add', 'update', or 'remove'.\n",
             args.action);
       return -1;
    }
 }
incoming_request()
static int incoming_request (struct ast_sip_session * session, pjsip_rx_data * rdata) static
Definition at line 196 of file res_pjsip_header_funcs.c.
References ao2_cleanup, AST_LIST_HEAD_INIT_NOLOCK, ast_log, AST_LOG_ERROR, ast_sip_session_add_datastore(), ast_sip_session_alloc_datastore(), ast_sip_session_get_datastore(), insert_headers(), ast_sip_session::inv_session, pool, RAII_VAR, and ast_datastore_info::type.
 {
    pj_pool_t *pool = session->inv_session->dlg->pool;
    RAII_VAR(struct ast_datastore *, datastore,
           ast_sip_session_get_datastore(session, header_datastore.type), ao2_cleanup);
    if (!datastore) {
       if (!(datastore =
            ast_sip_session_alloc_datastore(&header_datastore, header_datastore.type))
          ||
          !(datastore->data = pj_pool_alloc(pool, sizeof(struct hdr_list))) ||
          ast_sip_session_add_datastore(session, datastore)) {
          ast_log(AST_LOG_ERROR, "Unable to create datastore for header functions.\n");
          return 0;
       }
       AST_LIST_HEAD_INIT_NOLOCK((struct hdr_list *) datastore->data);
    }
    insert_headers(pool, (struct hdr_list *) datastore->data, rdata->msg_info.msg);
    return 0;
 }
insert_headers()
static int insert_headers (pj_pool_t * pool, struct hdr_list * list, pjsip_msg * msg) static
Definition at line 173 of file res_pjsip_header_funcs.c.
References AST_LIST_INSERT_TAIL, hdr_list_entry::hdr, and hdr_list_entry::nextptr.
Referenced by incoming_request().
 {
    pjsip_hdr *hdr = msg->hdr.next;
    struct hdr_list_entry *le;
    while (hdr && hdr != &msg->hdr) {
       le = pj_pool_zalloc(pool, sizeof(struct hdr_list_entry));
       le->hdr = pjsip_hdr_clone(pool, hdr);
       AST_LIST_INSERT_TAIL(list, le, nextptr);
       hdr = hdr->next;
    }
    return 0;
 }
load_module()
static int load_module (void) static
Definition at line 603 of file res_pjsip_header_funcs.c.
References ast_custom_function_register, AST_MODULE_LOAD_SUCCESS, and ast_sip_session_register_supplement.
Referenced by unload_module().
 {
    ast_sip_session_register_supplement(&header_funcs_supplement);
    ast_custom_function_register(&pjsip_header_function);
    return AST_MODULE_LOAD_SUCCESS;
 }
outgoing_request()
static void outgoing_request (struct ast_sip_session * session, pjsip_tx_data * tdata) static
Definition at line 576 of file res_pjsip_header_funcs.c.
References ao2_cleanup, AST_LIST_TRAVERSE, ast_sip_session_get_datastore(), ast_sip_session_remove_datastore(), hdr_list_entry::hdr, ast_sip_session::inv_session, hdr_list_entry::nextptr, pool, RAII_VAR, and ast_datastore_info::type.
 {
    pj_pool_t *pool = session->inv_session->dlg->pool;
    struct hdr_list *list;
    struct hdr_list_entry *le;
    RAII_VAR(struct ast_datastore *, datastore,
           ast_sip_session_get_datastore(session, header_datastore.type), ao2_cleanup);
    if (!datastore || !datastore->data ||
       (session->inv_session->state >= PJSIP_INV_STATE_CONFIRMED)) {
       return;
    }
    list = datastore->data;
    AST_LIST_TRAVERSE(list, le, nextptr) {
       pjsip_msg_add_hdr(tdata->msg, (pjsip_hdr *) pjsip_hdr_clone(pool, le->hdr));
    }
    ast_sip_session_remove_datastore(session, datastore->uid);
 }
read_header()
static int read_header (void * obj) static
Definition at line 254 of file res_pjsip_header_funcs.c.
References ao2_cleanup, ast_alloca, ast_copy_string(), ast_debug, ast_log, AST_LOG_ERROR, ast_sip_session_get_datastore(), ast_strip(), header_data::buf, header_data::channel, find_header(), hdr_list_entry::hdr, header_data::header_name, header_data::header_number, header_data::len, NULL, RAII_VAR, ast_sip_channel_pvt::session, and ast_datastore_info::type.
Referenced by func_read_header().
 {
    struct header_data *data = obj;
    pjsip_hdr *hdr = NULL;
    char *pj_hdr_string;
    size_t pj_hdr_string_len;
    char *p;
    size_t plen;
    RAII_VAR(struct ast_datastore *, datastore,
           ast_sip_session_get_datastore(data->channel->session, header_datastore.type),
           ao2_cleanup);
    if (!datastore || !datastore->data) {
       ast_debug(1, "There was no datastore from which to read headers.\n");
       return -1;
    }
    hdr = find_header((struct hdr_list *) datastore->data, data->header_name,
                  data->header_number);
    if (!hdr) {
       ast_debug(1, "There was no header named %s.\n", data->header_name);
       return -1;
    }
    pj_hdr_string = ast_alloca(data->len);
    pj_hdr_string_len = pjsip_hdr_print_on(hdr, pj_hdr_string, data->len);
    pj_hdr_string[pj_hdr_string_len] = '\0';
    p = strchr(pj_hdr_string, ':');
    if (!p) {
       ast_log(AST_LOG_ERROR,
             "A malformed header was returned from pjsip_hdr_print_on.\n");
       return -1;
    }
    ++p;
    p = ast_strip(p);
    plen = strlen(p);
    if (plen + 1 > data->len) {
       ast_log(AST_LOG_ERROR,
             "Buffer isn't big enough to hold header value.  %zu > %zu\n", plen + 1,
             data->len);
       return -1;
    }
    ast_copy_string(data->buf, p, data->len);
    return 0;
 }
remove_header()
static int remove_header (void * obj) static
Definition at line 398 of file res_pjsip_header_funcs.c.
References ao2_cleanup, AST_LIST_REMOVE_CURRENT, AST_LIST_TRAVERSE_SAFE_BEGIN, AST_LIST_TRAVERSE_SAFE_END, ast_log, AST_LOG_ERROR, ast_sip_session_get_datastore(), header_data::buf, header_data::channel, hdr_list_entry::hdr, header_data::header_name, header_data::len, len(), hdr_list_entry::nextptr, RAII_VAR, ast_sip_channel_pvt::session, and ast_datastore_info::type.
Referenced by func_read_header(), and func_write_header().
 {
    struct header_data *data = obj;
    size_t len = strlen(data->header_name);
    struct hdr_list *list;
    struct hdr_list_entry *le;
    int removed_count = 0;
    RAII_VAR(struct ast_datastore *, datastore,
           ast_sip_session_get_datastore(data->channel->session, header_datastore.type),
           ao2_cleanup);
    if (!datastore || !datastore->data) {
       ast_log(AST_LOG_ERROR, "No headers had been previously added to this session.\n");
       return -1;
    }
    list = datastore->data;
    AST_LIST_TRAVERSE_SAFE_BEGIN(list, le, nextptr) {
       if (data->header_name[len - 1] == '*') {
          if (pj_strnicmp2(&le->hdr->name, data->header_name, len - 1) == 0) {
             AST_LIST_REMOVE_CURRENT(nextptr);
             removed_count++;
          }
       } else {
          if (pj_stricmp2(&le->hdr->name, data->header_name) == 0) {
             AST_LIST_REMOVE_CURRENT(nextptr);
             removed_count++;
          }
       }
    }
    AST_LIST_TRAVERSE_SAFE_END;
    if (data->buf && data->len) {
       snprintf(data->buf, data->len, "%d", removed_count);
    }
    return 0;
 }
unload_module()
static int unload_module (void) static
Definition at line 611 of file res_pjsip_header_funcs.c.
References ast_custom_function_unregister(), AST_MODFLAG_LOAD_ORDER, AST_MODPRI_APP_DEPEND, AST_MODULE_INFO(), AST_MODULE_SUPPORT_CORE, ast_sip_session_unregister_supplement(), ASTERISK_GPL_KEY, and load_module().
 {
    ast_custom_function_unregister(&pjsip_header_function);
    ast_sip_session_unregister_supplement(&header_funcs_supplement);
    return 0;
 }
update_header()
static int update_header (void * obj) static
Definition at line 364 of file res_pjsip_header_funcs.c.
References ao2_cleanup, ast_log, AST_LOG_ERROR, ast_sip_session_get_datastore(), header_data::channel, find_header(), hdr_list_entry::hdr, header_data::header_name, header_data::header_number, header_data::header_value, NULL, RAII_VAR, ast_sip_channel_pvt::session, and ast_datastore_info::type.
Referenced by func_write_header().
 {
    struct header_data *data = obj;
    pjsip_hdr *hdr = NULL;
    RAII_VAR(struct ast_datastore *, datastore,
           ast_sip_session_get_datastore(data->channel->session, header_datastore.type),
           ao2_cleanup);
    if (!datastore || !datastore->data) {
       ast_log(AST_LOG_ERROR, "No headers had been previously added to this session.\n");
       return -1;
    }
    hdr = find_header((struct hdr_list *) datastore->data, data->header_name,
                  data->header_number);
    if (!hdr) {
       ast_log(AST_LOG_ERROR, "There was no header named %s.\n", data->header_name);
       return -1;
    }
    pj_strcpy2(&((pjsip_generic_string_hdr *) hdr)->hvalue, data->header_value);
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "PJSIP Header Functions" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_APP_DEPEND, .requires = "res_pjsip,res_pjsip_session", } static
Definition at line 624 of file res_pjsip_header_funcs.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 624 of file res_pjsip_header_funcs.c.
header_datastore
const struct ast_datastore_info header_datastore static
Initial value:
= {
   .type = "header_datastore",
}
Datastore for saving headers.
Definition at line 152 of file res_pjsip_header_funcs.c.
header_funcs_supplement
struct ast_sip_session_supplement header_funcs_supplement static
Definition at line 596 of file res_pjsip_header_funcs.c.
pjsip_header_function
struct ast_custom_function pjsip_header_function static
Initial value:
= {
   .name = "PJSIP_HEADER",
   .read = func_read_header,
   .write = func_write_header,
}
Definition at line 558 of file res_pjsip_header_funcs.c.