Asterisk - The Open Source Telephony Project: func_base64.c File Reference
func_base64.c File Reference
Module: Dial plan functions
Use the base64 as functions.
#include "asterisk.h"
#include "asterisk/module.h"
#include "asterisk/pbx.h"
#include "asterisk/utils.h"
#include "asterisk/strings.h"
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int base64_buf_helper (struct ast_channel *chan, const char *cmd, char *data, char *buf, size_t len)
static int base64_helper (struct ast_channel *chan, const char *cmd, char *data, char *buf, struct ast_str **str, ssize_t len)
static int base64_str_helper (struct ast_channel *chan, const char *cmd, char *data, struct ast_str **buf, ssize_t len)
static int load_module (void)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "base64 encode/decode dialplan functions" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, }
static const struct ast_module_info * ast_module_info = &__mod_info
static struct ast_custom_function base64_decode_function
static struct ast_custom_function base64_encode_function
Detailed Description
Use the base64 as functions.
Definition in file func_base64.c.
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 157 of file func_base64.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 157 of file func_base64.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 157 of file func_base64.c.
base64_buf_helper()
static int base64_buf_helper (struct ast_channel * chan, const char * cmd, char * data, char * buf, size_t len) static
Definition at line 121 of file func_base64.c.
References base64_helper(), and NULL.
 {
    return base64_helper(chan, cmd, data, buf, NULL, len);
 }
base64_helper()
static int base64_helper (struct ast_channel * chan, const char * cmd, char * data, char * buf, struct ast_str ** str, ssize_t len) static
Definition at line 75 of file func_base64.c.
References ast_base64decode(), ast_base64encode(), ast_log, ast_str_buffer(), ast_str_make_space, ast_str_size(), ast_str_strlen(), ast_str_update(), ast_strlen_zero, and LOG_WARNING.
Referenced by base64_buf_helper(), and base64_str_helper().
 {
    if (ast_strlen_zero(data)) {
       ast_log(LOG_WARNING, "Syntax: %s(<data>) - missing argument!\n", cmd);
       return -1;
    }
    if (cmd[7] == 'E') {
       if (buf) {
          ast_base64encode(buf, (unsigned char *) data, strlen(data), len);
       } else {
          if (len >= 0) {
             ast_str_make_space(str, len ? len : ast_str_strlen(*str) + strlen(data) * 4 / 3 + 2);
          }
          ast_base64encode(ast_str_buffer(*str) + ast_str_strlen(*str), (unsigned char *) data, strlen(data), ast_str_size(*str) - ast_str_strlen(*str));
          ast_str_update(*str);
       }
    } else {
       int decoded_len;
       if (buf) {
          decoded_len = ast_base64decode((unsigned char *) buf, data, len);
          /* add a terminating null at the end of buf, or at the
           * end of our decoded string, which ever is less */
          buf[decoded_len <= (len - 1) ? decoded_len : len - 1] = '\0';
       } else {
          if (len >= 0) {
             ast_str_make_space(str, len ? len : ast_str_strlen(*str) + strlen(data) * 3 / 4 + 2);
          }
          decoded_len = ast_base64decode((unsigned char *) ast_str_buffer(*str) + ast_str_strlen(*str), data, ast_str_size(*str) - ast_str_strlen(*str));
          if (len)
             /* add a terminating null at the end of our
              * buffer, or at the end of our decoded string,
              * which ever is less */
             ast_str_buffer(*str)[decoded_len <= (len - 1) ? decoded_len : len - 1] = '\0';
          else
             /* space for the null is allocated above */
             ast_str_buffer(*str)[decoded_len] = '\0';
          ast_str_update(*str);
       }
    }
    return 0;
 }
base64_str_helper()
static int base64_str_helper (struct ast_channel * chan, const char * cmd, char * data, struct ast_str ** buf, ssize_t len) static
Definition at line 127 of file func_base64.c.
References base64_helper(), and NULL.
 {
    return base64_helper(chan, cmd, data, NULL, buf, len);
 }
load_module()
static int load_module (void) static
Definition at line 151 of file func_base64.c.
References ast_custom_function_register.
 {
    return ast_custom_function_register(&base64_encode_function) |
       ast_custom_function_register(&base64_decode_function);
 }
unload_module()
static int unload_module (void) static
Definition at line 145 of file func_base64.c.
References ast_custom_function_unregister().
 {
    return ast_custom_function_unregister(&base64_encode_function) |
       ast_custom_function_unregister(&base64_decode_function);
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "base64 encode/decode dialplan functions" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, } static
Definition at line 157 of file func_base64.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 157 of file func_base64.c.
base64_decode_function
struct ast_custom_function base64_decode_function static
Initial value:
= {
   .name = "BASE64_DECODE",
   .read = base64_buf_helper,
   .read2 = base64_str_helper,
}
Definition at line 139 of file func_base64.c.
base64_encode_function
struct ast_custom_function base64_encode_function static
Initial value:
= {
   .name = "BASE64_ENCODE",
   .read = base64_buf_helper,
   .read2 = base64_str_helper,
}
Definition at line 133 of file func_base64.c.