Asterisk - The Open Source Telephony Project: app_playtones.c File Reference
app_playtones.c File Reference
Dial plan applications
Playtones application.
#include "asterisk.h"
#include "asterisk/module.h"
#include "asterisk/pbx.h"
#include "asterisk/channel.h"
#include "asterisk/indications.h"
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int handle_playtones (struct ast_channel *chan, const char *data)
static int handle_stopplaytones (struct ast_channel *chan, const char *data)
static int load_module (void)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Playtones Application" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, }
static const struct ast_module_info * ast_module_info = &__mod_info
static const char playtones_app [] = "PlayTones"
static const char stopplaytones_app [] = "StopPlayTones"
Detailed Description
Playtones application.
Author
Russell Bryant russe.nosp@m.ll@d.nosp@m.igium.nosp@m..com
Definition in file app_playtones.c.
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 131 of file app_playtones.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 131 of file app_playtones.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 131 of file app_playtones.c.
handle_playtones()
static int handle_playtones (struct ast_channel * chan, const char * data) static
Definition at line 77 of file app_playtones.c.
References ast_channel_zone(), ast_get_indication_tone(), ast_log, ast_playtones_start(), ast_strlen_zero, ast_tone_zone_sound_unref(), ast_tone_zone_sound::data, LOG_NOTICE, and str.
Referenced by load_module().
 {
    struct ast_tone_zone_sound *ts;
    int res;
    const char *str = data;
    if (ast_strlen_zero(str)) {
       ast_log(LOG_NOTICE,"Nothing to play\n");
       return -1;
    }
    ts = ast_get_indication_tone(ast_channel_zone(chan), str);
    if (ts) {
       res = ast_playtones_start(chan, 0, ts->data, 0);
       ts = ast_tone_zone_sound_unref(ts);
    } else {
       res = ast_playtones_start(chan, 0, str, 0);
    }
    if (res) {
       ast_log(LOG_NOTICE, "Unable to start playtones\n");
    }
    return res;
 }
handle_stopplaytones()
static int handle_stopplaytones (struct ast_channel * chan, const char * data) static
Definition at line 104 of file app_playtones.c.
References ast_playtones_stop().
Referenced by load_module().
 {
    ast_playtones_stop(chan);
    return 0;
 }
load_module()
static int load_module (void) static
Definition at line 121 of file app_playtones.c.
References AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, ast_register_application_xml, handle_playtones(), handle_stopplaytones(), playtones_app, and stopplaytones_app.
 {
    int res;
    res = ast_register_application_xml(playtones_app, handle_playtones);
    res |= ast_register_application_xml(stopplaytones_app, handle_stopplaytones);
    return res ? AST_MODULE_LOAD_DECLINE : AST_MODULE_LOAD_SUCCESS;
 }
unload_module()
static int unload_module (void) static
Definition at line 111 of file app_playtones.c.
References ast_unregister_application(), playtones_app, and stopplaytones_app.
 {
    int res;
    res = ast_unregister_application(playtones_app);
    res |= ast_unregister_application(stopplaytones_app);
    return res;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Playtones Application" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, } static
Definition at line 131 of file app_playtones.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 131 of file app_playtones.c.
playtones_app
const char playtones_app[] = "PlayTones" static
Definition at line 39 of file app_playtones.c.
Referenced by load_module(), and unload_module().
stopplaytones_app
const char stopplaytones_app[] = "StopPlayTones" static
Definition at line 40 of file app_playtones.c.
Referenced by load_module(), and unload_module().