Asterisk - The Open Source Telephony Project: res_config_mysql.c File Reference
res_config_mysql.c File Reference
MySQL CDR backend.
#include "asterisk.h"
#include <sys/stat.h>
#include <mysql/mysql.h>
#include <mysql/errmsg.h>
#include "asterisk/channel.h"
#include "asterisk/logger.h"
#include "asterisk/config.h"
#include "asterisk/module.h"
#include "asterisk/lock.h"
#include "asterisk/options.h"
#include "asterisk/cli.h"
#include "asterisk/utils.h"
#include "asterisk/threadstorage.h"
#include "asterisk/strings.h"
Data Structures
struct columns
struct databases
struct tables::mysql_columns
struct mysql_conn
struct mysql_tables
struct tables
Macros
#define ESCAPE_STRING(buf, var)
#define IS_SQL_LIKE_CLAUSE(x) ((x) && ast_ends_with(x, " LIKE"))
#define READHANDLE 0
#define release_database(a) ast_mutex_unlock(&(a)->lock)
#define RES_CONFIG_MYSQL_CONF "res_config_mysql.conf"
#define RES_CONFIG_MYSQL_CONF_OLD "res_mysql.conf"
#define WRITEHANDLE 1
Enumerations
enum requirements { RQ_WARN, RQ_CREATECLOSE, RQ_CREATECHAR }
Functions
static void __init_find_buf (void)
static void __init_modify2_buf (void)
static void __init_modify3_buf (void)
static void __init_modify_buf (void)
static void __init_scratch2_buf (void)
static void __init_scratch_buf (void)
static void __init_sql2_buf (void)
static void __init_sql_buf (void)
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static struct ast_config * config_mysql (const char *database, const char *table, const char *file, struct ast_config *cfg, struct ast_flags config_flags, const char *unused, const char *who_asked)
static char * decode_chunk (char *chunk)
static int destroy_mysql (const char *database, const char *table, const char *keyfield, const char *lookup, const struct ast_variable *rt_fields)
static void destroy_table (struct tables *table)
static struct columns * find_column (struct tables *table, const char *colname)
static struct mysql_conn * find_database (const char *database, int for_write)
static struct tables * find_table (const char *database, const char *tablename)
static char * handle_cli_realtime_mysql_cache (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static char * handle_cli_realtime_mysql_status (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static int load_module (void)
static int load_mysql_config (struct ast_config *config, const char *category, struct mysql_conn *conn)
static int mysql_reconnect (struct mysql_conn *conn)
static int parse_config (int reload)
static struct ast_config * realtime_multi_mysql (const char *database, const char *table, const struct ast_variable *rt_fields)
static struct ast_variable * realtime_mysql (const char *database, const char *table, const struct ast_variable *rt_fields)
static void release_table (struct tables *table)
static int reload (void)
static int require_mysql (const char *database, const char *tablename, va_list ap)
static int store_mysql (const char *database, const char *table, const struct ast_variable *rt_fields)
static int unload_module (void)
static int unload_mysql (const char *database, const char *tablename)
static int update2_mysql (const char *database, const char *tablename, const struct ast_variable *lookup_fields, const struct ast_variable *update_fields)
static int update_mysql (const char *database, const char *tablename, const char *keyfield, const char *lookup, const struct ast_variable *rt_fields)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "MySQL RealTime Configuration Driver" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_EXTENDED, .load = load_module, .unload = unload_module, .reload = reload, .load_pri = AST_MODPRI_REALTIME_DRIVER, .requires = "extconfig", }
static const struct ast_module_info * ast_module_info = &__mod_info
static struct ast_cli_entry cli_realtime_mysql_status []
static struct databases databases = { .first = NULL, .last = NULL, .lock = { PTHREAD_RWLOCK_INITIALIZER , NULL, {1, 0} } , }
static char * ESCAPE_CLAUSE = " ESCAPE '\\\\'"
static struct ast_threadstorage find_buf = { .once = PTHREAD_ONCE_INIT , .key_init = __init_find_buf , .custom_init = NULL , }
static struct ast_threadstorage modify2_buf = { .once = PTHREAD_ONCE_INIT , .key_init = __init_modify2_buf , .custom_init = NULL , }
static struct ast_threadstorage modify3_buf = { .once = PTHREAD_ONCE_INIT , .key_init = __init_modify3_buf , .custom_init = NULL , }
static struct ast_threadstorage modify_buf = { .once = PTHREAD_ONCE_INIT , .key_init = __init_modify_buf , .custom_init = NULL , }
static struct ast_config_engine mysql_engine
static struct mysql_tables mysql_tables = { .first = NULL, .last = NULL, .lock = { PTHREAD_RECURSIVE_MUTEX_INITIALIZER_NP , NULL, {1, 0} } , }
static struct ast_threadstorage scratch2_buf = { .once = PTHREAD_ONCE_INIT , .key_init = __init_scratch2_buf , .custom_init = NULL , }
static struct ast_threadstorage scratch_buf = { .once = PTHREAD_ONCE_INIT , .key_init = __init_scratch_buf , .custom_init = NULL , }
static struct ast_threadstorage sql2_buf = { .once = PTHREAD_ONCE_INIT , .key_init = __init_sql2_buf , .custom_init = NULL , }
static struct ast_threadstorage sql_buf = { .once = PTHREAD_ONCE_INIT , .key_init = __init_sql_buf , .custom_init = NULL , }
Detailed Description
MySQL CDR backend.
Definition in file res_config_mysql.c.
Macro Definition Documentation
ESCAPE_STRING
#define ESCAPE_STRING (buf, var)
Definition at line 54 of file res_config_mysql.c.
Referenced by destroy_mysql(), realtime_multi_mysql(), realtime_mysql(), store_mysql(), update2_mysql(), and update_mysql().
IS_SQL_LIKE_CLAUSE
#define IS_SQL_LIKE_CLAUSE (x) ((x) && ast_ends_with(x, " LIKE"))
Definition at line 305 of file res_config_mysql.c.
Referenced by realtime_multi_mysql(), and realtime_mysql().
READHANDLE
#define READHANDLE 0
Definition at line 51 of file res_config_mysql.c.
release_database
#define release_database (a) ast_mutex_unlock(&(a)->lock)
Definition at line 162 of file res_config_mysql.c.
Referenced by config_mysql(), destroy_mysql(), find_table(), realtime_multi_mysql(), realtime_mysql(), store_mysql(), update2_mysql(), and update_mysql().
RES_CONFIG_MYSQL_CONF
#define RES_CONFIG_MYSQL_CONF "res_config_mysql.conf"
Definition at line 49 of file res_config_mysql.c.
Referenced by config_mysql(), and parse_config().
RES_CONFIG_MYSQL_CONF_OLD
#define RES_CONFIG_MYSQL_CONF_OLD "res_mysql.conf"
Definition at line 50 of file res_config_mysql.c.
Referenced by parse_config().
WRITEHANDLE
#define WRITEHANDLE 1
Definition at line 52 of file res_config_mysql.c.
Enumeration Type Documentation
requirements
enum requirements
Enumerator
RQ_WARN
RQ_CREATECLOSE
RQ_CREATECHAR
Definition at line 81 of file res_config_mysql.c.
 { RQ_WARN, RQ_CREATECLOSE, RQ_CREATECHAR };
Function Documentation
__init_find_buf()
static void __init_find_buf (void) static
Definition at line 74 of file res_config_mysql.c.
 { RQ_WARN, RQ_CREATECLOSE, RQ_CREATECHAR };
__init_modify2_buf()
static void __init_modify2_buf (void) static
Definition at line 78 of file res_config_mysql.c.
 { RQ_WARN, RQ_CREATECLOSE, RQ_CREATECHAR };
__init_modify3_buf()
static void __init_modify3_buf (void) static
Definition at line 79 of file res_config_mysql.c.
 { RQ_WARN, RQ_CREATECLOSE, RQ_CREATECHAR };
__init_modify_buf()
static void __init_modify_buf (void) static
Definition at line 77 of file res_config_mysql.c.
 { RQ_WARN, RQ_CREATECLOSE, RQ_CREATECHAR };
__init_scratch2_buf()
static void __init_scratch2_buf (void) static
Definition at line 76 of file res_config_mysql.c.
 { RQ_WARN, RQ_CREATECLOSE, RQ_CREATECHAR };
__init_scratch_buf()
static void __init_scratch_buf (void) static
Definition at line 75 of file res_config_mysql.c.
 { RQ_WARN, RQ_CREATECLOSE, RQ_CREATECHAR };
__init_sql2_buf()
static void __init_sql2_buf (void) static
Definition at line 73 of file res_config_mysql.c.
 { RQ_WARN, RQ_CREATECLOSE, RQ_CREATECHAR };
__init_sql_buf()
static void __init_sql_buf (void) static
Definition at line 72 of file res_config_mysql.c.
 { RQ_WARN, RQ_CREATECLOSE, RQ_CREATECHAR };
__reg_module()
static void __reg_module (void) static
Definition at line 1563 of file res_config_mysql.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 1563 of file res_config_mysql.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 1563 of file res_config_mysql.c.
config_mysql()
static struct ast_config* config_mysql (const char * database, const char * table, const char * file, struct ast_config * cfg, struct ast_flags config_flags, const char * unused, const char * who_asked) static
Definition at line 876 of file res_config_mysql.c.
References ast_category_append(), ast_category_new_dynamic, ast_clear_flag, ast_config_internal_load(), ast_debug, ast_log, ast_str_buffer(), ast_str_set(), ast_str_strlen(), ast_str_thread_get(), ast_variable_append(), ast_variable_new, CONFIG_FLAG_FILEUNCHANGED, find_database(), last, LOG_WARNING, mysql_reconnect(), NULL, release_database, RES_CONFIG_MYSQL_CONF, result, and sql_buf.
 {
    struct mysql_conn *dbh;
    MYSQL_RES *result;
    MYSQL_ROW row;
    uint64_t num_rows;
    struct ast_variable *new_v;
    struct ast_category *cur_cat = NULL;
    struct ast_str *sql = ast_str_thread_get(&sql_buf, 200);
    char last[80] = "";
    int last_cat_metric = 0;
    ast_clear_flag(&config_flags, CONFIG_FLAG_FILEUNCHANGED);
    if (!file || !strcmp(file, RES_CONFIG_MYSQL_CONF)) {
       ast_log(LOG_WARNING, "MySQL RealTime: Cannot configure myself.\n");
       return NULL;
    }
    if (!(dbh = find_database(database, 0))) {
       ast_log(LOG_WARNING, "MySQL RealTime: Invalid database specified: '%s' (check res_mysql.conf)\n", database);
       return NULL;
    }
    ast_str_set(&sql, 0, "SELECT category, var_name, var_val, cat_metric FROM %s WHERE filename='%s' and commented=0 ORDER BY filename, category, cat_metric desc, var_metric asc, var_name, var_val, id", table, file);
    ast_debug(1, "MySQL RealTime: Static SQL: %s\n", ast_str_buffer(sql));
    /* We now have our complete statement; Lets connect to the server and execute it. */
    if (!mysql_reconnect(dbh)) {
       return NULL;
    }
    if (mysql_real_query(&dbh->handle, ast_str_buffer(sql), ast_str_strlen(sql))) {
       ast_log(LOG_WARNING, "MySQL RealTime: Failed to query database. Check debug for more info.\n");
       ast_debug(1, "MySQL RealTime: Query: %s\n", ast_str_buffer(sql));
       ast_debug(1, "MySQL RealTime: Query Failed because: %s\n", mysql_error(&dbh->handle));
       release_database(dbh);
       return NULL;
    }
    if ((result = mysql_store_result(&dbh->handle))) {
       num_rows = mysql_num_rows(result);
       ast_debug(1, "MySQL RealTime: Found %" PRIu64 " rows.\n", num_rows);
       /* There might exist a better way to access the column names other than counting,
        * but I believe that would require another loop that we don't need. */
       while ((row = mysql_fetch_row(result))) {
          if (!strcmp(row[1], "#include")) {
             if (!ast_config_internal_load(row[2], cfg, config_flags, "", who_asked)) {
                mysql_free_result(result);
                release_database(dbh);
                return NULL;
             }
             continue;
          }
          if (strcmp(last, row[0]) || last_cat_metric != atoi(row[3])) {
             cur_cat = ast_category_new_dynamic(row[0]);
             if (!cur_cat) {
                break;
             }
             strcpy(last, row[0]);
             last_cat_metric = atoi(row[3]);
             ast_category_append(cfg, cur_cat);
          }
          new_v = ast_variable_new(row[1], row[2], "");
          if (cur_cat)
             ast_variable_append(cur_cat, new_v);
       }
    } else {
       ast_log(LOG_WARNING, "MySQL RealTime: Could not find config '%s' in database.\n", file);
    }
    mysql_free_result(result);
    release_database(dbh);
    return cfg;
 }
decode_chunk()
static char* decode_chunk (char * chunk) static
Definition at line 293 of file res_config_mysql.c.
Referenced by realtime_multi_mysql(), and realtime_mysql().
 {
    char *orig = chunk;
    for (; *chunk; chunk++) {
       if (*chunk == '^' && strchr("0123456789ABCDEFabcdef", chunk[1]) && strchr("0123456789ABCDEFabcdef", chunk[2])) {
          sscanf(chunk + 1, "%02hhX", chunk);
          memmove(chunk + 1, chunk + 3, strlen(chunk + 3) + 1);
       }
    }
    return orig;
 }
destroy_mysql()
static int destroy_mysql (const char * database, const char * table, const char * keyfield, const char * lookup, const struct ast_variable * rt_fields) static
Definition at line 810 of file res_config_mysql.c.
References ast_debug, ast_log, ast_str_append(), ast_str_buffer(), ast_str_set(), ast_str_strlen(), ast_str_thread_get(), ast_strlen_zero, buf, ESCAPE_STRING, find_database(), LOG_WARNING, mysql_reconnect(), ast_variable::name, ast_variable::next, release_database, scratch_buf, sql_buf, and ast_variable::value.
 {
    struct mysql_conn *dbh;
    uint64_t numrows;
    struct ast_str *sql = ast_str_thread_get(&sql_buf, 16);
    struct ast_str *buf = ast_str_thread_get(&scratch_buf, 16);
    const struct ast_variable *field;
    if (!(dbh = find_database(database, 1))) {
       ast_log(LOG_WARNING, "MySQL RealTime: Invalid database specified: '%s' (check res_mysql.conf)\n", database);
       return -1;
    }
    if (!table) {
       ast_log(LOG_WARNING, "MySQL RealTime: No table specified.\n");
       release_database(dbh);
       return -1;
    }
    /* Get the first parameter and first value in our list of passed paramater/value pairs */
    /* newparam = va_arg(ap, const char *);
    newval = va_arg(ap, const char *);*/
    if (ast_strlen_zero(keyfield) || ast_strlen_zero(lookup))  {
       ast_log(LOG_WARNING, "MySQL RealTime: Realtime destroying requires at least 1 parameter and 1 value to search on.\n");
       release_database(dbh);
       return -1;
    }
    /* Must connect to the server before anything else, as the escape function requires the mysql handle. */
    if (!mysql_reconnect(dbh)) {
       release_database(dbh);
       return -1;
    }
    /* Create the first part of the query using the first parameter/value pairs we just extracted
       If there is only 1 set, then we have our query. Otherwise, loop thru the list and concat */
    ESCAPE_STRING(buf, lookup);
    ast_str_set(&sql, 0, "DELETE FROM %s WHERE `%s` = '%s'", table, keyfield, ast_str_buffer(buf));
    for (field = rt_fields; field; field = field->next) {
       ESCAPE_STRING(buf, field->value);
       ast_str_append(&sql, 0, " AND `%s` = '%s'", field->name, ast_str_buffer(buf));
    }
    ast_debug(1, "MySQL RealTime: Delete SQL: %s\n", ast_str_buffer(sql));
    /* Execution. */
    if (mysql_real_query(&dbh->handle, ast_str_buffer(sql), ast_str_strlen(sql))) {
       ast_log(LOG_WARNING, "MySQL RealTime: Failed to delete from database: %s\n", mysql_error(&dbh->handle));
       release_database(dbh);
       return -1;
    }
    numrows = mysql_affected_rows(&dbh->handle);
    release_database(dbh);
    ast_debug(1, "MySQL RealTime: Deleted %" PRIu64 " rows on table: %s\n", numrows, table);
    /* From http://dev.mysql.com/doc/mysql/en/mysql-affected-rows.html
     * An integer greater than zero indicates the number of rows affected
     * Zero indicates that no records were updated
     * -1 indicates that the query returned an error (although, if the query failed, it should have been caught above.)
    */
    return (int)numrows;
 }
destroy_table()
static void destroy_table (struct tables * table) static
Definition at line 164 of file res_config_mysql.c.
References ast_free, AST_LIST_REMOVE_HEAD, ast_mutex_destroy, ast_mutex_lock, ast_mutex_unlock, tables::columns, columns::list, and tables::lock.
Referenced by find_table(), unload_module(), and unload_mysql().
 {
    struct columns *column;
    ast_mutex_lock(&table->lock);
    while ((column = AST_LIST_REMOVE_HEAD(&table->columns, list))) {
       ast_free(column);
    }
    ast_mutex_unlock(&table->lock);
    ast_mutex_destroy(&table->lock);
    ast_free(table);
 }
find_column()
static struct columns* find_column (struct tables * table, const char * colname) static
Definition at line 280 of file res_config_mysql.c.
References AST_LIST_TRAVERSE, tables::columns, columns::list, and columns::name.
Referenced by update2_mysql(), and update_mysql().
 {
    struct columns *column;
    AST_LIST_TRAVERSE(&table->columns, column, list) {
       if (strcmp(column->name, colname) == 0) {
          break;
       }
    }
    return column;
 }
find_database()
static struct mysql_conn* find_database (const char * database, int for_write) static
Definition at line 132 of file res_config_mysql.c.
References ast_alloca, ast_mutex_lock, AST_RWLIST_RDLOCK, AST_RWLIST_TRAVERSE, AST_RWLIST_UNLOCK, and ast_strdupa.
Referenced by config_mysql(), destroy_mysql(), find_table(), realtime_multi_mysql(), realtime_mysql(), store_mysql(), update2_mysql(), and update_mysql().
 {
    char *whichdb;
    const char *ptr;
    struct mysql_conn *cur;
    if ((ptr = strchr(database, '/'))) {
       /* Multiple databases encoded within string */
       if (for_write) {
          whichdb = ast_strdupa(ptr + 1);
       } else {
          whichdb = ast_alloca(ptr - database + 1);
          strncpy(whichdb, database, ptr - database);
          whichdb[ptr - database] = '\0';
       }
    } else {
       whichdb = ast_strdupa(database);
    }
    AST_RWLIST_RDLOCK(&databases);
    AST_RWLIST_TRAVERSE(&databases, cur, list) {
       if (!strcmp(cur->unique_name, whichdb)) {
          ast_mutex_lock(&cur->lock);
          break;
       }
    }
    AST_RWLIST_UNLOCK(&databases);
    return cur;
 }
find_table()
static struct tables* find_table (const char * database, const char * tablename) static
Definition at line 176 of file res_config_mysql.c.
References ast_calloc, AST_LIST_HEAD_INIT_NOLOCK, AST_LIST_INSERT_TAIL, AST_LIST_LOCK, AST_LIST_TRAVERSE, AST_LIST_UNLOCK, ast_log, ast_mutex_init, ast_mutex_lock, ast_str_buffer(), ast_str_set(), ast_str_strlen(), ast_str_thread_get(), ast_verb, tables::columns, tables::database, destroy_table(), columns::dflt, find_buf, find_database(), columns::len, tables::lock, LOG_ERROR, mysql_reconnect(), columns::name, tables::name, NULL, columns::null, release_database, result, table, and columns::type.
Referenced by handle_cli_realtime_mysql_cache(), require_mysql(), update2_mysql(), and update_mysql().
 {
    struct columns *column;
    struct tables *table;
    struct ast_str *sql = ast_str_thread_get(&find_buf, 30);
    char *fname, *ftype, *flen, *fdflt, *fnull;
    struct mysql_conn *dbh;
    MYSQL_RES *result;
    MYSQL_ROW row;
    if (!(dbh = find_database(database, 1))) {
       return NULL;
    }
    AST_LIST_LOCK(&mysql_tables);
    AST_LIST_TRAVERSE(&mysql_tables, table, list) {
       if (!strcasecmp(table->name, tablename)) {
          ast_mutex_lock(&table->lock);
          AST_LIST_UNLOCK(&mysql_tables);
          release_database(dbh);
          return table;
       }
    }
    /* Not found, scan the table */
    ast_str_set(&sql, 0, "DESC %s", tablename);
    if (!mysql_reconnect(dbh)) {
       release_database(dbh);
       AST_LIST_UNLOCK(&mysql_tables);
       return NULL;
    }
    if (mysql_real_query(&dbh->handle, ast_str_buffer(sql), ast_str_strlen(sql))) {
       ast_log(LOG_ERROR, "Failed to query database '%s', table '%s' columns: %s\n", database, tablename, mysql_error(&dbh->handle));
       release_database(dbh);
       AST_LIST_UNLOCK(&mysql_tables);
       return NULL;
    }
    if (!(table = ast_calloc(1, sizeof(*table) + strlen(tablename) + 1))) {
       ast_log(LOG_ERROR, "Unable to allocate memory for new table structure\n");
       release_database(dbh);
       AST_LIST_UNLOCK(&mysql_tables);
       return NULL;
    }
    strcpy(table->name, tablename); /* SAFE */
    table->database = dbh;
    ast_mutex_init(&table->lock);
    AST_LIST_HEAD_INIT_NOLOCK(&table->columns);
    if ((result = mysql_store_result(&dbh->handle))) {
       while ((row = mysql_fetch_row(result))) {
          fname = row[0];
          ftype = row[1];
          fnull = row[2];
          fdflt = row[4];
          ast_verb(4, "Found column '%s' of type '%s'\n", fname, ftype);
          if (fdflt == NULL) {
             fdflt = "";
          }
          if (!(column = ast_calloc(1, sizeof(*column) + strlen(fname) + strlen(ftype) + strlen(fdflt) + 3))) {
             ast_log(LOG_ERROR, "Unable to allocate column element %s for %s\n", fname, tablename);
             destroy_table(table);
             release_database(dbh);
             AST_LIST_UNLOCK(&mysql_tables);
             return NULL;
          }
          if ((flen = strchr(ftype, '('))) {
             sscanf(flen, "(%30d)", &column->len);
          } else {
             /* Columns like dates, times, and timestamps don't have a length */
             column->len = -1;
          }
          column->name = (char *)column + sizeof(*column);
          column->type = (char *)column + sizeof(*column) + strlen(fname) + 1;
          column->dflt = (char *)column + sizeof(*column) + strlen(fname) + 1 + strlen(ftype) + 1;
          strcpy(column->name, fname);
          strcpy(column->type, ftype);
          strcpy(column->dflt, fdflt);
          column->null = (strcmp(fnull, "YES") == 0 ? 1 : 0);
          AST_LIST_INSERT_TAIL(&table->columns, column, list);
       }
       mysql_free_result(result);
    }
    AST_LIST_INSERT_TAIL(&mysql_tables, table, list);
    ast_mutex_lock(&table->lock);
    AST_LIST_UNLOCK(&mysql_tables);
    release_database(dbh);
    return table;
 }
handle_cli_realtime_mysql_cache()
static char * handle_cli_realtime_mysql_cache (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) static
Definition at line 1394 of file res_config_mysql.c.
References ast_cli_args::argc, ast_cli_args::argv, ast_cli(), AST_LIST_LOCK, AST_LIST_TRAVERSE, AST_LIST_UNLOCK, AST_RWLIST_RDLOCK, AST_RWLIST_TRAVERSE, AST_RWLIST_UNLOCK, ast_strdup, CLI_GENERATE, CLI_INIT, CLI_SUCCESS, tables::columns, ast_cli_entry::command, tables::database, ast_cli_args::fd, find_table(), columns::len, columns::list, tables::list, ast_cli_args::n, columns::name, tables::name, NULL, release_table(), columns::type, ast_cli_entry::usage, and ast_cli_args::word.
 {
    struct tables *cur;
    int l, which;
    char *ret = NULL;
    switch (cmd) {
    case CLI_INIT:
       e->command = "realtime mysql cache";
       e->usage =
          "Usage: realtime mysql cache [<database> <table>]\n"
          "       Shows table cache for the MySQL RealTime driver\n";
       return NULL;
    case CLI_GENERATE:
       if (a->argc < 4 || a->argc > 5) {
          return NULL;
       }
       l = strlen(a->word);
       which = 0;
       if (a->argc == 5) {
          AST_LIST_LOCK(&mysql_tables);
          AST_LIST_TRAVERSE(&mysql_tables, cur, list) {
             if (!strcasecmp(a->argv[3], cur->database->unique_name) && !strncasecmp(a->word, cur->name, l) && ++which > a->n) {
                ret = ast_strdup(cur->name);
                break;
             }
          }
          AST_LIST_UNLOCK(&mysql_tables);
       } else {
          struct mysql_conn *cur;
          AST_RWLIST_RDLOCK(&databases);
          AST_RWLIST_TRAVERSE(&databases, cur, list) {
             if (!strncasecmp(a->word, cur->unique_name, l) && ++which > a->n) {
                ret = ast_strdup(cur->unique_name);
                break;
             }
          }
          AST_RWLIST_UNLOCK(&databases);
       }
       return ret;
    }
    if (a->argc == 3) {
       /* List of tables */
       AST_LIST_LOCK(&mysql_tables);
       AST_LIST_TRAVERSE(&mysql_tables, cur, list) {
          ast_cli(a->fd, "%20.20s %s\n", cur->database->unique_name, cur->name);
       }
       AST_LIST_UNLOCK(&mysql_tables);
    } else if (a->argc == 4) {
       int found = 0;
       /* List of tables */
       AST_LIST_LOCK(&mysql_tables);
       AST_LIST_TRAVERSE(&mysql_tables, cur, list) {
          if (!strcasecmp(cur->database->unique_name, a->argv[3])) {
             ast_cli(a->fd, "%s\n", cur->name);
             found = 1;
          }
       }
       AST_LIST_UNLOCK(&mysql_tables);
       if (!found) {
          ast_cli(a->fd, "No tables cached within %s database\n", a->argv[3]);
       }
    } else if (a->argc == 5) {
       /* List of columns */
       if ((cur = find_table(a->argv[3], a->argv[4]))) {
          struct columns *col;
          ast_cli(a->fd, "Columns for Table Cache '%s':\n", a->argv[3]);
          ast_cli(a->fd, "%-20.20s %-20.20s %-3.3s\n", "Name", "Type", "Len");
          AST_LIST_TRAVERSE(&cur->columns, col, list) {
             ast_cli(a->fd, "%-20.20s %-20.20s %3d\n", col->name, col->type, col->len);
          }
          release_table(cur);
       } else {
          ast_cli(a->fd, "No such table '%s'\n", a->argv[3]);
       }
    }
    return CLI_SUCCESS;
 }
handle_cli_realtime_mysql_status()
static char * handle_cli_realtime_mysql_status (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) static
Definition at line 1474 of file res_config_mysql.c.
References ast_cli_args::argc, ast_cli_args::argv, ast_cli(), AST_MODFLAG_LOAD_ORDER, AST_MODPRI_REALTIME_DRIVER, AST_MODULE_INFO(), AST_MODULE_SUPPORT_EXTENDED, AST_RWLIST_RDLOCK, AST_RWLIST_TRAVERSE, AST_RWLIST_UNLOCK, ast_strdup, ast_strlen_zero, ASTERISK_GPL_KEY, CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::command, ast_cli_args::fd, load_module(), mysql_reconnect(), ast_cli_args::n, NULL, reload(), status, type, unload_module(), ast_cli_entry::usage, and ast_cli_args::word.
 {
    char status[256], status2[100] = "", type[20];
    char *ret = NULL;
    int ctime = 0, found = 0;
    struct mysql_conn *cur;
    int l = 0, which = 0;
    switch (cmd) {
    case CLI_INIT:
       e->command = "realtime mysql status";
       e->usage =
          "Usage: realtime mysql status [<database>]\n"
          "       Shows connection information for the MySQL RealTime driver\n";
       return NULL;
    case CLI_GENERATE:
       if (a->argc == 4) {
          AST_RWLIST_RDLOCK(&databases);
          AST_RWLIST_TRAVERSE(&databases, cur, list) {
             if (!strncasecmp(a->word, cur->unique_name, l) && ++which > a->n) {
                ret = ast_strdup(cur->unique_name);
                break;
             }
          }
          AST_RWLIST_UNLOCK(&databases);
       }
       return ret;
    }
    if (a->argc != 3)
       return CLI_SHOWUSAGE;
    AST_RWLIST_RDLOCK(&databases);
    AST_RWLIST_TRAVERSE(&databases, cur, list) {
       if (a->argc == 3 || (a->argc == 4 && !strcasecmp(a->argv[3], cur->unique_name))) {
          found = 1;
          if (mysql_reconnect(cur)) {
             snprintf(type, sizeof(type), "connected to");
             ctime = time(NULL) - cur->connect_time;
          } else {
             snprintf(type, sizeof(type), "configured for");
             ctime = -1;
          }
          if (!ast_strlen_zero(cur->host)) {
             snprintf(status, sizeof(status), "%s %s %s@%s, port %d", cur->unique_name, type, cur->name, cur->host, cur->port);
          } else {
             snprintf(status, sizeof(status), "%s %s %s on socket file %s", cur->unique_name, type, cur->name, cur->sock);
          }
          if (!ast_strlen_zero(cur->user)) {
             snprintf(status2, sizeof(status2), " with username %s", cur->user);
          } else {
             status2[0] = '\0';
          }
          if (ctime > 31536000) {
             ast_cli(a->fd, "%s%s for %.1f years.\n", status, status2, (double)ctime / 31536000.0);
          } else if (ctime > 86400 * 30) {
             ast_cli(a->fd, "%s%s for %d days.\n", status, status2, ctime / 86400);
          } else if (ctime > 86400) {
             ast_cli(a->fd, "%s%s for %d days, %d hours.\n", status, status2, ctime / 86400, (ctime % 86400) / 3600);
          } else if (ctime > 3600) {
             ast_cli(a->fd, "%s%s for %d hours, %d minutes.\n", status, status2, ctime / 3600, (ctime % 3600) / 60);
          } else if (ctime > 60) {
             ast_cli(a->fd, "%s%s for %d minutes.\n", status, status2, ctime / 60);
          } else if (ctime > -1) {
             ast_cli(a->fd, "%s%s for %d seconds.\n", status, status2, ctime);
          } else {
             ast_cli(a->fd, "%s%s.\n", status, status2);
          }
       }
    }
    AST_RWLIST_UNLOCK(&databases);
    if (!found) {
       ast_cli(a->fd, "No connections configured.\n");
    }
    return CLI_SUCCESS;
 }
load_module()
static int load_module (void) static
Definition at line 1149 of file res_config_mysql.c.
References ast_cli_register_multiple, ast_config_engine_register(), ast_verb, and parse_config().
Referenced by handle_cli_realtime_mysql_status().
 {
    parse_config(0);
    ast_config_engine_register(&mysql_engine);
    ast_verb(2, "MySQL RealTime driver loaded.\n");
    ast_cli_register_multiple(cli_realtime_mysql_status, sizeof(cli_realtime_mysql_status) / sizeof(struct ast_cli_entry));
    return 0;
 }
load_mysql_config()
static int load_mysql_config (struct ast_config * config, const char * category, struct mysql_conn * conn) static
Definition at line 1242 of file res_config_mysql.c.
References ast_copy_string(), ast_debug, ast_log, ast_strlen_zero, ast_variable_retrieve(), LOG_WARNING, RQ_CREATECHAR, RQ_CREATECLOSE, and RQ_WARN.
Referenced by parse_config().
 {
    const char *s;
    if (!(s = ast_variable_retrieve(config, category, "dbuser"))) {
       ast_log(LOG_WARNING, "MySQL RealTime: No database user found, using 'asterisk' as default.\n");
       s = "asterisk";
    }
    ast_copy_string(conn->user, s, sizeof(conn->user));
    if (!(s = ast_variable_retrieve(config, category, "dbpass"))) {
       ast_log(LOG_WARNING, "MySQL RealTime: No database password found, using 'asterisk' as default.\n");
       s = "asterisk";
    }
    ast_copy_string(conn->pass, s, sizeof(conn->pass));
    if (!(s = ast_variable_retrieve(config, category, "dbhost"))) {
       ast_log(LOG_WARNING, "MySQL RealTime: No database host found, using localhost via socket.\n");
       s = "";
    }
    ast_copy_string(conn->host, s, sizeof(conn->host));
    if (!(s = ast_variable_retrieve(config, category, "dbname"))) {
       ast_log(LOG_WARNING, "MySQL RealTime: No database name found, using 'asterisk' as default.\n");
       s = "asterisk";
    }
    ast_copy_string(conn->name, s, sizeof(conn->name));
    if (!(s = ast_variable_retrieve(config, category, "dbport"))) {
       ast_log(LOG_WARNING, "MySQL RealTime: No database port found, using 3306 as default.\n");
       conn->port = 3306;
    } else
       conn->port = atoi(s);
    if (!(s = ast_variable_retrieve(config, category, "dbsock"))) {
       if (ast_strlen_zero(conn->host)) {
          char *paths[3] = { "/tmp/mysql.sock", "/var/lib/mysql/mysql.sock", "/var/run/mysqld/mysqld.sock" };
          struct stat st;
          int i;
          for (i = 0; i < 3; i++) {
             if (!stat(paths[i], &st)) {
                ast_log(LOG_WARNING, "MySQL RealTime: No database socket found, using '%s' as default.\n", paths[i]);
                ast_copy_string(conn->sock, paths[i], sizeof(conn->sock));
             }
          }
          if (i == 3) {
             ast_log(LOG_WARNING, "MySQL RealTime: No database socket found (and unable to detect a suitable path).\n");
             return 0;
          }
       }
    } else
       ast_copy_string(conn->sock, s, sizeof(conn->sock));
    if ((s = ast_variable_retrieve(config, category, "dbcharset"))) {
       ast_copy_string(conn->charset, s, sizeof(conn->charset));
    }
    if (!(s = ast_variable_retrieve(config, category, "requirements"))) {
       ast_log(LOG_WARNING, "MySQL realtime: no requirements setting found, using 'warn' as default.\n");
       conn->requirements = RQ_WARN;
    } else if (!strcasecmp(s, "createclose")) {
       conn->requirements = RQ_CREATECLOSE;
    } else if (!strcasecmp(s, "createchar")) {
       conn->requirements = RQ_CREATECHAR;
    } else if (!strcasecmp(s, "warn")) {
       conn->requirements = RQ_WARN;
    } else {
       ast_log(LOG_WARNING, "MySQL realtime: unrecognized requirements setting '%s', using 'warn'\n", s);
       conn->requirements = RQ_WARN;
    }
    if (!ast_strlen_zero(conn->host)) {
       ast_debug(1, "MySQL RealTime host: %s\n", conn->host);
       ast_debug(1, "MySQL RealTime port: %i\n", conn->port);
    } else
       ast_debug(1, "MySQL RealTime socket: %s\n", conn->sock);
    ast_debug(1, "MySQL RealTime database name: %s\n", conn->name);
    ast_debug(1, "MySQL RealTime user: %s\n", conn->user);
    ast_debug(1, "MySQL RealTime password: %s\n", conn->pass);
    if(!ast_strlen_zero(conn->charset))
       ast_debug(1, "MySQL RealTime charset: %s\n", conn->charset);
    return 1;
 }
mysql_reconnect()
static int mysql_reconnect (struct mysql_conn * conn) static
Definition at line 1327 of file res_config_mysql.c.
References ast_debug, ast_log, ast_strlen_zero, LOG_ERROR, LOG_WARNING, and NULL.
Referenced by config_mysql(), destroy_mysql(), find_table(), handle_cli_realtime_mysql_status(), realtime_multi_mysql(), realtime_mysql(), store_mysql(), update2_mysql(), and update_mysql().
 {
 #ifdef MYSQL_OPT_RECONNECT
    my_bool trueval = 1;
 #endif
    /* mutex lock should have been locked before calling this function. */
 reconnect_tryagain:
    if ((!conn->connected) && (!ast_strlen_zero(conn->host) || !ast_strlen_zero(conn->sock)) && !ast_strlen_zero(conn->user) && !ast_strlen_zero(conn->name)) {
       if (!mysql_init(&conn->handle)) {
          ast_log(LOG_WARNING, "MySQL RealTime: Insufficient memory to allocate MySQL resource.\n");
          conn->connected = 0;
          return 0;
       }
       if(strlen(conn->charset) > 2){
          char set_names[255];
          char statement[512];
          snprintf(set_names, sizeof(set_names), "SET NAMES %s", conn->charset);
          mysql_real_escape_string(&conn->handle, statement, set_names, sizeof(set_names));
          mysql_options(&conn->handle, MYSQL_INIT_COMMAND, set_names);
          mysql_options(&conn->handle, MYSQL_SET_CHARSET_NAME, conn->charset);
       }
       if (mysql_real_connect(&conn->handle, conn->host, conn->user, conn->pass, conn->name, conn->port, conn->sock, 0)) {
 #ifdef MYSQL_OPT_RECONNECT
          /* The default is no longer to automatically reconnect on failure,
           * (as of 5.0.3) so we have to set that option here. */
          mysql_options(&conn->handle, MYSQL_OPT_RECONNECT, &trueval);
 #endif
          ast_debug(1, "MySQL RealTime: Successfully connected to database.\n");
          conn->connected = 1;
          conn->connect_time = time(NULL);
          return 1;
       } else {
          ast_log(LOG_ERROR, "MySQL RealTime: Failed to connect database server %s on %s (err %d). Check debug for more info.\n", conn->name, !ast_strlen_zero(conn->host) ? conn->host : conn->sock, mysql_errno(&conn->handle));
          ast_debug(1, "MySQL RealTime: Cannot Connect (%d): %s\n", mysql_errno(&conn->handle), mysql_error(&conn->handle));
          conn->connected = 0;
          conn->connect_time = 0;
          return 0;
       }
    } else {
       /* MySQL likes to return an error, even if it reconnects successfully.
        * So the postman pings twice. */
       if (mysql_ping(&conn->handle) != 0 && (usleep(1) + 2 > 0) && mysql_ping(&conn->handle) != 0) {
          conn->connected = 0;
          conn->connect_time = 0;
          ast_log(LOG_ERROR, "MySQL RealTime: Ping failed (%d).  Trying an explicit reconnect.\n", mysql_errno(&conn->handle));
          ast_debug(1, "MySQL RealTime: Server Error (%d): %s\n", mysql_errno(&conn->handle), mysql_error(&conn->handle));
          goto reconnect_tryagain;
       }
       if (!conn->connected) {
          conn->connected = 1;
          conn->connect_time = time(NULL);
       }
       if (mysql_select_db(&conn->handle, conn->name) != 0) {
          ast_log(LOG_WARNING, "MySQL RealTime: Unable to select database: %s. Still Connected (%u) - %s.\n", conn->name, mysql_errno(&conn->handle), mysql_error(&conn->handle));
          return 0;
       }
       ast_debug(1, "MySQL RealTime: Connection okay.\n");
       return 1;
    }
 }
parse_config()
static int parse_config (int reload) static
Definition at line 1193 of file res_config_mysql.c.
References ast_calloc, ast_category_browse(), ast_config_destroy(), ast_config_load, ast_log, ast_mutex_init, AST_RWLIST_INSERT_TAIL, AST_RWLIST_TRAVERSE, AST_RWLIST_UNLOCK, AST_RWLIST_WRLOCK, config, CONFIG_FLAG_FILEUNCHANGED, CONFIG_STATUS_FILEINVALID, CONFIG_STATUS_FILEMISSING, CONFIG_STATUS_FILEUNCHANGED, load_mysql_config(), LOG_ERROR, LOG_WARNING, NULL, RES_CONFIG_MYSQL_CONF, and RES_CONFIG_MYSQL_CONF_OLD.
Referenced by load_module(), and reload().
 {
    struct ast_config *config = NULL;
    struct ast_flags config_flags = { reload ? CONFIG_FLAG_FILEUNCHANGED : 0 };
    const char *catg;
    struct mysql_conn *cur;
    if ((config = ast_config_load(RES_CONFIG_MYSQL_CONF, config_flags)) == CONFIG_STATUS_FILEMISSING) {
       /* Support old config file name */
       config = ast_config_load(RES_CONFIG_MYSQL_CONF_OLD, config_flags);
    }
    if (config == CONFIG_STATUS_FILEMISSING) {
       return 0;
    } else if (config == CONFIG_STATUS_FILEUNCHANGED) {
       return 0;
    } else if (config == CONFIG_STATUS_FILEINVALID) {
       ast_log(LOG_ERROR, "Not %sloading " RES_CONFIG_MYSQL_CONF "\n", reload ? "re" : "");
    }
    AST_RWLIST_WRLOCK(&databases);
    for (catg = ast_category_browse(config, NULL); catg; catg = ast_category_browse(config, catg)) {
       /* Does this category already exist? */
       AST_RWLIST_TRAVERSE(&databases, cur, list) {
          if (!strcmp(cur->unique_name, catg)) {
             break;
          }
       }
       if (!cur) {
          if (!(cur = ast_calloc(1, sizeof(*cur) + strlen(catg) + 1))) {
             ast_log(LOG_WARNING, "Could not allocate space for MySQL database '%s'\n", catg);
             continue;
          }
          strcpy(cur->unique_name, catg); /* SAFE */
          ast_mutex_init(&cur->lock);
          AST_RWLIST_INSERT_TAIL(&databases, cur, list);
       }
       load_mysql_config(config, catg, cur);
    }
    AST_RWLIST_UNLOCK(&databases);
    ast_config_destroy(config);
    return 0;
 }
realtime_multi_mysql()
static struct ast_config* realtime_multi_mysql (const char * database, const char * table, const struct ast_variable * rt_fields) static
Definition at line 420 of file res_config_mysql.c.
References ast_category_append(), ast_category_new_anonymous, ast_category_rename(), ast_config_destroy(), ast_config_new(), ast_debug, ast_log, ast_str_append(), ast_str_buffer(), ast_str_set(), ast_str_strlen(), ast_str_thread_get(), ast_strdupa, ast_strip(), ast_strlen_zero, ast_variable_append(), ast_variable_new, buf, decode_chunk(), ESCAPE_CLAUSE, ESCAPE_STRING, find_database(), IS_SQL_LIKE_CLAUSE, LOG_WARNING, mysql_reconnect(), name, ast_variable::name, ast_variable::next, NULL, release_database, result, scratch_buf, sql_buf, strsep(), ast_variable::value, and var.
 {
    struct mysql_conn *dbh;
    MYSQL_RES *result;
    MYSQL_ROW row;
    MYSQL_FIELD *fields;
    int numFields, i;
    struct ast_str *sql = ast_str_thread_get(&sql_buf, 16);
    struct ast_str *buf = ast_str_thread_get(&scratch_buf, 16);
    const char *initfield = NULL;
    char *stringp;
    char *chunk;
    char *op;
    char *escape = "";
    const struct ast_variable *field = rt_fields;
    struct ast_variable *var = NULL;
    struct ast_config *cfg = NULL;
    struct ast_category *cat = NULL;
    if (!(dbh = find_database(database, 0))) {
       ast_log(LOG_WARNING, "MySQL RealTime: Invalid database specified: '%s' (check res_mysql.conf)\n", database);
       return NULL;
    }
    if (!table) {
       ast_log(LOG_WARNING, "MySQL RealTime: No table specified.\n");
       release_database(dbh);
       return NULL;
    }
    if (!(cfg = ast_config_new())) {
       /* If I can't alloc memory at this point, why bother doing anything else? */
       ast_log(LOG_WARNING, "Out of memory!\n");
       release_database(dbh);
       return NULL;
    }
    /* Get the first parameter and first value in our list of passed paramater/value pairs */
    if (!field) {
       ast_log(LOG_WARNING, "MySQL RealTime: Realtime retrieval requires at least 1 parameter and 1 value to search on.\n");
       ast_config_destroy(cfg);
       release_database(dbh);
       return NULL;
    }
    initfield = ast_strdupa(field->name);
    if ((op = strchr(initfield, ' '))) {
       *op = '\0';
    }
    /* Must connect to the server before anything else, as the escape function requires the mysql handle. */
    if (!mysql_reconnect(dbh)) {
       release_database(dbh);
       ast_config_destroy(cfg);
       return NULL;
    }
    /* Create the first part of the query using the first parameter/value pairs we just extracted
       If there is only 1 set, then we have our query. Otherwise, loop thru the list and concat */
    if (!strchr(field->name, ' ')) {
       op = " =";
    } else {
       op = "";
       if (IS_SQL_LIKE_CLAUSE(field->name)) {
          escape = ESCAPE_CLAUSE;
       }
    }
    ESCAPE_STRING(buf, field->value);
    ast_str_set(&sql, 0, "SELECT * FROM %s WHERE %s%s '%s'%s", table, field->name, op, ast_str_buffer(buf), escape);
    while ((field = field->next)) {
       escape = "";
       if (!strchr(field->name, ' ')) {
          op = " =";
       } else {
          op = "";
          if (IS_SQL_LIKE_CLAUSE(field->name)) {
             escape = ESCAPE_CLAUSE;
          }
       }
       ESCAPE_STRING(buf, field->value);
       ast_str_append(&sql, 0, " AND %s%s '%s'%s", field->name, op, ast_str_buffer(buf), escape);
    }
    if (initfield) {
       ast_str_append(&sql, 0, " ORDER BY %s", initfield);
    }
    ast_debug(1, "MySQL RealTime: Retrieve SQL: %s\n", ast_str_buffer(sql));
    /* Execution. */
    if (mysql_real_query(&dbh->handle, ast_str_buffer(sql), ast_str_strlen(sql))) {
       ast_log(LOG_WARNING, "MySQL RealTime: Failed to query database: %s\n", mysql_error(&dbh->handle));
       release_database(dbh);
       ast_config_destroy(cfg);
       return NULL;
    }
    if ((result = mysql_store_result(&dbh->handle))) {
       numFields = mysql_num_fields(result);
       fields = mysql_fetch_fields(result);
       while ((row = mysql_fetch_row(result))) {
          var = NULL;
          cat = ast_category_new_anonymous();
          if (!cat) {
             continue;
          }
          for (i = 0; i < numFields; i++) {
             if (ast_strlen_zero(row[i]))
                continue;
             for (stringp = row[i], chunk = strsep(&stringp, ";"); chunk; chunk = strsep(&stringp, ";")) {
                if (chunk && !ast_strlen_zero(decode_chunk(ast_strip(chunk)))) {
                   if (initfield && !strcmp(initfield, fields[i].name)) {
                      ast_category_rename(cat, chunk);
                   }
                   var = ast_variable_new(fields[i].name, chunk, "");
                   ast_variable_append(cat, var);
                }
             }
          }
          ast_category_append(cfg, cat);
       }
    } else {
       ast_debug(1, "MySQL RealTime: Could not find any rows in table %s.\n", table);
    }
    release_database(dbh);
    mysql_free_result(result);
    return cfg;
 }
realtime_mysql()
static struct ast_variable* realtime_mysql (const char * database, const char * table, const struct ast_variable * rt_fields) static
Definition at line 310 of file res_config_mysql.c.
References ast_debug, ast_log, ast_str_append(), ast_str_buffer(), ast_str_set(), ast_str_strlen(), ast_str_thread_get(), ast_strlen_zero, ast_variable_new, buf, decode_chunk(), ESCAPE_CLAUSE, ESCAPE_STRING, find_database(), IS_SQL_LIKE_CLAUSE, LOG_WARNING, mysql_reconnect(), name, ast_variable::name, ast_variable::next, NULL, release_database, result, scratch_buf, sql_buf, strsep(), ast_variable::value, and var.
 {
    struct mysql_conn *dbh;
    MYSQL_RES *result;
    MYSQL_ROW row;
    MYSQL_FIELD *fields;
    int numFields, i;
    struct ast_str *sql = ast_str_thread_get(&sql_buf, 16);
    struct ast_str *buf = ast_str_thread_get(&scratch_buf, 16);
    char *stringp;
    char *chunk;
    char *op;
    char *escape = "";
    const struct ast_variable *field = rt_fields;
    struct ast_variable *var=NULL, *prev=NULL;
    if (!(dbh = find_database(database, 0))) {
       ast_log(LOG_WARNING, "MySQL RealTime: Invalid database specified: %s (check res_mysql.conf)\n", database);
       return NULL;
    }
    if (!table) {
       ast_log(LOG_WARNING, "MySQL RealTime: No table specified.\n");
       release_database(dbh);
       return NULL;
    }
    /* Get the first parameter and first value in our list of passed paramater/value pairs */
    if (!field) {
       ast_log(LOG_WARNING, "MySQL RealTime: Realtime retrieval requires at least 1 parameter and 1 value to search on.\n");
       release_database(dbh);
       return NULL;
    }
    /* Must connect to the server before anything else, as the escape function requires the mysql handle. */
    if (!mysql_reconnect(dbh)) {
       release_database(dbh);
       return NULL;
    }
    /* Create the first part of the query using the first parameter/value pairs we just extracted
       If there is only 1 set, then we have our query. Otherwise, loop thru the list and concat */
    if (!strchr(field->name, ' ')) {
       op = " =";
    } else {
       op = "";
       if (IS_SQL_LIKE_CLAUSE(field->name)) {
          escape = ESCAPE_CLAUSE;
       }
    }
    ESCAPE_STRING(buf, field->value);
    ast_str_set(&sql, 0, "SELECT * FROM %s WHERE %s%s '%s'%s", table, field->name, op, ast_str_buffer(buf), escape);
    while ((field = field->next)) {
       escape = "";
       if (!strchr(field->name, ' ')) {
          op = " =";
       } else {
          op = "";
          if (IS_SQL_LIKE_CLAUSE(field->name)) {
             escape = ESCAPE_CLAUSE;
          }
       }
       ESCAPE_STRING(buf, field->value);
       ast_str_append(&sql, 0, " AND %s%s '%s'%s", field->name, op, ast_str_buffer(buf), escape);
    }
    ast_debug(1, "MySQL RealTime: Retrieve SQL: %s\n", ast_str_buffer(sql));
    /* Execution. */
    if (mysql_real_query(&dbh->handle, ast_str_buffer(sql), ast_str_strlen(sql))) {
       ast_log(LOG_WARNING, "MySQL RealTime: Failed to query database: %s\n", mysql_error(&dbh->handle));
       release_database(dbh);
       return NULL;
    }
    if ((result = mysql_store_result(&dbh->handle))) {
       numFields = mysql_num_fields(result);
       fields = mysql_fetch_fields(result);
       while ((row = mysql_fetch_row(result))) {
          for (i = 0; i < numFields; i++) {
             /* Encode NULL values separately from blank values, for the Realtime API */
             if (row[i] == NULL) {
                row[i] = "";
             } else if (ast_strlen_zero(row[i])) {
                row[i] = " ";
             }
             for (stringp = row[i], chunk = strsep(&stringp, ";"); chunk; chunk = strsep(&stringp, ";")) {
                if (prev) {
                   if ((prev->next = ast_variable_new(fields[i].name, decode_chunk(chunk), ""))) {
                      prev = prev->next;
                   }
                } else {
                   prev = var = ast_variable_new(fields[i].name, decode_chunk(chunk), "");
                }
             }
          }
       }
    } else {
       ast_debug(1, "MySQL RealTime: Could not find any rows in table %s.\n", table);
    }
    release_database(dbh);
    mysql_free_result(result);
    return var;
 }
release_table()
static void release_table (struct tables * table) static
Definition at line 273 of file res_config_mysql.c.
References ast_mutex_unlock, and tables::lock.
Referenced by handle_cli_realtime_mysql_cache(), require_mysql(), update2_mysql(), and update_mysql().
 {
    if (table) {
       ast_mutex_unlock(&table->lock);
    }
 }
reload()
static int reload (void) static
Definition at line 1186 of file res_config_mysql.c.
References ast_verb, and parse_config().
Referenced by handle_cli_realtime_mysql_status().
 {
    parse_config(1);
    ast_verb(2, "MySQL RealTime reloaded.\n");
    return 0;
 }
require_mysql()
static int require_mysql (const char * database, const char * tablename, va_list ap) static
Definition at line 973 of file res_config_mysql.c.
References AST_LIST_TRAVERSE, ast_log, ast_rq_is_int(), tables::columns, find_table(), columns::len, tables::list, LOG_WARNING, columns::name, release_table(), RQ_CHAR, RQ_DATE, RQ_DATETIME, RQ_FLOAT, RQ_INTEGER1, RQ_INTEGER2, RQ_INTEGER3, RQ_INTEGER4, RQ_INTEGER8, RQ_UINTEGER1, RQ_UINTEGER2, RQ_UINTEGER3, RQ_UINTEGER4, RQ_UINTEGER8, strcasestr(), table, columns::type, and type.
 {
    struct columns *column;
    struct tables *table = find_table(database, tablename);
    char *elm;
    int type;
    int size;
    int res = 0;
    if (!table) {
       ast_log(LOG_WARNING, "Table %s not found in database.  This table should exist if you're using realtime.\n", tablename);
       return -1;
    }
    while ((elm = va_arg(ap, char *))) {
       type = va_arg(ap, require_type);
       size = va_arg(ap, int);
       AST_LIST_TRAVERSE(&table->columns, column, list) {
          if (strcmp(column->name, elm) == 0) {
             /* Char can hold anything, as long as it is large enough */
             if (strncmp(column->type, "char", 4) == 0 || strncmp(column->type, "varchar", 7) == 0) {
                if ((size > column->len) && column->len != -1) {
                   ast_log(LOG_WARNING, "Realtime table %s@%s: Column '%s' should be at least %d long, but is only %d long.\n", database, tablename, column->name, size, column->len);
                   res = -1;
                }
             } else if (strcasestr(column->type, "unsigned")) {
                if (!ast_rq_is_int(type)) {
                   ast_log(LOG_WARNING, "Realtime table %s@%s: column '%s' cannot be type '%s' (need %s)\n",
                      database, tablename, column->name, column->type,
                      type == RQ_CHAR ? "char" : type == RQ_FLOAT ? "float" :
                      type == RQ_DATETIME ? "datetime" : type == RQ_DATE ? "date" : "a rather stiff drink");
                   res = -1;
                } else if (strncasecmp(column->type, "tinyint", 1) == 0) {
                   if (type != RQ_UINTEGER1) {
                      ast_log(LOG_WARNING, "Realtime table %s@%s: column '%s' may not be large enough for "            \
                         "the required data length: %d (detected stringtype)\n",                                      \
                         tablename, database, column->name, size);                                                    \
                      res = -1;                                                                                        \
                   }
                } else if (strncasecmp(column->type, "smallint", 1) == 0) {
                   if (type != RQ_UINTEGER1 && type != RQ_INTEGER1 && type != RQ_UINTEGER2) {
                      ast_log(LOG_WARNING, "Realtime table %s@%s: column '%s' may not be large enough for "            \
                         "the required data length: %d (detected stringtype)\n",                                      \
                         tablename, database, column->name, size);                                                    \
                      res = -1;                                                                                        \
                   }
                } else if (strncasecmp(column->type, "mediumint", 1) == 0) {
                   if (type != RQ_UINTEGER1 && type != RQ_INTEGER1 &&
                      type != RQ_UINTEGER2 && type != RQ_INTEGER2 &&
                      type != RQ_UINTEGER3) {
                      ast_log(LOG_WARNING, "Realtime table %s@%s: column '%s' may not be large enough for "            \
                         "the required data length: %d (detected stringtype)\n",                                      \
                         tablename, database, column->name, size);                                                    \
                      res = -1;                                                                                        \
                   }
                } else if (strncasecmp(column->type, "int", 1) == 0) {
                   if (type != RQ_UINTEGER1 && type != RQ_INTEGER1 &&
                      type != RQ_UINTEGER2 && type != RQ_INTEGER2 &&
                      type != RQ_UINTEGER3 && type != RQ_INTEGER3 &&
                      type != RQ_UINTEGER4) {
                      ast_log(LOG_WARNING, "Realtime table %s@%s: column '%s' may not be large enough for "            \
                         "the required data length: %d (detected stringtype)\n",                                      \
                         tablename, database, column->name, size);                                                    \
                      res = -1;                                                                                        \
                   }
                } else if (strncasecmp(column->type, "bigint", 1) == 0) {
                   if (type != RQ_UINTEGER1 && type != RQ_INTEGER1 &&
                      type != RQ_UINTEGER2 && type != RQ_INTEGER2 &&
                      type != RQ_UINTEGER3 && type != RQ_INTEGER3 &&
                      type != RQ_UINTEGER4 && type != RQ_INTEGER4 &&
                      type != RQ_UINTEGER8) {
                      ast_log(LOG_WARNING, "Realtime table %s@%s: column '%s' may not be large enough for "            \
                         "the required data length: %d (detected stringtype)\n",                                      \
                         tablename, database, column->name, size);                                                    \
                      res = -1;                                                                                        \
                   }
                }
             } else if (strcasestr(column->type, "int")) {
                if (!ast_rq_is_int(type)) {
                   ast_log(LOG_WARNING, "Realtime table %s@%s: column '%s' cannot be type '%s' (need %s)\n",
                      database, tablename, column->name, column->type,
                      type == RQ_CHAR ? "char" : type == RQ_FLOAT ? "float" :
                      type == RQ_DATETIME ? "datetime" : type == RQ_DATE ? "date" :
                      "to get a life, rather than writing silly error messages");
                   res = -1;
                } else if (strncasecmp(column->type, "tinyint", 1) == 0) {
                   if (type != RQ_INTEGER1) {
                      ast_log(LOG_WARNING, "Realtime table %s@%s: column '%s' may not be large enough for "            \
                         "the required data length: %d (detected stringtype)\n",                                      \
                         tablename, database, column->name, size);                                                    \
                      res = -1;                                                                                        \
                   }
                } else if (strncasecmp(column->type, "smallint", 1) == 0) {
                   if (type != RQ_UINTEGER1 && type != RQ_INTEGER1 && type != RQ_INTEGER2) {
                      ast_log(LOG_WARNING, "Realtime table %s@%s: column '%s' may not be large enough for "            \
                         "the required data length: %d (detected stringtype)\n",                                      \
                         tablename, database, column->name, size);                                                    \
                      res = -1;                                                                                        \
                   }
                } else if (strncasecmp(column->type, "mediumint", 1) == 0) {
                   if (type != RQ_UINTEGER1 && type != RQ_INTEGER1 &&
                      type != RQ_UINTEGER2 && type != RQ_INTEGER2 &&
                      type != RQ_INTEGER3) {
                      ast_log(LOG_WARNING, "Realtime table %s@%s: column '%s' may not be large enough for "            \
                         "the required data length: %d (detected stringtype)\n",                                      \
                         tablename, database, column->name, size);                                                    \
                      res = -1;                                                                                        \
                   }
                } else if (strncasecmp(column->type, "int", 1) == 0) {
                   if (type != RQ_UINTEGER1 && type != RQ_INTEGER1 &&
                      type != RQ_UINTEGER2 && type != RQ_INTEGER2 &&
                      type != RQ_UINTEGER3 && type != RQ_INTEGER3 &&
                      type != RQ_INTEGER4) {
                      ast_log(LOG_WARNING, "Realtime table %s@%s: column '%s' may not be large enough for "            \
                         "the required data length: %d (detected stringtype)\n",                                      \
                         tablename, database, column->name, size);                                                    \
                      res = -1;                                                                                        \
                   }
                } else if (strncasecmp(column->type, "bigint", 1) == 0) {
                   if (type != RQ_UINTEGER1 && type != RQ_INTEGER1 &&
                      type != RQ_UINTEGER2 && type != RQ_INTEGER2 &&
                      type != RQ_UINTEGER3 && type != RQ_INTEGER3 &&
                      type != RQ_UINTEGER4 && type != RQ_INTEGER4 &&
                      type != RQ_INTEGER8) {
                      ast_log(LOG_WARNING, "Realtime table %s@%s: column '%s' may not be large enough for "            \
                         "the required data length: %d (detected stringtype)\n",                                      \
                         tablename, database, column->name, size);                                                    \
                      res = -1;                                                                                        \
                   }
                }
             } else if (strncmp(column->type, "float", 5) == 0) {
                if (!ast_rq_is_int(type) && type != RQ_FLOAT) {
                   ast_log(LOG_WARNING, "Realtime table %s@%s: Column %s cannot be a %s\n", tablename, database, column->name, column->type);
                   res = -1;
                }
             } else if (strncmp(column->type, "datetime", 8) == 0 || strncmp(column->type, "timestamp", 9) == 0) {
                if (type != RQ_DATETIME) {
                   ast_log(LOG_WARNING, "Realtime table %s@%s: Column %s cannot be a %s\n", tablename, database, column->name, column->type);
                   res = -1;
                }
             } else if (strncmp(column->type, "date", 4) == 0) {
                if (type != RQ_DATE) {
                   ast_log(LOG_WARNING, "Realtime table %s@%s: Column %s cannot be a %s\n", tablename, database, column->name, column->type);
                   res = -1;
                }
             } else { /* Other, possibly unsupported types? */
                ast_log(LOG_WARNING, "Possibly unsupported column type '%s' on column '%s'\n", column->type, column->name);
                res = -1;
             }
             break;
          }
       }
       if (!column) {
          ast_log(LOG_WARNING, "Table %s requires a column '%s' of size '%d', but no such column exists.\n", tablename, elm, size);
       }
    }
    release_table(table);
    return res;
 }
store_mysql()
static int store_mysql (const char * database, const char * table, const struct ast_variable * rt_fields) static
Definition at line 752 of file res_config_mysql.c.
References ast_debug, ast_log, ast_str_append(), ast_str_buffer(), ast_str_set(), ast_str_strlen(), ast_str_thread_get(), buf, ESCAPE_STRING, find_database(), LOG_WARNING, mysql_reconnect(), ast_variable::name, ast_variable::next, release_database, scratch_buf, sql2_buf, sql_buf, and ast_variable::value.
 {
    struct mysql_conn *dbh;
    struct ast_str *sql = ast_str_thread_get(&sql_buf, 16);
    struct ast_str *sql2 = ast_str_thread_get(&sql2_buf, 16);
    struct ast_str *buf = ast_str_thread_get(&scratch_buf, 16);
    const struct ast_variable *field = rt_fields;
    if (!(dbh = find_database(database, 1))) {
       ast_log(LOG_WARNING, "MySQL RealTime: Invalid database specified: '%s' (check res_mysql.conf)\n", database);
       return -1;
    }
    if (!table) {
       ast_log(LOG_WARNING, "MySQL RealTime: No table specified.\n");
       release_database(dbh);
       return -1;
    }
    /* Get the first parameter and first value in our list of passed paramater/value pairs */
    if (!field) {
       ast_log(LOG_WARNING, "MySQL RealTime: Realtime storage requires at least 1 parameter and 1 value to search on.\n");
       release_database(dbh);
       return -1;
    }
    /* Must connect to the server before anything else, as the escape function requires the mysql handle. */
    if (!mysql_reconnect(dbh)) {
       release_database(dbh);
       return -1;
    }
    /* Create the first part of the query using the first parameter/value pairs we just extracted
       If there is only 1 set, then we have our query. Otherwise, loop thru the list and concat */
    ESCAPE_STRING(buf, field->value);
    ast_str_set(&sql, 0, "INSERT INTO %s (`%s`", table, field->name);
    ast_str_set(&sql2, 0, ") VALUES ('%s'", ast_str_buffer(buf));
    while ((field = field->next)) {
       ESCAPE_STRING(buf, field->value);
       ast_str_append(&sql, 0, ", `%s`", field->name);
       ast_str_append(&sql2, 0, ", '%s'", ast_str_buffer(buf));
    }
    ast_str_append(&sql, 0, "%s)", ast_str_buffer(sql2));
    ast_debug(1,"MySQL RealTime: Insert SQL: %s\n", ast_str_buffer(sql));
    /* Execution. */
    if (mysql_real_query(&dbh->handle, ast_str_buffer(sql), ast_str_strlen(sql))) {
       ast_log(LOG_WARNING, "MySQL RealTime: Failed to insert into database: %s\n", mysql_error(&dbh->handle));
       release_database(dbh);
       return -1;
    }
    release_database(dbh);
    ast_debug(1, "MySQL RealTime: row inserted on table: %s\n", table);
    return 1;
 }
unload_module()
static int unload_module (void) static
Definition at line 1159 of file res_config_mysql.c.
References ast_cli_unregister_multiple(), ast_config_engine_deregister(), ast_free, AST_LIST_LOCK, AST_LIST_REMOVE_HEAD, AST_LIST_UNLOCK, ast_mutex_destroy, AST_RWLIST_REMOVE_HEAD, AST_RWLIST_UNLOCK, AST_RWLIST_WRLOCK, ast_verb, destroy_table(), tables::list, and table.
Referenced by handle_cli_realtime_mysql_status().
 {
    struct mysql_conn *cur;
    struct tables *table;
    ast_cli_unregister_multiple(cli_realtime_mysql_status, sizeof(cli_realtime_mysql_status) / sizeof(struct ast_cli_entry));
    ast_config_engine_deregister(&mysql_engine);
    ast_verb(2, "MySQL RealTime unloaded.\n");
    AST_RWLIST_WRLOCK(&databases);
    while ((cur = AST_RWLIST_REMOVE_HEAD(&databases, list))) {
       mysql_close(&cur->handle);
       ast_mutex_destroy(&cur->lock);
       ast_free(cur);
    }
    AST_RWLIST_UNLOCK(&databases);
    /* Destroy cached table info */
    AST_LIST_LOCK(&mysql_tables);
    while ((table = AST_LIST_REMOVE_HEAD(&mysql_tables, list))) {
       destroy_table(table);
    }
    AST_LIST_UNLOCK(&mysql_tables);
    return 0;
 }
unload_mysql()
static int unload_mysql (const char * database, const char * tablename) static
Definition at line 957 of file res_config_mysql.c.
References AST_LIST_LOCK, AST_LIST_REMOVE_CURRENT, AST_LIST_TRAVERSE_SAFE_BEGIN, AST_LIST_TRAVERSE_SAFE_END, AST_LIST_UNLOCK, destroy_table(), tables::list, and tables::name.
 {
    struct tables *cur;
    AST_LIST_LOCK(&mysql_tables);
    AST_LIST_TRAVERSE_SAFE_BEGIN(&mysql_tables, cur, list) {
       if (strcmp(cur->name, tablename) == 0) {
          AST_LIST_REMOVE_CURRENT(list);
          destroy_table(cur);
          break;
       }
    }
    AST_LIST_TRAVERSE_SAFE_END
    AST_LIST_UNLOCK(&mysql_tables);
    return cur ? 0 : -1;
 }
update2_mysql()
static int update2_mysql (const char * database, const char * tablename, const struct ast_variable * lookup_fields, const struct ast_variable * update_fields) static
Definition at line 655 of file res_config_mysql.c.
References ast_debug, ast_log, ast_str_append(), ast_str_buffer(), ast_str_set(), ast_str_strlen(), ast_str_thread_get(), buf, ESCAPE_STRING, find_column(), find_database(), find_table(), first, LOG_ERROR, LOG_WARNING, mysql_reconnect(), ast_variable::name, ast_variable::next, NULL, release_database, release_table(), scratch_buf, sql2_buf, sql_buf, table, and ast_variable::value.
 {
    struct mysql_conn *dbh;
    uint64_t numrows;
    int first;
    const struct ast_variable *field;
    struct ast_str *sql = ast_str_thread_get(&sql_buf, 100), *buf = ast_str_thread_get(&scratch_buf, 100);
    struct ast_str *where = ast_str_thread_get(&sql2_buf, 100);
    struct tables *table;
    struct columns *column = NULL;
    if (!tablename) {
       ast_log(LOG_WARNING, "MySQL RealTime: No table specified.\n");
       return -1;
    }
    if (!(dbh = find_database(database, 1))) {
       ast_log(LOG_ERROR, "Invalid database specified: %s\n", database);
       return -1;
    }
    if (!(table = find_table(database, tablename))) {
       ast_log(LOG_ERROR, "Table '%s' does not exist!!\n", tablename);
       release_database(dbh);
       return -1;
    }
    if (!sql || !buf || !where) {
       release_database(dbh);
       release_table(table);
       return -1;
    }
    ast_str_set(&sql, 0, "UPDATE %s SET", tablename);
    ast_str_set(&where, 0, "WHERE");
    /* Must connect to the server before anything else, as the escape function requires the mysql handle. */
    if (!mysql_reconnect(dbh)) {
       release_table(table);
       release_database(dbh);
       return -1;
    }
    first = 1;
    for (field = lookup_fields; field; field = field->next) {
       if (!(column = find_column(table, field->name))) {
          ast_log(LOG_ERROR, "Updating on column '%s', but that column does not exist within the table '%s'!\n", field->name, tablename);
          release_table(table);
          release_database(dbh);
          return -1;
       }
       ESCAPE_STRING(buf, field->value);
       ast_str_append(&where, 0, "%s `%s` = '%s'", first ? "" : " AND", field->name, ast_str_buffer(buf));
       first = 0;
    }
    first = 1;
    for (field = update_fields; field; field = field->next) {
       /* If the column is not within the table, then skip it */
       if (!(column = find_column(table, field->name))) {
          ast_log(LOG_WARNING, "Attempted to update column '%s' in table '%s', but column does not exist!\n", field->name, tablename);
          continue;
       }
       ESCAPE_STRING(buf, field->value);
       ast_str_append(&sql, 0, "%s `%s` = '%s'", first ? "" : ",", field->name, ast_str_buffer(buf));
       first = 0;
    }
    release_table(table);
    ast_str_append(&sql, 0, " %s", ast_str_buffer(where));
    ast_debug(1, "MySQL RealTime: Update SQL: %s\n", ast_str_buffer(sql));
    /* Execution. */
    if (mysql_real_query(&dbh->handle, ast_str_buffer(sql), ast_str_strlen(sql))) {
       ast_log(LOG_WARNING, "MySQL RealTime: Failed to update database: %s\n", mysql_error(&dbh->handle));
       release_table(table);
       release_database(dbh);
       return -1;
    }
    numrows = mysql_affected_rows(&dbh->handle);
    release_database(dbh);
    ast_debug(1, "MySQL RealTime: Updated %" PRIu64 " rows on table: %s\n", numrows, tablename);
    /* From http://dev.mysql.com/doc/mysql/en/mysql-affected-rows.html
     * An integer greater than zero indicates the number of rows affected
     * Zero indicates that no records were updated
     * -1 indicates that the query returned an error (although, if the query failed, it should have been caught above.)
    */
    return (int)numrows;
 }
update_mysql()
static int update_mysql (const char * database, const char * tablename, const char * keyfield, const char * lookup, const struct ast_variable * rt_fields) static
Definition at line 554 of file res_config_mysql.c.
References ast_debug, ast_log, ast_str_append(), ast_str_buffer(), ast_str_set(), ast_str_strlen(), ast_str_thread_get(), buf, ESCAPE_STRING, find_column(), find_database(), find_table(), LOG_ERROR, LOG_WARNING, mysql_reconnect(), ast_variable::name, ast_variable::next, NULL, release_database, release_table(), scratch_buf, sql_buf, table, and ast_variable::value.
 {
    struct mysql_conn *dbh;
    uint64_t numrows;
    const struct ast_variable *field = rt_fields;
    struct ast_str *sql = ast_str_thread_get(&sql_buf, 100), *buf = ast_str_thread_get(&scratch_buf, 100);
    struct tables *table;
    struct columns *column = NULL;
    if (!(dbh = find_database(database, 1))) {
       ast_log(LOG_WARNING, "MySQL RealTime: Invalid database specified: '%s' (check res_mysql.conf)\n", database);
       return -1;
    }
    if (!tablename) {
       ast_log(LOG_WARNING, "MySQL RealTime: No table specified.\n");
       release_database(dbh);
       return -1;
    }
    if (!(table = find_table(database, tablename))) {
       ast_log(LOG_ERROR, "Table '%s' does not exist!!\n", tablename);
       release_database(dbh);
       return -1;
    }
    if (!(column = find_column(table, keyfield))) {
       ast_log(LOG_ERROR, "MySQL RealTime: Updating on column '%s', but that column does not exist within the table '%s' (db '%s')!\n", keyfield, tablename, database);
       release_table(table);
       release_database(dbh);
       return -1;
    }
    /* Get the first parameter and first value in our list of passed paramater/value pairs */
    if (!field) {
       ast_log(LOG_WARNING, "MySQL RealTime: Realtime update requires at least 1 parameter and 1 value to update.\n");
       release_table(table);
       release_database(dbh);
       return -1;
    }
    /* Check that the column exists in the table */
    if (!(column = find_column(table, field->name))) {
       ast_log(LOG_ERROR, "MySQL RealTime: Updating column '%s', but that column does not exist within the table '%s' (first pair MUST exist)!\n", field->name, tablename);
       release_table(table);
       release_database(dbh);
       return -1;
    }
    /* Must connect to the server before anything else, as the escape function requires the mysql handle. */
    if (!mysql_reconnect(dbh)) {
       release_table(table);
       release_database(dbh);
       return -1;
    }
    /* Create the first part of the query using the first parameter/value pairs we just extracted
       If there is only 1 set, then we have our query. Otherwise, loop thru the list and concat */
    ESCAPE_STRING(buf, field->value);
    ast_str_set(&sql, 0, "UPDATE %s SET `%s` = '%s'", tablename, field->name, ast_str_buffer(buf));
    while ((field = field->next)) {
       /* If the column is not within the table, then skip it */
       if (!(column = find_column(table, field->name))) {
          ast_log(LOG_WARNING, "Attempted to update column '%s' in table '%s', but column does not exist!\n", field->name, tablename);
          continue;
       }
       ESCAPE_STRING(buf, field->value);
       ast_str_append(&sql, 0, ", `%s` = '%s'", field->name, ast_str_buffer(buf));
    }
    ESCAPE_STRING(buf, lookup);
    ast_str_append(&sql, 0, " WHERE `%s` = '%s'", keyfield, ast_str_buffer(buf));
    ast_debug(1, "MySQL RealTime: Update SQL: %s\n", ast_str_buffer(sql));
    /* Execution. */
    if (mysql_real_query(&dbh->handle, ast_str_buffer(sql), ast_str_strlen(sql))) {
       ast_log(LOG_WARNING, "MySQL RealTime: Failed to update database: %s\n", mysql_error(&dbh->handle));
       release_table(table);
       release_database(dbh);
       return -1;
    }
    numrows = mysql_affected_rows(&dbh->handle);
    release_table(table);
    release_database(dbh);
    ast_debug(1, "MySQL RealTime: Updated %" PRIu64 " rows on table: %s\n", numrows, tablename);
    /* From http://dev.mysql.com/doc/mysql/en/mysql-affected-rows.html
     * An integer greater than zero indicates the number of rows affected
     * Zero indicates that no records were updated
     * -1 indicates that the query returned an error (although, if the query failed, it should have been caught above.)
    */
    return (int)numrows;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "MySQL RealTime Configuration Driver" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_EXTENDED, .load = load_module, .unload = unload_module, .reload = reload, .load_pri = AST_MODPRI_REALTIME_DRIVER, .requires = "extconfig", } static
Definition at line 1563 of file res_config_mysql.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 1563 of file res_config_mysql.c.
cli_realtime_mysql_status
struct ast_cli_entry cli_realtime_mysql_status[] static
Initial value:
= {
   { .handler =  handle_cli_realtime_mysql_status , .summary =  "Shows connection information for the MySQL RealTime driver" ,},
   { .handler =  handle_cli_realtime_mysql_cache , .summary =  "Shows cached tables within the MySQL realtime driver" ,},
}
Definition at line 127 of file res_config_mysql.c.
databases
struct databases databases = { .first = NULL, .last = NULL, .lock = { PTHREAD_RWLOCK_INITIALIZER , NULL, {1, 0} } , } static
ESCAPE_CLAUSE
char* ESCAPE_CLAUSE = " ESCAPE '\\\\'" static
Definition at line 308 of file res_config_mysql.c.
Referenced by realtime_multi_mysql(), and realtime_mysql().
find_buf
struct ast_threadstorage find_buf = { .once = PTHREAD_ONCE_INIT , .key_init = __init_find_buf , .custom_init = NULL , } static
Definition at line 74 of file res_config_mysql.c.
Referenced by find_table().
modify2_buf
struct ast_threadstorage modify2_buf = { .once = PTHREAD_ONCE_INIT , .key_init = __init_modify2_buf , .custom_init = NULL , } static
Definition at line 78 of file res_config_mysql.c.
modify3_buf
struct ast_threadstorage modify3_buf = { .once = PTHREAD_ONCE_INIT , .key_init = __init_modify3_buf , .custom_init = NULL , } static
Definition at line 79 of file res_config_mysql.c.
modify_buf
struct ast_threadstorage modify_buf = { .once = PTHREAD_ONCE_INIT , .key_init = __init_modify_buf , .custom_init = NULL , } static
Definition at line 77 of file res_config_mysql.c.
mysql_engine
struct ast_config_engine mysql_engine static
Definition at line 1136 of file res_config_mysql.c.
mysql_tables
struct mysql_tables mysql_tables = { .first = NULL, .last = NULL, .lock = { PTHREAD_RECURSIVE_MUTEX_INITIALIZER_NP , NULL, {1, 0} } , } static
scratch2_buf
struct ast_threadstorage scratch2_buf = { .once = PTHREAD_ONCE_INIT , .key_init = __init_scratch2_buf , .custom_init = NULL , } static
Definition at line 76 of file res_config_mysql.c.
scratch_buf
struct ast_threadstorage scratch_buf = { .once = PTHREAD_ONCE_INIT , .key_init = __init_scratch_buf , .custom_init = NULL , } static
Definition at line 75 of file res_config_mysql.c.
Referenced by destroy_mysql(), realtime_multi_mysql(), realtime_mysql(), store_mysql(), update2_mysql(), and update_mysql().
sql2_buf
struct ast_threadstorage sql2_buf = { .once = PTHREAD_ONCE_INIT , .key_init = __init_sql2_buf , .custom_init = NULL , } static
Definition at line 73 of file res_config_mysql.c.
Referenced by store_mysql(), and update2_mysql().
sql_buf
struct ast_threadstorage sql_buf = { .once = PTHREAD_ONCE_INIT , .key_init = __init_sql_buf , .custom_init = NULL , } static
Definition at line 72 of file res_config_mysql.c.
Referenced by config_mysql(), destroy_mysql(), realtime_multi_mysql(), realtime_mysql(), store_mysql(), update2_mysql(), and update_mysql().