Asterisk - The Open Source Telephony Project: manager_mwi.c File Reference
manager_mwi.c File Reference
The Asterisk Management Interface - AMI (MWI event handling)
#include "asterisk.h"
#include "asterisk/manager.h"
#include "asterisk/app.h"
#include "asterisk/mwi.h"
#include "asterisk/channel.h"
#include "asterisk/stasis_message_router.h"
#include "asterisk/stasis.h"
Functions
static int exclude_event_cb (const char *key)
Callback function used by mwi_app_event_cb to weed out "Event" keys.
int manager_mwi_init (void)
Initialize support for AMI MWI events.
static void manager_mwi_shutdown (void)
static void mwi_app_event_cb (void *data, struct stasis_subscription *sub, struct stasis_message *message)
Generic MWI event callback used for one-off events from voicemail modules.
static void mwi_update_cb (void *data, struct stasis_subscription *sub, struct stasis_message *message)
Variables
struct stasis_message_router * mwi_state_router
static struct stasis_forward * topic_forwarder
The Stasis Message Bus API subscription returned by the forwarding of the MWI topic to the manager topic.
Detailed Description
The Asterisk Management Interface - AMI (MWI event handling)
Author
Matt Jordan mjord.nosp@m.an@d.nosp@m.igium.nosp@m..com
Definition in file manager_mwi.c.
Function Documentation
exclude_event_cb()
static int exclude_event_cb (const char * key) static
Callback function used by mwi_app_event_cb to weed out "Event" keys.
Definition at line 46 of file manager_mwi.c.
Referenced by mwi_app_event_cb().
 {
    if (!strcmp(key, "Event")) {
       return -1;
    }
    return 0;
 }
manager_mwi_init()
int manager_mwi_init (void)
Initialize support for AMI MWI events.
Since
12
Return values
0 on success
non-zero on error
Definition at line 153 of file manager_mwi.c.
References ast_manager_get_message_router(), ast_manager_get_topic(), ast_mwi_state_type(), ast_mwi_topic_all(), ast_mwi_vm_app_type(), ast_register_cleanup(), manager_mwi_shutdown(), manager_topic, mwi_app_event_cb(), mwi_update_cb(), NULL, stasis_forward_all(), and stasis_message_router_add().
Referenced by subscribe_all().
 {
    int ret = 0;
    struct stasis_topic *manager_topic;
    struct stasis_topic *mwi_topic;
    struct stasis_message_router *message_router;
    manager_topic = ast_manager_get_topic();
    if (!manager_topic) {
       return -1;
    }
    message_router = ast_manager_get_message_router();
    if (!message_router) {
       return -1;
    }
    mwi_topic = ast_mwi_topic_all();
    if (!mwi_topic) {
       return -1;
    }
    topic_forwarder = stasis_forward_all(mwi_topic, manager_topic);
    if (!topic_forwarder) {
       return -1;
    }
    ast_register_cleanup(manager_mwi_shutdown);
    ret |= stasis_message_router_add(message_router,
                 ast_mwi_state_type(),
                 mwi_update_cb,
                 NULL);
    ret |= stasis_message_router_add(message_router,
                 ast_mwi_vm_app_type(),
                 mwi_app_event_cb,
                 NULL);
    /* If somehow we failed to add any routes, just shut down the whole
     * thing and fail it.
     */
    if (ret) {
       manager_mwi_shutdown();
       return -1;
    }
    return 0;
 }
manager_mwi_shutdown()
static void manager_mwi_shutdown (void) static
Definition at line 147 of file manager_mwi.c.
References NULL, and stasis_forward_cancel().
Referenced by manager_mwi_init().
 {
    stasis_forward_cancel(topic_forwarder);
    topic_forwarder = NULL;
 }
mwi_app_event_cb()
static void mwi_app_event_cb (void * data, struct stasis_subscription * sub, struct stasis_message * message) static
Generic MWI event callback used for one-off events from voicemail modules.
Definition at line 55 of file manager_mwi.c.
References ast_free, ast_json_object_get(), ast_json_string_get(), ast_log, AST_LOG_WARNING, ast_manager_build_channel_state_string(), ast_manager_str_from_json_object(), ast_str_buffer(), ast_mwi_blob::blob, EVENT_FLAG_CALL, exclude_event_cb(), manager_event, ast_mwi_blob::mwi_state, NULL, RAII_VAR, ast_mwi_state::snapshot, stasis_message_data(), and ast_mwi_state::uniqueid.
Referenced by manager_mwi_init().
 {
    struct ast_mwi_blob *payload = stasis_message_data(message);
    RAII_VAR(struct ast_str *, channel_event_string, NULL, ast_free);
    RAII_VAR(struct ast_str *, event_buffer, NULL, ast_free);
    struct ast_json *event_json = ast_json_object_get(payload->blob, "Event");
    if (!event_json) {
       return;
    }
    if (payload->mwi_state && payload->mwi_state->snapshot) {
       channel_event_string = ast_manager_build_channel_state_string(payload->mwi_state->snapshot);
    }
    event_buffer = ast_manager_str_from_json_object(payload->blob, exclude_event_cb);
    if (!event_buffer) {
       ast_log(AST_LOG_WARNING, "Failed to create payload for event %s\n", ast_json_string_get(event_json));
       return;
    }
    manager_event(EVENT_FLAG_CALL, ast_json_string_get(event_json),
          "Mailbox: %s\r\n"
          "%s"
          "%s",
          payload->mwi_state ? payload->mwi_state->uniqueid : "Unknown",
          ast_str_buffer(event_buffer),
          channel_event_string ? ast_str_buffer(channel_event_string) : "");
 }
mwi_update_cb()
static void mwi_update_cb (void * data, struct stasis_subscription * sub, struct stasis_message * message) static
Definition at line 86 of file manager_mwi.c.
References AS_OR, ast_app_has_voicemail(), ast_free, ast_manager_build_channel_state_string(), ast_mwi_state_type(), EVENT_FLAG_CALL, manager_event, ast_mwi_state::new_msgs, NULL, ast_mwi_state::old_msgs, RAII_VAR, ast_mwi_state::snapshot, stasis_message_data(), stasis_message_type(), and ast_mwi_state::uniqueid.
Referenced by manager_mwi_init().
 {
    struct ast_mwi_state *mwi_state;
    RAII_VAR(struct ast_str *, channel_event_string, NULL, ast_free);
    if (ast_mwi_state_type() != stasis_message_type(message)) {
       return;
    }
    mwi_state = stasis_message_data(message);
    if (!mwi_state) {
       return;
    }
    if (mwi_state->snapshot) {
       channel_event_string = ast_manager_build_channel_state_string(mwi_state->snapshot);
    }
    /*** DOCUMENTATION
       <managerEventInstance>
          <synopsis>Raised when the state of messages in a voicemail mailbox
          has changed or when a channel has finished interacting with a
          mailbox.</synopsis>
          <syntax>
             <channel_snapshot/>
             <parameter name="Mailbox">
                <para>The mailbox with the new message, specified as <literal>mailbox</literal>@<literal>context</literal></para>
             </parameter>
             <parameter name="Waiting">
                <para>Whether or not the mailbox has messages waiting for it.</para>
             </parameter>
             <parameter name="New">
                <para>The number of new messages.</para>
             </parameter>
             <parameter name="Old">
                <para>The number of old messages.</para>
             </parameter>
          </syntax>
          <description>
             <note><para>The Channel related parameters are only present if a
             channel was involved in the manipulation of a mailbox. If no
             channel is involved, the parameters are not included with the
             event.</para>
             </note>
          </description>
       </managerEventInstance>
    ***/
    manager_event(EVENT_FLAG_CALL, "MessageWaiting",
          "%s"
          "Mailbox: %s\r\n"
          "Waiting: %d\r\n"
          "New: %d\r\n"
          "Old: %d\r\n",
          AS_OR(channel_event_string, ""),
          mwi_state->uniqueid,
          ast_app_has_voicemail(mwi_state->uniqueid, NULL),
          mwi_state->new_msgs,
          mwi_state->old_msgs);
 }
Variable Documentation
mwi_state_router
struct stasis_message_router* mwi_state_router
Definition at line 35 of file manager_mwi.c.
topic_forwarder
struct stasis_forward* topic_forwarder static
The Stasis Message Bus API subscription returned by the forwarding of the MWI topic to the manager topic.
Definition at line 43 of file manager_mwi.c.