Asterisk - The Open Source Telephony Project: cel_beanstalkd.c File Reference
cel_beanstalkd.c File Reference
Asterisk Channel Event Beanstalkd backend.
#include "asterisk.h"
#include "asterisk/channel.h"
#include "asterisk/cel.h"
#include "asterisk/module.h"
#include "asterisk/logger.h"
#include "asterisk/utils.h"
#include "asterisk/manager.h"
#include "asterisk/config.h"
#include "asterisk/json.h"
#include "beanstalk.h"
Macros
#define BEANSTALK_JOB_DELAY 0
#define BEANSTALK_JOB_PRIORITY 99
#define BEANSTALK_JOB_SIZE 4096
#define BEANSTALK_JOB_TTR 60
#define CEL_BACKEND_NAME "Beanstalk Event Logging"
#define CEL_BEANSTALK_ENABLED_DEFAULT 0
Beanstalk CEL is off by default.
#define CEL_SHOW_USERDEF_DEFAULT 0
show_user_def is off by default
#define DEFAULT_BEANSTALK_HOST "127.0.0.1"
#define DEFAULT_BEANSTALK_PORT 11300
#define DEFAULT_BEANSTALK_TUBE "asterisk-cel"
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static void cel_bs_put (struct ast_event *event)
static int load_config (int reload)
static int load_module (void)
static int reload (void)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Beanstalkd CEL Backend" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_EXTENDED, .load = load_module, .unload = unload_module, .reload = reload, .load_pri = AST_MODPRI_CDR_DRIVER, .requires = "cel", }
static const struct ast_module_info * ast_module_info = &__mod_info
static char * bs_host
static int bs_port
static char * bs_tube
static const char CONF_FILE [] = "cel_beanstalkd.conf"
static ast_rwlock_t config_lock = { PTHREAD_RWLOCK_INITIALIZER , NULL, {1, 0} }
static const char DATE_FORMAT [] = "%Y-%m-%d %T"
static int enablecel
static int priority
Detailed Description
Asterisk Channel Event Beanstalkd backend.
This module requires the beanstalk-client library, avaialble from https://github.com/deepfryed/beanstalk-client
See also
AstCEL
Definition in file cel_beanstalkd.c.
Macro Definition Documentation
BEANSTALK_JOB_DELAY
#define BEANSTALK_JOB_DELAY 0
Definition at line 77 of file cel_beanstalkd.c.
Referenced by cel_bs_put().
BEANSTALK_JOB_PRIORITY
#define BEANSTALK_JOB_PRIORITY 99
Definition at line 75 of file cel_beanstalkd.c.
Referenced by load_config().
BEANSTALK_JOB_SIZE
#define BEANSTALK_JOB_SIZE 4096
Definition at line 74 of file cel_beanstalkd.c.
BEANSTALK_JOB_TTR
#define BEANSTALK_JOB_TTR 60
Definition at line 76 of file cel_beanstalkd.c.
Referenced by cel_bs_put().
CEL_BACKEND_NAME
#define CEL_BACKEND_NAME "Beanstalk Event Logging"
Definition at line 72 of file cel_beanstalkd.c.
Referenced by load_config(), and unload_module().
CEL_BEANSTALK_ENABLED_DEFAULT
#define CEL_BEANSTALK_ENABLED_DEFAULT 0
Beanstalk CEL is off by default.
Definition at line 65 of file cel_beanstalkd.c.
Referenced by load_config().
CEL_SHOW_USERDEF_DEFAULT
#define CEL_SHOW_USERDEF_DEFAULT 0
show_user_def is off by default
Definition at line 70 of file cel_beanstalkd.c.
DEFAULT_BEANSTALK_HOST
#define DEFAULT_BEANSTALK_HOST "127.0.0.1"
Definition at line 78 of file cel_beanstalkd.c.
Referenced by load_config().
DEFAULT_BEANSTALK_PORT
#define DEFAULT_BEANSTALK_PORT 11300
Definition at line 79 of file cel_beanstalkd.c.
Referenced by load_config().
DEFAULT_BEANSTALK_TUBE
#define DEFAULT_BEANSTALK_TUBE "asterisk-cel"
Definition at line 80 of file cel_beanstalkd.c.
Referenced by load_config().
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 276 of file cel_beanstalkd.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 276 of file cel_beanstalkd.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 276 of file cel_beanstalkd.c.
cel_bs_put()
static void cel_bs_put (struct ast_event * event) static
Definition at line 89 of file cel_beanstalkd.c.
References ast_cel_event_record::account_code, ast_cel_event_record::amaflag, ast_cel_event_record::application_data, ast_cel_event_record::application_name, AST_CEL_EVENT_RECORD_VERSION, ast_cel_fill_record(), ast_channel_amaflags2string(), ast_json_dump_string, ast_json_free(), ast_json_pack(), ast_json_unref(), ast_localtime(), ast_log, ast_rwlock_rdlock, ast_rwlock_unlock, ast_strftime(), BEANSTALK_JOB_DELAY, BEANSTALK_JOB_TTR, bs_host, bs_port, bs_tube, ast_cel_event_record::caller_id_ani, ast_cel_event_record::caller_id_dnid, ast_cel_event_record::caller_id_name, ast_cel_event_record::caller_id_num, ast_cel_event_record::caller_id_rdnis, ast_cel_event_record::channel_name, config_lock, ast_cel_event_record::context, DATE_FORMAT, enablecel, ast_cel_event_record::event_name, ast_cel_event_record::event_time, ast_cel_event_record::extension, ast_cel_event_record::extra, ast_cel_event_record::linked_id, LOG_DEBUG, LOG_ERROR, NULL, ast_cel_event_record::peer_account, priority, S_OR, ast_cel_event_record::unique_id, ast_cel_event_record::user_field, and ast_cel_event_record::version.
Referenced by load_config().
 {
    struct ast_tm timeresult;
    char start_time[80];
    char *cel_buffer;
    int bs_id;
    int bs_socket;
    struct ast_json *t_cel_json;
    struct ast_cel_event_record record = {
       .version = AST_CEL_EVENT_RECORD_VERSION,
    };
    if (!enablecel) {
       return;
    }
    if (ast_cel_fill_record(event, &record)) {
       return;
    }
    ast_rwlock_rdlock(&config_lock);
    bs_socket = bs_connect(bs_host, bs_port);
    if (bs_use(bs_socket, bs_tube) != BS_STATUS_OK) {
       ast_log(LOG_ERROR, "Connection to Beanstalk tube %s @ %s:%d had failed", bs_tube, bs_host, bs_port);
       ast_rwlock_unlock(&config_lock);
       return;
    }
    ast_localtime(&record.event_time, &timeresult, NULL);
    ast_strftime(start_time, sizeof(start_time), DATE_FORMAT, &timeresult);
    ast_rwlock_unlock(&config_lock);
    t_cel_json = ast_json_pack("{s:s, s:s, s:s, s:s, s:s, s:s, s:s, s:s, s:s, s:s, s:s, s:s, s:s, s:s, s:s, s:s, s:s, s:s, s:s, s:s}",
                         "EventName", S_OR(record.event_name, ""),
                         "AccountCode", S_OR(record.account_code, ""),
                         "CallerIDnum", S_OR(record.caller_id_num, ""),
                         "CallerIDname", S_OR(record.caller_id_name, ""),
                         "CallerIDani", S_OR(record.caller_id_ani, ""),
                         "CallerIDrdnis", S_OR(record.caller_id_rdnis, ""),
                         "CallerIDdnid", S_OR(record.caller_id_dnid, ""),
                         "Exten", S_OR(record.extension, ""),
                         "Context", S_OR(record.context, ""),
                         "Channel", S_OR(record.channel_name, ""),
                         "Application", S_OR(record.application_name, ""),
                         "AppData", S_OR(record.application_data, ""),
                         "EventTime", S_OR(start_time, ""),
                         "AMAFlags", S_OR(ast_channel_amaflags2string(record.amaflag), ""),
                         "UniqueID", S_OR(record.unique_id, ""),
                         "LinkedID", S_OR(record.linked_id, ""),
                         "Userfield", S_OR(record.user_field, ""),
                         "Peer", S_OR(record.peer_account, ""),
                         "PeerAccount", S_OR(record.peer_account, ""),
                         "Extra", S_OR(record.extra, "")
    );
    cel_buffer = ast_json_dump_string(t_cel_json);
    ast_json_unref(t_cel_json);
    bs_id = bs_put(bs_socket, priority, BEANSTALK_JOB_DELAY, BEANSTALK_JOB_TTR, cel_buffer, strlen(cel_buffer));
    if (bs_id > 0) {
       ast_log(LOG_DEBUG, "Successfully created job %d with %s\n", bs_id, cel_buffer);
    } else {
       ast_log(LOG_ERROR, "CDR job creation failed for %s\n", cel_buffer);
    }
    bs_disconnect(bs_socket);
    ast_json_free(cel_buffer);
 }
load_config()
static int load_config (int reload) static
Definition at line 164 of file cel_beanstalkd.c.
References ast_category_browse(), ast_cel_backend_register(), ast_cel_backend_unregister(), ast_config_destroy(), ast_config_load, ast_free, ast_log, ast_rwlock_unlock, ast_rwlock_wrlock, ast_strdup, ast_true(), ast_variable_browse(), BEANSTALK_JOB_PRIORITY, bs_host, bs_port, bs_tube, CEL_BACKEND_NAME, CEL_BEANSTALK_ENABLED_DEFAULT, cel_bs_put(), CONF_FILE, CONFIG_FLAG_FILEUNCHANGED, config_lock, CONFIG_STATUS_FILEINVALID, CONFIG_STATUS_FILEUNCHANGED, DEFAULT_BEANSTALK_HOST, DEFAULT_BEANSTALK_PORT, DEFAULT_BEANSTALK_TUBE, enablecel, LOG_ERROR, LOG_NOTICE, LOG_WARNING, ast_variable::name, ast_variable::next, NULL, priority, and ast_variable::value.
Referenced by load_module(), and reload().
 {
    const char *cat = NULL;
    struct ast_config *cfg;
    struct ast_flags config_flags = { reload ? CONFIG_FLAG_FILEUNCHANGED : 0 };
    struct ast_variable *v;
    int newenablecel = CEL_BEANSTALK_ENABLED_DEFAULT;
    cfg = ast_config_load(CONF_FILE, config_flags);
    if (cfg == CONFIG_STATUS_FILEUNCHANGED) {
       return 0;
    }
    if (cfg == CONFIG_STATUS_FILEINVALID) {
       ast_log(LOG_WARNING, "Configuration file '%s' is invalid. CEL Beanstalkd Module not activated.\n",
          CONF_FILE);
       return -1;
    } else if (!cfg) {
       ast_log(LOG_WARNING, "Failed to load configuration file. CEL Beanstalkd Module not activated.\n");
       if (enablecel) {
          ast_cel_backend_unregister(CEL_BACKEND_NAME);
       }
       enablecel = 0;
       return -1;
    }
    if (reload) {
       ast_rwlock_wrlock(&config_lock);
       ast_free(bs_host);
       ast_free(bs_tube);
    }
    /* Bootstrap the default configuration */
    bs_host = ast_strdup(DEFAULT_BEANSTALK_HOST);
    bs_port = DEFAULT_BEANSTALK_PORT;
    bs_tube = ast_strdup(DEFAULT_BEANSTALK_TUBE);
    priority = BEANSTALK_JOB_PRIORITY;
    while ((cat = ast_category_browse(cfg, cat))) {
       if (strcasecmp(cat, "general")) {
          continue;
       }
       for (v = ast_variable_browse(cfg, cat); v; v = v->next) {
          if (!strcasecmp(v->name, "enabled")) {
             newenablecel = ast_true(v->value) ? 1 : 0;
          } else if (!strcasecmp(v->name, "host")) {
             ast_free(bs_host);
             bs_host = ast_strdup(v->value);
          } else if (!strcasecmp(v->name, "port")) {
             bs_port = atoi(v->value);
          } else if (!strcasecmp(v->name, "tube")) {
             ast_free(bs_tube);
             bs_tube = ast_strdup(v->value);
          } else if (!strcasecmp(v->name, "priority")) {
             priority = atoi(v->value);
          } else {
             ast_log(LOG_NOTICE, "Unknown option '%s' specified "
                   "for CEL beanstalk backend.\n", v->name);
          }
       }
    }
    if (reload) {
       ast_rwlock_unlock(&config_lock);
    }
    ast_config_destroy(cfg);
    if (enablecel && !newenablecel) {
       ast_cel_backend_unregister(CEL_BACKEND_NAME);
    } else if (!enablecel && newenablecel) {
       if (ast_cel_backend_register(CEL_BACKEND_NAME, cel_bs_put)) {
          ast_log(LOG_ERROR, "Unable to register Beanstalkd CEL handling\n");
       }
    }
    enablecel = newenablecel;
    return 0;
 }
load_module()
static int load_module (void) static
Definition at line 255 of file cel_beanstalkd.c.
References AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, and load_config().
Referenced by reload().
 {
    if (load_config(0)) {
       return AST_MODULE_LOAD_DECLINE;
    }
    return AST_MODULE_LOAD_SUCCESS;
 }
reload()
static int reload (void) static
Definition at line 264 of file cel_beanstalkd.c.
References AST_MODFLAG_LOAD_ORDER, AST_MODPRI_CDR_DRIVER, AST_MODULE_INFO(), AST_MODULE_SUPPORT_EXTENDED, ASTERISK_GPL_KEY, load_config(), load_module(), and unload_module().
 {
    return load_config(1);
 }
unload_module()
static int unload_module (void) static
Definition at line 247 of file cel_beanstalkd.c.
References ast_cel_backend_unregister(), ast_free, bs_host, bs_tube, and CEL_BACKEND_NAME.
Referenced by reload().
 {
    ast_cel_backend_unregister(CEL_BACKEND_NAME);
    ast_free(bs_host);
    ast_free(bs_tube);
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Beanstalkd CEL Backend" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_EXTENDED, .load = load_module, .unload = unload_module, .reload = reload, .load_pri = AST_MODPRI_CDR_DRIVER, .requires = "cel", } static
Definition at line 276 of file cel_beanstalkd.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 276 of file cel_beanstalkd.c.
bs_host
char* bs_host static
Definition at line 82 of file cel_beanstalkd.c.
Referenced by cel_bs_put(), load_config(), and unload_module().
bs_port
int bs_port static
Definition at line 83 of file cel_beanstalkd.c.
Referenced by cel_bs_put(), and load_config().
bs_tube
char* bs_tube static
Definition at line 84 of file cel_beanstalkd.c.
Referenced by cel_bs_put(), load_config(), and unload_module().
CONF_FILE
const char CONF_FILE[] = "cel_beanstalkd.conf" static
Definition at line 62 of file cel_beanstalkd.c.
Referenced by load_config().
config_lock
ast_rwlock_t config_lock = { PTHREAD_RWLOCK_INITIALIZER , NULL, {1, 0} } static
Definition at line 87 of file cel_beanstalkd.c.
Referenced by cel_bs_put(), and load_config().
DATE_FORMAT
const char DATE_FORMAT[] = "%Y-%m-%d %T" static
Definition at line 60 of file cel_beanstalkd.c.
Referenced by cel_bs_put().
enablecel
int enablecel static
Definition at line 67 of file cel_beanstalkd.c.
Referenced by cel_bs_put(), and load_config().
priority
int priority static
Definition at line 85 of file cel_beanstalkd.c.
Referenced by cel_bs_put(), and load_config().