Asterisk - The Open Source Telephony Project: stasis_message_sanitizer Struct Reference
stasis_message_sanitizer Struct Reference
Structure containing callbacks for Stasis message sanitization.
#include <stasis.h>
Data Fields
int(* channel)(const struct ast_channel *chan)
Callback which determines whether a channel should be sanitized from a message based on the channel.
int(* channel_id)(const char *channel_id)
Callback which determines whether a channel should be sanitized from a message based on the channel's unique ID.
int(* channel_snapshot)(const struct ast_channel_snapshot *snapshot)
Callback which determines whether a channel should be sanitized from a message based on the channel's snapshot.
Detailed Description
Structure containing callbacks for Stasis message sanitization.
Note
If either callback is implemented, both should be implemented since not all callers may have access to the full snapshot.
Definition at line 200 of file stasis.h.
Field Documentation
channel
int(* channel) (const struct ast_channel *chan)
Callback which determines whether a channel should be sanitized from a message based on the channel.
Parameters
chan The channel to be checked
Return values
non-zero if the channel should be left out of the message
zero if the channel should remain in the message
Definition at line 232 of file stasis.h.
Referenced by app_send_end_msg().
channel_id
int(* channel_id) (const char *channel_id)
Callback which determines whether a channel should be sanitized from a message based on the channel's unique ID.
Parameters
channel_id The unique ID of the channel
Return values
non-zero if the channel should be left out of the message
zero if the channel should remain in the message
Definition at line 210 of file stasis.h.
Referenced by ast_endpoint_snapshot_to_json(), and container_to_json_array().
channel_snapshot
int(* channel_snapshot) (const struct ast_channel_snapshot *snapshot)
Callback which determines whether a channel should be sanitized from a message based on the channel's snapshot.
Parameters
snapshot A snapshot generated from the channel
Return values
non-zero if the channel should be left out of the message
zero if the channel should remain in the message
Definition at line 221 of file stasis.h.
Referenced by ast_ari_channels_list(), ast_channel_snapshot_to_json(), stasis_end_to_json(), and stasis_start_to_json().
The documentation for this struct was generated from the following file:
stasis.h