Asterisk - The Open Source Telephony Project: test_http_media_cache.c File Reference
test_http_media_cache.c File Reference
Tests for the HTTP media cache backend.
#include "asterisk.h"
#include <fcntl.h>
#include "asterisk/module.h"
#include "asterisk/http.h"
#include "asterisk/bucket.h"
#include "asterisk/test.h"
Data Structures
struct test_options
Macros
#define CATEGORY "/res/http_media_cache/"
#define SET_OR_APPEND_CACHE_CONTROL(str)
#define TEST_URI "test_media_cache"
#define VALIDATE_EXPIRES(test, bucket_file, expected, delta)
#define VALIDATE_STR_METADATA(test, bucket_file, key, expected)
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
AST_TEST_DEFINE (retrieve_cache_control_directives)
AST_TEST_DEFINE (retrieve_cache_control_age)
AST_TEST_DEFINE (retrieve_etag_expired)
AST_TEST_DEFINE (retrieve_expires)
AST_TEST_DEFINE (retrieve_etag)
AST_TEST_DEFINE (retrieve_nominal)
AST_TEST_DEFINE (create_nominal)
static void bucket_file_cleanup (void *obj)
static int http_callback (struct ast_tcptls_session_instance *ser, const struct ast_http_uri *urih, const char *uri, enum ast_http_method method, struct ast_variable *get_params, struct ast_variable *headers)
static int load_module (void)
static int pre_test_cb (struct ast_test_info *info, struct ast_test *test)
static int process_config (int reload)
static int reload_module (void)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_DEFAULT , .description = "HTTP Media Cache Backend Tests" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .reload = reload_module, .unload = unload_module, .requires = "res_http_media_cache", }
static const struct ast_module_info * ast_module_info = &__mod_info
static struct test_options options
static char server_uri [512]
static struct ast_http_uri test_uri
Detailed Description
Tests for the HTTP media cache backend.
Author
Matt Jordan <mjordan@digium.com>
Definition in file test_http_media_cache.c.
Macro Definition Documentation
CATEGORY
#define CATEGORY "/res/http_media_cache/"
Definition at line 44 of file test_http_media_cache.c.
Referenced by AST_TEST_DEFINE(), and load_module().
SET_OR_APPEND_CACHE_CONTROL
#define SET_OR_APPEND_CACHE_CONTROL (str)
Definition at line 83 of file test_http_media_cache.c.
Referenced by http_callback().
TEST_URI
#define TEST_URI "test_media_cache"
Definition at line 46 of file test_http_media_cache.c.
Referenced by process_config().
VALIDATE_EXPIRES
#define VALIDATE_EXPIRES (test, bucket_file, expected, delta)
Definition at line 66 of file test_http_media_cache.c.
Referenced by AST_TEST_DEFINE().
VALIDATE_STR_METADATA
#define VALIDATE_STR_METADATA (test, bucket_file, key, expected)
Value:
do { \
   RAII_VAR(struct ast_bucket_metadata *, metadata, ast_bucket_file_metadata_get((bucket_file), (key)), ao2_cleanup); \
   ast_test_validate(test, metadata != NULL); \
   ast_test_validate(test, !strcmp(metadata->value, (expected))); \
} while (0)
Definition at line 77 of file test_http_media_cache.c.
Referenced by AST_TEST_DEFINE().
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 701 of file test_http_media_cache.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 701 of file test_http_media_cache.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 701 of file test_http_media_cache.c.
AST_TEST_DEFINE() [1/7]
AST_TEST_DEFINE (retrieve_cache_control_directives)
Definition at line 223 of file test_http_media_cache.c.
References ast_bucket_file_is_stale(), ast_bucket_file_retrieve(), AST_TEST_NOT_RUN, AST_TEST_PASS, ast_test_status_update, ast_tvnow(), bucket_file_cleanup(), test_options::cache_control, CATEGORY, test_options::etag, sip_to_pjsip::info(), test_options::maxage, test_options::must_revalidate, test_options::no_cache, NULL, options, RAII_VAR, test_options::send_file, server_uri, test_options::status_code, test_options::status_text, TEST_EXECUTE, TEST_INIT, and VALIDATE_EXPIRES.
 {
    RAII_VAR(struct ast_bucket_file *, bucket_file, NULL, bucket_file_cleanup);
    struct timeval now = ast_tvnow();
    char uri[1024];
    switch (cmd) {
    case TEST_INIT:
       info->name = __func__;
       info->category = CATEGORY;
       info->summary = "Test retrieval of a resource with Cache-Control directives that affect staleness";
       info->description =
          "This test covers retrieval of a resource with the Cache-Control header,\n"
          "which specifies no-cache and/or must-revalidate.";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    snprintf(uri, sizeof(uri), "%s/%s", server_uri, "foo.wav");
    options.send_file = 1;
    options.status_code = 200;
    options.status_text = "OK";
    ast_test_status_update(test, "Testing no-cache...\n");
    options.cache_control.no_cache = 1;
    bucket_file = ast_bucket_file_retrieve(uri);
    ast_test_validate(test, bucket_file != NULL);
    ast_test_validate(test, ast_bucket_file_is_stale(bucket_file) == 1);
    bucket_file_cleanup(bucket_file);
    ast_test_status_update(test, "Testing no-cache with ETag...\n");
    options.cache_control.no_cache = 1;
    options.etag = "123456789";
    bucket_file = ast_bucket_file_retrieve(uri);
    ast_test_validate(test, bucket_file != NULL);
    ast_test_validate(test, ast_bucket_file_is_stale(bucket_file) == 0);
    bucket_file_cleanup(bucket_file);
    options.etag = NULL;
    ast_test_status_update(test, "Testing no-cache with max-age...\n");
    options.cache_control.no_cache = 1;
    options.cache_control.maxage = 300;
    bucket_file = ast_bucket_file_retrieve(uri);
    ast_test_validate(test, bucket_file != NULL);
    VALIDATE_EXPIRES(test, bucket_file, now.tv_sec + 300, 3);
    ast_test_validate(test, ast_bucket_file_is_stale(bucket_file) == 1);
    bucket_file_cleanup(bucket_file);
    options.cache_control.maxage = 0;
    options.cache_control.no_cache = 0;
    ast_test_status_update(test, "Testing must-revalidate...\n");
    options.cache_control.must_revalidate = 1;
    bucket_file = ast_bucket_file_retrieve(uri);
    ast_test_validate(test, bucket_file != NULL);
    ast_test_validate(test, ast_bucket_file_is_stale(bucket_file) == 1);
    bucket_file_cleanup(bucket_file);
    ast_test_status_update(test, "Testing must-revalidate with ETag...\n");
    options.cache_control.must_revalidate = 1;
    options.etag = "123456789";
    bucket_file = ast_bucket_file_retrieve(uri);
    ast_test_validate(test, bucket_file != NULL);
    ast_test_validate(test, ast_bucket_file_is_stale(bucket_file) == 0);
    bucket_file_cleanup(bucket_file);
    options.etag = NULL;
    ast_test_status_update(test, "Testing must-revalidate with max-age...\n");
    options.cache_control.must_revalidate = 1;
    options.cache_control.maxage = 300;
    bucket_file = ast_bucket_file_retrieve(uri);
    ast_test_validate(test, bucket_file != NULL);
    VALIDATE_EXPIRES(test, bucket_file, now.tv_sec + 300, 3);
    ast_test_validate(test, ast_bucket_file_is_stale(bucket_file) == 1);
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [2/7]
AST_TEST_DEFINE (retrieve_cache_control_age)
Definition at line 305 of file test_http_media_cache.c.
References ast_bucket_file_is_stale(), ast_bucket_file_retrieve(), AST_TEST_NOT_RUN, AST_TEST_PASS, ast_test_status_update, ast_tvnow(), bucket_file_cleanup(), test_options::cache_control, CATEGORY, test_options::expires, sip_to_pjsip::info(), test_options::maxage, NULL, options, RAII_VAR, test_options::s_maxage, test_options::send_file, server_uri, test_options::status_code, test_options::status_text, TEST_EXECUTE, TEST_INIT, and VALIDATE_EXPIRES.
 {
    RAII_VAR(struct ast_bucket_file *, bucket_file, NULL, bucket_file_cleanup);
    struct timeval now = ast_tvnow();
    char uri[1024];
    switch (cmd) {
    case TEST_INIT:
       info->name = __func__;
       info->category = CATEGORY;
       info->summary = "Test retrieval of a resource with age specifiers in Cache-Control";
       info->description =
          "This test covers retrieval of a resource with the Cache-Control header,\n"
          "which specifies max-age and/or s-maxage. The test verifies proper precedence\n"
          "ordering of the header attributes, along with its relation if the Expires\n"
          "header is present.";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    snprintf(uri, sizeof(uri), "%s/%s", server_uri, "foo.wav");
    options.send_file = 1;
    options.status_code = 200;
    options.status_text = "OK";
    ast_test_status_update(test, "Testing max-age...\n");
    options.cache_control.maxage = 300;
    bucket_file = ast_bucket_file_retrieve(uri);
    ast_test_validate(test, bucket_file != NULL);
    VALIDATE_EXPIRES(test, bucket_file, now.tv_sec + 300, 3);
    ast_test_validate(test, ast_bucket_file_is_stale(bucket_file) == 0);
    bucket_file_cleanup(bucket_file);
    ast_test_status_update(test, "Testing s-maxage...\n");
    now = ast_tvnow();
    options.cache_control.maxage = 0;
    options.cache_control.s_maxage = 300;
    bucket_file = ast_bucket_file_retrieve(uri);
    ast_test_validate(test, bucket_file != NULL);
    VALIDATE_EXPIRES(test, bucket_file, now.tv_sec + 300, 3);
    ast_test_validate(test, ast_bucket_file_is_stale(bucket_file) == 0);
    bucket_file_cleanup(bucket_file);
    ast_test_status_update(test, "Testing max-age and s-maxage...\n");
    now = ast_tvnow();
    options.cache_control.maxage = 300;
    options.cache_control.s_maxage = 600;
    bucket_file = ast_bucket_file_retrieve(uri);
    ast_test_validate(test, bucket_file != NULL);
    VALIDATE_EXPIRES(test, bucket_file, now.tv_sec + 600, 3);
    ast_test_validate(test, ast_bucket_file_is_stale(bucket_file) == 0);
    bucket_file_cleanup(bucket_file);
    ast_test_status_update(test, "Testing max-age and Expires...\n");
    now = ast_tvnow();
    options.cache_control.maxage = 300;
    options.cache_control.s_maxage = 0;
    options.expires.tv_sec = now.tv_sec + 3000;
    bucket_file = ast_bucket_file_retrieve(uri);
    ast_test_validate(test, bucket_file != NULL);
    VALIDATE_EXPIRES(test, bucket_file, now.tv_sec + 300, 3);
    ast_test_validate(test, ast_bucket_file_is_stale(bucket_file) == 0);
    bucket_file_cleanup(bucket_file);
    ast_test_status_update(test, "Testing s-maxage and Expires...\n");
    now = ast_tvnow();
    options.cache_control.maxage = 0;
    options.cache_control.s_maxage = 300;
    options.expires.tv_sec = now.tv_sec + 3000;
    bucket_file = ast_bucket_file_retrieve(uri);
    ast_test_validate(test, bucket_file != NULL);
    VALIDATE_EXPIRES(test, bucket_file, now.tv_sec + 300, 3);
    ast_test_validate(test, ast_bucket_file_is_stale(bucket_file) == 0);
    bucket_file_cleanup(bucket_file);
    ast_test_status_update(test, "Testing s-maxage and Expires...\n");
    now = ast_tvnow();
    options.cache_control.maxage = 0;
    options.cache_control.s_maxage = 300;
    options.expires.tv_sec = now.tv_sec + 3000;
    bucket_file = ast_bucket_file_retrieve(uri);
    ast_test_validate(test, bucket_file != NULL);
    VALIDATE_EXPIRES(test, bucket_file, now.tv_sec + 300, 3);
    ast_test_validate(test, ast_bucket_file_is_stale(bucket_file) == 0);
    bucket_file_cleanup(bucket_file);
    ast_test_status_update(test, "Testing max-age, s-maxage, and Expires...\n");
    now = ast_tvnow();
    options.cache_control.maxage = 300;
    options.cache_control.s_maxage = 600;
    options.expires.tv_sec = now.tv_sec + 3000;
    bucket_file = ast_bucket_file_retrieve(uri);
    ast_test_validate(test, bucket_file != NULL);
    VALIDATE_EXPIRES(test, bucket_file, now.tv_sec + 600, 3);
    ast_test_validate(test, ast_bucket_file_is_stale(bucket_file) == 0);
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [3/7]
AST_TEST_DEFINE (retrieve_etag_expired)
Definition at line 406 of file test_http_media_cache.c.
References ast_bucket_file_is_stale(), ast_bucket_file_retrieve(), ast_sorcery_object_get_id(), ast_strlen_zero, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_tvnow(), bucket_file_cleanup(), CATEGORY, test_options::etag, test_options::expires, sip_to_pjsip::info(), NULL, options, RAII_VAR, test_options::send_file, server_uri, test_options::status_code, test_options::status_text, TEST_EXECUTE, TEST_INIT, VALIDATE_EXPIRES, and VALIDATE_STR_METADATA.
 {
    RAII_VAR(struct ast_bucket_file *, bucket_file, NULL, bucket_file_cleanup);
    struct timeval now = ast_tvnow();
    char uri[1024];
    switch (cmd) {
    case TEST_INIT:
       info->name = __func__;
       info->category = CATEGORY;
       info->summary = "Test retrieval of an expired resource with an ETag";
       info->description =
          "This test covers a staleness check of a resource with an ETag\n"
          "that has also expired. It guarantees that even if a resource\n"
          "is expired, we will still not consider it stale if the resource\n"
          "has not changed per the ETag value.";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    options.send_file = 1;
    options.status_code = 200;
    options.status_text = "OK";
    options.etag = "123456789";
    options.expires.tv_sec = now.tv_sec - 1;
    snprintf(uri, sizeof(uri), "%s/%s", server_uri, "foo.wav");
    bucket_file = ast_bucket_file_retrieve(uri);
    ast_test_validate(test, bucket_file != NULL);
    ast_test_validate(test, !strcmp(uri, ast_sorcery_object_get_id(bucket_file)));
    ast_test_validate(test, !ast_strlen_zero(bucket_file->path));
    VALIDATE_STR_METADATA(test, bucket_file, "etag", options.etag);
    VALIDATE_EXPIRES(test, bucket_file, now.tv_sec - 1, 3);
    ast_test_validate(test, ast_bucket_file_is_stale(bucket_file) == 0);
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [4/7]
AST_TEST_DEFINE (retrieve_expires)
Definition at line 447 of file test_http_media_cache.c.
References ast_bucket_file_is_stale(), ast_bucket_file_retrieve(), ast_sorcery_object_get_id(), ast_strlen_zero, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_tvnow(), bucket_file_cleanup(), CATEGORY, test_options::expires, sip_to_pjsip::info(), NULL, options, RAII_VAR, test_options::send_file, server_uri, test_options::status_code, test_options::status_text, TEST_EXECUTE, TEST_INIT, and VALIDATE_EXPIRES.
 {
    RAII_VAR(struct ast_bucket_file *, bucket_file, NULL, bucket_file_cleanup);
    struct timeval now = ast_tvnow();
    char uri[1024];
    switch (cmd) {
    case TEST_INIT:
       info->name = __func__;
       info->category = CATEGORY;
       info->summary = "Test retrieval with explicit expiration";
       info->description =
          "This test covers retrieving a resource that has an Expires.\n"
          "After retrieval of the resource, staleness is checked. With\n"
          "a non-expired resource, we expect the resource to not be stale.\n"
          "When the expiration has occurred, we expect the staleness check\n"
          "to fail.";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    options.send_file = 1;
    options.status_code = 200;
    options.status_text = "OK";
    options.expires.tv_sec = now.tv_sec + 3000;
    snprintf(uri, sizeof(uri), "%s/%s", server_uri, "foo.wav");
    bucket_file = ast_bucket_file_retrieve(uri);
    ast_test_validate(test, bucket_file != NULL);
    ast_test_validate(test, !strcmp(uri, ast_sorcery_object_get_id(bucket_file)));
    ast_test_validate(test, !ast_strlen_zero(bucket_file->path));
    VALIDATE_EXPIRES(test, bucket_file, now.tv_sec + 3000, 3);
    ast_test_validate(test, ast_bucket_file_is_stale(bucket_file) == 0);
    /* Clean up previous result */
    bucket_file_cleanup(bucket_file);
    options.expires.tv_sec = now.tv_sec - 1;
    bucket_file = ast_bucket_file_retrieve(uri);
    ast_test_validate(test, bucket_file != NULL);
    VALIDATE_EXPIRES(test, bucket_file, now.tv_sec - 1, 3);
    ast_test_validate(test, ast_bucket_file_is_stale(bucket_file) == 1);
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [5/7]
AST_TEST_DEFINE (retrieve_etag)
Definition at line 497 of file test_http_media_cache.c.
References ast_bucket_file_is_stale(), ast_bucket_file_retrieve(), ast_sorcery_object_get_id(), ast_strlen_zero, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_tvnow(), bucket_file_cleanup(), CATEGORY, test_options::etag, sip_to_pjsip::info(), NULL, options, RAII_VAR, test_options::send_file, server_uri, test_options::status_code, test_options::status_text, TEST_EXECUTE, TEST_INIT, VALIDATE_EXPIRES, and VALIDATE_STR_METADATA.
 {
    RAII_VAR(struct ast_bucket_file *, bucket_file, NULL, bucket_file_cleanup);
    struct timeval now = ast_tvnow();
    char uri[1024];
    switch (cmd) {
    case TEST_INIT:
       info->name = __func__;
       info->category = CATEGORY;
       info->summary = "Test retrieval with an ETag";
       info->description =
          "This test covers retrieving a resource that has an ETag.\n"
          "After retrieval of the resource, staleness is checked. With\n"
          "matching ETags, we expect the resource to not be stale. When\n"
          "the ETag does not match, we expect the resource to be stale.";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    options.send_file = 1;
    options.status_code = 200;
    options.status_text = "OK";
    options.etag = "123456789";
    snprintf(uri, sizeof(uri), "%s/%s", server_uri, "foo.wav");
    bucket_file = ast_bucket_file_retrieve(uri);
    ast_test_validate(test, bucket_file != NULL);
    ast_test_validate(test, !strcmp(uri, ast_sorcery_object_get_id(bucket_file)));
    ast_test_validate(test, !ast_strlen_zero(bucket_file->path));
    VALIDATE_STR_METADATA(test, bucket_file, "etag", options.etag);
    VALIDATE_EXPIRES(test, bucket_file, now.tv_sec, 3);
    ast_test_validate(test, ast_bucket_file_is_stale(bucket_file) == 0);
    options.etag = "99999999";
    ast_test_validate(test, ast_bucket_file_is_stale(bucket_file) == 1);
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [6/7]
AST_TEST_DEFINE (retrieve_nominal)
Definition at line 540 of file test_http_media_cache.c.
References ast_bucket_file_retrieve(), ast_sorcery_object_get_id(), ast_strlen_zero, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_tvnow(), bucket_file_cleanup(), CATEGORY, sip_to_pjsip::info(), NULL, options, RAII_VAR, test_options::send_file, server_uri, test_options::status_code, test_options::status_text, TEST_EXECUTE, TEST_INIT, and VALIDATE_EXPIRES.
 {
    RAII_VAR(struct ast_bucket_file *, bucket_file, NULL, bucket_file_cleanup);
    struct timeval now = ast_tvnow();
    char uri[1024];
    switch (cmd) {
    case TEST_INIT:
       info->name = __func__;
       info->category = CATEGORY;
       info->summary = "Test nominal retrieval";
       info->description =
          "Test nominal retrieval of a resource.";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    options.send_file = 1;
    options.status_code = 200;
    options.status_text = "OK";
    snprintf(uri, sizeof(uri), "%s/%s", server_uri, "foo.wav");
    bucket_file = ast_bucket_file_retrieve(uri);
    ast_test_validate(test, bucket_file != NULL);
    ast_test_validate(test, !strcmp(uri, ast_sorcery_object_get_id(bucket_file)));
    ast_test_validate(test, !ast_strlen_zero(bucket_file->path));
    VALIDATE_EXPIRES(test, bucket_file, now.tv_sec, 3);
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [7/7]
AST_TEST_DEFINE (create_nominal)
Definition at line 573 of file test_http_media_cache.c.
References ast_bucket_file_alloc(), ast_bucket_file_create(), ast_bucket_file_temporary_create(), AST_TEST_NOT_RUN, AST_TEST_PASS, ast_tvnow(), bucket_file_cleanup(), CATEGORY, sip_to_pjsip::info(), NULL, options, RAII_VAR, test_options::send_file, server_uri, test_options::status_code, test_options::status_text, TEST_EXECUTE, TEST_INIT, and VALIDATE_EXPIRES.
 {
    RAII_VAR(struct ast_bucket_file *, bucket_file, NULL, bucket_file_cleanup);
    struct timeval now = ast_tvnow();
    char uri[1024];
    switch (cmd) {
    case TEST_INIT:
       info->name = __func__;
       info->category = CATEGORY;
       info->summary = "Test nominal creation";
       info->description =
          "Test nominal creation of a resource.";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    options.send_file = 1;
    options.status_code = 200;
    options.status_text = "OK";
    snprintf(uri, sizeof(uri), "%s/%s", server_uri, "foo.wav");
    bucket_file = ast_bucket_file_alloc(uri);
    ast_test_validate(test, bucket_file != NULL);
    ast_test_validate(test, ast_bucket_file_temporary_create(bucket_file) == 0);
    ast_test_validate(test, ast_bucket_file_create(bucket_file) == 0);
    VALIDATE_EXPIRES(test, bucket_file, now.tv_sec, 3);
    return AST_TEST_PASS;
 }
bucket_file_cleanup()
static void bucket_file_cleanup (void * obj) static
Definition at line 213 of file test_http_media_cache.c.
References ao2_ref, and ast_bucket_file_delete().
Referenced by AST_TEST_DEFINE().
 {
    struct ast_bucket_file *bucket_file = obj;
    if (bucket_file) {
       ast_bucket_file_delete(bucket_file);
       ao2_ref(bucket_file, -1);
    }
 }
http_callback()
static int http_callback (struct ast_tcptls_session_instance * ser, const struct ast_http_uri * urih, const char * uri, enum ast_http_method method, struct ast_variable * get_params, struct ast_variable * headers) static
Definition at line 91 of file test_http_media_cache.c.
References ast_free, ast_http_error(), AST_HTTP_GET, ast_http_request_close_on_completion(), ast_http_send(), ast_localtime(), ast_log, ast_str_append(), ast_str_buffer(), ast_str_create, ast_str_strlen(), ast_strftime(), ast_strlen_zero, buf, test_options::cache_control, errno, error(), test_options::etag, test_options::expires, LOG_ERROR, test_options::maxage, test_options::must_revalidate, ast_variable::name, ast_variable::next, test_options::no_cache, NULL, options, test_options::s_maxage, test_options::send_file, SET_OR_APPEND_CACHE_CONTROL, test_options::status_code, test_options::status_text, and ast_variable::value.
 {
    char file_name[64] = "/tmp/test-media-cache-XXXXXX";
    struct ast_str *http_header = ast_str_create(128);
    struct ast_str *cache_control = ast_str_create(128);
    int fd = -1;
    int unmodified = 0;
    int send_file = options.send_file && method == AST_HTTP_GET;
    if (!http_header) {
       goto error;
    }
    if (send_file) {
       char buf[1024];
       fd = mkstemp(file_name);
       if (fd == -1) {
          ast_log(LOG_ERROR, "Unable to open temp file for testing: %s (%d)", strerror(errno), errno);
          goto error;
       }
       memset(buf, 1, sizeof(buf));
       if (write(fd, buf, sizeof(buf)) != sizeof(buf)) {
          ast_log(LOG_ERROR, "Failed to write expected number of bytes to pipe\n");
          close(fd);
          goto error;
       }
       close(fd);
       fd = open(file_name, 0);
       if (fd == -1) {
          ast_log(LOG_ERROR, "Unable to open temp file for testing: %s (%d)", strerror(errno), errno);
          goto error;
       }
    }
    if (options.cache_control.maxage) {
       SET_OR_APPEND_CACHE_CONTROL(cache_control);
       ast_str_append(&cache_control, 0, "max-age=%d", options.cache_control.maxage);
    }
    if (options.cache_control.s_maxage) {
       SET_OR_APPEND_CACHE_CONTROL(cache_control);
       ast_str_append(&cache_control, 0, "s-maxage=%d", options.cache_control.s_maxage);
    }
    if (options.cache_control.no_cache) {
       SET_OR_APPEND_CACHE_CONTROL(cache_control);
       ast_str_append(&cache_control, 0, "%s", "no-cache");
    }
    if (options.cache_control.must_revalidate) {
       SET_OR_APPEND_CACHE_CONTROL(cache_control);
       ast_str_append(&cache_control, 0, "%s", "must-revalidate");
    }
    if (ast_str_strlen(cache_control)) {
       ast_str_append(&http_header, 0, "%s\r\n", ast_str_buffer(cache_control));
    }
    if (options.expires.tv_sec) {
       struct ast_tm now_time;
       char tmbuf[64];
       ast_localtime(&options.expires, &now_time, NULL);
       ast_strftime(tmbuf, sizeof(tmbuf), "%a, %d %b %Y %T %z", &now_time);
       ast_str_append(&http_header, 0, "Expires: %s\r\n", tmbuf);
    }
    if (!ast_strlen_zero(options.etag)) {
       struct ast_variable *v;
       ast_str_append(&http_header, 0, "ETag: %s\r\n", options.etag);
       for (v = headers; v; v = v->next) {
          if (!strcasecmp(v->name, "If-None-Match") && !strcasecmp(v->value, options.etag)) {
             unmodified = 1;
             break;
          }
       }
    }
    if (!unmodified) {
       ast_http_send(ser, method, options.status_code, options.status_text, http_header, NULL, send_file ? fd : 0, 1);
    } else {
       ast_http_send(ser, method, 304, "Not Modified", http_header, NULL, 0, 1);
    }
    if (send_file) {
       close(fd);
       unlink(file_name);
    }
    ast_free(cache_control);
    return 0;
 error:
    ast_free(http_header);
    ast_free(cache_control);
    ast_http_request_close_on_completion(ser);
    ast_http_error(ser, 418, "I'm a Teapot", "Please don't ask me to brew coffee.");
    return 0;
 }
load_module()
static int load_module (void) static
Definition at line 655 of file test_http_media_cache.c.
References ast_http_uri_link(), AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, AST_TEST_REGISTER, ast_test_register_init(), CATEGORY, pre_test_cb(), and process_config().
Referenced by unload_module().
 {
    if (process_config(0)) {
       return AST_MODULE_LOAD_DECLINE;
    }
    if (ast_http_uri_link(&test_uri)) {
       return AST_MODULE_LOAD_DECLINE;
    }
    AST_TEST_REGISTER(create_nominal);
    AST_TEST_REGISTER(retrieve_nominal);
    AST_TEST_REGISTER(retrieve_etag);
    AST_TEST_REGISTER(retrieve_expires);
    AST_TEST_REGISTER(retrieve_etag_expired);
    AST_TEST_REGISTER(retrieve_cache_control_age);
    AST_TEST_REGISTER(retrieve_cache_control_directives);
    ast_test_register_init(CATEGORY, pre_test_cb);
    return AST_MODULE_LOAD_SUCCESS;
 }
pre_test_cb()
static int pre_test_cb (struct ast_test_info * info, struct ast_test * test) static
Definition at line 206 of file test_http_media_cache.c.
References options.
Referenced by load_module().
 {
    memset(&options, 0, sizeof(options));
    return 0;
 }
process_config()
static int process_config (int reload) static
Definition at line 607 of file test_http_media_cache.c.
References ast_config_destroy(), ast_config_load, ast_config_option(), ast_false(), bindaddr, config, CONFIG_FLAG_FILEUNCHANGED, CONFIG_STATUS_FILEINVALID, CONFIG_STATUS_FILEUNCHANGED, enabled, prefix, S_OR, server_uri, and TEST_URI.
Referenced by load_module(), and reload_module().
 {
    struct ast_config *config;
    struct ast_flags config_flags = { reload ? CONFIG_FLAG_FILEUNCHANGED : 0 };
    const char *bindaddr;
    const char *bindport;
    const char *prefix;
    const char *enabled;
    config = ast_config_load("http.conf", config_flags);
    if (!config || config == CONFIG_STATUS_FILEINVALID) {
       return -1;
    } else if (config == CONFIG_STATUS_FILEUNCHANGED) {
       return 0;
    }
    enabled = ast_config_option(config, "general", "enabled");
    if (!enabled || ast_false(enabled)) {
       ast_config_destroy(config);
       return -1;
    }
    /* Construct our Server URI */
    bindaddr = ast_config_option(config, "general", "bindaddr");
    if (!bindaddr) {
       ast_config_destroy(config);
       return -1;
    }
    bindport = ast_config_option(config, "general", "bindport");
    if (!bindport) {
       bindport = "8088";
    }
    prefix = ast_config_option(config, "general", "prefix");
    snprintf(server_uri, sizeof(server_uri), "http://%s:%s%s/%s", bindaddr, bindport, S_OR(prefix, ""), TEST_URI);
    ast_config_destroy(config);
    return 0;
 }
reload_module()
static int reload_module (void) static
Definition at line 650 of file test_http_media_cache.c.
References process_config().
Referenced by unload_module().
 {
    return process_config(1);
 }
unload_module()
static int unload_module (void) static
Definition at line 679 of file test_http_media_cache.c.
References ast_http_uri_unlink(), AST_MODFLAG_DEFAULT, AST_MODULE_INFO(), AST_MODULE_SUPPORT_CORE, AST_TEST_UNREGISTER, ASTERISK_GPL_KEY, load_module(), reload(), and reload_module().
 {
    ast_http_uri_unlink(&test_uri);
    AST_TEST_UNREGISTER(create_nominal);
    AST_TEST_UNREGISTER(retrieve_nominal);
    AST_TEST_UNREGISTER(retrieve_etag);
    AST_TEST_UNREGISTER(retrieve_expires);
    AST_TEST_UNREGISTER(retrieve_etag_expired);
    AST_TEST_UNREGISTER(retrieve_cache_control_age);
    AST_TEST_UNREGISTER(retrieve_cache_control_directives);
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_DEFAULT , .description = "HTTP Media Cache Backend Tests" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .reload = reload_module, .unload = unload_module, .requires = "res_http_media_cache", } static
Definition at line 701 of file test_http_media_cache.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 701 of file test_http_media_cache.c.
options
struct test_options options static
Examples:
/usr/src/asterisk-18.5.0/main/app.c.
Definition at line 62 of file test_http_media_cache.c.
Referenced by __ssl_setup(), agent_login_exec(), app_exec(), aqm_exec(), ast_ari_bridges_record(), ast_ari_channels_record(), ast_get_number_str(), AST_TEST_DEFINE(), audiosocket_request(), auth_exec(), bridge_exec(), bridgewait_exec(), cdr_prop_write_callback(), cdr_read_callback(), cdr_write(), cdr_write_callback(), chanavail_exec(), chanspy_exec(), conf_exec(), controlplayback_exec(), detect_write(), dial_exec_full(), directory_exec(), disa_exec(), dundi_query_read(), dundifunc_read(), enable_jack_hook(), extenspy_exec(), feature_automixmonitor(), feature_automonitor(), file_read(), file_write(), forkcdr_exec(), function_enum(), generate_rtpmap_attr(), get_codecs(), handle_cli_presencestate_change(), handle_cli_presencestate_list(), handle_request_subscribe(), handle_updates(), hash_ao2_container_init(), hash_ao2_insert_node(), hint_read(), http_callback(), manager_mixmonitor(), milliwatt_exec(), mixmonitor_exec(), multicast_rtp_request(), originate_exec(), ospauth_exec(), ospfinished_exec(), osplookup_exec(), ospnext_exec(), page_state_callback(), park_and_announce_app_exec(), park_app_parse_data(), pbx_builtin_background(), pbx_builtin_incomplete(), pbx_builtin_saycharacters_case(), pbx_builtin_saynumber(), pbx_builtin_waitexten(), pickupchan_exec(), playback_exec(), pqm_exec(), pre_session_setup(), pre_test_cb(), presence_read(), presence_write(), privacy_exec(), process_echocancel(), queue_exec(), rb_ao2_container_init(), rb_ao2_insert_node(), rcvfax_exec(), read_exec(), read_mf_exec(), read_sf_exec(), readexten_exec(), receivefax_exec(), record_exec(), sayunixtime_exec(), search_directory_sub(), sendfax_exec(), sendurl_exec(), set_general_options(), sla_add_trunk_to_station(), sla_trunk_exec(), smdi_msg_retrieve_read(), sms_exec(), sndfax_exec(), softhangup_exec(), sorcery_memory_cache_open(), start_monitor_exec(), stir_shaken_cli_show(), unicast_rtp_request(), upqm_exec(), vmauthenticate(), volume_read(), volume_write(), wait_exec(), xmpp_pubsub_build_publish_skeleton(), xmpp_pubsub_subscribe(), and zapateller_exec().
server_uri
char server_uri[512] static
Definition at line 64 of file test_http_media_cache.c.
Referenced by AST_TEST_DEFINE(), load_module(), process_config(), and sip_outbound_publisher_init().
test_uri
struct ast_http_uri test_uri static
Definition at line 197 of file test_http_media_cache.c.