Asterisk - The Open Source Telephony Project: named_locks.c File Reference
named_locks.c File Reference
Named Locks.
#include "asterisk.h"
#include "asterisk/_private.h"
#include "asterisk/astobj2.h"
#include "asterisk/named_locks.h"
#include "asterisk/utils.h"
Data Structures
struct ast_named_lock
struct named_lock_proxy
Macros
#define NAMED_LOCKS_BUCKETS 101
Functions
struct ast_named_lock * __ast_named_lock_get (const char *filename, int lineno, const char *func, enum ast_named_lock_type lock_type, const char *keyspace, const char *key)
int ast_named_locks_init (void)
static void named_lock_proxy_cb (void *weakproxy, void *data)
static void named_locks_shutdown (void)
Variables
struct ao2_container * named_locks
Detailed Description
Named Locks.
Author
George Joseph georg.nosp@m.e.jo.nosp@m.seph@.nosp@m.fair.nosp@m.view5.nosp@m..com
Definition in file named_locks.c.
Macro Definition Documentation
NAMED_LOCKS_BUCKETS
#define NAMED_LOCKS_BUCKETS 101
Definition at line 34 of file named_locks.c.
Referenced by ast_named_locks_init().
Function Documentation
ast_named_locks_init()
int ast_named_locks_init (void)
Provided by named_locks.c
Definition at line 52 of file named_locks.c.
References AO2_ALLOC_OPT_LOCK_MUTEX, ao2_container_alloc_hash, ast_register_cleanup(), NAMED_LOCKS_BUCKETS, named_locks_shutdown(), and NULL.
Referenced by asterisk_daemon().
 {
    named_locks = ao2_container_alloc_hash(AO2_ALLOC_OPT_LOCK_MUTEX, 0,
       NAMED_LOCKS_BUCKETS, named_lock_proxy_hash_fn, NULL, named_lock_proxy_cmp_fn);
    if (!named_locks) {
       return -1;
    }
    ast_register_cleanup(named_locks_shutdown);
    return 0;
 }
named_lock_proxy_cb()
static void named_lock_proxy_cb (void * weakproxy, void * data) static
Definition at line 65 of file named_locks.c.
References ao2_unlink.
Referenced by __ast_named_lock_get().
 {
    ao2_unlink(named_locks, weakproxy);
 }
named_locks_shutdown()
static void named_locks_shutdown (void) static
Definition at line 47 of file named_locks.c.
References ao2_cleanup.
Referenced by ast_named_locks_init().
 {
    ao2_cleanup(named_locks);
 }
Variable Documentation
named_locks
struct ao2_container* named_locks
Definition at line 33 of file named_locks.c.