Asterisk - The Open Source Telephony Project: res_snmp.c File Reference
res_snmp.c File Reference
SNMP Agent / SubAgent support for Asterisk.
#include "asterisk.h"
#include "asterisk/channel.h"
#include "asterisk/module.h"
#include "snmp/agent.h"
Macros
#define MODULE_DESCRIPTION "SNMP [Sub]Agent for Asterisk"
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int load_config (void)
Load res_snmp.conf config file.
static int load_module (void)
Load the module.
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_DEFAULT , .description = "SNMP [Sub]Agent for Asterisk" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .support_level = AST_MODULE_SUPPORT_EXTENDED, .load = load_module, .unload = unload_module, }
static const struct ast_module_info * ast_module_info = &__mod_info
int res_snmp_agentx_subagent
int res_snmp_dont_stop
static int res_snmp_enabled
static pthread_t thread = AST_PTHREADT_NULL
Detailed Description
SNMP Agent / SubAgent support for Asterisk.
Author
Thorsten Lockert tholo.nosp@m.@voo.nosp@m.p.as
Uses the Net-SNMP libraries available at http://net-snmp.sourceforge.net/
Definition in file res_snmp.c.
Macro Definition Documentation
MODULE_DESCRIPTION
#define MODULE_DESCRIPTION "SNMP [Sub]Agent for Asterisk"
Definition at line 41 of file res_snmp.c.
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 140 of file res_snmp.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 140 of file res_snmp.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 140 of file res_snmp.c.
load_config()
static int load_config (void) static
Load res_snmp.conf config file.
Returns
1 on load, 0 file does not exist
Definition at line 53 of file res_snmp.c.
References ast_category_browse(), ast_config_destroy(), ast_config_load, ast_false(), ast_log, ast_true(), ast_variable_browse(), CONFIG_STATUS_FILEINVALID, CONFIG_STATUS_FILEMISSING, LOG_ERROR, LOG_WARNING, ast_variable::name, ast_variable::next, NULL, res_snmp_agentx_subagent, res_snmp_enabled, ast_variable::value, and var.
Referenced by load_module().
 {
    struct ast_variable *var;
    struct ast_config *cfg;
    struct ast_flags config_flags = { 0 };
    char *cat;
    res_snmp_enabled = 0;
    res_snmp_agentx_subagent = 1;
    cfg = ast_config_load("res_snmp.conf", config_flags);
    if (cfg == CONFIG_STATUS_FILEMISSING || cfg == CONFIG_STATUS_FILEINVALID) {
       ast_log(LOG_WARNING, "Could not load res_snmp.conf\n");
       return 0;
    }
    cat = ast_category_browse(cfg, NULL);
    while (cat) {
       var = ast_variable_browse(cfg, cat);
       if (strcasecmp(cat, "general") == 0) {
          while (var) {
             if (strcasecmp(var->name, "subagent") == 0) {
                if (ast_true(var->value))
                   res_snmp_agentx_subagent = 1;
                else if (ast_false(var->value))
                   res_snmp_agentx_subagent = 0;
                else {
                   ast_log(LOG_ERROR, "Value '%s' does not evaluate to true or false.\n", var->value);
                   ast_config_destroy(cfg);
                   return 1;
                }
             } else if (strcasecmp(var->name, "enabled") == 0) {
                res_snmp_enabled = ast_true(var->value);
             } else {
                ast_log(LOG_ERROR, "Unrecognized variable '%s' in category '%s'\n", var->name, cat);
                ast_config_destroy(cfg);
                return 1;
             }
             var = var->next;
          }
       } else {
          ast_log(LOG_ERROR, "Unrecognized category '%s'\n", cat);
          ast_config_destroy(cfg);
          return 1;
       }
       cat = ast_category_browse(cfg, cat);
    }
    ast_config_destroy(cfg);
    return 1;
 }
load_module()
static int load_module (void) static
Load the module.
Module loading including tests for configuration or dependencies. This function can return AST_MODULE_LOAD_FAILURE, AST_MODULE_LOAD_DECLINE, or AST_MODULE_LOAD_SUCCESS. If a dependency or environment variable fails tests return AST_MODULE_LOAD_FAILURE. If the module can not load the configuration file or other non-critical problem return AST_MODULE_LOAD_DECLINE. On success return AST_MODULE_LOAD_SUCCESS.
Definition at line 114 of file res_snmp.c.
References agent_thread(), AST_MODULE_LOAD_DECLINE, ast_pthread_create_background, ast_verb, load_config(), NULL, res_snmp_dont_stop, res_snmp_enabled, and thread.
Referenced by unload_module().
 {
    if(!load_config())
       return AST_MODULE_LOAD_DECLINE;
    ast_verb(1, "Loading [Sub]Agent Module\n");
    res_snmp_dont_stop = 1;
    if (res_snmp_enabled)
       return ast_pthread_create_background(&thread, NULL, agent_thread, NULL);
    else
       return 0;
 }
unload_module()
static int unload_module (void) static
Definition at line 128 of file res_snmp.c.
References AST_MODFLAG_DEFAULT, AST_MODULE_INFO(), AST_MODULE_SUPPORT_EXTENDED, AST_PTHREADT_NULL, ast_verb, ASTERISK_GPL_KEY, load_module(), NULL, res_snmp_dont_stop, and thread.
 {
    ast_verb(1, "Unloading [Sub]Agent Module\n");
    res_snmp_dont_stop = 0;
    return ((thread != AST_PTHREADT_NULL) ? pthread_join(thread, NULL) : 0);
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_DEFAULT , .description = "SNMP [Sub]Agent for Asterisk" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .support_level = AST_MODULE_SUPPORT_EXTENDED, .load = load_module, .unload = unload_module, } static
Definition at line 140 of file res_snmp.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 140 of file res_snmp.c.
res_snmp_agentx_subagent
int res_snmp_agentx_subagent
Definition at line 43 of file res_snmp.c.
Referenced by agent_thread(), and load_config().
res_snmp_dont_stop
int res_snmp_dont_stop
Definition at line 44 of file res_snmp.c.
Referenced by agent_thread(), load_module(), and unload_module().
res_snmp_enabled
int res_snmp_enabled static
Definition at line 45 of file res_snmp.c.
Referenced by load_config(), and load_module().
thread
pthread_t thread = AST_PTHREADT_NULL static
Definition at line 47 of file res_snmp.c.
Referenced by load_module(), and unload_module().