Asterisk - The Open Source Telephony Project: codec_codec2.c File Reference
codec_codec2.c File Reference
Module: Codecs
Translate between signed linear and Codec 2.
#include "asterisk.h"
#include "asterisk/codec.h"
#include "asterisk/frame.h"
#include "asterisk/linkedlists.h"
#include "asterisk/logger.h"
#include "asterisk/module.h"
#include "asterisk/rtp_engine.h"
#include "asterisk/translate.h"
#include <codec2/codec2.h>
#include "asterisk/slin.h"
#include "ex_codec2.h"
Data Structures
struct codec2_translator_pvt
Macros
#define BUFFER_SAMPLES 8000
#define CODEC2_FRAME_LEN 6 /* consider codec2_bits_per_frame(.) */
#define CODEC2_SAMPLES 160 /* consider codec2_samples_per_frame(.) */
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static void codec2_destroy_stuff (struct ast_trans_pvt *pvt)
static int codec2_new (struct ast_trans_pvt *pvt)
static int codec2tolin_framein (struct ast_trans_pvt *pvt, struct ast_frame *f)
decode and store in outbuf.
static int lintocodec2_framein (struct ast_trans_pvt *pvt, struct ast_frame *f)
store samples into working buffer for later decode
static struct ast_frame * lintocodec2_frameout (struct ast_trans_pvt *pvt)
encode and produce a frame
static int load_module (void)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Codec 2 Coder/Decoder" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, }
static const struct ast_module_info * ast_module_info = &__mod_info
static struct ast_translator codec2tolin
static struct ast_translator lintocodec2
Detailed Description
Translate between signed linear and Codec 2.
Author
Alexander Traud pabst.nosp@m.raud.nosp@m.@comp.nosp@m.user.nosp@m.ve.co.nosp@m.m
Note
http://www.rowetel.com/codec2.html
Definition in file codec_codec2.c.
Macro Definition Documentation
BUFFER_SAMPLES
#define BUFFER_SAMPLES 8000
Definition at line 47 of file codec_codec2.c.
CODEC2_FRAME_LEN
#define CODEC2_FRAME_LEN 6 /* consider codec2_bits_per_frame(.) */
Definition at line 49 of file codec_codec2.c.
Referenced by codec2tolin_framein(), and lintocodec2_frameout().
CODEC2_SAMPLES
#define CODEC2_SAMPLES 160 /* consider codec2_samples_per_frame(.) */
Definition at line 48 of file codec_codec2.c.
Referenced by codec2_sample(), codec2tolin_framein(), and lintocodec2_frameout().
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 222 of file codec_codec2.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 222 of file codec_codec2.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 222 of file codec_codec2.c.
codec2_destroy_stuff()
static void codec2_destroy_stuff (struct ast_trans_pvt * pvt) static
Definition at line 141 of file codec_codec2.c.
References ast_trans_pvt::pvt, codec2_translator_pvt::state, and tmp().
 {
    struct codec2_translator_pvt *tmp = pvt->pvt;
    if (tmp->state) {
       codec2_destroy(tmp->state);
    }
 }
codec2_new()
static int codec2_new (struct ast_trans_pvt * pvt) static
Definition at line 60 of file codec_codec2.c.
References ast_log, LOG_ERROR, ast_trans_pvt::pvt, codec2_translator_pvt::state, and tmp().
 {
    struct codec2_translator_pvt *tmp = pvt->pvt;
    tmp->state = codec2_create(CODEC2_MODE_2400);
    if (!tmp->state) {
       ast_log(LOG_ERROR, "Error creating Codec 2 conversion\n");
       return -1;
    }
    return 0;
 }
codec2tolin_framein()
static int codec2tolin_framein (struct ast_trans_pvt * pvt, struct ast_frame * f) static
decode and store in outbuf.
Definition at line 75 of file codec_codec2.c.
References CODEC2_FRAME_LEN, CODEC2_SAMPLES, ast_frame::data, ast_frame::datalen, ast_trans_pvt::datalen, ast_trans_pvt::i16, ast_trans_pvt::outbuf, ast_frame::ptr, ast_trans_pvt::pvt, ast_trans_pvt::samples, codec2_translator_pvt::state, and tmp().
 {
    struct codec2_translator_pvt *tmp = pvt->pvt;
    int x;
    for (x = 0; x < f->datalen; x += CODEC2_FRAME_LEN) {
       unsigned char *src = f->data.ptr + x;
       int16_t *dst = pvt->outbuf.i16 + pvt->samples;
       codec2_decode(tmp->state, dst, src);
       pvt->samples += CODEC2_SAMPLES;
       pvt->datalen += CODEC2_SAMPLES * 2;
    }
    return 0;
 }
lintocodec2_framein()
static int lintocodec2_framein (struct ast_trans_pvt * pvt, struct ast_frame * f) static
store samples into working buffer for later decode
Definition at line 94 of file codec_codec2.c.
References codec2_translator_pvt::buf, ast_frame::data, ast_frame::datalen, ast_frame::ptr, ast_trans_pvt::pvt, ast_frame::samples, ast_trans_pvt::samples, and tmp().
 {
    struct codec2_translator_pvt *tmp = pvt->pvt;
    memcpy(tmp->buf + pvt->samples, f->data.ptr, f->datalen);
    pvt->samples += f->samples;
    return 0;
 }
lintocodec2_frameout()
static struct ast_frame* lintocodec2_frameout (struct ast_trans_pvt * pvt) static
encode and produce a frame
Definition at line 105 of file codec_codec2.c.
References AST_LIST_NEXT, ast_trans_frameout(), codec2_translator_pvt::buf, CODEC2_FRAME_LEN, CODEC2_SAMPLES, last, NULL, ast_trans_pvt::outbuf, ast_trans_pvt::pvt, result, ast_frame::samples, ast_trans_pvt::samples, codec2_translator_pvt::state, tmp(), and ast_trans_pvt::uc.
 {
    struct codec2_translator_pvt *tmp = pvt->pvt;
    struct ast_frame *result = NULL;
    struct ast_frame *last = NULL;
    int samples = 0; /* output samples */
    while (pvt->samples >= CODEC2_SAMPLES) {
       struct ast_frame *current;
       /* Encode a frame of data */
       codec2_encode(tmp->state, pvt->outbuf.uc, tmp->buf + samples);
       samples += CODEC2_SAMPLES;
       pvt->samples -= CODEC2_SAMPLES;
       current = ast_trans_frameout(pvt, CODEC2_FRAME_LEN, CODEC2_SAMPLES);
       if (!current) {
          continue;
       } else if (last) {
          AST_LIST_NEXT(last, frame_list) = current;
       } else {
          result = current;
       }
       last = current;
    }
    /* Move the data at the end of the buffer to the front */
    if (samples) {
       memmove(tmp->buf, tmp->buf + samples, pvt->samples * 2);
    }
    return result;
 }
load_module()
static int load_module (void) static
Definition at line 206 of file codec_codec2.c.
References ast_format_codec2, AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, ast_register_translator, ast_rtp_engine_load_format(), and unload_module().
 {
    int res = 0;
    res |= ast_register_translator(&codec2tolin);
    res |= ast_register_translator(&lintocodec2);
    res |= ast_rtp_engine_load_format(ast_format_codec2);
    if (res) {
       unload_module();
       return AST_MODULE_LOAD_DECLINE;
    }
    return AST_MODULE_LOAD_SUCCESS;
 }
unload_module()
static int unload_module (void) static
Definition at line 195 of file codec_codec2.c.
References ast_format_codec2, ast_rtp_engine_unload_format(), and ast_unregister_translator().
Referenced by load_module().
 {
    int res = 0;
    res |= ast_rtp_engine_unload_format(ast_format_codec2);
    res |= ast_unregister_translator(&lintocodec2);
    res |= ast_unregister_translator(&codec2tolin);
    return res;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Codec 2 Coder/Decoder" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, } static
Definition at line 222 of file codec_codec2.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 222 of file codec_codec2.c.
codec2tolin
struct ast_translator codec2tolin static
Definition at line 150 of file codec_codec2.c.
lintocodec2
struct ast_translator lintocodec2 static
Definition at line 172 of file codec_codec2.c.