Asterisk - The Open Source Telephony Project: core_local.h File Reference
core_local.h File Reference
Local proxy channel special access.
Functions
struct stasis_message_type * ast_local_bridge_type (void)
Message type for when two local channel halves are bridged together.
struct ast_channel * ast_local_get_peer (struct ast_channel *ast)
Get the other local channel in the pair.
void ast_local_lock_all (struct ast_channel *chan, void **tech_pvt, struct ast_channel **base_chan, struct ast_channel **base_owner)
Add a reference to the local channel's private tech, lock the local channel's private base, and add references and lock both sides of the local channel.
struct stasis_message_type * ast_local_optimization_begin_type (void)
Message type for when a local channel optimization begins.
struct stasis_message_type * ast_local_optimization_end_type (void)
Message type for when a local channel optimization completes.
int ast_local_setup_bridge (struct ast_channel *ast, struct ast_bridge *bridge, struct ast_channel *swap, struct ast_bridge_features *features)
Setup the outgoing local channel to join a bridge on ast_call().
int ast_local_setup_masquerade (struct ast_channel *ast, struct ast_channel *masq)
Setup the outgoing local channel to masquerade into a channel on ast_call().
void ast_local_unlock_all (void *tech_pvt, struct ast_channel *base_chan, struct ast_channel *base_owner)
Remove a reference to the given local channel's private tech, unlock the given local channel's private base, and remove references and unlock both sides of given the local channel.
Detailed Description
Local proxy channel special access.
Author
Richard Mudgett rmudg.nosp@m.ett@.nosp@m.digiu.nosp@m.m.co.nosp@m.m
See Also:
CREDITS
Definition in file core_local.h.
Function Documentation
ast_local_bridge_type()
struct stasis_message_type* ast_local_bridge_type (void)
Message type for when two local channel halves are bridged together.
Since
12.0.0
Note
Payloads for the ast_local_bridge_type are a ast_multi_channel_blob. Roles for the channels in the ast_multi_channel_blob are "1" and "2", reflecting the two halves. Unlike most other bridges, the 'bridge' between two local channels is not part of the bridge framework; as such, the message simply references the two local channel halves that are now bridged.
Return values
A Stasis Message Bus API message type
Referenced by ast_local_init(), local_message_to_ami(), local_shutdown(), and publish_local_bridge_message().
ast_local_get_peer()
struct ast_channel* ast_local_get_peer (struct ast_channel * ast)
Get the other local channel in the pair.
Since
12.0.0
Parameters
ast Local channel to get peer.
Note
On entry, ast must be locked.
Return values
peer reffed on success.
NULL if no peer or error.
Definition at line 276 of file core_local.c.
References ao2_find, ao2_lock, ao2_ref, ao2_unlock, ast_channel_ref, ast_channel_tech_pvt(), local_pvt::base, ast_unreal_pvt::chan, NULL, and ast_unreal_pvt::owner.
Referenced by ari_channels_handle_originate_with_id(), and park_local_transfer().
 {
    struct local_pvt *p = ast_channel_tech_pvt(ast);
    struct local_pvt *found;
    struct ast_channel *peer;
    if (!p) {
       return NULL;
    }
    found = p ? ao2_find(locals, p, 0) : NULL;
    if (!found) {
       /* ast is either not a local channel or it has alredy been hungup */
       return NULL;
    }
    ao2_lock(found);
    if (ast == p->base.owner) {
       peer = p->base.chan;
    } else if (ast == p->base.chan) {
       peer = p->base.owner;
    } else {
       peer = NULL;
    }
    if (peer) {
       ast_channel_ref(peer);
    }
    ao2_unlock(found);
    ao2_ref(found, -1);
    return peer;
 }
ast_local_lock_all()
void ast_local_lock_all (struct ast_channel * chan, void ** tech_pvt, struct ast_channel ** base_chan, struct ast_channel ** base_owner)
Add a reference to the local channel's private tech, lock the local channel's private base, and add references and lock both sides of the local channel.
Note
None of these locks should be held prior to calling this function.
To undo this process call ast_local_unlock_all2.
Since
13.17.0, 14.6.0
Parameters
chan Must be a local channel
tech_pvt [out] channel's private tech (ref and lock added)
base_chan [out] One side of the local channel (ref and lock added)
base_owner [out] Other side of the local channel (ref and lock added)
Definition at line 241 of file core_local.c.
References ao2_bump, ast_channel_tech_pvt(), ast_unreal_lock_all(), local_pvt::base, and NULL.
Referenced by attended_transfer_bridge().
 {
    struct local_pvt *p = ast_channel_tech_pvt(chan);
    *tech_pvt = NULL;
    *base_chan = NULL;
    *base_owner = NULL;
    if (p) {
       *tech_pvt = ao2_bump(p);
       ast_unreal_lock_all(&p->base, base_chan, base_owner);
    }
 }
ast_local_optimization_begin_type()
struct stasis_message_type* ast_local_optimization_begin_type (void)
Message type for when a local channel optimization begins.
Since
12.0.0
Note
Payloads for the ast_local_optimization_begin_type are a ast_multi_channel_blob. Roles for the channels in the ast_multi_channel_blob are "1" and "2", reflecting the two halves.
Return values
A Stasis Message Bus API message type
Referenced by ast_local_init(), AST_TEST_DEFINE(), local_message_to_ami(), local_optimization_started_cb(), local_shutdown(), and setup_stasis_subs().
ast_local_optimization_end_type()
struct stasis_message_type* ast_local_optimization_end_type (void)
Message type for when a local channel optimization completes.
Since
12.0.0
Note
Payloads for the ast_local_optimization_end_type are a ast_multi_channel_blob. Roles for the channels in the ast_multi_channel_blob are "1" and "2", reflecting the two halves.
Return values
A Stasis Message Bus API message type
Referenced by ast_local_init(), AST_TEST_DEFINE(), create_routes(), local_message_to_ami(), local_optimization_finished_cb(), local_shutdown(), and setup_stasis_subs().
ast_local_setup_bridge()
int ast_local_setup_bridge (struct ast_channel * ast, struct ast_bridge * bridge, struct ast_channel * swap, struct ast_bridge_features * features)
Setup the outgoing local channel to join a bridge on ast_call().
Since
12.0.0
Parameters
ast Either channel of a local channel pair.
bridge Bridge to join.
swap Channel to swap with when joining.
features Bridge features structure.
Note
The features parameter must be NULL or obtained by ast_bridge_features_new(). You must not dereference features after calling even if the call fails.
Intended to be called after ast_request() and before ast_call() on a local channel.
Return values
0 on success.
-1 on error.
Definition at line 599 of file core_local.c.
References local_pvt::action, ao2_find, ao2_lock, ao2_ref, ao2_unlock, ast_bridge_features_destroy(), ast_channel_lock, ast_channel_ref, ast_channel_tech_pvt(), ast_channel_unlock, ast_test_flag, AST_UNREAL_CARETAKER_THREAD, local_pvt::base, local_pvt::bridge, ast_unreal_pvt::chan, local_bridge::features, local_bridge::join, LOCAL_CALL_ACTION_BRIDGE, LOCAL_CALL_ACTION_DIALPLAN, NULL, ast_unreal_pvt::owner, local_bridge::swap, and local_pvt::type.
Referenced by attended_transfer_bridge().
 {
    struct local_pvt *p;
    struct local_pvt *found;
    int res = -1;
    /* Sanity checks. */
    if (!ast || !bridge) {
       ast_bridge_features_destroy(features);
       return -1;
    }
    ast_channel_lock(ast);
    p = ast_channel_tech_pvt(ast);
    ast_channel_unlock(ast);
    found = p ? ao2_find(locals, p, 0) : NULL;
    if (found) {
       ao2_lock(found);
       if (found->type == LOCAL_CALL_ACTION_DIALPLAN
          && found->base.owner
          && found->base.chan
          && !ast_test_flag(&found->base, AST_UNREAL_CARETAKER_THREAD)) {
          ao2_ref(bridge, +1);
          if (swap) {
             ast_channel_ref(swap);
          }
          found->type = LOCAL_CALL_ACTION_BRIDGE;
          found->action.bridge.join = bridge;
          found->action.bridge.swap = swap;
          found->action.bridge.features = features;
          res = 0;
       } else {
          ast_bridge_features_destroy(features);
       }
       ao2_unlock(found);
       ao2_ref(found, -1);
    }
    return res;
 }
ast_local_setup_masquerade()
int ast_local_setup_masquerade (struct ast_channel * ast, struct ast_channel * masq)
Setup the outgoing local channel to masquerade into a channel on ast_call().
Since
12.0.0
Parameters
ast Either channel of a local channel pair.
masq Channel to masquerade into.
Note
Intended to be called after ast_request() and before ast_call() on a local channel.
Return values
0 on success.
-1 on error.
Definition at line 641 of file core_local.c.
References local_pvt::action, ao2_find, ao2_lock, ao2_ref, ao2_unlock, ast_channel_lock, ast_channel_ref, ast_channel_tech_pvt(), ast_channel_unlock, ast_test_flag, AST_UNREAL_CARETAKER_THREAD, local_pvt::base, ast_unreal_pvt::chan, LOCAL_CALL_ACTION_DIALPLAN, LOCAL_CALL_ACTION_MASQUERADE, local_pvt::masq, NULL, ast_unreal_pvt::owner, and local_pvt::type.
Referenced by attended_transfer_bridge().
 {
    struct local_pvt *p;
    struct local_pvt *found;
    int res = -1;
    /* Sanity checks. */
    if (!ast || !masq) {
       return -1;
    }
    ast_channel_lock(ast);
    p = ast_channel_tech_pvt(ast);
    ast_channel_unlock(ast);
    found = p ? ao2_find(locals, p, 0) : NULL;
    if (found) {
       ao2_lock(found);
       if (found->type == LOCAL_CALL_ACTION_DIALPLAN
          && found->base.owner
          && found->base.chan
          && !ast_test_flag(&found->base, AST_UNREAL_CARETAKER_THREAD)) {
          ast_channel_ref(masq);
          found->type = LOCAL_CALL_ACTION_MASQUERADE;
          found->action.masq = masq;
          res = 0;
       }
       ao2_unlock(found);
       ao2_ref(found, -1);
    }
    return res;
 }
ast_local_unlock_all()
void ast_local_unlock_all (void * tech_pvt, struct ast_channel * base_chan, struct ast_channel * base_owner)
Remove a reference to the given local channel's private tech, unlock the given local channel's private base, and remove references and unlock both sides of given the local channel.
Note
This function should be used in conjunction with ast_local_lock_all2.
Since
13.17.0, 14.6.0
Parameters
tech_pvt channel's private tech (ref and lock removed)
base_chan One side of the local channel (ref and lock removed)
base_owner Other side of the local channel (ref and lock removed)
Definition at line 256 of file core_local.c.
References ao2_ref, ao2_unlock, ast_channel_unlock, ast_channel_unref, and local_pvt::base.
Referenced by attended_transfer_bridge().
 {
    if (base_chan) {
       ast_channel_unlock(base_chan);
       ast_channel_unref(base_chan);
    }
    if (base_owner) {
       ast_channel_unlock(base_owner);
       ast_channel_unref(base_owner);
    }
    if (tech_pvt) {
       struct local_pvt *p = tech_pvt;
       ao2_unlock(&p->base);
       ao2_ref(tech_pvt, -1);
    }
 }