Asterisk - The Open Source Telephony Project: max_forwards.h File Reference
max_forwards.h File Reference
Functions
int ast_max_forwards_decrement (struct ast_channel *chan)
Decrement the max forwards count for a particular channel.
int ast_max_forwards_get (struct ast_channel *chan)
Get the current max forwards for a particular channel.
int ast_max_forwards_reset (struct ast_channel *chan)
Reset the max forwards on a channel to its starting value.
int ast_max_forwards_set (struct ast_channel *chan, int starting_count)
Set the starting max forwards for a particular channel.
Function Documentation
ast_max_forwards_decrement()
int ast_max_forwards_decrement (struct ast_channel * chan)
Decrement the max forwards count for a particular channel.
If the channel has not had max forwards set on it, then the channel will have the default max forwards set on it and that value will not be decremented.
Precondition
chan is locked
The channel for which the max forwards value should be decremented
Return values
0 Success
-1 Failure
Definition at line 135 of file max_forwards.c.
References max_forwards::current_count, ast_datastore::data, and max_forwards_datastore_find_or_alloc().
Referenced by __ast_request_and_dial(), ast_ari_channels_dial(), begin_dial_prerun(), call_forward_inherit(), dial_exec_full(), do_forward(), findmeexec(), ring_entry(), and wait_for_answer().
 {
    struct ast_datastore *mf_datastore;
    struct max_forwards *mf;
    mf_datastore = max_forwards_datastore_find_or_alloc(chan);
    if (!mf_datastore) {
       return -1;
    }
    mf = mf_datastore->data;
    --mf->current_count;
    return 0;
 }
ast_max_forwards_get()
int ast_max_forwards_get (struct ast_channel * chan)
Get the current max forwards for a particular channel.
If the channel has not had max forwards set on it, then the channel will have the default max forwards set on it and that value will be returned.
Precondition
chan is locked
Parameters
chan The channel to get the max forwards for.
Returns
The current max forwards count on the channel
Definition at line 121 of file max_forwards.c.
References max_forwards::current_count, ast_datastore::data, and max_forwards_datastore_find_or_alloc().
Referenced by app_exec(), begin_dial_prerun(), dial_exec_full(), func_channel_read(), and queue_exec().
 {
    struct ast_datastore *mf_datastore;
    struct max_forwards *mf;
    mf_datastore = max_forwards_datastore_find_or_alloc(chan);
    if (!mf_datastore) {
       return -1;
    }
    mf = mf_datastore->data;
    return mf->current_count;
 }
ast_max_forwards_reset()
int ast_max_forwards_reset (struct ast_channel * chan)
Reset the max forwards on a channel to its starting value.
If the channel has not had max forwards set on it, then the channel will have the default max forwards set on it.
Precondition
chan is locked.
Parameters
chan The channel on which to reset the max forwards count.
Return values
0 Success
-1 Failure
Definition at line 151 of file max_forwards.c.
References max_forwards::current_count, ast_datastore::data, max_forwards_datastore_find_or_alloc(), and max_forwards::starting_count.
Referenced by pre_bridge_setup().
 {
    struct ast_datastore *mf_datastore;
    struct max_forwards *mf;
    mf_datastore = max_forwards_datastore_find_or_alloc(chan);
    if (!mf_datastore) {
       return -1;
    }
    mf = mf_datastore->data;
    mf->current_count = mf->starting_count;
    return 0;
 }
ast_max_forwards_set()
int ast_max_forwards_set (struct ast_channel * chan, int starting_count)
Set the starting max forwards for a particular channel.
Precondition
chan is locked
Parameters
starting_count The value to set the max forwards to.
chan The channel on which to set the max forwards.
Return values
0 Success
1 Failure
Definition at line 105 of file max_forwards.c.
References max_forwards::current_count, ast_datastore::data, max_forwards_datastore_find_or_alloc(), and max_forwards::starting_count.
Referenced by func_channel_write_real().
 {
    struct ast_datastore *mf_datastore;
    struct max_forwards *mf;
    mf_datastore = max_forwards_datastore_find_or_alloc(chan);
    if (!mf_datastore) {
       return -1;
    }
    mf = mf_datastore->data;
    mf->starting_count = mf->current_count = starting_count;
    return 0;
 }