Asterisk - The Open Source Telephony Project: pjsip_scheduler.c File Reference
pjsip_scheduler.c File Reference
res_pjsip Scheduler
#include "asterisk.h"
#include "asterisk/res_pjsip.h"
#include "include/res_pjsip_private.h"
#include "asterisk/res_pjsip_cli.h"
#include "asterisk/taskprocessor.h"
#include <regex.h>
Data Structures
struct ast_sip_sched_task
Macros
#define ID_LEN 13 /* task_deadbeef */
#define TASK_BUCKETS 53
#define TIME_FORMAT "%a %T"
Functions
AO2_STRING_FIELD_CMP_FN (ast_sip_sched_task, name)
AO2_STRING_FIELD_HASH_FN (ast_sip_sched_task, name)
AO2_STRING_FIELD_SORT_FN (ast_sip_sched_task, name)
int ast_sip_destroy_scheduler (void)
int ast_sip_initialize_scheduler (void)
Initialize scheduler.
int ast_sip_sched_is_task_running (struct ast_sip_sched_task *schtd)
Checks if the task is currently running.
int ast_sip_sched_is_task_running_by_name (const char *name)
Checks if the task is currently running.
int ast_sip_sched_task_cancel (struct ast_sip_sched_task *schtd)
Cancels the next invocation of a task.
int ast_sip_sched_task_cancel_by_name (const char *name)
Cancels the next invocation of a task by name.
int ast_sip_sched_task_get_name (struct ast_sip_sched_task *schtd, char *name, size_t maxlen)
Gets the task name.
int ast_sip_sched_task_get_next_run (struct ast_sip_sched_task *schtd)
Gets the number of milliseconds until the next invocation.
int ast_sip_sched_task_get_next_run_by_name (const char *name)
Gets the number of milliseconds until the next invocation.
int ast_sip_sched_task_get_times (struct ast_sip_sched_task *schtd, struct timeval *queued, struct timeval *last_start, struct timeval *last_end)
Gets the last start and end times of the task.
int ast_sip_sched_task_get_times2 (struct ast_sip_sched_task *schtd, struct timeval *queued, struct timeval *last_start, struct timeval *last_end, int *interval, int *time_left, struct timeval *next_start)
Gets the queued, last start, last_end, time left, interval, next run.
int ast_sip_sched_task_get_times_by_name (const char *name, struct timeval *queued, struct timeval *last_start, struct timeval *last_end)
Gets the last start and end times of the task by name.
int ast_sip_sched_task_get_times_by_name2 (const char *name, struct timeval *queued, struct timeval *last_start, struct timeval *last_end, int *interval, int *time_left, struct timeval *next_start)
Gets the queued, last start, last_end, time left, interval, next run by task name.
struct ast_sip_sched_task * ast_sip_schedule_task (struct ast_taskprocessor *serializer, int interval, ast_sip_task sip_task, const char *name, void *task_data, enum ast_sip_scheduler_task_flags flags)
Schedule a task to run in the res_pjsip thread pool.
static char * cli_show_tasks (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static int push_to_serializer (const void *data)
static int run_task (void *data)
static void schtd_dtor (void *data)
Variables
static struct ast_cli_entry cli_commands []
static struct ast_sched_context * scheduler_context
static int task_count
static struct ao2_container * tasks
Detailed Description
res_pjsip Scheduler
Author
George Joseph georg.nosp@m.e.jo.nosp@m.seph@.nosp@m.fair.nosp@m.view5.nosp@m..com
Definition in file pjsip_scheduler.c.
Macro Definition Documentation
ID_LEN
#define ID_LEN 13 /* task_deadbeef */
Referenced by ast_sip_schedule_task().
TASK_BUCKETS
#define TASK_BUCKETS 53
Definition at line 35 of file pjsip_scheduler.c.
Referenced by ast_sip_initialize_scheduler().
TIME_FORMAT
#define TIME_FORMAT "%a %T"
Definition at line 488 of file pjsip_scheduler.c.
Referenced by cli_show_tasks().
Function Documentation
AO2_STRING_FIELD_CMP_FN()
AO2_STRING_FIELD_CMP_FN (ast_sip_sched_task , name)
AO2_STRING_FIELD_HASH_FN()
AO2_STRING_FIELD_HASH_FN (ast_sip_sched_task , name)
AO2_STRING_FIELD_SORT_FN()
AO2_STRING_FIELD_SORT_FN (ast_sip_sched_task , name)
ast_sip_destroy_scheduler()
int ast_sip_destroy_scheduler (void)
Definition at line 642 of file pjsip_scheduler.c.
References ao2_cleanup, ao2_iterator_destroy(), ao2_iterator_init(), ao2_iterator_next, ao2_ref, ARRAY_LEN, ast_cli_unregister_multiple(), ast_sched_context_destroy(), ast_sip_sched_task_cancel(), and NULL.
Referenced by load_module(), and unload_module().
 {
    ast_cli_unregister_multiple(cli_commands, ARRAY_LEN(cli_commands));
    if (scheduler_context) {
       if (tasks) {
          struct ao2_iterator iter;
          struct ast_sip_sched_task *schtd;
          /* Cancel all scheduled tasks */
          iter = ao2_iterator_init(tasks, 0);
          while ((schtd = ao2_iterator_next(&iter))) {
             ast_sip_sched_task_cancel(schtd);
             ao2_ref(schtd, -1);
          }
          ao2_iterator_destroy(&iter);
       }
       ast_sched_context_destroy(scheduler_context);
       scheduler_context = NULL;
    }
    ao2_cleanup(tasks);
    tasks = NULL;
    return 0;
 }
ast_sip_initialize_scheduler()
int ast_sip_initialize_scheduler (void)
Initialize scheduler.
Since
13.9.0
Return values
-1 failure
0 success
Definition at line 614 of file pjsip_scheduler.c.
References AO2_ALLOC_OPT_LOCK_RWLOCK, ao2_container_alloc_hash, AO2_CONTAINER_ALLOC_OPT_DUPS_REJECT, ARRAY_LEN, ast_cli_register_multiple, ast_log, ast_sched_context_create(), ast_sched_context_destroy(), ast_sched_start_thread(), LOG_ERROR, and TASK_BUCKETS.
Referenced by load_module().
 {
    scheduler_context = ast_sched_context_create();
    if (!scheduler_context) {
       ast_log(LOG_ERROR, "Failed to create scheduler. Aborting load\n");
       return -1;
    }
    if (ast_sched_start_thread(scheduler_context)) {
       ast_log(LOG_ERROR, "Failed to start scheduler. Aborting load\n");
       ast_sched_context_destroy(scheduler_context);
       return -1;
    }
    tasks = ao2_container_alloc_hash(AO2_ALLOC_OPT_LOCK_RWLOCK,
       AO2_CONTAINER_ALLOC_OPT_DUPS_REJECT, TASK_BUCKETS, ast_sip_sched_task_hash_fn,
       ast_sip_sched_task_sort_fn, ast_sip_sched_task_cmp_fn);
    if (!tasks) {
       ast_log(LOG_ERROR, "Failed to allocate task container. Aborting load\n");
       ast_sched_context_destroy(scheduler_context);
       return -1;
    }
    ast_cli_register_multiple(cli_commands, ARRAY_LEN(cli_commands));
    return 0;
 }
cli_show_tasks()
static char* cli_show_tasks (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) static
Definition at line 490 of file pjsip_scheduler.c.
References AO2_ALLOC_OPT_LOCK_NOLOCK, ao2_container_alloc_rbtree, ao2_container_count(), ao2_container_dup(), ao2_iterator_destroy(), ao2_iterator_init(), ao2_iterator_next, AO2_ITERATOR_UNLINK, ao2_lock, ao2_ref, ao2_unlock, ast_cli_args::argc, ast_cli_args::argv, ast_cli(), ast_localtime(), ast_sip_sched_task_get_next_run(), AST_SIP_SCHED_TASK_ONESHOT, ast_strftime(), ast_tv(), ast_tvadd(), ast_tvnow(), ast_tvzero(), CLI_FAILURE, CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::command, ast_cli_args::fd, ast_sip_sched_task::flags, ast_sip_sched_task::interval, ast_sip_sched_task::is_running, ast_sip_sched_task::last_start, ast_sip_sched_task::name, NULL, regex(), ast_sip_sched_task::run_count, TIME_FORMAT, ast_cli_entry::usage, and ast_sip_sched_task::when_queued.
 {
    struct ao2_iterator iter;
    struct ao2_container *sorted_tasks;
    struct ast_sip_sched_task *schtd;
    struct ast_tm tm;
    char times_run[16];
    char queued[32];
    char last_start[32];
    char next_start[32];
    struct timeval now;
    int using_regex = 0;
    regex_t regex;
    switch (cmd) {
    case CLI_INIT:
       e->command = "pjsip show scheduled_tasks";
       e->usage = "Usage: pjsip show scheduled_tasks [ like <pattern> ]\n"
                   "      Show scheduled pjsip tasks\n";
       return NULL;
    case CLI_GENERATE:
       return NULL;
    }
    if (a->argc != 3 && a->argc != 5) {
       return CLI_SHOWUSAGE;
    }
    if (a->argc == 5) {
       int regrc;
       if (strcasecmp(a->argv[3], "like")) {
          return CLI_SHOWUSAGE;
       }
       regrc = regcomp(&regex, a->argv[4], REG_EXTENDED | REG_ICASE | REG_NOSUB);
       if (regrc) {
          char err[256];
          regerror(regrc, &regex, err, 256);
          ast_cli(a->fd, "PJSIP Scheduled Tasks: Error: %s\n", err);
          return CLI_FAILURE;
       }
       using_regex = 1;
    }
    /* Get a sorted snapshot of the scheduled tasks */
    sorted_tasks = ao2_container_alloc_rbtree(AO2_ALLOC_OPT_LOCK_NOLOCK, 0,
       ast_sip_sched_task_sort_fn, NULL);
    if (!sorted_tasks) {
       ast_cli(a->fd, "PJSIP Scheduled Tasks: Unable to allocate temporary container\n");
       return CLI_FAILURE;
    }
    if (ao2_container_dup(sorted_tasks, tasks, 0)) {
       ao2_ref(sorted_tasks, -1);
       ast_cli(a->fd, "PJSIP Scheduled Tasks: Unable to sort temporary container\n");
       return CLI_FAILURE;
    }
    now = ast_tvnow();
    ast_localtime(&now, &tm, NULL);
    ast_cli(a->fd, "PJSIP Scheduled Tasks:\n\n");
    ast_cli(a->fd,
       "<Task Name....................................> <Interval> <Times Run> <State>"
       "  <Queued....>  <Last Start>  <Next Start.....secs>\n"
       "=============================================================================="
       "===================================================\n");
    iter = ao2_iterator_init(sorted_tasks, AO2_ITERATOR_UNLINK);
    for (; (schtd = ao2_iterator_next(&iter)); ao2_ref(schtd, -1)) {
       int next_run_sec;
       struct timeval next;
       ao2_lock(schtd);
       if (using_regex && regexec(&regex, schtd->name, 0, NULL, 0) == REG_NOMATCH) {
          ao2_unlock(schtd);
          continue;
       }
       next_run_sec = ast_sip_sched_task_get_next_run(schtd) / 1000;
       if (next_run_sec < 0) {
          /* Scheduled task is now canceled */
          ao2_unlock(schtd);
          continue;
       }
       next = ast_tvadd(now, ast_tv(next_run_sec, 0));
       ast_localtime(&schtd->when_queued, &tm, NULL);
       ast_strftime(queued, sizeof(queued), TIME_FORMAT, &tm);
       ast_localtime(&schtd->last_start, &tm, NULL);
       ast_strftime(last_start, sizeof(last_start), TIME_FORMAT, &tm);
       ast_localtime(&next, &tm, NULL);
       ast_strftime(next_start, sizeof(next_start), TIME_FORMAT, &tm);
       sprintf(times_run, "%d", schtd->run_count);
       ast_cli(a->fd, "%-46.46s   %9d   %9s   %-5s  %-12s  %-12s  %-12s %8d\n",
          schtd->name,
          schtd->interval / 1000,
          schtd->flags & AST_SIP_SCHED_TASK_ONESHOT ? "oneshot" : times_run,
          schtd->is_running ? "run" : "wait",
          queued,
          (ast_tvzero(schtd->last_start) || (schtd->flags & AST_SIP_SCHED_TASK_ONESHOT) ? "" : last_start),
          next_start,
          next_run_sec);
       ao2_unlock(schtd);
    }
    if (using_regex) {
       regfree(&regex);
    }
    ao2_iterator_destroy(&iter);
    ast_cli(a->fd, "\nTotal Scheduled Tasks: %d\n\n", ao2_container_count(sorted_tasks));
    ao2_ref(sorted_tasks, -1);
    return CLI_SUCCESS;
 }
push_to_serializer()
static int push_to_serializer (const void * data) static
Definition at line 157 of file pjsip_scheduler.c.
References ao2_lock, ao2_t_ref, ao2_unlink, ao2_unlock, ast_log, ast_sip_push_task(), AST_SIP_SCHED_TASK_TRACK, ast_sip_sched_task::current_scheduler_id, ast_sip_sched_task::flags, ast_sip_sched_task::interval, LOG_DEBUG, ast_sip_sched_task::name, run_task(), and ast_sip_sched_task::serializer.
Referenced by ast_sip_schedule_task(), and run_task().
 {
    struct ast_sip_sched_task *schtd = (struct ast_sip_sched_task *)data;
    int sched_id;
    ao2_lock(schtd);
    sched_id = schtd->current_scheduler_id;
    schtd->current_scheduler_id = -1;
    ao2_unlock(schtd);
    if (sched_id < 0) {
       /* Task was cancelled while waiting on the lock */
       return 0;
    }
    if (schtd->flags & AST_SIP_SCHED_TASK_TRACK) {
       ast_log(LOG_DEBUG, "Sched %p: Ready to run %s\n", schtd, schtd->name);
    }
    ao2_t_ref(schtd, +1, "Give ref to run_task()");
    if (ast_sip_push_task(schtd->serializer, run_task, schtd)) {
       /*
        * Oh my.  Have to cancel the scheduled item because we
        * unexpectedly cannot run it anymore.
        */
       ao2_unlink(tasks, schtd);
       ao2_lock(schtd);
       schtd->interval = 0;
       ao2_unlock(schtd);
       ao2_t_ref(schtd, -1, "Failed so release run_task() ref");
    }
    return 0;
 }
run_task()
static int run_task (void * data) static
Definition at line 80 of file pjsip_scheduler.c.
References ao2_cleanup, ao2_lock, ao2_unlink, ao2_unlock, ast_log, ast_samp2tv(), ast_sched_add(), AST_SIP_SCHED_TASK_DELAY, AST_SIP_SCHED_TASK_ONESHOT, AST_SIP_SCHED_TASK_TRACK, AST_SIP_SCHED_TASK_VARIABLE, ast_tvadd(), ast_tvdiff_ms(), ast_tvnow(), ast_sip_sched_task::interval, LOG_DEBUG, LOG_ERROR, push_to_serializer(), and RAII_VAR.
Referenced by push_to_serializer().
 {
    RAII_VAR(struct ast_sip_sched_task *, schtd, data, ao2_cleanup);
    int res;
    int delay;
    if (!schtd->interval) {
       /* Task was cancelled while waiting to be executed by the serializer */
       return -1;
    }
    if (schtd->flags & AST_SIP_SCHED_TASK_TRACK) {
       ast_log(LOG_DEBUG, "Sched %p: Running %s\n", schtd, schtd->name);
    }
    ao2_lock(schtd);
    schtd->last_start = ast_tvnow();
    schtd->is_running = 1;
    ++schtd->run_count;
    ao2_unlock(schtd);
    res = schtd->task(schtd->task_data);
    ao2_lock(schtd);
    schtd->is_running = 0;
    schtd->last_end = ast_tvnow();
    /*
     * Don't restart if the task returned <= 0 or if the interval
     * was set to 0 while the task was running
     */
    if ((schtd->flags & AST_SIP_SCHED_TASK_ONESHOT) || res <= 0 || !schtd->interval) {
       schtd->interval = 0;
       ao2_unlock(schtd);
       ao2_unlink(tasks, schtd);
       return -1;
    }
    if (schtd->flags & AST_SIP_SCHED_TASK_VARIABLE) {
       schtd->interval = res;
    }
    if (schtd->flags & AST_SIP_SCHED_TASK_DELAY) {
       delay = schtd->interval;
    } else {
       int64_t diff;
       /* Determine next periodic interval we need to expire. */
       do {
          schtd->next_periodic = ast_tvadd(schtd->next_periodic,
             ast_samp2tv(schtd->interval, 1000));
          diff = ast_tvdiff_ms(schtd->next_periodic, schtd->last_end);
       } while (diff <= 0);
       delay = diff;
    }
    schtd->current_scheduler_id = ast_sched_add(scheduler_context, delay, push_to_serializer, schtd);
    if (schtd->current_scheduler_id < 0) {
       schtd->interval = 0;
       ao2_unlock(schtd);
       ast_log(LOG_ERROR, "Sched %p: Failed to reschedule task %s\n", schtd, schtd->name);
       ao2_unlink(tasks, schtd);
       return -1;
    }
    ao2_unlock(schtd);
    if (schtd->flags & AST_SIP_SCHED_TASK_TRACK) {
       ast_log(LOG_DEBUG, "Sched %p: Rescheduled %s for %d ms\n", schtd, schtd->name,
          delay);
    }
    return 0;
 }
schtd_dtor()
static void schtd_dtor (void * data) static
Definition at line 399 of file pjsip_scheduler.c.
References ao2_ref, ast_free, ast_log, AST_SIP_SCHED_TASK_DATA_AO2, AST_SIP_SCHED_TASK_DATA_FREE, AST_SIP_SCHED_TASK_TRACK, ast_taskprocessor_unreference(), ast_sip_sched_task::flags, LOG_DEBUG, ast_sip_sched_task::name, ast_sip_sched_task::serializer, and ast_sip_sched_task::task_data.
Referenced by ast_sip_schedule_task().
 {
    struct ast_sip_sched_task *schtd = data;
    if (schtd->flags & AST_SIP_SCHED_TASK_TRACK) {
       ast_log(LOG_DEBUG, "Sched %p: Destructor %s\n", schtd, schtd->name);
    }
    if (schtd->flags & AST_SIP_SCHED_TASK_DATA_AO2) {
       /* release our own ref, then release the callers if asked to do so */
       ao2_ref(schtd->task_data, (schtd->flags & AST_SIP_SCHED_TASK_DATA_FREE) ? -2 : -1);
    } else if (schtd->task_data && (schtd->flags & AST_SIP_SCHED_TASK_DATA_FREE)) {
       ast_free(schtd->task_data);
    }
    ast_taskprocessor_unreference(schtd->serializer);
 }
Variable Documentation
cli_commands
struct ast_cli_entry cli_commands[] static
Initial value:
= {
   { .handler =  cli_show_tasks , .summary =  "Show pjsip scheduled tasks" ,},
}
Definition at line 610 of file pjsip_scheduler.c.
scheduler_context
struct ast_sched_context* scheduler_context static
Definition at line 37 of file pjsip_scheduler.c.
task_count
int task_count static
Definition at line 39 of file pjsip_scheduler.c.
Referenced by ast_sip_schedule_task().
tasks
struct ao2_container* tasks static
Definition at line 38 of file pjsip_scheduler.c.