Asterisk - The Open Source Telephony Project: pjsip_configuration.c File Reference
pjsip_configuration.c File Reference
#include "asterisk.h"
#include <pjsip.h>
#include <pjsip_ua.h>
#include "asterisk/res_pjsip.h"
#include "include/res_pjsip_private.h"
#include "asterisk/res_pjsip_cli.h"
#include "asterisk/acl.h"
#include "asterisk/manager.h"
#include "asterisk/astobj2.h"
#include "asterisk/utils.h"
#include "asterisk/sorcery.h"
#include "asterisk/callerid.h"
#include "asterisk/test.h"
#include "asterisk/statsd.h"
#include "asterisk/pbx.h"
#include "asterisk/stream.h"
#include "asterisk/stasis.h"
#include "asterisk/security_events.h"
Data Structures
struct sip_persistent_endpoint
Persistent endpoint information.
Macros
#define AMI_DEFAULT_STR_SIZE 512
#define AMI_SHOW_ENDPOINT "PJSIPShowEndpoint"
#define AMI_SHOW_ENDPOINTS "PJSIPShowEndpoints"
#define PERSISTENT_BUCKETS 53
Number of buckets for persistent endpoint information.
Functions
static void acl_change_stasis_cb (void *data, struct stasis_subscription *sub, struct stasis_message *message)
static int acl_to_str (const void *obj, const intptr_t *args, char **buf)
static void active_channels_to_str (const struct ast_sip_endpoint *endpoint, struct ast_str **str)
static int active_channels_to_str_cb (void *object, void *arg, int flags)
static int add_to_regcontext (void *obj, void *arg, int flags)
static int ami_show_endpoint (struct mansession *s, const struct message *m)
static int ami_show_endpoints (struct mansession *s, const struct message *m)
void ast_res_pjsip_destroy_configuration (void)
int ast_res_pjsip_initialize_configuration (void)
int ast_res_pjsip_reload_configuration (void)
void ast_sip_auth_vector_destroy (struct ast_sip_auth_vector *auths)
Free contents of an auth vector.
int ast_sip_auth_vector_init (struct ast_sip_auth_vector *auths, const char *value)
Initialize an auth vector with the configured values.
int ast_sip_auths_to_str (const struct ast_sip_auth_vector *auths, char **buf)
Converts an auths array to a string of comma separated values.
void ast_sip_cleanup_auths (struct ast_sip_auth *auths[], size_t num_auths)
Clean up retrieved auth structures from memory.
struct ast_str * ast_sip_create_ami_event (const char *event, struct ast_sip_ami *ami)
Creates a string to store AMI event data in.
struct ast_sip_endpoint * ast_sip_default_outbound_endpoint (void)
Retrieve the default outbound endpoint.
void * ast_sip_endpoint_alloc (const char *name)
Allocate a new SIP endpoint.
int ast_sip_for_each_channel (const struct ast_sip_endpoint *endpoint, ao2_callback_fn on_channel_snapshot, void *arg)
For every channel snapshot on an endpoint all the given 'on_channel_snapshot' handler.
int ast_sip_for_each_channel_snapshot (const struct ast_endpoint_snapshot *endpoint_snapshot, ao2_callback_fn on_channel_snapshot, void *arg)
For every channel snapshot on an endpoint snapshot call the given 'on_channel_snapshot' handler.
const char * ast_sip_get_device_state (const struct ast_sip_endpoint *endpoint)
Retrieve the device state for an endpoint.
struct ast_endpoint_snapshot * ast_sip_get_endpoint_snapshot (const struct ast_sip_endpoint *endpoint)
Retrieve the endpoint snapshot for an endpoint.
struct ao2_container * ast_sip_get_endpoints (void)
Retrieve any endpoints available to sorcery.
struct ast_sorcery * ast_sip_get_sorcery (void)
Get a pointer to the SIP sorcery structure.
int ast_sip_persistent_endpoint_add_to_regcontext (const char *regcontext)
void ast_sip_persistent_endpoint_publish_contact_state (const char *endpoint_name, const struct ast_sip_contact_status *contact_status)
Publish the change of state for a contact.
int ast_sip_persistent_endpoint_update_state (const char *endpoint_name, enum ast_endpoint_state state)
Change state of a persistent endpoint.
int ast_sip_retrieve_auths (const struct ast_sip_auth_vector *auths, struct ast_sip_auth **out)
Retrieve relevant SIP auth structures from sorcery.
int ast_sip_retrieve_auths_vector (const struct ast_sip_auth_vector *auth_ids, struct ast_sip_auth_objects_vector *auth_objects)
int ast_sip_sorcery_object_to_ami (const void *obj, struct ast_str **buf)
Converts a sorcery object to a string of object properties.
static int call_offer_pref_handler (const struct aco_option *opt, struct ast_variable *var, void *obj)
static int caller_id_handler (const struct aco_option *opt, struct ast_variable *var, void *obj)
static int caller_id_privacy_handler (const struct aco_option *opt, struct ast_variable *var, void *obj)
static int caller_id_privacy_to_str (const void *obj, const intptr_t *args, char **buf)
static int caller_id_tag_handler (const struct aco_option *opt, struct ast_variable *var, void *obj)
static int caller_id_tag_to_str (const void *obj, const intptr_t *args, char **buf)
static int caller_id_to_str (const void *obj, const intptr_t *args, char **buf)
static int callgroup_to_str (const void *obj, const intptr_t *args, char **buf)
static struct ao2_container * cli_endpoint_get_container (const char *regex)
static int cli_endpoint_iterate (void *obj, ao2_callback_fn callback, void *args)
static int cli_endpoint_print_body (void *obj, void *arg, int flags)
static void cli_endpoint_print_child_body (char *type, const void *obj, struct ast_sip_cli_context *context)
static void cli_endpoint_print_child_header (char *type, struct ast_sip_cli_context *context)
static int cli_endpoint_print_header (void *obj, void *arg, int flags)
static void * cli_endpoint_retrieve_by_id (const char *id)
static int codec_prefs_handler (const struct aco_option *opt, struct ast_variable *var, void *obj)
static int codec_prefs_to_str (const struct ast_stream_codec_negotiation_prefs *prefs, const void *obj, const intptr_t *args, char **buf)
static int connected_line_method_handler (const struct aco_option *opt, struct ast_variable *var, void *obj)
static int connected_line_method_to_str (const void *obj, const intptr_t *args, char **buf)
static int contact_acl_to_str (const void *obj, const intptr_t *args, char **buf)
static int contact_user_handler (const struct aco_option *opt, struct ast_variable *var, void *obj)
static int contact_user_to_str (const void *obj, const intptr_t *args, char **buf)
static int direct_media_glare_mitigation_handler (const struct aco_option *opt, struct ast_variable *var, void *obj)
static int direct_media_glare_mitigation_to_str (const void *obj, const intptr_t *args, char **buf)
static int direct_media_method_handler (const struct aco_option *opt, struct ast_variable *var, void *obj)
static int direct_media_method_to_str (const void *obj, const intptr_t *args, char **buf)
static int dtls_handler (const struct aco_option *opt, struct ast_variable *var, void *obj)
static int dtlsautogeneratecert_to_str (const void *obj, const intptr_t *args, char **buf)
static int dtlscafile_to_str (const void *obj, const intptr_t *args, char **buf)
static int dtlscapath_to_str (const void *obj, const intptr_t *args, char **buf)
static int dtlscertfile_to_str (const void *obj, const intptr_t *args, char **buf)
static int dtlscipher_to_str (const void *obj, const intptr_t *args, char **buf)
static int dtlsfingerprint_to_str (const void *obj, const intptr_t *args, char **buf)
static int dtlsprivatekey_to_str (const void *obj, const intptr_t *args, char **buf)
static int dtlsrekey_to_str (const void *obj, const intptr_t *args, char **buf)
static int dtlssetup_to_str (const void *obj, const intptr_t *args, char **buf)
static int dtlsverify_to_str (const void *obj, const intptr_t *args, char **buf)
static int dtmf_handler (const struct aco_option *opt, struct ast_variable *var, void *obj)
static int dtmf_to_str (const void *obj, const intptr_t *args, char **buf)
static int endpoint_acl_handler (const struct aco_option *opt, struct ast_variable *var, void *obj)
static void endpoint_deleted_observer (const void *object)
static void endpoint_destructor (void *obj)
static int format_ami_endpoint (const struct ast_sip_endpoint *endpoint, struct ast_sip_ami *ami)
static int format_ami_endpoints (void *obj, void *arg, int flags)
static int format_str_append_auth (const struct ast_sip_auth_vector *auths, struct ast_str **buf)
static int from_user_handler (const struct aco_option *opt, struct ast_variable *var, void *obj)
static int from_user_to_str (const void *obj, const intptr_t *args, char **buf)
static int group_handler (const struct aco_option *opt, struct ast_variable *var, void *obj)
static int ident_handler (const struct aco_option *opt, struct ast_variable *var, void *obj)
static int ident_to_str (const void *obj, const intptr_t *args, char **buf)
static int inbound_auth_handler (const struct aco_option *opt, struct ast_variable *var, void *obj)
static int inbound_auths_to_str (const void *obj, const intptr_t *args, char **buf)
static int incoming_answer_codec_prefs_to_str (const void *obj, const intptr_t *args, char **buf)
static int incoming_call_offer_pref_to_str (const void *obj, const intptr_t *args, char **buf)
static int incoming_offer_codec_prefs_to_str (const void *obj, const intptr_t *args, char **buf)
static void info_configuration_destroy (struct ast_sip_endpoint_info_configuration *info)
static int init_info_configuration (struct ast_sip_endpoint_info_configuration *info)
static int init_media_configuration (struct ast_sip_endpoint_media_configuration *media)
static int init_subscription_configuration (struct ast_sip_endpoint_subscription_configuration *subscription)
static void load_all_endpoints (void)
static void media_configuration_destroy (struct ast_sip_endpoint_media_configuration *media)
static int media_encryption_handler (const struct aco_option *opt, struct ast_variable *var, void *obj)
static int media_encryption_to_str (const void *obj, const intptr_t *args, char **buf)
static int named_callgroups_to_str (const void *obj, const intptr_t *args, char **buf)
static int named_groups_handler (const struct aco_option *opt, struct ast_variable *var, void *obj)
static int named_pickupgroups_to_str (const void *obj, const intptr_t *args, char **buf)
static int outbound_auth_handler (const struct aco_option *opt, struct ast_variable *var, void *obj)
static int outbound_auths_to_str (const void *obj, const intptr_t *args, char **buf)
static int outgoing_answer_codec_prefs_to_str (const void *obj, const intptr_t *args, char **buf)
static int outgoing_call_offer_pref_to_str (const void *obj, const intptr_t *args, char **buf)
static int outgoing_offer_codec_prefs_to_str (const void *obj, const intptr_t *args, char **buf)
static int persistent_endpoint_cmp (void *obj, void *arg, int flags)
Comparison function for persistent endpoint information.
static void persistent_endpoint_destroy (void *obj)
Destructor function for persistent endpoint information.
static struct ast_endpoint * persistent_endpoint_find_or_create (const struct ast_sip_endpoint *endpoint)
Internal function which finds (or creates) persistent endpoint information.
static int persistent_endpoint_hash (const void *obj, const int flags)
Hashing function for persistent endpoint information.
static int pickupgroup_to_str (const void *obj, const intptr_t *args, char **buf)
static int prack_handler (const struct aco_option *opt, struct ast_variable *var, void *obj)
static int prack_to_str (const void *obj, const intptr_t *args, char **buf)
static int redirect_handler (const struct aco_option *opt, struct ast_variable *var, void *obj)
static int set_var_handler (const struct aco_option *opt, struct ast_variable *var, void *obj)
static int set_var_to_str (const void *obj, const intptr_t *args, char **buf)
static int set_var_to_vl (const void *obj, struct ast_variable **fields)
static int sip_endpoint_apply_handler (const struct ast_sorcery *sorcery, void *obj)
Callback function for when an object is finalized.
static int sip_endpoint_identifier_str2type (const char *str)
static const char * sip_endpoint_identifier_type2str (enum ast_sip_endpoint_identifier_type method)
static int sip_endpoint_to_ami (const struct ast_sip_endpoint *endpoint, struct ast_str **buf)
static int sip_endpoints_aors_ami (void *obj, void *arg, int flags)
static void * sip_nat_hook_alloc (const char *name)
static void sip_sorcery_object_ami_set_type_name (const void *obj, struct ast_str **buf)
static void subscription_configuration_destroy (struct ast_sip_endpoint_subscription_configuration *subscription)
static int t38udptl_ec_handler (const struct aco_option *opt, struct ast_variable *var, void *obj)
static int t38udptl_ec_to_str (const void *obj, const intptr_t *args, char **buf)
static int timers_handler (const struct aco_option *opt, struct ast_variable *var, void *obj)
static int timers_to_str (const void *obj, const intptr_t *args, char **buf)
static int tos_audio_to_str (const void *obj, const intptr_t *args, char **buf)
static int tos_handler (const struct aco_option *opt, struct ast_variable *var, void *obj)
static int tos_video_to_str (const void *obj, const intptr_t *args, char **buf)
static int voicemail_extension_handler (const struct aco_option *opt, struct ast_variable *var, void *obj)
static int voicemail_extension_to_str (const void *obj, const intptr_t *args, char **buf)
Variables
static struct stasis_subscription * acl_change_sub
static const char * ast_rtp_dtls_fingerprint_map []
static const char * ast_rtp_dtls_setup_map []
static const char * ast_t38_ec_modes_map []
struct ast_sip_cli_formatter_entry * channel_formatter
static struct ast_cli_entry cli_commands []
static const char * direct_media_glare_mitigation_map []
struct ast_sip_cli_formatter_entry * endpoint_formatter
static const struct ast_sorcery_observer endpoint_observers
static const char * id_configuration_refresh_methods []
static const char * media_encryption_map []
static struct ao2_container * persistent_endpoints
Container for persistent endpoint information.
static struct ast_sorcery * sip_sorcery
Macro Definition Documentation
AMI_DEFAULT_STR_SIZE
#define AMI_DEFAULT_STR_SIZE 512
Definition at line 1582 of file pjsip_configuration.c.
Referenced by ast_sip_create_ami_event().
AMI_SHOW_ENDPOINT
#define AMI_SHOW_ENDPOINT "PJSIPShowEndpoint"
Definition at line 1674 of file pjsip_configuration.c.
Referenced by ami_show_endpoint(), ast_res_pjsip_destroy_configuration(), and ast_res_pjsip_initialize_configuration().
AMI_SHOW_ENDPOINTS
#define AMI_SHOW_ENDPOINTS "PJSIPShowEndpoints"
Definition at line 1673 of file pjsip_configuration.c.
Referenced by ast_res_pjsip_destroy_configuration(), and ast_res_pjsip_initialize_configuration().
PERSISTENT_BUCKETS
#define PERSISTENT_BUCKETS 53
Number of buckets for persistent endpoint information.
Definition at line 41 of file pjsip_configuration.c.
Referenced by ast_res_pjsip_initialize_configuration().
Function Documentation
acl_change_stasis_cb()
static void acl_change_stasis_cb (void * data, struct stasis_subscription * sub, struct stasis_message * message) static
Definition at line 1963 of file pjsip_configuration.c.
References ast_named_acl_change_type(), ast_sorcery_force_reload_object(), and stasis_message_type().
Referenced by ast_res_pjsip_initialize_configuration().
 {
    if (stasis_message_type(message) != ast_named_acl_change_type()) {
       return;
    }
    ast_sorcery_force_reload_object(sip_sorcery, "endpoint");
 }
acl_to_str()
static int acl_to_str (const void * obj, const intptr_t * args, char ** buf) static
Definition at line 104 of file pjsip_configuration.c.
References ast_sip_endpoint::acl, ast_acl_list_is_empty(), AST_LIST_FIRST, AST_LIST_LOCK, AST_LIST_UNLOCK, ast_strdup, ast_strlen_zero, sip_persistent_endpoint::endpoint, and ast_acl::name.
Referenced by ast_res_pjsip_initialize_configuration().
 {
    const struct ast_sip_endpoint *endpoint = obj;
    struct ast_acl_list *acl_list;
    struct ast_acl *first_acl;
    if (endpoint && !ast_acl_list_is_empty(acl_list=endpoint->acl)) {
       AST_LIST_LOCK(acl_list);
       first_acl = AST_LIST_FIRST(acl_list);
       if (ast_strlen_zero(first_acl->name)) {
          *buf = "deny/permit";
       } else {
          *buf = first_acl->name;
       }
       AST_LIST_UNLOCK(acl_list);
    }
    *buf = ast_strdup(*buf);
    return 0;
 }
active_channels_to_str()
static void active_channels_to_str (const struct ast_sip_endpoint * endpoint, struct ast_str ** str) static
Definition at line 1566 of file pjsip_configuration.c.
References active_channels_to_str_cb(), ao2_cleanup, ast_sip_for_each_channel_snapshot(), ast_sip_get_endpoint_snapshot(), ast_str_truncate(), and RAII_VAR.
Referenced by format_ami_endpoints(), and sip_endpoint_to_ami().
 {
    RAII_VAR(struct ast_endpoint_snapshot *, endpoint_snapshot,
        ast_sip_get_endpoint_snapshot(endpoint), ao2_cleanup);
    if (endpoint_snapshot) {
       return;
    }
    ast_sip_for_each_channel_snapshot(endpoint_snapshot,
                  active_channels_to_str_cb, str);
    ast_str_truncate(*str, -1);
 }
active_channels_to_str_cb()
static int active_channels_to_str_cb (void * object, void * arg, int flags) static
Definition at line 1558 of file pjsip_configuration.c.
References ast_str_append(), ast_channel_snapshot::base, buf, and ast_channel_snapshot_base::name.
Referenced by active_channels_to_str().
 {
    const struct ast_channel_snapshot *snapshot = object;
    struct ast_str **buf = arg;
    ast_str_append(buf, 0, "%s,", snapshot->base->name);
    return 0;
 }
add_to_regcontext()
static int add_to_regcontext (void * obj, void * arg, int flags) static
Definition at line 1296 of file pjsip_configuration.c.
References ast_add_extension(), ast_endpoint_get_resource(), ast_endpoint_get_state(), AST_ENDPOINT_ONLINE, ast_exists_extension(), ast_free_ptr(), ast_strdup, sip_persistent_endpoint::endpoint, NULL, and regcontext.
Referenced by ast_sip_persistent_endpoint_add_to_regcontext().
 {
    struct sip_persistent_endpoint *persistent = obj;
    const char *regcontext = arg;
    if (ast_endpoint_get_state(persistent->endpoint) == AST_ENDPOINT_ONLINE) {
       if (!ast_exists_extension(NULL, regcontext, ast_endpoint_get_resource(
             persistent->endpoint), 1, NULL)) {
          ast_add_extension(regcontext, 1, ast_endpoint_get_resource(persistent->endpoint), 1, NULL, NULL,
             "Noop", ast_strdup(ast_endpoint_get_resource(persistent->endpoint)), ast_free_ptr, "PJSIP");
       }
    }
    return 0;
 }
ami_show_endpoint()
static int ami_show_endpoint (struct mansession * s, const struct message * m) static
Definition at line 1676 of file pjsip_configuration.c.
References AMI_SHOW_ENDPOINT, ao2_cleanup, ast_sip_format_endpoint_ami(), ast_sip_get_sorcery(), ast_sorcery_retrieve_by_id(), ast_strlen_zero, astman_get_header(), astman_send_error_va(), astman_send_list_complete_end(), astman_send_list_complete_start(), astman_send_listack(), ast_sip_ami::count, sip_persistent_endpoint::endpoint, format_ami_endpoint(), ast_sip_ami::m, NULL, RAII_VAR, and ast_sip_ami::s.
Referenced by ast_res_pjsip_initialize_configuration().
 {
    struct ast_sip_ami ami = { .s = s, .m = m, .action_id = astman_get_header(m, "ActionID"),
       .count = 0, };
    RAII_VAR(struct ast_sip_endpoint *, endpoint, NULL, ao2_cleanup);
    const char *endpoint_name = astman_get_header(m, "Endpoint");
    int count = 0;
    if (ast_strlen_zero(endpoint_name)) {
       astman_send_error_va(s, m, "%s requires an endpoint name\n",
          AMI_SHOW_ENDPOINT);
       return 0;
    }
    if (!strncasecmp(endpoint_name, "pjsip/", 6)) {
       endpoint_name += 6;
    }
    if (!(endpoint = ast_sorcery_retrieve_by_id(
             ast_sip_get_sorcery(), "endpoint", endpoint_name))) {
       astman_send_error_va(s, m, "Unable to retrieve endpoint %s\n",
          endpoint_name);
       return 0;
    }
    astman_send_listack(s, m, "Following are Events for each object associated with the Endpoint",
       "start");
    /* the endpoint detail needs to always come first so apply as such */
    if (format_ami_endpoint(endpoint, &ami) ||
        ast_sip_format_endpoint_ami(endpoint, &ami, &count)) {
       astman_send_error_va(s, m, "Unable to format endpoint %s\n",
          endpoint_name);
    }
    astman_send_list_complete_start(s, m, "EndpointDetailComplete", ami.count + 1);
    astman_send_list_complete_end(s);
    return 0;
 }
ami_show_endpoints()
static int ami_show_endpoints (struct mansession * s, const struct message * m) static
Definition at line 1769 of file pjsip_configuration.c.
References ao2_callback, ao2_cleanup, ao2_container_count(), ast_sip_get_endpoints(), astman_get_header(), astman_send_error(), astman_send_list_complete_end(), astman_send_list_complete_start(), astman_send_listack(), endpoints, format_ami_endpoints(), ast_sip_ami::m, NULL, OBJ_NODATA, RAII_VAR, and ast_sip_ami::s.
Referenced by ast_res_pjsip_initialize_configuration().
 {
    struct ast_sip_ami ami = { .s = s, .m = m, .action_id = astman_get_header(m, "ActionID"), };
    RAII_VAR(struct ao2_container *, endpoints, NULL, ao2_cleanup);
    int num;
    endpoints = ast_sip_get_endpoints();
    if (!endpoints) {
       astman_send_error(s, m, "Could not get endpoints\n");
       return 0;
    }
    if (!(num = ao2_container_count(endpoints))) {
       astman_send_error(s, m, "No endpoints found\n");
       return 0;
    }
    astman_send_listack(s, m, "A listing of Endpoints follows, presented as EndpointList events",
       "start");
    ao2_callback(endpoints, OBJ_NODATA, format_ami_endpoints, &ami);
    astman_send_list_complete_start(s, m, "EndpointListComplete", num);
    astman_send_list_complete_end(s);
    return 0;
 }
ast_res_pjsip_destroy_configuration()
void ast_res_pjsip_destroy_configuration (void)
Definition at line 2219 of file pjsip_configuration.c.
References AMI_SHOW_ENDPOINT, AMI_SHOW_ENDPOINTS, ao2_cleanup, ARRAY_LEN, ast_cli_unregister_multiple(), ast_manager_unregister(), ast_sip_destroy_cli(), ast_sip_destroy_sorcery_auth(), ast_sip_destroy_sorcery_global(), ast_sip_destroy_sorcery_location(), ast_sip_destroy_sorcery_transport(), ast_sip_unregister_cli_formatter(), ast_sorcery_unref, NULL, and stasis_unsubscribe_and_join().
Referenced by unload_pjsip().
 {
    if (!sip_sorcery) {
       return;
    }
    acl_change_sub = stasis_unsubscribe_and_join(acl_change_sub);
    ast_sip_destroy_sorcery_global();
    ast_sip_destroy_sorcery_location();
    ast_sip_destroy_sorcery_auth();
    ast_sip_destroy_sorcery_transport();
    ast_sorcery_unref(sip_sorcery);
    sip_sorcery = NULL;
    ast_manager_unregister(AMI_SHOW_ENDPOINT);
    ast_manager_unregister(AMI_SHOW_ENDPOINTS);
    ast_cli_unregister_multiple(cli_commands, ARRAY_LEN(cli_commands));
    ast_sip_unregister_cli_formatter(endpoint_formatter);
    ast_sip_destroy_cli();
    ao2_cleanup(persistent_endpoints);
    persistent_endpoints = NULL;
 }
ast_res_pjsip_initialize_configuration()
int ast_res_pjsip_initialize_configuration (void)
Definition at line 1973 of file pjsip_configuration.c.
References accountcode, acl_change_stasis_cb(), acl_to_str(), AMI_SHOW_ENDPOINT, ami_show_endpoint(), AMI_SHOW_ENDPOINTS, ami_show_endpoints(), ao2_alloc, AO2_ALLOC_OPT_LOCK_MUTEX, ao2_container_alloc_hash, ARRAY_LEN, ast_cli_register_multiple, ast_log, ast_manager_register_xml, ast_named_acl_change_type(), ast_security_topic(), ast_sip_endpoint_alloc(), ast_sip_initialize_cli(), ast_sip_initialize_sorcery_auth(), ast_sip_initialize_sorcery_domain_alias(), ast_sip_initialize_sorcery_global(), ast_sip_initialize_sorcery_location(), ast_sip_initialize_sorcery_transport(), ast_sip_location_prune_boot_contacts(), ast_sip_register_cli_formatter(), ast_sorcery_apply_default, ast_sorcery_internal_object_register, ast_sorcery_load(), ast_sorcery_object_field_register, ast_sorcery_object_field_register_alias, ast_sorcery_object_field_register_custom, ast_sorcery_object_get_id(), ast_sorcery_object_register, ast_sorcery_observer_add(), ast_sorcery_open, ast_sorcery_unref, call_offer_pref_handler(), caller_id_handler(), caller_id_privacy_handler(), caller_id_privacy_to_str(), caller_id_tag_handler(), caller_id_tag_to_str(), caller_id_to_str(), callgroup_to_str(), CHARFLDSET, cli_endpoint_get_container(), cli_endpoint_iterate(), cli_endpoint_print_body(), cli_endpoint_print_header(), cli_endpoint_retrieve_by_id(), codec_prefs_handler(), connected_line_method_handler(), connected_line_method_to_str(), contact_acl_to_str(), contact_user_handler(), contact_user_to_str(), context, ast_sip_endpoint::context, direct_media_glare_mitigation_handler(), direct_media_glare_mitigation_to_str(), direct_media_method_handler(), direct_media_method_to_str(), dtls_handler(), dtlsautogeneratecert_to_str(), dtlscafile_to_str(), dtlscapath_to_str(), dtlscertfile_to_str(), dtlscipher_to_str(), dtlsfingerprint_to_str(), dtlsprivatekey_to_str(), dtlsrekey_to_str(), dtlssetup_to_str(), dtlsverify_to_str(), dtmf_handler(), dtmf_to_str(), endpoint_acl_handler(), EVENT_FLAG_SYSTEM, FLDSET, from_user_handler(), from_user_to_str(), ast_sip_endpoint::fromuser, ast_sip_cli_formatter_entry::get_container, ast_sip_cli_formatter_entry::get_id, group_handler(), ident_handler(), ident_to_str(), inbound_auth_handler(), inbound_auths_to_str(), incoming_answer_codec_prefs_to_str(), incoming_call_offer_pref_to_str(), incoming_offer_codec_prefs_to_str(), sip_to_pjsip::info(), ast_sip_cli_formatter_entry::iterate, language, load_all_endpoints(), LOG_ERROR, media_encryption_handler(), media_encryption_to_str(), mohsuggest, ast_sip_cli_formatter_entry::name, named_callgroups_to_str(), named_groups_handler(), named_pickupgroups_to_str(), nat, ast_sip_endpoint::nat, NULL, OPT_BOOL_T, OPT_CHAR_ARRAY_T, OPT_CODEC_T, OPT_NOOP_T, OPT_STRINGFIELD_T, OPT_UINT_T, OPT_YESNO_T, outbound_auth_handler(), outbound_auths_to_str(), outgoing_answer_codec_prefs_to_str(), outgoing_call_offer_pref_to_str(), outgoing_offer_codec_prefs_to_str(), PERSISTENT_BUCKETS, persistent_endpoint_cmp(), persistent_endpoint_hash(), pickupgroup_to_str(), prack_handler(), prack_to_str(), ast_sip_cli_formatter_entry::print_body, ast_sip_cli_formatter_entry::print_header, redirect_handler(), ast_sip_cli_formatter_entry::retrieve_by_id, set_var_handler(), set_var_to_str(), set_var_to_vl(), sip_endpoint_apply_handler(), sip_nat_hook_alloc(), stasis_subscribe, stasis_subscription_accept_message_type(), STASIS_SUBSCRIPTION_FILTER_SELECTIVE, stasis_subscription_set_filter(), STRFLDSET, t38udptl_ec_handler(), t38udptl_ec_to_str(), timers_handler(), timers_to_str(), tos_audio_to_str(), tos_handler(), tos_video_to_str(), voicemail_extension_handler(), and voicemail_extension_to_str().
Referenced by load_module().
 {
    if (ast_manager_register_xml(AMI_SHOW_ENDPOINTS, EVENT_FLAG_SYSTEM, ami_show_endpoints) ||
        ast_manager_register_xml(AMI_SHOW_ENDPOINT, EVENT_FLAG_SYSTEM, ami_show_endpoint)) {
       return -1;
    }
    persistent_endpoints = ao2_container_alloc_hash(AO2_ALLOC_OPT_LOCK_MUTEX, 0,
       PERSISTENT_BUCKETS, persistent_endpoint_hash, NULL, persistent_endpoint_cmp);
    if (!persistent_endpoints) {
       return -1;
    }
    if (!(sip_sorcery = ast_sorcery_open())) {
       ast_log(LOG_ERROR, "Failed to open SIP sorcery failed to open\n");
       return -1;
    }
    ast_sip_initialize_cli();
    if (ast_sip_initialize_sorcery_auth()) {
       ast_log(LOG_ERROR, "Failed to register SIP authentication support\n");
       ast_sorcery_unref(sip_sorcery);
       sip_sorcery = NULL;
       return -1;
    }
    ast_sorcery_apply_default(sip_sorcery, "endpoint", "config", "pjsip.conf,criteria=type=endpoint");
    ast_sorcery_apply_default(sip_sorcery, "nat_hook", "memory", NULL);
    if (ast_sorcery_object_register(sip_sorcery, "endpoint", ast_sip_endpoint_alloc, NULL, sip_endpoint_apply_handler)) {
       ast_log(LOG_ERROR, "Failed to register SIP endpoint object with sorcery\n");
       ast_sorcery_unref(sip_sorcery);
       sip_sorcery = NULL;
       return -1;
    }
    if (ast_sorcery_internal_object_register(sip_sorcery, "nat_hook", sip_nat_hook_alloc, NULL, NULL)) {
       ast_log(LOG_ERROR, "Failed to register nat_hook\n");
    }
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "type", "", OPT_NOOP_T, 0, 0);
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "context", "default", OPT_STRINGFIELD_T, 0, STRFLDSET(struct ast_sip_endpoint, context));
    ast_sorcery_object_field_register_alias(sip_sorcery, "endpoint", "disallow", "", OPT_CODEC_T, 0, FLDSET(struct ast_sip_endpoint, media.codecs));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "allow", "", OPT_CODEC_T, 1, FLDSET(struct ast_sip_endpoint, media.codecs));
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "dtmf_mode", "rfc4733", dtmf_handler, dtmf_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "rtp_ipv6", "no", OPT_BOOL_T, 1, FLDSET(struct ast_sip_endpoint, media.rtp.ipv6));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "rtp_symmetric", "no", OPT_BOOL_T, 1, FLDSET(struct ast_sip_endpoint, media.rtp.symmetric));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "ice_support", "no", OPT_BOOL_T, 1, FLDSET(struct ast_sip_endpoint, media.rtp.ice_support));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "use_ptime", "no", OPT_BOOL_T, 1, FLDSET(struct ast_sip_endpoint, media.rtp.use_ptime));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "force_rport", "yes", OPT_BOOL_T, 1, FLDSET(struct ast_sip_endpoint, nat.force_rport));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "rewrite_contact", "no", OPT_BOOL_T, 1, FLDSET(struct ast_sip_endpoint, nat.rewrite_contact));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "transport", "", OPT_STRINGFIELD_T, 0, STRFLDSET(struct ast_sip_endpoint, transport));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "outbound_proxy", "", OPT_STRINGFIELD_T, 0, STRFLDSET(struct ast_sip_endpoint, outbound_proxy));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "moh_suggest", "default", OPT_STRINGFIELD_T, 0, STRFLDSET(struct ast_sip_endpoint, mohsuggest));
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "100rel", "yes", prack_handler, prack_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "timers", "yes", timers_handler, timers_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "timers_min_se", "90", OPT_UINT_T, 0, FLDSET(struct ast_sip_endpoint, extensions.timer.min_se));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "timers_sess_expires", "1800", OPT_UINT_T, 0, FLDSET(struct ast_sip_endpoint, extensions.timer.sess_expires));
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "auth", "", inbound_auth_handler, inbound_auths_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "outbound_auth", "", outbound_auth_handler, outbound_auths_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "aors", "", OPT_STRINGFIELD_T, 0, STRFLDSET(struct ast_sip_endpoint, aors));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "media_address", "", OPT_STRINGFIELD_T, 0, STRFLDSET(struct ast_sip_endpoint, media.address));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "bind_rtp_to_media_address", "no", OPT_BOOL_T, 1, STRFLDSET(struct ast_sip_endpoint, media.bind_rtp_to_media_address));
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "identify_by", "username,ip", ident_handler, ident_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "direct_media", "yes", OPT_BOOL_T, 1, FLDSET(struct ast_sip_endpoint, media.direct_media.enabled));
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "direct_media_method", "invite", direct_media_method_handler, direct_media_method_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "trust_connected_line", "yes", OPT_YESNO_T, 1, FLDSET(struct ast_sip_endpoint, id.trust_connected_line));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "send_connected_line", "yes", OPT_YESNO_T, 1, FLDSET(struct ast_sip_endpoint, id.send_connected_line));
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "connected_line_method", "invite", connected_line_method_handler, connected_line_method_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "direct_media_glare_mitigation", "none", direct_media_glare_mitigation_handler, direct_media_glare_mitigation_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "disable_direct_media_on_nat", "no", OPT_BOOL_T, 1, FLDSET(struct ast_sip_endpoint, media.direct_media.disable_on_nat));
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "callerid", "", caller_id_handler, caller_id_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "callerid_privacy", "allowed_not_screened", caller_id_privacy_handler, caller_id_privacy_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "callerid_tag", "", caller_id_tag_handler, caller_id_tag_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "trust_id_inbound", "no", OPT_BOOL_T, 1, FLDSET(struct ast_sip_endpoint, id.trust_inbound));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "trust_id_outbound", "no", OPT_BOOL_T, 1, FLDSET(struct ast_sip_endpoint, id.trust_outbound));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "send_pai", "no", OPT_BOOL_T, 1, FLDSET(struct ast_sip_endpoint, id.send_pai));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "send_rpid", "no", OPT_BOOL_T, 1, FLDSET(struct ast_sip_endpoint, id.send_rpid));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "rpid_immediate", "no", OPT_BOOL_T, 1, FLDSET(struct ast_sip_endpoint, id.rpid_immediate));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "send_diversion", "yes", OPT_BOOL_T, 1, FLDSET(struct ast_sip_endpoint, id.send_diversion));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "send_history_info", "no", OPT_BOOL_T, 1, FLDSET(struct ast_sip_endpoint, id.send_history_info));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "mailboxes", "", OPT_STRINGFIELD_T, 0, STRFLDSET(struct ast_sip_endpoint, subscription.mwi.mailboxes));
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "voicemail_extension", "", voicemail_extension_handler, voicemail_extension_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "aggregate_mwi", "yes", OPT_BOOL_T, 1, FLDSET(struct ast_sip_endpoint, subscription.mwi.aggregate));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "mwi_subscribe_replaces_unsolicited", "no", OPT_YESNO_T, 1, FLDSET(struct ast_sip_endpoint, subscription.mwi.subscribe_replaces_unsolicited));
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "media_encryption", "no", media_encryption_handler, media_encryption_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "use_avpf", "no", OPT_BOOL_T, 1, FLDSET(struct ast_sip_endpoint, media.rtp.use_avpf));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "force_avp", "no", OPT_BOOL_T, 1, FLDSET(struct ast_sip_endpoint, media.rtp.force_avp));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "media_use_received_transport", "no", OPT_BOOL_T, 1, FLDSET(struct ast_sip_endpoint, media.rtp.use_received_transport));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "rtp_keepalive", "0", OPT_UINT_T, 0, FLDSET(struct ast_sip_endpoint, media.rtp.keepalive));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "rtp_timeout", "0", OPT_UINT_T, 0, FLDSET(struct ast_sip_endpoint, media.rtp.timeout));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "rtp_timeout_hold", "0", OPT_UINT_T, 0, FLDSET(struct ast_sip_endpoint, media.rtp.timeout_hold));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "one_touch_recording", "no", OPT_BOOL_T, 1, FLDSET(struct ast_sip_endpoint, info.recording.enabled));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "inband_progress", "no", OPT_BOOL_T, 1, FLDSET(struct ast_sip_endpoint, inband_progress));
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "call_group", "", group_handler, callgroup_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "pickup_group", "", group_handler, pickupgroup_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "named_call_group", "", named_groups_handler, named_callgroups_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "named_pickup_group", "", named_groups_handler, named_pickupgroups_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "device_state_busy_at", "0", OPT_UINT_T, 0, FLDSET(struct ast_sip_endpoint, devicestate_busy_at));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "t38_udptl", "no", OPT_BOOL_T, 1, FLDSET(struct ast_sip_endpoint, media.t38.enabled));
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "t38_udptl_ec", "none", t38udptl_ec_handler, t38udptl_ec_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "t38_udptl_maxdatagram", "0", OPT_UINT_T, 0, FLDSET(struct ast_sip_endpoint, media.t38.maxdatagram));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "fax_detect", "no", OPT_BOOL_T, 1, FLDSET(struct ast_sip_endpoint, faxdetect));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "fax_detect_timeout", "0", OPT_UINT_T, 0, FLDSET(struct ast_sip_endpoint, faxdetect_timeout));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "t38_udptl_nat", "no", OPT_BOOL_T, 1, FLDSET(struct ast_sip_endpoint, media.t38.nat));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "t38_udptl_ipv6", "no", OPT_BOOL_T, 1, FLDSET(struct ast_sip_endpoint, media.t38.ipv6));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "tone_zone", "", OPT_STRINGFIELD_T, 0, STRFLDSET(struct ast_sip_endpoint, zone));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "language", "", OPT_STRINGFIELD_T, 0, STRFLDSET(struct ast_sip_endpoint, language));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "record_on_feature", "automixmon", OPT_STRINGFIELD_T, 0, STRFLDSET(struct ast_sip_endpoint, info.recording.onfeature));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "record_off_feature", "automixmon", OPT_STRINGFIELD_T, 0, STRFLDSET(struct ast_sip_endpoint, info.recording.offfeature));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "allow_transfer", "yes", OPT_BOOL_T, 1, FLDSET(struct ast_sip_endpoint, allowtransfer));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "user_eq_phone", "no", OPT_BOOL_T, 1, FLDSET(struct ast_sip_endpoint, usereqphone));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "moh_passthrough", "no", OPT_BOOL_T, 1, FLDSET(struct ast_sip_endpoint, moh_passthrough));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "sdp_owner", "-", OPT_STRINGFIELD_T, 0, STRFLDSET(struct ast_sip_endpoint, media.sdpowner));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "sdp_session", "Asterisk", OPT_STRINGFIELD_T, 0, STRFLDSET(struct ast_sip_endpoint, media.sdpsession));
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "tos_audio", "0", tos_handler, tos_audio_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "tos_video", "0", tos_handler, tos_video_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "cos_audio", "0", OPT_UINT_T, 0, FLDSET(struct ast_sip_endpoint, media.cos_audio));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "cos_video", "0", OPT_UINT_T, 0, FLDSET(struct ast_sip_endpoint, media.cos_video));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "allow_subscribe", "yes", OPT_BOOL_T, 1, FLDSET(struct ast_sip_endpoint, subscription.allow));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "sub_min_expiry", "0", OPT_UINT_T, 0, FLDSET(struct ast_sip_endpoint, subscription.minexpiry));
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "from_user", "", from_user_handler, from_user_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "from_domain", "", OPT_STRINGFIELD_T, 0, STRFLDSET(struct ast_sip_endpoint, fromdomain));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "mwi_from_user", "", OPT_STRINGFIELD_T, 0, STRFLDSET(struct ast_sip_endpoint, subscription.mwi.fromuser));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "rtp_engine", "asterisk", OPT_STRINGFIELD_T, 0, STRFLDSET(struct ast_sip_endpoint, media.rtp.engine));
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "dtls_verify", "no", dtls_handler, dtlsverify_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "dtls_rekey", "0", dtls_handler, dtlsrekey_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "dtls_auto_generate_cert", "no", dtls_handler, dtlsautogeneratecert_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "dtls_cert_file", "", dtls_handler, dtlscertfile_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "dtls_private_key", "", dtls_handler, dtlsprivatekey_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "dtls_cipher", "", dtls_handler, dtlscipher_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "dtls_ca_file", "", dtls_handler, dtlscafile_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "dtls_ca_path", "", dtls_handler, dtlscapath_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "dtls_setup", "", dtls_handler, dtlssetup_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "dtls_fingerprint", "", dtls_handler, dtlsfingerprint_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "srtp_tag_32", "no", OPT_BOOL_T, 1, FLDSET(struct ast_sip_endpoint, media.rtp.srtp_tag_32));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "media_encryption_optimistic", "no", OPT_BOOL_T, 1, FLDSET(struct ast_sip_endpoint, media.rtp.encryption_optimistic));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "g726_non_standard", "no", OPT_BOOL_T, 1, FLDSET(struct ast_sip_endpoint, media.g726_non_standard));
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "redirect_method", "user", redirect_handler, NULL, NULL, 0, 0);
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "set_var", "", set_var_handler, set_var_to_str, set_var_to_vl, 0, 0);
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "message_context", "", OPT_STRINGFIELD_T, 0, STRFLDSET(struct ast_sip_endpoint, message_context));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "accountcode", "", OPT_STRINGFIELD_T, 0, STRFLDSET(struct ast_sip_endpoint, accountcode));
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "deny", "", endpoint_acl_handler, NULL, NULL, 0, 0);
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "permit", "", endpoint_acl_handler, NULL, NULL, 0, 0);
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "acl", "", endpoint_acl_handler, acl_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "contact_deny", "", endpoint_acl_handler, NULL, NULL, 0, 0);
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "contact_permit", "", endpoint_acl_handler, NULL, NULL, 0, 0);
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "contact_acl", "", endpoint_acl_handler, contact_acl_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "subscribe_context", "", OPT_CHAR_ARRAY_T, 0, CHARFLDSET(struct ast_sip_endpoint, subscription.context));
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "contact_user", "", contact_user_handler, contact_user_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "preferred_codec_only", "no", OPT_BOOL_T, 1, FLDSET(struct ast_sip_endpoint, preferred_codec_only));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "asymmetric_rtp_codec", "no", OPT_BOOL_T, 1, FLDSET(struct ast_sip_endpoint, asymmetric_rtp_codec));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "rtcp_mux", "no", OPT_BOOL_T, 1, FLDSET(struct ast_sip_endpoint, media.rtcp_mux));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "allow_overlap", "yes", OPT_BOOL_T, 1, FLDSET(struct ast_sip_endpoint, allow_overlap));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "refer_blind_progress", "yes", OPT_BOOL_T, 1, FLDSET(struct ast_sip_endpoint, refer_blind_progress));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "notify_early_inuse_ringing", "no", OPT_BOOL_T, 1, FLDSET(struct ast_sip_endpoint, notify_early_inuse_ringing));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "max_audio_streams", "1", OPT_UINT_T, 0, FLDSET(struct ast_sip_endpoint, media.max_audio_streams));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "max_video_streams", "1", OPT_UINT_T, 0, FLDSET(struct ast_sip_endpoint, media.max_video_streams));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "bundle", "no", OPT_BOOL_T, 1, FLDSET(struct ast_sip_endpoint, media.bundle));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "webrtc", "no", OPT_YESNO_T, 1, FLDSET(struct ast_sip_endpoint, media.webrtc));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "incoming_mwi_mailbox", "", OPT_STRINGFIELD_T, 0, STRFLDSET(struct ast_sip_endpoint, incoming_mwi_mailbox));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "follow_early_media_fork", "yes", OPT_BOOL_T, 1, FLDSET(struct ast_sip_endpoint, media.rtp.follow_early_media_fork));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "accept_multiple_sdp_answers", "no", OPT_BOOL_T, 1, FLDSET(struct ast_sip_endpoint, media.rtp.accept_multiple_sdp_answers));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "suppress_q850_reason_headers", "no", OPT_BOOL_T, 1, FLDSET(struct ast_sip_endpoint, suppress_q850_reason_headers));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "ignore_183_without_sdp", "no", OPT_BOOL_T, 1, FLDSET(struct ast_sip_endpoint, ignore_183_without_sdp));
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "incoming_call_offer_pref", "local",
       call_offer_pref_handler, incoming_call_offer_pref_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "outgoing_call_offer_pref", "remote_merge",
       call_offer_pref_handler, outgoing_call_offer_pref_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "codec_prefs_incoming_offer",
       "prefer: pending, operation: intersect, keep: all, transcode: allow",
       codec_prefs_handler, incoming_offer_codec_prefs_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "codec_prefs_outgoing_offer",
       "prefer: pending, operation: union, keep: all, transcode: allow",
       codec_prefs_handler, outgoing_offer_codec_prefs_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "codec_prefs_incoming_answer",
       "prefer: pending, operation: intersect, keep: all",
       codec_prefs_handler, incoming_answer_codec_prefs_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "codec_prefs_outgoing_answer",
       "prefer: pending, operation: intersect, keep: all",
       codec_prefs_handler, outgoing_answer_codec_prefs_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "stir_shaken", "no", OPT_BOOL_T, 1, FLDSET(struct ast_sip_endpoint, stir_shaken));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "allow_unauthenticated_options", "no", OPT_BOOL_T, 1, FLDSET(struct ast_sip_endpoint, allow_unauthenticated_options));
    if (ast_sip_initialize_sorcery_transport()) {
       ast_log(LOG_ERROR, "Failed to register SIP transport support with sorcery\n");
       ast_sorcery_unref(sip_sorcery);
       sip_sorcery = NULL;
       return -1;
    }
    if (ast_sip_initialize_sorcery_location()) {
       ast_log(LOG_ERROR, "Failed to register SIP location support with sorcery\n");
       ast_sorcery_unref(sip_sorcery);
       sip_sorcery = NULL;
       return -1;
    }
    ast_sorcery_observer_add(sip_sorcery, "endpoint", &endpoint_observers);
    if (ast_sip_initialize_sorcery_domain_alias()) {
       ast_log(LOG_ERROR, "Failed to register SIP domain aliases support with sorcery\n");
       ast_sorcery_unref(sip_sorcery);
       sip_sorcery = NULL;
       return -1;
    }
    if (ast_sip_initialize_sorcery_global()) {
       ast_log(LOG_ERROR, "Failed to register SIP Global support\n");
       ast_sorcery_unref(sip_sorcery);
       sip_sorcery = NULL;
       return -1;
    }
    endpoint_formatter = ao2_alloc(sizeof(struct ast_sip_cli_formatter_entry), NULL);
    if (!endpoint_formatter) {
       ast_log(LOG_ERROR, "Unable to allocate memory for endpoint_formatter\n");
       ast_sorcery_unref(sip_sorcery);
       sip_sorcery = NULL;
       return -1;
    }
    endpoint_formatter->name = "endpoint";
    endpoint_formatter->print_header = cli_endpoint_print_header;
    endpoint_formatter->print_body = cli_endpoint_print_body;
    endpoint_formatter->get_container = cli_endpoint_get_container;
    endpoint_formatter->iterate = cli_endpoint_iterate;
    endpoint_formatter->retrieve_by_id = cli_endpoint_retrieve_by_id;
    endpoint_formatter->get_id = ast_sorcery_object_get_id;
    ast_sip_register_cli_formatter(endpoint_formatter);
    ast_cli_register_multiple(cli_commands, ARRAY_LEN(cli_commands));
    ast_sorcery_load(sip_sorcery);
    load_all_endpoints();
    ast_sip_location_prune_boot_contacts();
    acl_change_sub = stasis_subscribe(ast_security_topic(), acl_change_stasis_cb, NULL);
    stasis_subscription_accept_message_type(acl_change_sub, ast_named_acl_change_type());
    stasis_subscription_set_filter(acl_change_sub, STASIS_SUBSCRIPTION_FILTER_SELECTIVE);
    return 0;
 }
ast_res_pjsip_reload_configuration()
int ast_res_pjsip_reload_configuration (void)
Definition at line 2241 of file pjsip_configuration.c.
References ast_sorcery_reload().
Referenced by reload_configuration_task().
 {
    if (sip_sorcery) {
       ast_sorcery_reload(sip_sorcery);
    }
    return 0;
 }
ast_sip_auth_vector_destroy()
void ast_sip_auth_vector_destroy (struct ast_sip_auth_vector * vector)
Free contents of an auth vector.
Parameters
array Vector whose contents are to be freed
Definition at line 249 of file pjsip_configuration.c.
References ast_free, AST_VECTOR_FREE, AST_VECTOR_REMOVE_UNORDERED, AST_VECTOR_SIZE, and name.
Referenced by ast_sip_auth_vector_init(), endpoint_destructor(), handle_client_state_destruction(), sip_outbound_publish_destroy(), sip_outbound_registration_destroy(), and sip_outbound_registration_perform().
 {
    int i;
    size_t size;
    if (!auths) {
       return;
    }
    size = AST_VECTOR_SIZE(auths);
    for (i = 0; i < size; ++i) {
       const char *name = AST_VECTOR_REMOVE_UNORDERED(auths, 0);
       ast_free((char *) name);
    }
    AST_VECTOR_FREE(auths);
 }
ast_sip_auth_vector_init()
int ast_sip_auth_vector_init (struct ast_sip_auth_vector * vector, const char * auth_names)
Initialize an auth vector with the configured values.
Parameters
vector Vector to initialize
auth_names Comma-separated list of names to set in the array
Return values
0 Success
non-zero Failure
Definition at line 267 of file pjsip_configuration.c.
References ast_assert, ast_free, ast_sip_auth_vector_destroy(), ast_strdup, ast_strdupa, ast_strip(), ast_strlen_zero, AST_VECTOR_APPEND, AST_VECTOR_INIT, AST_VECTOR_SIZE, NULL, and strsep().
Referenced by inbound_auth_handler(), and outbound_auth_handler().
 {
    char *auth_names = ast_strdupa(value);
    char *val;
    ast_assert(auths != NULL);
    if (AST_VECTOR_SIZE(auths)) {
       ast_sip_auth_vector_destroy(auths);
    }
    if (AST_VECTOR_INIT(auths, 1)) {
       return -1;
    }
    while ((val = ast_strip(strsep(&auth_names, ",")))) {
       if (ast_strlen_zero(val)) {
          continue;
       }
       val = ast_strdup(val);
       if (!val) {
          goto failure;
       }
       if (AST_VECTOR_APPEND(auths, val)) {
          ast_free(val);
          goto failure;
       }
    }
    return 0;
 failure:
    ast_sip_auth_vector_destroy(auths);
    return -1;
 }
ast_sip_auths_to_str()
int ast_sip_auths_to_str (const struct ast_sip_auth_vector * auths, char ** buf)
Converts an auths array to a string of comma separated values.
Parameters
auths an auth array
buf the string buffer to write the object data
Return values
0 Success, non-zero on failure
Definition at line 317 of file pjsip_configuration.c.
References ast_calloc, ast_join_delim(), AST_VECTOR_SIZE, ast_sip_auth_vector::elems, and MAX_OBJECT_FIELD.
Referenced by format_str_append_auth(), inbound_auths_to_str(), and outbound_auths_to_str().
 {
    if (!auths || !AST_VECTOR_SIZE(auths)) {
       return 0;
    }
    if (!(*buf = ast_calloc(MAX_OBJECT_FIELD, sizeof(char)))) {
       return -1;
    }
    /* I feel like accessing the vector's elem array directly is cheating...*/
    ast_join_delim(*buf, MAX_OBJECT_FIELD, auths->elems, AST_VECTOR_SIZE(auths), ',');
    return 0;
 }
ast_sip_cleanup_auths()
void ast_sip_cleanup_auths (struct ast_sip_auth * auths[], size_t num_auths)
Clean up retrieved auth structures from memory.
Call this function once you have completed operating on auths retrieved from ast_sip_retrieve_auths
Parameters
auths An array of auth object pointers to clean up
num_auths The number of auths in the array
Definition at line 2377 of file pjsip_configuration.c.
References ao2_cleanup.
Referenced by digest_check_auth(), and set_outbound_initial_authentication_credentials().
 {
    int i;
    for (i = 0; i < num_auths; ++i) {
       ao2_cleanup(auths[i]);
    }
 }
ast_sip_create_ami_event()
struct ast_str* ast_sip_create_ami_event (const char * event, struct ast_sip_ami * ami)
Creates a string to store AMI event data in.
Parameters
event the event to set
ami AMI session and message container
Return values
an initialized ast_str or NULL on error.
Definition at line 1584 of file pjsip_configuration.c.
References ast_sip_ami::action_id, AMI_DEFAULT_STR_SIZE, ast_str_append(), ast_str_create, ast_str_set(), ast_strlen_zero, astman_send_error_va(), buf, ast_sip_ami::m, NULL, and ast_sip_ami::s.
Referenced by ami_outbound_registration_task(), ami_registrations_aor(), ami_subscription_detail(), ast_sip_format_contact_ami(), format_ami_aor_handler(), format_ami_aorlist_handler(), format_ami_auth_handler(), format_ami_authlist_handler(), format_ami_contactlist_handler(), format_ami_endpoint(), format_ami_endpoint_transport(), format_ami_endpoints(), format_ami_resource_lists(), and send_identify_ami_event().
 {
    struct ast_str *buf = ast_str_create(AMI_DEFAULT_STR_SIZE);
    if (!(buf)) {
       astman_send_error_va(ami->s, ami->m, "Unable create event "
                  "for %s\n", event);
       return NULL;
    }
    ast_str_set(&buf, 0, "Event: %s\r\n", event);
    if (!ast_strlen_zero(ami->action_id)) {
       ast_str_append(&buf, 0, "ActionID: %s\r\n", ami->action_id);
    }
    return buf;
 }
ast_sip_default_outbound_endpoint()
struct ast_sip_endpoint* ast_sip_default_outbound_endpoint (void)
Retrieve the default outbound endpoint.
Return values
The default outbound endpoint, NULL if not found.
Definition at line 2353 of file pjsip_configuration.c.
References ast_free, ast_sip_global_default_outbound_endpoint(), ast_sorcery_retrieve_by_id(), ast_strlen_zero, name, NULL, and RAII_VAR.
Referenced by get_outbound_endpoint(), handle_atsign(), handle_single_token(), and notify_uri().
 {
    RAII_VAR(char *, name, ast_sip_global_default_outbound_endpoint(), ast_free);
    return ast_strlen_zero(name) ? NULL : ast_sorcery_retrieve_by_id(
       sip_sorcery, "endpoint", name);
 }
ast_sip_endpoint_alloc()
void* ast_sip_endpoint_alloc (const char * name)
Allocate a new SIP endpoint.
This will return an endpoint with its refcount increased by one. This reference can be released using ao2_ref().
Parameters
name The name of the endpoint.
Return values
NULL Endpoint allocation failed
non-NULL The newly allocated endpoint
Definition at line 2306 of file pjsip_configuration.c.
References ao2_cleanup, ast_format_cap_alloc, AST_FORMAT_CAP_FLAG_DEFAULT, ast_party_id_init(), ast_sorcery_generic_alloc(), ast_strdup, ast_string_field_init, AST_VECTOR_INIT, ast_sip_endpoint_media_configuration::codecs, sip_persistent_endpoint::endpoint, endpoint_destructor(), ast_sip_endpoint::id, ast_sip_endpoint::ident_method_order, ast_sip_endpoint::info, init_info_configuration(), init_media_configuration(), init_subscription_configuration(), ast_sip_endpoint::media, NULL, ast_sip_endpoint_id_configuration::self, ast_sip_endpoint::subscription, and ast_party_id::tag.
Referenced by ast_res_pjsip_initialize_configuration().
 {
    struct ast_sip_endpoint *endpoint = ast_sorcery_generic_alloc(sizeof(*endpoint), endpoint_destructor);
    if (!endpoint) {
       return NULL;
    }
    if (ast_string_field_init(endpoint, 64)) {
       ao2_cleanup(endpoint);
       return NULL;
    }
    if (!(endpoint->media.codecs = ast_format_cap_alloc(AST_FORMAT_CAP_FLAG_DEFAULT))) {
       ao2_cleanup(endpoint);
       return NULL;
    }
    if (init_subscription_configuration(&endpoint->subscription)) {
       ao2_cleanup(endpoint);
       return NULL;
    }
    if (init_info_configuration(&endpoint->info)) {
       ao2_cleanup(endpoint);
       return NULL;
    }
    if (init_media_configuration(&endpoint->media)) {
       ao2_cleanup(endpoint);
       return NULL;
    }
    ast_party_id_init(&endpoint->id.self);
    endpoint->id.self.tag = ast_strdup("");
    if (AST_VECTOR_INIT(&endpoint->ident_method_order, 1)) {
       return NULL;
    }
    return endpoint;
 }
ast_sip_for_each_channel()
int ast_sip_for_each_channel (const struct ast_sip_endpoint * endpoint, ao2_callback_fn on_channel_snapshot, void * arg)
For every channel snapshot on an endpoint all the given 'on_channel_snapshot' handler.
Parameters
endpoint endpoint
on_channel_snapshot callback for each channel snapshot
arg user data passed to handler
Return values
0 Success, non-zero on failure
Definition at line 1550 of file pjsip_configuration.c.
References ao2_cleanup, ast_sip_for_each_channel_snapshot(), ast_sip_get_endpoint_snapshot(), and RAII_VAR.
Referenced by cli_channel_iterate(), and cli_channelstats_iterate().
 {
    RAII_VAR(struct ast_endpoint_snapshot *, endpoint_snapshot, ast_sip_get_endpoint_snapshot(endpoint), ao2_cleanup);
    return ast_sip_for_each_channel_snapshot(endpoint_snapshot, on_channel_snapshot, arg);
 }
ast_sip_for_each_channel_snapshot()
int ast_sip_for_each_channel_snapshot (const struct ast_endpoint_snapshot * endpoint_snapshot, ao2_callback_fn on_channel_snapshot, void * arg)
For every channel snapshot on an endpoint snapshot call the given 'on_channel_snapshot' handler.
Parameters
endpoint_snapshot snapshot of an endpoint
on_channel_snapshot callback for each channel snapshot
arg user data passed to handler
Return values
0 Success, non-zero on failure
Definition at line 1523 of file pjsip_configuration.c.
References ao2_cleanup, ast_channel_snapshot_get_latest(), ast_endpoint_snapshot::channel_ids, NULL, ast_endpoint_snapshot::num_channels, and RAII_VAR.
Referenced by active_channels_to_str(), and ast_sip_for_each_channel().
 {
    int num, num_channels = endpoint_snapshot->num_channels;
    if (!on_channel_snapshot || !num_channels) {
       return 0;
    }
    for (num = 0; num < num_channels; ++num) {
       RAII_VAR(struct ast_channel_snapshot *, snapshot, NULL, ao2_cleanup);
       int res;
       snapshot = ast_channel_snapshot_get_latest(endpoint_snapshot->channel_ids[num]);
       if (!snapshot) {
          continue;
       }
       res = on_channel_snapshot(snapshot, arg, 0);
       if (res) {
          return -1;
       }
    }
    return 0;
 }
ast_sip_get_device_state()
const char* ast_sip_get_device_state (const struct ast_sip_endpoint * endpoint)
Retrieve the device state for an endpoint.
Parameters
endpoint The endpoint whose state is to be retrieved.
Return values
The device state.
Definition at line 1507 of file pjsip_configuration.c.
References ast_devstate2str(), ast_sorcery_object_get_id(), and MAX_OBJECT_FIELD.
Referenced by cli_endpoint_print_body(), format_ami_endpoints(), and sip_endpoint_to_ami().
 {
    char device[MAX_OBJECT_FIELD];
    snprintf(device, MAX_OBJECT_FIELD, "PJSIP/%s", ast_sorcery_object_get_id(endpoint));
    return ast_devstate2str(ast_device_state(device));
 }
ast_sip_get_endpoint_snapshot()
struct ast_endpoint_snapshot* ast_sip_get_endpoint_snapshot (const struct ast_sip_endpoint * endpoint)
Retrieve the endpoint snapshot for an endpoint.
Parameters
endpoint The endpoint whose snapshot is to be retreieved.
Return values
The endpoint snapshot
Definition at line 1515 of file pjsip_configuration.c.
References ast_endpoint_get_resource(), ast_endpoint_get_tech(), ast_endpoint_latest_snapshot(), and ast_sip_endpoint::persistent.
Referenced by active_channels_to_str(), ast_sip_for_each_channel(), and cli_endpoint_print_body().
 {
    return ast_endpoint_latest_snapshot(
       ast_endpoint_get_tech(endpoint->persistent),
       ast_endpoint_get_resource(endpoint->persistent));
 }
ast_sip_get_endpoints()
struct ao2_container* ast_sip_get_endpoints (void)
Retrieve any endpoints available to sorcery.
Return values
Endpoints available to sorcery, NULL if no endpoints found.
Definition at line 2344 of file pjsip_configuration.c.
References AST_RETRIEVE_FLAG_ALL, AST_RETRIEVE_FLAG_MULTIPLE, ast_sorcery_retrieve_by_fields(), endpoints, and NULL.
Referenced by ami_registrations_endpoints(), ami_show_endpoints(), and load_module().
 {
    struct ao2_container *endpoints;
    endpoints = ast_sorcery_retrieve_by_fields(sip_sorcery, "endpoint", AST_RETRIEVE_FLAG_MULTIPLE | AST_RETRIEVE_FLAG_ALL, NULL);
    return endpoints;
 }
ast_sip_get_sorcery()
struct ast_sorcery* ast_sip_get_sorcery (void)
Get a pointer to the SIP sorcery structure.
Return values
NULL sorcery has not been initialized
non-NULL sorcery structure
Definition at line 2404 of file pjsip_configuration.c.
References sip_sorcery.
Referenced by acl_change_stasis_cb(), acl_on_rx_msg(), alloc_artificial_auth(), ami_show_endpoint(), ami_show_registration_contact_statuses(), ami_show_resource_lists(), ami_sip_qualify(), anonymous_identify(), aor_deleted_observer(), ast_res_pjsip_cleanup_options_handling(), ast_sip_cli_print_sorcery_objectset(), ast_sip_destroy_distributor(), ast_sip_destroy_sorcery_global(), ast_sip_destroy_sorcery_location(), ast_sip_destroy_transport_management(), ast_sip_for_each_auth(), ast_sip_initialize_distributor(), ast_sip_initialize_sorcery_auth(), ast_sip_initialize_sorcery_domain_alias(), ast_sip_initialize_sorcery_global(), ast_sip_initialize_sorcery_location(), ast_sip_initialize_sorcery_transport(), ast_sip_initialize_transport_management(), ast_sip_location_create_contact(), ast_sip_location_delete_contact(), ast_sip_location_prune_boot_contacts(), ast_sip_location_retrieve_aor(), ast_sip_location_retrieve_aor_contacts_nolock_filtered(), ast_sip_location_retrieve_contact(), ast_sip_location_update_contact(), ast_sip_retrieve_auths(), ast_sip_retrieve_auths_vector(), ast_sip_set_tpselector_from_transport_name(), ast_sip_sorcery_object_to_ami(), asterisk_publication_devicestate_state_change(), asterisk_publication_mwi_state_change(), asterisk_publication_new(), asterisk_publication_send_refresh(), auth_observer(), can_reuse_registration(), chan_pjsip_devicestate(), check_expiration_thread(), check_state(), cleanup_resource_list(), cli_aor_get_container(), cli_aor_retrieve_by_id(), cli_complete_endpoint(), cli_complete_registration(), cli_contact_get_container(), cli_endpoint_retrieve_by_id(), cli_get_aors(), cli_get_auths(), cli_get_container(), cli_iterate(), cli_iterator(), cli_qualify(), cli_reload_qualify_aor(), cli_reload_qualify_endpoint(), cli_retrieve_by_id(), cli_show_qualify_endpoint(), common_identify(), contact_observer_updated(), create_artificial_endpoint(), create_mwi_subscriptions(), create_resource_list(), create_rtp(), find_aor(), find_aor_name(), find_endpoint(), format_ami_endpoint_identify(), format_ami_endpoint_transport(), get_all_contacts(), get_publishes_and_update_state(), get_registrations(), get_write_timeout(), handle_atsign(), handle_export_primitives(), handle_single_token(), handle_slash(), line_identify(), load_module(), mwi_contact_changed(), mwi_contact_deleted(), mwi_subscription_shutdown(), on_rx_process_symmetric_transport(), permanent_uri_handler(), pjsip_acf_dial_contacts_read(), pjsip_aor_function_read(), pjsip_contact_function_read(), pjsip_endpoint_function_read(), pjsip_outbound_registration_metrics_init(), pjsip_outbound_registration_metrics_unload_cb(), process_nat(), publish_request_initial(), push_notify(), register_aor_core(), registration_deleted_observer(), registration_loaded_observer(), reload_module(), request(), reregister_all(), retrieve_resource_list(), send_unsolicited_mwi_notify(), sip_aor_to_ami(), sip_cli_print_global(), sip_options_aor_observer_modified_task(), sip_options_apply_aor_configuration(), sip_options_contact_add_management_task(), sip_options_init_task(), sip_options_qualify_contact(), sip_options_synchronize_task(), sub_persistence_recreate(), subscription_persistence_create(), subscription_persistence_load(), subscription_persistence_recreate(), subscription_persistence_remove(), subscription_persistence_update(), transfer(), and unload_module().
 {
    return sip_sorcery;
 }
ast_sip_persistent_endpoint_add_to_regcontext()
int ast_sip_persistent_endpoint_add_to_regcontext (const char * regcontext)
Definition at line 1312 of file pjsip_configuration.c.
References add_to_regcontext(), ao2_callback, ast_context_find_or_create(), ast_log, ast_strlen_zero, LOG_ERROR, NULL, and OBJ_NODATA.
Referenced by check_regcontext().
 {
    if (ast_strlen_zero(regcontext)) {
       return 0;
    }
    /* Make sure the regcontext exists */
    if (!ast_context_find_or_create(NULL, NULL, regcontext, "PJSIP")) {
       ast_log(LOG_ERROR, "Failed to create regcontext '%s'\n", regcontext);
       return -1;
    }
    /* Add any online endpoints */
    ao2_callback(persistent_endpoints, OBJ_NODATA, add_to_regcontext, (void *)regcontext);
    return 0;
 }
ast_sip_persistent_endpoint_publish_contact_state()
void ast_sip_persistent_endpoint_publish_contact_state (const char * endpoint_name, const struct ast_sip_contact_status * contact_status)
Publish the change of state for a contact.
Parameters
endpoint_name The SIP endpoint name.
contact_status The contact status.
Definition at line 1386 of file pjsip_configuration.c.
References ao2_find, ao2_ref, ast_sip_contact_status::aor, ast_endpoint_blob_publish(), ast_endpoint_contact_state_type(), ast_endpoint_get_resource(), ast_json_pack(), ast_json_unref(), ast_sip_get_contact_status_label(), sip_persistent_endpoint::endpoint, OBJ_SEARCH_KEY, ast_sip_contact_status::rtt, ast_sip_contact_status::status, and ast_sip_contact_status::uri.
Referenced by sip_options_publish_contact_state().
 {
    struct sip_persistent_endpoint *persistent;
    struct ast_json *blob;
    char rtt[32];
    persistent = ao2_find(persistent_endpoints, endpoint_name, OBJ_SEARCH_KEY);
    if (!persistent) {
       return;
    }
    snprintf(rtt, sizeof(rtt), "%" PRId64, contact_status->rtt);
    blob = ast_json_pack("{s: s, s: s, s: s, s: s, s: s}",
       "contact_status", ast_sip_get_contact_status_label(contact_status->status),
       "aor", contact_status->aor,
       "uri", contact_status->uri,
       "roundtrip_usec", rtt,
       "endpoint_name", ast_endpoint_get_resource(persistent->endpoint));
    if (blob) {
       ast_endpoint_blob_publish(persistent->endpoint, ast_endpoint_contact_state_type(), blob);
       ast_json_unref(blob);
    }
    ao2_ref(persistent, -1);
 }
ast_sip_persistent_endpoint_update_state()
int ast_sip_persistent_endpoint_update_state (const char * endpoint_name, enum ast_endpoint_state state)
Change state of a persistent endpoint.
Parameters
endpoint_name The SIP endpoint name to change state.
state The new state
Return values
0 Success
-1 Endpoint not found
Definition at line 1329 of file pjsip_configuration.c.
References ao2_find, ao2_ref, ast_add_extension(), ast_context_remove_extension(), AST_DEVICE_UNKNOWN, AST_DEVSTATE_CACHABLE, ast_devstate_changed(), ast_endpoint_blob_publish(), ast_endpoint_get_resource(), ast_endpoint_get_state(), AST_ENDPOINT_OFFLINE, AST_ENDPOINT_ONLINE, ast_endpoint_set_state(), ast_endpoint_state_type(), ast_exists_extension(), ast_free, ast_free_ptr(), ast_json_pack(), ast_json_unref(), ast_sip_get_regcontext(), ast_strdup, ast_strlen_zero, ast_verb, E_MATCH, sip_persistent_endpoint::endpoint, NULL, OBJ_SEARCH_KEY, pbx_find_extension(), regcontext, and pbx_find_info::stacklen.
Referenced by sip_options_synchronize_endpoint(), sip_options_unused_endpoint_state_compositor(), and sip_options_update_endpoint_state_compositor_aor().
 {
    struct sip_persistent_endpoint *persistent;
    struct ast_json *blob;
    char *regcontext;
    persistent = ao2_find(persistent_endpoints, endpoint_name, OBJ_SEARCH_KEY);
    if (!persistent) {
       return -1;
    }
    /* If there was no state change, don't publish anything. */
    if (ast_endpoint_get_state(persistent->endpoint) == state) {
       ao2_ref(persistent, -1);
       return 0;
    }
    regcontext = ast_sip_get_regcontext();
    if (state == AST_ENDPOINT_ONLINE) {
       ast_endpoint_set_state(persistent->endpoint, AST_ENDPOINT_ONLINE);
       blob = ast_json_pack("{s: s}", "peer_status", "Reachable");
       if (!ast_strlen_zero(regcontext)) {
          if (!ast_exists_extension(NULL, regcontext, ast_endpoint_get_resource(persistent->endpoint), 1, NULL)) {
             ast_add_extension(regcontext, 1, ast_endpoint_get_resource(persistent->endpoint), 1, NULL, NULL,
                "Noop", ast_strdup(ast_endpoint_get_resource(persistent->endpoint)), ast_free_ptr, "PJSIP");
          }
       }
       ast_verb(2, "Endpoint %s is now Reachable\n", ast_endpoint_get_resource(persistent->endpoint));
    } else {
       ast_endpoint_set_state(persistent->endpoint, AST_ENDPOINT_OFFLINE);
       blob = ast_json_pack("{s: s}", "peer_status", "Unreachable");
       if (!ast_strlen_zero(regcontext)) {
          struct pbx_find_info q = { .stacklen = 0 };
          if (pbx_find_extension(NULL, NULL, &q, regcontext, ast_endpoint_get_resource(persistent->endpoint), 1, NULL, "", E_MATCH)) {
             ast_context_remove_extension(regcontext, ast_endpoint_get_resource(persistent->endpoint), 1, NULL);
          }
       }
       ast_verb(2, "Endpoint %s is now Unreachable\n", ast_endpoint_get_resource(persistent->endpoint));
    }
    ast_free(regcontext);
    ast_endpoint_blob_publish(persistent->endpoint, ast_endpoint_state_type(), blob);
    ast_json_unref(blob);
    ast_devstate_changed(AST_DEVICE_UNKNOWN, AST_DEVSTATE_CACHABLE, "PJSIP/%s", ast_endpoint_get_resource(persistent->endpoint));
    ao2_ref(persistent, -1);
    return 0;
 }
ast_sip_retrieve_auths()
int ast_sip_retrieve_auths (const struct ast_sip_auth_vector * auths, struct ast_sip_auth ** out)
Retrieve relevant SIP auth structures from sorcery.
Parameters
auths Vector of sorcery IDs of auth credentials to retrieve
[out] out The retrieved auths are stored here
Definition at line 2360 of file pjsip_configuration.c.
References ast_log, ast_sip_get_sorcery(), ast_sorcery_retrieve_by_id(), AST_VECTOR_GET, AST_VECTOR_SIZE, LOG_NOTICE, and name.
Referenced by digest_check_auth(), and set_outbound_initial_authentication_credentials().
 {
    int i;
    for (i = 0; i < AST_VECTOR_SIZE(auths); ++i) {
       /* Using AST_VECTOR_GET is safe since the vector is immutable */
       const char *name = AST_VECTOR_GET(auths, i);
       out[i] = ast_sorcery_retrieve_by_id(ast_sip_get_sorcery(), SIP_SORCERY_AUTH_TYPE, name);
       if (!out[i]) {
          ast_log(LOG_NOTICE, "Couldn't find auth '%s'. Cannot authenticate\n", name);
          return -1;
       }
    }
    return 0;
 }
ast_sip_retrieve_auths_vector()
int ast_sip_retrieve_auths_vector (const struct ast_sip_auth_vector * auth_ids, struct ast_sip_auth_objects_vector * auth_objects)
Definition at line 2385 of file pjsip_configuration.c.
References ast_log, ast_sip_get_sorcery(), ast_sorcery_retrieve_by_id(), AST_VECTOR_APPEND, AST_VECTOR_GET, AST_VECTOR_SIZE, LOG_WARNING, and name.
Referenced by digest_create_request_with_auth().
 {
    int i;
    for (i = 0; i < AST_VECTOR_SIZE(auth_ids); ++i) {
       /* Using AST_VECTOR_GET is safe since the vector is immutable */
       const char *name = AST_VECTOR_GET(auth_ids, i);
       struct ast_sip_auth *auth_object = ast_sorcery_retrieve_by_id(ast_sip_get_sorcery(), SIP_SORCERY_AUTH_TYPE, name);
       if (!auth_object) {
          ast_log(LOG_WARNING, "Auth object '%s' could not be found\n", name);
       } else {
          AST_VECTOR_APPEND(auth_objects, auth_object);
       }
    }
    return AST_VECTOR_SIZE(auth_objects) == AST_VECTOR_SIZE(auth_ids) ? 0 : -1;
 }
ast_sip_sorcery_object_to_ami()
int ast_sip_sorcery_object_to_ami (const void * obj, struct ast_str ** buf)
Converts a sorcery object to a string of object properties.
Parameters
obj the sorcery object to convert
str the string buffer to write the object data
Return values
0 Success, non-zero on failure
Definition at line 1609 of file pjsip_configuration.c.
References ast_free, AST_HANDLER_ONLY_STRING, ast_sip_get_sorcery(), ast_sorcery_objectset_create2(), ast_str_append(), ast_to_camel_case, ast_variables_destroy(), ast_variable::name, ast_variable::next, RAII_VAR, sip_sorcery_object_ami_set_type_name(), and ast_variable::value.
Referenced by ami_outbound_registration_task(), ami_registrations_aor(), format_ami_resource_lists(), sip_auth_to_ami(), sip_contact_to_ami(), sip_endpoint_to_ami(), sip_identify_to_ami(), and sip_transport_to_ami().
 {
    RAII_VAR(struct ast_variable *, objset, ast_sorcery_objectset_create2(
           ast_sip_get_sorcery(), obj, AST_HANDLER_ONLY_STRING), ast_variables_destroy);
    struct ast_variable *i;
    if (!objset) {
       return -1;
    }
    sip_sorcery_object_ami_set_type_name(obj, buf);
    for (i = objset; i; i = i->next) {
       RAII_VAR(char *, camel, ast_to_camel_case(i->name), ast_free);
       ast_str_append(buf, 0, "%s: %s\r\n", camel, i->value);
    }
    return 0;
 }
call_offer_pref_handler()
static int call_offer_pref_handler (const struct aco_option * opt, struct ast_variable * var, void * obj) static
Definition at line 1124 of file pjsip_configuration.c.
References ast_sip_call_codec_str_to_pref(), sip_persistent_endpoint::endpoint, ast_sip_endpoint_media_configuration::incoming_call_offer_pref, ast_sip_endpoint::media, ast_variable::name, ast_sip_endpoint_media_configuration::outgoing_call_offer_pref, and ast_variable::value.
Referenced by ast_res_pjsip_initialize_configuration().
 {
    struct ast_sip_endpoint *endpoint = obj;
    struct ast_flags pref = { 0, };
    int outgoing = strcmp(var->name, "outgoing_call_offer_pref") == 0;
    int res = ast_sip_call_codec_str_to_pref(&pref, var->value, outgoing);
    if (res != 0) {
       return -1;
    }
    if (outgoing) {
       endpoint->media.outgoing_call_offer_pref = pref;
    } else {
       endpoint->media.incoming_call_offer_pref = pref;
    }
    return 0;
 }
caller_id_handler()
static int caller_id_handler (const struct aco_option * opt, struct ast_variable * var, void * obj) static
Definition at line 592 of file pjsip_configuration.c.
References ast_callerid_split(), ast_free, ast_strdup, ast_strlen_zero, cid_name, cid_num, sip_persistent_endpoint::endpoint, ast_sip_endpoint::id, ast_party_id::name, NULL, ast_party_id::number, ast_sip_endpoint_id_configuration::self, ast_party_name::str, ast_party_number::str, ast_party_name::valid, ast_party_number::valid, and ast_variable::value.
Referenced by ast_res_pjsip_initialize_configuration().
 {
    struct ast_sip_endpoint *endpoint = obj;
    char cid_name[80] = { '\0' };
    char cid_num[80] = { '\0' };
    ast_free(endpoint->id.self.name.str);
    endpoint->id.self.name.str = NULL;
    endpoint->id.self.name.valid = 0;
    ast_free(endpoint->id.self.number.str);
    endpoint->id.self.number.str = NULL;
    endpoint->id.self.number.valid = 0;
    ast_callerid_split(var->value, cid_name, sizeof(cid_name), cid_num, sizeof(cid_num));
    if (!ast_strlen_zero(cid_name)) {
       endpoint->id.self.name.str = ast_strdup(cid_name);
       if (!endpoint->id.self.name.str) {
          return -1;
       }
       endpoint->id.self.name.valid = 1;
    }
    if (!ast_strlen_zero(cid_num)) {
       endpoint->id.self.number.str = ast_strdup(cid_num);
       if (!endpoint->id.self.number.str) {
          return -1;
       }
       endpoint->id.self.number.valid = 1;
    }
    return 0;
 }
caller_id_privacy_handler()
static int caller_id_privacy_handler (const struct aco_option * opt, struct ast_variable * var, void * obj) static
Definition at line 646 of file pjsip_configuration.c.
References ast_parse_caller_presentation(), sip_persistent_endpoint::endpoint, ast_sip_endpoint::id, ast_party_id::name, ast_party_id::number, ast_party_name::presentation, ast_party_number::presentation, ast_sip_endpoint_id_configuration::self, and ast_variable::value.
Referenced by ast_res_pjsip_initialize_configuration().
 {
    struct ast_sip_endpoint *endpoint = obj;
    int callingpres = ast_parse_caller_presentation(var->value);
    if (callingpres == -1 && sscanf(var->value, "%d", &callingpres) != 1) {
       return -1;
    }
    endpoint->id.self.number.presentation = callingpres;
    endpoint->id.self.name.presentation = callingpres;
    return 0;
 }
caller_id_privacy_to_str()
static int caller_id_privacy_to_str (const void * obj, const intptr_t * args, char ** buf) static
Definition at line 658 of file pjsip_configuration.c.
References ast_named_caller_presentation(), ast_strdup, sip_persistent_endpoint::endpoint, ast_sip_endpoint::id, ast_party_id::name, ast_party_name::presentation, and ast_sip_endpoint_id_configuration::self.
Referenced by ast_res_pjsip_initialize_configuration().
 {
    const struct ast_sip_endpoint *endpoint = obj;
    const char *presentation = ast_named_caller_presentation(
       endpoint->id.self.name.presentation);
    *buf = ast_strdup(presentation);
    return 0;
 }
caller_id_tag_handler()
static int caller_id_tag_handler (const struct aco_option * opt, struct ast_variable * var, void * obj) static
Definition at line 668 of file pjsip_configuration.c.
References ast_free, ast_strdup, sip_persistent_endpoint::endpoint, ast_sip_endpoint::id, ast_sip_endpoint_id_configuration::self, ast_party_id::tag, and ast_variable::value.
Referenced by ast_res_pjsip_initialize_configuration().
 {
    struct ast_sip_endpoint *endpoint = obj;
    ast_free(endpoint->id.self.tag);
    endpoint->id.self.tag = ast_strdup(var->value);
    return endpoint->id.self.tag ? 0 : -1;
 }
caller_id_tag_to_str()
static int caller_id_tag_to_str (const void * obj, const intptr_t * args, char ** buf) static
Definition at line 678 of file pjsip_configuration.c.
References ast_strdup, sip_persistent_endpoint::endpoint, ast_sip_endpoint::id, ast_sip_endpoint_id_configuration::self, and ast_party_id::tag.
Referenced by ast_res_pjsip_initialize_configuration().
 {
    const struct ast_sip_endpoint *endpoint = obj;
    *buf = ast_strdup(endpoint->id.self.tag);
    return 0;
 }
caller_id_to_str()
static int caller_id_to_str (const void * obj, const intptr_t * args, char ** buf) static
Definition at line 623 of file pjsip_configuration.c.
References ast_callerid_merge(), ast_calloc, sip_persistent_endpoint::endpoint, ast_sip_endpoint::id, name, ast_party_id::name, NULL, ast_party_id::number, S_COR, ast_sip_endpoint_id_configuration::self, ast_party_name::str, ast_party_number::str, ast_party_name::valid, and ast_party_number::valid.
Referenced by ast_res_pjsip_initialize_configuration().
 {
    const struct ast_sip_endpoint *endpoint = obj;
    const char *name = S_COR(endpoint->id.self.name.valid,
              endpoint->id.self.name.str, NULL);
    const char *number = S_COR(endpoint->id.self.number.valid,
                endpoint->id.self.number.str, NULL);
    /* make sure size is at least 10 - that should cover the "<unknown>"
       case as well as any additional formatting characters added in
       the name and/or number case. */
    int size = 10;
    size += name ? strlen(name) : 0;
    size += number ? strlen(number) : 0;
    if (!(*buf = ast_calloc(size + 1, sizeof(char)))) {
       return -1;
    }
    ast_callerid_merge(*buf, size + 1, name, number, NULL);
    return 0;
 }
callgroup_to_str()
static int callgroup_to_str (const void * obj, const intptr_t * args, char ** buf) static
Definition at line 736 of file pjsip_configuration.c.
References ast_calloc, ast_print_group(), ast_sip_endpoint_pickup_configuration::callgroup, sip_persistent_endpoint::endpoint, MAX_OBJECT_FIELD, and ast_sip_endpoint::pickup.
Referenced by ast_res_pjsip_initialize_configuration().
 {
    const struct ast_sip_endpoint *endpoint = obj;
    if (!(*buf = ast_calloc(MAX_OBJECT_FIELD, sizeof(char)))) {
       return -1;
    }
    ast_print_group(*buf, MAX_OBJECT_FIELD, endpoint->pickup.callgroup);
    return 0;
 }
cli_endpoint_get_container()
static struct ao2_container* cli_endpoint_get_container (const char * regex) static
Definition at line 1796 of file pjsip_configuration.c.
References AO2_ALLOC_OPT_LOCK_NOLOCK, ao2_cleanup, ao2_container_alloc_list, ao2_container_dup(), ao2_ref, ast_sorcery_object_id_compare(), ast_sorcery_object_id_sort(), ast_sorcery_retrieve_by_regex(), container, NULL, and RAII_VAR.
Referenced by ast_res_pjsip_initialize_configuration().
 {
    RAII_VAR(struct ao2_container *, container, NULL, ao2_cleanup);
    struct ao2_container *s_container;
    container = ast_sorcery_retrieve_by_regex(sip_sorcery, "endpoint", regex);
    if (!container) {
       return NULL;
    }
    s_container = ao2_container_alloc_list(AO2_ALLOC_OPT_LOCK_NOLOCK, 0,
       (void *)ast_sorcery_object_id_sort, (void *)ast_sorcery_object_id_compare);
    if (!s_container) {
       return NULL;
    }
    if (ao2_container_dup(s_container, container, 0)) {
       ao2_ref(s_container, -1);
       return NULL;
    }
    return s_container;
 }
cli_endpoint_iterate()
static int cli_endpoint_iterate (void * obj, ao2_callback_fn callback, void * args) static
Definition at line 1820 of file pjsip_configuration.c.
References ao2_callback, and OBJ_NODATA.
Referenced by ast_res_pjsip_initialize_configuration().
 {
    ao2_callback(obj, OBJ_NODATA, callback, args);
    return 0;
 }
cli_endpoint_print_body()
static int cli_endpoint_print_body (void * obj, void * arg, int flags) static
Definition at line 1874 of file pjsip_configuration.c.
References ao2_cleanup, ast_sip_endpoint::aors, ast_alloca, ast_assert, ast_sip_cli_print_sorcery_objectset(), ast_sip_get_device_state(), ast_sip_get_endpoint_snapshot(), ast_sorcery_object_get_id(), ast_str_append(), ast_sip_cli_context::auth_direction, cli_endpoint_print_child_body(), CLI_INDENT_TO_SPACES, CLI_LAST_TABSTOP, context, ast_sip_endpoint::devicestate_busy_at, sip_persistent_endpoint::endpoint, ast_sip_endpoint::id, ast_sip_endpoint::inbound_auths, ast_sip_cli_context::indent_level, INFINITY, NULL, ast_party_id::number, ast_sip_endpoint::outbound_auths, ast_sip_cli_context::output_buffer, RAII_VAR, ast_sip_cli_context::recurse, S_COR, ast_sip_endpoint_id_configuration::self, ast_sip_cli_context::show_details, ast_sip_cli_context::show_details_only_level_0, ast_party_number::str, and ast_party_number::valid.
Referenced by ast_res_pjsip_initialize_configuration().
 {
    struct ast_sip_endpoint *endpoint = obj;
    RAII_VAR(struct ast_endpoint_snapshot *, endpoint_snapshot, ast_sip_get_endpoint_snapshot(endpoint), ao2_cleanup);
    struct ast_sip_cli_context *context = arg;
    const char *id = ast_sorcery_object_get_id(endpoint);
    char *print_name = NULL;
    int print_name_len;
    char *number = S_COR(endpoint->id.self.number.valid,
       endpoint->id.self.number.str, NULL);
    int indent;
    int flexwidth;
    ast_assert(context->output_buffer != NULL);
    if (number) {
       print_name_len = strlen(id) + strlen(number) + 2;
       print_name = ast_alloca(print_name_len);
       snprintf(print_name, print_name_len, "%s/%s", id, number);
    }
    indent = CLI_INDENT_TO_SPACES(context->indent_level);
    flexwidth = CLI_LAST_TABSTOP - indent - 2;
    ast_str_append(&context->output_buffer, 0, "%*s:  %-*.*s  %-12.12s  %d of %.0f\n",
       indent, "Endpoint",
       flexwidth, flexwidth, print_name ? print_name : id,
       ast_sip_get_device_state(endpoint),
       endpoint_snapshot->num_channels,
       (double) endpoint->devicestate_busy_at ? endpoint->devicestate_busy_at :
                                           INFINITY
                                           );
    if (context->recurse) {
       context->indent_level++;
       context->auth_direction = "Out";
       cli_endpoint_print_child_body("auth", &endpoint->outbound_auths, context);
       context->auth_direction = "In";
       cli_endpoint_print_child_body("auth", &endpoint->inbound_auths, context);
       cli_endpoint_print_child_body("aor", endpoint->aors, context);
       cli_endpoint_print_child_body("transport", endpoint, context);
       cli_endpoint_print_child_body("identify", endpoint, context);
       cli_endpoint_print_child_body("channel", endpoint, context);
       context->indent_level--;
       if (context->indent_level == 0) {
          ast_str_append(&context->output_buffer, 0, "\n");
       }
    }
    if (context->show_details || (context->show_details_only_level_0 && context->indent_level == 0)) {
       ast_str_append(&context->output_buffer, 0, "\n");
       ast_sip_cli_print_sorcery_objectset(endpoint, context, 0);
    }
    return 0;
 }
cli_endpoint_print_child_body()
static void cli_endpoint_print_child_body (char * type, const void * obj, struct ast_sip_cli_context * context) static
Definition at line 1864 of file pjsip_configuration.c.
References ao2_cleanup, ast_sip_lookup_cli_formatter(), NULL, and RAII_VAR.
Referenced by cli_endpoint_print_body().
 {
    RAII_VAR(struct ast_sip_cli_formatter_entry *, formatter_entry, NULL, ao2_cleanup);
    formatter_entry = ast_sip_lookup_cli_formatter(type);
    if (formatter_entry) {
       formatter_entry->iterate((void *)obj, formatter_entry->print_body, context);
    }
 }
cli_endpoint_print_child_header()
static void cli_endpoint_print_child_header (char * type, struct ast_sip_cli_context * context) static
Definition at line 1832 of file pjsip_configuration.c.
References ao2_cleanup, ast_sip_lookup_cli_formatter(), NULL, and RAII_VAR.
Referenced by cli_endpoint_print_header().
 {
    RAII_VAR(struct ast_sip_cli_formatter_entry *, formatter_entry, NULL, ao2_cleanup);
    formatter_entry = ast_sip_lookup_cli_formatter(type);
    if (formatter_entry) {
       formatter_entry->print_header(NULL, context, 0);
    }
 }
cli_endpoint_print_header()
static int cli_endpoint_print_header (void * obj, void * arg, int flags) static
Definition at line 1842 of file pjsip_configuration.c.
References ast_assert, ast_str_append(), cli_endpoint_print_child_header(), context, ast_sip_cli_context::indent_level, NULL, ast_sip_cli_context::output_buffer, and ast_sip_cli_context::recurse.
Referenced by ast_res_pjsip_initialize_configuration().
 {
    struct ast_sip_cli_context *context = arg;
    ast_assert(context->output_buffer != NULL);
    ast_str_append(&context->output_buffer, 0,
          " Endpoint:  <Endpoint/CID.....................................>  <State.....>  <Channels.>\n");
    if (context->recurse) {
       context->indent_level++;
       cli_endpoint_print_child_header("auth", context);
       cli_endpoint_print_child_header("aor", context);
       cli_endpoint_print_child_header("transport", context);
       cli_endpoint_print_child_header("identify", context);
       cli_endpoint_print_child_header("channel", context);
       context->indent_level--;
    }
    return 0;
 }
cli_endpoint_retrieve_by_id()
static void* cli_endpoint_retrieve_by_id (const char * id) static
Definition at line 1827 of file pjsip_configuration.c.
References ast_sip_get_sorcery(), and ast_sorcery_retrieve_by_id().
Referenced by ast_res_pjsip_initialize_configuration().
 {
    return ast_sorcery_retrieve_by_id(ast_sip_get_sorcery(), "endpoint", id);
 }
codec_prefs_handler()
static int codec_prefs_handler (const struct aco_option * opt, struct ast_variable * var, void * obj) static
Definition at line 1169 of file pjsip_configuration.c.
References ast_free, ast_log, ast_sorcery_object_get_id(), ast_str_buffer(), ast_str_create, ast_stream_codec_operation_to_str, ast_stream_codec_param_to_str, ast_stream_codec_prefs_parse(), CODEC_NEGOTIATION_KEEP_ALL, CODEC_NEGOTIATION_KEEP_UNSPECIFIED, CODEC_NEGOTIATION_OPERATION_INTERSECT, CODEC_NEGOTIATION_OPERATION_UNION, CODEC_NEGOTIATION_OPERATION_UNSPECIFIED, CODEC_NEGOTIATION_PARAM_OPERATION, CODEC_NEGOTIATION_PREFER_PENDING, CODEC_NEGOTIATION_PREFER_UNSPECIFIED, CODEC_NEGOTIATION_TRANSCODE_ALLOW, CODEC_NEGOTIATION_TRANSCODE_UNSPECIFIED, ast_sip_endpoint_media_configuration::codec_prefs_incoming_answer, ast_sip_endpoint_media_configuration::codec_prefs_incoming_offer, ast_sip_endpoint_media_configuration::codec_prefs_outgoing_answer, ast_sip_endpoint_media_configuration::codec_prefs_outgoing_offer, sip_persistent_endpoint::endpoint, ast_stream_codec_negotiation_prefs::keep, LOG_ERROR, ast_sip_endpoint::media, ast_variable::name, ast_stream_codec_negotiation_prefs::operation, ast_stream_codec_negotiation_prefs::prefer, ast_stream_codec_negotiation_prefs::transcode, and ast_variable::value.
Referenced by ast_res_pjsip_initialize_configuration().
 {
    struct ast_sip_endpoint *endpoint = obj;
    struct ast_stream_codec_negotiation_prefs *option_prefs;
    struct ast_stream_codec_negotiation_prefs prefs;
    struct ast_str *error_message = ast_str_create(128);
    enum ast_stream_codec_negotiation_prefs_prefer_values default_prefer;
    enum ast_stream_codec_negotiation_prefs_operation_values default_operation;
    int res = 0;
    res = ast_stream_codec_prefs_parse(var->value, &prefs, &error_message);
    if (res < 0) {
       ast_log(LOG_ERROR, "Endpoint '%s': %s for option '%s'\n",
          ast_sorcery_object_get_id(endpoint), ast_str_buffer(error_message), var->name);
       ast_free(error_message);
       return -1;
    }
    ast_free(error_message);
    if (strcmp(var->name, "codec_prefs_incoming_offer") == 0) {
       if (prefs.operation == CODEC_NEGOTIATION_OPERATION_UNION) {
          ast_log(LOG_ERROR, "Endpoint '%s': Codec preference '%s' has invalid value '%s' for option: '%s'",
             ast_sorcery_object_get_id(endpoint),
             ast_stream_codec_param_to_str(CODEC_NEGOTIATION_PARAM_OPERATION),
             ast_stream_codec_operation_to_str(CODEC_NEGOTIATION_OPERATION_UNION),
             var->name);
          return -1;
       }
       option_prefs = &endpoint->media.codec_prefs_incoming_offer;
       default_prefer = CODEC_NEGOTIATION_PREFER_PENDING;
       default_operation = CODEC_NEGOTIATION_OPERATION_INTERSECT;
    } else if (strcmp(var->name, "codec_prefs_outgoing_offer") == 0) {
       option_prefs = &endpoint->media.codec_prefs_outgoing_offer;
       default_prefer = CODEC_NEGOTIATION_PREFER_PENDING;
       default_operation = CODEC_NEGOTIATION_OPERATION_UNION;
    } else if (strcmp(var->name, "codec_prefs_incoming_answer") == 0) {
       option_prefs = &endpoint->media.codec_prefs_incoming_answer;
       default_prefer = CODEC_NEGOTIATION_PREFER_PENDING;
       default_operation = CODEC_NEGOTIATION_OPERATION_INTERSECT;
    } else if (strcmp(var->name, "codec_prefs_outgoing_answer") == 0) {
       option_prefs = &endpoint->media.codec_prefs_outgoing_answer;
       default_prefer = CODEC_NEGOTIATION_PREFER_PENDING;
       default_operation = CODEC_NEGOTIATION_OPERATION_INTERSECT;
    } else {
       ast_log(LOG_ERROR, "Endpoint '%s': Unsupported option '%s'\n",
          ast_sorcery_object_get_id(endpoint),
          var->name);
       return -1;
    }
    if (prefs.prefer == CODEC_NEGOTIATION_PREFER_UNSPECIFIED) {
       prefs.prefer = default_prefer;
    }
    if (prefs.operation == CODEC_NEGOTIATION_OPERATION_UNSPECIFIED) {
       prefs.operation = default_operation;
    }
    if (prefs.keep == CODEC_NEGOTIATION_KEEP_UNSPECIFIED) {
       prefs.keep = CODEC_NEGOTIATION_KEEP_ALL;
    }
    if (prefs.transcode == CODEC_NEGOTIATION_TRANSCODE_UNSPECIFIED) {
       prefs.transcode = CODEC_NEGOTIATION_TRANSCODE_ALLOW;
    }
    /* Now that defaults have been applied as needed we apply the full codec
     * preference configuration to the option.
     */
    *option_prefs = prefs;
    return 0;
 }
codec_prefs_to_str()
static int codec_prefs_to_str (const struct ast_stream_codec_negotiation_prefs * prefs, const void * obj, const intptr_t * args, char ** buf) static
Definition at line 1244 of file pjsip_configuration.c.
References ast_free, ast_str_create, ast_strdup, ast_stream_codec_prefs_to_str(), AST_STREAM_MAX_CODEC_PREFS_LENGTH, and codecs.
Referenced by incoming_answer_codec_prefs_to_str(), incoming_offer_codec_prefs_to_str(), outgoing_answer_codec_prefs_to_str(), and outgoing_offer_codec_prefs_to_str().
 {
    struct ast_str *codecs = ast_str_create(AST_STREAM_MAX_CODEC_PREFS_LENGTH);
    if (!codecs) {
       return -1;
    }
    *buf = ast_strdup(ast_stream_codec_prefs_to_str(prefs, &codecs));
    ast_free(codecs);
    return 0;
 }
connected_line_method_handler()
static int connected_line_method_handler (const struct aco_option * opt, struct ast_variable * var, void * obj) static
Definition at line 534 of file pjsip_configuration.c.
References ast_log, AST_SIP_SESSION_REFRESH_METHOD_INVITE, AST_SIP_SESSION_REFRESH_METHOD_UPDATE, ast_sorcery_object_get_id(), sip_persistent_endpoint::endpoint, ast_sip_endpoint::id, LOG_NOTICE, ast_variable::name, ast_sip_endpoint_id_configuration::refresh_method, and ast_variable::value.
Referenced by ast_res_pjsip_initialize_configuration().
 {
    struct ast_sip_endpoint *endpoint = obj;
    if (!strcasecmp(var->value, "invite") || !strcasecmp(var->value, "reinvite")) {
       endpoint->id.refresh_method = AST_SIP_SESSION_REFRESH_METHOD_INVITE;
    } else if (!strcasecmp(var->value, "update")) {
       endpoint->id.refresh_method = AST_SIP_SESSION_REFRESH_METHOD_UPDATE;
    } else {
       ast_log(LOG_NOTICE, "Unrecognized option value %s for %s on endpoint %s\n",
             var->value, var->name, ast_sorcery_object_get_id(endpoint));
       return -1;
    }
    return 0;
 }
connected_line_method_to_str()
static int connected_line_method_to_str (const void * obj, const intptr_t * args, char ** buf) static
Definition at line 550 of file pjsip_configuration.c.
References ast_strdup, sip_persistent_endpoint::endpoint, ast_sip_endpoint::id, id_configuration_refresh_methods, and ast_sip_endpoint_id_configuration::refresh_method.
Referenced by ast_res_pjsip_initialize_configuration().
 {
    const struct ast_sip_endpoint *endpoint = obj;
    *buf = ast_strdup(id_configuration_refresh_methods[endpoint->id.refresh_method]);
    return 0;
 }
contact_acl_to_str()
static int contact_acl_to_str (const void * obj, const intptr_t * args, char ** buf) static
Definition at line 125 of file pjsip_configuration.c.
References ast_acl_list_is_empty(), AST_LIST_FIRST, AST_LIST_LOCK, AST_LIST_UNLOCK, ast_strdup, ast_strlen_zero, ast_sip_endpoint::contact_acl, sip_persistent_endpoint::endpoint, and ast_acl::name.
Referenced by ast_res_pjsip_initialize_configuration().
 {
    const struct ast_sip_endpoint *endpoint = obj;
    struct ast_acl_list *acl_list;
    struct ast_acl *first_acl;
    if (endpoint && !ast_acl_list_is_empty(acl_list=endpoint->contact_acl)) {
       AST_LIST_LOCK(acl_list);
       first_acl = AST_LIST_FIRST(acl_list);
       if (ast_strlen_zero(first_acl->name)) {
          *buf = "deny/permit";
       } else {
          *buf = first_acl->name;
       }
       AST_LIST_UNLOCK(acl_list);
    }
    *buf = ast_strdup(*buf);
    return 0;
 }
contact_user_handler()
static int contact_user_handler (const struct aco_option * opt, struct ast_variable * var, void * obj) static
Definition at line 1101 of file pjsip_configuration.c.
References ast_free, ast_strdup, ast_sip_endpoint::contact_user, sip_persistent_endpoint::endpoint, and ast_variable::value.
Referenced by ast_res_pjsip_initialize_configuration().
 {
    struct ast_sip_endpoint *endpoint = obj;
    ast_free(endpoint->contact_user);
    endpoint->contact_user = ast_strdup(var->value);
    return endpoint->contact_user ? 0 : -1;
 }
contact_user_to_str()
static int contact_user_to_str (const void * obj, const intptr_t * args, char ** buf) static
Definition at line 1112 of file pjsip_configuration.c.
References ast_strdup, ast_sip_endpoint::contact_user, and sip_persistent_endpoint::endpoint.
Referenced by ast_res_pjsip_initialize_configuration().
 {
    const struct ast_sip_endpoint *endpoint = obj;
    *buf = ast_strdup(endpoint->contact_user);
    if (!(*buf)) {
       return -1;
    }
    return 0;
 }
direct_media_glare_mitigation_handler()
static int direct_media_glare_mitigation_handler (const struct aco_option * opt, struct ast_variable * var, void * obj) static
Definition at line 557 of file pjsip_configuration.c.
References ast_log, AST_SIP_DIRECT_MEDIA_GLARE_MITIGATION_INCOMING, AST_SIP_DIRECT_MEDIA_GLARE_MITIGATION_NONE, AST_SIP_DIRECT_MEDIA_GLARE_MITIGATION_OUTGOING, ast_sorcery_object_get_id(), ast_sip_endpoint_media_configuration::direct_media, sip_persistent_endpoint::endpoint, ast_sip_direct_media_configuration::glare_mitigation, LOG_NOTICE, ast_sip_endpoint::media, ast_variable::name, and ast_variable::value.
Referenced by ast_res_pjsip_initialize_configuration().
 {
    struct ast_sip_endpoint *endpoint = obj;
    if (!strcasecmp(var->value, "none")) {
       endpoint->media.direct_media.glare_mitigation = AST_SIP_DIRECT_MEDIA_GLARE_MITIGATION_NONE;
    } else if (!strcasecmp(var->value, "outgoing")) {
       endpoint->media.direct_media.glare_mitigation = AST_SIP_DIRECT_MEDIA_GLARE_MITIGATION_OUTGOING;
    } else if (!strcasecmp(var->value, "incoming")) {
       endpoint->media.direct_media.glare_mitigation = AST_SIP_DIRECT_MEDIA_GLARE_MITIGATION_INCOMING;
    } else {
       ast_log(LOG_NOTICE, "Unrecognized option value %s for %s on endpoint %s\n",
             var->value, var->name, ast_sorcery_object_get_id(endpoint));
       return -1;
    }
    return 0;
 }
direct_media_glare_mitigation_to_str()
static int direct_media_glare_mitigation_to_str (const void * obj, const intptr_t * args, char ** buf) static
Definition at line 582 of file pjsip_configuration.c.
References ARRAY_IN_BOUNDS, ast_strdup, ast_sip_endpoint_media_configuration::direct_media, direct_media_glare_mitigation_map, sip_persistent_endpoint::endpoint, ast_sip_direct_media_configuration::glare_mitigation, and ast_sip_endpoint::media.
Referenced by ast_res_pjsip_initialize_configuration().
 {
    const struct ast_sip_endpoint *endpoint = obj;
    if (ARRAY_IN_BOUNDS(endpoint->media.direct_media.glare_mitigation, direct_media_glare_mitigation_map)) {
       *buf = ast_strdup(direct_media_glare_mitigation_map[endpoint->media.direct_media.glare_mitigation]);
    }
    return 0;
 }
direct_media_method_handler()
static int direct_media_method_handler (const struct aco_option * opt, struct ast_variable * var, void * obj) static
Definition at line 504 of file pjsip_configuration.c.
References ast_log, AST_SIP_SESSION_REFRESH_METHOD_INVITE, AST_SIP_SESSION_REFRESH_METHOD_UPDATE, ast_sorcery_object_get_id(), ast_sip_endpoint_media_configuration::direct_media, sip_persistent_endpoint::endpoint, LOG_NOTICE, ast_sip_endpoint::media, ast_sip_direct_media_configuration::method, ast_variable::name, and ast_variable::value.
Referenced by ast_res_pjsip_initialize_configuration().
 {
    struct ast_sip_endpoint *endpoint = obj;
    if (!strcasecmp(var->value, "invite") || !strcasecmp(var->value, "reinvite")) {
       endpoint->media.direct_media.method = AST_SIP_SESSION_REFRESH_METHOD_INVITE;
    } else if (!strcasecmp(var->value, "update")) {
       endpoint->media.direct_media.method = AST_SIP_SESSION_REFRESH_METHOD_UPDATE;
    } else {
       ast_log(LOG_NOTICE, "Unrecognized option value %s for %s on endpoint %s\n",
             var->value, var->name, ast_sorcery_object_get_id(endpoint));
       return -1;
    }
    return 0;
 }
direct_media_method_to_str()
static int direct_media_method_to_str (const void * obj, const intptr_t * args, char ** buf) static
Definition at line 525 of file pjsip_configuration.c.
References ARRAY_IN_BOUNDS, ast_strdup, sip_persistent_endpoint::endpoint, ast_sip_endpoint::id, id_configuration_refresh_methods, and ast_sip_endpoint_id_configuration::refresh_method.
Referenced by ast_res_pjsip_initialize_configuration().
 {
    const struct ast_sip_endpoint *endpoint = obj;
    if (ARRAY_IN_BOUNDS(endpoint->id.refresh_method, id_configuration_refresh_methods)) {
       *buf = ast_strdup(id_configuration_refresh_methods[endpoint->id.refresh_method]);
    }
    return 0;
 }
dtls_handler()
static int dtls_handler (const struct aco_option * opt, struct ast_variable * var, void * obj) static
Definition at line 808 of file pjsip_configuration.c.
References ast_copy_string(), ast_rtp_dtls_cfg_parse(), ast_strdupa, buf, ast_sip_media_rtp_configuration::dtls_cfg, sip_persistent_endpoint::endpoint, ast_sip_endpoint::media, name, ast_variable::name, NULL, ast_sip_endpoint_media_configuration::rtp, and ast_variable::value.
Referenced by ast_res_pjsip_initialize_configuration().
 {
    struct ast_sip_endpoint *endpoint = obj;
    char *name = ast_strdupa(var->name);
    char *front = NULL;
    char *back = NULL;
    char *buf = name;
    /* strip out underscores in the name */
    front = strtok_r(buf, "_", &back);
    while (front) {
       int size = strlen(front);
       ast_copy_string(buf, front, size + 1);
       buf += size;
       front = strtok_r(NULL, "_", &back);
    }
    return ast_rtp_dtls_cfg_parse(&endpoint->media.rtp.dtls_cfg, name, var->value);
 }
dtlsautogeneratecert_to_str()
static int dtlsautogeneratecert_to_str (const void * obj, const intptr_t * args, char ** buf) static
Definition at line 844 of file pjsip_configuration.c.
References ast_strdup, AST_YESNO, ast_sip_media_rtp_configuration::dtls_cfg, sip_persistent_endpoint::endpoint, ast_rtp_dtls_cfg::ephemeral_cert, ast_sip_endpoint::media, and ast_sip_endpoint_media_configuration::rtp.
Referenced by ast_res_pjsip_initialize_configuration().
 {
    const struct ast_sip_endpoint *endpoint = obj;
    *buf = ast_strdup(AST_YESNO(endpoint->media.rtp.dtls_cfg.ephemeral_cert));
    return 0;
 }
dtlscafile_to_str()
static int dtlscafile_to_str (const void * obj, const intptr_t * args, char ** buf) static
Definition at line 872 of file pjsip_configuration.c.
References ast_strdup, ast_rtp_dtls_cfg::cafile, ast_sip_media_rtp_configuration::dtls_cfg, sip_persistent_endpoint::endpoint, ast_sip_endpoint::media, and ast_sip_endpoint_media_configuration::rtp.
Referenced by ast_res_pjsip_initialize_configuration().
 {
    const struct ast_sip_endpoint *endpoint = obj;
    *buf = ast_strdup(endpoint->media.rtp.dtls_cfg.cafile);
    return 0;
 }
dtlscapath_to_str()
static int dtlscapath_to_str (const void * obj, const intptr_t * args, char ** buf) static
Definition at line 879 of file pjsip_configuration.c.
References ast_strdup, ast_rtp_dtls_cfg::capath, ast_sip_media_rtp_configuration::dtls_cfg, sip_persistent_endpoint::endpoint, ast_sip_endpoint::media, and ast_sip_endpoint_media_configuration::rtp.
Referenced by ast_res_pjsip_initialize_configuration().
 {
    const struct ast_sip_endpoint *endpoint = obj;
    *buf = ast_strdup(endpoint->media.rtp.dtls_cfg.capath);
    return 0;
 }
dtlscertfile_to_str()
static int dtlscertfile_to_str (const void * obj, const intptr_t * args, char ** buf) static
Definition at line 851 of file pjsip_configuration.c.
References ast_strdup, ast_rtp_dtls_cfg::certfile, ast_sip_media_rtp_configuration::dtls_cfg, sip_persistent_endpoint::endpoint, ast_sip_endpoint::media, and ast_sip_endpoint_media_configuration::rtp.
Referenced by ast_res_pjsip_initialize_configuration().
 {
    const struct ast_sip_endpoint *endpoint = obj;
    *buf = ast_strdup(endpoint->media.rtp.dtls_cfg.certfile);
    return 0;
 }
dtlscipher_to_str()
static int dtlscipher_to_str (const void * obj, const intptr_t * args, char ** buf) static
Definition at line 865 of file pjsip_configuration.c.
References ast_strdup, ast_rtp_dtls_cfg::cipher, ast_sip_media_rtp_configuration::dtls_cfg, sip_persistent_endpoint::endpoint, ast_sip_endpoint::media, and ast_sip_endpoint_media_configuration::rtp.
Referenced by ast_res_pjsip_initialize_configuration().
 {
    const struct ast_sip_endpoint *endpoint = obj;
    *buf = ast_strdup(endpoint->media.rtp.dtls_cfg.cipher);
    return 0;
 }
dtlsfingerprint_to_str()
static int dtlsfingerprint_to_str (const void * obj, const intptr_t * args, char ** buf) static
Definition at line 907 of file pjsip_configuration.c.
References ARRAY_IN_BOUNDS, ast_rtp_dtls_fingerprint_map, ast_strdup, ast_sip_media_rtp_configuration::dtls_cfg, sip_persistent_endpoint::endpoint, ast_rtp_dtls_cfg::hash, ast_sip_endpoint::media, and ast_sip_endpoint_media_configuration::rtp.
Referenced by ast_res_pjsip_initialize_configuration().
 {
    const struct ast_sip_endpoint *endpoint = obj;
    if (ARRAY_IN_BOUNDS(endpoint->media.rtp.dtls_cfg.hash, ast_rtp_dtls_fingerprint_map)) {
       *buf = ast_strdup(ast_rtp_dtls_fingerprint_map[endpoint->media.rtp.dtls_cfg.hash]);
    }
    return 0;
 }
dtlsprivatekey_to_str()
static int dtlsprivatekey_to_str (const void * obj, const intptr_t * args, char ** buf) static
Definition at line 858 of file pjsip_configuration.c.
References ast_strdup, ast_sip_media_rtp_configuration::dtls_cfg, sip_persistent_endpoint::endpoint, ast_sip_endpoint::media, ast_rtp_dtls_cfg::pvtfile, and ast_sip_endpoint_media_configuration::rtp.
Referenced by ast_res_pjsip_initialize_configuration().
 {
    const struct ast_sip_endpoint *endpoint = obj;
    *buf = ast_strdup(endpoint->media.rtp.dtls_cfg.pvtfile);
    return 0;
 }
dtlsrekey_to_str()
static int dtlsrekey_to_str (const void * obj, const intptr_t * args, char ** buf) static
Definition at line 836 of file pjsip_configuration.c.
References ast_asprintf, ast_sip_media_rtp_configuration::dtls_cfg, sip_persistent_endpoint::endpoint, ast_sip_endpoint::media, ast_rtp_dtls_cfg::rekey, and ast_sip_endpoint_media_configuration::rtp.
Referenced by ast_res_pjsip_initialize_configuration().
 {
    const struct ast_sip_endpoint *endpoint = obj;
    return ast_asprintf(
       buf, "%u", endpoint->media.rtp.dtls_cfg.rekey) >=0 ? 0 : -1;
 }
dtlssetup_to_str()
static int dtlssetup_to_str (const void * obj, const intptr_t * args, char ** buf) static
Definition at line 893 of file pjsip_configuration.c.
References ARRAY_IN_BOUNDS, ast_rtp_dtls_setup_map, ast_strdup, ast_rtp_dtls_cfg::default_setup, ast_sip_media_rtp_configuration::dtls_cfg, sip_persistent_endpoint::endpoint, ast_sip_endpoint::media, and ast_sip_endpoint_media_configuration::rtp.
Referenced by ast_res_pjsip_initialize_configuration().
 {
    const struct ast_sip_endpoint *endpoint = obj;
    if (ARRAY_IN_BOUNDS(endpoint->media.rtp.dtls_cfg.default_setup, ast_rtp_dtls_setup_map)) {
       *buf = ast_strdup(ast_rtp_dtls_setup_map[endpoint->media.rtp.dtls_cfg.default_setup]);
    }
    return 0;
 }
dtlsverify_to_str()
static int dtlsverify_to_str (const void * obj, const intptr_t * args, char ** buf) static
Definition at line 829 of file pjsip_configuration.c.
References ast_strdup, AST_YESNO, ast_sip_media_rtp_configuration::dtls_cfg, sip_persistent_endpoint::endpoint, ast_sip_endpoint::media, ast_sip_endpoint_media_configuration::rtp, and ast_rtp_dtls_cfg::verify.
Referenced by ast_res_pjsip_initialize_configuration().
 {
    const struct ast_sip_endpoint *endpoint = obj;
    *buf = ast_strdup(AST_YESNO(endpoint->media.rtp.dtls_cfg.verify));
    return 0;
 }
dtmf_handler()
static int dtmf_handler (const struct aco_option * opt, struct ast_variable * var, void * obj) static
Definition at line 146 of file pjsip_configuration.c.
References ast_sip_str_to_dtmf(), ast_sip_endpoint::dtmf, sip_persistent_endpoint::endpoint, and ast_variable::value.
Referenced by ast_res_pjsip_initialize_configuration().
 {
    struct ast_sip_endpoint *endpoint = obj;
    int dtmf = ast_sip_str_to_dtmf(var->value);
    if (dtmf == -1) {
       return -1;
    }
    endpoint->dtmf = dtmf;
    return 0;
 }
dtmf_to_str()
static int dtmf_to_str (const void * obj, const intptr_t * args, char ** buf) static
Definition at line 159 of file pjsip_configuration.c.
References ast_sip_dtmf_to_str(), ast_strdup, ast_sip_endpoint::dtmf, sip_persistent_endpoint::endpoint, and result.
Referenced by ast_res_pjsip_initialize_configuration().
 {
    const struct ast_sip_endpoint *endpoint = obj;
    char dtmf_str[20];
    int result = -1;
    result = ast_sip_dtmf_to_str(endpoint->dtmf, dtmf_str, sizeof(dtmf_str));
    if (result == 0) {
       *buf = ast_strdup(dtmf_str);
    } else {
       *buf = ast_strdup("none");
    }
    return 0;
 }
endpoint_acl_handler()
static int endpoint_acl_handler (const struct aco_option * opt, struct ast_variable * var, void * obj) static
Definition at line 87 of file pjsip_configuration.c.
References ast_sip_endpoint::acl, ast_append_acl(), ast_strlen_zero, ast_sip_endpoint::contact_acl, sip_persistent_endpoint::endpoint, error(), sip_to_pjsip::ignore(), ast_variable::name, and ast_variable::value.
Referenced by ast_res_pjsip_initialize_configuration().
 {
    struct ast_sip_endpoint *endpoint = obj;
    int error = 0;
    int ignore;
    if (ast_strlen_zero(var->value)) return 0;
    if (!strncmp(var->name, "contact_", 8)) {
       ast_append_acl(var->name + 8, var->value, &endpoint->contact_acl, &error, &ignore);
    } else {
       ast_append_acl(var->name, var->value, &endpoint->acl, &error, &ignore);
    }
    return error;
 }
endpoint_deleted_observer()
static void endpoint_deleted_observer (const void * object) static
Definition at line 75 of file pjsip_configuration.c.
References ao2_find, ast_endpoint_get_resource(), sip_persistent_endpoint::endpoint, OBJ_NODATA, OBJ_SEARCH_KEY, OBJ_UNLINK, and ast_sip_endpoint::persistent.
 {
    const struct ast_sip_endpoint *endpoint = object;
    ao2_find(persistent_endpoints, ast_endpoint_get_resource(endpoint->persistent),
       OBJ_SEARCH_KEY | OBJ_UNLINK | OBJ_NODATA);
 }
endpoint_destructor()
static void endpoint_destructor (void * obj) static
Definition at line 2267 of file pjsip_configuration.c.
References ast_sip_endpoint::acl, ao2_cleanup, ast_free, ast_free_acl_list(), ast_party_id_free(), ast_sip_auth_vector_destroy(), ast_stream_topology_free(), ast_string_field_free_memory, ast_unref_namedgroups(), ast_variables_destroy(), AST_VECTOR_FREE, ast_sip_endpoint::channel_vars, ast_sip_endpoint_media_configuration::codecs, ast_sip_endpoint::contact_acl, ast_sip_endpoint::contact_user, sip_persistent_endpoint::endpoint, ast_sip_endpoint::id, ast_sip_endpoint::ident_method_order, ast_sip_endpoint::inbound_auths, ast_sip_endpoint::info, info_configuration_destroy(), ast_sip_endpoint::media, media_configuration_destroy(), ast_sip_endpoint_pickup_configuration::named_callgroups, ast_sip_endpoint_pickup_configuration::named_pickupgroups, ast_sip_endpoint::outbound_auths, ast_sip_endpoint::persistent, ast_sip_endpoint::pickup, ast_sip_endpoint_id_configuration::self, ast_sip_endpoint::subscription, subscription_configuration_destroy(), and ast_sip_endpoint_media_configuration::topology.
Referenced by ast_sip_endpoint_alloc().
 {
    struct ast_sip_endpoint *endpoint = obj;
    ast_string_field_free_memory(endpoint);
    ao2_cleanup(endpoint->media.codecs);
    ast_stream_topology_free(endpoint->media.topology);
    subscription_configuration_destroy(&endpoint->subscription);
    info_configuration_destroy(&endpoint->info);
    media_configuration_destroy(&endpoint->media);
    ast_sip_auth_vector_destroy(&endpoint->inbound_auths);
    ast_sip_auth_vector_destroy(&endpoint->outbound_auths);
    ast_party_id_free(&endpoint->id.self);
    endpoint->pickup.named_callgroups = ast_unref_namedgroups(endpoint->pickup.named_callgroups);
    endpoint->pickup.named_pickupgroups = ast_unref_namedgroups(endpoint->pickup.named_pickupgroups);
    ao2_cleanup(endpoint->persistent);
    ast_variables_destroy(endpoint->channel_vars);
    AST_VECTOR_FREE(&endpoint->ident_method_order);
    ast_free(endpoint->contact_user);
    ast_free_acl_list(endpoint->contact_acl);
    ast_free_acl_list(endpoint->acl);
 }
format_ami_endpoint()
static int format_ami_endpoint (const struct ast_sip_endpoint * endpoint, struct ast_sip_ami * ami) static
Definition at line 1658 of file pjsip_configuration.c.
References ast_free, ast_sip_create_ami_event(), ast_str_buffer(), astman_append(), buf, RAII_VAR, ast_sip_ami::s, and sip_endpoint_to_ami().
Referenced by ami_show_endpoint().
 {
    RAII_VAR(struct ast_str *, buf,
        ast_sip_create_ami_event("EndpointDetail", ami), ast_free);
    if (!buf) {
       return -1;
    }
    sip_endpoint_to_ami(endpoint, &buf);
    astman_append(ami->s, "%s\r\n", ast_str_buffer(buf));
    return 0;
 }
format_ami_endpoints()
static int format_ami_endpoints (void * obj, void * arg, int flags) static
Definition at line 1729 of file pjsip_configuration.c.
References active_channels_to_str(), ast_sip_endpoint::aors, ast_sip_ami::arg, ast_free, ast_sip_create_ami_event(), ast_sip_for_each_aor(), ast_sip_get_device_state(), ast_str_append(), ast_str_buffer(), astman_append(), buf, CMP_STOP, sip_persistent_endpoint::endpoint, format_str_append_auth(), ast_sip_endpoint::inbound_auths, ast_sip_endpoint::outbound_auths, RAII_VAR, ast_sip_ami::s, sip_endpoints_aors_ami(), sip_sorcery_object_ami_set_type_name(), and ast_sip_endpoint::transport.
Referenced by ami_show_endpoints().
 {
    struct ast_sip_endpoint *endpoint = obj;
    struct ast_sip_ami *ami = arg;
    RAII_VAR(struct ast_str *, buf,
        ast_sip_create_ami_event("EndpointList", ami), ast_free);
    if (!buf) {
       return CMP_STOP;
    }
    sip_sorcery_object_ami_set_type_name(endpoint, &buf);
    ast_str_append(&buf, 0, "Transport: %s\r\n",
              endpoint->transport);
    ast_str_append(&buf, 0, "Aor: %s\r\n",
              endpoint->aors);
    ast_str_append(&buf, 0, "Auths: ");
    format_str_append_auth(&endpoint->inbound_auths, &buf);
    ast_str_append(&buf, 0, "\r\n");
    ast_str_append(&buf, 0, "OutboundAuths: ");
    format_str_append_auth(&endpoint->outbound_auths, &buf);
    ast_str_append(&buf, 0, "\r\n");
    ast_sip_for_each_aor(endpoint->aors,
               sip_endpoints_aors_ami, &buf);
    ast_str_append(&buf, 0, "DeviceState: %s\r\n",
              ast_sip_get_device_state(endpoint));
    ast_str_append(&buf, 0, "ActiveChannels: ");
    active_channels_to_str(endpoint, &buf);
    ast_str_append(&buf, 0, "\r\n");
    astman_append(ami->s, "%s\r\n", ast_str_buffer(buf));
    return 0;
 }
format_str_append_auth()
static int format_str_append_auth (const struct ast_sip_auth_vector * auths, struct ast_str ** buf) static
Definition at line 1717 of file pjsip_configuration.c.
References ast_free, ast_sip_auths_to_str(), ast_str_append(), NULL, and str.
Referenced by format_ami_endpoints().
 {
    char *str = NULL;
    if (ast_sip_auths_to_str(auths, &str)) {
       return -1;
    }
    ast_str_append(buf, 0, "%s", str ? str : "");
    ast_free(str);
    return 0;
 }
from_user_handler()
static int from_user_handler (const struct aco_option * opt, struct ast_variable * var, void * obj) static
Definition at line 995 of file pjsip_configuration.c.
References ast_log, ast_sorcery_object_get_id(), ast_string_field_set, sip_persistent_endpoint::endpoint, ast_sip_endpoint::fromuser, LOG_ERROR, ast_variable::name, and ast_variable::value.
Referenced by ast_res_pjsip_initialize_configuration().
 {
    struct ast_sip_endpoint *endpoint = obj;
    /* Valid non-alphanumeric characters for URI */
    char *valid_uri_marks = "-._~%!$&'()*+,;=:";
    const char *val;
    for (val = var->value; *val; val++) {
       if (!isalpha(*val) && !isdigit(*val) && !strchr(valid_uri_marks, *val)) {
          ast_log(LOG_ERROR, "Error configuring endpoint '%s' - '%s' field "
          "contains invalid character '%c'\n",
          ast_sorcery_object_get_id(endpoint), var->name, *val);
          return -1;
       }
    }
    ast_string_field_set(endpoint, fromuser, var->value);
    return 0;
 }
from_user_to_str()
static int from_user_to_str (const void * obj, const intptr_t * args, char ** buf) static
Definition at line 1017 of file pjsip_configuration.c.
References ast_strdup, sip_persistent_endpoint::endpoint, and ast_sip_endpoint::fromuser.
Referenced by ast_res_pjsip_initialize_configuration().
 {
    const struct ast_sip_endpoint *endpoint = obj;
    *buf = ast_strdup(endpoint->fromuser);
    return 0;
 }
group_handler()
static int group_handler (const struct aco_option * opt, struct ast_variable * var, void * obj) static
Definition at line 720 of file pjsip_configuration.c.
References ast_get_group(), ast_sip_endpoint_pickup_configuration::callgroup, sip_persistent_endpoint::endpoint, ast_variable::name, ast_sip_endpoint::pickup, ast_sip_endpoint_pickup_configuration::pickupgroup, and ast_variable::value.
Referenced by ast_res_pjsip_initialize_configuration().
 {
    struct ast_sip_endpoint *endpoint = obj;
    if (!strncmp(var->name, "call_group", 10)) {
       endpoint->pickup.callgroup = ast_get_group(var->value);
    } else if (!strncmp(var->name, "pickup_group", 12)) {
       endpoint->pickup.pickupgroup = ast_get_group(var->value);
    } else {
       return -1;
    }
    return 0;
 }
ident_handler()
static int ident_handler (const struct aco_option * opt, struct ast_variable * var, void * obj) static
Definition at line 400 of file pjsip_configuration.c.
References ast_log, ast_sorcery_object_get_id(), ast_strdupa, ast_strip(), ast_strlen_zero, AST_VECTOR_APPEND, AST_VECTOR_ELEM_CLEANUP_NOOP, AST_VECTOR_RESET, AST_VECTOR_SIZE, sip_persistent_endpoint::endpoint, ast_sip_endpoint::ident_method, ast_sip_endpoint::ident_method_order, LOG_ERROR, method, sip_endpoint_identifier_str2type(), strsep(), and ast_variable::value.
Referenced by ast_res_pjsip_initialize_configuration().
 {
    struct ast_sip_endpoint *endpoint = obj;
    char *idents = ast_strdupa(var->value);
    char *val;
    int method;
    /*
     * If there's already something in the vector when we get here,
     * it's the default value so we need to clean it out.
     */
    if (AST_VECTOR_SIZE(&endpoint->ident_method_order)) {
       AST_VECTOR_RESET(&endpoint->ident_method_order, AST_VECTOR_ELEM_CLEANUP_NOOP);
       endpoint->ident_method = 0;
    }
    while ((val = ast_strip(strsep(&idents, ",")))) {
       if (ast_strlen_zero(val)) {
          continue;
       }
       method = sip_endpoint_identifier_str2type(val);
       if (method == -1) {
          ast_log(LOG_ERROR, "Unrecognized identification method %s specified for endpoint %s\n",
                val, ast_sorcery_object_get_id(endpoint));
          AST_VECTOR_RESET(&endpoint->ident_method_order, AST_VECTOR_ELEM_CLEANUP_NOOP);
          endpoint->ident_method = 0;
          return -1;
       }
       if (endpoint->ident_method & method) {
          /* We are already indentifying by this method.  No need to do it again. */
          continue;
       }
       endpoint->ident_method |= method;
       AST_VECTOR_APPEND(&endpoint->ident_method_order, method);
    }
    return 0;
 }
ident_to_str()
static int ident_to_str (const void * obj, const intptr_t * args, char ** buf) static
Definition at line 441 of file pjsip_configuration.c.
References ast_assert, ast_log, ast_malloc, AST_VECTOR_GET, AST_VECTOR_SIZE, sip_persistent_endpoint::endpoint, ast_sip_endpoint::ident_method_order, LOG_WARNING, MAX_OBJECT_FIELD, method, methods, and sip_endpoint_identifier_type2str().
Referenced by ast_res_pjsip_initialize_configuration().
 {
    const struct ast_sip_endpoint *endpoint = obj;
    int methods;
    int idx;
    int buf_used = 0;
    int buf_size = MAX_OBJECT_FIELD;
    methods = AST_VECTOR_SIZE(&endpoint->ident_method_order);
    if (!methods) {
       return 0;
    }
    *buf = ast_malloc(buf_size);
    if (!*buf) {
       return -1;
    }
    for (idx = 0; idx < methods; ++idx) {
       enum ast_sip_endpoint_identifier_type method;
       const char *method_str;
       method = AST_VECTOR_GET(&endpoint->ident_method_order, idx);
       method_str = sip_endpoint_identifier_type2str(method);
       /* Should never have an "<unknown>" method string */
       ast_assert(strcmp(method_str, "<unknown>"));
       if (!strcmp(method_str, "<unknown>")) {
          continue;
       }
       buf_used += snprintf(*buf + buf_used, buf_size - buf_used, "%s%s",
          method_str, idx < methods - 1 ? "," : "");
       if (buf_size <= buf_used) {
          /* Need more room than available, truncating. */
          *(*buf + (buf_size - 1)) = '\0';
          ast_log(LOG_WARNING, "Truncated identify_by string: %s\n", *buf);
          break;
       }
    }
    return 0;
 }
inbound_auth_handler()
static int inbound_auth_handler (const struct aco_option * opt, struct ast_variable * var, void * obj) static
Definition at line 303 of file pjsip_configuration.c.
References ast_sip_auth_vector_init(), sip_persistent_endpoint::endpoint, ast_sip_endpoint::inbound_auths, and ast_variable::value.
Referenced by ast_res_pjsip_initialize_configuration().
 {
    struct ast_sip_endpoint *endpoint = obj;
    return ast_sip_auth_vector_init(&endpoint->inbound_auths, var->value);
 }
inbound_auths_to_str()
static int inbound_auths_to_str (const void * obj, const intptr_t * args, char ** buf) static
Definition at line 332 of file pjsip_configuration.c.
References ast_sip_auths_to_str(), sip_persistent_endpoint::endpoint, and ast_sip_endpoint::inbound_auths.
Referenced by ast_res_pjsip_initialize_configuration().
 {
    const struct ast_sip_endpoint *endpoint = obj;
    return ast_sip_auths_to_str(&endpoint->inbound_auths, buf);
 }
incoming_answer_codec_prefs_to_str()
static int incoming_answer_codec_prefs_to_str (const void * obj, const intptr_t * args, char ** buf) static
Definition at line 1271 of file pjsip_configuration.c.
References ast_sip_endpoint_media_configuration::codec_prefs_incoming_answer, codec_prefs_to_str(), sip_persistent_endpoint::endpoint, and ast_sip_endpoint::media.
Referenced by ast_res_pjsip_initialize_configuration().
 {
    const struct ast_sip_endpoint *endpoint = obj;
    return codec_prefs_to_str(&endpoint->media.codec_prefs_incoming_answer, obj, args, buf);
 }
incoming_call_offer_pref_to_str()
static int incoming_call_offer_pref_to_str (const void * obj, const intptr_t * args, char ** buf) static
Definition at line 1145 of file pjsip_configuration.c.
References ast_sip_call_codec_pref_to_str(), ast_strdup, sip_persistent_endpoint::endpoint, ast_sip_endpoint_media_configuration::incoming_call_offer_pref, and ast_sip_endpoint::media.
Referenced by ast_res_pjsip_initialize_configuration().
 {
    const struct ast_sip_endpoint *endpoint = obj;
    *buf = ast_strdup(ast_sip_call_codec_pref_to_str(endpoint->media.incoming_call_offer_pref));
    if (!(*buf)) {
       return -1;
    }
    return 0;
 }
incoming_offer_codec_prefs_to_str()
static int incoming_offer_codec_prefs_to_str (const void * obj, const intptr_t * args, char ** buf) static
Definition at line 1259 of file pjsip_configuration.c.
References ast_sip_endpoint_media_configuration::codec_prefs_incoming_offer, codec_prefs_to_str(), sip_persistent_endpoint::endpoint, and ast_sip_endpoint::media.
Referenced by ast_res_pjsip_initialize_configuration().
 {
    const struct ast_sip_endpoint *endpoint = obj;
    return codec_prefs_to_str(&endpoint->media.codec_prefs_incoming_offer, obj, args, buf);
 }
info_configuration_destroy()
static void info_configuration_destroy (struct ast_sip_endpoint_info_configuration * info) static
Definition at line 2255 of file pjsip_configuration.c.
References ast_string_field_free_memory, and ast_sip_endpoint_info_configuration::recording.
Referenced by endpoint_destructor().
 {
    ast_string_field_free_memory(&info->recording);
 }
init_info_configuration()
static int init_info_configuration (struct ast_sip_endpoint_info_configuration * info) static
Definition at line 2296 of file pjsip_configuration.c.
References ast_string_field_init, and ast_sip_endpoint_info_configuration::recording.
Referenced by ast_sip_endpoint_alloc().
 {
    return ast_string_field_init(&info->recording, 32);
 }
init_media_configuration()
static int init_media_configuration (struct ast_sip_endpoint_media_configuration * media) static
Definition at line 2301 of file pjsip_configuration.c.
References ast_string_field_init, and ast_sip_endpoint_media_configuration::rtp.
Referenced by ast_sip_endpoint_alloc().
 {
    return ast_string_field_init(media, 64) || ast_string_field_init(&media->rtp, 32);
 }
init_subscription_configuration()
static int init_subscription_configuration (struct ast_sip_endpoint_subscription_configuration * subscription) static
Definition at line 2291 of file pjsip_configuration.c.
References ast_string_field_init, and ast_sip_endpoint_subscription_configuration::mwi.
Referenced by ast_sip_endpoint_alloc().
 {
    return ast_string_field_init(&subscription->mwi, 64);
 }
load_all_endpoints()
static void load_all_endpoints (void) static
Definition at line 1955 of file pjsip_configuration.c.
References ao2_cleanup, AST_RETRIEVE_FLAG_ALL, AST_RETRIEVE_FLAG_MULTIPLE, ast_sorcery_retrieve_by_fields(), endpoints, and NULL.
Referenced by ast_res_pjsip_initialize_configuration().
 {
    struct ao2_container *endpoints;
    endpoints = ast_sorcery_retrieve_by_fields(sip_sorcery, "endpoint", AST_RETRIEVE_FLAG_MULTIPLE | AST_RETRIEVE_FLAG_ALL, NULL);
    ao2_cleanup(endpoints);
 }
media_configuration_destroy()
static void media_configuration_destroy (struct ast_sip_endpoint_media_configuration * media) static
Definition at line 2260 of file pjsip_configuration.c.
References ast_rtp_dtls_cfg_free(), ast_string_field_free_memory, ast_sip_media_rtp_configuration::dtls_cfg, and ast_sip_endpoint_media_configuration::rtp.
Referenced by endpoint_destructor().
 {
    ast_rtp_dtls_cfg_free(&media->rtp.dtls_cfg);
    ast_string_field_free_memory(&media->rtp);
    ast_string_field_free_memory(media);
 }
media_encryption_handler()
static int media_encryption_handler (const struct aco_option * opt, struct ast_variable * var, void * obj) static
Definition at line 685 of file pjsip_configuration.c.
References ast_rtp_dtls_cfg_parse(), AST_SIP_MEDIA_ENCRYPT_DTLS, AST_SIP_MEDIA_ENCRYPT_NONE, AST_SIP_MEDIA_ENCRYPT_SDES, ast_sip_media_rtp_configuration::dtls_cfg, ast_sip_media_rtp_configuration::encryption, sip_persistent_endpoint::endpoint, ast_sip_endpoint::media, ast_sip_endpoint_media_configuration::rtp, and ast_variable::value.
Referenced by ast_res_pjsip_initialize_configuration().
 {
    struct ast_sip_endpoint *endpoint = obj;
    if (!strcasecmp("no", var->value)) {
       endpoint->media.rtp.encryption = AST_SIP_MEDIA_ENCRYPT_NONE;
    } else if (!strcasecmp("sdes", var->value)) {
       endpoint->media.rtp.encryption = AST_SIP_MEDIA_ENCRYPT_SDES;
    } else if (!strcasecmp("dtls", var->value)) {
       endpoint->media.rtp.encryption = AST_SIP_MEDIA_ENCRYPT_DTLS;
       return ast_rtp_dtls_cfg_parse(&endpoint->media.rtp.dtls_cfg, "dtlsenable", "yes");
    } else {
       return -1;
    }
    return 0;
 }
media_encryption_to_str()
static int media_encryption_to_str (const void * obj, const intptr_t * args, char ** buf) static
Definition at line 710 of file pjsip_configuration.c.
References ARRAY_IN_BOUNDS, ast_strdup, ast_sip_media_rtp_configuration::encryption, sip_persistent_endpoint::endpoint, ast_sip_endpoint::media, media_encryption_map, and ast_sip_endpoint_media_configuration::rtp.
Referenced by ast_res_pjsip_initialize_configuration().
 {
    const struct ast_sip_endpoint *endpoint = obj;
    if (ARRAY_IN_BOUNDS(endpoint->media.rtp.encryption, media_encryption_map)) {
       *buf = ast_strdup(media_encryption_map[
                  endpoint->media.rtp.encryption]);
    }
    return 0;
 }
named_callgroups_to_str()
static int named_callgroups_to_str (const void * obj, const intptr_t * args, char ** buf) static
Definition at line 788 of file pjsip_configuration.c.
References ast_free, ast_print_namedgroups(), ast_str_buffer(), ast_str_create, ast_strdup, sip_persistent_endpoint::endpoint, MAX_OBJECT_FIELD, ast_sip_endpoint_pickup_configuration::named_callgroups, ast_sip_endpoint::pickup, RAII_VAR, and str.
Referenced by ast_res_pjsip_initialize_configuration().
 {
    const struct ast_sip_endpoint *endpoint = obj;
    RAII_VAR(struct ast_str *, str, ast_str_create(MAX_OBJECT_FIELD), ast_free);
    ast_print_namedgroups(&str, endpoint->pickup.named_callgroups);
    *buf = ast_strdup(ast_str_buffer(str));
    return 0;
 }
named_groups_handler()
static int named_groups_handler (const struct aco_option * opt, struct ast_variable * var, void * obj) static
Definition at line 760 of file pjsip_configuration.c.
References ast_get_namedgroups(), ast_strlen_zero, ast_unref_namedgroups(), sip_persistent_endpoint::endpoint, ast_variable::name, ast_sip_endpoint_pickup_configuration::named_callgroups, ast_sip_endpoint_pickup_configuration::named_pickupgroups, ast_sip_endpoint::pickup, and ast_variable::value.
Referenced by ast_res_pjsip_initialize_configuration().
 {
    struct ast_sip_endpoint *endpoint = obj;
    if (!strncmp(var->name, "named_call_group", 16)) {
       if (ast_strlen_zero(var->value)) {
          endpoint->pickup.named_callgroups =
             ast_unref_namedgroups(endpoint->pickup.named_callgroups);
       } else if (!(endpoint->pickup.named_callgroups =
             ast_get_namedgroups(var->value))) {
          return -1;
       }
    } else if (!strncmp(var->name, "named_pickup_group", 18)) {
       if (ast_strlen_zero(var->value)) {
          endpoint->pickup.named_pickupgroups =
             ast_unref_namedgroups(endpoint->pickup.named_pickupgroups);
       } else if (!(endpoint->pickup.named_pickupgroups =
             ast_get_namedgroups(var->value))) {
          return -1;
       }
    } else {
       return -1;
    }
    return 0;
 }
named_pickupgroups_to_str()
static int named_pickupgroups_to_str (const void * obj, const intptr_t * args, char ** buf) static
Definition at line 798 of file pjsip_configuration.c.
References ast_free, ast_print_namedgroups(), ast_str_buffer(), ast_str_create, ast_strdup, sip_persistent_endpoint::endpoint, MAX_OBJECT_FIELD, ast_sip_endpoint_pickup_configuration::named_pickupgroups, ast_sip_endpoint::pickup, RAII_VAR, and str.
Referenced by ast_res_pjsip_initialize_configuration().
 {
    const struct ast_sip_endpoint *endpoint = obj;
    RAII_VAR(struct ast_str *, str, ast_str_create(MAX_OBJECT_FIELD), ast_free);
    ast_print_namedgroups(&str, endpoint->pickup.named_pickupgroups);
    *buf = ast_strdup(ast_str_buffer(str));
    return 0;
 }
outbound_auth_handler()
static int outbound_auth_handler (const struct aco_option * opt, struct ast_variable * var, void * obj) static
Definition at line 310 of file pjsip_configuration.c.
References ast_sip_auth_vector_init(), sip_persistent_endpoint::endpoint, ast_sip_endpoint::outbound_auths, and ast_variable::value.
Referenced by ast_res_pjsip_initialize_configuration().
 {
    struct ast_sip_endpoint *endpoint = obj;
    return ast_sip_auth_vector_init(&endpoint->outbound_auths, var->value);
 }
outbound_auths_to_str()
static int outbound_auths_to_str (const void * obj, const intptr_t * args, char ** buf) static
Definition at line 338 of file pjsip_configuration.c.
References ast_sip_auths_to_str(), sip_persistent_endpoint::endpoint, and ast_sip_endpoint::outbound_auths.
Referenced by ast_res_pjsip_initialize_configuration().
 {
    const struct ast_sip_endpoint *endpoint = obj;
    return ast_sip_auths_to_str(&endpoint->outbound_auths, buf);
 }
outgoing_answer_codec_prefs_to_str()
static int outgoing_answer_codec_prefs_to_str (const void * obj, const intptr_t * args, char ** buf) static
Definition at line 1277 of file pjsip_configuration.c.
References ast_sip_endpoint_media_configuration::codec_prefs_outgoing_answer, codec_prefs_to_str(), sip_persistent_endpoint::endpoint, and ast_sip_endpoint::media.
Referenced by ast_res_pjsip_initialize_configuration().
 {
    const struct ast_sip_endpoint *endpoint = obj;
    return codec_prefs_to_str(&endpoint->media.codec_prefs_outgoing_answer, obj, args, buf);
 }
outgoing_call_offer_pref_to_str()
static int outgoing_call_offer_pref_to_str (const void * obj, const intptr_t * args, char ** buf) static
Definition at line 1157 of file pjsip_configuration.c.
References ast_sip_call_codec_pref_to_str(), ast_strdup, sip_persistent_endpoint::endpoint, ast_sip_endpoint::media, and ast_sip_endpoint_media_configuration::outgoing_call_offer_pref.
Referenced by ast_res_pjsip_initialize_configuration().
 {
    const struct ast_sip_endpoint *endpoint = obj;
    *buf = ast_strdup(ast_sip_call_codec_pref_to_str(endpoint->media.outgoing_call_offer_pref));
    if (!(*buf)) {
       return -1;
    }
    return 0;
 }
outgoing_offer_codec_prefs_to_str()
static int outgoing_offer_codec_prefs_to_str (const void * obj, const intptr_t * args, char ** buf) static
Definition at line 1265 of file pjsip_configuration.c.
References ast_sip_endpoint_media_configuration::codec_prefs_outgoing_offer, codec_prefs_to_str(), sip_persistent_endpoint::endpoint, and ast_sip_endpoint::media.
Referenced by ast_res_pjsip_initialize_configuration().
 {
    const struct ast_sip_endpoint *endpoint = obj;
    return codec_prefs_to_str(&endpoint->media.codec_prefs_outgoing_offer, obj, args, buf);
 }
persistent_endpoint_cmp()
static int persistent_endpoint_cmp (void * obj, void * arg, int flags) static
Comparison function for persistent endpoint information.
Definition at line 66 of file pjsip_configuration.c.
References ast_endpoint_get_resource(), CMP_MATCH, CMP_STOP, sip_persistent_endpoint::endpoint, and OBJ_KEY.
Referenced by ast_res_pjsip_initialize_configuration().
 {
    const struct sip_persistent_endpoint *persistent1 = obj;
    const struct sip_persistent_endpoint *persistent2 = arg;
    const char *id = (flags & OBJ_KEY ? arg : ast_endpoint_get_resource(persistent2->endpoint));
    return !strcmp(ast_endpoint_get_resource(persistent1->endpoint), id) ? CMP_MATCH | CMP_STOP : 0;
 }
persistent_endpoint_destroy()
static void persistent_endpoint_destroy (void * obj) static
Destructor function for persistent endpoint information.
Definition at line 1289 of file pjsip_configuration.c.
References ast_endpoint_shutdown(), and sip_persistent_endpoint::endpoint.
Referenced by persistent_endpoint_find_or_create().
 {
    struct sip_persistent_endpoint *persistent = obj;
    ast_endpoint_shutdown(persistent->endpoint);
 }
persistent_endpoint_find_or_create()
static struct ast_endpoint* persistent_endpoint_find_or_create (const struct ast_sip_endpoint * endpoint) static
Internal function which finds (or creates) persistent endpoint information.
Definition at line 1413 of file pjsip_configuration.c.
References AO2_ALLOC_OPT_LOCK_NOLOCK, ao2_alloc_options, ao2_cleanup, ao2_find, ao2_link_flags, ao2_ref, ast_endpoint_create(), AST_ENDPOINT_OFFLINE, ast_endpoint_set_state(), ast_sorcery_object_get_id(), lock, NULL, OBJ_NOLOCK, OBJ_SEARCH_KEY, persistent_endpoint_destroy(), RAII_VAR, and SCOPED_AO2LOCK.
Referenced by sip_endpoint_apply_handler().
 {
    RAII_VAR(struct sip_persistent_endpoint *, persistent, NULL, ao2_cleanup);
    SCOPED_AO2LOCK(lock, persistent_endpoints);
    persistent = ao2_find(persistent_endpoints, ast_sorcery_object_get_id(endpoint),
       OBJ_SEARCH_KEY | OBJ_NOLOCK);
    if (!persistent) {
       persistent = ao2_alloc_options(sizeof(*persistent), persistent_endpoint_destroy,
          AO2_ALLOC_OPT_LOCK_NOLOCK);
       if (!persistent) {
          return NULL;
       }
       persistent->endpoint = ast_endpoint_create("PJSIP",
          ast_sorcery_object_get_id(endpoint));
       if (!persistent->endpoint) {
          return NULL;
       }
       ast_endpoint_set_state(persistent->endpoint, AST_ENDPOINT_OFFLINE);
       ao2_link_flags(persistent_endpoints, persistent, OBJ_NOLOCK);
    }
    ao2_ref(persistent->endpoint, +1);
    return persistent->endpoint;
 }
persistent_endpoint_hash()
static int persistent_endpoint_hash (const void * obj, const int flags) static
Hashing function for persistent endpoint information.
Definition at line 57 of file pjsip_configuration.c.
References ast_endpoint_get_resource(), ast_str_hash(), sip_persistent_endpoint::endpoint, and OBJ_KEY.
Referenced by ast_res_pjsip_initialize_configuration().
 {
    const struct sip_persistent_endpoint *persistent = obj;
    const char *id = (flags & OBJ_KEY ? obj : ast_endpoint_get_resource(persistent->endpoint));
    return ast_str_hash(id);
 }
pickupgroup_to_str()
static int pickupgroup_to_str (const void * obj, const intptr_t * args, char ** buf) static
Definition at line 748 of file pjsip_configuration.c.
References ast_calloc, ast_print_group(), sip_persistent_endpoint::endpoint, MAX_OBJECT_FIELD, ast_sip_endpoint::pickup, and ast_sip_endpoint_pickup_configuration::pickupgroup.
Referenced by ast_res_pjsip_initialize_configuration().
 {
    const struct ast_sip_endpoint *endpoint = obj;
    if (!(*buf = ast_calloc(MAX_OBJECT_FIELD, sizeof(char)))) {
       return -1;
    }
    ast_print_group(*buf, MAX_OBJECT_FIELD, endpoint->pickup.pickupgroup);
    return 0;
 }
prack_handler()
static int prack_handler (const struct aco_option * opt, struct ast_variable * var, void * obj) static
Definition at line 175 of file pjsip_configuration.c.
References ast_false(), ast_true(), sip_persistent_endpoint::endpoint, ast_sip_endpoint::extensions, ast_sip_endpoint_extensions::flags, and ast_variable::value.
Referenced by ast_res_pjsip_initialize_configuration().
 {
    struct ast_sip_endpoint *endpoint = obj;
    /* clear all */
    endpoint->extensions.flags &= ~(PJSIP_INV_SUPPORT_100REL | PJSIP_INV_REQUIRE_100REL);
    if (ast_true(var->value)) {
       endpoint->extensions.flags |= PJSIP_INV_SUPPORT_100REL;
    } else if (!strcasecmp(var->value, "required")) {
       endpoint->extensions.flags |= PJSIP_INV_REQUIRE_100REL;
    } else if (!ast_false(var->value)){
       return -1;
    }
    return 0;
 }
prack_to_str()
static int prack_to_str (const void * obj, const intptr_t * args, char ** buf) static
Definition at line 193 of file pjsip_configuration.c.
References ast_strdup, sip_persistent_endpoint::endpoint, ast_sip_endpoint::extensions, and ast_sip_endpoint_extensions::flags.
Referenced by ast_res_pjsip_initialize_configuration().
 {
    const struct ast_sip_endpoint *endpoint = obj;
    if (endpoint->extensions.flags & PJSIP_INV_REQUIRE_100REL) {
       *buf = "required";
    } else if (endpoint->extensions.flags & PJSIP_INV_SUPPORT_100REL) {
       *buf = "yes";
    } else {
       *buf = "no";
    }
    *buf = ast_strdup(*buf);
    return 0;
 }
redirect_handler()
static int redirect_handler (const struct aco_option * opt, struct ast_variable * var, void * obj) static
Definition at line 485 of file pjsip_configuration.c.
References ast_log, AST_SIP_REDIRECT_URI_CORE, AST_SIP_REDIRECT_URI_PJSIP, AST_SIP_REDIRECT_USER, ast_sorcery_object_get_id(), sip_persistent_endpoint::endpoint, LOG_ERROR, ast_sip_endpoint::redirect_method, and ast_variable::value.
Referenced by ast_res_pjsip_initialize_configuration().
 {
    struct ast_sip_endpoint *endpoint = obj;
    if (!strcasecmp(var->value, "user")) {
       endpoint->redirect_method = AST_SIP_REDIRECT_USER;
    } else if (!strcasecmp(var->value, "uri_core")) {
       endpoint->redirect_method = AST_SIP_REDIRECT_URI_CORE;
    } else if (!strcasecmp(var->value, "uri_pjsip")) {
       endpoint->redirect_method = AST_SIP_REDIRECT_URI_PJSIP;
    } else {
       ast_log(LOG_ERROR, "Unrecognized redirect method %s specified for endpoint %s\n",
          var->value, ast_sorcery_object_get_id(endpoint));
       return -1;
    }
    return 0;
 }
set_var_handler()
static int set_var_handler (const struct aco_option * opt, struct ast_variable * var, void * obj) static
Definition at line 1026 of file pjsip_configuration.c.
References ast_strdupa, ast_strlen_zero, ast_variable_list_append, ast_variable_list_replace(), ast_variable_new, ast_sip_endpoint::channel_vars, sip_persistent_endpoint::endpoint, name, and ast_variable::value.
Referenced by ast_res_pjsip_initialize_configuration().
 {
    struct ast_sip_endpoint *endpoint = obj;
    struct ast_variable *new_var;
    char *name;
    char *val;
    if (ast_strlen_zero(var->value)) {
       return 0;
    }
    name = ast_strdupa(var->value);
    val = strchr(name, '=');
    if (!val) {
       return -1;
    }
    *val++ = '\0';
    if (!(new_var = ast_variable_new(name, val, ""))) {
       return -1;
    }
    if (ast_variable_list_replace(&endpoint->channel_vars, new_var)) {
       ast_variable_list_append(&endpoint->channel_vars, new_var);
    }
    return 0;
 }
set_var_to_str()
static int set_var_to_str (const void * obj, const intptr_t * args, char ** buf) static
Definition at line 1058 of file pjsip_configuration.c.
References ast_free, ast_str_append(), ast_str_create, ast_str_truncate(), ast_strdup, ast_sip_endpoint::channel_vars, sip_persistent_endpoint::endpoint, MAX_OBJECT_FIELD, ast_variable::name, ast_variable::next, str, ast_variable::value, and var.
Referenced by ast_res_pjsip_initialize_configuration().
 {
    struct ast_str *str = ast_str_create(MAX_OBJECT_FIELD);
    const struct ast_sip_endpoint *endpoint = obj;
    struct ast_variable *var;
    for (var = endpoint->channel_vars; var; var = var->next) {
       ast_str_append(&str, 0, "%s=%s,", var->name, var->value);
    }
    *buf = ast_strdup(ast_str_truncate(str, -1));
    ast_free(str);
    return 0;
 }
set_var_to_vl()
static int set_var_to_vl (const void * obj, struct ast_variable ** fields) static
Definition at line 1073 of file pjsip_configuration.c.
References ast_variables_dup(), ast_sip_endpoint::channel_vars, and sip_persistent_endpoint::endpoint.
Referenced by ast_res_pjsip_initialize_configuration().
 {
    const struct ast_sip_endpoint *endpoint = obj;
    if (endpoint->channel_vars) {
       *fields = ast_variables_dup(endpoint->channel_vars);
    }
    return 0;
 }
sip_endpoint_apply_handler()
static int sip_endpoint_apply_handler (const struct ast_sorcery * sorcery, void * obj) static
Callback function for when an object is finalized.
Definition at line 1443 of file pjsip_configuration.c.
References ast_clear_flag, ast_log, ast_rtp_dtls_cfg_validate(), AST_RTP_DTLS_SETUP_ACTPASS, AST_RTP_DTLS_VERIFY_FINGERPRINT, ast_set_flag, AST_SIP_CALL_CODEC_PREF_ALL, AST_SIP_CALL_CODEC_PREF_FIRST, AST_SIP_CALL_CODEC_PREF_INTERSECT, AST_SIP_CALL_CODEC_PREF_LOCAL, AST_SIP_MEDIA_ENCRYPT_DTLS, ast_sorcery_object_get_id(), ast_stream_topology_create_from_format_cap(), ast_strlen_zero, ast_sip_endpoint_media_configuration::bundle, ast_rtp_dtls_cfg::certfile, ast_sip_endpoint_media_configuration::codecs, ast_rtp_dtls_cfg::default_setup, ast_sip_media_rtp_configuration::dtls_cfg, ast_rtp_dtls_cfg::enabled, ast_sip_media_rtp_configuration::encryption, sip_persistent_endpoint::endpoint, ast_rtp_dtls_cfg::ephemeral_cert, ast_sip_endpoint::extensions, ast_flags::flags, ast_sip_media_rtp_configuration::ice_support, ast_sip_endpoint_media_configuration::incoming_call_offer_pref, LOG_ERROR, ast_sip_endpoint::media, ast_sip_timer_options::min_se, ast_sip_endpoint::persistent, persistent_endpoint_find_or_create(), ast_sip_endpoint::preferred_codec_only, ast_sip_endpoint_media_configuration::rtcp_mux, ast_sip_endpoint_media_configuration::rtp, ast_sip_timer_options::sess_expires, ast_sip_endpoint_extensions::timer, ast_sip_endpoint_media_configuration::topology, ast_sip_media_rtp_configuration::use_avpf, ast_sip_media_rtp_configuration::use_received_transport, ast_rtp_dtls_cfg::verify, and ast_sip_endpoint_media_configuration::webrtc.
Referenced by ast_res_pjsip_initialize_configuration().
 {
    struct ast_sip_endpoint *endpoint = obj;
    if (!(endpoint->persistent = persistent_endpoint_find_or_create(endpoint))) {
       return -1;
    }
    if (endpoint->extensions.timer.min_se < 90) {
       ast_log(LOG_ERROR, "Session timer minimum expires time must be 90 or greater on endpoint '%s'\n",
          ast_sorcery_object_get_id(endpoint));
       return -1;
    } else if (endpoint->extensions.timer.sess_expires < endpoint->extensions.timer.min_se) {
       ast_log(LOG_ERROR, "Session timer expires must be greater than minimum session expires time on endpoint '%s'\n",
          ast_sorcery_object_get_id(endpoint));
       return -1;
    }
    if (ast_rtp_dtls_cfg_validate(&endpoint->media.rtp.dtls_cfg)) {
       return -1;
    }
    if (endpoint->preferred_codec_only) {
       if (endpoint->media.incoming_call_offer_pref.flags != (AST_SIP_CALL_CODEC_PREF_LOCAL | AST_SIP_CALL_CODEC_PREF_INTERSECT | AST_SIP_CALL_CODEC_PREF_ALL)) {
          ast_log(LOG_ERROR, "Setting both preferred_codec_only and incoming_call_offer_pref is not supported on endpoint '%s'\n",
             ast_sorcery_object_get_id(endpoint));
          return -1;
       }
       ast_clear_flag(&endpoint->media.incoming_call_offer_pref, AST_SIP_CALL_CODEC_PREF_ALL);
       ast_set_flag(&endpoint->media.incoming_call_offer_pref, AST_SIP_CALL_CODEC_PREF_FIRST);
    }
    endpoint->media.topology = ast_stream_topology_create_from_format_cap(endpoint->media.codecs);
    if (!endpoint->media.topology) {
       return -1;
    }
    endpoint->media.rtcp_mux |= endpoint->media.bundle;
    /*
     * If webrtc has been enabled then enable those attributes, and default
     * some, that are needed in order for webrtc to work.
     */
    endpoint->media.bundle |= endpoint->media.webrtc;
    endpoint->media.rtcp_mux |= endpoint->media.webrtc;
    endpoint->media.rtp.use_avpf |= endpoint->media.webrtc;
    endpoint->media.rtp.ice_support |= endpoint->media.webrtc;
    endpoint->media.rtp.use_received_transport |= endpoint->media.webrtc;
    if (endpoint->media.webrtc) {
       endpoint->media.rtp.encryption = AST_SIP_MEDIA_ENCRYPT_DTLS;
       endpoint->media.rtp.dtls_cfg.enabled = 1;
       endpoint->media.rtp.dtls_cfg.default_setup = AST_RTP_DTLS_SETUP_ACTPASS;
       endpoint->media.rtp.dtls_cfg.verify = AST_RTP_DTLS_VERIFY_FINGERPRINT;
       if (ast_strlen_zero(endpoint->media.rtp.dtls_cfg.certfile)) {
          /* If no certificate has been specified, try to automatically create one */
          endpoint->media.rtp.dtls_cfg.ephemeral_cert = 1;
       }
    }
    return 0;
 }
sip_endpoint_identifier_str2type()
static int sip_endpoint_identifier_str2type (const char * str) static
Definition at line 382 of file pjsip_configuration.c.
References AST_SIP_ENDPOINT_IDENTIFY_BY_AUTH_USERNAME, AST_SIP_ENDPOINT_IDENTIFY_BY_HEADER, AST_SIP_ENDPOINT_IDENTIFY_BY_IP, AST_SIP_ENDPOINT_IDENTIFY_BY_USERNAME, and method.
Referenced by ident_handler().
 {
    int method;
    if (!strcasecmp(str, "username")) {
       method = AST_SIP_ENDPOINT_IDENTIFY_BY_USERNAME;
    } else if (!strcasecmp(str, "auth_username")) {
       method = AST_SIP_ENDPOINT_IDENTIFY_BY_AUTH_USERNAME;
    } else if (!strcasecmp(str, "ip")) {
       method = AST_SIP_ENDPOINT_IDENTIFY_BY_IP;
    } else if (!strcasecmp(str, "header")) {
       method = AST_SIP_ENDPOINT_IDENTIFY_BY_HEADER;
    } else {
       method = -1;
    }
    return method;
 }
sip_endpoint_identifier_type2str()
static const char* sip_endpoint_identifier_type2str (enum ast_sip_endpoint_identifier_type method) static
Definition at line 352 of file pjsip_configuration.c.
References AST_SIP_ENDPOINT_IDENTIFY_BY_AUTH_USERNAME, AST_SIP_ENDPOINT_IDENTIFY_BY_HEADER, AST_SIP_ENDPOINT_IDENTIFY_BY_IP, AST_SIP_ENDPOINT_IDENTIFY_BY_USERNAME, and str.
Referenced by ident_to_str().
 {
    const char *str = "<unknown>";
    switch (method) {
    case AST_SIP_ENDPOINT_IDENTIFY_BY_USERNAME:
       str = "username";
       break;
    case AST_SIP_ENDPOINT_IDENTIFY_BY_AUTH_USERNAME:
       str = "auth_username";
       break;
    case AST_SIP_ENDPOINT_IDENTIFY_BY_IP:
       str = "ip";
       break;
    case AST_SIP_ENDPOINT_IDENTIFY_BY_HEADER:
       str = "header";
       break;
    }
    return str;
 }
sip_endpoint_to_ami()
static int sip_endpoint_to_ami (const struct ast_sip_endpoint * endpoint, struct ast_str ** buf) static
Definition at line 1641 of file pjsip_configuration.c.
References active_channels_to_str(), ast_sip_get_device_state(), ast_sip_sorcery_object_to_ami(), and ast_str_append().
Referenced by format_ami_endpoint().
 {
    if (ast_sip_sorcery_object_to_ami(endpoint, buf)) {
       return -1;
    }
    ast_str_append(buf, 0, "DeviceState: %s\r\n",
              ast_sip_get_device_state(endpoint));
    ast_str_append(buf, 0, "ActiveChannels: ");
    active_channels_to_str(endpoint, buf);
    ast_str_append(buf, 0, "\r\n");
    return 0;
 }
sip_endpoints_aors_ami()
static int sip_endpoints_aors_ami (void * obj, void * arg, int flags) static
Definition at line 1629 of file pjsip_configuration.c.
References ast_sip_contact_to_str(), ast_sip_for_each_contact(), ast_str_append(), and buf.
Referenced by format_ami_endpoints().
 {
    struct ast_sip_aor *aor = obj;
    struct ast_str **buf = arg;
    ast_str_append(buf, 0, "Contacts: ");
    ast_sip_for_each_contact(aor, ast_sip_contact_to_str, arg);
    ast_str_append(buf, 0, "\r\n");
    return 0;
 }
sip_nat_hook_alloc()
static void* sip_nat_hook_alloc (const char * name) static
Definition at line 1283 of file pjsip_configuration.c.
References ast_sorcery_generic_alloc(), and NULL.
Referenced by ast_res_pjsip_initialize_configuration().
 {
    return ast_sorcery_generic_alloc(sizeof(struct ast_sip_nat_hook), NULL);
 }
sip_sorcery_object_ami_set_type_name()
static void sip_sorcery_object_ami_set_type_name (const void * obj, struct ast_str ** buf) static
Definition at line 1601 of file pjsip_configuration.c.
References ast_sorcery_object_get_id(), ast_sorcery_object_get_type(), and ast_str_append().
Referenced by ast_sip_sorcery_object_to_ami(), and format_ami_endpoints().
 {
    ast_str_append(buf, 0, "ObjectType: %s\r\n",
              ast_sorcery_object_get_type(obj));
    ast_str_append(buf, 0, "ObjectName: %s\r\n",
              ast_sorcery_object_get_id(obj));
 }
subscription_configuration_destroy()
static void subscription_configuration_destroy (struct ast_sip_endpoint_subscription_configuration * subscription) static
Definition at line 2249 of file pjsip_configuration.c.
References ast_free, ast_string_field_free_memory, ast_sip_endpoint_subscription_configuration::mwi, and ast_sip_mwi_configuration::voicemail_extension.
Referenced by endpoint_destructor().
 {
    ast_string_field_free_memory(&subscription->mwi);
    ast_free(subscription->mwi.voicemail_extension);
 }
t38udptl_ec_handler()
static int t38udptl_ec_handler (const struct aco_option * opt, struct ast_variable * var, void * obj) static
Definition at line 916 of file pjsip_configuration.c.
References sip_persistent_endpoint::endpoint, ast_sip_t38_configuration::error_correction, ast_sip_endpoint::media, ast_sip_endpoint_media_configuration::t38, UDPTL_ERROR_CORRECTION_FEC, UDPTL_ERROR_CORRECTION_NONE, UDPTL_ERROR_CORRECTION_REDUNDANCY, and ast_variable::value.
Referenced by ast_res_pjsip_initialize_configuration().
 {
    struct ast_sip_endpoint *endpoint = obj;
    if (!strcmp(var->value, "none")) {
       endpoint->media.t38.error_correction = UDPTL_ERROR_CORRECTION_NONE;
    } else if (!strcmp(var->value, "fec")) {
       endpoint->media.t38.error_correction = UDPTL_ERROR_CORRECTION_FEC;
    } else if (!strcmp(var->value, "redundancy")) {
       endpoint->media.t38.error_correction = UDPTL_ERROR_CORRECTION_REDUNDANCY;
    } else {
       return -1;
    }
    return 0;
 }
t38udptl_ec_to_str()
static int t38udptl_ec_to_str (const void * obj, const intptr_t * args, char ** buf) static
Definition at line 940 of file pjsip_configuration.c.
References ARRAY_IN_BOUNDS, ast_strdup, ast_t38_ec_modes_map, sip_persistent_endpoint::endpoint, ast_sip_t38_configuration::error_correction, ast_sip_endpoint::media, and ast_sip_endpoint_media_configuration::t38.
Referenced by ast_res_pjsip_initialize_configuration().
 {
    const struct ast_sip_endpoint *endpoint = obj;
    if (ARRAY_IN_BOUNDS(endpoint->media.t38.error_correction, ast_t38_ec_modes_map)) {
       *buf = ast_strdup(ast_t38_ec_modes_map[
                  endpoint->media.t38.error_correction]);
    }
    return 0;
 }
timers_handler()
static int timers_handler (const struct aco_option * opt, struct ast_variable * var, void * obj) static
Definition at line 209 of file pjsip_configuration.c.
References ast_false(), ast_true(), sip_persistent_endpoint::endpoint, ast_sip_endpoint::extensions, ast_sip_endpoint_extensions::flags, and ast_variable::value.
Referenced by ast_res_pjsip_initialize_configuration().
 {
    struct ast_sip_endpoint *endpoint = obj;
    /* clear all */
    endpoint->extensions.flags &= ~(PJSIP_INV_SUPPORT_TIMER | PJSIP_INV_REQUIRE_TIMER
                | PJSIP_INV_ALWAYS_USE_TIMER);
    /* set only the specified flag and let pjsip normalize if needed */
    if (ast_true(var->value)) {
       endpoint->extensions.flags |= PJSIP_INV_SUPPORT_TIMER;
    } else if (!strcasecmp(var->value, "required")) {
       endpoint->extensions.flags |= PJSIP_INV_REQUIRE_TIMER;
    } else if (!strcasecmp(var->value, "always") || !strcasecmp(var->value, "forced")) {
       endpoint->extensions.flags |= PJSIP_INV_ALWAYS_USE_TIMER;
    } else if (!ast_false(var->value)) {
       return -1;
    }
    return 0;
 }
timers_to_str()
static int timers_to_str (const void * obj, const intptr_t * args, char ** buf) static
Definition at line 231 of file pjsip_configuration.c.
References ast_strdup, sip_persistent_endpoint::endpoint, ast_sip_endpoint::extensions, and ast_sip_endpoint_extensions::flags.
Referenced by ast_res_pjsip_initialize_configuration().
 {
    const struct ast_sip_endpoint *endpoint = obj;
    if (endpoint->extensions.flags & PJSIP_INV_ALWAYS_USE_TIMER) {
       *buf = "always";
    } else if (endpoint->extensions.flags & PJSIP_INV_REQUIRE_TIMER) {
       *buf = "required";
    } else if (endpoint->extensions.flags & PJSIP_INV_SUPPORT_TIMER) {
       *buf = "yes";
    } else {
       *buf = "no";
    }
    *buf = ast_strdup(*buf);
    return 0;
 }
tos_audio_to_str()
static int tos_audio_to_str (const void * obj, const intptr_t * args, char ** buf) static
Definition at line 975 of file pjsip_configuration.c.
References ast_asprintf, sip_persistent_endpoint::endpoint, ast_sip_endpoint::media, and ast_sip_endpoint_media_configuration::tos_audio.
Referenced by ast_res_pjsip_initialize_configuration().
 {
    const struct ast_sip_endpoint *endpoint = obj;
    if (ast_asprintf(buf, "%u", endpoint->media.tos_audio) == -1) {
       return -1;
    }
    return 0;
 }
tos_handler()
static int tos_handler (const struct aco_option * opt, struct ast_variable * var, void * obj) static
Definition at line 950 of file pjsip_configuration.c.
References ast_assert, ast_log, ast_sorcery_object_get_id(), ast_str2tos(), sip_persistent_endpoint::endpoint, LOG_ERROR, ast_sip_endpoint::media, ast_variable::name, ast_sip_endpoint_media_configuration::tos_audio, ast_sip_endpoint_media_configuration::tos_video, value, and ast_variable::value.
Referenced by ast_res_pjsip_initialize_configuration().
 {
    struct ast_sip_endpoint *endpoint = obj;
    unsigned int value;
    if (ast_str2tos(var->value, &value)) {
       ast_log(LOG_ERROR, "Error configuring endpoint '%s' - Could not "
          "interpret '%s' value '%s'\n",
          ast_sorcery_object_get_id(endpoint), var->name, var->value);
       return -1;
    }
    if (!strcmp(var->name, "tos_audio")) {
       endpoint->media.tos_audio = value;
    } else if (!strcmp(var->name, "tos_video")) {
       endpoint->media.tos_video = value;
    } else {
       /* If we reach this point, someone called the tos_handler when they shouldn't have. */
       ast_assert(0);
       return -1;
    }
    return 0;
 }
tos_video_to_str()
static int tos_video_to_str (const void * obj, const intptr_t * args, char ** buf) static
Definition at line 985 of file pjsip_configuration.c.
References ast_asprintf, sip_persistent_endpoint::endpoint, ast_sip_endpoint::media, and ast_sip_endpoint_media_configuration::tos_video.
Referenced by ast_res_pjsip_initialize_configuration().
 {
    const struct ast_sip_endpoint *endpoint = obj;
    if (ast_asprintf(buf, "%u", endpoint->media.tos_video) == -1) {
       return -1;
    }
    return 0;
 }
voicemail_extension_handler()
static int voicemail_extension_handler (const struct aco_option * opt, struct ast_variable * var, void * obj) static
Definition at line 1082 of file pjsip_configuration.c.
References ast_free, ast_strdup, sip_persistent_endpoint::endpoint, ast_sip_endpoint_subscription_configuration::mwi, ast_sip_endpoint::subscription, ast_variable::value, and ast_sip_mwi_configuration::voicemail_extension.
Referenced by ast_res_pjsip_initialize_configuration().
 {
    struct ast_sip_endpoint *endpoint = obj;
    ast_free(endpoint->subscription.mwi.voicemail_extension);
    endpoint->subscription.mwi.voicemail_extension = ast_strdup(var->value);
    return endpoint->subscription.mwi.voicemail_extension ? 0 : -1;
 }
voicemail_extension_to_str()
static int voicemail_extension_to_str (const void * obj, const intptr_t * args, char ** buf) static
Definition at line 1092 of file pjsip_configuration.c.
References ast_strdup, sip_persistent_endpoint::endpoint, ast_sip_endpoint_subscription_configuration::mwi, ast_sip_endpoint::subscription, and ast_sip_mwi_configuration::voicemail_extension.
Referenced by ast_res_pjsip_initialize_configuration().
 {
    const struct ast_sip_endpoint *endpoint = obj;
    *buf = ast_strdup(endpoint->subscription.mwi.voicemail_extension);
    return 0;
 }
Variable Documentation
acl_change_sub
struct stasis_subscription* acl_change_sub static
Definition at line 54 of file pjsip_configuration.c.
ast_rtp_dtls_fingerprint_map
const char* ast_rtp_dtls_fingerprint_map[] static
Initial value:
= {
   [AST_RTP_DTLS_HASH_SHA256] = "SHA-256",
   [AST_RTP_DTLS_HASH_SHA1] = "SHA-1",
}
Definition at line 902 of file pjsip_configuration.c.
Referenced by dtlsfingerprint_to_str().
ast_rtp_dtls_setup_map
const char* ast_rtp_dtls_setup_map[] static
Definition at line 886 of file pjsip_configuration.c.
Referenced by dtlssetup_to_str().
ast_t38_ec_modes_map
const char* ast_t38_ec_modes_map[] static
Initial value:
= {
   [UDPTL_ERROR_CORRECTION_NONE] = "none",
   [UDPTL_ERROR_CORRECTION_FEC] = "fec",
   [UDPTL_ERROR_CORRECTION_REDUNDANCY] = "redundancy"
}
Definition at line 934 of file pjsip_configuration.c.
Referenced by t38udptl_ec_to_str().
channel_formatter
struct ast_sip_cli_formatter_entry* channel_formatter
Definition at line 1952 of file pjsip_configuration.c.
cli_commands
struct ast_cli_entry cli_commands[] static
Definition at line 1935 of file pjsip_configuration.c.
direct_media_glare_mitigation_map
const char* direct_media_glare_mitigation_map[] static
Initial value:
= {
   [AST_SIP_DIRECT_MEDIA_GLARE_MITIGATION_NONE] = "none",
   [AST_SIP_DIRECT_MEDIA_GLARE_MITIGATION_OUTGOING] = "outgoing",
   [AST_SIP_DIRECT_MEDIA_GLARE_MITIGATION_INCOMING] = "incoming"
}
Definition at line 576 of file pjsip_configuration.c.
Referenced by direct_media_glare_mitigation_to_str().
endpoint_formatter
struct ast_sip_cli_formatter_entry* endpoint_formatter
Definition at line 1953 of file pjsip_configuration.c.
endpoint_observers
const struct ast_sorcery_observer endpoint_observers static
Initial value:
= {
   .deleted = endpoint_deleted_observer,
}
Definition at line 83 of file pjsip_configuration.c.
id_configuration_refresh_methods
const char* id_configuration_refresh_methods[] static
Initial value:
= {
   [AST_SIP_SESSION_REFRESH_METHOD_INVITE] = "invite",
   [AST_SIP_SESSION_REFRESH_METHOD_UPDATE] = "update"
}
Definition at line 520 of file pjsip_configuration.c.
Referenced by connected_line_method_to_str(), and direct_media_method_to_str().
media_encryption_map
const char* media_encryption_map[] static
Definition at line 703 of file pjsip_configuration.c.
Referenced by media_encryption_to_str().
persistent_endpoints
struct ao2_container* persistent_endpoints static
Container for persistent endpoint information.
Definition at line 50 of file pjsip_configuration.c.
sip_sorcery
struct ast_sorcery* sip_sorcery static
Definition at line 52 of file pjsip_configuration.c.
Referenced by ast_sip_get_sorcery().