Asterisk - The Open Source Telephony Project: res_pjsip_one_touch_record_info.c File Reference
res_pjsip_one_touch_record_info.c File Reference
#include "asterisk.h"
#include <pjsip.h>
#include <pjsip_ua.h>
#include "asterisk/features.h"
#include "asterisk/res_pjsip.h"
#include "asterisk/res_pjsip_session.h"
#include "asterisk/module.h"
#include "asterisk/features_config.h"
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int handle_incoming_request (struct ast_sip_session *session, struct pjsip_rx_data *rdata)
static int load_module (void)
static void send_response (struct ast_sip_session *session, int code, struct pjsip_rx_data *rdata)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "PJSIP INFO One Touch Recording Support" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_APP_DEPEND, .requires = "res_pjsip,res_pjsip_session", }
static const struct ast_module_info * ast_module_info = &__mod_info
static struct ast_sip_session_supplement info_supplement
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 128 of file res_pjsip_one_touch_record_info.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 128 of file res_pjsip_one_touch_record_info.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 128 of file res_pjsip_one_touch_record_info.c.
handle_incoming_request()
static int handle_incoming_request (struct ast_sip_session * session, struct pjsip_rx_data * rdata) static
Definition at line 48 of file res_pjsip_one_touch_record_info.c.
References ast_channel_lock, ast_channel_unlock, AST_FEATURE_MAX_LEN, AST_FRAME_DTMF, ast_get_feature(), ast_queue_frame(), ast_strlen_zero, ast_sip_session::channel, digit, ast_sip_info_recording_configuration::enabled, ast_sip_session::endpoint, ast_sip_endpoint::info, NULL, ast_sip_info_recording_configuration::offfeature, ast_sip_info_recording_configuration::onfeature, ast_sip_endpoint_info_configuration::recording, and send_response().
 {
    static const pj_str_t rec_str = { "Record", 6 };
    pjsip_generic_string_hdr *record;
    int feature_res;
    char feature_code[AST_FEATURE_MAX_LEN];
    const char *feature;
    char *digit;
    record = pjsip_msg_find_hdr_by_name(rdata->msg_info.msg, &rec_str, NULL);
    /* If we don't have Record header, we have nothing to do */
    if (!record) {
       return 0;
    }
    if (!pj_stricmp2(&record->hvalue, "on")) {
       feature = session->endpoint->info.recording.onfeature;
    } else if (!pj_stricmp2(&record->hvalue, "off")) {
       feature = session->endpoint->info.recording.offfeature;
    } else {
       /* Don't send response because another module may handle this */
       return 0;
    }
    if (!session->channel) {
       send_response(session, 481, rdata);
       return 1;
    }
    /* Is this endpoint configured with One Touch Recording? */
    if (!session->endpoint->info.recording.enabled || ast_strlen_zero(feature)) {
       send_response(session, 403, rdata);
       return 1;
    }
    ast_channel_lock(session->channel);
    feature_res = ast_get_feature(session->channel, feature, feature_code, sizeof(feature_code));
    ast_channel_unlock(session->channel);
    if (feature_res || ast_strlen_zero(feature_code)) {
       send_response(session, 403, rdata);
       return 1;
    }
    for (digit = feature_code; *digit; ++digit) {
       struct ast_frame f = { AST_FRAME_DTMF, .subclass.integer = *digit, .len = 100 };
       ast_queue_frame(session->channel, &f);
    }
    send_response(session, 200, rdata);
    return 1;
 }
load_module()
static int load_module (void) static
Definition at line 109 of file res_pjsip_one_touch_record_info.c.
References AST_MODULE_LOAD_SUCCESS, and ast_sip_session_register_supplement.
Referenced by unload_module().
 {
    ast_sip_session_register_supplement(&info_supplement);
    return AST_MODULE_LOAD_SUCCESS;
 }
send_response()
static void send_response (struct ast_sip_session * session, int code, struct pjsip_rx_data * rdata) static
Definition at line 37 of file res_pjsip_one_touch_record_info.c.
References ast_sip_session::inv_session, and NULL.
Referenced by handle_incoming_request().
 {
    pjsip_tx_data *tdata;
    if (pjsip_dlg_create_response(session->inv_session->dlg, rdata, code, NULL, &tdata) == PJ_SUCCESS) {
       struct pjsip_transaction *tsx = pjsip_rdata_get_tsx(rdata);
       pjsip_dlg_send_response(session->inv_session->dlg, tsx, tdata);
    }
 }
unload_module()
static int unload_module (void) static
Definition at line 116 of file res_pjsip_one_touch_record_info.c.
References AST_MODFLAG_LOAD_ORDER, AST_MODPRI_APP_DEPEND, AST_MODULE_INFO(), AST_MODULE_SUPPORT_CORE, ast_sip_session_unregister_supplement(), ASTERISK_GPL_KEY, and load_module().
 {
    ast_sip_session_unregister_supplement(&info_supplement);
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "PJSIP INFO One Touch Recording Support" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_APP_DEPEND, .requires = "res_pjsip,res_pjsip_session", } static
Definition at line 128 of file res_pjsip_one_touch_record_info.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 128 of file res_pjsip_one_touch_record_info.c.
info_supplement
struct ast_sip_session_supplement info_supplement static
Initial value:
= {
   .method = "INFO",
   .priority = AST_SIP_SUPPLEMENT_PRIORITY_FIRST,
   .incoming_request = handle_incoming_request,
}
Definition at line 103 of file res_pjsip_one_touch_record_info.c.