Asterisk - The Open Source Telephony Project: func_evalexten.c File Reference
func_evalexten.c File Reference
Module: Dial plan functions
Dialplan extension evaluation function.
#include "asterisk.h"
#include "asterisk/module.h"
#include "asterisk/channel.h"
#include "asterisk/pbx.h"
#include "asterisk/utils.h"
#include "asterisk/app.h"
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int eval_exten_read (struct ast_channel *chan, const char *cmd, char *data, char *buf, size_t len)
static int get_extension_data (char *name, int namesize, struct ast_channel *c, const char *context, const char *exten, int priority)
static int load_module (void)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Extension evaluation function" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, }
static const struct ast_module_info * ast_module_info = &__mod_info
static struct ast_custom_function eval_exten_function
Detailed Description
Dialplan extension evaluation function.
Author
Naveen Albert aster.nosp@m.isk@.nosp@m.phrea.nosp@m.knet.nosp@m..org
Definition in file func_evalexten.c.
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 200 of file func_evalexten.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 200 of file func_evalexten.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 200 of file func_evalexten.c.
eval_exten_read()
static int eval_exten_read (struct ast_channel * chan, const char * cmd, char * data, char * buf, size_t len) static
Definition at line 110 of file func_evalexten.c.
References ast_channel_caller(), ast_channel_context(), ast_channel_context_set(), ast_channel_exten(), ast_channel_exten_set(), ast_channel_lock, ast_channel_priority(), ast_channel_priority_set(), ast_channel_unlock, ast_debug, ast_findlabel_extension(), ast_log, ast_strdupa, ast_strlen_zero, context, exten, get_extension_data(), len(), LOG_WARNING, NULL, parse(), pbx_substitute_variables_helper(), S_COR, and strsep().
 {
    char *exten, *pri, *context, *parse;
    int ipri;
    const char *realcontext, *realexten;
    int realpriority;
    char tmpbuf[len];
    if (ast_strlen_zero(data)) {
       ast_log(LOG_WARNING, "The EVAL_EXTEN function requires an extension\n");
       return -1;
    }
    parse = ast_strdupa(data);
    /* Split context,exten,pri */
    context = strsep(&parse, ",");
    exten = strsep(&parse, ",");
    pri = strsep(&parse, ",");
    if (!exten) {
       /* Only a priority in this one */
       pri = context;
       exten = NULL;
       context = NULL;
    } else if (!pri) {
       /* Only an extension and priority in this one */
       pri = exten;
       exten = context;
       context = NULL;
    }
    ast_debug(1, "Context, extension, priority: %s, %s, %s\n", context, exten, pri);
    if (sscanf(pri, "%30d", &ipri) != 1) {
       ipri = ast_findlabel_extension(chan, context ? context : ast_channel_context(chan),
          exten ? exten : ast_channel_exten(chan), pri,
          S_COR(ast_channel_caller(chan)->id.number.valid, ast_channel_caller(chan)->id.number.str, NULL));
       if (ipri < 1) {
          ast_log(LOG_WARNING, "Priority '%s' must be a number > 0, or valid label\n", pri);
          return -1;
       }
    }
    ast_debug(1, "Context, extension, priority: %s, %s, %d\n", context, exten, ipri);
    ast_channel_lock(chan);
    realcontext = ast_strdupa(ast_channel_context(chan));
    realexten = ast_strdupa(ast_channel_exten(chan));
    realpriority = ast_channel_priority(chan);
    ast_channel_unlock(chan);
    if (ast_strlen_zero(exten)) {
       exten = ast_strdupa(realexten);
    }
    if (ast_strlen_zero(context)) {
       context = ast_strdupa(realcontext);
    }
    if (get_extension_data(tmpbuf, len, chan, context, exten, ipri)) {
       return -1; /* EVAL_EXTEN failed */
    }
    /* Substitute variables now, using the location of the evaluated extension */
    /* strdupa required or we'll just overwrite what we read when we set these */
    ast_channel_lock(chan);
    ast_channel_context_set(chan, context);
    ast_channel_exten_set(chan, exten);
    ast_channel_priority_set(chan, ipri);
    ast_channel_unlock(chan);
    pbx_substitute_variables_helper(chan, tmpbuf, buf, len);
    ast_channel_lock(chan);
    ast_channel_context_set(chan, realcontext);
    ast_channel_exten_set(chan, realexten);
    ast_channel_priority_set(chan, realpriority);
    ast_channel_unlock(chan);
    return 0;
 }
get_extension_data()
static int get_extension_data (char * name, int namesize, struct ast_channel * c, const char * context, const char * exten, int priority) static
Definition at line 90 of file func_evalexten.c.
References ast_copy_string(), ast_get_extension_app_data(), ast_rdlock_contexts(), ast_unlock_contexts(), E_MATCH, NULL, pbx_find_extension(), pbx_find_info::stacklen, and tmp().
Referenced by eval_exten_read().
 {
    struct ast_exten *e;
    struct pbx_find_info q = { .stacklen = 0 }; /* the rest is set in pbx_find_context */
    ast_rdlock_contexts();
    e = pbx_find_extension(c, NULL, &q, context, exten, priority, NULL, "", E_MATCH);
    ast_unlock_contexts();
    if (e) {
       if (name) {
          const char *tmp = ast_get_extension_app_data(e);
          if (tmp) {
             ast_copy_string(name, tmp, namesize);
          }
       }
       return 0;
    }
    return -1;
 }
load_module()
static int load_module (void) static
Definition at line 195 of file func_evalexten.c.
References ast_custom_function_register.
 {
    return ast_custom_function_register(&eval_exten_function);
 }
unload_module()
static int unload_module (void) static
Definition at line 190 of file func_evalexten.c.
References ast_custom_function_unregister().
 {
    return ast_custom_function_unregister(&eval_exten_function);
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Extension evaluation function" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, } static
Definition at line 200 of file func_evalexten.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 200 of file func_evalexten.c.
eval_exten_function
struct ast_custom_function eval_exten_function static
Initial value:
= {
   .name = "EVAL_EXTEN",
   .read = eval_exten_read,
}
Definition at line 185 of file func_evalexten.c.