Asterisk - The Open Source Telephony Project: stored.c File Reference
stored.c File Reference
Stored file operations for Stasis.
#include "asterisk.h"
#include "asterisk/astobj2.h"
#include "asterisk/paths.h"
#include "asterisk/stasis_app_recording.h"
#include <sys/stat.h>
#include <sys/types.h>
#include <unistd.h>
Data Structures
struct match_recording_data
struct stasis_app_stored_recording
Functions
static char * find_recording (const char *dir_name, const char *file)
Finds a recording in the given directory.
static int handle_find_recording (const char *dir_name, const char *filename, void *obj)
static int handle_scan_file (const char *dir_name, const char *filename, void *obj)
static int is_recording (const char *filename)
static struct stasis_app_stored_recording * recording_alloc (void)
Allocate a recording object.
static int recording_sort (const void *obj_left, const void *obj_right, int flags)
static int split_path (const char *path, char **dir, char **file)
Split a path into directory and file, resolving canonical directory.
int stasis_app_stored_recording_copy (struct stasis_app_stored_recording *src_recording, const char *dst, struct stasis_app_stored_recording **dst_recording)
Copy a recording.
int stasis_app_stored_recording_delete (struct stasis_app_stored_recording *recording)
Delete a recording from disk.
struct ao2_container * stasis_app_stored_recording_find_all (void)
Find all stored recordings on disk.
struct stasis_app_stored_recording * stasis_app_stored_recording_find_by_name (const char *name)
Creates a stored recording object, with the given name.
const char * stasis_app_stored_recording_get_extension (struct stasis_app_stored_recording *recording)
Returns the extension for this recording.
const char * stasis_app_stored_recording_get_file (struct stasis_app_stored_recording *recording)
Returns the filename for this recording, for use with streamfile.
const char * stasis_app_stored_recording_get_filename (struct stasis_app_stored_recording *recording)
Returns the full filename, with extension, for this recording.
struct ast_json * stasis_app_stored_recording_to_json (struct stasis_app_stored_recording *recording)
Convert stored recording info to JSON.
static void stored_recording_dtor (void *obj)
Detailed Description
Stored file operations for Stasis.
Author
David M. Lee, II dlee@.nosp@m.digi.nosp@m.um.co.nosp@m.m
Definition in file stored.c.
Function Documentation
find_recording()
static char* find_recording (const char * dir_name, const char * file) static
Finds a recording in the given directory.
This function searchs for a file with the given file name, with a registered format that matches its extension.
Parameters
dir_name Directory to search (absolute path).
file File name, without extension.
Returns
Absolute path of the recording file.
NULL if recording is not found.
Definition at line 184 of file stored.c.
References ast_file_read_dir, stasis_app_stored_recording::file, match_recording_data::file, match_recording_data::file_with_ext, handle_find_recording(), and NULL.
Referenced by stasis_app_stored_recording_find_by_name().
 {
    struct match_recording_data data = {
       .file = file,
       .file_with_ext = NULL
    };
    ast_file_read_dir(dir_name, handle_find_recording, &data);
    /* Note, string potentially allocated in handle_file_recording */
    return data.file_with_ext;
handle_find_recording()
static int handle_find_recording (const char * dir_name, const char * filename, void * obj) static
Definition at line 156 of file stored.c.
References ast_asprintf, match_recording_data::file, match_recording_data::file_with_ext, and is_recording().
Referenced by find_recording().
 {
    struct match_recording_data *data = obj;
    int num;
    /* If not a recording or the names do not match the keep searching */
    if (!(num = is_recording(filename)) || strncmp(data->file, filename, num)) {
       return 0;
    }
    if (ast_asprintf(&data->file_with_ext, "%s/%s", dir_name, filename) < 0) {
       return -1;
    }
    return 1;
handle_scan_file()
static int handle_scan_file (const char * dir_name, const char * filename, void * obj) static
Definition at line 249 of file stored.c.
References ao2_link, ao2_ref, ast_asprintf, ast_config_AST_RECORDING_DIR, ast_free, ast_string_field_set, stasis_app_stored_recording::file, stasis_app_stored_recording::file_with_ext, stasis_app_stored_recording::format, is_recording(), stasis_app_stored_recording::name, recording_alloc(), and recordings.
Referenced by stasis_app_stored_recording_find_all().
 {
    struct ao2_container *recordings = obj;
    struct stasis_app_stored_recording *recording;
    char *dot, *filepath;
    /* Skip if it is not a recording */
    if (!is_recording(filename)) {
       return 0;
    }
    if (ast_asprintf(&filepath, "%s/%s", dir_name, filename) < 0) {
       return -1;
    }
    recording = recording_alloc();
    if (!recording) {
       ast_free(filepath);
       return -1;
    }
    ast_string_field_set(recording, file_with_ext, filepath);
    /* Build file and format from full path */
    ast_string_field_set(recording, file, filepath);
    ast_free(filepath);
    dot = strrchr(recording->file, '.');
    *dot = '\0';
    recording->format = dot + 1;
    /* Removed the recording dir from the file for the name. */
    ast_string_field_set(recording, name,
       recording->file + strlen(ast_config_AST_RECORDING_DIR) + 1);
    /* Add it to the recordings container */
    ao2_link(recordings, recording);
    ao2_ref(recording, -1);
is_recording()
static int is_recording (const char * filename) static
Definition at line 135 of file stored.c.
References ast_debug, ast_get_format_for_file_ext(), and ext.
Referenced by handle_find_recording(), and handle_scan_file().
 {
    const char *ext = strrchr(filename, '.');
    if (!ext) {
       /* No file extension; not us */
       return 0;
    }
    ++ext;
    if (!ast_get_format_for_file_ext(ext)) {
       ast_debug(5, "Recording %s: unrecognized format %s\n",
          filename, ext);
       /* Keep looking */
       return 0;
    }
    /* Return the index to the .ext */
    return ext - filename - 1;
recording_alloc()
static struct stasis_app_stored_recording* recording_alloc (void) static
Allocate a recording object.
Definition at line 200 of file stored.c.
References ao2_alloc, ao2_cleanup, ao2_ref, ast_string_field_init, NULL, RAII_VAR, and stored_recording_dtor().
Referenced by handle_scan_file(), and stasis_app_stored_recording_find_by_name().
 {
    RAII_VAR(struct stasis_app_stored_recording *, recording, NULL,
       ao2_cleanup);
    int res;
    recording = ao2_alloc(sizeof(*recording), stored_recording_dtor);
    if (!recording) {
       return NULL;
    }
    res = ast_string_field_init(recording, 255);
    if (res != 0) {
       return NULL;
    }
    ao2_ref(recording, +1);
recording_sort()
static int recording_sort (const void * obj_left, const void * obj_right, int flags) static
< Deprecated name
< Deprecated name
< Deprecated name
< Deprecated name
< Deprecated name
< Deprecated name
Definition at line 219 of file stored.c.
References ast_assert, stasis_app_stored_recording::name, OBJ_KEY, OBJ_PARTIAL_KEY, and OBJ_POINTER.
Referenced by stasis_app_stored_recording_find_all().
 {
    const struct stasis_app_stored_recording *object_left = obj_left;
    const struct stasis_app_stored_recording *object_right = obj_right;
    const char *right_key = obj_right;
    int cmp;
    switch (flags & (OBJ_POINTER | OBJ_KEY | OBJ_PARTIAL_KEY)) {
    case OBJ_POINTER:
       right_key = object_right->name;
       /* Fall through */
    case OBJ_KEY:
       cmp = strcmp(object_left->name, right_key);
       break;
    case OBJ_PARTIAL_KEY:
       /*
        * We could also use a partial key struct containing a length
        * so strlen() does not get called for every comparison instead.
        */
       cmp = strncmp(object_left->name, right_key, strlen(right_key));
       break;
    default:
       /* Sort can only work on something with a full or partial key. */
       ast_assert(0);
       cmp = 0;
       break;
    }
split_path()
static int split_path (const char * path, char ** dir, char ** file) static
Split a path into directory and file, resolving canonical directory.
The path is resolved relative to the recording directory. Both dir and file are allocated strings, which you must ast_free().
Parameters
path Path to split.
[out] dir Output parameter for directory portion.
[out] fail Output parameter for the file portion.
Returns
0 on success.
Non-zero on error.
Definition at line 92 of file stored.c.
References ast_asprintf, ast_config_AST_RECORDING_DIR, ast_free, ast_std_free(), ast_strdup, NULL, and RAII_VAR.
Referenced by stasis_app_stored_recording_find_by_name().
 {
    RAII_VAR(char *, relative_dir, NULL, ast_free);
    RAII_VAR(char *, absolute_dir, NULL, ast_free);
    RAII_VAR(char *, real_dir, NULL, ast_std_free);
    char *last_slash;
    const char *file_portion;
    relative_dir = ast_strdup(path);
    if (!relative_dir) {
       return -1;
    }
    last_slash = strrchr(relative_dir, '/');
    if (last_slash) {
       *last_slash = '\0';
       file_portion = last_slash + 1;
       ast_asprintf(&absolute_dir, "%s/%s",
          ast_config_AST_RECORDING_DIR, relative_dir);
    } else {
       /* There is no directory portion */
       file_portion = path;
       *relative_dir = '\0';
       absolute_dir = ast_strdup(ast_config_AST_RECORDING_DIR);
    }
    if (!absolute_dir) {
       return -1;
    }
    real_dir = realpath(absolute_dir, NULL);
    if (!real_dir) {
       return -1;
    }
    *dir = ast_strdup(real_dir); /* Dupe so we can ast_free() */
    *file = ast_strdup(file_portion);
    return (*dir && *file) ? 0 : -1;
stasis_app_stored_recording_copy()
int stasis_app_stored_recording_copy (struct stasis_app_stored_recording * src_recording, const char * dst, struct stasis_app_stored_recording ** dst_recording)
Copy a recording.
Parameters
src_recording The recording to copy
dst The destination of the recording to make
dst_recording If successful, the stored recording created as a result of the copy
Return values
0 on success
Non-zero on error
Definition at line 389 of file stored.c.
Referenced by ast_ari_recordings_copy_stored().
 {
    RAII_VAR(char *, full_path, NULL, ast_free);
    char *dst_file = ast_strdupa(dst);
    char *format;
    char *last_slash;
    int res;
    /* Drop the extension if specified, core will do this for us */
    format = strrchr(dst_file, '.');
    if (format) {
       *format = '\0';
    }
    /* See if any intermediary directories need to be made */
    last_slash = strrchr(dst_file, '/');
    if (last_slash) {
       RAII_VAR(char *, tmp_path, NULL, ast_free);
       *last_slash = '\0';
       if (ast_asprintf(&tmp_path, "%s/%s", ast_config_AST_RECORDING_DIR, dst_file) < 0) {
          return -1;
       }
       if (ast_safe_mkdir(ast_config_AST_RECORDING_DIR,
             tmp_path, 0777) != 0) {
          /* errno set by ast_mkdir */
          return -1;
       }
       *last_slash = '/';
       if (ast_asprintf(&full_path, "%s/%s", ast_config_AST_RECORDING_DIR, dst_file) < 0) {
          return -1;
       }
    } else {
       /* There is no directory portion */
       if (ast_asprintf(&full_path, "%s/%s", ast_config_AST_RECORDING_DIR, dst_file) < 0) {
          return -1;
       }
    }
    ast_verb(4, "Copying recording %s to %s (format %s)\n", src_recording->file,
       full_path, src_recording->format);
    res = ast_filecopy(src_recording->file, full_path, src_recording->format);
    if (!res) {
stasis_app_stored_recording_delete()
int stasis_app_stored_recording_delete (struct stasis_app_stored_recording * recording)
Delete a recording from disk.
Parameters
recording Recording to delete.
Returns
0 on success.
Non-zero on error.
Definition at line 439 of file stored.c.
Referenced by ast_ari_recordings_delete_stored().
 {
stasis_app_stored_recording_find_all()
struct ao2_container* stasis_app_stored_recording_find_all (void)
Find all stored recordings on disk.
Returns
Container of stasis_app_stored_recording objects.
NULL on error.
Definition at line 290 of file stored.c.
References AO2_ALLOC_OPT_LOCK_NOLOCK, AO2_CONTAINER_ALLOC_OPT_DUPS_REPLACE, ao2_container_alloc_rbtree, ao2_ref, ast_config_AST_RECORDING_DIR, ast_file_read_dirs(), handle_scan_file(), NULL, recording_sort(), and recordings.
Referenced by ast_ari_recordings_list_stored().
 {
    struct ao2_container *recordings;
    int res;
    recordings = ao2_container_alloc_rbtree(AO2_ALLOC_OPT_LOCK_NOLOCK,
       AO2_CONTAINER_ALLOC_OPT_DUPS_REPLACE, recording_sort, NULL);
    if (!recordings) {
       return NULL;
    }
    res = ast_file_read_dirs(ast_config_AST_RECORDING_DIR,
              handle_scan_file, recordings, -1);
    if (res) {
       ao2_ref(recordings, -1);
       return NULL;
stasis_app_stored_recording_find_by_name()
struct stasis_app_stored_recording* stasis_app_stored_recording_find_by_name (const char * name)
Creates a stored recording object, with the given name.
Parameters
name Name of the recording.
Returns
New recording object.
NULL if recording is not found. errno is set to indicate why
ENOMEM - out of memeory
EACCES - file permissions (or recording is outside the config dir)
Any of the error codes for stat(), opendir(), readdir()
Definition at line 310 of file stored.c.
References ao2_cleanup, ast_begins_with(), ast_config_AST_RECORDING_DIR, ast_free, ast_log, ast_std_free(), ast_string_field_build, ast_string_field_set, errno, stasis_app_stored_recording::file, stasis_app_stored_recording::file_with_ext, find_recording(), LOG_WARNING, NULL, RAII_VAR, recording_alloc(), and split_path().
Referenced by ast_ari_recordings_copy_stored(), ast_ari_recordings_delete_stored(), ast_ari_recordings_get_stored(), ast_ari_recordings_get_stored_file(), and play_on_channel().
 {
    RAII_VAR(struct stasis_app_stored_recording *, recording, NULL,
       ao2_cleanup);
    RAII_VAR(char *, dir, NULL, ast_free);
    RAII_VAR(char *, file, NULL, ast_free);
    RAII_VAR(char *, file_with_ext, NULL, ast_free);
    int res;
    struct stat file_stat;
    int prefix_len = strlen(ast_config_AST_RECORDING_DIR);
    errno = 0;
    if (!name) {
       errno = EINVAL;
       return NULL;
    }
    recording = recording_alloc();
    if (!recording) {
       return NULL;
    }
    res = split_path(name, &dir, &file);
    if (res != 0) {
       return NULL;
    }
    ast_string_field_build(recording, file, "%s/%s", dir, file);
    if (!ast_begins_with(dir, ast_config_AST_RECORDING_DIR)) {
       /* It's possible that one or more component of the recording path is
        * a symbolic link, this would prevent dir from ever matching. */
       char *real_basedir = realpath(ast_config_AST_RECORDING_DIR, NULL);
       if (!real_basedir || !ast_begins_with(dir, real_basedir)) {
          /* Attempt to escape the recording directory */
          ast_log(LOG_WARNING, "Attempt to access invalid recording directory %s\n",
             dir);
          ast_std_free(real_basedir);
          errno = EACCES;
          return NULL;
       }
       prefix_len = strlen(real_basedir);
       ast_std_free(real_basedir);
    }
    /* The actual name of the recording is file with the config dir
     * prefix removed.
     */
    ast_string_field_set(recording, name, recording->file + prefix_len + 1);
    file_with_ext = find_recording(dir, file);
    if (!file_with_ext) {
       return NULL;
    }
    ast_string_field_set(recording, file_with_ext, file_with_ext);
    recording->format = strrchr(recording->file_with_ext, '.');
    if (!recording->format) {
       return NULL;
    }
    ++(recording->format);
    res = stat(file_with_ext, &file_stat);
    if (res != 0) {
       return NULL;
    }
    if (!S_ISREG(file_stat.st_mode)) {
       /* Let's not play if it's not a regular file */
       errno = EACCES;
       return NULL;
stasis_app_stored_recording_get_extension()
const char* stasis_app_stored_recording_get_extension (struct stasis_app_stored_recording * recording)
Returns the extension for this recording.
Since
14.0.0
Parameters
recording Recording to query.
Returns
The extension associated with this recording.
NULL on error
Definition at line 71 of file stored.c.
References stasis_app_stored_recording::format, and NULL.
Referenced by ast_ari_recordings_get_stored_file().
 {
    if (!recording) {
       return NULL;
    }
    return recording->format;
 }
stasis_app_stored_recording_get_file()
const char* stasis_app_stored_recording_get_file (struct stasis_app_stored_recording * recording)
Returns the filename for this recording, for use with streamfile.
The returned string will be valid until the recording object is freed.
Parameters
recording Recording to query.
Returns
Absolute path to the recording file, without the extension.
NULL on error.
Definition at line 53 of file stored.c.
References stasis_app_stored_recording::file, and NULL.
Referenced by play_on_channel().
 {
    if (!recording) {
       return NULL;
    }
    return recording->file;
 }
stasis_app_stored_recording_get_filename()
const char* stasis_app_stored_recording_get_filename (struct stasis_app_stored_recording * recording)
Returns the full filename, with extension, for this recording.
Since
14.0.0
Parameters
recording Recording to query.
Returns
Absolute path to the recording file, with the extension.
NULL on error
Definition at line 62 of file stored.c.
References stasis_app_stored_recording::file_with_ext, and NULL.
Referenced by ast_ari_recordings_get_stored_file().
 {
    if (!recording) {
       return NULL;
    }
    return recording->file_with_ext;
 }
stasis_app_stored_recording_to_json()
struct ast_json* stasis_app_stored_recording_to_json (struct stasis_app_stored_recording * recording)
Convert stored recording info to JSON.
Parameters
recording Recording to convert.
Returns
JSON representation.
NULL on error.
Definition at line 446 of file stored.c.
References ast_json_pack(), stasis_app_stored_recording::file_with_ext, stasis_app_stored_recording::format, stasis_app_stored_recording::name, and NULL.
Referenced by ast_ari_recordings_copy_stored(), ast_ari_recordings_get_stored(), and ast_ari_recordings_list_stored().
 {
    /* Path was validated when the recording object was created */
    return unlink(recording->file_with_ext);
 }
 struct ast_json *stasis_app_stored_recording_to_json(
    struct stasis_app_stored_recording *recording)
 {
    if (!recording) {
       return NULL;
    }
stored_recording_dtor()
static void stored_recording_dtor (void * obj) static
Definition at line 46 of file stored.c.
References ast_string_field_free_memory.
Referenced by recording_alloc().
 {
    struct stasis_app_stored_recording *recording = obj;
    ast_string_field_free_memory(recording);
 }