Asterisk - The Open Source Telephony Project: rec_seq.c File Reference
rec_seq.c File Reference
#include <sys/types.h>
#include <errno.h>
#include <limits.h>
#include <stdio.h>
#include <string.h>
#include "../include/db.h"
#include "recno.h"
Functions
int __rec_seq (DB *dbp, DBT *key, DBT *data, u_int flags) const
Function Documentation
__rec_seq()
int __rec_seq (DB * dbp, DBT * key, DBT * data, u_int flags) const
Definition at line 61 of file rec_seq.c.
References __rec_ret(), __rec_search(), B_DB_LOCK, _btree::bt_cursor, _btree::bt_mp, _btree::bt_nrecs, _btree::bt_pinned, CURS_INIT, DBT::data, errno, F_ISSET, F_SET, __db::internal, MAX_REC_NUMBER, mpool_put(), NULL, _epg::page, R_CURSOR, R_EOF, R_FIRST, R_INMEM, R_LAST, R_NEXT, R_PREV, _cursor::rcursor, RET_ERROR, RET_SPECIAL, RET_SUCCESS, SEARCH, and status.
Referenced by __rec_open().
 {
    BTREE *t;
    EPG *e;
    recno_t nrec;
    int status;
    t = dbp->internal;
    /* Toss any page pinned across calls. */
    if (t->bt_pinned != NULL) {
       mpool_put(t->bt_mp, t->bt_pinned, 0);
       t->bt_pinned = NULL;
    }
    switch(flags) {
    case R_CURSOR:
       if ((nrec = *(recno_t *)key->data) == 0)
          goto einval;
       break;
    case R_NEXT:
       if (F_ISSET(&t->bt_cursor, CURS_INIT)) {
          nrec = t->bt_cursor.rcursor + 1;
          break;
       }
       /* FALLTHROUGH */
    case R_FIRST:
       nrec = 1;
       break;
    case R_PREV:
       if (F_ISSET(&t->bt_cursor, CURS_INIT)) {
          if ((nrec = t->bt_cursor.rcursor - 1) == 0)
             return (RET_SPECIAL);
          break;
       }
       /* FALLTHROUGH */
    case R_LAST:
       if (!F_ISSET(t, R_EOF | R_INMEM) &&
           t->bt_irec(t, MAX_REC_NUMBER) == RET_ERROR)
          return (RET_ERROR);
       nrec = t->bt_nrecs;
       break;
    default:
 einval:     errno = EINVAL;
       return (RET_ERROR);
    }
    if (t->bt_nrecs == 0 || nrec > t->bt_nrecs) {
       if (!F_ISSET(t, R_EOF | R_INMEM) &&
           (status = t->bt_irec(t, nrec)) != RET_SUCCESS)
          return (status);
       if (t->bt_nrecs == 0 || nrec > t->bt_nrecs)
          return (RET_SPECIAL);
    }
    if ((e = __rec_search(t, nrec - 1, SEARCH)) == NULL)
       return (RET_ERROR);
    F_SET(&t->bt_cursor, CURS_INIT);
    t->bt_cursor.rcursor = nrec;
    status = __rec_ret(t, e, nrec, key, data);
    if (F_ISSET(t, B_DB_LOCK))
       mpool_put(t->bt_mp, e->page, 0);
    else
       t->bt_pinned = e->page;
    return (status);
 }