Asterisk - The Open Source Telephony Project: app_tonedetect.c File Reference
app_tonedetect.c File Reference
Dial plan applications
Tone detection module.
#include "asterisk.h"
#include <math.h>
#include "asterisk/module.h"
#include "asterisk/frame.h"
#include "asterisk/format_cache.h"
#include "asterisk/channel.h"
#include "asterisk/dsp.h"
#include "asterisk/pbx.h"
#include "asterisk/audiohook.h"
#include "asterisk/app.h"
#include "asterisk/indications.h"
#include "asterisk/conversions.h"
Data Structures
struct detect_information
Enumerations
enum { OPT_ARG_DECIBEL, OPT_ARG_GOTO_RX, OPT_ARG_GOTO_TX, OPT_ARG_ARRAY_SIZE }
enum { OPT_APP_DECIBEL = (1 << 0), OPT_APP_SQUELCH = (1 << 1) }
enum { OPT_APP_ARG_DECIBEL, OPT_APP_ARG_ARRAY_SIZE }
enum td_opts {
OPT_TX = (1 << 1), OPT_RX = (1 << 2), OPT_END_FILTER = (1 << 3), OPT_GOTO_RX = (1 << 4),
OPT_GOTO_TX = (1 << 5), OPT_DECIBEL = (1 << 6), OPT_SQUELCH = (1 << 7)
}
Functions
AST_MODULE_INFO_STANDARD_EXTENDED (ASTERISK_GPL_KEY, "Tone detection module")
static void destroy_callback (void *data)
static int detect_callback (struct ast_audiohook *audiohook, struct ast_channel *chan, struct ast_frame *frame, enum ast_audiohook_direction direction)
static int detect_read (struct ast_channel *chan, const char *cmd, char *data, char *buffer, size_t buflen)
static int detect_write (struct ast_channel *chan, const char *cmd, char *data, const char *value)
static int freq_parser (char *freqs, int *freq1, int *freq2)
static char * goto_parser (struct ast_channel *chan, char *loc)
static int load_module (void)
static int remove_detect (struct ast_channel *chan)
static int unload_module (void)
static int wait_exec (struct ast_channel *chan, const char *data)
Variables
static const struct ast_datastore_info detect_datastore
static struct ast_custom_function detect_function
static const struct ast_app_option td_opts [128] = { [ 'd' ] = { .flag = OPT_DECIBEL , .arg_index = OPT_ARG_DECIBEL + 1 }, [ 'g' ] = { .flag = OPT_GOTO_RX , .arg_index = OPT_ARG_GOTO_RX + 1 }, [ 'h' ] = { .flag = OPT_GOTO_TX , .arg_index = OPT_ARG_GOTO_TX + 1 }, [ 's' ] = { .flag = OPT_SQUELCH }, [ 't' ] = { .flag = OPT_TX }, [ 'r' ] = { .flag = OPT_RX }, [ 'x' ] = { .flag = OPT_END_FILTER }, }
static const struct ast_app_option wait_exec_options [128] = { [ 'd' ] = { .flag = OPT_APP_DECIBEL , .arg_index = OPT_APP_ARG_DECIBEL + 1 }, [ 's' ] = { .flag = OPT_APP_SQUELCH }, }
static char * waitapp = "WaitForTone"
Detailed Description
Tone detection module.
Author
Naveen Albert aster.nosp@m.isk@.nosp@m.phrea.nosp@m.knet.nosp@m..org
Definition in file app_tonedetect.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
OPT_ARG_DECIBEL
OPT_ARG_GOTO_RX
OPT_ARG_GOTO_TX
OPT_ARG_ARRAY_SIZE
Definition at line 183 of file app_tonedetect.c.
      {
    OPT_ARG_DECIBEL,
    OPT_ARG_GOTO_RX,
    OPT_ARG_GOTO_TX,
    /* note: this entry _MUST_ be the last one in the enum */
    OPT_ARG_ARRAY_SIZE,
 };
anonymous enum
anonymous enum
Enumerator
OPT_APP_DECIBEL
OPT_APP_SQUELCH
Definition at line 508 of file app_tonedetect.c.
      {
    OPT_APP_DECIBEL =  (1 << 0),
    OPT_APP_SQUELCH =  (1 << 1),
 };
anonymous enum
anonymous enum
Enumerator
OPT_APP_ARG_DECIBEL
OPT_APP_ARG_ARRAY_SIZE
Definition at line 513 of file app_tonedetect.c.
      {
    OPT_APP_ARG_DECIBEL,
    /* note: this entry _MUST_ be the last one in the enum */
    OPT_APP_ARG_ARRAY_SIZE,
 };
td_opts
enum td_opts
Enumerator
OPT_TX
OPT_RX
OPT_END_FILTER
OPT_GOTO_RX
OPT_GOTO_TX
OPT_DECIBEL
OPT_SQUELCH
Definition at line 173 of file app_tonedetect.c.
              {
    OPT_TX = (1 << 1),
    OPT_RX = (1 << 2),
    OPT_END_FILTER = (1 << 3),
    OPT_GOTO_RX = (1 << 4),
    OPT_GOTO_TX = (1 << 5),
    OPT_DECIBEL = (1 << 6),
    OPT_SQUELCH = (1 << 7),
 };
Function Documentation
AST_MODULE_INFO_STANDARD_EXTENDED()
AST_MODULE_INFO_STANDARD_EXTENDED (ASTERISK_GPL_KEY , "Tone detection module")
Referenced by load_module().
destroy_callback()
static void destroy_callback (void * data) static
Definition at line 201 of file app_tonedetect.c.
References ast_audiohook_destroy(), ast_audiohook_detach(), ast_audiohook_lock, ast_audiohook_unlock, ast_dsp_free(), ast_free, detect_information::audiohook, di, detect_information::dsp, detect_information::gotorx, and detect_information::gototx.
 {
    struct detect_information *di = data;
    ast_dsp_free(di->dsp);
    if (di->gotorx) {
       ast_free(di->gotorx);
    }
    if (di->gototx) {
       ast_free(di->gototx);
    }
    ast_audiohook_lock(&di->audiohook);
    ast_audiohook_detach(&di->audiohook);
    ast_audiohook_unlock(&di->audiohook);
    ast_audiohook_destroy(&di->audiohook);
    ast_free(di);
    return;
 }
detect_callback()
static int detect_callback (struct ast_audiohook * audiohook, struct ast_channel * chan, struct ast_frame * frame, enum ast_audiohook_direction direction) static
Definition at line 224 of file app_tonedetect.c.
References ast_async_parseable_goto(), AST_AUDIOHOOK_DIRECTION_READ, AST_AUDIOHOOK_STATUS_DONE, ast_channel_datastore_find(), ast_debug, ast_dsp_process(), AST_FRAME_DTMF, AST_FRAME_VOICE, ast_frfree, ast_frisolate, ast_datastore::data, di, detect_information::dsp, ast_frame::frametype, detect_information::gotorx, detect_information::gototx, ast_frame_subclass::integer, NULL, result, detect_information::rx, detect_information::rxcount, ast_audiohook::status, ast_frame::subclass, detect_information::tx, and detect_information::txcount.
Referenced by detect_write().
 {
    struct ast_datastore *datastore = NULL;
    struct detect_information *di = NULL;
    /* If the audiohook is stopping it means the channel is shutting down.... but we let the datastore destroy take care of it */
    if (audiohook->status == AST_AUDIOHOOK_STATUS_DONE)
       return 0;
    /* Grab datastore which contains our gain information */
    if (!(datastore = ast_channel_datastore_find(chan, &detect_datastore, NULL)))
       return 0;
    di = datastore->data;
    if (!frame || frame->frametype != AST_FRAME_VOICE)
       return 0;
    if (!(direction == AST_AUDIOHOOK_DIRECTION_READ ? &di->rx : &di->tx))
       return 0;
    /* we don't want to modify the original frame */
    if (!(frame = ast_frisolate(frame))) {
       return 0;
    }
    frame = ast_dsp_process(chan, di->dsp, frame);
    if (frame->frametype == AST_FRAME_DTMF) {
       char result = frame->subclass.integer;
       if (result == 'q') {
          ast_debug(1, "TONE_DETECT just got a hit\n");
          if (direction == AST_AUDIOHOOK_DIRECTION_READ)
             di->rxcount = di->rxcount + 1;
          else
             di->txcount = di->txcount + 1;
          if (direction == AST_AUDIOHOOK_DIRECTION_READ && di->gotorx) {
             ast_async_parseable_goto(chan, di->gotorx);
          } else if (di->gototx) {
             ast_async_parseable_goto(chan, di->gototx);
          }
       }
    }
    ast_frfree(frame);
    return 0;
 }
detect_read()
static int detect_read (struct ast_channel * chan, const char * cmd, char * data, char * buffer, size_t buflen) static
Definition at line 369 of file app_tonedetect.c.
References ast_channel_datastore_find(), ast_channel_lock, ast_channel_unlock, ast_log, ast_datastore::data, di, LOG_WARNING, NULL, detect_information::rxcount, and detect_information::txcount.
 {
    struct ast_datastore *datastore = NULL;
    struct detect_information *di = NULL;
    if (!chan) {
       ast_log(LOG_WARNING, "No channel was provided to %s function.\n", cmd);
       return -1;
    }
    ast_channel_lock(chan);
    if (!(datastore = ast_channel_datastore_find(chan, &detect_datastore, NULL))) {
       ast_channel_unlock(chan);
       return -1; /* function not initiated yet, so nothing to read */
    } else {
       ast_channel_unlock(chan);
       di = datastore->data;
    }
    if (strchr(data, 't')) {
       snprintf(buffer, buflen, "%d", di->txcount);
    } else if (strchr(data, 'r')) {
       snprintf(buffer, buflen, "%d", di->rxcount);
    } else {
       ast_log(LOG_WARNING, "Invalid direction: %s\n", data);
    }
    return 0;
 }
detect_write()
static int detect_write (struct ast_channel * chan, const char * cmd, char * data, const char * value) static
Definition at line 399 of file app_tonedetect.c.
References args, AST_APP_ARG, ast_app_parse_options(), ast_audiohook_attach(), ast_audiohook_init(), AST_AUDIOHOOK_MANIPULATE_ALL_RATES, AST_AUDIOHOOK_TYPE_MANIPULATE, ast_calloc, ast_channel_datastore_add(), ast_channel_datastore_find(), ast_channel_lock, ast_channel_unlock, ast_datastore_alloc, ast_datastore_free(), ast_debug, AST_DECLARE_APP_ARGS, ast_dsp_new(), ast_dsp_set_features(), ast_dsp_set_freqmode(), ast_log, AST_STANDARD_APP_ARGS, ast_str_to_int(), ast_strdupa, ast_strlen_zero, ast_test_flag, detect_information::audiohook, ast_datastore::data, detect_information::db, detect_callback(), di, detect_information::dsp, DSP_FEATURE_FREQ_DETECT, detect_information::duration, detect_information::freq1, detect_information::freq2, freq_parser(), ast_dsp::freqs, goto_parser(), detect_information::gotorx, detect_information::gototx, LOG_WARNING, ast_audiohook::manipulate_callback, NULL, OPT_ARG_ARRAY_SIZE, OPT_ARG_DECIBEL, OPT_ARG_GOTO_RX, OPT_ARG_GOTO_TX, OPT_DECIBEL, OPT_END_FILTER, OPT_GOTO_RX, OPT_GOTO_TX, OPT_RX, OPT_SQUELCH, OPT_TX, options, parse(), remove_detect(), detect_information::rx, detect_information::rxcount, detect_information::squelch, detect_information::tx, and detect_information::txcount.
 {
    char *parse;
    struct ast_datastore *datastore = NULL;
    struct detect_information *di = NULL;
    int is_new = 0;
    struct ast_flags flags = { 0 };
    char *opt_args[OPT_ARG_ARRAY_SIZE];
    struct ast_dsp *dsp;
    int freq1 = 0, freq2 = 0, duration = 500, db = 16, squelch = 0;
    AST_DECLARE_APP_ARGS(args,
       AST_APP_ARG(freqs);
       AST_APP_ARG(duration);
       AST_APP_ARG(options);
    );
    if (!chan) {
       ast_log(LOG_WARNING, "No channel was provided to %s function.\n", cmd);
       return -1;
    }
    parse = ast_strdupa(data);
    AST_STANDARD_APP_ARGS(args, parse);
    ast_channel_lock(chan);
    if (!(datastore = ast_channel_datastore_find(chan, &detect_datastore, NULL))) {
       ast_channel_unlock(chan);
       if (!(datastore = ast_datastore_alloc(&detect_datastore, NULL)))
          return 0;
       if (!(di = ast_calloc(1, sizeof(*di)))) {
          ast_datastore_free(datastore);
          return 0;
       }
       ast_audiohook_init(&di->audiohook, AST_AUDIOHOOK_TYPE_MANIPULATE, "Tone Detector", AST_AUDIOHOOK_MANIPULATE_ALL_RATES);
       di->audiohook.manipulate_callback = detect_callback;
       is_new = 1;
    } else {
       ast_channel_unlock(chan);
       di = datastore->data;
    }
    if (!ast_strlen_zero(args.options)) {
       ast_app_parse_options(td_opts, &flags, opt_args, args.options);
    }
    if (ast_test_flag(&flags, OPT_END_FILTER)) {
       return remove_detect(chan);
    }
    if (freq_parser(args.freqs, &freq1, &freq2)) {
       return -1;
    }
    if (!ast_strlen_zero(args.duration) && (ast_str_to_int(args.duration, &duration) || duration < 1)) {
       ast_log(LOG_WARNING, "Invalid duration: %s\n", args.duration);
       return -1;
    }
    di->duration = duration;
    if (ast_test_flag(&flags, OPT_DECIBEL) && !ast_strlen_zero(opt_args[OPT_ARG_DECIBEL])) {
       if ((ast_str_to_int(opt_args[OPT_ARG_DECIBEL], &db) || db < 1)) {
          ast_log(LOG_WARNING, "Invalid decibel level: %s\n", opt_args[OPT_ARG_DECIBEL]);
          return -1;
       }
    }
    di->gotorx = NULL;
    di->gototx = NULL;
    /* resolve gotos now, in case a full context,exten,pri wasn't specified */
    if (ast_test_flag(&flags, OPT_GOTO_RX) && !ast_strlen_zero(opt_args[OPT_ARG_GOTO_RX])) {
       di->gotorx = goto_parser(chan, opt_args[OPT_ARG_GOTO_RX]);
    }
    if (ast_test_flag(&flags, OPT_GOTO_TX) && !ast_strlen_zero(opt_args[OPT_ARG_GOTO_TX])) {
       di->gototx = goto_parser(chan, opt_args[OPT_ARG_GOTO_TX]);
    }
    di->db = db;
    di->squelch = ast_test_flag(&flags, OPT_SQUELCH);
    di->tx = 1;
    di->rx = 1;
    if (ast_strlen_zero(args.options) || ast_test_flag(&flags, OPT_TX)) {
       di->tx = 1;
       di->rx = 0;
    }
    if (ast_strlen_zero(args.options) || ast_test_flag(&flags, OPT_RX)) {
       di->rx = 1;
       di->tx = 0;
    }
    if (is_new) {
       if (!(dsp = ast_dsp_new())) {
          ast_log(LOG_WARNING, "Unable to allocate DSP!\n");
          return -1;
       }
       ast_dsp_set_features(dsp, DSP_FEATURE_FREQ_DETECT);
       ast_dsp_set_freqmode(dsp, freq1, duration, db, squelch);
       di->dsp = dsp;
       di->txcount = 0;
       di->rxcount = 0;
       ast_debug(1, "Keeping our ears open for %s Hz, %d db\n", args.freqs, db);
       datastore->data = di;
       ast_channel_lock(chan);
       ast_channel_datastore_add(chan, datastore);
       ast_channel_unlock(chan);
       ast_audiohook_attach(chan, &di->audiohook);
    } else {
       dsp = di->dsp;
       ast_dsp_set_freqmode(dsp, freq1, duration, db, squelch);
    }
    return 0;
 }
freq_parser()
static int freq_parser (char * freqs, int * freq1, int * freq2) static
Definition at line 299 of file app_tonedetect.c.
References ast_log, ast_str_to_int(), ast_strdupa, ast_strlen_zero, LOG_ERROR, LOG_WARNING, and strsep().
Referenced by detect_write(), and wait_exec().
{
    char *f1, *f2, *f3;
    if (ast_strlen_zero(freqs)) {
       ast_log(LOG_ERROR, "No frequency specified\n");
       return -1;
    }
    f3 = ast_strdupa(freqs);
    f1 = strsep(&f3, "+");
    f2 = strsep(&f3, "+");
    if (!ast_strlen_zero(f3)) {
       ast_log(LOG_WARNING, "Only up to 2 frequencies may be specified: %s\n", freqs);
       return -1;
    }
    if (ast_str_to_int(f1, freq1)) {
       ast_log(LOG_WARNING, "Frequency must be an integer: %s\n", f1);
       return -1;
    }
    if (*freq1 < 1) {
       ast_log(LOG_WARNING, "Sorry, positive frequencies only: %d\n", *freq1);
       return -1;
    }
    if (!ast_strlen_zero(f2)) {
       ast_log(LOG_WARNING, "Sorry, currently only 1 frequency is supported\n");
       return -1;
       /* not supported just yet, but possibly will be in the future */
       if (ast_str_to_int(f2, freq2)) {
          ast_log(LOG_WARNING, "Frequency must be an integer: %s\n", f2);
          return -1;
       }
       if (*freq2 < 1) {
          ast_log(LOG_WARNING, "Sorry, positive frequencies only: %d\n", *freq2);
          return -1;
       }
    }
    return 0;
 }
goto_parser()
static char* goto_parser (struct ast_channel * chan, char * loc) static
Definition at line 336 of file app_tonedetect.c.
References ast_channel_context(), ast_channel_exten(), ast_channel_lock, ast_channel_unlock, ast_malloc, ast_strdupa, ast_strlen_zero, context, exten, NULL, parse(), and strsep().
Referenced by detect_write().
{
    char *exten, *pri, *context, *parse;
    char *dest;
    int size;
    parse = ast_strdupa(loc);
    context = strsep(&parse, ",");
    exten = strsep(&parse, ",");
    pri = strsep(&parse, ",");
    if (!exten) {
       pri = context;
       exten = NULL;
       context = NULL;
    } else if (!pri) {
       pri = exten;
       exten = context;
       context = NULL;
    }
    ast_channel_lock(chan);
    if (ast_strlen_zero(exten)) {
       exten = ast_strdupa(ast_channel_exten(chan));
    }
    if (ast_strlen_zero(context)) {
       context = ast_strdupa(ast_channel_context(chan));
    }
    ast_channel_unlock(chan);
    /* size + 1 for null terminator + 2 commas */
    size = sizeof(context) + sizeof(exten) + sizeof(pri) + 2;
    dest = ast_malloc(size + 1);
    snprintf(dest, size, "%s,%s,%s", context, exten, pri);
    return dest;
 }
load_module()
static int load_module (void) static
Definition at line 641 of file app_tonedetect.c.
References ast_custom_function_register, AST_MODULE_INFO_STANDARD_EXTENDED(), ast_register_application_xml, ASTERISK_GPL_KEY, and wait_exec().
 {
    int res;
    res = ast_register_application_xml(waitapp, wait_exec);
    res |= ast_custom_function_register(&detect_function);
    return res;
 }
remove_detect()
static int remove_detect (struct ast_channel * chan) static
Definition at line 270 of file app_tonedetect.c.
References ast_audiohook_remove(), ast_channel_datastore_find(), ast_channel_datastore_remove(), ast_channel_name(), ast_datastore_free(), ast_log, AST_LOG_WARNING, detect_information::audiohook, ast_datastore::data, NULL, and SCOPED_CHANNELLOCK.
Referenced by detect_write().
 {
    struct ast_datastore *datastore = NULL;
    struct detect_information *data;
    SCOPED_CHANNELLOCK(chan_lock, chan);
    datastore = ast_channel_datastore_find(chan, &detect_datastore, NULL);
    if (!datastore) {
       ast_log(AST_LOG_WARNING, "Cannot remove TONE_DETECT from %s: TONE_DETECT not currently enabled\n",
               ast_channel_name(chan));
       return -1;
    }
    data = datastore->data;
    if (ast_audiohook_remove(chan, &data->audiohook)) {
       ast_log(AST_LOG_WARNING, "Failed to remove TONE_DETECT audiohook from channel %s\n", ast_channel_name(chan));
       return -1;
    }
    if (ast_channel_datastore_remove(chan, datastore)) {
       ast_log(AST_LOG_WARNING, "Failed to remove TONE_DETECT datastore from channel %s\n",
               ast_channel_name(chan));
       return -1;
    }
    ast_datastore_free(datastore);
    return 0;
 }
unload_module()
static int unload_module (void) static
Definition at line 631 of file app_tonedetect.c.
References ast_custom_function_unregister(), and ast_unregister_application().
 {
    int res;
    res = ast_unregister_application(waitapp);
    res |= ast_custom_function_unregister(&detect_function);
    return res;
 }
wait_exec()
static int wait_exec (struct ast_channel * chan, const char * data) static
Definition at line 524 of file app_tonedetect.c.
References args, AST_APP_ARG, ast_app_parse_options(), ast_channel_name(), ast_debug, AST_DECLARE_APP_ARGS, ast_dsp_free(), ast_dsp_new(), ast_dsp_process(), ast_dsp_set_features(), ast_dsp_set_freqmode(), AST_FRAME_DTMF, AST_FRAME_VOICE, ast_log, ast_read(), ast_remaining_ms(), AST_STANDARD_APP_ARGS, ast_str_to_int(), ast_strdupa, ast_strlen_zero, ast_test_flag, ast_tvnow(), ast_waitfor(), detect_information::db, detect_information::dsp, DSP_FEATURE_FREQ_DETECT, detect_information::duration, ast_frame::frametype, detect_information::freq1, detect_information::freq2, freq_parser(), ast_frame_subclass::integer, LOG_WARNING, NULL, OPT_APP_ARG_ARRAY_SIZE, OPT_APP_ARG_DECIBEL, OPT_APP_DECIBEL, OPT_APP_SQUELCH, options, pbx_builtin_setvar_helper(), result, detect_information::squelch, ast_frame::subclass, timeout, and wait_exec_options.
Referenced by load_module().
 {
    char *appdata;
    struct ast_flags flags = {0};
    char *opt_args[OPT_APP_ARG_ARRAY_SIZE];
    double timeoutf = 0;
    int freq1 = 0, freq2 = 0, timeout = 0, duration = 500, times = 1, db = 16, squelch = 0;
    struct ast_frame *frame = NULL;
    struct ast_dsp *dsp;
    struct timeval start;
    int remaining_time = 0;
    int hits = 0;
    AST_DECLARE_APP_ARGS(args,
       AST_APP_ARG(freqs);
       AST_APP_ARG(duration);
       AST_APP_ARG(timeout);
       AST_APP_ARG(times);
       AST_APP_ARG(options);
    );
    appdata = ast_strdupa(data);
    AST_STANDARD_APP_ARGS(args, appdata);
    if (!ast_strlen_zero(args.options)) {
       ast_app_parse_options(wait_exec_options, &flags, opt_args, args.options);
    }
    if (freq_parser(args.freqs, &freq1, &freq2)) {
       pbx_builtin_setvar_helper(chan, "WAITFORTONESTATUS", "ERROR");
       return -1;
    }
    if (!ast_strlen_zero(args.timeout) && (sscanf(args.timeout, "%30lf", &timeoutf) != 1 || timeout < 0)) {
       ast_log(LOG_WARNING, "Invalid timeout: %s\n", args.timeout);
       pbx_builtin_setvar_helper(chan, "WAITFORTONESTATUS", "ERROR");
       return -1;
    }
    timeout = 1000 * timeoutf;
    if (!ast_strlen_zero(args.duration) && (ast_str_to_int(args.duration, &duration) || duration < 1)) {
       ast_log(LOG_WARNING, "Invalid duration: %s\n", args.duration);
       pbx_builtin_setvar_helper(chan, "WAITFORTONESTATUS", "ERROR");
       return -1;
    }
    if (!ast_strlen_zero(args.times) && (ast_str_to_int(args.times, &times) || times < 1)) {
       ast_log(LOG_WARNING, "Invalid number of times: %s\n", args.times);
       pbx_builtin_setvar_helper(chan, "WAITFORTONESTATUS", "ERROR");
       return -1;
    }
    if (ast_test_flag(&flags, OPT_APP_DECIBEL) && !ast_strlen_zero(opt_args[OPT_APP_ARG_DECIBEL])) {
       if ((ast_str_to_int(opt_args[OPT_APP_ARG_DECIBEL], &db) || db < 1)) {
          ast_log(LOG_WARNING, "Invalid decibel level: %s\n", opt_args[OPT_APP_ARG_DECIBEL]);
          pbx_builtin_setvar_helper(chan, "WAITFORTONESTATUS", "ERROR");
          return -1;
       }
    }
    squelch = ast_test_flag(&flags, OPT_APP_SQUELCH);
    if (!(dsp = ast_dsp_new())) {
       ast_log(LOG_WARNING, "Unable to allocate DSP!\n");
       pbx_builtin_setvar_helper(chan, "WAITFORTONESTATUS", "ERROR");
       return -1;
    }
    ast_dsp_set_features(dsp, DSP_FEATURE_FREQ_DETECT);
    ast_dsp_set_freqmode(dsp,  freq1, duration, db, squelch);
    ast_debug(1, "Waiting for %s Hz, %d time(s), timeout %d ms, %d db\n", args.freqs, times, timeout, db);
    start = ast_tvnow();
    while (timeout == 0 || remaining_time > 0) {
       if (timeout > 0) {
          remaining_time = ast_remaining_ms(start, timeout);
          if (remaining_time <= 0) {
             pbx_builtin_setvar_helper(chan, "WAITFORTONESTATUS", "TIMEOUT");
             break;
          }
       }
       if (ast_waitfor(chan, 1000) > 0) {
          if (!(frame = ast_read(chan))) {
             ast_debug(1, "Channel '%s' did not return a frame; probably hung up.\n", ast_channel_name(chan));
             pbx_builtin_setvar_helper(chan, "WAITFORTONESTATUS", "HANGUP");
             break;
          } else if (frame->frametype == AST_FRAME_VOICE) {
             frame = ast_dsp_process(chan, dsp, frame);
             if (frame->frametype == AST_FRAME_DTMF) {
                char result = frame->subclass.integer;
                if (result == 'q') {
                   hits++;
                   ast_debug(1, "We just detected %s Hz (hit #%d)\n", args.freqs, hits);
                   if (hits >= times) {
                      pbx_builtin_setvar_helper(chan, "WAITFORTONESTATUS", "SUCCESS");
                      break;
                   }
                }
             }
          }
       } else {
          pbx_builtin_setvar_helper(chan, "WAITFORTONESTATUS", "HANGUP");
       }
    }
    ast_dsp_free(dsp);
    return 0;
 }
Variable Documentation
detect_datastore
const struct ast_datastore_info detect_datastore static
Initial value:
= {
   .type = "detect",
   .destroy = destroy_callback
}
Definition at line 219 of file app_tonedetect.c.
detect_function
struct ast_custom_function detect_function static
Initial value:
= {
   .name = "TONE_DETECT",
   .read = detect_read,
   .write = detect_write,
}
Definition at line 625 of file app_tonedetect.c.
td_opts
const struct ast_app_option td_opts[128] = { [ 'd' ] = { .flag = OPT_DECIBEL , .arg_index = OPT_ARG_DECIBEL + 1 }, [ 'g' ] = { .flag = OPT_GOTO_RX , .arg_index = OPT_ARG_GOTO_RX + 1 }, [ 'h' ] = { .flag = OPT_GOTO_TX , .arg_index = OPT_ARG_GOTO_TX + 1 }, [ 's' ] = { .flag = OPT_SQUELCH }, [ 't' ] = { .flag = OPT_TX }, [ 'r' ] = { .flag = OPT_RX }, [ 'x' ] = { .flag = OPT_END_FILTER }, } static
Definition at line 199 of file app_tonedetect.c.
wait_exec_options
const struct ast_app_option wait_exec_options[128] = { [ 'd' ] = { .flag = OPT_APP_DECIBEL , .arg_index = OPT_APP_ARG_DECIBEL + 1 }, [ 's' ] = { .flag = OPT_APP_SQUELCH }, } static
Definition at line 522 of file app_tonedetect.c.
Referenced by wait_exec().
waitapp
char* waitapp = "WaitForTone" static
Definition at line 623 of file app_tonedetect.c.