Asterisk - The Open Source Telephony Project: res_ari_events.c File Reference
res_ari_events.c File Reference
WebSocket resource.
#include "asterisk.h"
#include "asterisk/app.h"
#include "asterisk/module.h"
#include "asterisk/stasis_app.h"
#include "ari/resource_events.h"
#include "ari/ari_model_validators.h"
#include "asterisk/http_websocket.h"
Macros
#define MAX_VALS 128
Functions
static void __reg_module (void)
static void __unreg_module (void)
static int ast_ari_events_event_websocket_ws_attempted_cb (struct ast_tcptls_session_instance *ser, struct ast_variable *get_params, struct ast_variable *headers, const char *session_id)
static void ast_ari_events_event_websocket_ws_established_cb (struct ast_websocket *ws_session, struct ast_variable *get_params, struct ast_variable *headers)
static void ast_ari_events_user_event_cb (struct ast_tcptls_session_instance *ser, struct ast_variable *get_params, struct ast_variable *path_vars, struct ast_variable *headers, struct ast_json *body, struct ast_ari_response *response)
Parameter parsing callback for /events/user/{eventName}.
int ast_ari_events_user_event_parse_body (struct ast_json *body, struct ast_ari_events_user_event_args *args)
Body parsing function for /events/user/{eventName}.
struct ast_module * AST_MODULE_SELF_SYM (void)
static int load_module (void)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_DEFAULT , .description = "RESTful API module - WebSocket resource" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .requires = "res_ari,res_ari_model,res_stasis,res_http_websocket", }
static const struct ast_module_info * ast_module_info = &__mod_info
static struct stasis_rest_handlers events
REST handler for /api-docs/events.json.
static struct stasis_rest_handlers events_user
REST handler for /api-docs/events.json.
static struct stasis_rest_handlers events_user_eventName
REST handler for /api-docs/events.json.
Detailed Description
WebSocket resource.
Author
David M. Lee, II dlee@.nosp@m.digi.nosp@m.um.co.nosp@m.m
Definition in file res_ari_events.c.
Macro Definition Documentation
MAX_VALS
#define MAX_VALS 128
Definition at line 53 of file res_ari_events.c.
Referenced by ast_ari_events_event_websocket_ws_attempted_cb(), ast_ari_events_event_websocket_ws_established_cb(), and ast_ari_events_user_event_cb().
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 473 of file res_ari_events.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 473 of file res_ari_events.c.
ast_ari_events_event_websocket_ws_attempted_cb()
static int ast_ari_events_event_websocket_ws_attempted_cb (struct ast_tcptls_session_instance * ser, struct ast_variable * get_params, struct ast_variable * headers, const char * session_id) static
Definition at line 55 of file res_ari_events.c.
References ast_ari_events_event_websocket_args::app, ast_ari_events_event_websocket_args::app_count, ast_ari_events_event_websocket_args::app_parse, ARRAY_LEN, ast_app_separate_args, ast_ari_response_alloc_failed(), ast_ari_response_error(), ast_ari_websocket_events_event_websocket_attempted(), ast_calloc, ast_free, ast_http_error(), ast_json_dump_string, ast_json_free(), ast_log, ast_malloc, ast_strdup, ast_true(), LOG_ERROR, MAX_VALS, ast_variable::name, ast_variable::next, NULL, RAII_VAR, ast_ari_events_event_websocket_args::subscribe_all, and ast_variable::value.
Referenced by load_module().
 {
    struct ast_ari_events_event_websocket_args args = {};
    int res = 0;
    RAII_VAR(struct ast_ari_response *, response, NULL, ast_free);
    struct ast_variable *i;
    response = ast_calloc(1, sizeof(*response));
    if (!response) {
       ast_log(LOG_ERROR, "Failed to create response.\n");
       goto fin;
    }
    for (i = get_params; i; i = i->next) {
       if (strcmp(i->name, "app") == 0) {
          /* Parse comma separated list */
          char *vals[MAX_VALS];
          size_t j;
          args.app_parse = ast_strdup(i->value);
          if (!args.app_parse) {
             ast_ari_response_alloc_failed(response);
             goto fin;
          }
          if (strlen(args.app_parse) == 0) {
             /* ast_app_separate_args can't handle "" */
             args.app_count = 1;
             vals[0] = args.app_parse;
          } else {
             args.app_count = ast_app_separate_args(
                args.app_parse, ',', vals,
                ARRAY_LEN(vals));
          }
          if (args.app_count == 0) {
             ast_ari_response_alloc_failed(response);
             goto fin;
          }
          if (args.app_count >= MAX_VALS) {
             ast_ari_response_error(response, 400,
                "Bad Request",
                "Too many values for app");
             goto fin;
          }
          args.app = ast_malloc(sizeof(*args.app) * args.app_count);
          if (!args.app) {
             ast_ari_response_alloc_failed(response);
             goto fin;
          }
          for (j = 0; j < args.app_count; ++j) {
             args.app[j] = (vals[j]);
          }
       } else
       if (strcmp(i->name, "subscribeAll") == 0) {
          args.subscribe_all = ast_true(i->value);
       } else
       {}
    }
    res = ast_ari_websocket_events_event_websocket_attempted(ser, headers, &args, session_id);
 fin: __attribute__((unused))
    if (!response) {
       ast_http_error(ser, 500, "Server Error", "Memory allocation error");
       res = -1;
    } else if (response->response_code != 0) {
       /* Param parsing failure */
       RAII_VAR(char *, msg, NULL, ast_json_free);
       if (response->message) {
          msg = ast_json_dump_string(response->message);
       } else {
          ast_log(LOG_ERROR, "Missing response message\n");
       }
       if (msg) {
          ast_http_error(ser, response->response_code, response->response_text, msg);
       }
       res = -1;
    }
    ast_free(args.app_parse);
    ast_free(args.app);
    return res;
 }
ast_ari_events_event_websocket_ws_established_cb()
static void ast_ari_events_event_websocket_ws_established_cb (struct ast_websocket * ws_session, struct ast_variable * get_params, struct ast_variable * headers) static
Definition at line 144 of file res_ari_events.c.
References ao2_cleanup, ast_ari_events_event_websocket_args::app, ast_ari_events_event_websocket_args::app_count, ast_ari_events_event_websocket_args::app_parse, ARRAY_LEN, ast_app_separate_args, ast_ari_response_alloc_failed(), ast_ari_response_error(), ast_ari_validate_message_fn(), ast_ari_websocket_events_event_websocket_established(), ast_ari_websocket_session_create(), ast_calloc, ast_free, ast_json_dump_string, ast_json_free(), ast_log, ast_malloc, ast_strdup, ast_true(), AST_WEBSOCKET_OPCODE_TEXT, ast_websocket_unref(), ast_websocket_write(), LOG_ERROR, MAX_VALS, ast_variable::name, ast_variable::next, NULL, RAII_VAR, SCOPED_MODULE_USE, ast_module_info::self, session, ast_ari_events_event_websocket_args::subscribe_all, and ast_variable::value.
Referenced by load_module().
 {
    struct ast_ari_events_event_websocket_args args = {};
    RAII_VAR(struct ast_ari_response *, response, NULL, ast_free);
    struct ast_variable *i;
    RAII_VAR(struct ast_websocket *, s, ws_session, ast_websocket_unref);
    RAII_VAR(struct ast_ari_websocket_session *, session, NULL, ao2_cleanup);
    SCOPED_MODULE_USE(ast_module_info->self);
    response = ast_calloc(1, sizeof(*response));
    if (!response) {
       ast_log(LOG_ERROR, "Failed to create response.\n");
       goto fin;
    }
 #if defined(AST_DEVMODE)
    session = ast_ari_websocket_session_create(ws_session,
       ast_ari_validate_message_fn());
 #else
    session = ast_ari_websocket_session_create(ws_session, NULL);
 #endif
    if (!session) {
       ast_log(LOG_ERROR, "Failed to create ARI session\n");
       goto fin;
    }
    for (i = get_params; i; i = i->next) {
       if (strcmp(i->name, "app") == 0) {
          /* Parse comma separated list */
          char *vals[MAX_VALS];
          size_t j;
          args.app_parse = ast_strdup(i->value);
          if (!args.app_parse) {
             ast_ari_response_alloc_failed(response);
             goto fin;
          }
          if (strlen(args.app_parse) == 0) {
             /* ast_app_separate_args can't handle "" */
             args.app_count = 1;
             vals[0] = args.app_parse;
          } else {
             args.app_count = ast_app_separate_args(
                args.app_parse, ',', vals,
                ARRAY_LEN(vals));
          }
          if (args.app_count == 0) {
             ast_ari_response_alloc_failed(response);
             goto fin;
          }
          if (args.app_count >= MAX_VALS) {
             ast_ari_response_error(response, 400,
                "Bad Request",
                "Too many values for app");
             goto fin;
          }
          args.app = ast_malloc(sizeof(*args.app) * args.app_count);
          if (!args.app) {
             ast_ari_response_alloc_failed(response);
             goto fin;
          }
          for (j = 0; j < args.app_count; ++j) {
             args.app[j] = (vals[j]);
          }
       } else
       if (strcmp(i->name, "subscribeAll") == 0) {
          args.subscribe_all = ast_true(i->value);
       } else
       {}
    }
    ast_ari_websocket_events_event_websocket_established(session, headers, &args);
 fin: __attribute__((unused))
    if (response && response->response_code != 0) {
       /* Param parsing failure */
       RAII_VAR(char *, msg, NULL, ast_json_free);
       if (response->message) {
          msg = ast_json_dump_string(response->message);
       } else {
          ast_log(LOG_ERROR, "Missing response message\n");
       }
       if (msg) {
          ast_websocket_write(ws_session,
             AST_WEBSOCKET_OPCODE_TEXT, msg,  strlen(msg));
       }
    }
    ast_free(args.app_parse);
    ast_free(args.app);
 }
ast_ari_events_user_event_cb()
static void ast_ari_events_user_event_cb (struct ast_tcptls_session_instance * ser, struct ast_variable * get_params, struct ast_variable * path_vars, struct ast_variable * headers, struct ast_json * body, struct ast_ari_response * response) static
Parameter parsing callback for /events/user/{eventName}.
Parameters
get_params GET parameters in the HTTP request.
path_vars Path variables extracted from the request.
headers HTTP headers.
[out] response Response to the HTTP request.
Definition at line 290 of file res_ari_events.c.
References ast_ari_events_user_event_args::application, ARRAY_LEN, ast_app_separate_args, ast_ari_events_user_event(), ast_ari_response_alloc_failed(), ast_ari_response_error(), ast_ari_validate_void(), ast_free, ast_log, ast_malloc, ast_strdup, ast_ari_events_user_event_args::event_name, LOG_ERROR, MAX_VALS, ast_ari_response::message, ast_variable::name, ast_variable::next, NULL, ast_ari_response::response_code, ast_ari_events_user_event_args::source, ast_ari_events_user_event_args::source_count, ast_ari_events_user_event_args::source_parse, ast_variable::value, and ast_ari_events_user_event_args::variables.
 {
    struct ast_ari_events_user_event_args args = {};
    struct ast_variable *i;
 #if defined(AST_DEVMODE)
    int is_valid;
    int code;
 #endif /* AST_DEVMODE */
    for (i = get_params; i; i = i->next) {
       if (strcmp(i->name, "application") == 0) {
          args.application = (i->value);
       } else
       if (strcmp(i->name, "source") == 0) {
          /* Parse comma separated list */
          char *vals[MAX_VALS];
          size_t j;
          args.source_parse = ast_strdup(i->value);
          if (!args.source_parse) {
             ast_ari_response_alloc_failed(response);
             goto fin;
          }
          if (strlen(args.source_parse) == 0) {
             /* ast_app_separate_args can't handle "" */
             args.source_count = 1;
             vals[0] = args.source_parse;
          } else {
             args.source_count = ast_app_separate_args(
                args.source_parse, ',', vals,
                ARRAY_LEN(vals));
          }
          if (args.source_count == 0) {
             ast_ari_response_alloc_failed(response);
             goto fin;
          }
          if (args.source_count >= MAX_VALS) {
             ast_ari_response_error(response, 400,
                "Bad Request",
                "Too many values for source");
             goto fin;
          }
          args.source = ast_malloc(sizeof(*args.source) * args.source_count);
          if (!args.source) {
             ast_ari_response_alloc_failed(response);
             goto fin;
          }
          for (j = 0; j < args.source_count; ++j) {
             args.source[j] = (vals[j]);
          }
       } else
       {}
    }
    for (i = path_vars; i; i = i->next) {
       if (strcmp(i->name, "eventName") == 0) {
          args.event_name = (i->value);
       } else
       {}
    }
    args.variables = body;
    ast_ari_events_user_event(headers, &args, response);
 #if defined(AST_DEVMODE)
    code = response->response_code;
    switch (code) {
    case 0: /* Implementation is still a stub, or the code wasn't set */
       is_valid = response->message == NULL;
       break;
    case 500: /* Internal Server Error */
    case 501: /* Not Implemented */
    case 404: /* Application does not exist. */
    case 422: /* Event source not found. */
    case 400: /* Invalid even tsource URI or userevent data. */
       is_valid = 1;
       break;
    default:
       if (200 <= code && code <= 299) {
          is_valid = ast_ari_validate_void(
             response->message);
       } else {
          ast_log(LOG_ERROR, "Invalid error response %d for /events/user/{eventName}\n", code);
          is_valid = 0;
       }
    }
    if (!is_valid) {
       ast_log(LOG_ERROR, "Response validation failed for /events/user/{eventName}\n");
       ast_ari_response_error(response, 500,
          "Internal Server Error", "Response validation failed");
    }
 #endif /* AST_DEVMODE */
 fin: __attribute__((unused))
    ast_free(args.source_parse);
    ast_free(args.source);
    return;
 }
ast_ari_events_user_event_parse_body()
int ast_ari_events_user_event_parse_body (struct ast_json * body, struct ast_ari_events_user_event_args * args)
Body parsing function for /events/user/{eventName}.
Parameters
body The JSON body from which to parse parameters.
[out] args The args structure to parse into.
Return values
zero on success
non-zero on failure
Definition at line 241 of file res_ari_events.c.
References ast_ari_events_user_event_args::application, ast_free, AST_JSON_ARRAY, ast_json_array_get(), ast_json_array_size(), ast_json_object_get(), ast_json_string_get(), ast_json_typeof(), ast_malloc, ast_ari_events_user_event_args::source, and ast_ari_events_user_event_args::source_count.
Referenced by ast_ari_events_user_event().
 {
    struct ast_json *field;
    /* Parse query parameters out of it */
    field = ast_json_object_get(body, "application");
    if (field) {
       args->application = ast_json_string_get(field);
    }
    field = ast_json_object_get(body, "source");
    if (field) {
       /* If they were silly enough to both pass in a query param and a
        * JSON body, free up the query value.
        */
       ast_free(args->source);
       if (ast_json_typeof(field) == AST_JSON_ARRAY) {
          /* Multiple param passed as array */
          size_t i;
          args->source_count = ast_json_array_size(field);
          args->source = ast_malloc(sizeof(*args->source) * args->source_count);
          if (!args->source) {
             return -1;
          }
          for (i = 0; i < args->source_count; ++i) {
             args->source[i] = ast_json_string_get(ast_json_array_get(field, i));
          }
       } else {
          /* Multiple param passed as single value */
          args->source_count = 1;
          args->source = ast_malloc(sizeof(*args->source) * args->source_count);
          if (!args->source) {
             return -1;
          }
          args->source[0] = ast_json_string_get(field);
       }
    }
    return 0;
 }
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 473 of file res_ari_events.c.
load_module()
static int load_module (void) static
Definition at line 432 of file res_ari_events.c.
References ao2_ref, ast_ari_add_handler(), ast_ari_events_event_websocket_ws_attempted_cb(), ast_ari_events_event_websocket_ws_established_cb(), ast_ari_websocket_events_event_websocket_dtor(), ast_ari_websocket_events_event_websocket_init(), AST_MODFLAG_DEFAULT, AST_MODULE_INFO(), AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, AST_MODULE_SUPPORT_CORE, ast_websocket_server_add_protocol2(), ast_websocket_server_create(), ast_websocket_sub_protocol_alloc(), ASTERISK_GPL_KEY, NULL, ast_websocket_protocol::session_attempted, ast_websocket_protocol::session_established, unload_module(), and stasis_rest_handlers::ws_server.
 {
    int res = 0;
    struct ast_websocket_protocol *protocol;
    if (ast_ari_websocket_events_event_websocket_init() == -1) {
       return AST_MODULE_LOAD_DECLINE;
    }
    events.ws_server = ast_websocket_server_create();
    if (!events.ws_server) {
       ast_ari_websocket_events_event_websocket_dtor();
       return AST_MODULE_LOAD_DECLINE;
    }
    protocol = ast_websocket_sub_protocol_alloc("ari");
    if (!protocol) {
       ao2_ref(events.ws_server, -1);
       events.ws_server = NULL;
       ast_ari_websocket_events_event_websocket_dtor();
       return AST_MODULE_LOAD_DECLINE;
    }
    protocol->session_attempted = ast_ari_events_event_websocket_ws_attempted_cb;
    protocol->session_established = ast_ari_events_event_websocket_ws_established_cb;
    res |= ast_websocket_server_add_protocol2(events.ws_server, protocol);
    res |= ast_ari_add_handler(&events);
    if (res) {
       unload_module();
       return AST_MODULE_LOAD_DECLINE;
    }
    return AST_MODULE_LOAD_SUCCESS;
 }
unload_module()
static int unload_module (void) static
Definition at line 423 of file res_ari_events.c.
References ao2_cleanup, ast_ari_remove_handler(), ast_ari_websocket_events_event_websocket_dtor(), NULL, and stasis_rest_handlers::ws_server.
Referenced by load_module().
 {
    ast_ari_remove_handler(&events);
    ao2_cleanup(events.ws_server);
    events.ws_server = NULL;
    ast_ari_websocket_events_event_websocket_dtor();
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_DEFAULT , .description = "RESTful API module - WebSocket resource" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .requires = "res_ari,res_ari_model,res_stasis,res_http_websocket", } static
Definition at line 473 of file res_ari_events.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 473 of file res_ari_events.c.
events
struct stasis_rest_handlers events static
REST handler for /api-docs/events.json.
Definition at line 415 of file res_ari_events.c.
events_user
struct stasis_rest_handlers events_user static
REST handler for /api-docs/events.json.
Definition at line 407 of file res_ari_events.c.
events_user_eventName
struct stasis_rest_handlers events_user_eventName static
REST handler for /api-docs/events.json.
Definition at line 397 of file res_ari_events.c.