Asterisk - The Open Source Telephony Project: res_pjsip_private.h File Reference
res_pjsip_private.h File Reference
#include "asterisk/module.h"
#include "asterisk/compat.h"
Enumerations
enum ast_sip_taskprocessor_overload_trigger { TASKPROCESSOR_OVERLOAD_TRIGGER_NONE = 0, TASKPROCESSOR_OVERLOAD_TRIGGER_GLOBAL, TASKPROCESSOR_OVERLOAD_TRIGGER_PJSIP_ONLY }
Functions
void ast_res_pjsip_cleanup_message_filter (void)
void ast_res_pjsip_cleanup_options_handling (void)
void ast_res_pjsip_destroy_configuration (void)
struct ast_sip_contact_status * ast_res_pjsip_find_or_create_contact_status (const struct ast_sip_contact *contact)
int ast_res_pjsip_init_contact_transports (void)
int ast_res_pjsip_init_message_filter (void)
int ast_res_pjsip_init_options_handling (int reload)
int ast_res_pjsip_initialize_configuration (void)
int ast_res_pjsip_preinit_options_handling (void)
int ast_res_pjsip_reload_configuration (void)
void ast_sip_destroy_cli (void)
void ast_sip_destroy_distributor (void)
void ast_sip_destroy_global_headers (void)
int ast_sip_destroy_scheduler (void)
int ast_sip_destroy_sorcery_auth (void)
int ast_sip_destroy_sorcery_global (void)
int ast_sip_destroy_sorcery_location (void)
int ast_sip_destroy_sorcery_transport (void)
void ast_sip_destroy_system (void)
void ast_sip_destroy_transport_events (void)
void ast_sip_destroy_transport_management (void)
enum ast_sip_taskprocessor_overload_trigger ast_sip_get_taskprocessor_overload_trigger (void)
char * ast_sip_global_default_outbound_endpoint (void)
int ast_sip_initialize_cli (void)
int ast_sip_initialize_distributor (void)
void ast_sip_initialize_dns (void)
int ast_sip_initialize_global (void)
void ast_sip_initialize_global_headers (void)
void ast_sip_initialize_resolver (void)
int ast_sip_initialize_scheduler (void)
Initialize scheduler.
int ast_sip_initialize_sorcery_auth (void)
Initialize sorcery with auth support.
int ast_sip_initialize_sorcery_domain_alias (void)
Initialize sorcery with domain alias support.
int ast_sip_initialize_sorcery_global (void)
int ast_sip_initialize_sorcery_location (void)
Initialize sorcery with location support.
int ast_sip_initialize_sorcery_qualify (void)
int ast_sip_initialize_sorcery_transport (void)
Initialize sorcery with transport support.
int ast_sip_initialize_system (void)
int ast_sip_initialize_transport_events (void)
int ast_sip_initialize_transport_management (void)
const char * ast_sip_overload_trigger_to_str (enum ast_sip_taskprocessor_overload_trigger trigger)
int ast_sip_persistent_endpoint_add_to_regcontext (const char *regcontext)
int ast_sip_validate_uri_length (const char *uri)
int ast_sip_will_uri_survive_restart (pjsip_sip_uri *uri, struct ast_sip_endpoint *endpoint, pjsip_rx_data *rdata)
int sip_cli_print_global (struct ast_sip_cli_context *context)
int sip_cli_print_system (struct ast_sip_cli_context *context)
void sip_get_threadpool_options (struct ast_threadpool_options *threadpool_options)
Enumeration Type Documentation
ast_sip_taskprocessor_overload_trigger
enum ast_sip_taskprocessor_overload_trigger
Enumerator
TASKPROCESSOR_OVERLOAD_TRIGGER_NONE
TASKPROCESSOR_OVERLOAD_TRIGGER_GLOBAL
TASKPROCESSOR_OVERLOAD_TRIGGER_PJSIP_ONLY
Definition at line 411 of file res_pjsip_private.h.
{
    TASKPROCESSOR_OVERLOAD_TRIGGER_NONE = 0,
    TASKPROCESSOR_OVERLOAD_TRIGGER_GLOBAL,
    TASKPROCESSOR_OVERLOAD_TRIGGER_PJSIP_ONLY
 };
Function Documentation
ast_res_pjsip_cleanup_message_filter()
void ast_res_pjsip_cleanup_message_filter (void)
Definition at line 565 of file pjsip_message_filter.c.
References ast_sip_session_unregister_supplement(), ast_sip_unregister_service(), ast_sip_unregister_supplement(), filter_module_transport, and filter_module_tsx.
Referenced by ast_res_pjsip_init_message_filter(), and unload_pjsip().
 {
    ast_sip_unregister_service(&filter_module_tsx);
    ast_sip_unregister_service(&filter_module_transport);
    ast_sip_unregister_supplement(&filter_supplement);
    ast_sip_session_unregister_supplement(&filter_session_supplement);
 }
ast_res_pjsip_cleanup_options_handling()
void ast_res_pjsip_cleanup_options_handling (void)
Definition at line 2835 of file pjsip_options.c.
References ao2_cleanup, ARRAY_LEN, ast_cli_unregister_multiple(), ast_log, ast_manager_unregister(), ast_serializer_shutdown_group_join(), ast_sip_get_pjsip_endpoint(), ast_sip_get_sorcery(), ast_sip_push_task_wait_serializer(), ast_sip_unregister_endpoint_formatter(), ast_sorcery_observer_remove(), ast_taskprocessor_unreference(), LOG_WARNING, management_serializer, MAX_UNLOAD_TIMEOUT_TIME, NULL, options_module, and sip_options_cleanup_task().
Referenced by ast_res_pjsip_init_options_handling(), and unload_pjsip().
 {
    int remaining;
    struct ast_taskprocessor *mgmt_serializer;
    ast_cli_unregister_multiple(cli_options, ARRAY_LEN(cli_options));
    ast_manager_unregister("PJSIPQualify");
    ast_manager_unregister("PJSIPShowContacts");
    ast_sip_unregister_endpoint_formatter(&contact_status_formatter);
    ast_sorcery_observer_remove(ast_sip_get_sorcery(), "contact",
       &contact_observer_callbacks);
    ast_sorcery_observer_remove(ast_sip_get_sorcery(), "aor",
       &aor_observer_callbacks);
    ast_sorcery_observer_remove(ast_sip_get_sorcery(), "endpoint",
       &endpoint_observer_callbacks);
    mgmt_serializer = management_serializer;
    management_serializer = NULL;
    if (mgmt_serializer) {
       ast_sip_push_task_wait_serializer(mgmt_serializer, sip_options_cleanup_task, NULL);
    }
    remaining = ast_serializer_shutdown_group_join(shutdown_group,
       MAX_UNLOAD_TIMEOUT_TIME);
    if (remaining) {
       ast_log(LOG_WARNING, "Cleanup incomplete. Could not stop %d AORs.\n",
          remaining);
    }
    ao2_cleanup(shutdown_group);
    shutdown_group = NULL;
    if (mgmt_serializer) {
       ast_taskprocessor_unreference(mgmt_serializer);
    }
    ao2_cleanup(sip_options_aors);
    sip_options_aors = NULL;
    ao2_cleanup(sip_options_contact_statuses);
    sip_options_contact_statuses = NULL;
    ao2_cleanup(sip_options_endpoint_state_compositors);
    sip_options_endpoint_state_compositors = NULL;
    pjsip_endpt_unregister_module(ast_sip_get_pjsip_endpoint(), &options_module);
 }
ast_res_pjsip_destroy_configuration()
void ast_res_pjsip_destroy_configuration (void)
Definition at line 2219 of file pjsip_configuration.c.
References AMI_SHOW_ENDPOINT, AMI_SHOW_ENDPOINTS, ao2_cleanup, ARRAY_LEN, ast_cli_unregister_multiple(), ast_manager_unregister(), ast_sip_destroy_cli(), ast_sip_destroy_sorcery_auth(), ast_sip_destroy_sorcery_global(), ast_sip_destroy_sorcery_location(), ast_sip_destroy_sorcery_transport(), ast_sip_unregister_cli_formatter(), ast_sorcery_unref, NULL, and stasis_unsubscribe_and_join().
Referenced by unload_pjsip().
 {
    if (!sip_sorcery) {
       return;
    }
    acl_change_sub = stasis_unsubscribe_and_join(acl_change_sub);
    ast_sip_destroy_sorcery_global();
    ast_sip_destroy_sorcery_location();
    ast_sip_destroy_sorcery_auth();
    ast_sip_destroy_sorcery_transport();
    ast_sorcery_unref(sip_sorcery);
    sip_sorcery = NULL;
    ast_manager_unregister(AMI_SHOW_ENDPOINT);
    ast_manager_unregister(AMI_SHOW_ENDPOINTS);
    ast_cli_unregister_multiple(cli_commands, ARRAY_LEN(cli_commands));
    ast_sip_unregister_cli_formatter(endpoint_formatter);
    ast_sip_destroy_cli();
    ao2_cleanup(persistent_endpoints);
    persistent_endpoints = NULL;
 }
ast_res_pjsip_find_or_create_contact_status()
struct ast_sip_contact_status* ast_res_pjsip_find_or_create_contact_status (const struct ast_sip_contact * contact)
Definition at line 462 of file pjsip_options.c.
References ao2_find, ao2_link_flags, ao2_lock, ao2_ref, ao2_unlock, ast_sip_contact::aor, ast_sip_contact_status::aor, ast_assert, ast_sip_get_contact_status_label(), ast_sorcery_object_get_id(), AST_STATSD_GAUGE, ast_statsd_log_string_va(), ast_string_field_set, CREATED, ast_sip_contact_status::last_status, NULL, OBJ_NOLOCK, OBJ_SEARCH_KEY, ast_sip_contact_status::rtt, sip_contact_status_alloc(), sip_options_contact_status_update(), ast_sip_contact_status::status, ast_sip_contact::uri, and ast_sip_contact_status::uri.
Referenced by contact_apply_handler(), permanent_uri_handler(), sip_options_contact_add_task(), sip_options_contact_status_available_count(), sip_options_qualify_contact(), sip_options_set_contact_status_qualified(), and sip_options_set_contact_status_unqualified().
 {
    struct ast_sip_contact_status *contact_status;
    int res;
    /*
     * At startup a contact status can be retrieved when static contacts
     * are themselves being setup.  This happens before we are fully setup.
     * Since we don't actually trigger qualify or anything as a result it
     * is safe to do so.  They'll just get back a contact status that will
     * be updated later.  At this time they only care that the contact
     * status gets created for the static contact anyway.
     */
    if (!sip_options_contact_statuses) {
       /*
        * We haven't been pre-initialized or we are shutting down.
        * Neither situation should happen.
        */
       ast_assert(0);
       return NULL;
    }
    ao2_lock(sip_options_contact_statuses);
    /* If contact status for this contact already exists just return it */
    contact_status = ao2_find(sip_options_contact_statuses,
       ast_sorcery_object_get_id(contact), OBJ_SEARCH_KEY | OBJ_NOLOCK);
    if (contact_status) {
       ao2_unlock(sip_options_contact_statuses);
       return contact_status;
    }
    /* Otherwise we have to create and store a new contact status */
    contact_status = sip_contact_status_alloc(ast_sorcery_object_get_id(contact));
    if (!contact_status) {
       ao2_unlock(sip_options_contact_statuses);
       return NULL;
    }
    contact_status->rtt = 0;
    contact_status->status = CREATED;
    contact_status->last_status = CREATED;
    res = ast_string_field_set(contact_status, uri, contact->uri);
    res |= ast_string_field_set(contact_status, aor, contact->aor);
    if (res) {
       ao2_unlock(sip_options_contact_statuses);
       ao2_ref(contact_status, -1);
       return NULL;
    }
    ao2_link_flags(sip_options_contact_statuses, contact_status, OBJ_NOLOCK);
    ao2_unlock(sip_options_contact_statuses);
    ast_statsd_log_string_va("PJSIP.contacts.states.%s", AST_STATSD_GAUGE,
       "+1", 1.0, ast_sip_get_contact_status_label(contact_status->status));
    sip_options_contact_status_update(contact_status);
    return contact_status;
 }
ast_res_pjsip_init_contact_transports()
int ast_res_pjsip_init_contact_transports (void)
ast_res_pjsip_init_message_filter()
int ast_res_pjsip_init_message_filter (void)
Definition at line 573 of file pjsip_message_filter.c.
References ast_log, ast_res_pjsip_cleanup_message_filter(), ast_sip_register_service(), ast_sip_register_supplement(), ast_sip_session_register_supplement, filter_module_transport, filter_module_tsx, and LOG_ERROR.
Referenced by load_module().
 {
    ast_sip_session_register_supplement(&filter_session_supplement);
    ast_sip_register_supplement(&filter_supplement);
    if (ast_sip_register_service(&filter_module_transport)) {
       ast_log(LOG_ERROR, "Could not register message filter module for incoming and outgoing requests\n");
       ast_res_pjsip_cleanup_message_filter();
       return -1;
    }
    if (ast_sip_register_service(&filter_module_tsx)) {
       ast_log(LOG_ERROR, "Could not register message filter module for incoming and outgoing requests\n");
       ast_res_pjsip_cleanup_message_filter();
       return -1;
    }
    return 0;
 }
ast_res_pjsip_init_options_handling()
int ast_res_pjsip_init_options_handling (int reload)
Definition at line 2918 of file pjsip_options.c.
References ami_show_contacts(), ami_sip_qualify(), AO2_ALLOC_OPT_LOCK_RWLOCK, ao2_container_alloc_hash, AOR_BUCKETS, ARRAY_LEN, ast_cli_register_multiple, ast_manager_register_xml, ast_res_pjsip_cleanup_options_handling(), ast_sip_create_serializer(), ast_sip_get_pjsip_endpoint(), ast_sip_push_task_wait_serializer(), ast_sip_register_endpoint_formatter(), ast_taskprocessor_alert_set_levels(), AST_TASKPROCESSOR_HIGH_WATER_LEVEL, ENDPOINT_STATE_COMPOSITOR_BUCKETS, EVENT_FLAG_REPORTING, EVENT_FLAG_SYSTEM, NULL, options_module, sip_options_init_task(), and sip_options_synchronize().
Referenced by load_module(), and reload_configuration_task().
 {
    struct ast_taskprocessor *mgmt_serializer;
    static const pj_str_t STR_OPTIONS = { "OPTIONS", 7 };
    if (reload) {
       sip_options_synchronize(1);
       return 0;
    }
    if (pjsip_endpt_register_module(ast_sip_get_pjsip_endpoint(), &options_module)
       != PJ_SUCCESS) {
       return -1;
    }
    if (pjsip_endpt_add_capability(ast_sip_get_pjsip_endpoint(), NULL, PJSIP_H_ALLOW,
       NULL, 1, &STR_OPTIONS) != PJ_SUCCESS) {
       ast_res_pjsip_cleanup_options_handling();
       return -1;
    }
    sip_options_aors = ao2_container_alloc_hash(AO2_ALLOC_OPT_LOCK_RWLOCK, 0, AOR_BUCKETS,
       sip_options_aor_hash_fn, NULL, sip_options_aor_cmp_fn);
    if (!sip_options_aors) {
       ast_res_pjsip_cleanup_options_handling();
       return -1;
    }
    sip_options_endpoint_state_compositors =
       ao2_container_alloc_hash(AO2_ALLOC_OPT_LOCK_RWLOCK, 0,
          ENDPOINT_STATE_COMPOSITOR_BUCKETS,
          sip_options_endpoint_state_compositor_hash_fn, NULL,
          sip_options_endpoint_state_compositor_cmp_fn);
    if (!sip_options_endpoint_state_compositors) {
       ast_res_pjsip_cleanup_options_handling();
       return -1;
    }
    mgmt_serializer = ast_sip_create_serializer("pjsip/options/manage");
    if (!mgmt_serializer) {
       ast_res_pjsip_cleanup_options_handling();
       return -1;
    }
    /*
     * Set the water mark levels high because we can get a flood of
     * contact status updates from sip_options_synchronize() that
     * quickly clears on initial load or reload.
     */
    ast_taskprocessor_alert_set_levels(mgmt_serializer, -1,
       10 * AST_TASKPROCESSOR_HIGH_WATER_LEVEL);
    /*
     * We make sure that the environment is completely setup before we allow
     * any other threads to post contact_status updates to the
     * management_serializer.
     */
    if (ast_sip_push_task_wait_serializer(mgmt_serializer, sip_options_init_task,
       mgmt_serializer)) {
       /* Set management_serializer in case pushing the task actually failed. */
       management_serializer = mgmt_serializer;
       ast_res_pjsip_cleanup_options_handling();
       return -1;
    }
    ast_sip_register_endpoint_formatter(&contact_status_formatter);
    ast_manager_register_xml("PJSIPQualify", EVENT_FLAG_SYSTEM | EVENT_FLAG_REPORTING,
       ami_sip_qualify);
    ast_manager_register_xml("PJSIPShowContacts", EVENT_FLAG_SYSTEM, ami_show_contacts);
    ast_cli_register_multiple(cli_options, ARRAY_LEN(cli_options));
    return 0;
 }
ast_res_pjsip_initialize_configuration()
int ast_res_pjsip_initialize_configuration (void)
Definition at line 1973 of file pjsip_configuration.c.
References accountcode, acl_change_stasis_cb(), acl_to_str(), AMI_SHOW_ENDPOINT, ami_show_endpoint(), AMI_SHOW_ENDPOINTS, ami_show_endpoints(), ao2_alloc, AO2_ALLOC_OPT_LOCK_MUTEX, ao2_container_alloc_hash, ARRAY_LEN, ast_cli_register_multiple, ast_log, ast_manager_register_xml, ast_named_acl_change_type(), ast_security_topic(), ast_sip_endpoint_alloc(), ast_sip_initialize_cli(), ast_sip_initialize_sorcery_auth(), ast_sip_initialize_sorcery_domain_alias(), ast_sip_initialize_sorcery_global(), ast_sip_initialize_sorcery_location(), ast_sip_initialize_sorcery_transport(), ast_sip_location_prune_boot_contacts(), ast_sip_register_cli_formatter(), ast_sorcery_apply_default, ast_sorcery_internal_object_register, ast_sorcery_load(), ast_sorcery_object_field_register, ast_sorcery_object_field_register_alias, ast_sorcery_object_field_register_custom, ast_sorcery_object_get_id(), ast_sorcery_object_register, ast_sorcery_observer_add(), ast_sorcery_open, ast_sorcery_unref, call_offer_pref_handler(), caller_id_handler(), caller_id_privacy_handler(), caller_id_privacy_to_str(), caller_id_tag_handler(), caller_id_tag_to_str(), caller_id_to_str(), callgroup_to_str(), CHARFLDSET, cli_endpoint_get_container(), cli_endpoint_iterate(), cli_endpoint_print_body(), cli_endpoint_print_header(), cli_endpoint_retrieve_by_id(), codec_prefs_handler(), connected_line_method_handler(), connected_line_method_to_str(), contact_acl_to_str(), contact_user_handler(), contact_user_to_str(), context, ast_sip_endpoint::context, direct_media_glare_mitigation_handler(), direct_media_glare_mitigation_to_str(), direct_media_method_handler(), direct_media_method_to_str(), dtls_handler(), dtlsautogeneratecert_to_str(), dtlscafile_to_str(), dtlscapath_to_str(), dtlscertfile_to_str(), dtlscipher_to_str(), dtlsfingerprint_to_str(), dtlsprivatekey_to_str(), dtlsrekey_to_str(), dtlssetup_to_str(), dtlsverify_to_str(), dtmf_handler(), dtmf_to_str(), endpoint_acl_handler(), EVENT_FLAG_SYSTEM, FLDSET, from_user_handler(), from_user_to_str(), ast_sip_endpoint::fromuser, ast_sip_cli_formatter_entry::get_container, ast_sip_cli_formatter_entry::get_id, group_handler(), ident_handler(), ident_to_str(), inbound_auth_handler(), inbound_auths_to_str(), incoming_answer_codec_prefs_to_str(), incoming_call_offer_pref_to_str(), incoming_offer_codec_prefs_to_str(), sip_to_pjsip::info(), ast_sip_cli_formatter_entry::iterate, language, load_all_endpoints(), LOG_ERROR, media_encryption_handler(), media_encryption_to_str(), mohsuggest, ast_sip_cli_formatter_entry::name, named_callgroups_to_str(), named_groups_handler(), named_pickupgroups_to_str(), nat, ast_sip_endpoint::nat, NULL, OPT_BOOL_T, OPT_CHAR_ARRAY_T, OPT_CODEC_T, OPT_NOOP_T, OPT_STRINGFIELD_T, OPT_UINT_T, OPT_YESNO_T, outbound_auth_handler(), outbound_auths_to_str(), outgoing_answer_codec_prefs_to_str(), outgoing_call_offer_pref_to_str(), outgoing_offer_codec_prefs_to_str(), PERSISTENT_BUCKETS, persistent_endpoint_cmp(), persistent_endpoint_hash(), pickupgroup_to_str(), prack_handler(), prack_to_str(), ast_sip_cli_formatter_entry::print_body, ast_sip_cli_formatter_entry::print_header, redirect_handler(), ast_sip_cli_formatter_entry::retrieve_by_id, set_var_handler(), set_var_to_str(), set_var_to_vl(), sip_endpoint_apply_handler(), sip_nat_hook_alloc(), stasis_subscribe, stasis_subscription_accept_message_type(), STASIS_SUBSCRIPTION_FILTER_SELECTIVE, stasis_subscription_set_filter(), STRFLDSET, t38udptl_ec_handler(), t38udptl_ec_to_str(), timers_handler(), timers_to_str(), tos_audio_to_str(), tos_handler(), tos_video_to_str(), voicemail_extension_handler(), and voicemail_extension_to_str().
Referenced by load_module().
 {
    if (ast_manager_register_xml(AMI_SHOW_ENDPOINTS, EVENT_FLAG_SYSTEM, ami_show_endpoints) ||
        ast_manager_register_xml(AMI_SHOW_ENDPOINT, EVENT_FLAG_SYSTEM, ami_show_endpoint)) {
       return -1;
    }
    persistent_endpoints = ao2_container_alloc_hash(AO2_ALLOC_OPT_LOCK_MUTEX, 0,
       PERSISTENT_BUCKETS, persistent_endpoint_hash, NULL, persistent_endpoint_cmp);
    if (!persistent_endpoints) {
       return -1;
    }
    if (!(sip_sorcery = ast_sorcery_open())) {
       ast_log(LOG_ERROR, "Failed to open SIP sorcery failed to open\n");
       return -1;
    }
    ast_sip_initialize_cli();
    if (ast_sip_initialize_sorcery_auth()) {
       ast_log(LOG_ERROR, "Failed to register SIP authentication support\n");
       ast_sorcery_unref(sip_sorcery);
       sip_sorcery = NULL;
       return -1;
    }
    ast_sorcery_apply_default(sip_sorcery, "endpoint", "config", "pjsip.conf,criteria=type=endpoint");
    ast_sorcery_apply_default(sip_sorcery, "nat_hook", "memory", NULL);
    if (ast_sorcery_object_register(sip_sorcery, "endpoint", ast_sip_endpoint_alloc, NULL, sip_endpoint_apply_handler)) {
       ast_log(LOG_ERROR, "Failed to register SIP endpoint object with sorcery\n");
       ast_sorcery_unref(sip_sorcery);
       sip_sorcery = NULL;
       return -1;
    }
    if (ast_sorcery_internal_object_register(sip_sorcery, "nat_hook", sip_nat_hook_alloc, NULL, NULL)) {
       ast_log(LOG_ERROR, "Failed to register nat_hook\n");
    }
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "type", "", OPT_NOOP_T, 0, 0);
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "context", "default", OPT_STRINGFIELD_T, 0, STRFLDSET(struct ast_sip_endpoint, context));
    ast_sorcery_object_field_register_alias(sip_sorcery, "endpoint", "disallow", "", OPT_CODEC_T, 0, FLDSET(struct ast_sip_endpoint, media.codecs));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "allow", "", OPT_CODEC_T, 1, FLDSET(struct ast_sip_endpoint, media.codecs));
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "dtmf_mode", "rfc4733", dtmf_handler, dtmf_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "rtp_ipv6", "no", OPT_BOOL_T, 1, FLDSET(struct ast_sip_endpoint, media.rtp.ipv6));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "rtp_symmetric", "no", OPT_BOOL_T, 1, FLDSET(struct ast_sip_endpoint, media.rtp.symmetric));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "ice_support", "no", OPT_BOOL_T, 1, FLDSET(struct ast_sip_endpoint, media.rtp.ice_support));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "use_ptime", "no", OPT_BOOL_T, 1, FLDSET(struct ast_sip_endpoint, media.rtp.use_ptime));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "force_rport", "yes", OPT_BOOL_T, 1, FLDSET(struct ast_sip_endpoint, nat.force_rport));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "rewrite_contact", "no", OPT_BOOL_T, 1, FLDSET(struct ast_sip_endpoint, nat.rewrite_contact));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "transport", "", OPT_STRINGFIELD_T, 0, STRFLDSET(struct ast_sip_endpoint, transport));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "outbound_proxy", "", OPT_STRINGFIELD_T, 0, STRFLDSET(struct ast_sip_endpoint, outbound_proxy));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "moh_suggest", "default", OPT_STRINGFIELD_T, 0, STRFLDSET(struct ast_sip_endpoint, mohsuggest));
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "100rel", "yes", prack_handler, prack_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "timers", "yes", timers_handler, timers_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "timers_min_se", "90", OPT_UINT_T, 0, FLDSET(struct ast_sip_endpoint, extensions.timer.min_se));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "timers_sess_expires", "1800", OPT_UINT_T, 0, FLDSET(struct ast_sip_endpoint, extensions.timer.sess_expires));
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "auth", "", inbound_auth_handler, inbound_auths_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "outbound_auth", "", outbound_auth_handler, outbound_auths_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "aors", "", OPT_STRINGFIELD_T, 0, STRFLDSET(struct ast_sip_endpoint, aors));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "media_address", "", OPT_STRINGFIELD_T, 0, STRFLDSET(struct ast_sip_endpoint, media.address));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "bind_rtp_to_media_address", "no", OPT_BOOL_T, 1, STRFLDSET(struct ast_sip_endpoint, media.bind_rtp_to_media_address));
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "identify_by", "username,ip", ident_handler, ident_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "direct_media", "yes", OPT_BOOL_T, 1, FLDSET(struct ast_sip_endpoint, media.direct_media.enabled));
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "direct_media_method", "invite", direct_media_method_handler, direct_media_method_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "trust_connected_line", "yes", OPT_YESNO_T, 1, FLDSET(struct ast_sip_endpoint, id.trust_connected_line));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "send_connected_line", "yes", OPT_YESNO_T, 1, FLDSET(struct ast_sip_endpoint, id.send_connected_line));
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "connected_line_method", "invite", connected_line_method_handler, connected_line_method_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "direct_media_glare_mitigation", "none", direct_media_glare_mitigation_handler, direct_media_glare_mitigation_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "disable_direct_media_on_nat", "no", OPT_BOOL_T, 1, FLDSET(struct ast_sip_endpoint, media.direct_media.disable_on_nat));
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "callerid", "", caller_id_handler, caller_id_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "callerid_privacy", "allowed_not_screened", caller_id_privacy_handler, caller_id_privacy_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "callerid_tag", "", caller_id_tag_handler, caller_id_tag_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "trust_id_inbound", "no", OPT_BOOL_T, 1, FLDSET(struct ast_sip_endpoint, id.trust_inbound));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "trust_id_outbound", "no", OPT_BOOL_T, 1, FLDSET(struct ast_sip_endpoint, id.trust_outbound));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "send_pai", "no", OPT_BOOL_T, 1, FLDSET(struct ast_sip_endpoint, id.send_pai));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "send_rpid", "no", OPT_BOOL_T, 1, FLDSET(struct ast_sip_endpoint, id.send_rpid));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "rpid_immediate", "no", OPT_BOOL_T, 1, FLDSET(struct ast_sip_endpoint, id.rpid_immediate));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "send_diversion", "yes", OPT_BOOL_T, 1, FLDSET(struct ast_sip_endpoint, id.send_diversion));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "send_history_info", "no", OPT_BOOL_T, 1, FLDSET(struct ast_sip_endpoint, id.send_history_info));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "mailboxes", "", OPT_STRINGFIELD_T, 0, STRFLDSET(struct ast_sip_endpoint, subscription.mwi.mailboxes));
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "voicemail_extension", "", voicemail_extension_handler, voicemail_extension_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "aggregate_mwi", "yes", OPT_BOOL_T, 1, FLDSET(struct ast_sip_endpoint, subscription.mwi.aggregate));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "mwi_subscribe_replaces_unsolicited", "no", OPT_YESNO_T, 1, FLDSET(struct ast_sip_endpoint, subscription.mwi.subscribe_replaces_unsolicited));
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "media_encryption", "no", media_encryption_handler, media_encryption_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "use_avpf", "no", OPT_BOOL_T, 1, FLDSET(struct ast_sip_endpoint, media.rtp.use_avpf));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "force_avp", "no", OPT_BOOL_T, 1, FLDSET(struct ast_sip_endpoint, media.rtp.force_avp));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "media_use_received_transport", "no", OPT_BOOL_T, 1, FLDSET(struct ast_sip_endpoint, media.rtp.use_received_transport));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "rtp_keepalive", "0", OPT_UINT_T, 0, FLDSET(struct ast_sip_endpoint, media.rtp.keepalive));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "rtp_timeout", "0", OPT_UINT_T, 0, FLDSET(struct ast_sip_endpoint, media.rtp.timeout));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "rtp_timeout_hold", "0", OPT_UINT_T, 0, FLDSET(struct ast_sip_endpoint, media.rtp.timeout_hold));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "one_touch_recording", "no", OPT_BOOL_T, 1, FLDSET(struct ast_sip_endpoint, info.recording.enabled));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "inband_progress", "no", OPT_BOOL_T, 1, FLDSET(struct ast_sip_endpoint, inband_progress));
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "call_group", "", group_handler, callgroup_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "pickup_group", "", group_handler, pickupgroup_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "named_call_group", "", named_groups_handler, named_callgroups_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "named_pickup_group", "", named_groups_handler, named_pickupgroups_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "device_state_busy_at", "0", OPT_UINT_T, 0, FLDSET(struct ast_sip_endpoint, devicestate_busy_at));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "t38_udptl", "no", OPT_BOOL_T, 1, FLDSET(struct ast_sip_endpoint, media.t38.enabled));
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "t38_udptl_ec", "none", t38udptl_ec_handler, t38udptl_ec_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "t38_udptl_maxdatagram", "0", OPT_UINT_T, 0, FLDSET(struct ast_sip_endpoint, media.t38.maxdatagram));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "fax_detect", "no", OPT_BOOL_T, 1, FLDSET(struct ast_sip_endpoint, faxdetect));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "fax_detect_timeout", "0", OPT_UINT_T, 0, FLDSET(struct ast_sip_endpoint, faxdetect_timeout));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "t38_udptl_nat", "no", OPT_BOOL_T, 1, FLDSET(struct ast_sip_endpoint, media.t38.nat));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "t38_udptl_ipv6", "no", OPT_BOOL_T, 1, FLDSET(struct ast_sip_endpoint, media.t38.ipv6));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "tone_zone", "", OPT_STRINGFIELD_T, 0, STRFLDSET(struct ast_sip_endpoint, zone));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "language", "", OPT_STRINGFIELD_T, 0, STRFLDSET(struct ast_sip_endpoint, language));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "record_on_feature", "automixmon", OPT_STRINGFIELD_T, 0, STRFLDSET(struct ast_sip_endpoint, info.recording.onfeature));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "record_off_feature", "automixmon", OPT_STRINGFIELD_T, 0, STRFLDSET(struct ast_sip_endpoint, info.recording.offfeature));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "allow_transfer", "yes", OPT_BOOL_T, 1, FLDSET(struct ast_sip_endpoint, allowtransfer));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "user_eq_phone", "no", OPT_BOOL_T, 1, FLDSET(struct ast_sip_endpoint, usereqphone));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "moh_passthrough", "no", OPT_BOOL_T, 1, FLDSET(struct ast_sip_endpoint, moh_passthrough));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "sdp_owner", "-", OPT_STRINGFIELD_T, 0, STRFLDSET(struct ast_sip_endpoint, media.sdpowner));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "sdp_session", "Asterisk", OPT_STRINGFIELD_T, 0, STRFLDSET(struct ast_sip_endpoint, media.sdpsession));
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "tos_audio", "0", tos_handler, tos_audio_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "tos_video", "0", tos_handler, tos_video_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "cos_audio", "0", OPT_UINT_T, 0, FLDSET(struct ast_sip_endpoint, media.cos_audio));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "cos_video", "0", OPT_UINT_T, 0, FLDSET(struct ast_sip_endpoint, media.cos_video));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "allow_subscribe", "yes", OPT_BOOL_T, 1, FLDSET(struct ast_sip_endpoint, subscription.allow));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "sub_min_expiry", "0", OPT_UINT_T, 0, FLDSET(struct ast_sip_endpoint, subscription.minexpiry));
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "from_user", "", from_user_handler, from_user_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "from_domain", "", OPT_STRINGFIELD_T, 0, STRFLDSET(struct ast_sip_endpoint, fromdomain));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "mwi_from_user", "", OPT_STRINGFIELD_T, 0, STRFLDSET(struct ast_sip_endpoint, subscription.mwi.fromuser));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "rtp_engine", "asterisk", OPT_STRINGFIELD_T, 0, STRFLDSET(struct ast_sip_endpoint, media.rtp.engine));
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "dtls_verify", "no", dtls_handler, dtlsverify_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "dtls_rekey", "0", dtls_handler, dtlsrekey_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "dtls_auto_generate_cert", "no", dtls_handler, dtlsautogeneratecert_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "dtls_cert_file", "", dtls_handler, dtlscertfile_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "dtls_private_key", "", dtls_handler, dtlsprivatekey_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "dtls_cipher", "", dtls_handler, dtlscipher_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "dtls_ca_file", "", dtls_handler, dtlscafile_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "dtls_ca_path", "", dtls_handler, dtlscapath_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "dtls_setup", "", dtls_handler, dtlssetup_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "dtls_fingerprint", "", dtls_handler, dtlsfingerprint_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "srtp_tag_32", "no", OPT_BOOL_T, 1, FLDSET(struct ast_sip_endpoint, media.rtp.srtp_tag_32));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "media_encryption_optimistic", "no", OPT_BOOL_T, 1, FLDSET(struct ast_sip_endpoint, media.rtp.encryption_optimistic));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "g726_non_standard", "no", OPT_BOOL_T, 1, FLDSET(struct ast_sip_endpoint, media.g726_non_standard));
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "redirect_method", "user", redirect_handler, NULL, NULL, 0, 0);
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "set_var", "", set_var_handler, set_var_to_str, set_var_to_vl, 0, 0);
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "message_context", "", OPT_STRINGFIELD_T, 0, STRFLDSET(struct ast_sip_endpoint, message_context));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "accountcode", "", OPT_STRINGFIELD_T, 0, STRFLDSET(struct ast_sip_endpoint, accountcode));
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "deny", "", endpoint_acl_handler, NULL, NULL, 0, 0);
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "permit", "", endpoint_acl_handler, NULL, NULL, 0, 0);
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "acl", "", endpoint_acl_handler, acl_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "contact_deny", "", endpoint_acl_handler, NULL, NULL, 0, 0);
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "contact_permit", "", endpoint_acl_handler, NULL, NULL, 0, 0);
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "contact_acl", "", endpoint_acl_handler, contact_acl_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "subscribe_context", "", OPT_CHAR_ARRAY_T, 0, CHARFLDSET(struct ast_sip_endpoint, subscription.context));
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "contact_user", "", contact_user_handler, contact_user_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "preferred_codec_only", "no", OPT_BOOL_T, 1, FLDSET(struct ast_sip_endpoint, preferred_codec_only));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "asymmetric_rtp_codec", "no", OPT_BOOL_T, 1, FLDSET(struct ast_sip_endpoint, asymmetric_rtp_codec));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "rtcp_mux", "no", OPT_BOOL_T, 1, FLDSET(struct ast_sip_endpoint, media.rtcp_mux));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "allow_overlap", "yes", OPT_BOOL_T, 1, FLDSET(struct ast_sip_endpoint, allow_overlap));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "refer_blind_progress", "yes", OPT_BOOL_T, 1, FLDSET(struct ast_sip_endpoint, refer_blind_progress));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "notify_early_inuse_ringing", "no", OPT_BOOL_T, 1, FLDSET(struct ast_sip_endpoint, notify_early_inuse_ringing));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "max_audio_streams", "1", OPT_UINT_T, 0, FLDSET(struct ast_sip_endpoint, media.max_audio_streams));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "max_video_streams", "1", OPT_UINT_T, 0, FLDSET(struct ast_sip_endpoint, media.max_video_streams));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "bundle", "no", OPT_BOOL_T, 1, FLDSET(struct ast_sip_endpoint, media.bundle));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "webrtc", "no", OPT_YESNO_T, 1, FLDSET(struct ast_sip_endpoint, media.webrtc));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "incoming_mwi_mailbox", "", OPT_STRINGFIELD_T, 0, STRFLDSET(struct ast_sip_endpoint, incoming_mwi_mailbox));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "follow_early_media_fork", "yes", OPT_BOOL_T, 1, FLDSET(struct ast_sip_endpoint, media.rtp.follow_early_media_fork));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "accept_multiple_sdp_answers", "no", OPT_BOOL_T, 1, FLDSET(struct ast_sip_endpoint, media.rtp.accept_multiple_sdp_answers));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "suppress_q850_reason_headers", "no", OPT_BOOL_T, 1, FLDSET(struct ast_sip_endpoint, suppress_q850_reason_headers));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "ignore_183_without_sdp", "no", OPT_BOOL_T, 1, FLDSET(struct ast_sip_endpoint, ignore_183_without_sdp));
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "incoming_call_offer_pref", "local",
       call_offer_pref_handler, incoming_call_offer_pref_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "outgoing_call_offer_pref", "remote_merge",
       call_offer_pref_handler, outgoing_call_offer_pref_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "codec_prefs_incoming_offer",
       "prefer: pending, operation: intersect, keep: all, transcode: allow",
       codec_prefs_handler, incoming_offer_codec_prefs_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "codec_prefs_outgoing_offer",
       "prefer: pending, operation: union, keep: all, transcode: allow",
       codec_prefs_handler, outgoing_offer_codec_prefs_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "codec_prefs_incoming_answer",
       "prefer: pending, operation: intersect, keep: all",
       codec_prefs_handler, incoming_answer_codec_prefs_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register_custom(sip_sorcery, "endpoint", "codec_prefs_outgoing_answer",
       "prefer: pending, operation: intersect, keep: all",
       codec_prefs_handler, outgoing_answer_codec_prefs_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "stir_shaken", "no", OPT_BOOL_T, 1, FLDSET(struct ast_sip_endpoint, stir_shaken));
    ast_sorcery_object_field_register(sip_sorcery, "endpoint", "allow_unauthenticated_options", "no", OPT_BOOL_T, 1, FLDSET(struct ast_sip_endpoint, allow_unauthenticated_options));
    if (ast_sip_initialize_sorcery_transport()) {
       ast_log(LOG_ERROR, "Failed to register SIP transport support with sorcery\n");
       ast_sorcery_unref(sip_sorcery);
       sip_sorcery = NULL;
       return -1;
    }
    if (ast_sip_initialize_sorcery_location()) {
       ast_log(LOG_ERROR, "Failed to register SIP location support with sorcery\n");
       ast_sorcery_unref(sip_sorcery);
       sip_sorcery = NULL;
       return -1;
    }
    ast_sorcery_observer_add(sip_sorcery, "endpoint", &endpoint_observers);
    if (ast_sip_initialize_sorcery_domain_alias()) {
       ast_log(LOG_ERROR, "Failed to register SIP domain aliases support with sorcery\n");
       ast_sorcery_unref(sip_sorcery);
       sip_sorcery = NULL;
       return -1;
    }
    if (ast_sip_initialize_sorcery_global()) {
       ast_log(LOG_ERROR, "Failed to register SIP Global support\n");
       ast_sorcery_unref(sip_sorcery);
       sip_sorcery = NULL;
       return -1;
    }
    endpoint_formatter = ao2_alloc(sizeof(struct ast_sip_cli_formatter_entry), NULL);
    if (!endpoint_formatter) {
       ast_log(LOG_ERROR, "Unable to allocate memory for endpoint_formatter\n");
       ast_sorcery_unref(sip_sorcery);
       sip_sorcery = NULL;
       return -1;
    }
    endpoint_formatter->name = "endpoint";
    endpoint_formatter->print_header = cli_endpoint_print_header;
    endpoint_formatter->print_body = cli_endpoint_print_body;
    endpoint_formatter->get_container = cli_endpoint_get_container;
    endpoint_formatter->iterate = cli_endpoint_iterate;
    endpoint_formatter->retrieve_by_id = cli_endpoint_retrieve_by_id;
    endpoint_formatter->get_id = ast_sorcery_object_get_id;
    ast_sip_register_cli_formatter(endpoint_formatter);
    ast_cli_register_multiple(cli_commands, ARRAY_LEN(cli_commands));
    ast_sorcery_load(sip_sorcery);
    load_all_endpoints();
    ast_sip_location_prune_boot_contacts();
    acl_change_sub = stasis_subscribe(ast_security_topic(), acl_change_stasis_cb, NULL);
    stasis_subscription_accept_message_type(acl_change_sub, ast_named_acl_change_type());
    stasis_subscription_set_filter(acl_change_sub, STASIS_SUBSCRIPTION_FILTER_SELECTIVE);
    return 0;
 }
ast_res_pjsip_preinit_options_handling()
int ast_res_pjsip_preinit_options_handling (void)
Definition at line 2912 of file pjsip_options.c.
References sip_options_contact_statuses_alloc().
Referenced by load_module().
 {
    sip_options_contact_statuses = sip_options_contact_statuses_alloc();
    return sip_options_contact_statuses ? 0 : -1;
 }
ast_res_pjsip_reload_configuration()
int ast_res_pjsip_reload_configuration (void)
Definition at line 2241 of file pjsip_configuration.c.
References ast_sorcery_reload().
Referenced by reload_configuration_task().
 {
    if (sip_sorcery) {
       ast_sorcery_reload(sip_sorcery);
    }
    return 0;
 }
ast_sip_destroy_cli()
void ast_sip_destroy_cli (void)
Definition at line 375 of file pjsip_cli.c.
References ao2_ref, ARRAY_LEN, and ast_cli_unregister_multiple().
Referenced by ast_res_pjsip_destroy_configuration().
 {
    ast_cli_unregister_multiple(pjsip_cli, ARRAY_LEN(pjsip_cli));
    ao2_ref(formatter_registry, -1);
 }
ast_sip_destroy_distributor()
void ast_sip_destroy_distributor (void)
Definition at line 1334 of file pjsip_distributor.c.
References ao2_cleanup, ao2_global_obj_release, ARRAY_LEN, ast_cli_unregister_multiple(), ast_sched_context_destroy(), ast_sip_get_sorcery(), ast_sip_unregister_cli_formatter(), ast_sip_unregister_service(), ast_sorcery_observer_remove(), auth_mod, distributor_mod, distributor_pool_shutdown(), and endpoint_mod.
Referenced by ast_sip_initialize_distributor(), and unload_pjsip().
 {
    ast_cli_unregister_multiple(cli_commands, ARRAY_LEN(cli_commands));
    ast_sip_unregister_cli_formatter(unid_formatter);
    ast_sip_unregister_service(&auth_mod);
    ast_sip_unregister_service(&endpoint_mod);
    ast_sip_unregister_service(&distributor_mod);
    ao2_global_obj_release(artificial_auth);
    ao2_cleanup(artificial_endpoint);
    ast_sorcery_observer_remove(ast_sip_get_sorcery(), "global", &global_observer);
    if (prune_context) {
       ast_sched_context_destroy(prune_context);
    }
    distributor_pool_shutdown();
    ao2_cleanup(dialog_associations);
    ao2_cleanup(unidentified_requests);
 }
ast_sip_destroy_global_headers()
void ast_sip_destroy_global_headers (void)
Definition at line 181 of file pjsip_global_headers.c.
References ast_sip_unregister_service(), destroy_headers(), global_header_mod, request_headers, and response_headers.
Referenced by unload_pjsip().
 {
    destroy_headers(&request_headers);
    destroy_headers(&response_headers);
    ast_sip_unregister_service(&global_header_mod);
 }
ast_sip_destroy_scheduler()
int ast_sip_destroy_scheduler (void)
Definition at line 642 of file pjsip_scheduler.c.
References ao2_cleanup, ao2_iterator_destroy(), ao2_iterator_init(), ao2_iterator_next, ao2_ref, ARRAY_LEN, ast_cli_unregister_multiple(), ast_sched_context_destroy(), ast_sip_sched_task_cancel(), and NULL.
Referenced by load_module(), and unload_module().
 {
    ast_cli_unregister_multiple(cli_commands, ARRAY_LEN(cli_commands));
    if (scheduler_context) {
       if (tasks) {
          struct ao2_iterator iter;
          struct ast_sip_sched_task *schtd;
          /* Cancel all scheduled tasks */
          iter = ao2_iterator_init(tasks, 0);
          while ((schtd = ao2_iterator_next(&iter))) {
             ast_sip_sched_task_cancel(schtd);
             ao2_ref(schtd, -1);
          }
          ao2_iterator_destroy(&iter);
       }
       ast_sched_context_destroy(scheduler_context);
       scheduler_context = NULL;
    }
    ao2_cleanup(tasks);
    tasks = NULL;
    return 0;
 }
ast_sip_destroy_sorcery_auth()
int ast_sip_destroy_sorcery_auth (void)
Definition at line 426 of file config_auth.c.
References ARRAY_LEN, ast_cli_unregister_multiple(), ast_manager_unregister(), ast_sip_unregister_cli_formatter(), and ast_sip_unregister_endpoint_formatter().
Referenced by ast_res_pjsip_destroy_configuration().
 {
    ast_cli_unregister_multiple(cli_commands, ARRAY_LEN(cli_commands));
    ast_sip_unregister_cli_formatter(cli_formatter);
    ast_sip_unregister_endpoint_formatter(&endpoint_auth_formatter);
    ast_manager_unregister("PJSIPShowAuths");
    return 0;
 }
ast_sip_destroy_sorcery_global()
int ast_sip_destroy_sorcery_global (void)
Definition at line 630 of file config_global.c.
References ao2_t_global_obj_release, ast_context_destroy_by_name(), ast_free, ast_sip_get_sorcery(), ast_sorcery_instance_observer_remove(), previous_regcontext, and sorcery.
Referenced by ast_res_pjsip_destroy_configuration().
 {
    struct ast_sorcery *sorcery = ast_sip_get_sorcery();
    ast_sorcery_instance_observer_remove(sorcery, &observer_callbacks_global);
    if (previous_regcontext) {
       ast_context_destroy_by_name(previous_regcontext, "PJSIP");
       ast_free(previous_regcontext);
    }
    ao2_t_global_obj_release(global_cfg, "Module is unloading");
    return 0;
 }
ast_sip_destroy_sorcery_location()
int ast_sip_destroy_sorcery_location (void)
Definition at line 1467 of file location.c.
References ARRAY_LEN, ast_cli_unregister_multiple(), ast_manager_unregister(), ast_sip_get_sorcery(), ast_sip_unregister_cli_formatter(), ast_sip_unregister_endpoint_formatter(), and ast_sorcery_observer_remove().
Referenced by ast_res_pjsip_destroy_configuration().
 {
    ast_sorcery_observer_remove(ast_sip_get_sorcery(), "aor", &aor_observer);
    ast_cli_unregister_multiple(cli_commands, ARRAY_LEN(cli_commands));
    ast_sip_unregister_cli_formatter(contact_formatter);
    ast_sip_unregister_cli_formatter(aor_formatter);
    ast_manager_unregister("PJSIPShowAors");
    ast_sip_unregister_endpoint_formatter(&endpoint_aor_formatter);
    return 0;
 }
ast_sip_destroy_sorcery_transport()
int ast_sip_destroy_sorcery_transport (void)
Definition at line 1692 of file config_transport.c.
References ao2_ref, ARRAY_LEN, ast_cli_unregister_multiple(), ast_sip_unregister_cli_formatter(), ast_sip_unregister_endpoint_formatter(), and NULL.
Referenced by ast_res_pjsip_destroy_configuration().
 {
    ast_cli_unregister_multiple(cli_commands, ARRAY_LEN(cli_commands));
    ast_sip_unregister_cli_formatter(cli_formatter);
    ast_sip_unregister_endpoint_formatter(&endpoint_transport_formatter);
    ao2_ref(transport_states, -1);
    transport_states = NULL;
    return 0;
 }
ast_sip_destroy_system()
void ast_sip_destroy_system (void)
Definition at line 245 of file config_system.c.
References ast_sorcery_unref.
Referenced by unload_pjsip().
 {
    ast_sorcery_unref(system_sorcery);
 }
ast_sip_destroy_transport_events()
void ast_sip_destroy_transport_events (void)
Definition at line 382 of file pjsip_transport_events.c.
References ao2_global_obj_release, ast_sip_get_pjsip_endpoint(), and tpmgr_state_callback.
Referenced by unload_pjsip().
 {
    pjsip_tpmgr *tpmgr;
    tpmgr = pjsip_endpt_get_tpmgr(ast_sip_get_pjsip_endpoint());
    if (tpmgr) {
       pjsip_tpmgr_set_state_cb(tpmgr, tpmgr_state_callback);
    }
    ao2_global_obj_release(active_transports);
 }
ast_sip_destroy_transport_management()
void ast_sip_destroy_transport_management (void)
Definition at line 410 of file pjsip_transport_management.c.
References ao2_global_obj_release, AST_PTHREADT_NULL, ast_sched_clean_by_callback(), ast_sched_context_destroy(), ast_sip_get_sorcery(), ast_sip_transport_state_unregister(), ast_sip_unregister_service(), ast_sorcery_observer_remove(), idle_monitor_module, idle_sched_cb(), idle_sched_cleanup(), keepalive_interval, keepalive_thread, and NULL.
Referenced by unload_pjsip().
 {
    if (keepalive_interval) {
       keepalive_interval = 0;
       if (keepalive_thread != AST_PTHREADT_NULL) {
          pthread_kill(keepalive_thread, SIGURG);
          pthread_join(keepalive_thread, NULL);
          keepalive_thread = AST_PTHREADT_NULL;
       }
    }
    ast_sorcery_observer_remove(ast_sip_get_sorcery(), "global", &keepalive_global_observer);
    ast_sip_transport_state_unregister(&monitored_transport_reg);
    ast_sip_unregister_service(&idle_monitor_module);
    ast_sched_clean_by_callback(sched, idle_sched_cb, idle_sched_cleanup);
    ast_sched_context_destroy(sched);
    sched = NULL;
    ao2_global_obj_release(monitored_transports);
 }
ast_sip_get_taskprocessor_overload_trigger()
enum ast_sip_taskprocessor_overload_trigger ast_sip_get_taskprocessor_overload_trigger (void)
Definition at line 492 of file config_global.c.
References ao2_ref, DEFAULT_TASKPROCESSOR_OVERLOAD_TRIGGER, get_global_cfg(), and global_config::overload_trigger.
Referenced by global_loaded().
 {
    enum ast_sip_taskprocessor_overload_trigger trigger;
    struct global_config *cfg;
    cfg = get_global_cfg();
    if (!cfg) {
       return DEFAULT_TASKPROCESSOR_OVERLOAD_TRIGGER;
    }
    trigger = cfg->overload_trigger;
    ao2_ref(cfg, -1);
    return trigger;
 }
ast_sip_global_default_outbound_endpoint()
char* ast_sip_global_default_outbound_endpoint (void)
Definition at line 217 of file config_global.c.
References ao2_ref, ast_strdup, DEFAULT_OUTBOUND_ENDPOINT, global_config::default_outbound_endpoint, get_global_cfg(), and str.
Referenced by ast_sip_default_outbound_endpoint().
 {
    char *str;
    struct global_config *cfg;
    cfg = get_global_cfg();
    if (!cfg) {
       return ast_strdup(DEFAULT_OUTBOUND_ENDPOINT);
    }
    str = ast_strdup(cfg->default_outbound_endpoint);
    ao2_ref(cfg, -1);
    return str;
 }
ast_sip_initialize_cli()
int ast_sip_initialize_cli (void)
Definition at line 360 of file pjsip_cli.c.
References AO2_ALLOC_OPT_LOCK_NOLOCK, ao2_container_alloc_hash, ARRAY_LEN, ast_cli_register_multiple, ast_log, formatter_compare(), formatter_hash(), formatter_sort(), and LOG_ERROR.
Referenced by ast_res_pjsip_initialize_configuration().
 {
    formatter_registry = ao2_container_alloc_hash(AO2_ALLOC_OPT_LOCK_NOLOCK, 0, 17,
       formatter_hash, formatter_sort, formatter_compare);
    if (!formatter_registry) {
       ast_log(LOG_ERROR, "Unable to create formatter_registry.\n");
       return -1;
    }
    ast_cli_register_multiple(pjsip_cli, ARRAY_LEN(pjsip_cli));
    return 0;
 }
ast_sip_initialize_distributor()
int ast_sip_initialize_distributor (void)
Definition at line 1260 of file pjsip_distributor.c.
References AO2_ALLOC_OPT_LOCK_NOLOCK, AO2_ALLOC_OPT_LOCK_RWLOCK, ao2_alloc_options, ao2_container_alloc_hash, ARRAY_LEN, ast_cli_register_multiple, ast_log, ast_sched_context_create(), ast_sched_start_thread(), ast_sip_destroy_distributor(), ast_sip_get_sorcery(), ast_sip_register_cli_formatter(), ast_sip_register_service(), ast_sorcery_observer_add(), ast_sorcery_reload_object(), auth_mod, cli_unid_get_container(), cli_unid_get_id(), cli_unid_iterate(), cli_unid_print_body(), cli_unid_print_header(), cli_unid_retrieve_by_id(), create_artificial_auth(), create_artificial_endpoint(), DEFAULT_SUSPECTS_BUCKETS, DIALOG_ASSOCIATIONS_BUCKETS, dialog_associations_cmp(), dialog_associations_hash(), distributor_mod, distributor_pool_setup(), endpoint_mod, ast_sip_cli_formatter_entry::get_container, ast_sip_cli_formatter_entry::get_id, ast_sip_cli_formatter_entry::iterate, LOG_ERROR, ast_sip_cli_formatter_entry::name, NULL, ast_sip_cli_formatter_entry::print_body, ast_sip_cli_formatter_entry::print_header, ast_sip_cli_formatter_entry::retrieve_by_id, suspects_compare(), and suspects_hash().
Referenced by load_module().
 {
    unidentified_requests = ao2_container_alloc_hash(AO2_ALLOC_OPT_LOCK_RWLOCK, 0,
       DEFAULT_SUSPECTS_BUCKETS, suspects_hash, NULL, suspects_compare);
    if (!unidentified_requests) {
       return -1;
    }
    dialog_associations = ao2_container_alloc_hash(AO2_ALLOC_OPT_LOCK_RWLOCK, 0,
       DIALOG_ASSOCIATIONS_BUCKETS, dialog_associations_hash, NULL,
       dialog_associations_cmp);
    if (!dialog_associations) {
       ast_sip_destroy_distributor();
       return -1;
    }
    if (distributor_pool_setup()) {
       ast_sip_destroy_distributor();
       return -1;
    }
    prune_context = ast_sched_context_create();
    if (!prune_context) {
       ast_sip_destroy_distributor();
       return -1;
    }
    if (ast_sched_start_thread(prune_context)) {
       ast_sip_destroy_distributor();
       return -1;
    }
    ast_sorcery_observer_add(ast_sip_get_sorcery(), "global", &global_observer);
    ast_sorcery_reload_object(ast_sip_get_sorcery(), "global");
    if (create_artificial_endpoint() || create_artificial_auth()) {
       ast_sip_destroy_distributor();
       return -1;
    }
    if (ast_sip_register_service(&distributor_mod)) {
       ast_sip_destroy_distributor();
       return -1;
    }
    if (ast_sip_register_service(&endpoint_mod)) {
       ast_sip_destroy_distributor();
       return -1;
    }
    if (ast_sip_register_service(&auth_mod)) {
       ast_sip_destroy_distributor();
       return -1;
    }
    unid_formatter = ao2_alloc_options(sizeof(struct ast_sip_cli_formatter_entry), NULL,
       AO2_ALLOC_OPT_LOCK_NOLOCK);
    if (!unid_formatter) {
       ast_sip_destroy_distributor();
       ast_log(LOG_ERROR, "Unable to allocate memory for unid_formatter\n");
       return -1;
    }
    unid_formatter->name = "unidentified_request";
    unid_formatter->print_header = cli_unid_print_header;
    unid_formatter->print_body = cli_unid_print_body;
    unid_formatter->get_container = cli_unid_get_container;
    unid_formatter->iterate = cli_unid_iterate;
    unid_formatter->get_id = cli_unid_get_id;
    unid_formatter->retrieve_by_id = cli_unid_retrieve_by_id;
    ast_sip_register_cli_formatter(unid_formatter);
    ast_cli_register_multiple(cli_commands, ARRAY_LEN(cli_commands));
    return 0;
 }
ast_sip_initialize_dns()
void ast_sip_initialize_dns (void)
Definition at line 314 of file config_system.c.
References ast_sip_push_task_wait_servant(), NULL, and system_create_resolver_and_set_nameservers().
Referenced by load_module(), and reload_configuration_task().
 {
    ast_sip_push_task_wait_servant(NULL, system_create_resolver_and_set_nameservers, NULL);
 }
ast_sip_initialize_global()
int ast_sip_initialize_global (void)
ast_sip_initialize_global_headers()
void ast_sip_initialize_global_headers (void)
Definition at line 163 of file pjsip_global_headers.c.
References AST_RWLIST_HEAD_INIT, ast_sip_register_service(), global_header_mod, request_headers, and response_headers.
Referenced by load_module().
 {
    AST_RWLIST_HEAD_INIT(&request_headers);
    AST_RWLIST_HEAD_INIT(&response_headers);
    ast_sip_register_service(&global_header_mod);
 }
ast_sip_initialize_resolver()
void ast_sip_initialize_resolver (void)
Definition at line 708 of file pjsip_resolver.c.
References ast_log, ast_sip_push_task_wait_servant(), LOG_NOTICE, NULL, and sip_replace_resolver().
Referenced by load_module().
 {
    /* Replace the existing PJSIP resolver with our own implementation */
    ast_sip_push_task_wait_servant(NULL, sip_replace_resolver, NULL);
 }
ast_sip_initialize_scheduler()
int ast_sip_initialize_scheduler (void)
Initialize scheduler.
Since
13.9.0
Return values
-1 failure
0 success
Definition at line 614 of file pjsip_scheduler.c.
References AO2_ALLOC_OPT_LOCK_RWLOCK, ao2_container_alloc_hash, AO2_CONTAINER_ALLOC_OPT_DUPS_REJECT, ARRAY_LEN, ast_cli_register_multiple, ast_log, ast_sched_context_create(), ast_sched_context_destroy(), ast_sched_start_thread(), LOG_ERROR, and TASK_BUCKETS.
Referenced by load_module().
 {
    scheduler_context = ast_sched_context_create();
    if (!scheduler_context) {
       ast_log(LOG_ERROR, "Failed to create scheduler. Aborting load\n");
       return -1;
    }
    if (ast_sched_start_thread(scheduler_context)) {
       ast_log(LOG_ERROR, "Failed to start scheduler. Aborting load\n");
       ast_sched_context_destroy(scheduler_context);
       return -1;
    }
    tasks = ao2_container_alloc_hash(AO2_ALLOC_OPT_LOCK_RWLOCK,
       AO2_CONTAINER_ALLOC_OPT_DUPS_REJECT, TASK_BUCKETS, ast_sip_sched_task_hash_fn,
       ast_sip_sched_task_sort_fn, ast_sip_sched_task_cmp_fn);
    if (!tasks) {
       ast_log(LOG_ERROR, "Failed to allocate task container. Aborting load\n");
       ast_sched_context_destroy(scheduler_context);
       return -1;
    }
    ast_cli_register_multiple(cli_commands, ARRAY_LEN(cli_commands));
    return 0;
 }
ast_sip_initialize_sorcery_auth()
int ast_sip_initialize_sorcery_auth (void)
Initialize sorcery with auth support.
Definition at line 370 of file config_auth.c.
References ami_show_auths(), ao2_alloc, ARRAY_LEN, ast_cli_register_multiple, ast_log, ast_manager_register_xml, ast_sip_get_sorcery(), ast_sip_register_cli_formatter(), ast_sip_register_endpoint_formatter(), ast_sorcery_apply_default, ast_sorcery_object_field_register, ast_sorcery_object_field_register_custom, ast_sorcery_object_get_id(), ast_sorcery_object_register, auth_alloc(), auth_apply(), auth_type_handler(), auth_type_to_str(), cli_get_container(), cli_iterator(), cli_print_body(), cli_print_header(), cli_retrieve_by_id(), EVENT_FLAG_SYSTEM, FLDSET, ast_sip_cli_formatter_entry::get_container, ast_sip_cli_formatter_entry::get_id, ast_sip_cli_formatter_entry::iterate, LOG_ERROR, ast_sip_cli_formatter_entry::name, NULL, OPT_NOOP_T, OPT_STRINGFIELD_T, OPT_UINT_T, ast_sip_cli_formatter_entry::print_body, ast_sip_cli_formatter_entry::print_header, ast_sip_cli_formatter_entry::retrieve_by_id, sorcery, and STRFLDSET.
Referenced by ast_res_pjsip_initialize_configuration().
 {
    struct ast_sorcery *sorcery = ast_sip_get_sorcery();
    ast_sorcery_apply_default(sorcery, SIP_SORCERY_AUTH_TYPE, "config", "pjsip.conf,criteria=type=auth");
    if (ast_sorcery_object_register(sorcery, SIP_SORCERY_AUTH_TYPE, auth_alloc, NULL, auth_apply)) {
       return -1;
    }
    ast_sorcery_object_field_register(sorcery, SIP_SORCERY_AUTH_TYPE, "type", "",
          OPT_NOOP_T, 0, 0);
    ast_sorcery_object_field_register(sorcery, SIP_SORCERY_AUTH_TYPE, "username",
          "", OPT_STRINGFIELD_T, 0, STRFLDSET(struct ast_sip_auth, auth_user));
    ast_sorcery_object_field_register(sorcery, SIP_SORCERY_AUTH_TYPE, "password",
          "", OPT_STRINGFIELD_T, 0, STRFLDSET(struct ast_sip_auth, auth_pass));
    ast_sorcery_object_field_register(sorcery, SIP_SORCERY_AUTH_TYPE, "refresh_token",
          "", OPT_STRINGFIELD_T, 0, STRFLDSET(struct ast_sip_auth, refresh_token));
    ast_sorcery_object_field_register(sorcery, SIP_SORCERY_AUTH_TYPE, "oauth_clientid",
          "", OPT_STRINGFIELD_T, 0, STRFLDSET(struct ast_sip_auth, oauth_clientid));
    ast_sorcery_object_field_register(sorcery, SIP_SORCERY_AUTH_TYPE, "oauth_secret",
          "", OPT_STRINGFIELD_T, 0, STRFLDSET(struct ast_sip_auth, oauth_secret));
    ast_sorcery_object_field_register(sorcery, SIP_SORCERY_AUTH_TYPE, "md5_cred",
          "", OPT_STRINGFIELD_T, 0, STRFLDSET(struct ast_sip_auth, md5_creds));
    ast_sorcery_object_field_register(sorcery, SIP_SORCERY_AUTH_TYPE, "realm",
          "", OPT_STRINGFIELD_T, 0, STRFLDSET(struct ast_sip_auth, realm));
    ast_sorcery_object_field_register(sorcery, SIP_SORCERY_AUTH_TYPE, "nonce_lifetime",
          "32", OPT_UINT_T, 0, FLDSET(struct ast_sip_auth, nonce_lifetime));
    ast_sorcery_object_field_register_custom(sorcery, SIP_SORCERY_AUTH_TYPE, "auth_type",
          "userpass", auth_type_handler, auth_type_to_str, NULL, 0, 0);
    ast_sip_register_endpoint_formatter(&endpoint_auth_formatter);
    cli_formatter = ao2_alloc(sizeof(struct ast_sip_cli_formatter_entry), NULL);
    if (!cli_formatter) {
       ast_log(LOG_ERROR, "Unable to allocate memory for cli formatter\n");
       return -1;
    }
    cli_formatter->name = SIP_SORCERY_AUTH_TYPE;
    cli_formatter->print_header = cli_print_header;
    cli_formatter->print_body = cli_print_body;
    cli_formatter->get_container = cli_get_container;
    cli_formatter->iterate = cli_iterator;
    cli_formatter->get_id = ast_sorcery_object_get_id;
    cli_formatter->retrieve_by_id = cli_retrieve_by_id;
    ast_sip_register_cli_formatter(cli_formatter);
    ast_cli_register_multiple(cli_commands, ARRAY_LEN(cli_commands));
    if (ast_manager_register_xml("PJSIPShowAuths", EVENT_FLAG_SYSTEM, ami_show_auths)) {
       return -1;
    }
    return 0;
 }
ast_sip_initialize_sorcery_domain_alias()
int ast_sip_initialize_sorcery_domain_alias (void)
Initialize sorcery with domain alias support.
Definition at line 71 of file config_domain_aliases.c.
References ast_sip_get_sorcery(), ast_sorcery_apply_default, ast_sorcery_object_field_register, ast_sorcery_object_register, domain_alias_alloc(), domain_alias_apply(), NULL, OPT_NOOP_T, OPT_STRINGFIELD_T, SIP_SORCERY_DOMAIN_ALIAS_TYPE, sorcery, and STRFLDSET.
Referenced by ast_res_pjsip_initialize_configuration().
 {
    struct ast_sorcery *sorcery = ast_sip_get_sorcery();
    ast_sorcery_apply_default(sorcery, SIP_SORCERY_DOMAIN_ALIAS_TYPE, "config", "pjsip.conf,criteria=type=domain_alias");
    if (ast_sorcery_object_register(sorcery, SIP_SORCERY_DOMAIN_ALIAS_TYPE,
       domain_alias_alloc, NULL, domain_alias_apply)) {
       return -1;
    }
    ast_sorcery_object_field_register(sorcery, SIP_SORCERY_DOMAIN_ALIAS_TYPE, "type", "",
          OPT_NOOP_T, 0, 0);
    ast_sorcery_object_field_register(sorcery, SIP_SORCERY_DOMAIN_ALIAS_TYPE, "domain",
          "", OPT_STRINGFIELD_T, 0, STRFLDSET(struct ast_sip_domain_alias, domain));
    return 0;
 }
ast_sip_initialize_sorcery_global()
int ast_sip_initialize_sorcery_global (void)
Definition at line 647 of file config_global.c.
References __stringify, ast_get_version(), ast_sip_get_sorcery(), ast_sorcery_apply_default, ast_sorcery_instance_observer_add(), ast_sorcery_object_field_register, ast_sorcery_object_field_register_custom, ast_sorcery_object_register, global_config::contact_expiration_check_interval, global_config::debug, DEFAULT_CONTACT_EXPIRATION_CHECK_INTERVAL, DEFAULT_DEBUG, DEFAULT_DISABLE_MULTI_DOMAIN, DEFAULT_ENDPOINT_IDENTIFIER_ORDER, DEFAULT_FROM_USER, global_config::default_from_user, DEFAULT_IGNORE_URI_USER_OPTIONS, DEFAULT_KEEPALIVE_INTERVAL, DEFAULT_MAX_FORWARDS, DEFAULT_MAX_INITIAL_QUALIFY_TIME, DEFAULT_MWI_DISABLE_INITIAL_UNSOLICITED, DEFAULT_MWI_TPS_QUEUE_HIGH, DEFAULT_MWI_TPS_QUEUE_LOW, DEFAULT_NOREFERSUB, DEFAULT_OUTBOUND_ENDPOINT, global_config::default_outbound_endpoint, DEFAULT_REALM, global_config::default_realm, DEFAULT_REGCONTEXT, DEFAULT_SEND_CONTACT_STATUS_ON_UPDATE_REGISTRATION, DEFAULT_TASKPROCESSOR_OVERLOAD_TRIGGER, DEFAULT_UNIDENTIFIED_REQUEST_COUNT, DEFAULT_UNIDENTIFIED_REQUEST_PERIOD, DEFAULT_UNIDENTIFIED_REQUEST_PRUNE_INTERVAL, DEFAULT_USE_CALLERID_CONTACT, default_useragent, DEFAULT_USERAGENT_PREFIX, DEFAULT_VOICEMAIL_EXTENSION, global_config::default_voicemail_extension, global_config::disable_multi_domain, global_config::endpoint_identifier_order, FLDSET, global_alloc(), global_apply(), global_config::ignore_uri_user_options, global_config::keep_alive_interval, global_config::max_initial_qualify_time, global_config::mwi, global_config::norefersub, NULL, OPT_BOOL_T, OPT_INT_T, OPT_NOOP_T, OPT_STRINGFIELD_T, OPT_UINT_T, OPT_YESNO_T, overload_trigger_handler(), overload_trigger_map, overload_trigger_to_str(), global_config::regcontext, global_config::send_contact_status_on_update_registration, sorcery, STRFLDSET, global_config::unidentified_request_count, global_config::unidentified_request_period, global_config::unidentified_request_prune_interval, global_config::use_callerid_contact, and global_config::useragent.
Referenced by ast_res_pjsip_initialize_configuration().
 {
    struct ast_sorcery *sorcery = ast_sip_get_sorcery();
    snprintf(default_useragent, sizeof(default_useragent), "%s %s",
       DEFAULT_USERAGENT_PREFIX, ast_get_version());
    ast_sorcery_apply_default(sorcery, "global", "config", "pjsip.conf,criteria=type=global,single_object=yes,explicit_name=global");
    if (ast_sorcery_object_register(sorcery, "global", global_alloc, NULL, global_apply)) {
       return -1;
    }
    ast_sorcery_object_field_register(sorcery, "global", "type", "", OPT_NOOP_T, 0, 0);
    ast_sorcery_object_field_register(sorcery, "global", "max_forwards",
       __stringify(DEFAULT_MAX_FORWARDS),
       OPT_UINT_T, 0, FLDSET(struct global_config, max_forwards));
    ast_sorcery_object_field_register(sorcery, "global", "user_agent", default_useragent,
       OPT_STRINGFIELD_T, 0, STRFLDSET(struct global_config, useragent));
    ast_sorcery_object_field_register(sorcery, "global", "default_outbound_endpoint",
       DEFAULT_OUTBOUND_ENDPOINT,
       OPT_STRINGFIELD_T, 0, STRFLDSET(struct global_config, default_outbound_endpoint));
    ast_sorcery_object_field_register(sorcery, "global", "debug", DEFAULT_DEBUG,
       OPT_STRINGFIELD_T, 0, STRFLDSET(struct global_config, debug));
    ast_sorcery_object_field_register(sorcery, "global", "endpoint_identifier_order",
       DEFAULT_ENDPOINT_IDENTIFIER_ORDER,
       OPT_STRINGFIELD_T, 0, STRFLDSET(struct global_config, endpoint_identifier_order));
    ast_sorcery_object_field_register(sorcery, "global", "keep_alive_interval",
       __stringify(DEFAULT_KEEPALIVE_INTERVAL),
       OPT_UINT_T, 0, FLDSET(struct global_config, keep_alive_interval));
    ast_sorcery_object_field_register(sorcery, "global", "max_initial_qualify_time",
       __stringify(DEFAULT_MAX_INITIAL_QUALIFY_TIME),
       OPT_UINT_T, 0, FLDSET(struct global_config, max_initial_qualify_time));
    ast_sorcery_object_field_register(sorcery, "global", "default_from_user", DEFAULT_FROM_USER,
       OPT_STRINGFIELD_T, 0, STRFLDSET(struct global_config, default_from_user));
    ast_sorcery_object_field_register(sorcery, "global", "default_voicemail_extension",
       DEFAULT_VOICEMAIL_EXTENSION, OPT_STRINGFIELD_T, 0, STRFLDSET(struct global_config,
       default_voicemail_extension));
    ast_sorcery_object_field_register(sorcery, "global", "regcontext", DEFAULT_REGCONTEXT,
       OPT_STRINGFIELD_T, 0, STRFLDSET(struct global_config, regcontext));
    ast_sorcery_object_field_register(sorcery, "global", "contact_expiration_check_interval",
       __stringify(DEFAULT_CONTACT_EXPIRATION_CHECK_INTERVAL),
       OPT_UINT_T, 0, FLDSET(struct global_config, contact_expiration_check_interval));
    ast_sorcery_object_field_register(sorcery, "global", "disable_multi_domain",
       DEFAULT_DISABLE_MULTI_DOMAIN ? "yes" : "no",
       OPT_BOOL_T, 1, FLDSET(struct global_config, disable_multi_domain));
    ast_sorcery_object_field_register(sorcery, "global", "unidentified_request_count",
       __stringify(DEFAULT_UNIDENTIFIED_REQUEST_COUNT),
       OPT_UINT_T, 0, FLDSET(struct global_config, unidentified_request_count));
    ast_sorcery_object_field_register(sorcery, "global", "unidentified_request_period",
       __stringify(DEFAULT_UNIDENTIFIED_REQUEST_PERIOD),
       OPT_UINT_T, 0, FLDSET(struct global_config, unidentified_request_period));
    ast_sorcery_object_field_register(sorcery, "global", "unidentified_request_prune_interval",
       __stringify(DEFAULT_UNIDENTIFIED_REQUEST_PRUNE_INTERVAL),
       OPT_UINT_T, 0, FLDSET(struct global_config, unidentified_request_prune_interval));
    ast_sorcery_object_field_register(sorcery, "global", "default_realm", DEFAULT_REALM,
       OPT_STRINGFIELD_T, 0, STRFLDSET(struct global_config, default_realm));
    ast_sorcery_object_field_register(sorcery, "global", "mwi_tps_queue_high",
       __stringify(DEFAULT_MWI_TPS_QUEUE_HIGH),
       OPT_UINT_T, 0, FLDSET(struct global_config, mwi.tps_queue_high));
    ast_sorcery_object_field_register(sorcery, "global", "mwi_tps_queue_low",
       __stringify(DEFAULT_MWI_TPS_QUEUE_LOW),
       OPT_INT_T, 0, FLDSET(struct global_config, mwi.tps_queue_low));
    ast_sorcery_object_field_register(sorcery, "global", "mwi_disable_initial_unsolicited",
       DEFAULT_MWI_DISABLE_INITIAL_UNSOLICITED ? "yes" : "no",
       OPT_BOOL_T, 1, FLDSET(struct global_config, mwi.disable_initial_unsolicited));
    ast_sorcery_object_field_register(sorcery, "global", "ignore_uri_user_options",
       DEFAULT_IGNORE_URI_USER_OPTIONS ? "yes" : "no",
       OPT_BOOL_T, 1, FLDSET(struct global_config, ignore_uri_user_options));
    ast_sorcery_object_field_register(sorcery, "global", "use_callerid_contact",
       DEFAULT_USE_CALLERID_CONTACT ? "yes" : "no",
       OPT_YESNO_T, 1, FLDSET(struct global_config, use_callerid_contact));
    ast_sorcery_object_field_register(sorcery, "global", "send_contact_status_on_update_registration",
       DEFAULT_SEND_CONTACT_STATUS_ON_UPDATE_REGISTRATION ? "yes" : "no",
       OPT_YESNO_T, 1, FLDSET(struct global_config, send_contact_status_on_update_registration));
    ast_sorcery_object_field_register_custom(sorcery, "global", "taskprocessor_overload_trigger",
       overload_trigger_map[DEFAULT_TASKPROCESSOR_OVERLOAD_TRIGGER],
       overload_trigger_handler, overload_trigger_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register(sorcery, "global", "norefersub",
       DEFAULT_NOREFERSUB ? "yes" : "no",
       OPT_YESNO_T, 1, FLDSET(struct global_config, norefersub));
    if (ast_sorcery_instance_observer_add(sorcery, &observer_callbacks_global)) {
       return -1;
    }
    return 0;
 }
ast_sip_initialize_sorcery_location()
int ast_sip_initialize_sorcery_location (void)
Initialize sorcery with location support.
Definition at line 1366 of file location.c.
References ami_show_aors(), ao2_alloc, aor_alloc(), aor_apply_handler(), ARRAY_LEN, ast_cli_register_multiple, ast_log, ast_manager_register_xml, ast_pjproject_get_buildopt(), ast_sip_get_contact_status_label(), ast_sip_get_sorcery(), ast_sip_register_cli_formatter(), ast_sip_register_endpoint_formatter(), ast_sorcery_apply_default, ast_sorcery_object_field_register, ast_sorcery_object_field_register_custom, ast_sorcery_object_register, ast_sorcery_object_set_congestion_levels(), ast_sorcery_observer_add(), AST_STATSD_GAUGE, ast_statsd_log_full_va(), AST_TASKPROCESSOR_HIGH_WATER_LEVEL, cli_aor_get_container(), cli_aor_get_id(), cli_aor_iterate(), cli_aor_print_body(), cli_aor_print_header(), cli_aor_retrieve_by_id(), cli_contact_get_container(), cli_contact_get_id(), cli_contact_iterate(), cli_contact_print_body(), cli_contact_print_header(), cli_contact_retrieve_by_id(), contact_alloc(), contact_apply_handler(), contacts_to_str(), contacts_to_var_list(), default_expiration, EVENT_FLAG_SYSTEM, expiration_str2struct(), expiration_struct2str(), FLDSET, ast_sip_cli_formatter_entry::get_container, ast_sip_cli_formatter_entry::get_id, ast_sip_cli_formatter_entry::iterate, LOG_ERROR, mailboxes, ast_sip_cli_formatter_entry::name, NULL, OPT_BOOL_T, OPT_DOUBLE_T, OPT_NOOP_T, OPT_STRINGFIELD_T, OPT_UINT_T, OPT_YESNO_T, PARSE_IN_RANGE, permanent_uri_handler(), pj_max_hostname, pjsip_max_url_size, ast_sip_cli_formatter_entry::print_body, ast_sip_cli_formatter_entry::print_header, REMOVED, ast_sip_cli_formatter_entry::retrieve_by_id, sorcery, STRFLDSET, voicemail_extension_handler(), and voicemail_extension_to_str().
Referenced by ast_res_pjsip_initialize_configuration().
 {
    struct ast_sorcery *sorcery = ast_sip_get_sorcery();
    int i;
    ast_pjproject_get_buildopt("PJ_MAX_HOSTNAME", "%d", &pj_max_hostname);
    /* As of pjproject 2.4.5, PJSIP_MAX_URL_SIZE isn't exposed yet but we try anyway. */
    ast_pjproject_get_buildopt("PJSIP_MAX_URL_SIZE", "%d", &pjsip_max_url_size);
    ast_sorcery_apply_default(sorcery, "contact", "astdb", "registrar");
    ast_sorcery_object_set_congestion_levels(sorcery, "contact", -1,
       3 * AST_TASKPROCESSOR_HIGH_WATER_LEVEL);
    ast_sorcery_apply_default(sorcery, "aor", "config", "pjsip.conf,criteria=type=aor");
    if (ast_sorcery_object_register(sorcery, "contact", contact_alloc, NULL, contact_apply_handler) ||
       ast_sorcery_object_register(sorcery, "aor", aor_alloc, NULL, aor_apply_handler)) {
       return -1;
    }
    ast_sorcery_observer_add(sorcery, "aor", &aor_observer);
    ast_sorcery_object_field_register(sorcery, "contact", "type", "", OPT_NOOP_T, 0, 0);
    ast_sorcery_object_field_register(sorcery, "contact", "uri", "", OPT_STRINGFIELD_T, 0, STRFLDSET(struct ast_sip_contact, uri));
    ast_sorcery_object_field_register(sorcery, "contact", "path", "", OPT_STRINGFIELD_T, 0, STRFLDSET(struct ast_sip_contact, path));
    ast_sorcery_object_field_register_custom(sorcery, "contact", "expiration_time", "", expiration_str2struct, expiration_struct2str, NULL, 0, 0);
    ast_sorcery_object_field_register(sorcery, "contact", "qualify_frequency", 0, OPT_UINT_T,
       PARSE_IN_RANGE, FLDSET(struct ast_sip_contact, qualify_frequency), 0, 86400);
    ast_sorcery_object_field_register(sorcery, "contact", "qualify_timeout", "3.0", OPT_DOUBLE_T, 0, FLDSET(struct ast_sip_contact, qualify_timeout));
    ast_sorcery_object_field_register(sorcery, "contact", "authenticate_qualify", "no", OPT_YESNO_T, 1, FLDSET(struct ast_sip_contact, authenticate_qualify));
    ast_sorcery_object_field_register(sorcery, "contact", "outbound_proxy", "", OPT_STRINGFIELD_T, 0, STRFLDSET(struct ast_sip_contact, outbound_proxy));
    ast_sorcery_object_field_register(sorcery, "contact", "user_agent", "", OPT_STRINGFIELD_T, 0, STRFLDSET(struct ast_sip_contact, user_agent));
    ast_sorcery_object_field_register(sorcery, "contact", "endpoint", "", OPT_STRINGFIELD_T, 0, STRFLDSET(struct ast_sip_contact, endpoint_name));
    ast_sorcery_object_field_register(sorcery, "contact", "reg_server", "", OPT_STRINGFIELD_T, 0, STRFLDSET(struct ast_sip_contact, reg_server));
    ast_sorcery_object_field_register(sorcery, "contact", "via_addr", "", OPT_STRINGFIELD_T, 0, STRFLDSET(struct ast_sip_contact, via_addr));
    ast_sorcery_object_field_register(sorcery, "contact", "via_port", "0", OPT_UINT_T, 0, FLDSET(struct ast_sip_contact, via_port));
    ast_sorcery_object_field_register(sorcery, "contact", "call_id", "", OPT_STRINGFIELD_T, 0, STRFLDSET(struct ast_sip_contact, call_id));
    ast_sorcery_object_field_register(sorcery, "contact", "prune_on_boot", "no", OPT_YESNO_T, 1, FLDSET(struct ast_sip_contact, prune_on_boot));
    ast_sorcery_object_field_register(sorcery, "aor", "type", "", OPT_NOOP_T, 0, 0);
    ast_sorcery_object_field_register(sorcery, "aor", "minimum_expiration", "60", OPT_UINT_T, 0, FLDSET(struct ast_sip_aor, minimum_expiration));
    ast_sorcery_object_field_register(sorcery, "aor", "maximum_expiration", "7200", OPT_UINT_T, 0, FLDSET(struct ast_sip_aor, maximum_expiration));
    ast_sorcery_object_field_register(sorcery, "aor", "default_expiration", "3600", OPT_UINT_T, 0, FLDSET(struct ast_sip_aor, default_expiration));
    ast_sorcery_object_field_register(sorcery, "aor", "qualify_frequency", 0, OPT_UINT_T, PARSE_IN_RANGE, FLDSET(struct ast_sip_aor, qualify_frequency), 0, 86400);
    ast_sorcery_object_field_register(sorcery, "aor", "qualify_timeout", "3.0", OPT_DOUBLE_T, 0, FLDSET(struct ast_sip_aor, qualify_timeout));
    ast_sorcery_object_field_register(sorcery, "aor", "authenticate_qualify", "no", OPT_BOOL_T, 1, FLDSET(struct ast_sip_aor, authenticate_qualify));
    ast_sorcery_object_field_register(sorcery, "aor", "max_contacts", "0", OPT_UINT_T, 0, FLDSET(struct ast_sip_aor, max_contacts));
    ast_sorcery_object_field_register(sorcery, "aor", "remove_existing", "no", OPT_BOOL_T, 1, FLDSET(struct ast_sip_aor, remove_existing));
    ast_sorcery_object_field_register_custom(sorcery, "aor", "contact", "", permanent_uri_handler, contacts_to_str, contacts_to_var_list, 0, 0);
    ast_sorcery_object_field_register(sorcery, "aor", "mailboxes", "", OPT_STRINGFIELD_T, 0, STRFLDSET(struct ast_sip_aor, mailboxes));
    ast_sorcery_object_field_register_custom(sorcery, "aor", "voicemail_extension", "", voicemail_extension_handler, voicemail_extension_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register(sorcery, "aor", "outbound_proxy", "", OPT_STRINGFIELD_T, 0, STRFLDSET(struct ast_sip_aor, outbound_proxy));
    ast_sorcery_object_field_register(sorcery, "aor", "support_path", "no", OPT_BOOL_T, 1, FLDSET(struct ast_sip_aor, support_path));
    ast_sip_register_endpoint_formatter(&endpoint_aor_formatter);
    contact_formatter = ao2_alloc(sizeof(struct ast_sip_cli_formatter_entry), NULL);
    if (!contact_formatter) {
       ast_log(LOG_ERROR, "Unable to allocate memory for contact_formatter\n");
       return -1;
    }
    contact_formatter->name = "contact";
    contact_formatter->print_header = cli_contact_print_header;
    contact_formatter->print_body = cli_contact_print_body;
    contact_formatter->get_container = cli_contact_get_container;
    contact_formatter->iterate = cli_contact_iterate;
    contact_formatter->get_id = cli_contact_get_id;
    contact_formatter->retrieve_by_id = cli_contact_retrieve_by_id;
    aor_formatter = ao2_alloc(sizeof(struct ast_sip_cli_formatter_entry), NULL);
    if (!aor_formatter) {
       ast_log(LOG_ERROR, "Unable to allocate memory for aor_formatter\n");
       return -1;
    }
    aor_formatter->name = "aor";
    aor_formatter->print_header = cli_aor_print_header;
    aor_formatter->print_body = cli_aor_print_body;
    aor_formatter->get_container = cli_aor_get_container;
    aor_formatter->iterate = cli_aor_iterate;
    aor_formatter->get_id = cli_aor_get_id;
    aor_formatter->retrieve_by_id = cli_aor_retrieve_by_id;
    ast_sip_register_cli_formatter(contact_formatter);
    ast_sip_register_cli_formatter(aor_formatter);
    ast_cli_register_multiple(cli_commands, ARRAY_LEN(cli_commands));
    if (ast_manager_register_xml("PJSIPShowAors", EVENT_FLAG_SYSTEM, ami_show_aors)) {
       return -1;
    }
    /*
     * Reset StatsD gauges in case we didn't shut down cleanly.
     * Note that this must done here, as contacts will create the contact_status
     * object before PJSIP options handling is initialized.
     */
    for (i = 0; i <= REMOVED; i++) {
       ast_statsd_log_full_va("PJSIP.contacts.states.%s", AST_STATSD_GAUGE, 0, 1.0, ast_sip_get_contact_status_label(i));
    }
    return 0;
 }
ast_sip_initialize_sorcery_qualify()
int ast_sip_initialize_sorcery_qualify (void)
ast_sip_initialize_sorcery_transport()
int ast_sip_initialize_sorcery_transport (void)
Initialize sorcery with transport support.
Definition at line 1618 of file config_transport.c.
References ao2_alloc, AO2_ALLOC_OPT_LOCK_MUTEX, ao2_cleanup, ao2_container_alloc_hash, ARRAY_LEN, ast_cli_register_multiple, AST_DEFAULT_WEBSOCKET_WRITE_TIMEOUT_STR, ast_log, AST_RETRIEVE_FLAG_ALL, AST_RETRIEVE_FLAG_MULTIPLE, ast_sip_get_sorcery(), ast_sip_register_cli_formatter(), ast_sip_register_endpoint_formatter(), ast_sorcery_apply_default, ast_sorcery_object_field_register, ast_sorcery_object_field_register_custom, ast_sorcery_object_get_id(), ast_sorcery_object_register, ast_sorcery_retrieve_by_fields(), ca_list_file_to_str(), ca_list_path_to_str(), cert_file_to_str(), cli_get_container(), cli_iterate(), cli_print_body(), cli_print_header(), cli_retrieve_by_id(), cos, DEFAULT_STATE_BUCKETS, FLDSET, ast_sip_cli_formatter_entry::get_container, ast_sip_cli_formatter_entry::get_id, internal_state_cmp(), internal_state_hash(), ast_sip_cli_formatter_entry::iterate, localnet_to_str(), localnet_to_vl(), LOG_ERROR, ast_sip_cli_formatter_entry::name, NULL, OPT_BOOL_T, OPT_INT_T, OPT_STRINGFIELD_T, OPT_UINT_T, PARSE_IN_RANGE, password, ast_sip_cli_formatter_entry::print_body, ast_sip_cli_formatter_entry::print_header, privkey_file_to_str(), require_client_cert_to_str(), ast_sip_cli_formatter_entry::retrieve_by_id, sip_transport_alloc(), sorcery, STRFLDSET, tls_method_to_str(), tos_to_str(), transport_apply(), transport_bind_handler(), transport_bind_to_str(), transport_localnet_handler(), transport_protocol_handler(), transport_protocol_to_str(), transport_state_init(), transport_tls_bool_handler(), transport_tls_file_handler(), transport_tls_method_handler(), transport_tos_handler(), verify_client_to_str(), and verify_server_to_str().
Referenced by ast_res_pjsip_initialize_configuration().
 {
    struct ast_sorcery *sorcery = ast_sip_get_sorcery();
    struct ao2_container *transports = NULL;
    /* Create outbound registration states container. */
    transport_states = ao2_container_alloc_hash(AO2_ALLOC_OPT_LOCK_MUTEX, 0,
       DEFAULT_STATE_BUCKETS, internal_state_hash, NULL, internal_state_cmp);
    if (!transport_states) {
       ast_log(LOG_ERROR, "Unable to allocate transport states container\n");
       return -1;
    }
    ast_sorcery_apply_default(sorcery, "transport", "config", "pjsip.conf,criteria=type=transport");
    if (ast_sorcery_object_register(sorcery, "transport", sip_transport_alloc, NULL, transport_apply)) {
       return -1;
    }
    /* Normally type is a OPT_NOOP_T but we're using it to make sure that state is created */
    ast_sorcery_object_field_register_custom(sorcery, "transport", "type", "", transport_state_init, NULL, NULL, 0, 0);
    ast_sorcery_object_field_register_custom(sorcery, "transport", "protocol", "udp", transport_protocol_handler, transport_protocol_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register_custom(sorcery, "transport", "bind", "", transport_bind_handler, transport_bind_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register(sorcery, "transport", "async_operations", "1", OPT_UINT_T, 0, FLDSET(struct ast_sip_transport, async_operations));
    ast_sorcery_object_field_register_custom(sorcery, "transport", "ca_list_file", "", transport_tls_file_handler, ca_list_file_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register_custom(sorcery, "transport", "ca_list_path", "", transport_tls_file_handler, ca_list_path_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register_custom(sorcery, "transport", "cert_file", "", transport_tls_file_handler, cert_file_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register_custom(sorcery, "transport", "priv_key_file", "", transport_tls_file_handler, privkey_file_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register(sorcery, "transport", "password", "", OPT_STRINGFIELD_T, 0, STRFLDSET(struct ast_sip_transport, password));
    ast_sorcery_object_field_register(sorcery, "transport", "external_signaling_address", "", OPT_STRINGFIELD_T, 0, STRFLDSET(struct ast_sip_transport, external_signaling_address));
    ast_sorcery_object_field_register(sorcery, "transport", "external_signaling_port", "0", OPT_UINT_T, PARSE_IN_RANGE, FLDSET(struct ast_sip_transport, external_signaling_port), 0, 65535);
    ast_sorcery_object_field_register(sorcery, "transport", "external_media_address", "", OPT_STRINGFIELD_T, 0, STRFLDSET(struct ast_sip_transport, external_media_address));
    ast_sorcery_object_field_register(sorcery, "transport", "domain", "", OPT_STRINGFIELD_T, 0, STRFLDSET(struct ast_sip_transport, domain));
    ast_sorcery_object_field_register_custom(sorcery, "transport", "verify_server", "", transport_tls_bool_handler, verify_server_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register_custom(sorcery, "transport", "verify_client", "", transport_tls_bool_handler, verify_client_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register_custom(sorcery, "transport", "require_client_cert", "", transport_tls_bool_handler, require_client_cert_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register_custom(sorcery, "transport", "method", "", transport_tls_method_handler, tls_method_to_str, NULL, 0, 0);
 #if defined(PJ_HAS_SSL_SOCK) && PJ_HAS_SSL_SOCK != 0
    ast_sorcery_object_field_register_custom(sorcery, "transport", "cipher", "", transport_tls_cipher_handler, transport_tls_cipher_to_str, NULL, 0, 0);
 #endif
    ast_sorcery_object_field_register_custom(sorcery, "transport", "local_net", "", transport_localnet_handler, localnet_to_str, localnet_to_vl, 0, 0);
    ast_sorcery_object_field_register_custom(sorcery, "transport", "tos", "0", transport_tos_handler, tos_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register(sorcery, "transport", "cos", "0", OPT_UINT_T, 0, FLDSET(struct ast_sip_transport, cos));
    ast_sorcery_object_field_register(sorcery, "transport", "websocket_write_timeout", AST_DEFAULT_WEBSOCKET_WRITE_TIMEOUT_STR, OPT_INT_T, PARSE_IN_RANGE, FLDSET(struct ast_sip_transport, write_timeout), 1, INT_MAX);
    ast_sorcery_object_field_register(sorcery, "transport", "allow_reload", "no", OPT_BOOL_T, 1, FLDSET(struct ast_sip_transport, allow_reload));
    ast_sorcery_object_field_register(sorcery, "transport", "symmetric_transport", "no", OPT_BOOL_T, 1, FLDSET(struct ast_sip_transport, symmetric_transport));
    ast_sip_register_endpoint_formatter(&endpoint_transport_formatter);
    cli_formatter = ao2_alloc(sizeof(struct ast_sip_cli_formatter_entry), NULL);
    if (!cli_formatter) {
       ast_log(LOG_ERROR, "Unable to allocate memory for cli formatter\n");
       return -1;
    }
    cli_formatter->name = "transport";
    cli_formatter->print_header = cli_print_header;
    cli_formatter->print_body = cli_print_body;
    cli_formatter->get_container = cli_get_container;
    cli_formatter->iterate = cli_iterate;
    cli_formatter->get_id = ast_sorcery_object_get_id;
    cli_formatter->retrieve_by_id = cli_retrieve_by_id;
    ast_sip_register_cli_formatter(cli_formatter);
    ast_cli_register_multiple(cli_commands, ARRAY_LEN(cli_commands));
    /* trigger load of transports from realtime by trying to revrieve them all */
    transports = ast_sorcery_retrieve_by_fields(sorcery, "transport", AST_RETRIEVE_FLAG_ALL | AST_RETRIEVE_FLAG_MULTIPLE, NULL);
    ao2_cleanup(transports);
    return 0;
 }
ast_sip_initialize_system()
int ast_sip_initialize_system (void)
Definition at line 175 of file config_system.c.
References __stringify, system_config::accept_multiple_sdp_answers, ao2_cleanup, ao2_container_count(), ast_log, AST_RETRIEVE_FLAG_ALL, AST_RETRIEVE_FLAG_MULTIPLE, ast_sorcery_alloc(), ast_sorcery_apply_default, ast_sorcery_load(), ast_sorcery_object_field_register, ast_sorcery_object_register_no_reload, ast_sorcery_open, ast_sorcery_retrieve_by_fields(), ast_sorcery_unref, system_config::compactheaders, DEFAULT_TIMER_B, DEFAULT_TIMER_T1, system_config::disable_rport, system_config::disable_tcp_switch, FLDSET, system_config::follow_early_media_fork, LOG_ERROR, NULL, OPT_BOOL_T, OPT_NOOP_T, OPT_UINT_T, RAII_VAR, system_alloc(), system_apply(), system_config::threadpool, system_config::timerb, and system_config::timert1.
Referenced by load_module().
 {
    RAII_VAR(struct ao2_container *, system_configs, NULL, ao2_cleanup);
    RAII_VAR(struct system_config *, system, NULL, ao2_cleanup);
    system_sorcery = ast_sorcery_open();
    if (!system_sorcery) {
       ast_log(LOG_ERROR, "Failed to open SIP system sorcery\n");
       return -1;
    }
    ast_sorcery_apply_default(system_sorcery, "system", "config", "pjsip.conf,criteria=type=system,single_object=yes,explicit_name=system");
    if (ast_sorcery_object_register_no_reload(system_sorcery, "system", system_alloc, NULL, system_apply)) {
       ast_log(LOG_ERROR, "Failed to register with sorcery (is res_sorcery_config loaded?)\n");
       ast_sorcery_unref(system_sorcery);
       system_sorcery = NULL;
       return -1;
    }
    ast_sorcery_object_field_register(system_sorcery, "system", "type", "", OPT_NOOP_T, 0, 0);
    ast_sorcery_object_field_register(system_sorcery, "system", "timer_t1", __stringify(DEFAULT_TIMER_T1),
          OPT_UINT_T, 0, FLDSET(struct system_config, timert1));
    ast_sorcery_object_field_register(system_sorcery, "system", "timer_b", __stringify(DEFAULT_TIMER_B),
          OPT_UINT_T, 0, FLDSET(struct system_config, timerb));
    ast_sorcery_object_field_register(system_sorcery, "system", "compact_headers", "no",
          OPT_BOOL_T, 1, FLDSET(struct system_config, compactheaders));
    ast_sorcery_object_field_register(system_sorcery, "system", "threadpool_initial_size", "0",
          OPT_UINT_T, 0, FLDSET(struct system_config, threadpool.initial_size));
    ast_sorcery_object_field_register(system_sorcery, "system", "threadpool_auto_increment", "5",
          OPT_UINT_T, 0, FLDSET(struct system_config, threadpool.auto_increment));
    ast_sorcery_object_field_register(system_sorcery, "system", "threadpool_idle_timeout", "60",
          OPT_UINT_T, 0, FLDSET(struct system_config, threadpool.idle_timeout));
    ast_sorcery_object_field_register(system_sorcery, "system", "threadpool_max_size", "50",
          OPT_UINT_T, 0, FLDSET(struct system_config, threadpool.max_size));
    ast_sorcery_object_field_register(system_sorcery, "system", "disable_tcp_switch", "yes",
          OPT_BOOL_T, 1, FLDSET(struct system_config, disable_tcp_switch));
    ast_sorcery_object_field_register(system_sorcery, "system", "follow_early_media_fork", "yes",
          OPT_BOOL_T, 1, FLDSET(struct system_config, follow_early_media_fork));
    ast_sorcery_object_field_register(system_sorcery, "system", "accept_multiple_sdp_answers", "no",
          OPT_BOOL_T, 1, FLDSET(struct system_config, accept_multiple_sdp_answers));
    ast_sorcery_object_field_register(system_sorcery, "system", "disable_rport", "no",
          OPT_BOOL_T, 1, FLDSET(struct system_config, disable_rport));
    ast_sorcery_load(system_sorcery);
    system_configs = ast_sorcery_retrieve_by_fields(system_sorcery, "system",
       AST_RETRIEVE_FLAG_MULTIPLE | AST_RETRIEVE_FLAG_ALL, NULL);
    if (ao2_container_count(system_configs)) {
       return 0;
    }
    /* No config present, allocate one and apply defaults */
    system = ast_sorcery_alloc(system_sorcery, "system", NULL);
    if (!system) {
       ast_log(LOG_ERROR, "Unable to allocate default system config.\n");
       ast_sorcery_unref(system_sorcery);
       return -1;
    }
    if (system_apply(system_sorcery, system)) {
       ast_log(LOG_ERROR, "Failed to apply default system config.\n");
       ast_sorcery_unref(system_sorcery);
       return -1;
    }
    return 0;
 }
ast_sip_initialize_transport_events()
int ast_sip_initialize_transport_events (void)
Definition at line 394 of file pjsip_transport_events.c.
References ACTIVE_TRANSPORTS_BUCKETS, AO2_ALLOC_OPT_LOCK_MUTEX, ao2_container_alloc_hash, ao2_global_obj_replace_unref, ao2_ref, ast_sip_get_pjsip_endpoint(), NULL, tpmgr_state_callback, and transport_state_callback().
Referenced by load_module().
 {
    pjsip_tpmgr *tpmgr;
    struct ao2_container *transports;
    tpmgr = pjsip_endpt_get_tpmgr(ast_sip_get_pjsip_endpoint());
    if (!tpmgr) {
       return -1;
    }
    transports = ao2_container_alloc_hash(AO2_ALLOC_OPT_LOCK_MUTEX, 0,
       ACTIVE_TRANSPORTS_BUCKETS, transport_monitor_hash_fn, NULL,
       transport_monitor_cmp_fn);
    if (!transports) {
       return -1;
    }
    ao2_global_obj_replace_unref(active_transports, transports);
    ao2_ref(transports, -1);
    tpmgr_state_callback = pjsip_tpmgr_get_state_cb(tpmgr);
    pjsip_tpmgr_set_state_cb(tpmgr, &transport_state_callback);
    return 0;
 }
ast_sip_initialize_transport_management()
int ast_sip_initialize_transport_management (void)
Definition at line 372 of file pjsip_transport_management.c.
References AO2_ALLOC_OPT_LOCK_MUTEX, ao2_container_alloc_hash, ao2_global_obj_release, ao2_global_obj_replace_unref, ao2_ref, ast_log, AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, ast_sched_context_create(), ast_sched_context_destroy(), ast_sched_start_thread(), ast_sip_get_sorcery(), ast_sip_register_service(), ast_sip_transport_state_register(), ast_sorcery_observer_add(), ast_sorcery_reload_object(), idle_monitor_module, LOG_ERROR, monitored_transport_cmp_fn(), monitored_transport_hash_fn(), NULL, and TRANSPORTS_BUCKETS.
Referenced by load_module().
 {
    struct ao2_container *transports;
    transports = ao2_container_alloc_hash(AO2_ALLOC_OPT_LOCK_MUTEX, 0, TRANSPORTS_BUCKETS,
       monitored_transport_hash_fn, NULL, monitored_transport_cmp_fn);
    if (!transports) {
       ast_log(LOG_ERROR, "Could not create container for transports to perform keepalive on.\n");
       return AST_MODULE_LOAD_DECLINE;
    }
    ao2_global_obj_replace_unref(monitored_transports, transports);
    ao2_ref(transports, -1);
    sched = ast_sched_context_create();
    if (!sched) {
       ast_log(LOG_ERROR, "Failed to create keepalive scheduler context.\n");
       ao2_global_obj_release(monitored_transports);
       return AST_MODULE_LOAD_DECLINE;
    }
    if (ast_sched_start_thread(sched)) {
       ast_log(LOG_ERROR, "Failed to start keepalive scheduler thread\n");
       ast_sched_context_destroy(sched);
       sched = NULL;
       ao2_global_obj_release(monitored_transports);
       return AST_MODULE_LOAD_DECLINE;
    }
    ast_sip_register_service(&idle_monitor_module);
    ast_sip_transport_state_register(&monitored_transport_reg);
    ast_sorcery_observer_add(ast_sip_get_sorcery(), "global", &keepalive_global_observer);
    ast_sorcery_reload_object(ast_sip_get_sorcery(), "global");
    return AST_MODULE_LOAD_SUCCESS;
 }
ast_sip_overload_trigger_to_str()
const char* ast_sip_overload_trigger_to_str (enum ast_sip_taskprocessor_overload_trigger trigger)
Definition at line 546 of file config_global.c.
References ARRAY_IN_BOUNDS, and overload_trigger_map.
Referenced by overload_trigger_to_str().
 {
    return ARRAY_IN_BOUNDS(trigger, overload_trigger_map) ?
       overload_trigger_map[trigger] : "";
 }
ast_sip_persistent_endpoint_add_to_regcontext()
int ast_sip_persistent_endpoint_add_to_regcontext (const char * regcontext)
Definition at line 1312 of file pjsip_configuration.c.
References add_to_regcontext(), ao2_callback, ast_context_find_or_create(), ast_log, ast_strlen_zero, LOG_ERROR, NULL, and OBJ_NODATA.
Referenced by check_regcontext().
 {
    if (ast_strlen_zero(regcontext)) {
       return 0;
    }
    /* Make sure the regcontext exists */
    if (!ast_context_find_or_create(NULL, NULL, regcontext, "PJSIP")) {
       ast_log(LOG_ERROR, "Failed to create regcontext '%s'\n", regcontext);
       return -1;
    }
    /* Add any online endpoints */
    ao2_callback(persistent_endpoints, OBJ_NODATA, add_to_regcontext, (void *)regcontext);
    return 0;
 }
ast_sip_validate_uri_length()
int ast_sip_validate_uri_length (const char * uri)
Definition at line 525 of file location.c.
References ast_strdupa, ast_strip_quoted(), host, pj_max_hostname, pjsip_max_url_size, and strsep().
Referenced by permanent_uri_handler(), sip_outbound_registration_apply(), and validate_publish_config().
 {
    int max_length = pj_max_hostname - 1;
    char *contact = ast_strdupa(contact_uri);
    char *host;
    char *at;
    int theres_a_port = 0;
    if (strlen(contact_uri) > pjsip_max_url_size - 1) {
       return -1;
    }
    contact = ast_strip_quoted(contact, "<", ">");
    if (!strncasecmp(contact, "sip:", 4)) {
       host = contact + 4;
    } else if (!strncasecmp(contact, "sips:", 5)) {
       host = contact + 5;
    } else {
       /* Not a SIP URI */
       return -1;
    }
    at = strchr(contact, '@');
    if (at) {
       /* sip[s]:user@host */
       host = at + 1;
    }
    if (host[0] == '[') {
       /* Host is an IPv6 address. Just get up to the matching bracket */
       char *close_bracket;
       close_bracket = strchr(host, ']');
       if (!close_bracket) {
          return -1;
       }
       close_bracket++;
       if (*close_bracket == ':') {
          theres_a_port = 1;
       }
       *close_bracket = '\0';
    } else {
       /* uri parameters could contain ';' so trim them off first */
       host = strsep(&host, ";?");
       /* Host is FQDN or IPv4 address. Need to find closing delimiter */
       if (strchr(host, ':')) {
          theres_a_port = 1;
          host = strsep(&host, ":");
       }
    }
    if (!theres_a_port) {
       max_length -= strlen("_sips.tcp.");
    }
    if (strlen(host) > max_length) {
       return -1;
    }
    return 0;
 }
ast_sip_will_uri_survive_restart()
int ast_sip_will_uri_survive_restart (pjsip_sip_uri * uri, struct ast_sip_endpoint * endpoint, pjsip_rx_data * rdata)
Definition at line 3723 of file res_pjsip.c.
References ast_sip_endpoint::nat, result, and ast_sip_endpoint_nat_configuration::rewrite_contact.
Referenced by register_aor_core(), and subscription_persistence_update().
 {
    pj_str_t host_name;
    int result = 1;
    /* Determine if the contact cannot survive a restart/boot. */
    if (uri->port == rdata->pkt_info.src_port
       && !pj_strcmp(&uri->host,
          pj_cstr(&host_name, rdata->pkt_info.src_name))
       /* We have already checked if the URI scheme is sip: or sips: */
       && PJSIP_TRANSPORT_IS_RELIABLE(rdata->tp_info.transport)) {
       pj_str_t type_name;
       /* Determine the transport parameter value */
       if (!strcasecmp("WSS", rdata->tp_info.transport->type_name)) {
          /* WSS is special, as it needs to be ws. */
          pj_cstr(&type_name, "ws");
       } else {
          pj_cstr(&type_name, rdata->tp_info.transport->type_name);
       }
       if (!pj_stricmp(&uri->transport_param, &type_name)
          && (endpoint->nat.rewrite_contact
             /* Websockets are always rewritten */
             || !pj_stricmp(&uri->transport_param,
                pj_cstr(&type_name, "ws")))) {
          /*
           * The contact was rewritten to the reliable transport's
           * source address.  Disconnecting the transport for any
           * reason invalidates the contact.
           */
          result = 0;
       }
    }
    return result;
 }
sip_cli_print_global()
int sip_cli_print_global (struct ast_sip_cli_context * context)
Definition at line 612 of file config_global.c.
References ao2_ref, ast_sip_cli_print_sorcery_objectset(), ast_sip_get_sorcery(), ast_sorcery_alloc(), ast_str_append(), get_global_cfg(), NULL, and ast_sip_cli_context::output_buffer.
Referenced by cli_show_settings().
 {
    struct global_config *cfg = get_global_cfg();
    if (!cfg) {
       cfg = ast_sorcery_alloc(ast_sip_get_sorcery(), "global", NULL);
       if (!cfg) {
          return -1;
       }
    }
    ast_str_append(&context->output_buffer, 0, "\nGlobal Settings:\n\n");
    ast_sip_cli_print_sorcery_objectset(cfg, context, 0);
    ao2_ref(cfg, -1);
    return 0;
 }
sip_cli_print_system()
int sip_cli_print_system (struct ast_sip_cli_context * context)
Definition at line 157 of file config_system.c.
References ao2_ref, ast_sip_cli_print_sorcery_objectset(), ast_sorcery_alloc(), ast_str_append(), get_system_cfg(), NULL, and ast_sip_cli_context::output_buffer.
Referenced by cli_show_settings().
 {
    struct system_config *cfg = get_system_cfg();
    if (!cfg) {
       cfg = ast_sorcery_alloc(system_sorcery, "system", NULL);
       if (!cfg) {
          return -1;
       }
    }
    ast_str_append(&context->output_buffer, 0, "\nSystem Settings:\n\n");
    ast_sip_cli_print_sorcery_objectset(cfg, context, 0);
    ao2_ref(cfg, -1);
    return 0;
 }
sip_get_threadpool_options()
void sip_get_threadpool_options (struct ast_threadpool_options * threadpool_options)
Definition at line 70 of file config_system.c.
References sip_threadpool_options.
Referenced by load_module().
 {
    *threadpool_options = sip_threadpool_options;
 }