Asterisk - The Open Source Telephony Project: ast_unreal_pvt_callbacks Struct Reference
ast_unreal_pvt_callbacks Struct Reference
Callbacks that can be provided by concrete implementations of the unreal channel driver that will be called when events occur in the unreal layer.
#include <core_unreal.h>
Data Fields
void(*const optimization_finished)(struct ast_unreal_pvt *p, int success, unsigned int id)
Called when an optimization attempt completed successfully.
void(*const optimization_started)(struct ast_unreal_pvt *p, struct ast_channel *source, enum ast_unreal_channel_indicator dest, unsigned int id)
Called when an optimization attempt has started.
Detailed Description
Callbacks that can be provided by concrete implementations of the unreal channel driver that will be called when events occur in the unreal layer.
Definition at line 58 of file core_unreal.h.
Field Documentation
optimization_finished
void(* const optimization_finished) (struct ast_unreal_pvt *p, int success, unsigned int id)
Called when an optimization attempt completed successfully.
Note
p is locked when this callback is called
Parameters
p The ast_unreal_pvt object
success Non-zero if the optimization succeeded, zero if the optimization met with fatal and permanent error
id Unique identifier for this optimization. Same as the one from the optimization_started call
Definition at line 81 of file core_unreal.h.
Referenced by try_merge_optimize_out(), and try_swap_optimize_out().
optimization_started
void(* const optimization_started) (struct ast_unreal_pvt *p, struct ast_channel *source, enum ast_unreal_channel_indicator dest, unsigned int id)
Called when an optimization attempt has started.
Note
p is locked when this callback is called
Parameters
p The ast_unreal_pvt object
source The channel that is optimizing into an unreal_pvt channel's bridge. If NULL, the optimization is being accomplished via a bridge merge.
dest Indicator of which channel's bridge in the unreal_pvt will survive the optimization
id Unique identifier for this optimization operation.
Definition at line 69 of file core_unreal.h.
Referenced by try_merge_optimize_out(), and try_swap_optimize_out().
The documentation for this struct was generated from the following file:
core_unreal.h