Asterisk - The Open Source Telephony Project: sig_pri.h File Reference
sig_pri.h File Reference
Interface header for PRI signaling module.
#include "asterisk/channel.h"
#include "asterisk/frame.h"
#include "asterisk/ccss.h"
#include <libpri.h>
#include <dahdi/user.h>
Data Structures
struct sig_pri_callback
struct sig_pri_chan
struct sig_pri_span
Macros
#define DAHDI_CHAN_MAPPING_LOGICAL 1
#define DAHDI_CHAN_MAPPING_PHYSICAL 0
#define DAHDI_OVERLAPDIAL_BOTH (DAHDI_OVERLAPDIAL_INCOMING|DAHDI_OVERLAPDIAL_OUTGOING)
#define DAHDI_OVERLAPDIAL_INCOMING 2
#define DAHDI_OVERLAPDIAL_NONE 0
#define DAHDI_OVERLAPDIAL_OUTGOING 1
#define SIG_BRI (0x2000000 | DAHDI_SIG_CLEAR)
#define SIG_BRI_PTMP (0X4000000 | DAHDI_SIG_CLEAR)
#define SIG_PRI DAHDI_SIG_CLEAR
#define SIG_PRI_AOC_GRANT_D (1 << 1)
#define SIG_PRI_AOC_GRANT_E (1 << 2)
#define SIG_PRI_AOC_GRANT_S (1 << 0)
#define SIG_PRI_DEBUG_DEFAULT 0
#define SIG_PRI_DEBUG_NORMAL (PRI_DEBUG_APDU | PRI_DEBUG_Q931_STATE | PRI_DEBUG_Q921_STATE)
#define SIG_PRI_MAX_CHANNELS 672
#define SIG_PRI_NUM_DCHANS 4
Enumerations
enum sig_pri_call_level {
SIG_PRI_CALL_LEVEL_IDLE, SIG_PRI_CALL_LEVEL_SETUP, SIG_PRI_CALL_LEVEL_OVERLAP, SIG_PRI_CALL_LEVEL_PROCEEDING,
SIG_PRI_CALL_LEVEL_ALERTING, SIG_PRI_CALL_LEVEL_DEFER_DIAL, SIG_PRI_CALL_LEVEL_CONNECT
}
enum sig_pri_colp_signaling { SIG_PRI_COLP_BLOCK, SIG_PRI_COLP_CONNECT, SIG_PRI_COLP_UPDATE }
enum sig_pri_law { SIG_PRI_DEFLAW = 0, SIG_PRI_ULAW, SIG_PRI_ALAW }
enum sig_pri_moh_event { SIG_PRI_MOH_EVENT_RESET, SIG_PRI_MOH_EVENT_HOLD, SIG_PRI_MOH_EVENT_UNHOLD, SIG_PRI_MOH_EVENT_NUM }
enum sig_pri_moh_signaling { SIG_PRI_MOH_SIGNALING_MOH, SIG_PRI_MOH_SIGNALING_NOTIFY }
enum sig_pri_moh_state { SIG_PRI_MOH_STATE_IDLE, SIG_PRI_MOH_STATE_NOTIFY, SIG_PRI_MOH_STATE_MOH, SIG_PRI_MOH_STATE_NUM }
enum sig_pri_reset_state { SIG_PRI_RESET_IDLE, SIG_PRI_RESET_ACTIVE, SIG_PRI_RESET_NO_ACK }
enum sig_pri_tone {
SIG_PRI_TONE_RINGTONE = 0, SIG_PRI_TONE_STUTTER, SIG_PRI_TONE_CONGESTION, SIG_PRI_TONE_DIALTONE,
SIG_PRI_TONE_DIALRECALL, SIG_PRI_TONE_INFO, SIG_PRI_TONE_BUSY
}
Functions
void pri_event_alarm (struct sig_pri_span *pri, int index, int before_start_pri)
void pri_event_noalarm (struct sig_pri_span *pri, int index, int before_start_pri)
int pri_is_up (struct sig_pri_span *pri)
int pri_send_callrerouting_facility_exec (struct sig_pri_chan *p, enum ast_channel_state chanstate, const char *destination, const char *original, const char *reason)
int pri_send_keypad_facility_exec (struct sig_pri_chan *p, const char *digits)
int sig_pri_ami_show_spans (struct mansession *s, const char *show_cmd, struct sig_pri_span *pri, const int *dchannels, const char *action_id)
int sig_pri_answer (struct sig_pri_chan *p, struct ast_channel *ast)
int sig_pri_available (struct sig_pri_chan **pvt, int is_specific_channel)
int sig_pri_call (struct sig_pri_chan *p, struct ast_channel *ast, const char *rdest, int timeout, int layer1)
int sig_pri_cc_agent_callee_available (struct ast_cc_agent *agent)
void sig_pri_cc_agent_destructor (struct ast_cc_agent *agent)
int sig_pri_cc_agent_init (struct ast_cc_agent *agent, struct sig_pri_chan *pvt_chan)
int sig_pri_cc_agent_party_b_free (struct ast_cc_agent *agent)
void sig_pri_cc_agent_req_rsp (struct ast_cc_agent *agent, enum ast_cc_agent_response_reason reason)
int sig_pri_cc_agent_start_monitoring (struct ast_cc_agent *agent)
int sig_pri_cc_agent_start_offer_timer (struct ast_cc_agent *agent)
int sig_pri_cc_agent_status_req (struct ast_cc_agent *agent)
int sig_pri_cc_agent_stop_offer_timer (struct ast_cc_agent *agent)
int sig_pri_cc_agent_stop_ringing (struct ast_cc_agent *agent)
int sig_pri_cc_monitor_cancel_available_timer (struct ast_cc_monitor *monitor, int *sched_id)
void sig_pri_cc_monitor_destructor (void *monitor_pvt)
int sig_pri_cc_monitor_req_cc (struct ast_cc_monitor *monitor, int *available_timer_id)
int sig_pri_cc_monitor_status_rsp (struct ast_cc_monitor *monitor, enum ast_device_state devstate)
int sig_pri_cc_monitor_suspend (struct ast_cc_monitor *monitor)
int sig_pri_cc_monitor_unsuspend (struct ast_cc_monitor *monitor)
void sig_pri_chan_alarm_notify (struct sig_pri_chan *p, int noalarm)
void sig_pri_chan_delete (struct sig_pri_chan *doomed)
struct sig_pri_chan * sig_pri_chan_new (void *pvt_data, struct sig_pri_span *pri, int logicalspan, int channo, int trunkgroup)
void sig_pri_cli_show_channels (int fd, struct sig_pri_span *pri)
void sig_pri_cli_show_channels_header (int fd)
void sig_pri_cli_show_span (int fd, int *dchannels, struct sig_pri_span *pri)
void sig_pri_cli_show_spans (int fd, int span, struct sig_pri_span *pri)
void sig_pri_dial_complete (struct sig_pri_chan *pvt, struct ast_channel *ast)
int sig_pri_digit_begin (struct sig_pri_chan *pvt, struct ast_channel *ast, char digit)
void sig_pri_extract_called_num_subaddr (struct sig_pri_chan *p, const char *rdest, char *called, size_t called_buff_size)
void sig_pri_fixup (struct ast_channel *oldchan, struct ast_channel *newchan, struct sig_pri_chan *pchan)
int sig_pri_hangup (struct sig_pri_chan *p, struct ast_channel *ast)
int sig_pri_indicate (struct sig_pri_chan *p, struct ast_channel *chan, int condition, const void *data, size_t datalen)
void sig_pri_init_pri (struct sig_pri_span *pri)
int sig_pri_is_alarm_ignored (struct sig_pri_span *pri)
int sig_pri_is_chan_available (struct sig_pri_chan *pvt)
int sig_pri_load (const char *cc_type_name)
struct ast_channel * sig_pri_request (struct sig_pri_chan *p, enum sig_pri_law law, const struct ast_assigned_ids *assignedids, const struct ast_channel *requestor, int transfercapability)
void sig_pri_set_alarm (struct sig_pri_chan *p, int in_alarm)
int sig_pri_start_pri (struct sig_pri_span *pri)
void sig_pri_stop_pri (struct sig_pri_span *pri)
void sig_pri_unload (void)
Variables
struct sig_pri_callback sig_pri_callbacks
Detailed Description
Interface header for PRI signaling module.
Author
Matthew Fredrickson cresl.nosp@m.in@d.nosp@m.igium.nosp@m..com
Definition in file sig_pri.h.
Macro Definition Documentation
DAHDI_CHAN_MAPPING_LOGICAL
#define DAHDI_CHAN_MAPPING_LOGICAL 1
Definition at line 250 of file sig_pri.h.
Referenced by process_dahdi().
DAHDI_CHAN_MAPPING_PHYSICAL
#define DAHDI_CHAN_MAPPING_PHYSICAL 0
Definition at line 249 of file sig_pri.h.
Referenced by dahdi_chan_conf_default(), and process_dahdi().
DAHDI_OVERLAPDIAL_BOTH
#define DAHDI_OVERLAPDIAL_BOTH (DAHDI_OVERLAPDIAL_INCOMING|DAHDI_OVERLAPDIAL_OUTGOING)
Definition at line 256 of file sig_pri.h.
Referenced by process_dahdi().
DAHDI_OVERLAPDIAL_INCOMING
#define DAHDI_OVERLAPDIAL_INCOMING 2
Definition at line 255 of file sig_pri.h.
Referenced by dahdi_handle_event(), dahdi_read(), and process_dahdi().
DAHDI_OVERLAPDIAL_NONE
#define DAHDI_OVERLAPDIAL_NONE 0
Definition at line 253 of file sig_pri.h.
Referenced by process_dahdi().
DAHDI_OVERLAPDIAL_OUTGOING
#define DAHDI_OVERLAPDIAL_OUTGOING 1
Definition at line 254 of file sig_pri.h.
Referenced by dahdi_read(), and process_dahdi().
SIG_BRI
#define SIG_BRI (0x2000000 | DAHDI_SIG_CLEAR)
Definition at line 245 of file sig_pri.h.
SIG_BRI_PTMP
#define SIG_BRI_PTMP (0X4000000 | DAHDI_SIG_CLEAR)
Definition at line 246 of file sig_pri.h.
SIG_PRI
#define SIG_PRI DAHDI_SIG_CLEAR
Definition at line 244 of file sig_pri.h.
SIG_PRI_AOC_GRANT_D
#define SIG_PRI_AOC_GRANT_D (1 << 1)
Definition at line 54 of file sig_pri.h.
Referenced by process_dahdi().
SIG_PRI_AOC_GRANT_E
#define SIG_PRI_AOC_GRANT_E (1 << 2)
Definition at line 55 of file sig_pri.h.
Referenced by process_dahdi().
SIG_PRI_AOC_GRANT_S
#define SIG_PRI_AOC_GRANT_S (1 << 0)
Definition at line 53 of file sig_pri.h.
Referenced by process_dahdi().
SIG_PRI_DEBUG_DEFAULT
#define SIG_PRI_DEBUG_DEFAULT 0
PRI debug message flags set on initial startup.
Definition at line 50 of file sig_pri.h.
SIG_PRI_DEBUG_NORMAL
#define SIG_PRI_DEBUG_NORMAL (PRI_DEBUG_APDU | PRI_DEBUG_Q931_STATE | PRI_DEBUG_Q921_STATE)
PRI debug message flags when normal PRI debugging is turned on at the command line.
Definition at line 41 of file sig_pri.h.
Referenced by dahdi_cc_callback().
SIG_PRI_MAX_CHANNELS
#define SIG_PRI_MAX_CHANNELS 672
No more than a DS3 per trunk group
Definition at line 242 of file sig_pri.h.
SIG_PRI_NUM_DCHANS
#define SIG_PRI_NUM_DCHANS 4
No more than 4 d-channels
Definition at line 241 of file sig_pri.h.
Referenced by __unload_module(), dahdi_cc_callback(), dahdi_create_channel_range(), dahdi_restart(), mkintf(), restart_monitor(), and setup_dahdi_int().
Enumeration Type Documentation
sig_pri_call_level
enum sig_pri_call_level
Call establishment life cycle level for simple comparisons.
Enumerator
SIG_PRI_CALL_LEVEL_IDLE
Call does not exist.
SIG_PRI_CALL_LEVEL_SETUP
Call is present but has no response yet. (SETUP)
SIG_PRI_CALL_LEVEL_OVERLAP
Call is collecting digits for overlap dialing. (SETUP ACKNOWLEDGE)
SIG_PRI_CALL_LEVEL_PROCEEDING
Call routing is happening. (PROCEEDING)
SIG_PRI_CALL_LEVEL_ALERTING
Called party is being alerted of the call. (ALERTING)
SIG_PRI_CALL_LEVEL_DEFER_DIAL
Call is dialing 'w' deferred digits. (CONNECT)
SIG_PRI_CALL_LEVEL_CONNECT
Call is connected/answered. (CONNECT)
Definition at line 135 of file sig_pri.h.
{
    /*! Call does not exist. */
    SIG_PRI_CALL_LEVEL_IDLE,
    /*! Call is present but has no response yet. (SETUP) */
    SIG_PRI_CALL_LEVEL_SETUP,
    /*! Call is collecting digits for overlap dialing. (SETUP ACKNOWLEDGE) */
    SIG_PRI_CALL_LEVEL_OVERLAP,
    /*! Call routing is happening. (PROCEEDING) */
    SIG_PRI_CALL_LEVEL_PROCEEDING,
    /*! Called party is being alerted of the call. (ALERTING) */
    SIG_PRI_CALL_LEVEL_ALERTING,
    /*! Call is dialing 'w' deferred digits. (CONNECT) */
    SIG_PRI_CALL_LEVEL_DEFER_DIAL,
    /*! Call is connected/answered. (CONNECT) */
    SIG_PRI_CALL_LEVEL_CONNECT,
 };
sig_pri_colp_signaling
enum sig_pri_colp_signaling
Enumerator
SIG_PRI_COLP_BLOCK
Block all connected line updates.
SIG_PRI_COLP_CONNECT
Only send connected line information with the CONNECT message.
SIG_PRI_COLP_UPDATE
Allow all connected line updates.
Definition at line 437 of file sig_pri.h.
{
    /*! Block all connected line updates. */
    SIG_PRI_COLP_BLOCK,
    /*! Only send connected line information with the CONNECT message. */
    SIG_PRI_COLP_CONNECT,
    /*! Allow all connected line updates. */
    SIG_PRI_COLP_UPDATE,
 };
sig_pri_law
enum sig_pri_law
Enumerator
SIG_PRI_DEFLAW
SIG_PRI_ULAW
SIG_PRI_ALAW
Definition at line 67 of file sig_pri.h.
                  {
    SIG_PRI_DEFLAW = 0,
    SIG_PRI_ULAW,
    SIG_PRI_ALAW
 };
sig_pri_moh_event
enum sig_pri_moh_event
Enumerator
SIG_PRI_MOH_EVENT_RESET
Reset the MOH state machine. (Because of hangup.)
SIG_PRI_MOH_EVENT_HOLD
Bridged peer placed this channel on hold.
SIG_PRI_MOH_EVENT_UNHOLD
Bridged peer took this channel off hold.
SIG_PRI_MOH_EVENT_NUM
Number of MOH events. Must be last in enum.
Definition at line 110 of file sig_pri.h.
{
    /*! Reset the MOH state machine. (Because of hangup.) */
    SIG_PRI_MOH_EVENT_RESET,
    /*! Bridged peer placed this channel on hold. */
    SIG_PRI_MOH_EVENT_HOLD,
    /*! Bridged peer took this channel off hold. */
    SIG_PRI_MOH_EVENT_UNHOLD,
 #if defined(HAVE_PRI_CALL_HOLD)
    /*! The hold request was successfully acknowledged. */
    SIG_PRI_MOH_EVENT_HOLD_ACK,
    /*! The hold request was rejected. */
    SIG_PRI_MOH_EVENT_HOLD_REJ,
    /*! The unhold request was successfully acknowledged. */
    SIG_PRI_MOH_EVENT_RETRIEVE_ACK,
    /*! The unhold request was rejected. */
    SIG_PRI_MOH_EVENT_RETRIEVE_REJ,
    /*! The remote party took this channel off hold. */
    SIG_PRI_MOH_EVENT_REMOTE_RETRIEVE_ACK,
 #endif   /* defined(HAVE_PRI_CALL_HOLD) */
    /*! Number of MOH events.  Must be last in enum. */
    SIG_PRI_MOH_EVENT_NUM
 };
sig_pri_moh_signaling
enum sig_pri_moh_signaling
Enumerator
SIG_PRI_MOH_SIGNALING_MOH
Generate MOH to the remote party.
SIG_PRI_MOH_SIGNALING_NOTIFY
Send hold notification signaling to the remote party.
Definition at line 73 of file sig_pri.h.
{
    /*! Generate MOH to the remote party. */
    SIG_PRI_MOH_SIGNALING_MOH,
    /*! Send hold notification signaling to the remote party. */
    SIG_PRI_MOH_SIGNALING_NOTIFY,
 #if defined(HAVE_PRI_CALL_HOLD)
    /*! Use HOLD/RETRIEVE signaling to release the B channel while on hold. */
    SIG_PRI_MOH_SIGNALING_HOLD,
 #endif   /* defined(HAVE_PRI_CALL_HOLD) */
 };
sig_pri_moh_state
enum sig_pri_moh_state
Enumerator
SIG_PRI_MOH_STATE_IDLE
Bridged peer has not put us on hold.
SIG_PRI_MOH_STATE_NOTIFY
Bridged peer has put us on hold and we were to notify the remote party.
SIG_PRI_MOH_STATE_MOH
Bridged peer has put us on hold and we were to play MOH or HOLD/RETRIEVE fallback.
SIG_PRI_MOH_STATE_NUM
Number of MOH states. Must be last in enum.
Definition at line 84 of file sig_pri.h.
{
    /*! Bridged peer has not put us on hold. */
    SIG_PRI_MOH_STATE_IDLE,
    /*! Bridged peer has put us on hold and we were to notify the remote party. */
    SIG_PRI_MOH_STATE_NOTIFY,
    /*! Bridged peer has put us on hold and we were to play MOH or HOLD/RETRIEVE fallback. */
    SIG_PRI_MOH_STATE_MOH,
 #if defined(HAVE_PRI_CALL_HOLD)
    /*! Requesting to put channel on hold. */
    SIG_PRI_MOH_STATE_HOLD_REQ,
    /*! Trying to go on hold when bridged peer requested to unhold. */
    SIG_PRI_MOH_STATE_PEND_UNHOLD,
    /*! Channel is held. */
    SIG_PRI_MOH_STATE_HOLD,
    /*! Requesting to take channel out of hold. */
    SIG_PRI_MOH_STATE_RETRIEVE_REQ,
    /*! Trying to take channel out of hold when bridged peer requested to hold. */
    SIG_PRI_MOH_STATE_PEND_HOLD,
    /*! Failed to take the channel out of hold. No B channels were available? */
    SIG_PRI_MOH_STATE_RETRIEVE_FAIL,
 #endif   /* defined(HAVE_PRI_CALL_HOLD) */
    /*! Number of MOH states.  Must be last in enum. */
    SIG_PRI_MOH_STATE_NUM
 };
sig_pri_reset_state
enum sig_pri_reset_state
Enumerator
SIG_PRI_RESET_IDLE
The channel is not being RESTARTed.
SIG_PRI_RESET_ACTIVE
The channel is being RESTARTed.
Note
Waiting for a RESTART ACKNOWLEDGE from the peer.
SIG_PRI_RESET_NO_ACK
Peer may not be sending the expected RESTART ACKNOWLEDGE.
We have already received a SETUP on this channel. If another SETUP comes in on this channel then the peer considers this channel useable. Assume that the peer is never going to give us a RESTART ACKNOWLEDGE and assume that we have received one. This is not according to Q.931, but some peers occasionally fail to send a RESTART ACKNOWLEDGE.
Definition at line 152 of file sig_pri.h.
{
    /*! \brief The channel is not being RESTARTed. */
    SIG_PRI_RESET_IDLE,
    /*!
     * \brief The channel is being RESTARTed.
     * \note Waiting for a RESTART ACKNOWLEDGE from the peer.
     */
    SIG_PRI_RESET_ACTIVE,
    /*!
     * \brief Peer may not be sending the expected RESTART ACKNOWLEDGE.
     *
     * \details We have already received a SETUP on this channel.
     * If another SETUP comes in on this channel then the peer
     * considers this channel useable.  Assume that the peer is
     * never going to give us a RESTART ACKNOWLEDGE and assume that
     * we have received one.  This is not according to Q.931, but
     * some peers occasionally fail to send a RESTART ACKNOWLEDGE.
     */
    SIG_PRI_RESET_NO_ACK,
 };
sig_pri_tone
enum sig_pri_tone
Enumerator
SIG_PRI_TONE_RINGTONE
SIG_PRI_TONE_STUTTER
SIG_PRI_TONE_CONGESTION
SIG_PRI_TONE_DIALTONE
SIG_PRI_TONE_DIALRECALL
SIG_PRI_TONE_INFO
SIG_PRI_TONE_BUSY
Definition at line 57 of file sig_pri.h.
                   {
    SIG_PRI_TONE_RINGTONE = 0,
    SIG_PRI_TONE_STUTTER,
    SIG_PRI_TONE_CONGESTION,
    SIG_PRI_TONE_DIALTONE,
    SIG_PRI_TONE_DIALRECALL,
    SIG_PRI_TONE_INFO,
    SIG_PRI_TONE_BUSY,
 };
Function Documentation
pri_event_alarm()
void pri_event_alarm (struct sig_pri_span * pri, int index, int before_start_pri)
Referenced by dahdi_cc_callback(), and my_on_hook().
pri_event_noalarm()
void pri_event_noalarm (struct sig_pri_span * pri, int index, int before_start_pri)
Referenced by dahdi_cc_callback(), and my_on_hook().
pri_is_up()
int pri_is_up (struct sig_pri_span * pri)
pri_send_callrerouting_facility_exec()
int pri_send_callrerouting_facility_exec (struct sig_pri_chan * p, enum ast_channel_state chanstate, const char * destination, const char * original, const char * reason)
Referenced by destroy_all_channels().
pri_send_keypad_facility_exec()
int pri_send_keypad_facility_exec (struct sig_pri_chan * p, const char * digits)
Referenced by destroy_all_channels().
sig_pri_ami_show_spans()
int sig_pri_ami_show_spans (struct mansession * s, const char * show_cmd, struct sig_pri_span * pri, const int * dchannels, const char * action_id)
Referenced by action_dahdishowchannels().
sig_pri_answer()
int sig_pri_answer (struct sig_pri_chan * p, struct ast_channel * ast)
Referenced by dahdi_answer().
sig_pri_available()
int sig_pri_available (struct sig_pri_chan ** pvt, int is_specific_channel)
Referenced by available().
sig_pri_call()
int sig_pri_call (struct sig_pri_chan * p, struct ast_channel * ast, const char * rdest, int timeout, int layer1)
Referenced by dahdi_call().
sig_pri_cc_agent_callee_available()
int sig_pri_cc_agent_callee_available (struct ast_cc_agent * agent)
Referenced by action_dahdishowchannels().
sig_pri_cc_agent_destructor()
void sig_pri_cc_agent_destructor (struct ast_cc_agent * agent)
Referenced by action_dahdishowchannels().
sig_pri_cc_agent_init()
int sig_pri_cc_agent_init (struct ast_cc_agent * agent, struct sig_pri_chan * pvt_chan)
Referenced by action_dahdishowchannels().
sig_pri_cc_agent_party_b_free()
int sig_pri_cc_agent_party_b_free (struct ast_cc_agent * agent)
Referenced by action_dahdishowchannels().
sig_pri_cc_agent_req_rsp()
void sig_pri_cc_agent_req_rsp (struct ast_cc_agent * agent, enum ast_cc_agent_response_reason reason)
Referenced by action_dahdishowchannels().
sig_pri_cc_agent_start_monitoring()
int sig_pri_cc_agent_start_monitoring (struct ast_cc_agent * agent)
Referenced by action_dahdishowchannels().
sig_pri_cc_agent_start_offer_timer()
int sig_pri_cc_agent_start_offer_timer (struct ast_cc_agent * agent)
Referenced by action_dahdishowchannels().
sig_pri_cc_agent_status_req()
int sig_pri_cc_agent_status_req (struct ast_cc_agent * agent)
Referenced by action_dahdishowchannels().
sig_pri_cc_agent_stop_offer_timer()
int sig_pri_cc_agent_stop_offer_timer (struct ast_cc_agent * agent)
Referenced by action_dahdishowchannels().
sig_pri_cc_agent_stop_ringing()
int sig_pri_cc_agent_stop_ringing (struct ast_cc_agent * agent)
Referenced by action_dahdishowchannels().
sig_pri_cc_monitor_cancel_available_timer()
int sig_pri_cc_monitor_cancel_available_timer (struct ast_cc_monitor * monitor, int * sched_id)
Referenced by action_dahdishowchannels().
sig_pri_cc_monitor_destructor()
void sig_pri_cc_monitor_destructor (void * monitor_pvt)
Referenced by action_dahdishowchannels().
sig_pri_cc_monitor_req_cc()
int sig_pri_cc_monitor_req_cc (struct ast_cc_monitor * monitor, int * available_timer_id)
Referenced by action_dahdishowchannels().
sig_pri_cc_monitor_status_rsp()
int sig_pri_cc_monitor_status_rsp (struct ast_cc_monitor * monitor, enum ast_device_state devstate)
Referenced by action_dahdishowchannels().
sig_pri_cc_monitor_suspend()
int sig_pri_cc_monitor_suspend (struct ast_cc_monitor * monitor)
Referenced by action_dahdishowchannels().
sig_pri_cc_monitor_unsuspend()
int sig_pri_cc_monitor_unsuspend (struct ast_cc_monitor * monitor)
Referenced by action_dahdishowchannels().
sig_pri_chan_alarm_notify()
void sig_pri_chan_alarm_notify (struct sig_pri_chan * p, int noalarm)
Referenced by dahdi_handle_event(), and handle_init_event().
sig_pri_chan_delete()
void sig_pri_chan_delete (struct sig_pri_chan * doomed)
Referenced by destroy_dahdi_pvt().
sig_pri_chan_new()
struct sig_pri_chan* sig_pri_chan_new (void * pvt_data, struct sig_pri_span * pri, int logicalspan, int channo, int trunkgroup)
Referenced by available(), and mkintf().
sig_pri_cli_show_channels()
void sig_pri_cli_show_channels (int fd, struct sig_pri_span * pri)
Referenced by dahdi_cc_callback().
sig_pri_cli_show_channels_header()
void sig_pri_cli_show_channels_header (int fd)
Referenced by dahdi_cc_callback().
sig_pri_cli_show_span()
void sig_pri_cli_show_span (int fd, int * dchannels, struct sig_pri_span * pri)
Referenced by dahdi_cc_callback().
sig_pri_cli_show_spans()
void sig_pri_cli_show_spans (int fd, int span, struct sig_pri_span * pri)
Referenced by dahdi_cc_callback().
sig_pri_dial_complete()
void sig_pri_dial_complete (struct sig_pri_chan * pvt, struct ast_channel * ast)
Referenced by dahdi_handle_event().
sig_pri_digit_begin()
int sig_pri_digit_begin (struct sig_pri_chan * pvt, struct ast_channel * ast, char digit)
Referenced by dahdi_digit_begin().
sig_pri_extract_called_num_subaddr()
void sig_pri_extract_called_num_subaddr (struct sig_pri_chan * p, const char * rdest, char * called, size_t called_buff_size)
Referenced by dahdi_call(), and dahdi_request().
sig_pri_fixup()
void sig_pri_fixup (struct ast_channel * oldchan, struct ast_channel * newchan, struct sig_pri_chan * pchan)
Referenced by dahdi_fixup().
sig_pri_hangup()
int sig_pri_hangup (struct sig_pri_chan * p, struct ast_channel * ast)
Referenced by dahdi_hangup().
sig_pri_indicate()
int sig_pri_indicate (struct sig_pri_chan * p, struct ast_channel * chan, int condition, const void * data, size_t datalen)
Referenced by dahdi_indicate().
sig_pri_init_pri()
void sig_pri_init_pri (struct sig_pri_span * pri)
Referenced by dahdi_cc_callback(), dahdi_restart(), and load_module().
sig_pri_is_alarm_ignored()
int sig_pri_is_alarm_ignored (struct sig_pri_span * pri)
Referenced by handle_alarms(), handle_clear_alarms(), and my_on_hook().
sig_pri_is_chan_available()
int sig_pri_is_chan_available (struct sig_pri_chan * pvt)
Referenced by my_on_hook().
sig_pri_load()
int sig_pri_load (const char * cc_type_name)
Referenced by load_module().
sig_pri_request()
struct ast_channel* sig_pri_request (struct sig_pri_chan * p, enum sig_pri_law law, const struct ast_assigned_ids * assignedids, const struct ast_channel * requestor, int transfercapability)
Referenced by dahdi_request().
sig_pri_set_alarm()
void sig_pri_set_alarm (struct sig_pri_chan * p, int in_alarm)
Referenced by mkintf().
sig_pri_start_pri()
int sig_pri_start_pri (struct sig_pri_span * pri)
Referenced by setup_dahdi_int().
sig_pri_stop_pri()
void sig_pri_stop_pri (struct sig_pri_span * pri)
Referenced by __unload_module().
sig_pri_unload()
void sig_pri_unload (void)
Referenced by __unload_module().
Variable Documentation
sig_pri_callbacks
struct sig_pri_callback sig_pri_callbacks
Global sig_pri callbacks to the upper layer.