Asterisk - The Open Source Telephony Project: gsm_create.c File Reference
gsm_create.c File Reference
#include "config.h"
#include "proto.h"
#include <stdio.h>
#include "gsm.h"
#include "private.h"
Functions
char * malloc ()
char *memset P ((char *, int, int))
gsm gsm_create P0 ()
Function Documentation
malloc()
char* malloc ()
Referenced by __ast_bt_destroy(), __ast_bt_get_symbols(), __ast_repl_malloc(), __bt_open(), __bt_ret(), __hash_open(), __ibitmap(), __ovfl_get(), __rec_fmap(), __rec_fpipe(), __rec_put(), __rec_ret(), __rec_vpipe(), add_channel(), ael2_parse(), ael_yyalloc(), append_sub(), ast_std_malloc(), ast_yyalloc(), bt_page(), collect_data(), collect_key(), compose_func_args(), create_lpc10_decoder_state(), create_lpc10_encoder_state(), dbm_open(), expr2_token_subst(), fetch_bitmap(), find_chan(), g722_decode_init(), g722_encode_init(), gen_prios(), hash_realloc(), init_bc(), linkprio(), main(), make_number(), make_str(), mallocconcat(), malloccopy(), misdn_lib_send_event(), newbuf(), op_tildetilde(), P0(), parsefilearg(), readawaysamples(), setup_filestack(), tmp(), while(), workloop(), and yyparse().
P()
char* memset P ((char *, int, int))
P0()
gsm gsm_create P0 ()
Definition at line 32 of file gsm_create.c.
References malloc().
 {
    gsm  r;
    r = (gsm)malloc(sizeof(struct gsm_state));
    if (!r) return r;
    memset((char *)r, 0, sizeof(*r));
    r->nrp = 40;
    return r;
 }