Asterisk - The Open Source Telephony Project: format_compatibility.c File Reference
main/format_compatibility.c File Reference
Media Format Bitfield Compatibility API.
#include "asterisk.h"
#include "asterisk/logger.h"
#include "asterisk/astobj2.h"
#include "asterisk/codec.h"
#include "asterisk/format.h"
#include "asterisk/format_compatibility.h"
#include "asterisk/format_cache.h"
Functions
struct ast_format * ast_format_compatibility_bitfield2format (uint64_t bitfield)
Convert a bitfield to its respective format structure.
uint64_t ast_format_compatibility_codec2bitfield (const struct ast_codec *codec)
Convert a codec structure to its respective bitfield.
uint64_t ast_format_compatibility_format2bitfield (const struct ast_format *format)
Convert a format structure to its respective bitfield.
Detailed Description
Media Format Bitfield Compatibility API.
Author
Joshua Colp jcolp.nosp@m.@dig.nosp@m.ium.c.nosp@m.om
Definition in file main/format_compatibility.c.
Function Documentation
ast_format_compatibility_bitfield2format()
struct ast_format* ast_format_compatibility_bitfield2format (uint64_t bitfield)
Convert a bitfield to its respective format structure.
Parameters
bitfield The bitfield for the media format
Return values
non-NULL success
NULL failure (The format bitfield value is not supported)
Note
The reference count of the returned format is NOT incremented
G.723.1 compression
GSM compression
Raw mu-law data (G.711)
Raw A-law data (G.711)
ADPCM (G.726, 32kbps, AAL2 codeword packing)
ADPCM (IMA)
Raw 16-bit Signed Linear (8000 Hz) PCM
LPC10, 180 samples/frame
G.729A audio
SpeeX Free Compression
iLBC Free Compression
ADPCM (G.726, 32kbps, RFC3551 codeword packing)
G.722
G.722.1 (also known as Siren7, 32kbps assumed)
G.722.1 Annex C (also known as Siren14, 48kbps assumed)
Raw 16-bit Signed Linear (16000 Hz) PCM
G.719 (64 kbps assumed)
SpeeX Wideband (16kHz) Free Compression
Opus audio (8kHz, 16kHz, 24kHz, 48Khz)
Raw mu-law data (G.711)
H.261 Video
H.263 Video
H.263+ Video
H.264 Video
MPEG4 Video
VP8 Video
JPEG Images
PNG Images
T.140 RED Text format RFC 4103
T.140 Text format - ITU T.140, RFC 4103
Definition at line 173 of file main/format_compatibility.c.
References AST_FORMAT_ADPCM, ast_format_adpcm, AST_FORMAT_ALAW, ast_format_alaw, AST_FORMAT_G719, ast_format_g719, AST_FORMAT_G722, ast_format_g722, AST_FORMAT_G723, ast_format_g723, AST_FORMAT_G726, ast_format_g726, AST_FORMAT_G726_AAL2, ast_format_g726_aal2, AST_FORMAT_G729, ast_format_g729, AST_FORMAT_GSM, ast_format_gsm, AST_FORMAT_H261, ast_format_h261, AST_FORMAT_H263, ast_format_h263, AST_FORMAT_H263P, ast_format_h263p, AST_FORMAT_H264, ast_format_h264, AST_FORMAT_ILBC, ast_format_ilbc, AST_FORMAT_JPEG, ast_format_jpeg, AST_FORMAT_LPC10, ast_format_lpc10, AST_FORMAT_MP4, ast_format_mp4, AST_FORMAT_OPUS, ast_format_opus, AST_FORMAT_PNG, ast_format_png, AST_FORMAT_SIREN14, ast_format_siren14, AST_FORMAT_SIREN7, ast_format_siren7, ast_format_slin, AST_FORMAT_SLIN, ast_format_slin16, AST_FORMAT_SLIN16, AST_FORMAT_SPEEX, ast_format_speex, AST_FORMAT_SPEEX16, ast_format_speex16, AST_FORMAT_T140, ast_format_t140, AST_FORMAT_T140_RED, ast_format_t140_red, AST_FORMAT_TESTLAW, ast_format_testlaw, AST_FORMAT_ULAW, ast_format_ulaw, AST_FORMAT_VP8, ast_format_vp8, and NULL.
Referenced by __get_from_jb(), codec_choose_from_prefs(), decode_frame(), iax2_codec_pref_best_bitfield2cap(), iax2_codec_pref_from_bitfield(), iax2_codec_pref_index(), iax2_codec_pref_to_cap(), iax2_format_compatibility_bitfield2cap(), iax2_getformatname(), iax2_send(), socket_process_helper(), and socket_process_meta().
 {
    switch (bitfield) {
    /*! G.723.1 compression */
    case AST_FORMAT_G723:
       return ast_format_g723;
    /*! GSM compression */
    case AST_FORMAT_GSM:
       return ast_format_gsm;
    /*! Raw mu-law data (G.711) */
    case AST_FORMAT_ULAW:
       return ast_format_ulaw;
    /*! Raw A-law data (G.711) */
    case AST_FORMAT_ALAW:
       return ast_format_alaw;
    /*! ADPCM (G.726, 32kbps, AAL2 codeword packing) */
    case AST_FORMAT_G726_AAL2:
       return ast_format_g726_aal2;
    /*! ADPCM (IMA) */
    case AST_FORMAT_ADPCM:
       return ast_format_adpcm;
    /*! Raw 16-bit Signed Linear (8000 Hz) PCM */
    case AST_FORMAT_SLIN:
       return ast_format_slin;
    /*! LPC10, 180 samples/frame */
    case AST_FORMAT_LPC10:
       return ast_format_lpc10;
    /*! G.729A audio */
    case AST_FORMAT_G729:
       return ast_format_g729;
    /*! SpeeX Free Compression */
    case AST_FORMAT_SPEEX:
       return ast_format_speex;
    /*! iLBC Free Compression */
    case AST_FORMAT_ILBC:
       return ast_format_ilbc;
    /*! ADPCM (G.726, 32kbps, RFC3551 codeword packing) */
    case AST_FORMAT_G726:
       return ast_format_g726;
    /*! G.722 */
    case AST_FORMAT_G722:
       return ast_format_g722;
    /*! G.722.1 (also known as Siren7, 32kbps assumed) */
    case AST_FORMAT_SIREN7:
       return ast_format_siren7;
    /*! G.722.1 Annex C (also known as Siren14, 48kbps assumed) */
    case AST_FORMAT_SIREN14:
       return ast_format_siren14;
    /*! Raw 16-bit Signed Linear (16000 Hz) PCM */
    case AST_FORMAT_SLIN16:
       return ast_format_slin16;
    /*! G.719 (64 kbps assumed) */
    case AST_FORMAT_G719:
       return ast_format_g719;
    /*! SpeeX Wideband (16kHz) Free Compression */
    case AST_FORMAT_SPEEX16:
       return ast_format_speex16;
    /*! Opus audio (8kHz, 16kHz, 24kHz, 48Khz) */
    case AST_FORMAT_OPUS:
       return ast_format_opus;
    /*! Raw mu-law data (G.711) */
    case AST_FORMAT_TESTLAW:
       return ast_format_testlaw;
    /*! H.261 Video */
    case AST_FORMAT_H261:
       return ast_format_h261;
    /*! H.263 Video */
    case AST_FORMAT_H263:
       return ast_format_h263;
    /*! H.263+ Video */
    case AST_FORMAT_H263P:
       return ast_format_h263p;
    /*! H.264 Video */
    case AST_FORMAT_H264:
       return ast_format_h264;
    /*! MPEG4 Video */
    case AST_FORMAT_MP4:
       return ast_format_mp4;
    /*! VP8 Video */
    case AST_FORMAT_VP8:
       return ast_format_vp8;
    /*! JPEG Images */
    case AST_FORMAT_JPEG:
       return ast_format_jpeg;
    /*! PNG Images */
    case AST_FORMAT_PNG:
       return ast_format_png;
    /*! T.140 RED Text format RFC 4103 */
    case AST_FORMAT_T140_RED:
       return ast_format_t140_red;
    /*! T.140 Text format - ITU T.140, RFC 4103 */
    case AST_FORMAT_T140:
       return ast_format_t140;
    }
    return NULL;
 }
ast_format_compatibility_codec2bitfield()
uint64_t ast_format_compatibility_codec2bitfield (const struct ast_codec * codec)
Convert a codec structure to its respective bitfield.
Parameters
codec The media codec
Return values
non-zero success
zero format not supported
Definition at line 106 of file main/format_compatibility.c.
References AST_FORMAT_ADPCM, ast_format_adpcm, AST_FORMAT_ALAW, ast_format_alaw, AST_FORMAT_G719, ast_format_g719, AST_FORMAT_G722, ast_format_g722, AST_FORMAT_G723, ast_format_g723, AST_FORMAT_G726, ast_format_g726, AST_FORMAT_G726_AAL2, ast_format_g726_aal2, AST_FORMAT_G729, ast_format_g729, ast_format_get_codec_id(), AST_FORMAT_GSM, ast_format_gsm, AST_FORMAT_H261, ast_format_h261, AST_FORMAT_H263, ast_format_h263, AST_FORMAT_H263P, ast_format_h263p, AST_FORMAT_H264, ast_format_h264, AST_FORMAT_ILBC, ast_format_ilbc, AST_FORMAT_JPEG, ast_format_jpeg, AST_FORMAT_LPC10, ast_format_lpc10, AST_FORMAT_MP4, ast_format_mp4, AST_FORMAT_OPUS, ast_format_opus, AST_FORMAT_PNG, ast_format_png, AST_FORMAT_SIREN14, ast_format_siren14, AST_FORMAT_SIREN7, ast_format_siren7, ast_format_slin, AST_FORMAT_SLIN, ast_format_slin16, AST_FORMAT_SLIN16, AST_FORMAT_SPEEX, ast_format_speex, AST_FORMAT_SPEEX16, ast_format_speex16, AST_FORMAT_T140, ast_format_t140, AST_FORMAT_T140_RED, ast_format_t140_red, AST_FORMAT_TESTLAW, ast_format_testlaw, AST_FORMAT_ULAW, ast_format_ulaw, AST_FORMAT_VP8, ast_format_vp8, and ast_codec::id.
 {
    if (codec->id == ast_format_get_codec_id(ast_format_g723)) {
       return AST_FORMAT_G723;
    } else if (codec->id == ast_format_get_codec_id(ast_format_gsm)) {
       return AST_FORMAT_GSM;
    } else if (codec->id == ast_format_get_codec_id(ast_format_ulaw)) {
       return AST_FORMAT_ULAW;
    } else if (codec->id == ast_format_get_codec_id(ast_format_alaw)) {
       return AST_FORMAT_ALAW;
    } else if (codec->id == ast_format_get_codec_id(ast_format_g726_aal2)) {
       return AST_FORMAT_G726_AAL2;
    } else if (codec->id == ast_format_get_codec_id(ast_format_adpcm)) {
       return AST_FORMAT_ADPCM;
    } else if (codec->id == ast_format_get_codec_id(ast_format_slin)) {
       return AST_FORMAT_SLIN;
    } else if (codec->id == ast_format_get_codec_id(ast_format_lpc10)) {
       return AST_FORMAT_LPC10;
    } else if (codec->id == ast_format_get_codec_id(ast_format_g729)) {
       return AST_FORMAT_G729;
    } else if (codec->id == ast_format_get_codec_id(ast_format_speex)) {
       return AST_FORMAT_SPEEX;
    } else if (codec->id == ast_format_get_codec_id(ast_format_ilbc)) {
       return AST_FORMAT_ILBC;
    } else if (codec->id == ast_format_get_codec_id(ast_format_g726)) {
       return AST_FORMAT_G726;
    } else if (codec->id == ast_format_get_codec_id(ast_format_g722)) {
       return AST_FORMAT_G722;
    } else if (codec->id == ast_format_get_codec_id(ast_format_siren7)) {
       return AST_FORMAT_SIREN7;
    } else if (codec->id == ast_format_get_codec_id(ast_format_siren14)) {
       return AST_FORMAT_SIREN14;
    } else if (codec->id == ast_format_get_codec_id(ast_format_slin16)) {
       return AST_FORMAT_SLIN16;
    } else if (codec->id == ast_format_get_codec_id(ast_format_g719)) {
       return AST_FORMAT_G719;
    } else if (codec->id == ast_format_get_codec_id(ast_format_speex16)) {
       return AST_FORMAT_SPEEX16;
    } else if (codec->id == ast_format_get_codec_id(ast_format_opus)) {
       return AST_FORMAT_OPUS;
    } else if (codec->id == ast_format_get_codec_id(ast_format_testlaw)) {
       return AST_FORMAT_TESTLAW;
    } else if (codec->id == ast_format_get_codec_id(ast_format_h261)) {
       return AST_FORMAT_H261;
    } else if (codec->id == ast_format_get_codec_id(ast_format_h263)) {
       return AST_FORMAT_H263;
    } else if (codec->id == ast_format_get_codec_id(ast_format_h263p)) {
       return AST_FORMAT_H263P;
    } else if (codec->id == ast_format_get_codec_id(ast_format_h264)) {
       return AST_FORMAT_H264;
    } else if (codec->id == ast_format_get_codec_id(ast_format_mp4)) {
       return AST_FORMAT_MP4;
    } else if (codec->id == ast_format_get_codec_id(ast_format_vp8)) {
       return AST_FORMAT_VP8;
    } else if (codec->id == ast_format_get_codec_id(ast_format_jpeg)) {
       return AST_FORMAT_JPEG;
    } else if (codec->id == ast_format_get_codec_id(ast_format_png)) {
       return AST_FORMAT_PNG;
    } else if (codec->id == ast_format_get_codec_id(ast_format_t140_red)) {
       return AST_FORMAT_T140_RED;
    } else if (codec->id == ast_format_get_codec_id(ast_format_t140)) {
       return AST_FORMAT_T140;
    }
    return 0;
 }
ast_format_compatibility_format2bitfield()
uint64_t ast_format_compatibility_format2bitfield (const struct ast_format * format)
Convert a format structure to its respective bitfield.
Parameters
format The media format
Return values
non-zero success
zero format not supported
Definition at line 39 of file main/format_compatibility.c.
References AST_FORMAT_ADPCM, ast_format_adpcm, AST_FORMAT_ALAW, ast_format_alaw, ast_format_cmp(), AST_FORMAT_CMP_EQUAL, AST_FORMAT_G719, ast_format_g719, AST_FORMAT_G722, ast_format_g722, AST_FORMAT_G723, ast_format_g723, AST_FORMAT_G726, ast_format_g726, AST_FORMAT_G726_AAL2, ast_format_g726_aal2, AST_FORMAT_G729, ast_format_g729, AST_FORMAT_GSM, ast_format_gsm, AST_FORMAT_H261, ast_format_h261, AST_FORMAT_H263, ast_format_h263, AST_FORMAT_H263P, ast_format_h263p, AST_FORMAT_H264, ast_format_h264, AST_FORMAT_ILBC, ast_format_ilbc, AST_FORMAT_JPEG, ast_format_jpeg, AST_FORMAT_LPC10, ast_format_lpc10, AST_FORMAT_MP4, ast_format_mp4, AST_FORMAT_OPUS, ast_format_opus, AST_FORMAT_PNG, ast_format_png, AST_FORMAT_SIREN14, ast_format_siren14, AST_FORMAT_SIREN7, ast_format_siren7, ast_format_slin, AST_FORMAT_SLIN, ast_format_slin16, AST_FORMAT_SLIN16, AST_FORMAT_SPEEX, ast_format_speex, AST_FORMAT_SPEEX16, ast_format_speex16, AST_FORMAT_T140, ast_format_t140, AST_FORMAT_T140_RED, ast_format_t140_red, AST_FORMAT_TESTLAW, ast_format_testlaw, AST_FORMAT_ULAW, ast_format_ulaw, AST_FORMAT_VP8, and ast_format_vp8.
Referenced by conf_run(), iax2_codec_choose(), iax2_codec_pref_append(), iax2_codec_pref_prepend(), iax2_format_compatibility_cap2bitfield(), iax2_send(), iax_template_parse(), phone_write(), and socket_process_helper().
 {
    if (ast_format_cmp(format, ast_format_g723) == AST_FORMAT_CMP_EQUAL) {
       return AST_FORMAT_G723;
    } else if (ast_format_cmp(format, ast_format_gsm) == AST_FORMAT_CMP_EQUAL) {
       return AST_FORMAT_GSM;
    } else if (ast_format_cmp(format, ast_format_ulaw) == AST_FORMAT_CMP_EQUAL) {
       return AST_FORMAT_ULAW;
    } else if (ast_format_cmp(format, ast_format_alaw) == AST_FORMAT_CMP_EQUAL) {
       return AST_FORMAT_ALAW;
    } else if (ast_format_cmp(format, ast_format_g726_aal2) == AST_FORMAT_CMP_EQUAL) {
       return AST_FORMAT_G726_AAL2;
    } else if (ast_format_cmp(format, ast_format_adpcm) == AST_FORMAT_CMP_EQUAL) {
       return AST_FORMAT_ADPCM;
    } else if (ast_format_cmp(format, ast_format_slin) == AST_FORMAT_CMP_EQUAL) {
       return AST_FORMAT_SLIN;
    } else if (ast_format_cmp(format, ast_format_lpc10) == AST_FORMAT_CMP_EQUAL) {
       return AST_FORMAT_LPC10;
    } else if (ast_format_cmp(format, ast_format_g729) == AST_FORMAT_CMP_EQUAL) {
       return AST_FORMAT_G729;
    } else if (ast_format_cmp(format, ast_format_speex) == AST_FORMAT_CMP_EQUAL) {
       return AST_FORMAT_SPEEX;
    } else if (ast_format_cmp(format, ast_format_ilbc) == AST_FORMAT_CMP_EQUAL) {
       return AST_FORMAT_ILBC;
    } else if (ast_format_cmp(format, ast_format_g726) == AST_FORMAT_CMP_EQUAL) {
       return AST_FORMAT_G726;
    } else if (ast_format_cmp(format, ast_format_g722) == AST_FORMAT_CMP_EQUAL) {
       return AST_FORMAT_G722;
    } else if (ast_format_cmp(format, ast_format_siren7) == AST_FORMAT_CMP_EQUAL) {
       return AST_FORMAT_SIREN7;
    } else if (ast_format_cmp(format, ast_format_siren14) == AST_FORMAT_CMP_EQUAL) {
       return AST_FORMAT_SIREN14;
    } else if (ast_format_cmp(format, ast_format_slin16) == AST_FORMAT_CMP_EQUAL) {
       return AST_FORMAT_SLIN16;
    } else if (ast_format_cmp(format, ast_format_g719) == AST_FORMAT_CMP_EQUAL) {
       return AST_FORMAT_G719;
    } else if (ast_format_cmp(format, ast_format_speex16) == AST_FORMAT_CMP_EQUAL) {
       return AST_FORMAT_SPEEX16;
    } else if (ast_format_cmp(format, ast_format_opus) == AST_FORMAT_CMP_EQUAL) {
       return AST_FORMAT_OPUS;
    } else if (ast_format_cmp(format, ast_format_testlaw) == AST_FORMAT_CMP_EQUAL) {
       return AST_FORMAT_TESTLAW;
    } else if (ast_format_cmp(format, ast_format_h261) == AST_FORMAT_CMP_EQUAL) {
       return AST_FORMAT_H261;
    } else if (ast_format_cmp(format, ast_format_h263) == AST_FORMAT_CMP_EQUAL) {
       return AST_FORMAT_H263;
    } else if (ast_format_cmp(format, ast_format_h263p) == AST_FORMAT_CMP_EQUAL) {
       return AST_FORMAT_H263P;
    } else if (ast_format_cmp(format, ast_format_h264) == AST_FORMAT_CMP_EQUAL) {
       return AST_FORMAT_H264;
    } else if (ast_format_cmp(format, ast_format_mp4) == AST_FORMAT_CMP_EQUAL) {
       return AST_FORMAT_MP4;
    } else if (ast_format_cmp(format, ast_format_vp8) == AST_FORMAT_CMP_EQUAL) {
       return AST_FORMAT_VP8;
    } else if (ast_format_cmp(format, ast_format_jpeg) == AST_FORMAT_CMP_EQUAL) {
       return AST_FORMAT_JPEG;
    } else if (ast_format_cmp(format, ast_format_png) == AST_FORMAT_CMP_EQUAL) {
       return AST_FORMAT_PNG;
    } else if (ast_format_cmp(format, ast_format_t140_red) == AST_FORMAT_CMP_EQUAL) {
       return AST_FORMAT_T140_RED;
    } else if (ast_format_cmp(format, ast_format_t140) == AST_FORMAT_CMP_EQUAL) {
       return AST_FORMAT_T140;
    }
    return 0;
 }