Asterisk - The Open Source Telephony Project: conf_state_empty.c File Reference
conf_state_empty.c File Reference
Dial plan applications
Confbridge state handling for the EMPTY state.
#include "asterisk.h"
#include "asterisk/devicestate.h"
#include "include/confbridge.h"
#include "include/conf_state.h"
Functions
static void join_marked (struct confbridge_user *user)
static void join_unmarked (struct confbridge_user *user)
static void join_waitmarked (struct confbridge_user *user)
static void transition_to_empty (struct confbridge_user *user)
Variables
struct confbridge_state * CONF_STATE_EMPTY = &STATE_EMPTY
Conference state with no active or waiting users.
struct confbridge_state STATE_EMPTY
Detailed Description
Confbridge state handling for the EMPTY state.
Author
Terry Wilson <twilson@digium.com>
Definition in file conf_state_empty.c.
Function Documentation
join_marked()
static void join_marked (struct confbridge_user * user) static
Definition at line 72 of file conf_state_empty.c.
References conf_add_post_join_action(), conf_add_user_marked(), conf_change_state(), conf_handle_first_join(), conf_handle_only_person(), CONF_STATE_SINGLE_MARKED, and confbridge_user::conference.
 {
    conf_add_user_marked(user->conference, user);
    conf_handle_first_join(user->conference);
    conf_add_post_join_action(user, conf_handle_only_person);
    conf_change_state(user, CONF_STATE_SINGLE_MARKED);
 }
join_unmarked()
static void join_unmarked (struct confbridge_user * user) static
Definition at line 55 of file conf_state_empty.c.
References conf_add_post_join_action(), conf_add_user_active(), conf_change_state(), conf_handle_first_join(), conf_handle_only_person(), CONF_STATE_SINGLE, and confbridge_user::conference.
 {
    conf_add_user_active(user->conference, user);
    conf_handle_first_join(user->conference);
    conf_add_post_join_action(user, conf_handle_only_person);
    conf_change_state(user, CONF_STATE_SINGLE);
 }
join_waitmarked()
static void join_waitmarked (struct confbridge_user * user) static
Definition at line 64 of file conf_state_empty.c.
References conf_change_state(), conf_default_join_waitmarked(), conf_handle_first_join(), CONF_STATE_INACTIVE, and confbridge_user::conference.
 {
    conf_default_join_waitmarked(user);
    conf_handle_first_join(user->conference);
    conf_change_state(user, CONF_STATE_INACTIVE);
 }
transition_to_empty()
static void transition_to_empty (struct confbridge_user * user) static
Definition at line 81 of file conf_state_empty.c.
References AST_DEVICE_NOT_INUSE, AST_DEVSTATE_CACHABLE, ast_devstate_changed(), conf_ended(), confbridge_user::conference, and confbridge_conference::name.
 {
    /* Set device state to "not in use" */
    ast_devstate_changed(AST_DEVICE_NOT_INUSE, AST_DEVSTATE_CACHABLE, "confbridge:%s", user->conference->name);
    conf_ended(user->conference);
 }
Variable Documentation
CONF_STATE_EMPTY
struct confbridge_state* CONF_STATE_EMPTY = &STATE_EMPTY
Conference state with no active or waiting users.
Definition at line 53 of file conf_state_empty.c.
Referenced by join_conference_bridge(), leave_marked(), leave_unmarked(), and leave_waitmarked().
STATE_EMPTY
struct confbridge_state STATE_EMPTY
Definition at line 45 of file conf_state_empty.c.