Asterisk - The Open Source Telephony Project: res_mwi_devstate.c File Reference
res_mwi_devstate.c File Reference
#include "asterisk.h"
#include "asterisk/mwi.h"
#include "asterisk/devicestate.h"
#include "asterisk/module.h"
#include "asterisk/stasis_message_router.h"
#include "asterisk/stasis.h"
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int load_module (void)
static int mwi_cached_cb (void *obj, void *arg, int flags)
static void mwi_update_cb (void *data, struct stasis_subscription *sub, struct stasis_message *msg)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "MWI Device State Subscriptions" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEVSTATE_PROVIDER, }
static const struct ast_module_info * ast_module_info = &__mod_info
static struct stasis_subscription * mwi_sub
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 105 of file res_mwi_devstate.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 105 of file res_mwi_devstate.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 105 of file res_mwi_devstate.c.
load_module()
static int load_module (void) static
Definition at line 71 of file res_mwi_devstate.c.
References ao2_callback, ao2_ref, AST_MODFLAG_LOAD_ORDER, AST_MODPRI_DEVSTATE_PROVIDER, AST_MODULE_INFO(), AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, AST_MODULE_SUPPORT_CORE, ast_mwi_state_cache(), ast_mwi_state_type(), ast_mwi_topic_all(), ASTERISK_GPL_KEY, mwi_cached_cb(), mwi_update_cb(), NULL, OBJ_NODATA, stasis_cache_dump(), stasis_subscribe, stasis_subscription_accept_message_type(), STASIS_SUBSCRIPTION_FILTER_SELECTIVE, stasis_subscription_set_filter(), and unload_module().
 {
    struct ao2_container *cached;
    if (!(mwi_sub = stasis_subscribe(ast_mwi_topic_all(), mwi_update_cb, NULL))) {
       return AST_MODULE_LOAD_DECLINE;
    }
    if (stasis_subscription_accept_message_type(mwi_sub, ast_mwi_state_type())) {
       unload_module();
       return AST_MODULE_LOAD_DECLINE;
    }
    if (stasis_subscription_set_filter(mwi_sub, STASIS_SUBSCRIPTION_FILTER_SELECTIVE)) {
       unload_module();
       return AST_MODULE_LOAD_DECLINE;
    }
    cached = stasis_cache_dump(ast_mwi_state_cache(), NULL);
    if (!cached) {
       unload_module();
       return AST_MODULE_LOAD_DECLINE;
    }
    ao2_callback(cached, OBJ_NODATA, mwi_cached_cb, NULL);
    ao2_ref(cached, -1);
    return AST_MODULE_LOAD_SUCCESS;
 }
mwi_cached_cb()
static int mwi_cached_cb (void * obj, void * arg, int flags) static
Definition at line 56 of file res_mwi_devstate.c.
References mwi_update_cb(), and NULL.
Referenced by load_module().
 {
    struct stasis_message *msg = obj;
    mwi_update_cb(NULL, mwi_sub, msg);
    return 0;
 }
mwi_update_cb()
static void mwi_update_cb (void * data, struct stasis_subscription * sub, struct stasis_message * msg) static
Definition at line 33 of file res_mwi_devstate.c.
References ast_debug, AST_DEVICE_INUSE, AST_DEVICE_NOT_INUSE, AST_DEVSTATE_CACHABLE, ast_devstate_changed(), ast_mwi_state_type(), ast_mwi_state::new_msgs, stasis_message_data(), stasis_message_type(), and ast_mwi_state::uniqueid.
Referenced by load_module(), and mwi_cached_cb().
 {
    struct ast_mwi_state *mwi_state;
    if (ast_mwi_state_type() != stasis_message_type(msg)) {
       return;
    }
    mwi_state = stasis_message_data(msg);
    if (!mwi_state) {
       return;
    }
    if (mwi_state->new_msgs > 0) {
       ast_debug(1, "Sending inuse devstate change for MWI:%s\n", mwi_state->uniqueid);
       ast_devstate_changed(AST_DEVICE_INUSE, AST_DEVSTATE_CACHABLE, "MWI:%s", mwi_state->uniqueid);
    } else {
       ast_debug(1, "Sending not inuse devstate change for MWI:%s\n", mwi_state->uniqueid);
       ast_devstate_changed(AST_DEVICE_NOT_INUSE, AST_DEVSTATE_CACHABLE, "MWI:%s", mwi_state->uniqueid);
    }
 }
unload_module()
static int unload_module (void) static
Definition at line 64 of file res_mwi_devstate.c.
References stasis_unsubscribe().
Referenced by load_module().
 {
    mwi_sub = stasis_unsubscribe(mwi_sub);
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "MWI Device State Subscriptions" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEVSTATE_PROVIDER, } static
Definition at line 105 of file res_mwi_devstate.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 105 of file res_mwi_devstate.c.
mwi_sub
struct stasis_subscription* mwi_sub static
Definition at line 31 of file res_mwi_devstate.c.
Referenced by allow_and_or_replace_unsolicited(), is_unsolicited_allowed(), mwi_contact_deleted(), mwi_get_notify_data(), mwi_stasis_cb(), mwi_subscription_shutdown(), mwi_to_ami(), send_contact_notify(), send_notify(), serialized_cleanup(), serialized_notify(), and unsubscribe().