Asterisk - The Open Source Telephony Project: store.c File Reference
store.c File Reference
#include "asterisk.h"
#include <sys/stat.h>
#include "asterisk/cli.h"
#include "asterisk/sorcery.h"
#include "stir_shaken.h"
#include "store.h"
#include "asterisk/res_stir_shaken.h"
Data Structures
struct stir_shaken_store
Macros
#define CONFIG_TYPE "store"
#define VARIABLE_SUBSTITUTE "${CERTIFICATE}"
Functions
static int on_load_path (const struct aco_option *opt, struct ast_variable *var, void *obj)
static int on_load_public_cert_url (const struct aco_option *opt, struct ast_variable *var, void *obj)
static int path_to_str (const void *obj, const intptr_t *args, char **buf)
static int public_cert_url_to_str (const void *obj, const intptr_t *args, char **buf)
static void * stir_shaken_store_alloc (const char *name)
static int stir_shaken_store_apply (const struct ast_sorcery *sorcery, void *obj)
static void stir_shaken_store_destructor (void *obj)
static struct stir_shaken_store * stir_shaken_store_get (const char *id)
static struct ao2_container * stir_shaken_store_get_all (void)
int stir_shaken_store_load (void)
Load time initialization for the stir/shaken 'store' configuration.
static char * stir_shaken_store_show (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
int stir_shaken_store_unload (void)
Unload time cleanup for the stir/shaken 'store' configuration.
Variables
static struct ast_cli_entry stir_shaken_store_cli []
Macro Definition Documentation
CONFIG_TYPE
#define CONFIG_TYPE "store"
Definition at line 30 of file store.c.
Referenced by stir_shaken_store_get(), stir_shaken_store_get_all(), and stir_shaken_store_load().
VARIABLE_SUBSTITUTE
#define VARIABLE_SUBSTITUTE "${CERTIFICATE}"
Definition at line 32 of file store.c.
Referenced by on_load_public_cert_url().
Function Documentation
on_load_path()
static int on_load_path (const struct aco_option * opt, struct ast_variable * var, void * obj) static
Definition at line 118 of file store.c.
References ast_log, ast_string_field_set, LOG_ERROR, stir_shaken_store::path, and ast_variable::value.
Referenced by stir_shaken_store_load().
 {
    struct stir_shaken_store *cfg = obj;
    struct stat statbuf;
    if (stat(var->value, &statbuf)) {
       ast_log(LOG_ERROR, "stir/shaken - path '%s' not found\n", var->value);
       return -1;
    }
    if (!S_ISDIR(statbuf.st_mode)) {
       ast_log(LOG_ERROR, "stir/shaken - path '%s' is not a directory\n", var->value);
       return -1;
    }
    return ast_string_field_set(cfg, path, var->value);
 }
on_load_public_cert_url()
static int on_load_public_cert_url (const struct aco_option * opt, struct ast_variable * var, void * obj) static
Definition at line 145 of file store.c.
References ast_begins_with(), ast_log, ast_string_field_set, LOG_ERROR, stir_shaken_store::public_cert_url, ast_variable::value, and VARIABLE_SUBSTITUTE.
Referenced by stir_shaken_store_load().
 {
    struct stir_shaken_store *cfg = obj;
    if (!ast_begins_with(var->value, "http")) {
       ast_log(LOG_ERROR, "stir/shaken - public_cert_url scheme must be 'http[s]'\n");
       return -1;
    }
    if (!strstr(var->value, VARIABLE_SUBSTITUTE)) {
       ast_log(LOG_ERROR, "stir/shaken - public_cert_url must contain variable '%s' "
             "used for substitution\n", VARIABLE_SUBSTITUTE);
       return -1;
    }
    return ast_string_field_set(cfg, public_cert_url, var->value);
 }
path_to_str()
static int path_to_str (const void * obj, const intptr_t * args, char ** buf) static
Definition at line 136 of file store.c.
References ast_strdup, and stir_shaken_store::path.
Referenced by stir_shaken_store_load().
 {
    const struct stir_shaken_store *cfg = obj;
    *buf = ast_strdup(cfg->path);
    return 0;
 }
public_cert_url_to_str()
static int public_cert_url_to_str (const void * obj, const intptr_t * args, char ** buf) static
Definition at line 163 of file store.c.
References ast_strdup, and stir_shaken_store::public_cert_url.
Referenced by stir_shaken_store_load().
 {
    const struct stir_shaken_store *cfg = obj;
    *buf = ast_strdup(cfg->public_cert_url);
    return 0;
 }
stir_shaken_store_alloc()
static void* stir_shaken_store_alloc (const char * name) static
Definition at line 62 of file store.c.
References ao2_ref, ast_sorcery_generic_alloc(), ast_string_field_init, NULL, and stir_shaken_store_destructor().
Referenced by stir_shaken_store_load().
 {
    struct stir_shaken_store *cfg;
    cfg = ast_sorcery_generic_alloc(sizeof(*cfg), stir_shaken_store_destructor);
    if (!cfg) {
       return NULL;
    }
    if (ast_string_field_init(cfg, 512)) {
       ao2_ref(cfg, -1);
       return NULL;
    }
    return cfg;
 }
stir_shaken_store_apply()
static int stir_shaken_store_apply (const struct ast_sorcery * sorcery, void * obj) static
Definition at line 79 of file store.c.
Referenced by stir_shaken_store_load().
 {
    return 0;
 }
stir_shaken_store_destructor()
static void stir_shaken_store_destructor (void * obj) static
Definition at line 55 of file store.c.
References ast_string_field_free_memory.
Referenced by stir_shaken_store_alloc().
 {
    struct stir_shaken_store *cfg = obj;
    ast_string_field_free_memory(cfg);
 }
stir_shaken_store_get()
static struct stir_shaken_store* stir_shaken_store_get (const char * id) static
Definition at line 44 of file store.c.
References ast_sorcery_retrieve_by_id(), ast_stir_shaken_sorcery(), and CONFIG_TYPE.
Referenced by stir_shaken_store_show().
 {
    return ast_sorcery_retrieve_by_id(ast_stir_shaken_sorcery(), CONFIG_TYPE, id);
 }
stir_shaken_store_get_all()
static struct ao2_container* stir_shaken_store_get_all (void) static
Definition at line 49 of file store.c.
References AST_RETRIEVE_FLAG_ALL, AST_RETRIEVE_FLAG_MULTIPLE, ast_sorcery_retrieve_by_fields(), ast_stir_shaken_sorcery(), CONFIG_TYPE, and NULL.
Referenced by stir_shaken_store_show().
 {
    return ast_sorcery_retrieve_by_fields(ast_stir_shaken_sorcery(), CONFIG_TYPE,
       AST_RETRIEVE_FLAG_MULTIPLE | AST_RETRIEVE_FLAG_ALL, NULL);
 }
stir_shaken_store_load()
int stir_shaken_store_load (void)
Load time initialization for the stir/shaken 'store' configuration.
Return values
0 on success, -1 on error
Definition at line 180 of file store.c.
References ARRAY_LEN, ast_cli_register_multiple, ast_log, ast_sorcery_apply_default, ast_sorcery_object_field_register, ast_sorcery_object_field_register_custom, ast_sorcery_object_register, ast_stir_shaken_sorcery(), CONFIG_TYPE, LOG_ERROR, NULL, on_load_path(), on_load_public_cert_url(), OPT_NOOP_T, path_to_str(), public_cert_url_to_str(), sorcery, stir_shaken_store_alloc(), and stir_shaken_store_apply().
Referenced by load_module().
 {
    struct ast_sorcery *sorcery = ast_stir_shaken_sorcery();
    ast_sorcery_apply_default(sorcery, CONFIG_TYPE, "config", "stir_shaken.conf,criteria=type=store");
    if (ast_sorcery_object_register(sorcery, CONFIG_TYPE, stir_shaken_store_alloc,
          NULL, stir_shaken_store_apply)) {
       ast_log(LOG_ERROR, "stir/shaken - failed to register '%s' sorcery object\n", CONFIG_TYPE);
       return -1;
    }
    ast_sorcery_object_field_register(sorcery, CONFIG_TYPE, "type", "", OPT_NOOP_T, 0, 0);
    ast_sorcery_object_field_register_custom(sorcery, CONFIG_TYPE, "path", "",
       on_load_path, path_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register_custom(sorcery, CONFIG_TYPE, "public_cert_url", "",
       on_load_public_cert_url, public_cert_url_to_str, NULL, 0, 0);
    ast_cli_register_multiple(stir_shaken_store_cli,
       ARRAY_LEN(stir_shaken_store_cli));
    return 0;
 }
stir_shaken_store_show()
static char* stir_shaken_store_show (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) static
Definition at line 84 of file store.c.
References ao2_cleanup, ast_cli_args::argc, ast_cli_args::argv, CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::command, NULL, ast_cli_args::pos, stir_shaken_cli_show(), stir_shaken_store_get(), stir_shaken_store_get_all(), stir_shaken_tab_complete_name(), ast_cli_entry::usage, and ast_cli_args::word.
 {
    struct stir_shaken_store *cfg;
    switch(cmd) {
    case CLI_INIT:
       e->command = "stir_shaken show store";
       e->usage =
          "Usage: stir_shaken show store <id>\n"
          "       Show the store stir/shaken settings for a given id\n";
       return NULL;
    case CLI_GENERATE:
       if (a->pos == 3) {
          return stir_shaken_tab_complete_name(a->word, stir_shaken_store_get_all());
       } else {
          return NULL;
       };
    }
    if (a->argc != 4) {
       return CLI_SHOWUSAGE;
    }
    cfg = stir_shaken_store_get(a->argv[3]);
    stir_shaken_cli_show(cfg, a, 0);
    ao2_cleanup(cfg);
    return CLI_SUCCESS;
 }
stir_shaken_store_unload()
int stir_shaken_store_unload (void)
Unload time cleanup for the stir/shaken 'store' configuration.
Return values
0 on success, -1 on error
Definition at line 172 of file store.c.
References ARRAY_LEN, and ast_cli_unregister_multiple().
Referenced by unload_module().
 {
    ast_cli_unregister_multiple(stir_shaken_store_cli,
       ARRAY_LEN(stir_shaken_store_cli));
    return 0;
 }
Variable Documentation
stir_shaken_store_cli
struct ast_cli_entry stir_shaken_store_cli[] static
Initial value:
= {
   { .handler =  stir_shaken_store_show , .summary =  "Show stir/shaken store configuration by id" ,},
}
Definition at line 114 of file store.c.