Asterisk - The Open Source Telephony Project: ast_fax_tech Struct Reference
ast_fax_tech Struct Reference
used to register a FAX technology module with res_fax
#include <res_fax.h>
Data Fields
int(*const cancel_session)(struct ast_fax_session *)
enum ast_fax_capabilities caps
char *(*const cli_show_capabilities)(int)
char *(*const cli_show_session)(struct ast_fax_session *, int)
char *(*const cli_show_settings)(int)
char *(*const cli_show_stats)(int)
const char *const description
void(*const destroy_session)(struct ast_fax_session *)
int(*const generate_silence)(struct ast_fax_session *)
void(*const manager_fax_session)(struct mansession *, const char *, struct ast_fax_session *)
struct ast_module * module
void *(*const new_session)(struct ast_fax_session *, struct ast_fax_tech_token *)
struct ast_frame *(*const read)(struct ast_fax_session *)
void(*const release_token)(struct ast_fax_tech_token *)
struct ast_fax_tech_token *(*const reserve_session)(struct ast_fax_session *)
int(*const start_session)(struct ast_fax_session *)
int(*const switch_to_t38)(struct ast_fax_session *)
const char *const type
const char *const version
int(*const write)(struct ast_fax_session *, const struct ast_frame *)
Detailed Description
used to register a FAX technology module with res_fax
Definition at line 235 of file res_fax.h.
Field Documentation
cancel_session
int(* const cancel_session) (struct ast_fax_session *)
cancels a fax session
Definition at line 261 of file res_fax.h.
Referenced by fax_gateway_framehook_destroy(), and generic_fax_exec().
caps
enum ast_fax_capabilities caps
the ast_fax_capabilities supported by the fax technology
Definition at line 243 of file res_fax.h.
Referenced by fax_session_new(), and fax_session_reserve().
cli_show_capabilities
char*(* const cli_show_capabilities) (int)
displays capabilities of the fax technology
Definition at line 267 of file res_fax.h.
Referenced by cli_fax_show_capabilities().
cli_show_session
char*(* const cli_show_session) (struct ast_fax_session *, int)
displays details about the fax session
Definition at line 269 of file res_fax.h.
Referenced by cli_fax_show_session().
cli_show_settings
char*(* const cli_show_settings) (int)
displays settings from the fax technology module
Definition at line 276 of file res_fax.h.
Referenced by cli_fax_show_settings().
cli_show_stats
char*(* const cli_show_stats) (int)
displays statistics from the fax technology module
Definition at line 274 of file res_fax.h.
Referenced by cli_fax_show_stats().
description
const char* const description
a short description of the fax technology
Definition at line 239 of file res_fax.h.
Referenced by ast_fax_tech_register(), cli_fax_show_capabilities(), cli_fax_show_settings(), cli_fax_show_version(), fax_session_new(), fax_session_reserve(), Parameter::load(), Api::load(), Property::load(), Model::load(), and ResourceApi::load().
destroy_session
void(* const destroy_session) (struct ast_fax_session *)
destroys an existing fax session
Definition at line 253 of file res_fax.h.
Referenced by destroy_session().
generate_silence
int(* const generate_silence) (struct ast_fax_session *)
initiates the generation of silence to the fax session
Definition at line 263 of file res_fax.h.
Referenced by generic_fax_exec().
manager_fax_session
void(* const manager_fax_session) (struct mansession *, const char *, struct ast_fax_session *)
Generates manager event detailing the fax session
Definition at line 271 of file res_fax.h.
Referenced by manager_fax_session().
module
struct ast_module* module
module information for the fax technology
Definition at line 245 of file res_fax.h.
Referenced by destroy_session(), fax_session_new(), fax_session_reserve(), and load_module().
new_session
void*(* const new_session) (struct ast_fax_session *, struct ast_fax_tech_token *)
creates a new fax session, optionally using a previously-reserved token
Definition at line 251 of file res_fax.h.
Referenced by fax_session_new().
read
struct ast_frame*(* const read) (struct ast_fax_session *)
sends an Asterisk frame to res_fax
Definition at line 255 of file res_fax.h.
Referenced by generic_fax_exec().
release_token
void(* const release_token) (struct ast_fax_tech_token *)
releases an unused session token
Definition at line 249 of file res_fax.h.
Referenced by fax_session_release().
reserve_session
struct ast_fax_tech_token*(* const reserve_session) (struct ast_fax_session *)
reserves a session for future use; returns a token
Definition at line 247 of file res_fax.h.
Referenced by fax_session_reserve().
start_session
int(* const start_session) (struct ast_fax_session *)
starts the fax session
Definition at line 259 of file res_fax.h.
Referenced by fax_gateway_start(), and generic_fax_exec().
switch_to_t38
int(* const switch_to_t38) (struct ast_fax_session *)
switches an existing dual-mode session from audio to T.38
Definition at line 265 of file res_fax.h.
Referenced by generic_fax_exec().
type
const char* const type
the type of fax session supported with this ast_fax_tech structure
Definition at line 237 of file res_fax.h.
Referenced by ast_fax_tech_register(), ast_fax_tech_unregister(), cli_fax_show_capabilities(), cli_fax_show_sessions(), cli_fax_show_settings(), Property::load(), and manager_fax_sessions_entry().
version
const char* const version
version string of the technology module
Definition at line 241 of file res_fax.h.
Referenced by cli_fax_show_version(), and ParsingContext::next().
write
int(* const write) (struct ast_fax_session *, const struct ast_frame *)
writes an Asterisk frame to the fax session
Definition at line 257 of file res_fax.h.
Referenced by fax_gateway_detect_v21(), fax_gateway_framehook(), generic_fax_exec(), and MultiOrderedConfigParser::write().
The documentation for this struct was generated from the following file:
res_fax.h