Asterisk - The Open Source Telephony Project: format_g726.c File Reference
format_g726.c File Reference
Module: Media File Formats
Headerless G.726 (16/24/32/40kbps) data format for Asterisk.
#include "asterisk.h"
#include "asterisk/mod_format.h"
#include "asterisk/module.h"
#include "asterisk/endian.h"
#include "asterisk/format_cache.h"
Data Structures
struct g726_desc
Macros
#define BUF_SIZE (5*FRAME_TIME) /* max frame size in bytes ? */
#define FRAME_TIME 10 /* 10 ms size */
#define RATE_16 3
#define RATE_24 2
#define RATE_32 1
#define RATE_40 0
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int g726_16_open (struct ast_filestream *s)
static int g726_16_rewrite (struct ast_filestream *s, const char *comment)
static int g726_24_open (struct ast_filestream *s)
static int g726_24_rewrite (struct ast_filestream *s, const char *comment)
static int g726_32_open (struct ast_filestream *s)
static int g726_32_rewrite (struct ast_filestream *s, const char *comment)
static int g726_40_open (struct ast_filestream *s)
static int g726_40_rewrite (struct ast_filestream *s, const char *comment)
static int g726_open (struct ast_filestream *tmp, int rate)
static struct ast_frame * g726_read (struct ast_filestream *s, int *whennext)
static int g726_seek (struct ast_filestream *fs, off_t sample_offset, int whence)
static off_t g726_tell (struct ast_filestream *fs)
static int g726_trunc (struct ast_filestream *fs)
static int g726_write (struct ast_filestream *s, struct ast_frame *f)
static int load_module (void)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Raw G.726 (16/24/32/40kbps) data" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_APP_DEPEND }
static const struct ast_module_info * ast_module_info = &__mod_info
static struct ast_format_def f_def []
static int frame_size [4]
Detailed Description
Headerless G.726 (16/24/32/40kbps) data format for Asterisk.
File name extensions:
40 kbps: g726-40
32 kbps: g726-32
24 kbps: g726-24
16 kbps: g726-16
Definition in file format_g726.c.
Macro Definition Documentation
BUF_SIZE
#define BUF_SIZE (5*FRAME_TIME) /* max frame size in bytes ? */
Definition at line 50 of file format_g726.c.
FRAME_TIME
#define FRAME_TIME 10 /* 10 ms size */
Definition at line 48 of file format_g726.c.
Referenced by g726_read().
RATE_16
#define RATE_16 3
Definition at line 45 of file format_g726.c.
Referenced by g726_16_open(), and g726_16_rewrite().
RATE_24
#define RATE_24 2
Definition at line 44 of file format_g726.c.
Referenced by g726_24_open(), and g726_24_rewrite().
RATE_32
#define RATE_32 1
Definition at line 43 of file format_g726.c.
Referenced by g726_32_open(), and g726_32_rewrite().
RATE_40
#define RATE_40 0
Definition at line 42 of file format_g726.c.
Referenced by g726_40_open(), and g726_40_rewrite().
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 289 of file format_g726.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 289 of file format_g726.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 289 of file format_g726.c.
g726_16_open()
static int g726_16_open (struct ast_filestream * s) static
Definition at line 89 of file format_g726.c.
References g726_open(), and RATE_16.
 {
    return g726_open(s, RATE_16);
 }
g726_16_rewrite()
static int g726_16_rewrite (struct ast_filestream * s, const char * comment) static
Definition at line 109 of file format_g726.c.
References g726_open(), and RATE_16.
 {
    return g726_open(s, RATE_16);
 }
g726_24_open()
static int g726_24_open (struct ast_filestream * s) static
Definition at line 84 of file format_g726.c.
References g726_open(), and RATE_24.
 {
    return g726_open(s, RATE_24);
 }
g726_24_rewrite()
static int g726_24_rewrite (struct ast_filestream * s, const char * comment) static
Definition at line 104 of file format_g726.c.
References g726_open(), and RATE_24.
 {
    return g726_open(s, RATE_24);
 }
g726_32_open()
static int g726_32_open (struct ast_filestream * s) static
Definition at line 79 of file format_g726.c.
References g726_open(), and RATE_32.
 {
    return g726_open(s, RATE_32);
 }
g726_32_rewrite()
static int g726_32_rewrite (struct ast_filestream * s, const char * comment) static
Definition at line 99 of file format_g726.c.
References g726_open(), and RATE_32.
 {
    return g726_open(s, RATE_32);
 }
g726_40_open()
static int g726_40_open (struct ast_filestream * s) static
Definition at line 74 of file format_g726.c.
References g726_open(), and RATE_40.
 {
    return g726_open(s, RATE_40);
 }
g726_40_rewrite()
static int g726_40_rewrite (struct ast_filestream * s, const char * comment) static
Definition at line 94 of file format_g726.c.
References g726_open(), and RATE_40.
 {
    return g726_open(s, RATE_40);
 }
g726_open()
static int g726_open (struct ast_filestream * tmp, int rate) static
Definition at line 66 of file format_g726.c.
References ast_filestream::_private, ast_debug, and g726_desc::rate.
Referenced by g726_16_open(), g726_16_rewrite(), g726_24_open(), g726_24_rewrite(), g726_32_open(), g726_32_rewrite(), g726_40_open(), and g726_40_rewrite().
 {
    struct g726_desc *s = (struct g726_desc *)tmp->_private;
    s->rate = rate;
    ast_debug(1, "Created filestream G.726-%dk.\n", 40 - s->rate * 8);
    return 0;
 }
g726_read()
static struct ast_frame* g726_read (struct ast_filestream * s, int * whennext) static
Definition at line 118 of file format_g726.c.
References ast_filestream::_private, ast_format_get_name(), AST_FRAME_SET_BUFFER, AST_FRIENDLY_OFFSET, ast_log, ast_filestream::buf, ast_frame::data, ast_frame::datalen, errno, ast_filestream::f, ast_frame_subclass::format, ast_filestream::fr, frame_size, FRAME_TIME, LOG_WARNING, NULL, ast_frame::ptr, g726_desc::rate, ast_frame::samples, and ast_frame::subclass.
 {
    size_t res;
    struct g726_desc *fs = (struct g726_desc *)s->_private;
    /* Send a frame from the file to the appropriate channel */
    AST_FRAME_SET_BUFFER(&s->fr, s->buf, AST_FRIENDLY_OFFSET, frame_size[fs->rate]);
    s->fr.samples = 8 * FRAME_TIME;
    if ((res = fread(s->fr.data.ptr, 1, s->fr.datalen, s->f)) != s->fr.datalen) {
       if (res) {
          ast_log(LOG_WARNING, "Short read of %s data (expected %d bytes, read %zu): %s\n",
                ast_format_get_name(s->fr.subclass.format), s->fr.datalen, res,
                strerror(errno));
       }
       return NULL;
    }
    *whennext = s->fr.samples;
    return &s->fr;
 }
g726_seek()
static int g726_seek (struct ast_filestream * fs, off_t sample_offset, int whence) static
Definition at line 156 of file format_g726.c.
References ast_log, AST_LOG_WARNING, errno, ast_filestream::f, max, min, and SEEK_FORCECUR.
 {
    off_t offset = 0, min = 0, cur, max, distance;
    if ((cur = ftello(fs->f)) < 0) {
       ast_log(AST_LOG_WARNING, "Unable to determine current position in g726 filestream %p: %s\n", fs, strerror(errno));
       return -1;
    }
    if (fseeko(fs->f, 0, SEEK_END) < 0) {
       ast_log(AST_LOG_WARNING, "Unable to seek to end of g726 filestream %p: %s\n", fs, strerror(errno));
       return -1;
    }
    if ((max = ftello(fs->f)) < 0) {
       ast_log(AST_LOG_WARNING, "Unable to determine max position in g726 filestream %p: %s\n", fs, strerror(errno));
       return -1;
    }
    /* have to fudge to frame here, so not fully to sample */
    distance = sample_offset / 2;
    if (whence == SEEK_SET) {
       offset = distance;
    } else if (whence == SEEK_CUR || whence == SEEK_FORCECUR) {
       offset = distance + cur;
    } else if (whence == SEEK_END) {
       offset = max - distance;
    }
    if (whence != SEEK_FORCECUR) {
       offset = offset > max ? max : offset;
       offset = offset < min ? min : offset;
    }
    return fseeko(fs->f, offset, SEEK_SET);
 }
g726_tell()
static off_t g726_tell (struct ast_filestream * fs) static
Definition at line 197 of file format_g726.c.
References ast_filestream::f.
 {
    return ftello(fs->f) << 1;
 }
g726_trunc()
static int g726_trunc (struct ast_filestream * fs) static
Definition at line 192 of file format_g726.c.
 {
    return -1;
 }
g726_write()
static int g726_write (struct ast_filestream * s, struct ast_frame * f) static
Definition at line 138 of file format_g726.c.
References ast_filestream::_private, ast_log, ast_frame::data, ast_frame::datalen, errno, ast_filestream::f, frame_size, if(), LOG_WARNING, ast_frame::ptr, and g726_desc::rate.
 {
    int res;
    struct g726_desc *fs = (struct g726_desc *)s->_private;
    if (f->datalen % frame_size[fs->rate]) {
       ast_log(LOG_WARNING, "Invalid data length %d, should be multiple of %d\n",
                   f->datalen, frame_size[fs->rate]);
       return -1;
    }
    if ((res = fwrite(f->data.ptr, 1, f->datalen, s->f)) != f->datalen) {
       ast_log(LOG_WARNING, "Bad write (%d/%d): %s\n",
             res, frame_size[fs->rate], strerror(errno));
          return -1;
    }
    return 0;
 }
load_module()
static int load_module (void) static
Definition at line 269 of file format_g726.c.
References ast_format_def_register, ast_format_g726, ast_log, AST_MODFLAG_LOAD_ORDER, AST_MODPRI_APP_DEPEND, AST_MODULE_INFO(), AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, AST_MODULE_SUPPORT_CORE, ASTERISK_GPL_KEY, ast_format_def::desc_size, ast_format_def::format, LOG_WARNING, name, and unload_module().
 {
    int i;
    for (i = 0; f_def[i].desc_size ; i++) {
       f_def[i].format = ast_format_g726;
       if (ast_format_def_register(&f_def[i])) { /* errors are fatal */
          ast_log(LOG_WARNING, "Failed to register format %s.\n", f_def[i].name);
          unload_module();
          return AST_MODULE_LOAD_DECLINE;
       }
    }
    return AST_MODULE_LOAD_SUCCESS;
 }
unload_module()
static int unload_module (void) static
Definition at line 258 of file format_g726.c.
References ast_format_def_unregister(), ast_log, ast_format_def::desc_size, LOG_WARNING, and name.
Referenced by load_module().
 {
    int i;
    for (i = 0; f_def[i].desc_size ; i++) {
       if (ast_format_def_unregister(f_def[i].name))
          ast_log(LOG_WARNING, "Failed to unregister format %s.\n", f_def[i].name);
    }
    return(0);
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Raw G.726 (16/24/32/40kbps) data" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_APP_DEPEND } static
Definition at line 289 of file format_g726.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 289 of file format_g726.c.
f_def
struct ast_format_def f_def[] static
Definition at line 202 of file format_g726.c.
frame_size
int frame_size[4] static
Definition at line 52 of file format_g726.c.
Referenced by after_bridge_move_channel(), ast_websocket_read(), ast_websocket_write(), g726_read(), and g726_write().