Asterisk - The Open Source Telephony Project: res_pjsip_send_to_voicemail.c File Reference
res_pjsip_send_to_voicemail.c File Reference
Module for managing send to voicemail requests in SIP REFER messages against PJSIP channels.
#include "asterisk.h"
#include <pjsip.h>
#include <pjsip_ua.h>
#include "asterisk/pbx.h"
#include "asterisk/res_pjsip.h"
#include "asterisk/res_pjsip_session.h"
#include "asterisk/module.h"
Macros
#define DATASTORE_NAME "call_feature_send_to_vm_datastore"
#define SEND_TO_VM_HEADER "PJSIP_HEADER(add,X-Digium-Call-Feature)"
#define SEND_TO_VM_HEADER_VALUE "feature_send_to_vm"
#define SEND_TO_VM_REDIRECT "REDIRECTING(reason)"
#define SEND_TO_VM_REDIRECT_QUOTED_VALUE "\"" SEND_TO_VM_REDIRECT_VALUE "\""
#define SEND_TO_VM_REDIRECT_VALUE "send_to_vm"
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static void channel_cleanup_wrapper (void *data)
static pjsip_fromto_hdr * get_diversion_header (pjsip_rx_data *rdata)
static pjsip_param * get_diversion_reason (pjsip_fromto_hdr *hdr)
static int handle_incoming_request (struct ast_sip_session *session, struct pjsip_rx_data *rdata)
static void handle_outgoing_response (struct ast_sip_session *session, struct pjsip_tx_data *tdata)
static int has_call_feature (pjsip_rx_data *rdata)
static int has_diversion_reason (pjsip_rx_data *rdata)
static int load_module (void)
static void send_response (struct ast_sip_session *session, int code, struct pjsip_rx_data *rdata)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "PJSIP REFER Send to Voicemail Support" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_APP_DEPEND, .requires = "res_pjsip,res_pjsip_session", }
static const struct ast_module_info * ast_module_info = &__mod_info
static struct ast_datastore_info call_feature_info
static struct ast_sip_session_supplement refer_supplement
Detailed Description
Module for managing send to voicemail requests in SIP REFER messages against PJSIP channels.
Author
Jonathan Rose jrose.nosp@m.@dig.nosp@m.ium.c.nosp@m.om
Definition in file res_pjsip_send_to_voicemail.c.
Macro Definition Documentation
DATASTORE_NAME
#define DATASTORE_NAME "call_feature_send_to_vm_datastore"
Definition at line 44 of file res_pjsip_send_to_voicemail.c.
Referenced by handle_incoming_request(), and handle_outgoing_response().
SEND_TO_VM_HEADER
#define SEND_TO_VM_HEADER "PJSIP_HEADER(add,X-Digium-Call-Feature)"
Definition at line 46 of file res_pjsip_send_to_voicemail.c.
Referenced by handle_incoming_request(), and handle_outgoing_response().
SEND_TO_VM_HEADER_VALUE
#define SEND_TO_VM_HEADER_VALUE "feature_send_to_vm"
Definition at line 47 of file res_pjsip_send_to_voicemail.c.
Referenced by handle_incoming_request(), and has_call_feature().
SEND_TO_VM_REDIRECT
#define SEND_TO_VM_REDIRECT "REDIRECTING(reason)"
Definition at line 49 of file res_pjsip_send_to_voicemail.c.
Referenced by handle_incoming_request(), and handle_outgoing_response().
SEND_TO_VM_REDIRECT_QUOTED_VALUE
#define SEND_TO_VM_REDIRECT_QUOTED_VALUE "\"" SEND_TO_VM_REDIRECT_VALUE "\""
Definition at line 51 of file res_pjsip_send_to_voicemail.c.
Referenced by has_diversion_reason().
SEND_TO_VM_REDIRECT_VALUE
#define SEND_TO_VM_REDIRECT_VALUE "send_to_vm"
Definition at line 50 of file res_pjsip_send_to_voicemail.c.
Referenced by handle_incoming_request(), and has_diversion_reason().
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 235 of file res_pjsip_send_to_voicemail.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 235 of file res_pjsip_send_to_voicemail.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 235 of file res_pjsip_send_to_voicemail.c.
channel_cleanup_wrapper()
static void channel_cleanup_wrapper (void * data) static
Definition at line 64 of file res_pjsip_send_to_voicemail.c.
References ast_channel_cleanup, and ast_channel::data.
 {
    struct ast_channel *chan = data;
    ast_channel_cleanup(chan);
 }
get_diversion_header()
static pjsip_fromto_hdr* get_diversion_header (pjsip_rx_data * rdata) static
Definition at line 81 of file res_pjsip_send_to_voicemail.c.
References NULL, and value.
Referenced by has_diversion_reason().
 {
    static const pj_str_t from_str = { "From", 4 };
    static const pj_str_t diversion_str = { "Diversion", 9 };
    pjsip_generic_string_hdr *hdr;
    pj_str_t value;
    if (!(hdr = pjsip_msg_find_hdr_by_name(
             rdata->msg_info.msg, &diversion_str, NULL))) {
       return NULL;
    }
    pj_strdup_with_null(rdata->tp_info.pool, &value, &hdr->hvalue);
    /* parse as a fromto header */
    return pjsip_parse_hdr(rdata->tp_info.pool, &from_str, value.ptr,
                 pj_strlen(&value), NULL);
 }
get_diversion_reason()
static pjsip_param* get_diversion_reason (pjsip_fromto_hdr * hdr) static
Definition at line 75 of file res_pjsip_send_to_voicemail.c.
Referenced by has_diversion_reason().
 {
    static const pj_str_t reason_str = { "reason", 6 };
    return pjsip_param_find(&hdr->other_param, &reason_str);
 }
handle_incoming_request()
static int handle_incoming_request (struct ast_sip_session * session, struct pjsip_rx_data * rdata) static
Definition at line 125 of file res_pjsip_send_to_voicemail.c.
References ao2_ref, ast_channel_bridge_peer(), ast_channel_name(), ast_channel_unref, ast_log, ast_sip_session_add_datastore(), ast_sip_session_alloc_datastore(), ast_sorcery_object_get_id(), ast_sip_session::channel, ast_datastore::data, DATASTORE_NAME, ast_sip_session::endpoint, has_call_feature(), has_diversion_reason(), LOG_WARNING, pbx_builtin_setvar_helper(), send_response(), SEND_TO_VM_HEADER, SEND_TO_VM_HEADER_VALUE, SEND_TO_VM_REDIRECT, and SEND_TO_VM_REDIRECT_VALUE.
 {
    struct ast_datastore *sip_session_datastore;
    struct ast_channel *other_party;
    int has_feature;
    int has_reason;
    if (!session->channel) {
       return 0;
    }
    has_feature = has_call_feature(rdata);
    has_reason = has_diversion_reason(rdata);
    if (!has_feature && !has_reason) {
       /* If we don't have a call feature or diversion reason or if
          it's not a feature this module is related to then there
          is nothing to do. */
       return 0;
    }
    /* Check bridge status... */
    other_party = ast_channel_bridge_peer(session->channel);
    if (!other_party) {
       /* The channel wasn't in a two party bridge */
       ast_log(LOG_WARNING, "%s (%s) attempted to transfer to voicemail, "
          "but was not in a two party bridge.\n",
          ast_sorcery_object_get_id(session->endpoint),
          ast_channel_name(session->channel));
       send_response(session, 400, rdata);
       return -1;
    }
    sip_session_datastore = ast_sip_session_alloc_datastore(
       &call_feature_info, DATASTORE_NAME);
    if (!sip_session_datastore) {
       ast_channel_unref(other_party);
       send_response(session, 500, rdata);
       return -1;
    }
    sip_session_datastore->data = other_party;
    if (ast_sip_session_add_datastore(session, sip_session_datastore)) {
       ao2_ref(sip_session_datastore, -1);
       send_response(session, 500, rdata);
       return -1;
    }
    if (has_feature) {
       pbx_builtin_setvar_helper(other_party, SEND_TO_VM_HEADER,
                  SEND_TO_VM_HEADER_VALUE);
    }
    if (has_reason) {
       pbx_builtin_setvar_helper(other_party, SEND_TO_VM_REDIRECT,
                  SEND_TO_VM_REDIRECT_VALUE);
    }
    ao2_ref(sip_session_datastore, -1);
    return 0;
 }
handle_outgoing_response()
static void handle_outgoing_response (struct ast_sip_session * session, struct pjsip_tx_data * tdata) static
Definition at line 187 of file res_pjsip_send_to_voicemail.c.
References ao2_ref, ast_sip_session_get_datastore(), ast_sip_session_remove_datastore(), ast_datastore::data, DATASTORE_NAME, NULL, pbx_builtin_setvar_helper(), SEND_TO_VM_HEADER, SEND_TO_VM_REDIRECT, and status.
 {
    pjsip_status_line status = tdata->msg->line.status;
    struct ast_datastore *feature_datastore =
       ast_sip_session_get_datastore(session, DATASTORE_NAME);
    struct ast_channel *target_chan;
    if (!feature_datastore) {
       return;
    }
    /* Since we are handling the response, there is no need to keep the datastore in the session anymore. */
    ast_sip_session_remove_datastore(session, DATASTORE_NAME);
    /* If the response >= 300, the refer failed and we need to clear the feature. */
    if (status.code >= 300) {
       target_chan = feature_datastore->data;
       pbx_builtin_setvar_helper(target_chan, SEND_TO_VM_HEADER, NULL);
       pbx_builtin_setvar_helper(target_chan, SEND_TO_VM_REDIRECT, NULL);
    }
    ao2_ref(feature_datastore, -1);
 }
has_call_feature()
static int has_call_feature (pjsip_rx_data * rdata) static
Definition at line 115 of file res_pjsip_send_to_voicemail.c.
References NULL, and SEND_TO_VM_HEADER_VALUE.
Referenced by handle_incoming_request().
 {
    static const pj_str_t call_feature_str = { "X-Digium-Call-Feature", 21 };
    pjsip_generic_string_hdr *hdr = pjsip_msg_find_hdr_by_name(
       rdata->msg_info.msg, &call_feature_str, NULL);
    return hdr && !pj_stricmp2(&hdr->hvalue, SEND_TO_VM_HEADER_VALUE);
 }
has_diversion_reason()
static int has_diversion_reason (pjsip_rx_data * rdata) static
Definition at line 101 of file res_pjsip_send_to_voicemail.c.
References get_diversion_header(), get_diversion_reason(), SEND_TO_VM_REDIRECT_QUOTED_VALUE, and SEND_TO_VM_REDIRECT_VALUE.
Referenced by handle_incoming_request().
 {
    pjsip_param *reason;
    pjsip_fromto_hdr *hdr = get_diversion_header(rdata);
    if (!hdr) {
       return 0;
    }
    reason = get_diversion_reason(hdr);
    return reason
       && (!pj_stricmp2(&reason->value, SEND_TO_VM_REDIRECT_QUOTED_VALUE)
          || !pj_stricmp2(&reason->value, SEND_TO_VM_REDIRECT_VALUE));
 }
load_module()
static int load_module (void) static
Definition at line 216 of file res_pjsip_send_to_voicemail.c.
References AST_MODULE_LOAD_SUCCESS, and ast_sip_session_register_supplement.
Referenced by unload_module().
 {
    ast_sip_session_register_supplement(&refer_supplement);
    return AST_MODULE_LOAD_SUCCESS;
 }
send_response()
static void send_response (struct ast_sip_session * session, int code, struct pjsip_rx_data * rdata) static
Definition at line 53 of file res_pjsip_send_to_voicemail.c.
References ast_sip_session::inv_session, and NULL.
Referenced by handle_incoming_request().
 {
    pjsip_tx_data *tdata;
    if (pjsip_dlg_create_response(session->inv_session->dlg, rdata, code, NULL, &tdata) == PJ_SUCCESS) {
       struct pjsip_transaction *tsx = pjsip_rdata_get_tsx(rdata);
       pjsip_dlg_send_response(session->inv_session->dlg, tsx, tdata);
    }
 }
unload_module()
static int unload_module (void) static
Definition at line 223 of file res_pjsip_send_to_voicemail.c.
References AST_MODFLAG_LOAD_ORDER, AST_MODPRI_APP_DEPEND, AST_MODULE_INFO(), AST_MODULE_SUPPORT_CORE, ast_sip_session_unregister_supplement(), ASTERISK_GPL_KEY, and load_module().
 {
    ast_sip_session_unregister_supplement(&refer_supplement);
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "PJSIP REFER Send to Voicemail Support" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_APP_DEPEND, .requires = "res_pjsip,res_pjsip_session", } static
Definition at line 235 of file res_pjsip_send_to_voicemail.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 235 of file res_pjsip_send_to_voicemail.c.
call_feature_info
struct ast_datastore_info call_feature_info static
Initial value:
= {
   .type = "REFER call feature info",
   .destroy = channel_cleanup_wrapper,
}
Definition at line 70 of file res_pjsip_send_to_voicemail.c.
refer_supplement
struct ast_sip_session_supplement refer_supplement static
Initial value:
= {
   .method = "REFER",
   .incoming_request = handle_incoming_request,
   .outgoing_response = handle_outgoing_response,
}
Definition at line 210 of file res_pjsip_send_to_voicemail.c.