Asterisk - The Open Source Telephony Project: res_endpoint_stats.c File Reference
res_endpoint_stats.c File Reference
#include "asterisk.h"
#include "asterisk/module.h"
#include "asterisk/stasis_endpoints.h"
#include "asterisk/stasis_message_router.h"
#include "asterisk/statsd.h"
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static void cache_update_cb (void *data, struct stasis_subscription *sub, struct stasis_message *message)
static int dump_cache_load (void *obj, void *arg, int flags)
static int dump_cache_unload (void *obj, void *arg, int flags)
static void handle_endpoint_update (struct ast_endpoint_snapshot *old_snapshot, struct ast_endpoint_snapshot *new_snapshot)
static int load_module (void)
static int unload_module (void)
static void update_endpoint_state (struct ast_endpoint_snapshot *snapshot, const char *delta)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_DEFAULT , .description = "Endpoint statistics" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_EXTENDED, .load = load_module, .unload = unload_module, .requires = "res_statsd" }
static const struct ast_module_info * ast_module_info = &__mod_info
static struct stasis_message_router * router
Statsd Endpoint stats.
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 155 of file res_endpoint_stats.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 155 of file res_endpoint_stats.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 155 of file res_endpoint_stats.c.
cache_update_cb()
static void cache_update_cb (void * data, struct stasis_subscription * sub, struct stasis_message * message) static
Definition at line 78 of file res_endpoint_stats.c.
References ast_endpoint_snapshot_type(), handle_endpoint_update(), stasis_cache_update::new_snapshot, stasis_cache_update::old_snapshot, stasis_message_data(), stasis_cache_update::type, and update().
Referenced by load_module().
 {
    struct stasis_cache_update *update = stasis_message_data(message);
    struct ast_endpoint_snapshot *old_snapshot;
    struct ast_endpoint_snapshot *new_snapshot;
    if (ast_endpoint_snapshot_type() != update->type) {
       return;
    }
    old_snapshot = stasis_message_data(update->old_snapshot);
    new_snapshot = stasis_message_data(update->new_snapshot);
    handle_endpoint_update(old_snapshot, new_snapshot);
 }
dump_cache_load()
static int dump_cache_load (void * obj, void * arg, int flags) static
Definition at line 95 of file res_endpoint_stats.c.
References handle_endpoint_update(), NULL, and stasis_message_data().
Referenced by load_module().
 {
    struct stasis_message *msg = obj;
    struct ast_endpoint_snapshot *snapshot = stasis_message_data(msg);
    handle_endpoint_update(NULL, snapshot);
    return 0;
 }
dump_cache_unload()
static int dump_cache_unload (void * obj, void * arg, int flags) static
Definition at line 105 of file res_endpoint_stats.c.
References handle_endpoint_update(), NULL, and stasis_message_data().
Referenced by unload_module().
 {
    struct stasis_message *msg = obj;
    struct ast_endpoint_snapshot *snapshot = stasis_message_data(msg);
    handle_endpoint_update(snapshot, NULL);
    return 0;
 }
handle_endpoint_update()
static void handle_endpoint_update (struct ast_endpoint_snapshot * old_snapshot, struct ast_endpoint_snapshot * new_snapshot) static
Definition at line 60 of file res_endpoint_stats.c.
References AST_STATSD_GAUGE, ast_statsd_log_full_va(), ast_statsd_log_string(), ast_endpoint_snapshot::num_channels, ast_endpoint_snapshot::resource, ast_endpoint_snapshot::state, ast_endpoint_snapshot::tech, and update_endpoint_state().
Referenced by cache_update_cb(), dump_cache_load(), and dump_cache_unload().
 {
    if (!old_snapshot && new_snapshot) {
       ast_statsd_log_string("endpoints.count", AST_STATSD_GAUGE, "+1", 1.0);
       update_endpoint_state(new_snapshot, "+1");
    } else if (old_snapshot && !new_snapshot) {
       ast_statsd_log_string("endpoints.count", AST_STATSD_GAUGE, "-1", 1.0);
       update_endpoint_state(old_snapshot, "-1");
    } else {
       if (old_snapshot->state != new_snapshot->state) {
          update_endpoint_state(old_snapshot, "-1");
          update_endpoint_state(new_snapshot, "+1");
       }
       ast_statsd_log_full_va("endpoints.%s.%s.channels", AST_STATSD_GAUGE, new_snapshot->num_channels, 1.0,
          new_snapshot->tech, new_snapshot->resource);
    }
 }
load_module()
static int load_module (void) static
Definition at line 115 of file res_endpoint_stats.c.
References ao2_callback, ao2_ref, ast_endpoint_cache(), ast_endpoint_snapshot_type(), ast_endpoint_topic_all_cached(), AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, cache_update_cb(), dump_cache_load(), endpoints, NULL, OBJ_MULTIPLE, OBJ_NODATA, OBJ_NOLOCK, stasis_cache_dump(), stasis_cache_update_type(), stasis_message_router_add(), and stasis_message_router_create.
Referenced by unload_module().
 {
    struct ao2_container *endpoints;
    router = stasis_message_router_create(ast_endpoint_topic_all_cached());
    if (!router) {
       return AST_MODULE_LOAD_DECLINE;
    }
    stasis_message_router_add(router, stasis_cache_update_type(), cache_update_cb, NULL);
    endpoints = stasis_cache_dump(ast_endpoint_cache(), ast_endpoint_snapshot_type());
    if (endpoints) {
       ao2_callback(endpoints, OBJ_MULTIPLE | OBJ_NODATA | OBJ_NOLOCK, dump_cache_load, NULL);
       ao2_ref(endpoints, -1);
    }
    return AST_MODULE_LOAD_SUCCESS;
 }
unload_module()
static int unload_module (void) static
Definition at line 134 of file res_endpoint_stats.c.
References ao2_callback, ao2_ref, ast_endpoint_cache(), ast_endpoint_snapshot_type(), AST_MODFLAG_DEFAULT, AST_MODULE_INFO(), AST_MODULE_SUPPORT_EXTENDED, ASTERISK_GPL_KEY, dump_cache_unload(), endpoints, load_module(), NULL, OBJ_MULTIPLE, OBJ_NODATA, OBJ_NOLOCK, stasis_cache_dump(), and stasis_message_router_unsubscribe_and_join().
 {
    struct ao2_container *endpoints;
    endpoints = stasis_cache_dump(ast_endpoint_cache(), ast_endpoint_snapshot_type());
    if (endpoints) {
       ao2_callback(endpoints, OBJ_MULTIPLE | OBJ_NODATA | OBJ_NOLOCK, dump_cache_unload, NULL);
       ao2_ref(endpoints, -1);
    }
    stasis_message_router_unsubscribe_and_join(router);
    router = NULL;
    return 0;
 }
update_endpoint_state()
static void update_endpoint_state (struct ast_endpoint_snapshot * snapshot, const char * delta) static
Definition at line 45 of file res_endpoint_stats.c.
References AST_ENDPOINT_OFFLINE, AST_ENDPOINT_ONLINE, AST_ENDPOINT_UNKNOWN, AST_STATSD_GAUGE, ast_statsd_log_string(), and ast_endpoint_snapshot::state.
Referenced by handle_endpoint_update().
 {
    switch (snapshot->state) {
    case AST_ENDPOINT_UNKNOWN:
       ast_statsd_log_string("endpoints.state.unknown", AST_STATSD_GAUGE, delta, 1.0);
       break;
    case AST_ENDPOINT_OFFLINE:
       ast_statsd_log_string("endpoints.state.offline", AST_STATSD_GAUGE, delta, 1.0);
       break;
    case AST_ENDPOINT_ONLINE:
       ast_statsd_log_string("endpoints.state.online", AST_STATSD_GAUGE, delta, 1.0);
       break;
    }
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_DEFAULT , .description = "Endpoint statistics" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_EXTENDED, .load = load_module, .unload = unload_module, .requires = "res_statsd" } static
Definition at line 155 of file res_endpoint_stats.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 155 of file res_endpoint_stats.c.
router
struct stasis_message_router* router static
Statsd Endpoint stats.
This module subscribes to Stasis endpoints and send statistics based on their state.
Author
Matthew Jordan mjord.nosp@m.an@d.nosp@m.igium.nosp@m..com
Since
13.7.0
Stasis message router
Definition at line 43 of file res_endpoint_stats.c.