Asterisk - The Open Source Telephony Project: LPCencode.h File Reference
LPCencode.h File Reference
Functions
void LPCencode (float *syntdenum, float *weightdenum, int *lsf_index, float *data, iLBC_Enc_Inst_t *iLBCenc_inst)
Function Documentation
LPCencode()
void LPCencode (float * syntdenum, float * weightdenum, int * lsf_index, float * data, iLBC_Enc_Inst_t * iLBCenc_inst)
Definition at line 214 of file LPCencode.c.
References LPC_FILTERORDER, iLBC_Enc_Inst_t_::lpc_n, LPC_N_MAX, LSF_check(), iLBC_Enc_Inst_t_::lsfdeqold, iLBC_Enc_Inst_t_::lsfold, SimpleAnalysis(), SimpleInterpolateLSF(), and SimplelsfQ().
Referenced by iLBC_encode().
     {
        float lsf[LPC_FILTERORDER * LPC_N_MAX];
        float lsfdeq[LPC_FILTERORDER * LPC_N_MAX];
        SimpleAnalysis(lsf, data, iLBCenc_inst);
        SimplelsfQ(lsfdeq, lsf_index, lsf, iLBCenc_inst->lpc_n);
        LSF_check(lsfdeq, LPC_FILTERORDER, iLBCenc_inst->lpc_n);
        SimpleInterpolateLSF(syntdenum, weightdenum,
            lsf, lsfdeq, iLBCenc_inst->lsfold,
            iLBCenc_inst->lsfdeqold, LPC_FILTERORDER, iLBCenc_inst);
    }