Asterisk - The Open Source Telephony Project: app_alarmreceiver.c File Reference
app_alarmreceiver.c File Reference
Dial plan applications
Central Station Alarm receiver for Ademco Contact ID.
#include "asterisk.h"
#include <math.h>
#include <sys/wait.h>
#include <sys/time.h>
#include "asterisk/lock.h"
#include "asterisk/file.h"
#include "asterisk/channel.h"
#include "asterisk/pbx.h"
#include "asterisk/module.h"
#include "asterisk/translate.h"
#include "asterisk/app.h"
#include "asterisk/dsp.h"
#include "asterisk/config.h"
#include "asterisk/localtime.h"
#include "asterisk/callerid.h"
#include "asterisk/astdb.h"
#include "asterisk/utils.h"
#include "asterisk/indications.h"
#include "asterisk/format_cache.h"
Data Structures
struct event_node
Macros
#define ADEMCO_AUDIO_CALL_NEXT "606"
#define ADEMCO_CONTACT_ID "ADEMCO_CONTACT_ID"
#define ADEMCO_EXPRESS_4_1 "ADEMCO_EXPRESS_4_1"
#define ADEMCO_EXPRESS_4_2 "ADEMCO_EXPRESS_4_2"
#define ADEMCO_HIGH_SPEED "ADEMCO_HIGH_SPEED"
#define ADEMCO_MSG_TYPE_1 "18"
#define ADEMCO_MSG_TYPE_2 "98"
#define ADEMCO_MSG_TYPE_3 "17"
#define ADEMCO_MSG_TYPE_4 "27"
#define ADEMCO_MSG_TYPE_5 "55"
#define ADEMCO_MSG_TYPE_6 "56"
#define ADEMCO_SUPER_FAST "ADEMCO_SUPER_FAST"
#define ALMRCV_CONFIG "alarmreceiver.conf"
#define UNKNOWN_FORMAT "UNKNOWN_FORMAT"
Typedefs
typedef struct event_node event_node_t
Functions
static void __reg_module (void)
static void __unreg_module (void)
static int ademco_check_valid (char *signalling_type, char *event)
Check if the message is in known and valid Ademco format.
static int ademco_detect_format (char *signalling_type, char *event, int *no_checksum)
Detect the message format of an event.
static int ademco_verify_checksum (char *event, int expected)
Verify Ademco checksum.
static int alarmreceiver_exec (struct ast_channel *chan, const char *data)
This is the main function called by Asterisk Core whenever the App is invoked in the extension logic.
struct ast_module * AST_MODULE_SELF_SYM (void)
static void database_increment (char *key)
Attempt to access a database variable and increment it.
static int load_config (int reload)
Load the configuration from the configuration file.
static int load_module (void)
Load the module.
static int log_events (struct ast_channel *chan, char *signalling_type, event_node_t *event, int no_checksum)
Log events if configuration key logindividualevents is enabled or on exit.
static int receive_ademco_event (struct ast_channel *chan, event_node_t **ehead, char *signalling_type, int *no_checksum)
Receive Ademco ContactID or other format Data String.
static int receive_dtmf_digits (struct ast_channel *chan, char *digit_string, int buf_size, int expected, int *received)
Receive a fixed length DTMF string.
static int reload (void)
static int send_tone_burst (struct ast_channel *chan, const char *tone_freq, int tone_duration, int delay)
Send a single tone burst for a specified duration and frequency.
static int unload_module (void)
Unregister Alarm Receiver App.
static int write_event (FILE *logfile, event_node_t *event)
Log a single event.
static int write_metadata (FILE *logfile, char *signalling_type, struct ast_channel *chan, int no_checksum)
Write metadata to log file.
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_DEFAULT , .description = "Alarm Receiver for Asterisk" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_EXTENDED, .load = load_module, .unload = unload_module, .reload = reload, }
static int answait = 1250
static const char app [] = "AlarmReceiver"
static const struct ast_module_info * ast_module_info = &__mod_info
struct timeval call_start_time
static char db_family [128] = {'\0'}
struct {
char digit
char weight
} digits_mapping []
static char event_app [128] = {'\0'}
static char event_file [14] = "/event-XXXXXX"
static char event_spool_dir [128] = {'\0'}
static int fdtimeout = 2000
static int log_individual_events = 0
static int no_group_meta = 0
static int sdtimeout = 200
static char time_stamp_format [128] = {"%a %b %d, %Y @ %H:%M:%S %Z"}
static int toneloudness = 4096
Detailed Description
Central Station Alarm receiver for Ademco Contact ID.
Author
Steve Rodgers hwsta.nosp@m.r@ro.nosp@m.dgers.nosp@m..sdc.nosp@m.oxmai.nosp@m.l.co.nosp@m.m
*** WARNING *** WARNING *** WARNING *** WARNING *** WARNING *** WARNING *** WARNING *** WARNING ***
Use at your own risk. Please consult the GNU GPL license document included with Asterisk. *
*** WARNING *** WARNING *** WARNING *** WARNING *** WARNING *** WARNING *** WARNING *** WARNING ***
Definition in file app_alarmreceiver.c.
Macro Definition Documentation
ADEMCO_AUDIO_CALL_NEXT
#define ADEMCO_AUDIO_CALL_NEXT "606"
Definition at line 128 of file app_alarmreceiver.c.
Referenced by receive_ademco_event().
ADEMCO_CONTACT_ID
#define ADEMCO_CONTACT_ID "ADEMCO_CONTACT_ID"
Definition at line 71 of file app_alarmreceiver.c.
Referenced by ademco_check_valid(), ademco_detect_format(), and receive_ademco_event().
ADEMCO_EXPRESS_4_1
#define ADEMCO_EXPRESS_4_1 "ADEMCO_EXPRESS_4_1"
Definition at line 80 of file app_alarmreceiver.c.
Referenced by ademco_check_valid(), ademco_detect_format(), and receive_ademco_event().
ADEMCO_EXPRESS_4_2
#define ADEMCO_EXPRESS_4_2 "ADEMCO_EXPRESS_4_2"
Definition at line 87 of file app_alarmreceiver.c.
Referenced by ademco_check_valid(), ademco_detect_format(), and receive_ademco_event().
ADEMCO_HIGH_SPEED
#define ADEMCO_HIGH_SPEED "ADEMCO_HIGH_SPEED"
Definition at line 94 of file app_alarmreceiver.c.
Referenced by ademco_check_valid(), and ademco_detect_format().
ADEMCO_MSG_TYPE_1
#define ADEMCO_MSG_TYPE_1 "18"
Definition at line 121 of file app_alarmreceiver.c.
Referenced by ademco_check_valid(), and ademco_detect_format().
ADEMCO_MSG_TYPE_2
#define ADEMCO_MSG_TYPE_2 "98"
Definition at line 122 of file app_alarmreceiver.c.
Referenced by ademco_check_valid(), and ademco_detect_format().
ADEMCO_MSG_TYPE_3
#define ADEMCO_MSG_TYPE_3 "17"
Definition at line 123 of file app_alarmreceiver.c.
Referenced by ademco_check_valid(), and ademco_detect_format().
ADEMCO_MSG_TYPE_4
#define ADEMCO_MSG_TYPE_4 "27"
Definition at line 124 of file app_alarmreceiver.c.
Referenced by ademco_check_valid(), and ademco_detect_format().
ADEMCO_MSG_TYPE_5
#define ADEMCO_MSG_TYPE_5 "55"
Definition at line 125 of file app_alarmreceiver.c.
Referenced by ademco_check_valid(), and ademco_detect_format().
ADEMCO_MSG_TYPE_6
#define ADEMCO_MSG_TYPE_6 "56"
Definition at line 126 of file app_alarmreceiver.c.
Referenced by ademco_check_valid(), and ademco_detect_format().
ADEMCO_SUPER_FAST
#define ADEMCO_SUPER_FAST "ADEMCO_SUPER_FAST"
Definition at line 115 of file app_alarmreceiver.c.
Referenced by ademco_check_valid(), and ademco_detect_format().
ALMRCV_CONFIG
#define ALMRCV_CONFIG "alarmreceiver.conf"
Definition at line 68 of file app_alarmreceiver.c.
Referenced by load_config().
UNKNOWN_FORMAT
#define UNKNOWN_FORMAT "UNKNOWN_FORMAT"
Definition at line 69 of file app_alarmreceiver.c.
Referenced by ademco_check_valid(), ademco_detect_format(), alarmreceiver_exec(), and receive_ademco_event().
Typedef Documentation
event_node_t
typedef struct event_node event_node_t
Definition at line 142 of file app_alarmreceiver.c.
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 1000 of file app_alarmreceiver.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 1000 of file app_alarmreceiver.c.
ademco_check_valid()
static int ademco_check_valid (char * signalling_type, char * event) static
Check if the message is in known and valid Ademco format.
Parameters
signalling_type Expected signalling type for the message
event event received
Return values
0 The event is valid
-1 The event is not valid
Definition at line 523 of file app_alarmreceiver.c.
References ADEMCO_CONTACT_ID, ADEMCO_EXPRESS_4_1, ADEMCO_EXPRESS_4_2, ADEMCO_HIGH_SPEED, ADEMCO_MSG_TYPE_1, ADEMCO_MSG_TYPE_2, ADEMCO_MSG_TYPE_3, ADEMCO_MSG_TYPE_4, ADEMCO_MSG_TYPE_5, ADEMCO_MSG_TYPE_6, ADEMCO_SUPER_FAST, and UNKNOWN_FORMAT.
Referenced by receive_ademco_event().
 {
    if (!strcmp(signalling_type, UNKNOWN_FORMAT)) {
       return 1;
    }
    if (!strcmp(signalling_type, ADEMCO_CONTACT_ID)
       && strncmp(event + 4, ADEMCO_MSG_TYPE_1, 2)
       && strncmp(event + 4, ADEMCO_MSG_TYPE_2, 2)) {
       return -1;
    }
    if (!strcmp(signalling_type, ADEMCO_EXPRESS_4_1) && strncmp(event + 4, ADEMCO_MSG_TYPE_3, 2)) {
       return -1;
    }
    if (!strcmp(signalling_type, ADEMCO_EXPRESS_4_2) && strncmp(event + 4, ADEMCO_MSG_TYPE_4, 2)) {
       return -1;
    }
    if (!strcmp(signalling_type, ADEMCO_HIGH_SPEED) && strncmp(event + 4, ADEMCO_MSG_TYPE_5, 2)) {
       return -1;
    }
    if (!strcmp(signalling_type, ADEMCO_SUPER_FAST) && strncmp(event + 4, ADEMCO_MSG_TYPE_6, 2)) {
       return -1;
    }
    return 0;
 }
ademco_detect_format()
static int ademco_detect_format (char * signalling_type, char * event, int * no_checksum) static
Detect the message format of an event.
Parameters
signalling_type Expected signalling type for the message
event event received
no_checksum Should we calculate checksum for the message
Returns
The expected digits for the detected event type
Definition at line 563 of file app_alarmreceiver.c.
References ADEMCO_CONTACT_ID, ADEMCO_EXPRESS_4_1, ADEMCO_EXPRESS_4_2, ADEMCO_HIGH_SPEED, ADEMCO_MSG_TYPE_1, ADEMCO_MSG_TYPE_2, ADEMCO_MSG_TYPE_3, ADEMCO_MSG_TYPE_4, ADEMCO_MSG_TYPE_5, ADEMCO_MSG_TYPE_6, ADEMCO_SUPER_FAST, ast_debug, ast_verb, and UNKNOWN_FORMAT.
Referenced by receive_ademco_event().
 {
    int res = 16;
    if (!strncmp(event + 4, ADEMCO_MSG_TYPE_1, 2)
       || !strncmp(event + 4, ADEMCO_MSG_TYPE_2, 2)) {
       sprintf(signalling_type, "%s", ADEMCO_CONTACT_ID);
    }
    if (!strncmp(event + 4, ADEMCO_MSG_TYPE_3, 2)) {
       sprintf(signalling_type, "%s", ADEMCO_EXPRESS_4_1);
       res = 8;
    }
    if (!strncmp(event + 4, ADEMCO_MSG_TYPE_4, 2)) {
       sprintf(signalling_type, "%s", ADEMCO_EXPRESS_4_2);
       res = 9;
    }
    if (!strncmp(event + 4, ADEMCO_MSG_TYPE_5, 2)) {
       sprintf(signalling_type, "%s", ADEMCO_HIGH_SPEED);
    }
    if (!strncmp(event + 4, ADEMCO_MSG_TYPE_6, 2)) {
       sprintf(signalling_type, "%s", ADEMCO_SUPER_FAST);
       *no_checksum = 1;
       res = 15;
    }
    if (strcmp(signalling_type, UNKNOWN_FORMAT)) {
       ast_verb(4, "AlarmMonitoring: Detected format %s.\n", signalling_type);
       ast_debug(1, "AlarmMonitoring: Autodetected format %s.\n", signalling_type);
    }
    return res;
 }
ademco_verify_checksum()
static int ademco_verify_checksum (char * event, int expected) static
Verify Ademco checksum.
Since
11.0
Parameters
event Received DTMF String
expected Number of Digits expected
Return values
0 success
-1 failure
Definition at line 456 of file app_alarmreceiver.c.
References ARRAY_LEN, ast_verb, digit, and digits_mapping.
Referenced by receive_ademco_event().
 {
    int checksum = 0;
    int i, j;
    for (j = 0; j < expected; j++) {
       for (i = 0; i < ARRAY_LEN(digits_mapping); i++) {
          if (digits_mapping[i].digit == event[j]) {
             break;
          }
       }
       if (i >= ARRAY_LEN(digits_mapping)) {
          ast_verb(2, "AlarmReceiver: Bad DTMF character %c, trying again\n", event[j]);
          return -1;
       }
       checksum += digits_mapping[i].weight;
    }
    /* Checksum is mod(15) of the total */
    if (!(checksum % 15)) {
       return 0;
    }
    return -1;
 }
alarmreceiver_exec()
static int alarmreceiver_exec (struct ast_channel * chan, const char * data) static
This is the main function called by Asterisk Core whenever the App is invoked in the extension logic.
Parameters
chan Asterisk Channel
data Application data
Return values
0 success
-1 failure
Definition at line 792 of file app_alarmreceiver.c.
References answait, ast_answer(), ast_channel_name(), ast_channel_readformat(), ast_channel_writeformat(), ast_copy_string(), ast_debug, ast_format_alaw, ast_format_cmp(), AST_FORMAT_CMP_NOT_EQUAL, ast_format_ulaw, ast_free, ast_log, ast_safe_sleep(), ast_safe_system(), ast_set_read_format(), ast_set_write_format(), AST_STATE_UP, ast_strlen_zero, ast_tvnow(), ast_verb, call_start_time, event_app, log_events(), log_individual_events, LOG_WARNING, event_node::next, NULL, receive_ademco_event(), and UNKNOWN_FORMAT.
Referenced by load_module().
 {
    int res = 0;
    int no_checksum = 0;
    event_node_t *elp, *efree;
    char signalling_type[64] = "";
    event_node_t *event_head = NULL;
    if ((ast_format_cmp(ast_channel_writeformat(chan), ast_format_ulaw) == AST_FORMAT_CMP_NOT_EQUAL) &&
       (ast_format_cmp(ast_channel_writeformat(chan), ast_format_alaw) == AST_FORMAT_CMP_NOT_EQUAL)) {
       ast_verb(4, "AlarmReceiver: Setting write format to Mu-law\n");
       if (ast_set_write_format(chan, ast_format_ulaw)) {
          ast_log(LOG_WARNING, "AlarmReceiver: Unable to set write format to Mu-law on %s\n",ast_channel_name(chan));
          return -1;
       }
    }
    if ((ast_format_cmp(ast_channel_readformat(chan), ast_format_ulaw) == AST_FORMAT_CMP_NOT_EQUAL) &&
       (ast_format_cmp(ast_channel_readformat(chan), ast_format_alaw) == AST_FORMAT_CMP_NOT_EQUAL)) {
       ast_verb(4, "AlarmReceiver: Setting read format to Mu-law\n");
       if (ast_set_read_format(chan, ast_format_ulaw)) {
          ast_log(LOG_WARNING, "AlarmReceiver: Unable to set read format to Mu-law on %s\n",ast_channel_name(chan));
          return -1;
       }
    }
    /* Set default values for this invocation of the application */
    ast_copy_string(signalling_type, UNKNOWN_FORMAT, sizeof(signalling_type));
    call_start_time = ast_tvnow();
    /* Answer the channel if it is not already */
    if (ast_channel_state(chan) != AST_STATE_UP) {
       ast_verb(4, "AlarmReceiver: Answering channel\n");
       if (ast_answer(chan)) {
          return -1;
       }
    }
    /* Wait for the connection to settle post-answer */
    ast_verb(4, "AlarmReceiver: Waiting for connection to stabilize\n");
    if (ast_safe_sleep(chan, answait)) {
       return -1;
    }
    /* Attempt to receive the events */
    receive_ademco_event(chan, &event_head, signalling_type, &no_checksum);
    /* Events queued by receiver, write them all out here if so configured */
    if (!log_individual_events) {
       res = log_events(chan, signalling_type, event_head, no_checksum);
    }
    /* Do we exec a command line at the end? */
    if ((!res) && (!ast_strlen_zero(event_app)) && (event_head)) {
       ast_debug(1,"Alarmreceiver: executing: %s\n", event_app);
       ast_safe_system(event_app);
    }
    /* Free up the data allocated in our linked list */
    for (elp = event_head; (elp != NULL);) {
       efree = elp;
       elp = elp->next;
       ast_free(efree);
    }
    return 0;
 }
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 1000 of file app_alarmreceiver.c.
database_increment()
static void database_increment (char * key) static
Attempt to access a database variable and increment it.
Note
Only if the user defined db-family in alarmreceiver.conf
The alarmreceiver app will write statistics to a few variables in this family if it is defined. If the new key doesn't exist in the family, then create it and set its value to 1.
Parameters
key A database key to increment
Returns
Nothing
Definition at line 208 of file app_alarmreceiver.c.
References ast_db_get(), ast_db_put(), ast_strlen_zero, ast_verb, db_family, and value.
Referenced by receive_ademco_event().
 {
    unsigned v;
    char value[16];
    if (ast_strlen_zero(db_family)) {
       return;  /* If not defined, don't do anything */
    }
    if (ast_db_get(db_family, key, value, sizeof(value) - 1)) {
       ast_verb(4, "AlarmReceiver: Creating database entry %s and setting to 1\n", key);
       /* Guess we have to create it */
       ast_db_put(db_family, key, "1");
       return;
    }
    sscanf(value, "%30u", &v);
    v++;
    ast_verb(4, "AlarmReceiver: New value for %s: %u\n", key, v);
    snprintf(value, sizeof(value), "%u", v);
    if (ast_db_put(db_family, key, value)) {
       ast_verb(4, "AlarmReceiver: database_increment write error\n");
    }
    return;
 }
load_config()
static int load_config (int reload) static
Load the configuration from the configuration file.
Parameters
reload True on reload
Return values
1 success
0 failure
Definition at line 868 of file app_alarmreceiver.c.
References ALMRCV_CONFIG, answait, ast_config_destroy(), ast_config_load, ast_copy_string(), ast_log, ast_true(), ast_variable_retrieve(), ast_verb, CONFIG_FLAG_FILEUNCHANGED, CONFIG_STATUS_FILEINVALID, CONFIG_STATUS_FILEUNCHANGED, db_family, event_app, event_spool_dir, fdtimeout, LOG_ERROR, log_individual_events, no_group_meta, NULL, sdtimeout, time_stamp_format, toneloudness, and value.
Referenced by load_module(), and reload().
 {
    struct ast_config *cfg;
    const char *value;
    struct ast_flags config_flags = { reload ? CONFIG_FLAG_FILEUNCHANGED : 0 };
    /* Read in the config file */
    cfg = ast_config_load(ALMRCV_CONFIG, config_flags);
    if (!cfg) {
       ast_verb(4, "AlarmReceiver: No config file\n");
       return 0;
    } else if (cfg == CONFIG_STATUS_FILEUNCHANGED) {
       return 1;
    } else if (cfg == CONFIG_STATUS_FILEINVALID) {
       ast_log(LOG_ERROR, "Config file %s is in an invalid format.  Aborting.\n",
          ALMRCV_CONFIG);
       return 0;
    }
    if ((value = ast_variable_retrieve(cfg, "general", "eventcmd")) != NULL) {
       ast_copy_string(event_app, value, sizeof(event_app));
    }
    if ((value = ast_variable_retrieve(cfg, "general", "loudness")) != NULL) {
       toneloudness = atoi(value);
       if (toneloudness < 100) {
          toneloudness = 100;
       } else if (toneloudness > 8192) {
          toneloudness = 8192;
       }
    }
    if ((value = ast_variable_retrieve(cfg, "general", "fdtimeout")) != NULL) {
       fdtimeout = atoi(value);
       if (fdtimeout < 1000) {
          fdtimeout = 1000;
       } else if (fdtimeout > 10000) {
          fdtimeout = 10000;
       }
    }
    if ((value = ast_variable_retrieve(cfg, "general", "sdtimeout")) != NULL) {
       sdtimeout = atoi(value);
       if (sdtimeout < 110) {
          sdtimeout = 110;
       } else if (sdtimeout > 4000) {
          sdtimeout = 4000;
       }
    }
    if ((value = ast_variable_retrieve(cfg, "general", "answait")) != NULL) {
       answait = atoi(value);
       if (answait < 500) {
          answait = 500;
       } else if (answait > 10000) {
          answait = 10000;
       }
    }
    if ((value = ast_variable_retrieve(cfg, "general", "no_group_meta")) != NULL) {
       no_group_meta = ast_true(value);
    }
    if ((value = ast_variable_retrieve(cfg, "general", "logindividualevents")) != NULL) {
       log_individual_events = ast_true(value);
    }
    if ((value = ast_variable_retrieve(cfg, "general", "eventspooldir")) != NULL) {
       ast_copy_string(event_spool_dir, value, sizeof(event_spool_dir));
    }
    if ((value = ast_variable_retrieve(cfg, "general", "timestampformat")) != NULL) {
       ast_copy_string(time_stamp_format, value, sizeof(time_stamp_format));
    }
    if ((value = ast_variable_retrieve(cfg, "general", "db-family")) != NULL) {
       ast_copy_string(db_family, value, sizeof(db_family));
    }
    ast_config_destroy(cfg);
    return 1;
 }
load_module()
static int load_module (void) static
Load the module.
Module loading including tests for configuration or dependencies. This function can return AST_MODULE_LOAD_FAILURE, AST_MODULE_LOAD_DECLINE, or AST_MODULE_LOAD_SUCCESS. If a dependency or environment variable fails tests return AST_MODULE_LOAD_FAILURE. If the module can not load the configuration file or other non-critical problem return AST_MODULE_LOAD_DECLINE. On success return AST_MODULE_LOAD_SUCCESS.
Definition at line 974 of file app_alarmreceiver.c.
References alarmreceiver_exec(), app, AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, ast_register_application_xml, and load_config().
Referenced by reload().
 {
    if (load_config(0)) {
       if (ast_register_application_xml(app, alarmreceiver_exec)) {
          return AST_MODULE_LOAD_DECLINE;
       }
       return AST_MODULE_LOAD_SUCCESS;
    }
    return AST_MODULE_LOAD_DECLINE;
 }
log_events()
static int log_events (struct ast_channel * chan, char * signalling_type, event_node_t * event, int no_checksum) static
Log events if configuration key logindividualevents is enabled or on exit.
Parameters
chan Asterisk Channel
signalling_type Signaling Type
event Event Structure
no_checksum Expecting messages without checksum
Return values
0 success
-1 failure
Definition at line 402 of file app_alarmreceiver.c.
References ast_copy_string(), ast_debug, ast_strlen_zero, ast_verb, event_file, event_spool_dir, event_node::next, NULL, write_event(), and write_metadata().
Referenced by alarmreceiver_exec(), and receive_ademco_event().
 {
    char workstring[sizeof(event_spool_dir) + sizeof(event_file)] = "";
    int fd;
    FILE *logfile;
    event_node_t *elp = event;
    if (!ast_strlen_zero(event_spool_dir)) {
       /* Make a template */
       ast_copy_string(workstring, event_spool_dir, sizeof(workstring));
       strncat(workstring, event_file, sizeof(workstring) - strlen(workstring) - 1);
       /* Make the temporary file */
       fd = mkstemp(workstring);
       if (fd == -1) {
          ast_verb(3, "AlarmReceiver: can't make temporary file\n");
          ast_debug(1, "AlarmReceiver: can't make temporary file\n");
          return -1;
       }
       if ((logfile = fdopen(fd, "w")) == NULL) {
          return -1;
       }
       /* Write the file */
       if (write_metadata(logfile, signalling_type, chan, no_checksum)) {
          fflush(logfile);
          fclose(logfile);
          return -1;
       }
       while ((elp != NULL) && (write_event(logfile, elp) == 0)) {
          elp = elp->next;
       }
       fflush(logfile);
       fclose(logfile);
    }
    return 0;
 }
receive_ademco_event()
static int receive_ademco_event (struct ast_channel * chan, event_node_t ** ehead, char * signalling_type, int * no_checksum) static
Receive Ademco ContactID or other format Data String.
Parameters
chan Asterisk Channel
ehead Pointer to events list
signalling_type Expected signalling type for the message
no_checksum Should we calculate checksum for the message
Return values
0 success
-1 failure
Definition at line 611 of file app_alarmreceiver.c.
References ADEMCO_AUDIO_CALL_NEXT, ademco_check_valid(), ADEMCO_CONTACT_ID, ademco_detect_format(), ADEMCO_EXPRESS_4_1, ADEMCO_EXPRESS_4_2, ademco_verify_checksum(), ast_calloc, ast_channel_lock, ast_channel_unlock, ast_copy_string(), ast_debug, ast_strlen_zero, ast_tvdiff_ms(), ast_tvnow(), ast_verb, call_start_time, event_node::data, database_increment(), log_events(), log_individual_events, event_node::next, NULL, pbx_builtin_getvar_helper(), receive_dtmf_digits(), send_tone_burst(), and UNKNOWN_FORMAT.
Referenced by alarmreceiver_exec().
 {
    int res = 0;
    const char *limit;
    char event[17];
    event_node_t *enew, *elp;
    int got_some_digits = 0;
    int events_received = 0;
    int ack_retries = 0;
    int limit_retries = 0;
    int expected_length = sizeof(event) - 1;
    database_increment("calls-received");
    /* Wait for first event */
    ast_verb(4, "AlarmReceiver: Waiting for first event from panel...\n");
    while (res >= 0) {
       int digits_received = 0;
       res = 0;
       if (log_individual_events) {
          sprintf(signalling_type, "%s", UNKNOWN_FORMAT);
          expected_length = 16;
          *no_checksum = 0;
       }
       if (got_some_digits == 0) {
          /* Send ACK tone sequence */
          ast_verb(4, "AlarmReceiver: Sending 1400Hz 100ms burst (ACK)\n");
          res = send_tone_burst(chan, "1400", 100, 0);
          if (!res) {
             ast_verb(4, "AlarmReceiver: Sending 2300Hz 100ms burst (ACK)\n");
             res = send_tone_burst(chan, "2300", 100, 100);
          }
       }
       if (res) {
          return -1;
       }
       res = receive_dtmf_digits(chan, event, sizeof(event), expected_length, &digits_received);
       if (res < 0) {
          if (events_received == 0) {
             /* Hangup with no events received should be logged in the DB */
             database_increment("no-events-received");
             ast_verb(4, "AlarmReceiver: No events received!\n");
          } else {
             if (ack_retries) {
                database_increment("ack-retries");
                ast_verb(4, "AlarmReceiver: ACK retries during this call: %d\n", ack_retries);
             }
          }
          ast_verb(4, "AlarmReceiver: App exiting...\n");
          break;
       }
       if (!strcmp(signalling_type, UNKNOWN_FORMAT) && digits_received > 5) {
          expected_length = ademco_detect_format(signalling_type, event, no_checksum);
          if (res > 0) {
             if (digits_received == expected_length) {
                res = limit_retries = 0;
             } else if (digits_received == expected_length - 1
                && (!strcmp(signalling_type, ADEMCO_EXPRESS_4_2)
                || !strcmp(signalling_type, ADEMCO_EXPRESS_4_1))) {
                /* ADEMCO EXPRESS without checksum */
                res = limit_retries = 0;
                expected_length--;
                *no_checksum = 1;
                ast_verb(4, "AlarmMonitoring: Skipping checksum for format %s.\n", signalling_type);
                ast_debug(1, "AlarmMonitoring: Skipping checksum for format %s.\n", signalling_type);
             }
          }
       }
       ast_channel_lock(chan);
       limit = pbx_builtin_getvar_helper(chan, "ALARMRECEIVER_CALL_LIMIT");
       if (!ast_strlen_zero(limit)) {
          if (ast_tvdiff_ms(ast_tvnow(), call_start_time) > atoi(limit)) {
             ast_channel_unlock(chan);
             return -1;
          }
       }
       limit = pbx_builtin_getvar_helper(chan, "ALARMRECEIVER_RETRIES_LIMIT");
       ast_channel_unlock(chan);
       if (!ast_strlen_zero(limit)) {
          if (limit_retries + 1 >= atoi(limit)) {
             return -1;
          }
       }
       if (res) {
          /* Didn't get all of the digits */
          ast_verb(2, "AlarmReceiver: Incomplete string: %s, trying again...\n", event);
          limit_retries++;
          if (!events_received && strcmp(signalling_type, UNKNOWN_FORMAT))
          {
             sprintf(signalling_type, "%s", UNKNOWN_FORMAT);
             expected_length = sizeof(event) - 1;
          }
          if (!got_some_digits) {
             got_some_digits = (!ast_strlen_zero(event)) ? 1 : 0;
             ack_retries++;
          }
          continue;
       }
       got_some_digits = 1;
       ast_verb(2, "AlarmReceiver: Received Event %s\n", event);
       ast_debug(1, "AlarmReceiver: Received event: %s\n", event);
       /* Calculate checksum */
       if (!(*no_checksum) && ademco_verify_checksum(event, expected_length)) {
          database_increment("checksum-errors");
          ast_verb(2, "AlarmReceiver: Nonzero checksum\n");
          ast_debug(1, "AlarmReceiver: Nonzero checksum\n");
          continue;
       }
       /* Check the message type for correctness */
       if (ademco_check_valid(signalling_type, event)) {
          database_increment("format-errors");
          ast_verb(2, "AlarmReceiver: Wrong message type\n");
          ast_debug(1, "AlarmReceiver: Wrong message type\n");
          continue;
       }
       events_received++;
       /* Queue the Event */
       if (!(enew = ast_calloc(1, sizeof(*enew)))) {
          return -1;
       }
       enew->next = NULL;
       ast_copy_string(enew->data, event, sizeof(enew->data));
       /* Insert event onto end of list */
       if (*ehead == NULL) {
          *ehead = enew;
       } else {
          for (elp = *ehead; elp->next != NULL; elp = elp->next) {
             ;
          }
          elp->next = enew;
       }
       /* Let the user have the option of logging the single event before sending the kissoff tone */
       if (log_individual_events && log_events(chan, signalling_type, enew, *no_checksum)) {
          return -1;
       }
       /* Send the kissoff tone (1400 Hz, 900 ms, after 200ms delay) */
       if (send_tone_burst(chan, "1400", 900, 200)) {
          return -1;
       }
       /* If audio call follows, exit alarm receiver app */
       if (!strcmp(signalling_type, ADEMCO_CONTACT_ID)
          && !strncmp(event + 7, ADEMCO_AUDIO_CALL_NEXT, 3)) {
          ast_verb(4, "AlarmReceiver: App exiting... Audio call next!\n");
          return 0;
       }
    }
    return res;
 }
receive_dtmf_digits()
static int receive_dtmf_digits (struct ast_channel * chan, char * digit_string, int buf_size, int expected, int * received) static
Receive a fixed length DTMF string.
Note
Doesn't give preferential treatment to any digit,
allow different timeout values for the first and all subsequent digits
Parameters
chan Asterisk Channel
digit_string Digits String
buf_size The size of the Digits String buffer
expected Digits expected for this message type
received Pointer to number of digits received so far
Return values
0 if all digits were successfully received
1 if a timeout occurred
-1 if the caller hung up or on channel errors
Definition at line 253 of file app_alarmreceiver.c.
References ast_channel_hangupcause_set(), ast_channel_name(), AST_CONTROL_HANGUP, ast_debug, AST_FRAME_CONTROL, AST_FRAME_DTMF, ast_frfree, ast_read(), ast_tvdiff_ms(), ast_tvnow(), ast_verb, ast_waitfor(), ast_frame::data, fdtimeout, ast_frame::frametype, ast_frame_subclass::integer, NULL, sdtimeout, ast_frame::subclass, and ast_frame::uint32.
Referenced by receive_ademco_event().
 {
    int rtn = 0;
    int r;
    struct ast_frame *f;
    struct timeval lastdigittime;
    lastdigittime = ast_tvnow();
    while (*received < expected && *received < buf_size - 1) {
       /* If timed out, leave */
       if (ast_tvdiff_ms(ast_tvnow(), lastdigittime) > ((*received > 0) ? sdtimeout : fdtimeout)) {
          ast_verb(4, "AlarmReceiver: DTMF Digit Timeout on %s\n", ast_channel_name(chan));
          ast_debug(1, "AlarmReceiver: DTMF timeout on chan %s\n", ast_channel_name(chan));
          rtn = 1;
          break;
       }
       if ((r = ast_waitfor(chan, -1)) < 0) {
          ast_debug(1, "Waitfor returned %d\n", r);
          continue;
       }
       if ((f = ast_read(chan)) == NULL) {
          rtn = -1;
          break;
       }
       /* If they hung up, leave */
       if ((f->frametype == AST_FRAME_CONTROL)
          && (f->subclass.integer == AST_CONTROL_HANGUP)) {
          if (f->data.uint32) {
             ast_channel_hangupcause_set(chan, f->data.uint32);
          }
          ast_frfree(f);
          rtn = -1;
          break;
       }
       /* If not DTMF, just do it again */
       if (f->frametype != AST_FRAME_DTMF) {
          ast_frfree(f);
          continue;
       }
       /* Save digit */
       digit_string[(*received)++] = f->subclass.integer;
       ast_frfree(f);
       lastdigittime = ast_tvnow();
    }
    /* Null terminate the end of the digit_string */
    digit_string[*received] = '\0';
    return rtn;
 }
reload()
static int reload (void) static
Definition at line 986 of file app_alarmreceiver.c.
References AST_MODFLAG_DEFAULT, AST_MODULE_INFO(), AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, AST_MODULE_SUPPORT_EXTENDED, ASTERISK_GPL_KEY, load_config(), load_module(), and unload_module().
 {
    if (load_config(1)) {
       return AST_MODULE_LOAD_SUCCESS;
    }
    return AST_MODULE_LOAD_DECLINE;
 }
send_tone_burst()
static int send_tone_burst (struct ast_channel * chan, const char * tone_freq, int tone_duration, int delay) static
Send a single tone burst for a specified duration and frequency.
Since
11.0
Parameters
chan Asterisk Channel
tone_freq Frequency of the tone to send
tone_duration Tone duration in ms
delay Delay before sending the tone
Return values
0 success
-1 failure
Definition at line 496 of file app_alarmreceiver.c.
References ast_playtones_start(), ast_playtones_stop(), ast_safe_sleep(), and toneloudness.
Referenced by receive_ademco_event().
 {
    if (delay && ast_safe_sleep(chan, delay)) {
       return -1;
    }
    if (ast_playtones_start(chan, toneloudness, tone_freq, 0)) {
       return -1;
    }
    if (ast_safe_sleep(chan, tone_duration)) {
       return -1;
    }
    ast_playtones_stop(chan);
    return 0;
 }
unload_module()
static int unload_module (void) static
Unregister Alarm Receiver App.
Return values
0 success
-1 failure
Definition at line 959 of file app_alarmreceiver.c.
References app, and ast_unregister_application().
Referenced by reload().
 {
    return ast_unregister_application(app);
 }
write_event()
static int write_event (FILE * logfile, event_node_t * event) static
Log a single event.
Parameters
logfile Log File Pointer
event Event Structure
Return values
0 success
-1 failure
Definition at line 382 of file app_alarmreceiver.c.
References event_node::data, and no_group_meta.
Referenced by log_events().
 {
    if (fprintf(logfile, "%s%s\n", no_group_meta ? "event=" : "", event->data) < 0) {
       return -1;
    }
    return 0;
 }
write_metadata()
static int write_metadata (FILE * logfile, char * signalling_type, struct ast_channel * chan, int no_checksum) static
Write metadata to log file.
Parameters
logfile Log File Pointer
signalling_type Signaling Type
chan Asterisk Channel
no_checksum Expecting messages without checksum
Return values
0 success
-1 failure
Definition at line 321 of file app_alarmreceiver.c.
References ast_channel_caller(), ast_copy_string(), ast_debug, ast_localtime(), ast_shrink_phone_number(), ast_strftime(), ast_strlen_zero, ast_tvnow(), ast_verb, ast_bridge::name, no_group_meta, NULL, S_COR, and time_stamp_format.
Referenced by log_events().
 {
    struct timeval t;
    struct ast_tm now;
    char *cl;
    char *cn;
    char workstring[80];
    char timestamp[80];
    /* Extract the caller ID location */
    ast_copy_string(workstring,
       S_COR(ast_channel_caller(chan)->id.number.valid,
       ast_channel_caller(chan)->id.number.str, ""), sizeof(workstring));
    ast_shrink_phone_number(workstring);
    if (ast_strlen_zero(workstring)) {
       cl = "<unknown>";
    } else {
       cl = workstring;
    }
    cn = S_COR(ast_channel_caller(chan)->id.name.valid,
       ast_channel_caller(chan)->id.name.str, "<unknown>");
    /* Get the current time */
    t = ast_tvnow();
    ast_localtime(&t, &now, NULL);
    /* Format the time */
    ast_strftime(timestamp, sizeof(timestamp), time_stamp_format, &now);
    if (no_group_meta && fprintf(logfile, "PROTOCOL=%s\n"
          "CHECKSUM=%s\n"
          "CALLINGFROM=%s\n"
          "CALLERNAME=%s\n"
          "TIMESTAMP=%s\n\n",
          signalling_type, (!no_checksum) ? "yes" : "no", cl, cn, timestamp) > -1) {
       return 0;
    } else if (fprintf(logfile, "\n\n[metadata]\n\n"
          "PROTOCOL=%s\n"
          "CHECKSUM=%s\n"
          "CALLINGFROM=%s\n"
          "CALLERNAME=%s\n"
          "TIMESTAMP=%s\n\n"
          "[events]\n\n",
          signalling_type, (!no_checksum) ? "yes" : "no", cl, cn, timestamp) > -1) {
       return 0;
    }
    ast_verb(3, "AlarmReceiver: can't write metadata\n");
    ast_debug(1, "AlarmReceiver: can't write metadata\n");
    return -1;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_DEFAULT , .description = "Alarm Receiver for Asterisk" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_EXTENDED, .load = load_module, .unload = unload_module, .reload = reload, } static
Definition at line 1000 of file app_alarmreceiver.c.
answait
int answait = 1250 static
Definition at line 184 of file app_alarmreceiver.c.
Referenced by alarmreceiver_exec(), and load_config().
app
const char app[] = "AlarmReceiver" static
Definition at line 146 of file app_alarmreceiver.c.
Referenced by load_module(), and unload_module().
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 1000 of file app_alarmreceiver.c.
call_start_time
struct timeval call_start_time
Definition at line 144 of file app_alarmreceiver.c.
Referenced by alarmreceiver_exec(), and receive_ademco_event().
db_family
char db_family[128] = {'\0'} static
Definition at line 190 of file app_alarmreceiver.c.
Referenced by database_increment(), and load_config().
digit
char digit
Examples:
/usr/src/asterisk-18.5.0/main/app.c.
Definition at line 131 of file app_alarmreceiver.c.
Referenced by __ast_pbx_run(), __ast_read(), action_atxfer(), action_cancel_atxfer(), action_playback_and_continue(), ademco_verify_checksum(), agent_alert(), ast_dsp_process(), ast_rtp_dtmf_begin(), ast_translate_number_ka(), ast_unreal_digit_begin(), ast_unreal_digit_end(), attended_transfer_exec(), bridge_channel_feature_digit_add(), chan_pjsip_pvt_dtor(), channel_dtmf_begin_cb(), channel_dtmf_end_cb(), collect_digits(), compare(), controlplayback_exec(), dahdi_chan_conf_default(), dahdi_digit_begin(), dial_exec_full(), dictate_exec(), directory_exec(), do_directory(), dtmf_end_to_json(), dtmf_stream(), handle_clear_alarms(), handle_incoming_request(), handle_keypad_button_message(), info_dtmf_data_alloc(), jb_debug_output(), keypad_cfg_read(), manager_play_dtmf(), manager_play_mf(), mgcp_senddigit_end(), misdn_digit_end(), moh_digit_match(), morsecode_exec(), ooh323_digit_begin(), phone_call(), phone_check_exception(), phone_exception(), play_file(), send_dtmf_begin_event(), send_dtmf_end_event(), store_digit(), test_dtmf_amplitude_sweep(), test_dtmf_twist_sweep(), try_calling(), unistim_do_senddigit(), and valid_exit().
digits_mapping
struct { ... } digits_mapping[]
Initial value:
= { {'0', 10}, {'1', 1} , {'2', 2}, {'3', 3}, {'4', 4}, {'5', 5},
   {'6', 6}, {'7', 7}, {'8', 8}, {'9', 9}, {'*', 11}, {'#', 12},
   {'A', 13}, {'B', 14}, {'C', 15} }
Referenced by ademco_verify_checksum().
event_app
char event_app[128] = {'\0'} static
Definition at line 189 of file app_alarmreceiver.c.
Referenced by alarmreceiver_exec(), and load_config().
event_file
char event_file[14] = "/event-XXXXXX" static
Definition at line 194 of file app_alarmreceiver.c.
Referenced by log_events().
event_spool_dir
char event_spool_dir[128] = {'\0'} static
Definition at line 188 of file app_alarmreceiver.c.
Referenced by load_config(), and log_events().
fdtimeout
int fdtimeout = 2000 static
Definition at line 182 of file app_alarmreceiver.c.
Referenced by acf_faxopt_write(), load_config(), and receive_dtmf_digits().
log_individual_events
int log_individual_events = 0 static
Definition at line 186 of file app_alarmreceiver.c.
Referenced by alarmreceiver_exec(), load_config(), and receive_ademco_event().
no_group_meta
int no_group_meta = 0 static
Definition at line 187 of file app_alarmreceiver.c.
Referenced by load_config(), write_event(), and write_metadata().
sdtimeout
int sdtimeout = 200 static
Definition at line 183 of file app_alarmreceiver.c.
Referenced by load_config(), and receive_dtmf_digits().
time_stamp_format
char time_stamp_format[128] = {"%a %b %d, %Y @ %H:%M:%S %Z"} static
Definition at line 191 of file app_alarmreceiver.c.
Referenced by load_config(), and write_metadata().
toneloudness
int toneloudness = 4096 static
Definition at line 185 of file app_alarmreceiver.c.
Referenced by load_config(), and send_tone_burst().
weight
char weight
Definition at line 132 of file app_alarmreceiver.c.
Referenced by cache_lookup_internal(), dns_srv_alloc(), dns_srv_sort(), dundi_lookup_thread(), dundi_show_cache(), dundi_show_mappings(), precache_trans(), and srv_result_read().