Asterisk - The Open Source Telephony Project: parking_devicestate.c File Reference
parking_devicestate.c File Reference
Call Parking Device State Management.
#include "asterisk.h"
#include "asterisk/logger.h"
#include "res_parking.h"
#include "asterisk/devicestate.h"
Data Structures
struct parking_lot_extension_inuse_search
Functions
int load_parking_devstate (void)
Register Parking devstate handler.
static enum ast_device_state metermaidstate (const char *data)
static int parking_lot_search_context_extension_inuse (void *obj, void *arg, int flags)
void parking_notify_metermaids (int exten, const char *context, enum ast_device_state state)
Notify metermaids that we've changed an extension.
static int retrieve_parked_user_targeted (void *obj, void *arg, int flags)
void unload_parking_devstate (void)
Unregister Parking devstate handler.
Detailed Description
Call Parking Device State Management.
Author
Jonathan Rose jrose.nosp@m.@dig.nosp@m.ium.c.nosp@m.om
Definition in file parking_devicestate.c.
Function Documentation
load_parking_devstate()
int load_parking_devstate (void)
Register Parking devstate handler.
Since
12.0.0
Definition at line 121 of file parking_devicestate.c.
References ast_devstate_prov_add(), and metermaidstate().
Referenced by load_module().
 {
    return ast_devstate_prov_add("Park", metermaidstate);
 }
metermaidstate()
static enum ast_device_state metermaidstate (const char * data) static
Definition at line 77 of file parking_devicestate.c.
References ao2_callback, ao2_cleanup, ast_debug, AST_DEVICE_INUSE, AST_DEVICE_INVALID, AST_DEVICE_NOT_INUSE, ast_strdupa, ast_strlen_zero, parking_lot_extension_inuse_search::context, parking_lot_extension_inuse_search::exten, get_parking_lot_container(), NULL, parking_lot_search_context_extension_inuse(), RAII_VAR, and strsep().
Referenced by load_parking_devstate().
 {
    struct ao2_container *global_lots = get_parking_lot_container();
    RAII_VAR(struct parking_lot *, lot, NULL, ao2_cleanup);
    char *context;
    char *exten;
    struct parking_lot_extension_inuse_search search = {};
    context = ast_strdupa(data);
    exten = strsep(&context, "@");
    if (ast_strlen_zero(context) || ast_strlen_zero(exten)) {
       return AST_DEVICE_INVALID;
    }
    search.context = context;
    if (sscanf(exten, "%d", &search.exten) != 1) {
       return AST_DEVICE_INVALID;
    }
    ast_debug(4, "Checking state of exten %d in context %s\n", search.exten, context);
    lot = ao2_callback(global_lots, 0, parking_lot_search_context_extension_inuse, &data);
    if (!lot) {
       return AST_DEVICE_NOT_INUSE;
    }
    return AST_DEVICE_INUSE;
 }
parking_lot_search_context_extension_inuse()
static int parking_lot_search_context_extension_inuse (void * obj, void * arg, int flags) static
Definition at line 47 of file parking_devicestate.c.
References ao2_callback, ao2_cleanup, ao2_lock, ao2_unlock, parking_lot::cfg, CMP_MATCH, parking_lot_extension_inuse_search::context, parking_lot_extension_inuse_search::exten, NULL, PARK_UNSET, parking_lot::parked_users, parking_lot_cfg::parking_con, parking_lot_cfg::parking_start, parking_lot_cfg::parking_stop, RAII_VAR, and retrieve_parked_user_targeted().
Referenced by metermaidstate().
 {
    struct parking_lot *lot = obj;
    struct parking_lot_extension_inuse_search *search = arg;
    RAII_VAR(struct parked_user *, user, NULL, ao2_cleanup);
    if (strcmp(lot->cfg->parking_con, search->context)) {
       return 0;
    }
    if ((search->exten < lot->cfg->parking_start) || (search->exten > lot->cfg->parking_stop)) {
       return 0;
    }
    user = ao2_callback(lot->parked_users, 0, retrieve_parked_user_targeted, &search->exten);
    if (!user) {
       return 0;
    }
    ao2_lock(user);
    if (user->resolution != PARK_UNSET) {
       /* The parked user isn't in an answerable state. */
       ao2_unlock(user);
       return 0;
    }
    ao2_unlock(user);
    return CMP_MATCH;
 }
parking_notify_metermaids()
void parking_notify_metermaids (int exten, const char * context, enum ast_device_state state)
Notify metermaids that we've changed an extension.
Since
12.0.0
Parameters
exten Extension of the call parked/unparked
context Context of the call parked/unparked
state new device state
Definition at line 108 of file parking_devicestate.c.
References ast_debug, ast_devstate2str(), AST_DEVSTATE_CACHABLE, and ast_devstate_changed().
Referenced by bridge_parking_pull(), and bridge_parking_push().
 {
    ast_debug(4, "Notification of state change to metermaids %d@%s\n to state '%s'\n",
       exten, context, ast_devstate2str(state));
    ast_devstate_changed(state, AST_DEVSTATE_CACHABLE, "park:%d@%s", exten, context);
 }
retrieve_parked_user_targeted()
static int retrieve_parked_user_targeted (void * obj, void * arg, int flags) static
Definition at line 36 of file parking_devicestate.c.
References CMP_MATCH, and parked_user::parking_space.
Referenced by parking_lot_search_context_extension_inuse().
 {
    int *target = arg;
    struct parked_user *user = obj;
    if (user->parking_space == *target) {
       return CMP_MATCH;
    }
    return 0;
 }
unload_parking_devstate()
void unload_parking_devstate (void)
Unregister Parking devstate handler.
Since
12.0.0
Definition at line 116 of file parking_devicestate.c.
References ast_devstate_prov_del().
Referenced by unload_module().
 {
    ast_devstate_prov_del("Park");
 }