Asterisk - The Open Source Telephony Project: conf_config_parser.c File Reference
conf_config_parser.c File Reference
ConfBridge config parser.
#include "asterisk.h"
#include "asterisk/logger.h"
#include "asterisk/config.h"
#include "asterisk/config_options.h"
#include "include/confbridge.h"
#include "asterisk/astobj2.h"
#include "asterisk/cli.h"
#include "asterisk/bridge_features.h"
#include "asterisk/stringfields.h"
#include "asterisk/pbx.h"
Data Structures
struct confbridge_cfg
struct dtmf_menu_hook_pvt
struct func_confbridge_data
Functions
static int add_action_to_menu_entry (struct conf_menu_entry *menu_entry, enum conf_menu_action_id id, char *databuf)
static int add_menu_entry (struct conf_menu *menu, const char *dtmf, const char *action_names)
static int announce_user_count_all_handler (const struct aco_option *opt, struct ast_variable *var, void *obj)
static AO2_GLOBAL_OBJ_STATIC (cfg_handle)
static int apply_menu_to_user (struct confbridge_user *user, struct conf_menu *menu)
static int bridge_cmp_cb (void *obj, void *arg, int flags)
static int bridge_hash_cb (const void *obj, const int flags)
static void * bridge_profile_alloc (const char *category)
static void bridge_profile_destructor (void *obj)
static void * bridge_profile_find (struct ao2_container *container, const char *category)
static struct bridge_profile_sounds * bridge_profile_sounds_alloc (void)
static void bridge_profile_sounds_destroy_cb (void *obj)
static int bridge_template_handler (const struct aco_option *opt, struct ast_variable *var, void *obj)
static char * complete_bridge_profile_name (const char *line, const char *word, int pos, int state)
static char * complete_menu_name (const char *line, const char *word, int pos, int state)
static char * complete_user_profile_name (const char *line, const char *word, int pos, int state)
void conf_bridge_profile_copy (struct bridge_profile *dst, struct bridge_profile *src)
copies a bridge profile
void conf_bridge_profile_destroy (struct bridge_profile *b_profile)
Destroy a bridge profile found by 'conf_find_bridge_profile'.
void conf_destroy_config (void)
destroy the information loaded from the confbridge.conf file
const struct bridge_profile * conf_find_bridge_profile (struct ast_channel *chan, const char *bridge_profile_name, struct bridge_profile *result)
Find a bridge profile given a bridge profile's name and store that profile in result structure.
int conf_find_menu_entry_by_sequence (const char *dtmf_sequence, struct conf_menu *menu, struct conf_menu_entry *result)
Finds a menu_entry in a menu structure matched by DTMF sequence.
const struct user_profile * conf_find_user_profile (struct ast_channel *chan, const char *user_profile_name, struct user_profile *result)
find a user profile given a user profile's name and store that profile in result structure.
int conf_load_config (void)
load confbridge.conf file
void conf_menu_entry_destroy (struct conf_menu_entry *menu_entry)
Destroys and frees all the actions stored in a menu_entry structure.
static int conf_menu_profile_copy (struct conf_menu *dst, struct conf_menu *src)
int conf_reload_config (void)
reload confbridge.conf file
int conf_set_menu_to_user (struct ast_channel *chan, struct confbridge_user *user, const char *menu_profile_name)
find a menu profile given a menu profile's name and apply the menu in DTMF hooks.
static void conf_user_profile_copy (struct user_profile *dst, struct user_profile *src)
static void * confbridge_cfg_alloc (void)
static void confbridge_cfg_destructor (void *obj)
CONFIG_INFO_STANDARD (cfg_info, cfg_handle, confbridge_cfg_alloc,.files=ACO_FILES(&confbridge_conf),.pre_apply_config=verify_default_profiles,)
static int copy_menu_entry (struct conf_menu_entry *dst, struct conf_menu_entry *src)
static void func_confbridge_data_destructor (struct func_confbridge_data *b_data)
static void func_confbridge_destroy_cb (void *data)
int func_confbridge_helper (struct ast_channel *chan, const char *cmd, char *data, const char *value)
static char * handle_cli_confbridge_show_bridge_profile (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static char * handle_cli_confbridge_show_bridge_profiles (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static char * handle_cli_confbridge_show_menu (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static char * handle_cli_confbridge_show_menus (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static char * handle_cli_confbridge_show_user_profile (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static char * handle_cli_confbridge_show_user_profiles (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static void * menu_alloc (const char *category)
static int menu_cmp_cb (void *obj, void *arg, int flags)
static void menu_destructor (void *obj)
static void * menu_find (struct ao2_container *container, const char *category)
static int menu_hash_cb (const void *obj, const int flags)
static int menu_hook_callback (struct ast_bridge_channel *bridge_channel, void *hook_pvt)
static void menu_hook_destroy (void *hook_pvt)
static int menu_option_handler (const struct aco_option *opt, struct ast_variable *var, void *obj)
static int menu_template_handler (const struct aco_option *opt, struct ast_variable *var, void *obj)
static int mix_interval_handler (const struct aco_option *opt, struct ast_variable *var, void *obj)
static int remb_behavior_handler (const struct aco_option *opt, struct ast_variable *var, void *obj)
static int set_sound (const char *sound_name, const char *sound_file, struct bridge_profile *b_profile)
static int sound_option_handler (const struct aco_option *opt, struct ast_variable *var, void *obj)
static int user_cmp_cb (void *obj, void *arg, int flags)
static int user_hash_cb (const void *obj, const int flags)
static void * user_profile_alloc (const char *category)
static void user_profile_destructor (void *obj)
static void * user_profile_find (struct ao2_container *container, const char *category)
static int user_template_handler (const struct aco_option *opt, struct ast_variable *var, void *obj)
static int verify_default_profiles (void)
static int video_mode_handler (const struct aco_option *opt, struct ast_variable *var, void *obj)
Variables
static struct aco_type bridge_type
static struct aco_type * bridge_types [] = ACO_TYPES(&bridge_type)
static struct ast_cli_entry cli_confbridge_parser []
static struct aco_file confbridge_conf
static const struct ast_datastore_info confbridge_datastore
static struct aco_type general_type
static struct aco_type menu_type
static struct aco_type * menu_types [] = ACO_TYPES(&menu_type)
static struct aco_type user_type
static struct aco_type * user_types [] = ACO_TYPES(&user_type)
Detailed Description
ConfBridge config parser.
Author
David Vossel dvoss.nosp@m.el@d.nosp@m.igium.nosp@m..com
Definition in file conf_config_parser.c.
Function Documentation
add_action_to_menu_entry()
static int add_action_to_menu_entry (struct conf_menu_entry * menu_entry, enum conf_menu_action_id id, char * databuf) static
Definition at line 1255 of file conf_config_parser.c.
References conf_menu_entry::actions, args, AST_APP_ARG, ast_calloc, ast_copy_string(), AST_DECLARE_APP_ARGS, ast_free, AST_LIST_INSERT_TAIL, AST_STANDARD_APP_ARGS, ast_strlen_zero, context, conf_menu_action::data, conf_menu_action::dialplan_args, exten, conf_menu_action::id, id, MENU_ACTION_ADMIN_KICK_LAST, MENU_ACTION_ADMIN_TOGGLE_LOCK, MENU_ACTION_ADMIN_TOGGLE_MUTE_PARTICIPANTS, MENU_ACTION_DECREASE_LISTENING, MENU_ACTION_DECREASE_TALKING, MENU_ACTION_DIALPLAN_EXEC, MENU_ACTION_INCREASE_LISTENING, MENU_ACTION_INCREASE_TALKING, MENU_ACTION_LEAVE, MENU_ACTION_NOOP, MENU_ACTION_PARTICIPANT_COUNT, MENU_ACTION_PLAYBACK, MENU_ACTION_PLAYBACK_AND_CONTINUE, MENU_ACTION_RELEASE_SINGLE_VIDEO_SRC, MENU_ACTION_RESET_LISTENING, MENU_ACTION_RESET_TALKING, MENU_ACTION_SET_SINGLE_VIDEO_SRC, MENU_ACTION_TOGGLE_BINAURAL, MENU_ACTION_TOGGLE_MUTE, conf_menu_action::playback_file, and priority.
Referenced by add_menu_entry().
 {
    struct conf_menu_action *menu_action = ast_calloc(1, sizeof(*menu_action));
    if (!menu_action) {
       return -1;
    }
    menu_action->id = id;
    switch (id) {
    case MENU_ACTION_NOOP:
    case MENU_ACTION_TOGGLE_MUTE:
    case MENU_ACTION_TOGGLE_BINAURAL:
    case MENU_ACTION_INCREASE_LISTENING:
    case MENU_ACTION_DECREASE_LISTENING:
    case MENU_ACTION_INCREASE_TALKING:
    case MENU_ACTION_DECREASE_TALKING:
    case MENU_ACTION_RESET_LISTENING:
    case MENU_ACTION_RESET_TALKING:
    case MENU_ACTION_ADMIN_TOGGLE_LOCK:
    case MENU_ACTION_ADMIN_TOGGLE_MUTE_PARTICIPANTS:
    case MENU_ACTION_PARTICIPANT_COUNT:
    case MENU_ACTION_ADMIN_KICK_LAST:
    case MENU_ACTION_LEAVE:
    case MENU_ACTION_SET_SINGLE_VIDEO_SRC:
    case MENU_ACTION_RELEASE_SINGLE_VIDEO_SRC:
       break;
    case MENU_ACTION_PLAYBACK:
    case MENU_ACTION_PLAYBACK_AND_CONTINUE:
       if (!(ast_strlen_zero(databuf))) {
          ast_copy_string(menu_action->data.playback_file, databuf, sizeof(menu_action->data.playback_file));
       } else {
          ast_free(menu_action);
          return -1;
       }
       break;
    case MENU_ACTION_DIALPLAN_EXEC:
       if (!(ast_strlen_zero(databuf))) {
          AST_DECLARE_APP_ARGS(args,
             AST_APP_ARG(context);
             AST_APP_ARG(exten);
             AST_APP_ARG(priority);
          );
          AST_STANDARD_APP_ARGS(args, databuf);
          if (!ast_strlen_zero(args.context)) {
             ast_copy_string(menu_action->data.dialplan_args.context,
                args.context,
                sizeof(menu_action->data.dialplan_args.context));
          }
          if (!ast_strlen_zero(args.exten)) {
             ast_copy_string(menu_action->data.dialplan_args.exten,
                args.exten,
                sizeof(menu_action->data.dialplan_args.exten));
          }
          menu_action->data.dialplan_args.priority = 1; /* 1 by default */
          if (!ast_strlen_zero(args.priority) &&
             (sscanf(args.priority, "%30d", &menu_action->data.dialplan_args.priority) != 1)) {
             /* invalid priority */
             ast_free(menu_action);
             return -1;
          }
       } else {
          ast_free(menu_action);
          return -1;
       }
    };
    AST_LIST_INSERT_TAIL(&menu_entry->actions, menu_action, action);
    return 0;
 }
add_menu_entry()
static int add_menu_entry (struct conf_menu * menu, const char * dtmf, const char * action_names) static
Definition at line 1327 of file conf_config_parser.c.
References conf_menu_entry::actions, add_action_to_menu_entry(), ast_calloc, ast_copy_string(), ast_free, AST_LIST_INSERT_TAIL, AST_LIST_REMOVE_CURRENT, AST_LIST_REMOVE_HEAD, AST_LIST_TRAVERSE_SAFE_BEGIN, AST_LIST_TRAVERSE_SAFE_END, ast_strdupa, ast_strip(), ast_strlen_zero, buf, conf_menu_entry::dtmf, conf_menu::entries, MENU_ACTION_ADMIN_KICK_LAST, MENU_ACTION_ADMIN_TOGGLE_LOCK, MENU_ACTION_ADMIN_TOGGLE_MUTE_PARTICIPANTS, MENU_ACTION_DECREASE_LISTENING, MENU_ACTION_DECREASE_TALKING, MENU_ACTION_DIALPLAN_EXEC, MENU_ACTION_INCREASE_LISTENING, MENU_ACTION_INCREASE_TALKING, MENU_ACTION_LEAVE, MENU_ACTION_NOOP, MENU_ACTION_PARTICIPANT_COUNT, MENU_ACTION_PLAYBACK, MENU_ACTION_PLAYBACK_AND_CONTINUE, MENU_ACTION_RELEASE_SINGLE_VIDEO_SRC, MENU_ACTION_RESET_LISTENING, MENU_ACTION_RESET_TALKING, MENU_ACTION_SET_SINGLE_VIDEO_SRC, MENU_ACTION_TOGGLE_BINAURAL, MENU_ACTION_TOGGLE_MUTE, NULL, PATH_MAX, strsep(), and tmp().
Referenced by menu_option_handler().
 {
    struct conf_menu_entry *menu_entry = NULL, *cur = NULL;
    int res = 0;
    char *tmp_action_names = ast_strdupa(action_names);
    char *action = NULL;
    char *action_args;
    char *tmp;
    char buf[PATH_MAX];
    char *delimiter = ",";
    if (!(menu_entry = ast_calloc(1, sizeof(*menu_entry)))) {
       return -1;
    }
    for (;;) {
       char *comma;
       char *startbrace;
       char *endbrace;
       unsigned int action_len;
       if (ast_strlen_zero(tmp_action_names)) {
          break;
       }
       startbrace = strchr(tmp_action_names, '(');
       endbrace = strchr(tmp_action_names, ')');
       comma = strchr(tmp_action_names, ',');
       /* If the next action has brackets with comma delimited arguments in it,
        * make the delimeter ')' instead of a comma to preserve the argments */
       if (startbrace && endbrace && comma && (comma > startbrace && comma < endbrace)) {
          delimiter = ")";
       } else {
          delimiter = ",";
       }
       if (!(action = strsep(&tmp_action_names, delimiter))) {
          break;
       }
       action = ast_strip(action);
       if (ast_strlen_zero(action)) {
          continue;
       }
       action_len = strlen(action);
       ast_copy_string(menu_entry->dtmf, dtmf, sizeof(menu_entry->dtmf));
       if (!strcasecmp(action, "toggle_mute")) {
          res |= add_action_to_menu_entry(menu_entry, MENU_ACTION_TOGGLE_MUTE, NULL);
       } else if (!strcasecmp(action, "toggle_binaural")) {
          res |= add_action_to_menu_entry(menu_entry, MENU_ACTION_TOGGLE_BINAURAL, NULL);
       } else if (!strcasecmp(action, "no_op")) {
          res |= add_action_to_menu_entry(menu_entry, MENU_ACTION_NOOP, NULL);
       } else if (!strcasecmp(action, "increase_listening_volume")) {
          res |= add_action_to_menu_entry(menu_entry, MENU_ACTION_INCREASE_LISTENING, NULL);
       } else if (!strcasecmp(action, "decrease_listening_volume")) {
          res |= add_action_to_menu_entry(menu_entry, MENU_ACTION_DECREASE_LISTENING, NULL);
       } else if (!strcasecmp(action, "increase_talking_volume")) {
          res |= add_action_to_menu_entry(menu_entry, MENU_ACTION_INCREASE_TALKING, NULL);
       } else if (!strcasecmp(action, "reset_listening_volume")) {
          res |= add_action_to_menu_entry(menu_entry, MENU_ACTION_RESET_LISTENING, NULL);
       } else if (!strcasecmp(action, "reset_talking_volume")) {
          res |= add_action_to_menu_entry(menu_entry, MENU_ACTION_RESET_TALKING, NULL);
       } else if (!strcasecmp(action, "decrease_talking_volume")) {
          res |= add_action_to_menu_entry(menu_entry, MENU_ACTION_DECREASE_TALKING, NULL);
       } else if (!strcasecmp(action, "admin_toggle_conference_lock")) {
          res |= add_action_to_menu_entry(menu_entry, MENU_ACTION_ADMIN_TOGGLE_LOCK, NULL);
       } else if (!strcasecmp(action, "admin_toggle_mute_participants")) {
          res |= add_action_to_menu_entry(menu_entry, MENU_ACTION_ADMIN_TOGGLE_MUTE_PARTICIPANTS, NULL);
       } else if (!strcasecmp(action, "participant_count")) {
          res |= add_action_to_menu_entry(menu_entry, MENU_ACTION_PARTICIPANT_COUNT, NULL);
       } else if (!strcasecmp(action, "admin_kick_last")) {
          res |= add_action_to_menu_entry(menu_entry, MENU_ACTION_ADMIN_KICK_LAST, NULL);
       } else if (!strcasecmp(action, "leave_conference")) {
          res |= add_action_to_menu_entry(menu_entry, MENU_ACTION_LEAVE, NULL);
       } else if (!strcasecmp(action, "set_as_single_video_src")) {
          res |= add_action_to_menu_entry(menu_entry, MENU_ACTION_SET_SINGLE_VIDEO_SRC, NULL);
       } else if (!strcasecmp(action, "release_as_single_video_src")) {
          res |= add_action_to_menu_entry(menu_entry, MENU_ACTION_RELEASE_SINGLE_VIDEO_SRC, NULL);
       } else if (!strncasecmp(action, "dialplan_exec(", 14)) {
          ast_copy_string(buf, action, sizeof(buf));
          action_args = buf;
          if ((action_args = strchr(action, '('))) {
             action_args++;
          }
          /* it is possible that this argument may or may not
           * have a closing brace at this point, it all depends on if
           * comma delimited arguments were provided */
          if ((tmp = strchr(action, ')'))) {
             *tmp = '\0';
          }
          res |= add_action_to_menu_entry(menu_entry, MENU_ACTION_DIALPLAN_EXEC, action_args);
       } else if (action_len >= 21 && !strncasecmp(action, "playback_and_continue(", 22)) {
          ast_copy_string(buf, action, sizeof(buf));
          action_args = buf;
          if ((action_args = strchr(action, '(')) && (tmp = strrchr(action_args, ')'))) {
             *tmp = '\0';
             action_args++;
          }
          res |= add_action_to_menu_entry(menu_entry, MENU_ACTION_PLAYBACK_AND_CONTINUE, action_args);
       } else if (action_len >= 8 && !strncasecmp(action, "playback(", 9)) {
          ast_copy_string(buf, action, sizeof(buf));
          action_args = buf;
          if ((action_args = strchr(action, '(')) && (tmp = strrchr(action_args, ')'))) {
             *tmp = '\0';
             action_args++;
          }
          res |= add_action_to_menu_entry(menu_entry, MENU_ACTION_PLAYBACK, action_args);
       }
    }
    /* if adding any of the actions failed, bail */
    if (res) {
       struct conf_menu_action *menu_action;
       while ((menu_action = AST_LIST_REMOVE_HEAD(&menu_entry->actions, action))) {
          ast_free(menu_action);
       }
       ast_free(menu_entry);
       return -1;
    }
    /* remove any list entry with an identical DTMF sequence for overrides */
    AST_LIST_TRAVERSE_SAFE_BEGIN(&menu->entries, cur, entry) {
       if (!strcasecmp(cur->dtmf, menu_entry->dtmf)) {
          AST_LIST_REMOVE_CURRENT(entry);
          ast_free(cur);
          break;
       }
    }
    AST_LIST_TRAVERSE_SAFE_END;
    AST_LIST_INSERT_TAIL(&menu->entries, menu_entry, entry);
    return 0;
 }
announce_user_count_all_handler()
static int announce_user_count_all_handler (const struct aco_option * opt, struct ast_variable * var, void * obj) static
Definition at line 2082 of file conf_config_parser.c.
References user_profile::announce_user_count_all_after, ast_false(), ast_true(), user_profile::flags, ast_variable::name, USER_OPT_ANNOUNCEUSERCOUNTALL, and ast_variable::value.
Referenced by conf_load_config().
 {
    struct user_profile *u_profile = obj;
    if (strcasecmp(var->name, "announce_user_count_all")) {
       return -1;
    }
    if (ast_true(var->value)) {
       u_profile->flags = u_profile->flags | USER_OPT_ANNOUNCEUSERCOUNTALL;
    } else if (ast_false(var->value)) {
       u_profile->flags = u_profile->flags & ~USER_OPT_ANNOUNCEUSERCOUNTALL;
    } else if (sscanf(var->value, "%30u", &u_profile->announce_user_count_all_after) == 1) {
       u_profile->flags = u_profile->flags | USER_OPT_ANNOUNCEUSERCOUNTALL;
    } else {
       return -1;
    }
    return 0;
 }
AO2_GLOBAL_OBJ_STATIC()
static AO2_GLOBAL_OBJ_STATIC (cfg_handle) static
apply_menu_to_user()
static int apply_menu_to_user (struct confbridge_user * user, struct conf_menu * menu) static
Definition at line 2627 of file conf_config_parser.c.
References ao2_bump, ast_bridge_dtmf_hook(), ast_calloc, AST_LIST_TRAVERSE, copy_menu_entry(), conf_menu_entry::dtmf, conf_menu::entries, confbridge_user::features, dtmf_menu_hook_pvt::menu, dtmf_menu_hook_pvt::menu_entry, menu_hook_callback(), menu_hook_destroy(), confbridge_user::menu_name, conf_menu::name, SCOPED_AO2LOCK, user, and dtmf_menu_hook_pvt::user.
Referenced by conf_set_menu_to_user().
 {
    struct conf_menu_entry *menu_entry;
    SCOPED_AO2LOCK(menu_lock, menu);
    AST_LIST_TRAVERSE(&menu->entries, menu_entry, entry) {
       struct dtmf_menu_hook_pvt *pvt;
       if (!(pvt = ast_calloc(1, sizeof(*pvt)))) {
          return -1;
       }
       pvt->user = user;
       pvt->menu = ao2_bump(menu);
       if (copy_menu_entry(&pvt->menu_entry, menu_entry)) {
          menu_hook_destroy(pvt);
          return -1;
       }
       if (ast_bridge_dtmf_hook(&user->features, pvt->menu_entry.dtmf,
          menu_hook_callback, pvt, menu_hook_destroy, 0)) {
          menu_hook_destroy(pvt);
       }
    }
    strcpy(user->menu_name, menu->name); /* Safe */
    return 0;
 }
bridge_cmp_cb()
static int bridge_cmp_cb (void * obj, void * arg, int flags) static
bridge profile container functions
Definition at line 847 of file conf_config_parser.c.
References CMP_MATCH, bridge_profile::name, OBJ_KEY, OBJ_PARTIAL_KEY, and OBJ_POINTER.
Referenced by confbridge_cfg_alloc().
 {
    const struct bridge_profile *left = obj;
    const struct bridge_profile *right = arg;
    const char *right_name = arg;
    int cmp;
    switch (flags & (OBJ_POINTER | OBJ_KEY | OBJ_PARTIAL_KEY)) {
    default:
    case OBJ_POINTER:
       right_name = right->name;
       /* Fall through */
    case OBJ_KEY:
       cmp = strcasecmp(left->name, right_name);
       break;
    case OBJ_PARTIAL_KEY:
       cmp = strncasecmp(left->name, right_name, strlen(right_name));
       break;
    }
    return cmp ? 0 : CMP_MATCH;
 }
bridge_hash_cb()
static int bridge_hash_cb (const void * obj, const int flags) static
Definition at line 869 of file conf_config_parser.c.
References ast_assert, ast_str_case_hash(), name, bridge_profile::name, OBJ_KEY, OBJ_PARTIAL_KEY, and OBJ_POINTER.
Referenced by confbridge_cfg_alloc().
 {
    const struct bridge_profile *b_profile = obj;
    const char *name = obj;
    int hash;
    switch (flags & (OBJ_POINTER | OBJ_KEY | OBJ_PARTIAL_KEY)) {
    default:
    case OBJ_POINTER:
       name = b_profile->name;
       /* Fall through */
    case OBJ_KEY:
       hash = ast_str_case_hash(name);
       break;
    case OBJ_PARTIAL_KEY:
       /* Should never happen in hash callback. */
       ast_assert(0);
       hash = 0;
       break;
    }
    return hash;
 }
bridge_profile_alloc()
static void * bridge_profile_alloc (const char * category) static
Definition at line 716 of file conf_config_parser.c.
References ao2_alloc, ao2_ref, ast_copy_string(), bridge_profile_destructor(), bridge_profile_sounds_alloc(), bridge_profile::name, NULL, and bridge_profile::sounds.
Referenced by verify_default_profiles().
 {
    struct bridge_profile *b_profile;
    if (!(b_profile = ao2_alloc(sizeof(*b_profile), bridge_profile_destructor))) {
       return NULL;
    }
    if (!(b_profile->sounds = bridge_profile_sounds_alloc())) {
       ao2_ref(b_profile, -1);
       return NULL;
    }
    ast_copy_string(b_profile->name, category, sizeof(b_profile->name));
    return b_profile;
 }
bridge_profile_destructor()
static void bridge_profile_destructor (void * obj) static
Definition at line 710 of file conf_config_parser.c.
References ao2_cleanup, and bridge_profile::sounds.
Referenced by bridge_profile_alloc().
 {
    struct bridge_profile *b_profile = obj;
    ao2_cleanup(b_profile->sounds);
 }
bridge_profile_find()
static void * bridge_profile_find (struct ao2_container * container, const char * category) static
Definition at line 734 of file conf_config_parser.c.
References ao2_find, and OBJ_KEY.
 {
    return ao2_find(container, category, OBJ_KEY);
 }
bridge_profile_sounds_alloc()
static struct bridge_profile_sounds * bridge_profile_sounds_alloc (void) static
Definition at line 1002 of file conf_config_parser.c.
References ao2_alloc, ao2_ref, ast_string_field_init, bridge_profile_sounds_destroy_cb(), NULL, and sounds.
Referenced by bridge_profile_alloc(), bridge_template_handler(), and func_confbridge_helper().
 {
    struct bridge_profile_sounds *sounds = ao2_alloc(sizeof(*sounds), bridge_profile_sounds_destroy_cb);
    if (!sounds) {
       return NULL;
    }
    if (ast_string_field_init(sounds, 512)) {
       ao2_ref(sounds, -1);
       return NULL;
    }
    return sounds;
 }
bridge_profile_sounds_destroy_cb()
static void bridge_profile_sounds_destroy_cb (void * obj) static
Bridge Profile Sounds functions
Definition at line 996 of file conf_config_parser.c.
References ast_string_field_free_memory, and sounds.
Referenced by bridge_profile_sounds_alloc().
 {
    struct bridge_profile_sounds *sounds = obj;
    ast_string_field_free_memory(sounds);
 }
bridge_template_handler()
static int bridge_template_handler (const struct aco_option * opt, struct ast_variable * var, void * obj) static
Definition at line 2213 of file conf_config_parser.c.
References ao2_ref, ast_string_field_set, bridge_profile_sounds::begin, bridge_profile_sounds_alloc(), conf_find_bridge_profile(), bridge_profile_sounds::errormenu, bridge_profile_sounds::getpin, bridge_profile_sounds::hasjoin, bridge_profile_sounds::hasleft, bridge_profile_sounds::invalidpin, bridge_profile_sounds::join, bridge_profile_sounds::kicked, bridge_profile_sounds::leaderhasleft, leave, bridge_profile_sounds::leave, bridge_profile_sounds::locked, bridge_profile_sounds::lockednow, muted, bridge_profile_sounds::muted, NULL, bridge_profile_sounds::onlyone, bridge_profile_sounds::onlyperson, bridge_profile_sounds::otherinparty, bridge_profile_sounds::participantsmuted, bridge_profile_sounds::participantsunmuted, bridge_profile_sounds::placeintoconf, sounds, bridge_profile::sounds, bridge_profile_sounds::thereare, bridge_profile_sounds::unlockednow, bridge_profile_sounds::unmuted, ast_variable::value, and bridge_profile_sounds::waitforleader.
Referenced by conf_load_config().
 {
    struct bridge_profile *b_profile = obj;
    struct bridge_profile_sounds *sounds = bridge_profile_sounds_alloc();
    struct bridge_profile_sounds *oldsounds = b_profile->sounds;
    if (!sounds) {
       return -1;
    }
    if (!(conf_find_bridge_profile(NULL, var->value, b_profile))) {
       ao2_ref(sounds, -1);
       return -1;
    }
    /* Using a bridge profile as a template is a little complicated due to the sounds. Since the sounds
     * structure of a dynamic profile will need to be altered, a completely new sounds structure must be
     * created instead of simply holding a reference to the one built by the config file. */
    ast_string_field_set(sounds, onlyperson, b_profile->sounds->onlyperson);
    ast_string_field_set(sounds, onlyone, b_profile->sounds->onlyone);
    ast_string_field_set(sounds, hasjoin, b_profile->sounds->hasjoin);
    ast_string_field_set(sounds, hasleft, b_profile->sounds->hasleft);
    ast_string_field_set(sounds, kicked, b_profile->sounds->kicked);
    ast_string_field_set(sounds, muted, b_profile->sounds->muted);
    ast_string_field_set(sounds, unmuted, b_profile->sounds->unmuted);
    ast_string_field_set(sounds, thereare, b_profile->sounds->thereare);
    ast_string_field_set(sounds, otherinparty, b_profile->sounds->otherinparty);
    ast_string_field_set(sounds, placeintoconf, b_profile->sounds->placeintoconf);
    ast_string_field_set(sounds, waitforleader, b_profile->sounds->waitforleader);
    ast_string_field_set(sounds, leaderhasleft, b_profile->sounds->leaderhasleft);
    ast_string_field_set(sounds, getpin, b_profile->sounds->getpin);
    ast_string_field_set(sounds, invalidpin, b_profile->sounds->invalidpin);
    ast_string_field_set(sounds, locked, b_profile->sounds->locked);
    ast_string_field_set(sounds, unlockednow, b_profile->sounds->unlockednow);
    ast_string_field_set(sounds, lockednow, b_profile->sounds->lockednow);
    ast_string_field_set(sounds, errormenu, b_profile->sounds->errormenu);
    ast_string_field_set(sounds, join, b_profile->sounds->join);
    ast_string_field_set(sounds, leave, b_profile->sounds->leave);
    ast_string_field_set(sounds, participantsmuted, b_profile->sounds->participantsmuted);
    ast_string_field_set(sounds, participantsunmuted, b_profile->sounds->participantsunmuted);
    ast_string_field_set(sounds, begin, b_profile->sounds->begin);
    ao2_ref(b_profile->sounds, -1); /* sounds struct copied over to it from the template by reference only. */
    ao2_ref(oldsounds, -1);    /* original sounds struct we don't need anymore */
    b_profile->sounds = sounds;     /* the new sounds struct that is a deep copy of the one from the template. */
    return 0;
 }
complete_bridge_profile_name()
static char* complete_bridge_profile_name (const char * line, const char * word, int pos, int state) static
Definition at line 1626 of file conf_config_parser.c.
References ao2_cleanup, ao2_global_obj_ref, ao2_iterator_destroy(), ao2_iterator_init(), ao2_iterator_next, ao2_ref, ast_strdup, cfg_handle, bridge_profile::name, NULL, and RAII_VAR.
Referenced by handle_cli_confbridge_show_bridge_profile().
 {
    int which = 0;
    char *res = NULL;
    int wordlen = strlen(word);
    struct ao2_iterator i;
    struct bridge_profile *b_profile = NULL;
    RAII_VAR(struct confbridge_cfg *, cfg, ao2_global_obj_ref(cfg_handle), ao2_cleanup);
    if (!cfg) {
       return NULL;
    }
    i = ao2_iterator_init(cfg->bridge_profiles, 0);
    while ((b_profile = ao2_iterator_next(&i))) {
       if (!strncasecmp(b_profile->name, word, wordlen) && ++which > state) {
          res = ast_strdup(b_profile->name);
          ao2_ref(b_profile, -1);
          break;
       }
       ao2_ref(b_profile, -1);
    }
    ao2_iterator_destroy(&i);
    return res;
 }
complete_menu_name()
static char* complete_menu_name (const char * line, const char * word, int pos, int state) static
Definition at line 1858 of file conf_config_parser.c.
References ao2_cleanup, ao2_global_obj_ref, ao2_iterator_destroy(), ao2_iterator_init(), ao2_iterator_next, ao2_ref, ast_strdup, cfg_handle, conf_menu::name, NULL, and RAII_VAR.
Referenced by handle_cli_confbridge_show_menu().
 {
    int which = 0;
    char *res = NULL;
    int wordlen = strlen(word);
    struct ao2_iterator i;
    struct conf_menu *menu = NULL;
    RAII_VAR(struct confbridge_cfg *, cfg, ao2_global_obj_ref(cfg_handle), ao2_cleanup);
    if (!cfg) {
       return NULL;
    }
    i = ao2_iterator_init(cfg->menus, 0);
    while ((menu = ao2_iterator_next(&i))) {
       if (!strncasecmp(menu->name, word, wordlen) && ++which > state) {
          res = ast_strdup(menu->name);
          ao2_ref(menu, -1);
          break;
       }
       ao2_ref(menu, -1);
    }
    ao2_iterator_destroy(&i);
    return res;
 }
complete_user_profile_name()
static char* complete_user_profile_name (const char * line, const char * word, int pos, int state) static
Definition at line 1463 of file conf_config_parser.c.
References ao2_cleanup, ao2_global_obj_ref, ao2_iterator_destroy(), ao2_iterator_init(), ao2_iterator_next, ao2_ref, ast_strdup, cfg_handle, user_profile::name, NULL, and RAII_VAR.
Referenced by handle_cli_confbridge_show_user_profile().
 {
    int which = 0;
    char *res = NULL;
    int wordlen = strlen(word);
    struct ao2_iterator i;
    struct user_profile *u_profile = NULL;
    RAII_VAR(struct confbridge_cfg *, cfg, ao2_global_obj_ref(cfg_handle), ao2_cleanup);
    if (!cfg) {
       return NULL;
    }
    i = ao2_iterator_init(cfg->user_profiles, 0);
    while ((u_profile = ao2_iterator_next(&i))) {
       if (!strncasecmp(u_profile->name, word, wordlen) && ++which > state) {
          res = ast_strdup(u_profile->name);
          ao2_ref(u_profile, -1);
          break;
       }
       ao2_ref(u_profile, -1);
    }
    ao2_iterator_destroy(&i);
    return res;
 }
conf_bridge_profile_copy()
void conf_bridge_profile_copy (struct bridge_profile * dst, struct bridge_profile * src)
copies a bridge profile
Note
conf_bridge_profile_destroy must be called on the dst structure
Definition at line 2523 of file conf_config_parser.c.
References ao2_ref, and bridge_profile::sounds.
Referenced by conf_find_bridge_profile(), and join_conference_bridge().
 {
    *dst = *src;
    if (src->sounds) {
       ao2_ref(src->sounds, +1);
    }
 }
conf_bridge_profile_destroy()
void conf_bridge_profile_destroy (struct bridge_profile * b_profile)
Destroy a bridge profile found by 'conf_find_bridge_profile'.
Definition at line 2531 of file conf_config_parser.c.
References ao2_ref, NULL, and bridge_profile::sounds.
Referenced by confbridge_exec(), destroy_conference_bridge(), func_confbridge_data_destructor(), func_confbridge_helper(), and handle_cli_confbridge_show_bridge_profile().
 {
    if (b_profile->sounds) {
       ao2_ref(b_profile->sounds, -1);
       b_profile->sounds = NULL;
    }
 }
conf_destroy_config()
void conf_destroy_config (void)
destroy the information loaded from the confbridge.conf file
Definition at line 2694 of file conf_config_parser.c.
References aco_info_destroy(), ao2_global_obj_release, ARRAY_LEN, ast_cli_unregister_multiple(), and cfg_handle.
Referenced by conf_load_config(), and unload_module().
 {
    ast_cli_unregister_multiple(cli_confbridge_parser, ARRAY_LEN(cli_confbridge_parser));
    aco_info_destroy(&cfg_info);
    ao2_global_obj_release(cfg_handle);
 }
conf_find_bridge_profile()
const struct bridge_profile* conf_find_bridge_profile (struct ast_channel * chan, const char * bridge_profile_name, struct bridge_profile * result)
Find a bridge profile given a bridge profile's name and store that profile in result structure.
Parameters
chan channel the bridge profile is requested for
bridge_profile_name name of the profile requested (optional)
result data contained by the bridge profile will be copied to this struct pointer
If bridge_profile_name is not provided, this function will check for the presence of a bridge profile set by the CONFBRIDGE function on a channel datastore. If that doesn't exist, the default_bridge profile is used.
Return values
bridge profile on success
NULL on failure
Definition at line 2539 of file conf_config_parser.c.
References ao2_cleanup, ao2_find, ao2_global_obj_ref, ao2_lock, ao2_ref, ao2_unlock, ast_channel_datastore_find(), ast_channel_lock, ast_channel_unlock, ast_strlen_zero, func_confbridge_data::b_profile, func_confbridge_data::b_usable, cfg_handle, conf_bridge_profile_copy(), ast_datastore::data, DEFAULT_BRIDGE_PROFILE, NULL, OBJ_KEY, RAII_VAR, and result.
Referenced by bridge_template_handler(), confbridge_exec(), and handle_cli_confbridge_show_bridge_profile().
 {
    struct bridge_profile *tmp2;
    struct ast_datastore *datastore = NULL;
    struct func_confbridge_data *b_data = NULL;
    RAII_VAR(struct confbridge_cfg *, cfg, ao2_global_obj_ref(cfg_handle), ao2_cleanup);
    if (chan && ast_strlen_zero(bridge_profile_name)) {
       ast_channel_lock(chan);
       datastore = ast_channel_datastore_find(chan, &confbridge_datastore, NULL);
       ast_channel_unlock(chan);
       if (datastore) {
          b_data = datastore->data;
          if (b_data->b_usable) {
             conf_bridge_profile_copy(result, &b_data->b_profile);
             return result;
          }
       }
    }
    if (!cfg) {
       return NULL;
    }
    if (ast_strlen_zero(bridge_profile_name)) {
       bridge_profile_name = DEFAULT_BRIDGE_PROFILE;
    }
    if (!(tmp2 = ao2_find(cfg->bridge_profiles, bridge_profile_name, OBJ_KEY))) {
       return NULL;
    }
    ao2_lock(tmp2);
    conf_bridge_profile_copy(result, tmp2);
    ao2_unlock(tmp2);
    ao2_ref(tmp2, -1);
    return result;
 }
conf_find_menu_entry_by_sequence()
int conf_find_menu_entry_by_sequence (const char * dtmf_sequence, struct conf_menu * menu, struct conf_menu_entry * result)
Finds a menu_entry in a menu structure matched by DTMF sequence.
Note
the menu entry found must be destroyed using conf_menu_entry_destroy()
Return values
1 success, entry is found and stored in result
0 failure, no entry found for given DTMF sequence
Definition at line 2610 of file conf_config_parser.c.
References ao2_lock, ao2_unlock, AST_LIST_TRAVERSE, copy_menu_entry(), conf_menu_entry::dtmf, conf_menu::entries, and NULL.
Referenced by action_playback_and_continue().
 {
    struct conf_menu_entry *menu_entry = NULL;
    ao2_lock(menu);
    AST_LIST_TRAVERSE(&menu->entries, menu_entry, entry) {
       if (!strcasecmp(menu_entry->dtmf, dtmf_sequence)) {
          copy_menu_entry(result, menu_entry);
          ao2_unlock(menu);
          return 1;
       }
    }
    ao2_unlock(menu);
    return 0;
 }
conf_find_user_profile()
const struct user_profile* conf_find_user_profile (struct ast_channel * chan, const char * user_profile_name, struct user_profile * result)
find a user profile given a user profile's name and store that profile in result structure.
Parameters
chan channel the user profile is requested for
user_profile_name name of the profile requested (optional)
result data contained by the user profile will be copied to this struct pointer
If user_profile_name is not provided, this function will check for the presence of a user profile set by the CONFBRIDGE function on a channel datastore. If that doesn't exist, the default_user profile is used.
Return values
user profile on success
NULL on failure
Definition at line 2486 of file conf_config_parser.c.
References ao2_cleanup, ao2_find, ao2_global_obj_ref, ao2_lock, ao2_ref, ao2_unlock, ast_channel_datastore_find(), ast_channel_lock, ast_channel_unlock, ast_strlen_zero, cfg_handle, conf_user_profile_copy(), ast_datastore::data, DEFAULT_USER_PROFILE, NULL, OBJ_KEY, RAII_VAR, result, func_confbridge_data::u_profile, and func_confbridge_data::u_usable.
Referenced by conf_send_event_to_participants(), confbridge_exec(), handle_cli_confbridge_show_user_profile(), and user_template_handler().
 {
    struct user_profile *tmp2;
    struct ast_datastore *datastore = NULL;
    struct func_confbridge_data *b_data = NULL;
    RAII_VAR(struct confbridge_cfg *, cfg, ao2_global_obj_ref(cfg_handle), ao2_cleanup);
    if (chan && ast_strlen_zero(user_profile_name)) {
       ast_channel_lock(chan);
       datastore = ast_channel_datastore_find(chan, &confbridge_datastore, NULL);
       ast_channel_unlock(chan);
       if (datastore) {
          b_data = datastore->data;
          if (b_data->u_usable) {
             conf_user_profile_copy(result, &b_data->u_profile);
             return result;
          }
       }
    }
    if (!cfg) {
       return NULL;
    }
    if (ast_strlen_zero(user_profile_name)) {
       user_profile_name = DEFAULT_USER_PROFILE;
    }
    if (!(tmp2 = ao2_find(cfg->user_profiles, user_profile_name, OBJ_KEY))) {
       return NULL;
    }
    ao2_lock(tmp2);
    conf_user_profile_copy(result, tmp2);
    ao2_unlock(tmp2);
    ao2_ref(tmp2, -1);
    return result;
 }
conf_load_config()
int conf_load_config (void)
load confbridge.conf file
Definition at line 2384 of file conf_config_parser.c.
References __stringify, ACO_EXACT, aco_info_init(), aco_option_register, aco_option_register_custom, ACO_PREFIX, aco_process_config(), ACO_PROCESS_ERROR, ACO_REGEX, announce_user_count_all_handler(), ARRAY_LEN, ast_cli_register_multiple, BRIDGE_OPT_BINAURAL_ACTIVE, BRIDGE_OPT_ENABLE_EVENTS, BRIDGE_OPT_RECORD_CONFERENCE, BRIDGE_OPT_RECORD_FILE_APPEND, BRIDGE_OPT_RECORD_FILE_TIMESTAMP, bridge_template_handler(), CHARFLDSET, conf_destroy_config(), DEFAULT_SILENCE_THRESHOLD, DEFAULT_TALKING_THRESHOLD, error(), FLDSET, language, menu_option_handler(), menu_template_handler(), mix_interval_handler(), NULL, OPT_BOOLFLAG_T, OPT_CHAR_ARRAY_T, OPT_NOOP_T, OPT_UINT_T, PARSE_DEFAULT, regcontext, remb_behavior_handler(), sound_option_handler(), timeout, USER_OPT_ADMIN, USER_OPT_ANNOUNCE_JOIN_LEAVE, USER_OPT_ANNOUNCE_JOIN_LEAVE_REVIEW, USER_OPT_ANNOUNCEUSERCOUNT, USER_OPT_ANSWER_CHANNEL, USER_OPT_DENOISE, USER_OPT_DROP_SILENCE, USER_OPT_DTMF_PASS, USER_OPT_ECHO_EVENTS, USER_OPT_ENDMARKED, USER_OPT_JITTERBUFFER, USER_OPT_MARKEDUSER, USER_OPT_MUSICONHOLD, USER_OPT_NOONLYPERSON, USER_OPT_QUIET, USER_OPT_SEND_EVENTS, USER_OPT_STARTMUTED, USER_OPT_TALKER_DETECT, USER_OPT_TEXT_MESSAGING, USER_OPT_WAITMARKED, user_template_handler(), and video_mode_handler().
Referenced by load_module().
 {
    if (aco_info_init(&cfg_info)) {
       return -1;
    }
    /* User options */
    aco_option_register(&cfg_info, "type", ACO_EXACT, user_types, NULL, OPT_NOOP_T, 0, 0);
    aco_option_register(&cfg_info, "admin", ACO_EXACT, user_types, "no", OPT_BOOLFLAG_T, 1, FLDSET(struct user_profile, flags), USER_OPT_ADMIN);
    aco_option_register(&cfg_info, "send_events", ACO_EXACT, user_types, "no", OPT_BOOLFLAG_T, 1, FLDSET(struct user_profile, flags), USER_OPT_SEND_EVENTS);
    aco_option_register(&cfg_info, "echo_events", ACO_EXACT, user_types, "no", OPT_BOOLFLAG_T, 1, FLDSET(struct user_profile, flags), USER_OPT_ECHO_EVENTS);
    aco_option_register(&cfg_info, "marked", ACO_EXACT, user_types, "no", OPT_BOOLFLAG_T, 1, FLDSET(struct user_profile, flags), USER_OPT_MARKEDUSER);
    aco_option_register(&cfg_info, "startmuted", ACO_EXACT, user_types, "no", OPT_BOOLFLAG_T, 1, FLDSET(struct user_profile, flags), USER_OPT_STARTMUTED);
    aco_option_register(&cfg_info, "music_on_hold_when_empty", ACO_EXACT, user_types, "no", OPT_BOOLFLAG_T, 1, FLDSET(struct user_profile, flags), USER_OPT_MUSICONHOLD);
    aco_option_register(&cfg_info, "quiet", ACO_EXACT, user_types, "no", OPT_BOOLFLAG_T, 1, FLDSET(struct user_profile, flags), USER_OPT_QUIET);
    aco_option_register_custom(&cfg_info, "announce_user_count_all", ACO_EXACT, user_types, "no", announce_user_count_all_handler, 0);
    aco_option_register(&cfg_info, "announce_user_count", ACO_EXACT, user_types, "no", OPT_BOOLFLAG_T, 1, FLDSET(struct user_profile, flags), USER_OPT_ANNOUNCEUSERCOUNT);
    /* Negative logic. Defaults to "yes" and evaluates with ast_false(). If !ast_false(), USER_OPT_NOONLYPERSON is cleared */
    aco_option_register(&cfg_info, "announce_only_user", ACO_EXACT, user_types, "yes", OPT_BOOLFLAG_T, 0, FLDSET(struct user_profile, flags), USER_OPT_NOONLYPERSON);
    aco_option_register(&cfg_info, "wait_marked", ACO_EXACT, user_types, "no", OPT_BOOLFLAG_T, 1, FLDSET(struct user_profile, flags), USER_OPT_WAITMARKED);
    aco_option_register(&cfg_info, "end_marked", ACO_EXACT, user_types, "no", OPT_BOOLFLAG_T, 1, FLDSET(struct user_profile, flags), USER_OPT_ENDMARKED);
    aco_option_register(&cfg_info, "talk_detection_events", ACO_EXACT, user_types, "no", OPT_BOOLFLAG_T, 1, FLDSET(struct user_profile, flags), USER_OPT_TALKER_DETECT);
    aco_option_register(&cfg_info, "dtmf_passthrough", ACO_EXACT, user_types, "no", OPT_BOOLFLAG_T, 1, FLDSET(struct user_profile, flags), USER_OPT_DTMF_PASS);
    aco_option_register(&cfg_info, "announce_join_leave", ACO_EXACT, user_types, "no", OPT_BOOLFLAG_T, 1, FLDSET(struct user_profile, flags), USER_OPT_ANNOUNCE_JOIN_LEAVE);
    aco_option_register(&cfg_info, "announce_join_leave_review", ACO_EXACT, user_types, "no", OPT_BOOLFLAG_T, 1, FLDSET(struct user_profile, flags), USER_OPT_ANNOUNCE_JOIN_LEAVE_REVIEW);
    aco_option_register(&cfg_info, "pin", ACO_EXACT, user_types, NULL, OPT_CHAR_ARRAY_T, 0, CHARFLDSET(struct user_profile, pin));
    aco_option_register(&cfg_info, "music_on_hold_class", ACO_EXACT, user_types, NULL, OPT_CHAR_ARRAY_T, 0, CHARFLDSET(struct user_profile, moh_class));
    aco_option_register(&cfg_info, "announcement", ACO_EXACT, user_types, NULL, OPT_CHAR_ARRAY_T, 0, CHARFLDSET(struct user_profile, announcement));
    aco_option_register(&cfg_info, "denoise", ACO_EXACT, user_types, "no", OPT_BOOLFLAG_T, 1, FLDSET(struct user_profile, flags), USER_OPT_DENOISE);
    aco_option_register(&cfg_info, "dsp_drop_silence", ACO_EXACT, user_types, "no", OPT_BOOLFLAG_T, 1, FLDSET(struct user_profile, flags), USER_OPT_DROP_SILENCE);
    aco_option_register(&cfg_info, "dsp_silence_threshold", ACO_EXACT, user_types, __stringify(DEFAULT_SILENCE_THRESHOLD), OPT_UINT_T, 0, FLDSET(struct user_profile, silence_threshold));
    aco_option_register(&cfg_info, "dsp_talking_threshold", ACO_EXACT, user_types, __stringify(DEFAULT_TALKING_THRESHOLD), OPT_UINT_T, 0, FLDSET(struct user_profile, talking_threshold));
    aco_option_register(&cfg_info, "jitterbuffer", ACO_EXACT, user_types, "no", OPT_BOOLFLAG_T, 1, FLDSET(struct user_profile, flags), USER_OPT_JITTERBUFFER);
    aco_option_register(&cfg_info, "timeout", ACO_EXACT, user_types, "0", OPT_UINT_T, 0, FLDSET(struct user_profile, timeout));
    aco_option_register(&cfg_info, "text_messaging", ACO_EXACT, user_types, "yes", OPT_BOOLFLAG_T, 1, FLDSET(struct user_profile, flags), USER_OPT_TEXT_MESSAGING);
    aco_option_register(&cfg_info, "answer_channel", ACO_EXACT, user_types, "yes", OPT_BOOLFLAG_T, 1, FLDSET(struct user_profile, flags), USER_OPT_ANSWER_CHANNEL);
    /* This option should only be used with the CONFBRIDGE dialplan function */
    aco_option_register_custom(&cfg_info, "template", ACO_EXACT, user_types, NULL, user_template_handler, 0);
 /* XXX ASTERISK-21271 need a user supplied bridge merge_priority to merge ConfBridges (default = 1, range 1-INT_MAX) */
    /* Bridge options */
    aco_option_register(&cfg_info, "type", ACO_EXACT, bridge_types, NULL, OPT_NOOP_T, 0, 0);
    aco_option_register(&cfg_info, "jitterbuffer", ACO_EXACT, bridge_types, "no", OPT_BOOLFLAG_T, 1, FLDSET(struct bridge_profile, flags), USER_OPT_JITTERBUFFER);
    /* "auto" will fail to parse as a uint, but we use PARSE_DEFAULT to set the value to 0 in that case, which is the value that auto resolves to */
    aco_option_register(&cfg_info, "internal_sample_rate", ACO_EXACT, bridge_types, "0", OPT_UINT_T, PARSE_DEFAULT, FLDSET(struct bridge_profile, internal_sample_rate), 0);
    aco_option_register(&cfg_info, "binaural_active", ACO_EXACT, bridge_types, "no", OPT_BOOLFLAG_T, 1, FLDSET(struct bridge_profile, flags), BRIDGE_OPT_BINAURAL_ACTIVE);
    aco_option_register(&cfg_info, "maximum_sample_rate", ACO_EXACT, bridge_types, "0", OPT_UINT_T, PARSE_DEFAULT, FLDSET(struct bridge_profile, maximum_sample_rate), 0);
    aco_option_register_custom(&cfg_info, "mixing_interval", ACO_EXACT, bridge_types, "20", mix_interval_handler, 0);
    aco_option_register(&cfg_info, "record_conference", ACO_EXACT, bridge_types, "no", OPT_BOOLFLAG_T, 1, FLDSET(struct bridge_profile, flags), BRIDGE_OPT_RECORD_CONFERENCE);
    aco_option_register_custom(&cfg_info, "video_mode", ACO_EXACT, bridge_types, NULL, video_mode_handler, 0);
    aco_option_register(&cfg_info, "record_file_append", ACO_EXACT, bridge_types, "yes", OPT_BOOLFLAG_T, 1, FLDSET(struct bridge_profile, flags), BRIDGE_OPT_RECORD_FILE_APPEND);
    aco_option_register(&cfg_info, "record_file_timestamp", ACO_EXACT, bridge_types, "yes", OPT_BOOLFLAG_T, 1, FLDSET(struct bridge_profile, flags), BRIDGE_OPT_RECORD_FILE_TIMESTAMP);
    aco_option_register(&cfg_info, "max_members", ACO_EXACT, bridge_types, "0", OPT_UINT_T, 0, FLDSET(struct bridge_profile, max_members));
    aco_option_register(&cfg_info, "record_file", ACO_EXACT, bridge_types, NULL, OPT_CHAR_ARRAY_T, 0, CHARFLDSET(struct bridge_profile, rec_file));
    aco_option_register(&cfg_info, "record_options", ACO_EXACT, bridge_types, NULL, OPT_CHAR_ARRAY_T, 0, CHARFLDSET(struct bridge_profile, rec_options));
    aco_option_register(&cfg_info, "record_command", ACO_EXACT, bridge_types, NULL, OPT_CHAR_ARRAY_T, 0, CHARFLDSET(struct bridge_profile, rec_command));
    aco_option_register(&cfg_info, "regcontext", ACO_EXACT, bridge_types, NULL, OPT_CHAR_ARRAY_T, 0, CHARFLDSET(struct bridge_profile, regcontext));
    aco_option_register(&cfg_info, "language", ACO_EXACT, bridge_types, "en", OPT_CHAR_ARRAY_T, 0, CHARFLDSET(struct bridge_profile, language));
    aco_option_register_custom(&cfg_info, "sound_", ACO_PREFIX, bridge_types, NULL, sound_option_handler, 0);
    aco_option_register(&cfg_info, "video_update_discard", ACO_EXACT, bridge_types, "2000", OPT_UINT_T, 0, FLDSET(struct bridge_profile, video_update_discard));
    aco_option_register(&cfg_info, "remb_send_interval", ACO_EXACT, bridge_types, "0", OPT_UINT_T, 0, FLDSET(struct bridge_profile, remb_send_interval));
    aco_option_register_custom(&cfg_info, "remb_behavior", ACO_EXACT, bridge_types, "average", remb_behavior_handler, 0);
    aco_option_register(&cfg_info, "remb_estimated_bitrate", ACO_EXACT, bridge_types, "0", OPT_UINT_T, 0, FLDSET(struct bridge_profile, remb_estimated_bitrate));
    aco_option_register(&cfg_info, "enable_events", ACO_EXACT, bridge_types, "no", OPT_BOOLFLAG_T, 1, FLDSET(struct bridge_profile, flags), BRIDGE_OPT_ENABLE_EVENTS);
    /* This option should only be used with the CONFBRIDGE dialplan function */
    aco_option_register_custom(&cfg_info, "template", ACO_EXACT, bridge_types, NULL, bridge_template_handler, 0);
    /* Menu options */
    aco_option_register(&cfg_info, "type", ACO_EXACT, menu_types, NULL, OPT_NOOP_T, 0, 0);
    /* This option should only be used with the CONFBRIDGE dialplan function */
    aco_option_register_custom(&cfg_info, "template", ACO_EXACT, menu_types, NULL, menu_template_handler, 0);
    aco_option_register_custom(&cfg_info, "^[0-9A-D*#]+$", ACO_REGEX, menu_types, NULL, menu_option_handler, 0);
    if (aco_process_config(&cfg_info, 0) == ACO_PROCESS_ERROR) {
       goto error;
    }
    if (ast_cli_register_multiple(cli_confbridge_parser, ARRAY_LEN(cli_confbridge_parser))) {
       goto error;
    }
    return 0;
 error:
    conf_destroy_config();
    return -1;
 }
conf_menu_entry_destroy()
void conf_menu_entry_destroy (struct conf_menu_entry * menu_entry)
Destroys and frees all the actions stored in a menu_entry structure.
Definition at line 2602 of file conf_config_parser.c.
References conf_menu_entry::actions, ast_free, AST_LIST_REMOVE_HEAD, and NULL.
Referenced by action_playback_and_continue(), conf_menu_profile_copy(), and menu_destructor().
 {
    struct conf_menu_action *menu_action = NULL;
    while ((menu_action = AST_LIST_REMOVE_HEAD(&menu_entry->actions, action))) {
       ast_free(menu_action);
    }
 }
conf_menu_profile_copy()
static int conf_menu_profile_copy (struct conf_menu * dst, struct conf_menu * src) static
Definition at line 2280 of file conf_config_parser.c.
References ast_calloc, ast_free, AST_LIST_INSERT_TAIL, AST_LIST_TRAVERSE, conf_menu_entry_destroy(), copy_menu_entry(), and conf_menu::entries.
Referenced by menu_template_handler().
 {
    /* Copy each menu item to the dst struct */
    struct conf_menu_entry *cur;
    AST_LIST_TRAVERSE(&src->entries, cur, entry) {
       struct conf_menu_entry *cpy;
       if (!(cpy = ast_calloc(1, sizeof(*cpy)))) {
          return -1;
       }
       if (copy_menu_entry(cpy, cur)) {
          conf_menu_entry_destroy(cpy);
          ast_free(cpy);
          return -1;
       }
       AST_LIST_INSERT_TAIL(&dst->entries, cpy, entry);
    }
    return 0;
 }
conf_reload_config()
int conf_reload_config (void)
reload confbridge.conf file
Definition at line 2472 of file conf_config_parser.c.
References aco_process_config(), and ACO_PROCESS_ERROR.
Referenced by reload().
 {
    if (aco_process_config(&cfg_info, 1) == ACO_PROCESS_ERROR) {
       /* On a reload, just keep the config we already have in place. */
       return -1;
    }
    return 0;
 }
conf_set_menu_to_user()
int conf_set_menu_to_user (struct ast_channel * chan, struct confbridge_user * user, const char * menu_profile_name)
find a menu profile given a menu profile's name and apply the menu in DTMF hooks.
Parameters
chan channel the menu profile is requested for
user user profile the menu is being applied to
menu_profile_name name of the profile requested (optional)
If menu_profile_name is not provided, this function will check for the presence of a menu profile set by the CONFBRIDGE function on a channel datastore. If that doesn't exist, the default_menu profile is used.
Return values
0 on success
-1 on failure
Definition at line 2656 of file conf_config_parser.c.
References ao2_bump, ao2_cleanup, ao2_find, ao2_global_obj_ref, apply_menu_to_user(), ast_channel_datastore_find(), ast_channel_lock, ast_channel_unlock, ast_strlen_zero, cfg_handle, ast_datastore::data, DEFAULT_MENU_PROFILE, func_confbridge_data::m_usable, func_confbridge_data::menu, NULL, OBJ_KEY, and RAII_VAR.
Referenced by confbridge_exec().
 {
    RAII_VAR(struct confbridge_cfg *, cfg, ao2_global_obj_ref(cfg_handle), ao2_cleanup);
    RAII_VAR(struct conf_menu *, menu, NULL, ao2_cleanup);
    if (chan && ast_strlen_zero(menu_profile_name)) {
       struct ast_datastore *datastore;
       struct func_confbridge_data *b_data;
       ast_channel_lock(chan);
       datastore = ast_channel_datastore_find(chan, &confbridge_datastore, NULL);
       ast_channel_unlock(chan);
       if (datastore) {
          /* If a menu exists in the CONFBRIDGE function datastore, use it. */
          b_data = datastore->data;
          if (b_data->m_usable) {
             menu = ao2_bump(b_data->menu);
             return apply_menu_to_user(user, menu);
          }
       }
    }
    /* Otherwise, we need to get whatever menu profile is specified to use (or default). */
    if (!cfg) {
       return -1;
    }
    if (ast_strlen_zero(menu_profile_name)) {
       menu_profile_name = DEFAULT_MENU_PROFILE;
    }
    if (!(menu = ao2_find(cfg->menus, menu_profile_name, OBJ_KEY))) {
       return -1;
    }
    return apply_menu_to_user(user, menu);
 }
conf_user_profile_copy()
static void conf_user_profile_copy (struct user_profile * dst, struct user_profile * src) static
Definition at line 2481 of file conf_config_parser.c.
Referenced by conf_find_user_profile().
 {
    *dst = *src;
 }
confbridge_cfg_alloc()
void * confbridge_cfg_alloc (void) static
Definition at line 2050 of file conf_config_parser.c.
References ao2_alloc, AO2_ALLOC_OPT_LOCK_MUTEX, ao2_container_alloc_hash, ao2_ref, bridge_cmp_cb(), bridge_hash_cb(), confbridge_cfg::bridge_profiles, confbridge_cfg_destructor(), error(), menu_cmp_cb(), menu_hash_cb(), confbridge_cfg::menus, NULL, user_cmp_cb(), user_hash_cb(), and confbridge_cfg::user_profiles.
 {
    struct confbridge_cfg *cfg;
    if (!(cfg = ao2_alloc(sizeof(*cfg), confbridge_cfg_destructor))) {
       return NULL;
    }
    cfg->user_profiles = ao2_container_alloc_hash(AO2_ALLOC_OPT_LOCK_MUTEX, 0, 283,
       user_hash_cb, NULL, user_cmp_cb);
    if (!cfg->user_profiles) {
       goto error;
    }
    cfg->bridge_profiles = ao2_container_alloc_hash(AO2_ALLOC_OPT_LOCK_MUTEX, 0, 283,
       bridge_hash_cb, NULL, bridge_cmp_cb);
    if (!cfg->bridge_profiles) {
       goto error;
    }
    cfg->menus = ao2_container_alloc_hash(AO2_ALLOC_OPT_LOCK_MUTEX, 0, 283,
       menu_hash_cb, NULL, menu_cmp_cb);
    if (!cfg->menus) {
       goto error;
    }
    return cfg;
 error:
    ao2_ref(cfg, -1);
    return NULL;
 }
confbridge_cfg_destructor()
static void confbridge_cfg_destructor (void * obj) static
Definition at line 2042 of file conf_config_parser.c.
References ao2_cleanup, confbridge_cfg::bridge_profiles, confbridge_cfg::menus, and confbridge_cfg::user_profiles.
Referenced by confbridge_cfg_alloc().
 {
    struct confbridge_cfg *cfg = obj;
    ao2_cleanup(cfg->user_profiles);
    ao2_cleanup(cfg->bridge_profiles);
    ao2_cleanup(cfg->menus);
 }
CONFIG_INFO_STANDARD()
CONFIG_INFO_STANDARD (cfg_info , cfg_handle , confbridge_cfg_alloc , . files = ACO_FILES(&confbridge_conf), . pre_apply_config = verify_default_profiles)
copy_menu_entry()
static int copy_menu_entry (struct conf_menu_entry * dst, struct conf_menu_entry * src) static
Definition at line 2260 of file conf_config_parser.c.
References conf_menu_entry::actions, ast_calloc, ast_copy_string(), AST_LIST_HEAD_INIT_NOLOCK, AST_LIST_INSERT_TAIL, AST_LIST_NEXT, AST_LIST_TRAVERSE, conf_menu_entry::dtmf, and NULL.
Referenced by apply_menu_to_user(), conf_find_menu_entry_by_sequence(), and conf_menu_profile_copy().
 {
    struct conf_menu_action *menu_action;
    struct conf_menu_action *new_menu_action;
    ast_copy_string(dst->dtmf, src->dtmf, sizeof(dst->dtmf));
    AST_LIST_HEAD_INIT_NOLOCK(&dst->actions);
    AST_LIST_TRAVERSE(&src->actions, menu_action, action) {
       if (!(new_menu_action = ast_calloc(1, sizeof(*new_menu_action)))) {
          return -1;
       }
       memcpy(new_menu_action, menu_action, sizeof(*new_menu_action));
       AST_LIST_NEXT(new_menu_action, action) = NULL;
       AST_LIST_INSERT_TAIL(&dst->actions, new_menu_action, action);
    }
    return 0;
 }
func_confbridge_data_destructor()
static void func_confbridge_data_destructor (struct func_confbridge_data * b_data) static
Definition at line 1097 of file conf_config_parser.c.
References ao2_cleanup, ast_free, func_confbridge_data::b_profile, conf_bridge_profile_destroy(), and func_confbridge_data::menu.
Referenced by func_confbridge_destroy_cb().
 {
    conf_bridge_profile_destroy(&b_data->b_profile);
    ao2_cleanup(b_data->menu);
    ast_free(b_data);
 }
func_confbridge_destroy_cb()
static void func_confbridge_destroy_cb (void * data) static
Definition at line 1104 of file conf_config_parser.c.
References func_confbridge_data_destructor().
 {
    struct func_confbridge_data *b_data = data;
    func_confbridge_data_destructor(b_data);
 };
func_confbridge_helper()
int func_confbridge_helper (struct ast_channel * chan, const char * cmd, char * data, const char * value)
Definition at line 1115 of file conf_config_parser.c.
References aco_process_var(), ao2_cleanup, args, AST_APP_ARG, ast_calloc, ast_channel_datastore_add(), ast_channel_datastore_find(), ast_channel_datastore_remove(), ast_channel_lock, ast_channel_unlock, ast_datastore_alloc, ast_datastore_free(), AST_DECLARE_APP_ARGS, ast_log, AST_STANDARD_APP_ARGS, ast_strdupa, ast_strlen_zero, func_confbridge_data::b_profile, func_confbridge_data::b_usable, bridge_profile_sounds_alloc(), conf_bridge_profile_destroy(), ast_datastore::data, DEFAULT_BRIDGE_PROFILE, DEFAULT_MENU_PROFILE, DEFAULT_USER_PROFILE, ast_variable::file, LOG_WARNING, func_confbridge_data::m_usable, func_confbridge_data::menu, menu_alloc(), ast_variable::name, NULL, parse(), bridge_profile::sounds, type, func_confbridge_data::u_profile, func_confbridge_data::u_usable, user_profile_destructor(), value, and ast_variable::value.
 {
    struct ast_datastore *datastore;
    struct func_confbridge_data *b_data;
    char *parse;
    struct ast_variable tmpvar = { 0, };
    struct ast_variable template = {
       .name = "template",
       .file = "CONFBRIDGE"
    };
    AST_DECLARE_APP_ARGS(args,
       AST_APP_ARG(type);
       AST_APP_ARG(option);
    );
    if (!chan) {
       ast_log(LOG_WARNING, "No channel was provided to %s function.\n", cmd);
       return -1;
    }
    /* parse all the required arguments and make sure they exist. */
    if (ast_strlen_zero(data)) {
       return -1;
    }
    parse = ast_strdupa(data);
    AST_STANDARD_APP_ARGS(args, parse);
    if (ast_strlen_zero(args.type) || ast_strlen_zero(args.option)) {
       return -1;
    }
    ast_channel_lock(chan);
    datastore = ast_channel_datastore_find(chan, &confbridge_datastore, NULL);
    if (!datastore) {
       datastore = ast_datastore_alloc(&confbridge_datastore, NULL);
       if (!datastore) {
          ast_channel_unlock(chan);
          return 0;
       }
       b_data = ast_calloc(1, sizeof(*b_data));
       if (!b_data) {
          ast_channel_unlock(chan);
          ast_datastore_free(datastore);
          return 0;
       }
       datastore->data = b_data;
       b_data->b_profile.sounds = bridge_profile_sounds_alloc();
       if (!b_data->b_profile.sounds) {
          ast_channel_unlock(chan);
          ast_datastore_free(datastore);
          return 0;
       }
       if (!(b_data->menu = menu_alloc("dialplan"))) {
          ast_channel_unlock(chan);
          ast_datastore_free(datastore);
          return 0;
       }
       ast_channel_datastore_add(chan, datastore);
    } else {
       b_data = datastore->data;
    }
    ast_channel_unlock(chan);
    /* SET(CONFBRIDGE(type,option)=value) */
    if (!value) {
       value = "";
    }
    tmpvar.name = args.option;
    tmpvar.value = value;
    tmpvar.file = "CONFBRIDGE";
    if (!strcasecmp(args.type, "bridge")) {
       if (!strcasecmp(args.option, "clear")) {
          b_data->b_usable = 0;
          conf_bridge_profile_destroy(&b_data->b_profile);
          memset(&b_data->b_profile, 0, sizeof(b_data->b_profile)) ;
          if (!(b_data->b_profile.sounds = bridge_profile_sounds_alloc())) {
             /* If this reallocation fails, the datastore has become unusable and must be destroyed. */
             ast_channel_lock(chan);
             ast_channel_datastore_remove(chan, datastore);
             ast_channel_unlock(chan);
             ast_datastore_free(datastore);
          }
          return 0;
       }
       if (b_data && !b_data->b_usable && strcasecmp(args.option, "template")) {
          template.value = DEFAULT_BRIDGE_PROFILE;
          aco_process_var(&bridge_type, "dialplan", &template, &b_data->b_profile);
       }
       if (!aco_process_var(&bridge_type, "dialplan", &tmpvar, &b_data->b_profile)) {
          b_data->b_usable = 1;
          return 0;
       }
    } else if (!strcasecmp(args.type, "user")) {
       if (!strcasecmp(args.option, "clear")) {
          b_data->u_usable = 0;
          user_profile_destructor(&b_data->u_profile);
          memset(&b_data->u_profile, 0, sizeof(b_data->u_profile));
          return 0;
       }
       if (b_data && !b_data->u_usable && strcasecmp(args.option, "template")) {
          template.value = DEFAULT_USER_PROFILE;
          aco_process_var(&user_type, "dialplan", &template, &b_data->u_profile);
       }
       if (!aco_process_var(&user_type, "dialplan", &tmpvar, &b_data->u_profile)) {
          b_data->u_usable = 1;
          return 0;
       }
    } else if (!strcasecmp(args.type, "menu")) {
       if (!strcasecmp(args.option, "clear")) {
          b_data->m_usable = 0;
          ao2_cleanup(b_data->menu);
          if (!(b_data->menu = menu_alloc("dialplan"))) {
             /* If this reallocation fails, the datastore has become unusable and must be destroyed */
             ast_channel_lock(chan);
             ast_channel_datastore_remove(chan, datastore);
             ast_channel_unlock(chan);
             ast_datastore_free(datastore);
          }
          return 0;
       }
       if (b_data && !b_data->m_usable && strcasecmp(args.option, "template")) {
          template.value = DEFAULT_MENU_PROFILE;
          aco_process_var(&menu_type, "dialplan", &template, &b_data->menu);
       }
       if (!aco_process_var(&menu_type, "dialplan", &tmpvar, b_data->menu)) {
          b_data->m_usable = 1;
          return 0;
       }
    }
    ast_log(LOG_WARNING, "%s(%s,%s) cannot be set to '%s'. Invalid type, option, or value.\n",
       cmd, args.type, args.option, value);
    return -1;
 }
handle_cli_confbridge_show_bridge_profile()
static char* handle_cli_confbridge_show_bridge_profile (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) static
Definition at line 1686 of file conf_config_parser.c.
References ast_cli_args::argc, ast_cli_args::argv, ast_assert, ast_cli(), ast_copy_string(), ast_strlen_zero, BRIDGE_OPT_ENABLE_EVENTS, BRIDGE_OPT_RECORD_CONFERENCE, BRIDGE_OPT_RECORD_FILE_APPEND, BRIDGE_OPT_RECORD_FILE_TIMESTAMP, BRIDGE_OPT_REMB_BEHAVIOR_AVERAGE, BRIDGE_OPT_REMB_BEHAVIOR_AVERAGE_ALL, BRIDGE_OPT_REMB_BEHAVIOR_HIGHEST, BRIDGE_OPT_REMB_BEHAVIOR_HIGHEST_ALL, BRIDGE_OPT_REMB_BEHAVIOR_LOWEST, BRIDGE_OPT_REMB_BEHAVIOR_LOWEST_ALL, BRIDGE_OPT_VIDEO_SRC_FIRST_MARKED, BRIDGE_OPT_VIDEO_SRC_FOLLOW_TALKER, BRIDGE_OPT_VIDEO_SRC_LAST_MARKED, BRIDGE_OPT_VIDEO_SRC_SFU, CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::command, complete_bridge_profile_name(), conf_bridge_profile_destroy(), conf_find_bridge_profile(), conf_get_sound(), CONF_SOUND_BEGIN, CONF_SOUND_BINAURAL_OFF, CONF_SOUND_BINAURAL_ON, CONF_SOUND_ERROR_MENU, CONF_SOUND_GET_PIN, CONF_SOUND_HAS_JOINED, CONF_SOUND_HAS_LEFT, CONF_SOUND_INVALID_PIN, CONF_SOUND_JOIN, CONF_SOUND_KICKED, CONF_SOUND_LEADER_HAS_LEFT, CONF_SOUND_LEAVE, CONF_SOUND_LOCKED, CONF_SOUND_LOCKED_NOW, CONF_SOUND_MUTED, CONF_SOUND_ONLY_ONE, CONF_SOUND_ONLY_PERSON, CONF_SOUND_OTHER_IN_PARTY, CONF_SOUND_PARTICIPANTS_MUTED, CONF_SOUND_PARTICIPANTS_UNMUTED, CONF_SOUND_PLACE_IN_CONF, CONF_SOUND_THERE_ARE, CONF_SOUND_UNLOCKED_NOW, CONF_SOUND_UNMUTED, CONF_SOUND_WAIT_FOR_LEADER, ast_cli_args::fd, bridge_profile::flags, bridge_profile::internal_sample_rate, bridge_profile::language, ast_cli_args::line, bridge_profile::max_members, bridge_profile::maximum_sample_rate, bridge_profile::mix_interval, ast_cli_args::n, bridge_profile::name, NULL, ast_cli_args::pos, bridge_profile::rec_command, bridge_profile::rec_file, bridge_profile::rec_options, bridge_profile::regcontext, bridge_profile::remb_send_interval, bridge_profile::sounds, tmp(), ast_cli_entry::usage, bridge_profile::video_update_discard, and ast_cli_args::word.
 {
    struct bridge_profile b_profile;
    char tmp[64];
    switch (cmd) {
    case CLI_INIT:
       e->command = "confbridge show profile bridge";
       e->usage =
          "Usage: confbridge show profile bridge <profile name>\n";
       return NULL;
    case CLI_GENERATE:
       if (a->pos == 4) {
          return complete_bridge_profile_name(a->line, a->word, a->pos, a->n);
       }
       return NULL;
    }
    if (a->argc != 5) {
       return CLI_SHOWUSAGE;
    }
    if (!(conf_find_bridge_profile(NULL, a->argv[4], &b_profile))) {
       ast_cli(a->fd, "No conference bridge profile named '%s' found!\n", a->argv[4]);
       return CLI_SUCCESS;
    }
    ast_cli(a->fd,"--------------------------------------------\n");
    ast_cli(a->fd,"Name:                 %s\n", b_profile.name);
    ast_cli(a->fd,"Language:             %s\n", b_profile.language);
    if (b_profile.internal_sample_rate) {
       snprintf(tmp, sizeof(tmp), "%u", b_profile.internal_sample_rate);
    } else {
       ast_copy_string(tmp, "auto", sizeof(tmp));
    }
    ast_cli(a->fd,"Internal Sample Rate: %s\n", tmp);
    if (b_profile.maximum_sample_rate) {
       snprintf(tmp, sizeof(tmp), "%u", b_profile.maximum_sample_rate);
    } else {
       ast_copy_string(tmp, "none", sizeof(tmp));
    }
    ast_cli(a->fd,"Maximum Sample Rate: %s\n", tmp);
    if (b_profile.mix_interval) {
       ast_cli(a->fd,"Mixing Interval:      %u\n", b_profile.mix_interval);
    } else {
       ast_cli(a->fd,"Mixing Interval:      Default 20ms\n");
    }
    ast_cli(a->fd,"Record Conference:    %s\n",
       b_profile.flags & BRIDGE_OPT_RECORD_CONFERENCE ?
       "yes" : "no");
    ast_cli(a->fd,"Record File Append:    %s\n",
       b_profile.flags & BRIDGE_OPT_RECORD_FILE_APPEND ?
       "yes" : "no");
    ast_cli(a->fd,"Record File Timestamp: %s\n",
       b_profile.flags & BRIDGE_OPT_RECORD_FILE_TIMESTAMP ?
       "yes" : "no");
    ast_cli(a->fd,"Record File:          %s\n",
       ast_strlen_zero(b_profile.rec_file) ? "Auto Generated" :
       b_profile.rec_file);
    ast_cli(a->fd,"Record Options:       %s\n",
       b_profile.rec_options);
    ast_cli(a->fd,"Record Command:       %s\n",
       b_profile.rec_command);
    if (b_profile.max_members) {
       ast_cli(a->fd,"Max Members:          %u\n", b_profile.max_members);
    } else {
       ast_cli(a->fd,"Max Members:          No Limit\n");
    }
    ast_cli(a->fd,"Registration context: %s\n", b_profile.regcontext);
    switch (b_profile.flags
       & (BRIDGE_OPT_VIDEO_SRC_LAST_MARKED |
          BRIDGE_OPT_VIDEO_SRC_FIRST_MARKED |
          BRIDGE_OPT_VIDEO_SRC_FOLLOW_TALKER |
          BRIDGE_OPT_VIDEO_SRC_SFU)) {
    case BRIDGE_OPT_VIDEO_SRC_LAST_MARKED:
       ast_cli(a->fd, "Video Mode:           last_marked\n");
       break;
    case BRIDGE_OPT_VIDEO_SRC_FIRST_MARKED:
       ast_cli(a->fd, "Video Mode:           first_marked\n");
       break;
    case BRIDGE_OPT_VIDEO_SRC_FOLLOW_TALKER:
       ast_cli(a->fd, "Video Mode:           follow_talker\n");
       break;
    case BRIDGE_OPT_VIDEO_SRC_SFU:
       ast_cli(a->fd, "Video Mode:           sfu\n");
       break;
    case 0:
       ast_cli(a->fd, "Video Mode:           no video\n");
       break;
    default:
       /* Opps.  We have more than one video mode flag set. */
       ast_assert(0);
       break;
    }
    ast_cli(a->fd,"Video Update Discard: %u\n", b_profile.video_update_discard);
    ast_cli(a->fd,"REMB Send Interval: %u\n", b_profile.remb_send_interval);
    switch (b_profile.flags
       & (BRIDGE_OPT_REMB_BEHAVIOR_AVERAGE | BRIDGE_OPT_REMB_BEHAVIOR_LOWEST
          | BRIDGE_OPT_REMB_BEHAVIOR_HIGHEST | BRIDGE_OPT_REMB_BEHAVIOR_AVERAGE_ALL
          | BRIDGE_OPT_REMB_BEHAVIOR_LOWEST_ALL | BRIDGE_OPT_REMB_BEHAVIOR_LOWEST_ALL)) {
    case BRIDGE_OPT_REMB_BEHAVIOR_AVERAGE:
       ast_cli(a->fd, "REMB Behavior:           average\n");
       break;
    case BRIDGE_OPT_REMB_BEHAVIOR_LOWEST:
       ast_cli(a->fd, "REMB Behavior:           lowest\n");
       break;
    case BRIDGE_OPT_REMB_BEHAVIOR_HIGHEST:
       ast_cli(a->fd, "REMB Behavior:           highest\n");
       break;
    case BRIDGE_OPT_REMB_BEHAVIOR_AVERAGE_ALL:
       ast_cli(a->fd, "REMB Behavior:           average_all\n");
       break;
    case BRIDGE_OPT_REMB_BEHAVIOR_LOWEST_ALL:
       ast_cli(a->fd, "REMB Behavior:           lowest_all\n");
       break;
    case BRIDGE_OPT_REMB_BEHAVIOR_HIGHEST_ALL:
       ast_cli(a->fd, "REMB Behavior:           highest_all\n");
       break;
    default:
       ast_assert(0);
       break;
    }
    ast_cli(a->fd,"Enable Events:             %s\n",
       b_profile.flags & BRIDGE_OPT_ENABLE_EVENTS ?
       "yes" : "no");
    ast_cli(a->fd,"sound_only_person:    %s\n", conf_get_sound(CONF_SOUND_ONLY_PERSON, b_profile.sounds));
    ast_cli(a->fd,"sound_only_one:       %s\n", conf_get_sound(CONF_SOUND_ONLY_ONE, b_profile.sounds));
    ast_cli(a->fd,"sound_has_joined:     %s\n", conf_get_sound(CONF_SOUND_HAS_JOINED, b_profile.sounds));
    ast_cli(a->fd,"sound_has_left:       %s\n", conf_get_sound(CONF_SOUND_HAS_LEFT, b_profile.sounds));
    ast_cli(a->fd,"sound_kicked:         %s\n", conf_get_sound(CONF_SOUND_KICKED, b_profile.sounds));
    ast_cli(a->fd,"sound_muted:          %s\n", conf_get_sound(CONF_SOUND_MUTED, b_profile.sounds));
    ast_cli(a->fd,"sound_unmuted:        %s\n", conf_get_sound(CONF_SOUND_UNMUTED, b_profile.sounds));
    ast_cli(a->fd,"sound_binaural_on:    %s\n", conf_get_sound(CONF_SOUND_BINAURAL_ON, b_profile.sounds));
    ast_cli(a->fd,"sound_binaural_off:   %s\n", conf_get_sound(CONF_SOUND_BINAURAL_OFF, b_profile.sounds));
    ast_cli(a->fd,"sound_there_are:      %s\n", conf_get_sound(CONF_SOUND_THERE_ARE, b_profile.sounds));
    ast_cli(a->fd,"sound_other_in_party: %s\n", conf_get_sound(CONF_SOUND_OTHER_IN_PARTY, b_profile.sounds));
    ast_cli(a->fd,"sound_place_into_conference: %s\n", conf_get_sound(CONF_SOUND_PLACE_IN_CONF, b_profile.sounds));
    ast_cli(a->fd,"sound_wait_for_leader:       %s\n", conf_get_sound(CONF_SOUND_WAIT_FOR_LEADER, b_profile.sounds));
    ast_cli(a->fd,"sound_leader_has_left:       %s\n", conf_get_sound(CONF_SOUND_LEADER_HAS_LEFT, b_profile.sounds));
    ast_cli(a->fd,"sound_get_pin:        %s\n", conf_get_sound(CONF_SOUND_GET_PIN, b_profile.sounds));
    ast_cli(a->fd,"sound_invalid_pin:    %s\n", conf_get_sound(CONF_SOUND_INVALID_PIN, b_profile.sounds));
    ast_cli(a->fd,"sound_locked:         %s\n", conf_get_sound(CONF_SOUND_LOCKED, b_profile.sounds));
    ast_cli(a->fd,"sound_unlocked_now:   %s\n", conf_get_sound(CONF_SOUND_UNLOCKED_NOW, b_profile.sounds));
    ast_cli(a->fd,"sound_lockednow:      %s\n", conf_get_sound(CONF_SOUND_LOCKED_NOW, b_profile.sounds));
    ast_cli(a->fd,"sound_error_menu:     %s\n", conf_get_sound(CONF_SOUND_ERROR_MENU, b_profile.sounds));
    ast_cli(a->fd,"sound_join:           %s\n", conf_get_sound(CONF_SOUND_JOIN, b_profile.sounds));
    ast_cli(a->fd,"sound_leave:          %s\n", conf_get_sound(CONF_SOUND_LEAVE, b_profile.sounds));
    ast_cli(a->fd,"sound_participants_muted:     %s\n", conf_get_sound(CONF_SOUND_PARTICIPANTS_MUTED, b_profile.sounds));
    ast_cli(a->fd,"sound_participants_unmuted:     %s\n", conf_get_sound(CONF_SOUND_PARTICIPANTS_UNMUTED, b_profile.sounds));
    ast_cli(a->fd,"sound_begin:          %s\n", conf_get_sound(CONF_SOUND_BEGIN, b_profile.sounds));
    ast_cli(a->fd,"\n");
    conf_bridge_profile_destroy(&b_profile);
    return CLI_SUCCESS;
 }
handle_cli_confbridge_show_bridge_profiles()
static char* handle_cli_confbridge_show_bridge_profiles (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) static
Definition at line 1653 of file conf_config_parser.c.
References ao2_cleanup, ao2_global_obj_ref, ao2_iterator_destroy(), ao2_iterator_init(), ao2_iterator_next, ao2_lock, ao2_ref, ao2_unlock, ast_cli(), cfg_handle, CLI_GENERATE, CLI_INIT, CLI_SUCCESS, ast_cli_entry::command, ast_cli_args::fd, bridge_profile::name, NULL, RAII_VAR, and ast_cli_entry::usage.
 {
    struct ao2_iterator it;
    struct bridge_profile *b_profile;
    RAII_VAR(struct confbridge_cfg *, cfg, NULL, ao2_cleanup);
    switch (cmd) {
    case CLI_INIT:
       e->command = "confbridge show profile bridges";
       e->usage =
          "Usage: confbridge show profile bridges\n";
       return NULL;
    case CLI_GENERATE:
       return NULL;
    }
    if (!(cfg = ao2_global_obj_ref(cfg_handle))) {
       return NULL;
    }
    ast_cli(a->fd,"--------- Bridge Profiles -----------\n");
    ao2_lock(cfg->bridge_profiles);
    it = ao2_iterator_init(cfg->bridge_profiles, 0);
    while ((b_profile = ao2_iterator_next(&it))) {
       ast_cli(a->fd,"%s\n", b_profile->name);
       ao2_ref(b_profile, -1);
    }
    ao2_iterator_destroy(&it);
    ao2_unlock(cfg->bridge_profiles);
    return CLI_SUCCESS;
 }
handle_cli_confbridge_show_menu()
static char* handle_cli_confbridge_show_menu (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) static
Definition at line 1918 of file conf_config_parser.c.
References conf_menu_entry::actions, ao2_cleanup, ao2_global_obj_ref, ao2_lock, ao2_unlock, ast_cli_args::argc, ast_cli_args::argv, ast_cli(), AST_LIST_TRAVERSE, cfg_handle, CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::command, complete_menu_name(), conf_menu_action::data, conf_menu_action::dialplan_args, conf_menu_entry::dtmf, ast_cli_args::fd, conf_menu_action::id, ast_cli_args::line, MENU_ACTION_ADMIN_KICK_LAST, MENU_ACTION_ADMIN_TOGGLE_LOCK, MENU_ACTION_ADMIN_TOGGLE_MUTE_PARTICIPANTS, MENU_ACTION_DECREASE_LISTENING, MENU_ACTION_DECREASE_TALKING, MENU_ACTION_DIALPLAN_EXEC, MENU_ACTION_INCREASE_LISTENING, MENU_ACTION_INCREASE_TALKING, MENU_ACTION_LEAVE, MENU_ACTION_NOOP, MENU_ACTION_PARTICIPANT_COUNT, MENU_ACTION_PLAYBACK, MENU_ACTION_PLAYBACK_AND_CONTINUE, MENU_ACTION_RELEASE_SINGLE_VIDEO_SRC, MENU_ACTION_RESET_LISTENING, MENU_ACTION_RESET_TALKING, MENU_ACTION_SET_SINGLE_VIDEO_SRC, MENU_ACTION_TOGGLE_BINAURAL, MENU_ACTION_TOGGLE_MUTE, menu_find(), ast_cli_args::n, NULL, conf_menu_action::playback_file, ast_cli_args::pos, RAII_VAR, ast_cli_entry::usage, and ast_cli_args::word.
 {
    RAII_VAR(struct conf_menu *, menu, NULL, ao2_cleanup);
    RAII_VAR(struct confbridge_cfg *, cfg, NULL, ao2_cleanup);
    struct conf_menu_entry *menu_entry = NULL;
    struct conf_menu_action *menu_action = NULL;
    switch (cmd) {
    case CLI_INIT:
       e->command = "confbridge show menu";
       e->usage =
          "Usage: confbridge show menu [<menu name>]\n";
       return NULL;
    case CLI_GENERATE:
       if (a->pos == 3) {
          return complete_menu_name(a->line, a->word, a->pos, a->n);
       }
       return NULL;
    }
    if (a->argc != 4) {
       return CLI_SHOWUSAGE;
    }
    if (!(cfg = ao2_global_obj_ref(cfg_handle))) {
       return NULL;
    }
    if (!(menu = menu_find(cfg->menus, a->argv[3]))) {
       ast_cli(a->fd, "No conference menu named '%s' found!\n", a->argv[3]);
       return CLI_SUCCESS;
    }
    ao2_lock(menu);
    ast_cli(a->fd,"Name: %s\n", menu->name);
    AST_LIST_TRAVERSE(&menu->entries, menu_entry, entry) {
       int action_num = 0;
       ast_cli(a->fd, "%s=", menu_entry->dtmf);
       AST_LIST_TRAVERSE(&menu_entry->actions, menu_action, action) {
          if (action_num) {
             ast_cli(a->fd, ", ");
          }
          switch (menu_action->id) {
          case MENU_ACTION_TOGGLE_MUTE:
             ast_cli(a->fd, "toggle_mute");
             break;
          case MENU_ACTION_TOGGLE_BINAURAL:
             ast_cli(a->fd, "toggle_binaural");
             break;
          case MENU_ACTION_NOOP:
             ast_cli(a->fd, "no_op");
             break;
          case MENU_ACTION_INCREASE_LISTENING:
             ast_cli(a->fd, "increase_listening_volume");
             break;
          case MENU_ACTION_DECREASE_LISTENING:
             ast_cli(a->fd, "decrease_listening_volume");
             break;
          case MENU_ACTION_RESET_LISTENING:
             ast_cli(a->fd, "reset_listening_volume");
             break;
          case MENU_ACTION_RESET_TALKING:
             ast_cli(a->fd, "reset_talking_volume");
             break;
          case MENU_ACTION_INCREASE_TALKING:
             ast_cli(a->fd, "increase_talking_volume");
             break;
          case MENU_ACTION_DECREASE_TALKING:
             ast_cli(a->fd, "decrease_talking_volume");
             break;
          case MENU_ACTION_PLAYBACK:
             ast_cli(a->fd, "playback(%s)", menu_action->data.playback_file);
             break;
          case MENU_ACTION_PLAYBACK_AND_CONTINUE:
             ast_cli(a->fd, "playback_and_continue(%s)", menu_action->data.playback_file);
             break;
          case MENU_ACTION_DIALPLAN_EXEC:
             ast_cli(a->fd, "dialplan_exec(%s,%s,%d)",
                menu_action->data.dialplan_args.context,
                menu_action->data.dialplan_args.exten,
                menu_action->data.dialplan_args.priority);
             break;
          case MENU_ACTION_ADMIN_TOGGLE_LOCK:
             ast_cli(a->fd, "admin_toggle_conference_lock");
             break;
          case MENU_ACTION_ADMIN_TOGGLE_MUTE_PARTICIPANTS:
             ast_cli(a->fd, "admin_toggle_mute_participants");
             break;
          case MENU_ACTION_PARTICIPANT_COUNT:
             ast_cli(a->fd, "participant_count");
             break;
          case MENU_ACTION_ADMIN_KICK_LAST:
             ast_cli(a->fd, "admin_kick_last");
             break;
          case MENU_ACTION_LEAVE:
             ast_cli(a->fd, "leave_conference");
             break;
          case MENU_ACTION_SET_SINGLE_VIDEO_SRC:
             ast_cli(a->fd, "set_as_single_video_src");
             break;
          case MENU_ACTION_RELEASE_SINGLE_VIDEO_SRC:
             ast_cli(a->fd, "release_as_single_video_src");
             break;
          }
          action_num++;
       }
       ast_cli(a->fd,"\n");
    }
    ao2_unlock(menu);
    return CLI_SUCCESS;
 }
handle_cli_confbridge_show_menus()
static char* handle_cli_confbridge_show_menus (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) static
Definition at line 1885 of file conf_config_parser.c.
References ao2_cleanup, ao2_global_obj_ref, ao2_iterator_destroy(), ao2_iterator_init(), ao2_iterator_next, ao2_lock, ao2_ref, ao2_unlock, ast_cli(), cfg_handle, CLI_GENERATE, CLI_INIT, CLI_SUCCESS, ast_cli_entry::command, ast_cli_args::fd, conf_menu::name, NULL, RAII_VAR, and ast_cli_entry::usage.
 {
    struct ao2_iterator it;
    struct conf_menu *menu;
    RAII_VAR(struct confbridge_cfg *, cfg, NULL, ao2_cleanup);
    switch (cmd) {
    case CLI_INIT:
       e->command = "confbridge show menus";
       e->usage =
          "Usage: confbridge show profile menus\n";
       return NULL;
    case CLI_GENERATE:
       return NULL;
    }
    if (!(cfg = ao2_global_obj_ref(cfg_handle))) {
       return NULL;
    }
    ast_cli(a->fd,"--------- Menus -----------\n");
    ao2_lock(cfg->menus);
    it = ao2_iterator_init(cfg->menus, 0);
    while ((menu = ao2_iterator_next(&it))) {
       ast_cli(a->fd,"%s\n", menu->name);
       ao2_ref(menu, -1);
    }
    ao2_iterator_destroy(&it);
    ao2_unlock(cfg->menus);
    return CLI_SUCCESS;
 }
handle_cli_confbridge_show_user_profile()
static char* handle_cli_confbridge_show_user_profile (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) static
Definition at line 1522 of file conf_config_parser.c.
References user_profile::announcement, ast_cli_args::argc, ast_cli_args::argv, ast_cli(), ast_strlen_zero, CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::command, complete_user_profile_name(), conf_find_user_profile(), ast_cli_args::fd, user_profile::flags, ast_cli_args::line, user_profile::moh_class, ast_cli_args::n, user_profile::name, NULL, user_profile::pin, ast_cli_args::pos, user_profile::silence_threshold, user_profile::talking_threshold, ast_cli_entry::usage, USER_OPT_ADMIN, USER_OPT_ANNOUNCE_JOIN_LEAVE, USER_OPT_ANNOUNCE_JOIN_LEAVE_REVIEW, USER_OPT_ANNOUNCEUSERCOUNT, USER_OPT_ANNOUNCEUSERCOUNTALL, USER_OPT_ANSWER_CHANNEL, USER_OPT_DENOISE, USER_OPT_DROP_SILENCE, USER_OPT_DTMF_PASS, USER_OPT_ECHO_EVENTS, USER_OPT_ENDMARKED, USER_OPT_JITTERBUFFER, USER_OPT_MARKEDUSER, USER_OPT_MUSICONHOLD, USER_OPT_QUIET, USER_OPT_SEND_EVENTS, USER_OPT_STARTMUTED, USER_OPT_TALKER_DETECT, USER_OPT_TEXT_MESSAGING, USER_OPT_WAITMARKED, and ast_cli_args::word.
 {
    struct user_profile u_profile;
    switch (cmd) {
    case CLI_INIT:
       e->command = "confbridge show profile user";
       e->usage =
          "Usage: confbridge show profile user [<profile name>]\n";
       return NULL;
    case CLI_GENERATE:
       if (a->pos == 4) {
          return complete_user_profile_name(a->line, a->word, a->pos, a->n);
       }
       return NULL;
    }
    if (a->argc != 5) {
       return CLI_SHOWUSAGE;
    }
    if (!(conf_find_user_profile(NULL, a->argv[4], &u_profile))) {
       ast_cli(a->fd, "No conference user profile named '%s' found!\n", a->argv[4]);
       return CLI_SUCCESS;
    }
    ast_cli(a->fd,"--------------------------------------------\n");
    ast_cli(a->fd,"Name:                    %s\n",
       u_profile.name);
    ast_cli(a->fd,"Admin:                   %s\n",
       u_profile.flags & USER_OPT_ADMIN ?
       "true" : "false");
    ast_cli(a->fd,"Send Events:             %s\n",
       u_profile.flags & USER_OPT_SEND_EVENTS ?
       "true" : "false");
    ast_cli(a->fd,"Echo Events:             %s\n",
       u_profile.flags & USER_OPT_ECHO_EVENTS ?
       "true" : "false");
    ast_cli(a->fd,"Marked User:             %s\n",
       u_profile.flags & USER_OPT_MARKEDUSER ?
       "true" : "false");
    ast_cli(a->fd,"Start Muted:             %s\n",
       u_profile.flags & USER_OPT_STARTMUTED?
       "true" : "false");
    ast_cli(a->fd,"MOH When Empty:          %s\n",
       u_profile.flags & USER_OPT_MUSICONHOLD ?
       "enabled" : "disabled");
    ast_cli(a->fd,"MOH Class:               %s\n",
       ast_strlen_zero(u_profile.moh_class) ?
       "default" : u_profile.moh_class);
    ast_cli(a->fd,"Announcement:            %s\n",
       u_profile.announcement);
    ast_cli(a->fd,"Quiet:                   %s\n",
       u_profile.flags & USER_OPT_QUIET ?
       "enabled" : "disabled");
    ast_cli(a->fd,"Wait Marked:             %s\n",
       u_profile.flags & USER_OPT_WAITMARKED ?
       "enabled" : "disabled");
    ast_cli(a->fd,"END Marked:              %s\n",
       u_profile.flags & USER_OPT_ENDMARKED ?
       "enabled" : "disabled");
    ast_cli(a->fd,"Drop_silence:            %s\n",
       u_profile.flags & USER_OPT_DROP_SILENCE ?
       "enabled" : "disabled");
    ast_cli(a->fd,"Silence Threshold:       %ums\n",
       u_profile.silence_threshold);
    ast_cli(a->fd,"Talking Threshold:       %u\n",
       u_profile.talking_threshold);
    ast_cli(a->fd,"Denoise:                 %s\n",
       u_profile.flags & USER_OPT_DENOISE ?
       "enabled" : "disabled");
    ast_cli(a->fd,"Jitterbuffer:            %s\n",
       u_profile.flags & USER_OPT_JITTERBUFFER ?
       "enabled" : "disabled");
    ast_cli(a->fd,"Talk Detect Events:      %s\n",
       u_profile.flags & USER_OPT_TALKER_DETECT ?
       "enabled" : "disabled");
    ast_cli(a->fd,"DTMF Pass Through:       %s\n",
       u_profile.flags & USER_OPT_DTMF_PASS ?
       "enabled" : "disabled");
    ast_cli(a->fd,"PIN:                     %s\n",
       ast_strlen_zero(u_profile.pin) ?
       "None" : u_profile.pin);
    ast_cli(a->fd,"Announce User Count:     %s\n",
       u_profile.flags & USER_OPT_ANNOUNCEUSERCOUNT ?
       "enabled" : "disabled");
    ast_cli(a->fd,"Announce join/leave:     %s\n",
       u_profile.flags & (USER_OPT_ANNOUNCE_JOIN_LEAVE | USER_OPT_ANNOUNCE_JOIN_LEAVE_REVIEW) ?
       u_profile.flags & USER_OPT_ANNOUNCE_JOIN_LEAVE_REVIEW ?
       "enabled (with review)" : "enabled" : "disabled");
    ast_cli(a->fd,"Announce User Count all: %s\n",
       u_profile.flags & USER_OPT_ANNOUNCEUSERCOUNTALL ?
       "enabled" : "disabled");
    ast_cli(a->fd,"Text Messaging:          %s\n",
          u_profile.flags & USER_OPT_TEXT_MESSAGING ?
          "enabled" : "disabled");
    ast_cli(a->fd,"Answer Channel:          %s\n",
          u_profile.flags & USER_OPT_ANSWER_CHANNEL ?
          "true" : "false");
    ast_cli(a->fd, "\n");
    return CLI_SUCCESS;
 }
handle_cli_confbridge_show_user_profiles()
static char* handle_cli_confbridge_show_user_profiles (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) static
Definition at line 1490 of file conf_config_parser.c.
References ao2_cleanup, ao2_global_obj_ref, ao2_iterator_destroy(), ao2_iterator_init(), ao2_iterator_next, ao2_lock, ao2_ref, ao2_unlock, ast_cli(), cfg_handle, CLI_GENERATE, CLI_INIT, CLI_SUCCESS, ast_cli_entry::command, ast_cli_args::fd, user_profile::name, NULL, RAII_VAR, and ast_cli_entry::usage.
 {
    struct ao2_iterator it;
    struct user_profile *u_profile;
    RAII_VAR(struct confbridge_cfg *, cfg, NULL, ao2_cleanup);
    switch (cmd) {
    case CLI_INIT:
       e->command = "confbridge show profile users";
       e->usage =
          "Usage: confbridge show profile users\n";
       return NULL;
    case CLI_GENERATE:
       return NULL;
    }
    if (!(cfg = ao2_global_obj_ref(cfg_handle))) {
       return NULL;
    }
    ast_cli(a->fd,"--------- User Profiles -----------\n");
    ao2_lock(cfg->user_profiles);
    it = ao2_iterator_init(cfg->user_profiles, 0);
    while ((u_profile = ao2_iterator_next(&it))) {
       ast_cli(a->fd,"%s\n", u_profile->name);
       ao2_ref(u_profile, -1);
    }
    ao2_iterator_destroy(&it);
    ao2_unlock(cfg->user_profiles);
    return CLI_SUCCESS;
 }
menu_alloc()
static void * menu_alloc (const char * category) static
Definition at line 792 of file conf_config_parser.c.
References ao2_alloc, ast_copy_string(), menu_destructor(), conf_menu::name, and NULL.
Referenced by func_confbridge_helper(), and verify_default_profiles().
 {
    struct conf_menu *menu;
    if (!(menu = ao2_alloc(sizeof(*menu), menu_destructor))) {
       return NULL;
    }
    ast_copy_string(menu->name, category, sizeof(menu->name));
    return menu;
 }
menu_cmp_cb()
static int menu_cmp_cb (void * obj, void * arg, int flags) static
menu container functions
Definition at line 893 of file conf_config_parser.c.
References CMP_MATCH, conf_menu::name, OBJ_KEY, OBJ_PARTIAL_KEY, and OBJ_POINTER.
Referenced by confbridge_cfg_alloc().
 {
    const struct conf_menu *left = obj;
    const struct conf_menu *right = arg;
    const char *right_name = arg;
    int cmp;
    switch (flags & (OBJ_POINTER | OBJ_KEY | OBJ_PARTIAL_KEY)) {
    default:
    case OBJ_POINTER:
       right_name = right->name;
       /* Fall through */
    case OBJ_KEY:
       cmp = strcasecmp(left->name, right_name);
       break;
    case OBJ_PARTIAL_KEY:
       cmp = strncasecmp(left->name, right_name, strlen(right_name));
       break;
    }
    return cmp ? 0 : CMP_MATCH;
 }
menu_destructor()
static void menu_destructor (void * obj) static
Definition at line 938 of file conf_config_parser.c.
References ast_free, AST_LIST_REMOVE_HEAD, conf_menu_entry_destroy(), conf_menu::entries, and NULL.
Referenced by menu_alloc().
 {
    struct conf_menu *menu = obj;
    struct conf_menu_entry *entry = NULL;
    while ((entry = AST_LIST_REMOVE_HEAD(&menu->entries, entry))) {
       conf_menu_entry_destroy(entry);
       ast_free(entry);
    }
 }
menu_find()
static void * menu_find (struct ao2_container * container, const char * category) static
Definition at line 802 of file conf_config_parser.c.
References ao2_find, and OBJ_KEY.
Referenced by handle_cli_confbridge_show_menu().
 {
    return ao2_find(container, category, OBJ_KEY);
 }
menu_hash_cb()
static int menu_hash_cb (const void * obj, const int flags) static
Definition at line 915 of file conf_config_parser.c.
References ast_assert, ast_str_case_hash(), name, conf_menu::name, OBJ_KEY, OBJ_PARTIAL_KEY, and OBJ_POINTER.
Referenced by confbridge_cfg_alloc().
 {
    const struct conf_menu *menu = obj;
    const char *name = obj;
    int hash;
    switch (flags & (OBJ_POINTER | OBJ_KEY | OBJ_PARTIAL_KEY)) {
    default:
    case OBJ_POINTER:
       name = menu->name;
       /* Fall through */
    case OBJ_KEY:
       hash = ast_str_case_hash(name);
       break;
    case OBJ_PARTIAL_KEY:
       /* Should never happen in hash callback. */
       ast_assert(0);
       hash = 0;
       break;
    }
    return hash;
 }
menu_hook_callback()
static int menu_hook_callback (struct ast_bridge_channel * bridge_channel, void * hook_pvt) static
Definition at line 2595 of file conf_config_parser.c.
References conf_handle_dtmf(), dtmf_menu_hook_pvt::menu, dtmf_menu_hook_pvt::menu_entry, and dtmf_menu_hook_pvt::user.
Referenced by apply_menu_to_user().
 {
    struct dtmf_menu_hook_pvt *pvt = hook_pvt;
    return conf_handle_dtmf(bridge_channel, pvt->user, &pvt->menu_entry, pvt->menu);
 }
menu_hook_destroy()
static void menu_hook_destroy (void * hook_pvt) static
Definition at line 2582 of file conf_config_parser.c.
References conf_menu_entry::actions, ao2_cleanup, ast_free, AST_LIST_REMOVE_HEAD, dtmf_menu_hook_pvt::menu, dtmf_menu_hook_pvt::menu_entry, and NULL.
Referenced by apply_menu_to_user().
 {
    struct dtmf_menu_hook_pvt *pvt = hook_pvt;
    struct conf_menu_action *action = NULL;
    ao2_cleanup(pvt->menu);
    while ((action = AST_LIST_REMOVE_HEAD(&pvt->menu_entry.actions, action))) {
       ast_free(action);
    }
    ast_free(pvt);
 }
menu_option_handler()
static int menu_option_handler (const struct aco_option * opt, struct ast_variable * var, void * obj) static
Definition at line 2330 of file conf_config_parser.c.
References add_menu_entry(), ast_variable::name, and ast_variable::value.
Referenced by conf_load_config().
 {
    add_menu_entry(obj, var->name, var->value);
    return 0;
 }
menu_template_handler()
static int menu_template_handler (const struct aco_option * opt, struct ast_variable * var, void * obj) static
Definition at line 2303 of file conf_config_parser.c.
References ao2_cleanup, ao2_find, ao2_global_obj_ref, cfg_handle, conf_menu_profile_copy(), NULL, OBJ_KEY, RAII_VAR, and ast_variable::value.
Referenced by conf_load_config().
 {
    struct conf_menu *dst_menu = obj;
    RAII_VAR(struct confbridge_cfg *, cfg, ao2_global_obj_ref(cfg_handle), ao2_cleanup);
    RAII_VAR(struct conf_menu *, src_menu, NULL, ao2_cleanup);
    if (!cfg) {
       return 0;
    }
    if (!(src_menu = ao2_find(cfg->menus, var->value, OBJ_KEY))) {
       return -1;
    }
    if (conf_menu_profile_copy(dst_menu, src_menu)) {
       return -1;
    }
    return 0;
 }
mix_interval_handler()
static int mix_interval_handler (const struct aco_option * opt, struct ast_variable * var, void * obj) static
Definition at line 2101 of file conf_config_parser.c.
References bridge_profile::mix_interval, ast_variable::name, and ast_variable::value.
Referenced by conf_load_config().
 {
    struct bridge_profile *b_profile = obj;
    if (strcasecmp(var->name, "mixing_interval")) {
       return -1;
    }
    if (sscanf(var->value, "%30u", &b_profile->mix_interval) != 1) {
       return -1;
    }
    switch (b_profile->mix_interval) {
    case 10:
    case 20:
    case 40:
    case 80:
       return 0;
    default:
       return -1;
    }
 }
remb_behavior_handler()
static int remb_behavior_handler (const struct aco_option * opt, struct ast_variable * var, void * obj) static
Definition at line 2169 of file conf_config_parser.c.
References ast_clear_flag, ast_set_flag, BRIDGE_OPT_REMB_BEHAVIOR_AVERAGE, BRIDGE_OPT_REMB_BEHAVIOR_AVERAGE_ALL, BRIDGE_OPT_REMB_BEHAVIOR_FORCE, BRIDGE_OPT_REMB_BEHAVIOR_HIGHEST, BRIDGE_OPT_REMB_BEHAVIOR_HIGHEST_ALL, BRIDGE_OPT_REMB_BEHAVIOR_LOWEST, BRIDGE_OPT_REMB_BEHAVIOR_LOWEST_ALL, ast_variable::name, and ast_variable::value.
Referenced by conf_load_config().
 {
    struct bridge_profile *b_profile = obj;
    if (strcasecmp(var->name, "remb_behavior")) {
       return -1;
    }
    ast_clear_flag(b_profile, BRIDGE_OPT_REMB_BEHAVIOR_AVERAGE |
       BRIDGE_OPT_REMB_BEHAVIOR_LOWEST |
       BRIDGE_OPT_REMB_BEHAVIOR_HIGHEST |
       BRIDGE_OPT_REMB_BEHAVIOR_AVERAGE_ALL |
       BRIDGE_OPT_REMB_BEHAVIOR_LOWEST_ALL |
       BRIDGE_OPT_REMB_BEHAVIOR_HIGHEST_ALL |
       BRIDGE_OPT_REMB_BEHAVIOR_FORCE
       );
    if (!strcasecmp(var->value, "average")) {
       ast_set_flag(b_profile, BRIDGE_OPT_REMB_BEHAVIOR_AVERAGE);
    } else if (!strcasecmp(var->value, "lowest")) {
       ast_set_flag(b_profile, BRIDGE_OPT_REMB_BEHAVIOR_LOWEST);
    } else if (!strcasecmp(var->value, "highest")) {
       ast_set_flag(b_profile, BRIDGE_OPT_REMB_BEHAVIOR_HIGHEST);
    } else if (!strcasecmp(var->value, "average_all")) {
       ast_set_flag(b_profile, BRIDGE_OPT_REMB_BEHAVIOR_AVERAGE_ALL);
    } else if (!strcasecmp(var->value, "lowest_all")) {
       ast_set_flag(b_profile, BRIDGE_OPT_REMB_BEHAVIOR_LOWEST_ALL);
    } else if (!strcasecmp(var->value, "highest_all")) {
       ast_set_flag(b_profile, BRIDGE_OPT_REMB_BEHAVIOR_HIGHEST_ALL);
    } else if (!strcasecmp(var->value, "force")) {
       ast_set_flag(b_profile, BRIDGE_OPT_REMB_BEHAVIOR_FORCE);
    } else {
       return -1;
    }
    return 0;
 }
set_sound()
static int set_sound (const char * sound_name, const char * sound_file, struct bridge_profile * b_profile) static
Definition at line 1017 of file conf_config_parser.c.
References ast_log, ast_string_field_set, ast_strlen_zero, bridge_profile_sounds::begin, bridge_profile_sounds::binauraloff, bridge_profile_sounds::binauralon, bridge_profile_sounds::errormenu, bridge_profile_sounds::getpin, bridge_profile_sounds::hasjoin, bridge_profile_sounds::hasleft, bridge_profile_sounds::invalidpin, bridge_profile_sounds::join, bridge_profile_sounds::kicked, bridge_profile_sounds::leaderhasleft, leave, bridge_profile_sounds::locked, bridge_profile_sounds::lockednow, LOG_WARNING, muted, bridge_profile_sounds::onlyone, bridge_profile_sounds::onlyperson, bridge_profile_sounds::otherinparty, bridge_profile_sounds::participantsmuted, bridge_profile_sounds::participantsunmuted, bridge_profile_sounds::placeintoconf, sounds, bridge_profile::sounds, bridge_profile_sounds::thereare, bridge_profile_sounds::unlockednow, bridge_profile_sounds::unmuted, and bridge_profile_sounds::waitforleader.
Referenced by sound_option_handler().
 {
    struct bridge_profile_sounds *sounds = b_profile->sounds;
    if (ast_strlen_zero(sound_file)) {
       return -1;
    }
    if (!strcasecmp(sound_name, "sound_only_person")) {
       ast_string_field_set(sounds, onlyperson, sound_file);
    } else if (!strcasecmp(sound_name, "sound_only_one")) {
       ast_string_field_set(sounds, onlyone, sound_file);
    } else if (!strcasecmp(sound_name, "sound_has_joined")) {
       ast_string_field_set(sounds, hasjoin, sound_file);
    } else if (!strcasecmp(sound_name, "sound_has_left")) {
       ast_string_field_set(sounds, hasleft, sound_file);
    } else if (!strcasecmp(sound_name, "sound_kicked")) {
       ast_string_field_set(sounds, kicked, sound_file);
    } else if (!strcasecmp(sound_name, "sound_muted")) {
       ast_string_field_set(sounds, muted, sound_file);
    } else if (!strcasecmp(sound_name, "sound_unmuted")) {
       ast_string_field_set(sounds, unmuted, sound_file);
    } else if (!strcasecmp(sound_name, "sound_binaural_on")) {
       ast_string_field_set(sounds, binauralon, sound_file);
    } else if (!strcasecmp(sound_name, "sound_binaural_off")) {
       ast_string_field_set(sounds, binauraloff, sound_file);
    } else if (!strcasecmp(sound_name, "sound_there_are")) {
       ast_string_field_set(sounds, thereare, sound_file);
    } else if (!strcasecmp(sound_name, "sound_other_in_party")) {
       ast_string_field_set(sounds, otherinparty, sound_file);
    } else if (!strcasecmp(sound_name, "sound_place_into_conference")) {
       static int deprecation_warning = 1;
       if (deprecation_warning) {
          ast_log(LOG_WARNING, "sound_place_into_conference is deprecated"
             " and unused. Use sound_begin for similar functionality.");
          deprecation_warning = 0;
       }
       ast_string_field_set(sounds, placeintoconf, sound_file);
    } else if (!strcasecmp(sound_name, "sound_wait_for_leader")) {
       ast_string_field_set(sounds, waitforleader, sound_file);
    } else if (!strcasecmp(sound_name, "sound_leader_has_left")) {
       ast_string_field_set(sounds, leaderhasleft, sound_file);
    } else if (!strcasecmp(sound_name, "sound_get_pin")) {
       ast_string_field_set(sounds, getpin, sound_file);
    } else if (!strcasecmp(sound_name, "sound_invalid_pin")) {
       ast_string_field_set(sounds, invalidpin, sound_file);
    } else if (!strcasecmp(sound_name, "sound_locked")) {
       ast_string_field_set(sounds, locked, sound_file);
    } else if (!strcasecmp(sound_name, "sound_unlocked_now")) {
       ast_string_field_set(sounds, unlockednow, sound_file);
    } else if (!strcasecmp(sound_name, "sound_locked_now")) {
       ast_string_field_set(sounds, lockednow, sound_file);
    } else if (!strcasecmp(sound_name, "sound_error_menu")) {
       ast_string_field_set(sounds, errormenu, sound_file);
    } else if (!strcasecmp(sound_name, "sound_join")) {
       ast_string_field_set(sounds, join, sound_file);
    } else if (!strcasecmp(sound_name, "sound_leave")) {
       ast_string_field_set(sounds, leave, sound_file);
    } else if (!strcasecmp(sound_name, "sound_participants_muted")) {
       ast_string_field_set(sounds, participantsmuted, sound_file);
    } else if (!strcasecmp(sound_name, "sound_participants_unmuted")) {
       ast_string_field_set(sounds, participantsunmuted, sound_file);
    } else if (!strcasecmp(sound_name, "sound_begin")) {
       ast_string_field_set(sounds, begin, sound_file);
    } else {
       return -1;
    }
    return 0;
 }
sound_option_handler()
static int sound_option_handler (const struct aco_option * opt, struct ast_variable * var, void * obj) static
Definition at line 2324 of file conf_config_parser.c.
References ast_variable::name, set_sound(), and ast_variable::value.
Referenced by conf_load_config().
 {
    set_sound(var->name, var->value, obj);
    return 0;
 }
user_cmp_cb()
static int user_cmp_cb (void * obj, void * arg, int flags) static
User profile container functions
Definition at line 950 of file conf_config_parser.c.
References CMP_MATCH, user_profile::name, OBJ_KEY, OBJ_PARTIAL_KEY, and OBJ_POINTER.
Referenced by confbridge_cfg_alloc().
 {
    const struct user_profile *left = obj;
    const struct user_profile *right = arg;
    const char *right_name = arg;
    int cmp;
    switch (flags & (OBJ_POINTER | OBJ_KEY | OBJ_PARTIAL_KEY)) {
    default:
    case OBJ_POINTER:
       right_name = right->name;
       /* Fall through */
    case OBJ_KEY:
       cmp = strcasecmp(left->name, right_name);
       break;
    case OBJ_PARTIAL_KEY:
       cmp = strncasecmp(left->name, right_name, strlen(right_name));
       break;
    }
    return cmp ? 0 : CMP_MATCH;
 }
user_hash_cb()
static int user_hash_cb (const void * obj, const int flags) static
Definition at line 972 of file conf_config_parser.c.
References ast_assert, ast_str_case_hash(), name, user_profile::name, OBJ_KEY, OBJ_PARTIAL_KEY, and OBJ_POINTER.
Referenced by confbridge_cfg_alloc().
 {
    const struct user_profile *u_profile = obj;
    const char *name = obj;
    int hash;
    switch (flags & (OBJ_POINTER | OBJ_KEY | OBJ_PARTIAL_KEY)) {
    default:
    case OBJ_POINTER:
       name = u_profile->name;
       /* Fall through */
    case OBJ_KEY:
       hash = ast_str_case_hash(name);
       break;
    case OBJ_PARTIAL_KEY:
       /* Should never happen in hash callback. */
       ast_assert(0);
       hash = 0;
       break;
    }
    return hash;
 }
user_profile_alloc()
static void * user_profile_alloc (const char * category) static
Definition at line 758 of file conf_config_parser.c.
References ao2_alloc, ast_copy_string(), user_profile::name, NULL, and user_profile_destructor().
Referenced by verify_default_profiles().
 {
    struct user_profile *u_profile;
    if (!(u_profile = ao2_alloc(sizeof(*u_profile), user_profile_destructor))) {
       return NULL;
    }
    ast_copy_string(u_profile->name, category, sizeof(u_profile->name));
    return u_profile;
 }
user_profile_destructor()
static void user_profile_destructor (void * obj) static
Definition at line 753 of file conf_config_parser.c.
Referenced by func_confbridge_helper(), and user_profile_alloc().
 {
    return;
 }
user_profile_find()
static void * user_profile_find (struct ao2_container * container, const char * category) static
Definition at line 771 of file conf_config_parser.c.
References ao2_find, and OBJ_KEY.
 {
    return ao2_find(container, category, OBJ_KEY);
 }
user_template_handler()
static int user_template_handler (const struct aco_option * opt, struct ast_variable * var, void * obj) static
Definition at line 2206 of file conf_config_parser.c.
References conf_find_user_profile(), NULL, and ast_variable::value.
Referenced by conf_load_config().
 {
    struct user_profile *u_profile = obj;
    return conf_find_user_profile(NULL, var->value, u_profile) ? 0 : -1;
 }
verify_default_profiles()
static int verify_default_profiles (void) static
Definition at line 2336 of file conf_config_parser.c.
References aco_pending_config(), aco_set_defaults(), ao2_cleanup, ao2_find, ao2_link, ast_log, AST_LOG_NOTICE, bridge_profile_alloc(), confbridge_cfg::bridge_profiles, DEFAULT_BRIDGE_PROFILE, DEFAULT_MENU_PROFILE, DEFAULT_USER_PROFILE, menu_alloc(), confbridge_cfg::menus, NULL, OBJ_KEY, RAII_VAR, user_profile_alloc(), and confbridge_cfg::user_profiles.
 {
    RAII_VAR(struct user_profile *, user_profile, NULL, ao2_cleanup);
    RAII_VAR(struct bridge_profile *, bridge_profile, NULL, ao2_cleanup);
    RAII_VAR(struct conf_menu *, menu_profile, NULL, ao2_cleanup);
    /* We can only be called as a result of an aco_process_config so this is safe */
    struct confbridge_cfg *cfg = aco_pending_config(&cfg_info);
    if (!cfg) {
       return 0;
    }
    bridge_profile = ao2_find(cfg->bridge_profiles, DEFAULT_BRIDGE_PROFILE, OBJ_KEY);
    if (!bridge_profile) {
       bridge_profile = bridge_profile_alloc(DEFAULT_BRIDGE_PROFILE);
       if (!bridge_profile) {
          return -1;
       }
       ast_log(AST_LOG_NOTICE, "Adding %s profile to app_confbridge\n", DEFAULT_BRIDGE_PROFILE);
       aco_set_defaults(&bridge_type, DEFAULT_BRIDGE_PROFILE, bridge_profile);
       ao2_link(cfg->bridge_profiles, bridge_profile);
    }
    user_profile = ao2_find(cfg->user_profiles, DEFAULT_USER_PROFILE, OBJ_KEY);
    if (!user_profile) {
       user_profile = user_profile_alloc(DEFAULT_USER_PROFILE);
       if (!user_profile) {
          return -1;
       }
       ast_log(AST_LOG_NOTICE, "Adding %s profile to app_confbridge\n", DEFAULT_USER_PROFILE);
       aco_set_defaults(&user_type, DEFAULT_USER_PROFILE, user_profile);
       ao2_link(cfg->user_profiles, user_profile);
    }
    menu_profile = ao2_find(cfg->menus, DEFAULT_MENU_PROFILE, OBJ_KEY);
    if (!menu_profile) {
       menu_profile = menu_alloc(DEFAULT_MENU_PROFILE);
       if (!menu_profile) {
          return -1;
       }
       ast_log(AST_LOG_NOTICE, "Adding %s menu to app_confbridge\n", DEFAULT_MENU_PROFILE);
       aco_set_defaults(&menu_type, DEFAULT_MENU_PROFILE, menu_profile);
       ao2_link(cfg->menus, menu_profile);
    }
    return 0;
 }
video_mode_handler()
static int video_mode_handler (const struct aco_option * opt, struct ast_variable * var, void * obj) static
Definition at line 2122 of file conf_config_parser.c.
References ast_clear_flag, ast_set_flags_to, BRIDGE_OPT_VIDEO_SRC_FIRST_MARKED, BRIDGE_OPT_VIDEO_SRC_FOLLOW_TALKER, BRIDGE_OPT_VIDEO_SRC_LAST_MARKED, BRIDGE_OPT_VIDEO_SRC_SFU, ast_variable::name, and ast_variable::value.
Referenced by conf_load_config().
 {
    struct bridge_profile *b_profile = obj;
    if (strcasecmp(var->name, "video_mode")) {
       return -1;
    }
    if (!strcasecmp(var->value, "first_marked")) {
       ast_set_flags_to(b_profile,
          BRIDGE_OPT_VIDEO_SRC_FIRST_MARKED
             | BRIDGE_OPT_VIDEO_SRC_LAST_MARKED
             | BRIDGE_OPT_VIDEO_SRC_FOLLOW_TALKER
             | BRIDGE_OPT_VIDEO_SRC_SFU,
          BRIDGE_OPT_VIDEO_SRC_FIRST_MARKED);
    } else if (!strcasecmp(var->value, "last_marked")) {
       ast_set_flags_to(b_profile,
          BRIDGE_OPT_VIDEO_SRC_FIRST_MARKED
             | BRIDGE_OPT_VIDEO_SRC_LAST_MARKED
             | BRIDGE_OPT_VIDEO_SRC_FOLLOW_TALKER
             | BRIDGE_OPT_VIDEO_SRC_SFU,
          BRIDGE_OPT_VIDEO_SRC_LAST_MARKED);
    } else if (!strcasecmp(var->value, "follow_talker")) {
       ast_set_flags_to(b_profile,
          BRIDGE_OPT_VIDEO_SRC_FIRST_MARKED
             | BRIDGE_OPT_VIDEO_SRC_LAST_MARKED
             | BRIDGE_OPT_VIDEO_SRC_FOLLOW_TALKER
             | BRIDGE_OPT_VIDEO_SRC_SFU,
          BRIDGE_OPT_VIDEO_SRC_FOLLOW_TALKER);
    } else if (!strcasecmp(var->value, "sfu")) {
       ast_set_flags_to(b_profile,
          BRIDGE_OPT_VIDEO_SRC_FIRST_MARKED
             | BRIDGE_OPT_VIDEO_SRC_LAST_MARKED
             | BRIDGE_OPT_VIDEO_SRC_FOLLOW_TALKER
             | BRIDGE_OPT_VIDEO_SRC_SFU,
          BRIDGE_OPT_VIDEO_SRC_SFU);
    } else if (!strcasecmp(var->value, "none")) {
       ast_clear_flag(b_profile,
          BRIDGE_OPT_VIDEO_SRC_FIRST_MARKED
             | BRIDGE_OPT_VIDEO_SRC_LAST_MARKED
             | BRIDGE_OPT_VIDEO_SRC_FOLLOW_TALKER
             | BRIDGE_OPT_VIDEO_SRC_SFU);
    } else {
       return -1;
    }
    return 0;
 }
Variable Documentation
bridge_type
struct aco_type bridge_type static
Definition at line 739 of file conf_config_parser.c.
bridge_types
struct aco_type* bridge_types[] = ACO_TYPES(&bridge_type) static
Definition at line 820 of file conf_config_parser.c.
cli_confbridge_parser
struct ast_cli_entry cli_confbridge_parser[] static
Definition at line 2032 of file conf_config_parser.c.
confbridge_conf
struct aco_file confbridge_conf static
Initial value:
= {
   .filename = "confbridge.conf",
   .types = ACO_TYPES(&bridge_type, &user_type, &menu_type, &general_type),
}
Definition at line 832 of file conf_config_parser.c.
confbridge_datastore
const struct ast_datastore_info confbridge_datastore static
Initial value:
= {
   .type = "confbridge",
   .destroy = func_confbridge_destroy_cb
}
Definition at line 1110 of file conf_config_parser.c.
general_type
struct aco_type general_type static
Definition at line 825 of file conf_config_parser.c.
menu_type
struct aco_type menu_type static
Definition at line 807 of file conf_config_parser.c.
menu_types
struct aco_type* menu_types[] = ACO_TYPES(&menu_type) static
Definition at line 821 of file conf_config_parser.c.
user_type
struct aco_type user_type static
Definition at line 776 of file conf_config_parser.c.
user_types
struct aco_type* user_types[] = ACO_TYPES(&user_type) static
Definition at line 822 of file conf_config_parser.c.