Asterisk - The Open Source Telephony Project: pbx_builtins.c File Reference
pbx_builtins.c File Reference
Core PBX builtin routines.
#include "asterisk.h"
#include "asterisk/_private.h"
#include "asterisk/pbx.h"
#include "asterisk/causes.h"
#include "asterisk/indications.h"
#include "asterisk/stasis_channels.h"
#include "asterisk/say.h"
#include "asterisk/app.h"
#include "asterisk/module.h"
#include "pbx_private.h"
Data Structures
struct pbx_builtin
Declaration of builtin applications.
Macros
#define BACKGROUND_MATCHEXTEN (1 << 2)
#define BACKGROUND_NOANSWER (1 << 1)
#define BACKGROUND_PLAYBACK (1 << 3)
#define BACKGROUND_SKIP (1 << 0)
#define WAITEXTEN_DIALTONE (1 << 1)
#define WAITEXTEN_MOH (1 << 0)
Functions
int indicate_busy (struct ast_channel *chan, const char *data)
int indicate_congestion (struct ast_channel *chan, const char *data)
int load_pbx_builtins (void)
static int pbx_builtin_answer (struct ast_channel *chan, const char *data)
static int pbx_builtin_background (struct ast_channel *chan, const char *data)
static int pbx_builtin_execiftime (struct ast_channel *chan, const char *data)
static int pbx_builtin_goto (struct ast_channel *chan, const char *data)
static int pbx_builtin_gotoif (struct ast_channel *chan, const char *data)
static int pbx_builtin_gotoiftime (struct ast_channel *chan, const char *data)
static int pbx_builtin_hangup (struct ast_channel *chan, const char *data)
static int pbx_builtin_importvar (struct ast_channel *chan, const char *data)
static int pbx_builtin_incomplete (struct ast_channel *chan, const char *data)
static int pbx_builtin_noop (struct ast_channel *chan, const char *data)
static int pbx_builtin_proceeding (struct ast_channel *chan, const char *data)
static int pbx_builtin_progress (struct ast_channel *chan, const char *data)
int pbx_builtin_raise_exception (struct ast_channel *chan, const char *reason)
static int pbx_builtin_ringing (struct ast_channel *chan, const char *data)
static int pbx_builtin_saycharacters (struct ast_channel *chan, const char *data)
static int pbx_builtin_saycharacters_case (struct ast_channel *chan, const char *data)
static int pbx_builtin_saydigits (struct ast_channel *chan, const char *data)
static int pbx_builtin_saymoney (struct ast_channel *chan, const char *data)
static int pbx_builtin_saynumber (struct ast_channel *chan, const char *data)
static int pbx_builtin_sayphonetic (struct ast_channel *chan, const char *data)
static int pbx_builtin_setamaflags (struct ast_channel *chan, const char *data)
static int pbx_builtin_wait (struct ast_channel *chan, const char *data)
static int pbx_builtin_waitdigit (struct ast_channel *chan, const char *data)
static int pbx_builtin_waitexten (struct ast_channel *chan, const char *data)
static void unload_pbx_builtins (void)
Variables
static const struct ast_app_option background_opts [128] = { [ 's' ] = { .flag = (1 << 0) }, [ 'n' ] = { .flag = (1 << 1) }, [ 'm' ] = { .flag = (1 << 2) }, [ 'p' ] = { .flag = (1 << 3) }, }
struct pbx_builtin builtins []
static const struct ast_app_option waitexten_opts [128] = { [ 'm' ] = { .flag = (1 << 0) , .arg_index = 0 + 1 }, [ 'd' ] = { .flag = (1 << 1) , .arg_index = 0 + 1 }, }
Detailed Description
Core PBX builtin routines.
Author
George Joseph georg.nosp@m.e.jo.nosp@m.seph@.nosp@m.fair.nosp@m.view5.nosp@m..com
Definition in file pbx_builtins.c.
Macro Definition Documentation
BACKGROUND_MATCHEXTEN
#define BACKGROUND_MATCHEXTEN (1 << 2)
Definition at line 685 of file pbx_builtins.c.
Referenced by pbx_builtin_background().
BACKGROUND_NOANSWER
#define BACKGROUND_NOANSWER (1 << 1)
Definition at line 684 of file pbx_builtins.c.
Referenced by pbx_builtin_background().
BACKGROUND_PLAYBACK
#define BACKGROUND_PLAYBACK (1 << 3)
Definition at line 686 of file pbx_builtins.c.
Referenced by pbx_builtin_background().
BACKGROUND_SKIP
#define BACKGROUND_SKIP (1 << 0)
Definition at line 683 of file pbx_builtins.c.
Referenced by pbx_builtin_background().
WAITEXTEN_DIALTONE
#define WAITEXTEN_DIALTONE (1 << 1)
Definition at line 696 of file pbx_builtins.c.
Referenced by pbx_builtin_waitexten().
WAITEXTEN_MOH
#define WAITEXTEN_MOH (1 << 0)
Definition at line 695 of file pbx_builtins.c.
Referenced by pbx_builtin_waitexten().
Function Documentation
load_pbx_builtins()
int load_pbx_builtins (void)
Provided by pbx_builtins.c
Definition at line 1556 of file pbx_builtins.c.
References ARRAY_LEN, ast_log, ast_register_application2(), ast_register_cleanup(), builtins, pbx_builtin::execute, LOG_ERROR, pbx_builtin::name, NULL, unload_pbx_builtins(), and ast_channel::x.
Referenced by asterisk_daemon().
 {
    int x;
    /* Register builtin applications */
    for (x = 0; x < ARRAY_LEN(builtins); x++) {
       if (ast_register_application2(builtins[x].name, builtins[x].execute, NULL, NULL, NULL)) {
          ast_log(LOG_ERROR, "Unable to register builtin application '%s'\n", builtins[x].name);
          return -1;
       }
    }
    ast_register_cleanup(unload_pbx_builtins);
    return 0;
 }
pbx_builtin_gotoif()
static int pbx_builtin_gotoif (struct ast_channel * chan, const char * data) static
Definition at line 1269 of file pbx_builtins.c.
References ast_debug, ast_log, ast_strdupa, ast_strlen_zero, LOG_WARNING, pbx_builtin_goto(), pbx_checkcondition(), and strsep().
 {
    char *condition, *branch1, *branch2, *branch;
    char *stringp;
    if (ast_strlen_zero(data)) {
       ast_log(LOG_WARNING, "Ignoring, since there is no variable to check\n");
       return 0;
    }
    stringp = ast_strdupa(data);
    condition = strsep(&stringp,"?");
    branch1 = strsep(&stringp,":");
    branch2 = strsep(&stringp,"");
    branch = pbx_checkcondition(condition) ? branch1 : branch2;
    if (ast_strlen_zero(branch)) {
       ast_debug(1, "Not taking any branch\n");
       return 0;
    }
    return pbx_builtin_goto(chan, branch);
 }
pbx_builtin_importvar()
static int pbx_builtin_importvar (struct ast_channel * chan, const char * data) static
Todo:
XXX should do !ast_strlen_zero(..) of the args ?
Definition at line 1474 of file pbx_builtins.c.
References ast_alloca, ast_channel_get_by_name(), ast_channel_unref, ast_log, ast_strdupa, ast_strlen_zero, LOG_WARNING, name, pbx_builtin_setvar_helper(), pbx_substitute_variables_helper(), strsep(), tmp(), value, and VAR_BUF_SIZE.
 {
    char *name;
    char *value;
    char *channel;
    char tmp[VAR_BUF_SIZE];
    static int deprecation_warning = 0;
    if (ast_strlen_zero(data)) {
       ast_log(LOG_WARNING, "Ignoring, since there is no variable to set\n");
       return 0;
    }
    tmp[0] = 0;
    if (!deprecation_warning) {
       ast_log(LOG_WARNING, "ImportVar is deprecated.  Please use Set(varname=${IMPORT(channel,variable)}) instead.\n");
       deprecation_warning = 1;
    }
    value = ast_strdupa(data);
    name = strsep(&value,"=");
    channel = strsep(&value,",");
    if (channel && value && name) { /*! \todo XXX should do !ast_strlen_zero(..) of the args ? */
       struct ast_channel *chan2 = ast_channel_get_by_name(channel);
       if (chan2) {
          char *s = ast_alloca(strlen(value) + 4);
          sprintf(s, "${%s}", value);
          pbx_substitute_variables_helper(chan2, s, tmp, sizeof(tmp) - 1);
          chan2 = ast_channel_unref(chan2);
       }
       pbx_builtin_setvar_helper(chan, name, tmp);
    }
    return(0);
 }
pbx_builtin_incomplete()
static int pbx_builtin_incomplete (struct ast_channel * chan, const char * data) static
Definition at line 806 of file pbx_builtins.c.
References __ast_answer(), answer(), ast_check_hangup(), AST_CONTROL_INCOMPLETE, ast_indicate(), AST_PBX_INCOMPLETE, AST_STATE_UP, ast_strlen_zero, and options.
 {
    const char *options = data;
    int answer = 1;
    /* Some channels can receive DTMF in unanswered state; some cannot */
    if (!ast_strlen_zero(options) && strchr(options, 'n')) {
       answer = 0;
    }
    /* If the channel is hungup, stop waiting */
    if (ast_check_hangup(chan)) {
       return -1;
    } else if (ast_channel_state(chan) != AST_STATE_UP && answer) {
       __ast_answer(chan, 0);
    }
    ast_indicate(chan, AST_CONTROL_INCOMPLETE);
    return AST_PBX_INCOMPLETE;
 }
pbx_builtin_noop()
static int pbx_builtin_noop (struct ast_channel * chan, const char * data) static
Definition at line 1264 of file pbx_builtins.c.
 {
    return 0;
 }
pbx_builtin_raise_exception()
int pbx_builtin_raise_exception (struct ast_channel * chan, const char * reason)
Definition at line 703 of file pbx_builtins.c.
References raise_exception().
 {
    /* Priority will become 1, next time through the AUTOLOOP */
    return raise_exception(chan, reason, 0);
 }
pbx_builtin_saycharacters()
static int pbx_builtin_saycharacters (struct ast_channel * chan, const char * data) static
Definition at line 1436 of file pbx_builtins.c.
References ast_channel_language(), ast_channel_lock, ast_channel_unlock, AST_DIGIT_ANY, AST_SAY_CASE_NONE, ast_say_character_str(), ast_true(), and pbx_builtin_getvar_helper().
 {
    int res = 0;
    int interrupt = 0;
    const char *interrupt_string;
    ast_channel_lock(chan);
    interrupt_string = pbx_builtin_getvar_helper(chan, "SAY_DTMF_INTERRUPT");
    if (ast_true(interrupt_string)) {
       interrupt = 1;
    }
    ast_channel_unlock(chan);
    if (data) {
       res = ast_say_character_str(chan, data, interrupt ? AST_DIGIT_ANY : "", ast_channel_language(chan), AST_SAY_CASE_NONE);
    }
    return res;
 }
pbx_builtin_saycharacters_case()
static int pbx_builtin_saycharacters_case (struct ast_channel * chan, const char * data) static
Definition at line 1380 of file pbx_builtins.c.
References args, AST_APP_ARG, ast_channel_language(), ast_channel_lock, ast_channel_unlock, AST_DECLARE_APP_ARGS, AST_DIGIT_ANY, ast_log, AST_SAY_CASE_ALL, AST_SAY_CASE_LOWER, AST_SAY_CASE_NONE, AST_SAY_CASE_UPPER, ast_say_character_str(), AST_STANDARD_APP_ARGS, ast_strdupa, ast_strlen_zero, ast_true(), LOG_WARNING, options, parse(), and pbx_builtin_getvar_helper().
 {
    int res = 0;
    int sensitivity = 0;
    char *parse;
    int interrupt = 0;
    const char *interrupt_string;
    AST_DECLARE_APP_ARGS(args,
       AST_APP_ARG(options);
       AST_APP_ARG(characters);
    );
    ast_channel_lock(chan);
    interrupt_string = pbx_builtin_getvar_helper(chan, "SAY_DTMF_INTERRUPT");
    if (ast_true(interrupt_string)) {
       interrupt = 1;
    }
    ast_channel_unlock(chan);
    if (ast_strlen_zero(data)) {
       ast_log(LOG_WARNING, "SayAlphaCase requires two arguments (options, characters)\n");
       return 0;
    }
    parse = ast_strdupa(data);
    AST_STANDARD_APP_ARGS(args, parse);
    if (!args.options || strlen(args.options) != 1) {
       ast_log(LOG_WARNING, "SayAlphaCase options are mutually exclusive and required\n");
       return 0;
    }
    switch (args.options[0]) {
    case 'a':
       sensitivity = AST_SAY_CASE_ALL;
       break;
    case 'l':
       sensitivity = AST_SAY_CASE_LOWER;
       break;
    case 'n':
       sensitivity = AST_SAY_CASE_NONE;
       break;
    case 'u':
       sensitivity = AST_SAY_CASE_UPPER;
       break;
    default:
       ast_log(LOG_WARNING, "Invalid option: '%s'\n", args.options);
       return 0;
    }
    res = ast_say_character_str(chan, args.characters, interrupt ? AST_DIGIT_ANY : "", ast_channel_language(chan), sensitivity);
    return res;
 }
pbx_builtin_saydigits()
static int pbx_builtin_saydigits (struct ast_channel * chan, const char * data) static
Definition at line 1340 of file pbx_builtins.c.
References ast_channel_language(), ast_channel_lock, ast_channel_unlock, AST_DIGIT_ANY, ast_say_digit_str(), ast_true(), and pbx_builtin_getvar_helper().
 {
    int res = 0;
    int interrupt = 0;
    const char *interrupt_string;
    ast_channel_lock(chan);
    interrupt_string = pbx_builtin_getvar_helper(chan, "SAY_DTMF_INTERRUPT");
    if (ast_true(interrupt_string)) {
       interrupt = 1;
    }
    ast_channel_unlock(chan);
    if (data) {
       res = ast_say_digit_str(chan, data, interrupt ? AST_DIGIT_ANY : "", ast_channel_language(chan));
    }
    return res;
 }
pbx_builtin_saymoney()
static int pbx_builtin_saymoney (struct ast_channel * chan, const char * data) static
Definition at line 1360 of file pbx_builtins.c.
References ast_channel_language(), ast_channel_lock, ast_channel_unlock, AST_DIGIT_ANY, ast_say_money_str(), ast_true(), and pbx_builtin_getvar_helper().
 {
    int res = 0;
    int interrupt = 0;
    const char *interrupt_string;
    ast_channel_lock(chan);
    interrupt_string = pbx_builtin_getvar_helper(chan, "SAY_DTMF_INTERRUPT");
    if (ast_true(interrupt_string)) {
       interrupt = 1;
    }
    ast_channel_unlock(chan);
    if (data) {
       res = ast_say_money_str(chan, data, interrupt ? AST_DIGIT_ANY : "", ast_channel_language(chan));
    }
    return res;
 }
pbx_builtin_saynumber()
static int pbx_builtin_saynumber (struct ast_channel * chan, const char * data) static
Definition at line 1293 of file pbx_builtins.c.
References ast_channel_language(), ast_channel_lock, ast_channel_unlock, ast_check_hangup_locked(), ast_copy_string(), AST_DIGIT_ANY, ast_log, ast_say_number(), ast_strlen_zero, ast_true(), LOG_WARNING, options, pbx_builtin_getvar_helper(), strsep(), and tmp().
 {
    char tmp[256];
    char *number = tmp;
    int number_val;
    char *options;
    int res;
    int interrupt = 0;
    const char *interrupt_string;
    ast_channel_lock(chan);
    interrupt_string = pbx_builtin_getvar_helper(chan, "SAY_DTMF_INTERRUPT");
    if (ast_true(interrupt_string)) {
       interrupt = 1;
    }
    ast_channel_unlock(chan);
    if (ast_strlen_zero(data)) {
       ast_log(LOG_WARNING, "SayNumber requires an argument (number)\n");
       return -1;
    }
    ast_copy_string(tmp, data, sizeof(tmp));
    strsep(&number, ",");
    if (sscanf(tmp, "%d", &number_val) != 1) {
       ast_log(LOG_WARNING, "argument '%s' to SayNumber could not be parsed as a number.\n", tmp);
       return 0;
    }
    options = strsep(&number, ",");
    if (options) {
       if ( strcasecmp(options, "f") && strcasecmp(options, "m") &&
          strcasecmp(options, "c") && strcasecmp(options, "n") ) {
          ast_log(LOG_WARNING, "SayNumber gender option is either 'f', 'm', 'c' or 'n'\n");
          return -1;
       }
    }
    res = ast_say_number(chan, number_val, interrupt ? AST_DIGIT_ANY : "", ast_channel_language(chan), options);
    if (res < 0 && !ast_check_hangup_locked(chan)) {
       ast_log(LOG_WARNING, "We were unable to say the number %s, is it too large?\n", tmp);
    }
    return interrupt ? res : 0;
 }
pbx_builtin_sayphonetic()
static int pbx_builtin_sayphonetic (struct ast_channel * chan, const char * data) static
Definition at line 1456 of file pbx_builtins.c.
References ast_channel_language(), ast_channel_lock, ast_channel_unlock, AST_DIGIT_ANY, ast_say_phonetic_str(), ast_true(), and pbx_builtin_getvar_helper().
 {
    int res = 0;
    int interrupt = 0;
    const char *interrupt_string;
    ast_channel_lock(chan);
    interrupt_string = pbx_builtin_getvar_helper(chan, "SAY_DTMF_INTERRUPT");
    if (ast_true(interrupt_string)) {
       interrupt = 1;
    }
    ast_channel_unlock(chan);
    if (data)
       res = ast_say_phonetic_str(chan, data, interrupt ? AST_DIGIT_ANY : "", ast_channel_language(chan));
    return res;
 }
unload_pbx_builtins()
static void unload_pbx_builtins (void) static
Definition at line 1546 of file pbx_builtins.c.
References ARRAY_LEN, ast_unregister_application(), builtins, pbx_builtin::name, and ast_channel::x.
Referenced by load_pbx_builtins().
 {
    int x;
    /* Unregister builtin applications */
    for (x = 0; x < ARRAY_LEN(builtins); x++) {
       ast_unregister_application(builtins[x].name);
    }
 }
Variable Documentation
background_opts
const struct ast_app_option background_opts[128] = { [ 's' ] = { .flag = (1 << 0) }, [ 'n' ] = { .flag = (1 << 1) }, [ 'm' ] = { .flag = (1 << 2) }, [ 'p' ] = { .flag = (1 << 3) }, } static
Definition at line 693 of file pbx_builtins.c.
Referenced by pbx_builtin_background().
builtins
struct pbx_builtin builtins[]
Referenced by load_pbx_builtins(), and unload_pbx_builtins().
waitexten_opts
const struct ast_app_option waitexten_opts[128] = { [ 'm' ] = { .flag = (1 << 0) , .arg_index = 0 + 1 }, [ 'd' ] = { .flag = (1 << 1) , .arg_index = 0 + 1 }, } static
Definition at line 701 of file pbx_builtins.c.
Referenced by pbx_builtin_waitexten().