Asterisk - The Open Source Telephony Project: app_image.c File Reference
app_image.c File Reference
Dial plan applications
App to transmit an image.
#include "asterisk.h"
#include "asterisk/pbx.h"
#include "asterisk/module.h"
#include "asterisk/image.h"
Functions
AST_MODULE_INFO_STANDARD_DEPRECATED (ASTERISK_GPL_KEY, "Image Transmission Application")
static int load_module (void)
static int sendimage_exec (struct ast_channel *chan, const char *data)
static int unload_module (void)
Variables
static char * app = "SendImage"
Detailed Description
App to transmit an image.
Author
Mark Spencer marks.nosp@m.ter@.nosp@m.digiu.nosp@m.m.co.nosp@m.m
Definition in file app_image.c.
Function Documentation
AST_MODULE_INFO_STANDARD_DEPRECATED()
AST_MODULE_INFO_STANDARD_DEPRECATED (ASTERISK_GPL_KEY , "Image Transmission Application")
Referenced by load_module().
load_module()
static int load_module (void) static
Definition at line 102 of file app_image.c.
References app, AST_MODULE_INFO_STANDARD_DEPRECATED(), ast_register_application_xml, ASTERISK_GPL_KEY, and sendimage_exec().
 {
    return ast_register_application_xml(app, sendimage_exec);
 }
sendimage_exec()
static int sendimage_exec (struct ast_channel * chan, const char * data) static
Definition at line 74 of file app_image.c.
References ast_log, ast_send_image(), ast_strlen_zero, ast_supports_images(), LOG_WARNING, and pbx_builtin_setvar_helper().
Referenced by load_module().
 {
    if (ast_strlen_zero(data)) {
       ast_log(LOG_WARNING, "SendImage requires an argument (filename)\n");
       return -1;
    }
    if (!ast_supports_images(chan)) {
       /* Does not support transport */
       pbx_builtin_setvar_helper(chan, "SENDIMAGESTATUS", "UNSUPPORTED");
       return 0;
    }
    if (!ast_send_image(chan, data)) {
       pbx_builtin_setvar_helper(chan, "SENDIMAGESTATUS", "SUCCESS");
    } else {
       pbx_builtin_setvar_helper(chan, "SENDIMAGESTATUS", "FAILURE");
    }
    return 0;
 }
unload_module()
static int unload_module (void) static
Definition at line 97 of file app_image.c.
References app, and ast_unregister_application().
 {
    return ast_unregister_application(app);
 }
Variable Documentation
app
char* app = "SendImage" static
Definition at line 38 of file app_image.c.
Referenced by load_module(), and unload_module().