Asterisk - The Open Source Telephony Project: stasis_endpoints.c File Reference
stasis_endpoints.c File Reference
Stasis endpoint API.
#include "asterisk.h"
#include "asterisk/astobj2.h"
#include "asterisk/stasis.h"
#include "asterisk/stasis_endpoints.h"
Functions
struct stasis_message * ast_endpoint_blob_create (struct ast_endpoint *endpoint, struct stasis_message_type *type, struct ast_json *blob)
Creates a ast_endpoint_blob message.
void ast_endpoint_blob_publish (struct ast_endpoint *endpoint, struct stasis_message_type *type, struct ast_json *blob)
Creates and publishes a ast_endpoint_blob message.
struct stasis_cache * ast_endpoint_cache (void)
Backend cache for ast_endpoint_topic_all_cached().
struct stasis_cp_all * ast_endpoint_cache_all (void)
struct ast_endpoint_snapshot * ast_endpoint_latest_snapshot (const char *tech, const char *name)
Retrieve the most recent snapshot for the endpoint with the given name.
struct ast_json * ast_endpoint_snapshot_to_json (const struct ast_endpoint_snapshot *snapshot, const struct stasis_message_sanitizer *sanitize)
Build a JSON object from a ast_endpoint_snapshot.
int ast_endpoint_stasis_init (void)
Initialization function for endpoint stasis support.
struct stasis_topic * ast_endpoint_topic_all (void)
Topic for all endpoint releated messages.
struct stasis_topic * ast_endpoint_topic_all_cached (void)
Cached topic for all endpoint related messages.
static struct ast_manager_event_blob * contactstatus_to_ami (struct stasis_message *msg)
static struct ast_json * contactstatus_to_json (struct stasis_message *msg, const struct stasis_message_sanitizer *sanitize)
static void endpoint_blob_dtor (void *obj)
static const char * endpoint_snapshot_get_id (struct stasis_message *message)
Callback extract a unique identity from a snapshot message.
static void endpoints_stasis_cleanup (void)
static struct ast_manager_event_blob * peerstatus_to_ami (struct stasis_message *msg)
static struct ast_json * peerstatus_to_json (struct stasis_message *msg, const struct stasis_message_sanitizer *sanitize)
STASIS_MESSAGE_TYPE_DEFN (ast_endpoint_snapshot_type)
STASIS_MESSAGE_TYPE_DEFN (ast_endpoint_state_type,.to_ami=peerstatus_to_ami,.to_json=peerstatus_to_json,)
STASIS_MESSAGE_TYPE_DEFN (ast_endpoint_contact_state_type,.to_ami=contactstatus_to_ami,.to_json=contactstatus_to_json)
Variables
static struct stasis_cp_all * endpoint_cache_all
Detailed Description
Stasis endpoint API.
Author
David M. Lee, II dlee@.nosp@m.digi.nosp@m.um.co.nosp@m.m
Definition in file stasis_endpoints.c.
Function Documentation
ast_endpoint_snapshot_to_json()
struct ast_json* ast_endpoint_snapshot_to_json (const struct ast_endpoint_snapshot * snapshot, const struct stasis_message_sanitizer * sanitize)
Build a JSON object from a ast_endpoint_snapshot.
Parameters
snapshot Endpoint snapshot.
sanitize The message sanitizer to use on the snapshot
Returns
JSON object representing endpoint snapshot.
NULL on error
Definition at line 398 of file stasis_endpoints.c.
References ast_assert, ast_endpoint_state_to_string(), ast_json_array_append(), ast_json_integer_create(), ast_json_object_get(), ast_json_object_set(), ast_json_pack(), ast_json_string_create(), ast_json_unref(), stasis_message_sanitizer::channel_id, ast_endpoint_snapshot::channel_ids, ast_endpoint_snapshot::max_channels, NULL, ast_endpoint_snapshot::num_channels, ast_endpoint_snapshot::resource, ast_endpoint_snapshot::state, and ast_endpoint_snapshot::tech.
Referenced by ast_ari_endpoints_get(), ast_ari_endpoints_list(), ast_ari_endpoints_list_by_tech(), contactstatus_to_json(), message_received_handler(), multi_user_event_to_json(), peerstatus_to_json(), and simple_endpoint_event().
 {
    struct ast_json *json;
    struct ast_json *channel_array;
    int i;
    json = ast_json_pack("{s: s, s: s, s: s, s: []}",
       "technology", snapshot->tech,
       "resource", snapshot->resource,
       "state", ast_endpoint_state_to_string(snapshot->state),
       "channel_ids");
    if (json == NULL) {
       return NULL;
    }
    if (snapshot->max_channels != -1) {
       int res = ast_json_object_set(json, "max_channels",
          ast_json_integer_create(snapshot->max_channels));
       if (res != 0) {
          ast_json_unref(json);
          return NULL;
       }
    }
    channel_array = ast_json_object_get(json, "channel_ids");
    ast_assert(channel_array != NULL);
    for (i = 0; i < snapshot->num_channels; ++i) {
       int res;
       if (sanitize && sanitize->channel_id
          && sanitize->channel_id(snapshot->channel_ids[i])) {
          continue;
       }
       res = ast_json_array_append(channel_array,
          ast_json_string_create(snapshot->channel_ids[i]));
       if (res != 0) {
          ast_json_unref(json);
          return NULL;
       }
    }
    return json;
 }
ast_endpoint_stasis_init()
int ast_endpoint_stasis_init (void)
Initialization function for endpoint stasis support.
Returns
0 on success.
non-zero on error.
Since
12
Definition at line 458 of file stasis_endpoints.c.
References ast_endpoint_contact_state_type(), ast_endpoint_snapshot_type(), ast_endpoint_state_type(), ast_register_cleanup(), endpoint_snapshot_get_id(), endpoints_stasis_cleanup(), stasis_cp_all_create(), and STASIS_MESSAGE_TYPE_INIT.
Referenced by asterisk_daemon().
 {
    int res = 0;
    ast_register_cleanup(endpoints_stasis_cleanup);
    endpoint_cache_all = stasis_cp_all_create("endpoint:all",
       endpoint_snapshot_get_id);
    if (!endpoint_cache_all) {
       return -1;
    }
    res |= STASIS_MESSAGE_TYPE_INIT(ast_endpoint_snapshot_type);
    res |= STASIS_MESSAGE_TYPE_INIT(ast_endpoint_state_type);
    res |= STASIS_MESSAGE_TYPE_INIT(ast_endpoint_contact_state_type);
    return res;
 }
contactstatus_to_ami()
static struct ast_manager_event_blob* contactstatus_to_ami (struct stasis_message * msg) static
Definition at line 203 of file stasis_endpoints.c.
References ast_free, ast_json_object_get(), ast_json_string_get(), ast_manager_event_blob_create(), ast_str_append(), ast_str_buffer(), ast_str_create, ast_endpoint_blob::blob, EVENT_FLAG_SYSTEM, NULL, RAII_VAR, stasis_message_data(), and value.
Referenced by contactstatus_to_json().
 {
    struct ast_endpoint_blob *obj = stasis_message_data(msg);
    RAII_VAR(struct ast_str *, contactstatus_event_string, ast_str_create(64), ast_free);
    const char *value;
    if (!(value = ast_json_string_get(ast_json_object_get(obj->blob, "uri")))) {
       return NULL;
    }
    ast_str_append(&contactstatus_event_string, 0, "URI: %s\r\n", value);
    if (!(value = ast_json_string_get(ast_json_object_get(obj->blob, "contact_status")))) {
       return NULL;
    }
    ast_str_append(&contactstatus_event_string, 0, "ContactStatus: %s\r\n", value);
    if (!(value = ast_json_string_get(ast_json_object_get(obj->blob, "aor")))) {
       return NULL;
    }
    ast_str_append(&contactstatus_event_string, 0, "AOR: %s\r\n", value);
    if (!(value = ast_json_string_get(ast_json_object_get(obj->blob, "endpoint_name")))) {
       return NULL;
    }
    ast_str_append(&contactstatus_event_string, 0, "EndpointName: %s\r\n", value);
    if ((value = ast_json_string_get(ast_json_object_get(obj->blob, "roundtrip_usec")))) {
       ast_str_append(&contactstatus_event_string, 0, "RoundtripUsec: %s\r\n", value);
    }
    return ast_manager_event_blob_create(EVENT_FLAG_SYSTEM, "ContactStatus",
       "%s", ast_str_buffer(contactstatus_event_string));
 }
contactstatus_to_json()
static struct ast_json* contactstatus_to_json (struct stasis_message * msg, const struct stasis_message_sanitizer * sanitize) static
Definition at line 237 of file stasis_endpoints.c.
References ast_endpoint_contact_state_type(), ast_endpoint_snapshot_to_json(), ast_json_object_get(), ast_json_pack(), ast_json_string_get(), ast_json_timeval(), ast_json_unref(), ast_strlen_zero, ast_endpoint_blob::blob, contactstatus_to_ami(), NULL, ast_endpoint_blob::snapshot, stasis_message_data(), stasis_message_timestamp(), STASIS_MESSAGE_TYPE_DEFN(), and to_ami().
 {
    struct ast_endpoint_blob *obj = stasis_message_data(msg);
    struct ast_json *json_endpoint;
    struct ast_json *json_final;
    const char *rtt;
    const struct timeval *tv = stasis_message_timestamp(msg);
    json_endpoint = ast_endpoint_snapshot_to_json(obj->snapshot, NULL);
    if (!json_endpoint) {
       return NULL;
    }
    /* The roundtrip time is optional. */
    rtt = ast_json_string_get(ast_json_object_get(obj->blob, "roundtrip_usec"));
    if (!ast_strlen_zero(rtt)) {
       json_final = ast_json_pack("{s: s, s: o, s: o, s: { s: s, s: s, s: s, s: s } } ",
          "type", "ContactStatusChange",
          "timestamp", ast_json_timeval(*tv, NULL),
          "endpoint", json_endpoint,
          "contact_info",
          "uri", ast_json_string_get(ast_json_object_get(obj->blob, "uri")),
          "contact_status", ast_json_string_get(ast_json_object_get(obj->blob,
             "contact_status")),
          "aor", ast_json_string_get(ast_json_object_get(obj->blob, "aor")),
          "roundtrip_usec", rtt);
    } else {
       json_final = ast_json_pack("{s: s, s: o, s: o, s: { s: s, s: s, s: s } } ",
          "type", "ContactStatusChange",
          "timestamp", ast_json_timeval(*tv, NULL),
          "endpoint", json_endpoint,
          "contact_info",
          "uri", ast_json_string_get(ast_json_object_get(obj->blob, "uri")),
          "contact_status", ast_json_string_get(ast_json_object_get(obj->blob,
             "contact_status")),
          "aor", ast_json_string_get(ast_json_object_get(obj->blob, "aor")));
    }
    if (!json_final) {
       ast_json_unref(json_endpoint);
    }
    return json_final;
 }
endpoint_blob_dtor()
static void endpoint_blob_dtor (void * obj) static
Definition at line 286 of file stasis_endpoints.c.
References ao2_cleanup, and ast_json_unref().
Referenced by ast_endpoint_blob_create().
 {
    struct ast_endpoint_blob *event = obj;
    ao2_cleanup(event->snapshot);
    ast_json_unref(event->blob);
 }
endpoint_snapshot_get_id()
static const char* endpoint_snapshot_get_id (struct stasis_message * message) static
Callback extract a unique identity from a snapshot message.
This identity is unique to the underlying object of the snapshot, such as the UniqueId field of a channel.
Parameters
message Message to extract id from.
Returns
String representing the snapshot's id.
NULL if the message_type of the message isn't a handled snapshot.
Since
12
Definition at line 384 of file stasis_endpoints.c.
References ast_endpoint_snapshot_type(), ast_endpoint_snapshot::id, NULL, stasis_message_data(), and stasis_message_type().
Referenced by ast_endpoint_stasis_init().
 {
    struct ast_endpoint_snapshot *snapshot;
    if (ast_endpoint_snapshot_type() != stasis_message_type(message)) {
       return NULL;
    }
    snapshot = stasis_message_data(message);
    return snapshot->id;
 }
endpoints_stasis_cleanup()
static void endpoints_stasis_cleanup (void) static
Definition at line 448 of file stasis_endpoints.c.
References ao2_cleanup, ast_endpoint_contact_state_type(), ast_endpoint_snapshot_type(), ast_endpoint_state_type(), NULL, and STASIS_MESSAGE_TYPE_CLEANUP.
Referenced by ast_endpoint_stasis_init().
 {
    STASIS_MESSAGE_TYPE_CLEANUP(ast_endpoint_snapshot_type);
    STASIS_MESSAGE_TYPE_CLEANUP(ast_endpoint_state_type);
    STASIS_MESSAGE_TYPE_CLEANUP(ast_endpoint_contact_state_type);
    ao2_cleanup(endpoint_cache_all);
    endpoint_cache_all = NULL;
 }
peerstatus_to_ami()
static struct ast_manager_event_blob* peerstatus_to_ami (struct stasis_message * msg) static
Definition at line 128 of file stasis_endpoints.c.
References ast_free, ast_json_object_get(), ast_json_string_get(), ast_manager_event_blob_create(), ast_str_append(), ast_str_buffer(), ast_str_create, ast_endpoint_blob::blob, EVENT_FLAG_SYSTEM, NULL, RAII_VAR, ast_endpoint_snapshot::resource, ast_endpoint_blob::snapshot, stasis_message_data(), ast_endpoint_snapshot::tech, and value.
Referenced by peerstatus_to_json().
 {
    struct ast_endpoint_blob *obj = stasis_message_data(msg);
    RAII_VAR(struct ast_str *, peerstatus_event_string, ast_str_create(64), ast_free);
    const char *value;
    /* peer_status is the only *required* thing */
    if (!(value = ast_json_string_get(ast_json_object_get(obj->blob, "peer_status")))) {
       return NULL;
    }
    ast_str_append(&peerstatus_event_string, 0, "PeerStatus: %s\r\n", value);
    if ((value = ast_json_string_get(ast_json_object_get(obj->blob, "cause")))) {
       ast_str_append(&peerstatus_event_string, 0, "Cause: %s\r\n", value);
    }
    if ((value = ast_json_string_get(ast_json_object_get(obj->blob, "address")))) {
       ast_str_append(&peerstatus_event_string, 0, "Address: %s\r\n", value);
    }
    if ((value = ast_json_string_get(ast_json_object_get(obj->blob, "port")))) {
       ast_str_append(&peerstatus_event_string, 0, "Port: %s\r\n", value);
    }
    if ((value = ast_json_string_get(ast_json_object_get(obj->blob, "time")))) {
       ast_str_append(&peerstatus_event_string, 0, "Time: %s\r\n", value);
    }
    return ast_manager_event_blob_create(EVENT_FLAG_SYSTEM, "PeerStatus",
       "ChannelType: %s\r\n"
       "Peer: %s/%s\r\n"
       "%s",
       obj->snapshot->tech,
       obj->snapshot->tech,
       obj->snapshot->resource,
       ast_str_buffer(peerstatus_event_string));
 }
peerstatus_to_json()
static struct ast_json* peerstatus_to_json (struct stasis_message * msg, const struct stasis_message_sanitizer * sanitize) static
Definition at line 163 of file stasis_endpoints.c.
References ast_endpoint_snapshot_to_json(), ast_endpoint_state_type(), ast_json_object_create(), ast_json_object_update(), ast_json_pack(), ast_json_timeval(), ast_json_unref(), ast_endpoint_blob::blob, NULL, peerstatus_to_ami(), ast_endpoint_blob::snapshot, stasis_message_data(), stasis_message_timestamp(), STASIS_MESSAGE_TYPE_DEFN(), and to_ami().
 {
    struct ast_endpoint_blob *obj = stasis_message_data(msg);
    struct ast_json *json_endpoint;
    struct ast_json *json_peer;
    struct ast_json *json_final;
    const struct timeval *tv = stasis_message_timestamp(msg);
    json_endpoint = ast_endpoint_snapshot_to_json(obj->snapshot, NULL);
    if (!json_endpoint) {
       return NULL;
    }
    json_peer = ast_json_object_create();
    if (!json_peer) {
       ast_json_unref(json_endpoint);
       return NULL;
    }
    /* Copy all fields from the blob */
    ast_json_object_update(json_peer, obj->blob);
    json_final = ast_json_pack("{s: s, s: o, s: o, s: o }",
       "type", "PeerStatusChange",
       "timestamp", ast_json_timeval(*tv, NULL),
       "endpoint", json_endpoint,
       "peer", json_peer);
    if (!json_final) {
       ast_json_unref(json_endpoint);
       ast_json_unref(json_peer);
    }
    return json_final;
 }
STASIS_MESSAGE_TYPE_DEFN() [1/3]
STASIS_MESSAGE_TYPE_DEFN (ast_endpoint_snapshot_type)
Referenced by ast_endpoint_topic_all_cached(), contactstatus_to_json(), and peerstatus_to_json().
STASIS_MESSAGE_TYPE_DEFN() [2/3]
STASIS_MESSAGE_TYPE_DEFN (ast_endpoint_state_type , . to_ami = peerstatus_to_ami, . to_json = peerstatus_to_json)
STASIS_MESSAGE_TYPE_DEFN() [3/3]
STASIS_MESSAGE_TYPE_DEFN (ast_endpoint_contact_state_type , . to_ami = contactstatus_to_ami, . to_json = contactstatus_to_json)
Variable Documentation
endpoint_cache_all
struct stasis_cp_all* endpoint_cache_all static
Definition at line 104 of file stasis_endpoints.c.
Referenced by ast_endpoint_cache_all().