Asterisk - The Open Source Telephony Project: func_uri.c File Reference
func_uri.c File Reference
Module: Dial plan functions
URI encoding / decoding.
#include "asterisk.h"
#include "asterisk/module.h"
#include "asterisk/channel.h"
#include "asterisk/pbx.h"
#include "asterisk/utils.h"
#include "asterisk/app.h"
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int load_module (void)
static int unload_module (void)
static int uridecode (struct ast_channel *chan, const char *cmd, char *data, char *buf, size_t len)
uridecode: Decode URI according to RFC 2396
static int uriencode (struct ast_channel *chan, const char *cmd, char *data, char *buf, size_t len)
uriencode: Encode URL according to RFC 2396
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "URI encode/decode dialplan functions" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, }
static const struct ast_module_info * ast_module_info = &__mod_info
static struct ast_custom_function urldecode_function
static struct ast_custom_function urlencode_function
Detailed Description
URI encoding / decoding.
Author
Olle E. Johansson oej@e.nosp@m.dvin.nosp@m.a.net
Note
For now this code only supports 8 bit characters, not unicode, which we ultimately will need to support.
Definition in file func_uri.c.
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 123 of file func_uri.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 123 of file func_uri.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 123 of file func_uri.c.
load_module()
static int load_module (void) static
Definition at line 117 of file func_uri.c.
References ast_custom_function_register.
 {
    return ast_custom_function_register(&urldecode_function)
       || ast_custom_function_register(&urlencode_function);
 }
unload_module()
static int unload_module (void) static
Definition at line 111 of file func_uri.c.
References ast_custom_function_unregister().
 {
    return ast_custom_function_unregister(&urldecode_function)
       || ast_custom_function_unregister(&urlencode_function);
 }
uridecode()
static int uridecode (struct ast_channel * chan, const char * cmd, char * data, char * buf, size_t len) static
uridecode: Decode URI according to RFC 2396
Definition at line 87 of file func_uri.c.
References ast_copy_string(), ast_strlen_zero, ast_uri_decode(), and ast_uri_http.
 {
    if (ast_strlen_zero(data)) {
       buf[0] = '\0';
       return 0;
    }
    ast_copy_string(buf, data, len);
    ast_uri_decode(buf, ast_uri_http);
    return 0;
 }
uriencode()
static int uriencode (struct ast_channel * chan, const char * cmd, char * data, char * buf, size_t len) static
uriencode: Encode URL according to RFC 2396
Definition at line 73 of file func_uri.c.
References ast_strlen_zero, ast_uri_encode(), and ast_uri_http.
 {
    if (ast_strlen_zero(data)) {
       buf[0] = '\0';
       return 0;
    }
    ast_uri_encode(data, buf, len, ast_uri_http);
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "URI encode/decode dialplan functions" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, } static
Definition at line 123 of file func_uri.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 123 of file func_uri.c.
urldecode_function
struct ast_custom_function urldecode_function static
Initial value:
= {
   .name = "URIDECODE",
   .read = uridecode,
}
Definition at line 101 of file func_uri.c.
urlencode_function
struct ast_custom_function urlencode_function static
Initial value:
= {
   .name = "URIENCODE",
   .read = uriencode,
}
Definition at line 106 of file func_uri.c.