Asterisk - The Open Source Telephony Project: app_softhangup.c File Reference
app_softhangup.c File Reference
Dial plan applications
SoftHangup application.
#include "asterisk.h"
#include "asterisk/file.h"
#include "asterisk/channel.h"
#include "asterisk/pbx.h"
#include "asterisk/module.h"
#include "asterisk/lock.h"
#include "asterisk/app.h"
Enumerations
enum { OPTION_ALL = (1 << 0) }
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int load_module (void)
static int softhangup_exec (struct ast_channel *chan, const char *data)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Hangs up the requested channel" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, }
static char * app = "SoftHangup"
static const struct ast_app_option app_opts [128] = { [ 'a' ] = { .flag = OPTION_ALL }, }
static const struct ast_module_info * ast_module_info = &__mod_info
Detailed Description
SoftHangup application.
Author
Mark Spencer marks.nosp@m.ter@.nosp@m.digiu.nosp@m.m.co.nosp@m.m
Definition in file app_softhangup.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
OPTION_ALL
Definition at line 66 of file app_softhangup.c.
      {
    OPTION_ALL = (1 << 0),
 };
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 147 of file app_softhangup.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 147 of file app_softhangup.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 147 of file app_softhangup.c.
load_module()
static int load_module (void) static
Definition at line 142 of file app_softhangup.c.
References app, ast_register_application_xml, and softhangup_exec().
 {
    return ast_register_application_xml(app, softhangup_exec);
 }
softhangup_exec()
static int softhangup_exec (struct ast_channel * chan, const char * data) static
Definition at line 74 of file app_softhangup.c.
References app_opts, args, AST_APP_ARG, ast_app_parse_options(), ast_channel_iterator_by_name_new(), ast_channel_iterator_destroy(), ast_channel_iterator_next(), ast_channel_lock, AST_CHANNEL_NAME, ast_channel_name(), ast_channel_tech(), ast_channel_unlock, ast_channel_unref, ast_copy_string(), AST_DECLARE_APP_ARGS, ast_log, ast_softhangup(), AST_SOFTHANGUP_EXPLICIT, AST_STANDARD_APP_ARGS, ast_strdupa, ast_strlen_zero, ast_test_flag, ast_verb, c, LOG_WARNING, name, NULL, OPTION_ALL, options, parse(), and type.
Referenced by load_module().
 {
    struct ast_channel *c = NULL;
    char *cut, *opts[0];
    char name[AST_CHANNEL_NAME] = "", *parse;
    struct ast_flags flags = {0};
    int lenmatch;
    AST_DECLARE_APP_ARGS(args,
       AST_APP_ARG(channel);
       AST_APP_ARG(options);
    );
    struct ast_channel_iterator *iter;
    if (ast_strlen_zero(data)) {
       ast_log(LOG_WARNING, "SoftHangup requires an argument (Technology/resource)\n");
       return 0;
    }
    parse = ast_strdupa(data);
    AST_STANDARD_APP_ARGS(args, parse);
    if (args.argc == 2)
       ast_app_parse_options(app_opts, &flags, opts, args.options);
    lenmatch = strlen(args.channel);
    if (!(iter = ast_channel_iterator_by_name_new(args.channel, lenmatch))) {
       return -1;
    }
    while ((c = ast_channel_iterator_next(iter))) {
       ast_channel_lock(c);
       ast_copy_string(name, ast_channel_name(c), sizeof(name));
       if (ast_test_flag(&flags, OPTION_ALL)) {
          /* CAPI is set up like CAPI[foo/bar]/clcnt */
          if (!strcmp(ast_channel_tech(c)->type, "CAPI")) {
             cut = strrchr(name, '/');
          /* Basically everything else is Foo/Bar-Z */
          } else {
             /* use strrchr() because Foo/Bar-Z could actually be Foo/B-a-r-Z */
             cut = strrchr(name,'-');
          }
          /* Get rid of what we've cut */
          if (cut)
             *cut = 0;
       }
       if (!strcasecmp(name, args.channel)) {
          ast_verb(4, "Soft hanging %s up.\n", ast_channel_name(c));
          ast_softhangup(c, AST_SOFTHANGUP_EXPLICIT);
          if (!ast_test_flag(&flags, OPTION_ALL)) {
             ast_channel_unlock(c);
             c = ast_channel_unref(c);
             break;
          }
       }
       ast_channel_unlock(c);
       c = ast_channel_unref(c);
    }
    ast_channel_iterator_destroy(iter);
    return 0;
 }
unload_module()
static int unload_module (void) static
Definition at line 137 of file app_softhangup.c.
References app, and ast_unregister_application().
 {
    return ast_unregister_application(app);
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Hangs up the requested channel" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, } static
Definition at line 147 of file app_softhangup.c.
app
char* app = "SoftHangup" static
Definition at line 64 of file app_softhangup.c.
Referenced by load_module(), and unload_module().
app_opts
const struct ast_app_option app_opts[128] = { [ 'a' ] = { .flag = OPTION_ALL }, } static
Definition at line 72 of file app_softhangup.c.
Referenced by softhangup_exec().
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 147 of file app_softhangup.c.