Asterisk - The Open Source Telephony Project: codec_a_mu.c File Reference
codec_a_mu.c File Reference
Module: Codecs
codec_a_mu.c - translate between alaw and ulaw directly
#include "asterisk.h"
#include "asterisk/module.h"
#include "asterisk/translate.h"
#include "asterisk/alaw.h"
#include "asterisk/ulaw.h"
#include "asterisk/utils.h"
#include "ex_ulaw.h"
#include "ex_alaw.h"
Macros
#define BUFFER_SAMPLES 8000 /* size for the translation buffers */
Functions
static void __reg_module (void)
static void __unreg_module (void)
static int alawtoulaw_framein (struct ast_trans_pvt *pvt, struct ast_frame *f)
convert frame data and store into the buffer
struct ast_module * AST_MODULE_SELF_SYM (void)
static int load_module (void)
static int ulawtoalaw_framein (struct ast_trans_pvt *pvt, struct ast_frame *f)
convert frame data and store into the buffer
static int unload_module (void)
standard module glue
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "A-law and Mulaw direct Coder/Decoder" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, }
static unsigned char a2mu [256]
static struct ast_translator alawtoulaw
static const struct ast_module_info * ast_module_info = &__mod_info
static unsigned char mu2a [256]
static struct ast_translator ulawtoalaw
Detailed Description
codec_a_mu.c - translate between alaw and ulaw directly
Definition in file codec_a_mu.c.
Macro Definition Documentation
BUFFER_SAMPLES
#define BUFFER_SAMPLES 8000 /* size for the translation buffers */
Definition at line 38 of file codec_a_mu.c.
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 150 of file codec_a_mu.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 150 of file codec_a_mu.c.
alawtoulaw_framein()
static int alawtoulaw_framein (struct ast_trans_pvt * pvt, struct ast_frame * f) static
convert frame data and store into the buffer
Definition at line 48 of file codec_a_mu.c.
References a2mu, ast_frame::data, ast_trans_pvt::datalen, ast_trans_pvt::outbuf, ast_frame::ptr, ast_frame::samples, ast_trans_pvt::samples, and ast_trans_pvt::uc.
 {
    int x = f->samples;
    unsigned char *src = f->data.ptr;
    unsigned char *dst = pvt->outbuf.uc + pvt->samples;
    pvt->samples += x;
    pvt->datalen += x;
    while (x--)
       *dst++ = a2mu[*src++];
    return 0;
 }
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 150 of file codec_a_mu.c.
load_module()
static int load_module (void) static
Definition at line 129 of file codec_a_mu.c.
References a2mu, AST_ALAW, AST_LIN2A, AST_LIN2MU, AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, AST_MULAW, ast_register_translator, mu2a, and unload_module().
 {
    int res;
    int x;
    for (x=0;x<256;x++) {
       mu2a[x] = AST_LIN2A(AST_MULAW(x));
       a2mu[x] = AST_LIN2MU(AST_ALAW(x));
    }
    res = ast_register_translator(&alawtoulaw);
    res |= ast_register_translator(&ulawtoalaw);
    if (res) {
       unload_module();
       return AST_MODULE_LOAD_DECLINE;
    }
    return AST_MODULE_LOAD_SUCCESS;
 }
ulawtoalaw_framein()
static int ulawtoalaw_framein (struct ast_trans_pvt * pvt, struct ast_frame * f) static
convert frame data and store into the buffer
Definition at line 64 of file codec_a_mu.c.
References ast_frame::data, ast_trans_pvt::datalen, mu2a, ast_trans_pvt::outbuf, ast_frame::ptr, ast_frame::samples, ast_trans_pvt::samples, and ast_trans_pvt::uc.
 {
    int x = f->samples;
    unsigned char *src = f->data.ptr;
    unsigned char *dst = pvt->outbuf.uc + pvt->samples;
    pvt->samples += x;
    pvt->datalen += x;
    while (x--)
       *dst++ = mu2a[*src++];
    return 0;
 }
unload_module()
static int unload_module (void) static
standard module glue
Definition at line 119 of file codec_a_mu.c.
References ast_unregister_translator().
Referenced by load_module().
 {
    int res;
    res = ast_unregister_translator(&ulawtoalaw);
    res |= ast_unregister_translator(&alawtoulaw);
    return res;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "A-law and Mulaw direct Coder/Decoder" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, } static
Definition at line 150 of file codec_a_mu.c.
a2mu
unsigned char a2mu[256] static
Definition at line 41 of file codec_a_mu.c.
Referenced by alawtoulaw_framein(), and load_module().
alawtoulaw
struct ast_translator alawtoulaw static
Definition at line 79 of file codec_a_mu.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 150 of file codec_a_mu.c.
mu2a
unsigned char mu2a[256] static
Definition at line 40 of file codec_a_mu.c.
Referenced by load_module(), and ulawtoalaw_framein().
ulawtoalaw
struct ast_translator ulawtoalaw static
Definition at line 98 of file codec_a_mu.c.