Asterisk - The Open Source Telephony Project: smoother.c File Reference
smoother.c File Reference
Frame smoother manipulation routines.
#include "asterisk.h"
#include "asterisk/_private.h"
#include "asterisk/frame.h"
#include "asterisk/astobj2.h"
#include "asterisk/time.h"
#include "asterisk/utils.h"
#include "asterisk/format.h"
#include "asterisk/codec.h"
#include "asterisk/smoother.h"
Data Structures
struct ast_smoother
Macros
#define SMOOTHER_SIZE 8000
Functions
int __ast_smoother_feed (struct ast_smoother *s, struct ast_frame *f, int swap)
void ast_smoother_free (struct ast_smoother *s)
int ast_smoother_get_flags (struct ast_smoother *s)
struct ast_smoother * ast_smoother_new (int size)
struct ast_frame * ast_smoother_read (struct ast_smoother *s)
void ast_smoother_reconfigure (struct ast_smoother *s, int bytes)
Reconfigure an existing smoother to output a different number of bytes per frame.
void ast_smoother_reset (struct ast_smoother *s, int bytes)
void ast_smoother_set_flags (struct ast_smoother *s, int flags)
int ast_smoother_test_flag (struct ast_smoother *s, int flag)
static int smoother_frame_feed (struct ast_smoother *s, struct ast_frame *f, int swap)
Detailed Description
Frame smoother manipulation routines.
Author
Mark Spencer marks.nosp@m.ter@.nosp@m.digiu.nosp@m.m.co.nosp@m.m
Definition in file smoother.c.
Macro Definition Documentation
SMOOTHER_SIZE
#define SMOOTHER_SIZE 8000
Definition at line 41 of file smoother.c.
Referenced by __ast_smoother_feed().
Function Documentation
__ast_smoother_feed()
int __ast_smoother_feed (struct ast_smoother * s, struct ast_frame * f, int swap)
Definition at line 133 of file smoother.c.
References ao2_bump, ast_format_cmp(), AST_FORMAT_CMP_NOT_EQUAL, ast_format_get_name(), AST_FRAME_VOICE, ast_log, AST_MIN_OFFSET, AST_SMOOTHER_FLAG_G729, ast_swapcopy_samples(), ast_frame::data, ast_frame::datalen, ast_smoother::f, ast_smoother::flags, ast_smoother::format, ast_frame_subclass::format, ast_frame::frametype, ast_smoother::len, LOG_WARNING, ast_frame::offset, ast_smoother::opt, ast_smoother::opt_needs_swap, ast_frame::ptr, ast_frame::samples, ast_smoother::samplesperbyte, ast_smoother::size, smoother_frame_feed(), SMOOTHER_SIZE, and ast_frame::subclass.
 {
    if (f->frametype != AST_FRAME_VOICE) {
       ast_log(LOG_WARNING, "Huh?  Can't smooth a non-voice frame!\n");
       return -1;
    }
    if (!s->format) {
       s->format = ao2_bump(f->subclass.format);
       s->samplesperbyte = (float)f->samples / (float)f->datalen;
    } else if (ast_format_cmp(s->format, f->subclass.format) == AST_FORMAT_CMP_NOT_EQUAL) {
       ast_log(LOG_WARNING, "Smoother was working on %s format frames, now trying to feed %s?\n",
          ast_format_get_name(s->format), ast_format_get_name(f->subclass.format));
       return -1;
    }
    if (s->len + f->datalen > SMOOTHER_SIZE) {
       ast_log(LOG_WARNING, "Out of smoother space\n");
       return -1;
    }
    if (((f->datalen == s->size) ||
         ((f->datalen < 10) && (s->flags & AST_SMOOTHER_FLAG_G729))) &&
        !s->opt &&
        !s->len &&
        (f->offset >= AST_MIN_OFFSET)) {
       /* Optimize by sending the frame we just got
          on the next read, thus eliminating the douple
          copy */
       if (swap)
          ast_swapcopy_samples(f->data.ptr, f->data.ptr, f->samples);
       s->opt = f;
       s->opt_needs_swap = swap ? 1 : 0;
       return 0;
    }
    return smoother_frame_feed(s, f, swap);
 }
ast_smoother_free()
void ast_smoother_free (struct ast_smoother * s)
Definition at line 220 of file smoother.c.
References ao2_cleanup, ast_free, and ast_smoother::format.
Referenced by ast_rtp_destroy(), ast_rtp_dtmf_end_with_duration(), ast_rtp_local_bridge(), ast_rtp_write(), destroy_session(), generic_fax_exec(), mbl_load_device(), multicast_rtp_destroy(), and unload_module().
 {
    ao2_cleanup(s->format);
    ast_free(s);
 }
ast_smoother_get_flags()
int ast_smoother_get_flags (struct ast_smoother * s)
Definition at line 118 of file smoother.c.
References ast_smoother::flags.
 {
    return s->flags;
 }
ast_smoother_new()
struct ast_smoother* ast_smoother_new (int size)
Definition at line 108 of file smoother.c.
References ast_calloc, ast_smoother_reset(), and NULL.
Referenced by ast_rtp_write(), generic_fax_exec(), mbl_load_device(), and multicast_rtp_write().
 {
    struct ast_smoother *s;
    if (size < 1)
       return NULL;
    if ((s = ast_calloc(1, sizeof(*s))))
       ast_smoother_reset(s, size);
    return s;
 }
ast_smoother_read()
struct ast_frame* ast_smoother_read (struct ast_smoother * s)
Definition at line 169 of file smoother.c.
References ast_format_get_sample_rate(), AST_FRAME_VOICE, AST_FRIENDLY_OFFSET, ast_log, ast_samp2tv(), AST_SMOOTHER_FLAG_G729, ast_tvadd(), ast_tvzero(), ast_smoother::data, ast_frame::data, ast_frame::datalen, ast_smoother::delivery, ast_frame::delivery, ast_smoother::f, ast_smoother::flags, ast_smoother::format, ast_frame_subclass::format, ast_smoother::framedata, ast_frame::frametype, ast_smoother::len, LOG_WARNING, NULL, ast_frame::offset, ast_smoother::opt, ast_frame::ptr, ast_frame::samples, ast_smoother::samplesperbyte, ast_smoother::size, and ast_frame::subclass.
Referenced by ast_rtp_write(), generic_fax_exec(), mbl_read(), mbl_write(), and multicast_rtp_write().
 {
    struct ast_frame *opt;
    int len;
    /* IF we have an optimization frame, send it */
    if (s->opt) {
       if (s->opt->offset < AST_FRIENDLY_OFFSET)
          ast_log(LOG_WARNING, "Returning a frame of inappropriate offset (%d).\n",
                      s->opt->offset);
       opt = s->opt;
       s->opt = NULL;
       return opt;
    }
    /* Make sure we have enough data */
    if (s->len < s->size) {
       /* Or, if this is a G.729 frame with VAD on it, send it immediately anyway */
       if (!((s->flags & AST_SMOOTHER_FLAG_G729) && (s->len % 10)))
          return NULL;
    }
    len = s->size;
    if (len > s->len)
       len = s->len;
    /* Make frame */
    s->f.frametype = AST_FRAME_VOICE;
    s->f.subclass.format = s->format;
    s->f.data.ptr = s->framedata + AST_FRIENDLY_OFFSET;
    s->f.offset = AST_FRIENDLY_OFFSET;
    s->f.datalen = len;
    /* Samples will be improper given VAD, but with VAD the concept really doesn't even exist */
    s->f.samples = len * s->samplesperbyte;   /* XXX rounding */
    s->f.delivery = s->delivery;
    /* Fill Data */
    memcpy(s->f.data.ptr, s->data, len);
    s->len -= len;
    /* Move remaining data to the front if applicable */
    if (s->len) {
       /* In principle this should all be fine because if we are sending
          G.729 VAD, the next timestamp will take over anyawy */
       memmove(s->data, s->data + len, s->len);
       if (!ast_tvzero(s->delivery)) {
          /* If we have delivery time, increment it, otherwise, leave it at 0 */
          s->delivery = ast_tvadd(s->delivery, ast_samp2tv(s->f.samples,
             ast_format_get_sample_rate(s->format)));
       }
    }
    /* Return frame */
    return &s->f;
 }
ast_smoother_reconfigure()
void ast_smoother_reconfigure (struct ast_smoother * s, int bytes)
Reconfigure an existing smoother to output a different number of bytes per frame.
Parameters
s the smoother to reconfigure
bytes the desired number of bytes per output frame
Returns
nothing
Definition at line 86 of file smoother.c.
References NULL, ast_smoother::opt, ast_smoother::opt_needs_swap, ast_smoother::size, and smoother_frame_feed().
 {
    /* if there is no change, then nothing to do */
    if (s->size == bytes) {
       return;
    }
    /* set the new desired output size */
    s->size = bytes;
    /* if there is no 'optimized' frame in the smoother,
     *   then there is nothing left to do
     */
    if (!s->opt) {
       return;
    }
    /* there is an 'optimized' frame here at the old size,
     * but it must now be put into the buffer so the data
     * can be extracted at the new size
     */
    smoother_frame_feed(s, s->opt, s->opt_needs_swap);
    s->opt = NULL;
 }
ast_smoother_reset()
void ast_smoother_reset (struct ast_smoother * s, int bytes)
Definition at line 79 of file smoother.c.
References ao2_cleanup, ast_smoother::format, and ast_smoother::size.
Referenced by ast_smoother_new(), and mbl_new().
 {
    ao2_cleanup(s->format);
    memset(s, 0, sizeof(*s));
    s->size = bytes;
 }
ast_smoother_set_flags()
void ast_smoother_set_flags (struct ast_smoother * s, int flags)
Definition at line 123 of file smoother.c.
References ast_smoother::flags.
Referenced by ast_rtp_write(), and multicast_rtp_write().
 {
    s->flags = flags;
 }
ast_smoother_test_flag()
int ast_smoother_test_flag (struct ast_smoother * s, int flag)
Definition at line 128 of file smoother.c.
References ast_smoother::flags.
Referenced by ast_rtp_write(), and multicast_rtp_write().
 {
    return (s->flags & flag);
 }
smoother_frame_feed()
static int smoother_frame_feed (struct ast_smoother * s, struct ast_frame * f, int swap) static
Definition at line 57 of file smoother.c.
References ast_log, AST_SMOOTHER_FLAG_G729, ast_swapcopy_samples(), ast_tvzero(), ast_smoother::data, ast_frame::data, ast_frame::datalen, ast_smoother::delivery, ast_frame::delivery, ast_smoother::flags, ast_smoother::len, LOG_NOTICE, ast_frame::ptr, and ast_frame::samples.
Referenced by __ast_smoother_feed(), and ast_smoother_reconfigure().
 {
    if (s->flags & AST_SMOOTHER_FLAG_G729) {
       if (s->len % 10) {
          ast_log(LOG_NOTICE, "Dropping extra frame of G.729 since we already have a VAD frame at the end\n");
          return 0;
       }
    }
    if (swap) {
       ast_swapcopy_samples(s->data + s->len, f->data.ptr, f->samples);
    } else {
       memcpy(s->data + s->len, f->data.ptr, f->datalen);
    }
    /* If either side is empty, reset the delivery time */
    if (!s->len || ast_tvzero(f->delivery) || ast_tvzero(s->delivery)) { /* XXX really ? */
       s->delivery = f->delivery;
    }
    s->len += f->datalen;
    return 0;
 }