Asterisk - The Open Source Telephony Project: packing.h File Reference
packing.h File Reference
Functions
void dopack (unsigned char **bitstream, int index, int bitno, int *pos)
void packcombine (int *index, int rest, int bitno_rest)
void packsplit (int *index, int *firstpart, int *rest, int bitno_firstpart, int bitno_total)
void unpack (unsigned char **bitstream, int *index, int bitno, int *pos)
Function Documentation
dopack()
void dopack (unsigned char ** bitstream, int index, int bitno, int * pos)
Definition at line 68 of file packing.c.
Referenced by iLBC_encode().
     {
        int posLeft;
        /* Clear the bits before starting in a new byte */
        if ((*pos)==0) {
            **bitstream=0;
        }
        while (bitno>0) {
            /* Jump to the next byte if end of this byte is reached*/
            if (*pos==8) {
                *pos=0;
                (*bitstream)++;
                **bitstream=0;
            }
            posLeft=8-(*pos);
            /* Insert index into the bitstream */
            if (bitno <= posLeft) {
                **bitstream |= (unsigned char)(index<<(posLeft-bitno));
                *pos+=bitno;
                bitno=0;
            } else {
                **bitstream |= (unsigned char)(index>>(bitno-posLeft));
                *pos=8;
                index-=((index>>(bitno-posLeft))<<(bitno-posLeft));
                bitno-=posLeft;
            }
        }
    }
packcombine()
void packcombine (int * index, int rest, int bitno_rest)
Definition at line 53 of file packing.c.
Referenced by iLBC_decode().
     {
        *index = *index<<bitno_rest;
        *index += rest;
    }
packsplit()
void packsplit (int * index, int * firstpart, int * rest, int bitno_firstpart, int bitno_total)
Definition at line 26 of file packing.c.
Referenced by iLBC_encode().
     {
        int bitno_rest = bitno_total-bitno_firstpart;
        *firstpart = *index>>(bitno_rest);
        *rest = *index-(*firstpart<<(bitno_rest));
    }
unpack()
void unpack (unsigned char ** bitstream, int * index, int bitno, int * pos)
Definition at line 126 of file packing.c.
Referenced by iLBC_decode().
     {
        int BitsLeft;
        *index=0;
        while (bitno>0) {
            /* move forward in bitstream when the end of the
               byte is reached */
            if (*pos==8) {
                *pos=0;
                (*bitstream)++;
            }
            BitsLeft=8-(*pos);
            /* Extract bits to index */
            if (BitsLeft>=bitno) {
                *index+=((((**bitstream)<<(*pos)) & 0xFF)>>(8-bitno));
                *pos+=bitno;
                bitno=0;
            } else {
                if ((8-bitno)>0) {
                    *index+=((((**bitstream)<<(*pos)) & 0xFF)>>
                        (8-bitno));
                    *pos=8;
                } else {
                    *index+=(((int)(((**bitstream)<<(*pos)) & 0xFF))<<
                        (bitno-8));
                    *pos=8;
                }
                bitno-=BitsLeft;
            }
        }
    }