Asterisk - The Open Source Telephony Project: func_math.c File Reference
func_math.c File Reference
Module: Dial plan functions
Math related dialplan function.
#include "asterisk.h"
#include <math.h>
#include "asterisk/module.h"
#include "asterisk/channel.h"
#include "asterisk/pbx.h"
#include "asterisk/utils.h"
#include "asterisk/conversions.h"
#include "asterisk/app.h"
#include "asterisk/config.h"
#include "asterisk/test.h"
Enumerations
enum TypeOfFunctions {
ADDFUNCTION, DIVIDEFUNCTION, MULTIPLYFUNCTION, SUBTRACTFUNCTION,
MODULUSFUNCTION, POWFUNCTION, SHLEFTFUNCTION, SHRIGHTFUNCTION,
BITWISEANDFUNCTION, BITWISEXORFUNCTION, BITWISEORFUNCTION, GTFUNCTION,
LTFUNCTION, GTEFUNCTION, LTEFUNCTION, EQFUNCTION
}
enum TypeOfResult { FLOAT_RESULT, INT_RESULT, HEX_RESULT, CHAR_RESULT }
Functions
static void __reg_module (void)
static void __unreg_module (void)
static int acf_abs_exec (struct ast_channel *chan, const char *cmd, char *parse, char *buffer, size_t buflen)
static int acf_max_exec (struct ast_channel *chan, const char *cmd, char *parse, char *buffer, size_t buflen)
static int acf_min_exec (struct ast_channel *chan, const char *cmd, char *parse, char *buffer, size_t buflen)
struct ast_module * AST_MODULE_SELF_SYM (void)
AST_TEST_DEFINE (test_MATH_function)
static int crement_function_read (struct ast_channel *chan, const char *cmd, char *data, char *buf, size_t len)
static int load_module (void)
static int math (struct ast_channel *chan, const char *cmd, char *parse, char *buf, size_t len)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Mathematical dialplan function" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, }
static struct ast_custom_function acf_abs
static struct ast_custom_function acf_max
static struct ast_custom_function acf_min
static const struct ast_module_info * ast_module_info = &__mod_info
static struct ast_custom_function decrement_function
static struct ast_custom_function increment_function
static struct ast_custom_function math_function
Detailed Description
Math related dialplan function.
Author
Andy Powell
Mark Spencer marks.nosp@m.ter@.nosp@m.digiu.nosp@m.m.co.nosp@m.m
Nir Simionovich nirs@.nosp@m.gree.nosp@m.nfiel.nosp@m.dtec.nosp@m.h.net
Naveen Albert aster.nosp@m.isk@.nosp@m.phrea.nosp@m.knet.nosp@m..org
Definition in file func_math.c.
Enumeration Type Documentation
TypeOfFunctions
enum TypeOfFunctions
Enumerator
ADDFUNCTION
DIVIDEFUNCTION
MULTIPLYFUNCTION
SUBTRACTFUNCTION
MODULUSFUNCTION
POWFUNCTION
SHLEFTFUNCTION
SHRIGHTFUNCTION
BITWISEANDFUNCTION
BITWISEXORFUNCTION
BITWISEORFUNCTION
GTFUNCTION
LTFUNCTION
GTEFUNCTION
LTEFUNCTION
EQFUNCTION
Definition at line 154 of file func_math.c.
                      {
    ADDFUNCTION,
    DIVIDEFUNCTION,
    MULTIPLYFUNCTION,
    SUBTRACTFUNCTION,
    MODULUSFUNCTION,
    POWFUNCTION,
    SHLEFTFUNCTION,
    SHRIGHTFUNCTION,
    BITWISEANDFUNCTION,
    BITWISEXORFUNCTION,
    BITWISEORFUNCTION,
    GTFUNCTION,
    LTFUNCTION,
    GTEFUNCTION,
    LTEFUNCTION,
    EQFUNCTION
 };
TypeOfResult
enum TypeOfResult
Enumerator
FLOAT_RESULT
INT_RESULT
HEX_RESULT
CHAR_RESULT
Definition at line 173 of file func_math.c.
                   {
    FLOAT_RESULT,
    INT_RESULT,
    HEX_RESULT,
    CHAR_RESULT
 };
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 723 of file func_math.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 723 of file func_math.c.
acf_abs_exec()
static int acf_abs_exec (struct ast_channel * chan, const char * cmd, char * parse, char * buffer, size_t buflen) static
Definition at line 583 of file func_math.c.
References args, AST_APP_ARG, ast_debug, AST_DECLARE_APP_ARGS, ast_log, AST_STANDARD_APP_ARGS, ast_strlen_zero, and LOG_WARNING.
 {
    double num1, response_num;
    AST_DECLARE_APP_ARGS(args,
               AST_APP_ARG(num1);
    );
    AST_STANDARD_APP_ARGS(args, parse);
    if (ast_strlen_zero(args.num1) || sscanf(args.num1, "%30lf", &num1) != 1) {
       ast_log(LOG_WARNING, "Bad or missing argument for number: %s", args.num1);
       return -1;
    }
    response_num = fabs(num1);
    ast_debug(1, "%f is the absolute value of %f\n", response_num, num1);
    if ((int) response_num == response_num) {
       snprintf(buffer, buflen, "%d", (int) response_num);
    } else {
       snprintf(buffer, buflen, "%f", response_num);
    }
    return 0;
 }
acf_max_exec()
static int acf_max_exec (struct ast_channel * chan, const char * cmd, char * parse, char * buffer, size_t buflen) static
Definition at line 537 of file func_math.c.
References args, AST_APP_ARG, ast_debug, AST_DECLARE_APP_ARGS, ast_log, AST_STANDARD_APP_ARGS, ast_strlen_zero, LOG_ERROR, and LOG_WARNING.
 {
    double num1, num2, response_num = 0;
    AST_DECLARE_APP_ARGS(args,
               AST_APP_ARG(num1);
               AST_APP_ARG(num2);
    );
    AST_STANDARD_APP_ARGS(args, parse);
    if (ast_strlen_zero(args.num1) && ast_strlen_zero(args.num2)) {
       ast_log(LOG_ERROR, "Missing argument for number(s).");
       return -1;
    }
    if (ast_strlen_zero(args.num1)) {
       response_num = -1; /* couldn't read num1 successfully */
    } else if (sscanf(args.num1, "%30lf", &num1) != 1) {
       ast_log(LOG_WARNING, "'%s' is not a valid number\n", args.num1);
       return -1;
    }
    if (ast_strlen_zero(args.num2)) {
       num2 = num1; /* num1 must be a valid integer here */
    } else if (sscanf(args.num2, "%30lf", &num2) != 1) {
       ast_log(LOG_WARNING, "'%s' is not a valid number\n", args.num2);
       return -1;
    }
    if (response_num == -1) { /* could only read num2 */
       response_num = num2;
    } else {
       response_num = (num1 < num2) ? num2 : num1;
    }
    ast_debug(1, "%f is the maximum of [%f,%f]\n", response_num, num1, num2);
    if ((int) response_num == response_num) {
       snprintf(buffer, buflen, "%d", (int) response_num);
    } else {
       snprintf(buffer, buflen, "%f", response_num);
    }
    return 0;
 }
acf_min_exec()
static int acf_min_exec (struct ast_channel * chan, const char * cmd, char * parse, char * buffer, size_t buflen) static
Definition at line 491 of file func_math.c.
References args, AST_APP_ARG, ast_debug, AST_DECLARE_APP_ARGS, ast_log, AST_STANDARD_APP_ARGS, ast_strlen_zero, LOG_ERROR, and LOG_WARNING.
 {
    double num1, num2, response_num = 0;
    AST_DECLARE_APP_ARGS(args,
               AST_APP_ARG(num1);
               AST_APP_ARG(num2);
    );
    AST_STANDARD_APP_ARGS(args, parse);
    if (ast_strlen_zero(args.num1) && ast_strlen_zero(args.num2)) {
       ast_log(LOG_ERROR, "Missing argument for number(s).");
       return -1;
    }
    if (ast_strlen_zero(args.num1)) {
       response_num = -1; /* couldn't read num1 successfully */
    } else if (sscanf(args.num1, "%30lf", &num1) != 1) {
       ast_log(LOG_WARNING, "'%s' is not a valid number\n", args.num1);
       return -1;
    }
    if (ast_strlen_zero(args.num2)) {
       num2 = num1; /* num1 must be a valid integer here */
    } else if (sscanf(args.num2, "%30lf", &num2) != 1) {
       ast_log(LOG_WARNING, "'%s' is not a valid number\n", args.num2);
       return -1;
    }
    if (response_num == -1) { /* could only read num2 */
       response_num = num2;
    } else {
       response_num = (num1 > num2) ? num2 : num1;
    }
    ast_debug(1, "%f is the minimum of [%f,%f]\n", response_num, num1, num2);
    if ((int) response_num == response_num) {
       snprintf(buffer, buflen, "%d", (int) response_num);
    } else {
       snprintf(buffer, buflen, "%f", response_num);
    }
    return 0;
 }
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 723 of file func_math.c.
AST_TEST_DEFINE()
AST_TEST_DEFINE (test_MATH_function)
Definition at line 643 of file func_math.c.
References ast_free, ast_str_buffer(), ast_str_create, ast_str_set(), ast_str_substitute_variables(), AST_TEST_FAIL, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_test_status_update, sip_to_pjsip::info(), NULL, result, TEST_EXECUTE, and TEST_INIT.
 {
    enum ast_test_result_state res = AST_TEST_PASS;
    struct ast_str *expr, *result;
    switch (cmd) {
    case TEST_INIT:
       info->name = "test_MATH_function";
       info->category = "/main/pbx/";
       info->summary = "Test MATH function substitution";
       info->description =
          "Executes a series of variable substitutions using the MATH function and ensures that the expected results are received.";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    ast_test_status_update(test, "Testing MATH() substitution ...\n");
    if (!(expr = ast_str_create(16))) {
       return AST_TEST_FAIL;
    }
    if (!(result = ast_str_create(16))) {
       ast_free(expr);
       return AST_TEST_FAIL;
    }
    ast_str_set(&expr, 0, "${MATH(170 AND 63,i)}");
    ast_str_substitute_variables(&result, 0, NULL, ast_str_buffer(expr));
    if (strcmp(ast_str_buffer(result), "42") != 0) {
       ast_test_status_update(test, "Expected result '42' not returned! ('%s')\n",
             ast_str_buffer(result));
       res = AST_TEST_FAIL;
    }
    ast_str_set(&expr, 0, "${MATH(170AND63,i)}");
    ast_str_substitute_variables(&result, 0, NULL, ast_str_buffer(expr));
    if (strcmp(ast_str_buffer(result), "42") != 0) {
       ast_test_status_update(test, "Expected result '42' not returned! ('%s')\n",
             ast_str_buffer(result));
       res = AST_TEST_FAIL;
    }
    ast_free(expr);
    ast_free(result);
    return res;
 }
crement_function_read()
static int crement_function_read (struct ast_channel * chan, const char * cmd, char * data, char * buf, size_t len) static
Definition at line 423 of file func_math.c.
References ast_channel_lock, ast_channel_unlock, ast_copy_string(), ast_log, ast_strlen_zero, LOG_NOTICE, LOG_WARNING, pbx_builtin_getvar_helper(), pbx_builtin_setvar_helper(), and var.
 {
    int ret = -1;
    int int_value = 0;
    int modify_orig = 0;
    const char *var;
    char endchar = 0, returnvar[12]; /* If you need a variable longer than 11 digits - something is way wrong */
    if (ast_strlen_zero(data)) {
       ast_log(LOG_WARNING, "Syntax: %s(<data>) - missing argument!\n", cmd);
       return -1;
    }
    if (!chan) {
       ast_log(LOG_WARNING, "No channel was provided to %s function.\n", cmd);
       return -1;
    }
    ast_channel_lock(chan);
    if (!(var = pbx_builtin_getvar_helper(chan, data))) {
       ast_log(LOG_NOTICE, "Failed to obtain variable %s, bailing out\n", data);
       ast_channel_unlock(chan);
       return -1;
    }
    if (ast_strlen_zero(var)) {
       ast_log(LOG_NOTICE, "Variable %s doesn't exist - are you sure you wrote it correctly?\n", data);
       ast_channel_unlock(chan);
       return -1;
    }
    if (sscanf(var, "%30d%1c", &int_value, &endchar) == 0 || endchar != 0) {
       ast_log(LOG_NOTICE, "The content of ${%s} is not a numeric value - bailing out!\n", data);
       ast_channel_unlock(chan);
       return -1;
    }
    /* now we'll actually do something useful */
    if (!strcasecmp(cmd, "INC")) {              /* Increment variable */
       int_value++;
       modify_orig = 1;
    } else if (!strcasecmp(cmd, "DEC")) {       /* Decrement variable */
       int_value--;
       modify_orig = 1;
    }
    if (snprintf(returnvar, sizeof(returnvar), "%d", int_value) > 0) {
       pbx_builtin_setvar_helper(chan, data, returnvar);
       if (modify_orig) {
          ast_copy_string(buf, returnvar, len);
       }
       ret = 0;
    } else {
       pbx_builtin_setvar_helper(chan, data, "0");
       if (modify_orig) {
          ast_copy_string(buf, "0", len);
       }
       ast_log(LOG_NOTICE, "Variable %s refused to be %sREMENTED, setting value to 0", data, cmd);
       ret = 0;
    }
    ast_channel_unlock(chan);
    return ret;
 }
load_module()
static int load_module (void) static
Definition at line 708 of file func_math.c.
References ast_custom_function_register, and AST_TEST_REGISTER.
 {
    int res = 0;
    res |= ast_custom_function_register(&math_function);
    res |= ast_custom_function_register(&increment_function);
    res |= ast_custom_function_register(&decrement_function);
    res |= ast_custom_function_register(&acf_min);
    res |= ast_custom_function_register(&acf_max);
    res |= ast_custom_function_register(&acf_abs);
    AST_TEST_REGISTER(test_MATH_function);
    return res;
 }
math()
static int math (struct ast_channel * chan, const char * cmd, char * parse, char * buf, size_t len) static
Definition at line 180 of file func_math.c.
References ADDFUNCTION, args, AST_APP_ARG, ast_copy_string(), AST_DECLARE_APP_ARGS, ast_log, AST_STANDARD_APP_ARGS, ast_strlen_zero, BITWISEANDFUNCTION, BITWISEORFUNCTION, BITWISEXORFUNCTION, CHAR_RESULT, DIVIDEFUNCTION, EQFUNCTION, FLOAT_RESULT, GTEFUNCTION, GTFUNCTION, HEX_RESULT, INT_RESULT, LOG_WARNING, LTEFUNCTION, LTFUNCTION, MODULUSFUNCTION, MULTIPLYFUNCTION, NULL, POWFUNCTION, SHLEFTFUNCTION, SHRIGHTFUNCTION, and SUBTRACTFUNCTION.
 {
    double fnum1;
    double fnum2;
    double ftmp = 0;
    char *op;
    int iaction = -1;
    int type_of_result = FLOAT_RESULT;
    char *mvalue1, *mvalue2 = NULL, *mtype_of_result;
    int negvalue1 = 0;
    AST_DECLARE_APP_ARGS(args,
               AST_APP_ARG(argv0);
               AST_APP_ARG(argv1);
    );
    if (ast_strlen_zero(parse)) {
       ast_log(LOG_WARNING, "Syntax: MATH(<number1><op><number 2>[,<type_of_result>]) - missing argument!\n");
       return -1;
    }
    AST_STANDARD_APP_ARGS(args, parse);
    if (args.argc < 1) {
       ast_log(LOG_WARNING, "Syntax: MATH(<number1><op><number 2>[,<type_of_result>]) - missing argument!\n");
       return -1;
    }
    mvalue1 = args.argv0;
    if (mvalue1[0] == '-') {
       negvalue1 = 1;
       mvalue1++;
    }
    if ((op = strchr(mvalue1, '*'))) {
       iaction = MULTIPLYFUNCTION;
       *op = '\0';
    } else if ((op = strchr(mvalue1, '/'))) {
       iaction = DIVIDEFUNCTION;
       *op = '\0';
    } else if ((op = strchr(mvalue1, '%'))) {
       iaction = MODULUSFUNCTION;
       *op = '\0';
    } else if ((op = strchr(mvalue1, '^'))) {
       iaction = POWFUNCTION;
       *op = '\0';
    } else if ((op = strstr(mvalue1, "AND"))) {
       iaction = BITWISEANDFUNCTION;
       *op = '\0';
       op += 2;
    } else if ((op = strstr(mvalue1, "XOR"))) {
       iaction = BITWISEXORFUNCTION;
       *op = '\0';
       op += 2;
    } else if ((op = strstr(mvalue1, "OR"))) {
       iaction = BITWISEORFUNCTION;
       *op = '\0';
       ++op;
    } else if ((op = strchr(mvalue1, '>'))) {
       iaction = GTFUNCTION;
       *op = '\0';
       if (*(op + 1) == '=') {
          iaction = GTEFUNCTION;
          ++op;
       } else if (*(op + 1) == '>') {
          iaction = SHRIGHTFUNCTION;
          ++op;
       }
    } else if ((op = strchr(mvalue1, '<'))) {
       iaction = LTFUNCTION;
       *op = '\0';
       if (*(op + 1) == '=') {
          iaction = LTEFUNCTION;
          ++op;
       } else if (*(op + 1) == '<') {
          iaction = SHLEFTFUNCTION;
          ++op;
       }
    } else if ((op = strchr(mvalue1, '='))) {
       *op = '\0';
       if (*(op + 1) == '=') {
          iaction = EQFUNCTION;
          ++op;
       } else
          op = NULL;
    } else if ((op = strchr(mvalue1, '+'))) {
       iaction = ADDFUNCTION;
       *op = '\0';
    } else if ((op = strchr(mvalue1, '-'))) { /* subtraction MUST always be last, in case we have a negative second number */
       iaction = SUBTRACTFUNCTION;
       *op = '\0';
    }
    if (op)
       mvalue2 = op + 1;
    /* detect wanted type of result */
    mtype_of_result = args.argv1;
    if (mtype_of_result) {
       if (!strcasecmp(mtype_of_result, "float")
           || !strcasecmp(mtype_of_result, "f"))
          type_of_result = FLOAT_RESULT;
       else if (!strcasecmp(mtype_of_result, "int")
           || !strcasecmp(mtype_of_result, "i"))
          type_of_result = INT_RESULT;
       else if (!strcasecmp(mtype_of_result, "hex")
           || !strcasecmp(mtype_of_result, "h"))
          type_of_result = HEX_RESULT;
       else if (!strcasecmp(mtype_of_result, "char")
           || !strcasecmp(mtype_of_result, "c"))
          type_of_result = CHAR_RESULT;
       else {
          ast_log(LOG_WARNING, "Unknown type of result requested '%s'.\n",
                mtype_of_result);
          return -1;
       }
    }
    if (!mvalue2) {
       ast_log(LOG_WARNING,
             "Supply all the parameters - just this once, please\n");
       return -1;
    }
    if (sscanf(mvalue1, "%30lf", &fnum1) != 1) {
       ast_log(LOG_WARNING, "'%s' is not a valid number\n", mvalue1);
       return -1;
    }
    if (sscanf(mvalue2, "%30lf", &fnum2) != 1) {
       ast_log(LOG_WARNING, "'%s' is not a valid number\n", mvalue2);
       return -1;
    }
    if (negvalue1)
       fnum1 = 0 - fnum1;
    switch (iaction) {
    case ADDFUNCTION:
       ftmp = fnum1 + fnum2;
       break;
    case DIVIDEFUNCTION:
       if (fnum2 <= 0)
          ftmp = 0;         /* can't do a divide by 0 */
       else
          ftmp = (fnum1 / fnum2);
       break;
    case MULTIPLYFUNCTION:
       ftmp = (fnum1 * fnum2);
       break;
    case SUBTRACTFUNCTION:
       ftmp = (fnum1 - fnum2);
       break;
    case MODULUSFUNCTION:
       {
          int inum1 = fnum1;
          int inum2 = fnum2;
          if (inum2 == 0) {
             ftmp = 0;
          } else {
             ftmp = (inum1 % inum2);
          }
          break;
       }
    case POWFUNCTION:
       ftmp = pow(fnum1, fnum2);
       break;
    case SHLEFTFUNCTION:
       {
          int inum1 = fnum1;
          int inum2 = fnum2;
          ftmp = (inum1 << inum2);
          break;
       }
    case SHRIGHTFUNCTION:
       {
          int inum1 = fnum1;
          int inum2 = fnum2;
          ftmp = (inum1 >> inum2);
          break;
       }
    case BITWISEANDFUNCTION:
       {
          int inum1 = fnum1;
          int inum2 = fnum2;
          ftmp = (inum1 & inum2);
          break;
       }
    case BITWISEXORFUNCTION:
       {
          int inum1 = fnum1;
          int inum2 = fnum2;
          ftmp = (inum1 ^ inum2);
          break;
       }
    case BITWISEORFUNCTION:
       {
          int inum1 = fnum1;
          int inum2 = fnum2;
          ftmp = (inum1 | inum2);
          break;
       }
    case GTFUNCTION:
       ast_copy_string(buf, (fnum1 > fnum2) ? "TRUE" : "FALSE", len);
       break;
    case LTFUNCTION:
       ast_copy_string(buf, (fnum1 < fnum2) ? "TRUE" : "FALSE", len);
       break;
    case GTEFUNCTION:
       ast_copy_string(buf, (fnum1 >= fnum2) ? "TRUE" : "FALSE", len);
       break;
    case LTEFUNCTION:
       ast_copy_string(buf, (fnum1 <= fnum2) ? "TRUE" : "FALSE", len);
       break;
    case EQFUNCTION:
       ast_copy_string(buf, (fnum1 == fnum2) ? "TRUE" : "FALSE", len);
       break;
    default:
       ast_log(LOG_WARNING,
             "Something happened that neither of us should be proud of %d\n",
             iaction);
       return -1;
    }
    if (iaction < GTFUNCTION || iaction > EQFUNCTION) {
       if (type_of_result == FLOAT_RESULT)
          snprintf(buf, len, "%f", ftmp);
       else if (type_of_result == INT_RESULT)
          snprintf(buf, len, "%i", (int) ftmp);
       else if (type_of_result == HEX_RESULT)
          snprintf(buf, len, "%x", (unsigned int) ftmp);
       else if (type_of_result == CHAR_RESULT)
          snprintf(buf, len, "%c", (unsigned char) ftmp);
    }
    return 0;
 }
unload_module()
static int unload_module (void) static
Definition at line 693 of file func_math.c.
References ast_custom_function_unregister(), and AST_TEST_UNREGISTER.
 {
    int res = 0;
    res |= ast_custom_function_unregister(&math_function);
    res |= ast_custom_function_unregister(&increment_function);
    res |= ast_custom_function_unregister(&decrement_function);
    res |= ast_custom_function_unregister(&acf_min);
    res |= ast_custom_function_unregister(&acf_max);
    res |= ast_custom_function_unregister(&acf_abs);
    AST_TEST_UNREGISTER(test_MATH_function);
    return res;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Mathematical dialplan function" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, } static
Definition at line 723 of file func_math.c.
acf_abs
struct ast_custom_function acf_abs static
Initial value:
= {
   .name = "ABS",
   .read = acf_abs_exec,
   .read_max = 12,
}
Definition at line 636 of file func_math.c.
acf_max
struct ast_custom_function acf_max static
Initial value:
= {
   .name = "MAX",
   .read = acf_max_exec,
   .read_max = 12,
}
Definition at line 630 of file func_math.c.
acf_min
struct ast_custom_function acf_min static
Initial value:
= {
   .name = "MIN",
   .read = acf_min_exec,
   .read_max = 12,
}
Definition at line 624 of file func_math.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 723 of file func_math.c.
decrement_function
struct ast_custom_function decrement_function static
Initial value:
= {
   .name = "DEC",
   .read = crement_function_read,
}
Definition at line 619 of file func_math.c.
increment_function
struct ast_custom_function increment_function static
Initial value:
= {
   .name = "INC",
   .read = crement_function_read,
}
Definition at line 614 of file func_math.c.
math_function
struct ast_custom_function math_function static
Initial value:
= {
   .name = "MATH",
   .read = math
}
Definition at line 609 of file func_math.c.