Asterisk - The Open Source Telephony Project: bt_conv.c File Reference
bt_conv.c File Reference
#include <sys/param.h>
#include <stdio.h>
#include "../include/db.h"
#include "btree.h"
Functions
void __bt_pgin (void *t, pgno_t pg, void *pp)
void __bt_pgout (void *t, pgno_t pg, void *pp)
static void mswap __P ((PAGE *))
static void mswap (PAGE *pg)
Function Documentation
__bt_pgin()
void __bt_pgin (void * t, pgno_t pg, void * pp)
Definition at line 61 of file bt_conv.c.
References B_NEEDSWAP, F_ISSET, _page::flags, GETBINTERNAL, GETBLEAF, _page::linp, _page::lower, mswap(), NEXTINDEX, _page::nextpg, P_BIGDATA, P_BIGKEY, P_BINTERNAL, P_BLEAF, P_META, P_TYPE, _page::pgno, _page::prevpg, and _page::upper.
Referenced by __bt_open().
 {
    PAGE *h;
    indx_t i, top;
    u_char flags;
    char *p;
    if (!F_ISSET(((BTREE *)t), B_NEEDSWAP))
       return;
    if (pg == P_META) {
       mswap(pp);
       return;
    }
    h = pp;
    M_32_SWAP(h->pgno);
    M_32_SWAP(h->prevpg);
    M_32_SWAP(h->nextpg);
    M_32_SWAP(h->flags);
    M_16_SWAP(h->lower);
    M_16_SWAP(h->upper);
    top = NEXTINDEX(h);
    if ((h->flags & P_TYPE) == P_BINTERNAL)
       for (i = 0; i < top; i++) {
          M_16_SWAP(h->linp[i]);
          p = (char *)GETBINTERNAL(h, i);
          P_32_SWAP(p);
          p += sizeof(u_int32_t);
          P_32_SWAP(p);
          p += sizeof(pgno_t);
          if (*(u_char *)p & P_BIGKEY) {
             p += sizeof(u_char);
             P_32_SWAP(p);
             p += sizeof(pgno_t);
             P_32_SWAP(p);
          }
       }
    else if ((h->flags & P_TYPE) == P_BLEAF)
       for (i = 0; i < top; i++) {
          M_16_SWAP(h->linp[i]);
          p = (char *)GETBLEAF(h, i);
          P_32_SWAP(p);
          p += sizeof(u_int32_t);
          P_32_SWAP(p);
          p += sizeof(u_int32_t);
          flags = *(u_char *)p;
          if (flags & (P_BIGKEY | P_BIGDATA)) {
             p += sizeof(u_char);
             if (flags & P_BIGKEY) {
                P_32_SWAP(p);
                p += sizeof(pgno_t);
                P_32_SWAP(p);
             }
             if (flags & P_BIGDATA) {
                p += sizeof(u_int32_t);
                P_32_SWAP(p);
                p += sizeof(pgno_t);
                P_32_SWAP(p);
             }
          }
       }
 }
__bt_pgout()
void __bt_pgout (void * t, pgno_t pg, void * pp)
Definition at line 129 of file bt_conv.c.
References B_NEEDSWAP, F_ISSET, _page::flags, GETBINTERNAL, GETBLEAF, _page::linp, _page::lower, mswap(), NEXTINDEX, _page::nextpg, P_BIGDATA, P_BIGKEY, P_BINTERNAL, P_BLEAF, P_META, P_TYPE, _page::pgno, _page::prevpg, and _page::upper.
Referenced by __bt_open().
 {
    PAGE *h;
    indx_t i, top;
    u_char flags;
    char *p;
    if (!F_ISSET(((BTREE *)t), B_NEEDSWAP))
       return;
    if (pg == P_META) {
       mswap(pp);
       return;
    }
    h = pp;
    top = NEXTINDEX(h);
    if ((h->flags & P_TYPE) == P_BINTERNAL)
       for (i = 0; i < top; i++) {
          p = (char *)GETBINTERNAL(h, i);
          P_32_SWAP(p);
          p += sizeof(u_int32_t);
          P_32_SWAP(p);
          p += sizeof(pgno_t);
          if (*(u_char *)p & P_BIGKEY) {
             p += sizeof(u_char);
             P_32_SWAP(p);
             p += sizeof(pgno_t);
             P_32_SWAP(p);
          }
          M_16_SWAP(h->linp[i]);
       }
    else if ((h->flags & P_TYPE) == P_BLEAF)
       for (i = 0; i < top; i++) {
          p = (char *)GETBLEAF(h, i);
          P_32_SWAP(p);
          p += sizeof(u_int32_t);
          P_32_SWAP(p);
          p += sizeof(u_int32_t);
          flags = *(u_char *)p;
          if (flags & (P_BIGKEY | P_BIGDATA)) {
             p += sizeof(u_char);
             if (flags & P_BIGKEY) {
                P_32_SWAP(p);
                p += sizeof(pgno_t);
                P_32_SWAP(p);
             }
             if (flags & P_BIGDATA) {
                p += sizeof(u_int32_t);
                P_32_SWAP(p);
                p += sizeof(pgno_t);
                P_32_SWAP(p);
             }
          }
          M_16_SWAP(h->linp[i]);
       }
    M_32_SWAP(h->pgno);
    M_32_SWAP(h->prevpg);
    M_32_SWAP(h->nextpg);
    M_32_SWAP(h->flags);
    M_16_SWAP(h->lower);
    M_16_SWAP(h->upper);
 }
__P()
static void mswap __P ((PAGE *)) static
mswap()
static void mswap (PAGE * pg) static
Definition at line 203 of file bt_conv.c.
Referenced by __bt_pgin(), and __bt_pgout().
 {
    char *p;
    p = (char *)pg;
    P_32_SWAP(p);     /* magic */
    p += sizeof(u_int32_t);
    P_32_SWAP(p);     /* version */
    p += sizeof(u_int32_t);
    P_32_SWAP(p);     /* psize */
    p += sizeof(u_int32_t);
    P_32_SWAP(p);     /* free */
    p += sizeof(u_int32_t);
    P_32_SWAP(p);     /* nrecs */
    p += sizeof(u_int32_t);
    P_32_SWAP(p);     /* flags */
    p += sizeof(u_int32_t);
 }