Asterisk - The Open Source Telephony Project: pbx_realtime.c File Reference
pbx_realtime.c File Reference
Realtime PBX Module.
#include "asterisk.h"
#include <signal.h>
#include "asterisk/file.h"
#include "asterisk/logger.h"
#include "asterisk/channel.h"
#include "asterisk/config.h"
#include "asterisk/pbx.h"
#include "asterisk/module.h"
#include "asterisk/frame.h"
#include "asterisk/term.h"
#include "asterisk/manager.h"
#include "asterisk/cli.h"
#include "asterisk/lock.h"
#include "asterisk/linkedlists.h"
#include "asterisk/chanvars.h"
#include "asterisk/sched.h"
#include "asterisk/io.h"
#include "asterisk/utils.h"
#include "asterisk/astdb.h"
#include "asterisk/app.h"
#include "asterisk/astobj2.h"
#include "asterisk/stasis_channels.h"
Data Structures
struct cache_entry
Macros
#define EXT_DATA_SIZE 256
#define MODE_CANMATCH 2
#define MODE_MATCH 0
#define MODE_MATCHMORE 1
Enumerations
enum option_flags { OPTION_CHEAT = (1 << 0), OPTION_NUMGAMES = (1 << 1), OPTION_WAIT = (1 << 0), OPTION_PATTERNS_DISABLED = (1 << 0) }
Functions
AST_MODULE_INFO_STANDARD_EXTENDED (ASTERISK_GPL_KEY, "Realtime Switch")
static int cache_cmp (void *obj, void *arg, int flags)
static int cache_hash (const void *obj, const int flags)
static void * cleanup (void *unused)
static struct ast_variable * dup_vars (struct ast_variable *v)
static int extension_length_comparator (struct ast_category *p, struct ast_category *q)
static void free_entry (void *obj)
static int load_module (void)
static int purge_old_fn (void *obj, void *arg, int flags)
static int realtime_canmatch (struct ast_channel *chan, const char *context, const char *exten, int priority, const char *callerid, const char *data)
static struct ast_variable * realtime_common (const char *context, const char *exten, int priority, const char *data, int mode)
static int realtime_exec (struct ast_channel *chan, const char *context, const char *exten, int priority, const char *callerid, const char *data)
static int realtime_exists (struct ast_channel *chan, const char *context, const char *exten, int priority, const char *callerid, const char *data)
static int realtime_matchmore (struct ast_channel *chan, const char *context, const char *exten, int priority, const char *callerid, const char *data)
static struct ast_variable * realtime_switch_common (const char *table, const char *context, const char *exten, int priority, int mode, struct ast_flags flags)
static int unload_module (void)
Variables
struct ao2_container * cache
pthread_t cleanup_thread = 0
static struct ast_switch realtime_switch
static const struct ast_app_option switch_opts [128] = { [ 'p' ] = { .flag = OPTION_PATTERNS_DISABLED }, }
Detailed Description
Realtime PBX Module.
See also: ARA - The Asterisk Realtime Interface
Definition in file pbx_realtime.c.
Macro Definition Documentation
EXT_DATA_SIZE
#define EXT_DATA_SIZE 256
Definition at line 59 of file pbx_realtime.c.
Referenced by realtime_exec().
MODE_CANMATCH
#define MODE_CANMATCH 2
Definition at line 57 of file pbx_realtime.c.
Referenced by realtime_canmatch(), and realtime_switch_common().
MODE_MATCH
#define MODE_MATCH 0
Definition at line 55 of file pbx_realtime.c.
Referenced by realtime_common(), realtime_exec(), realtime_exists(), and realtime_switch_common().
MODE_MATCHMORE
#define MODE_MATCHMORE 1
Definition at line 56 of file pbx_realtime.c.
Referenced by realtime_matchmore(), and realtime_switch_common().
Enumeration Type Documentation
option_flags
enum option_flags
Enumerator
OPTION_CHEAT
OPTION_NUMGAMES
OPTION_WAIT
OPTION_PATTERNS_DISABLED
Definition at line 61 of file pbx_realtime.c.
                   {
    OPTION_PATTERNS_DISABLED = (1 << 0),
 };
Function Documentation
AST_MODULE_INFO_STANDARD_EXTENDED()
AST_MODULE_INFO_STANDARD_EXTENDED (ASTERISK_GPL_KEY , "Realtime Switch")
Referenced by load_module().
cache_cmp()
static int cache_cmp (void * obj, void * arg, int flags) static
Definition at line 86 of file pbx_realtime.c.
References CMP_MATCH, cache_entry::context, cache_entry::exten, and cache_entry::priority.
Referenced by load_module().
 {
    struct cache_entry *e = obj, *f = arg;
    return e->priority != f->priority ? 0 :
       strcmp(e->exten, f->exten) ? 0 :
       strcmp(e->context, f->context) ? 0 :
       CMP_MATCH;
 }
cache_hash()
static int cache_hash (const void * obj, const int flags) static
Definition at line 80 of file pbx_realtime.c.
References ast_str_case_hash(), cache_entry::exten, and cache_entry::priority.
Referenced by load_module().
 {
    const struct cache_entry *e = obj;
    return ast_str_case_hash(e->exten) + e->priority;
 }
cleanup()
static void* cleanup (void * unused) static
Definition at line 124 of file pbx_realtime.c.
References ao2_callback, ao2_container_count(), ast_tvnow(), NULL, OBJ_MULTIPLE, OBJ_NODATA, OBJ_UNLINK, and purge_old_fn().
Referenced by _sip_tcp_helper_thread(), ast_event_new(), ast_rtcp_write(), ast_rtp_dtmf_end_with_duration(), ast_sockaddr_resolve(), ast_stir_shaken_sign(), AST_TEST_DEFINE(), astobj2_test_1_helper(), build_user(), create_cts(), create_message_types(), digest_check_auth(), digest_create_request_with_auth(), handle_uri(), invalid_record_test(), load_module(), nominal_test(), off_nominal_test(), pjsip_outbound_registration_metrics_init(), query_set_test(), realtime_peer(), sendtext_exec(), set_outbound_authentication_credentials(), set_outbound_initial_authentication_credentials(), sfu_topologies_on_source_change(), sipinfo_send(), softmix_bridge_stream_sources_update(), stir_shaken_sign(), and stir_shaken_verify_json().
 {
    struct timespec forever = { 999999999, 0 }, one_second = { 1, 0 };
    struct timeval now;
    for (;;) {
       pthread_testcancel();
       if (ao2_container_count(cache) == 0) {
          nanosleep(&forever, NULL);
       }
       pthread_testcancel();
       now = ast_tvnow();
       ao2_callback(cache, OBJ_MULTIPLE | OBJ_UNLINK | OBJ_NODATA, purge_old_fn, &now);
       pthread_testcancel();
       nanosleep(&one_second, NULL);
    }
    return NULL;
 }
dup_vars()
static struct ast_variable* dup_vars (struct ast_variable * v) static
Definition at line 95 of file pbx_realtime.c.
References ast_variable_new, ast_variables_destroy(), ast_variable::file, ast_variable::name, ast_variable::next, NULL, and ast_variable::value.
Referenced by realtime_common().
 {
    struct ast_variable *new, *list = NULL;
    for (; v; v = v->next) {
       if (!(new = ast_variable_new(v->name, v->value, v->file))) {
          ast_variables_destroy(list);
          return NULL;
       }
       /* Reversed list in cache, but when we duplicate out of the cache,
        * it's back to correct order. */
       new->next = list;
       list = new;
    }
    return list;
 }
extension_length_comparator()
static int extension_length_comparator (struct ast_category * p, struct ast_category * q) static
Definition at line 144 of file pbx_realtime.c.
References ast_variable_find(), and S_OR.
Referenced by realtime_switch_common().
 {
    const char *extenp = S_OR(ast_variable_find(p, "exten"), "");
    const char *extenq = S_OR(ast_variable_find(q, "exten"), "");
    return strlen(extenp) - strlen(extenq);
 }
free_entry()
static void free_entry (void * obj) static
Definition at line 111 of file pbx_realtime.c.
References ast_variables_destroy(), and cache_entry::var.
Referenced by realtime_common().
 {
    struct cache_entry *e = obj;
    ast_variables_destroy(e->var);
 }
load_module()
static int load_module (void) static
Definition at line 413 of file pbx_realtime.c.
References AO2_ALLOC_OPT_LOCK_MUTEX, ao2_container_alloc_hash, AST_MODULE_INFO_STANDARD_EXTENDED(), AST_MODULE_LOAD_FAILURE, AST_MODULE_LOAD_SUCCESS, ast_pthread_create, ast_register_switch(), ASTERISK_GPL_KEY, cache_cmp(), cache_hash(), cleanup(), and NULL.
 {
    cache = ao2_container_alloc_hash(AO2_ALLOC_OPT_LOCK_MUTEX, 0, 573,
       cache_hash, NULL, cache_cmp);
    if (!cache) {
       return AST_MODULE_LOAD_FAILURE;
    }
    if (ast_pthread_create(&cleanup_thread, NULL, cleanup, NULL)) {
       return AST_MODULE_LOAD_FAILURE;
    }
    if (ast_register_switch(&realtime_switch))
       return AST_MODULE_LOAD_FAILURE;
    return AST_MODULE_LOAD_SUCCESS;
 }
purge_old_fn()
static int purge_old_fn (void * obj, void * arg, int flags) static
Definition at line 117 of file pbx_realtime.c.
References ast_tvdiff_ms(), CMP_MATCH, and cache_entry::when.
Referenced by cleanup().
 {
    struct cache_entry *e = obj;
    struct timeval *now = arg;
    return ast_tvdiff_ms(*now, e->when) >= 1000 ? CMP_MATCH : 0;
 }
realtime_canmatch()
static int realtime_canmatch (struct ast_channel * chan, const char * context, const char * exten, int priority, const char * callerid, const char * data) static
Definition at line 299 of file pbx_realtime.c.
References ast_variables_destroy(), MODE_CANMATCH, realtime_common(), and cache_entry::var.
 {
    struct ast_variable *var = realtime_common(context, exten, priority, data, MODE_CANMATCH);
    if (var) {
       ast_variables_destroy(var);
       return 1;
    }
    return 0;
 }
realtime_common()
static struct ast_variable* realtime_common (const char * context, const char * exten, int priority, const char * data, int mode) static
Definition at line 229 of file pbx_realtime.c.
References ao2_alloc, ao2_find, ao2_link, ao2_ref, ast_app_parse_options(), ast_copy_string(), AST_MAX_EXTENSION, ast_strdupa, ast_strlen_zero, ast_tvnow(), ast_variables_destroy(), buf, cache_entry::context, dup_vars(), cache_entry::exten, free_entry(), MODE_MATCH, NULL, OBJ_POINTER, cache_entry::priority, realtime_switch_common(), S_OR, switch_opts, table, cache_entry::var, and cache_entry::when.
Referenced by realtime_canmatch(), realtime_exec(), realtime_exists(), and realtime_matchmore().
 {
    const char *ctx = NULL;
    char *table;
    struct ast_variable *var=NULL;
    struct ast_flags flags = { 0, };
    struct cache_entry *ce;
    struct {
       struct cache_entry ce;
       char exten[AST_MAX_EXTENSION];
    } cache_search = { { .priority = priority, .context = (char *) context }, };
    char *buf = ast_strdupa(data);
    /* "Realtime" prefix is stripped off in the parent engine.  The
     * remaining string is: [[context@]table][/opts] */
    char *opts = strchr(buf, '/');
    if (opts)
       *opts++ = '\0';
    table = strchr(buf, '@');
    if (table) {
       *table++ = '\0';
       ctx = buf;
    }
    ctx = S_OR(ctx, context);
    table = S_OR(table, "extensions");
    if (!ast_strlen_zero(opts)) {
       ast_app_parse_options(switch_opts, &flags, NULL, opts);
    }
    ast_copy_string(cache_search.exten, exten, sizeof(cache_search.exten));
    if (mode == MODE_MATCH && (ce = ao2_find(cache, &cache_search, OBJ_POINTER))) {
       var = dup_vars(ce->var);
       ao2_ref(ce, -1);
    } else {
       var = realtime_switch_common(table, ctx, exten, priority, mode, flags);
       do {
          struct ast_variable *new;
          /* Only cache matches */
          if (mode != MODE_MATCH) {
             break;
          }
          if (!(new = dup_vars(var))) {
             break;
          }
          if (!(ce = ao2_alloc(sizeof(*ce) + strlen(exten) + strlen(context), free_entry))) {
             ast_variables_destroy(new);
             break;
          }
          ce->context = ce->exten + strlen(exten) + 1;
          strcpy(ce->exten, exten); /* SAFE */
          strcpy(ce->context, context); /* SAFE */
          ce->priority = priority;
          ce->var = new;
          ce->when = ast_tvnow();
          ao2_link(cache, ce);
          pthread_kill(cleanup_thread, SIGURG);
          ao2_ref(ce, -1);
       } while (0);
    }
    return var;
 }
realtime_exec()
static int realtime_exec (struct ast_channel * chan, const char * context, const char * exten, int priority, const char * callerid, const char * data) static
Definition at line 309 of file pbx_realtime.c.
References a, app, ast_channel_appl(), ast_channel_appl_set(), ast_channel_context(), ast_channel_data(), ast_channel_data_set(), ast_channel_exten(), ast_channel_lock, ast_channel_name(), ast_channel_priority(), ast_channel_publish_snapshot(), AST_CHANNEL_SNAPSHOT_INVALIDATE_DIALPLAN, ast_channel_snapshot_invalidate_segment(), ast_channel_snapshot_type(), ast_channel_unlock, ast_log, ast_strdupa, ast_strlen_zero, ast_variables_destroy(), ast_verb, COLOR_BRCYAN, COLOR_BRMAGENTA, EXT_DATA_SIZE, LOG_NOTICE, LOG_WARNING, MODE_MATCH, ast_variable::name, ast_variable::next, NULL, pbx_exec(), pbx_findapp(), pbx_substitute_variables_helper(), realtime_common(), S_OR, term_color(), ast_variable::value, and cache_entry::var.
 {
    int res = -1;
    struct ast_variable *var = realtime_common(context, exten, priority, data, MODE_MATCH);
    if (var) {
       char *appdata_tmp = "";
       char *app = NULL;
       struct ast_variable *v;
       for (v = var; v ; v = v->next) {
          if (!strcasecmp(v->name, "app"))
             app = ast_strdupa(v->value);
          else if (!strcasecmp(v->name, "appdata")) {
             appdata_tmp = ast_strdupa(v->value);
          }
       }
       ast_variables_destroy(var);
       if (!ast_strlen_zero(app)) {
          struct ast_app *a = pbx_findapp(app);
          if (a) {
             char appdata[512];
             char tmp1[80];
             char tmp2[80];
             char tmp3[EXT_DATA_SIZE];
             appdata[0] = 0; /* just in case the substitute var func isn't called */
             if(!ast_strlen_zero(appdata_tmp))
                pbx_substitute_variables_helper(chan, appdata_tmp, appdata, sizeof(appdata) - 1);
             ast_verb(3, "Executing [%s@%s:%d] %s(\"%s\", \"%s\")\n",
                   ast_channel_exten(chan), ast_channel_context(chan), ast_channel_priority(chan),
                    term_color(tmp1, app, COLOR_BRCYAN, 0, sizeof(tmp1)),
                    term_color(tmp2, ast_channel_name(chan), COLOR_BRMAGENTA, 0, sizeof(tmp2)),
                    term_color(tmp3, S_OR(appdata, ""), COLOR_BRMAGENTA, 0, sizeof(tmp3)));
             if (ast_channel_snapshot_type()) {
                char *tmp_appl;
                char *tmp_data;
                ast_channel_lock(chan);
                /* Force a new dialplan segment that will be unique to use so we can update it with the
                 * information we want. In the future when a channel snapshot is published this will
                 * occur again and unset this flag.
                 */
                ast_channel_snapshot_invalidate_segment(chan, AST_CHANNEL_SNAPSHOT_INVALIDATE_DIALPLAN);
                /* pbx_exec sets application name and data, but we don't want to log
                 * every exec. Just update the snapshot here instead. Publishing the
                 * snapshot retrieves data from the channel object directly, so save
                 * current values prior to publishing so they can be restored after.
                 */
                tmp_appl = ast_channel_appl(chan) ? ast_strdupa(ast_channel_appl(chan)) : NULL;
                tmp_data = ast_channel_data(chan) ? ast_strdupa(ast_channel_data(chan)) : NULL;
                ast_channel_appl_set(chan, app);
                ast_channel_data_set(chan, !ast_strlen_zero(appdata) ? appdata : "(NULL)");
                ast_channel_publish_snapshot(chan);
                ast_channel_appl_set(chan, tmp_appl);
                ast_channel_data_set(chan, tmp_data);
                ast_channel_unlock(chan);
             }
             res = pbx_exec(chan, a, appdata);
          } else
             ast_log(LOG_NOTICE, "No such application '%s' for extension '%s' in context '%s'\n", app, exten, context);
       } else {
          ast_log(LOG_WARNING, "No application specified for realtime extension '%s' in context '%s'\n", exten, context);
       }
    }
    return res;
 }
realtime_exists()
static int realtime_exists (struct ast_channel * chan, const char * context, const char * exten, int priority, const char * callerid, const char * data) static
Definition at line 289 of file pbx_realtime.c.
References ast_variables_destroy(), MODE_MATCH, realtime_common(), and cache_entry::var.
 {
    struct ast_variable *var = realtime_common(context, exten, priority, data, MODE_MATCH);
    if (var) {
       ast_variables_destroy(var);
       return 1;
    }
    return 0;
 }
realtime_matchmore()
static int realtime_matchmore (struct ast_channel * chan, const char * context, const char * exten, int priority, const char * callerid, const char * data) static
Definition at line 382 of file pbx_realtime.c.
References ast_variables_destroy(), MODE_MATCHMORE, realtime_common(), and cache_entry::var.
 {
    struct ast_variable *var = realtime_common(context, exten, priority, data, MODE_MATCHMORE);
    if (var) {
       ast_variables_destroy(var);
       return 1;
    }
    return 0;
 }
realtime_switch_common()
static struct ast_variable* realtime_switch_common (const char * table, const char * context, const char * exten, int priority, int mode, struct ast_flags flags) static
Definition at line 166 of file pbx_realtime.c.
References ast_category_browse(), ast_category_detach_variables(), ast_category_get(), ast_config_destroy(), ast_config_sort_categories(), ast_copy_string(), ast_extension_close(), ast_extension_match(), ast_load_realtime(), ast_load_realtime_multientry(), AST_MAX_EXTENSION, ast_test_flag, ast_variable_retrieve(), extension_length_comparator(), match(), MODE_CANMATCH, MODE_MATCH, MODE_MATCHMORE, NULL, OPTION_PATTERNS_DISABLED, SENTINEL, and cache_entry::var.
Referenced by realtime_common().
 {
    struct ast_variable *var;
    struct ast_config *cfg;
    char pri[20];
    char *ematch;
    char rexten[AST_MAX_EXTENSION + 20]="";
    int match;
    /* Optimization: since we don't support hints in realtime, it's silly to
     * query for a hint here, since we won't actually do anything with it.
     * This just wastes CPU time and resources. */
    if (priority < 0) {
       return NULL;
    }
    snprintf(pri, sizeof(pri), "%d", priority);
    switch(mode) {
    case MODE_MATCHMORE:
       ematch = "exten LIKE";
       snprintf(rexten, sizeof(rexten), "%s_%%", exten);
       break;
    case MODE_CANMATCH:
       ematch = "exten LIKE";
       snprintf(rexten, sizeof(rexten), "%s%%", exten);
       break;
    case MODE_MATCH:
    default:
       ematch = "exten";
       ast_copy_string(rexten, exten, sizeof(rexten));
    }
    var = ast_load_realtime(table, ematch, rexten, "context", context, "priority", pri, SENTINEL);
    if (!var && !ast_test_flag(&flags, OPTION_PATTERNS_DISABLED)) {
       cfg = ast_load_realtime_multientry(table, "exten LIKE", "\\_%", "context", context, "priority", pri, SENTINEL);
       if (cfg) {
          char *cat = NULL;
          /* Sort so that longer patterns are checked first */
          ast_config_sort_categories(cfg, 1, extension_length_comparator);
          while ((cat = ast_category_browse(cfg, cat))) {
             const char *realtime_exten = ast_variable_retrieve(cfg, cat, "exten");
             switch(mode) {
             case MODE_MATCHMORE:
                match = ast_extension_close(realtime_exten, exten, 1);
                break;
             case MODE_CANMATCH:
                match = ast_extension_close(realtime_exten, exten, 0);
                break;
             case MODE_MATCH:
             default:
                match = ast_extension_match(realtime_exten, exten);
             }
             if (match) {
                var = ast_category_detach_variables(ast_category_get(cfg, cat, NULL));
                break;
             }
          }
          ast_config_destroy(cfg);
       }
    }
    return var;
 }
unload_module()
static int unload_module (void) static
Definition at line 402 of file pbx_realtime.c.
References ao2_ref, ast_unregister_switch(), and NULL.
 {
    ast_unregister_switch(&realtime_switch);
    pthread_cancel(cleanup_thread);
    pthread_kill(cleanup_thread, SIGURG);
    pthread_join(cleanup_thread, NULL);
    /* Destroy all remaining entries */
    ao2_ref(cache, -1);
    return 0;
 }
Variable Documentation
cache
struct ao2_container* cache
Definition at line 77 of file pbx_realtime.c.
Referenced by ast_ari_endpoints_list(), ast_ari_endpoints_list_by_tech(), AST_TEST_DEFINE(), cache_dtor(), load_module(), sorcery_memory_cache_ami_expire(), sorcery_memory_cache_ami_expire_object(), sorcery_memory_cache_ami_populate(), sorcery_memory_cache_ami_stale(), sorcery_memory_cache_ami_stale_object(), sorcery_memory_cache_complete_name(), sorcery_memory_cache_complete_object_name(), sorcery_memory_cache_destructor(), sorcery_memory_cache_dump(), sorcery_memory_cache_expire(), sorcery_memory_cache_hash(), sorcery_memory_cache_populate(), sorcery_memory_cache_retrieve_fields(), sorcery_memory_cache_retrieve_multiple(), sorcery_memory_cache_retrieve_prefix(), sorcery_memory_cache_retrieve_regex(), sorcery_memory_cache_show(), sorcery_memory_cache_stale(), sorcery_memory_cached_object_destructor(), stasis_cache_create_full(), stasis_caching_topic_create(), and unload_module().
cleanup_thread
pthread_t cleanup_thread = 0
Definition at line 78 of file pbx_realtime.c.
realtime_switch
struct ast_switch realtime_switch static
Definition at line 392 of file pbx_realtime.c.
switch_opts
const struct ast_app_option switch_opts[128] = { [ 'p' ] = { .flag = OPTION_PATTERNS_DISABLED }, } static
Definition at line 67 of file pbx_realtime.c.
Referenced by realtime_common().