Asterisk - The Open Source Telephony Project: cel_sqlite3_custom.c File Reference
cel_sqlite3_custom.c File Reference
Custom SQLite3 CEL records.
#include "asterisk.h"
#include <sqlite3.h>
#include "asterisk/paths.h"
#include "asterisk/channel.h"
#include "asterisk/cel.h"
#include "asterisk/module.h"
#include "asterisk/config.h"
#include "asterisk/pbx.h"
#include "asterisk/logger.h"
#include "asterisk/utils.h"
#include "asterisk/cli.h"
#include "asterisk/options.h"
#include "asterisk/stringfields.h"
Data Structures
struct sql_values
struct values
Macros
#define SQLITE_BACKEND_NAME "CEL sqlite3 custom backend"
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static void free_config (void)
static int load_column_config (const char *tmp)
static int load_config (int reload)
static int load_module (void)
static int load_values_config (const char *tmp)
static int reload (void)
static int unload_module (void)
static void write_cel (struct ast_event *event)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "SQLite3 Custom CEL Module" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_EXTENDED, .load = load_module, .unload = unload_module, .reload = reload, .load_pri = AST_MODPRI_CDR_DRIVER, .requires = "cel", }
static const struct ast_module_info * ast_module_info = &__mod_info
static int busy_timeout
static char * columns
static const char config_file [] = "cel_sqlite3_custom.conf"
static sqlite3 * db = NULL
static ast_mutex_t lock = { PTHREAD_RECURSIVE_MUTEX_INITIALIZER_NP , NULL, {1, 0} }
static struct sql_values sql_values = { .first = NULL, .last = NULL, .lock = { PTHREAD_RECURSIVE_MUTEX_INITIALIZER_NP , NULL, {1, 0} } , }
static char table [80]
Detailed Description
Custom SQLite3 CEL records.
Author
Adapted by Steve Murphy murf@.nosp@m.digi.nosp@m.um.co.nosp@m.m from Alejandro Rios aleja.nosp@m.ndro.nosp@m..rios.nosp@m.@ava.nosp@m.tar.c.nosp@m.om.c.nosp@m.o and Russell Bryant russe.nosp@m.ll@d.nosp@m.igium.nosp@m..com from cdr_mysql_custom by Edward Eastman ed@dm.nosp@m.3.co.nosp@m..uk, and cdr_sqlite by Holger Schurig hs423.nosp@m.3@ma.nosp@m.il.mn.nosp@m.-sol.nosp@m.ution.nosp@m.s.de
See also AstCEL
Definition in file cel_sqlite3_custom.c.
Macro Definition Documentation
SQLITE_BACKEND_NAME
#define SQLITE_BACKEND_NAME "CEL sqlite3 custom backend"
Definition at line 58 of file cel_sqlite3_custom.c.
Referenced by load_module(), and unload_module().
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 364 of file cel_sqlite3_custom.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 364 of file cel_sqlite3_custom.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 364 of file cel_sqlite3_custom.c.
free_config()
static void free_config (void) static
Definition at line 221 of file cel_sqlite3_custom.c.
References ast_free, AST_LIST_REMOVE_HEAD, db, values::list, NULL, and value.
Referenced by load_config(), load_module(), and unload_module().
 {
    struct values *value;
    if (db) {
       sqlite3_close(db);
       db = NULL;
    }
    if (columns) {
       ast_free(columns);
       columns = NULL;
    }
    while ((value = AST_LIST_REMOVE_HEAD(&sql_values, list))) {
       ast_free(value);
    }
 }
load_column_config()
static int load_column_config (const char * tmp) static
Definition at line 82 of file cel_sqlite3_custom.c.
References ast_free, ast_log, ast_str_append(), ast_str_buffer(), ast_str_create, ast_str_strlen(), ast_strdup, ast_strip(), ast_strlen_zero, LOG_ERROR, LOG_WARNING, NULL, strsep(), and table.
Referenced by load_config().
 {
    char *col = NULL;
    char *cols = NULL, *save = NULL;
    char *escaped = NULL;
    struct ast_str *column_string = NULL;
    if (ast_strlen_zero(tmp)) {
       ast_log(LOG_WARNING, "Column names not specified. Module not loaded.\n");
       return -1;
    }
    if (!(column_string = ast_str_create(1024))) {
       ast_log(LOG_ERROR, "Out of memory creating temporary buffer for column list for table '%s.'\n", table);
       return -1;
    }
    if (!(save = cols = ast_strdup(tmp))) {
       ast_log(LOG_ERROR, "Out of memory creating temporary buffer for column list for table '%s.'\n", table);
       ast_free(column_string);
       return -1;
    }
    while ((col = strsep(&cols, ","))) {
       col = ast_strip(col);
       escaped = sqlite3_mprintf("%q", col);
       if (!escaped) {
          ast_log(LOG_ERROR, "Out of memory creating entry for column '%s' in table '%s.'\n", col, table);
          ast_free(column_string);
          ast_free(save);
          return -1;
       }
       ast_str_append(&column_string, 0, "%s%s", ast_str_strlen(column_string) ? "," : "", escaped);
       sqlite3_free(escaped);
    }
    if (!(columns = ast_strdup(ast_str_buffer(column_string)))) {
       ast_log(LOG_ERROR, "Out of memory copying columns string for table '%s.'\n", table);
       ast_free(column_string);
       ast_free(save);
       return -1;
    }
    ast_free(column_string);
    ast_free(save);
    return 0;
 }
load_config()
static int load_config (int reload) static
Definition at line 158 of file cel_sqlite3_custom.c.
References ast_config_destroy(), ast_config_load, ast_copy_string(), ast_log, ast_parse_arg(), ast_strlen_zero, ast_variable_browse(), ast_variable_retrieve(), ast_verb, busy_timeout, config_file, CONFIG_FLAG_FILEUNCHANGED, CONFIG_STATUS_FILEINVALID, CONFIG_STATUS_FILEMISSING, CONFIG_STATUS_FILEUNCHANGED, free_config(), load_column_config(), load_values_config(), LOG_WARNING, NULL, PARSE_DEFAULT, PARSE_INT32, table, and tmp().
Referenced by load_module(), and reload().
 {
    struct ast_config *cfg;
    struct ast_flags config_flags = { reload ? CONFIG_FLAG_FILEUNCHANGED : 0 };
    struct ast_variable *mappingvar;
    const char *tmp;
    if ((cfg = ast_config_load(config_file, config_flags)) == CONFIG_STATUS_FILEMISSING || cfg == CONFIG_STATUS_FILEINVALID) {
       ast_log(LOG_WARNING, "Failed to %sload configuration file. %s\n",
          reload ? "re" : "", reload ? "" : "Module not activated.");
       return -1;
    } else if (cfg == CONFIG_STATUS_FILEUNCHANGED) {
       return 0;
    }
    if (reload) {
       free_config();
    }
    if (!(mappingvar = ast_variable_browse(cfg, "master"))) {
       /* Nothing configured */
       ast_config_destroy(cfg);
       return -1;
    }
    /* Mapping must have a table name */
    if (!ast_strlen_zero(tmp = ast_variable_retrieve(cfg, "master", "table"))) {
       ast_copy_string(table, tmp, sizeof(table));
    } else {
       ast_log(LOG_WARNING, "Table name not specified.  Assuming cel.\n");
       strcpy(table, "cel");
    }
    /* sqlite3_busy_timeout in miliseconds */
    if ((tmp = ast_variable_retrieve(cfg, "master", "busy_timeout")) != NULL) {
       if (ast_parse_arg(tmp, PARSE_INT32|PARSE_DEFAULT, &busy_timeout, 1000) != 0) {
          ast_log(LOG_WARNING, "Invalid busy_timeout value '%s' specified. Using 1000 instead.\n", tmp);
       }
    } else {
       busy_timeout = 1000;
    }
    /* Columns */
    if (load_column_config(ast_variable_retrieve(cfg, "master", "columns"))) {
       ast_config_destroy(cfg);
       free_config();
       return -1;
    }
    /* Values */
    if (load_values_config(ast_variable_retrieve(cfg, "master", "values"))) {
       ast_config_destroy(cfg);
       free_config();
       return -1;
    }
    ast_verb(3, "Logging CEL records to table '%s' in 'master.db'\n", table);
    ast_config_destroy(cfg);
    return 0;
 }
load_module()
static int load_module (void) static
Definition at line 300 of file cel_sqlite3_custom.c.
References ast_cel_backend_register(), ast_config_AST_LOG_DIR, ast_log, AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, busy_timeout, db, error(), free_config(), load_config(), LOG_ERROR, LOG_WARNING, NULL, PATH_MAX, SQLITE_BACKEND_NAME, table, and write_cel().
Referenced by reload().
 {
    char *error;
    char filename[PATH_MAX];
    int res;
    char *sql;
    if (load_config(0)) {
       return AST_MODULE_LOAD_DECLINE;
    }
    /* is the database there? */
    snprintf(filename, sizeof(filename), "%s/master.db", ast_config_AST_LOG_DIR);
    res = sqlite3_open(filename, &db);
    if (res != SQLITE_OK) {
       ast_log(LOG_ERROR, "Could not open database %s.\n", filename);
       free_config();
       return AST_MODULE_LOAD_DECLINE;
    }
    sqlite3_busy_timeout(db, busy_timeout);
    /* is the table there? */
    sql = sqlite3_mprintf("SELECT COUNT(*) FROM %q;", table);
    res = sqlite3_exec(db, sql, NULL, NULL, NULL);
    sqlite3_free(sql);
    if (res != SQLITE_OK) {
       /* We don't use %q for the column list here since we already escaped when building it */
       sql = sqlite3_mprintf("CREATE TABLE %q (AcctId INTEGER PRIMARY KEY, %s)", table, columns);
       res = sqlite3_exec(db, sql, NULL, NULL, &error);
       sqlite3_free(sql);
       if (res != SQLITE_OK) {
          ast_log(LOG_WARNING, "Unable to create table '%s': %s.\n", table, error);
          sqlite3_free(error);
          free_config();
          return AST_MODULE_LOAD_DECLINE;
       }
    }
    if (ast_cel_backend_register(SQLITE_BACKEND_NAME, write_cel)) {
       ast_log(LOG_ERROR, "Unable to register custom SQLite3 CEL handling\n");
       free_config();
       return AST_MODULE_LOAD_DECLINE;
    }
    return AST_MODULE_LOAD_SUCCESS;
 }
load_values_config()
static int load_values_config (const char * tmp) static
Definition at line 126 of file cel_sqlite3_custom.c.
References ast_calloc, ast_copy_string(), ast_free, AST_LIST_INSERT_TAIL, ast_log, ast_strdup, ast_strip_quoted(), ast_strlen_zero, values::expression, values::list, LOG_ERROR, LOG_WARNING, NULL, strsep(), and value.
Referenced by load_config().
 {
    char *val = NULL;
    char *vals = NULL, *save = NULL;
    struct values *value = NULL;
    if (ast_strlen_zero(tmp)) {
       ast_log(LOG_WARNING, "Values not specified. Module not loaded.\n");
       return -1;
    }
    if (!(save = vals = ast_strdup(tmp))) {
       ast_log(LOG_ERROR, "Out of memory creating temporary buffer for value '%s'\n", tmp);
       return -1;
    }
    while ((val = strsep(&vals, ","))) {
       /* Strip the single quotes off if they are there */
       val = ast_strip_quoted(val, "'", "'");
       value = ast_calloc(sizeof(char), sizeof(*value) + strlen(val) + 1);
       if (!value) {
          ast_log(LOG_ERROR, "Out of memory creating entry for value '%s'\n", val);
          ast_free(save);
          return -1;
       }
       value->expression = (char *) value + sizeof(*value);
       ast_copy_string(value->expression, val, strlen(val) + 1);
       AST_LIST_INSERT_TAIL(&sql_values, value, list);
    }
    ast_free(save);
    return 0;
 }
reload()
static int reload (void) static
Definition at line 346 of file cel_sqlite3_custom.c.
References AST_MODFLAG_LOAD_ORDER, AST_MODPRI_CDR_DRIVER, AST_MODULE_INFO(), AST_MODULE_SUPPORT_EXTENDED, ast_mutex_lock, ast_mutex_unlock, ASTERISK_GPL_KEY, load_config(), load_module(), lock, and unload_module().
 {
    int res = 0;
    ast_mutex_lock(&lock);
    res = load_config(1);
    ast_mutex_unlock(&lock);
    return res;
 }
unload_module()
static int unload_module (void) static
Definition at line 291 of file cel_sqlite3_custom.c.
References ast_cel_backend_unregister(), free_config(), and SQLITE_BACKEND_NAME.
Referenced by reload().
 {
    ast_cel_backend_unregister(SQLITE_BACKEND_NAME);
    free_config();
    return 0;
 }
write_cel()
static void write_cel (struct ast_event * event) static
Definition at line 240 of file cel_sqlite3_custom.c.
References ast_cel_fabricate_channel_from_event(), ast_channel_unref, ast_debug, ast_free, AST_LIST_TRAVERSE, ast_log, ast_mutex_lock, ast_mutex_unlock, ast_str_append(), ast_str_buffer(), ast_str_create, ast_str_strlen(), db, dummy(), error(), values::expression, values::list, lock, LOG_ERROR, NULL, pbx_substitute_variables_helper(), table, and value.
Referenced by load_module().
 {
    char *error = NULL;
    char *sql = NULL;
    if (db == NULL) {
       /* Should not have loaded, but be failsafe. */
       return;
    }
    ast_mutex_lock(&lock);
    { /* Make it obvious that only sql should be used outside of this block */
       char *escaped;
       char subst_buf[2048];
       struct values *value;
       struct ast_channel *dummy;
       struct ast_str *value_string = ast_str_create(1024);
       dummy = ast_cel_fabricate_channel_from_event(event);
       if (!dummy) {
          ast_log(LOG_ERROR, "Unable to fabricate channel from CEL event.\n");
          ast_free(value_string);
          ast_mutex_unlock(&lock);
          return;
       }
       AST_LIST_TRAVERSE(&sql_values, value, list) {
          pbx_substitute_variables_helper(dummy, value->expression, subst_buf, sizeof(subst_buf) - 1);
          escaped = sqlite3_mprintf("%q", subst_buf);
          ast_str_append(&value_string, 0, "%s'%s'", ast_str_strlen(value_string) ? "," : "", escaped);
          sqlite3_free(escaped);
       }
       sql = sqlite3_mprintf("INSERT INTO %q (%s) VALUES (%s)", table, columns, ast_str_buffer(value_string));
       ast_debug(1, "About to log: %s\n", sql);
       dummy = ast_channel_unref(dummy);
       ast_free(value_string);
    }
    if (sqlite3_exec(db, sql, NULL, NULL, &error) != SQLITE_OK) {
       ast_log(LOG_ERROR, "%s. SQL: %s.\n", error, sql);
       sqlite3_free(error);
    }
    if (sql) {
       sqlite3_free(sql);
    }
    ast_mutex_unlock(&lock);
    return;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "SQLite3 Custom CEL Module" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_EXTENDED, .load = load_module, .unload = unload_module, .reload = reload, .load_pri = AST_MODPRI_CDR_DRIVER, .requires = "cel", } static
Definition at line 364 of file cel_sqlite3_custom.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 364 of file cel_sqlite3_custom.c.
busy_timeout
int busy_timeout static
Definition at line 71 of file cel_sqlite3_custom.c.
Referenced by load_config(), and load_module().
columns
char* columns static
Bug:
Handling of this var is crash prone on reloads
Definition at line 70 of file cel_sqlite3_custom.c.
config_file
const char config_file[] = "cel_sqlite3_custom.conf" static
Definition at line 62 of file cel_sqlite3_custom.c.
Referenced by load_config().
db
sqlite3* db = NULL static
Definition at line 64 of file cel_sqlite3_custom.c.
Referenced by free_config(), load_module(), and write_cel().
lock
ast_mutex_t lock = { PTHREAD_RECURSIVE_MUTEX_INITIALIZER_NP , NULL, {1, 0} } static
Definition at line 60 of file cel_sqlite3_custom.c.
Referenced by reload(), and write_cel().
sql_values
struct sql_values sql_values = { .first = NULL, .last = NULL, .lock = { PTHREAD_RECURSIVE_MUTEX_INITIALIZER_NP , NULL, {1, 0} } , } static
table
char table[80] static
Definition at line 66 of file cel_sqlite3_custom.c.
Referenced by load_column_config(), load_config(), load_module(), and write_cel().