Asterisk - The Open Source Telephony Project: resource_endpoints.h File Reference
resource_endpoints.h File Reference
Generated file - declares stubs to be implemented in res/ari/resource_endpoints.c.
#include "asterisk/ari.h"
Data Structures
struct ast_ari_endpoints_get_args
struct ast_ari_endpoints_list_args
struct ast_ari_endpoints_list_by_tech_args
struct ast_ari_endpoints_send_message_args
struct ast_ari_endpoints_send_message_to_endpoint_args
Functions
void ast_ari_endpoints_get (struct ast_variable *headers, struct ast_ari_endpoints_get_args *args, struct ast_ari_response *response)
Details for an endpoint.
void ast_ari_endpoints_list (struct ast_variable *headers, struct ast_ari_endpoints_list_args *args, struct ast_ari_response *response)
List all endpoints.
void ast_ari_endpoints_list_by_tech (struct ast_variable *headers, struct ast_ari_endpoints_list_by_tech_args *args, struct ast_ari_response *response)
List available endoints for a given endpoint technology.
void ast_ari_endpoints_send_message (struct ast_variable *headers, struct ast_ari_endpoints_send_message_args *args, struct ast_ari_response *response)
Send a message to some technology URI or endpoint.
int ast_ari_endpoints_send_message_parse_body (struct ast_json *body, struct ast_ari_endpoints_send_message_args *args)
Body parsing function for /endpoints/sendMessage.
void ast_ari_endpoints_send_message_to_endpoint (struct ast_variable *headers, struct ast_ari_endpoints_send_message_to_endpoint_args *args, struct ast_ari_response *response)
Send a message to some endpoint in a technology.
int ast_ari_endpoints_send_message_to_endpoint_parse_body (struct ast_json *body, struct ast_ari_endpoints_send_message_to_endpoint_args *args)
Body parsing function for /endpoints/{tech}/{resource}/sendMessage.
Detailed Description
Generated file - declares stubs to be implemented in res/ari/resource_endpoints.c.
Endpoint resources
Author
David M. Lee, II dlee@.nosp@m.digi.nosp@m.um.co.nosp@m.m
Definition in file resource_endpoints.h.
Function Documentation
ast_ari_endpoints_get()
void ast_ari_endpoints_get (struct ast_variable * headers, struct ast_ari_endpoints_get_args * args, struct ast_ari_response * response)
Details for an endpoint.
Parameters
headers HTTP headers
args Swagger parameters
[out] response HTTP response
Definition at line 153 of file resource_endpoints.c.
References ao2_cleanup, ast_ari_response_alloc_failed(), ast_ari_response_error(), ast_ari_response_ok(), ast_endpoint_latest_snapshot(), ast_endpoint_snapshot_to_json(), NULL, RAII_VAR, ast_ari_endpoints_get_args::resource, stasis_app_get_sanitizer(), and ast_ari_endpoints_get_args::tech.
Referenced by ast_ari_endpoints_get_cb().
 {
    struct ast_json *json;
    RAII_VAR(struct ast_endpoint_snapshot *, snapshot, NULL, ao2_cleanup);
    snapshot = ast_endpoint_latest_snapshot(args->tech, args->resource);
    if (!snapshot) {
       ast_ari_response_error(response, 404, "Not Found",
          "Endpoint not found");
       return;
    }
    json = ast_endpoint_snapshot_to_json(snapshot, stasis_app_get_sanitizer());
    if (!json) {
       ast_ari_response_alloc_failed(response);
       return;
    }
    ast_ari_response_ok(response, json);
 }
ast_ari_endpoints_list()
void ast_ari_endpoints_list (struct ast_variable * headers, struct ast_ari_endpoints_list_args * args, struct ast_ari_response * response)
List all endpoints.
Parameters
headers HTTP headers
args Swagger parameters
[out] response HTTP response
Definition at line 37 of file resource_endpoints.c.
References ao2_cleanup, ao2_iterator_destroy(), ao2_iterator_init(), ao2_iterator_next, ao2_ref, ast_ari_response_alloc_failed(), ast_ari_response_error(), ast_ari_response_ok(), ast_endpoint_cache(), ast_endpoint_snapshot_to_json(), ast_endpoint_snapshot_type(), ast_json_array_append(), ast_json_array_create(), ast_json_ref(), ast_json_unref(), cache, NULL, RAII_VAR, stasis_app_get_sanitizer(), stasis_cache_dump(), and stasis_message_data().
Referenced by ast_ari_endpoints_list_cb().
 {
    RAII_VAR(struct stasis_cache *, cache, NULL, ao2_cleanup);
    RAII_VAR(struct ao2_container *, snapshots, NULL, ao2_cleanup);
    RAII_VAR(struct ast_json *, json, NULL, ast_json_unref);
    struct ao2_iterator i;
    void *obj;
    cache = ast_endpoint_cache();
    if (!cache) {
       ast_ari_response_error(
          response, 500, "Internal Server Error",
          "Message bus not initialized");
       return;
    }
    ao2_ref(cache, +1);
    snapshots = stasis_cache_dump(cache, ast_endpoint_snapshot_type());
    if (!snapshots) {
       ast_ari_response_alloc_failed(response);
       return;
    }
    json = ast_json_array_create();
    if (!json) {
       ast_ari_response_alloc_failed(response);
       return;
    }
    i = ao2_iterator_init(snapshots, 0);
    while ((obj = ao2_iterator_next(&i))) {
       RAII_VAR(struct stasis_message *, msg, obj, ao2_cleanup);
       struct ast_endpoint_snapshot *snapshot = stasis_message_data(msg);
       struct ast_json *json_endpoint = ast_endpoint_snapshot_to_json(snapshot, stasis_app_get_sanitizer());
       if (!json_endpoint || ast_json_array_append(json, json_endpoint)) {
          ao2_iterator_destroy(&i);
          ast_ari_response_alloc_failed(response);
          return;
       }
    }
    ao2_iterator_destroy(&i);
    ast_ari_response_ok(response, ast_json_ref(json));
 }
ast_ari_endpoints_list_by_tech()
void ast_ari_endpoints_list_by_tech (struct ast_variable * headers, struct ast_ari_endpoints_list_by_tech_args * args, struct ast_ari_response * response)
List available endoints for a given endpoint technology.
Parameters
headers HTTP headers
args Swagger parameters
[out] response HTTP response
Definition at line 85 of file resource_endpoints.c.
References ao2_cleanup, ao2_iterator_destroy(), ao2_iterator_init(), ao2_iterator_next, ao2_ref, ast_ari_response_alloc_failed(), ast_ari_response_error(), ast_ari_response_ok(), ast_endpoint_cache(), ast_endpoint_find_by_id(), ast_endpoint_snapshot_to_json(), ast_endpoint_snapshot_type(), ast_json_array_append(), ast_json_array_create(), ast_json_ref(), ast_json_unref(), cache, NULL, RAII_VAR, stasis_app_get_sanitizer(), stasis_cache_dump(), stasis_message_data(), ast_endpoint_snapshot::tech, and ast_ari_endpoints_list_by_tech_args::tech.
Referenced by ast_ari_endpoints_list_by_tech_cb().
 {
    RAII_VAR(struct stasis_cache *, cache, NULL, ao2_cleanup);
    RAII_VAR(struct ao2_container *, snapshots, NULL, ao2_cleanup);
    RAII_VAR(struct ast_json *, json, NULL, ast_json_unref);
    struct ast_endpoint *tech_endpoint;
    struct ao2_iterator i;
    void *obj;
    tech_endpoint = ast_endpoint_find_by_id(args->tech);
    if (!tech_endpoint) {
       ast_ari_response_error(response, 404, "Not Found",
                    "No Endpoints found - invalid tech %s", args->tech);
       return;
    }
    ao2_ref(tech_endpoint, -1);
    cache = ast_endpoint_cache();
    if (!cache) {
       ast_ari_response_error(
          response, 500, "Internal Server Error",
          "Message bus not initialized");
       return;
    }
    ao2_ref(cache, +1);
    snapshots = stasis_cache_dump(cache, ast_endpoint_snapshot_type());
    if (!snapshots) {
       ast_ari_response_alloc_failed(response);
       return;
    }
    json = ast_json_array_create();
    if (!json) {
       ast_ari_response_alloc_failed(response);
       return;
    }
    i = ao2_iterator_init(snapshots, 0);
    while ((obj = ao2_iterator_next(&i))) {
       RAII_VAR(struct stasis_message *, msg, obj, ao2_cleanup);
       struct ast_endpoint_snapshot *snapshot = stasis_message_data(msg);
       struct ast_json *json_endpoint;
       int r;
       if (strcasecmp(args->tech, snapshot->tech) != 0) {
          continue;
       }
       json_endpoint = ast_endpoint_snapshot_to_json(snapshot, stasis_app_get_sanitizer());
       if (!json_endpoint) {
          continue;
       }
       r = ast_json_array_append(
          json, json_endpoint);
       if (r != 0) {
          ao2_iterator_destroy(&i);
          ast_ari_response_alloc_failed(response);
          return;
       }
    }
    ao2_iterator_destroy(&i);
    ast_ari_response_ok(response, ast_json_ref(json));
 }
ast_ari_endpoints_send_message()
void ast_ari_endpoints_send_message (struct ast_variable * headers, struct ast_ari_endpoints_send_message_args * args, struct ast_ari_response * response)
Send a message to some technology URI or endpoint.
Parameters
headers HTTP headers
args Swagger parameters
[out] response HTTP response
Definition at line 255 of file resource_endpoints.c.
References ast_ari_endpoints_send_message_parse_body(), ast_json_object_get(), ast_variables_destroy(), ast_ari_endpoints_send_message_args::body, ast_ari_endpoints_send_message_args::from, json_to_ast_variables(), NULL, send_message(), ast_ari_endpoints_send_message_args::to, and ast_ari_endpoints_send_message_args::variables.
Referenced by ast_ari_endpoints_send_message_cb().
 {
    struct ast_variable *variables = NULL;
    if (args->variables) {
       struct ast_json *json_variables;
       ast_ari_endpoints_send_message_parse_body(args->variables, args);
       json_variables = ast_json_object_get(args->variables, "variables");
       if (json_variables
          && json_to_ast_variables(response, json_variables, &variables)) {
          return;
       }
    }
    send_message(args->to, args->from, args->body, variables, response);
    ast_variables_destroy(variables);
 }
ast_ari_endpoints_send_message_parse_body()
int ast_ari_endpoints_send_message_parse_body (struct ast_json * body, struct ast_ari_endpoints_send_message_args * args)
Body parsing function for /endpoints/sendMessage.
Parameters
body The JSON body from which to parse parameters.
[out] args The args structure to parse into.
Return values
zero on success
non-zero on failure
Definition at line 103 of file res_ari_endpoints.c.
References ast_json_object_get(), ast_json_string_get(), ast_ari_endpoints_send_message_args::body, ast_ari_endpoints_send_message_args::from, and ast_ari_endpoints_send_message_args::to.
Referenced by ast_ari_endpoints_send_message().
 {
    struct ast_json *field;
    /* Parse query parameters out of it */
    field = ast_json_object_get(body, "to");
    if (field) {
       args->to = ast_json_string_get(field);
    }
    field = ast_json_object_get(body, "from");
    if (field) {
       args->from = ast_json_string_get(field);
    }
    field = ast_json_object_get(body, "body");
    if (field) {
       args->body = ast_json_string_get(field);
    }
    return 0;
 }
ast_ari_endpoints_send_message_to_endpoint()
void ast_ari_endpoints_send_message_to_endpoint (struct ast_variable * headers, struct ast_ari_endpoints_send_message_to_endpoint_args * args, struct ast_ari_response * response)
Send a message to some endpoint in a technology.
Parameters
headers HTTP headers
args Swagger parameters
[out] response HTTP response
Definition at line 276 of file resource_endpoints.c.
References ao2_ref, ast_ari_endpoints_send_message_to_endpoint_parse_body(), ast_ari_response_error(), ast_endpoint_latest_snapshot(), ast_json_object_get(), ast_str_to_lower(), ast_strdupa, ast_variables_destroy(), ast_ari_endpoints_send_message_to_endpoint_args::body, ast_ari_endpoints_send_message_to_endpoint_args::from, json_to_ast_variables(), NULL, ast_ari_endpoints_send_message_to_endpoint_args::resource, send_message(), ast_endpoint_snapshot::tech, ast_ari_endpoints_send_message_to_endpoint_args::tech, and ast_ari_endpoints_send_message_to_endpoint_args::variables.
Referenced by ast_ari_endpoints_send_message_to_endpoint_cb().
 {
    struct ast_variable *variables = NULL;
    struct ast_endpoint_snapshot *snapshot;
    char msg_to[128];
    char *tech = ast_strdupa(args->tech);
    /* Really, we just want to know if this thing exists */
    snapshot = ast_endpoint_latest_snapshot(args->tech, args->resource);
    if (!snapshot) {
       ast_ari_response_error(response, 404, "Not Found",
          "Endpoint not found");
       return;
    }
    ao2_ref(snapshot, -1);
    if (args->variables) {
       struct ast_json *json_variables;
       ast_ari_endpoints_send_message_to_endpoint_parse_body(args->variables, args);
       json_variables = ast_json_object_get(args->variables, "variables");
       if (json_variables
          && json_to_ast_variables(response, json_variables, &variables)) {
          return;
       }
    }
    snprintf(msg_to, sizeof(msg_to), "%s:%s", ast_str_to_lower(tech), args->resource);
    send_message(msg_to, args->from, args->body, variables, response);
    ast_variables_destroy(variables);
 }
ast_ari_endpoints_send_message_to_endpoint_parse_body()
int ast_ari_endpoints_send_message_to_endpoint_parse_body (struct ast_json * body, struct ast_ari_endpoints_send_message_to_endpoint_args * args)
Body parsing function for /endpoints/{tech}/{resource}/sendMessage.
Parameters
body The JSON body from which to parse parameters.
[out] args The args structure to parse into.
Return values
zero on success
non-zero on failure
Definition at line 310 of file res_ari_endpoints.c.
References ast_json_object_get(), ast_json_string_get(), ast_ari_endpoints_send_message_to_endpoint_args::body, and ast_ari_endpoints_send_message_to_endpoint_args::from.
Referenced by ast_ari_endpoints_send_message_to_endpoint().
 {
    struct ast_json *field;
    /* Parse query parameters out of it */
    field = ast_json_object_get(body, "from");
    if (field) {
       args->from = ast_json_string_get(field);
    }
    field = ast_json_object_get(body, "body");
    if (field) {
       args->body = ast_json_string_get(field);
    }
    return 0;
 }