Asterisk - The Open Source Telephony Project: conf_state_multi.c File Reference
conf_state_multi.c File Reference
Dial plan applications
Confbridge state handling for the MULTI state.
#include "include/confbridge.h"
#include "include/conf_state.h"
Functions
static void join_marked (struct confbridge_user *user)
static void join_unmarked (struct confbridge_user *user)
static void leave_unmarked (struct confbridge_user *user)
Variables
struct confbridge_state * CONF_STATE_MULTI = &STATE_MULTI
Conference state with multiple active users, but no marked users.
struct confbridge_state STATE_MULTI
Detailed Description
Confbridge state handling for the MULTI state.
Author
Terry Wilson <twilson@digium.com>
Definition in file conf_state_multi.c.
Function Documentation
join_marked()
static void join_marked (struct confbridge_user * user) static
Definition at line 58 of file conf_state_multi.c.
References conf_add_user_marked(), conf_change_state(), CONF_STATE_MULTI_MARKED, conf_update_user_mute(), and confbridge_user::conference.
 {
    conf_add_user_marked(user->conference, user);
    conf_update_user_mute(user);
    conf_change_state(user, CONF_STATE_MULTI_MARKED);
 }
join_unmarked()
static void join_unmarked (struct confbridge_user * user) static
Definition at line 52 of file conf_state_multi.c.
References conf_add_user_active(), conf_update_user_mute(), and confbridge_user::conference.
 {
    conf_add_user_active(user->conference, user);
    conf_update_user_mute(user);
 }
leave_unmarked()
static void leave_unmarked (struct confbridge_user * user) static
Definition at line 66 of file conf_state_multi.c.
References confbridge_conference::activeusers, conf_change_state(), conf_remove_user_active(), CONF_STATE_SINGLE, and confbridge_user::conference.
 {
    conf_remove_user_active(user->conference, user);
    if (user->conference->activeusers == 1) {
       conf_change_state(user, CONF_STATE_SINGLE);
    }
 }
Variable Documentation
CONF_STATE_MULTI
struct confbridge_state* CONF_STATE_MULTI = &STATE_MULTI
Conference state with multiple active users, but no marked users.
Definition at line 50 of file conf_state_multi.c.
Referenced by join_unmarked(), and leave_marked().
STATE_MULTI
struct confbridge_state STATE_MULTI
Definition at line 42 of file conf_state_multi.c.