Asterisk - The Open Source Telephony Project: stasis_endpoints.h File Reference
stasis_endpoints.h File Reference
Endpoint abstractions.
#include "asterisk/endpoints.h"
#include "asterisk/stasis.h"
#include "asterisk/stasis_cache_pattern.h"
#include "asterisk/stringfields.h"
Data Structures
struct ast_endpoint_blob
Blob of data associated with an endpoint.
struct ast_endpoint_snapshot
A snapshot of an endpoint's state.
Functions
struct stasis_message * ast_endpoint_blob_create (struct ast_endpoint *endpoint, struct stasis_message_type *type, struct ast_json *blob)
Creates a ast_endpoint_blob message.
void ast_endpoint_blob_publish (struct ast_endpoint *endpoint, struct stasis_message_type *type, struct ast_json *blob)
Creates and publishes a ast_endpoint_blob message.
struct stasis_cache * ast_endpoint_cache (void)
Backend cache for ast_endpoint_topic_all_cached().
struct stasis_cp_all * ast_endpoint_cache_all (void)
struct stasis_message_type * ast_endpoint_contact_state_type (void)
Message type for endpoint contact state changes.
struct ast_endpoint_snapshot * ast_endpoint_latest_snapshot (const char *tech, const char *resource)
Retrieve the most recent snapshot for the endpoint with the given name.
struct ast_endpoint_snapshot * ast_endpoint_snapshot_create (struct ast_endpoint *endpoint)
Create a snapshot of an endpoint.
struct ast_json * ast_endpoint_snapshot_to_json (const struct ast_endpoint_snapshot *snapshot, const struct stasis_message_sanitizer *sanitize)
Build a JSON object from a ast_endpoint_snapshot.
struct stasis_message_type * ast_endpoint_snapshot_type (void)
Message type for ast_endpoint_snapshot.
int ast_endpoint_stasis_init (void)
Initialization function for endpoint stasis support.
struct stasis_message_type * ast_endpoint_state_type (void)
Message type for endpoint state changes.
struct stasis_topic * ast_endpoint_topic (struct ast_endpoint *endpoint)
Returns the topic for a specific endpoint.
struct stasis_topic * ast_endpoint_topic_all (void)
Topic for all endpoint releated messages.
struct stasis_topic * ast_endpoint_topic_all_cached (void)
Cached topic for all endpoint related messages.
struct stasis_topic * ast_endpoint_topic_cached (struct ast_endpoint *endpoint)
Returns the topic for a specific endpoint.
Detailed Description
Endpoint abstractions.
Author
David M. Lee, II dlee@.nosp@m.digi.nosp@m.um.co.nosp@m.m
Since
12
Definition in file stasis_endpoints.h.
Function Documentation
ast_endpoint_snapshot_to_json()
struct ast_json* ast_endpoint_snapshot_to_json (const struct ast_endpoint_snapshot * snapshot, const struct stasis_message_sanitizer * sanitize)
Build a JSON object from a ast_endpoint_snapshot.
Parameters
snapshot Endpoint snapshot.
sanitize The message sanitizer to use on the snapshot
Returns
JSON object representing endpoint snapshot.
NULL on error
Definition at line 398 of file stasis_endpoints.c.
References ast_assert, ast_endpoint_state_to_string(), ast_json_array_append(), ast_json_integer_create(), ast_json_object_get(), ast_json_object_set(), ast_json_pack(), ast_json_string_create(), ast_json_unref(), stasis_message_sanitizer::channel_id, ast_endpoint_snapshot::channel_ids, ast_endpoint_snapshot::max_channels, NULL, ast_endpoint_snapshot::num_channels, ast_endpoint_snapshot::resource, ast_endpoint_snapshot::state, and ast_endpoint_snapshot::tech.
Referenced by ast_ari_endpoints_get(), ast_ari_endpoints_list(), ast_ari_endpoints_list_by_tech(), contactstatus_to_json(), message_received_handler(), multi_user_event_to_json(), peerstatus_to_json(), and simple_endpoint_event().
 {
    struct ast_json *json;
    struct ast_json *channel_array;
    int i;
    json = ast_json_pack("{s: s, s: s, s: s, s: []}",
       "technology", snapshot->tech,
       "resource", snapshot->resource,
       "state", ast_endpoint_state_to_string(snapshot->state),
       "channel_ids");
    if (json == NULL) {
       return NULL;
    }
    if (snapshot->max_channels != -1) {
       int res = ast_json_object_set(json, "max_channels",
          ast_json_integer_create(snapshot->max_channels));
       if (res != 0) {
          ast_json_unref(json);
          return NULL;
       }
    }
    channel_array = ast_json_object_get(json, "channel_ids");
    ast_assert(channel_array != NULL);
    for (i = 0; i < snapshot->num_channels; ++i) {
       int res;
       if (sanitize && sanitize->channel_id
          && sanitize->channel_id(snapshot->channel_ids[i])) {
          continue;
       }
       res = ast_json_array_append(channel_array,
          ast_json_string_create(snapshot->channel_ids[i]));
       if (res != 0) {
          ast_json_unref(json);
          return NULL;
       }
    }
    return json;
 }
ast_endpoint_stasis_init()
int ast_endpoint_stasis_init (void)
Initialization function for endpoint stasis support.
Returns
0 on success.
non-zero on error.
Since
12
Definition at line 458 of file stasis_endpoints.c.
References ast_endpoint_contact_state_type(), ast_endpoint_snapshot_type(), ast_endpoint_state_type(), ast_register_cleanup(), endpoint_snapshot_get_id(), endpoints_stasis_cleanup(), stasis_cp_all_create(), and STASIS_MESSAGE_TYPE_INIT.
Referenced by asterisk_daemon().
 {
    int res = 0;
    ast_register_cleanup(endpoints_stasis_cleanup);
    endpoint_cache_all = stasis_cp_all_create("endpoint:all",
       endpoint_snapshot_get_id);
    if (!endpoint_cache_all) {
       return -1;
    }
    res |= STASIS_MESSAGE_TYPE_INIT(ast_endpoint_snapshot_type);
    res |= STASIS_MESSAGE_TYPE_INIT(ast_endpoint_state_type);
    res |= STASIS_MESSAGE_TYPE_INIT(ast_endpoint_contact_state_type);
    return res;
 }