Asterisk - The Open Source Telephony Project: app_readexten.c File Reference
app_readexten.c File Reference
Dial plan applications
Trivial application to read an extension into a variable.
#include "asterisk.h"
#include "asterisk/file.h"
#include "asterisk/pbx.h"
#include "asterisk/app.h"
#include "asterisk/module.h"
#include "asterisk/indications.h"
#include "asterisk/channel.h"
Enumerations
enum readexten_option_flags { OPT_SKIP = (1 << 0), OPT_INDICATION = (1 << 1), OPT_NOANSWER = (1 << 2), OPT_POUND_TO_END = (1 << 3) }
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int load_module (void)
static int readexten_exec (struct ast_channel *chan, const char *data)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Read and evaluate extension validity" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, }
static char * app = "ReadExten"
static const struct ast_module_info * ast_module_info = &__mod_info
static const struct ast_app_option readexten_app_options [128] = { [ 's' ] = { .flag = OPT_SKIP }, [ 'i' ] = { .flag = OPT_INDICATION }, [ 'n' ] = { .flag = OPT_NOANSWER }, [ 'p' ] = { .flag = OPT_POUND_TO_END }, }
Detailed Description
Trivial application to read an extension into a variable.
Author
David Chappell David.nosp@m..Cha.nosp@m.ppell.nosp@m.@tri.nosp@m.ncoll.nosp@m..edu
Definition in file app_readexten.c.
Enumeration Type Documentation
readexten_option_flags
enum readexten_option_flags
Enumerator
OPT_SKIP
OPT_INDICATION
OPT_NOANSWER
OPT_POUND_TO_END
Definition at line 103 of file app_readexten.c.
{
    OPT_SKIP = (1 << 0),
    OPT_INDICATION = (1 << 1),
    OPT_NOANSWER = (1 << 2),
    OPT_POUND_TO_END = (1 << 3),
 };
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 288 of file app_readexten.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 288 of file app_readexten.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 288 of file app_readexten.c.
load_module()
static int load_module (void) static
Definition at line 282 of file app_readexten.c.
References ast_register_application_xml, and readexten_exec().
 {
    int res = ast_register_application_xml(app, readexten_exec);
    return res;
 }
readexten_exec()
static int readexten_exec (struct ast_channel * chan, const char * data) static
Definition at line 119 of file app_readexten.c.
References ast_answer(), AST_APP_ARG, ast_app_parse_options(), ast_channel_caller(), ast_channel_context(), ast_channel_language(), ast_channel_name(), ast_channel_pbx(), ast_channel_zone(), ast_check_hangup(), ast_debug, AST_DECLARE_APP_ARGS, ast_exists_extension(), ast_fileexists(), ast_get_indication_tone(), ast_log, ast_matchmore_extension(), ast_playtones_start(), ast_playtones_stop(), AST_STANDARD_APP_ARGS, AST_STATE_UP, ast_stopstream(), ast_strdupa, ast_streamfile(), ast_strlen_zero, ast_test_flag, ast_tone_zone_sound_unref(), ast_waitfordigit(), context, ast_tone_zone_sound::data, ast_pbx::dtimeoutms, exten, LOG_WARNING, NULL, OPT_INDICATION, OPT_NOANSWER, OPT_POUND_TO_END, OPT_SKIP, options, pbx_builtin_setvar_helper(), readexten_app_options, ast_pbx::rtimeoutms, S_COR, status, and timeout.
Referenced by load_module().
 {
    int res = 0;
    char exten[256] = "";
    int maxdigits = sizeof(exten) - 1;
    int timeout = 0, digit_timeout = 0, x = 0;
    char *argcopy = NULL, *status = "";
    struct ast_tone_zone_sound *ts = NULL;
    struct ast_flags flags = {0};
     AST_DECLARE_APP_ARGS(arglist,
       AST_APP_ARG(variable);
       AST_APP_ARG(filename);
       AST_APP_ARG(context);
       AST_APP_ARG(options);
       AST_APP_ARG(timeout);
    );
    if (ast_strlen_zero(data)) {
       ast_log(LOG_WARNING, "ReadExten requires at least one argument\n");
       pbx_builtin_setvar_helper(chan, "READEXTENSTATUS", "ERROR");
       return 0;
    }
    argcopy = ast_strdupa(data);
    AST_STANDARD_APP_ARGS(arglist, argcopy);
    if (ast_strlen_zero(arglist.variable)) {
       ast_log(LOG_WARNING, "Usage: ReadExten(variable[,filename[,context[,options[,timeout]]]])\n");
       pbx_builtin_setvar_helper(chan, "READEXTENSTATUS", "ERROR");
       return 0;
    }
    if (ast_strlen_zero(arglist.filename)) {
       arglist.filename = NULL;
    }
    if (ast_strlen_zero(arglist.context)) {
       arglist.context = ast_strdupa(ast_channel_context(chan));
    }
    if (!ast_strlen_zero(arglist.options)) {
       ast_app_parse_options(readexten_app_options, &flags, NULL, arglist.options);
    }
    if (!ast_strlen_zero(arglist.timeout)) {
       timeout = atoi(arglist.timeout);
       if (timeout > 0)
          timeout *= 1000;
    }
    if (timeout <= 0)
       timeout = ast_channel_pbx(chan) ? ast_channel_pbx(chan)->rtimeoutms : 10000;
    digit_timeout = ast_channel_pbx(chan) ? ast_channel_pbx(chan)->dtimeoutms : 5000;
    if (ast_test_flag(&flags, OPT_INDICATION) && !ast_strlen_zero(arglist.filename)) {
       ts = ast_get_indication_tone(ast_channel_zone(chan), arglist.filename);
    }
    do {
       if (ast_channel_state(chan) != AST_STATE_UP) {
          if (ast_test_flag(&flags, OPT_SKIP)) {
             /* At the user's option, skip if the line is not up */
             pbx_builtin_setvar_helper(chan, arglist.variable, "");
             status = "SKIP";
             break;
          } else if (!ast_test_flag(&flags, OPT_NOANSWER)) {
             /* Otherwise answer unless we're supposed to read while on-hook */
             res = ast_answer(chan);
          }
       }
       if (res < 0) {
          status = "HANGUP";
          break;
       }
       ast_playtones_stop(chan);
       ast_stopstream(chan);
       if (ts && ts->data[0]) {
          res = ast_playtones_start(chan, 0, ts->data, 0);
       } else if (arglist.filename) {
          if (ast_test_flag(&flags, OPT_INDICATION) && ast_fileexists(arglist.filename, NULL, ast_channel_language(chan)) <= 0) {
             /*
              * We were asked to play an indication that did not exist in the config.
              * If no such file exists, play it as a tonelist.  With any luck they won't
              * have a file named "350+440.ulaw"
              * (but honestly, who would do something so silly?)
              */
             res = ast_playtones_start(chan, 0, arglist.filename, 0);
          } else {
             res = ast_streamfile(chan, arglist.filename, ast_channel_language(chan));
          }
       }
       for (x = 0; x < maxdigits; x++) {
          ast_debug(3, "extension so far: '%s', timeout: %d\n", exten, timeout);
          res = ast_waitfordigit(chan, timeout);
          ast_playtones_stop(chan);
          ast_stopstream(chan);
          timeout = digit_timeout;
          if (res < 1) {    /* timeout expired or hangup */
             if (ast_check_hangup(chan)) {
                status = "HANGUP";
             } else if (x == 0) {
                pbx_builtin_setvar_helper(chan, arglist.variable, "t");
                status = "TIMEOUT";
             }
             break;
          }
          if (ast_test_flag(&flags, OPT_POUND_TO_END) && res == '#') {
             exten[x] = 0;
             break;
          }
          exten[x] = res;
          if (!ast_matchmore_extension(chan, arglist.context, exten, 1 /* priority */,
             S_COR(ast_channel_caller(chan)->id.number.valid, ast_channel_caller(chan)->id.number.str, NULL))) {
             if (!ast_exists_extension(chan, arglist.context, exten, 1,
                S_COR(ast_channel_caller(chan)->id.number.valid, ast_channel_caller(chan)->id.number.str, NULL))
                && res == '#') {
                exten[x] = '\0';
             }
             break;
          }
       }
       if (!ast_strlen_zero(status))
          break;
       if (ast_exists_extension(chan, arglist.context, exten, 1,
          S_COR(ast_channel_caller(chan)->id.number.valid, ast_channel_caller(chan)->id.number.str, NULL))) {
          ast_debug(3, "User entered valid extension '%s'\n", exten);
          pbx_builtin_setvar_helper(chan, arglist.variable, exten);
          status = "OK";
       } else {
          ast_debug(3, "User dialed invalid extension '%s' in context '%s' on %s\n", exten, arglist.context, ast_channel_name(chan));
          pbx_builtin_setvar_helper(chan, arglist.variable, "i");
          pbx_builtin_setvar_helper(chan, "INVALID_EXTEN", exten);
          status = "INVALID";
       }
    } while (0);
    if (ts) {
       ts = ast_tone_zone_sound_unref(ts);
    }
    pbx_builtin_setvar_helper(chan, "READEXTENSTATUS", status);
    return status[0] == 'H' ? -1 : 0;
 }
unload_module()
static int unload_module (void) static
Definition at line 276 of file app_readexten.c.
References ast_unregister_application().
 {
    int res = ast_unregister_application(app);
    return res;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Read and evaluate extension validity" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, } static
Definition at line 288 of file app_readexten.c.
app
char* app = "ReadExten" static
Definition at line 117 of file app_readexten.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 288 of file app_readexten.c.
readexten_app_options
const struct ast_app_option readexten_app_options[128] = { [ 's' ] = { .flag = OPT_SKIP }, [ 'i' ] = { .flag = OPT_INDICATION }, [ 'n' ] = { .flag = OPT_NOANSWER }, [ 'p' ] = { .flag = OPT_POUND_TO_END }, } static
Definition at line 115 of file app_readexten.c.
Referenced by readexten_exec().