Asterisk - The Open Source Telephony Project: multicast_rtp.h File Reference
multicast_rtp.h File Reference
Functions
struct ast_multicast_rtp_options * ast_multicast_rtp_create_options (const char *type, const char *options)
Create multicast RTP options.
void ast_multicast_rtp_free_options (struct ast_multicast_rtp_options *mcast_options)
Free multicast RTP options.
struct ast_format * ast_multicast_rtp_options_get_format (struct ast_multicast_rtp_options *mcast_options)
Get format specified in multicast options.
Function Documentation
ast_multicast_rtp_create_options()
struct ast_multicast_rtp_options* ast_multicast_rtp_create_options (const char * type, const char * options)
Create multicast RTP options.
These are passed to the multicast RTP engine on its creation.
Parameters
type The type of multicast RTP, either "basic" or "linksys"
options Miscellaneous options
Return values
NULL Failure
non-NULL success
Definition at line 140 of file res_rtp_multicast.c.
References ast_app_parse_options(), ast_calloc, ast_log, ast_multicast_rtp_free_options(), ast_strlen_zero, ast_multicast_rtp_options::buf, LOG_WARNING, multicast_rtp_options, NULL, ast_multicast_rtp_options::opt_args, ast_multicast_rtp_options::options, ast_multicast_rtp_options::opts, S_OR, and ast_multicast_rtp_options::type.
Referenced by multicast_rtp_request().
 {
    struct ast_multicast_rtp_options *mcast_options;
    char *pos;
    mcast_options = ast_calloc(1, sizeof(*mcast_options)
          + strlen(type)
          + strlen(S_OR(options, "")) + 2);
    if (!mcast_options) {
       return NULL;
    }
    pos = mcast_options->buf;
    /* Safe */
    strcpy(pos, type);
    mcast_options->type = pos;
    pos += strlen(type) + 1;
    if (!ast_strlen_zero(options)) {
       strcpy(pos, options); /* Safe */
    }
    mcast_options->options = pos;
    if (ast_app_parse_options(multicast_rtp_options, &mcast_options->opts,
       mcast_options->opt_args, mcast_options->options)) {
       ast_log(LOG_WARNING, "Error parsing multicast RTP options\n");
       ast_multicast_rtp_free_options(mcast_options);
       return NULL;
    }
    return mcast_options;
 }
ast_multicast_rtp_free_options()
void ast_multicast_rtp_free_options (struct ast_multicast_rtp_options * mcast_options)
Free multicast RTP options.
This function is NULL-tolerant
Parameters
mcast_options Options to free
Definition at line 175 of file res_rtp_multicast.c.
References ast_free.
Referenced by ast_multicast_rtp_create_options(), and multicast_rtp_request().
 {
    ast_free(mcast_options);
 }
ast_multicast_rtp_options_get_format()
struct ast_format* ast_multicast_rtp_options_get_format (struct ast_multicast_rtp_options * mcast_options)
Get format specified in multicast options.
Multicast options allow for a format to be selected. This function accesses the selected format and creates an ast_format structure for it.
Parameters
mcast_options The options where a codec was specified
Return values
NULL No format specified in the options non-NULL The format to use for communication
Definition at line 180 of file res_rtp_multicast.c.
References ast_format_cache_get, ast_strlen_zero, ast_test_flag, multicast_rtp_activate(), multicast_rtp_destroy(), multicast_rtp_new(), multicast_rtp_read(), multicast_rtp_write(), NULL, OPT_ARG_CODEC, ast_multicast_rtp_options::opt_args, OPT_CODEC, and ast_multicast_rtp_options::opts.
Referenced by multicast_rtp_request().
 {
    if (ast_test_flag(&mcast_options->opts, OPT_CODEC)
       && !ast_strlen_zero(mcast_options->opt_args[OPT_ARG_CODEC])) {
       return ast_format_cache_get(mcast_options->opt_args[OPT_ARG_CODEC]);
    }
    return NULL;
 }