Asterisk - The Open Source Telephony Project: curl.h File Reference
curl.h File Reference
Functions
struct curl_cb_data * curl_cb_data_create (void)
Allocate memory for a curl_cb_data struct.
void curl_cb_data_free (struct curl_cb_data *data)
Free a curl_cb_data struct.
char * curl_cb_data_get_cache_control (const struct curl_cb_data *data)
Get the cache_control field from a curl_cb_data struct.
char * curl_cb_data_get_expires (const struct curl_cb_data *data)
Get the expires field from a curl_cb_data struct.
char * curl_public_key (const char *public_cert_url, const char *path, struct curl_cb_data *data)
CURL the public key from the provided URL to the specified path.
Function Documentation
curl_cb_data_create()
struct curl_cb_data* curl_cb_data_create (void)
Allocate memory for a curl_cb_data struct.
Note
This will need to be freed by the consumer using curl_cb_data_free
Return values
NULL on failure
curl_cb_struct on success
Definition at line 42 of file curl.c.
References ast_calloc.
Referenced by run_curl().
 {
    struct curl_cb_data *data;
    data = ast_calloc(1, sizeof(*data));
    return data;
 }
curl_cb_data_free()
void curl_cb_data_free (struct curl_cb_data * data)
Free a curl_cb_data struct.
Parameters
data The curl_cb_data struct to free
Definition at line 51 of file curl.c.
References ast_free, curl_cb_data::cache_control, and curl_cb_data::expires.
Referenced by run_curl().
 {
    if (!data) {
       return;
    }
    ast_free(data->cache_control);
    ast_free(data->expires);
    ast_free(data);
 }
curl_cb_data_get_cache_control()
char* curl_cb_data_get_cache_control (const struct curl_cb_data * data)
Get the cache_control field from a curl_cb_data struct.
Parameters
data The curl_cb_data
Return values
cache_control on success
NULL otherwise
Definition at line 63 of file curl.c.
References curl_cb_data::cache_control, and NULL.
Referenced by set_public_key_expiration().
 {
    if (!data) {
       return NULL;
    }
    return data->cache_control;
 }
curl_cb_data_get_expires()
char* curl_cb_data_get_expires (const struct curl_cb_data * data)
Get the expires field from a curl_cb_data struct.
Parameters
data The curl_cb_data
Return values
expires on success
NULL otherwise
Definition at line 72 of file curl.c.
References curl_cb_data::expires, and NULL.
Referenced by set_public_key_expiration().
 {
    if (!data) {
       return NULL;
    }
    return data->expires;
 }
curl_public_key()
char* curl_public_key (const char * public_cert_url, const char * path, struct curl_cb_data * data)
CURL the public key from the provided URL to the specified path.
Note
The returned string will need to be freed by the caller
Parameters
public_cert_url The public cert URL
path The path to download the file to
data The curl_cb_data
Return values
NULL on failure
full path filename on success
Definition at line 185 of file curl.c.
References ast_asprintf, ast_free, ast_log, create_temp_file(), errno, get_curl_instance(), LOG_ERROR, NULL, RAII_VAR, and stir_shaken_get_serial_number_x509().
Referenced by run_curl().
 {
    FILE *public_key_file;
    RAII_VAR(char *, tmp_filename, NULL, ast_free);
    char *filename;
    char *serial;
    int fd;
    long http_code;
    CURL *curl;
    char curl_errbuf[CURL_ERROR_SIZE + 1];
    curl_errbuf[CURL_ERROR_SIZE] = '\0';
    /* For now, it's fine to pass in path as is - it shouldn't end with a '/'. However,
     * if we decide to change how certificates are stored in the future (configurable paths),
     * then we will need to check to see if path ends with '/', copy everything up to the '/',
     * and use this new variable for create_temp_file as well as for ast_asprintf below.
     */
    fd = create_temp_file(path, &tmp_filename);
    if (fd == -1) {
       ast_log(LOG_ERROR, "Failed to get temporary file descriptor for CURL\n");
       return NULL;
    }
    public_key_file = fdopen(fd, "wb");
    if (!public_key_file) {
       ast_log(LOG_ERROR, "Failed to open file '%s' to write public key from '%s': %s (%d)\n",
          tmp_filename, public_cert_url, strerror(errno), errno);
       close(fd);
       remove(tmp_filename);
       return NULL;
    }
    curl = get_curl_instance(data);
    if (!curl) {
       ast_log(LOG_ERROR, "Failed to set up CURL isntance for '%s'\n", public_cert_url);
       fclose(public_key_file);
       remove(tmp_filename);
       return NULL;
    }
    curl_easy_setopt(curl, CURLOPT_URL, public_cert_url);
    curl_easy_setopt(curl, CURLOPT_WRITEDATA, public_key_file);
    curl_easy_setopt(curl, CURLOPT_ERRORBUFFER, curl_errbuf);
    if (curl_easy_perform(curl)) {
       ast_log(LOG_ERROR, "%s\n", curl_errbuf);
       curl_easy_cleanup(curl);
       fclose(public_key_file);
       remove(tmp_filename);
       return NULL;
    }
    curl_easy_getinfo(curl, CURLINFO_RESPONSE_CODE, &http_code);
    curl_easy_cleanup(curl);
    fclose(public_key_file);
    if (http_code / 100 != 2) {
       ast_log(LOG_ERROR, "Failed to retrieve URL '%s': code %ld\n", public_cert_url, http_code);
       remove(tmp_filename);
       return NULL;
    }
    serial = stir_shaken_get_serial_number_x509(tmp_filename);
    if (!serial) {
       ast_log(LOG_ERROR, "Failed to get serial from cert %s\n", tmp_filename);
       remove(tmp_filename);
       return NULL;
    }
    if (ast_asprintf(&filename, "%s/%s.pem", path, serial) < 0) {
       ast_log(LOG_ERROR, "Failed to allocate memory for new filename for temporary "
          "file %s after CURL\n", tmp_filename);
       ast_free(serial);
       remove(tmp_filename);
       return NULL;
    }
    ast_free(serial);
    if (rename(tmp_filename, filename)) {
       ast_log(LOG_ERROR, "Failed to rename temporary file %s to %s after CURL\n", tmp_filename, filename);
       ast_free(filename);
       remove(tmp_filename);
       return NULL;
    }
    return filename;
 }