Asterisk - The Open Source Telephony Project: mod_format.h File Reference
mod_format.h File Reference
Header for providers of file and format handling routines. Clients of these routines should include "asterisk/file.h" instead.
#include "asterisk/file.h"
#include "asterisk/frame.h"
Data Structures
struct ast_filestream
This structure is allocated by file.c in one chunk, together with buf_size and desc_size bytes of memory to be used for private purposes (e.g. buffers etc.)
struct ast_format_def
Each supported file format is described by the following structure.
Macros
#define ast_format_def_register(f) __ast_format_def_register(f, AST_MODULE_SELF)
Functions
int __ast_format_def_register (const struct ast_format_def *f, struct ast_module *mod)
Register a new file format capability. Adds a format to Asterisk's format abilities.
int ast_format_def_unregister (const char *name)
Unregisters a file format.
Detailed Description
Header for providers of file and format handling routines. Clients of these routines should include "asterisk/file.h" instead.
Definition in file mod_format.h.
Macro Definition Documentation
ast_format_def_register
#define ast_format_def_register (f) __ast_format_def_register(f, AST_MODULE_SELF)
Definition at line 136 of file mod_format.h.
Referenced by load_module().
Function Documentation
__ast_format_def_register()
int __ast_format_def_register (const struct ast_format_def * f, struct ast_module * mod)
Register a new file format capability. Adds a format to Asterisk's format abilities.
Return values
0 on success
-1 on failure
Definition at line 124 of file file.c.
References a, ast_calloc, ast_format_register_type(), ast_log, AST_RWLIST_INSERT_HEAD, AST_RWLIST_TRAVERSE, AST_RWLIST_UNLOCK, AST_RWLIST_WRLOCK, ast_verb, b, ast_format_def::buf_size, ast_format_def::exts, ast_format_def::list, LOG_WARNING, ast_format_def::module, ast_format_def::name, publish_format_update(), and tmp().
 {
    struct ast_format_def *tmp;
    AST_RWLIST_WRLOCK(&formats);
    AST_RWLIST_TRAVERSE(&formats, tmp, list) {
       if (!strcasecmp(f->name, tmp->name)) {
          AST_RWLIST_UNLOCK(&formats);
          ast_log(LOG_WARNING, "Tried to register '%s' format, already registered\n", f->name);
          return -1;
       }
    }
    if (!(tmp = ast_calloc(1, sizeof(*tmp)))) {
       AST_RWLIST_UNLOCK(&formats);
       return -1;
    }
    *tmp = *f;
    tmp->module = mod;
    if (tmp->buf_size) {
       /*
        * Align buf_size properly, rounding up to the machine-specific
        * alignment for pointers.
        */
       struct _test_align { void *a, *b; } p;
       int align = (char *)&p.b - (char *)&p.a;
       tmp->buf_size = ((f->buf_size + align - 1) / align) * align;
    }
    memset(&tmp->list, 0, sizeof(tmp->list));
    AST_RWLIST_INSERT_HEAD(&formats, tmp, list);
    AST_RWLIST_UNLOCK(&formats);
    ast_verb(2, "Registered file format %s, extension(s) %s\n", f->name, f->exts);
    publish_format_update(f, ast_format_register_type());
    return 0;
 }
ast_format_def_unregister()
int ast_format_def_unregister (const char * name)
Unregisters a file format.
Parameters
name the name of the format you wish to unregister Unregisters a format based on the name of the format.
Return values
0 on success
-1 on failure to unregister
Definition at line 162 of file file.c.
References ast_format_unregister_type(), ast_free, ast_log, AST_RWLIST_REMOVE_CURRENT, AST_RWLIST_TRAVERSE_SAFE_BEGIN, AST_RWLIST_TRAVERSE_SAFE_END, AST_RWLIST_UNLOCK, AST_RWLIST_WRLOCK, ast_verb, ast_format_def::list, LOG_WARNING, ast_format_def::name, publish_format_update(), and tmp().
Referenced by unload_module().
 {
    struct ast_format_def *tmp;
    int res = -1;
    AST_RWLIST_WRLOCK(&formats);
    AST_RWLIST_TRAVERSE_SAFE_BEGIN(&formats, tmp, list) {
       if (!strcasecmp(name, tmp->name)) {
          AST_RWLIST_REMOVE_CURRENT(list);
          publish_format_update(tmp, ast_format_unregister_type());
          ast_free(tmp);
          res = 0;
       }
    }
    AST_RWLIST_TRAVERSE_SAFE_END;
    AST_RWLIST_UNLOCK(&formats);
    if (!res)
       ast_verb(2, "Unregistered format %s\n", name);
    else
       ast_log(LOG_WARNING, "Tried to unregister format %s, already unregistered\n", name);
    return res;
 }