Asterisk - The Open Source Telephony Project: app_saycounted.c File Reference
app_saycounted.c File Reference
Dial plan applications
Applications to decline words according to current language.
#include "asterisk.h"
#include "asterisk/logger.h"
#include "asterisk/module.h"
#include "asterisk/app.h"
#include "asterisk/say.h"
Functions
AST_MODULE_INFO_STANDARD_EXTENDED (ASTERISK_GPL_KEY, "Decline words according to channel language")
static int load_module (void)
static int saycountedadj_exec (struct ast_channel *chan, const char *data)
static int saycountednoun_exec (struct ast_channel *chan, const char *data)
static int unload_module (void)
Detailed Description
Applications to decline words according to current language.
Author
David Chappell David.nosp@m..Cha.nosp@m.ppell.nosp@m.@tri.nosp@m.ncoll.nosp@m..edu
Definition in file app_saycounted.c.
Function Documentation
AST_MODULE_INFO_STANDARD_EXTENDED()
AST_MODULE_INFO_STANDARD_EXTENDED (ASTERISK_GPL_KEY , "Decline words according to channel language")
Referenced by unload_module().
load_module()
static int load_module (void) static
Definition at line 190 of file app_saycounted.c.
References ast_register_application_xml, saycountedadj_exec(), and saycountednoun_exec().
 {
    int res;
    res = ast_register_application_xml("SayCountedNoun", saycountednoun_exec);
    res |= ast_register_application_xml("SayCountedAdj", saycountedadj_exec);
    return res;
 }
saycountedadj_exec()
static int saycountedadj_exec (struct ast_channel * chan, const char * data) static
Definition at line 152 of file app_saycounted.c.
References args, AST_APP_ARG, AST_DECLARE_APP_ARGS, ast_log, ast_say_counted_adjective(), AST_STANDARD_APP_ARGS, ast_strdupa, ast_strlen_zero, LOG_WARNING, and parse().
Referenced by load_module().
 {
    char *parse;
    int number;
    AST_DECLARE_APP_ARGS(args,
       AST_APP_ARG(number);
       AST_APP_ARG(adjective);
       AST_APP_ARG(gender);
    );
    if (ast_strlen_zero(data)) {
       ast_log(LOG_WARNING, "SayCountedAdj requires two or three arguments (<number>,<adjective>[,<gender>])\n");
       return -1;
    }
    parse = ast_strdupa(data);
    AST_STANDARD_APP_ARGS(args, parse);
    if (args.argc < 2) {
       ast_log(LOG_WARNING, "SayCountedAdj requires at least two arguments\n");
       return -1;
    }
    if (sscanf(args.number, "%d", &number) != 1) {
       ast_log(LOG_WARNING, "First argument must be a number between 0 and 2,147,483,647.\n");
       return -1;
    }
    if (!ast_strlen_zero(args.gender)) {
       if (strchr("cCfFmMnN", args.gender[0])) {
          ast_log(LOG_WARNING, "SayCountedAdj gender option must be one of 'f', 'm', 'c', or 'n'.\n");
          return -1;
       }
    }
    return ast_say_counted_adjective(chan, number, args.adjective, args.gender);
 }
saycountednoun_exec()
static int saycountednoun_exec (struct ast_channel * chan, const char * data) static
Definition at line 122 of file app_saycounted.c.
References args, AST_APP_ARG, AST_DECLARE_APP_ARGS, ast_log, ast_say_counted_noun(), AST_STANDARD_APP_ARGS, ast_strdupa, ast_strlen_zero, LOG_WARNING, and parse().
Referenced by load_module().
 {
    char *parse;
    int number;
    AST_DECLARE_APP_ARGS(args,
       AST_APP_ARG(number);
       AST_APP_ARG(noun);
    );
    if (ast_strlen_zero(data)) {
       ast_log(LOG_WARNING, "SayCountedNoun requires two arguments (<number>,<noun>)\n");
       return -1;
    }
    parse = ast_strdupa(data);
    AST_STANDARD_APP_ARGS(args, parse);
    if (args.argc != 2) {
       ast_log(LOG_WARNING, "SayCountedNoun requires two arguments\n");
       return -1;
    }
    if (sscanf(args.number, "%d", &number) != 1) {
       ast_log(LOG_WARNING, "First argument must be a number between 0 and 2,147,483,647.\n");
       return -1;
    }
    return ast_say_counted_noun(chan, number, args.noun);
 }
unload_module()
static int unload_module (void) static
Definition at line 198 of file app_saycounted.c.
References AST_MODULE_INFO_STANDARD_EXTENDED(), ast_unregister_application(), and ASTERISK_GPL_KEY.
 {
    int res;
    res = ast_unregister_application("SayCountedNoun");
    res |= ast_unregister_application("SayCountedAdj");
    return res;
 }