Asterisk - The Open Source Telephony Project: res_ari_applications.c File Reference
res_ari_applications.c File Reference
Stasis application resources.
#include "asterisk.h"
#include "asterisk/app.h"
#include "asterisk/module.h"
#include "asterisk/stasis_app.h"
#include "ari/resource_applications.h"
#include "ari/ari_model_validators.h"
Macros
#define MAX_VALS 128
Functions
static void __reg_module (void)
static void __unreg_module (void)
static void ast_ari_applications_filter_cb (struct ast_tcptls_session_instance *ser, struct ast_variable *get_params, struct ast_variable *path_vars, struct ast_variable *headers, struct ast_json *body, struct ast_ari_response *response)
Parameter parsing callback for /applications/{applicationName}/eventFilter.
int ast_ari_applications_filter_parse_body (struct ast_json *body, struct ast_ari_applications_filter_args *args)
Body parsing function for /applications/{applicationName}/eventFilter.
static void ast_ari_applications_get_cb (struct ast_tcptls_session_instance *ser, struct ast_variable *get_params, struct ast_variable *path_vars, struct ast_variable *headers, struct ast_json *body, struct ast_ari_response *response)
Parameter parsing callback for /applications/{applicationName}.
static void ast_ari_applications_list_cb (struct ast_tcptls_session_instance *ser, struct ast_variable *get_params, struct ast_variable *path_vars, struct ast_variable *headers, struct ast_json *body, struct ast_ari_response *response)
Parameter parsing callback for /applications.
static void ast_ari_applications_subscribe_cb (struct ast_tcptls_session_instance *ser, struct ast_variable *get_params, struct ast_variable *path_vars, struct ast_variable *headers, struct ast_json *body, struct ast_ari_response *response)
Parameter parsing callback for /applications/{applicationName}/subscription.
int ast_ari_applications_subscribe_parse_body (struct ast_json *body, struct ast_ari_applications_subscribe_args *args)
Body parsing function for /applications/{applicationName}/subscription.
static void ast_ari_applications_unsubscribe_cb (struct ast_tcptls_session_instance *ser, struct ast_variable *get_params, struct ast_variable *path_vars, struct ast_variable *headers, struct ast_json *body, struct ast_ari_response *response)
Parameter parsing callback for /applications/{applicationName}/subscription.
int ast_ari_applications_unsubscribe_parse_body (struct ast_json *body, struct ast_ari_applications_unsubscribe_args *args)
Body parsing function for /applications/{applicationName}/subscription.
struct ast_module * AST_MODULE_SELF_SYM (void)
static int load_module (void)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_DEFAULT , .description = "RESTful API module - Stasis application resources" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .requires = "res_ari,res_ari_model,res_stasis", }
static struct stasis_rest_handlers applications
REST handler for /api-docs/applications.json.
static struct stasis_rest_handlers applications_applicationName
REST handler for /api-docs/applications.json.
static struct stasis_rest_handlers applications_applicationName_eventFilter
REST handler for /api-docs/applications.json.
static struct stasis_rest_handlers applications_applicationName_subscription
REST handler for /api-docs/applications.json.
static const struct ast_module_info * ast_module_info = &__mod_info
Detailed Description
Stasis application resources.
Author
David M. Lee, II dlee@.nosp@m.digi.nosp@m.um.co.nosp@m.m
Definition in file res_ari_applications.c.
Macro Definition Documentation
MAX_VALS
#define MAX_VALS 128
Definition at line 51 of file res_ari_applications.c.
Referenced by ast_ari_applications_subscribe_cb(), and ast_ari_applications_unsubscribe_cb().
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 595 of file res_ari_applications.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 595 of file res_ari_applications.c.
ast_ari_applications_filter_cb()
static void ast_ari_applications_filter_cb (struct ast_tcptls_session_instance * ser, struct ast_variable * get_params, struct ast_variable * path_vars, struct ast_variable * headers, struct ast_json * body, struct ast_ari_response * response) static
Parameter parsing callback for /applications/{applicationName}/eventFilter.
Parameters
get_params GET parameters in the HTTP request.
path_vars Path variables extracted from the request.
headers HTTP headers.
[out] response Response to the HTTP request.
Definition at line 477 of file res_ari_applications.c.
References ast_ari_applications_filter_args::application_name, ast_ari_applications_filter(), ast_ari_response_error(), ast_ari_validate_application(), ast_log, ast_ari_applications_filter_args::filter, LOG_ERROR, ast_ari_response::message, ast_variable::name, ast_variable::next, NULL, ast_ari_response::response_code, and ast_variable::value.
 {
    struct ast_ari_applications_filter_args args = {};
    struct ast_variable *i;
 #if defined(AST_DEVMODE)
    int is_valid;
    int code;
 #endif /* AST_DEVMODE */
    for (i = path_vars; i; i = i->next) {
       if (strcmp(i->name, "applicationName") == 0) {
          args.application_name = (i->value);
       } else
       {}
    }
    args.filter = body;
    ast_ari_applications_filter(headers, &args, response);
 #if defined(AST_DEVMODE)
    code = response->response_code;
    switch (code) {
    case 0: /* Implementation is still a stub, or the code wasn't set */
       is_valid = response->message == NULL;
       break;
    case 500: /* Internal Server Error */
    case 501: /* Not Implemented */
    case 400: /* Bad request. */
    case 404: /* Application does not exist. */
       is_valid = 1;
       break;
    default:
       if (200 <= code && code <= 299) {
          is_valid = ast_ari_validate_application(
             response->message);
       } else {
          ast_log(LOG_ERROR, "Invalid error response %d for /applications/{applicationName}/eventFilter\n", code);
          is_valid = 0;
       }
    }
    if (!is_valid) {
       ast_log(LOG_ERROR, "Response validation failed for /applications/{applicationName}/eventFilter\n");
       ast_ari_response_error(response, 500,
          "Internal Server Error", "Response validation failed");
    }
 #endif /* AST_DEVMODE */
 fin: __attribute__((unused))
    return;
 }
ast_ari_applications_filter_parse_body()
int ast_ari_applications_filter_parse_body (struct ast_json * body, struct ast_ari_applications_filter_args * args)
Body parsing function for /applications/{applicationName}/eventFilter.
Parameters
body The JSON body from which to parse parameters.
[out] args The args structure to parse into.
Return values
zero on success
non-zero on failure
Definition at line 462 of file res_ari_applications.c.
 {
    /* Parse query parameters out of it */
    return 0;
 }
ast_ari_applications_get_cb()
static void ast_ari_applications_get_cb (struct ast_tcptls_session_instance * ser, struct ast_variable * get_params, struct ast_variable * path_vars, struct ast_variable * headers, struct ast_json * body, struct ast_ari_response * response) static
Parameter parsing callback for /applications/{applicationName}.
Parameters
get_params GET parameters in the HTTP request.
path_vars Path variables extracted from the request.
headers HTTP headers.
[out] response Response to the HTTP request.
Definition at line 110 of file res_ari_applications.c.
References ast_ari_applications_get_args::application_name, ast_ari_applications_get(), ast_ari_response_error(), ast_ari_validate_application(), ast_log, LOG_ERROR, ast_ari_response::message, ast_variable::name, ast_variable::next, NULL, ast_ari_response::response_code, and ast_variable::value.
 {
    struct ast_ari_applications_get_args args = {};
    struct ast_variable *i;
 #if defined(AST_DEVMODE)
    int is_valid;
    int code;
 #endif /* AST_DEVMODE */
    for (i = path_vars; i; i = i->next) {
       if (strcmp(i->name, "applicationName") == 0) {
          args.application_name = (i->value);
       } else
       {}
    }
    ast_ari_applications_get(headers, &args, response);
 #if defined(AST_DEVMODE)
    code = response->response_code;
    switch (code) {
    case 0: /* Implementation is still a stub, or the code wasn't set */
       is_valid = response->message == NULL;
       break;
    case 500: /* Internal Server Error */
    case 501: /* Not Implemented */
    case 404: /* Application does not exist. */
       is_valid = 1;
       break;
    default:
       if (200 <= code && code <= 299) {
          is_valid = ast_ari_validate_application(
             response->message);
       } else {
          ast_log(LOG_ERROR, "Invalid error response %d for /applications/{applicationName}\n", code);
          is_valid = 0;
       }
    }
    if (!is_valid) {
       ast_log(LOG_ERROR, "Response validation failed for /applications/{applicationName}\n");
       ast_ari_response_error(response, 500,
          "Internal Server Error", "Response validation failed");
    }
 #endif /* AST_DEVMODE */
 fin: __attribute__((unused))
    return;
 }
ast_ari_applications_list_cb()
static void ast_ari_applications_list_cb (struct ast_tcptls_session_instance * ser, struct ast_variable * get_params, struct ast_variable * path_vars, struct ast_variable * headers, struct ast_json * body, struct ast_ari_response * response) static
Parameter parsing callback for /applications.
Parameters
get_params GET parameters in the HTTP request.
path_vars Path variables extracted from the request.
headers HTTP headers.
[out] response Response to the HTTP request.
Definition at line 60 of file res_ari_applications.c.
References ast_ari_applications_list(), ast_ari_response_error(), ast_ari_validate_application_fn(), ast_ari_validate_list(), ast_log, LOG_ERROR, ast_ari_response::message, NULL, and ast_ari_response::response_code.
 {
    struct ast_ari_applications_list_args args = {};
 #if defined(AST_DEVMODE)
    int is_valid;
    int code;
 #endif /* AST_DEVMODE */
    ast_ari_applications_list(headers, &args, response);
 #if defined(AST_DEVMODE)
    code = response->response_code;
    switch (code) {
    case 0: /* Implementation is still a stub, or the code wasn't set */
       is_valid = response->message == NULL;
       break;
    case 500: /* Internal Server Error */
    case 501: /* Not Implemented */
       is_valid = 1;
       break;
    default:
       if (200 <= code && code <= 299) {
          is_valid = ast_ari_validate_list(response->message,
             ast_ari_validate_application_fn());
       } else {
          ast_log(LOG_ERROR, "Invalid error response %d for /applications\n", code);
          is_valid = 0;
       }
    }
    if (!is_valid) {
       ast_log(LOG_ERROR, "Response validation failed for /applications\n");
       ast_ari_response_error(response, 500,
          "Internal Server Error", "Response validation failed");
    }
 #endif /* AST_DEVMODE */
 fin: __attribute__((unused))
    return;
 }
ast_ari_applications_subscribe_cb()
static void ast_ari_applications_subscribe_cb (struct ast_tcptls_session_instance * ser, struct ast_variable * get_params, struct ast_variable * path_vars, struct ast_variable * headers, struct ast_json * body, struct ast_ari_response * response) static
Parameter parsing callback for /applications/{applicationName}/subscription.
Parameters
get_params GET parameters in the HTTP request.
path_vars Path variables extracted from the request.
headers HTTP headers.
[out] response Response to the HTTP request.
Definition at line 206 of file res_ari_applications.c.
References ast_ari_applications_subscribe_args::application_name, ARRAY_LEN, ast_app_separate_args, ast_ari_applications_subscribe(), ast_ari_applications_subscribe_parse_body(), ast_ari_response_alloc_failed(), ast_ari_response_error(), ast_ari_validate_application(), ast_free, ast_log, ast_malloc, ast_strdup, ast_ari_applications_subscribe_args::event_source, ast_ari_applications_subscribe_args::event_source_count, ast_ari_applications_subscribe_args::event_source_parse, LOG_ERROR, MAX_VALS, ast_ari_response::message, ast_variable::name, ast_variable::next, NULL, ast_ari_response::response_code, and ast_variable::value.
 {
    struct ast_ari_applications_subscribe_args args = {};
    struct ast_variable *i;
 #if defined(AST_DEVMODE)
    int is_valid;
    int code;
 #endif /* AST_DEVMODE */
    for (i = get_params; i; i = i->next) {
       if (strcmp(i->name, "eventSource") == 0) {
          /* Parse comma separated list */
          char *vals[MAX_VALS];
          size_t j;
          args.event_source_parse = ast_strdup(i->value);
          if (!args.event_source_parse) {
             ast_ari_response_alloc_failed(response);
             goto fin;
          }
          if (strlen(args.event_source_parse) == 0) {
             /* ast_app_separate_args can't handle "" */
             args.event_source_count = 1;
             vals[0] = args.event_source_parse;
          } else {
             args.event_source_count = ast_app_separate_args(
                args.event_source_parse, ',', vals,
                ARRAY_LEN(vals));
          }
          if (args.event_source_count == 0) {
             ast_ari_response_alloc_failed(response);
             goto fin;
          }
          if (args.event_source_count >= MAX_VALS) {
             ast_ari_response_error(response, 400,
                "Bad Request",
                "Too many values for event_source");
             goto fin;
          }
          args.event_source = ast_malloc(sizeof(*args.event_source) * args.event_source_count);
          if (!args.event_source) {
             ast_ari_response_alloc_failed(response);
             goto fin;
          }
          for (j = 0; j < args.event_source_count; ++j) {
             args.event_source[j] = (vals[j]);
          }
       } else
       {}
    }
    for (i = path_vars; i; i = i->next) {
       if (strcmp(i->name, "applicationName") == 0) {
          args.application_name = (i->value);
       } else
       {}
    }
    if (ast_ari_applications_subscribe_parse_body(body, &args)) {
       ast_ari_response_alloc_failed(response);
       goto fin;
    }
    ast_ari_applications_subscribe(headers, &args, response);
 #if defined(AST_DEVMODE)
    code = response->response_code;
    switch (code) {
    case 0: /* Implementation is still a stub, or the code wasn't set */
       is_valid = response->message == NULL;
       break;
    case 500: /* Internal Server Error */
    case 501: /* Not Implemented */
    case 400: /* Missing parameter. */
    case 404: /* Application does not exist. */
    case 422: /* Event source does not exist. */
       is_valid = 1;
       break;
    default:
       if (200 <= code && code <= 299) {
          is_valid = ast_ari_validate_application(
             response->message);
       } else {
          ast_log(LOG_ERROR, "Invalid error response %d for /applications/{applicationName}/subscription\n", code);
          is_valid = 0;
       }
    }
    if (!is_valid) {
       ast_log(LOG_ERROR, "Response validation failed for /applications/{applicationName}/subscription\n");
       ast_ari_response_error(response, 500,
          "Internal Server Error", "Response validation failed");
    }
 #endif /* AST_DEVMODE */
 fin: __attribute__((unused))
    ast_free(args.event_source_parse);
    ast_free(args.event_source);
    return;
 }
ast_ari_applications_subscribe_parse_body()
int ast_ari_applications_subscribe_parse_body (struct ast_json * body, struct ast_ari_applications_subscribe_args * args)
Body parsing function for /applications/{applicationName}/subscription.
Parameters
body The JSON body from which to parse parameters.
[out] args The args structure to parse into.
Return values
zero on success
non-zero on failure
Definition at line 161 of file res_ari_applications.c.
References ast_free, AST_JSON_ARRAY, ast_json_array_get(), ast_json_array_size(), ast_json_object_get(), ast_json_string_get(), ast_json_typeof(), ast_malloc, ast_ari_applications_subscribe_args::event_source, and ast_ari_applications_subscribe_args::event_source_count.
Referenced by ast_ari_applications_subscribe_cb().
 {
    struct ast_json *field;
    /* Parse query parameters out of it */
    field = ast_json_object_get(body, "eventSource");
    if (field) {
       /* If they were silly enough to both pass in a query param and a
        * JSON body, free up the query value.
        */
       ast_free(args->event_source);
       if (ast_json_typeof(field) == AST_JSON_ARRAY) {
          /* Multiple param passed as array */
          size_t i;
          args->event_source_count = ast_json_array_size(field);
          args->event_source = ast_malloc(sizeof(*args->event_source) * args->event_source_count);
          if (!args->event_source) {
             return -1;
          }
          for (i = 0; i < args->event_source_count; ++i) {
             args->event_source[i] = ast_json_string_get(ast_json_array_get(field, i));
          }
       } else {
          /* Multiple param passed as single value */
          args->event_source_count = 1;
          args->event_source = ast_malloc(sizeof(*args->event_source) * args->event_source_count);
          if (!args->event_source) {
             return -1;
          }
          args->event_source[0] = ast_json_string_get(field);
       }
    }
    return 0;
 }
ast_ari_applications_unsubscribe_cb()
static void ast_ari_applications_unsubscribe_cb (struct ast_tcptls_session_instance * ser, struct ast_variable * get_params, struct ast_variable * path_vars, struct ast_variable * headers, struct ast_json * body, struct ast_ari_response * response) static
Parameter parsing callback for /applications/{applicationName}/subscription.
Parameters
get_params GET parameters in the HTTP request.
path_vars Path variables extracted from the request.
headers HTTP headers.
[out] response Response to the HTTP request.
Definition at line 356 of file res_ari_applications.c.
References ast_ari_applications_unsubscribe_args::application_name, ARRAY_LEN, ast_app_separate_args, ast_ari_applications_unsubscribe(), ast_ari_applications_unsubscribe_parse_body(), ast_ari_response_alloc_failed(), ast_ari_response_error(), ast_ari_validate_application(), ast_free, ast_log, ast_malloc, ast_strdup, ast_ari_applications_unsubscribe_args::event_source, ast_ari_applications_unsubscribe_args::event_source_count, ast_ari_applications_unsubscribe_args::event_source_parse, LOG_ERROR, MAX_VALS, ast_ari_response::message, ast_variable::name, ast_variable::next, NULL, ast_ari_response::response_code, and ast_variable::value.
 {
    struct ast_ari_applications_unsubscribe_args args = {};
    struct ast_variable *i;
 #if defined(AST_DEVMODE)
    int is_valid;
    int code;
 #endif /* AST_DEVMODE */
    for (i = get_params; i; i = i->next) {
       if (strcmp(i->name, "eventSource") == 0) {
          /* Parse comma separated list */
          char *vals[MAX_VALS];
          size_t j;
          args.event_source_parse = ast_strdup(i->value);
          if (!args.event_source_parse) {
             ast_ari_response_alloc_failed(response);
             goto fin;
          }
          if (strlen(args.event_source_parse) == 0) {
             /* ast_app_separate_args can't handle "" */
             args.event_source_count = 1;
             vals[0] = args.event_source_parse;
          } else {
             args.event_source_count = ast_app_separate_args(
                args.event_source_parse, ',', vals,
                ARRAY_LEN(vals));
          }
          if (args.event_source_count == 0) {
             ast_ari_response_alloc_failed(response);
             goto fin;
          }
          if (args.event_source_count >= MAX_VALS) {
             ast_ari_response_error(response, 400,
                "Bad Request",
                "Too many values for event_source");
             goto fin;
          }
          args.event_source = ast_malloc(sizeof(*args.event_source) * args.event_source_count);
          if (!args.event_source) {
             ast_ari_response_alloc_failed(response);
             goto fin;
          }
          for (j = 0; j < args.event_source_count; ++j) {
             args.event_source[j] = (vals[j]);
          }
       } else
       {}
    }
    for (i = path_vars; i; i = i->next) {
       if (strcmp(i->name, "applicationName") == 0) {
          args.application_name = (i->value);
       } else
       {}
    }
    if (ast_ari_applications_unsubscribe_parse_body(body, &args)) {
       ast_ari_response_alloc_failed(response);
       goto fin;
    }
    ast_ari_applications_unsubscribe(headers, &args, response);
 #if defined(AST_DEVMODE)
    code = response->response_code;
    switch (code) {
    case 0: /* Implementation is still a stub, or the code wasn't set */
       is_valid = response->message == NULL;
       break;
    case 500: /* Internal Server Error */
    case 501: /* Not Implemented */
    case 400: /* Missing parameter; event source scheme not recognized. */
    case 404: /* Application does not exist. */
    case 409: /* Application not subscribed to event source. */
    case 422: /* Event source does not exist. */
       is_valid = 1;
       break;
    default:
       if (200 <= code && code <= 299) {
          is_valid = ast_ari_validate_application(
             response->message);
       } else {
          ast_log(LOG_ERROR, "Invalid error response %d for /applications/{applicationName}/subscription\n", code);
          is_valid = 0;
       }
    }
    if (!is_valid) {
       ast_log(LOG_ERROR, "Response validation failed for /applications/{applicationName}/subscription\n");
       ast_ari_response_error(response, 500,
          "Internal Server Error", "Response validation failed");
    }
 #endif /* AST_DEVMODE */
 fin: __attribute__((unused))
    ast_free(args.event_source_parse);
    ast_free(args.event_source);
    return;
 }
ast_ari_applications_unsubscribe_parse_body()
int ast_ari_applications_unsubscribe_parse_body (struct ast_json * body, struct ast_ari_applications_unsubscribe_args * args)
Body parsing function for /applications/{applicationName}/subscription.
Parameters
body The JSON body from which to parse parameters.
[out] args The args structure to parse into.
Return values
zero on success
non-zero on failure
Definition at line 311 of file res_ari_applications.c.
References ast_free, AST_JSON_ARRAY, ast_json_array_get(), ast_json_array_size(), ast_json_object_get(), ast_json_string_get(), ast_json_typeof(), ast_malloc, ast_ari_applications_unsubscribe_args::event_source, and ast_ari_applications_unsubscribe_args::event_source_count.
Referenced by ast_ari_applications_unsubscribe_cb().
 {
    struct ast_json *field;
    /* Parse query parameters out of it */
    field = ast_json_object_get(body, "eventSource");
    if (field) {
       /* If they were silly enough to both pass in a query param and a
        * JSON body, free up the query value.
        */
       ast_free(args->event_source);
       if (ast_json_typeof(field) == AST_JSON_ARRAY) {
          /* Multiple param passed as array */
          size_t i;
          args->event_source_count = ast_json_array_size(field);
          args->event_source = ast_malloc(sizeof(*args->event_source) * args->event_source_count);
          if (!args->event_source) {
             return -1;
          }
          for (i = 0; i < args->event_source_count; ++i) {
             args->event_source[i] = ast_json_string_get(ast_json_array_get(field, i));
          }
       } else {
          /* Multiple param passed as single value */
          args->event_source_count = 1;
          args->event_source = ast_malloc(sizeof(*args->event_source) * args->event_source_count);
          if (!args->event_source) {
             return -1;
          }
          args->event_source[0] = ast_json_string_get(field);
       }
    }
    return 0;
 }
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 595 of file res_ari_applications.c.
load_module()
static int load_module (void) static
Definition at line 576 of file res_ari_applications.c.
References ast_ari_add_handler(), AST_MODFLAG_DEFAULT, AST_MODULE_INFO(), AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, AST_MODULE_SUPPORT_CORE, ASTERISK_GPL_KEY, and unload_module().
 {
    int res = 0;
    res |= ast_ari_add_handler(&applications);
    if (res) {
       unload_module();
       return AST_MODULE_LOAD_DECLINE;
    }
    return AST_MODULE_LOAD_SUCCESS;
 }
unload_module()
static int unload_module (void) static
Definition at line 570 of file res_ari_applications.c.
References ast_ari_remove_handler().
Referenced by load_module().
 {
    ast_ari_remove_handler(&applications);
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_DEFAULT , .description = "RESTful API module - Stasis application resources" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .requires = "res_ari,res_ari_model,res_stasis", } static
Definition at line 595 of file res_ari_applications.c.
applications
struct stasis_rest_handlers applications static
REST handler for /api-docs/applications.json.
Definition at line 561 of file res_ari_applications.c.
applications_applicationName
struct stasis_rest_handlers applications_applicationName static
REST handler for /api-docs/applications.json.
Definition at line 551 of file res_ari_applications.c.
applications_applicationName_eventFilter
struct stasis_rest_handlers applications_applicationName_eventFilter static
REST handler for /api-docs/applications.json.
Definition at line 542 of file res_ari_applications.c.
applications_applicationName_subscription
struct stasis_rest_handlers applications_applicationName_subscription static
REST handler for /api-docs/applications.json.
Definition at line 532 of file res_ari_applications.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 595 of file res_ari_applications.c.