Asterisk - The Open Source Telephony Project: astdb2sqlite3.c File Reference
astdb2sqlite3.c File Reference
Berkeley DB to SQLite3 converter.
#include "asterisk.h"
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <unistd.h>
#include <sqlite3.h>
#include <libgen.h>
#include "db1-ast/include/db.h"
Macros
#define DEFINE_SQL_STATEMENT(stmt, sql)
#define MAX_DB_FIELD 256
#define MIN(a, b)
Functions
static int ast_db_begin_transaction (void)
static int ast_db_commit_transaction (void)
static int ast_db_rollback_transaction (void)
static int convert_bdb_to_sqlite3 (const char *bdb_dbname)
static int db_create_astdb (void)
static int db_open (const char *dbname)
static int db_put_raw (const char *key, size_t keylen, const char *value, size_t valuelen)
DEFINE_SQL_STATEMENT (put_stmt, "INSERT OR REPLACE INTO astdb (key, value) VALUES (?, ?)")
static int init_statements (void)
static int init_stmt (sqlite3_stmt **stmt, const char *sql, size_t len)
int main (int argc, char *argv[])
static int sql_db_init (const char *dbname)
Variables
static sqlite3 * astdb
Detailed Description
Berkeley DB to SQLite3 converter.
Author
Terry Wilson twils.nosp@m.on@d.nosp@m.igium.nosp@m..com
Definition in file astdb2sqlite3.c.
Macro Definition Documentation
DEFINE_SQL_STATEMENT
#define DEFINE_SQL_STATEMENT (stmt, sql)
Value:
static sqlite3_stmt *stmt; \
   const char stmt##_sql[] = sql;
Definition at line 49 of file astdb2sqlite3.c.
MAX_DB_FIELD
#define MAX_DB_FIELD 256
Definition at line 41 of file astdb2sqlite3.c.
Referenced by convert_bdb_to_sqlite3().
MIN
#define MIN (a, b)
Value:
({ typeof (a) _a = (a); \
   typeof (b) _b = (b); \
   a < _b ? _a : _b; })
Definition at line 42 of file astdb2sqlite3.c.
Referenced by convert_bdb_to_sqlite3().
Function Documentation
ast_db_begin_transaction()
static int ast_db_begin_transaction (void) static
Definition at line 70 of file astdb2sqlite3.c.
Referenced by db_create_astdb().
 {
    return db_execute_transaction_sql("BEGIN TRANSACTION");
 }
ast_db_commit_transaction()
static int ast_db_commit_transaction (void) static
Definition at line 75 of file astdb2sqlite3.c.
Referenced by db_create_astdb().
 {
    return db_execute_transaction_sql("COMMIT");
 }
ast_db_rollback_transaction()
static int ast_db_rollback_transaction (void) static
Definition at line 80 of file astdb2sqlite3.c.
Referenced by db_create_astdb().
 {
    return db_execute_transaction_sql("ROLLBACK");
 }
convert_bdb_to_sqlite3()
static int convert_bdb_to_sqlite3 (const char * bdb_dbname) static
Definition at line 104 of file astdb2sqlite3.c.
References AST_FILE_MODE, bdb, DBT::data, DB_BTREE, db_put_raw(), dbopen(), last, MAX_DB_FIELD, MIN, NULL, R_FIRST, R_LAST, R_NEXT, DBT::size, and value.
Referenced by main().
 {
    DB *bdb;
    DBT key = { 0, }, value = { 0, }, last_key = { 0, };
    int res, last = 0;
    char last_key_s[MAX_DB_FIELD];
    if (!(bdb = dbopen(bdb_dbname, O_RDONLY, AST_FILE_MODE, DB_BTREE, NULL))) {
       fprintf(stderr, "Unable to open Asterisk database '%s'\n", bdb_dbname);
       return -1;
    }
    if (bdb->seq(bdb, &last_key, &value, R_LAST)) {
       /* Empty database */
       return 0;
    }
    memcpy(last_key_s, last_key.data, MIN(last_key.size - 1, sizeof(last_key_s)));
    last_key_s[last_key.size - 1] = '\0';
    for (res = bdb->seq(bdb, &key, &value, R_FIRST);
          !res; res = bdb->seq(bdb, &key, &value, R_NEXT)) {
       last = !strcmp(key.data, last_key_s);
       db_put_raw((const char *) key.data, key.size - 1, (const char *) value.data, value.size - 1);
       if (last) {
          break;
       }
    }
    bdb->close(bdb);
    return 0;
 }
db_create_astdb()
static int db_create_astdb (void) static
Definition at line 147 of file astdb2sqlite3.c.
References ast_db_begin_transaction(), ast_db_commit_transaction(), ast_db_rollback_transaction(), astdb, and init_stmt().
Referenced by sql_db_init().
 {
    if (init_stmt(&create_astdb_stmt, create_astdb_stmt_sql, sizeof(create_astdb_stmt_sql))) {
       return -1;
    }
    ast_db_begin_transaction();
    if (sqlite3_step(create_astdb_stmt) != SQLITE_DONE) {
       fprintf(stderr, "Couldn't create astdb table: %s\n", sqlite3_errmsg(astdb));
       ast_db_rollback_transaction();
       sqlite3_reset(create_astdb_stmt);
       return -1;
    }
    ast_db_commit_transaction();
    sqlite3_reset(create_astdb_stmt);
    return 0;
 }
db_open()
static int db_open (const char * dbname) static
Definition at line 174 of file astdb2sqlite3.c.
References astdb.
Referenced by sql_db_init().
 {
    if (sqlite3_open(dbname, &astdb) != SQLITE_OK) {
       fprintf(stderr, "Unable to open Asterisk database '%s': %s\n", dbname, sqlite3_errmsg(astdb));
       sqlite3_close(astdb);
       return -1;
    }
    return 0;
 }
db_put_raw()
static int db_put_raw (const char * key, size_t keylen, const char * value, size_t valuelen) static
Definition at line 85 of file astdb2sqlite3.c.
References astdb.
Referenced by convert_bdb_to_sqlite3().
 {
    int res = 0;
    if (sqlite3_bind_text(put_stmt, 1, key, keylen, SQLITE_STATIC) != SQLITE_OK) {
       fprintf(stderr, "Couldn't bind key to stmt: %s\n", sqlite3_errmsg(astdb));
       res = -1;
    } else if (sqlite3_bind_text(put_stmt, 2, value, valuelen, SQLITE_STATIC) != SQLITE_OK) {
       fprintf(stderr, "Couldn't bind value to stmt: %s\n", sqlite3_errmsg(astdb));
       res = -1;
    } else if (sqlite3_step(put_stmt) != SQLITE_DONE) {
       fprintf(stderr, "Couldn't execute statement: %s\n", sqlite3_errmsg(astdb));
       res = -1;
    }
    sqlite3_reset(put_stmt);
    return res;
 }
DEFINE_SQL_STATEMENT()
DEFINE_SQL_STATEMENT (put_stmt , "INSERT OR REPLACE INTO astdb (key, value) VALUES (?, ?)")
Definition at line 52 of file astdb2sqlite3.c.
References astdb, and NULL.
 {
    char *errmsg = NULL;
    int res =0;
    sqlite3_exec(astdb, sql, NULL, NULL, &errmsg);
    if (errmsg) {
       fprintf(stderr, "Error executing SQL: %s\n", errmsg);
       sqlite3_free(errmsg);
       res = -1;
    }
    return res;
 }
init_statements()
static int init_statements (void) static
Definition at line 167 of file astdb2sqlite3.c.
References init_stmt().
Referenced by sql_db_init().
 {
    /* Don't initialize create_astdb_statement here as the astdb table needs to exist
     * brefore these statements can be initialized */
    return init_stmt(&put_stmt, put_stmt_sql, sizeof(put_stmt_sql));
 }
init_stmt()
static int init_stmt (sqlite3_stmt ** stmt, const char * sql, size_t len) static
Definition at line 137 of file astdb2sqlite3.c.
References astdb, and NULL.
Referenced by db_create_astdb(), and init_statements().
 {
    if (sqlite3_prepare(astdb, sql, len, stmt, NULL) != SQLITE_OK) {
       fprintf(stderr, "Couldn't prepare statement '%s': %s\n", sql, sqlite3_errmsg(astdb));
       return -1;
    }
    return 0;
 }
main()
int main (int argc, char * argv[])
Definition at line 194 of file astdb2sqlite3.c.
References astdb, convert_bdb_to_sqlite3(), dbname, errno, and sql_db_init().
 {
    char *dbname;
    struct stat dont_care;
    if (argc != 2) {
       fprintf(stderr, "%s takes the path of astdb as its only argument\n", basename(argv[0]));
       exit(-1);
    }
    if (stat(argv[1], &dont_care)) {
       fprintf(stderr, "Unable to open %s: %s\n", argv[1], strerror(errno));
       exit(-1);
    }
    if (!(dbname = alloca(strlen(argv[1]) + sizeof(".sqlite3")))) {
       exit(-1);
    }
    strcpy(dbname, argv[1]);
    strcat(dbname, ".sqlite3");
    if (!stat(dbname, &dont_care)) {
       fprintf(stderr, "%s already exists!\n", dbname);
       exit(-1);
    }
    if (sql_db_init(dbname)) {
       exit(-1);
    }
    if (convert_bdb_to_sqlite3(argv[1])) {
       fprintf(stderr, "Database conversion failed!\n");
       exit(-1);
       sqlite3_close(astdb);
    }
    sqlite3_close(astdb);
    return 0;
 }
sql_db_init()
static int sql_db_init (const char * dbname) static
Definition at line 185 of file astdb2sqlite3.c.
References db_create_astdb(), db_open(), and init_statements().
Referenced by main().
 {
    if (db_open(dbname) || db_create_astdb() || init_statements()) {
       return -1;
    }
    return 0;
 }
Variable Documentation
astdb
sqlite3* astdb static
Definition at line 47 of file astdb2sqlite3.c.
Referenced by db_create_astdb(), db_open(), db_put_raw(), DEFINE_SQL_STATEMENT(), init_stmt(), and main().