Asterisk - The Open Source Telephony Project: gsm_destroy.c File Reference
gsm_destroy.c File Reference
#include "gsm.h"
#include "config.h"
#include "proto.h"
Functions
void free ()
void gsm_destroy P1 ((S), gsm S)
Function Documentation
free()
void free ()
Referenced by __ast_bt_destroy(), __ast_bt_free_symbols(), __ast_bt_get_symbols(), __ast_context_destroy(), __ast_free(), __bt_close(), __bt_open(), __bt_setcur(), __buf_free(), __hash_open(), __rec_put(), add_channel(), add_pri(), ael2_parse(), ael_yyfree(), append_sub(), ast_add_extension2(), ast_category_destroy(), ast_config_destroy(), ast_context_add_include2(), ast_context_add_switch2(), ast_expr(), ast_includes_destroy(), ast_remove_hint(), ast_std_free(), ast_str_expr(), ast_var_delete(), ast_variables_destroy(), ast_yyerror(), ast_yyfree(), bt_page(), check_pval_item(), collect_data(), collect_key(), config_text_file_load(), dbm_open(), del_chan(), delete_sub(), destroy_arglist(), destroy_exten(), destroy_extensions(), destroy_namelist(), destroy_pval_item(), fetch_bitmap(), finalize(), fix_gotos_in_extensions(), free_value(), g722_decode_release(), g722_encode_release(), gen_prios(), handle_cr(), handle_event_nt(), hash_close(), hash_realloc(), hdestroy(), linkprio(), localized_ast_include_rename(), main(), make_str(), misdn_lib_destroy(), misdn_lib_init(), mpool_close(), newbuf(), op_func(), op_tildetilde(), P1(), pbx_load_config(), readawaysamples(), setup_filestack(), stack_init(), tmp(), to_number(), while(), yydestruct(), yyerror(), and yyparse().
P1()
void gsm_destroy P1 ((S) , gsm S)
Definition at line 23 of file gsm_destroy.c.
References free().
 {
    free((char *)S);
 }