Asterisk - The Open Source Telephony Project: res_ari_bridges.c File Reference
res_ari_bridges.c File Reference
Bridge resources.
#include "asterisk.h"
#include "asterisk/app.h"
#include "asterisk/module.h"
#include "asterisk/stasis_app.h"
#include "ari/resource_bridges.h"
#include "ari/ari_model_validators.h"
Macros
#define MAX_VALS 128
Functions
static void __reg_module (void)
static void __unreg_module (void)
static void ast_ari_bridges_add_channel_cb (struct ast_tcptls_session_instance *ser, struct ast_variable *get_params, struct ast_variable *path_vars, struct ast_variable *headers, struct ast_json *body, struct ast_ari_response *response)
Parameter parsing callback for /bridges/{bridgeId}/addChannel.
int ast_ari_bridges_add_channel_parse_body (struct ast_json *body, struct ast_ari_bridges_add_channel_args *args)
Body parsing function for /bridges/{bridgeId}/addChannel.
static void ast_ari_bridges_clear_video_source_cb (struct ast_tcptls_session_instance *ser, struct ast_variable *get_params, struct ast_variable *path_vars, struct ast_variable *headers, struct ast_json *body, struct ast_ari_response *response)
Parameter parsing callback for /bridges/{bridgeId}/videoSource.
static void ast_ari_bridges_create_cb (struct ast_tcptls_session_instance *ser, struct ast_variable *get_params, struct ast_variable *path_vars, struct ast_variable *headers, struct ast_json *body, struct ast_ari_response *response)
Parameter parsing callback for /bridges.
int ast_ari_bridges_create_parse_body (struct ast_json *body, struct ast_ari_bridges_create_args *args)
Body parsing function for /bridges.
static void ast_ari_bridges_create_with_id_cb (struct ast_tcptls_session_instance *ser, struct ast_variable *get_params, struct ast_variable *path_vars, struct ast_variable *headers, struct ast_json *body, struct ast_ari_response *response)
Parameter parsing callback for /bridges/{bridgeId}.
int ast_ari_bridges_create_with_id_parse_body (struct ast_json *body, struct ast_ari_bridges_create_with_id_args *args)
Body parsing function for /bridges/{bridgeId}.
static void ast_ari_bridges_destroy_cb (struct ast_tcptls_session_instance *ser, struct ast_variable *get_params, struct ast_variable *path_vars, struct ast_variable *headers, struct ast_json *body, struct ast_ari_response *response)
Parameter parsing callback for /bridges/{bridgeId}.
static void ast_ari_bridges_get_cb (struct ast_tcptls_session_instance *ser, struct ast_variable *get_params, struct ast_variable *path_vars, struct ast_variable *headers, struct ast_json *body, struct ast_ari_response *response)
Parameter parsing callback for /bridges/{bridgeId}.
static void ast_ari_bridges_list_cb (struct ast_tcptls_session_instance *ser, struct ast_variable *get_params, struct ast_variable *path_vars, struct ast_variable *headers, struct ast_json *body, struct ast_ari_response *response)
Parameter parsing callback for /bridges.
static void ast_ari_bridges_play_cb (struct ast_tcptls_session_instance *ser, struct ast_variable *get_params, struct ast_variable *path_vars, struct ast_variable *headers, struct ast_json *body, struct ast_ari_response *response)
Parameter parsing callback for /bridges/{bridgeId}/play.
int ast_ari_bridges_play_parse_body (struct ast_json *body, struct ast_ari_bridges_play_args *args)
Body parsing function for /bridges/{bridgeId}/play.
static void ast_ari_bridges_play_with_id_cb (struct ast_tcptls_session_instance *ser, struct ast_variable *get_params, struct ast_variable *path_vars, struct ast_variable *headers, struct ast_json *body, struct ast_ari_response *response)
Parameter parsing callback for /bridges/{bridgeId}/play/{playbackId}.
int ast_ari_bridges_play_with_id_parse_body (struct ast_json *body, struct ast_ari_bridges_play_with_id_args *args)
Body parsing function for /bridges/{bridgeId}/play/{playbackId}.
static void ast_ari_bridges_record_cb (struct ast_tcptls_session_instance *ser, struct ast_variable *get_params, struct ast_variable *path_vars, struct ast_variable *headers, struct ast_json *body, struct ast_ari_response *response)
Parameter parsing callback for /bridges/{bridgeId}/record.
int ast_ari_bridges_record_parse_body (struct ast_json *body, struct ast_ari_bridges_record_args *args)
Body parsing function for /bridges/{bridgeId}/record.
static void ast_ari_bridges_remove_channel_cb (struct ast_tcptls_session_instance *ser, struct ast_variable *get_params, struct ast_variable *path_vars, struct ast_variable *headers, struct ast_json *body, struct ast_ari_response *response)
Parameter parsing callback for /bridges/{bridgeId}/removeChannel.
int ast_ari_bridges_remove_channel_parse_body (struct ast_json *body, struct ast_ari_bridges_remove_channel_args *args)
Body parsing function for /bridges/{bridgeId}/removeChannel.
static void ast_ari_bridges_set_video_source_cb (struct ast_tcptls_session_instance *ser, struct ast_variable *get_params, struct ast_variable *path_vars, struct ast_variable *headers, struct ast_json *body, struct ast_ari_response *response)
Parameter parsing callback for /bridges/{bridgeId}/videoSource/{channelId}.
static void ast_ari_bridges_start_moh_cb (struct ast_tcptls_session_instance *ser, struct ast_variable *get_params, struct ast_variable *path_vars, struct ast_variable *headers, struct ast_json *body, struct ast_ari_response *response)
Parameter parsing callback for /bridges/{bridgeId}/moh.
int ast_ari_bridges_start_moh_parse_body (struct ast_json *body, struct ast_ari_bridges_start_moh_args *args)
Body parsing function for /bridges/{bridgeId}/moh.
static void ast_ari_bridges_stop_moh_cb (struct ast_tcptls_session_instance *ser, struct ast_variable *get_params, struct ast_variable *path_vars, struct ast_variable *headers, struct ast_json *body, struct ast_ari_response *response)
Parameter parsing callback for /bridges/{bridgeId}/moh.
struct ast_module * AST_MODULE_SELF_SYM (void)
static int load_module (void)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_DEFAULT , .description = "RESTful API module - Bridge resources" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .requires = "res_ari,res_ari_model,res_stasis,res_stasis_recording,res_stasis_playback", }
static const struct ast_module_info * ast_module_info = &__mod_info
static struct stasis_rest_handlers bridges
REST handler for /api-docs/bridges.json.
static struct stasis_rest_handlers bridges_bridgeId
REST handler for /api-docs/bridges.json.
static struct stasis_rest_handlers bridges_bridgeId_addChannel
REST handler for /api-docs/bridges.json.
static struct stasis_rest_handlers bridges_bridgeId_moh
REST handler for /api-docs/bridges.json.
static struct stasis_rest_handlers bridges_bridgeId_play
REST handler for /api-docs/bridges.json.
static struct stasis_rest_handlers bridges_bridgeId_play_playbackId
REST handler for /api-docs/bridges.json.
static struct stasis_rest_handlers bridges_bridgeId_record
REST handler for /api-docs/bridges.json.
static struct stasis_rest_handlers bridges_bridgeId_removeChannel
REST handler for /api-docs/bridges.json.
static struct stasis_rest_handlers bridges_bridgeId_videoSource
REST handler for /api-docs/bridges.json.
static struct stasis_rest_handlers bridges_bridgeId_videoSource_channelId
REST handler for /api-docs/bridges.json.
Detailed Description
Bridge resources.
Author
David M. Lee, II dlee@.nosp@m.digi.nosp@m.um.co.nosp@m.m
Definition in file res_ari_bridges.c.
Macro Definition Documentation
MAX_VALS
#define MAX_VALS 128
Definition at line 53 of file res_ari_bridges.c.
Referenced by ast_ari_bridges_add_channel_cb(), ast_ari_bridges_play_cb(), ast_ari_bridges_play_with_id_cb(), and ast_ari_bridges_remove_channel_cb().
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 1588 of file res_ari_bridges.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 1588 of file res_ari_bridges.c.
ast_ari_bridges_add_channel_cb()
static void ast_ari_bridges_add_channel_cb (struct ast_tcptls_session_instance * ser, struct ast_variable * get_params, struct ast_variable * path_vars, struct ast_variable * headers, struct ast_json * body, struct ast_ari_response * response) static
Parameter parsing callback for /bridges/{bridgeId}/addChannel.
Parameters
get_params GET parameters in the HTTP request.
path_vars Path variables extracted from the request.
headers HTTP headers.
[out] response Response to the HTTP request.
Definition at line 457 of file res_ari_bridges.c.
References ast_ari_bridges_add_channel_args::absorb_dtmf, ARRAY_LEN, ast_app_separate_args, ast_ari_bridges_add_channel(), ast_ari_bridges_add_channel_parse_body(), ast_ari_response_alloc_failed(), ast_ari_response_error(), ast_ari_validate_void(), ast_free, ast_log, ast_malloc, ast_strdup, ast_true(), ast_ari_bridges_add_channel_args::bridge_id, ast_ari_bridges_add_channel_args::channel, ast_ari_bridges_add_channel_args::channel_count, ast_ari_bridges_add_channel_args::channel_parse, ast_ari_bridges_add_channel_args::inhibit_connected_line_updates, LOG_ERROR, MAX_VALS, ast_ari_response::message, ast_ari_bridges_add_channel_args::mute, ast_variable::name, ast_variable::next, NULL, ast_ari_response::response_code, ast_ari_bridges_add_channel_args::role, and ast_variable::value.
 {
    struct ast_ari_bridges_add_channel_args args = {};
    struct ast_variable *i;
 #if defined(AST_DEVMODE)
    int is_valid;
    int code;
 #endif /* AST_DEVMODE */
    for (i = get_params; i; i = i->next) {
       if (strcmp(i->name, "channel") == 0) {
          /* Parse comma separated list */
          char *vals[MAX_VALS];
          size_t j;
          args.channel_parse = ast_strdup(i->value);
          if (!args.channel_parse) {
             ast_ari_response_alloc_failed(response);
             goto fin;
          }
          if (strlen(args.channel_parse) == 0) {
             /* ast_app_separate_args can't handle "" */
             args.channel_count = 1;
             vals[0] = args.channel_parse;
          } else {
             args.channel_count = ast_app_separate_args(
                args.channel_parse, ',', vals,
                ARRAY_LEN(vals));
          }
          if (args.channel_count == 0) {
             ast_ari_response_alloc_failed(response);
             goto fin;
          }
          if (args.channel_count >= MAX_VALS) {
             ast_ari_response_error(response, 400,
                "Bad Request",
                "Too many values for channel");
             goto fin;
          }
          args.channel = ast_malloc(sizeof(*args.channel) * args.channel_count);
          if (!args.channel) {
             ast_ari_response_alloc_failed(response);
             goto fin;
          }
          for (j = 0; j < args.channel_count; ++j) {
             args.channel[j] = (vals[j]);
          }
       } else
       if (strcmp(i->name, "role") == 0) {
          args.role = (i->value);
       } else
       if (strcmp(i->name, "absorbDTMF") == 0) {
          args.absorb_dtmf = ast_true(i->value);
       } else
       if (strcmp(i->name, "mute") == 0) {
          args.mute = ast_true(i->value);
       } else
       if (strcmp(i->name, "inhibitConnectedLineUpdates") == 0) {
          args.inhibit_connected_line_updates = ast_true(i->value);
       } else
       {}
    }
    for (i = path_vars; i; i = i->next) {
       if (strcmp(i->name, "bridgeId") == 0) {
          args.bridge_id = (i->value);
       } else
       {}
    }
    if (ast_ari_bridges_add_channel_parse_body(body, &args)) {
       ast_ari_response_alloc_failed(response);
       goto fin;
    }
    ast_ari_bridges_add_channel(headers, &args, response);
 #if defined(AST_DEVMODE)
    code = response->response_code;
    switch (code) {
    case 0: /* Implementation is still a stub, or the code wasn't set */
       is_valid = response->message == NULL;
       break;
    case 500: /* Internal Server Error */
    case 501: /* Not Implemented */
    case 400: /* Channel not found */
    case 404: /* Bridge not found */
    case 409: /* Bridge not in Stasis application; Channel currently recording */
    case 422: /* Channel not in Stasis application */
       is_valid = 1;
       break;
    default:
       if (200 <= code && code <= 299) {
          is_valid = ast_ari_validate_void(
             response->message);
       } else {
          ast_log(LOG_ERROR, "Invalid error response %d for /bridges/{bridgeId}/addChannel\n", code);
          is_valid = 0;
       }
    }
    if (!is_valid) {
       ast_log(LOG_ERROR, "Response validation failed for /bridges/{bridgeId}/addChannel\n");
       ast_ari_response_error(response, 500,
          "Internal Server Error", "Response validation failed");
    }
 #endif /* AST_DEVMODE */
 fin: __attribute__((unused))
    ast_free(args.channel_parse);
    ast_free(args.channel);
    return;
 }
ast_ari_bridges_add_channel_parse_body()
int ast_ari_bridges_add_channel_parse_body (struct ast_json * body, struct ast_ari_bridges_add_channel_args * args)
Body parsing function for /bridges/{bridgeId}/addChannel.
Parameters
body The JSON body from which to parse parameters.
[out] args The args structure to parse into.
Return values
zero on success
non-zero on failure
Definition at line 396 of file res_ari_bridges.c.
References ast_ari_bridges_add_channel_args::absorb_dtmf, ast_free, AST_JSON_ARRAY, ast_json_array_get(), ast_json_array_size(), ast_json_is_true(), ast_json_object_get(), ast_json_string_get(), ast_json_typeof(), ast_malloc, ast_ari_bridges_add_channel_args::channel, ast_ari_bridges_add_channel_args::channel_count, ast_ari_bridges_add_channel_args::inhibit_connected_line_updates, ast_ari_bridges_add_channel_args::mute, and ast_ari_bridges_add_channel_args::role.
Referenced by ast_ari_bridges_add_channel_cb().
 {
    struct ast_json *field;
    /* Parse query parameters out of it */
    field = ast_json_object_get(body, "channel");
    if (field) {
       /* If they were silly enough to both pass in a query param and a
        * JSON body, free up the query value.
        */
       ast_free(args->channel);
       if (ast_json_typeof(field) == AST_JSON_ARRAY) {
          /* Multiple param passed as array */
          size_t i;
          args->channel_count = ast_json_array_size(field);
          args->channel = ast_malloc(sizeof(*args->channel) * args->channel_count);
          if (!args->channel) {
             return -1;
          }
          for (i = 0; i < args->channel_count; ++i) {
             args->channel[i] = ast_json_string_get(ast_json_array_get(field, i));
          }
       } else {
          /* Multiple param passed as single value */
          args->channel_count = 1;
          args->channel = ast_malloc(sizeof(*args->channel) * args->channel_count);
          if (!args->channel) {
             return -1;
          }
          args->channel[0] = ast_json_string_get(field);
       }
    }
    field = ast_json_object_get(body, "role");
    if (field) {
       args->role = ast_json_string_get(field);
    }
    field = ast_json_object_get(body, "absorbDTMF");
    if (field) {
       args->absorb_dtmf = ast_json_is_true(field);
    }
    field = ast_json_object_get(body, "mute");
    if (field) {
       args->mute = ast_json_is_true(field);
    }
    field = ast_json_object_get(body, "inhibitConnectedLineUpdates");
    if (field) {
       args->inhibit_connected_line_updates = ast_json_is_true(field);
    }
    return 0;
 }
ast_ari_bridges_clear_video_source_cb()
static void ast_ari_bridges_clear_video_source_cb (struct ast_tcptls_session_instance * ser, struct ast_variable * get_params, struct ast_variable * path_vars, struct ast_variable * headers, struct ast_json * body, struct ast_ari_response * response) static
Parameter parsing callback for /bridges/{bridgeId}/videoSource.
Parameters
get_params GET parameters in the HTTP request.
path_vars Path variables extracted from the request.
headers HTTP headers.
[out] response Response to the HTTP request.
Definition at line 796 of file res_ari_bridges.c.
References ast_ari_bridges_clear_video_source(), ast_ari_response_error(), ast_ari_validate_void(), ast_log, ast_ari_bridges_clear_video_source_args::bridge_id, LOG_ERROR, ast_ari_response::message, ast_variable::name, ast_variable::next, NULL, ast_ari_response::response_code, and ast_variable::value.
 {
    struct ast_ari_bridges_clear_video_source_args args = {};
    struct ast_variable *i;
 #if defined(AST_DEVMODE)
    int is_valid;
    int code;
 #endif /* AST_DEVMODE */
    for (i = path_vars; i; i = i->next) {
       if (strcmp(i->name, "bridgeId") == 0) {
          args.bridge_id = (i->value);
       } else
       {}
    }
    ast_ari_bridges_clear_video_source(headers, &args, response);
 #if defined(AST_DEVMODE)
    code = response->response_code;
    switch (code) {
    case 0: /* Implementation is still a stub, or the code wasn't set */
       is_valid = response->message == NULL;
       break;
    case 500: /* Internal Server Error */
    case 501: /* Not Implemented */
    case 404: /* Bridge not found */
       is_valid = 1;
       break;
    default:
       if (200 <= code && code <= 299) {
          is_valid = ast_ari_validate_void(
             response->message);
       } else {
          ast_log(LOG_ERROR, "Invalid error response %d for /bridges/{bridgeId}/videoSource\n", code);
          is_valid = 0;
       }
    }
    if (!is_valid) {
       ast_log(LOG_ERROR, "Response validation failed for /bridges/{bridgeId}/videoSource\n");
       ast_ari_response_error(response, 500,
          "Internal Server Error", "Response validation failed");
    }
 #endif /* AST_DEVMODE */
 fin: __attribute__((unused))
    return;
 }
ast_ari_bridges_create_cb()
static void ast_ari_bridges_create_cb (struct ast_tcptls_session_instance * ser, struct ast_variable * get_params, struct ast_variable * path_vars, struct ast_variable * headers, struct ast_json * body, struct ast_ari_response * response) static
Parameter parsing callback for /bridges.
Parameters
get_params GET parameters in the HTTP request.
path_vars Path variables extracted from the request.
headers HTTP headers.
[out] response Response to the HTTP request.
Definition at line 133 of file res_ari_bridges.c.
References ast_ari_bridges_create(), ast_ari_bridges_create_parse_body(), ast_ari_response_alloc_failed(), ast_ari_response_error(), ast_ari_validate_bridge(), ast_log, ast_ari_bridges_create_args::bridge_id, LOG_ERROR, ast_ari_response::message, ast_ari_bridges_create_args::name, ast_variable::name, ast_variable::next, NULL, ast_ari_response::response_code, ast_ari_bridges_create_args::type, and ast_variable::value.
 {
    struct ast_ari_bridges_create_args args = {};
    struct ast_variable *i;
 #if defined(AST_DEVMODE)
    int is_valid;
    int code;
 #endif /* AST_DEVMODE */
    for (i = get_params; i; i = i->next) {
       if (strcmp(i->name, "type") == 0) {
          args.type = (i->value);
       } else
       if (strcmp(i->name, "bridgeId") == 0) {
          args.bridge_id = (i->value);
       } else
       if (strcmp(i->name, "name") == 0) {
          args.name = (i->value);
       } else
       {}
    }
    if (ast_ari_bridges_create_parse_body(body, &args)) {
       ast_ari_response_alloc_failed(response);
       goto fin;
    }
    ast_ari_bridges_create(headers, &args, response);
 #if defined(AST_DEVMODE)
    code = response->response_code;
    switch (code) {
    case 0: /* Implementation is still a stub, or the code wasn't set */
       is_valid = response->message == NULL;
       break;
    case 500: /* Internal Server Error */
    case 501: /* Not Implemented */
       is_valid = 1;
       break;
    default:
       if (200 <= code && code <= 299) {
          is_valid = ast_ari_validate_bridge(
             response->message);
       } else {
          ast_log(LOG_ERROR, "Invalid error response %d for /bridges\n", code);
          is_valid = 0;
       }
    }
    if (!is_valid) {
       ast_log(LOG_ERROR, "Response validation failed for /bridges\n");
       ast_ari_response_error(response, 500,
          "Internal Server Error", "Response validation failed");
    }
 #endif /* AST_DEVMODE */
 fin: __attribute__((unused))
    return;
 }
ast_ari_bridges_create_parse_body()
int ast_ari_bridges_create_parse_body (struct ast_json * body, struct ast_ari_bridges_create_args * args)
Body parsing function for /bridges.
Parameters
body The JSON body from which to parse parameters.
[out] args The args structure to parse into.
Return values
zero on success
non-zero on failure
Definition at line 105 of file res_ari_bridges.c.
References ast_json_object_get(), ast_json_string_get(), ast_ari_bridges_create_args::bridge_id, ast_ari_bridges_create_args::name, and ast_ari_bridges_create_args::type.
Referenced by ast_ari_bridges_create_cb().
 {
    struct ast_json *field;
    /* Parse query parameters out of it */
    field = ast_json_object_get(body, "type");
    if (field) {
       args->type = ast_json_string_get(field);
    }
    field = ast_json_object_get(body, "bridgeId");
    if (field) {
       args->bridge_id = ast_json_string_get(field);
    }
    field = ast_json_object_get(body, "name");
    if (field) {
       args->name = ast_json_string_get(field);
    }
    return 0;
 }
ast_ari_bridges_create_with_id_cb()
static void ast_ari_bridges_create_with_id_cb (struct ast_tcptls_session_instance * ser, struct ast_variable * get_params, struct ast_variable * path_vars, struct ast_variable * headers, struct ast_json * body, struct ast_ari_response * response) static
Parameter parsing callback for /bridges/{bridgeId}.
Parameters
get_params GET parameters in the HTTP request.
path_vars Path variables extracted from the request.
headers HTTP headers.
[out] response Response to the HTTP request.
Definition at line 217 of file res_ari_bridges.c.
References ast_ari_bridges_create_with_id(), ast_ari_bridges_create_with_id_parse_body(), ast_ari_response_alloc_failed(), ast_ari_response_error(), ast_ari_validate_bridge(), ast_log, ast_ari_bridges_create_with_id_args::bridge_id, LOG_ERROR, ast_ari_response::message, ast_variable::name, ast_ari_bridges_create_with_id_args::name, ast_variable::next, NULL, ast_ari_response::response_code, ast_ari_bridges_create_with_id_args::type, and ast_variable::value.
 {
    struct ast_ari_bridges_create_with_id_args args = {};
    struct ast_variable *i;
 #if defined(AST_DEVMODE)
    int is_valid;
    int code;
 #endif /* AST_DEVMODE */
    for (i = get_params; i; i = i->next) {
       if (strcmp(i->name, "type") == 0) {
          args.type = (i->value);
       } else
       if (strcmp(i->name, "name") == 0) {
          args.name = (i->value);
       } else
       {}
    }
    for (i = path_vars; i; i = i->next) {
       if (strcmp(i->name, "bridgeId") == 0) {
          args.bridge_id = (i->value);
       } else
       {}
    }
    if (ast_ari_bridges_create_with_id_parse_body(body, &args)) {
       ast_ari_response_alloc_failed(response);
       goto fin;
    }
    ast_ari_bridges_create_with_id(headers, &args, response);
 #if defined(AST_DEVMODE)
    code = response->response_code;
    switch (code) {
    case 0: /* Implementation is still a stub, or the code wasn't set */
       is_valid = response->message == NULL;
       break;
    case 500: /* Internal Server Error */
    case 501: /* Not Implemented */
       is_valid = 1;
       break;
    default:
       if (200 <= code && code <= 299) {
          is_valid = ast_ari_validate_bridge(
             response->message);
       } else {
          ast_log(LOG_ERROR, "Invalid error response %d for /bridges/{bridgeId}\n", code);
          is_valid = 0;
       }
    }
    if (!is_valid) {
       ast_log(LOG_ERROR, "Response validation failed for /bridges/{bridgeId}\n");
       ast_ari_response_error(response, 500,
          "Internal Server Error", "Response validation failed");
    }
 #endif /* AST_DEVMODE */
 fin: __attribute__((unused))
    return;
 }
ast_ari_bridges_create_with_id_parse_body()
int ast_ari_bridges_create_with_id_parse_body (struct ast_json * body, struct ast_ari_bridges_create_with_id_args * args)
Body parsing function for /bridges/{bridgeId}.
Parameters
body The JSON body from which to parse parameters.
[out] args The args structure to parse into.
Return values
zero on success
non-zero on failure
Definition at line 193 of file res_ari_bridges.c.
References ast_json_object_get(), ast_json_string_get(), ast_ari_bridges_create_with_id_args::name, and ast_ari_bridges_create_with_id_args::type.
Referenced by ast_ari_bridges_create_with_id_cb().
 {
    struct ast_json *field;
    /* Parse query parameters out of it */
    field = ast_json_object_get(body, "type");
    if (field) {
       args->type = ast_json_string_get(field);
    }
    field = ast_json_object_get(body, "name");
    if (field) {
       args->name = ast_json_string_get(field);
    }
    return 0;
 }
ast_ari_bridges_destroy_cb()
static void ast_ari_bridges_destroy_cb (struct ast_tcptls_session_instance * ser, struct ast_variable * get_params, struct ast_variable * path_vars, struct ast_variable * headers, struct ast_json * body, struct ast_ari_response * response) static
Parameter parsing callback for /bridges/{bridgeId}.
Parameters
get_params GET parameters in the HTTP request.
path_vars Path variables extracted from the request.
headers HTTP headers.
[out] response Response to the HTTP request.
Definition at line 345 of file res_ari_bridges.c.
References ast_ari_bridges_destroy(), ast_ari_response_error(), ast_ari_validate_void(), ast_log, ast_ari_bridges_destroy_args::bridge_id, LOG_ERROR, ast_ari_response::message, ast_variable::name, ast_variable::next, NULL, ast_ari_response::response_code, and ast_variable::value.
 {
    struct ast_ari_bridges_destroy_args args = {};
    struct ast_variable *i;
 #if defined(AST_DEVMODE)
    int is_valid;
    int code;
 #endif /* AST_DEVMODE */
    for (i = path_vars; i; i = i->next) {
       if (strcmp(i->name, "bridgeId") == 0) {
          args.bridge_id = (i->value);
       } else
       {}
    }
    ast_ari_bridges_destroy(headers, &args, response);
 #if defined(AST_DEVMODE)
    code = response->response_code;
    switch (code) {
    case 0: /* Implementation is still a stub, or the code wasn't set */
       is_valid = response->message == NULL;
       break;
    case 500: /* Internal Server Error */
    case 501: /* Not Implemented */
    case 404: /* Bridge not found */
       is_valid = 1;
       break;
    default:
       if (200 <= code && code <= 299) {
          is_valid = ast_ari_validate_void(
             response->message);
       } else {
          ast_log(LOG_ERROR, "Invalid error response %d for /bridges/{bridgeId}\n", code);
          is_valid = 0;
       }
    }
    if (!is_valid) {
       ast_log(LOG_ERROR, "Response validation failed for /bridges/{bridgeId}\n");
       ast_ari_response_error(response, 500,
          "Internal Server Error", "Response validation failed");
    }
 #endif /* AST_DEVMODE */
 fin: __attribute__((unused))
    return;
 }
ast_ari_bridges_get_cb()
static void ast_ari_bridges_get_cb (struct ast_tcptls_session_instance * ser, struct ast_variable * get_params, struct ast_variable * path_vars, struct ast_variable * headers, struct ast_json * body, struct ast_ari_response * response) static
Parameter parsing callback for /bridges/{bridgeId}.
Parameters
get_params GET parameters in the HTTP request.
path_vars Path variables extracted from the request.
headers HTTP headers.
[out] response Response to the HTTP request.
Definition at line 287 of file res_ari_bridges.c.
References ast_ari_bridges_get(), ast_ari_response_error(), ast_ari_validate_bridge(), ast_log, ast_ari_bridges_get_args::bridge_id, LOG_ERROR, ast_ari_response::message, ast_variable::name, ast_variable::next, NULL, ast_ari_response::response_code, and ast_variable::value.
 {
    struct ast_ari_bridges_get_args args = {};
    struct ast_variable *i;
 #if defined(AST_DEVMODE)
    int is_valid;
    int code;
 #endif /* AST_DEVMODE */
    for (i = path_vars; i; i = i->next) {
       if (strcmp(i->name, "bridgeId") == 0) {
          args.bridge_id = (i->value);
       } else
       {}
    }
    ast_ari_bridges_get(headers, &args, response);
 #if defined(AST_DEVMODE)
    code = response->response_code;
    switch (code) {
    case 0: /* Implementation is still a stub, or the code wasn't set */
       is_valid = response->message == NULL;
       break;
    case 500: /* Internal Server Error */
    case 501: /* Not Implemented */
    case 404: /* Bridge not found */
       is_valid = 1;
       break;
    default:
       if (200 <= code && code <= 299) {
          is_valid = ast_ari_validate_bridge(
             response->message);
       } else {
          ast_log(LOG_ERROR, "Invalid error response %d for /bridges/{bridgeId}\n", code);
          is_valid = 0;
       }
    }
    if (!is_valid) {
       ast_log(LOG_ERROR, "Response validation failed for /bridges/{bridgeId}\n");
       ast_ari_response_error(response, 500,
          "Internal Server Error", "Response validation failed");
    }
 #endif /* AST_DEVMODE */
 fin: __attribute__((unused))
    return;
 }
ast_ari_bridges_list_cb()
static void ast_ari_bridges_list_cb (struct ast_tcptls_session_instance * ser, struct ast_variable * get_params, struct ast_variable * path_vars, struct ast_variable * headers, struct ast_json * body, struct ast_ari_response * response) static
Parameter parsing callback for /bridges.
Parameters
get_params GET parameters in the HTTP request.
path_vars Path variables extracted from the request.
headers HTTP headers.
[out] response Response to the HTTP request.
Definition at line 62 of file res_ari_bridges.c.
References ast_ari_bridges_list(), ast_ari_response_error(), ast_ari_validate_bridge_fn(), ast_ari_validate_list(), ast_log, LOG_ERROR, ast_ari_response::message, NULL, and ast_ari_response::response_code.
 {
    struct ast_ari_bridges_list_args args = {};
 #if defined(AST_DEVMODE)
    int is_valid;
    int code;
 #endif /* AST_DEVMODE */
    ast_ari_bridges_list(headers, &args, response);
 #if defined(AST_DEVMODE)
    code = response->response_code;
    switch (code) {
    case 0: /* Implementation is still a stub, or the code wasn't set */
       is_valid = response->message == NULL;
       break;
    case 500: /* Internal Server Error */
    case 501: /* Not Implemented */
       is_valid = 1;
       break;
    default:
       if (200 <= code && code <= 299) {
          is_valid = ast_ari_validate_list(response->message,
             ast_ari_validate_bridge_fn());
       } else {
          ast_log(LOG_ERROR, "Invalid error response %d for /bridges\n", code);
          is_valid = 0;
       }
    }
    if (!is_valid) {
       ast_log(LOG_ERROR, "Response validation failed for /bridges\n");
       ast_ari_response_error(response, 500,
          "Internal Server Error", "Response validation failed");
    }
 #endif /* AST_DEVMODE */
 fin: __attribute__((unused))
    return;
 }
ast_ari_bridges_play_cb()
static void ast_ari_bridges_play_cb (struct ast_tcptls_session_instance * ser, struct ast_variable * get_params, struct ast_variable * path_vars, struct ast_variable * headers, struct ast_json * body, struct ast_ari_response * response) static
Parameter parsing callback for /bridges/{bridgeId}/play.
Parameters
get_params GET parameters in the HTTP request.
path_vars Path variables extracted from the request.
headers HTTP headers.
[out] response Response to the HTTP request.
Definition at line 1049 of file res_ari_bridges.c.
References ARRAY_LEN, ast_app_separate_args, ast_ari_bridges_play(), ast_ari_bridges_play_parse_body(), ast_ari_response_alloc_failed(), ast_ari_response_error(), ast_ari_validate_playback(), ast_free, ast_log, ast_malloc, ast_strdup, ast_ari_bridges_play_args::bridge_id, ast_ari_bridges_play_args::lang, LOG_ERROR, MAX_VALS, ast_ari_bridges_play_args::media, ast_ari_bridges_play_args::media_count, ast_ari_bridges_play_args::media_parse, ast_ari_response::message, ast_variable::name, ast_variable::next, NULL, ast_ari_bridges_play_args::offsetms, ast_ari_bridges_play_args::playback_id, ast_ari_response::response_code, ast_ari_bridges_play_args::skipms, and ast_variable::value.
 {
    struct ast_ari_bridges_play_args args = {};
    struct ast_variable *i;
 #if defined(AST_DEVMODE)
    int is_valid;
    int code;
 #endif /* AST_DEVMODE */
    for (i = get_params; i; i = i->next) {
       if (strcmp(i->name, "media") == 0) {
          /* Parse comma separated list */
          char *vals[MAX_VALS];
          size_t j;
          args.media_parse = ast_strdup(i->value);
          if (!args.media_parse) {
             ast_ari_response_alloc_failed(response);
             goto fin;
          }
          if (strlen(args.media_parse) == 0) {
             /* ast_app_separate_args can't handle "" */
             args.media_count = 1;
             vals[0] = args.media_parse;
          } else {
             args.media_count = ast_app_separate_args(
                args.media_parse, ',', vals,
                ARRAY_LEN(vals));
          }
          if (args.media_count == 0) {
             ast_ari_response_alloc_failed(response);
             goto fin;
          }
          if (args.media_count >= MAX_VALS) {
             ast_ari_response_error(response, 400,
                "Bad Request",
                "Too many values for media");
             goto fin;
          }
          args.media = ast_malloc(sizeof(*args.media) * args.media_count);
          if (!args.media) {
             ast_ari_response_alloc_failed(response);
             goto fin;
          }
          for (j = 0; j < args.media_count; ++j) {
             args.media[j] = (vals[j]);
          }
       } else
       if (strcmp(i->name, "lang") == 0) {
          args.lang = (i->value);
       } else
       if (strcmp(i->name, "offsetms") == 0) {
          args.offsetms = atoi(i->value);
       } else
       if (strcmp(i->name, "skipms") == 0) {
          args.skipms = atoi(i->value);
       } else
       if (strcmp(i->name, "playbackId") == 0) {
          args.playback_id = (i->value);
       } else
       {}
    }
    for (i = path_vars; i; i = i->next) {
       if (strcmp(i->name, "bridgeId") == 0) {
          args.bridge_id = (i->value);
       } else
       {}
    }
    if (ast_ari_bridges_play_parse_body(body, &args)) {
       ast_ari_response_alloc_failed(response);
       goto fin;
    }
    ast_ari_bridges_play(headers, &args, response);
 #if defined(AST_DEVMODE)
    code = response->response_code;
    switch (code) {
    case 0: /* Implementation is still a stub, or the code wasn't set */
       is_valid = response->message == NULL;
       break;
    case 500: /* Internal Server Error */
    case 501: /* Not Implemented */
    case 404: /* Bridge not found */
    case 409: /* Bridge not in a Stasis application */
       is_valid = 1;
       break;
    default:
       if (200 <= code && code <= 299) {
          is_valid = ast_ari_validate_playback(
             response->message);
       } else {
          ast_log(LOG_ERROR, "Invalid error response %d for /bridges/{bridgeId}/play\n", code);
          is_valid = 0;
       }
    }
    if (!is_valid) {
       ast_log(LOG_ERROR, "Response validation failed for /bridges/{bridgeId}/play\n");
       ast_ari_response_error(response, 500,
          "Internal Server Error", "Response validation failed");
    }
 #endif /* AST_DEVMODE */
 fin: __attribute__((unused))
    ast_free(args.media_parse);
    ast_free(args.media);
    return;
 }
ast_ari_bridges_play_parse_body()
int ast_ari_bridges_play_parse_body (struct ast_json * body, struct ast_ari_bridges_play_args * args)
Body parsing function for /bridges/{bridgeId}/play.
Parameters
body The JSON body from which to parse parameters.
[out] args The args structure to parse into.
Return values
zero on success
non-zero on failure
Definition at line 988 of file res_ari_bridges.c.
References ast_free, AST_JSON_ARRAY, ast_json_array_get(), ast_json_array_size(), ast_json_integer_get(), ast_json_object_get(), ast_json_string_get(), ast_json_typeof(), ast_malloc, ast_ari_bridges_play_args::lang, ast_ari_bridges_play_args::media, ast_ari_bridges_play_args::media_count, ast_ari_bridges_play_args::offsetms, ast_ari_bridges_play_args::playback_id, and ast_ari_bridges_play_args::skipms.
Referenced by ast_ari_bridges_play_cb().
 {
    struct ast_json *field;
    /* Parse query parameters out of it */
    field = ast_json_object_get(body, "media");
    if (field) {
       /* If they were silly enough to both pass in a query param and a
        * JSON body, free up the query value.
        */
       ast_free(args->media);
       if (ast_json_typeof(field) == AST_JSON_ARRAY) {
          /* Multiple param passed as array */
          size_t i;
          args->media_count = ast_json_array_size(field);
          args->media = ast_malloc(sizeof(*args->media) * args->media_count);
          if (!args->media) {
             return -1;
          }
          for (i = 0; i < args->media_count; ++i) {
             args->media[i] = ast_json_string_get(ast_json_array_get(field, i));
          }
       } else {
          /* Multiple param passed as single value */
          args->media_count = 1;
          args->media = ast_malloc(sizeof(*args->media) * args->media_count);
          if (!args->media) {
             return -1;
          }
          args->media[0] = ast_json_string_get(field);
       }
    }
    field = ast_json_object_get(body, "lang");
    if (field) {
       args->lang = ast_json_string_get(field);
    }
    field = ast_json_object_get(body, "offsetms");
    if (field) {
       args->offsetms = ast_json_integer_get(field);
    }
    field = ast_json_object_get(body, "skipms");
    if (field) {
       args->skipms = ast_json_integer_get(field);
    }
    field = ast_json_object_get(body, "playbackId");
    if (field) {
       args->playback_id = ast_json_string_get(field);
    }
    return 0;
 }
ast_ari_bridges_play_with_id_cb()
static void ast_ari_bridges_play_with_id_cb (struct ast_tcptls_session_instance * ser, struct ast_variable * get_params, struct ast_variable * path_vars, struct ast_variable * headers, struct ast_json * body, struct ast_ari_response * response) static
Parameter parsing callback for /bridges/{bridgeId}/play/{playbackId}.
Parameters
get_params GET parameters in the HTTP request.
path_vars Path variables extracted from the request.
headers HTTP headers.
[out] response Response to the HTTP request.
Definition at line 1222 of file res_ari_bridges.c.
References ARRAY_LEN, ast_app_separate_args, ast_ari_bridges_play_with_id(), ast_ari_bridges_play_with_id_parse_body(), ast_ari_response_alloc_failed(), ast_ari_response_error(), ast_ari_validate_playback(), ast_free, ast_log, ast_malloc, ast_strdup, ast_ari_bridges_play_with_id_args::bridge_id, ast_ari_bridges_play_with_id_args::lang, LOG_ERROR, MAX_VALS, ast_ari_bridges_play_with_id_args::media, ast_ari_bridges_play_with_id_args::media_count, ast_ari_bridges_play_with_id_args::media_parse, ast_ari_response::message, ast_variable::name, ast_variable::next, NULL, ast_ari_bridges_play_with_id_args::offsetms, ast_ari_bridges_play_with_id_args::playback_id, ast_ari_response::response_code, ast_ari_bridges_play_with_id_args::skipms, and ast_variable::value.
 {
    struct ast_ari_bridges_play_with_id_args args = {};
    struct ast_variable *i;
 #if defined(AST_DEVMODE)
    int is_valid;
    int code;
 #endif /* AST_DEVMODE */
    for (i = get_params; i; i = i->next) {
       if (strcmp(i->name, "media") == 0) {
          /* Parse comma separated list */
          char *vals[MAX_VALS];
          size_t j;
          args.media_parse = ast_strdup(i->value);
          if (!args.media_parse) {
             ast_ari_response_alloc_failed(response);
             goto fin;
          }
          if (strlen(args.media_parse) == 0) {
             /* ast_app_separate_args can't handle "" */
             args.media_count = 1;
             vals[0] = args.media_parse;
          } else {
             args.media_count = ast_app_separate_args(
                args.media_parse, ',', vals,
                ARRAY_LEN(vals));
          }
          if (args.media_count == 0) {
             ast_ari_response_alloc_failed(response);
             goto fin;
          }
          if (args.media_count >= MAX_VALS) {
             ast_ari_response_error(response, 400,
                "Bad Request",
                "Too many values for media");
             goto fin;
          }
          args.media = ast_malloc(sizeof(*args.media) * args.media_count);
          if (!args.media) {
             ast_ari_response_alloc_failed(response);
             goto fin;
          }
          for (j = 0; j < args.media_count; ++j) {
             args.media[j] = (vals[j]);
          }
       } else
       if (strcmp(i->name, "lang") == 0) {
          args.lang = (i->value);
       } else
       if (strcmp(i->name, "offsetms") == 0) {
          args.offsetms = atoi(i->value);
       } else
       if (strcmp(i->name, "skipms") == 0) {
          args.skipms = atoi(i->value);
       } else
       {}
    }
    for (i = path_vars; i; i = i->next) {
       if (strcmp(i->name, "bridgeId") == 0) {
          args.bridge_id = (i->value);
       } else
       if (strcmp(i->name, "playbackId") == 0) {
          args.playback_id = (i->value);
       } else
       {}
    }
    if (ast_ari_bridges_play_with_id_parse_body(body, &args)) {
       ast_ari_response_alloc_failed(response);
       goto fin;
    }
    ast_ari_bridges_play_with_id(headers, &args, response);
 #if defined(AST_DEVMODE)
    code = response->response_code;
    switch (code) {
    case 0: /* Implementation is still a stub, or the code wasn't set */
       is_valid = response->message == NULL;
       break;
    case 500: /* Internal Server Error */
    case 501: /* Not Implemented */
    case 404: /* Bridge not found */
    case 409: /* Bridge not in a Stasis application */
       is_valid = 1;
       break;
    default:
       if (200 <= code && code <= 299) {
          is_valid = ast_ari_validate_playback(
             response->message);
       } else {
          ast_log(LOG_ERROR, "Invalid error response %d for /bridges/{bridgeId}/play/{playbackId}\n", code);
          is_valid = 0;
       }
    }
    if (!is_valid) {
       ast_log(LOG_ERROR, "Response validation failed for /bridges/{bridgeId}/play/{playbackId}\n");
       ast_ari_response_error(response, 500,
          "Internal Server Error", "Response validation failed");
    }
 #endif /* AST_DEVMODE */
 fin: __attribute__((unused))
    ast_free(args.media_parse);
    ast_free(args.media);
    return;
 }
ast_ari_bridges_play_with_id_parse_body()
int ast_ari_bridges_play_with_id_parse_body (struct ast_json * body, struct ast_ari_bridges_play_with_id_args * args)
Body parsing function for /bridges/{bridgeId}/play/{playbackId}.
Parameters
body The JSON body from which to parse parameters.
[out] args The args structure to parse into.
Return values
zero on success
non-zero on failure
Definition at line 1165 of file res_ari_bridges.c.
References ast_free, AST_JSON_ARRAY, ast_json_array_get(), ast_json_array_size(), ast_json_integer_get(), ast_json_object_get(), ast_json_string_get(), ast_json_typeof(), ast_malloc, ast_ari_bridges_play_with_id_args::lang, ast_ari_bridges_play_with_id_args::media, ast_ari_bridges_play_with_id_args::media_count, ast_ari_bridges_play_with_id_args::offsetms, and ast_ari_bridges_play_with_id_args::skipms.
Referenced by ast_ari_bridges_play_with_id_cb().
 {
    struct ast_json *field;
    /* Parse query parameters out of it */
    field = ast_json_object_get(body, "media");
    if (field) {
       /* If they were silly enough to both pass in a query param and a
        * JSON body, free up the query value.
        */
       ast_free(args->media);
       if (ast_json_typeof(field) == AST_JSON_ARRAY) {
          /* Multiple param passed as array */
          size_t i;
          args->media_count = ast_json_array_size(field);
          args->media = ast_malloc(sizeof(*args->media) * args->media_count);
          if (!args->media) {
             return -1;
          }
          for (i = 0; i < args->media_count; ++i) {
             args->media[i] = ast_json_string_get(ast_json_array_get(field, i));
          }
       } else {
          /* Multiple param passed as single value */
          args->media_count = 1;
          args->media = ast_malloc(sizeof(*args->media) * args->media_count);
          if (!args->media) {
             return -1;
          }
          args->media[0] = ast_json_string_get(field);
       }
    }
    field = ast_json_object_get(body, "lang");
    if (field) {
       args->lang = ast_json_string_get(field);
    }
    field = ast_json_object_get(body, "offsetms");
    if (field) {
       args->offsetms = ast_json_integer_get(field);
    }
    field = ast_json_object_get(body, "skipms");
    if (field) {
       args->skipms = ast_json_integer_get(field);
    }
    return 0;
 }
ast_ari_bridges_record_cb()
static void ast_ari_bridges_record_cb (struct ast_tcptls_session_instance * ser, struct ast_variable * get_params, struct ast_variable * path_vars, struct ast_variable * headers, struct ast_json * body, struct ast_ari_response * response) static
Parameter parsing callback for /bridges/{bridgeId}/record.
Parameters
get_params GET parameters in the HTTP request.
path_vars Path variables extracted from the request.
headers HTTP headers.
[out] response Response to the HTTP request.
Definition at line 1382 of file res_ari_bridges.c.
References ast_ari_bridges_record(), ast_ari_bridges_record_parse_body(), ast_ari_response_alloc_failed(), ast_ari_response_error(), ast_ari_validate_live_recording(), ast_log, ast_true(), ast_ari_bridges_record_args::beep, ast_ari_bridges_record_args::bridge_id, ast_ari_bridges_record_args::format, ast_ari_bridges_record_args::if_exists, LOG_ERROR, ast_ari_bridges_record_args::max_duration_seconds, ast_ari_bridges_record_args::max_silence_seconds, ast_ari_response::message, ast_variable::name, ast_ari_bridges_record_args::name, ast_variable::next, NULL, ast_ari_response::response_code, ast_ari_bridges_record_args::terminate_on, and ast_variable::value.
 {
    struct ast_ari_bridges_record_args args = {};
    struct ast_variable *i;
 #if defined(AST_DEVMODE)
    int is_valid;
    int code;
 #endif /* AST_DEVMODE */
    for (i = get_params; i; i = i->next) {
       if (strcmp(i->name, "name") == 0) {
          args.name = (i->value);
       } else
       if (strcmp(i->name, "format") == 0) {
          args.format = (i->value);
       } else
       if (strcmp(i->name, "maxDurationSeconds") == 0) {
          args.max_duration_seconds = atoi(i->value);
       } else
       if (strcmp(i->name, "maxSilenceSeconds") == 0) {
          args.max_silence_seconds = atoi(i->value);
       } else
       if (strcmp(i->name, "ifExists") == 0) {
          args.if_exists = (i->value);
       } else
       if (strcmp(i->name, "beep") == 0) {
          args.beep = ast_true(i->value);
       } else
       if (strcmp(i->name, "terminateOn") == 0) {
          args.terminate_on = (i->value);
       } else
       {}
    }
    for (i = path_vars; i; i = i->next) {
       if (strcmp(i->name, "bridgeId") == 0) {
          args.bridge_id = (i->value);
       } else
       {}
    }
    if (ast_ari_bridges_record_parse_body(body, &args)) {
       ast_ari_response_alloc_failed(response);
       goto fin;
    }
    ast_ari_bridges_record(headers, &args, response);
 #if defined(AST_DEVMODE)
    code = response->response_code;
    switch (code) {
    case 0: /* Implementation is still a stub, or the code wasn't set */
       is_valid = response->message == NULL;
       break;
    case 500: /* Internal Server Error */
    case 501: /* Not Implemented */
    case 400: /* Invalid parameters */
    case 404: /* Bridge not found */
    case 409: /* Bridge is not in a Stasis application; A recording with the same name already exists on the system and can not be overwritten because it is in progress or ifExists=fail */
    case 422: /* The format specified is unknown on this system */
       is_valid = 1;
       break;
    default:
       if (200 <= code && code <= 299) {
          is_valid = ast_ari_validate_live_recording(
             response->message);
       } else {
          ast_log(LOG_ERROR, "Invalid error response %d for /bridges/{bridgeId}/record\n", code);
          is_valid = 0;
       }
    }
    if (!is_valid) {
       ast_log(LOG_ERROR, "Response validation failed for /bridges/{bridgeId}/record\n");
       ast_ari_response_error(response, 500,
          "Internal Server Error", "Response validation failed");
    }
 #endif /* AST_DEVMODE */
 fin: __attribute__((unused))
    return;
 }
ast_ari_bridges_record_parse_body()
int ast_ari_bridges_record_parse_body (struct ast_json * body, struct ast_ari_bridges_record_args * args)
Body parsing function for /bridges/{bridgeId}/record.
Parameters
body The JSON body from which to parse parameters.
[out] args The args structure to parse into.
Return values
zero on success
non-zero on failure
Definition at line 1338 of file res_ari_bridges.c.
References ast_json_integer_get(), ast_json_is_true(), ast_json_object_get(), ast_json_string_get(), ast_ari_bridges_record_args::beep, ast_ari_bridges_record_args::format, ast_ari_bridges_record_args::if_exists, ast_ari_bridges_record_args::max_duration_seconds, ast_ari_bridges_record_args::max_silence_seconds, ast_ari_bridges_record_args::name, and ast_ari_bridges_record_args::terminate_on.
Referenced by ast_ari_bridges_record_cb().
 {
    struct ast_json *field;
    /* Parse query parameters out of it */
    field = ast_json_object_get(body, "name");
    if (field) {
       args->name = ast_json_string_get(field);
    }
    field = ast_json_object_get(body, "format");
    if (field) {
       args->format = ast_json_string_get(field);
    }
    field = ast_json_object_get(body, "maxDurationSeconds");
    if (field) {
       args->max_duration_seconds = ast_json_integer_get(field);
    }
    field = ast_json_object_get(body, "maxSilenceSeconds");
    if (field) {
       args->max_silence_seconds = ast_json_integer_get(field);
    }
    field = ast_json_object_get(body, "ifExists");
    if (field) {
       args->if_exists = ast_json_string_get(field);
    }
    field = ast_json_object_get(body, "beep");
    if (field) {
       args->beep = ast_json_is_true(field);
    }
    field = ast_json_object_get(body, "terminateOn");
    if (field) {
       args->terminate_on = ast_json_string_get(field);
    }
    return 0;
 }
ast_ari_bridges_remove_channel_cb()
static void ast_ari_bridges_remove_channel_cb (struct ast_tcptls_session_instance * ser, struct ast_variable * get_params, struct ast_variable * path_vars, struct ast_variable * headers, struct ast_json * body, struct ast_ari_response * response) static
Parameter parsing callback for /bridges/{bridgeId}/removeChannel.
Parameters
get_params GET parameters in the HTTP request.
path_vars Path variables extracted from the request.
headers HTTP headers.
[out] response Response to the HTTP request.
Definition at line 620 of file res_ari_bridges.c.
References ARRAY_LEN, ast_app_separate_args, ast_ari_bridges_remove_channel(), ast_ari_bridges_remove_channel_parse_body(), ast_ari_response_alloc_failed(), ast_ari_response_error(), ast_ari_validate_void(), ast_free, ast_log, ast_malloc, ast_strdup, ast_ari_bridges_remove_channel_args::bridge_id, ast_ari_bridges_remove_channel_args::channel, ast_ari_bridges_remove_channel_args::channel_count, ast_ari_bridges_remove_channel_args::channel_parse, LOG_ERROR, MAX_VALS, ast_ari_response::message, ast_variable::name, ast_variable::next, NULL, ast_ari_response::response_code, and ast_variable::value.
 {
    struct ast_ari_bridges_remove_channel_args args = {};
    struct ast_variable *i;
 #if defined(AST_DEVMODE)
    int is_valid;
    int code;
 #endif /* AST_DEVMODE */
    for (i = get_params; i; i = i->next) {
       if (strcmp(i->name, "channel") == 0) {
          /* Parse comma separated list */
          char *vals[MAX_VALS];
          size_t j;
          args.channel_parse = ast_strdup(i->value);
          if (!args.channel_parse) {
             ast_ari_response_alloc_failed(response);
             goto fin;
          }
          if (strlen(args.channel_parse) == 0) {
             /* ast_app_separate_args can't handle "" */
             args.channel_count = 1;
             vals[0] = args.channel_parse;
          } else {
             args.channel_count = ast_app_separate_args(
                args.channel_parse, ',', vals,
                ARRAY_LEN(vals));
          }
          if (args.channel_count == 0) {
             ast_ari_response_alloc_failed(response);
             goto fin;
          }
          if (args.channel_count >= MAX_VALS) {
             ast_ari_response_error(response, 400,
                "Bad Request",
                "Too many values for channel");
             goto fin;
          }
          args.channel = ast_malloc(sizeof(*args.channel) * args.channel_count);
          if (!args.channel) {
             ast_ari_response_alloc_failed(response);
             goto fin;
          }
          for (j = 0; j < args.channel_count; ++j) {
             args.channel[j] = (vals[j]);
          }
       } else
       {}
    }
    for (i = path_vars; i; i = i->next) {
       if (strcmp(i->name, "bridgeId") == 0) {
          args.bridge_id = (i->value);
       } else
       {}
    }
    if (ast_ari_bridges_remove_channel_parse_body(body, &args)) {
       ast_ari_response_alloc_failed(response);
       goto fin;
    }
    ast_ari_bridges_remove_channel(headers, &args, response);
 #if defined(AST_DEVMODE)
    code = response->response_code;
    switch (code) {
    case 0: /* Implementation is still a stub, or the code wasn't set */
       is_valid = response->message == NULL;
       break;
    case 500: /* Internal Server Error */
    case 501: /* Not Implemented */
    case 400: /* Channel not found */
    case 404: /* Bridge not found */
    case 409: /* Bridge not in Stasis application */
    case 422: /* Channel not in this bridge */
       is_valid = 1;
       break;
    default:
       if (200 <= code && code <= 299) {
          is_valid = ast_ari_validate_void(
             response->message);
       } else {
          ast_log(LOG_ERROR, "Invalid error response %d for /bridges/{bridgeId}/removeChannel\n", code);
          is_valid = 0;
       }
    }
    if (!is_valid) {
       ast_log(LOG_ERROR, "Response validation failed for /bridges/{bridgeId}/removeChannel\n");
       ast_ari_response_error(response, 500,
          "Internal Server Error", "Response validation failed");
    }
 #endif /* AST_DEVMODE */
 fin: __attribute__((unused))
    ast_free(args.channel_parse);
    ast_free(args.channel);
    return;
 }
ast_ari_bridges_remove_channel_parse_body()
int ast_ari_bridges_remove_channel_parse_body (struct ast_json * body, struct ast_ari_bridges_remove_channel_args * args)
Body parsing function for /bridges/{bridgeId}/removeChannel.
Parameters
body The JSON body from which to parse parameters.
[out] args The args structure to parse into.
Return values
zero on success
non-zero on failure
Definition at line 575 of file res_ari_bridges.c.
References ast_free, AST_JSON_ARRAY, ast_json_array_get(), ast_json_array_size(), ast_json_object_get(), ast_json_string_get(), ast_json_typeof(), ast_malloc, ast_ari_bridges_remove_channel_args::channel, and ast_ari_bridges_remove_channel_args::channel_count.
Referenced by ast_ari_bridges_remove_channel_cb().
 {
    struct ast_json *field;
    /* Parse query parameters out of it */
    field = ast_json_object_get(body, "channel");
    if (field) {
       /* If they were silly enough to both pass in a query param and a
        * JSON body, free up the query value.
        */
       ast_free(args->channel);
       if (ast_json_typeof(field) == AST_JSON_ARRAY) {
          /* Multiple param passed as array */
          size_t i;
          args->channel_count = ast_json_array_size(field);
          args->channel = ast_malloc(sizeof(*args->channel) * args->channel_count);
          if (!args->channel) {
             return -1;
          }
          for (i = 0; i < args->channel_count; ++i) {
             args->channel[i] = ast_json_string_get(ast_json_array_get(field, i));
          }
       } else {
          /* Multiple param passed as single value */
          args->channel_count = 1;
          args->channel = ast_malloc(sizeof(*args->channel) * args->channel_count);
          if (!args->channel) {
             return -1;
          }
          args->channel[0] = ast_json_string_get(field);
       }
    }
    return 0;
 }
ast_ari_bridges_set_video_source_cb()
static void ast_ari_bridges_set_video_source_cb (struct ast_tcptls_session_instance * ser, struct ast_variable * get_params, struct ast_variable * path_vars, struct ast_variable * headers, struct ast_json * body, struct ast_ari_response * response) static
Parameter parsing callback for /bridges/{bridgeId}/videoSource/{channelId}.
Parameters
get_params GET parameters in the HTTP request.
path_vars Path variables extracted from the request.
headers HTTP headers.
[out] response Response to the HTTP request.
Definition at line 733 of file res_ari_bridges.c.
References ast_ari_bridges_set_video_source(), ast_ari_response_error(), ast_ari_validate_void(), ast_log, ast_ari_bridges_set_video_source_args::bridge_id, ast_ari_bridges_set_video_source_args::channel_id, LOG_ERROR, ast_ari_response::message, ast_variable::name, ast_variable::next, NULL, ast_ari_response::response_code, and ast_variable::value.
 {
    struct ast_ari_bridges_set_video_source_args args = {};
    struct ast_variable *i;
 #if defined(AST_DEVMODE)
    int is_valid;
    int code;
 #endif /* AST_DEVMODE */
    for (i = path_vars; i; i = i->next) {
       if (strcmp(i->name, "bridgeId") == 0) {
          args.bridge_id = (i->value);
       } else
       if (strcmp(i->name, "channelId") == 0) {
          args.channel_id = (i->value);
       } else
       {}
    }
    ast_ari_bridges_set_video_source(headers, &args, response);
 #if defined(AST_DEVMODE)
    code = response->response_code;
    switch (code) {
    case 0: /* Implementation is still a stub, or the code wasn't set */
       is_valid = response->message == NULL;
       break;
    case 500: /* Internal Server Error */
    case 501: /* Not Implemented */
    case 404: /* Bridge or Channel not found */
    case 409: /* Channel not in Stasis application */
    case 422: /* Channel not in this Bridge */
       is_valid = 1;
       break;
    default:
       if (200 <= code && code <= 299) {
          is_valid = ast_ari_validate_void(
             response->message);
       } else {
          ast_log(LOG_ERROR, "Invalid error response %d for /bridges/{bridgeId}/videoSource/{channelId}\n", code);
          is_valid = 0;
       }
    }
    if (!is_valid) {
       ast_log(LOG_ERROR, "Response validation failed for /bridges/{bridgeId}/videoSource/{channelId}\n");
       ast_ari_response_error(response, 500,
          "Internal Server Error", "Response validation failed");
    }
 #endif /* AST_DEVMODE */
 fin: __attribute__((unused))
    return;
 }
ast_ari_bridges_start_moh_cb()
static void ast_ari_bridges_start_moh_cb (struct ast_tcptls_session_instance * ser, struct ast_variable * get_params, struct ast_variable * path_vars, struct ast_variable * headers, struct ast_json * body, struct ast_ari_response * response) static
Parameter parsing callback for /bridges/{bridgeId}/moh.
Parameters
get_params GET parameters in the HTTP request.
path_vars Path variables extracted from the request.
headers HTTP headers.
[out] response Response to the HTTP request.
Definition at line 867 of file res_ari_bridges.c.
References ast_ari_bridges_start_moh(), ast_ari_bridges_start_moh_parse_body(), ast_ari_response_alloc_failed(), ast_ari_response_error(), ast_ari_validate_void(), ast_log, ast_ari_bridges_start_moh_args::bridge_id, LOG_ERROR, ast_ari_response::message, ast_ari_bridges_start_moh_args::moh_class, ast_variable::name, ast_variable::next, NULL, ast_ari_response::response_code, and ast_variable::value.
 {
    struct ast_ari_bridges_start_moh_args args = {};
    struct ast_variable *i;
 #if defined(AST_DEVMODE)
    int is_valid;
    int code;
 #endif /* AST_DEVMODE */
    for (i = get_params; i; i = i->next) {
       if (strcmp(i->name, "mohClass") == 0) {
          args.moh_class = (i->value);
       } else
       {}
    }
    for (i = path_vars; i; i = i->next) {
       if (strcmp(i->name, "bridgeId") == 0) {
          args.bridge_id = (i->value);
       } else
       {}
    }
    if (ast_ari_bridges_start_moh_parse_body(body, &args)) {
       ast_ari_response_alloc_failed(response);
       goto fin;
    }
    ast_ari_bridges_start_moh(headers, &args, response);
 #if defined(AST_DEVMODE)
    code = response->response_code;
    switch (code) {
    case 0: /* Implementation is still a stub, or the code wasn't set */
       is_valid = response->message == NULL;
       break;
    case 500: /* Internal Server Error */
    case 501: /* Not Implemented */
    case 404: /* Bridge not found */
    case 409: /* Bridge not in Stasis application */
       is_valid = 1;
       break;
    default:
       if (200 <= code && code <= 299) {
          is_valid = ast_ari_validate_void(
             response->message);
       } else {
          ast_log(LOG_ERROR, "Invalid error response %d for /bridges/{bridgeId}/moh\n", code);
          is_valid = 0;
       }
    }
    if (!is_valid) {
       ast_log(LOG_ERROR, "Response validation failed for /bridges/{bridgeId}/moh\n");
       ast_ari_response_error(response, 500,
          "Internal Server Error", "Response validation failed");
    }
 #endif /* AST_DEVMODE */
 fin: __attribute__((unused))
    return;
 }
ast_ari_bridges_start_moh_parse_body()
int ast_ari_bridges_start_moh_parse_body (struct ast_json * body, struct ast_ari_bridges_start_moh_args * args)
Body parsing function for /bridges/{bridgeId}/moh.
Parameters
body The JSON body from which to parse parameters.
[out] args The args structure to parse into.
Return values
zero on success
non-zero on failure
Definition at line 847 of file res_ari_bridges.c.
References ast_json_object_get(), ast_json_string_get(), and ast_ari_bridges_start_moh_args::moh_class.
Referenced by ast_ari_bridges_start_moh_cb().
 {
    struct ast_json *field;
    /* Parse query parameters out of it */
    field = ast_json_object_get(body, "mohClass");
    if (field) {
       args->moh_class = ast_json_string_get(field);
    }
    return 0;
 }
ast_ari_bridges_stop_moh_cb()
static void ast_ari_bridges_stop_moh_cb (struct ast_tcptls_session_instance * ser, struct ast_variable * get_params, struct ast_variable * path_vars, struct ast_variable * headers, struct ast_json * body, struct ast_ari_response * response) static
Parameter parsing callback for /bridges/{bridgeId}/moh.
Parameters
get_params GET parameters in the HTTP request.
path_vars Path variables extracted from the request.
headers HTTP headers.
[out] response Response to the HTTP request.
Definition at line 936 of file res_ari_bridges.c.
References ast_ari_bridges_stop_moh(), ast_ari_response_error(), ast_ari_validate_void(), ast_log, ast_ari_bridges_stop_moh_args::bridge_id, LOG_ERROR, ast_ari_response::message, ast_variable::name, ast_variable::next, NULL, ast_ari_response::response_code, and ast_variable::value.
 {
    struct ast_ari_bridges_stop_moh_args args = {};
    struct ast_variable *i;
 #if defined(AST_DEVMODE)
    int is_valid;
    int code;
 #endif /* AST_DEVMODE */
    for (i = path_vars; i; i = i->next) {
       if (strcmp(i->name, "bridgeId") == 0) {
          args.bridge_id = (i->value);
       } else
       {}
    }
    ast_ari_bridges_stop_moh(headers, &args, response);
 #if defined(AST_DEVMODE)
    code = response->response_code;
    switch (code) {
    case 0: /* Implementation is still a stub, or the code wasn't set */
       is_valid = response->message == NULL;
       break;
    case 500: /* Internal Server Error */
    case 501: /* Not Implemented */
    case 404: /* Bridge not found */
    case 409: /* Bridge not in Stasis application */
       is_valid = 1;
       break;
    default:
       if (200 <= code && code <= 299) {
          is_valid = ast_ari_validate_void(
             response->message);
       } else {
          ast_log(LOG_ERROR, "Invalid error response %d for /bridges/{bridgeId}/moh\n", code);
          is_valid = 0;
       }
    }
    if (!is_valid) {
       ast_log(LOG_ERROR, "Response validation failed for /bridges/{bridgeId}/moh\n");
       ast_ari_response_error(response, 500,
          "Internal Server Error", "Response validation failed");
    }
 #endif /* AST_DEVMODE */
 fin: __attribute__((unused))
    return;
 }
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 1588 of file res_ari_bridges.c.
load_module()
static int load_module (void) static
Definition at line 1569 of file res_ari_bridges.c.
References ast_ari_add_handler(), AST_MODFLAG_DEFAULT, AST_MODULE_INFO(), AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, AST_MODULE_SUPPORT_CORE, ASTERISK_GPL_KEY, and unload_module().
 {
    int res = 0;
    res |= ast_ari_add_handler(&bridges);
    if (res) {
       unload_module();
       return AST_MODULE_LOAD_DECLINE;
    }
    return AST_MODULE_LOAD_SUCCESS;
 }
unload_module()
static int unload_module (void) static
Definition at line 1563 of file res_ari_bridges.c.
References ast_ari_remove_handler().
Referenced by load_module().
 {
    ast_ari_remove_handler(&bridges);
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_DEFAULT , .description = "RESTful API module - Bridge resources" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .requires = "res_ari,res_ari_model,res_stasis,res_stasis_recording,res_stasis_playback", } static
Definition at line 1588 of file res_ari_bridges.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 1588 of file res_ari_bridges.c.
bridges
struct stasis_rest_handlers bridges static
REST handler for /api-docs/bridges.json.
Definition at line 1553 of file res_ari_bridges.c.
bridges_bridgeId
struct stasis_rest_handlers bridges_bridgeId static
REST handler for /api-docs/bridges.json.
Definition at line 1541 of file res_ari_bridges.c.
bridges_bridgeId_addChannel
struct stasis_rest_handlers bridges_bridgeId_addChannel static
REST handler for /api-docs/bridges.json.
Definition at line 1466 of file res_ari_bridges.c.
bridges_bridgeId_moh
struct stasis_rest_handlers bridges_bridgeId_moh static
REST handler for /api-docs/bridges.json.
Definition at line 1503 of file res_ari_bridges.c.
bridges_bridgeId_play
struct stasis_rest_handlers bridges_bridgeId_play static
REST handler for /api-docs/bridges.json.
Definition at line 1523 of file res_ari_bridges.c.
bridges_bridgeId_play_playbackId
struct stasis_rest_handlers bridges_bridgeId_play_playbackId static
REST handler for /api-docs/bridges.json.
Definition at line 1513 of file res_ari_bridges.c.
bridges_bridgeId_record
struct stasis_rest_handlers bridges_bridgeId_record static
REST handler for /api-docs/bridges.json.
Definition at line 1532 of file res_ari_bridges.c.
bridges_bridgeId_removeChannel
struct stasis_rest_handlers bridges_bridgeId_removeChannel static
REST handler for /api-docs/bridges.json.
Definition at line 1475 of file res_ari_bridges.c.
bridges_bridgeId_videoSource
struct stasis_rest_handlers bridges_bridgeId_videoSource static
REST handler for /api-docs/bridges.json.
Definition at line 1494 of file res_ari_bridges.c.
bridges_bridgeId_videoSource_channelId
struct stasis_rest_handlers bridges_bridgeId_videoSource_channelId static
REST handler for /api-docs/bridges.json.
Definition at line 1484 of file res_ari_bridges.c.