Asterisk - The Open Source Telephony Project: bridge_native_dahdi.h File Reference
bridge_native_dahdi.h File Reference
Native DAHDI bridging support.
Functions
int dahdi_native_load (const struct ast_channel_tech *tech)
void dahdi_native_unload (void)
Detailed Description
Native DAHDI bridging support.
Author
Richard Mudgett rmudg.nosp@m.ett@.nosp@m.digiu.nosp@m.m.co.nosp@m.m
See Also:
CREDITS
Definition in file bridge_native_dahdi.h.
Function Documentation
dahdi_native_load()
int dahdi_native_load (const struct ast_channel_tech * tech)
Definition at line 904 of file bridge_native_dahdi.c.
References ast_bridge_technology_register, and dahdi_native_unload().
Referenced by load_module().
 {
    dahdi_tech = tech;
    if (ast_bridge_technology_register(&native_bridge)) {
       dahdi_native_unload();
       return -1;
    }
    return 0;
 }
dahdi_native_unload()
void dahdi_native_unload (void)
Definition at line 891 of file bridge_native_dahdi.c.
References ast_bridge_technology_unregister().
Referenced by __unload_module(), and dahdi_native_load().
 {
    ast_bridge_technology_unregister(&native_bridge);
 }