Asterisk - The Open Source Telephony Project: test_res_stasis.c File Reference
test_res_stasis.c File Reference
Test Stasis Application API.
Author
David M. Lee, II <dlee@digium.com>
.
#include "asterisk.h"
#include "asterisk/module.h"
#include "asterisk/test.h"
#include "asterisk/stasis_app.h"
Data Structures
struct app_data
Functions
static void __reg_module (void)
static void __unreg_module (void)
static struct app_data * app_data_create (void)
static void app_data_dtor (void *obj)
struct ast_module * AST_MODULE_SELF_SYM (void)
AST_TEST_DEFINE (app_invoke_dne)
AST_TEST_DEFINE (app_invoke_one)
AST_TEST_DEFINE (app_replaced)
static int load_module (void)
static void test_handler (void *data, const char *app_name, struct ast_json *message)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_DEFAULT , .description = "Stasis Core testing" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .requires = "res_stasis", }
static const struct ast_module_info * ast_module_info = &__mod_info
static const char * test_category = "/stasis/res/"
Detailed Description
Test Stasis Application API.
Author
David M. Lee, II <dlee@digium.com>
.
Definition in file test_res_stasis.c.
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 201 of file test_res_stasis.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 201 of file test_res_stasis.c.
app_data_create()
static struct app_data* app_data_create (void) static
Definition at line 75 of file test_res_stasis.c.
References ao2_alloc, app_data_dtor(), ast_json_array_create(), app_data::messages, and NULL.
Referenced by AST_TEST_DEFINE().
 {
    struct app_data *res = ao2_alloc(sizeof(struct app_data), app_data_dtor);
    if (!res) {
       return NULL;
    }
    res->messages = ast_json_array_create();
    return res;
 }
app_data_dtor()
static void app_data_dtor (void * obj) static
Definition at line 67 of file test_res_stasis.c.
References ast_json_unref(), app_data::messages, and NULL.
Referenced by app_data_create().
 {
    struct app_data *actual = obj;
    ast_json_unref(actual->messages);
    actual->messages = NULL;
 }
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 201 of file test_res_stasis.c.
AST_TEST_DEFINE() [1/3]
AST_TEST_DEFINE (app_invoke_dne)
Definition at line 41 of file test_res_stasis.c.
References ast_json_null(), AST_TEST_NOT_RUN, AST_TEST_PASS, sip_to_pjsip::info(), stasis_app_send(), test_category, TEST_EXECUTE, and TEST_INIT.
 {
    int res;
    switch (cmd) {
    case TEST_INIT:
       info->name = __func__;
       info->category = test_category;
       info->summary = "Test stasis app invocation.";
       info->description = "Test stasis app invocation.";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    res = stasis_app_send("i-am-not-an-app", ast_json_null());
    ast_test_validate(test, -1 == res);
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [2/3]
AST_TEST_DEFINE (app_invoke_one)
Definition at line 96 of file test_res_stasis.c.
References ao2_cleanup, app_data_create(), app_name(), ast_json_equal(), ast_json_null(), ast_json_pack(), ast_json_ref(), ast_json_unref(), AST_TEST_NOT_RUN, AST_TEST_PASS, sip_to_pjsip::info(), app_data::invocations, app_data::messages, NULL, RAII_VAR, stasis_app_register(), stasis_app_send(), stasis_app_unregister(), test_category, TEST_EXECUTE, test_handler(), and TEST_INIT.
 {
    RAII_VAR(struct app_data *, app_data, NULL, ao2_cleanup);
    RAII_VAR(char *, app_name, NULL, stasis_app_unregister);
    RAII_VAR(struct ast_json *, expected_message, NULL, ast_json_unref);
    RAII_VAR(struct ast_json *, message, NULL, ast_json_unref);
    int res;
    switch (cmd) {
    case TEST_INIT:
       info->name = __func__;
       info->category = test_category;
       info->summary = "Test stasis app invocation.";
       info->description = "Test stasis app invocation.";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    app_name = "test-handler";
    app_data = app_data_create();
    stasis_app_register(app_name, test_handler, app_data);
    message = ast_json_pack("{ s: o }", "test-message", ast_json_null());
    expected_message = ast_json_pack("[o]", ast_json_ref(message));
    res = stasis_app_send(app_name, message);
    ast_test_validate(test, 0 == res);
    ast_test_validate(test, 1 == app_data->invocations);
    ast_test_validate(test, ast_json_equal(expected_message, app_data->messages));
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [3/3]
AST_TEST_DEFINE (app_replaced)
Definition at line 131 of file test_res_stasis.c.
References ao2_cleanup, app_data_create(), app_name(), ast_eid_default, ast_eid_to_str(), ast_json_array_get(), ast_json_equal(), ast_json_null(), ast_json_object_del(), ast_json_object_get(), ast_json_pack(), ast_json_ref(), ast_json_unref(), AST_TEST_NOT_RUN, AST_TEST_PASS, sip_to_pjsip::info(), NULL, RAII_VAR, stasis_app_register(), stasis_app_send(), stasis_app_unregister(), test_category, TEST_EXECUTE, test_handler(), and TEST_INIT.
 {
    RAII_VAR(struct app_data *, app_data1, NULL, ao2_cleanup);
    RAII_VAR(struct app_data *, app_data2, NULL, ao2_cleanup);
    RAII_VAR(char *, app_name, NULL, stasis_app_unregister);
    RAII_VAR(struct ast_json *, expected_message1, NULL, ast_json_unref);
    RAII_VAR(struct ast_json *, message, NULL, ast_json_unref);
    RAII_VAR(struct ast_json *, expected_message2, NULL, ast_json_unref);
    char eid[20];
    int res;
    switch (cmd) {
    case TEST_INIT:
       info->name = __func__;
       info->category = test_category;
       info->summary = "Test stasis app invocation.";
       info->description = "Test stasis app invocation.";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    app_name = "test-handler";
    app_data1 = app_data_create();
    app_data2 = app_data_create();
    stasis_app_register(app_name, test_handler, app_data1);
    stasis_app_register(app_name, test_handler, app_data2);
    expected_message1 = ast_json_pack("[{s: s, s: s, s: s}]",
       "type", "ApplicationReplaced",
       "application", app_name,
       "asterisk_id", ast_eid_to_str(eid, sizeof(eid), &ast_eid_default));
    message = ast_json_pack("{ s: o }", "test-message", ast_json_null());
    expected_message2 = ast_json_pack("[o]", ast_json_ref(message));
    res = stasis_app_send(app_name, message);
    ast_test_validate(test, 0 == res);
    ast_test_validate(test, 1 == app_data1->invocations);
    ast_test_validate(test, ast_json_object_get(ast_json_array_get(app_data1->messages, 0), "timestamp")? 1: 0);
    ast_json_object_del(ast_json_array_get(app_data1->messages, 0), "timestamp");
    ast_test_validate(test, ast_json_equal(expected_message1, app_data1->messages));
    ast_test_validate(test, 1 == app_data2->invocations);
    ast_test_validate(test, ast_json_equal(expected_message2, app_data2->messages));
    return AST_TEST_PASS;
 }
load_module()
static int load_module (void) static
Definition at line 188 of file test_res_stasis.c.
References AST_MODFLAG_DEFAULT, AST_MODULE_INFO(), AST_MODULE_LOAD_SUCCESS, AST_MODULE_SUPPORT_CORE, AST_TEST_REGISTER, ASTERISK_GPL_KEY, and unload_module().
 {
    AST_TEST_REGISTER(app_replaced);
    AST_TEST_REGISTER(app_invoke_one);
    AST_TEST_REGISTER(app_invoke_dne);
    return AST_MODULE_LOAD_SUCCESS;
 }
test_handler()
static void test_handler (void * data, const char * app_name, struct ast_json * message) static
Definition at line 87 of file test_res_stasis.c.
References ast_assert, ast_json_array_append(), ast_json_copy(), app_data::invocations, and app_data::messages.
Referenced by AST_TEST_DEFINE().
 {
    struct app_data *actual = data;
    int res;
    ++(actual->invocations);
    res = ast_json_array_append(actual->messages, ast_json_copy(message));
    ast_assert(res == 0);
 }
unload_module()
static int unload_module (void) static
Definition at line 180 of file test_res_stasis.c.
References AST_TEST_UNREGISTER.
Referenced by load_module().
 {
    AST_TEST_UNREGISTER(app_invoke_dne);
    AST_TEST_UNREGISTER(app_invoke_one);
    AST_TEST_UNREGISTER(app_replaced);
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_DEFAULT , .description = "Stasis Core testing" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .requires = "res_stasis", } static
Definition at line 201 of file test_res_stasis.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 201 of file test_res_stasis.c.
test_category
const char* test_category = "/stasis/res/" static
Definition at line 39 of file test_res_stasis.c.
Referenced by AST_TEST_DEFINE().