Asterisk - The Open Source Telephony Project: max_forwards.c File Reference
max_forwards.c File Reference
#include "asterisk.h"
#include "asterisk/max_forwards.h"
#include "asterisk/channel.h"
Data Structures
struct max_forwards
Channel datastore data for max forwards.
Macros
#define DEFAULT_MAX_FORWARDS 20
Functions
int ast_max_forwards_decrement (struct ast_channel *chan)
Decrement the max forwards count for a particular channel.
int ast_max_forwards_get (struct ast_channel *chan)
Get the current max forwards for a particular channel.
int ast_max_forwards_reset (struct ast_channel *chan)
Reset the max forwards on a channel to its starting value.
int ast_max_forwards_set (struct ast_channel *chan, int starting_count)
Set the starting max forwards for a particular channel.
static struct max_forwards * max_forwards_alloc (int starting_count, int current_count)
static struct ast_datastore * max_forwards_datastore_alloc (struct ast_channel *chan, int starting_count)
static struct ast_datastore * max_forwards_datastore_find_or_alloc (struct ast_channel *chan)
static void max_forwards_destroy (void *data)
static void * max_forwards_duplicate (void *data)
Variables
const struct ast_datastore_info max_forwards_info
Macro Definition Documentation
DEFAULT_MAX_FORWARDS
#define DEFAULT_MAX_FORWARDS 20
Definition at line 24 of file max_forwards.c.
Referenced by max_forwards_datastore_find_or_alloc().
Function Documentation
ast_max_forwards_decrement()
int ast_max_forwards_decrement (struct ast_channel * chan)
Decrement the max forwards count for a particular channel.
If the channel has not had max forwards set on it, then the channel will have the default max forwards set on it and that value will not be decremented.
Precondition
chan is locked
The channel for which the max forwards value should be decremented
Return values
0 Success
-1 Failure
Definition at line 135 of file max_forwards.c.
References max_forwards::current_count, ast_datastore::data, and max_forwards_datastore_find_or_alloc().
Referenced by __ast_request_and_dial(), ast_ari_channels_dial(), begin_dial_prerun(), call_forward_inherit(), dial_exec_full(), do_forward(), findmeexec(), ring_entry(), and wait_for_answer().
 {
    struct ast_datastore *mf_datastore;
    struct max_forwards *mf;
    mf_datastore = max_forwards_datastore_find_or_alloc(chan);
    if (!mf_datastore) {
       return -1;
    }
    mf = mf_datastore->data;
    --mf->current_count;
    return 0;
 }
ast_max_forwards_get()
int ast_max_forwards_get (struct ast_channel * chan)
Get the current max forwards for a particular channel.
If the channel has not had max forwards set on it, then the channel will have the default max forwards set on it and that value will be returned.
Precondition
chan is locked
Parameters
chan The channel to get the max forwards for.
Returns
The current max forwards count on the channel
Definition at line 121 of file max_forwards.c.
References max_forwards::current_count, ast_datastore::data, and max_forwards_datastore_find_or_alloc().
Referenced by app_exec(), begin_dial_prerun(), dial_exec_full(), func_channel_read(), and queue_exec().
 {
    struct ast_datastore *mf_datastore;
    struct max_forwards *mf;
    mf_datastore = max_forwards_datastore_find_or_alloc(chan);
    if (!mf_datastore) {
       return -1;
    }
    mf = mf_datastore->data;
    return mf->current_count;
 }
ast_max_forwards_reset()
int ast_max_forwards_reset (struct ast_channel * chan)
Reset the max forwards on a channel to its starting value.
If the channel has not had max forwards set on it, then the channel will have the default max forwards set on it.
Precondition
chan is locked.
Parameters
chan The channel on which to reset the max forwards count.
Return values
0 Success
-1 Failure
Definition at line 151 of file max_forwards.c.
References max_forwards::current_count, ast_datastore::data, max_forwards_datastore_find_or_alloc(), and max_forwards::starting_count.
Referenced by pre_bridge_setup().
 {
    struct ast_datastore *mf_datastore;
    struct max_forwards *mf;
    mf_datastore = max_forwards_datastore_find_or_alloc(chan);
    if (!mf_datastore) {
       return -1;
    }
    mf = mf_datastore->data;
    mf->current_count = mf->starting_count;
    return 0;
 }
ast_max_forwards_set()
int ast_max_forwards_set (struct ast_channel * chan, int starting_count)
Set the starting max forwards for a particular channel.
Precondition
chan is locked
Parameters
starting_count The value to set the max forwards to.
chan The channel on which to set the max forwards.
Return values
0 Success
1 Failure
Definition at line 105 of file max_forwards.c.
References max_forwards::current_count, ast_datastore::data, max_forwards_datastore_find_or_alloc(), and max_forwards::starting_count.
Referenced by func_channel_write_real().
 {
    struct ast_datastore *mf_datastore;
    struct max_forwards *mf;
    mf_datastore = max_forwards_datastore_find_or_alloc(chan);
    if (!mf_datastore) {
       return -1;
    }
    mf = mf_datastore->data;
    mf->starting_count = mf->current_count = starting_count;
    return 0;
 }
max_forwards_alloc()
static struct max_forwards* max_forwards_alloc (int starting_count, int current_count) static
Definition at line 36 of file max_forwards.c.
References ast_malloc, max_forwards::current_count, NULL, and max_forwards::starting_count.
Referenced by max_forwards_datastore_alloc(), and max_forwards_duplicate().
 {
    struct max_forwards *mf;
    mf = ast_malloc(sizeof(*mf));
    if (!mf) {
       return NULL;
    }
    mf->starting_count = starting_count;
    mf->current_count = current_count;
    return mf;
 }
max_forwards_datastore_alloc()
static struct ast_datastore* max_forwards_datastore_alloc (struct ast_channel * chan, int starting_count) static
Definition at line 69 of file max_forwards.c.
References ast_channel_datastore_add(), ast_datastore_alloc, ast_datastore_free(), ast_datastore::data, DATASTORE_INHERIT_FOREVER, ast_datastore::inheritance, max_forwards_alloc(), and NULL.
Referenced by max_forwards_datastore_find_or_alloc().
 {
    struct ast_datastore *mf_datastore;
    struct max_forwards *mf;
    mf_datastore = ast_datastore_alloc(&max_forwards_info, NULL);
    if (!mf_datastore) {
       return NULL;
    }
    mf_datastore->inheritance = DATASTORE_INHERIT_FOREVER;
    mf = max_forwards_alloc(starting_count, starting_count);
    if (!mf) {
       ast_datastore_free(mf_datastore);
       return NULL;
    }
    mf_datastore->data = mf;
    ast_channel_datastore_add(chan, mf_datastore);
    return mf_datastore;
 }
max_forwards_datastore_find_or_alloc()
static struct ast_datastore* max_forwards_datastore_find_or_alloc (struct ast_channel * chan) static
Definition at line 93 of file max_forwards.c.
References ast_channel_datastore_find(), DEFAULT_MAX_FORWARDS, max_forwards_datastore_alloc(), and NULL.
Referenced by ast_max_forwards_decrement(), ast_max_forwards_get(), ast_max_forwards_reset(), and ast_max_forwards_set().
 {
    struct ast_datastore *mf_datastore;
    mf_datastore = ast_channel_datastore_find(chan, &max_forwards_info, NULL);
    if (!mf_datastore) {
       mf_datastore = max_forwards_datastore_alloc(chan, DEFAULT_MAX_FORWARDS);
    }
    return mf_datastore;
 }
max_forwards_destroy()
static void max_forwards_destroy (void * data) static
Definition at line 58 of file max_forwards.c.
References ast_free.
 {
    ast_free(data);
 }
max_forwards_duplicate()
static void* max_forwards_duplicate (void * data) static
Definition at line 51 of file max_forwards.c.
References max_forwards::current_count, max_forwards_alloc(), and max_forwards::starting_count.
 {
    struct max_forwards *mf = data;
    return max_forwards_alloc(mf->starting_count, mf->current_count);
 }
Variable Documentation
max_forwards_info
const struct ast_datastore_info max_forwards_info
Initial value:
= {
   .type = "mfaled-interface",
   .duplicate = max_forwards_duplicate,
   .destroy = max_forwards_destroy,
}
Definition at line 63 of file max_forwards.c.