Asterisk - The Open Source Telephony Project: swagger_model Namespace Reference
swagger_model Namespace Reference
Data Structures
class AllowableList
class AllowableRange
class Api
class ApiDeclaration
class ErrorResponse
class Model
class Operation
class Parameter
class ParsingContext
class Property
class ResourceApi
class ResourceListing
class Stringify
class SwaggerError
class SwaggerPostProcessor
class SwaggerType
Functions
def compare_versions (lhs, rhs)
def get_list_parameter_type (type_string)
def load_allowable_values (json, context)
def validate_required_fields (json, required_fields, context)
Variables
list SWAGGER_PRIMITIVES
list SWAGGER_VERSIONS = ["1.1", "1.2"]
Function Documentation
compare_versions()
def swagger_model.compare_versions (lhs, rhs)
Performs a lexicographical comparison between two version numbers.
This properly handles simple major.minor.whatever.sure.why.not version
numbers, but fails miserably if there's any letters in there.
For reference:
  1.0 == 1.0
  1.0 < 1.0.1
  1.2 < 1.10
@param lhs Left hand side of the comparison
@param rhs Right hand side of the comparison
@return  < 0 if lhs  < rhs
@return == 0 if lhs == rhs
@return  > 0 if lhs  > rhs
Definition at line 60 of file swagger_model.py.
Referenced by ParsingContext.version_less_than().
 def compare_versions(lhs, rhs):
     '''Performs a lexicographical comparison between two version numbers.
     This properly handles simple major.minor.whatever.sure.why.not version
     numbers, but fails miserably if there's any letters in there.
     For reference:
       1.0 == 1.0
       1.0 < 1.0.1
       1.2 < 1.10
     @param lhs Left hand side of the comparison
     @param rhs Right hand side of the comparison
     @return  < 0 if lhs  < rhs
     @return == 0 if lhs == rhs
     @return  > 0 if lhs  > rhs
     '''
     lhs = [int(v) for v in lhs.split('.')]
     rhs = [int(v) for v in rhs.split('.')]
     return (lhs > rhs) - (lhs < rhs)
get_list_parameter_type()
def swagger_model.get_list_parameter_type (type_string)
Returns the type parameter if the given type_string is List[].
@param type_string: Type string to parse
@returns Type parameter of the list, or None if not a List.
Definition at line 453 of file swagger_model.py.
Referenced by SwaggerType.load().
 def get_list_parameter_type(type_string):
     """Returns the type parameter if the given type_string is List[].
     @param type_string: Type string to parse
     @returns Type parameter of the list, or None if not a List.
     """
     list_match = re.match('^List\[(.*)\]$', type_string)
     return list_match and list_match.group(1)
load_allowable_values()
def swagger_model.load_allowable_values (json, context)
Parse a JSON allowableValues object.
This returns None, AllowableList or AllowableRange, depending on the
valueType in the JSON. If the valueType is not recognized, a SwaggerError
is raised.
Definition at line 240 of file swagger_model.py.
 def load_allowable_values(json, context):
     """Parse a JSON allowableValues object.
     This returns None, AllowableList or AllowableRange, depending on the
     valueType in the JSON. If the valueType is not recognized, a SwaggerError
     is raised.
     """
     if not json:
         return None
     if not 'valueType' in json:
         raise SwaggerError("Missing valueType field", context)
     value_type = json['valueType']
     if value_type == 'RANGE':
         if not 'min' in json and not 'max' in json:
             raise SwaggerError("Missing fields min/max", context)
         return AllowableRange(json.get('min'), json.get('max'))
     if value_type == 'LIST':
         if not 'values' in json:
             raise SwaggerError("Missing field values", context)
         return AllowableList(json['values'])
     raise SwaggerError("Unkown valueType %s" % value_type, context)
validate_required_fields()
def swagger_model.validate_required_fields (json, required_fields, context)
Checks a JSON object for a set of required fields.
If any required field is missing, a SwaggerError is raised.
@param json: JSON object to check.
@param required_fields: List of required fields.
@param context: Current context in the API.
Definition at line 752 of file swagger_model.py.
Referenced by Parameter.load(), ErrorResponse.load(), Operation.load(), Api.load(), Property.load(), Model.load(), ApiDeclaration.load(), ResourceApi.load(), and ResourceListing.load().
 def validate_required_fields(json, required_fields, context):
     """Checks a JSON object for a set of required fields.
     If any required field is missing, a SwaggerError is raised.
     @param json: JSON object to check.
     @param required_fields: List of required fields.
     @param context: Current context in the API.
     """
     missing_fields = [f for f in required_fields if not f in json]
     if missing_fields:
         raise SwaggerError(
             "Missing fields: %s" % ', '.join(missing_fields), context)
Variable Documentation
SWAGGER_PRIMITIVES
list SWAGGER_PRIMITIVES
Definition at line 40 of file swagger_model.py.
SWAGGER_VERSIONS
list SWAGGER_VERSIONS = ["1.1", "1.2"]
Definition at line 38 of file swagger_model.py.