Asterisk - The Open Source Telephony Project: phoneprov.h File Reference
phoneprov.h File Reference
#include "asterisk.h"
#include "asterisk/inline_api.h"
Macros
#define _ASTERISK_PHONEPROV_H
Typedefs
typedef int(* ast_phoneprov_load_users_cb) (void)
Causes the provider to load its users.
Enumerations
enum ast_phoneprov_std_variables {
AST_PHONEPROV_STD_MAC = 0, AST_PHONEPROV_STD_PROFILE, AST_PHONEPROV_STD_USERNAME, AST_PHONEPROV_STD_DISPLAY_NAME,
AST_PHONEPROV_STD_SECRET, AST_PHONEPROV_STD_LABEL, AST_PHONEPROV_STD_CALLERID, AST_PHONEPROV_STD_TIMEZONE,
AST_PHONEPROV_STD_LINENUMBER, AST_PHONEPROV_STD_LINEKEYS, AST_PHONEPROV_STD_SERVER, AST_PHONEPROV_STD_SERVER_PORT,
AST_PHONEPROV_STD_SERVER_IFACE, AST_PHONEPROV_STD_VOICEMAIL_EXTEN, AST_PHONEPROV_STD_EXTENSION_LENGTH, AST_PHONEPROV_STD_TZOFFSET,
AST_PHONEPROV_STD_DST_ENABLE, AST_PHONEPROV_STD_DST_START_MONTH, AST_PHONEPROV_STD_DST_START_MDAY, AST_PHONEPROV_STD_DST_START_HOUR,
AST_PHONEPROV_STD_DST_END_MONTH, AST_PHONEPROV_STD_DST_END_MDAY, AST_PHONEPROV_STD_DST_END_HOUR, AST_PHONEPROV_STD_VAR_LIST_LENGTH
}
Functions
int ast_phoneprov_add_extension (char *provider_name, struct varshead *vars)
Adds an extension.
void ast_phoneprov_delete_extension (char *provider_name, char *macaddress)
Deletes an extension.
void ast_phoneprov_delete_extensions (char *provider_name)
Deletes all extensions for this provider.
int ast_phoneprov_provider_register (char *provider_name, ast_phoneprov_load_users_cb load_users)
Registers a config provider to phoneprov.
void ast_phoneprov_provider_unregister (char *provider_name)
Unegisters a config provider from phoneprov and frees its resources.
const char * ast_phoneprov_std_variable_lookup (enum ast_phoneprov_std_variables var)
Returns the string respresentation of a phoneprov standard variable.
Macro Definition Documentation
_ASTERISK_PHONEPROV_H
#define _ASTERISK_PHONEPROV_H
Definition at line 24 of file phoneprov.h.
Typedef Documentation
ast_phoneprov_load_users_cb
typedef int(* ast_phoneprov_load_users_cb) (void)
Causes the provider to load its users.
This function is called by phoneprov in response to a ast_phoneprov_provider_register call by the provider. It may also be called by phoneprov to request a reload in response to the res_phoneprov module being reloaded.
Return values
0 if successful
non-zero if failure
Definition at line 75 of file phoneprov.h.
Enumeration Type Documentation
ast_phoneprov_std_variables
enum ast_phoneprov_std_variables
Enumerator
AST_PHONEPROV_STD_MAC
AST_PHONEPROV_STD_PROFILE
AST_PHONEPROV_STD_USERNAME
AST_PHONEPROV_STD_DISPLAY_NAME
AST_PHONEPROV_STD_SECRET
AST_PHONEPROV_STD_LABEL
AST_PHONEPROV_STD_CALLERID
AST_PHONEPROV_STD_TIMEZONE
AST_PHONEPROV_STD_LINENUMBER
AST_PHONEPROV_STD_LINEKEYS
AST_PHONEPROV_STD_SERVER
AST_PHONEPROV_STD_SERVER_PORT
AST_PHONEPROV_STD_SERVER_IFACE
AST_PHONEPROV_STD_VOICEMAIL_EXTEN
AST_PHONEPROV_STD_EXTENSION_LENGTH
AST_PHONEPROV_STD_TZOFFSET
AST_PHONEPROV_STD_DST_ENABLE
AST_PHONEPROV_STD_DST_START_MONTH
AST_PHONEPROV_STD_DST_START_MDAY
AST_PHONEPROV_STD_DST_START_HOUR
AST_PHONEPROV_STD_DST_END_MONTH
AST_PHONEPROV_STD_DST_END_MDAY
AST_PHONEPROV_STD_DST_END_HOUR
AST_PHONEPROV_STD_VAR_LIST_LENGTH
Definition at line 29 of file phoneprov.h.
{
    AST_PHONEPROV_STD_MAC = 0,
    AST_PHONEPROV_STD_PROFILE,
    AST_PHONEPROV_STD_USERNAME,
    AST_PHONEPROV_STD_DISPLAY_NAME,
    AST_PHONEPROV_STD_SECRET,
    AST_PHONEPROV_STD_LABEL,
    AST_PHONEPROV_STD_CALLERID,
    AST_PHONEPROV_STD_TIMEZONE,
    AST_PHONEPROV_STD_LINENUMBER,
    AST_PHONEPROV_STD_LINEKEYS,
    AST_PHONEPROV_STD_SERVER,
    AST_PHONEPROV_STD_SERVER_PORT,
    AST_PHONEPROV_STD_SERVER_IFACE,
    AST_PHONEPROV_STD_VOICEMAIL_EXTEN,
    AST_PHONEPROV_STD_EXTENSION_LENGTH,
    AST_PHONEPROV_STD_TZOFFSET,
    AST_PHONEPROV_STD_DST_ENABLE,
    AST_PHONEPROV_STD_DST_START_MONTH,
    AST_PHONEPROV_STD_DST_START_MDAY,
    AST_PHONEPROV_STD_DST_START_HOUR,
    AST_PHONEPROV_STD_DST_END_MONTH,
    AST_PHONEPROV_STD_DST_END_MDAY,
    AST_PHONEPROV_STD_DST_END_HOUR,
    AST_PHONEPROV_STD_VAR_LIST_LENGTH,  /* This entry must always be the last in the list */
 };
Function Documentation
ast_phoneprov_add_extension()
int ast_phoneprov_add_extension (char * provider_name, struct varshead * vars)
Adds an extension.
Parameters
provider_name The name of the provider
defaults An ast_vat_t linked list of the extension's variables. The list is automatically cloned and it must contain at least MACADDRESS and USERNAME entries.
Return values
0 if successful
non-zero if failure
Definition at line 1614 of file res_phoneprov.c.
Referenced by users_apply_handler().
 {
    RAII_VAR(struct phoneprov_provider *, provider, NULL, ao2_cleanup);
    RAII_VAR(struct user *, user, NULL, ao2_cleanup);
    RAII_VAR(struct phone_profile *, profile, NULL, ao2_cleanup);
    struct extension *exten;
    char *profile_name;
    char *mac;
    char *username;
    if (ast_strlen_zero(provider_name)) {
       ast_log(LOG_ERROR, "Provider name can't be empty.\n");
       return -1;
    }
    if (!vars) {
       ast_log(LOG_ERROR, "Variable list can't be empty.\n");
       return -1;
    }
    username = ast_var_find(vars, variable_lookup[AST_PHONEPROV_STD_USERNAME]);
    if (!username) {
       ast_log(LOG_ERROR, "Extension name can't be empty.\n");
       return -1;
    }
    mac = ast_var_find(vars, variable_lookup[AST_PHONEPROV_STD_MAC]);
    if (!mac) {
       ast_log(LOG_ERROR, "MAC Address can't be empty.\n");
       return -1;
    }
    provider = find_provider(provider_name);
    if (!provider) {
       ast_log(LOG_ERROR, "Provider '%s' wasn't found in the registry.\n", provider_name);
       return -1;
    }
    profile_name = ast_var_find(vars,
       variable_lookup[AST_PHONEPROV_STD_PROFILE]);
    if (!profile_name) {
       ast_log(LOG_ERROR, "No profile could be found for user '%s' - skipping.\n", username);
       return -1;
    }
    if (!(profile = find_profile(profile_name))) {
       ast_log(LOG_ERROR, "Could not look up profile '%s' - skipping.\n", profile_name);
       return -1;
    }
    if (!(user = find_user(mac))) {
       if (!(user = build_user(mac, profile, provider_name))) {
          ast_log(LOG_ERROR, "Could not create user for '%s' - skipping\n", mac);
          return -1;
       }
       if (!(exten = build_extension(username, vars))) {
          ast_log(LOG_ERROR, "Could not create extension for '%s' - skipping\n", user->macaddress);
          return -1;
       }
       if (add_user_extension(user, exten)) {
          ast_log(LOG_WARNING, "Could not add extension '%s' to user '%s'\n", exten->name, user->macaddress);
          exten = delete_extension(exten);
          return -1;
       }
       if (build_user_routes(user)) {
          ast_log(LOG_WARNING, "Could not create http routes for '%s' - skipping\n", user->macaddress);
          return -1;
       }
       ao2_link(users, user);
    } else {
       if (strcmp(provider_name, user->provider_name)) {
          ast_log(LOG_ERROR, "MAC address '%s' was already added by provider '%s' - skipping\n", user->macaddress, user->provider_name);
          return -1;
       }
       if (!(exten = build_extension(username, vars))) {
          ast_log(LOG_ERROR, "Could not create extension for '%s' - skipping\n", user->macaddress);
          return -1;
       }
       if (add_user_extension(user, exten)) {
          ast_log(LOG_WARNING, "Could not add extension '%s' to user '%s'\n", exten->name, user->macaddress);
ast_phoneprov_delete_extension()
void ast_phoneprov_delete_extension (char * provider_name, char * macaddress)
Deletes an extension.
Parameters
provider_name The name of the provider
macaddress The mac address of the extension
Definition at line 1585 of file res_phoneprov.c.
References CMP_MATCH.
Referenced by phoneprov_destroy().
{
       return CMP_MATCH;
    }
    return 0;
 }
 void ast_phoneprov_delete_extension(char *provider_name, char *macaddress)
 {
ast_phoneprov_delete_extensions()
void ast_phoneprov_delete_extensions (char * provider_name)
Deletes all extensions for this provider.
Parameters
provider_name The name of the provider
Definition at line 1595 of file res_phoneprov.c.
 {
ast_phoneprov_provider_register()
int ast_phoneprov_provider_register (char * provider_name, ast_phoneprov_load_users_cb load_users)
Registers a config provider to phoneprov.
Parameters
provider_name The name of the provider
load_users Callback that gathers user variables then loads them by calling ast_phoneprov_add_extension once for each extension.
Return values
0 if successful
non-zero if failure
Definition at line 1514 of file res_phoneprov.c.
References ao2_alloc, ao2_link, ao2_ref, ast_log, ast_string_field_init, ast_string_field_set, ast_strlen_zero, find_provider(), phoneprov_provider::load_users, LOG_ERROR, LOG_WARNING, NULL, provider, provider_destructor(), var, and variable_lookup.
Referenced by load_module(), and reload_module().
{
       return NULL;
    }
    return variable_lookup[var];
 }
 int ast_phoneprov_provider_register(char *provider_name,
    ast_phoneprov_load_users_cb load_users)
 {
    struct phoneprov_provider *provider;
    if (ast_strlen_zero(provider_name)) {
       ast_log(LOG_ERROR, "Provider name can't be empty.\n");
       return -1;
    }
    if (!providers) {
       ast_log(LOG_WARNING, "Provider '%s' cannot be registered: res_phoneprov not loaded.\n", provider_name);
       return -1;
    }
    provider = find_provider(provider_name);
    if (provider) {
       ast_log(LOG_ERROR, "There is already a provider registered named '%s'.\n", provider_name);
       ao2_ref(provider, -1);
       return -1;
    }
    provider = ao2_alloc(sizeof(struct phoneprov_provider), provider_destructor);
    if (!provider) {
       ast_log(LOG_ERROR, "Unable to allocate sufficient memory for provider '%s'.\n", provider_name);
       return -1;
    }
    if (ast_string_field_init(provider, 32)) {
       ao2_ref(provider, -1);
       ast_log(LOG_ERROR, "Unable to allocate sufficient memory for provider '%s' stringfields.\n", provider_name);
       return -1;
    }
    ast_string_field_set(provider, provider_name, provider_name);
    provider->load_users = load_users;
    ao2_link(providers, provider);
    ao2_ref(provider, -1);
    if (provider->load_users()) {
ast_phoneprov_provider_unregister()
void ast_phoneprov_provider_unregister (char * provider_name)
Unegisters a config provider from phoneprov and frees its resources.
Parameters
provider_name The name of the provider
Definition at line 1604 of file res_phoneprov.c.
References ao2_callback, extensions_delete_cb(), OBJ_MULTIPLE, OBJ_NODATA, and OBJ_UNLINK.
Referenced by reload_module(), and unload_module().
                {
       return;
    }
    ao2_callback(users, OBJ_UNLINK | OBJ_NODATA | OBJ_MULTIPLE, extensions_delete_cb, provider_name);
 }
 void ast_phoneprov_provider_unregister(char *provider_name)
 {
ast_phoneprov_std_variable_lookup()
const char* ast_phoneprov_std_variable_lookup (enum ast_phoneprov_std_variables var)
Returns the string respresentation of a phoneprov standard variable.
Parameters
var One of enum ast_phoneprov_std_variables
Returns
The string representation or NULL if not found.
Definition at line 1505 of file res_phoneprov.c.
Referenced by load_endpoint(), and users_apply_handler().
 {