Asterisk - The Open Source Telephony Project: rawplayer.c File Reference
rawplayer.c File Reference
#include <stdio.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <stdlib.h>
Macros
#define BUFLEN 320
Functions
static int deliver_file (char *path, int fdout)
int main (int argc, char *argv[])
Macro Definition Documentation
BUFLEN
#define BUFLEN 320
Definition at line 10 of file rawplayer.c.
Referenced by deliver_file().
Function Documentation
deliver_file()
static int deliver_file (char * path, int fdout) static
Definition at line 17 of file rawplayer.c.
References buf, BUFLEN, and error().
Referenced by main().
{
    int fd = 0, bytes = 0, error = 0;
    short buf[BUFLEN];
    if ((fd = open(path,O_RDONLY))) {
       while ((bytes=read(fd, buf, BUFLEN)) > 0) {
          if(write(fdout, buf, bytes) < 0){
             error = -2;
             break;
          }
       }
       if(fd)
          close(fd);
    } else
       return -1;
    return error;
 }
main()
int main (int argc, char * argv[])
Definition at line 37 of file rawplayer.c.
References deliver_file().
{
    int x = 0, fdout = 0;
    fdout = fileno(stdout);
    for (;;)
       for (x = 1; x < argc ; x++) {
          if(deliver_file(argv[x], fdout))
             exit(1);
       }
 }