Asterisk - The Open Source Telephony Project: app_verbose.c File Reference
app_verbose.c File Reference
Dial plan applications
Verbose logging application.
#include "asterisk.h"
#include "asterisk/module.h"
#include "asterisk/app.h"
#include "asterisk/channel.h"
#include "asterisk/logger.h"
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int load_module (void)
static int log_exec (struct ast_channel *chan, const char *data)
static int unload_module (void)
static int verbose_exec (struct ast_channel *chan, const char *data)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Send verbose output" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, }
static char * app_log = "Log"
static char * app_verbose = "Verbose"
static const struct ast_module_info * ast_module_info = &__mod_info
Detailed Description
Verbose logging application.
Author
Tilghman Lesher app_v.nosp@m.erbo.nosp@m.se_v0.nosp@m.01@t.nosp@m.he-ti.nosp@m.lghm.nosp@m.an.co.nosp@m.m
Definition in file app_verbose.c.
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 178 of file app_verbose.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 178 of file app_verbose.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 178 of file app_verbose.c.
load_module()
static int load_module (void) static
Definition at line 168 of file app_verbose.c.
References app_log, app_verbose, ast_register_application_xml, log_exec(), and verbose_exec().
 {
    int res;
    res = ast_register_application_xml(app_log, log_exec);
    res |= ast_register_application_xml(app_verbose, verbose_exec);
    return res;
 }
log_exec()
static int log_exec (struct ast_channel * chan, const char * data) static
Definition at line 111 of file app_verbose.c.
References __LOG_DEBUG, __LOG_DTMF, __LOG_ERROR, __LOG_NOTICE, __LOG_VERBOSE, __LOG_WARNING, args, AST_APP_ARG, ast_channel_context(), ast_channel_exten(), ast_channel_priority(), AST_DECLARE_APP_ARGS, ast_dynamic_logger_level(), ast_log, ast_log_dynamic_level, AST_MAX_EXTENSION, AST_STANDARD_APP_ARGS, ast_strdupa, ast_strlen_zero, context, LOG_ERROR, and parse().
Referenced by load_module().
 {
    char *parse;
    int lnum = -1;
    char extension[AST_MAX_EXTENSION + 5], context[AST_MAX_EXTENSION + 2];
    AST_DECLARE_APP_ARGS(args,
       AST_APP_ARG(level);
       AST_APP_ARG(msg);
    );
    if (ast_strlen_zero(data))
       return 0;
    parse = ast_strdupa(data);
    AST_STANDARD_APP_ARGS(args, parse);
    if (!strcasecmp(args.level, "ERROR")) {
       lnum = __LOG_ERROR;
    } else if (!strcasecmp(args.level, "WARNING")) {
       lnum = __LOG_WARNING;
    } else if (!strcasecmp(args.level, "NOTICE")) {
       lnum = __LOG_NOTICE;
    } else if (!strcasecmp(args.level, "DEBUG")) {
       lnum = __LOG_DEBUG;
    } else if (!strcasecmp(args.level, "VERBOSE")) {
       lnum = __LOG_VERBOSE;
    } else if (!strcasecmp(args.level, "DTMF")) {
       lnum = __LOG_DTMF;
    } else {
       int level = ast_dynamic_logger_level(args.level);
       if (level > -1) {
          ast_log_dynamic_level(level, "%s\n", args.msg);
       } else {
          ast_log(LOG_ERROR, "Unknown log level: '%s'\n", args.level);
       }
    }
    if (lnum > -1) {
       snprintf(context, sizeof(context), "@ %s", ast_channel_context(chan));
       snprintf(extension, sizeof(extension), "Ext. %s", ast_channel_exten(chan));
       ast_log(lnum, extension, ast_channel_priority(chan), context, "%s\n", args.msg);
    }
    return 0;
 }
unload_module()
static int unload_module (void) static
Definition at line 158 of file app_verbose.c.
References app_log, app_verbose, and ast_unregister_application().
 {
    int res;
    res = ast_unregister_application(app_verbose);
    res |= ast_unregister_application(app_log);
    return res;
 }
verbose_exec()
static int verbose_exec (struct ast_channel * chan, const char * data) static
Definition at line 79 of file app_verbose.c.
References args, AST_APP_ARG, AST_DECLARE_APP_ARGS, ast_log, AST_STANDARD_APP_ARGS, ast_strdupa, ast_strlen_zero, ast_verb, LOG_WARNING, and parse().
Referenced by load_module().
 {
    unsigned int vsize;
    char *parse;
    AST_DECLARE_APP_ARGS(args,
       AST_APP_ARG(level);
       AST_APP_ARG(msg);
    );
    if (ast_strlen_zero(data)) {
       return 0;
    }
    parse = ast_strdupa(data);
    AST_STANDARD_APP_ARGS(args, parse);
    if (args.argc == 1) {
       args.msg = args.level;
       args.level = "0";
    }
    if (sscanf(args.level, "%30u", &vsize) != 1) {
       vsize = 0;
       ast_log(LOG_WARNING, "'%s' is not a verboser number\n", args.level);
    } else if (4 < vsize) {
       vsize = 4;
    }
    ast_verb(vsize, "%s\n", args.msg);
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Send verbose output" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, } static
Definition at line 178 of file app_verbose.c.
app_log
char* app_log = "Log" static
Definition at line 39 of file app_verbose.c.
Referenced by load_module(), and unload_module().
app_verbose
char* app_verbose = "Verbose" static
Definition at line 38 of file app_verbose.c.
Referenced by load_module(), and unload_module().
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 178 of file app_verbose.c.