Asterisk - The Open Source Telephony Project: media_index.h File Reference
media_index.h File Reference
Media file format and description indexing engine.
Macros
#define ast_media_index_update(index, variant) ast_media_index_update_for_file(index, variant, NULL)
Update a media index.
Functions
const char * ast_media_get_description (struct ast_media_index *index, const char *filename, const char *variant)
Get the description for a media file.
struct ast_format_cap * ast_media_get_format_cap (struct ast_media_index *index, const char *filename, const char *variant)
Get the ast_format_cap for a media file.
struct ao2_container * ast_media_get_media (struct ast_media_index *index)
Get the a container of all media available on the system.
struct ao2_container * ast_media_get_variants (struct ast_media_index *index, const char *filename)
Get the languages in which a media file is available.
struct ast_media_index * ast_media_index_create (const char *base_dir)
Creates a new media index.
int ast_media_index_update_for_file (struct ast_media_index *index, const char *variant, const char *filename)
Update a media index for a specific sound file.
Detailed Description
Media file format and description indexing engine.
Definition in file media_index.h.
Macro Definition Documentation
ast_media_index_update
#define ast_media_index_update (index, variant) ast_media_index_update_for_file(index, variant, NULL)
Update a media index.
Parameters
index Media index in which to query information
variant Media variant for which to get the description
Return values
non-zero on error
Returns
zero on success
Definition at line 121 of file media_index.h.
Function Documentation
ast_media_get_description()
const char* ast_media_get_description (struct ast_media_index * index, const char * filename, const char * variant)
Get the description for a media file.
Parameters
index Media index in which to query information
filename Name of the file for which to get the description
variant Media variant for which to get the description
Return values
NULL if not found
Returns
The description requested (must be copied to be kept)
Definition at line 230 of file media_index.c.
References ao2_cleanup, ast_strlen_zero, find_variant(), NULL, RAII_VAR, and media_variant::variant.
Referenced by create_sound_blob(), and show_sound_info_cb().
 {
    RAII_VAR(struct media_variant *, variant, NULL, ao2_cleanup);
    if (ast_strlen_zero(filename) || ast_strlen_zero(variant_str)) {
       return NULL;
    }
    variant = find_variant(index, filename, variant_str);
    if (!variant) {
       return NULL;
    }
    return variant->description;
 }
ast_media_get_format_cap()
struct ast_format_cap* ast_media_get_format_cap (struct ast_media_index * index, const char * filename, const char * variant)
Get the ast_format_cap for a media file.
Parameters
index Media index in which to query information
filename Name of the file for which to get the description
variant Media variant for which to get the description
Return values
NULL if not found
Returns
a copy of the format capabilities (must be destroyed with ast_format_cap_destroy)
Definition at line 245 of file media_index.c.
References ao2_cleanup, ast_format_cap_alloc, ast_format_cap_append_from_cap(), AST_FORMAT_CAP_FLAG_DEFAULT, AST_MEDIA_TYPE_UNKNOWN, ast_strlen_zero, find_variant(), NULL, RAII_VAR, and media_variant::variant.
Referenced by add_format_information_cb(), and show_sound_info_cb().
 {
    struct ast_format_cap *dupcap;
    RAII_VAR(struct media_variant *, variant, NULL, ao2_cleanup);
    if (ast_strlen_zero(filename) || ast_strlen_zero(variant_str)) {
       return NULL;
    }
    variant = find_variant(index, filename, variant_str);
    if (!variant) {
       return NULL;
    }
    dupcap = ast_format_cap_alloc(AST_FORMAT_CAP_FLAG_DEFAULT);
    if (dupcap) {
       ast_format_cap_append_from_cap(dupcap, variant->formats, AST_MEDIA_TYPE_UNKNOWN);
    }
    return dupcap;
 }
ast_media_get_media()
struct ao2_container* ast_media_get_media (struct ast_media_index * index)
Get the a container of all media available on the system.
Parameters
index Media index in which to query information
Return values
NULL on error
Returns
an ast_str_container filled with media file name strings
Definition at line 307 of file media_index.c.
References add_media_cb(), ao2_callback, ao2_cleanup, ao2_ref, ast_str_container_alloc, ast_media_index::index, INDEX_BUCKETS, ast_media_index::media_list_cache, NULL, OBJ_NODATA, and RAII_VAR.
Referenced by ast_ari_sounds_list(), handle_cli_sound_show(), and handle_cli_sounds_show().
 {
    RAII_VAR(struct ao2_container *, media, NULL, ao2_cleanup);
    if (!index->media_list_cache) {
       media = ast_str_container_alloc(INDEX_BUCKETS);
       if (!media) {
          return NULL;
       }
       ao2_callback(index->index, OBJ_NODATA, add_media_cb, media);
       /* Ref to the cache */
       ao2_ref(media, +1);
       index->media_list_cache = media;
    }
    /* Ref to the caller */
    ao2_ref(index->media_list_cache, +1);
    return index->media_list_cache;
 }
ast_media_get_variants()
struct ao2_container* ast_media_get_variants (struct ast_media_index * index, const char * filename)
Get the languages in which a media file is available.
Parameters
index Media index in which to query information
filename Name of the file for which to get available languages
Return values
NULL on error
Returns
an ast_str_container filled with language strings
Definition at line 274 of file media_index.c.
References add_variant_cb(), ao2_callback, ao2_cleanup, ao2_find, ao2_ref, ast_str_container_alloc, ast_media_index::index, sip_to_pjsip::info(), NULL, OBJ_KEY, OBJ_NODATA, RAII_VAR, and VARIANT_BUCKETS.
Referenced by create_sound_blob(), and handle_cli_sound_show().
 {
    RAII_VAR(struct media_info *, info, NULL, ao2_cleanup);
    RAII_VAR(struct ao2_container *, variants, NULL, ao2_cleanup);
    if (!filename) {
       return NULL;
    }
    variants = ast_str_container_alloc(VARIANT_BUCKETS);
    if (!variants) {
       return NULL;
    }
    info = ao2_find(index->index, filename, OBJ_KEY);
    if (!info) {
       return NULL;
    }
    ao2_callback(info->variants, OBJ_NODATA, add_variant_cb, variants);
    ao2_ref(variants, +1);
    return variants;
 }
ast_media_index_create()
struct ast_media_index* ast_media_index_create (const char * base_dir)
Creates a new media index.
Parameters
base_dir Base directory for indexing
Return values
NULL on error
A new AO2 refcounted media index
Definition at line 162 of file media_index.c.
References ao2_alloc, AO2_ALLOC_OPT_LOCK_MUTEX, ao2_container_alloc_hash, ao2_ref, ast_media_index::base_dir, ast_media_index::index, INDEX_BUCKETS, media_index_dtor(), media_info_cmp(), media_info_hash(), and NULL.
Referenced by ast_sounds_get_index_for_file().
 {
    size_t base_dir_sz = strlen(base_dir) + 1;
    struct ast_media_index *index = ao2_alloc(sizeof(*index) + base_dir_sz, media_index_dtor);
    if (!index) {
       return NULL;
    }
    memcpy(index->base_dir, base_dir, base_dir_sz);
    index->index = ao2_container_alloc_hash(AO2_ALLOC_OPT_LOCK_MUTEX, 0, INDEX_BUCKETS,
       media_info_hash, NULL, media_info_cmp);
    if (!index->index) {
       ao2_ref(index, -1);
       return NULL;
    }
    return index;
 }
ast_media_index_update_for_file()
int ast_media_index_update_for_file (struct ast_media_index * index, const char * variant, const char * filename)
Update a media index for a specific sound file.
Since
13.25.0
16.2.0
Parameters
index Media index in which to query information
variant Media variant for which to get the description
filename Sound file name without extension
Note
If filename is NULL, this function will act as ast_media_index_update and add all sound files to the index.
Return values
non-zero on error
Returns
zero on success
Definition at line 587 of file media_index.c.
References ast_alloca, ast_debug, ast_file_read_dirs(), ast_strlen_zero, ast_tvdiff_us(), ast_media_index::base_dir, read_dirs_data::dirname_len, read_dirs_data::index, NULL, read_dirs_cb(), S_OR, read_dirs_data::search_filename, and read_dirs_data::search_variant.
Referenced by update_index_cb().
 {
    struct timeval start;
    struct timeval end;
    int64_t elapsed;
    int rc;
    size_t dirname_len = strlen(index->base_dir) + strlen(S_OR(variant, "")) + 1;
    struct read_dirs_data data = {
       .search_filename = S_OR(filename, ""),
       .search_filename_len = strlen(S_OR(filename, "")),
       .search_variant = S_OR(variant, ""),
       .index = index,
       .dirname_len = dirname_len,
    };
    char *search_dir = ast_alloca(dirname_len + 1);
    sprintf(search_dir, "%s%s%s", index->base_dir, ast_strlen_zero(variant) ? "" : "/",
       data.search_variant);
    gettimeofday(&start, NULL);
    rc = ast_file_read_dirs(search_dir, read_dirs_cb, &data, -1);
    gettimeofday(&end, NULL);
    elapsed = ast_tvdiff_us(end, start);
    ast_debug(1, "Media for language '%s' indexed in %8.6f seconds\n", data.search_variant, elapsed / 1E6);
    return rc;
 }