Asterisk - The Open Source Telephony Project: res_clioriginate.c File Reference
res_clioriginate.c File Reference
Originate calls via the CLI.
#include "asterisk.h"
#include "asterisk/channel.h"
#include "asterisk/pbx.h"
#include "asterisk/module.h"
#include "asterisk/cli.h"
#include "asterisk/utils.h"
#include "asterisk/frame.h"
#include "asterisk/format_cache.h"
Macros
#define TIMEOUT 30
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static char * handle_orig (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
handle for orgination app or exten.
static char * handle_redirect (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static int load_module (void)
static char * orig_app (int fd, const char *chan, const char *app, const char *appdata)
orginate a call from the CLI
static char * orig_exten (int fd, const char *chan, const char *data)
orginate from extension
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Call origination and redirection from the CLI" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, }
static const struct ast_module_info * ast_module_info = &__mod_info
static struct ast_cli_entry cli_cliorig []
Detailed Description
Originate calls via the CLI.
Author
Russell Bryant russe.nosp@m.ll@d.nosp@m.igium.nosp@m..com
Definition in file res_clioriginate.c.
Macro Definition Documentation
TIMEOUT
#define TIMEOUT 30
The timeout for originated calls, in seconds
Definition at line 42 of file res_clioriginate.c.
Referenced by orig_app(), and orig_exten().
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 249 of file res_clioriginate.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 249 of file res_clioriginate.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 249 of file res_clioriginate.c.
handle_orig()
static char* handle_orig (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) static
handle for orgination app or exten.
Parameters
e pointer to the CLI structure to initialize
cmd operation to execute
a structure that contains either application or extension arguments
Return values
CLI_SUCCESS on success.
CLI_SHOWUSAGE on failure.
Definition at line 136 of file res_clioriginate.c.
References ast_cli_args::argv, ast_cli_complete(), ast_complete_applications(), ast_strlen_zero, CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, ast_cli_entry::command, ast_cli_args::fd, ast_cli_args::line, ast_cli_args::n, NULL, orig_app(), orig_exten(), ast_cli_args::pos, ast_cli_entry::usage, and ast_cli_args::word.
 {
    static const char * const choices[] = { "application", "extension", NULL };
    char *res = NULL;
    switch (cmd) {
    case CLI_INIT:
       e->command = "channel originate";
       e->usage =
          "  There are two ways to use this command. A call can be originated between a\n"
          "channel and a specific application, or between a channel and an extension in\n"
          "the dialplan. This is similar to call files or the manager originate action.\n"
          "Calls originated with this command are given a timeout of 30 seconds.\n\n"
          "Usage1: channel originate <tech/data> application <appname> [appdata]\n"
          "  This will originate a call between the specified channel tech/data and the\n"
          "given application. Arguments to the application are optional. If the given\n"
          "arguments to the application include spaces, all of the arguments to the\n"
          "application need to be placed in quotation marks.\n\n"
          "Usage2: channel originate <tech/data> extension [exten@][context]\n"
          "  This will originate a call between the specified channel tech/data and the\n"
          "given extension. If no context is specified, the 'default' context will be\n"
          "used. If no extension is given, the 's' extension will be used.\n";
       return NULL;
    case CLI_GENERATE:
       if (a->pos == 3) {
          res = ast_cli_complete(a->word, choices, a->n);
       } else if (a->pos == 4) {
          if (!strcasecmp("application", a->argv[3])) {
             res = ast_complete_applications(a->line, a->word, a->n);
          }
       }
       return res;
    }
    if (ast_strlen_zero(a->argv[2]) || ast_strlen_zero(a->argv[3]))
       return CLI_SHOWUSAGE;
    if (!strcasecmp("application", a->argv[3])) {
       res = orig_app(a->fd, a->argv[2], a->argv[4], a->argv[5]);
    } else if (!strcasecmp("extension", a->argv[3])) {
       res = orig_exten(a->fd, a->argv[2], a->argv[4]);
    } else {
       res = CLI_SHOWUSAGE;
    }
    return res;
 }
handle_redirect()
static char* handle_redirect (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) static
Todo:
It would be nice to be able to redirect 2 channels at the same time like you can with AMI redirect. However, it is not possible to acquire two channels without the potential for a deadlock with how ast_channel structs are managed today. Once ast_channel is a refcounted object, this command will be able to support that.
Definition at line 185 of file res_clioriginate.c.
References ast_cli_args::argc, ast_cli_entry::args, ast_cli_args::argv, ast_async_parseable_goto(), ast_channel_get_by_name(), ast_channel_unref, ast_cli(), ast_complete_channels(), CLI_FAILURE, CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::command, ast_cli_args::fd, ast_cli_args::line, ast_cli_args::n, name, NULL, ast_cli_args::pos, ast_cli_entry::usage, and ast_cli_args::word.
 {
    const char *name, *dest;
    struct ast_channel *chan;
    int res;
    switch (cmd) {
    case CLI_INIT:
       e->command = "channel redirect";
       e->usage = ""
       "Usage: channel redirect <channel> <[[context,]exten,]priority>\n"
       "    Redirect an active channel to a specified extension.\n";
       /*! \todo It would be nice to be able to redirect 2 channels at the same
        *  time like you can with AMI redirect.  However, it is not possible to acquire
        *  two channels without the potential for a deadlock with how ast_channel structs
        *  are managed today.  Once ast_channel is a refcounted object, this command
        *  will be able to support that. */
       return NULL;
    case CLI_GENERATE:
       return ast_complete_channels(a->line, a->word, a->pos, a->n, 2);
    }
    if (a->argc != e->args + 2) {
       return CLI_SHOWUSAGE;
    }
    name = a->argv[2];
    dest = a->argv[3];
    if (!(chan = ast_channel_get_by_name(name))) {
       ast_cli(a->fd, "Channel '%s' not found\n", name);
       return CLI_FAILURE;
    }
    res = ast_async_parseable_goto(chan, dest);
    chan = ast_channel_unref(chan);
    if (!res) {
       ast_cli(a->fd, "Channel '%s' successfully redirected to %s\n", name, dest);
    } else {
       ast_cli(a->fd, "Channel '%s' failed to be redirected to %s\n", name, dest);
    }
    return res ? CLI_FAILURE : CLI_SUCCESS;
 }
load_module()
static int load_module (void) static
Definition at line 242 of file res_clioriginate.c.
References ARRAY_LEN, ast_cli_register_multiple, AST_MODULE_LOAD_DECLINE, and AST_MODULE_LOAD_SUCCESS.
 {
    int res;
    res = ast_cli_register_multiple(cli_cliorig, ARRAY_LEN(cli_cliorig));
    return res ? AST_MODULE_LOAD_DECLINE : AST_MODULE_LOAD_SUCCESS;
 }
orig_app()
static char* orig_app (int fd, const char * chan, const char * app, const char * appdata) static
orginate a call from the CLI
Parameters
fd file descriptor for cli
chan channel to create type/data
app application you want to run
appdata data for application
Return values
CLI_SUCCESS on success.
CLI_SHOWUSAGE on failure.
Definition at line 53 of file res_clioriginate.c.
References ao2_ref, ast_cli(), ast_format_cap_alloc, ast_format_cap_append, AST_FORMAT_CAP_FLAG_DEFAULT, ast_format_slin, AST_OUTGOING_NO_WAIT, ast_pbx_outgoing_app(), ast_strdupa, ast_strlen_zero, CLI_FAILURE, CLI_SHOWUSAGE, CLI_SUCCESS, NULL, strsep(), and TIMEOUT.
Referenced by handle_orig().
 {
    char *chantech;
    char *chandata;
    int reason = 0;
    struct ast_format_cap *cap;
    if (ast_strlen_zero(app))
       return CLI_SHOWUSAGE;
    chandata = ast_strdupa(chan);
    chantech = strsep(&chandata, "/");
    if (!chandata) {
       ast_cli(fd, "*** No data provided after channel type! ***\n");
       return CLI_SHOWUSAGE;
    }
    if (!(cap = ast_format_cap_alloc(AST_FORMAT_CAP_FLAG_DEFAULT))) {
       return CLI_FAILURE;
    }
    ast_format_cap_append(cap, ast_format_slin, 0);
    ast_pbx_outgoing_app(chantech, cap, chandata, TIMEOUT * 1000, app, appdata,
          &reason, AST_OUTGOING_NO_WAIT, NULL, NULL, NULL, NULL,
          NULL, NULL);
    ao2_ref(cap, -1);
    return CLI_SUCCESS;
 }
orig_exten()
static char* orig_exten (int fd, const char * chan, const char * data) static
orginate from extension
Parameters
fd file descriptor for cli
chan channel to create type/data
data contains exten@context
Return values
CLI_SUCCESS on success.
CLI_SHOWUSAGE on failure.
Definition at line 91 of file res_clioriginate.c.
References ao2_ref, ast_cli(), ast_format_cap_alloc, ast_format_cap_append, AST_FORMAT_CAP_FLAG_DEFAULT, ast_format_slin, AST_OUTGOING_NO_WAIT, ast_pbx_outgoing_exten(), ast_strdupa, ast_strlen_zero, CLI_FAILURE, CLI_SHOWUSAGE, CLI_SUCCESS, context, exten, NULL, strsep(), and TIMEOUT.
Referenced by gosub_exec(), and handle_orig().
 {
    char *chantech;
    char *chandata;
    char *exten = NULL;
    char *context = NULL;
    int reason = 0;
    struct ast_format_cap *cap;
    chandata = ast_strdupa(chan);
    chantech = strsep(&chandata, "/");
    if (!chandata) {
       ast_cli(fd, "*** No data provided after channel type! ***\n");
       return CLI_SHOWUSAGE;
    }
    if (!ast_strlen_zero(data)) {
       context = ast_strdupa(data);
       exten = strsep(&context, "@");
    }
    if (ast_strlen_zero(exten))
       exten = "s";
    if (ast_strlen_zero(context))
       context = "default";
    if (!(cap = ast_format_cap_alloc(AST_FORMAT_CAP_FLAG_DEFAULT))) {
       return CLI_FAILURE;
    }
    ast_format_cap_append(cap, ast_format_slin, 0);
    ast_pbx_outgoing_exten(chantech, cap, chandata, TIMEOUT * 1000, context,
          exten, 1, &reason, AST_OUTGOING_NO_WAIT, NULL, NULL,
          NULL, NULL, NULL, 0, NULL);
    ao2_ref(cap, -1);
    return CLI_SUCCESS;
 }
unload_module()
static int unload_module (void) static
Definition at line 237 of file res_clioriginate.c.
References ARRAY_LEN, and ast_cli_unregister_multiple().
 {
    return ast_cli_unregister_multiple(cli_cliorig, ARRAY_LEN(cli_cliorig));
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Call origination and redirection from the CLI" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, } static
Definition at line 249 of file res_clioriginate.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 249 of file res_clioriginate.c.
cli_cliorig
struct ast_cli_entry cli_cliorig[] static
Initial value:
= {
   { .handler =  handle_orig , .summary =  "Originate a call" ,},
   { .handler =  handle_redirect , .summary =  "Redirect a call" ,},
}
Definition at line 232 of file res_clioriginate.c.