Asterisk - The Open Source Telephony Project: stasis_system.h File Reference
stasis_system.h File Reference
#include "asterisk/stasis.h"
Functions
struct stasis_message_type * ast_cc_available_type (void)
A stasis_message_type for CCSS Available messages.
struct stasis_message_type * ast_cc_callerrecalling_type (void)
A stasis_message_type for CCSS Caller Recalling messages.
struct stasis_message_type * ast_cc_callerstartmonitoring_type (void)
A stasis_message_type for CCSS Caller Start Monitoring messages.
struct stasis_message_type * ast_cc_callerstopmonitoring_type (void)
A stasis_message_type for CCSS Caller Stop Monitoring messages.
struct stasis_message_type * ast_cc_failure_type (void)
A stasis_message_type for CCSS Failure messages.
struct stasis_message_type * ast_cc_monitorfailed_type (void)
A stasis_message_type for CCSS Monitor Failed messages.
struct stasis_message_type * ast_cc_offertimerstart_type (void)
A stasis_message_type for CCSS Offer Timer Start messages.
struct stasis_message_type * ast_cc_recallcomplete_type (void)
A stasis_message_type for CCSS Recall Complete messages.
struct stasis_message_type * ast_cc_requestacknowledged_type (void)
A stasis_message_type for CCSS Request Acknowledged messages.
struct stasis_message_type * ast_cc_requested_type (void)
A stasis_message_type for CCSS Requested messages.
struct stasis_message_type * ast_cluster_discovery_type (void)
A stasis_message_type for Cluster discovery.
struct stasis_message_type * ast_network_change_type (void)
A stasis_message_type for network changes.
int ast_stasis_system_init (void)
Initialize the stasis system topic and message types.
void ast_system_publish_registry (const char *channeltype, const char *username, const char *domain, const char *status, const char *cause)
Publish a channel driver outgoing registration message.
struct stasis_message_type * ast_system_registry_type (void)
A stasis_message_type for outbound registration.
struct stasis_topic * ast_system_topic (void)
A Stasis Message Bus API topic which publishes messages regarding system changes.
Function Documentation
ast_cc_available_type()
struct stasis_message_type* ast_cc_available_type (void)
A stasis_message_type for CCSS Available messages.
Since
12
Referenced by ast_stasis_system_init(), cc_publish_available(), and stasis_system_cleanup().
ast_cc_callerrecalling_type()
struct stasis_message_type* ast_cc_callerrecalling_type (void)
A stasis_message_type for CCSS Caller Recalling messages.
Since
12
Referenced by ast_stasis_system_init(), cc_publish_callerrecalling(), and stasis_system_cleanup().
ast_cc_callerstartmonitoring_type()
struct stasis_message_type* ast_cc_callerstartmonitoring_type (void)
A stasis_message_type for CCSS Caller Start Monitoring messages.
Since
12
Referenced by ast_stasis_system_init(), cc_publish_callerstartmonitoring(), and stasis_system_cleanup().
ast_cc_callerstopmonitoring_type()
struct stasis_message_type* ast_cc_callerstopmonitoring_type (void)
A stasis_message_type for CCSS Caller Stop Monitoring messages.
Since
12
Referenced by ast_stasis_system_init(), cc_publish_callerstopmonitoring(), and stasis_system_cleanup().
ast_cc_failure_type()
struct stasis_message_type* ast_cc_failure_type (void)
A stasis_message_type for CCSS Failure messages.
Since
12
Referenced by ast_stasis_system_init(), cc_publish_failure(), and stasis_system_cleanup().
ast_cc_monitorfailed_type()
struct stasis_message_type* ast_cc_monitorfailed_type (void)
A stasis_message_type for CCSS Monitor Failed messages.
Since
12
Referenced by ast_stasis_system_init(), cc_publish_monitorfailed(), and stasis_system_cleanup().
ast_cc_offertimerstart_type()
struct stasis_message_type* ast_cc_offertimerstart_type (void)
A stasis_message_type for CCSS Offer Timer Start messages.
Since
12
Referenced by ast_stasis_system_init(), cc_publish_offertimerstart(), and stasis_system_cleanup().
ast_cc_recallcomplete_type()
struct stasis_message_type* ast_cc_recallcomplete_type (void)
A stasis_message_type for CCSS Recall Complete messages.
Since
12
Referenced by ast_stasis_system_init(), cc_publish_recallcomplete(), and stasis_system_cleanup().
ast_cc_requestacknowledged_type()
struct stasis_message_type* ast_cc_requestacknowledged_type (void)
A stasis_message_type for CCSS Request Acknowledged messages.
Since
12
Referenced by ast_stasis_system_init(), cc_publish_requestacknowledged(), and stasis_system_cleanup().
ast_cc_requested_type()
struct stasis_message_type* ast_cc_requested_type (void)
A stasis_message_type for CCSS Requested messages.
Since
12
Referenced by ast_stasis_system_init(), cc_publish_requested(), and stasis_system_cleanup().
ast_cluster_discovery_type()
struct stasis_message_type* ast_cluster_discovery_type (void)
A stasis_message_type for Cluster discovery.
Since
13.11.0
Referenced by ast_stasis_system_init(), publish_cluster_discovery_to_stasis_full(), and stasis_system_cleanup().
ast_network_change_type()
struct stasis_message_type* ast_network_change_type (void)
A stasis_message_type for network changes.
Since
12
Return values
NULL on error
Referenced by ast_stasis_system_init(), load_module(), network_change_stasis_cb(), network_change_stasis_subscribe(), stasis_system_cleanup(), and stun_monitor_request().
ast_stasis_system_init()
int ast_stasis_system_init (void)
Initialize the stasis system topic and message types.
Return values
0 on success
-1 on failure
Initialize the stasis system topic and message types.
Definition at line 373 of file stasis_system.c.
References ast_cc_available_type(), ast_cc_callerrecalling_type(), ast_cc_callerstartmonitoring_type(), ast_cc_callerstopmonitoring_type(), ast_cc_failure_type(), ast_cc_monitorfailed_type(), ast_cc_offertimerstart_type(), ast_cc_recallcomplete_type(), ast_cc_requestacknowledged_type(), ast_cc_requested_type(), ast_cluster_discovery_type(), ast_network_change_type(), ast_register_cleanup(), ast_system_registry_type(), STASIS_MESSAGE_TYPE_INIT, stasis_system_cleanup(), and stasis_topic_create().
Referenced by asterisk_daemon().
 {
    ast_register_cleanup(stasis_system_cleanup);
    system_topic = stasis_topic_create("system:all");
    if (!system_topic) {
       return 1;
    }
    if (STASIS_MESSAGE_TYPE_INIT(ast_network_change_type) != 0) {
       return -1;
    }
    if (STASIS_MESSAGE_TYPE_INIT(ast_system_registry_type) != 0) {
       return -1;
    }
    if (STASIS_MESSAGE_TYPE_INIT(ast_cc_available_type) != 0) {
       return -1;
    }
    if (STASIS_MESSAGE_TYPE_INIT(ast_cc_offertimerstart_type) != 0) {
       return -1;
    }
    if (STASIS_MESSAGE_TYPE_INIT(ast_cc_requested_type) != 0) {
       return -1;
    }
    if (STASIS_MESSAGE_TYPE_INIT(ast_cc_requestacknowledged_type) != 0) {
       return -1;
    }
    if (STASIS_MESSAGE_TYPE_INIT(ast_cc_callerstopmonitoring_type) != 0) {
       return -1;
    }
    if (STASIS_MESSAGE_TYPE_INIT(ast_cc_callerstartmonitoring_type) != 0) {
       return -1;
    }
    if (STASIS_MESSAGE_TYPE_INIT(ast_cc_callerrecalling_type) != 0) {
       return -1;
    }
    if (STASIS_MESSAGE_TYPE_INIT(ast_cc_recallcomplete_type) != 0) {
       return -1;
    }
    if (STASIS_MESSAGE_TYPE_INIT(ast_cc_failure_type) != 0) {
       return -1;
    }
    if (STASIS_MESSAGE_TYPE_INIT(ast_cc_monitorfailed_type) != 0) {
       return -1;
    }
    if (STASIS_MESSAGE_TYPE_INIT(ast_cluster_discovery_type) != 0) {
       return -1;
    }
    return 0;
 }
ast_system_publish_registry()
void ast_system_publish_registry (const char * channeltype, const char * username, const char * domain, const char * status, const char * cause)
Publish a channel driver outgoing registration message.
Since
12
Parameters
channeltype The channel driver that published the message
username The username that was used to register
domain The domain that was used to register
status The result of the registration
cause The reason for the result
Definition at line 118 of file stasis_system.c.
References ao2_ref, ast_json_pack(), ast_json_payload_create(), ast_json_unref(), ast_system_registry_type(), ast_system_topic(), S_OR, stasis_message_create(), and stasis_publish().
Referenced by handle_registration_response(), iax2_publish_registry(), and sip_publish_registry().
 {
    struct ast_json *registry;
    struct ast_json_payload *payload;
    struct stasis_message *message;
    if (!ast_system_registry_type()) {
       return;
    }
    registry = ast_json_pack("{s: s, s: s, s: s, s: s, s: s, s: s}",
       "type", "registry",
       "channeltype", channeltype,
       "username", username,
       "domain", domain,
       "status", status,
       "cause", S_OR(cause, ""));
    payload = ast_json_payload_create(registry);
    ast_json_unref(registry);
    if (!payload) {
       return;
    }
    message = stasis_message_create(ast_system_registry_type(), payload);
    ao2_ref(payload, -1);
    if (!message) {
       return;
    }
    stasis_publish(ast_system_topic(), message);
    ao2_ref(message, -1);
 }
ast_system_registry_type()
struct stasis_message_type* ast_system_registry_type (void)
A stasis_message_type for outbound registration.
Since
12
Referenced by ast_stasis_system_init(), ast_system_publish_registry(), pjsip_outbound_registration_metrics_init(), and stasis_system_cleanup().
ast_system_topic()
struct stasis_topic* ast_system_topic (void)
A Stasis Message Bus API topic which publishes messages regarding system changes.
Since
12
Return values
Definition at line 347 of file stasis_system.c.
References system_topic.
Referenced by ast_system_publish_registry(), cc_publish(), load_module(), manager_system_init(), network_change_stasis_subscribe(), pjsip_outbound_registration_metrics_init(), publish_cluster_discovery_to_stasis_full(), publish_format_update(), and stun_monitor_request().
 {
    return system_topic;
 }