Asterisk - The Open Source Telephony Project: stasis_channels.c File Reference
stasis_channels.c File Reference
Stasis Messages and Data Types for Channel Objects.
#include "asterisk.h"
#include "asterisk/astobj2.h"
#include "asterisk/json.h"
#include "asterisk/pbx.h"
#include "asterisk/bridge.h"
#include "asterisk/translate.h"
#include "asterisk/stasis.h"
#include "asterisk/stasis_channels.h"
#include "asterisk/dial.h"
#include "asterisk/linkedlists.h"
Data Structures
struct ast_multi_channel_blob
A multi channel blob data structure for multi_channel_blob stasis messages.
struct channel_role_snapshot
A channel snapshot wrapper object used in ast_multi_channel_blob objects.
struct dial_masquerade_datastore
struct dial_target
Macros
#define NUM_MULTI_CHANNEL_BLOB_BUCKETS 7
Functions
static struct ast_manager_event_blob * agent_login_to_ami (struct stasis_message *msg)
static struct ast_manager_event_blob * agent_logoff_to_ami (struct stasis_message *msg)
struct stasis_message * ast_channel_blob_create (struct ast_channel *chan, struct stasis_message_type *type, struct ast_json *blob)
Creates a ast_channel_blob message.
struct stasis_message * ast_channel_blob_create_from_cache (const char *channel_id, struct stasis_message_type *type, struct ast_json *blob)
Create a ast_channel_blob message, pulling channel state from the cache.
struct ao2_container * ast_channel_cache_all (void)
struct ao2_container * ast_channel_cache_by_name (void)
Secondary channel cache, indexed by name.
void ast_channel_publish_blob (struct ast_channel *chan, struct stasis_message_type *type, struct ast_json *blob)
Publish a channel blob message.
void ast_channel_publish_cached_blob (struct ast_channel *chan, struct stasis_message_type *type, struct ast_json *blob)
Publish a channel blob message using the latest snapshot from the cache.
void ast_channel_publish_dial (struct ast_channel *caller, struct ast_channel *peer, const char *dialstring, const char *dialstatus)
Publish in the ast_channel_topic or ast_channel_topic_all topics a stasis message for the channels involved in a dial operation.
void ast_channel_publish_dial_forward (struct ast_channel *caller, struct ast_channel *peer, struct ast_channel *forwarded, const char *dialstring, const char *dialstatus, const char *forward)
Publish in the ast_channel_topic or ast_channel_topic_all topics a stasis message for the channels involved in a dial operation that is forwarded.
static void ast_channel_publish_dial_internal (struct ast_channel *caller, struct ast_channel *peer, struct ast_channel *forwarded, const char *dialstring, const char *dialstatus, const char *forward)
void ast_channel_publish_final_snapshot (struct ast_channel *chan)
Send the final channel snapshot for a channel, thus removing it from cache.
void ast_channel_publish_snapshot (struct ast_channel *chan)
Publish a ast_channel_snapshot for a channel.
void ast_channel_publish_varset (struct ast_channel *chan, const char *name, const char *value)
Publish a ast_channel_varset for a channel.
int ast_channel_snapshot_caller_id_equal (const struct ast_channel_snapshot *old_snapshot, const struct ast_channel_snapshot *new_snapshot)
Compares the callerid info of two snapshots.
int ast_channel_snapshot_cep_equal (const struct ast_channel_snapshot *old_snapshot, const struct ast_channel_snapshot *new_snapshot)
Compares the context, exten and priority of two snapshots.
int ast_channel_snapshot_connected_line_equal (const struct ast_channel_snapshot *old_snapshot, const struct ast_channel_snapshot *new_snapshot)
Compares the connected line info of two snapshots.
struct ast_channel_snapshot * ast_channel_snapshot_create (struct ast_channel *chan)
Generate a snapshot of the channel state. This is an ao2 object, so ao2_cleanup() to deallocate.
struct ast_channel_snapshot * ast_channel_snapshot_get_latest (const char *uniqueid)
Obtain the latest ast_channel_snapshot from the Stasis Message Bus API cache. This is an ao2 object, so use ao2_cleanup() to deallocate.
struct ast_channel_snapshot * ast_channel_snapshot_get_latest_by_name (const char *name)
Obtain the latest ast_channel_snapshot from the Stasis Message Bus API cache. This is an ao2 object, so use ao2_cleanup() to deallocate.
void ast_channel_snapshot_invalidate_segment (struct ast_channel *chan, enum ast_channel_snapshot_segment_invalidation segment)
Invalidate a channel snapshot segment from being reused.
struct ast_json * ast_channel_snapshot_to_json (const struct ast_channel_snapshot *snapshot, const struct stasis_message_sanitizer *sanitize)
Build a JSON object from a ast_channel_snapshot.
void ast_channel_stage_snapshot (struct ast_channel *chan)
Set flag to indicate channel snapshot is being staged.
void ast_channel_stage_snapshot_done (struct ast_channel *chan)
Clear flag to indicate channel snapshot is being staged, and publish snapshot.
struct stasis_topic * ast_channel_topic_all (void)
A topic which publishes the events for all channels.
void ast_multi_channel_blob_add_channel (struct ast_multi_channel_blob *obj, const char *role, struct ast_channel_snapshot *snapshot)
Add a ast_channel_snapshot to a ast_multi_channel_blob object.
struct ast_multi_channel_blob * ast_multi_channel_blob_create (struct ast_json *blob)
Create a ast_multi_channel_blob suitable for a stasis_message.
struct ast_channel_snapshot * ast_multi_channel_blob_get_channel (struct ast_multi_channel_blob *obj, const char *role)
Retrieve a channel snapshot associated with a specific role from a ast_multi_channel_blob.
struct ao2_container * ast_multi_channel_blob_get_channels (struct ast_multi_channel_blob *obj, const char *role)
Retrieve all channel snapshots associated with a specific role from a ast_multi_channel_blob.
struct ast_json * ast_multi_channel_blob_get_json (struct ast_multi_channel_blob *obj)
Retrieve the JSON blob from a ast_multi_channel_blob. Returned ast_json is still owned by obj.
int ast_stasis_channels_init (void)
Initialize the stasis channel topic and message types.
static void channel_blob_dtor (void *obj)
static struct ast_json * channel_blob_to_json (struct stasis_message *message, const char *type, const struct stasis_message_sanitizer *sanitize)
static int channel_role_cmp_cb (void *obj, void *arg, int flags)
static int channel_role_hash_cb (const void *obj, const int flags)
static void channel_role_snapshot_dtor (void *obj)
static struct ast_channel_snapshot_base * channel_snapshot_base_create (struct ast_channel *chan)
static void channel_snapshot_base_dtor (void *obj)
static struct ast_channel_snapshot_bridge * channel_snapshot_bridge_create (struct ast_channel *chan)
static struct ast_channel_snapshot_caller * channel_snapshot_caller_create (struct ast_channel *chan)
static void channel_snapshot_caller_dtor (void *obj)
static int channel_snapshot_cmp_cb (void *obj, void *arg, int flags)
static struct ast_channel_snapshot_connected * channel_snapshot_connected_create (struct ast_channel *chan)
static struct ast_channel_snapshot_dialplan * channel_snapshot_dialplan_create (struct ast_channel *chan)
static void channel_snapshot_dialplan_dtor (void *obj)
static void channel_snapshot_dtor (void *obj)
static struct ast_channel_snapshot_hangup * channel_snapshot_hangup_create (struct ast_channel *chan)
static int channel_snapshot_hash_cb (const void *obj, const int flags)
static struct ast_channel_snapshot_peer * channel_snapshot_peer_create (struct ast_channel *chan)
static int channel_snapshot_uniqueid_cmp_cb (void *obj, void *arg, int flags)
static int channel_snapshot_uniqueid_hash_cb (const void *obj, const int flags)
static struct ast_channel_snapshot_update * channel_snapshot_update_create (struct ast_channel *chan)
static void channel_snapshot_update_dtor (void *obj)
static struct stasis_message * create_channel_blob_message (struct ast_channel_snapshot *snapshot, struct stasis_message_type *type, struct ast_json *blob)
static void dial_masquerade_breakdown (void *data, struct ast_channel *old_chan, struct ast_channel *new_chan)
static void dial_masquerade_caller_datastore_destroy (void *data)
static struct dial_masquerade_datastore * dial_masquerade_datastore_add (struct ast_channel *chan, struct dial_masquerade_datastore *masq_data)
static struct dial_masquerade_datastore * dial_masquerade_datastore_alloc (void)
static void dial_masquerade_datastore_cleanup (struct dial_masquerade_datastore *masq_data)
static void dial_masquerade_datastore_destroy (void *data)
static void dial_masquerade_datastore_dtor (void *vdoomed)
static struct ast_datastore * dial_masquerade_datastore_find (struct ast_channel *chan)
static void dial_masquerade_datastore_remove_chan (struct dial_masquerade_datastore *masq_data, struct ast_channel *chan)
static void dial_masquerade_fixup (void *data, struct ast_channel *old_chan, struct ast_channel *new_chan)
static void dial_target_free (struct dial_target *doomed)
static struct ast_json * dial_to_json (struct stasis_message *message, const struct stasis_message_sanitizer *sanitize)
static struct ast_json * dtmf_end_to_json (struct stasis_message *message, const struct stasis_message_sanitizer *sanitize)
static struct ast_json * hangup_request_to_json (struct stasis_message *message, const struct stasis_message_sanitizer *sanitize)
static struct ast_json * hold_to_json (struct stasis_message *message, const struct stasis_message_sanitizer *sanitize)
static void multi_channel_blob_dtor (void *obj)
static void publish_message_for_channel_topics (struct stasis_message *message, struct ast_channel *chan)
static void remove_dial_masquerade (struct ast_channel *peer)
static void remove_dial_masquerade_caller (struct ast_channel *caller)
static int set_dial_masquerade (struct ast_channel *caller, struct ast_channel *peer, const char *dialstring)
static void stasis_channels_cleanup (void)
static struct ast_manager_event_blob * talking_start_to_ami (struct stasis_message *msg)
static struct ast_json * talking_start_to_json (struct stasis_message *message, const struct stasis_message_sanitizer *sanitize)
static struct ast_manager_event_blob * talking_stop_to_ami (struct stasis_message *msg)
static struct ast_json * talking_stop_to_json (struct stasis_message *message, const struct stasis_message_sanitizer *sanitize)
static struct ast_json * unhold_to_json (struct stasis_message *message, const struct stasis_message_sanitizer *sanitize)
static struct ast_manager_event_blob * varset_to_ami (struct stasis_message *msg)
static struct ast_json * varset_to_json (struct stasis_message *message, const struct stasis_message_sanitizer *sanitize)
STASIS_MESSAGE_TYPE_DEFN (ast_channel_snapshot_type)
Define channel message types.
STASIS_MESSAGE_TYPE_DEFN (ast_channel_dial_type,.to_json=dial_to_json,)
STASIS_MESSAGE_TYPE_DEFN (ast_channel_varset_type,.to_ami=varset_to_ami,.to_json=varset_to_json,)
STASIS_MESSAGE_TYPE_DEFN (ast_channel_hangup_request_type,.to_json=hangup_request_to_json,)
STASIS_MESSAGE_TYPE_DEFN (ast_channel_masquerade_type)
STASIS_MESSAGE_TYPE_DEFN (ast_channel_dtmf_begin_type)
STASIS_MESSAGE_TYPE_DEFN (ast_channel_dtmf_end_type,.to_json=dtmf_end_to_json,)
STASIS_MESSAGE_TYPE_DEFN (ast_channel_hold_type,.to_json=hold_to_json,)
STASIS_MESSAGE_TYPE_DEFN (ast_channel_unhold_type,.to_json=unhold_to_json,)
STASIS_MESSAGE_TYPE_DEFN (ast_channel_flash_type)
STASIS_MESSAGE_TYPE_DEFN (ast_channel_chanspy_start_type)
STASIS_MESSAGE_TYPE_DEFN (ast_channel_chanspy_stop_type)
STASIS_MESSAGE_TYPE_DEFN (ast_channel_fax_type)
STASIS_MESSAGE_TYPE_DEFN (ast_channel_hangup_handler_type)
STASIS_MESSAGE_TYPE_DEFN (ast_channel_moh_start_type)
STASIS_MESSAGE_TYPE_DEFN (ast_channel_moh_stop_type)
STASIS_MESSAGE_TYPE_DEFN (ast_channel_monitor_start_type)
STASIS_MESSAGE_TYPE_DEFN (ast_channel_monitor_stop_type)
STASIS_MESSAGE_TYPE_DEFN (ast_channel_mixmonitor_start_type)
STASIS_MESSAGE_TYPE_DEFN (ast_channel_mixmonitor_stop_type)
STASIS_MESSAGE_TYPE_DEFN (ast_channel_mixmonitor_mute_type)
STASIS_MESSAGE_TYPE_DEFN (ast_channel_agent_login_type,.to_ami=agent_login_to_ami,)
STASIS_MESSAGE_TYPE_DEFN (ast_channel_agent_logoff_type,.to_ami=agent_logoff_to_ami,)
STASIS_MESSAGE_TYPE_DEFN (ast_channel_talking_start,.to_ami=talking_start_to_ami,.to_json=talking_start_to_json,)
STASIS_MESSAGE_TYPE_DEFN (ast_channel_talking_stop,.to_ami=talking_stop_to_ami,.to_json=talking_stop_to_json,)
Variables
static struct ao2_container * channel_cache
static struct ao2_container * channel_cache_by_name
static struct stasis_topic * channel_topic_all
static const struct ast_datastore_info dial_masquerade_caller_info
static const struct ast_datastore_info dial_masquerade_info
Detailed Description
Stasis Messages and Data Types for Channel Objects.
Author
Matt Jordan <mjordan@digium.com>
Definition in file stasis_channels.c.
Macro Definition Documentation
NUM_MULTI_CHANNEL_BLOB_BUCKETS
#define NUM_MULTI_CHANNEL_BLOB_BUCKETS 7
Definition at line 117 of file stasis_channels.c.
Referenced by ast_multi_channel_blob_create(), and ast_multi_channel_blob_get_channels().
Function Documentation
agent_login_to_ami()
static struct ast_manager_event_blob* agent_login_to_ami (struct stasis_message * msg) static
Definition at line 1213 of file stasis_channels.c.
References ast_free, ast_json_object_get(), ast_json_string_get(), ast_manager_build_channel_state_string(), ast_manager_event_blob_create(), ast_str_buffer(), ast_channel_blob::blob, EVENT_FLAG_AGENT, NULL, ast_channel_blob::snapshot, and stasis_message_data().
Referenced by unhold_to_json().
 {
    struct ast_str *channel_string;
    struct ast_channel_blob *obj = stasis_message_data(msg);
    const char *agent = ast_json_string_get(ast_json_object_get(obj->blob, "agent"));
    struct ast_manager_event_blob *ev;
    channel_string = ast_manager_build_channel_state_string(obj->snapshot);
    if (!channel_string) {
       return NULL;
    }
    ev = ast_manager_event_blob_create(EVENT_FLAG_AGENT, "AgentLogin",
       "%s"
       "Agent: %s\r\n",
       ast_str_buffer(channel_string), agent);
    ast_free(channel_string);
    return ev;
 }
agent_logoff_to_ami()
static struct ast_manager_event_blob* agent_logoff_to_ami (struct stasis_message * msg) static
Definition at line 1233 of file stasis_channels.c.
References ast_free, ast_json_integer_get(), ast_json_object_get(), ast_json_string_get(), ast_manager_build_channel_state_string(), ast_manager_event_blob_create(), ast_str_buffer(), ast_channel_blob::blob, EVENT_FLAG_AGENT, NULL, ast_channel_blob::snapshot, and stasis_message_data().
Referenced by unhold_to_json().
 {
    struct ast_str *channel_string;
    struct ast_channel_blob *obj = stasis_message_data(msg);
    const char *agent = ast_json_string_get(ast_json_object_get(obj->blob, "agent"));
    long logintime = ast_json_integer_get(ast_json_object_get(obj->blob, "logintime"));
    struct ast_manager_event_blob *ev;
    channel_string = ast_manager_build_channel_state_string(obj->snapshot);
    if (!channel_string) {
       return NULL;
    }
    ev = ast_manager_event_blob_create(EVENT_FLAG_AGENT, "AgentLogoff",
       "%s"
       "Agent: %s\r\n"
       "Logintime: %ld\r\n",
       ast_str_buffer(channel_string), agent, logintime);
    ast_free(channel_string);
    return ev;
 }
ast_channel_publish_dial_internal()
static void ast_channel_publish_dial_internal (struct ast_channel * caller, struct ast_channel * peer, struct ast_channel * forwarded, const char * dialstring, const char * dialstatus, const char * forward) static
Definition at line 602 of file stasis_channels.c.
References ao2_ref, ast_assert, ast_channel_dial_type(), ast_channel_lock, ast_channel_snapshot_create(), ast_channel_snapshot_get_latest(), ast_channel_uniqueid(), ast_channel_unlock, ast_json_pack(), ast_json_unref(), ast_multi_channel_blob_add_channel(), ast_multi_channel_blob_create(), ast_strlen_zero, ast_channel_snapshot::caller, NULL, ast_channel_snapshot::peer, publish_message_for_channel_topics(), remove_dial_masquerade(), remove_dial_masquerade_caller(), S_OR, set_dial_masquerade(), and stasis_message_create().
Referenced by ast_channel_publish_dial_forward(), dial_masquerade_breakdown(), and dial_masquerade_fixup().
 {
    struct ast_multi_channel_blob *payload;
    struct stasis_message *msg;
    struct ast_json *blob;
    struct ast_channel_snapshot *peer_snapshot;
    if (!ast_channel_dial_type()) {
       return;
    }
    ast_assert(peer != NULL);
    blob = ast_json_pack("{s: s, s: s, s: s}",
       "dialstatus", S_OR(dialstatus, ""),
       "forward", S_OR(forward, ""),
       "dialstring", S_OR(dialstring, ""));
    if (!blob) {
       return;
    }
    payload = ast_multi_channel_blob_create(blob);
    ast_json_unref(blob);
    if (!payload) {
       return;
    }
    if (caller) {
       struct ast_channel_snapshot *caller_snapshot;
       ast_channel_lock(caller);
       if (ast_strlen_zero(dialstatus)) {
          caller_snapshot = ast_channel_snapshot_get_latest(ast_channel_uniqueid(caller));
       } else {
          caller_snapshot = ast_channel_snapshot_create(caller);
       }
       ast_channel_unlock(caller);
       if (!caller_snapshot) {
          ao2_ref(payload, -1);
          return;
       }
       ast_multi_channel_blob_add_channel(payload, "caller", caller_snapshot);
       ao2_ref(caller_snapshot, -1);
    }
    ast_channel_lock(peer);
    if (ast_strlen_zero(dialstatus)) {
       peer_snapshot = ast_channel_snapshot_get_latest(ast_channel_uniqueid(peer));
    } else {
       peer_snapshot = ast_channel_snapshot_create(peer);
    }
    ast_channel_unlock(peer);
    if (!peer_snapshot) {
       ao2_ref(payload, -1);
       return;
    }
    ast_multi_channel_blob_add_channel(payload, "peer", peer_snapshot);
    ao2_ref(peer_snapshot, -1);
    if (forwarded) {
       struct ast_channel_snapshot *forwarded_snapshot;
       ast_channel_lock(forwarded);
       forwarded_snapshot = ast_channel_snapshot_create(forwarded);
       ast_channel_unlock(forwarded);
       if (!forwarded_snapshot) {
          ao2_ref(payload, -1);
          return;
       }
       ast_multi_channel_blob_add_channel(payload, "forwarded", forwarded_snapshot);
       ao2_ref(forwarded_snapshot, -1);
    }
    msg = stasis_message_create(ast_channel_dial_type(), payload);
    ao2_ref(payload, -1);
    if (msg) {
       publish_message_for_channel_topics(msg, caller ?: peer);
       ao2_ref(msg, -1);
    }
 }
ast_channel_snapshot_caller_id_equal()
int ast_channel_snapshot_caller_id_equal (const struct ast_channel_snapshot * old_snapshot, const struct ast_channel_snapshot * new_snapshot)
Compares the callerid info of two snapshots.
Since
12
Parameters
old_snapshot Old snapshot
new_snapshot New snapshot
Returns
True (non-zero) if callerid are identical.
False (zero) if callerid changed.
Definition at line 1318 of file stasis_channels.c.
References ast_assert, ast_channel_snapshot::caller, ast_channel_snapshot_caller::name, NULL, and ast_channel_snapshot_caller::number.
Referenced by channel_callerid(), and channel_new_callerid().
 {
    ast_assert(old_snapshot != NULL);
    ast_assert(new_snapshot != NULL);
    return strcmp(old_snapshot->caller->number, new_snapshot->caller->number) == 0 &&
       strcmp(old_snapshot->caller->name, new_snapshot->caller->name) == 0;
 }
ast_channel_snapshot_cep_equal()
int ast_channel_snapshot_cep_equal (const struct ast_channel_snapshot * old_snapshot, const struct ast_channel_snapshot * new_snapshot)
Compares the context, exten and priority of two snapshots.
Since
12
Parameters
old_snapshot Old snapshot
new_snapshot New snapshot
Returns
True (non-zero) if context, exten or priority are identical.
False (zero) if context, exten and priority changed.
Definition at line 1297 of file stasis_channels.c.
References ast_channel_snapshot_dialplan::appl, ast_assert, ast_strlen_zero, ast_channel_snapshot_dialplan::context, ast_channel_snapshot::dialplan, ast_channel_snapshot_dialplan::exten, NULL, and ast_channel_snapshot_dialplan::priority.
Referenced by channel_dialplan(), and channel_newexten().
 {
    ast_assert(old_snapshot != NULL);
    ast_assert(new_snapshot != NULL);
    /* We actually get some snapshots with CEP set, but before the
     * application is set. Since empty application is invalid, we treat
     * setting the application from nothing as a CEP change.
     */
    if (ast_strlen_zero(old_snapshot->dialplan->appl) &&
        !ast_strlen_zero(new_snapshot->dialplan->appl)) {
       return 0;
    }
    return old_snapshot->dialplan->priority == new_snapshot->dialplan->priority &&
       strcmp(old_snapshot->dialplan->context, new_snapshot->dialplan->context) == 0 &&
       strcmp(old_snapshot->dialplan->exten, new_snapshot->dialplan->exten) == 0;
 }
ast_channel_snapshot_connected_line_equal()
int ast_channel_snapshot_connected_line_equal (const struct ast_channel_snapshot * old_snapshot, const struct ast_channel_snapshot * new_snapshot)
Compares the connected line info of two snapshots.
Since
13.1.0
Parameters
old_snapshot Old snapshot
new_snapshot New snapshot
Returns
True (non-zero) if callerid are identical.
False (zero) if callerid changed.
Definition at line 1328 of file stasis_channels.c.
References ast_assert, ast_channel_snapshot::connected, ast_channel_snapshot_connected::name, NULL, and ast_channel_snapshot_connected::number.
Referenced by channel_connected_line(), and channel_new_connected_line().
 {
    ast_assert(old_snapshot != NULL);
    ast_assert(new_snapshot != NULL);
    return strcmp(old_snapshot->connected->number, new_snapshot->connected->number) == 0 &&
       strcmp(old_snapshot->connected->name, new_snapshot->connected->name) == 0;
 }
ast_channel_snapshot_to_json()
struct ast_json* ast_channel_snapshot_to_json (const struct ast_channel_snapshot * snapshot, const struct stasis_message_sanitizer * sanitize)
Build a JSON object from a ast_channel_snapshot.
Parameters
snapshot The snapshot to convert to JSON
sanitize The message sanitizer to use on the snapshot
Returns
JSON object representing channel snapshot.
NULL on error
Definition at line 1255 of file stasis_channels.c.
References ast_channel_snapshot_base::accountcode, ast_channel_snapshot_dialplan::appl, ast_channel_snapshot::ari_vars, ast_json_channel_vars(), ast_json_dialplan_cep_app(), ast_json_name_number(), ast_json_object_set(), ast_json_pack(), ast_json_timeval(), AST_LIST_EMPTY, ast_state2str(), ast_channel_snapshot::base, ast_channel_snapshot::caller, stasis_message_sanitizer::channel_snapshot, ast_channel_snapshot::connected, ast_channel_snapshot_dialplan::context, ast_channel_snapshot_base::creationtime, ast_channel_snapshot_dialplan::data, ast_channel_snapshot::dialplan, ast_channel_snapshot_dialplan::exten, ast_channel_snapshot_base::language, ast_channel_snapshot_caller::name, ast_channel_snapshot_connected::name, ast_channel_snapshot_base::name, NULL, ast_channel_snapshot_caller::number, ast_channel_snapshot_connected::number, ast_channel_snapshot_dialplan::priority, ast_channel_snapshot::state, and ast_channel_snapshot_base::uniqueid.
Referenced by ari_channels_handle_originate_with_id(), ari_channels_handle_snoop_channel(), ast_ari_channels_create(), ast_ari_channels_get(), ast_ari_channels_list(), AST_TEST_DEFINE(), attended_transfer_to_json(), blind_transfer_to_json(), channel_blob_to_json(), channel_callerid(), channel_connected_line(), channel_destroyed_event(), channel_dialplan(), channel_to_json(), dial_to_json(), dtmf_end_to_json(), hold_to_json(), multi_user_event_to_json(), rtcp_report_to_json(), simple_bridge_channel_event(), simple_channel_event(), stasis_app_exec(), stasis_end_to_json(), stasis_start_to_json(), and unhold_to_json().
 {
    struct ast_json *json_chan;
    if (snapshot == NULL
       || (sanitize
          && sanitize->channel_snapshot
          && sanitize->channel_snapshot(snapshot))) {
       return NULL;
    }
    json_chan = ast_json_pack(
       /* Broken up into groups of three for readability */
       "{ s: s, s: s, s: s,"
       "  s: o, s: o, s: s,"
       "  s: o, s: o, s: s }",
       /* First line */
       "id", snapshot->base->uniqueid,
       "name", snapshot->base->name,
       "state", ast_state2str(snapshot->state),
       /* Second line */
       "caller", ast_json_name_number(
          snapshot->caller->name, snapshot->caller->number),
       "connected", ast_json_name_number(
          snapshot->connected->name, snapshot->connected->number),
       "accountcode", snapshot->base->accountcode,
       /* Third line */
       "dialplan", ast_json_dialplan_cep_app(
          snapshot->dialplan->context, snapshot->dialplan->exten, snapshot->dialplan->priority,
          snapshot->dialplan->appl, snapshot->dialplan->data),
       "creationtime", ast_json_timeval(snapshot->base->creationtime, NULL),
       "language", snapshot->base->language);
    if (snapshot->ari_vars && !AST_LIST_EMPTY(snapshot->ari_vars)) {
       ast_json_object_set(json_chan, "channelvars", ast_json_channel_vars(snapshot->ari_vars));
    }
    return json_chan;
 }
ast_stasis_channels_init()
int ast_stasis_channels_init (void)
Initialize the stasis channel topic and message types.
Returns
0 on success
Non-zero on error
Definition at line 1666 of file stasis_channels.c.
References AO2_ALLOC_OPT_LOCK_RWLOCK, ao2_container_alloc_hash, ast_channel_agent_login_type(), ast_channel_agent_logoff_type(), ast_channel_chanspy_start_type(), ast_channel_chanspy_stop_type(), ast_channel_dial_type(), ast_channel_dtmf_begin_type(), ast_channel_dtmf_end_type(), ast_channel_fax_type(), ast_channel_flash_type(), ast_channel_hangup_handler_type(), ast_channel_hangup_request_type(), ast_channel_hold_type(), ast_channel_masquerade_type(), ast_channel_mixmonitor_mute_type(), ast_channel_mixmonitor_start_type(), ast_channel_mixmonitor_stop_type(), ast_channel_moh_start_type(), ast_channel_moh_stop_type(), ast_channel_monitor_start_type(), ast_channel_monitor_stop_type(), ast_channel_snapshot_type(), ast_channel_talking_start(), ast_channel_talking_stop(), ast_channel_unhold_type(), ast_channel_varset_type(), AST_NUM_CHANNEL_BUCKETS, ast_register_cleanup(), channel_snapshot_cmp_cb(), channel_snapshot_hash_cb(), channel_snapshot_uniqueid_cmp_cb(), channel_snapshot_uniqueid_hash_cb(), NULL, stasis_channels_cleanup(), STASIS_MESSAGE_TYPE_INIT, and stasis_topic_create().
Referenced by ast_channels_init().
 {
    int res = 0;
    ast_register_cleanup(stasis_channels_cleanup);
    channel_topic_all = stasis_topic_create("channel:all");
    if (!channel_topic_all) {
       return -1;
    }
    channel_cache = ao2_container_alloc_hash(AO2_ALLOC_OPT_LOCK_RWLOCK,
       0, AST_NUM_CHANNEL_BUCKETS, channel_snapshot_uniqueid_hash_cb,
       NULL, channel_snapshot_uniqueid_cmp_cb);
    if (!channel_cache) {
       return -1;
    }
    channel_cache_by_name = ao2_container_alloc_hash(AO2_ALLOC_OPT_LOCK_RWLOCK,
       0, AST_NUM_CHANNEL_BUCKETS, channel_snapshot_hash_cb,
       NULL, channel_snapshot_cmp_cb);
    if (!channel_cache_by_name) {
       return -1;
    }
    res |= STASIS_MESSAGE_TYPE_INIT(ast_channel_agent_login_type);
    res |= STASIS_MESSAGE_TYPE_INIT(ast_channel_agent_logoff_type);
    res |= STASIS_MESSAGE_TYPE_INIT(ast_channel_snapshot_type);
    res |= STASIS_MESSAGE_TYPE_INIT(ast_channel_dial_type);
    res |= STASIS_MESSAGE_TYPE_INIT(ast_channel_varset_type);
    res |= STASIS_MESSAGE_TYPE_INIT(ast_channel_hangup_request_type);
    res |= STASIS_MESSAGE_TYPE_INIT(ast_channel_masquerade_type);
    res |= STASIS_MESSAGE_TYPE_INIT(ast_channel_dtmf_begin_type);
    res |= STASIS_MESSAGE_TYPE_INIT(ast_channel_dtmf_end_type);
    res |= STASIS_MESSAGE_TYPE_INIT(ast_channel_flash_type);
    res |= STASIS_MESSAGE_TYPE_INIT(ast_channel_hold_type);
    res |= STASIS_MESSAGE_TYPE_INIT(ast_channel_unhold_type);
    res |= STASIS_MESSAGE_TYPE_INIT(ast_channel_chanspy_start_type);
    res |= STASIS_MESSAGE_TYPE_INIT(ast_channel_chanspy_stop_type);
    res |= STASIS_MESSAGE_TYPE_INIT(ast_channel_fax_type);
    res |= STASIS_MESSAGE_TYPE_INIT(ast_channel_hangup_handler_type);
    res |= STASIS_MESSAGE_TYPE_INIT(ast_channel_moh_start_type);
    res |= STASIS_MESSAGE_TYPE_INIT(ast_channel_moh_stop_type);
    res |= STASIS_MESSAGE_TYPE_INIT(ast_channel_monitor_start_type);
    res |= STASIS_MESSAGE_TYPE_INIT(ast_channel_monitor_stop_type);
    res |= STASIS_MESSAGE_TYPE_INIT(ast_channel_mixmonitor_start_type);
    res |= STASIS_MESSAGE_TYPE_INIT(ast_channel_mixmonitor_stop_type);
    res |= STASIS_MESSAGE_TYPE_INIT(ast_channel_mixmonitor_mute_type);
    res |= STASIS_MESSAGE_TYPE_INIT(ast_channel_talking_start);
    res |= STASIS_MESSAGE_TYPE_INIT(ast_channel_talking_stop);
    return res;
 }
channel_blob_dtor()
static void channel_blob_dtor (void * obj) static
Definition at line 595 of file stasis_channels.c.
References ao2_cleanup, and ast_json_unref().
Referenced by create_channel_blob_message().
 {
    struct ast_channel_blob *event = obj;
    ao2_cleanup(event->snapshot);
    ast_json_unref(event->blob);
 }
channel_blob_to_json()
static struct ast_json* channel_blob_to_json (struct stasis_message * message, const char * type, const struct stasis_message_sanitizer * sanitize) static
Definition at line 1338 of file stasis_channels.c.
References ast_channel_snapshot_to_json(), ast_json_copy(), ast_json_is_null(), ast_json_object_create(), ast_json_object_set(), ast_json_string_create(), ast_json_timeval(), ast_json_unref(), ast_channel_blob::blob, NULL, ast_channel_blob::snapshot, channel_role_snapshot::snapshot, stasis_message_data(), and stasis_message_timestamp().
Referenced by hangup_request_to_json(), talking_start_to_json(), talking_stop_to_json(), and varset_to_json().
 {
    struct ast_json *to_json;
    struct ast_channel_blob *channel_blob = stasis_message_data(message);
    struct ast_json *blob = channel_blob->blob;
    struct ast_channel_snapshot *snapshot = channel_blob->snapshot;
    const struct timeval *tv = stasis_message_timestamp(message);
    int res = 0;
    if (blob == NULL || ast_json_is_null(blob)) {
       to_json = ast_json_object_create();
    } else {
       /* blobs are immutable, so shallow copies are fine */
       to_json = ast_json_copy(blob);
    }
    if (!to_json) {
       return NULL;
    }
    res |= ast_json_object_set(to_json, "type", ast_json_string_create(type));
    res |= ast_json_object_set(to_json, "timestamp",
       ast_json_timeval(*tv, NULL));
    /* For global channel messages, the snapshot is optional */
    if (snapshot) {
       struct ast_json *json_channel;
       json_channel = ast_channel_snapshot_to_json(snapshot, sanitize);
       if (!json_channel) {
          ast_json_unref(to_json);
          return NULL;
       }
       res |= ast_json_object_set(to_json, "channel", json_channel);
    }
    if (res != 0) {
       ast_json_unref(to_json);
       return NULL;
    }
    return to_json;
 }
channel_role_cmp_cb()
static int channel_role_cmp_cb (void * obj, void * arg, int flags) static
Definition at line 820 of file stasis_channels.c.
References CMP_MATCH, OBJ_SEARCH_KEY, OBJ_SEARCH_MASK, OBJ_SEARCH_OBJECT, OBJ_SEARCH_PARTIAL_KEY, and channel_role_snapshot::role.
Referenced by ast_multi_channel_blob_create(), and ast_multi_channel_blob_get_channels().
 {
    const struct channel_role_snapshot *object_left = obj;
    const struct channel_role_snapshot *object_right = arg;
    const char *right_key = arg;
    int cmp;
    switch (flags & OBJ_SEARCH_MASK) {
    case OBJ_SEARCH_OBJECT:
       right_key = object_right->role;
    case OBJ_SEARCH_KEY:
       cmp = strcasecmp(object_left->role, right_key);
       break;
    case OBJ_SEARCH_PARTIAL_KEY:
       cmp = strncasecmp(object_left->role, right_key, strlen(right_key));
       break;
    default:
       cmp = 0;
       break;
    }
    if (cmp) {
       return 0;
    }
    return CMP_MATCH;
 }
channel_role_hash_cb()
static int channel_role_hash_cb (const void * obj, const int flags) static
Definition at line 850 of file stasis_channels.c.
References ast_assert, ast_str_case_hash(), OBJ_SEARCH_KEY, OBJ_SEARCH_MASK, and OBJ_SEARCH_OBJECT.
Referenced by ast_multi_channel_blob_create().
 {
    const struct channel_role_snapshot *object = obj;
    const char *key;
    switch (flags & OBJ_SEARCH_MASK) {
    case OBJ_SEARCH_KEY:
       key = obj;
       break;
    case OBJ_SEARCH_OBJECT:
       key = object->role;
       break;
    default:
       ast_assert(0);
       return 0;
    }
    return ast_str_case_hash(key);
 }
channel_role_snapshot_dtor()
static void channel_role_snapshot_dtor (void * obj) static
Definition at line 949 of file stasis_channels.c.
References ao2_cleanup, and channel_role_snapshot::snapshot.
Referenced by ast_multi_channel_blob_add_channel().
 {
    struct channel_role_snapshot *role_snapshot = obj;
    ao2_cleanup(role_snapshot->snapshot);
 }
channel_snapshot_base_create()
static struct ast_channel_snapshot_base* channel_snapshot_base_create (struct ast_channel * chan) static
Definition at line 266 of file stasis_channels.c.
References accountcode, AO2_ALLOC_OPT_LOCK_NOLOCK, ao2_alloc_options, ao2_ref, ast_channel_accountcode(), ast_channel_creationtime(), ast_channel_language(), ast_channel_name(), ast_channel_tech(), ast_channel_uniqueid(), ast_channel_userfield(), ast_string_field_init, ast_string_field_set, channel_snapshot_base_dtor(), ast_channel_snapshot_base::creationtime, language, name, NULL, ast_channel_tech::properties, ast_channel_snapshot_base::tech_properties, type, ast_channel_snapshot_base::uniqueid, and ast_channel_snapshot_base::userfield.
Referenced by ast_channel_snapshot_create().
 {
    struct ast_channel_snapshot_base *snapshot;
    snapshot = ao2_alloc_options(sizeof(*snapshot), channel_snapshot_base_dtor,
       AO2_ALLOC_OPT_LOCK_NOLOCK);
    if (!snapshot) {
       return NULL;
    }
    if (ast_string_field_init(snapshot, 256)) {
       ao2_ref(snapshot, -1);
       return NULL;
    }
    ast_string_field_set(snapshot, name, ast_channel_name(chan));
    ast_string_field_set(snapshot, type, ast_channel_tech(chan)->type);
    ast_string_field_set(snapshot, accountcode, ast_channel_accountcode(chan));
    ast_string_field_set(snapshot, userfield, ast_channel_userfield(chan));
    ast_string_field_set(snapshot, uniqueid, ast_channel_uniqueid(chan));
    ast_string_field_set(snapshot, language, ast_channel_language(chan));
    snapshot->creationtime = ast_channel_creationtime(chan);
    snapshot->tech_properties = ast_channel_tech(chan)->properties;
    return snapshot;
 }
channel_snapshot_base_dtor()
static void channel_snapshot_base_dtor (void * obj) static
Definition at line 259 of file stasis_channels.c.
References ast_string_field_free_memory.
Referenced by channel_snapshot_base_create().
 {
    struct ast_channel_snapshot_base *snapshot = obj;
    ast_string_field_free_memory(snapshot);
 }
channel_snapshot_bridge_create()
static struct ast_channel_snapshot_bridge* channel_snapshot_bridge_create (struct ast_channel * chan) static
Definition at line 378 of file stasis_channels.c.
References AO2_ALLOC_OPT_LOCK_NOLOCK, ao2_alloc_options, ao2_cleanup, AST_BRIDGE_FLAG_INVISIBLE, ast_channel_get_bridge(), ast_test_flag, ast_bridge::feature_flags, ast_channel_snapshot_bridge::id, NULL, and ast_bridge::uniqueid.
Referenced by ast_channel_snapshot_create().
 {
    const char *uniqueid = "";
    struct ast_bridge *bridge;
    struct ast_channel_snapshot_bridge *snapshot;
    bridge = ast_channel_get_bridge(chan);
    if (bridge && !ast_test_flag(&bridge->feature_flags, AST_BRIDGE_FLAG_INVISIBLE)) {
       uniqueid = bridge->uniqueid;
    }
    ao2_cleanup(bridge);
    snapshot = ao2_alloc_options(sizeof(*snapshot) + strlen(uniqueid) + 1, NULL, AO2_ALLOC_OPT_LOCK_NOLOCK);
    if (!snapshot) {
       return NULL;
    }
    strcpy(snapshot->id, uniqueid); /* Safe */
    return snapshot;
 }
channel_snapshot_caller_create()
static struct ast_channel_snapshot_caller* channel_snapshot_caller_create (struct ast_channel * chan) static
Definition at line 321 of file stasis_channels.c.
References ast_channel_snapshot_caller::ani, AO2_ALLOC_OPT_LOCK_NOLOCK, ao2_alloc_options, ao2_ref, ast_channel_caller(), ast_channel_dialed(), ast_channel_redirecting(), ast_party_id_presentation(), ast_string_field_init, ast_string_field_set, channel_snapshot_caller_dtor(), ast_channel_snapshot_caller::dialed_subaddr, ast_channel_snapshot_caller::dnid, name, NULL, ast_channel_snapshot_caller::pres, ast_channel_snapshot_caller::rdnis, S_COR, S_OR, ast_party_dialed::str, and ast_channel_snapshot_caller::subaddr.
Referenced by ast_channel_snapshot_create().
 {
    struct ast_channel_snapshot_caller *snapshot;
    snapshot = ao2_alloc_options(sizeof(*snapshot), channel_snapshot_caller_dtor,
       AO2_ALLOC_OPT_LOCK_NOLOCK);
    if (!snapshot) {
       return NULL;
    }
    if (ast_string_field_init(snapshot, 256)) {
       ao2_ref(snapshot, -1);
       return NULL;
    }
    ast_string_field_set(snapshot, name,
       S_COR(ast_channel_caller(chan)->id.name.valid, ast_channel_caller(chan)->id.name.str, ""));
    ast_string_field_set(snapshot, number,
       S_COR(ast_channel_caller(chan)->id.number.valid, ast_channel_caller(chan)->id.number.str, ""));
    ast_string_field_set(snapshot, subaddr,
       S_COR(ast_channel_caller(chan)->id.subaddress.valid, ast_channel_caller(chan)->id.subaddress.str, ""));
    ast_string_field_set(snapshot, ani,
       S_COR(ast_channel_caller(chan)->ani.number.valid, ast_channel_caller(chan)->ani.number.str, ""));
    ast_string_field_set(snapshot, rdnis,
       S_COR(ast_channel_redirecting(chan)->from.number.valid, ast_channel_redirecting(chan)->from.number.str, ""));
    ast_string_field_set(snapshot, dnid,
       S_OR(ast_channel_dialed(chan)->number.str, ""));
    ast_string_field_set(snapshot, dialed_subaddr,
       S_COR(ast_channel_dialed(chan)->subaddress.valid, ast_channel_dialed(chan)->subaddress.str, ""));
    snapshot->pres = ast_party_id_presentation(&ast_channel_caller(chan)->id);
    return snapshot;
 }
channel_snapshot_caller_dtor()
static void channel_snapshot_caller_dtor (void * obj) static
Definition at line 314 of file stasis_channels.c.
References ast_string_field_free_memory.
Referenced by channel_snapshot_caller_create().
 {
    struct ast_channel_snapshot_caller *snapshot = obj;
    ast_string_field_free_memory(snapshot);
 }
channel_snapshot_cmp_cb()
static int channel_snapshot_cmp_cb (void * obj, void * arg, int flags) static
Definition at line 165 of file stasis_channels.c.
References ast_channel_snapshot::base, CMP_MATCH, ast_channel_snapshot_base::name, OBJ_SEARCH_KEY, OBJ_SEARCH_MASK, OBJ_SEARCH_OBJECT, and OBJ_SEARCH_PARTIAL_KEY.
Referenced by ast_multi_channel_blob_get_channels(), and ast_stasis_channels_init().
 {
    const struct ast_channel_snapshot *object_left = obj;
    const struct ast_channel_snapshot *object_right = arg;
    const char *right_key = arg;
    int cmp;
    switch (flags & OBJ_SEARCH_MASK) {
    case OBJ_SEARCH_OBJECT:
       right_key = object_right->base->name;
    case OBJ_SEARCH_KEY:
       cmp = strcasecmp(object_left->base->name, right_key);
       break;
    case OBJ_SEARCH_PARTIAL_KEY:
       cmp = strncasecmp(object_left->base->name, right_key, strlen(right_key));
       break;
    default:
       cmp = 0;
       break;
    }
    if (cmp) {
       return 0;
    }
    return CMP_MATCH;
 }
channel_snapshot_connected_create()
static struct ast_channel_snapshot_connected* channel_snapshot_connected_create (struct ast_channel * chan) static
Definition at line 358 of file stasis_channels.c.
References AO2_ALLOC_OPT_LOCK_NOLOCK, ao2_alloc_options, ast_channel_connected(), ast_copy_string(), name, ast_channel_snapshot_connected::name, NULL, ast_channel_snapshot_connected::number, and S_COR.
Referenced by ast_channel_snapshot_create().
 {
    const char *name = S_COR(ast_channel_connected(chan)->id.name.valid, ast_channel_connected(chan)->id.name.str, "");
    const char *number = S_COR(ast_channel_connected(chan)->id.number.valid, ast_channel_connected(chan)->id.number.str, "");
    size_t name_len = strlen(name) + 1;
    size_t number_len = strlen(number) + 1;
    struct ast_channel_snapshot_connected *snapshot;
    snapshot = ao2_alloc_options(sizeof(*snapshot) + name_len + number_len, NULL, AO2_ALLOC_OPT_LOCK_NOLOCK);
    if (!snapshot) {
       return NULL;
    }
    strcpy(snapshot->name, name); /* Safe */
    snapshot->number = snapshot->name + name_len;
    ast_copy_string(snapshot->number, number, number_len); /* Safe */
    return snapshot;
 }
channel_snapshot_dialplan_create()
static struct ast_channel_snapshot_dialplan* channel_snapshot_dialplan_create (struct ast_channel * chan) static
Definition at line 407 of file stasis_channels.c.
References AO2_ALLOC_OPT_LOCK_NOLOCK, ao2_alloc_options, ao2_ref, ast_channel_snapshot_dialplan::appl, ast_channel_appl(), ast_channel_context(), ast_channel_data(), ast_channel_exten(), ast_channel_priority(), ast_string_field_init, ast_string_field_set, channel_snapshot_dialplan_dtor(), context, ast_channel_snapshot_dialplan::data, exten, NULL, and ast_channel_snapshot_dialplan::priority.
Referenced by ast_channel_snapshot_create().
 {
    struct ast_channel_snapshot_dialplan *snapshot;
    snapshot = ao2_alloc_options(sizeof(*snapshot), channel_snapshot_dialplan_dtor,
       AO2_ALLOC_OPT_LOCK_NOLOCK);
    if (!snapshot) {
       return NULL;
    }
    if (ast_string_field_init(snapshot, 256)) {
       ao2_ref(snapshot, -1);
       return NULL;
    }
    if (ast_channel_appl(chan)) {
       ast_string_field_set(snapshot, appl, ast_channel_appl(chan));
    }
    if (ast_channel_data(chan)) {
       ast_string_field_set(snapshot, data, ast_channel_data(chan));
    }
    ast_string_field_set(snapshot, context, ast_channel_context(chan));
    ast_string_field_set(snapshot, exten, ast_channel_exten(chan));
    snapshot->priority = ast_channel_priority(chan);
    return snapshot;
 }
channel_snapshot_dialplan_dtor()
static void channel_snapshot_dialplan_dtor (void * obj) static
Definition at line 400 of file stasis_channels.c.
References ast_string_field_free_memory.
Referenced by channel_snapshot_dialplan_create().
 {
    struct ast_channel_snapshot_dialplan *snapshot = obj;
    ast_string_field_free_memory(snapshot);
 }
channel_snapshot_dtor()
static void channel_snapshot_dtor (void * obj) static
Definition at line 244 of file stasis_channels.c.
References ao2_cleanup, ast_channel_snapshot::ari_vars, ast_channel_snapshot::base, ast_channel_snapshot::bridge, ast_channel_snapshot::caller, ast_channel_snapshot::connected, ast_channel_snapshot::dialplan, ast_channel_snapshot::hangup, ast_channel_snapshot::manager_vars, and ast_channel_snapshot::peer.
Referenced by ast_channel_snapshot_create().
 {
    struct ast_channel_snapshot *snapshot = obj;
    ao2_cleanup(snapshot->base);
    ao2_cleanup(snapshot->peer);
    ao2_cleanup(snapshot->caller);
    ao2_cleanup(snapshot->connected);
    ao2_cleanup(snapshot->bridge);
    ao2_cleanup(snapshot->dialplan);
    ao2_cleanup(snapshot->hangup);
    ao2_cleanup(snapshot->manager_vars);
    ao2_cleanup(snapshot->ari_vars);
 }
channel_snapshot_hangup_create()
static struct ast_channel_snapshot_hangup* channel_snapshot_hangup_create (struct ast_channel * chan) static
Definition at line 435 of file stasis_channels.c.
References AO2_ALLOC_OPT_LOCK_NOLOCK, ao2_alloc_options, ast_channel_hangupcause(), ast_channel_hangupsource(), ast_channel_snapshot_hangup::cause, NULL, S_OR, and ast_channel_snapshot_hangup::source.
Referenced by ast_channel_snapshot_create().
 {
    const char *hangupsource = S_OR(ast_channel_hangupsource(chan), "");
    struct ast_channel_snapshot_hangup *snapshot;
    snapshot = ao2_alloc_options(sizeof(*snapshot) + strlen(hangupsource) + 1, NULL, AO2_ALLOC_OPT_LOCK_NOLOCK);
    if (!snapshot) {
       return NULL;
    }
    snapshot->cause = ast_channel_hangupcause(chan);
    strcpy(snapshot->source, hangupsource); /* Safe */
    return snapshot;
 }
channel_snapshot_hash_cb()
static int channel_snapshot_hash_cb (const void * obj, const int flags) static
Definition at line 142 of file stasis_channels.c.
References ast_assert, ast_str_case_hash(), OBJ_SEARCH_KEY, OBJ_SEARCH_MASK, and OBJ_SEARCH_OBJECT.
Referenced by ast_multi_channel_blob_get_channels(), and ast_stasis_channels_init().
 {
    const struct ast_channel_snapshot *object = obj;
    const char *key;
    switch (flags & OBJ_SEARCH_MASK) {
    case OBJ_SEARCH_KEY:
       key = obj;
       break;
    case OBJ_SEARCH_OBJECT:
       key = object->base->name;
       break;
    default:
       ast_assert(0);
       return 0;
    }
    return ast_str_case_hash(key);
 }
channel_snapshot_peer_create()
static struct ast_channel_snapshot_peer* channel_snapshot_peer_create (struct ast_channel * chan) static
Definition at line 294 of file stasis_channels.c.
References ast_channel_snapshot_peer::account, AO2_ALLOC_OPT_LOCK_NOLOCK, ao2_alloc_options, ast_channel_linkedid(), ast_channel_peeraccount(), ast_copy_string(), ast_channel_snapshot_peer::linkedid, NULL, and S_OR.
Referenced by ast_channel_snapshot_create().
 {
    const char *linkedid = S_OR(ast_channel_linkedid(chan), "");
    const char *peeraccount = S_OR(ast_channel_peeraccount(chan), "");
    size_t linkedid_len = strlen(linkedid) + 1;
    size_t peeraccount_len = strlen(peeraccount) + 1;
    struct ast_channel_snapshot_peer *snapshot;
    snapshot = ao2_alloc_options(sizeof(*snapshot) + linkedid_len + peeraccount_len, NULL, AO2_ALLOC_OPT_LOCK_NOLOCK);
    if (!snapshot) {
       return NULL;
    }
    strcpy(snapshot->account, peeraccount); /* Safe */
    snapshot->linkedid = snapshot->account + peeraccount_len;
    ast_copy_string(snapshot->linkedid, linkedid, linkedid_len); /* Safe */
    return snapshot;
 }
channel_snapshot_uniqueid_cmp_cb()
static int channel_snapshot_uniqueid_cmp_cb (void * obj, void * arg, int flags) static
Definition at line 218 of file stasis_channels.c.
References ast_channel_snapshot::base, CMP_MATCH, OBJ_SEARCH_KEY, OBJ_SEARCH_MASK, OBJ_SEARCH_OBJECT, OBJ_SEARCH_PARTIAL_KEY, and ast_channel_snapshot_base::uniqueid.
Referenced by ast_stasis_channels_init().
 {
    const struct ast_channel_snapshot *object_left = obj;
    const struct ast_channel_snapshot *object_right = arg;
    const char *right_key = arg;
    int cmp;
    switch (flags & OBJ_SEARCH_MASK) {
    case OBJ_SEARCH_OBJECT:
       right_key = object_right->base->uniqueid;
    case OBJ_SEARCH_KEY:
       cmp = strcasecmp(object_left->base->uniqueid, right_key);
       break;
    case OBJ_SEARCH_PARTIAL_KEY:
       cmp = strncasecmp(object_left->base->uniqueid, right_key, strlen(right_key));
       break;
    default:
       cmp = 0;
       break;
    }
    if (cmp) {
       return 0;
    }
    return CMP_MATCH;
 }
channel_snapshot_uniqueid_hash_cb()
static int channel_snapshot_uniqueid_hash_cb (const void * obj, const int flags) static
Definition at line 195 of file stasis_channels.c.
References ast_assert, ast_str_case_hash(), OBJ_SEARCH_KEY, OBJ_SEARCH_MASK, and OBJ_SEARCH_OBJECT.
Referenced by ast_stasis_channels_init().
 {
    const struct ast_channel_snapshot *object = obj;
    const char *key;
    switch (flags & OBJ_SEARCH_MASK) {
    case OBJ_SEARCH_KEY:
       key = obj;
       break;
    case OBJ_SEARCH_OBJECT:
       key = object->base->uniqueid;
       break;
    default:
       ast_assert(0);
       return 0;
    }
    return ast_str_case_hash(key);
 }
channel_snapshot_update_create()
static struct ast_channel_snapshot_update* channel_snapshot_update_create (struct ast_channel * chan) static
Definition at line 566 of file stasis_channels.c.
References AO2_ALLOC_OPT_LOCK_NOLOCK, ao2_alloc_options, ao2_bump, ao2_ref, ast_channel_snapshot(), ast_channel_snapshot_create(), channel_snapshot_update_dtor(), ast_channel_snapshot_update::new_snapshot, NULL, ast_channel_snapshot_update::old_snapshot, and update().
Referenced by ast_channel_publish_final_snapshot(), and ast_channel_publish_snapshot().
 {
    struct ast_channel_snapshot_update *update;
    update = ao2_alloc_options(sizeof(*update), channel_snapshot_update_dtor,
       AO2_ALLOC_OPT_LOCK_NOLOCK);
    if (!update) {
       return NULL;
    }
    update->old_snapshot = ao2_bump(ast_channel_snapshot(chan));
    update->new_snapshot = ast_channel_snapshot_create(chan);
    if (!update->new_snapshot) {
       ao2_ref(update, -1);
       return NULL;
    }
    return update;
 }
channel_snapshot_update_dtor()
static void channel_snapshot_update_dtor (void * obj) static
Definition at line 558 of file stasis_channels.c.
References ao2_cleanup, ast_channel_snapshot_update::new_snapshot, ast_channel_snapshot_update::old_snapshot, and update().
Referenced by channel_snapshot_update_create().
 {
    struct ast_channel_snapshot_update *update = obj;
    ao2_cleanup(update->old_snapshot);
    ao2_cleanup(update->new_snapshot);
 }
create_channel_blob_message()
static struct stasis_message* create_channel_blob_message (struct ast_channel_snapshot * snapshot, struct stasis_message_type * type, struct ast_json * blob) static
Definition at line 745 of file stasis_channels.c.
References ao2_alloc, ao2_cleanup, ao2_ref, ast_json_null(), ast_json_ref(), ast_channel_blob::blob, channel_blob_dtor(), NULL, ast_channel_blob::snapshot, and stasis_message_create().
Referenced by ast_channel_blob_create(), and ast_channel_blob_create_from_cache().
 {
    struct stasis_message *msg;
    struct ast_channel_blob *obj;
    obj = ao2_alloc(sizeof(*obj), channel_blob_dtor);
    if (!obj) {
       return NULL;
    }
    if (snapshot) {
       obj->snapshot = snapshot;
       ao2_ref(obj->snapshot, +1);
    }
    if (!blob) {
       blob = ast_json_null();
    }
    obj->blob = ast_json_ref(blob);
    msg = stasis_message_create(type, obj);
    ao2_cleanup(obj);
    return msg;
 }
dial_masquerade_breakdown()
static void dial_masquerade_breakdown (void * data, struct ast_channel * old_chan, struct ast_channel * new_chan) static
Definition at line 1882 of file stasis_channels.c.
References ao2_lock, ao2_unlock, ast_channel_name(), ast_channel_publish_dial_internal(), ast_debug, AST_LIST_EMPTY, AST_LIST_TRAVERSE, dial_masquerade_datastore::caller, dial_masquerade_datastore::dialed_peers, dial_target::dialstring, dial_target::list, NULL, and dial_target::peer.
 {
    struct dial_masquerade_datastore *masq_data = data;
    struct dial_target *cur;
    ao2_lock(masq_data);
    if (!masq_data->caller) {
       ao2_unlock(masq_data);
       return;
    }
    if (masq_data->caller == new_chan) {
       /*
        * The caller channel is being masqueraded into.
        * The masquerade is likely because of a blonde transfer.
        */
       ast_debug(1, "Caller channel %s being masqueraded into by %s (is_empty:%d)\n",
          ast_channel_name(old_chan), ast_channel_name(new_chan),
          AST_LIST_EMPTY(&masq_data->dialed_peers));
       AST_LIST_TRAVERSE(&masq_data->dialed_peers, cur, list) {
          ast_channel_publish_dial_internal(old_chan, cur->peer, NULL,
             cur->dialstring, "NOANSWER", NULL);
          ast_channel_publish_dial_internal(new_chan, cur->peer, NULL,
             cur->dialstring, NULL, NULL);
       }
       ao2_unlock(masq_data);
       return;
    }
    /*
     * One of the peer channels is being masqueraded into.
     * The masquerade is likely because of a call pickup.
     */
    AST_LIST_TRAVERSE(&masq_data->dialed_peers, cur, list) {
       if (cur->peer == new_chan) {
          ast_debug(1, "Peer channel %s being masqueraded into by %s\n",
             ast_channel_name(old_chan), ast_channel_name(new_chan));
          ast_channel_publish_dial_internal(masq_data->caller, old_chan, NULL,
             cur->dialstring, "CANCEL", NULL);
          ast_channel_publish_dial_internal(masq_data->caller, new_chan, NULL,
             cur->dialstring, NULL, NULL);
          break;
       }
    }
    ao2_unlock(masq_data);
 }
dial_masquerade_caller_datastore_destroy()
static void dial_masquerade_caller_datastore_destroy (void * data) static
Definition at line 1815 of file stasis_channels.c.
References ao2_ref, dial_masquerade_datastore_cleanup(), and dial_masquerade_datastore_find().
 {
    dial_masquerade_datastore_cleanup(data);
    ao2_ref(data, -1);
 }
dial_masquerade_datastore_add()
static struct dial_masquerade_datastore* dial_masquerade_datastore_add (struct ast_channel * chan, struct dial_masquerade_datastore * masq_data) static
Definition at line 1977 of file stasis_channels.c.
References ast_channel_datastore_add(), ast_datastore_alloc, ast_datastore_free(), dial_masquerade_datastore::caller, ast_datastore::data, dial_masquerade_datastore_alloc(), and NULL.
Referenced by set_dial_masquerade().
 {
    struct ast_datastore *datastore;
    datastore = ast_datastore_alloc(!masq_data ? &dial_masquerade_caller_info : &dial_masquerade_info, NULL);
    if (!datastore) {
       return NULL;
    }
    if (!masq_data) {
       masq_data = dial_masquerade_datastore_alloc();
       if (!masq_data) {
          ast_datastore_free(datastore);
          return NULL;
       }
       masq_data->caller = chan;
    }
    datastore->data = masq_data;
    ast_channel_datastore_add(chan, datastore);
    return masq_data;
 }
dial_masquerade_datastore_alloc()
static struct dial_masquerade_datastore* dial_masquerade_datastore_alloc (void) static
Definition at line 1789 of file stasis_channels.c.
References ao2_alloc, AST_LIST_HEAD_INIT_NOLOCK, dial_masquerade_datastore_dtor(), dial_masquerade_datastore::dialed_peers, and NULL.
Referenced by dial_masquerade_datastore_add().
 {
    struct dial_masquerade_datastore *masq_data;
    masq_data = ao2_alloc(sizeof(struct dial_masquerade_datastore),
       dial_masquerade_datastore_dtor);
    if (!masq_data) {
       return NULL;
    }
    AST_LIST_HEAD_INIT_NOLOCK(&masq_data->dialed_peers);
    return masq_data;
 }
dial_masquerade_datastore_cleanup()
static void dial_masquerade_datastore_cleanup (struct dial_masquerade_datastore * masq_data) static
Definition at line 1755 of file stasis_channels.c.
References AST_LIST_REMOVE_HEAD, dial_target_free(), dial_masquerade_datastore::dialed_peers, and dial_target::list.
Referenced by dial_masquerade_caller_datastore_destroy(), dial_masquerade_datastore_dtor(), dial_masquerade_datastore_remove_chan(), and dial_masquerade_fixup().
 {
    struct dial_target *cur;
    while ((cur = AST_LIST_REMOVE_HEAD(&masq_data->dialed_peers, list))) {
       dial_target_free(cur);
    }
 }
dial_masquerade_datastore_destroy()
static void dial_masquerade_datastore_destroy (void * data) static
Definition at line 1806 of file stasis_channels.c.
References ao2_ref.
 {
    ao2_ref(data, -1);
 }
dial_masquerade_datastore_dtor()
static void dial_masquerade_datastore_dtor (void * vdoomed) static
Definition at line 1784 of file stasis_channels.c.
References dial_masquerade_datastore_cleanup().
Referenced by dial_masquerade_datastore_alloc().
 {
    dial_masquerade_datastore_cleanup(vdoomed);
 }
dial_masquerade_datastore_find()
static struct ast_datastore * dial_masquerade_datastore_find (struct ast_channel * chan) static
Definition at line 1954 of file stasis_channels.c.
References ast_channel_datastore_find(), and NULL.
Referenced by dial_masquerade_caller_datastore_destroy(), dial_masquerade_fixup(), remove_dial_masquerade(), remove_dial_masquerade_caller(), and set_dial_masquerade().
 {
    struct ast_datastore *datastore;
    datastore = ast_channel_datastore_find(chan, &dial_masquerade_info, NULL);
    if (!datastore) {
       datastore = ast_channel_datastore_find(chan, &dial_masquerade_caller_info, NULL);
    }
    return datastore;
 }
dial_masquerade_datastore_remove_chan()
static void dial_masquerade_datastore_remove_chan (struct dial_masquerade_datastore * masq_data, struct ast_channel * chan) static
Definition at line 1764 of file stasis_channels.c.
References ao2_lock, ao2_unlock, AST_LIST_REMOVE_CURRENT, AST_LIST_TRAVERSE_SAFE_BEGIN, AST_LIST_TRAVERSE_SAFE_END, dial_masquerade_datastore::caller, dial_masquerade_datastore_cleanup(), dial_target_free(), dial_masquerade_datastore::dialed_peers, dial_target::list, and dial_target::peer.
Referenced by remove_dial_masquerade(), remove_dial_masquerade_caller(), and set_dial_masquerade().
 {
    struct dial_target *cur;
    ao2_lock(masq_data);
    if (masq_data->caller == chan) {
       dial_masquerade_datastore_cleanup(masq_data);
    } else {
       AST_LIST_TRAVERSE_SAFE_BEGIN(&masq_data->dialed_peers, cur, list) {
          if (cur->peer == chan) {
             AST_LIST_REMOVE_CURRENT(list);
             dial_target_free(cur);
             break;
          }
       }
       AST_LIST_TRAVERSE_SAFE_END;
    }
    ao2_unlock(masq_data);
 }
dial_masquerade_fixup()
static void dial_masquerade_fixup (void * data, struct ast_channel * old_chan, struct ast_channel * new_chan) static
Definition at line 1823 of file stasis_channels.c.
References ao2_lock, ao2_unlock, ast_channel_datastore_remove(), ast_channel_name(), ast_channel_publish_dial_internal(), ast_datastore_free(), ast_debug, AST_LIST_EMPTY, AST_LIST_REMOVE_CURRENT, AST_LIST_TRAVERSE, AST_LIST_TRAVERSE_SAFE_BEGIN, AST_LIST_TRAVERSE_SAFE_END, dial_masquerade_datastore::caller, dial_masquerade_datastore_cleanup(), dial_masquerade_datastore_find(), dial_target_free(), dial_masquerade_datastore::dialed_peers, dial_target::dialstring, NULL, and dial_target::peer.
 {
    struct dial_masquerade_datastore *masq_data = data;
    struct dial_target *cur;
    struct ast_datastore *datastore;
    ao2_lock(masq_data);
    if (!masq_data->caller) {
       /* Nothing to do but remove the datastore */
    } else if (masq_data->caller == old_chan) {
       /* The caller channel is being masqueraded out. */
       ast_debug(1, "Caller channel %s being masqueraded out to %s (is_empty:%d)\n",
          ast_channel_name(new_chan), ast_channel_name(old_chan),
          AST_LIST_EMPTY(&masq_data->dialed_peers));
       AST_LIST_TRAVERSE(&masq_data->dialed_peers, cur, list) {
          ast_channel_publish_dial_internal(new_chan, cur->peer, NULL,
             cur->dialstring, "NOANSWER", NULL);
          ast_channel_publish_dial_internal(old_chan, cur->peer, NULL,
             cur->dialstring, NULL, NULL);
       }
       dial_masquerade_datastore_cleanup(masq_data);
    } else {
       /* One of the peer channels is being masqueraded out. */
       AST_LIST_TRAVERSE_SAFE_BEGIN(&masq_data->dialed_peers, cur, list) {
          if (cur->peer == old_chan) {
             ast_debug(1, "Peer channel %s being masqueraded out to %s\n",
                ast_channel_name(new_chan), ast_channel_name(old_chan));
             ast_channel_publish_dial_internal(masq_data->caller, new_chan, NULL,
                cur->dialstring, "CANCEL", NULL);
             ast_channel_publish_dial_internal(masq_data->caller, old_chan, NULL,
                cur->dialstring, NULL, NULL);
             AST_LIST_REMOVE_CURRENT(list);
             dial_target_free(cur);
             break;
          }
       }
       AST_LIST_TRAVERSE_SAFE_END;
    }
    ao2_unlock(masq_data);
    /* Remove the datastore from the channel. */
    datastore = dial_masquerade_datastore_find(old_chan);
    if (!datastore) {
       return;
    }
    ast_channel_datastore_remove(old_chan, datastore);
    ast_datastore_free(datastore);
 }
dial_target_free()
static void dial_target_free (struct dial_target * doomed) static
Definition at line 1733 of file stasis_channels.c.
References ast_channel_cleanup, ast_free, dial_target::dialstring, and dial_target::peer.
Referenced by dial_masquerade_datastore_cleanup(), dial_masquerade_datastore_remove_chan(), and dial_masquerade_fixup().
 {
    if (!doomed) {
       return;
    }
    ast_free(doomed->dialstring);
    ast_channel_cleanup(doomed->peer);
    ast_free(doomed);
 }
dial_to_json()
static struct ast_json* dial_to_json (struct stasis_message * message, const struct stasis_message_sanitizer * sanitize) static
Definition at line 1433 of file stasis_channels.c.
References ast_channel_snapshot_to_json(), ast_json_object_get(), ast_json_object_set(), ast_json_pack(), ast_json_string_get(), ast_json_timeval(), ast_json_unref(), ast_multi_channel_blob_get_channel(), ast_multi_channel_blob_get_json(), NULL, stasis_message_data(), and stasis_message_timestamp().
Referenced by unhold_to_json().
 {
    struct ast_multi_channel_blob *payload = stasis_message_data(message);
    struct ast_json *blob = ast_multi_channel_blob_get_json(payload);
    const char *dialstatus =
       ast_json_string_get(ast_json_object_get(blob, "dialstatus"));
    const char *forward =
       ast_json_string_get(ast_json_object_get(blob, "forward"));
    const char *dialstring =
       ast_json_string_get(ast_json_object_get(blob, "dialstring"));
    struct ast_json *caller_json = ast_channel_snapshot_to_json(ast_multi_channel_blob_get_channel(payload, "caller"), sanitize);
    struct ast_json *peer_json = ast_channel_snapshot_to_json(ast_multi_channel_blob_get_channel(payload, "peer"), sanitize);
    struct ast_json *forwarded_json = ast_channel_snapshot_to_json(ast_multi_channel_blob_get_channel(payload, "forwarded"), sanitize);
    struct ast_json *json;
    const struct timeval *tv = stasis_message_timestamp(message);
    int res = 0;
    json = ast_json_pack("{s: s, s: o, s: s, s: s, s: s}",
       "type", "Dial",
       "timestamp", ast_json_timeval(*tv, NULL),
       "dialstatus", dialstatus,
       "forward", forward,
       "dialstring", dialstring);
    if (!json) {
       ast_json_unref(caller_json);
       ast_json_unref(peer_json);
       ast_json_unref(forwarded_json);
       return NULL;
    }
    if (caller_json) {
       res |= ast_json_object_set(json, "caller", caller_json);
    }
    if (peer_json) {
       res |= ast_json_object_set(json, "peer", peer_json);
    }
    if (forwarded_json) {
       res |= ast_json_object_set(json, "forwarded", forwarded_json);
    }
    if (res) {
       ast_json_unref(json);
       return NULL;
    }
    return json;
 }
dtmf_end_to_json()
static struct ast_json* dtmf_end_to_json (struct stasis_message * message, const struct stasis_message_sanitizer * sanitize) static
Definition at line 1385 of file stasis_channels.c.
References ast_channel_snapshot_to_json(), ast_json_integer_get(), ast_json_object_get(), ast_json_pack(), ast_json_string_get(), ast_json_timeval(), ast_channel_blob::blob, digit, NULL, ast_channel_blob::snapshot, channel_role_snapshot::snapshot, stasis_message_data(), and stasis_message_timestamp().
Referenced by unhold_to_json().
 {
    struct ast_channel_blob *channel_blob = stasis_message_data(message);
    struct ast_json *blob = channel_blob->blob;
    struct ast_channel_snapshot *snapshot = channel_blob->snapshot;
    const char *direction =
       ast_json_string_get(ast_json_object_get(blob, "direction"));
    const char *digit =
       ast_json_string_get(ast_json_object_get(blob, "digit"));
    long duration_ms =
       ast_json_integer_get(ast_json_object_get(blob, "duration_ms"));
    const struct timeval *tv = stasis_message_timestamp(message);
    struct ast_json *json_channel;
    /* Only present received DTMF end events as JSON */
    if (strcasecmp("Received", direction) != 0) {
       return NULL;
    }
    json_channel = ast_channel_snapshot_to_json(snapshot, sanitize);
    if (!json_channel) {
       return NULL;
    }
    return ast_json_pack("{s: s, s: o, s: s, s: I, s: o}",
       "type", "ChannelDtmfReceived",
       "timestamp", ast_json_timeval(*tv, NULL),
       "digit", digit,
       "duration_ms", (ast_json_int_t)duration_ms,
       "channel", json_channel);
 }
hangup_request_to_json()
static struct ast_json* hangup_request_to_json (struct stasis_message * message, const struct stasis_message_sanitizer * sanitize) static
Definition at line 1426 of file stasis_channels.c.
References channel_blob_to_json().
Referenced by unhold_to_json().
 {
    return channel_blob_to_json(message, "ChannelHangupRequest", sanitize);
 }
hold_to_json()
static struct ast_json* hold_to_json (struct stasis_message * message, const struct stasis_message_sanitizer * sanitize) static
Definition at line 1535 of file stasis_channels.c.
References ast_channel_snapshot_to_json(), ast_json_object_get(), ast_json_pack(), ast_json_string_get(), ast_json_timeval(), ast_channel_blob::blob, musicclass, NULL, S_OR, ast_channel_blob::snapshot, channel_role_snapshot::snapshot, stasis_message_data(), and stasis_message_timestamp().
Referenced by unhold_to_json().
 {
    struct ast_channel_blob *channel_blob = stasis_message_data(message);
    struct ast_json *blob = channel_blob->blob;
    struct ast_channel_snapshot *snapshot = channel_blob->snapshot;
    const char *musicclass = ast_json_string_get(ast_json_object_get(blob, "musicclass"));
    const struct timeval *tv = stasis_message_timestamp(message);
    struct ast_json *json_channel;
    json_channel = ast_channel_snapshot_to_json(snapshot, sanitize);
    if (!json_channel) {
       return NULL;
    }
    return ast_json_pack("{s: s, s: o, s: s, s: o}",
       "type", "ChannelHold",
       "timestamp", ast_json_timeval(*tv, NULL),
       "musicclass", S_OR(musicclass, "N/A"),
       "channel", json_channel);
 }
multi_channel_blob_dtor()
static void multi_channel_blob_dtor (void * obj) static
Definition at line 873 of file stasis_channels.c.
References ao2_cleanup, ast_json_unref(), ast_multi_channel_blob::blob, and ast_multi_channel_blob::channel_snapshots.
Referenced by ast_multi_channel_blob_create().
 {
    struct ast_multi_channel_blob *multi_blob = obj;
    ao2_cleanup(multi_blob->channel_snapshots);
    ast_json_unref(multi_blob->blob);
 }
publish_message_for_channel_topics()
static void publish_message_for_channel_topics (struct stasis_message * message, struct ast_channel * chan) static
Definition at line 586 of file stasis_channels.c.
References ast_channel_topic(), ast_channel_topic_all(), and stasis_publish().
Referenced by ast_channel_publish_dial_internal().
 {
    if (chan) {
       stasis_publish(ast_channel_topic(chan), message);
    } else {
       stasis_publish(ast_channel_topic_all(), message);
    }
 }
remove_dial_masquerade()
static void remove_dial_masquerade (struct ast_channel * peer) static
Definition at line 2081 of file stasis_channels.c.
References ast_channel_datastore_remove(), ast_datastore_free(), ast_datastore::data, dial_masquerade_datastore_find(), and dial_masquerade_datastore_remove_chan().
Referenced by ast_channel_publish_dial_forward(), and ast_channel_publish_dial_internal().
 {
    struct ast_datastore *datastore;
    struct dial_masquerade_datastore *masq_data;
    datastore = dial_masquerade_datastore_find(peer);
    if (!datastore) {
       return;
    }
    masq_data = datastore->data;
    if (masq_data) {
       dial_masquerade_datastore_remove_chan(masq_data, peer);
    }
    ast_channel_datastore_remove(peer, datastore);
    ast_datastore_free(datastore);
 }
remove_dial_masquerade_caller()
static void remove_dial_masquerade_caller (struct ast_channel * caller) static
Definition at line 2100 of file stasis_channels.c.
References ast_channel_datastore_remove(), ast_datastore_free(), AST_LIST_EMPTY, ast_datastore::data, dial_masquerade_datastore_find(), dial_masquerade_datastore_remove_chan(), and dial_masquerade_datastore::dialed_peers.
Referenced by ast_channel_publish_dial_forward(), and ast_channel_publish_dial_internal().
 {
    struct ast_datastore *datastore;
    struct dial_masquerade_datastore *masq_data;
    datastore = dial_masquerade_datastore_find(caller);
    if (!datastore) {
       return;
    }
    masq_data = datastore->data;
    if (!masq_data || !AST_LIST_EMPTY(&masq_data->dialed_peers)) {
       return;
    }
    dial_masquerade_datastore_remove_chan(masq_data, caller);
    ast_channel_datastore_remove(caller, datastore);
    ast_datastore_free(datastore);
 }
set_dial_masquerade()
static int set_dial_masquerade (struct ast_channel * caller, struct ast_channel * peer, const char * dialstring) static
Definition at line 2002 of file stasis_channels.c.
References ao2_lock, ao2_ref, ao2_unlock, ast_assert, ast_calloc, ast_channel_datastore_remove(), ast_channel_ref, ast_datastore_free(), ast_free, AST_LIST_INSERT_HEAD, ast_strdup, dial_masquerade_datastore::caller, ast_datastore::data, dial_masquerade_datastore_add(), dial_masquerade_datastore_find(), dial_masquerade_datastore_remove_chan(), dial_masquerade_datastore::dialed_peers, dial_target::dialstring, dial_target::list, NULL, and dial_target::peer.
Referenced by ast_channel_publish_dial_forward(), and ast_channel_publish_dial_internal().
 {
    struct ast_datastore *datastore;
    struct dial_masquerade_datastore *masq_data;
    struct dial_target *target;
    /* Find or create caller datastore */
    datastore = dial_masquerade_datastore_find(caller);
    if (!datastore) {
       masq_data = dial_masquerade_datastore_add(caller, NULL);
    } else {
       masq_data = datastore->data;
    }
    if (!masq_data) {
       return -1;
    }
    ao2_ref(masq_data, +1);
    /*
     * Someone likely forgot to do an ast_channel_publish_dial()
     * or ast_channel_publish_dial_forward() with a final dial
     * status on the channel.
     */
    ast_assert(masq_data->caller == caller);
    /* Create peer target to put into datastore */
    target = ast_calloc(1, sizeof(*target));
    if (!target) {
       ao2_ref(masq_data, -1);
       return -1;
    }
    if (dialstring) {
       target->dialstring = ast_strdup(dialstring);
       if (!target->dialstring) {
          ast_free(target);
          ao2_ref(masq_data, -1);
          return -1;
       }
    }
    target->peer = ast_channel_ref(peer);
    /* Put peer target into datastore */
    ao2_lock(masq_data);
    dial_masquerade_datastore_remove_chan(masq_data, peer);
    AST_LIST_INSERT_HEAD(&masq_data->dialed_peers, target, list);
    ao2_unlock(masq_data);
    datastore = dial_masquerade_datastore_find(peer);
    if (datastore) {
       if (datastore->data == masq_data) {
          /*
           * Peer already had the datastore for this dial masquerade.
           * This was a redundant peer dial masquerade setup.
           */
          ao2_ref(masq_data, -1);
          return 0;
       }
       /* Something is wrong.  Try to fix if the assert doesn't abort. */
       ast_assert(0);
       /* Remove the stale dial masquerade datastore */
       dial_masquerade_datastore_remove_chan(datastore->data, peer);
       ast_channel_datastore_remove(peer, datastore);
       ast_datastore_free(datastore);
    }
    /* Create the peer dial masquerade datastore */
    if (dial_masquerade_datastore_add(peer, masq_data)) {
       /* Success */
       return 0;
    }
    /* Failed to create the peer datastore */
    dial_masquerade_datastore_remove_chan(masq_data, peer);
    ao2_ref(masq_data, -1);
    return -1;
 }
stasis_channels_cleanup()
static void stasis_channels_cleanup (void) static
Definition at line 1630 of file stasis_channels.c.
References ao2_cleanup, ast_channel_agent_login_type(), ast_channel_agent_logoff_type(), ast_channel_chanspy_start_type(), ast_channel_chanspy_stop_type(), ast_channel_dial_type(), ast_channel_dtmf_begin_type(), ast_channel_dtmf_end_type(), ast_channel_fax_type(), ast_channel_flash_type(), ast_channel_hangup_handler_type(), ast_channel_hangup_request_type(), ast_channel_hold_type(), ast_channel_masquerade_type(), ast_channel_mixmonitor_mute_type(), ast_channel_mixmonitor_start_type(), ast_channel_mixmonitor_stop_type(), ast_channel_moh_start_type(), ast_channel_moh_stop_type(), ast_channel_monitor_start_type(), ast_channel_monitor_stop_type(), ast_channel_snapshot_type(), ast_channel_talking_start(), ast_channel_talking_stop(), ast_channel_unhold_type(), ast_channel_varset_type(), NULL, and STASIS_MESSAGE_TYPE_CLEANUP.
Referenced by ast_stasis_channels_init().
 {
    ao2_cleanup(channel_topic_all);
    channel_topic_all = NULL;
    ao2_cleanup(channel_cache);
    channel_cache = NULL;
    ao2_cleanup(channel_cache_by_name);
    channel_cache_by_name = NULL;
    STASIS_MESSAGE_TYPE_CLEANUP(ast_channel_snapshot_type);
    STASIS_MESSAGE_TYPE_CLEANUP(ast_channel_dial_type);
    STASIS_MESSAGE_TYPE_CLEANUP(ast_channel_varset_type);
    STASIS_MESSAGE_TYPE_CLEANUP(ast_channel_hangup_request_type);
    STASIS_MESSAGE_TYPE_CLEANUP(ast_channel_masquerade_type);
    STASIS_MESSAGE_TYPE_CLEANUP(ast_channel_dtmf_begin_type);
    STASIS_MESSAGE_TYPE_CLEANUP(ast_channel_dtmf_end_type);
    STASIS_MESSAGE_TYPE_CLEANUP(ast_channel_flash_type);
    STASIS_MESSAGE_TYPE_CLEANUP(ast_channel_hold_type);
    STASIS_MESSAGE_TYPE_CLEANUP(ast_channel_unhold_type);
    STASIS_MESSAGE_TYPE_CLEANUP(ast_channel_chanspy_start_type);
    STASIS_MESSAGE_TYPE_CLEANUP(ast_channel_chanspy_stop_type);
    STASIS_MESSAGE_TYPE_CLEANUP(ast_channel_fax_type);
    STASIS_MESSAGE_TYPE_CLEANUP(ast_channel_hangup_handler_type);
    STASIS_MESSAGE_TYPE_CLEANUP(ast_channel_moh_start_type);
    STASIS_MESSAGE_TYPE_CLEANUP(ast_channel_moh_stop_type);
    STASIS_MESSAGE_TYPE_CLEANUP(ast_channel_monitor_start_type);
    STASIS_MESSAGE_TYPE_CLEANUP(ast_channel_monitor_stop_type);
    STASIS_MESSAGE_TYPE_CLEANUP(ast_channel_mixmonitor_start_type);
    STASIS_MESSAGE_TYPE_CLEANUP(ast_channel_mixmonitor_stop_type);
    STASIS_MESSAGE_TYPE_CLEANUP(ast_channel_mixmonitor_mute_type);
    STASIS_MESSAGE_TYPE_CLEANUP(ast_channel_agent_login_type);
    STASIS_MESSAGE_TYPE_CLEANUP(ast_channel_agent_logoff_type);
    STASIS_MESSAGE_TYPE_CLEANUP(ast_channel_talking_start);
    STASIS_MESSAGE_TYPE_CLEANUP(ast_channel_talking_stop);
 }
STASIS_MESSAGE_TYPE_DEFN() [1/25]
STASIS_MESSAGE_TYPE_DEFN (ast_channel_snapshot_type)
Define channel message types.
Referenced by unhold_to_json().
STASIS_MESSAGE_TYPE_DEFN() [2/25]
STASIS_MESSAGE_TYPE_DEFN (ast_channel_dial_type , . to_json = dial_to_json)
STASIS_MESSAGE_TYPE_DEFN() [3/25]
STASIS_MESSAGE_TYPE_DEFN (ast_channel_varset_type , . to_ami = varset_to_ami, . to_json = varset_to_json)
STASIS_MESSAGE_TYPE_DEFN() [4/25]
STASIS_MESSAGE_TYPE_DEFN (ast_channel_hangup_request_type , . to_json = hangup_request_to_json)
STASIS_MESSAGE_TYPE_DEFN() [5/25]
STASIS_MESSAGE_TYPE_DEFN (ast_channel_masquerade_type)
STASIS_MESSAGE_TYPE_DEFN() [6/25]
STASIS_MESSAGE_TYPE_DEFN (ast_channel_dtmf_begin_type)
STASIS_MESSAGE_TYPE_DEFN() [7/25]
STASIS_MESSAGE_TYPE_DEFN (ast_channel_dtmf_end_type , . to_json = dtmf_end_to_json)
STASIS_MESSAGE_TYPE_DEFN() [8/25]
STASIS_MESSAGE_TYPE_DEFN (ast_channel_hold_type , . to_json = hold_to_json)
STASIS_MESSAGE_TYPE_DEFN() [9/25]
STASIS_MESSAGE_TYPE_DEFN (ast_channel_unhold_type , . to_json = unhold_to_json)
STASIS_MESSAGE_TYPE_DEFN() [10/25]
STASIS_MESSAGE_TYPE_DEFN (ast_channel_flash_type)
STASIS_MESSAGE_TYPE_DEFN() [11/25]
STASIS_MESSAGE_TYPE_DEFN (ast_channel_chanspy_start_type)
STASIS_MESSAGE_TYPE_DEFN() [12/25]
STASIS_MESSAGE_TYPE_DEFN (ast_channel_chanspy_stop_type)
STASIS_MESSAGE_TYPE_DEFN() [13/25]
STASIS_MESSAGE_TYPE_DEFN (ast_channel_fax_type)
STASIS_MESSAGE_TYPE_DEFN() [14/25]
STASIS_MESSAGE_TYPE_DEFN (ast_channel_hangup_handler_type)
STASIS_MESSAGE_TYPE_DEFN() [15/25]
STASIS_MESSAGE_TYPE_DEFN (ast_channel_moh_start_type)
STASIS_MESSAGE_TYPE_DEFN() [16/25]
STASIS_MESSAGE_TYPE_DEFN (ast_channel_moh_stop_type)
STASIS_MESSAGE_TYPE_DEFN() [17/25]
STASIS_MESSAGE_TYPE_DEFN (ast_channel_monitor_start_type)
STASIS_MESSAGE_TYPE_DEFN() [18/25]
STASIS_MESSAGE_TYPE_DEFN (ast_channel_monitor_stop_type)
STASIS_MESSAGE_TYPE_DEFN() [19/25]
STASIS_MESSAGE_TYPE_DEFN (ast_channel_mixmonitor_start_type)
STASIS_MESSAGE_TYPE_DEFN() [20/25]
STASIS_MESSAGE_TYPE_DEFN (ast_channel_mixmonitor_stop_type)
STASIS_MESSAGE_TYPE_DEFN() [21/25]
STASIS_MESSAGE_TYPE_DEFN (ast_channel_mixmonitor_mute_type)
STASIS_MESSAGE_TYPE_DEFN() [22/25]
STASIS_MESSAGE_TYPE_DEFN (ast_channel_agent_login_type , . to_ami = agent_login_to_ami)
STASIS_MESSAGE_TYPE_DEFN() [23/25]
STASIS_MESSAGE_TYPE_DEFN (ast_channel_agent_logoff_type , . to_ami = agent_logoff_to_ami)
STASIS_MESSAGE_TYPE_DEFN() [24/25]
STASIS_MESSAGE_TYPE_DEFN (ast_channel_talking_start , . to_ami = talking_start_to_ami, . to_json = talking_start_to_json)
STASIS_MESSAGE_TYPE_DEFN() [25/25]
STASIS_MESSAGE_TYPE_DEFN (ast_channel_talking_stop , . to_ami = talking_stop_to_ami, . to_json = talking_stop_to_json)
talking_start_to_ami()
static struct ast_manager_event_blob* talking_start_to_ami (struct stasis_message * msg) static
Definition at line 1483 of file stasis_channels.c.
References ast_free, ast_manager_build_channel_state_string(), ast_manager_event_blob_create(), ast_str_buffer(), EVENT_FLAG_CALL, NULL, ast_channel_blob::snapshot, and stasis_message_data().
Referenced by unhold_to_json().
 {
    struct ast_str *channel_string;
    struct ast_channel_blob *obj = stasis_message_data(msg);
    struct ast_manager_event_blob *blob;
    channel_string = ast_manager_build_channel_state_string(obj->snapshot);
    if (!channel_string) {
       return NULL;
    }
    blob = ast_manager_event_blob_create(EVENT_FLAG_CALL, "ChannelTalkingStart",
                                         "%s", ast_str_buffer(channel_string));
    ast_free(channel_string);
    return blob;
 }
talking_start_to_json()
static struct ast_json* talking_start_to_json (struct stasis_message * message, const struct stasis_message_sanitizer * sanitize) static
Definition at line 1501 of file stasis_channels.c.
References channel_blob_to_json().
Referenced by unhold_to_json().
 {
    return channel_blob_to_json(message, "ChannelTalkingStarted", sanitize);
 }
talking_stop_to_ami()
static struct ast_manager_event_blob* talking_stop_to_ami (struct stasis_message * msg) static
Definition at line 1507 of file stasis_channels.c.
References ast_free, ast_json_integer_get(), ast_json_object_get(), ast_manager_build_channel_state_string(), ast_manager_event_blob_create(), ast_str_buffer(), ast_channel_blob::blob, EVENT_FLAG_CALL, NULL, ast_channel_blob::snapshot, and stasis_message_data().
Referenced by unhold_to_json().
 {
    struct ast_str *channel_string;
    struct ast_channel_blob *obj = stasis_message_data(msg);
    int duration = ast_json_integer_get(ast_json_object_get(obj->blob, "duration"));
    struct ast_manager_event_blob *blob;
    channel_string = ast_manager_build_channel_state_string(obj->snapshot);
    if (!channel_string) {
       return NULL;
    }
    blob = ast_manager_event_blob_create(EVENT_FLAG_CALL, "ChannelTalkingStop",
                                         "%s"
                                         "Duration: %d\r\n",
                                         ast_str_buffer(channel_string),
                                         duration);
    ast_free(channel_string);
    return blob;
 }
talking_stop_to_json()
static struct ast_json* talking_stop_to_json (struct stasis_message * message, const struct stasis_message_sanitizer * sanitize) static
Definition at line 1529 of file stasis_channels.c.
References channel_blob_to_json().
Referenced by unhold_to_json().
 {
    return channel_blob_to_json(message, "ChannelTalkingFinished", sanitize);
 }
unhold_to_json()
static struct ast_json* unhold_to_json (struct stasis_message * message, const struct stasis_message_sanitizer * sanitize) static
Definition at line 1557 of file stasis_channels.c.
References agent_login_to_ami(), agent_logoff_to_ami(), ast_channel_agent_login_type(), ast_channel_agent_logoff_type(), ast_channel_chanspy_start_type(), ast_channel_chanspy_stop_type(), ast_channel_dial_type(), ast_channel_dtmf_begin_type(), ast_channel_dtmf_end_type(), ast_channel_fax_type(), ast_channel_flash_type(), ast_channel_hangup_handler_type(), ast_channel_hangup_request_type(), ast_channel_hold_type(), ast_channel_masquerade_type(), ast_channel_mixmonitor_mute_type(), ast_channel_mixmonitor_start_type(), ast_channel_mixmonitor_stop_type(), ast_channel_moh_start_type(), ast_channel_moh_stop_type(), ast_channel_monitor_start_type(), ast_channel_monitor_stop_type(), ast_channel_snapshot_to_json(), ast_channel_snapshot_type(), ast_channel_talking_start(), ast_channel_talking_stop(), ast_channel_unhold_type(), ast_channel_varset_type(), ast_json_pack(), ast_json_timeval(), dial_to_json(), dtmf_end_to_json(), hangup_request_to_json(), hold_to_json(), NULL, ast_channel_blob::snapshot, channel_role_snapshot::snapshot, stasis_message_data(), stasis_message_timestamp(), STASIS_MESSAGE_TYPE_DEFN(), talking_start_to_ami(), talking_start_to_json(), talking_stop_to_ami(), talking_stop_to_json(), to_ami(), varset_to_ami(), and varset_to_json().
 {
    struct ast_channel_blob *channel_blob = stasis_message_data(message);
    struct ast_channel_snapshot *snapshot = channel_blob->snapshot;
    const struct timeval *tv = stasis_message_timestamp(message);
    struct ast_json *json_channel;
    json_channel = ast_channel_snapshot_to_json(snapshot, sanitize);
    if (!json_channel) {
       return NULL;
    }
    return ast_json_pack("{s: s, s: o, s: o}",
       "type", "ChannelUnhold",
       "timestamp", ast_json_timeval(*tv, NULL),
       "channel", json_channel);
 }
varset_to_ami()
static struct ast_manager_event_blob* varset_to_ami (struct stasis_message * msg) static
Definition at line 1175 of file stasis_channels.c.
References ast_escape_c_alloc(), ast_free, ast_json_object_get(), ast_json_string_get(), ast_manager_build_channel_state_string(), ast_manager_event_blob_create(), ast_str_buffer(), ast_str_create, ast_str_set(), ast_channel_blob::blob, EVENT_FLAG_DIALPLAN, NULL, ast_channel_blob::snapshot, stasis_message_data(), and value.
Referenced by unhold_to_json().
 {
    struct ast_str *channel_event_string;
    struct ast_channel_blob *obj = stasis_message_data(msg);
    const char *variable =
       ast_json_string_get(ast_json_object_get(obj->blob, "variable"));
    char *value;
    struct ast_manager_event_blob *ev;
    value = ast_escape_c_alloc(ast_json_string_get(ast_json_object_get(obj->blob,
       "value")));
    if (!value) {
       return NULL;
    }
    if (obj->snapshot) {
       channel_event_string = ast_manager_build_channel_state_string(obj->snapshot);
    } else {
       channel_event_string = ast_str_create(35);
       ast_str_set(&channel_event_string, 0,
          "Channel: none\r\n"
          "Uniqueid: none\r\n");
    }
    if (!channel_event_string) {
       ast_free(value);
       return NULL;
    }
    ev = ast_manager_event_blob_create(EVENT_FLAG_DIALPLAN, "VarSet",
       "%s"
       "Variable: %s\r\n"
       "Value: %s\r\n",
       ast_str_buffer(channel_event_string), variable, value);
    ast_free(channel_event_string);
    ast_free(value);
    return ev;
 }
varset_to_json()
static struct ast_json* varset_to_json (struct stasis_message * message, const struct stasis_message_sanitizer * sanitize) static
Definition at line 1419 of file stasis_channels.c.
References channel_blob_to_json().
Referenced by unhold_to_json().
 {
    return channel_blob_to_json(message, "ChannelVarset", sanitize);
 }
Variable Documentation
channel_cache
struct ao2_container* channel_cache static
Definition at line 120 of file stasis_channels.c.
Referenced by channels_scrape_cb().
channel_cache_by_name
struct ao2_container* channel_cache_by_name static
Definition at line 121 of file stasis_channels.c.
channel_topic_all
struct stasis_topic* channel_topic_all static
Definition at line 119 of file stasis_channels.c.
Referenced by ast_channel_topic_all().
dial_masquerade_caller_info
const struct ast_datastore_info dial_masquerade_caller_info static
Definition at line 1939 of file stasis_channels.c.
dial_masquerade_info
const struct ast_datastore_info dial_masquerade_info static
Definition at line 1932 of file stasis_channels.c.