Asterisk - The Open Source Telephony Project: threadstorage.h File Reference
threadstorage.h File Reference
Definitions to aid in the use of thread local storage.
#include "asterisk/utils.h"
#include "asterisk/inline_api.h"
Data Structures
struct ast_threadstorage
data for a thread locally stored variable
Macros
#define AST_PTHREAD_ONCE_INIT PTHREAD_ONCE_INIT
#define AST_THREADSTORAGE(name) AST_THREADSTORAGE_CUSTOM_SCOPE(name, NULL, ast_free_ptr, static)
Define a thread storage variable.
#define AST_THREADSTORAGE_CUSTOM(a, b, c) AST_THREADSTORAGE_CUSTOM_SCOPE(a,b,c,static)
Define a thread storage variable, with custom initialization and cleanup.
#define AST_THREADSTORAGE_CUSTOM_SCOPE(name, c_init, c_cleanup, scope)
#define AST_THREADSTORAGE_EXTERNAL(name) extern struct ast_threadstorage name
#define AST_THREADSTORAGE_PUBLIC(name) AST_THREADSTORAGE_CUSTOM_SCOPE(name, NULL, ast_free_ptr,)
#define AST_THREADSTORAGE_RAW(name) AST_THREADSTORAGE_CUSTOM_SCOPE(name, NULL, THREADSTORAGE_RAW_CLEANUP,)
#define THREADSTORAGE_RAW_CLEANUP NULL
Functions
void * ast_threadstorage_get (struct ast_threadstorage *ts, size_t init_size)
Retrieve thread storage.
void * ast_threadstorage_get_ptr (struct ast_threadstorage *ts)
Retrieve a raw pointer from threadstorage.
int ast_threadstorage_set_ptr (struct ast_threadstorage *ts, void *ptr)
Set a raw pointer from threadstorage.
Detailed Description
Definitions to aid in the use of thread local storage.
Author
Russell Bryant russe.nosp@m.ll@d.nosp@m.igium.nosp@m..com
The Asterisk Thread Storage API
Definition in file threadstorage.h.
Macro Definition Documentation
AST_PTHREAD_ONCE_INIT
#define AST_PTHREAD_ONCE_INIT PTHREAD_ONCE_INIT
Definition at line 114 of file threadstorage.h.
AST_THREADSTORAGE
#define AST_THREADSTORAGE (name) AST_THREADSTORAGE_CUSTOM_SCOPE(name, NULL, ast_free_ptr, static)
Define a thread storage variable.
Parameters
name The name of the thread storage object
This macro would be used to declare an instance of thread storage in a file.
Example usage:
AST_THREADSTORAGE(my_buf);
Definition at line 84 of file threadstorage.h.
Referenced by ao2_container_unregister().
AST_THREADSTORAGE_CUSTOM
#define AST_THREADSTORAGE_CUSTOM (a, b, c) AST_THREADSTORAGE_CUSTOM_SCOPE(a,b,c,static)
Define a thread storage variable, with custom initialization and cleanup.
Parameters
a The name of the thread storage object
b This is a custom function that will be called after each thread specific object is allocated, with the allocated block of memory passed as the argument.
c This is a custom function that will be called instead of ast_free when the thread goes away. Note that if this is used, it MUST call free on the allocated memory.
Example usage:
AST_THREADSTORAGE_CUSTOM(my_buf, my_init, my_cleanup);
Definition at line 109 of file threadstorage.h.
AST_THREADSTORAGE_CUSTOM_SCOPE
#define AST_THREADSTORAGE_CUSTOM_SCOPE (name, c_init, c_cleanup, scope)
Definition at line 118 of file threadstorage.h.
AST_THREADSTORAGE_EXTERNAL
#define AST_THREADSTORAGE_EXTERNAL (name) extern struct ast_threadstorage name
Definition at line 88 of file threadstorage.h.
AST_THREADSTORAGE_PUBLIC
#define AST_THREADSTORAGE_PUBLIC (name) AST_THREADSTORAGE_CUSTOM_SCOPE(name, NULL, ast_free_ptr,)
Definition at line 86 of file threadstorage.h.
AST_THREADSTORAGE_RAW
#define AST_THREADSTORAGE_RAW (name) AST_THREADSTORAGE_CUSTOM_SCOPE(name, NULL, THREADSTORAGE_RAW_CLEANUP,)
Definition at line 90 of file threadstorage.h.
THREADSTORAGE_RAW_CLEANUP
#define THREADSTORAGE_RAW_CLEANUP NULL
Definition at line 69 of file threadstorage.h.
Function Documentation
ast_threadstorage_get()
void * ast_threadstorage_get (struct ast_threadstorage * ts, size_t init_size) inline
Retrieve thread storage.
Parameters
ts This is a pointer to the thread storage structure declared by using the AST_THREADSTORAGE macro. If declared with AST_THREADSTORAGE(my_buf), then this argument would be (&my_buf).
init_size This is the amount of space to be allocated the first time this thread requests its data. Thus, this should be the size that the code accessing this thread storage is assuming the size to be.
Returns
This function will return the thread local storage associated with the thread storage management variable passed as the first argument. The result will be NULL in the case of a memory allocation error.
Example usage:
AST_THREADSTORAGE(my_buf);
#define MY_BUF_SIZE   128
...
void my_func(const char *fmt, ...)
{
     void *buf;
     if (!(buf = ast_threadstorage_get(&my_buf, MY_BUF_SIZE)))
          return;
     ...
}
Examples:
/usr/src/asterisk-18.5.0/include/asterisk/strings.h.
Definition at line 197 of file threadstorage.h.
References ast_calloc, ast_free, AST_INLINE_API, ast_threadstorage_get_ptr(), buf, ast_threadstorage::custom_init, make_ari_stubs::file, ast_threadstorage::key, ast_threadstorage::key_init, NULL, and ast_threadstorage::once.
Referenced by __ast_frdup(), __frame_free(), acf_curl_helper(), ast_callid_threadassoc_add(), ast_callid_threadassoc_change(), ast_callid_threadassoc_remove(), ast_channel_internal_errno(), ast_channel_internal_errno_set(), ast_find_lock_info(), ast_frame_header_new(), ast_inet_ntoa(), ast_mark_lock_acquired(), ast_mark_lock_failed(), ast_read_threadstorage_callid(), ast_remove_lock_info(), ast_restore_lock_info(), ast_sched_del(), ast_sip_thread_is_servant(), ast_state2str(), ast_store_lock_info(), ast_suspend_lock_info(), ast_term_color(), ast_thread_inhibit_escalations(), ast_thread_inhibit_escalations_swap(), ast_thread_is_user_interface(), ast_thread_user_interface_set(), ast_verb_console_get(), ast_verb_console_register(), ast_verb_console_set(), ast_verb_console_unregister(), callstate2str(), chan_pjsip_get_uniqueid(), console_print(), control2str(), device2str(), dialplan_handle_msg_cb(), dummy_start(), find_or_create_temporary_state(), find_temporary_state(), get_auth(), get_transport_list(), iax_frame_free(), iax_frame_new(), idle_sched_init_pj_thread(), is_passthru_update(), pj_thread_register_check(), process_text_line(), registration_client_send(), remove_auth(), remove_temporary_state(), set_passthru_update(), sip_outbound_registration_response_cb(), sip_thread_start(), ssl_error_to_string(), store_auth(), substate2str(), thread_inhibits_escalations(), and transmit_response_using_temp().
 {
ast_threadstorage_get_ptr()
void * ast_threadstorage_get_ptr (struct ast_threadstorage * ts) inline
Retrieve a raw pointer from threadstorage.
Parameters
ts Threadstorage object to operate on.
Returns
A pointer associated with the current thread, NULL if no pointer is associated yet.
Note
This should only be used on threadstorage declared by AST_THREADSTORAGE_RAW unless you really know what you are doing.
Definition at line 241 of file threadstorage.h.
References ast_threadstorage::key, ast_threadstorage::key_init, and ast_threadstorage::once.
Referenced by __ast_trace(), _ast_trace_dec_indent(), _ast_trace_get_indent(), _ast_trace_inc_indent(), ast_channel_get_intercept_mode(), ast_cli_completion_add(), ast_cli_completion_vector(), ast_log_safe(), ast_threadpool_serializer_get_current(), and ast_threadstorage_get().
 {
ast_threadstorage_set_ptr()
int ast_threadstorage_set_ptr (struct ast_threadstorage * ts, void * ptr) inline
Set a raw pointer from threadstorage.
Parameters
ts Threadstorage object to operate on.
Return values
0 Success
non-zero Failure
Note
This should only be used on threadstorage declared by AST_THREADSTORAGE_RAW unless you really know what you are doing.
Definition at line 260 of file threadstorage.h.
Referenced by __ast_trace(), _ast_trace_dec_indent(), _ast_trace_inc_indent(), _ast_trace_set_indent(), ast_cli_completion_vector(), ast_log_safe(), channel_set_intercept_mode(), cli_completion_vector_add(), and execute_tasks().