Asterisk - The Open Source Telephony Project: firmware.h File Reference
firmware.h File Reference
IAX Firmware Support header file.
#include "parser.h"
Functions
int iax_firmware_append (struct iax_ie_data *ie_data, const char *device_name, unsigned int block_desc)
int iax_firmware_get_version (const char *device_name, uint16_t *version)
void iax_firmware_reload (void)
void iax_firmware_traverse (const char *prefix, int(*callback)(struct ast_iax2_firmware_header *header, void *user_data), void *user_data)
void iax_firmware_unload (void)
Detailed Description
IAX Firmware Support header file.
Definition in file firmware.h.
Function Documentation
iax_firmware_append()
int iax_firmware_append (struct iax_ie_data * ie_data, const char * device_name, unsigned int block_desc)
Definition at line 283 of file firmware.c.
References AST_LIST_LOCK, AST_LIST_TRAVERSE, AST_LIST_UNLOCK, ast_strlen_zero, bs, ast_iax2_firmware_header::data, ast_iax2_firmware_header::datalen, ast_iax2_firmware_header::devname, iax_firmware::fwh, iax_ie_append(), iax_ie_append_int(), iax_ie_append_raw(), IAX_IE_FWBLOCKDATA, IAX_IE_FWBLOCKDESC, and iax_firmware::list.
Referenced by socket_process_helper().
 {
    int res = -1;
    unsigned int bs = desc & 0xff;
    unsigned int start = (desc >> 8) & 0xffffff;
    unsigned int bytes;
    struct iax_firmware *cur;
    if (ast_strlen_zero((char *)dev) || !bs)
       return -1;
    start *= bs;
    AST_LIST_LOCK(&firmwares);
    AST_LIST_TRAVERSE(&firmwares, cur, list) {
       if (strcmp(dev, (const char *) cur->fwh->devname))
          continue;
       iax_ie_append_int(ied, IAX_IE_FWBLOCKDESC, desc);
       if (start < ntohl(cur->fwh->datalen)) {
          bytes = ntohl(cur->fwh->datalen) - start;
          if (bytes > bs)
             bytes = bs;
          iax_ie_append_raw(ied, IAX_IE_FWBLOCKDATA, cur->fwh->data + start, bytes);
       } else {
          bytes = 0;
          iax_ie_append(ied, IAX_IE_FWBLOCKDATA);
       }
       if (bytes == bs)
          res = 0;
       else
          res = 1;
       break;
    }
    AST_LIST_UNLOCK(&firmwares);
    return res;
 }
iax_firmware_get_version()
int iax_firmware_get_version (const char * device_name, uint16_t * version)
Definition at line 263 of file firmware.c.
References AST_LIST_LOCK, AST_LIST_TRAVERSE, AST_LIST_UNLOCK, ast_strlen_zero, ast_iax2_firmware_header::devname, iax_firmware::fwh, iax_firmware::list, NULL, and ast_iax2_firmware_header::version.
Referenced by update_registry().
 {
    struct iax_firmware *cur = NULL;
    if (ast_strlen_zero(dev))
       return 0;
    AST_LIST_LOCK(&firmwares);
    AST_LIST_TRAVERSE(&firmwares, cur, list) {
       if (!strcmp(dev, (const char *) cur->fwh->devname)) {
          *version = ntohs(cur->fwh->version);
          AST_LIST_UNLOCK(&firmwares);
          return 1;
       }
    }
    AST_LIST_UNLOCK(&firmwares);
    return 0;
 }
iax_firmware_reload()
void iax_firmware_reload (void)
Definition at line 206 of file firmware.c.
References ast_config_AST_DATA_DIR, AST_LIST_LOCK, AST_LIST_REMOVE_CURRENT, AST_LIST_TRAVERSE, AST_LIST_TRAVERSE_SAFE_BEGIN, AST_LIST_TRAVERSE_SAFE_END, AST_LIST_UNLOCK, ast_log, ast_verb, iax_firmware::dead, destroy_firmware(), errno, IAX_FIRMWARE_SUBDIR, iax_firmware::list, LOG_WARNING, NULL, PATH_MAX, and try_firmware().
Referenced by load_module(), and reload_config().
 {
    struct iax_firmware *cur = NULL;
    DIR *fwd;
    struct dirent *de;
    char fn[PATH_MAX + sizeof(IAX_FIRMWARE_SUBDIR) + sizeof(de->d_name)];
    AST_LIST_LOCK(&firmwares);
    /* Mark all as dead */
    AST_LIST_TRAVERSE(&firmwares, cur, list) {
       cur->dead = 1;
    }
    /* Now that we have marked them dead... load new ones */
    snprintf(fn, sizeof(fn), "%s%s", ast_config_AST_DATA_DIR, IAX_FIRMWARE_SUBDIR);
    fwd = opendir(fn);
    if (fwd) {
       while((de = readdir(fwd))) {
          if (de->d_name[0] != '.') {
             snprintf(fn, sizeof(fn), "%s%s/%s",
                ast_config_AST_DATA_DIR, IAX_FIRMWARE_SUBDIR, de->d_name);
             if (!try_firmware(fn)) {
                ast_verb(2, "Loaded firmware '%s'\n", de->d_name);
             }
          }
       }
       closedir(fwd);
    } else {
       ast_log(LOG_WARNING, "Error opening firmware directory '%s': %s\n", fn, strerror(errno));
    }
    /* Clean up leftovers */
    AST_LIST_TRAVERSE_SAFE_BEGIN(&firmwares, cur, list) {
       if (!cur->dead)
          continue;
       AST_LIST_REMOVE_CURRENT(list);
       destroy_firmware(cur);
    }
    AST_LIST_TRAVERSE_SAFE_END;
    AST_LIST_UNLOCK(&firmwares);
 }
iax_firmware_traverse()
void iax_firmware_traverse (const char * prefix, int(*)(struct ast_iax2_firmware_header *header, void *user_data) callback, void * user_data)
iax_firmware_unload()
void iax_firmware_unload (void)
Definition at line 250 of file firmware.c.
References AST_LIST_LOCK, AST_LIST_REMOVE_CURRENT, AST_LIST_TRAVERSE_SAFE_BEGIN, AST_LIST_TRAVERSE_SAFE_END, AST_LIST_UNLOCK, destroy_firmware(), iax_firmware::list, and NULL.
Referenced by __unload_module().
 {
    struct iax_firmware *cur = NULL;
    AST_LIST_LOCK(&firmwares);
    AST_LIST_TRAVERSE_SAFE_BEGIN(&firmwares, cur, list) {
       AST_LIST_REMOVE_CURRENT(list);
       destroy_firmware(cur);
    }
    AST_LIST_TRAVERSE_SAFE_END;
    AST_LIST_UNLOCK(&firmwares);
 }