Asterisk - The Open Source Telephony Project: pbx_switch.c File Reference
pbx_switch.c File Reference
PBX switch routines.
#include "asterisk.h"
#include "asterisk/_private.h"
#include "asterisk/cli.h"
#include "asterisk/linkedlists.h"
#include "asterisk/pbx.h"
#include "pbx_private.h"
Data Structures
struct switches
Functions
int ast_register_switch (struct ast_switch *sw)
Register an alternative dialplan switch.
void ast_unregister_switch (struct ast_switch *sw)
Unregister an alternative switch.
static char * handle_show_switches (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
handle_show_switches: CLI support for listing registered dial plan switches
int load_pbx_switch (void)
struct ast_switch * pbx_findswitch (const char *sw)
static void unload_pbx_switch (void)
Variables
static struct ast_cli_entry sw_cli []
static struct switches switches = { .first = NULL, .last = NULL, .lock = { PTHREAD_RWLOCK_INITIALIZER , NULL, {1, 0} } , }
Detailed Description
PBX switch routines.
Author
Corey Farrell git@c.nosp@m.fwar.nosp@m.e.com
Definition in file pbx_switch.c.
Function Documentation
ast_register_switch()
int ast_register_switch (struct ast_switch * sw)
Register an alternative dialplan switch.
Parameters
sw switch to register
This function registers a populated ast_switch structure with the asterisk switching architecture.
Return values
0 success
non-zero failure
Definition at line 58 of file pbx_switch.c.
References ast_log, AST_RWLIST_INSERT_TAIL, AST_RWLIST_TRAVERSE, AST_RWLIST_UNLOCK, AST_RWLIST_WRLOCK, ast_switch::list, LOG_WARNING, ast_switch::name, and tmp().
Referenced by load_module().
 {
    struct ast_switch *tmp;
    AST_RWLIST_WRLOCK(&switches);
    AST_RWLIST_TRAVERSE(&switches, tmp, list) {
       if (!strcasecmp(tmp->name, sw->name)) {
          AST_RWLIST_UNLOCK(&switches);
          ast_log(LOG_WARNING, "Switch '%s' already found\n", sw->name);
          return -1;
       }
    }
    AST_RWLIST_INSERT_TAIL(&switches, sw, list);
    AST_RWLIST_UNLOCK(&switches);
    return 0;
 }
ast_unregister_switch()
void ast_unregister_switch (struct ast_switch * sw)
Unregister an alternative switch.
Parameters
sw switch to unregister
Unregisters a switch from asterisk.
Returns
nothing
Definition at line 76 of file pbx_switch.c.
References AST_RWLIST_REMOVE, AST_RWLIST_UNLOCK, AST_RWLIST_WRLOCK, and ast_switch::list.
Referenced by __unload_module(), and unload_module().
 {
    AST_RWLIST_WRLOCK(&switches);
    AST_RWLIST_REMOVE(&switches, sw, list);
    AST_RWLIST_UNLOCK(&switches);
 }
handle_show_switches()
static char* handle_show_switches (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) static
handle_show_switches: CLI support for listing registered dial plan switches
Definition at line 84 of file pbx_switch.c.
References ast_cli(), AST_RWLIST_EMPTY, AST_RWLIST_RDLOCK, AST_RWLIST_TRAVERSE, AST_RWLIST_UNLOCK, CLI_GENERATE, CLI_INIT, CLI_SUCCESS, ast_cli_entry::command, ast_switch::description, ast_cli_args::fd, ast_switch::list, ast_switch::name, NULL, and ast_cli_entry::usage.
 {
    struct ast_switch *sw;
    switch (cmd) {
    case CLI_INIT:
       e->command = "core show switches";
       e->usage =
          "Usage: core show switches\n"
          "       List registered switches\n";
       return NULL;
    case CLI_GENERATE:
       return NULL;
    }
    AST_RWLIST_RDLOCK(&switches);
    if (AST_RWLIST_EMPTY(&switches)) {
       AST_RWLIST_UNLOCK(&switches);
       ast_cli(a->fd, "There are no registered alternative switches\n");
       return CLI_SUCCESS;
    }
    ast_cli(a->fd, "\n    -= Registered Asterisk Alternative Switches =-\n");
    AST_RWLIST_TRAVERSE(&switches, sw, list)
       ast_cli(a->fd, "%s: %s\n", sw->name, sw->description);
    AST_RWLIST_UNLOCK(&switches);
    return CLI_SUCCESS;
 }
load_pbx_switch()
int load_pbx_switch (void)
Provided by pbx_switch.c
Definition at line 125 of file pbx_switch.c.
References ARRAY_LEN, ast_cli_register_multiple, ast_register_cleanup(), and unload_pbx_switch().
Referenced by asterisk_daemon().
 {
    ast_cli_register_multiple(sw_cli, ARRAY_LEN(sw_cli));
    ast_register_cleanup(unload_pbx_switch);
    return 0;
 }
pbx_findswitch()
struct ast_switch* pbx_findswitch (const char * sw)
pbx_switch.c functions needed by pbx.c
Definition at line 40 of file pbx_switch.c.
References AST_RWLIST_RDLOCK, AST_RWLIST_TRAVERSE, AST_RWLIST_UNLOCK, ast_switch::list, and ast_switch::name.
Referenced by ast_check_timing(), and pbx_find_extension().
 {
    struct ast_switch *asw;
    AST_RWLIST_RDLOCK(&switches);
    AST_RWLIST_TRAVERSE(&switches, asw, list) {
       if (!strcasecmp(asw->name, sw))
          break;
    }
    AST_RWLIST_UNLOCK(&switches);
    return asw;
 }
unload_pbx_switch()
static void unload_pbx_switch (void) static
Definition at line 120 of file pbx_switch.c.
References ARRAY_LEN, and ast_cli_unregister_multiple().
Referenced by load_pbx_switch().
 {
    ast_cli_unregister_multiple(sw_cli, ARRAY_LEN(sw_cli));
 }
Variable Documentation
sw_cli
struct ast_cli_entry sw_cli[] static
Initial value:
= {
   { .handler =  handle_show_switches , .summary =  "Show alternative switches" ,},
}
Definition at line 116 of file pbx_switch.c.
switches
struct switches switches = { .first = NULL, .last = NULL, .lock = { PTHREAD_RWLOCK_INITIALIZER , NULL, {1, 0} } , } static