Asterisk - The Open Source Telephony Project: res_phoneprov.c File Reference
res_phoneprov.c File Reference
Phone provisioning application for the asterisk internal http server.
#include "asterisk.h"
#include <sys/ioctl.h>
#include <sys/socket.h>
#include <net/if.h>
#include "asterisk/channel.h"
#include "asterisk/file.h"
#include "asterisk/paths.h"
#include "asterisk/pbx.h"
#include "asterisk/cli.h"
#include "asterisk/module.h"
#include "asterisk/http.h"
#include "asterisk/utils.h"
#include "asterisk/app.h"
#include "asterisk/strings.h"
#include "asterisk/stringfields.h"
#include "asterisk/options.h"
#include "asterisk/config.h"
#include "asterisk/acl.h"
#include "asterisk/astobj2.h"
#include "asterisk/ast_version.h"
#include "asterisk/phoneprov.h"
Data Structures
struct extension
structure to hold extensions
struct http_route
structure to hold http routes (valid URIs, and the files they link to)
struct phone_profile
structure to hold phone profiles read from phoneprov.conf
struct phoneprov_file
structure to hold file data
struct phoneprov_provider
structure to hold config providers
struct user
structure to hold users read from users.conf
Macros
#define AST_API_MODULE
#define MAX_PROFILE_BUCKETS 17
#define MAX_PROVIDER_BUCKETS 17
#define MAX_ROUTE_BUCKETS 563
#define MAX_USER_BUCKETS 563
#define SIMPLE_CMP_FN(fname, stype, field)
Creates a compare function for a structure string field.
#define SIMPLE_HASH_FN(fname, stype, field)
Creates a hash function for a structure string field.
#define VAR_BUF_SIZE 4096
Functions
static int add_user_extension (struct user *user, struct extension *exten)
Add an extension to a user ordered by index/linenumber.
AST_MODULE_INFO (ASTERISK_GPL_KEY, AST_MODFLAG_GLOBAL_SYMBOLS|AST_MODFLAG_LOAD_ORDER, "HTTP Phone Provisioning",.support_level=AST_MODULE_SUPPORT_EXTENDED,.load=load_module,.unload=unload_module,.reload=reload,.load_pri=AST_MODPRI_CHANNEL_DEPEND,.requires="http",)
int ast_phoneprov_add_extension (char *provider_name, struct varshead *vars)
Adds an extension.
void ast_phoneprov_delete_extension (char *provider_name, char *macaddress)
Deletes an extension.
void ast_phoneprov_delete_extensions (char *provider_name)
Deletes all extensions for this provider.
int ast_phoneprov_provider_register (char *provider_name, ast_phoneprov_load_users_cb load_users)
Registers a config provider to phoneprov.
void ast_phoneprov_provider_unregister (char *provider_name)
Unegisters a config provider from phoneprov and frees its resources.
const char * ast_phoneprov_std_variable_lookup (enum ast_phoneprov_std_variables var)
Returns the string respresentation of a phoneprov standard variable.
static struct extension * build_extension (const char *name, struct varshead *vars)
static void build_profile (const char *name, struct ast_variable *v)
Build a phone profile and add it to the list of phone profiles.
static void build_route (struct phoneprov_file *pp_file, struct phone_profile *profile, struct user *user, char *uri)
Build a route structure and add it to the list of available http routes.
static struct user * build_user (const char *mac, struct phone_profile *profile, char *provider_name)
Build and return a user structure based on gathered config data.
static int build_user_routes (struct user *user)
Add an http route for dynamic files attached to the profile of the user.
static struct extension * delete_extension (struct extension *exten)
static void delete_file (struct phoneprov_file *file)
static void delete_profiles (void)
Delete all phone profiles, freeing their memory.
static void delete_providers (void)
Delete all providers.
static void delete_routes (void)
Delete all http routes, freeing their memory.
static void delete_users (void)
Delete all users.
static int extension_delete_cb (void *obj, void *arg, void *data, int flags)
static int extensions_delete_cb (void *obj, void *arg, int flags)
static struct phone_profile * find_profile (const char *name)
Return a phone profile looked up by name.
static struct phoneprov_provider * find_provider (char *name)
static struct user * find_user (const char *macaddress)
Return a user looked up by name.
static struct varshead * get_defaults (void)
static char * handle_show_routes (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
CLI command to list static and dynamic routes.
static int http_route_cmp_fn (void *obj, void *arg, int flags)
static int http_route_hash_fn (const void *obj, const int flags)
static int load_common (void)
static int load_file (const char *filename, char **ret)
Read a TEXT file into a string and return the length.
static int load_module (void)
Load the module.
static int load_users (void)
static int lookup_iface (const char *iface, struct in_addr *address)
static int phone_profile_cmp_fn (void *obj, void *arg, int flags)
static int phone_profile_hash_fn (const void *obj, const int flags)
static int phoneprov_callback (struct ast_tcptls_session_instance *ser, const struct ast_http_uri *urih, const char *uri, enum ast_http_method method, struct ast_variable *get_vars, struct ast_variable *headers)
Callback that is executed everytime an http request is received by this module.
static int pp_each_extension_helper (struct ast_channel *chan, const char *cmd, char *data, char *buf, struct ast_str **bufstr, int len)
A dialplan function that can be used to output a template for each extension attached to a user.
static int pp_each_extension_read (struct ast_channel *chan, const char *cmd, char *data, char *buf, size_t len)
static int pp_each_extension_read2 (struct ast_channel *chan, const char *cmd, char *data, struct ast_str **buf, ssize_t len)
static int pp_each_user_helper (struct ast_channel *chan, char *data, char *buf, struct ast_str **bufstr, int len)
A dialplan function that can be used to print a string for each phoneprov user.
static int pp_each_user_read (struct ast_channel *chan, const char *cmd, char *data, char *buf, size_t len)
static int pp_each_user_read2 (struct ast_channel *chan, const char *cmd, char *data, struct ast_str **buf, ssize_t len)
static void profile_destructor (void *obj)
static void provider_destructor (void *obj)
static int reload (void)
static void route_destructor (void *obj)
static int route_list_cb (void *obj, void *arg, void *data, int flags)
static int routes_delete_cb (void *obj, void *arg, int flags)
static void set_timezone_variables (struct varshead *headp, const char *zone)
Set all timezone-related variables based on a zone (i.e. America/New_York)
static int unload_module (void)
static struct phone_profile * unref_profile (struct phone_profile *prof)
static struct http_route * unref_route (struct http_route *route)
static struct user * unref_user (struct user *user)
static int user_cmp_fn (void *obj, void *arg, int flags)
static void user_destructor (void *obj)
Free all memory associated with a user.
static int user_hash_fn (const void *obj, const int flags)
Variables
static struct in_addr __ourip = { .s_addr = 0x00000000, }
for use in lookup_iface
struct ao2_container * http_routes
static struct ast_http_uri phoneprovuri
static struct ast_cli_entry pp_cli []
static struct ast_custom_function pp_each_extension_function
static struct ast_custom_function pp_each_user_function
static const char * pp_general_lookup []
static const char * pp_user_lookup []
struct ao2_container * profiles
struct ao2_container * providers
struct ao2_container * users
static const char * variable_lookup []
Detailed Description
Phone provisioning application for the asterisk internal http server.
Author
Matthew Brooks mbroo.nosp@m.ks@d.nosp@m.igium.nosp@m..com
Terry Wilson twils.nosp@m.on@d.nosp@m.igium.nosp@m..com
George Joseph georg.nosp@m.e.jo.nosp@m.seph@.nosp@m.fair.nosp@m.view5.nosp@m..com
Definition in file res_phoneprov.c.
Macro Definition Documentation
AST_API_MODULE
#define AST_API_MODULE
Definition at line 45 of file res_phoneprov.c.
MAX_PROFILE_BUCKETS
#define MAX_PROFILE_BUCKETS 17
Definition at line 81 of file res_phoneprov.c.
Referenced by load_module().
MAX_PROVIDER_BUCKETS
#define MAX_PROVIDER_BUCKETS 17
Definition at line 80 of file res_phoneprov.c.
Referenced by load_module().
MAX_ROUTE_BUCKETS
#define MAX_ROUTE_BUCKETS 563
Definition at line 82 of file res_phoneprov.c.
Referenced by load_module().
MAX_USER_BUCKETS
#define MAX_USER_BUCKETS 563
Definition at line 83 of file res_phoneprov.c.
Referenced by load_module().
SIMPLE_CMP_FN
#define SIMPLE_CMP_FN (fname, stype, field)
Creates a compare function for a structure string field.
Parameters
fname The name to use for the function
stype The structure type
field The field in the structure to compare
SIMPLE_CMP_FN(mystruct, myfield) will produce a function named mystruct_cmp_fn which compares mystruct->myfield.
Definition at line 157 of file res_phoneprov.c.
SIMPLE_HASH_FN
#define SIMPLE_HASH_FN (fname, stype, field)
Creates a hash function for a structure string field.
Parameters
fname The name to use for the function
stype The structure type
field The field in the structure to hash
SIMPLE_HASH_FN(mystruct, myfield) will produce a function named mystruct_hash_fn which hashes mystruct->myfield.
Definition at line 128 of file res_phoneprov.c.
VAR_BUF_SIZE
#define VAR_BUF_SIZE 4096
Definition at line 86 of file res_phoneprov.c.
Function Documentation
add_user_extension()
static int add_user_extension (struct user * user, struct extension * exten) static
Add an extension to a user ordered by index/linenumber.
Definition at line 798 of file res_phoneprov.c.
 {
    struct ast_var_t *pvar, *var2;
    struct ast_str *str = ast_str_create(16);
    if (!str) {
       return -1;
    }
    /* Append profile variables here, and substitute variables on profile
     * setvars, so that we can use user specific variables in them */
    AST_VAR_LIST_TRAVERSE(user->profile->headp, pvar) {
       if (ast_var_find(exten->headp, pvar->name)) {
          continue;
       }
       ast_str_substitute_variables_varshead(&str, 0, exten->headp, pvar->value);
       if ((var2 = ast_var_assign(pvar->name, ast_str_buffer(str)))) {
          AST_VAR_LIST_INSERT_TAIL(exten->headp, var2);
       }
    }
    ast_free(str);
    if (AST_LIST_EMPTY(&user->extensions)) {
       AST_LIST_INSERT_HEAD(&user->extensions, exten, entry);
    } else {
       struct extension *exten_iter;
       AST_LIST_TRAVERSE_SAFE_BEGIN(&user->extensions, exten_iter, entry) {
          if (exten->index < exten_iter->index) {
             AST_LIST_INSERT_BEFORE_CURRENT(exten, entry);
          } else if (exten->index == exten_iter->index) {
             ast_log(LOG_WARNING, "Duplicate linenumber=%d for %s\n", exten->index, user->macaddress);
             return -1;
          } else if (!AST_LIST_NEXT(exten_iter, entry)) {
             AST_LIST_INSERT_TAIL(&user->extensions, exten, entry);
AST_MODULE_INFO()
AST_MODULE_INFO (ASTERISK_GPL_KEY , AST_MODFLAG_GLOBAL_SYMBOLS| AST_MODFLAG_LOAD_ORDER, "HTTP Phone Provisioning" , . support_level = AST_MODULE_SUPPORT_EXTENDED, . load = load_module, . unload = unload_module, . reload = reload, . load_pri = AST_MODPRI_CHANNEL_DEPEND, . requires = "http")
Referenced by ast_beep_stop(), ast_cel_backend_register(), ast_manager_event_blob_create(), ast_sounds_get_index_for_file(), chan_misdn_log(), do_reload(), find_member_by_queuename_and_interface(), handle_cli_realtime_mysql_status(), handle_cli_realtime_pgsql_status(), load_module(), load_values_config(), ooh323_convert_hangupcause_h323ToAsterisk(), realtime_ldap_status(), reload(), reload_module(), unload_module(), and vm_msg_play().
ast_phoneprov_add_extension()
int ast_phoneprov_add_extension (char * provider_name, struct varshead * vars)
Adds an extension.
Parameters
provider_name The name of the provider
defaults An ast_vat_t linked list of the extension's variables. The list is automatically cloned and it must contain at least MACADDRESS and USERNAME entries.
Return values
0 if successful
non-zero if failure
Definition at line 1614 of file res_phoneprov.c.
Referenced by users_apply_handler().
 {
    RAII_VAR(struct phoneprov_provider *, provider, NULL, ao2_cleanup);
    RAII_VAR(struct user *, user, NULL, ao2_cleanup);
    RAII_VAR(struct phone_profile *, profile, NULL, ao2_cleanup);
    struct extension *exten;
    char *profile_name;
    char *mac;
    char *username;
    if (ast_strlen_zero(provider_name)) {
       ast_log(LOG_ERROR, "Provider name can't be empty.\n");
       return -1;
    }
    if (!vars) {
       ast_log(LOG_ERROR, "Variable list can't be empty.\n");
       return -1;
    }
    username = ast_var_find(vars, variable_lookup[AST_PHONEPROV_STD_USERNAME]);
    if (!username) {
       ast_log(LOG_ERROR, "Extension name can't be empty.\n");
       return -1;
    }
    mac = ast_var_find(vars, variable_lookup[AST_PHONEPROV_STD_MAC]);
    if (!mac) {
       ast_log(LOG_ERROR, "MAC Address can't be empty.\n");
       return -1;
    }
    provider = find_provider(provider_name);
    if (!provider) {
       ast_log(LOG_ERROR, "Provider '%s' wasn't found in the registry.\n", provider_name);
       return -1;
    }
    profile_name = ast_var_find(vars,
       variable_lookup[AST_PHONEPROV_STD_PROFILE]);
    if (!profile_name) {
       ast_log(LOG_ERROR, "No profile could be found for user '%s' - skipping.\n", username);
       return -1;
    }
    if (!(profile = find_profile(profile_name))) {
       ast_log(LOG_ERROR, "Could not look up profile '%s' - skipping.\n", profile_name);
       return -1;
    }
    if (!(user = find_user(mac))) {
       if (!(user = build_user(mac, profile, provider_name))) {
          ast_log(LOG_ERROR, "Could not create user for '%s' - skipping\n", mac);
          return -1;
       }
       if (!(exten = build_extension(username, vars))) {
          ast_log(LOG_ERROR, "Could not create extension for '%s' - skipping\n", user->macaddress);
          return -1;
       }
       if (add_user_extension(user, exten)) {
          ast_log(LOG_WARNING, "Could not add extension '%s' to user '%s'\n", exten->name, user->macaddress);
          exten = delete_extension(exten);
          return -1;
       }
       if (build_user_routes(user)) {
          ast_log(LOG_WARNING, "Could not create http routes for '%s' - skipping\n", user->macaddress);
          return -1;
       }
       ao2_link(users, user);
    } else {
       if (strcmp(provider_name, user->provider_name)) {
          ast_log(LOG_ERROR, "MAC address '%s' was already added by provider '%s' - skipping\n", user->macaddress, user->provider_name);
          return -1;
       }
       if (!(exten = build_extension(username, vars))) {
          ast_log(LOG_ERROR, "Could not create extension for '%s' - skipping\n", user->macaddress);
          return -1;
       }
       if (add_user_extension(user, exten)) {
          ast_log(LOG_WARNING, "Could not add extension '%s' to user '%s'\n", exten->name, user->macaddress);
ast_phoneprov_delete_extension()
void ast_phoneprov_delete_extension (char * provider_name, char * macaddress)
Deletes an extension.
Parameters
provider_name The name of the provider
macaddress The mac address of the extension
Definition at line 1585 of file res_phoneprov.c.
References CMP_MATCH.
Referenced by phoneprov_destroy().
{
       return CMP_MATCH;
    }
    return 0;
 }
 void ast_phoneprov_delete_extension(char *provider_name, char *macaddress)
 {
ast_phoneprov_delete_extensions()
void ast_phoneprov_delete_extensions (char * provider_name)
Deletes all extensions for this provider.
Parameters
provider_name The name of the provider
Definition at line 1595 of file res_phoneprov.c.
 {
ast_phoneprov_provider_register()
int ast_phoneprov_provider_register (char * provider_name, ast_phoneprov_load_users_cb load_users)
Registers a config provider to phoneprov.
Parameters
provider_name The name of the provider
load_users Callback that gathers user variables then loads them by calling ast_phoneprov_add_extension once for each extension.
Return values
0 if successful
non-zero if failure
Definition at line 1514 of file res_phoneprov.c.
References ao2_alloc, ao2_link, ao2_ref, ast_log, ast_string_field_init, ast_string_field_set, ast_strlen_zero, find_provider(), phoneprov_provider::load_users, LOG_ERROR, LOG_WARNING, NULL, provider, provider_destructor(), var, and variable_lookup.
Referenced by load_module(), and reload_module().
{
       return NULL;
    }
    return variable_lookup[var];
 }
 int ast_phoneprov_provider_register(char *provider_name,
    ast_phoneprov_load_users_cb load_users)
 {
    struct phoneprov_provider *provider;
    if (ast_strlen_zero(provider_name)) {
       ast_log(LOG_ERROR, "Provider name can't be empty.\n");
       return -1;
    }
    if (!providers) {
       ast_log(LOG_WARNING, "Provider '%s' cannot be registered: res_phoneprov not loaded.\n", provider_name);
       return -1;
    }
    provider = find_provider(provider_name);
    if (provider) {
       ast_log(LOG_ERROR, "There is already a provider registered named '%s'.\n", provider_name);
       ao2_ref(provider, -1);
       return -1;
    }
    provider = ao2_alloc(sizeof(struct phoneprov_provider), provider_destructor);
    if (!provider) {
       ast_log(LOG_ERROR, "Unable to allocate sufficient memory for provider '%s'.\n", provider_name);
       return -1;
    }
    if (ast_string_field_init(provider, 32)) {
       ao2_ref(provider, -1);
       ast_log(LOG_ERROR, "Unable to allocate sufficient memory for provider '%s' stringfields.\n", provider_name);
       return -1;
    }
    ast_string_field_set(provider, provider_name, provider_name);
    provider->load_users = load_users;
    ao2_link(providers, provider);
    ao2_ref(provider, -1);
    if (provider->load_users()) {
ast_phoneprov_provider_unregister()
void ast_phoneprov_provider_unregister (char * provider_name)
Unegisters a config provider from phoneprov and frees its resources.
Parameters
provider_name The name of the provider
Definition at line 1604 of file res_phoneprov.c.
References ao2_callback, extensions_delete_cb(), OBJ_MULTIPLE, OBJ_NODATA, and OBJ_UNLINK.
Referenced by reload_module(), and unload_module().
                {
       return;
    }
    ao2_callback(users, OBJ_UNLINK | OBJ_NODATA | OBJ_MULTIPLE, extensions_delete_cb, provider_name);
 }
 void ast_phoneprov_provider_unregister(char *provider_name)
 {
ast_phoneprov_std_variable_lookup()
const char* ast_phoneprov_std_variable_lookup (enum ast_phoneprov_std_variables var)
Returns the string respresentation of a phoneprov standard variable.
Parameters
var One of enum ast_phoneprov_std_variables
Returns
The string representation or NULL if not found.
Definition at line 1505 of file res_phoneprov.c.
Referenced by load_endpoint(), and users_apply_handler().
 {
build_extension()
static struct extension* build_extension (const char * name, struct varshead * vars) static
Definition at line 681 of file res_phoneprov.c.
 {
    struct extension *exten;
    const char *tmp;
    if (!(exten = ast_calloc_with_stringfields(1, struct extension, 32))) {
       return NULL;
    }
    ast_string_field_set(exten, name, name);
    exten->headp = ast_var_list_clone(vars);
    if (!exten->headp) {
       ast_log(LOG_ERROR, "Unable to clone variables for extension '%s'\n", name);
       delete_extension(exten);
       return NULL;
    }
    tmp = ast_var_find(exten->headp, variable_lookup[AST_PHONEPROV_STD_LINENUMBER]);
    if (!tmp) {
       AST_VAR_LIST_INSERT_TAIL(exten->headp,
          ast_var_assign(variable_lookup[AST_PHONEPROV_STD_LINENUMBER], "1"));
       exten->index = 1;
    } else {
       sscanf(tmp, "%d", &exten->index);
    }
    if (!ast_var_find(exten->headp, variable_lookup[AST_PHONEPROV_STD_LINEKEYS])) {
       AST_VAR_LIST_INSERT_TAIL(exten->headp,
          ast_var_assign(variable_lookup[AST_PHONEPROV_STD_LINEKEYS], "1"));
build_profile()
static void build_profile (const char * name, struct ast_variable * v) static
Build a phone profile and add it to the list of phone profiles.
Parameters
name the name of the profile
v ast_variable from parsing phoneprov.conf
Definition at line 580 of file res_phoneprov.c.
References ao2_alloc, args, AST_APP_ARG, ast_calloc_with_stringfields, AST_DECLARE_APP_ARGS, ast_http_ftype2mtype(), AST_LIST_HEAD_INIT_NOLOCK, AST_LIST_INSERT_TAIL, AST_NONSTANDARD_APP_ARGS, AST_STANDARD_APP_ARGS, ast_string_field_build, ast_string_field_init, ast_string_field_set, ast_strip(), ast_strlen_zero, ast_var_assign, ast_var_list_create(), AST_VAR_LIST_INSERT_TAIL(), build_route(), phone_profile::default_mime_type, phone_profile::dynamic_files, format, phoneprov_file::format, phone_profile::headp, phoneprov_file::mime_type, ast_variable::name, ast_variable::next, NULL, profile_destructor(), S_OR, phone_profile::static_files, phone_profile::staticdir, unref_profile(), and ast_variable::value.
 {
    struct phone_profile *profile;
    if (!(profile = ao2_alloc(sizeof(*profile), profile_destructor))) {
       return;
    }
    if (ast_string_field_init(profile, 32)) {
       profile = unref_profile(profile);
       return;
    }
    if (!(profile->headp = ast_var_list_create())) {
       profile = unref_profile(profile);
       return;
    }
    AST_LIST_HEAD_INIT_NOLOCK(&profile->static_files);
    AST_LIST_HEAD_INIT_NOLOCK(&profile->dynamic_files);
    ast_string_field_set(profile, name, name);
    for (; v; v = v->next) {
       if (!strcasecmp(v->name, "mime_type")) {
          ast_string_field_set(profile, default_mime_type, v->value);
       } else if (!strcasecmp(v->name, "setvar")) {
          char value_copy[strlen(v->value) + 1];
          AST_DECLARE_APP_ARGS(args,
             AST_APP_ARG(varname);
             AST_APP_ARG(varval);
          );
          strcpy(value_copy, v->value); /* safe */
          AST_NONSTANDARD_APP_ARGS(args, value_copy, '=');
          do {
             if (ast_strlen_zero(args.varname) || ast_strlen_zero(args.varval))
                break;
             args.varname = ast_strip(args.varname);
             args.varval = ast_strip(args.varval);
             if (ast_strlen_zero(args.varname) || ast_strlen_zero(args.varval))
                break;
             AST_VAR_LIST_INSERT_TAIL(profile->headp, ast_var_assign(args.varname, args.varval));
          } while (0);
       } else if (!strcasecmp(v->name, "staticdir")) {
          ast_string_field_set(profile, staticdir, v->value);
       } else {
          struct phoneprov_file *pp_file;
          char *file_extension;
          char value_copy[strlen(v->value) + 1];
          AST_DECLARE_APP_ARGS(args,
             AST_APP_ARG(filename);
             AST_APP_ARG(mimetype);
          );
          if (!(pp_file = ast_calloc_with_stringfields(1, struct phoneprov_file, 32))) {
             profile = unref_profile(profile);
             return;
          }
          if ((file_extension = strrchr(pp_file->format, '.')))
             file_extension++;
          strcpy(value_copy, v->value); /* safe */
          AST_STANDARD_APP_ARGS(args, value_copy);
          /* Mime type order of preference
           * 1) Specific mime-type defined for file in profile
           * 2) Mime determined by extension
           * 3) Default mime type specified in profile
           * 4) text/plain
           */
          ast_string_field_set(pp_file, mime_type, S_OR(args.mimetype,
             (S_OR(S_OR(ast_http_ftype2mtype(file_extension), profile->default_mime_type), "text/plain"))));
          if (!strcasecmp(v->name, "static_file")) {
             ast_string_field_set(pp_file, format, args.filename);
             ast_string_field_build(pp_file, template, "%s%s", profile->staticdir, args.filename);
             AST_LIST_INSERT_TAIL(&profile->static_files, pp_file, entry);
             /* Add a route for the static files, as their filenames won't change per-user */
             build_route(pp_file, profile, NULL, NULL);
          } else {
             ast_string_field_set(pp_file, format, v->name);
             ast_string_field_set(pp_file, template, args.filename);
             AST_LIST_INSERT_TAIL(&profile->dynamic_files, pp_file, entry);
          }
build_route()
static void build_route (struct phoneprov_file * pp_file, struct phone_profile * profile, struct user * user, char * uri) static
Build a route structure and add it to the list of available http routes.
Parameters
pp_file File to link to the route
user User to link to the route (NULL means static route)
uri URI of the route
Definition at line 507 of file res_phoneprov.c.
References ao2_alloc, ao2_link, ast_log, ast_string_field_init, ast_string_field_set, http_route::file, phoneprov_file::format, LOG_ERROR, http_route::profile, route_destructor(), S_OR, unref_route(), user, and http_route::user.
Referenced by build_profile(), and build_user_routes().
 {
    struct http_route *route;
    if (!(route = ao2_alloc(sizeof(*route), route_destructor))) {
       return;
    }
    if (ast_string_field_init(route, 32)) {
       ast_log(LOG_ERROR, "Couldn't create string fields for %s\n", pp_file->format);
       route = unref_route(route);
       return;
    }
    ast_string_field_set(route, uri, S_OR(uri, pp_file->format));
    route->user = user;
    route->file = pp_file;
    route->profile = profile;
build_user()
static struct user* build_user (const char * mac, struct phone_profile * profile, char * provider_name) static
Build and return a user structure based on gathered config data.
Definition at line 776 of file res_phoneprov.c.
 {
    struct user *user;
    if (!(user = ao2_alloc(sizeof(*user), user_destructor))) {
       return NULL;
    }
    if (ast_string_field_init(user, 64)) {
       user = unref_user(user);
       return NULL;
    }
build_user_routes()
static int build_user_routes (struct user * user) static
Add an http route for dynamic files attached to the profile of the user.
Definition at line 843 of file res_phoneprov.c.
References AST_LIST_FIRST, AST_LIST_TRAVERSE, ast_str_buffer(), ast_str_create, ast_str_substitute_variables_varshead(), build_route(), phone_profile::dynamic_files, user::extensions, phoneprov_file::format, user::profile, and str.
 {
    struct phoneprov_file *pp_file;
    struct ast_str *str;
    if (!(str = ast_str_create(16))) {
       return -1;
    }
    AST_LIST_TRAVERSE(&user->profile->dynamic_files, pp_file, entry) {
delete_extension()
static struct extension* delete_extension (struct extension * exten) static
Definition at line 672 of file res_phoneprov.c.
Referenced by user_destructor().
 {
delete_file()
static void delete_file (struct phoneprov_file * file) static
Definition at line 388 of file res_phoneprov.c.
Referenced by profile_destructor().
 {
delete_profiles()
static void delete_profiles (void) static
Delete all phone profiles, freeing their memory.
Definition at line 567 of file res_phoneprov.c.
 {
    if (!profiles) {
       return;
delete_providers()
static void delete_providers (void) static
Delete all providers.
Definition at line 373 of file res_phoneprov.c.
 {
    if (!providers) {
       return;
delete_routes()
static void delete_routes (void) static
Delete all http routes, freeing their memory.
Definition at line 493 of file res_phoneprov.c.
 {
    if (!http_routes) {
       return;
delete_users()
static void delete_users (void) static
Delete all users.
Definition at line 766 of file res_phoneprov.c.
 {
extension_delete_cb()
static int extension_delete_cb (void * obj, void * arg, void * data, int flags) static
Definition at line 1573 of file res_phoneprov.c.
References CMP_MATCH.
{
       return 0;
    }
    return CMP_MATCH;
 }
 static int extension_delete_cb(void *obj, void *arg, void *data, int flags)
 {
    struct user *user = obj;
    char *provider_name = data;
extensions_delete_cb()
static int extensions_delete_cb (void * obj, void * arg, int flags) static
Definition at line 1563 of file res_phoneprov.c.
Referenced by ast_phoneprov_provider_unregister().
 {
find_profile()
static struct phone_profile* find_profile (const char * name) static
Return a phone profile looked up by name.
Definition at line 539 of file res_phoneprov.c.
 {
find_provider()
static struct phoneprov_provider* find_provider (char * name) static
Definition at line 367 of file res_phoneprov.c.
Referenced by ast_phoneprov_provider_register().
 {
find_user()
static struct user* find_user (const char * macaddress) static
Return a user looked up by name.
Definition at line 727 of file res_phoneprov.c.
References ao2_cleanup, and NULL.
Referenced by pp_each_extension_helper().
 {
    ao2_cleanup(user);
    return NULL;
get_defaults()
static struct varshead* get_defaults (void) static
Definition at line 1191 of file res_phoneprov.c.
References ast_config_destroy(), ast_config_load, ast_inet_ntoa(), ast_log, AST_PHONEPROV_STD_EXTENSION_LENGTH, AST_PHONEPROV_STD_PROFILE, AST_PHONEPROV_STD_SERVER, AST_PHONEPROV_STD_SERVER_IFACE, AST_PHONEPROV_STD_SERVER_PORT, AST_PHONEPROV_STD_VOICEMAIL_EXTEN, ast_var_assign, ast_var_list_create(), ast_var_list_destroy(), AST_VAR_LIST_INSERT_TAIL(), ast_variable_browse(), ast_variable_retrieve(), CONFIG_STATUS_FILEINVALID, LOG_ERROR, LOG_WARNING, lookup_iface(), ast_variable::name, ast_variable::next, NULL, pp_general_lookup, pp_user_lookup, S_OR, value, ast_variable::value, var, and variable_lookup.
 {
    struct ast_config *phoneprov_cfg, *cfg = CONFIG_STATUS_FILEINVALID;
    const char *value;
    struct ast_variable *v;
    struct ast_var_t *var;
    struct ast_flags config_flags = { 0 };
    struct varshead *defaults = ast_var_list_create();
    if (!defaults) {
       ast_log(LOG_ERROR, "Unable to create default var list.\n");
       return NULL;
    }
    if (!(phoneprov_cfg = ast_config_load("phoneprov.conf", config_flags))
       || phoneprov_cfg == CONFIG_STATUS_FILEINVALID) {
       ast_log(LOG_ERROR, "Unable to load config phoneprov.conf\n");
       ast_var_list_destroy(defaults);
       return NULL;
    }
    value = ast_variable_retrieve(phoneprov_cfg, "general", pp_general_lookup[AST_PHONEPROV_STD_SERVER]);
    if (!value) {
       struct in_addr addr;
       value = ast_variable_retrieve(phoneprov_cfg, "general", pp_general_lookup[AST_PHONEPROV_STD_SERVER_IFACE]);
       if (value) {
          lookup_iface(value, &addr);
          value = ast_inet_ntoa(addr);
       }
    }
    if (value) {
       var = ast_var_assign(variable_lookup[AST_PHONEPROV_STD_SERVER], value);
       AST_VAR_LIST_INSERT_TAIL(defaults, var);
    } else {
       ast_log(LOG_WARNING, "Unable to find a valid server address or name.\n");
    }
    value = ast_variable_retrieve(phoneprov_cfg, "general", pp_general_lookup[AST_PHONEPROV_STD_SERVER_PORT]);
    if (!value) {
       if ((cfg = ast_config_load("sip.conf", config_flags)) && cfg != CONFIG_STATUS_FILEINVALID) {
          value = ast_variable_retrieve(cfg, "general", "bindport");
       }
    }
    var = ast_var_assign(variable_lookup[AST_PHONEPROV_STD_SERVER_PORT], S_OR(value, "5060"));
    if (cfg && cfg != CONFIG_STATUS_FILEINVALID) {
       ast_config_destroy(cfg);
    }
    AST_VAR_LIST_INSERT_TAIL(defaults, var);
    value = ast_variable_retrieve(phoneprov_cfg, "general", pp_general_lookup[AST_PHONEPROV_STD_PROFILE]);
    if (!value) {
       ast_log(LOG_ERROR, "Unable to load default profile.\n");
       ast_config_destroy(phoneprov_cfg);
       ast_var_list_destroy(defaults);
       return NULL;
    }
    var = ast_var_assign(variable_lookup[AST_PHONEPROV_STD_PROFILE], value);
    AST_VAR_LIST_INSERT_TAIL(defaults, var);
    ast_config_destroy(phoneprov_cfg);
    if (!(cfg = ast_config_load("users.conf", config_flags)) || cfg == CONFIG_STATUS_FILEINVALID) {
       ast_log(LOG_ERROR, "Unable to load users.conf\n");
       ast_var_list_destroy(defaults);
       return NULL;
    }
    /* Go ahead and load global variables from users.conf so we can append to profiles */
    for (v = ast_variable_browse(cfg, "general"); v; v = v->next) {
       if (!strcasecmp(v->name, pp_user_lookup[AST_PHONEPROV_STD_VOICEMAIL_EXTEN])) {
          var = ast_var_assign(variable_lookup[AST_PHONEPROV_STD_VOICEMAIL_EXTEN], v->value);
          AST_VAR_LIST_INSERT_TAIL(defaults, var);
       }
       if (!strcasecmp(v->name, pp_user_lookup[AST_PHONEPROV_STD_EXTENSION_LENGTH])) {
          var = ast_var_assign(variable_lookup[AST_PHONEPROV_STD_EXTENSION_LENGTH], v->value);
handle_show_routes()
static char* handle_show_routes (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) static
CLI command to list static and dynamic routes.
Definition at line 1149 of file res_phoneprov.c.
 {
    int fd = a->fd;
    switch(cmd) {
    case CLI_INIT:
       e->command = "phoneprov show routes";
       e->usage =
          "Usage: phoneprov show routes\n"
          "       Lists all registered phoneprov http routes.\n";
       return NULL;
    case CLI_GENERATE:
       return NULL;
    }
    /* This currently iterates over routes twice, but it is the only place I've needed
     * to really separate static an dynamic routes, so I've just left it this way. */
    ast_cli(a->fd, "Static routes\n\n");
    ast_cli(a->fd, FORMATS, "Profile", "Relative URI", "Physical location");
    ao2_callback_data(http_routes, OBJ_NODATA | OBJ_MULTIPLE, route_list_cb, &fd, NULL);
http_route_cmp_fn()
static int http_route_cmp_fn (void * obj, void * arg, int flags) static
Definition at line 332 of file res_phoneprov.c.
Referenced by load_module().
 {
http_route_hash_fn()
static int http_route_hash_fn (const void * obj, const int flags) static
Definition at line 331 of file res_phoneprov.c.
Referenced by load_module().
 {
load_common()
static int load_common (void) static
Definition at line 1343 of file res_phoneprov.c.
Referenced by load_module().
 {
    struct ast_config *phoneprov_cfg;
    struct ast_flags config_flags = { 0 };
    char *cat;
    if (!(phoneprov_cfg = ast_config_load("phoneprov.conf", config_flags))
       || phoneprov_cfg == CONFIG_STATUS_FILEINVALID) {
       ast_log(LOG_ERROR, "Unable to load config phoneprov.conf\n");
       return -1;
    }
    cat = NULL;
    while ((cat = ast_category_browse(phoneprov_cfg, cat))) {
       if (!strcasecmp(cat, "general")) {
          continue;
       }
       build_profile(cat, ast_variable_browse(phoneprov_cfg, cat));
    }
    ast_config_destroy(phoneprov_cfg);
load_file()
static int load_file (const char * filename, char ** ret) static
Read a TEXT file into a string and return the length.
Definition at line 395 of file res_phoneprov.c.
Referenced by make_ari_stubs::main(), and pp_each_extension_helper().
 {
    int len = 0;
    FILE *f;
    if (!(f = fopen(filename, "r"))) {
       *ret = NULL;
       return -1;
    }
    fseek(f, 0, SEEK_END);
    len = ftell(f);
    fseek(f, 0, SEEK_SET);
    if (!(*ret = ast_malloc(len + 1))) {
       fclose(f);
       return -2;
    }
    if (len != fread(*ret, sizeof(char), len, f)) {
       fclose(f);
       ast_free(*ret);
       *ret = NULL;
       return -3;
    }
    fclose(f);
load_module()
static int load_module (void) static
Load the module.
Module loading including tests for configuration or dependencies. This function can return AST_MODULE_LOAD_FAILURE, AST_MODULE_LOAD_DECLINE, or AST_MODULE_LOAD_SUCCESS. If a dependency or environment variable fails tests return AST_MODULE_LOAD_FAILURE. If the module can not load the configuration file or other non-critical problem return AST_MODULE_LOAD_DECLINE. On success return AST_MODULE_LOAD_SUCCESS.
Definition at line 1409 of file res_phoneprov.c.
References AO2_ALLOC_OPT_LOCK_MUTEX, ao2_container_alloc_hash, ARRAY_LEN, ast_cli_register_multiple, ast_custom_function_register, ast_http_uri_link(), ast_log, AST_MODULE_LOAD_DECLINE, ast_phoneprov_provider_register(), error(), http_route_cmp_fn(), http_route_hash_fn(), load_common(), phoneprov_provider::load_users, LOG_ERROR, LOG_WARNING, MAX_PROFILE_BUCKETS, MAX_PROVIDER_BUCKETS, MAX_ROUTE_BUCKETS, MAX_USER_BUCKETS, NULL, phone_profile_hash_fn(), user_cmp_fn(), and user_hash_fn().
 {
    profiles = ao2_container_alloc_hash(AO2_ALLOC_OPT_LOCK_MUTEX, 0, MAX_PROFILE_BUCKETS,
       phone_profile_hash_fn, NULL, phone_profile_cmp_fn);
    if (!profiles) {
       ast_log(LOG_ERROR, "Unable to allocate profiles container.\n");
       return AST_MODULE_LOAD_DECLINE;
    }
    http_routes = ao2_container_alloc_hash(AO2_ALLOC_OPT_LOCK_MUTEX, 0, MAX_ROUTE_BUCKETS,
       http_route_hash_fn, NULL, http_route_cmp_fn);
    if (!http_routes) {
       ast_log(LOG_ERROR, "Unable to allocate routes container.\n");
       goto error;
    }
    if (load_common()) {
       ast_log(LOG_ERROR, "Unable to load provisioning profiles.\n");
       goto error;
    }
    users = ao2_container_alloc_hash(AO2_ALLOC_OPT_LOCK_MUTEX, 0, MAX_USER_BUCKETS,
       user_hash_fn, NULL, user_cmp_fn);
    if (!users) {
       ast_log(LOG_ERROR, "Unable to allocate users container.\n");
       goto error;
    }
    providers = ao2_container_alloc_hash(AO2_ALLOC_OPT_LOCK_MUTEX, 0,
       MAX_PROVIDER_BUCKETS, phoneprov_provider_hash_fn, NULL, phoneprov_provider_cmp_fn);
    if (!providers) {
       ast_log(LOG_ERROR, "Unable to allocate providers container.\n");
       goto error;
    }
    /* Register ourselves as the provider for sip.conf/users.conf */
    if (ast_phoneprov_provider_register(SIPUSERS_PROVIDER_NAME, load_users)) {
       ast_log(LOG_WARNING, "Unable register sip/users config provider.  Others may succeed.\n");
    }
    ast_http_uri_link(&phoneprovuri);
    ast_custom_function_register(&pp_each_user_function);
    ast_custom_function_register(&pp_each_extension_function);
    ast_cli_register_multiple(pp_cli, ARRAY_LEN(pp_cli));
load_users()
static int load_users (void) static
Definition at line 1273 of file res_phoneprov.c.
 {
    struct ast_config *cfg;
    char *cat;
    const char *value;
    struct ast_flags config_flags = { 0 };
    struct varshead *defaults = get_defaults();
    if (!defaults) {
       ast_log(LOG_WARNING, "Unable to load default variables.\n");
       return -1;
    }
    if (!(cfg = ast_config_load("users.conf", config_flags))
       || cfg == CONFIG_STATUS_FILEINVALID) {
       ast_log(LOG_WARNING, "Unable to load users.conf\n");
       ast_var_list_destroy(defaults);
       return -1;
    }
    cat = NULL;
    while ((cat = ast_category_browse(cfg, cat))) {
       const char *tmp;
       int i;
       struct ast_var_t *varx;
       struct ast_var_t *vard;
       if (strcasecmp(cat, "general") && strcasecmp(cat, "authentication")) {
          struct varshead *variables = ast_var_list_create();
          if (!((tmp = ast_variable_retrieve(cfg, cat, "autoprov")) && ast_true(tmp))) {
             ast_var_list_destroy(variables);
             continue;
          }
          /* Transfer the standard variables */
          for (i = 0; i < AST_PHONEPROV_STD_VAR_LIST_LENGTH; i++) {
             if (pp_user_lookup[i]) {
                value = ast_variable_retrieve(cfg, cat, pp_user_lookup[i]);
                if (value) {
                   varx = ast_var_assign(variable_lookup[i],
                      value);
                   AST_VAR_LIST_INSERT_TAIL(variables, varx);
                }
             }
          }
          if (!ast_var_find(variables, variable_lookup[AST_PHONEPROV_STD_MAC])) {
             ast_log(LOG_WARNING, "autoprov set for %s, but no mac address - skipping.\n", cat);
             ast_var_list_destroy(variables);
             continue;
          }
          /* Apply defaults */
          AST_VAR_LIST_TRAVERSE(defaults, vard) {
             if (ast_var_find(variables, vard->name)) {
                continue;
             }
             varx = ast_var_assign(vard->name, vard->value);
             AST_VAR_LIST_INSERT_TAIL(variables, varx);
          }
lookup_iface()
static int lookup_iface (const char * iface, struct in_addr * address) static
Definition at line 337 of file res_phoneprov.c.
References __ourip, ast_copy_string(), ast_log, errno, LOG_ERROR, and LOG_WARNING.
Referenced by get_defaults().
 {
    int mysock, res = 0;
    struct ifreq ifr;
    struct sockaddr_in *sin;
    memset(&ifr, 0, sizeof(ifr));
    ast_copy_string(ifr.ifr_name, iface, sizeof(ifr.ifr_name));
    mysock = socket(PF_INET, SOCK_DGRAM, IPPROTO_IP);
    if (mysock < 0) {
       ast_log(LOG_ERROR, "Failed to create socket: %s\n", strerror(errno));
       return -1;
    }
    res = ioctl(mysock, SIOCGIFADDR, &ifr);
    close(mysock);
    if (res < 0) {
       ast_log(LOG_WARNING, "Unable to get IP of %s: %s\n", iface, strerror(errno));
       memcpy(address, &__ourip, sizeof(__ourip));
       return -1;
    } else {
       sin = (struct sockaddr_in *)&ifr.ifr_addr;
phone_profile_cmp_fn()
static int phone_profile_cmp_fn (void * obj, void * arg, int flags) static
Definition at line 309 of file res_phoneprov.c.
 {
phone_profile_hash_fn()
static int phone_profile_hash_fn (const void * obj, const int flags) static
Definition at line 308 of file res_phoneprov.c.
Referenced by load_module().
 {
phoneprov_callback()
static int phoneprov_callback (struct ast_tcptls_session_instance * ser, const struct ast_http_uri * urih, const char * uri, enum ast_http_method method, struct ast_variable * get_vars, struct ast_variable * headers) static
Callback that is executed everytime an http request is received by this module.
Definition at line 862 of file res_phoneprov.c.
 {
    struct http_route *route;
    struct ast_str *result;
    char path[PATH_MAX];
    char *file = NULL;
    char *server;
    int len;
    int fd;
    struct ast_str *http_header;
    if (method != AST_HTTP_GET && method != AST_HTTP_HEAD) {
       ast_http_error(ser, 501, "Not Implemented", "Attempt to use unimplemented / unsupported method");
       return 0;
    }
    if (!(route = ao2_find(http_routes, uri, OBJ_SEARCH_KEY))) {
       goto out404;
    }
    snprintf(path, sizeof(path), "%s/phoneprov/%s", ast_config_AST_DATA_DIR, route->file->template);
    if (!route->user) { /* Static file */
       fd = open(path, O_RDONLY);
       if (fd < 0) {
          goto out500;
       }
       len = lseek(fd, 0, SEEK_END);
       lseek(fd, 0, SEEK_SET);
       if (len < 0) {
          ast_log(LOG_WARNING, "Could not load file: %s (%d)\n", path, len);
          close(fd);
          goto out500;
       }
       http_header = ast_str_create(80);
       ast_str_set(&http_header, 0, "Content-type: %s\r\n",
          route->file->mime_type);
       ast_http_send(ser, method, 200, NULL, http_header, NULL, fd, 0);
       close(fd);
       route = unref_route(route);
       return 0;
    } else { /* Dynamic file */
       struct ast_str *tmp;
       len = load_file(path, &file);
       if (len < 0) {
          ast_log(LOG_WARNING, "Could not load file: %s (%d)\n", path, len);
          if (file) {
             ast_free(file);
          }
          goto out500;
       }
       if (!file) {
          goto out500;
       }
       if (!(tmp = ast_str_create(len))) {
          if (file) {
             ast_free(file);
          }
          goto out500;
       }
       /* Unless we are overridden by serveriface or serveraddr, we set the SERVER variable to
        * the IP address we are listening on that the phone contacted for this config file */
       server = ast_var_find(AST_LIST_FIRST(&route->user->extensions)->headp,
          variable_lookup[AST_PHONEPROV_STD_SERVER]);
       if (!server) {
          union {
             struct sockaddr sa;
             struct sockaddr_in sa_in;
          } name;
          socklen_t namelen = sizeof(name.sa);
          int res;
          if ((res = getsockname(ast_iostream_get_fd(ser->stream), &name.sa, &namelen))) {
             ast_log(LOG_WARNING, "Could not get server IP, breakage likely.\n");
          } else {
             struct extension *exten_iter;
             const char *newserver = ast_inet_ntoa(name.sa_in.sin_addr);
             AST_LIST_TRAVERSE(&route->user->extensions, exten_iter, entry) {
                AST_VAR_LIST_INSERT_TAIL(exten_iter->headp,
                   ast_var_assign(variable_lookup[AST_PHONEPROV_STD_SERVER], newserver));
             }
          }
       }
       ast_str_substitute_variables_varshead(&tmp, 0, AST_LIST_FIRST(&route->user->extensions)->headp, file);
       ast_free(file);
       http_header = ast_str_create(80);
       ast_str_set(&http_header, 0, "Content-type: %s\r\n",
          route->file->mime_type);
       if (!(result = ast_str_create(512))) {
          ast_log(LOG_ERROR, "Could not create result string!\n");
          if (tmp) {
             ast_free(tmp);
          }
          ast_free(http_header);
          goto out500;
       }
       ast_str_append(&result, 0, "%s", ast_str_buffer(tmp));
       ast_http_send(ser, method, 200, NULL, http_header, result, 0, 0);
       ast_free(tmp);
       route = unref_route(route);
       return 0;
    }
 out404:
    ast_http_error(ser, 404, "Not Found", uri);
pp_each_extension_helper()
static int pp_each_extension_helper (struct ast_channel * chan, const char * cmd, char * data, char * buf, struct ast_str ** bufstr, int len) static
A dialplan function that can be used to output a template for each extension attached to a user.
Definition at line 1054 of file res_phoneprov.c.
References args, AST_APP_ARG, ast_build_string(), ast_config_AST_DATA_DIR, AST_DECLARE_APP_ARGS, ast_free, AST_LIST_TRAVERSE, ast_log, AST_STANDARD_APP_ARGS, ast_str_append(), ast_str_buffer(), ast_str_create, ast_str_substitute_variables_varshead(), ast_strlen_zero, exten, user::extensions, make_ari_stubs::file, find_user(), extension::headp, len(), load_file(), LOG_WARNING, ast_custom_function::name, PATH_MAX, pp_each_user_read(), pp_each_user_read2(), str, and user.
Referenced by pp_each_extension_read2().
{
    .name = "PP_EACH_USER",
    .read = pp_each_user_read,
    .read2 = pp_each_user_read2,
 };
 /*! \brief A dialplan function that can be used to output a template for each extension attached to a user */
 static int pp_each_extension_helper(struct ast_channel *chan, const char *cmd, char *data, char *buf, struct ast_str **bufstr, int len)
 {
    struct user *user;
    struct extension *exten;
    char path[PATH_MAX];
    char *file;
    int filelen;
    struct ast_str *str;
    AST_DECLARE_APP_ARGS(args,
       AST_APP_ARG(mac);
       AST_APP_ARG(template);
    );
    AST_STANDARD_APP_ARGS(args, data);
    if (ast_strlen_zero(args.mac) || ast_strlen_zero(args.template)) {
       ast_log(LOG_WARNING, "PP_EACH_EXTENSION requries both a macaddress and template filename.\n");
       return 0;
    }
    if (!(user = find_user(args.mac))) {
       ast_log(LOG_WARNING, "Could not find user with mac = '%s'\n", args.mac);
       return 0;
    }
    snprintf(path, sizeof(path), "%s/phoneprov/%s", ast_config_AST_DATA_DIR, args.template);
    filelen = load_file(path, &file);
    if (filelen < 0) {
       ast_log(LOG_WARNING, "Could not load file: %s (%d)\n", path, filelen);
       if (file) {
          ast_free(file);
       }
       return 0;
    }
    if (!file) {
       return 0;
    }
    if (!(str = ast_str_create(filelen))) {
       return 0;
    }
    AST_LIST_TRAVERSE(&user->extensions, exten, entry) {
       ast_str_substitute_variables_varshead(&str, 0, exten->headp, file);
       if (buf) {
          size_t slen = len;
          ast_build_string(&buf, &slen, "%s", ast_str_buffer(str));
       } else {
          ast_str_append(bufstr, len, "%s", ast_str_buffer(str));
       }
    }
pp_each_extension_read()
static int pp_each_extension_read (struct ast_channel * chan, const char * cmd, char * data, char * buf, size_t len) static
Definition at line 1115 of file res_phoneprov.c.
 {
pp_each_extension_read2()
static int pp_each_extension_read2 (struct ast_channel * chan, const char * cmd, char * data, struct ast_str ** buf, ssize_t len) static
Definition at line 1120 of file res_phoneprov.c.
References NULL, and pp_each_extension_helper().
 {
pp_each_user_helper()
static int pp_each_user_helper (struct ast_channel * chan, char * data, char * buf, struct ast_str ** bufstr, int len) static
A dialplan function that can be used to print a string for each phoneprov user.
Definition at line 997 of file res_phoneprov.c.
Referenced by pp_each_user_read2().
       :
    route = unref_route(route);
    ast_http_error(ser, 500, "Internal Error", "An internal error has occured.");
    return 0;
 }
 /*! \brief A dialplan function that can be used to print a string for each phoneprov user */
 static int pp_each_user_helper(struct ast_channel *chan, char *data, char *buf, struct ast_str **bufstr, int len)
 {
    char *tmp;
    struct ao2_iterator i;
    struct user *user;
    struct ast_str *str;
    AST_DECLARE_APP_ARGS(args,
       AST_APP_ARG(string);
       AST_APP_ARG(exclude_mac);
    );
    AST_STANDARD_APP_ARGS(args, data);
    if (!(str = ast_str_create(16))) {
       return -1;
    }
    /* Fix data by turning %{ into ${ */
    while ((tmp = strstr(args.string, "%{")))
       *tmp = '$';
    i = ao2_iterator_init(users, 0);
    while ((user = ao2_iterator_next(&i))) {
       if (!ast_strlen_zero(args.exclude_mac) && !strcasecmp(user->macaddress, args.exclude_mac)) {
          continue;
       }
       ast_str_substitute_variables_varshead(&str, len, AST_LIST_FIRST(&user->extensions)->headp, args.string);
       if (buf) {
          size_t slen = len;
          ast_build_string(&buf, &slen, "%s", ast_str_buffer(str));
       } else {
          ast_str_append(bufstr, len, "%s", ast_str_buffer(str));
       }
pp_each_user_read()
static int pp_each_user_read (struct ast_channel * chan, const char * cmd, char * data, char * buf, size_t len) static
Definition at line 1037 of file res_phoneprov.c.
Referenced by pp_each_extension_helper().
 {
pp_each_user_read2()
static int pp_each_user_read2 (struct ast_channel * chan, const char * cmd, char * data, struct ast_str ** buf, ssize_t len) static
Definition at line 1042 of file res_phoneprov.c.
References NULL, and pp_each_user_helper().
Referenced by pp_each_extension_helper().
 {
profile_destructor()
static void profile_destructor (void * obj) static
Definition at line 544 of file res_phoneprov.c.
References ao2_find, ast_free, AST_LIST_REMOVE_HEAD, ast_var_delete(), delete_file(), phone_profile::dynamic_files, ast_var_t::entries, make_ari_stubs::file, phone_profile::headp, OBJ_SEARCH_KEY, phone_profile::static_files, and var.
Referenced by build_profile().
 {
    return ao2_find(profiles, name, OBJ_SEARCH_KEY);
 }
 static void profile_destructor(void *obj)
 {
    struct phone_profile *profile = obj;
    struct phoneprov_file *file;
    struct ast_var_t *var;
    while ((file = AST_LIST_REMOVE_HEAD(&profile->static_files, entry))) {
       delete_file(file);
    }
    while ((file = AST_LIST_REMOVE_HEAD(&profile->dynamic_files, entry))) {
       delete_file(file);
    }
    while ((var = AST_LIST_REMOVE_HEAD(profile->headp, entries))) {
       ast_var_delete(var);
    }
provider_destructor()
static void provider_destructor (void * obj) static
Definition at line 382 of file res_phoneprov.c.
Referenced by ast_phoneprov_provider_register().
 {
reload()
static int reload (void) static
Definition at line 1462 of file res_phoneprov.c.
      :
    unload_module();
    return AST_MODULE_LOAD_DECLINE;
 }
 static int reload(void)
 {
    struct ao2_iterator i;
    struct phoneprov_provider *provider;
    /* Clean everything except the providers */
    delete_routes();
    delete_users();
    delete_profiles();
    /* Reload the profiles */
    if (load_common()) {
       ast_log(LOG_ERROR, "Unable to reload provisioning profiles.\n");
       unload_module();
       return AST_MODULE_LOAD_DECLINE;
    }
    /* For each provider, reload the users */
    ao2_lock(providers);
    i = ao2_iterator_init(providers, 0);
    for(; (provider = ao2_iterator_next(&i)); ao2_ref(provider, -1)) {
       if (provider->load_users()) {
          ast_log(LOG_ERROR, "Unable to load provider '%s' users. Reload aborted.\n", provider->provider_name);
          continue;
route_destructor()
static void route_destructor (void * obj) static
Definition at line 485 of file res_phoneprov.c.
Referenced by build_route().
 {
route_list_cb()
static int route_list_cb (void * obj, void * arg, void * data, int flags) static
Definition at line 1133 of file res_phoneprov.c.
References ast_cli(), http_route::file, phone_profile::name, http_route::profile, user::provider_name, phoneprov_file::template, http_route::uri, and http_route::user.
 {
    int fd = *(int *)arg;
    struct http_route *route = obj;
    if (data && route->user) {
       ast_cli(fd, FORMATD, route->user->provider_name, route->profile->name, route->uri, route->file->template);
routes_delete_cb()
static int routes_delete_cb (void * obj, void * arg, int flags) static
Definition at line 732 of file res_phoneprov.c.
References ao2_find, user::macaddress, OBJ_SEARCH_KEY, and http_route::user.
 {
    return ao2_find(users, macaddress, OBJ_SEARCH_KEY);
 }
 static int routes_delete_cb(void *obj, void *arg, int flags)
 {
    struct http_route *route = obj;
    struct user *user = route->user;
set_timezone_variables()
static void set_timezone_variables (struct varshead * headp, const char * zone) static
Set all timezone-related variables based on a zone (i.e. America/New_York)
Parameters
headp pointer to list of user variables
zone A time zone. NULL sets variables based on timezone of the machine
Definition at line 431 of file res_phoneprov.c.
References ast_get_dst_info(), ast_localtime(), ast_var_assign, AST_VAR_LIST_INSERT_TAIL(), ast_tm::tm_hour, ast_tm::tm_mday, and ast_tm::tm_mon.
 {
    time_t utc_time;
    int dstenable;
    time_t dststart;
    time_t dstend;
    struct ast_tm tm_info;
    int tzoffset;
    char buffer[21];
    struct timeval when;
    time(&utc_time);
    ast_get_dst_info(&utc_time, &dstenable, &dststart, &dstend, &tzoffset, zone);
    snprintf(buffer, sizeof(buffer), "%d", tzoffset);
    AST_VAR_LIST_INSERT_TAIL(headp, ast_var_assign("TZOFFSET", buffer));
    if (!dstenable) {
       return;
    }
    AST_VAR_LIST_INSERT_TAIL(headp, ast_var_assign("DST_ENABLE", "1"));
    when.tv_sec = dststart;
    ast_localtime(&when, &tm_info, zone);
    snprintf(buffer, sizeof(buffer), "%d", tm_info.tm_mon+1);
    AST_VAR_LIST_INSERT_TAIL(headp, ast_var_assign("DST_START_MONTH", buffer));
    snprintf(buffer, sizeof(buffer), "%d", tm_info.tm_mday);
    AST_VAR_LIST_INSERT_TAIL(headp, ast_var_assign("DST_START_MDAY", buffer));
    snprintf(buffer, sizeof(buffer), "%d", tm_info.tm_hour);
    AST_VAR_LIST_INSERT_TAIL(headp, ast_var_assign("DST_START_HOUR", buffer));
    when.tv_sec = dstend;
    ast_localtime(&when, &tm_info, zone);
    snprintf(buffer, sizeof(buffer), "%d", tm_info.tm_mon + 1);
    AST_VAR_LIST_INSERT_TAIL(headp, ast_var_assign("DST_END_MONTH", buffer));
    snprintf(buffer, sizeof(buffer), "%d", tm_info.tm_mday);
    AST_VAR_LIST_INSERT_TAIL(headp, ast_var_assign("DST_END_MDAY", buffer));
unload_module()
static int unload_module (void) static
Definition at line 1372 of file res_phoneprov.c.
 {
    ast_http_uri_unlink(&phoneprovuri);
    ast_custom_function_unregister(&pp_each_user_function);
    ast_custom_function_unregister(&pp_each_extension_function);
    ast_cli_unregister_multiple(pp_cli, ARRAY_LEN(pp_cli));
    /* This cleans up the sip.conf/users.conf provider (called specifically for clarity) */
    ast_phoneprov_provider_unregister(SIPUSERS_PROVIDER_NAME);
    /* This cleans up the framework which also cleans up the providers. */
    delete_profiles();
    ao2_cleanup(profiles);
    profiles = NULL;
    delete_routes();
    delete_users();
    ao2_cleanup(http_routes);
    http_routes = NULL;
    ao2_cleanup(users);
unref_profile()
static struct phone_profile* unref_profile (struct phone_profile * prof) static
Definition at line 531 of file res_phoneprov.c.
Referenced by build_profile(), and user_destructor().
 {
unref_route()
static struct http_route* unref_route (struct http_route * route) static
Definition at line 478 of file res_phoneprov.c.
Referenced by build_route().
 {
unref_user()
static struct user* unref_user (struct user * user) static
Definition at line 719 of file res_phoneprov.c.
 {
user_cmp_fn()
static int user_cmp_fn (void * obj, void * arg, int flags) static
Definition at line 320 of file res_phoneprov.c.
Referenced by load_module().
 {
user_destructor()
static void user_destructor (void * obj) static
Free all memory associated with a user.
Definition at line 745 of file res_phoneprov.c.
References AST_LIST_REMOVE_HEAD, CMP_MATCH, delete_extension(), exten, user::extensions, user::profile, and unref_profile().
{
       return CMP_MATCH;
    }
    return 0;
 }
 /*! \brief Free all memory associated with a user */
 static void user_destructor(void *obj)
 {
    struct user *user = obj;
    struct extension *exten;
    while ((exten = AST_LIST_REMOVE_HEAD(&user->extensions, entry))) {
       exten = delete_extension(exten);
    }
    if (user->profile) {
       user->profile = unref_profile(user->profile);
    }
user_hash_fn()
static int user_hash_fn (const void * obj, const int flags) static
Definition at line 319 of file res_phoneprov.c.
Referenced by load_module().
 {
Variable Documentation
__ourip
struct in_addr __ourip = { .s_addr = 0x00000000, } static
for use in lookup_iface
Definition at line 263 of file res_phoneprov.c.
Referenced by lookup_iface().
http_routes
struct ao2_container* http_routes
Definition at line 330 of file res_phoneprov.c.
phoneprovuri
struct ast_http_uri phoneprovuri static
Definition at line 1182 of file res_phoneprov.c.
pp_cli
struct ast_cli_entry pp_cli[] static
Initial value:
= {
   AST_CLI_DEFINE(handle_show_routes, "Show registered phoneprov http routes"),
}
Definition at line 1178 of file res_phoneprov.c.
pp_each_extension_function
struct ast_custom_function pp_each_extension_function static
Initial value:
= {
   .name = "PP_EACH_EXTENSION",
   .read = pp_each_extension_read,
   .read2 = pp_each_extension_read2,
}
Definition at line 1125 of file res_phoneprov.c.
pp_each_user_function
struct ast_custom_function pp_each_user_function static
Initial value:
= {
   .name = "PP_EACH_USER",
   .read = pp_each_user_read,
   .read2 = pp_each_user_read2,
}
Definition at line 1047 of file res_phoneprov.c.
pp_general_lookup
const char* pp_general_lookup[] static
Definition at line 236 of file res_phoneprov.c.
Referenced by get_defaults().
pp_user_lookup
const char* pp_user_lookup[] static
Definition at line 209 of file res_phoneprov.c.
Referenced by get_defaults().
profiles
struct ao2_container* profiles
Definition at line 307 of file res_phoneprov.c.
providers
struct ao2_container* providers
Definition at line 272 of file res_phoneprov.c.
Referenced by load_module(), prometheus_metrics_provider_register(), reload_module(), and unload_module().
users
struct ao2_container* users
Definition at line 318 of file res_phoneprov.c.
Referenced by load_users().
variable_lookup
const char* variable_lookup[] static
Definition at line 182 of file res_phoneprov.c.
Referenced by ast_phoneprov_provider_register(), and get_defaults().