Asterisk - The Open Source Telephony Project: pjsip_session.c File Reference
pjsip_session.c File Reference
#include "asterisk.h"
#include <pjsip.h>
#include <pjsip_ua.h>
#include <pjlib.h>
#include "asterisk/res_pjsip.h"
#include "asterisk/res_pjsip_session.h"
#include "include/res_pjsip_private.h"
#include "asterisk/linkedlists.h"
#include "asterisk/lock.h"
#include "asterisk/module.h"
Data Structures
struct session_supplements
Functions
int ast_sip_session_add_supplements (struct ast_sip_session *session)
Add supplements to a SIP session.
void ast_sip_session_register_supplement_with_module (struct ast_module *module, struct ast_sip_session_supplement *supplement)
Register a supplement to SIP session processing.
void ast_sip_session_remove_supplements (struct ast_sip_session *session)
Remove supplements from a SIP session.
void ast_sip_session_unregister_supplement (struct ast_sip_session_supplement *supplement)
Unregister a an supplement to SIP session processing.
static struct ast_sip_session_supplement * supplement_dup (const struct ast_sip_session_supplement *src)
Variables
struct session_supplements session_supplements = { .first = NULL, .last = NULL, .lock = { PTHREAD_RWLOCK_INITIALIZER , NULL, {1, 0} } , }
Function Documentation
ast_sip_session_add_supplements()
int ast_sip_session_add_supplements (struct ast_sip_session * session)
Add supplements to a SIP session.
Parameters
session The session to initialize
Definition at line 90 of file pjsip_session.c.
References AST_LIST_INSERT_TAIL, ast_module_ref, AST_RWLIST_RDLOCK, AST_RWLIST_TRAVERSE, AST_RWLIST_UNLOCK, copy(), lock, ast_sip_session_supplement::module, ast_sip_session_supplement::next, SCOPED_LOCK, supplement_dup(), and ast_sip_session::supplements.
Referenced by ast_sip_session_alloc().
 {
    struct ast_sip_session_supplement *iter;
    SCOPED_LOCK(lock, &session_supplements, AST_RWLIST_RDLOCK, AST_RWLIST_UNLOCK);
    AST_RWLIST_TRAVERSE(&session_supplements, iter, next) {
       struct ast_sip_session_supplement *copy = supplement_dup(iter);
       if (!copy) {
          return -1;
       }
       /* referenced session created. increasing module reference. */
       ast_module_ref(copy->module);
       AST_LIST_INSERT_TAIL(&session->supplements, copy, next);
    }
    return 0;
 }
ast_sip_session_register_supplement_with_module()
void ast_sip_session_register_supplement_with_module (struct ast_module * module, struct ast_sip_session_supplement * supplement)
Register a supplement to SIP session processing.
This allows for someone to insert themselves in the processing of SIP requests and responses. This, for example could allow for a module to set channel data based on headers in an incoming message. Similarly, a module could reject an incoming request if desired.
Parameters
module Referenced module(NULL safe)
supplement The supplement to register
Definition at line 35 of file pjsip_session.c.
References ast_assert, AST_RWLIST_INSERT_BEFORE_CURRENT, AST_RWLIST_INSERT_TAIL, AST_RWLIST_TRAVERSE_SAFE_BEGIN, AST_RWLIST_TRAVERSE_SAFE_END, AST_RWLIST_UNLOCK, AST_RWLIST_WRLOCK, AST_SIP_SESSION_BEFORE_MEDIA, lock, ast_sip_session_supplement::module, ast_sip_session_supplement::next, NULL, ast_sip_session_supplement::priority, ast_sip_session_supplement::response_priority, and SCOPED_LOCK.
 {
    struct ast_sip_session_supplement *iter;
    int inserted = 0;
    SCOPED_LOCK(lock, &session_supplements, AST_RWLIST_WRLOCK, AST_RWLIST_UNLOCK);
    ast_assert(supplement != NULL);
    supplement->module = module;
    if (!supplement->response_priority) {
       supplement->response_priority = AST_SIP_SESSION_BEFORE_MEDIA;
    }
    AST_RWLIST_TRAVERSE_SAFE_BEGIN(&session_supplements, iter, next) {
       if (iter->priority > supplement->priority) {
          AST_RWLIST_INSERT_BEFORE_CURRENT(supplement, next);
          inserted = 1;
          break;
       }
    }
    AST_RWLIST_TRAVERSE_SAFE_END;
    if (!inserted) {
       AST_RWLIST_INSERT_TAIL(&session_supplements, supplement, next);
    }
 }
ast_sip_session_remove_supplements()
void ast_sip_session_remove_supplements (struct ast_sip_session * session)
Remove supplements from a SIP session.
Parameters
session The session to remove
Definition at line 111 of file pjsip_session.c.
References ast_free, AST_LIST_REMOVE_HEAD, ast_module_unref, ast_sip_session_supplement::module, ast_sip_session_supplement::next, and ast_sip_session::supplements.
Referenced by session_destructor().
 {
    struct ast_sip_session_supplement *iter;
    if (!session) {
       return;
    }
    /* free the supplements */
    while ((iter = AST_LIST_REMOVE_HEAD(&session->supplements, next))) {
       if (iter->module) {
          /* referenced session closed. decreasing modue reference. */
          ast_module_unref(iter->module);
       }
       ast_free(iter);
    }
    return;
 }
ast_sip_session_unregister_supplement()
void ast_sip_session_unregister_supplement (struct ast_sip_session_supplement * supplement)
Unregister a an supplement to SIP session processing.
Parameters
supplement The supplement to unregister
Definition at line 63 of file pjsip_session.c.
References AST_RWLIST_REMOVE_CURRENT, AST_RWLIST_TRAVERSE_SAFE_BEGIN, AST_RWLIST_TRAVERSE_SAFE_END, AST_RWLIST_UNLOCK, AST_RWLIST_WRLOCK, lock, ast_sip_session_supplement::next, and SCOPED_LOCK.
Referenced by ast_res_pjsip_cleanup_message_filter(), load_module(), and unload_module().
 {
    struct ast_sip_session_supplement *iter;
    SCOPED_LOCK(lock, &session_supplements, AST_RWLIST_WRLOCK, AST_RWLIST_UNLOCK);
    AST_RWLIST_TRAVERSE_SAFE_BEGIN(&session_supplements, iter, next) {
       if (supplement == iter) {
          AST_RWLIST_REMOVE_CURRENT(next);
          break;
       }
    }
    AST_RWLIST_TRAVERSE_SAFE_END;
 }
supplement_dup()
static struct ast_sip_session_supplement* supplement_dup (const struct ast_sip_session_supplement * src) static
Definition at line 77 of file pjsip_session.c.
References ast_calloc, and NULL.
Referenced by ast_sip_session_add_supplements().
 {
    struct ast_sip_session_supplement *dst = ast_calloc(1, sizeof(*dst));
    if (!dst) {
       return NULL;
    }
    /* Will need to revisit if shallow copy becomes an issue */
    *dst = *src;
    return dst;
 }
Variable Documentation
session_supplements
struct session_supplements session_supplements = { .first = NULL, .last = NULL, .lock = { PTHREAD_RWLOCK_INITIALIZER , NULL, {1, 0} } , }