Asterisk - The Open Source Telephony Project: codec_lpc10.c File Reference
codec_lpc10.c File Reference
Module: Codecs
Translate between signed linear and LPC10 (Linear Predictor Code)
#include "asterisk.h"
#include "asterisk/translate.h"
#include "asterisk/config.h"
#include "asterisk/module.h"
#include "asterisk/utils.h"
#include "asterisk/linkedlists.h"
#include "lpc10/lpc10.h"
#include "asterisk/slin.h"
#include "ex_lpc10.h"
Data Structures
struct lpc10_coder_pvt
Macros
#define BUFFER_SAMPLES 8000
#define LPC10_BYTES_IN_COMPRESSED_FRAME (LPC10_BITS_IN_COMPRESSED_FRAME + 7)/8
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static void build_bits (unsigned char *c, INT32 *bits)
static void extract_bits (INT32 *bits, unsigned char *c)
static int lintolpc10_framein (struct ast_trans_pvt *pvt, struct ast_frame *f)
static struct ast_frame * lintolpc10_frameout (struct ast_trans_pvt *pvt)
static int load_module (void)
static int lpc10_dec_new (struct ast_trans_pvt *pvt)
static void lpc10_destroy (struct ast_trans_pvt *arg)
static int lpc10_enc_new (struct ast_trans_pvt *pvt)
static int lpc10tolin_framein (struct ast_trans_pvt *pvt, struct ast_frame *f)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_DEFAULT , .description = "LPC10 2.4kbps Coder/Decoder" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, }
static const struct ast_module_info * ast_module_info = &__mod_info
static struct ast_translator lintolpc10
static struct ast_translator lpc10tolin
Detailed Description
Translate between signed linear and LPC10 (Linear Predictor Code)
Definition in file codec_lpc10.c.
Macro Definition Documentation
BUFFER_SAMPLES
#define BUFFER_SAMPLES 8000
Definition at line 55 of file codec_lpc10.c.
Referenced by lintolpc10_framein(), and lpc10tolin_framein().
LPC10_BYTES_IN_COMPRESSED_FRAME
#define LPC10_BYTES_IN_COMPRESSED_FRAME (LPC10_BITS_IN_COMPRESSED_FRAME + 7)/8
Definition at line 53 of file codec_lpc10.c.
Referenced by lintolpc10_frameout(), and lpc10tolin_framein().
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 285 of file codec_lpc10.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 285 of file codec_lpc10.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 285 of file codec_lpc10.c.
build_bits()
static void build_bits (unsigned char * c, INT32 * bits) static
Definition at line 95 of file codec_lpc10.c.
References LPC10_BITS_IN_COMPRESSED_FRAME.
Referenced by lintolpc10_frameout().
 {
    unsigned char mask=0x80;
    int x;
    *c = 0;
    for (x=0;x<LPC10_BITS_IN_COMPRESSED_FRAME;x++) {
       if (bits[x])
          *c |= mask;
       mask = mask >> 1;
       if ((x % 8)==7) {
          c++;
          *c = 0;
          mask = 0x80;
       }
    }
 }
extract_bits()
static void extract_bits (INT32 * bits, unsigned char * c) static
Definition at line 81 of file codec_lpc10.c.
References LPC10_BITS_IN_COMPRESSED_FRAME.
Referenced by lpc10tolin_framein().
 {
    int x;
    for (x=0;x<LPC10_BITS_IN_COMPRESSED_FRAME;x++) {
       if (*c & (0x80 >> (x & 7)))
          bits[x] = 1;
       else
          bits[x] = 0;
       if ((x & 7) == 7)
          c++;
    }
 }
lintolpc10_framein()
static int lintolpc10_framein (struct ast_trans_pvt * pvt, struct ast_frame * f) static
Definition at line 145 of file codec_lpc10.c.
References ast_log, lpc10_coder_pvt::buf, BUFFER_SAMPLES, ast_frame::data, ast_frame::datalen, LOG_WARNING, ast_frame::ptr, ast_trans_pvt::pvt, ast_frame::samples, ast_trans_pvt::samples, and tmp().
 {
    struct lpc10_coder_pvt *tmp = pvt->pvt;
    /* Just add the frames to our stream */
    if (pvt->samples + f->samples > BUFFER_SAMPLES) {
       ast_log(LOG_WARNING, "Out of buffer space\n");
       return -1;
    }
    memcpy(tmp->buf + pvt->samples, f->data.ptr, f->datalen);
    pvt->samples += f->samples;
    return 0;
 }
lintolpc10_frameout()
static struct ast_frame* lintolpc10_frameout (struct ast_trans_pvt * pvt) static
Definition at line 159 of file codec_lpc10.c.
References AST_LIST_NEXT, ast_trans_frameout(), lpc10_coder_pvt::buf, build_bits(), lpc10_coder_pvt::enc, last, lpc10_coder_pvt::longer, lpc10_coder_pvt::lpc10, LPC10_BITS_IN_COMPRESSED_FRAME, LPC10_BYTES_IN_COMPRESSED_FRAME, lpc10_encode(), LPC10_SAMPLES_PER_FRAME, NULL, ast_trans_pvt::outbuf, ast_trans_pvt::pvt, result, ast_frame::samples, ast_trans_pvt::samples, tmp(), and ast_trans_pvt::uc.
 {
    struct lpc10_coder_pvt *tmp = pvt->pvt;
    struct ast_frame *result = NULL;
    struct ast_frame *last = NULL;
    int samples = 0; /* output samples */
    while (pvt->samples >= LPC10_SAMPLES_PER_FRAME) {
       struct ast_frame *current;
       float tmpbuf[LPC10_SAMPLES_PER_FRAME];
       INT32 bits[LPC10_BITS_IN_COMPRESSED_FRAME];  /* XXX what ??? */
       int x;
       /* Encode a frame of data */
       for (x=0;x<LPC10_SAMPLES_PER_FRAME;x++)
          tmpbuf[x] = (float)tmp->buf[x + samples] / 32768.0;
       lpc10_encode(tmpbuf, bits, tmp->lpc10.enc);
       build_bits(pvt->outbuf.uc, bits);
       samples += LPC10_SAMPLES_PER_FRAME;
       pvt->samples -= LPC10_SAMPLES_PER_FRAME;
       /* Use one of the two left over bits to record if this is a 22 or 23 ms frame...
          important for IAX use */
       tmp->longer = 1 - tmp->longer;
       current = ast_trans_frameout(pvt, LPC10_BYTES_IN_COMPRESSED_FRAME, LPC10_SAMPLES_PER_FRAME);
       if (!current) {
          continue;
       } else if (last) {
          AST_LIST_NEXT(last, frame_list) = current;
       } else {
          result = current;
       }
       last = current;
    }
    /* Move the data at the end of the buffer to the front */
    if (samples) {
       memmove(tmp->buf, tmp->buf + samples, pvt->samples * 2);
    }
    return result;
 }
load_module()
static int load_module (void) static
Definition at line 266 of file codec_lpc10.c.
References AST_MODFLAG_DEFAULT, AST_MODULE_INFO(), AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, AST_MODULE_SUPPORT_CORE, ast_register_translator, ASTERISK_GPL_KEY, and unload_module().
 {
    int res;
    res = ast_register_translator(&lpc10tolin);
    res |= ast_register_translator(&lintolpc10);
    if (res) {
       unload_module();
       return AST_MODULE_LOAD_DECLINE;
    }
    return AST_MODULE_LOAD_SUCCESS;
 }
lpc10_dec_new()
static int lpc10_dec_new (struct ast_trans_pvt * pvt) static
Definition at line 74 of file codec_lpc10.c.
References create_lpc10_decoder_state(), lpc10_coder_pvt::dec, lpc10_coder_pvt::lpc10, ast_trans_pvt::pvt, and tmp().
 {
    struct lpc10_coder_pvt *tmp = pvt->pvt;
    return (tmp->lpc10.dec = create_lpc10_decoder_state()) ? 0 : -1;
 }
lpc10_destroy()
static void lpc10_destroy (struct ast_trans_pvt * arg) static
Definition at line 204 of file codec_lpc10.c.
References ast_free, lpc10_coder_pvt::enc, lpc10_coder_pvt::lpc10, and ast_trans_pvt::pvt.
 {
    struct lpc10_coder_pvt *pvt = arg->pvt;
    /* Enc and DEC are both just allocated, so they can be freed */
    ast_free(pvt->lpc10.enc);
 }
lpc10_enc_new()
static int lpc10_enc_new (struct ast_trans_pvt * pvt) static
Definition at line 67 of file codec_lpc10.c.
References create_lpc10_encoder_state(), lpc10_coder_pvt::enc, lpc10_coder_pvt::lpc10, ast_trans_pvt::pvt, and tmp().
 {
    struct lpc10_coder_pvt *tmp = pvt->pvt;
    return (tmp->lpc10.enc = create_lpc10_encoder_state()) ? 0 : -1;
 }
lpc10tolin_framein()
static int lpc10tolin_framein (struct ast_trans_pvt * pvt, struct ast_frame * f) static
Definition at line 112 of file codec_lpc10.c.
References ast_log, BUFFER_SAMPLES, ast_frame::data, ast_frame::datalen, ast_trans_pvt::datalen, lpc10_coder_pvt::dec, extract_bits(), ast_trans_pvt::i16, len(), LOG_WARNING, lpc10_coder_pvt::lpc10, LPC10_BITS_IN_COMPRESSED_FRAME, LPC10_BYTES_IN_COMPRESSED_FRAME, lpc10_decode(), LPC10_SAMPLES_PER_FRAME, ast_trans_pvt::outbuf, ast_frame::ptr, ast_trans_pvt::pvt, ast_trans_pvt::samples, and tmp().
 {
    struct lpc10_coder_pvt *tmp = pvt->pvt;
    int16_t *dst = pvt->outbuf.i16;
    int len = 0;
    while (len + LPC10_BYTES_IN_COMPRESSED_FRAME <= f->datalen) {
       int x;
       float tmpbuf[LPC10_SAMPLES_PER_FRAME];
       INT32 bits[LPC10_BITS_IN_COMPRESSED_FRAME]; /* XXX see note */
       if (pvt->samples + LPC10_SAMPLES_PER_FRAME > BUFFER_SAMPLES) {
          ast_log(LOG_WARNING, "Out of buffer space\n");
          return -1;
       }
       extract_bits(bits, f->data.ptr + len);
       if (lpc10_decode(bits, tmpbuf, tmp->lpc10.dec)) {
          ast_log(LOG_WARNING, "Invalid lpc10 data\n");
          return -1;
       }
       for (x=0;x<LPC10_SAMPLES_PER_FRAME;x++) {
          /* Convert to a short between -1.0 and 1.0 */
          dst[pvt->samples + x] = (int16_t)(32768.0 * tmpbuf[x]);
       }
       pvt->samples += LPC10_SAMPLES_PER_FRAME;
       pvt->datalen += 2*LPC10_SAMPLES_PER_FRAME;
       len += LPC10_BYTES_IN_COMPRESSED_FRAME;
    }
    if (len != f->datalen)
       printf("Decoded %d, expected %d\n", len, f->datalen);
    return 0;
 }
unload_module()
static int unload_module (void) static
Definition at line 256 of file codec_lpc10.c.
References ast_unregister_translator().
Referenced by load_module().
 {
    int res;
    res = ast_unregister_translator(&lintolpc10);
    res |= ast_unregister_translator(&lpc10tolin);
    return res;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_DEFAULT , .description = "LPC10 2.4kbps Coder/Decoder" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, } static
Definition at line 285 of file codec_lpc10.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 285 of file codec_lpc10.c.
lintolpc10
struct ast_translator lintolpc10 static
Definition at line 233 of file codec_lpc10.c.
lpc10tolin
struct ast_translator lpc10tolin static
Definition at line 211 of file codec_lpc10.c.