Asterisk - The Open Source Telephony Project: alertpipe.h File Reference
alertpipe.h File Reference
#include "asterisk/utils.h"
Enumerations
enum ast_alert_status_t { AST_ALERT_READ_SUCCESS = 0, AST_ALERT_NOT_READABLE, AST_ALERT_READ_FAIL, AST_ALERT_READ_FATAL }
Functions
void ast_alertpipe_clear (int alert_pipe[2])
Sets the alert pipe file descriptors to default values.
void ast_alertpipe_close (int alert_pipe[2])
Close an alert pipe.
ast_alert_status_t ast_alertpipe_flush (int alert_pipe[2])
Consume all alerts written to the alert pipe.
int ast_alertpipe_init (int alert_pipe[2])
Initialize an alert pipe.
ast_alert_status_t ast_alertpipe_read (int alert_pipe[2])
Read an event from an alert pipe.
int ast_alertpipe_readable (int alert_pipe[2])
Determine if the alert pipe is readable.
int ast_alertpipe_readfd (int alert_pipe[2])
Get the alert pipe's read file descriptor.
void ast_alertpipe_swap (int alert_pipe_1[2], int alert_pipe_2[2])
Swap the file descriptors from two alert pipes.
int ast_alertpipe_writable (int alert_pipe[2])
Determine if the alert pipe is writable.
ssize_t ast_alertpipe_write (int alert_pipe[2])
Write an event to an alert pipe.
Enumeration Type Documentation
ast_alert_status_t
enum ast_alert_status_t
Enumerator
AST_ALERT_READ_SUCCESS
AST_ALERT_NOT_READABLE
AST_ALERT_READ_FAIL
AST_ALERT_READ_FATAL
Definition at line 24 of file alertpipe.h.
              {
    AST_ALERT_READ_SUCCESS = 0,
    AST_ALERT_NOT_READABLE,
    AST_ALERT_READ_FAIL,
    AST_ALERT_READ_FATAL,
 } ast_alert_status_t;
Function Documentation
ast_alertpipe_clear()
void ast_alertpipe_clear (int alert_pipe[2]) inline
Sets the alert pipe file descriptors to default values.
Since
13.16.0
Parameters
p a two-element array containing the alert pipe's file descriptors
Definition at line 97 of file alertpipe.h.
Referenced by ast_alertpipe_close(), ast_alertpipe_init(), and ast_channel_internal_alertpipe_clear().
 {
ast_alertpipe_close()
void ast_alertpipe_close (int alert_pipe[2])
Close an alert pipe.
Since
13.16.0
Parameters
p a two-element containing the alert pipe's file descriptors
Definition at line 79 of file alertpipe.c.
References ast_alertpipe_clear().
Referenced by ast_alertpipe_init(), ast_channel_internal_alertpipe_close(), bridge_channel_destroy(), and really_quit().
 {
 #ifdef HAVE_EVENTFD
    if (alert_pipe[0] == alert_pipe[1]) {
       if (alert_pipe[0] > -1) {
          close(alert_pipe[0]);
          ast_alertpipe_clear(alert_pipe);
       }
       return;
    }
 #endif
    if (alert_pipe[0] > -1) {
       close(alert_pipe[0]);
    }
    if (alert_pipe[1] > -1) {
       close(alert_pipe[1]);
    }
    ast_alertpipe_clear(alert_pipe);
 }
ast_alertpipe_flush()
ast_alert_status_t ast_alertpipe_flush (int alert_pipe[2])
Consume all alerts written to the alert pipe.
Since
13.16.0
Parameters
p a two-element array containing the alert pipe's file descriptors
Return values
AST_ALERT_READ_SUCCESS on success
AST_ALERT_NOT_READABLE if the alert pipe is not readable
AST_ALERT_READ_FATAL if the alert pipe's file descriptors are in blocking mode, or a read error occurs.
Definition at line 134 of file alertpipe.c.
References AST_ALERT_NOT_READABLE, AST_ALERT_READ_FAIL, AST_ALERT_READ_SUCCESS, ast_alertpipe_readable(), ast_log, errno, LOG_WARNING, and tmp().
Referenced by ast_channel_internal_alert_flush().
 {
    int bytes_read;
    uint64_t tmp[16];
    if (!ast_alertpipe_readable(alert_pipe)) {
       return AST_ALERT_NOT_READABLE;
    }
    /* Read the alertpipe until it is exhausted. */
    for (;;) {
       bytes_read = read(alert_pipe[0], tmp, sizeof(tmp));
       if (bytes_read < 0) {
          if (errno == EINTR) {
             continue;
          }
          if (errno == EAGAIN || errno == EWOULDBLOCK) {
             /*
              * Would block so nothing left to read.
              * This is the normal loop exit.
              */
             break;
          }
          ast_log(LOG_WARNING, "read() failed flushing alertpipe: %s\n",
             strerror(errno));
          return AST_ALERT_READ_FAIL;
       }
       if (!bytes_read) {
          /* Read nothing so we are done */
          break;
       }
    }
    return AST_ALERT_READ_SUCCESS;
 }
ast_alertpipe_init()
int ast_alertpipe_init (int alert_pipe[2])
Initialize an alert pipe.
Since
13.16.0
Parameters
p a two-element array to hold the alert pipe's file descriptors
Returns
non-zero if a failure occurred, zero otherwise.
Definition at line 38 of file alertpipe.c.
References ast_alertpipe_clear(), ast_alertpipe_close(), ast_fd_set_flags, ast_log, errno, and LOG_WARNING.
Referenced by ast_channel_internal_alertpipe_init(), asterisk_daemon(), and bridge_channel_internal_alloc().
 {
 #ifdef HAVE_EVENTFD
    int fd = eventfd(0, EFD_NONBLOCK | EFD_SEMAPHORE);
    if (fd > -1) {
       alert_pipe[0] = alert_pipe[1] = fd;
       return 0;
    }
    ast_log(LOG_WARNING, "Failed to create alert pipe with eventfd(), falling back to pipe(): %s\n",
       strerror(errno));
    ast_alertpipe_clear(alert_pipe);
 #endif
 #ifdef HAVE_PIPE2
    if (pipe2(alert_pipe, O_NONBLOCK)) {
       ast_log(LOG_WARNING, "Failed to create alert pipe: %s\n", strerror(errno));
       return -1;
    }
 #else
    if (pipe(alert_pipe)) {
       ast_log(LOG_WARNING, "Failed to create alert pipe: %s\n", strerror(errno));
       return -1;
    } else {
       if (ast_fd_set_flags(alert_pipe[0], O_NONBLOCK)
          || ast_fd_set_flags(alert_pipe[1], O_NONBLOCK)) {
          ast_alertpipe_close(alert_pipe);
          return -1;
       }
    }
 #endif
    return 0;
 }
ast_alertpipe_read()
ast_alert_status_t ast_alertpipe_read (int alert_pipe[2])
Read an event from an alert pipe.
Since
13.16.0
Parameters
p a two-element array containing the alert pipe's file descriptors
Return values
AST_ALERT_READ_SUCCESS on success
AST_ALERT_NOT_READABLE if the alert pipe is not readable
AST_ALERT_READ_FATAL if the alert pipe's file descriptors are in blocking mode, or a read error occurs.
Definition at line 102 of file alertpipe.c.
References AST_ALERT_NOT_READABLE, AST_ALERT_READ_FAIL, AST_ALERT_READ_SUCCESS, ast_alertpipe_readable(), ast_log, errno, LOG_WARNING, and tmp().
Referenced by ast_channel_internal_alert_read(), bridge_channel_handle_write(), and monitor_sig_flags().
 {
    uint64_t tmp;
    if (!ast_alertpipe_readable(alert_pipe)) {
       return AST_ALERT_NOT_READABLE;
    }
    if (read(alert_pipe[0], &tmp, sizeof(tmp)) < 0) {
       if (errno != EINTR && errno != EAGAIN) {
          ast_log(LOG_WARNING, "read() failed: %s\n", strerror(errno));
          return AST_ALERT_READ_FAIL;
       }
    }
    return AST_ALERT_READ_SUCCESS;
 }
ast_alertpipe_readable()
int ast_alertpipe_readable (int alert_pipe[2]) inline
Determine if the alert pipe is readable.
Since
13.16.0
Parameters
p a two-element array containing the alert pipe's file descriptors
Returns
non-zero if the alert pipe is readable, zero otherwise.
Definition at line 112 of file alertpipe.h.
Referenced by ast_alertpipe_flush(), ast_alertpipe_read(), and ast_channel_internal_alert_readable().
 {
ast_alertpipe_readfd()
int ast_alertpipe_readfd (int alert_pipe[2]) inline
Get the alert pipe's read file descriptor.
Since
13.16.0
Parameters
p a two-element array containing the alert pipe's file descriptors
Returns
-1 if the file descriptor is not initialized, a non-negative value otherwise.
Definition at line 143 of file alertpipe.h.
References SWAP.
Referenced by ast_channel_internal_alert_readfd().
 {
ast_alertpipe_swap()
void ast_alertpipe_swap (int alert_pipe_1[2], int alert_pipe_2[2]) inline
Swap the file descriptors from two alert pipes.
Since
13.16.0
Parameters
p1 a two-element array containing an alert pipe's file descriptors
p2 a two-element array containing an alert pipe's file descriptors
Definition at line 158 of file alertpipe.h.
Referenced by ast_channel_internal_alertpipe_swap().
ast_alertpipe_writable()
int ast_alertpipe_writable (int alert_pipe[2]) inline
Determine if the alert pipe is writable.
Since
13.16.0
Parameters
p a two-element array containing the alert pipe's file descriptors
Returns
non-zero if the alert pipe is writable, zero otherwise.
Definition at line 127 of file alertpipe.h.
Referenced by ast_alertpipe_write(), and ast_channel_alert_writable().
 {
ast_alertpipe_write()
ssize_t ast_alertpipe_write (int alert_pipe[2])
Write an event to an alert pipe.
Since
13.16.0
Parameters
p a two-element array containing the alert pipe's file descriptors
Return values
0 Success
1 Failure
Definition at line 120 of file alertpipe.c.
References ast_alertpipe_writable(), errno, and tmp().
Referenced by __quit_handler(), _hup_handler(), ast_bridge_channel_queue_frame(), and ast_channel_alert_write().
 {
    uint64_t tmp = 1;
    if (!ast_alertpipe_writable(alert_pipe)) {
       errno = EBADF;
       return 0;
    }
    /* preset errno in case returned size does not match */
    errno = EPIPE;
    return write(alert_pipe[1], &tmp, sizeof(tmp)) != sizeof(tmp);
 }