Asterisk - The Open Source Telephony Project: app_waitforsilence.c File Reference
app_waitforsilence.c File Reference
Dial plan applications
Wait for Silence.
#include "asterisk.h"
#include "asterisk/app.h"
#include "asterisk/file.h"
#include "asterisk/channel.h"
#include "asterisk/pbx.h"
#include "asterisk/dsp.h"
#include "asterisk/module.h"
#include "asterisk/format_cache.h"
Data Structures
struct wait_type
Functions
AST_MODULE_INFO_STANDARD_EXTENDED (ASTERISK_GPL_KEY, "Wait For Silence/Noise")
static int do_waiting (struct ast_channel *chan, int timereqd, time_t waitstart, int timeout, const struct wait_type *wait_for)
static int load_module (void)
static int unload_module (void)
static int waitfor_exec (struct ast_channel *chan, const char *data, const struct wait_type *wait_for)
static int waitfornoise_exec (struct ast_channel *chan, const char *data)
static int waitforsilence_exec (struct ast_channel *chan, const char *data)
Variables
static char * app_noise = "WaitForNoise"
static char * app_silence = "WaitForSilence"
static const struct wait_type wait_for_noise
static const struct wait_type wait_for_silence
Detailed Description
Wait for Silence.
Waits for up to 'x' milliseconds of silence, 'y' times
WaitForSilence(500,2) will wait for 1/2 second of silence, twice
WaitForSilence(1000,1) will wait for 1 second of silence, once
WaitForSilence(300,3,10) will wait for 300ms of silence, 3 times, and return after 10sec
Author
David C. Troy dave@.nosp@m.popv.nosp@m.ox.co.nosp@m.m
Wait For Noise The same as Wait For Silence but listenes noise on the chennel that is above
the pre-configured silence threshold from dsp.conf
Author
Philipp Skadorov skado.nosp@m.rov@.nosp@m.yahoo.nosp@m..com
Definition in file app_waitforsilence.c.
Function Documentation
AST_MODULE_INFO_STANDARD_EXTENDED()
AST_MODULE_INFO_STANDARD_EXTENDED (ASTERISK_GPL_KEY , "Wait For Silence/Noise")
Referenced by load_module().
do_waiting()
static int do_waiting (struct ast_channel * chan, int timereqd, time_t waitstart, int timeout, const struct wait_type * wait_for) static
Definition at line 154 of file app_waitforsilence.c.
References ao2_bump, ao2_cleanup, ast_channel_name(), ast_channel_readformat(), ast_debug, ast_dsp_free(), ast_dsp_get_threshold_from_settings(), ast_dsp_new(), ast_dsp_set_threshold(), ast_format_get_name(), ast_format_slin, AST_FRAME_VOICE, ast_frfree, ast_log, ast_read(), ast_set_read_format(), ast_verb, ast_waitfor(), ast_frame::frametype, wait_type::func, LOG_WARNING, wait_type::name, NULL, pbx_builtin_setvar_helper(), RAII_VAR, wait_type::status, wait_type::stop_on_frame_timeout, and THRESHOLD_SILENCE.
Referenced by waitfor_exec().
 {
    RAII_VAR(struct ast_format *, rfmt, NULL, ao2_cleanup);
    int res;
    struct ast_dsp *sildet;
    rfmt = ao2_bump(ast_channel_readformat(chan));
    if ((res = ast_set_read_format(chan, ast_format_slin)) < 0) {
       ast_log(LOG_WARNING, "Unable to set channel to linear mode, giving up\n");
       return -1;
    }
    /* Create the silence detector */
    if (!(sildet = ast_dsp_new())) {
       ast_log(LOG_WARNING, "Unable to create silence detector\n");
       return -1;
    }
    ast_dsp_set_threshold(sildet, ast_dsp_get_threshold_from_settings(THRESHOLD_SILENCE));
    for (;;) {
       int dsptime = 0;
       res = ast_waitfor(chan, timereqd);
       /* Must have gotten a hangup; let's exit */
       if (res < 0) {
          pbx_builtin_setvar_helper(chan, "WAITSTATUS", "HANGUP");
          break;
       }
       /* We waited and got no frame; sounds like digital silence or a muted digital channel */
       if (res == 0) {
          if (wait_for->stop_on_frame_timeout) {
             dsptime = timereqd;
          }
       } else {
          /* Looks like we did get a frame, so let's check it out */
          struct ast_frame *f = ast_read(chan);
          if (!f) {
             pbx_builtin_setvar_helper(chan, "WAITSTATUS", "HANGUP");
             break;
          }
          if (f->frametype == AST_FRAME_VOICE) {
             wait_for->func(sildet, f, &dsptime);
          }
          ast_frfree(f);
       }
       ast_debug(1, "Got %dms of %s < %dms required\n", dsptime, wait_for->name, timereqd);
       if (dsptime >= timereqd) {
          ast_verb(3, "Exiting with %dms of %s >= %dms required\n", dsptime, wait_for->name, timereqd);
          pbx_builtin_setvar_helper(chan, "WAITSTATUS", wait_for->status);
          ast_debug(1, "WAITSTATUS was set to %s\n", wait_for->status);
          res = 1;
          break;
       }
       if (timeout && difftime(time(NULL), waitstart) >= timeout) {
          pbx_builtin_setvar_helper(chan, "WAITSTATUS", "TIMEOUT");
          ast_debug(1, "WAITSTATUS was set to TIMEOUT\n");
          res = 0;
          break;
       }
    }
    if (rfmt && ast_set_read_format(chan, rfmt)) {
       ast_log(LOG_WARNING, "Unable to restore format %s to channel '%s'\n", ast_format_get_name(rfmt), ast_channel_name(chan));
    }
    ast_dsp_free(sildet);
    return res;
 }
load_module()
static int load_module (void) static
Definition at line 311 of file app_waitforsilence.c.
References app_noise, app_silence, AST_MODULE_INFO_STANDARD_EXTENDED(), ast_register_application_xml, ASTERISK_GPL_KEY, waitfornoise_exec(), and waitforsilence_exec().
 {
    int res;
    res = ast_register_application_xml(app_silence, waitforsilence_exec);
    res |= ast_register_application_xml(app_noise, waitfornoise_exec);
    return res;
 }
unload_module()
static int unload_module (void) static
Definition at line 302 of file app_waitforsilence.c.
References app_noise, app_silence, and ast_unregister_application().
 {
    int res;
    res = ast_unregister_application(app_silence);
    res |= ast_unregister_application(app_noise);
    return res;
 }
waitfor_exec()
static int waitfor_exec (struct ast_channel * chan, const char * data, const struct wait_type * wait_for) static
Definition at line 228 of file app_waitforsilence.c.
References args, ast_answer(), AST_APP_ARG, ast_channel_start_silence_generator(), ast_channel_stop_silence_generator(), AST_DECLARE_APP_ARGS, ast_log, ast_opt_transmit_silence, AST_STANDARD_APP_ARGS, AST_STATE_UP, ast_strdupa, ast_strlen_zero, ast_verb, do_waiting(), LOG_ERROR, wait_type::name, NULL, parse(), and timeout.
Referenced by waitfornoise_exec(), and waitforsilence_exec().
 {
    int res = 1;
    int timereqd = 1000;
    int timeout = 0;
    int iterations = 1, i;
    time_t waitstart;
    char *parse;
    struct ast_silence_generator *silgen = NULL;
    AST_DECLARE_APP_ARGS(args,
       AST_APP_ARG(timereqd);
       AST_APP_ARG(iterations);
       AST_APP_ARG(timeout);
    );
    parse = ast_strdupa(data);
    AST_STANDARD_APP_ARGS(args, parse);
    if (!ast_strlen_zero(args.timereqd)) {
       if (sscanf(args.timereqd, "%30d", &timereqd) != 1 || timereqd < 0) {
          ast_log(LOG_ERROR, "Argument '%srequired' must be an integer greater than or equal to zero.\n",
                wait_for->name);
          return -1;
       }
    }
    if (!ast_strlen_zero(args.iterations)) {
       if (sscanf(args.iterations, "%30d", &iterations) != 1 || iterations < 1) {
          ast_log(LOG_ERROR, "Argument 'iterations' must be an integer greater than 0.\n");
          return -1;
       }
    }
    if (!ast_strlen_zero(args.timeout)) {
       if (sscanf(args.timeout, "%30d", &timeout) != 1 || timeout < 0) {
          ast_log(LOG_ERROR, "Argument 'timeout' must be an integer greater than or equal to zero.\n");
          return -1;
       }
    }
    if (ast_channel_state(chan) != AST_STATE_UP) {
       ast_answer(chan); /* Answer the channel */
    }
    ast_verb(3, "Waiting %d time(s) for %dms of %s with %ds timeout\n",
           iterations, timereqd, wait_for->name, timeout);
    if (ast_opt_transmit_silence) {
       silgen = ast_channel_start_silence_generator(chan);
    }
    time(&waitstart);
    for (i = 0; i < iterations && res == 1; i++) {
       res = do_waiting(chan, timereqd, waitstart, timeout, wait_for);
    }
    if (silgen) {
       ast_channel_stop_silence_generator(chan, silgen);
    }
    return res > 0 ? 0 : res;
 }
waitfornoise_exec()
static int waitfornoise_exec (struct ast_channel * chan, const char * data) static
Definition at line 297 of file app_waitforsilence.c.
References waitfor_exec().
Referenced by load_module().
 {
    return waitfor_exec(chan, data, &wait_for_noise);
 }
waitforsilence_exec()
static int waitforsilence_exec (struct ast_channel * chan, const char * data) static
Definition at line 292 of file app_waitforsilence.c.
References waitfor_exec().
Referenced by load_module().
 {
    return waitfor_exec(chan, data, &wait_for_silence);
 }
Variable Documentation
app_noise
char* app_noise = "WaitForNoise" static
Definition at line 131 of file app_waitforsilence.c.
Referenced by load_module(), and unload_module().
app_silence
char* app_silence = "WaitForSilence" static
Definition at line 130 of file app_waitforsilence.c.
Referenced by load_module(), and unload_module().
wait_for_noise
const struct wait_type wait_for_noise static
Definition at line 147 of file app_waitforsilence.c.
wait_for_silence
const struct wait_type wait_for_silence static
Definition at line 140 of file app_waitforsilence.c.