Asterisk - The Open Source Telephony Project: logger_category.h File Reference
logger_category.h File Reference
#include "asterisk/logger.h"
Macros
#define ast_debug_category(sublevel, ids, ...)
Log for a debug category.
#define AST_LOG_CATEGORY_DISABLED 0
#define AST_LOG_CATEGORY_ENABLED -1
Functions
char * ast_debug_category_complete (const char *const *argv, int argc, const char *word, int state)
Add a unique (no duplicates) result to a request for completion for debug categories.
int ast_debug_category_is_allowed (int sublevel, uintmax_t ids)
Check if a debug category is enabled, and allowed to output.
uintmax_t ast_debug_category_register (const char *name)
Register a debug level logger category.
int ast_debug_category_set_sublevel (const char *name, int sublevel)
Set the debug category's sublevel.
int ast_debug_category_set_sublevels (const char *const *names, size_t size, int default_sublevel)
Set one or more debug category's sublevel.
int ast_debug_category_unregister (const char *name)
Un-register a debug level logger category.
int ast_logger_category_load (void)
Load/Initialize system wide logger category functionality.
int ast_logger_category_unload (void)
Unload system wide logger category functionality.
Macro Definition Documentation
ast_debug_category
#define ast_debug_category (sublevel, ids, ...)
Value:
do { \
      if (DEBUG_ATLEAST(sublevel) || ast_debug_category_is_allowed(sublevel, ids)) { \
         ast_log(AST_LOG_DEBUG, __VA_ARGS__); \
      } \
   } while (0)
Log for a debug category.
This will output log data for debug under the following conditions:
The specified sublevel is at, or below the current system debug level
At least one of the given category ids is enabled AND a. The category sublevel is enabled OR the given sublevel is at, or below a category's specified sublevel.
Parameters
sublevel The minimum level to output at
ids One or more unique category ids to output for
Since
16.14
17.8
18.0
Definition at line 171 of file logger_category.h.
Referenced by ast_rtp_ice_start_media(), and rtp_add_candidates_to_ice().
AST_LOG_CATEGORY_DISABLED
#define AST_LOG_CATEGORY_DISABLED 0
Logger category is disabled
Definition at line 31 of file logger_category.h.
Referenced by category_is_allowed(), category_register(), category_set_sublevel(), handle_cli_rtcp_set_debug(), handle_cli_rtp_set_debug(), handle_cli_stun_set_debug(), and handle_debug_category().
AST_LOG_CATEGORY_ENABLED
#define AST_LOG_CATEGORY_ENABLED -1
Logger category is enabled
Definition at line 26 of file logger_category.h.
Referenced by category_is_allowed(), handle_cli_rtcp_set_debug(), handle_cli_rtp_set_debug(), handle_cli_stun_set_debug(), handle_debug_category(), rtcp_do_debug_ip(), and rtp_do_debug_ip().
Function Documentation
ast_debug_category_complete()
char* ast_debug_category_complete (const char *const * argv, int argc, const char * word, int state)
Add a unique (no duplicates) result to a request for completion for debug categories.
Parameters
argv A list of already completed options
argc The number of already completed options
word The word to complete
state The state
Return values
0 Success, -1 Failure
Since
16.14
17.8
18.0
Definition at line 300 of file logger_category.c.
References category_complete().
Referenced by handle_debug_category().
 {
    return category_complete(&debug_categories, argv, argc, word, state);
 }
ast_debug_category_is_allowed()
int ast_debug_category_is_allowed (int sublevel, uintmax_t ids)
Check if a debug category is enabled, and allowed to output.
Note
If more than one id is specified then if even one is allowed "true" is returned.
Parameters
sublevel Current set sublevel must be this sublevel or less
ids One or more unique category ids to check
Return values
1 if allowed, 0 if not allowed
Since
16.14
17.8
18.0
Definition at line 306 of file logger_category.c.
References category_is_allowed().
 {
    return category_is_allowed(sublevel, &debug_categories, ids);
 }
ast_debug_category_register()
uintmax_t ast_debug_category_register (const char * name)
Register a debug level logger category.
Parameters
name The name of the category
id The unique id of the category
Return values
0 if failed to register/retrieve an id. Otherwise it returns the id for the registered category.
Since
16.14
17.8
18.0
Definition at line 279 of file logger_category.c.
References category_register().
Referenced by ast_rtp_engine_init(), and ast_stun_init().
 {
    return category_register(&debug_categories, name);
 }
ast_debug_category_set_sublevel()
int ast_debug_category_set_sublevel (const char * name, int sublevel)
Set the debug category's sublevel.
Statements are output at a specified sublevel. Typically any number greater than or equal to 0. Other acceptable values include AST_LOG_CATEGORY_ENABLED and AST_LOG_CATEGORY_DISABLED.
Parameters
name The name of the category
sublevel The debug sublevel output number
Return values
0 Success, -1 Failure
Since
16.14
17.8
18.0
Definition at line 289 of file logger_category.c.
References category_set_sublevel(), and NULL.
Referenced by handle_cli_rtcp_set_debug(), handle_cli_rtp_set_debug(), handle_cli_stun_set_debug(), rtcp_do_debug_ip(), and rtp_do_debug_ip().
 {
    return category_set_sublevel(NULL, &debug_categories, name, sublevel);
 }
ast_debug_category_set_sublevels()
int ast_debug_category_set_sublevels (const char *const * names, size_t size, int default_sublevel)
Set one or more debug category's sublevel.
Accepts an array of category names, and optional associated sublevels. Sublevels can be associated with a name by using a ':' as a separator. For example:
<category name>="">:<category sublevel>="">
The given default sublevel is used if no sublevel is associated with a name.
Parameters
names An array of category names
size The size of the array (number of elements)
default_sublevel The sublevel value to use if one is not associated with a name
Return values
0 Success, -1 Failure
Since
16.14
17.8
18.0
Definition at line 294 of file logger_category.c.
References category_set_sublevels().
Referenced by handle_debug_category().
 {
    return category_set_sublevels(&debug_categories, names, size, default_sublevel);
 }
ast_debug_category_unregister()
int ast_debug_category_unregister (const char * name)
Un-register a debug level logger category.
Return values
0 Success, -1 Failure
Since
16.14
17.8
18.0
Definition at line 284 of file logger_category.c.
References category_unregister().
Referenced by rtp_engine_shutdown(), and stun_shutdown().
 {
    return category_unregister(&debug_categories, name);
 }
ast_logger_category_load()
int ast_logger_category_load (void)
Load/Initialize system wide logger category functionality.
Return values
0 Success, -1 Failure
Since
16.14
17.8
18.0
Definition at line 317 of file logger_category.c.
References AST_VECTOR_RW_INIT, and categories_level_t::categories.
Referenced by init_logger().
 {
    if (AST_VECTOR_RW_INIT(&debug_categories.categories, 10)) {
       return -1;
    }
    return 0;
 }
ast_logger_category_unload()
int ast_logger_category_unload (void)
Unload system wide logger category functionality.
Return values
0 Success, -1 Failure
Since
16.14
17.8
18.0
Definition at line 311 of file logger_category.c.
References AST_VECTOR_RW_FREE, and categories_level_t::categories.
Referenced by close_logger().
 {
    AST_VECTOR_RW_FREE(&debug_categories.categories);
    return 0;
 }