Asterisk - The Open Source Telephony Project: app_audiosocket.c File Reference
app_audiosocket.c File Reference
Dial plan applications
AudioSocket application – transmit and receive audio through a TCP socket.
#include "asterisk.h"
#include "errno.h"
#include <uuid/uuid.h>
#include "asterisk/file.h"
#include "asterisk/module.h"
#include "asterisk/channel.h"
#include "asterisk/app.h"
#include "asterisk/res_audiosocket.h"
#include "asterisk/utils.h"
#include "asterisk/format_cache.h"
Macros
#define AST_MODULE "app_audiosocket"
#define AUDIOSOCKET_CONFIG "audiosocket.conf"
#define MAX_CONNECT_TIMEOUT_MSEC 2000
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int audiosocket_exec (struct ast_channel *chan, const char *data)
static int audiosocket_run (struct ast_channel *chan, const char *id, const int svc)
static int load_module (void)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = "app_audiosocket" , .flags = AST_MODFLAG_LOAD_ORDER , .description = "AudioSocket Application" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_EXTENDED, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_CHANNEL_DRIVER, .requires = "res_audiosocket", }
static const char app [] = "AudioSocket"
static const struct ast_module_info * ast_module_info = &__mod_info
Detailed Description
AudioSocket application – transmit and receive audio through a TCP socket.
Author
Seán C McCord scm@c.nosp@m.ycor.nosp@m.esys..nosp@m.com
Definition in file app_audiosocket.c.
Macro Definition Documentation
AST_MODULE
#define AST_MODULE "app_audiosocket"
Definition at line 45 of file app_audiosocket.c.
Referenced by AST_TEST_DEFINE(), create_test_dialplan(), evt_gen_auth_method_not_allowed(), evt_gen_chal_resp_failed(), evt_gen_chal_sent(), evt_gen_failed_acl(), evt_gen_inval_acct_id(), evt_gen_inval_password(), evt_gen_inval_transport(), evt_gen_load_avg(), evt_gen_mem_limit(), evt_gen_req_bad_format(), evt_gen_req_no_support(), evt_gen_req_not_allowed(), evt_gen_session_limit(), evt_gen_successful_auth(), evt_gen_unexpected_addr(), hook_state_alloc(), load_module(), phoneprov_destroy(), reload_module(), unload_module(), and users_apply_handler().
AUDIOSOCKET_CONFIG
#define AUDIOSOCKET_CONFIG "audiosocket.conf"
Definition at line 46 of file app_audiosocket.c.
MAX_CONNECT_TIMEOUT_MSEC
#define MAX_CONNECT_TIMEOUT_MSEC 2000
Definition at line 47 of file app_audiosocket.c.
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 240 of file app_audiosocket.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 240 of file app_audiosocket.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 240 of file app_audiosocket.c.
audiosocket_exec()
static int audiosocket_exec (struct ast_channel * chan, const char * data) static
Definition at line 74 of file app_audiosocket.c.
References ao2_bump, ao2_ref, args, AST_APP_ARG, ast_audiosocket_connect(), ast_channel_name(), ast_channel_readformat(), ast_channel_writeformat(), AST_DECLARE_APP_ARGS, ast_format_slin, ast_log, ast_set_read_format(), ast_set_write_format(), AST_STANDARD_APP_ARGS, ast_strdupa, ast_strlen_zero, audiosocket_run(), LOG_ERROR, and parse().
Referenced by load_module().
 {
    char *parse;
    struct ast_format *readFormat, *writeFormat;
    const char *chanName;
    int res;
    AST_DECLARE_APP_ARGS(args,
       AST_APP_ARG(idStr);
       AST_APP_ARG(server);
    );
    int s = 0;
    uuid_t uu;
    chanName = ast_channel_name(chan);
    /* Parse and validate arguments */
    parse = ast_strdupa(data);
    AST_STANDARD_APP_ARGS(args, parse);
    if (ast_strlen_zero(args.idStr)) {
       ast_log(LOG_ERROR, "UUID is required\n");
       return -1;
    }
    if (uuid_parse(args.idStr, uu)) {
       ast_log(LOG_ERROR, "Failed to parse UUID '%s'\n", args.idStr);
       return -1;
    }
    if ((s = ast_audiosocket_connect(args.server, chan)) < 0) {
       /* The res module will already output a log message, so another is not needed */
       return -1;
    }
    writeFormat = ao2_bump(ast_channel_writeformat(chan));
    readFormat = ao2_bump(ast_channel_readformat(chan));
    if (ast_set_write_format(chan, ast_format_slin)) {
       ast_log(LOG_ERROR, "Failed to set write format to SLINEAR for channel %s\n", chanName);
       ao2_ref(writeFormat, -1);
       ao2_ref(readFormat, -1);
       close(s);
       return -1;
    }
    if (ast_set_read_format(chan, ast_format_slin)) {
       ast_log(LOG_ERROR, "Failed to set read format to SLINEAR for channel %s\n", chanName);
       /* Attempt to restore previous write format even though it is likely to
        * fail, since setting the read format did.
        */
       if (ast_set_write_format(chan, writeFormat)) {
          ast_log(LOG_ERROR, "Failed to restore write format for channel %s\n", chanName);
       }
       ao2_ref(writeFormat, -1);
       ao2_ref(readFormat, -1);
       close(s);
       return -1;
    }
    res = audiosocket_run(chan, args.idStr, s);
    /* On non-zero return, report failure */
    if (res) {
       /* Restore previous formats and close the connection */
       if (ast_set_write_format(chan, writeFormat)) {
          ast_log(LOG_ERROR, "Failed to restore write format for channel %s\n", chanName);
       }
       if (ast_set_read_format(chan, readFormat)) {
          ast_log(LOG_ERROR, "Failed to restore read format for channel %s\n", chanName);
       }
       ao2_ref(writeFormat, -1);
       ao2_ref(readFormat, -1);
       close(s);
       return res;
    }
    close(s);
    if (ast_set_write_format(chan, writeFormat)) {
       ast_log(LOG_ERROR, "Failed to restore write format for channel %s\n", chanName);
    }
    if (ast_set_read_format(chan, readFormat)) {
       ast_log(LOG_ERROR, "Failed to restore read format for channel %s\n", chanName);
    }
    ao2_ref(writeFormat, -1);
    ao2_ref(readFormat, -1);
    return 0;
 }
audiosocket_run()
static int audiosocket_run (struct ast_channel * chan, const char * id, const int svc) static
Definition at line 162 of file app_audiosocket.c.
References ast_audiosocket_init(), ast_audiosocket_receive_frame(), ast_audiosocket_send_frame(), ast_channel_name(), AST_FRAME_VOICE, ast_frfree, ast_log, ast_read(), AST_STATE_UP, ast_waitfor_nandfds(), ast_write(), ast_frame::frametype, LOG_ERROR, LOG_WARNING, and NULL.
Referenced by audiosocket_exec().
 {
    const char *chanName;
    struct ast_channel *targetChan;
    int ms = 0;
    int outfd = -1;
    struct ast_frame *f;
    if (!chan || ast_channel_state(chan) != AST_STATE_UP) {
       ast_log(LOG_ERROR, "Channel is %s\n", chan ? "not answered" : "missing");
       return -1;
    }
    if (ast_audiosocket_init(svc, id)) {
       ast_log(LOG_ERROR, "Failed to intialize AudioSocket\n");
       return -1;
    }
    chanName = ast_channel_name(chan);
    while (1) {
       targetChan = ast_waitfor_nandfds(&chan, 1, &svc, 1, NULL, &outfd, &ms);
       if (targetChan) {
          f = ast_read(chan);
          if (!f) {
             return -1;
          }
          if (f->frametype == AST_FRAME_VOICE) {
             /* Send audio frame to audiosocket */
             if (ast_audiosocket_send_frame(svc, f)) {
                ast_log(LOG_ERROR, "Failed to forward channel frame from %s to AudioSocket\n",
                   chanName);
                ast_frfree(f);
                return -1;
             }
          }
          ast_frfree(f);
       }
       if (outfd >= 0) {
          f = ast_audiosocket_receive_frame(svc);
          if (!f) {
             ast_log(LOG_ERROR, "Failed to receive frame from AudioSocket message for"
                "channel %s\n", chanName);
             return -1;
          }
          if (ast_write(chan, f)) {
             ast_log(LOG_WARNING, "Failed to forward frame to channel %s\n", chanName);
             ast_frfree(f);
             return -1;
          }
          ast_frfree(f);
       }
    }
    return 0;
 }
load_module()
static int load_module (void) static
Definition at line 226 of file app_audiosocket.c.
References app, AST_MODFLAG_LOAD_ORDER, AST_MODPRI_CHANNEL_DRIVER, AST_MODULE_INFO(), AST_MODULE_SUPPORT_EXTENDED, ast_register_application_xml, ASTERISK_GPL_KEY, audiosocket_exec(), and unload_module().
 {
    return ast_register_application_xml(app, audiosocket_exec);
 }
unload_module()
static int unload_module (void) static
Definition at line 221 of file app_audiosocket.c.
References app, and ast_unregister_application().
Referenced by load_module().
 {
    return ast_unregister_application(app);
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = "app_audiosocket" , .flags = AST_MODFLAG_LOAD_ORDER , .description = "AudioSocket Application" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_EXTENDED, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_CHANNEL_DRIVER, .requires = "res_audiosocket", } static
Definition at line 240 of file app_audiosocket.c.
app
const char app[] = "AudioSocket" static
Definition at line 70 of file app_audiosocket.c.
Referenced by load_module(), and unload_module().
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 240 of file app_audiosocket.c.