Asterisk - The Open Source Telephony Project: codec_gsm.c File Reference
codec_gsm.c File Reference
Module: Codecs
Translate between signed linear and Global System for Mobile Communications (GSM)
#include "asterisk.h"
#include "asterisk/translate.h"
#include "asterisk/config.h"
#include "asterisk/module.h"
#include "asterisk/utils.h"
#include "asterisk/linkedlists.h"
#include "gsm.h"
#include "../formats/msgsm.h"
#include "asterisk/slin.h"
#include "ex_gsm.h"
Data Structures
struct gsm_translator_pvt
Macros
#define BUFFER_SAMPLES 8000
#define GSM_FRAME_LEN 33
#define GSM_SAMPLES 160
#define MSGSM_FRAME_LEN 65
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static void gsm_destroy_stuff (struct ast_trans_pvt *pvt)
static int gsm_new (struct ast_trans_pvt *pvt)
static int gsmtolin_framein (struct ast_trans_pvt *pvt, struct ast_frame *f)
decode and store in outbuf.
static int lintogsm_framein (struct ast_trans_pvt *pvt, struct ast_frame *f)
store samples into working buffer for later decode
static struct ast_frame * lintogsm_frameout (struct ast_trans_pvt *pvt)
encode and produce a frame
static int load_module (void)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_DEFAULT , .description = "GSM Coder/Decoder" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, }
static const struct ast_module_info * ast_module_info = &__mod_info
static struct ast_translator gsmtolin
static struct ast_translator lintogsm
Detailed Description
Translate between signed linear and Global System for Mobile Communications (GSM)
Definition in file codec_gsm.c.
Macro Definition Documentation
BUFFER_SAMPLES
#define BUFFER_SAMPLES 8000
Definition at line 50 of file codec_gsm.c.
Referenced by gsmtolin_framein(), and lintogsm_framein().
GSM_FRAME_LEN
#define GSM_FRAME_LEN 33
Definition at line 52 of file codec_gsm.c.
Referenced by gsmtolin_framein(), and lintogsm_frameout().
GSM_SAMPLES
#define GSM_SAMPLES 160
Definition at line 51 of file codec_gsm.c.
Referenced by gsm_sample(), gsmtolin_framein(), and lintogsm_frameout().
MSGSM_FRAME_LEN
#define MSGSM_FRAME_LEN 65
Definition at line 53 of file codec_gsm.c.
Referenced by gsmtolin_framein().
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 252 of file codec_gsm.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 252 of file codec_gsm.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 252 of file codec_gsm.c.
gsm_destroy_stuff()
static void gsm_destroy_stuff (struct ast_trans_pvt * pvt) static
Definition at line 172 of file codec_gsm.c.
References gsm_translator_pvt::gsm, ast_trans_pvt::pvt, and tmp().
 {
    struct gsm_translator_pvt *tmp = pvt->pvt;
    if (tmp->gsm)
       gsm_destroy(tmp->gsm);
 }
gsm_new()
static int gsm_new (struct ast_trans_pvt * pvt) static
Definition at line 64 of file codec_gsm.c.
References gsm_translator_pvt::gsm, ast_trans_pvt::pvt, and tmp().
 {
    struct gsm_translator_pvt *tmp = pvt->pvt;
    return (tmp->gsm = gsm_create()) ? 0 : -1;
 }
gsmtolin_framein()
static int gsmtolin_framein (struct ast_trans_pvt * pvt, struct ast_frame * f) static
decode and store in outbuf.
Definition at line 72 of file codec_gsm.c.
References ast_log, BUFFER_SAMPLES, conv65(), ast_frame::data, ast_frame::datalen, ast_trans_pvt::datalen, gsm_translator_pvt::gsm, GSM_FRAME_LEN, GSM_SAMPLES, ast_trans_pvt::i16, len(), LOG_WARNING, MSGSM_FRAME_LEN, ast_trans_pvt::outbuf, ast_frame::ptr, ast_trans_pvt::pvt, ast_trans_pvt::samples, and tmp().
 {
    struct gsm_translator_pvt *tmp = pvt->pvt;
    int x;
    int16_t *dst = pvt->outbuf.i16;
    /* guess format from frame len. 65 for MSGSM, 33 for regular GSM */
    int flen = (f->datalen % MSGSM_FRAME_LEN == 0) ?
       MSGSM_FRAME_LEN : GSM_FRAME_LEN;
    for (x=0; x < f->datalen; x += flen) {
       unsigned char data[2 * GSM_FRAME_LEN];
       unsigned char *src;
       int len;
       if (flen == MSGSM_FRAME_LEN) {
          len = 2*GSM_SAMPLES;
          src = data;
          /* Translate MSGSM format to Real GSM format before feeding in */
          /* XXX what's the point here! we should just work
           * on the full format.
           */
          conv65(f->data.ptr + x, data);
       } else {
          len = GSM_SAMPLES;
          src = f->data.ptr + x;
       }
       /* XXX maybe we don't need to check */
       if (pvt->samples + len > BUFFER_SAMPLES) {
          ast_log(LOG_WARNING, "Out of buffer space\n");
          return -1;
       }
       if (gsm_decode(tmp->gsm, src, dst + pvt->samples)) {
          ast_log(LOG_WARNING, "Invalid GSM data (1)\n");
          return -1;
       }
       pvt->samples += GSM_SAMPLES;
       pvt->datalen += 2 * GSM_SAMPLES;
       if (flen == MSGSM_FRAME_LEN) {
          if (gsm_decode(tmp->gsm, data + GSM_FRAME_LEN, dst + pvt->samples)) {
             ast_log(LOG_WARNING, "Invalid GSM data (2)\n");
             return -1;
          }
          pvt->samples += GSM_SAMPLES;
          pvt->datalen += 2 * GSM_SAMPLES;
       }
    }
    return 0;
 }
lintogsm_framein()
static int lintogsm_framein (struct ast_trans_pvt * pvt, struct ast_frame * f) static
store samples into working buffer for later decode
Definition at line 121 of file codec_gsm.c.
References ast_log, gsm_translator_pvt::buf, BUFFER_SAMPLES, ast_frame::data, ast_frame::datalen, LOG_WARNING, ast_frame::ptr, ast_trans_pvt::pvt, ast_frame::samples, ast_trans_pvt::samples, and tmp().
 {
    struct gsm_translator_pvt *tmp = pvt->pvt;
    /* XXX We should look at how old the rest of our stream is, and if it
       is too old, then we should overwrite it entirely, otherwise we can
       get artifacts of earlier talk that do not belong */
    if (pvt->samples + f->samples > BUFFER_SAMPLES) {
       ast_log(LOG_WARNING, "Out of buffer space\n");
       return -1;
    }
    memcpy(tmp->buf + pvt->samples, f->data.ptr, f->datalen);
    pvt->samples += f->samples;
    return 0;
 }
lintogsm_frameout()
static struct ast_frame* lintogsm_frameout (struct ast_trans_pvt * pvt) static
encode and produce a frame
Definition at line 138 of file codec_gsm.c.
References AST_LIST_NEXT, ast_trans_frameout(), gsm_translator_pvt::buf, ast_trans_pvt::c, gsm_translator_pvt::gsm, GSM_FRAME_LEN, GSM_SAMPLES, last, NULL, ast_trans_pvt::outbuf, ast_trans_pvt::pvt, result, ast_frame::samples, ast_trans_pvt::samples, and tmp().
 {
    struct gsm_translator_pvt *tmp = pvt->pvt;
    struct ast_frame *result = NULL;
    struct ast_frame *last = NULL;
    int samples = 0; /* output samples */
    while (pvt->samples >= GSM_SAMPLES) {
       struct ast_frame *current;
       /* Encode a frame of data */
       gsm_encode(tmp->gsm, tmp->buf + samples, (gsm_byte *) pvt->outbuf.c);
       samples += GSM_SAMPLES;
       pvt->samples -= GSM_SAMPLES;
       current = ast_trans_frameout(pvt, GSM_FRAME_LEN, GSM_SAMPLES);
       if (!current) {
          continue;
       } else if (last) {
          AST_LIST_NEXT(last, frame_list) = current;
       } else {
          result = current;
       }
       last = current;
    }
    /* Move the data at the end of the buffer to the front */
    if (samples) {
       memmove(tmp->buf, tmp->buf + samples, pvt->samples * 2);
    }
    return result;
 }
load_module()
static int load_module (void) static
Definition at line 233 of file codec_gsm.c.
References AST_MODFLAG_DEFAULT, AST_MODULE_INFO(), AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, AST_MODULE_SUPPORT_CORE, ast_register_translator, ASTERISK_GPL_KEY, and unload_module().
 {
    int res;
    res = ast_register_translator(&gsmtolin);
    res |= ast_register_translator(&lintogsm);
    if (res) {
       unload_module();
       return AST_MODULE_LOAD_DECLINE;
    }
    return AST_MODULE_LOAD_SUCCESS;
 }
unload_module()
static int unload_module (void) static
Definition at line 223 of file codec_gsm.c.
References ast_unregister_translator().
Referenced by load_module().
 {
    int res;
    res = ast_unregister_translator(&lintogsm);
    res |= ast_unregister_translator(&gsmtolin);
    return res;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_DEFAULT , .description = "GSM Coder/Decoder" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, } static
Definition at line 252 of file codec_gsm.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 252 of file codec_gsm.c.
gsmtolin
struct ast_translator gsmtolin static
Definition at line 179 of file codec_gsm.c.
lintogsm
struct ast_translator lintogsm static
Definition at line 201 of file codec_gsm.c.