Asterisk - The Open Source Telephony Project: plc.c File Reference
plc.c File Reference
SpanDSP - a series of DSP components for telephony.
#include "asterisk.h"
#include <math.h>
#include "asterisk/config.h"
#include "asterisk/module.h"
#include "asterisk/plc.h"
Macros
#define ATTENUATION_INCREMENT 0.0025 /* Attenuation per sample */
#define FALSE 0
#define INT16_MAX (32767)
#define INT16_MIN (-32767-1)
#define ms_to_samples(t) (((t)*DEFAULT_SAMPLE_RATE)/1000)
#define TRUE (!FALSE)
Functions
static void __reg_module (void)
static void __unreg_module (void)
static int __inline__ amdf_pitch (int min_pitch, int max_pitch, int16_t amp[], int len)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int16_t fsaturate (double damp)
static int load_module (void)
static void normalise_history (plc_state_t *s)
int plc_fillin (plc_state_t *s, int16_t amp[], int len)
Fill-in a block of missing audio samples.
plc_state_t * plc_init (plc_state_t *s)
Process a block of received V.29 modem audio samples.
int plc_rx (plc_state_t *s, int16_t amp[], int len)
Process a block of received audio samples.
static int reload_module (void)
static void save_history (plc_state_t *s, int16_t *buf, int len)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_GLOBAL_SYMBOLS | AST_MODFLAG_LOAD_ORDER , .description = "PLC" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .reload = reload_module, .load_pri = AST_MODPRI_CORE, .requires = "extconfig", }
static const struct ast_module_info * ast_module_info = &__mod_info
Detailed Description
SpanDSP - a series of DSP components for telephony.
Author
Steve Underwood steve.nosp@m.u@co.nosp@m.ppice.nosp@m..org
Definition in file plc.c.
Macro Definition Documentation
ATTENUATION_INCREMENT
#define ATTENUATION_INCREMENT 0.0025 /* Attenuation per sample */
Definition at line 58 of file plc.c.
Referenced by plc_fillin(), and plc_rx().
FALSE
#define FALSE 0
Definition at line 46 of file plc.c.
INT16_MAX
#define INT16_MAX (32767)
Definition at line 53 of file plc.c.
Referenced by fsaturate().
INT16_MIN
#define INT16_MIN (-32767-1)
Definition at line 54 of file plc.c.
Referenced by fsaturate().
ms_to_samples
#define ms_to_samples (t) (((t)*DEFAULT_SAMPLE_RATE)/1000)
Definition at line 60 of file plc.c.
TRUE
#define TRUE (!FALSE)
Definition at line 49 of file plc.c.
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 300 of file plc.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 300 of file plc.c.
amdf_pitch()
static int __inline__ amdf_pitch (int min_pitch, int max_pitch, int16_t amp[], int len) static
Definition at line 108 of file plc.c.
References abs, and len().
Referenced by plc_fillin().
 {
    int i;
    int j;
    int acc;
    int min_acc;
    int pitch;
    pitch = min_pitch;
    min_acc = INT_MAX;
    for (i = max_pitch; i <= min_pitch; i++) {
       acc = 0;
       for (j = 0; j < len; j++)
          acc += abs(amp[i + j] - amp[j]);
       if (acc < min_acc) {
          min_acc = acc;
          pitch = i;
       }
    }
    return pitch;
 }
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 300 of file plc.c.
fsaturate()
static int16_t fsaturate (double damp) inline static
Definition at line 62 of file plc.c.
References INT16_MAX, and INT16_MIN.
Referenced by plc_fillin(), and plc_rx().
 {
    if (damp > 32767.0)
       return  INT16_MAX;
    if (damp < -32768.0)
       return  INT16_MIN;
    return (int16_t) rint(damp);
 }
load_module()
static int load_module (void) static
Definition at line 281 of file plc.c.
References AST_MODULE_LOAD_SUCCESS, and reload_module().
Referenced by unload_module().
 {
    reload_module();
    return AST_MODULE_LOAD_SUCCESS;
 }
normalise_history()
static void normalise_history (plc_state_t * s) static
Definition at line 94 of file plc.c.
References plc_state_t::buf_ptr, plc_state_t::history, PLC_HISTORY_LEN, and tmp().
Referenced by plc_fillin().
 {
    int16_t tmp[PLC_HISTORY_LEN];
    if (s->buf_ptr == 0)
       return;
    memcpy(tmp, s->history, sizeof(int16_t)*s->buf_ptr);
    memmove(s->history, s->history + s->buf_ptr, sizeof(int16_t) * (PLC_HISTORY_LEN - s->buf_ptr));
    memcpy(s->history + PLC_HISTORY_LEN - s->buf_ptr, tmp, sizeof(int16_t) * s->buf_ptr);
    s->buf_ptr = 0;
 }
plc_fillin()
int plc_fillin (plc_state_t * s, int16_t amp[], int len)
Fill-in a block of missing audio samples.
Fill-in a block of missing audio samples.
Parameters
s The packet loss concealer context.
amp The audio sample buffer.
len The number of samples to be synthesised.
Returns
The number of samples synthesized.
Definition at line 175 of file plc.c.
References amdf_pitch(), ATTENUATION_INCREMENT, CORRELATION_SPAN, fsaturate(), plc_state_t::history, len(), plc_state_t::missing_samples, normalise_history(), plc_state_t::pitch, plc_state_t::pitch_offset, plc_state_t::pitchbuf, PLC_HISTORY_LEN, PLC_PITCH_MAX, PLC_PITCH_MIN, and save_history().
Referenced by adjust_frame_for_plc().
 {
    int i;
    int pitch_overlap;
    float old_step;
    float new_step;
    float old_weight;
    float new_weight;
    float gain;
    int orig_len;
    orig_len = len;
    if (s->missing_samples == 0) {
       /* As the gap in real speech starts we need to assess the last known pitch,
       and prepare the synthetic data we will use for fill-in */
       normalise_history(s);
       s->pitch = amdf_pitch(PLC_PITCH_MIN, PLC_PITCH_MAX, s->history + PLC_HISTORY_LEN - CORRELATION_SPAN - PLC_PITCH_MIN, CORRELATION_SPAN);
       /* We overlap a 1/4 wavelength */
       pitch_overlap = s->pitch >> 2;
       /* Cook up a single cycle of pitch, using a single of the real signal with 1/4
       cycle OLA'ed to make the ends join up nicely */
       /* The first 3/4 of the cycle is a simple copy */
       for (i = 0;  i < s->pitch - pitch_overlap;  i++)
          s->pitchbuf[i] = s->history[PLC_HISTORY_LEN - s->pitch + i];
       /* The last 1/4 of the cycle is overlapped with the end of the previous cycle */
       new_step = 1.0/pitch_overlap;
       new_weight = new_step;
       for ( ; i < s->pitch; i++) {
          s->pitchbuf[i] = s->history[PLC_HISTORY_LEN - s->pitch + i] * (1.0 - new_weight) + s->history[PLC_HISTORY_LEN - 2 * s->pitch + i]*new_weight;
          new_weight += new_step;
       }
       /* We should now be ready to fill in the gap with repeated, decaying cycles
       of what is in pitchbuf */
       /* We need to OLA the first 1/4 wavelength of the synthetic data, to smooth
       it into the previous real data. To avoid the need to introduce a delay
       in the stream, reverse the last 1/4 wavelength, and OLA with that. */
       gain = 1.0;
       new_step = 1.0 / pitch_overlap;
       old_step = new_step;
       new_weight = new_step;
       old_weight = 1.0 - new_step;
       for (i = 0; i < pitch_overlap; i++) {
          amp[i] = fsaturate(old_weight * s->history[PLC_HISTORY_LEN - 1 - i] + new_weight * s->pitchbuf[i]);
          new_weight += new_step;
          old_weight -= old_step;
          if (old_weight < 0.0)
             old_weight = 0.0;
       }
       s->pitch_offset = i;
    } else {
       gain = 1.0 - s->missing_samples*ATTENUATION_INCREMENT;
       i = 0;
    }
    for ( ; gain > 0.0 && i < len; i++) {
       amp[i] = s->pitchbuf[s->pitch_offset] * gain;
       gain -= ATTENUATION_INCREMENT;
       if (++s->pitch_offset >= s->pitch)
          s->pitch_offset = 0;
    }
    for ( ; i < len; i++)
       amp[i] = 0;
    s->missing_samples += orig_len;
    save_history(s, amp, len);
    return len;
 }
plc_init()
plc_state_t* plc_init (plc_state_t * s)
Process a block of received V.29 modem audio samples.
Process a block of received V.29 modem audio samples.
Parameters
s The packet loss concealer context.
Returns
A pointer to the he packet loss concealer context.
Definition at line 244 of file plc.c.
 {
    memset(s, 0, sizeof(*s));
    return s;
 }
plc_rx()
int plc_rx (plc_state_t * s, int16_t amp[], int len)
Process a block of received audio samples.
Process a block of received audio samples.
Parameters
s The packet loss concealer context.
amp The audio sample buffer.
len The number of samples in the buffer.
Returns
The number of samples in the buffer.
Definition at line 132 of file plc.c.
References ATTENUATION_INCREMENT, fsaturate(), len(), plc_state_t::missing_samples, plc_state_t::pitch, plc_state_t::pitch_offset, plc_state_t::pitchbuf, and save_history().
Referenced by adjust_frame_for_plc().
 {
    int i;
    int pitch_overlap;
    float old_step;
    float new_step;
    float old_weight;
    float new_weight;
    float gain;
    if (s->missing_samples) {
       /* Although we have a real signal, we need to smooth it to fit well
       with the synthetic signal we used for the previous block */
       /* The start of the real data is overlapped with the next 1/4 cycle
          of the synthetic data. */
       pitch_overlap = s->pitch >> 2;
       if (pitch_overlap > len)
          pitch_overlap = len;
       gain = 1.0 - s->missing_samples*ATTENUATION_INCREMENT;
       if (gain < 0.0)
          gain = 0.0;
       new_step = 1.0/pitch_overlap;
       old_step = new_step*gain;
       new_weight = new_step;
       old_weight = (1.0 - new_step)*gain;
       for (i = 0; i < pitch_overlap; i++) {
          amp[i] = fsaturate(old_weight * s->pitchbuf[s->pitch_offset] + new_weight * amp[i]);
          if (++s->pitch_offset >= s->pitch)
             s->pitch_offset = 0;
          new_weight += new_step;
          old_weight -= old_step;
          if (old_weight < 0.0)
             old_weight = 0.0;
       }
       s->missing_samples = 0;
    }
    save_history(s, amp, len);
    return len;
 }
reload_module()
static int reload_module (void) static
Definition at line 252 of file plc.c.
References ast_config_destroy(), ast_config_load, AST_OPT_FLAG_GENERIC_PLC, AST_OPT_FLAG_GENERIC_PLC_ON_EQUAL_CODECS, ast_opt_generic_plc, ast_options, ast_set2_flag, ast_true(), ast_variable_browse(), CONFIG_STATUS_FILEINVALID, CONFIG_STATUS_FILEMISSING, CONFIG_STATUS_FILEUNCHANGED, ast_variable::name, ast_variable::next, ast_variable::value, and var.
Referenced by load_module(), and unload_module().
 {
    struct ast_variable *var;
    struct ast_flags config_flags = { 0 };
    struct ast_config *cfg = ast_config_load("codecs.conf", config_flags);
    if (cfg == CONFIG_STATUS_FILEMISSING || cfg == CONFIG_STATUS_FILEUNCHANGED || cfg == CONFIG_STATUS_FILEINVALID) {
       return 0;
    }
    for (var = ast_variable_browse(cfg, "plc"); var; var = var->next) {
       if (!strcasecmp(var->name, "genericplc")) {
          ast_set2_flag(&ast_options, ast_true(var->value), AST_OPT_FLAG_GENERIC_PLC);
       } else if (!strcasecmp(var->name, "genericplc_on_equal_codecs")) {
          ast_set2_flag(&ast_options, ast_true(var->value), AST_OPT_FLAG_GENERIC_PLC_ON_EQUAL_CODECS);
       }
    }
    ast_config_destroy(cfg);
    /*
     * Force on_equal_codecs to false if generic_plc is false.
     */
    if (!ast_opt_generic_plc) {
       ast_set2_flag(&ast_options, 0, AST_OPT_FLAG_GENERIC_PLC_ON_EQUAL_CODECS);
    }
    return 0;
 }
save_history()
static void save_history (plc_state_t * s, int16_t * buf, int len) static
Definition at line 71 of file plc.c.
References plc_state_t::buf_ptr, plc_state_t::history, len(), and PLC_HISTORY_LEN.
Referenced by plc_fillin(), and plc_rx().
 {
    if (len >= PLC_HISTORY_LEN) {
       /* Just keep the last part of the new data, starting at the beginning of the buffer */
        memcpy(s->history, buf + len - PLC_HISTORY_LEN, sizeof(int16_t) * PLC_HISTORY_LEN);
       s->buf_ptr = 0;
       return;
    }
    if (s->buf_ptr + len > PLC_HISTORY_LEN) {
       /* Wraps around - must break into two sections */
       memcpy(s->history + s->buf_ptr, buf, sizeof(int16_t) * (PLC_HISTORY_LEN - s->buf_ptr));
       len -= (PLC_HISTORY_LEN - s->buf_ptr);
       memcpy(s->history, buf + (PLC_HISTORY_LEN - s->buf_ptr), sizeof(int16_t)*len);
       s->buf_ptr = len;
       return;
    }
    /* Can use just one section */
    memcpy(s->history + s->buf_ptr, buf, sizeof(int16_t)*len);
    s->buf_ptr += len;
 }
unload_module()
static int unload_module (void) static
Definition at line 288 of file plc.c.
References AST_MODFLAG_GLOBAL_SYMBOLS, AST_MODFLAG_LOAD_ORDER, AST_MODPRI_CORE, AST_MODULE_INFO(), AST_MODULE_SUPPORT_CORE, ASTERISK_GPL_KEY, load_module(), reload(), and reload_module().
 {
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_GLOBAL_SYMBOLS | AST_MODFLAG_LOAD_ORDER , .description = "PLC" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .reload = reload_module, .load_pri = AST_MODPRI_CORE, .requires = "extconfig", } static
Definition at line 300 of file plc.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 300 of file plc.c.