Asterisk - The Open Source Telephony Project: sip_api.h File Reference
sip_api.h File Reference
#include "asterisk/config.h"
Data Structures
struct ast_sip_api_tech
Macros
#define AST_SIP_API_VERSION 1
Functions
int ast_sip_api_provider_register (const struct ast_sip_api_tech *provider)
Register a SIP API provider.
void ast_sip_api_provider_unregister (void)
Unregister a SIP API provider.
int ast_sipinfo_send (struct ast_channel *chan, struct ast_variable *headers, const char *content_type, const char *content, const char *useragent_filter)
Send a customized SIP INFO request.
Macro Definition Documentation
AST_SIP_API_VERSION
#define AST_SIP_API_VERSION 1
Definition at line 28 of file sip_api.h.
Referenced by ast_sip_api_provider_register().
Function Documentation
ast_sip_api_provider_register()
int ast_sip_api_provider_register (const struct ast_sip_api_tech * provider)
Register a SIP API provider.
This will fail if a provider has already registered or if the provider is using an incorrect version.
Parameters
provider The provider to register
Return values
0 Success
-1 Failure
Definition at line 39 of file sip_api.c.
References ast_log, AST_SIP_API_VERSION, LOG_WARNING, ast_sip_api_tech::name, provider, and ast_sip_api_tech::version.
Referenced by load_module().
 {
    if (api_provider) {
       ast_log(LOG_WARNING, "SIP provider %s has already registered. Not registering provider %s\n",
             api_provider->name, provider->name);
       return -1;
    }
    if (provider->version != AST_SIP_API_VERSION) {
       ast_log(LOG_WARNING, "SIP API provider version mismatch: Current version is %d but provider "
             "uses version %d\n", AST_SIP_API_VERSION, provider->version);
       return -1;
    }
    api_provider = provider;
    return 0;
 }
ast_sip_api_provider_unregister()
void ast_sip_api_provider_unregister (void)
Unregister a SIP API provider.
Definition at line 57 of file sip_api.c.
References NULL.
Referenced by unload_module().
 {
    api_provider = NULL;
 }
ast_sipinfo_send()
int ast_sipinfo_send (struct ast_channel * chan, struct ast_variable * headers, const char * content_type, const char * content, const char * useragent_filter)
Send a customized SIP INFO request.
Parameters
chan Channel
headers The headers to add to the INFO request
content_type The content type header to add
content The body of the INFO request
useragent_filter If non-NULL, only send the INFO if the recipient's User-Agent contains useragent_filter as a substring
Return values
0 Success
non-zero Failure
Definition at line 25 of file sip_api.c.
References ast_log, LOG_WARNING, and ast_sip_api_tech::sipinfo_send.
Referenced by sip_sendcustominfo().
 {
    if (!api_provider) {
       ast_log(LOG_WARNING, "Unable to send custom SIP INFO. No API provider registered\n");
       return -1;
    }
    return api_provider->sipinfo_send(chan, headers, content_type, content, useragent_filter);
 }