Asterisk - The Open Source Telephony Project: file.c File Reference
file.c File Reference
Generic File Format Support.
#include "asterisk.h"
#include <dirent.h>
#include <sys/stat.h>
#include <sys/wait.h>
#include <math.h>
#include "asterisk/_private.h"
#include "asterisk/paths.h"
#include "asterisk/mod_format.h"
#include "asterisk/cli.h"
#include "asterisk/channel.h"
#include "asterisk/sched.h"
#include "asterisk/translate.h"
#include "asterisk/utils.h"
#include "asterisk/lock.h"
#include "asterisk/app.h"
#include "asterisk/pbx.h"
#include "asterisk/linkedlists.h"
#include "asterisk/module.h"
#include "asterisk/astobj2.h"
#include "asterisk/test.h"
#include "asterisk/stasis.h"
#include "asterisk/json.h"
#include "asterisk/stasis_system.h"
#include "asterisk/media_cache.h"
Data Structures
struct formats
Macros
#define exts_compare(list, type) (type_in_list((list), (type), strcmp))
#define FORMAT "%-10s %-10s %-20s\n"
#define FORMAT2 "%-10s %-10s %-20s\n"
Enumerations
enum file_action {
ACTION_EXISTS = 1, ACTION_DELETE, ACTION_RENAME, ACTION_OPEN,
ACTION_COPY
}
enum fsread_res { FSREAD_FAILURE, FSREAD_SUCCESS_SCHED, FSREAD_SUCCESS_NOSCHED }
enum wrap_fn { WRAP_OPEN, WRAP_REWRITE }
Functions
static int __ast_file_read_dirs (const char *path, ast_file_on_file on_file, void *obj, int max_depth)
int __ast_format_def_register (const struct ast_format_def *f, struct ast_module *mod)
Register a new file format capability. Adds a format to Asterisk's format abilities.
int ast_applystream (struct ast_channel *chan, struct ast_filestream *s)
Applys a open stream to a channel.
int ast_closestream (struct ast_filestream *f)
Closes a stream.
int ast_file_init (void)
int ast_file_read_dirs (const char *dir_name, ast_file_on_file on_file, void *obj, int max_depth)
Recursively iterate through files and directories up to max_depth.
int ast_filecopy (const char *filename, const char *filename2, const char *fmt)
Copies a file.
int ast_filedelete (const char *filename, const char *fmt)
Deletes a file.
int ast_fileexists (const char *filename, const char *fmt, const char *preflang)
Checks for the existence of a given file.
int ast_filerename (const char *filename, const char *filename2, const char *fmt)
Renames a file.
int ast_format_def_unregister (const char *name)
Unregisters a file format.
char * ast_format_str_reduce (char *fmts)
static int ast_fsread_audio (const void *data)
static int ast_fsread_video (const void *data)
int ast_get_extension_for_mime_type (const char *mime_type, char *buffer, size_t capacity)
Get a suitable filename extension for the given MIME type.
struct ast_format * ast_get_format_for_file_ext (const char *file_ext)
Get the ast_format associated with the given file extension.
struct ast_filestream * ast_openstream (struct ast_channel *chan, const char *filename, const char *preflang)
Opens stream for use in seeking, playing.
struct ast_filestream * ast_openstream_full (struct ast_channel *chan, const char *filename, const char *preflang, int asis)
Opens stream for use in seeking, playing.
struct ast_filestream * ast_openvstream (struct ast_channel *chan, const char *filename, const char *preflang)
Opens stream for use in seeking, playing.
int ast_playstream (struct ast_filestream *s)
Play a open stream on a channel.
int ast_ratestream (struct ast_filestream *fs)
Return the sample rate of the stream's format.
static enum fsread_res ast_readaudio_callback (struct ast_filestream *s)
struct ast_filestream * ast_readfile (const char *filename, const char *type, const char *comment, int flags, int check, mode_t mode)
Starts reading from a file.
struct ast_frame * ast_readframe (struct ast_filestream *s)
Read a frame from a filestream.
static enum fsread_res ast_readvideo_callback (struct ast_filestream *s)
int ast_seekstream (struct ast_filestream *fs, off_t sample_offset, int whence)
Seeks into stream.
int ast_stopstream (struct ast_channel *tmp)
Stops a stream.
int ast_stream_and_wait (struct ast_channel *chan, const char *file, const char *digits)
stream file until digit If the file name is non-empty, try to play it.
int ast_stream_fastforward (struct ast_filestream *fs, off_t ms)
Fast forward stream ms.
int ast_stream_rewind (struct ast_filestream *fs, off_t ms)
Rewind stream ms.
int ast_streamfile (struct ast_channel *chan, const char *filename, const char *preflang)
Streams a file.
off_t ast_tellstream (struct ast_filestream *fs)
Tell where we are in a stream.
int ast_truncstream (struct ast_filestream *fs)
Trunc stream at current location.
int ast_waitstream (struct ast_channel *c, const char *breakon)
Waits for a stream to stop or digit to be pressed.
int ast_waitstream_exten (struct ast_channel *c, const char *context)
Waits for a stream to stop or digit matching a valid one digit exten to be pressed.
int ast_waitstream_fr (struct ast_channel *c, const char *breakon, const char *forward, const char *reverse, int ms)
Same as waitstream but allows stream to be forwarded or rewound.
int ast_waitstream_fr_w_cb (struct ast_channel *c, const char *breakon, const char *forward, const char *reverse, int ms, ast_waitstream_fr_cb cb)
Same as waitstream_fr but allows a callback to be alerted when a user fastforwards or rewinds the file.
int ast_waitstream_full (struct ast_channel *c, const char *breakon, int audiofd, int cmdfd)
struct ast_filestream * ast_writefile (const char *filename, const char *type, const char *comment, int flags, int check, mode_t mode)
Starts writing a file.
int ast_writestream (struct ast_filestream *fs, struct ast_frame *f)
Writes a frame to a stream.
static char * build_filename (const char *filename, const char *ext)
construct a filename. Absolute pathnames are preserved, relative names are prefixed by the sounds/ directory. The wav49 suffix is replaced by 'WAV'. Returns a malloc'ed string to be freed by the caller.
static int copy (const char *infile, const char *outfile)
static void file_shutdown (void)
static int fileexists_core (const char *filename, const char *fmt, const char *preflang, char *buf, int buflen, struct ast_format_cap *result_cap)
helper routine to locate a file with a given format and language preference.
static int fileexists_test (const char *filename, const char *fmt, const char *lang, char *buf, int buflen, struct ast_format_cap *result_cap)
test if a file exists for a given format.
static int filehelper (const char *filename, const void *arg2, const char *fmt, const enum file_action action)
static void filestream_close (struct ast_filestream *f)
static void filestream_destructor (void *arg)
static int fn_wrapper (struct ast_filestream *s, const char *comment, enum wrap_fn mode)
static struct ast_filestream * get_filestream (struct ast_format_def *fmt, FILE *bfile)
static char * handle_cli_core_show_file_formats (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static int is_absolute_path (const char *filename)
static int is_remote_path (const char *filename)
static struct ast_json * json_array_from_list (const char *list, const char *sep)
static int open_wrapper (struct ast_filestream *s)
static int publish_format_update (const struct ast_format_def *f, struct stasis_message_type *type)
static struct ast_frame * read_frame (struct ast_filestream *s, int *whennext)
static int rewrite_wrapper (struct ast_filestream *s, const char *comment)
static int sanitize_waitstream_return (int return_value)
STASIS_MESSAGE_TYPE_DEFN (ast_format_register_type)
STASIS_MESSAGE_TYPE_DEFN (ast_format_unregister_type)
static int type_in_list (const char *list, const char *type, int(*cmp)(const char *s1, const char *s2))
static void waitstream_control (struct ast_channel *c, enum ast_waitstream_fr_cb_values type, ast_waitstream_fr_cb cb, int skip_ms)
static int waitstream_core (struct ast_channel *c, const char *breakon, const char *forward, const char *reverse, int skip_ms, int audiofd, int cmdfd, const char *context, ast_waitstream_fr_cb cb)
the core of all waitstream() functions
Variables
int ast_language_is_prefix = 1
The following variable controls the layout of localized sound files. If 0, use the historical layout with prefix just before the filename (i.e. digits/en/1.gsm , digits/it/1.gsm or default to digits/1.gsm), if 1 put the prefix at the beginning of the filename (i.e. en/digits/1.gsm, it/digits/1.gsm or default to digits/1.gsm). The latter permits a language to be entirely in one directory.
static struct ast_cli_entry cli_file []
static struct formats formats = { .first = NULL, .last = NULL, .lock = { PTHREAD_RWLOCK_INITIALIZER , NULL, {1, 0} } , }
static ast_mutex_t read_dirs_lock = { PTHREAD_RECURSIVE_MUTEX_INITIALIZER_NP , NULL, {1, 0} }
Lock to hold when iterating over directories.
Detailed Description
Generic File Format Support.
Author
Mark Spencer marks.nosp@m.ter@.nosp@m.digiu.nosp@m.m.co.nosp@m.m
Definition in file file.c.
Macro Definition Documentation
exts_compare
#define exts_compare (list, type) (type_in_list((list), (type), strcmp))
Definition at line 351 of file file.c.
Referenced by ast_format_str_reduce(), ast_get_format_for_file_ext(), ast_readfile(), ast_writefile(), and filehelper().
FORMAT
#define FORMAT "%-10s %-10s %-20s\n"
Referenced by handle_cli_core_show_file_formats().
FORMAT2
#define FORMAT2 "%-10s %-10s %-20s\n"
Referenced by handle_cli_core_show_file_formats().
Enumeration Type Documentation
file_action
enum file_action
Enumerator
ACTION_EXISTS
ACTION_DELETE
ACTION_RENAME
ACTION_OPEN
ACTION_COPY
Definition at line 495 of file file.c.
                  {
    ACTION_EXISTS = 1, /* return matching format if file exists, 0 otherwise */
    ACTION_DELETE, /* delete file, return 0 on success, -1 on error */
    ACTION_RENAME, /* rename file. return 0 on success, -1 on error */
    ACTION_OPEN,
    ACTION_COPY /* copy file. return 0 on success, -1 on error */
 };
fsread_res
enum fsread_res
Enumerator
FSREAD_FAILURE
FSREAD_SUCCESS_SCHED
FSREAD_SUCCESS_NOSCHED
Definition at line 906 of file file.c.
                 {
    FSREAD_FAILURE,
    FSREAD_SUCCESS_SCHED,
    FSREAD_SUCCESS_NOSCHED,
 };
wrap_fn
enum wrap_fn
Enumerator
WRAP_OPEN
WRAP_REWRITE
Definition at line 466 of file file.c.
 { WRAP_OPEN, WRAP_REWRITE };
Function Documentation
__ast_file_read_dirs()
static int __ast_file_read_dirs (const char * path, ast_file_on_file on_file, void * obj, int max_depth) static
Definition at line 1113 of file file.c.
References ast_debug, ast_free, ast_log, ast_malloc, errno, LOG_ERROR, NULL, and RAII_VAR.
Referenced by ast_file_read_dirs().
 {
    DIR *dir;
    struct dirent *entry;
    int res;
    if (!(dir = opendir(path))) {
       ast_log(LOG_ERROR, "Error opening directory - %s: %s\n",
          path, strerror(errno));
       return -1;
    }
    --max_depth;
    res = 0;
    while ((entry = readdir(dir)) != NULL && !errno) {
       int is_file = 0;
       int is_dir = 0;
       RAII_VAR(char *, full_path, NULL, ast_free);
       if (!strcmp(entry->d_name, ".") || !strcmp(entry->d_name, "..")) {
          continue;
       }
 /*
  * If the dirent structure has a d_type use it to determine if we are dealing with
  * a file or directory. Unfortunately if it doesn't have it, or if the type is
  * unknown, or a link then we'll need to use the stat function instead.
  */
 #ifdef _DIRENT_HAVE_D_TYPE
       if (entry->d_type != DT_UNKNOWN && entry->d_type != DT_LNK) {
          is_file = entry->d_type == DT_REG;
          is_dir = entry->d_type == DT_DIR;
       } else
 #endif
       {
          struct stat statbuf;
          /*
           * Don't use alloca or we risk blowing out the stack if recursing
           * into subdirectories.
           */
          full_path = ast_malloc(strlen(path) + strlen(entry->d_name) + 2);
          if (!full_path) {
             return -1;
          }
          sprintf(full_path, "%s/%s", path, entry->d_name);
          if (stat(full_path, &statbuf)) {
             ast_log(LOG_ERROR, "Error reading path stats - %s: %s\n",
                full_path, strerror(errno));
             /*
              * Output an error, but keep going. It could just be
              * a broken link and other files could be fine.
              */
             continue;
          }
          is_file = S_ISREG(statbuf.st_mode);
          is_dir = S_ISDIR(statbuf.st_mode);
       }
       if (is_file) {
          /* If the handler returns non-zero then stop */
          if ((res = on_file(path, entry->d_name, obj))) {
             break;
          }
          /* Otherwise move on to next item in directory */
          continue;
       }
       if (!is_dir) {
          ast_debug(5, "Skipping %s: not a regular file or directory\n", full_path);
          continue;
       }
       /* Only re-curse into sub-directories if not at the max depth */
       if (max_depth != 0) {
          if (!full_path) {
             /* Don't use alloca.  See note above. */
             full_path = ast_malloc(strlen(path) + strlen(entry->d_name) + 2);
             if (!full_path) {
                return -1;
             }
             sprintf(full_path, "%s/%s", path, entry->d_name);
          }
          if ((res = __ast_file_read_dirs(full_path, on_file, obj, max_depth))) {
             break;
          }
       }
    }
    closedir(dir);
    if (!res && errno) {
       ast_log(LOG_ERROR, "Error while reading directories - %s: %s\n",
          path, strerror(errno));
       res = -1;
    }
    return res;
 }
__ast_format_def_register()
int __ast_format_def_register (const struct ast_format_def * f, struct ast_module * mod)
Register a new file format capability. Adds a format to Asterisk's format abilities.
Return values
0 on success
-1 on failure
Definition at line 124 of file file.c.
References a, ast_calloc, ast_format_register_type(), ast_log, AST_RWLIST_INSERT_HEAD, AST_RWLIST_TRAVERSE, AST_RWLIST_UNLOCK, AST_RWLIST_WRLOCK, ast_verb, b, ast_format_def::buf_size, ast_format_def::exts, ast_format_def::list, LOG_WARNING, ast_format_def::module, ast_format_def::name, publish_format_update(), and tmp().
 {
    struct ast_format_def *tmp;
    AST_RWLIST_WRLOCK(&formats);
    AST_RWLIST_TRAVERSE(&formats, tmp, list) {
       if (!strcasecmp(f->name, tmp->name)) {
          AST_RWLIST_UNLOCK(&formats);
          ast_log(LOG_WARNING, "Tried to register '%s' format, already registered\n", f->name);
          return -1;
       }
    }
    if (!(tmp = ast_calloc(1, sizeof(*tmp)))) {
       AST_RWLIST_UNLOCK(&formats);
       return -1;
    }
    *tmp = *f;
    tmp->module = mod;
    if (tmp->buf_size) {
       /*
        * Align buf_size properly, rounding up to the machine-specific
        * alignment for pointers.
        */
       struct _test_align { void *a, *b; } p;
       int align = (char *)&p.b - (char *)&p.a;
       tmp->buf_size = ((f->buf_size + align - 1) / align) * align;
    }
    memset(&tmp->list, 0, sizeof(tmp->list));
    AST_RWLIST_INSERT_HEAD(&formats, tmp, list);
    AST_RWLIST_UNLOCK(&formats);
    ast_verb(2, "Registered file format %s, extension(s) %s\n", f->name, f->exts);
    publish_format_update(f, ast_format_register_type());
    return 0;
 }
ast_applystream()
int ast_applystream (struct ast_channel * chan, struct ast_filestream * s)
Applys a open stream to a channel.
Parameters
chan channel to work
s ast_filestream to apply
Return values
0 on success.
-1 on failure.
Definition at line 1020 of file file.c.
References ast_filestream::owner.
Referenced by ast_streamfile(), handle_getoption(), handle_recordfile(), handle_streamfile(), and speech_streamfile().
 {
    s->owner = chan;
    return 0;
 }
ast_closestream()
int ast_closestream (struct ast_filestream * f)
Closes a stream.
Parameters
f filestream to close Close a playback or recording stream
Return values
0 on success.
-1 on failure.
Definition at line 1068 of file file.c.
References ao2_ref, filestream_close(), and NULL.
Referenced by __ast_play_and_record(), ast_hangup(), ast_moh_files_next(), ast_monitor_start(), ast_monitor_stop(), ast_readfile(), ast_stopstream(), ast_writefile(), dictate_exec(), filehelper(), filestream_destructor(), gen_closestream(), handle_cli_file_convert(), handle_recordfile(), local_ast_moh_stop(), mixmonitor_ds_close_fs(), moh_files_release(), msg_create_from_file(), record_exec(), and recordthread().
 {
    /* This used to destroy the filestream, but it now just decrements a refcount.
     * We close the stream in order to quit queuing frames now, because we might
     * change the writeformat, which could result in a subsequent write error, if
     * the format is different. */
    if (f == NULL) {
       return 0;
    }
    filestream_close(f);
    ao2_ref(f, -1);
    return 0;
 }
ast_file_init()
int ast_file_init (void)
Provided by file.c
Definition at line 1983 of file file.c.
References ARRAY_LEN, ast_cli_register_multiple, ast_format_register_type(), ast_format_unregister_type(), ast_register_cleanup(), file_shutdown(), and STASIS_MESSAGE_TYPE_INIT.
Referenced by asterisk_daemon().
 {
    STASIS_MESSAGE_TYPE_INIT(ast_format_register_type);
    STASIS_MESSAGE_TYPE_INIT(ast_format_unregister_type);
    ast_cli_register_multiple(cli_file, ARRAY_LEN(cli_file));
    ast_register_cleanup(file_shutdown);
    return 0;
 }
ast_file_read_dirs()
int ast_file_read_dirs (const char * dir_name, ast_file_on_file on_file, void * obj, int max_depth)
Recursively iterate through files and directories up to max_depth.
Parameters
dir_name the name of the directory to search
on_file callback called on each file
obj user data object
max_depth re-curse into sub-directories up to a given maximum (-1 = infinite)
Returns
-1 or errno on failure, otherwise 0
Definition at line 1231 of file file.c.
References __ast_file_read_dirs(), ast_mutex_lock, ast_mutex_unlock, errno, and read_dirs_lock.
Referenced by ast_media_index_update_for_file(), AST_TEST_DEFINE(), module_load_helper(), and stasis_app_stored_recording_find_all().
 {
    int res;
    errno = 0;
 #if !defined(__GLIBC__)
    ast_mutex_lock(&read_dirs_lock);
 #endif
    res = __ast_file_read_dirs(dir_name, on_file, obj, max_depth);
 #if !defined(__GLIBC__)
    ast_mutex_unlock(&read_dirs_lock);
 #endif
    return res;
 }
ast_filecopy()
int ast_filecopy (const char * oldname, const char * newname, const char * fmt)
Copies a file.
Parameters
oldname name of the file you wish to copy (minus extension)
newname name you wish the file to be copied to (minus extension)
fmt the format of the file Copy a given file in a given format, or if fmt is NULL, then do so for all
Definition at line 1108 of file file.c.
References ACTION_COPY, and filehelper().
Referenced by copy_plain_file(), msg_create_from_file(), and vm_forwardoptions().
 {
    return filehelper(filename, filename2, fmt, ACTION_COPY);
 }
ast_filedelete()
int ast_filedelete (const char * filename, const char * fmt)
Deletes a file.
Parameters
filename name of the file you wish to delete (minus the extension)
fmt of the file Delete a given file in a given format, or if fmt is NULL, then do so for all
Definition at line 1098 of file file.c.
References ACTION_DELETE, filehelper(), and NULL.
Referenced by __ast_play_and_record(), announce_thread(), ast_monitor_start(), ast_monitor_stop(), async_delete_name_rec_task(), conf_free(), conf_rec_name(), conf_run(), confbridge_exec(), dial_exec_full(), handle_cli_file_convert(), leave_voicemail(), msg_create_from_file(), play_message(), play_record_review(), record_exec(), recording_cancel(), setup_privacy_args(), valid_priv_reply(), vm_allocate_dh(), and vm_delete().
 {
    return filehelper(filename, NULL, fmt, ACTION_DELETE);
 }
ast_fileexists()
int ast_fileexists (const char * filename, const char * fmt, const char * preflang)
Checks for the existence of a given file.
Parameters
filename name of the file you wish to check, minus the extension
fmt the format you wish to check (the extension)
preflang (the preferred language you wisht to find the file in) See if a given file exists in a given format. If fmt is NULL, any format is accepted.
Return values
0,false. The file does not exist
1,true. The file does exist.
Definition at line 1086 of file file.c.
References ast_alloca, buf, fileexists_core(), and NULL.
Referenced by announce_thread(), app_exec(), ast_get_character_str(), ast_get_digit_str(), ast_get_phonetic_str(), ast_moh_files_next(), ast_monitor_start(), ast_monitor_stop(), AST_TEST_DEFINE(), common_exec(), conf_run(), dial_exec_full(), eivr_comm(), forward_message(), get_folder(), invent_message(), leave_voicemail(), meetme_menu_admin_extended(), minivm_delete_exec(), msg_create_from_file(), page_exec(), play_file(), play_message(), play_message_by_id_helper(), play_message_callerid(), readexten_exec(), record_exec(), retrydial_exec(), sayname(), setup_privacy_args(), sound_file_exists(), stasis_app_control_record(), valid_priv_reply(), vm_allocate_dh(), vm_intro(), vm_msg_play(), vm_newuser_setup(), vm_options(), and vm_tempgreeting().
 {
    char *buf;
    int buflen;
    if (preflang == NULL)
       preflang = "";
    buflen = strlen(preflang) + strlen(filename) + 4;  /* room for everything */
    buf = ast_alloca(buflen);
    return fileexists_core(filename, fmt, preflang, buf, buflen, NULL) ? 1 : 0;
 }
ast_filerename()
int ast_filerename (const char * oldname, const char * newname, const char * fmt)
Renames a file.
Parameters
oldname the name of the file you wish to act upon (minus the extension)
newname the name you wish to rename the file to (minus the extension)
fmt the format of the file Rename a given file in a given format, or if fmt is NULL, then do so for all
Returns
-1 on failure
Definition at line 1103 of file file.c.
References ACTION_RENAME, and filehelper().
Referenced by __ast_play_and_record(), ast_monitor_stop(), forward_message(), leave_voicemail(), msg_create_from_file(), play_record_review(), rename_file(), and vm_forwardoptions().
 {
    return filehelper(filename, filename2, fmt, ACTION_RENAME);
 }
ast_format_def_unregister()
int ast_format_def_unregister (const char * name)
Unregisters a file format.
Parameters
name the name of the format you wish to unregister Unregisters a format based on the name of the format.
Return values
0 on success
-1 on failure to unregister
Definition at line 162 of file file.c.
References ast_format_unregister_type(), ast_free, ast_log, AST_RWLIST_REMOVE_CURRENT, AST_RWLIST_TRAVERSE_SAFE_BEGIN, AST_RWLIST_TRAVERSE_SAFE_END, AST_RWLIST_UNLOCK, AST_RWLIST_WRLOCK, ast_verb, ast_format_def::list, LOG_WARNING, ast_format_def::name, publish_format_update(), and tmp().
Referenced by unload_module().
 {
    struct ast_format_def *tmp;
    int res = -1;
    AST_RWLIST_WRLOCK(&formats);
    AST_RWLIST_TRAVERSE_SAFE_BEGIN(&formats, tmp, list) {
       if (!strcasecmp(name, tmp->name)) {
          AST_RWLIST_REMOVE_CURRENT(list);
          publish_format_update(tmp, ast_format_unregister_type());
          ast_free(tmp);
          res = 0;
       }
    }
    AST_RWLIST_TRAVERSE_SAFE_END;
    AST_RWLIST_UNLOCK(&formats);
    if (!res)
       ast_verb(2, "Unregistered format %s\n", name);
    else
       ast_log(LOG_WARNING, "Tried to unregister format %s, already unregistered\n", name);
    return res;
 }
ast_format_str_reduce()
char* ast_format_str_reduce (char * fmts)
Remove duplicate formats from a format string.
Parameters
fmts a format string, this string will be modified
Return values
NULL error
Returns
a pointer to the reduced format string, this is a pointer to fmts
Definition at line 1826 of file file.c.
References ast_log, AST_MAX_FORMATS, AST_RWLIST_RDLOCK, AST_RWLIST_TRAVERSE, AST_RWLIST_UNLOCK, ast_strdupa, ast_format_def::exts, exts_compare, first, len(), LOG_WARNING, NULL, strsep(), and type.
Referenced by actual_load_config(), and AST_TEST_DEFINE().
 {
    struct ast_format_def *f;
    struct ast_format_def *fmts_ptr[AST_MAX_FORMATS];
    char *fmts_str[AST_MAX_FORMATS];
    char *stringp, *type;
    char *orig = fmts;
    int i, j, x, first, found = 0;
    int len = strlen(fmts) + 1;
    int res;
    if (AST_RWLIST_RDLOCK(&formats)) {
       ast_log(LOG_WARNING, "Unable to lock format list\n");
       return NULL;
    }
    stringp = ast_strdupa(fmts);
    for (x = 0; (type = strsep(&stringp, "|")) && x < AST_MAX_FORMATS; x++) {
       AST_RWLIST_TRAVERSE(&formats, f, list) {
          if (exts_compare(f->exts, type)) {
             found = 1;
             break;
          }
       }
       fmts_str[x] = type;
       if (found) {
          fmts_ptr[x] = f;
       } else {
          fmts_ptr[x] = NULL;
       }
    }
    AST_RWLIST_UNLOCK(&formats);
    first = 1;
    for (i = 0; i < x; i++) {
       /* ignore invalid entries */
       if (!fmts_ptr[i]) {
          ast_log(LOG_WARNING, "ignoring unknown format '%s'\n", fmts_str[i]);
          continue;
       }
       /* special handling for the first entry */
       if (first) {
          res = snprintf(fmts, len, "%s", fmts_str[i]);
          fmts += res;
          len -= res;
          first = 0;
          continue;
       }
       found = 0;
       for (j = 0; j < i; j++) {
          /* this is a duplicate */
          if (fmts_ptr[j] == fmts_ptr[i]) {
             found = 1;
             break;
          }
       }
       if (!found) {
          res = snprintf(fmts, len, "|%s", fmts_str[i]);
          fmts += res;
          len -= res;
       }
    }
    if (first) {
       ast_log(LOG_WARNING, "no known formats found in format list (%s)\n", orig);
       return NULL;
    }
    return orig;
 }
ast_fsread_audio()
static int ast_fsread_audio (const void * data) static
Definition at line 962 of file file.c.
References ast_fsread_video(), ast_readaudio_callback(), and FSREAD_SUCCESS_SCHED.
Referenced by ast_readaudio_callback().
 {
    struct ast_filestream *fs = (struct ast_filestream *)data;
    enum fsread_res res;
    res = ast_readaudio_callback(fs);
    if (res == FSREAD_SUCCESS_SCHED)
       return 1;
    return 0;
 }
ast_fsread_video()
static int ast_fsread_video (const void * data) static
Definition at line 1007 of file file.c.
References ast_readvideo_callback(), and FSREAD_SUCCESS_SCHED.
Referenced by ast_fsread_audio().
 {
    struct ast_filestream *fs = (struct ast_filestream *)data;
    enum fsread_res res;
    res = ast_readvideo_callback(fs);
    if (res == FSREAD_SUCCESS_SCHED)
       return 1;
    return 0;
 }
ast_get_extension_for_mime_type()
int ast_get_extension_for_mime_type (const char * mime_type, char * buffer, size_t capacity)
Get a suitable filename extension for the given MIME type.
Parameters
mime_type The MIME type for which to find extensions
buffer A pointer to a buffer to receive the extension
capacity The size of 'buffer' in bytes
Return values
1 if an extension was found for the provided MIME type
0 if the MIME type was not found
Definition at line 1951 of file file.c.
References ast_assert, AST_RWLIST_TRAVERSE, ast_format_def::exts, formats::lock, lock, ast_format_def::mime_types, SCOPED_RDLOCK, and type_in_list().
Referenced by bucket_file_update_path().
 {
    struct ast_format_def *f;
    SCOPED_RDLOCK(lock, &formats.lock);
    ast_assert(buffer && capacity);
    AST_RWLIST_TRAVERSE(&formats, f, list) {
       if (type_in_list(f->mime_types, mime_type, strcasecmp)) {
          size_t item_len = strcspn(f->exts, "|");
          size_t bytes_written = snprintf(buffer, capacity, ".%.*s", (int) item_len, f->exts);
          if (bytes_written < capacity) {
             /* Only return success if we didn't truncate */
             return 1;
          }
       }
    }
    return 0;
 }
ast_get_format_for_file_ext()
struct ast_format* ast_get_format_for_file_ext (const char * file_ext)
Get the ast_format associated with the given file extension.
Since
12
Parameters
file_ext The file extension for which to find the format
Return values
NULL if not found
A pointer to the ast_format associated with this file extension
Definition at line 1938 of file file.c.
References AST_RWLIST_TRAVERSE, ast_format_def::exts, exts_compare, ast_format_def::format, formats::lock, lock, NULL, and SCOPED_RDLOCK.
Referenced by ast_ari_bridges_record(), ast_ari_channels_record(), ast_ari_recordings_get_stored_file(), bucket_file_update_path(), is_recording(), and process_media_file().
 {
    struct ast_format_def *f;
    SCOPED_RDLOCK(lock, &formats.lock);
    AST_RWLIST_TRAVERSE(&formats, f, list) {
       if (exts_compare(f->exts, file_ext)) {
          return f->format;
       }
    }
    return NULL;
 }
ast_openstream()
struct ast_filestream* ast_openstream (struct ast_channel * chan, const char * filename, const char * preflang)
Opens stream for use in seeking, playing.
Parameters
chan channel to work with
filename to use
preflang prefered language to use
Return values
a ast_filestream pointer if it opens the file.
NULL on error.
Definition at line 755 of file file.c.
References ast_openstream_full().
Referenced by ast_streamfile(), dictate_exec(), handle_getoption(), handle_streamfile(), and speech_streamfile().
 {
    return ast_openstream_full(chan, filename, preflang, 0);
 }
ast_openstream_full()
struct ast_filestream* ast_openstream_full (struct ast_channel * chan, const char * filename, const char * preflang, int asis)
Opens stream for use in seeking, playing.
Parameters
chan channel to work with
filename to use
preflang prefered language to use
asis if set, don't clear generators
Return values
a ast_filestream pointer if it opens the file.
NULL on error.
Definition at line 760 of file file.c.
References ACTION_OPEN, ao2_ref, ast_alloca, ast_channel_generator(), ast_channel_lock, ast_channel_set_oldwriteformat(), ast_channel_stream(), ast_channel_unlock, ast_channel_writeformat(), ast_deactivate_generator(), ast_format_cap_alloc, AST_FORMAT_CAP_FLAG_DEFAULT, ast_format_cap_has_type(), ast_log, AST_MEDIA_TYPE_AUDIO, ast_set_write_format_from_cap(), ast_stopstream(), buf, fileexists_core(), filehelper(), LOG_WARNING, and NULL.
Referenced by ast_moh_files_next(), ast_openstream(), and gen_nextfile().
 {
    /*
     * Use fileexists_core() to find a file in a compatible
     * language and format, set up a suitable translator,
     * and open the stream.
     */
    struct ast_format_cap *file_fmt_cap;
    int res;
    int buflen;
    char *buf;
    if (!asis) {
       /* do this first, otherwise we detect the wrong writeformat */
       ast_stopstream(chan);
       if (ast_channel_generator(chan))
          ast_deactivate_generator(chan);
    }
    if (preflang == NULL)
       preflang = "";
    buflen = strlen(preflang) + strlen(filename) + 4;
    buf = ast_alloca(buflen);
    if (!(file_fmt_cap = ast_format_cap_alloc(AST_FORMAT_CAP_FLAG_DEFAULT))) {
       return NULL;
    }
    if (!fileexists_core(filename, NULL, preflang, buf, buflen, file_fmt_cap) ||
       !ast_format_cap_has_type(file_fmt_cap, AST_MEDIA_TYPE_AUDIO)) {
       ast_log(LOG_WARNING, "File %s does not exist in any format\n", filename);
       ao2_ref(file_fmt_cap, -1);
       return NULL;
    }
    /* Set the channel to a format we can work with and save off the previous format. */
    ast_channel_lock(chan);
    ast_channel_set_oldwriteformat(chan, ast_channel_writeformat(chan));
    /* Set the channel to the best format that exists for the file. */
    res = ast_set_write_format_from_cap(chan, file_fmt_cap);
    ast_channel_unlock(chan);
    /* don't need this anymore now that the channel's write format is set. */
    ao2_ref(file_fmt_cap, -1);
    if (res == -1) {  /* No format available that works with this channel */
       return NULL;
    }
    res = filehelper(buf, chan, NULL, ACTION_OPEN);
    if (res >= 0)
       return ast_channel_stream(chan);
    return NULL;
 }
ast_openvstream()
struct ast_filestream* ast_openvstream (struct ast_channel * chan, const char * filename, const char * preflang)
Opens stream for use in seeking, playing.
Parameters
chan channel to work with
filename to use
preflang prefered language to use
Return values
a ast_filestream pointer if it opens the file.
NULL on error.
Definition at line 812 of file file.c.
References ACTION_OPEN, ao2_bump, ao2_cleanup, ao2_ref, ast_alloca, ast_channel_lock, ast_channel_nativeformats(), ast_channel_unlock, ast_channel_vstream(), ast_format_cap_alloc, ast_format_cap_count(), AST_FORMAT_CAP_FLAG_DEFAULT, ast_format_cap_get_format(), ast_format_cap_has_type(), ast_format_cap_iscompatible(), ast_format_get_name(), ast_format_get_type(), ast_log, AST_MEDIA_TYPE_VIDEO, buf, fileexists_core(), filehelper(), format, LOG_WARNING, and NULL.
Referenced by ast_streamfile(), handle_getoption(), and handle_streamfile().
 {
    /* As above, but for video. But here we don't have translators
     * so we must enforce a format.
     */
    struct ast_format_cap *nativeformats, *tmp_cap;
    char *buf;
    int buflen;
    int i, fd;
    if (preflang == NULL) {
       preflang = "";
    }
    buflen = strlen(preflang) + strlen(filename) + 4;
    buf = ast_alloca(buflen);
    ast_channel_lock(chan);
    nativeformats = ao2_bump(ast_channel_nativeformats(chan));
    ast_channel_unlock(chan);
    /* is the channel capable of video without translation ?*/
    if (!ast_format_cap_has_type(nativeformats, AST_MEDIA_TYPE_VIDEO)) {
       ao2_cleanup(nativeformats);
       return NULL;
    }
    if (!(tmp_cap = ast_format_cap_alloc(AST_FORMAT_CAP_FLAG_DEFAULT))) {
       ao2_cleanup(nativeformats);
       return NULL;
    }
    /* Video is supported, so see what video formats exist for this file */
    if (!fileexists_core(filename, NULL, preflang, buf, buflen, tmp_cap)) {
       ao2_ref(tmp_cap, -1);
       ao2_cleanup(nativeformats);
       return NULL;
    }
    /* iterate over file formats and pick the first one compatible with the channel's native formats */
    for (i = 0; i < ast_format_cap_count(tmp_cap); ++i) {
       struct ast_format *format = ast_format_cap_get_format(tmp_cap, i);
       if ((ast_format_get_type(format) != AST_MEDIA_TYPE_VIDEO) ||
          !ast_format_cap_iscompatible(nativeformats, tmp_cap)) {
          ao2_ref(format, -1);
          continue;
       }
       fd = filehelper(buf, chan, ast_format_get_name(format), ACTION_OPEN);
       if (fd >= 0) {
          ao2_ref(format, -1);
          ao2_ref(tmp_cap, -1);
          ao2_cleanup(nativeformats);
          return ast_channel_vstream(chan);
       }
       ast_log(LOG_WARNING, "File %s has video but couldn't be opened\n", filename);
       ao2_ref(format, -1);
    }
    ao2_ref(tmp_cap, -1);
    ao2_cleanup(nativeformats);
    return NULL;
 }
ast_playstream()
int ast_playstream (struct ast_filestream * s)
Play a open stream on a channel.
Parameters
s filestream to play
Return values
0 on success.
-1 on failure.
Definition at line 1026 of file file.c.
References ast_format_get_type(), AST_MEDIA_TYPE_AUDIO, ast_readaudio_callback(), ast_readvideo_callback(), ast_filestream::fmt, ast_format_def::format, and FSREAD_FAILURE.
Referenced by ast_streamfile(), handle_getoption(), handle_streamfile(), and speech_streamfile().
 {
    enum fsread_res res;
    if (ast_format_get_type(s->fmt->format) == AST_MEDIA_TYPE_AUDIO)
       res = ast_readaudio_callback(s);
    else
       res = ast_readvideo_callback(s);
    return (res == FSREAD_FAILURE) ? -1 : 0;
 }
ast_ratestream()
int ast_ratestream (struct ast_filestream * fs)
Return the sample rate of the stream's format.
Parameters
fs fs to act on
Returns
sample rate in Hz
Definition at line 1053 of file file.c.
References ast_format_get_sample_rate(), ast_filestream::fmt, and ast_format_def::format.
Referenced by msg_create_from_file().
 {
    return ast_format_get_sample_rate(fs->fmt->format);
 }
ast_readaudio_callback()
static enum fsread_res ast_readaudio_callback (struct ast_filestream * s) static
Definition at line 914 of file file.c.
References ast_channel_name(), ast_channel_sched(), ast_channel_streamid_set(), ast_channel_timingfd(), ast_debug, ast_format_get_sample_rate(), ast_frfree, ast_fsread_audio(), ast_sched_add(), ast_settimeout(), ast_settimeout_full(), ast_write(), ast_filestream::fmt, ast_format_def::format, FSREAD_FAILURE, FSREAD_SUCCESS_NOSCHED, FSREAD_SUCCESS_SCHED, ast_filestream::lasttimeout, NULL, ast_filestream::orig_chan_name, ast_filestream::owner, read_frame(), and roundf().
Referenced by ast_fsread_audio(), and ast_playstream().
 {
    int whennext = 0;
    while (!whennext) {
       struct ast_frame *fr;
       if (s->orig_chan_name && strcasecmp(ast_channel_name(s->owner), s->orig_chan_name)) {
          goto return_failure;
       }
       fr = read_frame(s, &whennext);
       if (!fr /* stream complete */ || ast_write(s->owner, fr) /* error writing */) {
          if (fr) {
             ast_debug(2, "Failed to write frame\n");
             ast_frfree(fr);
          }
          goto return_failure;
       }
       if (fr) {
          ast_frfree(fr);
       }
    }
    if (whennext != s->lasttimeout) {
       if (ast_channel_timingfd(s->owner) > -1) {
          float samp_rate = (float) ast_format_get_sample_rate(s->fmt->format);
          unsigned int rate;
          rate = (unsigned int) roundf(samp_rate / ((float) whennext));
          ast_settimeout_full(s->owner, rate, ast_fsread_audio, s, 1);
       } else {
          ast_channel_streamid_set(s->owner, ast_sched_add(ast_channel_sched(s->owner), whennext / (ast_format_get_sample_rate(s->fmt->format) / 1000), ast_fsread_audio, s));
       }
       s->lasttimeout = whennext;
       return FSREAD_SUCCESS_NOSCHED;
    }
    return FSREAD_SUCCESS_SCHED;
 return_failure:
    ast_channel_streamid_set(s->owner, -1);
    ast_settimeout(s->owner, 0, NULL, NULL);
    return FSREAD_FAILURE;
 }
ast_readfile()
struct ast_filestream* ast_readfile (const char * filename, const char * type, const char * comment, int flags, int check, mode_t mode)
Starts reading from a file.
Parameters
filename the name of the file to read from
type format of file you wish to read from
comment comment to go with
flags file flags
check (unimplemented, hence negligible)
mode Open mode Open an incoming file stream. flags are flags for the open() command, and if check is non-zero, then it will not read a file if there are any files that start with that name and have an extension Please note, this is a blocking function. Program execution will not return until ast_waitstream completes it's execution.
Return values
a struct ast_filestream on success.
NULL on failure.
Definition at line 1309 of file file.c.
References ast_closestream(), ast_free, ast_log, AST_RWLIST_RDLOCK, AST_RWLIST_TRAVERSE, AST_RWLIST_UNLOCK, ast_strdup, build_filename(), errno, ast_format_def::exts, exts_compare, ast_filestream::f, ast_filestream::filename, ast_filestream::flags, ast_filestream::fmt, get_filestream(), LOG_WARNING, ast_filestream::mode, NULL, open_wrapper(), ast_filestream::trans, and ast_filestream::vfs.
Referenced by __ast_play_and_record(), handle_cli_file_convert(), and msg_create_from_file().
 {
    FILE *bfile;
    struct ast_format_def *f;
    struct ast_filestream *fs = NULL;
    char *fn;
    int format_found = 0;
    AST_RWLIST_RDLOCK(&formats);
    AST_RWLIST_TRAVERSE(&formats, f, list) {
       fs = NULL;
       if (!exts_compare(f->exts, type))
          continue;
       else
          format_found = 1;
       fn = build_filename(filename, type);
       if (!fn) {
          continue;
       }
       errno = 0;
       bfile = fopen(fn, "r");
       if (!bfile || (fs = get_filestream(f, bfile)) == NULL || open_wrapper(fs) ) {
          ast_log(LOG_WARNING, "Unable to open %s\n", fn);
          if (fs) {
             ast_closestream(fs);
          }
          fs = NULL;
          bfile = NULL;
          ast_free(fn);
          break;
       }
       /* found it */
       fs->trans = NULL;
       fs->fmt = f;
       fs->flags = flags;
       fs->mode = mode;
       fs->filename = ast_strdup(filename);
       fs->vfs = NULL;
       ast_free(fn);
       break;
    }
    AST_RWLIST_UNLOCK(&formats);
    if (!format_found)
       ast_log(LOG_WARNING, "No such format '%s'\n", type);
    return fs;
 }
ast_readframe()
struct ast_frame* ast_readframe (struct ast_filestream * s)
Read a frame from a filestream.
Parameters
s ast_filestream to act on
Returns
a frame.
Return values
NULL if read failed.
Definition at line 899 of file file.c.
References read_frame().
Referenced by __ast_play_and_record(), dictate_exec(), gen_readframe(), handle_cli_file_convert(), and moh_files_readframe().
 {
    int whennext = 0;
    return read_frame(s, &whennext);
 }
ast_readvideo_callback()
static enum fsread_res ast_readvideo_callback (struct ast_filestream * s) static
Definition at line 977 of file file.c.
References ast_channel_sched(), ast_channel_vstreamid_set(), ast_debug, ast_format_get_sample_rate(), ast_frfree, ast_sched_add(), ast_write(), ast_filestream::fmt, ast_format_def::format, FSREAD_FAILURE, FSREAD_SUCCESS_NOSCHED, FSREAD_SUCCESS_SCHED, ast_filestream::lasttimeout, ast_filestream::owner, and read_frame().
Referenced by ast_fsread_video(), and ast_playstream().
 {
    int whennext = 0;
    while (!whennext) {
       struct ast_frame *fr = read_frame(s, &whennext);
       if (!fr /* stream complete */ || ast_write(s->owner, fr) /* error writing */) {
          if (fr) {
             ast_debug(2, "Failed to write frame\n");
             ast_frfree(fr);
          }
          ast_channel_vstreamid_set(s->owner, -1);
          return FSREAD_FAILURE;
       }
       if (fr) {
          ast_frfree(fr);
       }
    }
    if (whennext != s->lasttimeout) {
       ast_channel_vstreamid_set(s->owner, ast_sched_add(ast_channel_sched(s->owner), whennext / (ast_format_get_sample_rate(s->fmt->format) / 1000), ast_fsread_video, s));
       s->lasttimeout = whennext;
       return FSREAD_SUCCESS_NOSCHED;
    }
    return FSREAD_SUCCESS_SCHED;
 }
ast_seekstream()
int ast_seekstream (struct ast_filestream * fs, off_t sample_offset, int whence)
Seeks into stream.
Parameters
fs ast_filestream to perform seek on
sample_offset numbers of samples to seek
whence SEEK_SET, SEEK_CUR, SEEK_END
Return values
0 on success.
-1 on failure.
Definition at line 1038 of file file.c.
References ast_filestream::fmt, and ast_format_def::seek.
Referenced by __ast_read(), ast_moh_files_next(), ast_stream_fastforward(), ast_stream_rewind(), ast_streamfile(), ast_write_stream(), control_streamfile(), dictate_exec(), handle_getoption(), handle_recordfile(), handle_streamfile(), msg_create_from_file(), and speech_streamfile().
 {
    return fs->fmt->seek(fs, sample_offset, whence);
 }
ast_stopstream()
int ast_stopstream (struct ast_channel * c)
Stops a stream.
Parameters
c The channel you wish to stop playback on
Stop playback of a stream
Return values
0 always
Note
The channel does not need to be locked before calling this function.
Definition at line 187 of file file.c.
References ast_channel_lock, ast_channel_oldwriteformat(), ast_channel_stream(), ast_channel_stream_set(), ast_channel_unlock, ast_channel_vstream(), ast_channel_vstream_set(), ast_closestream(), ast_format_get_name(), ast_log, ast_set_write_format(), LOG_WARNING, and NULL.
Referenced by action_playback_and_continue(), adsi_transmit_message_full(), agent_alert(), announce_to_dial(), ast_openstream_full(), ast_play_and_wait(), ast_readstring_full(), ast_say_enumeration_full_da(), ast_say_enumeration_full_de(), ast_say_enumeration_full_en(), ast_say_enumeration_full_he(), ast_say_enumeration_full_is(), ast_say_enumeration_full_vi(), ast_say_number_full_cs(), ast_say_number_full_da(), ast_say_number_full_de(), ast_say_number_full_en(), ast_say_number_full_en_GB(), ast_say_number_full_es(), ast_say_number_full_fr(), ast_say_number_full_gr(), ast_say_number_full_he(), ast_say_number_full_hu(), ast_say_number_full_is(), ast_say_number_full_it(), ast_say_number_full_ja(), ast_say_number_full_ka(), ast_say_number_full_nl(), ast_say_number_full_no(), ast_say_number_full_pt(), ast_say_number_full_ru(), ast_say_number_full_se(), ast_say_number_full_th(), ast_say_number_full_ur(), ast_say_number_full_vi(), ast_say_number_full_zh(), background_detect_exec(), conf_exec(), conf_run(), control_streamfile(), dial_exec_full(), directory_exec(), grab_transfer(), handle_getoption(), handle_speechrecognize(), handle_streamfile(), ices_exec(), ivr_dispatch(), leave_voicemail(), meetme_menu_admin(), meetme_menu_admin_extended(), minivm_greet_exec(), mp3_exec(), NBScat_exec(), pbx_builtin_background(), pl_odtworz_plik(), play_file(), play_files_helper(), play_mailbox_owner(), playback_exec(), queue_exec(), read_exec(), readexten_exec(), record_exec(), recordthread(), s_streamwait3(), say_character_str_full(), say_digit_str_full(), say_money_str_full(), say_phonetic_str_full(), select_item_seq(), send_waveform_to_channel(), speech_background(), vm_authenticate(), vm_execmain(), wait_for_winner(), waitstream_core(), and zapateller_exec().
 {
    ast_channel_lock(tmp);
    /* Stop a running stream if there is one */
    if (ast_channel_stream(tmp)) {
       ast_closestream(ast_channel_stream(tmp));
       ast_channel_stream_set(tmp, NULL);
       if (ast_channel_oldwriteformat(tmp) && ast_set_write_format(tmp, ast_channel_oldwriteformat(tmp)))
          ast_log(LOG_WARNING, "Unable to restore format back to %s\n", ast_format_get_name(ast_channel_oldwriteformat(tmp)));
    }
    /* Stop the video stream too */
    if (ast_channel_vstream(tmp) != NULL) {
       ast_closestream(ast_channel_vstream(tmp));
       ast_channel_vstream_set(tmp, NULL);
    }
    ast_channel_unlock(tmp);
    return 0;
 }
ast_stream_and_wait()
int ast_stream_and_wait (struct ast_channel * chan, const char * file, const char * digits)
stream file until digit If the file name is non-empty, try to play it.
Note
If digits == "" then we can simply check for non-zero.
Returns
0 if success.
Return values
-1 if error.
digit if interrupted by a digit.
Definition at line 1814 of file file.c.
References ast_channel_language(), ast_streamfile(), ast_strlen_zero, and ast_waitstream().
Referenced by __ast_play_and_record(), action_playback(), action_toggle_mute_participants(), agent_alert(), agent_login_exec(), announce_user_count(), app_exec(), ast_bridge_channel_playfile(), ast_pickup_call(), ast_record_review(), bridge_features_duration_callback(), confbridge_exec(), directory_exec(), forward_message(), grab_transfer(), invent_message(), ivr_dispatch(), join_conference_bridge(), leave_voicemail(), limits_interval_playback(), mixmonitor_thread(), park_app_exec(), parked_call_app_exec(), play_file(), play_files_helper(), play_mailbox_owner(), play_message_callerid(), play_prompt_to_user(), play_record_review(), playback_common(), sayname(), select_item_seq(), setup_mixmonitor_ds(), stream_failsound(), vm_forwardoptions(), vmsayname_exec(), and wait_file2().
 {
    int res = 0;
    if (!ast_strlen_zero(file)) {
       res = ast_streamfile(chan, file, ast_channel_language(chan));
       if (!res) {
          res = ast_waitstream(chan, digits);
       }
    }
    return res;
 }
ast_stream_fastforward()
int ast_stream_fastforward (struct ast_filestream * fs, off_t ms)
Fast forward stream ms.
Parameters
fs filestream to act on
ms milliseconds to move
Return values
0 on success.
-1 on failure.
Definition at line 1058 of file file.c.
References ast_seekstream(), and DEFAULT_SAMPLES_PER_MS.
Referenced by waitstream_control().
 {
    return ast_seekstream(fs, ms * DEFAULT_SAMPLES_PER_MS, SEEK_CUR);
 }
ast_stream_rewind()
int ast_stream_rewind (struct ast_filestream * fs, off_t ms)
Rewind stream ms.
Parameters
fs filestream to act on
ms milliseconds to move
Return values
0 on success.
-1 on failure.
Definition at line 1063 of file file.c.
References ast_seekstream(), and DEFAULT_SAMPLES_PER_MS.
Referenced by __ast_play_and_record(), handle_recordfile(), record_exec(), and waitstream_control().
 {
    return ast_seekstream(fs, -ms * DEFAULT_SAMPLES_PER_MS, SEEK_CUR);
 }
ast_streamfile()
int ast_streamfile (struct ast_channel * c, const char * filename, const char * preflang)
Streams a file.
Parameters
c channel to stream the file to
filename the name of the file you wish to stream, minus the extension
preflang the preferred language you wish to have the file streamed to you in Prepares a channel for the streaming of a file. To start the stream, afterward do a ast_waitstream() on the channel Also, it will stop any existing streams on the channel.
Return values
0 on success.
-1 on failure.
Definition at line 1250 of file file.c.
References ast_applystream(), ast_channel_flags(), ast_channel_lock, ast_channel_name(), ast_channel_nativeformats(), ast_channel_unlock, ast_channel_writeformat(), ast_debug, AST_FLAG_MASQ_NOSTREAM, ast_format_cap_get_names(), AST_FORMAT_CAP_NAMES_LEN, ast_format_get_name(), ast_log, ast_openstream(), ast_openvstream(), ast_playstream(), ast_seekstream(), ast_str_alloca, ast_strdup, ast_test_flag, ast_test_suite_event_notify, ast_verb, errno, ast_filestream::f, ast_filestream::fmt, ast_format_def::format, LOG_WARNING, NULL, ast_filestream::orig_chan_name, VERBOSITY_ATLEAST, and ast_filestream::vfs.
Referenced by __analog_ss_thread(), action_playback_and_continue(), analog_ss_thread(), announce_thread(), announce_to_dial(), app_exec(), ast_app_getdata(), ast_app_getdata_full(), ast_play_and_wait(), ast_say_date_da(), ast_say_date_de(), ast_say_date_en(), ast_say_date_fr(), ast_say_date_gr(), ast_say_date_he(), ast_say_date_hu(), ast_say_date_is(), ast_say_date_ja(), ast_say_date_ka(), ast_say_date_nl(), ast_say_date_th(), ast_say_date_with_format_gr(), ast_say_datetime_en(), ast_say_datetime_fr(), ast_say_datetime_from_now_en(), ast_say_datetime_from_now_fr(), ast_say_datetime_from_now_he(), ast_say_datetime_from_now_ka(), ast_say_datetime_gr(), ast_say_datetime_he(), ast_say_datetime_ja(), ast_say_datetime_nl(), ast_say_datetime_pt(), ast_say_datetime_th(), ast_say_datetime_zh(), ast_say_enumeration_full_da(), ast_say_enumeration_full_de(), ast_say_enumeration_full_en(), ast_say_enumeration_full_he(), ast_say_enumeration_full_is(), ast_say_enumeration_full_vi(), ast_say_number_full_cs(), ast_say_number_full_da(), ast_say_number_full_de(), ast_say_number_full_en(), ast_say_number_full_en_GB(), ast_say_number_full_es(), ast_say_number_full_fr(), ast_say_number_full_gr(), ast_say_number_full_he(), ast_say_number_full_hu(), ast_say_number_full_is(), ast_say_number_full_it(), ast_say_number_full_ja(), ast_say_number_full_ka(), ast_say_number_full_nl(), ast_say_number_full_no(), ast_say_number_full_pt(), ast_say_number_full_ru(), ast_say_number_full_se(), ast_say_number_full_th(), ast_say_number_full_ur(), ast_say_number_full_vi(), ast_say_number_full_zh(), ast_say_time_de(), ast_say_time_en(), ast_say_time_fr(), ast_say_time_gr(), ast_say_time_hu(), ast_say_time_ja(), ast_say_time_ka(), ast_say_time_nl(), ast_say_time_zh(), ast_stream_and_wait(), auth_exec(), background_detect_exec(), common_exec(), conf_exec(), conf_get_pin(), conf_run(), control_streamfile(), dial_exec_full(), do_directory(), find_conf_realtime(), forward_message(), gr_say_number_female(), handle_recordfile(), invent_message(), leave_voicemail(), meetme_menu_admin(), meetme_menu_admin_extended(), meetme_menu_normal(), minivm_greet_exec(), page_exec(), pbx_builtin_background(), pl_odtworz_plik(), play_and_wait(), play_file(), play_record_review(), playback_exec(), privacy_exec(), readexten_exec(), record_exec(), retrydial_exec(), s_streamwait3(), say_character_str_full(), say_digit_str_full(), say_money_str_full(), say_phonetic_str_full(), select_item_menu(), setup_privacy_args(), vm_authenticate(), wait_file(), and wait_for_winner().
 {
    struct ast_filestream *fs;
    struct ast_filestream *vfs=NULL;
    off_t pos;
    int seekattempt;
    int res;
    fs = ast_openstream(chan, filename, preflang);
    if (!fs) {
       struct ast_str *codec_buf = ast_str_alloca(AST_FORMAT_CAP_NAMES_LEN);
       ast_channel_lock(chan);
       ast_log(LOG_WARNING, "Unable to open %s (format %s): %s\n",
          filename, ast_format_cap_get_names(ast_channel_nativeformats(chan), &codec_buf), strerror(errno));
       ast_channel_unlock(chan);
       return -1;
    }
    /* check to see if there is any data present (not a zero length file),
     * done this way because there is no where for ast_openstream_full to
     * return the file had no data. */
    pos = ftello(fs->f);
    seekattempt = fseeko(fs->f, -1, SEEK_END);
    if (seekattempt) {
       if (errno == EINVAL) {
          /* Zero-length file, as opposed to a pipe */
          return 0;
       } else {
          ast_seekstream(fs, 0, SEEK_SET);
       }
    } else {
       fseeko(fs->f, pos, SEEK_SET);
    }
    vfs = ast_openvstream(chan, filename, preflang);
    if (vfs) {
       ast_debug(1, "Ooh, found a video stream, too, format %s\n", ast_format_get_name(vfs->fmt->format));
    }
    if (ast_test_flag(ast_channel_flags(chan), AST_FLAG_MASQ_NOSTREAM))
       fs->orig_chan_name = ast_strdup(ast_channel_name(chan));
    if (ast_applystream(chan, fs))
       return -1;
    if (vfs && ast_applystream(chan, vfs))
       return -1;
    ast_test_suite_event_notify("PLAYBACK", "Message: %s\r\nChannel: %s", filename, ast_channel_name(chan));
    res = ast_playstream(fs);
    if (!res && vfs)
       res = ast_playstream(vfs);
    if (VERBOSITY_ATLEAST(3)) {
       ast_channel_lock(chan);
       ast_verb(3, "<%s> Playing '%s.%s' (language '%s')\n", ast_channel_name(chan), filename, ast_format_get_name(ast_channel_writeformat(chan)), preflang ? preflang : "default");
       ast_channel_unlock(chan);
    }
    return res;
 }
ast_tellstream()
off_t ast_tellstream (struct ast_filestream * fs)
Tell where we are in a stream.
Parameters
fs fs to act on
Returns
a long as a sample offset into stream
Definition at line 1048 of file file.c.
References ast_filestream::fmt, and ast_format_def::tell.
Referenced by __ast_play_and_record(), ast_moh_files_next(), control_streamfile(), handle_getoption(), handle_recordfile(), handle_speechrecognize(), handle_streamfile(), msg_create_from_file(), waitstream_control(), and waitstream_core().
 {
    return fs->fmt->tell(fs);
 }
ast_truncstream()
int ast_truncstream (struct ast_filestream * fs)
Trunc stream at current location.
Parameters
fs filestream to act on
Return values
0 on success.
-1 on failure.
Definition at line 1043 of file file.c.
References ast_filestream::fmt, and ast_format_def::trunc.
Referenced by __ast_play_and_record(), handle_recordfile(), and record_exec().
 {
    return fs->fmt->trunc(fs);
 }
ast_waitstream()
int ast_waitstream (struct ast_channel * c, const char * breakon)
Waits for a stream to stop or digit to be pressed.
Parameters
c channel to waitstream on
breakon string of DTMF digits to break upon Begins playback of a stream... Wait for a stream to stop or for any one of a given digit to arrive,
Return values
0 if the stream finishes
the character if it was interrupted by the channel.
-1 on error
Definition at line 1776 of file file.c.
References NULL, sanitize_waitstream_return(), and waitstream_core().
Referenced by __analog_ss_thread(), action_playback_and_continue(), analog_ss_thread(), announce_thread(), announce_to_dial(), app_exec(), ast_play_and_wait(), ast_say_date_da(), ast_say_date_de(), ast_say_date_en(), ast_say_date_fr(), ast_say_date_gr(), ast_say_date_he(), ast_say_date_hu(), ast_say_date_is(), ast_say_date_ja(), ast_say_date_ka(), ast_say_date_nl(), ast_say_date_th(), ast_say_date_with_format_gr(), ast_say_datetime_en(), ast_say_datetime_fr(), ast_say_datetime_from_now_en(), ast_say_datetime_from_now_fr(), ast_say_datetime_from_now_he(), ast_say_datetime_from_now_ka(), ast_say_datetime_gr(), ast_say_datetime_he(), ast_say_datetime_ja(), ast_say_datetime_nl(), ast_say_datetime_pt(), ast_say_datetime_th(), ast_say_datetime_zh(), ast_say_enumeration_full_da(), ast_say_enumeration_full_de(), ast_say_enumeration_full_en(), ast_say_enumeration_full_he(), ast_say_enumeration_full_is(), ast_say_enumeration_full_vi(), ast_say_number_full_cs(), ast_say_number_full_da(), ast_say_number_full_de(), ast_say_number_full_en(), ast_say_number_full_en_GB(), ast_say_number_full_es(), ast_say_number_full_fr(), ast_say_number_full_gr(), ast_say_number_full_he(), ast_say_number_full_hu(), ast_say_number_full_is(), ast_say_number_full_it(), ast_say_number_full_ja(), ast_say_number_full_ka(), ast_say_number_full_nl(), ast_say_number_full_no(), ast_say_number_full_pt(), ast_say_number_full_ru(), ast_say_number_full_se(), ast_say_number_full_th(), ast_say_number_full_ur(), ast_say_number_full_vi(), ast_say_number_full_zh(), ast_say_time_de(), ast_say_time_en(), ast_say_time_gr(), ast_say_time_he(), ast_say_time_hu(), ast_say_time_ja(), ast_say_time_ka(), ast_say_time_nl(), ast_say_time_zh(), ast_stream_and_wait(), auth_exec(), common_exec(), conf_exec(), conf_get_pin(), conf_run(), directory_exec(), find_conf_realtime(), gr_say_number_female(), handle_recordfile(), invent_message(), leave_voicemail(), meetme_menu_admin(), meetme_menu_admin_extended(), meetme_menu_normal(), minivm_greet_exec(), page_exec(), pbx_builtin_background(), pl_odtworz_plik(), play_and_wait(), play_file(), play_record_review(), playback_exec(), privacy_exec(), record_exec(), retrydial_exec(), s_streamwait3(), say_character_str_full(), say_digit_str_full(), say_money_str_full(), say_phonetic_str_full(), select_item_menu(), setup_privacy_args(), vm_authenticate(), and wait_file().
 {
    int res;
    res = waitstream_core(c, breakon, NULL, NULL, 0, -1, -1, NULL, NULL /* no callback */);
    return sanitize_waitstream_return(res);
 }
ast_waitstream_exten()
int ast_waitstream_exten (struct ast_channel * c, const char * context)
Waits for a stream to stop or digit matching a valid one digit exten to be pressed.
Parameters
c channel to waitstream on
context string of context to match digits to break upon Begins playback of a stream... Wait for a stream to stop or for any one of a valid extension digit to arrive,
Return values
0 if the stream finishes.
the character if it was interrupted.
-1 on error.
Definition at line 1795 of file file.c.
References ast_channel_context(), NULL, sanitize_waitstream_return(), and waitstream_core().
Referenced by pbx_builtin_background().
 {
    int res;
    /* Waitstream, with return in the case of a valid 1 digit extension */
    /* in the current or specified context being pressed */
    if (!context)
       context = ast_channel_context(c);
    res = waitstream_core(c, NULL, NULL, NULL, 0,
       -1, -1, context, NULL /* no callback */);
    return sanitize_waitstream_return(res);
 }
ast_waitstream_fr()
int ast_waitstream_fr (struct ast_channel * c, const char * breakon, const char * forward, const char * rewind, int ms)
Same as waitstream but allows stream to be forwarded or rewound.
Parameters
c channel to waitstream on
breakon string of DTMF digits to break upon
forward DTMF digit to fast forward upon
rewind DTMF digit to rewind upon
ms How many miliseconds to skip forward/back Begins playback of a stream... Wait for a stream to stop or for any one of a given digit to arrive,
Return values
0 if the stream finishes.
the character if it was interrupted,
the value of the control frame if it was interrupted by some other party,
-1 on error.
Definition at line 1745 of file file.c.
References NULL, and waitstream_core().
Referenced by control_streamfile().
 {
    return waitstream_core(c, breakon, forward, reverse, ms,
       -1 /* no audiofd */, -1 /* no cmdfd */, NULL /* no context */, NULL /* no callback */);
 }
ast_waitstream_fr_w_cb()
int ast_waitstream_fr_w_cb (struct ast_channel * c, const char * breakon, const char * forward, const char * rewind, int ms, ast_waitstream_fr_cb cb)
Same as waitstream_fr but allows a callback to be alerted when a user fastforwards or rewinds the file.
Parameters
c channel to waitstream on
breakon string of DTMF digits to break upon
forward DTMF digit to fast forward upon
rewind DTMF digit to rewind upon
ms How many milliseconds to skip forward/back
cb to call when rewind or fastfoward occurs. Begins playback of a stream... Wait for a stream to stop or for any one of a given digit to arrive,
Return values
0 if the stream finishes.
the character if it was interrupted,
the value of the control frame if it was interrupted by some other party,
-1 on error.
Definition at line 1734 of file file.c.
References NULL, and waitstream_core().
Referenced by control_streamfile().
 {
    return waitstream_core(c, breakon, forward, reverse, ms,
       -1 /* no audiofd */, -1 /* no cmdfd */, NULL /* no context */, cb);
 }
ast_waitstream_full()
int ast_waitstream_full (struct ast_channel * c, const char * breakon, int audiofd, int monfd)
Same as waitstream, but with audio output to fd and monitored fd checking.
Returns
1 if monfd is ready for reading
Definition at line 1785 of file file.c.
References NULL, sanitize_waitstream_return(), and waitstream_core().
Referenced by ast_readstring_full(), ast_say_enumeration_full_da(), ast_say_enumeration_full_de(), ast_say_enumeration_full_en(), ast_say_enumeration_full_he(), ast_say_enumeration_full_is(), ast_say_enumeration_full_vi(), ast_say_number_full_cs(), ast_say_number_full_da(), ast_say_number_full_de(), ast_say_number_full_en(), ast_say_number_full_en_GB(), ast_say_number_full_es(), ast_say_number_full_fr(), ast_say_number_full_gr(), ast_say_number_full_he(), ast_say_number_full_hu(), ast_say_number_full_is(), ast_say_number_full_it(), ast_say_number_full_ja(), ast_say_number_full_ka(), ast_say_number_full_nl(), ast_say_number_full_no(), ast_say_number_full_pt(), ast_say_number_full_ru(), ast_say_number_full_se(), ast_say_number_full_th(), ast_say_number_full_ur(), ast_say_number_full_vi(), ast_say_number_full_zh(), handle_getoption(), handle_streamfile(), pl_odtworz_plik(), s_streamwait3(), say_character_str_full(), say_digit_str_full(), say_money_str_full(), and say_phonetic_str_full().
 {
    int res;
    res = waitstream_core(c, breakon, NULL, NULL, 0,
       audiofd, cmdfd, NULL /* no context */, NULL /* no callback */);
    return sanitize_waitstream_return(res);
 }
ast_writefile()
struct ast_filestream* ast_writefile (const char * filename, const char * type, const char * comment, int flags, int check, mode_t mode)
Starts writing a file.
Parameters
filename the name of the file to write to
type format of file you wish to write out to
comment comment to go with
flags output file flags
check (unimplemented, hence negligible)
mode Open mode Create an outgoing file stream. oflags are flags for the open() command, and if check is non-zero, then it will not write a file if there are any files that start with that name and have an extension Please note, this is a blocking function. Program execution will not return until ast_waitstream completes it's execution.
Return values
a struct ast_filestream on success.
NULL on failure.
Definition at line 1361 of file file.c.
References ast_closestream(), ast_free, ast_log, ast_malloc, ast_opt_cache_record_files, AST_RWLIST_RDLOCK, AST_RWLIST_TRAVERSE, AST_RWLIST_UNLOCK, ast_strdup, buf, build_filename(), c, errno, ast_format_def::exts, exts_compare, ast_filestream::f, ast_filestream::filename, ast_filestream::flags, ast_filestream::fmt, get_filestream(), LOG_WARNING, ast_filestream::mode, NULL, ast_filestream::realfilename, record_cache_dir, rewrite_wrapper(), ast_format_def::seek, ast_filestream::trans, ast_filestream::vfs, and ast_filestream::write_buffer.
Referenced by __ast_play_and_record(), ast_monitor_start(), ast_writestream(), dictate_exec(), handle_cli_file_convert(), handle_recordfile(), mixmonitor_save_prep(), record_exec(), and recordthread().
 {
    int fd, myflags = 0;
    /* compiler claims this variable can be used before initialization... */
    FILE *bfile = NULL;
    struct ast_format_def *f;
    struct ast_filestream *fs = NULL;
    char *buf = NULL;
    size_t size = 0;
    int format_found = 0;
    AST_RWLIST_RDLOCK(&formats);
    /* set the O_TRUNC flag if and only if there is no O_APPEND specified */
    /* We really can't use O_APPEND as it will break WAV header updates */
    if (flags & O_APPEND) {
       flags &= ~O_APPEND;
    } else {
       myflags = O_TRUNC;
    }
    myflags |= O_WRONLY | O_CREAT;
    /* XXX need to fix this - we should just do the fopen,
     * not open followed by fdopen()
     */
    AST_RWLIST_TRAVERSE(&formats, f, list) {
       char *fn, *orig_fn = NULL;
       if (fs)
          break;
       if (!exts_compare(f->exts, type))
          continue;
       else
          format_found = 1;
       fn = build_filename(filename, type);
       if (!fn) {
          continue;
       }
       fd = open(fn, flags | myflags, mode);
       if (fd > -1) {
          /* fdopen() the resulting file stream */
          bfile = fdopen(fd, ((flags | myflags) & O_RDWR) ? "w+" : "w");
          if (!bfile) {
             ast_log(LOG_WARNING, "Whoa, fdopen failed: %s!\n", strerror(errno));
             close(fd);
             fd = -1;
          }
       }
       if (ast_opt_cache_record_files && (fd > -1)) {
          char *c;
          fclose(bfile); /* this also closes fd */
          /*
            We touch orig_fn just as a place-holder so other things (like vmail) see the file is there.
            What we are really doing is writing to record_cache_dir until we are done then we will mv the file into place.
          */
          orig_fn = ast_strdup(fn);
          for (c = fn; *c; c++)
             if (*c == '/')
                *c = '_';
          size = strlen(fn) + strlen(record_cache_dir) + 2;
          buf = ast_malloc(size);
          strcpy(buf, record_cache_dir);
          strcat(buf, "/");
          strcat(buf, fn);
          ast_free(fn);
          fn = buf;
          fd = open(fn, flags | myflags, mode);
          if (fd > -1) {
             /* fdopen() the resulting file stream */
             bfile = fdopen(fd, ((flags | myflags) & O_RDWR) ? "w+" : "w");
             if (!bfile) {
                ast_log(LOG_WARNING, "Whoa, fdopen failed: %s!\n", strerror(errno));
                close(fd);
                fd = -1;
             }
          }
       }
       if (fd > -1) {
          errno = 0;
          fs = get_filestream(f, bfile);
          if (fs) {
             if ((fs->write_buffer = ast_malloc(32768))) {
                setvbuf(fs->f, fs->write_buffer, _IOFBF, 32768);
             }
          }
          if (!fs || rewrite_wrapper(fs, comment)) {
             ast_log(LOG_WARNING, "Unable to rewrite %s\n", fn);
             close(fd);
             if (orig_fn) {
                unlink(fn);
                unlink(orig_fn);
                ast_free(orig_fn);
             }
             if (fs) {
                ast_closestream(fs);
                fs = NULL;
             }
             /*
              * 'fn' was has either been allocated from build_filename, or that was freed
              * and now 'fn' points to memory allocated for 'buf'. Either way the memory
              * now needs to be released.
              */
             ast_free(fn);
             continue;
          }
          fs->trans = NULL;
          fs->fmt = f;
          fs->flags = flags;
          fs->mode = mode;
          if (orig_fn) {
             fs->realfilename = orig_fn;
             fs->filename = fn;
             /*
              * The above now manages the memory allocated for 'orig_fn' and 'fn', so
              * set them to NULL, so they don't get released at the end of the loop.
              */
             orig_fn = NULL;
             fn = NULL;
          } else {
             fs->realfilename = NULL;
             fs->filename = ast_strdup(filename);
          }
          fs->vfs = NULL;
          /* If truncated, we'll be at the beginning; if not truncated, then append */
          f->seek(fs, 0, SEEK_END);
       } else if (errno != EEXIST) {
          ast_log(LOG_WARNING, "Unable to open file %s: %s\n", fn, strerror(errno));
          if (orig_fn)
             unlink(orig_fn);
       }
       /* Free 'fn', or if 'fn' points to 'buf' then free 'buf' */
       ast_free(fn);
       ast_free(orig_fn);
    }
    AST_RWLIST_UNLOCK(&formats);
    if (!format_found)
       ast_log(LOG_WARNING, "No such format '%s'\n", type);
    return fs;
 }
ast_writestream()
int ast_writestream (struct ast_filestream * fs, struct ast_frame * f)
Writes a frame to a stream.
Parameters
fs filestream to write to
f frame to write to the filestream Send a frame to a filestream – note: does NOT free the frame, call ast_frfree manually
Return values
0 on success.
-1 on failure.
Definition at line 209 of file file.c.
References ao2_replace, ast_debug, ast_format_cmp(), AST_FORMAT_CMP_EQUAL, AST_FORMAT_CMP_NOT_EQUAL, ast_format_get_name(), ast_format_get_type(), AST_FRAME_VIDEO, AST_FRAME_VOICE, ast_frfree, AST_LIST_NEXT, ast_log, AST_MEDIA_TYPE_AUDIO, ast_translate(), ast_translator_build_path(), ast_translator_free_path(), ast_writefile(), ast_filestream::filename, ast_filestream::flags, ast_filestream::fmt, ast_format_def::format, ast_frame_subclass::format, ast_frame::frametype, ast_filestream::lastwriteformat, LOG_WARNING, ast_filestream::mode, ast_format_def::name, NULL, ast_frame::subclass, ast_filestream::trans, type, ast_filestream::vfs, and ast_format_def::write.
Referenced by __ast_play_and_record(), __ast_read(), ast_write_stream(), dictate_exec(), handle_cli_file_convert(), handle_recordfile(), mixmonitor_thread(), record_exec(), and recordthread().
 {
    int res = -1;
    if (f->frametype == AST_FRAME_VIDEO) {
       if (ast_format_get_type(fs->fmt->format) == AST_MEDIA_TYPE_AUDIO) {
          /* This is the audio portion.  Call the video one... */
          if (!fs->vfs && fs->filename) {
             const char *type = ast_format_get_name(f->subclass.format);
             fs->vfs = ast_writefile(fs->filename, type, NULL, fs->flags, 0, fs->mode);
             ast_debug(1, "Opened video output file\n");
          }
          if (fs->vfs)
             return ast_writestream(fs->vfs, f);
          /* else ignore */
          return 0;
       }
    } else if (f->frametype != AST_FRAME_VOICE) {
       ast_log(LOG_WARNING, "Tried to write non-voice frame\n");
       return -1;
    }
    if (ast_format_cmp(f->subclass.format, fs->fmt->format) != AST_FORMAT_CMP_NOT_EQUAL) {
       res =  fs->fmt->write(fs, f);
       if (res < 0)
          ast_log(LOG_WARNING, "Natural write failed\n");
       else if (res > 0)
          ast_log(LOG_WARNING, "Huh??\n");
    } else {
       /* XXX If they try to send us a type of frame that isn't the normal frame, and isn't
              the one we've setup a translator for, we do the "wrong thing" XXX */
       if (fs->trans && (ast_format_cmp(f->subclass.format, fs->lastwriteformat) != AST_FORMAT_CMP_EQUAL)) {
          ast_translator_free_path(fs->trans);
          fs->trans = NULL;
       }
       if (!fs->trans) {
          fs->trans = ast_translator_build_path(fs->fmt->format, f->subclass.format);
       }
       if (!fs->trans) {
          ast_log(LOG_WARNING, "Unable to translate to format %s, source format %s\n",
             fs->fmt->name, ast_format_get_name(f->subclass.format));
       } else {
          struct ast_frame *trf;
          ao2_replace(fs->lastwriteformat, f->subclass.format);
          /* Get the translated frame but don't consume the original in case they're using it on another stream */
          if ((trf = ast_translate(fs->trans, f, 0))) {
             struct ast_frame *cur;
             /* the translator may have returned multiple frames, so process them */
             for (cur = trf; cur; cur = AST_LIST_NEXT(cur, frame_list)) {
                if ((res = fs->fmt->write(fs, trf))) {
                   ast_log(LOG_WARNING, "Translated frame write failed\n");
                   break;
                }
             }
             ast_frfree(trf);
          } else {
             res = 0;
          }
       }
    }
    return res;
 }
build_filename()
static char* build_filename (const char * filename, const char * ext) static
construct a filename. Absolute pathnames are preserved, relative names are prefixed by the sounds/ directory. The wav49 suffix is replaced by 'WAV'. Returns a malloc'ed string to be freed by the caller.
Definition at line 314 of file file.c.
References ast_asprintf, ast_config_AST_DATA_DIR, and NULL.
Referenced by ast_readfile(), ast_writefile(), and filehelper().
 {
    char *fn = NULL;
    /* The wav49 -> WAV translation is duplicated in apps/app_mixmonitor.c, so
       if you change it here you need to change it there as well */
    if (!strcmp(ext, "wav49"))
       ext = "WAV";
    if (filename[0] == '/') {
       if (ast_asprintf(&fn, "%s.%s", filename, ext) < 0) {
          fn = NULL;
       }
    } else {
       if (ast_asprintf(&fn, "%s/sounds/%s.%s",
               ast_config_AST_DATA_DIR, filename, ext) < 0) {
          fn = NULL;
       }
    }
    return fn;
 }
copy()
static int copy (const char * infile, const char * outfile) static
Definition at line 271 of file file.c.
References AST_FILE_MODE, ast_log, buf, errno, len(), and LOG_WARNING.
Referenced by filehelper().
 {
    int ifd, ofd, len;
    char buf[4096];   /* XXX make it lerger. */
    if ((ifd = open(infile, O_RDONLY)) < 0) {
       ast_log(LOG_WARNING, "Unable to open %s in read-only mode\n", infile);
       return -1;
    }
    if ((ofd = open(outfile, O_WRONLY | O_TRUNC | O_CREAT, AST_FILE_MODE)) < 0) {
       ast_log(LOG_WARNING, "Unable to open %s in write-only mode\n", outfile);
       close(ifd);
       return -1;
    }
    while ( (len = read(ifd, buf, sizeof(buf)) ) ) {
       int res;
       if (len < 0) {
          ast_log(LOG_WARNING, "Read failed on %s: %s\n", infile, strerror(errno));
          break;
       }
       /* XXX handle partial writes */
       res = write(ofd, buf, len);
       if (res != len) {
          ast_log(LOG_WARNING, "Write failed on %s (%d of %d): %s\n", outfile, res, len, strerror(errno));
          len = -1; /* error marker */
          break;
       }
    }
    close(ifd);
    close(ofd);
    if (len < 0) {
       unlink(outfile);
       return -1; /* error */
    }
    return 0;   /* success */
 }
file_shutdown()
static void file_shutdown (void) static
Definition at line 1976 of file file.c.
References ARRAY_LEN, ast_cli_unregister_multiple(), ast_format_register_type(), ast_format_unregister_type(), and STASIS_MESSAGE_TYPE_CLEANUP.
Referenced by ast_file_init().
 {
    ast_cli_unregister_multiple(cli_file, ARRAY_LEN(cli_file));
    STASIS_MESSAGE_TYPE_CLEANUP(ast_format_register_type);
    STASIS_MESSAGE_TYPE_CLEANUP(ast_format_unregister_type);
 }
fileexists_core()
static int fileexists_core (const char * filename, const char * fmt, const char * preflang, char * buf, int buflen, struct ast_format_cap * result_cap) static
helper routine to locate a file with a given format and language preference.
Note
Try preflang, preflang with stripped '_' suffices, or NULL.
The last parameter(s) point to a buffer of sufficient size, which on success is filled with the matching filename.
Parameters
filename Name of the file.
fmt Format to look for the file in. OPTIONAL
preflang The perfered language
buf Returns the matching filename
buflen Size of the buf
result_cap OPTIONAL format capabilities result structure returns what formats the file was found in.
Return values
1,true. file exists and result format is set
0,false. file does not exist.
Definition at line 706 of file file.c.
References ast_strdupa, ast_strlen_zero, DEFAULT_LANGUAGE, end, fileexists_test(), and NULL.
Referenced by ast_fileexists(), ast_openstream_full(), and ast_openvstream().
 {
    char *lang;
    if (buf == NULL) {
       return 0;
    }
    /* We try languages in the following order:
     *    preflang (may include dialect and style codes)
     *    lang (preflang without dialect - if any)
     *    <none>
     *    default (unless the same as preflang or lang without dialect)
     */
    lang = ast_strdupa(preflang);
    /* Try preferred language, including removing any style or dialect codes */
    while (!ast_strlen_zero(lang)) {
       char *end;
       if (fileexists_test(filename, fmt, lang, buf, buflen, result_cap)) {
          return 1;
       }
       if ((end = strrchr(lang, '_')) != NULL) {
          *end = '\0';
          continue;
       }
       break;
    }
    /* Try without any language */
    if (fileexists_test(filename, fmt, NULL, buf, buflen, result_cap)) {
       return 1;
    }
    /* Finally try the default language unless it was already tried before */
    if ((ast_strlen_zero(preflang) || strcmp(preflang, DEFAULT_LANGUAGE)) && (ast_strlen_zero(lang) || strcmp(lang, DEFAULT_LANGUAGE))) {
       if ((fileexists_test(filename, fmt, DEFAULT_LANGUAGE, buf, buflen, result_cap)) > 0) {
          return 1;
       }
    }
    return 0;
 }
fileexists_test()
static int fileexists_test (const char * filename, const char * fmt, const char * lang, char * buf, int buflen, struct ast_format_cap * result_cap) static
test if a file exists for a given format.
Note
result_cap is OPTIONAL
Return values
1,true and result_cap represents format capabilities file exists in.
0,false
Definition at line 656 of file file.c.
References ACTION_EXISTS, ast_language_is_prefix, ast_media_cache_retrieve(), c, filehelper(), is_absolute_path(), is_remote_path(), and NULL.
Referenced by fileexists_core().
 {
    if (buf == NULL) {
       return 0;
    }
    if (is_remote_path(filename) && !ast_media_cache_retrieve(filename, NULL, buf, buflen)) {
       return filehelper(buf, result_cap, NULL, ACTION_EXISTS);
    }
    if (ast_language_is_prefix && !is_absolute_path(filename)) { /* new layout */
       if (lang) {
          snprintf(buf, buflen, "%s/%s", lang, filename);
       } else {
          snprintf(buf, buflen, "%s", filename);
       }
    } else { /* old layout */
       strcpy(buf, filename);  /* first copy the full string */
       if (lang) {
          /* insert the language and suffix if needed */
          const char *c = strrchr(filename, '/');
          int offset = c ? c - filename + 1 : 0; /* points right after the last '/' */
          snprintf(buf + offset, buflen - offset, "%s/%s", lang, filename + offset);
       }
    }
    return filehelper(buf, result_cap, fmt, ACTION_EXISTS);
 }
filehelper()
static int filehelper (const char * filename, const void * arg2, const char * fmt, const enum file_action action) static
Definition at line 514 of file file.c.
References ACTION_COPY, ACTION_DELETE, ACTION_EXISTS, ACTION_OPEN, ACTION_RENAME, ast_channel_stream(), ast_channel_stream_set(), ast_channel_vstream(), ast_channel_vstream_set(), ast_channel_writeformat(), ast_closestream(), ast_format_cap_append, ast_format_cmp(), AST_FORMAT_CMP_NOT_EQUAL, ast_format_get_type(), ast_free, ast_log, AST_MEDIA_TYPE_AUDIO, AST_MEDIA_TYPE_VIDEO, AST_RWLIST_RDLOCK, AST_RWLIST_TRAVERSE, AST_RWLIST_UNLOCK, build_filename(), copy(), errno, ext, ast_format_def::exts, exts_compare, ast_filestream::f, ast_filestream::filename, ast_filestream::fmt, ast_format_def::format, get_filestream(), ast_filestream::lasttimeout, LOG_WARNING, NULL, open_wrapper(), strsep(), and ast_filestream::trans.
Referenced by ast_filecopy(), ast_filedelete(), ast_filerename(), ast_openstream_full(), ast_openvstream(), and fileexists_test().
 {
    struct ast_format_def *f;
    int res = (action == ACTION_EXISTS) ? 0 : -1;
    AST_RWLIST_RDLOCK(&formats);
    /* Check for a specific format */
    AST_RWLIST_TRAVERSE(&formats, f, list) {
       char *ext = NULL;
       char storage[strlen(f->exts) + 1];
       char *stringp;
       if (fmt && !exts_compare(f->exts, fmt))
          continue;
       /* Look for a file matching the supported extensions.
        * The file must exist, and for OPEN, must match
        * one of the formats supported by the channel.
        */
       strcpy(storage, f->exts); /* safe - this is in the stack so does not need to be freed */
       stringp = storage;
       while ( (ext = strsep(&stringp, "|")) ) {
          struct stat st;
          char *fn = build_filename(filename, ext);
          if (fn == NULL)
             continue;
          if ( stat(fn, &st) ) { /* file not existent */
             ast_free(fn);
             continue;
          }
          /* for 'OPEN' we need to be sure that the format matches
           * what the channel can process
           */
          if (action == ACTION_OPEN) {
             struct ast_channel *chan = (struct ast_channel *)arg2;
             FILE *bfile;
             struct ast_filestream *s;
             if ((ast_format_cmp(ast_channel_writeformat(chan), f->format) == AST_FORMAT_CMP_NOT_EQUAL) &&
                  !(((ast_format_get_type(f->format) == AST_MEDIA_TYPE_AUDIO) && fmt) ||
                  ((ast_format_get_type(f->format) == AST_MEDIA_TYPE_VIDEO) && fmt))) {
                ast_free(fn);
                continue;   /* not a supported format */
             }
             if ( (bfile = fopen(fn, "r")) == NULL) {
                ast_free(fn);
                continue;   /* cannot open file */
             }
             s = get_filestream(f, bfile);
             if (!s) {
                fclose(bfile);
                ast_free(fn);  /* cannot allocate descriptor */
                continue;
             }
             if (open_wrapper(s)) {
                ast_free(fn);
                ast_closestream(s);
                continue;   /* cannot run open on file */
             }
             if (st.st_size == 0) {
                ast_log(LOG_WARNING, "File %s detected to have zero size.\n", fn);
             }
             /* ok this is good for OPEN */
             res = 1; /* found */
             s->lasttimeout = -1;
             s->fmt = f;
             s->trans = NULL;
             s->filename = NULL;
             if (ast_format_get_type(s->fmt->format) == AST_MEDIA_TYPE_AUDIO) {
                if (ast_channel_stream(chan))
                   ast_closestream(ast_channel_stream(chan));
                ast_channel_stream_set(chan, s);
             } else {
                if (ast_channel_vstream(chan))
                   ast_closestream(ast_channel_vstream(chan));
                ast_channel_vstream_set(chan, s);
             }
             ast_free(fn);
             break;
          }
          switch (action) {
          case ACTION_OPEN:
             break;   /* will never get here */
          case ACTION_EXISTS:  /* return the matching format */
             /* if arg2 is present, it is a format capabilities structure.
              * Add this format to the set of formats this file can be played in */
             if (arg2) {
                ast_format_cap_append((struct ast_format_cap *) arg2, f->format, 0);
             }
             res = 1; /* file does exist and format it exists in is returned in arg2 */
             break;
          case ACTION_DELETE:
             if ( (res = unlink(fn)) )
                ast_log(LOG_WARNING, "unlink(%s) failed: %s\n", fn, strerror(errno));
             break;
          case ACTION_RENAME:
          case ACTION_COPY: {
             char *nfn = build_filename((const char *)arg2, ext);
             if (!nfn)
                ast_log(LOG_WARNING, "Out of memory\n");
             else {
                res = action == ACTION_COPY ? copy(fn, nfn) : rename(fn, nfn);
                if (res)
                   ast_log(LOG_WARNING, "%s(%s,%s) failed: %s\n",
                      action == ACTION_COPY ? "copy" : "rename",
                       fn, nfn, strerror(errno));
                ast_free(nfn);
             }
              }
             break;
          default:
             ast_log(LOG_WARNING, "Unknown helper %u\n", action);
          }
          ast_free(fn);
       }
    }
    AST_RWLIST_UNLOCK(&formats);
    return res;
 }
filestream_close()
static void filestream_close (struct ast_filestream * f) static
Definition at line 357 of file file.c.
References ast_channel_sched(), ast_channel_stream_set(), ast_channel_streamid(), ast_channel_streamid_set(), ast_channel_vstream_set(), ast_channel_vstreamid(), ast_channel_vstreamid_set(), ast_format_get_type(), ast_log, AST_LOG_WARNING, AST_MEDIA_TYPE_AUDIO, AST_MEDIA_TYPE_VIDEO, AST_SCHED_DEL_ACCESSOR, ast_settimeout(), ast_filestream::fmt, ast_format_def::format, ast_format_def::name, NULL, and ast_filestream::owner.
Referenced by ast_closestream(), and filestream_destructor().
 {
    enum ast_media_type format_type = ast_format_get_type(f->fmt->format);
    if (!f->owner) {
       return;
    }
    /* Stop a running stream if there is one */
    switch (format_type)
    {
    case AST_MEDIA_TYPE_AUDIO:
       ast_channel_stream_set(f->owner, NULL);
       AST_SCHED_DEL_ACCESSOR(ast_channel_sched(f->owner), f->owner, ast_channel_streamid, ast_channel_streamid_set);
       ast_settimeout(f->owner, 0, NULL, NULL);
       break;
    case AST_MEDIA_TYPE_VIDEO:
       ast_channel_vstream_set(f->owner, NULL);
       AST_SCHED_DEL_ACCESSOR(ast_channel_sched(f->owner), f->owner, ast_channel_vstreamid, ast_channel_vstreamid_set);
       break;
    default:
       ast_log(AST_LOG_WARNING, "Unable to schedule deletion of filestream with unsupported type %s\n", f->fmt->name);
       break;
    }
 }
filestream_destructor()
static void filestream_destructor (void * arg) static
Definition at line 383 of file file.c.
References ao2_cleanup, ast_closestream(), ast_free, ast_module_unref, ast_safe_fork(), ast_translator_free_path(), ast_format_def::close, ast_filestream::f, ast_filestream::filename, filestream_close(), ast_filestream::fmt, ast_frame_subclass::format, ast_filestream::fr, ast_filestream::lastwriteformat, ast_format_def::module, ast_filestream::orig_chan_name, ast_filestream::realfilename, SENTINEL, status, ast_frame::subclass, ast_filestream::trans, ast_filestream::vfs, and ast_filestream::write_buffer.
Referenced by get_filestream().
 {
    struct ast_filestream *f = arg;
    int status;
    int pid = -1;
    /* Stop a running stream if there is one */
    filestream_close(f);
    /* destroy the translator on exit */
    if (f->trans)
       ast_translator_free_path(f->trans);
    if (f->fmt->close) {
       void (*closefn)(struct ast_filestream *) = f->fmt->close;
       closefn(f);
    }
    if (f->f) {
       fclose(f->f);
    }
    if (f->realfilename && f->filename) {
       pid = ast_safe_fork(0);
       if (!pid) {
          execl("/bin/mv", "mv", "-f", f->filename, f->realfilename, SENTINEL);
          _exit(1);
       }
       else if (pid > 0) {
          /* Block the parent until the move is complete.*/
          waitpid(pid, &status, 0);
       }
    }
    ast_free(f->filename);
    ast_free(f->realfilename);
    if (f->vfs)
       ast_closestream(f->vfs);
    ast_free(f->write_buffer);
    ast_free((void *)f->orig_chan_name);
    ao2_cleanup(f->lastwriteformat);
    ao2_cleanup(f->fr.subclass.format);
    ast_module_unref(f->fmt->module);
 }
fn_wrapper()
static int fn_wrapper (struct ast_filestream * s, const char * comment, enum wrap_fn mode) static
Definition at line 468 of file file.c.
References ast_log, ast_filestream::fmt, LOG_WARNING, ast_format_def::name, ast_format_def::open, ast_format_def::rewrite, and WRAP_OPEN.
Referenced by open_wrapper(), and rewrite_wrapper().
 {
    struct ast_format_def *f = s->fmt;
    int ret = -1;
    int (*openfn)(struct ast_filestream *s);
    if (mode == WRAP_OPEN && (openfn = f->open) && openfn(s))
       ast_log(LOG_WARNING, "Unable to open format %s\n", f->name);
    else if (mode == WRAP_REWRITE && f->rewrite && f->rewrite(s, comment))
       ast_log(LOG_WARNING, "Unable to rewrite format %s\n", f->name);
    else {
       /* preliminary checks succeed. */
       ret = 0;
    }
    return ret;
 }
get_filestream()
static struct ast_filestream* get_filestream (struct ast_format_def * fmt, FILE * bfile) static
Definition at line 428 of file file.c.
References ast_filestream::_private, ao2_alloc, ao2_bump, ast_format_get_type(), AST_FRAME_VIDEO, AST_FRAME_VOICE, AST_MEDIA_TYPE_AUDIO, AST_MEDIA_TYPE_VIDEO, ast_module_running_ref, ast_module_unref, ast_filestream::buf, ast_format_def::buf_size, ast_format_def::desc_size, ast_filestream::f, filestream_destructor(), ast_filestream::fmt, ast_format_def::format, ast_frame_subclass::format, ast_filestream::fr, ast_frame::frametype, if(), ast_frame::mallocd, ast_format_def::module, ast_format_def::name, NULL, ast_frame::src, and ast_frame::subclass.
Referenced by ast_readfile(), ast_writefile(), and filehelper().
 {
    struct ast_filestream *s;
    int l = sizeof(*s) + fmt->buf_size + fmt->desc_size;  /* total allocation size */
    if (!ast_module_running_ref(fmt->module)) {
       return NULL;
    }
    s = ao2_alloc(l, filestream_destructor);
    if (!s) {
       ast_module_unref(fmt->module);
       return NULL;
    }
    s->fmt = fmt;
    s->f = bfile;
    if (fmt->desc_size)
       s->_private = ((char *)(s + 1)) + fmt->buf_size;
    if (fmt->buf_size)
       s->buf = (char *)(s + 1);
    s->fr.src = fmt->name;
    if (ast_format_get_type(fmt->format) == AST_MEDIA_TYPE_AUDIO) {
       s->fr.frametype = AST_FRAME_VOICE;
    } else if (ast_format_get_type(fmt->format) == AST_MEDIA_TYPE_VIDEO) {
       s->fr.frametype = AST_FRAME_VIDEO;
    }
    s->fr.mallocd = 0;
    s->fr.subclass.format = ao2_bump(fmt->format);
    return s;
 }
handle_cli_core_show_file_formats()
static char* handle_cli_core_show_file_formats (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) static
Definition at line 1902 of file file.c.
References ast_cli_args::argc, ast_cli(), ast_format_get_name(), AST_RWLIST_RDLOCK, AST_RWLIST_TRAVERSE, AST_RWLIST_UNLOCK, CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::command, ast_format_def::exts, ast_cli_args::fd, ast_format_def::format, FORMAT, FORMAT2, ast_format_def::name, NULL, and ast_cli_entry::usage.
 {
 #define FORMAT "%-10s %-10s %-20s\n"
 #define FORMAT2 "%-10s %-10s %-20s\n"
    struct ast_format_def *f;
    int count_fmt = 0;
    switch (cmd) {
    case CLI_INIT:
       e->command = "core show file formats";
       e->usage =
          "Usage: core show file formats\n"
          "       Displays currently registered file formats (if any).\n";
       return NULL;
    case CLI_GENERATE:
       return NULL;
    }
    if (a->argc != 4)
       return CLI_SHOWUSAGE;
    ast_cli(a->fd, FORMAT, "Format", "Name", "Extensions");
    ast_cli(a->fd, FORMAT, "------", "----", "----------");
    AST_RWLIST_RDLOCK(&formats);
    AST_RWLIST_TRAVERSE(&formats, f, list) {
       ast_cli(a->fd, FORMAT2, ast_format_get_name(f->format), f->name, f->exts);
       count_fmt++;
    }
    AST_RWLIST_UNLOCK(&formats);
    ast_cli(a->fd, "%d file formats registered.\n", count_fmt);
    return CLI_SUCCESS;
 #undef FORMAT
 #undef FORMAT2
 }
is_absolute_path()
static int is_absolute_path (const char * filename) static
Definition at line 640 of file file.c.
Referenced by fileexists_test().
 {
    return filename[0] == '/';
 }
is_remote_path()
static int is_remote_path (const char * filename) static
Definition at line 645 of file file.c.
Referenced by fileexists_test().
 {
    return strstr(filename, "://") ? 1 : 0;
 }
json_array_from_list()
static struct ast_json* json_array_from_list (const char * list, const char * sep) static
Definition at line 74 of file file.c.
References array(), ast_json_array_append(), ast_json_array_create(), ast_json_ref(), ast_json_string_create(), ast_json_unref(), ast_strdupa, ext, NULL, RAII_VAR, and strsep().
Referenced by publish_format_update().
 {
    RAII_VAR(struct ast_json *, array, ast_json_array_create(), ast_json_unref);
    char *stringp, *ext;
    stringp = ast_strdupa(list);  /* this is in the stack so does not need to be freed */
    if (!array || !stringp) {
       return NULL;
    }
    while ((ext = strsep(&stringp, sep))) {
       if (ast_json_array_append(array, ast_json_string_create(ext))) {
          return NULL;
       }
    }
    return ast_json_ref(array);
 }
open_wrapper()
static int open_wrapper (struct ast_filestream * s) static
Definition at line 490 of file file.c.
References fn_wrapper(), NULL, and WRAP_OPEN.
Referenced by ast_readfile(), and filehelper().
 {
    return fn_wrapper(s, NULL, WRAP_OPEN);
 }
publish_format_update()
static int publish_format_update (const struct ast_format_def * f, struct stasis_message_type * type) static
Definition at line 93 of file file.c.
References ao2_cleanup, ast_json_pack(), ast_json_payload_create(), ast_json_unref(), ast_system_topic(), ast_format_def::exts, json_array_from_list(), ast_format_def::name, NULL, RAII_VAR, stasis_message_create(), and stasis_publish().
Referenced by __ast_format_def_register(), and ast_format_def_unregister().
 {
    RAII_VAR(struct stasis_message *, msg, NULL, ao2_cleanup);
    RAII_VAR(struct ast_json_payload *, json_payload, NULL, ao2_cleanup);
    RAII_VAR(struct ast_json *, json_object, NULL, ast_json_unref);
    if (!type) {
       return -1;
    }
    json_object = ast_json_pack("{s: s, s: o}",
       "format", f->name,
       "extensions", json_array_from_list(f->exts, "|"));
    if (!json_object) {
       return -1;
    }
    json_payload = ast_json_payload_create(json_object);
    if (!json_payload) {
       return -1;
    }
    msg = stasis_message_create(type, json_payload);
    if (!msg) {
       return -1;
    }
    stasis_publish(ast_system_topic(), msg);
    return 0;
 }
read_frame()
static struct ast_frame* read_frame (struct ast_filestream * s, int * whennext) static
Definition at line 874 of file file.c.
References ast_frfree, ast_frisolate, ast_filestream::fmt, NULL, and ast_format_def::read.
Referenced by ast_readaudio_callback(), ast_readframe(), ast_readvideo_callback(), and audiohook_read_frame_helper().
 {
    struct ast_frame *fr, *new_fr;
    if (!s || !s->fmt) {
       return NULL;
    }
    if (!(fr = s->fmt->read(s, whennext))) {
       return NULL;
    }
    if (!(new_fr = ast_frisolate(fr))) {
       ast_frfree(fr);
       return NULL;
    }
    if (new_fr != fr) {
       ast_frfree(fr);
       fr = new_fr;
    }
    return fr;
 }
rewrite_wrapper()
static int rewrite_wrapper (struct ast_filestream * s, const char * comment) static
Definition at line 485 of file file.c.
References fn_wrapper().
Referenced by ast_writefile().
 {
    return fn_wrapper(s, comment, WRAP_REWRITE);
 }
sanitize_waitstream_return()
static int sanitize_waitstream_return (int return_value) static
Definition at line 1759 of file file.c.
References AST_CONTROL_STREAM_RESTART, AST_CONTROL_STREAM_STOP, and AST_CONTROL_STREAM_SUSPEND.
Referenced by ast_waitstream(), ast_waitstream_exten(), and ast_waitstream_full().
 {
    switch (return_value) {
    case AST_CONTROL_STREAM_STOP:
    case AST_CONTROL_STREAM_SUSPEND:
    case AST_CONTROL_STREAM_RESTART:
       /* Fall through and set return_value to 0 */
       return_value = 0;
       break;
    default:
       /* Do nothing */
       break;
    }
    return return_value;
 }
STASIS_MESSAGE_TYPE_DEFN() [1/2]
STASIS_MESSAGE_TYPE_DEFN (ast_format_register_type)
STASIS_MESSAGE_TYPE_DEFN() [2/2]
STASIS_MESSAGE_TYPE_DEFN (ast_format_unregister_type)
type_in_list()
static int type_in_list (const char * list, const char * type, int(*)(const char *s1, const char *s2) cmp) static
Definition at line 338 of file file.c.
References ast_strdupa, item, and strsep().
Referenced by ast_get_extension_for_mime_type().
 {
    char *stringp = ast_strdupa(list), *item;
    while ((item = strsep(&stringp, "|"))) {
       if (!cmp(item, type)) {
          return 1;
       }
    }
    return 0;
 }
waitstream_control()
static void waitstream_control (struct ast_channel * c, enum ast_waitstream_fr_cb_values type, ast_waitstream_fr_cb cb, int skip_ms) static
Definition at line 1509 of file file.c.
References ast_channel_name(), ast_channel_stream(), ast_format_get_sample_rate(), ast_stream_fastforward(), ast_stream_rewind(), ast_tellstream(), ast_test_suite_event_notify, AST_WAITSTREAM_CB_FASTFORWARD, AST_WAITSTREAM_CB_REWIND, ast_filestream::f, ast_filestream::fmt, and ast_format_def::format.
Referenced by waitstream_core().
 {
    switch (type)
    {
    case AST_WAITSTREAM_CB_FASTFORWARD:
       {
          int eoftest;
          ast_stream_fastforward(ast_channel_stream(c), skip_ms);
          eoftest = fgetc(ast_channel_stream(c)->f);
          if (feof(ast_channel_stream(c)->f)) {
             ast_stream_rewind(ast_channel_stream(c), skip_ms);
          } else {
             ungetc(eoftest, ast_channel_stream(c)->f);
          }
       }
       break;
    case AST_WAITSTREAM_CB_REWIND:
       ast_stream_rewind(ast_channel_stream(c), skip_ms);
       break;
    default:
       break;
    }
    if (cb) {
       long ms_len = ast_tellstream(ast_channel_stream(c)) / (ast_format_get_sample_rate(ast_channel_stream(c)->fmt->format) / 1000);
       cb(c, ms_len, type);
    }
    ast_test_suite_event_notify("PLAYBACK","Channel: %s\r\n"
       "Control: %s\r\n"
       "SkipMs: %d\r\n",
       ast_channel_name(c),
       (type == AST_WAITSTREAM_CB_FASTFORWARD) ? "FastForward" : "Rewind",
       skip_ms);
 }
waitstream_core()
static int waitstream_core (struct ast_channel * c, const char * breakon, const char * forward, const char * reverse, int skip_ms, int audiofd, int cmdfd, const char * context, ast_waitstream_fr_cb cb) static
the core of all waitstream() functions
Definition at line 1551 of file file.c.
References ast_channel_caller(), ast_channel_clear_flag(), ast_channel_flags(), ast_channel_name(), ast_channel_sched(), ast_channel_set_flag(), ast_channel_softhangup_internal_flag(), ast_channel_stream(), ast_channel_timingfunc(), AST_CONTROL_ANSWER, AST_CONTROL_AOC, AST_CONTROL_BUSY, AST_CONTROL_CONGESTION, AST_CONTROL_CONNECTED_LINE, AST_CONTROL_FLASH, AST_CONTROL_HANGUP, AST_CONTROL_HOLD, AST_CONTROL_PVT_CAUSE_CODE, AST_CONTROL_REDIRECTING, AST_CONTROL_RINGING, AST_CONTROL_SRCCHANGE, AST_CONTROL_SRCUPDATE, AST_CONTROL_STREAM_FORWARD, AST_CONTROL_STREAM_RESTART, AST_CONTROL_STREAM_REVERSE, AST_CONTROL_STREAM_STOP, AST_CONTROL_STREAM_SUSPEND, AST_CONTROL_UNHOLD, AST_CONTROL_UPDATE_RTP_PEER, AST_CONTROL_VIDUPDATE, ast_exists_extension(), AST_FLAG_END_DTMF_ONLY, AST_FLAG_MASQ_NOSTREAM, ast_format_get_sample_rate(), AST_FRAME_CONTROL, AST_FRAME_DTMF_END, AST_FRAME_VOICE, ast_frfree, ast_log, ast_read(), ast_sched_runq(), ast_sched_wait(), ast_stopstream(), ast_strdupa, ast_tellstream(), ast_test_flag, ast_test_suite_event_notify, ast_waitfor(), ast_waitfor_nandfds(), AST_WAITSTREAM_CB_FASTFORWARD, AST_WAITSTREAM_CB_REWIND, AST_WAITSTREAM_CB_START, ast_frame::data, ast_frame::datalen, errno, exten, ast_filestream::fmt, ast_format_def::format, ast_frame::frametype, ast_frame_subclass::integer, LOG_WARNING, NULL, ast_filestream::orig_chan_name, ast_frame::ptr, S_COR, ast_frame::subclass, and waitstream_control().
Referenced by ast_waitstream(), ast_waitstream_exten(), ast_waitstream_fr(), ast_waitstream_fr_w_cb(), and ast_waitstream_full().
 {
    const char *orig_chan_name = NULL;
    int err = 0;
    if (!breakon)
       breakon = "";
    if (!forward)
       forward = "";
    if (!reverse)
       reverse = "";
    /* Switch the channel to end DTMF frame only. waitstream_core doesn't care about the start of DTMF. */
    ast_channel_set_flag(c, AST_FLAG_END_DTMF_ONLY);
    if (ast_test_flag(ast_channel_flags(c), AST_FLAG_MASQ_NOSTREAM))
       orig_chan_name = ast_strdupa(ast_channel_name(c));
    if (ast_channel_stream(c) && cb) {
       long ms_len = ast_tellstream(ast_channel_stream(c)) / (ast_format_get_sample_rate(ast_channel_stream(c)->fmt->format) / 1000);
       cb(c, ms_len, AST_WAITSTREAM_CB_START);
    }
    while (ast_channel_stream(c)) {
       int res;
       int ms;
       if (orig_chan_name && strcasecmp(orig_chan_name, ast_channel_name(c))) {
          ast_stopstream(c);
          err = 1;
          break;
       }
       ms = ast_sched_wait(ast_channel_sched(c));
       if (ms < 0 && !ast_channel_timingfunc(c)) {
          ast_stopstream(c);
          break;
       }
       if (ms < 0)
          ms = 1000;
       if (cmdfd < 0) {
          res = ast_waitfor(c, ms);
          if (res < 0) {
             ast_log(LOG_WARNING, "Select failed (%s)\n", strerror(errno));
             ast_channel_clear_flag(c, AST_FLAG_END_DTMF_ONLY);
             return res;
          }
       } else {
          int outfd;
          struct ast_channel *rchan = ast_waitfor_nandfds(&c, 1, &cmdfd, (cmdfd > -1) ? 1 : 0, NULL, &outfd, &ms);
          if (!rchan && (outfd < 0) && (ms)) {
             /* Continue */
             if (errno == EINTR)
                continue;
             ast_log(LOG_WARNING, "Wait failed (%s)\n", strerror(errno));
             ast_channel_clear_flag(c, AST_FLAG_END_DTMF_ONLY);
             return -1;
          } else if (outfd > -1) { /* this requires cmdfd set */
             /* The FD we were watching has something waiting */
             ast_channel_clear_flag(c, AST_FLAG_END_DTMF_ONLY);
             return 1;
          }
          /* if rchan is set, it is 'c' */
          res = rchan ? 1 : 0; /* map into 'res' values */
       }
       if (res > 0) {
          struct ast_frame *fr = ast_read(c);
          if (!fr) {
             ast_channel_clear_flag(c, AST_FLAG_END_DTMF_ONLY);
             return -1;
          }
          switch (fr->frametype) {
          case AST_FRAME_DTMF_END:
             if (context) {
                const char exten[2] = { fr->subclass.integer, '\0' };
                if (ast_exists_extension(c, context, exten, 1,
                   S_COR(ast_channel_caller(c)->id.number.valid, ast_channel_caller(c)->id.number.str, NULL))) {
                   res = fr->subclass.integer;
                   ast_frfree(fr);
                   ast_channel_clear_flag(c, AST_FLAG_END_DTMF_ONLY);
                   return res;
                }
             } else {
                res = fr->subclass.integer;
                if (strchr(forward, res)) {
                   waitstream_control(c, AST_WAITSTREAM_CB_FASTFORWARD, cb, skip_ms);
                } else if (strchr(reverse, res)) {
                   waitstream_control(c, AST_WAITSTREAM_CB_REWIND, cb, skip_ms);
                } else if (strchr(breakon, res)) {
                   ast_test_suite_event_notify("PLAYBACK","Channel: %s\r\n"
                      "Control: %s\r\n",
                      ast_channel_name(c),
                      "Break");
                   ast_frfree(fr);
                   ast_channel_clear_flag(c, AST_FLAG_END_DTMF_ONLY);
                   return res;
                }
             }
             break;
          case AST_FRAME_CONTROL:
             switch (fr->subclass.integer) {
             case AST_CONTROL_STREAM_STOP:
             case AST_CONTROL_STREAM_SUSPEND:
             case AST_CONTROL_STREAM_RESTART:
                /* Fall-through and break out */
                ast_test_suite_event_notify("PLAYBACK","Channel: %s\r\n"
                   "Control: %s\r\n",
                   ast_channel_name(c),
                   "Break");
                res = fr->subclass.integer;
                ast_frfree(fr);
                ast_channel_clear_flag(c, AST_FLAG_END_DTMF_ONLY);
                return res;
             case AST_CONTROL_STREAM_REVERSE:
                if (!skip_ms) {
                   skip_ms = 3000;
                }
                waitstream_control(c, AST_WAITSTREAM_CB_REWIND, cb, skip_ms);
                break;
             case AST_CONTROL_STREAM_FORWARD:
                if (!skip_ms) {
                   skip_ms = 3000;
                }
                waitstream_control(c, AST_WAITSTREAM_CB_FASTFORWARD, cb, skip_ms);
                break;
             case AST_CONTROL_HANGUP:
             case AST_CONTROL_BUSY:
             case AST_CONTROL_CONGESTION:
                ast_frfree(fr);
                ast_channel_clear_flag(c, AST_FLAG_END_DTMF_ONLY);
                return -1;
             case AST_CONTROL_RINGING:
             case AST_CONTROL_ANSWER:
             case AST_CONTROL_VIDUPDATE:
             case AST_CONTROL_SRCUPDATE:
             case AST_CONTROL_SRCCHANGE:
             case AST_CONTROL_HOLD:
             case AST_CONTROL_UNHOLD:
             case AST_CONTROL_CONNECTED_LINE:
             case AST_CONTROL_REDIRECTING:
             case AST_CONTROL_AOC:
             case AST_CONTROL_UPDATE_RTP_PEER:
             case AST_CONTROL_PVT_CAUSE_CODE:
             case AST_CONTROL_FLASH:
             case -1:
                /* Unimportant */
                break;
             default:
                ast_log(LOG_WARNING, "Unexpected control subclass '%d'\n", fr->subclass.integer);
             }
             break;
          case AST_FRAME_VOICE:
             /* Write audio if appropriate */
             if (audiofd > -1) {
                if (write(audiofd, fr->data.ptr, fr->datalen) < 0) {
                   ast_log(LOG_WARNING, "write() failed: %s\n", strerror(errno));
                }
             }
          default:
             /* Ignore all others */
             break;
          }
          ast_frfree(fr);
       }
       ast_sched_runq(ast_channel_sched(c));
    }
    ast_channel_clear_flag(c, AST_FLAG_END_DTMF_ONLY);
    return (err || ast_channel_softhangup_internal_flag(c)) ? -1 : 0;
 }
Variable Documentation
ast_language_is_prefix
int ast_language_is_prefix = 1
The following variable controls the layout of localized sound files. If 0, use the historical layout with prefix just before the filename (i.e. digits/en/1.gsm , digits/it/1.gsm or default to digits/1.gsm), if 1 put the prefix at the beginning of the filename (i.e. en/digits/1.gsm, it/digits/1.gsm or default to digits/1.gsm). The latter permits a language to be entirely in one directory.
This is settable in asterisk.conf.
Definition at line 67 of file file.c.
Referenced by fileexists_test(), handle_show_settings(), load_asterisk_conf(), and main().
cli_file
struct ast_cli_entry cli_file[] static
Initial value:
= {
   { .handler =  handle_cli_core_show_file_formats , .summary =  "Displays file formats" ,}
}
Definition at line 1972 of file file.c.
formats
struct formats formats = { .first = NULL, .last = NULL, .lock = { PTHREAD_RWLOCK_INITIALIZER , NULL, {1, 0} } , } static
read_dirs_lock
ast_mutex_t read_dirs_lock = { PTHREAD_RECURSIVE_MUTEX_INITIALIZER_NP , NULL, {1, 0} } static
Lock to hold when iterating over directories.
Currently, 'readdir' is not required to be thread-safe. In most modern implementations it should be safe to make concurrent calls into 'readdir' that specify different directory streams (glibc would be one of these). However, since it is potentially unsafe for some implementations we'll use our own locking in order to achieve synchronization for those.
Definition at line 1228 of file file.c.
Referenced by ast_file_read_dirs().