Asterisk - The Open Source Telephony Project: ast_srtp_policy_res Struct Reference
ast_srtp_policy_res Struct Reference
#include <res_srtp.h>
Data Fields
struct ast_srtp_policy *(* alloc)(void)
void(* destroy)(struct ast_srtp_policy *policy)
int(* set_master_key)(struct ast_srtp_policy *policy, const unsigned char *key, size_t key_len, const unsigned char *salt, size_t salt_len)
void(* set_ssrc)(struct ast_srtp_policy *policy, unsigned long ssrc, int inbound)
int(* set_suite)(struct ast_srtp_policy *policy, enum ast_srtp_suite suite)
Detailed Description
Definition at line 70 of file res_srtp.h.
Field Documentation
alloc
struct ast_srtp_policy*(* alloc) (void)
Definition at line 71 of file res_srtp.h.
Referenced by crypto_activate(), and rtcp_debug_test_addr().
destroy
void(* destroy) (struct ast_srtp_policy *policy)
Definition at line 72 of file res_srtp.h.
Referenced by crypto_activate(), and rtcp_debug_test_addr().
set_master_key
int(* set_master_key) (struct ast_srtp_policy *policy, const unsigned char *key, size_t key_len, const unsigned char *salt, size_t salt_len)
Definition at line 74 of file res_srtp.h.
Referenced by rtcp_debug_test_addr(), and set_crypto_policy().
set_ssrc
void(* set_ssrc) (struct ast_srtp_policy *policy, unsigned long ssrc, int inbound)
Definition at line 75 of file res_srtp.h.
Referenced by rtcp_debug_test_addr(), and set_crypto_policy().
set_suite
int(* set_suite) (struct ast_srtp_policy *policy, enum ast_srtp_suite suite)
Definition at line 73 of file res_srtp.h.
Referenced by rtcp_debug_test_addr(), and set_crypto_policy().
The documentation for this struct was generated from the following file:
res_srtp.h