Asterisk - The Open Source Telephony Project: parking_ui.c File Reference
parking_ui.c File Reference
Call Parking CLI commands.
#include "asterisk.h"
#include "res_parking.h"
#include "asterisk/config.h"
#include "asterisk/config_options.h"
#include "asterisk/utils.h"
#include "asterisk/module.h"
#include "asterisk/cli.h"
#include "asterisk/astobj2.h"
#include "asterisk/features.h"
#include "asterisk/manager.h"
Data Structures
struct parking_lot_complete
Functions
static void cli_display_parking_global (int fd)
static void cli_display_parking_lot (int fd, const char *name)
static void cli_display_parking_lot_list (int fd)
static char * complete_parking_lot (const char *word, int seeking)
static int complete_parking_lot_search (void *obj, void *arg, void *data, int flags)
static void display_parked_call (struct parked_user *user, int fd)
static int display_parked_users_cb (void *obj, void *arg, int flags)
static void display_parking_lot (struct parking_lot *lot, int fd)
static int display_parking_lot_cb (void *obj, void *arg, int flags)
static char * handle_show_parking_lot_cmd (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
int load_parking_ui (void)
Register CLI commands.
void unload_parking_ui (void)
Unregister CLI commands.
Variables
static struct ast_cli_entry cli_parking_lot []
Detailed Description
Call Parking CLI commands.
Author
Jonathan Rose jrose.nosp@m.@dig.nosp@m.ium.c.nosp@m.om
Definition in file parking_ui.c.
Function Documentation
cli_display_parking_global()
static void cli_display_parking_global (int fd) static
Definition at line 103 of file parking_ui.c.
References ast_cli(), and parking_dynamic_lots_enabled().
Referenced by handle_show_parking_lot_cmd().
 {
    ast_cli(fd, "Parking General Options\n"
                "-----------------------\n");
    ast_cli(fd, "Dynamic Parking     :  %s\n", parking_dynamic_lots_enabled() ? "yes" : "no");
    ast_cli(fd, "\n");
 }
cli_display_parking_lot()
static void cli_display_parking_lot (int fd, const char * name) static
Definition at line 78 of file parking_ui.c.
References ao2_callback, ao2_cleanup, ao2_container_count(), ast_cli(), display_parked_users_cb(), display_parking_lot(), NULL, OBJ_MULTIPLE, OBJ_NODATA, parking_lot_find_by_name(), and RAII_VAR.
Referenced by handle_show_parking_lot_cmd().
 {
    RAII_VAR(struct parking_lot *, lot, NULL, ao2_cleanup);
    lot = parking_lot_find_by_name(name);
    /* If the parking lot couldn't be found with the search, also abort. */
    if (!lot) {
       ast_cli(fd, "Could not find parking lot '%s'\n\n", name);
       return;
    }
    display_parking_lot(lot, fd);
    ast_cli(fd, "Parked Calls\n------------\n");
    if (!ao2_container_count(lot->parked_users)) {
       ast_cli(fd, "  (none)\n");
       ast_cli(fd, "\n\n");
       return;
    }
    ao2_callback(lot->parked_users, OBJ_MULTIPLE | OBJ_NODATA, display_parked_users_cb, &fd);
    ast_cli(fd, "\n");
 }
cli_display_parking_lot_list()
static void cli_display_parking_lot_list (int fd) static
Definition at line 111 of file parking_ui.c.
References ao2_callback, ast_cli(), display_parking_lot_cb(), get_parking_lot_container(), OBJ_MULTIPLE, and OBJ_NODATA.
Referenced by handle_show_parking_lot_cmd().
 {
    struct ao2_container *lot_container;
    lot_container = get_parking_lot_container();
    if (!lot_container) {
       ast_cli(fd, "Failed to obtain parking lot list.\n\n");
       return;
    }
    ao2_callback(lot_container, OBJ_MULTIPLE | OBJ_NODATA, display_parking_lot_cb, &fd);
    ast_cli(fd, "\n");
 }
complete_parking_lot()
static char* complete_parking_lot (const char * word, int seeking) static
Definition at line 140 of file parking_ui.c.
References ao2_callback_data, ao2_ref, ast_strdup, ast_strlen_zero, complete_parking_lot_search(), get_parking_lot_container(), parking_lot::name, NULL, OBJ_PARTIAL_KEY, and parking_lot_complete::seeking.
Referenced by handle_show_parking_lot_cmd().
 {
    char *ret = NULL;
    struct parking_lot *lot;
    struct ao2_container *global_lots = get_parking_lot_container();
    struct parking_lot_complete search = {
       .seeking = seeking,
       };
    lot = ao2_callback_data(global_lots, ast_strlen_zero(word) ? 0 : OBJ_PARTIAL_KEY,
       complete_parking_lot_search, (char *) word, &search);
    if (!lot) {
       return NULL;
    }
    ret = ast_strdup(lot->name);
    ao2_ref(lot, -1);
    return ret;
 }
complete_parking_lot_search()
static int complete_parking_lot_search (void * obj, void * arg, void * data, int flags) static
Definition at line 131 of file parking_ui.c.
References CMP_MATCH, parking_lot_complete::seeking, and parking_lot_complete::which.
Referenced by complete_parking_lot().
 {
    struct parking_lot_complete *search = data;
    if (++search->which > search->seeking) {
       return CMP_MATCH;
    }
    return 0;
 }
display_parked_call()
static void display_parked_call (struct parked_user * user, int fd) static
Definition at line 38 of file parking_ui.c.
References ast_channel_name(), ast_cli(), parked_user::chan, parked_user::parker_dial_string, and parked_user::parking_space.
Referenced by display_parked_users_cb().
 {
    ast_cli(fd, "  Space               :  %d\n", user->parking_space);
    ast_cli(fd, "  Channel             :  %s\n", ast_channel_name(user->chan));
    ast_cli(fd, "  Parker Dial String  :  %s\n", user->parker_dial_string);
    ast_cli(fd, "\n");
 }
display_parked_users_cb()
static int display_parked_users_cb (void * obj, void * arg, int flags) static
Definition at line 46 of file parking_ui.c.
References display_parked_call().
Referenced by cli_display_parking_lot().
 {
    int *fd = arg;
    struct parked_user *user = obj;
    display_parked_call(user, *fd);
    return 0;
 }
display_parking_lot()
static void display_parking_lot (struct parking_lot * lot, int fd) static
Definition at line 54 of file parking_ui.c.
References ast_cli(), parking_lot::cfg, parking_lot_cfg::comebackcontext, parking_lot_cfg::comebackdialtime, parking_lot_cfg::comebacktoorigin, parking_lot::mode, parking_lot_cfg::mohclass, parking_lot::name, parking_lot_cfg::parkext, parking_lot_cfg::parking_con, parking_lot_cfg::parking_start, parking_lot_cfg::parking_stop, PARKINGLOT_DISABLED, PARKINGLOT_DYNAMIC, and parking_lot_cfg::parkingtime.
Referenced by cli_display_parking_lot(), and display_parking_lot_cb().
 {
    ast_cli(fd, "Parking Lot: %s\n--------------------------------------------------------------------------\n", lot->name);
    ast_cli(fd, "Parking Extension   :  %s\n", lot->cfg->parkext);
    ast_cli(fd, "Parking Context     :  %s\n", lot->cfg->parking_con);
    ast_cli(fd, "Parking Spaces      :  %d-%d\n", lot->cfg->parking_start, lot->cfg->parking_stop);
    ast_cli(fd, "Parking Time        :  %u sec\n", lot->cfg->parkingtime);
    ast_cli(fd, "Comeback to Origin  :  %s\n", lot->cfg->comebacktoorigin ? "yes" : "no");
    ast_cli(fd, "Comeback Context    :  %s%s\n", lot->cfg->comebackcontext, lot->cfg->comebacktoorigin ? " (comebacktoorigin=yes, not used)" : "");
    ast_cli(fd, "Comeback Dial Time  :  %u sec\n", lot->cfg->comebackdialtime);
    ast_cli(fd, "MusicOnHold Class   :  %s\n", lot->cfg->mohclass);
    ast_cli(fd, "Enabled             :  %s\n", (lot->mode == PARKINGLOT_DISABLED) ? "no" : "yes");
    ast_cli(fd, "Dynamic             :  %s\n", (lot->mode == PARKINGLOT_DYNAMIC) ? "yes" : "no");
    ast_cli(fd, "\n");
 }
display_parking_lot_cb()
static int display_parking_lot_cb (void * obj, void * arg, int flags) static
Definition at line 70 of file parking_ui.c.
References display_parking_lot().
Referenced by cli_display_parking_lot_list().
 {
    int *fd = arg;
    struct parking_lot *lot = obj;
    display_parking_lot(lot, *fd);
    return 0;
 }
handle_show_parking_lot_cmd()
static char* handle_show_parking_lot_cmd (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) static
Definition at line 162 of file parking_ui.c.
References ast_cli_args::argc, ast_cli_args::argv, ast_cli(), cli_display_parking_global(), cli_display_parking_lot(), cli_display_parking_lot_list(), CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::command, complete_parking_lot(), ast_cli_args::fd, ast_cli_args::n, NULL, ast_cli_args::pos, ast_cli_entry::usage, and ast_cli_args::word.
 {
    switch (cmd) {
    case CLI_INIT:
       e->command = "parking show";
       e->usage =
          "Usage: parking show [name]\n"
          "  Shows a list of parking lots or details of a specific parking lot.";
       return NULL;
    case CLI_GENERATE:
       if (a->pos == 2) {
          return complete_parking_lot(a->word, a->n);
       }
       return NULL;
    }
    ast_cli(a->fd, "\n");
    if (a->argc == 2) {
       cli_display_parking_global(a->fd);
       cli_display_parking_lot_list(a->fd);
       return CLI_SUCCESS;
    }
    if (a->argc == 3) {
       cli_display_parking_lot(a->fd, a->argv[2]);
       return CLI_SUCCESS;
    }
    return CLI_SHOWUSAGE;
 }
load_parking_ui()
int load_parking_ui (void)
Register CLI commands.
Since
12.0.0
Return values
0 if successful
-1 on failure
Definition at line 198 of file parking_ui.c.
References ARRAY_LEN, and ast_cli_register_multiple.
Referenced by load_module().
 {
    return ast_cli_register_multiple(cli_parking_lot, ARRAY_LEN(cli_parking_lot));
 }
unload_parking_ui()
void unload_parking_ui (void)
Unregister CLI commands.
Since
12.0.0
Definition at line 203 of file parking_ui.c.
References ARRAY_LEN, and ast_cli_unregister_multiple().
Referenced by unload_module().
 {
    ast_cli_unregister_multiple(cli_parking_lot, ARRAY_LEN(cli_parking_lot));
 }
Variable Documentation
cli_parking_lot
struct ast_cli_entry cli_parking_lot[] static
Initial value:
= {
   { .handler =  handle_show_parking_lot_cmd , .summary =  "Show a parking lot or a list of all parking lots." ,},
}
Definition at line 194 of file parking_ui.c.