Asterisk - The Open Source Telephony Project: codec_ilbc.c File Reference
codec_ilbc.c File Reference
Module: Codecs
Translate between signed linear and Internet Low Bitrate Codec.
#include "asterisk.h"
#include "asterisk/codec.h"
#include "asterisk/format.h"
#include "asterisk/frame.h"
#include "asterisk/linkedlists.h"
#include "asterisk/logger.h"
#include "asterisk/module.h"
#include "asterisk/translate.h"
#include "ilbc/iLBC_encode.h"
#include "ilbc/iLBC_decode.h"
#include "asterisk/ilbc.h"
#include "asterisk/slin.h"
#include "ex_ilbc.h"
Data Structures
struct ilbc_coder_pvt
Macros
#define BUF_TYPE uc
#define BUFFER_SAMPLES 8000
#define USE_ILBC_ENHANCER 0
Typedefs
typedef float ilbc_block
typedef unsigned char ilbc_bytes
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int ilbctolin_framein (struct ast_trans_pvt *pvt, struct ast_frame *f)
decode a frame and store in outbuf
static int ilbctolin_new (struct ast_trans_pvt *pvt)
static int lintoilbc_framein (struct ast_trans_pvt *pvt, struct ast_frame *f)
store a frame into a temporary buffer, for later decoding
static struct ast_frame * lintoilbc_frameout (struct ast_trans_pvt *pvt)
encode the temporary buffer and generate a frame
static int lintoilbc_new (struct ast_trans_pvt *pvt)
static int load_module (void)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "iLBC Coder/Decoder" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, }
static const struct ast_module_info * ast_module_info = &__mod_info
static struct ast_translator ilbctolin
static struct ast_translator lintoilbc
Detailed Description
Translate between signed linear and Internet Low Bitrate Codec.
Definition in file codec_ilbc.c.
Macro Definition Documentation
BUF_TYPE
#define BUF_TYPE uc
Definition at line 53 of file codec_ilbc.c.
BUFFER_SAMPLES
#define BUFFER_SAMPLES 8000
Definition at line 59 of file codec_ilbc.c.
Referenced by ilbctolin_framein().
USE_ILBC_ENHANCER
#define USE_ILBC_ENHANCER 0
Definition at line 58 of file codec_ilbc.c.
Referenced by ilbctolin_framein().
Typedef Documentation
ilbc_block
typedef float ilbc_block
Definition at line 52 of file codec_ilbc.c.
ilbc_bytes
typedef unsigned char ilbc_bytes
Definition at line 51 of file codec_ilbc.c.
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 276 of file codec_ilbc.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 276 of file codec_ilbc.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 276 of file codec_ilbc.c.
ilbctolin_framein()
static int ilbctolin_framein (struct ast_trans_pvt * pvt, struct ast_frame * f) static
decode a frame and store in outbuf
Definition at line 94 of file codec_ilbc.c.
References ast_debug, ast_format_get_attribute_data(), ast_log, BUFFER_SAMPLES, ast_frame::data, ast_frame::datalen, ast_trans_pvt::datalen, ilbc_coder_pvt::dec, ast_translator::dst_codec, ast_frame_subclass::format, ast_trans_pvt::i16, iLBC_decode(), initDecode(), ilbc_coder_pvt::inited, LOG_WARNING, ilbc_attr::mode, NULL, ast_trans_pvt::outbuf, ast_frame::ptr, ast_trans_pvt::pvt, ast_codec::sample_rate, ast_frame::samples, ast_trans_pvt::samples, ast_frame::src, ast_frame::subclass, ast_trans_pvt::t, tmp(), and USE_ILBC_ENHANCER.
 {
    struct ilbc_coder_pvt *tmp = pvt->pvt;
    struct ilbc_attr *attr = ast_format_get_attribute_data(f->subclass.format);
    const unsigned int mode = attr ? attr->mode : 30;
    const unsigned int sample_rate = pvt->t->dst_codec.sample_rate;
    const unsigned int samples_per_frame = mode * sample_rate / 1000;
    const unsigned int octets_per_frame = (mode == 20) ? 38 : 50;
    int plc_mode = 1; /* 1 = normal data, 0 = plc */
    /* Assuming there's space left, decode into the current buffer at
       the tail location.  Read in as many frames as there are */
    int x,i;
    int datalen = f->datalen;
    int16_t *dst = pvt->outbuf.i16;
    ilbc_block tmpf[samples_per_frame];
    if (!f->data.ptr && datalen) {
       ast_debug(1, "issue 16070, ILIB ERROR. data = NULL datalen = %d src = %s\n", datalen, f->src ? f->src : "no src set");
       f->datalen = 0;
       datalen = 0;
    }
    if (datalen == 0) { /* native PLC, set fake datalen and clear plc_mode */
       datalen = octets_per_frame;
       f->samples = samples_per_frame;
       plc_mode = 0;  /* do native plc */
       pvt->samples += samples_per_frame;
    }
    if (datalen % octets_per_frame) {
       ast_log(LOG_WARNING, "Huh?  An ilbc frame that isn't a multiple of %u bytes long from %s (%d)?\n", octets_per_frame, f->src, datalen);
       return -1;
    }
    if (!tmp->inited) {
       initDecode(&tmp->dec, mode, USE_ILBC_ENHANCER);
       tmp->inited = 1;
    }
    for (x = 0; x < datalen; x += octets_per_frame) {
       if (pvt->samples + samples_per_frame > BUFFER_SAMPLES) {
          ast_log(LOG_WARNING, "Out of buffer space\n");
          return -1;
       }
       iLBC_decode(tmpf, plc_mode ? f->data.ptr + x : NULL, &tmp->dec, plc_mode);
       for (i = 0; i < samples_per_frame; i++)
          dst[pvt->samples + i] = tmpf[i];
       pvt->samples += samples_per_frame;
       pvt->datalen += samples_per_frame * 2;
    }
    return 0;
 }
ilbctolin_new()
static int ilbctolin_new (struct ast_trans_pvt * pvt) static
Definition at line 84 of file codec_ilbc.c.
References ilbc_coder_pvt::inited, ast_trans_pvt::pvt, and tmp().
 {
    struct ilbc_coder_pvt *tmp = pvt->pvt;
    tmp->inited = 0; /* we do not know the iLBC mode, yet */
    return 0;
 }
lintoilbc_framein()
static int lintoilbc_framein (struct ast_trans_pvt * pvt, struct ast_frame * f) static
store a frame into a temporary buffer, for later decoding
Definition at line 149 of file codec_ilbc.c.
References ilbc_coder_pvt::buf, ast_frame::data, ast_frame::datalen, ast_frame::ptr, ast_trans_pvt::pvt, ast_frame::samples, ast_trans_pvt::samples, and tmp().
 {
    struct ilbc_coder_pvt *tmp = pvt->pvt;
    /* Just add the frames to our stream */
    /* XXX We should look at how old the rest of our stream is, and if it
       is too old, then we should overwrite it entirely, otherwise we can
       get artifacts of earlier talk that do not belong */
    memcpy(tmp->buf + pvt->samples, f->data.ptr, f->datalen);
    pvt->samples += f->samples;
    return 0;
 }
lintoilbc_frameout()
static struct ast_frame* lintoilbc_frameout (struct ast_trans_pvt * pvt) static
encode the temporary buffer and generate a frame
Definition at line 163 of file codec_ilbc.c.
References ast_format_get_attribute_data(), AST_LIST_NEXT, ast_trans_frameout(), ilbc_coder_pvt::buf, ast_translator::dst_codec, ilbc_coder_pvt::enc, ast_trans_pvt::f, ast_frame_subclass::format, iLBC_encode(), last, ilbc_attr::mode, NULL, ast_trans_pvt::outbuf, ast_trans_pvt::pvt, result, ast_codec::sample_rate, ast_frame::samples, ast_trans_pvt::samples, ast_frame::subclass, ast_trans_pvt::t, and tmp().
 {
    struct ilbc_coder_pvt *tmp = pvt->pvt;
    struct ast_frame *result = NULL;
    struct ast_frame *last = NULL;
    int samples = 0; /* output samples */
    struct ilbc_attr *attr = ast_format_get_attribute_data(pvt->f.subclass.format);
    const unsigned int mode = attr ? attr->mode : 30;
    const unsigned int sample_rate = pvt->t->dst_codec.sample_rate;
    const unsigned int samples_per_frame = mode * sample_rate / 1000;
    const unsigned int octets_per_frame = (mode == 20) ? 38 : 50;
    while (pvt->samples >= samples_per_frame) {
       struct ast_frame *current;
       ilbc_block tmpf[samples_per_frame];
       int i;
       /* Encode a frame of data */
       for (i = 0; i < samples_per_frame; i++)
          tmpf[i] = tmp->buf[samples + i];
       iLBC_encode((ilbc_bytes *) pvt->outbuf.BUF_TYPE, tmpf, &tmp->enc);
       samples += samples_per_frame;
       pvt->samples -= samples_per_frame;
       current = ast_trans_frameout(pvt, octets_per_frame, samples_per_frame);
       if (!current) {
          continue;
       } else if (last) {
          AST_LIST_NEXT(last, frame_list) = current;
       } else {
          result = current;
       }
       last = current;
    }
    /* Move the data at the end of the buffer to the front */
    if (samples) {
       memmove(tmp->buf, tmp->buf + samples, pvt->samples * 2);
    }
    return result;
 }
lintoilbc_new()
static int lintoilbc_new (struct ast_trans_pvt * pvt) static
Definition at line 73 of file codec_ilbc.c.
References ast_format_get_attribute_data(), ilbc_coder_pvt::enc, ast_trans_pvt::explicit_dst, initEncode(), ilbc_attr::mode, NULL, ast_trans_pvt::pvt, and tmp().
 {
    struct ilbc_coder_pvt *tmp = pvt->pvt;
    struct ilbc_attr *attr = pvt->explicit_dst ? ast_format_get_attribute_data(pvt->explicit_dst) : NULL;
    const unsigned int mode = attr ? attr->mode : 30;
    initEncode(&tmp->enc, mode);
    return 0;
 }
load_module()
static int load_module (void) static
Definition at line 261 of file codec_ilbc.c.
References AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, ast_register_translator, and unload_module().
 {
    int res;
    res = ast_register_translator(&ilbctolin);
    res |= ast_register_translator(&lintoilbc);
    if (res) {
       unload_module();
       return AST_MODULE_LOAD_DECLINE;
    }
    return AST_MODULE_LOAD_SUCCESS;
 }
unload_module()
static int unload_module (void) static
Definition at line 251 of file codec_ilbc.c.
References ast_unregister_translator().
Referenced by load_module().
 {
    int res;
    res = ast_unregister_translator(&lintoilbc);
    res |= ast_unregister_translator(&ilbctolin);
    return res;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "iLBC Coder/Decoder" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, } static
Definition at line 276 of file codec_ilbc.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 276 of file codec_ilbc.c.
ilbctolin
struct ast_translator ilbctolin static
Definition at line 208 of file codec_ilbc.c.
lintoilbc
struct ast_translator lintoilbc static
Definition at line 229 of file codec_ilbc.c.