Asterisk - The Open Source Telephony Project: res_odbc_transaction.c File Reference
res_odbc_transaction.c File Reference
#include "asterisk.h"
#include "asterisk/res_odbc.h"
#include "asterisk/res_odbc_transaction.h"
#include "asterisk/channel.h"
#include "asterisk/pbx.h"
#include "asterisk/app.h"
#include "asterisk/module.h"
Data Structures
struct odbc_txn_frame
Functions
static void __reg_module (void)
static void __unreg_module (void)
static int acf_transaction_read (struct ast_channel *chan, const char *cmd, char *data, char *buf, size_t len)
static int acf_transaction_write (struct ast_channel *chan, const char *cmd, char *s, const char *value)
struct ast_module * AST_MODULE_SELF_SYM (void)
struct odbc_obj * ast_odbc_retrieve_transaction_obj (struct ast_channel *chan, const char *objname)
Retrieve an ODBC transaction connection with the given ODBC class name.
static int commit_exec (struct ast_channel *chan, const char *data)
static struct odbc_txn_frame * create_transaction (struct ast_channel *chan, const char *name, const char *dsn)
static struct odbc_txn_frame * find_transaction (struct ast_channel *chan, const char *name, int active)
static int load_module (void)
static int mark_transaction_active (struct ast_channel *chan, struct odbc_txn_frame *tx)
static void odbc_txn_free (void *vdata)
static struct odbc_txn_frame * release_transaction (struct odbc_txn_frame *tx)
static int rollback_exec (struct ast_channel *chan, const char *data)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_GLOBAL_SYMBOLS | AST_MODFLAG_LOAD_ORDER , .description = "ODBC transaction resource" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_REALTIME_DEPEND, }
static const char *const app_commit = "ODBC_Commit"
static const char *const app_rollback = "ODBC_Rollback"
static const struct ast_module_info * ast_module_info = &__mod_info
static struct ast_custom_function odbc_function
static const struct ast_datastore_info txn_info
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 530 of file res_odbc_transaction.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 530 of file res_odbc_transaction.c.
acf_transaction_read()
static int acf_transaction_read (struct ast_channel * chan, const char * cmd, char * data, char * buf, size_t len) static
Definition at line 316 of file res_odbc_transaction.c.
References args, AST_APP_ARG, ast_copy_string(), AST_DECLARE_APP_ARGS, ast_odbc_isolation2text(), AST_STANDARD_APP_ARGS, ast_strlen_zero, find_transaction(), odbc_txn_frame::forcecommit, odbc_txn_frame::isolation, odbc_txn_frame::name, and NULL.
 {
    AST_DECLARE_APP_ARGS(args,
       AST_APP_ARG(property);
       AST_APP_ARG(opt);
    );
    struct odbc_txn_frame *tx;
    AST_STANDARD_APP_ARGS(args, data);
    if (strcasecmp(args.property, "transaction") == 0) {
       if ((tx = find_transaction(chan, NULL, 1))) {
          ast_copy_string(buf, tx->name, len);
          return 0;
       }
    } else if (strcasecmp(args.property, "isolation") == 0) {
       if (!ast_strlen_zero(args.opt)) {
          tx = find_transaction(chan, args.opt, 0);
       } else {
          tx = find_transaction(chan, NULL, 1);
       }
       if (tx) {
          ast_copy_string(buf, ast_odbc_isolation2text(tx->isolation), len);
          return 0;
       }
    } else if (strcasecmp(args.property, "forcecommit") == 0) {
       if (!ast_strlen_zero(args.opt)) {
          tx = find_transaction(chan, args.opt, 0);
       } else {
          tx = find_transaction(chan, NULL, 1);
       }
       if (tx) {
          ast_copy_string(buf, tx->forcecommit ? "1" : "0", len);
          return 0;
       }
    }
    return -1;
 }
acf_transaction_write()
static int acf_transaction_write (struct ast_channel * chan, const char * cmd, char * s, const char * value) static
Definition at line 390 of file res_odbc_transaction.c.
References args, AST_APP_ARG, AST_DECLARE_APP_ARGS, ast_false(), ast_log, ast_odbc_print_errors(), ast_odbc_text2isolation(), AST_STANDARD_APP_ARGS, ast_strlen_zero, ast_true(), odbc_obj::con, create_transaction(), find_transaction(), odbc_txn_frame::forcecommit, odbc_txn_frame::isolation, LOG_ERROR, mark_transaction_active(), NULL, odbc_txn_frame::obj, pbx_builtin_setvar_helper(), and S_OR.
 {
    AST_DECLARE_APP_ARGS(args,
       AST_APP_ARG(property);
       AST_APP_ARG(opt);
    );
    struct odbc_txn_frame *tx;
    AST_STANDARD_APP_ARGS(args, s);
    if (strcasecmp(args.property, "transaction") == 0) {
       /* Set active transaction */
       if ((tx = find_transaction(chan, value, 0))) {
          mark_transaction_active(chan, tx);
       } else if (!create_transaction(chan, value, args.opt)) {
          pbx_builtin_setvar_helper(chan, "ODBC_RESULT", "FAILED_TO_CREATE");
          return -1;
       }
       pbx_builtin_setvar_helper(chan, "ODBC_RESULT", "OK");
       return 0;
    } else if (strcasecmp(args.property, "forcecommit") == 0) {
       /* Set what happens when an uncommitted transaction ends without explicit Commit or Rollback */
       if (ast_strlen_zero(args.opt)) {
          tx = find_transaction(chan, NULL, 1);
       } else {
          tx = find_transaction(chan, args.opt, 0);
       }
       if (!tx) {
          pbx_builtin_setvar_helper(chan, "ODBC_RESULT", "FAILED_TO_CREATE");
          return -1;
       }
       if (ast_true(value)) {
          tx->forcecommit = 1;
       } else if (ast_false(value)) {
          tx->forcecommit = 0;
       } else {
          ast_log(LOG_ERROR, "Invalid value for forcecommit: '%s'\n", S_OR(value, ""));
          pbx_builtin_setvar_helper(chan, "ODBC_RESULT", "INVALID_VALUE");
          return -1;
       }
       pbx_builtin_setvar_helper(chan, "ODBC_RESULT", "OK");
       return 0;
    } else if (strcasecmp(args.property, "isolation") == 0) {
       /* How do uncommitted transactions affect reads? */
       /* XXX This is completely useless. The problem is that setting the isolation here
        * does not actually alter the connection. The only time the isolation gets set is
        * when the transaction is created. The only way to set isolation is to set it on
        * the ODBC class's configuration in res_odbc.conf.
        */
       int isolation = ast_odbc_text2isolation(value);
       if (ast_strlen_zero(args.opt)) {
          tx = find_transaction(chan, NULL, 1);
       } else {
          tx = find_transaction(chan, args.opt, 0);
       }
       if (!tx) {
          pbx_builtin_setvar_helper(chan, "ODBC_RESULT", "FAILED_TO_CREATE");
          return -1;
       }
       if (isolation == 0) {
          pbx_builtin_setvar_helper(chan, "ODBC_RESULT", "INVALID_VALUE");
          ast_log(LOG_ERROR, "Invalid isolation specification: '%s'\n", S_OR(value, ""));
       } else if (SQLSetConnectAttr(tx->obj->con, SQL_ATTR_TXN_ISOLATION, (void *)(long)isolation, 0) == SQL_ERROR) {
          pbx_builtin_setvar_helper(chan, "ODBC_RESULT", "SQL_ERROR");
          ast_odbc_print_errors(SQL_HANDLE_DBC, tx->obj->con, "SetConnectAttr (Txn isolation)");
       } else {
          pbx_builtin_setvar_helper(chan, "ODBC_RESULT", "OK");
          tx->isolation = isolation;
       }
       return 0;
    } else {
       ast_log(LOG_ERROR, "Unknown property: '%s'\n", args.property);
       return -1;
    }
 }
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 530 of file res_odbc_transaction.c.
ast_odbc_retrieve_transaction_obj()
struct odbc_obj* ast_odbc_retrieve_transaction_obj (struct ast_channel * chan, const char * objname)
Retrieve an ODBC transaction connection with the given ODBC class name.
Note
The name passed here is not the name of the transaction but the name of the ODBC class defined in res_odbc.conf.
Do not call ast_odbc_release_obj() on the retrieved connection. Calling this function does not make you the owner of the connection.
XXX This function is majorly flawed because it ignores properties of transactions and simply finds one that corresponds to the given DSN. The problem here is that transactions have names and they maintain which transaction is "active" for operations like transaction creation, commit, and rollback. However, when it comes to intermediary operations to be made on the transactions, all that is ignored. It means that if a channel has created multiple transactions for the same DSN, it's a crapshoot which of those transactions the operation will be performed on. This can potentially lead to baffling errors under the right circumstances.
XXX The semantics of this function make for writing some awkward code. If you use func_odbc as an example, it has to first try to retrieve a transactional connection, then failing that, create a non-transactional connection. The result is that it has to remember which type of connection it's using and know whether to release the connection when completed or not. It would be much better if callers did not have to jump through such hoops.
Parameters
chan Channel on which the ODBC transaction was created
objname The name of the ODBC class configured in res_odbc.conf
Return values
NULL Transaction connection could not be found.
non-NULL A transactional connection
Definition at line 466 of file res_odbc_transaction.c.
References ast_channel_datastore_find(), ast_channel_lock, ast_channel_unlock, AST_LIST_HEAD, AST_LIST_LOCK, AST_LIST_TRAVERSE, AST_LIST_UNLOCK, ast_odbc_class_get_name(), ast_datastore::data, odbc_txn_frame::list, NULL, odbc_txn_frame::obj, and odbc_obj::parent.
Referenced by acf_odbc_write().
 {
    struct ast_datastore *txn_store;
    AST_LIST_HEAD(, odbc_txn_frame) *oldlist;
    struct odbc_txn_frame *txn = NULL;
    if (!chan || !objname) {
       /* No channel == no transaction */
       return NULL;
    }
    ast_channel_lock(chan);
    if ((txn_store = ast_channel_datastore_find(chan, &txn_info, NULL))) {
       oldlist = txn_store->data;
    } else {
       ast_channel_unlock(chan);
       return NULL;
    }
    AST_LIST_LOCK(oldlist);
    ast_channel_unlock(chan);
    AST_LIST_TRAVERSE(oldlist, txn, list) {
       if (txn->obj && txn->obj->parent && !strcmp(ast_odbc_class_get_name(txn->obj->parent), objname)) {
          AST_LIST_UNLOCK(oldlist);
          return txn->obj;
       }
    }
    AST_LIST_UNLOCK(oldlist);
    return NULL;
 }
commit_exec()
static int commit_exec (struct ast_channel * chan, const char * data) static
Definition at line 272 of file res_odbc_transaction.c.
References ast_odbc_print_errors(), ast_str_buffer(), ast_strlen_zero, odbc_obj::con, find_transaction(), NULL, odbc_txn_frame::obj, and pbx_builtin_setvar_helper().
Referenced by load_module().
 {
    struct odbc_txn_frame *tx;
    if (ast_strlen_zero(data)) {
       tx = find_transaction(chan, NULL, 1);
    } else {
       tx = find_transaction(chan, data, 0);
    }
    /* XXX COMMIT_RESULT is set to OK even if no transaction was found. Very misleading */
    pbx_builtin_setvar_helper(chan, "COMMIT_RESULT", "OK");
    if (tx) {
       if (SQLEndTran(SQL_HANDLE_DBC, tx->obj->con, SQL_COMMIT) == SQL_ERROR) {
          struct ast_str *errors = ast_odbc_print_errors(SQL_HANDLE_DBC, tx->obj->con, "SQLEndTran");
          pbx_builtin_setvar_helper(chan, "COMMIT_RESULT", ast_str_buffer(errors));
       }
    }
    return 0;
 }
create_transaction()
static struct odbc_txn_frame* create_transaction (struct ast_channel * chan, const char * name, const char * dsn) static
Definition at line 133 of file res_odbc_transaction.c.
References odbc_txn_frame::active, ast_calloc, ast_channel_datastore_add(), ast_channel_datastore_find(), ast_channel_lock, ast_channel_unlock, ast_datastore_alloc, ast_datastore_free(), ast_free, AST_LIST_HEAD, AST_LIST_HEAD_INIT, AST_LIST_INSERT_TAIL, AST_LIST_LOCK, AST_LIST_TRAVERSE, AST_LIST_UNLOCK, ast_log, ast_odbc_class_get_forcecommit(), ast_odbc_class_get_isolation(), ast_odbc_print_errors(), ast_odbc_release_obj(), ast_odbc_request_obj, ast_strlen_zero, odbc_obj::con, ast_datastore::data, odbc_txn_frame::forcecommit, odbc_txn_frame::isolation, odbc_txn_frame::list, LOG_ERROR, odbc_txn_frame::name, NULL, odbc_txn_frame::obj, and odbc_obj::parent.
Referenced by acf_transaction_write().
 {
    struct ast_datastore *txn_store;
    AST_LIST_HEAD(, odbc_txn_frame) *oldlist;
    struct odbc_txn_frame *txn = NULL;
    struct odbc_txn_frame *otxn;
    if (ast_strlen_zero(dsn)) {
       return NULL;
    }
    ast_channel_lock(chan);
    if ((txn_store = ast_channel_datastore_find(chan, &txn_info, NULL))) {
       oldlist = txn_store->data;
    } else {
       if (!(txn_store = ast_datastore_alloc(&txn_info, NULL))) {
          ast_log(LOG_ERROR, "Unable to allocate a new datastore.  Cannot create a new transaction.\n");
          ast_channel_unlock(chan);
          return NULL;
       }
       if (!(oldlist = ast_calloc(1, sizeof(*oldlist)))) {
          ast_log(LOG_ERROR, "Unable to allocate datastore list head.  Cannot create a new transaction.\n");
          ast_datastore_free(txn_store);
          ast_channel_unlock(chan);
          return NULL;
       }
       txn_store->data = oldlist;
       AST_LIST_HEAD_INIT(oldlist);
       ast_channel_datastore_add(chan, txn_store);
    }
    ast_channel_unlock(chan);
    txn = ast_calloc(1, sizeof(*txn) + strlen(name) + 1);
    if (!txn) {
       return NULL;
    }
    strcpy(txn->name, name); /* SAFE */
    txn->obj = ast_odbc_request_obj(dsn, 0);
    if (!txn->obj) {
       ast_free(txn);
       return NULL;
    }
    txn->isolation = ast_odbc_class_get_isolation(txn->obj->parent);
    txn->forcecommit = ast_odbc_class_get_forcecommit(txn->obj->parent);
    txn->active = 1;
    if (SQLSetConnectAttr(txn->obj->con, SQL_ATTR_AUTOCOMMIT, (void *)SQL_AUTOCOMMIT_OFF, 0) == SQL_ERROR) {
       ast_odbc_print_errors(SQL_HANDLE_DBC, txn->obj->con, "SetConnectAttr (Autocommit)");
       ast_odbc_release_obj(txn->obj);
       ast_free(txn);
       return NULL;
    }
    /* Set the isolation property */
    if (SQLSetConnectAttr(txn->obj->con, SQL_ATTR_TXN_ISOLATION, (void *)(long)txn->isolation, 0) == SQL_ERROR) {
       ast_odbc_print_errors(SQL_HANDLE_DBC, txn->obj->con, "SetConnectAttr");
       ast_odbc_release_obj(txn->obj);
       ast_free(txn);
       return NULL;
    }
    /* On creation, the txn becomes active, and all others inactive */
    AST_LIST_LOCK(oldlist);
    AST_LIST_TRAVERSE(oldlist, otxn, list) {
       otxn->active = 0;
    }
    AST_LIST_INSERT_TAIL(oldlist, txn, list);
    AST_LIST_UNLOCK(oldlist);
    return txn;
 }
find_transaction()
static struct odbc_txn_frame* find_transaction (struct ast_channel * chan, const char * name, int active) static
Definition at line 208 of file res_odbc_transaction.c.
References odbc_txn_frame::active, ast_channel_datastore_find(), ast_channel_lock, ast_channel_unlock, AST_LIST_HEAD, AST_LIST_LOCK, AST_LIST_TRAVERSE, AST_LIST_UNLOCK, ast_datastore::data, odbc_txn_frame::list, odbc_txn_frame::name, and NULL.
Referenced by acf_transaction_read(), acf_transaction_write(), commit_exec(), and rollback_exec().
 {
    struct ast_datastore *txn_store;
    AST_LIST_HEAD(, odbc_txn_frame) *oldlist;
    struct odbc_txn_frame *txn = NULL;
    if (!chan || (!active && !name)) {
       return NULL;
    }
    ast_channel_lock(chan);
    txn_store = ast_channel_datastore_find(chan, &txn_info, NULL);
    ast_channel_unlock(chan);
    if (!txn_store) {
       /* No datastore? Definitely no transaction then */
       return NULL;
    }
    oldlist = txn_store->data;
    AST_LIST_LOCK(oldlist);
    AST_LIST_TRAVERSE(oldlist, txn, list) {
       if (active) {
          if (txn->active) {
             break;
          }
       } else if (!strcasecmp(txn->name, name)) {
          break;
       }
    }
    AST_LIST_UNLOCK(oldlist);
    return txn;
 }
load_module()
static int load_module (void) static
Definition at line 517 of file res_odbc_transaction.c.
References app_commit, app_rollback, ast_custom_function_register, AST_MODFLAG_GLOBAL_SYMBOLS, AST_MODFLAG_LOAD_ORDER, AST_MODPRI_REALTIME_DEPEND, AST_MODULE_INFO(), AST_MODULE_SUPPORT_CORE, ast_register_application_xml, ASTERISK_GPL_KEY, commit_exec(), rollback_exec(), and unload_module().
 {
    ast_register_application_xml(app_commit, commit_exec);
    ast_register_application_xml(app_rollback, rollback_exec);
    ast_custom_function_register(&odbc_function);
    return 0;
 }
mark_transaction_active()
static int mark_transaction_active (struct ast_channel * chan, struct odbc_txn_frame * tx) static
Definition at line 359 of file res_odbc_transaction.c.
References odbc_txn_frame::active, ast_channel_datastore_find(), ast_channel_lock, ast_channel_unlock, AST_LIST_HEAD, AST_LIST_LOCK, AST_LIST_TRAVERSE, AST_LIST_UNLOCK, ast_datastore::data, odbc_txn_frame::list, and NULL.
Referenced by acf_transaction_write().
 {
    struct ast_datastore *txn_store;
    AST_LIST_HEAD(, odbc_txn_frame) *oldlist;
    struct odbc_txn_frame *active = NULL, *txn;
    if (!chan) {
       return -1;
    }
    ast_channel_lock(chan);
    if (!(txn_store = ast_channel_datastore_find(chan, &txn_info, NULL))) {
       ast_channel_unlock(chan);
       return -1;
    }
    oldlist = txn_store->data;
    AST_LIST_LOCK(oldlist);
    AST_LIST_TRAVERSE(oldlist, txn, list) {
       if (txn == tx) {
          txn->active = 1;
          active = txn;
       } else {
          txn->active = 0;
       }
    }
    AST_LIST_UNLOCK(oldlist);
    ast_channel_unlock(chan);
    return active ? 0 : -1;
 }
odbc_txn_free()
static void odbc_txn_free (void * vdata) static
Definition at line 112 of file res_odbc_transaction.c.
References ast_debug, ast_free, AST_LIST_HEAD, AST_LIST_HEAD_DESTROY, AST_LIST_LOCK, AST_LIST_REMOVE_HEAD, AST_LIST_UNLOCK, odbc_txn_frame::list, and release_transaction().
 {
    struct odbc_txn_frame *tx;
    AST_LIST_HEAD(, odbc_txn_frame) *oldlist = vdata;
    ast_debug(2, "odbc_txn_free(%p) called\n", vdata);
    AST_LIST_LOCK(oldlist);
    while ((tx = AST_LIST_REMOVE_HEAD(oldlist, list))) {
       release_transaction(tx);
    }
    AST_LIST_UNLOCK(oldlist);
    AST_LIST_HEAD_DESTROY(oldlist);
    ast_free(oldlist);
 }
release_transaction()
static struct odbc_txn_frame * release_transaction (struct odbc_txn_frame * tx) static
Definition at line 244 of file res_odbc_transaction.c.
References ast_debug, ast_free, ast_odbc_print_errors(), ast_odbc_release_obj(), odbc_obj::con, odbc_txn_frame::forcecommit, NULL, and odbc_txn_frame::obj.
Referenced by odbc_txn_free().
 {
    if (!tx) {
       return NULL;
    }
    ast_debug(2, "release_transaction(%p) called (tx->obj = %p\n", tx, tx->obj);
    ast_debug(1, "called on a transactional handle with %s\n", tx->forcecommit ? "COMMIT" : "ROLLBACK");
    if (SQLEndTran(SQL_HANDLE_DBC, tx->obj->con, tx->forcecommit ? SQL_COMMIT : SQL_ROLLBACK) == SQL_ERROR) {
       ast_odbc_print_errors(SQL_HANDLE_DBC, tx->obj->con, "SQLEndTran");
    }
    /* Transaction is done, reset autocommit
     *
     * XXX I'm unsure if this is actually necessary, since we're releasing
     * the connection back to unixODBC. However, if unixODBC pooling is enabled,
     * it can't hurt to do just in case.
     */
    if (SQLSetConnectAttr(tx->obj->con, SQL_ATTR_AUTOCOMMIT, (void *)SQL_AUTOCOMMIT_ON, 0) == SQL_ERROR) {
       ast_odbc_print_errors(SQL_HANDLE_DBC, tx->obj->con, "SQLSetAttr");
    }
    ast_odbc_release_obj(tx->obj);
    ast_free(tx);
    return NULL;
 }
rollback_exec()
static int rollback_exec (struct ast_channel * chan, const char * data) static
Definition at line 294 of file res_odbc_transaction.c.
References ast_odbc_print_errors(), ast_str_buffer(), ast_strlen_zero, odbc_obj::con, find_transaction(), NULL, odbc_txn_frame::obj, and pbx_builtin_setvar_helper().
Referenced by load_module().
 {
    struct odbc_txn_frame *tx;
    if (ast_strlen_zero(data)) {
       tx = find_transaction(chan, NULL, 1);
    } else {
       tx = find_transaction(chan, data, 0);
    }
    /* XXX ROLLBACK_RESULT is set to OK even if no transaction was found. Very misleading */
    pbx_builtin_setvar_helper(chan, "ROLLBACK_RESULT", "OK");
    if (tx) {
       if (SQLEndTran(SQL_HANDLE_DBC, tx->obj->con, SQL_ROLLBACK) == SQL_ERROR) {
          struct ast_str *errors = ast_odbc_print_errors(SQL_HANDLE_DBC, tx->obj->con, "SQLEndTran");
          pbx_builtin_setvar_helper(chan, "ROLLBACK_RESULT", ast_str_buffer(errors));
       }
    }
    return 0;
 }
unload_module()
static int unload_module (void) static
Definition at line 512 of file res_odbc_transaction.c.
Referenced by load_module().
 {
    return -1;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_GLOBAL_SYMBOLS | AST_MODFLAG_LOAD_ORDER , .description = "ODBC transaction resource" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_REALTIME_DEPEND, } static
Definition at line 530 of file res_odbc_transaction.c.
app_commit
const char* const app_commit = "ODBC_Commit" static
Definition at line 504 of file res_odbc_transaction.c.
Referenced by load_module().
app_rollback
const char* const app_rollback = "ODBC_Rollback" static
Definition at line 505 of file res_odbc_transaction.c.
Referenced by load_module().
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 530 of file res_odbc_transaction.c.
odbc_function
struct ast_custom_function odbc_function static
Initial value:
= {
   .name = "ODBC",
   .read = acf_transaction_read,
   .write = acf_transaction_write,
}
Definition at line 498 of file res_odbc_transaction.c.
txn_info
const struct ast_datastore_info txn_info static
Initial value:
= {
   .type = "ODBC_Transaction",
   .destroy = odbc_txn_free,
}
Definition at line 128 of file res_odbc_transaction.c.