Asterisk - The Open Source Telephony Project: event.c File Reference
event.c File Reference
Internal generic event system.
#include "asterisk.h"
#include "asterisk/_private.h"
#include "asterisk/event.h"
#include "asterisk/linkedlists.h"
#include "asterisk/dlinkedlists.h"
#include "asterisk/lock.h"
#include "asterisk/utils.h"
#include "asterisk/unaligned.h"
#include "asterisk/taskprocessor.h"
#include "asterisk/astobj2.h"
#include "asterisk/cli.h"
Data Structures
struct ast_ev_check_list
Subscription event check list.
struct ast_event
An event.
struct ast_event_ie
An event information element.
struct ast_event_ie_str_payload
The payload for a string information element.
struct ast_event_ie_val
struct ie_map
IE payload types and names.
Functions
int ast_event_append_eid (struct ast_event **event)
Append the global EID IE.
int ast_event_append_ie_bitflags (struct ast_event **event, enum ast_event_ie_type ie_type, uint32_t flags)
Append an information element that has a bitflags payload.
int ast_event_append_ie_raw (struct ast_event **event, enum ast_event_ie_type ie_type, const void *data, size_t data_len)
Append an information element that has a raw payload.
int ast_event_append_ie_str (struct ast_event **event, enum ast_event_ie_type ie_type, const char *str)
Append an information element that has a string payload.
int ast_event_append_ie_uint (struct ast_event **event, enum ast_event_ie_type ie_type, uint32_t data)
Append an information element that has an integer payload.
void ast_event_destroy (struct ast_event *event)
Destroy an event.
enum ast_event_ie_pltype ast_event_get_ie_pltype (enum ast_event_ie_type ie_type)
Get the payload type for a given information element type.
const void * ast_event_get_ie_raw (const struct ast_event *event, enum ast_event_ie_type ie_type)
Get the value of an information element that has a raw payload.
uint16_t ast_event_get_ie_raw_payload_len (const struct ast_event *event, enum ast_event_ie_type ie_type)
Get the length of the raw payload for a particular IE.
const char * ast_event_get_ie_str (const struct ast_event *event, enum ast_event_ie_type ie_type)
Get the value of an information element that has a string payload.
const char * ast_event_get_ie_type_name (enum ast_event_ie_type ie_type)
Get the string representation of an information element type.
uint32_t ast_event_get_ie_uint (const struct ast_event *event, enum ast_event_ie_type ie_type)
Get the value of an information element that has an integer payload.
size_t ast_event_get_size (const struct ast_event *event)
Get the size of an event.
enum ast_event_type ast_event_get_type (const struct ast_event *event)
Get the type for an event.
const char * ast_event_get_type_name (const struct ast_event *event)
Get the string representation of the type of the given event.
const char * ast_event_iterator_get_ie_str (struct ast_event_iterator *iterator)
Get the value of the current IE in the iterator as a string payload.
enum ast_event_ie_type ast_event_iterator_get_ie_type (struct ast_event_iterator *iterator)
Get the type of the current IE in the iterator instance.
uint32_t ast_event_iterator_get_ie_uint (struct ast_event_iterator *iterator)
Get the value of the current IE in the iterator as an integer payload.
int ast_event_iterator_init (struct ast_event_iterator *iterator, const struct ast_event *event)
Initialize an event iterator instance.
int ast_event_iterator_next (struct ast_event_iterator *iterator)
Move iterator instance to next IE.
size_t ast_event_minimum_length (void)
Get the minimum length of an ast_event.
struct ast_event * ast_event_new (enum ast_event_type type,...)
Create a new event.
static void * event_iterator_get_ie_raw (struct ast_event_iterator *iterator)
static uint16_t event_iterator_get_ie_raw_payload_len (struct ast_event_iterator *iterator)
Variables
static const char *const event_names [AST_EVENT_TOTAL]
Event Names.
static const struct ie_map ie_maps [AST_EVENT_IE_TOTAL]
Detailed Description
Internal generic event system.
Author
Russell Bryant russe.nosp@m.ll@d.nosp@m.igium.nosp@m..com
Definition in file event.c.
Function Documentation
ast_event_append_eid()
int ast_event_append_eid (struct ast_event ** event)
Append the global EID IE.
Parameters
event the event to append IE to
Note
For ast_event_new() that includes IEs, this is done automatically for you.
Return values
0 success
-1 failure
Definition at line 518 of file event.c.
References ast_eid_default, ast_event_append_ie_raw(), and AST_EVENT_IE_EID.
Referenced by ast_event_new().
 {
    return ast_event_append_ie_raw(event, AST_EVENT_IE_EID,
          &ast_eid_default, sizeof(ast_eid_default));
 }
ast_event_append_ie_bitflags()
int ast_event_append_ie_bitflags (struct ast_event ** event, enum ast_event_ie_type ie_type, uint32_t bitflags)
Append an information element that has a bitflags payload.
Parameters
event the event that the IE will be appended to
ie_type the type of IE to append
bitflags the flags that are the payload of the IE
Return values
0 success
-1 failure
Since
1.8
The pointer to the event will get updated with the new location for the event that now contains the appended information element. If the re-allocation of the memory for this event fails, it will be set to NULL.
Definition at line 367 of file event.c.
References ast_event_append_ie_raw().
Referenced by ast_event_new().
 {
    flags = htonl(flags);
    return ast_event_append_ie_raw(event, ie_type, &flags, sizeof(flags));
 }
ast_event_append_ie_raw()
int ast_event_append_ie_raw (struct ast_event ** event, enum ast_event_ie_type ie_type, const void * data, size_t data_len)
Append an information element that has a raw payload.
Parameters
event the event that the IE will be appended to
ie_type the type of IE to append
data A pointer to the raw data for the payload of the IE
data_len The amount of data to copy into the payload
Return values
0 success
-1 failure
The pointer to the event will get updated with the new location for the event that now contains the appended information element. If the re-allocation of the memory for this event fails, it will be set to NULL.
Definition at line 374 of file event.c.
References ast_free, ast_realloc, ast_event::event_len, ast_event_ie::ie_payload, ast_event_ie::ie_payload_len, and ast_event_ie::ie_type.
Referenced by ast_event_append_eid(), ast_event_append_ie_bitflags(), ast_event_append_ie_str(), ast_event_append_ie_uint(), and ast_event_new().
 {
    struct ast_event_ie *ie;
    struct ast_event *old_event;
    unsigned int extra_len;
    uint16_t event_len;
    event_len = ntohs((*event)->event_len);
    extra_len = sizeof(*ie) + data_len;
    old_event = *event;
    *event = ast_realloc(*event, event_len + extra_len);
    if (!*event) {
       ast_free(old_event);
       return -1;
    }
    ie = (struct ast_event_ie *) ( ((char *) *event) + event_len );
    ie->ie_type = htons(ie_type);
    ie->ie_payload_len = htons(data_len);
    memcpy(ie->ie_payload, data, data_len);
    (*event)->event_len = htons(event_len + extra_len);
    return 0;
 }
ast_event_append_ie_str()
int ast_event_append_ie_str (struct ast_event ** event, enum ast_event_ie_type ie_type, const char * str)
Append an information element that has a string payload.
Parameters
event the event that the IE will be appended to
ie_type the type of IE to append
str The string for the payload of the IE
Return values
0 success
-1 failure
The pointer to the event will get updated with the new location for the event that now contains the appended information element. If the re-allocation of the memory for this event fails, it will be set to NULL.
Definition at line 345 of file event.c.
References ast_alloca, ast_event_append_ie_raw(), ast_str_hash(), ast_event_ie_str_payload::hash, and ast_event_ie_str_payload::str.
Referenced by ast_event_new(), and AST_TEST_DEFINE().
 {
    struct ast_event_ie_str_payload *str_payload;
    size_t payload_len;
    payload_len = sizeof(*str_payload) + strlen(str);
    str_payload = ast_alloca(payload_len);
    strcpy(str_payload->str, str);
    str_payload->hash = ast_str_hash(str);
    return ast_event_append_ie_raw(event, ie_type, str_payload, payload_len);
 }
ast_event_append_ie_uint()
int ast_event_append_ie_uint (struct ast_event ** event, enum ast_event_ie_type ie_type, uint32_t data)
Append an information element that has an integer payload.
Parameters
event the event that the IE will be appended to
ie_type the type of IE to append
data The integer for the payload of the IE
Return values
0 success
-1 failure
The pointer to the event will get updated with the new location for the event that now contains the appended information element. If the re-allocation of the memory for this event fails, it will be set to NULL.
Definition at line 360 of file event.c.
References ast_event_append_ie_raw().
Referenced by ast_event_new(), and AST_TEST_DEFINE().
 {
    data = htonl(data);
    return ast_event_append_ie_raw(event, ie_type, &data, sizeof(data));
 }
ast_event_destroy()
void ast_event_destroy (struct ast_event * event)
Destroy an event.
Parameters
event the event to destroy
Returns
Nothing
Definition at line 524 of file event.c.
References ast_free.
Referenced by AST_TEST_DEFINE(), cel_report_event(), corosync_ping(), publish_to_corosync(), and send_cluster_notify().
 {
    ast_free(event);
 }
ast_event_get_ie_pltype()
enum ast_event_ie_pltype ast_event_get_ie_pltype (enum ast_event_ie_type ie_type)
Get the payload type for a given information element type.
Parameters
ie_type the information element type to get the payload type of
Returns
the payload type for the provided IE type
Since
1.6.1
Definition at line 218 of file event.c.
References ARRAY_LEN, AST_EVENT_IE_PLTYPE_UNKNOWN, ast_log, ie_maps, ie_map::ie_pltype, ast_event_ie::ie_type, and LOG_ERROR.
Referenced by dump_event(), and match_ie_val().
 {
    if (ie_type <= 0 || ie_type >= ARRAY_LEN(ie_maps)) {
       ast_log(LOG_ERROR, "Invalid IE type - '%d'\n", ie_type);
       return AST_EVENT_IE_PLTYPE_UNKNOWN;
    }
    return ie_maps[ie_type].ie_pltype;
 }
ast_event_get_ie_raw()
const void* ast_event_get_ie_raw (const struct ast_event * event, enum ast_event_ie_type ie_type)
Get the value of an information element that has a raw payload.
Parameters
event The event to get the IE from
ie_type the type of information element to retrieve
Returns
This returns the payload of the information element with the given type. If the information element isn't found, NULL will be returned.
Definition at line 311 of file event.c.
References ast_event_iterator_get_ie_type(), ast_event_iterator_init(), ast_event_iterator_next(), event_iterator_get_ie_raw(), ast_event_ie::ie_type, and NULL.
Referenced by ast_event_get_ie_str(), ast_event_get_ie_uint(), ast_event_new(), corosync_node_alloc(), corosync_ping_to_event(), cpg_deliver_cb(), publish_cluster_discovery_to_stasis(), publish_corosync_ping_to_stasis(), publish_device_state_to_stasis(), publish_mwi_to_stasis(), and publish_to_corosync().
 {
    struct ast_event_iterator iterator;
    int res;
    for (res = ast_event_iterator_init(&iterator, event); !res; res = ast_event_iterator_next(&iterator)) {
       if (ast_event_iterator_get_ie_type(&iterator) == ie_type) {
          return event_iterator_get_ie_raw(&iterator);
       }
    }
    return NULL;
 }
ast_event_get_ie_raw_payload_len()
uint16_t ast_event_get_ie_raw_payload_len (const struct ast_event * event, enum ast_event_ie_type ie_type)
Get the length of the raw payload for a particular IE.
Parameters
event The event to get the IE payload length from
ie_type the type of information element to get the length of
Returns
If an IE of type ie_type is found, its payload length is returned. Otherwise, 0 is returned.
Definition at line 330 of file event.c.
References ast_event_iterator_get_ie_type(), ast_event_iterator_init(), ast_event_iterator_next(), event_iterator_get_ie_raw_payload_len(), and ast_event_ie::ie_type.
 {
    struct ast_event_iterator iterator;
    int res;
    for (res = ast_event_iterator_init(&iterator, event); !res; res = ast_event_iterator_next(&iterator)) {
       if (ast_event_iterator_get_ie_type(&iterator) == ie_type) {
          return event_iterator_get_ie_raw_payload_len(&iterator);
       }
    }
    return 0;
 }
ast_event_get_ie_str()
const char* ast_event_get_ie_str (const struct ast_event * event, enum ast_event_ie_type ie_type)
Get the value of an information element that has a string payload.
Parameters
event The event to get the IE from
ie_type the type of information element to retrieve
Returns
This returns the payload of the information element with the given type. If the information element isn't found, NULL will be returned.
Definition at line 302 of file event.c.
References ast_event_get_ie_raw(), NULL, and ast_event_ie_str_payload::str.
Referenced by ast_cel_fill_record(), check_event(), corosync_node_alloc(), match_ie_val(), publish_device_state_to_stasis(), publish_mwi_to_stasis(), and test_sub().
 {
    const struct ast_event_ie_str_payload *str_payload;
    str_payload = ast_event_get_ie_raw(event, ie_type);
    return str_payload ? str_payload->str : NULL;
 }
ast_event_get_ie_type_name()
const char* ast_event_get_ie_type_name (enum ast_event_ie_type ie_type)
Get the string representation of an information element type.
Parameters
ie_type the information element type to get the string representation of
Returns
the string representation of the information element type
Since
1.6.1
Definition at line 208 of file event.c.
References ARRAY_LEN, ast_log, ie_maps, ast_event_ie::ie_type, LOG_ERROR, and ie_map::name.
Referenced by add_ip_json_object(), add_json_object(), alloc_security_event_json_object(), append_event_str_single(), append_json_single(), dump_event(), and events_are_equal().
 {
    if (ie_type <= 0 || ie_type >= ARRAY_LEN(ie_maps)) {
       ast_log(LOG_ERROR, "Invalid IE type - '%d'\n", ie_type);
       return "";
    }
    return ie_maps[ie_type].name;
 }
ast_event_get_ie_uint()
uint32_t ast_event_get_ie_uint (const struct ast_event * event, enum ast_event_ie_type ie_type)
Get the value of an information element that has an integer payload.
Parameters
event The event to get the IE from
ie_type the type of information element to retrieve
Returns
This returns the payload of the information element with the given type. However, an IE with a payload of 0, and the case where no IE is found yield the same return value.
Definition at line 293 of file event.c.
References ast_event_get_ie_raw(), and get_unaligned_uint32().
Referenced by ast_cel_fill_record(), check_event(), corosync_node_alloc(), dump_event(), match_ie_val(), publish_cluster_discovery_to_stasis(), publish_device_state_to_stasis(), and publish_mwi_to_stasis().
 {
    const uint32_t *ie_val;
    ie_val = ast_event_get_ie_raw(event, ie_type);
    return ie_val ? ntohl(get_unaligned_uint32(ie_val)) : 0;
 }
ast_event_get_size()
size_t ast_event_get_size (const struct ast_event * event)
Get the size of an event.
Parameters
event the event to get the size of
Returns
the number of bytes contained in the event
Since
1.6.1
Definition at line 228 of file event.c.
References ast_event::event_len.
Referenced by ao2_dup_event(), ast_event_iterator_init(), AST_TEST_DEFINE(), and publish_event_to_corosync().
 {
    size_t res;
    res = ntohs(event->event_len);
    return res;
 }
ast_event_get_type()
enum ast_event_type ast_event_get_type (const struct ast_event * event)
Get the type for an event.
Parameters
event the event to get the type for
Returns
the event type as represented by one of the values in the ast_event_type enum
Definition at line 288 of file event.c.
References ast_event::type.
Referenced by ast_event_get_type_name(), check_event(), check_events(), cpg_deliver_cb(), events_are_equal(), publish_cluster_discovery_to_stasis(), publish_corosync_ping_to_stasis(), publish_device_state_to_stasis(), publish_event_to_corosync(), publish_mwi_to_stasis(), and publish_to_corosync().
 {
    return ntohs(event->type);
 }
ast_event_get_type_name()
const char* ast_event_get_type_name (const struct ast_event * event)
Get the string representation of the type of the given event.
event the event to get the type of
Returns
the string representation of the event type of the provided event
Since
1.6.1
Definition at line 194 of file event.c.
References ARRAY_LEN, ast_event_get_type(), ast_log, LOG_ERROR, and type.
Referenced by cpg_deliver_cb(), and publish_event_to_corosync().
 {
    enum ast_event_type type;
    type = ast_event_get_type(event);
    if ((unsigned int)type >= ARRAY_LEN(event_names)) {
       ast_log(LOG_ERROR, "Invalid event type - '%u'\n", type);
       return "";
    }
    return event_names[type];
 }
ast_event_iterator_get_ie_str()
const char* ast_event_iterator_get_ie_str (struct ast_event_iterator * iterator)
Get the value of the current IE in the iterator as a string payload.
Parameters
iterator The iterator instance
Returns
This returns the payload of the information element as a string.
Definition at line 274 of file event.c.
References ast_event_iterator::ie, ast_event_ie::ie_payload, NULL, and ast_event_ie_str_payload::str.
Referenced by dump_event().
 {
    const struct ast_event_ie_str_payload *str_payload;
    str_payload = (struct ast_event_ie_str_payload *) iterator->ie->ie_payload;
    return str_payload ? str_payload->str : NULL;
 }
ast_event_iterator_get_ie_type()
enum ast_event_ie_type ast_event_iterator_get_ie_type (struct ast_event_iterator * iterator)
Get the type of the current IE in the iterator instance.
Parameters
iterator The iterator instance
Returns
the ie type as represented by one of the value sin the ast_event_ie_type enum
Definition at line 264 of file event.c.
References ast_event_iterator::ie, and ast_event_ie::ie_type.
Referenced by ast_event_get_ie_raw(), ast_event_get_ie_raw_payload_len(), dump_event(), and events_are_equal().
 {
    return ntohs(iterator->ie->ie_type);
 }
ast_event_iterator_get_ie_uint()
uint32_t ast_event_iterator_get_ie_uint (struct ast_event_iterator * iterator)
Get the value of the current IE in the iterator as an integer payload.
Parameters
iterator The iterator instance
Returns
This returns the payload of the information element as a uint.
Definition at line 269 of file event.c.
References get_unaligned_uint32(), ast_event_iterator::ie, and ast_event_ie::ie_payload.
Referenced by dump_event().
 {
    return ntohl(get_unaligned_uint32(iterator->ie->ie_payload));
 }
ast_event_iterator_init()
int ast_event_iterator_init (struct ast_event_iterator * iterator, const struct ast_event * event)
Initialize an event iterator instance.
Parameters
iterator The iterator instance to initialize
event The event that will be iterated through
Return values
0 Success, there are IEs available to iterate
-1 Failure, there are no IEs in the event to iterate
Definition at line 242 of file event.c.
References ast_event_get_size(), ast_event_iterator::event, ast_event_iterator::event_len, ast_event_iterator::ie, and NULL.
Referenced by ast_event_get_ie_raw(), ast_event_get_ie_raw_payload_len(), dump_event(), and events_are_equal().
 {
    int res = 0;
    iterator->event_len = ast_event_get_size(event);
    iterator->event = event;
    if (iterator->event_len >= sizeof(*event) + sizeof(struct ast_event_ie)) {
       iterator->ie = (struct ast_event_ie *) ( ((char *) event) + sizeof(*event) );
    } else {
       iterator->ie = NULL;
       res = -1;
    }
    return res;
 }
ast_event_iterator_next()
int ast_event_iterator_next (struct ast_event_iterator * iterator)
Move iterator instance to next IE.
Parameters
iterator The iterator instance
Return values
0 on success
-1 if end is reached
Definition at line 258 of file event.c.
References ast_event_iterator::event, ast_event_iterator::event_len, ast_event_iterator::ie, and ast_event_ie::ie_payload_len.
Referenced by ast_event_get_ie_raw(), ast_event_get_ie_raw_payload_len(), dump_event(), and events_are_equal().
 {
    iterator->ie = (struct ast_event_ie *) ( ((char *) iterator->ie) + sizeof(*iterator->ie) + ntohs(iterator->ie->ie_payload_len));
    return ((iterator->event_len <= (((char *) iterator->ie) - ((char *) iterator->event))) ? -1 : 0);
 }
ast_event_minimum_length()
size_t ast_event_minimum_length (void)
Get the minimum length of an ast_event.
Returns
minimum amount of memory that will be consumed by any ast_event.
Definition at line 529 of file event.c.
Referenced by cpg_deliver_cb().
 {
    return sizeof(struct ast_event);
 }
ast_event_new()
struct ast_event* ast_event_new (enum ast_event_type event_type, ...)
Create a new event.
Parameters
event_type The type of event to create
The rest of the arguments to this function specify information elements to add to the event. They are specified in the form:
<enum ast_event_ie_type>, [enum ast_event_ie_pltype, [payload] ]
and must end with AST_EVENT_IE_END.
If the ie_type specified is not AST_EVENT_IE_END, then it must be followed by a valid IE payload type. A payload must also be specified after the IE payload type.
Note
The EID IE will be appended automatically when this function is used with at least one IE specified.
Returns
This returns the event that has been created. If there is an error creating the event, NULL will be returned.
Example usage:
if (!(event = ast_event_new(AST_EVENT_MWI,
    AST_EVENT_IE_MAILBOX, AST_EVENT_IE_PLTYPE_STR, mailbox,
    AST_EVENT_IE_NEWMSGS, AST_EVENT_IE_PLTYPE_UINT, new,
    AST_EVENT_IE_OLDMSGS, AST_EVENT_IE_PLTYPE_UINT, old,
    AST_EVENT_IE_END))) {
      return;
}
This creates a MWI event with 3 information elements, a mailbox which is a string, and the number of new and old messages, specified as integers.
Definition at line 402 of file event.c.
References ast_calloc, ast_event_append_eid(), ast_event_append_ie_bitflags(), ast_event_append_ie_raw(), ast_event_append_ie_str(), ast_event_append_ie_uint(), ast_event_get_ie_raw(), AST_EVENT_IE_EID, AST_EVENT_IE_END, AST_EVENT_IE_PLTYPE_BITFLAGS, AST_EVENT_IE_PLTYPE_EXISTS, AST_EVENT_IE_PLTYPE_RAW, AST_EVENT_IE_PLTYPE_STR, AST_EVENT_IE_PLTYPE_UINT, AST_EVENT_IE_PLTYPE_UNKNOWN, AST_EVENT_TOTAL, ast_free, AST_LIST_HEAD_NOLOCK_STATIC, AST_LIST_INSERT_TAIL, AST_LIST_REMOVE_CURRENT, AST_LIST_TRAVERSE, AST_LIST_TRAVERSE_SAFE_BEGIN, AST_LIST_TRAVERSE_SAFE_END, ast_log, ast_malloc, cleanup(), ast_event_ie_val::ie_pltype, ast_event_ie_val::ie_type, ast_event_ie::ie_type, LOG_WARNING, NULL, ast_event_ie_val::payload, ast_event_ie_val::raw, ast_event_ie_val::raw_datalen, ast_event_ie_val::str, and ast_event_ie_val::uint.
Referenced by append_event(), ast_cel_create_event_with_time(), AST_TEST_DEFINE(), corosync_ping(), corosync_ping_to_event(), devstate_to_event(), fake_event(), mwi_to_event(), publish_corosync_ping_to_stasis(), and send_cluster_notify().
 {
    va_list ap;
    struct ast_event *event;
    enum ast_event_ie_type ie_type;
    struct ast_event_ie_val *ie_val;
    AST_LIST_HEAD_NOLOCK_STATIC(ie_vals, ast_event_ie_val);
    /* Invalid type */
    if (type >= AST_EVENT_TOTAL) {
       ast_log(LOG_WARNING, "Someone tried to create an event of invalid "
          "type '%u'!\n", type);
       return NULL;
    }
    va_start(ap, type);
    for (ie_type = va_arg(ap, enum ast_event_ie_type);
       ie_type != AST_EVENT_IE_END;
       ie_type = va_arg(ap, enum ast_event_ie_type))
    {
       struct ast_event_ie_val *ie_value = ast_malloc(sizeof(*ie_value));
       int insert = 0;
       memset(ie_value, 0, sizeof(*ie_value));
       ie_value->ie_type = ie_type;
       ie_value->ie_pltype = va_arg(ap, enum ast_event_ie_pltype);
       switch (ie_value->ie_pltype) {
       case AST_EVENT_IE_PLTYPE_UINT:
          ie_value->payload.uint = va_arg(ap, uint32_t);
          insert = 1;
          break;
       case AST_EVENT_IE_PLTYPE_BITFLAGS:
          ie_value->payload.uint = va_arg(ap, uint32_t);
          insert = 1;
          break;
       case AST_EVENT_IE_PLTYPE_STR:
          ie_value->payload.str = va_arg(ap, const char *);
          insert = 1;
          break;
       case AST_EVENT_IE_PLTYPE_RAW:
       {
          void *data = va_arg(ap, void *);
          size_t datalen = va_arg(ap, size_t);
          ie_value->payload.raw = ast_malloc(datalen);
          memcpy(ie_value->payload.raw, data, datalen);
          ie_value->raw_datalen = datalen;
          insert = 1;
          break;
       }
       case AST_EVENT_IE_PLTYPE_UNKNOWN:
       case AST_EVENT_IE_PLTYPE_EXISTS:
          break;
       }
       if (insert) {
          AST_LIST_INSERT_TAIL(&ie_vals, ie_value, entry);
       } else {
          ast_log(LOG_WARNING, "Unsupported PLTYPE(%d)\n", ie_value->ie_pltype);
       }
    }
    va_end(ap);
    if (!(event = ast_calloc(1, sizeof(*event)))) {
       return NULL;
    }
    event->type = htons(type);
    event->event_len = htons(sizeof(*event));
    AST_LIST_TRAVERSE(&ie_vals, ie_val, entry) {
       switch (ie_val->ie_pltype) {
       case AST_EVENT_IE_PLTYPE_STR:
          ast_event_append_ie_str(&event, ie_val->ie_type, ie_val->payload.str);
          break;
       case AST_EVENT_IE_PLTYPE_UINT:
          ast_event_append_ie_uint(&event, ie_val->ie_type, ie_val->payload.uint);
          break;
       case AST_EVENT_IE_PLTYPE_BITFLAGS:
          ast_event_append_ie_bitflags(&event, ie_val->ie_type, ie_val->payload.uint);
          break;
       case AST_EVENT_IE_PLTYPE_RAW:
          ast_event_append_ie_raw(&event, ie_val->ie_type,
                ie_val->payload.raw, ie_val->raw_datalen);
          break;
       case AST_EVENT_IE_PLTYPE_EXISTS:
       case AST_EVENT_IE_PLTYPE_UNKNOWN:
          break;
       }
       /* realloc inside one of the append functions failed */
       if (!event) {
          goto cleanup;
       }
    }
    if (!ast_event_get_ie_raw(event, AST_EVENT_IE_EID)) {
       /* If the event is originating on this server, add the server's
        * entity ID to the event. */
       ast_event_append_eid(&event);
    }
 cleanup:
    AST_LIST_TRAVERSE_SAFE_BEGIN(&ie_vals, ie_val, entry) {
       AST_LIST_REMOVE_CURRENT(entry);
       if (ie_val->ie_pltype == AST_EVENT_IE_PLTYPE_RAW) {
          ast_free(ie_val->payload.raw);
       }
       ast_free(ie_val);
    }
    AST_LIST_TRAVERSE_SAFE_END;
    return event;
 }
event_iterator_get_ie_raw()
static void* event_iterator_get_ie_raw (struct ast_event_iterator * iterator) static
Definition at line 283 of file event.c.
References ast_event_iterator::ie, and ast_event_ie::ie_payload.
Referenced by ast_event_get_ie_raw().
 {
    return iterator->ie->ie_payload;
 }
event_iterator_get_ie_raw_payload_len()
static uint16_t event_iterator_get_ie_raw_payload_len (struct ast_event_iterator * iterator) static
Definition at line 325 of file event.c.
References ast_event_iterator::ie, and ast_event_ie::ie_payload_len.
Referenced by ast_event_get_ie_raw_payload_len().
 {
    return ntohs(iterator->ie->ie_payload_len);
 }
Variable Documentation
event_names
const char* const event_names[AST_EVENT_TOTAL] static
Event Names.
Definition at line 109 of file event.c.
ie_maps
const struct ie_map ie_maps[AST_EVENT_IE_TOTAL] static
Referenced by ast_event_get_ie_pltype(), and ast_event_get_ie_type_name().