Asterisk - The Open Source Telephony Project: app_dumpchan.c File Reference
app_dumpchan.c File Reference
Dial plan applications
Application to dump channel variables.
#include "asterisk.h"
#include "asterisk/pbx.h"
#include "asterisk/module.h"
#include "asterisk/channel.h"
#include "asterisk/app.h"
#include "asterisk/translate.h"
#include "asterisk/bridge.h"
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int dumpchan_exec (struct ast_channel *chan, const char *data)
static int load_module (void)
static int serialize_showchan (struct ast_channel *c, char *buf, size_t size)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Dump Info About The Calling Channel" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, }
static const char app [] = "DumpChan"
static const struct ast_module_info * ast_module_info = &__mod_info
Detailed Description
Application to dump channel variables.
Author
Anthony Minessale anthm.nosp@m.ct@y.nosp@m.ahoo..nosp@m.com
Definition in file app_dumpchan.c.
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 207 of file app_dumpchan.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 207 of file app_dumpchan.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 207 of file app_dumpchan.c.
dumpchan_exec()
static int dumpchan_exec (struct ast_channel * chan, const char * data) static
Definition at line 172 of file app_dumpchan.c.
References ast_channel_name(), ast_str_buffer(), ast_str_thread_get(), ast_strlen_zero, ast_verb, sip_to_pjsip::info(), pbx_builtin_serialize_variables(), serialize_showchan(), and VERBOSITY_ATLEAST.
Referenced by load_module().
 {
    struct ast_str *vars = ast_str_thread_get(&ast_str_thread_global_buf, 16);
    char info[2048];
    int level = 0;
    static char *line = "================================================================================";
    if (!ast_strlen_zero(data))
       level = atoi(data);
    if (VERBOSITY_ATLEAST(level)) {
       serialize_showchan(chan, info, sizeof(info));
       pbx_builtin_serialize_variables(chan, &vars);
       ast_verb(level, "\n"
          "Dumping Info For Channel: %s:\n"
          "%s\n"
          "Info:\n"
          "%s\n"
          "Variables:\n"
          "%s%s\n", ast_channel_name(chan), line, info, ast_str_buffer(vars), line);
    }
    return 0;
 }
load_module()
static int load_module (void) static
Definition at line 202 of file app_dumpchan.c.
References app, ast_register_application_xml, and dumpchan_exec().
 {
    return ast_register_application_xml(app, dumpchan_exec);
 }
serialize_showchan()
static int serialize_showchan (struct ast_channel * c, char * buf, size_t size) static
Definition at line 69 of file app_dumpchan.c.
References ao2_cleanup, ast_channel_appl(), ast_channel_blockproc(), ast_channel_caller(), ast_channel_callgroup(), ast_channel_connected(), ast_channel_context(), ast_channel_data(), ast_channel_dialed(), ast_channel_exten(), ast_channel_fd(), ast_channel_fin(), ast_channel_flags(), ast_channel_fout(), ast_channel_get_bridge(), ast_channel_get_duration(), ast_channel_language(), ast_channel_linkedid(), ast_channel_lock, ast_channel_name(), ast_channel_nativeformats(), ast_channel_parkinglot(), ast_channel_pickupgroup(), ast_channel_priority(), ast_channel_rawreadformat(), ast_channel_rawwriteformat(), ast_channel_readformat(), ast_channel_readtrans(), ast_channel_redirecting(), ast_channel_rings(), ast_channel_tech(), ast_channel_uniqueid(), ast_channel_unlock, ast_channel_whentohangup(), ast_channel_writeformat(), ast_channel_writetrans(), AST_FLAG_BLOCKING, ast_format_cap_get_names(), AST_FORMAT_CAP_NAMES_LEN, ast_format_get_name(), ast_print_group(), ast_state2str(), ast_str_alloca, ast_test_flag, ast_translate_path_to_str(), DEBUGCHAN_FLAG, min, name, S_COR, S_OR, type, and ast_bridge::uniqueid.
Referenced by dumpchan_exec().
 {
    long elapsed_seconds = 0;
    int hour = 0, min = 0, sec = 0;
    struct ast_str *format_buf = ast_str_alloca(AST_FORMAT_CAP_NAMES_LEN);
    char cgrp[256];
    char pgrp[256];
    struct ast_str *write_transpath = ast_str_alloca(256);
    struct ast_str *read_transpath = ast_str_alloca(256);
    struct ast_bridge *bridge;
    memset(buf, 0, size);
    if (!c)
       return 0;
    elapsed_seconds = ast_channel_get_duration(c);
    hour = elapsed_seconds / 3600;
    min = (elapsed_seconds % 3600) / 60;
    sec = elapsed_seconds % 60;
    ast_channel_lock(c);
    bridge = ast_channel_get_bridge(c);
    snprintf(buf,size,
       "Name=               %s\n"
       "Type=               %s\n"
       "UniqueID=           %s\n"
       "LinkedID=           %s\n"
       "CallerIDNum=        %s\n"
       "CallerIDName=       %s\n"
       "ConnectedLineIDNum= %s\n"
       "ConnectedLineIDName=%s\n"
       "DNIDDigits=         %s\n"
       "RDNIS=              %s\n"
       "Parkinglot=         %s\n"
       "Language=           %s\n"
       "State=              %s (%u)\n"
       "Rings=              %d\n"
       "NativeFormat=       %s\n"
       "WriteFormat=        %s\n"
       "ReadFormat=         %s\n"
       "RawWriteFormat=     %s\n"
       "RawReadFormat=      %s\n"
       "WriteTranscode=     %s %s\n"
       "ReadTranscode=      %s %s\n"
       "1stFileDescriptor=  %d\n"
       "Framesin=           %u %s\n"
       "Framesout=          %u %s\n"
       "TimetoHangup=       %ld\n"
       "ElapsedTime=        %dh%dm%ds\n"
       "BridgeID=           %s\n"
       "Context=            %s\n"
       "Extension=          %s\n"
       "Priority=           %d\n"
       "CallGroup=          %s\n"
       "PickupGroup=        %s\n"
       "Application=        %s\n"
       "Data=               %s\n"
       "Blocking_in=        %s\n",
       ast_channel_name(c),
       ast_channel_tech(c)->type,
       ast_channel_uniqueid(c),
       ast_channel_linkedid(c),
       S_COR(ast_channel_caller(c)->id.number.valid, ast_channel_caller(c)->id.number.str, "(N/A)"),
       S_COR(ast_channel_caller(c)->id.name.valid, ast_channel_caller(c)->id.name.str, "(N/A)"),
       S_COR(ast_channel_connected(c)->id.number.valid, ast_channel_connected(c)->id.number.str, "(N/A)"),
       S_COR(ast_channel_connected(c)->id.name.valid, ast_channel_connected(c)->id.name.str, "(N/A)"),
       S_OR(ast_channel_dialed(c)->number.str, "(N/A)"),
       S_COR(ast_channel_redirecting(c)->from.number.valid, ast_channel_redirecting(c)->from.number.str, "(N/A)"),
       ast_channel_parkinglot(c),
       ast_channel_language(c),
       ast_state2str(ast_channel_state(c)),
       ast_channel_state(c),
       ast_channel_rings(c),
       ast_format_cap_get_names(ast_channel_nativeformats(c), &format_buf),
       ast_format_get_name(ast_channel_writeformat(c)),
       ast_format_get_name(ast_channel_readformat(c)),
       ast_format_get_name(ast_channel_rawwriteformat(c)),
       ast_format_get_name(ast_channel_rawreadformat(c)),
       ast_channel_writetrans(c) ? "Yes" : "No",
       ast_translate_path_to_str(ast_channel_writetrans(c), &write_transpath),
       ast_channel_readtrans(c) ? "Yes" : "No",
       ast_translate_path_to_str(ast_channel_readtrans(c), &read_transpath),
       ast_channel_fd(c, 0),
       ast_channel_fin(c) & ~DEBUGCHAN_FLAG, (ast_channel_fin(c) & DEBUGCHAN_FLAG) ? " (DEBUGGED)" : "",
       ast_channel_fout(c) & ~DEBUGCHAN_FLAG, (ast_channel_fout(c) & DEBUGCHAN_FLAG) ? " (DEBUGGED)" : "",
       (long)ast_channel_whentohangup(c)->tv_sec,
       hour,
       min,
       sec,
       bridge ? bridge->uniqueid : "(Not bridged)",
       ast_channel_context(c),
       ast_channel_exten(c),
       ast_channel_priority(c),
       ast_print_group(cgrp, sizeof(cgrp), ast_channel_callgroup(c)),
       ast_print_group(pgrp, sizeof(pgrp), ast_channel_pickupgroup(c)),
       ast_channel_appl(c) ? ast_channel_appl(c) : "(N/A)",
       ast_channel_data(c) ? S_OR(ast_channel_data(c), "(Empty)") : "(None)",
       (ast_test_flag(ast_channel_flags(c), AST_FLAG_BLOCKING) ? ast_channel_blockproc(c) : "(Not Blocking)"));
    ast_channel_unlock(c);
    ao2_cleanup(bridge);
    return 0;
 }
unload_module()
static int unload_module (void) static
Definition at line 197 of file app_dumpchan.c.
References app, and ast_unregister_application().
 {
    return ast_unregister_application(app);
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Dump Info About The Calling Channel" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, } static
Definition at line 207 of file app_dumpchan.c.
app
const char app[] = "DumpChan" static
Definition at line 67 of file app_dumpchan.c.
Referenced by load_module(), and unload_module().
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 207 of file app_dumpchan.c.