Asterisk - The Open Source Telephony Project: test_expr.c File Reference
test_expr.c File Reference
Expression Tests.
#include "asterisk.h"
#include "asterisk/utils.h"
#include "asterisk/module.h"
#include "asterisk/test.h"
#include "asterisk/ast_expr.h"
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
AST_TEST_DEFINE (expr_test)
static int load_module (void)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Expression evaluation tests" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, }
static const struct ast_module_info * ast_module_info = &__mod_info
Detailed Description
Expression Tests.
Author
Tilghman Lesher <tlesher AT digium DOT com>
Verify that the expression parser works as intended.
Definition in file test_expr.c.
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 190 of file test_expr.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 190 of file test_expr.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 190 of file test_expr.c.
AST_TEST_DEFINE()
AST_TEST_DEFINE (expr_test)
Definition at line 41 of file test_expr.c.
References ARRAY_LEN, ast_expr(), AST_TEST_FAIL, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_test_status_update, buf, sip_to_pjsip::info(), input(), len(), NULL, TEST_EXECUTE, and TEST_INIT.
 {
    int res = AST_TEST_PASS, i, len;
    struct {
       char *input;
       const char *output;
    } tests[] = {
       { "2 + 2", "4" },
       { "      2     +       2            ", "4" },
       { "", "" },
       { "2 - 4", "-2" },
       { "4 - 2", "2" },
       { "-4 - -2", "-2" },
       { "4 + 2 * 8", "20" },
       { "(4 + 2) * 8", "48" },
       { "4 + (2 * 8)", "20" },
       { "4 + (2 * 8) ? 3 :: 6", "3" },
       { "4 + 8 / 2", "8" },
       { "FLOOR(4 + 8 / 3)", "6" }, /* Floating point op on 1.6 and higher, need FLOOR() to keep result sane */
       { "(4+8) / 3", "4" },
       { "4 + 8 % 3", "6" },
       { "4 + 9 % 3", "4" },
       { "(4+9) %3", "1" },
       { "(4+8) %3", "0" },
       { "(4+9) %3", "1" },
       { "(4+8) %3", "0" },
       { "(4+9) % 3", "1" },
       { "(4+8) % 3", "0" },
       { "(4+9) % 3", "1" },
       { "(4+8) % 3", "0" },
       { "(4+9)% 3", "1" },
       { "(4+8)% 3", "0" },
       { "(4+9)% 3", "1" },
       { "(4+8)% 3", "0" },
       { "4 & 4", "4" },
       { "0 & 4", "0" },
       { "0 & 0", "0" },
       { "2 | 0", "2" },
       { "2 | 4", "2" },
       { "0 | 0", "0" },
       { "!0 | 0", "1" },
       { "!4 | 0", "0" },
       { "4 | !0", "4" },
       { "!4 | !0", "1" },
       { "0", "0" },
       { "!0", "1" },
       { "00", "00" },
       { "!00", "1" },
       { "1", "1" },
       { "!1", "0" },
       { "01", "01" },
       { "!01", "0" },
       { "3 < 4", "1" },
       { "4 < 3", "0" },
       { "3 > 4", "0" },
       { "4 > 3", "1" },
       { "3 = 3", "1" },
       { "3 = 4", "0" },
       { "3 != 3", "0" },
       { "3 != 4", "1" },
       { "3 >= 4", "0" },
       { "3 >= 3", "1" },
       { "4 >= 3", "1" },
       { "3 <= 4", "1" },
       { "4 <= 3", "0" },
       { "4 <= 4", "1" },
       { "3 > 4 & 4 < 3", "0" },
       { "4 > 3 & 3 < 4", "1" },
       { "x = x", "1" },
       { "y = x", "0" },
       { "x != y", "1" },
       { "x != x", "0" },
       { "\"Something interesting\" =~ interesting", "11" },
       { "\"Something interesting\" =~ Something", "9" },
       { "\"Something interesting\" : Something", "9" },
       { "\"Something interesting\" : interesting", "0" },
       { "\"Something interesting\" =~ \"interesting\"", "11" },
       { "\"Something interesting\" =~ \"Something\"", "9" },
       { "\"Something interesting\" : \"Something\"", "9" },
       { "\"Something interesting\" : \"interesting\"", "0" },
       { "\"Something interesting\" =~ (interesting)", "11" },
       { "\"Something interesting\" =~ (Something)", "9" },
       { "\"Something interesting\" : (Something)", "9" },
       { "\"Something interesting\" : (interesting)", "0" },
       { "\"Something interesting\" =~ \"\\(interesting\\)\"", "0" },
       { "\"Something interesting\" =~ \"\\(Something\\)\"", "0" },
       { "\"Something interesting\" : \"\\(Something\\)\"", "0" },
       { "\"Something interesting\" : \"\\(interesting\\)\"", "0" },
       { "\"011043567857575\" : \"011\\(..\\)\"", "0" },
       { "\"9011043567857575\" : \"011\\(..\\)\"", "0" },
       { "\"011043567857575\" =~ \"011\\(..\\)\"", "0" },
       { "\"9011043567857575\" =~ \"011\\(..\\)\"", "0" },
       { "\"Something interesting\" =~ (interesting)", "11" },
       { "\"Something interesting\" =~ (Something)", "9" },
       { "\"Something interesting\" : (Something)", "9" },
       { "\"Something interesting\" : (interesting)", "0" },
       { "\"Something interesting\" =~ \"(interesting)\"", "interesting" },
       { "\"Something interesting\" =~ \"(Something)\"", "Something" },
       { "\"Something interesting\" : \"(Something)\"", "Something" },
       { "\"Something interesting\" : \"(interesting)\"", "" },
       { "\"011043567857575\" : \"011(..)\"", "04" },
       { "\"9011043567857575\" : \"011(..)\"", "" },
       { "\"011043567857575\" =~ \"011(..)\"", "04" },
       { "\"9011043567857575\" =~ \"011(..)\"", "04" },
       { "3", "3" },
       { "something", "something" },
       { "043", "043" },
       { "${GLOBAL(ULKOPREFIX)}9${x}", "${GLOBAL(ULKOPREFIX)}9${x}" },
       { "512059${x}", "512059${x}" },
    };
    char buf[32];
    switch (cmd) {
    case TEST_INIT:
       info->name = "expr_test";
       info->category = "/main/ast_expr/";
       info->summary = "unit test for the internal expression engine";
       info->description =
          "Verifies behavior for the internal expression engine";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    for (i = 0; i < ARRAY_LEN(tests); i++) {
       memset(buf, 0, sizeof(buf));
       len = ast_expr(tests[i].input, buf, sizeof(buf), NULL);
       buf[len] = '\0';
       if (strcmp(buf, tests[i].output)) {
          ast_test_status_update(test, "Case %d: expression '%s' evaluated as '%s', but should have evaluated as '%s'\n", i + 1, tests[i].input, buf, tests[i].output);
          res = AST_TEST_FAIL;
       }
    }
    return res;
 }
load_module()
static int load_module (void) static
Definition at line 184 of file test_expr.c.
References AST_MODULE_LOAD_SUCCESS, and AST_TEST_REGISTER.
 {
    AST_TEST_REGISTER(expr_test);
    return AST_MODULE_LOAD_SUCCESS;
 }
unload_module()
static int unload_module (void) static
Definition at line 178 of file test_expr.c.
References AST_TEST_UNREGISTER.
 {
    AST_TEST_UNREGISTER(expr_test);
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Expression evaluation tests" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, } static
Definition at line 190 of file test_expr.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 190 of file test_expr.c.