Asterisk - The Open Source Telephony Project: app_transfer.c File Reference
app_transfer.c File Reference
Dial plan applications
Transfer a caller.
#include "asterisk.h"
#include "asterisk/pbx.h"
#include "asterisk/module.h"
#include "asterisk/app.h"
#include "asterisk/channel.h"
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int load_module (void)
static int transfer_exec (struct ast_channel *chan, const char *data)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Transfers a caller to another extension" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, }
static const char *const app = "Transfer"
static const struct ast_module_info * ast_module_info = &__mod_info
Detailed Description
Transfer a caller.
Author
Mark Spencer marks.nosp@m.ter@.nosp@m.digiu.nosp@m.m.co.nosp@m.m
Requires transfer support from channel driver
Definition in file app_transfer.c.
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 166 of file app_transfer.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 166 of file app_transfer.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 166 of file app_transfer.c.
load_module()
static int load_module (void) static
Definition at line 161 of file app_transfer.c.
References app, ast_register_application_xml, and transfer_exec().
 {
    return ast_register_application_xml(app, transfer_exec);
 }
transfer_exec()
static int transfer_exec (struct ast_channel * chan, const char * data) static
Definition at line 87 of file app_transfer.c.
References args, AST_APP_ARG, ast_channel_name(), ast_channel_tech(), ast_debug, AST_DECLARE_APP_ARGS, ast_log, AST_STANDARD_APP_ARGS, ast_strdupa, ast_strlen_zero, ast_transfer_protocol(), len(), LOG_WARNING, NULL, parse(), pbx_builtin_setvar_helper(), status, transfer, and type.
Referenced by load_module().
 {
    int res;
    int len;
    char *slash;
    char *tech = NULL;
    char *dest = NULL;
    char *status;
    char *parse;
    int protocol = 0;
    char status_protocol[20];
    AST_DECLARE_APP_ARGS(args,
       AST_APP_ARG(dest);
    );
    if (ast_strlen_zero((char *)data)) {
       ast_log(LOG_WARNING, "Transfer requires an argument ([Tech/]destination)\n");
       pbx_builtin_setvar_helper(chan, "TRANSFERSTATUS", "FAILURE");
       snprintf(status_protocol, sizeof(status_protocol), "%d", protocol);
       pbx_builtin_setvar_helper(chan, "TRANSFERSTATUSPROTOCOL", status_protocol);
       return 0;
    } else
       parse = ast_strdupa(data);
    AST_STANDARD_APP_ARGS(args, parse);
    dest = args.dest;
    if ((slash = strchr(dest, '/')) && (len = (slash - dest))) {
       tech = dest;
       dest = slash + 1;
       /* Allow execution only if the Tech/destination agrees with the type of the channel */
       if (strncasecmp(ast_channel_tech(chan)->type, tech, len)) {
          pbx_builtin_setvar_helper(chan, "TRANSFERSTATUS", "FAILURE");
          snprintf(status_protocol, sizeof(status_protocol), "%d", protocol);
          pbx_builtin_setvar_helper(chan, "TRANSFERSTATUSPROTOCOL", status_protocol);
          return 0;
       }
    }
    /* Check if the channel supports transfer before we try it */
    if (!ast_channel_tech(chan)->transfer) {
       pbx_builtin_setvar_helper(chan, "TRANSFERSTATUS", "UNSUPPORTED");
       snprintf(status_protocol, sizeof(status_protocol), "%d", protocol);
       pbx_builtin_setvar_helper(chan, "TRANSFERSTATUSPROTOCOL", status_protocol);
       return 0;
    }
    /* New transfer API returns a protocol code
       SIP example, 0 = success, 3xx-6xx are sip error codes for the REFER */
    res = ast_transfer_protocol(chan, dest, &protocol);
    if (res < 0) {
       status = "FAILURE";
       res = 0;
    } else {
       status = "SUCCESS";
       res = 0;
    }
    snprintf(status_protocol, sizeof(status_protocol), "%d", protocol);
    ast_debug(1, "ast_transfer channel %s TRANSFERSTATUS=%s, TRANSFERSTATUSPROTOCOL=%s\n",
         ast_channel_name(chan), status, status_protocol);
    pbx_builtin_setvar_helper(chan, "TRANSFERSTATUS", status);
    pbx_builtin_setvar_helper(chan, "TRANSFERSTATUSPROTOCOL", status_protocol);
    return res;
 }
unload_module()
static int unload_module (void) static
Definition at line 156 of file app_transfer.c.
References app, and ast_unregister_application().
 {
    return ast_unregister_application(app);
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Transfers a caller to another extension" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, } static
Definition at line 166 of file app_transfer.c.
app
const char* const app = "Transfer" static
Definition at line 85 of file app_transfer.c.
Referenced by load_module(), and unload_module().
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 166 of file app_transfer.c.