Asterisk - The Open Source Telephony Project: ast_sip_event_publisher_handler Struct Reference
ast_sip_event_publisher_handler Struct Reference
Callbacks that event publisher handlers will define.
#include <res_pjsip_outbound_publish.h>
Data Fields
const char * event_name
The name of the event this handler deals with.
struct {
struct ast_sip_event_publisher_handler * next
} next
int(* start_publishing)(struct ast_sip_outbound_publish *configuration, struct ast_sip_outbound_publish_client *client)
Called when a publisher should start publishing.
int(* stop_publishing)(struct ast_sip_outbound_publish_client *client)
Called when a publisher should stop publishing.
Detailed Description
Callbacks that event publisher handlers will define.
Definition at line 41 of file res_pjsip_outbound_publish.h.
Field Documentation
event_name
const char* event_name
The name of the event this handler deals with.
Definition at line 43 of file res_pjsip_outbound_publish.h.
Referenced by ast_sip_register_event_publisher_handler(), find_publisher_handler_for_event_name(), load_module(), and sip_outbound_publish_synchronize().
next [1/2]
struct { ... } next
next [2/2]
struct ast_sip_event_publisher_handler* next
Definition at line 66 of file res_pjsip_outbound_publish.h.
start_publishing
int(* start_publishing) (struct ast_sip_outbound_publish *configuration, struct ast_sip_outbound_publish_client *client)
Called when a publisher should start publishing.
Parameters
configuration The outbound publish configuration, event-specific configuration is accessible using extended sorcery fields
client The publish client that can be used to send PUBLISH messages.
Return values
0 success
-1 failure
Definition at line 54 of file res_pjsip_outbound_publish.h.
Referenced by ast_sip_register_event_publisher_handler(), and sip_outbound_publish_synchronize().
stop_publishing
int(* stop_publishing) (struct ast_sip_outbound_publish_client *client)
Called when a publisher should stop publishing.
Parameters
client The publish client that was used to send PUBLISH messages.
Return values
0 success
-1 failure
Definition at line 64 of file res_pjsip_outbound_publish.h.
Referenced by ast_sip_register_event_publisher_handler(), and stop_publishing().
The documentation for this struct was generated from the following file:
res_pjsip_outbound_publish.h