Asterisk - The Open Source Telephony Project: test_logger.c File Reference
test_logger.c File Reference
Test module for the logging subsystem.
#include "asterisk.h"
#include "asterisk/file.h"
#include "asterisk/channel.h"
#include "asterisk/pbx.h"
#include "asterisk/module.h"
#include "asterisk/lock.h"
#include "asterisk/app.h"
#include "asterisk/cli.h"
Data Structures
struct test
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static char * handle_cli_dynamic_level_test (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static char * handle_cli_performance_test (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static char * handle_cli_queue_test (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static int load_module (void)
static void output_tests (struct test *tests, size_t num_tests, int fd)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Logger Test Module" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, }
static const struct ast_module_info * ast_module_info = &__mod_info
static struct ast_cli_entry cli_logger []
Detailed Description
Test module for the logging subsystem.
Author
Kevin P. Fleming <kpfleming@digium.com>
Definition in file test_logger.c.
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 275 of file test_logger.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 275 of file test_logger.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 275 of file test_logger.c.
handle_cli_dynamic_level_test()
static char* handle_cli_dynamic_level_test (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) static
Definition at line 65 of file test_logger.c.
References ARRAY_LEN, ast_cli(), ast_log_dynamic_level, ast_logger_register_level(), ast_logger_unregister_level(), ast_strlen_zero, CLI_GENERATE, CLI_INIT, CLI_SUCCESS, ast_cli_entry::command, ast_cli_args::fd, test::name, NULL, output_tests(), test, test::u_failure, test::u_success, ast_cli_entry::usage, test::x_failure, and test::x_success.
 {
    unsigned int level;
    unsigned int x;
    unsigned int test;
    struct test tests[] = {
       { .name = "Simple register/message/unregister",
       },
       { .name = "Register multiple levels",
       },
    };
    switch (cmd) {
    case CLI_INIT:
       e->command = "logger test dynamic";
       e->usage = ""
          "Usage: logger test dynamic\n"
          "";
       return NULL;
    case CLI_GENERATE:
       return NULL;
    }
    for (test = 0; test < ARRAY_LEN(tests); test++) {
       ast_cli(a->fd, "Test %u: %s.\n", test + 1, tests[test].name);
       switch (test) {
       case 0:
          if ((level = ast_logger_register_level("test")) != -1) {
             ast_cli(a->fd, "Test: got level %u\n", level);
             ast_log_dynamic_level(level, "Logger Dynamic Test: Test 1\n");
             ast_logger_unregister_level("test");
             tests[test].x_success++;
          } else {
             ast_cli(a->fd, "Test: Failed, could not register level 'test'.\n");
             tests[test].u_failure++;
          }
          break;
       case 1:
       {
          char level_name[18][8];
          for (x = 0; x < ARRAY_LEN(level_name); x++) {
             sprintf(level_name[x], "level%02u", x);
             if ((level = ast_logger_register_level(level_name[x])) == -1) {
                if (x < 16) {
                   tests[test].u_failure++;
                } else {
                   tests[test].x_failure++;
                }
                level_name[x][0] = '\0';
             } else {
                ast_cli(a->fd, "Test: registered '%s', got level %u\n", level_name[x], level);
                if (x < 16) {
                   tests[test].x_success++;
                } else {
                   tests[test].u_success++;
                }
             }
          }
          for (x = 0; x < ARRAY_LEN(level_name); x++) {
             if (!ast_strlen_zero(level_name[x])) {
                ast_logger_unregister_level(level_name[x]);
             }
          }
       }
       }
    }
    output_tests(tests, ARRAY_LEN(tests), a->fd);
    return CLI_SUCCESS;
 }
handle_cli_performance_test()
static char* handle_cli_performance_test (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) static
Definition at line 139 of file test_logger.c.
References ARRAY_LEN, ast_cli(), ast_log_dynamic_level, ast_logger_register_level(), ast_logger_unregister_level(), ast_tvdiff_ms(), ast_tvnow(), CLI_GENERATE, CLI_INIT, CLI_SUCCESS, ast_cli_entry::command, ast_cli_args::fd, test::name, NULL, output_tests(), test, test::u_failure, ast_cli_entry::usage, and test::x_success.
 {
    unsigned int level;
    unsigned int test;
    struct test tests[] = {
       { .name = "Log 10,000 messages",
       },
    };
    switch (cmd) {
    case CLI_INIT:
       e->command = "logger test performance";
       e->usage = ""
          "Usage: logger test performance\n"
          "";
       return NULL;
    case CLI_GENERATE:
       return NULL;
    }
    for (test = 0; test < ARRAY_LEN(tests); test++) {
       ast_cli(a->fd, "Test %u: %s.\n", test + 1, tests[test].name);
       switch (test) {
       case 0:
          if ((level = ast_logger_register_level("perftest")) != -1) {
             unsigned int x;
             struct timeval start, end;
             int elapsed;
             ast_cli(a->fd, "Test: got level %u\n", level);
             start = ast_tvnow();
             for (x = 0; x < 10000; x++) {
                ast_log_dynamic_level(level, "Performance test log message\n");
             }
             end = ast_tvnow();
             elapsed = ast_tvdiff_ms(end, start);
             ast_cli(a->fd, "Test: 10,000 messages in %f seconds.\n", (float) elapsed / 1000);
             ast_logger_unregister_level("perftest");
             tests[test].x_success++;
          } else {
             ast_cli(a->fd, "Test: Failed, could not register level 'perftest'.\n");
             tests[test].u_failure++;
          }
          break;
       }
    }
    output_tests(tests, ARRAY_LEN(tests), a->fd);
    return CLI_SUCCESS;
 }
handle_cli_queue_test()
static char* handle_cli_queue_test (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) static
Definition at line 191 of file test_logger.c.
References ast_cli(), ast_log_dynamic_level, ast_logger_create_channel(), ast_logger_get_queue_limit(), ast_logger_register_level(), ast_logger_remove_channel(), ast_logger_set_queue_limit(), AST_LOGGER_SUCCESS, ast_logger_unregister_level(), ast_tvdiff_ms(), ast_tvnow(), CLI_GENERATE, CLI_INIT, CLI_SUCCESS, ast_cli_entry::command, error(), ast_cli_args::fd, NULL, and ast_cli_entry::usage.
 {
    int level;
    int current_queue_limit;
    unsigned int x;
    struct timeval start, end;
    int elapsed;
    char tmppath[] = "/tmp/asterisk_logger_queue.XXXXXX";
    int fd;
    switch (cmd) {
    case CLI_INIT:
       e->command = "logger test queue";
       e->usage = ""
          "Usage: logger test queue\n"
          "";
       return NULL;
    case CLI_GENERATE:
       return NULL;
    }
    fd = mkstemp(tmppath);
    if (fd < 0) {
       ast_cli(a->fd, "Test: Failed, could not create temporary log file '%s'.\n", tmppath);
       return CLI_SUCCESS;
    }
    level = ast_logger_register_level("queuetest");
    if (level < 0) {
       ast_cli(a->fd, "Test: Failed, could not register level 'queuetest'.\n");
       return CLI_SUCCESS;
    }
    ast_cli(a->fd, "Test: got level %d for 'queuetest'.\n", level);
    if (ast_logger_create_channel(tmppath, "queuetest") != AST_LOGGER_SUCCESS) {
       ast_cli(a->fd, "Test: Unable to create logger channel '%s'\n", tmppath);
       goto error;
    }
    current_queue_limit = ast_logger_get_queue_limit();
    ast_cli(a->fd, "Test: Current queue limit: %d.  Setting to 100 for test.\n", current_queue_limit);
    ast_logger_set_queue_limit(100);
    ast_cli(a->fd, "Test: You should see SOME 'exceeded' and 'resumed' messages after the test "
       "is completed.  How many is dependent on system resources.\n");
    start = ast_tvnow();
    for (x = 0; x < 10000; x++) {
       ast_log_dynamic_level(level, "Performance test log message %2d\n", x);
    }
    end = ast_tvnow();
    elapsed = ast_tvdiff_ms(end, start);
    ast_cli(a->fd, "Test: 10,000 messages in %f seconds.\n", (float) elapsed / 1000);
    ast_cli(a->fd, "Test: Completed.  Resetting queue limit to %d.\n", current_queue_limit);
    ast_logger_set_queue_limit(current_queue_limit);
 error:
    ast_logger_remove_channel(tmppath);
    ast_logger_unregister_level("queuetest");
    close(fd);
    unlink(tmppath);
    return CLI_SUCCESS;
 }
load_module()
static int load_module (void) static
Definition at line 269 of file test_logger.c.
References ARRAY_LEN, ast_cli_register_multiple, and AST_MODULE_LOAD_SUCCESS.
 {
    ast_cli_register_multiple(cli_logger, ARRAY_LEN(cli_logger));
    return AST_MODULE_LOAD_SUCCESS;
 }
output_tests()
static void output_tests (struct test * tests, size_t num_tests, int fd) static
Definition at line 51 of file test_logger.c.
References ast_cli(), test::name, test::u_failure, test::u_success, test::x_failure, and test::x_success.
Referenced by handle_cli_dynamic_level_test(), and handle_cli_performance_test().
 {
    unsigned int x;
    for (x = 0; x < num_tests; x++) {
       ast_cli(fd, "Test %u: %s\n", x + 1, tests[x].name);
       ast_cli(fd, "\tExpected Successes: %u\n", tests[x].x_success);
       ast_cli(fd, "\tExpected Failures: %u\n", tests[x].x_failure);
       ast_cli(fd, "\tUnexpected Successes: %u\n", tests[x].u_success);
       ast_cli(fd, "\tUnexpected Failures: %u\n", tests[x].u_failure);
       ast_cli(fd, "Test %u Result: %s\n", x + 1, (tests[x].u_success + tests[x].u_failure) ? "FAIL" : "PASS");
    }
 }
unload_module()
static int unload_module (void) static
Definition at line 263 of file test_logger.c.
References ARRAY_LEN, and ast_cli_unregister_multiple().
 {
    ast_cli_unregister_multiple(cli_logger, ARRAY_LEN(cli_logger));
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Logger Test Module" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, } static
Definition at line 275 of file test_logger.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 275 of file test_logger.c.
cli_logger
struct ast_cli_entry cli_logger[] static
Initial value:
= {
   { .handler =  handle_cli_dynamic_level_test , .summary =  "Test the dynamic logger level implementation" ,},
   { .handler =  handle_cli_performance_test , .summary =  "Test the logger performance" ,},
   { .handler =  handle_cli_queue_test , .summary =  "Test the logger queue" ,},
}
Definition at line 257 of file test_logger.c.