Asterisk - The Open Source Telephony Project: conf_chan_announce.c File Reference
conf_chan_announce.c File Reference
ConfBridge announcer channel driver.
#include "asterisk.h"
#include "asterisk/channel.h"
#include "asterisk/bridge.h"
#include "asterisk/core_unreal.h"
#include "include/confbridge.h"
Data Structures
struct announce_pvt
Functions
static int announce_call (struct ast_channel *chan, const char *addr, int timeout)
static int announce_hangup (struct ast_channel *ast)
static void announce_pvt_destructor (void *vdoomed)
static struct ast_channel * announce_request (const char *type, struct ast_format_cap *cap, const struct ast_assigned_ids *assignedids, const struct ast_channel *requestor, const char *data, int *cause)
int conf_announce_channel_push (struct ast_channel *ast)
Push the announcer channel into the conference.
struct ast_channel_tech * conf_announce_get_tech (void)
Get ConfBridge announce channel technology struct.
Variables
static struct ast_channel_tech announce_tech
Detailed Description
ConfBridge announcer channel driver.
Author
Richard Mudgett rmudg.nosp@m.ett@.nosp@m.digiu.nosp@m.m.co.nosp@m.m
See Also:
CREDITS
Definition in file conf_chan_announce.c.
Function Documentation
announce_call()
static int announce_call (struct ast_channel * chan, const char * addr, int timeout) static
Definition at line 47 of file conf_chan_announce.c.
 {
    /* Make sure anyone calling ast_call() for this channel driver is going to fail. */
    return -1;
 }
announce_hangup()
static int announce_hangup (struct ast_channel * ast) static
Definition at line 53 of file conf_chan_announce.c.
References ao2_ref, ast_channel_tech_pvt(), ast_unreal_hangup(), and announce_pvt::base.
 {
    struct announce_pvt *p = ast_channel_tech_pvt(ast);
    int res;
    if (!p) {
       return -1;
    }
    /* give the pvt a ref to fulfill calling requirements. */
    ao2_ref(p, +1);
    res = ast_unreal_hangup(&p->base, ast);
    ao2_ref(p, -1);
    return res;
 }
announce_pvt_destructor()
static void announce_pvt_destructor (void * vdoomed) static
Definition at line 70 of file conf_chan_announce.c.
References ao2_cleanup, ast_unreal_destructor(), announce_pvt::base, announce_pvt::bridge, and NULL.
Referenced by announce_request().
 {
    struct announce_pvt *doomed = vdoomed;
    ao2_cleanup(doomed->bridge);
    doomed->bridge = NULL;
    ast_unreal_destructor(&doomed->base);
 }
announce_request()
static struct ast_channel* announce_request (const char * type, struct ast_format_cap * cap, const struct ast_assigned_ids * assignedids, const struct ast_channel * requestor, const char * data, int * cause) static
Definition at line 79 of file conf_chan_announce.c.
References announce_pvt_destructor(), ao2_cleanup, ao2_find, ao2_ref, ast_answer(), ast_assert, ast_channel_add_bridge_role(), ast_copy_string(), ast_hangup(), ast_set_flag, AST_STATE_UP, ast_unreal_alloc(), ast_unreal_new_channels(), AST_UNREAL_NO_OPTIMIZATION, conf_announce_get_tech(), conference_bridges, ast_channel::data, NULL, OBJ_KEY, and RAII_VAR.
 {
    struct ast_channel *chan;
    const char *conf_name = data;
    RAII_VAR(struct confbridge_conference *, conference, NULL, ao2_cleanup);
    RAII_VAR(struct announce_pvt *, pvt, NULL, ao2_cleanup);
    conference = ao2_find(conference_bridges, conf_name, OBJ_KEY);
    if (!conference) {
       return NULL;
    }
    ast_assert(conference->bridge != NULL);
    /* Allocate a new private structure and then Asterisk channels */
    pvt = (struct announce_pvt *) ast_unreal_alloc(sizeof(*pvt), announce_pvt_destructor,
       cap);
    if (!pvt) {
       return NULL;
    }
    ast_set_flag(&pvt->base, AST_UNREAL_NO_OPTIMIZATION);
    ast_copy_string(pvt->base.name, conf_name, sizeof(pvt->base.name));
    pvt->bridge = conference->bridge;
    ao2_ref(pvt->bridge, +1);
    chan = ast_unreal_new_channels(&pvt->base, conf_announce_get_tech(),
       AST_STATE_UP, AST_STATE_UP, NULL, NULL, assignedids, requestor, 0);
    if (chan) {
       ast_answer(pvt->base.owner);
       ast_answer(pvt->base.chan);
       if (ast_channel_add_bridge_role(pvt->base.chan, "announcer")) {
          ast_hangup(chan);
          chan = NULL;
       }
    }
    return chan;
 }
conf_announce_channel_push()
int conf_announce_channel_push (struct ast_channel * ast)
Push the announcer channel into the conference.
Since
12.0.0
Parameters
ast Either channel in the announcer channel pair.
Return values
0 on success.
-1 on error.
Definition at line 144 of file conf_chan_announce.c.
References ao2_cleanup, ao2_lock, ao2_ref, ao2_unlock, AST_BRIDGE_CHANNEL_FLAG_IMMOVABLE, ast_bridge_features_new(), ast_bridge_impart(), AST_BRIDGE_IMPART_CHAN_INDEPENDENT, ast_channel_tech_pvt(), ast_set_flag, AST_UNREAL_CARETAKER_THREAD, ast_bridge_features::feature_flags, lock, NULL, RAII_VAR, and SCOPED_CHANNELLOCK.
Referenced by push_announcer().
 {
    struct ast_bridge_features *features;
    struct ast_channel *chan;
    RAII_VAR(struct announce_pvt *, p, NULL, ao2_cleanup);
    {
       SCOPED_CHANNELLOCK(lock, ast);
       p = ast_channel_tech_pvt(ast);
       if (!p) {
          return -1;
       }
       ao2_ref(p, +1);
       chan = p->base.chan;
       if (!chan) {
          return -1;
       }
    }
    features = ast_bridge_features_new();
    if (!features) {
       return -1;
    }
    ast_set_flag(&features->feature_flags, AST_BRIDGE_CHANNEL_FLAG_IMMOVABLE);
    /* Impart the output channel into the bridge */
    if (ast_bridge_impart(p->bridge, chan, NULL, features,
       AST_BRIDGE_IMPART_CHAN_INDEPENDENT)) {
       return -1;
    }
    ao2_lock(p);
    ast_set_flag(&p->base, AST_UNREAL_CARETAKER_THREAD);
    ao2_unlock(p);
    return 0;
 }
conf_announce_get_tech()
struct ast_channel_tech* conf_announce_get_tech (void)
Get ConfBridge announce channel technology struct.
Since
12.0.0
Returns
ConfBridge announce channel technology.
Definition at line 139 of file conf_chan_announce.c.
References announce_tech.
Referenced by announce_request(), load_module(), and unload_module().
 {
    return &announce_tech;
 }
Variable Documentation
announce_tech
struct ast_channel_tech announce_tech static
Definition at line 117 of file conf_chan_announce.c.
Referenced by conf_announce_get_tech().