Asterisk - The Open Source Telephony Project: res_monitor.c File Reference
res_monitor.c File Reference
PBX channel monitoring.
#include "asterisk.h"
#include <sys/stat.h>
#include <libgen.h>
#include "asterisk/paths.h"
#include "asterisk/lock.h"
#include "asterisk/channel.h"
#include "asterisk/file.h"
#include "asterisk/pbx.h"
#include "asterisk/module.h"
#include "asterisk/cli.h"
#include "asterisk/manager.h"
#include "asterisk/stasis.h"
#include "asterisk/stasis_channels.h"
#include "asterisk/monitor.h"
#include "asterisk/app.h"
#include "asterisk/utils.h"
#include "asterisk/config.h"
#include "asterisk/options.h"
#include "asterisk/beep.h"
Macros
#define AST_API_MODULE
#define LOCK_IF_NEEDED(lock, needed)
#define UNLOCK_IF_NEEDED(lock, needed)
Enumerations
enum {
MON_FLAG_BRIDGED = (1 << 0), MON_FLAG_MIX = (1 << 1), MON_FLAG_DROP_IN = (1 << 2), MON_FLAG_DROP_OUT = (1 << 3),
MON_FLAG_BEEP = (1 << 4)
}
enum { OPT_ARG_BEEP_INTERVAL, OPT_ARG_ARRAY_SIZE }
enum MONITOR_PAUSING_ACTION { MONITOR_ACTION_PAUSE, MONITOR_ACTION_UNPAUSE }
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
int AST_OPTIONAL_API_NAME() ast_monitor_change_fname (struct ast_channel *chan, const char *fname_base, int need_lock)
Change monitored filename of channel.
int AST_OPTIONAL_API_NAME() ast_monitor_pause (struct ast_channel *chan)
Pause monitoring of channel.
static int ast_monitor_set_state (struct ast_channel *chan, int state)
Change state of monitored channel.
void AST_OPTIONAL_API_NAME() ast_monitor_setjoinfiles (struct ast_channel *chan, int turnon)
int AST_OPTIONAL_API_NAME() ast_monitor_start (struct ast_channel *chan, const char *format_spec, const char *fname_base, int need_lock, int stream_action, const char *beep_id)
Start monitoring a channel.
int AST_OPTIONAL_API_NAME() ast_monitor_stop (struct ast_channel *chan, int need_lock)
Stop monitoring channel.
int AST_OPTIONAL_API_NAME() ast_monitor_unpause (struct ast_channel *chan)
Unpause monitoring of channel.
static int change_monitor_action (struct mansession *s, const struct message *m)
Change filename of a monitored channel by manager connection.
static int change_monitor_exec (struct ast_channel *chan, const char *data)
Wrapper function.
static int do_pause_or_unpause (struct mansession *s, const struct message *m, int action)
static const char * get_soxmix_format (const char *format)
Get audio format.
static int load_module (void)
static int pause_monitor_action (struct mansession *s, const struct message *m)
static int pause_monitor_exec (struct ast_channel *chan, const char *data)
Wrapper for ast_monitor_pause.
static int start_monitor_action (struct mansession *s, const struct message *m)
Start monitoring a channel by manager connection.
static int start_monitor_exec (struct ast_channel *chan, const char *data)
Start monitor.
static int stop_monitor_action (struct mansession *s, const struct message *m)
Stop monitoring a channel by manager connection.
static int stop_monitor_exec (struct ast_channel *chan, const char *data)
Wrapper function.
static int unload_module (void)
static int unpause_monitor_action (struct mansession *s, const struct message *m)
static int unpause_monitor_exec (struct ast_channel *chan, const char *data)
Wrapper for ast_monitor_unpause.
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_GLOBAL_SYMBOLS | AST_MODFLAG_LOAD_ORDER , .description = "Call Monitoring Resource" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_DEPRECATED, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_CHANNEL_DEPEND, .optional_modules = "func_periodic_hook", }
static const struct ast_module_info * ast_module_info = &__mod_info
static const struct ast_app_option monitor_opts [128] = { [ 'b' ] = { .flag = MON_FLAG_BRIDGED }, [ 'm' ] = { .flag = MON_FLAG_MIX }, [ 'i' ] = { .flag = MON_FLAG_DROP_IN }, [ 'o' ] = { .flag = MON_FLAG_DROP_OUT }, [ 'B' ] = { .flag = MON_FLAG_BEEP , .arg_index = OPT_ARG_BEEP_INTERVAL + 1 }, }
static ast_mutex_t monitorlock = { PTHREAD_RECURSIVE_MUTEX_INITIALIZER_NP , NULL, {1, 0} }
static unsigned long seq = 0
Detailed Description
PBX channel monitoring.
Author
Mark Spencer marks.nosp@m.ter@.nosp@m.digiu.nosp@m.m.co.nosp@m.m
Definition in file res_monitor.c.
Macro Definition Documentation
AST_API_MODULE
#define AST_API_MODULE
Definition at line 47 of file res_monitor.c.
LOCK_IF_NEEDED
#define LOCK_IF_NEEDED (lock, needed)
Value:
do { \
   if (needed) \
      ast_channel_lock(lock); \
   } while(0)
Definition at line 263 of file res_monitor.c.
Referenced by ast_monitor_change_fname(), ast_monitor_set_state(), ast_monitor_start(), and ast_monitor_stop().
UNLOCK_IF_NEEDED
#define UNLOCK_IF_NEEDED (lock, needed)
Value:
do { \
   if (needed) \
      ast_channel_unlock(lock); \
   } while (0)
Definition at line 268 of file res_monitor.c.
Referenced by ast_monitor_change_fname(), ast_monitor_set_state(), ast_monitor_start(), and ast_monitor_stop().
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
MON_FLAG_BRIDGED
MON_FLAG_MIX
MON_FLAG_DROP_IN
MON_FLAG_DROP_OUT
MON_FLAG_BEEP
Definition at line 665 of file res_monitor.c.
      {
    MON_FLAG_BRIDGED =  (1 << 0),
    MON_FLAG_MIX =      (1 << 1),
    MON_FLAG_DROP_IN =  (1 << 2),
    MON_FLAG_DROP_OUT = (1 << 3),
    MON_FLAG_BEEP =     (1 << 4),
 };
anonymous enum
anonymous enum
Enumerator
OPT_ARG_BEEP_INTERVAL
OPT_ARG_ARRAY_SIZE
Definition at line 673 of file res_monitor.c.
      {
    OPT_ARG_BEEP_INTERVAL,
    OPT_ARG_ARRAY_SIZE,  /* Always last element of the enum */
 };
MONITOR_PAUSING_ACTION
enum MONITOR_PAUSING_ACTION
Enumerator
MONITOR_ACTION_PAUSE
MONITOR_ACTION_UNPAUSE
Definition at line 932 of file res_monitor.c.
 {
    MONITOR_ACTION_PAUSE,
    MONITOR_ACTION_UNPAUSE
 };
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 1015 of file res_monitor.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 1015 of file res_monitor.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 1015 of file res_monitor.c.
ast_monitor_change_fname()
int AST_OPTIONAL_API_NAME() ast_monitor_change_fname (struct ast_channel * chan, const char * fname_base, int need_lock)
Change monitored filename of channel.
Parameters
chan
fname_base new filename
need_lock
Return values
0 on success.
-1 on failure.
Note
We cannot just compare filenames, due to symlinks, relative paths, and other possible filesystem issues. We could use realpath(3), but its use is discouraged. However, if we try to create the same file from two different paths, the second will fail, and so we have our notification that the filenames point to the same path.
Remember, also, that we're using the basename of the file (i.e. the file without the format suffix), so it does not already exist and we aren't interfering with the recording itself.
Definition at line 590 of file res_monitor.c.
References ast_channel_monitor(), ast_channel_name(), ast_config_AST_MONITOR_DIR, ast_copy_string(), ast_debug, ast_log, ast_mkdir(), ast_strdupa, ast_strlen_zero, doexit, errno, ast_channel_monitor::filename_base, ast_channel_monitor::filename_changed, LOCK_IF_NEEDED, LOG_ERROR, LOG_WARNING, name, and UNLOCK_IF_NEEDED.
Referenced by __stub__ast_monitor_stop(), change_monitor_action(), change_monitor_exec(), start_monitor_action(), and start_monitor_exec().
 {
    if (ast_strlen_zero(fname_base)) {
       ast_log(LOG_WARNING, "Cannot change monitor filename of channel %s to null\n", ast_channel_name(chan));
       return -1;
    }
    LOCK_IF_NEEDED(chan, need_lock);
    if (ast_channel_monitor(chan)) {
       int directory = strchr(fname_base, '/') ? 1 : 0;
       const char *absolute = *fname_base == '/' ? "" : ast_config_AST_MONITOR_DIR;
       const char *absolute_suffix = *fname_base == '/' ? "" : "/";
       char tmpstring[sizeof(ast_channel_monitor(chan)->filename_base)] = "";
       int i, fd[2] = { -1, -1 }, doexit = 0;
       /* before continuing, see if we're trying to rename the file to itself... */
       snprintf(tmpstring, sizeof(tmpstring), "%s%s%s", absolute, absolute_suffix, fname_base);
       /* try creating the directory just in case it doesn't exist */
       if (directory) {
          char *name = ast_strdupa(tmpstring);
          ast_mkdir(dirname(name), 0777);
       }
       /*!
        * \note We cannot just compare filenames, due to symlinks, relative
        * paths, and other possible filesystem issues.  We could use
        * realpath(3), but its use is discouraged.  However, if we try to
        * create the same file from two different paths, the second will
        * fail, and so we have our notification that the filenames point to
        * the same path.
        *
        * Remember, also, that we're using the basename of the file (i.e.
        * the file without the format suffix), so it does not already exist
        * and we aren't interfering with the recording itself.
        */
       ast_debug(2, "comparing tmpstring %s to filename_base %s\n", tmpstring, ast_channel_monitor(chan)->filename_base);
       if ((fd[0] = open(tmpstring, O_CREAT | O_WRONLY, 0644)) < 0 ||
          (fd[1] = open(ast_channel_monitor(chan)->filename_base, O_CREAT | O_EXCL | O_WRONLY, 0644)) < 0) {
          if (fd[0] < 0) {
             ast_log(LOG_ERROR, "Unable to compare filenames: %s\n", strerror(errno));
          } else {
             ast_debug(2, "No need to rename monitor filename to itself\n");
          }
          doexit = 1;
       }
       /* Cleanup temporary files */
       for (i = 0; i < 2; i++) {
          if (fd[i] >= 0) {
             while (close(fd[i]) < 0 && errno == EINTR);
          }
       }
       unlink(tmpstring);
       /* if previous monitor file existed in a subdirectory, the directory will not be removed */
       unlink(ast_channel_monitor(chan)->filename_base);
       if (doexit) {
          UNLOCK_IF_NEEDED(chan, need_lock);
          return 0;
       }
       ast_copy_string(ast_channel_monitor(chan)->filename_base, tmpstring, sizeof(ast_channel_monitor(chan)->filename_base));
       ast_channel_monitor(chan)->filename_changed = 1;
    } else {
       ast_log(LOG_WARNING, "Cannot change monitor filename of channel %s to %s, monitoring not started\n", ast_channel_name(chan), fname_base);
    }
    UNLOCK_IF_NEEDED(chan, need_lock);
    return 0;
 }
ast_monitor_pause()
int AST_OPTIONAL_API_NAME() ast_monitor_pause (struct ast_channel * chan)
Pause monitoring of channel.
Definition at line 559 of file res_monitor.c.
References AST_MONITOR_PAUSED, and ast_monitor_set_state().
Referenced by __stub__ast_monitor_setjoinfiles(), do_pause_or_unpause(), and pause_monitor_exec().
 {
    return ast_monitor_set_state(chan, AST_MONITOR_PAUSED);
 }
ast_monitor_set_state()
static int ast_monitor_set_state (struct ast_channel * chan, int state) static
Change state of monitored channel.
Parameters
chan
state monitor state
Return values
0 on success.
-1 on failure.
Definition at line 282 of file res_monitor.c.
References ast_channel_monitor(), LOCK_IF_NEEDED, state, ast_channel_monitor::state, and UNLOCK_IF_NEEDED.
Referenced by ast_monitor_pause(), ast_monitor_start(), and ast_monitor_unpause().
 {
    LOCK_IF_NEEDED(chan, 1);
    if (!ast_channel_monitor(chan)) {
       UNLOCK_IF_NEEDED(chan, 1);
       return -1;
    }
    ast_channel_monitor(chan)->state = state;
    UNLOCK_IF_NEEDED(chan, 1);
    return 0;
 }
ast_monitor_setjoinfiles()
void AST_OPTIONAL_API_NAME() ast_monitor_setjoinfiles (struct ast_channel * chan, int turnon)
Definition at line 926 of file res_monitor.c.
References ast_channel_monitor(), and ast_channel_monitor::joinfiles.
Referenced by __stub__ast_monitor_change_fname(), start_automonitor(), start_monitor_action(), start_monitor_exec(), and try_calling().
 {
    if (ast_channel_monitor(chan))
       ast_channel_monitor(chan)->joinfiles = turnon;
 }
ast_monitor_start()
int AST_OPTIONAL_API_NAME() ast_monitor_start (struct ast_channel * chan, const char * format_spec, const char * fname_base, int need_lock, int stream_action, const char * beep_id)
Start monitoring a channel.
Parameters
chan ast_channel struct to record
format_spec file format to use for recording
fname_base filename base to record to
need_lock whether to lock the channel mutex
stream_action whether to record the input and/or output streams. X_REC_IN | X_REC_OUT is most often used Creates the file to record, if no format is specified it assumes WAV It also sets channel variable __MONITORED=yes
Return values
0 on success
-1 on failure
Definition at line 305 of file res_monitor.c.
References ao2_cleanup, ast_calloc, ast_channel_blob_create_from_cache(), ast_channel_insmpl_set(), ast_channel_monitor(), ast_channel_monitor_set(), ast_channel_monitor_start_type(), ast_channel_name(), ast_channel_outsmpl_set(), ast_channel_topic(), ast_channel_uniqueid(), ast_closestream(), ast_config_AST_MONITOR_DIR, ast_copy_string(), ast_debug, AST_FILE_MODE, ast_filedelete(), ast_fileexists(), ast_free, ast_log, ast_mkdir(), AST_MONITOR_RUNNING, ast_monitor_set_state(), ast_monitor_stop(), ast_mutex_lock, ast_mutex_unlock, ast_strdup, ast_strdupa, ast_strlen_zero, ast_writefile(), ast_channel_monitor::beep_id, ast_channel_monitor::filename_base, ast_channel_monitor::filename_changed, FILENAME_MAX, ast_channel_monitor::format, LOCK_IF_NEEDED, LOG_WARNING, monitor, monitorlock, name, NULL, pbx_builtin_setvar_helper(), RAII_VAR, ast_channel_monitor::read_filename, ast_channel_monitor::read_stream, seq, stasis_publish(), ast_channel_monitor::stop, UNLOCK_IF_NEEDED, ast_channel_monitor::write_filename, ast_channel_monitor::write_stream, X_REC_IN, and X_REC_OUT.
Referenced by start_automonitor(), start_monitor_action(), start_monitor_exec(), and try_calling().
 {
    int res = 0;
    RAII_VAR(struct stasis_message *, message, NULL, ao2_cleanup);
    LOCK_IF_NEEDED(chan, need_lock);
    if (!(ast_channel_monitor(chan))) {
       struct ast_channel_monitor *monitor;
       char *channel_name, *p;
       /* Create monitoring directory if needed */
       ast_mkdir(ast_config_AST_MONITOR_DIR, 0777);
       if (!(monitor = ast_calloc(1, sizeof(*monitor)))) {
          UNLOCK_IF_NEEDED(chan, need_lock);
          return -1;
       }
       if (!ast_strlen_zero(beep_id)) {
          ast_copy_string(monitor->beep_id, beep_id, sizeof(monitor->beep_id));
       }
       /* Determine file names */
       if (!ast_strlen_zero(fname_base)) {
          int directory = strchr(fname_base, '/') ? 1 : 0;
          const char *absolute = *fname_base == '/' ? "" : ast_config_AST_MONITOR_DIR;
          const char *absolute_suffix = *fname_base == '/' ? "" : "/";
          snprintf(monitor->read_filename, FILENAME_MAX, "%s%s%s-in",
                   absolute, absolute_suffix, fname_base);
          snprintf(monitor->write_filename, FILENAME_MAX, "%s%s%s-out",
                   absolute, absolute_suffix, fname_base);
          snprintf(monitor->filename_base, FILENAME_MAX, "%s%s%s",
                   absolute, absolute_suffix, fname_base);
          /* try creating the directory just in case it doesn't exist */
          if (directory) {
             char *name = ast_strdupa(monitor->filename_base);
             ast_mkdir(dirname(name), 0777);
          }
       } else {
          ast_mutex_lock(&monitorlock);
          snprintf(monitor->read_filename, FILENAME_MAX, "%s/audio-in-%lu",
                   ast_config_AST_MONITOR_DIR, seq);
          snprintf(monitor->write_filename, FILENAME_MAX, "%s/audio-out-%lu",
                   ast_config_AST_MONITOR_DIR, seq);
          seq++;
          ast_mutex_unlock(&monitorlock);
          /* Replace all '/' chars from the channel name with '-' chars. */
          channel_name = ast_strdupa(ast_channel_name(chan));
          for (p = channel_name; (p = strchr(p, '/')); ) {
             *p = '-';
          }
          snprintf(monitor->filename_base, FILENAME_MAX, "%s/%d-%s",
                 ast_config_AST_MONITOR_DIR, (int)time(NULL), channel_name);
          monitor->filename_changed = 1;
       }
       monitor->stop = ast_monitor_stop;
       /* Determine file format */
       if (!ast_strlen_zero(format_spec)) {
          monitor->format = ast_strdup(format_spec);
       } else {
          monitor->format = ast_strdup("wav");
       }
       /* open files */
       if (stream_action & X_REC_IN) {
          if (ast_fileexists(monitor->read_filename, NULL, NULL) > 0)
             ast_filedelete(monitor->read_filename, NULL);
          if (!(monitor->read_stream = ast_writefile(monitor->read_filename,
                      monitor->format, NULL,
                      O_CREAT|O_TRUNC|O_WRONLY, 0, AST_FILE_MODE))) {
             ast_log(LOG_WARNING, "Could not create file %s\n",
                      monitor->read_filename);
             ast_free(monitor);
             UNLOCK_IF_NEEDED(chan, need_lock);
             return -1;
          }
       } else
          monitor->read_stream = NULL;
       if (stream_action & X_REC_OUT) {
          if (ast_fileexists(monitor->write_filename, NULL, NULL) > 0) {
             ast_filedelete(monitor->write_filename, NULL);
          }
          if (!(monitor->write_stream = ast_writefile(monitor->write_filename,
                      monitor->format, NULL,
                      O_CREAT|O_TRUNC|O_WRONLY, 0, AST_FILE_MODE))) {
             ast_log(LOG_WARNING, "Could not create file %s\n",
                      monitor->write_filename);
             if (monitor->read_stream) {
                ast_closestream(monitor->read_stream);
             }
             ast_free(monitor);
             UNLOCK_IF_NEEDED(chan, need_lock);
             return -1;
          }
       } else
          monitor->write_stream = NULL;
       ast_channel_insmpl_set(chan, 0);
       ast_channel_outsmpl_set(chan, 0);
       ast_channel_monitor_set(chan, monitor);
       ast_monitor_set_state(chan, AST_MONITOR_RUNNING);
       /* so we know this call has been monitored in case we need to bill for it or something */
       pbx_builtin_setvar_helper(chan, "__MONITORED","true");
       message = ast_channel_blob_create_from_cache(ast_channel_uniqueid(chan),
             ast_channel_monitor_start_type(),
             NULL);
       if (message) {
          stasis_publish(ast_channel_topic(chan), message);
       }
    } else {
       ast_debug(1,"Cannot start monitoring %s, already monitored\n", ast_channel_name(chan));
       res = -1;
    }
    UNLOCK_IF_NEEDED(chan, need_lock);
    return res;
 }
ast_monitor_stop()
int AST_OPTIONAL_API_NAME() ast_monitor_stop (struct ast_channel * chan, int need_lock)
Stop monitoring channel.
Parameters
chan
need_lock Stop the recording, close any open streams, mix in/out channels if required
Returns
Always 0
Definition at line 461 of file res_monitor.c.
References ao2_cleanup, ast_beep_stop(), ast_channel_blob_create_from_cache(), ast_channel_monitor(), ast_channel_monitor_set(), ast_channel_monitor_stop_type(), ast_channel_topic(), ast_channel_uniqueid(), ast_closestream(), ast_debug, ast_filedelete(), ast_fileexists(), ast_filerename(), ast_free, ast_log, ast_safe_system(), ast_str_append(), ast_str_buffer(), ast_str_create, ast_str_set(), ast_strlen_zero, execute(), ast_channel_monitor::filename_base, format, ast_channel_monitor::format, get_soxmix_format(), LOCK_IF_NEEDED, LOG_WARNING, NULL, pbx_builtin_getvar_helper(), pbx_builtin_setvar_helper(), RAII_VAR, stasis_publish(), tmp(), UNLOCK_IF_NEEDED, and write_stream().
Referenced by __stub__ast_monitor_start(), ast_monitor_start(), stop_monitor_action(), and stop_monitor_exec().
 {
    int delfiles = 0;
    RAII_VAR(struct stasis_message *, message, NULL, ao2_cleanup);
    LOCK_IF_NEEDED(chan, need_lock);
    if (ast_channel_monitor(chan)) {
       RAII_VAR(struct ast_str *, tmp, ast_str_create(1024), ast_free);
       if (ast_channel_monitor(chan)->read_stream) {
          ast_closestream(ast_channel_monitor(chan)->read_stream);
       }
       if (ast_channel_monitor(chan)->write_stream) {
          ast_closestream(ast_channel_monitor(chan)->write_stream);
       }
       if (tmp && ast_channel_monitor(chan)->filename_changed && !ast_strlen_zero(ast_channel_monitor(chan)->filename_base)) {
          if (ast_fileexists(ast_channel_monitor(chan)->read_filename,NULL,NULL) > 0) {
             ast_str_set(&tmp, 0, "%s-in", ast_channel_monitor(chan)->filename_base);
             if (ast_fileexists(ast_str_buffer(tmp), NULL, NULL) > 0) {
                ast_filedelete(ast_str_buffer(tmp), NULL);
             }
             ast_filerename(ast_channel_monitor(chan)->read_filename, ast_str_buffer(tmp), ast_channel_monitor(chan)->format);
          } else {
             ast_log(LOG_WARNING, "File %s not found\n", ast_channel_monitor(chan)->read_filename);
          }
          if (tmp && ast_fileexists(ast_channel_monitor(chan)->write_filename,NULL,NULL) > 0) {
             ast_str_set(&tmp, 0, "%s-out", ast_channel_monitor(chan)->filename_base);
             if (ast_fileexists(ast_str_buffer(tmp), NULL, NULL) > 0) {
                ast_filedelete(ast_str_buffer(tmp), NULL);
             }
             ast_filerename(ast_channel_monitor(chan)->write_filename, ast_str_buffer(tmp), ast_channel_monitor(chan)->format);
          } else {
             ast_log(LOG_WARNING, "File %s not found\n", ast_channel_monitor(chan)->write_filename);
          }
       }
       if (tmp && ast_channel_monitor(chan)->joinfiles && !ast_strlen_zero(ast_channel_monitor(chan)->filename_base)) {
          const char *format = !strcasecmp(ast_channel_monitor(chan)->format,"wav49") ? "WAV" : ast_channel_monitor(chan)->format;
          char *fname_base = ast_channel_monitor(chan)->filename_base;
          const char *execute, *execute_args;
          /* at this point, fname_base really is the full path */
          /* Set the execute application */
          execute = pbx_builtin_getvar_helper(chan, "MONITOR_EXEC");
          if (ast_strlen_zero(execute)) {
 #ifdef HAVE_SOXMIX
             execute = "nice -n 19 soxmix";
 #else
             execute = "nice -n 19 sox -m";
 #endif
             format = get_soxmix_format(format);
             delfiles = 1;
          }
          execute_args = pbx_builtin_getvar_helper(chan, "MONITOR_EXEC_ARGS");
          if (ast_strlen_zero(execute_args)) {
             execute_args = "";
          }
          ast_str_set(&tmp, 0, delfiles ? "( " : "");
          ast_str_append(&tmp, 0, "%s \"%s-in.%s\" \"%s-out.%s\" \"%s.%s\" %s &",
             execute, fname_base, format, fname_base, format, fname_base, format,execute_args);
          if (delfiles) {
             /* remove legs when done mixing */
             ast_str_append(&tmp, 0, "& rm -f \"%s-\"* ) &", fname_base);
          }
          ast_debug(1,"monitor executing %s\n", ast_str_buffer(tmp));
          if (ast_safe_system(ast_str_buffer(tmp)) == -1)
             ast_log(LOG_WARNING, "Execute of %s failed.\n", ast_str_buffer(tmp));
       }
       if (!ast_strlen_zero(ast_channel_monitor(chan)->beep_id)) {
          ast_beep_stop(chan, ast_channel_monitor(chan)->beep_id);
       }
       ast_free(ast_channel_monitor(chan)->format);
       ast_free(ast_channel_monitor(chan));
       ast_channel_monitor_set(chan, NULL);
       message = ast_channel_blob_create_from_cache(ast_channel_uniqueid(chan),
             ast_channel_monitor_stop_type(),
             NULL);
       if (message) {
          stasis_publish(ast_channel_topic(chan), message);
       }
       pbx_builtin_setvar_helper(chan, "MONITORED", NULL);
    }
    pbx_builtin_setvar_helper(chan, "AUTO_MONITOR", NULL);
    UNLOCK_IF_NEEDED(chan, need_lock);
    return 0;
 }
ast_monitor_unpause()
int AST_OPTIONAL_API_NAME() ast_monitor_unpause (struct ast_channel * chan)
Unpause monitoring of channel.
Definition at line 565 of file res_monitor.c.
References AST_MONITOR_RUNNING, and ast_monitor_set_state().
Referenced by __stub__ast_monitor_pause(), do_pause_or_unpause(), and unpause_monitor_exec().
 {
    return ast_monitor_set_state(chan, AST_MONITOR_RUNNING);
 }
change_monitor_action()
static int change_monitor_action (struct mansession * s, const struct message * m) static
Change filename of a monitored channel by manager connection.
Definition at line 892 of file res_monitor.c.
References AMI_SUCCESS, ast_channel_get_by_name(), ast_channel_unref, ast_monitor_change_fname(), ast_strlen_zero, astman_get_header(), astman_send_ack(), astman_send_error(), c, name, and NULL.
Referenced by load_module().
 {
    struct ast_channel *c = NULL;
    const char *name = astman_get_header(m, "Channel");
    const char *fname = astman_get_header(m, "File");
    if (ast_strlen_zero(name)) {
       astman_send_error(s, m, "No channel specified");
       return AMI_SUCCESS;
    }
    if (ast_strlen_zero(fname)) {
       astman_send_error(s, m, "No filename specified");
       return AMI_SUCCESS;
    }
    if (!(c = ast_channel_get_by_name(name))) {
       astman_send_error(s, m, "No such channel");
       return AMI_SUCCESS;
    }
    if (ast_monitor_change_fname(c, fname, 1)) {
       c = ast_channel_unref(c);
       astman_send_error(s, m, "Could not change monitored filename of channel");
       return AMI_SUCCESS;
    }
    c = ast_channel_unref(c);
    astman_send_ack(s, m, "Changed monitor filename");
    return AMI_SUCCESS;
 }
change_monitor_exec()
static int change_monitor_exec (struct ast_channel * chan, const char * data) static
Wrapper function.
See also
ast_monitor_change_fname
Definition at line 802 of file res_monitor.c.
References ast_monitor_change_fname().
Referenced by load_module().
 {
    return ast_monitor_change_fname(chan, data, 1);
 }
do_pause_or_unpause()
static int do_pause_or_unpause (struct mansession * s, const struct message * m, int action) static
Definition at line 938 of file res_monitor.c.
References AMI_SUCCESS, ast_channel_get_by_name(), ast_channel_unref, ast_monitor_pause(), ast_monitor_unpause(), ast_strlen_zero, astman_get_header(), astman_send_ack(), astman_send_error(), c, MONITOR_ACTION_PAUSE, name, and NULL.
Referenced by pause_monitor_action(), and unpause_monitor_action().
 {
    struct ast_channel *c = NULL;
    const char *name = astman_get_header(m, "Channel");
    if (ast_strlen_zero(name)) {
       astman_send_error(s, m, "No channel specified");
       return AMI_SUCCESS;
    }
    if (!(c = ast_channel_get_by_name(name))) {
       astman_send_error(s, m, "No such channel");
       return AMI_SUCCESS;
    }
    if (action == MONITOR_ACTION_PAUSE) {
       ast_monitor_pause(c);
    } else {
       ast_monitor_unpause(c);
    }
    c = ast_channel_unref(c);
    astman_send_ack(s, m, (action == MONITOR_ACTION_PAUSE ? "Paused monitoring of the channel" : "Unpaused monitoring of the channel"));
    return AMI_SUCCESS;
 }
get_soxmix_format()
static const char* get_soxmix_format (const char * format) static
Get audio format.
Parameters
format recording format. The file format extensions that Asterisk uses are not all the same as that which soxmix expects. This function ensures that the format used as the extension on the filename is something soxmix will understand.
Definition at line 442 of file res_monitor.c.
References format.
Referenced by ast_monitor_stop().
 {
    const char *res = format;
    if (!strcasecmp(format,"ulaw"))
       res = "ul";
    if (!strcasecmp(format,"alaw"))
       res = "al";
    return res;
 }
load_module()
static int load_module (void) static
Definition at line 976 of file res_monitor.c.
References ast_manager_register_xml, AST_MODULE_LOAD_SUCCESS, ast_register_application_xml, change_monitor_action(), change_monitor_exec(), EVENT_FLAG_CALL, pause_monitor_action(), pause_monitor_exec(), start_monitor_action(), start_monitor_exec(), stop_monitor_action(), stop_monitor_exec(), unpause_monitor_action(), and unpause_monitor_exec().
Referenced by unload_module().
 {
    ast_register_application_xml("Monitor", start_monitor_exec);
    ast_register_application_xml("StopMonitor", stop_monitor_exec);
    ast_register_application_xml("ChangeMonitor", change_monitor_exec);
    ast_register_application_xml("PauseMonitor", pause_monitor_exec);
    ast_register_application_xml("UnpauseMonitor", unpause_monitor_exec);
    ast_manager_register_xml("Monitor", EVENT_FLAG_CALL, start_monitor_action);
    ast_manager_register_xml("StopMonitor", EVENT_FLAG_CALL, stop_monitor_action);
    ast_manager_register_xml("ChangeMonitor", EVENT_FLAG_CALL, change_monitor_action);
    ast_manager_register_xml("PauseMonitor", EVENT_FLAG_CALL, pause_monitor_action);
    ast_manager_register_xml("UnpauseMonitor", EVENT_FLAG_CALL, unpause_monitor_action);
    return AST_MODULE_LOAD_SUCCESS;
 }
pause_monitor_action()
static int pause_monitor_action (struct mansession * s, const struct message * m) static
Definition at line 966 of file res_monitor.c.
References do_pause_or_unpause(), and MONITOR_ACTION_PAUSE.
Referenced by load_module().
 {
    return do_pause_or_unpause(s, m, MONITOR_ACTION_PAUSE);
 }
pause_monitor_exec()
static int pause_monitor_exec (struct ast_channel * chan, const char * data) static
Wrapper for ast_monitor_pause.
Definition at line 571 of file res_monitor.c.
References ast_monitor_pause().
Referenced by load_module().
 {
    return ast_monitor_pause(chan);
 }
start_monitor_action()
static int start_monitor_action (struct mansession * s, const struct message * m) static
Start monitoring a channel by manager connection.
Definition at line 808 of file res_monitor.c.
References AMI_SUCCESS, ast_channel_get_by_name(), ast_channel_lock, ast_channel_name(), ast_channel_unlock, ast_channel_unref, ast_monitor_change_fname(), ast_monitor_setjoinfiles(), ast_monitor_start(), ast_strdupa, ast_strlen_zero, ast_true(), astman_get_header(), astman_send_ack(), astman_send_error(), c, d, format, name, NULL, X_REC_IN, and X_REC_OUT.
Referenced by load_module().
 {
    struct ast_channel *c = NULL;
    const char *name = astman_get_header(m, "Channel");
    const char *fname = astman_get_header(m, "File");
    const char *format = astman_get_header(m, "Format");
    const char *mix = astman_get_header(m, "Mix");
    char *d;
    if (ast_strlen_zero(name)) {
       astman_send_error(s, m, "No channel specified");
       return AMI_SUCCESS;
    }
    if (!(c = ast_channel_get_by_name(name))) {
       astman_send_error(s, m, "No such channel");
       return AMI_SUCCESS;
    }
    if (ast_strlen_zero(fname)) {
       /* No filename specified, default to the channel name. */
       ast_channel_lock(c);
       fname = ast_strdupa(ast_channel_name(c));
       ast_channel_unlock(c);
       /* Replace all '/' chars from the channel name with '-' chars. */
       for (d = (char *) fname; (d = strchr(d, '/')); ) {
          *d = '-';
       }
    }
    if (ast_monitor_start(c, format, fname, 1, X_REC_IN | X_REC_OUT, NULL)) {
       if (ast_monitor_change_fname(c, fname, 1)) {
          astman_send_error(s, m, "Could not start monitoring channel");
          c = ast_channel_unref(c);
          return AMI_SUCCESS;
       }
    }
    if (ast_true(mix)) {
       ast_channel_lock(c);
       ast_monitor_setjoinfiles(c, 1);
       ast_channel_unlock(c);
    }
    c = ast_channel_unref(c);
    astman_send_ack(s, m, "Started monitoring channel");
    return AMI_SUCCESS;
 }
start_monitor_exec()
static int start_monitor_exec (struct ast_channel * chan, const char * data) static
Start monitor.
Parameters
chan
data arguments passed fname|options
Return values
0 on success.
-1 on failure.
Definition at line 693 of file res_monitor.c.
References args, AST_APP_ARG, ast_app_parse_options(), ast_beep_start(), ast_cdr_setuserfield(), ast_channel_lock, ast_channel_name(), ast_channel_unlock, AST_DECLARE_APP_ARGS, ast_log, ast_monitor_change_fname(), ast_monitor_setjoinfiles(), ast_monitor_start(), AST_STANDARD_APP_ARGS, ast_strdupa, ast_strlen_zero, ast_test_flag, format, LOG_ERROR, LOG_WARNING, MON_FLAG_BEEP, MON_FLAG_BRIDGED, MON_FLAG_DROP_IN, MON_FLAG_DROP_OUT, MON_FLAG_MIX, monitor_opts, NULL, OPT_ARG_ARRAY_SIZE, OPT_ARG_BEEP_INTERVAL, options, parse(), pbx_builtin_setvar_helper(), S_OR, tmp(), X_JOIN, X_REC_IN, and X_REC_OUT.
Referenced by load_module().
 {
    char *arg;
    char *options;
    char *delay;
    char *urlprefix = NULL;
    char tmp[256];
    int stream_action = X_REC_IN | X_REC_OUT;
    int joinfiles = 0;
    int res = 0;
    char *parse;
    struct ast_flags flags = { 0 };
    char *opts[OPT_ARG_ARRAY_SIZE] = { NULL, };
    char beep_id[64] = "";
    AST_DECLARE_APP_ARGS(args,
       AST_APP_ARG(format);
       AST_APP_ARG(fname_base);
       AST_APP_ARG(options);
    );
    /* Parse arguments. */
    if (ast_strlen_zero(data)) {
       ast_log(LOG_ERROR, "Monitor requires an argument\n");
       return 0;
    }
    parse = ast_strdupa(data);
    AST_STANDARD_APP_ARGS(args, parse);
    if (!ast_strlen_zero(args.options)) {
       ast_app_parse_options(monitor_opts, &flags, opts, args.options);
       if (ast_test_flag(&flags, MON_FLAG_MIX)) {
          stream_action |= X_JOIN;
       }
       if (ast_test_flag(&flags, MON_FLAG_DROP_IN)) {
          stream_action &= ~X_REC_IN;
       }
       if (ast_test_flag(&flags, MON_FLAG_DROP_OUT)) {
          stream_action &= ~X_REC_OUT;
       }
       if (ast_test_flag(&flags, MON_FLAG_BEEP)) {
          const char *interval_str = S_OR(opts[OPT_ARG_BEEP_INTERVAL], "15");
          unsigned int interval = 15;
          if (sscanf(interval_str, "%30u", &interval) != 1) {
             ast_log(LOG_WARNING, "Invalid interval '%s' for periodic beep. Using default of %u\n",
                   interval_str, interval);
          }
          if (ast_beep_start(chan, interval, beep_id, sizeof(beep_id))) {
             ast_log(LOG_WARNING, "Unable to enable periodic beep, please ensure func_periodic_hook is loaded.\n");
             return -1;
          }
       }
    }
    arg = strchr(args.format, ':');
    if (arg) {
       *arg++ = 0;
       urlprefix = arg;
    }
    if (!ast_strlen_zero(urlprefix) && !ast_strlen_zero(args.fname_base)) {
       snprintf(tmp, sizeof(tmp), "%s/%s.%s", urlprefix, args.fname_base,
          ((strcmp(args.format, "gsm")) ? "wav" : "gsm"));
       ast_channel_lock(chan);
       ast_cdr_setuserfield(ast_channel_name(chan), tmp);
       ast_channel_unlock(chan);
    }
    if (ast_test_flag(&flags, MON_FLAG_BRIDGED)) {
       /* We must remove the "b" option if listed.  In principle none of
          the following could give NULL results, but we check just to
          be pedantic. Reconstructing with checks for 'm' option does not
          work if we end up adding more options than 'm' in the future. */
       delay = ast_strdupa(data);
       options = strrchr(delay, ',');
       if (options) {
          arg = strchr(options, 'b');
          if (arg) {
             *arg = 'X';
             pbx_builtin_setvar_helper(chan,"AUTO_MONITOR", delay);
          }
       }
       return 0;
    }
    res = ast_monitor_start(chan, args.format, args.fname_base, 1, stream_action, beep_id);
    if (res < 0)
       res = ast_monitor_change_fname(chan, args.fname_base, 1);
    if (stream_action & X_JOIN) {
       if ((stream_action & X_REC_IN) && (stream_action & X_REC_OUT))
          joinfiles = 1;
       else
          ast_log(LOG_WARNING, "Won't mix streams unless both input and output streams are recorded\n");
    }
    ast_monitor_setjoinfiles(chan, joinfiles);
    return res;
 }
stop_monitor_action()
static int stop_monitor_action (struct mansession * s, const struct message * m) static
Stop monitoring a channel by manager connection.
Definition at line 861 of file res_monitor.c.
References AMI_SUCCESS, ast_channel_get_by_name(), ast_channel_unref, ast_monitor_stop(), ast_strlen_zero, astman_get_header(), astman_send_ack(), astman_send_error(), c, name, and NULL.
Referenced by load_module().
 {
    struct ast_channel *c = NULL;
    const char *name = astman_get_header(m, "Channel");
    int res;
    if (ast_strlen_zero(name)) {
       astman_send_error(s, m, "No channel specified");
       return AMI_SUCCESS;
    }
    if (!(c = ast_channel_get_by_name(name))) {
       astman_send_error(s, m, "No such channel");
       return AMI_SUCCESS;
    }
    res = ast_monitor_stop(c, 1);
    c = ast_channel_unref(c);
    if (res) {
       astman_send_error(s, m, "Could not stop monitoring channel");
       return AMI_SUCCESS;
    }
    astman_send_ack(s, m, "Stopped monitoring channel");
    return AMI_SUCCESS;
 }
stop_monitor_exec()
static int stop_monitor_exec (struct ast_channel * chan, const char * data) static
Wrapper function.
See also
ast_monitor_stop
Definition at line 796 of file res_monitor.c.
References ast_monitor_stop().
Referenced by load_module().
 {
    return ast_monitor_stop(chan, 1);
 }
unload_module()
static int unload_module (void) static
Definition at line 992 of file res_monitor.c.
References ast_manager_unregister(), AST_MODFLAG_GLOBAL_SYMBOLS, AST_MODFLAG_LOAD_ORDER, AST_MODPRI_CHANNEL_DEPEND, AST_MODULE_INFO(), AST_MODULE_SUPPORT_DEPRECATED, ast_unregister_application(), ASTERISK_GPL_KEY, and load_module().
 {
    ast_unregister_application("Monitor");
    ast_unregister_application("StopMonitor");
    ast_unregister_application("ChangeMonitor");
    ast_unregister_application("PauseMonitor");
    ast_unregister_application("UnpauseMonitor");
    ast_manager_unregister("Monitor");
    ast_manager_unregister("StopMonitor");
    ast_manager_unregister("ChangeMonitor");
    ast_manager_unregister("PauseMonitor");
    ast_manager_unregister("UnpauseMonitor");
    return 0;
 }
unpause_monitor_action()
static int unpause_monitor_action (struct mansession * s, const struct message * m) static
Definition at line 971 of file res_monitor.c.
References do_pause_or_unpause(), and MONITOR_ACTION_UNPAUSE.
Referenced by load_module().
 {
    return do_pause_or_unpause(s, m, MONITOR_ACTION_UNPAUSE);
 }
unpause_monitor_exec()
static int unpause_monitor_exec (struct ast_channel * chan, const char * data) static
Wrapper for ast_monitor_unpause.
Definition at line 577 of file res_monitor.c.
References ast_monitor_unpause().
Referenced by load_module().
 {
    return ast_monitor_unpause(chan);
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_GLOBAL_SYMBOLS | AST_MODFLAG_LOAD_ORDER , .description = "Call Monitoring Resource" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_DEPRECATED, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_CHANNEL_DEPEND, .optional_modules = "func_periodic_hook", } static
Definition at line 1015 of file res_monitor.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 1015 of file res_monitor.c.
monitor_opts
const struct ast_app_option monitor_opts[128] = { [ 'b' ] = { .flag = MON_FLAG_BRIDGED }, [ 'm' ] = { .flag = MON_FLAG_MIX }, [ 'i' ] = { .flag = MON_FLAG_DROP_IN }, [ 'o' ] = { .flag = MON_FLAG_DROP_OUT }, [ 'B' ] = { .flag = MON_FLAG_BEEP , .arg_index = OPT_ARG_BEEP_INTERVAL + 1 }, } static
Definition at line 684 of file res_monitor.c.
Referenced by start_monitor_exec().
monitorlock
ast_mutex_t monitorlock = { PTHREAD_RECURSIVE_MUTEX_INITIALIZER_NP , NULL, {1, 0} } static
Definition at line 261 of file res_monitor.c.
Referenced by ast_monitor_start().
seq
unsigned long seq = 0 static
Definition at line 273 of file res_monitor.c.
Referenced by ast_monitor_start().