Asterisk - The Open Source Telephony Project: conf_chan_record.c File Reference
conf_chan_record.c File Reference
ConfBridge recorder channel driver.
#include "asterisk.h"
#include "asterisk/channel.h"
#include "asterisk/bridge.h"
#include "asterisk/format_cache.h"
#include "include/confbridge.h"
Functions
struct ast_channel_tech * conf_record_get_tech (void)
Get ConfBridge record channel technology struct.
static int rec_call (struct ast_channel *chan, const char *addr, int timeout)
static struct ast_frame * rec_read (struct ast_channel *ast)
static struct ast_channel * rec_request (const char *type, struct ast_format_cap *cap, const struct ast_assigned_ids *assignedids, const struct ast_channel *requestor, const char *data, int *cause)
static int rec_write (struct ast_channel *ast, struct ast_frame *f)
Variables
static unsigned int name_sequence = 0
static struct ast_channel_tech record_tech
Detailed Description
ConfBridge recorder channel driver.
Author
Richard Mudgett rmudg.nosp@m.ett@.nosp@m.digiu.nosp@m.m.co.nosp@m.m
See Also:
CREDITS
Definition in file conf_chan_record.c.
Function Documentation
conf_record_get_tech()
struct ast_channel_tech* conf_record_get_tech (void)
Get ConfBridge record channel technology struct.
Since
12.0.0
Returns
ConfBridge record channel technology.
Definition at line 102 of file conf_chan_record.c.
References record_tech.
Referenced by load_module(), rec_request(), and unload_module().
 {
    return &record_tech;
 }
rec_call()
static int rec_call (struct ast_channel * chan, const char * addr, int timeout) static
Definition at line 41 of file conf_chan_record.c.
 {
    /* Make sure anyone calling ast_call() for this channel driver is going to fail. */
    return -1;
 }
rec_read()
static struct ast_frame* rec_read (struct ast_channel * ast) static
Definition at line 47 of file conf_chan_record.c.
References ast_null_frame.
 {
    return &ast_null_frame;
 }
rec_request()
static struct ast_channel* rec_request (const char * type, struct ast_format_cap * cap, const struct ast_assigned_ids * assignedids, const struct ast_channel * requestor, const char * data, int * cause) static
Definition at line 57 of file conf_chan_record.c.
References ao2_cleanup, ast_atomic_fetchadd_int(), ast_channel_add_bridge_role(), ast_channel_alloc, ast_channel_nativeformats_set(), ast_channel_release(), ast_channel_set_rawreadformat(), ast_channel_set_rawwriteformat(), ast_channel_set_readformat(), ast_channel_set_writeformat(), ast_channel_tech_set(), ast_channel_unlock, ast_format_cap_alloc, ast_format_cap_append_by_type(), AST_FORMAT_CAP_FLAG_DEFAULT, ast_format_slin, AST_MEDIA_TYPE_AUDIO, AST_STATE_UP, conf_record_get_tech(), ast_channel::data, name_sequence, NULL, and RAII_VAR.
 {
    struct ast_channel *chan;
    const char *conf_name = data;
    RAII_VAR(struct ast_format_cap *, capabilities, NULL, ao2_cleanup);
    int generated_seqno = ast_atomic_fetchadd_int((int *) &name_sequence, +1);
    capabilities = ast_format_cap_alloc(AST_FORMAT_CAP_FLAG_DEFAULT);
    if (!capabilities) {
       return NULL;
    }
    ast_format_cap_append_by_type(capabilities, AST_MEDIA_TYPE_AUDIO);
    chan = ast_channel_alloc(1, AST_STATE_UP, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0,
       "CBRec/%s-%08x",
       conf_name, (unsigned) generated_seqno);
    if (!chan) {
       return NULL;
    }
    if (ast_channel_add_bridge_role(chan, "recorder")) {
       ast_channel_unlock(chan);
       ast_channel_release(chan);
       return NULL;
    }
    ast_channel_tech_set(chan, conf_record_get_tech());
    ast_channel_nativeformats_set(chan, capabilities);
    ast_channel_set_writeformat(chan, ast_format_slin);
    ast_channel_set_rawwriteformat(chan, ast_format_slin);
    ast_channel_set_readformat(chan, ast_format_slin);
    ast_channel_set_rawreadformat(chan, ast_format_slin);
    ast_channel_unlock(chan);
    return chan;
 }
rec_write()
static int rec_write (struct ast_channel * ast, struct ast_frame * f) static
Definition at line 52 of file conf_chan_record.c.
 {
    return 0;
 }
Variable Documentation
name_sequence
unsigned int name_sequence = 0 static
Definition at line 39 of file conf_chan_record.c.
Referenced by rec_request().
record_tech
struct ast_channel_tech record_tech static
Definition at line 92 of file conf_chan_record.c.
Referenced by conf_record_get_tech().