Asterisk - The Open Source Telephony Project: 52798ad97bdf_add_pjsip_identify_by_header Namespace Reference
52798ad97bdf_add_pjsip_identify_by_header Namespace Reference
Functions
def column_downgrade (table_name, column_name, enum_name, enum_values)
def column_upgrade (table_name, column_name, enum_name)
def downgrade ()
def upgrade ()
Variables
string down_revision = 'e2f04d309071'
string revision = '52798ad97bdf'
Function Documentation
column_downgrade()
def 52798ad97bdf_add_pjsip_identify_by_header.column_downgrade (table_name, column_name, enum_name, enum_values)
Definition at line 32 of file 52798ad97bdf_add_pjsip_identify_by_header.py.
Referenced by downgrade().
 def column_downgrade(table_name, column_name, enum_name, enum_values):
     if op.get_context().bind.dialect.name != 'postgresql':
         op.alter_column(table_name, column_name,
                         type_=sa.Enum(*enum_values, name=enum_name))
         return
     # Postgres requires a few more steps
     updated = sa.Enum(*enum_values, name=enum_name)
     updated.create(op.get_bind(), checkfirst=False)
     op.execute('ALTER TABLE ' + table_name + ' ALTER COLUMN ' + column_name +
                ' TYPE ' + enum_name + ' USING identify_by::text::' + enum_name)
column_upgrade()
def 52798ad97bdf_add_pjsip_identify_by_header.column_upgrade (table_name, column_name, enum_name)
Definition at line 17 of file 52798ad97bdf_add_pjsip_identify_by_header.py.
Referenced by upgrade().
 def column_upgrade(table_name, column_name, enum_name):
     if op.get_context().bind.dialect.name != 'postgresql':
         if op.get_context().bind.dialect.name == 'mssql':
             op.drop_constraint('ck_ps_endpoints_identify_by_pjsip_identify_by_values',
                                table_name)
         op.alter_column(table_name, column_name, type_=sa.String(80))
         return
     # Postgres requires a few more steps
     op.execute('ALTER TABLE ' + table_name + ' ALTER COLUMN ' + column_name +
                ' TYPE varchar(80) USING identify_by::text::' + enum_name)
     op.execute('DROP TYPE ' + enum_name)
downgrade()
def 52798ad97bdf_add_pjsip_identify_by_header.downgrade ()
Definition at line 55 of file 52798ad97bdf_add_pjsip_identify_by_header.py.
References column_downgrade().
 def downgrade():
     column_downgrade('ps_endpoints', 'identify_by', 'pjsip_identify_by_values',
                      ['username', 'auth_username', 'ip'])
upgrade()
def 52798ad97bdf_add_pjsip_identify_by_header.upgrade ()
Definition at line 46 of file 52798ad97bdf_add_pjsip_identify_by_header.py.
References column_upgrade().
 def upgrade():
     # The ps_endpoints identify_by column has always been a comma separated
     # list of enum values.  This is better represented as a string anyway to
     # avoid database compatibility issues.  Also future changes are likely
     # to allow loadable endpoint identifier names and negating fixed enum
     # benefits.
     column_upgrade('ps_endpoints', 'identify_by', 'pjsip_identify_by_values')
Variable Documentation
down_revision
string down_revision = 'e2f04d309071'
Definition at line 11 of file 52798ad97bdf_add_pjsip_identify_by_header.py.
revision
string revision = '52798ad97bdf'
Definition at line 10 of file 52798ad97bdf_add_pjsip_identify_by_header.py.