Asterisk - The Open Source Telephony Project: bt_close.c File Reference
bt_close.c File Reference
#include <sys/param.h>
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include "../include/db.h"
#include "btree.h"
Functions
int __bt_close (DB *dbp)
int __bt_sync (DB *dbp, u_int flags) const
static int bt_meta __P ((BTREE *))
static int bt_meta (BTREE *t)
Function Documentation
__bt_close()
int __bt_close (DB * dbp)
Definition at line 64 of file bt_close.c.
References __bt_sync(), _btree::bt_cursor, _btree::bt_fd, _btree::bt_mp, _btree::bt_pinned, _btree::bt_rdata, _btree::bt_rkey, DBT::data, free(), __db::internal, _cursor::key, mpool_close(), mpool_put(), NULL, RET_ERROR, RET_SUCCESS, and DBT::size.
Referenced by __bt_open(), __rec_close(), and __rec_open().
 {
    BTREE *t;
    int fd;
    t = dbp->internal;
    /* Toss any page pinned across calls. */
    if (t->bt_pinned != NULL) {
       mpool_put(t->bt_mp, t->bt_pinned, 0);
       t->bt_pinned = NULL;
    }
    /* Sync the tree. */
    if (__bt_sync(dbp, 0) == RET_ERROR)
       return (RET_ERROR);
    /* Close the memory pool. */
    if (mpool_close(t->bt_mp) == RET_ERROR)
       return (RET_ERROR);
    /* Free random memory. */
    if (t->bt_cursor.key.data != NULL) {
       free(t->bt_cursor.key.data);
       t->bt_cursor.key.size = 0;
       t->bt_cursor.key.data = NULL;
    }
    if (t->bt_rkey.data) {
       free(t->bt_rkey.data);
       t->bt_rkey.size = 0;
       t->bt_rkey.data = NULL;
    }
    if (t->bt_rdata.data) {
       free(t->bt_rdata.data);
       t->bt_rdata.size = 0;
       t->bt_rdata.data = NULL;
    }
    fd = t->bt_fd;
    free(t);
    free(dbp);
    return (close(fd) ? RET_ERROR : RET_SUCCESS);
 }
__bt_sync()
int __bt_sync (DB * dbp, u_int flags) const
Definition at line 119 of file bt_close.c.
References B_INMEM, B_METADIRTY, B_MODIFIED, B_RDONLY, bt_meta(), _btree::bt_mp, _btree::bt_pinned, errno, F_CLR, F_ISSET, __db::internal, mpool_put(), mpool_sync(), NULL, RET_ERROR, RET_SUCCESS, and status.
Referenced by __bt_close(), __bt_open(), and __rec_sync().
 {
    BTREE *t;
    int status;
    t = dbp->internal;
    /* Toss any page pinned across calls. */
    if (t->bt_pinned != NULL) {
       mpool_put(t->bt_mp, t->bt_pinned, 0);
       t->bt_pinned = NULL;
    }
    /* Sync doesn't currently take any flags. */
    if (flags != 0) {
       errno = EINVAL;
       return (RET_ERROR);
    }
    if (F_ISSET(t, B_INMEM | B_RDONLY) || !F_ISSET(t, B_MODIFIED))
       return (RET_SUCCESS);
    if (F_ISSET(t, B_METADIRTY) && bt_meta(t) == RET_ERROR)
       return (RET_ERROR);
    if ((status = mpool_sync(t->bt_mp)) == RET_SUCCESS)
       F_CLR(t, B_MODIFIED);
    return (status);
 }
__P()
static int bt_meta __P ((BTREE *)) static
bt_meta()
static int bt_meta (BTREE * t) static
Definition at line 162 of file bt_close.c.
References _btree::bt_free, _btree::bt_mp, _btree::bt_nrecs, _btree::bt_psize, BTREEMAGIC, BTREEVERSION, F_ISSET, _btmeta::flags, _btmeta::free, _btmeta::magic, MPOOL_DIRTY, mpool_get(), mpool_put(), _btmeta::nrecs, NULL, P_META, _btmeta::psize, RET_ERROR, RET_SUCCESS, SAVEMETA, and _btmeta::version.
Referenced by __bt_sync().
 {
    BTMETA m;
    void *p;
    if ((p = mpool_get(t->bt_mp, P_META, 0)) == NULL)
       return (RET_ERROR);
    /* Fill in metadata. */
    m.magic = BTREEMAGIC;
    m.version = BTREEVERSION;
    m.psize = t->bt_psize;
    m.free = t->bt_free;
    m.nrecs = t->bt_nrecs;
    m.flags = F_ISSET(t, SAVEMETA);
    memmove(p, &m, sizeof(BTMETA));
    mpool_put(t->bt_mp, p, MPOOL_DIRTY);
    return (RET_SUCCESS);
 }