Asterisk - The Open Source Telephony Project: test_db.c File Reference
test_db.c File Reference
AstDB Unit Tests.
#include "asterisk.h"
#include "asterisk/test.h"
#include "asterisk/module.h"
#include "asterisk/astdb.h"
#include "asterisk/logger.h"
Macros
#define BASE "astdbtest"
#define FAM1 BASE "/" SUB1
#define FAM2 BASE "/" SUB2
#define STR_FILL_32 "abcdefghijklmnopqrstuvwxyz123456"
#define SUB1 "one"
#define SUB2 "two"
Enumerations
enum { FAMILY = 0, KEY = 1, VALUE = 2 }
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
AST_TEST_DEFINE (put_get_del)
AST_TEST_DEFINE (gettree_deltree)
AST_TEST_DEFINE (perftest)
AST_TEST_DEFINE (put_get_long)
static int load_module (void)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "AstDB test module" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, }
static const struct ast_module_info * ast_module_info = &__mod_info
static const char long_val [] = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
Detailed Description
AstDB Unit Tests.
Author
Terry Wilson twils.nosp@m.on@d.nosp@m.igium.nosp@m..com
Definition in file test_db.c.
Macro Definition Documentation
BASE
#define BASE "astdbtest"
Referenced by AST_TEST_DEFINE().
FAM1
#define FAM1 BASE "/" SUB1
Referenced by AST_TEST_DEFINE().
FAM2
#define FAM2 BASE "/" SUB2
Referenced by AST_TEST_DEFINE().
STR_FILL_32
#define STR_FILL_32 "abcdefghijklmnopqrstuvwxyz123456"
Referenced by AST_TEST_DEFINE().
SUB1
#define SUB1 "one"
Referenced by AST_TEST_DEFINE().
SUB2
#define SUB2 "two"
Referenced by AST_TEST_DEFINE().
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
FAMILY
KEY
VALUE
Definition at line 39 of file test_db.c.
      {
    FAMILY = 0,
    KEY    = 1,
    VALUE  = 2,
 };
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 309 of file test_db.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 309 of file test_db.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 309 of file test_db.c.
AST_TEST_DEFINE() [1/4]
AST_TEST_DEFINE (put_get_del)
Definition at line 49 of file test_db.c.
References ARRAY_LEN, ast_db_del(), ast_db_get(), ast_db_put(), AST_TEST_FAIL, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_test_status_update, buf, FAMILY, sip_to_pjsip::info(), KEY, long_val, TEST_EXECUTE, TEST_INIT, and VALUE.
 {
    int res = AST_TEST_PASS;
    const char *inputs[][3] = {
       {"family", "key", "value"},
       {"astdbtest", "a", "b"},
       {"astdbtest", "a", "a"},
       {"astdbtest", "b", "a"},
       {"astdbtest", "b", "b"},
       {"astdbtest", "b", "!@#$%^&*()|+-<>?"},
       {"astdbtest", long_val, "b"},
       {"astdbtest", "b", long_val},
       {"astdbtest", "!@#$%^&*()|+-<>?", "b"},
    };
    size_t x;
    char buf[sizeof(long_val)] = { 0, };
    switch (cmd) {
    case TEST_INIT:
       info->name = "put_get_del";
       info->category = "/main/astdb/";
       info->summary = "ast_db_(put|get|del) unit test";
       info->description =
          "Ensures that the ast_db put, get, and del functions work";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    for (x = 0; x < ARRAY_LEN(inputs); x++) {
       if (ast_db_put(inputs[x][FAMILY], inputs[x][KEY], inputs[x][VALUE])) {
          ast_test_status_update(test, "Failed to put %s : %s : %s\n", inputs[x][FAMILY], inputs[x][KEY], inputs[x][VALUE]);
          res = AST_TEST_FAIL;
       }
       if (ast_db_get(inputs[x][FAMILY], inputs[x][KEY], buf, sizeof(buf))) {
          ast_test_status_update(test, "Failed to get %s : %s : %s\n", inputs[x][FAMILY], inputs[x][KEY], inputs[x][VALUE]);
          res = AST_TEST_FAIL;
       } else if (strcmp(buf, inputs[x][VALUE])) {
          ast_test_status_update(test, "Failed to match key '%s/%s' value '%s' to '%s'\n", inputs[x][FAMILY], inputs[x][KEY], inputs[x][VALUE], buf);
          res = AST_TEST_FAIL;
       }
       if (ast_db_del(inputs[x][FAMILY], inputs[x][KEY])) {
          ast_test_status_update(test, "Failed to del %s : %s\n", inputs[x][FAMILY], inputs[x][KEY]);
          res = AST_TEST_FAIL;
       }
    }
    return res;
 }
AST_TEST_DEFINE() [2/4]
AST_TEST_DEFINE (gettree_deltree)
Definition at line 99 of file test_db.c.
References ARRAY_LEN, ast_db_deltree(), ast_db_freetree(), ast_db_gettree(), ast_db_put(), AST_TEST_FAIL, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_test_status_update, BASE, buf, ast_db_entry::data, FAM1, FAM2, FAMILY, sip_to_pjsip::info(), ast_db_entry::key, KEY, ast_db_entry::next, NULL, SUB1, SUB2, TEST_EXECUTE, TEST_INIT, and VALUE.
 {
    int res = AST_TEST_PASS;
    const char *inputs[][3] = {
 #define BASE "astdbtest"
 #define SUB1 "one"
 #define SUB2 "two"
 #define FAM1 BASE "/" SUB1
 #define FAM2 BASE "/" SUB2
       {FAM1, "one", "blah"},
       {FAM1, "two", "bling"},
       {FAM1, "three", "blast"},
       {FAM2, "one", "blah"},
       {FAM2, "two", "bling"},
       {FAM2, "three", "blast"},
    };
    size_t x;
    struct ast_db_entry *dbes, *cur;
    int num_deleted;
    switch (cmd) {
    case TEST_INIT:
       info->name = "gettree_deltree";
       info->category = "/main/astdb/";
       info->summary = "ast_db_(gettree|deltree) unit test";
       info->description =
          "Ensures that the ast_db gettree and deltree functions work";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    for (x = 0; x < ARRAY_LEN(inputs); x++) {
       if (ast_db_put(inputs[x][FAMILY], inputs[x][KEY], inputs[x][VALUE])) {
          ast_test_status_update(test, "Failed to put %s : %s : %s\n", inputs[x][FAMILY], inputs[x][KEY], inputs[x][VALUE]);
          res = AST_TEST_FAIL;
       }
    }
    if (!(dbes = ast_db_gettree(BASE, NULL))) {
       ast_test_status_update(test, "Failed to ast_db_gettree family %s\n", BASE);
       res = AST_TEST_FAIL;
    }
    for (cur = dbes, x = 0; cur; cur = cur->next, x++) {
       int found = 0;
       size_t z;
       for (z = 0; z < ARRAY_LEN(inputs); z++) {
          char buf[256];
          snprintf(buf, sizeof(buf), "/%s/%s", inputs[z][FAMILY], inputs[z][KEY]);
          if (!strcmp(buf, cur->key) && !strcmp(inputs[z][VALUE], cur->data)) {
             found = 1;
          }
       }
       if (!found) {
          ast_test_status_update(test, "inputs array has no entry for %s == %s\n", cur->key, cur->data);
          res = AST_TEST_FAIL;
       }
    }
    if (x != ARRAY_LEN(inputs)) {
       ast_test_status_update(test, "ast_db_gettree returned %zu entries when we expected %zu\n", x, ARRAY_LEN(inputs));
       res = AST_TEST_FAIL;
    }
    ast_db_freetree(dbes);
    if (!(dbes = ast_db_gettree(BASE, SUB1))) {
       ast_test_status_update(test, "Failed to ast_db_gettree for %s/%s\n", BASE, SUB1);
       res = AST_TEST_FAIL;
    }
    for (cur = dbes, x = 0; cur; cur = cur->next, x++) {
       int found = 0;
       size_t z;
       for (z = 0; z < ARRAY_LEN(inputs); z++) {
          char buf[256];
          snprintf(buf, sizeof(buf), "/%s/%s", inputs[z][FAMILY], inputs[z][KEY]);
          if (!strcmp(buf, cur->key) && !strcmp(inputs[z][VALUE], cur->data)) {
             found = 1;
          }
       }
       if (!found) {
          ast_test_status_update(test, "inputs array has no entry for %s == %s\n", cur->key, cur->data);
          res = AST_TEST_FAIL;
       }
    }
    if (x != (ARRAY_LEN(inputs) / 2)) {
       ast_test_status_update(test, "ast_db_gettree returned %zu entries when we expected %zu\n", x, ARRAY_LEN(inputs) / 2);
       res = AST_TEST_FAIL;
    }
    ast_db_freetree(dbes);
    if ((num_deleted = ast_db_deltree(BASE, SUB2)) != ARRAY_LEN(inputs) / 2) {
       ast_test_status_update(test, "Failed to deltree %s/%s, expected %zu deletions and got %d\n", BASE, SUB2, ARRAY_LEN(inputs) / 2, num_deleted);
       res = AST_TEST_FAIL;
    }
    if ((num_deleted = ast_db_deltree(BASE, NULL)) != ARRAY_LEN(inputs) / 2) {
       ast_test_status_update(test, "Failed to deltree %s, expected %zu deletions and got %d\n", BASE, ARRAY_LEN(inputs) / 2, num_deleted);
       res = AST_TEST_FAIL;
    }
    return res;
 }
AST_TEST_DEFINE() [3/4]
AST_TEST_DEFINE (perftest)
Definition at line 207 of file test_db.c.
References ast_db_deltree(), ast_db_put(), AST_TEST_NOT_RUN, AST_TEST_PASS, buf, sip_to_pjsip::info(), NULL, TEST_EXECUTE, and TEST_INIT.
 {
    int res = AST_TEST_PASS;
    size_t x;
    char buf[10];
    switch (cmd) {
    case TEST_INIT:
       info->name = "perftest";
       info->category = "/main/astdb/";
       info->summary = "astdb performance unit test";
       info->description =
          "Measure astdb performance";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    for (x = 0; x < 100000; x++) {
       sprintf(buf, "%zu", x);
       ast_db_put("astdbtest", buf, buf);
    }
    ast_db_deltree("astdbtest", NULL);
    return res;
 }
AST_TEST_DEFINE() [4/4]
AST_TEST_DEFINE (put_get_long)
Definition at line 234 of file test_db.c.
References ast_db_del(), ast_db_get_allocated(), ast_db_put(), ast_free, ast_str_append(), ast_str_buffer(), ast_str_create, ast_str_reset(), ast_str_strlen(), AST_TEST_FAIL, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_test_status_update, sip_to_pjsip::info(), NULL, out, STR_FILL_32, TEST_EXECUTE, and TEST_INIT.
 {
    int res = AST_TEST_PASS;
    struct ast_str *s;
    int i, j;
 #define STR_FILL_32 "abcdefghijklmnopqrstuvwxyz123456"
    switch (cmd) {
    case TEST_INIT:
       info->name = "put_get_long";
       info->category = "/main/astdb/";
       info->summary = "ast_db_(put|get_allocated) unit test";
       info->description =
          "Ensures that the ast_db_put and ast_db_get_allocated functions work";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    if (!(s = ast_str_create(4096))) {
       return AST_TEST_FAIL;
    }
    for (i = 1024; i <= 1024 * 1024 * 8; i *= 2) {
       char *out = NULL;
       ast_str_reset(s);
       for (j = 0; j < i; j += sizeof(STR_FILL_32) - 1) {
          ast_str_append(&s, 0, "%s", STR_FILL_32);
       }
       if (ast_db_put("astdbtest", "long", ast_str_buffer(s))) {
          ast_test_status_update(test, "Failed to put value of %zu bytes\n", ast_str_strlen(s));
          res = AST_TEST_FAIL;
       } else if (ast_db_get_allocated("astdbtest", "long", &out)) {
          ast_test_status_update(test, "Failed to get value of %zu bytes\n", ast_str_strlen(s));
          res = AST_TEST_FAIL;
       } else if (strcmp(ast_str_buffer(s), out)) {
          ast_test_status_update(test, "Failed to match value of %zu bytes\n", ast_str_strlen(s));
          res = AST_TEST_FAIL;
       } else if (ast_db_del("astdbtest", "long")) {
          ast_test_status_update(test, "Failed to delete astdbtest/long\n");
          res = AST_TEST_FAIL;
       }
       if (out) {
          ast_free(out);
       }
    }
    ast_free(s);
    return res;
 }
load_module()
static int load_module (void) static
Definition at line 300 of file test_db.c.
References AST_MODULE_LOAD_SUCCESS, and AST_TEST_REGISTER.
 {
    AST_TEST_REGISTER(put_get_del);
    AST_TEST_REGISTER(gettree_deltree);
    AST_TEST_REGISTER(perftest);
    AST_TEST_REGISTER(put_get_long);
    return AST_MODULE_LOAD_SUCCESS;
 }
unload_module()
static int unload_module (void) static
Definition at line 291 of file test_db.c.
References AST_TEST_UNREGISTER.
 {
    AST_TEST_UNREGISTER(put_get_del);
    AST_TEST_UNREGISTER(gettree_deltree);
    AST_TEST_UNREGISTER(perftest);
    AST_TEST_UNREGISTER(put_get_long);
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "AstDB test module" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, } static
Definition at line 309 of file test_db.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 309 of file test_db.c.
long_val
const char long_val[] = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" static
Definition at line 47 of file test_db.c.
Referenced by AST_TEST_DEFINE().