Asterisk - The Open Source Telephony Project: res_hep.h File Reference
res_hep.h File Reference
Routines for integration with Homer using HEPv3.
#include "asterisk/netsock2.h"
Data Structures
struct hepv3_capture_info
HEPv3 Capture Info.
Enumerations
enum hep_uuid_type { HEP_UUID_TYPE_CALL_ID = 0, HEP_UUID_TYPE_CHANNEL }
enum hepv3_capture_type {
HEPV3_CAPTURE_TYPE_SIP = 0x01, HEPV3_CAPTURE_TYPE_H323 = 0x02, HEPV3_CAPTURE_TYPE_SDP = 0x03, HEPV3_CAPTURE_TYPE_RTP = 0x04,
HEPV3_CAPTURE_TYPE_RTCP = 0x05, HEPV3_CAPTURE_TYPE_MGCP = 0x06, HEPV3_CAPTURE_TYPE_MEGACO = 0x07, HEPV3_CAPTURE_TYPE_M2UA = 0x08,
HEPV3_CAPTURE_TYPE_M3UA = 0x09, HEPV3_CAPTURE_TYPE_IAX = 0x10
}
HEPv3 Packet Capture Types.
Functions
struct hepv3_capture_info * hepv3_create_capture_info (const void *payload, size_t len)
Create a hepv3_capture_info object.
enum hep_uuid_type hepv3_get_uuid_type (void)
Get the preferred UUID type.
int hepv3_is_loaded (void)
Return whether or not we're currently loaded and active.
int hepv3_send_packet (struct hepv3_capture_info *capture_info)
Send a generic packet capture to HEPv3.
Detailed Description
Routines for integration with Homer using HEPv3.
Author
Alexandr Dubovikov alexa.nosp@m.ndr..nosp@m.dubov.nosp@m.ikov.nosp@m.@sipc.nosp@m.aptu.nosp@m.re.or.nosp@m.g
Matt Jordan mjord.nosp@m.an@d.nosp@m.igium.nosp@m..com
Definition in file res_hep.h.
Enumeration Type Documentation
hep_uuid_type
enum hep_uuid_type
Enumerator
HEP_UUID_TYPE_CALL_ID
HEP_UUID_TYPE_CHANNEL
Definition at line 52 of file res_hep.h.
                    {
    HEP_UUID_TYPE_CALL_ID = 0,
    HEP_UUID_TYPE_CHANNEL,
 };
hepv3_capture_type
enum hepv3_capture_type
HEPv3 Packet Capture Types.
Enumerator
HEPV3_CAPTURE_TYPE_SIP
HEPV3_CAPTURE_TYPE_H323
HEPV3_CAPTURE_TYPE_SDP
HEPV3_CAPTURE_TYPE_RTP
HEPV3_CAPTURE_TYPE_RTCP
HEPV3_CAPTURE_TYPE_MGCP
HEPV3_CAPTURE_TYPE_MEGACO
HEPV3_CAPTURE_TYPE_M2UA
HEPV3_CAPTURE_TYPE_M3UA
HEPV3_CAPTURE_TYPE_IAX
Definition at line 39 of file res_hep.h.
{
    HEPV3_CAPTURE_TYPE_SIP    = 0x01,
    HEPV3_CAPTURE_TYPE_H323   = 0x02,
    HEPV3_CAPTURE_TYPE_SDP    = 0x03,
    HEPV3_CAPTURE_TYPE_RTP    = 0x04,
    HEPV3_CAPTURE_TYPE_RTCP   = 0x05,
    HEPV3_CAPTURE_TYPE_MGCP   = 0x06,
    HEPV3_CAPTURE_TYPE_MEGACO = 0x07,
    HEPV3_CAPTURE_TYPE_M2UA   = 0x08,
    HEPV3_CAPTURE_TYPE_M3UA   = 0x09,
    HEPV3_CAPTURE_TYPE_IAX    = 0x10,
 };
Function Documentation
hepv3_create_capture_info()
struct hepv3_capture_info* hepv3_create_capture_info (const void * payload, size_t len)
Create a hepv3_capture_info object.
This returned object is an ao2 reference counted object.
Any attribute in the returned hepv3_capture_info that is a pointer should point to something that is allocated on the heap, as it will be free'd when the hepv3_capture_info object is reclaimed.
Parameters
payload The payload to send to the HEP capture node
len Length of payload
Return values
A hepv3_capture_info ref counted object on success
NULL on error
Definition at line 428 of file res_hep.c.
References ao2_alloc, ao2_ref, ast_malloc, capture_info_dtor(), sip_to_pjsip::info(), hepv3_capture_info::len, len(), NULL, hepv3_capture_info::payload, and hepv3_capture_info::protocol_id.
Referenced by logging_on_rx_msg(), logging_on_tx_msg(), and rtcp_message_handler().
 {
    struct hepv3_capture_info *info;
    info = ao2_alloc(sizeof(*info), capture_info_dtor);
    if (!info) {
       return NULL;
    }
    info->payload = ast_malloc(len);
    if (!info->payload) {
       ao2_ref(info, -1);
       return NULL;
    }
    memcpy(info->payload, payload, len);
    info->len = len;
    /* Set a reasonable default */
    info->protocol_id = IPPROTO_UDP;
    return info;
 }
hepv3_get_uuid_type()
enum hep_uuid_type hepv3_get_uuid_type (void)
Get the preferred UUID type.
Since
13.10.0
Return values
The type of UUID the packet should use
Definition at line 409 of file res_hep.c.
References ao2_cleanup, ao2_global_obj_ref, config, HEP_UUID_TYPE_CALL_ID, and RAII_VAR.
Referenced by assign_uuid().
 {
    RAII_VAR(struct module_config *, config, ao2_global_obj_ref(global_config), ao2_cleanup);
    if (!config) {
       /* Well, that's unfortunate. Return something. */
       return HEP_UUID_TYPE_CALL_ID;
    }
    return config->general->uuid_type;
 }
hepv3_is_loaded()
int hepv3_is_loaded (void)
Return whether or not we're currently loaded and active.
Return values
0 The module is not loaded
1 The module is loaded
Definition at line 421 of file res_hep.c.
References ao2_cleanup, ao2_global_obj_ref, config, and RAII_VAR.
Referenced by load_module().
 {
    RAII_VAR(struct module_config *, config, ao2_global_obj_ref(global_config), ao2_cleanup);
    return config && config->general->enabled;
 }
hepv3_send_packet()
int hepv3_send_packet (struct hepv3_capture_info * capture_info)
Send a generic packet capture to HEPv3.
Parameters
capture_info Information describing the packet. This should be a reference counted object, created via hepv3_create_capture_info.
Once this function is called, it assumes ownership of the capture_info object and steals the reference of the object. Regardless of success or failure, the calling function should assumed that this function will own the object.
Return values
0 on success
-1 on error
Definition at line 581 of file res_hep.c.
References ao2_cleanup, ao2_global_obj_ref, ao2_ref, ast_taskprocessor_push(), config, hep_queue_cb(), and RAII_VAR.
Referenced by logging_on_rx_msg(), logging_on_tx_msg(), and rtcp_message_handler().
 {
    RAII_VAR(struct module_config *, config, ao2_global_obj_ref(global_config), ao2_cleanup);
    int res;
    if (!config || !config->general->enabled) {
       ao2_ref(capture_info, -1);
       return 0;
    }
    res = ast_taskprocessor_push(hep_queue_tp, hep_queue_cb, capture_info);
    if (res == -1) {
       ao2_ref(capture_info, -1);
    }
    return res;
 }