Asterisk - The Open Source Telephony Project: func_hangupcause.c File Reference
func_hangupcause.c File Reference
Module: Dial plan functions
Functions related to retreiving per-channel hangupcause information.
#include "asterisk.h"
#include "asterisk/module.h"
#include "asterisk/channel.h"
#include "asterisk/pbx.h"
#include "asterisk/utils.h"
#include "asterisk/app.h"
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int hangupcause_clear_exec (struct ast_channel *chan, const char *data)
static int hangupcause_keys_read (struct ast_channel *chan, const char *cmd, char *data, char *buf, size_t len)
static int hangupcause_read (struct ast_channel *chan, const char *cmd, char *data, char *buf, size_t len)
static int load_module (void)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "HANGUPCAUSE related functions and applications" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, }
static const char app [] = "HangupCauseClear"
static const struct ast_module_info * ast_module_info = &__mod_info
static struct ast_custom_function hangupcause_function
static struct ast_custom_function hangupcause_keys_function
Detailed Description
Functions related to retreiving per-channel hangupcause information.
Author
Kinsey Moore kmoor.nosp@m.e@di.nosp@m.gium..nosp@m.com
See Also:
CREDITS
Definition in file func_hangupcause.c.
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 256 of file func_hangupcause.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 256 of file func_hangupcause.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 256 of file func_hangupcause.c.
hangupcause_clear_exec()
static int hangupcause_clear_exec (struct ast_channel * chan, const char * data) static
Definition at line 202 of file func_hangupcause.c.
References ast_channel_dialed_causes_clear(), ast_channel_lock, and ast_channel_unlock.
Referenced by load_module().
{
    ast_channel_lock(chan);
    ast_channel_dialed_causes_clear(chan);
    ast_channel_unlock(chan);
    return 0;
 }
hangupcause_keys_read()
static int hangupcause_keys_read (struct ast_channel * chan, const char * cmd, char * data, char * buf, size_t len) static
Definition at line 169 of file func_hangupcause.c.
References ast_channel_dialed_causes_channels(), ast_channel_lock, ast_channel_unlock, ast_copy_string(), ast_free, ast_str_buffer(), and ast_str_strlen().
 {
    struct ast_str *chanlist;
    /* Ensure that the buffer is empty */
    *buf = 0;
    if (!chan) {
       return -1;
    }
    ast_channel_lock(chan);
    chanlist = ast_channel_dialed_causes_channels(chan);
    ast_channel_unlock(chan);
    if (chanlist && ast_str_strlen(chanlist)) {
       ast_copy_string(buf, ast_str_buffer(chanlist), len);
    }
    ast_free(chanlist);
    return 0;
 }
hangupcause_read()
static int hangupcause_read (struct ast_channel * chan, const char * cmd, char * data, char * buf, size_t len) static
< Channel name
< Type of information requested (ast or tech)
< Channel name
< Type of information requested (ast or tech)
Definition at line 108 of file func_hangupcause.c.
References ao2_ref, args, AST_APP_ARG, ast_control_pvt_cause_code::ast_cause, ast_cause2str(), ast_channel_dialed_causes_find(), ast_channel_lock, ast_channel_unlock, ast_copy_string(), AST_DECLARE_APP_ARGS, ast_log, AST_STANDARD_APP_ARGS, ast_strdupa, ast_control_pvt_cause_code::code, LOG_WARNING, and type.
 {
    char *parms;
    struct ast_control_pvt_cause_code *cause_code;
    int res = 0;
    AST_DECLARE_APP_ARGS(args,
       AST_APP_ARG(channel);   /*!< Channel name */
       AST_APP_ARG(type);   /*!< Type of information requested (ast or tech) */
       );
    /* Ensure that the buffer is empty */
    *buf = 0;
    if (!chan) {
       return -1;
    }
    parms = ast_strdupa(data);
    AST_STANDARD_APP_ARGS(args, parms);
    if (args.argc != 2) {
       /* Must have two arguments. */
       ast_log(LOG_WARNING, "The HANGUPCAUSE function must have 2 parameters, not %u\n", args.argc);
       return -1;
    }
    ast_channel_lock(chan);
    cause_code = ast_channel_dialed_causes_find(chan, args.channel);
    ast_channel_unlock(chan);
    if (!cause_code) {
       ast_log(LOG_WARNING, "Unable to find information for channel %s\n", args.channel);
       return -1;
    }
    if (!strcmp(args.type, "ast")) {
       ast_copy_string(buf, ast_cause2str(cause_code->ast_cause), len);
    } else if (!strcmp(args.type, "tech")) {
       ast_copy_string(buf, cause_code->code, len);
    } else {
       ast_log(LOG_WARNING, "Information type not recognized (%s)\n", args.type);
       res = -1;
    }
    ao2_ref(cause_code, -1);
    return res;
 }
load_module()
static int load_module (void) static
Definition at line 245 of file func_hangupcause.c.
References app, ast_custom_function_register, AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, ast_register_application_xml, and hangupcause_clear_exec().
 {
    int res;
    res = ast_custom_function_register(&hangupcause_function);
    res |= ast_custom_function_register(&hangupcause_keys_function);
    res |= ast_register_application_xml(app, hangupcause_clear_exec);
    return res ? AST_MODULE_LOAD_DECLINE : AST_MODULE_LOAD_SUCCESS;
 }
unload_module()
static int unload_module (void) static
Definition at line 228 of file func_hangupcause.c.
References app, ast_custom_function_unregister(), and ast_unregister_application().
 {
    int res;
    res = ast_custom_function_unregister(&hangupcause_function);
    res |= ast_custom_function_unregister(&hangupcause_keys_function);
    res |= ast_unregister_application(app);
    return res;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "HANGUPCAUSE related functions and applications" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, } static
Definition at line 256 of file func_hangupcause.c.
app
const char app[] = "HangupCauseClear" static
Definition at line 219 of file func_hangupcause.c.
Referenced by load_module(), and unload_module().
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 256 of file func_hangupcause.c.
hangupcause_function
struct ast_custom_function hangupcause_function static
Initial value:
= {
   .name = "HANGUPCAUSE",
   .read = hangupcause_read,
}
Definition at line 209 of file func_hangupcause.c.
hangupcause_keys_function
struct ast_custom_function hangupcause_keys_function static
Initial value:
= {
   .name = "HANGUPCAUSE_KEYS",
   .read = hangupcause_keys_read,
}
Definition at line 214 of file func_hangupcause.c.