Asterisk - The Open Source Telephony Project: cel_manager.c File Reference
cel_manager.c File Reference
Asterisk Channel Event records.
#include "asterisk.h"
#include "asterisk/channel.h"
#include "asterisk/cel.h"
#include "asterisk/module.h"
#include "asterisk/logger.h"
#include "asterisk/utils.h"
#include "asterisk/manager.h"
#include "asterisk/config.h"
Macros
#define CEL_AMI_ENABLED_DEFAULT 0
AMI CEL is off by default.
#define CEL_SHOW_USERDEF_DEFAULT 0
show_user_def is off by default
#define MANAGER_BACKEND_NAME "Manager Event Logging"
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int load_config (int reload)
static int load_module (void)
static void manager_log (struct ast_event *event)
static int reload (void)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Asterisk Manager Interface CEL Backend" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .reload = reload, .load_pri = AST_MODPRI_CDR_DRIVER, .requires = "cel", }
static const struct ast_module_info * ast_module_info = &__mod_info
static unsigned char cel_show_user_def
static const char CONF_FILE [] = "cel.conf"
static const char DATE_FORMAT [] = "%Y-%m-%d %T"
static int enablecel
Detailed Description
Asterisk Channel Event records.
See also
CDR - Call Data Records and billing
AMI - The Manager Interface
AMI configuration
Definition in file cel_manager.c.
Macro Definition Documentation
CEL_AMI_ENABLED_DEFAULT
#define CEL_AMI_ENABLED_DEFAULT 0
AMI CEL is off by default.
Definition at line 211 of file cel_manager.c.
Referenced by load_config().
CEL_SHOW_USERDEF_DEFAULT
#define CEL_SHOW_USERDEF_DEFAULT 0
show_user_def is off by default
Definition at line 216 of file cel_manager.c.
Referenced by load_config().
MANAGER_BACKEND_NAME
#define MANAGER_BACKEND_NAME "Manager Event Logging"
Definition at line 218 of file cel_manager.c.
Referenced by load_config(), and unload_module().
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 384 of file cel_manager.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 384 of file cel_manager.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 384 of file cel_manager.c.
load_config()
static int load_config (int reload) static
Definition at line 300 of file cel_manager.c.
References ast_category_browse(), ast_cel_backend_register(), ast_cel_backend_unregister(), ast_config_destroy(), ast_config_load, ast_log, ast_true(), ast_variable_browse(), CEL_AMI_ENABLED_DEFAULT, cel_show_user_def, CEL_SHOW_USERDEF_DEFAULT, CONF_FILE, CONFIG_FLAG_FILEUNCHANGED, CONFIG_STATUS_FILEINVALID, CONFIG_STATUS_FILEUNCHANGED, enablecel, LOG_ERROR, LOG_NOTICE, LOG_WARNING, MANAGER_BACKEND_NAME, manager_log(), ast_variable::name, ast_variable::next, NULL, and ast_variable::value.
Referenced by load_module(), and reload().
 {
    const char *cat = NULL;
    struct ast_config *cfg;
    struct ast_flags config_flags = { reload ? CONFIG_FLAG_FILEUNCHANGED : 0 };
    struct ast_variable *v;
    int newenablecel = CEL_AMI_ENABLED_DEFAULT;
    int new_cel_show_user_def = CEL_SHOW_USERDEF_DEFAULT;
    cfg = ast_config_load(CONF_FILE, config_flags);
    if (cfg == CONFIG_STATUS_FILEUNCHANGED) {
       return 0;
    }
    if (cfg == CONFIG_STATUS_FILEINVALID) {
       ast_log(LOG_WARNING, "Configuration file '%s' is invalid. CEL manager Module not activated.\n",
          CONF_FILE);
       enablecel = 0;
       return -1;
    } else if (!cfg) {
       ast_log(LOG_WARNING, "Failed to load configuration file. CEL manager Module not activated.\n");
       enablecel = 0;
       return -1;
    }
    while ((cat = ast_category_browse(cfg, cat))) {
       if (strcasecmp(cat, "manager")) {
          continue;
       }
       for (v = ast_variable_browse(cfg, cat); v; v = v->next) {
          if (!strcasecmp(v->name, "enabled")) {
             newenablecel = ast_true(v->value) ? 1 : 0;
          } else if (!strcasecmp(v->name, "show_user_defined")) {
             new_cel_show_user_def = ast_true(v->value) ? 1 : 0;
          } else {
             ast_log(LOG_NOTICE, "Unknown option '%s' specified "
                   "for cel_manager.\n", v->name);
          }
       }
    }
    ast_config_destroy(cfg);
    cel_show_user_def = new_cel_show_user_def;
    if (enablecel && !newenablecel) {
       ast_cel_backend_unregister(MANAGER_BACKEND_NAME);
    } else if (!enablecel && newenablecel) {
       if (ast_cel_backend_register(MANAGER_BACKEND_NAME, manager_log)) {
          ast_log(LOG_ERROR, "Unable to register Asterisk Call Manager CEL handling\n");
       }
    }
    enablecel = newenablecel;
    return 0;
 }
load_module()
static int load_module (void) static
Definition at line 363 of file cel_manager.c.
References AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, and load_config().
Referenced by reload().
 {
    if (load_config(0)) {
       return AST_MODULE_LOAD_DECLINE;
    }
    return AST_MODULE_LOAD_SUCCESS;
 }
manager_log()
static void manager_log (struct ast_event * event) static
Definition at line 223 of file cel_manager.c.
References ast_cel_event_record::account_code, ast_cel_event_record::amaflag, ast_cel_event_record::application_data, ast_cel_event_record::application_name, AST_CEL_EVENT_RECORD_VERSION, ast_cel_fill_record(), AST_CEL_USER_DEFINED, ast_channel_amaflags2string(), ast_localtime(), ast_strftime(), ast_cel_event_record::caller_id_ani, ast_cel_event_record::caller_id_dnid, ast_cel_event_record::caller_id_name, ast_cel_event_record::caller_id_num, ast_cel_event_record::caller_id_rdnis, cel_show_user_def, ast_cel_event_record::channel_name, ast_cel_event_record::context, DATE_FORMAT, enablecel, EVENT_FLAG_CALL, ast_cel_event_record::event_name, ast_cel_event_record::event_time, ast_cel_event_record::event_type, ast_cel_event_record::extension, ast_cel_event_record::extra, ast_cel_event_record::linked_id, manager_event, NULL, ast_cel_event_record::peer, ast_cel_event_record::peer_account, ast_cel_event_record::unique_id, ast_cel_event_record::user_defined_name, ast_cel_event_record::user_field, and ast_cel_event_record::version.
Referenced by load_config().
 {
    struct ast_tm timeresult;
    char start_time[80] = "";
    char user_defined_header[160];
    const char *event_name;
    struct ast_cel_event_record record = {
       .version = AST_CEL_EVENT_RECORD_VERSION,
    };
    if (!enablecel) {
       return;
    }
    if (ast_cel_fill_record(event, &record)) {
       return;
    }
    ast_localtime(&record.event_time, &timeresult, NULL);
    ast_strftime(start_time, sizeof(start_time), DATE_FORMAT, &timeresult);
    event_name = record.event_name;
    user_defined_header[0] = '\0';
    if (record.event_type == AST_CEL_USER_DEFINED) {
       if (cel_show_user_def) {
          snprintf(user_defined_header, sizeof(user_defined_header),
             "UserDefType: %s\r\n", record.user_defined_name);
       } else {
          event_name = record.user_defined_name;
       }
    }
    manager_event(EVENT_FLAG_CALL, "CEL",
       "EventName: %s\r\n"
       "AccountCode: %s\r\n"
       "CallerIDnum: %s\r\n"
       "CallerIDname: %s\r\n"
       "CallerIDani: %s\r\n"
       "CallerIDrdnis: %s\r\n"
       "CallerIDdnid: %s\r\n"
       "Exten: %s\r\n"
       "Context: %s\r\n"
       "Channel: %s\r\n"
       "Application: %s\r\n"
       "AppData: %s\r\n"
       "EventTime: %s\r\n"
       "AMAFlags: %s\r\n"
       "UniqueID: %s\r\n"
       "LinkedID: %s\r\n"
       "Userfield: %s\r\n"
       "Peer: %s\r\n"
       "PeerAccount: %s\r\n"
       "%s"
       "Extra: %s\r\n",
       event_name,
       record.account_code,
       record.caller_id_num,
       record.caller_id_name,
       record.caller_id_ani,
       record.caller_id_rdnis,
       record.caller_id_dnid,
       record.extension,
       record.context,
       record.channel_name,
       record.application_name,
       record.application_data,
       start_time,
       ast_channel_amaflags2string(record.amaflag),
       record.unique_id,
       record.linked_id,
       record.user_field,
       record.peer,
       record.peer_account,
       user_defined_header,
       record.extra);
 }
reload()
static int reload (void) static
Definition at line 372 of file cel_manager.c.
References AST_MODFLAG_LOAD_ORDER, AST_MODPRI_CDR_DRIVER, AST_MODULE_INFO(), AST_MODULE_SUPPORT_CORE, ASTERISK_GPL_KEY, load_config(), load_module(), and unload_module().
 {
    return load_config(1);
 }
unload_module()
static int unload_module (void) static
Definition at line 357 of file cel_manager.c.
References ast_cel_backend_unregister(), and MANAGER_BACKEND_NAME.
Referenced by reload().
 {
    ast_cel_backend_unregister(MANAGER_BACKEND_NAME);
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Asterisk Manager Interface CEL Backend" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .reload = reload, .load_pri = AST_MODPRI_CDR_DRIVER, .requires = "cel", } static
Definition at line 384 of file cel_manager.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 384 of file cel_manager.c.
cel_show_user_def
unsigned char cel_show_user_def static
TRUE if we should set the EventName header to USER_DEFINED on user events.
Definition at line 221 of file cel_manager.c.
Referenced by load_config(), and manager_log().
CONF_FILE
const char CONF_FILE[] = "cel.conf" static
Definition at line 208 of file cel_manager.c.
Referenced by load_config().
DATE_FORMAT
const char DATE_FORMAT[] = "%Y-%m-%d %T" static
Definition at line 206 of file cel_manager.c.
Referenced by manager_log().
enablecel
int enablecel static
Definition at line 213 of file cel_manager.c.
Referenced by load_config(), and manager_log().