Asterisk - The Open Source Telephony Project: term.c File Reference
term.c File Reference
Terminal Routines.
#include "asterisk.h"
#include "asterisk/_private.h"
#include <sys/time.h>
#include <signal.h>
#include <sys/stat.h>
#include <fcntl.h>
#include "asterisk/term.h"
#include "asterisk/lock.h"
#include "asterisk/utils.h"
#include "asterisk/threadstorage.h"
Data Structures
struct commonbuf
Functions
static void __init_commonbuf (void)
const char * ast_term_color (int fgcolor, int bgcolor)
Return a color sequence string.
int ast_term_color_code (struct ast_str **str, int fgcolor, int bgcolor)
Append a color sequence to an ast_str.
int ast_term_init (void)
const char * ast_term_reset (void)
Returns the terminal reset code.
static void check_bgcolor (int *bgcolor)
static int check_colors_allowed (void)
static void check_fgcolor (int *fgcolor, int *attr)
static short convshort (char *s)
static int opposite (int color)
char * term_color (char *outbuf, const char *inbuf, int fgcolor, int bgcolor, int maxout)
Colorize a specified string by adding terminal color codes.
char * term_color_code (char *outbuf, int fgcolor, int bgcolor, int maxout)
Write a color sequence to a string.
const char * term_end (void)
void term_filter_escapes (char *line)
const char * term_quit (void)
char * term_strip (char *outbuf, const char *inbuf, int maxout)
Remove colorings from a specified string.
Variables
static struct ast_threadstorage commonbuf = { .once = PTHREAD_ONCE_INIT , .key_init = __init_commonbuf , .custom_init = NULL , }
static char enddata [80] = ""
static char quitdata [80] = ""
static const char *const termpath []
static int vt100compat
Detailed Description
Terminal Routines.
Author
Mark Spencer marks.nosp@m.ter@.nosp@m.digiu.nosp@m.m.co.nosp@m.m
Definition in file term.c.
Function Documentation
__init_commonbuf()
static void __init_commonbuf (void) static
Definition at line 55 of file term.c.
 {
ast_term_color()
const char* ast_term_color (int fgcolor, int bgcolor)
Return a color sequence string.
Parameters
fgcolor foreground color
bgcolor background color
Note
This function may be called up to 15 times within the arguments to a single function without the danger of overwriting a common buffer.
Returns
A color sequence string, or the empty string, on error
Definition at line 290 of file term.c.
References AST_TERM_MAX_ESCAPE_CHARS, AST_TERM_MAX_ROTATING_BUFFERS, ast_threadstorage_get(), buf, commonbuf::buffer, term_color_code(), and commonbuf::which.
Referenced by print_app_docs(), print_queue(), and set_header().
 {
    struct commonbuf *cb = ast_threadstorage_get(&commonbuf, sizeof(*cb));
    char *buf;
    if (!cb) {
       return "";
    }
    buf = cb->buffer[cb->which++];
    if (cb->which == AST_TERM_MAX_ROTATING_BUFFERS) {
       cb->which = 0;
    }
    return term_color_code(buf, fgcolor, bgcolor, AST_TERM_MAX_ESCAPE_CHARS);
 }
ast_term_color_code()
int ast_term_color_code (struct ast_str ** str, int fgcolor, int bgcolor)
Append a color sequence to an ast_str.
Parameters
str The string to append to
fgcolor foreground color
bgcolor background color
Return values
0 success
-1 failure
Definition at line 245 of file term.c.
References ast_opt_force_black_background, ast_str_append(), check_bgcolor(), check_colors_allowed(), check_fgcolor(), COLOR_BLACK, and ESC.
Referenced by ast_xmldoc_printable(), and cli_prompt().
 {
    int attr = 0;
    if (!check_colors_allowed()) {
       return -1;
    }
    check_fgcolor(&fgcolor, &attr);
    check_bgcolor(&bgcolor);
    if (ast_opt_force_black_background) {
       ast_str_append(str, 0, "%c[%d;%d;%dm", ESC, attr, fgcolor, COLOR_BLACK + 10);
    } else if (bgcolor) {
       ast_str_append(str, 0, "%c[%d;%d;%dm", ESC, attr, fgcolor, bgcolor + 10);
    } else {
       ast_str_append(str, 0, "%c[%d;%dm", ESC, attr, fgcolor);
    }
    return 0;
 }
ast_term_init()
int ast_term_init (void)
Provided by term.c
Definition at line 92 of file term.c.
References ast_opt_console, ast_opt_force_black_background, ast_opt_light_background, ast_opt_no_color, ATTR_RESET, commonbuf::buffer, COLOR_BLACK, COLOR_WHITE, convshort(), end, enddata, ESC, NULL, quitdata, termpath, and vt100compat.
Referenced by ast_remotecontrol(), asterisk_daemon(), and main().
 {
    char *term = getenv("TERM");
    char termfile[256] = "";
    char buffer[512] = "";
    int termfd = -1, parseokay = 0, i;
    if (ast_opt_no_color) {
       return 0;
    }
    if (!ast_opt_console) {
       /* If any remote console is not compatible, we'll strip the color codes at that point */
       vt100compat = 1;
       goto end;
    }
    if (!term) {
       return 0;
    }
    for (i = 0;; i++) {
       if (termpath[i] == NULL) {
          break;
       }
       snprintf(termfile, sizeof(termfile), "%s/%c/%s", termpath[i], *term, term);
       termfd = open(termfile, O_RDONLY);
       if (termfd > -1) {
          break;
       }
    }
    if (termfd > -1) {
       int actsize = read(termfd, buffer, sizeof(buffer) - 1);
       short sz_names = convshort(buffer + 2);
       short sz_bools = convshort(buffer + 4);
       short n_nums   = convshort(buffer + 6);
       /* if ((sz_names + sz_bools) & 1)
          sz_bools++; */
       if (sz_names + sz_bools + n_nums < actsize) {
          /* Offset 13 is defined in /usr/include/term.h, though we do not
           * include it here, as it conflicts with include/asterisk/term.h */
          short max_colors = convshort(buffer + 12 + sz_names + sz_bools + 13 * 2);
          if (max_colors > 0) {
             vt100compat = 1;
          }
          parseokay = 1;
       }
       close(termfd);
    }
    if (!parseokay) {
       /* These comparisons should not be substrings nor case-insensitive, as
        * terminal types are very particular about how they treat suffixes and
        * capitalization.  For example, terminal type 'linux-m' does NOT
        * support color, while 'linux' does.  Not even all vt100* terminals
        * support color, either (e.g. 'vt100+fnkeys'). */
       if (!strcmp(term, "linux")) {
          vt100compat = 1;
       } else if (!strcmp(term, "xterm")) {
          vt100compat = 1;
       } else if (!strcmp(term, "xterm-color")) {
          vt100compat = 1;
       } else if (!strcmp(term, "xterm-256color")) {
          vt100compat = 1;
       } else if (!strncmp(term, "Eterm", 5)) {
          /* Both entries which start with Eterm support color */
          vt100compat = 1;
       } else if (!strcmp(term, "vt100")) {
          vt100compat = 1;
       } else if (!strncmp(term, "crt", 3)) {
          /* Both crt terminals support color */
          vt100compat = 1;
       }
    }
 end:
    if (vt100compat) {
       /* Make commands show up in nice colors */
       if (ast_opt_light_background) {
          snprintf(enddata, sizeof(enddata), "%c[%dm", ESC, COLOR_BLACK);
       } else if (ast_opt_force_black_background) {
          snprintf(enddata, sizeof(enddata), "%c[%d;%d;%dm", ESC, ATTR_RESET, COLOR_WHITE, COLOR_BLACK + 10);
       } else {
          snprintf(enddata, sizeof(enddata), "%c[%dm", ESC, ATTR_RESET);
       }
       snprintf(quitdata, sizeof(quitdata), "%c[%dm", ESC, ATTR_RESET);
    }
    return 0;
 }
ast_term_reset()
const char* ast_term_reset (void)
Returns the terminal reset code.
Returns
String which, when sent to the screen, resets the terminal colors
Definition at line 306 of file term.c.
References term_end().
Referenced by ast_xmldoc_printable(), cli_show_module_options(), print_app_docs(), print_queue(), and set_header().
 {
    return term_end();
 }
check_bgcolor()
static void check_bgcolor (int * bgcolor) static
Definition at line 233 of file term.c.
Referenced by ast_term_color_code(), and term_color_code().
 {
    if (*bgcolor) {
       *bgcolor &= ~128;
    }
 }
check_colors_allowed()
static int check_colors_allowed (void) static
Definition at line 240 of file term.c.
References vt100compat.
Referenced by ast_term_color_code(), and term_color_code().
 {
    return vt100compat;
 }
check_fgcolor()
static void check_fgcolor (int * fgcolor, int * attr) static
Definition at line 221 of file term.c.
References ast_opt_light_background, ATTR_BRIGHT, and opposite().
Referenced by ast_term_color_code(), and term_color_code().
 {
    *attr = ast_opt_light_background ? 0 : ATTR_BRIGHT;
    if (*fgcolor & 128) {
       *fgcolor &= ~128;
    }
    if (ast_opt_light_background) {
       *fgcolor = opposite(*fgcolor);
    }
 }
convshort()
static short convshort (char * s) static
Definition at line 77 of file term.c.
References a, and b.
Referenced by ast_term_init().
 {
    register int a, b;
    a = (int) s[0] & 0377;
    b = (int) s[1] & 0377;
    if (a == 0377 && b == 0377)
       return -1;
    if (a == 0376 && b == 0377)
       return -2;
    return a + b * 256;
 }
opposite()
static int opposite (int color) static
Definition at line 62 of file term.c.
References COLOR_BLACK, COLOR_BLUE, COLOR_BROWN, COLOR_CYAN, COLOR_GREEN, COLOR_MAGENTA, and COLOR_RED.
Referenced by check_fgcolor(), and term_color().
 {
    int lookup[] = {
       /* BLACK */ COLOR_BLACK,
       /* RED */ COLOR_MAGENTA,
       /* GREEN */ COLOR_GREEN,
       /* BROWN */ COLOR_BROWN,
       /* BLUE */ COLOR_CYAN,
       /* MAGENTA */ COLOR_RED,
       /* CYAN */ COLOR_BLUE,
       /* WHITE */ COLOR_BLACK };
    return color ? lookup[color - 30] : 0;
 }
term_color()
char* term_color (char * outbuf, const char * inbuf, int fgcolor, int bgcolor, int maxout)
Colorize a specified string by adding terminal color codes.
Parameters
outbuf Result buffer
inbuf Starting string
fgcolor Foreground color, specified as one of the constants in include/asterisk/term.h. Use '0' if the want the normal terminal foreground color.
bgcolor Background color, specified as one of the constants in include/asterisk/term.h. Use '0' if you want the normal terminal background color.
maxout Maximum size of outbuf
Returns
outbuf
Deprecated:
Due to the necessity of pre-sizing a result buffer, new code should avoid using this function in preference to ast_term_color_code() or ast_term_color().
Definition at line 184 of file term.c.
References ast_copy_string(), ast_opt_force_black_background, ast_opt_light_background, ATTR_BRIGHT, COLOR_BLACK, ESC, opposite(), term_end(), and vt100compat.
Referenced by __ast_register_translator(), ast_frame_dump(), ast_unregister_translator(), cli_show_module_options(), cli_show_module_type(), handle_cli_agi_show(), handle_dahdi_show_cadences(), handle_show_function(), handle_showmancmd(), lua_pbx_exec(), print_event_instance(), realtime_exec(), show_config_description(), start_resource(), test_cli_show_results(), and test_execute_multiple().
 {
    int attr = 0;
    if (!vt100compat) {
       ast_copy_string(outbuf, inbuf, maxout);
       return outbuf;
    }
    if (!fgcolor) {
       ast_copy_string(outbuf, inbuf, maxout);
       return outbuf;
    }
    if (fgcolor & 128) {
       attr = ast_opt_light_background ? 0 : ATTR_BRIGHT;
       fgcolor &= ~128;
    }
    if (bgcolor) {
       bgcolor &= ~128;
    }
    if (ast_opt_light_background) {
       fgcolor = opposite(fgcolor);
    }
    if (ast_opt_force_black_background) {
       if (!bgcolor) {
          bgcolor = COLOR_BLACK;
       }
       snprintf(outbuf, maxout, "%c[%d;%d;%dm%s%s", ESC, attr, fgcolor, bgcolor + 10, inbuf, term_end());
    } else {
       snprintf(outbuf, maxout, "%c[%d;%dm%s%s", ESC, attr, fgcolor, inbuf, term_end());
    }
    return outbuf;
 }
term_color_code()
char* term_color_code (char * outbuf, int fgcolor, int bgcolor, int maxout)
Write a color sequence to a string.
Parameters
outbuf the location to write to
fgcolor foreground color
bgcolor background color
maxout maximum number of characters to write
Deprecated:
You should use ast_term_color_code or ast_term_color, instead.
Returns
outbuf
Definition at line 267 of file term.c.
References ast_opt_force_black_background, check_bgcolor(), check_colors_allowed(), check_fgcolor(), COLOR_BLACK, and ESC.
Referenced by ast_term_color().
 {
    int attr = 0;
    if (!check_colors_allowed()) {
       *outbuf = '\0';
       return outbuf;
    }
    check_fgcolor(&fgcolor, &attr);
    check_bgcolor(&bgcolor);
    if (ast_opt_force_black_background) {
       snprintf(outbuf, maxout, "%c[%d;%d;%dm", ESC, attr, fgcolor, COLOR_BLACK + 10);
    } else if (bgcolor) {
       snprintf(outbuf, maxout, "%c[%d;%d;%dm", ESC, attr, fgcolor, bgcolor + 10);
    } else {
       snprintf(outbuf, maxout, "%c[%d;%dm", ESC, attr, fgcolor);
    }
    return outbuf;
 }
term_end()
const char* term_end (void)
Definition at line 356 of file term.c.
References enddata.
Referenced by ast_remotecontrol(), ast_term_reset(), asterisk_daemon(), consolehandler(), main(), and term_color().
 {
    return enddata;
 }
term_filter_escapes()
void term_filter_escapes (char * line)
Definition at line 334 of file term.c.
References ESC, and len().
 {
    int i;
    int len = strlen(line);
    for (i = 0; i < len; i++) {
       if (line[i] != ESC)
          continue;
       if ((i < (len - 2)) &&
           (line[i + 1] == 0x5B)) {
          switch (line[i + 2]) {
          case 0x30:
          case 0x31:
          case 0x33:
             continue;
          }
       }
       /* replace ESC with a space */
       line[i] = ' ';
    }
 }
term_quit()
const char* term_quit (void)
Definition at line 361 of file term.c.
References quitdata.
Referenced by ast_el_read_char(), check_init(), main(), and really_quit().
 {
    return quitdata;
 }
term_strip()
char* term_strip (char * outbuf, const char * inbuf, int maxout)
Remove colorings from a specified string.
Parameters
outbuf the location to write to
inbuf the original string
maxout the available size of outbuf
Returns
outbuf
Definition at line 311 of file term.c.
References ESC, and inbuf().
Referenced by action_command(), format_log_default(), format_log_json(), and format_log_plain().
 {
    char *outbuf_ptr = outbuf;
    const char *inbuf_ptr = inbuf;
    while (outbuf_ptr < outbuf + maxout) {
       switch (*inbuf_ptr) {
          case ESC:
             while (*inbuf_ptr && (*inbuf_ptr != 'm'))
                inbuf_ptr++;
             break;
          default:
             *outbuf_ptr = *inbuf_ptr;
             outbuf_ptr++;
       }
       if (! *inbuf_ptr)
          break;
       inbuf_ptr++;
    }
    return outbuf;
 }
Variable Documentation
commonbuf
struct ast_threadstorage commonbuf = { .once = PTHREAD_ONCE_INIT , .key_init = __init_commonbuf , .custom_init = NULL , } static
Definition at line 55 of file term.c.
enddata
char enddata[80] = "" static
Definition at line 45 of file term.c.
Referenced by ast_term_init(), and term_end().
quitdata
char quitdata[80] = "" static
Definition at line 46 of file term.c.
Referenced by ast_term_init(), and term_quit().
termpath
const char* const termpath[] static
Definition at line 48 of file term.c.
Referenced by ast_term_init().
vt100compat
int vt100compat static
Definition at line 43 of file term.c.
Referenced by ast_term_init(), check_colors_allowed(), and term_color().