Asterisk - The Open Source Telephony Project: test_channel_feature_hooks.c File Reference
test_channel_feature_hooks.c File Reference
Channel features unit tests.
#include "asterisk.h"
#include "asterisk/module.h"
#include "asterisk/test.h"
#include "asterisk/channel.h"
#include "asterisk/time.h"
#include "asterisk/bridge.h"
#include "asterisk/bridge_basic.h"
#include "asterisk/features.h"
#include "asterisk/format_cache.h"
Macros
#define CHANNEL_TECH_NAME "FeaturesTestChannel"
#define HANGUP_CHANNEL(channel)
Hang up a test channel safely.
#define START_ALICE(channel) START_CHANNEL(channel, "Alice", "100")
Create a test_features_chan_tech for Alice.
#define START_BOB(channel) START_CHANNEL(channel, "Bob", "200")
Create a test_features_chan_tech for Bob.
#define START_CHANNEL(channel, name, number)
#define TEST_BACKEND_NAME "Features Test Logging"
#define TEST_CATEGORY "/channels/features/"
#define TEST_CHANNEL_FORMAT ast_format_slin
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
AST_TEST_DEFINE (test_features_channel_dtmf)
AST_TEST_DEFINE (test_features_channel_interval)
static int feature_callback (struct ast_bridge_channel *bridge_channel, void *obj)
static int load_module (void)
static void safe_bridge_destroy (struct ast_bridge *bridge)
static void safe_channel_release (struct ast_channel *chan)
static void stream_periodic_frames (struct ast_channel *chan, int ms, int interval_ms)
static void test_nanosleep (int secs, long nanosecs)
static int unload_module (void)
static void wait_for_bridged (struct ast_channel *channel)
Wait until a channel is bridged.
static void wait_for_unbridged (struct ast_channel *channel)
Wait until a channel is not bridged.
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Bridge Features Unit Tests" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, }
static const struct ast_module_info * ast_module_info = &__mod_info
static struct ast_channel_tech test_features_chan_tech
A channel technology used for the unit tests.
Detailed Description
Channel features unit tests.
Author
Kinsey Moore kmoor.nosp@m.e@di.nosp@m.gium..nosp@m.com
Definition in file test_channel_feature_hooks.c.
Macro Definition Documentation
CHANNEL_TECH_NAME
#define CHANNEL_TECH_NAME "FeaturesTestChannel"
Definition at line 45 of file test_channel_feature_hooks.c.
HANGUP_CHANNEL
#define HANGUP_CHANNEL (channel)
Hang up a test channel safely.
Definition at line 107 of file test_channel_feature_hooks.c.
Referenced by AST_TEST_DEFINE().
START_ALICE
#define START_ALICE (channel) START_CHANNEL(channel, "Alice", "100")
Create a test_features_chan_tech for Alice.
Definition at line 90 of file test_channel_feature_hooks.c.
Referenced by AST_TEST_DEFINE().
START_BOB
#define START_BOB (channel) START_CHANNEL(channel, "Bob", "200")
Create a test_features_chan_tech for Bob.
Definition at line 93 of file test_channel_feature_hooks.c.
Referenced by AST_TEST_DEFINE().
START_CHANNEL
#define START_CHANNEL (channel, name, number)
Definition at line 95 of file test_channel_feature_hooks.c.
TEST_BACKEND_NAME
#define TEST_BACKEND_NAME "Features Test Logging"
Definition at line 47 of file test_channel_feature_hooks.c.
TEST_CATEGORY
#define TEST_CATEGORY "/channels/features/"
Definition at line 43 of file test_channel_feature_hooks.c.
Referenced by AST_TEST_DEFINE().
TEST_CHANNEL_FORMAT
#define TEST_CHANNEL_FORMAT ast_format_slin
Definition at line 49 of file test_channel_feature_hooks.c.
Referenced by load_module().
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 358 of file test_channel_feature_hooks.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 358 of file test_channel_feature_hooks.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 358 of file test_channel_feature_hooks.c.
AST_TEST_DEFINE() [1/2]
AST_TEST_DEFINE (test_features_channel_dtmf)
Definition at line 160 of file test_channel_feature_hooks.c.
References ast_bridge_basic_new(), ast_bridge_depart(), ast_bridge_dtmf_hook(), ast_bridge_features_cleanup(), ast_bridge_features_init(), ast_bridge_impart(), AST_BRIDGE_IMPART_CHAN_DEPARTABLE, ast_channel_feature_hooks_append(), AST_FRAME_DTMF, ast_queue_frame(), AST_TEST_NOT_RUN, AST_TEST_PASS, feature_callback(), HANGUP_CHANNEL, sip_to_pjsip::info(), ast_frame_subclass::integer, ast_frame::len, NULL, RAII_VAR, safe_bridge_destroy(), safe_channel_release(), START_ALICE, START_BOB, stream_periodic_frames(), ast_frame::subclass, TEST_CATEGORY, TEST_EXECUTE, TEST_INIT, wait_for_bridged(), and wait_for_unbridged().
 {
    RAII_VAR(struct ast_channel *, chan_alice, NULL, safe_channel_release);
    RAII_VAR(struct ast_channel *, chan_bob, NULL, safe_channel_release);
    RAII_VAR(struct ast_bridge *, bridge1, NULL, safe_bridge_destroy);
    RAII_VAR(struct ast_bridge *, bridge2, NULL, safe_bridge_destroy);
    struct ast_bridge_features features;
    int callback_executed = 0;
    struct ast_frame f = { AST_FRAME_DTMF, };
    switch (cmd) {
    case TEST_INIT:
       info->name = __func__;
       info->category = TEST_CATEGORY;
       info->summary = "Test running DTMF hooks on a channel via the feature hooks mechanism";
       info->description =
          "This test creates two channels, adds a DTMF hook to one, places them into\n"
          "a bridge, and verifies that the DTMF hook added to the channel feature\n"
          "hooks can be triggered once the channel is bridged.";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    /* Create the bridges */
    bridge1 = ast_bridge_basic_new();
    ast_test_validate(test, bridge1 != NULL);
    bridge2 = ast_bridge_basic_new();
    ast_test_validate(test, bridge2 != NULL);
    /* Create channels that will go into the bridge */
    START_ALICE(chan_alice);
    START_BOB(chan_bob);
    /* Setup the features and add them to alice */
    ast_bridge_features_init(&features);
    ast_test_validate(test, !ast_bridge_dtmf_hook(&features, "##**", feature_callback, &callback_executed, NULL, 0));
    ast_test_validate(test, !ast_channel_feature_hooks_append(chan_alice, &features));
    ast_bridge_features_cleanup(&features);
    /* Bridge the channels */
    ast_test_validate(test, !ast_bridge_impart(bridge1, chan_alice, NULL, NULL, AST_BRIDGE_IMPART_CHAN_DEPARTABLE));
    ast_test_validate(test, !ast_bridge_impart(bridge1, chan_bob, NULL, NULL, AST_BRIDGE_IMPART_CHAN_DEPARTABLE));
    wait_for_bridged(chan_alice);
    /* Execute the feature */
    f.len = 100;
    f.subclass.integer = '#';
    ast_queue_frame(chan_alice, &f);
    ast_queue_frame(chan_alice, &f);
    f.subclass.integer = '*';
    ast_queue_frame(chan_alice, &f);
    ast_queue_frame(chan_alice, &f);
    stream_periodic_frames(chan_alice, 1000, 20);
    /* Remove the channels from the bridge */
    ast_test_validate(test, !ast_bridge_depart(chan_alice));
    ast_test_validate(test, !ast_bridge_depart(chan_bob));
    wait_for_unbridged(chan_alice);
    /* Bridge the channels again to ensure that the feature hook remains on the channel */
    ast_test_validate(test, !ast_bridge_impart(bridge2, chan_alice, NULL, NULL, AST_BRIDGE_IMPART_CHAN_DEPARTABLE));
    ast_test_validate(test, !ast_bridge_impart(bridge2, chan_bob, NULL, NULL, AST_BRIDGE_IMPART_CHAN_DEPARTABLE));
    wait_for_bridged(chan_alice);
    /* Execute the feature */
    f.len = 100;
    f.subclass.integer = '#';
    ast_queue_frame(chan_alice, &f);
    ast_queue_frame(chan_alice, &f);
    f.subclass.integer = '*';
    ast_queue_frame(chan_alice, &f);
    ast_queue_frame(chan_alice, &f);
    stream_periodic_frames(chan_alice, 1000, 20);
    /* Remove the channels from the bridge */
    ast_test_validate(test, !ast_bridge_depart(chan_alice));
    ast_test_validate(test, !ast_bridge_depart(chan_bob));
    /* Hangup the channels */
    HANGUP_CHANNEL(chan_alice);
    HANGUP_CHANNEL(chan_bob);
    ast_test_validate(test, callback_executed == 2);
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [2/2]
AST_TEST_DEFINE (test_features_channel_interval)
Definition at line 253 of file test_channel_feature_hooks.c.
References ast_bridge_basic_new(), ast_bridge_depart(), ast_bridge_features_cleanup(), ast_bridge_features_init(), ast_bridge_impart(), AST_BRIDGE_IMPART_CHAN_DEPARTABLE, ast_bridge_interval_hook(), ast_channel_feature_hooks_append(), AST_TEST_NOT_RUN, AST_TEST_PASS, feature_callback(), HANGUP_CHANNEL, sip_to_pjsip::info(), NULL, RAII_VAR, safe_bridge_destroy(), safe_channel_release(), START_ALICE, START_BOB, TEST_CATEGORY, TEST_EXECUTE, TEST_INIT, test_nanosleep(), wait_for_bridged(), and wait_for_unbridged().
 {
    RAII_VAR(struct ast_channel *, chan_alice, NULL, safe_channel_release);
    RAII_VAR(struct ast_channel *, chan_bob, NULL, safe_channel_release);
    RAII_VAR(struct ast_bridge *, bridge1, NULL, safe_bridge_destroy);
    RAII_VAR(struct ast_bridge *, bridge2, NULL, safe_bridge_destroy);
    struct ast_bridge_features features;
    int callback_executed = 0;
    switch (cmd) {
    case TEST_INIT:
       info->name = __func__;
       info->category = TEST_CATEGORY;
       info->summary = "Test running interval hooks on a channel via the feature hooks mechanism";
       info->description =
          "This test creates two channels, adds an interval hook to one, places them\n"
          "into a bridge, and verifies that the interval hook added to the channel\n"
          "feature hooks is triggered once the channel is bridged.";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    /* Create the bridges */
    bridge1 = ast_bridge_basic_new();
    ast_test_validate(test, bridge1 != NULL);
    bridge2 = ast_bridge_basic_new();
    ast_test_validate(test, bridge2 != NULL);
    /* Create channels that will go into the bridge */
    START_ALICE(chan_alice);
    START_BOB(chan_bob);
    /* Setup the features and add them to alice */
    ast_bridge_features_init(&features);
    ast_test_validate(test, !ast_bridge_interval_hook(&features, 0, 1000, feature_callback, &callback_executed, NULL, 0));
    ast_test_validate(test, !ast_channel_feature_hooks_append(chan_alice, &features));
    ast_bridge_features_cleanup(&features);
    /* Bridge the channels */
    ast_test_validate(test, !ast_bridge_impart(bridge1, chan_alice, NULL, NULL, AST_BRIDGE_IMPART_CHAN_DEPARTABLE));
    ast_test_validate(test, !ast_bridge_impart(bridge1, chan_bob, NULL, NULL, AST_BRIDGE_IMPART_CHAN_DEPARTABLE));
    wait_for_bridged(chan_alice);
    /* Let the interval hook execute once */
    test_nanosleep(1, 500000000);
    /* Remove the channels from the bridge */
    ast_test_validate(test, !ast_bridge_depart(chan_alice));
    ast_test_validate(test, !ast_bridge_depart(chan_bob));
    wait_for_unbridged(chan_alice);
    ast_test_validate(test, callback_executed >= 1);
    callback_executed = 0;
    /* Bridge the channels again to ensure that the feature hook remains on the channel */
    ast_test_validate(test, !ast_bridge_impart(bridge2, chan_alice, NULL, NULL, AST_BRIDGE_IMPART_CHAN_DEPARTABLE));
    ast_test_validate(test, !ast_bridge_impart(bridge2, chan_bob, NULL, NULL, AST_BRIDGE_IMPART_CHAN_DEPARTABLE));
    wait_for_bridged(chan_alice);
    /* Let the interval hook execute once */
    test_nanosleep(1, 500000000);
    /* Remove the channels from the bridge */
    ast_test_validate(test, !ast_bridge_depart(chan_alice));
    ast_test_validate(test, !ast_bridge_depart(chan_bob));
    /* Hangup the channels */
    HANGUP_CHANNEL(chan_alice);
    HANGUP_CHANNEL(chan_bob);
    ast_test_validate(test, callback_executed >= 1);
    return AST_TEST_PASS;
 }
feature_callback()
static int feature_callback (struct ast_bridge_channel * bridge_channel, void * obj) static
Definition at line 130 of file test_channel_feature_hooks.c.
Referenced by AST_TEST_DEFINE().
 {
    int *callback_executed = obj;
    (*callback_executed)++;
    return 0;
 }
load_module()
static int load_module (void) static
Definition at line 344 of file test_channel_feature_hooks.c.
References ast_channel_register(), ast_format_cap_alloc, ast_format_cap_append, AST_FORMAT_CAP_FLAG_DEFAULT, AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, AST_TEST_REGISTER, ast_channel_tech::capabilities, and TEST_CHANNEL_FORMAT.
 {
    test_features_chan_tech.capabilities = ast_format_cap_alloc(AST_FORMAT_CAP_FLAG_DEFAULT);
    if (!test_features_chan_tech.capabilities) {
       return AST_MODULE_LOAD_DECLINE;
    }
    ast_format_cap_append(test_features_chan_tech.capabilities, TEST_CHANNEL_FORMAT, 0);
    ast_channel_register(&test_features_chan_tech);
    AST_TEST_REGISTER(test_features_channel_dtmf);
    AST_TEST_REGISTER(test_features_channel_interval);
    return AST_MODULE_LOAD_SUCCESS;
 }
safe_bridge_destroy()
static void safe_bridge_destroy (struct ast_bridge * bridge) static
Definition at line 122 of file test_channel_feature_hooks.c.
References ast_bridge_destroy().
Referenced by AST_TEST_DEFINE().
 {
    if (!bridge) {
       return;
    }
    ast_bridge_destroy(bridge, 0);
 }
safe_channel_release()
static void safe_channel_release (struct ast_channel * chan) static
Definition at line 114 of file test_channel_feature_hooks.c.
References ast_channel_release().
Referenced by AST_TEST_DEFINE().
 {
    if (!chan) {
       return;
    }
    ast_channel_release(chan);
 }
stream_periodic_frames()
static void stream_periodic_frames (struct ast_channel * chan, int ms, int interval_ms) static
Definition at line 138 of file test_channel_feature_hooks.c.
References ast_assert, ast_null_frame, ast_queue_frame(), NULL, and test_nanosleep().
Referenced by AST_TEST_DEFINE().
 {
    long nanosecs;
    ast_assert(chan != NULL);
    ast_assert(0 < ms);
    ast_assert(0 < interval_ms);
    nanosecs = interval_ms * 1000000L;
    while (0 < ms) {
       ast_queue_frame(chan, &ast_null_frame);
       if (interval_ms < ms) {
          ms -= interval_ms;
       } else {
          nanosecs = ms * 1000000L;
          ms = 0;
       }
       test_nanosleep(0, nanosecs);
    }
 }
test_nanosleep()
static void test_nanosleep (int secs, long nanosecs) static
Definition at line 57 of file test_channel_feature_hooks.c.
References errno.
Referenced by AST_TEST_DEFINE(), stream_periodic_frames(), wait_for_bridged(), and wait_for_unbridged().
 {
    struct timespec sleep_time = {secs, nanosecs};
    while ((nanosleep(&sleep_time, &sleep_time) == -1) && (errno == EINTR)) {
    }
 }
unload_module()
static int unload_module (void) static
Definition at line 332 of file test_channel_feature_hooks.c.
References ao2_cleanup, ast_channel_unregister(), AST_TEST_UNREGISTER, ast_channel_tech::capabilities, and NULL.
 {
    AST_TEST_UNREGISTER(test_features_channel_dtmf);
    AST_TEST_UNREGISTER(test_features_channel_interval);
    ast_channel_unregister(&test_features_chan_tech);
    ao2_cleanup(test_features_chan_tech.capabilities);
    test_features_chan_tech.capabilities = NULL;
    return 0;
 }
wait_for_bridged()
static void wait_for_bridged (struct ast_channel * channel) static
Wait until a channel is bridged.
Definition at line 66 of file test_channel_feature_hooks.c.
References ast_channel_is_bridged(), ast_channel_lock, ast_channel_unlock, and test_nanosleep().
Referenced by AST_TEST_DEFINE().
 {
    ast_channel_lock(channel);
    while (!ast_channel_is_bridged(channel)) {
       ast_channel_unlock(channel);
       test_nanosleep(0, 1000000);
       ast_channel_lock(channel);
    }
    ast_channel_unlock(channel);
 }
wait_for_unbridged()
static void wait_for_unbridged (struct ast_channel * channel) static
Wait until a channel is not bridged.
Definition at line 78 of file test_channel_feature_hooks.c.
References ast_channel_is_bridged(), ast_channel_lock, ast_channel_unlock, and test_nanosleep().
Referenced by AST_TEST_DEFINE().
 {
    ast_channel_lock(channel);
    while (ast_channel_is_bridged(channel)) {
       ast_channel_unlock(channel);
       test_nanosleep(0, 1000000);
       ast_channel_lock(channel);
    }
    ast_channel_unlock(channel);
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Bridge Features Unit Tests" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, } static
Definition at line 358 of file test_channel_feature_hooks.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 358 of file test_channel_feature_hooks.c.
test_features_chan_tech
struct ast_channel_tech test_features_chan_tech static
Initial value:
= {
   .type = CHANNEL_TECH_NAME,
   .description = "Mock channel technology for Features tests",
}
A channel technology used for the unit tests.
Definition at line 52 of file test_channel_feature_hooks.c.