Asterisk - The Open Source Telephony Project: muted.c File Reference
muted.c File Reference
Mute Daemon.
#include "asterisk/autoconfig.h"
#include <stdio.h>
#include <errno.h>
#include <stdlib.h>
#include <unistd.h>
#include <fcntl.h>
#include <string.h>
#include <netdb.h>
#include <sys/socket.h>
#include <sys/ioctl.h>
#include <netinet/in.h>
#include <arpa/inet.h>
Data Structures
struct channel
struct subchannel
Macros
#define ast_strlen_zero(a) (!(*(a)))
Functions
static void add_channel (char *tech, char *location)
static void append_sub (struct channel *chan, char *name)
static void check_mute (void)
static int connect_asterisk (void)
static void delete_sub (struct channel *chan, char *name)
static struct channel * find_channel (char *channel)
static char * get_line (void)
static int getvol (void)
static void hangup_chan (char *channel)
static int load_config (void)
static int login_asterisk (void)
int main (int argc, char *argv[])
static void mute (void)
static int mutedlevel (int orig, int level)
static void offhook_chan (char *channel)
static int open_mixer (void)
static int setvol (int vol)
static void unmute (void)
static void usage (void)
static int wait_event (void)
Variables
static FILE * astf
static struct channel * channels
static char * config = "/etc/asterisk/muted.conf"
static int debug = 0
static char host [256] = ""
static int mixchan = SOUND_MIXER_VOLUME
static int mixfd
static int muted = 0
static int mutelevel = 20
static int mutevol = 0
static int needfork = 1
static int oldvol = 0
static char pass [256] = ""
static int smoothfade = 0
static int stepsize = 3
static char user [256] = ""
Detailed Description
Mute Daemon.
Author
Mark Spencer marks.nosp@m.ter@.nosp@m.digiu.nosp@m.m.co.nosp@m.m
Updated for Mac OSX CoreAudio
Josh Roberson josh@.nosp@m.aste.nosp@m.riasg.nosp@m.i.co.nosp@m.m
Note
Specially written for Malcolm Davenport, but I think I'll use it too Connects to the Asterisk Manager Interface, AMI, and listens for events on certain devices. If a phone call is connected to one of the devices (phones) the local sound is muted to a lower volume during the call.
Definition in file muted.c.
Macro Definition Documentation
ast_strlen_zero
#define ast_strlen_zero (a) (!(*(a)))
Definition at line 73 of file muted.c.
Function Documentation
add_channel()
static void add_channel (char * tech, char * location) static
Definition at line 102 of file muted.c.
References channels, free(), channel::location, malloc(), channel::next, strdup, and channel::tech.
Referenced by load_config().
 {
    struct channel *chan;
    chan = malloc(sizeof(struct channel));
    if (chan) {
       memset(chan, 0, sizeof(struct channel));
       if (!(chan->tech = strdup(tech))) {
          free(chan);
          return;
       }
       if (!(chan->location = strdup(location))) {
          free(chan->tech);
          free(chan);
          return;
       }
       chan->next = channels;
       channels = chan;
    }
 }
append_sub()
static void append_sub (struct channel * chan, char * name) static
Definition at line 585 of file muted.c.
References free(), malloc(), subchannel::name, subchannel::next, strdup, sub, and channel::subs.
Referenced by offhook_chan().
 {
    struct subchannel *sub;
    sub = chan->subs;
    while(sub) {
       if (!strcasecmp(sub->name, name))
          return;
       sub = sub->next;
    }
    sub = malloc(sizeof(struct subchannel));
    if (sub) {
       memset(sub, 0, sizeof(struct subchannel));
       if (!(sub->name = strdup(name))) {
          free(sub);
          return;
       }
       sub->next = chan->subs;
       chan->subs = sub;
    }
 }
check_mute()
static void check_mute (void) static
Definition at line 547 of file muted.c.
References channels, mute(), muted, channel::next, channel::subs, and unmute().
Referenced by hangup_chan(), and offhook_chan().
 {
    int offhook = 0;
    struct channel *chan;
    chan = channels;
    while(chan) {
       if (chan->subs) {
          offhook++;
          break;
       }
       chan = chan->next;
    }
    if (offhook && !muted)
       mute();
    else if (!offhook && muted)
       unmute();
 }
connect_asterisk()
static int connect_asterisk (void) static
Connect to the asterisk manager interface
Definition at line 225 of file muted.c.
References astf, errno, gethostbyname, host, and hp.
Referenced by main().
 {
    int sock;
    struct hostent *hp;
    char *ports;
    int port = 5038;
    struct sockaddr_in sin;
    ports = strchr(host, ':');
    if (ports) {
       *ports = '\0';
       ports++;
       if ((sscanf(ports, "%5d", &port) != 1) || (port < 1) || (port > 65535)) {
          fprintf(stderr, "'%s' is not a valid port number in the hostname\n", ports);
          return -1;
       }
    }
    hp = gethostbyname(host);
    if (!hp) {
       fprintf(stderr, "Can't find host '%s'\n", host);
       return -1;
    }
    sock = socket(AF_INET, SOCK_STREAM, 0);
    if (sock < 0) {
       fprintf(stderr, "Failed to create socket: %s\n", strerror(errno));
       return -1;
    }
    sin.sin_family = AF_INET;
    sin.sin_port = htons(port);
    memcpy(&sin.sin_addr, hp->h_addr, sizeof(sin.sin_addr));
    if (connect(sock, (struct sockaddr *)&sin, sizeof(sin))) {
       fprintf(stderr, "Failed to connect to '%s' port '%d': %s\n", host, port, strerror(errno));
       close(sock);
       return -1;
    }
    astf = fdopen(sock, "r+");
    if (!astf) {
       fprintf(stderr, "fdopen failed: %s\n", strerror(errno));
       close(sock);
       return -1;
    }
    return 0;
 }
delete_sub()
static void delete_sub (struct channel * chan, char * name) static
Definition at line 565 of file muted.c.
References free(), subchannel::name, subchannel::next, NULL, sub, and channel::subs.
Referenced by hangup_chan().
 {
    struct subchannel *sub, *prev;
    prev = NULL;
    sub = chan->subs;
    while(sub) {
       if (!strcasecmp(sub->name, name)) {
          if (prev)
             prev->next = sub->next;
          else
             chan->subs = sub->next;
          free(sub->name);
          free(sub);
          return;
       }
       prev = sub;
       sub = sub->next;
    }
 }
find_channel()
static struct channel* find_channel (char * channel) static
Definition at line 326 of file muted.c.
References channels, debug, channel::location, channel::next, NULL, channel::tech, and tmp().
Referenced by hangup_chan(), and offhook_chan().
 {
    char tmp[256] = "";
    char *s, *t;
    struct channel *chan;
    strncpy(tmp, channel, sizeof(tmp) - 1);
    s = strchr(tmp, '/');
    if (s) {
       *s = '\0';
       s++;
       t = strrchr(s, '-');
       if (t) {
          *t = '\0';
       }
       if (debug)
          printf("Searching for '%s' tech, '%s' location\n", tmp, s);
       chan = channels;
       while(chan) {
          if (!strcasecmp(chan->tech, tmp) && !strcasecmp(chan->location, s)) {
             if (debug)
                printf("Found '%s'/'%s'\n", chan->tech, chan->location);
             break;
          }
          chan = chan->next;
       }
    } else
       chan = NULL;
    return chan;
 }
get_line()
static char* get_line (void) static
Definition at line 269 of file muted.c.
References astf, buf, and NULL.
Referenced by login_asterisk(), and wait_event().
 {
    static char buf[1024];
    if (fgets(buf, sizeof(buf), astf)) {
       while(strlen(buf) && (buf[strlen(buf) - 1] < 33))
          buf[strlen(buf) - 1] = '\0';
       return buf;
    } else
       return NULL;
 }
getvol()
static int getvol (void) static
Definition at line 357 of file muted.c.
References channels, errno, mixchan, mixfd, and NULL.
Referenced by mute(), and unmute().
 {
    int vol;
    if (ioctl(mixfd, MIXER_READ(mixchan), &vol)) {
 #else
 static float getvol(void)
 {
    float volumeL, volumeR, vol;
    OSStatus err;
    AudioDeviceID device;
    UInt32 size;
    UInt32 channels[2];
    AudioObjectPropertyAddress OutputAddr = { kAudioHardwarePropertyDefaultOutputDevice, kAudioObjectPropertyScopeGlobal, kAudioObjectPropertyElementMaster };
    AudioObjectPropertyAddress ChannelAddr = { kAudioDevicePropertyPreferredChannelsForStereo, kAudioDevicePropertyScopeOutput, kAudioObjectPropertyElementWildcard };
    AudioObjectPropertyAddress VolumeAddr = { kAudioDevicePropertyVolumeScalar, kAudioDevicePropertyScopeOutput, };
    size = sizeof(device);
    err = AudioObjectGetPropertyData(kAudioObjectSystemObject, &OutputAddr, 0, NULL, &size, &device);
    size = sizeof(channels);
    if (!err) {
       err = AudioObjectGetPropertyData(device, &ChannelAddr, 0, NULL, &size, &channels);
    }
    size = sizeof(vol);
    if (!err) {
       VolumeAddr.mElement = channels[0];
       err = AudioObjectGetPropertyData(device, &VolumeAddr, 0, NULL, &size, &volumeL);
    }
    if (!err) {
       VolumeAddr.mElement = channels[1];
       err = AudioObjectGetPropertyData(device, &VolumeAddr, 0, NULL, &size, &volumeR);
    }
    if (!err)
       vol = (volumeL < volumeR) ? volumeR : volumeL;
    else {
 #endif
       fprintf(stderr, "Unable to read mixer volume: %s\n", strerror(errno));
       return -1;
    }
    return vol;
 }
hangup_chan()
static void hangup_chan (char * channel) static
Definition at line 606 of file muted.c.
References check_mute(), debug, delete_sub(), and find_channel().
Referenced by wait_event().
 {
    struct channel *chan;
    if (debug)
       printf("Hangup '%s'\n", channel);
    chan = find_channel(channel);
    if (chan)
       delete_sub(chan, channel);
    check_mute();
 }
load_config()
static int load_config (void) static
Definition at line 123 of file muted.c.
References add_channel(), buf, channels, config, errno, host, mutelevel, pass, and smoothfade.
Referenced by main().
 {
    FILE *f;
    char buf[256];
    char *val;
    char *val2;
    int lineno=0;
    int x;
    f = fopen(config, "r");
    if (!f) {
       fprintf(stderr, "Unable to open config file '%s': %s\n", config, strerror(errno));
       return -1;
    }
    while(!feof(f)) {
       if (!fgets(buf, sizeof(buf), f)) {
          continue;
       }
       if (!feof(f)) {
          lineno++;
          val = strchr(buf, '#');
          if (val) *val = '\0';
          while(strlen(buf) && (buf[strlen(buf) - 1] < 33))
             buf[strlen(buf) - 1] = '\0';
          if (!strlen(buf))
             continue;
          val = buf;
          while(*val) {
             if (*val < 33)
                break;
             val++;
          }
          if (*val) {
             *val = '\0';
             val++;
             while(*val && (*val < 33)) val++;
          }
          if (!strcasecmp(buf, "host")) {
             if (val && strlen(val))
                strncpy(host, val, sizeof(host) - 1);
             else
                fprintf(stderr, "host needs an argument (the host) at line %d\n", lineno);
          } else if (!strcasecmp(buf, "user")) {
             if (val && strlen(val))
                snprintf(user, sizeof(user), "%s", val);
             else
                fprintf(stderr, "user needs an argument (the user) at line %d\n", lineno);
          } else if (!strcasecmp(buf, "pass")) {
             if (val && strlen(val))
                snprintf(pass, sizeof(pass), "%s", val);
             else
                fprintf(stderr, "pass needs an argument (the password) at line %d\n", lineno);
          } else if (!strcasecmp(buf, "smoothfade")) {
             smoothfade = 1;
          } else if (!strcasecmp(buf, "mutelevel")) {
             if (val && (sscanf(val, "%3d", &x) == 1) && (x > -1) && (x < 101)) {
                mutelevel = x;
             } else
                fprintf(stderr, "mutelevel must be a number from 0 (most muted) to 100 (no mute) at line %d\n", lineno);
          } else if (!strcasecmp(buf, "channel")) {
             if (val && strlen(val)) {
                val2 = strchr(val, '/');
                if (val2) {
                   *val2 = '\0';
                   val2++;
                   add_channel(val, val2);
                } else
                   fprintf(stderr, "channel needs to be of the format Tech/Location at line %d\n", lineno);
             } else
                fprintf(stderr, "channel needs an argument (the channel) at line %d\n", lineno);
          } else {
             fprintf(stderr, "ignoring unknown keyword '%s'\n", buf);
          }
       }
    }
    fclose(f);
    if (!strlen(host))
       fprintf(stderr, "no 'host' specification in config file\n");
    else if (!strlen(user))
       fprintf(stderr, "no 'user' specification in config file\n");
    else if (!channels)
       fprintf(stderr, "no 'channel' specifications in config file\n");
    else
       return 0;
    return -1;
 }
login_asterisk()
static int login_asterisk (void) static
Login to the asterisk manager interface
Definition at line 281 of file muted.c.
References astf, get_line(), and pass.
Referenced by main().
 {
    char *welcome;
    char *resp;
    if (!(welcome = get_line())) {
       fprintf(stderr, "disconnected (1)\n");
       return -1;
    }
    fprintf(astf,
       "Action: Login\r\n"
       "Username: %s\r\n"
       "Secret: %s\r\n\r\n", user, pass);
    if (!(welcome = get_line())) {
       fprintf(stderr, "disconnected (2)\n");
       return -1;
    }
    if (strcasecmp(welcome, "Response: Success")) {
       fprintf(stderr, "login failed ('%s')\n", welcome);
       return -1;
    }
    /* Eat the rest of the event */
    while((resp = get_line()) && strlen(resp));
    if (!resp) {
       fprintf(stderr, "disconnected (3)\n");
       return -1;
    }
    fprintf(astf,
       "Action: Status\r\n\r\n");
    if (!(welcome = get_line())) {
       fprintf(stderr, "disconnected (4)\n");
       return -1;
    }
    if (strcasecmp(welcome, "Response: Success")) {
       fprintf(stderr, "status failed ('%s')\n", welcome);
       return -1;
    }
    /* Eat the rest of the event */
    while((resp = get_line()) && strlen(resp));
    if (!resp) {
       fprintf(stderr, "disconnected (5)\n");
       return -1;
    }
    return 0;
 }
main()
int main (int argc, char * argv[])
Definition at line 687 of file muted.c.
References astf, connect_asterisk(), debug, errno, load_config(), login_asterisk(), mixfd, needfork, NULL, open_mixer(), usage(), and wait_event().
 {
    int x;
    while((x = getopt(argc, argv, "fhd")) > 0) {
       switch(x) {
       case 'd':
          debug = 1;
          needfork = 0;
          break;
       case 'f':
          needfork = 0;
          break;
       case 'h':
          /* Fall through */
       default:
          usage();
          exit(1);
       }
    }
    if (load_config())
       exit(1);
 #ifndef __Darwin__
    if (open_mixer())
       exit(1);
 #endif
    if (connect_asterisk()) {
 #ifndef __Darwin__
       close(mixfd);
 #endif
       exit(1);
    }
    if (login_asterisk()) {
 #ifndef __Darwin__
       close(mixfd);
 #endif
       fclose(astf);
       exit(1);
    }
 #ifdef HAVE_WORKING_FORK
    if (needfork) {
 #ifndef HAVE_SBIN_LAUNCHD
       if (daemon(0,0) < 0) {
          fprintf(stderr, "daemon() failed: %s\n", strerror(errno));
          exit(1);
       }
 #else
       const char *found = NULL, *paths[] = {
          "/Library/LaunchAgents/org.asterisk.muted.plist",
          "/Library/LaunchDaemons/org.asterisk.muted.plist",
          "contrib/init.d/org.asterisk.muted.plist",
          "<path-to-asterisk-source>/contrib/init.d/org.asterisk.muted.plist" };
       char userpath[256];
       struct stat unused;
       struct passwd *pwd = getpwuid(getuid());
       int i;
       snprintf(userpath, sizeof(userpath), "%s%s", pwd->pw_dir, paths[0]);
       if (!stat(userpath, &unused)) {
          found = userpath;
       }
       if (!found) {
          for (i = 0; i < 3; i++) {
             if (!stat(paths[i], &unused)) {
                found = paths[i];
                break;
             }
          }
       }
       fprintf(stderr, "Mac OS X detected.  Use 'launchctl load -w %s' to launch.\n", found ? found : paths[3]);
       exit(1);
 #endif /* !defined(HAVE_SBIN_LAUNCHD */
    }
 #endif
    for(;;) {
       if (wait_event()) {
          fclose(astf);
          while(connect_asterisk()) {
             sleep(5);
          }
          if (login_asterisk()) {
             fclose(astf);
             exit(1);
          }
       }
    }
    exit(0);
 }
mute()
static void mute (void) static
Definition at line 468 of file muted.c.
References debug, getvol(), muted, mutedlevel(), mutelevel, setvol(), smoothfade, and stepsize.
Referenced by check_mute().
 {
 #ifndef __Darwin__
    int vol;
    int start;
    int x;
 #else
    float vol;
    float start = 1.0;
    float x;
 #endif
    vol = getvol();
    oldvol = vol;
    if (smoothfade)
 #ifdef __Darwin__
       start = mutelevel;
 #else
       start = 100;
    else
       start = mutelevel;
 #endif
    for (x=start;x>=mutelevel;x-=stepsize) {
       mutevol = mutedlevel(vol, x);
       setvol(mutevol);
       /* Wait 0.01 sec */
       usleep(10000);
    }
    mutevol = mutedlevel(vol, mutelevel);
    setvol(mutevol);
    if (debug)
 #ifdef __Darwin__
       printf("Mute from '%f' to '%f'!\n", oldvol, mutevol);
 #else
       printf("Mute from '%04x' to '%04x'!\n", oldvol, mutevol);
 #endif
    muted = 1;
 }
mutedlevel()
static int mutedlevel (int orig, int level) static
Definition at line 450 of file muted.c.
Referenced by mute(), and unmute().
 {
    int l = orig >> 8;
    int r = orig & 0xff;
    l = (float)(level) * (float)(l) / 100.0;
    r = (float)(level) * (float)(r) / 100.0;
    return (l << 8) | r;
 #else
 static float mutedlevel(float orig, float level)
 {
    float master = orig;
    master = level * master / 100.0;
    return master;
 #endif
 }
offhook_chan()
static void offhook_chan (char * channel) static
Definition at line 617 of file muted.c.
References append_sub(), check_mute(), debug, and find_channel().
Referenced by wait_event().
 {
    struct channel *chan;
    if (debug)
       printf("Offhook '%s'\n", channel);
    chan = find_channel(channel);
    if (chan)
       append_sub(chan, channel);
    check_mute();
 }
open_mixer()
static int open_mixer (void) static
Definition at line 213 of file muted.c.
References errno, and mixfd.
Referenced by main().
 {
    mixfd = open("/dev/mixer", O_RDWR);
    if (mixfd < 0) {
       fprintf(stderr, "Unable to open /dev/mixer: %s\n", strerror(errno));
       return -1;
    }
    return 0;
 }
setvol()
static int setvol (int vol) static
Definition at line 400 of file muted.c.
References channels, errno, mixchan, mixfd, and NULL.
Referenced by mute(), and unmute().
 {
 #ifndef __Darwin__
    if (ioctl(mixfd, MIXER_WRITE(mixchan), &vol)) {
 #else
    float volumeL = vol;
    float volumeR = vol;
    OSStatus err;
    AudioDeviceID device;
    UInt32 size;
    UInt32 channels[2];
    AudioObjectPropertyAddress OutputAddr = { kAudioHardwarePropertyDefaultOutputDevice, kAudioObjectPropertyScopeGlobal, kAudioObjectPropertyElementMaster };
    AudioObjectPropertyAddress ChannelAddr = { kAudioDevicePropertyPreferredChannelsForStereo, kAudioDevicePropertyScopeOutput, kAudioObjectPropertyElementWildcard };
    AudioObjectPropertyAddress VolumeAddr = { kAudioDevicePropertyVolumeScalar, kAudioDevicePropertyScopeOutput, };
    size = sizeof(device);
    err = AudioObjectGetPropertyData(kAudioObjectSystemObject, &OutputAddr, 0, NULL, &size, &device);
    size = sizeof(channels);
    err = AudioObjectGetPropertyData(device, &ChannelAddr, 0, NULL, &size, &channels);
    size = sizeof(vol);
    if (!err) {
       VolumeAddr.mElement = channels[0];
       err = AudioObjectSetPropertyData(device, &VolumeAddr, 0, NULL, size, &volumeL);
    }
    if (!err) {
       VolumeAddr.mElement = channels[1];
       err = AudioObjectSetPropertyData(device, &VolumeAddr, 0, NULL, size, &volumeR);
    }
    if (err) {
 #endif
       fprintf(stderr, "Unable to write mixer volume: %s\n", strerror(errno));
       return -1;
    }
    return 0;
 }
unmute()
static void unmute (void) static
Definition at line 506 of file muted.c.
References debug, getvol(), muted, mutedlevel(), mutelevel, setvol(), smoothfade, and stepsize.
Referenced by check_mute().
 {
 #ifdef __Darwin__
    float vol;
    float start;
    float x;
 #else
    int vol;
    int start;
    int x;
 #endif
    vol = getvol();
    if (debug)
 #ifdef __Darwin__
       printf("Unmute from '%f' (should be '%f') to '%f'!\n", vol, mutevol, oldvol);
    mutevol = vol;
    if (vol == mutevol) {
 #else
       printf("Unmute from '%04x' (should be '%04x') to '%04x'!\n", vol, mutevol, oldvol);
    if ((int)vol == mutevol) {
 #endif
       if (smoothfade)
          start = mutelevel;
       else
 #ifdef __Darwin__
          start = 1.0;
 #else
          start = 100;
 #endif
       for (x=start;x<100;x+=stepsize) {
          mutevol = mutedlevel(oldvol, x);
          setvol(mutevol);
          /* Wait 0.01 sec */
          usleep(10000);
       }
       setvol(oldvol);
    } else
       printf("Whoops, it's already been changed!\n");
    muted = 0;
 }
usage()
static void usage (void) static
Definition at line 680 of file muted.c.
Referenced by main().
 {
    printf("Usage: muted [-f] [-d]\n"
           "        -f : Do not fork\n"
           "        -d : Debug (implies -f)\n");
 }
wait_event()
static int wait_event (void) static
Definition at line 628 of file muted.c.
References get_line(), hangup_chan(), and offhook_chan().
Referenced by main().
 {
    char *resp;
    char event[120]="";
    char channel[120]="";
    char oldname[120]="";
    char newname[120]="";
    resp = get_line();
    if (!resp) {
       fprintf(stderr, "disconnected (6)\n");
       return -1;
    }
    if (!strncasecmp(resp, "Event: ", strlen("Event: "))) {
       int event_len = -1;
       int channel_len = -1;
       int newname_len = -1;
       int oldname_len = -1;
       event_len = snprintf(event, sizeof(event), "%s", resp + strlen("Event: "));
       /* Consume the rest of the non-event */
       while((resp = get_line()) && strlen(resp)) {
          if (!strncasecmp(resp, "Channel: ", strlen("Channel: ")))
             channel_len = snprintf(channel, sizeof(channel), "%s", resp + strlen("Channel: "));
          if (!strncasecmp(resp, "Newname: ", strlen("Newname: ")))
             newname_len = snprintf(newname, sizeof(newname), "%s", resp + strlen("Newname: "));
          if (!strncasecmp(resp, "Oldname: ", strlen("Oldname: ")))
             oldname_len = snprintf(oldname, sizeof(oldname), "%s", resp + strlen("Oldname: "));
       }
       if (channel_len == strlen(channel)) {
          if (event_len == strlen(event) && !strcasecmp(event, "Hangup"))
             hangup_chan(channel);
          else
             offhook_chan(channel);
       }
       if (newname_len == strlen(newname) && oldname_len == strlen(oldname)) {
          if (event_len == strlen(event) && !strcasecmp(event, "Rename")) {
             hangup_chan(oldname);
             offhook_chan(newname);
          }
       }
    } else {
       /* Consume the rest of the non-event */
       while((resp = get_line()) && strlen(resp));
    }
    if (!resp) {
       fprintf(stderr, "disconnected (7)\n");
       return -1;
    }
    return 0;
 }
Variable Documentation
astf
FILE* astf static
Definition at line 209 of file muted.c.
Referenced by connect_asterisk(), get_line(), login_asterisk(), and main().
channels
struct channel * channels static
Referenced by add_channel(), check_mute(), find_channel(), getvol(), load_config(), and setvol().
config
char* config = "/etc/asterisk/muted.conf" static
Definition at line 75 of file muted.c.
Referenced by load_config().
debug
int debug = 0 static
Definition at line 84 of file muted.c.
Referenced by find_channel(), hangup_chan(), main(), mute(), offhook_chan(), and unmute().
host
char host[256] = "" static
Definition at line 77 of file muted.c.
Referenced by __find_callno(), app_exec(), apply_negotiated_sdp_stream(), ast_ari_channels_external_media(), ast_ari_get_docs(), ast_get_ip_or_srv(), ast_gethostbyname(), ast_sip_get_transport_name(), ast_sip_validate_uri_length(), ast_sockaddr_parse(), ast_sockaddr_resolve(), ast_sockaddr_stringify_fmt(), ast_sockaddr_stringify_port(), AST_TEST_DEFINE(), authenticate_verify(), build_callid_pvt(), build_callid_registry(), change_outgoing_sdp_stream_media_address(), connect_asterisk(), create_addr(), dns_srv_alloc(), extract_contact_addr(), festival_exec(), handle_cli_iax2_show_registry(), handle_identify(), iax2_request(), insert_user_in_contact_uri(), launch_ha_netscript(), launch_netscript(), load_config(), load_pktccops_config(), make_email_file(), manager_iax2_show_registry(), negotiate_incoming_sdp_stream(), osp_lookup(), parse_config(), parse_moved_contact(), peer_set_srcaddr(), pjsip_enable_logger_host(), process_sdp(), process_sdp_c(), reload_config(), security_event_populate(), sendmail(), sendpage(), session_outgoing_nat_hook(), set_config(), sip_devicestate(), sip_parse_register_line(), sip_request_call(), sip_resolve(), sip_sanitized_host(), sip_show_mwi(), sip_show_registry(), srv_datastore_setup(), srv_result_read(), unicast_rtp_request(), and wizard_apply_handler().
mixchan
int mixchan = SOUND_MIXER_VOLUME static
Definition at line 87 of file muted.c.
Referenced by getvol(), and setvol().
mixfd
int mixfd static
Definition at line 211 of file muted.c.
Referenced by getvol(), main(), open_mixer(), and setvol().
muted
int muted = 0 static
Examples:
/usr/src/asterisk-18.5.0/main/app.c.
Definition at line 82 of file muted.c.
Referenced by __ast_play_and_record(), bridge_template_handler(), check_mute(), dahdi_confmute(), mute(), my_wink(), set_sound(), and unmute().
mutelevel
int mutelevel = 20 static
Definition at line 81 of file muted.c.
Referenced by load_config(), mute(), and unmute().
mutevol
int mutevol = 0 static
Definition at line 443 of file muted.c.
needfork
int needfork = 1 static
Definition at line 83 of file muted.c.
Referenced by main().
oldvol
int oldvol = 0 static
Definition at line 442 of file muted.c.
pass
char pass[256] = "" static
Definition at line 79 of file muted.c.
Referenced by load_config(), and login_asterisk().
smoothfade
int smoothfade = 0 static
Definition at line 80 of file muted.c.
Referenced by load_config(), mute(), and unmute().
stepsize
int stepsize = 3 static
Definition at line 85 of file muted.c.
Referenced by mute(), and unmute().
user
char user[256] = "" static
Definition at line 78 of file muted.c.