Asterisk - The Open Source Telephony Project: ndbm.c File Reference
ndbm.c File Reference
#include <sys/param.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <ndbm.h>
#include "hash.h"
Functions
int dbm_clearerr (DBM *db)
void dbm_close (DBM *db)
int dbm_delete (DBM *db, datum key)
int dbm_dirfno (DBM *db)
int dbm_error (DBM *db)
datum dbm_fetch (DBM *db, datum key)
datum dbm_firstkey (DBM *db)
datum dbm_nextkey (DBM *db)
DBM * dbm_open (char *file, int flags, int mode) const
int dbm_store (DBM *db, datum key, datum data, int flags)
Function Documentation
dbm_clearerr()
int dbm_clearerr (DBM * db)
Definition at line 219 of file ndbm.c.
References htab::errnum, hp, and __db::internal.
 {
    HTAB *hp;
    hp = (HTAB *)db->internal;
    hp->errnum = 0;
    return (0);
 }
dbm_close()
void dbm_close (DBM * db)
Definition at line 91 of file ndbm.c.
References db.
 {
    (void)(db->close)(db);
 }
dbm_delete()
int dbm_delete (DBM * db, datum key)
Definition at line 170 of file ndbm.c.
References DBT::data, datum::dptr, datum::dsize, DBT::size, and status.
 {
    int status;
    DBT dbtkey;
    dbtkey.data = key.dptr;
    dbtkey.size = key.dsize;
    status = (db->del)(db, &dbtkey, 0);
    if (status)
       return (-1);
    else
       return (0);
 }
dbm_dirfno()
int dbm_dirfno (DBM * db)
Definition at line 230 of file ndbm.c.
References __db::internal.
 {
    return(((HTAB *)db->internal)->fp);
 }
dbm_error()
int dbm_error (DBM * db)
Definition at line 209 of file ndbm.c.
References htab::errnum, hp, and __db::internal.
 {
    HTAB *hp;
    hp = (HTAB *)db->internal;
    return (hp->errnum);
 }
dbm_fetch()
datum dbm_fetch (DBM * db, datum key)
Definition at line 103 of file ndbm.c.
References DBT::data, datum::dptr, datum::dsize, NULL, DBT::size, and status.
 {
    datum retdata;
    int status;
    DBT dbtkey, dbtretdata;
    dbtkey.data = key.dptr;
    dbtkey.size = key.dsize;
    status = (db->get)(db, &dbtkey, &dbtretdata, 0);
    if (status) {
       dbtretdata.data = NULL;
       dbtretdata.size = 0;
    }
    retdata.dptr = dbtretdata.data;
    retdata.dsize = dbtretdata.size;
    return (retdata);
 }
dbm_firstkey()
datum dbm_firstkey (DBM * db)
Definition at line 129 of file ndbm.c.
References DBT::data, datum::dptr, datum::dsize, NULL, R_FIRST, DBT::size, and status.
 {
    int status;
    datum retkey;
    DBT dbtretkey, dbtretdata;
    status = (db->seq)(db, &dbtretkey, &dbtretdata, R_FIRST);
    if (status)
       dbtretkey.data = NULL;
    retkey.dptr = dbtretkey.data;
    retkey.dsize = dbtretkey.size;
    return (retkey);
 }
dbm_nextkey()
datum dbm_nextkey (DBM * db)
Definition at line 150 of file ndbm.c.
References DBT::data, datum::dptr, datum::dsize, NULL, R_NEXT, DBT::size, and status.
 {
    int status;
    datum retkey;
    DBT dbtretkey, dbtretdata;
    status = (db->seq)(db, &dbtretkey, &dbtretdata, R_NEXT);
    if (status)
       dbtretkey.data = NULL;
    retkey.dptr = dbtretkey.data;
    retkey.dsize = dbtretkey.size;
    return (retkey);
 }
dbm_open()
DBM* dbm_open (char * file, int flags, int mode) const
Definition at line 61 of file ndbm.c.
References __hash_open(), HASHINFO::bsize, HASHINFO::cachesize, db, DBM_SUFFIX, HASHINFO::ffactor, make_ari_stubs::file, free(), sip_to_pjsip::info(), len(), HASHINFO::lorder, malloc(), HASHINFO::nelem, and NULL.
 {
    DBM *db;
    HASHINFO info;
    const size_t len = strlen(file) + sizeof (DBM_SUFFIX);
 #ifdef __GNUC__
    char path[len];
 #else
    char *path = malloc(len);
    if (path == NULL)
       return NULL;
 #endif
    info.bsize = 4096;
    info.ffactor = 40;
    info.nelem = 1;
    info.cachesize = 0;
    info.hash = NULL;
    info.lorder = 0;
    snprintf(path, len, "%s%s", file, DBM_SUFFIX);
    db = (DBM *)__hash_open(path, flags, mode, &info, 0);
 #ifndef  __GNUC__
    free(path);
 #endif
    return db;
 }
dbm_store()
int dbm_store (DBM * db, datum key, datum data, int flags)
Definition at line 193 of file ndbm.c.
References DBT::data, DBM_INSERT, datum::dptr, datum::dsize, R_NOOVERWRITE, and DBT::size.
 {
    DBT dbtkey, dbtdata;
    dbtkey.data = key.dptr;
    dbtkey.size = key.dsize;
    dbtdata.data = data.dptr;
    dbtdata.size = data.dsize;
    return ((db->put)(db, &dbtkey, &dbtdata,
        (flags == DBM_INSERT) ? R_NOOVERWRITE : 0));
 }