Asterisk - The Open Source Telephony Project: stasis_message_vtable Struct Reference
stasis_message_vtable Struct Reference
Virtual table providing methods for messages.
#include <stasis.h>
Data Fields
struct ast_manager_event_blob *(* to_ami)(struct stasis_message *message)
Build the AMI representation of the message.
struct ast_event *(* to_event)(struct stasis_message *message)
Build the ast_event representation of the message.
struct ast_json *(* to_json)(struct stasis_message *message, const struct stasis_message_sanitizer *sanitize)
Build the JSON representation of the message.
Detailed Description
Virtual table providing methods for messages.
Since
12
Definition at line 239 of file stasis.h.
Field Documentation
to_ami
struct ast_manager_event_blob*(* to_ami) (struct stasis_message *message)
Build the AMI representation of the message.
May be NULL, or may return NULL, to indicate no representation. The returned object should be ao2_cleanup()'ed.
Parameters
message Message to convert to AMI string.
Returns
Newly allocated ast_manager_event_blob.
NULL on error.
NULL if AMI format is not supported.
Definition at line 266 of file stasis.h.
Referenced by create_message_types(), and stasis_message_type_create().
to_event
struct ast_event*(* to_event) (struct stasis_message *message)
Build the ast_event representation of the message.
Since
12.3.0 May be NULL, or may return NULL, to indicate no representation. The returned object should be free'd.
Parameters
message Message to convert to an ast_event.
Returns
Newly allocated ast_event.
NULL on error.
NULL if AMI format is not supported.
Definition at line 281 of file stasis.h.
Referenced by create_message_types(), and stasis_message_type_create().
to_json
struct ast_json*(* to_json) (struct stasis_message *message, const struct stasis_message_sanitizer *sanitize)
Build the JSON representation of the message.
May be NULL, or may return NULL, to indicate no representation. The returned object should be ast_json_unref()'ed.
Parameters
message Message to convert to JSON string.
sanitize Snapshot sanitization callback.
Returns
Newly allocated JSON message.
NULL on error.
NULL if JSON format is not supported.
Definition at line 253 of file stasis.h.
Referenced by create_message_types(), and stasis_message_type_create().
The documentation for this struct was generated from the following file:
stasis.h