Asterisk - The Open Source Telephony Project: app_userevent.c File Reference
app_userevent.c File Reference
Dial plan applications
UserEvent application – send manager event.
#include "asterisk.h"
#include "asterisk/pbx.h"
#include "asterisk/module.h"
#include "asterisk/manager.h"
#include "asterisk/app.h"
#include "asterisk/json.h"
#include "asterisk/stasis_channels.h"
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int load_module (void)
static int unload_module (void)
static int userevent_exec (struct ast_channel *chan, const char *data)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Custom User Event Application" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, }
static char * app = "UserEvent"
static const struct ast_module_info * ast_module_info = &__mod_info
Detailed Description
UserEvent application – send manager event.
Definition in file app_userevent.c.
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 135 of file app_userevent.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 135 of file app_userevent.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 135 of file app_userevent.c.
load_module()
static int load_module (void) static
Definition at line 130 of file app_userevent.c.
References app, ast_register_application_xml, and userevent_exec().
 {
    return ast_register_application_xml(app, userevent_exec);
 }
unload_module()
static int unload_module (void) static
Definition at line 125 of file app_userevent.c.
References app, and ast_unregister_application().
 {
    return ast_unregister_application(app);
 }
userevent_exec()
static int userevent_exec (struct ast_channel * chan, const char * data) static
Definition at line 72 of file app_userevent.c.
References args, AST_APP_ARG, ast_channel_lock, ast_channel_unlock, AST_DECLARE_APP_ARGS, ast_json_object_set(), ast_json_pack(), ast_json_string_create(), ast_json_unref(), ast_log, ast_multi_object_blob_single_channel_publish(), ast_multi_user_event_type(), AST_STANDARD_APP_ARGS, ast_strdupa, ast_strip(), ast_strlen_zero, LOG_WARNING, NULL, parse(), RAII_VAR, strsep(), and value.
Referenced by load_module().
 {
    char *parse;
    int x;
    AST_DECLARE_APP_ARGS(args,
       AST_APP_ARG(eventname);
       AST_APP_ARG(extra)[100];
    );
    RAII_VAR(struct ast_json *, blob, NULL, ast_json_unref);
    if (ast_strlen_zero(data)) {
       ast_log(LOG_WARNING, "UserEvent requires an argument (eventname,optional event body)\n");
       return -1;
    }
    parse = ast_strdupa(data);
    AST_STANDARD_APP_ARGS(args, parse);
    blob = ast_json_pack("{s: s}",
               "eventname", args.eventname);
    if (!blob) {
       return -1;
    }
    for (x = 0; x < args.argc - 1; x++) {
       char *key, *value = args.extra[x];
       struct ast_json *json_value;
       key = strsep(&value, ":");
       if (!value) {
          /* no ':' in string? */
          continue;
       }
       value = ast_strip(value);
       json_value = ast_json_string_create(value);
       if (!json_value) {
          return -1;
       }
       /* ref stolen by ast_json_object_set */
       if (ast_json_object_set(blob, key, json_value)) {
          return -1;
       }
    }
    ast_channel_lock(chan);
    ast_multi_object_blob_single_channel_publish(chan, ast_multi_user_event_type(), blob);
    ast_channel_unlock(chan);
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Custom User Event Application" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, } static
Definition at line 135 of file app_userevent.c.
app
char* app = "UserEvent" static
Definition at line 70 of file app_userevent.c.
Referenced by load_module(), and unload_module().
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 135 of file app_userevent.c.