Asterisk - The Open Source Telephony Project: res_pjsip_endpoint_identifier_anonymous.c File Reference
res_pjsip_endpoint_identifier_anonymous.c File Reference
#include "asterisk.h"
#include <pjsip.h>
#include "asterisk/res_pjsip.h"
#include "asterisk/module.h"
Macros
#define DOMAIN_NAME_LEN 255
Functions
static void __reg_module (void)
static void __unreg_module (void)
static struct ast_sip_endpoint * anonymous_identify (pjsip_rx_data *rdata)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int find_transport_state_in_use (void *obj, void *arg, int flags)
static int get_endpoint_details (pjsip_rx_data *rdata, char *domain, size_t domain_size)
static int load_module (void)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_DEFAULT , .description = "PJSIP Anonymous endpoint identifier" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .requires = "res_pjsip", }
static struct ast_sip_endpoint_identifier anonymous_identifier
static const struct ast_module_info * ast_module_info = &__mod_info
Macro Definition Documentation
DOMAIN_NAME_LEN
#define DOMAIN_NAME_LEN 255
Definition at line 60 of file res_pjsip_endpoint_identifier_anonymous.c.
Referenced by anonymous_identify().
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 144 of file res_pjsip_endpoint_identifier_anonymous.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 144 of file res_pjsip_endpoint_identifier_anonymous.c.
anonymous_identify()
static struct ast_sip_endpoint* anonymous_identify (pjsip_rx_data * rdata) static
Definition at line 62 of file res_pjsip_endpoint_identifier_anonymous.c.
References ao2_callback, ao2_cleanup, ao2_ref, ast_debug, ast_sip_get_disable_multi_domain(), ast_sip_get_sorcery(), ast_sip_get_transport_states(), ast_sorcery_object_get_id(), ast_sorcery_retrieve_by_id(), ast_strlen_zero, ast_sip_transport::domain, ast_sip_domain_alias::domain, DOMAIN_NAME_LEN, done, find_transport_state_in_use(), get_endpoint_details(), ast_sip_transport_state::id, NULL, and transport_states.
 {
    char domain_name[DOMAIN_NAME_LEN + 1];
    struct ast_sip_endpoint *endpoint;
    if (get_endpoint_details(rdata, domain_name, sizeof(domain_name))) {
       return NULL;
    }
    if (!ast_sip_get_disable_multi_domain()) {
       struct ast_sip_domain_alias *alias;
       struct ao2_container *transport_states;
       struct ast_sip_transport_state *transport_state = NULL;
       struct ast_sip_transport *transport = NULL;
       char id[sizeof("anonymous@") + DOMAIN_NAME_LEN];
       /* Attempt to find the endpoint given the name and domain provided */
       snprintf(id, sizeof(id), "anonymous@%s", domain_name);
       endpoint = ast_sorcery_retrieve_by_id(ast_sip_get_sorcery(), "endpoint", id);
       if (endpoint) {
          goto done;
       }
       /* See if an alias exists for the domain provided */
       alias = ast_sorcery_retrieve_by_id(ast_sip_get_sorcery(), "domain_alias",
          domain_name);
       if (alias) {
          snprintf(id, sizeof(id), "anonymous@%s", alias->domain);
          ao2_ref(alias, -1);
          endpoint = ast_sorcery_retrieve_by_id(ast_sip_get_sorcery(), "endpoint", id);
          if (endpoint) {
             goto done;
          }
       }
       /* See if the transport this came in on has a provided domain */
       if ((transport_states = ast_sip_get_transport_states())
          && (transport_state = ao2_callback(transport_states, 0, find_transport_state_in_use, rdata))
          && (transport = ast_sorcery_retrieve_by_id(ast_sip_get_sorcery(), "transport", transport_state->id))
          && !ast_strlen_zero(transport->domain)) {
          snprintf(id, sizeof(id), "anonymous@%s", transport->domain);
          endpoint = ast_sorcery_retrieve_by_id(ast_sip_get_sorcery(), "endpoint", id);
       }
       ao2_cleanup(transport);
       ao2_cleanup(transport_state);
       ao2_cleanup(transport_states);
       if (endpoint) {
          goto done;
       }
    }
    /* Fall back to no domain */
    endpoint = ast_sorcery_retrieve_by_id(ast_sip_get_sorcery(), "endpoint", "anonymous");
 done:
    if (endpoint) {
       ast_debug(3, "Retrieved anonymous endpoint '%s'\n", ast_sorcery_object_get_id(endpoint));
    }
    return endpoint;
 }
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 144 of file res_pjsip_endpoint_identifier_anonymous.c.
find_transport_state_in_use()
static int find_transport_state_in_use (void * obj, void * arg, int flags) static
Definition at line 45 of file res_pjsip_endpoint_identifier_anonymous.c.
References CMP_MATCH, ast_sip_transport_state::factory, and ast_sip_transport_state::transport.
Referenced by anonymous_identify().
 {
    struct ast_sip_transport_state *transport_state = obj;
    pjsip_rx_data *rdata = arg;
    if (transport_state->transport == rdata->tp_info.transport
       || (transport_state->factory
          && !pj_strcmp(&transport_state->factory->addr_name.host, &rdata->tp_info.transport->local_name.host)
          && transport_state->factory->addr_name.port == rdata->tp_info.transport->local_name.port)) {
       return CMP_MATCH;
    }
    return 0;
 }
get_endpoint_details()
static int get_endpoint_details (pjsip_rx_data * rdata, char * domain, size_t domain_size) static
Definition at line 33 of file res_pjsip_endpoint_identifier_anonymous.c.
References ast_copy_pj_str().
Referenced by anonymous_identify().
 {
    pjsip_uri *from = rdata->msg_info.from->uri;
    pjsip_sip_uri *sip_from;
    if (!PJSIP_URI_SCHEME_IS_SIP(from) && !PJSIP_URI_SCHEME_IS_SIPS(from)) {
       return -1;
    }
    sip_from = (pjsip_sip_uri *) pjsip_uri_get_uri(from);
    ast_copy_pj_str(domain, &sip_from->host, domain_size);
    return 0;
 }
load_module()
static int load_module (void) static
Definition at line 127 of file res_pjsip_endpoint_identifier_anonymous.c.
References AST_MODULE_LOAD_SUCCESS, and ast_sip_register_endpoint_identifier_with_name().
Referenced by unload_module().
 {
    ast_sip_register_endpoint_identifier_with_name(&anonymous_identifier, "anonymous");
    return AST_MODULE_LOAD_SUCCESS;
 }
unload_module()
static int unload_module (void) static
Definition at line 133 of file res_pjsip_endpoint_identifier_anonymous.c.
References AST_MODFLAG_DEFAULT, AST_MODULE_INFO(), AST_MODULE_SUPPORT_CORE, ast_sip_unregister_endpoint_identifier(), ASTERISK_GPL_KEY, and load_module().
 {
    ast_sip_unregister_endpoint_identifier(&anonymous_identifier);
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_DEFAULT , .description = "PJSIP Anonymous endpoint identifier" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .requires = "res_pjsip", } static
Definition at line 144 of file res_pjsip_endpoint_identifier_anonymous.c.
anonymous_identifier
struct ast_sip_endpoint_identifier anonymous_identifier static
Initial value:
= {
   .identify_endpoint = anonymous_identify,
}
Definition at line 123 of file res_pjsip_endpoint_identifier_anonymous.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 144 of file res_pjsip_endpoint_identifier_anonymous.c.