Asterisk - The Open Source Telephony Project: resource_events.c File Reference
resource_events.c File Reference
/api-docs/events.{format} implementation- WebSocket resource
#include "asterisk.h"
#include "resource_events.h"
#include "asterisk/astobj2.h"
#include "asterisk/http_websocket.h"
#include "asterisk/stasis_app.h"
#include "asterisk/vector.h"
Data Structures
struct event_session
A wrapper for the /ref ast_ari_websocket_session.
Macros
#define APPS_NUM_BUCKETS 7
#define EVENT_SESSION_NUM_BUCKETS 23
#define MESSAGES_INIT_SIZE 23
Enumerations
enum event_session_error_type { ERROR_TYPE_STASIS_REGISTRATION = 1, ERROR_TYPE_OOM = 2, ERROR_TYPE_MISSING_APP_PARAM = 3, ERROR_TYPE_INVALID_APP_PARAM = 4 }
event_session error types.
Functions
void ast_ari_events_user_event (struct ast_variable *headers, struct ast_ari_events_user_event_args *args, struct ast_ari_response *response)
Generate a user event.
int ast_ari_websocket_events_event_websocket_attempted (struct ast_tcptls_session_instance *ser, struct ast_variable *headers, struct ast_ari_events_event_websocket_args *args, const char *session_id)
WebSocket connection for events.
void ast_ari_websocket_events_event_websocket_dtor (void)
WebSocket connection for events.
void ast_ari_websocket_events_event_websocket_established (struct ast_ari_websocket_session *ws_session, struct ast_variable *headers, struct ast_ari_events_event_websocket_args *args)
WebSocket connection for events.
int ast_ari_websocket_events_event_websocket_init (void)
WebSocket connection for events.
static int event_session_alloc (struct ast_tcptls_session_instance *ser, struct ast_ari_events_event_websocket_args *args, const char *session_id)
Creates an event_session object and registers its apps with Stasis.
static int event_session_allocation_error_handler (struct event_session *session, enum event_session_error_type error, struct ast_tcptls_session_instance *ser)
Handles event_session error processing.
static void event_session_cleanup (struct event_session *session)
Processes cleanup actions for a event_session object.
static int event_session_compare (void *obj, void *arg, int flags)
AO2 comparison function for event_session objects.
static void event_session_dtor (void *obj)
Event session object destructor (event_session).
static int event_session_hash (const void *obj, const int flags)
AO2 hash function for event_session objects.
static void event_session_shutdown (struct event_session *session)
Explicitly shutdown a session.
static int event_session_shutdown_cb (void *session, void *arg, int flags)
static void event_session_update_websocket (struct event_session *session, struct ast_ari_websocket_session *ws_session)
Updates the websocket session for an event_session.
static void stasis_app_message_handler (void *data, const char *app_name, struct ast_json *message)
Callback handler for Stasis application messages.
Variables
static struct ao2_container * event_session_registry
Local registry for created event_session objects.
Detailed Description
/api-docs/events.{format} implementation- WebSocket resource
Author
David M. Lee, II dlee@.nosp@m.digi.nosp@m.um.co.nosp@m.m
Definition in file resource_events.c.
Macro Definition Documentation
APPS_NUM_BUCKETS
#define APPS_NUM_BUCKETS 7
Number of buckets for a websocket apps container. Remember to keep it a prime number!
Definition at line 42 of file resource_events.c.
Referenced by event_session_alloc().
EVENT_SESSION_NUM_BUCKETS
#define EVENT_SESSION_NUM_BUCKETS 23
Number of buckets for the event session registry. Remember to keep it a prime number!
Definition at line 39 of file resource_events.c.
Referenced by ast_ari_websocket_events_event_websocket_init().
MESSAGES_INIT_SIZE
#define MESSAGES_INIT_SIZE 23
Initial size of a message queue.
Definition at line 45 of file resource_events.c.
Referenced by event_session_alloc().
Enumeration Type Documentation
event_session_error_type
enum event_session_error_type
event_session error types.
Enumerator
ERROR_TYPE_STASIS_REGISTRATION
Stasis failed to register the application.
ERROR_TYPE_OOM
Insufficient memory to create the event session.
ERROR_TYPE_MISSING_APP_PARAM
HTTP request was missing an [app] parameter.
ERROR_TYPE_INVALID_APP_PARAM
HTTP request contained an invalid [app] parameter.
Definition at line 58 of file resource_events.c.
{
    ERROR_TYPE_STASIS_REGISTRATION = 1,  /*!< Stasis failed to register the application. */
    ERROR_TYPE_OOM = 2,                  /*!< Insufficient memory to create the event
                                              session. */
    ERROR_TYPE_MISSING_APP_PARAM = 3,    /*!< HTTP request was missing an [app] parameter. */
    ERROR_TYPE_INVALID_APP_PARAM = 4,    /*!< HTTP request contained an invalid [app]
                                              parameter. */
 };
Function Documentation
ast_ari_events_user_event()
void ast_ari_events_user_event (struct ast_variable * headers, struct ast_ari_events_user_event_args * args, struct ast_ari_response * response)
Generate a user event.
Parameters
headers HTTP headers
args Swagger parameters
[out] response HTTP response
Definition at line 532 of file resource_events.c.
References ast_ari_events_user_event_args::application, ast_ari_events_user_event_parse_body(), ast_ari_response_error(), ast_ari_response_no_content(), ast_json_object_get(), ast_strlen_zero, ast_ari_events_user_event_args::event_name, NULL, ast_ari_events_user_event_args::source, ast_ari_events_user_event_args::source_count, STASIS_APP_USER_APP_NOT_FOUND, stasis_app_user_event(), STASIS_APP_USER_EVENT_SOURCE_BAD_SCHEME, STASIS_APP_USER_EVENT_SOURCE_NOT_FOUND, STASIS_APP_USER_INTERNAL_ERROR, STASIS_APP_USER_OK, STASIS_APP_USER_USEREVENT_INVALID, and ast_ari_events_user_event_args::variables.
Referenced by ast_ari_events_user_event_cb().
 {
    enum stasis_app_user_event_res res;
    struct ast_json *json_variables = NULL;
    if (args->variables) {
       ast_ari_events_user_event_parse_body(args->variables, args);
       json_variables = ast_json_object_get(args->variables, "variables");
    }
    if (ast_strlen_zero(args->application)) {
       ast_ari_response_error(response, 400, "Bad Request",
          "Missing parameter application");
       return;
    }
    res = stasis_app_user_event(args->application,
       args->event_name,
       args->source, args->source_count,
       json_variables);
    switch (res) {
    case STASIS_APP_USER_OK:
       ast_ari_response_no_content(response);
       break;
    case STASIS_APP_USER_APP_NOT_FOUND:
       ast_ari_response_error(response, 404, "Not Found",
          "Application not found");
       break;
    case STASIS_APP_USER_EVENT_SOURCE_NOT_FOUND:
       ast_ari_response_error(response, 422, "Unprocessable Entity",
          "Event source was not found");
       break;
    case STASIS_APP_USER_EVENT_SOURCE_BAD_SCHEME:
       ast_ari_response_error(response, 400, "Bad Request",
          "Invalid event source URI scheme");
       break;
    case STASIS_APP_USER_USEREVENT_INVALID:
       ast_ari_response_error(response, 400, "Bad Request",
          "Invalid userevnet data");
       break;
    case STASIS_APP_USER_INTERNAL_ERROR:
    default:
       ast_ari_response_error(response, 500, "Internal Server Error",
          "Error processing request");
    }
 }
ast_ari_websocket_events_event_websocket_attempted()
int ast_ari_websocket_events_event_websocket_attempted (struct ast_tcptls_session_instance * ser, struct ast_variable * headers, struct ast_ari_events_event_websocket_args * args, const char * session_id)
WebSocket connection for events.
Parameters
ser HTTP TCP/TLS Server Session
headers HTTP headers
args Swagger parameters
session_id The id of the current session.
Return values
0 success
non-zero error
Definition at line 488 of file resource_events.c.
References ast_debug, and event_session_alloc().
Referenced by ast_ari_events_event_websocket_ws_attempted_cb().
 {
    ast_debug(3, "/events WebSocket attempted\n");
    /* Create the event session */
    return event_session_alloc(ser, args, session_id);
 }
ast_ari_websocket_events_event_websocket_dtor()
void ast_ari_websocket_events_event_websocket_dtor (void)
WebSocket connection for events.
Returns
Nothing
Definition at line 465 of file resource_events.c.
References ao2_callback, ao2_cleanup, event_session_shutdown_cb(), NULL, OBJ_MULTIPLE, and OBJ_NODATA.
Referenced by load_module(), and unload_module().
 {
    ao2_callback(event_session_registry, OBJ_MULTIPLE | OBJ_NODATA, event_session_shutdown_cb, NULL);
    ao2_cleanup(event_session_registry);
    event_session_registry = NULL;
 }
ast_ari_websocket_events_event_websocket_established()
void ast_ari_websocket_events_event_websocket_established (struct ast_ari_websocket_session * session, struct ast_variable * headers, struct ast_ari_events_event_websocket_args * args)
WebSocket connection for events.
Parameters
session ARI WebSocket.
headers HTTP headers.
args Swagger parameters.
session_id The id of the current session.
Definition at line 498 of file resource_events.c.
References ao2_find, ao2_ref, ao2_unlink, ast_ari_websocket_session_id(), ast_ari_websocket_session_read(), ast_assert, ast_debug, ast_json_unref(), ast_log, event_session_cleanup(), event_session_update_websocket(), LOG_WARNING, NULL, OBJ_SEARCH_KEY, and session.
Referenced by ast_ari_events_event_websocket_ws_established_cb().
 {
    struct event_session *session;
    struct ast_json *msg;
    const char *session_id;
    ast_debug(3, "/events WebSocket established\n");
    ast_assert(ws_session != NULL);
    session_id = ast_ari_websocket_session_id(ws_session);
    /* Find the event_session and update its websocket  */
    session = ao2_find(event_session_registry, session_id, OBJ_SEARCH_KEY);
    if (session) {
       ao2_unlink(event_session_registry, session);
       event_session_update_websocket(session, ws_session);
    } else {
       ast_log(LOG_WARNING,
          "Failed to locate an event session for the provided websocket session\n");
    }
    /* We don't process any input, but we'll consume it waiting for EOF */
    while ((msg = ast_ari_websocket_session_read(ws_session))) {
       ast_json_unref(msg);
    }
    event_session_cleanup(session);
    ao2_ref(session, -1);
 }
ast_ari_websocket_events_event_websocket_init()
int ast_ari_websocket_events_event_websocket_init (void)
WebSocket connection for events.
Return values
0 success
-1 error
Definition at line 473 of file resource_events.c.
References AO2_ALLOC_OPT_LOCK_MUTEX, ao2_container_alloc_hash, ast_log, event_session_compare(), event_session_hash(), EVENT_SESSION_NUM_BUCKETS, LOG_WARNING, and NULL.
Referenced by load_module().
 {
    /* Try to instantiate the registry */
    event_session_registry = ao2_container_alloc_hash(AO2_ALLOC_OPT_LOCK_MUTEX, 0,
       EVENT_SESSION_NUM_BUCKETS, event_session_hash, NULL, event_session_compare);
    if (!event_session_registry) {
       /* This is bad, bad. */
       ast_log(LOG_WARNING,
              "Failed to allocate the local registry for websocket applications\n");
       return -1;
    }
    return 0;
 }
event_session_alloc()
static int event_session_alloc (struct ast_tcptls_session_instance * ser, struct ast_ari_events_event_websocket_args * args, const char * session_id) static
Creates an event_session object and registers its apps with Stasis.
Definition at line 388 of file resource_events.c.
References ao2_alloc, ao2_cleanup, ao2_link, ast_ari_events_event_websocket_args::app, app, ast_ari_events_event_websocket_args::app_count, APPS_NUM_BUCKETS, ast_log, ast_str_container_add(), ast_str_container_alloc, ast_strlen_zero, AST_VECTOR_INIT, ERROR_TYPE_INVALID_APP_PARAM, ERROR_TYPE_MISSING_APP_PARAM, ERROR_TYPE_OOM, ERROR_TYPE_STASIS_REGISTRATION, event_session_allocation_error_handler(), event_session_dtor(), handler(), LOG_WARNING, MESSAGES_INIT_SIZE, NULL, RAII_VAR, session, stasis_app_message_handler(), stasis_app_register(), stasis_app_register_all(), and ast_ari_events_event_websocket_args::subscribe_all.
Referenced by ast_ari_websocket_events_event_websocket_attempted().
 {
    RAII_VAR(struct event_session *, session, NULL, ao2_cleanup);
    int (* register_handler)(const char *, stasis_app_cb handler, void *data);
    size_t size, i;
    /* The request must have at least one [app] parameter */
    if (args->app_count == 0) {
       return event_session_allocation_error_handler(
          session, ERROR_TYPE_MISSING_APP_PARAM, ser);
    }
    size = sizeof(*session) + strlen(session_id) + 1;
    /* Instantiate the event session */
    session = ao2_alloc(size, event_session_dtor);
    if (!session) {
       return event_session_allocation_error_handler(session, ERROR_TYPE_OOM, ser);
    }
    strncpy(session->session_id, session_id, size - sizeof(*session));
    /* Instantiate the hash table for Stasis apps */
    session->websocket_apps =
       ast_str_container_alloc(APPS_NUM_BUCKETS);
    if (!session->websocket_apps) {
       return event_session_allocation_error_handler(session, ERROR_TYPE_OOM, ser);
    }
    /* Instantiate the message queue */
    if (AST_VECTOR_INIT(&session->message_queue, MESSAGES_INIT_SIZE)) {
       return event_session_allocation_error_handler(session, ERROR_TYPE_OOM, ser);
    }
    /* Register the apps with Stasis */
    if (args->subscribe_all) {
       register_handler = &stasis_app_register_all;
    } else {
       register_handler = &stasis_app_register;
    }
    for (i = 0; i < args->app_count; ++i) {
       const char *app = args->app[i];
       if (ast_strlen_zero(app)) {
          return event_session_allocation_error_handler(
             session, ERROR_TYPE_INVALID_APP_PARAM, ser);
       }
       if (ast_str_container_add(session->websocket_apps, app)) {
          return event_session_allocation_error_handler(session, ERROR_TYPE_OOM, ser);
       }
       if (register_handler(app, stasis_app_message_handler, session)) {
          ast_log(LOG_WARNING, "Stasis registration failed for application: '%s'\n", app);
          return event_session_allocation_error_handler(
             session, ERROR_TYPE_STASIS_REGISTRATION, ser);
       }
    }
    /* Add the event session to the local registry */
    if (!ao2_link(event_session_registry, session)) {
       return event_session_allocation_error_handler(session, ERROR_TYPE_OOM, ser);
    }
    return 0;
 }
event_session_allocation_error_handler()
static int event_session_allocation_error_handler (struct event_session * session, enum event_session_error_type error, struct ast_tcptls_session_instance * ser) static
Handles event_session error processing.
Definition at line 339 of file resource_events.c.
References ast_http_error(), ERROR_TYPE_INVALID_APP_PARAM, ERROR_TYPE_MISSING_APP_PARAM, ERROR_TYPE_OOM, ERROR_TYPE_STASIS_REGISTRATION, and event_session_cleanup().
Referenced by event_session_alloc().
 {
    /* Notify the client */
    switch (error) {
    case ERROR_TYPE_STASIS_REGISTRATION:
       ast_http_error(ser, 500, "Internal Server Error",
          "Stasis registration failed");
       break;
    case ERROR_TYPE_OOM:
       ast_http_error(ser, 500, "Internal Server Error",
          "Allocation failed");
       break;
    case ERROR_TYPE_MISSING_APP_PARAM:
       ast_http_error(ser, 400, "Bad Request",
          "HTTP request is missing param: [app]");
       break;
    case ERROR_TYPE_INVALID_APP_PARAM:
       ast_http_error(ser, 400, "Bad Request",
          "Invalid application provided in param [app].");
       break;
    default:
       break;
    }
    /* Cleanup the session */
    event_session_cleanup(session);
    return -1;
 }
event_session_cleanup()
static void event_session_cleanup (struct event_session * session) static
Processes cleanup actions for a event_session object.
Definition at line 297 of file resource_events.c.
References ao2_unlink, and event_session_shutdown().
Referenced by ast_ari_websocket_events_event_websocket_established(), event_session_allocation_error_handler(), and event_session_shutdown_cb().
 {
    if (!session) {
       return;
    }
    event_session_shutdown(session);
    if (event_session_registry) {
       ao2_unlink(event_session_registry, session);
    }
 }
event_session_compare()
static int event_session_compare (void * obj, void * arg, int flags) static
AO2 comparison function for event_session objects.
Definition at line 153 of file resource_events.c.
References CMP_MATCH, OBJ_SEARCH_KEY, OBJ_SEARCH_MASK, OBJ_SEARCH_OBJECT, and OBJ_SEARCH_PARTIAL_KEY.
Referenced by ast_ari_websocket_events_event_websocket_init().
 {
    const struct event_session *object_left = obj;
    const struct event_session *object_right = arg;
    const char *right_key = arg;
    int cmp = 0;
    switch (flags & OBJ_SEARCH_MASK) {
    case OBJ_SEARCH_OBJECT:
       right_key = object_right->session_id;
       /* Fall through */
    case OBJ_SEARCH_KEY:
       cmp = strcmp(object_left->session_id, right_key);
       break;
    case OBJ_SEARCH_PARTIAL_KEY:
       cmp = strncmp(object_left->session_id, right_key, strlen(right_key));
       break;
    default:
       break;
    }
    return cmp ? 0 : CMP_MATCH;
 }
event_session_dtor()
static void event_session_dtor (void * obj) static
Event session object destructor (event_session).
Definition at line 316 of file resource_events.c.
References ast_assert, AST_VECTOR_SIZE, NULL, session, event_session::websocket_apps, and event_session::ws_session.
Referenced by event_session_alloc().
 {
 #ifdef AST_DEVMODE /* Avoid unused variable warning */
    struct event_session *session = obj;
 #endif
    /* event_session_shutdown should have been called before now */
    ast_assert(session->ws_session == NULL);
    ast_assert(session->websocket_apps == NULL);
    ast_assert(AST_VECTOR_SIZE(&session->message_queue) == 0);
 }
event_session_hash()
static int event_session_hash (const void * obj, const int flags) static
AO2 hash function for event_session objects.
Computes hash value for the given event_session, with respect to the provided search flags.
Definition at line 191 of file resource_events.c.
References ast_assert, ast_str_hash(), OBJ_SEARCH_KEY, OBJ_SEARCH_MASK, OBJ_SEARCH_OBJECT, and session.
Referenced by ast_ari_websocket_events_event_websocket_init().
 {
    const struct event_session *session;
    const char *key;
    switch (flags & OBJ_SEARCH_MASK) {
    case OBJ_SEARCH_KEY:
       key = obj;
       break;
    case OBJ_SEARCH_OBJECT:
       session = obj;
       key = session->session_id;
       break;
    default:
       /* Hash can only work on something with a full key. */
       ast_assert(0);
       return 0;
    }
    return ast_str_hash(key);
 }
event_session_shutdown()
static void event_session_shutdown (struct event_session * session) static
Explicitly shutdown a session.
An explicit shutdown is necessary, since the stasis_app has a reference to this session. We also need to be sure to null out the ws_session field, since the websocket is about to go away.
Definition at line 223 of file resource_events.c.
References ao2_cleanup, ao2_iterator_destroy(), ao2_iterator_init(), ao2_iterator_next, app, ast_json_unref(), AST_VECTOR_FREE, AST_VECTOR_GET, AST_VECTOR_SIZE, lock, NULL, SCOPED_AO2LOCK, stasis_app_unregister(), event_session::websocket_apps, and event_session::ws_session.
Referenced by event_session_cleanup().
 {
    struct ao2_iterator i;
    char *app;
    int j;
    SCOPED_AO2LOCK(lock, session);
    /* Clean up the websocket_apps container */
    if (session->websocket_apps) {
       i = ao2_iterator_init(session->websocket_apps, 0);
       while ((app = ao2_iterator_next(&i))) {
          stasis_app_unregister(app);
          ao2_cleanup(app);
       }
       ao2_iterator_destroy(&i);
       ao2_cleanup(session->websocket_apps);
       session->websocket_apps = NULL;
    }
    /* Clean up the message_queue container */
    for (j = 0; j < AST_VECTOR_SIZE(&session->message_queue); j++) {
       struct ast_json *msg = AST_VECTOR_GET(&session->message_queue, j);
       ast_json_unref(msg);
    }
    AST_VECTOR_FREE(&session->message_queue);
    /* Remove the handle to the underlying websocket session */
    session->ws_session = NULL;
 }
event_session_shutdown_cb()
static int event_session_shutdown_cb (void * session, void * arg, int flags) static
Definition at line 458 of file resource_events.c.
References event_session_cleanup().
Referenced by ast_ari_websocket_events_event_websocket_dtor().
 {
    event_session_cleanup(session);
    return 0;
 }
event_session_update_websocket()
static void event_session_update_websocket (struct event_session * session, struct ast_ari_websocket_session * ws_session) static
Updates the websocket session for an event_session.
The websocket for the given event_session will be updated to the value of the ws_session argument.
If the value of the ws_session is not NULL and there are messages in the event session's message_queue, the messages are dispatched and removed from the queue.
Definition at line 269 of file resource_events.c.
References ao2_lock, ao2_unlock, ast_ari_websocket_session_write(), ast_assert, ast_json_unref(), AST_VECTOR_ELEM_CLEANUP_NOOP, AST_VECTOR_GET, AST_VECTOR_RESET, AST_VECTOR_SIZE, NULL, and event_session::ws_session.
Referenced by ast_ari_websocket_events_event_websocket_established().
 {
    int i;
    ast_assert(session != NULL);
    ao2_lock(session);
    session->ws_session = ws_session;
    for (i = 0; i < AST_VECTOR_SIZE(&session->message_queue); i++) {
       struct ast_json *msg = AST_VECTOR_GET(&session->message_queue, i);
       ast_ari_websocket_session_write(session->ws_session, msg);
       ast_json_unref(msg);
    }
    AST_VECTOR_RESET(&session->message_queue, AST_VECTOR_ELEM_CLEANUP_NOOP);
    ao2_unlock(session);
 }
stasis_app_message_handler()
static void stasis_app_message_handler (void * data, const char * app_name, struct ast_json * message) static
Callback handler for Stasis application messages.
Definition at line 79 of file resource_events.c.
References ao2_find, ao2_lock, ao2_unlock, ast_ari_json_format(), ast_ari_websocket_session_get_remote_addr(), ast_ari_websocket_session_write(), ast_assert, ast_json_dump_string_format(), ast_json_free(), ast_json_object_get(), ast_json_object_set(), ast_json_ref(), ast_json_string_create(), ast_json_string_get(), ast_log, ast_sockaddr_stringify(), AST_VECTOR_APPEND, ast_verbose(), LOG_WARNING, NULL, OBJ_NODATA, OBJ_UNLINK, S_OR, session, stasis_app_event_allowed(), stasis_app_get_debug_by_name(), str, event_session::websocket_apps, and event_session::ws_session.
Referenced by event_session_alloc().
 {
    struct event_session *session = data;
    const char *msg_type, *msg_application;
    int app_debug_enabled;
    ast_assert(session != NULL);
    /*
     * We need to get the debug flag before lockinf session
     * to help prevent a deadlock with the apps_registry container.
     */
    app_debug_enabled = stasis_app_get_debug_by_name(app_name);
    ao2_lock(session);
    msg_type = S_OR(ast_json_string_get(ast_json_object_get(message, "type")), "");
    msg_application = S_OR(
       ast_json_string_get(ast_json_object_get(message, "application")), "");
    /* If we've been replaced, remove the application from our local
       websocket_apps container */
    if (strcmp(msg_type, "ApplicationReplaced") == 0 &&
       strcmp(msg_application, app_name) == 0) {
       ao2_find(session->websocket_apps, msg_application,
          OBJ_UNLINK | OBJ_NODATA);
    }
    /* Now, we need to determine our state to see how we will handle the message */
    if (ast_json_object_set(message, "application", ast_json_string_create(app_name))) {
       /* We failed to add an application element to our json message */
       ast_log(LOG_WARNING,
               "Failed to dispatch '%s' message from Stasis app '%s'; could not update message\n",
               msg_type,
               msg_application);
    } else if (!session->ws_session) {
       /* If the websocket is NULL, the message goes to the queue */
       if (!AST_VECTOR_APPEND(&session->message_queue, message)) {
          ast_json_ref(message);
       }
       ast_log(LOG_WARNING,
             "Queued '%s' message for Stasis app '%s'; websocket is not ready\n",
             msg_type,
             msg_application);
    } else if (stasis_app_event_allowed(app_name, message)) {
       if (app_debug_enabled) {
          char *str = ast_json_dump_string_format(message, ast_ari_json_format());
          ast_verbose("<--- Sending ARI event to %s --->\n%s\n",
             ast_sockaddr_stringify(ast_ari_websocket_session_get_remote_addr(session->ws_session)),
             str);
          ast_json_free(str);
       }
       /* We are ready to publish the message */
       ast_ari_websocket_session_write(session->ws_session, message);
    }
    ao2_unlock(session);
 }
Variable Documentation
event_session_registry
struct ao2_container* event_session_registry static
Local registry for created event_session objects.
Definition at line 68 of file resource_events.c.