Asterisk - The Open Source Telephony Project: test_conversions.c File Reference
test_conversions.c File Reference
Conversions Unit Tests.
#include "asterisk.h"
#include "asterisk/test.h"
#include "asterisk/module.h"
#include "asterisk/conversions.h"
Macros
#define CATEGORY "/main/conversions/"
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
AST_TEST_DEFINE (str_to_int)
AST_TEST_DEFINE (str_to_uint)
AST_TEST_DEFINE (str_to_long)
AST_TEST_DEFINE (str_to_ulong)
AST_TEST_DEFINE (str_to_imax)
AST_TEST_DEFINE (str_to_umax)
static int load_module (void)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Conversions test module" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, }
static const struct ast_module_info * ast_module_info = &__mod_info
Detailed Description
Conversions Unit Tests.
Author
Kevin Harwell kharw.nosp@m.ell@.nosp@m.digiu.nosp@m.m.co.nosp@m.m
Definition in file test_conversions.c.
Macro Definition Documentation
CATEGORY
#define CATEGORY "/main/conversions/"
Definition at line 38 of file test_conversions.c.
Referenced by AST_TEST_DEFINE().
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 333 of file test_conversions.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 333 of file test_conversions.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 333 of file test_conversions.c.
AST_TEST_DEFINE() [1/6]
AST_TEST_DEFINE (str_to_int)
Definition at line 40 of file test_conversions.c.
References ast_str_to_int(), AST_TEST_NOT_RUN, AST_TEST_PASS, CATEGORY, sip_to_pjsip::info(), NULL, str, TEST_EXECUTE, and TEST_INIT.
 {
    const char *invalid = "abc";
    const char *invalid_partial = "7abc";
    const char *negative = "-7";
    const char *negative_spaces = "  -7";
    const char *negative_out_of_range = "-9999999999";
    const char *out_of_range = "9999999999";
    const char *spaces = "  ";
    const char *valid = "7";
    const char *valid_spaces = "  7";
    int val;
    char str[64];
    switch (cmd) {
    case TEST_INIT:
       info->name = __func__;
       info->category = CATEGORY;
       info->summary = "convert a string to a signed integer";
       info->description = info->summary;
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    ast_test_validate(test, ast_str_to_int(NULL, &val));
    ast_test_validate(test, ast_str_to_int("\0", &val));
    ast_test_validate(test, ast_str_to_int(invalid, &val));
    ast_test_validate(test, ast_str_to_int(invalid_partial, &val));
    ast_test_validate(test, !ast_str_to_int(negative, &val));
    ast_test_validate(test, !ast_str_to_int(negative_spaces, &val));
    ast_test_validate(test, ast_str_to_int(negative_out_of_range, &val));
    ast_test_validate(test, ast_str_to_int(out_of_range, &val));
    ast_test_validate(test, ast_str_to_int(spaces, &val));
    ast_test_validate(test, !ast_str_to_int(valid, &val));
    ast_test_validate(test, !ast_str_to_int(valid_spaces, &val));
    ast_test_validate(test, snprintf(str, sizeof(str), "%d", INT_MAX) > 0);
    ast_test_validate(test, !ast_str_to_int(str, &val));
    ast_test_validate(test, val == INT_MAX);
    ast_test_validate(test, snprintf(str, sizeof(str), "%d", INT_MIN) > 0);
    ast_test_validate(test, !ast_str_to_int(str, &val));
    ast_test_validate(test, val == INT_MIN);
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [2/6]
AST_TEST_DEFINE (str_to_uint)
Definition at line 88 of file test_conversions.c.
References ast_str_to_uint(), AST_TEST_NOT_RUN, AST_TEST_PASS, CATEGORY, sip_to_pjsip::info(), NULL, str, TEST_EXECUTE, and TEST_INIT.
 {
    const char *invalid = "abc";
    const char *invalid_partial = "7abc";
    const char *negative = "-7";
    const char *negative_spaces = "  -7";
    const char *out_of_range = "9999999999";
    const char *spaces = "  ";
    const char *valid = "7";
    const char *valid_spaces = "  7";
    unsigned int val;
    char str[64];
    switch (cmd) {
    case TEST_INIT:
       info->name = __func__;
       info->category = CATEGORY;
       info->summary = "convert a string to an unsigned integer";
       info->description = info->summary;
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    ast_test_validate(test, ast_str_to_uint(NULL, &val));
    ast_test_validate(test, ast_str_to_uint("\0", &val));
    ast_test_validate(test, ast_str_to_uint(invalid, &val));
    ast_test_validate(test, ast_str_to_uint(invalid_partial, &val));
    ast_test_validate(test, ast_str_to_uint(negative, &val));
    ast_test_validate(test, ast_str_to_uint(negative_spaces, &val));
    ast_test_validate(test, ast_str_to_uint(out_of_range, &val));
    ast_test_validate(test, ast_str_to_uint(spaces, &val));
    ast_test_validate(test, !ast_str_to_uint(valid, &val));
    ast_test_validate(test, !ast_str_to_uint(valid_spaces, &val));
    ast_test_validate(test, snprintf(str, sizeof(str), "%u", UINT_MAX) > 0);
    ast_test_validate(test, !ast_str_to_uint(str, &val));
    ast_test_validate(test, val == UINT_MAX);
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [3/6]
AST_TEST_DEFINE (str_to_long)
Definition at line 130 of file test_conversions.c.
References ast_str_to_long(), AST_TEST_NOT_RUN, AST_TEST_PASS, CATEGORY, sip_to_pjsip::info(), NULL, str, TEST_EXECUTE, and TEST_INIT.
 {
    const char *invalid = "abc";
    const char *invalid_partial = "7abc";
    const char *negative = "-7";
    const char *negative_spaces = "  -7";
    const char *negative_out_of_range = "-99999999999999999999";
    const char *out_of_range = "99999999999999999999";
    const char *spaces = "  ";
    const char *valid = "7";
    const char *valid_spaces = "  7";
    long val;
    char str[64];
    switch (cmd) {
    case TEST_INIT:
       info->name = __func__;
       info->category = CATEGORY;
       info->summary = "convert a string to a signed long";
       info->description = info->summary;
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    ast_test_validate(test, ast_str_to_long(NULL, &val));
    ast_test_validate(test, ast_str_to_long("\0", &val));
    ast_test_validate(test, ast_str_to_long(invalid, &val));
    ast_test_validate(test, ast_str_to_long(invalid_partial, &val));
    ast_test_validate(test, !ast_str_to_long(negative, &val));
    ast_test_validate(test, !ast_str_to_long(negative_spaces, &val));
    ast_test_validate(test, ast_str_to_long(negative_out_of_range, &val));
    ast_test_validate(test, ast_str_to_long(out_of_range, &val));
    ast_test_validate(test, ast_str_to_long(spaces, &val));
    ast_test_validate(test, !ast_str_to_long(valid, &val));
    ast_test_validate(test, !ast_str_to_long(valid_spaces, &val));
    ast_test_validate(test, snprintf(str, sizeof(str), "%ld", LONG_MAX) > 0);
    ast_test_validate(test, !ast_str_to_long(str, &val));
    ast_test_validate(test, val == LONG_MAX);
    ast_test_validate(test, snprintf(str, sizeof(str), "%ld", LONG_MIN) > 0);
    ast_test_validate(test, !ast_str_to_long(str, &val));
    ast_test_validate(test, val == LONG_MIN);
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [4/6]
AST_TEST_DEFINE (str_to_ulong)
Definition at line 178 of file test_conversions.c.
References ast_str_to_ulong(), AST_TEST_NOT_RUN, AST_TEST_PASS, CATEGORY, sip_to_pjsip::info(), NULL, str, TEST_EXECUTE, and TEST_INIT.
 {
    const char *invalid = "abc";
    const char *invalid_partial = "7abc";
    const char *negative = "-7";
    const char *negative_spaces = "  -7";
    const char *out_of_range = "99999999999999999999";
    const char *spaces = "  ";
    const char *valid = "7";
    const char *valid_spaces = "  7";
    unsigned long val;
    char str[64];
    switch (cmd) {
    case TEST_INIT:
       info->name = __func__;
       info->category = CATEGORY;
       info->summary = "convert a string to an unsigned long";
       info->description = info->summary;
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    ast_test_validate(test, ast_str_to_ulong(NULL, &val));
    ast_test_validate(test, ast_str_to_ulong("\0", &val));
    ast_test_validate(test, ast_str_to_ulong(invalid, &val));
    ast_test_validate(test, ast_str_to_ulong(invalid_partial, &val));
    ast_test_validate(test, ast_str_to_ulong(negative, &val));
    ast_test_validate(test, ast_str_to_ulong(negative_spaces, &val));
    ast_test_validate(test, ast_str_to_ulong(out_of_range, &val));
    ast_test_validate(test, ast_str_to_ulong(spaces, &val));
    ast_test_validate(test, !ast_str_to_ulong(valid, &val));
    ast_test_validate(test, !ast_str_to_ulong(valid_spaces, &val));
    ast_test_validate(test, snprintf(str, sizeof(str), "%lu", ULONG_MAX) > 0);
    ast_test_validate(test, !ast_str_to_ulong(str, &val));
    ast_test_validate(test, val == ULONG_MAX);
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [5/6]
AST_TEST_DEFINE (str_to_imax)
Definition at line 220 of file test_conversions.c.
References ast_str_to_imax(), AST_TEST_NOT_RUN, AST_TEST_PASS, CATEGORY, sip_to_pjsip::info(), NULL, str, TEST_EXECUTE, and TEST_INIT.
 {
    const char *invalid = "abc";
    const char *invalid_partial = "7abc";
    const char *negative = "-7";
    const char *negative_spaces = "  -7";
    const char *negative_out_of_range = "-99999999999999999999999999999999999999999999999999";
    const char *out_of_range = "99999999999999999999999999999999999999999999999999";
    const char *spaces = "  ";
    const char *valid = "7";
    const char *valid_spaces = "  7";
    intmax_t val;
    char str[64];
    switch (cmd) {
    case TEST_INIT:
       info->name = __func__;
       info->category = CATEGORY;
       info->summary = "convert a string to a signed max size integer";
       info->description = info->summary;
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    ast_test_validate(test, ast_str_to_imax(NULL, &val));
    ast_test_validate(test, ast_str_to_imax("\0", &val));
    ast_test_validate(test, ast_str_to_imax(invalid, &val));
    ast_test_validate(test, ast_str_to_imax(invalid_partial, &val));
    ast_test_validate(test, !ast_str_to_imax(negative, &val));
    ast_test_validate(test, !ast_str_to_imax(negative_spaces, &val));
    ast_test_validate(test, ast_str_to_imax(negative_out_of_range, &val));
    ast_test_validate(test, ast_str_to_imax(out_of_range, &val));
    ast_test_validate(test, ast_str_to_imax(spaces, &val));
    ast_test_validate(test, !ast_str_to_imax(valid, &val));
    ast_test_validate(test, !ast_str_to_imax(valid_spaces, &val));
    ast_test_validate(test, snprintf(str, sizeof(str), "%jd", INTMAX_MAX) > 0);
    ast_test_validate(test, !ast_str_to_imax(str, &val));
    ast_test_validate(test, val == INTMAX_MAX);
    ast_test_validate(test, snprintf(str, sizeof(str), "%jd", INTMAX_MIN) > 0);
    ast_test_validate(test, !ast_str_to_imax(str, &val));
    ast_test_validate(test, val == INTMAX_MIN);
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [6/6]
AST_TEST_DEFINE (str_to_umax)
Definition at line 269 of file test_conversions.c.
References ast_str_to_umax(), AST_TEST_NOT_RUN, AST_TEST_PASS, CATEGORY, sip_to_pjsip::info(), NULL, str, TEST_EXECUTE, and TEST_INIT.
 {
    const char *invalid = "abc";
    const char *invalid_partial = "7abc";
    const char *negative = "-7";
    const char *negative_spaces = "  -7";
    const char *out_of_range = "99999999999999999999999999999999999999999999999999";
    const char *spaces = "  ";
    const char *valid = "7";
    const char *valid_spaces = "  7";
    uintmax_t val;
    char str[64];
    switch (cmd) {
    case TEST_INIT:
       info->name = __func__;
       info->category = CATEGORY;
       info->summary = "convert a string to an unsigned max size integer";
       info->description = info->summary;
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    ast_test_validate(test, ast_str_to_umax(NULL, &val));
    ast_test_validate(test, ast_str_to_umax("\0", &val));
    ast_test_validate(test, ast_str_to_umax(invalid, &val));
    ast_test_validate(test, ast_str_to_umax(invalid_partial, &val));
    ast_test_validate(test, ast_str_to_umax(negative, &val));
    ast_test_validate(test, ast_str_to_umax(negative_spaces, &val));
    ast_test_validate(test, ast_str_to_umax(out_of_range, &val));
    ast_test_validate(test, ast_str_to_umax(spaces, &val));
    ast_test_validate(test, !ast_str_to_umax(valid, &val));
    ast_test_validate(test, !ast_str_to_umax(valid_spaces, &val));
    ast_test_validate(test, snprintf(str, sizeof(str), "%ju", UINTMAX_MAX) > 0);
    ast_test_validate(test, !ast_str_to_umax(str, &val));
    ast_test_validate(test, val == UINTMAX_MAX);
    return AST_TEST_PASS;
 }
load_module()
static int load_module (void) static
Definition at line 311 of file test_conversions.c.
References AST_MODULE_LOAD_SUCCESS, and AST_TEST_REGISTER.
 {
    AST_TEST_REGISTER(str_to_int);
    AST_TEST_REGISTER(str_to_uint);
    AST_TEST_REGISTER(str_to_long);
    AST_TEST_REGISTER(str_to_ulong);
    AST_TEST_REGISTER(str_to_imax);
    AST_TEST_REGISTER(str_to_umax);
    return AST_MODULE_LOAD_SUCCESS;
 }
unload_module()
static int unload_module (void) static
Definition at line 322 of file test_conversions.c.
References AST_TEST_UNREGISTER.
 {
    AST_TEST_UNREGISTER(str_to_int);
    AST_TEST_UNREGISTER(str_to_uint);
    AST_TEST_UNREGISTER(str_to_long);
    AST_TEST_UNREGISTER(str_to_ulong);
    AST_TEST_UNREGISTER(str_to_imax);
    AST_TEST_UNREGISTER(str_to_umax);
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Conversions test module" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, } static
Definition at line 333 of file test_conversions.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 333 of file test_conversions.c.