Asterisk - The Open Source Telephony Project: app_originate.c File Reference
app_originate.c File Reference
Dial plan applications
Originate application.
#include "asterisk.h"
#include "asterisk/file.h"
#include "asterisk/channel.h"
#include "asterisk/pbx.h"
#include "asterisk/module.h"
#include "asterisk/app.h"
#include "asterisk/format_cache.h"
Enumerations
enum {
OPT_PREDIAL_CALLEE = (1 << 0), OPT_PREDIAL_CALLER = (1 << 1), OPT_ASYNC = (1 << 2), OPT_CALLER_NUM = (1 << 3),
OPT_CALLER_NAME = (1 << 4), OPT_CODECS = (1 << 5), OPT_VARIABLES = (1 << 6)
}
enum {
OPT_ARG_PREDIAL_CALLEE, OPT_ARG_PREDIAL_CALLER, OPT_ARG_CALLER_NUM, OPT_ARG_CALLER_NAME,
OPT_ARG_CODECS, OPT_ARG_VARIABLES, OPT_ARG_ARRAY_SIZE
}
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int load_module (void)
static int originate_exec (struct ast_channel *chan, const char *data)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Originate call" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, }
static const char app_originate [] = "Originate"
static const struct ast_module_info * ast_module_info = &__mod_info
static const struct ast_app_option originate_exec_options [128] = { [ 'a' ] = { .flag = OPT_ASYNC }, [ 'b' ] = { .flag = OPT_PREDIAL_CALLEE , .arg_index = OPT_ARG_PREDIAL_CALLEE + 1 }, [ 'B' ] = { .flag = OPT_PREDIAL_CALLER , .arg_index = OPT_ARG_PREDIAL_CALLER + 1 }, [ 'C' ] = { .flag = OPT_CODECS , .arg_index = OPT_ARG_CODECS + 1 }, [ 'c' ] = { .flag = OPT_CALLER_NUM , .arg_index = OPT_ARG_CALLER_NUM + 1 }, [ 'n' ] = { .flag = OPT_CALLER_NAME , .arg_index = OPT_ARG_CALLER_NAME + 1 }, [ 'v' ] = { .flag = OPT_VARIABLES , .arg_index = OPT_ARG_VARIABLES + 1 }, }
Detailed Description
Originate application.
Author
Roberto Casas rober.nosp@m.to.c.nosp@m.asas@.nosp@m.diap.nosp@m.le.co.nosp@m.m
Russell Bryant russe.nosp@m.ll@d.nosp@m.igium.nosp@m..com
Definition in file app_originate.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
OPT_PREDIAL_CALLEE
OPT_PREDIAL_CALLER
OPT_ASYNC
OPT_CALLER_NUM
OPT_CALLER_NAME
OPT_CODECS
OPT_VARIABLES
Definition at line 142 of file app_originate.c.
      {
    OPT_PREDIAL_CALLEE =    (1 << 0),
    OPT_PREDIAL_CALLER =    (1 << 1),
    OPT_ASYNC =             (1 << 2),
    OPT_CALLER_NUM =        (1 << 3),
    OPT_CALLER_NAME =       (1 << 4),
    OPT_CODECS =            (1 << 5),
    OPT_VARIABLES =         (1 << 6),
 };
anonymous enum
anonymous enum
Enumerator
OPT_ARG_PREDIAL_CALLEE
OPT_ARG_PREDIAL_CALLER
OPT_ARG_CALLER_NUM
OPT_ARG_CALLER_NAME
OPT_ARG_CODECS
OPT_ARG_VARIABLES
OPT_ARG_ARRAY_SIZE
Definition at line 152 of file app_originate.c.
      {
    OPT_ARG_PREDIAL_CALLEE,
    OPT_ARG_PREDIAL_CALLER,
    OPT_ARG_CALLER_NUM,
    OPT_ARG_CALLER_NAME,
    OPT_ARG_CODECS,
    OPT_ARG_VARIABLES,
    /* note: this entry _MUST_ be the last one in the enum */
    OPT_ARG_ARRAY_SIZE,
 };
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 410 of file app_originate.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 410 of file app_originate.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 410 of file app_originate.c.
load_module()
static int load_module (void) static
Definition at line 401 of file app_originate.c.
References app_originate, AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, ast_register_application_xml, and originate_exec().
 {
    int res;
    res = ast_register_application_xml(app_originate, originate_exec);
    return res ? AST_MODULE_LOAD_DECLINE : AST_MODULE_LOAD_SUCCESS;
 }
originate_exec()
static int originate_exec (struct ast_channel * chan, const char * data) static
Definition at line 173 of file app_originate.c.
References ao2_cleanup, args, AST_APP_ARG, ast_app_exec_sub(), ast_app_parse_options64(), ast_autoservice_start(), ast_autoservice_stop(), ast_channel_caller(), AST_CONTROL_ANSWER, AST_CONTROL_BUSY, AST_CONTROL_CONGESTION, AST_CONTROL_HANGUP, AST_CONTROL_RINGING, ast_debug, AST_DECLARE_APP_ARGS, ast_format_cap_alloc, ast_format_cap_append, AST_FORMAT_CAP_FLAG_DEFAULT, ast_format_cap_remove_by_type(), ast_format_cap_update_by_allow_disallow(), ast_format_slin, ast_log, AST_MEDIA_TYPE_UNKNOWN, AST_OUTGOING_NO_WAIT, AST_OUTGOING_WAIT, ast_pbx_outgoing_app_predial(), ast_pbx_outgoing_exten_predial(), ast_replace_subargument_delimiter(), AST_STANDARD_APP_ARGS, ast_strdupa, ast_strlen_zero, ast_strsep(), ast_test_flag64, ast_variable_list_append, ast_variable_new, ast_variables_destroy(), cid_name, cid_num, exten, ast_party_caller::id, LOG_ERROR, LOG_NOTICE, LOG_WARNING, name, ast_party_id::name, NULL, ast_party_id::number, OPT_ARG_ARRAY_SIZE, OPT_ARG_CALLER_NAME, OPT_ARG_CALLER_NUM, OPT_ARG_CODECS, OPT_ARG_PREDIAL_CALLEE, OPT_ARG_PREDIAL_CALLER, OPT_ARG_VARIABLES, OPT_ASYNC, OPT_CALLER_NAME, OPT_CALLER_NUM, OPT_CODECS, OPT_PREDIAL_CALLEE, OPT_PREDIAL_CALLER, OPT_VARIABLES, options, originate_exec_options, parse(), pbx_builtin_setvar_helper(), priority, S_OR, ast_party_name::str, ast_party_number::str, strsep(), text, timeout, type, and var.
Referenced by load_module().
 {
    AST_DECLARE_APP_ARGS(args,
       AST_APP_ARG(tech_data);
       AST_APP_ARG(type);
       AST_APP_ARG(arg1);
       AST_APP_ARG(arg2);
       AST_APP_ARG(arg3);
       AST_APP_ARG(timeout);
       AST_APP_ARG(options);
    );
    struct ast_flags64 opts = { 0, };
    char *opt_args[OPT_ARG_ARRAY_SIZE];
    char *predial_callee = NULL;
    char *parse, *cnum = NULL, *cname = NULL;
    struct ast_variable *vars = NULL;
    char *chantech, *chandata;
    int res = -1;
    int continue_in_dialplan = 0;
    int outgoing_status = 0;
    unsigned int timeout = 30;
    static const char default_exten[] = "s";
    struct ast_format_cap *capabilities;
    capabilities = ast_format_cap_alloc(AST_FORMAT_CAP_FLAG_DEFAULT);
    ast_autoservice_start(chan);
    if (!capabilities) {
       goto return_cleanup;
    }
    ast_format_cap_append(capabilities, ast_format_slin, 0);
    if (ast_strlen_zero(data)) {
       ast_log(LOG_ERROR, "Originate() requires arguments\n");
       goto return_cleanup;
    }
    parse = ast_strdupa(data);
    AST_STANDARD_APP_ARGS(args, parse);
    if (args.argc < 3) {
       ast_log(LOG_ERROR, "Incorrect number of arguments\n");
       goto return_cleanup;
    }
    if (!ast_strlen_zero(args.timeout)) {
       if(sscanf(args.timeout, "%u", &timeout) != 1) {
          ast_log(LOG_NOTICE, "Invalid timeout: '%s'. Setting timeout to 30 seconds\n", args.timeout);
          timeout = 30;
       }
    }
    chandata = ast_strdupa(args.tech_data);
    chantech = strsep(&chandata, "/");
    if (ast_strlen_zero(chandata) || ast_strlen_zero(chantech)) {
       ast_log(LOG_ERROR, "Channel Tech/Data invalid: '%s'\n", args.tech_data);
       goto return_cleanup;
    }
    if (!ast_strlen_zero(args.options) &&
       ast_app_parse_options64(originate_exec_options, &opts, opt_args, args.options)) {
       ast_log(LOG_ERROR, "Invalid options: '%s'\n", args.options);
       goto return_cleanup;
    }
    /* PREDIAL: Run gosub on the caller's channel */
    if (ast_test_flag64(&opts, OPT_PREDIAL_CALLER)
       && !ast_strlen_zero(opt_args[OPT_ARG_PREDIAL_CALLER])) {
       ast_replace_subargument_delimiter(opt_args[OPT_ARG_PREDIAL_CALLER]);
       ast_app_exec_sub(NULL, chan, opt_args[OPT_ARG_PREDIAL_CALLER], 0);
    }
    if (ast_test_flag64(&opts, OPT_PREDIAL_CALLEE)
       && !ast_strlen_zero(opt_args[OPT_ARG_PREDIAL_CALLEE])) {
       ast_replace_subargument_delimiter(opt_args[OPT_ARG_PREDIAL_CALLEE]);
       predial_callee = opt_args[OPT_ARG_PREDIAL_CALLEE];
    }
    if (strcasecmp(args.type, "exten") && strcasecmp(args.type, "app")) {
       ast_log(LOG_ERROR, "Incorrect type, it should be 'exten' or 'app': %s\n",
             args.type);
       goto return_cleanup;
    }
    if (ast_test_flag64(&opts, OPT_CODECS)) {
       if (!ast_strlen_zero(opt_args[OPT_ARG_CODECS])) {
          ast_format_cap_remove_by_type(capabilities, AST_MEDIA_TYPE_UNKNOWN);
          ast_format_cap_update_by_allow_disallow(capabilities, opt_args[OPT_ARG_CODECS], 1);
       }
    }
    if (ast_test_flag64(&opts, OPT_CALLER_NUM)) {
       if (!ast_strlen_zero(opt_args[OPT_ARG_CALLER_NUM])) {
          cnum = opt_args[OPT_ARG_CALLER_NUM];
       } else if (ast_channel_caller(chan)->id.number.str) {
          cnum = ast_channel_caller(chan)->id.number.str;
       }
    }
    if (ast_test_flag64(&opts, OPT_CALLER_NAME)) {
       if (!ast_strlen_zero(opt_args[OPT_ARG_CALLER_NAME])) {
          cname = opt_args[OPT_ARG_CALLER_NAME];
       } else if (ast_channel_caller(chan)->id.name.str) {
          cname = ast_channel_caller(chan)->id.name.str;
       }
    }
    /* Assign variables */
    if (ast_test_flag64(&opts, OPT_VARIABLES)
       && !ast_strlen_zero(opt_args[OPT_ARG_VARIABLES])) {
       char *vartext;
       char *text = opt_args[OPT_ARG_VARIABLES];
       while ((vartext = ast_strsep(&text, '^', 0))) {
          struct ast_variable *var;
          char *varname, *varvalue;
          if (!(varname = ast_strsep(&vartext, '=', 0))) {
             ast_log(LOG_ERROR, "Variable syntax error: %s\n", vartext);
             goto return_cleanup;
          }
          if (!(varvalue = ast_strsep(&vartext, '=', 0))) {
             varvalue = ""; /* empty values are allowed */
          }
          var = ast_variable_new(varname, varvalue, "");
          if (!var) {
             ast_log(LOG_ERROR, "Failed to allocate variable: %s\n", varname);
             goto return_cleanup;
          }
          ast_debug(1, "Appending variable '%s' with value '%s'", varname, varvalue);
          ast_variable_list_append(&vars, var);
       }
    }
    if (!strcasecmp(args.type, "exten")) {
       const char *cid_num = cnum;
       const char *cid_name = cname;
       int priority = 1; /* Initialized in case priority not specified */
       const char *exten = args.arg2;
       if (args.argc == 5) {
          /* Context/Exten/Priority all specified */
          if (sscanf(args.arg3, "%30d", &priority) != 1) {
             ast_log(LOG_ERROR, "Invalid priority: '%s'\n", args.arg3);
             goto return_cleanup;
          }
       } else if (args.argc == 3) {
          /* Exten not specified */
          exten = default_exten;
       }
       ast_debug(1, "Originating call to '%s/%s' and connecting them to extension %s,%s,%d\n",
             chantech, chandata, args.arg1, exten, priority);
       res = ast_pbx_outgoing_exten_predial(chantech, capabilities, chandata,
             timeout * 1000, args.arg1, exten, priority, &outgoing_status,
             ast_test_flag64(&opts, OPT_ASYNC) ? AST_OUTGOING_NO_WAIT : AST_OUTGOING_WAIT,
             cid_num, cid_name, vars, NULL, NULL, 0, NULL,
             predial_callee);
    } else {
       const char *cid_num = cnum;
       const char *cid_name = cname;
       ast_debug(1, "Originating call to '%s/%s' and connecting them to %s(%s)\n",
             chantech, chandata, args.arg1, S_OR(args.arg2, ""));
       res = ast_pbx_outgoing_app_predial(chantech, capabilities, chandata,
             timeout * 1000, args.arg1, args.arg2, &outgoing_status,
             ast_test_flag64(&opts, OPT_ASYNC) ? AST_OUTGOING_NO_WAIT : AST_OUTGOING_WAIT,
             cid_num, cid_name, vars, NULL, NULL, NULL,
             predial_callee);
    }
    /*
     * Getting here means that we have passed the various validation checks and
     * have at least attempted the dial. If we have a reason (outgoing_status),
     * we clear our error indicator so that we ultimately report the right thing
     * to the caller.
     */
    if (res && outgoing_status) {
       res = 0;
    }
    /* We need to exit cleanly if we've gotten this far */
    continue_in_dialplan = 1;
 return_cleanup:
    if (res) {
       pbx_builtin_setvar_helper(chan, "ORIGINATE_STATUS", "FAILED");
    } else {
       switch (outgoing_status) {
       case 0:
       case AST_CONTROL_ANSWER:
          pbx_builtin_setvar_helper(chan, "ORIGINATE_STATUS", "SUCCESS");
          break;
       case AST_CONTROL_BUSY:
          pbx_builtin_setvar_helper(chan, "ORIGINATE_STATUS", "BUSY");
          break;
       case AST_CONTROL_CONGESTION:
          pbx_builtin_setvar_helper(chan, "ORIGINATE_STATUS", "CONGESTION");
          break;
       case AST_CONTROL_HANGUP:
          pbx_builtin_setvar_helper(chan, "ORIGINATE_STATUS", "HANGUP");
          break;
       case AST_CONTROL_RINGING:
          pbx_builtin_setvar_helper(chan, "ORIGINATE_STATUS", "RINGING");
          break;
       default:
          ast_log(LOG_WARNING, "Unknown originate status result of '%d'\n",
                outgoing_status);
          pbx_builtin_setvar_helper(chan, "ORIGINATE_STATUS", "UNKNOWN");
          break;
       }
    }
    if (vars) {
       ast_variables_destroy(vars);
    }
    ao2_cleanup(capabilities);
    ast_autoservice_stop(chan);
    return continue_in_dialplan ? 0 : -1;
 }
unload_module()
static int unload_module (void) static
Definition at line 396 of file app_originate.c.
References app_originate, and ast_unregister_application().
 {
    return ast_unregister_application(app_originate);
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Originate call" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, } static
Definition at line 410 of file app_originate.c.
app_originate
const char app_originate[] = "Originate" static
Definition at line 45 of file app_originate.c.
Referenced by load_module(), and unload_module().
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 410 of file app_originate.c.
originate_exec_options
const struct ast_app_option originate_exec_options[128] = { [ 'a' ] = { .flag = OPT_ASYNC }, [ 'b' ] = { .flag = OPT_PREDIAL_CALLEE , .arg_index = OPT_ARG_PREDIAL_CALLEE + 1 }, [ 'B' ] = { .flag = OPT_PREDIAL_CALLER , .arg_index = OPT_ARG_PREDIAL_CALLER + 1 }, [ 'C' ] = { .flag = OPT_CODECS , .arg_index = OPT_ARG_CODECS + 1 }, [ 'c' ] = { .flag = OPT_CALLER_NUM , .arg_index = OPT_ARG_CALLER_NUM + 1 }, [ 'n' ] = { .flag = OPT_CALLER_NAME , .arg_index = OPT_ARG_CALLER_NAME + 1 }, [ 'v' ] = { .flag = OPT_VARIABLES , .arg_index = OPT_ARG_VARIABLES + 1 }, } static
Definition at line 171 of file app_originate.c.
Referenced by originate_exec().