Asterisk - The Open Source Telephony Project: res_audiosocket.c File Reference
res_audiosocket.c File Reference
AudioSocket support for Asterisk.
#include "asterisk.h"
#include "errno.h"
#include <uuid/uuid.h>
#include "asterisk/file.h"
#include "asterisk/res_audiosocket.h"
#include "asterisk/channel.h"
#include "asterisk/module.h"
#include "asterisk/uuid.h"
#include "asterisk/format_cache.h"
Macros
#define MAX_CONNECT_TIMEOUT_MSEC 2000
#define MODULE_DESCRIPTION "AudioSocket support functions for Asterisk"
Functions
static void __reg_module (void)
static void __unreg_module (void)
const int ast_audiosocket_connect (const char *server, struct ast_channel *chan)
Send the initial message to an AudioSocket server.
const int ast_audiosocket_init (const int svc, const char *id)
Send the initial message to an AudioSocket server.
struct ast_frame * ast_audiosocket_receive_frame (const int svc)
Receive an Asterisk frame from an AudioSocket server.
const int ast_audiosocket_send_frame (const int svc, const struct ast_frame *f)
Send an Asterisk audio frame to an AudioSocket server.
struct ast_module * AST_MODULE_SELF_SYM (void)
static int handle_audiosocket_connection (const char *server, const struct ast_sockaddr addr, const int netsockfd)
static int load_module (void)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_GLOBAL_SYMBOLS | AST_MODFLAG_LOAD_ORDER , .description = "AudioSocket support" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_EXTENDED, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_CHANNEL_DEPEND, }
static const struct ast_module_info * ast_module_info = &__mod_info
Detailed Description
AudioSocket support for Asterisk.
Author
Seán C McCord scm@c.nosp@m.ycor.nosp@m.esys..nosp@m.com
Definition in file res_audiosocket.c.
Macro Definition Documentation
MAX_CONNECT_TIMEOUT_MSEC
#define MAX_CONNECT_TIMEOUT_MSEC 2000
Definition at line 44 of file res_audiosocket.c.
Referenced by handle_audiosocket_connection().
MODULE_DESCRIPTION
#define MODULE_DESCRIPTION "AudioSocket support functions for Asterisk"
Definition at line 42 of file res_audiosocket.c.
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 344 of file res_audiosocket.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 344 of file res_audiosocket.c.
ast_audiosocket_connect()
const int ast_audiosocket_connect (const char * server, struct ast_channel * chan)
Send the initial message to an AudioSocket server.
Parameters
server The server address, including port.
chan An optional channel which will be put into autoservice during the connection period. If there is no channel to be autoserviced, pass NULL instead.
Return values
socket file descriptor for AudioSocket on success
-1 on error
Definition at line 99 of file res_audiosocket.c.
References AST_AF_UNSPEC, ast_autoservice_start(), ast_autoservice_stop(), ast_channel_name(), ast_connect(), ast_free, ast_log, ast_sockaddr_port, ast_sockaddr_resolve(), ast_sockaddr_stringify(), ast_socket_nonblock, ast_strlen_zero, end, errno, handle_audiosocket_connection(), LOG_ERROR, LOG_WARNING, NULL, PARSE_PORT_REQUIRE, and ast_sockaddr::ss.
Referenced by audiosocket_exec(), and audiosocket_request().
 {
    int s = -1;
    struct ast_sockaddr *addrs = NULL;
    int num_addrs = 0, i = 0;
    if (chan && ast_autoservice_start(chan) < 0) {
       ast_log(LOG_WARNING, "Failed to start autoservice for channel "
          "%s\n", ast_channel_name(chan));
       goto end;
    }
    if (ast_strlen_zero(server)) {
       ast_log(LOG_ERROR, "No AudioSocket server provided\n");
       goto end;
    }
    if (!(num_addrs = ast_sockaddr_resolve(&addrs, server, PARSE_PORT_REQUIRE,
       AST_AF_UNSPEC))) {
       ast_log(LOG_ERROR, "Failed to resolve AudioSocket service using %s - "
          "requires a valid hostname and port\n", server);
       goto end;
    }
    /* Connect to AudioSocket service */
    for (i = 0; i < num_addrs; i++) {
       if (!ast_sockaddr_port(&addrs[i])) {
          /* If there's no port, other addresses should have the
           * same problem. Stop here.
           */
          ast_log(LOG_ERROR, "No port provided for %s\n",
             ast_sockaddr_stringify(&addrs[i]));
          s = -1;
          goto end;
       }
       if ((s = ast_socket_nonblock(addrs[i].ss.ss_family, SOCK_STREAM,
          IPPROTO_TCP)) < 0) {
          ast_log(LOG_WARNING, "Unable to create socket: %s\n", strerror(errno));
          continue;
       }
       if (ast_connect(s, &addrs[i]) && errno == EINPROGRESS) {
          if (handle_audiosocket_connection(server, addrs[i], s)) {
             close(s);
             continue;
          }
       } else {
          ast_log(LOG_ERROR, "Connection to %s failed with unexpected error: %s\n",
             ast_sockaddr_stringify(&addrs[i]), strerror(errno));
          close(s);
          s = -1;
       }
       break;
    }
 end:
    if (addrs) {
       ast_free(addrs);
    }
    if (chan && ast_autoservice_stop(chan) < 0) {
       ast_log(LOG_WARNING, "Failed to stop autoservice for channel %s\n",
       ast_channel_name(chan));
       close(s);
       return -1;
    }
    if (i == num_addrs) {
       ast_log(LOG_ERROR, "Failed to connect to AudioSocket service\n");
       close(s);
       return -1;
    }
    return s;
 }
ast_audiosocket_init()
const int ast_audiosocket_init (const int svc, const char * id)
Send the initial message to an AudioSocket server.
Parameters
svc The file descriptor of the network socket to the AudioSocket server.
id The UUID to send to the AudioSocket server to uniquely identify this connection.
Return values
0 on success
-1 on error
Definition at line 180 of file res_audiosocket.c.
References ast_log, ast_strlen_zero, buf, LOG_ERROR, and LOG_WARNING.
Referenced by audiosocket_call(), and audiosocket_run().
 {
    uuid_t uu;
    int ret = 0;
    uint8_t buf[3 + 16];
    if (ast_strlen_zero(id)) {
       ast_log(LOG_ERROR, "No UUID for AudioSocket\n");
       return -1;
    }
    if (uuid_parse(id, uu)) {
       ast_log(LOG_ERROR, "Failed to parse UUID '%s'\n", id);
       return -1;
    }
    buf[0] = 0x01;
    buf[1] = 0x00;
    buf[2] = 0x10;
    memcpy(buf + 3, uu, 16);
    if (write(svc, buf, 3 + 16) != 3 + 16) {
       ast_log(LOG_WARNING, "Failed to write data to AudioSocket\n");
       ret = -1;
    }
    return ret;
 }
ast_audiosocket_receive_frame()
struct ast_frame* ast_audiosocket_receive_frame (const int svc)
Receive an Asterisk frame from an AudioSocket server.
This returned object is a pointer to an Asterisk frame which must be manually freed by the caller.
Parameters
svc The file descriptor of the network socket to the AudioSocket server.
Return values
A ast_frame on success
NULL on error
Definition at line 231 of file res_audiosocket.c.
References ast_format_slin, AST_FRAME_VOICE, ast_free, ast_frisolate, ast_log, ast_malloc, AST_MALLOCD_DATA, ast_null_frame, ast_frame::data, ast_frame::datalen, errno, ast_frame::frametype, len(), LOG_ERROR, LOG_WARNING, NULL, ast_frame::ptr, and ast_frame::samples.
Referenced by audiosocket_read(), and audiosocket_run().
 {
    int i = 0, n = 0, ret = 0, not_audio = 0;
    struct ast_frame f = {
       .frametype = AST_FRAME_VOICE,
       .subclass.format = ast_format_slin,
       .src = "AudioSocket",
       .mallocd = AST_MALLOCD_DATA,
    };
    uint8_t kind;
    uint8_t len_high;
    uint8_t len_low;
    uint16_t len = 0;
    uint8_t *data;
    n = read(svc, &kind, 1);
    if (n < 0 && errno == EAGAIN) {
       return &ast_null_frame;
    }
    if (n == 0) {
       return &ast_null_frame;
    }
    if (n != 1) {
       ast_log(LOG_WARNING, "Failed to read type header from AudioSocket\n");
       return NULL;
    }
    if (kind == 0x00) {
       /* AudioSocket ended by remote */
       return NULL;
    }
    if (kind != 0x10) {
       /* read but ignore non-audio message */
       ast_log(LOG_WARNING, "Received non-audio AudioSocket message\n");
       not_audio = 1;
    }
    n = read(svc, &len_high, 1);
    if (n != 1) {
       ast_log(LOG_WARNING, "Failed to read data length from AudioSocket\n");
       return NULL;
    }
    len += len_high * 256;
    n = read(svc, &len_low, 1);
    if (n != 1) {
       ast_log(LOG_WARNING, "Failed to read data length from AudioSocket\n");
       return NULL;
    }
    len += len_low;
    if (len < 1) {
       return &ast_null_frame;
    }
    data = ast_malloc(len);
    if (!data) {
       ast_log(LOG_ERROR, "Failed to allocate for data from AudioSocket\n");
       return NULL;
    }
    ret = 0;
    n = 0;
    i = 0;
    while (i < len) {
       n = read(svc, data + i, len - i);
       if (n < 0) {
          ast_log(LOG_ERROR, "Failed to read data from AudioSocket\n");
          ret = n;
          break;
       }
       if (n == 0) {
          ast_log(LOG_ERROR, "Insufficient data read from AudioSocket\n");
          ret = -1;
          break;
       }
       i += n;
    }
    if (ret != 0) {
       ast_free(data);
       return NULL;
    }
    if (not_audio) {
       ast_free(data);
       return &ast_null_frame;
    }
    f.data.ptr = data;
    f.datalen = len;
    f.samples = len / 2;
    /* The frame steals data, so it doesn't need to be freed here */
    return ast_frisolate(&f);
 }
ast_audiosocket_send_frame()
const int ast_audiosocket_send_frame (const int svc, const struct ast_frame * f)
Send an Asterisk audio frame to an AudioSocket server.
Parameters
svc The file descriptor of the network socket to the AudioSocket server.
f The Asterisk audio frame to send.
Return values
0 on success
-1 on error
Definition at line 209 of file res_audiosocket.c.
References ast_log, buf, ast_frame::data, ast_frame::datalen, LOG_WARNING, and ast_frame::ptr.
Referenced by audiosocket_run(), and audiosocket_write().
 {
    int ret = 0;
    uint8_t kind = 0x10; /* always 16-bit, 8kHz signed linear mono, for now */
    uint8_t *p;
    uint8_t buf[3 + f->datalen];
    p = buf;
    *(p++) = kind;
    *(p++) = f->datalen >> 8;
    *(p++) = f->datalen & 0xff;
    memcpy(p, f->data.ptr, f->datalen);
    if (write(svc, buf, 3 + f->datalen) != 3 + f->datalen) {
       ast_log(LOG_WARNING, "Failed to write data to AudioSocket\n");
       ret = -1;
    }
    return ret;
 }
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 344 of file res_audiosocket.c.
handle_audiosocket_connection()
static int handle_audiosocket_connection (const char * server, const struct ast_sockaddr addr, const int netsockfd) static
Definition at line 57 of file res_audiosocket.c.
References ast_log, ast_poll, ast_sockaddr_stringify(), errno, LOG_WARNING, and MAX_CONNECT_TIMEOUT_MSEC.
Referenced by ast_audiosocket_connect().
 {
    struct pollfd pfds[1];
    int res, conresult;
    socklen_t reslen;
    reslen = sizeof(conresult);
    pfds[0].fd = netsockfd;
    pfds[0].events = POLLOUT;
    while ((res = ast_poll(pfds, 1, MAX_CONNECT_TIMEOUT_MSEC)) != 1) {
       if (errno != EINTR) {
          if (!res) {
             ast_log(LOG_WARNING, "AudioSocket connection to '%s' timed"
                "out after MAX_CONNECT_TIMEOUT_MSEC (%d) milliseconds.\n",
                server, MAX_CONNECT_TIMEOUT_MSEC);
          } else {
             ast_log(LOG_WARNING, "Connect to '%s' failed: %s\n", server,
                strerror(errno));
          }
          return -1;
       }
    }
    if (getsockopt(pfds[0].fd, SOL_SOCKET, SO_ERROR, &conresult, &reslen) < 0) {
       ast_log(LOG_WARNING, "Connection to %s failed with error: %s\n",
          ast_sockaddr_stringify(&addr), strerror(errno));
       return -1;
    }
    if (conresult) {
       ast_log(LOG_WARNING, "Connecting to '%s' failed for url '%s': %s\n",
          ast_sockaddr_stringify(&addr), server, strerror(conresult));
       return -1;
    }
    return 0;
 }
load_module()
static int load_module (void) static
Definition at line 327 of file res_audiosocket.c.
References AST_MODULE_LOAD_SUCCESS, and ast_verb.
Referenced by unload_module().
 {
    ast_verb(1, "Loading AudioSocket Support module\n");
    return AST_MODULE_LOAD_SUCCESS;
 }
unload_module()
static int unload_module (void) static
Definition at line 333 of file res_audiosocket.c.
References AST_MODFLAG_GLOBAL_SYMBOLS, AST_MODFLAG_LOAD_ORDER, AST_MODPRI_CHANNEL_DEPEND, AST_MODULE_INFO(), AST_MODULE_LOAD_SUCCESS, AST_MODULE_SUPPORT_EXTENDED, ast_verb, ASTERISK_GPL_KEY, and load_module().
 {
    ast_verb(1, "Unloading AudioSocket Support module\n");
    return AST_MODULE_LOAD_SUCCESS;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_GLOBAL_SYMBOLS | AST_MODFLAG_LOAD_ORDER , .description = "AudioSocket support" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_EXTENDED, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_CHANNEL_DEPEND, } static
Definition at line 344 of file res_audiosocket.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 344 of file res_audiosocket.c.