Asterisk - The Open Source Telephony Project: spandspflow2pcap Namespace Reference
spandspflow2pcap Namespace Reference
Data Structures
class FaxPcap
class SkipPacket
class SpandspLog
Functions
def main (logname, pcapname)
def n2b (text)
Variables
bool EMPTY_RECOVERY = False
IFP = namedtuple('IFP', 'date seqno data')
bool LOSSY = False
Function Documentation
main()
def spandspflow2pcap.main (logname, pcapname)
Definition at line 239 of file spandspflow2pcap.py.
References format, and len().
 def main(logname, pcapname):
     with open(sys.argv[1], 'r') as infile:
         log = SpandspLog(infile)
         # with open(sys.argv[2], 'xb') as outfile:  # py3 exclusive write, bin
         create_or_fail = os.O_CREAT | os.O_EXCL | os.O_WRONLY
         try:
             fd = os.open(sys.argv[2], create_or_fail, 0o600)
         except Exception:
             raise
         else:
             with os.fdopen(fd, 'wb') as outfile:
                 pcap = FaxPcap(outfile)
                 for data in log:
                     pcap.add(data)
n2b()
def spandspflow2pcap.n2b (text)
Convert "aa bb cc" to bytearray('\xaa\xbb\xcc').
Definition at line 44 of file spandspflow2pcap.py.
References replace().
Referenced by SpandspLog.__iter__().
 def n2b(text):
     """
     Convert "aa bb cc" to bytearray('\xaa\xbb\xcc').
     """
     return bytearray(
         b16decode(text.replace(' ', '').replace('\n', '').upper()))
Variable Documentation
EMPTY_RECOVERY
bool EMPTY_RECOVERY = False
Definition at line 38 of file spandspflow2pcap.py.
IFP
IFP = namedtuple('IFP', 'date seqno data')
Definition at line 41 of file spandspflow2pcap.py.
Referenced by SpandspLog.__iter__(), and FaxPcap.add().
LOSSY
bool LOSSY = False
Definition at line 37 of file spandspflow2pcap.py.