Asterisk - The Open Source Telephony Project: bt_page.c File Reference
bt_page.c File Reference
#include <sys/types.h>
#include <stdio.h>
#include "../include/db.h"
#include "btree.h"
Functions
int __bt_free (BTREE *t, PAGE *h)
PAGE * __bt_new (BTREE *t, pgno_t *npg)
Function Documentation
__bt_free()
int __bt_free (BTREE * t, PAGE * h)
Definition at line 60 of file bt_page.c.
References B_METADIRTY, _btree::bt_free, _btree::bt_mp, F_SET, MPOOL_DIRTY, mpool_put(), _page::nextpg, P_INVALID, _page::pgno, and _page::prevpg.
Referenced by __bt_pdelete(), and __ovfl_delete().
 {
    /* Insert the page at the head of the free list. */
    h->prevpg = P_INVALID;
    h->nextpg = t->bt_free;
    t->bt_free = h->pgno;
    F_SET(t, B_METADIRTY);
    /* Make sure the page gets written back. */
    return (mpool_put(t->bt_mp, h, MPOOL_DIRTY));
 }
__bt_new()
PAGE* __bt_new (BTREE * t, pgno_t * npg)
Definition at line 86 of file bt_page.c.
References B_METADIRTY, _btree::bt_free, _btree::bt_mp, F_SET, mpool_get(), mpool_new(), _page::nextpg, NULL, and P_INVALID.
Referenced by __ovfl_put(), bt_page(), and bt_root().
 {
    PAGE *h;
    if (t->bt_free != P_INVALID &&
        (h = mpool_get(t->bt_mp, t->bt_free, 0)) != NULL) {
       *npg = t->bt_free;
       t->bt_free = h->nextpg;
       F_SET(t, B_METADIRTY);
       return (h);
    }
    return (mpool_new(t->bt_mp, npg));
 }