Asterisk - The Open Source Telephony Project: cli_functions.h File Reference
cli_functions.h File Reference
PJSIP CLI functions header file.
Functions
int pjsip_channel_cli_register (void)
Registers the channel cli commands.
void pjsip_channel_cli_unregister (void)
Unregisters the channel cli commands.
Detailed Description
PJSIP CLI functions header file.
Author
George Joseph <george.joseph@fairview5.com>
Definition in file cli_functions.h.
Function Documentation
pjsip_channel_cli_register()
int pjsip_channel_cli_register (void)
Registers the channel cli commands.
Since
13.9.0
Return values
0 on success
-1 on failure
Definition at line 448 of file cli_commands.c.
References ao2_alloc, ao2_ref, ARRAY_LEN, ast_cli_register_multiple, ast_log, ast_sip_register_cli_formatter(), cli_channel_get_container(), cli_channel_get_id(), cli_channel_iterate(), cli_channel_print_body(), cli_channel_print_header(), cli_channel_retrieve_by_id(), cli_channelstats_get_container(), cli_channelstats_iterate(), cli_channelstats_print_body(), cli_channelstats_print_header(), ast_sip_cli_formatter_entry::get_container, ast_sip_cli_formatter_entry::get_id, ast_sip_cli_formatter_entry::iterate, LOG_ERROR, ast_sip_cli_formatter_entry::name, NULL, ast_sip_cli_formatter_entry::print_body, ast_sip_cli_formatter_entry::print_header, and ast_sip_cli_formatter_entry::retrieve_by_id.
Referenced by load_module().
 {
    channel_formatter = ao2_alloc(sizeof(struct ast_sip_cli_formatter_entry), NULL);
    if (!channel_formatter) {
       ast_log(LOG_ERROR, "Unable to allocate memory for channel_formatter\n");
       return -1;
    }
    channel_formatter->name = "channel";
    channel_formatter->print_header = cli_channel_print_header;
    channel_formatter->print_body = cli_channel_print_body;
    channel_formatter->get_container = cli_channel_get_container;
    channel_formatter->iterate = cli_channel_iterate;
    channel_formatter->retrieve_by_id = cli_channel_retrieve_by_id;
    channel_formatter->get_id = cli_channel_get_id;
    channelstats_formatter = ao2_alloc(sizeof(struct ast_sip_cli_formatter_entry), NULL);
    if (!channelstats_formatter) {
       ao2_ref(channel_formatter, -1);
       ast_log(LOG_ERROR, "Unable to allocate memory for channelstats_formatter\n");
       return -1;
    }
    channelstats_formatter->name = "channelstat";
    channelstats_formatter->print_header = cli_channelstats_print_header;
    channelstats_formatter->print_body = cli_channelstats_print_body;
    channelstats_formatter->get_container = cli_channelstats_get_container;
    channelstats_formatter->iterate = cli_channelstats_iterate;
    channelstats_formatter->retrieve_by_id = cli_channel_retrieve_by_id;
    channelstats_formatter->get_id = cli_channel_get_id;
    ast_sip_register_cli_formatter(channel_formatter);
    ast_sip_register_cli_formatter(channelstats_formatter);
    ast_cli_register_multiple(cli_commands, ARRAY_LEN(cli_commands));
    return 0;
 }
pjsip_channel_cli_unregister()
void pjsip_channel_cli_unregister (void)
Unregisters the channel cli commands.
Since
13.9.0
Definition at line 484 of file cli_commands.c.
References ARRAY_LEN, ast_cli_unregister_multiple(), and ast_sip_unregister_cli_formatter().
Referenced by unload_module().
 {
    ast_cli_unregister_multiple(cli_commands, ARRAY_LEN(cli_commands));
    ast_sip_unregister_cli_formatter(channel_formatter);
    ast_sip_unregister_cli_formatter(channelstats_formatter);
 }