Asterisk - The Open Source Telephony Project: res_pjsip_rfc3326.c File Reference
res_pjsip_rfc3326.c File Reference
#include "asterisk.h"
#include <pjsip.h>
#include <pjsip_ua.h>
#include "asterisk/res_pjsip.h"
#include "asterisk/res_pjsip_session.h"
#include "asterisk/module.h"
#include "asterisk/causes.h"
#include "asterisk/threadpool.h"
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int load_module (void)
static void rfc3326_add_reason_header (struct ast_sip_session *session, struct pjsip_tx_data *tdata)
static int rfc3326_incoming_request (struct ast_sip_session *session, struct pjsip_rx_data *rdata)
static void rfc3326_incoming_response (struct ast_sip_session *session, struct pjsip_rx_data *rdata)
static void rfc3326_outgoing_request (struct ast_sip_session *session, struct pjsip_tx_data *tdata)
static void rfc3326_outgoing_response (struct ast_sip_session *session, struct pjsip_tx_data *tdata)
static void rfc3326_use_reason_header (struct ast_sip_session *session, struct pjsip_rx_data *rdata)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "PJSIP RFC3326 Support" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_APP_DEPEND, .requires = "res_pjsip,res_pjsip_session", }
static const struct ast_module_info * ast_module_info = &__mod_info
static struct ast_sip_session_supplement rfc3326_supplement
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 168 of file res_pjsip_rfc3326.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 168 of file res_pjsip_rfc3326.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 168 of file res_pjsip_rfc3326.c.
load_module()
static int load_module (void) static
Definition at line 150 of file res_pjsip_rfc3326.c.
References AST_MODULE_LOAD_SUCCESS, and ast_sip_session_register_supplement.
Referenced by unload_module().
 {
    ast_sip_session_register_supplement(&rfc3326_supplement);
    return AST_MODULE_LOAD_SUCCESS;
 }
rfc3326_add_reason_header()
static void rfc3326_add_reason_header (struct ast_sip_session * session, struct pjsip_tx_data * tdata) static
Definition at line 94 of file res_pjsip_rfc3326.c.
References ast_cause2str(), AST_CAUSE_ANSWERED_ELSEWHERE, ast_channel_hangupcause(), ast_debug, ast_sip_add_header(), ast_sorcery_object_get_id(), buf, ast_sip_session::channel, ast_sip_session::endpoint, and ast_sip_endpoint::suppress_q850_reason_headers.
Referenced by rfc3326_outgoing_request(), and rfc3326_outgoing_response().
 {
    char buf[20];
    if (ast_channel_hangupcause(session->channel) == AST_CAUSE_ANSWERED_ELSEWHERE) {
       ast_sip_add_header(tdata, "Reason", "SIP;cause=200;text=\"Call completed elsewhere\"");
    }
    if (session->endpoint && session->endpoint->suppress_q850_reason_headers) {
       ast_debug(1, "A Q.850 '%s'(%i) Reason header was suppresed for endpoint '%s'\n",
          ast_cause2str((ast_channel_hangupcause(session->channel) & 0x7f)),
          (ast_channel_hangupcause(session->channel) & 0x7f),
          ast_sorcery_object_get_id(session->endpoint));
    } else {
       snprintf(buf, sizeof(buf), "Q.850;cause=%i", ast_channel_hangupcause(session->channel) & 0x7f);
       ast_sip_add_header(tdata, "Reason", buf);
    }
 }
rfc3326_incoming_request()
static int rfc3326_incoming_request (struct ast_sip_session * session, struct pjsip_rx_data * rdata) static
Definition at line 70 of file res_pjsip_rfc3326.c.
References ast_sip_session::channel, and rfc3326_use_reason_header().
 {
    if ((pjsip_method_cmp(&rdata->msg_info.msg->line.req.method, &pjsip_bye_method) &&
         pjsip_method_cmp(&rdata->msg_info.msg->line.req.method, &pjsip_cancel_method)) ||
        !session->channel) {
       return 0;
    }
    rfc3326_use_reason_header(session, rdata);
    return 0;
 }
rfc3326_incoming_response()
static void rfc3326_incoming_response (struct ast_sip_session * session, struct pjsip_rx_data * rdata) static
Definition at line 83 of file res_pjsip_rfc3326.c.
References ast_sip_session::channel, and rfc3326_use_reason_header().
 {
    struct pjsip_status_line status = rdata->msg_info.msg->line.status;
    if ((status.code < 300) || !session->channel) {
       return;
    }
    rfc3326_use_reason_header(session, rdata);
 }
rfc3326_outgoing_request()
static void rfc3326_outgoing_request (struct ast_sip_session * session, struct pjsip_tx_data * tdata) static
Definition at line 113 of file res_pjsip_rfc3326.c.
References ast_threadpool_serializer_get_current(), ast_sip_session::channel, rfc3326_add_reason_header(), and ast_sip_session::serializer.
 {
    if ((pjsip_method_cmp(&tdata->msg->line.req.method, &pjsip_bye_method)
          && pjsip_method_cmp(&tdata->msg->line.req.method, &pjsip_cancel_method))
       || !session->channel
       /*
        * The session->channel has been seen to go away on us between
        * checks so we must also be running under the call's serializer
        * thread.
        */
       || session->serializer != ast_threadpool_serializer_get_current()) {
       return;
    }
    rfc3326_add_reason_header(session, tdata);
 }
rfc3326_outgoing_response()
static void rfc3326_outgoing_response (struct ast_sip_session * session, struct pjsip_tx_data * tdata) static
Definition at line 130 of file res_pjsip_rfc3326.c.
References ast_threadpool_serializer_get_current(), ast_sip_session::channel, rfc3326_add_reason_header(), and ast_sip_session::serializer.
 {
    struct pjsip_status_line status = tdata->msg->line.status;
    if (status.code < 300
       || !session->channel
       || session->serializer != ast_threadpool_serializer_get_current()) {
       return;
    }
    rfc3326_add_reason_header(session, tdata);
 }
rfc3326_use_reason_header()
static void rfc3326_use_reason_header (struct ast_sip_session * session, struct pjsip_rx_data * rdata) static
Definition at line 37 of file res_pjsip_rfc3326.c.
References ast_channel_hangupcause_set(), ast_copy_pj_str(), ast_skip_blanks(), buf, ast_sip_session::channel, NULL, and text.
Referenced by rfc3326_incoming_request(), and rfc3326_incoming_response().
 {
    static const pj_str_t str_reason = { "Reason", 6 };
    pjsip_generic_string_hdr *header;
    char buf[20];
    char *cause;
    char *text;
    int code;
    header = pjsip_msg_find_hdr_by_name(rdata->msg_info.msg, &str_reason, NULL);
    for (; header;
       header = pjsip_msg_find_hdr_by_name(rdata->msg_info.msg, &str_reason, header->next)) {
       ast_copy_pj_str(buf, &header->hvalue, sizeof(buf));
       cause = ast_skip_blanks(buf);
       if (strncasecmp(cause, "Q.850", 5) || !(cause = strstr(cause, "cause="))) {
          continue;
       }
       /* If text is present get rid of it */
       if ((text = strstr(cause, ";"))) {
          *text = '\0';
       }
       if (sscanf(cause, "cause=%30d", &code) != 1) {
          continue;
       }
       ast_channel_hangupcause_set(session->channel, code & 0x7f);
       break;
    }
 }
unload_module()
static int unload_module (void) static
Definition at line 156 of file res_pjsip_rfc3326.c.
References AST_MODFLAG_LOAD_ORDER, AST_MODPRI_APP_DEPEND, AST_MODULE_INFO(), AST_MODULE_SUPPORT_CORE, ast_sip_session_unregister_supplement(), ASTERISK_GPL_KEY, and load_module().
 {
    ast_sip_session_unregister_supplement(&rfc3326_supplement);
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "PJSIP RFC3326 Support" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_APP_DEPEND, .requires = "res_pjsip,res_pjsip_session", } static
Definition at line 168 of file res_pjsip_rfc3326.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 168 of file res_pjsip_rfc3326.c.
rfc3326_supplement
struct ast_sip_session_supplement rfc3326_supplement static
Definition at line 143 of file res_pjsip_rfc3326.c.