Asterisk - The Open Source Telephony Project: 3772f8f828da_update_identify_by Namespace Reference
3772f8f828da_update_identify_by Namespace Reference
Functions
def downgrade ()
def enum_update (table_name, column_name, enum_name, enum_values)
def upgrade ()
Variables
string down_revision = 'c7a44a5a0851'
string revision = '3772f8f828da'
Function Documentation
downgrade()
def 3772f8f828da_update_identify_by.downgrade ()
Definition at line 44 of file 3772f8f828da_update_identify_by.py.
References enum_update().
 def downgrade():
     enum_update('ps_endpoints', 'identify_by', 'pjsip_identify_by_values',
                 ['username'])
enum_update()
def 3772f8f828da_update_identify_by.enum_update (table_name, column_name, enum_name, enum_values)
Definition at line 17 of file 3772f8f828da_update_identify_by.py.
Referenced by downgrade(), and upgrade().
 def enum_update(table_name, column_name, enum_name, enum_values):
     if op.get_context().bind.dialect.name != 'postgresql':
         if op.get_context().bind.dialect.name == 'mssql':
             op.drop_constraint('ck_ps_endpoints_identify_by_pjsip_identify_by_values', 'ps_endpoints')
         op.alter_column(table_name, column_name,
                         type_=sa.Enum(*enum_values, name=enum_name))
         return
     # Postgres requires a few more steps
     tmp = enum_name + '_tmp'
     op.execute('ALTER TYPE ' + enum_name + ' RENAME TO ' + tmp)
     updated = sa.Enum(*enum_values, name=enum_name)
     updated.create(op.get_bind(), checkfirst=False)
     op.execute('ALTER TABLE ' + table_name + ' ALTER COLUMN ' + column_name +
                ' TYPE ' + enum_name + ' USING identify_by::text::' + enum_name)
     op.execute('DROP TYPE ' + tmp)
upgrade()
def 3772f8f828da_update_identify_by.upgrade ()
Definition at line 39 of file 3772f8f828da_update_identify_by.py.
References enum_update().
 def upgrade():
     enum_update('ps_endpoints', 'identify_by', 'pjsip_identify_by_values',
                 ['username', 'auth_username'])
Variable Documentation
down_revision
string down_revision = 'c7a44a5a0851'
Definition at line 11 of file 3772f8f828da_update_identify_by.py.
revision
string revision = '3772f8f828da'
Definition at line 10 of file 3772f8f828da_update_identify_by.py.