Asterisk - The Open Source Telephony Project: format_ilbc.c File Reference
format_ilbc.c File Reference
Module: Media File Formats
Save to raw, headerless iLBC data.
#include "asterisk.h"
#include "asterisk/mod_format.h"
#include "asterisk/module.h"
#include "asterisk/endian.h"
#include "asterisk/format_cache.h"
Macros
#define ILBC_BUF_SIZE 50 /* One Real iLBC Frame */
#define ILBC_SAMPLES 240
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static struct ast_frame * ilbc_read (struct ast_filestream *s, int *whennext)
static int ilbc_seek (struct ast_filestream *fs, off_t sample_offset, int whence)
static off_t ilbc_tell (struct ast_filestream *fs)
static int ilbc_trunc (struct ast_filestream *fs)
static int ilbc_write (struct ast_filestream *fs, struct ast_frame *f)
static int load_module (void)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Raw iLBC data" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_APP_DEPEND }
static const struct ast_module_info * ast_module_info = &__mod_info
static struct ast_format_def ilbc_f
Detailed Description
Save to raw, headerless iLBC data.
File name extension: ilbc
Definition in file format_ilbc.c.
Macro Definition Documentation
ILBC_BUF_SIZE
#define ILBC_BUF_SIZE 50 /* One Real iLBC Frame */
Definition at line 43 of file format_ilbc.c.
Referenced by ilbc_read(), ilbc_seek(), and ilbc_tell().
ILBC_SAMPLES
#define ILBC_SAMPLES 240
Definition at line 44 of file format_ilbc.c.
Referenced by ilbc_read(), ilbc_seek(), and ilbc_tell().
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 156 of file format_ilbc.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 156 of file format_ilbc.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 156 of file format_ilbc.c.
ilbc_read()
static struct ast_frame* ilbc_read (struct ast_filestream * s, int * whennext) static
Definition at line 46 of file format_ilbc.c.
References ast_format_get_name(), AST_FRAME_SET_BUFFER, AST_FRIENDLY_OFFSET, ast_log, ast_filestream::buf, ast_frame::data, ast_frame::datalen, errno, ast_filestream::f, ast_frame_subclass::format, ast_filestream::fr, ILBC_BUF_SIZE, ILBC_SAMPLES, LOG_WARNING, NULL, ast_frame::ptr, ast_frame::samples, and ast_frame::subclass.
 {
    size_t res;
    /* Send a frame from the file to the appropriate channel */
    AST_FRAME_SET_BUFFER(&s->fr, s->buf, AST_FRIENDLY_OFFSET, ILBC_BUF_SIZE);
    if ((res = fread(s->fr.data.ptr, 1, s->fr.datalen, s->f)) != s->fr.datalen) {
       if (res) {
          ast_log(LOG_WARNING, "Short read of %s data (expected %d bytes, read %zu): %s\n",
                ast_format_get_name(s->fr.subclass.format), s->fr.datalen, res,
                strerror(errno));
       }
       return NULL;
    }
    *whennext = s->fr.samples = ILBC_SAMPLES;
    return &s->fr;
 }
ilbc_seek()
static int ilbc_seek (struct ast_filestream * fs, off_t sample_offset, int whence) static
Definition at line 78 of file format_ilbc.c.
References ast_filestream::f, ILBC_BUF_SIZE, ILBC_SAMPLES, max, min, ast_frame::offset, and SEEK_FORCECUR.
 {
    long bytes;
    off_t min,cur,max,offset=0;
    min = 0;
    cur = ftello(fs->f);
    fseeko(fs->f, 0, SEEK_END);
    max = ftello(fs->f);
    bytes = ILBC_BUF_SIZE * (sample_offset / ILBC_SAMPLES);
    if (whence == SEEK_SET)
       offset = bytes;
    else if (whence == SEEK_CUR || whence == SEEK_FORCECUR)
       offset = cur + bytes;
    else if (whence == SEEK_END)
       offset = max - bytes;
    if (whence != SEEK_FORCECUR) {
       offset = (offset > max)?max:offset;
    }
    /* protect against seeking beyond begining. */
    offset = (offset < min)?min:offset;
    if (fseeko(fs->f, offset, SEEK_SET) < 0)
       return -1;
    return 0;
 }
ilbc_tell()
static off_t ilbc_tell (struct ast_filestream * fs) static
Definition at line 121 of file format_ilbc.c.
References ast_filestream::f, ILBC_BUF_SIZE, ILBC_SAMPLES, and ast_frame::offset.
 {
    off_t offset = ftello(fs->f);
    return (offset/ILBC_BUF_SIZE)*ILBC_SAMPLES;
 }
ilbc_trunc()
static int ilbc_trunc (struct ast_filestream * fs) static
Definition at line 104 of file format_ilbc.c.
References ast_log, AST_LOG_WARNING, errno, and ast_filestream::f.
 {
    int fd;
    off_t cur;
    if ((fd = fileno(fs->f)) < 0) {
       ast_log(AST_LOG_WARNING, "Unable to determine file descriptor for iLBC filestream %p: %s\n", fs, strerror(errno));
       return -1;
    }
    if ((cur = ftello(fs->f)) < 0) {
       ast_log(AST_LOG_WARNING, "Unable to determine current position in iLBC filestream %p: %s\n", fs, strerror(errno));
       return -1;
    }
    /* Truncate file to current length */
    return ftruncate(fd, cur);
 }
ilbc_write()
static int ilbc_write (struct ast_filestream * fs, struct ast_frame * f) static
Definition at line 64 of file format_ilbc.c.
References ast_log, ast_frame::data, ast_frame::datalen, errno, ast_filestream::f, LOG_WARNING, and ast_frame::ptr.
 {
    int res;
    if (f->datalen % 50) {
       ast_log(LOG_WARNING, "Invalid data length, %d, should be multiple of 50\n", f->datalen);
       return -1;
    }
    if ((res = fwrite(f->data.ptr, 1, f->datalen, fs->f)) != f->datalen) {
          ast_log(LOG_WARNING, "Bad write (%d/50): %s\n", res, strerror(errno));
          return -1;
    }
    return 0;
 }
load_module()
static int load_module (void) static
Definition at line 138 of file format_ilbc.c.
References ast_format_def_register, ast_format_ilbc, AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, and ast_format_def::format.
Referenced by unload_module().
 {
    ilbc_f.format = ast_format_ilbc;
    if (ast_format_def_register(&ilbc_f))
       return AST_MODULE_LOAD_DECLINE;
    return AST_MODULE_LOAD_SUCCESS;
 }
unload_module()
static int unload_module (void) static
Definition at line 146 of file format_ilbc.c.
References ast_format_def_unregister(), AST_MODFLAG_LOAD_ORDER, AST_MODPRI_APP_DEPEND, AST_MODULE_INFO(), AST_MODULE_SUPPORT_CORE, ASTERISK_GPL_KEY, load_module(), and ast_format_def::name.
 {
    return ast_format_def_unregister(ilbc_f.name);
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Raw iLBC data" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_APP_DEPEND } static
Definition at line 156 of file format_ilbc.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 156 of file format_ilbc.c.
ilbc_f
struct ast_format_def ilbc_f static
Definition at line 127 of file format_ilbc.c.