Asterisk - The Open Source Telephony Project: alaw.c File Reference
alaw.c File Reference
a-Law to Signed linear conversion
#include "asterisk.h"
#include "asterisk/alaw.h"
#include "asterisk/logger.h"
Macros
#define AMI_MASK 0x55
Functions
static short int alaw2linear (unsigned char alaw)
void ast_alaw_init (void)
To init the alaw to slinear conversion stuff, this needs to be run.
static unsigned char linear2alaw (short int linear)
Variables
short __ast_alaw [256]
unsigned char __ast_lin2a [8192]
converts signed linear to alaw
Detailed Description
a-Law to Signed linear conversion
Author
Mark Spencer marks.nosp@m.ter@.nosp@m.digiu.nosp@m.m.co.nosp@m.m
Definition in file alaw.c.
Macro Definition Documentation
AMI_MASK
#define AMI_MASK 0x55
Definition at line 36 of file alaw.c.
Referenced by alaw2linear(), and linear2alaw().
Function Documentation
alaw2linear()
static short int alaw2linear (unsigned char alaw) inline static
Definition at line 112 of file alaw.c.
References AMI_MASK, and AST_ALAW_AMI_MASK.
Referenced by ast_alaw_init().
 {
    int i;
    int seg;
    alaw ^= AMI_MASK;
    i = ((alaw & 0x0F) << 4) + 8 /* rounding error */;
    seg = (((int) alaw & 0x70) >> 4);
    if (seg) {
       i = (i + 0x100) << (seg - 1);
    }
    return (short int) ((alaw & 0x80) ? i : -i);
 }
ast_alaw_init()
void ast_alaw_init (void)
To init the alaw to slinear conversion stuff, this needs to be run.
Definition at line 152 of file alaw.c.
References __ast_alaw, __ast_lin2a, alaw2linear(), AST_ALAW, AST_ALAW_STEP, AST_LIN2A, ast_log, linear2alaw(), LOG_NOTICE, and LOG_WARNING.
Referenced by asterisk_daemon().
 {
    int i;
    /*
     *  Set up mu-law conversion table
     */
 #ifndef G711_NEW_ALGORITHM
    for (i = 0; i < 256; i++) {
       __ast_alaw[i] = alaw2linear(i);
    }
    /* set up the reverse (mu-law) conversion table */
    for (i = -32768; i < 32768; i++) {
       __ast_lin2a[((unsigned short)i) >> 3] = linear2alaw(i);
    }
 #else
    for (i = 0; i < 256; i++) {
       __ast_alaw[i] = alaw2linear(i);
    }
    /* set up the reverse (a-law) conversion table */
    for (i = 0; i <= 32768; i += AST_ALAW_STEP) {
       AST_LIN2A_LOOKUP(i) = linear2alaw(i, 0 /* half-cooked */);
    }
 #endif
 #ifdef TEST_CODING_TABLES
    for (i = -32768; i < 32768; ++i) {
 #ifndef G711_NEW_ALGORITHM
       unsigned char e1 = linear2alaw(i);
 #else
       unsigned char e1 = linear2alaw(i, 1);
 #endif
       short d1 = alaw2linear(e1);
       unsigned char e2 = AST_LIN2A(i);
       short d2 = alaw2linear(e2);
       short d3 = AST_ALAW(e1);
       if (e1 != e2 || d1 != d3 || d2 != d3) {
          ast_log(LOG_WARNING, "a-Law coding tables test failed on %d: e1=%u, e2=%u, d1=%d, d2=%d\n",
                i, (unsigned)e1, (unsigned)e2, (int)d1, (int)d2);
       }
    }
    ast_log(LOG_NOTICE, "a-Law coding tables test complete.\n");
 #endif /* TEST_CODING_TABLES */
 #ifdef TEST_TANDEM_TRANSCODING
    /* tandem transcoding test */
    for (i = -32768; i < 32768; ++i) {
       unsigned char e1 = AST_LIN2A(i);
       short d1 = AST_ALAW(e1);
       unsigned char e2 = AST_LIN2A(d1);
       short d2 = AST_ALAW(e2);
       unsigned char e3 = AST_LIN2A(d2);
       short d3 = AST_ALAW(e3);
       if (e1 != e2 || e2 != e3 || d1 != d2 || d2 != d3) {
          ast_log(LOG_WARNING, "a-Law tandem transcoding test failed on %d: e1=%u, e2=%u, d1=%d, d2=%d, d3=%d\n",
                i, (unsigned)e1, (unsigned)e2, (int)d1, (int)d2, (int)d3);
       }
    }
    ast_log(LOG_NOTICE, "a-Law tandem transcoding test complete.\n");
 #endif /* TEST_TANDEM_TRANSCODING */
 }
linear2alaw()
static unsigned char linear2alaw (short int linear) inline static
Definition at line 38 of file alaw.c.
References AMI_MASK, and AST_ALAW_AMI_MASK.
Referenced by ast_alaw_init().
 {
    int mask;
    int seg;
    int pcm_val;
    static int seg_end[8] =
       {
          0xFF, 0x1FF, 0x3FF, 0x7FF, 0xFFF, 0x1FFF, 0x3FFF, 0x7FFF
       };
    pcm_val = linear;
    if (pcm_val >= 0) {
       /* Sign (7th) bit = 1 */
       mask = AMI_MASK | 0x80;
    } else {
       /* Sign bit = 0 */
       mask = AMI_MASK;
       pcm_val = -pcm_val;
    }
    /* Convert the scaled magnitude to segment number. */
    for (seg = 0; seg < 8; seg++) {
       if (pcm_val <= seg_end[seg]) {
          break;
       }
    }
    /* Combine the sign, segment, and quantization bits. */
    return ((seg << 4) | ((pcm_val >> ((seg) ? (seg + 3) : 4)) & 0x0F)) ^ mask;
 }
Variable Documentation
__ast_alaw
short __ast_alaw[256]
help
Definition at line 150 of file alaw.c.
Referenced by ast_alaw_init().
__ast_lin2a
unsigned char __ast_lin2a[8192]
converts signed linear to alaw
Definition at line 146 of file alaw.c.
Referenced by ast_alaw_init().