Asterisk - The Open Source Telephony Project: conf2ael.c File Reference
conf2ael.c File Reference
#include "asterisk.h"
#include "asterisk/paths.h"
#include <locale.h>
#include <ctype.h>
#include <err.h>
#include <regex.h>
#include "asterisk/pbx.h"
#include "asterisk/ast_expr.h"
#include "asterisk/channel.h"
#include "asterisk/chanvars.h"
#include "asterisk/module.h"
#include "asterisk/app.h"
#include "asterisk/config.h"
#include "asterisk/options.h"
#include "asterisk/callerid.h"
#include "asterisk/lock.h"
#include "asterisk/hashtab.h"
#include "asterisk/ael_structs.h"
#include "asterisk/devicestate.h"
#include "asterisk/stringfields.h"
#include "asterisk/pval.h"
#include "asterisk/extconf.h"
Data Structures
struct ast_app
ast_app: A registered application
struct ast_context
ast_context: An extension context - must remain in sync with fake_context
struct ast_exten
ast_exten: An extension The dialplan is saved as a linked list with each context having it's own linked list of extensions - one item per priority.
struct ast_hint
Structure for dial plan hints.
struct ast_ignorepat
ast_ignorepat: Ignore patterns in dial plan
struct ast_include
ast_include: include= support in extensions.conf
struct ast_state_cb
ast_state_cb: An extension state notify register item
struct ast_sw
ast_sw: Switch statement in extensions.conf
struct profile_data
struct profile_entry
struct store_hint
struct store_hints
Macros
#define ASTMM_LIBC ASTMM_IGNORE
#define BACKGROUND_MATCHEXTEN (1 << 2)
#define BACKGROUND_NOANSWER (1 << 1)
#define BACKGROUND_PLAYBACK (1 << 3)
#define BACKGROUND_SKIP (1 << 0)
#define EXT_DATA_SIZE 8192
#define STATUS_NO_CONTEXT 1
#define STATUS_NO_EXTENSION 2
#define STATUS_NO_LABEL 4
#define STATUS_NO_PRIORITY 3
#define STATUS_SUCCESS 5
#define SWITCH_DATA_LENGTH 256
#define VAR_BUF_SIZE 4096
#define VAR_HARDTRAN 3
#define VAR_NORMAL 1
#define VAR_SOFTTRAN 2
Functions
int __ast_bt_get_addresses (struct ast_bt *bt)
struct ast_vector_string * __ast_bt_get_symbols (void **addresses, size_t num_frames)
void __ast_cli_register_multiple (void)
int all_bits_set (unsigned int *word, int bitsperword, int totalbits)
int ast_add_extension2 (struct ast_context *con, int replace, const char *extension, int priority, const char *label, const char *callerid, const char *application, void *data, void(*datad)(void *), const char *registrar, const char *registrar_file, int registrar_line)
Add an extension to an extension context, this time with an ast_context *.
int ast_add_profile (const char *x, uint64_t scale)
support for event profiling
void ast_cli_unregister_multiple (void)
int ast_context_add_ignorepat2 (struct ast_context *con, const char *value, const char *registrar)
int ast_context_add_include2 (struct ast_context *con, const char *value, const char *registrar)
Add a context include.
int ast_context_add_switch2 (struct ast_context *con, const char *value, const char *data, int eval, const char *registrar)
Adds a switch (first param is a ast_context)
void ast_context_destroy (struct ast_context *con, const char *registrar)
Destroy a context (matches the specified context or ANY context if NULL)
struct ast_context * ast_context_find_or_create (struct ast_context **extcontexts, struct ast_hashtab *exttable, const char *name, const char *registrar)
Register a new context or find an existing one.
int ast_context_verify_includes (struct ast_context *con)
Verifies includes in an ast_contect structure.
struct ast_custom_function * ast_custom_function_find (const char *name)
const char * ast_get_context_name (struct ast_context *con)
int ast_hashtab_compare_contexts (const void *ah_a, const void *ah_b)
hashtable functions for contexts
unsigned int ast_hashtab_hash_contexts (const void *obj)
void ast_log (int level, const char *file, int line, const char *function, const char *fmt,...)
Used for sending a log message This is the standard logger function. Probably the only way you will invoke it would be something like this: ast_log(AST_LOG_WHATEVER, "Problem with the %s Captain. We should get some more. Will %d be enough?\n", "flux capacitor", 10); where WHATEVER is one of ERROR, DEBUG, EVENT, NOTICE, or WARNING depending on which log you wish to output to. These are implemented as macros, that will provide the function with the needed arguments.
void ast_mark_lock_acquired (void *lock_addr)
Mark the last lock as acquired.
void ast_merge_contexts_and_delete (struct ast_context **extcontexts, struct ast_hashtab *exttable, const char *registrar)
Merge the temporary contexts into a global contexts list and delete from the global list the ones that are being added.
void ast_module_register (const struct ast_module_info *x)
void ast_module_unregister (const struct ast_module_info *x)
void ast_remove_lock_info (void *lock_addr, struct ast_bt *bt)
remove lock info for the current thread
void ast_restore_lock_info (void *lock_addr)
void ast_store_lock_info (enum ast_lock_type type, const char *filename, int line_num, const char *func, const char *lock_name, void *lock_addr, struct ast_bt *bt)
Store lock info for the current thread.
void ast_suspend_lock_info (void *lock_addr)
struct ast_exten * ast_walk_context_extensions (struct ast_context *con, struct ast_exten *exten)
const struct ast_include * ast_walk_context_includes (const struct ast_context *con, const struct ast_include *inc)
struct ast_context * ast_walk_contexts (struct ast_context *con)
static int bit_at (unsigned int *word, int bitsperword, int bitnum)
void get_start_stop (unsigned int *word, int bitsperword, int totalbits, int *start, int *end)
int main (int argc, char **argv)
int pbx_builtin_setvar (struct ast_channel *chan, const char *data)
Parse and set a single channel variable, where the name and value are separated with an '=' character.
struct ast_exten * pbx_find_extension (struct ast_channel *chan, struct ast_context *bypass, struct pbx_find_info *q, const char *context, const char *exten, int priority, const char *label, const char *callerid, enum ext_match_t action)
void pbx_substitute_variables_helper (struct ast_channel *c, const char *cp1, char *cp2, int count)
Variables
const char * ast_config_AST_CONFIG_DIR = "/etc/asterisk"
char * config = "extensions.conf"
struct ast_context * contexts
char * days []
struct ast_context * local_contexts
char * months []
int option_debug = 0
int option_verbose = 0
Macro Definition Documentation
ASTMM_LIBC
#define ASTMM_LIBC ASTMM_IGNORE
Definition at line 30 of file conf2ael.c.
BACKGROUND_MATCHEXTEN
#define BACKGROUND_MATCHEXTEN (1 << 2)
Definition at line 117 of file conf2ael.c.
BACKGROUND_NOANSWER
#define BACKGROUND_NOANSWER (1 << 1)
Definition at line 116 of file conf2ael.c.
BACKGROUND_PLAYBACK
#define BACKGROUND_PLAYBACK (1 << 3)
Definition at line 118 of file conf2ael.c.
BACKGROUND_SKIP
#define BACKGROUND_SKIP (1 << 0)
Definition at line 115 of file conf2ael.c.
EXT_DATA_SIZE
#define EXT_DATA_SIZE 8192
Definition at line 104 of file conf2ael.c.
STATUS_NO_CONTEXT
#define STATUS_NO_CONTEXT 1
Definition at line 229 of file conf2ael.c.
STATUS_NO_EXTENSION
#define STATUS_NO_EXTENSION 2
Definition at line 230 of file conf2ael.c.
STATUS_NO_LABEL
#define STATUS_NO_LABEL 4
Definition at line 232 of file conf2ael.c.
STATUS_NO_PRIORITY
#define STATUS_NO_PRIORITY 3
Definition at line 231 of file conf2ael.c.
STATUS_SUCCESS
#define STATUS_SUCCESS 5
Definition at line 233 of file conf2ael.c.
SWITCH_DATA_LENGTH
#define SWITCH_DATA_LENGTH 256
Definition at line 107 of file conf2ael.c.
VAR_BUF_SIZE
#define VAR_BUF_SIZE 4096
Definition at line 109 of file conf2ael.c.
VAR_HARDTRAN
#define VAR_HARDTRAN 3
Definition at line 113 of file conf2ael.c.
VAR_NORMAL
#define VAR_NORMAL 1
Definition at line 111 of file conf2ael.c.
VAR_SOFTTRAN
#define VAR_SOFTTRAN 2
Definition at line 112 of file conf2ael.c.
Function Documentation
__ast_bt_get_addresses()
int __ast_bt_get_addresses (struct ast_bt * bt)
Definition at line 713 of file conf2ael.c.
 {
    return 0;
 }
__ast_bt_get_symbols()
struct ast_vector_string* __ast_bt_get_symbols (void ** addresses, size_t num_frames)
Definition at line 718 of file conf2ael.c.
References NULL.
 {
    return NULL;
 }
__ast_cli_register_multiple()
void __ast_cli_register_multiple (void)
Definition at line 599 of file conf2ael.c.
Referenced by ast_context_find_or_create().
 {
 }
all_bits_set()
int all_bits_set (unsigned int * word, int bitsperword, int totalbits)
Definition at line 286 of file conf2ael.c.
References total.
Referenced by main().
 {
    int i, total=totalbits/bitsperword,bitmask = 0;
    for (i=0; i<bitsperword; i++)
    {
       bitmask |= (1 << i);
    }
    for (i=0; i<total; i++)
    {
       if (word[i] != bitmask)
          return 0;
    }
    return 1;
 }
ast_add_extension2()
int ast_add_extension2 (struct ast_context * con, int replace, const char * extension, int priority, const char * label, const char * callerid, const char * application, void * data, void(*)(void *) datad, const char * registrar, const char * registrar_file, int registrar_line)
Add an extension to an extension context, this time with an ast_context *.
Parameters
registrar_file optional configuration file that defines this extension
registrar_line optional line number of configuration file that defines extension
Note
For details about the other arguments, check ast_add_extension()
Add an extension to an extension context, this time with an ast_context *.
We sort extensions in order of matching preference, so that we can stop the search as soon as we find a suitable match. This ordering also takes care of wildcards such as '.' (meaning "one or more of any character") and '!' (which is 'earlymatch', meaning "zero or more of any character" but also impacts the return value from CANMATCH and EARLYMATCH.
The extension match rules defined in the devmeeting 2006.05.05 are quite simple: WE SELECT THE LONGEST MATCH. In detail, "longest" means the number of matched characters in the extension. In case of ties (e.g. _XXX and 333) in the length of a pattern, we give priority to entries with the smallest cardinality (e.g, [5-9] comes before [2-8] before the former has only 5 elements, while the latter has 7, etc. In case of same cardinality, the first element in the range counts. If we still have a tie, any final '!' will make this as a possibly less specific pattern.
EBUSY - can't lock EEXIST - extension with the same priority exist and no replace is set
Definition at line 562 of file conf2ael.c.
References ast_exten::datad, and localized_add_extension2().
Referenced by add_extensions(), lua_register_hints(), manager_dialplan_extension_add(), pbx_load_config(), and pbx_load_users().
 {
    return localized_add_extension2(con, replace, extension, priority, label, callerid, application, data, datad, registrar);
 }
ast_add_profile()
int ast_add_profile (const char * x, uint64_t scale)
support for event profiling
(note, this must be documented a lot more) ast_add_profile allocates a generic 'counter' with a given name, which can be shown with the command 'core show profile <name>'
The counter accumulates positive or negative values supplied by
See also
ast_add_profile(), dividing them by the 'scale' value passed in the create call, and also counts the number of 'events'. Values can also be taked by the TSC counter on ia32 architectures, in which case you can mark the start of an event calling ast_mark(id, 1) and then the end of the event with ast_mark(id, 0). For non-i386 architectures, these two calls return 0.
support for event profiling
Returns
Returns the identifier of the counter.
Definition at line 82 of file conf2ael.c.
References ast_log(), make_ari_stubs::file, and format.
Referenced by ao2_weakproxy_unsubscribe(), and extension_match_core().
 { return 0;}
ast_cli_unregister_multiple()
void ast_cli_unregister_multiple (void)
Definition at line 613 of file conf2ael.c.
References ast_walk_contexts().
Referenced by ast_module_unregister().
 {
 }
ast_context_add_ignorepat2()
int ast_context_add_ignorepat2 (struct ast_context * con, const char * value, const char * registrar)
Definition at line 570 of file conf2ael.c.
References localized_context_add_ignorepat2().
Referenced by ast_compile_ael2(), and pbx_load_config().
 {
    return localized_context_add_ignorepat2(con, value, registrar);
 }
ast_context_add_include2()
int ast_context_add_include2 (struct ast_context * con, const char * value, const char * registrar)
Add a context include.
Parameters
con context to add the include to
value include value to add
registrar who registered the context
Adds an include taking a struct ast_context as the first parameter
Return values
0 on success
-1 on failure
Definition at line 583 of file conf2ael.c.
References localized_context_add_include2().
Referenced by ast_compile_ael2(), and pbx_load_config().
 {
    return localized_context_add_include2(con, value,registrar);
 }
ast_context_add_switch2()
int ast_context_add_switch2 (struct ast_context * con, const char * value, const char * data, int eval, const char * registrar)
Adds a switch (first param is a ast_context)
Note
See ast_context_add_switch() for argument information, with the exception of the first argument. In this case, it's a pointer to an ast_context structure as opposed to the name.
Definition at line 576 of file conf2ael.c.
References localized_context_add_switch2().
Referenced by ast_compile_ael2(), lua_register_switches(), and pbx_load_config().
 {
    return localized_context_add_switch2(con, value, data, eval, registrar);
 }
ast_context_destroy()
void ast_context_destroy (struct ast_context * con, const char * registrar)
Destroy a context (matches the specified context or ANY context if NULL)
Parameters
con context to destroy
registrar who registered it
You can optionally leave out either parameter. It will find it based on either the ast_context or the registrar name.
Returns
nothing
Definition at line 625 of file conf2ael.c.
References ast_context_verify_includes(), and localized_context_destroy().
Referenced by AST_TEST_DEFINE(), ast_walk_contexts(), parking_lot_cfg_remove_extensions(), remove_all_configured_parking_lot_extensions(), remove_pending_parking_lot_extensions(), sla_destroy(), and unload_module().
 {
    return localized_context_destroy(con, registrar);
 }
ast_context_find_or_create()
struct ast_context* ast_context_find_or_create (struct ast_context ** extcontexts, struct ast_hashtab * exttable, const char * name, const char * registrar)
Register a new context or find an existing one.
Parameters
extcontexts pointer to the ast_context structure pointer
exttable pointer to the hashtable that contains all the elements in extcontexts
name name of the new context
registrar registrar of the context
This function allows you to play in two environments: the global contexts (active dialplan) or an external context set of your choosing. To act on the external set, make sure extcontexts and exttable are set; for the globals, make sure both extcontexts and exttable are NULL.
This will first search for a context with your name. If it exists already, it will not create a new one. If it does not exist, it will create a new one with the given name and registrar.
Returns
NULL on failure, and an ast_context structure on success
Definition at line 590 of file conf2ael.c.
References __ast_cli_register_multiple(), and localized_context_find_or_create().
Referenced by add_hints(), app_create(), ast_compile_ael2(), ast_sip_persistent_endpoint_add_to_regcontext(), AST_TEST_DEFINE(), config_parse_variables(), create_test_dialplan(), handle_cli_dialplan_add_extension(), handle_cli_dialplan_add_include(), load_module(), lua_register_hints(), lua_register_switches(), manager_dialplan_extension_add(), parking_duration_callback(), parking_lot_cfg_create_extensions(), pbx_load_config(), pbx_load_users(), reload_config(), set_config(), sla_build_station(), and sla_build_trunk().
 {
    printf("find/Creating context %s, registrar=%s\n", name, registrar);
    return localized_context_find_or_create(extcontexts, exttable, name, registrar);
 }
ast_context_verify_includes()
int ast_context_verify_includes (struct ast_context * con)
Verifies includes in an ast_contect structure.
Parameters
con context in which to verify the includes
Return values
0 if no problems found
-1 if there were any missing context
Definition at line 632 of file conf2ael.c.
References ast_merge_contexts_and_delete(), and localized_context_verify_includes().
Referenced by ast_context_destroy(), and pbx_load_module().
 {
    return  localized_context_verify_includes(con);
 }
ast_custom_function_find()
struct ast_custom_function* ast_custom_function_find (const char * name)
Definition at line 242 of file conf2ael.c.
References events, ast_exten::name, and value.
Referenced by ast_compile_ael2(), AST_TEST_DEFINE(), chanavail_exec(), config_curl(), destroy_curl(), op_func(), realtime_curl(), realtime_multi_curl(), require_curl(), store_curl(), update2_curl(), and update_curl().
 {
    return 0; /* in "standalone" mode, functions are just not avail */
 }
ast_get_context_name()
const char* ast_get_context_name (struct ast_context * con)
Definition at line 645 of file conf2ael.c.
References ast_walk_context_extensions(), ast_exten::exten, ast_context::name, and NULL.
Referenced by _macro_exec(), add_extension(), ast_compile_ael2(), ast_merge_contexts_and_delete(), complete_dialplan_add_extension(), complete_dialplan_add_ignorepat(), complete_dialplan_add_include(), complete_dialplan_remove_context(), complete_dialplan_remove_extension(), complete_dialplan_remove_ignorepat(), complete_dialplan_remove_include(), dundi_precache_full(), extension_is_compatible(), find_matching_endif(), find_matching_endwhile(), find_matching_priority(), and handle_cli_dialplan_save().
 {
    return con ? con->name : NULL;
 }
ast_hashtab_compare_contexts()
int ast_hashtab_compare_contexts (const void * ah_a, const void * ah_b)
hashtable functions for contexts
Definition at line 687 of file conf2ael.c.
References ast_hashtab_hash_contexts().
Referenced by lua_register_hints(), lua_register_switches(), pbx_find_extension(), and pbx_load_module().
 {
    return 0;
 }
ast_hashtab_hash_contexts()
unsigned int ast_hashtab_hash_contexts (const void * obj)
Definition at line 694 of file conf2ael.c.
Referenced by ast_hashtab_compare_contexts(), lua_register_hints(), lua_register_switches(), and pbx_load_module().
 {
    return 0;
 }
ast_log()
void ast_log (int level, const char * file, int line, const char * function, const char * fmt, ...)
Used for sending a log message This is the standard logger function. Probably the only way you will invoke it would be something like this: ast_log(AST_LOG_WHATEVER, "Problem with the %s Captain. We should get some more. Will %d be enough?\n", "flux capacitor", 10); where WHATEVER is one of ERROR, DEBUG, EVENT, NOTICE, or WARNING depending on which log you wish to output to. These are implemented as macros, that will provide the function with the needed arguments.
Parameters
level Type of log event
file Will be provided by the AST_LOG_* macro
line Will be provided by the AST_LOG_* macro
function Will be provided by the AST_LOG_* macro
fmt This is what is important. The format is the same as your favorite breed of printf. You know how that works, right? :-)
Definition at line 86 of file conf2ael.c.
Referenced by ast_add_profile(), and main().
 {
    va_list vars;
    va_start(vars,fmt);
    printf("LOG: lev:%d file:%s  line:%d func: %s  ",
          level, file, line, function);
    vprintf(fmt, vars);
    fflush(stdout);
    va_end(vars);
 }
ast_mark_lock_acquired()
void ast_mark_lock_acquired (void * lock_addr)
Mark the last lock as acquired.
Definition at line 700 of file conf2ael.c.
Referenced by __ast_pthread_mutex_lock(), __ast_pthread_mutex_trylock(), __ast_rwlock_rdlock(), __ast_rwlock_timedrdlock(), __ast_rwlock_timedwrlock(), __ast_rwlock_tryrdlock(), __ast_rwlock_trywrlock(), and __ast_rwlock_wrlock().
 {
 }
ast_merge_contexts_and_delete()
void ast_merge_contexts_and_delete (struct ast_context ** extcontexts, struct ast_hashtab * exttable, const char * registrar)
Merge the temporary contexts into a global contexts list and delete from the global list the ones that are being added.
Parameters
extcontexts pointer to the ast_context structure
exttable pointer to the ast_hashtab structure that contains all the elements in extcontexts
registrar of the context; if it's set the routine will delete all contexts that belong to that registrar; if NULL only the contexts that are specified in extcontexts
Definition at line 639 of file conf2ael.c.
References ast_get_context_name(), and localized_merge_contexts_and_delete().
Referenced by ast_context_verify_includes(), lua_reload_extensions(), and pbx_load_module().
 {
    localized_merge_contexts_and_delete(extcontexts, exttable, registrar);
 }
ast_module_register()
void ast_module_register (const struct ast_module_info * x)
Definition at line 603 of file conf2ael.c.
 {
 }
ast_module_unregister()
void ast_module_unregister (const struct ast_module_info * x)
Definition at line 607 of file conf2ael.c.
References ast_cli_unregister_multiple().
 {
 }
ast_remove_lock_info()
void ast_remove_lock_info (void * lock_addr, struct ast_bt * bt)
remove lock info for the current thread
this gets called by ast_mutex_unlock so that information on the lock can be removed from the current thread's lock info struct.
Definition at line 703 of file conf2ael.c.
Referenced by __ast_pthread_mutex_lock(), __ast_pthread_mutex_unlock(), __ast_rwlock_rdlock(), __ast_rwlock_timedrdlock(), __ast_rwlock_timedwrlock(), __ast_rwlock_unlock(), and __ast_rwlock_wrlock().
 {
 }
ast_restore_lock_info()
void ast_restore_lock_info (void * lock_addr)
Definition at line 726 of file conf2ael.c.
Referenced by __ast_cond_timedwait(), and __ast_cond_wait().
 {
 }
ast_store_lock_info()
void ast_store_lock_info (enum ast_lock_type type, const char * filename, int line_num, const char * func, const char * lock_name, void * lock_addr, struct ast_bt * bt)
Store lock info for the current thread.
This function gets called in ast_mutex_lock() and ast_mutex_trylock() so that information about this lock can be stored in this thread's lock info struct. The lock is marked as pending as the thread is waiting on the lock. ast_mark_lock_acquired() will mark it as held by this thread.
Definition at line 707 of file conf2ael.c.
Referenced by __ast_pthread_mutex_lock(), __ast_pthread_mutex_trylock(), __ast_rwlock_rdlock(), __ast_rwlock_timedrdlock(), __ast_rwlock_timedwrlock(), __ast_rwlock_tryrdlock(), __ast_rwlock_trywrlock(), and __ast_rwlock_wrlock().
 {
 }
ast_suspend_lock_info()
void ast_suspend_lock_info (void * lock_addr)
Definition at line 723 of file conf2ael.c.
Referenced by __ast_cond_timedwait(), and __ast_cond_wait().
 {
 }
ast_walk_context_extensions()
struct ast_exten* ast_walk_context_extensions (struct ast_context * con, struct ast_exten * exten)
Definition at line 651 of file conf2ael.c.
References ast_walk_context_includes(), and NULL.
Referenced by ast_get_context_name(), complete_dialplan_remove_extension(), context_used(), dundi_precache_full(), find_matching_priority(), and handle_cli_dialplan_save().
 {
    return NULL;
 }
ast_walk_context_includes()
const struct ast_include* ast_walk_context_includes (const struct ast_context * con, const struct ast_include * inc)
Definition at line 657 of file conf2ael.c.
References context, NULL, and pbx_find_extension().
Referenced by ast_walk_context_extensions().
 {
    return NULL;
 }
ast_walk_contexts()
struct ast_context* ast_walk_contexts (struct ast_context * con)
Definition at line 618 of file conf2ael.c.
References ast_context_destroy(), localized_walk_contexts(), and ast_exten::registrar.
Referenced by _macro_exec(), ast_cli_unregister_multiple(), complete_dialplan_add_extension(), complete_dialplan_add_ignorepat(), complete_dialplan_add_include(), complete_dialplan_remove_context(), complete_dialplan_remove_extension(), complete_dialplan_remove_ignorepat(), complete_dialplan_remove_include(), dundi_precache_full(), find_matching_endif(), find_matching_endwhile(), find_matching_priority(), handle_cli_dialplan_save(), and pbx_load_module().
 {
    return localized_walk_contexts(con);
 }
bit_at()
static int bit_at (unsigned int * word, int bitsperword, int bitnum) static
Definition at line 262 of file conf2ael.c.
Referenced by get_start_stop().
 {
    return word[bitnum/bitsperword] & (1 << (bitnum % bitsperword));
 }
get_start_stop()
void get_start_stop (unsigned int * word, int bitsperword, int totalbits, int * start, int * end)
Definition at line 267 of file conf2ael.c.
References bit_at().
Referenced by main().
 {
    int i;
    int thisbit, thatbit = bit_at(word, bitsperword, totalbits-1);
    for (i=0; i<totalbits; i++) {
       thisbit = bit_at(word, bitsperword, i);
       if (thisbit != thatbit ) {
          if (thisbit) {
             *start = i;
          } else {
             *end = i;
          }
       }
       thatbit = thisbit;
    }
 }
main()
int main (int argc, char ** argv)
Definition at line 305 of file conf2ael.c.
References ael2_print(), all_bits_set(), ast_context::alts, ast_exten::app, args, ast_config_AST_CONFIG_DIR, AST_LIST_FIRST, ast_log(), ast_strdup, config, ast_exten::data, ast_timing::daymask, days, ast_timing::dowmask, ast_exten::exten, free(), get_start_stop(), ast_include::hastime, ast_context::ignorepats, ast_context::includes, localized_pbx_load_module(), localized_use_conf_dir(), localized_walk_context_extensions(), localized_walk_context_switches(), localized_walk_contexts(), localized_walk_extension_priorities(), LOG_ERROR, min, ast_timing::minmask, ast_timing::monthmask, months, ast_sw::name, ast_include::name, ast_context::name, ast_include::next, ast_ignorepat::next, ast_ignorepat::pattern, ast_exten::peer, ast_exten::priority, PV_APPLICATION_CALL, PV_CONTEXT, PV_EXTENSION, PV_IGNOREPAT, PV_INCLUDES, PV_STATEMENTBLOCK, PV_SWITCHES, PV_WORD, pvalAppCallAddArg(), pvalAppCallSetAppName(), pvalContextAddStatement(), pvalContextSetName(), pvalCreateNode(), pvalExtenSetHints(), pvalExtenSetName(), pvalExtenSetStatement(), pvalIgnorePatSetPattern(), pvalIncludesAddInclude(), pvalIncludesAddIncludeWithTimeConstraints(), pvalStatementBlockAddStatement(), pvalSwitchesAddSwitch(), pvalTopLevAddObject(), pvalWordSetString(), strdup, ast_include::timing, and tmp().
 {
    struct ast_context *tmp;
    struct ast_exten *e, *eroot;
    pval *tree, *tmptree, *sws;
    struct ast_include *tmpi;
    struct ast_sw *sw = 0;
    struct ast_ignorepat *ipi;
    pval *incl=0;
    int localdir = 0, i;
    tree = 0;
    tmptree = 0;
    /* process the command line args */
    for (i=1; i<argc; i++)
    {
       if (strcmp(argv[i],"-d")==0)
          localdir =1;
    }
    /* 3 simple steps: */
    /*   1. read in the extensions.conf config file
     *   2. traverse, and build an AEL tree
     *   3. Output the AEL tree into a file
     */
    printf("WARNING: This is an EXTREMELY preliminary version of a program\n");
    printf("         that will someday hopefully do a thoughful and intelligent\n");
    printf("         job of transforming your extensions.conf file into an\n");
    printf("         extensions.ael file.\n");
    printf("         This version has absolutely no intelligence, and pretty\n");
    printf("         much just does a direct conversion\n");
    printf("         The result will most likely need careful attention to\n");
    printf("         finish the job!!!!!\n");
    if (!localdir)
       printf(" (You could use -d the use the extensions.conf in the current directory!)\n");
    printf("Loading %s/%s...\n", ast_config_AST_CONFIG_DIR, config);
    if (!localdir)
       localized_use_conf_dir();
    localized_pbx_load_module();
    printf("... Done!\n");
    tmp = 0;
    while ((tmp = localized_walk_contexts(tmp)) ) {
       printf("Context: %s\n", tmp->name);
    }
    printf("=========\n");
    tmp = 0;
    while ((tmp = localized_walk_contexts(tmp)) ) {
       /* printf("Context: %s\n", tmp->name); */
       tmptree = pvalCreateNode(PV_CONTEXT);
       if (!tree)
          tree = tmptree;
       else
          pvalTopLevAddObject(tree, tmptree);
       pvalContextSetName(tmptree, ast_strdup(tmp->name));
       if (tmp->includes) {
          incl = pvalCreateNode(PV_INCLUDES);
          pvalContextAddStatement(tmptree, incl);
          for (tmpi = tmp->includes; tmpi; ) { /* includes */
             if (strchr(tmpi->name,'|')==0) {
                if (tmpi->hastime)
                {
                   char timerange[15];
                   char dowrange[10];
                   char domrange[10];
                   char monrange[10];
                   int startbit=0, endbit=0;
                   if (all_bits_set(tmpi->timing.minmask, 30, 720))
                      strcpy(timerange, "*");
                   else {
                      int hr, min;
                      char tbuf[20];
                      get_start_stop(tmpi->timing.minmask, 30, 720, &startbit, &endbit);
                      hr = startbit/30;
                      min = (startbit % 30) * 2;
                      sprintf(tbuf,"%02d:%02d", hr, min);
                      strcpy(timerange, tbuf);
                      hr = endbit/30;
                      min = (endbit % 30) * 2;
                      sprintf(tbuf,"%02d:%02d", hr, min);
                      strcat(timerange,"-");
                      strcat(timerange,tbuf);
                   }
                   if (all_bits_set(&tmpi->timing.dowmask, 7, 7))
                      strcpy(dowrange, "*");
                   else {
                      get_start_stop(&tmpi->timing.dowmask, 7, 7, &startbit, &endbit);
                      strcpy(dowrange, days[startbit]);
                      strcat(dowrange,"-");
                      strcat(dowrange, days[endbit]);
                   }
                   if (all_bits_set(&tmpi->timing.monthmask, 12, 12))
                      strcpy(monrange, "*");
                   else {
                      get_start_stop(&tmpi->timing.monthmask, 12, 12, &startbit, &endbit);
                      strcpy(monrange, months[startbit]);
                      strcat(monrange,"-");
                      strcat(monrange, months[endbit]);
                   }
                   if (all_bits_set(&tmpi->timing.daymask, 31, 31))
                      strcpy(domrange, "*");
                   else {
                      char tbuf[20];
                      get_start_stop(&tmpi->timing.daymask, 31, 31, &startbit, &endbit);
                      sprintf(tbuf,"%d", startbit);
                      strcpy(domrange, tbuf);
                      strcat(domrange,"-");
                      sprintf(tbuf,"%d", endbit);
                      strcat(domrange, tbuf);
                   }
                   /* now all 4 fields are set; what do we do? */
                   pvalIncludesAddIncludeWithTimeConstraints(incl, strdup(tmpi->name), strdup(timerange), strdup(domrange), strdup(dowrange), strdup(monrange));
                } else {
                   pvalIncludesAddInclude(incl, strdup(tmpi->name));
                }
             } else { /* it appears the timing constraint info is tacked onto the name, carve it up and divvy it out */
                char *dow,*dom,*mon;
                char *all = strdup(tmpi->name);
                char *hr = strchr(all,'|');
                if (hr) {
                   *hr++ = 0;
                   dow = strchr(hr,'|');
                   if (dow) {
                      *dow++ = 0;
                      dom = strchr(dow,'|');
                      if (dom) {
                         *dom++ = 0;
                         mon = strchr(dom,'|');
                         if (mon) {
                            *mon++ = 0;
                            /* now all 4 fields are set; what do we do? */
                            pvalIncludesAddIncludeWithTimeConstraints(incl, strdup(all), strdup(hr), strdup(dow), strdup(dom), strdup(mon));
                            /* the original data is always best to keep (no 2-min rounding) */
                         } else {
                            ast_log(LOG_ERROR,"No month spec attached to include!\n");
                         }
                      } else {
                         ast_log(LOG_ERROR,"No day of month spec attached to include!\n");
                      }
                   } else {
                      ast_log(LOG_ERROR,"No day of week spec attached to include!\n");
                   }
                }
                free(all);
             }
             tmpi = tmpi->next;
          }
       }
       for (ipi = tmp->ignorepats; ipi; ) { /* ignorepats */
          incl = pvalCreateNode(PV_IGNOREPAT);
          pvalIgnorePatSetPattern(incl,(char *)ipi->pattern);
          pvalContextAddStatement(tmptree, incl);
          ipi = ipi->next;
       }
       eroot=0;
       while ( (eroot = localized_walk_context_extensions(tmp, eroot)) ) {
          pval *exten = pvalCreateNode(PV_EXTENSION);
          pvalContextAddStatement(tmptree, exten);
          pvalExtenSetName(exten, ast_strdup(eroot->exten));
          if (eroot->peer) {
             pval *block = pvalCreateNode(PV_STATEMENTBLOCK);
             pvalExtenSetStatement(exten, block);
             e = 0;
             while ( (e = localized_walk_extension_priorities(eroot, e)) ) {
                pval *statemnt = pvalCreateNode(PV_APPLICATION_CALL);
                pval *args = pvalCreateNode(PV_WORD);
                /* printf("           %s(%s)\n", e->app, (char*)e->data); */
                pvalAppCallSetAppName(statemnt, ast_strdup(e->app));
                pvalWordSetString(args, ast_strdup(e->data));
                pvalAppCallAddArg(statemnt, args);
                pvalStatementBlockAddStatement(block, statemnt);
             }
          } else if (eroot->priority == -1) {
             pval *statemnt = pvalCreateNode(PV_APPLICATION_CALL);
             pval *args = pvalCreateNode(PV_WORD);
             /* printf("Mike, we have a hint on exten %s with data %s\n", eroot->exten, eroot->app); */
             pvalAppCallSetAppName(statemnt, "NoOp");
             pvalWordSetString(args, ast_strdup(eroot->app));
             pvalExtenSetStatement(exten, statemnt);
             pvalExtenSetHints(exten, ast_strdup(eroot->app));
          } else {
             pval *statemnt = pvalCreateNode(PV_APPLICATION_CALL);
             pval *args = pvalCreateNode(PV_WORD);
             /* printf("           %s (%s)\n", eroot->app, (char *)eroot->data); */
             pvalAppCallSetAppName(statemnt, ast_strdup(eroot->app));
             pvalWordSetString(args, ast_strdup(eroot->data));
             pvalAppCallAddArg(statemnt, args);
             pvalExtenSetStatement(exten, statemnt);
          }
          /* printf("   extension: %s\n", eroot->exten); */
       }
       if (AST_LIST_FIRST(&tmp->alts)) {
          sws = pvalCreateNode(PV_SWITCHES);
          pvalContextAddStatement(tmptree,sws);
          sw = 0;
          while ((sw = localized_walk_context_switches(tmp,sw)) ) {
             pvalSwitchesAddSwitch(sws, ast_strdup(sw->name));
          }
       }
    }
    printf("Generating aelout.ael file...\n");
    ael2_print("aelout.ael", tree);
    printf("...Done!\n");
    return 0;
 }
pbx_builtin_setvar()
int pbx_builtin_setvar (struct ast_channel * chan, const char * data)
Parse and set a single channel variable, where the name and value are separated with an '=' character.
Note
Will lock the channel.
Definition at line 546 of file conf2ael.c.
References c, localized_pbx_builtin_setvar(), and pbx_substitute_variables_helper().
Referenced by ast_compile_ael2().
 {
    return localized_pbx_builtin_setvar(chan, data);
 }
pbx_find_extension()
struct ast_exten* pbx_find_extension (struct ast_channel * chan, struct ast_context * bypass, struct pbx_find_info * q, const char * context, const char * exten, int priority, const char * label, const char * callerid, enum ext_match_t action)
Definition at line 672 of file conf2ael.c.
References ast_hashtab_compare_contexts(), and localized_find_extension().
Referenced by add_extension(), ast_sip_persistent_endpoint_update_state(), ast_walk_context_includes(), check_goto(), check_pval_item(), check_retrieve_call_extensions(), conf_ended(), delete_extens(), get_extension_data(), parking_blind_transfer_park(), parking_duration_callback(), parking_is_exten_park(), parking_lot_cfg_create_extensions(), register_peer_exten(), and test_exten().
 {
    return localized_find_extension(bypass, q, context, exten, priority, label, callerid, action);
 }
pbx_substitute_variables_helper()
void pbx_substitute_variables_helper (struct ast_channel * c, const char * cp1, char * cp2, int count)
Definition at line 552 of file conf2ael.c.
References AST_MAX_EXTENSION.
Referenced by add_extensions(), ast_add_extension2_lockopt(), AST_TEST_DEFINE(), dtmf_store_framehook(), escape_and_substitute(), eval_exten_read(), function_eval(), get_mapping_weight(), import_helper(), launch_monitor_thread(), load_values_config(), manager_log(), pbx_builtin_importvar(), pbx_builtin_setvar(), pbx_extension_helper(), pbx_find_extension(), pbx_load_config(), realtime_exec(), rotate_file(), substituted(), test_chan_function(), test_chan_integer(), test_chan_integer_accessor(), test_chan_string(), test_chan_variable(), and write_cel().
 {
    if (cp1 && *cp1)
       strncpy(cp2,cp1,AST_MAX_EXTENSION); /* Right now, this routine is ONLY being called for
                                     a possible var substitution on extension names,
                                     so....! */
    else
       *cp2 = 0;
 }
Variable Documentation
ast_config_AST_CONFIG_DIR
const char* ast_config_AST_CONFIG_DIR = "/etc/asterisk"
Definition at line 59 of file conf2ael.c.
Referenced by action_createconfig(), ast_module_reload(), ast_str_retrieve_variable(), AST_TEST_DEFINE(), compile_script(), config_text_file_load(), delete_config_file(), handle_cli_dialplan_save(), handle_show_settings(), ices_exec(), launch_script(), lua_read_extensions_file(), main(), make_fn(), message_template_parse_filebody(), pbx_load_module(), set_fn(), setup_filestack(), while(), and write_config_file().
config
char* config = "extensions.conf"
Definition at line 66 of file conf2ael.c.
Referenced by __ast_sorcery_apply_config(), ast_ari_asterisk_get_info(), ast_ari_websocket_session_create(), ast_cel_set_config(), ast_config_new(), AST_TEST_DEFINE(), ast_variable_append(), asterisk_publication_config_alloc(), asterisk_publication_config_destroy(), asterisk_publication_devicestate_state_change(), asterisk_publication_mwi_state_change(), asterisk_publication_new(), config_alloc(), config_can_be_inherited(), custom_log(), do_reload(), hep_queue_cb(), hepv3_config_alloc(), hepv3_config_dtor(), hepv3_config_pre_apply(), hepv3_get_uuid_type(), hepv3_is_loaded(), hepv3_send_packet(), ineligible_configuration(), load_config(), load_module(), load_odbc_config(), load_pktccops_config(), main(), misdn_cfg_init(), module_config_alloc(), module_config_dtor(), parse_config(), process_config(), prometheus_config_pre_apply(), prometheus_general_config_alloc(), prometheus_general_config_dtor(), prometheus_show_status(), realtime_sqlite3_load(), regex_filter_handler(), reload_config(), reload_module(), send_refresh_cb(), sorcery_config_close(), sorcery_config_destructor(), sorcery_config_internal_load(), sorcery_config_open(), sorcery_config_retrieve_fields(), sorcery_config_retrieve_id(), sorcery_config_retrieve_multiple(), sorcery_config_retrieve_prefix(), sorcery_config_retrieve_regex(), sorcery_realtime_create(), sorcery_realtime_delete(), sorcery_realtime_open(), sorcery_realtime_retrieve_fields(), sorcery_realtime_retrieve_multiple(), and sorcery_realtime_update().
contexts
static struct ast_context * contexts
Definition at line 4483 of file extconf.c.
Referenced by AST_TEST_DEFINE().
days
char* days[]
Definition at line 3777 of file extconf.c.
Referenced by main().
local_contexts
struct ast_context* local_contexts
Referenced by ast_context_find_or_create(), and pbx_load_module().
months
char* months[]
Definition at line 3789 of file extconf.c.
Referenced by main().