Asterisk - The Open Source Telephony Project: ast_srtp_res Struct Reference
ast_srtp_res Struct Reference
#include <res_srtp.h>
Data Fields
int(* add_stream)(struct ast_srtp *srtp, struct ast_srtp_policy *policy)
int(* change_source)(struct ast_srtp *srtp, unsigned int from_ssrc, unsigned int to_ssrc)
int(* create)(struct ast_srtp **srtp, struct ast_rtp_instance *rtp, struct ast_srtp_policy *policy)
void(* destroy)(struct ast_srtp *srtp)
int(* get_random)(unsigned char *key, size_t len)
int(* protect)(struct ast_srtp *srtp, void **buf, int *size, int rtcp)
int(* replace)(struct ast_srtp **srtp, struct ast_rtp_instance *rtp, struct ast_srtp_policy *policy)
void(* set_cb)(struct ast_srtp *srtp, const struct ast_srtp_cb *cb, void *data)
int(* unprotect)(struct ast_srtp *srtp, void *buf, int *size, int rtcp)
Detailed Description
Definition at line 34 of file res_srtp.h.
Field Documentation
add_stream
int(* add_stream) (struct ast_srtp *srtp, struct ast_srtp_policy *policy)
Definition at line 42 of file res_srtp.h.
Referenced by ast_rtp_instance_add_srtp_policy().
change_source
int(* change_source) (struct ast_srtp *srtp, unsigned int from_ssrc, unsigned int to_ssrc)
Definition at line 44 of file res_srtp.h.
Referenced by ast_rtp_change_source().
create
int(* create) (struct ast_srtp **srtp, struct ast_rtp_instance *rtp, struct ast_srtp_policy *policy)
Create a new SRTP session for an RTP instance with a default policy
Definition at line 36 of file res_srtp.h.
Referenced by ast_rtp_instance_add_srtp_policy().
destroy
void(* destroy) (struct ast_srtp *srtp)
Destroy an SRTP session, along with all associated policies
Definition at line 40 of file res_srtp.h.
Referenced by instance_destructor().
get_random
int(* get_random) (unsigned char *key, size_t len)
Definition at line 52 of file res_srtp.h.
Referenced by crypto_init_keys().
protect
int(* protect) (struct ast_srtp *srtp, void **buf, int *size, int rtcp)
Definition at line 50 of file res_srtp.h.
Referenced by __rtp_sendto().
replace
int(* replace) (struct ast_srtp **srtp, struct ast_rtp_instance *rtp, struct ast_srtp_policy *policy)
Definition at line 38 of file res_srtp.h.
Referenced by ast_rtp_instance_add_srtp_policy().
set_cb
void(* set_cb) (struct ast_srtp *srtp, const struct ast_srtp_cb *cb, void *data)
Definition at line 46 of file res_srtp.h.
unprotect
int(* unprotect) (struct ast_srtp *srtp, void *buf, int *size, int rtcp)
Definition at line 48 of file res_srtp.h.
Referenced by ast_rtcp_interpret(), and ast_rtp_interpret().
The documentation for this struct was generated from the following file:
res_srtp.h