Asterisk - The Open Source Telephony Project: xml.h File Reference
xml.h File Reference
Asterisk XML abstraction layer.
Functions
struct ast_xml_node * ast_xml_add_child (struct ast_xml_node *parent, struct ast_xml_node *child)
Add a child node, to a specified parent node.
struct ast_xml_node * ast_xml_add_child_list (struct ast_xml_node *parent, struct ast_xml_node *child)
Add a list of child nodes, to a specified parent node.
void ast_xml_close (struct ast_xml_doc *doc)
Close an already open document and free the used structure.
struct ast_xml_node * ast_xml_copy_node_list (struct ast_xml_node *list)
Create a copy of a n ode list.
int ast_xml_doc_dump_file (FILE *output, struct ast_xml_doc *doc)
Dump the specified document to a file.
struct ast_xml_node * ast_xml_find_element (struct ast_xml_node *root_node, const char *name, const char *attrname, const char *attrvalue)
Find a node element by name.
struct ast_xml_ns * ast_xml_find_namespace (struct ast_xml_doc *doc, struct ast_xml_node *node, const char *ns_name)
int ast_xml_finish (void)
Cleanup library allocated global data.
void ast_xml_free_attr (const char *attribute)
Free an attribute returned by ast_xml_get_attribute()
void ast_xml_free_node (struct ast_xml_node *node)
Free node.
void ast_xml_free_text (const char *text)
Free a content element that was returned by ast_xml_get_text()
const char * ast_xml_get_attribute (struct ast_xml_node *node, const char *attrname)
Get a node attribute by name.
struct ast_xml_doc * ast_xml_get_doc (struct ast_xml_node *node)
Get the document based on a node.
const char * ast_xml_get_ns_href (struct ast_xml_ns *ns)
struct ast_xml_node * ast_xml_get_root (struct ast_xml_doc *doc)
Get the document root node.
const char * ast_xml_get_text (struct ast_xml_node *node)
Get an element content string.
int ast_xml_init (void)
Initialize the XML library implementation. This function is used to setup everything needed to start working with the xml implementation.
struct ast_xml_doc * ast_xml_new (void)
Create a XML document.
struct ast_xml_node * ast_xml_new_child (struct ast_xml_node *parent, const char *child_name)
Add a child node inside a passed parent node.
struct ast_xml_node * ast_xml_new_node (const char *name)
Create a XML node.
struct ast_xml_node * ast_xml_node_get_children (struct ast_xml_node *node)
Get the node's children.
const char * ast_xml_node_get_name (struct ast_xml_node *node)
Get the name of a node.
struct ast_xml_node * ast_xml_node_get_next (struct ast_xml_node *node)
Get the next node in the same level.
struct ast_xml_node * ast_xml_node_get_parent (struct ast_xml_node *node)
Get the parent of a specified node.
struct ast_xml_node * ast_xml_node_get_prev (struct ast_xml_node *node)
Get the previous node in the same leve.
struct ast_xml_doc * ast_xml_open (char *filename)
Open an XML document.
struct ast_xml_xpath_results * ast_xml_query (struct ast_xml_doc *doc, const char *xpath_str)
Execute an XPath query on an XML document.
struct ast_xml_doc * ast_xml_read_memory (char *buffer, size_t size)
Open an XML document that resides in memory.
int ast_xml_set_attribute (struct ast_xml_node *node, const char *name, const char *value)
Set an attribute to a node.
void ast_xml_set_root (struct ast_xml_doc *doc, struct ast_xml_node *node)
Specify the root node of a XML document.
void ast_xml_set_text (struct ast_xml_node *node, const char *content)
Set an element content string.
struct ast_xml_node * ast_xml_xpath_get_first_result (struct ast_xml_xpath_results *results)
Return the first result node of an XPath query.
int ast_xml_xpath_num_results (struct ast_xml_xpath_results *results)
Return the number of results from an XPath query.
void ast_xml_xpath_results_free (struct ast_xml_xpath_results *results)
Free the XPath results.
Detailed Description
Asterisk XML abstraction layer.
Definition in file xml.h.
Function Documentation
ast_xml_add_child()
struct ast_xml_node* ast_xml_add_child (struct ast_xml_node * parent, struct ast_xml_node * child)
Add a child node, to a specified parent node.
Parameters
parent Where to add the child node.
child The child node to add.
Return values
NULL on error.
non-NULL The add child node on success.
Definition at line 137 of file xml.c.
References NULL.
 {
    if (!parent || !child) {
       return NULL;
    }
    return (struct ast_xml_node *) xmlAddChild((xmlNode *) parent, (xmlNode *) child);
 }
ast_xml_add_child_list()
struct ast_xml_node* ast_xml_add_child_list (struct ast_xml_node * parent, struct ast_xml_node * child)
Add a list of child nodes, to a specified parent node.
Parameters
parent Where to add the child node.
child The child list to add.
Return values
NULL on error.
non-NULL The added child list on success.
Definition at line 145 of file xml.c.
References NULL.
Referenced by handle_dump_docs().
 {
    if (!parent || !child) {
       return NULL;
    }
    return (struct ast_xml_node *) xmlAddChildList((xmlNode *) parent, (xmlNode *) child);
 }
ast_xml_close()
void ast_xml_close (struct ast_xml_doc * doc)
Close an already open document and free the used structure.
Return values
doc The document reference.
Definition at line 180 of file xml.c.
References NULL.
Referenced by ast_xmldoc_load_documentation(), cc_esc_publish_handler(), handle_dump_docs(), sip_pidf_validate(), and xmldoc_unload_documentation().
 {
    if (!doc) {
       return;
    }
    xmlFreeDoc((xmlDoc *) doc);
    doc = NULL;
 }
ast_xml_copy_node_list()
struct ast_xml_node* ast_xml_copy_node_list (struct ast_xml_node * list)
Create a copy of a n ode list.
Parameters
list The list to copy.
Return values
NULL on error.
non-NULL The copied list.
Definition at line 153 of file xml.c.
References NULL.
Referenced by handle_dump_docs().
 {
    if (!list) {
       return NULL;
    }
    return (struct ast_xml_node *) xmlCopyNodeList((xmlNode *) list);
 }
ast_xml_doc_dump_file()
int ast_xml_doc_dump_file (FILE * output, struct ast_xml_doc * doc)
Dump the specified document to a file.
Definition at line 335 of file xml.c.
Referenced by handle_dump_docs().
 {
    return xmlDocDump(output, (xmlDocPtr)doc);
 }
ast_xml_find_element()
struct ast_xml_node* ast_xml_find_element (struct ast_xml_node * root_node, const char * name, const char * attrname, const char * attrvalue)
Find a node element by name.
Parameters
root_node This is the node starting point.
name Node name to find.
attrname attribute name to match (if NULL it won't be matched).
attrvalue attribute value to match (if NULL it won't be matched).
Return values
NULL if not found.
The node on success.
Definition at line 266 of file xml.c.
References ast_xml_free_attr(), ast_xml_get_attribute(), ast_xml_node_get_name(), ast_xml_node_get_next(), and NULL.
Referenced by _xmldoc_build_field(), cc_esc_publish_handler(), load_modules(), xmldoc_build_final_response(), xmldoc_build_list_responses(), xmldoc_get_node(), and xmldoc_get_syntax_config_object().
 {
    struct ast_xml_node *cur;
    const char *attr;
    if (!root_node) {
       return NULL;
    }
    for (cur = root_node; cur; cur = ast_xml_node_get_next(cur)) {
       /* Check if the name matchs */
       if (strcmp(ast_xml_node_get_name(cur), name)) {
          continue;
       }
       /* We need to check for a specific attribute name? */
       if (!attrname || !attrvalue) {
          return cur;
       }
       /* Get the attribute, we need to compare it. */
       if ((attr = ast_xml_get_attribute(cur, attrname))) {
          /* does attribute name/value matches? */
          if (!strcmp(attr, attrvalue)) {
             ast_xml_free_attr(attr);
             return cur;
          }
          ast_xml_free_attr(attr);
       }
    }
    return NULL;
 }
ast_xml_find_namespace()
struct ast_xml_ns* ast_xml_find_namespace (struct ast_xml_doc * doc, struct ast_xml_node * node, const char * ns_name)
Definition at line 307 of file xml.c.
Referenced by pidf_validate_presence().
{
    xmlNsPtr ns = xmlSearchNs((xmlDocPtr) doc, (xmlNodePtr) node, (xmlChar *) ns_name);
    return (struct ast_xml_ns *) ns;
 }
ast_xml_finish()
int ast_xml_finish (void)
Cleanup library allocated global data.
Return values
0 On success.
1 On error.
Definition at line 53 of file xml.c.
Referenced by xmldoc_unload_documentation().
 {
    xmlCleanupParser();
 #ifdef HAVE_LIBXSLT_CLEANUP
    xsltCleanupGlobals();
 #endif
    return 0;
 }
ast_xml_free_attr()
void ast_xml_free_attr (const char * attribute)
Free an attribute returned by ast_xml_get_attribute()
Parameters
attribute pointer to be freed.
Definition at line 222 of file xml.c.
Referenced by _ast_xmldoc_build_seealso(), ast_xml_find_element(), ast_xmldoc_build_documentation(), ast_xmldoc_regenerate_doc_item(), build_config_docs(), pidf_validate_presence(), pidf_validate_tuple(), xmldoc_attribute_match(), xmldoc_build_final_response(), xmldoc_build_list_responses(), xmldoc_get_syntax_cmd(), xmldoc_get_syntax_config_object(), xmldoc_get_syntax_config_option(), xmldoc_get_syntax_fun(), xmldoc_get_syntax_manager(), xmldoc_parse_argument(), xmldoc_parse_enumlist(), xmldoc_parse_example(), xmldoc_parse_info(), xmldoc_parse_optionlist(), xmldoc_parse_parameter(), xmldoc_parse_variable(), and xmldoc_parse_variablelist().
 {
    if (attribute) {
       xmlFree((char *) attribute);
    }
 }
ast_xml_free_node()
void ast_xml_free_node (struct ast_xml_node * node)
Free node.
Parameters
node Node to be released.
Definition at line 212 of file xml.c.
References NULL.
 {
    if (!node) {
       return;
    }
    xmlFreeNode((xmlNode *) node);
    node = NULL;
 }
ast_xml_free_text()
void ast_xml_free_text (const char * text)
Free a content element that was returned by ast_xml_get_text()
Parameters
text text to be freed.
Definition at line 229 of file xml.c.
Referenced by _ast_xmldoc_build_seealso(), cc_esc_publish_handler(), xmldoc_get_formatted(), xmldoc_get_syntax_config_object(), xmldoc_parse_example(), xmldoc_parse_para(), and xmldoc_parse_variable().
 {
    if (text) {
       xmlFree((char *) text);
    }
 }
ast_xml_get_attribute()
const char* ast_xml_get_attribute (struct ast_xml_node * node, const char * attrname)
Get a node attribute by name.
Parameters
node Node where to search the attribute.
attrname Attribute name.
Return values
NULL on error
The attribute value on success.
Definition at line 236 of file xml.c.
References NULL.
Referenced by _ast_xmldoc_build_seealso(), ast_xml_find_element(), ast_xmldoc_build_documentation(), ast_xmldoc_regenerate_doc_item(), build_config_docs(), pidf_validate_presence(), pidf_validate_tuple(), xmldoc_attribute_match(), xmldoc_build_final_response(), xmldoc_build_list_responses(), xmldoc_get_syntax_cmd(), xmldoc_get_syntax_config_object(), xmldoc_get_syntax_config_option(), xmldoc_get_syntax_fun(), xmldoc_get_syntax_manager(), xmldoc_parse_argument(), xmldoc_parse_enumlist(), xmldoc_parse_example(), xmldoc_parse_info(), xmldoc_parse_optionlist(), xmldoc_parse_parameter(), xmldoc_parse_variable(), and xmldoc_parse_variablelist().
 {
    xmlChar *attrvalue;
    if (!node) {
       return NULL;
    }
    if (!attrname) {
       return NULL;
    }
    attrvalue = xmlGetProp((xmlNode *) node, (xmlChar *) attrname);
    return (const char *) attrvalue;
 }
ast_xml_get_doc()
struct ast_xml_doc* ast_xml_get_doc (struct ast_xml_node * node)
Get the document based on a node.
Parameters
node A node that is part of the dom.
Returns
The dom pointer where this node resides.
Definition at line 298 of file xml.c.
References NULL.
 {
    if (!node) {
       return NULL;
    }
    return (struct ast_xml_doc *) ((xmlNode *)node)->doc;
 }
ast_xml_get_ns_href()
const char* ast_xml_get_ns_href (struct ast_xml_ns * ns)
Definition at line 312 of file xml.c.
Referenced by pidf_validate_presence().
 {
    return (const char *) ((xmlNsPtr) ns)->href;
 }
ast_xml_get_root()
struct ast_xml_node* ast_xml_get_root (struct ast_xml_doc * doc)
Get the document root node.
Parameters
doc Document reference
Return values
NULL on error
The root node on success.
Definition at line 199 of file xml.c.
References NULL.
Referenced by ast_xmldoc_build_documentation(), ast_xmldoc_load_documentation(), cc_esc_publish_handler(), handle_dump_docs(), pidf_validate_presence(), and xmldoc_get_node().
 {
    xmlNode *root_node;
    if (!doc) {
       return NULL;
    }
    root_node = xmlDocGetRootElement((xmlDoc *) doc);
    return (struct ast_xml_node *) root_node;
 }
ast_xml_get_text()
const char* ast_xml_get_text (struct ast_xml_node * node)
Get an element content string.
Parameters
node Node from where to get the string.
Return values
NULL on error.
The text content of node.
Definition at line 317 of file xml.c.
References NULL.
Referenced by _ast_xmldoc_build_seealso(), cc_esc_publish_handler(), load_modules(), xmldoc_get_formatted(), xmldoc_get_syntax_config_object(), xmldoc_parse_example(), xmldoc_parse_para(), and xmldoc_parse_variable().
 {
    if (!node) {
       return NULL;
    }
    return (const char *) xmlNodeGetContent((xmlNode *) node);
 }
ast_xml_init()
int ast_xml_init (void)
Initialize the XML library implementation. This function is used to setup everything needed to start working with the xml implementation.
Return values
0 On success.
1 On error.
Definition at line 46 of file xml.c.
Referenced by ast_xmldoc_load_documentation().
 {
    LIBXML_TEST_VERSION
    return 0;
 }
ast_xml_new()
struct ast_xml_doc* ast_xml_new (void)
Create a XML document.
Return values
NULL on error.
non-NULL The allocated document structure.
Definition at line 105 of file xml.c.
Referenced by handle_dump_docs().
 {
    xmlDoc *doc;
    doc = xmlNewDoc((const xmlChar *) "1.0");
    return (struct ast_xml_doc *) doc;
 }
ast_xml_new_child()
struct ast_xml_node* ast_xml_new_child (struct ast_xml_node * parent, const char * child_name)
Add a child node inside a passed parent node.
Parameters
parent The pointer of the parent node.
child_name The name of the child node to add.
Return values
NULL on error.
non-NULL The created child node pointer.
Definition at line 125 of file xml.c.
References NULL.
Referenced by xmldoc_update_config_type().
 {
    xmlNode *child;
    if (!parent || !child_name) {
       return NULL;
    }
    child = xmlNewChild((xmlNode *) parent, NULL, (const xmlChar *) child_name, NULL);
    return (struct ast_xml_node *) child;
 }
ast_xml_new_node()
struct ast_xml_node* ast_xml_new_node (const char * name)
Create a XML node.
Parameters
name The name of the node to be created.
Return values
NULL on error.
non-NULL The allocated node structe.
Definition at line 113 of file xml.c.
References NULL.
Referenced by handle_dump_docs().
 {
    xmlNode *node;
    if (!name) {
       return NULL;
    }
    node = xmlNewNode(NULL, (const xmlChar *) name);
    return (struct ast_xml_node *) node;
 }
ast_xml_node_get_children()
struct ast_xml_node* ast_xml_node_get_children (struct ast_xml_node * node)
Get the node's children.
Definition at line 345 of file xml.c.
Referenced by _ast_xmldoc_build_arguments(), _ast_xmldoc_build_seealso(), _ast_xmldoc_build_syntax(), _xmldoc_build_field(), ast_xmldoc_build_arguments(), ast_xmldoc_build_documentation(), ast_xmldoc_build_final_response(), ast_xmldoc_build_list_responses(), ast_xmldoc_build_seealso(), build_config_docs(), cc_esc_publish_handler(), handle_dump_docs(), load_modules(), pidf_validate_presence(), pidf_validate_tuple(), xmldoc_build_final_response(), xmldoc_build_list_responses(), xmldoc_get_formatted(), xmldoc_get_node(), xmldoc_get_syntax_cmd(), xmldoc_get_syntax_config_object(), xmldoc_get_syntax_fun(), xmldoc_get_syntax_manager(), xmldoc_has_inside(), xmldoc_has_nodes(), xmldoc_has_specialtags(), xmldoc_parse_argument(), xmldoc_parse_cmd_enumlist(), xmldoc_parse_enum(), xmldoc_parse_enumlist(), xmldoc_parse_example(), xmldoc_parse_info(), xmldoc_parse_option(), xmldoc_parse_optionlist(), xmldoc_parse_para(), xmldoc_parse_parameter(), xmldoc_parse_specialtags(), xmldoc_parse_variable(), and xmldoc_parse_variablelist().
 {
    return (struct ast_xml_node *) ((xmlNode *) node)->children;
 }
ast_xml_node_get_name()
const char* ast_xml_node_get_name (struct ast_xml_node * node)
Get the name of a node.
Definition at line 340 of file xml.c.
Referenced by _ast_xmldoc_build_arguments(), _ast_xmldoc_build_seealso(), _ast_xmldoc_build_syntax(), ast_xml_find_element(), ast_xmldoc_build_documentation(), ast_xmldoc_load_documentation(), build_config_docs(), pidf_validate_presence(), pidf_validate_tuple(), xmldoc_build_list_responses(), xmldoc_get_syntax_cmd(), xmldoc_get_syntax_fun(), xmldoc_get_syntax_manager(), xmldoc_has_inside(), xmldoc_has_nodes(), xmldoc_has_specialtags(), xmldoc_parse_cmd_enumlist(), xmldoc_parse_enumlist(), xmldoc_parse_example(), xmldoc_parse_info(), xmldoc_parse_option(), xmldoc_parse_optionlist(), xmldoc_parse_para(), xmldoc_parse_parameter(), xmldoc_parse_specialtags(), xmldoc_parse_variable(), and xmldoc_parse_variablelist().
 {
    return (const char *) ((xmlNode *) node)->name;
 }
ast_xml_node_get_next()
struct ast_xml_node* ast_xml_node_get_next (struct ast_xml_node * node)
Get the next node in the same level.
Definition at line 350 of file xml.c.
Referenced by _ast_xmldoc_build_arguments(), _ast_xmldoc_build_seealso(), _ast_xmldoc_build_syntax(), ast_xml_find_element(), ast_xmldoc_build_documentation(), build_config_docs(), pidf_validate_presence(), pidf_validate_tuple(), xmldoc_build_list_responses(), xmldoc_get_formatted(), xmldoc_get_node(), xmldoc_get_syntax_cmd(), xmldoc_get_syntax_fun(), xmldoc_get_syntax_manager(), xmldoc_has_inside(), xmldoc_has_nodes(), xmldoc_has_specialtags(), xmldoc_parse_argument(), xmldoc_parse_cmd_enumlist(), xmldoc_parse_enum(), xmldoc_parse_enumlist(), xmldoc_parse_example(), xmldoc_parse_info(), xmldoc_parse_option(), xmldoc_parse_optionlist(), xmldoc_parse_para(), xmldoc_parse_parameter(), xmldoc_parse_specialtags(), xmldoc_parse_variable(), and xmldoc_parse_variablelist().
 {
    return (struct ast_xml_node *) ((xmlNode *) node)->next;
 }
ast_xml_node_get_parent()
struct ast_xml_node* ast_xml_node_get_parent (struct ast_xml_node * node)
Get the parent of a specified node.
Definition at line 360 of file xml.c.
 {
    return (struct ast_xml_node *) ((xmlNode *) node)->parent;
 }
ast_xml_node_get_prev()
struct ast_xml_node* ast_xml_node_get_prev (struct ast_xml_node * node)
Get the previous node in the same leve.
Definition at line 355 of file xml.c.
 {
    return (struct ast_xml_node *) ((xmlNode *) node)->prev;
 }
ast_xml_open()
struct ast_xml_doc* ast_xml_open (char * filename)
Open an XML document.
Parameters
filename Document path.
Return values
NULL on error.
The ast_xml_doc reference to the open document.
Definition at line 63 of file xml.c.
References ast_log, LOG_NOTICE, and NULL.
Referenced by ast_xmldoc_load_documentation().
 {
    xmlDoc *doc;
    if (!filename) {
       return NULL;
    }
    doc = xmlReadFile(filename, NULL, XML_PARSE_RECOVER);
    if (!doc) {
       return NULL;
    }
    /* process xinclude elements. */
    if (xmlXIncludeProcess(doc) < 0) {
       xmlFreeDoc(doc);
       return NULL;
    }
 #ifdef HAVE_LIBXSLT
    {
       xsltStylesheetPtr xslt = xsltLoadStylesheetPI(doc);
       if (xslt) {
          xmlDocPtr tmpdoc = xsltApplyStylesheet(xslt, doc, NULL);
          xsltFreeStylesheet(xslt);
          xmlFreeDoc(doc);
          if (!tmpdoc) {
             return NULL;
          }
          doc = tmpdoc;
       }
    }
 #else /* no HAVE_LIBXSLT */
    ast_log(LOG_NOTICE, "XSLT support not found. XML documentation may be incomplete.\n");
 #endif /* HAVE_LIBXSLT */
    /* Optimize for XPath */
    xmlXPathOrderDocElems(doc);
    return (struct ast_xml_doc *) doc;
 }
ast_xml_query()
struct ast_xml_xpath_results* ast_xml_query (struct ast_xml_doc * doc, const char * xpath_str)
Execute an XPath query on an XML document.
Parameters
doc The XML document to query
xpath_str The XPath query string to execute on the document
Return values
An object containing the results of the XPath query on success
NULL on failure
Since
12
Definition at line 380 of file xml.c.
References ast_debug, ast_log, context, LOG_ERROR, LOG_WARNING, NULL, and result.
Referenced by ast_xmldoc_query().
 {
    xmlXPathContextPtr context;
    xmlXPathObjectPtr result;
    if (!(context = xmlXPathNewContext((xmlDoc *) doc))) {
       ast_log(LOG_ERROR, "Could not create XPath context!\n");
       return NULL;
    }
    result = xmlXPathEvalExpression((xmlChar *) xpath_str, context);
    xmlXPathFreeContext(context);
    if (!result) {
       ast_log(LOG_WARNING, "Error for query: %s\n", xpath_str);
       return NULL;
    }
    if (xmlXPathNodeSetIsEmpty(result->nodesetval)) {
       xmlXPathFreeObject(result);
       ast_debug(5, "No results for query: %s\n", xpath_str);
       return NULL;
    }
    return (struct ast_xml_xpath_results *) result;
 }
ast_xml_read_memory()
struct ast_xml_doc* ast_xml_read_memory (char * buffer, size_t size)
Open an XML document that resides in memory.
Parameters
buffer The address where the document is stored
size The number of bytes in the document
Return values
NULL on error.
The ast_xml_doc reference to the open document.
Definition at line 161 of file xml.c.
References NULL.
Referenced by sip_pidf_validate().
 {
    xmlDoc *doc;
    if (!buffer) {
       return NULL;
    }
    if (!(doc = xmlParseMemory(buffer, (int) size))) {
       /* process xinclude elements. */
       if (xmlXIncludeProcess(doc) < 0) {
          xmlFreeDoc(doc);
          return NULL;
       }
    }
    return (struct ast_xml_doc *) doc;
 }
ast_xml_set_attribute()
int ast_xml_set_attribute (struct ast_xml_node * node, const char * name, const char * value)
Set an attribute to a node.
Parameters
node In which node we want to insert the attribute.
name The attribute name.
value The attribute value.
Return values
0 on success.
-1 on error.
Definition at line 253 of file xml.c.
Referenced by xmldoc_update_config_option(), and xmldoc_update_config_type().
 {
    if (!name || !value) {
       return -1;
    }
    if (!xmlSetProp((xmlNode *) node, (xmlChar *) name, (xmlChar *) value)) {
       return -1;
    }
    return 0;
 }
ast_xml_set_root()
void ast_xml_set_root (struct ast_xml_doc * doc, struct ast_xml_node * node)
Specify the root node of a XML document.
Parameters
doc The document pointer.
node A pointer to the node we want to set as root node.
Definition at line 190 of file xml.c.
Referenced by handle_dump_docs().
 {
    if (!doc || !node) {
       return;
    }
    xmlDocSetRootElement((xmlDoc *) doc, (xmlNode *) node);
 }
ast_xml_set_text()
void ast_xml_set_text (struct ast_xml_node * node, const char * content)
Set an element content string.
Parameters
node Node from where to set the content string.
content The text to insert in the node.
Definition at line 326 of file xml.c.
Referenced by xmldoc_update_config_type().
 {
    if (!node || !content) {
       return;
    }
    xmlNodeSetContent((xmlNode *) node, (const xmlChar *) content);
 }
ast_xml_xpath_get_first_result()
struct ast_xml_node* ast_xml_xpath_get_first_result (struct ast_xml_xpath_results * results)
Return the first result node of an XPath query.
Parameters
results The XPath results object to get the first result from
Return values
The first result in the XPath object on success
NULL on error
Since
12
Definition at line 365 of file xml.c.
Referenced by load_modules(), xmldoc_update_config_option(), and xmldoc_update_config_type().
 {
    return (struct ast_xml_node *) ((xmlXPathObjectPtr) results)->nodesetval->nodeTab[0];
 }
ast_xml_xpath_num_results()
int ast_xml_xpath_num_results (struct ast_xml_xpath_results * results)
Return the number of results from an XPath query.
Parameters
results The XPath results object to count
Return values
The number of results in the XPath object
Since
12
Definition at line 375 of file xml.c.
 {
    return ((xmlXPathObjectPtr) results)->nodesetval->nodeNr;
 }
ast_xml_xpath_results_free()
void ast_xml_xpath_results_free (struct ast_xml_xpath_results * results)
Free the XPath results.
Parameters
results The XPath results object to dispose of
Since
12
Definition at line 370 of file xml.c.
Referenced by load_modules(), xmldoc_update_config_option(), and xmldoc_update_config_type().
 {
    xmlXPathFreeObject((xmlXPathObjectPtr) results);
 }