Asterisk - The Open Source Telephony Project: res_manager_presencestate.c File Reference
res_manager_presencestate.c File Reference
#include "asterisk.h"
#include "asterisk/module.h"
#include "asterisk/manager.h"
#include "asterisk/stasis.h"
#include "asterisk/presencestate.h"
Functions
static void __reg_module (void)
static void __unreg_module (void)
static int action_presencestatelist (struct mansession *s, const struct message *m)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int load_module (void)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Manager Presence State Topic Forwarder" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEVSTATE_CONSUMER, }
static const struct ast_module_info * ast_module_info = &__mod_info
static struct stasis_forward * topic_forwarder
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 149 of file res_manager_presencestate.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 149 of file res_manager_presencestate.c.
action_presencestatelist()
static int action_presencestatelist (struct mansession * s, const struct message * m) static
Definition at line 73 of file res_manager_presencestate.c.
References ao2_cleanup, ao2_iterator_destroy(), ao2_iterator_init(), ao2_iterator_next, ao2_ref, ast_presence_state_cache(), ast_presence_state_message_type(), ast_strlen_zero, astman_append(), astman_get_header(), astman_send_error(), astman_send_list_complete_end(), astman_send_list_complete_start(), astman_send_listack(), ast_manager_event_blob::extra_fields, ast_manager_event_blob::manager_event, NULL, RAII_VAR, stasis_cache_dump(), and stasis_message_to_ami().
Referenced by load_module().
 {
    RAII_VAR(struct ao2_container *, presence_states, NULL, ao2_cleanup);
    const char *action_id = astman_get_header(m, "ActionID");
    struct stasis_message *msg;
    struct ao2_iterator it_states;
    int count = 0;
    presence_states = stasis_cache_dump(ast_presence_state_cache(),
       ast_presence_state_message_type());
    if (!presence_states) {
       astman_send_error(s, m, "Memory Allocation Failure");
       return 0;
    }
    astman_send_listack(s, m, "Presence State Changes will follow", "start");
    it_states = ao2_iterator_init(presence_states, 0);
    for (; (msg = ao2_iterator_next(&it_states)); ao2_ref(msg, -1)) {
       struct ast_manager_event_blob *blob = stasis_message_to_ami(msg);
       if (!blob) {
          continue;
       }
       count++;
       astman_append(s, "Event: %s\r\n", blob->manager_event);
       if (!ast_strlen_zero(action_id)) {
          astman_append(s, "ActionID: %s\r\n", action_id);
       }
       astman_append(s, "%s\r\n", blob->extra_fields);
       ao2_ref(blob, -1);
    }
    ao2_iterator_destroy(&it_states);
    astman_send_list_complete_start(s, m, "PresenceStateListComplete", count);
    astman_send_list_complete_end(s);
    return 0;
 }
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 149 of file res_manager_presencestate.c.
load_module()
static int load_module (void) static
Definition at line 122 of file res_manager_presencestate.c.
References action_presencestatelist(), ast_manager_get_topic(), ast_manager_register_xml, AST_MODFLAG_LOAD_ORDER, AST_MODPRI_DEVSTATE_CONSUMER, AST_MODULE_INFO(), AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, AST_MODULE_SUPPORT_CORE, ast_presence_state_topic_all(), ASTERISK_GPL_KEY, EVENT_FLAG_CALL, EVENT_FLAG_REPORTING, manager_topic, stasis_forward_all(), stasis_forward_cancel(), and unload_module().
 {
    struct stasis_topic *manager_topic;
    manager_topic = ast_manager_get_topic();
    if (!manager_topic) {
       return AST_MODULE_LOAD_DECLINE;
    }
    topic_forwarder = stasis_forward_all(ast_presence_state_topic_all(), manager_topic);
    if (!topic_forwarder) {
       return AST_MODULE_LOAD_DECLINE;
    }
    if (ast_manager_register_xml("PresenceStateList", EVENT_FLAG_CALL | EVENT_FLAG_REPORTING,
                                action_presencestatelist)) {
       topic_forwarder = stasis_forward_cancel(topic_forwarder);
       return AST_MODULE_LOAD_DECLINE;
    }
    return AST_MODULE_LOAD_SUCCESS;
 }
unload_module()
static int unload_module (void) static
Definition at line 115 of file res_manager_presencestate.c.
References ast_manager_unregister(), and stasis_forward_cancel().
Referenced by load_module().
 {
    ast_manager_unregister("PresenceStateList");
    topic_forwarder = stasis_forward_cancel(topic_forwarder);
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Manager Presence State Topic Forwarder" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEVSTATE_CONSUMER, } static
Definition at line 149 of file res_manager_presencestate.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 149 of file res_manager_presencestate.c.
topic_forwarder
struct stasis_forward* topic_forwarder static
Definition at line 71 of file res_manager_presencestate.c.