Asterisk - The Open Source Telephony Project: res_pjsip_endpoint_identifier_user.c File Reference
res_pjsip_endpoint_identifier_user.c File Reference
#include "asterisk.h"
#include <pjsip.h>
#include "asterisk/res_pjsip.h"
#include "asterisk/module.h"
Macros
#define DOMAIN_NAME_LEN 255
#define USERNAME_LEN 255
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static struct ast_sip_endpoint * auth_username_identify (pjsip_rx_data *rdata)
static struct ast_sip_endpoint * find_endpoint (pjsip_rx_data *rdata, char *endpoint_name, char *domain_name)
static int find_transport_state_in_use (void *obj, void *arg, int flags)
static pjsip_authorization_hdr * get_auth_header (pjsip_rx_data *rdata, char *username, size_t username_size, char *realm, size_t realm_size, pjsip_authorization_hdr *start)
static int get_from_header (pjsip_rx_data *rdata, char *username, size_t username_size, char *domain, size_t domain_size)
static int load_module (void)
static int unload_module (void)
static struct ast_sip_endpoint * username_identify (pjsip_rx_data *rdata)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "PJSIP username endpoint identifier" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_CHANNEL_DEPEND - 4, .requires = "res_pjsip", }
static const struct ast_module_info * ast_module_info = &__mod_info
static struct ast_sip_endpoint_identifier auth_username_identifier
static struct ast_sip_endpoint_identifier username_identifier
Macro Definition Documentation
DOMAIN_NAME_LEN
#define DOMAIN_NAME_LEN 255
Definition at line 78 of file res_pjsip_endpoint_identifier_user.c.
Referenced by auth_username_identify(), find_endpoint(), and username_identify().
USERNAME_LEN
#define USERNAME_LEN 255
Definition at line 79 of file res_pjsip_endpoint_identifier_user.c.
Referenced by auth_username_identify(), find_endpoint(), and username_identify().
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 227 of file res_pjsip_endpoint_identifier_user.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 227 of file res_pjsip_endpoint_identifier_user.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 227 of file res_pjsip_endpoint_identifier_user.c.
auth_username_identify()
static struct ast_sip_endpoint* auth_username_identify (pjsip_rx_data * rdata) static
Definition at line 165 of file res_pjsip_endpoint_identifier_user.c.
References ao2_cleanup, ast_debug, AST_SIP_ENDPOINT_IDENTIFY_BY_AUTH_USERNAME, DOMAIN_NAME_LEN, find_endpoint(), get_auth_header(), ast_sip_endpoint::ident_method, NULL, and USERNAME_LEN.
 {
    char username[USERNAME_LEN + 1], realm[DOMAIN_NAME_LEN + 1];
    struct ast_sip_endpoint *endpoint;
    pjsip_authorization_hdr *auth_header = NULL;
    while ((auth_header = get_auth_header(rdata, username, sizeof(username), realm, sizeof(realm),
       auth_header ? auth_header->next : NULL))) {
       ast_debug(3, "Attempting identify by Authorization username '%s' realm '%s'\n", username,
          realm);
       endpoint = find_endpoint(rdata, username, realm);
       if (!endpoint) {
          ast_debug(3, "Endpoint not found for Authentication username '%s' realm '%s'\n",
             username, realm);
          ao2_cleanup(endpoint);
          continue;
       }
       if (!(endpoint->ident_method & AST_SIP_ENDPOINT_IDENTIFY_BY_AUTH_USERNAME)) {
          ast_debug(3, "Endpoint found for '%s' but 'auth_username' method not supported'\n",
             username);
          ao2_cleanup(endpoint);
          continue;
       }
       ast_debug(3, "Identified by Authorization username '%s' realm '%s'\n", username, realm);
       return endpoint;
    }
    return NULL;
 }
find_endpoint()
static struct ast_sip_endpoint* find_endpoint (pjsip_rx_data * rdata, char * endpoint_name, char * domain_name) static
Definition at line 81 of file res_pjsip_endpoint_identifier_user.c.
References ao2_callback, ao2_cleanup, ao2_ref, ast_sip_get_disable_multi_domain(), ast_sip_get_sorcery(), ast_sip_get_transport_states(), ast_sorcery_retrieve_by_id(), ast_strlen_zero, ast_sip_transport::domain, ast_sip_domain_alias::domain, DOMAIN_NAME_LEN, find_transport_state_in_use(), ast_sip_transport_state::id, NULL, transport_states, and USERNAME_LEN.
Referenced by auth_username_identify(), and username_identify().
 {
    struct ast_sip_endpoint *endpoint;
    if (!ast_sip_get_disable_multi_domain()) {
       struct ast_sip_domain_alias *alias;
       struct ao2_container *transport_states;
       struct ast_sip_transport_state *transport_state = NULL;
       struct ast_sip_transport *transport = NULL;
       char id[DOMAIN_NAME_LEN + USERNAME_LEN + sizeof("@")];
       /* Attempt to find the endpoint given the name and domain provided */
       snprintf(id, sizeof(id), "%s@%s", endpoint_name, domain_name);
       endpoint = ast_sorcery_retrieve_by_id(ast_sip_get_sorcery(), "endpoint", id);
       if (endpoint) {
          return endpoint;
       }
       /* See if an alias exists for the domain provided */
       alias = ast_sorcery_retrieve_by_id(ast_sip_get_sorcery(), "domain_alias",
          domain_name);
       if (alias) {
          snprintf(id, sizeof(id), "%s@%s", endpoint_name, alias->domain);
          ao2_ref(alias, -1);
          endpoint = ast_sorcery_retrieve_by_id(ast_sip_get_sorcery(), "endpoint", id);
          if (endpoint) {
             return endpoint;
          }
       }
       /* See if the transport this came in on has a provided domain */
       if ((transport_states = ast_sip_get_transport_states())
          && (transport_state = ao2_callback(transport_states, 0, find_transport_state_in_use, rdata))
          && (transport = ast_sorcery_retrieve_by_id(ast_sip_get_sorcery(), "transport", transport_state->id))
          && !ast_strlen_zero(transport->domain)) {
          snprintf(id, sizeof(id), "%s@%s", endpoint_name, transport->domain);
          endpoint = ast_sorcery_retrieve_by_id(ast_sip_get_sorcery(), "endpoint", id);
       }
       ao2_cleanup(transport);
       ao2_cleanup(transport_state);
       ao2_cleanup(transport_states);
       if (endpoint) {
          return endpoint;
       }
    }
    /* Fall back to no domain */
    return ast_sorcery_retrieve_by_id(ast_sip_get_sorcery(), "endpoint", endpoint_name);
 }
find_transport_state_in_use()
static int find_transport_state_in_use (void * obj, void * arg, int flags) static
Definition at line 63 of file res_pjsip_endpoint_identifier_user.c.
References CMP_MATCH, ast_sip_transport_state::factory, and ast_sip_transport_state::transport.
Referenced by find_endpoint().
 {
    struct ast_sip_transport_state *transport_state = obj;
    pjsip_rx_data *rdata = arg;
    if (transport_state->transport == rdata->tp_info.transport
       || (transport_state->factory
          && !pj_strcmp(&transport_state->factory->addr_name.host, &rdata->tp_info.transport->local_name.host)
          && transport_state->factory->addr_name.port == rdata->tp_info.transport->local_name.port)) {
       return CMP_MATCH;
    }
    return 0;
 }
get_auth_header()
static pjsip_authorization_hdr* get_auth_header (pjsip_rx_data * rdata, char * username, size_t username_size, char * realm, size_t realm_size, pjsip_authorization_hdr * start) static
Definition at line 46 of file res_pjsip_endpoint_identifier_user.c.
References ast_copy_pj_str(), and NULL.
Referenced by auth_username_identify().
 {
    pjsip_authorization_hdr *header;
    header = pjsip_msg_find_hdr(rdata->msg_info.msg, PJSIP_H_AUTHORIZATION, start);
    if (!header || pj_stricmp2(&header->scheme, "digest")) {
       return NULL;
    }
    ast_copy_pj_str(username, &header->credential.digest.username, username_size);
    ast_copy_pj_str(realm, &header->credential.digest.realm, realm_size);
    return header;
 }
get_from_header()
static int get_from_header (pjsip_rx_data * rdata, char * username, size_t username_size, char * domain, size_t domain_size) static
Definition at line 32 of file res_pjsip_endpoint_identifier_user.c.
References ast_copy_pj_str().
Referenced by username_identify().
 {
    pjsip_uri *from = rdata->msg_info.from->uri;
    pjsip_sip_uri *sip_from;
    if (!PJSIP_URI_SCHEME_IS_SIP(from) && !PJSIP_URI_SCHEME_IS_SIPS(from)) {
       return -1;
    }
    sip_from = (pjsip_sip_uri *) pjsip_uri_get_uri(from);
    ast_copy_pj_str(username, &sip_from->user, username_size);
    ast_copy_pj_str(domain, &sip_from->host, domain_size);
    return 0;
 }
load_module()
static int load_module (void) static
Definition at line 207 of file res_pjsip_endpoint_identifier_user.c.
References AST_MODULE_LOAD_SUCCESS, and ast_sip_register_endpoint_identifier_with_name().
Referenced by unload_module().
 {
    ast_sip_register_endpoint_identifier_with_name(&username_identifier, "username");
    ast_sip_register_endpoint_identifier_with_name(&auth_username_identifier, "auth_username");
    return AST_MODULE_LOAD_SUCCESS;
 }
unload_module()
static int unload_module (void) static
Definition at line 214 of file res_pjsip_endpoint_identifier_user.c.
References AST_MODFLAG_LOAD_ORDER, AST_MODPRI_CHANNEL_DEPEND, AST_MODULE_INFO(), AST_MODULE_SUPPORT_CORE, ast_sip_unregister_endpoint_identifier(), ASTERISK_GPL_KEY, and load_module().
 {
    ast_sip_unregister_endpoint_identifier(&auth_username_identifier);
    ast_sip_unregister_endpoint_identifier(&username_identifier);
    return 0;
 }
username_identify()
static struct ast_sip_endpoint* username_identify (pjsip_rx_data * rdata) static
Definition at line 132 of file res_pjsip_endpoint_identifier_user.c.
References ao2_cleanup, ast_debug, AST_SIP_ENDPOINT_IDENTIFY_BY_USERNAME, AST_SIP_USER_OPTIONS_TRUNCATE_CHECK, DOMAIN_NAME_LEN, find_endpoint(), get_from_header(), ast_sip_endpoint::ident_method, NULL, and USERNAME_LEN.
 {
    char username[USERNAME_LEN + 1];
    char domain[DOMAIN_NAME_LEN + 1];
    struct ast_sip_endpoint *endpoint;
    if (get_from_header(rdata, username, sizeof(username), domain, sizeof(domain))) {
       return NULL;
    }
    /*
     * We may want to be matched without any user options getting
     * in the way.
     */
    AST_SIP_USER_OPTIONS_TRUNCATE_CHECK(username);
    ast_debug(3, "Attempting identify by From username '%s' domain '%s'\n", username, domain);
    endpoint = find_endpoint(rdata, username, domain);
    if (!endpoint) {
       ast_debug(3, "Endpoint not found for From username '%s' domain '%s'\n", username, domain);
       return NULL;
    }
    if (!(endpoint->ident_method & AST_SIP_ENDPOINT_IDENTIFY_BY_USERNAME)) {
       ast_debug(3, "Endpoint found for '%s' but 'username' method not supported'\n", username);
       ao2_cleanup(endpoint);
       return NULL;
    }
    ast_debug(3, "Identified by From username '%s' domain '%s'\n", username, domain);
    return endpoint;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "PJSIP username endpoint identifier" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_CHANNEL_DEPEND - 4, .requires = "res_pjsip", } static
Definition at line 227 of file res_pjsip_endpoint_identifier_user.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 227 of file res_pjsip_endpoint_identifier_user.c.
auth_username_identifier
struct ast_sip_endpoint_identifier auth_username_identifier static
Initial value:
= {
   .identify_endpoint = auth_username_identify,
}
Definition at line 202 of file res_pjsip_endpoint_identifier_user.c.
username_identifier
struct ast_sip_endpoint_identifier username_identifier static
Initial value:
= {
   .identify_endpoint = username_identify,
}
Definition at line 198 of file res_pjsip_endpoint_identifier_user.c.