Asterisk - The Open Source Telephony Project: cel_radius.c File Reference
cel_radius.c File Reference
RADIUS CEL Support.
#include "asterisk.h"
#include <radcli/radcli.h>
#include "asterisk/channel.h"
#include "asterisk/cel.h"
#include "asterisk/module.h"
#include "asterisk/logger.h"
#include "asterisk/utils.h"
#include "asterisk/options.h"
Macros
#define ADD_VENDOR_CODE(x, y) (rc_avpair_add(rh, send, x, (void *)y, strlen(y), VENDOR_CODE))
#define DATE_FORMAT "%Y-%m-%d %T %z"
#define RADIUS_BACKEND_NAME "CEL Radius Logging"
#define VENDOR_CODE 22736
Enumerations
enum {
PW_AST_ACCT_CODE = 101, PW_AST_CIDNUM = 102, PW_AST_CIDNAME = 103, PW_AST_CIDANI = 104,
PW_AST_CIDRDNIS = 105, PW_AST_CIDDNID = 106, PW_AST_EXTEN = 107, PW_AST_CONTEXT = 108,
PW_AST_CHANNAME = 109, PW_AST_APPNAME = 110, PW_AST_APPDATA = 111, PW_AST_EVENT_TIME = 112,
PW_AST_AMA_FLAGS = 113, PW_AST_UNIQUE_ID = 114, PW_AST_USER_NAME = 115, PW_AST_LINKED_ID = 116
}
enum { RADIUS_FLAG_USEGMTIME = (1 << 0), RADIUS_FLAG_LOGUNIQUEID = (1 << 1), RADIUS_FLAG_LOGUSERFIELD = (1 << 2) }
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int build_radius_record (VALUE_PAIR **send, struct ast_cel_event_record *record)
static int load_module (void)
static void radius_log (struct ast_event *event)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER, .description = "RADIUS CEL Backend", .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n", .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b", .support_level = AST_MODULE_SUPPORT_EXTENDED, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_CDR_DRIVER, .requires = "cel", }
static const struct ast_module_info * ast_module_info = &__mod_info
static char * cel_config = "cel.conf"
static struct ast_flags global_flags = { RADIUS_FLAG_USEGMTIME | RADIUS_FLAG_LOGUNIQUEID | RADIUS_FLAG_LOGUSERFIELD }
static char radiuscfg [PATH_MAX] = "/etc/radiusclient-ng/radiusclient.conf"
static rc_handle * rh = NULL
Detailed Description
RADIUS CEL Support.
Author
Philippe Sultan The Radius Client Library - http://developer.berlios.de/projects/radiusclient-ng/
See also AstCEL
Definition in file cel_radius.c.
Macro Definition Documentation
ADD_VENDOR_CODE
#define ADD_VENDOR_CODE (x, y) (rc_avpair_add(rh, send, x, (void *)y, strlen(y), VENDOR_CODE))
Definition at line 92 of file cel_radius.c.
Referenced by build_radius_record().
DATE_FORMAT
#define DATE_FORMAT "%Y-%m-%d %T %z"
ISO 8601 standard format
Definition at line 46 of file cel_radius.c.
Referenced by build_radius_record().
RADIUS_BACKEND_NAME
#define RADIUS_BACKEND_NAME "CEL Radius Logging"
Definition at line 90 of file cel_radius.c.
Referenced by load_module(), and unload_module().
VENDOR_CODE
#define VENDOR_CODE 22736
Definition at line 48 of file cel_radius.c.
Referenced by build_radius_record().
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PW_AST_ACCT_CODE
PW_AST_CIDNUM
PW_AST_CIDNAME
PW_AST_CIDANI
PW_AST_CIDRDNIS
PW_AST_CIDDNID
PW_AST_EXTEN
PW_AST_CONTEXT
PW_AST_CHANNAME
PW_AST_APPNAME
PW_AST_APPDATA
PW_AST_EVENT_TIME
PW_AST_AMA_FLAGS
PW_AST_UNIQUE_ID
PW_AST_USER_NAME
PW_AST_LINKED_ID
Definition at line 50 of file cel_radius.c.
      {
    PW_AST_ACCT_CODE =    101,
    PW_AST_CIDNUM =       102,
    PW_AST_CIDNAME =      103,
    PW_AST_CIDANI =       104,
    PW_AST_CIDRDNIS =     105,
    PW_AST_CIDDNID =      106,
    PW_AST_EXTEN =        107,
    PW_AST_CONTEXT =      108,
    PW_AST_CHANNAME =     109,
    PW_AST_APPNAME =      110,
    PW_AST_APPDATA =      111,
    PW_AST_EVENT_TIME =   112,
    PW_AST_AMA_FLAGS =    113,
    PW_AST_UNIQUE_ID =    114,
    PW_AST_USER_NAME =    115,
    PW_AST_LINKED_ID =    116,
 };
anonymous enum
anonymous enum
Enumerator
RADIUS_FLAG_USEGMTIME
Log dates and times in UTC
RADIUS_FLAG_LOGUNIQUEID
Log Unique ID
RADIUS_FLAG_LOGUSERFIELD
Log User Field
Definition at line 69 of file cel_radius.c.
      {
    /*! Log dates and times in UTC */
    RADIUS_FLAG_USEGMTIME = (1 << 0),
    /*! Log Unique ID */
    RADIUS_FLAG_LOGUNIQUEID = (1 << 1),
    /*! Log User Field */
    RADIUS_FLAG_LOGUSERFIELD = (1 << 2)
 };
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 263 of file cel_radius.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 263 of file cel_radius.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 263 of file cel_radius.c.
build_radius_record()
static int build_radius_record (VALUE_PAIR ** send, struct ast_cel_event_record * record) static
Definition at line 94 of file cel_radius.c.
References ast_cel_event_record::account_code, ADD_VENDOR_CODE, ast_cel_event_record::amaflag, amaflags, ast_cel_event_record::application_data, ast_cel_event_record::application_name, ast_channel_amaflags2string(), ast_localtime(), ast_strdupa, ast_strftime(), ast_test_flag, ast_cel_event_record::caller_id_ani, ast_cel_event_record::caller_id_dnid, ast_cel_event_record::caller_id_name, ast_cel_event_record::caller_id_num, ast_cel_event_record::caller_id_rdnis, ast_cel_event_record::channel_name, ast_cel_event_record::context, DATE_FORMAT, ast_cel_event_record::event_time, ast_cel_event_record::extension, ast_cel_event_record::linked_id, NULL, PW_AST_ACCT_CODE, PW_AST_AMA_FLAGS, PW_AST_APPDATA, PW_AST_APPNAME, PW_AST_CHANNAME, PW_AST_CIDANI, PW_AST_CIDDNID, PW_AST_CIDNAME, PW_AST_CIDNUM, PW_AST_CIDRDNIS, PW_AST_CONTEXT, PW_AST_EVENT_TIME, PW_AST_EXTEN, PW_AST_LINKED_ID, PW_AST_UNIQUE_ID, RADIUS_FLAG_LOGUNIQUEID, RADIUS_FLAG_USEGMTIME, ast_cel_event_record::unique_id, and VENDOR_CODE.
Referenced by radius_log().
 {
    int recordtype = PW_STATUS_STOP;
    struct ast_tm tm;
    char timestr[128];
    char *amaflags;
    if (!rc_avpair_add(rh, send, PW_ACCT_STATUS_TYPE, &recordtype, 0, 0)) {
       return -1;
    }
    /* Account code */
    if (!ADD_VENDOR_CODE(PW_AST_ACCT_CODE, record->account_code)) {
       return -1;
    }
    /* Source */
    if (!ADD_VENDOR_CODE(PW_AST_CIDNUM, record->caller_id_num)) {
       return -1;
    }
    /* Destination */
    if (!ADD_VENDOR_CODE(PW_AST_EXTEN, record->extension)) {
       return -1;
    }
    /* Destination context */
    if (!ADD_VENDOR_CODE(PW_AST_CONTEXT, record->context)) {
       return -1;
    }
    /* Caller ID */
    if (!ADD_VENDOR_CODE(PW_AST_CIDNAME, record->caller_id_name)) {
       return -1;
    }
    /* Caller ID ani */
    if (!ADD_VENDOR_CODE(PW_AST_CIDANI, record->caller_id_ani)) {
       return -1;
    }
    /* Caller ID rdnis */
    if (!ADD_VENDOR_CODE(PW_AST_CIDRDNIS, record->caller_id_rdnis)) {
       return -1;
    }
    /* Caller ID dnid */
    if (!ADD_VENDOR_CODE(PW_AST_CIDDNID, record->caller_id_dnid)) {
       return -1;
    }
    /* Channel */
    if (!ADD_VENDOR_CODE(PW_AST_CHANNAME, record->channel_name)) {
       return -1;
    }
    /* Last Application */
    if (!ADD_VENDOR_CODE(PW_AST_APPNAME, record->application_name)) {
       return -1;
    }
    /* Last Data */
    if (!ADD_VENDOR_CODE(PW_AST_APPDATA, record->application_data)) {
       return -1;
    }
    /* Event Time */
    ast_localtime(&record->event_time, &tm,
       ast_test_flag(&global_flags, RADIUS_FLAG_USEGMTIME) ? "GMT" : NULL);
    ast_strftime(timestr, sizeof(timestr), DATE_FORMAT, &tm);
    if (!rc_avpair_add(rh, send, PW_AST_EVENT_TIME, timestr, strlen(timestr), VENDOR_CODE)) {
       return -1;
    }
    /* AMA Flags */
    amaflags = ast_strdupa(ast_channel_amaflags2string(record->amaflag));
    if (!rc_avpair_add(rh, send, PW_AST_AMA_FLAGS, amaflags, strlen(amaflags), VENDOR_CODE)) {
       return -1;
    }
    if (ast_test_flag(&global_flags, RADIUS_FLAG_LOGUNIQUEID)) {
       /* Unique ID */
       if (!ADD_VENDOR_CODE(PW_AST_UNIQUE_ID, record->unique_id)) {
          return -1;
       }
    }
    /* LinkedID */
    if (!ADD_VENDOR_CODE(PW_AST_LINKED_ID, record->linked_id)) {
       return -1;
    }
    /* Setting Acct-Session-Id & User-Name attributes for proper generation
       of Acct-Unique-Session-Id on server side */
    /* Channel */
    if (!rc_avpair_add(rh, send, PW_USER_NAME, (void *)record->channel_name,
          strlen(record->channel_name), 0)) {
       return -1;
    }
    return 0;
 }
load_module()
static int load_module (void) static
Definition at line 218 of file cel_radius.c.
References ast_cel_backend_register(), ast_config_destroy(), ast_config_load, ast_copy_string(), ast_log, AST_MODFLAG_LOAD_ORDER, AST_MODPRI_CDR_DRIVER, AST_MODULE_INFO(), AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, AST_MODULE_SUPPORT_EXTENDED, ast_set2_flag, ast_true(), ast_variable_retrieve(), ASTERISK_GPL_KEY, LOG_NOTICE, NULL, RADIUS_BACKEND_NAME, RADIUS_FLAG_USEGMTIME, radius_log(), tmp(), and unload_module().
 {
    struct ast_config *cfg;
    struct ast_flags config_flags = { 0 };
    const char *tmp;
    if ((cfg = ast_config_load(cel_config, config_flags))) {
       ast_set2_flag(&global_flags, ast_true(ast_variable_retrieve(cfg, "radius", "usegmtime")), RADIUS_FLAG_USEGMTIME);
       if ((tmp = ast_variable_retrieve(cfg, "radius", "radiuscfg"))) {
          ast_copy_string(radiuscfg, tmp, sizeof(radiuscfg));
       }
       ast_config_destroy(cfg);
    } else {
       return AST_MODULE_LOAD_DECLINE;
    }
    /* read radiusclient-ng config file */
    if (!(rh = rc_read_config(radiuscfg))) {
       ast_log(LOG_NOTICE, "Cannot load radiusclient-ng configuration file %s.\n", radiuscfg);
       return AST_MODULE_LOAD_DECLINE;
    }
    /* read radiusclient-ng dictionaries */
    if (rc_read_dictionary(rh, rc_conf_str(rh, "dictionary"))) {
       ast_log(LOG_NOTICE, "Cannot load radiusclient-ng dictionary file.\n");
       rc_destroy(rh);
       rh = NULL;
       return AST_MODULE_LOAD_DECLINE;
    }
    if (ast_cel_backend_register(RADIUS_BACKEND_NAME, radius_log)) {
       rc_destroy(rh);
       rh = NULL;
       return AST_MODULE_LOAD_DECLINE;
    } else {
       return AST_MODULE_LOAD_SUCCESS;
    }
 }
radius_log()
static void radius_log (struct ast_event * event) static
Definition at line 180 of file cel_radius.c.
References AST_CEL_EVENT_RECORD_VERSION, ast_cel_fill_record(), ast_debug, ast_log, build_radius_record(), LOG_ERROR, NULL, result, and ast_cel_event_record::version.
Referenced by load_module().
 {
    int result = ERROR_RC;
    VALUE_PAIR *send = NULL;
    struct ast_cel_event_record record = {
       .version = AST_CEL_EVENT_RECORD_VERSION,
    };
    if (ast_cel_fill_record(event, &record)) {
       return;
    }
    if (build_radius_record(&send, &record)) {
       ast_debug(1, "Unable to create RADIUS record. CEL not recorded!\n");
       goto return_cleanup;
    }
    result = rc_acct(rh, 0, send);
    if (result != OK_RC) {
       ast_log(LOG_ERROR, "Failed to record Radius CEL record!\n");
    }
 return_cleanup:
    if (send) {
       rc_avpair_free(send);
    }
 }
unload_module()
static int unload_module (void) static
Definition at line 208 of file cel_radius.c.
References ast_cel_backend_unregister(), AST_MODULE_LOAD_SUCCESS, NULL, and RADIUS_BACKEND_NAME.
Referenced by load_module().
 {
    ast_cel_backend_unregister(RADIUS_BACKEND_NAME);
    if (rh) {
       rc_destroy(rh);
       rh = NULL;
    }
    return AST_MODULE_LOAD_SUCCESS;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER, .description = "RADIUS CEL Backend", .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n", .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b", .support_level = AST_MODULE_SUPPORT_EXTENDED, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_CDR_DRIVER, .requires = "cel", } static
Definition at line 263 of file cel_radius.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 263 of file cel_radius.c.
cel_config
char* cel_config = "cel.conf" static
Definition at line 78 of file cel_radius.c.
global_flags
struct ast_flags global_flags = { RADIUS_FLAG_USEGMTIME | RADIUS_FLAG_LOGUNIQUEID | RADIUS_FLAG_LOGUSERFIELD } static
Definition at line 86 of file cel_radius.c.
radiuscfg
char radiuscfg[PATH_MAX] = "/etc/radiusclient-ng/radiusclient.conf" static
Definition at line 83 of file cel_radius.c.
rh
rc_handle* rh = NULL static
Definition at line 88 of file cel_radius.c.