Asterisk - The Open Source Telephony Project: channels.c File Reference
channels.c File Reference
Prometheus Channel Metrics.
#include "asterisk.h"
#include "asterisk/res_prometheus.h"
#include "asterisk/stasis_channels.h"
#include "asterisk/pbx.h"
#include "prometheus_internal.h"
Data Structures
struct channel_metric_defs
Macros
#define CHANNELS_DURATION_HELP "Individual channel durations (in seconds)."
#define CHANNELS_STATE_HELP "Individual channel states. 0=down; 1=reserved; 2=offhook; 3=dialing; 4=ring; 5=ringing; 6=up; 7=busy; 8=dialing_offhook; 9=prering."
Functions
int channel_metrics_init (void)
Initialize channel metrics.
static void channel_metrics_unload_cb (void)
static void channels_scrape_cb (struct ast_str **response)
static void get_channel_duration (struct prometheus_metric *metric, struct ast_channel_snapshot *snapshot)
static void get_channel_state (struct prometheus_metric *metric, struct ast_channel_snapshot *snapshot)
static void get_current_call_count (struct prometheus_metric *metric)
static void get_total_call_count (struct prometheus_metric *metric)
Variables
struct channel_metric_defs channel_metric_defs []
struct prometheus_callback channels_callback
static struct prometheus_metric global_channel_metrics []
static struct prometheus_metrics_provider provider
Detailed Description
Prometheus Channel Metrics.
Author
Matt Jordan mjord.nosp@m.an@d.nosp@m.igium.nosp@m..com
Definition in file channels.c.
Macro Definition Documentation
CHANNELS_DURATION_HELP
#define CHANNELS_DURATION_HELP "Individual channel durations (in seconds)."
Definition at line 36 of file channels.c.
CHANNELS_STATE_HELP
#define CHANNELS_STATE_HELP "Individual channel states. 0=down; 1=reserved; 2=offhook; 3=dialing; 4=ring; 5=ringing; 6=up; 7=busy; 8=dialing_offhook; 9=prering."
Definition at line 34 of file channels.c.
Function Documentation
channel_metrics_init()
int channel_metrics_init (void)
Initialize channel metrics.
Return values
0 success
-1 error
Definition at line 241 of file channels.c.
References prometheus_callback_register(), and prometheus_metrics_provider_register().
Referenced by load_module().
 {
    prometheus_metrics_provider_register(&provider);
    prometheus_callback_register(&channels_callback);
    return 0;
 }
channel_metrics_unload_cb()
static void channel_metrics_unload_cb (void) static
Definition at line 227 of file channels.c.
References prometheus_callback_unregister().
 {
    prometheus_callback_unregister(&channels_callback);
 }
channels_scrape_cb()
static void channels_scrape_cb (struct ast_str ** response) static
Definition at line 130 of file channels.c.
References ao2_container_clone, ao2_container_count(), ao2_iterator_destroy(), ao2_iterator_init(), ao2_iterator_next, ao2_ref, ARRAY_LEN, ast_calloc, ast_channel_cache_all(), ast_copy_string(), ast_eid_default, ast_eid_to_str(), ast_free, AST_LIST_INSERT_TAIL, ast_channel_snapshot::base, channel_cache, channels, prometheus_metric::children, prometheus_metric::get_metric_value, channel_metric_defs::get_value, channel_metric_defs::help, prometheus_metric::help, ast_channel_snapshot_peer::linkedid, channel_metric_defs::name, ast_channel_snapshot_base::name, NULL, ast_channel_snapshot::peer, PROMETHEUS_METRIC_GAUGE, PROMETHEUS_METRIC_SET_LABEL, PROMETHEUS_METRIC_STATIC_INITIALIZATION, prometheus_metric_to_string(), ast_channel_snapshot_base::type, prometheus_metric::type, ast_channel_snapshot_base::uniqueid, and prometheus_metric::value.
 {
    struct ao2_container *channel_cache;
    struct ao2_container *channels;
    struct ao2_iterator it_chans;
    struct ast_channel_snapshot *snapshot;
    struct prometheus_metric *channel_metrics;
    char eid_str[32];
    int num_channels;
    int i, j;
    struct prometheus_metric channel_count = PROMETHEUS_METRIC_STATIC_INITIALIZATION(
       PROMETHEUS_METRIC_GAUGE,
       "asterisk_channels_count",
       "Current channel count.",
       NULL
    );
    ast_eid_to_str(eid_str, sizeof(eid_str), &ast_eid_default);
    channel_cache = ast_channel_cache_all();
    if (!channel_cache) {
       return;
    }
    channels = ao2_container_clone(channel_cache, 0);
    ao2_ref(channel_cache, -1);
    if (!channels) {
       return;
    }
    num_channels = ao2_container_count(channels);
    /* Channel count */
    PROMETHEUS_METRIC_SET_LABEL(&channel_count, 0, "eid", eid_str);
    snprintf(channel_count.value, sizeof(channel_count.value), "%d", num_channels);
    prometheus_metric_to_string(&channel_count, response);
    /* Global call values */
    for (i = 0; i < ARRAY_LEN(global_channel_metrics); i++) {
       PROMETHEUS_METRIC_SET_LABEL(&global_channel_metrics[i], 0, "eid", eid_str);
       global_channel_metrics[i].get_metric_value(&global_channel_metrics[i]);
       prometheus_metric_to_string(&global_channel_metrics[i], response);
    }
    if (num_channels == 0) {
       ao2_ref(channels, -1);
       return;
    }
    /* Channel dependent values */
    channel_metrics = ast_calloc(ARRAY_LEN(channel_metric_defs) * num_channels, sizeof(*channel_metrics));
    if (!channel_metrics) {
       ao2_ref(channels, -1);
       return;
    }
    it_chans = ao2_iterator_init(channels, 0);
    for (i = 0; (snapshot = ao2_iterator_next(&it_chans)); ao2_ref(snapshot, -1), i++) {
       for (j = 0; j < ARRAY_LEN(channel_metric_defs); j++) {
          int index = i * ARRAY_LEN(channel_metric_defs) + j;
          channel_metrics[index].type = PROMETHEUS_METRIC_GAUGE;
          ast_copy_string(channel_metrics[index].name, channel_metric_defs[j].name, sizeof(channel_metrics[index].name));
          channel_metrics[index].help = channel_metric_defs[j].help;
          PROMETHEUS_METRIC_SET_LABEL(&channel_metrics[index], 0, "eid", eid_str);
          PROMETHEUS_METRIC_SET_LABEL(&channel_metrics[index], 1, "name", (snapshot->base->name));
          PROMETHEUS_METRIC_SET_LABEL(&channel_metrics[index], 2, "id", (snapshot->base->uniqueid));
          PROMETHEUS_METRIC_SET_LABEL(&channel_metrics[index], 3, "type", (snapshot->base->type));
          if (snapshot->peer) {
             PROMETHEUS_METRIC_SET_LABEL(&channel_metrics[index], 4, "linkedid", (snapshot->peer->linkedid));
          }
          channel_metric_defs[j].get_value(&channel_metrics[index], snapshot);
          if (i > 0) {
             AST_LIST_INSERT_TAIL(&channel_metrics[j].children, &channel_metrics[index], entry);
          }
       }
    }
    ao2_iterator_destroy(&it_chans);
    for (j = 0; j < ARRAY_LEN(channel_metric_defs); j++) {
       prometheus_metric_to_string(&channel_metrics[j], response);
    }
    ast_free(channel_metrics);
    ao2_ref(channels, -1);
 }
get_channel_duration()
static void get_channel_duration (struct prometheus_metric * metric, struct ast_channel_snapshot * snapshot) static
Definition at line 57 of file channels.c.
References ast_tvdiff_sec(), ast_tvnow(), ast_channel_snapshot::base, ast_channel_snapshot_base::creationtime, and prometheus_metric::value.
 {
    struct timeval now = ast_tvnow();
    int64_t duration = ast_tvdiff_sec(now, snapshot->base->creationtime);
    snprintf(metric->value, sizeof(metric->value), "%" PRIu64, duration);
 }
get_channel_state()
static void get_channel_state (struct prometheus_metric * metric, struct ast_channel_snapshot * snapshot) static
Definition at line 45 of file channels.c.
References ast_channel_snapshot::state, and prometheus_metric::value.
 {
    snprintf(metric->value, sizeof(metric->value), "%d", snapshot->state);
 }
get_current_call_count()
static void get_current_call_count (struct prometheus_metric * metric) static
Definition at line 100 of file channels.c.
References ast_active_calls(), and prometheus_metric::value.
 {
    snprintf(metric->value, sizeof(metric->value), "%d", ast_active_calls());
 }
get_total_call_count()
static void get_total_call_count (struct prometheus_metric * metric) static
Definition at line 95 of file channels.c.
References ast_processed_calls(), and prometheus_metric::value.
 {
    snprintf(metric->value, sizeof(metric->value), "%d", ast_processed_calls());
 }
Variable Documentation
channel_metric_defs
struct channel_metric_defs channel_metric_defs[]
channels_callback
struct prometheus_callback channels_callback
Initial value:
= {
   .name = "Channels callback",
   .callback_fn = channels_scrape_cb,
}
Definition at line 218 of file channels.c.
global_channel_metrics
struct prometheus_metric global_channel_metrics[] static
Definition at line 109 of file channels.c.
provider
struct prometheus_metrics_provider provider static
Initial value:
= {
   .name = "channels",
   .unload_cb = channel_metrics_unload_cb,
}
Definition at line 236 of file channels.c.