Asterisk - The Open Source Telephony Project: features_config.h File Reference
main/features_config.h File Reference
Functions
int load_features_config (void)
int reload_features_config (void)
void unload_features_config (void)
Function Documentation
load_features_config()
int load_features_config (void)
Definition at line 1996 of file features_config.c.
References __ast_custom_function_register(), ARRAY_LEN, ast_cli_register_multiple, load_config(), and NULL.
Referenced by load_module().
 {
    int res;
    res = load_config();
    res |= __ast_custom_function_register(&feature_function, NULL);
    res |= __ast_custom_function_register(&featuremap_function, NULL);
    res |= ast_cli_register_multiple(cli_features_config, ARRAY_LEN(cli_features_config));
    return res;
 }
reload_features_config()
int reload_features_config (void)
Definition at line 1985 of file features_config.c.
References aco_process_config(), ACO_PROCESS_ERROR, and parking_warning.
Referenced by load_module().
 {
    /* Rearm the parking config options have moved warning. */
    parking_warning = 0;
    if (aco_process_config(&cfg_info, 1) == ACO_PROCESS_ERROR) {
       return -1;
    }
    return 0;
 }
unload_features_config()
void unload_features_config (void)
Definition at line 1976 of file features_config.c.
References aco_info_destroy(), ao2_global_obj_release, ARRAY_LEN, ast_cli_unregister_multiple(), ast_custom_function_unregister(), and globals.
Referenced by unload_module().
 {
    ast_custom_function_unregister(&featuremap_function);
    ast_custom_function_unregister(&feature_function);
    ast_cli_unregister_multiple(cli_features_config, ARRAY_LEN(cli_features_config));
    aco_info_destroy(&cfg_info);
    ao2_global_obj_release(globals);
 }