Asterisk - The Open Source Telephony Project: res_pjsip.h File Reference
res_pjsip.h File Reference
#include <pjsip.h>
#include <pjsip_simple.h>
#include <pjsip/sip_transaction.h>
#include <pj/timer.h>
#include <pjlib.h>
#include "asterisk/stringfields.h"
#include "asterisk/netsock2.h"
#include "asterisk/linkedlists.h"
#include "asterisk/channel.h"
#include "asterisk/sorcery.h"
#include "asterisk/dnsmgr.h"
#include "asterisk/endpoints.h"
#include "asterisk/udptl.h"
#include "asterisk/rtp_engine.h"
#include "asterisk/vector.h"
#include "asterisk/stasis_channels.h"
#include "asterisk/stasis_endpoints.h"
#include "asterisk/stream.h"
Data Structures
struct ast_sip_ami
AMI variable container.
struct ast_sip_aor
A SIP address of record.
struct ast_sip_auth
struct ast_sip_auth_vector
struct ast_sip_authenticator
An interchangeable way of handling digest authentication for SIP.
struct ast_sip_body
SIP body description.
struct ast_sip_contact
Contact associated with an address of record.
struct ast_sip_contact_status
A contact's status.
struct ast_sip_contact_wrapper
A wrapper for contact that adds the aor_id and a consistent contact id. Used by ast_sip_for_each_contact.
struct ast_sip_direct_media_configuration
Direct media options for SIP endpoints.
struct ast_sip_domain_alias
struct ast_sip_endpoint
An entity with which Asterisk communicates.
struct ast_sip_endpoint_extensions
Endpoint configuration for SIP extensions.
struct ast_sip_endpoint_formatter
An entity responsible formatting endpoint information.
struct ast_sip_endpoint_id_configuration
Party identification options for endpoints.
struct ast_sip_endpoint_identifier
An entity responsible for identifying the source of a SIP message.
struct ast_sip_endpoint_info_configuration
Endpoint configuration options for INFO packages.
struct ast_sip_endpoint_media_configuration
Media configuration for SIP endpoints.
struct ast_sip_endpoint_nat_configuration
NAT configuration options for endpoints.
struct ast_sip_endpoint_pickup_configuration
Call pickup configuration options for endpoints.
struct ast_sip_endpoint_subscription_configuration
Endpoint subscription configuration.
struct ast_sip_identify_by_vector
struct ast_sip_info_recording_configuration
Configuration for one-touch INFO recording.
struct ast_sip_media_rtp_configuration
RTP configuration for SIP endpoints.
struct ast_sip_mwi_configuration
Endpoint configuration for unsolicited MWI.
struct ast_sip_nat_hook
Structure for SIP nat hook information.
struct ast_sip_outbound_authenticator
an interchangeable way of responding to authentication challenges
struct ast_sip_supplement
A supplement to SIP message processing.
struct ast_sip_t38_configuration
struct ast_sip_timer_options
Session timers options.
struct ast_sip_tpmgr_state_callback
struct ast_sip_transport
Transport to bind to.
struct ast_sip_transport_state
Structure for SIP transport information.
Macros
#define ast_sip_cleanup_auth_objects_vector(auth_objects) AST_VECTOR_RESET(auth_objects, ao2_cleanup)
Clean up retrieved auth objects in vector.
#define ast_sip_mod_data_get(mod_data, id, key) ast_sip_dict_get(mod_data[id], key)
Using the dictionary stored in mod_data array at a given id, retrieve the value associated with the given key.
#define ast_sip_mod_data_set(pool, mod_data, id, key, val) mod_data[id] = ast_sip_dict_set(pool, mod_data[id], key, val)
Utilizing a mod_data array for a given id, set the value associated with the given key.
#define ast_sip_transport_is_local(transport_state, addr) (transport_state->localnet && ast_apply_ha(transport_state->localnet, addr) != AST_SENSE_ALLOW)
#define ast_sip_transport_is_nonlocal(transport_state, addr) (!transport_state->localnet || ast_apply_ha(transport_state->localnet, addr) == AST_SENSE_ALLOW)
#define AST_SIP_USER_OPTIONS_TRUNCATE_CHECK(str)
Truncate the URI user field options string if enabled.
#define AST_SIP_X_AST_TXP "x-ast-txp"
#define AST_SIP_X_AST_TXP_LEN 9
#define MAX_RX_CHALLENGES 10
#define PJSIP_EXPIRES_NOT_SPECIFIED ((pj_uint32_t)-1)
#define PJSIP_MINVERSION(m, n, p) (((m << 24) | (n << 16) | (p << 8)) >= PJ_VERSION_NUM)
#define SIP_SORCERY_DOMAIN_ALIAS_TYPE "domain_alias"
#define SIP_TLS_MAX_CIPHERS 64
Maximum number of ciphers supported for a TLS transport.
Typedefs
typedef int(* ast_sip_dialog_outbound_auth_cb) (pjsip_dialog *dlg, pjsip_tx_data *tdata, void *user_data)
Callback called when an outbound request with authentication credentials is to be sent in dialog.
typedef int(* ast_sip_task) (void *user_data)
typedef int(* ast_transport_monitor_data_matcher) (void *a, void *b)
Transport shutdown monitor data matcher.
typedef void(* ast_transport_monitor_shutdown_cb) (void *data)
Transport shutdown monitor callback.
Enumerations
enum ast_sip_auth_type { AST_SIP_AUTH_TYPE_USER_PASS, AST_SIP_AUTH_TYPE_MD5, AST_SIP_AUTH_TYPE_GOOGLE_OAUTH, AST_SIP_AUTH_TYPE_ARTIFICIAL }
Methods of storing SIP digest authentication credentials.
enum ast_sip_call_codec_pref {
AST_SIP_CALL_CODEC_PREF_INTERSECT = 1 << 0, AST_SIP_CALL_CODEC_PREF_UNION = 1 << 1, AST_SIP_CALL_CODEC_PREF_ALL = 1 << 2, AST_SIP_CALL_CODEC_PREF_FIRST = 1 << 3,
AST_SIP_CALL_CODEC_PREF_LOCAL = 1 << 4, AST_SIP_CALL_CODEC_PREF_REMOTE = 1 << 5
}
Incoming/Outgoing call offer/answer joint codec preference.
enum ast_sip_check_auth_result { AST_SIP_AUTHENTICATION_CHALLENGE, AST_SIP_AUTHENTICATION_SUCCESS, AST_SIP_AUTHENTICATION_FAILED, AST_SIP_AUTHENTICATION_ERROR }
Possible returns from ast_sip_check_authentication.
enum ast_sip_contact_filter { AST_SIP_CONTACT_FILTER_DEFAULT = 0, AST_SIP_CONTACT_FILTER_REACHABLE = (1 << 0) }
Contact retrieval filtering flags.
enum ast_sip_contact_status_type {
UNAVAILABLE, AVAILABLE, UNKNOWN, CREATED,
REMOVED
}
Status type for a contact.
enum ast_sip_direct_media_glare_mitigation { AST_SIP_DIRECT_MEDIA_GLARE_MITIGATION_NONE, AST_SIP_DIRECT_MEDIA_GLARE_MITIGATION_OUTGOING, AST_SIP_DIRECT_MEDIA_GLARE_MITIGATION_INCOMING }
enum ast_sip_dtmf_mode {
AST_SIP_DTMF_NONE, AST_SIP_DTMF_RFC_4733, AST_SIP_DTMF_INBAND, AST_SIP_DTMF_INFO,
AST_SIP_DTMF_AUTO, AST_SIP_DTMF_AUTO_INFO
}
DTMF modes for SIP endpoints.
enum ast_sip_endpoint_identifier_type { AST_SIP_ENDPOINT_IDENTIFY_BY_USERNAME = (1 << 0), AST_SIP_ENDPOINT_IDENTIFY_BY_AUTH_USERNAME = (1 << 1), AST_SIP_ENDPOINT_IDENTIFY_BY_IP = (1 << 2), AST_SIP_ENDPOINT_IDENTIFY_BY_HEADER = (1 << 3) }
Different methods by which incoming requests can be matched to endpoints.
enum ast_sip_scheduler_task_flags {
AST_SIP_SCHED_TASK_DEFAULTS = (0 << 0), AST_SIP_SCHED_TASK_FIXED = (0 << 0), AST_SIP_SCHED_TASK_VARIABLE = (1 << 0), AST_SIP_SCHED_TASK_ONESHOT = (1 << 6),
AST_SIP_SCHED_TASK_DATA_NOT_AO2 = (0 << 1), AST_SIP_SCHED_TASK_DATA_AO2 = (1 << 1), AST_SIP_SCHED_TASK_DATA_NO_CLEANUP = (0 << 3), AST_SIP_SCHED_TASK_DATA_FREE = (1 << 3),
AST_SIP_SCHED_TASK_PERIODIC = (0 << 4), AST_SIP_SCHED_TASK_DELAY = (1 << 4), AST_SIP_SCHED_TASK_TRACK = (1 << 5)
}
Task flags for the res_pjsip scheduler.
enum ast_sip_session_media_encryption { AST_SIP_MEDIA_TRANSPORT_INVALID = 0, AST_SIP_MEDIA_ENCRYPT_NONE, AST_SIP_MEDIA_ENCRYPT_SDES, AST_SIP_MEDIA_ENCRYPT_DTLS }
enum ast_sip_session_redirect { AST_SIP_REDIRECT_USER = 0, AST_SIP_REDIRECT_URI_CORE, AST_SIP_REDIRECT_URI_PJSIP }
enum ast_sip_session_refresh_method { AST_SIP_SESSION_REFRESH_METHOD_INVITE, AST_SIP_SESSION_REFRESH_METHOD_UPDATE }
enum ast_sip_supplement_priority { AST_SIP_SUPPLEMENT_PRIORITY_FIRST = 0, AST_SIP_SUPPLEMENT_PRIORITY_CHANNEL = 1000000, AST_SIP_SUPPLEMENT_PRIORITY_LAST = INT_MAX }
enum ast_transport_monitor_reg { AST_TRANSPORT_MONITOR_REG_SUCCESS, AST_TRANSPORT_MONITOR_REG_REPLACED, AST_TRANSPORT_MONITOR_REG_NOT_FOUND, AST_TRANSPORT_MONITOR_REG_FAILED }
Functions
void ast_copy_pj_str (char *dest, const pj_str_t *src, size_t size)
Copy a pj_str_t into a standard character buffer.
int ast_copy_pj_str2 (char **dest, const pj_str_t *src)
Create and copy a pj_str_t into a standard character buffer.
struct ast_sip_endpoint * ast_pjsip_rdata_get_endpoint (pjsip_rx_data *rdata)
Get the looked-up endpoint on an out-of dialog request or response.
int ast_sip_add_body (pjsip_tx_data *tdata, const struct ast_sip_body *body)
Add a body to an outbound SIP message.
int ast_sip_add_body_multipart (pjsip_tx_data *tdata, const struct ast_sip_body *bodies[], int num_bodies)
Add a multipart body to an outbound SIP message.
void ast_sip_add_date_header (pjsip_tx_data *tdata)
Adds a Date header to the tdata, formatted like: Date: Wed, 01 Jan 2021 14:53:01 GMT.
int ast_sip_add_global_request_header (const char *name, const char *value, int replace)
int ast_sip_add_global_response_header (const char *name, const char *value, int replace)
int ast_sip_add_header (pjsip_tx_data *tdata, const char *name, const char *value)
Add a header to an outbound SIP message.
void ast_sip_add_usereqphone (const struct ast_sip_endpoint *endpoint, pj_pool_t *pool, pjsip_uri *uri)
Add 'user=phone' parameter to URI if enabled and user is a phone number.
int ast_sip_append_body (pjsip_tx_data *tdata, const char *body_text)
Append body data to a SIP message.
const char * ast_sip_auth_type_to_str (enum ast_sip_auth_type type)
Converts the given auth type to a string.
void ast_sip_auth_vector_destroy (struct ast_sip_auth_vector *vector)
Free contents of an auth vector.
int ast_sip_auth_vector_init (struct ast_sip_auth_vector *vector, const char *auth_names)
Initialize an auth vector with the configured values.
int ast_sip_auths_to_str (const struct ast_sip_auth_vector *auths, char **buf)
Converts an auths array to a string of comma separated values.
const char * ast_sip_call_codec_pref_to_str (struct ast_flags pref)
Convert the call codec preference flags to a string.
int ast_sip_call_codec_str_to_pref (struct ast_flags *pref, const char *pref_str, int is_outgoing)
Convert a call codec preference string to preference flags.
enum ast_sip_check_auth_result ast_sip_check_authentication (struct ast_sip_endpoint *endpoint, pjsip_rx_data *rdata, pjsip_tx_data *tdata)
Method to determine authentication status of an incoming request.
void ast_sip_cleanup_auths (struct ast_sip_auth *auths[], size_t num_auths)
Clean up retrieved auth structures from memory.
int ast_sip_contact_to_str (void *object, void *arg, int flags)
Handler used to convert a contact to a string.
struct ast_str * ast_sip_create_ami_event (const char *event, struct ast_sip_ami *ami)
Creates a string to store AMI event data in.
pjsip_dialog * ast_sip_create_dialog_uac (const struct ast_sip_endpoint *endpoint, const char *aor_name, const char *request_user)
General purpose method for creating a UAC dialog with an endpoint.
pjsip_dialog * ast_sip_create_dialog_uas (const struct ast_sip_endpoint *endpoint, pjsip_rx_data *rdata, pj_status_t *status)
General purpose method for creating a UAS dialog with an endpoint.
pjsip_dialog * ast_sip_create_dialog_uas_locked (const struct ast_sip_endpoint *endpoint, pjsip_rx_data *rdata, pj_status_t *status)
General purpose method for creating a UAS dialog with an endpoint.
int ast_sip_create_rdata (pjsip_rx_data *rdata, char *packet, const char *src_name, int src_port, char *transport_type, const char *local_name, int local_port)
General purpose method for creating an rdata structure using specific information.
int ast_sip_create_rdata_with_contact (pjsip_rx_data *rdata, char *packet, const char *src_name, int src_port, char *transport_type, const char *local_name, int local_port, const char *contact_uri)
General purpose method for creating an rdata structure using specific information.
int ast_sip_create_request (const char *method, struct pjsip_dialog *dlg, struct ast_sip_endpoint *endpoint, const char *uri, struct ast_sip_contact *contact, pjsip_tx_data **tdata)
General purpose method for creating a SIP request.
int ast_sip_create_request_with_auth (const struct ast_sip_auth_vector *auths, pjsip_rx_data *challenge, pjsip_tx_data *tdata, pjsip_tx_data **new_request)
Create a response to an authentication challenge.
int ast_sip_create_response (const pjsip_rx_data *rdata, int st_code, struct ast_sip_contact *contact, pjsip_tx_data **p_tdata)
General purpose method for creating a SIP response.
struct ast_taskprocessor * ast_sip_create_serializer (const char *name)
Create a new serializer for SIP tasks.
struct ast_taskprocessor * ast_sip_create_serializer_group (const char *name, struct ast_serializer_shutdown_group *shutdown_group)
Create a new serializer for SIP tasks.
struct ast_sip_endpoint * ast_sip_default_outbound_endpoint (void)
Retrieve the default outbound endpoint.
struct ast_sip_endpoint * ast_sip_dialog_get_endpoint (pjsip_dialog *dlg)
Get the endpoint associated with this dialog.
void ast_sip_dialog_set_endpoint (pjsip_dialog *dlg, struct ast_sip_endpoint *endpoint)
Set an endpoint on a SIP dialog so in-dialog requests do not undergo endpoint lookup.
void ast_sip_dialog_set_serializer (pjsip_dialog *dlg, struct ast_taskprocessor *serializer)
Set a serializer on a SIP dialog so requests and responses are automatically serialized.
int ast_sip_dialog_setup_outbound_authentication (pjsip_dialog *dlg, const struct ast_sip_endpoint *endpoint, ast_sip_dialog_outbound_auth_cb cb, void *user_data)
Set up outbound authentication on a SIP dialog.
void * ast_sip_dict_get (void *ht, const char *key)
Retrieves the value associated with the given key.
void * ast_sip_dict_set (pj_pool_t *pool, void *ht, const char *key, void *val)
Set the value for the given key.
int ast_sip_dlg_set_transport (const struct ast_sip_endpoint *endpoint, pjsip_dialog *dlg, pjsip_tpselector *selector)
Set the transport on a dialog.
int ast_sip_dtmf_to_str (const enum ast_sip_dtmf_mode dtmf, char *buf, size_t buf_len)
Convert the DTMF mode enum value into a string.
void * ast_sip_endpoint_alloc (const char *name)
Allocate a new SIP endpoint.
int ast_sip_failover_request (pjsip_tx_data *tdata)
Set a request to use the next value in the list of resolved addresses.
int ast_sip_for_each_aor (const char *aors, ao2_callback_fn on_aor, void *arg)
For every aor in the comma separated aors string call the given 'on_aor' handler.
int ast_sip_for_each_auth (const struct ast_sip_auth_vector *array, ao2_callback_fn on_auth, void *arg)
For every auth in the array call the given 'on_auth' handler.
int ast_sip_for_each_channel (const struct ast_sip_endpoint *endpoint, ao2_callback_fn on_channel_snapshot, void *arg)
For every channel snapshot on an endpoint all the given 'on_channel_snapshot' handler.
int ast_sip_for_each_channel_snapshot (const struct ast_endpoint_snapshot *endpoint_snapshot, ao2_callback_fn on_channel_snapshot, void *arg)
For every channel snapshot on an endpoint snapshot call the given 'on_channel_snapshot' handler.
int ast_sip_for_each_contact (const struct ast_sip_aor *aor, ao2_callback_fn on_contact, void *arg)
For every contact on an AOR call the given 'on_contact' handler.
int ast_sip_format_auths_ami (const struct ast_sip_auth_vector *auths, struct ast_sip_ami *ami)
Format auth details for AMI.
int ast_sip_format_contact_ami (void *obj, void *arg, int flags)
Formats the contact and sends over AMI.
int ast_sip_format_endpoint_ami (struct ast_sip_endpoint *endpoint, struct ast_sip_ami *ami, int *count)
Formats the endpoint and sends over AMI.
struct ast_sip_auth * ast_sip_get_artificial_auth (void)
Retrieves a reference to the artificial auth.
struct ast_sip_endpoint * ast_sip_get_artificial_endpoint (void)
Retrieves a reference to the artificial endpoint.
unsigned int ast_sip_get_contact_expiration_check_interval (void)
Retrieve the system contact expiration check interval setting.
const char * ast_sip_get_contact_short_status_label (const enum ast_sip_contact_status_type status)
struct ast_sip_contact_status * ast_sip_get_contact_status (const struct ast_sip_contact *contact)
Retrieve the current status for a contact.
const char * ast_sip_get_contact_status_label (const enum ast_sip_contact_status_type status)
translate ast_sip_contact_status_type to character string.
char * ast_sip_get_debug (void)
Retrieve the system debug setting (yes|no|host).
void ast_sip_get_default_from_user (char *from_user, size_t size)
Retrieve the global default from user.
void ast_sip_get_default_realm (char *realm, size_t size)
Retrieve the global default realm.
char * ast_sip_get_default_voicemail_extension (void)
Retrieve the default voicemail extension.
const char * ast_sip_get_device_state (const struct ast_sip_endpoint *endpoint)
Retrieve the device state for an endpoint.
unsigned int ast_sip_get_disable_multi_domain (void)
Retrieve the system setting 'disable multi domain'.
struct ast_taskprocessor * ast_sip_get_distributor_serializer (pjsip_rx_data *rdata)
Determine the distributor serializer for the SIP message.
char * ast_sip_get_endpoint_identifier_order (void)
Retrieve the global endpoint_identifier_order setting.
struct ast_endpoint_snapshot * ast_sip_get_endpoint_snapshot (const struct ast_sip_endpoint *endpoint)
Retrieve the endpoint snapshot for an endpoint.
struct ao2_container * ast_sip_get_endpoints (void)
Retrieve any endpoints available to sorcery.
int ast_sip_get_host_ip (int af, pj_sockaddr *addr)
Retrieve the local host address in IP form.
const char * ast_sip_get_host_ip_string (int af)
Retrieve the local host address in string form.
unsigned int ast_sip_get_ignore_uri_user_options (void)
Retrieve the global setting 'ignore_uri_user_options'.
unsigned int ast_sip_get_keep_alive_interval (void)
Retrieve the system keep alive interval setting.
unsigned int ast_sip_get_max_initial_qualify_time (void)
Retrieve the system max initial qualify time.
unsigned int ast_sip_get_mwi_disable_initial_unsolicited (void)
Retrieve the global setting 'disable sending unsolicited mwi on startup'.
unsigned int ast_sip_get_mwi_tps_queue_high (void)
Retrieve the global MWI taskprocessor high water alert trigger level.
int ast_sip_get_mwi_tps_queue_low (void)
Retrieve the global MWI taskprocessor low water clear alert level.
unsigned int ast_sip_get_norefersub (void)
Retrieve the global setting 'norefersub'.
pjsip_endpoint * ast_sip_get_pjsip_endpoint (void)
Get a pointer to the PJSIP endpoint.
char * ast_sip_get_regcontext (void)
Retrieve the global regcontext setting.
unsigned int ast_sip_get_send_contact_status_on_update_registration (void)
Retrieve the global setting 'send_contact_status_on_update_registration'.
struct ast_sorcery * ast_sip_get_sorcery (void)
Get a pointer to the SIP sorcery structure.
int ast_sip_get_transport_name (const struct ast_sip_endpoint *endpoint, pjsip_sip_uri *sip_uri, char *buf, size_t buf_len)
Get the transport name from an endpoint or request uri.
struct ast_sip_transport_state * ast_sip_get_transport_state (const char *transport_id)
Retrieve transport state.
struct ao2_container * ast_sip_get_transport_states (void)
Retrieves all transport states.
void ast_sip_get_unidentified_request_thresholds (unsigned int *count, unsigned int *period, unsigned int *prune_interval)
Retrieve the unidentified request security event thresholds.
unsigned int ast_sip_get_use_callerid_contact (void)
Retrieve the global setting 'use_callerid_contact'.
struct ast_sip_endpoint * ast_sip_identify_endpoint (pjsip_rx_data *rdata)
Determine the endpoint that has sent a SIP message.
int ast_sip_is_content_type (pjsip_media_type *content_type, char *type, char *subtype)
Checks if the given content type matches type/subtype.
int ast_sip_location_add_contact (struct ast_sip_aor *aor, const char *uri, struct timeval expiration_time, const char *path_info, const char *user_agent, const char *via_addr, int via_port, const char *call_id, struct ast_sip_endpoint *endpoint)
Add a new contact to an AOR.
int ast_sip_location_add_contact_nolock (struct ast_sip_aor *aor, const char *uri, struct timeval expiration_time, const char *path_info, const char *user_agent, const char *via_addr, int via_port, const char *call_id, struct ast_sip_endpoint *endpoint)
Add a new contact to an AOR without locking the AOR.
struct ast_sip_contact * ast_sip_location_create_contact (struct ast_sip_aor *aor, const char *uri, struct timeval expiration_time, const char *path_info, const char *user_agent, const char *via_addr, int via_port, const char *call_id, int prune_on_boot, struct ast_sip_endpoint *endpoint)
Create a new contact for an AOR without locking the AOR.
int ast_sip_location_delete_contact (struct ast_sip_contact *contact)
Delete a contact.
void ast_sip_location_prune_boot_contacts (void)
Prune the prune_on_boot contacts.
struct ast_sip_aor * ast_sip_location_retrieve_aor (const char *aor_name)
Retrieve a named AOR.
struct ao2_container * ast_sip_location_retrieve_aor_contacts (const struct ast_sip_aor *aor)
Retrieve all contacts currently available for an AOR.
struct ao2_container * ast_sip_location_retrieve_aor_contacts_filtered (const struct ast_sip_aor *aor, unsigned int flags)
Retrieve all contacts currently available for an AOR and filter based on flags.
struct ao2_container * ast_sip_location_retrieve_aor_contacts_nolock (const struct ast_sip_aor *aor)
Retrieve all contacts currently available for an AOR without locking the AOR.
struct ao2_container * ast_sip_location_retrieve_aor_contacts_nolock_filtered (const struct ast_sip_aor *aor, unsigned int flags)
Retrieve all contacts currently available for an AOR without locking the AOR and filter based on flags.
struct ast_sip_contact * ast_sip_location_retrieve_contact (const char *contact_name)
Retrieve a named contact.
void ast_sip_location_retrieve_contact_and_aor_from_list (const char *aor_list, struct ast_sip_aor **aor, struct ast_sip_contact **contact)
Retrieve the first bound contact AND the AOR chosen from a list of AORs.
void ast_sip_location_retrieve_contact_and_aor_from_list_filtered (const char *aor_list, unsigned int flags, struct ast_sip_aor **aor, struct ast_sip_contact **contact)
Retrieve the first bound contact AND the AOR chosen from a list of AORs and filter based on flags.
struct ast_sip_contact * ast_sip_location_retrieve_contact_from_aor_list (const char *aor_list)
Retrieve the first bound contact from a list of AORs.
struct ao2_container * ast_sip_location_retrieve_contacts_from_aor_list (const char *aor_list)
Retrieve all contacts from a list of AORs.
struct ast_sip_contact * ast_sip_location_retrieve_first_aor_contact (const struct ast_sip_aor *aor)
Retrieve the first bound contact for an AOR.
struct ast_sip_contact * ast_sip_location_retrieve_first_aor_contact_filtered (const struct ast_sip_aor *aor, unsigned int flags)
Retrieve the first bound contact for an AOR and filter based on flags.
int ast_sip_location_update_contact (struct ast_sip_contact *contact)
Update a contact.
void ast_sip_message_apply_transport (const char *transport_name, pjsip_tx_data *tdata)
Apply the configuration for a transport to an outgoing message.
void ast_sip_modify_id_header (pj_pool_t *pool, pjsip_fromto_hdr *id_hdr, const struct ast_party_id *id)
Set name and number information on an identity header.
void ast_sip_persistent_endpoint_publish_contact_state (const char *endpoint_name, const struct ast_sip_contact_status *contact_status)
Publish the change of state for a contact.
int ast_sip_persistent_endpoint_update_state (const char *endpoint_name, enum ast_endpoint_state state)
Change state of a persistent endpoint.
int ast_sip_push_task (struct ast_taskprocessor *serializer, int(*sip_task)(void *), void *task_data)
Pushes a task to SIP servants.
int ast_sip_push_task_synchronous (struct ast_taskprocessor *serializer, int(*sip_task)(void *), void *task_data)
Push a task to SIP servants and wait for it to complete.
int ast_sip_push_task_wait_serializer (struct ast_taskprocessor *serializer, int(*sip_task)(void *), void *task_data)
Push a task to the serializer and wait for it to complete.
int ast_sip_push_task_wait_servant (struct ast_taskprocessor *serializer, int(*sip_task)(void *), void *task_data)
Push a task to SIP servants and wait for it to complete.
char * ast_sip_rdata_get_header_value (pjsip_rx_data *rdata, const pj_str_t str)
Get a specific header value from rdata.
int ast_sip_register_authenticator (struct ast_sip_authenticator *auth)
Register a SIP authenticator.
void ast_sip_register_endpoint_formatter (struct ast_sip_endpoint_formatter *obj)
Register an endpoint formatter.
int ast_sip_register_endpoint_identifier (struct ast_sip_endpoint_identifier *identifier)
Register a SIP endpoint identifier.
int ast_sip_register_endpoint_identifier_with_name (struct ast_sip_endpoint_identifier *identifier, const char *name)
Register a SIP endpoint identifier with a name.
int ast_sip_register_outbound_authenticator (struct ast_sip_outbound_authenticator *outbound_auth)
Register an outbound SIP authenticator.
int ast_sip_register_service (pjsip_module *module)
Register a SIP service in Asterisk.
void ast_sip_register_supplement (struct ast_sip_supplement *supplement)
Register a supplement to SIP out of dialog processing.
void ast_sip_report_auth_challenge_sent (struct ast_sip_endpoint *endpoint, pjsip_rx_data *rdata, pjsip_tx_data *tdata)
Send a security event notification for when an authentication challenge is sent.
void ast_sip_report_auth_failed_challenge_response (struct ast_sip_endpoint *endpoint, pjsip_rx_data *rdata)
Send a security event notification for when a challenge response has failed.
void ast_sip_report_auth_success (struct ast_sip_endpoint *endpoint, pjsip_rx_data *rdata)
Send a security event notification for when authentication succeeds.
void ast_sip_report_failed_acl (struct ast_sip_endpoint *endpoint, pjsip_rx_data *rdata, const char *name)
Send a security event notification for when an ACL check fails.
void ast_sip_report_invalid_endpoint (const char *name, pjsip_rx_data *rdata)
Send a security event notification for when an invalid endpoint is requested.
void ast_sip_report_mem_limit (struct ast_sip_endpoint *endpoint, pjsip_rx_data *rdata)
Send a security event notification for when a memory limit is hit.
void ast_sip_report_req_no_support (struct ast_sip_endpoint *endpoint, pjsip_rx_data *rdata, const char *req_type)
Send a security event notification for when a request is not supported.
int ast_sip_requires_authentication (struct ast_sip_endpoint *endpoint, pjsip_rx_data *rdata)
Determine if an incoming request requires authentication.
int ast_sip_retrieve_auths (const struct ast_sip_auth_vector *auths, struct ast_sip_auth **out)
Retrieve relevant SIP auth structures from sorcery.
int ast_sip_retrieve_auths_vector (const struct ast_sip_auth_vector *auth_ids, struct ast_sip_auth_objects_vector *auth_objects)
int ast_sip_sched_is_task_running (struct ast_sip_sched_task *schtd)
Checks if the task is currently running.
int ast_sip_sched_is_task_running_by_name (const char *name)
Checks if the task is currently running.
int ast_sip_sched_task_cancel (struct ast_sip_sched_task *schtd)
Cancels the next invocation of a task.
int ast_sip_sched_task_cancel_by_name (const char *name)
Cancels the next invocation of a task by name.
int ast_sip_sched_task_get_name (struct ast_sip_sched_task *schtd, char *name, size_t maxlen)
Gets the task name.
int ast_sip_sched_task_get_next_run (struct ast_sip_sched_task *schtd)
Gets the number of milliseconds until the next invocation.
int ast_sip_sched_task_get_next_run_by_name (const char *name)
Gets the number of milliseconds until the next invocation.
int ast_sip_sched_task_get_times (struct ast_sip_sched_task *schtd, struct timeval *when_queued, struct timeval *last_start, struct timeval *last_end)
Gets the last start and end times of the task.
int ast_sip_sched_task_get_times2 (struct ast_sip_sched_task *schtd, struct timeval *when_queued, struct timeval *last_start, struct timeval *last_end, int *interval, int *time_left, struct timeval *next_start)
Gets the queued, last start, last_end, time left, interval, next run.
int ast_sip_sched_task_get_times_by_name (const char *name, struct timeval *when_queued, struct timeval *last_start, struct timeval *last_end)
Gets the last start and end times of the task by name.
int ast_sip_sched_task_get_times_by_name2 (const char *name, struct timeval *when_queued, struct timeval *last_start, struct timeval *last_end, int *interval, int *time_left, struct timeval *next_start)
Gets the queued, last start, last_end, time left, interval, next run by task name.
struct ast_sip_sched_task * ast_sip_schedule_task (struct ast_taskprocessor *serializer, int interval, ast_sip_task sip_task, const char *name, void *task_data, enum ast_sip_scheduler_task_flags flags)
Schedule a task to run in the res_pjsip thread pool.
int ast_sip_send_out_of_dialog_request (pjsip_tx_data *tdata, struct ast_sip_endpoint *endpoint, int timeout, void *token, void(*callback)(void *token, pjsip_event *e))
General purpose method for sending an Out-Of-Dialog SIP request.
int ast_sip_send_request (pjsip_tx_data *tdata, struct pjsip_dialog *dlg, struct ast_sip_endpoint *endpoint, void *token, void(*callback)(void *token, pjsip_event *e))
General purpose method for sending a SIP request.
int ast_sip_send_response (pjsip_response_addr *res_addr, pjsip_tx_data *tdata, struct ast_sip_endpoint *sip_endpoint)
Send a response to an out of dialog request.
int ast_sip_send_stateful_response (pjsip_rx_data *rdata, pjsip_tx_data *tdata, struct ast_sip_endpoint *sip_endpoint)
Send a stateful response to an out of dialog request.
struct ast_sip_service_route_vector * ast_sip_service_route_vector_alloc (void)
Allocate a vector of service routes.
void ast_sip_service_route_vector_destroy (struct ast_sip_service_route_vector *service_routes)
Destroy a vector of service routes.
int ast_sip_set_outbound_proxy (pjsip_tx_data *tdata, const char *proxy)
Set the outbound proxy for an outbound SIP message.
int ast_sip_set_tpselector_from_ep_or_uri (const struct ast_sip_endpoint *endpoint, pjsip_sip_uri *sip_uri, pjsip_tpselector *selector)
Sets pjsip_tpselector from an endpoint or uri.
int ast_sip_set_tpselector_from_transport (const struct ast_sip_transport *transport, pjsip_tpselector *selector)
Sets pjsip_tpselector from ast_sip_transport.
int ast_sip_set_tpselector_from_transport_name (const char *transport_name, pjsip_tpselector *selector)
Sets pjsip_tpselector from ast_sip_transport.
int ast_sip_sorcery_object_to_ami (const void *obj, struct ast_str **buf)
Converts a sorcery object to a string of object properties.
int ast_sip_str_to_dtmf (const char *dtmf_mode)
Convert the DTMF mode name into an enum.
int ast_sip_thread_is_servant (void)
Determine if the current thread is a SIP servant thread.
struct ast_threadpool * ast_sip_threadpool (void)
Retrieve the SIP threadpool object.
long ast_sip_threadpool_queue_size (void)
Return the size of the SIP threadpool's task queue.
void ast_sip_tpselector_unref (pjsip_tpselector *selector)
Unreference a pjsip_tpselector.
enum ast_transport_monitor_reg ast_sip_transport_monitor_register (pjsip_transport *transport, ast_transport_monitor_shutdown_cb cb, void *ao2_data)
Register a reliable transport shutdown monitor callback.
enum ast_transport_monitor_reg ast_sip_transport_monitor_register_replace (pjsip_transport *transport, ast_transport_monitor_shutdown_cb cb, void *ao2_data, ast_transport_monitor_data_matcher matches)
Register a reliable transport shutdown monitor callback replacing any duplicate.
void ast_sip_transport_monitor_unregister (pjsip_transport *transport, ast_transport_monitor_shutdown_cb cb, void *data, ast_transport_monitor_data_matcher matches)
Unregister a reliable transport shutdown monitor.
void ast_sip_transport_monitor_unregister_all (ast_transport_monitor_shutdown_cb cb, void *data, ast_transport_monitor_data_matcher matches)
Unregister a transport shutdown monitor from all reliable transports.
void ast_sip_transport_state_register (struct ast_sip_tpmgr_state_callback *element)
Register a transport state notification callback element.
int ast_sip_transport_state_set_preferred_identity (const char *transport_name, const char *identity)
Sets the P-Preferred-Identity on a child transport.
int ast_sip_transport_state_set_service_routes (const char *transport_name, struct ast_sip_service_route_vector *service_routes)
Sets the service routes on a child transport.
int ast_sip_transport_state_set_transport (const char *transport_name, pjsip_transport *transport)
Sets the PJSIP transport on a child transport.
void ast_sip_transport_state_unregister (struct ast_sip_tpmgr_state_callback *element)
Unregister a transport state notification callback element.
void ast_sip_unregister_authenticator (struct ast_sip_authenticator *auth)
Unregister a SIP authenticator.
void ast_sip_unregister_endpoint_formatter (struct ast_sip_endpoint_formatter *obj)
Unregister an endpoint formatter.
void ast_sip_unregister_endpoint_identifier (struct ast_sip_endpoint_identifier *identifier)
Unregister a SIP endpoint identifier.
void ast_sip_unregister_outbound_authenticator (struct ast_sip_outbound_authenticator *auth)
Unregister an outbound SIP authenticator.
void ast_sip_unregister_service (pjsip_module *module)
void ast_sip_unregister_supplement (struct ast_sip_supplement *supplement)
Unregister a an supplement to SIP out of dialog processing.
AST_VECTOR (ast_sip_service_route_vector, char *)
AST_VECTOR (ast_sip_auth_objects_vector, struct ast_sip_auth *)
Retrieve relevant SIP auth structures from sorcery as a vector.
Macro Definition Documentation
ast_sip_cleanup_auth_objects_vector
#define ast_sip_cleanup_auth_objects_vector (auth_objects) AST_VECTOR_RESET(auth_objects, ao2_cleanup)
Clean up retrieved auth objects in vector.
Call this function once you have completed operating on auths retrieved from ast_sip_retrieve_auths_vector. All auth objects will have their reference counts decremented and the vector size will be reset to 0. You must still call AST_VECTOR_FREE() on the vector itself.
Parameters
auth_objects A vector of auth structures to clean up
Definition at line 2538 of file res_pjsip.h.
Referenced by digest_create_request_with_auth().
ast_sip_mod_data_get
#define ast_sip_mod_data_get (mod_data, id, key) ast_sip_dict_get(mod_data[id], key)
Using the dictionary stored in mod_data array at a given id, retrieve the value associated with the given key.
Parameters
mod_data a module data array
id the mod_data array index
key the key to find
Return values
the value associated with the key, NULL otherwise.
Definition at line 2638 of file res_pjsip.h.
Referenced by ast_sip_send_out_of_dialog_request(), ast_sip_send_stateful_response(), ast_sip_subscription_get_header(), create_subscription_tree(), filter_on_tx_message(), get_restrictions(), session_inv_on_tsx_state_changed(), session_outgoing_nat_hook(), sip_subscription_accept(), and supplement_outgoing_response().
ast_sip_mod_data_set
#define ast_sip_mod_data_set (pool, mod_data, id, key, val) mod_data[id] = ast_sip_dict_set(pool, mod_data[id], key, val)
Utilizing a mod_data array for a given id, set the value associated with the given key.
For a given structure's mod_data array set the element indexed by id to be a dictionary containing the key/val pair.
Parameters
pool a memory allocation pool
mod_data a module data array
id the mod_data array index
key the key to find
val the value to associate with a key
Definition at line 2670 of file res_pjsip.h.
Referenced by ast_sip_create_response(), ast_sip_send_out_of_dialog_request(), ast_sip_send_stateful_response(), ast_sip_session_send_request_with_cb(), create_out_of_dialog_request(), create_subscription_tree(), get_restrictions(), session_outgoing_nat_hook(), sub_persistence_recreate(), and supplement_outgoing_response().
ast_sip_transport_is_local
#define ast_sip_transport_is_local (transport_state, addr) (transport_state->localnet && ast_apply_ha(transport_state->localnet, addr) != AST_SENSE_ALLOW)
Definition at line 165 of file res_pjsip.h.
Referenced by process_nat(), and session_outgoing_nat_hook().
ast_sip_transport_is_nonlocal
#define ast_sip_transport_is_nonlocal (transport_state, addr) (!transport_state->localnet || ast_apply_ha(transport_state->localnet, addr) == AST_SENSE_ALLOW)
Definition at line 162 of file res_pjsip.h.
Referenced by change_outgoing_sdp_stream_media_address().
AST_SIP_USER_OPTIONS_TRUNCATE_CHECK
#define AST_SIP_USER_OPTIONS_TRUNCATE_CHECK (str)
Truncate the URI user field options string if enabled.
Since
13.12.0
Parameters
str URI user field string to truncate if enabled
We need to be able to handle URI's looking like "sip:1235557890;phone-context=national@x.x.x.x;user=phone"
Where the URI user field is: "1235557890;phone-context=national"
When truncated the string will become: "1235557890"
Definition at line 3036 of file res_pjsip.h.
Referenced by find_aor(), get_destination(), handle_atsign(), options_on_rx_request(), publish_request_initial(), pubsub_on_rx_subscribe_request(), refer_incoming_blind_request(), rx_data_to_ast_msg(), session_inv_on_redirected(), sub_persistence_recreate(), and username_identify().
AST_SIP_X_AST_TXP
#define AST_SIP_X_AST_TXP "x-ast-txp"
URI parameter for symmetric transport
Definition at line 909 of file res_pjsip.h.
Referenced by ast_sip_get_transport_name(), on_rx_process_symmetric_transport(), sanitize_tdata(), and transport_apply().
AST_SIP_X_AST_TXP_LEN
#define AST_SIP_X_AST_TXP_LEN 9
Definition at line 910 of file res_pjsip.h.
Referenced by ast_sip_get_transport_name(), on_rx_process_symmetric_transport(), sanitize_tdata(), and transport_apply().
MAX_RX_CHALLENGES
#define MAX_RX_CHALLENGES 10
Maximum number of challenges before assuming that we are in a loop
Definition at line 80 of file res_pjsip.h.
Referenced by check_request_status(), outbound_invite_auth(), and session_inv_on_tsx_state_changed().
PJSIP_EXPIRES_NOT_SPECIFIED
#define PJSIP_EXPIRES_NOT_SPECIFIED ((pj_uint32_t)-1)
Definition at line 63 of file res_pjsip.h.
Referenced by initial_notify_task(), pubsub_on_rx_subscribe_request(), registrar_add_contact(), and registrar_get_expiration().
PJSIP_MINVERSION
#define PJSIP_MINVERSION (m, n, p) (((m << 24) | (n << 16) | (p << 8)) >= PJ_VERSION_NUM)
Definition at line 54 of file res_pjsip.h.
SIP_SORCERY_DOMAIN_ALIAS_TYPE
#define SIP_SORCERY_DOMAIN_ALIAS_TYPE "domain_alias"
Definition at line 254 of file res_pjsip.h.
Referenced by ast_sip_initialize_sorcery_domain_alias(), and domain_alias_apply().
SIP_TLS_MAX_CIPHERS
#define SIP_TLS_MAX_CIPHERS 64
Maximum number of ciphers supported for a TLS transport.
Definition at line 77 of file res_pjsip.h.
Typedef Documentation
ast_sip_dialog_outbound_auth_cb
typedef int(* ast_sip_dialog_outbound_auth_cb) (pjsip_dialog *dlg, pjsip_tx_data *tdata, void *user_data)
Callback called when an outbound request with authentication credentials is to be sent in dialog.
This callback will have the created request on it. The callback's purpose is to do any extra housekeeping that needs to be done as well as to send the request out.
This callback is only necessary if working with a PJSIP API that sits between the application and the dialog layer.
Parameters
dlg The dialog to which the request belongs
tdata The created request to be sent out
user_data Data supplied with the callback
Return values
0 Success
-1 Failure
Definition at line 1468 of file res_pjsip.h.
ast_transport_monitor_data_matcher
typedef int(* ast_transport_monitor_data_matcher) (void *a, void *b)
Transport shutdown monitor data matcher.
Since
13.20.0
Parameters
a User data to compare.
b User data to compare.
Return values
1 The data objects match
0 The data objects don't match
Definition at line 3457 of file res_pjsip.h.
ast_transport_monitor_shutdown_cb
typedef void(* ast_transport_monitor_shutdown_cb) (void *data)
Transport shutdown monitor callback.
Since
13.18.0
Parameters
data User data to know what to do when transport shuts down.
Note
The callback does not need to care that data is an ao2 object.
Returns
Nothing
Definition at line 3445 of file res_pjsip.h.
Enumeration Type Documentation
ast_sip_auth_type
enum ast_sip_auth_type
Methods of storing SIP digest authentication credentials.
Note that both methods result in MD5 digest authentication being used. The two methods simply alter how Asterisk determines the credentials for a SIP authentication
Enumerator
AST_SIP_AUTH_TYPE_USER_PASS
Credentials stored as a username and password combination
AST_SIP_AUTH_TYPE_MD5
Credentials stored as an MD5 sum
AST_SIP_AUTH_TYPE_GOOGLE_OAUTH
Google Oauth
AST_SIP_AUTH_TYPE_ARTIFICIAL
Credentials not stored this is a fake auth
Definition at line 431 of file res_pjsip.h.
{
    /*! Credentials stored as a username and password combination */
    AST_SIP_AUTH_TYPE_USER_PASS,
    /*! Credentials stored as an MD5 sum */
    AST_SIP_AUTH_TYPE_MD5,
    /*! Google Oauth */
    AST_SIP_AUTH_TYPE_GOOGLE_OAUTH,
    /*! Credentials not stored this is a fake auth */
ast_sip_call_codec_pref
enum ast_sip_call_codec_pref
Incoming/Outgoing call offer/answer joint codec preference.
The default is INTERSECT ALL LOCAL.
Enumerator
AST_SIP_CALL_CODEC_PREF_INTERSECT
Two bits for merge
Intersection of local and remote
AST_SIP_CALL_CODEC_PREF_UNION
Union of local and remote
AST_SIP_CALL_CODEC_PREF_ALL
Two bits for filter
No filter
AST_SIP_CALL_CODEC_PREF_FIRST
Only the first
AST_SIP_CALL_CODEC_PREF_LOCAL
Two bits for preference and sort
Prefer, and order by local values
AST_SIP_CALL_CODEC_PREF_REMOTE
Prefer, and order by remote values
Definition at line 529 of file res_pjsip.h.
{
    /*! Two bits for merge */
    /*! Intersection of local and remote */
    AST_SIP_CALL_CODEC_PREF_INTERSECT = 1 << 0,
    /*! Union of local and remote */
    AST_SIP_CALL_CODEC_PREF_UNION =     1 << 1,
    /*! Two bits for filter */
    /*! No filter */
    AST_SIP_CALL_CODEC_PREF_ALL =    1 << 2,
    /*! Only the first */
    AST_SIP_CALL_CODEC_PREF_FIRST =  1 << 3,
    /*! Two bits for preference and sort   */
    /*! Prefer, and order by local values */
ast_sip_check_auth_result
enum ast_sip_check_auth_result
Possible returns from ast_sip_check_authentication.
Enumerator
AST_SIP_AUTHENTICATION_CHALLENGE
Authentication needs to be challenged
AST_SIP_AUTHENTICATION_SUCCESS
Authentication succeeded
AST_SIP_AUTHENTICATION_FAILED
Authentication failed
AST_SIP_AUTHENTICATION_ERROR
Authentication encountered some internal error
Definition at line 932 of file res_pjsip.h.
{
ast_sip_contact_filter
enum ast_sip_contact_filter
Contact retrieval filtering flags.
Enumerator
AST_SIP_CONTACT_FILTER_DEFAULT
Default filter flags.
AST_SIP_CONTACT_FILTER_REACHABLE
Return only reachable or unknown contacts.
Definition at line 1004 of file res_pjsip.h.
{
     /*!
      * \brief Callback used to identify the source of a message.
      * See ast_sip_identify_endpoint for more details
ast_sip_contact_status_type
enum ast_sip_contact_status_type
Status type for a contact.
Enumerator
UNAVAILABLE
Frequency > 0, but no response from remote uri
AVAILABLE
Frequency > 0, and got response from remote uri
UNKNOWN
Default last status, and when a contact status object is not found
CREATED
Frequency == 0, has a contact, but don't know status (non-qualified)
REMOVED
Definition at line 323 of file res_pjsip.h.
{
    /*! Frequency > 0, but no response from remote uri */
    UNAVAILABLE,
    /*! Frequency > 0, and got response from remote uri */
    AVAILABLE,
    /*! Default last status, and when a contact status object is not found */
    UNKNOWN,
    /*! Frequency == 0, has a contact, but don't know status (non-qualified) */
    CREATED,
    REMOVED,
 };
ast_sip_direct_media_glare_mitigation
enum ast_sip_direct_media_glare_mitigation
Enumerator
AST_SIP_DIRECT_MEDIA_GLARE_MITIGATION_NONE
Take no special action to mitigate reinvite glare
AST_SIP_DIRECT_MEDIA_GLARE_MITIGATION_OUTGOING
Do not send an initial direct media session refresh on outgoing call legs Subsequent session refreshes will be sent no matter the session direction
AST_SIP_DIRECT_MEDIA_GLARE_MITIGATION_INCOMING
Do not send an initial direct media session refresh on incoming call legs Subsequent session refreshes will be sent no matter the session direction
Definition at line 491 of file res_pjsip.h.
{
    /*! Take no special action to mitigate reinvite glare */
    AST_SIP_DIRECT_MEDIA_GLARE_MITIGATION_NONE,
    /*! Do not send an initial direct media session refresh on outgoing call legs
     * Subsequent session refreshes will be sent no matter the session direction
     */
    AST_SIP_DIRECT_MEDIA_GLARE_MITIGATION_OUTGOING,
    /*! Do not send an initial direct media session refresh on incoming call legs
ast_sip_dtmf_mode
enum ast_sip_dtmf_mode
DTMF modes for SIP endpoints.
Enumerator
AST_SIP_DTMF_NONE
No DTMF to be used
AST_SIP_DTMF_RFC_4733
Use RFC 4733 events for DTMF
AST_SIP_DTMF_INBAND
Use DTMF in the audio stream
AST_SIP_DTMF_INFO
Use SIP INFO DTMF (blech)
AST_SIP_DTMF_AUTO
Use SIP 4733 if supported by the other side or INBAND if not
AST_SIP_DTMF_AUTO_INFO
Use SIP 4733 if supported by the other side or INFO DTMF (blech) if not
Definition at line 408 of file res_pjsip.h.
{
    /*! No DTMF to be used */
    AST_SIP_DTMF_NONE,
    /* XXX Should this be 2833 instead? */
    /*! Use RFC 4733 events for DTMF */
    AST_SIP_DTMF_RFC_4733,
    /*! Use DTMF in the audio stream */
    AST_SIP_DTMF_INBAND,
    /*! Use SIP INFO DTMF (blech) */
    AST_SIP_DTMF_INFO,
    /*! Use SIP 4733 if supported by the other side or INBAND if not */
    AST_SIP_DTMF_AUTO,
    /*! Use SIP 4733 if supported by the other side or INFO DTMF (blech) if not */
ast_sip_endpoint_identifier_type
enum ast_sip_endpoint_identifier_type
Different methods by which incoming requests can be matched to endpoints.
Enumerator
AST_SIP_ENDPOINT_IDENTIFY_BY_USERNAME
Identify based on user name in From header
AST_SIP_ENDPOINT_IDENTIFY_BY_AUTH_USERNAME
Identify based on user name in Auth header first, then From header
AST_SIP_ENDPOINT_IDENTIFY_BY_IP
Identify based on source IP address
AST_SIP_ENDPOINT_IDENTIFY_BY_HEADER
Identify based on arbitrary headers
Definition at line 472 of file res_pjsip.h.
{
    /*! Identify based on user name in From header */
    AST_SIP_ENDPOINT_IDENTIFY_BY_USERNAME = (1 << 0),
    /*! Identify based on user name in Auth header first, then From header */
    AST_SIP_ENDPOINT_IDENTIFY_BY_AUTH_USERNAME = (1 << 1),
    /*! Identify based on source IP address */
ast_sip_session_media_encryption
enum ast_sip_session_media_encryption
Enumerator
AST_SIP_MEDIA_TRANSPORT_INVALID
Invalid media encryption configuration
AST_SIP_MEDIA_ENCRYPT_NONE
Do not allow any encryption of session media
AST_SIP_MEDIA_ENCRYPT_SDES
Offer SDES-encrypted session media
AST_SIP_MEDIA_ENCRYPT_DTLS
Offer encrypted session media with datagram TLS key exchange
Definition at line 504 of file res_pjsip.h.
{
    /*! Invalid media encryption configuration */
    AST_SIP_MEDIA_TRANSPORT_INVALID = 0,
    /*! Do not allow any encryption of session media */
    AST_SIP_MEDIA_ENCRYPT_NONE,
    /*! Offer SDES-encrypted session media */
ast_sip_session_redirect
enum ast_sip_session_redirect
Enumerator
AST_SIP_REDIRECT_USER
User portion of the target URI should be used as the target in the dialplan
AST_SIP_REDIRECT_URI_CORE
Target URI should be used as the target in the dialplan
AST_SIP_REDIRECT_URI_PJSIP
Target URI should be used as the target within chan_pjsip itself
Definition at line 515 of file res_pjsip.h.
{
    /*! User portion of the target URI should be used as the target in the dialplan */
    AST_SIP_REDIRECT_USER = 0,
    /*! Target URI should be used as the target in the dialplan */
ast_sip_session_refresh_method
enum ast_sip_session_refresh_method
Enumerator
AST_SIP_SESSION_REFRESH_METHOD_INVITE
Use reinvite to negotiate direct media
AST_SIP_SESSION_REFRESH_METHOD_UPDATE
Use UPDATE to negotiate direct media
Definition at line 484 of file res_pjsip.h.
{
    /*! Use reinvite to negotiate direct media */
ast_sip_supplement_priority
enum ast_sip_supplement_priority
Enumerator
AST_SIP_SUPPLEMENT_PRIORITY_FIRST
Top priority. Supplements with this priority are those that need to run before any others
AST_SIP_SUPPLEMENT_PRIORITY_CHANNEL
Channel creation priority. chan_pjsip creates a channel at this priority. If your supplement depends on being run before or after channel creation, then set your priority to be lower or higher than this value.
AST_SIP_SUPPLEMENT_PRIORITY_LAST
Lowest priority. Supplements with this priority should be run after all other supplements
Definition at line 2869 of file res_pjsip.h.
{
ast_transport_monitor_reg
enum ast_transport_monitor_reg
Enumerator
AST_TRANSPORT_MONITOR_REG_SUCCESS
Successfully registered the transport monitor.
AST_TRANSPORT_MONITOR_REG_REPLACED
Replaced the already existing transport monitor with new one.
AST_TRANSPORT_MONITOR_REG_NOT_FOUND
Transport not found to monitor.
Note
Transport is either already shutdown or is not reliable.
AST_TRANSPORT_MONITOR_REG_FAILED
Error while registering transport monitor.
Definition at line 3459 of file res_pjsip.h.
{
Function Documentation
ast_copy_pj_str()
void ast_copy_pj_str (char * dest, const pj_str_t * src, size_t size)
Copy a pj_str_t into a standard character buffer.
pj_str_t is not NULL-terminated. Any place that expects a NULL- terminated string needs to have the pj_str_t copied into a separate buffer.
This method copies the pj_str_t contents into the destination buffer and NULL-terminates the buffer.
Parameters
dest The destination buffer
src The pj_str_t to copy
size The size of the destination buffer.
Definition at line 5240 of file res_pjsip.c.
References MIN.
Referenced by add_identity_header(), apply_dtls_attrib(), apply_negotiated_sdp_stream(), assign_uuid(), ast_sip_get_transport_name(), ast_sip_report_auth_challenge_sent(), ast_sip_report_auth_failed_challenge_response(), chan_pjsip_get_uniqueid(), change_outgoing_sdp_stream_media_address(), channel_read_pjsip(), cli_complete_subscription_common(), cli_list_subscriptions_detail(), cli_show_subscriptions_detail(), determine_sip_publish_type(), dialog_info_generate_body_content(), endpoint_lookup(), evaluate_like(), extract_contact_addr(), find_aor(), find_aor_name(), find_challenge(), get_auth_header(), get_codecs(), get_destination(), get_endpoint_details(), get_from_header(), get_mid_bundle_group(), get_user_agent(), handle_incoming_sdp(), handle_negotiated_sdp_session_media(), handle_registration_response(), headers_to_vars(), incoming_in_dialog_request(), log_failed_request(), negotiate_incoming_sdp_stream(), options_on_rx_request(), parse_uri_cb(), process_extmap_attributes(), process_ice_attributes(), process_ice_auth_attrb(), process_ssrc_attributes(), publish_request_initial(), pubsub_on_rx_publish_request(), pubsub_on_rx_subscribe_request(), refer_blind_callback(), refer_incoming_blind_request(), refer_incoming_refer_request(), register_aor_core(), rfc3326_use_reason_header(), rx_data_to_ast_msg(), save_response_fields_to_transport(), sdp_requires_deferral(), security_event_populate(), session_inv_on_redirected(), session_outgoing_nat_hook(), set_id_from_hdr(), set_id_from_oli(), set_mid_and_bundle_group(), set_redirecting_value(), set_remote_mslabel_and_stream_group(), set_sipdomain_variable(), sip_resolve(), sip_subscription_to_ami(), sub_persistence_recreate(), subscription_get_generator_from_rdata(), subscription_get_handler_from_rdata(), subscription_persistence_create(), subscription_persistence_update(), and transfer_refer().
 {
    size_t chars_to_copy = MIN(size - 1, pj_strlen(src));
    memcpy(dest, pj_strbuf(src), chars_to_copy);
    dest[chars_to_copy] = '\0';
 }
ast_copy_pj_str2()
int ast_copy_pj_str2 (char ** dest, const pj_str_t * src)
Create and copy a pj_str_t into a standard character buffer.
pj_str_t is not NULL-terminated. Any place that expects a NULL- terminated string needs to have the pj_str_t copied into a separate buffer.
Copies the pj_str_t contents into a newly allocated buffer pointed to by dest. NULL-terminates the buffer.
Note
Caller is responsible for freeing the allocated memory.
Parameters
dest [out] The destination buffer
src The pj_str_t to copy
Return values
Number of characters copied or negative value on error
Definition at line 5247 of file res_pjsip.c.
References ast_asprintf, and NULL.
 {
    int res = ast_asprintf(dest, "%.*s", (int)pj_strlen(src), pj_strbuf(src));
    if (res < 0) {
       *dest = NULL;
    }
    return res;
 }
ast_pjsip_rdata_get_endpoint()
struct ast_sip_endpoint* ast_pjsip_rdata_get_endpoint (pjsip_rx_data * rdata)
Get the looked-up endpoint on an out-of dialog request or response.
The function may ONLY be called on out-of-dialog requests or responses. For in-dialog requests and responses, it is required that the user of the dialog has the looked-up endpoint stored locally.
This function should never return NULL if the message is out-of-dialog. It will always return NULL if the message is in-dialog.
This function will increase the reference count of the returned endpoint by one. Release your reference using the ao2_ref function when finished.
Parameters
rdata Out-of-dialog request or response
Returns
The looked up endpoint
Definition at line 969 of file pjsip_distributor.c.
References ao2_ref, and endpoint_mod.
Referenced by authenticate(), handle_new_invite_request(), nat_on_rx_message(), options_on_rx_request(), pubsub_on_rx_mwi_notify_request(), pubsub_on_rx_publish_request(), pubsub_on_rx_subscribe_request(), registrar_on_rx_request(), rx_data_to_ast_msg(), send_options_response(), send_response(), and supplement_on_rx_request().
 {
    struct ast_sip_endpoint *endpoint = rdata->endpt_info.mod_data[endpoint_mod.id];
    if (endpoint) {
       ao2_ref(endpoint, +1);
    }
    return endpoint;
 }
ast_sip_add_body()
int ast_sip_add_body (pjsip_tx_data * tdata, const struct ast_sip_body * body)
Add a body to an outbound SIP message.
If this is called multiple times, the latest body will replace the current body.
Parameters
tdata The message to add the body to
body The message body to add
Return values
0 Success
-1 Failure
Definition at line 5091 of file res_pjsip.c.
References ast_body_to_pjsip_body().
Referenced by build_notify_body(), msg_send(), send_unsolicited_mwi_notify_to_contact(), sendtext(), sip_publisher_service_queue(), transmit_info_dtmf(), and transmit_info_with_vidupdate().
 {
    pjsip_msg_body *pjsip_body = ast_body_to_pjsip_body(tdata->pool, body);
    tdata->msg->body = pjsip_body;
    return 0;
 }
ast_sip_add_body_multipart()
int ast_sip_add_body_multipart (pjsip_tx_data * tdata, const struct ast_sip_body * bodies[], int num_bodies)
Add a multipart body to an outbound SIP message.
This will treat each part of the input vector as part of a multipart body and add each part to the SIP message.
Parameters
tdata The message to add the body to
bodies The parts of the body to add
Return values
0 Success
-1 Failure
Definition at line 5098 of file res_pjsip.c.
References ast_body_to_pjsip_body(), and NULL.
 {
    int i;
    /* NULL for type and subtype automatically creates "multipart/mixed" */
    pjsip_msg_body *body = pjsip_multipart_create(tdata->pool, NULL, NULL);
    for (i = 0; i < num_bodies; ++i) {
       pjsip_multipart_part *part = pjsip_multipart_create_part(tdata->pool);
       part->body = ast_body_to_pjsip_body(tdata->pool, bodies[i]);
       pjsip_multipart_add_part(tdata->pool, body, part);
    }
    tdata->msg->body = body;
    return 0;
 }
ast_sip_add_date_header()
void ast_sip_add_date_header (pjsip_tx_data * tdata)
Adds a Date header to the tdata, formatted like: Date: Wed, 01 Jan 2021 14:53:01 GMT.
Since
16.19.0
Note
There is no checking done to see if the header already exists before adding it. It's up to the caller of this function to determine if that needs to be done or not.
Definition at line 3288 of file res_pjsip.c.
References ast_sip_add_header(), and NULL.
Referenced by add_date_header(), and register_aor_core().
 {
    char date[256];
    struct tm tm;
    time_t t = time(NULL);
    gmtime_r(&t, &tm);
    strftime(date, sizeof(date), "%a, %d %b %Y %T GMT", &tm);
    ast_sip_add_header(tdata, "Date", date);
 }
ast_sip_add_global_request_header()
int ast_sip_add_global_request_header (const char * name, const char * value, int replace)
Definition at line 153 of file pjsip_global_headers.c.
References add_header(), and request_headers.
Referenced by global_apply().
 {
    return add_header(&request_headers, name, value, replace);
 }
ast_sip_add_global_response_header()
int ast_sip_add_global_response_header (const char * name, const char * value, int replace)
Definition at line 158 of file pjsip_global_headers.c.
References add_header(), and response_headers.
Referenced by global_apply().
 {
    return add_header(&response_headers, name, value, replace);
 }
ast_sip_add_header()
int ast_sip_add_header (pjsip_tx_data * tdata, const char * name, const char * value)
Add a header to an outbound SIP message.
Parameters
tdata The message to add the header to
name The header name
value The header value
Return values
0 Success
-1 Failure
Definition at line 5063 of file res_pjsip.c.
Referenced by add_header_from_channel_var(), add_headers_to_message(), ast_sip_add_date_header(), ast_sip_message_apply_transport(), build_notify(), notify_channel(), notify_contact(), notify_uri(), options_incoming_request(), rfc3326_add_reason_header(), send_options_response(), sip_publication_respond(), transfer_refer(), and vars_to_headers().
 {
    pj_str_t hdr_name;
    pj_str_t hdr_value;
    pjsip_generic_string_hdr *hdr;
    pj_cstr(&hdr_name, name);
    pj_cstr(&hdr_value, value);
    hdr = pjsip_generic_string_hdr_create(tdata->pool, &hdr_name, &hdr_value);
    pjsip_msg_add_hdr(tdata->msg, (pjsip_hdr *) hdr);
    return 0;
 }
ast_sip_add_usereqphone()
void ast_sip_add_usereqphone (const struct ast_sip_endpoint * endpoint, pj_pool_t * pool, pjsip_uri * uri)
Add 'user=phone' parameter to URI if enabled and user is a phone number.
Parameters
endpoint The endpoint to use for configuration
pool The memory pool to allocate the parameter from
uri The URI to check for user and to add parameter to
Definition at line 3994 of file res_pjsip.c.
References AST_DIGIT_ANY, and ast_sip_endpoint::usereqphone.
Referenced by ast_sip_create_dialog_uac(), create_out_of_dialog_request(), and set_from_header().
 {
    pjsip_sip_uri *sip_uri;
    int i = 0;
    static const pj_str_t STR_PHONE = { "phone", 5 };
    if (!endpoint || !endpoint->usereqphone || (!PJSIP_URI_SCHEME_IS_SIP(uri) && !PJSIP_URI_SCHEME_IS_SIPS(uri))) {
       return;
    }
    sip_uri = pjsip_uri_get_uri(uri);
    if (!pj_strlen(&sip_uri->user)) {
       return;
    }
    if (pj_strbuf(&sip_uri->user)[0] == '+') {
       i = 1;
    }
    /* Test URI user against allowed characters in AST_DIGIT_ANY */
    for (; i < pj_strlen(&sip_uri->user); i++) {
       if (!strchr(AST_DIGIT_ANY, pj_strbuf(&sip_uri->user)[i])) {
          break;
       }
    }
    if (i < pj_strlen(&sip_uri->user)) {
       return;
    }
    sip_uri->user_param = STR_PHONE;
 }
ast_sip_append_body()
int ast_sip_append_body (pjsip_tx_data * tdata, const char * body_text)
Append body data to a SIP message.
This acts mostly the same as ast_sip_add_body, except that rather than replacing a body if it currently exists, it appends data to an existing body.
Parameters
tdata The message to append the body to
body The string to append to the end of the current body
Return values
0 Success
-1 Failure
Definition at line 5114 of file res_pjsip.c.
References ast_str_alloca, ast_str_buffer(), and ast_str_set().
 {
    size_t combined_size = strlen(body_text) + tdata->msg->body->len;
    struct ast_str *body_buffer = ast_str_alloca(combined_size);
    ast_str_set(&body_buffer, 0, "%.*s%s", (int) tdata->msg->body->len, (char *) tdata->msg->body->data, body_text);
    tdata->msg->body->data = pj_pool_alloc(tdata->pool, combined_size);
    pj_memcpy(tdata->msg->body->data, ast_str_buffer(body_buffer), combined_size);
    tdata->msg->body->len = combined_size;
    return 0;
 }
ast_sip_auth_type_to_str()
const char* ast_sip_auth_type_to_str (enum ast_sip_auth_type type)
Converts the given auth type to a string.
Parameters
type the auth type to convert
Return values
a string representative of the auth type
Definition at line 80 of file config_auth.c.
References ARRAY_IN_BOUNDS, auth_types_map, and type.
Referenced by auth_type_to_str().
 {
    return ARRAY_IN_BOUNDS(type, auth_types_map) ?
       auth_types_map[type] : "";
 }
ast_sip_auth_vector_destroy()
void ast_sip_auth_vector_destroy (struct ast_sip_auth_vector * vector)
Free contents of an auth vector.
Parameters
array Vector whose contents are to be freed
Definition at line 249 of file pjsip_configuration.c.
References ast_free, AST_VECTOR_FREE, AST_VECTOR_REMOVE_UNORDERED, AST_VECTOR_SIZE, and name.
Referenced by ast_sip_auth_vector_init(), endpoint_destructor(), handle_client_state_destruction(), sip_outbound_publish_destroy(), sip_outbound_registration_destroy(), and sip_outbound_registration_perform().
 {
    int i;
    size_t size;
    if (!auths) {
       return;
    }
    size = AST_VECTOR_SIZE(auths);
    for (i = 0; i < size; ++i) {
       const char *name = AST_VECTOR_REMOVE_UNORDERED(auths, 0);
       ast_free((char *) name);
    }
    AST_VECTOR_FREE(auths);
 }
ast_sip_auth_vector_init()
int ast_sip_auth_vector_init (struct ast_sip_auth_vector * vector, const char * auth_names)
Initialize an auth vector with the configured values.
Parameters
vector Vector to initialize
auth_names Comma-separated list of names to set in the array
Return values
0 Success
non-zero Failure
Definition at line 267 of file pjsip_configuration.c.
References ast_assert, ast_free, ast_sip_auth_vector_destroy(), ast_strdup, ast_strdupa, ast_strip(), ast_strlen_zero, AST_VECTOR_APPEND, AST_VECTOR_INIT, AST_VECTOR_SIZE, NULL, and strsep().
Referenced by inbound_auth_handler(), and outbound_auth_handler().
 {
    char *auth_names = ast_strdupa(value);
    char *val;
    ast_assert(auths != NULL);
    if (AST_VECTOR_SIZE(auths)) {
       ast_sip_auth_vector_destroy(auths);
    }
    if (AST_VECTOR_INIT(auths, 1)) {
       return -1;
    }
    while ((val = ast_strip(strsep(&auth_names, ",")))) {
       if (ast_strlen_zero(val)) {
          continue;
       }
       val = ast_strdup(val);
       if (!val) {
          goto failure;
       }
       if (AST_VECTOR_APPEND(auths, val)) {
          ast_free(val);
          goto failure;
       }
    }
    return 0;
 failure:
    ast_sip_auth_vector_destroy(auths);
    return -1;
 }
ast_sip_auths_to_str()
int ast_sip_auths_to_str (const struct ast_sip_auth_vector * auths, char ** buf)
Converts an auths array to a string of comma separated values.
Parameters
auths an auth array
buf the string buffer to write the object data
Return values
0 Success, non-zero on failure
Definition at line 317 of file pjsip_configuration.c.
References ast_calloc, ast_join_delim(), AST_VECTOR_SIZE, ast_sip_auth_vector::elems, and MAX_OBJECT_FIELD.
Referenced by format_str_append_auth(), inbound_auths_to_str(), and outbound_auths_to_str().
 {
    if (!auths || !AST_VECTOR_SIZE(auths)) {
       return 0;
    }
    if (!(*buf = ast_calloc(MAX_OBJECT_FIELD, sizeof(char)))) {
       return -1;
    }
    /* I feel like accessing the vector's elem array directly is cheating...*/
    ast_join_delim(*buf, MAX_OBJECT_FIELD, auths->elems, AST_VECTOR_SIZE(auths), ',');
    return 0;
 }
ast_sip_call_codec_pref_to_str()
const char* ast_sip_call_codec_pref_to_str (struct ast_flags pref)
Convert the call codec preference flags to a string.
Since
18.0.0
Parameters
pref the call codec preference setting
Returns
a constant string with either the setting value or 'unknown'
Note
Don't try to free the string!
Definition at line 5534 of file res_pjsip.c.
References value.
Referenced by incoming_call_offer_pref_to_str(), log_caps(), and outgoing_call_offer_pref_to_str().
 {
    const char *value;
    if (ast_sip_call_codec_pref_test(pref, LOCAL) &&  ast_sip_call_codec_pref_test(pref, INTERSECT) && ast_sip_call_codec_pref_test(pref, ALL)) {
       value = "local";
    } else if (ast_sip_call_codec_pref_test(pref, LOCAL) &&  ast_sip_call_codec_pref_test(pref, UNION) && ast_sip_call_codec_pref_test(pref, ALL)) {
       value = "local_merge";
    } else if (ast_sip_call_codec_pref_test(pref, LOCAL) &&  ast_sip_call_codec_pref_test(pref, INTERSECT) && ast_sip_call_codec_pref_test(pref, FIRST)) {
       value = "local_first";
    } else if (ast_sip_call_codec_pref_test(pref, REMOTE) &&  ast_sip_call_codec_pref_test(pref, INTERSECT) && ast_sip_call_codec_pref_test(pref, ALL)) {
       value = "remote";
    } else if (ast_sip_call_codec_pref_test(pref, REMOTE) &&  ast_sip_call_codec_pref_test(pref, UNION) && ast_sip_call_codec_pref_test(pref, ALL)) {
       value = "remote_merge";
    } else if (ast_sip_call_codec_pref_test(pref, REMOTE) &&  ast_sip_call_codec_pref_test(pref, UNION) && ast_sip_call_codec_pref_test(pref, FIRST)) {
       value = "remote_first";
    } else {
       value = "unknown";
    }
    return value;
 }
ast_sip_call_codec_str_to_pref()
int ast_sip_call_codec_str_to_pref (struct ast_flags * pref, const char * pref_str, int is_outgoing)
Convert a call codec preference string to preference flags.
Since
18.0.0
Parameters
pref A pointer to an ast_flags structure to receive the preference flags
pref_str The call codec preference setting string
is_outgoing Is for outgoing calls?
Return values
0 The string was parsed successfully
-1 The string option was invalid
Definition at line 5557 of file res_pjsip.c.
References ast_set_flag, AST_SIP_CALL_CODEC_PREF_ALL, AST_SIP_CALL_CODEC_PREF_FIRST, AST_SIP_CALL_CODEC_PREF_INTERSECT, AST_SIP_CALL_CODEC_PREF_LOCAL, AST_SIP_CALL_CODEC_PREF_REMOTE, AST_SIP_CALL_CODEC_PREF_UNION, and ast_flags::flags.
Referenced by call_offer_pref_handler(), and test_create_joint().
 {
    pref->flags = 0;
    if (strcmp(pref_str, "local") == 0) {
       ast_set_flag(pref, AST_SIP_CALL_CODEC_PREF_LOCAL | AST_SIP_CALL_CODEC_PREF_INTERSECT | AST_SIP_CALL_CODEC_PREF_ALL);
    } else if (is_outgoing && strcmp(pref_str, "local_merge") == 0) {
       ast_set_flag(pref, AST_SIP_CALL_CODEC_PREF_LOCAL | AST_SIP_CALL_CODEC_PREF_UNION | AST_SIP_CALL_CODEC_PREF_ALL);
    } else if (strcmp(pref_str, "local_first") == 0) {
       ast_set_flag(pref, AST_SIP_CALL_CODEC_PREF_LOCAL | AST_SIP_CALL_CODEC_PREF_INTERSECT | AST_SIP_CALL_CODEC_PREF_FIRST);
    } else if (strcmp(pref_str, "remote") == 0) {
       ast_set_flag(pref, AST_SIP_CALL_CODEC_PREF_REMOTE | AST_SIP_CALL_CODEC_PREF_INTERSECT | AST_SIP_CALL_CODEC_PREF_ALL);
    } else if (is_outgoing && strcmp(pref_str, "remote_merge") == 0) {
       ast_set_flag(pref, AST_SIP_CALL_CODEC_PREF_REMOTE | AST_SIP_CALL_CODEC_PREF_UNION | AST_SIP_CALL_CODEC_PREF_ALL);
    } else if (strcmp(pref_str, "remote_first") == 0) {
       ast_set_flag(pref, AST_SIP_CALL_CODEC_PREF_REMOTE | AST_SIP_CALL_CODEC_PREF_UNION | AST_SIP_CALL_CODEC_PREF_FIRST);
    } else {
       return -1;
    }
    return 0;
 }
ast_sip_check_authentication()
enum ast_sip_check_auth_result ast_sip_check_authentication (struct ast_sip_endpoint * endpoint, pjsip_rx_data * rdata, pjsip_tx_data * tdata)
Method to determine authentication status of an incoming request.
This will call into a registered authenticator. The registered authenticator will do what is necessary to determine whether the incoming request passes authentication. A tentative response is passed into this function so that if, say, a digest authentication challenge should be sent in the ensuing response, it can be added to the response.
Parameters
endpoint The endpoint from the request was sent
rdata The request to potentially authenticate
tdata Tentative response to the request
Returns
The result of checking authentication.
Definition at line 3377 of file res_pjsip.c.
References ast_log, AST_SIP_AUTHENTICATION_SUCCESS, ast_sip_authenticator::check_authentication, and LOG_WARNING.
Referenced by authenticate().
 {
    if (!registered_authenticator) {
       ast_log(LOG_WARNING, "No SIP authenticator registered. Assuming authentication is successful\n");
       return AST_SIP_AUTHENTICATION_SUCCESS;
    }
    return registered_authenticator->check_authentication(endpoint, rdata, tdata);
 }
ast_sip_cleanup_auths()
void ast_sip_cleanup_auths (struct ast_sip_auth * auths[], size_t num_auths)
Clean up retrieved auth structures from memory.
Call this function once you have completed operating on auths retrieved from ast_sip_retrieve_auths
Parameters
auths An array of auth object pointers to clean up
num_auths The number of auths in the array
Definition at line 2377 of file pjsip_configuration.c.
References ao2_cleanup.
Referenced by digest_check_auth(), and set_outbound_initial_authentication_credentials().
 {
    int i;
    for (i = 0; i < num_auths; ++i) {
       ao2_cleanup(auths[i]);
    }
 }
ast_sip_contact_to_str()
int ast_sip_contact_to_str (void * object, void * arg, int flags)
Handler used to convert a contact to a string.
Parameters
object the ast_sip_aor_contact_pair containing a list of contacts to iterate and the contact
arg user data passed to handler
flags
Return values
0 Success, non-zero on failure
Definition at line 767 of file location.c.
References ast_str_append(), buf, and ast_sip_contact_wrapper::contact_id.
Referenced by contacts_to_str(), sip_contact_to_str(), and sip_endpoints_aors_ami().
 {
    struct ast_sip_contact_wrapper *wrapper = object;
    struct ast_str **buf = arg;
    ast_str_append(buf, 0, "%s,", wrapper->contact_id);
    return 0;
 }
ast_sip_create_ami_event()
struct ast_str* ast_sip_create_ami_event (const char * event, struct ast_sip_ami * ami)
Creates a string to store AMI event data in.
Parameters
event the event to set
ami AMI session and message container
Return values
an initialized ast_str or NULL on error.
Definition at line 1584 of file pjsip_configuration.c.
References ast_sip_ami::action_id, AMI_DEFAULT_STR_SIZE, ast_str_append(), ast_str_create, ast_str_set(), ast_strlen_zero, astman_send_error_va(), buf, ast_sip_ami::m, NULL, and ast_sip_ami::s.
Referenced by ami_outbound_registration_task(), ami_registrations_aor(), ami_subscription_detail(), ast_sip_format_contact_ami(), format_ami_aor_handler(), format_ami_aorlist_handler(), format_ami_auth_handler(), format_ami_authlist_handler(), format_ami_contactlist_handler(), format_ami_endpoint(), format_ami_endpoint_transport(), format_ami_endpoints(), format_ami_resource_lists(), and send_identify_ami_event().
 {
    struct ast_str *buf = ast_str_create(AMI_DEFAULT_STR_SIZE);
    if (!(buf)) {
       astman_send_error_va(ami->s, ami->m, "Unable create event "
                  "for %s\n", event);
       return NULL;
    }
    ast_str_set(&buf, 0, "Event: %s\r\n", event);
    if (!ast_strlen_zero(ami->action_id)) {
       ast_str_append(&buf, 0, "ActionID: %s\r\n", ami->action_id);
    }
    return buf;
 }
ast_sip_create_dialog_uac()
pjsip_dialog* ast_sip_create_dialog_uac (const struct ast_sip_endpoint * endpoint, const char * aor_name, const char * request_user)
General purpose method for creating a UAC dialog with an endpoint.
Parameters
endpoint A pointer to the endpoint
aor_name Optional name of the AOR to target, may even be an explicit SIP URI
request_user Optional user to place into the target URI
Return values
non-NULL success
NULL failure
Definition at line 4028 of file res_pjsip.c.
References ast_log, ast_sip_add_usereqphone(), ast_sip_dlg_set_transport(), ast_sip_tpselector_unref(), ast_sorcery_object_get_id(), ast_strlen_zero, ast_sip_endpoint::contact_user, ast_sip_endpoint::fromdomain, ast_sip_endpoint::fromuser, ast_sip_endpoint::info, LOG_ERROR, NULL, ast_sip_endpoint::outbound_proxy, sip_dialog_create_from(), and tmp().
Referenced by ast_sip_create_subscription(), and ast_sip_session_create_outgoing().
 {
    char enclosed_uri[PJSIP_MAX_URL_SIZE];
    pj_str_t local_uri = { "sip:temp@temp", 13 }, remote_uri, target_uri;
    pj_status_t res;
    pjsip_dialog *dlg = NULL;
    const char *outbound_proxy = endpoint->outbound_proxy;
    pjsip_tpselector selector = { .type = PJSIP_TPSELECTOR_NONE, };
    static const pj_str_t HCONTACT = { "Contact", 7 };
    snprintf(enclosed_uri, sizeof(enclosed_uri), "<%s>", uri);
    pj_cstr(&remote_uri, enclosed_uri);
    pj_cstr(&target_uri, uri);
    res = pjsip_dlg_create_uac(pjsip_ua_instance(), &local_uri, NULL, &remote_uri, &target_uri, &dlg);
    if (res == PJ_SUCCESS && !(PJSIP_URI_SCHEME_IS_SIP(dlg->target) || PJSIP_URI_SCHEME_IS_SIPS(dlg->target))) {
       /* dlg->target is a pjsip_other_uri, but it's assumed to be a
        * pjsip_sip_uri below. Fail fast. */
       res = PJSIP_EINVALIDURI;
       pjsip_dlg_terminate(dlg);
    }
    if (res != PJ_SUCCESS) {
       if (res == PJSIP_EINVALIDURI) {
          ast_log(LOG_ERROR,
             "Endpoint '%s': Could not create dialog to invalid URI '%s'.  Is endpoint registered and reachable?\n",
             ast_sorcery_object_get_id(endpoint), uri);
       }
       return NULL;
    }
    /* We have to temporarily bump up the sess_count here so the dialog is not prematurely destroyed */
    dlg->sess_count++;
    ast_sip_dlg_set_transport(endpoint, dlg, &selector);
    if (sip_dialog_create_from(dlg->pool, &local_uri, endpoint->fromuser, endpoint->fromdomain, &remote_uri, &selector)) {
       dlg->sess_count--;
       pjsip_dlg_terminate(dlg);
       ast_sip_tpselector_unref(&selector);
       return NULL;
    }
    ast_sip_tpselector_unref(&selector);
    /* Update the dialog with the new local URI, we do it afterwards so we can use the dialog pool for construction */
    pj_strdup_with_null(dlg->pool, &dlg->local.info_str, &local_uri);
    dlg->local.info->uri = pjsip_parse_uri(dlg->pool, dlg->local.info_str.ptr, dlg->local.info_str.slen, 0);
    if (!dlg->local.info->uri) {
       ast_log(LOG_ERROR,
          "Could not parse URI '%s' for endpoint '%s'\n",
          dlg->local.info_str.ptr, ast_sorcery_object_get_id(endpoint));
       dlg->sess_count--;
       pjsip_dlg_terminate(dlg);
       return NULL;
    }
    dlg->local.contact = pjsip_parse_hdr(dlg->pool, &HCONTACT, local_uri.ptr, local_uri.slen, NULL);
    if (!ast_strlen_zero(endpoint->contact_user)) {
       pjsip_sip_uri *sip_uri;
       sip_uri = pjsip_uri_get_uri(dlg->local.contact->uri);
       pj_strdup2(dlg->pool, &sip_uri->user, endpoint->contact_user);
    }
    /* If a request user has been specified and we are permitted to change it, do so */
    if (!ast_strlen_zero(request_user)) {
       pjsip_sip_uri *sip_uri;
       if (PJSIP_URI_SCHEME_IS_SIP(dlg->target) || PJSIP_URI_SCHEME_IS_SIPS(dlg->target)) {
          sip_uri = pjsip_uri_get_uri(dlg->target);
          pj_strdup2(dlg->pool, &sip_uri->user, request_user);
       }
       if (PJSIP_URI_SCHEME_IS_SIP(dlg->remote.info->uri) || PJSIP_URI_SCHEME_IS_SIPS(dlg->remote.info->uri)) {
          sip_uri = pjsip_uri_get_uri(dlg->remote.info->uri);
          pj_strdup2(dlg->pool, &sip_uri->user, request_user);
       }
    }
    /* Add the user=phone parameter if applicable */
    ast_sip_add_usereqphone(endpoint, dlg->pool, dlg->target);
    ast_sip_add_usereqphone(endpoint, dlg->pool, dlg->remote.info->uri);
    if (!ast_strlen_zero(outbound_proxy)) {
       pjsip_route_hdr route_set, *route;
       static const pj_str_t ROUTE_HNAME = { "Route", 5 };
       pj_str_t tmp;
       pj_list_init(&route_set);
       pj_strdup2_with_null(dlg->pool, &tmp, outbound_proxy);
       if (!(route = pjsip_parse_hdr(dlg->pool, &ROUTE_HNAME, tmp.ptr, tmp.slen, NULL))) {
          ast_log(LOG_ERROR, "Could not create dialog to endpoint '%s' as outbound proxy URI '%s' is not valid\n",
             ast_sorcery_object_get_id(endpoint), outbound_proxy);
          dlg->sess_count--;
          pjsip_dlg_terminate(dlg);
          return NULL;
       }
       pj_list_insert_nodes_before(&route_set, route);
       pjsip_dlg_set_route_set(dlg, &route_set);
    }
    dlg->sess_count--;
    return dlg;
 }
ast_sip_create_dialog_uas()
pjsip_dialog* ast_sip_create_dialog_uas (const struct ast_sip_endpoint * endpoint, pjsip_rx_data * rdata, pj_status_t * status)
General purpose method for creating a UAS dialog with an endpoint.
Deprecated:
This function is unsafe (due to the returned object not being locked nor having its reference incremented) and should no longer be used. Instead use ast_sip_create_dialog_uas_locked so a properly locked and referenced object is returned.
Parameters
endpoint A pointer to the endpoint
rdata The request that is starting the dialog
[out] status On failure, the reason for failure in creating the dialog
Definition at line 4233 of file res_pjsip.c.
References create_dialog_uas().
 {
 #ifdef HAVE_PJSIP_DLG_CREATE_UAS_AND_INC_LOCK
    pjsip_dialog *dlg;
    dlg = create_dialog_uas(endpoint, rdata, status, pjsip_dlg_create_uas_and_inc_lock);
    if (dlg) {
       pjsip_dlg_dec_lock(dlg);
    }
    return dlg;
 #else
    return create_dialog_uas(endpoint, rdata, status, pjsip_dlg_create_uas);
 #endif
 }
ast_sip_create_dialog_uas_locked()
pjsip_dialog* ast_sip_create_dialog_uas_locked (const struct ast_sip_endpoint * endpoint, pjsip_rx_data * rdata, pj_status_t * status)
General purpose method for creating a UAS dialog with an endpoint.
This function creates and returns a locked, and referenced counted pjsip dialog object. The caller is thus responsible for freeing the allocated memory, decrementing the reference, and releasing the lock when done with the returned object.
Note
The safest way to unlock the object, and decrement its reference is by calling pjsip_dlg_dec_lock. Alternatively, pjsip_dlg_dec_session can be used to decrement the reference only.
The dialog is returned locked and with a reference in order to ensure that the dialog object, and any of its associated objects (e.g. transaction) are not untimely destroyed. For instance, that could happen when a transport error occurs.
As long as the caller maintains a reference to the dialog there should be no worry that it might unknowningly be destroyed. However, once the caller unlocks the dialog there is a danger that some of the dialog's internal objects could be lost and/or compromised. For example, when the aforementioned transport error occurs the dialog's associated transaction gets destroyed (see pjsip_dlg_on_tsx_state in sip_dialog.c, and mod_inv_on_tsx_state in sip_inv.c).
In this case and before using the dialog again the caller should re-lock the dialog, check to make sure the dialog is still established, and the transaction still exists and has not been destroyed.
Parameters
endpoint A pointer to the endpoint
rdata The request that is starting the dialog
[out] status On failure, the reason for failure in creating the dialog
Return values
A locked, and reference counted pjsip_dialog object.
NULL on failure
Definition at line 4249 of file res_pjsip.c.
References create_dialog_uas().
Referenced by create_subscription_tree(), and pre_session_setup().
 {
 #ifdef HAVE_PJSIP_DLG_CREATE_UAS_AND_INC_LOCK
    return create_dialog_uas(endpoint, rdata, status, pjsip_dlg_create_uas_and_inc_lock);
 #else
    /*
     * This is put here in order to be compatible with older versions of pjproject.
     * Best we can do in this case is immediately lock after getting the dialog.
     * However, that does leave a "gap" between creating and locking.
     */
    pjsip_dialog *dlg;
    dlg = create_dialog_uas(endpoint, rdata, status, pjsip_dlg_create_uas);
    if (dlg) {
       pjsip_dlg_inc_lock(dlg);
    }
    return dlg;
 #endif
  }
ast_sip_create_rdata()
int ast_sip_create_rdata (pjsip_rx_data * rdata, char * packet, const char * src_name, int src_port, char * transport_type, const char * local_name, int local_port)
General purpose method for creating an rdata structure using specific information.
Parameters
rdata[out] The rdata structure that will be populated
packet A SIP message
src_name The source IP address of the message
src_port The source port of the message
transport_type The type of transport the message was received on
local_name The local IP address the message was received on
local_port The local port the message was received on
Return values
0 success
-1 failure
Definition at line 4323 of file res_pjsip.c.
References ast_sip_create_rdata_with_contact(), and NULL.
 {
    return ast_sip_create_rdata_with_contact(rdata, packet, src_name, src_port, transport_type,
       local_name, local_port, NULL);
 }
ast_sip_create_rdata_with_contact()
int ast_sip_create_rdata_with_contact (pjsip_rx_data * rdata, char * packet, const char * src_name, int src_port, char * transport_type, const char * local_name, int local_port, const char * contact_uri)
General purpose method for creating an rdata structure using specific information.
Since
13.15.0
Parameters
rdata[out] The rdata structure that will be populated
packet A SIP message
src_name The source IP address of the message
src_port The source port of the message
transport_type The type of transport the message was received on
local_name The local IP address the message was received on
local_port The local port the message was received on
contact_uri The contact URI of the message
Return values
0 success
-1 failure
Definition at line 4271 of file res_pjsip.c.
References ast_copy_string(), ast_log, ast_strlen_zero, LOG_WARNING, NULL, and tmp().
Referenced by ast_sip_create_rdata(), and subscription_persistence_recreate().
 {
    pj_str_t tmp;
    /*
     * Initialize the error list in case there is a parse error
     * in the given packet.
     */
    pj_list_init(&rdata->msg_info.parse_err);
    rdata->tp_info.transport = PJ_POOL_ZALLOC_T(rdata->tp_info.pool, pjsip_transport);
    if (!rdata->tp_info.transport) {
       return -1;
    }
    ast_copy_string(rdata->pkt_info.packet, packet, sizeof(rdata->pkt_info.packet));
    ast_copy_string(rdata->pkt_info.src_name, src_name, sizeof(rdata->pkt_info.src_name));
    rdata->pkt_info.src_port = src_port;
    pj_sockaddr_parse(pj_AF_UNSPEC(), 0, pj_cstr(&tmp, src_name), &rdata->pkt_info.src_addr);
    pj_sockaddr_set_port(&rdata->pkt_info.src_addr, src_port);
    pjsip_parse_rdata(packet, strlen(packet), rdata);
    if (!rdata->msg_info.msg || !pj_list_empty(&rdata->msg_info.parse_err)) {
       return -1;
    }
    if (!ast_strlen_zero(contact)) {
       pjsip_contact_hdr *contact_hdr;
       contact_hdr = pjsip_msg_find_hdr(rdata->msg_info.msg, PJSIP_H_CONTACT, NULL);
       if (contact_hdr) {
          contact_hdr->uri = pjsip_parse_uri(rdata->tp_info.pool, (char *)contact,
             strlen(contact), PJSIP_PARSE_URI_AS_NAMEADDR);
          if (!contact_hdr->uri) {
             ast_log(LOG_WARNING, "Unable to parse contact URI from '%s'.\n", contact);
             return -1;
          }
       }
    }
    pj_strdup2(rdata->tp_info.pool, &rdata->msg_info.via->recvd_param, rdata->pkt_info.src_name);
    rdata->msg_info.via->rport_param = -1;
    rdata->tp_info.transport->key.type = pjsip_transport_get_type_from_name(pj_cstr(&tmp, transport_type));
    rdata->tp_info.transport->type_name = transport_type;
    pj_strdup2(rdata->tp_info.pool, &rdata->tp_info.transport->local_name.host, local_name);
    rdata->tp_info.transport->local_name.port = local_port;
    return 0;
 }
ast_sip_create_request()
int ast_sip_create_request (const char * method, struct pjsip_dialog * dlg, struct ast_sip_endpoint * endpoint, const char * uri, struct ast_sip_contact * contact, pjsip_tx_data ** tdata)
General purpose method for creating a SIP request.
Its typical use would be to create one-off requests such as an out of dialog SIP MESSAGE.
The request can either be in- or out-of-dialog. If in-dialog, the dlg parameter MUST be present. If out-of-dialog the endpoint parameter MUST be present. If both are present, then we will assume that the message is to be sent in-dialog.
The uri parameter can be specified if the request should be sent to an explicit URI rather than one configured on the endpoint.
Parameters
method The method of the SIP request to send
dlg Optional. If specified, the dialog on which to request the message.
endpoint Optional. If specified, the request will be created out-of-dialog to the endpoint.
uri Optional. If specified, the request will be sent to this URI rather than one configured for the endpoint.
contact The contact with which this request is associated for out-of-dialog requests.
[out] tdata The newly-created request
The provided contact is attached to tdata with its reference bumped, but will not survive for the entire lifetime of tdata since the contact is cleaned up when all supplements have completed execution.
Return values
0 Success
-1 Failure
Definition at line 4490 of file res_pjsip.c.
References ast_assert, ast_log, create_in_dialog_request(), create_out_of_dialog_request(), get_pjsip_method(), LOG_WARNING, NULL, and pmethod.
Referenced by msg_send(), notify_channel(), notify_contact(), notify_uri(), send_unsolicited_mwi_notify_to_contact(), sendtext(), sip_options_qualify_contact(), transmit_info_dtmf(), and transmit_info_with_vidupdate().
 {
    const pjsip_method *pmethod = get_pjsip_method(method);
    if (!pmethod) {
       ast_log(LOG_WARNING, "Unknown method '%s'. Cannot send request\n", method);
       return -1;
    }
    if (dlg) {
       return create_in_dialog_request(pmethod, dlg, tdata);
    } else {
       ast_assert(endpoint != NULL);
       return create_out_of_dialog_request(pmethod, endpoint, uri, contact, tdata);
    }
 }
ast_sip_create_request_with_auth()
int ast_sip_create_request_with_auth (const struct ast_sip_auth_vector * auths, pjsip_rx_data * challenge, pjsip_tx_data * tdata, pjsip_tx_data ** new_request)
Create a response to an authentication challenge.
This will call into an outbound authenticator's create_request_with_auth callback to create a new request with authentication credentials. See the create_request_with_auth callback in the ast_sip_outbound_authenticator structure for details about the parameters and return values.
Definition at line 3412 of file res_pjsip.c.
References ast_log, ast_sip_outbound_authenticator::create_request_with_auth, and LOG_WARNING.
Referenced by check_request_status(), handle_registration_response(), outbound_invite_auth(), session_inv_on_tsx_state_changed(), and sip_outbound_publish_callback().
 {
    if (!registered_outbound_authenticator) {
       ast_log(LOG_WARNING, "No SIP outbound authenticator registered. Cannot respond to authentication challenge\n");
       return -1;
    }
    return registered_outbound_authenticator->create_request_with_auth(auths, challenge, old_request, new_request);
 }
ast_sip_create_response()
int ast_sip_create_response (const pjsip_rx_data * rdata, int st_code, struct ast_sip_contact * contact, pjsip_tx_data ** p_tdata)
General purpose method for creating a SIP response.
Its typical use would be to create responses for out of dialog requests.
Parameters
rdata The rdata from the incoming request.
st_code The response code to transmit.
contact The contact with which this request is associated.
[out] tdata The newly-created response
The provided contact is attached to tdata with its reference bumped, but will not survive for the entire lifetime of tdata since the contact is cleaned up when all supplements have completed execution.
Return values
0 Success
-1 Failure
Definition at line 5448 of file res_pjsip.c.
References ao2_bump, ast_sip_get_pjsip_endpoint(), ast_sip_mod_data_set, MOD_DATA_CONTACT, NULL, and supplement_module.
Referenced by register_aor_core(), send_options_response(), and send_response().
 {
    int res = pjsip_endpt_create_response(ast_sip_get_pjsip_endpoint(), rdata, st_code, NULL, tdata);
    if (!res) {
       ast_sip_mod_data_set((*tdata)->pool, (*tdata)->mod_data, supplement_module.id, MOD_DATA_CONTACT, ao2_bump(contact));
    }
    return res;
 }
ast_sip_default_outbound_endpoint()
struct ast_sip_endpoint* ast_sip_default_outbound_endpoint (void)
Retrieve the default outbound endpoint.
Return values
The default outbound endpoint, NULL if not found.
Definition at line 2353 of file pjsip_configuration.c.
References ast_free, ast_sip_global_default_outbound_endpoint(), ast_sorcery_retrieve_by_id(), ast_strlen_zero, name, NULL, and RAII_VAR.
Referenced by get_outbound_endpoint(), handle_atsign(), handle_single_token(), and notify_uri().
 {
    RAII_VAR(char *, name, ast_sip_global_default_outbound_endpoint(), ast_free);
    return ast_strlen_zero(name) ? NULL : ast_sorcery_retrieve_by_id(
       sip_sorcery, "endpoint", name);
 }
ast_sip_dialog_setup_outbound_authentication()
int ast_sip_dialog_setup_outbound_authentication (pjsip_dialog * dlg, const struct ast_sip_endpoint * endpoint, ast_sip_dialog_outbound_auth_cb cb, void * user_data)
Set up outbound authentication on a SIP dialog.
This sets up the infrastructure so that all requests associated with a created dialog can be re-sent with authentication credentials if the original request is challenged.
Parameters
dlg The dialog on which requests will be authenticated
endpoint The endpoint whom this dialog pertains to
cb Callback to call to send requests with authentication
user_data Data to be provided to the callback when it is called
Return values
0 Success
-1 Failure
ast_sip_dict_get()
void* ast_sip_dict_get (void * ht, const char * key)
Retrieves the value associated with the given key.
Parameters
ht the hash table/dictionary to search
key the key to find
Return values
the value associated with the key, NULL otherwise.
Definition at line 5338 of file res_pjsip.c.
References NULL.
 {
    unsigned int hval = 0;
    if (!ht) {
       return NULL;
    }
    return pj_hash_get(ht, key, PJ_HASH_KEY_STRING, &hval);
 }
ast_sip_dict_set()
void* ast_sip_dict_set (pj_pool_t * pool, void * ht, const char * key, void * val)
Set the value for the given key.
Note - if the hash table does not exist one is created first, the key/value pair is set, and the hash table returned.
Parameters
pool the pool to allocate memory in
ht the hash table/dictionary in which to store the key/value pair
key the key to associate a value with
val the value to associate with a key
Return values
the given, or newly created, hash table.
Definition at line 5349 of file res_pjsip.c.
 {
    if (!ht) {
       ht = pj_hash_create(pool, 11);
    }
    pj_hash_set(pool, ht, key, PJ_HASH_KEY_STRING, 0, val);
    return ht;
 }
ast_sip_dlg_set_transport()
int ast_sip_dlg_set_transport (const struct ast_sip_endpoint * endpoint, pjsip_dialog * dlg, pjsip_tpselector * selector)
Set the transport on a dialog.
Since
13.15.0
Parameters
endpoint
dlg
selector (optional)
Note
This API calls ast_sip_get_transport_name(endpoint, dlg->target) and if the result is non-NULL, calls pjsip_dlg_set_transport. If 'selector' is non-NULL, it is updated with the selector used.
It is the responsibility of the caller to unref the passed in selector if one is provided.
Definition at line 3791 of file res_pjsip.c.
References ast_sip_set_tpselector_from_ep_or_uri(), and ast_sip_tpselector_unref().
Referenced by ast_sip_create_dialog_uac().
 {
    pjsip_sip_uri *uri;
    pjsip_tpselector sel = { .type = PJSIP_TPSELECTOR_NONE, };
    uri = pjsip_uri_get_uri(dlg->target);
    if (!selector) {
       selector = &sel;
    }
    ast_sip_set_tpselector_from_ep_or_uri(endpoint, uri, selector);
    pjsip_dlg_set_transport(dlg, selector);
    if (selector == &sel) {
       ast_sip_tpselector_unref(&sel);
    }
    return 0;
 }
ast_sip_dtmf_to_str()
int ast_sip_dtmf_to_str (const enum ast_sip_dtmf_mode dtmf, char * buf, size_t buf_len)
Convert the DTMF mode enum value into a string.
Since
13.18.0
Parameters
dtmf the dtmf mode
buf Buffer to receive dtmf mode string
buf_len Buffer length
Return values
0 Success
-1 Failure
Definition at line 5484 of file res_pjsip.c.
References ast_copy_string(), AST_SIP_DTMF_AUTO, AST_SIP_DTMF_AUTO_INFO, AST_SIP_DTMF_INBAND, AST_SIP_DTMF_INFO, AST_SIP_DTMF_NONE, and AST_SIP_DTMF_RFC_4733.
Referenced by dtmf_to_str(), and pjsip_acf_dtmf_mode_read().
 {
    switch (dtmf) {
    case AST_SIP_DTMF_NONE:
       ast_copy_string(buf, "none", buf_len);
       break;
    case AST_SIP_DTMF_RFC_4733:
       ast_copy_string(buf, "rfc4733", buf_len);
       break;
    case AST_SIP_DTMF_INBAND:
       ast_copy_string(buf, "inband", buf_len);
       break;
    case AST_SIP_DTMF_INFO:
       ast_copy_string(buf, "info", buf_len);
       break;
    case AST_SIP_DTMF_AUTO:
       ast_copy_string(buf, "auto", buf_len);
       break;
    case AST_SIP_DTMF_AUTO_INFO:
       ast_copy_string(buf, "auto_info", buf_len);
       break;
    default:
       buf[0] = '\0';
       return -1;
    }
    return 0;
 }
ast_sip_endpoint_alloc()
void* ast_sip_endpoint_alloc (const char * name)
Allocate a new SIP endpoint.
This will return an endpoint with its refcount increased by one. This reference can be released using ao2_ref().
Parameters
name The name of the endpoint.
Return values
NULL Endpoint allocation failed
non-NULL The newly allocated endpoint
Definition at line 2306 of file pjsip_configuration.c.
References ao2_cleanup, ast_format_cap_alloc, AST_FORMAT_CAP_FLAG_DEFAULT, ast_party_id_init(), ast_sorcery_generic_alloc(), ast_strdup, ast_string_field_init, AST_VECTOR_INIT, ast_sip_endpoint_media_configuration::codecs, sip_persistent_endpoint::endpoint, endpoint_destructor(), ast_sip_endpoint::id, ast_sip_endpoint::ident_method_order, ast_sip_endpoint::info, init_info_configuration(), init_media_configuration(), init_subscription_configuration(), ast_sip_endpoint::media, NULL, ast_sip_endpoint_id_configuration::self, ast_sip_endpoint::subscription, and ast_party_id::tag.
Referenced by ast_res_pjsip_initialize_configuration().
 {
    struct ast_sip_endpoint *endpoint = ast_sorcery_generic_alloc(sizeof(*endpoint), endpoint_destructor);
    if (!endpoint) {
       return NULL;
    }
    if (ast_string_field_init(endpoint, 64)) {
       ao2_cleanup(endpoint);
       return NULL;
    }
    if (!(endpoint->media.codecs = ast_format_cap_alloc(AST_FORMAT_CAP_FLAG_DEFAULT))) {
       ao2_cleanup(endpoint);
       return NULL;
    }
    if (init_subscription_configuration(&endpoint->subscription)) {
       ao2_cleanup(endpoint);
       return NULL;
    }
    if (init_info_configuration(&endpoint->info)) {
       ao2_cleanup(endpoint);
       return NULL;
    }
    if (init_media_configuration(&endpoint->media)) {
       ao2_cleanup(endpoint);
       return NULL;
    }
    ast_party_id_init(&endpoint->id.self);
    endpoint->id.self.tag = ast_strdup("");
    if (AST_VECTOR_INIT(&endpoint->ident_method_order, 1)) {
       return NULL;
    }
    return endpoint;
 }
ast_sip_failover_request()
int ast_sip_failover_request (pjsip_tx_data * tdata)
Set a request to use the next value in the list of resolved addresses.
Parameters
tdata the tx data from the original request
Return values
0 No more addresses to try
1 The request was successfully re-intialized
Definition at line 4871 of file res_pjsip.c.
References NULL, and send_request_cb().
Referenced by check_request_status(), and handle_registration_response().
 {
    pjsip_via_hdr *via;
    if (!tdata || !tdata->dest_info.addr.count
       || (tdata->dest_info.cur_addr == tdata->dest_info.addr.count - 1)) {
       /* No more addresses to try */
       return 0;
    }
    /* Try next address */
    ++tdata->dest_info.cur_addr;
    via = (pjsip_via_hdr*)pjsip_msg_find_hdr(tdata->msg, PJSIP_H_VIA, NULL);
    via->branch_param.slen = 0;
    pjsip_tx_data_invalidate_msg(tdata);
    return 1;
 }
ast_sip_for_each_aor()
int ast_sip_for_each_aor (const char * aors, ao2_callback_fn on_aor, void * arg)
For every aor in the comma separated aors string call the given 'on_aor' handler.
Parameters
aors a comma separated list of aors
on_aor callback for each aor
arg user data passed to handler
Return values
0 Success, non-zero on failure
Definition at line 684 of file location.c.
References ao2_ref, ast_sip_location_retrieve_aor(), ast_strdupa, ast_strip(), ast_strlen_zero, copy(), name, and strsep().
Referenced by ami_registrations_endpoint(), ast_sip_location_retrieve_contacts_from_aor_list(), cli_aor_iterate(), format_ami_contact_status(), format_ami_endpoint_aor(), format_ami_endpoints(), mwi_new_subscribe(), and mwi_subscribe_all().
 {
    char *copy;
    char *name;
    int res;
    if (!on_aor || ast_strlen_zero(aors)) {
       return 0;
    }
    copy = ast_strdupa(aors);
    while ((name = ast_strip(strsep(&copy, ",")))) {
       struct ast_sip_aor *aor;
       aor = ast_sip_location_retrieve_aor(name);
       if (aor) {
          res = on_aor(aor, arg, 0);
          ao2_ref(aor, -1);
          if (res) {
             return -1;
          }
       }
    }
    return 0;
 }
ast_sip_for_each_auth()
int ast_sip_for_each_auth (const struct ast_sip_auth_vector * array, ao2_callback_fn on_auth, void * arg)
For every auth in the array call the given 'on_auth' handler.
Parameters
array an array of auths
on_auth callback for each auth
arg user data passed to handler
Return values
0 Success, non-zero on failure
Definition at line 135 of file config_auth.c.
References ao2_cleanup, ast_sip_get_sorcery(), ast_sorcery_retrieve_by_id(), AST_VECTOR_GET, AST_VECTOR_SIZE, and RAII_VAR.
Referenced by ast_sip_format_auths_ami(), and cli_iterator().
 {
    int i;
    if (!vector || !AST_VECTOR_SIZE(vector)) {
       return 0;
    }
    for (i = 0; i < AST_VECTOR_SIZE(vector); ++i) {
       /* AST_VECTOR_GET is safe to use since the vector is immutable */
       RAII_VAR(struct ast_sip_auth *, auth, ast_sorcery_retrieve_by_id(
              ast_sip_get_sorcery(), SIP_SORCERY_AUTH_TYPE,
              AST_VECTOR_GET(vector,i)), ao2_cleanup);
       if (!auth) {
          continue;
       }
       if (on_auth(auth, arg, 0)) {
          return -1;
       }
    }
    return 0;
 }
ast_sip_for_each_channel()
int ast_sip_for_each_channel (const struct ast_sip_endpoint * endpoint, ao2_callback_fn on_channel_snapshot, void * arg)
For every channel snapshot on an endpoint all the given 'on_channel_snapshot' handler.
Parameters
endpoint endpoint
on_channel_snapshot callback for each channel snapshot
arg user data passed to handler
Return values
0 Success, non-zero on failure
Definition at line 1550 of file pjsip_configuration.c.
References ao2_cleanup, ast_sip_for_each_channel_snapshot(), ast_sip_get_endpoint_snapshot(), and RAII_VAR.
Referenced by cli_channel_iterate(), and cli_channelstats_iterate().
 {
    RAII_VAR(struct ast_endpoint_snapshot *, endpoint_snapshot, ast_sip_get_endpoint_snapshot(endpoint), ao2_cleanup);
    return ast_sip_for_each_channel_snapshot(endpoint_snapshot, on_channel_snapshot, arg);
 }
ast_sip_for_each_channel_snapshot()
int ast_sip_for_each_channel_snapshot (const struct ast_endpoint_snapshot * endpoint_snapshot, ao2_callback_fn on_channel_snapshot, void * arg)
For every channel snapshot on an endpoint snapshot call the given 'on_channel_snapshot' handler.
Parameters
endpoint_snapshot snapshot of an endpoint
on_channel_snapshot callback for each channel snapshot
arg user data passed to handler
Return values
0 Success, non-zero on failure
Definition at line 1523 of file pjsip_configuration.c.
References ao2_cleanup, ast_channel_snapshot_get_latest(), ast_endpoint_snapshot::channel_ids, NULL, ast_endpoint_snapshot::num_channels, and RAII_VAR.
Referenced by active_channels_to_str(), and ast_sip_for_each_channel().
 {
    int num, num_channels = endpoint_snapshot->num_channels;
    if (!on_channel_snapshot || !num_channels) {
       return 0;
    }
    for (num = 0; num < num_channels; ++num) {
       RAII_VAR(struct ast_channel_snapshot *, snapshot, NULL, ao2_cleanup);
       int res;
       snapshot = ast_channel_snapshot_get_latest(endpoint_snapshot->channel_ids[num]);
       if (!snapshot) {
          continue;
       }
       res = on_channel_snapshot(snapshot, arg, 0);
       if (res) {
          return -1;
       }
    }
    return 0;
 }
ast_sip_for_each_contact()
int ast_sip_for_each_contact (const struct ast_sip_aor * aor, ao2_callback_fn on_contact, void * arg)
For every contact on an AOR call the given 'on_contact' handler.
Parameters
aor the aor containing a list of contacts to iterate
on_contact callback on each contact on an AOR. The object received by the callback will be a ast_sip_contact_wrapper structure.
arg user data passed to handler
Return values
0 Success, non-zero on failure
Definition at line 719 of file location.c.
References AO2_ALLOC_OPT_LOCK_NOLOCK, ao2_alloc_options, ao2_bump, ao2_cleanup, ao2_iterator_destroy(), ao2_iterator_init(), ao2_iterator_next, ao2_ref, ast_malloc, ast_sip_location_retrieve_aor_contacts(), ast_sorcery_object_get_id(), ast_strdup, contact_wrapper_destroy(), NULL, and RAII_VAR.
Referenced by ami_registrations_aor(), cli_aor_gather_contacts(), cli_contact_iterate(), contacts_to_str(), contacts_to_var_list(), format_contact_status_for_aor(), and sip_endpoints_aors_ami().
 {
    struct ao2_container *contacts;
    struct ao2_iterator i;
    int res = 0;
    void *object = NULL;
    if (!on_contact ||
        !(contacts = ast_sip_location_retrieve_aor_contacts(aor))) {
       return 0;
    }
    i = ao2_iterator_init(contacts, 0);
    while ((object = ao2_iterator_next(&i))) {
       RAII_VAR(struct ast_sip_contact *, contact, object, ao2_cleanup);
       RAII_VAR(struct ast_sip_contact_wrapper *, wrapper, NULL, ao2_cleanup);
       const char *aor_id = ast_sorcery_object_get_id(aor);
       wrapper = ao2_alloc_options(sizeof(struct ast_sip_contact_wrapper),
          contact_wrapper_destroy, AO2_ALLOC_OPT_LOCK_NOLOCK);
       if (!wrapper) {
          res = -1;
          break;
       }
       wrapper->contact_id = ast_malloc(strlen(aor_id) + strlen(contact->uri) + 2);
       if (!wrapper->contact_id) {
          res = -1;
          break;
       }
       sprintf(wrapper->contact_id, "%s/%s", aor_id, contact->uri);
       wrapper->aor_id = ast_strdup(aor_id);
       if (!wrapper->aor_id) {
          res = -1;
          break;
       }
       wrapper->contact = contact;
       ao2_bump(wrapper->contact);
       if ((res = on_contact(wrapper, arg, 0))) {
          break;
       }
    }
    ao2_iterator_destroy(&i);
    ao2_ref(contacts, -1);
    return res;
 }
ast_sip_format_auths_ami()
int ast_sip_format_auths_ami (const struct ast_sip_auth_vector * auths, struct ast_sip_ami * ami)
Format auth details for AMI.
Parameters
auths an auth array
ami ami variable container
Return values
0 Success, non-zero on failure
Definition at line 195 of file config_auth.c.
References ast_sip_for_each_auth(), and format_ami_auth_handler().
Referenced by ami_outbound_registration_task(), and format_ami_endpoint_auth().
 {
    return ast_sip_for_each_auth(auths, format_ami_auth_handler, ami);
 }
ast_sip_format_contact_ami()
int ast_sip_format_contact_ami (void * obj, void * arg, int flags)
Formats the contact and sends over AMI.
Parameters
obj a pointer an ast_sip_contact_wrapper structure
arg a pointer to an ast_sip_ami structure
flags ignored
Return values
0 Success, otherwise non-zero on error
Definition at line 2717 of file pjsip_options.c.
References ao2_cleanup, ast_sip_contact_wrapper::aor_id, ast_sip_ami::arg, ast_free, ast_sip_create_ami_event(), ast_sip_get_contact_status(), ast_sip_get_contact_status_label(), ast_sorcery_object_get_id(), ast_str_append(), ast_str_buffer(), ast_strlen_zero, astman_append(), ast_sip_contact::authenticate_qualify, AVAILABLE, buf, ast_sip_contact::call_id, ast_sip_contact_wrapper::contact, ast_sip_ami::count, ast_sip_contact::endpoint_name, ast_sip_contact::expiration_time, ast_sip_contact::outbound_proxy, ast_sip_contact::path, ast_sip_contact::qualify_frequency, ast_sip_contact::qualify_timeout, ast_sip_contact_status::rtt, ast_sip_ami::s, S_OR, status, ast_sip_contact_status::status, UNKNOWN, ast_sip_contact::uri, ast_sip_contact::user_agent, ast_sip_contact::via_addr, and ast_sip_contact::via_port.
Referenced by ami_show_registration_contact_statuses(), and format_contact_status_for_aor().
 {
    struct ast_sip_contact_wrapper *wrapper = obj;
    struct ast_sip_contact *contact = wrapper->contact;
    struct ast_sip_ami *ami = arg;
    struct ast_sip_contact_status *status;
    struct ast_str *buf;
    const struct ast_sip_endpoint *endpoint = ami->arg;
    buf = ast_sip_create_ami_event("ContactStatusDetail", ami);
    if (!buf) {
       return -1;
    }
    status = ast_sip_get_contact_status(contact);
    ast_str_append(&buf, 0, "AOR: %s\r\n", wrapper->aor_id);
    ast_str_append(&buf, 0, "URI: %s\r\n", contact->uri);
    ast_str_append(&buf, 0, "UserAgent: %s\r\n", contact->user_agent);
    ast_str_append(&buf, 0, "RegExpire: %ld\r\n", contact->expiration_time.tv_sec);
    if (!ast_strlen_zero(contact->via_addr)) {
       ast_str_append(&buf, 0, "ViaAddress: %s", contact->via_addr);
       if (contact->via_port) {
          ast_str_append(&buf, 0, ":%d", contact->via_port);
       }
       ast_str_append(&buf, 0, "\r\n");
    }
    if (!ast_strlen_zero(contact->call_id)) {
       ast_str_append(&buf, 0, "CallID: %s\r\n", contact->call_id);
    }
    ast_str_append(&buf, 0, "Status: %s\r\n",
       ast_sip_get_contact_status_label(status ? status->status : UNKNOWN));
    if (!status || status->status != AVAILABLE) {
       ast_str_append(&buf, 0, "RoundtripUsec: N/A\r\n");
    } else {
       ast_str_append(&buf, 0, "RoundtripUsec: %" PRId64 "\r\n", status->rtt);
    }
    ast_str_append(&buf, 0, "EndpointName: %s\r\n",
       endpoint ? ast_sorcery_object_get_id(endpoint) : S_OR(contact->endpoint_name, ""));
    ast_str_append(&buf, 0, "ID: %s\r\n", ast_sorcery_object_get_id(contact));
    ast_str_append(&buf, 0, "AuthenticateQualify: %d\r\n", contact->authenticate_qualify);
    ast_str_append(&buf, 0, "OutboundProxy: %s\r\n", contact->outbound_proxy);
    ast_str_append(&buf, 0, "Path: %s\r\n", contact->path);
    ast_str_append(&buf, 0, "QualifyFrequency: %u\r\n", contact->qualify_frequency);
    ast_str_append(&buf, 0, "QualifyTimeout: %.3f\r\n", contact->qualify_timeout);
    astman_append(ami->s, "%s\r\n", ast_str_buffer(buf));
    ami->count++;
    ast_free(buf);
    ao2_cleanup(status);
    return 0;
 }
ast_sip_format_endpoint_ami()
int ast_sip_format_endpoint_ami (struct ast_sip_endpoint * endpoint, struct ast_sip_ami * ami, int * count)
Formats the endpoint and sends over AMI.
Parameters
endpoint the endpoint to format and send
endpoint ami AMI variable container
count the number of formatters operated on
Return values
0 Success, otherwise non-zero on error
Definition at line 3699 of file res_pjsip.c.
References AST_RWLIST_RDLOCK, AST_RWLIST_TRAVERSE, AST_RWLIST_UNLOCK, ast_sip_endpoint_formatter::format_ami, lock, and SCOPED_LOCK.
Referenced by ami_show_endpoint().
 {
    int res = 0;
    struct ast_sip_endpoint_formatter *i;
    SCOPED_LOCK(lock, &endpoint_formatters, AST_RWLIST_RDLOCK, AST_RWLIST_UNLOCK);
    *count = 0;
    AST_RWLIST_TRAVERSE(&endpoint_formatters, i, next) {
       if (i->format_ami && ((res = i->format_ami(endpoint, ami)) < 0)) {
          return res;
       }
       if (!res) {
          (*count)++;
       }
    }
    return 0;
 }
ast_sip_get_artificial_auth()
struct ast_sip_auth* ast_sip_get_artificial_auth (void)
Retrieves a reference to the artificial auth.
Return values
The artificial auth
Definition at line 631 of file pjsip_distributor.c.
References ao2_global_obj_ref.
Referenced by digest_check_auth(), and global_loaded().
 {
    return ao2_global_obj_ref(artificial_auth);
 }
ast_sip_get_artificial_endpoint()
struct ast_sip_endpoint* ast_sip_get_artificial_endpoint (void)
Retrieves a reference to the artificial endpoint.
Return values
The artificial endpoint
Definition at line 654 of file pjsip_distributor.c.
References ao2_ref, and artificial_endpoint.
Referenced by digest_check_auth(), digest_requires_authentication(), endpoint_lookup(), and get_account_id().
 {
    ao2_ref(artificial_endpoint, +1);
    return artificial_endpoint;
 }
ast_sip_get_contact_expiration_check_interval()
unsigned int ast_sip_get_contact_expiration_check_interval (void)
Retrieve the system contact expiration check interval setting.
Return values
the contact expiration check interval.
Definition at line 309 of file config_global.c.
References ao2_ref, global_config::contact_expiration_check_interval, DEFAULT_CONTACT_EXPIRATION_CHECK_INTERVAL, and get_global_cfg().
Referenced by expiration_global_loaded().
 {
    unsigned int interval;
    struct global_config *cfg;
    cfg = get_global_cfg();
    if (!cfg) {
       return DEFAULT_CONTACT_EXPIRATION_CHECK_INTERVAL;
    }
    interval = cfg->contact_expiration_check_interval;
    ao2_ref(cfg, -1);
    return interval;
 }
ast_sip_get_contact_short_status_label()
const char* ast_sip_get_contact_short_status_label (const enum ast_sip_contact_status_type status)
Definition at line 342 of file pjsip_options.c.
References ARRAY_LEN, ast_assert, short_status_map, and status.
Referenced by cli_contact_print_body().
 {
    ast_assert(0 <= status && status < ARRAY_LEN(short_status_map));
    return short_status_map[status];
 }
ast_sip_get_contact_status()
struct ast_sip_contact_status* ast_sip_get_contact_status (const struct ast_sip_contact * contact)
Retrieve the current status for a contact.
Parameters
contact The contact.
Return values
non-NULL Success
NULL Status information not found
Note
The returned contact status object is immutable.
Definition at line 523 of file pjsip_options.c.
References ao2_find, AO2_STRING_FIELD_CMP_FN(), AO2_STRING_FIELD_HASH_FN(), ast_sorcery_object_get_id(), sip_options_endpoint_aor_status::name, and OBJ_SEARCH_KEY.
Referenced by ast_sip_format_contact_ami(), cli_contact_print_body(), contact_remove_unreachable(), format_ami_contactlist_handler(), pjsip_contact_function_read(), and sip_options_contact_update_task().
 {
    return ao2_find(sip_options_contact_statuses, ast_sorcery_object_get_id(contact),
       OBJ_SEARCH_KEY);
 }
ast_sip_get_contact_status_label()
const char* ast_sip_get_contact_status_label (const enum ast_sip_contact_status_type status)
translate ast_sip_contact_status_type to character string.
Return values
the character string equivalent.
Definition at line 336 of file pjsip_options.c.
References ARRAY_LEN, ast_assert, status, and status_map.
Referenced by ast_res_pjsip_find_or_create_contact_status(), ast_sip_format_contact_ami(), ast_sip_initialize_sorcery_location(), ast_sip_persistent_endpoint_publish_contact_state(), format_ami_contactlist_handler(), pjsip_contact_function_read(), sip_options_contact_status_notify_task(), sip_options_remove_contact_status(), and sip_options_set_contact_status().
 {
    ast_assert(0 <= status && status < ARRAY_LEN(status_map));
    return status_map[status];
 }
ast_sip_get_debug()
char* ast_sip_get_debug (void)
Retrieve the system debug setting (yes|no|host).
Note
returned string needs to be de-allocated by caller.
Return values
the system debug setting.
Definition at line 232 of file config_global.c.
References ao2_ref, ast_strdup, global_config::debug, DEFAULT_DEBUG, and get_global_cfg().
Referenced by check_debug().
 {
    char *res;
    struct global_config *cfg;
    cfg = get_global_cfg();
    if (!cfg) {
       return ast_strdup(DEFAULT_DEBUG);
    }
    res = ast_strdup(cfg->debug);
    ao2_ref(cfg, -1);
    return res;
 }
ast_sip_get_default_from_user()
void ast_sip_get_default_from_user (char * from_user, size_t size)
Retrieve the global default from user.
This is the value placed in outbound requests' From header if there is no better option (such as an endpoint-configured from_user or caller ID number).
Parameters
[out] from_user The default from user
size The buffer size of from_user
Returns
nothing
Definition at line 388 of file config_global.c.
References ao2_ref, ast_copy_string(), DEFAULT_FROM_USER, global_config::default_from_user, and get_global_cfg().
Referenced by sip_dialog_create_from().
 {
    struct global_config *cfg;
    cfg = get_global_cfg();
    if (!cfg) {
       ast_copy_string(from_user, DEFAULT_FROM_USER, size);
    } else {
       ast_copy_string(from_user, cfg->default_from_user, size);
       ao2_ref(cfg, -1);
    }
 }
ast_sip_get_default_realm()
void ast_sip_get_default_realm (char * realm, size_t size)
Retrieve the global default realm.
This is the value placed in outbound challenges' realm if there is no better option (such as an auth-configured realm).
Parameters
[out] realm The default realm
size The buffer size of realm
Returns
nothing
Definition at line 375 of file config_global.c.
References ao2_ref, ast_copy_string(), DEFAULT_REALM, global_config::default_realm, and get_global_cfg().
Referenced by create_artificial_auth(), and global_loaded().
 {
    struct global_config *cfg;
    cfg = get_global_cfg();
    if (!cfg) {
       ast_copy_string(realm, DEFAULT_REALM, size);
    } else {
       ast_copy_string(realm, cfg->default_realm, size);
       ao2_ref(cfg, -1);
    }
 }
ast_sip_get_default_voicemail_extension()
char* ast_sip_get_default_voicemail_extension (void)
Retrieve the default voicemail extension.
Since
13.9.0
Note
returned string needs to be de-allocated by caller.
Return values
the default voicemail extension
Definition at line 263 of file config_global.c.
References ao2_ref, ast_strdup, DEFAULT_VOICEMAIL_EXTENSION, global_config::default_voicemail_extension, and get_global_cfg().
Referenced by global_loaded().
 {
    char *res;
    struct global_config *cfg;
    cfg = get_global_cfg();
    if (!cfg) {
       return ast_strdup(DEFAULT_VOICEMAIL_EXTENSION);
    }
    res = ast_strdup(cfg->default_voicemail_extension);
    ao2_ref(cfg, -1);
    return res;
 }
ast_sip_get_device_state()
const char* ast_sip_get_device_state (const struct ast_sip_endpoint * endpoint)
Retrieve the device state for an endpoint.
Parameters
endpoint The endpoint whose state is to be retrieved.
Return values
The device state.
Definition at line 1507 of file pjsip_configuration.c.
References ast_devstate2str(), ast_sorcery_object_get_id(), and MAX_OBJECT_FIELD.
Referenced by cli_endpoint_print_body(), format_ami_endpoints(), and sip_endpoint_to_ami().
 {
    char device[MAX_OBJECT_FIELD];
    snprintf(device, MAX_OBJECT_FIELD, "PJSIP/%s", ast_sorcery_object_get_id(endpoint));
    return ast_devstate2str(ast_device_state(device));
 }
ast_sip_get_disable_multi_domain()
unsigned int ast_sip_get_disable_multi_domain (void)
Retrieve the system setting 'disable multi domain'.
Since
13.9.0
Return values
non zero if disable multi domain.
Definition at line 324 of file config_global.c.
References ao2_ref, DEFAULT_DISABLE_MULTI_DOMAIN, global_config::disable_multi_domain, and get_global_cfg().
Referenced by anonymous_identify(), find_endpoint(), request(), and sip_dialog_create_from().
 {
    unsigned int disable_multi_domain;
    struct global_config *cfg;
    cfg = get_global_cfg();
    if (!cfg) {
       return DEFAULT_DISABLE_MULTI_DOMAIN;
    }
    disable_multi_domain = cfg->disable_multi_domain;
    ao2_ref(cfg, -1);
    return disable_multi_domain;
 }
ast_sip_get_endpoint_identifier_order()
char* ast_sip_get_endpoint_identifier_order (void)
Retrieve the global endpoint_identifier_order setting.
Specifies the order by which endpoint identifiers should be regarded.
Return values
the global endpoint_identifier_order value
Definition at line 279 of file config_global.c.
References ao2_ref, ast_strdup, DEFAULT_ENDPOINT_IDENTIFIER_ORDER, global_config::endpoint_identifier_order, and get_global_cfg().
Referenced by ast_sip_register_endpoint_identifier_with_name(), and global_loaded().
 {
    char *res;
    struct global_config *cfg;
    cfg = get_global_cfg();
    if (!cfg) {
       return ast_strdup(DEFAULT_ENDPOINT_IDENTIFIER_ORDER);
    }
    res = ast_strdup(cfg->endpoint_identifier_order);
    ao2_ref(cfg, -1);
    return res;
 }
ast_sip_get_endpoint_snapshot()
struct ast_endpoint_snapshot* ast_sip_get_endpoint_snapshot (const struct ast_sip_endpoint * endpoint)
Retrieve the endpoint snapshot for an endpoint.
Parameters
endpoint The endpoint whose snapshot is to be retreieved.
Return values
The endpoint snapshot
Definition at line 1515 of file pjsip_configuration.c.
References ast_endpoint_get_resource(), ast_endpoint_get_tech(), ast_endpoint_latest_snapshot(), and ast_sip_endpoint::persistent.
Referenced by active_channels_to_str(), ast_sip_for_each_channel(), and cli_endpoint_print_body().
 {
    return ast_endpoint_latest_snapshot(
       ast_endpoint_get_tech(endpoint->persistent),
       ast_endpoint_get_resource(endpoint->persistent));
 }
ast_sip_get_endpoints()
struct ao2_container* ast_sip_get_endpoints (void)
Retrieve any endpoints available to sorcery.
Return values
Endpoints available to sorcery, NULL if no endpoints found.
Definition at line 2344 of file pjsip_configuration.c.
References AST_RETRIEVE_FLAG_ALL, AST_RETRIEVE_FLAG_MULTIPLE, ast_sorcery_retrieve_by_fields(), endpoints, and NULL.
Referenced by ami_registrations_endpoints(), ami_show_endpoints(), and load_module().
 {
    struct ao2_container *endpoints;
    endpoints = ast_sorcery_retrieve_by_fields(sip_sorcery, "endpoint", AST_RETRIEVE_FLAG_MULTIPLE | AST_RETRIEVE_FLAG_ALL, NULL);
    return endpoints;
 }
ast_sip_get_host_ip()
int ast_sip_get_host_ip (int af, pj_sockaddr * addr)
Retrieve the local host address in IP form.
Parameters
af The address family to retrieve
addr A place to store the local host address
Return values
0 success
-1 failure
Since
13.6.0
Definition at line 5460 of file res_pjsip.c.
References ast_strlen_zero, host_ip_ipv4, host_ip_ipv4_string, host_ip_ipv6, and host_ip_ipv6_string.
 {
    if (af == pj_AF_INET() && !ast_strlen_zero(host_ip_ipv4_string)) {
       pj_sockaddr_copy_addr(addr, &host_ip_ipv4);
       return 0;
    } else if (af == pj_AF_INET6() && !ast_strlen_zero(host_ip_ipv6_string)) {
       pj_sockaddr_copy_addr(addr, &host_ip_ipv6);
       return 0;
    }
    return -1;
 }
ast_sip_get_host_ip_string()
const char* ast_sip_get_host_ip_string (int af)
Retrieve the local host address in string form.
Parameters
af The address family to retrieve
Return values
non-NULL success
NULL failure
Since
13.6.0
Note
An empty string may be returned if the address family is valid but no local address exists
Definition at line 5473 of file res_pjsip.c.
References host_ip_ipv4_string, host_ip_ipv6_string, and NULL.
Referenced by create_local_sdp(), create_outgoing_sdp_stream(), and multihomed_rewrite_sdp().
 {
    if (af == pj_AF_INET()) {
       return host_ip_ipv4_string;
    } else if (af == pj_AF_INET6()) {
       return host_ip_ipv6_string;
    }
    return NULL;
 }
ast_sip_get_ignore_uri_user_options()
unsigned int ast_sip_get_ignore_uri_user_options (void)
Retrieve the global setting 'ignore_uri_user_options'.
Since
13.12.0
Return values
non zero if ignore the user field options.
Definition at line 447 of file config_global.c.
References ao2_ref, DEFAULT_IGNORE_URI_USER_OPTIONS, get_global_cfg(), and global_config::ignore_uri_user_options.
Referenced by find_registrar_aor().
 {
    unsigned int ignore_uri_user_options;
    struct global_config *cfg;
    cfg = get_global_cfg();
    if (!cfg) {
       return DEFAULT_IGNORE_URI_USER_OPTIONS;
    }
    ignore_uri_user_options = cfg->ignore_uri_user_options;
    ao2_ref(cfg, -1);
    return ignore_uri_user_options;
 }
ast_sip_get_keep_alive_interval()
unsigned int ast_sip_get_keep_alive_interval (void)
Retrieve the system keep alive interval setting.
Return values
the keep alive interval.
Definition at line 294 of file config_global.c.
References ao2_ref, DEFAULT_KEEPALIVE_INTERVAL, get_global_cfg(), and global_config::keep_alive_interval.
Referenced by keepalive_global_loaded().
 {
    unsigned int interval;
    struct global_config *cfg;
    cfg = get_global_cfg();
    if (!cfg) {
       return DEFAULT_KEEPALIVE_INTERVAL;
    }
    interval = cfg->keep_alive_interval;
    ao2_ref(cfg, -1);
    return interval;
 }
ast_sip_get_max_initial_qualify_time()
unsigned int ast_sip_get_max_initial_qualify_time (void)
Retrieve the system max initial qualify time.
Return values
the maximum initial qualify time.
Definition at line 339 of file config_global.c.
References ao2_ref, DEFAULT_MAX_INITIAL_QUALIFY_TIME, get_global_cfg(), and global_config::max_initial_qualify_time.
Referenced by sip_options_determine_initial_qualify_time().
 {
    unsigned int time;
    struct global_config *cfg;
    cfg = get_global_cfg();
    if (!cfg) {
       return DEFAULT_MAX_INITIAL_QUALIFY_TIME;
    }
    time = cfg->max_initial_qualify_time;
    ao2_ref(cfg, -1);
    return time;
 }
ast_sip_get_mwi_disable_initial_unsolicited()
unsigned int ast_sip_get_mwi_disable_initial_unsolicited (void)
Retrieve the global setting 'disable sending unsolicited mwi on startup'.
Since
13.12.0
Return values
non zero if disable.
Definition at line 432 of file config_global.c.
References ao2_ref, DEFAULT_MWI_DISABLE_INITIAL_UNSOLICITED, global_config::disable_initial_unsolicited, get_global_cfg(), and global_config::mwi.
Referenced by load_module(), and reload().
 {
    unsigned int disable_initial_unsolicited;
    struct global_config *cfg;
    cfg = get_global_cfg();
    if (!cfg) {
       return DEFAULT_MWI_DISABLE_INITIAL_UNSOLICITED;
    }
    disable_initial_unsolicited = cfg->mwi.disable_initial_unsolicited;
    ao2_ref(cfg, -1);
    return disable_initial_unsolicited;
 }
ast_sip_get_mwi_tps_queue_high()
unsigned int ast_sip_get_mwi_tps_queue_high (void)
Retrieve the global MWI taskprocessor high water alert trigger level.
Since
13.12.0
Return values
the system MWI taskprocessor high water alert trigger level
Definition at line 402 of file config_global.c.
References ao2_ref, DEFAULT_MWI_TPS_QUEUE_HIGH, get_global_cfg(), global_config::mwi, and global_config::tps_queue_high.
Referenced by global_loaded().
 {
    unsigned int tps_queue_high;
    struct global_config *cfg;
    cfg = get_global_cfg();
    if (!cfg) {
       return DEFAULT_MWI_TPS_QUEUE_HIGH;
    }
    tps_queue_high = cfg->mwi.tps_queue_high;
    ao2_ref(cfg, -1);
    return tps_queue_high;
 }
ast_sip_get_mwi_tps_queue_low()
int ast_sip_get_mwi_tps_queue_low (void)
Retrieve the global MWI taskprocessor low water clear alert level.
Since
13.12.0
Return values
the system MWI taskprocessor low water clear alert level
Definition at line 417 of file config_global.c.
References ao2_ref, DEFAULT_MWI_TPS_QUEUE_LOW, get_global_cfg(), global_config::mwi, and global_config::tps_queue_low.
Referenced by global_loaded().
 {
    int tps_queue_low;
    struct global_config *cfg;
    cfg = get_global_cfg();
    if (!cfg) {
       return DEFAULT_MWI_TPS_QUEUE_LOW;
    }
    tps_queue_low = cfg->mwi.tps_queue_low;
    ao2_ref(cfg, -1);
    return tps_queue_low;
 }
ast_sip_get_norefersub()
unsigned int ast_sip_get_norefersub (void)
Retrieve the global setting 'norefersub'.
Return values
non zero if norefersub is to be sent in "Supported" Headers
Definition at line 507 of file config_global.c.
References ao2_ref, DEFAULT_NOREFERSUB, get_global_cfg(), and global_config::norefersub.
Referenced by load_module().
 {
    unsigned int norefersub;
    struct global_config *cfg;
    cfg = get_global_cfg();
    if (!cfg) {
       return DEFAULT_NOREFERSUB;
    }
    norefersub = cfg->norefersub;
    ao2_ref(cfg, -1);
    return norefersub;
 }
ast_sip_get_pjsip_endpoint()
pjsip_endpoint* ast_sip_get_pjsip_endpoint (void)
Get a pointer to the PJSIP endpoint.
This is useful when modules have specific information they need to register with the PJSIP core.
Return values
NULL endpoint has not been created yet.
non-NULL PJSIP endpoint.
Definition at line 3718 of file res_pjsip.c.
References ast_pjsip_endpoint.
Referenced by acl_on_rx_msg(), ast_res_pjsip_cleanup_options_handling(), ast_res_pjsip_init_options_handling(), ast_sip_create_response(), ast_sip_destroy_transport_events(), ast_sip_initialize_transport_events(), ast_sip_pubsub_register_body_generator(), ast_sip_send_response(), ast_sip_session_defer_termination(), ast_sip_session_resume_reinvite(), authenticate(), cancel_publish_refresh(), cancel_registration(), channel_read_pjsip(), create_out_of_dialog_request(), digest_create_request_with_auth(), distribute(), distributor(), do_cli_dump_endpt(), endpoint_lookup(), endpt_send_request(), endpt_send_request_cb(), exten_state_data_alloc(), exten_state_data_destructor(), exten_state_publisher_cb(), filter_on_tx_message(), find_registrar_aor(), keepalive_transport_send_keepalive(), load_module(), logging_on_rx_msg(), logging_on_tx_msg(), notify_task(), on_rx_process_uris(), options_incoming_request(), parse_uri_cb(), pre_session_setup(), publish_request_initial(), pubsub_on_rx_mwi_notify_request(), pubsub_on_rx_publish_request(), pubsub_on_rx_subscribe_request(), register_aor(), register_aor_core(), registrar_on_rx_request(), reschedule_reinvite(), schedule_publish_refresh(), schedule_registration(), send_options_response(), session_reinvite_on_rx_request(), sip_check_transport(), sip_dialog_create_contact(), sip_dialog_create_from(), sip_outbound_publisher_init(), sip_outbound_registration_regc_alloc(), sip_publication_respond(), sip_replace_resolver(), sip_session_defer_termination_stop_timer(), subscription_persistence_load(), system_create_resolver_and_set_nameservers(), t38_change_state(), transport_apply(), and transport_create().
 {
    return ast_pjsip_endpoint;
 }
ast_sip_get_regcontext()
char* ast_sip_get_regcontext (void)
Retrieve the global regcontext setting.
Since
13.8.0
Note
returned string needs to be de-allocated by caller.
Return values
the global regcontext setting
Definition at line 247 of file config_global.c.
References ao2_ref, ast_strdup, DEFAULT_REGCONTEXT, get_global_cfg(), and global_config::regcontext.
Referenced by ast_sip_persistent_endpoint_update_state().
 {
    char *res;
    struct global_config *cfg;
    cfg = get_global_cfg();
    if (!cfg) {
       return ast_strdup(DEFAULT_REGCONTEXT);
    }
    res = ast_strdup(cfg->regcontext);
    ao2_ref(cfg, -1);
    return res;
 }
ast_sip_get_send_contact_status_on_update_registration()
unsigned int ast_sip_get_send_contact_status_on_update_registration (void)
Retrieve the global setting 'send_contact_status_on_update_registration'.
Since
16.2.0
Return values
non zero if need to send AMI ContactStatus event when a contact is updated.
Definition at line 477 of file config_global.c.
References ao2_ref, DEFAULT_SEND_CONTACT_STATUS_ON_UPDATE_REGISTRATION, get_global_cfg(), and global_config::send_contact_status_on_update_registration.
Referenced by contact_observer_updated().
 {
    unsigned int send_contact_status_on_update_registration;
    struct global_config *cfg;
    cfg = get_global_cfg();
    if (!cfg) {
       return DEFAULT_SEND_CONTACT_STATUS_ON_UPDATE_REGISTRATION;
    }
    send_contact_status_on_update_registration = cfg->send_contact_status_on_update_registration;
    ao2_ref(cfg, -1);
    return send_contact_status_on_update_registration;
 }
ast_sip_get_sorcery()
struct ast_sorcery* ast_sip_get_sorcery (void)
Get a pointer to the SIP sorcery structure.
Return values
NULL sorcery has not been initialized
non-NULL sorcery structure
Definition at line 2404 of file pjsip_configuration.c.
References sip_sorcery.
Referenced by acl_change_stasis_cb(), acl_on_rx_msg(), alloc_artificial_auth(), ami_show_endpoint(), ami_show_registration_contact_statuses(), ami_show_resource_lists(), ami_sip_qualify(), anonymous_identify(), aor_deleted_observer(), ast_res_pjsip_cleanup_options_handling(), ast_sip_cli_print_sorcery_objectset(), ast_sip_destroy_distributor(), ast_sip_destroy_sorcery_global(), ast_sip_destroy_sorcery_location(), ast_sip_destroy_transport_management(), ast_sip_for_each_auth(), ast_sip_initialize_distributor(), ast_sip_initialize_sorcery_auth(), ast_sip_initialize_sorcery_domain_alias(), ast_sip_initialize_sorcery_global(), ast_sip_initialize_sorcery_location(), ast_sip_initialize_sorcery_transport(), ast_sip_initialize_transport_management(), ast_sip_location_create_contact(), ast_sip_location_delete_contact(), ast_sip_location_prune_boot_contacts(), ast_sip_location_retrieve_aor(), ast_sip_location_retrieve_aor_contacts_nolock_filtered(), ast_sip_location_retrieve_contact(), ast_sip_location_update_contact(), ast_sip_retrieve_auths(), ast_sip_retrieve_auths_vector(), ast_sip_set_tpselector_from_transport_name(), ast_sip_sorcery_object_to_ami(), asterisk_publication_devicestate_state_change(), asterisk_publication_mwi_state_change(), asterisk_publication_new(), asterisk_publication_send_refresh(), auth_observer(), can_reuse_registration(), chan_pjsip_devicestate(), check_expiration_thread(), check_state(), cleanup_resource_list(), cli_aor_get_container(), cli_aor_retrieve_by_id(), cli_complete_endpoint(), cli_complete_registration(), cli_contact_get_container(), cli_endpoint_retrieve_by_id(), cli_get_aors(), cli_get_auths(), cli_get_container(), cli_iterate(), cli_iterator(), cli_qualify(), cli_reload_qualify_aor(), cli_reload_qualify_endpoint(), cli_retrieve_by_id(), cli_show_qualify_endpoint(), common_identify(), contact_observer_updated(), create_artificial_endpoint(), create_mwi_subscriptions(), create_resource_list(), create_rtp(), find_aor(), find_aor_name(), find_endpoint(), format_ami_endpoint_identify(), format_ami_endpoint_transport(), get_all_contacts(), get_publishes_and_update_state(), get_registrations(), get_write_timeout(), handle_atsign(), handle_export_primitives(), handle_single_token(), handle_slash(), line_identify(), load_module(), mwi_contact_changed(), mwi_contact_deleted(), mwi_subscription_shutdown(), on_rx_process_symmetric_transport(), permanent_uri_handler(), pjsip_acf_dial_contacts_read(), pjsip_aor_function_read(), pjsip_contact_function_read(), pjsip_endpoint_function_read(), pjsip_outbound_registration_metrics_init(), pjsip_outbound_registration_metrics_unload_cb(), process_nat(), publish_request_initial(), push_notify(), register_aor_core(), registration_deleted_observer(), registration_loaded_observer(), reload_module(), request(), reregister_all(), retrieve_resource_list(), send_unsolicited_mwi_notify(), sip_aor_to_ami(), sip_cli_print_global(), sip_options_aor_observer_modified_task(), sip_options_apply_aor_configuration(), sip_options_contact_add_management_task(), sip_options_init_task(), sip_options_qualify_contact(), sip_options_synchronize_task(), sub_persistence_recreate(), subscription_persistence_create(), subscription_persistence_load(), subscription_persistence_recreate(), subscription_persistence_remove(), subscription_persistence_update(), transfer(), and unload_module().
 {
    return sip_sorcery;
 }
ast_sip_get_transport_name()
int ast_sip_get_transport_name (const struct ast_sip_endpoint * endpoint, pjsip_sip_uri * sip_uri, char * buf, size_t buf_len)
Get the transport name from an endpoint or request uri.
Since
13.15.0
Parameters
endpoint
sip_uri
buf Buffer to receive transport name
buf_len Buffer length
Return values
0 Success
-1 Failure
Note
If endpoint->transport is not NULL, it is returned in buf. Otherwise if sip_uri has an 'x-ast-txp' parameter AND the sip_uri host is an ip4 or ip6 address, its value is returned,
Definition at line 3762 of file res_pjsip.c.
References ast_alloca, ast_copy_pj_str(), ast_copy_string(), AST_SIP_X_AST_TXP, AST_SIP_X_AST_TXP_LEN, ast_sockaddr_parse(), ast_strlen_zero, host, NULL, PARSE_PORT_FORBID, and ast_sip_endpoint::transport.
Referenced by ast_sip_set_tpselector_from_ep_or_uri().
 {
    char *host = NULL;
    static const pj_str_t x_name = { AST_SIP_X_AST_TXP, AST_SIP_X_AST_TXP_LEN };
    pjsip_param *x_transport;
    if (!ast_strlen_zero(endpoint->transport)) {
       ast_copy_string(buf, endpoint->transport, buf_len);
       return 0;
    }
    x_transport = pjsip_param_find(&sip_uri->other_param, &x_name);
    if (!x_transport) {
       return -1;
    }
    /* Only use x_transport if the uri host is an ip (4 or 6) address */
    host = ast_alloca(sip_uri->host.slen + 1);
    ast_copy_pj_str(host, &sip_uri->host, sip_uri->host.slen + 1);
    if (!ast_sockaddr_parse(NULL, host, PARSE_PORT_FORBID)) {
       return -1;
    }
    ast_copy_pj_str(buf, &x_transport->value, buf_len);
    return 0;
 }
ast_sip_get_transport_state()
struct ast_sip_transport_state* ast_sip_get_transport_state (const char * transport_id)
Retrieve transport state.
Since
13.7.1
Parameters
transport_id
Returns
transport_state
Note
ao2_cleanup(...) or ao2_ref(..., -1) must be called on the returned object
Definition at line 1564 of file config_transport.c.
References ao2_bump, ao2_find, ao2_lock, ao2_ref, ao2_unlock, ast_sip_transport_state::flow, NULL, OBJ_SEARCH_KEY, internal_state::state, and ast_sip_transport_state::transport.
Referenced by ast_sip_message_apply_transport(), ast_sip_set_tpselector_from_transport(), ast_sip_transport_state_set_preferred_identity(), ast_sip_transport_state_set_service_routes(), ast_sip_transport_state_set_transport(), change_outgoing_sdp_stream_media_address(), create_rtp(), and session_outgoing_nat_hook().
 {
    struct internal_state *state = NULL;
    struct ast_sip_transport_state *trans_state;
    if (!transport_states) {
       return NULL;
    }
    state = ao2_find(transport_states, transport_id, OBJ_SEARCH_KEY);
    if (!state) {
       return NULL;
    }
    trans_state = ao2_bump(state->state);
    ao2_ref(state, -1);
    /* If this is a child transport see if the transport is actually dead */
    if (trans_state->flow) {
       ao2_lock(trans_state);
       if (trans_state->transport && trans_state->transport->is_shutdown == PJ_TRUE) {
          pjsip_transport_dec_ref(trans_state->transport);
          trans_state->transport = NULL;
       }
       ao2_unlock(trans_state);
    }
    return trans_state;
 }
ast_sip_get_transport_states()
struct ao2_container* ast_sip_get_transport_states (void)
Retrieves all transport states.
Since
13.7.1
Returns
ao2_container
Note
ao2_cleanup(...) or ao2_ref(..., -1) must be called on the returned object
Definition at line 1604 of file config_transport.c.
References AO2_ALLOC_OPT_LOCK_MUTEX, ao2_callback, ao2_container_alloc_hash, DEFAULT_STATE_BUCKETS, NULL, OBJ_MULTIPLE, OBJ_NODATA, populate_transport_states(), transport_state_cmp(), and transport_state_hash().
Referenced by anonymous_identify(), find_endpoint(), get_udp_transport(), get_write_timeout(), and process_nat().
 {
    struct ao2_container *states = ao2_container_alloc_hash(AO2_ALLOC_OPT_LOCK_MUTEX, 0,
       DEFAULT_STATE_BUCKETS, transport_state_hash, NULL, transport_state_cmp);
    if (!states) {
       return NULL;
    }
    ao2_callback(transport_states, OBJ_NODATA | OBJ_MULTIPLE, populate_transport_states, states);
    return states;
 }
ast_sip_get_unidentified_request_thresholds()
void ast_sip_get_unidentified_request_thresholds (unsigned int * count, unsigned int * period, unsigned int * prune_interval)
Retrieve the unidentified request security event thresholds.
Since
13.8.0
Parameters
count The maximum number of unidentified requests per source ip to accumulate before emitting a security event
period The period in seconds over which to accumulate unidentified requests
prune_interval The interval in seconds at which expired entries will be pruned
Definition at line 354 of file config_global.c.
References ao2_ref, DEFAULT_UNIDENTIFIED_REQUEST_COUNT, DEFAULT_UNIDENTIFIED_REQUEST_PERIOD, DEFAULT_UNIDENTIFIED_REQUEST_PRUNE_INTERVAL, get_global_cfg(), global_config::unidentified_request_count, global_config::unidentified_request_period, and global_config::unidentified_request_prune_interval.
Referenced by global_loaded(), and prune_task().
 {
    struct global_config *cfg;
    cfg = get_global_cfg();
    if (!cfg) {
       *count = DEFAULT_UNIDENTIFIED_REQUEST_COUNT;
       *period = DEFAULT_UNIDENTIFIED_REQUEST_PERIOD;
       *prune_interval = DEFAULT_UNIDENTIFIED_REQUEST_PRUNE_INTERVAL;
       return;
    }
    *count = cfg->unidentified_request_count;
    *period = cfg->unidentified_request_period;
    *prune_interval = cfg->unidentified_request_prune_interval;
    ao2_ref(cfg, -1);
    return;
 }
ast_sip_get_use_callerid_contact()
unsigned int ast_sip_get_use_callerid_contact (void)
Retrieve the global setting 'use_callerid_contact'.
Since
13.24.0
Return values
non zero if CALLERID(num) is to be used as the default username in the contact
Definition at line 462 of file config_global.c.
References ao2_ref, DEFAULT_USE_CALLERID_CONTACT, get_global_cfg(), and global_config::use_callerid_contact.
Referenced by set_from_header().
 {
    unsigned int use_callerid_contact;
    struct global_config *cfg;
    cfg = get_global_cfg();
    if (!cfg) {
       return DEFAULT_USE_CALLERID_CONTACT;
    }
    use_callerid_contact = cfg->use_callerid_contact;
    ao2_ref(cfg, -1);
    return use_callerid_contact;
 }
ast_sip_identify_endpoint()
struct ast_sip_endpoint* ast_sip_identify_endpoint (pjsip_rx_data * rdata)
Determine the endpoint that has sent a SIP message.
This will call into each of the registered endpoint identifiers' identify_endpoint() callbacks until one returns a non-NULL endpoint. This will return an ao2 object. Its reference count will need to be decremented when completed using the endpoint.
Parameters
rdata The inbound SIP message to use when identifying the endpoint.
Return values
NULL No matching endpoint
non-NULL The matching endpoint
Definition at line 3528 of file res_pjsip.c.
References ast_assert, AST_RWLIST_RDLOCK, AST_RWLIST_TRAVERSE, AST_RWLIST_UNLOCK, endpoint_identifier_list::identifier, ast_sip_endpoint_identifier::identify_endpoint, lock, NULL, and SCOPED_LOCK.
Referenced by endpoint_lookup().
 {
    struct endpoint_identifier_list *iter;
    struct ast_sip_endpoint *endpoint = NULL;
    SCOPED_LOCK(lock, &endpoint_identifiers, AST_RWLIST_RDLOCK, AST_RWLIST_UNLOCK);
    AST_RWLIST_TRAVERSE(&endpoint_identifiers, iter, list) {
       ast_assert(iter->identifier->identify_endpoint != NULL);
       endpoint = iter->identifier->identify_endpoint(rdata);
       if (endpoint) {
          break;
       }
    }
    return endpoint;
 }
ast_sip_is_content_type()
int ast_sip_is_content_type (pjsip_media_type * content_type, char * type, char * subtype)
Checks if the given content type matches type/subtype.
Compares the pjsip_media_type with the passed type and subtype and returns the result of that comparison. The media type parameters are ignored.
Parameters
content_type The pjsip_media_type structure to compare
type The media type to compare
subtype The media subtype to compare
Return values
0 No match
-1 Match
Definition at line 5259 of file res_pjsip.c.
References compare().
Referenced by asterisk_publication_devicestate_state_change(), asterisk_publication_mwi_state_change(), check_content_type(), filter_on_tx_message(), pubsub_on_rx_notify_request(), session_outgoing_nat_hook(), and video_info_incoming_request().
 {
    pjsip_media_type compare;
    if (!content_type) {
       return 0;
    }
    pjsip_media_type_init2(&compare, type, subtype);
    return pjsip_media_type_cmp(content_type, &compare, 0) ? 0 : -1;
 }
ast_sip_location_add_contact()
int ast_sip_location_add_contact (struct ast_sip_aor * aor, const char * uri, struct timeval expiration_time, const char * path_info, const char * user_agent, const char * via_addr, int via_port, const char * call_id, struct ast_sip_endpoint * endpoint)
Add a new contact to an AOR.
Parameters
aor Pointer to the AOR
uri Full contact URI
expiration_time Optional expiration time of the contact
path_info Path information
user_agent User-Agent header from REGISTER request
via_addr
via_port
call_id
endpoint The endpoint that resulted in the contact being added
Return values
-1 failure
0 success
Warning
This function holds a named write lock on the aor. If you already hold the lock you should call ast_sip_location_add_contact_nolock instead.
Definition at line 429 of file location.c.
References ao2_lock, ao2_unlock, and ast_sip_location_add_contact_nolock().
 {
    int res;
    ao2_lock(aor);
    res = ast_sip_location_add_contact_nolock(aor, uri, expiration_time, path_info, user_agent,
       via_addr, via_port, call_id,
       endpoint);
    ao2_unlock(aor);
    return res;
 }
ast_sip_location_add_contact_nolock()
int ast_sip_location_add_contact_nolock (struct ast_sip_aor * aor, const char * uri, struct timeval expiration_time, const char * path_info, const char * user_agent, const char * via_addr, int via_port, const char * call_id, struct ast_sip_endpoint * endpoint)
Add a new contact to an AOR without locking the AOR.
Since
13.9.0
Parameters
aor Pointer to the AOR
uri Full contact URI
expiration_time Optional expiration time of the contact
path_info Path information
user_agent User-Agent header from REGISTER request
via_addr
via_port
call_id
endpoint The endpoint that resulted in the contact being added
Return values
-1 failure
0 success
Warning
This function should only be called if you already hold a named write lock on the aor.
Definition at line 416 of file location.c.
References ao2_cleanup, and ast_sip_location_create_contact().
Referenced by ast_sip_location_add_contact().
 {
    struct ast_sip_contact *contact;
    contact = ast_sip_location_create_contact(aor, uri, expiration_time, path_info,
       user_agent, via_addr, via_port, call_id, 0, endpoint);
    ao2_cleanup(contact);
    return contact ? 0 : -1;
 }
ast_sip_location_create_contact()
struct ast_sip_contact* ast_sip_location_create_contact (struct ast_sip_aor * aor, const char * uri, struct timeval expiration_time, const char * path_info, const char * user_agent, const char * via_addr, int via_port, const char * call_id, int prune_on_boot, struct ast_sip_endpoint * endpoint)
Create a new contact for an AOR without locking the AOR.
Since
13.18.0
Parameters
aor Pointer to the AOR
uri Full contact URI
expiration_time Optional expiration time of the contact
path_info Path information
user_agent User-Agent header from REGISTER request
via_addr
via_port
call_id
prune_on_boot Non-zero if the contact cannot survive a restart/boot.
endpoint The endpoint that resulted in the contact being added
Returns
The created contact or NULL on failure.
Warning
This function should only be called if you already hold a named write lock on the aor.
Definition at line 355 of file location.c.
References ao2_bump, ao2_ref, ast_config_AST_SYSTEM_NAME, ast_md5_hash(), ast_sip_get_sorcery(), ast_sorcery_alloc(), ast_sorcery_create(), ast_sorcery_object_get_id(), ast_string_field_set, ast_strlen_zero, ast_sip_contact::authenticate_qualify, ast_sip_aor::authenticate_qualify, ast_sip_contact::endpoint, ast_sip_contact::endpoint_name, ast_sip_contact::expiration_time, MAX_OBJECT_FIELD, name, NULL, ast_sip_contact::outbound_proxy, ast_sip_aor::outbound_proxy, ast_sip_contact::path, ast_sip_contact::prune_on_boot, ast_sip_contact::qualify_frequency, ast_sip_aor::qualify_frequency, ast_sip_contact::qualify_timeout, ast_sip_aor::qualify_timeout, ast_sip_contact::reg_server, ast_sip_aor::support_path, and ast_sip_contact::via_port.
Referenced by ast_sip_location_add_contact_nolock(), and register_aor_core().
 {
    struct ast_sip_contact *contact;
    char name[MAX_OBJECT_FIELD * 2 + 3];
    char hash[33];
    ast_md5_hash(hash, uri);
    snprintf(name, sizeof(name), "%s;@%s", ast_sorcery_object_get_id(aor), hash);
    contact = ast_sorcery_alloc(ast_sip_get_sorcery(), "contact", name);
    if (!contact) {
       return NULL;
    }
    ast_string_field_set(contact, uri, uri);
    contact->expiration_time = expiration_time;
    contact->qualify_frequency = aor->qualify_frequency;
    contact->qualify_timeout = aor->qualify_timeout;
    contact->authenticate_qualify = aor->authenticate_qualify;
    if (path_info && aor->support_path) {
       ast_string_field_set(contact, path, path_info);
    }
    if (!ast_strlen_zero(aor->outbound_proxy)) {
       ast_string_field_set(contact, outbound_proxy, aor->outbound_proxy);
    }
    if (!ast_strlen_zero(user_agent)) {
       ast_string_field_set(contact, user_agent, user_agent);
    }
    if (!ast_strlen_zero(ast_config_AST_SYSTEM_NAME)) {
       ast_string_field_set(contact, reg_server, ast_config_AST_SYSTEM_NAME);
    }
    if (!ast_strlen_zero(via_addr)) {
       ast_string_field_set(contact, via_addr, via_addr);
    }
    contact->via_port = via_port;
    if (!ast_strlen_zero(call_id)) {
       ast_string_field_set(contact, call_id, call_id);
    }
    contact->endpoint = ao2_bump(endpoint);
    if (endpoint) {
       ast_string_field_set(contact, endpoint_name, ast_sorcery_object_get_id(endpoint));
    }
    contact->prune_on_boot = prune_on_boot;
    if (ast_sorcery_create(ast_sip_get_sorcery(), contact)) {
       ao2_ref(contact, -1);
       return NULL;
    }
    return contact;
 }
ast_sip_location_delete_contact()
int ast_sip_location_delete_contact (struct ast_sip_contact * contact)
Delete a contact.
Parameters
contact Contact object to delete
Return values
-1 failure
0 success
Definition at line 450 of file location.c.
References ast_sip_get_sorcery(), and ast_sorcery_delete().
Referenced by contact_expire(), destroy_contact(), prune_boot_contacts_cb(), and registrar_contact_delete().
 {
    return ast_sorcery_delete(ast_sip_get_sorcery(), contact);
 }
ast_sip_location_prune_boot_contacts()
void ast_sip_location_prune_boot_contacts (void)
Prune the prune_on_boot contacts.
Since
13.18.0
Definition at line 469 of file location.c.
References ao2_callback, ao2_ref, AST_RETRIEVE_FLAG_ALL, AST_RETRIEVE_FLAG_MULTIPLE, ast_sip_get_sorcery(), ast_sorcery_retrieve_by_fields(), NULL, and prune_boot_contacts_cb().
Referenced by ast_res_pjsip_initialize_configuration().
 {
    struct ao2_container *contacts;
    contacts = ast_sorcery_retrieve_by_fields(ast_sip_get_sorcery(), "contact",
       AST_RETRIEVE_FLAG_MULTIPLE | AST_RETRIEVE_FLAG_ALL, NULL);
    if (contacts) {
       ao2_callback(contacts, 0, prune_boot_contacts_cb, NULL);
       ao2_ref(contacts, -1);
    }
 }
ast_sip_location_retrieve_aor()
struct ast_sip_aor* ast_sip_location_retrieve_aor (const char * aor_name)
Retrieve a named AOR.
Parameters
aor_name Name of the AOR
Return values
NULL if not found
non-NULL if found
Definition at line 147 of file location.c.
References ast_sip_get_sorcery(), and ast_sorcery_retrieve_by_id().
Referenced by ast_sip_for_each_aor(), ast_sip_location_retrieve_contact_and_aor_from_list_filtered(), find_aor(), find_aor_for_resource(), find_registrar_aor(), handle_slash(), notify_endpoint(), pjsip_acf_dial_contacts_read(), register_contact_transport_remove_cb(), and send_unsolicited_mwi_notify().
 {
    return ast_sorcery_retrieve_by_id(ast_sip_get_sorcery(), "aor", aor_name);
 }
ast_sip_location_retrieve_aor_contacts()
struct ao2_container* ast_sip_location_retrieve_aor_contacts (const struct ast_sip_aor * aor)
Retrieve all contacts currently available for an AOR.
Parameters
aor Pointer to the AOR
Return values
NULL if no contacts available
non-NULL if contacts available
Warning
Since this function prunes expired contacts before returning, it holds a named write lock on the aor. If you already hold the lock, call ast_sip_location_retrieve_aor_contacts_nolock instead.
Definition at line 247 of file location.c.
References AST_SIP_CONTACT_FILTER_DEFAULT, and ast_sip_location_retrieve_aor_contacts_filtered().
Referenced by ast_sip_for_each_contact(), format_ami_aor_handler(), gather_contacts_for_aor(), notify_endpoint(), pjsip_aor_function_read(), and send_unsolicited_mwi_notify().
 {
    return ast_sip_location_retrieve_aor_contacts_filtered(aor, AST_SIP_CONTACT_FILTER_DEFAULT);
 }
ast_sip_location_retrieve_aor_contacts_filtered()
struct ao2_container* ast_sip_location_retrieve_aor_contacts_filtered (const struct ast_sip_aor * aor, unsigned int flags)
Retrieve all contacts currently available for an AOR and filter based on flags.
Since
13.16.0
Parameters
aor Pointer to the AOR
flags Filtering flags
Return values
NULL if no contacts available
non-NULL if contacts available
Warning
Since this function prunes expired contacts before returning, it holds a named write lock on the aor. If you already hold the lock, call ast_sip_location_retrieve_aor_contacts_nolock instead.
Definition at line 252 of file location.c.
References ao2_lock, ao2_unlock, and ast_sip_location_retrieve_aor_contacts_nolock_filtered().
Referenced by ast_sip_location_retrieve_aor_contacts(), ast_sip_location_retrieve_first_aor_contact_filtered(), and pjsip_acf_dial_contacts_read().
 {
    struct ao2_container *contacts;
    /* ao2_lock / ao2_unlock do not actually write aor since it has an ao2 lockobj. */
    ao2_lock((void*)aor);
    contacts = ast_sip_location_retrieve_aor_contacts_nolock_filtered(aor, flags);
    ao2_unlock((void*)aor);
    return contacts;
 }
ast_sip_location_retrieve_aor_contacts_nolock()
struct ao2_container* ast_sip_location_retrieve_aor_contacts_nolock (const struct ast_sip_aor * aor)
Retrieve all contacts currently available for an AOR without locking the AOR.
Since
13.9.0
Parameters
aor Pointer to the AOR
Return values
NULL if no contacts available
non-NULL if contacts available
Warning
This function should only be called if you already hold a named write lock on the aor.
Definition at line 214 of file location.c.
References AST_SIP_CONTACT_FILTER_DEFAULT, and ast_sip_location_retrieve_aor_contacts_nolock_filtered().
Referenced by register_aor().
 {
    return ast_sip_location_retrieve_aor_contacts_nolock_filtered(aor, AST_SIP_CONTACT_FILTER_DEFAULT);
 }
ast_sip_location_retrieve_aor_contacts_nolock_filtered()
struct ao2_container* ast_sip_location_retrieve_aor_contacts_nolock_filtered (const struct ast_sip_aor * aor, unsigned int flags)
Retrieve all contacts currently available for an AOR without locking the AOR and filter based on flags.
Since
13.16.0
Parameters
aor Pointer to the AOR
flags Filtering flags
Return values
NULL if no contacts available
non-NULL if contacts available
Warning
This function should only be called if you already hold a named write lock on the aor.
Definition at line 219 of file location.c.
References ao2_callback, AST_SIP_CONTACT_FILTER_REACHABLE, ast_sip_get_sorcery(), ast_sorcery_object_get_id(), ast_sorcery_retrieve_by_prefix(), contact_expire(), contact_link_static(), contact_remove_unreachable(), NULL, OBJ_MULTIPLE, OBJ_NODATA, OBJ_UNLINK, ast_sip_aor::permanent_contacts, and prefix.
Referenced by ast_sip_location_retrieve_aor_contacts_filtered(), and ast_sip_location_retrieve_aor_contacts_nolock().
 {
    /* Give enough space for ;@ at the end, since that is our object naming scheme */
    size_t prefix_len = strlen(ast_sorcery_object_get_id(aor)) + sizeof(";@") - 1;
    char prefix[prefix_len + 1];
    struct ao2_container *contacts;
    sprintf(prefix, "%s;@", ast_sorcery_object_get_id(aor)); /* Safe */
    if (!(contacts = ast_sorcery_retrieve_by_prefix(ast_sip_get_sorcery(), "contact", prefix, prefix_len))) {
       return NULL;
    }
    /* Prune any expired contacts and delete them, we do this first because static contacts can never expire */
    ao2_callback(contacts, OBJ_NODATA | OBJ_MULTIPLE | OBJ_UNLINK, contact_expire, NULL);
    /* Add any permanent contacts from the AOR */
    if (aor->permanent_contacts) {
       ao2_callback(aor->permanent_contacts, OBJ_NODATA, contact_link_static, contacts);
    }
    if (flags & AST_SIP_CONTACT_FILTER_REACHABLE) {
       ao2_callback(contacts, OBJ_NODATA | OBJ_MULTIPLE | OBJ_UNLINK, contact_remove_unreachable, NULL);
    }
    return contacts;
 }
ast_sip_location_retrieve_contact()
struct ast_sip_contact* ast_sip_location_retrieve_contact (const char * contact_name)
Retrieve a named contact.
Parameters
contact_name Name of the contact
Return values
NULL if not found
non-NULL if found
Definition at line 350 of file location.c.
References ast_sip_get_sorcery(), and ast_sorcery_retrieve_by_id().
Referenced by register_contact_transport_remove_cb().
 {
    return ast_sorcery_retrieve_by_id(ast_sip_get_sorcery(), "contact", contact_name);
 }
ast_sip_location_retrieve_contact_and_aor_from_list()
void ast_sip_location_retrieve_contact_and_aor_from_list (const char * aor_list, struct ast_sip_aor ** aor, struct ast_sip_contact ** contact)
Retrieve the first bound contact AND the AOR chosen from a list of AORs.
Parameters
aor_list A comma-separated list of AOR names
aor The chosen AOR
contact The chosen contact
Definition at line 266 of file location.c.
References AST_SIP_CONTACT_FILTER_DEFAULT, and ast_sip_location_retrieve_contact_and_aor_from_list_filtered().
Referenced by ast_sip_location_retrieve_contact_from_aor_list().
 {
    ast_sip_location_retrieve_contact_and_aor_from_list_filtered(aor_list, AST_SIP_CONTACT_FILTER_DEFAULT, aor, contact);
 }
ast_sip_location_retrieve_contact_and_aor_from_list_filtered()
void ast_sip_location_retrieve_contact_and_aor_from_list_filtered (const char * aor_list, unsigned int flags, struct ast_sip_aor ** aor, struct ast_sip_contact ** contact)
Retrieve the first bound contact AND the AOR chosen from a list of AORs and filter based on flags.
Since
13.16.0
Parameters
aor_list A comma-separated list of AOR names
flags Filtering flags
aor The chosen AOR
contact The chosen contact
Definition at line 272 of file location.c.
References ao2_ref, ast_log, ast_sip_location_retrieve_aor(), ast_sip_location_retrieve_first_aor_contact_filtered(), ast_strdupa, ast_strip(), ast_strlen_zero, LOG_WARNING, NULL, and strsep().
Referenced by ast_sip_location_retrieve_contact_and_aor_from_list(), and ast_sip_session_create_outgoing().
 {
    char *aor_name;
    char *rest;
    /* If the location is still empty we have nowhere to go */
    if (ast_strlen_zero(aor_list) || !(rest = ast_strdupa(aor_list))) {
       ast_log(LOG_WARNING, "Unable to determine contacts from empty aor list\n");
       return;
    }
    *aor = NULL;
    *contact = NULL;
    while ((aor_name = ast_strip(strsep(&rest, ",")))) {
       *aor = ast_sip_location_retrieve_aor(aor_name);
       if (!(*aor)) {
          continue;
       }
       *contact = ast_sip_location_retrieve_first_aor_contact_filtered(*aor, flags);
       /* If a valid contact is available use its URI for dialing */
       if (*contact) {
          break;
       }
       ao2_ref(*aor, -1);
       *aor = NULL;
    }
 }
ast_sip_location_retrieve_contact_from_aor_list()
struct ast_sip_contact* ast_sip_location_retrieve_contact_from_aor_list (const char * aor_list)
Retrieve the first bound contact from a list of AORs.
Parameters
aor_list A comma-separated list of AOR names
Return values
NULL if no contacts available
non-NULL if contacts available
Definition at line 304 of file location.c.
References ao2_cleanup, ast_sip_location_retrieve_contact_and_aor_from_list(), cli_contact_populate_container(), and permanent_uri_sort_fn().
Referenced by ast_sip_create_subscription(), create_out_of_dialog_request(), handle_atsign(), handle_single_token(), insert_user_in_contact_uri(), mwi_contact_deleted(), and transfer().
 {
    struct ast_sip_aor *aor;
    struct ast_sip_contact *contact;
    ast_sip_location_retrieve_contact_and_aor_from_list(aor_list, &aor, &contact);
    ao2_cleanup(aor);
    return contact;
 }
ast_sip_location_retrieve_contacts_from_aor_list()
struct ao2_container* ast_sip_location_retrieve_contacts_from_aor_list (const char * aor_list)
Retrieve all contacts from a list of AORs.
Parameters
aor_list A comma-separated list of AOR names
Return values
NULL if no contacts available
non-NULL container (which must be freed) if contacts available
Definition at line 335 of file location.c.
References AO2_ALLOC_OPT_LOCK_NOLOCK, ao2_container_alloc_list, AO2_CONTAINER_ALLOC_OPT_DUPS_REJECT, ast_sip_for_each_aor(), gather_contacts_for_aor(), NULL, and permanent_uri_sort_fn().
 {
    struct ao2_container *contacts;
    contacts = ao2_container_alloc_list(AO2_ALLOC_OPT_LOCK_NOLOCK,
       AO2_CONTAINER_ALLOC_OPT_DUPS_REJECT, permanent_uri_sort_fn, NULL);
    if (!contacts) {
       return NULL;
    }
    ast_sip_for_each_aor(aor_list, gather_contacts_for_aor, contacts);
    return contacts;
 }
ast_sip_location_retrieve_first_aor_contact()
struct ast_sip_contact* ast_sip_location_retrieve_first_aor_contact (const struct ast_sip_aor * aor)
Retrieve the first bound contact for an AOR.
Parameters
aor Pointer to the AOR
Return values
NULL if no contacts available
non-NULL if contacts available
Definition at line 194 of file location.c.
References AST_SIP_CONTACT_FILTER_DEFAULT, and ast_sip_location_retrieve_first_aor_contact_filtered().
Referenced by handle_slash().
 {
    return ast_sip_location_retrieve_first_aor_contact_filtered(aor, AST_SIP_CONTACT_FILTER_DEFAULT);
 }
ast_sip_location_retrieve_first_aor_contact_filtered()
struct ast_sip_contact* ast_sip_location_retrieve_first_aor_contact_filtered (const struct ast_sip_aor * aor, unsigned int flags)
Retrieve the first bound contact for an AOR and filter based on flags.
Since
13.16.0
Parameters
aor Pointer to the AOR
flags Filtering flags
Return values
NULL if no contacts available
non-NULL if contacts available
Definition at line 199 of file location.c.
References ao2_callback, ao2_cleanup, ao2_container_count(), ast_sip_location_retrieve_aor_contacts_filtered(), and NULL.
Referenced by ast_sip_location_retrieve_contact_and_aor_from_list_filtered(), and ast_sip_location_retrieve_first_aor_contact().
 {
    struct ao2_container *contacts;
    struct ast_sip_contact *contact = NULL;
    contacts = ast_sip_location_retrieve_aor_contacts_filtered(aor, flags);
    if (contacts && ao2_container_count(contacts)) {
       /* Get the first AOR contact in the container. */
       contact = ao2_callback(contacts, 0, NULL, NULL);
    }
    ao2_cleanup(contacts);
    return contact;
 }
ast_sip_location_update_contact()
int ast_sip_location_update_contact (struct ast_sip_contact * contact)
Update a contact.
Parameters
contact New contact object with details
Return values
-1 failure
0 success
Definition at line 445 of file location.c.
References ast_sip_get_sorcery(), and ast_sorcery_update().
Referenced by register_aor_core().
 {
    return ast_sorcery_update(ast_sip_get_sorcery(), contact);
 }
ast_sip_message_apply_transport()
void ast_sip_message_apply_transport (const char * transport_name, pjsip_tx_data * tdata)
Apply the configuration for a transport to an outgoing message.
Since
17.0.0
Parameters
transport_name The name of the transport to apply configuration from
tdata The SIP message
Definition at line 301 of file config_transport.c.
References ao2_lock, ao2_ref, ao2_unlock, ast_sip_add_header(), ast_sip_get_transport_state(), ast_strlen_zero, AST_VECTOR_GET, AST_VECTOR_SIZE, ast_sip_transport_state::flow, ast_sip_transport_state::preferred_identity, and ast_sip_transport_state::service_routes.
Referenced by ast_sip_send_out_of_dialog_request(), handle_outgoing_request(), handle_outgoing_response(), and supplement_outgoing_response().
 {
    struct ast_sip_transport_state *transport_state;
    if (ast_strlen_zero(transport_name)) {
       return;
    }
    /* We only currently care about requests that are of the INVITE, CANCEL, or OPTIONS
     * type but in the future we could support other messages.
     */
    if (tdata->msg->type != PJSIP_REQUEST_MSG ||
       (pjsip_method_cmp(&tdata->msg->line.req.method, &pjsip_invite_method) &&
       pjsip_method_cmp(&tdata->msg->line.req.method, &pjsip_cancel_method) &&
       pjsip_method_cmp(&tdata->msg->line.req.method, &pjsip_options_method))) {
       return;
    }
    transport_state = ast_sip_get_transport_state(transport_name);
    if (!transport_state) {
       return;
    }
    if (!transport_state->flow) {
       ao2_ref(transport_state, -1);
       return;
    }
    ao2_lock(transport_state);
    /* If a Preferred Identity has been set then add it to the request */
    if (transport_state->preferred_identity) {
       ast_sip_add_header(tdata, "P-Preferred-Identity", transport_state->preferred_identity);
    }
    /* If Service Routes have been set then add them to the request */
    if (transport_state->service_routes) {
       int idx;
       for (idx = 0; idx < AST_VECTOR_SIZE(transport_state->service_routes); ++idx) {
          char *service_route = AST_VECTOR_GET(transport_state->service_routes, idx);
          ast_sip_add_header(tdata, "Route", service_route);
       }
    }
    ao2_unlock(transport_state);
    ao2_ref(transport_state, -1);
 }
ast_sip_modify_id_header()
void ast_sip_modify_id_header (pj_pool_t * pool, pjsip_fromto_hdr * id_hdr, const struct ast_party_id * id)
Set name and number information on an identity header.
Parameters
pool Memory pool to use for string duplication
id_hdr A From, P-Asserted-Identity, or Remote-Party-ID header to modify
id The identity information to apply to the header
Definition at line 5587 of file res_pjsip.c.
References ast_alloca, ast_escape_quoted(), ast_strlen_zero, ast_party_id::name, NULL, ast_party_id::number, ast_party_name::str, ast_party_number::str, ast_party_name::valid, and ast_party_number::valid.
Referenced by add_pai_header(), add_rpid_header(), and set_from_header().
 {
    pjsip_name_addr *id_name_addr;
    pjsip_sip_uri *id_uri;
    id_name_addr = (pjsip_name_addr *) id_hdr->uri;
    id_uri = pjsip_uri_get_uri(id_name_addr->uri);
    if (id->name.valid) {
       if (!ast_strlen_zero(id->name.str)) {
          int name_buf_len = strlen(id->name.str) * 2 + 1;
          char *name_buf = ast_alloca(name_buf_len);
          ast_escape_quoted(id->name.str, name_buf, name_buf_len);
          pj_strdup2(pool, &id_name_addr->display, name_buf);
       } else {
          pj_strdup2(pool, &id_name_addr->display, NULL);
       }
    }
    if (id->number.valid) {
       pj_strdup2(pool, &id_uri->user, id->number.str);
    }
 }
ast_sip_persistent_endpoint_publish_contact_state()
void ast_sip_persistent_endpoint_publish_contact_state (const char * endpoint_name, const struct ast_sip_contact_status * contact_status)
Publish the change of state for a contact.
Parameters
endpoint_name The SIP endpoint name.
contact_status The contact status.
Definition at line 1386 of file pjsip_configuration.c.
References ao2_find, ao2_ref, ast_sip_contact_status::aor, ast_endpoint_blob_publish(), ast_endpoint_contact_state_type(), ast_endpoint_get_resource(), ast_json_pack(), ast_json_unref(), ast_sip_get_contact_status_label(), sip_persistent_endpoint::endpoint, OBJ_SEARCH_KEY, ast_sip_contact_status::rtt, ast_sip_contact_status::status, and ast_sip_contact_status::uri.
Referenced by sip_options_publish_contact_state().
 {
    struct sip_persistent_endpoint *persistent;
    struct ast_json *blob;
    char rtt[32];
    persistent = ao2_find(persistent_endpoints, endpoint_name, OBJ_SEARCH_KEY);
    if (!persistent) {
       return;
    }
    snprintf(rtt, sizeof(rtt), "%" PRId64, contact_status->rtt);
    blob = ast_json_pack("{s: s, s: s, s: s, s: s, s: s}",
       "contact_status", ast_sip_get_contact_status_label(contact_status->status),
       "aor", contact_status->aor,
       "uri", contact_status->uri,
       "roundtrip_usec", rtt,
       "endpoint_name", ast_endpoint_get_resource(persistent->endpoint));
    if (blob) {
       ast_endpoint_blob_publish(persistent->endpoint, ast_endpoint_contact_state_type(), blob);
       ast_json_unref(blob);
    }
    ao2_ref(persistent, -1);
 }
ast_sip_persistent_endpoint_update_state()
int ast_sip_persistent_endpoint_update_state (const char * endpoint_name, enum ast_endpoint_state state)
Change state of a persistent endpoint.
Parameters
endpoint_name The SIP endpoint name to change state.
state The new state
Return values
0 Success
-1 Endpoint not found
Definition at line 1329 of file pjsip_configuration.c.
References ao2_find, ao2_ref, ast_add_extension(), ast_context_remove_extension(), AST_DEVICE_UNKNOWN, AST_DEVSTATE_CACHABLE, ast_devstate_changed(), ast_endpoint_blob_publish(), ast_endpoint_get_resource(), ast_endpoint_get_state(), AST_ENDPOINT_OFFLINE, AST_ENDPOINT_ONLINE, ast_endpoint_set_state(), ast_endpoint_state_type(), ast_exists_extension(), ast_free, ast_free_ptr(), ast_json_pack(), ast_json_unref(), ast_sip_get_regcontext(), ast_strdup, ast_strlen_zero, ast_verb, E_MATCH, sip_persistent_endpoint::endpoint, NULL, OBJ_SEARCH_KEY, pbx_find_extension(), regcontext, and pbx_find_info::stacklen.
Referenced by sip_options_synchronize_endpoint(), sip_options_unused_endpoint_state_compositor(), and sip_options_update_endpoint_state_compositor_aor().
 {
    struct sip_persistent_endpoint *persistent;
    struct ast_json *blob;
    char *regcontext;
    persistent = ao2_find(persistent_endpoints, endpoint_name, OBJ_SEARCH_KEY);
    if (!persistent) {
       return -1;
    }
    /* If there was no state change, don't publish anything. */
    if (ast_endpoint_get_state(persistent->endpoint) == state) {
       ao2_ref(persistent, -1);
       return 0;
    }
    regcontext = ast_sip_get_regcontext();
    if (state == AST_ENDPOINT_ONLINE) {
       ast_endpoint_set_state(persistent->endpoint, AST_ENDPOINT_ONLINE);
       blob = ast_json_pack("{s: s}", "peer_status", "Reachable");
       if (!ast_strlen_zero(regcontext)) {
          if (!ast_exists_extension(NULL, regcontext, ast_endpoint_get_resource(persistent->endpoint), 1, NULL)) {
             ast_add_extension(regcontext, 1, ast_endpoint_get_resource(persistent->endpoint), 1, NULL, NULL,
                "Noop", ast_strdup(ast_endpoint_get_resource(persistent->endpoint)), ast_free_ptr, "PJSIP");
          }
       }
       ast_verb(2, "Endpoint %s is now Reachable\n", ast_endpoint_get_resource(persistent->endpoint));
    } else {
       ast_endpoint_set_state(persistent->endpoint, AST_ENDPOINT_OFFLINE);
       blob = ast_json_pack("{s: s}", "peer_status", "Unreachable");
       if (!ast_strlen_zero(regcontext)) {
          struct pbx_find_info q = { .stacklen = 0 };
          if (pbx_find_extension(NULL, NULL, &q, regcontext, ast_endpoint_get_resource(persistent->endpoint), 1, NULL, "", E_MATCH)) {
             ast_context_remove_extension(regcontext, ast_endpoint_get_resource(persistent->endpoint), 1, NULL);
          }
       }
       ast_verb(2, "Endpoint %s is now Unreachable\n", ast_endpoint_get_resource(persistent->endpoint));
    }
    ast_free(regcontext);
    ast_endpoint_blob_publish(persistent->endpoint, ast_endpoint_state_type(), blob);
    ast_json_unref(blob);
    ast_devstate_changed(AST_DEVICE_UNKNOWN, AST_DEVSTATE_CACHABLE, "PJSIP/%s", ast_endpoint_get_resource(persistent->endpoint));
    ao2_ref(persistent, -1);
    return 0;
 }
ast_sip_rdata_get_header_value()
char* ast_sip_rdata_get_header_value (pjsip_rx_data * rdata, const pj_str_t str)
Get a specific header value from rdata.
Note
The returned value does not need to be freed since it's from the rdata pool
Parameters
rdata The rdata
str The header to find
Return values
NULL on failure
The header value on success
Definition at line 3543 of file res_pjsip.c.
References NULL.
Referenced by stir_shaken_incoming_request().
 {
    pjsip_generic_string_hdr *hdr;
    pj_str_t hdr_val;
    hdr = pjsip_msg_find_hdr_by_name(rdata->msg_info.msg, &str, NULL);
    if (!hdr) {
       return NULL;
    }
    pj_strdup_with_null(rdata->tp_info.pool, &hdr_val, &hdr->hvalue);
    return hdr_val.ptr;
 }
ast_sip_register_authenticator()
int ast_sip_register_authenticator (struct ast_sip_authenticator * auth)
Register a SIP authenticator.
An authenticator has three main purposes: 1) Determining if authentication should be performed on an incoming request 2) Gathering credentials necessary for issuing an authentication challenge 3) Authenticating a request that has credentials
Asterisk provides a default authenticator, but it may be replaced by a custom one if desired.
Parameters
auth The authenticator to register
Return values
0 Success
-1 Failure
Definition at line 3338 of file res_pjsip.c.
References ast_debug, ast_log, and LOG_WARNING.
Referenced by load_module().
 {
    if (registered_authenticator) {
       ast_log(LOG_WARNING, "Authenticator %p is already registered. Cannot register a new one\n", registered_authenticator);
       return -1;
    }
    registered_authenticator = auth;
    ast_debug(1, "Registered SIP authenticator module %p\n", auth);
    return 0;
 }
ast_sip_register_endpoint_formatter()
void ast_sip_register_endpoint_formatter (struct ast_sip_endpoint_formatter * obj)
Register an endpoint formatter.
Parameters
obj the formatter to register
Definition at line 3679 of file res_pjsip.c.
References AST_RWLIST_INSERT_TAIL, AST_RWLIST_UNLOCK, AST_RWLIST_WRLOCK, lock, ast_cli_entry::next, and SCOPED_LOCK.
Referenced by ast_res_pjsip_init_options_handling(), ast_sip_initialize_sorcery_auth(), ast_sip_initialize_sorcery_location(), ast_sip_initialize_sorcery_transport(), and load_module().
 {
    SCOPED_LOCK(lock, &endpoint_formatters, AST_RWLIST_WRLOCK, AST_RWLIST_UNLOCK);
    AST_RWLIST_INSERT_TAIL(&endpoint_formatters, obj, next);
 }
ast_sip_register_endpoint_identifier()
int ast_sip_register_endpoint_identifier (struct ast_sip_endpoint_identifier * identifier)
Register a SIP endpoint identifier.
An endpoint identifier's purpose is to determine which endpoint a given SIP message has come from.
Multiple endpoint identifiers may be registered so that if an endpoint cannot be identified by one identifier, it may be identified by another.
Asterisk provides two endpoint identifiers. One identifies endpoints based on the user part of the From header URI. The other identifies endpoints based on the source IP address.
If the order in which endpoint identifiers is run is important to you, then be sure to load individual endpoint identifier modules in the order you wish for them to be run in modules.conf
Note
endpoint identifiers registered using this method (no name specified) are placed at the front of the endpoint identifiers list ahead of any named identifiers.
Parameters
identifier The SIP endpoint identifier to register
Return values
0 Success
-1 Failure
Definition at line 3508 of file res_pjsip.c.
References ast_sip_register_endpoint_identifier_with_name(), and NULL.
Referenced by load_module().
 {
    return ast_sip_register_endpoint_identifier_with_name(identifier, NULL);
 }
ast_sip_register_endpoint_identifier_with_name()
int ast_sip_register_endpoint_identifier_with_name (struct ast_sip_endpoint_identifier * identifier, const char * name)
Register a SIP endpoint identifier with a name.
An endpoint identifier's purpose is to determine which endpoint a given SIP message has come from.
Multiple endpoint identifiers may be registered so that if an endpoint cannot be identified by one identifier, it may be identified by another.
Parameters
identifier The SIP endpoint identifier to register
name The name of the endpoint identifier
Return values
0 Success
-1 Failure
Definition at line 3431 of file res_pjsip.c.
References ast_calloc, ast_debug, ast_free, ast_log, AST_RWLIST_EMPTY, AST_RWLIST_INSERT_AFTER, AST_RWLIST_INSERT_BEFORE_CURRENT, AST_RWLIST_INSERT_HEAD, AST_RWLIST_INSERT_TAIL, AST_RWLIST_NEXT, AST_RWLIST_TRAVERSE_SAFE_BEGIN, AST_RWLIST_TRAVERSE_SAFE_END, AST_RWLIST_UNLOCK, AST_RWLIST_WRLOCK, ast_sip_get_endpoint_identifier_order(), ast_strlen_zero, endpoint_identifier_list::identifier, lock, LOG_ERROR, endpoint_identifier_list::name, endpoint_identifier_list::priority, and SCOPED_LOCK.
Referenced by ast_sip_register_endpoint_identifier(), and load_module().
 {
    char *prev, *current, *identifier_order;
    struct endpoint_identifier_list *iter, *id_list_item;
    SCOPED_LOCK(lock, &endpoint_identifiers, AST_RWLIST_WRLOCK, AST_RWLIST_UNLOCK);
    id_list_item = ast_calloc(1, sizeof(*id_list_item));
    if (!id_list_item) {
       ast_log(LOG_ERROR, "Unable to add endpoint identifier. Out of memory.\n");
       return -1;
    }
    id_list_item->identifier = identifier;
    id_list_item->name = name;
    ast_debug(1, "Register endpoint identifier %s(%p)\n", name ?: "", identifier);
    if (ast_strlen_zero(name)) {
       /* if an identifier has no name then place in front */
       AST_RWLIST_INSERT_HEAD(&endpoint_identifiers, id_list_item, list);
       return 0;
    }
    /* see if the name of the identifier is in the global endpoint_identifier_order list */
    identifier_order = prev = current = ast_sip_get_endpoint_identifier_order();
    if (ast_strlen_zero(identifier_order)) {
       id_list_item->priority = UINT_MAX;
       AST_RWLIST_INSERT_TAIL(&endpoint_identifiers, id_list_item, list);
       ast_free(identifier_order);
       return 0;
    }
    id_list_item->priority = 0;
    while ((current = strchr(current, ','))) {
       ++id_list_item->priority;
       if (!strncmp(prev, name, current - prev)
          && strlen(name) == current - prev) {
          break;
       }
       prev = ++current;
    }
    if (!current) {
       /* check to see if it is the only or last item */
       if (!strcmp(prev, name)) {
          ++id_list_item->priority;
       } else {
          id_list_item->priority = UINT_MAX;
       }
    }
    if (id_list_item->priority == UINT_MAX || AST_RWLIST_EMPTY(&endpoint_identifiers)) {
       /* if not in the endpoint_identifier_order list then consider it less in
          priority and add it to the end */
       AST_RWLIST_INSERT_TAIL(&endpoint_identifiers, id_list_item, list);
       ast_free(identifier_order);
       return 0;
    }
    AST_RWLIST_TRAVERSE_SAFE_BEGIN(&endpoint_identifiers, iter, list) {
       if (id_list_item->priority < iter->priority) {
          AST_RWLIST_INSERT_BEFORE_CURRENT(id_list_item, list);
          break;
       }
       if (!AST_RWLIST_NEXT(iter, list)) {
          AST_RWLIST_INSERT_AFTER(&endpoint_identifiers, iter, id_list_item, list);
          break;
       }
    }
    AST_RWLIST_TRAVERSE_SAFE_END;
    ast_free(identifier_order);
    return 0;
 }
ast_sip_register_outbound_authenticator()
int ast_sip_register_outbound_authenticator (struct ast_sip_outbound_authenticator * outbound_auth)
Register an outbound SIP authenticator.
An outbound authenticator is responsible for creating responses to authentication challenges by remote endpoints.
Parameters
auth The authenticator to register
Return values
0 Success
-1 Failure
Definition at line 3389 of file res_pjsip.c.
References ast_debug, ast_log, and LOG_WARNING.
Referenced by load_module().
 {
    if (registered_outbound_authenticator) {
       ast_log(LOG_WARNING, "Outbound authenticator %p is already registered. Cannot register a new one\n", registered_outbound_authenticator);
       return -1;
    }
    registered_outbound_authenticator = auth;
    ast_debug(1, "Registered SIP outbound authenticator module %p\n", auth);
    return 0;
 }
ast_sip_register_service()
int ast_sip_register_service (pjsip_module * module)
Register a SIP service in Asterisk.
This is more-or-less a wrapper around pjsip_endpt_register_module(). Registering a service makes it so that PJSIP will call into the service at appropriate times. For more information about PJSIP module callbacks, see the PJSIP documentation. Asterisk modules that call this function will likely do so at module load time.
Parameters
module The module that is to be registered with PJSIP
Return values
0 Success
-1 Failure
Definition at line 3315 of file res_pjsip.c.
References ast_sip_push_task_wait_servant(), NULL, and register_service().
Referenced by ast_res_pjsip_init_message_filter(), ast_sip_initialize_distributor(), ast_sip_initialize_global_headers(), ast_sip_initialize_transport_management(), and load_module().
 {
    return ast_sip_push_task_wait_servant(NULL, register_service, &module);
 }
ast_sip_register_supplement()
void ast_sip_register_supplement (struct ast_sip_supplement * supplement)
Register a supplement to SIP out of dialog processing.
This allows for someone to insert themselves in the processing of out of dialog SIP requests and responses. This, for example could allow for a module to set channel data based on headers in an incoming message. Similarly, a module could reject an incoming request if desired.
Parameters
supplement The supplement to register
Return values
0 Success
-1 Failure
Definition at line 4511 of file res_pjsip.c.
References AST_RWLIST_INSERT_BEFORE_CURRENT, AST_RWLIST_INSERT_TAIL, AST_RWLIST_TRAVERSE_SAFE_BEGIN, AST_RWLIST_TRAVERSE_SAFE_END, AST_RWLIST_UNLOCK, AST_RWLIST_WRLOCK, lock, ast_sip_supplement::next, ast_sip_supplement::priority, and SCOPED_LOCK.
Referenced by ast_res_pjsip_init_message_filter(), and load_module().
 {
    struct ast_sip_supplement *iter;
    int inserted = 0;
    SCOPED_LOCK(lock, &supplements, AST_RWLIST_WRLOCK, AST_RWLIST_UNLOCK);
    AST_RWLIST_TRAVERSE_SAFE_BEGIN(&supplements, iter, next) {
       if (iter->priority > supplement->priority) {
          AST_RWLIST_INSERT_BEFORE_CURRENT(supplement, next);
          inserted = 1;
          break;
       }
    }
    AST_RWLIST_TRAVERSE_SAFE_END;
    if (!inserted) {
       AST_RWLIST_INSERT_TAIL(&supplements, supplement, next);
    }
 }
ast_sip_report_auth_challenge_sent()
void ast_sip_report_auth_challenge_sent (struct ast_sip_endpoint * endpoint, pjsip_rx_data * rdata, pjsip_tx_data * tdata)
Send a security event notification for when an authentication challenge is sent.
Parameters
endpoint Pointer to the endpoint in use
rdata Received message
tdata Sent message
Definition at line 197 of file res/res_pjsip/security_events.c.
References ast_copy_pj_str(), AST_SEC_EVT, AST_SECURITY_EVENT_CHAL_SENT, AST_SECURITY_EVENT_CHAL_SENT_VERSION, ast_security_event_report(), ast_security_event_chal_sent::common, ast_security_event_common::event_type, get_account_id(), NULL, security_event_get_transport(), and security_event_populate().
Referenced by authenticate().
 {
    pjsip_www_authenticate_hdr *auth = pjsip_msg_find_hdr(tdata->msg, PJSIP_H_WWW_AUTHENTICATE, NULL);
    enum ast_transport transport = security_event_get_transport(rdata);
    char nonce[64] = "", call_id[pj_strlen(&rdata->msg_info.cid->id) + 1];
    struct ast_sockaddr local, remote;
    struct ast_security_event_chal_sent chal_sent = {
          .common.event_type = AST_SECURITY_EVENT_CHAL_SENT,
          .common.version    = AST_SECURITY_EVENT_CHAL_SENT_VERSION,
          .common.service    = "PJSIP",
          .common.account_id = get_account_id(endpoint),
          .common.local_addr = {
                .addr      = &local,
                .transport = transport,
          },
          .common.remote_addr = {
                .addr      = &remote,
                .transport = transport,
          },
          .common.session_id = call_id,
          .challenge         = nonce,
    };
    if (auth && !pj_strcmp2(&auth->scheme, "digest")) {
       ast_copy_pj_str(nonce, &auth->challenge.digest.nonce, sizeof(nonce));
    }
    security_event_populate(rdata, call_id, sizeof(call_id), &local, &remote);
    ast_security_event_report(AST_SEC_EVT(&chal_sent));
 }
ast_sip_report_auth_failed_challenge_response()
void ast_sip_report_auth_failed_challenge_response (struct ast_sip_endpoint * endpoint, pjsip_rx_data * rdata)
Send a security event notification for when a challenge response has failed.
Parameters
endpoint Pointer to the endpoint in use
rdata Received message
Definition at line 130 of file res/res_pjsip/security_events.c.
References ast_copy_pj_str(), AST_SEC_EVT, AST_SECURITY_EVENT_CHAL_RESP_FAILED, AST_SECURITY_EVENT_CHAL_RESP_FAILED_VERSION, ast_security_event_report(), ast_security_event_chal_resp_failed::common, ast_security_event_common::event_type, get_account_id(), NULL, ast_security_event_chal_resp_failed::response, security_event_get_transport(), and security_event_populate().
Referenced by authenticate().
 {
    pjsip_authorization_hdr *auth = pjsip_msg_find_hdr(rdata->msg_info.msg, PJSIP_H_AUTHORIZATION, NULL);
    enum ast_transport transport = security_event_get_transport(rdata);
    char call_id[pj_strlen(&rdata->msg_info.cid->id) + 1];
    char nonce[64] = "", response[256] = "";
    struct ast_sockaddr local, remote;
    struct ast_security_event_chal_resp_failed chal_resp_failed = {
             .common.event_type = AST_SECURITY_EVENT_CHAL_RESP_FAILED,
             .common.version    = AST_SECURITY_EVENT_CHAL_RESP_FAILED_VERSION,
             .common.service    = "PJSIP",
             .common.account_id = get_account_id(endpoint),
             .common.local_addr = {
                   .addr      = &local,
                   .transport = transport,
             },
             .common.remote_addr = {
                   .addr      = &remote,
                   .transport = transport,
             },
             .common.session_id = call_id,
             .challenge         = nonce,
             .response          = response,
             .expected_response = "",
    };
    if (auth && !pj_strcmp2(&auth->scheme, "Digest")) {
       ast_copy_pj_str(nonce, &auth->credential.digest.nonce, sizeof(nonce));
       ast_copy_pj_str(response, &auth->credential.digest.response, sizeof(response));
    }
    security_event_populate(rdata, call_id, sizeof(call_id), &local, &remote);
    ast_security_event_report(AST_SEC_EVT(&chal_resp_failed));
 }
ast_sip_report_auth_success()
void ast_sip_report_auth_success (struct ast_sip_endpoint * endpoint, pjsip_rx_data * rdata)
Send a security event notification for when authentication succeeds.
Parameters
endpoint Pointer to the endpoint in use
rdata Received message
Definition at line 168 of file res/res_pjsip/security_events.c.
References AST_SEC_EVT, ast_security_event_report(), AST_SECURITY_EVENT_SUCCESSFUL_AUTH, AST_SECURITY_EVENT_SUCCESSFUL_AUTH_VERSION, ast_security_event_successful_auth::common, ast_security_event_common::event_type, get_account_id(), NULL, security_event_get_transport(), and security_event_populate().
Referenced by authenticate().
 {
    pjsip_authorization_hdr *auth = pjsip_msg_find_hdr(rdata->msg_info.msg, PJSIP_H_AUTHORIZATION, NULL);
    enum ast_transport transport = security_event_get_transport(rdata);
    char call_id[pj_strlen(&rdata->msg_info.cid->id) + 1];
    struct ast_sockaddr local, remote;
    struct ast_security_event_successful_auth successful_auth = {
          .common.event_type  = AST_SECURITY_EVENT_SUCCESSFUL_AUTH,
          .common.version     = AST_SECURITY_EVENT_SUCCESSFUL_AUTH_VERSION,
          .common.service     = "PJSIP",
          .common.account_id  = get_account_id(endpoint),
          .common.local_addr  = {
                .addr       = &local,
                .transport  = transport,
          },
          .common.remote_addr = {
                .addr       = &remote,
                .transport  = transport,
          },
          .common.session_id  = call_id,
          .using_password     = auth ? 1 : 0,
    };
    security_event_populate(rdata, call_id, sizeof(call_id), &local, &remote);
    ast_security_event_report(AST_SEC_EVT(&successful_auth));
 }
ast_sip_report_failed_acl()
void ast_sip_report_failed_acl (struct ast_sip_endpoint * endpoint, pjsip_rx_data * rdata, const char * name)
Send a security event notification for when an ACL check fails.
Parameters
endpoint Pointer to the endpoint in use
rdata Received message
name Name of the ACL
Definition at line 102 of file res/res_pjsip/security_events.c.
References AST_SEC_EVT, AST_SECURITY_EVENT_FAILED_ACL, AST_SECURITY_EVENT_FAILED_ACL_VERSION, ast_security_event_report(), ast_security_event_failed_acl::common, ast_security_event_common::event_type, get_account_id(), name, security_event_get_transport(), and security_event_populate().
Referenced by apply_endpoint_acl(), apply_endpoint_contact_acl(), register_aor_core(), and registrar_on_rx_request().
 {
    enum ast_transport transport = security_event_get_transport(rdata);
    char call_id[pj_strlen(&rdata->msg_info.cid->id) + 1];
    struct ast_sockaddr local, remote;
    struct ast_security_event_failed_acl failed_acl_event = {
          .common.event_type  = AST_SECURITY_EVENT_FAILED_ACL,
          .common.version     = AST_SECURITY_EVENT_FAILED_ACL_VERSION,
          .common.service     = "PJSIP",
          .common.account_id  = get_account_id(endpoint),
          .common.local_addr  = {
                .addr       = &local,
                .transport  = transport,
          },
          .common.remote_addr = {
                .addr       = &remote,
                .transport  = transport,
          },
          .common.session_id  = call_id,
          .acl_name           = name,
    };
    security_event_populate(rdata, call_id, sizeof(call_id), &local, &remote);
    ast_security_event_report(AST_SEC_EVT(&failed_acl_event));
 }
ast_sip_report_invalid_endpoint()
void ast_sip_report_invalid_endpoint (const char * name, pjsip_rx_data * rdata)
Send a security event notification for when an invalid endpoint is requested.
Parameters
name Name of the endpoint requested
rdata Received message
Definition at line 75 of file res/res_pjsip/security_events.c.
References AST_SEC_EVT, AST_SECURITY_EVENT_INVAL_ACCT_ID, AST_SECURITY_EVENT_INVAL_ACCT_ID_VERSION, ast_security_event_report(), ast_security_event_inval_acct_id::common, ast_security_event_common::event_type, name, security_event_get_transport(), and security_event_populate().
Referenced by check_endpoint(), and endpoint_lookup().
 {
    enum ast_transport transport = security_event_get_transport(rdata);
    char call_id[pj_strlen(&rdata->msg_info.cid->id) + 1];
    struct ast_sockaddr local, remote;
    struct ast_security_event_inval_acct_id inval_acct_id = {
       .common.event_type = AST_SECURITY_EVENT_INVAL_ACCT_ID,
       .common.version    = AST_SECURITY_EVENT_INVAL_ACCT_ID_VERSION,
       .common.service    = "PJSIP",
       .common.account_id = name,
       .common.local_addr = {
          .addr      = &local,
          .transport = transport,
       },
       .common.remote_addr = {
          .addr       = &remote,
          .transport = transport,
       },
       .common.session_id = call_id,
    };
    security_event_populate(rdata, call_id, sizeof(call_id), &local, &remote);
    ast_security_event_report(AST_SEC_EVT(&inval_acct_id));
 }
ast_sip_report_mem_limit()
void ast_sip_report_mem_limit (struct ast_sip_endpoint * endpoint, pjsip_rx_data * rdata)
Send a security event notification for when a memory limit is hit.
Parameters
endpoint Pointer to the endpoint in use
rdata Received message
Definition at line 259 of file res/res_pjsip/security_events.c.
References AST_SEC_EVT, AST_SECURITY_EVENT_MEM_LIMIT, AST_SECURITY_EVENT_MEM_LIMIT_VERSION, ast_security_event_report(), ast_security_event_mem_limit::common, ast_security_event_common::event_type, get_account_id(), security_event_get_transport(), and security_event_populate().
 {
    enum ast_transport transport = security_event_get_transport(rdata);
    char call_id[pj_strlen(&rdata->msg_info.cid->id) + 1];
    struct ast_sockaddr local, remote;
    struct ast_security_event_mem_limit mem_limit_event = {
       .common.event_type  = AST_SECURITY_EVENT_MEM_LIMIT,
       .common.version     = AST_SECURITY_EVENT_MEM_LIMIT_VERSION,
       .common.service     = "PJSIP",
       .common.account_id  = get_account_id(endpoint),
       .common.local_addr  = {
          .addr       = &local,
          .transport  = transport,
       },
       .common.remote_addr = {
          .addr       = &remote,
          .transport  = transport,
       },
       .common.session_id  = call_id
    };
    security_event_populate(rdata, call_id, sizeof(call_id), &local, &remote);
    ast_security_event_report(AST_SEC_EVT(&mem_limit_event));
 }
ast_sip_report_req_no_support()
void ast_sip_report_req_no_support (struct ast_sip_endpoint * endpoint, pjsip_rx_data * rdata, const char * req_type)
Send a security event notification for when a request is not supported.
Parameters
endpoint Pointer to the endpoint in use
rdata Received message
req_type the type of request
Definition at line 230 of file res/res_pjsip/security_events.c.
References AST_SEC_EVT, ast_security_event_report(), AST_SECURITY_EVENT_REQ_NO_SUPPORT, AST_SECURITY_EVENT_REQ_NO_SUPPORT_VERSION, ast_security_event_req_no_support::common, ast_security_event_common::event_type, get_account_id(), security_event_get_transport(), and security_event_populate().
Referenced by find_registrar_aor(), and registrar_on_rx_request().
 {
    enum ast_transport transport = security_event_get_transport(rdata);
    char call_id[pj_strlen(&rdata->msg_info.cid->id) + 1];
    struct ast_sockaddr local, remote;
    struct ast_security_event_req_no_support req_no_support_event = {
       .common.event_type  = AST_SECURITY_EVENT_REQ_NO_SUPPORT,
       .common.version     = AST_SECURITY_EVENT_REQ_NO_SUPPORT_VERSION,
       .common.service     = "PJSIP",
       .common.account_id  = get_account_id(endpoint),
       .common.local_addr  = {
          .addr       = &local,
          .transport  = transport,
       },
       .common.remote_addr = {
          .addr       = &remote,
          .transport  = transport,
       },
       .common.session_id  = call_id,
       .request_type       = req_type
    };
    security_event_populate(rdata, call_id, sizeof(call_id), &local, &remote);
    ast_security_event_report(AST_SEC_EVT(&req_no_support_event));
 }
ast_sip_requires_authentication()
int ast_sip_requires_authentication (struct ast_sip_endpoint * endpoint, pjsip_rx_data * rdata)
Determine if an incoming request requires authentication.
This calls into the registered authenticator's requires_authentication callback in order to determine if the request requires authentication.
If there is no registered authenticator, then authentication will be assumed not to be required.
Parameters
endpoint The endpoint from which the request originates
rdata The incoming SIP request
Return values
non-zero The request requires authentication
0 The request does not require authentication
Definition at line 3361 of file res_pjsip.c.
References ast_sip_endpoint::allow_unauthenticated_options, ast_debug, ast_log, LOG_WARNING, and ast_sip_authenticator::requires_authentication.
Referenced by authenticate().
 {
    if (endpoint->allow_unauthenticated_options
       && !pjsip_method_cmp(&rdata->msg_info.msg->line.req.method, &pjsip_options_method)) {
       ast_debug(3, "Skipping OPTIONS authentication due to endpoint configuration\n");
       return 0;
    }
    if (!registered_authenticator) {
       ast_log(LOG_WARNING, "No SIP authenticator registered. Assuming authentication is not required\n");
       return 0;
    }
    return registered_authenticator->requires_authentication(endpoint, rdata);
 }
ast_sip_retrieve_auths()
int ast_sip_retrieve_auths (const struct ast_sip_auth_vector * auths, struct ast_sip_auth ** out)
Retrieve relevant SIP auth structures from sorcery.
Parameters
auths Vector of sorcery IDs of auth credentials to retrieve
[out] out The retrieved auths are stored here
Definition at line 2360 of file pjsip_configuration.c.
References ast_log, ast_sip_get_sorcery(), ast_sorcery_retrieve_by_id(), AST_VECTOR_GET, AST_VECTOR_SIZE, LOG_NOTICE, and name.
Referenced by digest_check_auth(), and set_outbound_initial_authentication_credentials().
 {
    int i;
    for (i = 0; i < AST_VECTOR_SIZE(auths); ++i) {
       /* Using AST_VECTOR_GET is safe since the vector is immutable */
       const char *name = AST_VECTOR_GET(auths, i);
       out[i] = ast_sorcery_retrieve_by_id(ast_sip_get_sorcery(), SIP_SORCERY_AUTH_TYPE, name);
       if (!out[i]) {
          ast_log(LOG_NOTICE, "Couldn't find auth '%s'. Cannot authenticate\n", name);
          return -1;
       }
    }
    return 0;
 }
ast_sip_retrieve_auths_vector()
int ast_sip_retrieve_auths_vector (const struct ast_sip_auth_vector * auth_ids, struct ast_sip_auth_objects_vector * auth_objects)
Definition at line 2385 of file pjsip_configuration.c.
References ast_log, ast_sip_get_sorcery(), ast_sorcery_retrieve_by_id(), AST_VECTOR_APPEND, AST_VECTOR_GET, AST_VECTOR_SIZE, LOG_WARNING, and name.
Referenced by digest_create_request_with_auth().
 {
    int i;
    for (i = 0; i < AST_VECTOR_SIZE(auth_ids); ++i) {
       /* Using AST_VECTOR_GET is safe since the vector is immutable */
       const char *name = AST_VECTOR_GET(auth_ids, i);
       struct ast_sip_auth *auth_object = ast_sorcery_retrieve_by_id(ast_sip_get_sorcery(), SIP_SORCERY_AUTH_TYPE, name);
       if (!auth_object) {
          ast_log(LOG_WARNING, "Auth object '%s' could not be found\n", name);
       } else {
          AST_VECTOR_APPEND(auth_objects, auth_object);
       }
    }
    return AST_VECTOR_SIZE(auth_objects) == AST_VECTOR_SIZE(auth_ids) ? 0 : -1;
 }
ast_sip_send_out_of_dialog_request()
int ast_sip_send_out_of_dialog_request (pjsip_tx_data * tdata, struct ast_sip_endpoint * endpoint, int timeout, void * token, void(*)(void *token, pjsip_event *e) callback)
General purpose method for sending an Out-Of-Dialog SIP request.
This is a companion function for ast_sip_create_request. The request created there can be passed to this function, though any request may be passed in.
This will automatically set up handling outbound authentication challenges if they arrive.
Parameters
tdata The request to send
endpoint Optional. If specified, the out-of-dialog request is sent to the endpoint.
timeout. If non-zero, after the timeout the transaction will be terminated and the callback will be called with the PJSIP_EVENT_TIMER type.
token Data to be passed to the callback upon receipt of out-of-dialog response.
callback Callback to be called upon receipt of out-of-dialog response.
Return values
0 Success
-1 Failure (out-of-dialog callback will not be called.)
Note
Timeout processing: There are 2 timers associated with this request, PJSIP timer_b which is set globally in the "system" section of pjsip.conf, and the timeout specified on this call. The timer that expires first (before normal completion) will cause the callback to be run with e->body.tsx_state.type = PJSIP_EVENT_TIMER. The timer that expires second is simply ignored and the callback is not run again.
Definition at line 4993 of file res_pjsip.c.
References ao2_cleanup, AST_LIST_TRAVERSE, AST_RWLIST_RDLOCK, AST_RWLIST_UNLOCK, ast_sip_message_apply_transport(), ast_sip_mod_data_get, ast_sip_mod_data_set, does_method_match(), endpt_send_request(), ast_sip_supplement::method, MOD_DATA_CONTACT, NULL, ast_sip_supplement::outgoing_request, send_request_data_alloc(), supplement_module, and ast_sip_endpoint::transport.
Referenced by ast_sip_send_request(), and sip_options_qualify_contact().
 {
    struct ast_sip_supplement *supplement;
    struct send_request_data *req_data;
    struct ast_sip_contact *contact;
    req_data = send_request_data_alloc(endpoint, token, callback);
    if (!req_data) {
       pjsip_tx_data_dec_ref(tdata);
       return -1;
    }
    if (endpoint) {
       ast_sip_message_apply_transport(endpoint->transport, tdata);
    }
    contact = ast_sip_mod_data_get(tdata->mod_data, supplement_module.id, MOD_DATA_CONTACT);
    AST_RWLIST_RDLOCK(&supplements);
    AST_LIST_TRAVERSE(&supplements, supplement, next) {
       if (supplement->outgoing_request
          && does_method_match(&tdata->msg->line.req.method.name, supplement->method)) {
          supplement->outgoing_request(endpoint, contact, tdata);
       }
    }
    AST_RWLIST_UNLOCK(&supplements);
    ast_sip_mod_data_set(tdata->pool, tdata->mod_data, supplement_module.id, MOD_DATA_CONTACT, NULL);
    ao2_cleanup(contact);
    if (endpt_send_request(endpoint, tdata, timeout, req_data, send_request_cb)
       != PJ_SUCCESS) {
       ao2_cleanup(req_data);
       return -1;
    }
    return 0;
 }
ast_sip_send_request()
int ast_sip_send_request (pjsip_tx_data * tdata, struct pjsip_dialog * dlg, struct ast_sip_endpoint * endpoint, void * token, void(*)(void *token, pjsip_event *e) callback)
General purpose method for sending a SIP request.
This is a companion function for ast_sip_create_request. The request created there can be passed to this function, though any request may be passed in.
This will automatically set up handling outbound authentication challenges if they arrive.
Parameters
tdata The request to send
dlg Optional. The dialog in which the request is sent. Otherwise it is out-of-dialog.
endpoint Optional. If specified, the out-of-dialog request is sent to the endpoint.
token Data to be passed to the callback upon receipt of out-of-dialog response.
callback Callback to be called upon receipt of out-of-dialog response.
Return values
0 Success
-1 Failure (out-of-dialog callback will not be called.)
Definition at line 5034 of file res_pjsip.c.
References ast_assert, ast_sip_send_out_of_dialog_request(), and send_in_dialog_request().
Referenced by msg_send(), notify_channel(), notify_contact(), notify_uri(), send_unsolicited_mwi_notify_to_contact(), and sendtext().
 {
    ast_assert(tdata->msg->type == PJSIP_REQUEST_MSG);
    if (dlg) {
       return send_in_dialog_request(tdata, dlg);
    } else {
       return ast_sip_send_out_of_dialog_request(tdata, endpoint, -1, token, callback);
    }
 }
ast_sip_send_response()
int ast_sip_send_response (pjsip_response_addr * res_addr, pjsip_tx_data * tdata, struct ast_sip_endpoint * sip_endpoint)
Send a response to an out of dialog request.
Use this function sparingly, since this does not create a transaction within PJSIP. This means that if the request is retransmitted, it is your responsibility to detect this and not process the same request twice, and to send the same response for each retransmission.
Parameters
res_addr The response address for this response
tdata The response to send
endpoint The ast_sip_endpoint associated with this response
Return values
0 Success
-1 Failure
Definition at line 5407 of file res_pjsip.c.
References ast_sip_get_pjsip_endpoint(), NULL, status, and supplement_outgoing_response().
 {
    pj_status_t status;
    supplement_outgoing_response(tdata, sip_endpoint);
    status = pjsip_endpt_send_response(ast_sip_get_pjsip_endpoint(), res_addr, tdata, NULL, NULL);
    if (status != PJ_SUCCESS) {
       pjsip_tx_data_dec_ref(tdata);
    }
    return status == PJ_SUCCESS ? 0 : -1;
 }
ast_sip_send_stateful_response()
int ast_sip_send_stateful_response (pjsip_rx_data * rdata, pjsip_tx_data * tdata, struct ast_sip_endpoint * sip_endpoint)
Send a stateful response to an out of dialog request.
This creates a transaction within PJSIP, meaning that if the request that we are responding to is retransmitted, we will not attempt to re-handle the request.
Parameters
rdata The request that is being responded to
tdata The response to send
endpoint The ast_sip_endpoint associated with this response
Since
13.4.0
Return values
0 Success
-1 Failure
Definition at line 5420 of file res_pjsip.c.
References ao2_cleanup, ast_sip_mod_data_get, ast_sip_mod_data_set, MOD_DATA_CONTACT, NULL, supplement_module, and supplement_outgoing_response().
Referenced by register_aor(), send_options_response(), and send_response().
 {
    pjsip_transaction *tsx;
    if (pjsip_tsx_create_uas(NULL, rdata, &tsx) != PJ_SUCCESS) {
       struct ast_sip_contact *contact;
       /* ast_sip_create_response bumps the refcount of the contact and adds it to the tdata.
        * We'll leak that reference if we don't get rid of it here.
        */
       contact = ast_sip_mod_data_get(tdata->mod_data, supplement_module.id, MOD_DATA_CONTACT);
       ao2_cleanup(contact);
       ast_sip_mod_data_set(tdata->pool, tdata->mod_data, supplement_module.id, MOD_DATA_CONTACT, NULL);
       pjsip_tx_data_dec_ref(tdata);
       return -1;
    }
    pjsip_tsx_recv_msg(tsx, rdata);
    supplement_outgoing_response(tdata, sip_endpoint);
    if (pjsip_tsx_send_msg(tsx, tdata) != PJ_SUCCESS) {
       pjsip_tx_data_dec_ref(tdata);
       return -1;
    }
    return 0;
 }
ast_sip_service_route_vector_alloc()
struct ast_sip_service_route_vector* ast_sip_service_route_vector_alloc (void)
Allocate a vector of service routes.
Since
17.0.0
Return values
non-NULL success
NULL failure
Definition at line 352 of file config_transport.c.
References ast_calloc, AST_VECTOR_INIT, and NULL.
Referenced by save_response_fields_to_transport().
 {
    struct ast_sip_service_route_vector *service_routes;
    service_routes = ast_calloc(1, sizeof(*service_routes));
    if (!service_routes) {
       return NULL;
    }
    AST_VECTOR_INIT(service_routes, 0);
    return service_routes;
 }
ast_sip_service_route_vector_destroy()
void ast_sip_service_route_vector_destroy (struct ast_sip_service_route_vector * service_routes)
Destroy a vector of service routes.
Since
17.0.0
Parameters
service_routes A vector of service routes
Definition at line 366 of file config_transport.c.
References ast_free, and AST_VECTOR_CALLBACK_VOID.
Referenced by ast_sip_transport_state_set_service_routes(), and save_response_fields_to_transport().
 {
    if (!service_routes) {
       return;
    }
    AST_VECTOR_CALLBACK_VOID(service_routes, ast_free);
    ast_free(service_routes);
 }
ast_sip_set_outbound_proxy()
int ast_sip_set_outbound_proxy (pjsip_tx_data * tdata, const char * proxy)
Set the outbound proxy for an outbound SIP message.
Parameters
tdata The message to set the outbound proxy on
proxy SIP uri of the proxy
Return values
0 Success
-1 Failure
Definition at line 5047 of file res_pjsip.c.
References NULL, and tmp().
Referenced by create_out_of_dialog_request(), path_outgoing_request(), and sip_options_qualify_contact().
 {
    pjsip_route_hdr *route;
    static const pj_str_t ROUTE_HNAME = { "Route", 5 };
    pj_str_t tmp;
    pj_strdup2_with_null(tdata->pool, &tmp, proxy);
    if (!(route = pjsip_parse_hdr(tdata->pool, &ROUTE_HNAME, tmp.ptr, tmp.slen, NULL))) {
       return -1;
    }
    pj_list_insert_nodes_before(&tdata->msg->hdr, (pjsip_hdr*)route);
    return 0;
 }
ast_sip_set_tpselector_from_ep_or_uri()
int ast_sip_set_tpselector_from_ep_or_uri (const struct ast_sip_endpoint * endpoint, pjsip_sip_uri * sip_uri, pjsip_tpselector * selector)
Sets pjsip_tpselector from an endpoint or uri.
Since
13.15.0
Parameters
endpoint If endpoint->transport is set, it's used
sip_uri If sip_uri contains a x-ast-txp parameter, it's used
selector The selector to be populated
Return values
0 success
-1 failure
Definition at line 3975 of file res_pjsip.c.
References ast_sip_get_transport_name(), and ast_sip_set_tpselector_from_transport_name().
Referenced by ast_sip_dlg_set_transport(), create_dialog_uas(), and create_out_of_dialog_request().
 {
    char transport_name[128];
    if (ast_sip_get_transport_name(endpoint, sip_uri, transport_name, sizeof(transport_name))) {
       return 0;
    }
    return ast_sip_set_tpselector_from_transport_name(transport_name, selector);
 }
ast_sip_set_tpselector_from_transport()
int ast_sip_set_tpselector_from_transport (const struct ast_sip_transport * transport, pjsip_tpselector * selector)
Sets pjsip_tpselector from ast_sip_transport.
Since
13.8.0
Parameters
transport The transport to be used
selector The selector to be populated
Return values
0 success
-1 failure
Note
The transport selector must be unreffed using ast_sip_tpselector_unref
Definition at line 3907 of file res_pjsip.c.
References ao2_lock, ao2_ref, ao2_unlock, ast_log, ast_sip_get_transport_state(), ast_sorcery_object_get_id(), AST_TRANSPORT_WS, AST_TRANSPORT_WSS, ast_sip_transport_state::factory, ast_sip_transport_state::flow, ast_sip_transport::flow, LOG_ERROR, LOG_WARNING, ast_sip_transport_state::transport, and ast_sip_transport::type.
Referenced by ast_sip_set_tpselector_from_transport_name().
 {
    int res = 0;
    struct ast_sip_transport_state *transport_state;
    transport_state = ast_sip_get_transport_state(ast_sorcery_object_get_id(transport));
    if (!transport_state) {
       ast_log(LOG_ERROR, "Unable to retrieve PJSIP transport state for '%s'\n",
          ast_sorcery_object_get_id(transport));
       return -1;
    }
    /* Only flows maintain dynamic state which needs protection */
    if (transport_state->flow) {
       ao2_lock(transport_state);
    }
    if (transport_state->transport) {
       selector->type = PJSIP_TPSELECTOR_TRANSPORT;
       selector->u.transport = transport_state->transport;
       pjsip_transport_add_ref(selector->u.transport);
    } else if (transport_state->factory) {
       selector->type = PJSIP_TPSELECTOR_LISTENER;
       selector->u.listener = transport_state->factory;
    } else if (transport->type == AST_TRANSPORT_WS || transport->type == AST_TRANSPORT_WSS) {
       /* The WebSocket transport has no factory as it can not create outgoing connections, so
        * even if an endpoint is locked to a WebSocket transport we let the PJSIP logic
        * find the existing connection if available and use it.
        */
    } else if (transport->flow) {
       /* This is a child of another transport, so we need to establish a new connection */
 #ifdef HAVE_PJSIP_TRANSPORT_DISABLE_CONNECTION_REUSE
       selector->disable_connection_reuse = PJ_TRUE;
 #else
       ast_log(LOG_WARNING, "Connection reuse could not be disabled on transport '%s' as support is not available\n",
          ast_sorcery_object_get_id(transport));
 #endif
    } else {
       res = -1;
    }
    if (transport_state->flow) {
       ao2_unlock(transport_state);
    }
    ao2_ref(transport_state, -1);
    return res;
 }
ast_sip_set_tpselector_from_transport_name()
int ast_sip_set_tpselector_from_transport_name (const char * transport_name, pjsip_tpselector * selector)
Sets pjsip_tpselector from ast_sip_transport.
Since
13.8.0
Parameters
transport_name The name of the transport to be used
selector The selector to be populated
Return values
0 success
-1 failure
Note
The transport selector must be unreffed using ast_sip_tpselector_unref
Definition at line 3957 of file res_pjsip.c.
References ao2_cleanup, ast_log, ast_sip_get_sorcery(), ast_sip_set_tpselector_from_transport(), ast_sorcery_retrieve_by_id(), ast_strlen_zero, LOG_ERROR, NULL, RAII_VAR, and ast_sip_transport_state::transport.
Referenced by ast_sip_set_tpselector_from_ep_or_uri(), registration_client_send(), set_transport(), and sip_outbound_registration_regc_alloc().
 {
    RAII_VAR(struct ast_sip_transport *, transport, NULL, ao2_cleanup);
    if (ast_strlen_zero(transport_name)) {
       return 0;
    }
    transport = ast_sorcery_retrieve_by_id(ast_sip_get_sorcery(), "transport", transport_name);
    if (!transport) {
       ast_log(LOG_ERROR, "Unable to retrieve PJSIP transport '%s'\n",
          transport_name);
       return -1;
    }
    return ast_sip_set_tpselector_from_transport(transport, selector);
 }
ast_sip_sorcery_object_to_ami()
int ast_sip_sorcery_object_to_ami (const void * obj, struct ast_str ** buf)
Converts a sorcery object to a string of object properties.
Parameters
obj the sorcery object to convert
str the string buffer to write the object data
Return values
0 Success, non-zero on failure
Definition at line 1609 of file pjsip_configuration.c.
References ast_free, AST_HANDLER_ONLY_STRING, ast_sip_get_sorcery(), ast_sorcery_objectset_create2(), ast_str_append(), ast_to_camel_case, ast_variables_destroy(), ast_variable::name, ast_variable::next, RAII_VAR, sip_sorcery_object_ami_set_type_name(), and ast_variable::value.
Referenced by ami_outbound_registration_task(), ami_registrations_aor(), format_ami_resource_lists(), sip_auth_to_ami(), sip_contact_to_ami(), sip_endpoint_to_ami(), sip_identify_to_ami(), and sip_transport_to_ami().
 {
    RAII_VAR(struct ast_variable *, objset, ast_sorcery_objectset_create2(
           ast_sip_get_sorcery(), obj, AST_HANDLER_ONLY_STRING), ast_variables_destroy);
    struct ast_variable *i;
    if (!objset) {
       return -1;
    }
    sip_sorcery_object_ami_set_type_name(obj, buf);
    for (i = objset; i; i = i->next) {
       RAII_VAR(char *, camel, ast_to_camel_case(i->name), ast_free);
       ast_str_append(buf, 0, "%s: %s\r\n", camel, i->value);
    }
    return 0;
 }
ast_sip_str_to_dtmf()
int ast_sip_str_to_dtmf (const char * dtmf_mode)
Convert the DTMF mode name into an enum.
Since
13.18.0
Parameters
dtmf_mode dtmf mode as a string
Return values
>= 0 The enum value
-1 Failure
Definition at line 5513 of file res_pjsip.c.
References AST_SIP_DTMF_AUTO, AST_SIP_DTMF_AUTO_INFO, AST_SIP_DTMF_INBAND, AST_SIP_DTMF_INFO, AST_SIP_DTMF_NONE, AST_SIP_DTMF_RFC_4733, and result.
Referenced by dtmf_handler(), and pjsip_acf_dtmf_mode_write().
 {
    int result = -1;
    if (!strcasecmp(dtmf_mode, "info")) {
       result = AST_SIP_DTMF_INFO;
    } else if (!strcasecmp(dtmf_mode, "rfc4733")) {
       result = AST_SIP_DTMF_RFC_4733;
    } else if (!strcasecmp(dtmf_mode, "inband")) {
       result = AST_SIP_DTMF_INBAND;
    } else if (!strcasecmp(dtmf_mode, "none")) {
       result = AST_SIP_DTMF_NONE;
    } else if (!strcasecmp(dtmf_mode, "auto")) {
       result = AST_SIP_DTMF_AUTO;
    } else if (!strcasecmp(dtmf_mode, "auto_info")) {
       result = AST_SIP_DTMF_AUTO_INFO;
    }
    return result;
 }
ast_sip_threadpool()
struct ast_threadpool* ast_sip_threadpool (void)
Retrieve the SIP threadpool object.
Definition at line 5630 of file res_pjsip.c.
References sip_threadpool.
Referenced by load_module().
 {
    return sip_threadpool;
 }
ast_sip_threadpool_queue_size()
long ast_sip_threadpool_queue_size (void)
Return the size of the SIP threadpool's task queue.
Since
13.7.0
Definition at line 5625 of file res_pjsip.c.
References ast_threadpool_queue_size().
 {
    return ast_threadpool_queue_size(sip_threadpool);
 }
ast_sip_tpselector_unref()
void ast_sip_tpselector_unref (pjsip_tpselector * selector)
Unreference a pjsip_tpselector.
Since
17.0.0
Parameters
selector The selector to be unreffed
Definition at line 3987 of file res_pjsip.c.
Referenced by ast_sip_create_dialog_uac(), ast_sip_dlg_set_transport(), create_dialog_uas(), create_out_of_dialog_request(), registration_client_send(), set_transport(), and sip_outbound_registration_regc_alloc().
 {
    if (selector->type == PJSIP_TPSELECTOR_TRANSPORT && selector->u.transport) {
       pjsip_transport_dec_ref(selector->u.transport);
    }
 }
ast_sip_transport_monitor_register()
enum ast_transport_monitor_reg ast_sip_transport_monitor_register (pjsip_transport * transport, ast_transport_monitor_shutdown_cb cb, void * ao2_data)
Register a reliable transport shutdown monitor callback.
Since
13.20.0
Parameters
transport Transport to monitor for shutdown.
cb Who to call when transport is shutdown.
ao2_data Data to pass with the callback.
Note
The data object passed will have its reference count automatically incremented by this call and automatically decremented after the callback runs or when the callback is unregistered.
There is no checking for duplicate registrations.
Returns
enum ast_transport_monitor_reg
Definition at line 306 of file pjsip_transport_events.c.
References ast_sip_transport_monitor_register_replace(), and NULL.
Referenced by registration_transport_monitor_setup(), and subscription_persistence_update().
 {
    return ast_sip_transport_monitor_register_replace(transport, cb, ao2_data, NULL);
 }
ast_sip_transport_monitor_register_replace()
enum ast_transport_monitor_reg ast_sip_transport_monitor_register_replace (pjsip_transport * transport, ast_transport_monitor_shutdown_cb cb, void * ao2_data, ast_transport_monitor_data_matcher matches)
Register a reliable transport shutdown monitor callback replacing any duplicate.
Since
13.26.0
16.3.0
Parameters
transport Transport to monitor for shutdown.
cb Who to call when transport is shutdown.
ao2_data Data to pass with the callback.
matches Matcher function that returns true if data matches a previously registered data object
Note
The data object passed will have its reference count automatically incremented by this call and automatically decremented after the callback runs or when the callback is unregistered.
This function checks for duplicates, and overwrites/replaces the old monitor with the given one.
Returns
enum ast_transport_monitor_reg
Definition at line 312 of file pjsip_transport_events.c.
References ao2_bump, ao2_cleanup, ao2_find, ao2_global_obj_ref, ao2_lock, ao2_ref, ao2_unlock, ast_assert, ast_debug, AST_TRANSPORT_MONITOR_REG_FAILED, AST_TRANSPORT_MONITOR_REG_NOT_FOUND, AST_TRANSPORT_MONITOR_REG_SUCCESS, AST_VECTOR_APPEND, transport_monitor_notifier::cb, callback_data::cb, transport_monitor_notifier::data, NULL, OBJ_NOLOCK, OBJ_SEARCH_KEY, ptr_matcher(), and transport_monitor_unregister_cb().
Referenced by ast_sip_transport_monitor_register(), and register_aor_core().
 {
    struct ao2_container *transports;
    struct transport_monitor *monitored;
    enum ast_transport_monitor_reg res = AST_TRANSPORT_MONITOR_REG_NOT_FOUND;
    ast_assert(transport != NULL && cb != NULL);
    transports = ao2_global_obj_ref(active_transports);
    if (!transports) {
       return res;
    }
    ao2_lock(transports);
    monitored = ao2_find(transports, transport->obj_name, OBJ_SEARCH_KEY | OBJ_NOLOCK);
    if (monitored) {
       struct transport_monitor_notifier new_monitor;
       struct callback_data cb_data = {
          .cb = cb,
          .data = ao2_data,
          .matches = matches ?: ptr_matcher,
       };
       transport_monitor_unregister_cb(monitored, &cb_data, 0);
       /* Add new monitor to vector */
       new_monitor.cb = cb;
       new_monitor.data = ao2_bump(ao2_data);
       if (AST_VECTOR_APPEND(&monitored->monitors, new_monitor)) {
          ao2_cleanup(ao2_data);
          res = AST_TRANSPORT_MONITOR_REG_FAILED;
          ast_debug(3, "Register monitor %p(%p) to transport %s FAILED\n",
             cb, ao2_data, transport->obj_name);
       } else {
          res = AST_TRANSPORT_MONITOR_REG_SUCCESS;
          ast_debug(3, "Registered monitor %p(%p) to transport %s\n",
             cb, ao2_data, transport->obj_name);
       }
       ao2_ref(monitored, -1);
    }
    ao2_unlock(transports);
    ao2_ref(transports, -1);
    return res;
 }
ast_sip_transport_monitor_unregister()
void ast_sip_transport_monitor_unregister (pjsip_transport * transport, ast_transport_monitor_shutdown_cb cb, void * data, ast_transport_monitor_data_matcher matches)
Unregister a reliable transport shutdown monitor.
Since
13.20.0
Parameters
transport Transport to monitor for shutdown.
cb The callback that was used for the original register.
data Data to pass to the matcher. May be NULL and does NOT need to be an ao2 object. If NULL, all monitors with the provided callbck are unregistered.
matches Matcher function that returns true if data matches the previously registered data object. If NULL, a simple pointer comparison is done.
Note
The data object passed into the original register will have its reference count automatically decremeneted.
Returns
Nothing
Definition at line 277 of file pjsip_transport_events.c.
References ao2_find, ao2_global_obj_ref, ao2_lock, ao2_ref, ao2_unlock, ast_assert, transport_monitor_notifier::cb, callback_data::cb, transport_monitor_notifier::data, NULL, OBJ_NOLOCK, OBJ_SEARCH_KEY, ptr_matcher(), and transport_monitor_unregister_cb().
Referenced by handle_registration_response(), registrar_contact_delete(), and subscription_persistence_remove().
 {
    struct ao2_container *transports;
    struct transport_monitor *monitored;
    ast_assert(transport != NULL && cb != NULL);
    transports = ao2_global_obj_ref(active_transports);
    if (!transports) {
       return;
    }
    ao2_lock(transports);
    monitored = ao2_find(transports, transport->obj_name, OBJ_SEARCH_KEY | OBJ_NOLOCK);
    if (monitored) {
       struct callback_data cb_data = {
          .cb = cb,
          .data = data,
          .matches = matches ?: ptr_matcher,
       };
       transport_monitor_unregister_cb(monitored, &cb_data, 0);
       ao2_ref(monitored, -1);
    }
    ao2_unlock(transports);
    ao2_ref(transports, -1);
 }
ast_sip_transport_monitor_unregister_all()
void ast_sip_transport_monitor_unregister_all (ast_transport_monitor_shutdown_cb cb, void * data, ast_transport_monitor_data_matcher matches)
Unregister a transport shutdown monitor from all reliable transports.
Since
13.20.0
Parameters
cb The callback that was used for the original register.
data Data to pass to the matcher. May be NULL and does NOT need to be an ao2 object. If NULL, all monitors with the provided callbck are unregistered.
matches Matcher function that returns true if ao2_data matches the previously registered data object. If NULL, a simple pointer comparison is done.
Note
The data object passed into the original register will have its reference count automatically decremeneted.
Returns
Nothing
Definition at line 257 of file pjsip_transport_events.c.
References ao2_callback, ao2_global_obj_ref, ao2_ref, ast_assert, transport_monitor_notifier::cb, callback_data::cb, transport_monitor_notifier::data, NULL, OBJ_MULTIPLE, OBJ_NODATA, ptr_matcher(), and transport_monitor_unregister_cb().
Referenced by registrar_contact_delete(), and unload_module().
 {
    struct ao2_container *transports;
    struct callback_data cb_data = {
       .cb = cb,
       .data = data,
       .matches = matches ?: ptr_matcher,
    };
    ast_assert(cb != NULL);
    transports = ao2_global_obj_ref(active_transports);
    if (!transports) {
       return;
    }
    ao2_callback(transports, OBJ_MULTIPLE | OBJ_NODATA, transport_monitor_unregister_cb, &cb_data);
    ao2_ref(transports, -1);
 }
ast_sip_transport_state_register()
void ast_sip_transport_state_register (struct ast_sip_tpmgr_state_callback * element)
Register a transport state notification callback element.
Since
13.18.0
Parameters
element What we are registering.
Returns
Nothing
Definition at line 366 of file pjsip_transport_events.c.
References AST_LIST_INSERT_HEAD, AST_LIST_TRAVERSE, AST_RWLIST_UNLOCK, AST_RWLIST_WRLOCK, and transport_state_list.
Referenced by ast_sip_initialize_transport_management().
 {
    struct ast_sip_tpmgr_state_callback *tpmgr_notifier;
    AST_RWLIST_WRLOCK(&transport_state_list);
    AST_LIST_TRAVERSE(&transport_state_list, tpmgr_notifier, node) {
       if (element == tpmgr_notifier) {
          /* Already registered. */
          AST_RWLIST_UNLOCK(&transport_state_list);
          return;
       }
    }
    AST_LIST_INSERT_HEAD(&transport_state_list, element, node);
    AST_RWLIST_UNLOCK(&transport_state_list);
 }
ast_sip_transport_state_set_preferred_identity()
int ast_sip_transport_state_set_preferred_identity (const char * transport_name, const char * identity)
Sets the P-Preferred-Identity on a child transport.
Since
17.0.0
Parameters
transport_name The name of the transport to be set on
identity The P-Preferred-Identity to use on requests on this transport
Return values
0 success
-1 failure
Definition at line 242 of file config_transport.c.
References ao2_lock, ao2_ref, ao2_unlock, ast_free, ast_sip_get_transport_state(), ast_strdup, ast_strlen_zero, ast_sip_transport_state::flow, and ast_sip_transport_state::preferred_identity.
Referenced by save_response_fields_to_transport().
 {
    struct ast_sip_transport_state *transport_state;
    if (ast_strlen_zero(transport_name)) {
       return 0;
    }
    transport_state = ast_sip_get_transport_state(transport_name);
    if (!transport_state) {
       return -1;
    }
    if (!transport_state->flow) {
       ao2_ref(transport_state, -1);
       return 0;
    }
    ao2_lock(transport_state);
    ast_free(transport_state->preferred_identity);
    transport_state->preferred_identity = ast_strdup(identity);
    ao2_unlock(transport_state);
    ao2_ref(transport_state, -1);
    return 0;
 }
ast_sip_transport_state_set_service_routes()
int ast_sip_transport_state_set_service_routes (const char * transport_name, struct ast_sip_service_route_vector * service_routes)
Sets the service routes on a child transport.
Since
17.0.0
Parameters
transport_name The name of the transport to be set on
service_routes A vector of service routes
Return values
0 success
-1 failure
Note
This assumes ownership of the service routes in both success and failure scenarios
Definition at line 270 of file config_transport.c.
References ao2_lock, ao2_ref, ao2_unlock, ast_sip_get_transport_state(), ast_sip_service_route_vector_destroy(), ast_strlen_zero, ast_sip_transport_state::flow, and ast_sip_transport_state::service_routes.
Referenced by save_response_fields_to_transport().
 {
    struct ast_sip_transport_state *transport_state;
    if (ast_strlen_zero(transport_name)) {
       ast_sip_service_route_vector_destroy(service_routes);
       return 0;
    }
    transport_state = ast_sip_get_transport_state(transport_name);
    if (!transport_state) {
       ast_sip_service_route_vector_destroy(service_routes);
       return -1;
    }
    if (!transport_state->flow) {
       ao2_ref(transport_state, -1);
       ast_sip_service_route_vector_destroy(service_routes);
       return 0;
    }
    ao2_lock(transport_state);
    ast_sip_service_route_vector_destroy(transport_state->service_routes);
    transport_state->service_routes = service_routes;
    ao2_unlock(transport_state);
    ao2_ref(transport_state, -1);
    return 0;
 }
ast_sip_transport_state_set_transport()
int ast_sip_transport_state_set_transport (const char * transport_name, pjsip_transport * transport)
Sets the PJSIP transport on a child transport.
Since
17.0.0
Parameters
transport_name The name of the transport to be updated
transport The PJSIP transport
Return values
0 success
-1 failure
Definition at line 206 of file config_transport.c.
References ao2_lock, ao2_ref, ao2_unlock, ast_sip_get_transport_state(), ast_strlen_zero, ast_sip_transport_state::flow, internal_state::transport, and ast_sip_transport_state::transport.
Referenced by save_response_fields_to_transport().
 {
    struct ast_sip_transport_state *transport_state;
    /* To make it easier on callers we allow an empty transport name */
    if (ast_strlen_zero(transport_name)) {
       return 0;
    }
    transport_state = ast_sip_get_transport_state(transport_name);
    if (!transport_state) {
       return -1;
    }
    if (!transport_state->flow) {
       ao2_ref(transport_state, -1);
       return 0;
    }
    ao2_lock(transport_state);
    if (transport_state->transport != transport) {
       if (transport_state->transport) {
          pjsip_transport_dec_ref(transport_state->transport);
       }
       transport_state->transport = transport;
       if (transport_state->transport) {
          pjsip_transport_add_ref(transport_state->transport);
       }
    }
    ao2_unlock(transport_state);
    ao2_ref(transport_state, -1);
    return 0;
 }
ast_sip_transport_state_unregister()
void ast_sip_transport_state_unregister (struct ast_sip_tpmgr_state_callback * element)
Unregister a transport state notification callback element.
Since
13.18.0
Parameters
element What we are unregistering.
Returns
Nothing
Definition at line 359 of file pjsip_transport_events.c.
References AST_LIST_REMOVE, AST_RWLIST_UNLOCK, AST_RWLIST_WRLOCK, and transport_state_list.
Referenced by ast_sip_destroy_transport_management().
 {
    AST_RWLIST_WRLOCK(&transport_state_list);
    AST_LIST_REMOVE(&transport_state_list, element, node);
    AST_RWLIST_UNLOCK(&transport_state_list);
 }
ast_sip_unregister_authenticator()
void ast_sip_unregister_authenticator (struct ast_sip_authenticator * auth)
Unregister a SIP authenticator.
When there is no authenticator registered, requests cannot be challenged or authenticated.
Parameters
auth The authenticator to unregister
Definition at line 3350 of file res_pjsip.c.
References ast_debug, ast_log, LOG_WARNING, and NULL.
Referenced by unload_module().
 {
    if (registered_authenticator != auth) {
       ast_log(LOG_WARNING, "Trying to unregister authenticator %p but authenticator %p registered\n",
             auth, registered_authenticator);
       return;
    }
    registered_authenticator = NULL;
    ast_debug(1, "Unregistered SIP authenticator %p\n", auth);
 }
ast_sip_unregister_endpoint_formatter()
void ast_sip_unregister_endpoint_formatter (struct ast_sip_endpoint_formatter * obj)
Unregister an endpoint formatter.
Parameters
obj the formatter to unregister
Definition at line 3685 of file res_pjsip.c.
References AST_RWLIST_REMOVE_CURRENT, AST_RWLIST_TRAVERSE_SAFE_BEGIN, AST_RWLIST_TRAVERSE_SAFE_END, AST_RWLIST_UNLOCK, AST_RWLIST_WRLOCK, lock, and SCOPED_LOCK.
Referenced by ast_res_pjsip_cleanup_options_handling(), ast_sip_destroy_sorcery_auth(), ast_sip_destroy_sorcery_location(), ast_sip_destroy_sorcery_transport(), and unload_module().
 {
    struct ast_sip_endpoint_formatter *i;
    SCOPED_LOCK(lock, &endpoint_formatters, AST_RWLIST_WRLOCK, AST_RWLIST_UNLOCK);
    AST_RWLIST_TRAVERSE_SAFE_BEGIN(&endpoint_formatters, i, next) {
       if (i == obj) {
          AST_RWLIST_REMOVE_CURRENT(next);
          break;
       }
    }
    AST_RWLIST_TRAVERSE_SAFE_END;
 }
ast_sip_unregister_endpoint_identifier()
void ast_sip_unregister_endpoint_identifier (struct ast_sip_endpoint_identifier * identifier)
Unregister a SIP endpoint identifier.
This stops an endpoint identifier from being used.
Parameters
identifier The SIP endoint identifier to unregister
Definition at line 3513 of file res_pjsip.c.
References ast_debug, ast_free, AST_RWLIST_REMOVE_CURRENT, AST_RWLIST_TRAVERSE_SAFE_BEGIN, AST_RWLIST_TRAVERSE_SAFE_END, AST_RWLIST_UNLOCK, AST_RWLIST_WRLOCK, endpoint_identifier_list::identifier, lock, and SCOPED_LOCK.
Referenced by unload_module().
 {
    struct endpoint_identifier_list *iter;
    SCOPED_LOCK(lock, &endpoint_identifiers, AST_RWLIST_WRLOCK, AST_RWLIST_UNLOCK);
    AST_RWLIST_TRAVERSE_SAFE_BEGIN(&endpoint_identifiers, iter, list) {
       if (iter->identifier == identifier) {
          AST_RWLIST_REMOVE_CURRENT(list);
          ast_free(iter);
          ast_debug(1, "Unregistered endpoint identifier %p\n", identifier);
          break;
       }
    }
    AST_RWLIST_TRAVERSE_SAFE_END;
 }
ast_sip_unregister_outbound_authenticator()
void ast_sip_unregister_outbound_authenticator (struct ast_sip_outbound_authenticator * auth)
Unregister an outbound SIP authenticator.
When there is no outbound authenticator registered, authentication challenges will be handled as any other final response would be.
Parameters
auth The authenticator to unregister
Definition at line 3401 of file res_pjsip.c.
References ast_debug, ast_log, LOG_WARNING, and NULL.
Referenced by unload_module().
 {
    if (registered_outbound_authenticator != auth) {
       ast_log(LOG_WARNING, "Trying to unregister outbound authenticator %p but outbound authenticator %p registered\n",
             auth, registered_outbound_authenticator);
       return;
    }
    registered_outbound_authenticator = NULL;
    ast_debug(1, "Unregistered SIP outbound authenticator %p\n", auth);
 }
ast_sip_unregister_service()
void ast_sip_unregister_service (pjsip_module * module)
This is the opposite of ast_sip_register_service(). Unregistering a service means that PJSIP will no longer call into the module any more. This will likely occur when an Asterisk module is unloaded.
Parameters
module The PJSIP module to unregister
Definition at line 3331 of file res_pjsip.c.
References ast_sip_push_task_wait_servant(), NULL, and unregister_service().
Referenced by ast_res_pjsip_cleanup_message_filter(), ast_sip_destroy_distributor(), ast_sip_destroy_global_headers(), ast_sip_destroy_transport_management(), load_module(), unload_module(), and unload_pjsip().
 {
    ast_sip_push_task_wait_servant(NULL, unregister_service, &module);
 }
ast_sip_unregister_supplement()
void ast_sip_unregister_supplement (struct ast_sip_supplement * supplement)
Unregister a an supplement to SIP out of dialog processing.
Parameters
supplement The supplement to unregister
Definition at line 4531 of file res_pjsip.c.
References AST_RWLIST_REMOVE_CURRENT, AST_RWLIST_TRAVERSE_SAFE_BEGIN, AST_RWLIST_TRAVERSE_SAFE_END, AST_RWLIST_UNLOCK, AST_RWLIST_WRLOCK, lock, ast_sip_supplement::next, and SCOPED_LOCK.
Referenced by ast_res_pjsip_cleanup_message_filter(), and unload_module().
 {
    struct ast_sip_supplement *iter;
    SCOPED_LOCK(lock, &supplements, AST_RWLIST_WRLOCK, AST_RWLIST_UNLOCK);
    AST_RWLIST_TRAVERSE_SAFE_BEGIN(&supplements, iter, next) {
       if (supplement == iter) {
          AST_RWLIST_REMOVE_CURRENT(next);
          break;
       }
    }
    AST_RWLIST_TRAVERSE_SAFE_END;
 }
AST_VECTOR() [1/2]
AST_VECTOR (ast_sip_service_route_vector , char *)
AST_VECTOR() [2/2]
AST_VECTOR (ast_sip_auth_objects_vector , struct ast_sip_auth *)
Retrieve relevant SIP auth structures from sorcery as a vector.
Parameters
auth_ids Vector of sorcery IDs of auth credentials to retrieve
[out] auth_objects A pointer ast_sip_auth_objects_vector to hold the objects
Return values
0 Success
-1 Number of auth objects found is less than the number of names supplied.
The number of auth objects retrieved may be less than the number of auth ids supplied if auth objects couldn't be found for some of them.
Since the ref count on all auith objects returned has been bumped, you must call ast_sip_cleanup_auth_objects_vector() to decrement the ref count on all of the auth objects in the vector, then call AST_VECTOR_FREE() on the vector itself.