Asterisk - The Open Source Telephony Project: app_zapateller.c File Reference
app_zapateller.c File Reference
Dial plan applications
Playback the special information tone to get rid of telemarketers.
#include "asterisk.h"
#include "asterisk/lock.h"
#include "asterisk/file.h"
#include "asterisk/channel.h"
#include "asterisk/pbx.h"
#include "asterisk/module.h"
#include "asterisk/translate.h"
#include "asterisk/app.h"
Functions
AST_MODULE_INFO_STANDARD_EXTENDED (ASTERISK_GPL_KEY, "Block Telemarketers with Special Information Tone")
static int load_module (void)
static int unload_module (void)
static int zapateller_exec (struct ast_channel *chan, const char *data)
Variables
static char * app = "Zapateller"
Detailed Description
Playback the special information tone to get rid of telemarketers.
Author
Mark Spencer marks.nosp@m.ter@.nosp@m.digiu.nosp@m.m.co.nosp@m.m
Definition in file app_zapateller.c.
Function Documentation
AST_MODULE_INFO_STANDARD_EXTENDED()
AST_MODULE_INFO_STANDARD_EXTENDED (ASTERISK_GPL_KEY , "Block Telemarketers with Special Information Tone")
Referenced by load_module().
load_module()
static int load_module (void) static
Definition at line 133 of file app_zapateller.c.
References app, AST_MODULE_INFO_STANDARD_EXTENDED(), AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, ast_register_application_xml, ASTERISK_GPL_KEY, and zapateller_exec().
 {
    return ((ast_register_application_xml(app, zapateller_exec)) ? AST_MODULE_LOAD_DECLINE : AST_MODULE_LOAD_SUCCESS);
 }
unload_module()
static int unload_module (void) static
Definition at line 128 of file app_zapateller.c.
References app, and ast_unregister_application().
 {
    return ast_unregister_application(app);
 }
zapateller_exec()
static int zapateller_exec (struct ast_channel * chan, const char * data) static
Definition at line 79 of file app_zapateller.c.
References answer(), args, ast_answer(), AST_APP_ARG, ast_channel_caller(), AST_DECLARE_APP_ARGS, ast_safe_sleep(), AST_STANDARD_APP_ARGS, AST_STATE_UP, ast_stopstream(), ast_strdupa, ast_strlen_zero, ast_tonepair(), options, parse(), and pbx_builtin_setvar_helper().
Referenced by load_module().
 {
    int res = 0;
    int i, answer = 0, nocallerid = 0;
    char *parse = ast_strdupa((char *)data);
    AST_DECLARE_APP_ARGS(args,
       AST_APP_ARG(options)[2];
    );
    AST_STANDARD_APP_ARGS(args, parse);
    for (i = 0; i < args.argc; i++) {
       if (!strcasecmp(args.options[i], "answer"))
          answer = 1;
       else if (!strcasecmp(args.options[i], "nocallerid"))
          nocallerid = 1;
    }
    pbx_builtin_setvar_helper(chan, "ZAPATELLERSTATUS", "NOTHING");
    ast_stopstream(chan);
    if (ast_channel_state(chan) != AST_STATE_UP) {
       if (answer) {
          res = ast_answer(chan);
          pbx_builtin_setvar_helper(chan, "ZAPATELLERSTATUS", "ANSWERED");
       }
       if (!res)
          res = ast_safe_sleep(chan, 500);
    }
    if (nocallerid /* Zap caller if no caller id. */
       && ast_channel_caller(chan)->id.number.valid
       && !ast_strlen_zero(ast_channel_caller(chan)->id.number.str)) {
       /* We have caller id. */
       return res;
    }
    if (!res)
       res = ast_tonepair(chan, 950, 0, 330, 0);
    if (!res)
       res = ast_tonepair(chan, 1400, 0, 330, 0);
    if (!res)
       res = ast_tonepair(chan, 1800, 0, 330, 0);
    if (!res)
       res = ast_tonepair(chan, 0, 0, 1000, 0);
    pbx_builtin_setvar_helper(chan, "ZAPATELLERSTATUS", "ZAPPED");
    return res;
 }
Variable Documentation
app
char* app = "Zapateller" static
Definition at line 77 of file app_zapateller.c.
Referenced by load_module(), and unload_module().