Asterisk - The Open Source Telephony Project: bridge_builtin_interval_features.c File Reference
bridge_builtin_interval_features.c File Reference
Built in bridging interval features.
#include "asterisk.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>
#include "asterisk/module.h"
#include "asterisk/channel.h"
#include "asterisk/bridge.h"
#include "asterisk/file.h"
#include "asterisk/app.h"
#include "asterisk/astobj2.h"
#include "asterisk/test.h"
#include "asterisk/say.h"
#include "asterisk/stringfields.h"
#include "asterisk/musiconhold.h"
#include "asterisk/causes.h"
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int bridge_builtin_set_limits (struct ast_bridge_features *features, struct ast_bridge_features_limits *limits, enum ast_bridge_hook_remove_flags remove_flags)
static int bridge_features_connect_callback (struct ast_bridge_channel *bridge_channel, void *hook_pvt)
static int bridge_features_duration_callback (struct ast_bridge_channel *bridge_channel, void *hook_pvt)
static void bridge_features_limits_copy (struct ast_bridge_features_limits *dst, struct ast_bridge_features_limits *src)
static void bridge_features_limits_dtor (void *vdoomed)
static int bridge_features_warning_callback (struct ast_bridge_channel *bridge_channel, void *hook_pvt)
static void limits_interval_playback (struct ast_bridge_channel *bridge_channel, struct ast_bridge_features_limits *limits, const char *file)
static int load_module (void)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Built in bridging interval features" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, }
static const struct ast_module_info * ast_module_info = &__mod_info
Detailed Description
Built in bridging interval features.
Author
Jonathan Rose jrose.nosp@m.@dig.nosp@m.ium.c.nosp@m.om
Definition in file bridge_builtin_interval_features.c.
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 215 of file bridge_builtin_interval_features.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 215 of file bridge_builtin_interval_features.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 215 of file bridge_builtin_interval_features.c.
bridge_builtin_set_limits()
static int bridge_builtin_set_limits (struct ast_bridge_features * features, struct ast_bridge_features_limits * limits, enum ast_bridge_hook_remove_flags remove_flags) static
Definition at line 148 of file bridge_builtin_interval_features.c.
References __ao2_cleanup(), AO2_ALLOC_OPT_LOCK_NOLOCK, ao2_alloc_options, ao2_cleanup, ao2_ref, ast_bridge_features_limits_construct(), AST_BRIDGE_HOOK_TIMER_OPTION_MEDIA, ast_bridge_interval_hook(), ast_log, ast_module_ref, ast_module_unref, ast_samp2tv(), ast_strlen_zero, ast_tvadd(), ast_tvnow(), bridge_features_connect_callback(), bridge_features_duration_callback(), bridge_features_limits_copy(), bridge_features_limits_dtor(), bridge_features_warning_callback(), ast_bridge_features_limits::duration, LOG_ERROR, LOG_WARNING, NULL, RAII_VAR, and ast_module_info::self.
Referenced by load_module().
 {
    RAII_VAR(struct ast_bridge_features_limits *, feature_limits, NULL, ao2_cleanup);
    if (!limits->duration) {
       return -1;
    }
    /* Create limits hook_pvt data. */
    ast_module_ref(ast_module_info->self);
    feature_limits = ao2_alloc_options(sizeof(*feature_limits),
       bridge_features_limits_dtor, AO2_ALLOC_OPT_LOCK_NOLOCK);
    if (!feature_limits) {
       ast_module_unref(ast_module_info->self);
       return -1;
    }
    if (ast_bridge_features_limits_construct(feature_limits)) {
       return -1;
    }
    bridge_features_limits_copy(feature_limits, limits);
    feature_limits->quitting_time = ast_tvadd(ast_tvnow(),
       ast_samp2tv(feature_limits->duration, 1000));
    /* Install limit hooks. */
    ao2_ref(feature_limits, +1);
    if (ast_bridge_interval_hook(features, AST_BRIDGE_HOOK_TIMER_OPTION_MEDIA,
       feature_limits->duration,
       bridge_features_duration_callback, feature_limits, __ao2_cleanup, remove_flags)) {
       ast_log(LOG_ERROR, "Failed to schedule the duration limiter to the bridge channel.\n");
       ao2_ref(feature_limits, -1);
       return -1;
    }
    if (!ast_strlen_zero(feature_limits->connect_sound)) {
       ao2_ref(feature_limits, +1);
       if (ast_bridge_interval_hook(features, AST_BRIDGE_HOOK_TIMER_OPTION_MEDIA, 1,
          bridge_features_connect_callback, feature_limits, __ao2_cleanup, remove_flags)) {
          ast_log(LOG_WARNING, "Failed to schedule connect sound to the bridge channel.\n");
          ao2_ref(feature_limits, -1);
       }
    }
    if (feature_limits->warning && feature_limits->warning < feature_limits->duration) {
       ao2_ref(feature_limits, +1);
       if (ast_bridge_interval_hook(features, AST_BRIDGE_HOOK_TIMER_OPTION_MEDIA,
          feature_limits->duration - feature_limits->warning,
          bridge_features_warning_callback, feature_limits, __ao2_cleanup, remove_flags)) {
          ast_log(LOG_WARNING, "Failed to schedule warning sound playback to the bridge channel.\n");
          ao2_ref(feature_limits, -1);
       }
    }
    return 0;
 }
bridge_features_connect_callback()
static int bridge_features_connect_callback (struct ast_bridge_channel * bridge_channel, void * hook_pvt) static
Definition at line 115 of file bridge_builtin_interval_features.c.
References ast_bridge_features_limits::connect_sound, and limits_interval_playback().
Referenced by bridge_builtin_set_limits().
 {
    struct ast_bridge_features_limits *limits = hook_pvt;
    limits_interval_playback(bridge_channel, limits, limits->connect_sound);
    return -1;
 }
bridge_features_duration_callback()
static int bridge_features_duration_callback (struct ast_bridge_channel * bridge_channel, void * hook_pvt) static
Definition at line 51 of file bridge_builtin_interval_features.c.
References ast_bridge_channel_leave_bridge(), AST_CAUSE_NORMAL_CLEARING, ast_channel_name(), AST_DIGIT_NONE, ast_stream_and_wait(), ast_strlen_zero, ast_test_suite_event_notify, BRIDGE_CHANNEL_STATE_END, ast_bridge_channel::chan, and ast_bridge_features_limits::duration_sound.
Referenced by bridge_builtin_set_limits().
 {
    struct ast_bridge_features_limits *limits = hook_pvt;
    if (!ast_strlen_zero(limits->duration_sound)) {
       ast_stream_and_wait(bridge_channel->chan, limits->duration_sound, AST_DIGIT_NONE);
    }
    ast_bridge_channel_leave_bridge(bridge_channel, BRIDGE_CHANNEL_STATE_END,
       AST_CAUSE_NORMAL_CLEARING);
    ast_test_suite_event_notify("BRIDGE_TIMELIMIT", "Channel1: %s",
       ast_channel_name(bridge_channel->chan));
    return -1;
 }
bridge_features_limits_copy()
static void bridge_features_limits_copy (struct ast_bridge_features_limits * dst, struct ast_bridge_features_limits * src) static
Definition at line 131 of file bridge_builtin_interval_features.c.
References ast_string_fields_copy, ast_bridge_features_limits::duration, ast_bridge_features_limits::frequency, ast_bridge_features_limits::quitting_time, and ast_bridge_features_limits::warning.
Referenced by bridge_builtin_set_limits().
 {
    ast_string_fields_copy(dst, src);
    dst->quitting_time = src->quitting_time;
    dst->duration = src->duration;
    dst->warning = src->warning;
    dst->frequency = src->frequency;
 }
bridge_features_limits_dtor()
static void bridge_features_limits_dtor (void * vdoomed) static
Definition at line 140 of file bridge_builtin_interval_features.c.
References ast_bridge_features_limits_destroy(), ast_module_unref, and ast_module_info::self.
Referenced by bridge_builtin_set_limits().
 {
    struct ast_bridge_features_limits *doomed = vdoomed;
    ast_bridge_features_limits_destroy(doomed);
    ast_module_unref(ast_module_info->self);
 }
bridge_features_warning_callback()
static int bridge_features_warning_callback (struct ast_bridge_channel * bridge_channel, void * hook_pvt) static
Definition at line 123 of file bridge_builtin_interval_features.c.
References ast_bridge_features_limits::frequency, limits_interval_playback(), and ast_bridge_features_limits::warning_sound.
Referenced by bridge_builtin_set_limits().
 {
    struct ast_bridge_features_limits *limits = hook_pvt;
    limits_interval_playback(bridge_channel, limits, limits->warning_sound);
    return limits->frequency ?: -1;
 }
limits_interval_playback()
static void limits_interval_playback (struct ast_bridge_channel * bridge_channel, struct ast_bridge_features_limits * limits, const char * file) static
Definition at line 67 of file bridge_builtin_interval_features.c.
References ast_channel_flags(), ast_channel_language(), ast_channel_latest_musicclass(), ast_channel_lock, ast_channel_unlock, AST_DIGIT_NONE, AST_FLAG_MOH, ast_moh_start(), ast_say_number(), ast_strdupa, ast_stream_and_wait(), ast_test_flag, ast_tvdiff_ms(), ast_tvnow(), ast_bridge_channel::chan, min, NULL, and ast_bridge_features_limits::quitting_time.
Referenced by bridge_features_connect_callback(), and bridge_features_warning_callback().
 {
    if (!strcasecmp(file, "timeleft")) {
       unsigned int remaining = ast_tvdiff_ms(limits->quitting_time, ast_tvnow()) / 1000;
       unsigned int min;
       unsigned int sec;
       if (remaining <= 0) {
          return;
       }
       if ((remaining / 60) > 1) {
          min = remaining / 60;
          sec = remaining % 60;
       } else {
          min = 0;
          sec = remaining;
       }
       ast_stream_and_wait(bridge_channel->chan, "vm-youhave", AST_DIGIT_NONE);
       if (min) {
          ast_say_number(bridge_channel->chan, min, AST_DIGIT_NONE,
             ast_channel_language(bridge_channel->chan), NULL);
          ast_stream_and_wait(bridge_channel->chan, "queue-minutes", AST_DIGIT_NONE);
       }
       if (sec) {
          ast_say_number(bridge_channel->chan, sec, AST_DIGIT_NONE,
             ast_channel_language(bridge_channel->chan), NULL);
          ast_stream_and_wait(bridge_channel->chan, "queue-seconds", AST_DIGIT_NONE);
       }
    } else {
       ast_stream_and_wait(bridge_channel->chan, file, AST_DIGIT_NONE);
    }
    /*
     * It may be necessary to resume music on hold after we finish
     * playing the announcment.
     */
    if (ast_test_flag(ast_channel_flags(bridge_channel->chan), AST_FLAG_MOH)) {
       const char *latest_musicclass;
       ast_channel_lock(bridge_channel->chan);
       latest_musicclass = ast_strdupa(ast_channel_latest_musicclass(bridge_channel->chan));
       ast_channel_unlock(bridge_channel->chan);
       ast_moh_start(bridge_channel->chan, latest_musicclass, NULL);
    }
 }
load_module()
static int load_module (void) static
Definition at line 209 of file bridge_builtin_interval_features.c.
References AST_BRIDGE_BUILTIN_INTERVAL_LIMITS, ast_bridge_interval_register(), and bridge_builtin_set_limits().
 {
    return ast_bridge_interval_register(AST_BRIDGE_BUILTIN_INTERVAL_LIMITS,
       bridge_builtin_set_limits);
 }
unload_module()
static int unload_module (void) static
Definition at line 203 of file bridge_builtin_interval_features.c.
References AST_BRIDGE_BUILTIN_INTERVAL_LIMITS, and ast_bridge_interval_unregister().
 {
    ast_bridge_interval_unregister(AST_BRIDGE_BUILTIN_INTERVAL_LIMITS);
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Built in bridging interval features" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, } static
Definition at line 215 of file bridge_builtin_interval_features.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 215 of file bridge_builtin_interval_features.c.