Asterisk - The Open Source Telephony Project: res_pjsip_mwi_body_generator.c File Reference
res_pjsip_mwi_body_generator.c File Reference
#include "asterisk.h"
#include <pjsip.h>
#include <pjsip_simple.h>
#include <pjlib.h>
#include "asterisk/res_pjsip.h"
#include "asterisk/res_pjsip_pubsub.h"
#include "asterisk/res_pjsip_body_generator_types.h"
#include "asterisk/module.h"
#include "asterisk/strings.h"
Macros
#define MWI_SUBTYPE "simple-message-summary"
#define MWI_TYPE "application"
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int load_module (void)
static void * mwi_allocate_body (void *data)
static void mwi_destroy_body (void *body)
static int mwi_generate_body_content (void *body, void *data)
static void mwi_to_string (void *body, struct ast_str **str)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "PJSIP MWI resource" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_CHANNEL_DEPEND, .requires = "res_pjsip,res_pjsip_pubsub", }
static const struct ast_module_info * ast_module_info = &__mod_info
static struct ast_sip_pubsub_body_generator mwi_generator
Macro Definition Documentation
MWI_SUBTYPE
#define MWI_SUBTYPE "simple-message-summary"
Definition at line 39 of file res_pjsip_mwi_body_generator.c.
MWI_TYPE
#define MWI_TYPE "application"
Definition at line 38 of file res_pjsip_mwi_body_generator.c.
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 118 of file res_pjsip_mwi_body_generator.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 118 of file res_pjsip_mwi_body_generator.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 118 of file res_pjsip_mwi_body_generator.c.
load_module()
static int load_module (void) static
Definition at line 98 of file res_pjsip_mwi_body_generator.c.
References AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, and ast_sip_pubsub_register_body_generator().
Referenced by unload_module().
 {
    if (ast_sip_pubsub_register_body_generator(&mwi_generator)) {
       return AST_MODULE_LOAD_DECLINE;
    }
    return AST_MODULE_LOAD_SUCCESS;
 }
mwi_allocate_body()
static void* mwi_allocate_body (void * data) static
Definition at line 41 of file res_pjsip_mwi_body_generator.c.
References ast_free, ast_malloc, ast_str_create, and NULL.
 {
    struct ast_str **mwi_str;
    mwi_str = ast_malloc(sizeof(*mwi_str));
    if (!mwi_str) {
       return NULL;
    }
    *mwi_str = ast_str_create(128);
    if (!*mwi_str) {
       ast_free(mwi_str);
       return NULL;
    }
    return mwi_str;
 }
mwi_destroy_body()
static void mwi_destroy_body (void * body) static
Definition at line 80 of file res_pjsip_mwi_body_generator.c.
References ast_free.
 {
    struct ast_str **mwi = body;
    ast_free(*mwi);
    ast_free(mwi);
 }
mwi_generate_body_content()
static int mwi_generate_body_content (void * body, void * data) static
Definition at line 57 of file res_pjsip_mwi_body_generator.c.
References ast_str_append(), ast_strlen_zero, ast_sip_message_accumulator::message_account, ast_sip_message_accumulator::new_msgs, and ast_sip_message_accumulator::old_msgs.
 {
    struct ast_str **mwi = body;
    struct ast_sip_message_accumulator *counter = data;
    ast_str_append(mwi, 0, "Messages-Waiting: %s\r\n",
          counter->new_msgs ? "yes" : "no");
    if (!ast_strlen_zero(counter->message_account))  {
       ast_str_append(mwi, 0, "Message-Account: %s\r\n", counter->message_account);
    }
    ast_str_append(mwi, 0, "Voice-Message: %d/%d (0/0)\r\n",
          counter->new_msgs, counter->old_msgs);
    return 0;
 }
mwi_to_string()
static void mwi_to_string (void * body, struct ast_str ** str) static
Definition at line 73 of file res_pjsip_mwi_body_generator.c.
References ast_str_buffer(), and ast_str_set().
 {
    struct ast_str **mwi = body;
    ast_str_set(str, 0, "%s", ast_str_buffer(*mwi));
 }
unload_module()
static int unload_module (void) static
Definition at line 106 of file res_pjsip_mwi_body_generator.c.
References AST_MODFLAG_LOAD_ORDER, AST_MODPRI_CHANNEL_DEPEND, AST_MODULE_INFO(), AST_MODULE_SUPPORT_CORE, ast_sip_pubsub_unregister_body_generator(), ASTERISK_GPL_KEY, and load_module().
 {
    ast_sip_pubsub_unregister_body_generator(&mwi_generator);
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "PJSIP MWI resource" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_CHANNEL_DEPEND, .requires = "res_pjsip,res_pjsip_pubsub", } static
Definition at line 118 of file res_pjsip_mwi_body_generator.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 118 of file res_pjsip_mwi_body_generator.c.
mwi_generator
struct ast_sip_pubsub_body_generator mwi_generator static
Definition at line 88 of file res_pjsip_mwi_body_generator.c.