Asterisk - The Open Source Telephony Project: cli.c File Reference
res/ari/cli.c File Reference
Command line for ARI.
#include "asterisk.h"
#include "asterisk/astobj2.h"
#include "asterisk/cli.h"
#include "asterisk/stasis_app.h"
#include "internal.h"
Data Structures
struct app_complete
struct user_complete
Functions
static char * ari_mkpasswd (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static char * ari_set_debug (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static char * ari_show (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static char * ari_show_app (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static char * ari_show_apps (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static char * ari_show_user (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static char * ari_show_users (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
int ast_ari_cli_register (void)
Register CLI commands for ARI.
void ast_ari_cli_unregister (void)
Unregister CLI commands for ARI.
static char * complete_ari_app (struct ast_cli_args *a, int include_all)
static int complete_ari_app_search (void *obj, void *arg, void *data, int flags)
static char * complete_ari_show_user (struct ast_cli_args *a)
static char * complete_ari_user (struct ast_cli_args *a)
static int complete_ari_user_search (void *obj, void *arg, void *data, int flags)
static int show_users_cb (void *obj, void *arg, int flags)
Variables
static struct ast_cli_entry cli_ari []
Detailed Description
Command line for ARI.
Author
David M. Lee, II dlee@.nosp@m.digi.nosp@m.um.co.nosp@m.m
Definition in file res/ari/cli.c.
Function Documentation
ari_mkpasswd()
static char* ari_mkpasswd (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) static
Definition at line 214 of file res/ari/cli.c.
References ast_cli_args::argc, ast_cli_args::argv, ast_cli(), ast_crypt_encrypt(), ast_free, CLI_FAILURE, CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::command, ast_cli_args::fd, NULL, RAII_VAR, and ast_cli_entry::usage.
 {
    RAII_VAR(char *, crypted, NULL, ast_free);
    switch (cmd) {
    case CLI_INIT:
       e->command = "ari mkpasswd";
       e->usage =
          "Usage: ari mkpasswd <password>\n"
          "       Encrypts a password for use in ari.conf\n"
          "       Be aware that the password will be shown in the\n"
          "       command line history. The mkpasswd shell command\n"
          "       may be preferable.\n"
          ;
       return NULL;
    case CLI_GENERATE:
       return NULL;
    default:
       break;
    }
    if (a->argc != 3) {
       return CLI_SHOWUSAGE;
    }
    crypted = ast_crypt_encrypt(a->argv[2]);
    if (!crypted) {
       ast_cli(a->fd, "Failed to encrypt password\n");
       return CLI_FAILURE;
    }
    ast_cli(a->fd,
       "; Copy the following two lines into ari.conf\n");
    ast_cli(a->fd, "password_format = crypt\n");
    ast_cli(a->fd, "password = %s\n", crypted);
    return CLI_SUCCESS;
 }
ari_set_debug()
static char* ari_set_debug (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) static
Definition at line 377 of file res/ari/cli.c.
References ao2_ref, app, ast_cli_args::argc, ast_cli_args::argv, ast_cli(), CLI_FAILURE, CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::command, complete_ari_app(), debug, ast_cli_args::fd, NULL, stasis_app_get_by_name(), stasis_app_name(), stasis_app_set_debug(), stasis_app_set_global_debug(), and ast_cli_entry::usage.
 {
    void *app;
    int debug;
    switch (cmd) {
    case CLI_INIT:
       e->command = "ari set debug";
       e->usage =
          "Usage: ari set debug <application|all> <on|off>\n"
          "       Enable or disable debugging on a specific application.\n"
          ;
       return NULL;
    case CLI_GENERATE:
       return complete_ari_app(a, 1);
    default:
       break;
    }
    if (a->argc != 5) {
       return CLI_SHOWUSAGE;
    }
    debug = !strcmp(a->argv[4], "on");
    if (!strcmp(a->argv[3], "all")) {
       stasis_app_set_global_debug(debug);
       ast_cli(a->fd, "Debugging on all applications %s\n",
          debug ? "enabled" : "disabled");
       return CLI_SUCCESS;
    }
    app = stasis_app_get_by_name(a->argv[3]);
    if (!app) {
       return CLI_FAILURE;
    }
    stasis_app_set_debug(app, debug);
    ast_cli(a->fd, "Debugging on '%s' %s\n",
       stasis_app_name(app),
       debug ? "enabled" : "disabled");
    ao2_ref(app, -1);
    return CLI_SUCCESS;
 }
ari_show()
static char* ari_show (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) static
Definition at line 32 of file res/ari/cli.c.
References ao2_cleanup, ao2_container_count(), ast_cli_args::argc, ast_ari_config_get(), ast_cli(), AST_CLI_YESNO, AST_JSON_COMPACT, AST_JSON_PRETTY, CLI_FAILURE, CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::command, ast_cli_args::fd, NULL, RAII_VAR, and ast_cli_entry::usage.
 {
    RAII_VAR(struct ast_ari_conf *, conf, NULL, ao2_cleanup);
    switch (cmd) {
    case CLI_INIT:
       e->command = "ari show status";
       e->usage =
          "Usage: ari show status\n"
          "       Shows all ARI settings\n";
       return NULL;
    case CLI_GENERATE:
       return NULL;
    default:
       break;
    }
    if (a->argc != 3) {
       return CLI_SHOWUSAGE;
    }
    conf = ast_ari_config_get();
    if (!conf) {
       ast_cli(a->fd, "Error getting ARI configuration\n");
       return CLI_FAILURE;
    }
    ast_cli(a->fd, "ARI Status:\n");
    ast_cli(a->fd, "Enabled: %s\n", AST_CLI_YESNO(conf->general->enabled));
    ast_cli(a->fd, "Output format: ");
    switch (conf->general->format) {
    case AST_JSON_COMPACT:
       ast_cli(a->fd, "compact");
       break;
    case AST_JSON_PRETTY:
       ast_cli(a->fd, "pretty");
       break;
    }
    ast_cli(a->fd, "\n");
    ast_cli(a->fd, "Auth realm: %s\n", conf->general->auth_realm);
    ast_cli(a->fd, "Allowed Origins: %s\n", conf->general->allowed_origins);
    ast_cli(a->fd, "User count: %d\n", ao2_container_count(conf->users));
    return CLI_SUCCESS;
 }
ari_show_app()
static char* ari_show_app (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) static
Definition at line 343 of file res/ari/cli.c.
References ao2_ref, app, ast_cli_args::argc, ast_cli_args::argv, CLI_FAILURE, CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::command, complete_ari_app(), NULL, stasis_app_get_by_name(), stasis_app_to_cli(), and ast_cli_entry::usage.
 {
    void *app;
    switch (cmd) {
    case CLI_INIT:
       e->command = "ari show app";
       e->usage =
          "Usage: ari show app <application>\n"
          "       Provide detailed information about a registered application.\n"
          ;
       return NULL;
    case CLI_GENERATE:
       return complete_ari_app(a, 0);
    default:
       break;
    }
    if (a->argc != 4) {
       return CLI_SHOWUSAGE;
    }
    app = stasis_app_get_by_name(a->argv[3]);
    if (!app) {
       return CLI_FAILURE;
    }
    stasis_app_to_cli(app, a);
    ao2_ref(app, -1);
    return CLI_SUCCESS;
 }
ari_show_apps()
static char* ari_show_apps (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) static
Definition at line 253 of file res/ari/cli.c.
References ao2_iterator_destroy(), ao2_iterator_init(), ao2_iterator_next, ao2_ref, app, apps, ast_cli_args::argc, ast_cli(), CLI_FAILURE, CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::command, ast_cli_args::fd, NULL, stasis_app_get_all(), and ast_cli_entry::usage.
 {
    struct ao2_container *apps;
    struct ao2_iterator it_apps;
    char *app;
    switch (cmd) {
    case CLI_INIT:
       e->command = "ari show apps";
       e->usage =
          "Usage: ari show apps\n"
          "       Lists all registered applications.\n"
          ;
       return NULL;
    case CLI_GENERATE:
       return NULL;
    default:
       break;
    }
    if (a->argc != 3) {
       return CLI_SHOWUSAGE;
    }
    apps = stasis_app_get_all();
    if (!apps) {
       ast_cli(a->fd, "Unable to retrieve registered applications!\n");
       return CLI_FAILURE;
    }
    ast_cli(a->fd, "Application Name         \n");
    ast_cli(a->fd, "=========================\n");
    it_apps = ao2_iterator_init(apps, 0);
    while ((app = ao2_iterator_next(&it_apps))) {
       ast_cli(a->fd, "%-25.25s\n", app);
       ao2_ref(app, -1);
    }
    ao2_iterator_destroy(&it_apps);
    ao2_ref(apps, -1);
    return CLI_SUCCESS;
 }
ari_show_user()
static char* ari_show_user (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) static
Definition at line 173 of file res/ari/cli.c.
References ao2_cleanup, ao2_find, ast_cli_args::argc, ast_cli_args::argv, ast_ari_config_get(), ast_cli(), AST_CLI_YESNO, CLI_FAILURE, CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::command, complete_ari_show_user(), ast_cli_args::fd, NULL, OBJ_KEY, RAII_VAR, and ast_cli_entry::usage.
 {
    RAII_VAR(struct ast_ari_conf *, conf, NULL, ao2_cleanup);
    RAII_VAR(struct ast_ari_conf_user *, user, NULL, ao2_cleanup);
    switch (cmd) {
    case CLI_INIT:
       e->command = "ari show user";
       e->usage =
          "Usage: ari show user <username>\n"
          "       Shows a specific ARI user\n";
       return NULL;
    case CLI_GENERATE:
       return complete_ari_show_user(a);
    default:
       break;
    }
    if (a->argc != 4) {
       return CLI_SHOWUSAGE;
    }
    conf = ast_ari_config_get();
    if (!conf) {
       ast_cli(a->fd, "Error getting ARI configuration\n");
       return CLI_FAILURE;
    }
    user = ao2_find(conf->users, a->argv[3], OBJ_KEY);
    if (!user) {
       ast_cli(a->fd, "User '%s' not found\n", a->argv[3]);
       return CLI_SUCCESS;
    }
    ast_cli(a->fd, "Username: %s\n", user->username);
    ast_cli(a->fd, "Read only?: %s\n", AST_CLI_YESNO(user->read_only));
    return CLI_SUCCESS;
 }
ari_show_users()
static char* ari_show_users (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) static
Definition at line 89 of file res/ari/cli.c.
References ao2_callback, ao2_cleanup, ast_cli_args::argc, ast_ari_config_get(), ast_cli(), CLI_FAILURE, CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::command, ast_cli_args::fd, NULL, OBJ_NODATA, RAII_VAR, show_users_cb(), and ast_cli_entry::usage.
 {
    RAII_VAR(struct ast_ari_conf *, conf, NULL, ao2_cleanup);
    switch (cmd) {
    case CLI_INIT:
       e->command = "ari show users";
       e->usage =
          "Usage: ari show users\n"
          "       Shows all ARI users\n";
       return NULL;
    case CLI_GENERATE:
       return NULL;
    default:
       break;
    }
    if (a->argc != 3) {
       return CLI_SHOWUSAGE;
    }
    conf = ast_ari_config_get();
    if (!conf) {
       ast_cli(a->fd, "Error getting ARI configuration\n");
       return CLI_FAILURE;
    }
    ast_cli(a->fd, "r/o?  Username\n");
    ast_cli(a->fd, "----  --------\n");
    ao2_callback(conf->users, OBJ_NODATA, show_users_cb, a);
    return CLI_SUCCESS;
 }
ast_ari_cli_register()
int ast_ari_cli_register (void)
Register CLI commands for ARI.
Returns
0 on success.
Non-zero on error.
Definition at line 434 of file res/ari/cli.c.
References ARRAY_LEN, and ast_cli_register_multiple.
Referenced by load_module().
{
    return ast_cli_register_multiple(cli_ari, ARRAY_LEN(cli_ari));
 }
ast_ari_cli_unregister()
void ast_ari_cli_unregister (void)
Unregister CLI commands for ARI.
Definition at line 438 of file res/ari/cli.c.
References ARRAY_LEN, and ast_cli_unregister_multiple().
Referenced by unload_module().
{
    ast_cli_unregister_multiple(cli_ari, ARRAY_LEN(cli_ari));
 }
complete_ari_app()
static char* complete_ari_app (struct ast_cli_args * a, int include_all) static
Definition at line 314 of file res/ari/cli.c.
References ao2_callback_data, ao2_cleanup, app, ast_cli(), ast_str_container_add(), ast_strdup, ast_strlen_zero, CLI_FAILURE, complete_ari_app_search(), ast_cli_args::fd, ast_cli_args::n, NULL, OBJ_SEARCH_PARTIAL_KEY, ast_cli_args::pos, RAII_VAR, stasis_app_get_all(), app_complete::state, and ast_cli_args::word.
Referenced by ari_set_debug(), and ari_show_app().
 {
    RAII_VAR(struct ao2_container *, apps, stasis_app_get_all(), ao2_cleanup);
    RAII_VAR(char *, app, NULL, ao2_cleanup);
    struct app_complete search = {
       .state = a->n,
    };
    if (a->pos != 3) {
       return NULL;
    }
    if (!apps) {
       ast_cli(a->fd, "Error getting ARI applications\n");
       return CLI_FAILURE;
    }
    if (include_all && ast_strlen_zero(a->word)) {
       ast_str_container_add(apps, " all");
    }
    app = ao2_callback_data(apps,
       ast_strlen_zero(a->word) ? 0 : OBJ_SEARCH_PARTIAL_KEY,
       complete_ari_app_search, (char*)a->word, &search);
    return app ? ast_strdup(app) : NULL;
 }
complete_ari_app_search()
static int complete_ari_app_search (void * obj, void * arg, void * data, int flags) static
Definition at line 304 of file res/ari/cli.c.
References CMP_MATCH, app_complete::state, and app_complete::which.
Referenced by complete_ari_app().
 {
    struct app_complete *search = data;
    if (++search->which > search->state) {
       return CMP_MATCH;
    }
    return 0;
 }
complete_ari_show_user()
static char* complete_ari_show_user (struct ast_cli_args * a) static
Definition at line 164 of file res/ari/cli.c.
References complete_ari_user(), NULL, and ast_cli_args::pos.
Referenced by ari_show_user().
 {
    if (a->pos == 3) {
       return complete_ari_user(a);
    }
    return NULL;
 }
complete_ari_user()
static char* complete_ari_user (struct ast_cli_args * a) static
Definition at line 142 of file res/ari/cli.c.
References ao2_callback_data, ao2_cleanup, ast_ari_config_get(), ast_cli(), ast_strdup, ast_strlen_zero, CLI_FAILURE, complete_ari_user_search(), ast_cli_args::fd, ast_cli_args::n, NULL, OBJ_PARTIAL_KEY, RAII_VAR, user_complete::state, and ast_cli_args::word.
Referenced by complete_ari_show_user().
 {
    RAII_VAR(struct ast_ari_conf *, conf, NULL, ao2_cleanup);
    RAII_VAR(struct ast_ari_conf_user *, user, NULL, ao2_cleanup);
    struct user_complete search = {
       .state = a->n,
    };
    conf = ast_ari_config_get();
    if (!conf) {
       ast_cli(a->fd, "Error getting ARI configuration\n");
       return CLI_FAILURE;
    }
    user = ao2_callback_data(conf->users,
       ast_strlen_zero(a->word) ? 0 : OBJ_PARTIAL_KEY,
       complete_ari_user_search, (char*)a->word, &search);
    return user ? ast_strdup(user->username) : NULL;
 }
complete_ari_user_search()
static int complete_ari_user_search (void * obj, void * arg, void * data, int flags) static
Definition at line 132 of file res/ari/cli.c.
References CMP_MATCH, user_complete::state, and user_complete::which.
Referenced by complete_ari_user().
 {
    struct user_complete *search = data;
    if (++search->which > search->state) {
       return CMP_MATCH;
    }
    return 0;
 }
show_users_cb()
static int show_users_cb (void * obj, void * arg, int flags) static
Definition at line 78 of file res/ari/cli.c.
References a, ast_cli(), AST_CLI_YESNO, ast_cli_args::fd, ast_ari_conf_user::read_only, and ast_ari_conf_user::username.
Referenced by ari_show_users().
 {
    struct ast_ari_conf_user *user = obj;
    struct ast_cli_args *a = arg;
    ast_cli(a->fd, "%-4s  %s\n",
       AST_CLI_YESNO(user->read_only),
       user->username);
    return 0;
 }
Variable Documentation
cli_ari
struct ast_cli_entry cli_ari[] static
Definition at line 424 of file res/ari/cli.c.