Asterisk - The Open Source Telephony Project: res_pjsip_exten_state.c File Reference
res_pjsip_exten_state.c File Reference
#include "asterisk.h"
#include <regex.h>
#include <pjsip.h>
#include <pjsip_simple.h>
#include <pjlib.h>
#include "asterisk/res_pjsip.h"
#include "asterisk/res_pjsip_outbound_publish.h"
#include "asterisk/res_pjsip_pubsub.h"
#include "asterisk/res_pjsip_body_generator_types.h"
#include "asterisk/module.h"
#include "asterisk/logger.h"
#include "asterisk/astobj2.h"
#include "asterisk/sorcery.h"
#include "asterisk/app.h"
#include "asterisk/taskprocessor.h"
Data Structures
struct exten_state_pub_data
struct exten_state_publisher
An extension state publisher.
struct exten_state_subscription
A subscription for extension state.
struct notify_task_data
Macros
#define BODY_SIZE 1024
#define DEFAULT_DIALOG_BODY "application/dialog-info+xml"
#define DEFAULT_PRESENCE_BODY "application/pidf+xml"
#define EVENT_TYPE_SIZE 50
#define INITIAL_LAST_EXTEN_STATE -3
#define PUBLISHER_BUCKETS 31
The number of buckets to use for storing publishers.
Functions
static void __reg_module (void)
static void __unreg_module (void)
static int add_datastore (struct exten_state_subscription *exten_state_sub)
static struct notify_task_data * alloc_notify_task_data (const char *exten, struct exten_state_subscription *exten_state_sub, struct ast_state_cb_info *info)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int build_regex (regex_t *regex, const char *text)
static struct ast_sip_exten_state_data * exten_state_data_alloc (struct ast_sip_subscription *sip_sub, struct exten_state_subscription *exten_state_sub)
static void exten_state_data_destructor (void *obj)
static struct exten_state_pub_data * exten_state_pub_data_alloc (const char *exten, struct ast_state_cb_info *info)
static void exten_state_pub_data_destroy (struct exten_state_pub_data *doomed)
static int exten_state_publisher_cb (void *data)
static int exten_state_publisher_cmp (void *obj, void *arg, int flags)
Comparator function for extension state publisher.
static void exten_state_publisher_destroy (void *obj)
Destructor for extension state publisher.
static int exten_state_publisher_hash (const void *obj, const int flags)
Hashing function for extension state publisher.
static int exten_state_publisher_state_cb (const char *context, const char *exten, struct ast_state_cb_info *info, void *data)
Global extension state callback function.
static struct exten_state_subscription * exten_state_subscription_alloc (struct ast_sip_subscription *sip_sub, struct ast_sip_endpoint *endpoint)
static void exten_state_subscription_destructor (void *obj)
static struct exten_state_subscription * get_exten_state_sub (struct ast_sip_subscription *sub)
static void * get_notify_data (struct ast_sip_subscription *sub)
static char * get_user_agent (const struct ast_sip_subscription *sip_sub)
static int load_module (void)
static int new_subscribe (struct ast_sip_endpoint *endpoint, const char *resource)
static int notify_task (void *obj)
static void notify_task_data_destructor (void *obj)
static int publisher_start (struct ast_sip_outbound_publish *configuration, struct ast_sip_outbound_publish_client *client)
static int publisher_stop (struct ast_sip_outbound_publish_client *client)
static int state_changed (const char *context, const char *exten, struct ast_state_cb_info *info, void *data)
static void state_changed_destroy (int id, void *data)
static int subscription_established (struct ast_sip_subscription *sub)
static void subscription_shutdown (struct ast_sip_subscription *sub)
static void to_ami (struct ast_sip_subscription *sub, struct ast_str **buf)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "PJSIP Extension State Notifications" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_CHANNEL_DEPEND + 5, .requires = "res_pjsip,res_pjsip_pubsub,res_pjsip_outbound_publish", }
static const struct ast_module_info * ast_module_info = &__mod_info
struct ast_sip_subscription_handler dialog_handler
struct ast_sip_notifier dialog_notifier
struct ast_sip_event_publisher_handler dialog_publisher
static struct ast_datastore_info ds_info = { }
static const char ds_name [] = "exten state datastore"
struct ast_sip_subscription_handler presence_handler
struct ast_sip_notifier presence_notifier
struct ast_sip_event_publisher_handler presence_publisher
static struct ast_taskprocessor * publish_exten_state_serializer
static struct ao2_container * publishers
Container of active outbound extension state publishers.
Macro Definition Documentation
BODY_SIZE
#define BODY_SIZE 1024
Definition at line 46 of file res_pjsip_exten_state.c.
DEFAULT_DIALOG_BODY
#define DEFAULT_DIALOG_BODY "application/dialog-info+xml"
Definition at line 114 of file res_pjsip_exten_state.c.
DEFAULT_PRESENCE_BODY
#define DEFAULT_PRESENCE_BODY "application/pidf+xml"
Definition at line 113 of file res_pjsip_exten_state.c.
EVENT_TYPE_SIZE
#define EVENT_TYPE_SIZE 50
Definition at line 47 of file res_pjsip_exten_state.c.
INITIAL_LAST_EXTEN_STATE
#define INITIAL_LAST_EXTEN_STATE -3
Definition at line 201 of file res_pjsip_exten_state.c.
Referenced by exten_state_subscription_alloc().
PUBLISHER_BUCKETS
#define PUBLISHER_BUCKETS 31
The number of buckets to use for storing publishers.
Definition at line 52 of file res_pjsip_exten_state.c.
Referenced by load_module().
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 1012 of file res_pjsip_exten_state.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 1012 of file res_pjsip_exten_state.c.
add_datastore()
static int add_datastore (struct exten_state_subscription * exten_state_sub) static
Definition at line 369 of file res_pjsip_exten_state.c.
References ao2_cleanup, ao2_ref, ast_sip_subscription_add_datastore(), ast_sip_subscription_alloc_datastore(), ds_name, RAII_VAR, and exten_state_subscription::sip_sub.
Referenced by subscription_established().
 {
    RAII_VAR(struct ast_datastore *, datastore,
        ast_sip_subscription_alloc_datastore(&ds_info, ds_name), ao2_cleanup);
    if (!datastore) {
       return -1;
    }
    datastore->data = exten_state_sub;
    ast_sip_subscription_add_datastore(exten_state_sub->sip_sub, datastore);
    ao2_ref(exten_state_sub, +1);
    return 0;
 }
alloc_notify_task_data()
static struct notify_task_data* alloc_notify_task_data (const char * exten, struct exten_state_subscription * exten_state_sub, struct ast_state_cb_info * info) static
Definition at line 251 of file res_pjsip_exten_state.c.
References ao2_alloc, ao2_bump, ao2_ref, AST_EXTENSION_DEACTIVATED, AST_EXTENSION_REMOVED, ast_log, ast_sip_subscription_get_datastores(), ast_strdup, ast_verb, ast_sip_exten_state_data::datastores, ast_sip_exten_state_data::device_state_info, ast_state_cb_info::device_state_info, ast_sip_exten_state_data::exten, exten_state_subscription::exten, ast_sip_exten_state_data::exten_state, ast_state_cb_info::exten_state, notify_task_data::exten_state_data, notify_task_data::exten_state_sub, exten_state_subscription::last_exten_state, exten_state_subscription::last_presence_state, LOG_WARNING, notify_task_data_destructor(), NULL, ast_sip_exten_state_data::presence_message, ast_state_cb_info::presence_message, ast_sip_exten_state_data::presence_state, ast_state_cb_info::presence_state, ast_sip_exten_state_data::presence_subtype, ast_state_cb_info::presence_subtype, exten_state_subscription::sip_sub, ast_sip_exten_state_data::sub, notify_task_data::terminate, ast_sip_exten_state_data::user_agent, and exten_state_subscription::user_agent.
Referenced by state_changed().
 {
    struct notify_task_data *task_data =
       ao2_alloc(sizeof(*task_data), notify_task_data_destructor);
    if (!task_data) {
       ast_log(LOG_WARNING, "Unable to create notify task data\n");
       return NULL;
    }
    task_data->exten_state_sub = exten_state_sub;
    task_data->exten_state_sub->last_exten_state = info->exten_state;
    task_data->exten_state_sub->last_presence_state = info->presence_state;
    ao2_ref(task_data->exten_state_sub, +1);
    task_data->exten_state_data.exten = exten_state_sub->exten;
    task_data->exten_state_data.exten_state = info->exten_state;
    task_data->exten_state_data.presence_state = info->presence_state;
    task_data->exten_state_data.presence_subtype = ast_strdup(info->presence_subtype);
    task_data->exten_state_data.presence_message = ast_strdup(info->presence_message);
    task_data->exten_state_data.user_agent = ast_strdup(exten_state_sub->user_agent);
    task_data->exten_state_data.device_state_info = ao2_bump(info->device_state_info);
    task_data->exten_state_data.sub = exten_state_sub->sip_sub;
    task_data->exten_state_data.datastores = ast_sip_subscription_get_datastores(exten_state_sub->sip_sub);
    if ((info->exten_state == AST_EXTENSION_DEACTIVATED) ||
        (info->exten_state == AST_EXTENSION_REMOVED)) {
       ast_verb(2, "Watcher for hint %s %s\n", exten, info->exten_state
           == AST_EXTENSION_REMOVED ? "removed" : "deactivated");
       task_data->terminate = 1;
    }
    return task_data;
 }
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 1012 of file res_pjsip_exten_state.c.
build_regex()
static int build_regex (regex_t * regex, const char * text) static
Definition at line 822 of file res_pjsip_exten_state.c.
References ast_log, buf, len(), LOG_ERROR, and NULL.
Referenced by publisher_start().
 {
    int res;
    if ((res = regcomp(regex, text, REG_EXTENDED | REG_ICASE | REG_NOSUB))) {
       size_t len = regerror(res, regex, NULL, 0);
       char buf[len];
       regerror(res, regex, buf, len);
       ast_log(LOG_ERROR, "Could not compile regex '%s': %s\n", text, buf);
       return -1;
    }
    return 0;
 }
exten_state_data_alloc()
static struct ast_sip_exten_state_data* exten_state_data_alloc (struct ast_sip_subscription * sip_sub, struct exten_state_subscription * exten_state_sub) static
Definition at line 482 of file res_pjsip_exten_state.c.
References ao2_alloc, ao2_cleanup, ast_extension_state_extended(), ast_hint_presence_state(), AST_PRESENCE_INVALID, ast_sip_get_pjsip_endpoint(), ast_sip_subscription_get_datastores(), ast_sip_subscription_get_local_uri(), ast_sip_subscription_get_remote_uri(), exten_state_subscription::context, ast_sip_exten_state_data::datastores, ast_sip_exten_state_data::device_state_info, ast_sip_exten_state_data::exten, exten_state_subscription::exten, ast_sip_exten_state_data::exten_state, exten_state_data_destructor(), ast_sip_exten_state_data::local, NULL, ast_sip_exten_state_data::pool, ast_sip_exten_state_data::presence_message, ast_sip_exten_state_data::presence_state, ast_sip_exten_state_data::presence_subtype, ast_sip_exten_state_data::remote, exten_state_subscription::sip_sub, ast_sip_exten_state_data::sub, ast_sip_exten_state_data::user_agent, and exten_state_subscription::user_agent.
Referenced by get_notify_data().
 {
    struct ast_sip_exten_state_data *exten_state_data;
    char *subtype = NULL;
    char *message = NULL;
    int presence_state;
    exten_state_data = ao2_alloc(sizeof(*exten_state_data), exten_state_data_destructor);
    if (!exten_state_data) {
       return NULL;
    }
    exten_state_data->exten = exten_state_sub->exten;
    presence_state = ast_hint_presence_state(NULL, exten_state_sub->context, exten_state_sub->exten, &subtype, &message);
    if (presence_state  == -1 || presence_state == AST_PRESENCE_INVALID) {
       ao2_cleanup(exten_state_data);
       return NULL;
    }
    exten_state_data->presence_state = presence_state;
    exten_state_data->presence_subtype = subtype;
    exten_state_data->presence_message = message;
    exten_state_data->user_agent = exten_state_sub->user_agent;
    ast_sip_subscription_get_local_uri(sip_sub, exten_state_data->local,
          sizeof(exten_state_data->local));
    ast_sip_subscription_get_remote_uri(sip_sub, exten_state_data->remote,
          sizeof(exten_state_data->remote));
    exten_state_data->sub = sip_sub;
    exten_state_data->datastores = ast_sip_subscription_get_datastores(sip_sub);
    exten_state_data->exten_state = ast_extension_state_extended(
          NULL, exten_state_sub->context, exten_state_sub->exten,
          &exten_state_data->device_state_info);
    if (exten_state_data->exten_state < 0) {
       ao2_cleanup(exten_state_data);
       return NULL;
    }
    exten_state_data->pool = pjsip_endpt_create_pool(ast_sip_get_pjsip_endpoint(),
          "exten_state", 1024, 1024);
    if (!exten_state_data->pool) {
       ao2_cleanup(exten_state_data);
       return NULL;
    }
    return exten_state_data;
 }
exten_state_data_destructor()
static void exten_state_data_destructor (void * obj) static
Definition at line 470 of file res_pjsip_exten_state.c.
References ao2_cleanup, ast_free, ast_sip_get_pjsip_endpoint(), ast_sip_exten_state_data::device_state_info, ast_sip_exten_state_data::pool, ast_sip_exten_state_data::presence_message, and ast_sip_exten_state_data::presence_subtype.
Referenced by exten_state_data_alloc().
 {
    struct ast_sip_exten_state_data *exten_state_data = obj;
    ao2_cleanup(exten_state_data->device_state_info);
    ast_free(exten_state_data->presence_subtype);
    ast_free(exten_state_data->presence_message);
    if (exten_state_data->pool) {
       pjsip_endpt_release_pool(ast_sip_get_pjsip_endpoint(), exten_state_data->pool);
    }
 }
exten_state_pub_data_alloc()
static struct exten_state_pub_data* exten_state_pub_data_alloc (const char * exten, struct ast_state_cb_info * info) static
Definition at line 582 of file res_pjsip_exten_state.c.
References ao2_bump, ao2_container_count(), ast_calloc, ast_strdup, AST_VECTOR_INIT, ast_state_cb_info::device_state_info, ast_state_cb_info::exten_state, exten_state_pub_data_destroy(), NULL, ast_state_cb_info::presence_message, ast_state_cb_info::presence_state, and ast_state_cb_info::presence_subtype.
Referenced by exten_state_publisher_state_cb().
 {
    struct exten_state_pub_data *pub_data;
    pub_data = ast_calloc(1, sizeof(*pub_data));
    if (!pub_data) {
       return NULL;
    }
    if (AST_VECTOR_INIT(&pub_data->pubs, ao2_container_count(publishers))) {
       exten_state_pub_data_destroy(pub_data);
       return NULL;
    }
    /* Save off currently known information for the body generators. */
    pub_data->exten_state_data.exten = ast_strdup(exten);
    pub_data->exten_state_data.exten_state = info->exten_state;
    pub_data->exten_state_data.presence_state = info->presence_state;
    pub_data->exten_state_data.presence_subtype = ast_strdup(info->presence_subtype);
    pub_data->exten_state_data.presence_message = ast_strdup(info->presence_message);
    pub_data->exten_state_data.device_state_info = ao2_bump(info->device_state_info);
    if (!pub_data->exten_state_data.exten
       || !pub_data->exten_state_data.presence_subtype
       || !pub_data->exten_state_data.presence_message) {
       exten_state_pub_data_destroy(pub_data);
       return NULL;
    }
    return pub_data;
 }
exten_state_pub_data_destroy()
static void exten_state_pub_data_destroy (struct exten_state_pub_data * doomed) static
Definition at line 565 of file res_pjsip_exten_state.c.
References ao2_cleanup, ao2_ref, ast_free, AST_VECTOR_CALLBACK_VOID, and AST_VECTOR_FREE.
Referenced by exten_state_pub_data_alloc(), exten_state_publisher_cb(), and exten_state_publisher_state_cb().
 {
    if (!doomed) {
       return;
    }
    ast_free((void *) doomed->exten_state_data.exten);
    ast_free(doomed->exten_state_data.presence_subtype);
    ast_free(doomed->exten_state_data.presence_message);
    ao2_cleanup(doomed->exten_state_data.device_state_info);
    AST_VECTOR_CALLBACK_VOID(&doomed->pubs, ao2_ref, -1);
    AST_VECTOR_FREE(&doomed->pubs);
    ast_free(doomed);
 }
exten_state_publisher_cb()
static int exten_state_publisher_cb (void * data) static
Definition at line 619 of file res_pjsip_exten_state.c.
References ast_free, ast_log, AST_SIP_EXTEN_STATE_DATA, ast_sip_get_pjsip_endpoint(), ast_sip_publish_client_get_user_from_uri(), ast_sip_publish_client_get_user_to_uri(), ast_sip_publish_client_user_send(), ast_sip_pubsub_generate_body_content(), ast_str_buffer(), ast_str_create, ast_strlen_zero, AST_VECTOR_GET, AST_VECTOR_SIZE, exten_state_publisher::body_subtype, ast_sip_body::body_text, exten_state_publisher::body_type, ast_sip_body_data::body_type, exten_state_publisher::client, exten_state_publisher::datastores, exten_state_pub_data_destroy(), LOG_WARNING, exten_state_publisher::name, pool, ast_sip_body::subtype, and ast_sip_body::type.
Referenced by exten_state_publisher_state_cb().
 {
    struct exten_state_pub_data *pub_data = data;
    struct exten_state_publisher *publisher;
    size_t idx;
    struct ast_str *body_text;
    pj_pool_t *pool;
    struct ast_sip_body_data gen_data = {
       .body_type = AST_SIP_EXTEN_STATE_DATA,
       .body_data = &pub_data->exten_state_data,
    };
    struct ast_sip_body body;
    body_text = ast_str_create(64);
    if (!body_text) {
       exten_state_pub_data_destroy(pub_data);
       return 0;
    }
    /* Need a PJSIP memory pool to generate the bodies. */
    pool = pjsip_endpt_create_pool(ast_sip_get_pjsip_endpoint(), "pub_state_body",
       1024, 1024);
    if (!pool) {
       ast_log(LOG_WARNING, "Exten state publishing unable to create memory pool\n");
       exten_state_pub_data_destroy(pub_data);
       ast_free(body_text);
       return 0;
    }
    pub_data->exten_state_data.pool = pool;
    for (idx = 0; idx < AST_VECTOR_SIZE(&pub_data->pubs); ++idx) {
       const char *uri;
       int res;
       publisher = AST_VECTOR_GET(&pub_data->pubs, idx);
       uri = ast_sip_publish_client_get_user_from_uri(publisher->client, pub_data->exten_state_data.exten,
          pub_data->exten_state_data.local, sizeof(pub_data->exten_state_data.local));
       if (ast_strlen_zero(uri)) {
          ast_log(LOG_WARNING, "PUBLISH client '%s' has no from_uri or server_uri defined.\n",
             publisher->name);
          continue;
       }
       uri = ast_sip_publish_client_get_user_to_uri(publisher->client, pub_data->exten_state_data.exten,
          pub_data->exten_state_data.remote, sizeof(pub_data->exten_state_data.remote));
       if (ast_strlen_zero(uri)) {
          ast_log(LOG_WARNING, "PUBLISH client '%s' has no to_uri or server_uri defined.\n",
             publisher->name);
          continue;
       }
       pub_data->exten_state_data.datastores = publisher->datastores;
       res = ast_sip_pubsub_generate_body_content(publisher->body_type,
          publisher->body_subtype, &gen_data, &body_text);
       pj_pool_reset(pool);
       if (res) {
          ast_log(LOG_WARNING,
             "PUBLISH client '%s' unable to generate %s/%s PUBLISH body.\n",
             publisher->name, publisher->body_type, publisher->body_subtype);
          continue;
       }
       body.type = publisher->body_type;
       body.subtype = publisher->body_subtype;
       body.body_text = ast_str_buffer(body_text);
       ast_sip_publish_client_user_send(publisher->client, pub_data->exten_state_data.exten, &body);
    }
    pjsip_endpt_release_pool(ast_sip_get_pjsip_endpoint(), pool);
    ast_free(body_text);
    exten_state_pub_data_destroy(pub_data);
    return 0;
 }
exten_state_publisher_cmp()
static int exten_state_publisher_cmp (void * obj, void * arg, int flags) static
Comparator function for extension state publisher.
Definition at line 775 of file res_pjsip_exten_state.c.
References ast_assert, CMP_MATCH, exten_state_publisher::name, OBJ_SEARCH_KEY, OBJ_SEARCH_MASK, OBJ_SEARCH_OBJECT, and OBJ_SEARCH_PARTIAL_KEY.
Referenced by load_module().
 {
    const struct exten_state_publisher *object_left = obj;
    const struct exten_state_publisher *object_right = arg;
    const char *right_key = arg;
    int cmp;
    switch (flags & OBJ_SEARCH_MASK) {
    case OBJ_SEARCH_OBJECT:
       right_key = object_right->name;
       /* Fall through */
    case OBJ_SEARCH_KEY:
       cmp = strcmp(object_left->name, right_key);
       break;
    case OBJ_SEARCH_PARTIAL_KEY:
       /* Not supported by container. */
       ast_assert(0);
       return 0;
    default:
       cmp = 0;
       break;
    }
    if (cmp) {
       return 0;
    }
    return CMP_MATCH;
 }
exten_state_publisher_destroy()
static void exten_state_publisher_destroy (void * obj) static
Destructor for extension state publisher.
Definition at line 806 of file res_pjsip_exten_state.c.
References ao2_cleanup, exten_state_publisher::client, exten_state_publisher::context_filter, exten_state_publisher::context_regex, exten_state_publisher::datastores, exten_state_publisher::exten_filter, and exten_state_publisher::exten_regex.
Referenced by publisher_start().
 {
    struct exten_state_publisher *publisher = obj;
    if (publisher->context_filter) {
       regfree(&publisher->context_regex);
    }
    if (publisher->exten_filter) {
       regfree(&publisher->exten_regex);
    }
    ao2_cleanup(publisher->client);
    ao2_cleanup(publisher->datastores);
 }
exten_state_publisher_hash()
static int exten_state_publisher_hash (const void * obj, const int flags) static
Hashing function for extension state publisher.
Definition at line 752 of file res_pjsip_exten_state.c.
References ast_assert, ast_str_hash(), OBJ_SEARCH_KEY, OBJ_SEARCH_MASK, and OBJ_SEARCH_OBJECT.
Referenced by load_module().
 {
    const struct exten_state_publisher *object;
    const char *key;
    switch (flags & OBJ_SEARCH_MASK) {
    case OBJ_SEARCH_KEY:
       key = obj;
       break;
    case OBJ_SEARCH_OBJECT:
       object = obj;
       key = object->name;
       break;
    default:
       ast_assert(0);
       return 0;
    }
    return ast_str_hash(key);
 }
exten_state_publisher_state_cb()
static int exten_state_publisher_state_cb (const char * context, const char * exten, struct ast_state_cb_info * info, void * data) static
Global extension state callback function.
Definition at line 699 of file res_pjsip_exten_state.c.
References ao2_iterator_destroy(), ao2_iterator_init(), ao2_iterator_next, ao2_ref, ast_debug, ast_extension_state2str(), AST_HINT_UPDATE_DEVICE, AST_HINT_UPDATE_PRESENCE, ast_presence_state2str(), ast_sip_push_task(), AST_VECTOR_APPEND, exten_state_publisher::context_filter, exten_state_publisher::context_regex, exten_state_publisher::exten_filter, exten_state_publisher::exten_regex, ast_state_cb_info::exten_state, exten_state_pub_data_alloc(), exten_state_pub_data_destroy(), exten_state_publisher_cb(), exten_state_publisher::name, NULL, ast_state_cb_info::presence_message, ast_state_cb_info::presence_state, ast_state_cb_info::presence_subtype, ast_state_cb_info::reason, and S_OR.
Referenced by publisher_start(), and unload_module().
 {
    struct ao2_iterator publisher_iter;
    struct exten_state_publisher *publisher;
    struct exten_state_pub_data *pub_data = NULL;
    ast_debug(5, "Exten state publisher: %s@%s Reason:%s State:%s Presence:%s Subtype:'%s' Message:'%s'\n",
       exten, context,
       info->reason == AST_HINT_UPDATE_DEVICE
          ? "Device"
          : info->reason == AST_HINT_UPDATE_PRESENCE
             ? "Presence"
             : "Unknown",
       ast_extension_state2str(info->exten_state),
       ast_presence_state2str(info->presence_state),
       S_OR(info->presence_subtype, ""),
       S_OR(info->presence_message, ""));
    publisher_iter = ao2_iterator_init(publishers, 0);
    for (; (publisher = ao2_iterator_next(&publisher_iter)); ao2_ref(publisher, -1)) {
       if ((publisher->context_filter && regexec(&publisher->context_regex, context, 0, NULL, 0)) ||
           (publisher->exten_filter && regexec(&publisher->exten_regex, exten, 0, NULL, 0))) {
          continue;
       }
       if (!pub_data) {
          pub_data = exten_state_pub_data_alloc(exten, info);
          if (!pub_data) {
             ao2_ref(publisher, -1);
             break;
          }
       }
       ao2_ref(publisher, +1);
       if (AST_VECTOR_APPEND(&pub_data->pubs, publisher)) {
          ao2_ref(publisher, -1);
       } else {
          ast_debug(5, "'%s' will publish exten state\n", publisher->name);
       }
    }
    ao2_iterator_destroy(&publisher_iter);
    if (pub_data
       && ast_sip_push_task(publish_exten_state_serializer, exten_state_publisher_cb,
          pub_data)) {
       exten_state_pub_data_destroy(pub_data);
    }
    return 0;
 }
exten_state_subscription_alloc()
static struct exten_state_subscription* exten_state_subscription_alloc (struct ast_sip_subscription * sip_sub, struct ast_sip_endpoint * endpoint) static
Definition at line 210 of file res_pjsip_exten_state.c.
References ao2_alloc, ao2_bump, AST_PRESENCE_NOT_SET, ast_sip_subscription_get_serializer(), exten_state_subscription_destructor(), get_user_agent(), INITIAL_LAST_EXTEN_STATE, exten_state_subscription::last_exten_state, exten_state_subscription::last_presence_state, NULL, exten_state_subscription::serializer, exten_state_subscription::sip_sub, and exten_state_subscription::user_agent.
Referenced by subscription_established().
 {
    struct exten_state_subscription * exten_state_sub;
    exten_state_sub = ao2_alloc(sizeof(*exten_state_sub), exten_state_subscription_destructor);
    if (!exten_state_sub) {
       return NULL;
    }
    exten_state_sub->sip_sub = sip_sub;
    /* We keep our own reference to the serializer as there is no guarantee in state_changed
     * that the subscription tree is still valid when it is called. This can occur when
     * the subscription is terminated at around the same time as the state_changed
     * callback is invoked.
     */
    exten_state_sub->serializer = ao2_bump(ast_sip_subscription_get_serializer(sip_sub));
    exten_state_sub->last_exten_state = INITIAL_LAST_EXTEN_STATE;
    exten_state_sub->last_presence_state = AST_PRESENCE_NOT_SET;
    exten_state_sub->user_agent = get_user_agent(sip_sub);
    return exten_state_sub;
 }
exten_state_subscription_destructor()
static void exten_state_subscription_destructor (void * obj) static
Definition at line 170 of file res_pjsip_exten_state.c.
References ast_free, ast_sip_subscription_destroy(), ast_taskprocessor_unreference(), exten_state_subscription::serializer, exten_state_subscription::sip_sub, sub, and exten_state_subscription::user_agent.
Referenced by exten_state_subscription_alloc().
 {
    struct exten_state_subscription *sub = obj;
    ast_free(sub->user_agent);
    ast_sip_subscription_destroy(sub->sip_sub);
    ast_taskprocessor_unreference(sub->serializer);
 }
get_exten_state_sub()
static struct exten_state_subscription* get_exten_state_sub (struct ast_sip_subscription * sub) static
Definition at line 389 of file res_pjsip_exten_state.c.
References ao2_cleanup, ast_sip_subscription_get_datastore(), ds_name, NULL, and RAII_VAR.
Referenced by get_notify_data(), subscription_shutdown(), and to_ami().
 {
    RAII_VAR(struct ast_datastore *, datastore,
        ast_sip_subscription_get_datastore(sub, ds_name), ao2_cleanup);
    return datastore ? datastore->data : NULL;
 }
get_notify_data()
static void * get_notify_data (struct ast_sip_subscription * sub) static
Definition at line 530 of file res_pjsip_exten_state.c.
References exten_state_data_alloc(), get_exten_state_sub(), and NULL.
 {
    struct exten_state_subscription *exten_state_sub;
    exten_state_sub = get_exten_state_sub(sub);
    if (!exten_state_sub) {
       return NULL;
    }
    return exten_state_data_alloc(sub, exten_state_sub);
 }
get_user_agent()
static char* get_user_agent (const struct ast_sip_subscription * sip_sub) static
Definition at line 179 of file res_pjsip_exten_state.c.
References ast_copy_pj_str(), ast_malloc, ast_sip_subscription_get_header(), ast_str_to_lower(), NULL, and exten_state_subscription::user_agent.
Referenced by exten_state_subscription_alloc().
 {
    size_t size;
    char *user_agent = NULL;
    pjsip_user_agent_hdr *user_agent_hdr = ast_sip_subscription_get_header(
          sip_sub, "User-Agent");
    if (!user_agent_hdr) {
       return NULL;
    }
    size = pj_strlen(&user_agent_hdr->hvalue) + 1;
    user_agent = ast_malloc(size);
    ast_copy_pj_str(user_agent, &user_agent_hdr->hvalue, size);
    return ast_str_to_lower(user_agent);
 }
load_module()
static int load_module (void) static
Definition at line 960 of file res_pjsip_exten_state.c.
References AO2_ALLOC_OPT_LOCK_MUTEX, ao2_container_alloc_hash, ast_log, AST_MODFLAG_LOAD_ORDER, AST_MODPRI_CHANNEL_DEPEND, AST_MODULE_INFO(), AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, AST_MODULE_SUPPORT_CORE, ast_sip_create_serializer(), ast_sip_register_event_publisher_handler(), ast_sip_register_subscription_handler(), ASTERISK_GPL_KEY, ast_sip_event_publisher_handler::event_name, ast_sip_subscription_handler::event_name, exten_state_publisher_cmp(), exten_state_publisher_hash(), LOG_WARNING, NULL, PUBLISHER_BUCKETS, and unload_module().
 {
    publishers = ao2_container_alloc_hash(AO2_ALLOC_OPT_LOCK_MUTEX, 0,
       PUBLISHER_BUCKETS, exten_state_publisher_hash, NULL, exten_state_publisher_cmp);
    if (!publishers) {
       ast_log(LOG_WARNING, "Unable to create container to store extension state publishers\n");
       return AST_MODULE_LOAD_DECLINE;
    }
    publish_exten_state_serializer = ast_sip_create_serializer("pjsip/exten_state");
    if (!publish_exten_state_serializer) {
       unload_module();
       return AST_MODULE_LOAD_DECLINE;
    }
    if (ast_sip_register_subscription_handler(&presence_handler)) {
       ast_log(LOG_WARNING, "Unable to register subscription handler %s\n",
          presence_handler.event_name);
       unload_module();
       return AST_MODULE_LOAD_DECLINE;
    }
    if (ast_sip_register_event_publisher_handler(&presence_publisher)) {
       ast_log(LOG_WARNING, "Unable to register presence publisher %s\n",
          presence_publisher.event_name);
       unload_module();
       return AST_MODULE_LOAD_DECLINE;
    }
    if (ast_sip_register_subscription_handler(&dialog_handler)) {
       ast_log(LOG_WARNING, "Unable to register subscription handler %s\n",
          dialog_handler.event_name);
       unload_module();
       return AST_MODULE_LOAD_DECLINE;
    }
    if (ast_sip_register_event_publisher_handler(&dialog_publisher)) {
       ast_log(LOG_WARNING, "Unable to register presence publisher %s\n",
          dialog_publisher.event_name);
       unload_module();
       return AST_MODULE_LOAD_DECLINE;
    }
    return AST_MODULE_LOAD_SUCCESS;
 }
new_subscribe()
static int new_subscribe (struct ast_sip_endpoint * endpoint, const char * resource) static
Definition at line 412 of file res_pjsip_exten_state.c.
References ast_exists_extension(), ast_log, ast_sorcery_object_get_id(), exten_state_subscription::context, ast_sip_endpoint_subscription_configuration::context, ast_sip_endpoint::context, LOG_NOTICE, NULL, PRIORITY_HINT, S_OR, and ast_sip_endpoint::subscription.
 {
    const char *context = S_OR(endpoint->subscription.context, endpoint->context);
    if (!ast_exists_extension(NULL, context, resource, PRIORITY_HINT, NULL)) {
       ast_log(LOG_NOTICE, "Endpoint '%s' state subscription failed: "
          "Extension '%s' does not exist in context '%s' or has no associated hint\n",
          ast_sorcery_object_get_id(endpoint), resource, context);
       return 404;
    }
    return 200;
 }
notify_task()
static int notify_task (void * obj) static
Definition at line 288 of file res_pjsip_exten_state.c.
References ao2_cleanup, AST_SIP_EXTEN_STATE_DATA, ast_sip_get_pjsip_endpoint(), ast_sip_subscription_get_datastores(), ast_sip_subscription_get_local_uri(), ast_sip_subscription_get_remote_uri(), ast_sip_subscription_is_terminated(), ast_sip_subscription_notify(), ast_sip_body_data::body_type, and RAII_VAR.
Referenced by state_changed().
 {
    RAII_VAR(struct notify_task_data *, task_data, obj, ao2_cleanup);
    struct ast_sip_body_data data = {
       .body_type = AST_SIP_EXTEN_STATE_DATA,
       .body_data = &task_data->exten_state_data,
    };
    /* Terminated subscriptions are no longer associated with a valid tree, and sending
     * NOTIFY messages on a subscription which has already been terminated won't work.
     */
    if (ast_sip_subscription_is_terminated(task_data->exten_state_sub->sip_sub)) {
       return 0;
    }
    /* All access to the subscription must occur within a task executed within its serializer */
    ast_sip_subscription_get_local_uri(task_data->exten_state_sub->sip_sub,
          task_data->exten_state_data.local, sizeof(task_data->exten_state_data.local));
    ast_sip_subscription_get_remote_uri(task_data->exten_state_sub->sip_sub,
          task_data->exten_state_data.remote, sizeof(task_data->exten_state_data.remote));
    /* Pool allocation has to happen here so that we allocate within a PJLIB thread */
    task_data->exten_state_data.pool = pjsip_endpt_create_pool(ast_sip_get_pjsip_endpoint(),
          "exten_state", 1024, 1024);
    if (!task_data->exten_state_data.pool) {
       return -1;
    }
    task_data->exten_state_data.sub = task_data->exten_state_sub->sip_sub;
    task_data->exten_state_data.datastores = ast_sip_subscription_get_datastores(task_data->exten_state_sub->sip_sub);
    ast_sip_subscription_notify(task_data->exten_state_sub->sip_sub, &data,
          task_data->terminate);
    pjsip_endpt_release_pool(ast_sip_get_pjsip_endpoint(),
          task_data->exten_state_data.pool);
    return 0;
 }
notify_task_data_destructor()
static void notify_task_data_destructor (void * obj) static
Definition at line 240 of file res_pjsip_exten_state.c.
References ao2_cleanup, ao2_ref, ast_free, ast_sip_exten_state_data::device_state_info, notify_task_data::exten_state_data, notify_task_data::exten_state_sub, ast_sip_exten_state_data::presence_message, ast_sip_exten_state_data::presence_subtype, and ast_sip_exten_state_data::user_agent.
Referenced by alloc_notify_task_data().
 {
    struct notify_task_data *task_data = obj;
    ao2_ref(task_data->exten_state_sub, -1);
    ao2_cleanup(task_data->exten_state_data.device_state_info);
    ast_free(task_data->exten_state_data.presence_subtype);
    ast_free(task_data->exten_state_data.presence_message);
    ast_free(task_data->exten_state_data.user_agent);
 }
publisher_start()
static int publisher_start (struct ast_sip_outbound_publish * configuration, struct ast_sip_outbound_publish_client * client) static
Definition at line 837 of file res_pjsip_exten_state.c.
References AO2_ALLOC_OPT_LOCK_NOLOCK, ao2_alloc_options, ao2_bump, ao2_container_count(), ao2_link_flags, ao2_lock, ao2_ref, ao2_unlock, ast_copy_string(), ast_datastores_alloc(), ast_extension_state_add(), ast_log, ast_sip_pubsub_is_body_generator_registered(), ast_sorcery_object_get_extended(), ast_sorcery_object_get_id(), ast_strdupa, ast_strlen_zero, exten_state_publisher::body_subtype, exten_state_publisher::body_type, build_regex(), exten_state_publisher::client, exten_state_subscription::context, exten_state_publisher::context_filter, exten_state_publisher::context_regex, exten_state_publisher::datastores, exten_state_subscription::exten, exten_state_publisher::exten_filter, exten_state_publisher::exten_regex, exten_state_publisher_destroy(), exten_state_publisher_state_cb(), LOG_ERROR, name, exten_state_publisher::name, NULL, OBJ_NOLOCK, and strsep().
 {
    struct exten_state_publisher *publisher;
    size_t name_size;
    size_t body_type_size;
    size_t body_subtype_size;
    char *body_subtype;
    const char *body_full;
    const char *body_type;
    const char *name;
    const char *context;
    const char *exten;
    name = ast_sorcery_object_get_id(configuration);
    body_full = ast_sorcery_object_get_extended(configuration, "body");
    if (ast_strlen_zero(body_full)) {
       ast_log(LOG_ERROR, "Outbound extension state publisher '%s': Body not set\n",
          name);
       return -1;
    }
    body_subtype = ast_strdupa(body_full);
    body_type = strsep(&body_subtype, "/");
    if (ast_strlen_zero(body_type) || ast_strlen_zero(body_subtype)) {
       ast_log(LOG_ERROR, "Outbound extension state publisher '%s': Body '%s' missing type or subtype\n",
          name, body_full);
       return -1;
    }
    if (!ast_sip_pubsub_is_body_generator_registered(body_type, body_subtype)) {
       ast_log(LOG_ERROR, "Outbound extension state publisher '%s': '%s' body generator not registered\n",
          name, body_full);
       return -1;
    }
    name_size = strlen(name) + 1;
    body_type_size = strlen(body_type) + 1;
    body_subtype_size = strlen(body_subtype) + 1;
    publisher = ao2_alloc_options(
       sizeof(*publisher) + name_size + body_type_size + body_subtype_size,
       exten_state_publisher_destroy, AO2_ALLOC_OPT_LOCK_NOLOCK);
    if (!publisher) {
       return -1;
    }
    ast_copy_string(publisher->name, name, name_size);
    publisher->body_type = publisher->name + name_size;
    ast_copy_string(publisher->body_type, body_type, body_type_size);
    publisher->body_subtype = publisher->body_type + body_type_size;
    ast_copy_string(publisher->body_subtype, body_subtype, body_subtype_size);
    context = ast_sorcery_object_get_extended(configuration, "context");
    if (!ast_strlen_zero(context)) {
       if (build_regex(&publisher->context_regex, context)) {
          ast_log(LOG_ERROR, "Outbound extension state publisher '%s': Could not build context filter '%s'\n",
             name, context);
          ao2_ref(publisher, -1);
          return -1;
       }
       publisher->context_filter = 1;
    }
    exten = ast_sorcery_object_get_extended(configuration, "exten");
    if (!ast_strlen_zero(exten)) {
       if (build_regex(&publisher->exten_regex, exten)) {
          ast_log(LOG_ERROR, "Outbound extension state publisher '%s': Could not build exten filter '%s'\n",
             name, exten);
          ao2_ref(publisher, -1);
          return -1;
       }
       publisher->exten_filter = 1;
    }
    publisher->datastores = ast_datastores_alloc();
    if (!publisher->datastores) {
       ast_log(LOG_ERROR, "Outbound extension state publisher '%s': Could not create datastores container\n",
          name);
       ao2_ref(publisher, -1);
       return -1;
    }
    publisher->client = ao2_bump(client);
    ao2_lock(publishers);
    if (!ao2_container_count(publishers)) {
       ast_extension_state_add(NULL, NULL, exten_state_publisher_state_cb, NULL);
    }
    ao2_link_flags(publishers, publisher, OBJ_NOLOCK);
    ao2_unlock(publishers);
    ao2_ref(publisher, -1);
    return 0;
 }
publisher_stop()
static int publisher_stop (struct ast_sip_outbound_publish_client * client) static
Definition at line 936 of file res_pjsip_exten_state.c.
References ao2_find, ast_sorcery_object_get_id(), OBJ_NODATA, OBJ_SEARCH_KEY, and OBJ_UNLINK.
 {
    ao2_find(publishers, ast_sorcery_object_get_id(client), OBJ_SEARCH_KEY | OBJ_UNLINK | OBJ_NODATA);
    return 0;
 }
state_changed()
static int state_changed (const char * context, const char * exten, struct ast_state_cb_info * info, void * data) static
Definition at line 333 of file res_pjsip_exten_state.c.
References alloc_notify_task_data(), ao2_cleanup, ast_sip_push_task(), notify_task_data::exten_state_sub, notify_task(), and exten_state_subscription::serializer.
Referenced by subscription_established(), and subscription_shutdown().
 {
    struct notify_task_data *task_data;
    struct exten_state_subscription *exten_state_sub = data;
    if (!(task_data = alloc_notify_task_data(exten, exten_state_sub, info))) {
       return -1;
    }
    /* safe to push this async since we copy the data from info and
       add a ref for the device state info */
    if (ast_sip_push_task(task_data->exten_state_sub->serializer, notify_task,
       task_data)) {
       ao2_cleanup(task_data);
       return -1;
    }
    return 0;
 }
state_changed_destroy()
static void state_changed_destroy (int id, void * data) static
Definition at line 353 of file res_pjsip_exten_state.c.
References ao2_cleanup.
Referenced by subscription_established().
 {
    struct exten_state_subscription *exten_state_sub = data;
    ao2_cleanup(exten_state_sub);
 }
subscription_established()
static int subscription_established (struct ast_sip_subscription * sub) static
Definition at line 427 of file res_pjsip_exten_state.c.
References add_datastore(), ao2_cleanup, ao2_ref, ast_copy_string(), ast_extension_state_add_destroy_extended(), ast_log, ast_sip_subscription_get_endpoint(), ast_sip_subscription_get_resource_name(), ast_sorcery_object_get_id(), exten_state_subscription::context, ast_sip_endpoint_subscription_configuration::context, ast_sip_endpoint::context, exten_state_subscription::exten, exten_state_subscription_alloc(), exten_state_subscription::id, LOG_WARNING, S_OR, state_changed(), state_changed_destroy(), and ast_sip_endpoint::subscription.
 {
    struct ast_sip_endpoint *endpoint = ast_sip_subscription_get_endpoint(sip_sub);
    const char *resource = ast_sip_subscription_get_resource_name(sip_sub);
    struct exten_state_subscription *exten_state_sub;
    if (!(exten_state_sub = exten_state_subscription_alloc(sip_sub, endpoint))) {
       ao2_cleanup(endpoint);
       return -1;
    }
    ast_copy_string(exten_state_sub->context,
       S_OR(endpoint->subscription.context, endpoint->context),
       sizeof(exten_state_sub->context));
    ast_copy_string(exten_state_sub->exten, resource, sizeof(exten_state_sub->exten));
    if ((exten_state_sub->id = ast_extension_state_add_destroy_extended(
            exten_state_sub->context, exten_state_sub->exten,
            state_changed, state_changed_destroy, exten_state_sub)) < 0) {
       ast_log(LOG_WARNING, "Unable to subscribe endpoint '%s' to extension '%s@%s'\n",
          ast_sorcery_object_get_id(endpoint), exten_state_sub->exten,
          exten_state_sub->context);
       ao2_cleanup(endpoint);
       ao2_cleanup(exten_state_sub);
       return -1;
    }
    /* Go ahead and cleanup the endpoint since we don't need it anymore */
    ao2_cleanup(endpoint);
    /* bump the ref since ast_extension_state_add holds a reference */
    ao2_ref(exten_state_sub, +1);
    if (add_datastore(exten_state_sub)) {
       ast_log(LOG_WARNING, "Unable to add to subscription datastore.\n");
       ao2_cleanup(exten_state_sub);
       return -1;
    }
    ao2_cleanup(exten_state_sub);
    return 0;
 }
subscription_shutdown()
static void subscription_shutdown (struct ast_sip_subscription * sub) static
Definition at line 398 of file res_pjsip_exten_state.c.
References ao2_cleanup, ast_extension_state_del(), ast_sip_subscription_remove_datastore(), ds_name, get_exten_state_sub(), exten_state_subscription::id, exten_state_subscription::sip_sub, and state_changed().
 {
    struct exten_state_subscription *exten_state_sub = get_exten_state_sub(sub);
    if (!exten_state_sub) {
       return;
    }
    ast_extension_state_del(exten_state_sub->id, state_changed);
    ast_sip_subscription_remove_datastore(exten_state_sub->sip_sub, ds_name);
    /* remove data store reference */
    ao2_cleanup(exten_state_sub);
 }
to_ami()
static void to_ami (struct ast_sip_subscription * sub, struct ast_str ** buf) static
Definition at line 542 of file res_pjsip_exten_state.c.
References ast_extension_state2str(), ast_str_append(), exten_state_subscription::exten, get_exten_state_sub(), and exten_state_subscription::last_exten_state.
Referenced by agi_async_end_to_ami(), aoc_e_to_ami(), ast_rtp_publish_rtcp_message(), contactstatus_to_json(), dahdichannel_to_ami(), declined_handler(), load_module(), peerstatus_to_json(), queue_agent_ringnoanswer_to_ami(), queue_caller_abandon_to_ami(), queue_member_ringinuse_to_ami(), security_event_to_ami(), stasis_message_can_be_ami(), stasis_message_to_ami(), test_suite_event_to_ami(), unhold_to_json(), and unload_module().
 {
    struct exten_state_subscription *exten_state_sub =
       get_exten_state_sub(sub);
    if (!exten_state_sub) {
       return;
    }
    ast_str_append(buf, 0, "SubscriptionType: extension_state\r\n"
              "Extension: %s\r\nExtensionStates: %s\r\n",
              exten_state_sub->exten, ast_extension_state2str(
                 exten_state_sub->last_exten_state));
 }
unload_module()
static int unload_module (void) static
Definition at line 942 of file res_pjsip_exten_state.c.
References ao2_cleanup, ast_extension_state_del(), ast_sip_unregister_event_publisher_handler(), ast_sip_unregister_subscription_handler(), ast_taskprocessor_unreference(), exten_state_publisher_state_cb(), and NULL.
Referenced by load_module().
 {
    ast_sip_unregister_event_publisher_handler(&dialog_publisher);
    ast_sip_unregister_subscription_handler(&dialog_handler);
    ast_sip_unregister_event_publisher_handler(&presence_publisher);
    ast_sip_unregister_subscription_handler(&presence_handler);
    ast_extension_state_del(0, exten_state_publisher_state_cb);
    ast_taskprocessor_unreference(publish_exten_state_serializer);
    publish_exten_state_serializer = NULL;
    ao2_cleanup(publishers);
    publishers = NULL;
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "PJSIP Extension State Notifications" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_CHANNEL_DEPEND + 5, .requires = "res_pjsip,res_pjsip_pubsub,res_pjsip_outbound_publish", } static
Definition at line 1012 of file res_pjsip_exten_state.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 1012 of file res_pjsip_exten_state.c.
dialog_handler
struct ast_sip_subscription_handler dialog_handler
Definition at line 155 of file res_pjsip_exten_state.c.
dialog_notifier
struct ast_sip_notifier dialog_notifier
Definition at line 133 of file res_pjsip_exten_state.c.
dialog_publisher
struct ast_sip_event_publisher_handler dialog_publisher
Initial value:
= {
   .event_name = "dialog",
   .start_publishing = publisher_start,
   .stop_publishing = publisher_stop,
}
Definition at line 164 of file res_pjsip_exten_state.c.
ds_info
struct ast_datastore_info ds_info = { } static
Definition at line 359 of file res_pjsip_exten_state.c.
ds_name
const char ds_name[] = "exten state datastore" static
Definition at line 360 of file res_pjsip_exten_state.c.
Referenced by add_datastore(), get_exten_state_sub(), and subscription_shutdown().
presence_handler
struct ast_sip_subscription_handler presence_handler
Definition at line 140 of file res_pjsip_exten_state.c.
presence_notifier
struct ast_sip_notifier presence_notifier
Definition at line 126 of file res_pjsip_exten_state.c.
presence_publisher
struct ast_sip_event_publisher_handler presence_publisher
Initial value:
= {
   .event_name = "presence",
   .start_publishing = publisher_start,
   .stop_publishing = publisher_stop,
}
Definition at line 149 of file res_pjsip_exten_state.c.
publish_exten_state_serializer
struct ast_taskprocessor* publish_exten_state_serializer static
Serializer for outbound extension state publishing.
Definition at line 60 of file res_pjsip_exten_state.c.
publishers
struct ao2_container* publishers static
Container of active outbound extension state publishers.
Definition at line 57 of file res_pjsip_exten_state.c.
Referenced by AST_TEST_DEFINE(), and explicit_publish_cb().