Asterisk - The Open Source Telephony Project: _private.h File Reference
_private.h File Reference
Prototypes for public functions only of internal interest,.
Functions
int aco_init (void)
void ast_autoservice_init (void)
int ast_bridging_init (void)
Initialize the bridging system.
void ast_builtins_init (void)
initialize the _full_cmd string in * each of the builtins.
int ast_channels_init (void)
int ast_cli_perms_init (int reload)
int ast_device_state_engine_init (void)
Initialize the device state engine in separate thread.
int ast_dns_system_resolver_init (void)
Initializes the resolver.
int ast_endpoint_init (void)
Endpoint support initialization.
int ast_file_init (void)
int ast_local_init (void)
Initialize the local proxy channel.
int ast_msg_init (void)
void ast_msg_shutdown (void)
int ast_named_locks_init (void)
int ast_parking_stasis_init (void)
initializes the rtp engine arrays
int ast_pj_init (void)
void ast_process_pending_reloads (void)
Process reload requests received during startup.
int ast_rtp_engine_init (void)
initializes the rtp engine arrays
int ast_ssl_init (void)
void ast_stun_init (void)
Initialize the STUN system in Asterisk.
int ast_term_init (void)
int ast_test_init (void)
int ast_timing_init (void)
int ast_tps_init (void)
int ast_xmldoc_load_documentation (void)
Load XML documentation. Provided by xmldoc.c.
int astdb_init (void)
int astobj2_init (void)
void clean_time_zones (void)
void close_logger (void)
int dns_core_init (void)
void dnsmgr_start_refresh (void)
int init_logger (void)
void load_asterisk_conf (void)
void load_astmm_phase_1 (void)
Initialize malloc debug phase 1.
void load_astmm_phase_2 (void)
Initialize malloc debug phase 2.
int load_modules (void)
int load_pbx (void)
int load_pbx_app (void)
int load_pbx_builtins (void)
int load_pbx_functions_cli (void)
int load_pbx_hangup_handler (void)
int load_pbx_switch (void)
int load_pbx_variables (void)
void logger_queue_start (void)
Start the ast_queue_log() logger.
int modules_shutdown (void)
void set_asterisk_conf_path (const char *path)
void set_socket_path (const char *path)
void threadstorage_init (void)
Detailed Description
Prototypes for public functions only of internal interest,.
Definition in file _private.h.
Function Documentation
aco_init()
int aco_init (void)
Provided by config_options.c
Definition at line 1380 of file config_options.c.
References aco_deinit(), ARRAY_LEN, ast_cli_register_multiple, ast_log, ast_register_cleanup(), ast_xmldoc_build_documentation(), and LOG_ERROR.
Referenced by asterisk_daemon().
 {
 #ifdef AST_XML_DOCS
    ast_register_cleanup(aco_deinit);
    if (!(xmldocs = ast_xmldoc_build_documentation("configInfo"))) {
       ast_log(LOG_ERROR, "Couldn't build config documentation\n");
       return -1;
    }
    ast_cli_register_multiple(cli_aco, ARRAY_LEN(cli_aco));
 #endif /* AST_XML_DOCS */
    return 0;
 }
ast_autoservice_init()
void ast_autoservice_init (void)
Provided by autoservice.c
Definition at line 380 of file autoservice.c.
References as_cond, ast_cond_init, ast_register_cleanup(), autoservice_shutdown(), and NULL.
Referenced by asterisk_daemon().
 {
    ast_register_cleanup(autoservice_shutdown);
    ast_cond_init(&as_cond, NULL);
 }
ast_bridging_init()
int ast_bridging_init (void)
Initialize the bridging system.
Since
12.0.0
Return values
0 on success.
-1 on error.
Definition at line 5605 of file bridge.c.
References AO2_ALLOC_OPT_LOCK_MUTEX, AO2_CONTAINER_ALLOC_OPT_DUPS_REPLACE, ao2_container_alloc_rbtree, ao2_container_register(), ARRAY_LEN, ast_bridging_init_basic(), ast_cli_register_multiple, ast_manager_register_xml_core, ast_register_cleanup(), ast_stasis_bridging_init(), bridge_cleanup(), bridge_manager_create(), bridge_prnt_obj(), bridge_sort_cmp(), manager_bridge_tech_list(), manager_bridge_tech_suspend(), manager_bridge_tech_unsuspend(), and NULL.
Referenced by asterisk_daemon().
 {
    ast_register_cleanup(bridge_cleanup);
    if (ast_stasis_bridging_init()) {
       return -1;
    }
    bridge_manager = bridge_manager_create();
    if (!bridge_manager) {
       return -1;
    }
    bridges = ao2_container_alloc_rbtree(AO2_ALLOC_OPT_LOCK_MUTEX,
       AO2_CONTAINER_ALLOC_OPT_DUPS_REPLACE, bridge_sort_cmp, NULL);
    if (!bridges) {
       return -1;
    }
    ao2_container_register("bridges", bridges, bridge_prnt_obj);
    ast_bridging_init_basic();
    ast_cli_register_multiple(bridge_cli, ARRAY_LEN(bridge_cli));
    ast_manager_register_xml_core("BridgeTechnologyList", 0, manager_bridge_tech_list);
    ast_manager_register_xml_core("BridgeTechnologySuspend", 0, manager_bridge_tech_suspend);
    ast_manager_register_xml_core("BridgeTechnologyUnsuspend", 0, manager_bridge_tech_unsuspend);
    return 0;
 }
ast_builtins_init()
void ast_builtins_init (void)
initialize the _full_cmd string in * each of the builtins.
Provided by cli.c
Definition at line 2209 of file main/cli.c.
References ARRAY_LEN, ast_cli_register_multiple, ast_register_cleanup(), AST_VECTOR_INIT, and cli_shutdown().
Referenced by asterisk_daemon().
 {
    AST_VECTOR_INIT(&shutdown_commands, 0);
    ast_cli_register_multiple(cli_cli, ARRAY_LEN(cli_cli));
    ast_register_cleanup(cli_shutdown);
 }
ast_channels_init()
int ast_channels_init (void)
Provided by channel.c
Definition at line 8109 of file channel.c.
References ami_vars, AO2_ALLOC_OPT_LOCK_MUTEX, ao2_container_alloc_hash, ao2_container_register(), ari_vars, ARRAY_LEN, ast_channel_cmp_cb(), ast_channel_hash_cb(), ast_channel_register(), ast_cli_register_multiple, AST_NUM_CHANNEL_BUCKETS, ast_register_cleanup(), AST_RWLIST_HEAD_INIT, ast_stasis_channels_init(), channels_shutdown(), NULL, and prnt_channel_key().
Referenced by asterisk_daemon().
 {
    channels = ao2_container_alloc_hash(AO2_ALLOC_OPT_LOCK_MUTEX, 0, AST_NUM_CHANNEL_BUCKETS,
       ast_channel_hash_cb, NULL, ast_channel_cmp_cb);
    if (!channels) {
       return -1;
    }
    ao2_container_register("channels", channels, prnt_channel_key);
    ast_channel_register(&surrogate_tech);
    ast_stasis_channels_init();
    ast_cli_register_multiple(cli_channel, ARRAY_LEN(cli_channel));
    ast_register_cleanup(channels_shutdown);
    AST_RWLIST_HEAD_INIT(&ami_vars);
    AST_RWLIST_HEAD_INIT(&ari_vars);
    return 0;
 }
ast_cli_perms_init()
int ast_cli_perms_init (int reload)
Provided by cli.c
Definition at line 2081 of file main/cli.c.
References ast_calloc, ast_category_browse(), ast_config_destroy(), ast_config_load2(), ast_free, AST_LIST_INSERT_TAIL, AST_LIST_TRAVERSE, ast_log, ast_mutex_trylock, ast_mutex_unlock, AST_RWLIST_INSERT_TAIL, AST_RWLIST_UNLOCK, AST_RWLIST_WRLOCK, ast_strdup, ast_strlen_zero, ast_variable_browse(), cli_default_perm, cli_perm::command, CONFIG_FLAG_FILEUNCHANGED, CONFIG_STATUS_FILEUNCHANGED, destroy_user_perms(), usergroup_cli_perm::gid, cli_perm::list, LOG_NOTICE, LOG_WARNING, ast_variable::name, ast_variable::next, NULL, cli_perm::permit, usergroup_cli_perm::perms, perms_config, permsconfiglock, usergroup_cli_perm::uid, and ast_variable::value.
Referenced by asterisk_daemon(), and handle_cli_reload_permissions().
 {
    struct ast_flags config_flags = { reload ? CONFIG_FLAG_FILEUNCHANGED : 0 };
    struct ast_config *cfg;
    char *cat = NULL;
    struct ast_variable *v;
    struct usergroup_cli_perm *user_group, *cp_entry;
    struct cli_perm *perm = NULL;
    struct passwd *pw;
    struct group *gr;
    if (ast_mutex_trylock(&permsconfiglock)) {
       ast_log(LOG_NOTICE, "You must wait until last 'cli reload permissions' command finish\n");
       return 1;
    }
    cfg = ast_config_load2(perms_config, "" /* core, can't reload */, config_flags);
    if (!cfg) {
       ast_mutex_unlock(&permsconfiglock);
       return 1;
    } else if (cfg == CONFIG_STATUS_FILEUNCHANGED) {
       ast_mutex_unlock(&permsconfiglock);
       return 0;
    }
    /* free current structures. */
    destroy_user_perms();
    while ((cat = ast_category_browse(cfg, cat))) {
       if (!strcasecmp(cat, "general")) {
          /* General options */
          for (v = ast_variable_browse(cfg, cat); v; v = v->next) {
             if (!strcasecmp(v->name, "default_perm")) {
                cli_default_perm = (!strcasecmp(v->value, "permit")) ? 1: 0;
             }
          }
          continue;
       }
       /* users or groups */
       gr = NULL, pw = NULL;
       if (cat[0] == '@') {
          /* This is a group */
          gr = getgrnam(&cat[1]);
          if (!gr) {
             ast_log (LOG_WARNING, "Unknown group '%s'\n", &cat[1]);
             continue;
          }
       } else {
          /* This is a user */
          pw = getpwnam(cat);
          if (!pw) {
             ast_log (LOG_WARNING, "Unknown user '%s'\n", cat);
             continue;
          }
       }
       user_group = NULL;
       /* Check for duplicates */
       AST_RWLIST_WRLOCK(&cli_perms);
       AST_LIST_TRAVERSE(&cli_perms, cp_entry, list) {
          if ((pw && cp_entry->uid == pw->pw_uid) || (gr && cp_entry->gid == gr->gr_gid)) {
             /* if it is duplicated, just added this new settings, to
             the current list. */
             user_group = cp_entry;
             break;
          }
       }
       AST_RWLIST_UNLOCK(&cli_perms);
       if (!user_group) {
          /* alloc space for the new user config. */
          user_group = ast_calloc(1, sizeof(*user_group));
          if (!user_group) {
             continue;
          }
          user_group->uid = (pw ? pw->pw_uid : -1);
          user_group->gid = (gr ? gr->gr_gid : -1);
          user_group->perms = ast_calloc(1, sizeof(*user_group->perms));
          if (!user_group->perms) {
             ast_free(user_group);
             continue;
          }
       }
       for (v = ast_variable_browse(cfg, cat); v; v = v->next) {
          if (ast_strlen_zero(v->value)) {
             /* we need to check this condition cause it could break security. */
             ast_log(LOG_WARNING, "Empty permit/deny option in user '%s'\n", cat);
             continue;
          }
          if (!strcasecmp(v->name, "permit")) {
             perm = ast_calloc(1, sizeof(*perm));
             if (perm) {
                perm->permit = 1;
                perm->command = ast_strdup(v->value);
             }
          } else if (!strcasecmp(v->name, "deny")) {
             perm = ast_calloc(1, sizeof(*perm));
             if (perm) {
                perm->permit = 0;
                perm->command = ast_strdup(v->value);
             }
          } else {
             /* up to now, only 'permit' and 'deny' are possible values. */
             ast_log(LOG_WARNING, "Unknown '%s' option\n", v->name);
             continue;
          }
          if (perm) {
             /* Added the permission to the user's list. */
             AST_LIST_INSERT_TAIL(user_group->perms, perm, list);
             perm = NULL;
          }
       }
       AST_RWLIST_WRLOCK(&cli_perms);
       AST_RWLIST_INSERT_TAIL(&cli_perms, user_group, list);
       AST_RWLIST_UNLOCK(&cli_perms);
    }
    ast_config_destroy(cfg);
    ast_mutex_unlock(&permsconfiglock);
    return 0;
 }
ast_device_state_engine_init()
int ast_device_state_engine_init (void)
Initialize the device state engine in separate thread.
Provided by devicestate.c
Definition at line 618 of file devicestate.c.
References ast_cond_init, ast_log, ast_pthread_create_background, ast_register_cleanup(), change_pending, change_thread, device_state_engine_cleanup(), do_devstate_changes(), LOG_ERROR, and NULL.
Referenced by asterisk_daemon().
 {
    ast_cond_init(&change_pending, NULL);
    if (ast_pthread_create_background(&change_thread, NULL, do_devstate_changes, NULL) < 0) {
       ast_log(LOG_ERROR, "Unable to start device state change thread.\n");
       return -1;
    }
    ast_register_cleanup(device_state_engine_cleanup);
    return 0;
 }
ast_dns_system_resolver_init()
int ast_dns_system_resolver_init (void)
Initializes the resolver.
Provided by dns_system_resolver.c
Return values
0 on success
-1 on failure
Definition at line 243 of file dns_system_resolver.c.
References ast_dns_resolver_register(), ast_register_cleanup(), ast_taskprocessor_get(), dns_system_resolver_destroy(), DNS_SYSTEM_RESOLVER_FAILURE, DNS_SYSTEM_RESOLVER_SUCCESS, and TPS_REF_DEFAULT.
Referenced by asterisk_daemon().
 {
    /* Register the base resolver */
    int res = ast_dns_resolver_register(&dns_system_resolver_base);
    if (res) {
       return DNS_SYSTEM_RESOLVER_FAILURE;
    }
    /* Instantiate the task processor */
    dns_system_resolver_tp = ast_taskprocessor_get("dns_system_resolver_tp",
                                                    TPS_REF_DEFAULT);
    /* Return error if the task processor failed to instantiate */
    if (!dns_system_resolver_tp) {
       return DNS_SYSTEM_RESOLVER_FAILURE;
    }
    /* Register the cleanup function */
    ast_register_cleanup(dns_system_resolver_destroy);
    return DNS_SYSTEM_RESOLVER_SUCCESS;
 }
ast_endpoint_init()
int ast_endpoint_init (void)
Endpoint support initialization.
Returns
0 on success.
Non-zero on error.
Definition at line 496 of file main/endpoints.c.
References AO2_ALLOC_OPT_LOCK_MUTEX, ao2_container_alloc_hash, ast_register_cleanup(), ENDPOINT_BUCKETS, endpoint_cleanup(), NULL, and TECH_ENDPOINT_BUCKETS.
Referenced by asterisk_daemon().
 {
    ast_register_cleanup(endpoint_cleanup);
    endpoints = ao2_container_alloc_hash(AO2_ALLOC_OPT_LOCK_MUTEX, 0, ENDPOINT_BUCKETS,
       ast_endpoint_hash_fn, NULL, ast_endpoint_cmp_fn);
    if (!endpoints) {
       return -1;
    }
    tech_endpoints = ao2_container_alloc_hash(AO2_ALLOC_OPT_LOCK_MUTEX, 0,
       TECH_ENDPOINT_BUCKETS, ast_endpoint_hash_fn, NULL, ast_endpoint_cmp_fn);
    if (!tech_endpoints) {
       return -1;
    }
    return 0;
 }
ast_file_init()
int ast_file_init (void)
Provided by file.c
Definition at line 1983 of file file.c.
Referenced by asterisk_daemon().
 {
    STASIS_MESSAGE_TYPE_INIT(ast_format_register_type);
    STASIS_MESSAGE_TYPE_INIT(ast_format_unregister_type);
    ast_cli_register_multiple(cli_file, ARRAY_LEN(cli_file));
    ast_register_cleanup(file_shutdown);
    return 0;
 }
ast_local_init()
int ast_local_init (void)
Initialize the local proxy channel.
Since
12.0.0
Return values
0 on success.
-1 on error.
Definition at line 1140 of file core_local.c.
References AO2_ALLOC_OPT_LOCK_MUTEX, ao2_container_alloc_list, ARRAY_LEN, ast_channel_register(), ast_cli_register_multiple, ast_format_cap_alloc, ast_format_cap_append_by_type(), AST_FORMAT_CAP_FLAG_DEFAULT, ast_local_bridge_type(), ast_local_optimization_begin_type(), ast_local_optimization_end_type(), ast_log, ast_manager_register_xml_core, AST_MEDIA_TYPE_UNKNOWN, ast_register_cleanup(), ast_channel_tech::capabilities, EVENT_FLAG_CALL, EVENT_FLAG_SYSTEM, local_shutdown(), locals_cmp_cb(), LOG_ERROR, manager_optimize_away(), NULL, and STASIS_MESSAGE_TYPE_INIT.
Referenced by asterisk_daemon().
 {
    if (STASIS_MESSAGE_TYPE_INIT(ast_local_optimization_begin_type)) {
       return -1;
    }
    if (STASIS_MESSAGE_TYPE_INIT(ast_local_optimization_end_type)) {
       return -1;
    }
    if (STASIS_MESSAGE_TYPE_INIT(ast_local_bridge_type)) {
       return -1;
    }
    if (!(local_tech.capabilities = ast_format_cap_alloc(AST_FORMAT_CAP_FLAG_DEFAULT))) {
       return -1;
    }
    ast_format_cap_append_by_type(local_tech.capabilities, AST_MEDIA_TYPE_UNKNOWN);
    locals = ao2_container_alloc_list(AO2_ALLOC_OPT_LOCK_MUTEX, 0, NULL, locals_cmp_cb);
    if (!locals) {
       return -1;
    }
    /* Make sure we can register our channel type */
    if (ast_channel_register(&local_tech)) {
       ast_log(LOG_ERROR, "Unable to register channel class 'Local'\n");
       return -1;
    }
    ast_cli_register_multiple(cli_local, ARRAY_LEN(cli_local));
    ast_manager_register_xml_core("LocalOptimizeAway", EVENT_FLAG_SYSTEM|EVENT_FLAG_CALL, manager_optimize_away);
    ast_register_cleanup(local_shutdown);
    return 0;
 }
ast_msg_init()
int ast_msg_init (void)
Provided by message.c
Definition at line 1730 of file message.c.
References __ast_custom_function_register(), action_messagesend(), ast_manager_register_xml_core, ast_msg_handler_register(), ast_register_application2(), ast_register_cleanup(), ast_rwlock_init, ast_taskprocessor_get(), AST_VECTOR_INIT, EVENT_FLAG_MESSAGE, message_shutdown(), msg_send_exec(), NULL, and TPS_REF_DEFAULT.
Referenced by asterisk_daemon().
 {
    int res;
    msg_q_tp = ast_taskprocessor_get("ast_msg_queue", TPS_REF_DEFAULT);
    if (!msg_q_tp) {
       return -1;
    }
    ast_rwlock_init(&msg_techs_lock);
    if (AST_VECTOR_INIT(&msg_techs, 8)) {
       return -1;
    }
    ast_rwlock_init(&msg_handlers_lock);
    if (AST_VECTOR_INIT(&msg_handlers, 4)) {
       return -1;
    }
    res = ast_msg_handler_register(&dialplan_msg_handler);
    res |= __ast_custom_function_register(&msg_function, NULL);
    res |= __ast_custom_function_register(&msg_data_function, NULL);
    res |= ast_register_application2(app_msg_send, msg_send_exec, NULL, NULL, NULL);
    res |= ast_manager_register_xml_core("MessageSend", EVENT_FLAG_MESSAGE, action_messagesend);
    ast_register_cleanup(message_shutdown);
    return res;
 }
ast_msg_shutdown()
void ast_msg_shutdown (void)
Provided by message.c
Definition at line 1689 of file message.c.
References ast_taskprocessor_unreference().
Referenced by can_safely_quit().
 {
    if (msg_q_tp) {
       msg_q_tp = ast_taskprocessor_unreference(msg_q_tp);
    }
 }
ast_named_locks_init()
int ast_named_locks_init (void)
Provided by named_locks.c
Definition at line 52 of file named_locks.c.
References AO2_ALLOC_OPT_LOCK_MUTEX, ao2_container_alloc_hash, ast_register_cleanup(), NAMED_LOCKS_BUCKETS, named_locks_shutdown(), and NULL.
Referenced by asterisk_daemon().
 {
    named_locks = ao2_container_alloc_hash(AO2_ALLOC_OPT_LOCK_MUTEX, 0,
       NAMED_LOCKS_BUCKETS, named_lock_proxy_hash_fn, NULL, named_lock_proxy_cmp_fn);
    if (!named_locks) {
       return -1;
    }
    ast_register_cleanup(named_locks_shutdown);
    return 0;
 }
ast_parking_stasis_init()
int ast_parking_stasis_init (void)
initializes the rtp engine arrays
Since
12.0.0
Definition at line 53 of file parking.c.
References ast_parked_call_type(), ast_register_cleanup(), parking_stasis_cleanup(), STASIS_MESSAGE_TYPE_INIT, and stasis_topic_create().
Referenced by asterisk_daemon().
 {
    if (STASIS_MESSAGE_TYPE_INIT(ast_parked_call_type)) {
       return -1;
    }
    parking_topic = stasis_topic_create("parking:all");
    if (!parking_topic) {
       return -1;
    }
    ast_register_cleanup(parking_stasis_cleanup);
    return 0;
 }
ast_pj_init()
int ast_pj_init (void)
Provided by libasteriskpj.c
Definition at line 45 of file libasteriskpj.c.
References AST_PJPROJECT_INIT_LOG_LEVEL.
Referenced by asterisk_daemon().
 {
 #ifdef HAVE_PJPROJECT_BUNDLED
    AST_PJPROJECT_INIT_LOG_LEVEL();
    pj_init();
 #endif
    return 0;
 }
ast_process_pending_reloads()
void ast_process_pending_reloads (void)
Process reload requests received during startup.
This function requests that the loader execute the pending reload requests that were queued during server startup.
Note
This function will do nothing if the server has not completely started up. Once called, the reload queue is emptied, and further invocations will have no affect.
Definition at line 1407 of file loader.c.
References ast_free, AST_LIST_LOCK, AST_LIST_REMOVE_HEAD, AST_LIST_UNLOCK, ast_log, ast_module_reload(), item, LOG_NOTICE, reload_queue_item::module, and NULL.
Referenced by asterisk_daemon().
 {
    struct reload_queue_item *item;
    modules_loaded = 1;
    AST_LIST_LOCK(&reload_queue);
    if (do_full_reload) {
       do_full_reload = 0;
       AST_LIST_UNLOCK(&reload_queue);
       ast_log(LOG_NOTICE, "Executing deferred reload request.\n");
       ast_module_reload(NULL);
       return;
    }
    while ((item = AST_LIST_REMOVE_HEAD(&reload_queue, entry))) {
       ast_log(LOG_NOTICE, "Executing deferred reload request for module '%s'.\n", item->module);
       ast_module_reload(item->module);
       ast_free(item);
    }
    AST_LIST_UNLOCK(&reload_queue);
 }
ast_rtp_engine_init()
int ast_rtp_engine_init (void)
initializes the rtp engine arrays
Definition at line 3622 of file rtp_engine.c.
References add_static_payload(), ast_debug_category_register(), ast_format_adpcm, ast_format_alaw, ast_format_g719, ast_format_g722, ast_format_g723, ast_format_g726, ast_format_g726_aal2, ast_format_g729, ast_format_gsm, ast_format_h261, ast_format_h263, ast_format_h263p, ast_format_h264, ast_format_h265, ast_format_ilbc, ast_format_jpeg, ast_format_lpc10, ast_format_mp4, ast_format_opus, ast_format_png, ast_format_siren14, ast_format_siren7, ast_format_slin, ast_format_slin12, ast_format_slin16, ast_format_slin192, ast_format_slin24, ast_format_slin32, ast_format_slin44, ast_format_slin48, ast_format_slin96, ast_format_speex, ast_format_speex16, ast_format_speex32, ast_format_t140, ast_format_t140_red, ast_format_ulaw, ast_format_vp8, ast_format_vp9, AST_LOG_CATEGORY_DTLS, AST_LOG_CATEGORY_DTLS_PACKET, AST_LOG_CATEGORY_ICE, AST_LOG_CATEGORY_RTCP, AST_LOG_CATEGORY_RTCP_PACKET, AST_LOG_CATEGORY_RTP, AST_LOG_CATEGORY_RTP_PACKET, ast_register_cleanup(), AST_RTP_CISCO_DTMF, AST_RTP_CN, AST_RTP_DTMF, ast_rtp_rtcp_received_type(), ast_rtp_rtcp_sent_type(), ast_rwlock_init, debug_category_dtls_id, debug_category_dtls_packet_id, debug_category_ice_id, debug_category_rtcp_id, debug_category_rtcp_packet_id, debug_category_rtp_id, debug_category_rtp_packet_id, NULL, rtp_engine_shutdown(), set_next_mime_type(), STASIS_MESSAGE_TYPE_INIT, and stasis_topic_create().
Referenced by asterisk_daemon().
 {
    ast_rwlock_init(&mime_types_lock);
    ast_rwlock_init(&static_RTP_PT_lock);
    rtp_topic = stasis_topic_create("rtp:all");
    if (!rtp_topic) {
       return -1;
    }
    STASIS_MESSAGE_TYPE_INIT(ast_rtp_rtcp_sent_type);
    STASIS_MESSAGE_TYPE_INIT(ast_rtp_rtcp_received_type);
    ast_register_cleanup(rtp_engine_shutdown);
    /* Define all the RTP mime types available */
    set_next_mime_type(ast_format_g723, 0, "audio", "G723", 8000);
    set_next_mime_type(ast_format_gsm, 0, "audio", "GSM", 8000);
    set_next_mime_type(ast_format_ulaw, 0, "audio", "PCMU", 8000);
    set_next_mime_type(ast_format_ulaw, 0, "audio", "G711U", 8000);
    set_next_mime_type(ast_format_alaw, 0, "audio", "PCMA", 8000);
    set_next_mime_type(ast_format_alaw, 0, "audio", "G711A", 8000);
    set_next_mime_type(ast_format_g726, 0, "audio", "G726-32", 8000);
    set_next_mime_type(ast_format_adpcm, 0, "audio", "DVI4", 8000);
    set_next_mime_type(ast_format_slin, 0, "audio", "L16", 8000);
    set_next_mime_type(ast_format_slin16, 0, "audio", "L16", 16000);
    set_next_mime_type(ast_format_slin16, 0, "audio", "L16-256", 16000);
    set_next_mime_type(ast_format_slin12, 0, "audio", "L16", 12000);
    set_next_mime_type(ast_format_slin24, 0, "audio", "L16", 24000);
    set_next_mime_type(ast_format_slin32, 0, "audio", "L16", 32000);
    set_next_mime_type(ast_format_slin44, 0, "audio", "L16", 44000);
    set_next_mime_type(ast_format_slin48, 0, "audio", "L16", 48000);
    set_next_mime_type(ast_format_slin96, 0, "audio", "L16", 96000);
    set_next_mime_type(ast_format_slin192, 0, "audio", "L16", 192000);
    set_next_mime_type(ast_format_lpc10, 0, "audio", "LPC", 8000);
    set_next_mime_type(ast_format_g729, 0, "audio", "G729", 8000);
    set_next_mime_type(ast_format_g729, 0, "audio", "G729A", 8000);
    set_next_mime_type(ast_format_g729, 0, "audio", "G.729", 8000);
    set_next_mime_type(ast_format_speex, 0, "audio", "speex", 8000);
    set_next_mime_type(ast_format_speex16, 0,  "audio", "speex", 16000);
    set_next_mime_type(ast_format_speex32, 0,  "audio", "speex", 32000);
    set_next_mime_type(ast_format_ilbc, 0, "audio", "iLBC", 8000);
    /* this is the sample rate listed in the RTP profile for the G.722 codec, *NOT* the actual sample rate of the media stream */
    set_next_mime_type(ast_format_g722, 0, "audio", "G722", 8000);
    set_next_mime_type(ast_format_g726_aal2, 0, "audio", "AAL2-G726-32", 8000);
    set_next_mime_type(NULL, AST_RTP_DTMF, "audio", "telephone-event", 8000);
    set_next_mime_type(NULL, AST_RTP_CISCO_DTMF, "audio", "cisco-telephone-event", 8000);
    set_next_mime_type(NULL, AST_RTP_CN, "audio", "CN", 8000);
    set_next_mime_type(ast_format_jpeg, 0, "video", "JPEG", 90000);
    set_next_mime_type(ast_format_png, 0, "video", "PNG", 90000);
    set_next_mime_type(ast_format_h261, 0, "video", "H261", 90000);
    set_next_mime_type(ast_format_h263, 0, "video", "H263", 90000);
    set_next_mime_type(ast_format_h263p, 0, "video", "h263-1998", 90000);
    set_next_mime_type(ast_format_h264, 0, "video", "H264", 90000);
    set_next_mime_type(ast_format_h265, 0, "video", "H265", 90000);
    set_next_mime_type(ast_format_mp4, 0, "video", "MP4V-ES", 90000);
    set_next_mime_type(ast_format_t140_red, 0, "text", "RED", 1000);
    set_next_mime_type(ast_format_t140, 0, "text", "T140", 1000);
    set_next_mime_type(ast_format_siren7, 0, "audio", "G7221", 16000);
    set_next_mime_type(ast_format_siren14, 0, "audio", "G7221", 32000);
    set_next_mime_type(ast_format_g719, 0, "audio", "G719", 48000);
    /* Opus, VP8, and VP9 */
    set_next_mime_type(ast_format_opus, 0,  "audio", "opus", 48000);
    set_next_mime_type(ast_format_vp8, 0,  "video", "VP8", 90000);
    set_next_mime_type(ast_format_vp9, 0, "video", "VP9", 90000);
    /* Define the static rtp payload mappings */
    add_static_payload(0, ast_format_ulaw, 0);
    #ifdef USE_DEPRECATED_G726
    add_static_payload(2, ast_format_g726, 0);/* Technically this is G.721, but if Cisco can do it, so can we... */
    #endif
    add_static_payload(3, ast_format_gsm, 0);
    add_static_payload(4, ast_format_g723, 0);
    add_static_payload(5, ast_format_adpcm, 0);/* 8 kHz */
    add_static_payload(6, ast_format_adpcm, 0); /* 16 kHz */
    add_static_payload(7, ast_format_lpc10, 0);
    add_static_payload(8, ast_format_alaw, 0);
    add_static_payload(9, ast_format_g722, 0);
    add_static_payload(10, ast_format_slin, 0); /* 2 channels */
    add_static_payload(11, ast_format_slin, 0); /* 1 channel */
    add_static_payload(13, NULL, AST_RTP_CN);
    add_static_payload(16, ast_format_adpcm, 0); /* 11.025 kHz */
    add_static_payload(17, ast_format_adpcm, 0); /* 22.050 kHz */
    add_static_payload(18, ast_format_g729, 0);
    add_static_payload(19, NULL, AST_RTP_CN);         /* Also used for CN */
    add_static_payload(26, ast_format_jpeg, 0);
    add_static_payload(31, ast_format_h261, 0);
    add_static_payload(34, ast_format_h263, 0);
    /*
     * Dynamic payload types - Even when dynamically assigning them we'll fall
     * back to using the statically declared values as the default number.
     */
    add_static_payload(96, ast_format_slin192, 0);
    add_static_payload(97, ast_format_ilbc, 0);
    add_static_payload(99, ast_format_h264, 0);
    add_static_payload(100, ast_format_vp8, 0);
    add_static_payload(101, NULL, AST_RTP_DTMF);
    add_static_payload(102, ast_format_siren7, 0);
    add_static_payload(103, ast_format_h263p, 0);
    add_static_payload(104, ast_format_mp4, 0);
    add_static_payload(105, ast_format_t140_red, 0);   /* Real time text chat (with redundancy encoding) */
    add_static_payload(106, ast_format_t140, 0);     /* Real time text chat */
    add_static_payload(107, ast_format_opus, 0);
    add_static_payload(108, ast_format_vp9, 0);
    add_static_payload(109, ast_format_h265, 0);
    add_static_payload(110, ast_format_speex, 0);
    add_static_payload(111, ast_format_g726, 0);
    add_static_payload(112, ast_format_g726_aal2, 0);
    add_static_payload(115, ast_format_siren14, 0);
    add_static_payload(116, ast_format_g719, 0);
    add_static_payload(117, ast_format_speex16, 0);
    add_static_payload(118, ast_format_slin16, 0); /* 16 Khz signed linear */
    add_static_payload(119, ast_format_speex32, 0);
    add_static_payload(121, NULL, AST_RTP_CISCO_DTMF);   /* Must be type 121 */
    add_static_payload(122, ast_format_slin12, 0);
    add_static_payload(123, ast_format_slin24, 0);
    add_static_payload(124, ast_format_slin32, 0);
    add_static_payload(125, ast_format_slin44, 0);
    add_static_payload(126, ast_format_slin48, 0);
    add_static_payload(127, ast_format_slin96, 0);
    /* payload types above 127 are not valid */
    debug_category_rtp_id = ast_debug_category_register(AST_LOG_CATEGORY_RTP);
    debug_category_rtp_packet_id = ast_debug_category_register(AST_LOG_CATEGORY_RTP_PACKET);
    debug_category_rtcp_id = ast_debug_category_register(AST_LOG_CATEGORY_RTCP);
    debug_category_rtcp_packet_id = ast_debug_category_register(AST_LOG_CATEGORY_RTCP_PACKET);
    debug_category_dtls_id = ast_debug_category_register(AST_LOG_CATEGORY_DTLS);
    debug_category_dtls_packet_id = ast_debug_category_register(AST_LOG_CATEGORY_DTLS_PACKET);
    debug_category_ice_id = ast_debug_category_register(AST_LOG_CATEGORY_ICE);
    return 0;
 }
ast_ssl_init()
int ast_ssl_init (void)
Provided by ssl.c
Definition at line 130 of file libasteriskssl.c.
References ast_calloc, ast_debug, ast_mutex_init, CRYPTO_set_id_callback(), CRYPTO_set_locking_callback(), get_OpenSSL_function, NULL, SSL_library_init(), SSL_load_error_strings(), ssl_lock(), ssl_num_locks, ssl_threadid(), and startup_complete.
Referenced by asterisk_daemon().
 {
    unsigned int i;
    int (*real_SSL_library_init)(void);
 #if OPENSSL_VERSION_NUMBER < 0x10000000L
    void (*real_CRYPTO_set_id_callback)(unsigned long (*)(void));
 #endif
    void (*real_CRYPTO_set_locking_callback)(void (*)(int, int, const char *, int));
    void (*real_SSL_load_error_strings)(void);
    const char *errstr;
    /* clear any previous dynamic linker errors */
    dlerror();
    get_OpenSSL_function(SSL_library_init);
    if ((errstr = dlerror()) != NULL) {
       ast_debug(1, "unable to get real address of SSL_library_init: %s\n", errstr);
       /* there is no way to continue in this situation... SSL will
        * likely be broken in this process
        */
       return -1;
    } else {
       real_SSL_library_init();
    }
    /* Make OpenSSL usage thread-safe. */
 #if OPENSSL_VERSION_NUMBER < 0x10000000L
    dlerror();
    get_OpenSSL_function(CRYPTO_set_id_callback);
    if ((errstr = dlerror()) != NULL) {
       ast_debug(1, "unable to get real address of CRYPTO_set_id_callback: %s\n", errstr);
       /* there is no way to continue in this situation... SSL will
        * likely be broken in this process
        */
       return -1;
    } else {
       real_CRYPTO_set_id_callback(ssl_threadid);
    }
 #endif
    dlerror();
    get_OpenSSL_function(CRYPTO_set_locking_callback);
    if ((errstr = dlerror()) != NULL) {
       ast_debug(1, "unable to get real address of CRYPTO_set_locking_callback: %s\n", errstr);
       /* there is no way to continue in this situation... SSL will
        * likely be broken in this process
        */
       return -1;
    } else {
       ssl_num_locks = CRYPTO_num_locks();
       if (!(ssl_locks = ast_calloc(ssl_num_locks, sizeof(ssl_locks[0])))) {
          return -1;
       }
       for (i = 0; i < ssl_num_locks; i++) {
          ast_mutex_init(&ssl_locks[i]);
       }
       real_CRYPTO_set_locking_callback(ssl_lock);
    }
    /* after this point, we don't check for errors from the dlsym() calls,
     * under the assumption that if the ones above were successful, all
     * the rest will be too. this assumption holds as long as OpenSSL still
     * provides all of these functions.
     */
    get_OpenSSL_function(SSL_load_error_strings);
    real_SSL_load_error_strings();
    startup_complete = 1;
    return 0;
 }
ast_stun_init()
void ast_stun_init (void)
Initialize the STUN system in Asterisk.
Provided by stun.c
Definition at line 543 of file stun.c.
References ast_cli_register_multiple, ast_debug_category_register(), AST_LOG_CATEGORY_STUN, AST_LOG_CATEGORY_STUN_PACKET, ast_register_cleanup(), and stun_shutdown().
Referenced by asterisk_daemon().
 {
    ast_cli_register_multiple(cli_stun, sizeof(cli_stun) / sizeof(struct ast_cli_entry));
    ast_register_cleanup(stun_shutdown);
    debug_category_stun_id = ast_debug_category_register(AST_LOG_CATEGORY_STUN);
    debug_category_stun_packet_id = ast_debug_category_register(AST_LOG_CATEGORY_STUN_PACKET);
 }
ast_term_init()
int ast_term_init (void)
Provided by term.c
Definition at line 92 of file term.c.
References ast_opt_console, ast_opt_force_black_background, ast_opt_light_background, ast_opt_no_color, ATTR_RESET, commonbuf::buffer, COLOR_BLACK, COLOR_WHITE, convshort(), end, enddata, ESC, NULL, quitdata, termpath, and vt100compat.
Referenced by ast_remotecontrol(), asterisk_daemon(), and main().
 {
    char *term = getenv("TERM");
    char termfile[256] = "";
    char buffer[512] = "";
    int termfd = -1, parseokay = 0, i;
    if (ast_opt_no_color) {
       return 0;
    }
    if (!ast_opt_console) {
       /* If any remote console is not compatible, we'll strip the color codes at that point */
       vt100compat = 1;
       goto end;
    }
    if (!term) {
       return 0;
    }
    for (i = 0;; i++) {
       if (termpath[i] == NULL) {
          break;
       }
       snprintf(termfile, sizeof(termfile), "%s/%c/%s", termpath[i], *term, term);
       termfd = open(termfile, O_RDONLY);
       if (termfd > -1) {
          break;
       }
    }
    if (termfd > -1) {
       int actsize = read(termfd, buffer, sizeof(buffer) - 1);
       short sz_names = convshort(buffer + 2);
       short sz_bools = convshort(buffer + 4);
       short n_nums   = convshort(buffer + 6);
       /* if ((sz_names + sz_bools) & 1)
          sz_bools++; */
       if (sz_names + sz_bools + n_nums < actsize) {
          /* Offset 13 is defined in /usr/include/term.h, though we do not
           * include it here, as it conflicts with include/asterisk/term.h */
          short max_colors = convshort(buffer + 12 + sz_names + sz_bools + 13 * 2);
          if (max_colors > 0) {
             vt100compat = 1;
          }
          parseokay = 1;
       }
       close(termfd);
    }
    if (!parseokay) {
       /* These comparisons should not be substrings nor case-insensitive, as
        * terminal types are very particular about how they treat suffixes and
        * capitalization.  For example, terminal type 'linux-m' does NOT
        * support color, while 'linux' does.  Not even all vt100* terminals
        * support color, either (e.g. 'vt100+fnkeys'). */
       if (!strcmp(term, "linux")) {
          vt100compat = 1;
       } else if (!strcmp(term, "xterm")) {
          vt100compat = 1;
       } else if (!strcmp(term, "xterm-color")) {
          vt100compat = 1;
       } else if (!strcmp(term, "xterm-256color")) {
          vt100compat = 1;
       } else if (!strncmp(term, "Eterm", 5)) {
          /* Both entries which start with Eterm support color */
          vt100compat = 1;
       } else if (!strcmp(term, "vt100")) {
          vt100compat = 1;
       } else if (!strncmp(term, "crt", 3)) {
          /* Both crt terminals support color */
          vt100compat = 1;
       }
    }
 end:
    if (vt100compat) {
       /* Make commands show up in nice colors */
       if (ast_opt_light_background) {
          snprintf(enddata, sizeof(enddata), "%c[%dm", ESC, COLOR_BLACK);
       } else if (ast_opt_force_black_background) {
          snprintf(enddata, sizeof(enddata), "%c[%d;%d;%dm", ESC, ATTR_RESET, COLOR_WHITE, COLOR_BLACK + 10);
       } else {
          snprintf(enddata, sizeof(enddata), "%c[%dm", ESC, ATTR_RESET);
       }
       snprintf(quitdata, sizeof(quitdata), "%c[%dm", ESC, ATTR_RESET);
    }
    return 0;
 }
ast_test_init()
int ast_test_init (void)
Provided by test.c
Definition at line 1221 of file test.c.
References ARRAY_LEN, ast_cli_register_multiple, ast_register_cleanup(), AST_TEST_REGISTER, STASIS_MESSAGE_TYPE_INIT, stasis_topic_create(), and test_cleanup().
Referenced by asterisk_daemon().
 {
 #ifdef TEST_FRAMEWORK
    ast_register_cleanup(test_cleanup);
    /* Create stasis topic */
    test_suite_topic = stasis_topic_create("testsuite:all");
    if (!test_suite_topic) {
       return -1;
    }
    if (STASIS_MESSAGE_TYPE_INIT(ast_test_suite_message_type) != 0) {
       return -1;
    }
    AST_TEST_REGISTER(test_registrations);
    /* Register cli commands */
    ast_cli_register_multiple(test_cli, ARRAY_LEN(test_cli));
 #endif
    return 0;
 }
ast_timing_init()
int ast_timing_init (void)
Provided by timing.c
Definition at line 289 of file timing.c.
References ARRAY_LEN, ast_cli_register_multiple, ast_heap_create, ast_register_cleanup(), timing_holder_cmp(), and timing_shutdown().
Referenced by asterisk_daemon().
 {
    if (!(timing_interfaces = ast_heap_create(2, timing_holder_cmp, 0))) {
       return -1;
    }
    ast_register_cleanup(timing_shutdown);
    return ast_cli_register_multiple(cli_timing, ARRAY_LEN(cli_timing));
 }
ast_tps_init()
int ast_tps_init (void)
Provided by taskprocessor.c
Definition at line 301 of file taskprocessor.c.
References AO2_ALLOC_OPT_LOCK_MUTEX, ao2_container_alloc_hash, ao2_ref, ARRAY_LEN, ast_cli_register_multiple, ast_cond_init, ast_log, ast_register_cleanup(), AST_VECTOR_RW_INIT, LOG_ERROR, NULL, tps_cmp_cb(), tps_hash_cb(), TPS_MAX_BUCKETS, and tps_shutdown().
Referenced by asterisk_daemon().
 {
    tps_singletons = ao2_container_alloc_hash(AO2_ALLOC_OPT_LOCK_MUTEX, 0,
       TPS_MAX_BUCKETS, tps_hash_cb, NULL, tps_cmp_cb);
    if (!tps_singletons) {
       ast_log(LOG_ERROR, "taskprocessor container failed to initialize!\n");
       return -1;
    }
    if (AST_VECTOR_RW_INIT(&overloaded_subsystems, 10)) {
       ao2_ref(tps_singletons, -1);
       ast_log(LOG_ERROR, "taskprocessor subsystems vector failed to initialize!\n");
       return -1;
    }
    ast_cond_init(&cli_ping_cond, NULL);
    ast_cli_register_multiple(taskprocessor_clis, ARRAY_LEN(taskprocessor_clis));
    ast_register_cleanup(tps_shutdown);
    return 0;
 }
ast_xmldoc_load_documentation()
int ast_xmldoc_load_documentation (void)
Load XML documentation. Provided by xmldoc.c.
Return values
1 on error.
0 on success.
Definition at line 2879 of file xmldoc.c.
References ast_asprintf, ast_calloc, ast_cli_register, ast_config_AST_DATA_DIR, ast_config_destroy(), ast_config_load2(), ast_debug, ast_free, ast_log, ast_malloc, ast_register_cleanup(), AST_RWLIST_INSERT_TAIL, AST_RWLIST_UNLOCK, AST_RWLIST_WRLOCK, ast_strdup, ast_strlen_zero, ast_variable_browse(), ast_xml_close(), ast_xml_get_root(), ast_xml_init(), ast_xml_node_get_name(), ast_xml_open(), CONFIG_STATUS_FILEINVALID, default_documentation_language, documentation_tree::doc, documentation_language, documentation_tree::filename, GLOB_ABORTED, LOG_ERROR, LOG_WARNING, MY_GLOB_FLAGS, ast_variable::name, ast_variable::next, NULL, ast_variable::value, var, and xmldoc_unload_documentation().
Referenced by asterisk_daemon().
 {
    struct ast_xml_node *root_node;
    struct ast_xml_doc *tmpdoc;
    struct documentation_tree *doc_tree;
    char *xmlpattern;
    struct ast_config *cfg = NULL;
    struct ast_variable *var = NULL;
    struct ast_flags cnfflags = { 0 };
    int globret, i, dup, duplicate;
    glob_t globbuf;
 #if !defined(HAVE_GLOB_NOMAGIC) || !defined(HAVE_GLOB_BRACE) || defined(DEBUG_NONGNU)
    int xmlpattern_maxlen;
 #endif
    /* setup default XML documentation language */
    snprintf(documentation_language, sizeof(documentation_language), default_documentation_language);
    if ((cfg = ast_config_load2("asterisk.conf", "" /* core can't reload */, cnfflags)) && cfg != CONFIG_STATUS_FILEINVALID) {
       for (var = ast_variable_browse(cfg, "options"); var; var = var->next) {
          if (!strcasecmp(var->name, "documentation_language")) {
             if (!ast_strlen_zero(var->value)) {
                snprintf(documentation_language, sizeof(documentation_language), "%s", var->value);
             }
          }
       }
       ast_config_destroy(cfg);
    }
    /* initialize the XML library. */
    ast_xml_init();
    ast_cli_register(&cli_dump_xmldocs);
    /* register function to be run when asterisk finish. */
    ast_register_cleanup(xmldoc_unload_documentation);
    globbuf.gl_offs = 0;    /* slots to reserve in gl_pathv */
 #if !defined(HAVE_GLOB_NOMAGIC) || !defined(HAVE_GLOB_BRACE) || defined(DEBUG_NONGNU)
    xmlpattern_maxlen = strlen(ast_config_AST_DATA_DIR) + strlen("/documentation/thirdparty") + strlen("/*-??_??.xml") + 1;
    xmlpattern = ast_malloc(xmlpattern_maxlen);
    globret = xml_pathmatch(xmlpattern, xmlpattern_maxlen, &globbuf);
 #else
    /* Get every *-LANG.xml file inside $(ASTDATADIR)/documentation */
    if (ast_asprintf(&xmlpattern, "%s/documentation{/thirdparty/,/}*-{%s,%.2s_??,%s}.xml", ast_config_AST_DATA_DIR,
       documentation_language, documentation_language, default_documentation_language) < 0) {
       return 1;
    }
    globret = glob(xmlpattern, MY_GLOB_FLAGS, NULL, &globbuf);
 #endif
    ast_debug(3, "gl_pathc %zu\n", (size_t)globbuf.gl_pathc);
    if (globret == GLOB_NOSPACE) {
       ast_log(LOG_WARNING, "XML load failure, glob expansion of pattern '%s' failed: Not enough memory\n", xmlpattern);
       ast_free(xmlpattern);
       return 1;
    } else if (globret  == GLOB_ABORTED) {
       ast_log(LOG_WARNING, "XML load failure, glob expansion of pattern '%s' failed: Read error\n", xmlpattern);
       ast_free(xmlpattern);
       return 1;
    }
    ast_free(xmlpattern);
    AST_RWLIST_WRLOCK(&xmldoc_tree);
    /* loop over expanded files */
    for (i = 0; i < globbuf.gl_pathc; i++) {
       /* check for duplicates (if we already [try to] open the same file. */
       duplicate = 0;
       for (dup = 0; dup < i; dup++) {
          if (!strcmp(globbuf.gl_pathv[i], globbuf.gl_pathv[dup])) {
             duplicate = 1;
             break;
          }
       }
       if (duplicate || strchr(globbuf.gl_pathv[i], '*')) {
       /* skip duplicates as well as pathnames not found
        * (due to use of GLOB_NOCHECK in xml_pathmatch) */
          continue;
       }
       tmpdoc = NULL;
       tmpdoc = ast_xml_open(globbuf.gl_pathv[i]);
       if (!tmpdoc) {
          ast_log(LOG_ERROR, "Could not open XML documentation at '%s'\n", globbuf.gl_pathv[i]);
          continue;
       }
       /* Get doc root node and check if it starts with '<docs>' */
       root_node = ast_xml_get_root(tmpdoc);
       if (!root_node) {
          ast_log(LOG_ERROR, "Error getting documentation root node\n");
          ast_xml_close(tmpdoc);
          continue;
       }
       /* Check root node name for malformed xmls. */
       if (strcmp(ast_xml_node_get_name(root_node), "docs")) {
          ast_log(LOG_ERROR, "Documentation file is not well formed!\n");
          ast_xml_close(tmpdoc);
          continue;
       }
       doc_tree = ast_calloc(1, sizeof(*doc_tree));
       if (!doc_tree) {
          ast_log(LOG_ERROR, "Unable to allocate documentation_tree structure!\n");
          ast_xml_close(tmpdoc);
          continue;
       }
       doc_tree->doc = tmpdoc;
       doc_tree->filename = ast_strdup(globbuf.gl_pathv[i]);
       AST_RWLIST_INSERT_TAIL(&xmldoc_tree, doc_tree, entry);
    }
    AST_RWLIST_UNLOCK(&xmldoc_tree);
    globfree(&globbuf);
    return 0;
 }
astdb_init()
int astdb_init (void)
Provided by db.c
Definition at line 1082 of file main/db.c.
References ARRAY_LEN, ast_cli_register_multiple, ast_cond_init, ast_manager_register_xml_core, ast_pthread_create_background, ast_register_atexit(), astdb_atexit(), db_init(), db_sync_thread(), dbcond, EVENT_FLAG_REPORTING, EVENT_FLAG_SYSTEM, manager_dbdel(), manager_dbdeltree(), manager_dbget(), manager_dbput(), NULL, and syncthread.
Referenced by asterisk_daemon().
 {
    ast_cond_init(&dbcond, NULL);
    if (db_init()) {
       return -1;
    }
    if (ast_pthread_create_background(&syncthread, NULL, db_sync_thread, NULL)) {
       return -1;
    }
    ast_register_atexit(astdb_atexit);
    ast_cli_register_multiple(cli_database, ARRAY_LEN(cli_database));
    ast_manager_register_xml_core("DBGet", EVENT_FLAG_SYSTEM | EVENT_FLAG_REPORTING, manager_dbget);
    ast_manager_register_xml_core("DBPut", EVENT_FLAG_SYSTEM, manager_dbput);
    ast_manager_register_xml_core("DBDel", EVENT_FLAG_SYSTEM, manager_dbdel);
    ast_manager_register_xml_core("DBDelTree", EVENT_FLAG_SYSTEM, manager_dbdeltree);
    return 0;
 }
astobj2_init()
int astobj2_init (void)
Provided by astobj2.c
Definition at line 1166 of file astobj2.c.
References ARRAY_LEN, ast_cli_register_multiple, ast_config_AST_LOG_DIR, ast_log, ast_opt_ref_debug, ast_register_cleanup(), astobj2_cleanup(), container_init(), LOG_ERROR, NULL, and ref_log.
Referenced by asterisk_daemon().
 {
    char ref_filename[1024];
    if (ast_opt_ref_debug) {
       snprintf(ref_filename, sizeof(ref_filename), "%s/refs", ast_config_AST_LOG_DIR);
       ref_log = fopen(ref_filename, "w");
       if (!ref_log) {
          ast_log(LOG_ERROR, "Could not open ref debug log file: %s\n", ref_filename);
       }
    }
    ast_register_cleanup(astobj2_cleanup);
    if (container_init() != 0) {
       fclose(ref_log);
       ref_log = NULL;
       return -1;
    }
 #if defined(AO2_DEBUG)
    ast_cli_register_multiple(cli_astobj2, ARRAY_LEN(cli_astobj2));
 #endif   /* defined(AO2_DEBUG) */
    return 0;
 }
clean_time_zones()
void clean_time_zones (void)
Provided by localtime.c
Definition at line 1590 of file localtime.c.
References AST_LIST_LOCK, AST_LIST_REMOVE_HEAD, AST_LIST_UNLOCK, state::list, and sstate_free().
Referenced by really_quit().
 {
    struct state *sp;
    AST_LIST_LOCK(&zonelist);
    while ((sp = AST_LIST_REMOVE_HEAD(&zonelist, list))) {
       sstate_free(sp);
    }
    AST_LIST_UNLOCK(&zonelist);
 }
close_logger()
void close_logger (void)
Provided by logger.c
Definition at line 1912 of file logger.c.
References ARRAY_LEN, ast_cli_unregister_multiple(), ast_cond_signal, ast_free, AST_LIST_LOCK, AST_LIST_REMOVE_HEAD, AST_LIST_UNLOCK, ast_logger_category_unload(), AST_PTHREADT_NULL, AST_RWLIST_UNLOCK, AST_RWLIST_WRLOCK, logchannel::fileptr, logchannel::list, logger_initialized, and NULL.
Referenced by really_quit().
 {
    struct logchannel *f = NULL;
    ast_logger_category_unload();
    ast_cli_unregister_multiple(cli_logger, ARRAY_LEN(cli_logger));
    logger_initialized = 0;
    /* Stop logger thread */
    AST_LIST_LOCK(&logmsgs);
    close_logger_thread = 1;
    ast_cond_signal(&logcond);
    AST_LIST_UNLOCK(&logmsgs);
    if (logthread != AST_PTHREADT_NULL) {
       pthread_join(logthread, NULL);
    }
    AST_RWLIST_WRLOCK(&logchannels);
    if (qlog) {
       fclose(qlog);
       qlog = NULL;
    }
    while ((f = AST_LIST_REMOVE_HEAD(&logchannels, list))) {
       if (f->fileptr && (f->fileptr != stdout) && (f->fileptr != stderr)) {
          fclose(f->fileptr);
          f->fileptr = NULL;
       }
       ast_free(f);
    }
    closelog(); /* syslog */
    AST_RWLIST_UNLOCK(&logchannels);
 }
dns_core_init()
int dns_core_init (void)
Provided by dns_core.c
Definition at line 614 of file dns_core.c.
References ast_register_cleanup(), ast_sched_context_create(), ast_sched_start_thread(), and dns_shutdown().
Referenced by asterisk_daemon().
 {
    sched = ast_sched_context_create();
    if (!sched) {
       return -1;
    }
    if (ast_sched_start_thread(sched)) {
       return -1;
    }
    ast_register_cleanup(dns_shutdown);
    return 0;
 }
dnsmgr_start_refresh()
void dnsmgr_start_refresh (void)
Provided by dnsmgr.c
Definition at line 302 of file dnsmgr.c.
References ast_sched_add_variable(), AST_SCHED_DEL, do_reload(), refresh_list(), and refresh_sched.
Referenced by asterisk_daemon().
 {
    if (refresh_sched > -1) {
       AST_SCHED_DEL(sched, refresh_sched);
       refresh_sched = ast_sched_add_variable(sched, 100, refresh_list, &master_refresh_info, 1);
    }
 }
init_logger()
int init_logger (void)
Provided by logger.c
Definition at line 1870 of file logger.c.
References ARRAY_LEN, ast_cli_register_multiple, ast_cond_destroy, ast_cond_init, ast_config_AST_LOG_DIR, ast_log(), ast_logger_category_load(), ast_mkdir(), ast_mutex_destroy, ast_mutex_init, ast_pthread_create, AST_RWLIST_UNLOCK, AST_RWLIST_WRLOCK, ast_verb_update(), init_logger_chain(), logmsgs::lock, LOG_ERROR, logger_initialized, logger_thread(), and NULL.
Referenced by asterisk_daemon().
 {
    int res;
    /* auto rotate if sig SIGXFSZ comes a-knockin */
    sigaction(SIGXFSZ, &handle_SIGXFSZ, NULL);
    /* Re-initialize the logmsgs mutex.  The recursive mutex can be accessed prior
     * to Asterisk being forked into the background, which can cause the thread
     * ID tracked by the underlying pthread mutex to be different than the ID of
     * the thread that unlocks the mutex.  Since init_logger is called after the
     * fork, it is safe to initialize the mutex here for future accesses.
     */
    ast_mutex_destroy(&logmsgs.lock);
    ast_mutex_init(&logmsgs.lock);
    ast_cond_init(&logcond, NULL);
    /* start logger thread */
    if (ast_pthread_create(&logthread, NULL, logger_thread, NULL) < 0) {
       ast_cond_destroy(&logcond);
       return -1;
    }
    /* register the logger cli commands */
    ast_cli_register_multiple(cli_logger, ARRAY_LEN(cli_logger));
    ast_mkdir(ast_config_AST_LOG_DIR, 0777);
    /* create log channels */
    AST_RWLIST_WRLOCK(&logchannels);
    res = init_logger_chain(NULL);
    AST_RWLIST_UNLOCK(&logchannels);
    ast_verb_update();
    logger_initialized = 1;
    if (res) {
       ast_log(LOG_ERROR, "Errors detected in logger.conf.  Default console logging is being used.\n");
    }
    ast_logger_category_load();
    return 0;
 }
load_asterisk_conf()
void load_asterisk_conf (void)
Definition at line 210 of file options.c.
References _cfg_paths::agi_dir, AST_CACHE_DIR_LEN, ast_clear_flag, ast_config_AST_CONFIG_FILE, ast_config_AST_CTL, ast_config_AST_RUN_DIR, ast_config_AST_SYSTEM_NAME, ast_config_destroy(), ast_config_load2(), ast_copy_string(), ast_defaultlanguage, ast_eid_default, ast_language_is_prefix, AST_LOCK_TYPE_FLOCK, AST_LOCK_TYPE_LOCKFILE, ast_log, AST_MIN_DTMF_DURATION, AST_OPT_FLAG_ALWAYS_FORK, AST_OPT_FLAG_CACHE_MEDIA_FRAMES, AST_OPT_FLAG_CACHE_RECORD_FILES, AST_OPT_FLAG_CONSOLE, AST_OPT_FLAG_DONT_WARN, AST_OPT_FLAG_DUMP_CORE, AST_OPT_FLAG_EXEC_INCLUDES, AST_OPT_FLAG_FORCE_BLACK_BACKGROUND, AST_OPT_FLAG_HIDE_CONSOLE_CONNECT, AST_OPT_FLAG_HIDE_MESSAGING_AMI_EVENTS, AST_OPT_FLAG_HIGH_PRIORITY, AST_OPT_FLAG_INIT_KEYS, AST_OPT_FLAG_LIGHT_BACKGROUND, AST_OPT_FLAG_LOCK_CONFIG_DIR, AST_OPT_FLAG_NO_COLOR, AST_OPT_FLAG_NO_FORK, AST_OPT_FLAG_QUIET, AST_OPT_FLAG_REF_DEBUG, AST_OPT_FLAG_STDEXTEN_MACRO, AST_OPT_FLAG_TIMESTAMP, AST_OPT_FLAG_TRANSCODE_VIA_SLIN, AST_OPT_FLAG_TRANSMIT_SILENCE, ast_opt_remote, ast_option_maxcalls, ast_option_maxfiles, ast_option_maxload, ast_option_rtpptdynamic, ast_option_rtpusedynamic, ast_parse_arg(), AST_RTP_PT_FIRST_DYNAMIC, ast_set2_flag, ast_set_default_eid(), ast_set_flag, ast_set_lock_type(), ast_str_to_eid(), ast_strlen_zero, ast_true(), ast_variable_browse(), _cfg_paths::cache_dir, _cfg_paths::config_dir, CONFIG_FLAG_NOREALTIME, CONFIG_STATUS_FILEINVALID, CONFIG_STATUS_FILEMISSING, CONFIG_STATUS_FILEUNCHANGED, _cfg_paths::ctl_file, _cfg_paths::ctl_group, _cfg_paths::ctl_owner, _cfg_paths::ctl_perms, _cfg_paths::data_dir, _cfg_paths::db_path, getloadavg(), hostname, _cfg_paths::key_dir, live_dangerously, _cfg_paths::log_dir, LOG_ERROR, LOG_WARNING, MAX_LANGUAGE, MAXHOSTNAMELEN, _cfg_paths::module_dir, _cfg_paths::monitor_dir, ast_variable::name, ast_variable::next, option_debug, option_dtmfminduration, option_minmemfree, option_trace, option_verbose, PARSE_IN_RANGE, PARSE_UINT32, pbx_live_dangerously(), _cfg_paths::pid_path, record_cache_dir, _cfg_paths::recording_dir, _cfg_paths::run_dir, _cfg_paths::run_group, _cfg_paths::run_user, _cfg_paths::sbin_dir, set_ulimit(), _cfg_paths::socket_path, _cfg_paths::spool_dir, _cfg_paths::system_name, ast_variable::value, and _cfg_paths::var_dir.
Referenced by main().
 {
    struct ast_config *cfg;
    struct ast_variable *v;
    char hostname[MAXHOSTNAMELEN] = "";
    struct ast_flags config_flags = { CONFIG_FLAG_NOREALTIME };
    struct {
       unsigned int dbdir:1;
       unsigned int keydir:1;
    } found = { 0, 0 };
    /* Default to false for security */
    int live_dangerously = 0;
    int option_debug_new = 0;
    int option_trace_new = 0;
    int option_verbose_new = 0;
    /* init with buildtime config */
 #ifdef REF_DEBUG
    /* The REF_DEBUG compiler flag is now only used to enable refdebug by default.
     * Support for debugging reference counts is always compiled in. */
    ast_set2_flag(&ast_options, 1, AST_OPT_FLAG_REF_DEBUG);
 #endif
    ast_set_default_eid(&ast_eid_default);
    cfg = ast_config_load2(ast_config_AST_CONFIG_FILE, "" /* core, can't reload */, config_flags);
    /* If AST_OPT_FLAG_EXEC_INCLUDES was previously enabled with -X turn it off now.
     * Using #exec from other configs requires that it be enabled from asterisk.conf. */
    ast_clear_flag(&ast_options, AST_OPT_FLAG_EXEC_INCLUDES);
    /* no asterisk.conf? no problem, use buildtime config! */
    if (cfg == CONFIG_STATUS_FILEMISSING || cfg == CONFIG_STATUS_FILEUNCHANGED || cfg == CONFIG_STATUS_FILEINVALID) {
       fprintf(stderr, "Unable to open specified master config file '%s', using built-in defaults\n", ast_config_AST_CONFIG_FILE);
       return;
    }
    for (v = ast_variable_browse(cfg, "files"); v; v = v->next) {
       if (!strcasecmp(v->name, "astctlpermissions")) {
          ast_copy_string(cfg_paths.ctl_perms, v->value, sizeof(cfg_paths.ctl_perms));
       } else if (!strcasecmp(v->name, "astctlowner")) {
          ast_copy_string(cfg_paths.ctl_owner, v->value, sizeof(cfg_paths.ctl_owner));
       } else if (!strcasecmp(v->name, "astctlgroup")) {
          ast_copy_string(cfg_paths.ctl_group, v->value, sizeof(cfg_paths.ctl_group));
       } else if (!strcasecmp(v->name, "astctl")) {
          ast_copy_string(cfg_paths.ctl_file, v->value, sizeof(cfg_paths.ctl_file));
       }
    }
    for (v = ast_variable_browse(cfg, "directories"); v; v = v->next) {
       if (!strcasecmp(v->name, "astcachedir")) {
          ast_copy_string(cfg_paths.cache_dir, v->value, sizeof(cfg_paths.cache_dir));
       } else if (!strcasecmp(v->name, "astetcdir")) {
          ast_copy_string(cfg_paths.config_dir, v->value, sizeof(cfg_paths.config_dir));
       } else if (!strcasecmp(v->name, "astspooldir")) {
          ast_copy_string(cfg_paths.spool_dir, v->value, sizeof(cfg_paths.spool_dir));
          snprintf(cfg_paths.monitor_dir, sizeof(cfg_paths.monitor_dir), "%s/monitor", v->value);
          snprintf(cfg_paths.recording_dir, sizeof(cfg_paths.recording_dir), "%s/recording", v->value);
       } else if (!strcasecmp(v->name, "astvarlibdir")) {
          ast_copy_string(cfg_paths.var_dir, v->value, sizeof(cfg_paths.var_dir));
          if (!found.dbdir) {
             snprintf(cfg_paths.db_path, sizeof(cfg_paths.db_path), "%s/astdb", v->value);
          }
       } else if (!strcasecmp(v->name, "astdbdir")) {
          snprintf(cfg_paths.db_path, sizeof(cfg_paths.db_path), "%s/astdb", v->value);
          found.dbdir = 1;
       } else if (!strcasecmp(v->name, "astdatadir")) {
          ast_copy_string(cfg_paths.data_dir, v->value, sizeof(cfg_paths.data_dir));
          if (!found.keydir) {
             snprintf(cfg_paths.key_dir, sizeof(cfg_paths.key_dir), "%s/keys", v->value);
          }
       } else if (!strcasecmp(v->name, "astkeydir")) {
          snprintf(cfg_paths.key_dir, sizeof(cfg_paths.key_dir), "%s/keys", v->value);
          found.keydir = 1;
       } else if (!strcasecmp(v->name, "astlogdir")) {
          ast_copy_string(cfg_paths.log_dir, v->value, sizeof(cfg_paths.log_dir));
       } else if (!strcasecmp(v->name, "astagidir")) {
          ast_copy_string(cfg_paths.agi_dir, v->value, sizeof(cfg_paths.agi_dir));
       } else if (!strcasecmp(v->name, "astrundir")) {
          snprintf(cfg_paths.pid_path, sizeof(cfg_paths.pid_path), "%s/%s", v->value, "asterisk.pid");
          ast_copy_string(cfg_paths.run_dir, v->value, sizeof(cfg_paths.run_dir));
       } else if (!strcasecmp(v->name, "astmoddir")) {
          ast_copy_string(cfg_paths.module_dir, v->value, sizeof(cfg_paths.module_dir));
       } else if (!strcasecmp(v->name, "astsbindir")) {
          ast_copy_string(cfg_paths.sbin_dir, v->value, sizeof(cfg_paths.sbin_dir));
       }
    }
    /* Combine astrundir and astctl settings. */
    snprintf(cfg_paths.socket_path, sizeof(cfg_paths.socket_path), "%s/%s",
       ast_config_AST_RUN_DIR, ast_config_AST_CTL);
    for (v = ast_variable_browse(cfg, "options"); v; v = v->next) {
       /* verbose level (-v at startup) */
       if (!strcasecmp(v->name, "verbose")) {
          option_verbose_new = atoi(v->value);
       /* whether or not to force timestamping in CLI verbose output. (-T at startup) */
       } else if (!strcasecmp(v->name, "timestamp")) {
          ast_set2_flag(&ast_options, ast_true(v->value), AST_OPT_FLAG_TIMESTAMP);
       /* whether or not to support #exec in config files */
       } else if (!strcasecmp(v->name, "execincludes")) {
          ast_set2_flag(&ast_options, ast_true(v->value), AST_OPT_FLAG_EXEC_INCLUDES);
       /* debug level (-d at startup) */
       } else if (!strcasecmp(v->name, "debug")) {
          option_debug_new = 0;
          if (sscanf(v->value, "%30d", &option_debug_new) != 1) {
             option_debug_new = ast_true(v->value) ? 1 : 0;
          }
       } else if (!strcasecmp(v->name, "trace")) {
          option_trace_new = 0;
          if (sscanf(v->value, "%30d", &option_trace_new) != 1) {
             option_trace_new = ast_true(v->value) ? 1 : 0;
          }
       } else if (!strcasecmp(v->name, "refdebug")) {
          ast_set2_flag(&ast_options, ast_true(v->value), AST_OPT_FLAG_REF_DEBUG);
 #if HAVE_WORKING_FORK
       /* Disable forking (-f at startup) */
       } else if (!strcasecmp(v->name, "nofork")) {
          ast_set2_flag(&ast_options, ast_true(v->value), AST_OPT_FLAG_NO_FORK);
       /* Always fork, even if verbose or debug are enabled (-F at startup) */
       } else if (!strcasecmp(v->name, "alwaysfork")) {
          ast_set2_flag(&ast_options, ast_true(v->value), AST_OPT_FLAG_ALWAYS_FORK);
 #endif
       /* Run quietly (-q at startup ) */
       } else if (!strcasecmp(v->name, "quiet")) {
          ast_set2_flag(&ast_options, ast_true(v->value), AST_OPT_FLAG_QUIET);
       /* Run as console (-c at startup, implies nofork) */
       } else if (!strcasecmp(v->name, "console")) {
          if (!ast_opt_remote) {
             ast_set2_flag(&ast_options, ast_true(v->value), AST_OPT_FLAG_NO_FORK | AST_OPT_FLAG_CONSOLE);
          }
       /* Run with high priority if the O/S permits (-p at startup) */
       } else if (!strcasecmp(v->name, "highpriority")) {
          ast_set2_flag(&ast_options, ast_true(v->value), AST_OPT_FLAG_HIGH_PRIORITY);
       /* Initialize RSA auth keys (IAX2) (-i at startup) */
       } else if (!strcasecmp(v->name, "initcrypto")) {
          ast_set2_flag(&ast_options, ast_true(v->value), AST_OPT_FLAG_INIT_KEYS);
       /* Disable ANSI colors for console (-c at startup) */
       } else if (!strcasecmp(v->name, "nocolor")) {
          ast_set2_flag(&ast_options, ast_true(v->value), AST_OPT_FLAG_NO_COLOR);
       /* Disable some usage warnings for picky people :p */
       } else if (!strcasecmp(v->name, "dontwarn")) {
          ast_set2_flag(&ast_options, ast_true(v->value), AST_OPT_FLAG_DONT_WARN);
       /* Dump core in case of crash (-g) */
       } else if (!strcasecmp(v->name, "dumpcore")) {
          ast_set2_flag(&ast_options, ast_true(v->value), AST_OPT_FLAG_DUMP_CORE);
       /* Cache recorded sound files to another directory during recording */
       } else if (!strcasecmp(v->name, "cache_record_files")) {
          ast_set2_flag(&ast_options, ast_true(v->value), AST_OPT_FLAG_CACHE_RECORD_FILES);
 #if !defined(LOW_MEMORY)
       /* Cache media frames for performance */
       } else if (!strcasecmp(v->name, "cache_media_frames")) {
          ast_set2_flag(&ast_options, ast_true(v->value), AST_OPT_FLAG_CACHE_MEDIA_FRAMES);
 #endif
       /* Specify cache directory */
       } else if (!strcasecmp(v->name, "record_cache_dir")) {
          ast_copy_string(record_cache_dir, v->value, AST_CACHE_DIR_LEN);
       /* Build transcode paths via SLINEAR, instead of directly */
       } else if (!strcasecmp(v->name, "transcode_via_sln")) {
          ast_set2_flag(&ast_options, ast_true(v->value), AST_OPT_FLAG_TRANSCODE_VIA_SLIN);
       /* Transmit SLINEAR silence while a channel is being recorded or DTMF is being generated on a channel */
       } else if (!strcasecmp(v->name, "transmit_silence_during_record") || !strcasecmp(v->name, "transmit_silence")) {
          ast_set2_flag(&ast_options, ast_true(v->value), AST_OPT_FLAG_TRANSMIT_SILENCE);
       } else if (!strcasecmp(v->name, "mindtmfduration")) {
          if (sscanf(v->value, "%30u", &option_dtmfminduration) != 1) {
             option_dtmfminduration = AST_MIN_DTMF_DURATION;
          }
       } else if (!strcasecmp(v->name, "rtp_use_dynamic")) {
          ast_option_rtpusedynamic = ast_true(v->value);
       /* http://www.iana.org/assignments/rtp-parameters
        * RTP dynamic payload types start at 96 normally; extend down to 0 */
       } else if (!strcasecmp(v->name, "rtp_pt_dynamic")) {
          ast_parse_arg(v->value, PARSE_UINT32|PARSE_IN_RANGE,
                        &ast_option_rtpptdynamic, 0, AST_RTP_PT_FIRST_DYNAMIC);
       } else if (!strcasecmp(v->name, "maxcalls")) {
          if ((sscanf(v->value, "%30d", &ast_option_maxcalls) != 1) || (ast_option_maxcalls < 0)) {
             ast_option_maxcalls = 0;
          }
       } else if (!strcasecmp(v->name, "maxload")) {
          double test[1];
          if (getloadavg(test, 1) == -1) {
             ast_log(LOG_ERROR, "Cannot obtain load average on this system. 'maxload' option disabled.\n");
             ast_option_maxload = 0.0;
          } else if ((sscanf(v->value, "%30lf", &ast_option_maxload) != 1) || (ast_option_maxload < 0.0)) {
             ast_option_maxload = 0.0;
          }
       /* Set the maximum amount of open files */
       } else if (!strcasecmp(v->name, "maxfiles")) {
          ast_option_maxfiles = atoi(v->value);
          if (!ast_opt_remote) {
             set_ulimit(ast_option_maxfiles);
          }
       /* What user to run as */
       } else if (!strcasecmp(v->name, "runuser")) {
          ast_copy_string(cfg_paths.run_user, v->value, sizeof(cfg_paths.run_user));
       /* What group to run as */
       } else if (!strcasecmp(v->name, "rungroup")) {
          ast_copy_string(cfg_paths.run_group, v->value, sizeof(cfg_paths.run_group));
       } else if (!strcasecmp(v->name, "systemname")) {
          ast_copy_string(cfg_paths.system_name, v->value, sizeof(cfg_paths.system_name));
       } else if (!strcasecmp(v->name, "autosystemname")) {
          if (ast_true(v->value)) {
             if (!gethostname(hostname, sizeof(hostname) - 1)) {
                ast_copy_string(cfg_paths.system_name, hostname, sizeof(cfg_paths.system_name));
             } else {
                if (ast_strlen_zero(ast_config_AST_SYSTEM_NAME)){
                   ast_copy_string(cfg_paths.system_name, "localhost", sizeof(cfg_paths.system_name));
                }
                ast_log(LOG_ERROR, "Cannot obtain hostname for this system.  Using '%s' instead.\n", ast_config_AST_SYSTEM_NAME);
             }
          }
       } else if (!strcasecmp(v->name, "languageprefix")) {
          ast_language_is_prefix = ast_true(v->value);
       } else if (!strcasecmp(v->name, "defaultlanguage")) {
          ast_copy_string(ast_defaultlanguage, v->value, MAX_LANGUAGE);
       } else if (!strcasecmp(v->name, "lockmode")) {
          if (!strcasecmp(v->value, "lockfile")) {
             ast_set_lock_type(AST_LOCK_TYPE_LOCKFILE);
          } else if (!strcasecmp(v->value, "flock")) {
             ast_set_lock_type(AST_LOCK_TYPE_FLOCK);
          } else {
             ast_log(LOG_WARNING, "'%s' is not a valid setting for the lockmode option, "
                "defaulting to 'lockfile'\n", v->value);
             ast_set_lock_type(AST_LOCK_TYPE_LOCKFILE);
          }
 #if defined(HAVE_SYSINFO)
       } else if (!strcasecmp(v->name, "minmemfree")) {
          /* specify the minimum amount of free memory to retain.  Asterisk should stop accepting new calls
           * if the amount of free memory falls below this watermark */
          if ((sscanf(v->value, "%30ld", &option_minmemfree) != 1) || (option_minmemfree < 0)) {
             option_minmemfree = 0;
          }
 #endif
       } else if (!strcasecmp(v->name, "entityid")) {
          struct ast_eid tmp_eid;
          if (!ast_str_to_eid(&tmp_eid, v->value)) {
             ast_eid_default = tmp_eid;
          } else {
             ast_log(LOG_WARNING, "Invalid Entity ID '%s' provided\n", v->value);
          }
       } else if (!strcasecmp(v->name, "lightbackground")) {
          ast_set2_flag(&ast_options, ast_true(v->value), AST_OPT_FLAG_LIGHT_BACKGROUND);
       } else if (!strcasecmp(v->name, "forceblackbackground")) {
          ast_set2_flag(&ast_options, ast_true(v->value), AST_OPT_FLAG_FORCE_BLACK_BACKGROUND);
       } else if (!strcasecmp(v->name, "hideconnect")) {
          ast_set2_flag(&ast_options, ast_true(v->value), AST_OPT_FLAG_HIDE_CONSOLE_CONNECT);
       } else if (!strcasecmp(v->name, "lockconfdir")) {
          ast_set2_flag(&ast_options, ast_true(v->value), AST_OPT_FLAG_LOCK_CONFIG_DIR);
       } else if (!strcasecmp(v->name, "stdexten")) {
          /* Choose how to invoke the extensions.conf stdexten */
          if (!strcasecmp(v->value, "gosub")) {
             ast_clear_flag(&ast_options, AST_OPT_FLAG_STDEXTEN_MACRO);
          } else if (!strcasecmp(v->value, "macro")) {
             ast_set_flag(&ast_options, AST_OPT_FLAG_STDEXTEN_MACRO);
          } else {
             ast_log(LOG_WARNING,
                "'%s' is not a valid setting for the stdexten option, defaulting to 'gosub'\n",
                v->value);
             ast_clear_flag(&ast_options, AST_OPT_FLAG_STDEXTEN_MACRO);
          }
       } else if (!strcasecmp(v->name, "live_dangerously")) {
          live_dangerously = ast_true(v->value);
       } else if (!strcasecmp(v->name, "hide_messaging_ami_events")) {
          ast_set2_flag(&ast_options, ast_true(v->value), AST_OPT_FLAG_HIDE_MESSAGING_AMI_EVENTS);
       }
    }
    if (!ast_opt_remote) {
       pbx_live_dangerously(live_dangerously);
    }
    option_debug += option_debug_new;
    option_trace += option_trace_new;
    option_verbose += option_verbose_new;
    ast_config_destroy(cfg);
 }
load_astmm_phase_1()
void load_astmm_phase_1 (void)
Initialize malloc debug phase 1.
Note
Must be called first thing after forking.
Returns
Nothing
Definition at line 1557 of file astmm.c.
Referenced by asterisk_daemon().
 {
 }
load_astmm_phase_2()
void load_astmm_phase_2 (void)
Initialize malloc debug phase 2.
Returns
Nothing
Definition at line 1561 of file astmm.c.
Referenced by asterisk_daemon().
 {
 }
load_modules()
int load_modules (void)
Provided by loader.c
Definition at line 2338 of file loader.c.
References AO2_ALLOC_OPT_LOCK_NOLOCK, ao2_container_alloc_list, ast_copy_string(), ast_debug, AST_DLLIST_LOCK, AST_DLLIST_TRAVERSE, AST_DLLIST_UNLOCK, ast_free, AST_LIST_HEAD_INIT_NOLOCK, AST_LIST_REMOVE_HEAD, AST_LIST_TRAVERSE, ast_log, AST_MODULE_SUPPORT_DEPRECATED, ast_str_append(), ast_str_buffer(), ast_str_create, ast_str_reset(), ast_str_strlen(), ast_strlen_zero, ast_tvdiff_us(), ast_tvnow(), AST_VECTOR_FREE, AST_VECTOR_GET, AST_VECTOR_INIT, AST_VECTOR_SIZE, ast_verb, ast_xml_find_element(), ast_xml_get_text(), ast_xml_node_get_children(), ast_xml_xpath_get_first_result(), ast_xml_xpath_results_free(), ast_xmldoc_query(), ast_module::declined, done, ast_module::flags, get_name_from_resource(), ast_module::info, load_resource_list(), loader_builtin_init(), loader_config_init(), LOG_ERROR, LOG_NOTICE, LOG_WARNING, NULL, order, ast_module::resource, load_order_entry::resource, ast_module::running, startup_errors, str, and ast_module_info::support_level.
Referenced by asterisk_daemon().
 {
    struct load_order_entry *order;
    unsigned int load_count;
    struct load_order load_order;
    int res = 0;
    int modulecount = 0;
    int i;
    struct ast_module *cur;
 #ifdef AST_XML_DOCS
    struct ast_str *warning_msg;
    char deprecated_in[33];
    char removed_in[33];
    char replacement[129];
 #endif
    struct timeval start_time = ast_tvnow();
    struct timeval end_time;
    int64_t usElapsed;
    ast_verb(1, "Asterisk Dynamic Loader Starting:\n");
 #if defined(HAVE_PERMANENT_DLOPEN)
    info_list = ao2_container_alloc_list(AO2_ALLOC_OPT_LOCK_NOLOCK, 0, NULL,
       info_list_obj_cmp_fn); /* must not be cleaned at shutdown */
    if (!info_list) {
       fprintf(stderr, "Module info list allocation failure.\n");
       return 1;
    }
 #endif
    AST_LIST_HEAD_INIT_NOLOCK(&load_order);
    AST_DLLIST_LOCK(&module_list);
    AST_VECTOR_INIT(&startup_errors, 0);
    startup_error_builder = ast_str_create(64);
    res = loader_builtin_init(&load_order);
    if (res) {
       goto done;
    }
    res = loader_config_init(&load_order);
    if (res) {
       goto done;
    }
    load_count = 0;
    AST_LIST_TRAVERSE(&load_order, order, entry)
       load_count++;
    if (load_count)
       ast_log(LOG_NOTICE, "%u modules will be loaded.\n", load_count);
    res = load_resource_list(&load_order, &modulecount);
    if (res == -1) {
       ast_log(LOG_WARNING, "Some non-required modules failed to load.\n");
       res = 0;
    }
 done:
    while ((order = AST_LIST_REMOVE_HEAD(&load_order, entry))) {
       ast_free(order->resource);
       ast_free(order);
    }
 #ifdef AST_XML_DOCS
    warning_msg = ast_str_create(512);
 #endif
    AST_DLLIST_TRAVERSE(&module_list, cur, entry) {
 #ifdef AST_XML_DOCS
       char *mod_name = NULL;
       struct ast_xml_xpath_results *results;
 #endif
       if (!cur->flags.running || cur->flags.declined) {
          continue;
       }
 #ifdef AST_XML_DOCS
       mod_name = get_name_from_resource(cur->resource);
       if (!warning_msg || !mod_name) {
          /* If we can't allocate memory, we have bigger issues */
          ast_free(mod_name);
          continue;
       }
       /* Clear out the previous values */
       deprecated_in[0] = removed_in[0] = replacement[0] = 0;
       results = ast_xmldoc_query("/docs/module[@name='%s']", mod_name);
       if (results) {
          struct ast_xml_node *deprecated_node, *removed_node, *replacement_node;
          struct ast_xml_node *metadata_nodes = ast_xml_node_get_children(ast_xml_xpath_get_first_result(results));
          deprecated_node = ast_xml_find_element(metadata_nodes, "deprecated_in", NULL, NULL);
          if (deprecated_node) {
             const char *result_tmp = ast_xml_get_text(deprecated_node);
             if (!ast_strlen_zero(result_tmp)) {
                ast_copy_string(deprecated_in, result_tmp, sizeof(deprecated_in));
             }
          }
          removed_node = ast_xml_find_element(metadata_nodes, "removed_in", NULL, NULL);
          if (removed_node) {
             const char *result_tmp = ast_xml_get_text(removed_node);
             if (!ast_strlen_zero(result_tmp)) {
                ast_copy_string(removed_in, result_tmp, sizeof(removed_in));
             }
          }
          replacement_node = ast_xml_find_element(metadata_nodes, "replacement", NULL, NULL);
          if (replacement_node) {
             const char *result_tmp = ast_xml_get_text(replacement_node);
             if (!ast_strlen_zero(result_tmp)) {
                ast_copy_string(replacement, result_tmp, sizeof(replacement));
             }
          }
          ast_xml_xpath_results_free(results);
       }
       ast_str_reset(warning_msg);
       if (cur->info->support_level == AST_MODULE_SUPPORT_DEPRECATED || !ast_strlen_zero(deprecated_in)
          || !ast_strlen_zero(removed_in) || !ast_strlen_zero(replacement)) {
          int already_butted = 0;
          ast_str_append(&warning_msg, -1, "Module '%s' has been loaded", mod_name);
          if (!ast_strlen_zero(deprecated_in)) {
             ast_str_append(&warning_msg, -1, " but %s deprecated in Asterisk version %s",
                 cur->info->support_level == AST_MODULE_SUPPORT_DEPRECATED ? "was" : "will be", deprecated_in);
             already_butted = 1;
          }
          if (!ast_strlen_zero(removed_in)) {
             ast_str_append(&warning_msg, -1, " %s will be removed in Asterisk version %s", already_butted ? "and" : "but", removed_in);
          } else {
             ast_str_append(&warning_msg, -1, " %s may be removed in a future release", already_butted ? "and" : "but");
          }
          ast_str_append(&warning_msg, -1, ".");
          if (!ast_strlen_zero(replacement)) {
             ast_str_append(&warning_msg, -1, " Its replacement is '%s'.", replacement);
          }
       }
       if (ast_str_strlen(warning_msg)) {
          ast_log(LOG_WARNING, "%s\n", ast_str_buffer(warning_msg));
       }
       ast_free(mod_name);
 #else
       if (cur->info->support_level == AST_MODULE_SUPPORT_DEPRECATED) {
          ast_log(LOG_WARNING, "The deprecated module '%s' has been loaded and is running, it may be removed in a future version\n", cur->resource);
       }
 #endif
    }
 #ifdef AST_XML_DOCS
    ast_free(warning_msg);
 #endif
    AST_DLLIST_UNLOCK(&module_list);
    for (i = 0; i < AST_VECTOR_SIZE(&startup_errors); i++) {
       char *str = AST_VECTOR_GET(&startup_errors, i);
       ast_log(LOG_ERROR, "%s", str);
       ast_free(str);
    }
    AST_VECTOR_FREE(&startup_errors);
    ast_free(startup_error_builder);
    startup_error_builder = NULL;
    end_time = ast_tvnow();
    usElapsed = ast_tvdiff_us(end_time, start_time);
 #ifdef AST_XML_DOCS
    ast_debug(1, "Loader time with AST_XML_DOCS: %ld.%06ld\n", usElapsed / 1000000, usElapsed % 1000000);
 #else
    ast_debug(1, "Loader time without AST_XML_DOCS: %ld.%06ld\n", usElapsed / 1000000, usElapsed % 1000000);
 #endif
    return res;
 }
load_pbx()
int load_pbx (void)
Provided by pbx.c
Definition at line 8460 of file pbx.c.
References __ast_custom_function_register(), action_extensionstatelist(), ARRAY_LEN, ast_cli_register_multiple, ast_device_state_message_type(), ast_device_state_topic_all(), ast_manager_register_xml_core, ast_presence_state_message_type(), ast_presence_state_topic_all(), ast_register_cleanup(), ast_verb, device_state_cb(), EVENT_FLAG_CALL, EVENT_FLAG_CONFIG, EVENT_FLAG_REPORTING, manager_show_dialplan(), NULL, presence_state_cb(), stasis_subscribe, stasis_subscription_accept_message_type(), STASIS_SUBSCRIPTION_FILTER_SELECTIVE, stasis_subscription_set_filter(), and unload_pbx().
Referenced by asterisk_daemon().
 {
    int res = 0;
    ast_register_cleanup(unload_pbx);
    /* Initialize the PBX */
    ast_verb(1, "Asterisk PBX Core Initializing\n");
    ast_verb(2, "Registering builtin functions:\n");
    ast_cli_register_multiple(pbx_cli, ARRAY_LEN(pbx_cli));
    __ast_custom_function_register(&exception_function, NULL);
    __ast_custom_function_register(&testtime_function, NULL);
    /* Register manager application */
    res |= ast_manager_register_xml_core("ShowDialPlan", EVENT_FLAG_CONFIG | EVENT_FLAG_REPORTING, manager_show_dialplan);
    res |= ast_manager_register_xml_core("ExtensionStateList", EVENT_FLAG_CALL | EVENT_FLAG_REPORTING, action_extensionstatelist);
    if (res) {
       return -1;
    }
    if (!(device_state_sub = stasis_subscribe(ast_device_state_topic_all(), device_state_cb, NULL))) {
       return -1;
    }
    stasis_subscription_accept_message_type(device_state_sub, ast_device_state_message_type());
    stasis_subscription_accept_message_type(device_state_sub, hint_change_message_type());
    stasis_subscription_accept_message_type(device_state_sub, hint_remove_message_type());
    stasis_subscription_set_filter(device_state_sub, STASIS_SUBSCRIPTION_FILTER_SELECTIVE);
    if (!(presence_state_sub = stasis_subscribe(ast_presence_state_topic_all(), presence_state_cb, NULL))) {
       return -1;
    }
    stasis_subscription_accept_message_type(presence_state_sub, ast_presence_state_message_type());
    stasis_subscription_set_filter(presence_state_sub, STASIS_SUBSCRIPTION_FILTER_SELECTIVE);
    return 0;
 }
load_pbx_app()
int load_pbx_app (void)
Provided by pbx_app.c
Definition at line 511 of file pbx_app.c.
References ARRAY_LEN, ast_cli_register_multiple, ast_register_cleanup(), and unload_pbx_app().
Referenced by asterisk_daemon().
 {
    ast_cli_register_multiple(app_cli, ARRAY_LEN(app_cli));
    ast_register_cleanup(unload_pbx_app);
    return 0;
 }
load_pbx_builtins()
int load_pbx_builtins (void)
Provided by pbx_builtins.c
Definition at line 1556 of file pbx_builtins.c.
References ARRAY_LEN, ast_log, ast_register_application2(), ast_register_cleanup(), builtins, pbx_builtin::execute, LOG_ERROR, pbx_builtin::name, NULL, unload_pbx_builtins(), and ast_channel::x.
Referenced by asterisk_daemon().
 {
    int x;
    /* Register builtin applications */
    for (x = 0; x < ARRAY_LEN(builtins); x++) {
       if (ast_register_application2(builtins[x].name, builtins[x].execute, NULL, NULL, NULL)) {
          ast_log(LOG_ERROR, "Unable to register builtin application '%s'\n", builtins[x].name);
          return -1;
       }
    }
    ast_register_cleanup(unload_pbx_builtins);
    return 0;
 }
load_pbx_functions_cli()
int load_pbx_functions_cli (void)
Provided by pbx_functions.c
Definition at line 732 of file pbx_functions.c.
References ARRAY_LEN, ast_cli_register_multiple, ast_register_cleanup(), and unload_pbx_functions_cli().
Referenced by asterisk_daemon().
 {
    ast_cli_register_multiple(acf_cli, ARRAY_LEN(acf_cli));
    ast_register_cleanup(unload_pbx_functions_cli);
    return 0;
 }
load_pbx_hangup_handler()
int load_pbx_hangup_handler (void)
Provided by pbx_hangup_handler.c
Definition at line 292 of file pbx_hangup_handler.c.
References ARRAY_LEN, ast_cli_register_multiple, ast_register_cleanup(), and unload_pbx_hangup_handler().
Referenced by asterisk_daemon().
 {
    ast_cli_register_multiple(cli, ARRAY_LEN(cli));
    ast_register_cleanup(unload_pbx_hangup_handler);
    return 0;
 }
load_pbx_switch()
int load_pbx_switch (void)
Provided by pbx_switch.c
Definition at line 125 of file pbx_switch.c.
References ARRAY_LEN, ast_cli_register_multiple, ast_register_cleanup(), and unload_pbx_switch().
Referenced by asterisk_daemon().
 {
    ast_cli_register_multiple(sw_cli, ARRAY_LEN(sw_cli));
    ast_register_cleanup(unload_pbx_switch);
    return 0;
 }
load_pbx_variables()
int load_pbx_variables (void)
Provided by pbx_variables.c
Definition at line 1216 of file pbx_variables.c.
References ARRAY_LEN, ast_cli_register_multiple, ast_register_application2(), ast_register_cleanup(), NULL, pbx_builtin_setvar(), pbx_builtin_setvar_multiple(), and unload_pbx_variables().
Referenced by asterisk_daemon().
 {
    int res = 0;
    res |= ast_cli_register_multiple(vars_cli, ARRAY_LEN(vars_cli));
    res |= ast_register_application2("Set", pbx_builtin_setvar, NULL, NULL, NULL);
    res |= ast_register_application2("MSet", pbx_builtin_setvar_multiple, NULL, NULL, NULL);
    ast_register_cleanup(unload_pbx_variables);
    return res;
 }
logger_queue_start()
void logger_queue_start (void)
Start the ast_queue_log() logger.
Provided by logger.c
Note
Called when the system is fully booted after startup so preloaded realtime modules can get up.
Returns
Nothing
Definition at line 1854 of file logger.c.
References ast_assert, ast_queue_log(), AST_RWLIST_UNLOCK, AST_RWLIST_WRLOCK, logger_initialized, logger_queue_init(), and queuelog_init.
Referenced by ast_queue_log(), and asterisk_daemon().
 {
    /* Must not be called before the logger is initialized. */
    ast_assert(logger_initialized);
    AST_RWLIST_WRLOCK(&logchannels);
    if (!queuelog_init) {
       logger_queue_init();
       queuelog_init = 1;
       AST_RWLIST_UNLOCK(&logchannels);
       ast_queue_log("NONE", "NONE", "NONE", "QUEUESTART", "%s", "");
    } else {
       AST_RWLIST_UNLOCK(&logchannels);
    }
 }
modules_shutdown()
int modules_shutdown (void)
Provided by loader.c
Note
Some resources, like timers, are started up dynamically, and thus may be still in use, even if all channels are dead. We must therefore check the usecount before asking modules to unload.
Definition at line 1182 of file loader.c.
References ast_debug, AST_DLLIST_EMPTY, AST_DLLIST_LOCK, AST_DLLIST_REMOVE_CURRENT, AST_DLLIST_TRAVERSE, AST_DLLIST_TRAVERSE_BACKWARDS_SAFE_BEGIN, AST_DLLIST_TRAVERSE_BACKWARDS_SAFE_END, AST_DLLIST_UNLOCK, ast_module_unref, ast_verb, ast_module::declined, ast_module::flags, ast_module::info, ast_module::keepuntilshutdown, module_destroy(), ast_module::resource, ast_module::running, ast_module_info::unload, and ast_module::usecount.
Referenced by really_quit().
 {
    struct ast_module *mod;
    int somethingchanged;
    int res;
    AST_DLLIST_LOCK(&module_list);
    /*!\note Some resources, like timers, are started up dynamically, and thus
     * may be still in use, even if all channels are dead.  We must therefore
     * check the usecount before asking modules to unload. */
    do {
       /* Reset flag before traversing the list */
       somethingchanged = 0;
       AST_DLLIST_TRAVERSE_BACKWARDS_SAFE_BEGIN(&module_list, mod, entry) {
          if (mod->usecount) {
             ast_debug(1, "Passing on %s: its use count is %d\n",
                mod->resource, mod->usecount);
             continue;
          }
          AST_DLLIST_REMOVE_CURRENT(entry);
          if (mod->flags.running && !mod->flags.declined && mod->info->unload) {
             ast_verb(1, "Unloading %s\n", mod->resource);
             mod->info->unload();
          }
          module_destroy(mod);
          somethingchanged = 1;
       }
       AST_DLLIST_TRAVERSE_BACKWARDS_SAFE_END;
       if (!somethingchanged) {
          AST_DLLIST_TRAVERSE(&module_list, mod, entry) {
             if (mod->flags.keepuntilshutdown) {
                ast_module_unref(mod);
                mod->flags.keepuntilshutdown = 0;
                somethingchanged = 1;
             }
          }
       }
    } while (somethingchanged);
    res = AST_DLLIST_EMPTY(&module_list);
    AST_DLLIST_UNLOCK(&module_list);
    return !res;
 }
set_asterisk_conf_path()
void set_asterisk_conf_path (const char * path)
Definition at line 200 of file options.c.
References ast_copy_string(), and _cfg_paths::config_file.
Referenced by main().
 {
    ast_copy_string(cfg_paths.config_file, path, sizeof(cfg_paths.config_file));
 }
set_socket_path()
void set_socket_path (const char * path)
Definition at line 205 of file options.c.
References ast_copy_string(), and _cfg_paths::socket_path.
Referenced by main().
 {
    ast_copy_string(cfg_paths.socket_path, path, sizeof(cfg_paths.socket_path));
 }
threadstorage_init()
void threadstorage_init (void)
Provided by threadstorage.c
Definition at line 35 of file threadstorage.c.
References a, ast_cli_args::argc, ast_cli_args::argv, ARRAY_LEN, ast_alloca, ast_calloc, ast_cli(), AST_CLI_DEFINE, ast_cli_register_multiple, ast_cli_unregister_multiple(), ast_free, AST_LIST_ENTRY, AST_LIST_HEAD_NOLOCK_STATIC, AST_LIST_INSERT_TAIL, AST_LIST_REMOVE_CURRENT, AST_LIST_TRAVERSE, AST_LIST_TRAVERSE_SAFE_BEGIN, AST_LIST_TRAVERSE_SAFE_END, ast_register_cleanup(), CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::command, ast_cli_args::fd, make_ari_stubs::file, len(), name, NULL, pthread_mutex_init, pthread_mutex_lock, pthread_mutex_t, pthread_mutex_unlock, thread, and ast_cli_entry::usage.
Referenced by asterisk_daemon().
 {
 }