Asterisk - The Open Source Telephony Project: func_cut.c File Reference
func_cut.c File Reference
Module: Dial plan functions
CUT function.
#include "asterisk.h"
#include "asterisk/file.h"
#include "asterisk/channel.h"
#include "asterisk/pbx.h"
#include "asterisk/module.h"
#include "asterisk/app.h"
Data Structures
struct sortable_keys
Macros
#define ERROR_NOARG (-1)
#define ERROR_NOMEM (-2)
#define ERROR_USAGE (-3)
Functions
static void __reg_module (void)
static void __unreg_module (void)
static int acf_cut_exec (struct ast_channel *chan, const char *cmd, char *data, char *buf, size_t len)
static int acf_cut_exec2 (struct ast_channel *chan, const char *cmd, char *data, struct ast_str **buf, ssize_t len)
static int acf_sort_exec (struct ast_channel *chan, const char *cmd, char *data, char *buf, size_t len)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int cut_internal (struct ast_channel *chan, char *data, struct ast_str **buf, ssize_t buflen)
static int load_module (void)
static int sort_internal (struct ast_channel *chan, char *data, char *buffer, size_t buflen)
static int sort_subroutine (const void *arg1, const void *arg2)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Cut out information from a string" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, }
static struct ast_custom_function acf_cut
static struct ast_custom_function acf_sort
static const struct ast_module_info * ast_module_info = &__mod_info
Detailed Description
CUT function.
Author
Tilghman Lesher app_c.nosp@m.ut__.nosp@m.v003@.nosp@m.the-.nosp@m.tilgh.nosp@m.man..nosp@m.com
Definition in file func_cut.c.
Macro Definition Documentation
ERROR_NOARG
#define ERROR_NOARG (-1)
Definition at line 98 of file func_cut.c.
Referenced by acf_cut_exec(), acf_cut_exec2(), acf_sort_exec(), cut_internal(), and sort_internal().
ERROR_NOMEM
#define ERROR_NOMEM (-2)
Definition at line 99 of file func_cut.c.
Referenced by acf_cut_exec(), acf_cut_exec2(), and acf_sort_exec().
ERROR_USAGE
#define ERROR_USAGE (-3)
Definition at line 100 of file func_cut.c.
Referenced by acf_cut_exec(), acf_cut_exec2(), and cut_internal().
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 337 of file func_cut.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 337 of file func_cut.c.
acf_cut_exec()
static int acf_cut_exec (struct ast_channel * chan, const char * cmd, char * data, char * buf, size_t len) static
Definition at line 256 of file func_cut.c.
References ast_copy_string(), ast_free, ast_log, ast_str_buffer(), ast_str_create, cut_internal(), ERROR_NOARG, ERROR_NOMEM, ERROR_USAGE, LOG_ERROR, and str.
 {
    int ret = -1;
    struct ast_str *str = ast_str_create(16);
    switch (cut_internal(chan, data, &str, len)) {
    case ERROR_NOARG:
       ast_log(LOG_ERROR, "Syntax: CUT(<varname>,<char-delim>,<range-spec>) - missing argument!\n");
       break;
    case ERROR_NOMEM:
       ast_log(LOG_ERROR, "Out of memory\n");
       break;
    case ERROR_USAGE:
       ast_log(LOG_ERROR, "Usage: CUT(<varname>,<char-delim>,<range-spec>)\n");
       break;
    case 0:
       ret = 0;
       ast_copy_string(buf, ast_str_buffer(str), len);
       break;
    default:
       ast_log(LOG_ERROR, "Unknown internal error\n");
    }
    ast_free(str);
    return ret;
 }
acf_cut_exec2()
static int acf_cut_exec2 (struct ast_channel * chan, const char * cmd, char * data, struct ast_str ** buf, ssize_t len) static
Definition at line 282 of file func_cut.c.
References ast_log, cut_internal(), ERROR_NOARG, ERROR_NOMEM, ERROR_USAGE, and LOG_ERROR.
 {
    int ret = -1;
    switch (cut_internal(chan, data, buf, len)) {
    case ERROR_NOARG:
       ast_log(LOG_ERROR, "Syntax: CUT(<varname>,<char-delim>,<range-spec>) - missing argument!\n");
       break;
    case ERROR_NOMEM:
       ast_log(LOG_ERROR, "Out of memory\n");
       break;
    case ERROR_USAGE:
       ast_log(LOG_ERROR, "Usage: CUT(<varname>,<char-delim>,<range-spec>)\n");
       break;
    case 0:
       ret = 0;
       break;
    default:
       ast_log(LOG_ERROR, "Unknown internal error\n");
    }
    return ret;
 }
acf_sort_exec()
static int acf_sort_exec (struct ast_channel * chan, const char * cmd, char * data, char * buf, size_t len) static
Definition at line 235 of file func_cut.c.
References ast_log, ERROR_NOARG, ERROR_NOMEM, LOG_ERROR, and sort_internal().
 {
    int ret = -1;
    switch (sort_internal(chan, data, buf, len)) {
    case ERROR_NOARG:
       ast_log(LOG_ERROR, "SORT() requires an argument\n");
       break;
    case ERROR_NOMEM:
       ast_log(LOG_ERROR, "Out of memory\n");
       break;
    case 0:
       ret = 0;
       break;
    default:
       ast_log(LOG_ERROR, "Unknown internal error\n");
    }
    return ret;
 }
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 337 of file func_cut.c.
cut_internal()
static int cut_internal (struct ast_channel * chan, char * data, struct ast_str ** buf, ssize_t buflen) static
Definition at line 153 of file func_cut.c.
References args, ast_alloca, AST_APP_ARG, ast_copy_string(), AST_DECLARE_APP_ARGS, ast_free, ast_get_encoded_char(), ast_log, AST_STANDARD_APP_ARGS, ast_str_append(), ast_str_buffer(), ast_str_create, ast_str_strlen(), ast_str_substitute_variables(), ast_strdupa, ERROR_NOARG, ERROR_USAGE, LOG_WARNING, NULL, parse(), and strsep().
Referenced by acf_cut_exec(), and acf_cut_exec2().
 {
    char *parse, ds[2], *var_expr;
    size_t delim_consumed;
    struct ast_str *var_value;
    AST_DECLARE_APP_ARGS(args,
       AST_APP_ARG(varname);
       AST_APP_ARG(delimiter);
       AST_APP_ARG(field);
    );
    parse = ast_strdupa(data);
    AST_STANDARD_APP_ARGS(args, parse);
    /* Check arguments */
    if (args.argc < 3) {
       return ERROR_NOARG;
    }
    var_expr = ast_alloca(strlen(args.varname) + 4);
    /* Get the value of the variable named in the 1st argument */
    snprintf(var_expr, strlen(args.varname) + 4, "${%s}", args.varname);
    var_value = ast_str_create(16);
    ast_str_substitute_variables(&var_value, 0, chan, var_expr);
    /* Copy delimiter from 2nd argument to ds[] possibly decoding backslash escapes */
    if (ast_get_encoded_char(args.delimiter, ds, &delim_consumed)) {
       ast_copy_string(ds, "-", sizeof(ds));
    }
    ds[1] = '\0';
    if (ast_str_strlen(var_value)) {
       int curfieldnum = 1;
       char *curfieldptr = ast_str_buffer(var_value);
       int out_field_count = 0;
       while (curfieldptr != NULL && args.field != NULL) {
          char *next_range = strsep(&(args.field), "&");
          int start_field, stop_field;
          char trashchar;
          if (sscanf(next_range, "%30d-%30d", &start_field, &stop_field) == 2) {
             /* range with both start and end */
          } else if (sscanf(next_range, "-%30d", &stop_field) == 1) {
             /* range with end only */
             start_field = 1;
          } else if ((sscanf(next_range, "%30d%1c", &start_field, &trashchar) == 2) && (trashchar == '-')) {
             /* range with start only */
             stop_field = INT_MAX;
          } else if (sscanf(next_range, "%30d", &start_field) == 1) {
             /* single number */
             stop_field = start_field;
          } else {
             /* invalid field spec */
             ast_free(var_value);
             return ERROR_USAGE;
          }
          /* Get to start, if not there already */
          while (curfieldptr != NULL && curfieldnum < start_field) {
             strsep(&curfieldptr, ds);
             curfieldnum++;
          }
          /* Most frequent problem is the expectation of reordering fields */
          if (curfieldnum > start_field) {
             ast_log(LOG_WARNING, "We're already past the field you wanted?\n");
          }
          /* Output fields until we either run out of fields or stop_field is reached */
          while (curfieldptr != NULL && curfieldnum <= stop_field) {
             char *field_value = strsep(&curfieldptr, ds);
             ast_str_append(buf, buflen, "%s%s", out_field_count++ ? ds : "", field_value);
             curfieldnum++;
          }
       }
    }
    ast_free(var_value);
    return 0;
 }
load_module()
static int load_module (void) static
Definition at line 327 of file func_cut.c.
References ast_custom_function_register.
 {
    int res = 0;
    res |= ast_custom_function_register(&acf_cut);
    res |= ast_custom_function_register(&acf_sort);
    return res;
 }
sort_internal()
static int sort_internal (struct ast_channel * chan, char * data, char * buffer, size_t buflen) static
Definition at line 102 of file func_cut.c.
References ast_alloca, ast_strdupa, ERROR_NOARG, sortable_keys::key, sort_subroutine(), strsep(), and sortable_keys::value.
Referenced by acf_sort_exec().
 {
    char *strings, *ptrkey, *ptrvalue;
    int count=1, count2, element_count=0;
    struct sortable_keys *sortable_keys;
    *buffer = '\0';
    if (!data)
       return ERROR_NOARG;
    strings = ast_strdupa(data);
    for (ptrkey = strings; *ptrkey; ptrkey++) {
       if (*ptrkey == ',')
          count++;
    }
    sortable_keys = ast_alloca(count * sizeof(struct sortable_keys));
    memset(sortable_keys, 0, count * sizeof(struct sortable_keys));
    /* Parse each into a struct */
    count2 = 0;
    while ((ptrkey = strsep(&strings, ","))) {
       ptrvalue = strchr(ptrkey, ':');
       if (!ptrvalue) {
          count--;
          continue;
       }
       *ptrvalue++ = '\0';
       sortable_keys[count2].key = ptrkey;
       sscanf(ptrvalue, "%30f", &sortable_keys[count2].value);
       count2++;
    }
    /* Sort the structs */
    qsort(sortable_keys, count, sizeof(struct sortable_keys), sort_subroutine);
    for (count2 = 0; count2 < count; count2++) {
       int blen = strlen(buffer);
       if (element_count++) {
          strncat(buffer + blen, ",", buflen - blen - 1);
          blen++;
       }
       strncat(buffer + blen, sortable_keys[count2].key, buflen - blen - 1);
    }
    return 0;
 }
sort_subroutine()
static int sort_subroutine (const void * arg1, const void * arg2) static
Definition at line 87 of file func_cut.c.
References sortable_keys::value.
Referenced by sort_internal().
 {
    const struct sortable_keys *one=arg1, *two=arg2;
    if (one->value < two->value)
       return -1;
    else if (one->value == two->value)
       return 0;
    else
       return 1;
 }
unload_module()
static int unload_module (void) static
Definition at line 317 of file func_cut.c.
References ast_custom_function_unregister().
 {
    int res = 0;
    res |= ast_custom_function_unregister(&acf_cut);
    res |= ast_custom_function_unregister(&acf_sort);
    return res;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Cut out information from a string" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, } static
Definition at line 337 of file func_cut.c.
acf_cut
struct ast_custom_function acf_cut static
Initial value:
= {
   .name = "CUT",
   .read = acf_cut_exec,
   .read2 = acf_cut_exec2,
}
Definition at line 311 of file func_cut.c.
acf_sort
struct ast_custom_function acf_sort static
Initial value:
= {
   .name = "SORT",
   .read = acf_sort_exec,
}
Definition at line 306 of file func_cut.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 337 of file func_cut.c.