Asterisk - The Open Source Telephony Project: func_blacklist.c File Reference
func_blacklist.c File Reference
Module: Dial plan functions
Function to lookup the callerid number, and see if it is blacklisted.
#include "asterisk.h"
#include "asterisk/pbx.h"
#include "asterisk/module.h"
#include "asterisk/channel.h"
#include "asterisk/astdb.h"
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int blacklist_read (struct ast_channel *chan, const char *cmd, char *data, char *buf, size_t len)
static int blacklist_read2 (struct ast_channel *chan, const char *cmd, char *data, struct ast_str **str, ssize_t len)
static int load_module (void)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Look up Caller*ID name/number from blacklist database" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, }
static const struct ast_module_info * ast_module_info = &__mod_info
static struct ast_custom_function blacklist_function
Detailed Description
Function to lookup the callerid number, and see if it is blacklisted.
Author
Mark Spencer marks.nosp@m.ter@.nosp@m.digiu.nosp@m.m.co.nosp@m.m
Definition in file func_blacklist.c.
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 112 of file func_blacklist.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 112 of file func_blacklist.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 112 of file func_blacklist.c.
blacklist_read()
static int blacklist_read (struct ast_channel * chan, const char * cmd, char * data, char * buf, size_t len) static
Definition at line 57 of file func_blacklist.c.
References ast_channel_caller(), ast_db_get(), ast_log, LOG_WARNING, and name.
Referenced by blacklist_read2().
 {
    char blacklist[1];
    int bl = 0;
    if (!chan) {
       ast_log(LOG_WARNING, "No channel was provided to %s function.\n", cmd);
       return -1;
    }
    if (ast_channel_caller(chan)->id.number.valid && ast_channel_caller(chan)->id.number.str) {
       if (!ast_db_get("blacklist", ast_channel_caller(chan)->id.number.str, blacklist, sizeof (blacklist)))
          bl = 1;
    }
    if (ast_channel_caller(chan)->id.name.valid && ast_channel_caller(chan)->id.name.str) {
       if (!ast_db_get("blacklist", ast_channel_caller(chan)->id.name.str, blacklist, sizeof (blacklist)))
          bl = 1;
    }
    snprintf(buf, len, "%d", bl);
    return 0;
 }
blacklist_read2()
static int blacklist_read2 (struct ast_channel * chan, const char * cmd, char * data, struct ast_str ** str, ssize_t len) static
Definition at line 80 of file func_blacklist.c.
References ast_str_buffer(), ast_str_make_space, ast_str_size(), ast_str_strlen(), ast_str_update(), and blacklist_read().
 {
    /* 2 bytes is a single integer, plus terminating null */
    if (ast_str_size(*str) - ast_str_strlen(*str) < 2) {
       if (len > ast_str_size(*str) || len == 0) {
          ast_str_make_space(str, len ? len : ast_str_strlen(*str) + 2);
       }
    }
    if (ast_str_size(*str) - ast_str_strlen(*str) >= 2) {
       int res = blacklist_read(chan, cmd, data, ast_str_buffer(*str) + ast_str_strlen(*str), 2);
       ast_str_update(*str);
       return res;
    }
    return -1;
 }
load_module()
static int load_module (void) static
Definition at line 107 of file func_blacklist.c.
References ast_custom_function_register.
 {
    return ast_custom_function_register(&blacklist_function);
 }
unload_module()
static int unload_module (void) static
Definition at line 102 of file func_blacklist.c.
References ast_custom_function_unregister().
 {
    return ast_custom_function_unregister(&blacklist_function);
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Look up Caller*ID name/number from blacklist database" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, } static
Definition at line 112 of file func_blacklist.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 112 of file func_blacklist.c.
blacklist_function
struct ast_custom_function blacklist_function static
Initial value:
= {
   .name = "BLACKLIST",
   .read = blacklist_read,
   .read2 = blacklist_read2,
}
Definition at line 96 of file func_blacklist.c.