Asterisk - The Open Source Telephony Project: func_shell.c File Reference
func_shell.c File Reference
Module: Dial plan functions
#include "asterisk.h"
#include "asterisk/module.h"
#include "asterisk/channel.h"
#include "asterisk/pbx.h"
#include "asterisk/utils.h"
#include "asterisk/app.h"
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int load_module (void)
static int shell_helper (struct ast_channel *chan, const char *cmd, char *data, char *buf, size_t len)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Collects the output generated by a command executed by the system shell" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, }
static const struct ast_module_info * ast_module_info = &__mod_info
static struct ast_custom_function shell_function
Detailed Description
SHELL function to return the output generated by a command issued to the system shell.
Note
Inspiration and Guidance from Russell! Thank You!
Author
Brandon Kruse bkrus.nosp@m.e@di.nosp@m.gium..nosp@m.com
Definition in file func_shell.c.
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 124 of file func_shell.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 124 of file func_shell.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 124 of file func_shell.c.
load_module()
static int load_module (void) static
Definition at line 119 of file func_shell.c.
References AST_CFE_READ, and ast_custom_function_register_escalating.
 {
    return ast_custom_function_register_escalating(&shell_function, AST_CFE_READ);
 }
shell_helper()
static int shell_helper (struct ast_channel * chan, const char * cmd, char * data, char * buf, size_t len) static
Definition at line 40 of file func_shell.c.
References ast_autoservice_start(), ast_autoservice_stop(), ast_log, ast_strlen_zero, and LOG_WARNING.
 {
    int res = 0;
    if (ast_strlen_zero(data)) {
       ast_log(LOG_WARNING, "Missing Argument!  Example:  Set(foo=${SHELL(echo \"bar\")})\n");
       return -1;
    }
    if (chan) {
       ast_autoservice_start(chan);
    }
    if (len >= 1) {
       FILE *ptr;
       char plbuff[4096];
       ptr = popen(data, "r");
       if (ptr) {
          while (fgets(plbuff, sizeof(plbuff), ptr)) {
             strncat(buf, plbuff, len - strlen(buf) - 1);
          }
          pclose(ptr);
       } else {
          ast_log(LOG_WARNING, "Failed to execute shell command '%s'\n", data);
          res = -1;
       }
    }
    if (chan) {
       ast_autoservice_stop(chan);
    }
    return res;
 }
unload_module()
static int unload_module (void) static
Definition at line 114 of file func_shell.c.
References ast_custom_function_unregister().
 {
    return ast_custom_function_unregister(&shell_function);
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Collects the output generated by a command executed by the system shell" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, } static
Definition at line 124 of file func_shell.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 124 of file func_shell.c.
shell_function
struct ast_custom_function shell_function static
Initial value:
= {
   .name = "SHELL",
   .read = shell_helper,
}
Definition at line 109 of file func_shell.c.