Asterisk - The Open Source Telephony Project: stasis_bridge.h File Reference
stasis_bridge.h File Reference
Internal API for the Stasis bridge subclass.
Macros
#define STASIS_BRIDGE_MIXING_CAPABILITIES
Functions
void bridge_stasis_init (void)
struct ast_bridge * bridge_stasis_new (uint32_t capabilities, unsigned int flags, const char *name, const char *id, enum ast_bridge_video_mode_type video_mode)
Detailed Description
Internal API for the Stasis bridge subclass.
Author
Richard Mudgett rmudg.nosp@m.ett@.nosp@m.digiu.nosp@m.m.co.nosp@m.m
See Also:
CREDITS
Definition in file stasis_bridge.h.
Macro Definition Documentation
STASIS_BRIDGE_MIXING_CAPABILITIES
#define STASIS_BRIDGE_MIXING_CAPABILITIES
Value:
(AST_BRIDGE_CAPABILITY_NATIVE \
   | AST_BRIDGE_CAPABILITY_1TO1MIX \
   | AST_BRIDGE_CAPABILITY_MULTIMIX)
Normal capabilities of mixing bridges
Definition at line 39 of file stasis_bridge.h.
Referenced by bridge_create_common(), bridge_stasis_pull(), and bridge_stasis_push().
Function Documentation
bridge_stasis_init()
void bridge_stasis_init (void)
Definition at line 327 of file stasis_bridge.c.
References ast_bridge_base_v_table, bridge_stasis_pull(), bridge_stasis_push(), bridge_stasis_push_peek(), bridge_stasis_v_table, ast_bridge_methods::name, ast_bridge_methods::pull, ast_bridge_methods::push, and ast_bridge_methods::push_peek.
Referenced by load_module().
 {
    /* Setup the Stasis bridge subclass v_table. */
    bridge_stasis_v_table = ast_bridge_base_v_table;
    bridge_stasis_v_table.name = "stasis";
    bridge_stasis_v_table.push = bridge_stasis_push;
    bridge_stasis_v_table.pull = bridge_stasis_pull;
    bridge_stasis_v_table.push_peek = bridge_stasis_push_peek;
 }
bridge_stasis_new()
struct ast_bridge* bridge_stasis_new (uint32_t capabilities, unsigned int flags, const char * name, const char * id, enum ast_bridge_video_mode_type video_mode)
Definition at line 300 of file stasis_bridge.c.
References ast_bridge_set_sfu_video_mode(), ast_bridge_set_single_src_video_mode(), ast_bridge_set_talker_src_video_mode(), ast_bridge_set_video_update_discard(), AST_BRIDGE_VIDEO_MODE_SFU, AST_BRIDGE_VIDEO_MODE_SINGLE_SRC, defer_bridge_add_obj::bridge, bridge_alloc(), bridge_base_init(), bridge_register(), bridge_stasis_v_table, and NULL.
Referenced by bridge_create_common().
 {
    void *bridge;
    bridge = bridge_alloc(sizeof(struct ast_bridge), &bridge_stasis_v_table);
    bridge = bridge_base_init(bridge, capabilities, flags, "Stasis", name, id);
    if (!bridge) {
       return NULL;
    }
    if (video_mode == AST_BRIDGE_VIDEO_MODE_SFU) {
       ast_bridge_set_sfu_video_mode(bridge);
       /* We require a minimum 5 seconds between video updates to stop floods from clients,
        * this should rarely be changed but should become configurable in the future.
        */
       ast_bridge_set_video_update_discard(bridge, 5);
    } else if (video_mode == AST_BRIDGE_VIDEO_MODE_SINGLE_SRC) {
       ast_bridge_set_single_src_video_mode(bridge, NULL);
    } else {
       ast_bridge_set_talker_src_video_mode(bridge);
    }
    bridge = bridge_register(bridge);
    return bridge;
 }