Asterisk - The Open Source Telephony Project: app_waituntil.c File Reference
app_waituntil.c File Reference
Dial plan applications
Sleep until the given epoch.
#include "asterisk.h"
#include "asterisk/logger.h"
#include "asterisk/channel.h"
#include "asterisk/pbx.h"
#include "asterisk/module.h"
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int load_module (void)
static int unload_module (void)
static int waituntil_exec (struct ast_channel *chan, const char *data)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Wait until specified time" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, }
static char * app = "WaitUntil"
static const struct ast_module_info * ast_module_info = &__mod_info
Detailed Description
Sleep until the given epoch.
Author
Philip Prindeville phili.nosp@m.pp@r.nosp@m.edfis.nosp@m.h-so.nosp@m.lutio.nosp@m.ns.c.nosp@m.om
Definition in file app_waituntil.c.
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 120 of file app_waituntil.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 120 of file app_waituntil.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 120 of file app_waituntil.c.
load_module()
static int load_module (void) static
Definition at line 115 of file app_waituntil.c.
References app, ast_register_application_xml, and waituntil_exec().
 {
    return ast_register_application_xml(app, waituntil_exec);
 }
unload_module()
static int unload_module (void) static
Definition at line 110 of file app_waituntil.c.
References app, and ast_unregister_application().
 {
    return ast_unregister_application(app);
 }
waituntil_exec()
static int waituntil_exec (struct ast_channel * chan, const char * data) static
Definition at line 72 of file app_waituntil.c.
References ast_log, ast_safe_sleep(), ast_strlen_zero, ast_tvdiff_ms(), ast_tvnow(), LOG_NOTICE, LOG_WARNING, and pbx_builtin_setvar_helper().
Referenced by load_module().
 {
    int res;
    double fraction;
    long seconds;
    struct timeval future = { 0, };
    struct timeval now = ast_tvnow();
    int msec;
    if (ast_strlen_zero(data)) {
       ast_log(LOG_WARNING, "WaitUntil requires an argument(epoch)\n");
       pbx_builtin_setvar_helper(chan, "WAITUNTILSTATUS", "FAILURE");
       return 0;
    }
    if (sscanf(data, "%30ld%30lf", &seconds, &fraction) == 0) {
       ast_log(LOG_WARNING, "WaitUntil called with non-numeric argument\n");
       pbx_builtin_setvar_helper(chan, "WAITUNTILSTATUS", "FAILURE");
       return 0;
    }
    future.tv_sec = seconds;
    future.tv_usec = fraction * 1000000;
    if ((msec = ast_tvdiff_ms(future, now)) < 0) {
       ast_log(LOG_NOTICE, "WaitUntil called in the past (now %ld, arg %ld)\n", (long)now.tv_sec, (long)future.tv_sec);
       pbx_builtin_setvar_helper(chan, "WAITUNTILSTATUS", "PAST");
       return 0;
    }
    if ((res = ast_safe_sleep(chan, msec)))
       pbx_builtin_setvar_helper(chan, "WAITUNTILSTATUS", "HANGUP");
    else
       pbx_builtin_setvar_helper(chan, "WAITUNTILSTATUS", "OK");
    return res;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Wait until specified time" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, } static
Definition at line 120 of file app_waituntil.c.
app
char* app = "WaitUntil" static
Definition at line 70 of file app_waituntil.c.
Referenced by load_module(), and unload_module().
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 120 of file app_waituntil.c.