Asterisk - The Open Source Telephony Project: autochan.c File Reference
autochan.c File Reference
"smart" channels
#include "asterisk.h"
#include "asterisk/autochan.h"
#include "asterisk/utils.h"
#include "asterisk/linkedlists.h"
#include "asterisk/options.h"
#include "asterisk/channel.h"
Functions
void ast_autochan_destroy (struct ast_autochan *autochan)
destroy an ast_autochan structure
void ast_autochan_new_channel (struct ast_channel *old_chan, struct ast_channel *new_chan)
Switch what channel autochans point to.
struct ast_autochan * ast_autochan_setup (struct ast_channel *chan)
set up a new ast_autochan structure
Detailed Description
"smart" channels
Author
Mark Michelson mmich.nosp@m.elso.nosp@m.n@dig.nosp@m.ium..nosp@m.com
Definition in file autochan.c.
Function Documentation
ast_autochan_destroy()
void ast_autochan_destroy (struct ast_autochan * autochan)
destroy an ast_autochan structure
Removes the passed-in autochan from the list of autochans and unrefs the channel that is pointed to. Also frees the autochan struct itself. This function will unref the channel reference which was made in ast_autochan_setup
Parameters
autochan The autochan that you wish to destroy
Return values
void
Definition at line 64 of file autochan.c.
References ast_autochan_channel_lock, ast_autochan_channel_unlock, ast_channel_autochans(), ast_channel_unref, ast_debug, ast_free, AST_LIST_REMOVE_CURRENT, AST_LIST_TRAVERSE_SAFE_BEGIN, AST_LIST_TRAVERSE_SAFE_END, ast_mutex_destroy, ast_autochan::chan, ast_autochan::list, and ast_autochan::lock.
Referenced by channel_spy(), common_exec(), launch_monitor_thread(), and mixmonitor_thread().
 {
    struct ast_autochan *autochan_iter;
    ast_autochan_channel_lock(autochan);
    AST_LIST_TRAVERSE_SAFE_BEGIN(ast_channel_autochans(autochan->chan), autochan_iter, list) {
       if (autochan_iter == autochan) {
          AST_LIST_REMOVE_CURRENT(list);
          ast_debug(1, "Removed autochan %p from the list, about to free it\n", autochan);
          break;
       }
    }
    AST_LIST_TRAVERSE_SAFE_END;
    ast_autochan_channel_unlock(autochan);
    autochan->chan = ast_channel_unref(autochan->chan);
    ast_mutex_destroy(&autochan->lock);
    ast_free(autochan);
 }
ast_autochan_new_channel()
void ast_autochan_new_channel (struct ast_channel * old_chan, struct ast_channel * new_chan)
Switch what channel autochans point to.
Traverses the list of autochans. All autochans which point to old_chan will be updated to point to new_chan instead. Currently this is only called during an ast_channel_move() operation in channel.c.
Precondition
Both channels must be locked before calling this function.
Parameters
old_chan The channel that autochans may currently point to
new_chan The channel that we want to point those autochans to now
Return values
void
Definition at line 86 of file autochan.c.
References ast_channel_autochans(), ast_channel_name(), ast_channel_ref, ast_channel_unref, ast_debug, AST_LIST_APPEND_LIST, AST_LIST_TRAVERSE, ast_mutex_lock, ast_mutex_unlock, ast_autochan::chan, ast_autochan::list, and ast_autochan::lock.
Referenced by channel_do_masquerade().
 {
    struct ast_autochan *autochan;
    AST_LIST_APPEND_LIST(ast_channel_autochans(new_chan), ast_channel_autochans(old_chan), list);
    /* Deadlock avoidance is not needed since the channels are already locked. */
    AST_LIST_TRAVERSE(ast_channel_autochans(new_chan), autochan, list) {
       ast_mutex_lock(&autochan->lock);
       if (autochan->chan == old_chan) {
          autochan->chan = ast_channel_ref(new_chan);
          ast_channel_unref(old_chan);
          ast_debug(1, "Autochan %p used to hold channel %s (%p) but now holds channel %s (%p)\n",
                autochan, ast_channel_name(old_chan), old_chan, ast_channel_name(new_chan), new_chan);
       }
       ast_mutex_unlock(&autochan->lock);
    }
 }
ast_autochan_setup()
struct ast_autochan* ast_autochan_setup (struct ast_channel * chan)
set up a new ast_autochan structure
Allocates and initializes an ast_autochan, sets the autochan's chan pointer to point to the chan parameter, and adds the autochan to the global list of autochans. The newly- created autochan is returned to the caller. This function will cause the refcount of chan to increase by 1.
Parameters
chan The channel our new autochan will point to
Note
autochans must be freed using ast_autochan_destroy
Return values
NULL Failure
non-NULL success
Definition at line 38 of file autochan.c.
References ast_calloc, ast_channel_autochans(), ast_channel_lock, ast_channel_name(), ast_channel_ref, ast_channel_unlock, ast_debug, AST_LIST_INSERT_TAIL, ast_mutex_init, ast_autochan::chan, ast_autochan::list, ast_autochan::lock, and NULL.
Referenced by attach_barge(), common_exec(), launch_monitor_thread(), and next_channel().
 {
    struct ast_autochan *autochan;
    if (!chan) {
       return NULL;
    }
    if (!(autochan = ast_calloc(1, sizeof(*autochan)))) {
       return NULL;
    }
    ast_mutex_init(&autochan->lock);
    autochan->chan = ast_channel_ref(chan);
    ast_debug(1, "Created autochan %p to hold channel %s (%p)\n",
       autochan, ast_channel_name(chan), chan);
    /* autochan is still private, no need for ast_autochan_channel_lock() */
    ast_channel_lock(autochan->chan);
    AST_LIST_INSERT_TAIL(ast_channel_autochans(autochan->chan), autochan, list);
    ast_channel_unlock(autochan->chan);
    return autochan;
 }