Asterisk - The Open Source Telephony Project: res_ari_sounds.c File Reference
res_ari_sounds.c File Reference
Sound resources.
#include "asterisk.h"
#include "asterisk/app.h"
#include "asterisk/module.h"
#include "asterisk/stasis_app.h"
#include "ari/resource_sounds.h"
#include "ari/ari_model_validators.h"
Macros
#define MAX_VALS 128
Functions
static void __reg_module (void)
static void __unreg_module (void)
static void ast_ari_sounds_get_cb (struct ast_tcptls_session_instance *ser, struct ast_variable *get_params, struct ast_variable *path_vars, struct ast_variable *headers, struct ast_json *body, struct ast_ari_response *response)
Parameter parsing callback for /sounds/{soundId}.
static void ast_ari_sounds_list_cb (struct ast_tcptls_session_instance *ser, struct ast_variable *get_params, struct ast_variable *path_vars, struct ast_variable *headers, struct ast_json *body, struct ast_ari_response *response)
Parameter parsing callback for /sounds.
int ast_ari_sounds_list_parse_body (struct ast_json *body, struct ast_ari_sounds_list_args *args)
Body parsing function for /sounds.
struct ast_module * AST_MODULE_SELF_SYM (void)
static int load_module (void)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_DEFAULT , .description = "RESTful API module - Sound resources" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .requires = "res_ari,res_ari_model,res_stasis", }
static const struct ast_module_info * ast_module_info = &__mod_info
static struct stasis_rest_handlers sounds
REST handler for /api-docs/sounds.json.
static struct stasis_rest_handlers sounds_soundId
REST handler for /api-docs/sounds.json.
Detailed Description
Sound resources.
Author
David M. Lee, II dlee@.nosp@m.digi.nosp@m.um.co.nosp@m.m
Definition in file res_ari_sounds.c.
Macro Definition Documentation
MAX_VALS
#define MAX_VALS 128
Definition at line 51 of file res_ari_sounds.c.
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 237 of file res_ari_sounds.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 237 of file res_ari_sounds.c.
ast_ari_sounds_get_cb()
static void ast_ari_sounds_get_cb (struct ast_tcptls_session_instance * ser, struct ast_variable * get_params, struct ast_variable * path_vars, struct ast_variable * headers, struct ast_json * body, struct ast_ari_response * response) static
Parameter parsing callback for /sounds/{soundId}.
Parameters
get_params GET parameters in the HTTP request.
path_vars Path variables extracted from the request.
headers HTTP headers.
[out] response Response to the HTTP request.
Definition at line 141 of file res_ari_sounds.c.
References ast_ari_response_error(), ast_ari_sounds_get(), ast_ari_validate_sound(), ast_log, LOG_ERROR, ast_ari_response::message, ast_variable::name, ast_variable::next, NULL, ast_ari_response::response_code, ast_ari_sounds_get_args::sound_id, and ast_variable::value.
 {
    struct ast_ari_sounds_get_args args = {};
    struct ast_variable *i;
 #if defined(AST_DEVMODE)
    int is_valid;
    int code;
 #endif /* AST_DEVMODE */
    for (i = path_vars; i; i = i->next) {
       if (strcmp(i->name, "soundId") == 0) {
          args.sound_id = (i->value);
       } else
       {}
    }
    ast_ari_sounds_get(headers, &args, response);
 #if defined(AST_DEVMODE)
    code = response->response_code;
    switch (code) {
    case 0: /* Implementation is still a stub, or the code wasn't set */
       is_valid = response->message == NULL;
       break;
    case 500: /* Internal Server Error */
    case 501: /* Not Implemented */
       is_valid = 1;
       break;
    default:
       if (200 <= code && code <= 299) {
          is_valid = ast_ari_validate_sound(
             response->message);
       } else {
          ast_log(LOG_ERROR, "Invalid error response %d for /sounds/{soundId}\n", code);
          is_valid = 0;
       }
    }
    if (!is_valid) {
       ast_log(LOG_ERROR, "Response validation failed for /sounds/{soundId}\n");
       ast_ari_response_error(response, 500,
          "Internal Server Error", "Response validation failed");
    }
 #endif /* AST_DEVMODE */
 fin: __attribute__((unused))
    return;
 }
ast_ari_sounds_list_cb()
static void ast_ari_sounds_list_cb (struct ast_tcptls_session_instance * ser, struct ast_variable * get_params, struct ast_variable * path_vars, struct ast_variable * headers, struct ast_json * body, struct ast_ari_response * response) static
Parameter parsing callback for /sounds.
Parameters
get_params GET parameters in the HTTP request.
path_vars Path variables extracted from the request.
headers HTTP headers.
[out] response Response to the HTTP request.
Definition at line 77 of file res_ari_sounds.c.
References ast_ari_response_alloc_failed(), ast_ari_response_error(), ast_ari_sounds_list(), ast_ari_sounds_list_parse_body(), ast_ari_validate_list(), ast_ari_validate_sound_fn(), ast_log, ast_ari_sounds_list_args::format, ast_ari_sounds_list_args::lang, LOG_ERROR, ast_ari_response::message, ast_variable::name, ast_variable::next, NULL, ast_ari_response::response_code, and ast_variable::value.
 {
    struct ast_ari_sounds_list_args args = {};
    struct ast_variable *i;
 #if defined(AST_DEVMODE)
    int is_valid;
    int code;
 #endif /* AST_DEVMODE */
    for (i = get_params; i; i = i->next) {
       if (strcmp(i->name, "lang") == 0) {
          args.lang = (i->value);
       } else
       if (strcmp(i->name, "format") == 0) {
          args.format = (i->value);
       } else
       {}
    }
    if (ast_ari_sounds_list_parse_body(body, &args)) {
       ast_ari_response_alloc_failed(response);
       goto fin;
    }
    ast_ari_sounds_list(headers, &args, response);
 #if defined(AST_DEVMODE)
    code = response->response_code;
    switch (code) {
    case 0: /* Implementation is still a stub, or the code wasn't set */
       is_valid = response->message == NULL;
       break;
    case 500: /* Internal Server Error */
    case 501: /* Not Implemented */
       is_valid = 1;
       break;
    default:
       if (200 <= code && code <= 299) {
          is_valid = ast_ari_validate_list(response->message,
             ast_ari_validate_sound_fn());
       } else {
          ast_log(LOG_ERROR, "Invalid error response %d for /sounds\n", code);
          is_valid = 0;
       }
    }
    if (!is_valid) {
       ast_log(LOG_ERROR, "Response validation failed for /sounds\n");
       ast_ari_response_error(response, 500,
          "Internal Server Error", "Response validation failed");
    }
 #endif /* AST_DEVMODE */
 fin: __attribute__((unused))
    return;
 }
ast_ari_sounds_list_parse_body()
int ast_ari_sounds_list_parse_body (struct ast_json * body, struct ast_ari_sounds_list_args * args)
Body parsing function for /sounds.
Parameters
body The JSON body from which to parse parameters.
[out] args The args structure to parse into.
Return values
zero on success
non-zero on failure
Definition at line 53 of file res_ari_sounds.c.
References ast_json_object_get(), ast_json_string_get(), ast_ari_sounds_list_args::format, and ast_ari_sounds_list_args::lang.
Referenced by ast_ari_sounds_list_cb().
 {
    struct ast_json *field;
    /* Parse query parameters out of it */
    field = ast_json_object_get(body, "lang");
    if (field) {
       args->lang = ast_json_string_get(field);
    }
    field = ast_json_object_get(body, "format");
    if (field) {
       args->format = ast_json_string_get(field);
    }
    return 0;
 }
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 237 of file res_ari_sounds.c.
load_module()
static int load_module (void) static
Definition at line 218 of file res_ari_sounds.c.
References ast_ari_add_handler(), AST_MODFLAG_DEFAULT, AST_MODULE_INFO(), AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, AST_MODULE_SUPPORT_CORE, ASTERISK_GPL_KEY, and unload_module().
 {
    int res = 0;
    res |= ast_ari_add_handler(&sounds);
    if (res) {
       unload_module();
       return AST_MODULE_LOAD_DECLINE;
    }
    return AST_MODULE_LOAD_SUCCESS;
 }
unload_module()
static int unload_module (void) static
Definition at line 212 of file res_ari_sounds.c.
References ast_ari_remove_handler().
Referenced by load_module().
 {
    ast_ari_remove_handler(&sounds);
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_DEFAULT , .description = "RESTful API module - Sound resources" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .requires = "res_ari,res_ari_model,res_stasis", } static
Definition at line 237 of file res_ari_sounds.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 237 of file res_ari_sounds.c.
sounds
struct stasis_rest_handlers sounds static
REST handler for /api-docs/sounds.json.
Definition at line 203 of file res_ari_sounds.c.
Referenced by bridge_profile_sounds_alloc(), bridge_profile_sounds_destroy_cb(), bridge_template_handler(), and set_sound().
sounds_soundId
struct stasis_rest_handlers sounds_soundId static
REST handler for /api-docs/sounds.json.
Definition at line 193 of file res_ari_sounds.c.