Asterisk - The Open Source Telephony Project: rtp_engine.h File Reference
rtp_engine.h File Reference
Pluggable RTP Architecture.
#include "asterisk/astobj2.h"
#include "asterisk/frame.h"
#include "asterisk/format_cap.h"
#include "asterisk/netsock2.h"
#include "asterisk/sched.h"
#include "asterisk/res_srtp.h"
#include "asterisk/stasis.h"
#include "asterisk/vector.h"
#include "asterisk/logger_category.h"
Data Structures
struct ast_rtp_codecs
struct ast_rtp_dtls_cfg
DTLS configuration structure.
struct ast_rtp_engine
struct ast_rtp_engine_dtls
Structure that represents the optional DTLS SRTP support within an RTP engine.
struct ast_rtp_engine_ice
Structure that represents the optional ICE support within an RTP engine.
struct ast_rtp_engine_ice_candidate
Structure for an ICE candidate.
struct ast_rtp_engine_test
Structure that represents the test functionality for res_rtp_asterisk unit tests.
struct ast_rtp_glue
struct ast_rtp_instance_stats
struct ast_rtp_payload_type
struct ast_rtp_rtcp_feedback
An object that represents data received in a feedback report.
struct ast_rtp_rtcp_feedback_remb
A REMB feedback message (see draft-alvestrand-rmcat-remb-03 for details)
struct ast_rtp_rtcp_report
An object that represents data sent during a SR/RR RTCP report.
struct ast_rtp_rtcp_report_block
A report block within a SR/RR report.
Macros
#define AST_DEBUG_CATEGORY_DTLS ast_debug_category_dtls_id() /* DTLS debug logging category id */
#define AST_DEBUG_CATEGORY_DTLS_PACKET ast_debug_category_dtls_packet_id() /* DTLS packet debug logging category id */
#define AST_DEBUG_CATEGORY_ICE ast_debug_category_ice_id() /* ICE debug logging category id */
#define AST_DEBUG_CATEGORY_RTCP ast_debug_category_rtcp_id() /* RTCP debug logging category id */
#define AST_DEBUG_CATEGORY_RTCP_PACKET ast_debug_category_rtcp_packet_id() /* RTCP packet debug logging category id */
#define AST_DEBUG_CATEGORY_RTP ast_debug_category_rtp_id() /* RTP debug logging category id */
#define AST_DEBUG_CATEGORY_RTP_PACKET ast_debug_category_rtp_packet_id() /* RTP packet debug logging category id */
#define ast_debug_dtls(sublevel, ...) ast_debug_category(sublevel, AST_DEBUG_CATEGORY_DTLS, __VA_ARGS__)
Log debug level DTLS information.
#define ast_debug_dtls_packet_is_allowed ast_debug_category_is_allowed(AST_LOG_CATEGORY_ENABLED, AST_DEBUG_CATEGORY_DTLS_PACKET)
#define ast_debug_ice(sublevel, ...) ast_debug_category(sublevel, AST_DEBUG_CATEGORY_ICE, __VA_ARGS__)
Log debug level ICE information.
#define ast_debug_rtcp(sublevel, ...) ast_debug_category(sublevel, AST_DEBUG_CATEGORY_RTCP, __VA_ARGS__)
Log debug level RTCP information.
#define ast_debug_rtcp_packet_is_allowed ast_debug_category_is_allowed(AST_LOG_CATEGORY_ENABLED, AST_DEBUG_CATEGORY_RTCP_PACKET)
#define ast_debug_rtp(sublevel, ...) ast_debug_category(sublevel, AST_DEBUG_CATEGORY_RTP, __VA_ARGS__)
Log debug level RTP information.
#define ast_debug_rtp_packet_is_allowed ast_debug_category_is_allowed(AST_LOG_CATEGORY_ENABLED, AST_DEBUG_CATEGORY_RTP_PACKET)
#define AST_LOG_CATEGORY_DTLS "dtls"
#define AST_LOG_CATEGORY_DTLS_PACKET "dtls_packet"
#define AST_LOG_CATEGORY_ICE "ice"
#define AST_LOG_CATEGORY_RTCP "rtcp"
#define AST_LOG_CATEGORY_RTCP_PACKET "rtcp_packet"
#define AST_LOG_CATEGORY_RTP "rtp"
#define AST_LOG_CATEGORY_RTP_PACKET "rtp_packet"
#define AST_RED_MAX_GENERATION 5
#define AST_RTP_CISCO_DTMF (1 << 2)
#define AST_RTP_CN (1 << 1)
#define AST_RTP_CODECS_NULL_INIT { .codecs_lock = AST_RWLOCK_INIT_VALUE, .payload_mapping_rx = { 0, }, .payload_mapping_tx = { 0, }, .framing = 0, }
#define AST_RTP_DTMF (1 << 0)
#define ast_rtp_engine_register(engine) ast_rtp_engine_register2(engine, AST_MODULE_SELF)
#define ast_rtp_glue_register(glue) ast_rtp_glue_register2(glue, AST_MODULE_SELF)
#define ast_rtp_instance_get_and_cmp_remote_address(instance, address) ast_rtp_instance_get_and_cmp_requested_target_address((instance), (address))
Get the address of the remote endpoint that we are sending RTP to, comparing its address to another.
#define ast_rtp_instance_get_remote_address(instance, address) ast_rtp_instance_get_incoming_source_address((instance), (address))
Get the address of the remote endpoint that we are sending RTP to.
#define ast_rtp_instance_set_remote_address(instance, address) ast_rtp_instance_set_requested_target_address((instance), (address))
Set the address of the remote endpoint that we are sending RTP to.
#define AST_RTP_MAX AST_RTP_CISCO_DTMF
#define AST_RTP_MAX_PT 128
#define AST_RTP_PT_FIRST_DYNAMIC 96
#define AST_RTP_PT_LAST_REASSIGN 63
#define AST_RTP_PT_LAST_STATIC 34
#define AST_RTP_RTCP_FMT_FIR 4
#define AST_RTP_RTCP_FMT_NACK 1
#define AST_RTP_RTCP_FMT_PLI 1
#define AST_RTP_RTCP_FMT_REMB 15
#define AST_RTP_RTCP_FMT_TRANSPORT_WIDE_CC 15
#define AST_RTP_RTCP_PSFB 206
#define AST_RTP_RTCP_RR 201
#define AST_RTP_RTCP_RTPFB 205
#define AST_RTP_RTCP_SR 200
#define AST_RTP_STAT_SET(current_stat, combined, placement, value)
#define AST_RTP_STAT_STRCPY(current_stat, combined, placement, value)
#define AST_RTP_STAT_TERMINATOR(combined)
#define MAX_CHANNEL_ID 152
Enumerations
enum ast_rtp_dtls_connection { AST_RTP_DTLS_CONNECTION_NEW, AST_RTP_DTLS_CONNECTION_EXISTING }
DTLS connection states.
enum ast_rtp_dtls_hash { AST_RTP_DTLS_HASH_SHA256, AST_RTP_DTLS_HASH_SHA1 }
DTLS fingerprint hashes.
enum ast_rtp_dtls_setup { AST_RTP_DTLS_SETUP_ACTIVE, AST_RTP_DTLS_SETUP_PASSIVE, AST_RTP_DTLS_SETUP_ACTPASS, AST_RTP_DTLS_SETUP_HOLDCONN }
DTLS setup types.
enum ast_rtp_dtls_verify { AST_RTP_DTLS_VERIFY_NONE = 0, AST_RTP_DTLS_VERIFY_FINGERPRINT = (1 << 0), AST_RTP_DTLS_VERIFY_CERTIFICATE = (1 << 1) }
DTLS verification settings.
enum ast_rtp_dtmf_mode { AST_RTP_DTMF_MODE_NONE = 0, AST_RTP_DTMF_MODE_RFC2833, AST_RTP_DTMF_MODE_INBAND }
enum ast_rtp_extension { AST_RTP_EXTENSION_UNSUPPORTED = 0, AST_RTP_EXTENSION_ABS_SEND_TIME, AST_RTP_EXTENSION_TRANSPORT_WIDE_CC, AST_RTP_EXTENSION_MAX }
Known RTP extensions.
enum ast_rtp_extension_direction {
AST_RTP_EXTENSION_DIRECTION_NONE, AST_RTP_EXTENSION_DIRECTION_SENDRECV, AST_RTP_EXTENSION_DIRECTION_SENDONLY, AST_RTP_EXTENSION_DIRECTION_RECVONLY,
AST_RTP_EXTENSION_DIRECTION_INACTIVE
}
Directions for RTP extensions.
enum ast_rtp_glue_result { AST_RTP_GLUE_RESULT_FORBID = 0, AST_RTP_GLUE_RESULT_REMOTE, AST_RTP_GLUE_RESULT_LOCAL }
enum ast_rtp_ice_candidate_type { AST_RTP_ICE_CANDIDATE_TYPE_HOST, AST_RTP_ICE_CANDIDATE_TYPE_SRFLX, AST_RTP_ICE_CANDIDATE_TYPE_RELAYED }
ICE candidate types.
enum ast_rtp_ice_component_type { AST_RTP_ICE_COMPONENT_RTP = 1, AST_RTP_ICE_COMPONENT_RTCP = 2 }
ICE component types.
enum ast_rtp_ice_role { AST_RTP_ICE_ROLE_CONTROLLED, AST_RTP_ICE_ROLE_CONTROLLING }
ICE role during negotiation.
enum ast_rtp_instance_rtcp { AST_RTP_INSTANCE_RTCP_DISABLED = 0, AST_RTP_INSTANCE_RTCP_STANDARD, AST_RTP_INSTANCE_RTCP_MUX }
enum ast_rtp_instance_stat {
AST_RTP_INSTANCE_STAT_ALL = 0, AST_RTP_INSTANCE_STAT_TXCOUNT, AST_RTP_INSTANCE_STAT_RXCOUNT, AST_RTP_INSTANCE_STAT_COMBINED_LOSS,
AST_RTP_INSTANCE_STAT_TXPLOSS, AST_RTP_INSTANCE_STAT_RXPLOSS, AST_RTP_INSTANCE_STAT_REMOTE_MAXRXPLOSS, AST_RTP_INSTANCE_STAT_REMOTE_MINRXPLOSS,
AST_RTP_INSTANCE_STAT_REMOTE_NORMDEVRXPLOSS, AST_RTP_INSTANCE_STAT_REMOTE_STDEVRXPLOSS, AST_RTP_INSTANCE_STAT_LOCAL_MAXRXPLOSS, AST_RTP_INSTANCE_STAT_LOCAL_MINRXPLOSS,
AST_RTP_INSTANCE_STAT_LOCAL_NORMDEVRXPLOSS, AST_RTP_INSTANCE_STAT_LOCAL_STDEVRXPLOSS, AST_RTP_INSTANCE_STAT_COMBINED_JITTER, AST_RTP_INSTANCE_STAT_TXJITTER,
AST_RTP_INSTANCE_STAT_RXJITTER, AST_RTP_INSTANCE_STAT_REMOTE_MAXJITTER, AST_RTP_INSTANCE_STAT_REMOTE_MINJITTER, AST_RTP_INSTANCE_STAT_REMOTE_NORMDEVJITTER,
AST_RTP_INSTANCE_STAT_REMOTE_STDEVJITTER, AST_RTP_INSTANCE_STAT_LOCAL_MAXJITTER, AST_RTP_INSTANCE_STAT_LOCAL_MINJITTER, AST_RTP_INSTANCE_STAT_LOCAL_NORMDEVJITTER,
AST_RTP_INSTANCE_STAT_LOCAL_STDEVJITTER, AST_RTP_INSTANCE_STAT_COMBINED_RTT, AST_RTP_INSTANCE_STAT_RTT, AST_RTP_INSTANCE_STAT_MAX_RTT,
AST_RTP_INSTANCE_STAT_MIN_RTT, AST_RTP_INSTANCE_STAT_NORMDEVRTT, AST_RTP_INSTANCE_STAT_STDEVRTT, AST_RTP_INSTANCE_STAT_LOCAL_SSRC,
AST_RTP_INSTANCE_STAT_REMOTE_SSRC, AST_RTP_INSTANCE_STAT_CHANNEL_UNIQUEID, AST_RTP_INSTANCE_STAT_TXOCTETCOUNT, AST_RTP_INSTANCE_STAT_RXOCTETCOUNT
}
enum ast_rtp_instance_stat_field { AST_RTP_INSTANCE_STAT_FIELD_QUALITY = 0, AST_RTP_INSTANCE_STAT_FIELD_QUALITY_JITTER, AST_RTP_INSTANCE_STAT_FIELD_QUALITY_LOSS, AST_RTP_INSTANCE_STAT_FIELD_QUALITY_RTT }
enum ast_rtp_options { AST_RTP_OPT_G726_NONSTANDARD = (1 << 0) }
enum ast_rtp_property {
AST_RTP_PROPERTY_NAT = 0, AST_RTP_PROPERTY_DTMF, AST_RTP_PROPERTY_DTMF_COMPENSATE, AST_RTP_PROPERTY_STUN,
AST_RTP_PROPERTY_RTCP, AST_RTP_PROPERTY_ASYMMETRIC_CODEC, AST_RTP_PROPERTY_RETRANS_RECV, AST_RTP_PROPERTY_RETRANS_SEND,
AST_RTP_PROPERTY_REMB, AST_RTP_PROPERTY_MAX
}
Functions
uintmax_t ast_debug_category_dtls_id (void)
uintmax_t ast_debug_category_dtls_packet_id (void)
uintmax_t ast_debug_category_ice_id (void)
uintmax_t ast_debug_category_rtcp_id (void)
uintmax_t ast_debug_category_rtcp_packet_id (void)
uintmax_t ast_debug_category_rtp_id (void)
uintmax_t ast_debug_category_rtp_packet_id (void)
int ast_rtp_codecs_find_payload_code (struct ast_rtp_codecs *codecs, int payload)
Search for the tx payload type in the ast_rtp_codecs structure.
unsigned int ast_rtp_codecs_get_framing (struct ast_rtp_codecs *codecs)
Get the framing used for a set of codecs.
struct ast_rtp_payload_type * ast_rtp_codecs_get_payload (struct ast_rtp_codecs *codecs, int payload)
Retrieve rx payload mapped information by payload type.
struct ast_format * ast_rtp_codecs_get_payload_format (struct ast_rtp_codecs *codecs, int payload)
Retrieve the actual ast_format stored on the codecs structure for a specific tx payload type.
enum ast_media_type ast_rtp_codecs_get_stream_type (struct ast_rtp_codecs *codecs)
Determine the type of RTP stream media from the codecs mapped.
int ast_rtp_codecs_payload_code (struct ast_rtp_codecs *codecs, int asterisk_format, struct ast_format *format, int code)
Retrieve a rx mapped payload type based on whether it is an Asterisk format and the code.
int ast_rtp_codecs_payload_code_tx (struct ast_rtp_codecs *codecs, int asterisk_format, const struct ast_format *format, int code)
Retrieve a tx mapped payload type based on whether it is an Asterisk format and the code.
void ast_rtp_codecs_payload_formats (struct ast_rtp_codecs *codecs, struct ast_format_cap *astformats, int *nonastformats)
Retrieve all formats that were found.
int ast_rtp_codecs_payload_replace_format (struct ast_rtp_codecs *codecs, int payload, struct ast_format *format)
Update the format associated with a tx payload type in a codecs structure.
int ast_rtp_codecs_payload_set_rx (struct ast_rtp_codecs *codecs, int code, struct ast_format *format)
Set a payload code for use with a specific Asterisk format.
void ast_rtp_codecs_payloads_clear (struct ast_rtp_codecs *codecs, struct ast_rtp_instance *instance)
Clear rx and tx payload mapping information from an RTP instance.
void ast_rtp_codecs_payloads_copy (struct ast_rtp_codecs *src, struct ast_rtp_codecs *dest, struct ast_rtp_instance *instance)
Copy payload information from one RTP instance to another.
void ast_rtp_codecs_payloads_destroy (struct ast_rtp_codecs *codecs)
Destroy the contents of an RTP codecs structure (but not the structure itself)
int ast_rtp_codecs_payloads_initialize (struct ast_rtp_codecs *codecs)
Initialize an RTP codecs structure.
void ast_rtp_codecs_payloads_set_m_type (struct ast_rtp_codecs *codecs, struct ast_rtp_instance *instance, int payload)
Record tx payload type information that was seen in an m= SDP line.
int ast_rtp_codecs_payloads_set_rtpmap_type (struct ast_rtp_codecs *codecs, struct ast_rtp_instance *instance, int payload, char *mimetype, char *mimesubtype, enum ast_rtp_options options)
Record tx payload type information that was seen in an a=rtpmap: SDP line.
int ast_rtp_codecs_payloads_set_rtpmap_type_rate (struct ast_rtp_codecs *codecs, struct ast_rtp_instance *instance, int pt, char *mimetype, char *mimesubtype, enum ast_rtp_options options, unsigned int sample_rate)
Set tx payload type to a known MIME media type for a codec with a specific sample rate.
void ast_rtp_codecs_payloads_unset (struct ast_rtp_codecs *codecs, struct ast_rtp_instance *instance, int payload)
Remove tx payload type mapped information.
void ast_rtp_codecs_payloads_xover (struct ast_rtp_codecs *src, struct ast_rtp_codecs *dest, struct ast_rtp_instance *instance)
Crossover copy the tx payload mapping of src to the rx payload mapping of dest.
void ast_rtp_codecs_set_framing (struct ast_rtp_codecs *codecs, unsigned int framing)
Set the framing used for a set of codecs.
struct ast_json * ast_rtp_convert_stats_json (const struct ast_rtp_instance_stats *stats)
Convert given stat instance into json format.
void ast_rtp_dtls_cfg_copy (const struct ast_rtp_dtls_cfg *src_cfg, struct ast_rtp_dtls_cfg *dst_cfg)
Copy contents of a DTLS configuration structure.
void ast_rtp_dtls_cfg_free (struct ast_rtp_dtls_cfg *dtls_cfg)
Free contents of a DTLS configuration structure.
int ast_rtp_dtls_cfg_parse (struct ast_rtp_dtls_cfg *dtls_cfg, const char *name, const char *value)
Parse DTLS related configuration options.
int ast_rtp_dtls_cfg_validate (struct ast_rtp_dtls_cfg *dtls_cfg)
Validates DTLS related configuration options.
struct ast_rtp_payload_type * ast_rtp_engine_alloc_payload_type (void)
Allocation routine for ast_rtp_payload_type.
int ast_rtp_engine_load_format (struct ast_format *format)
Custom formats declared in codecs.conf at startup must be communicated to the rtp_engine so their mime type can payload number can be initialized.
int ast_rtp_engine_register2 (struct ast_rtp_engine *engine, struct ast_module *module)
Register an RTP engine.
int ast_rtp_engine_register_srtp (struct ast_srtp_res *srtp_res, struct ast_srtp_policy_res *policy_res)
int ast_rtp_engine_srtp_is_registered (void)
int ast_rtp_engine_unload_format (struct ast_format *format)
Formats requiring the use of a format attribute interface must have that interface registered in order for the rtp engine to handle it correctly. If an attribute interface is unloaded, this function must be called to notify the rtp_engine.
int ast_rtp_engine_unregister (struct ast_rtp_engine *engine)
Unregister an RTP engine.
void ast_rtp_engine_unregister_srtp (void)
int ast_rtp_get_rate (const struct ast_format *format)
Retrieve the sample rate of a format according to RTP specifications.
int ast_rtp_glue_register2 (struct ast_rtp_glue *glue, struct ast_module *module)
Register RTP glue.
int ast_rtp_glue_unregister (struct ast_rtp_glue *glue)
Unregister RTP glue.
int ast_rtp_instance_activate (struct ast_rtp_instance *instance)
Indicate to the RTP engine that packets are now expected to be sent/received on the RTP instance.
int ast_rtp_instance_add_srtp_policy (struct ast_rtp_instance *instance, struct ast_srtp_policy *remote_policy, struct ast_srtp_policy *local_policy, int rtcp)
Add or replace the SRTP policies for the given RTP instance.
void ast_rtp_instance_available_formats (struct ast_rtp_instance *instance, struct ast_format_cap *to_endpoint, struct ast_format_cap *to_asterisk, struct ast_format_cap *result)
Request the formats that can be transcoded.
int ast_rtp_instance_bundle (struct ast_rtp_instance *child, struct ast_rtp_instance *parent)
Request that an RTP instance be bundled with another.
void ast_rtp_instance_change_source (struct ast_rtp_instance *instance)
Indicate a new source of audio has dropped in and the ssrc should change.
int ast_rtp_instance_destroy (struct ast_rtp_instance *instance)
Destroy an RTP instance.
void ast_rtp_instance_drop_packets (struct ast_rtp_instance *instance, int num)
Set the number of packets to drop on RTP read.
int ast_rtp_instance_dtmf_begin (struct ast_rtp_instance *instance, char digit)
Begin sending a DTMF digit.
int ast_rtp_instance_dtmf_end (struct ast_rtp_instance *instance, char digit)
Stop sending a DTMF digit.
int ast_rtp_instance_dtmf_end_with_duration (struct ast_rtp_instance *instance, char digit, unsigned int duration)
enum ast_rtp_dtmf_mode ast_rtp_instance_dtmf_mode_get (struct ast_rtp_instance *instance)
Get the DTMF mode of an RTP instance.
int ast_rtp_instance_dtmf_mode_set (struct ast_rtp_instance *instance, enum ast_rtp_dtmf_mode dtmf_mode)
Set the DTMF mode that should be used.
int ast_rtp_instance_early_bridge (struct ast_channel *c0, struct ast_channel *c1)
Early bridge two channels that use RTP instances.
void ast_rtp_instance_early_bridge_make_compatible (struct ast_channel *c_dst, struct ast_channel *c_src)
Make two channels compatible for early bridging.
void ast_rtp_instance_extmap_clear (struct ast_rtp_instance *instance)
Clear negotiated RTP extension information.
size_t ast_rtp_instance_extmap_count (struct ast_rtp_instance *instance)
Get the number of known unique identifiers.
int ast_rtp_instance_extmap_enable (struct ast_rtp_instance *instance, int id, enum ast_rtp_extension extension, enum ast_rtp_extension_direction direction)
Enable support for an RTP extension on an instance.
enum ast_rtp_extension_direction ast_rtp_instance_extmap_get_direction (struct ast_rtp_instance *instance, int id)
Retrieve the negotiated direction for an RTP extension id.
enum ast_rtp_extension ast_rtp_instance_extmap_get_extension (struct ast_rtp_instance *instance, int id)
Retrieve the extension for an RTP extension id.
int ast_rtp_instance_extmap_get_id (struct ast_rtp_instance *instance, enum ast_rtp_extension extension)
Retrieve the id for an RTP extension.
const char * ast_rtp_instance_extmap_get_uri (struct ast_rtp_instance *instance, int id)
Retrieve the URI for an RTP extension id.
int ast_rtp_instance_extmap_negotiate (struct ast_rtp_instance *instance, int id, enum ast_rtp_extension_direction direction, const char *uri, const char *attributes)
Negotiate received RTP extension information.
int ast_rtp_instance_fd (struct ast_rtp_instance *instance, int rtcp)
Get the file descriptor for an RTP session (or RTCP)
struct ast_rtp_glue * ast_rtp_instance_get_active_glue (struct ast_rtp_instance *instance)
Get the RTP glue in use on an RTP instance.
int ast_rtp_instance_get_and_cmp_local_address (struct ast_rtp_instance *instance, struct ast_sockaddr *address)
Get the address of the local endpoint that we are sending RTP to, comparing its address to another.
int ast_rtp_instance_get_and_cmp_requested_target_address (struct ast_rtp_instance *instance, struct ast_sockaddr *address)
Get the requested target address of the remote endpoint and compare it to the given address.
struct ast_rtp_instance * ast_rtp_instance_get_bridged (struct ast_rtp_instance *instance)
Get the other RTP instance that an instance is bridged to.
const char * ast_rtp_instance_get_channel_id (struct ast_rtp_instance *instance)
Get the unique ID of the channel that owns this RTP instance.
const char * ast_rtp_instance_get_cname (struct ast_rtp_instance *rtp)
Retrieve the CNAME used in RTCP SDES items.
struct ast_rtp_codecs * ast_rtp_instance_get_codecs (struct ast_rtp_instance *instance)
Get the codecs structure of an RTP instance.
void * ast_rtp_instance_get_data (struct ast_rtp_instance *instance)
Get the data portion of an RTP instance.
struct ast_rtp_engine_dtls * ast_rtp_instance_get_dtls (struct ast_rtp_instance *instance)
Obtain a pointer to the DTLS support present on an RTP instance.
struct ast_rtp_engine * ast_rtp_instance_get_engine (struct ast_rtp_instance *instance)
Get the RTP engine in use on an RTP instance.
void * ast_rtp_instance_get_extended_prop (struct ast_rtp_instance *instance, int property)
Get the value of an RTP instance extended property.
struct ast_rtp_glue * ast_rtp_instance_get_glue (const char *type)
Get the RTP glue that binds a channel to the RTP engine.
int ast_rtp_instance_get_hold_timeout (struct ast_rtp_instance *instance)
Get the RTP timeout value for when an RTP instance is on hold.
struct ast_rtp_engine_ice * ast_rtp_instance_get_ice (struct ast_rtp_instance *instance)
Obtain a pointer to the ICE support present on an RTP instance.
void ast_rtp_instance_get_incoming_source_address (struct ast_rtp_instance *instance, struct ast_sockaddr *address)
Get the incoming source address of the remote endpoint.
int ast_rtp_instance_get_keepalive (struct ast_rtp_instance *instance)
Get the RTP keepalive interval.
time_t ast_rtp_instance_get_last_rx (const struct ast_rtp_instance *rtp)
time_t ast_rtp_instance_get_last_tx (const struct ast_rtp_instance *rtp)
Get the last RTP transmission time.
void ast_rtp_instance_get_local_address (struct ast_rtp_instance *instance, struct ast_sockaddr *address)
Get the local address that we are expecting RTP on.
int ast_rtp_instance_get_prop (struct ast_rtp_instance *instance, enum ast_rtp_property property)
Get the value of an RTP instance property.
char * ast_rtp_instance_get_quality (struct ast_rtp_instance *instance, enum ast_rtp_instance_stat_field field, char *buf, size_t size)
Retrieve quality statistics about an RTP instance.
size_t ast_rtp_instance_get_recv_buffer_count (struct ast_rtp_instance *instance)
Get the current size of the receive buffer.
size_t ast_rtp_instance_get_recv_buffer_max (struct ast_rtp_instance *instance)
Get the maximum size of the receive buffer.
void ast_rtp_instance_get_requested_target_address (struct ast_rtp_instance *instance, struct ast_sockaddr *address)
Get the requested target address of the remote endpoint.
int ast_rtp_instance_get_sdes_received (struct ast_rtp_instance *instance)
Get the value of sdes_received on the test engine.
size_t ast_rtp_instance_get_send_buffer_count (struct ast_rtp_instance *instance)
Get the current size of the send buffer.
struct ast_srtp * ast_rtp_instance_get_srtp (struct ast_rtp_instance *instance, int rtcp)
Obtain the SRTP instance associated with an RTP instance.
unsigned int ast_rtp_instance_get_ssrc (struct ast_rtp_instance *rtp)
Retrieve the local SSRC value that we will be using.
int ast_rtp_instance_get_stats (struct ast_rtp_instance *instance, struct ast_rtp_instance_stats *stats, enum ast_rtp_instance_stat stat)
Retrieve statistics about an RTP instance.
struct ast_json * ast_rtp_instance_get_stats_all_json (struct ast_rtp_instance *instance)
Retrieve statistics about an RTP instance in json format.
struct ast_rtp_engine_test * ast_rtp_instance_get_test (struct ast_rtp_instance *instance)
Obtain a pointer to the test callbacks on an RTP instance.
int ast_rtp_instance_get_timeout (struct ast_rtp_instance *instance)
Get the RTP timeout value.
int ast_rtp_instance_make_compatible (struct ast_channel *chan, struct ast_rtp_instance *instance, struct ast_channel *peer)
Request that the underlying RTP engine make two RTP instances compatible with eachother.
struct ast_rtp_instance * ast_rtp_instance_new (const char *engine_name, struct ast_sched_context *sched, const struct ast_sockaddr *sa, void *data)
Create a new RTP instance.
void ast_rtp_instance_queue_report (struct ast_rtp_instance *instance)
Sends a SR/RR report the next time RTP would be sent.
struct ast_frame * ast_rtp_instance_read (struct ast_rtp_instance *instance, int rtcp)
Receive a frame over RTP.
void ast_rtp_instance_reset_test_engine (struct ast_rtp_instance *instance)
Resets all the fields to default values for the test engine.
int ast_rtp_instance_sendcng (struct ast_rtp_instance *instance, int level)
Send a comfort noise packet to the RTP instance.
void ast_rtp_instance_set_bridged (struct ast_rtp_instance *instance, struct ast_rtp_instance *bridged)
Set the other RTP instance that an instance is bridged to.
void ast_rtp_instance_set_channel_id (struct ast_rtp_instance *instance, const char *uniqueid)
Set the channel that owns this RTP instance.
void ast_rtp_instance_set_data (struct ast_rtp_instance *instance, void *data)
Set the data portion of an RTP instance.
void ast_rtp_instance_set_extended_prop (struct ast_rtp_instance *instance, int property, void *value)
Set the value of an RTP instance extended property.
void ast_rtp_instance_set_hold_timeout (struct ast_rtp_instance *instance, int timeout)
Set the RTP timeout value for when the instance is on hold.
int ast_rtp_instance_set_incoming_source_address (struct ast_rtp_instance *instance, const struct ast_sockaddr *address)
Set the incoming source address of the remote endpoint that we are sending RTP to.
void ast_rtp_instance_set_keepalive (struct ast_rtp_instance *instance, int timeout)
Set the RTP keepalive interval.
void ast_rtp_instance_set_last_rx (struct ast_rtp_instance *rtp, time_t time)
Set the last RTP reception time.
void ast_rtp_instance_set_last_tx (struct ast_rtp_instance *rtp, time_t time)
Set the last RTP transmission time.
int ast_rtp_instance_set_local_address (struct ast_rtp_instance *instance, const struct ast_sockaddr *address)
Set the address that we are expecting to receive RTP on.
void ast_rtp_instance_set_prop (struct ast_rtp_instance *instance, enum ast_rtp_property property, int value)
Set the value of an RTP instance property.
int ast_rtp_instance_set_qos (struct ast_rtp_instance *instance, int tos, int cos, const char *desc)
Set QoS parameters on an RTP session.
int ast_rtp_instance_set_read_format (struct ast_rtp_instance *instance, struct ast_format *format)
Request that the underlying RTP engine provide audio frames in a specific format.
void ast_rtp_instance_set_remote_ssrc (struct ast_rtp_instance *rtp, unsigned int ssrc)
Set the remote SSRC for an RTP instance.
int ast_rtp_instance_set_requested_target_address (struct ast_rtp_instance *instance, const struct ast_sockaddr *address)
Set the requested target address of the remote endpoint.
void ast_rtp_instance_set_schedid (struct ast_rtp_instance *instance, int id)
Set the schedid for RTCP.
void ast_rtp_instance_set_stats_vars (struct ast_channel *chan, struct ast_rtp_instance *instance)
Set standard statistics from an RTP instance on a channel.
void ast_rtp_instance_set_stream_num (struct ast_rtp_instance *instance, int stream_num)
Set the stream number for an RTP instance.
void ast_rtp_instance_set_timeout (struct ast_rtp_instance *instance, int timeout)
Set the RTP timeout value.
int ast_rtp_instance_set_write_format (struct ast_rtp_instance *instance, struct ast_format *format)
Tell underlying RTP engine that audio frames will be provided in a specific format.
void ast_rtp_instance_stop (struct ast_rtp_instance *instance)
Stop an RTP instance.
void ast_rtp_instance_stun_request (struct ast_rtp_instance *instance, struct ast_sockaddr *suggestion, const char *username)
Request that the underlying RTP engine send a STUN BIND request.
void ast_rtp_instance_update_source (struct ast_rtp_instance *instance)
Indicate that the RTP marker bit should be set on an RTP stream.
int ast_rtp_instance_write (struct ast_rtp_instance *instance, struct ast_frame *frame)
Send a frame out over RTP.
char * ast_rtp_lookup_mime_multiple2 (struct ast_str *buf, struct ast_format_cap *ast_format_capability, int rtp_capability, const int asterisk_format, enum ast_rtp_options options)
Convert formats into a string and put them into a buffer.
const char * ast_rtp_lookup_mime_subtype2 (const int asterisk_format, const struct ast_format *format, int code, enum ast_rtp_options options)
Retrieve mime subtype information on a payload.
unsigned int ast_rtp_lookup_sample_rate2 (int asterisk_format, const struct ast_format *format, int code)
Get the sample rate associated with known RTP payload types.
void ast_rtp_publish_rtcp_message (struct ast_rtp_instance *rtp, struct stasis_message_type *message_type, struct ast_rtp_rtcp_report *report, struct ast_json *blob)
Publish an RTCP message to Stasis Message Bus API.
int ast_rtp_red_buffer (struct ast_rtp_instance *instance, struct ast_frame *frame)
Buffer a frame in an RTP instance for RED.
int ast_rtp_red_init (struct ast_rtp_instance *instance, int buffer_time, int *payloads, int generations)
Initialize RED support on an RTP instance.
struct stasis_message_type * ast_rtp_rtcp_received_type (void)
Message type for an RTCP message received from some external source.
struct ast_rtp_rtcp_report * ast_rtp_rtcp_report_alloc (unsigned int report_blocks)
Allocate an ao2 ref counted instance of ast_rtp_rtcp_report.
struct stasis_message_type * ast_rtp_rtcp_sent_type (void)
Message type for an RTCP message sent from this Asterisk instance.
struct stasis_topic * ast_rtp_topic (void)
Stasis Message Bus API topic for RTP and RTCP related messages
Detailed Description
Pluggable RTP Architecture.
Author
Joshua Colp jcolp.nosp@m.@dig.nosp@m.ium.c.nosp@m.om Asterisk RTP Engine API
Definition in file rtp_engine.h.
Macro Definition Documentation
AST_RED_MAX_GENERATION
#define AST_RED_MAX_GENERATION 5
Maximum number of generations
Definition at line 98 of file rtp_engine.h.
Referenced by process_sdp_a_text().
AST_RTP_CISCO_DTMF
#define AST_RTP_CISCO_DTMF (1 << 2)
DTMF (Cisco Proprietary)
Definition at line 270 of file rtp_engine.h.
Referenced by ast_rtp_engine_init(), and ast_rtp_interpret().
AST_RTP_CN
#define AST_RTP_CN (1 << 1)
'Comfort Noise' (RFC3389)
Definition at line 268 of file rtp_engine.h.
Referenced by ast_rtp_engine_init(), ast_rtp_interpret(), and ast_rtp_sendcng().
AST_RTP_CODECS_NULL_INIT
#define AST_RTP_CODECS_NULL_INIT { .codecs_lock = AST_RWLOCK_INIT_VALUE, .payload_mapping_rx = { 0, }, .payload_mapping_tx = { 0, }, .framing = 0, }
Definition at line 716 of file rtp_engine.h.
Referenced by process_sdp(), set_caps(), and set_incoming_call_offer_cap().
AST_RTP_DTMF
#define AST_RTP_DTMF (1 << 0)
DTMF (RFC2833)
Definition at line 266 of file rtp_engine.h.
Referenced by __sip_alloc(), add_noncodec_to_sdp(), add_sdp(), ast_rtp_dtmf_begin(), ast_rtp_engine_init(), ast_rtp_interpret(), check_peer_ok(), create_addr_from_peer(), create_outgoing_sdp_stream(), process_sdp(), and sip_dtmfmode().
ast_rtp_engine_register
#define ast_rtp_engine_register (engine) ast_rtp_engine_register2(engine, AST_MODULE_SELF)
Definition at line 794 of file rtp_engine.h.
Referenced by AST_TEST_DEFINE(), and load_module().
ast_rtp_glue_register
#define ast_rtp_glue_register (glue) ast_rtp_glue_register2(glue, AST_MODULE_SELF)
Definition at line 847 of file rtp_engine.h.
Referenced by load_module().
ast_rtp_instance_get_and_cmp_remote_address
#define ast_rtp_instance_get_and_cmp_remote_address (instance, address) ast_rtp_instance_get_and_cmp_requested_target_address((instance), (address))
Get the address of the remote endpoint that we are sending RTP to, comparing its address to another.
Parameters
instance The instance that we want to get the remote address for
address An initialized address that may be overwritten if the remote address is different
Return values
0 address was not changed
1 address was changed Example usage:
struct ast_sockaddr address;
int ret;
ret = ast_rtp_instance_get_and_cmp_remote_address(instance, &address);
This retrieves the current remote address set on the instance pointed to by instance and puts the value into the address structure.
Since
1.8
Definition at line 1228 of file rtp_engine.h.
Referenced by check_for_rtp_changes(), ooh323_set_rtp_peer(), and sip_set_rtp_peer().
ast_rtp_instance_get_remote_address
#define ast_rtp_instance_get_remote_address (instance, address) ast_rtp_instance_get_incoming_source_address((instance), (address))
Get the address of the remote endpoint that we are sending RTP to.
Parameters
instance The instance that we want to get the remote address for
address A structure to put the address into
Example usage:
struct ast_sockaddr address;
ast_rtp_instance_get_remote_address(instance, &address);
This retrieves the current remote address set on the instance pointed to by instance and puts the value into the address structure.
Since
1.8
Definition at line 1192 of file rtp_engine.h.
Referenced by __rtp_recvfrom(), add_sdp(), ast_rtcp_write(), ast_rtp_bundle(), ast_rtp_dtmf_begin(), ast_rtp_dtmf_continuation(), ast_rtp_dtmf_end_with_duration(), ast_rtp_prop_set(), ast_rtp_read(), ast_rtp_rtcp_handle_nack(), ast_rtp_sendcng(), ast_rtp_write(), bridge_p2p_rtp_write(), channel_read_rtp(), create_dtmf_frame(), find_rtp_port(), jingle_interpret_ice_udp_transport(), multicast_send_control_packet(), ooh323_get_rtp_peer(), process_cn_rfc3389(), process_dtmf_rfc2833(), process_sdp(), rtp_raw_write(), send_start_rtp(), sip_acf_channel_read(), skinny_set_rtp_peer(), transmit_modify_with_sdp(), and unistim_set_rtp_peer().
ast_rtp_instance_set_remote_address
#define ast_rtp_instance_set_remote_address (instance, address) ast_rtp_instance_set_requested_target_address((instance), (address))
Set the address of the remote endpoint that we are sending RTP to.
Parameters
instance The RTP instance to change the address on
address Address to set it to
Return values
0 success
-1 failure
Example usage:
ast_rtp_instance_set_remote_address(instance, &sin);
This changes the remote address that RTP will be sent to on instance to the address given in the sin structure.
Since
1.8
Definition at line 1080 of file rtp_engine.h.
Referenced by __rtp_recvfrom(), apply_negotiated_sdp_stream(), ast_rtp_bundle(), ast_rtp_ice_start_media(), ast_rtp_read(), ast_rtp_remote_address_set(), ast_rtp_stop(), AST_TEST_DEFINE(), handle_open_receive_channel_ack_message(), jingle_interpret_ice_udp_transport(), multicast_rtp_request(), process_sdp(), setup_rtp_connection(), setup_rtp_remote(), start_rtp(), test_init_rtp_instances(), and unicast_rtp_request().
AST_RTP_MAX
#define AST_RTP_MAX AST_RTP_CISCO_DTMF
Maximum RTP-specific code
Definition at line 272 of file rtp_engine.h.
Referenced by add_sdp(), ast_rtp_lookup_mime_multiple2(), and create_outgoing_sdp_stream().
AST_RTP_MAX_PT
#define AST_RTP_MAX_PT 128
Maximum number of payload types RTP can support.
Definition at line 83 of file rtp_engine.h.
Referenced by ast_rtp_codecs_get_payload(), ast_rtp_codecs_get_payload_format(), ast_rtp_codecs_payload_replace_format(), ast_rtp_codecs_payloads_clear(), ast_rtp_codecs_payloads_initialize(), ast_rtp_codecs_payloads_set_m_type(), ast_rtp_codecs_payloads_set_rtpmap_type_rate(), ast_rtp_codecs_payloads_unset(), ast_rtp_engine_unload_format(), find_static_payload_type(), find_unused_payload(), handle_show_settings(), and rtp_engine_shutdown().
AST_RTP_PT_FIRST_DYNAMIC
#define AST_RTP_PT_FIRST_DYNAMIC 96
First dynamic RTP payload type
Definition at line 92 of file rtp_engine.h.
Referenced by find_unused_payload(), handle_show_settings(), load_asterisk_conf(), rtp_codecs_assign_payload_code_rx(), and rtp_codecs_find_non_primary_dynamic_rx().
AST_RTP_PT_LAST_REASSIGN
#define AST_RTP_PT_LAST_REASSIGN 63
Last reassignable RTP payload type
Definition at line 95 of file rtp_engine.h.
Referenced by find_unused_payload(), and handle_show_settings().
AST_RTP_PT_LAST_STATIC
#define AST_RTP_PT_LAST_STATIC 34
Last RTP payload type statically assigned, see http://www.iana.org/assignments/rtp-parameters
Definition at line 89 of file rtp_engine.h.
Referenced by add_codec_to_sdp(), ast_rtp_codecs_get_payload(), ast_rtp_codecs_payloads_set_m_type(), find_unused_payload(), and generate_rtpmap_attr().
AST_RTP_RTCP_FMT_FIR
#define AST_RTP_RTCP_FMT_FIR 4
Full INTRA-frame Request (From RFC5104)
Definition at line 307 of file rtp_engine.h.
Referenced by ast_rtcp_interpret().
AST_RTP_RTCP_FMT_NACK
#define AST_RTP_RTCP_FMT_NACK 1
Generic NACK (From RFC4585 also RFC5104)
Definition at line 303 of file rtp_engine.h.
Referenced by ast_rtcp_generate_nack(), ast_rtcp_interpret(), and rtcp_payload_subtype2str().
AST_RTP_RTCP_FMT_PLI
#define AST_RTP_RTCP_FMT_PLI 1
Picture loss indication (From RFC4585)
Definition at line 305 of file rtp_engine.h.
Referenced by ast_rtcp_interpret().
AST_RTP_RTCP_FMT_REMB
#define AST_RTP_RTCP_FMT_REMB 15
REMB Information (From draft-alvestrand-rmcat-remb-03)
Definition at line 309 of file rtp_engine.h.
Referenced by ast_rtcp_interpret(), AST_TEST_DEFINE(), remb_collector_alloc(), remb_hook_event_cb(), rtcp_payload_subtype2str(), rtp_write_rtcp_psfb(), and softmix_bridge_write_rtcp().
AST_RTP_RTCP_FMT_TRANSPORT_WIDE_CC
#define AST_RTP_RTCP_FMT_TRANSPORT_WIDE_CC 15
Transport-wide congestion control feedback (From draft-holmer-rmcat-transport-wide-cc-extensions-01)
Definition at line 311 of file rtp_engine.h.
Referenced by rtp_transport_wide_cc_feedback_produce().
AST_RTP_RTCP_PSFB
#define AST_RTP_RTCP_PSFB 206
Payload Specific Feed Back (From RFC4585 also RFC5104)
Definition at line 299 of file rtp_engine.h.
Referenced by ast_rtp_write(), AST_TEST_DEFINE(), chan_pjsip_write_stream(), remb_collector_alloc(), remb_hook_event_cb(), and softmix_bridge_write_rtcp().
AST_RTP_RTCP_RR
#define AST_RTP_RTCP_RR 201
Receiver Report
Definition at line 295 of file rtp_engine.h.
Referenced by AST_TEST_DEFINE(), and lintospeex_feedback().
AST_RTP_RTCP_RTPFB
#define AST_RTP_RTCP_RTPFB 205
Transport Layer Feed Back (From RFC4585 also RFC5104)
Definition at line 297 of file rtp_engine.h.
Referenced by ast_rtcp_generate_nack(), ast_rtcp_interpret(), rtcp_payload_subtype2str(), and rtp_transport_wide_cc_feedback_produce().
AST_RTP_RTCP_SR
#define AST_RTP_RTCP_SR 200
Sender Report
Definition at line 293 of file rtp_engine.h.
Referenced by AST_TEST_DEFINE(), hook_event_cb(), lintospeex_feedback(), rtcp_report_to_ami(), and rtcp_report_to_json().
AST_RTP_STAT_SET
#define AST_RTP_STAT_SET (current_stat, combined, placement, value)
Definition at line 433 of file rtp_engine.h.
Referenced by ast_rtp_get_stat().
AST_RTP_STAT_STRCPY
#define AST_RTP_STAT_STRCPY (current_stat, combined, placement, value)
Definition at line 441 of file rtp_engine.h.
Referenced by ast_rtp_get_stat().
AST_RTP_STAT_TERMINATOR
#define AST_RTP_STAT_TERMINATOR (combined)
Value:
if (stat == combined) { \
return 0; \
}
Definition at line 449 of file rtp_engine.h.
Referenced by ast_rtp_get_stat().
MAX_CHANNEL_ID
#define MAX_CHANNEL_ID 152
Maximum size of an internal Asterisk channel unique ID.
Note
Must match the AST_MAX_UNIQUEID(AST_MAX_PUBLIC_UNIQUEID) value. We don't use that defined value directly here to avoid a hard dependency on channel.h.
Definition at line 107 of file rtp_engine.h.
Enumeration Type Documentation
ast_rtp_dtls_connection
enum ast_rtp_dtls_connection
DTLS connection states.
Enumerator
AST_RTP_DTLS_CONNECTION_NEW
Endpoint wants to use a new connection
AST_RTP_DTLS_CONNECTION_EXISTING
Endpoint wishes to use existing connection
Definition at line 521 of file rtp_engine.h.
{
    AST_RTP_DTLS_CONNECTION_NEW,      /*!< Endpoint wants to use a new connection */
    AST_RTP_DTLS_CONNECTION_EXISTING, /*!< Endpoint wishes to use existing connection */
 };
ast_rtp_dtls_hash
enum ast_rtp_dtls_hash
DTLS fingerprint hashes.
Enumerator
AST_RTP_DTLS_HASH_SHA256
SHA-256 fingerprint hash
AST_RTP_DTLS_HASH_SHA1
SHA-1 fingerprint hash
Definition at line 527 of file rtp_engine.h.
{
    AST_RTP_DTLS_HASH_SHA256, /*!< SHA-256 fingerprint hash */
    AST_RTP_DTLS_HASH_SHA1,   /*!< SHA-1 fingerprint hash */
 };
ast_rtp_dtls_setup
enum ast_rtp_dtls_setup
DTLS setup types.
Enumerator
AST_RTP_DTLS_SETUP_ACTIVE
Endpoint is willing to inititate connections
AST_RTP_DTLS_SETUP_PASSIVE
Endpoint is willing to accept connections
AST_RTP_DTLS_SETUP_ACTPASS
Endpoint is willing to both accept and initiate connections
AST_RTP_DTLS_SETUP_HOLDCONN
Endpoint does not want the connection to be established right now
Definition at line 513 of file rtp_engine.h.
{
    AST_RTP_DTLS_SETUP_ACTIVE,   /*!< Endpoint is willing to inititate connections */
    AST_RTP_DTLS_SETUP_PASSIVE,  /*!< Endpoint is willing to accept connections */
    AST_RTP_DTLS_SETUP_ACTPASS,  /*!< Endpoint is willing to both accept and initiate connections */
    AST_RTP_DTLS_SETUP_HOLDCONN, /*!< Endpoint does not want the connection to be established right now */
 };
ast_rtp_dtls_verify
enum ast_rtp_dtls_verify
DTLS verification settings.
Enumerator
AST_RTP_DTLS_VERIFY_NONE
Don't verify anything
AST_RTP_DTLS_VERIFY_FINGERPRINT
Verify the fingerprint
AST_RTP_DTLS_VERIFY_CERTIFICATE
Verify the certificate
Definition at line 533 of file rtp_engine.h.
{
    AST_RTP_DTLS_VERIFY_NONE = 0,               /*!< Don't verify anything */
    AST_RTP_DTLS_VERIFY_FINGERPRINT = (1 << 0), /*!< Verify the fingerprint */
    AST_RTP_DTLS_VERIFY_CERTIFICATE = (1 << 1), /*!< Verify the certificate */
 };
ast_rtp_dtmf_mode
enum ast_rtp_dtmf_mode
RTP DTMF Modes
Enumerator
AST_RTP_DTMF_MODE_NONE
No DTMF is being carried over the RTP stream
AST_RTP_DTMF_MODE_RFC2833
DTMF is being carried out of band using RFC2833
AST_RTP_DTMF_MODE_INBAND
DTMF is being carried inband over the RTP stream
Definition at line 148 of file rtp_engine.h.
{
    /*! No DTMF is being carried over the RTP stream */
    AST_RTP_DTMF_MODE_NONE = 0,
    /*! DTMF is being carried out of band using RFC2833 */
    AST_RTP_DTMF_MODE_RFC2833,
    /*! DTMF is being carried inband over the RTP stream */
    AST_RTP_DTMF_MODE_INBAND,
 };
ast_rtp_extension
enum ast_rtp_extension
Known RTP extensions.
Enumerator
AST_RTP_EXTENSION_UNSUPPORTED
Per the RFC 0 should not be used, so we treat it as an unsupported extension placeholder
AST_RTP_EXTENSION_ABS_SEND_TIME
abs-send-time from https://tools.ietf.org/html/draft-alvestrand-rmcat-remb-03
AST_RTP_EXTENSION_TRANSPORT_WIDE_CC
transport-cc from https://tools.ietf.org/html/draft-holmer-rmcat-transport-wide-cc-extensions-01
AST_RTP_EXTENSION_MAX
The maximum number of known RTP extensions
Definition at line 542 of file rtp_engine.h.
{
    /*! Per the RFC 0 should not be used, so we treat it as an unsupported extension placeholder */
    AST_RTP_EXTENSION_UNSUPPORTED = 0,
    /*! abs-send-time from https://tools.ietf.org/html/draft-alvestrand-rmcat-remb-03 */
    AST_RTP_EXTENSION_ABS_SEND_TIME,
    /*! transport-cc from https://tools.ietf.org/html/draft-holmer-rmcat-transport-wide-cc-extensions-01 */
    AST_RTP_EXTENSION_TRANSPORT_WIDE_CC,
    /*! The maximum number of known RTP extensions */
    AST_RTP_EXTENSION_MAX,
 };
ast_rtp_extension_direction
enum ast_rtp_extension_direction
Directions for RTP extensions.
Enumerator
AST_RTP_EXTENSION_DIRECTION_NONE
The extension is not negotiated and is not flowing
AST_RTP_EXTENSION_DIRECTION_SENDRECV
Send and receive
AST_RTP_EXTENSION_DIRECTION_SENDONLY
Send only
AST_RTP_EXTENSION_DIRECTION_RECVONLY
Receive only
AST_RTP_EXTENSION_DIRECTION_INACTIVE
Negotiated but not sending or receiving
Definition at line 769 of file rtp_engine.h.
{
    /*! The extension is not negotiated and is not flowing */
    AST_RTP_EXTENSION_DIRECTION_NONE,
    /*! Send and receive */
    AST_RTP_EXTENSION_DIRECTION_SENDRECV,
    /*! Send only */
    AST_RTP_EXTENSION_DIRECTION_SENDONLY,
    /*! Receive only */
    AST_RTP_EXTENSION_DIRECTION_RECVONLY,
    /*! Negotiated but not sending or receiving */
    AST_RTP_EXTENSION_DIRECTION_INACTIVE,
 };
ast_rtp_glue_result
enum ast_rtp_glue_result
Result codes when RTP glue is queried for information
Enumerator
AST_RTP_GLUE_RESULT_FORBID
No remote or local bridging is permitted
AST_RTP_GLUE_RESULT_REMOTE
Move RTP stream to be remote between devices directly
AST_RTP_GLUE_RESULT_LOCAL
Perform RTP engine level bridging if possible
Definition at line 158 of file rtp_engine.h.
{
    /*! No remote or local bridging is permitted */
    AST_RTP_GLUE_RESULT_FORBID = 0,
    /*! Move RTP stream to be remote between devices directly */
    AST_RTP_GLUE_RESULT_REMOTE,
    /*! Perform RTP engine level bridging if possible */
    AST_RTP_GLUE_RESULT_LOCAL,
 };
ast_rtp_ice_candidate_type
enum ast_rtp_ice_candidate_type
ICE candidate types.
Enumerator
AST_RTP_ICE_CANDIDATE_TYPE_HOST
ICE host candidate. A host candidate represents the actual local transport address in the host.
AST_RTP_ICE_CANDIDATE_TYPE_SRFLX
ICE server reflexive candidate, which represents the public mapped address of the local address.
AST_RTP_ICE_CANDIDATE_TYPE_RELAYED
ICE relayed candidate, which represents the address allocated in TURN server.
Definition at line 455 of file rtp_engine.h.
{
    AST_RTP_ICE_CANDIDATE_TYPE_HOST,    /*!< ICE host candidate. A host candidate represents the actual local transport address in the host. */
    AST_RTP_ICE_CANDIDATE_TYPE_SRFLX,   /*!< ICE server reflexive candidate, which represents the public mapped address of the local address. */
    AST_RTP_ICE_CANDIDATE_TYPE_RELAYED, /*!< ICE relayed candidate, which represents the address allocated in TURN server. */
 };
ast_rtp_ice_component_type
enum ast_rtp_ice_component_type
ICE component types.
Enumerator
AST_RTP_ICE_COMPONENT_RTP
AST_RTP_ICE_COMPONENT_RTCP
Definition at line 462 of file rtp_engine.h.
{
    AST_RTP_ICE_COMPONENT_RTP = 1,
    AST_RTP_ICE_COMPONENT_RTCP = 2,
 };
ast_rtp_ice_role
enum ast_rtp_ice_role
ICE role during negotiation.
Enumerator
AST_RTP_ICE_ROLE_CONTROLLED
AST_RTP_ICE_ROLE_CONTROLLING
Definition at line 468 of file rtp_engine.h.
                       {
    AST_RTP_ICE_ROLE_CONTROLLED,
    AST_RTP_ICE_ROLE_CONTROLLING,
 };
ast_rtp_instance_rtcp
enum ast_rtp_instance_rtcp
Enumerator
AST_RTP_INSTANCE_RTCP_DISABLED
RTCP should not be sent/received
AST_RTP_INSTANCE_RTCP_STANDARD
RTCP should be sent/received based on standard port rules
AST_RTP_INSTANCE_RTCP_MUX
RTCP should be sent/received on the same port as RTP
Definition at line 255 of file rtp_engine.h.
{
    /*! RTCP should not be sent/received */
    AST_RTP_INSTANCE_RTCP_DISABLED = 0,
    /*! RTCP should be sent/received based on standard port rules */
    AST_RTP_INSTANCE_RTCP_STANDARD,
    /*! RTCP should be sent/received on the same port as RTP */
    AST_RTP_INSTANCE_RTCP_MUX,
 };
ast_rtp_instance_stat
enum ast_rtp_instance_stat
Statistics that can be retrieved from an RTP instance
Enumerator
AST_RTP_INSTANCE_STAT_ALL
Retrieve all statistics
AST_RTP_INSTANCE_STAT_TXCOUNT
Retrieve number of packets transmitted
AST_RTP_INSTANCE_STAT_RXCOUNT
Retrieve number of packets received
AST_RTP_INSTANCE_STAT_COMBINED_LOSS
Retrieve ALL statistics relating to packet loss
AST_RTP_INSTANCE_STAT_TXPLOSS
Retrieve number of packets lost for transmitting
AST_RTP_INSTANCE_STAT_RXPLOSS
Retrieve number of packets lost for receiving
AST_RTP_INSTANCE_STAT_REMOTE_MAXRXPLOSS
Retrieve maximum number of packets lost on remote side
AST_RTP_INSTANCE_STAT_REMOTE_MINRXPLOSS
Retrieve minimum number of packets lost on remote side
AST_RTP_INSTANCE_STAT_REMOTE_NORMDEVRXPLOSS
Retrieve average number of packets lost on remote side
AST_RTP_INSTANCE_STAT_REMOTE_STDEVRXPLOSS
Retrieve standard deviation of packets lost on remote side
AST_RTP_INSTANCE_STAT_LOCAL_MAXRXPLOSS
Retrieve maximum number of packets lost on local side
AST_RTP_INSTANCE_STAT_LOCAL_MINRXPLOSS
Retrieve minimum number of packets lost on local side
AST_RTP_INSTANCE_STAT_LOCAL_NORMDEVRXPLOSS
Retrieve average number of packets lost on local side
AST_RTP_INSTANCE_STAT_LOCAL_STDEVRXPLOSS
Retrieve standard deviation of packets lost on local side
AST_RTP_INSTANCE_STAT_COMBINED_JITTER
Retrieve ALL statistics relating to jitter
AST_RTP_INSTANCE_STAT_TXJITTER
Retrieve jitter on transmitted packets
AST_RTP_INSTANCE_STAT_RXJITTER
Retrieve jitter on received packets
AST_RTP_INSTANCE_STAT_REMOTE_MAXJITTER
Retrieve maximum jitter on remote side
AST_RTP_INSTANCE_STAT_REMOTE_MINJITTER
Retrieve minimum jitter on remote side
AST_RTP_INSTANCE_STAT_REMOTE_NORMDEVJITTER
Retrieve average jitter on remote side
AST_RTP_INSTANCE_STAT_REMOTE_STDEVJITTER
Retrieve standard deviation jitter on remote side
AST_RTP_INSTANCE_STAT_LOCAL_MAXJITTER
Retrieve maximum jitter on local side
AST_RTP_INSTANCE_STAT_LOCAL_MINJITTER
Retrieve minimum jitter on local side
AST_RTP_INSTANCE_STAT_LOCAL_NORMDEVJITTER
Retrieve average jitter on local side
AST_RTP_INSTANCE_STAT_LOCAL_STDEVJITTER
Retrieve standard deviation jitter on local side
AST_RTP_INSTANCE_STAT_COMBINED_RTT
Retrieve ALL statistics relating to round trip time
AST_RTP_INSTANCE_STAT_RTT
Retrieve round trip time
AST_RTP_INSTANCE_STAT_MAX_RTT
Retrieve maximum round trip time
AST_RTP_INSTANCE_STAT_MIN_RTT
Retrieve minimum round trip time
AST_RTP_INSTANCE_STAT_NORMDEVRTT
Retrieve average round trip time
AST_RTP_INSTANCE_STAT_STDEVRTT
Retrieve standard deviation round trip time
AST_RTP_INSTANCE_STAT_LOCAL_SSRC
Retrieve local SSRC
AST_RTP_INSTANCE_STAT_REMOTE_SSRC
Retrieve remote SSRC
AST_RTP_INSTANCE_STAT_CHANNEL_UNIQUEID
Retrieve channel unique ID
AST_RTP_INSTANCE_STAT_TXOCTETCOUNT
Retrieve number of octets transmitted
AST_RTP_INSTANCE_STAT_RXOCTETCOUNT
Retrieve number of octets received
Definition at line 180 of file rtp_engine.h.
{
    /*! Retrieve all statistics */
    AST_RTP_INSTANCE_STAT_ALL = 0,
    /*! Retrieve number of packets transmitted */
    AST_RTP_INSTANCE_STAT_TXCOUNT,
    /*! Retrieve number of packets received */
    AST_RTP_INSTANCE_STAT_RXCOUNT,
    /*! Retrieve ALL statistics relating to packet loss */
    AST_RTP_INSTANCE_STAT_COMBINED_LOSS,
    /*! Retrieve number of packets lost for transmitting */
    AST_RTP_INSTANCE_STAT_TXPLOSS,
    /*! Retrieve number of packets lost for receiving */
    AST_RTP_INSTANCE_STAT_RXPLOSS,
    /*! Retrieve maximum number of packets lost on remote side */
    AST_RTP_INSTANCE_STAT_REMOTE_MAXRXPLOSS,
    /*! Retrieve minimum number of packets lost on remote side */
    AST_RTP_INSTANCE_STAT_REMOTE_MINRXPLOSS,
    /*! Retrieve average number of packets lost on remote side */
    AST_RTP_INSTANCE_STAT_REMOTE_NORMDEVRXPLOSS,
    /*! Retrieve standard deviation of packets lost on remote side */
    AST_RTP_INSTANCE_STAT_REMOTE_STDEVRXPLOSS,
    /*! Retrieve maximum number of packets lost on local side */
    AST_RTP_INSTANCE_STAT_LOCAL_MAXRXPLOSS,
    /*! Retrieve minimum number of packets lost on local side */
    AST_RTP_INSTANCE_STAT_LOCAL_MINRXPLOSS,
    /*! Retrieve average number of packets lost on local side */
    AST_RTP_INSTANCE_STAT_LOCAL_NORMDEVRXPLOSS,
    /*! Retrieve standard deviation of packets lost on local side */
    AST_RTP_INSTANCE_STAT_LOCAL_STDEVRXPLOSS,
    /*! Retrieve ALL statistics relating to jitter */
    AST_RTP_INSTANCE_STAT_COMBINED_JITTER,
    /*! Retrieve jitter on transmitted packets */
    AST_RTP_INSTANCE_STAT_TXJITTER,
    /*! Retrieve jitter on received packets */
    AST_RTP_INSTANCE_STAT_RXJITTER,
    /*! Retrieve maximum jitter on remote side */
    AST_RTP_INSTANCE_STAT_REMOTE_MAXJITTER,
    /*! Retrieve minimum jitter on remote side */
    AST_RTP_INSTANCE_STAT_REMOTE_MINJITTER,
    /*! Retrieve average jitter on remote side */
    AST_RTP_INSTANCE_STAT_REMOTE_NORMDEVJITTER,
    /*! Retrieve standard deviation jitter on remote side */
    AST_RTP_INSTANCE_STAT_REMOTE_STDEVJITTER,
    /*! Retrieve maximum jitter on local side */
    AST_RTP_INSTANCE_STAT_LOCAL_MAXJITTER,
    /*! Retrieve minimum jitter on local side */
    AST_RTP_INSTANCE_STAT_LOCAL_MINJITTER,
    /*! Retrieve average jitter on local side */
    AST_RTP_INSTANCE_STAT_LOCAL_NORMDEVJITTER,
    /*! Retrieve standard deviation jitter on local side */
    AST_RTP_INSTANCE_STAT_LOCAL_STDEVJITTER,
    /*! Retrieve ALL statistics relating to round trip time */
    AST_RTP_INSTANCE_STAT_COMBINED_RTT,
    /*! Retrieve round trip time */
    AST_RTP_INSTANCE_STAT_RTT,
    /*! Retrieve maximum round trip time */
    AST_RTP_INSTANCE_STAT_MAX_RTT,
    /*! Retrieve minimum round trip time */
    AST_RTP_INSTANCE_STAT_MIN_RTT,
    /*! Retrieve average round trip time */
    AST_RTP_INSTANCE_STAT_NORMDEVRTT,
    /*! Retrieve standard deviation round trip time */
    AST_RTP_INSTANCE_STAT_STDEVRTT,
    /*! Retrieve local SSRC */
    AST_RTP_INSTANCE_STAT_LOCAL_SSRC,
    /*! Retrieve remote SSRC */
    AST_RTP_INSTANCE_STAT_REMOTE_SSRC,
    /*! Retrieve channel unique ID */
    AST_RTP_INSTANCE_STAT_CHANNEL_UNIQUEID,
    /*! Retrieve number of octets transmitted */
    AST_RTP_INSTANCE_STAT_TXOCTETCOUNT,
    /*! Retrieve number of octets received */
    AST_RTP_INSTANCE_STAT_RXOCTETCOUNT,
 };
ast_rtp_instance_stat_field
enum ast_rtp_instance_stat_field
Field statistics that can be retrieved from an RTP instance
Enumerator
AST_RTP_INSTANCE_STAT_FIELD_QUALITY
Retrieve quality information
AST_RTP_INSTANCE_STAT_FIELD_QUALITY_JITTER
Retrieve quality information about jitter
AST_RTP_INSTANCE_STAT_FIELD_QUALITY_LOSS
Retrieve quality information about packet loss
AST_RTP_INSTANCE_STAT_FIELD_QUALITY_RTT
Retrieve quality information about round trip time
Definition at line 168 of file rtp_engine.h.
{
    /*! Retrieve quality information */
    AST_RTP_INSTANCE_STAT_FIELD_QUALITY = 0,
    /*! Retrieve quality information about jitter */
    AST_RTP_INSTANCE_STAT_FIELD_QUALITY_JITTER,
    /*! Retrieve quality information about packet loss */
    AST_RTP_INSTANCE_STAT_FIELD_QUALITY_LOSS,
    /*! Retrieve quality information about round trip time */
    AST_RTP_INSTANCE_STAT_FIELD_QUALITY_RTT,
 };
ast_rtp_options
enum ast_rtp_options
Additional RTP options
Enumerator
AST_RTP_OPT_G726_NONSTANDARD
Remote side is using non-standard G.726
Definition at line 142 of file rtp_engine.h.
                      {
    /*! Remote side is using non-standard G.726 */
    AST_RTP_OPT_G726_NONSTANDARD = (1 << 0),
 };
ast_rtp_property
enum ast_rtp_property
RTP Properties that can be set on an RTP instance
Enumerator
AST_RTP_PROPERTY_NAT
Enable symmetric RTP support
AST_RTP_PROPERTY_DTMF
RTP instance will be carrying DTMF (using RFC2833)
AST_RTP_PROPERTY_DTMF_COMPENSATE
Expect unreliable DTMF from remote party
AST_RTP_PROPERTY_STUN
Enable STUN support
AST_RTP_PROPERTY_RTCP
Enable RTCP support
AST_RTP_PROPERTY_ASYMMETRIC_CODEC
Enable Asymmetric RTP Codecs
AST_RTP_PROPERTY_RETRANS_RECV
Enable packet retransmission for received packets
AST_RTP_PROPERTY_RETRANS_SEND
Enable packet retransmission for sent packets
AST_RTP_PROPERTY_REMB
Enable REMB sending and receiving passthrough support
AST_RTP_PROPERTY_MAX
Maximum number of RTP properties supported.
Note
THIS MUST BE THE LAST ENTRY IN THIS ENUM.
Definition at line 113 of file rtp_engine.h.
                       {
    /*! Enable symmetric RTP support */
    AST_RTP_PROPERTY_NAT = 0,
    /*! RTP instance will be carrying DTMF (using RFC2833) */
    AST_RTP_PROPERTY_DTMF,
    /*! Expect unreliable DTMF from remote party */
    AST_RTP_PROPERTY_DTMF_COMPENSATE,
    /*! Enable STUN support */
    AST_RTP_PROPERTY_STUN,
    /*! Enable RTCP support */
    AST_RTP_PROPERTY_RTCP,
    /*! Enable Asymmetric RTP Codecs */
    AST_RTP_PROPERTY_ASYMMETRIC_CODEC,
    /*! Enable packet retransmission for received packets */
    AST_RTP_PROPERTY_RETRANS_RECV,
    /*! Enable packet retransmission for sent packets */
    AST_RTP_PROPERTY_RETRANS_SEND,
    /*! Enable REMB sending and receiving passthrough support */
    AST_RTP_PROPERTY_REMB,
    /*!
     * \brief Maximum number of RTP properties supported
     *
     * \note THIS MUST BE THE LAST ENTRY IN THIS ENUM.
     */
    AST_RTP_PROPERTY_MAX,
 };
Function Documentation
ast_rtp_codecs_find_payload_code()
int ast_rtp_codecs_find_payload_code (struct ast_rtp_codecs * codecs, int payload)
Search for the tx payload type in the ast_rtp_codecs structure.
Parameters
codecs Codecs structure to look in
payload The payload type format to look for
Return values
Numerical payload type or -1 if unable to find payload in codecs
Example usage:
int payload = ast_rtp_codecs_find_payload_code(&codecs, 0);
This looks for the numerical payload for ULAW in the codecs structure.
Definition at line 1975 of file rtp_engine.c.
References ast_rwlock_rdlock, ast_rwlock_unlock, AST_VECTOR_GET, AST_VECTOR_SIZE, ast_rtp_codecs::codecs_lock, ast_rtp_payload_type::payload, and type.
Referenced by bridge_p2p_rtp_write().
 {
    struct ast_rtp_payload_type *type;
    int res = -1;
    ast_rwlock_rdlock(&codecs->codecs_lock);
    if (payload < AST_VECTOR_SIZE(&codecs->payload_mapping_tx)) {
       type = AST_VECTOR_GET(&codecs->payload_mapping_tx, payload);
       if (type) {
          res = payload;
       }
    }
    ast_rwlock_unlock(&codecs->codecs_lock);
    return res;
 }
ast_rtp_codecs_get_framing()
unsigned int ast_rtp_codecs_get_framing (struct ast_rtp_codecs * codecs)
Get the framing used for a set of codecs.
Parameters
codecs Codecs structure to get the framing from
Return values
The framing to be used for the media stream associated with these codecs
Since
13.0.0
Definition at line 1569 of file rtp_engine.c.
References ast_rwlock_rdlock, ast_rwlock_unlock, ast_rtp_codecs::codecs_lock, and ast_rtp_codecs::framing.
Referenced by ast_rtp_write(), create_outgoing_sdp_stream(), multicast_rtp_write(), native_rtp_bridge_compatible_check(), and process_sdp().
 {
    unsigned int framing;
    ast_rwlock_rdlock(&codecs->codecs_lock);
    framing = codecs->framing;
    ast_rwlock_unlock(&codecs->codecs_lock);
    return framing;
 }
ast_rtp_codecs_get_payload()
struct ast_rtp_payload_type* ast_rtp_codecs_get_payload (struct ast_rtp_codecs * codecs, int payload)
Retrieve rx payload mapped information by payload type.
Parameters
codecs Codecs structure to look in
payload Numerical payload to look up
Return values
Payload information.
NULL if payload does not exist.
Note
The payload returned by this function has its reference count increased. Callers are responsible for decrementing the reference count.
Example usage:
struct ast_rtp_payload_type *payload_type;
payload_type = ast_rtp_codecs_get_payload(&codecs, 0);
This looks up the information for payload '0' from the codecs structure.
Definition at line 1479 of file rtp_engine.c.
References ao2_bump, AST_RTP_MAX_PT, AST_RTP_PT_LAST_STATIC, ast_rwlock_rdlock, ast_rwlock_unlock, AST_VECTOR_GET, AST_VECTOR_SIZE, ast_rtp_codecs::codecs_lock, NULL, and type.
Referenced by ast_rtp_interpret(), and bridge_p2p_rtp_write().
 {
    struct ast_rtp_payload_type *type = NULL;
    if (payload < 0 || payload >= AST_RTP_MAX_PT) {
       return NULL;
    }
    ast_rwlock_rdlock(&codecs->codecs_lock);
    if (payload < AST_VECTOR_SIZE(&codecs->payload_mapping_rx)) {
       type = AST_VECTOR_GET(&codecs->payload_mapping_rx, payload);
       ao2_bump(type);
    }
    ast_rwlock_unlock(&codecs->codecs_lock);
    if (!type && payload <= AST_RTP_PT_LAST_STATIC) {
       ast_rwlock_rdlock(&static_RTP_PT_lock);
       type = ao2_bump(static_RTP_PT[payload]);
       ast_rwlock_unlock(&static_RTP_PT_lock);
    }
    return type;
 }
ast_rtp_codecs_get_payload_format()
struct ast_format* ast_rtp_codecs_get_payload_format (struct ast_rtp_codecs * codecs, int payload)
Retrieve the actual ast_format stored on the codecs structure for a specific tx payload type.
Parameters
codecs Codecs structure to look in
payload Numerical payload type to look up
Return values
pointer to format structure on success
NULL on failure
Note
The format returned by this function has its reference count increased. Callers are responsible for decrementing the reference count.
Since
10.0
Definition at line 1537 of file rtp_engine.c.
References ao2_bump, AST_RTP_MAX_PT, ast_rwlock_rdlock, ast_rwlock_unlock, AST_VECTOR_GET, AST_VECTOR_SIZE, ast_rtp_payload_type::asterisk_format, ast_rtp_codecs::codecs_lock, format, ast_rtp_payload_type::format, NULL, and type.
Referenced by get_codecs(), process_sdp_a_audio(), and process_sdp_a_video().
 {
    struct ast_rtp_payload_type *type;
    struct ast_format *format = NULL;
    if (payload < 0 || payload >= AST_RTP_MAX_PT) {
       return NULL;
    }
    ast_rwlock_rdlock(&codecs->codecs_lock);
    if (payload < AST_VECTOR_SIZE(&codecs->payload_mapping_tx)) {
       type = AST_VECTOR_GET(&codecs->payload_mapping_tx, payload);
       if (type && type->asterisk_format) {
          format = ao2_bump(type->format);
       }
    }
    ast_rwlock_unlock(&codecs->codecs_lock);
    return format;
 }
ast_rtp_codecs_get_stream_type()
enum ast_media_type ast_rtp_codecs_get_stream_type (struct ast_rtp_codecs * codecs)
Determine the type of RTP stream media from the codecs mapped.
Since
13.19.0
Parameters
codecs Codecs structure to look in
Returns
Media type or AST_MEDIA_TYPE_UNKNOWN if no codecs mapped.
Definition at line 1460 of file rtp_engine.c.
References ast_format_get_type(), AST_MEDIA_TYPE_UNKNOWN, ast_rwlock_rdlock, ast_rwlock_unlock, AST_VECTOR_GET, AST_VECTOR_SIZE, ast_rtp_payload_type::asterisk_format, ast_rtp_codecs::codecs_lock, ast_rtp_payload_type::format, ast_rtp_payload_type::payload, and type.
Referenced by ast_rtp_read().
 {
    enum ast_media_type stream_type = AST_MEDIA_TYPE_UNKNOWN;
    int payload;
    struct ast_rtp_payload_type *type;
    ast_rwlock_rdlock(&codecs->codecs_lock);
    for (payload = 0; payload < AST_VECTOR_SIZE(&codecs->payload_mapping_rx); ++payload) {
       type = AST_VECTOR_GET(&codecs->payload_mapping_rx, payload);
       if (type && type->asterisk_format) {
          stream_type = ast_format_get_type(type->format);
          break;
       }
    }
    ast_rwlock_unlock(&codecs->codecs_lock);
    return stream_type;
 }
ast_rtp_codecs_payload_code()
int ast_rtp_codecs_payload_code (struct ast_rtp_codecs * codecs, int asterisk_format, struct ast_format * format, int code)
Retrieve a rx mapped payload type based on whether it is an Asterisk format and the code.
Parameters
codecs Codecs structure to look in
asterisk_format Non-zero if the given Asterisk format is present
format Asterisk format to look for
code The format to look for
Find the currently assigned rx mapped payload type based on whether it is an Asterisk format or non-format code. If one is currently not assigned then create a rx payload type mapping.
Return values
Numerical payload type
-1 if could not assign.
Example usage:
int payload = ast_rtp_codecs_payload_code(&codecs, 1, ast_format_set(&tmp_fmt, AST_FORMAT_ULAW, 0), 0);
This looks for the numerical payload for ULAW in the codecs structure.
Since
1.8
Definition at line 1873 of file rtp_engine.c.
References ast_format_cmp(), AST_FORMAT_CMP_EQUAL, ast_rwlock_rdlock, ast_rwlock_unlock, AST_VECTOR_GET, AST_VECTOR_SIZE, ast_rtp_payload_type::asterisk_format, ast_rtp_codecs::codecs_lock, ast_rtp_payload_type::format, ast_rtp_payload_type::payload, ast_rtp_payload_type::primary_mapping, ast_rtp_payload_type::rtp_code, rtp_codecs_assign_payload_code_rx(), and type.
Referenced by add_codec_to_sdp(), add_noncodec_to_sdp(), add_sdp(), add_tcodec_to_sdp(), add_vcodec_to_sdp(), apply_cap_to_bundled(), create_outgoing_sdp_stream(), and jingle_add_payloads_to_description().
 {
    struct ast_rtp_payload_type *type;
    int idx;
    int payload = -1;
    ast_rwlock_rdlock(&static_RTP_PT_lock);
    if (!asterisk_format) {
       ast_rwlock_rdlock(&codecs->codecs_lock);
       for (idx = 0; idx < AST_VECTOR_SIZE(&codecs->payload_mapping_rx); ++idx) {
          type = AST_VECTOR_GET(&codecs->payload_mapping_rx, idx);
          if (!type) {
             continue;
          }
          if (!type->asterisk_format
             && type->primary_mapping
             && type->rtp_code == code) {
             payload = idx;
             break;
          }
       }
       ast_rwlock_unlock(&codecs->codecs_lock);
    } else if (format) {
       ast_rwlock_rdlock(&codecs->codecs_lock);
       for (idx = 0; idx < AST_VECTOR_SIZE(&codecs->payload_mapping_rx); ++idx) {
          type = AST_VECTOR_GET(&codecs->payload_mapping_rx, idx);
          if (!type) {
             continue;
          }
          if (type->asterisk_format
             && type->primary_mapping
             && ast_format_cmp(format, type->format) == AST_FORMAT_CMP_EQUAL) {
             payload = idx;
             break;
          }
       }
       ast_rwlock_unlock(&codecs->codecs_lock);
    }
    if (payload < 0) {
       payload = rtp_codecs_assign_payload_code_rx(codecs, asterisk_format, format,
          code, 0);
    }
    ast_rwlock_unlock(&static_RTP_PT_lock);
    return payload;
 }
ast_rtp_codecs_payload_code_tx()
int ast_rtp_codecs_payload_code_tx (struct ast_rtp_codecs * codecs, int asterisk_format, const struct ast_format * format, int code)
Retrieve a tx mapped payload type based on whether it is an Asterisk format and the code.
Since
14.0.0
Parameters
codecs Codecs structure to look in
asterisk_format Non-zero if the given Asterisk format is present
format Asterisk format to look for
code The format to look for
Return values
Numerical payload type
-1 if not found.
Definition at line 1928 of file rtp_engine.c.
References ast_format_cmp(), AST_FORMAT_CMP_EQUAL, ast_rwlock_rdlock, ast_rwlock_unlock, AST_VECTOR_GET, AST_VECTOR_SIZE, ast_rtp_payload_type::asterisk_format, ast_rtp_codecs::codecs_lock, find_static_payload_type(), ast_rtp_payload_type::format, ast_rtp_payload_type::payload, ast_rtp_payload_type::rtp_code, and type.
Referenced by ast_rtp_dtmf_begin(), ast_rtp_sendcng(), ast_rtp_write(), bridge_p2p_rtp_write(), multicast_rtp_write(), and send_start_rtp().
 {
    struct ast_rtp_payload_type *type;
    int idx;
    int payload = -1;
    if (!asterisk_format) {
       ast_rwlock_rdlock(&codecs->codecs_lock);
       for (idx = 0; idx < AST_VECTOR_SIZE(&codecs->payload_mapping_tx); ++idx) {
          type = AST_VECTOR_GET(&codecs->payload_mapping_tx, idx);
          if (!type) {
             continue;
          }
          if (!type->asterisk_format
             && type->rtp_code == code) {
             payload = idx;
             break;
          }
       }
       ast_rwlock_unlock(&codecs->codecs_lock);
    } else if (format) {
       ast_rwlock_rdlock(&codecs->codecs_lock);
       for (idx = 0; idx < AST_VECTOR_SIZE(&codecs->payload_mapping_tx); ++idx) {
          type = AST_VECTOR_GET(&codecs->payload_mapping_tx, idx);
          if (!type) {
             continue;
          }
          if (type->asterisk_format
             && ast_format_cmp(format, type->format) == AST_FORMAT_CMP_EQUAL) {
             payload = idx;
             break;
          }
       }
       ast_rwlock_unlock(&codecs->codecs_lock);
    }
    if (payload < 0) {
       ast_rwlock_rdlock(&static_RTP_PT_lock);
       payload = find_static_payload_type(asterisk_format, format, code);
       ast_rwlock_unlock(&static_RTP_PT_lock);
    }
    return payload;
 }
ast_rtp_codecs_payload_formats()
void ast_rtp_codecs_payload_formats (struct ast_rtp_codecs * codecs, struct ast_format_cap * astformats, int * nonastformats)
Retrieve all formats that were found.
Parameters
codecs Codecs structure to look in
astformats A capabilities structure to put the Asterisk formats in.
nonastformats An integer to put the non-Asterisk formats in
Example usage:
struct ast_format_cap *astformats = ast_format_cap_alloc_nolock()
int nonastformats;
ast_rtp_codecs_payload_formats(&codecs, astformats, &nonastformats);
This retrieves all the formats known about in the codecs structure and puts the Asterisk ones in the integer pointed to by astformats and the non-Asterisk ones in the integer pointed to by nonastformats.
Since
1.8
Definition at line 1580 of file rtp_engine.c.
References ast_format_cap_append, ast_format_cap_remove_by_type(), ast_format_cap_set_framing(), AST_MEDIA_TYPE_UNKNOWN, ast_rwlock_rdlock, ast_rwlock_unlock, AST_VECTOR_GET, AST_VECTOR_SIZE, ast_rtp_payload_type::asterisk_format, ast_rtp_codecs::codecs_lock, ast_rtp_payload_type::format, ast_rtp_codecs::framing, ast_rtp_payload_type::rtp_code, and type.
Referenced by jingle_interpret_description(), process_sdp(), set_caps(), and set_incoming_call_offer_cap().
 {
    int idx;
    ast_format_cap_remove_by_type(astformats, AST_MEDIA_TYPE_UNKNOWN);
    *nonastformats = 0;
    ast_rwlock_rdlock(&codecs->codecs_lock);
    for (idx = 0; idx < AST_VECTOR_SIZE(&codecs->payload_mapping_tx); ++idx) {
       struct ast_rtp_payload_type *type;
       type = AST_VECTOR_GET(&codecs->payload_mapping_tx, idx);
       if (!type) {
          continue;
       }
       if (type->asterisk_format) {
          ast_format_cap_append(astformats, type->format, 0);
       } else {
          *nonastformats |= type->rtp_code;
       }
    }
    if (codecs->framing) {
       ast_format_cap_set_framing(astformats, codecs->framing);
    }
    ast_rwlock_unlock(&codecs->codecs_lock);
 }
ast_rtp_codecs_payload_replace_format()
int ast_rtp_codecs_payload_replace_format (struct ast_rtp_codecs * codecs, int payload, struct ast_format * format)
Update the format associated with a tx payload type in a codecs structure.
Parameters
codecs Codecs structure to operate on
payload Numerical payload type to look up
format The format to replace the existing one
Return values
0 success
-1 failure
Since
13
Definition at line 1503 of file rtp_engine.c.
References ao2_cleanup, ao2_ref, ast_rtp_engine_alloc_payload_type(), AST_RTP_MAX_PT, ast_rwlock_unlock, ast_rwlock_wrlock, AST_VECTOR_GET, AST_VECTOR_REPLACE, AST_VECTOR_SIZE, ast_rtp_payload_type::asterisk_format, ast_rtp_codecs::codecs_lock, format, ast_rtp_payload_type::format, ast_rtp_payload_type::payload, payload_mapping_tx_is_present(), ast_rtp_payload_type::primary_mapping, and type.
Referenced by get_codecs(), process_sdp_a_audio(), and process_sdp_a_video().
 {
    struct ast_rtp_payload_type *type;
    if (payload < 0 || payload >= AST_RTP_MAX_PT || !format) {
       return -1;
    }
    type = ast_rtp_engine_alloc_payload_type();
    if (!type) {
       return -1;
    }
    ao2_ref(format, +1);
    type->format = format;
    type->asterisk_format = 1;
    type->payload = payload;
    type->primary_mapping = 1;
    ast_rwlock_wrlock(&codecs->codecs_lock);
    if (!payload_mapping_tx_is_present(codecs, type)) {
       if (payload < AST_VECTOR_SIZE(&codecs->payload_mapping_tx)) {
          ao2_cleanup(AST_VECTOR_GET(&codecs->payload_mapping_tx, payload));
       }
       if (AST_VECTOR_REPLACE(&codecs->payload_mapping_tx, payload, type)) {
          ao2_ref(type, -1);
       }
    } else {
       ao2_ref(type, -1);
    }
    ast_rwlock_unlock(&codecs->codecs_lock);
    return 0;
 }
ast_rtp_codecs_payload_set_rx()
int ast_rtp_codecs_payload_set_rx (struct ast_rtp_codecs * codecs, int code, struct ast_format * format)
Set a payload code for use with a specific Asterisk format.
Parameters
codecs Codecs structure to manipulate
code The payload code
format Asterisk format
Return values
0 Payload was set to the given format
-1 Payload was in use or could not be set
Since
15.0.0
Definition at line 1923 of file rtp_engine.c.
References rtp_codecs_assign_payload_code_rx().
Referenced by apply_cap_to_bundled(), and create_outgoing_sdp_stream().
 {
    return rtp_codecs_assign_payload_code_rx(codecs, 1, format, code, 1);
 }
ast_rtp_codecs_payloads_clear()
void ast_rtp_codecs_payloads_clear (struct ast_rtp_codecs * codecs, struct ast_rtp_instance * instance)
Clear rx and tx payload mapping information from an RTP instance.
Parameters
codecs The codecs structure that payloads will be cleared from
instance Optionally the instance that the codecs structure belongs to
Example usage:
struct ast_rtp_codecs codecs;
ast_rtp_codecs_payloads_clear(&codecs, NULL);
This clears the codecs structure and puts it into a pristine state.
Since
1.8
Definition at line 994 of file rtp_engine.c.
References ao2_lock, ao2_unlock, ast_rtp_codecs_payloads_destroy(), ast_rtp_codecs_payloads_initialize(), AST_RTP_MAX_PT, ast_rtp_instance::engine, NULL, and ast_rtp_engine::payload_set.
 {
    ast_rtp_codecs_payloads_destroy(codecs);
    ast_rtp_codecs_payloads_initialize(codecs);
    if (instance && instance->engine && instance->engine->payload_set) {
       int i;
       ao2_lock(instance);
       for (i = 0; i < AST_RTP_MAX_PT; i++) {
          instance->engine->payload_set(instance, i, 0, NULL, 0);
       }
       ao2_unlock(instance);
    }
 }
ast_rtp_codecs_payloads_copy()
void ast_rtp_codecs_payloads_copy (struct ast_rtp_codecs * src, struct ast_rtp_codecs * dest, struct ast_rtp_instance * instance)
Copy payload information from one RTP instance to another.
Parameters
src The source codecs structure
dest The destination codecs structure that the values from src will be copied to
instance Optionally the instance that the dst codecs structure belongs to
Example usage:
ast_rtp_codecs_payloads_copy(&codecs0, &codecs1, NULL);
This copies the payloads from the codecs0 structure to the codecs1 structure, overwriting any current values.
Since
1.8
Definition at line 1224 of file rtp_engine.c.
References ao2_t_cleanup, ast_rwlock_tryrdlock, ast_rwlock_unlock, ast_rwlock_wrlock, AST_VECTOR_GET, AST_VECTOR_REPLACE, AST_VECTOR_SIZE, ast_rtp_codecs::codecs_lock, ast_rtp_codecs::framing, NULL, rtp_codecs_payloads_copy_rx(), rtp_codecs_payloads_copy_tx(), and type.
Referenced by jingle_interpret_description(), process_sdp(), set_caps(), and set_incoming_call_offer_cap().
 {
    int idx;
    struct ast_rtp_payload_type *type;
    ast_rwlock_wrlock(&dest->codecs_lock);
    /* Deadlock avoidance because of held write lock. */
    while (ast_rwlock_tryrdlock(&src->codecs_lock)) {
       ast_rwlock_unlock(&dest->codecs_lock);
       sched_yield();
       ast_rwlock_wrlock(&dest->codecs_lock);
    }
    /*
     * This represents a completely new mapping of what the remote party is
     * expecting for payloads, so we clear out the entire tx payload mapping
     * vector and replace it.
     */
    for (idx = 0; idx < AST_VECTOR_SIZE(&dest->payload_mapping_tx); ++idx) {
       type = AST_VECTOR_GET(&dest->payload_mapping_tx, idx);
       ao2_t_cleanup(type, "destroying ast_rtp_codec tx mapping");
       AST_VECTOR_REPLACE(&dest->payload_mapping_tx, idx, NULL);
    }
    rtp_codecs_payloads_copy_rx(src, dest, instance);
    rtp_codecs_payloads_copy_tx(src, dest, instance);
    dest->framing = src->framing;
    ast_rwlock_unlock(&src->codecs_lock);
    ast_rwlock_unlock(&dest->codecs_lock);
 }
ast_rtp_codecs_payloads_destroy()
void ast_rtp_codecs_payloads_destroy (struct ast_rtp_codecs * codecs)
Destroy the contents of an RTP codecs structure (but not the structure itself)
Parameters
codecs The codecs structure to destroy the contents of
Example usage:
struct ast_rtp_codecs codecs;
ast_rtp_codecs_payloads_destroy(&codecs);
Since
11
Definition at line 974 of file rtp_engine.c.
References ao2_t_cleanup, ast_rwlock_destroy, AST_VECTOR_FREE, AST_VECTOR_GET, AST_VECTOR_SIZE, ast_rtp_codecs::codecs_lock, and type.
Referenced by ast_rtp_codecs_payloads_clear(), ast_stream_free(), ast_stream_set_rtp_codecs(), instance_destructor(), jingle_interpret_description(), process_sdp(), set_caps(), and set_incoming_call_offer_cap().
 {
    int idx;
    struct ast_rtp_payload_type *type;
    for (idx = 0; idx < AST_VECTOR_SIZE(&codecs->payload_mapping_rx); ++idx) {
       type = AST_VECTOR_GET(&codecs->payload_mapping_rx, idx);
       ao2_t_cleanup(type, "destroying ast_rtp_codec rx mapping");
    }
    AST_VECTOR_FREE(&codecs->payload_mapping_rx);
    for (idx = 0; idx < AST_VECTOR_SIZE(&codecs->payload_mapping_tx); ++idx) {
       type = AST_VECTOR_GET(&codecs->payload_mapping_tx, idx);
       ao2_t_cleanup(type, "destroying ast_rtp_codec tx mapping");
    }
    AST_VECTOR_FREE(&codecs->payload_mapping_tx);
    ast_rwlock_destroy(&codecs->codecs_lock);
 }
ast_rtp_codecs_payloads_initialize()
int ast_rtp_codecs_payloads_initialize (struct ast_rtp_codecs * codecs)
Initialize an RTP codecs structure.
Parameters
codecs The codecs structure to initialize
Return values
0 success
-1 failure
Example usage:
struct ast_rtp_codecs codecs;
ast_rtp_codecs_payloads_initialize(&codecs);
Since
11
Definition at line 958 of file rtp_engine.c.
References AST_RTP_MAX_PT, ast_rwlock_init, AST_VECTOR_FREE, AST_VECTOR_INIT, ast_rtp_codecs::codecs_lock, and ast_rtp_codecs::framing.
Referenced by ast_rtp_codecs_payloads_clear(), ast_rtp_instance_new(), get_codecs(), jingle_interpret_description(), and process_sdp().
 {
    int res;
    codecs->framing = 0;
    ast_rwlock_init(&codecs->codecs_lock);
    res = AST_VECTOR_INIT(&codecs->payload_mapping_rx, AST_RTP_MAX_PT);
    res |= AST_VECTOR_INIT(&codecs->payload_mapping_tx, AST_RTP_MAX_PT);
    if (res) {
       AST_VECTOR_FREE(&codecs->payload_mapping_rx);
       AST_VECTOR_FREE(&codecs->payload_mapping_tx);
    }
    return res;
 }
ast_rtp_codecs_payloads_set_m_type()
void ast_rtp_codecs_payloads_set_m_type (struct ast_rtp_codecs * codecs, struct ast_rtp_instance * instance, int payload)
Record tx payload type information that was seen in an m= SDP line.
Parameters
codecs The codecs structure to muck with
instance Optionally the instance that the codecs structure belongs to
payload Numerical payload that was seen in the m= SDP line
Example usage:
ast_rtp_codecs_payloads_set_m_type(&codecs, NULL, 0);
This records that the numerical payload '0' was seen in the codecs structure.
Since
1.8
Definition at line 1301 of file rtp_engine.c.
References ao2_bump, ao2_lock, ao2_ref, ao2_t_cleanup, ao2_unlock, ast_debug, AST_RTP_MAX_PT, AST_RTP_PT_LAST_STATIC, ast_rwlock_rdlock, ast_rwlock_unlock, ast_rwlock_wrlock, AST_VECTOR_GET, AST_VECTOR_REPLACE, AST_VECTOR_SIZE, ast_rtp_payload_type::asterisk_format, ast_rtp_codecs::codecs_lock, ast_rtp_instance::engine, ast_rtp_payload_type::format, 10aedae86a32_add_outgoing_enum_va::new_type, payload_mapping_tx_is_present(), ast_rtp_engine::payload_set, and ast_rtp_payload_type::rtp_code.
Referenced by get_codecs(), and process_sdp().
 {
    struct ast_rtp_payload_type *new_type;
    if (payload < 0 || payload >= AST_RTP_MAX_PT || payload > AST_RTP_PT_LAST_STATIC) {
       return;
    }
    ast_rwlock_rdlock(&static_RTP_PT_lock);
    new_type = ao2_bump(static_RTP_PT[payload]);
    ast_rwlock_unlock(&static_RTP_PT_lock);
    if (!new_type) {
       ast_debug(1, "Don't have a default tx payload type %d format for m type on %p\n",
          payload, codecs);
       return;
    }
    ast_debug(1, "Setting tx payload type %d based on m type on %p\n",
       payload, codecs);
    ast_rwlock_wrlock(&codecs->codecs_lock);
    if (!payload_mapping_tx_is_present(codecs, new_type)) {
       if (payload < AST_VECTOR_SIZE(&codecs->payload_mapping_tx)) {
          ao2_t_cleanup(AST_VECTOR_GET(&codecs->payload_mapping_tx, payload),
             "cleaning up replaced tx payload type");
       }
       if (AST_VECTOR_REPLACE(&codecs->payload_mapping_tx, payload, new_type)) {
          ao2_ref(new_type, -1);
       } else if (instance && instance->engine && instance->engine->payload_set) {
          ao2_lock(instance);
          instance->engine->payload_set(instance, payload, new_type->asterisk_format, new_type->format, new_type->rtp_code);
          ao2_unlock(instance);
       }
    } else {
       ao2_ref(new_type, -1);
    }
    ast_rwlock_unlock(&codecs->codecs_lock);
 }
ast_rtp_codecs_payloads_set_rtpmap_type()
int ast_rtp_codecs_payloads_set_rtpmap_type (struct ast_rtp_codecs * codecs, struct ast_rtp_instance * instance, int payload, char * mimetype, char * mimesubtype, enum ast_rtp_options options)
Record tx payload type information that was seen in an a=rtpmap: SDP line.
Parameters
codecs The codecs structure to muck with
instance Optionally the instance that the codecs structure belongs to
payload Numerical payload that was seen in the a=rtpmap: SDP line
mimetype The string mime type that was seen
mimesubtype The strin mime sub type that was seen
options Optional options that may change the behavior of this specific payload
Return values
0 success
-1 failure, invalid payload numbe
-2 failure, unknown mimetype
Example usage:
ast_rtp_codecs_payloads_set_rtpmap_type(&codecs, NULL, 0, "audio", "PCMU", 0);
This records that the numerical payload '0' was seen with mime type 'audio' and sub mime type 'PCMU' in the codecs structure.
Since
1.8
Definition at line 1428 of file rtp_engine.c.
References ast_rtp_codecs_payloads_set_rtpmap_type_rate().
Referenced by configure_local_rtp(), jingle_interpret_description(), ooh323_set_write_format(), process_sdp(), and setup_rtp_connection().
 {
    return ast_rtp_codecs_payloads_set_rtpmap_type_rate(codecs, instance, payload, mimetype, mimesubtype, options, 0);
 }
ast_rtp_codecs_payloads_set_rtpmap_type_rate()
int ast_rtp_codecs_payloads_set_rtpmap_type_rate (struct ast_rtp_codecs * codecs, struct ast_rtp_instance * instance, int pt, char * mimetype, char * mimesubtype, enum ast_rtp_options options, unsigned int sample_rate)
Set tx payload type to a known MIME media type for a codec with a specific sample rate.
Parameters
codecs RTP structure to modify
instance Optionally the instance that the codecs structure belongs to
pt Payload type entry to modify
mimetype top-level MIME type of media stream (typically "audio", "video", "text", etc.)
mimesubtype MIME subtype of media stream (typically a codec name)
options Zero or more flags from the ast_rtp_options enum
sample_rate The sample rate of the media stream
This function 'fills in' an entry in the list of possible formats for a media stream associated with an RTP structure.
Return values
0 on success
-1 if the payload type is out of range
-2 if the mimeType/mimeSubtype combination was not found
Since
1.8
Definition at line 1343 of file rtp_engine.c.
References ao2_lock, ao2_ref, ao2_t_cleanup, ao2_unlock, ast_format_cmp(), AST_FORMAT_CMP_EQUAL, ast_format_g726, ast_format_g726_aal2, ast_format_parse_sdp_fmtp(), ast_rtp_engine_alloc_payload_type(), AST_RTP_MAX_PT, ast_rtp_mime_types, AST_RTP_OPT_G726_NONSTANDARD, ast_rwlock_rdlock, ast_rwlock_unlock, ast_rwlock_wrlock, AST_VECTOR_GET, AST_VECTOR_REPLACE, AST_VECTOR_SIZE, ast_rtp_payload_type::asterisk_format, ast_rtp_codecs::codecs_lock, ast_rtp_instance::engine, ast_rtp_payload_type::format, mime_types_len, 10aedae86a32_add_outgoing_enum_va::new_type, ast_rtp_payload_type::payload, payload_mapping_tx_is_present(), ast_rtp_engine::payload_set, ast_rtp_mime_type::payload_type, ast_rtp_payload_type::primary_mapping, ast_rtp_payload_type::rtp_code, ast_rtp_mime_type::sample_rate, ast_rtp_mime_type::subtype, and ast_rtp_mime_type::type.
Referenced by ast_rtp_codecs_payloads_set_rtpmap_type(), get_codecs(), jingle_interpret_description(), process_sdp_a_audio(), process_sdp_a_text(), and process_sdp_a_video().
 {
    unsigned int idx;
    int found = 0;
    if (pt < 0 || pt >= AST_RTP_MAX_PT) {
       return -1; /* bogus payload type */
    }
    ast_rwlock_rdlock(&mime_types_lock);
    ast_rwlock_wrlock(&codecs->codecs_lock);
    for (idx = 0; idx < mime_types_len; ++idx) {
       const struct ast_rtp_mime_type *t = &ast_rtp_mime_types[idx];
       struct ast_rtp_payload_type *new_type;
       if (strcasecmp(mimesubtype, t->subtype)) {
          continue;
       }
       if (strcasecmp(mimetype, t->type)) {
          continue;
       }
       /* if both sample rates have been supplied, and they don't match,
        * then this not a match; if one has not been supplied, then the
        * rates are not compared */
       if (sample_rate && t->sample_rate &&
           (sample_rate != t->sample_rate)) {
          continue;
       }
       found = 1;
       new_type = ast_rtp_engine_alloc_payload_type();
       if (!new_type) {
          continue;
       }
       new_type->asterisk_format = t->payload_type.asterisk_format;
       new_type->rtp_code = t->payload_type.rtp_code;
       new_type->payload = pt;
       new_type->primary_mapping = 1;
       if (t->payload_type.asterisk_format
          && ast_format_cmp(t->payload_type.format, ast_format_g726) == AST_FORMAT_CMP_EQUAL
          && (options & AST_RTP_OPT_G726_NONSTANDARD)) {
          new_type->format = ast_format_g726_aal2;
       } else {
          new_type->format = t->payload_type.format;
       }
       if (new_type->format) {
          /* SDP parsing automatically increases the reference count */
          new_type->format = ast_format_parse_sdp_fmtp(new_type->format, "");
       }
       if (!payload_mapping_tx_is_present(codecs, new_type)) {
          if (pt < AST_VECTOR_SIZE(&codecs->payload_mapping_tx)) {
             ao2_t_cleanup(AST_VECTOR_GET(&codecs->payload_mapping_tx, pt),
                "cleaning up replaced tx payload type");
          }
          if (AST_VECTOR_REPLACE(&codecs->payload_mapping_tx, pt, new_type)) {
             ao2_ref(new_type, -1);
          } else if (instance && instance->engine && instance->engine->payload_set) {
             ao2_lock(instance);
             instance->engine->payload_set(instance, pt, new_type->asterisk_format, new_type->format, new_type->rtp_code);
             ao2_unlock(instance);
          }
       } else {
          ao2_ref(new_type, -1);
       }
       break;
    }
    ast_rwlock_unlock(&codecs->codecs_lock);
    ast_rwlock_unlock(&mime_types_lock);
    return (found ? 0 : -2);
 }
ast_rtp_codecs_payloads_unset()
void ast_rtp_codecs_payloads_unset (struct ast_rtp_codecs * codecs, struct ast_rtp_instance * instance, int payload)
Remove tx payload type mapped information.
Parameters
codecs The codecs structure to muck with
instance Optionally the instance that the codecs structure belongs to
payload Numerical payload to unset
Example usage:
ast_rtp_codecs_payloads_unset(&codecs, NULL, 0);
This clears the payload '0' from the codecs structure. It will be as if it was never set.
Since
1.8
Definition at line 1433 of file rtp_engine.c.
References ao2_cleanup, ao2_lock, ao2_unlock, ast_debug, AST_RTP_MAX_PT, ast_rwlock_unlock, ast_rwlock_wrlock, AST_VECTOR_GET, AST_VECTOR_REPLACE, AST_VECTOR_SIZE, ast_rtp_codecs::codecs_lock, ast_rtp_instance::engine, NULL, ast_rtp_engine::payload_set, and type.
Referenced by process_sdp_a_audio(), and process_sdp_a_video().
 {
    struct ast_rtp_payload_type *type;
    if (payload < 0 || payload >= AST_RTP_MAX_PT) {
       return;
    }
    ast_debug(2, "Unsetting payload %d on %p\n", payload, codecs);
    ast_rwlock_wrlock(&codecs->codecs_lock);
    if (payload < AST_VECTOR_SIZE(&codecs->payload_mapping_tx)) {
       type = AST_VECTOR_GET(&codecs->payload_mapping_tx, payload);
       ao2_cleanup(type);
       AST_VECTOR_REPLACE(&codecs->payload_mapping_tx, payload, NULL);
    }
    if (instance && instance->engine && instance->engine->payload_set) {
       ao2_lock(instance);
       instance->engine->payload_set(instance, payload, 0, NULL, 0);
       ao2_unlock(instance);
    }
    ast_rwlock_unlock(&codecs->codecs_lock);
 }
ast_rtp_codecs_payloads_xover()
void ast_rtp_codecs_payloads_xover (struct ast_rtp_codecs * src, struct ast_rtp_codecs * dest, struct ast_rtp_instance * instance)
Crossover copy the tx payload mapping of src to the rx payload mapping of dest.
Since
14.0.0
Parameters
src The source codecs structure
dest The destination codecs structure that the values from src will be copied to
instance Optionally the instance that the dst codecs structure belongs to
Returns
Nothing
Definition at line 1257 of file rtp_engine.c.
References ao2_lock, ao2_unlock, ast_assert, ast_debug, ast_rwlock_tryrdlock, ast_rwlock_unlock, ast_rwlock_wrlock, AST_VECTOR_GET, AST_VECTOR_SIZE, ast_rtp_payload_type::asterisk_format, ast_rtp_codecs::codecs_lock, ast_rtp_instance::engine, ast_rtp_payload_type::format, ast_rtp_codecs::framing, ast_rtp_engine::payload_set, ast_rtp_payload_type::primary_mapping, ast_rtp_payload_type::rtp_code, rtp_codecs_payload_replace_rx(), and type.
Referenced by ast_rtp_instance_early_bridge_make_compatible(), process_sdp(), set_caps(), and set_incoming_call_offer_cap().
 {
    int idx;
    struct ast_rtp_payload_type *type;
    ast_rwlock_wrlock(&dest->codecs_lock);
    if (src != dest) {
       /* Deadlock avoidance because of held write lock. */
       while (ast_rwlock_tryrdlock(&src->codecs_lock)) {
          ast_rwlock_unlock(&dest->codecs_lock);
          sched_yield();
          ast_rwlock_wrlock(&dest->codecs_lock);
       }
    }
    /* Crossover copy payload type tx mapping to rx mapping. */
    for (idx = 0; idx < AST_VECTOR_SIZE(&src->payload_mapping_tx); ++idx) {
       type = AST_VECTOR_GET(&src->payload_mapping_tx, idx);
       if (!type) {
          continue;
       }
       /* All tx mapping elements should have the primary flag set. */
       ast_assert(type->primary_mapping);
       ast_debug(2, "Crossover copying tx to rx payload mapping %d (%p) from %p to %p\n",
          idx, type, src, dest);
       rtp_codecs_payload_replace_rx(dest, idx, type);
       if (instance && instance->engine && instance->engine->payload_set) {
          ao2_lock(instance);
          instance->engine->payload_set(instance, idx, type->asterisk_format, type->format, type->rtp_code);
          ao2_unlock(instance);
       }
    }
    dest->framing = src->framing;
    if (src != dest) {
       ast_rwlock_unlock(&src->codecs_lock);
    }
    ast_rwlock_unlock(&dest->codecs_lock);
 }
ast_rtp_codecs_set_framing()
void ast_rtp_codecs_set_framing (struct ast_rtp_codecs * codecs, unsigned int framing)
Set the framing used for a set of codecs.
Parameters
codecs Codecs structure to set framing on
framing The framing value to set on the codecs
Since
13.0.0
Definition at line 1558 of file rtp_engine.c.
References ast_rwlock_unlock, ast_rwlock_wrlock, ast_rtp_codecs::codecs_lock, and ast_rtp_codecs::framing.
Referenced by add_sdp(), check_peer_ok(), configure_local_rtp(), create_addr_from_peer(), get_codecs(), jingle_enable_video(), jingle_new(), process_sdp(), process_sdp_a_audio(), and start_rtp().
 {
    if (!framing) {
       return;
    }
    ast_rwlock_wrlock(&codecs->codecs_lock);
    codecs->framing = framing;
    ast_rwlock_unlock(&codecs->codecs_lock);
 }
ast_rtp_dtls_cfg_copy()
void ast_rtp_dtls_cfg_copy (const struct ast_rtp_dtls_cfg * src_cfg, struct ast_rtp_dtls_cfg * dst_cfg)
Copy contents of a DTLS configuration structure.
Parameters
src_cfg source DTLS configuration structure
dst_cfg destination DTLS configuration structure
Definition at line 3113 of file rtp_engine.c.
References ast_rtp_dtls_cfg_free(), ast_strdup, ast_rtp_dtls_cfg::cafile, ast_rtp_dtls_cfg::capath, ast_rtp_dtls_cfg::certfile, ast_rtp_dtls_cfg::cipher, ast_rtp_dtls_cfg::default_setup, ast_rtp_dtls_cfg::enabled, ast_rtp_dtls_cfg::ephemeral_cert, ast_rtp_dtls_cfg::hash, ast_rtp_dtls_cfg::pvtfile, ast_rtp_dtls_cfg::rekey, ast_rtp_dtls_cfg::suite, and ast_rtp_dtls_cfg::verify.
Referenced by build_peer(), check_peer_ok(), and create_addr_from_peer().
 {
    ast_rtp_dtls_cfg_free(dst_cfg);         /* Prevent a double-call leaking memory via ast_strdup */
    dst_cfg->enabled = src_cfg->enabled;
    dst_cfg->verify = src_cfg->verify;
    dst_cfg->rekey = src_cfg->rekey;
    dst_cfg->suite = src_cfg->suite;
    dst_cfg->hash = src_cfg->hash;
    dst_cfg->ephemeral_cert = src_cfg->ephemeral_cert;
    dst_cfg->certfile = ast_strdup(src_cfg->certfile);
    dst_cfg->pvtfile = ast_strdup(src_cfg->pvtfile);
    dst_cfg->cipher = ast_strdup(src_cfg->cipher);
    dst_cfg->cafile = ast_strdup(src_cfg->cafile);
    dst_cfg->capath = ast_strdup(src_cfg->capath);
    dst_cfg->default_setup = src_cfg->default_setup;
 }
ast_rtp_dtls_cfg_free()
void ast_rtp_dtls_cfg_free (struct ast_rtp_dtls_cfg * dtls_cfg)
Free contents of a DTLS configuration structure.
Parameters
dtls_cfg a DTLS configuration structure
Definition at line 3131 of file rtp_engine.c.
References ast_free, ast_rtp_dtls_cfg::cafile, ast_rtp_dtls_cfg::capath, ast_rtp_dtls_cfg::certfile, ast_rtp_dtls_cfg::cipher, NULL, and ast_rtp_dtls_cfg::pvtfile.
Referenced by ast_rtp_dtls_cfg_copy(), build_peer(), media_configuration_destroy(), reload_config(), sip_destroy_peer(), sip_pvt_dtor(), and unload_module().
 {
    ast_free(dtls_cfg->certfile);
    dtls_cfg->certfile = NULL;
    ast_free(dtls_cfg->pvtfile);
    dtls_cfg->pvtfile = NULL;
    ast_free(dtls_cfg->cipher);
    dtls_cfg->cipher = NULL;
    ast_free(dtls_cfg->cafile);
    dtls_cfg->cafile = NULL;
    ast_free(dtls_cfg->capath);
    dtls_cfg->capath = NULL;
 }
ast_rtp_dtls_cfg_parse()
int ast_rtp_dtls_cfg_parse (struct ast_rtp_dtls_cfg * dtls_cfg, const char * name, const char * value)
Parse DTLS related configuration options.
Parameters
dtls_cfg a DTLS configuration structure
name name of the configuration option
value value of the configuration option
Return values
0 if handled
-1 if not handled
Definition at line 3020 of file rtp_engine.c.
References ast_file_is_readable(), ast_free, ast_log, AST_RTP_DTLS_HASH_SHA1, AST_RTP_DTLS_HASH_SHA256, AST_RTP_DTLS_SETUP_ACTIVE, AST_RTP_DTLS_SETUP_ACTPASS, AST_RTP_DTLS_SETUP_PASSIVE, AST_RTP_DTLS_VERIFY_CERTIFICATE, AST_RTP_DTLS_VERIFY_FINGERPRINT, AST_RTP_DTLS_VERIFY_NONE, ast_strdup, ast_strlen_zero, ast_true(), ast_rtp_dtls_cfg::cafile, ast_rtp_dtls_cfg::capath, ast_rtp_dtls_cfg::certfile, ast_rtp_dtls_cfg::cipher, ast_rtp_dtls_cfg::default_setup, ast_rtp_dtls_cfg::enabled, ast_rtp_dtls_cfg::ephemeral_cert, ast_rtp_dtls_cfg::hash, LOG_ERROR, ast_rtp_dtls_cfg::pvtfile, ast_rtp_dtls_cfg::rekey, and ast_rtp_dtls_cfg::verify.
Referenced by build_peer(), dtls_handler(), media_encryption_handler(), and reload_config().
 {
    if (!strcasecmp(name, "dtlsenable")) {
       dtls_cfg->enabled = ast_true(value) ? 1 : 0;
    } else if (!strcasecmp(name, "dtlsverify")) {
       if (!strcasecmp(value, "yes")) {
          dtls_cfg->verify = AST_RTP_DTLS_VERIFY_FINGERPRINT | AST_RTP_DTLS_VERIFY_CERTIFICATE;
       } else if (!strcasecmp(value, "fingerprint")) {
          dtls_cfg->verify = AST_RTP_DTLS_VERIFY_FINGERPRINT;
       } else if (!strcasecmp(value, "certificate")) {
          dtls_cfg->verify = AST_RTP_DTLS_VERIFY_CERTIFICATE;
       } else if (!strcasecmp(value, "no")) {
          dtls_cfg->verify = AST_RTP_DTLS_VERIFY_NONE;
       } else {
          return -1;
       }
    } else if (!strcasecmp(name, "dtlsrekey")) {
       if (sscanf(value, "%30u", &dtls_cfg->rekey) != 1) {
          return -1;
       }
    } else if (!strcasecmp(name, "dtlsautogeneratecert")) {
       dtls_cfg->ephemeral_cert = ast_true(value) ? 1 : 0;
    } else if (!strcasecmp(name, "dtlscertfile")) {
       if (!ast_strlen_zero(value) && !ast_file_is_readable(value)) {
          ast_log(LOG_ERROR, "%s file %s does not exist or is not readable\n", name, value);
          return -1;
       }
       ast_free(dtls_cfg->certfile);
       dtls_cfg->certfile = ast_strdup(value);
    } else if (!strcasecmp(name, "dtlsprivatekey")) {
       if (!ast_strlen_zero(value) && !ast_file_is_readable(value)) {
          ast_log(LOG_ERROR, "%s file %s does not exist or is not readable\n", name, value);
          return -1;
       }
       ast_free(dtls_cfg->pvtfile);
       dtls_cfg->pvtfile = ast_strdup(value);
    } else if (!strcasecmp(name, "dtlscipher")) {
       ast_free(dtls_cfg->cipher);
       dtls_cfg->cipher = ast_strdup(value);
    } else if (!strcasecmp(name, "dtlscafile")) {
       if (!ast_strlen_zero(value) && !ast_file_is_readable(value)) {
          ast_log(LOG_ERROR, "%s file %s does not exist or is not readable\n", name, value);
          return -1;
       }
       ast_free(dtls_cfg->cafile);
       dtls_cfg->cafile = ast_strdup(value);
    } else if (!strcasecmp(name, "dtlscapath") || !strcasecmp(name, "dtlscadir")) {
       if (!ast_strlen_zero(value) && !ast_file_is_readable(value)) {
          ast_log(LOG_ERROR, "%s file %s does not exist or is not readable\n", name, value);
          return -1;
       }
       ast_free(dtls_cfg->capath);
       dtls_cfg->capath = ast_strdup(value);
    } else if (!strcasecmp(name, "dtlssetup")) {
       if (!strcasecmp(value, "active")) {
          dtls_cfg->default_setup = AST_RTP_DTLS_SETUP_ACTIVE;
       } else if (!strcasecmp(value, "passive")) {
          dtls_cfg->default_setup = AST_RTP_DTLS_SETUP_PASSIVE;
       } else if (!strcasecmp(value, "actpass")) {
          dtls_cfg->default_setup = AST_RTP_DTLS_SETUP_ACTPASS;
       }
    } else if (!strcasecmp(name, "dtlsfingerprint")) {
       if (!strcasecmp(value, "sha-256")) {
          dtls_cfg->hash = AST_RTP_DTLS_HASH_SHA256;
       } else if (!strcasecmp(value, "sha-1")) {
          dtls_cfg->hash = AST_RTP_DTLS_HASH_SHA1;
       }
    } else {
       return -1;
    }
    return 0;
 }
ast_rtp_dtls_cfg_validate()
int ast_rtp_dtls_cfg_validate (struct ast_rtp_dtls_cfg * dtls_cfg)
Validates DTLS related configuration options.
Parameters
dtls_cfg a DTLS configuration structure
Return values
0 if valid
-1 if invalid
Definition at line 3094 of file rtp_engine.c.
References ast_log, ast_strlen_zero, ast_rtp_dtls_cfg::cafile, ast_rtp_dtls_cfg::capath, ast_rtp_dtls_cfg::certfile, ast_rtp_dtls_cfg::ephemeral_cert, LOG_ERROR, LOG_NOTICE, and ast_rtp_dtls_cfg::pvtfile.
Referenced by build_peer(), reload_config(), and sip_endpoint_apply_handler().
 {
    if (dtls_cfg->ephemeral_cert) {
       if (!ast_strlen_zero(dtls_cfg->certfile)) {
          ast_log(LOG_ERROR, "You cannot request automatically generated certificates"
             " (dtls_auto_generate_cert) and also specify a certificate file"
             " (dtls_cert_file) at the same time\n");
          return -1;
       } else if (!ast_strlen_zero(dtls_cfg->pvtfile)
               || !ast_strlen_zero(dtls_cfg->cafile)
               || !ast_strlen_zero(dtls_cfg->capath)) {
          ast_log(LOG_NOTICE, "dtls_pvt_file, dtls_cafile, and dtls_ca_path are"
             " ignored when dtls_auto_generate_cert is enabled\n");
       }
    }
    return 0;
 }
ast_rtp_engine_alloc_payload_type()
struct ast_rtp_payload_type* ast_rtp_engine_alloc_payload_type (void)
Allocation routine for ast_rtp_payload_type.
Return values
NULL on error
An ao2 ref counted ast_rtp_payload_type on success.
Note
The ast_rtp_payload_type returned by this function is an ao2 ref counted object.
Definition at line 325 of file rtp_engine.c.
References NULL, and rtp_payload_type_alloc().
Referenced by ast_rtp_codecs_payload_replace_format(), ast_rtp_codecs_payloads_set_rtpmap_type_rate(), and payload_mapping_rx_clear_primary().
 {
    return rtp_payload_type_alloc(NULL, 0, 0, 0);
 }
ast_rtp_engine_load_format()
int ast_rtp_engine_load_format (struct ast_format * format)
Custom formats declared in codecs.conf at startup must be communicated to the rtp_engine so their mime type can payload number can be initialized.
Definition at line 3229 of file rtp_engine.c.
References add_static_payload(), ast_codec_media_type2str(), ast_format_get_codec_name(), ast_format_get_sample_rate(), ast_format_get_type(), ast_str_to_upper(), ast_strdupa, and set_next_mime_type().
Referenced by load_module().
 {
    char *codec_name = ast_strdupa(ast_format_get_codec_name(format));
    codec_name = ast_str_to_upper(codec_name);
    set_next_mime_type(format,
       0,
       ast_codec_media_type2str(ast_format_get_type(format)),
       codec_name,
       ast_format_get_sample_rate(format));
    add_static_payload(-1, format, 0);
    return 0;
 }
ast_rtp_engine_register2()
int ast_rtp_engine_register2 (struct ast_rtp_engine * engine, struct ast_module * module)
Register an RTP engine.
Parameters
engine Structure of the RTP engine to register
module Module that the RTP engine is part of
Return values
0 success
-1 failure
Example usage:
ast_rtp_engine_register2(&example_rtp_engine, NULL);
This registers the RTP engine declared as example_rtp_engine with the RTP engine core, but does not associate a module with it.
Note
It is recommended that you use the ast_rtp_engine_register macro so that the module is associated with the RTP engine and use counting is performed.
Since
1.8
Definition at line 330 of file rtp_engine.c.
References ast_log, AST_RWLIST_INSERT_TAIL, AST_RWLIST_TRAVERSE, AST_RWLIST_UNLOCK, AST_RWLIST_WRLOCK, ast_strlen_zero, ast_verb, ast_rtp_engine::destroy, LOG_WARNING, ast_rtp_engine::mod, ast_rtp_engine::name, ast_rtp_engine::new, ast_rtp_engine::read, and ast_rtp_engine::write.
 {
    struct ast_rtp_engine *current_engine;
    /* Perform a sanity check on the engine structure to make sure it has the basics */
    if (ast_strlen_zero(engine->name) || !engine->new || !engine->destroy || !engine->write || !engine->read) {
       ast_log(LOG_WARNING, "RTP Engine '%s' failed sanity check so it was not registered.\n", !ast_strlen_zero(engine->name) ? engine->name : "Unknown");
       return -1;
    }
    /* Link owner module to the RTP engine for reference counting purposes */
    engine->mod = module;
    AST_RWLIST_WRLOCK(&engines);
    /* Ensure that no two modules with the same name are registered at the same time */
    AST_RWLIST_TRAVERSE(&engines, current_engine, entry) {
       if (!strcmp(current_engine->name, engine->name)) {
          ast_log(LOG_WARNING, "An RTP engine with the name '%s' has already been registered.\n", engine->name);
          AST_RWLIST_UNLOCK(&engines);
          return -1;
       }
    }
    /* The engine survived our critique. Off to the list it goes to be used */
    AST_RWLIST_INSERT_TAIL(&engines, engine, entry);
    AST_RWLIST_UNLOCK(&engines);
    ast_verb(2, "Registered RTP engine '%s'\n", engine->name);
    return 0;
 }
ast_rtp_engine_register_srtp()
int ast_rtp_engine_register_srtp (struct ast_srtp_res * srtp_res, struct ast_srtp_policy_res * policy_res)
Definition at line 2710 of file rtp_engine.c.
References policy_res, and srtp_res.
Referenced by res_srtp_init().
 {
    if (res_srtp || res_srtp_policy) {
       return -1;
    }
    if (!srtp_res || !policy_res) {
       return -1;
    }
    res_srtp = srtp_res;
    res_srtp_policy = policy_res;
    return 0;
 }
ast_rtp_engine_srtp_is_registered()
int ast_rtp_engine_srtp_is_registered (void)
Definition at line 2731 of file rtp_engine.c.
References res_srtp_policy.
Referenced by ast_sdp_srtp_alloc(), and dialog_initialize_dtls_srtp().
 {
    return res_srtp && res_srtp_policy;
 }
ast_rtp_engine_unload_format()
int ast_rtp_engine_unload_format (struct ast_format * format)
Formats requiring the use of a format attribute interface must have that interface registered in order for the rtp engine to handle it correctly. If an attribute interface is unloaded, this function must be called to notify the rtp_engine.
Definition at line 3245 of file rtp_engine.c.
References ao2_ref, ast_format_cmp(), AST_FORMAT_CMP_EQUAL, AST_RTP_MAX_PT, ast_rtp_mime_types, ast_rwlock_unlock, ast_rwlock_wrlock, mime_types_len, NULL, and rtp_engine_mime_type_cleanup().
Referenced by unload_module().
 {
    int x;
    int y = 0;
    ast_rwlock_wrlock(&static_RTP_PT_lock);
    /* remove everything pertaining to this format id from the lists */
    for (x = 0; x < AST_RTP_MAX_PT; x++) {
       if (static_RTP_PT[x]
          && ast_format_cmp(static_RTP_PT[x]->format, format) == AST_FORMAT_CMP_EQUAL) {
          ao2_ref(static_RTP_PT[x], -1);
          static_RTP_PT[x] = NULL;
       }
    }
    ast_rwlock_unlock(&static_RTP_PT_lock);
    ast_rwlock_wrlock(&mime_types_lock);
    /* rebuild the list skipping the items matching this id */
    for (x = 0; x < mime_types_len; x++) {
       if (ast_format_cmp(ast_rtp_mime_types[x].payload_type.format, format) == AST_FORMAT_CMP_EQUAL) {
          rtp_engine_mime_type_cleanup(x);
          continue;
       }
       if (x != y) {
          ast_rtp_mime_types[y] = ast_rtp_mime_types[x];
       }
       y++;
    }
    mime_types_len = y;
    ast_rwlock_unlock(&mime_types_lock);
    return 0;
 }
ast_rtp_engine_unregister()
int ast_rtp_engine_unregister (struct ast_rtp_engine * engine)
Unregister an RTP engine.
Parameters
engine Structure of the RTP engine to unregister
Return values
0 success
-1 failure
Example usage:
ast_rtp_engine_unregister(&example_rtp_engine);
This unregisters the RTP engine declared as example_rtp_engine from the RTP engine core. If a module reference was provided when it was registered then this will only be called once the RTP engine is no longer in use.
Since
1.8
Definition at line 364 of file rtp_engine.c.
References AST_RWLIST_REMOVE, AST_RWLIST_UNLOCK, AST_RWLIST_WRLOCK, ast_verb, ast_rtp_engine::name, and NULL.
Referenced by AST_TEST_DEFINE(), load_module(), and unload_module().
 {
    struct ast_rtp_engine *current_engine = NULL;
    AST_RWLIST_WRLOCK(&engines);
    if ((current_engine = AST_RWLIST_REMOVE(&engines, engine, entry))) {
       ast_verb(2, "Unregistered RTP engine '%s'\n", engine->name);
    }
    AST_RWLIST_UNLOCK(&engines);
    return current_engine ? 0 : -1;
 }
ast_rtp_engine_unregister_srtp()
void ast_rtp_engine_unregister_srtp (void)
Definition at line 2725 of file rtp_engine.c.
References NULL.
Referenced by res_srtp_shutdown().
 {
    res_srtp = NULL;
    res_srtp_policy = NULL;
 }
ast_rtp_glue_register2()
int ast_rtp_glue_register2 (struct ast_rtp_glue * glue, struct ast_module * module)
Register RTP glue.
Parameters
glue The glue to register
module Module that the RTP glue is part of
Return values
0 success
-1 failure
Example usage:
ast_rtp_glue_register2(&example_rtp_glue, NULL);
This registers the RTP glue declared as example_rtp_glue with the RTP engine core, but does not associate a module with it.
Note
It is recommended that you use the ast_rtp_glue_register macro so that the module is associated with the RTP glue and use counting is performed.
Since
1.8
Definition at line 379 of file rtp_engine.c.
References ast_log, AST_RWLIST_INSERT_TAIL, AST_RWLIST_TRAVERSE, AST_RWLIST_UNLOCK, AST_RWLIST_WRLOCK, ast_strlen_zero, ast_verb, LOG_WARNING, ast_rtp_glue::mod, NULL, and ast_rtp_glue::type.
 {
    struct ast_rtp_glue *current_glue = NULL;
    if (ast_strlen_zero(glue->type)) {
       return -1;
    }
    glue->mod = module;
    AST_RWLIST_WRLOCK(&glues);
    AST_RWLIST_TRAVERSE(&glues, current_glue, entry) {
       if (!strcasecmp(current_glue->type, glue->type)) {
          ast_log(LOG_WARNING, "RTP glue with the name '%s' has already been registered.\n", glue->type);
          AST_RWLIST_UNLOCK(&glues);
          return -1;
       }
    }
    AST_RWLIST_INSERT_TAIL(&glues, glue, entry);
    AST_RWLIST_UNLOCK(&glues);
    ast_verb(2, "Registered RTP glue '%s'\n", glue->type);
    return 0;
 }
ast_rtp_glue_unregister()
int ast_rtp_glue_unregister (struct ast_rtp_glue * glue)
Unregister RTP glue.
Parameters
glue The glue to unregister
Return values
0 success
-1 failure
Example usage:
ast_rtp_glue_unregister(&example_rtp_glue);
This unregisters the RTP glue declared as example_rtp_gkue from the RTP engine core. If a module reference was provided when it was registered then this will only be called once the RTP engine is no longer in use.
Since
1.8
Definition at line 408 of file rtp_engine.c.
References AST_RWLIST_REMOVE, AST_RWLIST_UNLOCK, AST_RWLIST_WRLOCK, ast_verb, NULL, and ast_rtp_glue::type.
Referenced by load_module(), and unload_module().
 {
    struct ast_rtp_glue *current_glue = NULL;
    AST_RWLIST_WRLOCK(&glues);
    if ((current_glue = AST_RWLIST_REMOVE(&glues, glue, entry))) {
       ast_verb(2, "Unregistered RTP glue '%s'\n", glue->type);
    }
    AST_RWLIST_UNLOCK(&glues);
    return current_glue ? 0 : -1;
 }
ast_rtp_instance_activate()
int ast_rtp_instance_activate (struct ast_rtp_instance * instance)
Indicate to the RTP engine that packets are now expected to be sent/received on the RTP instance.
Parameters
instance The RTP instance
Return values
0 success
-1 failure
Example usage:
ast_rtp_instance_activate(instance);
This tells the underlying RTP engine of instance that packets will now flow.
Since
1.8
Definition at line 2647 of file rtp_engine.c.
References ast_rtp_engine::activate, ao2_lock, ao2_unlock, and ast_rtp_instance::engine.
Referenced by apply_negotiated_sdp_stream(), handle_response_invite(), rtp_call(), test_init_rtp_instances(), and transmit_response_with_sdp().
 {
    int res;
    if (instance->engine->activate) {
       ao2_lock(instance);
       res = instance->engine->activate(instance);
       ao2_unlock(instance);
    } else {
       res = 0;
    }
    return res;
 }
ast_rtp_instance_add_srtp_policy()
int ast_rtp_instance_add_srtp_policy (struct ast_rtp_instance * instance, struct ast_srtp_policy * remote_policy, struct ast_srtp_policy * local_policy, int rtcp)
Add or replace the SRTP policies for the given RTP instance.
Parameters
instance the RTP instance
remote_policy the remote endpoint's policy
local_policy our policy for this RTP instance's remote endpoint
rtcp 1 for dedicated RTCP policies
Return values
0 Success
non-zero Failure
Note
If no remote policy is provided any existing SRTP policies are left and the new local policy is added
Definition at line 2736 of file rtp_engine.c.
References ast_srtp_res::add_stream, ao2_lock, ao2_unlock, ast_srtp_res::create, ast_srtp_res::replace, ast_rtp_instance::rtcp_srtp, and ast_rtp_instance::srtp.
Referenced by crypto_activate(), and rtcp_debug_test_addr().
 {
    int res = 0;
    struct ast_srtp **srtp;
    if (!res_srtp) {
       return -1;
    }
    ao2_lock(instance);
    srtp = rtcp ? &instance->rtcp_srtp : &instance->srtp;
    if (!*srtp) {
       res = res_srtp->create(srtp, instance, remote_policy);
    } else if (remote_policy) {
       res = res_srtp->replace(srtp, instance, remote_policy);
    }
    if (!res) {
       res = res_srtp->add_stream(*srtp, local_policy);
    }
    ao2_unlock(instance);
    return res;
 }
ast_rtp_instance_available_formats()
void ast_rtp_instance_available_formats (struct ast_rtp_instance * instance, struct ast_format_cap * to_endpoint, struct ast_format_cap * to_asterisk, struct ast_format_cap * result)
Request the formats that can be transcoded.
Parameters
instance The RTP instance
to_endpoint Formats being sent/received towards the endpoint
to_asterisk Formats being sent/received towards Asterisk
result capabilities structure to store and return supported formats in.
Example usage:
ast_rtp_instance_available_formats(instance, to_capabilities, from_capabilities, result_capabilities);
This sees if it is possible to have ulaw communicated to the endpoint but signed linear received into Asterisk.
Since
1.8
Definition at line 2633 of file rtp_engine.c.
References ao2_lock, ao2_unlock, ast_format_cap_count(), ast_translate_available_formats(), ast_rtp_engine::available_formats, and ast_rtp_instance::engine.
Referenced by sip_call().
 {
    if (instance->engine->available_formats) {
       ao2_lock(instance);
       instance->engine->available_formats(instance, to_endpoint, to_asterisk, result);
       ao2_unlock(instance);
       if (ast_format_cap_count(result)) {
          return;
       }
    }
    ast_translate_available_formats(to_endpoint, to_asterisk, result);
 }
ast_rtp_instance_bundle()
int ast_rtp_instance_bundle (struct ast_rtp_instance * child, struct ast_rtp_instance * parent)
Request that an RTP instance be bundled with another.
Since
15.0.0
Parameters
child The child RTP instance
parent The parent RTP instance the child should be bundled with
Return values
0 success
-1 failure
Definition at line 3804 of file rtp_engine.c.
References ao2_lock, ao2_unlock, ast_rtp_engine::bundle, and ast_rtp_instance::engine.
Referenced by apply_negotiated_sdp_stream(), and negotiate_incoming_sdp_stream().
 {
    int res = -1;
    if (parent && (child->engine != parent->engine)) {
       return -1;
    }
    ao2_lock(child);
    if (child->engine->bundle) {
       res = child->engine->bundle(child, parent);
    }
    ao2_unlock(child);
    return res;
 }
ast_rtp_instance_change_source()
void ast_rtp_instance_change_source (struct ast_rtp_instance * instance)
Indicate a new source of audio has dropped in and the ssrc should change.
Parameters
instance Instance that the new media source is feeding into
Example usage:
ast_rtp_instance_change_source(instance);
This indicates that the source of media that is feeding the instance pointed to by instance has changed and that the marker bit should be set and the SSRC updated.
Since
1.8
Definition at line 2160 of file rtp_engine.c.
References ao2_lock, ao2_unlock, ast_rtp_engine::change_source, and ast_rtp_instance::engine.
Referenced by create_outgoing_sdp_stream(), jingle_indicate(), mgcp_indicate(), ooh323_indicate(), sip_indicate(), skinny_indicate(), and unistim_indicate().
 {
    if (instance->engine->change_source) {
       ao2_lock(instance);
       instance->engine->change_source(instance);
       ao2_unlock(instance);
    }
 }
ast_rtp_instance_destroy()
int ast_rtp_instance_destroy (struct ast_rtp_instance * instance)
Destroy an RTP instance.
Parameters
instance The RTP instance to destroy
Return values
0 success
-1 failure
Example usage:
ast_rtp_instance_destroy(instance);
This destroys the RTP instance pointed to by instance. Once this function returns instance no longer points to valid memory and may not be used again.
Since
1.8
Definition at line 458 of file rtp_engine.c.
References ao2_cleanup.
Referenced by AST_TEST_DEFINE(), destroy_endpoint(), destroy_rtp(), dialog_clean_rtp(), jingle_session_destructor(), mgcp_hangup(), multicast_rtp_request(), ooh323_destroy(), rtp_hangup(), sip_new(), start_rtp(), stream_destroy(), unalloc_sub(), unicast_rtp_request(), and unistim_hangup_clean().
 {
    ao2_cleanup(instance);
    return 0;
 }
ast_rtp_instance_dtmf_begin()
int ast_rtp_instance_dtmf_begin (struct ast_rtp_instance * instance, char digit)
Begin sending a DTMF digit.
Parameters
instance The RTP instance to send the DTMF on
digit What DTMF digit to send
Return values
0 success
-1 failure
Example usage:
ast_rtp_instance_dtmf_begin(instance, '1');
This starts sending the DTMF '1' on the RTP instance pointed to by instance. It will continue being sent until it is ended.
Since
1.8
Definition at line 2081 of file rtp_engine.c.
References ao2_lock, ao2_unlock, ast_rtp_engine::dtmf_begin, and ast_rtp_instance::engine.
Referenced by chan_pjsip_digit_begin(), jingle_digit_begin(), mgcp_senddigit_begin(), ooh323_digit_begin(), and sip_senddigit_begin().
 {
    int res;
    if (instance->engine->dtmf_begin) {
       ao2_lock(instance);
       res = instance->engine->dtmf_begin(instance, digit);
       ao2_unlock(instance);
    } else {
       res = -1;
    }
    return res;
 }
ast_rtp_instance_dtmf_end()
int ast_rtp_instance_dtmf_end (struct ast_rtp_instance * instance, char digit)
Stop sending a DTMF digit.
Parameters
instance The RTP instance to stop the DTMF on
digit What DTMF digit to stop
Return values
0 success
-1 failure
Example usage:
ast_rtp_instance_dtmf_end(instance, '1');
This stops sending the DTMF '1' on the RTP instance pointed to by instance.
Since
1.8
Definition at line 2095 of file rtp_engine.c.
References ao2_lock, ao2_unlock, ast_rtp_engine::dtmf_end, and ast_rtp_instance::engine.
Referenced by mgcp_senddigit_end(), and ooh323_digit_end().
 {
    int res;
    if (instance->engine->dtmf_end) {
       ao2_lock(instance);
       res = instance->engine->dtmf_end(instance, digit);
       ao2_unlock(instance);
    } else {
       res = -1;
    }
    return res;
 }
ast_rtp_instance_dtmf_end_with_duration()
int ast_rtp_instance_dtmf_end_with_duration (struct ast_rtp_instance * instance, char digit, unsigned int duration)
Definition at line 2109 of file rtp_engine.c.
References ao2_lock, ao2_unlock, ast_rtp_engine::dtmf_end_with_duration, and ast_rtp_instance::engine.
Referenced by chan_pjsip_digit_end(), jingle_digit_end(), and sip_senddigit_end().
 {
    int res;
    if (instance->engine->dtmf_end_with_duration) {
       ao2_lock(instance);
       res = instance->engine->dtmf_end_with_duration(instance, digit, duration);
       ao2_unlock(instance);
    } else {
       res = -1;
    }
    return res;
 }
ast_rtp_instance_dtmf_mode_get()
enum ast_rtp_dtmf_mode ast_rtp_instance_dtmf_mode_get (struct ast_rtp_instance * instance)
Get the DTMF mode of an RTP instance.
Parameters
instance The RTP instance to get the DTMF mode of
Return values
DTMF mode
Example usage:
enum ast_rtp_dtmf_mode dtmf_mode = ast_rtp_instance_dtmf_mode_get(instance);
This gets the DTMF mode set on the RTP instance pointed to by 'instance'.
Since
1.8
Definition at line 2137 of file rtp_engine.c.
References ao2_lock, ao2_unlock, ast_rtp_engine::dtmf_mode_get, and ast_rtp_instance::engine.
Referenced by chan_pjsip_digit_begin(), chan_pjsip_digit_end(), native_rtp_bridge_compatible_check(), pjsip_acf_dtmf_mode_write(), and set_caps().
 {
    int res;
    if (instance->engine->dtmf_mode_get) {
       ao2_lock(instance);
       res = instance->engine->dtmf_mode_get(instance);
       ao2_unlock(instance);
    } else {
       res = 0;
    }
    return res;
 }
ast_rtp_instance_dtmf_mode_set()
int ast_rtp_instance_dtmf_mode_set (struct ast_rtp_instance * instance, enum ast_rtp_dtmf_mode dtmf_mode)
Set the DTMF mode that should be used.
Parameters
instance the RTP instance to set DTMF mode on
dtmf_mode The DTMF mode that is in use
Return values
0 success
-1 failure
Example usage:
ast_rtp_instance_dtmf_mode_set(instance, AST_RTP_DTMF_MODE_RFC2833);
This sets the RTP instance to use RFC2833 for DTMF transmission and receiving.
Since
1.8
Definition at line 2123 of file rtp_engine.c.
References ao2_lock, ao2_unlock, ast_rtp_engine::dtmf_mode_set, and ast_rtp_instance::engine.
Referenced by create_rtp(), enable_dsp_detect(), get_codecs(), pjsip_acf_dtmf_mode_write(), and sip_new().
 {
    int res;
    if (instance->engine->dtmf_mode_set) {
       ao2_lock(instance);
       res = instance->engine->dtmf_mode_set(instance, dtmf_mode);
       ao2_unlock(instance);
    } else {
       res = -1;
    }
    return res;
 }
ast_rtp_instance_early_bridge()
int ast_rtp_instance_early_bridge (struct ast_channel * c0, struct ast_channel * c1)
Early bridge two channels that use RTP instances.
Parameters
c0 First channel part of the bridge
c1 Second channel part of the bridge
Return values
0 success
-1 failure
Note
This should only be used by channel drivers in their technology declaration.
Since
1.8
Definition at line 2337 of file rtp_engine.c.
References ao2_cleanup, ast_channel_lock_both, ast_channel_name(), ast_channel_tech(), ast_channel_unlock, ast_debug, ast_format_cap_alloc, AST_FORMAT_CAP_FLAG_DEFAULT, ast_format_cap_iscompatible(), ast_log, AST_RTP_GLUE_RESULT_FORBID, AST_RTP_GLUE_RESULT_REMOTE, ast_rtp_instance_get_glue(), done, ast_rtp_glue::get_codec, ast_rtp_glue::get_rtp_info, ast_rtp_glue::get_vrtp_info, LOG_WARNING, NULL, type, unref_instance_cond(), and ast_rtp_glue::update_peer.
 {
    struct ast_rtp_instance *instance0 = NULL, *instance1 = NULL,
          *vinstance0 = NULL, *vinstance1 = NULL,
          *tinstance0 = NULL, *tinstance1 = NULL;
    struct ast_rtp_glue *glue0, *glue1;
    enum ast_rtp_glue_result audio_glue0_res = AST_RTP_GLUE_RESULT_FORBID, video_glue0_res = AST_RTP_GLUE_RESULT_FORBID;
    enum ast_rtp_glue_result audio_glue1_res = AST_RTP_GLUE_RESULT_FORBID, video_glue1_res = AST_RTP_GLUE_RESULT_FORBID;
    struct ast_format_cap *cap0 = ast_format_cap_alloc(AST_FORMAT_CAP_FLAG_DEFAULT);
    struct ast_format_cap *cap1 = ast_format_cap_alloc(AST_FORMAT_CAP_FLAG_DEFAULT);
    /* If there is no second channel just immediately bail out, we are of no use in that scenario */
    if (!c1 || !cap1 || !cap0) {
       ao2_cleanup(cap0);
       ao2_cleanup(cap1);
       return -1;
    }
    /* Lock both channels so we can look for the glue that binds them together */
    ast_channel_lock_both(c0, c1);
    /* Grab glue that binds each channel to something using the RTP engine */
    if (!(glue0 = ast_rtp_instance_get_glue(ast_channel_tech(c0)->type)) || !(glue1 = ast_rtp_instance_get_glue(ast_channel_tech(c1)->type))) {
       ast_log(LOG_WARNING, "Can't find native functions for channel '%s'\n", glue0 ? ast_channel_name(c1) : ast_channel_name(c0));
       goto done;
    }
    audio_glue0_res = glue0->get_rtp_info(c0, &instance0);
    video_glue0_res = glue0->get_vrtp_info ? glue0->get_vrtp_info(c0, &vinstance0) : AST_RTP_GLUE_RESULT_FORBID;
    audio_glue1_res = glue1->get_rtp_info(c1, &instance1);
    video_glue1_res = glue1->get_vrtp_info ? glue1->get_vrtp_info(c1, &vinstance1) : AST_RTP_GLUE_RESULT_FORBID;
    /* If we are carrying video, and both sides are not going to remotely bridge... fail the native bridge */
    if (video_glue0_res != AST_RTP_GLUE_RESULT_FORBID && (audio_glue0_res != AST_RTP_GLUE_RESULT_REMOTE || video_glue0_res != AST_RTP_GLUE_RESULT_REMOTE)) {
       audio_glue0_res = AST_RTP_GLUE_RESULT_FORBID;
    }
    if (video_glue1_res != AST_RTP_GLUE_RESULT_FORBID && (audio_glue1_res != AST_RTP_GLUE_RESULT_REMOTE || video_glue1_res != AST_RTP_GLUE_RESULT_REMOTE)) {
       audio_glue1_res = AST_RTP_GLUE_RESULT_FORBID;
    }
    if (audio_glue0_res == AST_RTP_GLUE_RESULT_REMOTE && (video_glue0_res == AST_RTP_GLUE_RESULT_FORBID || video_glue0_res == AST_RTP_GLUE_RESULT_REMOTE) && glue0->get_codec) {
       glue0->get_codec(c0, cap0);
    }
    if (audio_glue1_res == AST_RTP_GLUE_RESULT_REMOTE && (video_glue1_res == AST_RTP_GLUE_RESULT_FORBID || video_glue1_res == AST_RTP_GLUE_RESULT_REMOTE) && glue1->get_codec) {
       glue1->get_codec(c1, cap1);
    }
    /* If any sort of bridge is forbidden just completely bail out and go back to generic bridging */
    if (audio_glue0_res != AST_RTP_GLUE_RESULT_REMOTE || audio_glue1_res != AST_RTP_GLUE_RESULT_REMOTE) {
       goto done;
    }
    /* Make sure we have matching codecs */
    if (!ast_format_cap_iscompatible(cap0, cap1)) {
       goto done;
    }
    /* Bridge media early */
    if (glue0->update_peer(c0, instance1, vinstance1, tinstance1, cap1, 0)) {
       ast_log(LOG_WARNING, "Channel '%s' failed to setup early bridge to '%s'\n", ast_channel_name(c0), c1 ? ast_channel_name(c1) : "<unspecified>");
    }
 done:
    ast_channel_unlock(c0);
    ast_channel_unlock(c1);
    ao2_cleanup(cap0);
    ao2_cleanup(cap1);
    unref_instance_cond(&instance0);
    unref_instance_cond(&instance1);
    unref_instance_cond(&vinstance0);
    unref_instance_cond(&vinstance1);
    unref_instance_cond(&tinstance0);
    unref_instance_cond(&tinstance1);
    ast_debug(1, "Setting early bridge SDP of '%s' with that of '%s'\n", ast_channel_name(c0), c1 ? ast_channel_name(c1) : "<unspecified>");
    return 0;
 }
ast_rtp_instance_early_bridge_make_compatible()
void ast_rtp_instance_early_bridge_make_compatible (struct ast_channel * c_dst, struct ast_channel * c_src)
Make two channels compatible for early bridging.
Parameters
c_dst Destination channel to copy to
c_src Source channel to copy from
Since
1.8
Definition at line 2251 of file rtp_engine.c.
References ao2_cleanup, ast_channel_lock_both, ast_channel_name(), ast_channel_tech(), ast_channel_unlock, ast_debug, ast_format_cap_alloc, AST_FORMAT_CAP_FLAG_DEFAULT, ast_format_cap_iscompatible(), ast_log, ast_rtp_codecs_payloads_xover(), AST_RTP_GLUE_RESULT_FORBID, AST_RTP_GLUE_RESULT_REMOTE, ast_rtp_instance_get_glue(), ast_rtp_instance::codecs, done, ast_rtp_glue::get_codec, ast_rtp_glue::get_rtp_info, ast_rtp_glue::get_vrtp_info, LOG_WARNING, NULL, type, unref_instance_cond(), and ast_rtp_glue::update_peer.
Referenced by dial_exec_full(), and do_forward().
 {
    struct ast_rtp_instance *instance_dst = NULL, *instance_src = NULL,
       *vinstance_dst = NULL, *vinstance_src = NULL,
       *tinstance_dst = NULL, *tinstance_src = NULL;
    struct ast_rtp_glue *glue_dst, *glue_src;
    enum ast_rtp_glue_result audio_glue_dst_res = AST_RTP_GLUE_RESULT_FORBID, video_glue_dst_res = AST_RTP_GLUE_RESULT_FORBID;
    enum ast_rtp_glue_result audio_glue_src_res = AST_RTP_GLUE_RESULT_FORBID, video_glue_src_res = AST_RTP_GLUE_RESULT_FORBID;
    struct ast_format_cap *cap_dst = ast_format_cap_alloc(AST_FORMAT_CAP_FLAG_DEFAULT);
    struct ast_format_cap *cap_src = ast_format_cap_alloc(AST_FORMAT_CAP_FLAG_DEFAULT);
    /* Lock both channels so we can look for the glue that binds them together */
    ast_channel_lock_both(c_dst, c_src);
    if (!cap_src || !cap_dst) {
       goto done;
    }
    /* Grab glue that binds each channel to something using the RTP engine */
    if (!(glue_dst = ast_rtp_instance_get_glue(ast_channel_tech(c_dst)->type)) || !(glue_src = ast_rtp_instance_get_glue(ast_channel_tech(c_src)->type))) {
       ast_debug(1, "Can't find native functions for channel '%s'\n", glue_dst ? ast_channel_name(c_src) : ast_channel_name(c_dst));
       goto done;
    }
    audio_glue_dst_res = glue_dst->get_rtp_info(c_dst, &instance_dst);
    video_glue_dst_res = glue_dst->get_vrtp_info ? glue_dst->get_vrtp_info(c_dst, &vinstance_dst) : AST_RTP_GLUE_RESULT_FORBID;
    audio_glue_src_res = glue_src->get_rtp_info(c_src, &instance_src);
    video_glue_src_res = glue_src->get_vrtp_info ? glue_src->get_vrtp_info(c_src, &vinstance_src) : AST_RTP_GLUE_RESULT_FORBID;
    /* If we are carrying video, and both sides are not going to remotely bridge... fail the native bridge */
    if (video_glue_dst_res != AST_RTP_GLUE_RESULT_FORBID && (audio_glue_dst_res != AST_RTP_GLUE_RESULT_REMOTE || video_glue_dst_res != AST_RTP_GLUE_RESULT_REMOTE)) {
       audio_glue_dst_res = AST_RTP_GLUE_RESULT_FORBID;
    }
    if (video_glue_src_res != AST_RTP_GLUE_RESULT_FORBID && (audio_glue_src_res != AST_RTP_GLUE_RESULT_REMOTE || video_glue_src_res != AST_RTP_GLUE_RESULT_REMOTE)) {
       audio_glue_src_res = AST_RTP_GLUE_RESULT_FORBID;
    }
    if (audio_glue_dst_res == AST_RTP_GLUE_RESULT_REMOTE && (video_glue_dst_res == AST_RTP_GLUE_RESULT_FORBID || video_glue_dst_res == AST_RTP_GLUE_RESULT_REMOTE) && glue_dst->get_codec) {
       glue_dst->get_codec(c_dst, cap_dst);
    }
    if (audio_glue_src_res == AST_RTP_GLUE_RESULT_REMOTE && (video_glue_src_res == AST_RTP_GLUE_RESULT_FORBID || video_glue_src_res == AST_RTP_GLUE_RESULT_REMOTE) && glue_src->get_codec) {
       glue_src->get_codec(c_src, cap_src);
    }
    /* If any sort of bridge is forbidden just completely bail out and go back to generic bridging */
    if (audio_glue_dst_res != AST_RTP_GLUE_RESULT_REMOTE || audio_glue_src_res != AST_RTP_GLUE_RESULT_REMOTE) {
       goto done;
    }
    /* Make sure we have matching codecs */
    if (!ast_format_cap_iscompatible(cap_dst, cap_src)) {
       goto done;
    }
    ast_rtp_codecs_payloads_xover(&instance_src->codecs, &instance_dst->codecs, instance_dst);
    if (vinstance_dst && vinstance_src) {
       ast_rtp_codecs_payloads_xover(&vinstance_src->codecs, &vinstance_dst->codecs, vinstance_dst);
    }
    if (tinstance_dst && tinstance_src) {
       ast_rtp_codecs_payloads_xover(&tinstance_src->codecs, &tinstance_dst->codecs, tinstance_dst);
    }
    if (glue_dst->update_peer(c_dst, instance_src, vinstance_src, tinstance_src, cap_src, 0)) {
       ast_log(LOG_WARNING, "Channel '%s' failed to setup early bridge to '%s'\n",
          ast_channel_name(c_dst), ast_channel_name(c_src));
    } else {
       ast_debug(1, "Seeded SDP of '%s' with that of '%s'\n",
          ast_channel_name(c_dst), ast_channel_name(c_src));
    }
 done:
    ast_channel_unlock(c_dst);
    ast_channel_unlock(c_src);
    ao2_cleanup(cap_dst);
    ao2_cleanup(cap_src);
    unref_instance_cond(&instance_dst);
    unref_instance_cond(&instance_src);
    unref_instance_cond(&vinstance_dst);
    unref_instance_cond(&vinstance_src);
    unref_instance_cond(&tinstance_dst);
    unref_instance_cond(&tinstance_src);
 }
ast_rtp_instance_extmap_clear()
void ast_rtp_instance_extmap_clear (struct ast_rtp_instance * instance)
Clear negotiated RTP extension information.
Parameters
instance The RTP instance to clear negotiated extension information on
Definition at line 862 of file rtp_engine.c.
References ao2_lock, ao2_unlock, AST_RTP_EXTENSION_DIRECTION_NONE, AST_RTP_EXTENSION_UNSUPPORTED, AST_VECTOR_REPLACE, AST_VECTOR_SIZE, and rtp_extmap::extension.
Referenced by process_extmap_attributes().
 {
    static const struct rtp_extmap extmap_none = {
       .extension = AST_RTP_EXTENSION_UNSUPPORTED,
       .direction = AST_RTP_EXTENSION_DIRECTION_NONE,
    };
    int idx;
    ao2_lock(instance);
    /* Clear both the known unique ids and the negotiated extensions as we are about to have
     * new results set on us.
     */
    for (idx = 0; idx < AST_VECTOR_SIZE(&instance->extmap_unique_ids); ++idx) {
       AST_VECTOR_REPLACE(&instance->extmap_unique_ids, idx, extmap_none);
    }
    for (idx = 0; idx < AST_VECTOR_SIZE(&instance->extmap_negotiated); ++idx) {
       AST_VECTOR_REPLACE(&instance->extmap_negotiated, idx, -1);
    }
    ao2_unlock(instance);
 }
ast_rtp_instance_extmap_count()
size_t ast_rtp_instance_extmap_count (struct ast_rtp_instance * instance)
Get the number of known unique identifiers.
Parameters
instance The RTP instance to retrieve the count from
Returns
the number of known unique identifiers
Since
15.5.0
Definition at line 899 of file rtp_engine.c.
References ao2_lock, ao2_unlock, and AST_VECTOR_SIZE.
Referenced by add_extmap_to_stream(), and enable_rtp_extension().
 {
    size_t count;
    ao2_lock(instance);
    count = AST_VECTOR_SIZE(&instance->extmap_unique_ids);
    ao2_unlock(instance);
    return count;
 }
ast_rtp_instance_extmap_enable()
int ast_rtp_instance_extmap_enable (struct ast_rtp_instance * instance, int id, enum ast_rtp_extension extension, enum ast_rtp_extension_direction direction)
Enable support for an RTP extension on an instance.
Parameters
instance The RTP instance to enable the extension on
id The unique local identifier to use for this extension (-1 to have one auto selected)
extension The RTP extension
direction The initial direction that the RTP extension should be used in
Return values
0 success
-1 failure
Since
15.5.0
Definition at line 732 of file rtp_engine.c.
References ao2_lock, ao2_unlock, AST_RTP_EXTENSION_DIRECTION_NONE, AST_RTP_EXTENSION_UNSUPPORTED, AST_VECTOR_APPEND, AST_VECTOR_REPLACE, AST_VECTOR_SIZE, rtp_extmap::direction, ast_rtp_instance::engine, rtp_extmap::extension, and ast_rtp_engine::extension_enable.
Referenced by enable_rtp_extension().
 {
    struct rtp_extmap extmap = {
       .extension = extension,
       .direction = direction,
    };
    ao2_lock(instance);
    if (!instance->engine->extension_enable || !instance->engine->extension_enable(instance, extension)) {
       ao2_unlock(instance);
       return 0;
    }
    /* We store enabled extensions separately so we can easily do negotiation */
    if (AST_VECTOR_REPLACE(&instance->extmap_enabled, extension, direction)) {
       ao2_unlock(instance);
       return -1;
    }
    if (id <= 0) {
       /* We find a free unique identifier for this extension by just appending it to the
        * vector of unique ids. The size of the vector will become its unique identifier.
        * As well when we are asking for information on the extensions it will be returned,
        * allowing it to be added to the SDP offer.
        */
       if (AST_VECTOR_APPEND(&instance->extmap_unique_ids, extmap)) {
          AST_VECTOR_REPLACE(&instance->extmap_enabled, extension, AST_RTP_EXTENSION_DIRECTION_NONE);
          ao2_unlock(instance);
          return -1;
       }
       id = AST_VECTOR_SIZE(&instance->extmap_unique_ids);
    } else {
       /* Otherwise we put it precisely where they want it */
       if (AST_VECTOR_REPLACE(&instance->extmap_unique_ids, id - 1, extmap)) {
          AST_VECTOR_REPLACE(&instance->extmap_enabled, extension, AST_RTP_EXTENSION_DIRECTION_NONE);
          ao2_unlock(instance);
          return -1;
       }
    }
    /* Now that we have an id add the extension to here */
    if (AST_VECTOR_REPLACE(&instance->extmap_negotiated, extension, id)) {
       extmap.extension = AST_RTP_EXTENSION_UNSUPPORTED;
       extmap.direction = AST_RTP_EXTENSION_DIRECTION_NONE;
       AST_VECTOR_REPLACE(&instance->extmap_enabled, extension, AST_RTP_EXTENSION_DIRECTION_NONE);
       AST_VECTOR_REPLACE(&instance->extmap_unique_ids, id - 1, extmap);
       ao2_unlock(instance);
       return -1;
    }
    ao2_unlock(instance);
    return 0;
 }
ast_rtp_instance_extmap_get_direction()
enum ast_rtp_extension_direction ast_rtp_instance_extmap_get_direction (struct ast_rtp_instance * instance, int id)
Retrieve the negotiated direction for an RTP extension id.
Parameters
instance The RTP instance to retrieve the direction from
id The negotiated RTP extension id
Return values
direction the direction that has been negotiated
Since
15.5.0
Definition at line 930 of file rtp_engine.c.
References ao2_lock, ao2_unlock, AST_RTP_EXTENSION_DIRECTION_NONE, AST_VECTOR_GET_ADDR, AST_VECTOR_SIZE, and rtp_extmap::direction.
Referenced by add_extmap_to_stream().
 {
    enum ast_rtp_extension_direction direction = AST_RTP_EXTENSION_DIRECTION_NONE;
    ao2_lock(instance);
    if (0 < id && id <= AST_VECTOR_SIZE(&instance->extmap_unique_ids)) {
       struct rtp_extmap *extmap = AST_VECTOR_GET_ADDR(&instance->extmap_unique_ids, id - 1);
       direction = extmap->direction;
    }
    ao2_unlock(instance);
    return direction;
 }
ast_rtp_instance_extmap_get_extension()
enum ast_rtp_extension ast_rtp_instance_extmap_get_extension (struct ast_rtp_instance * instance, int id)
Retrieve the extension for an RTP extension id.
Parameters
instance The RTP instance to retrieve the extension from
id The negotiated RTP extension id
Return values
extension the extension that maps to the id
Since
15.5.0
Note
This will return AST_RTP_EXTENSION_UNSUPPORTED if an extension was proposed for this unique identifier but it is not supported or if the unique identifier is unused.
Definition at line 910 of file rtp_engine.c.
References ao2_lock, ao2_unlock, AST_RTP_EXTENSION_UNSUPPORTED, AST_VECTOR_GET_ADDR, AST_VECTOR_SIZE, and rtp_extmap::extension.
Referenced by add_extmap_to_stream(), and ast_rtp_instance_extmap_get_uri().
 {
    enum ast_rtp_extension extension = AST_RTP_EXTENSION_UNSUPPORTED;
    ao2_lock(instance);
    /* The local unique identifier starts at '1' so the highest unique identifier
     * can be the actual size of the vector. We compensate (as it is 0 index based)
     * by dropping it down to 1 to get the correct information.
     */
    if (0 < id && id <= AST_VECTOR_SIZE(&instance->extmap_unique_ids)) {
       struct rtp_extmap *extmap = AST_VECTOR_GET_ADDR(&instance->extmap_unique_ids, id - 1);
       extension = extmap->extension;
    }
    ao2_unlock(instance);
    return extension;
 }
ast_rtp_instance_extmap_get_id()
int ast_rtp_instance_extmap_get_id (struct ast_rtp_instance * instance, enum ast_rtp_extension extension)
Retrieve the id for an RTP extension.
Parameters
instance The RTP instance to retrieve the id from
extension The RTP extension
Return values
-1 not negotiated
id if negotiated
Since
15.5.0
Definition at line 886 of file rtp_engine.c.
References ao2_lock, ao2_unlock, AST_VECTOR_GET, AST_VECTOR_SIZE, and id.
Referenced by ast_rtp_rtcp_handle_nack(), enable_rtp_extension(), rtp_instance_parse_extmap_extensions(), and rtp_raw_write().
 {
    int id = -1;
    ao2_lock(instance);
    if (extension < AST_VECTOR_SIZE(&instance->extmap_negotiated)) {
       id = AST_VECTOR_GET(&instance->extmap_negotiated, extension);
    }
    ao2_unlock(instance);
    return id;
 }
ast_rtp_instance_extmap_get_uri()
const char* ast_rtp_instance_extmap_get_uri (struct ast_rtp_instance * instance, int id)
Retrieve the URI for an RTP extension id.
Parameters
instance The RTP instance to retrieve the direction from
id The negotiated RTP extension id
Return values
uri The URI for the RTP extension
Since
15.5.0
Definition at line 946 of file rtp_engine.c.
References ARRAY_LEN, AST_RTP_EXTENSION_UNSUPPORTED, ast_rtp_instance_extmap_get_extension(), rtp_extmap::extension, NULL, and rtp_extension_uris.
Referenced by add_extmap_to_stream().
 {
    enum ast_rtp_extension extension = ast_rtp_instance_extmap_get_extension(instance, id);
    if (extension == AST_RTP_EXTENSION_UNSUPPORTED ||
       (unsigned int)extension >= ARRAY_LEN(rtp_extension_uris)) {
       return NULL;
    }
    return rtp_extension_uris[extension];
 }
ast_rtp_instance_extmap_negotiate()
int ast_rtp_instance_extmap_negotiate (struct ast_rtp_instance * instance, int id, enum ast_rtp_extension_direction direction, const char * uri, const char * attributes)
Negotiate received RTP extension information.
Parameters
instance The RTP instance to set the extension on
id The local identifier for the extension
direction The direction that the extension should be used in
uri The unique URI for the extension
attributes Attributes specific to this extension (if NULL or empty then no attributes)
Return values
0 success
-1 failure
Since
15.5.0
Definition at line 818 of file rtp_engine.c.
References ao2_lock, ao2_unlock, ARRAY_LEN, AST_RTP_EXTENSION_DIRECTION_NONE, AST_RTP_EXTENSION_UNSUPPORTED, AST_VECTOR_GET, AST_VECTOR_REPLACE, AST_VECTOR_SIZE, rtp_extmap::direction, rtp_extmap::extension, rtp_extension_uris, and rtp_extmap_negotiate_direction().
Referenced by process_extmap_attributes().
 {
    /* 'attributes' is currently unused but exists in the API to ensure it does not need to be altered
     * in the future in case we need to use it.
     */
    int idx;
    enum ast_rtp_extension extension = AST_RTP_EXTENSION_UNSUPPORTED;
    /* Per the RFC the identifier has to be 1 or above */
    if (id < 1) {
       return -1;
    }
    /* Convert the provided URI to the internal representation */
    for (idx = 0; idx < ARRAY_LEN(rtp_extension_uris); ++idx) {
       if (!strcasecmp(rtp_extension_uris[idx], uri)) {
          extension = idx;
          break;
       }
    }
    ao2_lock(instance);
    /* We only accept the extension if it is enabled */
    if (extension < AST_VECTOR_SIZE(&instance->extmap_enabled) &&
       AST_VECTOR_GET(&instance->extmap_enabled, extension) != AST_RTP_EXTENSION_DIRECTION_NONE) {
       struct rtp_extmap extmap = {
          .extension = extension,
          .direction = rtp_extmap_negotiate_direction(AST_VECTOR_GET(&instance->extmap_enabled, extension), direction),
       };
       /* If the direction negotiation failed then don't accept or use this extension */
       if (extmap.direction != AST_RTP_EXTENSION_DIRECTION_NONE) {
          if (extension != AST_RTP_EXTENSION_UNSUPPORTED) {
             AST_VECTOR_REPLACE(&instance->extmap_negotiated, extension, id);
          }
          AST_VECTOR_REPLACE(&instance->extmap_unique_ids, id - 1, extmap);
       }
    }
    ao2_unlock(instance);
    return 0;
 }
ast_rtp_instance_fd()
int ast_rtp_instance_fd (struct ast_rtp_instance * instance, int rtcp)
Get the file descriptor for an RTP session (or RTCP)
Parameters
instance Instance to get the file descriptor for
rtcp Whether to retrieve the file descriptor for RTCP or not
Return values
fd success
-1 failure
Example usage:
int rtp_fd = ast_rtp_instance_fd(instance, 0);
This retrieves the file descriptor for the socket carrying media on the instance pointed to by instance.
Since
1.8
Definition at line 2192 of file rtp_engine.c.
References ao2_lock, ao2_unlock, ast_rtp_instance::engine, and ast_rtp_engine::fd.
Referenced by apply_negotiated_sdp_stream(), check_for_rtp_changes(), configure_local_rtp(), configure_rtcp(), jingle_enable_video(), jingle_new(), mgcp_new(), rtp_find_rtcp_fd_position(), sip_new(), sip_set_rtp_peer(), skinny_new(), start_rtp(), transmit_reinvite_with_sdp(), unicast_rtp_request(), and unistim_new().
 {
    int res;
    if (instance->engine->fd) {
       ao2_lock(instance);
       res = instance->engine->fd(instance, rtcp);
       ao2_unlock(instance);
    } else {
       res = -1;
    }
    return res;
 }
ast_rtp_instance_get_active_glue()
struct ast_rtp_glue* ast_rtp_instance_get_active_glue (struct ast_rtp_instance * instance)
Get the RTP glue in use on an RTP instance.
Parameters
instance The RTP instance
Return values
pointer to the glue
Example:
struct ast_rtp_glue *glue = ast_rtp_instance_get_active_glue(instance);
This gets the RTP glue currently in use on the RTP instance pointed to by 'instance'.
Since
1.8
Definition at line 2705 of file rtp_engine.c.
References ast_rtp_instance::glue.
 {
    return instance->glue;
 }
ast_rtp_instance_get_and_cmp_local_address()
int ast_rtp_instance_get_and_cmp_local_address (struct ast_rtp_instance * instance, struct ast_sockaddr * address)
Get the address of the local endpoint that we are sending RTP to, comparing its address to another.
Parameters
instance The instance that we want to get the local address for
address An initialized address that may be overwritten if the local address is different
Return values
0 address was not changed
1 address was changed Example usage:
struct ast_sockaddr address;
int ret;
ret = ast_rtp_instance_get_and_cmp_local_address(instance, &address);
This retrieves the current local address set on the instance pointed to by instance and puts the value into the address structure.
Since
1.8
Definition at line 629 of file rtp_engine.c.
References ao2_lock, ao2_unlock, ast_sockaddr_cmp(), ast_sockaddr_copy(), and ast_rtp_instance::local_address.
 {
    ao2_lock(instance);
    if (ast_sockaddr_cmp(address, &instance->local_address) != 0) {
       ast_sockaddr_copy(address, &instance->local_address);
       ao2_unlock(instance);
       return 1;
    }
    ao2_unlock(instance);
    return 0;
 }
ast_rtp_instance_get_and_cmp_requested_target_address()
int ast_rtp_instance_get_and_cmp_requested_target_address (struct ast_rtp_instance * instance, struct ast_sockaddr * address)
Get the requested target address of the remote endpoint and compare it to the given address.
Parameters
instance The instance that we want to get the remote address for
address An initialized address that may be overwritten addresses differ
Return values
0 address was not changed
1 address was changed
Definition at line 651 of file rtp_engine.c.
References ao2_lock, ao2_unlock, ast_sockaddr_cmp(), ast_sockaddr_copy(), and ast_rtp_instance::requested_target_address.
 {
    ao2_lock(instance);
    if (ast_sockaddr_cmp(address, &instance->requested_target_address) != 0) {
       ast_sockaddr_copy(address, &instance->requested_target_address);
       ao2_unlock(instance);
       return 1;
    }
    ao2_unlock(instance);
    return 0;
 }
ast_rtp_instance_get_bridged()
struct ast_rtp_instance* ast_rtp_instance_get_bridged (struct ast_rtp_instance * instance)
Get the other RTP instance that an instance is bridged to.
Parameters
instance The RTP instance that we want
Return values
non-NULL success
NULL failure
Example usage:
struct ast_rtp_instance *bridged = ast_rtp_instance_get_bridged(instance0);
This gets the RTP instance that instance0 is bridged to.
Since
1.8
Definition at line 2234 of file rtp_engine.c.
References ao2_lock, ao2_unlock, and ast_rtp_instance::bridged.
Referenced by ast_rtp_interpret(), and dialog_needdestroy().
 {
    struct ast_rtp_instance *bridged;
    ao2_lock(instance);
    bridged = instance->bridged;
    ao2_unlock(instance);
    return bridged;
 }
ast_rtp_instance_get_channel_id()
const char* ast_rtp_instance_get_channel_id (struct ast_rtp_instance * instance)
Get the unique ID of the channel that owns this RTP instance.
Note that this should remain valid for the lifetime of the RTP instance.
Parameters
instance The RTP instance
Return values
The unique ID of the channel
Empty string if no channel owns this RTP instance
Since
12
Definition at line 548 of file rtp_engine.c.
References ast_rtp_instance::channel_uniqueid.
Referenced by ast_rtp_get_stat(), rtp_check_timeout(), and rtp_transport_wide_cc_feedback_produce().
 {
    return instance->channel_uniqueid;
 }
ast_rtp_instance_get_cname()
const char* ast_rtp_instance_get_cname (struct ast_rtp_instance * rtp)
Retrieve the CNAME used in RTCP SDES items.
This is a pointer directly into the RTP struct, not a copy.
Parameters
rtp The RTP instance
Returns
the CNAME
Definition at line 3791 of file rtp_engine.c.
References ao2_lock, ao2_unlock, ast_rtp_engine::cname_get, and ast_rtp_instance::engine.
Referenced by add_ssrc_to_stream().
 {
    const char *cname = "";
    ao2_lock(rtp);
    if (rtp->engine->cname_get) {
       cname = rtp->engine->cname_get(rtp);
    }
    ao2_unlock(rtp);
    return cname;
 }
ast_rtp_instance_get_codecs()
struct ast_rtp_codecs* ast_rtp_instance_get_codecs (struct ast_rtp_instance * instance)
Get the codecs structure of an RTP instance.
Parameters
instance The RTP instance to get the codecs structure from
Example usage:
struct ast_rtp_codecs *codecs = ast_rtp_instance_get_codecs(instance);
This gets the codecs structure on the RTP instance pointed to by 'instance'.
Since
1.8
Definition at line 727 of file rtp_engine.c.
References ast_rtp_instance::codecs.
Referenced by add_codec_to_sdp(), add_noncodec_to_sdp(), add_sdp(), add_tcodec_to_sdp(), add_vcodec_to_sdp(), apply_cap_to_bundled(), ast_rtp_dtmf_begin(), ast_rtp_interpret(), ast_rtp_read(), ast_rtp_sendcng(), ast_rtp_write(), bridge_p2p_rtp_write(), check_peer_ok(), configure_local_rtp(), create_addr_from_peer(), create_outgoing_sdp_stream(), jingle_add_payloads_to_description(), jingle_enable_video(), jingle_interpret_description(), jingle_new(), multicast_rtp_write(), native_rtp_bridge_compatible_check(), ooh323_set_write_format(), process_sdp(), send_start_rtp(), set_caps(), set_incoming_call_offer_cap(), setup_rtp_connection(), and start_rtp().
 {
    return &instance->codecs;
 }
ast_rtp_instance_get_data()
void* ast_rtp_instance_get_data (struct ast_rtp_instance * instance)
Get the data portion of an RTP instance.
Parameters
instance The RTP instance we want the data portion from
Example usage:
  struct *blob = ast_rtp_instance_get_data(instance);
(
This gets the data pointer on the RTP instance pointed to by 'instance'.
Since
1.8
Definition at line 563 of file rtp_engine.c.
References ast_rtp_instance::data.
Referenced by __rtp_recvfrom(), __rtp_sendto(), ast_rtcp_calculate_sr_rr_statistics(), ast_rtcp_generate_nack(), ast_rtcp_generate_report(), ast_rtcp_generate_sdes(), ast_rtcp_interpret(), ast_rtcp_read(), ast_rtcp_write(), ast_rtp_bundle(), ast_rtp_change_source(), ast_rtp_destroy(), ast_rtp_dtmf_begin(), ast_rtp_dtmf_continuation(), ast_rtp_dtmf_end_with_duration(), ast_rtp_dtmf_mode_get(), ast_rtp_dtmf_mode_set(), ast_rtp_fd(), ast_rtp_get_cname(), ast_rtp_get_ssrc(), ast_rtp_get_stat(), ast_rtp_ice_add_remote_candidate(), ast_rtp_ice_change_components(), ast_rtp_ice_get_local_candidates(), ast_rtp_ice_get_password(), ast_rtp_ice_get_ufrag(), ast_rtp_ice_lite(), ast_rtp_ice_set_authentication(), ast_rtp_ice_set_role(), ast_rtp_ice_start(), ast_rtp_ice_start_media(), ast_rtp_ice_stop(), ast_rtp_ice_turn_request(), ast_rtp_interpret(), ast_rtp_local_bridge(), ast_rtp_on_ice_rx_data(), ast_rtp_on_ice_tx_pkt(), ast_rtp_on_turn_rtcp_state(), ast_rtp_on_turn_rtp_state(), ast_rtp_on_turn_rx_rtcp_data(), ast_rtp_on_turn_rx_rtp_data(), ast_rtp_prop_set(), ast_rtp_qos_set(), ast_rtp_read(), ast_rtp_remote_address_set(), ast_rtp_rtcp_handle_nack(), ast_rtp_sendcng(), ast_rtp_set_remote_ssrc(), ast_rtp_set_stream_num(), ast_rtp_stop(), ast_rtp_stun_request(), ast_rtp_update_source(), ast_rtp_write(), bridge_p2p_rtp_write(), create_dtmf_frame(), get_recv_buffer_count(), get_recv_buffer_max(), get_send_buffer_count(), ice_create(), ice_reset_session(), multicast_rtp_activate(), multicast_rtp_destroy(), multicast_rtp_write(), process_cn_rfc3389(), process_dtmf_cisco(), process_dtmf_rfc2833(), red_write(), rtcp_debug_test_addr(), rtp_instance_parse_transport_wide_cc(), rtp_raw_write(), rtp_red_buffer(), rtp_red_init(), rtp_sendto(), rtp_transport_wide_cc_feedback_produce(), set_rtp_rtcp_schedid(), and test_sip_rtpqos_1_get_stat().
 {
    return instance->data;
 }
ast_rtp_instance_get_dtls()
struct ast_rtp_engine_dtls* ast_rtp_instance_get_dtls (struct ast_rtp_instance * instance)
Obtain a pointer to the DTLS support present on an RTP instance.
Parameters
instance the RTP instance
Return values
DTLS support if present
NULL if no DTLS support available
Definition at line 3011 of file rtp_engine.c.
References ast_rtp_engine::dtls, ast_rtp_instance::engine, NULL, and rtp_dtls_wrappers.
Referenced by add_crypto_to_stream(), add_dtls_to_sdp(), apply_dtls_attrib(), ast_sdp_get_rtp_profile(), dialog_initialize_dtls_srtp(), process_crypto(), process_sdp(), process_sdp_a_dtls(), and setup_dtls_srtp().
 {
    if (instance->engine->dtls) {
       return &rtp_dtls_wrappers;
    }
    /* DTLS not available */
    return NULL;
 }
ast_rtp_instance_get_engine()
struct ast_rtp_engine* ast_rtp_instance_get_engine (struct ast_rtp_instance * instance)
Get the RTP engine in use on an RTP instance.
Parameters
instance The RTP instance
Return values
pointer to the engine
Example usage:
struct ast_rtp_engine *engine = ast_rtp_instance_get_engine(instance);
This gets the RTP engine currently in use on the RTP instance pointed to by 'instance'.
Since
1.8
Definition at line 2700 of file rtp_engine.c.
References ast_rtp_instance::engine.
Referenced by native_rtp_bridge_compatible_check(), native_rtp_bridge_start(), and native_rtp_bridge_stop().
 {
    return instance->engine;
 }
ast_rtp_instance_get_extended_prop()
void* ast_rtp_instance_get_extended_prop (struct ast_rtp_instance * instance, int property)
Get the value of an RTP instance extended property.
Parameters
instance The RTP instance to get the extended property on
property The extended property to get
Since
1.8
Definition at line 690 of file rtp_engine.c.
References ao2_lock, ao2_unlock, ast_rtp_instance::engine, ast_rtp_engine::extended_prop_get, and NULL.
 {
    void *prop;
    if (instance->engine->extended_prop_get) {
       ao2_lock(instance);
       prop = instance->engine->extended_prop_get(instance, property);
       ao2_unlock(instance);
    } else {
       prop = NULL;
    }
    return prop;
 }
ast_rtp_instance_get_glue()
struct ast_rtp_glue* ast_rtp_instance_get_glue (const char * type)
Get the RTP glue that binds a channel to the RTP engine.
Parameters
type Name of the glue we want
Return values
non-NULL success
NULL failure
Example usage:
struct ast_rtp_glue *glue = ast_rtp_instance_get_glue("Example");
This retrieves the RTP glue that has the name 'Example'.
Since
1.8
Definition at line 2206 of file rtp_engine.c.
References AST_RWLIST_RDLOCK, AST_RWLIST_TRAVERSE, AST_RWLIST_UNLOCK, NULL, and ast_rtp_glue::type.
Referenced by ast_ari_channels_rtpstatistics(), ast_rtp_instance_early_bridge(), ast_rtp_instance_early_bridge_make_compatible(), ast_rtp_instance_make_compatible(), and rtp_glue_data_get().
 {
    struct ast_rtp_glue *glue = NULL;
    AST_RWLIST_RDLOCK(&glues);
    AST_RWLIST_TRAVERSE(&glues, glue, entry) {
       if (!strcasecmp(glue->type, type)) {
          break;
       }
    }
    AST_RWLIST_UNLOCK(&glues);
    return glue;
 }
ast_rtp_instance_get_hold_timeout()
int ast_rtp_instance_get_hold_timeout (struct ast_rtp_instance * instance)
Get the RTP timeout value for when an RTP instance is on hold.
Parameters
instance The RTP instance
Return values
timeout value
Example usage:
int timeout = ast_rtp_instance_get_hold_timeout(instance);
This gets the RTP hold timeout value for the RTP instance pointed to by 'instance'.
Since
1.8
Definition at line 2690 of file rtp_engine.c.
References ast_rtp_instance::holdtimeout.
Referenced by check_rtp_timeout().
 {
    return instance->holdtimeout;
 }
ast_rtp_instance_get_ice()
struct ast_rtp_engine_ice* ast_rtp_instance_get_ice (struct ast_rtp_instance * instance)
Obtain a pointer to the ICE support present on an RTP instance.
Parameters
instance the RTP instance
Return values
ICE support if present
NULL if no ICE support available
Definition at line 2891 of file rtp_engine.c.
References ast_rtp_instance::engine, ast_rtp_engine::ice, NULL, and rtp_ice_wrappers.
Referenced by add_ice_to_sdp(), add_ice_to_stream(), check_ice_support(), create_rtp(), dialog_initialize_rtp(), jingle_add_google_candidates_to_transport(), jingle_add_ice_udp_candidates_to_transport(), jingle_enable_video(), jingle_interpret_google_transport(), jingle_interpret_ice_udp_transport(), jingle_new(), jingle_outgoing_hook(), jingle_request(), process_ice_attributes(), process_ice_auth_attrb(), process_sdp_a_ice(), set_ice_components(), and start_ice().
 {
    if (instance->engine->ice) {
       return &rtp_ice_wrappers;
    }
    /* ICE not available */
    return NULL;
 }
ast_rtp_instance_get_incoming_source_address()
void ast_rtp_instance_get_incoming_source_address (struct ast_rtp_instance * instance, struct ast_sockaddr * address)
Get the incoming source address of the remote endpoint.
This returns the remote address the engine is sending RTP to. Usually this will be the same as the requested target address, however in the case where the engine "learns" the address (for instance, symmetric RTP enabled) this will then contain the learned address.
Parameters
instance The instance that we want to get the incoming source address for
address A structure to put the address into
Definition at line 665 of file rtp_engine.c.
References ao2_lock, ao2_unlock, ast_sockaddr_copy(), and ast_rtp_instance::incoming_source_address.
 {
    ao2_lock(instance);
    ast_sockaddr_copy(address, &instance->incoming_source_address);
    ao2_unlock(instance);
 }
ast_rtp_instance_get_keepalive()
int ast_rtp_instance_get_keepalive (struct ast_rtp_instance * instance)
Get the RTP keepalive interval.
Parameters
instance The RTP instance
Return values
period Keepalive interval value
Example usage:
int interval = ast_rtp_instance_get_keepalive(instance);
This gets the RTP keepalive interval value for the RTP instance pointed to by 'instance'.
Since
1.8
Definition at line 2695 of file rtp_engine.c.
References ast_rtp_instance::keepalive.
Referenced by check_rtp_timeout(), and send_keepalive().
 {
    return instance->keepalive;
 }
ast_rtp_instance_get_last_rx()
time_t ast_rtp_instance_get_last_rx (const struct ast_rtp_instance * rtp)
Definition at line 3768 of file rtp_engine.c.
References ast_rtp_instance::last_rx.
Referenced by rtp_check_timeout().
 {
    return rtp->last_rx;
 }
ast_rtp_instance_get_last_tx()
time_t ast_rtp_instance_get_last_tx (const struct ast_rtp_instance * rtp)
Get the last RTP transmission time.
Parameters
rtp The instance from which to get the last transmission time
Returns
The last RTP transmission time
Definition at line 3758 of file rtp_engine.c.
References ast_rtp_instance::last_tx.
Referenced by send_keepalive().
 {
    return rtp->last_tx;
 }
ast_rtp_instance_get_local_address()
void ast_rtp_instance_get_local_address (struct ast_rtp_instance * instance, struct ast_sockaddr * address)
Get the local address that we are expecting RTP on.
Parameters
instance The RTP instance to get the address from
address The variable to store the address in
Example usage:
struct ast_sockaddr address;
ast_rtp_instance_get_local_address(instance, &address);
This gets the local address that we are expecting RTP on and stores it in the 'address' structure.
Since
1.8
Definition at line 643 of file rtp_engine.c.
References ao2_lock, ao2_unlock, ast_sockaddr_copy(), and ast_rtp_instance::local_address.
Referenced by add_sdp(), ast_rtp_ice_turn_request(), ast_rtp_prop_set(), ast_rtp_remote_address_set(), channel_read_rtp(), configure_local_rtp(), create_outgoing_sdp_stream(), get_our_media_address(), handle_open_receive_channel_ack_message(), multicast_send_control_packet(), send_start_rtp(), sip_acf_channel_read(), sip_allow_anyrtp_remote(), skinny_set_rtp_peer(), test_init_rtp_instances(), unicast_rtp_request(), and unistim_set_rtp_peer().
 {
    ao2_lock(instance);
    ast_sockaddr_copy(address, &instance->local_address);
    ao2_unlock(instance);
 }
ast_rtp_instance_get_prop()
int ast_rtp_instance_get_prop (struct ast_rtp_instance * instance, enum ast_rtp_property property)
Get the value of an RTP instance property.
Parameters
instance The RTP instance to get the property from
property The property to get
Return values
Current value of the property
Example usage:
ast_rtp_instance_get_prop(instance, AST_RTP_PROPERTY_NAT);
This returns the current value of the NAT property on the instance pointed to by instance.
Since
1.8
Definition at line 716 of file rtp_engine.c.
References ao2_lock, ao2_unlock, and ast_rtp_instance::properties.
Referenced by ast_rtcp_interpret(), ast_rtp_dtmf_compatible(), ast_rtp_read(), bridge_p2p_rtp_write(), process_dtmf_cisco(), process_dtmf_rfc2833(), rtp_raw_write(), and rtp_write_rtcp_psfb().
 {
    int prop;
    ao2_lock(instance);
    prop = instance->properties[property];
    ao2_unlock(instance);
    return prop;
 }
ast_rtp_instance_get_quality()
char* ast_rtp_instance_get_quality (struct ast_rtp_instance * instance, enum ast_rtp_instance_stat_field field, char * buf, size_t size)
Retrieve quality statistics about an RTP instance.
Parameters
instance Instance to get statistics on
field What quality statistic to retrieve
buf What buffer to put the result into
size Size of the above buffer
Return values
non-NULL success
NULL failure
Example usage:
char quality[AST_MAX_USER_FIELD];
ast_rtp_instance_get_quality(instance, AST_RTP_INSTANCE_STAT_FIELD_QUALITY, &buf, sizeof(buf));
This retrieves general quality statistics and places a text representation into the buf pointed to by buf.
Since
1.8
Definition at line 2460 of file rtp_engine.c.
References ast_rtp_instance_get_stats(), AST_RTP_INSTANCE_STAT_ALL, AST_RTP_INSTANCE_STAT_COMBINED_JITTER, AST_RTP_INSTANCE_STAT_COMBINED_LOSS, AST_RTP_INSTANCE_STAT_COMBINED_RTT, AST_RTP_INSTANCE_STAT_FIELD_QUALITY, AST_RTP_INSTANCE_STAT_FIELD_QUALITY_JITTER, AST_RTP_INSTANCE_STAT_FIELD_QUALITY_LOSS, AST_RTP_INSTANCE_STAT_FIELD_QUALITY_RTT, buf, ast_rtp_instance_stats::local_maxjitter, ast_rtp_instance_stats::local_maxrxploss, ast_rtp_instance_stats::local_minjitter, ast_rtp_instance_stats::local_minrxploss, ast_rtp_instance_stats::local_normdevjitter, ast_rtp_instance_stats::local_normdevrxploss, ast_rtp_instance_stats::local_ssrc, ast_rtp_instance_stats::local_stdevjitter, ast_rtp_instance_stats::local_stdevrxploss, ast_rtp_instance_stats::maxrtt, ast_rtp_instance_stats::minrtt, ast_rtp_instance_stats::normdevrtt, NULL, ast_rtp_instance_stats::remote_maxjitter, ast_rtp_instance_stats::remote_maxrxploss, ast_rtp_instance_stats::remote_minjitter, ast_rtp_instance_stats::remote_minrxploss, ast_rtp_instance_stats::remote_normdevjitter, ast_rtp_instance_stats::remote_normdevrxploss, ast_rtp_instance_stats::remote_ssrc, ast_rtp_instance_stats::remote_stdevjitter, ast_rtp_instance_stats::remote_stdevrxploss, ast_rtp_instance_stats::rtt, ast_rtp_instance_stats::rxcount, ast_rtp_instance_stats::rxjitter, ast_rtp_instance_stats::rxploss, ast_rtp_instance_stats::stdevrtt, ast_rtp_instance_stats::txcount, ast_rtp_instance_stats::txjitter, and ast_rtp_instance_stats::txploss.
Referenced by ast_rtp_instance_set_stats_vars(), channel_read_rtcp(), handle_request_bye(), sip_acf_channel_read(), and sip_hangup().
 {
    struct ast_rtp_instance_stats stats = { 0, };
    enum ast_rtp_instance_stat stat;
    /* Determine what statistics we will need to retrieve based on field passed in */
    if (field == AST_RTP_INSTANCE_STAT_FIELD_QUALITY) {
       stat = AST_RTP_INSTANCE_STAT_ALL;
    } else if (field == AST_RTP_INSTANCE_STAT_FIELD_QUALITY_JITTER) {
       stat = AST_RTP_INSTANCE_STAT_COMBINED_JITTER;
    } else if (field == AST_RTP_INSTANCE_STAT_FIELD_QUALITY_LOSS) {
       stat = AST_RTP_INSTANCE_STAT_COMBINED_LOSS;
    } else if (field == AST_RTP_INSTANCE_STAT_FIELD_QUALITY_RTT) {
       stat = AST_RTP_INSTANCE_STAT_COMBINED_RTT;
    } else {
       return NULL;
    }
    /* Attempt to actually retrieve the statistics we need to generate the quality string */
    if (ast_rtp_instance_get_stats(instance, &stats, stat)) {
       return NULL;
    }
    /* Now actually fill the buffer with the good information */
    if (field == AST_RTP_INSTANCE_STAT_FIELD_QUALITY) {
       snprintf(buf, size, "ssrc=%u;themssrc=%u;lp=%u;rxjitter=%f;rxcount=%u;txjitter=%f;txcount=%u;rlp=%u;rtt=%f",
           stats.local_ssrc, stats.remote_ssrc, stats.rxploss, stats.rxjitter, stats.rxcount, stats.txjitter, stats.txcount, stats.txploss, stats.rtt);
    } else if (field == AST_RTP_INSTANCE_STAT_FIELD_QUALITY_JITTER) {
       snprintf(buf, size, "minrxjitter=%f;maxrxjitter=%f;avgrxjitter=%f;stdevrxjitter=%f;reported_minjitter=%f;reported_maxjitter=%f;reported_avgjitter=%f;reported_stdevjitter=%f;",
           stats.local_minjitter, stats.local_maxjitter, stats.local_normdevjitter, sqrt(stats.local_stdevjitter), stats.remote_minjitter, stats.remote_maxjitter, stats.remote_normdevjitter, sqrt(stats.remote_stdevjitter));
    } else if (field == AST_RTP_INSTANCE_STAT_FIELD_QUALITY_LOSS) {
       snprintf(buf, size, "minrxlost=%f;maxrxlost=%f;avgrxlost=%f;stdevrxlost=%f;reported_minlost=%f;reported_maxlost=%f;reported_avglost=%f;reported_stdevlost=%f;",
           stats.local_minrxploss, stats.local_maxrxploss, stats.local_normdevrxploss, sqrt(stats.local_stdevrxploss), stats.remote_minrxploss, stats.remote_maxrxploss, stats.remote_normdevrxploss, sqrt(stats.remote_stdevrxploss));
    } else if (field == AST_RTP_INSTANCE_STAT_FIELD_QUALITY_RTT) {
       snprintf(buf, size, "minrtt=%f;maxrtt=%f;avgrtt=%f;stdevrtt=%f;", stats.minrtt, stats.maxrtt, stats.normdevrtt, stats.stdevrtt);
    }
    return buf;
 }
ast_rtp_instance_get_requested_target_address()
void ast_rtp_instance_get_requested_target_address (struct ast_rtp_instance * instance, struct ast_sockaddr * address)
Get the requested target address of the remote endpoint.
This returns the explicitly set address of a remote endpoint. Meaning this won't change unless specifically told to change. In most cases this should be the same as the incoming source address, except in cases where the engine "learns" the address in which case this and the incoming source address might differ.
Parameters
instance The instance that we want to get the requested target address for
address A structure to put the address into
Definition at line 673 of file rtp_engine.c.
References ao2_lock, ao2_unlock, ast_sockaddr_copy(), and ast_rtp_instance::requested_target_address.
Referenced by ast_rtp_read(), handle_response_invite(), and sip_allow_anyrtp_remote().
 {
    ao2_lock(instance);
    ast_sockaddr_copy(address, &instance->requested_target_address);
    ao2_unlock(instance);
 }
ast_rtp_instance_get_srtp()
struct ast_srtp* ast_rtp_instance_get_srtp (struct ast_rtp_instance * instance, int rtcp)
Obtain the SRTP instance associated with an RTP instance.
Parameters
instance the RTP instance
rtcp 1 to request instance for RTCP
Return values
the SRTP instance on success
NULL if no SRTP instance exists
Definition at line 2763 of file rtp_engine.c.
References ast_rtp_instance::rtcp_srtp, and ast_rtp_instance::srtp.
Referenced by __rtp_sendto(), ast_rtcp_read(), ast_rtp_change_source(), and ast_rtp_read().
 {
    if (rtcp && instance->rtcp_srtp) {
       return instance->rtcp_srtp;
    } else {
       return instance->srtp;
    }
 }
ast_rtp_instance_get_ssrc()
unsigned int ast_rtp_instance_get_ssrc (struct ast_rtp_instance * rtp)
Retrieve the local SSRC value that we will be using.
Parameters
rtp The RTP instance
Returns
The SSRC value
Definition at line 3778 of file rtp_engine.c.
References ao2_lock, ao2_unlock, ast_rtp_instance::engine, and ast_rtp_engine::ssrc_get.
Referenced by add_ssrc_to_stream(), ast_srtp_unprotect(), create_outgoing_sdp_stream(), and rtcp_debug_test_addr().
 {
    unsigned int ssrc = 0;
    ao2_lock(rtp);
    if (rtp->engine->ssrc_get) {
       ssrc = rtp->engine->ssrc_get(rtp);
    }
    ao2_unlock(rtp);
    return ssrc;
 }
ast_rtp_instance_get_stats()
int ast_rtp_instance_get_stats (struct ast_rtp_instance * instance, struct ast_rtp_instance_stats * stats, enum ast_rtp_instance_stat stat)
Retrieve statistics about an RTP instance.
Parameters
instance Instance to get statistics on
stats Structure to put results into
stat What statistic(s) to retrieve
Return values
0 success
-1 failure
Example usage:
struct ast_rtp_instance_stats stats;
ast_rtp_instance_get_stats(instance, &stats, AST_RTP_INSTANCE_STAT_ALL);
This retrieves all statistics the underlying RTP engine supports and puts the values into the stats structure.
Since
1.8
Definition at line 2446 of file rtp_engine.c.
References ao2_lock, ao2_unlock, ast_rtp_instance::engine, and ast_rtp_engine::get_stat.
Referenced by ast_rtp_instance_get_quality(), ast_rtp_instance_get_stats_all_json(), ast_sip_session_media_stats_save(), ast_srtp_unprotect(), AST_TEST_DEFINE(), channel_read_rtcp(), cli_channelstats_print_body(), crypto_activate(), process_ssrc_attributes(), show_chanstats_cb(), and sip_acf_channel_read().
 {
    int res;
    if (instance->engine->get_stat) {
       ao2_lock(instance);
       res = instance->engine->get_stat(instance, stats, stat);
       ao2_unlock(instance);
    } else {
       res = -1;
    }
    return res;
 }
ast_rtp_instance_get_test()
struct ast_rtp_engine_test* ast_rtp_instance_get_test (struct ast_rtp_instance * instance)
Obtain a pointer to the test callbacks on an RTP instance.
Parameters
instance the RTP instance
Return values
test callbacks if present
NULL if not present
Definition at line 2901 of file rtp_engine.c.
References ast_rtp_instance::engine, and ast_rtp_engine::test.
Referenced by __rtp_recvfrom(), ast_rtcp_interpret(), ast_rtp_instance_drop_packets(), ast_rtp_instance_get_recv_buffer_count(), ast_rtp_instance_get_recv_buffer_max(), ast_rtp_instance_get_sdes_received(), ast_rtp_instance_get_send_buffer_count(), ast_rtp_instance_queue_report(), ast_rtp_instance_reset_test_engine(), ast_rtp_instance_set_schedid(), and rtp_raw_write().
 {
    return instance->engine->test;
 }
ast_rtp_instance_get_timeout()
int ast_rtp_instance_get_timeout (struct ast_rtp_instance * instance)
Get the RTP timeout value.
Parameters
instance The RTP instance
Return values
timeout value
Example usage:
int timeout = ast_rtp_instance_get_timeout(instance);
This gets the RTP timeout value for the RTP instance pointed to by 'instance'.
Since
1.8
Definition at line 2685 of file rtp_engine.c.
References ast_rtp_instance::timeout.
Referenced by apply_negotiated_sdp_stream(), check_rtp_timeout(), and rtp_check_timeout().
 {
    return instance->timeout;
 }
ast_rtp_instance_make_compatible()
int ast_rtp_instance_make_compatible (struct ast_channel * chan, struct ast_rtp_instance * instance, struct ast_channel * peer)
Request that the underlying RTP engine make two RTP instances compatible with eachother.
Parameters
chan Our own Asterisk channel
instance The first RTP instance
peer The peer Asterisk channel
Return values
0 success
-1 failure
Example usage:
ast_rtp_instance_make_compatible(instance, peer);
This makes the RTP instance for 'peer' compatible with 'instance' and vice versa.
Since
1.8
Definition at line 2589 of file rtp_engine.c.
References ao2_ref, ast_channel_lock, ast_channel_tech(), ast_channel_unlock, ast_log, ast_rtp_instance_get_glue(), ast_rtp_instance::engine, ast_rtp_glue::get_rtp_info, LOG_ERROR, ast_rtp_engine::make_compatible, NULL, type, and ast_rtp_glue::type.
 {
    struct ast_rtp_glue *glue;
    struct ast_rtp_instance *peer_instance = NULL;
    int res = -1;
    if (!instance->engine->make_compatible) {
       return -1;
    }
    ast_channel_lock(peer);
    if (!(glue = ast_rtp_instance_get_glue(ast_channel_tech(peer)->type))) {
       ast_channel_unlock(peer);
       return -1;
    }
    glue->get_rtp_info(peer, &peer_instance);
    if (!peer_instance) {
       ast_log(LOG_ERROR, "Unable to get_rtp_info for peer type %s\n", glue->type);
       ast_channel_unlock(peer);
       return -1;
    }
    if (peer_instance->engine != instance->engine) {
       ast_log(LOG_ERROR, "Peer engine mismatch for type %s\n", glue->type);
       ast_channel_unlock(peer);
       ao2_ref(peer_instance, -1);
       return -1;
    }
    /*
     * XXX Good thing nothing calls this function because we would need
     * deadlock avoidance to get the two instance locks.
     */
    res = instance->engine->make_compatible(chan, instance, peer, peer_instance);
    ast_channel_unlock(peer);
    ao2_ref(peer_instance, -1);
    peer_instance = NULL;
    return res;
 }
ast_rtp_instance_new()
struct ast_rtp_instance* ast_rtp_instance_new (const char * engine_name, struct ast_sched_context * sched, const struct ast_sockaddr * sa, void * data)
Create a new RTP instance.
Parameters
engine_name Name of the engine to use for the RTP instance
sched Scheduler context that the RTP engine may want to use
sa Address we want to bind to
data Unique data for the engine
Return values
non-NULL success
NULL failure
Example usage:
struct ast_rtp_instance *instance = NULL;
instance = ast_rtp_instance_new(NULL, sched, &sin, NULL);
This creates a new RTP instance using the default engine and asks the RTP engine to bind to the address given in the address structure.
Note
The RTP engine does not have to use the address provided when creating an RTP instance. It may choose to use another depending on it's own configuration.
Since
1.8
Definition at line 465 of file rtp_engine.c.
References ao2_alloc, ao2_lock, ao2_ref, ao2_unlock, ast_debug, ast_log, ast_module_running_ref, ast_module_unref, ast_rtp_codecs_payloads_initialize(), AST_RWLIST_FIRST, AST_RWLIST_RDLOCK, AST_RWLIST_TRAVERSE, AST_RWLIST_UNLOCK, ast_sockaddr_copy(), ast_strlen_zero, AST_VECTOR_INIT, ast_rtp_instance::codecs, ast_rtp_instance::engine, instance_destructor(), ast_rtp_instance::local_address, LOG_ERROR, ast_rtp_engine::mod, ast_rtp_engine::name, ast_rtp_engine::new, and NULL.
Referenced by AST_TEST_DEFINE(), configure_local_rtp(), create_rtp(), dialog_initialize_rtp(), jingle_alloc(), jingle_enable_video(), multicast_rtp_request(), start_rtp(), test_init_rtp_instances(), and unicast_rtp_request().
 {
    struct ast_sockaddr address = {{0,}};
    struct ast_rtp_instance *instance = NULL;
    struct ast_rtp_engine *engine = NULL;
    struct ast_module *mod_ref;
    AST_RWLIST_RDLOCK(&engines);
    /* If an engine name was specified try to use it or otherwise use the first one registered */
    if (!ast_strlen_zero(engine_name)) {
       AST_RWLIST_TRAVERSE(&engines, engine, entry) {
          if (!strcmp(engine->name, engine_name)) {
             break;
          }
       }
    } else {
       engine = AST_RWLIST_FIRST(&engines);
    }
    /* If no engine was actually found bail out now */
    if (!engine) {
       ast_log(LOG_ERROR, "No RTP engine was found. Do you have one loaded?\n");
       AST_RWLIST_UNLOCK(&engines);
       return NULL;
    }
    /* Bump up the reference count before we return so the module can not be unloaded */
    mod_ref = ast_module_running_ref(engine->mod);
    AST_RWLIST_UNLOCK(&engines);
    if (!mod_ref) {
       /* BUGBUG: improve handling of this situation. */
       return NULL;
    }
    /* Allocate a new RTP instance */
    if (!(instance = ao2_alloc(sizeof(*instance), instance_destructor))) {
       ast_module_unref(engine->mod);
       return NULL;
    }
    instance->engine = engine;
    ast_sockaddr_copy(&instance->local_address, sa);
    ast_sockaddr_copy(&address, sa);
    if (ast_rtp_codecs_payloads_initialize(&instance->codecs)) {
       ao2_ref(instance, -1);
       return NULL;
    }
    /* Initialize RTP extension support */
    if (AST_VECTOR_INIT(&instance->extmap_enabled, 0) ||
       AST_VECTOR_INIT(&instance->extmap_negotiated, 0) ||
       AST_VECTOR_INIT(&instance->extmap_unique_ids, 0)) {
       ao2_ref(instance, -1);
       return NULL;
    }
    ast_debug(1, "Using engine '%s' for RTP instance '%p'\n", engine->name, instance);
    /*
     * And pass it off to the engine to setup
     *
     * Lock in case the RTP engine has other threads that
     * need synchronization with the construction.
     */
    ao2_lock(instance);
    if (instance->engine->new(instance, sched, &address, data)) {
       ast_debug(1, "Engine '%s' failed to setup RTP instance '%p'\n", engine->name, instance);
       ao2_unlock(instance);
       ao2_ref(instance, -1);
       return NULL;
    }
    ao2_unlock(instance);
    ast_debug(1, "RTP instance '%p' is setup and ready to go\n", instance);
    return instance;
 }
ast_rtp_instance_read()
struct ast_frame* ast_rtp_instance_read (struct ast_rtp_instance * instance, int rtcp)
Receive a frame over RTP.
Parameters
instance The RTP instance to receive frame on
rtcp Whether to read in RTCP or not
Return values
non-NULL success
NULL failure
Example usage:
struct ast_frame *frame;
frame = ast_rtp_instance_read(instance, 0);
This asks the RTP engine to read in RTP from the instance and return it as an Asterisk frame.
Since
1.8
Definition at line 578 of file rtp_engine.c.
References ao2_lock, ao2_unlock, ast_rtp_instance::engine, and ast_rtp_engine::read.
Referenced by AST_TEST_DEFINE(), jingle_read(), media_session_rtcp_read_callback(), media_session_rtp_read_callback(), mgcp_rtp_read(), ooh323_rtp_read(), rtp_read(), sip_rtp_read(), skinny_rtp_read(), test_read_frames(), and unistim_rtp_read().
 {
    struct ast_frame *frame;
    ao2_lock(instance);
    frame = instance->engine->read(instance, rtcp);
    ao2_unlock(instance);
    return frame;
 }
ast_rtp_instance_sendcng()
int ast_rtp_instance_sendcng (struct ast_rtp_instance * instance, int level)
Send a comfort noise packet to the RTP instance.
Parameters
instance The RTP instance
level Magnitude of the noise level
Return values
0 Success
non-zero Failure
Definition at line 2772 of file rtp_engine.c.
References ao2_lock, ao2_unlock, ast_rtp_instance::engine, and ast_rtp_engine::sendcng.
Referenced by check_rtp_timeout(), do_monitor(), and send_keepalive().
 {
    int res;
    if (instance->engine->sendcng) {
       ao2_lock(instance);
       res = instance->engine->sendcng(instance, level);
       ao2_unlock(instance);
    } else {
       res = -1;
    }
    return res;
 }
ast_rtp_instance_set_bridged()
void ast_rtp_instance_set_bridged (struct ast_rtp_instance * instance, struct ast_rtp_instance * bridged)
Set the other RTP instance that an instance is bridged to.
Parameters
instance The RTP instance that we want to set the bridged value on
bridged The RTP instance they are bridged to
Since
12
Definition at line 2244 of file rtp_engine.c.
References ao2_lock, ao2_unlock, and ast_rtp_instance::bridged.
Referenced by native_rtp_bridge_start(), and native_rtp_bridge_stop().
 {
    ao2_lock(instance);
    instance->bridged = bridged;
    ao2_unlock(instance);
 }
ast_rtp_instance_set_channel_id()
void ast_rtp_instance_set_channel_id (struct ast_rtp_instance * instance, const char * uniqueid)
Set the channel that owns this RTP instance.
Parameters
instance The RTP instance
uniqueid The uniqueid of the channel
Since
12
Definition at line 553 of file rtp_engine.c.
References ast_copy_string(), and ast_rtp_instance::channel_uniqueid.
Referenced by apply_negotiated_sdp_stream(), jingle_enable_video(), jingle_set_owner(), mgcp_set_owner(), multicast_rtp_request(), set_channel_on_rtp_instance(), sip_set_owner(), skinny_set_owner(), start_rtp(), unicast_rtp_request(), and unistim_set_owner().
 {
    ast_copy_string(instance->channel_uniqueid, uniqueid, sizeof(instance->channel_uniqueid));
 }
ast_rtp_instance_set_data()
void ast_rtp_instance_set_data (struct ast_rtp_instance * instance, void * data)
Set the data portion of an RTP instance.
Parameters
instance The RTP instance to manipulate
data Pointer to data
Example usage:
ast_rtp_instance_set_data(instance, blob);
This sets the data pointer on the RTP instance pointed to by 'instance' to blob.
Since
1.8
Definition at line 558 of file rtp_engine.c.
References ast_rtp_instance::data.
Referenced by ast_rtp_new(), multicast_rtp_new(), and test_sip_rtpqos_1_new().
 {
    instance->data = data;
 }
ast_rtp_instance_set_extended_prop()
void ast_rtp_instance_set_extended_prop (struct ast_rtp_instance * instance, int property, void * value)
Set the value of an RTP instance extended property.
Parameters
instance The RTP instance to set the extended property on
property The extended property to set
value The value to set the extended property to
Since
1.8
Definition at line 681 of file rtp_engine.c.
References ao2_lock, ao2_unlock, ast_rtp_instance::engine, and ast_rtp_engine::extended_prop_set.
 {
    if (instance->engine->extended_prop_set) {
       ao2_lock(instance);
       instance->engine->extended_prop_set(instance, property, value);
       ao2_unlock(instance);
    }
 }
ast_rtp_instance_set_hold_timeout()
void ast_rtp_instance_set_hold_timeout (struct ast_rtp_instance * instance, int timeout)
Set the RTP timeout value for when the instance is on hold.
Parameters
instance The RTP instance
timeout Value to set the timeout to
Example usage:
ast_rtp_instance_set_hold_timeout(instance, 5000);
This sets the RTP hold timeout value on 'instance' to be 5000.
Since
1.8
Definition at line 2675 of file rtp_engine.c.
References ast_rtp_instance::holdtimeout, and timeout.
Referenced by check_rtp_timeout(), and dialog_initialize_rtp().
 {
    instance->holdtimeout = timeout;
 }
ast_rtp_instance_set_incoming_source_address()
int ast_rtp_instance_set_incoming_source_address (struct ast_rtp_instance * instance, const struct ast_sockaddr * address)
Set the incoming source address of the remote endpoint that we are sending RTP to.
This sets the incoming source address the engine is sending RTP to. Usually this will be the same as the requested target address, however in the case where the engine "learns" the address (for instance, symmetric RTP enabled) this will then contain the learned address.
Parameters
instance The RTP instance to change the address on
address Address to set it to
Return values
0 success
-1 failure
Definition at line 606 of file rtp_engine.c.
References ao2_lock, ao2_unlock, and rtp_instance_set_incoming_source_address_nolock().
Referenced by ast_rtp_read().
 {
    ao2_lock(instance);
    rtp_instance_set_incoming_source_address_nolock(instance, address);
    ao2_unlock(instance);
    return 0;
 }
ast_rtp_instance_set_keepalive()
void ast_rtp_instance_set_keepalive (struct ast_rtp_instance * instance, int timeout)
Set the RTP keepalive interval.
Parameters
instance The RTP instance
timeout Value to set the keepalive interval to
Example usage:
ast_rtp_instance_set_keepalive(instance, 5000);
This sets the RTP keepalive interval on 'instance' to be 5000.
Since
1.8
Definition at line 2680 of file rtp_engine.c.
References ast_rtp_instance::keepalive.
Referenced by apply_negotiated_sdp_stream(), and dialog_initialize_rtp().
 {
    instance->keepalive = interval;
 }
ast_rtp_instance_set_last_rx()
void ast_rtp_instance_set_last_rx (struct ast_rtp_instance * rtp, time_t time)
Set the last RTP reception time.
Parameters
rtp The instance on which to set the last reception time
time The last reception time
Definition at line 3773 of file rtp_engine.c.
References ast_rtp_instance::last_rx.
Referenced by check_for_rtp_changes(), create_rtp(), media_session_rtcp_read_callback(), and media_session_rtp_read_callback().
 {
    rtp->last_rx = time;
 }
ast_rtp_instance_set_last_tx()
void ast_rtp_instance_set_last_tx (struct ast_rtp_instance * rtp, time_t time)
Set the last RTP transmission time.
Parameters
rtp The instance on which to set the last transmission time
time The last transmission time
Definition at line 3763 of file rtp_engine.c.
References ast_rtp_instance::last_tx.
Referenced by __rtp_sendto().
 {
    rtp->last_tx = time;
 }
ast_rtp_instance_set_local_address()
int ast_rtp_instance_set_local_address (struct ast_rtp_instance * instance, const struct ast_sockaddr * address)
Set the address that we are expecting to receive RTP on.
Parameters
instance The RTP instance to change the address on
address Address to set it to
Return values
0 success
-1 failure
Example usage:
ast_rtp_instance_set_local_address(instance, &sin);
This changes the local address that RTP is expected on to the address given in the sin structure.
Since
1.8
Definition at line 588 of file rtp_engine.c.
References ao2_lock, ao2_unlock, ast_sockaddr_copy(), and ast_rtp_instance::local_address.
Referenced by ast_rtp_remote_address_set(), and rtp_allocate_transport().
 {
    ao2_lock(instance);
    ast_sockaddr_copy(&instance->local_address, address);
    ao2_unlock(instance);
    return 0;
 }
ast_rtp_instance_set_prop()
void ast_rtp_instance_set_prop (struct ast_rtp_instance * instance, enum ast_rtp_property property, int value)
Set the value of an RTP instance property.
Parameters
instance The RTP instance to set the property on
property The property to modify
value The value to set the property to
Example usage:
ast_rtp_instance_set_prop(instance, AST_RTP_PROPERTY_NAT, 1);
This enables the AST_RTP_PROPERTY_NAT property on the instance pointed to by instance.
Since
1.8
Definition at line 705 of file rtp_engine.c.
References ao2_lock, ao2_unlock, ast_rtp_instance::engine, ast_rtp_engine::prop_set, ast_rtp_instance::properties, and value.
Referenced by ast_rtp_ice_start_media(), check_for_rtp_changes(), configure_local_rtp(), configure_rtcp(), create_addr_from_peer(), create_rtp(), dialog_initialize_rtp(), do_setnat(), enable_rtcp(), get_codecs(), handle_request_invite(), jingle_alloc(), jingle_enable_video(), pjsip_acf_dtmf_mode_write(), process_sdp(), sip_dtmfmode(), sip_set_rtp_peer(), start_rtp(), test_init_rtp_instances(), and transmit_reinvite_with_sdp().
 {
    ao2_lock(instance);
    instance->properties[property] = value;
    if (instance->engine->prop_set) {
       instance->engine->prop_set(instance, property, value);
    }
    ao2_unlock(instance);
 }
ast_rtp_instance_set_qos()
int ast_rtp_instance_set_qos (struct ast_rtp_instance * instance, int tos, int cos, const char * desc)
Set QoS parameters on an RTP session.
Parameters
instance Instance to set the QoS parameters on
tos Terms of service value
cos Class of service value
desc What is setting the QoS values
Return values
0 success
-1 failure
Example usage:
ast_rtp_instance_set_qos(instance, 0, 0, "Example");
This sets the TOS and COS values to 0 on the instance pointed to by instance.
Since
1.8
Definition at line 2169 of file rtp_engine.c.
References ao2_lock, ao2_unlock, ast_rtp_instance::engine, and ast_rtp_engine::qos.
Referenced by configure_local_rtp(), create_rtp(), dialog_initialize_rtp(), and start_rtp().
 {
    int res;
    if (instance->engine->qos) {
       ao2_lock(instance);
       res = instance->engine->qos(instance, tos, cos, desc);
       ao2_unlock(instance);
    } else {
       res = -1;
    }
    return res;
 }
ast_rtp_instance_set_read_format()
int ast_rtp_instance_set_read_format (struct ast_rtp_instance * instance, struct ast_format * format)
Request that the underlying RTP engine provide audio frames in a specific format.
Parameters
instance The RTP instance to change read format on
format Format that frames are wanted in
Return values
0 success
-1 failure
Example usage:
struct ast_format tmp_fmt;
ast_rtp_instance_set_read_format(instance, ast_format_set(&tmp_fmt, AST_FORMAT_ULAW, 0));
This requests that the RTP engine provide audio frames in the ULAW format.
Since
1.8
Definition at line 2560 of file rtp_engine.c.
References ao2_lock, ao2_unlock, ast_rtp_instance::engine, and ast_rtp_engine::set_read_format.
Referenced by sip_new(), and sip_setoption().
 {
    int res;
    if (instance->engine->set_read_format) {
       ao2_lock(instance);
       res = instance->engine->set_read_format(instance, format);
       ao2_unlock(instance);
    } else {
       res = -1;
    }
    return res;
 }
ast_rtp_instance_set_remote_ssrc()
void ast_rtp_instance_set_remote_ssrc (struct ast_rtp_instance * rtp, unsigned int ssrc)
Set the remote SSRC for an RTP instance.
Since
15.0.0
Parameters
rtp The RTP instance
ssrc The remote SSRC
Definition at line 3821 of file rtp_engine.c.
References ao2_lock, ao2_unlock, ast_rtp_instance::engine, and ast_rtp_engine::set_remote_ssrc.
Referenced by process_ssrc_attributes().
 {
    ao2_lock(rtp);
    if (rtp->engine->set_remote_ssrc) {
       rtp->engine->set_remote_ssrc(rtp, ssrc);
    }
    ao2_unlock(rtp);
 }
ast_rtp_instance_set_requested_target_address()
int ast_rtp_instance_set_requested_target_address (struct ast_rtp_instance * instance, const struct ast_sockaddr * address)
Set the requested target address of the remote endpoint.
This should always be the address of the remote endpoint. Consequently, this can differ from the address the engine is sending RTP to. However, usually they will be the same except in some circumstances (for instance when the engine "learns" the address if symmetric RTP is enabled).
Parameters
instance The RTP instance to change the address on
address Address to set it to
Return values
0 success
-1 failure
Definition at line 616 of file rtp_engine.c.
References ao2_lock, ao2_unlock, ast_sockaddr_copy(), ast_rtp_instance::requested_target_address, and rtp_instance_set_incoming_source_address_nolock().
 {
    ao2_lock(instance);
    ast_sockaddr_copy(&instance->requested_target_address, address);
    rtp_instance_set_incoming_source_address_nolock(instance, address);
    ao2_unlock(instance);
    return 0;
 }
ast_rtp_instance_set_stats_vars()
void ast_rtp_instance_set_stats_vars (struct ast_channel * chan, struct ast_rtp_instance * instance)
Set standard statistics from an RTP instance on a channel.
Parameters
chan Channel to set the statistics on
instance The RTP instance that statistics will be retrieved from
Note
Absolutely NO channel locks should be held before calling this function.
Example usage:
ast_rtp_instance_set_stats_vars(chan, rtp);
This retrieves standard statistics from the RTP instance rtp and sets it on the channel pointed to by chan.
Since
1.8
Definition at line 2500 of file rtp_engine.c.
References ast_channel_bridge_peer(), ast_channel_lock, ast_channel_lock_both, ast_channel_stage_snapshot(), ast_channel_stage_snapshot_done(), ast_channel_unlock, ast_channel_unref, AST_MAX_USER_FIELD, ast_rtp_instance_get_quality(), AST_RTP_INSTANCE_STAT_FIELD_QUALITY, AST_RTP_INSTANCE_STAT_FIELD_QUALITY_JITTER, AST_RTP_INSTANCE_STAT_FIELD_QUALITY_LOSS, AST_RTP_INSTANCE_STAT_FIELD_QUALITY_RTT, pbx_builtin_setvar_helper(), and quality.
Referenced by handle_request_bye(), and sip_hangup().
 {
    char quality_buf[AST_MAX_USER_FIELD];
    char *quality;
    struct ast_channel *bridge;
    bridge = ast_channel_bridge_peer(chan);
    if (bridge) {
       ast_channel_lock_both(chan, bridge);
       ast_channel_stage_snapshot(bridge);
    } else {
       ast_channel_lock(chan);
    }
    ast_channel_stage_snapshot(chan);
    quality = ast_rtp_instance_get_quality(instance, AST_RTP_INSTANCE_STAT_FIELD_QUALITY,
       quality_buf, sizeof(quality_buf));
    if (quality) {
       pbx_builtin_setvar_helper(chan, "RTPAUDIOQOS", quality);
       if (bridge) {
          pbx_builtin_setvar_helper(bridge, "RTPAUDIOQOSBRIDGED", quality);
       }
    }
    quality = ast_rtp_instance_get_quality(instance,
       AST_RTP_INSTANCE_STAT_FIELD_QUALITY_JITTER, quality_buf, sizeof(quality_buf));
    if (quality) {
       pbx_builtin_setvar_helper(chan, "RTPAUDIOQOSJITTER", quality);
       if (bridge) {
          pbx_builtin_setvar_helper(bridge, "RTPAUDIOQOSJITTERBRIDGED", quality);
       }
    }
    quality = ast_rtp_instance_get_quality(instance,
       AST_RTP_INSTANCE_STAT_FIELD_QUALITY_LOSS, quality_buf, sizeof(quality_buf));
    if (quality) {
       pbx_builtin_setvar_helper(chan, "RTPAUDIOQOSLOSS", quality);
       if (bridge) {
          pbx_builtin_setvar_helper(bridge, "RTPAUDIOQOSLOSSBRIDGED", quality);
       }
    }
    quality = ast_rtp_instance_get_quality(instance,
       AST_RTP_INSTANCE_STAT_FIELD_QUALITY_RTT, quality_buf, sizeof(quality_buf));
    if (quality) {
       pbx_builtin_setvar_helper(chan, "RTPAUDIOQOSRTT", quality);
       if (bridge) {
          pbx_builtin_setvar_helper(bridge, "RTPAUDIOQOSRTTBRIDGED", quality);
       }
    }
    ast_channel_stage_snapshot_done(chan);
    ast_channel_unlock(chan);
    if (bridge) {
       ast_channel_stage_snapshot_done(bridge);
       ast_channel_unlock(bridge);
       ast_channel_unref(bridge);
    }
 }
ast_rtp_instance_set_stream_num()
void ast_rtp_instance_set_stream_num (struct ast_rtp_instance * instance, int stream_num)
Set the stream number for an RTP instance.
Since
15.0.0
Parameters
rtp The RTP instance
stream_num The stream identifier number
Definition at line 3830 of file rtp_engine.c.
References ao2_lock, ao2_unlock, ast_rtp_instance::engine, and ast_rtp_engine::set_stream_num.
Referenced by apply_negotiated_sdp_stream().
 {
    ao2_lock(rtp);
    if (rtp->engine->set_stream_num) {
       rtp->engine->set_stream_num(rtp, stream_num);
    }
    ao2_unlock(rtp);
 }
ast_rtp_instance_set_timeout()
void ast_rtp_instance_set_timeout (struct ast_rtp_instance * instance, int timeout)
Set the RTP timeout value.
Parameters
instance The RTP instance
timeout Value to set the timeout to
Example usage:
ast_rtp_instance_set_timeout(instance, 5000);
This sets the RTP timeout value on 'instance' to be 5000.
Since
1.8
Definition at line 2670 of file rtp_engine.c.
References timeout, and ast_rtp_instance::timeout.
Referenced by apply_negotiated_sdp_stream(), check_rtp_timeout(), configure_local_rtp(), and dialog_initialize_rtp().
 {
    instance->timeout = timeout;
 }
ast_rtp_instance_set_write_format()
int ast_rtp_instance_set_write_format (struct ast_rtp_instance * instance, struct ast_format * format)
Tell underlying RTP engine that audio frames will be provided in a specific format.
Parameters
instance The RTP instance to change write format on
format Format that frames will be provided in
Return values
0 success
-1 failure
Example usage:
struct ast_format tmp_fmt;
ast_rtp_instance_set_write_format(instance, ast_format_set(&tmp_fmt, AST_FORMAT_ULAW, 0));
This tells the underlying RTP engine that audio frames will be provided to it in ULAW format.
Since
1.8
Definition at line 2574 of file rtp_engine.c.
References ao2_lock, ao2_unlock, ast_rtp_instance::engine, ast_rtp_engine::set_read_format, and ast_rtp_engine::set_write_format.
Referenced by sip_new(), and sip_setoption().
 {
    int res;
    if (instance->engine->set_read_format) {
       ao2_lock(instance);
       res = instance->engine->set_write_format(instance, format);
       ao2_unlock(instance);
    } else {
       res = -1;
    }
    return res;
 }
ast_rtp_instance_stop()
void ast_rtp_instance_stop (struct ast_rtp_instance * instance)
Stop an RTP instance.
Parameters
instance Instance that media is no longer going to at this time
Example usage:
ast_rtp_instance_stop(instance);
This tells the RTP engine being used for the instance pointed to by instance that media is no longer going to it at this time, but may in the future.
Since
1.8
Definition at line 2183 of file rtp_engine.c.
References ao2_lock, ao2_unlock, ast_rtp_instance::engine, and ast_rtp_engine::stop.
Referenced by apply_negotiated_sdp_stream(), close_rtp_connection(), destroy_rtp(), jingle_session_destructor(), ooh323_destroy(), process_sdp(), stop_media_flows(), stream_stop(), and unistim_hangup_clean().
 {
    if (instance->engine->stop) {
       ao2_lock(instance);
       instance->engine->stop(instance);
       ao2_unlock(instance);
    }
 }
ast_rtp_instance_stun_request()
void ast_rtp_instance_stun_request (struct ast_rtp_instance * instance, struct ast_sockaddr * suggestion, const char * username)
Request that the underlying RTP engine send a STUN BIND request.
Parameters
instance The RTP instance
suggestion The suggested destination
username Optionally a username for the request
Example usage:
ast_rtp_instance_stun_request(instance, NULL, NULL);
This requests that the RTP engine send a STUN BIND request on the session pointed to by 'instance'.
Since
1.8
Definition at line 2661 of file rtp_engine.c.
References ast_rtp_instance::engine, and ast_rtp_engine::stun_request.
Referenced by jingle_interpret_google_transport().
 {
    if (instance->engine->stun_request) {
       instance->engine->stun_request(instance, suggestion, username);
    }
 }
ast_rtp_instance_update_source()
void ast_rtp_instance_update_source (struct ast_rtp_instance * instance)
Indicate that the RTP marker bit should be set on an RTP stream.
Parameters
instance Instance that the new media source is feeding into
Example usage:
ast_rtp_instance_update_source(instance);
This indicates that the source of media that is feeding the instance pointed to by instance has been updated and that the marker bit should be set.
Since
1.8
Definition at line 2151 of file rtp_engine.c.
References ao2_lock, ao2_unlock, ast_rtp_instance::engine, and ast_rtp_engine::update_source.
Referenced by jingle_indicate(), mgcp_indicate(), ooh323_indicate(), sip_answer(), sip_indicate(), sip_write(), and skinny_indicate().
 {
    if (instance->engine->update_source) {
       ao2_lock(instance);
       instance->engine->update_source(instance);
       ao2_unlock(instance);
    }
 }
ast_rtp_instance_write()
int ast_rtp_instance_write (struct ast_rtp_instance * instance, struct ast_frame * frame)
Send a frame out over RTP.
Parameters
instance The RTP instance to send frame out on
frame the frame to send out
Return values
0 success
-1 failure
Example usage:
ast_rtp_instance_write(instance, frame);
This gives the frame pointed to by frame to the RTP engine being used for the instance and asks that it be transmitted to the current remote address set on the RTP instance.
Since
1.8
Definition at line 568 of file rtp_engine.c.
References ao2_lock, ao2_unlock, ast_rtp_instance::engine, and ast_rtp_engine::write.
Referenced by AST_TEST_DEFINE(), chan_pjsip_indicate(), jingle_write(), media_session_rtp_write_callback(), mgcp_write(), ooh323_write(), rtp_write(), sip_indicate(), sip_write(), skinny_write(), test_write_frames(), and unistim_write().
 {
    int res;
    ao2_lock(instance);
    res = instance->engine->write(instance, frame);
    ao2_unlock(instance);
    return res;
 }
ast_rtp_lookup_mime_multiple2()
char* ast_rtp_lookup_mime_multiple2 (struct ast_str * buf, struct ast_format_cap * ast_format_capability, int rtp_capability, const int asterisk_format, enum ast_rtp_options options)
Convert formats into a string and put them into a buffer.
Parameters
buf Buffer to put the mime output into
ast_format_capability Asterisk Formats we are looking up.
rtp_capability RTP codes that we are looking up
asterisk_format Non-zero if the ast_format_capability structure is to be used, 0 if rtp_capability is to be used
options Additional options that may change the result
Return values
non-NULL success
NULL failure
Example usage:
char buf[256] = "";
struct ast_format tmp_fmt;
struct ast_format_cap *cap = ast_format_cap_alloc_nolock();
ast_format_cap_append(cap, ast_format_set(&tmp_fmt, AST_FORMAT_ULAW, 0));
ast_format_cap_append(cap, ast_format_set(&tmp_fmt, AST_FORMAT_GSM, 0));
char *mime = ast_rtp_lookup_mime_multiple2(&buf, sizeof(buf), cap, 0, 1, 0);
ast_format_cap_destroy(cap);
This returns the mime values for ULAW and ALAW in the buffer pointed to by buf.
Since
1.8
Definition at line 2045 of file rtp_engine.c.
References ao2_ref, ast_format_cap_count(), ast_format_cap_get_format(), ast_rtp_lookup_mime_subtype2(), AST_RTP_MAX, ast_str_append(), ast_str_buffer(), name, and NULL.
Referenced by process_sdp().
 {
    int found = 0;
    const char *name;
    if (!buf) {
       return NULL;
    }
    if (asterisk_format) {
       int x;
       struct ast_format *tmp_fmt;
       for (x = 0; x < ast_format_cap_count(ast_format_capability); x++) {
          tmp_fmt = ast_format_cap_get_format(ast_format_capability, x);
          name = ast_rtp_lookup_mime_subtype2(asterisk_format, tmp_fmt, 0, options);
          ao2_ref(tmp_fmt, -1);
          ast_str_append(&buf, 0, "%s|", name);
          found = 1;
       }
    } else {
       int x;
       ast_str_append(&buf, 0, "0x%x (", (unsigned int) rtp_capability);
       for (x = 1; x <= AST_RTP_MAX; x <<= 1) {
          if (rtp_capability & x) {
             name = ast_rtp_lookup_mime_subtype2(asterisk_format, NULL, x, options);
             ast_str_append(&buf, 0, "%s|", name);
             found = 1;
          }
       }
    }
    ast_str_append(&buf, 0, "%s", found ? ")" : "nothing)");
    return ast_str_buffer(buf);
 }
ast_rtp_lookup_mime_subtype2()
const char* ast_rtp_lookup_mime_subtype2 (const int asterisk_format, const struct ast_format * format, int code, enum ast_rtp_options options)
Retrieve mime subtype information on a payload.
Parameters
asterisk_format Non-zero to look up using Asterisk format
format Asterisk format to look up
code RTP code to look up
options Additional options that may change the result
Return values
Mime subtype success
NULL failure
Example usage:
const char *subtype = ast_rtp_lookup_mime_subtype2(1, ast_format_set(&tmp_fmt, AST_FORMAT_ULAW, 0), 0, 0);
This looks up the mime subtype for the ULAW format.
Since
1.8
Definition at line 1992 of file rtp_engine.c.
References ast_format_cmp(), AST_FORMAT_CMP_EQUAL, AST_FORMAT_CMP_NOT_EQUAL, ast_format_g726_aal2, ast_rtp_mime_types, AST_RTP_OPT_G726_NONSTANDARD, ast_rwlock_rdlock, ast_rwlock_unlock, mime_types_len, ast_rtp_mime_type::payload_type, ast_rtp_payload_type::rtp_code, and ast_rtp_mime_type::subtype.
Referenced by add_codec_to_sdp(), add_noncodec_to_sdp(), add_sdp(), add_tcodec_to_sdp(), add_vcodec_to_sdp(), ast_rtp_lookup_mime_multiple2(), generate_rtpmap_attr(), jingle_add_payloads_to_description(), transmit_connect(), transmit_connect_with_sdp(), transmit_modify_request(), and transmit_modify_with_sdp().
 {
    int i;
    const char *res = "";
    ast_rwlock_rdlock(&mime_types_lock);
    for (i = 0; i < mime_types_len; i++) {
       if (ast_rtp_mime_types[i].payload_type.asterisk_format && asterisk_format && format &&
          (ast_format_cmp(format, ast_rtp_mime_types[i].payload_type.format) != AST_FORMAT_CMP_NOT_EQUAL)) {
          if ((ast_format_cmp(format, ast_format_g726_aal2) == AST_FORMAT_CMP_EQUAL) &&
                (options & AST_RTP_OPT_G726_NONSTANDARD)) {
             res = "G726-32";
             break;
          } else {
             res = ast_rtp_mime_types[i].subtype;
             break;
          }
       } else if (!ast_rtp_mime_types[i].payload_type.asterisk_format && !asterisk_format &&
          ast_rtp_mime_types[i].payload_type.rtp_code == code) {
          res = ast_rtp_mime_types[i].subtype;
          break;
       }
    }
    ast_rwlock_unlock(&mime_types_lock);
    return res;
 }
ast_rtp_lookup_sample_rate2()
unsigned int ast_rtp_lookup_sample_rate2 (int asterisk_format, const struct ast_format * format, int code)
Get the sample rate associated with known RTP payload types.
Parameters
asterisk_format True if the value in format is to be used.
format An asterisk format
code from AST_RTP list
Returns
the sample rate if the format was found, zero if it was not found
Since
1.8
Definition at line 2022 of file rtp_engine.c.
References ast_format_cmp(), AST_FORMAT_CMP_NOT_EQUAL, ast_rtp_mime_types, ast_rwlock_rdlock, ast_rwlock_unlock, mime_types_len, ast_rtp_mime_type::payload_type, ast_rtp_payload_type::rtp_code, and ast_rtp_mime_type::sample_rate.
Referenced by add_codec_to_sdp(), add_noncodec_to_sdp(), add_tcodec_to_sdp(), add_vcodec_to_sdp(), generate_rtpmap_attr(), and jingle_add_payloads_to_description().
 {
    unsigned int i;
    unsigned int res = 0;
    ast_rwlock_rdlock(&mime_types_lock);
    for (i = 0; i < mime_types_len; ++i) {
       if (ast_rtp_mime_types[i].payload_type.asterisk_format && asterisk_format && format &&
          (ast_format_cmp(format, ast_rtp_mime_types[i].payload_type.format) != AST_FORMAT_CMP_NOT_EQUAL)) {
          res = ast_rtp_mime_types[i].sample_rate;
          break;
       } else if (!ast_rtp_mime_types[i].payload_type.asterisk_format && !asterisk_format &&
          ast_rtp_mime_types[i].payload_type.rtp_code == code) {
          res = ast_rtp_mime_types[i].sample_rate;
          break;
       }
    }
    ast_rwlock_unlock(&mime_types_lock);
    return res;
 }
ast_rtp_publish_rtcp_message()
void ast_rtp_publish_rtcp_message (struct ast_rtp_instance * rtp, struct stasis_message_type * message_type, struct ast_rtp_rtcp_report * report, struct ast_json * blob)
Publish an RTCP message to Stasis Message Bus API.
Since
12
Parameters
rtp The rtp instance object
message_type The RTP message type to publish
report The RTCP report object to publish. This should be an ao2 ref counted object. This routine will increase the reference count of the object.
blob Additional JSON objects to publish along with the RTCP information
Definition at line 3485 of file rtp_engine.c.
References ao2_alloc, ao2_cleanup, ao2_ref, ast_channel_snapshot_get_latest(), ast_json_ref(), ast_rtp_rtcp_received_type(), ast_rtp_rtcp_sent_type(), ast_rtp_topic(), ast_strlen_zero, ast_rtp_instance::channel_uniqueid, NULL, RAII_VAR, rtcp_message_payload_dtor(), rtcp_report_to_ami(), rtcp_report_to_json(), stasis_message_create(), STASIS_MESSAGE_TYPE_DEFN(), stasis_publish(), and to_ami().
Referenced by ast_rtcp_calculate_sr_rr_statistics(), and ast_rtcp_interpret().
 {
    RAII_VAR(struct rtcp_message_payload *, payload, NULL, ao2_cleanup);
    RAII_VAR(struct stasis_message *, message, NULL, ao2_cleanup);
    if (!message_type) {
       return;
    }
    payload = ao2_alloc(sizeof(*payload), rtcp_message_payload_dtor);
    if (!payload || !report) {
       return;
    }
    if (!ast_strlen_zero(rtp->channel_uniqueid)) {
       payload->snapshot = ast_channel_snapshot_get_latest(rtp->channel_uniqueid);
    }
    if (blob) {
       payload->blob = blob;
       ast_json_ref(blob);
    }
    ao2_ref(report, +1);
    payload->report = report;
    message = stasis_message_create(message_type, payload);
    if (!message) {
       return;
    }
    stasis_publish(ast_rtp_topic(), message);
 }
ast_rtp_red_buffer()
int ast_rtp_red_buffer (struct ast_rtp_instance * instance, struct ast_frame * frame)
Buffer a frame in an RTP instance for RED.
Parameters
instance The instance to buffer the frame on
frame Frame that we want to buffer
Return values
0 success
-1 failure
Since
1.8
Definition at line 2432 of file rtp_engine.c.
References ao2_lock, ao2_unlock, ast_rtp_instance::engine, and ast_rtp_engine::red_buffer.
Referenced by sip_write().
 {
    int res;
    if (instance->engine->red_buffer) {
       ao2_lock(instance);
       res = instance->engine->red_buffer(instance, frame);
       ao2_unlock(instance);
    } else {
       res = -1;
    }
    return res;
 }
ast_rtp_red_init()
int ast_rtp_red_init (struct ast_rtp_instance * instance, int buffer_time, int * payloads, int generations)
Initialize RED support on an RTP instance.
Parameters
instance The instance to initialize RED support on
buffer_time How long to buffer before sending
payloads Payload values
generations Number of generations
Return values
0 success
-1 failure
Since
1.8
Definition at line 2418 of file rtp_engine.c.
References ao2_lock, ao2_unlock, ast_rtp_instance::engine, and ast_rtp_engine::red_init.
Referenced by process_sdp().
 {
    int res;
    if (instance->engine->red_init) {
       ao2_lock(instance);
       res = instance->engine->red_init(instance, buffer_time, payloads, generations);
       ao2_unlock(instance);
    } else {
       res = -1;
    }
    return res;
 }
ast_rtp_rtcp_report_alloc()
struct ast_rtp_rtcp_report* ast_rtp_rtcp_report_alloc (unsigned int report_blocks)
Allocate an ao2 ref counted instance of ast_rtp_rtcp_report.
Parameters
report_blocks The number of report blocks to allocate
Return values
An ao2 ref counted ast_rtp_rtcp_report object on success
NULL on error
Definition at line 3474 of file rtp_engine.c.
References ao2_alloc, and rtp_rtcp_report_dtor().
Referenced by ast_rtcp_interpret(), ast_rtcp_write(), ast_rtp_read(), rtp_write_rtcp_fir(), and rtp_write_rtcp_psfb().
 {
    struct ast_rtp_rtcp_report *rtcp_report;
    /* Size of object is sizeof the report + the number of report_blocks * sizeof pointer */
    rtcp_report = ao2_alloc((sizeof(*rtcp_report) + report_blocks * sizeof(struct ast_rtp_rtcp_report_block *)),
       rtp_rtcp_report_dtor);
    return rtcp_report;
 }