Asterisk - The Open Source Telephony Project: test_stasis_endpoints.c File Reference
test_stasis_endpoints.c File Reference
Test endpoints.
#include "asterisk.h"
#include "asterisk/astobj2.h"
#include "asterisk/channel.h"
#include "asterisk/endpoints.h"
#include "asterisk/module.h"
#include "asterisk/stasis_channels.h"
#include "asterisk/stasis_endpoints.h"
#include "asterisk/stasis_test.h"
#include "asterisk/test.h"
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
AST_TEST_DEFINE (state_changes)
AST_TEST_DEFINE (cache_clear)
AST_TEST_DEFINE (channel_messages)
static int cache_update (struct stasis_message *msg, const void *data)
Message matcher looking for cache update messages.
static int load_module (void)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_DEFAULT , .description = "Endpoint stasis-related testing" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .requires = "res_stasis_test", }
static const struct ast_module_info * ast_module_info = &__mod_info
static const char * test_category = "/stasis/endpoints/"
Detailed Description
Test endpoints.
Author
David M. Lee, II <dlee@digium.com>
Definition in file test_stasis_endpoints.c.
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 297 of file test_stasis_endpoints.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 297 of file test_stasis_endpoints.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 297 of file test_stasis_endpoints.c.
AST_TEST_DEFINE() [1/3]
AST_TEST_DEFINE (state_changes)
Definition at line 70 of file test_stasis_endpoints.c.
References ao2_cleanup, ast_endpoint_create(), AST_ENDPOINT_OFFLINE, ast_endpoint_set_max_channels(), ast_endpoint_set_state(), ast_endpoint_shutdown(), ast_endpoint_snapshot_type(), ast_endpoint_topic(), ast_hangup(), AST_TEST_NOT_RUN, AST_TEST_PASS, sip_to_pjsip::info(), ast_endpoint_snapshot::max_channels, NULL, RAII_VAR, stasis_message_data(), stasis_message_sink_cb(), stasis_message_sink_create(), stasis_message_sink_wait_for_count(), stasis_message_type(), STASIS_SINK_DEFAULT_WAIT, stasis_subscribe, stasis_unsubscribe(), ast_endpoint_snapshot::state, sub, test_category, TEST_EXECUTE, TEST_INIT, and type.
 {
    RAII_VAR(struct ast_endpoint *, uut, NULL, ast_endpoint_shutdown);
    RAII_VAR(struct ast_channel *, chan, NULL, ast_hangup);
    RAII_VAR(struct stasis_message_sink *, sink, NULL, ao2_cleanup);
    RAII_VAR(struct stasis_subscription *, sub, NULL, stasis_unsubscribe);
    struct stasis_message *msg;
    struct stasis_message_type *type;
    struct ast_endpoint_snapshot *actual_snapshot;
    int actual_count;
    switch (cmd) {
    case TEST_INIT:
       info->name = __func__;
       info->category = test_category;
       info->summary = "Test endpoint updates as its state changes";
       info->description =
          "Test endpoint updates as its state changes";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    uut = ast_endpoint_create("TEST", __func__);
    ast_test_validate(test, NULL != uut);
    sink = stasis_message_sink_create();
    ast_test_validate(test, NULL != sink);
    sub = stasis_subscribe(ast_endpoint_topic(uut),
       stasis_message_sink_cb(), sink);
    ast_test_validate(test, NULL != sub);
    ast_endpoint_set_state(uut, AST_ENDPOINT_OFFLINE);
    actual_count = stasis_message_sink_wait_for_count(sink, 1,
       STASIS_SINK_DEFAULT_WAIT);
    ast_test_validate(test, 1 == actual_count);
    msg = sink->messages[0];
    type = stasis_message_type(msg);
    ast_test_validate(test, ast_endpoint_snapshot_type() == type);
    actual_snapshot = stasis_message_data(msg);
    ast_test_validate(test, AST_ENDPOINT_OFFLINE == actual_snapshot->state);
    ast_endpoint_set_max_channels(uut, 8675309);
    actual_count = stasis_message_sink_wait_for_count(sink, 2,
       STASIS_SINK_DEFAULT_WAIT);
    ast_test_validate(test, 2 == actual_count);
    msg = sink->messages[1];
    type = stasis_message_type(msg);
    ast_test_validate(test, ast_endpoint_snapshot_type() == type);
    actual_snapshot = stasis_message_data(msg);
    ast_test_validate(test, 8675309 == actual_snapshot->max_channels);
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [2/3]
AST_TEST_DEFINE (cache_clear)
Definition at line 126 of file test_stasis_endpoints.c.
References ao2_cleanup, ast_endpoint_create(), ast_endpoint_shutdown(), ast_endpoint_snapshot_type(), ast_endpoint_topic_all_cached(), ast_hangup(), AST_TEST_NOT_RUN, AST_TEST_PASS, cache_update(), sip_to_pjsip::info(), stasis_cache_update::new_snapshot, NULL, stasis_cache_update::old_snapshot, RAII_VAR, ast_endpoint_snapshot::resource, stasis_cache_update_type(), stasis_message_data(), stasis_message_sink_cb(), stasis_message_sink_create(), stasis_message_sink_wait_for(), stasis_message_type(), STASIS_SINK_DEFAULT_WAIT, stasis_subscribe, stasis_unsubscribe(), sub, ast_endpoint_snapshot::tech, test_category, TEST_EXECUTE, TEST_INIT, type, stasis_cache_update::type, and update().
 {
    RAII_VAR(struct ast_endpoint *, uut, NULL, ast_endpoint_shutdown);
    RAII_VAR(struct ast_channel *, chan, NULL, ast_hangup);
    RAII_VAR(struct stasis_message_sink *, sink, NULL, ao2_cleanup);
    RAII_VAR(struct stasis_subscription *, sub, NULL, stasis_unsubscribe);
    struct stasis_message *msg;
    struct stasis_message_type *type;
    struct ast_endpoint_snapshot *actual_snapshot;
    struct stasis_cache_update *update;
    int message_index;
    switch (cmd) {
    case TEST_INIT:
       info->name = __func__;
       info->category = test_category;
       info->summary = "Test endpoint state change messages";
       info->description = "Test endpoint state change messages";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    /* Subscribe to the cache topic */
    sink = stasis_message_sink_create();
    ast_test_validate(test, NULL != sink);
    sub = stasis_subscribe(
       ast_endpoint_topic_all_cached(),
       stasis_message_sink_cb(), sink);
    ast_test_validate(test, NULL != sub);
    uut = ast_endpoint_create("TEST", __func__);
    ast_test_validate(test, NULL != uut);
    /* Since the cache topic is a singleton (ew), it may have messages from
     * elsewheres that it's processing, or maybe even some final messages
     * from the prior test. We've got to wait_for our specific message,
     * instead of wait_for_count.
     */
    message_index = stasis_message_sink_wait_for(sink, 0,
       cache_update, __func__, STASIS_SINK_DEFAULT_WAIT);
    ast_test_validate(test, 0 <= message_index);
    /* First message should be a cache creation entry for our endpoint */
    msg = sink->messages[message_index];
    type = stasis_message_type(msg);
    ast_test_validate(test, stasis_cache_update_type() == type);
    update = stasis_message_data(msg);
    ast_test_validate(test, ast_endpoint_snapshot_type() == update->type);
    ast_test_validate(test, NULL == update->old_snapshot);
    actual_snapshot = stasis_message_data(update->new_snapshot);
    ast_test_validate(test, 0 == strcmp("TEST", actual_snapshot->tech));
    ast_test_validate(test,
       0 == strcmp(__func__, actual_snapshot->resource));
    ast_endpoint_shutdown(uut);
    uut = NULL;
    /* Note: there's a few messages between the creation and the clear.
     * Wait for all of them... */
    message_index = stasis_message_sink_wait_for(sink, message_index + 2,
       cache_update, __func__, STASIS_SINK_DEFAULT_WAIT);
    ast_test_validate(test, 0 <= message_index);
    /* Now we should have a cache removal entry */
    msg = sink->messages[message_index];
    type = stasis_message_type(msg);
    ast_test_validate(test, stasis_cache_update_type() == type);
    update = stasis_message_data(msg);
    ast_test_validate(test, ast_endpoint_snapshot_type() == update->type);
    actual_snapshot = stasis_message_data(update->old_snapshot);
    ast_test_validate(test, 0 == strcmp("TEST", actual_snapshot->tech));
    ast_test_validate(test,
       0 == strcmp(__func__, actual_snapshot->resource));
    ast_test_validate(test, NULL == update->new_snapshot);
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [3/3]
AST_TEST_DEFINE (channel_messages)
Definition at line 206 of file test_stasis_endpoints.c.
References ao2_cleanup, ast_channel_alloc, ast_channel_snapshot_type(), ast_endpoint_add_channel(), ast_endpoint_create(), ast_endpoint_shutdown(), ast_endpoint_snapshot_type(), ast_endpoint_topic(), ast_hangup(), AST_STATE_DOWN, AST_TEST_NOT_RUN, AST_TEST_PASS, sip_to_pjsip::info(), NULL, ast_endpoint_snapshot::num_channels, RAII_VAR, stasis_message_data(), stasis_message_sink_cb(), stasis_message_sink_create(), stasis_message_sink_wait_for_count(), stasis_message_type(), STASIS_SINK_DEFAULT_WAIT, stasis_subscribe, stasis_unsubscribe(), sub, test_category, TEST_EXECUTE, TEST_INIT, and type.
 {
    RAII_VAR(struct ast_endpoint *, uut, NULL, ast_endpoint_shutdown);
    RAII_VAR(struct ast_channel *, chan, NULL, ast_hangup);
    RAII_VAR(struct stasis_message_sink *, sink, NULL, ao2_cleanup);
    RAII_VAR(struct stasis_subscription *, sub, NULL, stasis_unsubscribe);
    struct stasis_message *msg;
    struct stasis_message_type *type;
    struct ast_endpoint_snapshot *actual_snapshot;
    int actual_count;
    switch (cmd) {
    case TEST_INIT:
       info->name = __func__;
       info->category = test_category;
       info->summary = "Test channel messages on an endpoint topic";
       info->description =
          "Test channel messages on an endpoint topic";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    uut = ast_endpoint_create("TEST", __func__);
    ast_test_validate(test, NULL != uut);
    sink = stasis_message_sink_create();
    ast_test_validate(test, NULL != sink);
    sub = stasis_subscribe(ast_endpoint_topic(uut),
       stasis_message_sink_cb(), sink);
    ast_test_validate(test, NULL != sub);
    chan = ast_channel_alloc(0, AST_STATE_DOWN, "100", __func__, "100",
       "100", "default", NULL, NULL, 0, "TEST/test_res");
    ast_test_validate(test, NULL != chan);
    ast_endpoint_add_channel(uut, chan);
    actual_count = stasis_message_sink_wait_for_count(sink, 1,
       STASIS_SINK_DEFAULT_WAIT);
    ast_test_validate(test, 1 == actual_count);
    msg = sink->messages[0];
    type = stasis_message_type(msg);
    ast_test_validate(test, ast_endpoint_snapshot_type() == type);
    actual_snapshot = stasis_message_data(msg);
    ast_test_validate(test, 1 == actual_snapshot->num_channels);
    ast_hangup(chan);
    chan = NULL;
    actual_count = stasis_message_sink_wait_for_count(sink, 3,
       STASIS_SINK_DEFAULT_WAIT);
    ast_test_validate(test, 3 == actual_count);
    msg = sink->messages[1];
    type = stasis_message_type(msg);
    ast_test_validate(test, ast_channel_snapshot_type() == type);
    msg = sink->messages[2];
    type = stasis_message_type(msg);
    ast_test_validate(test, ast_endpoint_snapshot_type() == type);
    actual_snapshot = stasis_message_data(msg);
    ast_test_validate(test, 0 == actual_snapshot->num_channels);
    return AST_TEST_PASS;
 }
cache_update()
static int cache_update (struct stasis_message * msg, const void * data) static
Message matcher looking for cache update messages.
Definition at line 48 of file test_stasis_endpoints.c.
References ast_endpoint_snapshot_type(), name, stasis_cache_update::new_snapshot, stasis_cache_update::old_snapshot, ast_endpoint_snapshot::resource, stasis_cache_update_type(), stasis_message_data(), stasis_message_type(), stasis_cache_update::type, and update().
Referenced by AST_TEST_DEFINE(), and consumer_exec().
{
    struct stasis_cache_update *update;
    struct ast_endpoint_snapshot *snapshot;
    const char *name = data;
    if (stasis_cache_update_type() != stasis_message_type(msg)) {
       return 0;
    }
    update = stasis_message_data(msg);
    if (ast_endpoint_snapshot_type() != update->type) {
       return 0;
    }
    snapshot = stasis_message_data(update->old_snapshot);
    if (!snapshot) {
       snapshot = stasis_message_data(update->new_snapshot);
    }
    return 0 == strcmp(name, snapshot->resource);
 }
load_module()
static int load_module (void) static
Definition at line 284 of file test_stasis_endpoints.c.
References AST_MODFLAG_DEFAULT, AST_MODULE_INFO(), AST_MODULE_LOAD_SUCCESS, AST_MODULE_SUPPORT_CORE, AST_TEST_REGISTER, ASTERISK_GPL_KEY, and unload_module().
 {
    AST_TEST_REGISTER(state_changes);
    AST_TEST_REGISTER(cache_clear);
    AST_TEST_REGISTER(channel_messages);
    return AST_MODULE_LOAD_SUCCESS;
 }
unload_module()
static int unload_module (void) static
Definition at line 276 of file test_stasis_endpoints.c.
References AST_TEST_UNREGISTER.
Referenced by load_module().
 {
    AST_TEST_UNREGISTER(state_changes);
    AST_TEST_UNREGISTER(cache_clear);
    AST_TEST_UNREGISTER(channel_messages);
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_DEFAULT , .description = "Endpoint stasis-related testing" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .requires = "res_stasis_test", } static
Definition at line 297 of file test_stasis_endpoints.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 297 of file test_stasis_endpoints.c.
test_category
const char* test_category = "/stasis/endpoints/" static
Definition at line 45 of file test_stasis_endpoints.c.
Referenced by AST_TEST_DEFINE().