Asterisk - The Open Source Telephony Project: endpoints.c File Reference
res/prometheus/endpoints.c File Reference
Prometheus Endpoint Metrics.
#include "asterisk.h"
#include "asterisk/stasis_endpoints.h"
#include "asterisk/res_prometheus.h"
#include "prometheus_internal.h"
Data Structures
struct endpoint_metric_defs
Macros
#define ENDPOINTS_CHANNELS_COUNT_HELP "Count of the number of channels currently existing that are associated with the endpoint."
#define ENDPOINTS_STATE_HELP "Individual endpoint states. 0=unknown; 1=offline; 2=online."
Functions
int endpoint_metrics_init (void)
Initialize endpoint metrics.
static void endpoint_metrics_unload_cb (void)
static void endpoints_scrape_cb (struct ast_str **response)
static void get_endpoint_channel_count (struct prometheus_metric *metric, struct ast_endpoint_snapshot *snapshot)
static void get_endpoint_state (struct prometheus_metric *metric, struct ast_endpoint_snapshot *snapshot)
Variables
struct endpoint_metric_defs endpoint_metric_defs []
struct prometheus_callback endpoints_callback
static struct prometheus_metrics_provider provider
Detailed Description
Prometheus Endpoint Metrics.
Author
Matt Jordan mjord.nosp@m.an@d.nosp@m.igium.nosp@m..com
Definition in file res/prometheus/endpoints.c.
Macro Definition Documentation
ENDPOINTS_CHANNELS_COUNT_HELP
#define ENDPOINTS_CHANNELS_COUNT_HELP "Count of the number of channels currently existing that are associated with the endpoint."
Definition at line 35 of file res/prometheus/endpoints.c.
ENDPOINTS_STATE_HELP
#define ENDPOINTS_STATE_HELP "Individual endpoint states. 0=unknown; 1=offline; 2=online."
Definition at line 33 of file res/prometheus/endpoints.c.
Function Documentation
endpoint_metrics_init()
int endpoint_metrics_init (void)
Initialize endpoint metrics.
Return values
0 success
-1 error
Definition at line 198 of file res/prometheus/endpoints.c.
References prometheus_callback_register(), and prometheus_metrics_provider_register().
Referenced by load_module().
 {
    prometheus_metrics_provider_register(&provider);
    prometheus_callback_register(&endpoints_callback);
    return 0;
 }
endpoint_metrics_unload_cb()
static void endpoint_metrics_unload_cb (void) static
Definition at line 184 of file res/prometheus/endpoints.c.
References prometheus_callback_unregister().
 {
    prometheus_callback_unregister(&endpoints_callback);
 }
endpoints_scrape_cb()
static void endpoints_scrape_cb (struct ast_str ** response) static
Definition at line 97 of file res/prometheus/endpoints.c.
References ao2_container_clone, ao2_container_count(), ao2_iterator_destroy(), ao2_iterator_init(), ao2_iterator_next, ao2_ref, ARRAY_LEN, ast_calloc, ast_copy_string(), ast_eid_default, ast_eid_to_str(), ast_endpoint_cache(), ast_endpoint_snapshot_type(), ast_free, AST_LIST_INSERT_TAIL, endpoints, endpoint_metric_defs::get_value, endpoint_metric_defs::help, prometheus_metric::help, ast_endpoint_snapshot::id, endpoint_metric_defs::name, NULL, PROMETHEUS_METRIC_GAUGE, PROMETHEUS_METRIC_SET_LABEL, PROMETHEUS_METRIC_STATIC_INITIALIZATION, prometheus_metric_to_string(), ast_endpoint_snapshot::resource, stasis_cache_dump(), stasis_message_data(), ast_endpoint_snapshot::tech, prometheus_metric::type, and prometheus_metric::value.
 {
    struct ao2_container *endpoint_cache;
    struct ao2_container *endpoints;
    struct ao2_iterator it_endpoints;
    struct stasis_message *message;
    struct prometheus_metric *endpoint_metrics;
    char eid_str[32];
    int i, j, num_endpoints;
    struct prometheus_metric endpoint_count = PROMETHEUS_METRIC_STATIC_INITIALIZATION(
       PROMETHEUS_METRIC_GAUGE,
       "asterisk_endpoints_count",
       "Current endpoint count.",
       NULL
    );
    ast_eid_to_str(eid_str, sizeof(eid_str), &ast_eid_default);
    endpoint_cache = stasis_cache_dump(ast_endpoint_cache(), ast_endpoint_snapshot_type());
    if (!endpoint_cache) {
       return;
    }
    endpoints = ao2_container_clone(endpoint_cache, 0);
    ao2_ref(endpoint_cache, -1);
    if (!endpoints) {
       return;
    }
    num_endpoints = ao2_container_count(endpoints);
    /* Current endpoint count */
    PROMETHEUS_METRIC_SET_LABEL(&endpoint_count, 0, "eid", eid_str);
    snprintf(endpoint_count.value, sizeof(endpoint_count.value), "%d", num_endpoints);
    prometheus_metric_to_string(&endpoint_count, response);
    if (num_endpoints == 0) {
       ao2_ref(endpoints, -1);
       return;
    }
    endpoint_metrics = ast_calloc(ARRAY_LEN(endpoint_metric_defs) * num_endpoints, sizeof(*endpoint_metrics));
    if (!endpoint_metrics) {
       ao2_ref(endpoints, -1);
       return;
    }
    /* Endpoint dependent values */
    it_endpoints = ao2_iterator_init(endpoints, 0);
    for (i = 0; (message = ao2_iterator_next(&it_endpoints)); ao2_ref(message, -1), i++) {
       struct ast_endpoint_snapshot *snapshot = stasis_message_data(message);
       for (j = 0; j < ARRAY_LEN(endpoint_metric_defs); j++) {
          int index = i * ARRAY_LEN(endpoint_metric_defs) + j;
          endpoint_metrics[index].type = PROMETHEUS_METRIC_GAUGE;
          ast_copy_string(endpoint_metrics[index].name, endpoint_metric_defs[j].name, sizeof(endpoint_metrics[index].name));
          endpoint_metrics[index].help = endpoint_metric_defs[j].help;
          PROMETHEUS_METRIC_SET_LABEL(&endpoint_metrics[index], 0, "eid", eid_str);
          PROMETHEUS_METRIC_SET_LABEL(&endpoint_metrics[index], 1, "id", (snapshot->id));
          PROMETHEUS_METRIC_SET_LABEL(&endpoint_metrics[index], 2, "tech", (snapshot->tech));
          PROMETHEUS_METRIC_SET_LABEL(&endpoint_metrics[index], 3, "resource", (snapshot->resource));
          endpoint_metric_defs[j].get_value(&endpoint_metrics[index], snapshot);
          if (i != 0) {
             AST_LIST_INSERT_TAIL(&endpoint_metrics[j].children, &endpoint_metrics[index], entry);
          }
       }
    }
    ao2_iterator_destroy(&it_endpoints);
    for (j = 0; j < ARRAY_LEN(endpoint_metric_defs); j++) {
       prometheus_metric_to_string(&endpoint_metrics[j], response);
    }
    ast_free(endpoint_metrics);
    ao2_ref(endpoints, -1);
 }
get_endpoint_channel_count()
static void get_endpoint_channel_count (struct prometheus_metric * metric, struct ast_endpoint_snapshot * snapshot) static
Definition at line 56 of file res/prometheus/endpoints.c.
References ast_endpoint_snapshot::num_channels, and prometheus_metric::value.
 {
    snprintf(metric->value, sizeof(metric->value), "%d", snapshot->num_channels);
 }
get_endpoint_state()
static void get_endpoint_state (struct prometheus_metric * metric, struct ast_endpoint_snapshot * snapshot) static
Definition at line 44 of file res/prometheus/endpoints.c.
References ast_endpoint_snapshot::state, and prometheus_metric::value.
 {
    snprintf(metric->value, sizeof(metric->value), "%d", snapshot->state);
 }
Variable Documentation
endpoint_metric_defs
struct endpoint_metric_defs endpoint_metric_defs[]
endpoints_callback
struct prometheus_callback endpoints_callback
Initial value:
= {
   .name = "Endpoints callback",
   .callback_fn = endpoints_scrape_cb,
}
Definition at line 175 of file res/prometheus/endpoints.c.
provider
struct prometheus_metrics_provider provider static
Initial value:
= {
   .name = "endpoints",
   .unload_cb = endpoint_metrics_unload_cb,
}
Definition at line 193 of file res/prometheus/endpoints.c.