Asterisk - The Open Source Telephony Project: chanvars.h File Reference
chanvars.h File Reference
Channel Variables.
#include "asterisk/linkedlists.h"
Data Structures
struct ast_var_t
struct varshead
Macros
#define ast_var_assign(name, value) _ast_var_assign(name, value, __FILE__, __LINE__, __PRETTY_FUNCTION__)
#define AST_VAR_LIST_TRAVERSE(head, var) AST_LIST_TRAVERSE(head, var, entries)
Functions
struct ast_var_t * _ast_var_assign (const char *name, const char *value, const char *file, int lineno, const char *function)
void ast_var_delete (struct ast_var_t *var)
char * ast_var_find (const struct varshead *head, const char *name)
const char * ast_var_full_name (const struct ast_var_t *var)
struct varshead * ast_var_list_clone (struct varshead *head)
struct varshead * ast_var_list_create (void)
void ast_var_list_destroy (struct varshead *head)
static void AST_VAR_LIST_INSERT_HEAD (struct varshead *head, struct ast_var_t *var)
static void AST_VAR_LIST_INSERT_TAIL (struct varshead *head, struct ast_var_t *var)
const char * ast_var_name (const struct ast_var_t *var)
const char * ast_var_value (const struct ast_var_t *var)
Detailed Description
Channel Variables.
Definition in file chanvars.h.
Macro Definition Documentation
ast_var_assign
#define ast_var_assign (name, value) _ast_var_assign(name, value, __FILE__, __LINE__, __PRETTY_FUNCTION__)
Definition at line 40 of file chanvars.h.
Referenced by acf_iaxvar_write(), assign_and_insert(), ast_cel_fabricate_channel_from_event(), ast_channel_get_vars(), ast_channel_inherit_variables(), ast_iax2_new(), AST_TEST_DEFINE(), ast_unreal_call_setup(), ast_var_list_clone(), authenticate_reply(), build_profile(), cdr_object_create_public_records(), channel_get_external_vars(), clone_variables(), copy_variables(), do_say(), dundi_lookup_local(), frame_set_var(), get_defaults(), handle_aor(), handle_registrations(), iax2_dup_variable_datastore(), loopback_subst(), mock_cdr_backend_cb(), pbx_builtin_pushvar_helper(), pbx_builtin_setvar_helper(), set_timezone_variables(), set_variable(), shared_write(), and socket_process_helper().
AST_VAR_LIST_TRAVERSE
#define AST_VAR_LIST_TRAVERSE (head, var) AST_LIST_TRAVERSE(head, var, entries)
Definition at line 49 of file chanvars.h.
Referenced by ast_var_list_clone(), and fields_handler().
Function Documentation
_ast_var_assign()
struct ast_var_t* _ast_var_assign (const char * name, const char * value, const char * file, int lineno, const char * function)
Definition at line 36 of file chanvars.c.
References __ast_calloc(), ast_copy_string(), ast_var_t::name, NULL, ast_var_t::value, and var.
 {
    struct ast_var_t *var;
    int name_len = strlen(name) + 1;
    int value_len = strlen(value) + 1;
    var = __ast_calloc(sizeof(*var) + name_len + value_len, sizeof(char),
       file, lineno, function);
    if (!var) {
       return NULL;
    }
    ast_copy_string(var->name, name, name_len);
    var->value = var->name + name_len;
    ast_copy_string(var->value, value, value_len);
    return var;
 }
ast_var_delete()
static void ast_var_delete (struct ast_var_t * var)
Definition at line 2473 of file extconf.c.
References ast_free.
Referenced by acf_iaxvar_write(), ast_cdr_reset(), ast_channel_destructor(), ast_dummy_channel_destructor(), AST_TEST_DEFINE(), ast_var_list_destroy(), cdr_object_dtor(), chan_cleanup(), do_say(), dundi_lookup_local(), free_variables(), gosub_release_frame(), loopback_subst(), pbx_builtin_clear_globals(), pbx_builtin_setvar_helper(), profile_destructor(), set_variable(), shared_variable_free(), shared_write(), sip_removeheader(), and varshead_dtor().
 {
    free(var);
 }
ast_var_find()
char* ast_var_find (const struct varshead * head, const char * name)
Definition at line 85 of file chanvars.c.
References AST_LIST_TRAVERSE, ast_var_t::entries, ast_var_t::name, NULL, ast_var_t::value, and var.
Referenced by phoneprov_destroy(), and users_apply_handler().
 {
    struct ast_var_t *var;
    AST_LIST_TRAVERSE(head, var, entries) {
       if (!strcmp(name, var->name)) {
          return var->value;
       }
    }
    return NULL;
 }
ast_var_full_name()
const char* ast_var_full_name (const struct ast_var_t * var)
Definition at line 75 of file chanvars.c.
References ast_var_t::name, and NULL.
Referenced by ast_channel_inherit_variables(), ast_unreal_call_setup(), and inherit_channel_vars_from_id().
 {
    return (var ? var->name : NULL);
 }
ast_var_list_clone()
struct varshead* ast_var_list_clone (struct varshead * head)
Definition at line 124 of file chanvars.c.
References ast_var_assign, ast_var_list_create(), ast_var_list_destroy(), AST_VAR_LIST_INSERT_TAIL(), AST_VAR_LIST_TRAVERSE, ast_var_t::name, NULL, ast_var_t::value, and var.
 {
    struct varshead *clone;
    struct ast_var_t *var, *newvar;
    if (!head) {
       return NULL;
    }
    clone = ast_var_list_create();
    if (!clone) {
       return NULL;
    }
    AST_VAR_LIST_TRAVERSE(head, var) {
       newvar = ast_var_assign(var->name, var->value);
       if (!newvar) {
          ast_var_list_destroy(clone);
          return NULL;
       }
       AST_VAR_LIST_INSERT_TAIL(clone, newvar);
    }
    return clone;
 }
ast_var_list_create()
struct varshead* ast_var_list_create (void)
Definition at line 97 of file chanvars.c.
References ast_calloc, AST_LIST_HEAD_INIT_NOLOCK, and NULL.
Referenced by ast_var_list_clone(), build_profile(), get_defaults(), handle_aor(), handle_registrations(), and phoneprov_alloc().
 {
    struct varshead *head;
    head = ast_calloc(1, sizeof(*head));
    if (!head) {
       return NULL;
    }
    AST_LIST_HEAD_INIT_NOLOCK(head);
    return head;
 }
ast_var_list_destroy()
void ast_var_list_destroy (struct varshead * head)
Definition at line 109 of file chanvars.c.
References ast_free, AST_LIST_REMOVE_HEAD, ast_var_delete(), ast_var_t::entries, and var.
Referenced by ast_var_list_clone(), get_defaults(), handle_aor(), handle_registrations(), and phoneprov_destroy().
 {
    struct ast_var_t *var;
    if (!head) {
       return;
    }
    while ((var = AST_LIST_REMOVE_HEAD(head, entries))) {
       ast_var_delete(var);
    }
    ast_free(head);
 }
AST_VAR_LIST_INSERT_HEAD()
static void AST_VAR_LIST_INSERT_HEAD (struct varshead * head, struct ast_var_t * var) inline static
Definition at line 57 of file chanvars.h.
References AST_LIST_INSERT_HEAD, and ast_var_t::entries.
{
    if (var) {
       AST_LIST_INSERT_HEAD(head, var, entries);
    }
 }
AST_VAR_LIST_INSERT_TAIL()
static void AST_VAR_LIST_INSERT_TAIL (struct varshead * head, struct ast_var_t * var) inline static
Definition at line 51 of file chanvars.h.
References AST_LIST_INSERT_TAIL, and ast_var_t::entries.
Referenced by assign_and_insert(), ast_var_list_clone(), build_profile(), get_defaults(), handle_aor(), handle_registrations(), and set_timezone_variables().
{
    if (var) {
       AST_LIST_INSERT_TAIL(head, var, entries);
    }
 }
ast_var_name()
const char* ast_var_name (const struct ast_var_t * var)
Definition at line 60 of file chanvars.c.
References ast_var_t::name, name, and NULL.
Referenced by ast_cdr_serialize_variables(), ast_channel_get_vars(), ast_str_retrieve_variable(), cdr_format_var_internal(), cdr_object_create_public_records(), cdr_object_format_var_internal(), clearvar_prefix(), copy_variables(), frame_set_var(), generate_status(), get_key(), gosub_release_frame(), handle_show_chanvar(), handle_show_globals(), handle_showchan(), iax2_call(), iax2_dup_variable_datastore(), local_read(), ospauth_exec(), ospfinished_exec(), osplookup_exec(), ospnext_exec(), pbx_builtin_getvar_helper(), pbx_builtin_serialize_variables(), pbx_builtin_setvar_helper(), peek_read(), set_variable(), shared_read(), shared_write(), sip_call(), sip_removeheader(), skinny_call(), and transmit_invite().
 {
    const char *name;
    if (var == NULL || (name = var->name) == NULL)
       return NULL;
    /* Return the name without the initial underscores */
    if (name[0] == '_') {
       name++;
       if (name[0] == '_')
          name++;
    }
    return name;
 }
ast_var_value()
const char* ast_var_value (const struct ast_var_t * var)
Definition at line 80 of file chanvars.c.
References NULL, and ast_var_t::value.
Referenced by ast_cdr_serialize_variables(), ast_channel_get_vars(), ast_channel_inherit_variables(), ast_str_retrieve_variable(), ast_unreal_call_setup(), cdr_format_var_internal(), cdr_object_create_public_records(), cdr_object_format_var_internal(), copy_variables(), generate_status(), handle_show_chanvar(), handle_show_globals(), handle_showchan(), iax2_call(), iax2_dup_variable_datastore(), inherit_channel_vars_from_id(), ospauth_exec(), ospfinished_exec(), osplookup_exec(), ospnext_exec(), pbx_builtin_getvar_helper(), pbx_builtin_serialize_variables(), pbx_builtin_setvar_helper(), peek_read(), shared_read(), sip_call(), sip_removeheader(), skinny_call(), and transmit_invite().
 {
    return (var ? var->value : NULL);
 }