Asterisk - The Open Source Telephony Project: pbx_variables.c File Reference
pbx_variables.c File Reference
PBX variables routines.
#include "asterisk.h"
#include "asterisk/_private.h"
#include "asterisk/app.h"
#include "asterisk/ast_expr.h"
#include "asterisk/chanvars.h"
#include "asterisk/cli.h"
#include "asterisk/linkedlists.h"
#include "asterisk/lock.h"
#include "asterisk/module.h"
#include "asterisk/paths.h"
#include "asterisk/pbx.h"
#include "asterisk/stasis_channels.h"
#include "pbx_private.h"
Functions
const char * ast_str_retrieve_variable (struct ast_str **str, ssize_t maxlen, struct ast_channel *c, struct varshead *headp, const char *var)
void ast_str_substitute_variables (struct ast_str **buf, ssize_t maxlen, struct ast_channel *chan, const char *templ)
void ast_str_substitute_variables_full (struct ast_str **buf, ssize_t maxlen, struct ast_channel *c, struct varshead *headp, const char *templ, size_t *used)
void ast_str_substitute_variables_varshead (struct ast_str **buf, ssize_t maxlen, struct varshead *headp, const char *templ)
static const char * ast_str_substring (struct ast_str *value, int offset, int length)
static char * handle_set_chanvar (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static char * handle_set_global (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static char * handle_show_chanvar (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
CLI support for listing chanvar's variables in a parseable way.
static char * handle_show_globals (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
CLI support for listing global variables in a parseable way.
int load_pbx_variables (void)
static int parse_variable_name (char *var, int *offset, int *length, int *isfunc)
extract offset:length from variable name.
void pbx_builtin_clear_globals (void)
const char * pbx_builtin_getvar_helper (struct ast_channel *chan, const char *name)
Return a pointer to the value of the corresponding channel variable.
void pbx_builtin_pushvar_helper (struct ast_channel *chan, const char *name, const char *value)
Add a variable to the channel variable stack, without removing any previously set value.
int pbx_builtin_serialize_variables (struct ast_channel *chan, struct ast_str **buf)
Create a human-readable string, specifying all variables and their corresponding values.
int pbx_builtin_setvar (struct ast_channel *chan, const char *data)
Parse and set a single channel variable, where the name and value are separated with an '=' character.
int pbx_builtin_setvar_helper (struct ast_channel *chan, const char *name, const char *value)
Add a variable to the channel variable stack, removing the most recently set value for the same name.
int pbx_builtin_setvar_multiple (struct ast_channel *chan, const char *vdata)
Parse and set multiple channel variables, where the pairs are separated by the ',' character, and name and value are separated with an '=' character.
void pbx_retrieve_variable (struct ast_channel *c, const char *var, char **ret, char *workspace, int workspacelen, struct varshead *headp)
Support for Asterisk built-in variables in the dialplan.
void pbx_substitute_variables_helper (struct ast_channel *c, const char *cp1, char *cp2, int count)
void pbx_substitute_variables_helper_full (struct ast_channel *c, struct varshead *headp, const char *cp1, char *cp2, int count, size_t *used)
void pbx_substitute_variables_varshead (struct varshead *headp, const char *cp1, char *cp2, int count)
static char * substring (const char *value, int offset, int length, char *workspace, size_t workspace_len)
takes a substring. It is ok to call with value == workspace.
static void unload_pbx_variables (void)
Variables
static struct varshead globals = AST_LIST_HEAD_NOLOCK_INIT_VALUE
static ast_rwlock_t globalslock = { PTHREAD_RWLOCK_INITIALIZER , NULL, {1, 0} }
static struct ast_cli_entry vars_cli []
Detailed Description
PBX variables routines.
Author
Corey Farrell git@c.nosp@m.fwar.nosp@m.e.com
Definition in file pbx_variables.c.
Function Documentation
ast_str_retrieve_variable()
const char* ast_str_retrieve_variable (struct ast_str ** buf, ssize_t maxlen, struct ast_channel * chan, struct varshead * headp, const char * var)
Parameters
buf Result will be placed in this buffer.
maxlen -1 if the buffer should not grow, 0 if the buffer may grow to any size, and >0 if the buffer should grow only to that number of bytes.
chan Channel variables from which to extract values, and channel to pass to any dialplan functions.
headp If no channel is specified, a channel list from which to extract variable values
var Variable name to retrieve.
Definition at line 246 of file pbx_variables.c.
References ARRAY_LEN, ast_channel_caller(), ast_channel_context(), ast_channel_dialed(), ast_channel_exten(), ast_channel_hangupcause(), ast_channel_lock, ast_channel_name(), ast_channel_priority(), ast_channel_uniqueid(), ast_channel_unlock, ast_channel_varshead(), ast_config_AST_AGI_DIR, ast_config_AST_CACHE_DIR, ast_config_AST_CONFIG_DIR, ast_config_AST_DATA_DIR, ast_config_AST_DB, ast_config_AST_KEY_DIR, ast_config_AST_LOG_DIR, ast_config_AST_MODULE_DIR, ast_config_AST_RUN_DIR, ast_config_AST_SPOOL_DIR, ast_config_AST_SYSTEM_NAME, ast_config_AST_VAR_DIR, ast_debug, ast_eid_default, ast_eid_to_str(), AST_LIST_TRAVERSE, ast_party_id_presentation(), ast_rwlock_rdlock, ast_rwlock_unlock, ast_str_buffer(), ast_str_get_hint(), ast_str_set(), ast_str_substring(), ast_strdupa, ast_var_name(), ast_var_value(), ast_var_t::entries, globalslock, NULL, and parse_variable_name().
Referenced by ast_ari_asterisk_get_global_var(), ast_ari_channels_get_channel_var(), ast_str_substitute_variables_full(), and pbx_retrieve_variable().
 {
    const char not_found = '\0';
    char *tmpvar;
    const char *ret;
    const char *s; /* the result */
    int offset, length;
    int i, need_substring;
    struct varshead *places[2] = { headp, &globals };  /* list of places where we may look */
    char workspace[20];
    if (c) {
       ast_channel_lock(c);
       places[0] = ast_channel_varshead(c);
    }
    /*
     * Make a copy of var because parse_variable_name() modifies the string.
     * Then if called directly, we might need to run substring() on the result;
     * remember this for later in 'need_substring', 'offset' and 'length'
     */
    tmpvar = ast_strdupa(var); /* parse_variable_name modifies the string */
    need_substring = parse_variable_name(tmpvar, &offset, &length, &i /* ignored */);
    /*
     * Look first into predefined variables, then into variable lists.
     * Variable 's' points to the result, according to the following rules:
     * s == &not_found (set at the beginning) means that we did not find a
     * matching variable and need to look into more places.
     * If s != &not_found, s is a valid result string as follows:
     * s = NULL if the variable does not have a value;
     * you typically do this when looking for an unset predefined variable.
     * s = workspace if the result has been assembled there;
     * typically done when the result is built e.g. with an snprintf(),
     * so we don't need to do an additional copy.
     * s != workspace in case we have a string, that needs to be copied
     * (the ast_copy_string is done once for all at the end).
     * Typically done when the result is already available in some string.
     */
    s = &not_found;   /* default value */
    if (c) { /* This group requires a valid channel */
       /* Names with common parts are looked up a piece at a time using strncmp. */
       if (!strncmp(var, "CALL", 4)) {
          if (!strncmp(var + 4, "ING", 3)) {
             if (!strcmp(var + 7, "PRES")) {        /* CALLINGPRES */
                ast_str_set(str, maxlen, "%d",
                   ast_party_id_presentation(&ast_channel_caller(c)->id));
                s = ast_str_buffer(*str);
             } else if (!strcmp(var + 7, "ANI2")) {    /* CALLINGANI2 */
                ast_str_set(str, maxlen, "%d", ast_channel_caller(c)->ani2);
                s = ast_str_buffer(*str);
             } else if (!strcmp(var + 7, "TON")) {     /* CALLINGTON */
                ast_str_set(str, maxlen, "%d", ast_channel_caller(c)->id.number.plan);
                s = ast_str_buffer(*str);
             } else if (!strcmp(var + 7, "TNS")) {     /* CALLINGTNS */
                ast_str_set(str, maxlen, "%d", ast_channel_dialed(c)->transit_network_select);
                s = ast_str_buffer(*str);
             }
          }
       } else if (!strcmp(var, "HINT")) {
          s = ast_str_get_hint(str, maxlen, NULL, 0, c, ast_channel_context(c), ast_channel_exten(c)) ? ast_str_buffer(*str) : NULL;
       } else if (!strcmp(var, "HINTNAME")) {
          s = ast_str_get_hint(NULL, 0, str, maxlen, c, ast_channel_context(c), ast_channel_exten(c)) ? ast_str_buffer(*str) : NULL;
       } else if (!strcmp(var, "EXTEN")) {
          s = ast_channel_exten(c);
       } else if (!strcmp(var, "CONTEXT")) {
          s = ast_channel_context(c);
       } else if (!strcmp(var, "PRIORITY")) {
          ast_str_set(str, maxlen, "%d", ast_channel_priority(c));
          s = ast_str_buffer(*str);
       } else if (!strcmp(var, "CHANNEL")) {
          s = ast_channel_name(c);
       } else if (!strcmp(var, "UNIQUEID")) {
          s = ast_channel_uniqueid(c);
       } else if (!strcmp(var, "HANGUPCAUSE")) {
          ast_str_set(str, maxlen, "%d", ast_channel_hangupcause(c));
          s = ast_str_buffer(*str);
       }
    }
    if (s == &not_found) { /* look for more */
       if (!strcmp(var, "EPOCH")) {
          ast_str_set(str, maxlen, "%d", (int) time(NULL));
          s = ast_str_buffer(*str);
       } else if (!strcmp(var, "SYSTEMNAME")) {
          s = ast_config_AST_SYSTEM_NAME;
       } else if (!strcmp(var, "ASTCACHEDIR")) {
          s = ast_config_AST_CACHE_DIR;
       } else if (!strcmp(var, "ASTETCDIR")) {
          s = ast_config_AST_CONFIG_DIR;
       } else if (!strcmp(var, "ASTMODDIR")) {
          s = ast_config_AST_MODULE_DIR;
       } else if (!strcmp(var, "ASTVARLIBDIR")) {
          s = ast_config_AST_VAR_DIR;
       } else if (!strcmp(var, "ASTDBDIR")) {
          s = ast_config_AST_DB;
       } else if (!strcmp(var, "ASTKEYDIR")) {
          s = ast_config_AST_KEY_DIR;
       } else if (!strcmp(var, "ASTDATADIR")) {
          s = ast_config_AST_DATA_DIR;
       } else if (!strcmp(var, "ASTAGIDIR")) {
          s = ast_config_AST_AGI_DIR;
       } else if (!strcmp(var, "ASTSPOOLDIR")) {
          s = ast_config_AST_SPOOL_DIR;
       } else if (!strcmp(var, "ASTRUNDIR")) {
          s = ast_config_AST_RUN_DIR;
       } else if (!strcmp(var, "ASTLOGDIR")) {
          s = ast_config_AST_LOG_DIR;
       } else if (!strcmp(var, "ENTITYID")) {
          ast_eid_to_str(workspace, sizeof(workspace), &ast_eid_default);
          s = workspace;
       }
    }
    /* if not found, look into chanvars or global vars */
    for (i = 0; s == &not_found && i < ARRAY_LEN(places); i++) {
       struct ast_var_t *variables;
       if (!places[i])
          continue;
       if (places[i] == &globals)
          ast_rwlock_rdlock(&globalslock);
       AST_LIST_TRAVERSE(places[i], variables, entries) {
          if (!strcmp(ast_var_name(variables), var)) {
             s = ast_var_value(variables);
             break;
          }
       }
       if (places[i] == &globals)
          ast_rwlock_unlock(&globalslock);
    }
    if (s == &not_found || s == NULL) {
       ast_debug(5, "Result of '%s' is NULL\n", var);
       ret = NULL;
    } else {
       ast_debug(5, "Result of '%s' is '%s'\n", var, s);
       if (s != ast_str_buffer(*str)) {
          ast_str_set(str, maxlen, "%s", s);
       }
       ret = ast_str_buffer(*str);
       if (need_substring) {
          ret = ast_str_substring(*str, offset, length);
          ast_debug(2, "Final result of '%s' is '%s'\n", var, ret);
       }
    }
    if (c) {
       ast_channel_unlock(c);
    }
    return ret;
 }
ast_str_substitute_variables()
void ast_str_substitute_variables (struct ast_str ** buf, ssize_t maxlen, struct ast_channel * chan, const char * templ)
Parameters
buf Result will be placed in this buffer.
maxlen -1 if the buffer should not grow, 0 if the buffer may grow to any size, and >0 if the buffer should grow only to that number of bytes.
chan Channel variables from which to extract values, and channel to pass to any dialplan functions.
templ Variable template to expand.
Definition at line 616 of file pbx_variables.c.
References ast_str_substitute_variables_full(), and NULL.
Referenced by _macro_exec(), acf_odbc_read(), acf_odbc_write(), AST_TEST_DEFINE(), cli_odbc_read(), cli_odbc_write(), config_curl(), custom_log(), cut_internal(), destroy_curl(), do_notify(), exec_exec(), func_mchan_read(), function_eval2(), function_fieldnum_helper(), function_fieldqty_helper(), handle_getvariablefull(), import_helper(), listfilter(), make_email_file(), realtime_curl(), realtime_multi_curl(), replace(), require_curl(), run_app_helper(), sendmail(), sendpage(), shift_pop(), store_curl(), strreplace(), syslog_log(), test_2way_function(), test_chan_function(), test_chan_integer(), test_chan_integer_accessor(), test_chan_string(), test_chan_variable(), test_expected_result(), tryexec_exec(), unshift_push(), update2_curl(), and update_curl().
 {
    ast_str_substitute_variables_full(buf, maxlen, chan, NULL, templ, NULL);
 }
ast_str_substitute_variables_full()
void ast_str_substitute_variables_full (struct ast_str ** buf, ssize_t maxlen, struct ast_channel * c, struct varshead * headp, const char * templ, size_t * used)
Parameters
buf Result will be placed in this buffer.
maxlen -1 if the buffer should not grow, 0 if the buffer may grow to any size, and >0 if the buffer should grow only to that number of bytes.
c Channel variables from which to extract values, and channel to pass to any dialplan functions.
headp If no channel is specified, a channel list from which to extract variable values
templ Variable template to expand.
used Number of bytes read from the template. (May be NULL)
Definition at line 394 of file pbx_variables.c.
References ast_channel_unref, ast_channel_varshead(), ast_debug, ast_dummy_channel_alloc, ast_free, ast_func_read2(), ast_log, ast_str_append(), ast_str_append_substr(), ast_str_buffer(), ast_str_create, ast_str_expr(), ast_str_reset(), ast_str_retrieve_variable(), ast_str_set_substr(), ast_str_strlen(), ast_str_substring(), ast_strlen_zero, len(), LOG_ERROR, LOG_WARNING, NULL, and parse_variable_name().
Referenced by ast_str_substitute_variables(), and ast_str_substitute_variables_varshead().
 {
    /* Substitutes variables into buf, based on string templ */
    const char *whereweare;
    struct ast_str *substr1 = ast_str_create(16);
    struct ast_str *substr2 = NULL;
    struct ast_str *substr3 = ast_str_create(16);
    ast_str_reset(*buf);
    if (!substr1 || !substr3) {
       if (used) {
          *used = ast_str_strlen(*buf);
       }
       ast_free(substr1);
       ast_free(substr3);
       return;
    }
    whereweare = templ;
    while (!ast_strlen_zero(whereweare)) {
       const char *nextvar = NULL;
       const char *nextexp = NULL;
       const char *nextthing;
       const char *vars;
       const char *vare;
       char *finalvars;
       int pos;
       int brackets;
       int needsub;
       int len;
       /* reset our buffer */
       ast_str_reset(substr3);
       /* Determine how much simply needs to be copied to the output buf. */
       nextthing = strchr(whereweare, '$');
       if (nextthing) {
          pos = nextthing - whereweare;
          switch (nextthing[1]) {
          case '{':
             /* Variable substitution */
             nextvar = nextthing;
             break;
          case '[':
             /* Expression substitution */
             nextexp = nextthing;
             break;
          default:
             /* '$' is not part of a substitution so include it too. */
             ++pos;
             break;
          }
       } else {
          /* We're copying the whole remaining string */
          pos = strlen(whereweare);
       }
       if (pos) {
          /* Copy that many bytes */
          ast_str_append_substr(buf, maxlen, whereweare, pos);
          whereweare += pos;
       }
       if (nextvar) {
          int offset;
          int offset2;
          int isfunction;
          int res;
          /* We have a variable.  Find the start and end, and determine
             if we are going to have to recursively call ourselves on the
             contents */
          vars = vare = nextvar + 2;
          brackets = 1;
          needsub = 0;
          /* Find the end of it */
          while (brackets && *vare) {
             if ((vare[0] == '$') && (vare[1] == '{')) {
                needsub++;
                brackets++;
                vare++;
             } else if (vare[0] == '{') {
                brackets++;
             } else if (vare[0] == '}') {
                brackets--;
             } else if ((vare[0] == '$') && (vare[1] == '[')) {
                needsub++;
                vare++;
             }
             vare++;
          }
          len = vare - vars;
          if (brackets) {
             ast_log(LOG_WARNING, "Error in extension logic (missing '}')\n");
          } else {
             /* Don't count the closing '}' in the length. */
             --len;
          }
          /* Skip totally over variable string */
          whereweare = vare;
          /* Store variable name expression to lookup. */
          ast_str_set_substr(&substr1, 0, vars, len);
          ast_debug(5, "Evaluating '%s' (from '%s' len %d)\n", ast_str_buffer(substr1), vars, len);
          /* Substitute if necessary */
          if (needsub) {
             if (!substr2) {
                substr2 = ast_str_create(16);
                if (!substr2) {
                   continue;
                }
             }
             ast_str_substitute_variables_full(&substr2, 0, c, headp, ast_str_buffer(substr1), NULL);
             finalvars = ast_str_buffer(substr2);
          } else {
             finalvars = ast_str_buffer(substr1);
          }
          parse_variable_name(finalvars, &offset, &offset2, &isfunction);
          if (isfunction) {
             /* Evaluate function */
             if (c || !headp) {
                res = ast_func_read2(c, finalvars, &substr3, 0);
             } else {
                struct varshead old;
                struct ast_channel *bogus;
                bogus = ast_dummy_channel_alloc();
                if (bogus) {
                   old = *ast_channel_varshead(bogus);
                   *ast_channel_varshead(bogus) = *headp;
                   res = ast_func_read2(bogus, finalvars, &substr3, 0);
                   /* Don't deallocate the varshead that was passed in */
                   *ast_channel_varshead(bogus) = old;
                   ast_channel_unref(bogus);
                } else {
                   ast_log(LOG_ERROR, "Unable to allocate bogus channel for function value substitution.\n");
                   res = -1;
                }
             }
             ast_debug(2, "Function %s result is '%s'\n",
                finalvars, res ? "" : ast_str_buffer(substr3));
          } else {
             /* Retrieve variable value */
             ast_str_retrieve_variable(&substr3, 0, c, headp, finalvars);
             res = 0;
          }
          if (!res) {
             ast_str_substring(substr3, offset, offset2);
             ast_str_append(buf, maxlen, "%s", ast_str_buffer(substr3));
          }
       } else if (nextexp) {
          /* We have an expression.  Find the start and end, and determine
             if we are going to have to recursively call ourselves on the
             contents */
          vars = vare = nextexp + 2;
          brackets = 1;
          needsub = 0;
          /* Find the end of it */
          while (brackets && *vare) {
             if ((vare[0] == '$') && (vare[1] == '[')) {
                needsub++;
                brackets++;
                vare++;
             } else if (vare[0] == '[') {
                brackets++;
             } else if (vare[0] == ']') {
                brackets--;
             } else if ((vare[0] == '$') && (vare[1] == '{')) {
                needsub++;
                vare++;
             }
             vare++;
          }
          len = vare - vars;
          if (brackets) {
             ast_log(LOG_WARNING, "Error in extension logic (missing ']')\n");
          } else {
             /* Don't count the closing ']' in the length. */
             --len;
          }
          /* Skip totally over expression */
          whereweare = vare;
          /* Store expression to evaluate. */
          ast_str_set_substr(&substr1, 0, vars, len);
          /* Substitute if necessary */
          if (needsub) {
             if (!substr2) {
                substr2 = ast_str_create(16);
                if (!substr2) {
                   continue;
                }
             }
             ast_str_substitute_variables_full(&substr2, 0, c, headp, ast_str_buffer(substr1), NULL);
             finalvars = ast_str_buffer(substr2);
          } else {
             finalvars = ast_str_buffer(substr1);
          }
          if (ast_str_expr(&substr3, 0, c, finalvars)) {
             ast_debug(2, "Expression result is '%s'\n", ast_str_buffer(substr3));
          }
          ast_str_append(buf, maxlen, "%s", ast_str_buffer(substr3));
       }
    }
    if (used) {
       *used = ast_str_strlen(*buf);
    }
    ast_free(substr1);
    ast_free(substr2);
    ast_free(substr3);
 }
ast_str_substitute_variables_varshead()
void ast_str_substitute_variables_varshead (struct ast_str ** buf, ssize_t maxlen, struct varshead * headp, const char * templ)
Parameters
buf Result will be placed in this buffer.
maxlen -1 if the buffer should not grow, 0 if the buffer may grow to any size, and >0 if the buffer should grow only to that number of bytes.
headp If no channel is specified, a channel list from which to extract variable values
templ Variable template to expand.
Definition at line 621 of file pbx_variables.c.
References ast_str_substitute_variables_full(), and NULL.
Referenced by build_user_routes(), handle_aor(), handle_registrations(), and pp_each_extension_helper().
 {
    ast_str_substitute_variables_full(buf, maxlen, NULL, headp, templ, NULL);
 }
ast_str_substring()
static const char* ast_str_substring (struct ast_str * value, int offset, int length) static
Definition at line 185 of file pbx_variables.c.
References ast_str_buffer(), ast_str_reset(), ast_str_strlen(), ast_str_truncate(), and ast_str_update().
Referenced by ast_str_retrieve_variable(), and ast_str_substitute_variables_full().
 {
    int lr;  /* length of the input string after the copy */
    lr = ast_str_strlen(value); /* compute length after copy, so we never go out of the workspace */
    /* Quick check if no need to do anything */
    if (offset == 0 && length >= lr) /* take the whole string */
       return ast_str_buffer(value);
    if (offset < 0)   {  /* translate negative offset into positive ones */
       offset = lr + offset;
       if (offset < 0) /* If the negative offset was greater than the length of the string, just start at the beginning */
          offset = 0;
    }
    /* too large offset result in empty string so we know what to return */
    if (offset >= lr) {
       ast_str_reset(value);
       return ast_str_buffer(value);
    }
    if (offset > 0) {
       /* Go ahead and chop off the beginning */
       memmove(ast_str_buffer(value), ast_str_buffer(value) + offset, ast_str_strlen(value) - offset + 1);
       lr -= offset;
    }
    if (length >= 0 && length < lr) {   /* truncate if necessary */
       ast_str_truncate(value, length);
    } else if (length < 0) {
       if (lr > -length) { /* After we remove from the front and from the rear, is there anything left? */
          ast_str_truncate(value, lr + length);
       } else {
          ast_str_reset(value);
       }
    } else {
       /* Nothing to do, but update the buffer length */
       ast_str_update(value);
    }
    return ast_str_buffer(value);
 }
handle_set_chanvar()
static char* handle_set_chanvar (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) static
Definition at line 932 of file pbx_variables.c.
References ast_cli_args::argc, ast_cli_entry::args, ast_cli_args::argv, ast_channel_get_by_name(), ast_channel_unref, ast_cli(), ast_complete_channels(), CLI_FAILURE, CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::command, ast_cli_args::fd, ast_cli_args::line, ast_cli_args::n, NULL, pbx_builtin_setvar_helper(), ast_cli_args::pos, ast_cli_entry::usage, and ast_cli_args::word.
 {
    struct ast_channel *chan;
    const char *chan_name, *var_name, *var_value;
    switch (cmd) {
    case CLI_INIT:
       e->command = "dialplan set chanvar";
       e->usage =
          "Usage: dialplan set chanvar <channel> <varname> <value>\n"
          "       Set channel variable <varname> to <value>\n";
       return NULL;
    case CLI_GENERATE:
       return ast_complete_channels(a->line, a->word, a->pos, a->n, 3);
    }
    if (a->argc != e->args + 3)
       return CLI_SHOWUSAGE;
    chan_name = a->argv[e->args];
    var_name = a->argv[e->args + 1];
    var_value = a->argv[e->args + 2];
    if (!(chan = ast_channel_get_by_name(chan_name))) {
       ast_cli(a->fd, "Channel '%s' not found\n", chan_name);
       return CLI_FAILURE;
    }
    pbx_builtin_setvar_helper(chan, var_name, var_value);
    chan = ast_channel_unref(chan);
    ast_cli(a->fd, "\n    -- Channel variable '%s' set to '%s' for '%s'\n",  var_name, var_value, chan_name);
    return CLI_SUCCESS;
 }
handle_set_global()
static char* handle_set_global (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) static
Definition at line 910 of file pbx_variables.c.
References ast_cli_args::argc, ast_cli_entry::args, ast_cli_args::argv, ast_cli(), CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::command, ast_cli_args::fd, NULL, pbx_builtin_setvar_helper(), and ast_cli_entry::usage.
 {
    switch (cmd) {
    case CLI_INIT:
       e->command = "dialplan set global";
       e->usage =
          "Usage: dialplan set global <name> <value>\n"
          "       Set global dialplan variable <name> to <value>\n";
       return NULL;
    case CLI_GENERATE:
       return NULL;
    }
    if (a->argc != e->args + 2)
       return CLI_SHOWUSAGE;
    pbx_builtin_setvar_helper(NULL, a->argv[3], a->argv[4]);
    ast_cli(a->fd, "\n    -- Global variable '%s' set to '%s'\n", a->argv[3], a->argv[4]);
    return CLI_SUCCESS;
 }
handle_show_chanvar()
static char* handle_show_chanvar (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) static
CLI support for listing chanvar's variables in a parseable way.
Definition at line 874 of file pbx_variables.c.
References ast_cli_args::argc, ast_cli_entry::args, ast_cli_args::argv, ast_channel_get_by_name(), ast_channel_lock, ast_channel_unlock, ast_channel_unref, ast_channel_varshead(), ast_cli(), ast_complete_channels(), AST_LIST_TRAVERSE, ast_var_name(), ast_var_value(), CLI_FAILURE, CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::command, ast_var_t::entries, ast_cli_args::fd, ast_cli_args::line, ast_cli_args::n, NULL, ast_cli_args::pos, ast_cli_entry::usage, var, and ast_cli_args::word.
 {
    struct ast_channel *chan;
    struct ast_var_t *var;
    switch (cmd) {
    case CLI_INIT:
       e->command = "dialplan show chanvar";
       e->usage =
          "Usage: dialplan show chanvar <channel>\n"
          "       List current channel variables and their values\n";
       return NULL;
    case CLI_GENERATE:
       return ast_complete_channels(a->line, a->word, a->pos, a->n, 3);
    }
    if (a->argc != e->args + 1) {
       return CLI_SHOWUSAGE;
    }
    chan = ast_channel_get_by_name(a->argv[e->args]);
    if (!chan) {
       ast_cli(a->fd, "Channel '%s' not found\n", a->argv[e->args]);
       return CLI_FAILURE;
    }
    ast_channel_lock(chan);
    AST_LIST_TRAVERSE(ast_channel_varshead(chan), var, entries) {
       ast_cli(a->fd, "%s=%s\n", ast_var_name(var), ast_var_value(var));
    }
    ast_channel_unlock(chan);
    ast_channel_unref(chan);
    return CLI_SUCCESS;
 }
handle_show_globals()
static char* handle_show_globals (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) static
CLI support for listing global variables in a parseable way.
Definition at line 846 of file pbx_variables.c.
References ast_cli(), AST_LIST_TRAVERSE, ast_rwlock_rdlock, ast_rwlock_unlock, ast_var_name(), ast_var_value(), CLI_GENERATE, CLI_INIT, CLI_SUCCESS, ast_cli_entry::command, ast_var_t::entries, ast_cli_args::fd, globalslock, NULL, and ast_cli_entry::usage.
 {
    int i = 0;
    struct ast_var_t *newvariable;
    switch (cmd) {
    case CLI_INIT:
       e->command = "dialplan show globals";
       e->usage =
          "Usage: dialplan show globals\n"
          "       List current global dialplan variables and their values\n";
       return NULL;
    case CLI_GENERATE:
       return NULL;
    }
    ast_rwlock_rdlock(&globalslock);
    AST_LIST_TRAVERSE (&globals, newvariable, entries) {
       i++;
       ast_cli(a->fd, "   %s=%s\n", ast_var_name(newvariable), ast_var_value(newvariable));
    }
    ast_rwlock_unlock(&globalslock);
    ast_cli(a->fd, "\n    -- %d variable(s)\n", i);
    return CLI_SUCCESS;
 }
load_pbx_variables()
int load_pbx_variables (void)
Provided by pbx_variables.c
Definition at line 1216 of file pbx_variables.c.
References ARRAY_LEN, ast_cli_register_multiple, ast_register_application2(), ast_register_cleanup(), NULL, pbx_builtin_setvar(), pbx_builtin_setvar_multiple(), and unload_pbx_variables().
Referenced by asterisk_daemon().
 {
    int res = 0;
    res |= ast_cli_register_multiple(vars_cli, ARRAY_LEN(vars_cli));
    res |= ast_register_application2("Set", pbx_builtin_setvar, NULL, NULL, NULL);
    res |= ast_register_application2("MSet", pbx_builtin_setvar_multiple, NULL, NULL, NULL);
    ast_register_cleanup(unload_pbx_variables);
    return res;
 }
parse_variable_name()
static int parse_variable_name (char * var, int * offset, int * length, int * isfunc) static
extract offset:length from variable name.
Returns
1 if there is a offset:length part, which is trimmed off (values go into variables)
Definition at line 116 of file pbx_variables.c.
References var.
Referenced by ast_str_retrieve_variable(), ast_str_substitute_variables_full(), and pbx_substitute_variables_helper_full().
 {
    int parens = 0;
    *offset = 0;
    *length = INT_MAX;
    *isfunc = 0;
    for (; *var; var++) {
       if (*var == '(') {
          (*isfunc)++;
          parens++;
       } else if (*var == ')') {
          parens--;
       } else if (*var == ':' && parens == 0) {
          *var++ = '\0';
          sscanf(var, "%30d:%30d", offset, length);
          return 1; /* offset:length valid */
       }
    }
    return 0;
 }
pbx_builtin_clear_globals()
void pbx_builtin_clear_globals (void)
Definition at line 1191 of file pbx_variables.c.
References AST_LIST_REMOVE_HEAD, ast_rwlock_unlock, ast_rwlock_wrlock, ast_var_delete(), ast_var_t::entries, and globalslock.
Referenced by handle_cli_dialplan_reload(), reload(), and unload_pbx_variables().
 {
    struct ast_var_t *vardata;
    ast_rwlock_wrlock(&globalslock);
    while ((vardata = AST_LIST_REMOVE_HEAD(&globals, entries)))
       ast_var_delete(vardata);
    ast_rwlock_unlock(&globalslock);
 }
pbx_builtin_getvar_helper()
const char* pbx_builtin_getvar_helper (struct ast_channel * chan, const char * name)
Return a pointer to the value of the corresponding channel variable.
Note
Will lock the channel.
This function will return a pointer to the buffer inside the channel variable. This value should only be accessed with the channel locked. If the value needs to be kept around, it should be done by using the following thread-safe code:
const char *var;
ast_channel_lock(chan);
if ((var = pbx_builtin_getvar_helper(chan, "MYVAR"))) {
   var = ast_strdupa(var);
}
ast_channel_unlock(chan);
Definition at line 1000 of file pbx_variables.c.
References ast_channel_lock, ast_channel_unlock, ast_channel_varshead(), AST_LIST_TRAVERSE, ast_rwlock_rdlock, ast_rwlock_unlock, ast_var_name(), ast_var_value(), globalslock, and NULL.
Referenced by __ast_pbx_run(), _if_exec(), _macro_exec(), _while_exec(), action_agents(), add_header_from_channel_var(), agent_handle_show_specific(), agent_login_channel_config(), agent_request_exec(), agent_show_requested(), aMYSQL_connect(), analog_call(), array(), ast_bridge_timelimit(), ast_bridge_transfer_attended(), ast_call_forward(), ast_channel_connected_line_macro(), ast_channel_connected_line_sub(), ast_channel_redirecting_macro(), ast_channel_redirecting_sub(), ast_eivr_getvariable(), ast_get_chan_applicationmap(), ast_monitor_stop(), ast_unreal_hangup(), attended_transfer_exec(), bridge_check_monitor(), bridge_parking_push(), channel_get_external_vars(), check_bridge_play_sound(), common_exec(), conf_run(), create_dynamic_lot_full(), crement_function_read(), dahdi_hangup(), dial_exec_full(), do_forward(), dundi_exec(), dundi_helper(), eagi_exec(), feature_automixmonitor(), feature_automonitor(), feature_blind_transfer(), find_by_mark(), find_channel_parking_lot_name(), find_conf_realtime(), func_channel_read(), generate_parked_user(), generic_fax_exec(), get_also_info(), get_index(), get_refer_info(), get_transfer_context(), global_read(), gosub_run(), handle_call_forward(), handle_clear_alarms(), handle_gosub(), handle_hangup(), hash_read(), iax2_call(), iax2_exec(), import_ch(), leave_voicemail(), local_read(), macro_fixup(), manager_mixmonitor(), meetme_menu_admin_extended(), mgcp_call(), minivm_delete_exec(), minivm_notify_exec(), misdn_answer(), misdn_hangup(), morsecode_exec(), notify_new_message(), ooh323_call(), ooh323_hangup(), park_app_exec(), pbx_builtin_background(), pbx_builtin_gotoiftime(), pbx_builtin_saycharacters(), pbx_builtin_saycharacters_case(), pbx_builtin_saydigits(), pbx_builtin_saymoney(), pbx_builtin_saynumber(), pbx_builtin_sayphonetic(), pre_bridge_setup(), queue_exec(), receive_ademco_event(), report_receive_fax_status(), report_send_fax_status(), retrydial_exec(), ring_entry(), run_agi(), sayunixtime_exec(), sendtext_exec(), set_from_header(), set_local_info(), set_touch_variable(), set_transfer_variables_all(), setsubstate(), setup_mixmonitor(), setup_park_common_datastore(), sip_addheader(), sla_trunk_exec(), speech_background(), transfer_refer(), try_calling(), try_suggested_sip_codec(), and wait_for_answer().
 {
    struct ast_var_t *variables;
    const char *ret = NULL;
    int i;
    struct varshead *places[2] = { NULL, &globals };
    if (!name)
       return NULL;
    if (chan) {
       ast_channel_lock(chan);
       places[0] = ast_channel_varshead(chan);
    }
    for (i = 0; i < 2; i++) {
       if (!places[i])
          continue;
       if (places[i] == &globals)
          ast_rwlock_rdlock(&globalslock);
       AST_LIST_TRAVERSE(places[i], variables, entries) {
          if (!strcmp(name, ast_var_name(variables))) {
             ret = ast_var_value(variables);
             break;
          }
       }
       if (places[i] == &globals)
          ast_rwlock_unlock(&globalslock);
       if (ret)
          break;
    }
    if (chan)
       ast_channel_unlock(chan);
    return ret;
 }
pbx_builtin_pushvar_helper()
void pbx_builtin_pushvar_helper (struct ast_channel * chan, const char * name, const char * value)
Add a variable to the channel variable stack, without removing any previously set value.
Note
Will lock the channel.
Definition at line 1038 of file pbx_variables.c.
References ast_channel_lock, ast_channel_unlock, ast_channel_varshead(), ast_func_write(), AST_LIST_INSERT_HEAD, ast_log, ast_rwlock_unlock, ast_rwlock_wrlock, ast_strdupa, ast_var_assign, ast_verb, globals, globalslock, and LOG_WARNING.
Referenced by acf_odbc_read(), acf_odbc_write(), cli_odbc_read(), cli_odbc_write(), and frame_set_var().
 {
    struct ast_var_t *newvariable;
    struct varshead *headp;
    if (name[strlen(name)-1] == ')') {
       char *function = ast_strdupa(name);
       ast_log(LOG_WARNING, "Cannot push a value onto a function\n");
       ast_func_write(chan, function, value);
       return;
    }
    if (chan) {
       ast_channel_lock(chan);
       headp = ast_channel_varshead(chan);
    } else {
       ast_rwlock_wrlock(&globalslock);
       headp = &globals;
    }
    if (value && (newvariable = ast_var_assign(name, value))) {
       if (headp == &globals)
          ast_verb(2, "Setting global variable '%s' to '%s'\n", name, value);
       AST_LIST_INSERT_HEAD(headp, newvariable, entries);
    }
    if (chan)
       ast_channel_unlock(chan);
    else
       ast_rwlock_unlock(&globalslock);
 }
pbx_builtin_serialize_variables()
int pbx_builtin_serialize_variables (struct ast_channel * chan, struct ast_str ** buf)
Create a human-readable string, specifying all variables and their corresponding values.
Parameters
chan Channel from which to read variables
buf Dynamic string in which to place the result (should be allocated with ast_str_create).
See also
ast_str_create
Note
Will lock the channel.
Definition at line 969 of file pbx_variables.c.
References ast_channel_lock, ast_channel_unlock, ast_channel_varshead(), AST_LIST_TRAVERSE, ast_log, ast_str_append(), ast_str_reset(), ast_var_name(), ast_var_value(), ast_var_t::entries, LOG_ERROR, total, and var.
Referenced by ast_var_channels_table(), and dumpchan_exec().
 {
    struct ast_var_t *variables;
    const char *var, *val;
    int total = 0;
    if (!chan)
       return 0;
    ast_str_reset(*buf);
    ast_channel_lock(chan);
    AST_LIST_TRAVERSE(ast_channel_varshead(chan), variables, entries) {
       if ((var = ast_var_name(variables)) && (val = ast_var_value(variables))
          /* && !ast_strlen_zero(var) && !ast_strlen_zero(val) */
          ) {
          if (ast_str_append(buf, 0, "%s=%s\n", var, val) < 0) {
             ast_log(LOG_ERROR, "Data Buffer Size Exceeded!\n");
             break;
          } else
             total++;
       } else
          break;
    }
    ast_channel_unlock(chan);
    return total;
 }
pbx_builtin_setvar()
int pbx_builtin_setvar (struct ast_channel * chan, const char * data)
Parse and set a single channel variable, where the name and value are separated with an '=' character.
Note
Will lock the channel.
Definition at line 1129 of file pbx_variables.c.
References ast_log, ast_strdupa, ast_strlen_zero, LOG_WARNING, name, pbx_builtin_setvar_helper(), strsep(), and value.
Referenced by load_pbx_variables().
 {
    char *name, *value, *mydata;
    if (ast_strlen_zero(data)) {
       ast_log(LOG_WARNING, "Set requires one variable name/value pair.\n");
       return 0;
    }
    mydata = ast_strdupa(data);
    name = strsep(&mydata, "=");
    value = mydata;
    if (!value) {
       ast_log(LOG_WARNING, "Set requires an '=' to be a valid assignment.\n");
       return 0;
    }
    if (strchr(name, ' ')) {
       ast_log(LOG_WARNING, "Please avoid unnecessary spaces on variables as it may lead to unexpected results ('%s' set to '%s').\n", name, mydata);
    }
    pbx_builtin_setvar_helper(chan, name, value);
    return 0;
 }
pbx_builtin_setvar_helper()
int pbx_builtin_setvar_helper (struct ast_channel * chan, const char * name, const char * value)
Add a variable to the channel variable stack, removing the most recently set value for the same name.
Note
Will lock the channel. May also be used to set a channel dialplan function to a particular value.
See also
ast_func_write
Returns
-1 if the dialplan function fails to be set
Version
1.8 changed the function to return an error code
True if the old value was not an empty string.
Definition at line 1071 of file pbx_variables.c.
References ast_channel_lock, ast_channel_publish_varset(), ast_channel_unlock, ast_channel_varshead(), ast_func_write(), AST_LIST_INSERT_HEAD, AST_LIST_REMOVE_CURRENT, AST_LIST_TRAVERSE_SAFE_BEGIN, AST_LIST_TRAVERSE_SAFE_END, ast_rwlock_unlock, ast_rwlock_wrlock, ast_strdupa, ast_strlen_zero, ast_var_assign, ast_var_delete(), ast_var_name(), ast_var_value(), ast_verb, globals, globalslock, and name.
Referenced by __analog_ss_thread(), __ast_pbx_run(), _if_exec(), _macro_exec(), _while_exec(), acf_curl_helper(), acf_fetch(), acf_odbc_read(), acf_odbc_write(), acf_transaction_write(), action_atxfer(), action_kick_last(), action_setvar(), admin_exec(), agent_login_exec(), agent_request_exec(), agi_exec_full(), aMYSQL_fetch(), aMYSQL_set(), analog_ss_thread(), app_control_set_channel_var(), app_exec(), aqm_exec(), array(), ast_ari_asterisk_set_global_var(), ast_bridge_set_transfer_variables(), ast_bridge_vars_set(), ast_call_forward(), ast_cc_agent_set_interfaces_chanvar(), ast_eivr_setvariable(), ast_iax2_new(), ast_monitor_start(), ast_monitor_stop(), ast_pbx_outgoing_exten_predial(), ast_pickup_call(), ast_rtp_instance_set_stats_vars(), ast_set_cc_interfaces_chanvar(), ast_set_variables(), AST_TEST_DEFINE(), ast_unreal_hangup(), asyncgoto_exec(), attended_transfer_bridge(), attended_transfer_exec(), audiosocket_request(), background_detect_exec(), begin_dial_channel(), blind_transfer_bridge(), blind_transfer_cb(), blind_transfer_exec(), bridge_channel_internal_push_full(), bridge_exec(), bridgeadd_exec(), calendar_write_exec(), caller_joined_bridge(), caller_safety_timeout(), cb_events(), cccancel_exec(), ccreq_exec(), chan_pjsip_cng_tone_detected(), chan_pjsip_new(), chanavail_exec(), channel_spy(), check_bridge_play_sound(), clear_agent_status(), commit_exec(), conf_run(), confbridge_exec(), confkick_exec(), controlplayback_exec(), count_exec(), crement_function_read(), dahdi_handle_dtmf(), dahdi_new(), dial_exec_full(), dial_transfer(), directory_exec(), disa_exec(), do_directory(), do_forward(), do_notify(), do_waiting(), dtmf_store_framehook(), dynamic_dtmf_hook_callback(), end_bridge_callback(), execute_menu_entry(), export_aoc_vars(), export_ch(), extract_transferrer_headers(), fax_detect_framehook(), frame_set_var(), func_mchan_write(), function_db_delete(), function_db_exists(), function_db_read(), function_realtime_store(), generic_recall(), get_chan_by_ast_name(), get_rdnis(), get_refer_info(), global_write(), gosub_release_frame(), gosub_run(), handle_controlstreamfile(), handle_gosub(), handle_incoming_request(), handle_outgoing_response(), handle_request_bye(), handle_response_cmgr(), handle_set_chanvar(), handle_set_global(), handle_setvariable(), handle_streamfile(), hash_read(), hash_write(), isAnsweringMachine(), kick_conference_participant(), launch_monitor_thread(), leave_marked(), leave_queue(), leave_voicemail(), lua_set_variable(), lua_set_variable_value(), macro_fixup(), mbl_status_exec(), mgcp_new(), minivm_accmess_exec(), minivm_delete_exec(), minivm_greet_exec(), minivm_notify_exec(), minivm_record_exec(), misdn_call(), mixmonitor_exec(), msg_send_exec(), my_handle_dtmf(), MYSQL_exec(), onModeChanged(), ooh323_new(), ooh323_rtp_read(), originate_exec(), ospauth_exec(), ospfinished_exec(), osplookup_exec(), ospnext_exec(), parking_duration_callback(), parking_timeout_set_caller_features(), parse_moved_contact(), pbx_builtin_background(), pbx_builtin_gotoiftime(), pbx_builtin_importvar(), pbx_builtin_setvar(), pbx_builtin_setvar_multiple(), pbx_builtin_waitdigit(), pbx_load_config(), phase_e_handler(), play_message_datetime(), playback_exec(), pqm_exec(), prep_email_sub_vars(), privacy_exec(), process_ast_dsp(), process_sdp(), queue_exec(), read_exec(), read_mf_digits(), read_mf_exec(), read_sf_digits(), read_sf_exec(), readexten_exec(), realtimefield_read(), receivefax_exec(), record_abandoned(), record_exec(), refer_blind_callback(), reload(), reload_module(), return_exec(), rollback_exec(), rotate_file(), rqm_exec(), select_entry(), select_item_menu(), select_item_seq(), sendfax_exec(), sendimage_exec(), sendtext_exec(), sendurl_exec(), set(), set_asterisk_int(), set_channel_variables(), set_duration_var(), set_queue_result(), set_sipdomain_variable(), setsubstate(), shift_pop(), sip_addheader(), sip_hangup(), sip_new(), sip_read(), skinny_new(), sla_calc_trunk_timeouts(), sla_station_exec(), sla_trunk_exec(), speech_create(), start_automixmonitor(), start_automonitor(), start_monitor_exec(), system_exec_helper(), test_chan_variable(), testtime_write(), transfer_exec(), transmit(), tryexec_exec(), unicast_rtp_request(), unshift_push(), update_qe_rule(), upqm_exec(), user_timeout(), vm_allocate_dh(), vm_exec(), vm_playmsgexec(), vmauthenticate(), wait_exec(), wait_for_answer(), waituntil_exec(), and zapateller_exec().
 {
    struct ast_var_t *newvariable;
    struct varshead *headp;
    const char *nametail = name;
    /*! True if the old value was not an empty string. */
    int old_value_existed = 0;
    if (name[strlen(name) - 1] == ')') {
       char *function = ast_strdupa(name);
       return ast_func_write(chan, function, value);
    }
    if (chan) {
       ast_channel_lock(chan);
       headp = ast_channel_varshead(chan);
    } else {
       ast_rwlock_wrlock(&globalslock);
       headp = &globals;
    }
    /* For comparison purposes, we have to strip leading underscores */
    if (*nametail == '_') {
       nametail++;
       if (*nametail == '_')
          nametail++;
    }
    AST_LIST_TRAVERSE_SAFE_BEGIN(headp, newvariable, entries) {
       if (strcmp(ast_var_name(newvariable), nametail) == 0) {
          /* there is already such a variable, delete it */
          AST_LIST_REMOVE_CURRENT(entries);
          old_value_existed = !ast_strlen_zero(ast_var_value(newvariable));
          ast_var_delete(newvariable);
          break;
       }
    }
    AST_LIST_TRAVERSE_SAFE_END;
    if (value && (newvariable = ast_var_assign(name, value))) {
       if (headp == &globals) {
          ast_verb(2, "Setting global variable '%s' to '%s'\n", name, value);
       }
       AST_LIST_INSERT_HEAD(headp, newvariable, entries);
       ast_channel_publish_varset(chan, name, value);
    } else if (old_value_existed) {
       /* We just deleted a non-empty dialplan variable. */
       ast_channel_publish_varset(chan, name, "");
    }
    if (chan)
       ast_channel_unlock(chan);
    else
       ast_rwlock_unlock(&globalslock);
    return 0;
 }
pbx_builtin_setvar_multiple()
int pbx_builtin_setvar_multiple (struct ast_channel * chan, const char * data)
Parse and set multiple channel variables, where the pairs are separated by the ',' character, and name and value are separated with an '=' character.
Note
Will lock the channel.
Definition at line 1155 of file pbx_variables.c.
References args, AST_APP_ARG, ast_channel_context(), ast_channel_exten(), ast_channel_priority(), AST_DECLARE_APP_ARGS, ast_log, AST_NONSTANDARD_APP_ARGS, AST_STANDARD_APP_ARGS, ast_strdupa, ast_strlen_zero, LOG_WARNING, name, pair::name, pbx_builtin_setvar_helper(), and value.
Referenced by load_pbx_variables(), queue_function_var(), set_queue_variables(), and try_calling().
 {
    char *data;
    int x;
    AST_DECLARE_APP_ARGS(args,
       AST_APP_ARG(pair)[24];
    );
    AST_DECLARE_APP_ARGS(pair,
       AST_APP_ARG(name);
       AST_APP_ARG(value);
    );
    if (ast_strlen_zero(vdata)) {
       ast_log(LOG_WARNING, "MSet requires at least one variable name/value pair.\n");
       return 0;
    }
    data = ast_strdupa(vdata);
    AST_STANDARD_APP_ARGS(args, data);
    for (x = 0; x < args.argc; x++) {
       AST_NONSTANDARD_APP_ARGS(pair, args.pair[x], '=');
       if (pair.argc == 2) {
          pbx_builtin_setvar_helper(chan, pair.name, pair.value);
          if (strchr(pair.name, ' '))
             ast_log(LOG_WARNING, "Please avoid unnecessary spaces on variables as it may lead to unexpected results ('%s' set to '%s').\n", pair.name, pair.value);
       } else if (!chan) {
          ast_log(LOG_WARNING, "MSet: ignoring entry '%s' with no '='\n", pair.name);
       } else {
          ast_log(LOG_WARNING, "MSet: ignoring entry '%s' with no '=' (in %s@%s:%d\n", pair.name, ast_channel_exten(chan), ast_channel_context(chan), ast_channel_priority(chan));
       }
    }
    return 0;
 }
pbx_retrieve_variable()
void pbx_retrieve_variable (struct ast_channel * c, const char * var, char ** ret, char * workspace, int workspacelen, struct varshead * headp)
Support for Asterisk built-in variables in the dialplan.
Retrieve the value of a builtin variable or variable from the channel variable stack.
Note
See also
Globally predefined channel variables Channel variables
Hangup Causes for Asterisk The HANGUPCAUSE variable
Definition at line 235 of file pbx_variables.c.
References ast_copy_string(), ast_free, ast_str_buffer(), ast_str_create, ast_str_retrieve_variable(), NULL, and str.
Referenced by action_getvar(), generate_status(), handle_getvariable(), lua_get_variable(), lua_get_variable_value(), and pbx_substitute_variables_helper_full().
 {
    struct ast_str *str = ast_str_create(16);
    const char *cret;
    cret = ast_str_retrieve_variable(&str, 0, c, headp, var);
    ast_copy_string(workspace, ast_str_buffer(str), workspacelen);
    *ret = cret ? workspace : NULL;
    ast_free(str);
 }
pbx_substitute_variables_helper()
void pbx_substitute_variables_helper (struct ast_channel * c, const char * cp1, char * cp2, int count)
Definition at line 835 of file pbx_variables.c.
References ast_channel_varshead(), NULL, and pbx_substitute_variables_helper_full().
 {
    pbx_substitute_variables_helper_full(c, (c) ? ast_channel_varshead(c) : NULL, cp1, cp2, count, NULL);
 }
pbx_substitute_variables_helper_full()
void pbx_substitute_variables_helper_full (struct ast_channel * c, struct varshead * headp, const char * cp1, char * cp2, int count, size_t * used)
Definition at line 626 of file pbx_variables.c.
References ast_channel_unref, ast_channel_varshead(), ast_copy_string(), ast_debug, ast_dummy_channel_alloc, ast_expr(), ast_func_read(), ast_log, ast_strlen_zero, len(), LOG_ERROR, LOG_WARNING, NULL, parse_variable_name(), pbx_retrieve_variable(), substring(), var, and VAR_BUF_SIZE.
Referenced by pbx_substitute_variables_helper(), and pbx_substitute_variables_varshead().
 {
    /* Substitutes variables into cp2, based on string cp1, cp2 NO LONGER NEEDS TO BE ZEROED OUT!!!!  */
    const char *whereweare;
    const char *orig_cp2 = cp2;
    char ltmp[VAR_BUF_SIZE];
    char var[VAR_BUF_SIZE];
    *cp2 = 0; /* just in case nothing ends up there */
    whereweare = cp1;
    while (!ast_strlen_zero(whereweare) && count) {
       char *nextvar = NULL;
       char *nextexp = NULL;
       char *nextthing;
       char *vars;
       char *vare;
       int length;
       int pos;
       int brackets;
       int needsub;
       int len;
       /* Determine how much simply needs to be copied to the output buf. */
       nextthing = strchr(whereweare, '$');
       if (nextthing) {
          pos = nextthing - whereweare;
          switch (nextthing[1]) {
          case '{':
             /* Variable substitution */
             nextvar = nextthing;
             break;
          case '[':
             /* Expression substitution */
             nextexp = nextthing;
             break;
          default:
             /* '$' is not part of a substitution so include it too. */
             ++pos;
             break;
          }
       } else {
          /* We're copying the whole remaining string */
          pos = strlen(whereweare);
       }
       if (pos) {
          /* Can't copy more than 'count' bytes */
          if (pos > count)
             pos = count;
          /* Copy that many bytes */
          memcpy(cp2, whereweare, pos);
          count -= pos;
          cp2 += pos;
          whereweare += pos;
          *cp2 = 0;
       }
       if (nextvar) {
          int offset;
          int offset2;
          int isfunction;
          char *cp4;
          char workspace[VAR_BUF_SIZE] = "";
          /* We have a variable.  Find the start and end, and determine
             if we are going to have to recursively call ourselves on the
             contents */
          vars = vare = nextvar + 2;
          brackets = 1;
          needsub = 0;
          /* Find the end of it */
          while (brackets && *vare) {
             if ((vare[0] == '$') && (vare[1] == '{')) {
                needsub++;
                brackets++;
                vare++;
             } else if (vare[0] == '{') {
                brackets++;
             } else if (vare[0] == '}') {
                brackets--;
             } else if ((vare[0] == '$') && (vare[1] == '[')) {
                needsub++;
                vare++;
             }
             vare++;
          }
          len = vare - vars;
          if (brackets) {
             ast_log(LOG_WARNING, "Error in extension logic (missing '}')\n");
          } else {
             /* Don't count the closing '}' in the length. */
             --len;
          }
          /* Skip totally over variable string */
          whereweare = vare;
          /* Store variable name expression to lookup (and truncate). */
          ast_copy_string(var, vars, len + 1);
          /* Substitute if necessary */
          if (needsub) {
             pbx_substitute_variables_helper_full(c, headp, var, ltmp, VAR_BUF_SIZE - 1, NULL);
             vars = ltmp;
          } else {
             vars = var;
          }
          parse_variable_name(vars, &offset, &offset2, &isfunction);
          if (isfunction) {
             /* Evaluate function */
             if (c || !headp)
                cp4 = ast_func_read(c, vars, workspace, VAR_BUF_SIZE) ? NULL : workspace;
             else {
                struct varshead old;
                struct ast_channel *bogus;
                bogus = ast_dummy_channel_alloc();
                if (bogus) {
                   old = *ast_channel_varshead(bogus);
                   *ast_channel_varshead(bogus) = *headp;
                   cp4 = ast_func_read(bogus, vars, workspace, VAR_BUF_SIZE) ? NULL : workspace;
                   /* Don't deallocate the varshead that was passed in */
                   *ast_channel_varshead(bogus) = old;
                   ast_channel_unref(bogus);
                } else {
                   ast_log(LOG_ERROR, "Unable to allocate bogus channel for function value substitution.\n");
                   cp4 = NULL;
                }
             }
             ast_debug(2, "Function %s result is '%s'\n", vars, cp4 ? cp4 : "(null)");
          } else {
             /* Retrieve variable value */
             pbx_retrieve_variable(c, vars, &cp4, workspace, VAR_BUF_SIZE, headp);
          }
          if (cp4) {
             cp4 = substring(cp4, offset, offset2, workspace, VAR_BUF_SIZE);
             length = strlen(cp4);
             if (length > count)
                length = count;
             memcpy(cp2, cp4, length);
             count -= length;
             cp2 += length;
             *cp2 = 0;
          }
       } else if (nextexp) {
          /* We have an expression.  Find the start and end, and determine
             if we are going to have to recursively call ourselves on the
             contents */
          vars = vare = nextexp + 2;
          brackets = 1;
          needsub = 0;
          /* Find the end of it */
          while (brackets && *vare) {
             if ((vare[0] == '$') && (vare[1] == '[')) {
                needsub++;
                brackets++;
                vare++;
             } else if (vare[0] == '[') {
                brackets++;
             } else if (vare[0] == ']') {
                brackets--;
             } else if ((vare[0] == '$') && (vare[1] == '{')) {
                needsub++;
                vare++;
             }
             vare++;
          }
          len = vare - vars;
          if (brackets) {
             ast_log(LOG_WARNING, "Error in extension logic (missing ']')\n");
          } else {
             /* Don't count the closing ']' in the length. */
             --len;
          }
          /* Skip totally over expression */
          whereweare = vare;
          /* Store expression to evaluate (and truncate). */
          ast_copy_string(var, vars, len + 1);
          /* Substitute if necessary */
          if (needsub) {
             pbx_substitute_variables_helper_full(c, headp, var, ltmp, VAR_BUF_SIZE - 1, NULL);
             vars = ltmp;
          } else {
             vars = var;
          }
          length = ast_expr(vars, cp2, count, c);
          if (length) {
             ast_debug(1, "Expression result is '%s'\n", cp2);
             count -= length;
             cp2 += length;
             *cp2 = 0;
          }
       }
    }
    if (used) {
       *used = cp2 - orig_cp2;
    }
 }
pbx_substitute_variables_varshead()
void pbx_substitute_variables_varshead (struct varshead * headp, const char * cp1, char * cp2, int count)
Definition at line 840 of file pbx_variables.c.
References NULL, and pbx_substitute_variables_helper_full().
Referenced by do_say(), dundi_lookup_local(), get_mapping_weight(), and loopback_subst().
 {
    pbx_substitute_variables_helper_full(NULL, headp, cp1, cp2, count, NULL);
 }
substring()
static char* substring (const char * value, int offset, int length, char * workspace, size_t workspace_len) static
takes a substring. It is ok to call with value == workspace.
Parameters
value
offset < 0 means start from the end of the string and set the beginning to be that many characters back.
length is the length of the substring, a value less than 0 means to leave that many off the end.
workspace
workspace_len Always return a copy in workspace.
Definition at line 149 of file pbx_variables.c.
References ast_copy_string().
Referenced by pbx_substitute_variables_helper_full().
 {
    char *ret = workspace;
    int lr;  /* length of the input string after the copy */
    ast_copy_string(workspace, value, workspace_len); /* always make a copy */
    lr = strlen(ret); /* compute length after copy, so we never go out of the workspace */
    /* Quick check if no need to do anything */
    if (offset == 0 && length >= lr) /* take the whole string */
       return ret;
    if (offset < 0)   {  /* translate negative offset into positive ones */
       offset = lr + offset;
       if (offset < 0) /* If the negative offset was greater than the length of the string, just start at the beginning */
          offset = 0;
    }
    /* too large offset result in empty string so we know what to return */
    if (offset >= lr)
       return ret + lr;  /* the final '\0' */
    ret += offset;    /* move to the start position */
    if (length >= 0 && length < lr - offset)  /* truncate if necessary */
       ret[length] = '\0';
    else if (length < 0) {
       if (lr > offset - length) /* After we remove from the front and from the rear, is there anything left? */
          ret[lr + length - offset] = '\0';
       else
          ret[0] = '\0';
    }
    return ret;
 }
unload_pbx_variables()
static void unload_pbx_variables (void) static
Definition at line 1208 of file pbx_variables.c.
References ARRAY_LEN, ast_cli_unregister_multiple(), ast_unregister_application(), and pbx_builtin_clear_globals().
Referenced by load_pbx_variables().
 {
    ast_cli_unregister_multiple(vars_cli, ARRAY_LEN(vars_cli));
    ast_unregister_application("Set");
    ast_unregister_application("MSet");
    pbx_builtin_clear_globals();
 }
Variable Documentation
globals
struct varshead globals = AST_LIST_HEAD_NOLOCK_INIT_VALUE static
Definition at line 109 of file pbx_variables.c.
Referenced by pbx_builtin_pushvar_helper(), and pbx_builtin_setvar_helper().
globalslock
ast_rwlock_t globalslock = { PTHREAD_RWLOCK_INITIALIZER , NULL, {1, 0} } static
Definition at line 108 of file pbx_variables.c.
Referenced by ast_str_retrieve_variable(), handle_show_globals(), pbx_builtin_clear_globals(), pbx_builtin_getvar_helper(), pbx_builtin_pushvar_helper(), and pbx_builtin_setvar_helper().
vars_cli
struct ast_cli_entry vars_cli[] static
Definition at line 1201 of file pbx_variables.c.