Asterisk - The Open Source Telephony Project: ael_main.c File Reference
ael_main.c File Reference
#include "asterisk.h"
#include <locale.h>
#include <ctype.h>
#include <regex.h>
#include <limits.h>
#include "asterisk/backtrace.h"
#include "asterisk/channel.h"
#include "asterisk/ast_expr.h"
#include "asterisk/module.h"
#include "asterisk/app.h"
#include "asterisk/lock.h"
#include "asterisk/hashtab.h"
#include "asterisk/ael_structs.h"
#include "asterisk/extconf.h"
Data Structures
struct ast_context
ast_context: An extension context - must remain in sync with fake_context
struct namelist
Macros
#define ADD_LAST(headptr, memptr) if(!headptr){ headptr=(memptr); (headptr##_last)=(memptr);} else {(headptr##_last)->next = (memptr); (headptr##_last) = (memptr);}
#define ASTMM_LIBC ASTMM_IGNORE
Functions
int __ast_bt_get_addresses (struct ast_bt *bt)
struct ast_vector_string * __ast_bt_get_symbols (void **addresses, size_t num_frames)
void __ast_cli_register_multiple (void)
void __ast_verbose (const char *file, int line, const char *func, int level, const char *fmt,...)
Send a verbose message (based on verbose level)
int ael_external_load_module (void)
int ast_add_extension2 (struct ast_context *con, int replace, const char *extension, int priority, const char *label, const char *callerid, const char *application, void *data, void(*datad)(void *), const char *registrar)
int ast_add_profile (const char *x, uint64_t scale)
support for event profiling
void ast_cli_unregister_multiple (void)
void ast_context_add_ignorepat2 (struct ast_context *con, const char *value, const char *registrar)
void ast_context_add_include2 (struct ast_context *con, const char *value, const char *registrar)
Add a context include.
void ast_context_add_switch2 (struct ast_context *con, const char *value, const char *data, int eval, const char *registrar)
Adds a switch (first param is a ast_context)
struct ast_context * ast_context_create (void **extcontexts, const char *name, const char *registrar)
void ast_context_destroy (void)
struct ast_context * ast_context_find_or_create (void **extcontexts, void *tab, const char *name, const char *registrar)
void ast_context_verify_includes (void)
struct ast_custom_function * ast_custom_function_find (const char *name)
const char * ast_get_context_name (struct ast_context *con)
int ast_hashtab_compare_contexts (const void *ah_a, const void *ah_b)
hashtable functions for contexts
unsigned int ast_hashtab_hash_contexts (const void *obj)
int ast_loader_register (int(*updater)(void))
Add a procedure to be run when modules have been updated.
int ast_loader_unregister (int(*updater)(void))
Remove a procedure to be run when modules are updated.
void ast_log (int level, const char *file, int line, const char *function, const char *fmt,...)
Used for sending a log message This is the standard logger function. Probably the only way you will invoke it would be something like this: ast_log(AST_LOG_WHATEVER, "Problem with the %s Captain. We should get some more. Will %d be enough?\n", "flux capacitor", 10); where WHATEVER is one of ERROR, DEBUG, EVENT, NOTICE, or WARNING depending on which log you wish to output to. These are implemented as macros, that will provide the function with the needed arguments.
void ast_mark_lock_acquired (void *lock_addr)
Mark the last lock as acquired.
void ast_merge_contexts_and_delete (void)
void ast_module_register (const struct ast_module_info *x)
void ast_module_unregister (const struct ast_module_info *x)
char * ast_process_quotes_and_slashes (char *start, char find, char replace_with)
Process a string to find and replace characters.
void ast_remove_lock_info (void *lock_addr, struct ast_bt *bt)
remove lock info for the current thread
void ast_restore_lock_info (void *lock_addr)
void ast_store_lock_info (enum ast_lock_type type, const char *filename, int line_num, const char *func, const char *lock_name, void *lock_addr, struct ast_bt *bt)
Store lock info for the current thread.
void ast_suspend_lock_info (void *lock_addr)
struct ast_exten * ast_walk_context_extensions (struct ast_context *con, struct ast_exten *exten)
struct ast_ignorepat * ast_walk_context_ignorepats (struct ast_context *con, struct ast_ignorepat *ip)
struct ast_include * ast_walk_context_includes (struct ast_context *con, struct ast_include *inc)
struct ast_sw * ast_walk_context_switches (struct ast_context *con, struct ast_sw *sw)
struct ast_context * ast_walk_contexts (void)
struct namelist * create_name (const char *name)
void destroy_namelist (struct namelist *x)
void filter_leading_space_from_exprs (char *str)
void filter_newlines (char *str)
int main (int argc, char **argv)
void pbx_builtin_setvar (void *chan, void *data)
struct ast_exten * pbx_find_extension (struct ast_channel *chan, struct ast_context *bypass, struct pbx_find_info *q, const char *context, const char *exten, int priority, const char *label, const char *callerid, enum ext_match_t action)
struct ast_app * pbx_findapp (const char *app)
Look up an application.
void pbx_substitute_variables_helper (struct ast_channel *c, const char *cp1, char *cp2, int count)
Variables
const char * ast_config_AST_CONFIG_DIR = config_dir
const char * ast_config_AST_VAR_DIR = var_dir
static char config_dir [PATH_MAX]
struct ast_context * context_list
int conts =0
static int dump_extensions = 0
static FILE * dumpfile
int extens =0
static int FIRST_TIME = 0
struct namelist * globalvars
struct namelist * globalvars_last
struct ast_context * last_context
char last_exten [18000]
struct module_symbols mod_data
static int no_comp = 0
int option_debug = 0
int option_verbose = 0
int priors =0
static int quiet = 0
static int use_curr_dir = 0
static char var_dir [PATH_MAX]
Macro Definition Documentation
ADD_LAST
#define ADD_LAST (headptr, memptr) if(!headptr){ headptr=(memptr); (headptr##_last)=(memptr);} else {(headptr##_last)->next = (memptr); (headptr##_last) = (memptr);}
Definition at line 64 of file ael_main.c.
Referenced by ast_context_add_ignorepat2(), ast_context_add_include2(), ast_context_add_switch2(), and pbx_builtin_setvar().
ASTMM_LIBC
#define ASTMM_LIBC ASTMM_IGNORE
Definition at line 14 of file ael_main.c.
Function Documentation
__ast_bt_get_addresses()
int __ast_bt_get_addresses (struct ast_bt * bt)
Definition at line 615 of file ael_main.c.
 {
    return 0;
 }
__ast_bt_get_symbols()
struct ast_vector_string* __ast_bt_get_symbols (void ** addresses, size_t num_frames)
Definition at line 620 of file ael_main.c.
References NULL.
 {
    return NULL;
 }
__ast_cli_register_multiple()
void __ast_cli_register_multiple (void)
Definition at line 204 of file ael_main.c.
References c, and pbx_substitute_variables_helper().
 {
    if(!no_comp)
          printf("Executed ast_cli_register_multiple();\n");
 }
__ast_verbose()
void __ast_verbose (const char * file, int line, const char * func, int level, const char * fmt, ...)
Send a verbose message (based on verbose level)
This works like ast_log, but prints verbose messages to the console depending on verbosity level set.
ast_verbose(VERBOSE_PREFIX_3 "Whatever %s is happening\n", "nothing");
This will print the message to the console if the verbose level is set to a level >= 3
Note the absence of a comma after the VERBOSE_PREFIX_3. This is important. VERBOSE_PREFIX_1 through VERBOSE_PREFIX_4 are defined.
Version
11 added level parameter
Definition at line 2198 of file logger.c.
References __ast_verbose_ap(), and ast_read_threadstorage_callid().
 {
    ast_callid callid;
    va_list ap;
    callid = ast_read_threadstorage_callid();
    va_start(ap, fmt);
    __ast_verbose_ap(file, line, func, level, callid, fmt, ap);
    va_end(ap);
 }
ael_external_load_module()
int ael_external_load_module (void)
Referenced by filter_newlines(), main(), and reload().
ast_add_extension2()
int ast_add_extension2 (struct ast_context * con, int replace, const char * extension, int priority, const char * label, const char * callerid, const char * application, void * data, void(*)(void *) datad, const char * registrar)
Definition at line 221 of file ael_main.c.
References ast_context::eswitches, extens, ast_context::extension_count, filter_leading_space_from_exprs(), filter_newlines(), free(), ast_context::ignorepats, ast_context::includes, last_exten, namelist::name, ast_context::name, namelist::name2, namelist::next, priors, and ast_context::switches.
 {
    priors++;
    con->extension_count++;
    if (strcmp(extension,last_exten) != 0) {
       extens++;
       strcpy(last_exten, extension);
    }
    if (!label) {
       label = "(null)";
    }
    if (!callerid) {
       callerid = "(null)";
    }
    if (!application) {
       application = "(null)";
    }
    if(!no_comp)
       printf("Executed ast_add_extension2(context=%s, rep=%d, exten=%s, priority=%d, label=%s, callerid=%s, appl=%s, data=%s, FREE, registrar=%s);\n",
             con->name, replace, extension, priority, label, callerid, application, (data?(char*)data:"(null)"), registrar);
    if( dump_extensions && dumpfile ) {
       struct namelist *n;
       if( FIRST_TIME ) {
          FIRST_TIME = 0;
          if( globalvars )
             fprintf(dumpfile,"[globals]\n");
          for(n=globalvars;n;n=n->next) {
             fprintf(dumpfile, "%s\n", n->name);
          }
       }
       /* print out each extension , possibly the context header also */
       if( con != last_context ) {
          fprintf(dumpfile,"\n\n[%s]\n", con->name);
          last_context = con;
          for(n=con->ignorepats;n;n=n->next) {
             fprintf(dumpfile, "ignorepat => %s\n", n->name);
          }
          for(n=con->includes;n;n=n->next) {
             fprintf(dumpfile, "include => %s\n", n->name);
          }
          for(n=con->switches;n;n=n->next) {
             fprintf(dumpfile, "switch => %s/%s\n", n->name, n->name2);
          }
          for(n=con->eswitches;n;n=n->next) {
             fprintf(dumpfile, "eswitch => %s/%s\n", n->name, n->name2);
          }
       }
       if( data ) {
          filter_newlines((char*)data);
          filter_leading_space_from_exprs((char*)data);
          /* in previous versions, commas were converted to '|' to separate
             args in app calls, but now, commas are used. There used to be
             code here to insert backslashes (escapes) before any commas
             that may have been embedded in the app args. This code is no more. */
          if( strcmp(label,"(null)") != 0  )
             fprintf(dumpfile,"exten => %s,%d(%s),%s(%s)\n", extension, priority, label, application, (char*)data);
          else
             fprintf(dumpfile,"exten => %s,%d,%s(%s)\n", extension, priority, application, (char*)data);
       } else {
          if( strcmp(label,"(null)") != 0  )
             fprintf(dumpfile,"exten => %s,%d(%s),%s\n", extension, priority, label, application);
          else
             fprintf(dumpfile,"exten => %s,%d,%s\n", extension, priority, application);
       }
    }
    /* since add_extension2 is responsible for the malloc'd data stuff */
    free(data);
    return 0;
 }
ast_add_profile()
int ast_add_profile (const char * x, uint64_t scale)
support for event profiling
(note, this must be documented a lot more) ast_add_profile allocates a generic 'counter' with a given name, which can be shown with the command 'core show profile <name>'
The counter accumulates positive or negative values supplied by
See also
ast_add_profile(), dividing them by the 'scale' value passed in the create call, and also counts the number of 'events'. Values can also be taked by the TSC counter on ia32 architectures, in which case you can mark the start of an event calling ast_mark(id, 1) and then the end of the event with ast_mark(id, 0). For non-i386 architectures, these two calls return 0.
support for event profiling
Returns
Returns the identifier of the counter.
Definition at line 178 of file ael_main.c.
 {
    if (!no_comp)
       printf("Executed ast_add_profile();\n");
    return 0;
 }
ast_cli_unregister_multiple()
void ast_cli_unregister_multiple (void)
Definition at line 408 of file ael_main.c.
 {
    if(!no_comp)
       printf("Executed ast_cli_unregister_multiple();\n");
 }
ast_context_add_ignorepat2()
void ast_context_add_ignorepat2 (struct ast_context * con, const char * value, const char * registrar)
Definition at line 348 of file ael_main.c.
References ADD_LAST, create_name(), and ast_context::ignorepats.
 {
    if(!no_comp)
       printf("Executed ast_context_add_ignorepat2(con, value=%s, registrar=%s);\n", value, registrar);
    if( dump_extensions ) {
       struct namelist *x;
       x = create_name(value);
       ADD_LAST(con->ignorepats,x);
    }
 }
ast_context_add_include2()
void ast_context_add_include2 (struct ast_context * con, const char * value, const char * registrar)
Add a context include.
Parameters
con context to add the include to
value include value to add
registrar who registered the context
Adds an include taking a struct ast_context as the first parameter
Return values
0 on success
-1 on failure
Definition at line 359 of file ael_main.c.
References ADD_LAST, create_name(), and ast_context::includes.
 {
    if(!no_comp)
       printf("Executed ast_context_add_include2(con, value=%s, registrar=%s);\n", value, registrar);
    if( dump_extensions ) {
       struct namelist *x;
       x = create_name((char*)value);
       ADD_LAST(con->includes,x);
    }
 }
ast_context_add_switch2()
void ast_context_add_switch2 (struct ast_context * con, const char * value, const char * data, int eval, const char * registrar)
Adds a switch (first param is a ast_context)
Note
See ast_context_add_switch() for argument information, with the exception of the first argument. In this case, it's a pointer to an ast_context structure as opposed to the name.
Definition at line 370 of file ael_main.c.
References ADD_LAST, create_name(), ast_context::eswitches, namelist::name2, and ast_context::switches.
 {
    if(!no_comp)
       printf("Executed ast_context_add_switch2(con, value=%s, data=%s, eval=%d, registrar=%s);\n", value, data, eval, registrar);
    if( dump_extensions ) {
       struct namelist *x;
       x = create_name((char*)value);
       strncpy(x->name2, data, 99);
       if( eval ) {
          ADD_LAST(con->switches,x);
       } else {
          ADD_LAST(con->eswitches,x);
       }
    }
 }
ast_context_create()
struct ast_context * ast_context_create (void ** extcontexts, const char * name, const char * registrar)
Definition at line 318 of file ael_main.c.
References calloc, context_list, conts, ast_context::name, ast_context::next, NULL, and ast_context::registrar.
 {
    struct ast_context *x = calloc(1, sizeof(*x));
    if (!x)
       return NULL;
    x->next = context_list;
    context_list = x;
    if (!no_comp)
       printf("Executed ast_context_create(conts, name=%s, registrar=%s);\n", name, registrar);
    conts++;
    strncpy(x->name, name, sizeof(x->name) - 1);
    strncpy(x->registrar, registrar, sizeof(x->registrar) - 1);
    return x;
 }
ast_context_destroy()
void ast_context_destroy (void)
Definition at line 414 of file ael_main.c.
References ast_get_context_name().
 {
    if( !no_comp)
       printf("Executed ast_context_destroy();\n");
 }
ast_context_find_or_create()
struct ast_context * ast_context_find_or_create (void ** extcontexts, void * tab, const char * name, const char * registrar)
Definition at line 333 of file ael_main.c.
References calloc, context_list, conts, ast_context::name, ast_context::next, NULL, and ast_context::registrar.
 {
    struct ast_context *x = calloc(1, sizeof(*x));
    if (!x)
       return NULL;
    x->next = context_list;
    context_list = x;
    if (!no_comp)
       printf("Executed ast_context_find_or_create(conts, name=%s, registrar=%s);\n", name, registrar);
    conts++;
    strncpy(x->name, name, sizeof(x->name) - 1);
    strncpy(x->registrar, registrar, sizeof(x->registrar) - 1);
    return x;
 }
ast_context_verify_includes()
void ast_context_verify_includes (void)
Definition at line 395 of file ael_main.c.
 {
    if(!no_comp)
       printf("Executed ast_context_verify_includes();\n");
 }
ast_custom_function_find()
struct ast_custom_function* ast_custom_function_find (const char * name)
Definition at line 173 of file ael_main.c.
Referenced by pbx_findapp().
 {
    return 0; /* in "standalone" mode, functions are just not avail */
 }
ast_get_context_name()
const char* ast_get_context_name (struct ast_context * con)
Definition at line 421 of file ael_main.c.
References ast_walk_context_extensions(), ast_context::name, and NULL.
Referenced by ast_context_destroy().
 {
    return con ? con->name : NULL;
 }
ast_hashtab_compare_contexts()
int ast_hashtab_compare_contexts (const void * ah_a, const void * ah_b)
hashtable functions for contexts
Definition at line 589 of file ael_main.c.
References ast_hashtab_hash_contexts().
Referenced by main().
 {
    return 0;
 }
ast_hashtab_hash_contexts()
unsigned int ast_hashtab_hash_contexts (const void * obj)
Definition at line 596 of file ael_main.c.
Referenced by ast_hashtab_compare_contexts().
 {
    return 0;
 }
ast_loader_register()
int ast_loader_register (int(*)(void) updater)
Add a procedure to be run when modules have been updated.
Parameters
updater The function to run when modules have been updated.
This function adds the given function to a linked list of functions to be run when the modules are updated.
Return values
0 on success
-1 on failure.
Definition at line 186 of file ael_main.c.
 {
    return 1;
 }
ast_loader_unregister()
int ast_loader_unregister (int(*)(void) updater)
Remove a procedure to be run when modules are updated.
Parameters
updater The updater function to unregister.
This removes the given function from the updater list.
Return values
0 on success
-1 on failure.
Definition at line 191 of file ael_main.c.
 {
    return 1;
 }
ast_log()
void ast_log (int level, const char * file, int line, const char * function, const char * fmt, ...)
Used for sending a log message This is the standard logger function. Probably the only way you will invoke it would be something like this: ast_log(AST_LOG_WHATEVER, "Problem with the %s Captain. We should get some more. Will %d be enough?\n", "flux capacitor", 10); where WHATEVER is one of ERROR, DEBUG, EVENT, NOTICE, or WARNING depending on which log you wish to output to. These are implemented as macros, that will provide the function with the needed arguments.
Parameters
level Type of log event
file Will be provided by the AST_LOG_* macro
line Will be provided by the AST_LOG_* macro
function Will be provided by the AST_LOG_* macro
fmt This is what is important. The format is the same as your favorite breed of printf. You know how that works, right? :-)
Definition at line 130 of file ael_main.c.
References context, exten, and pbx_find_extension().
Referenced by main().
 {
            va_list vars;
               va_start(vars,fmt);
                  printf("LOG: lev:%d file:%s  line:%d func: %s  ",
                                      level, file, line, function);
                     vprintf(fmt, vars);
                        fflush(stdout);
                           va_end(vars);
 }
ast_mark_lock_acquired()
void ast_mark_lock_acquired (void * lock_addr)
Mark the last lock as acquired.
Definition at line 602 of file ael_main.c.
 {
 }
ast_merge_contexts_and_delete()
void ast_merge_contexts_and_delete (void)
Definition at line 389 of file ael_main.c.
 {
    if(!no_comp)
       printf("Executed ast_merge_contexts_and_delete();\n");
 }
ast_module_register()
void ast_module_register (const struct ast_module_info * x)
Definition at line 195 of file ael_main.c.
 {
 }
ast_module_unregister()
void ast_module_unregister (const struct ast_module_info * x)
Definition at line 199 of file ael_main.c.
 {
 }
ast_process_quotes_and_slashes()
char* ast_process_quotes_and_slashes (char * start, char find, char replace_with)
Process a string to find and replace characters.
Parameters
start The string to analyze
find The character to find
replace_with The character that will replace the one we are looking for
Definition at line 2104 of file main/utils.c.
 {
    char *dataPut = start;
    int inEscape = 0;
    int inQuotes = 0;
    for (; *start; start++) {
       if (inEscape) {
          *dataPut++ = *start;       /* Always goes verbatim */
          inEscape = 0;
       } else {
          if (*start == '\\') {
             inEscape = 1;      /* Do not copy \ into the data */
          } else if (*start == '\'') {
             inQuotes = 1 - inQuotes;   /* Do not copy ' into the data */
          } else {
             /* Replace , with |, unless in quotes */
             *dataPut++ = inQuotes ? *start : ((*start == find) ? replace_with : *start);
          }
       }
    }
    if (start != dataPut)
       *dataPut = 0;
    return dataPut;
 }
ast_remove_lock_info()
void ast_remove_lock_info (void * lock_addr, struct ast_bt * bt)
remove lock info for the current thread
this gets called by ast_mutex_unlock so that information on the lock can be removed from the current thread's lock info struct.
Definition at line 605 of file ael_main.c.
 {
 }
ast_restore_lock_info()
void ast_restore_lock_info (void * lock_addr)
Definition at line 628 of file ael_main.c.
 {
 }
ast_store_lock_info()
void ast_store_lock_info (enum ast_lock_type type, const char * filename, int line_num, const char * func, const char * lock_name, void * lock_addr, struct ast_bt * bt)
Store lock info for the current thread.
This function gets called in ast_mutex_lock() and ast_mutex_trylock() so that information about this lock can be stored in this thread's lock info struct. The lock is marked as pending as the thread is waiting on the lock. ast_mark_lock_acquired() will mark it as held by this thread.
Definition at line 609 of file ael_main.c.
 {
 }
ast_suspend_lock_info()
void ast_suspend_lock_info (void * lock_addr)
Definition at line 625 of file ael_main.c.
 {
 }
ast_walk_context_extensions()
struct ast_exten* ast_walk_context_extensions (struct ast_context * con, struct ast_exten * exten)
Definition at line 427 of file ael_main.c.
References ast_walk_context_includes(), and NULL.
Referenced by ast_get_context_name().
 {
    return NULL;
 }
ast_walk_context_ignorepats()
static struct ast_ignorepat * ast_walk_context_ignorepats (struct ast_context * con, struct ast_ignorepat * ip)
Definition at line 439 of file ael_main.c.
References ast_walk_context_switches(), and NULL.
Referenced by ast_walk_context_includes().
 {
    return NULL;
 }
ast_walk_context_includes()
static struct ast_include * ast_walk_context_includes (struct ast_context * con, struct ast_include * inc)
Definition at line 433 of file ael_main.c.
References ast_walk_context_ignorepats(), and NULL.
Referenced by ast_walk_context_extensions().
 {
    return NULL;
 }
ast_walk_context_switches()
static struct ast_sw * ast_walk_context_switches (struct ast_context * con, struct ast_sw * sw)
Definition at line 445 of file ael_main.c.
References NULL.
Referenced by ast_walk_context_ignorepats().
 {
    return NULL;
 }
ast_walk_contexts()
struct ast_context * ast_walk_contexts (void)
Definition at line 401 of file ael_main.c.
 {
    if(!no_comp)
       printf("Executed ast_walk_contexts();\n");
    return 0;
 }
create_name()
struct namelist * create_name (const char * name)
Definition at line 79 of file ael_main.c.
References calloc, namelist::name, and NULL.
Referenced by ast_context_add_ignorepat2(), ast_context_add_include2(), ast_context_add_switch2(), destroy_namelist(), and pbx_builtin_setvar().
 {
    struct namelist *x = calloc(1, sizeof(*x));
    if (!x)
       return NULL;
    strncpy(x->name, name, sizeof(x->name) - 1);
    return x;
 }
destroy_namelist()
void destroy_namelist (struct namelist * x)
Definition at line 67 of file ael_main.c.
References create_name(), free(), namelist::name, and namelist::next.
Referenced by main().
 {
    struct namelist *z,*z2;
    for(z=x; z; z = z2)
    {
       z2 = z->next;
       z->next = 0;
       free(z);
    }
 }
filter_leading_space_from_exprs()
void filter_leading_space_from_exprs (char * str)
Definition at line 450 of file ael_main.c.
References str.
Referenced by ast_add_extension2().
 {
    /*  Mainly for aesthetics */
    char *t, *v, *u = str;
    while ( u && *u ) {
       if( *u == '$' && *(u+1) == '[' ) {
          t = u+2;
          while( *t == '\n' || *t == '\r' || *t == '\t' || *t == ' ' ) {
             v = t;
             while ( *v ) {
                *v = *(v+1);
                v++;
             }
          }
       }
       u++;
    }
 }
filter_newlines()
void filter_newlines (char * str)
Definition at line 472 of file ael_main.c.
References ael_external_load_module(), and str.
Referenced by ast_add_extension2().
 {
    /* remove all newlines, returns  */
    char *t=str;
    while( t && *t ) {
       if( *t == '\n' || *t == '\r' ) {
          *t = ' '; /* just replace newlines and returns with spaces; they act as
                    token separators, and just blindly removing them could be
                    harmful. */
       }
       t++;
    }
 }
main()
int main (int argc, char ** argv)
Definition at line 491 of file ael_main.c.
References ael_external_load_module(), ast_hashtab_compare_contexts(), ast_log(), config_dir, conts, destroy_namelist(), ast_context::eswitches, extens, ast_context::extension_count, free(), ast_context::ignorepats, ast_context::includes, localized_use_conf_dir(), localized_use_local_dir(), namelist::name, ast_context::name, namelist::name2, namelist::next, ast_context::next, priors, ast_context::switches, and var_dir.
 {
    int i;
    struct namelist *n;
    struct ast_context *lp,*lp2;
    for(i=1;i<argc;i++) {
       if( argv[i][0] == '-' && argv[i][1] == 'n' )
          no_comp =1;
       if( argv[i][0] == '-' && argv[i][1] == 'q' ) {
          quiet = 1;
          no_comp =1;
       }
       if( argv[i][0] == '-' && argv[i][1] == 'd' )
          use_curr_dir =1;
       if( argv[i][0] == '-' && argv[i][1] == 'w' )
          dump_extensions =1;
    }
    if( !quiet ) {
       printf("\n(If you find progress and other non-error messages irritating, you can use -q to suppress them)\n");
       if( !no_comp )
          printf("\n(You can use the -n option if you aren't interested in seeing all the instructions generated by the compiler)\n\n");
       if( !use_curr_dir )
          printf("\n(You can use the -d option if you want to use the current working directory as the CONFIG_DIR. I will look in this dir for extensions.ael* and its included files)\n\n");
       if( !dump_extensions )
          printf("\n(You can use the -w option to dump extensions.conf format to extensions.conf.aeldump)\n");
    }
    if( use_curr_dir ) {
       strcpy(config_dir, ".");
       localized_use_local_dir();
    }
    else {
       strcpy(config_dir, "/etc/asterisk");
       localized_use_conf_dir();
    }
    strcpy(var_dir, "/var/lib/asterisk");
    if( dump_extensions ) {
       dumpfile = fopen("extensions.conf.aeldump","w");
       if( !dumpfile ) {
          printf("\n\nSorry, cannot open extensions.conf.aeldump for writing! Correct the situation and try again!\n\n");
          exit(10);
       }
    }
    FIRST_TIME = 1;
    ael_external_load_module();
    ast_log(4, "ael2_parse", __LINE__, "main", "%d contexts, %d extensions, %d priorities\n", conts, extens, priors);
    if( dump_extensions && dumpfile ) {
       for( lp = context_list; lp; lp = lp->next ) { /* print out any contexts that didn't have any
                                            extensions in them */
          if( lp->extension_count == 0 ) {
             fprintf(dumpfile,"\n\n[%s]\n", lp->name);
             for(n=lp->ignorepats;n;n=n->next) {
                fprintf(dumpfile, "ignorepat => %s\n", n->name);
             }
             for(n=lp->includes;n;n=n->next) {
                fprintf(dumpfile, "include => %s\n", n->name);
             }
             for(n=lp->switches;n;n=n->next) {
                fprintf(dumpfile, "switch => %s/%s\n", n->name, n->name2);
             }
             for(n=lp->eswitches;n;n=n->next) {
                fprintf(dumpfile, "eswitch => %s/%s\n", n->name, n->name2);
             }
          }
       }
    }
    if( dump_extensions && dumpfile )
       fclose(dumpfile);
    for( lp = context_list; lp; lp = lp2 ) { /* free the ast_context structs */
       lp2 = lp->next;
       lp->next = 0;
       destroy_namelist(lp->includes);
       destroy_namelist(lp->ignorepats);
       destroy_namelist(lp->switches);
       destroy_namelist(lp->eswitches);
       free(lp);
    }
     return 0;
 }
pbx_builtin_setvar()
void pbx_builtin_setvar (void * chan, void * data)
Definition at line 305 of file ael_main.c.
References ADD_LAST, and create_name().
 {
    struct namelist *x = create_name(data);
    if(!no_comp)
       printf("Executed pbx_builtin_setvar(chan, data=%s);\n", (char*)data);
    if( dump_extensions ) {
       x = create_name(data);
       ADD_LAST(globalvars,x);
    }
 }
pbx_find_extension()
struct ast_exten* pbx_find_extension (struct ast_channel * chan, struct ast_context * bypass, struct pbx_find_info * q, const char * context, const char * exten, int priority, const char * label, const char * callerid, enum ext_match_t action)
Definition at line 152 of file ael_main.c.
References localized_find_extension().
Referenced by ast_log().
 {
    return localized_find_extension(bypass, q, context, exten, priority, label, callerid, action);
 }
pbx_findapp()
struct ast_app* pbx_findapp (const char * app)
Look up an application.
Parameters
app name of the app
This function searches for the ast_app structure within the apps that are registered for the one with the name you passed in.
Returns
the ast_app structure that matches on success, or NULL on failure
Definition at line 165 of file ael_main.c.
References ast_custom_function_find(), and namelist::name.
Referenced by aelsub_exec(), answer_exec_run(), ari_channel_thread(), ari_originate_dial(), ast_app_exec_macro(), AST_TEST_DEFINE(), bridge_check_monitor(), bridge_stasis_run_cb(), conf_run(), conf_start_record(), disa_exec(), do_magic_pickup(), dundi_exec(), exec_exec(), execif_exec(), forward_message(), handle_exec(), iax2_exec(), lua_pbx_exec(), page_exec(), pbx_builtin_execiftime(), pbx_extension_helper(), pbx_outgoing_exec(), realtime_exec(), run_app_helper(), snoop_stasis_thread(), try_calling(), and tryexec_exec().
 {
    return (struct ast_app*)1; /* so as not to trigger an error */
 }
pbx_substitute_variables_helper()
void pbx_substitute_variables_helper (struct ast_channel * c, const char * cp1, char * cp2, int count)
Definition at line 211 of file ael_main.c.
References AST_MAX_EXTENSION.
Referenced by __ast_cli_register_multiple().
 {
    if (cp1 && *cp1)
       strncpy(cp2,cp1,AST_MAX_EXTENSION); /* Right now, this routine is ONLY being called for
                                     a possible var substitution on extension names,
                                     so....! */
    else
       *cp2 = 0;
 }
Variable Documentation
ast_config_AST_CONFIG_DIR
const char* ast_config_AST_CONFIG_DIR = config_dir
Definition at line 98 of file ael_main.c.
ast_config_AST_VAR_DIR
const char* ast_config_AST_VAR_DIR = var_dir
Definition at line 99 of file ael_main.c.
Referenced by ael2_semantic_check(), ast_str_retrieve_variable(), handle_show_settings(), launch_script(), and ustmtext().
config_dir
char config_dir[PATH_MAX] static
Definition at line 96 of file ael_main.c.
Referenced by main().
context_list
struct ast_context* context_list
Definition at line 88 of file ael_main.c.
Referenced by ast_context_create(), and ast_context_find_or_create().
conts
int conts =0
Definition at line 93 of file ael_main.c.
Referenced by ast_context_create(), ast_context_find_or_create(), and main().
dump_extensions
int dump_extensions = 0 static
Definition at line 126 of file ael_main.c.
dumpfile
FILE* dumpfile static
Definition at line 128 of file ael_main.c.
extens
int extens =0
Definition at line 93 of file ael_main.c.
Referenced by ast_add_extension2(), check_retrieve_call_extensions(), and main().
FIRST_TIME
int FIRST_TIME = 0 static
Definition at line 127 of file ael_main.c.
globalvars
struct namelist* globalvars
Definition at line 90 of file ael_main.c.
globalvars_last
struct namelist* globalvars_last
Definition at line 91 of file ael_main.c.
last_context
struct ast_context* last_context
Definition at line 89 of file ael_main.c.
last_exten
char last_exten[18000]
Definition at line 94 of file ael_main.c.
Referenced by ast_add_extension2().
mod_data
struct module_symbols mod_data
no_comp
int no_comp = 0 static
Definition at line 124 of file ael_main.c.
priors
int priors =0
Definition at line 93 of file ael_main.c.
Referenced by ast_add_extension2(), and main().
quiet
int quiet = 0 static
Definition at line 123 of file ael_main.c.
Referenced by confbridge_exec().
use_curr_dir
int use_curr_dir = 0 static
Definition at line 125 of file ael_main.c.
var_dir
char var_dir[PATH_MAX] static
Definition at line 97 of file ael_main.c.
Referenced by main().