Asterisk - The Open Source Telephony Project: rec_put.c File Reference
rec_put.c File Reference
#include <sys/types.h>
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "../include/db.h"
#include "recno.h"
Functions
int __rec_iput (BTREE *t, recno_t nrec, const DBT *data, u_int flags)
int __rec_put (DB *dbp, DBT *key, const DBT *data, u_int flags) const
Function Documentation
__rec_iput()
int __rec_iput (BTREE * t, recno_t nrec, const DBT * data, u_int flags)
Definition at line 190 of file rec_put.c.
References __bt_split(), __ovfl_put(), __rec_dleaf(), __rec_search(), B_MODIFIED, _btree::bt_mp, _btree::bt_nrecs, _btree::bt_ovflsize, DBT::data, db, F_SET, _epg::index, _page::linp, _page::lower, MPOOL_DIRTY, mpool_put(), NEXTINDEX, NOVFLSIZE, NRLEAFDBT, NULL, P_BIGDATA, _epg::page, R_IAFTER, R_IBEFORE, RET_ERROR, RET_SUCCESS, SEARCH, SINSERT, DBT::size, status, _page::upper, and WR_RLEAF.
Referenced by __rec_fmap(), __rec_fpipe(), __rec_put(), __rec_vmap(), and __rec_vpipe().
 {
    DBT tdata;
    EPG *e;
    PAGE *h;
    indx_t idx, nxtindex;
    pgno_t pg;
    u_int32_t nbytes;
    int dflags, status;
    char *dest, db[NOVFLSIZE];
    /*
     * If the data won't fit on a page, store it on indirect pages.
     *
     * XXX
     * If the insert fails later on, these pages aren't recovered.
     */
    if (data->size > t->bt_ovflsize) {
       if (__ovfl_put(t, data, &pg) == RET_ERROR)
          return (RET_ERROR);
       tdata.data = db;
       tdata.size = NOVFLSIZE;
       *(pgno_t *)db = pg;
       *(u_int32_t *)(db + sizeof(pgno_t)) = data->size;
       dflags = P_BIGDATA;
       data = &tdata;
    } else
       dflags = 0;
    /* __rec_search pins the returned page. */
    if ((e = __rec_search(t, nrec,
        nrec > t->bt_nrecs || flags == R_IAFTER || flags == R_IBEFORE ?
        SINSERT : SEARCH)) == NULL)
       return (RET_ERROR);
    h = e->page;
    idx = e->index;
    /*
     * Add the specified key/data pair to the tree.  The R_IAFTER and
     * R_IBEFORE flags insert the key after/before the specified key.
     *
     * Pages are split as required.
     */
    switch (flags) {
    case R_IAFTER:
       ++idx;
       break;
    case R_IBEFORE:
       break;
    default:
       if (nrec < t->bt_nrecs &&
           __rec_dleaf(t, h, idx) == RET_ERROR) {
          mpool_put(t->bt_mp, h, 0);
          return (RET_ERROR);
       }
       break;
    }
    /*
     * If not enough room, split the page.  The split code will insert
     * the key and data and unpin the current page.  If inserting into
     * the offset array, shift the pointers up.
     */
    nbytes = NRLEAFDBT(data->size);
    if ((u_int32_t) (h->upper - h->lower) < nbytes + sizeof(indx_t)) {
       status = __bt_split(t, h, NULL, data, dflags, nbytes, idx);
       if (status == RET_SUCCESS)
          ++t->bt_nrecs;
       return (status);
    }
    if (idx < (nxtindex = NEXTINDEX(h)))
       memmove(h->linp + idx + 1, h->linp + idx,
           (nxtindex - idx) * sizeof(indx_t));
    h->lower += sizeof(indx_t);
    h->linp[idx] = h->upper -= nbytes;
    dest = (char *)h + h->upper;
    WR_RLEAF(dest, data, dflags);
    ++t->bt_nrecs;
    F_SET(t, B_MODIFIED);
    mpool_put(t->bt_mp, h, MPOOL_DIRTY);
    return (RET_SUCCESS);
 }
__rec_put()
int __rec_put (DB * dbp, DBT * key, const DBT * data, u_int flags) const
Definition at line 62 of file rec_put.c.
References __rec_iput(), __rec_ret(), _btree::bt_bval, _btree::bt_cursor, _btree::bt_mp, _btree::bt_nrecs, _btree::bt_pinned, _btree::bt_rdata, _btree::bt_reclen, CURS_INIT, DBT::data, errno, F_ISSET, F_SET, free(), __db::internal, malloc(), mpool_put(), NULL, R_CURSOR, R_EOF, R_FIXLEN, R_IAFTER, R_IBEFORE, R_INMEM, R_MODIFIED, R_NOOVERWRITE, R_SETCURSOR, _cursor::rcursor, realloc, RET_ERROR, RET_SPECIAL, RET_SUCCESS, DBT::size, and status.
Referenced by __rec_open().
 {
    BTREE *t;
    DBT fdata, tdata;
    recno_t nrec;
    int status;
    t = dbp->internal;
    /* Toss any page pinned across calls. */
    if (t->bt_pinned != NULL) {
       mpool_put(t->bt_mp, t->bt_pinned, 0);
       t->bt_pinned = NULL;
    }
    /*
     * If using fixed-length records, and the record is long, return
     * EINVAL.  If it's short, pad it out.  Use the record data return
     * memory, it's only short-term.
     */
    if (F_ISSET(t, R_FIXLEN) && data->size != t->bt_reclen) {
       if (data->size > t->bt_reclen)
          goto einval;
       if (t->bt_rdata.size < t->bt_reclen) {
          t->bt_rdata.data = t->bt_rdata.data == NULL ?
              malloc(t->bt_reclen) :
              realloc(t->bt_rdata.data, t->bt_reclen);
          if (t->bt_rdata.data == NULL)
             return (RET_ERROR);
          t->bt_rdata.size = t->bt_reclen;
       }
       memmove(t->bt_rdata.data, data->data, data->size);
       memset((char *)t->bt_rdata.data + data->size,
           t->bt_bval, t->bt_reclen - data->size);
       fdata.data = t->bt_rdata.data;
       fdata.size = t->bt_reclen;
    } else {
       fdata.data = data->data;
       fdata.size = data->size;
    }
    switch (flags) {
    case R_CURSOR:
       if (!F_ISSET(&t->bt_cursor, CURS_INIT))
          goto einval;
       nrec = t->bt_cursor.rcursor;
       break;
    case R_SETCURSOR:
       if ((nrec = *(recno_t *)key->data) == 0)
          goto einval;
       break;
    case R_IAFTER:
       if ((nrec = *(recno_t *)key->data) == 0) {
          nrec = 1;
          flags = R_IBEFORE;
       }
       break;
    case 0:
    case R_IBEFORE:
       if ((nrec = *(recno_t *)key->data) == 0)
          goto einval;
       break;
    case R_NOOVERWRITE:
       if ((nrec = *(recno_t *)key->data) == 0)
          goto einval;
       if (nrec <= t->bt_nrecs)
          return (RET_SPECIAL);
       break;
    default:
 einval:     errno = EINVAL;
       return (RET_ERROR);
    }
    /*
     * Make sure that records up to and including the put record are
     * already in the database.  If skipping records, create empty ones.
     */
    if (nrec > t->bt_nrecs) {
       if (!F_ISSET(t, R_EOF | R_INMEM) &&
           t->bt_irec(t, nrec) == RET_ERROR)
          return (RET_ERROR);
       if (nrec > t->bt_nrecs + 1) {
          if (F_ISSET(t, R_FIXLEN)) {
             if ((tdata.data =
                 (void *)malloc(t->bt_reclen)) == NULL)
                return (RET_ERROR);
             tdata.size = t->bt_reclen;
             memset(tdata.data, t->bt_bval, tdata.size);
          } else {
             tdata.data = NULL;
             tdata.size = 0;
          }
          while (nrec > t->bt_nrecs + 1)
             if (__rec_iput(t,
                 t->bt_nrecs, &tdata, 0) != RET_SUCCESS)
                return (RET_ERROR);
          if (F_ISSET(t, R_FIXLEN))
             free(tdata.data);
       }
    }
    if ((status = __rec_iput(t, nrec - 1, &fdata, flags)) != RET_SUCCESS)
       return (status);
    if (flags == R_SETCURSOR)
       t->bt_cursor.rcursor = nrec;
    F_SET(t, R_MODIFIED);
    return (__rec_ret(t, NULL, nrec, key, NULL));
 }