Asterisk - The Open Source Telephony Project: res_format_attr_celt.c File Reference
res_format_attr_celt.c File Reference
CELT format attribute interface.
#include "asterisk.h"
#include <ctype.h>
#include "asterisk/module.h"
#include "asterisk/format.h"
#include "asterisk/astobj2.h"
#include "asterisk/logger.h"
#include "asterisk/strings.h"
#include "asterisk/utils.h"
Data Structures
struct celt_attr
CELT attribute structure.
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int celt_clone (const struct ast_format *src, struct ast_format *dst)
static enum ast_format_cmp_res celt_cmp (const struct ast_format *format1, const struct ast_format *format2)
static void celt_destroy (struct ast_format *format)
static void celt_generate_sdp_fmtp (const struct ast_format *format, unsigned int payload, struct ast_str **str)
static struct ast_format * celt_getjoint (const struct ast_format *format1, const struct ast_format *format2)
static struct ast_format * celt_parse_sdp_fmtp (const struct ast_format *format, const char *attributes)
static struct ast_format * celt_set (const struct ast_format *format, const char *name, const char *value)
static int load_module (void)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "CELT Format Attribute Module" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_CHANNEL_DEPEND, }
static const struct ast_module_info * ast_module_info = &__mod_info
static struct ast_format_interface celt_interface
Detailed Description
CELT format attribute interface.
Author
David Vossel dvoss.nosp@m.el@d.nosp@m.igium.nosp@m..com
Definition in file res_format_attr_celt.c.
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 216 of file res_format_attr_celt.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 216 of file res_format_attr_celt.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 216 of file res_format_attr_celt.c.
celt_clone()
static int celt_clone (const struct ast_format * src, struct ast_format * dst) static
Definition at line 59 of file res_format_attr_celt.c.
References ast_calloc, ast_format_get_attribute_data(), and ast_format_set_attribute_data().
 {
    struct celt_attr *original = ast_format_get_attribute_data(src);
    struct celt_attr *attr = ast_calloc(1, sizeof(*attr));
    if (!attr) {
       return -1;
    }
    if (original) {
       *attr = *original;
    }
    ast_format_set_attribute_data(dst, attr);
    return 0;
 }
celt_cmp()
static enum ast_format_cmp_res celt_cmp (const struct ast_format * format1, const struct ast_format * format2) static
Definition at line 113 of file res_format_attr_celt.c.
References AST_FORMAT_CMP_EQUAL, AST_FORMAT_CMP_NOT_EQUAL, ast_format_get_attribute_data(), and celt_attr::samplerate.
 {
    struct celt_attr *attr1 = ast_format_get_attribute_data(format1);
    struct celt_attr *attr2 = ast_format_get_attribute_data(format2);
    if (((!attr1 || !attr1->samplerate) && (!attr2 || !attr2->samplerate)) ||
       (attr1->samplerate == attr2->samplerate)) {
       return AST_FORMAT_CMP_EQUAL;
    }
    return AST_FORMAT_CMP_NOT_EQUAL;
 }
celt_destroy()
static void celt_destroy (struct ast_format * format) static
Definition at line 52 of file res_format_attr_celt.c.
References ast_format_get_attribute_data(), and ast_free.
 {
    struct celt_attr *attr = ast_format_get_attribute_data(format);
    ast_free(attr);
 }
celt_generate_sdp_fmtp()
static void celt_generate_sdp_fmtp (const struct ast_format * format, unsigned int payload, struct ast_str ** str) static
Definition at line 102 of file res_format_attr_celt.c.
References ast_format_get_attribute_data(), ast_str_append(), and celt_attr::framesize.
 {
    struct celt_attr *attr = ast_format_get_attribute_data(format);
    if (!attr || !attr->framesize) {
       return;
    }
    ast_str_append(str, 0, "a=fmtp:%u framesize=%u\r\n", payload, attr->framesize);
 }
celt_getjoint()
static struct ast_format* celt_getjoint (const struct ast_format * format1, const struct ast_format * format2) static
Definition at line 126 of file res_format_attr_celt.c.
References ast_format_clone(), ast_format_get_attribute_data(), celt_attr::framesize, celt_attr::maxbitrate, MIN, NULL, and celt_attr::samplerate.
 {
    struct celt_attr *attr1 = ast_format_get_attribute_data(format1);
    struct celt_attr *attr2 = ast_format_get_attribute_data(format2);
    struct ast_format *jointformat;
    struct celt_attr *jointattr;
    if (attr1 && attr2 && (attr1->samplerate != attr2->samplerate)) {
       return NULL;
    }
    jointformat = ast_format_clone(format1);
    if (!jointformat) {
       return NULL;
    }
    jointattr = ast_format_get_attribute_data(jointformat);
    /* either would work, they are guaranteed the same at this point. */
    jointattr->samplerate = attr1->samplerate;
    /* Take the lowest max bitrate */
    jointattr->maxbitrate = MIN(attr1->maxbitrate, attr2->maxbitrate);
    jointattr->framesize = attr2->framesize; /* TODO figure out what joint framesize means */
    return jointformat;
 }
celt_parse_sdp_fmtp()
static struct ast_format* celt_parse_sdp_fmtp (const struct ast_format * format, const char * attributes) static
Definition at line 77 of file res_format_attr_celt.c.
References ast_format_clone(), ast_format_get_attribute_data(), ast_strdupa, celt_attr::framesize, and NULL.
 {
    char *attribs = ast_strdupa(attributes), *attrib;
    struct ast_format *cloned;
    struct celt_attr *attr;
    unsigned int val;
    cloned = ast_format_clone(format);
    if (!cloned) {
       return NULL;
    }
    attr = ast_format_get_attribute_data(cloned);
    /* lower-case everything, so we are case-insensitive */
    for (attrib = attribs; *attrib; ++attrib) {
       *attrib = tolower(*attrib);
    } /* based on channels/chan_sip.c:process_a_sdp_image() */
    if (sscanf(attribs, "framesize=%30u", &val) == 1) {
       attr->framesize = val;
    }
    return cloned;
 }
celt_set()
static struct ast_format* celt_set (const struct ast_format * format, const char * name, const char * value) static
Definition at line 153 of file res_format_attr_celt.c.
References ao2_ref, ast_format_clone(), ast_format_get_attribute_data(), ast_log, celt_attr::framesize, LOG_WARNING, celt_attr::maxbitrate, NULL, and celt_attr::samplerate.
 {
    struct ast_format *cloned;
    struct celt_attr *attr;
    unsigned int val;
    cloned = ast_format_clone(format);
    if (!cloned) {
       return NULL;
    }
    attr = ast_format_get_attribute_data(cloned);
    if (sscanf(value, "%30u", &val) != 1) {
       ast_log(LOG_WARNING, "Unknown value '%s' for attribute type '%s'\n",
          value, name);
       ao2_ref(cloned, -1);
       return NULL;
    }
    if (!strcasecmp(name, "sample_rate")) {
       attr->samplerate = val;
    } else if (!strcasecmp(name, "max_bitrate")) {
       attr->maxbitrate = val;
    } else if (!strcasecmp(name, "frame_size")) {
       attr->framesize = val;
    } else {
       ast_log(LOG_WARNING, "Unknown attribute type '%s'\n", name);
       ao2_ref(cloned, -1);
       return NULL;
    }
    return cloned;
 }
load_module()
static int load_module (void) static
Definition at line 197 of file res_format_attr_celt.c.
References ast_format_interface_register, AST_MODULE_LOAD_DECLINE, and AST_MODULE_LOAD_SUCCESS.
Referenced by unload_module().
 {
    if (ast_format_interface_register("celt", &celt_interface)) {
       return AST_MODULE_LOAD_DECLINE;
    }
    return AST_MODULE_LOAD_SUCCESS;
 }
unload_module()
static int unload_module (void) static
Definition at line 206 of file res_format_attr_celt.c.
References AST_MODFLAG_LOAD_ORDER, AST_MODPRI_CHANNEL_DEPEND, AST_MODULE_INFO(), AST_MODULE_SUPPORT_CORE, ASTERISK_GPL_KEY, and load_module().
 {
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "CELT Format Attribute Module" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_CHANNEL_DEPEND, } static
Definition at line 216 of file res_format_attr_celt.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 216 of file res_format_attr_celt.c.
celt_interface
struct ast_format_interface celt_interface static
Definition at line 187 of file res_format_attr_celt.c.