Asterisk - The Open Source Telephony Project: app_morsecode.c File Reference
app_morsecode.c File Reference
Dial plan applications
Morsecode application.
#include "asterisk.h"
#include "asterisk/file.h"
#include "asterisk/channel.h"
#include "asterisk/pbx.h"
#include "asterisk/module.h"
#include "asterisk/indications.h"
Functions
AST_MODULE_INFO_STANDARD_EXTENDED (ASTERISK_GPL_KEY, "Morse code")
static int load_module (void)
static int morsecode_exec (struct ast_channel *chan, const char *data)
static int playtone (struct ast_channel *chan, int tone, int len)
static int unload_module (void)
Variables
static const char *const americanmorsecode []
static const char app_morsecode [] = "Morsecode"
static const char *const internationalcode []
Detailed Description
Morsecode application.
Author
Tilghman Lesher app_m.nosp@m.orse.nosp@m.code_.nosp@m._v00.nosp@m.1@the.nosp@m.-til.nosp@m.ghman.nosp@m..com
Naveen Albert aster.nosp@m.isk@.nosp@m.phrea.nosp@m.knet.nosp@m..org
Definition in file app_morsecode.c.
Function Documentation
AST_MODULE_INFO_STANDARD_EXTENDED()
AST_MODULE_INFO_STANDARD_EXTENDED (ASTERISK_GPL_KEY , "Morse code")
Referenced by load_module().
load_module()
static int load_module (void) static
Definition at line 295 of file app_morsecode.c.
References app_morsecode, AST_MODULE_INFO_STANDARD_EXTENDED(), ast_register_application_xml, ASTERISK_GPL_KEY, and morsecode_exec().
 {
    return ast_register_application_xml(app_morsecode, morsecode_exec);
 }
morsecode_exec()
static int morsecode_exec (struct ast_channel * chan, const char * data) static
Definition at line 181 of file app_morsecode.c.
References americanmorsecode, ast_channel_lock, ast_channel_unlock, ast_log, ast_strlen_zero, digit, internationalcode, LOG_WARNING, pbx_builtin_getvar_helper(), and playtone().
Referenced by load_module().
 {
    int res = 0, ditlen, tone, toneoff, digit2;
    const char *digit;
    const char *ditlenc, *tonec, *toneb, *codetype;
    if (ast_strlen_zero(data)) {
       ast_log(LOG_WARNING, "Syntax: Morsecode(<string>) - no argument found\n");
       return 0;
    }
    /* Use variable MORESEDITLEN, if set (else 80) */
    ast_channel_lock(chan);
    ditlenc = pbx_builtin_getvar_helper(chan, "MORSEDITLEN");
    if (ast_strlen_zero(ditlenc) || (sscanf(ditlenc, "%30d", &ditlen) != 1)) {
       ditlen = 80;
    }
    ast_channel_unlock(chan);
    /* Use variable MORSETONE, if set (else 800) */
    ast_channel_lock(chan);
    tonec = pbx_builtin_getvar_helper(chan, "MORSETONE");
    if (ast_strlen_zero(tonec) || (sscanf(tonec, "%30d", &tone) != 1)) {
       tone = 800;
    }
    ast_channel_unlock(chan);
    /* Use variable MORSEOFF, if set (else 0) */
    ast_channel_lock(chan);
    toneb = pbx_builtin_getvar_helper(chan, "MORSEOFF");
    if (ast_strlen_zero(toneb) || (sscanf(toneb, "%30d", &toneoff) != 1)) {
       toneoff = 0;
    }
    ast_channel_unlock(chan);
    /* Use variable MORSETYPE, if set (else INTERNATIONAL) */
    ast_channel_lock(chan);
    codetype = pbx_builtin_getvar_helper(chan, "MORSETYPE");
    if (!codetype || strcmp(codetype, "AMERICAN")) {
       codetype = "INTERNATIONAL";
    }
    ast_channel_unlock(chan);
    if (!strcmp(codetype, "AMERICAN")) {
       for (digit = data; *digit; digit++) {
          const char *dahdit;
          digit2 = *digit;
          if (digit2 < 0 || digit2 > 127) {
             continue;
          }
          for (dahdit = americanmorsecode[digit2]; *dahdit; dahdit++) {
             if (*dahdit == '-') {
                res = playtone(chan, tone, 3 * ditlen);
             } else if (*dahdit == '.') {
                res = playtone(chan, tone, 1 * ditlen);
             } else if (*dahdit == 'L') {
                res = playtone(chan, tone, 6 * ditlen); /* long dash */
             } else if (*dahdit == '0') {
                res = playtone(chan, tone, 9 * ditlen); /* extra long dash */
             } else if (*dahdit == ' ') { /* space char (x20) = 6 dot lengths */
                /* Intra-char pauses, specific to American Morse */
                res = playtone(chan, toneoff, 3 * ditlen);
             } else {
                /* Account for ditlen of silence immediately following */
                res = playtone(chan, toneoff, 2 * ditlen);
             }
             /* Pause slightly between each dit and dah */
             res = playtone(chan, toneoff, 1 * ditlen);
             if (res)
                break;
          }
          /* Pause between characters */
          res = playtone(chan, toneoff, 3 * ditlen);
          if (res)
             break;
       }
    } else { /* International */
       for (digit = data; *digit; digit++) {
          const char *dahdit;
          digit2 = *digit;
          if (digit2 < 0 || digit2 > 127) {
             continue;
          }
          for (dahdit = internationalcode[digit2]; *dahdit; dahdit++) {
             if (*dahdit == '-') {
                res = playtone(chan, tone, 3 * ditlen);
             } else if (*dahdit == '.') {
                res = playtone(chan, tone, 1 * ditlen);
             } else {
                /* Account for ditlen of silence immediately following */
                res = playtone(chan, toneoff, 2 * ditlen);
             }
             /* Pause slightly between each dit and dah */
             res = playtone(chan, toneoff, 1 * ditlen);
             if (res)
                break;
          }
          /* Pause between characters */
          res = playtone(chan, toneoff, 2 * ditlen);
          if (res)
             break;
       }
    }
    return res;
 }
playtone()
static int playtone (struct ast_channel * chan, int tone, int len) static
Definition at line 170 of file app_morsecode.c.
References ast_playtones_start(), ast_playtones_stop(), and ast_safe_sleep().
Referenced by action_bridge(), and morsecode_exec().
 {
    int res;
    char dtmf[20];
    snprintf(dtmf, sizeof(dtmf), "%d/%d", tone, len);
    ast_playtones_start(chan, 0, dtmf, 0);
    res = ast_safe_sleep(chan, len);
    ast_playtones_stop(chan);
    return res;
 }
unload_module()
static int unload_module (void) static
Definition at line 290 of file app_morsecode.c.
References app_morsecode, and ast_unregister_application().
 {
    return ast_unregister_application(app_morsecode);
 }
Variable Documentation
americanmorsecode
const char* const americanmorsecode[] static
Definition at line 126 of file app_morsecode.c.
Referenced by morsecode_exec().
app_morsecode
const char app_morsecode[] = "Morsecode" static
Definition at line 80 of file app_morsecode.c.
Referenced by load_module(), and unload_module().
internationalcode
const char* const internationalcode[] static
Definition at line 82 of file app_morsecode.c.
Referenced by morsecode_exec().