Asterisk - The Open Source Telephony Project: app_celgenuserevent.c File Reference
app_celgenuserevent.c File Reference
Dial plan applications
Generate User-Defined CEL event.
#include "asterisk.h"
#include "asterisk/module.h"
#include "asterisk/app.h"
#include "asterisk/channel.h"
#include "asterisk/cel.h"
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int celgenuserevent_exec (struct ast_channel *chan, const char *data)
static int load_module (void)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_DEFAULT , .description = "Generate an User-Defined CEL event" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .requires = "cel", }
static char * app = "CELGenUserEvent"
static const struct ast_module_info * ast_module_info = &__mod_info
Detailed Description
Generate User-Defined CEL event.
Author
Steve Murphy
Definition in file app_celgenuserevent.c.
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 107 of file app_celgenuserevent.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 107 of file app_celgenuserevent.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 107 of file app_celgenuserevent.c.
celgenuserevent_exec()
static int celgenuserevent_exec (struct ast_channel * chan, const char * data) static
Definition at line 59 of file app_celgenuserevent.c.
References args, AST_APP_ARG, ast_cel_publish_event(), AST_CEL_USER_DEFINED, AST_DECLARE_APP_ARGS, ast_json_pack(), ast_json_unref(), AST_STANDARD_APP_ARGS, ast_strdupa, ast_strlen_zero, NULL, parse(), RAII_VAR, and S_OR.
Referenced by load_module().
 {
    int res = 0;
    char *parse;
    RAII_VAR(struct ast_json *, blob, NULL, ast_json_unref);
    AST_DECLARE_APP_ARGS(args,
       AST_APP_ARG(event);
       AST_APP_ARG(extra);
    );
    if (ast_strlen_zero(data)) {
       return 0;
    }
    parse = ast_strdupa(data);
    AST_STANDARD_APP_ARGS(args, parse);
    blob = ast_json_pack("{s: s, s: {s: s}}",
       "event", args.event,
       "extra", "extra", S_OR(args.extra, ""));
    if (!blob) {
       return res;
    }
    ast_cel_publish_event(chan, AST_CEL_USER_DEFINED, blob);
    return res;
 }
load_module()
static int load_module (void) static
Definition at line 92 of file app_celgenuserevent.c.
References app, AST_MODFLAG_DEFAULT, AST_MODULE_INFO(), AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, AST_MODULE_SUPPORT_CORE, ast_register_application_xml, ASTERISK_GPL_KEY, celgenuserevent_exec(), and unload_module().
 {
    int res = ast_register_application_xml(app, celgenuserevent_exec);
    if (res) {
       return AST_MODULE_LOAD_DECLINE;
    } else {
       return AST_MODULE_LOAD_SUCCESS;
    }
 }
unload_module()
static int unload_module (void) static
Definition at line 86 of file app_celgenuserevent.c.
References app, and ast_unregister_application().
Referenced by load_module().
 {
    ast_unregister_application(app);
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_DEFAULT , .description = "Generate an User-Defined CEL event" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .requires = "cel", } static
Definition at line 107 of file app_celgenuserevent.c.
app
char* app = "CELGenUserEvent" static
Definition at line 57 of file app_celgenuserevent.c.
Referenced by load_module(), and unload_module().
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 107 of file app_celgenuserevent.c.