Asterisk - The Open Source Telephony Project: func_holdintercept.c File Reference
func_holdintercept.c File Reference
Module: Dial plan functions
Function that intercepts HOLD frames from channels and raises events.
#include "asterisk.h"
#include "asterisk/module.h"
#include "asterisk/channel.h"
#include "asterisk/pbx.h"
#include "asterisk/app.h"
#include "asterisk/frame.h"
#include "asterisk/stasis.h"
#include "asterisk/stasis_channels.h"
Data Structures
struct hold_intercept_data
Private data structure used with the function's datastore.
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int hold_intercept_fn_write (struct ast_channel *chan, const char *function, char *data, const char *value)
static struct ast_frame * hold_intercept_framehook (struct ast_channel *chan, struct ast_frame *f, enum ast_framehook_event event, void *data)
Frame hook that is called to intercept hold/unhold.
static int hold_intercept_framehook_consume (void *data, enum ast_frame_type type)
Callback function which informs upstream if we are consuming a frame of a specific type.
static int load_module (void)
static int remove_hold_intercept (struct ast_channel *chan)
static int set_hold_intercept (struct ast_channel *chan)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Hold interception dialplan function" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, }
static const struct ast_module_info * ast_module_info = &__mod_info
static const struct ast_datastore_info hold_intercept_datastore
The channel datastore the function uses to store state.
static struct ast_custom_function hold_intercept_function
Definition of the HOLD_INTERCEPT function.
Detailed Description
Function that intercepts HOLD frames from channels and raises events.
Author
Matt Jordan mjord.nosp@m.an@d.nosp@m.igium.nosp@m..com
Definition in file func_holdintercept.c.
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 234 of file func_holdintercept.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 234 of file func_holdintercept.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 234 of file func_holdintercept.c.
hold_intercept_fn_write()
static int hold_intercept_fn_write (struct ast_channel * chan, const char * function, char * data, const char * value) static
Definition at line 190 of file func_holdintercept.c.
References ast_log, AST_LOG_WARNING, ast_strlen_zero, remove_hold_intercept(), and set_hold_intercept().
 {
    int res;
    if (!chan) {
       return -1;
    }
    if (ast_strlen_zero(data)) {
       ast_log(AST_LOG_WARNING, "HOLD_INTERCEPT requires an argument\n");
       return -1;
    }
    if (!strcasecmp(data, "set")) {
       res = set_hold_intercept(chan);
    } else if (!strcasecmp(data, "remove")) {
       res = remove_hold_intercept(chan);
    } else {
       ast_log(AST_LOG_WARNING, "HOLD_INTERCEPT: unknown option %s\n", data);
       res = -1;
    }
    return res;
 }
hold_intercept_framehook()
static struct ast_frame* hold_intercept_framehook (struct ast_channel * chan, struct ast_frame * f, enum ast_framehook_event event, void * data) static
Frame hook that is called to intercept hold/unhold.
Definition at line 108 of file func_holdintercept.c.
References ast_channel_hold_type(), ast_channel_publish_cached_blob(), ast_channel_unhold_type(), AST_CONTROL_HOLD, AST_CONTROL_UNHOLD, AST_FRAME_CONTROL, AST_FRAMEHOOK_EVENT_WRITE, ast_frfree, ast_null_frame, ast_frame::frametype, ast_frame_subclass::integer, NULL, and ast_frame::subclass.
Referenced by set_hold_intercept().
 {
    int frame_type;
    if (!f || (event != AST_FRAMEHOOK_EVENT_WRITE)) {
       return f;
    }
    if (f->frametype != AST_FRAME_CONTROL) {
       return f;
    }
    frame_type = f->subclass.integer;
    if (frame_type != AST_CONTROL_HOLD && frame_type != AST_CONTROL_UNHOLD) {
       return f;
    }
    /* Munch munch */
    ast_frfree(f);
    f = &ast_null_frame;
    ast_channel_publish_cached_blob(chan,
       frame_type == AST_CONTROL_HOLD ? ast_channel_hold_type() : ast_channel_unhold_type(),
       NULL);
    return f;
 }
hold_intercept_framehook_consume()
static int hold_intercept_framehook_consume (void * data, enum ast_frame_type type) static
Callback function which informs upstream if we are consuming a frame of a specific type.
Definition at line 138 of file func_holdintercept.c.
References AST_FRAME_CONTROL.
Referenced by set_hold_intercept().
 {
    return (type == AST_FRAME_CONTROL ? 1 : 0);
 }
load_module()
static int load_module (void) static
Definition at line 229 of file func_holdintercept.c.
References ast_custom_function_register, AST_MODULE_LOAD_DECLINE, and AST_MODULE_LOAD_SUCCESS.
 {
    return ast_custom_function_register(&hold_intercept_function) ? AST_MODULE_LOAD_DECLINE : AST_MODULE_LOAD_SUCCESS;
 }
remove_hold_intercept()
static int remove_hold_intercept (struct ast_channel * chan) static
Definition at line 77 of file func_holdintercept.c.
References ast_channel_datastore_find(), ast_channel_datastore_remove(), ast_channel_name(), ast_datastore_free(), ast_framehook_detach(), ast_log, AST_LOG_WARNING, ast_datastore::data, hold_intercept_data::framehook_id, NULL, and SCOPED_CHANNELLOCK.
Referenced by hold_intercept_fn_write().
 {
    struct ast_datastore *datastore = NULL;
    struct hold_intercept_data *data;
    SCOPED_CHANNELLOCK(chan_lock, chan);
    datastore = ast_channel_datastore_find(chan, &hold_intercept_datastore, NULL);
    if (!datastore) {
       ast_log(AST_LOG_WARNING, "Cannot remove HOLD_INTERCEPT from %s: HOLD_INTERCEPT not currently enabled\n",
               ast_channel_name(chan));
       return -1;
    }
    data = datastore->data;
    if (ast_framehook_detach(chan, data->framehook_id)) {
       ast_log(AST_LOG_WARNING, "Failed to remove HOLD_INTERCEPT framehook from channel %s\n",
               ast_channel_name(chan));
       return -1;
    }
    if (ast_channel_datastore_remove(chan, datastore)) {
       ast_log(AST_LOG_WARNING, "Failed to remove HOLD_INTERCEPT datastore from channel %s\n",
               ast_channel_name(chan));
       return -1;
    }
    ast_datastore_free(datastore);
    return 0;
 }
set_hold_intercept()
static int set_hold_intercept (struct ast_channel * chan) static
Definition at line 144 of file func_holdintercept.c.
References ast_calloc, ast_channel_datastore_add(), ast_channel_datastore_find(), ast_channel_name(), ast_datastore_alloc, ast_datastore_free(), ast_framehook_attach(), AST_FRAMEHOOK_INTERFACE_VERSION, ast_free, ast_log, AST_LOG_WARNING, ast_datastore::data, ast_framehook_interface::data, hold_intercept_data::framehook_id, hold_intercept_framehook(), hold_intercept_framehook_consume(), NULL, SCOPED_CHANNELLOCK, and ast_framehook_interface::version.
Referenced by hold_intercept_fn_write().
 {
    struct ast_datastore *datastore;
    struct hold_intercept_data *data;
    static struct ast_framehook_interface hold_framehook_interface = {
       .version = AST_FRAMEHOOK_INTERFACE_VERSION,
       .event_cb = hold_intercept_framehook,
       .consume_cb = hold_intercept_framehook_consume,
       .disable_inheritance = 1,
    };
    SCOPED_CHANNELLOCK(chan_lock, chan);
    datastore = ast_channel_datastore_find(chan, &hold_intercept_datastore, NULL);
    if (datastore) {
       ast_log(AST_LOG_WARNING, "HOLD_INTERCEPT already set on '%s'\n",
               ast_channel_name(chan));
       return 0;
    }
    datastore = ast_datastore_alloc(&hold_intercept_datastore, NULL);
    if (!datastore) {
       return -1;
    }
    data = ast_calloc(1, sizeof(*data));
    if (!data) {
       ast_datastore_free(datastore);
       return -1;
    }
    data->framehook_id = ast_framehook_attach(chan, &hold_framehook_interface);
    if (data->framehook_id < 0) {
       ast_log(AST_LOG_WARNING, "Failed to attach HOLD_INTERCEPT framehook to '%s'\n",
               ast_channel_name(chan));
       ast_datastore_free(datastore);
       ast_free(data);
       return -1;
    }
    datastore->data = data;
    ast_channel_datastore_add(chan, datastore);
    return 0;
 }
unload_module()
static int unload_module (void) static
Definition at line 223 of file func_holdintercept.c.
References ast_custom_function_unregister().
 {
    return ast_custom_function_unregister(&hold_intercept_function);
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Hold interception dialplan function" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, } static
Definition at line 234 of file func_holdintercept.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 234 of file func_holdintercept.c.
hold_intercept_datastore
const struct ast_datastore_info hold_intercept_datastore static
Initial value:
= {
   .type = "hold_intercept",
}
The channel datastore the function uses to store state.
Definition at line 72 of file func_holdintercept.c.
hold_intercept_function
struct ast_custom_function hold_intercept_function static
Initial value:
= {
   .name = "HOLD_INTERCEPT",
   .write = hold_intercept_fn_write,
}
Definition of the HOLD_INTERCEPT function.
Definition at line 217 of file func_holdintercept.c.