Asterisk - The Open Source Telephony Project: app_ices.c File Reference
app_ices.c File Reference
Dial plan applications
Stream to an icecast server via ICES (see contrib/asterisk-ices.xml)
#include "asterisk.h"
#include <signal.h>
#include <fcntl.h>
#include <sys/time.h>
#include "asterisk/paths.h"
#include "asterisk/lock.h"
#include "asterisk/file.h"
#include "asterisk/channel.h"
#include "asterisk/frame.h"
#include "asterisk/pbx.h"
#include "asterisk/module.h"
#include "asterisk/translate.h"
#include "asterisk/app.h"
#include "asterisk/format_cache.h"
Macros
#define path_BIN "/usr/bin/"
#define path_LOCAL "/usr/local/bin/"
Functions
AST_MODULE_INFO_STANDARD_DEPRECATED (ASTERISK_GPL_KEY, "Encode and Stream via icecast and ices")
static int ices_exec (struct ast_channel *chan, const char *data)
static int icesencode (char *filename, int fd)
static int load_module (void)
static int unload_module (void)
Variables
static char * app = "ICES"
Detailed Description
Stream to an icecast server via ICES (see contrib/asterisk-ices.xml)
Author
Mark Spencer marks.nosp@m.ter@.nosp@m.digiu.nosp@m.m.co.nosp@m.m
ICES - http://www.icecast.org/ices.php
Definition in file app_ices.c.
Macro Definition Documentation
path_BIN
#define path_BIN "/usr/bin/"
Definition at line 70 of file app_ices.c.
Referenced by icesencode().
path_LOCAL
#define path_LOCAL "/usr/local/bin/"
Definition at line 71 of file app_ices.c.
Referenced by icesencode().
Function Documentation
AST_MODULE_INFO_STANDARD_DEPRECATED()
AST_MODULE_INFO_STANDARD_DEPRECATED (ASTERISK_GPL_KEY , "Encode and Stream via icecast and ices")
Referenced by load_module().
ices_exec()
static int ices_exec (struct ast_channel * chan, const char * data) static
Definition at line 110 of file app_ices.c.
References ao2_bump, ao2_cleanup, ast_answer(), ast_channel_readformat(), ast_config_AST_CONFIG_DIR, ast_copy_string(), ast_debug, ast_fd_set_flags, ast_format_slin, AST_FRAME_VOICE, ast_frfree, ast_log, ast_read(), ast_set_read_format(), AST_STATE_UP, ast_stopstream(), ast_strlen_zero, ast_waitfor(), c, ast_frame::data, ast_frame::datalen, errno, ast_frame::frametype, icesencode(), LOG_WARNING, and ast_frame::ptr.
Referenced by load_module().
 {
    int res = 0;
    int fds[2];
    int ms = -1;
    int pid = -1;
    struct ast_format *oreadformat;
    struct ast_frame *f;
    char filename[256]="";
    char *c;
    if (ast_strlen_zero(data)) {
       ast_log(LOG_WARNING, "ICES requires an argument (configfile.xml)\n");
       return -1;
    }
    if (pipe(fds)) {
       ast_log(LOG_WARNING, "Unable to create pipe\n");
       return -1;
    }
    ast_fd_set_flags(fds[1], O_NONBLOCK);
    ast_stopstream(chan);
    if (ast_channel_state(chan) != AST_STATE_UP)
       res = ast_answer(chan);
    if (res) {
       close(fds[0]);
       close(fds[1]);
       ast_log(LOG_WARNING, "Answer failed!\n");
       return -1;
    }
    oreadformat = ao2_bump(ast_channel_readformat(chan));
    res = ast_set_read_format(chan, ast_format_slin);
    if (res < 0) {
       close(fds[0]);
       close(fds[1]);
       ast_log(LOG_WARNING, "Unable to set write format to signed linear\n");
       ao2_cleanup(oreadformat);
       return -1;
    }
    if (((char *)data)[0] == '/')
       ast_copy_string(filename, (char *) data, sizeof(filename));
    else
       snprintf(filename, sizeof(filename), "%s/%s", ast_config_AST_CONFIG_DIR, (char *)data);
    /* Placeholder for options */
    c = strchr(filename, '|');
    if (c)
       *c = '\0';
    res = icesencode(filename, fds[0]);
    if (res >= 0) {
       pid = res;
       for (;;) {
          /* Wait for audio, and stream */
          ms = ast_waitfor(chan, -1);
          if (ms < 0) {
             ast_debug(1, "Hangup detected\n");
             res = -1;
             break;
          }
          f = ast_read(chan);
          if (!f) {
             ast_debug(1, "Null frame == hangup() detected\n");
             res = -1;
             break;
          }
          if (f->frametype == AST_FRAME_VOICE) {
             res = write(fds[1], f->data.ptr, f->datalen);
             if (res < 0) {
                if (errno != EAGAIN) {
                   ast_log(LOG_WARNING, "Write failed to pipe: %s\n", strerror(errno));
                   res = -1;
                   ast_frfree(f);
                   break;
                }
             }
          }
          ast_frfree(f);
       }
    }
    close(fds[0]);
    close(fds[1]);
    if (pid > -1)
       kill(pid, SIGKILL);
    if (!res && oreadformat)
       ast_set_read_format(chan, oreadformat);
    ao2_cleanup(oreadformat);
    return res;
 }
icesencode()
static int icesencode (char * filename, int fd) static
Definition at line 75 of file app_ices.c.
References ast_close_fds_above_n(), ast_debug, ast_log, ast_opt_high_priority, ast_safe_fork(), ast_set_priority(), LOG_WARNING, path_BIN, path_LOCAL, and SENTINEL.
Referenced by ices_exec().
 {
    int res;
    res = ast_safe_fork(0);
    if (res < 0)
       ast_log(LOG_WARNING, "Fork failed\n");
    if (res) {
       return res;
    }
    if (ast_opt_high_priority)
       ast_set_priority(0);
    dup2(fd, STDIN_FILENO);
    ast_close_fds_above_n(STDERR_FILENO);
    /* Most commonly installed in /usr/local/bin
     * But many places has it in /usr/bin
     * As a last-ditch effort, try to use PATH
     */
    execl(path_LOCAL "ices2", "ices", filename, SENTINEL);
    execl(path_BIN "ices2", "ices", filename, SENTINEL);
    execlp("ices2", "ices", filename, SENTINEL);
    ast_debug(1, "Couldn't find ices version 2, attempting to use ices version 1.\n");
    execl(path_LOCAL "ices", "ices", filename, SENTINEL);
    execl(path_BIN "ices", "ices", filename, SENTINEL);
    execlp("ices", "ices", filename, SENTINEL);
    ast_log(LOG_WARNING, "Execute of ices failed, could not find command.\n");
    close(fd);
    _exit(0);
 }
load_module()
static int load_module (void) static
Definition at line 209 of file app_ices.c.
References app, AST_MODULE_INFO_STANDARD_DEPRECATED(), ast_register_application_xml, ASTERISK_GPL_KEY, and ices_exec().
 {
    return ast_register_application_xml(app, ices_exec);
 }
unload_module()
static int unload_module (void) static
Definition at line 204 of file app_ices.c.
References app, and ast_unregister_application().
 {
    return ast_unregister_application(app);
 }
Variable Documentation
app
char* app = "ICES" static
Definition at line 73 of file app_ices.c.
Referenced by load_module(), and unload_module().