Asterisk - The Open Source Telephony Project: test_stasis_state.c File Reference
test_stasis_state.c File Reference
#include "asterisk.h"
#include "asterisk/astobj2.h"
#include "asterisk/conversions.h"
#include "asterisk/module.h"
#include "asterisk/stasis_state.h"
#include "asterisk/test.h"
Data Structures
struct foo_data
Macros
#define MANAGER_TOPIC "foo"
#define test_category "/stasis/core/state/"
#define TOPIC_COUNT 500
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
AST_TEST_DEFINE (implicit_publish)
AST_TEST_DEFINE (explicit_publish)
AST_VECTOR (subscriptions, struct stasis_state_subscriber *)
AST_VECTOR (publishers, struct stasis_state_publisher *)
static struct stasis_message * create_foo_type_message (const char *id)
static int explicit_publish_cb (const char *id, struct stasis_message *msg, void *user_data)
struct stasis_message_type * foo_type (void)
static void foo_type_cb (void *data, struct stasis_subscription *sub, struct stasis_message *message)
static void handle_validate (const char *id, struct stasis_state_subscriber *sub)
static int implicit_publish_cb (const char *id, struct stasis_message *msg, void *user_data)
static int load_module (void)
static int publish (struct stasis_state_manager *manager, on_stasis_state cb, void *user_data)
static int publishers_create (struct stasis_state_manager *manager, struct publishers *pubs)
static int publishers_destroy (struct stasis_state_manager *manager, struct publishers *pubs)
STASIS_MESSAGE_TYPE_DEFN (foo_type)
static int subscriptions_create (struct stasis_state_manager *manager, struct subscriptions *subs)
static int subscriptions_destroy (struct stasis_state_manager *manager, struct subscriptions *subs)
static int unload_module (void)
static int validate_data (const char *id, struct foo_data *foo)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Stasis state testing" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, }
static const struct ast_module_info * ast_module_info = &__mod_info
static int expect_null
struct stasis_state_observer foo_observer
static size_t running_total
static size_t sum_total
Macro Definition Documentation
MANAGER_TOPIC
#define MANAGER_TOPIC "foo"
Definition at line 36 of file test_stasis_state.c.
Referenced by AST_TEST_DEFINE().
test_category
#define test_category "/stasis/core/state/"
Definition at line 32 of file test_stasis_state.c.
Referenced by AST_TEST_DEFINE().
TOPIC_COUNT
#define TOPIC_COUNT 500
Definition at line 34 of file test_stasis_state.c.
Referenced by publishers_create(), publishers_destroy(), and subscriptions_create().
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 466 of file test_stasis_state.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 466 of file test_stasis_state.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 466 of file test_stasis_state.c.
AST_TEST_DEFINE() [1/2]
AST_TEST_DEFINE (implicit_publish)
Definition at line 356 of file test_stasis_state.c.
References ao2_cleanup, ao2_ref, ast_log, AST_TEST_FAIL, AST_TEST_NOT_RUN, AST_TEST_PASS, cleanup(), implicit_publish_cb(), sip_to_pjsip::info(), LOG_ERROR, MANAGER_TOPIC, NULL, publish(), publishers_destroy(), RAII_VAR, stasis_state_manager_create(), subscriptions_create(), subscriptions_destroy(), test_category, TEST_EXECUTE, and TEST_INIT.
 {
    RAII_VAR(struct stasis_state_manager *, manager, NULL, ao2_cleanup);
    struct subscriptions subs;
    int rc = AST_TEST_PASS;
    switch (cmd) {
    case TEST_INIT:
       info->name = __func__;
       info->category = test_category;
       info->summary = "Test implicit publishing of stasis state";
       info->description = info->summary;
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    manager = stasis_state_manager_create(MANAGER_TOPIC);
    ast_test_validate(test, manager != NULL);
    ast_test_validate(test, !subscriptions_create(manager, &subs));
    ast_test_validate_cleanup(test, !publish(manager, implicit_publish_cb, manager),
       rc, cleanup);
 cleanup:
    if (subscriptions_destroy(manager, &subs) || publishers_destroy(manager, NULL)) {
       return AST_TEST_FAIL;
    }
    /*
     * State subscriptions add a ref a state. The state in turn adds a ref
     * to the manager. So if more than one ref is held on the manager before
     * exiting, there is a ref leak some place.
     */
    if (ao2_ref(manager, 0) != 1) {
       ast_log(LOG_ERROR, "Memory leak - Too many references held on manager\n");
       return AST_TEST_FAIL;
    }
    return rc;
 }
AST_TEST_DEFINE() [2/2]
AST_TEST_DEFINE (explicit_publish)
Definition at line 399 of file test_stasis_state.c.
References ao2_cleanup, ao2_ref, ast_log, AST_TEST_FAIL, AST_TEST_NOT_RUN, AST_TEST_PASS, cleanup(), explicit_publish_cb(), sip_to_pjsip::info(), LOG_ERROR, MANAGER_TOPIC, NULL, publish(), publishers, publishers_create(), publishers_destroy(), RAII_VAR, stasis_state_manager_create(), subscriptions_create(), subscriptions_destroy(), test_category, TEST_EXECUTE, and TEST_INIT.
 {
    RAII_VAR(struct stasis_state_manager *, manager, NULL, ao2_cleanup);
    struct subscriptions subs;
    struct publishers pubs;
    int rc = AST_TEST_PASS;
    switch (cmd) {
    case TEST_INIT:
       info->name = __func__;
       info->category = test_category;
       info->summary = "Test explicit publishing of stasis state";
       info->description = info->summary;
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    manager = stasis_state_manager_create(MANAGER_TOPIC);
    ast_test_validate(test, manager != NULL);
    ast_test_validate(test, !subscriptions_create(manager, &subs));
    ast_test_validate_cleanup(test, !publishers_create(manager, &pubs), rc, cleanup);
    ast_test_validate_cleanup(test, !publish(manager, explicit_publish_cb, &pubs),
       rc, cleanup);
 cleanup:
    if (subscriptions_destroy(manager, &subs) || publishers_destroy(manager, &pubs)) {
       return AST_TEST_FAIL;
    }
    /*
     * State subscriptions add a ref a state. The state in turn adds a ref
     * to the manager. So if more than one ref is held on the manager before
     * exiting, there is a ref leak some place.
     */
    if (ao2_ref(manager, 0) != 1) {
       ast_log(LOG_ERROR, "Memory leak - Too many references held on manager\n");
       return AST_TEST_FAIL;
    }
    return rc;
 }
AST_VECTOR() [1/2]
AST_VECTOR (subscriptions , struct stasis_state_subscriber *)
AST_VECTOR() [2/2]
AST_VECTOR (publishers , struct stasis_state_publisher *)
create_foo_type_message()
static struct stasis_message* create_foo_type_message (const char * id) static
Definition at line 246 of file test_stasis_state.c.
References ao2_alloc, ao2_ref, ast_log, ast_str_to_umax(), foo_data::bar, foo_type(), LOG_ERROR, NULL, and stasis_message_create_full().
Referenced by explicit_publish_cb(), and implicit_publish_cb().
 {
    struct stasis_message *msg;
    struct foo_data *foo;
    foo = ao2_alloc(sizeof(*foo), NULL);
    if (!foo) {
       ast_log(LOG_ERROR, "Failed to allocate foo data for '%s'\n", id);
       return NULL;
    }
    if (ast_str_to_umax(id, &foo->bar)) {
       ast_log(LOG_ERROR, "Unable to convert the state's id '%s' to numeric\n", id);
       ao2_ref(foo, -1);
       return NULL;
    }
    msg = stasis_message_create_full(foo_type(), foo, NULL);
    if (!msg) {
       ast_log(LOG_ERROR, "Failed to create stasis message for '%s'\n", id);
    }
    ao2_ref(foo, -1);
    return msg;
 }
explicit_publish_cb()
static int explicit_publish_cb (const char * id, struct stasis_message * msg, void * user_data) static
Definition at line 293 of file test_stasis_state.c.
References ao2_ref, ast_log, AST_VECTOR_GET, AST_VECTOR_SIZE, CMP_STOP, create_foo_type_message(), LOG_ERROR, NULL, publishers, stasis_message_data(), stasis_state_publish(), stasis_state_publisher_id(), and validate_data().
Referenced by AST_TEST_DEFINE().
 {
    /* For each state object create and publish new state data */
    struct publishers *pubs = user_data;
    struct stasis_state_publisher *pub = NULL;
    struct foo_data *foo = stasis_message_data(msg);
    size_t i;
    if (validate_data(id, foo)) {
       return CMP_STOP;
    }
    msg = create_foo_type_message(id);
    if (!msg) {
       return CMP_STOP;
    }
    for (i = 0; i < AST_VECTOR_SIZE(pubs); ++i) {
       if (!strcmp(stasis_state_publisher_id(AST_VECTOR_GET(pubs, i)), id)) {
          pub = AST_VECTOR_GET(pubs, i);
          break;
       }
    }
    if (!pub) {
       ast_log(LOG_ERROR, "Unable to locate publisher for id '%s'\n", id);
       return CMP_STOP;
    }
    stasis_state_publish(pub, msg);
    ao2_ref(msg, -1);
    return 0;
 }
foo_type()
struct stasis_message_type* foo_type (void)
Referenced by create_foo_type_message(), load_module(), and unload_module().
foo_type_cb()
static void foo_type_cb (void * data, struct stasis_subscription * sub, struct stasis_message * message) static
Definition at line 108 of file test_stasis_state.c.
Referenced by subscriptions_create().
 {
    /* No op since we are not really testing stasis topic handling here */
 }
handle_validate()
static void handle_validate (const char * id, struct stasis_state_subscriber * sub) static
Definition at line 96 of file test_stasis_state.c.
References ao2_cleanup, stasis_state_subscriber_data(), and validate_data().
 {
    struct foo_data *foo = stasis_state_subscriber_data(sub);
    validate_data(id, foo);
    ao2_cleanup(foo);
 }
implicit_publish_cb()
static int implicit_publish_cb (const char * id, struct stasis_message * msg, void * user_data) static
Definition at line 272 of file test_stasis_state.c.
References ao2_ref, CMP_STOP, create_foo_type_message(), NULL, stasis_message_data(), stasis_state_publish_by_id(), and validate_data().
Referenced by AST_TEST_DEFINE().
 {
    /* For each state object create and publish new state data */
    struct foo_data *foo = stasis_message_data(msg);
    if (validate_data(id, foo)) {
       return CMP_STOP;
    }
    msg = create_foo_type_message(id);
    if (!msg) {
       return CMP_STOP;
    }
    /* Now publish it on the managed state object */
    stasis_state_publish_by_id(user_data, id, NULL, msg);
    ao2_ref(msg, -1);
    return 0;
 }
load_module()
static int load_module (void) static
Definition at line 454 of file test_stasis_state.c.
References AST_MODULE_LOAD_SUCCESS, AST_TEST_REGISTER, foo_type(), and STASIS_MESSAGE_TYPE_INIT.
 {
    if (STASIS_MESSAGE_TYPE_INIT(foo_type) != 0) {
       return -1;
    }
    AST_TEST_REGISTER(implicit_publish);
    AST_TEST_REGISTER(explicit_publish);
    return AST_MODULE_LOAD_SUCCESS;
 }
publish()
static int publish (struct stasis_state_manager * manager, on_stasis_state cb, void * user_data) static
Definition at line 328 of file test_stasis_state.c.
References ast_log, expect_null, LOG_ERROR, running_total, stasis_state_callback_all(), and sum_total.
Referenced by AST_TEST_DEFINE().
 {
    /* First time there is no state data */
    expect_null = 1;
    running_total = 0;
    stasis_state_callback_all(manager, cb, user_data);
    if (running_total != sum_total) {
       ast_log(LOG_ERROR, "Failed manager_callback (1): running=%zu, sum=%zu\n",
             running_total, sum_total);
       return -1;
    }
    /* Second time check valid state data exists */
    running_total = expect_null = 0;
    stasis_state_callback_all(manager, cb, user_data);
    if (running_total != sum_total) {
       ast_log(LOG_ERROR, "Failed manager_callback (2): running=%zu, sum=%zu\n",
             running_total, sum_total);
       return -1;
    }
    return 0;
 }
publishers_create()
static int publishers_create (struct stasis_state_manager * manager, struct publishers * pubs) static
Definition at line 205 of file test_stasis_state.c.
References ao2_ref, ast_log, AST_VECTOR_APPEND, AST_VECTOR_INIT, LOG_ERROR, publishers_destroy(), stasis_state_add_publisher(), and TOPIC_COUNT.
Referenced by AST_TEST_DEFINE().
 {
    size_t i;
    if (AST_VECTOR_INIT(pubs, TOPIC_COUNT)) {
       return -1;
    }
    for (i = 0; i < TOPIC_COUNT; ++i) {
       struct stasis_state_publisher *pub;
       char id[32];
       if (snprintf(id, 10, "%zu", i) == -1) {
          ast_log(LOG_ERROR, "Unable to convert publisher id to string\n");
          break;
       }
       /* Create the state publisher */
       pub = stasis_state_add_publisher(manager, id);
       if (!pub) {
          ast_log(LOG_ERROR, "Failed to create a state publisher for id '%s'\n", id);
          break;
       }
       if (AST_VECTOR_APPEND(pubs, pub)) {
          ast_log(LOG_ERROR, "Failed to add to publisher to vector for id '%s'\n", id);
          ao2_ref(pub, -1);
          break;
       }
    }
    if (i != TOPIC_COUNT) {
       ast_log(LOG_ERROR, "Failed to create all publishers: count=%zu\n", i);
       publishers_destroy(manager, pubs);
       return -1;
    }
    return 0;
 }
publishers_destroy()
static int publishers_destroy (struct stasis_state_manager * manager, struct publishers * pubs) static
Definition at line 179 of file test_stasis_state.c.
References ao2_cleanup, ast_log, AST_VECTOR_CALLBACK_VOID, AST_VECTOR_FREE, LOG_ERROR, NULL, stasis_state_remove_publish_by_id(), and TOPIC_COUNT.
Referenced by AST_TEST_DEFINE(), and publishers_create().
 {
    size_t i;
    if (pubs) {
       /* Remove explicit publishers */
       AST_VECTOR_CALLBACK_VOID(pubs, ao2_cleanup);
       AST_VECTOR_FREE(pubs);
       return 0;
    }
    for (i = 0; i < TOPIC_COUNT; ++i) {
       char id[32];
       /* Remove implicit publishers */
       if (snprintf(id, 10, "%zu", i) == -1) {
          ast_log(LOG_ERROR, "Unable to convert publisher id to string\n");
          return -1;
       }
       stasis_state_remove_publish_by_id(manager, id, NULL, NULL);
    }
    return 0;
 }
STASIS_MESSAGE_TYPE_DEFN()
STASIS_MESSAGE_TYPE_DEFN (foo_type)
foo stasis message type
subscriptions_create()
static int subscriptions_create (struct stasis_state_manager * manager, struct subscriptions * subs) static
Definition at line 131 of file test_stasis_state.c.
References ao2_ref, ast_log, AST_VECTOR_APPEND, AST_VECTOR_INIT, expect_null, foo_type_cb(), LOG_ERROR, NULL, running_total, stasis_state_add_observer(), stasis_state_subscribe_pool(), sub, subscriptions_destroy(), sum_total, and TOPIC_COUNT.
Referenced by AST_TEST_DEFINE().
 {
    size_t i;
    if (stasis_state_add_observer(manager, &foo_observer) ||
       AST_VECTOR_INIT(subs, TOPIC_COUNT)) {
       return -1;
    }
    sum_total = running_total = 0;
    expect_null = 1;
    for (i = 0; i < TOPIC_COUNT; ++i) {
       struct stasis_state_subscriber *sub;
       char id[32];
       if (snprintf(id, 10, "%zu", i) == -1) {
          ast_log(LOG_ERROR, "Unable to convert subscriber id to string\n");
          break;
       }
       sub = stasis_state_subscribe_pool(manager, id, foo_type_cb, NULL);
       if (!sub) {
          ast_log(LOG_ERROR, "Failed to create a state subscriber for id '%s'\n", id);
          ao2_ref(sub, -1);
          break;
       }
       if (AST_VECTOR_APPEND(subs, sub)) {
          ast_log(LOG_ERROR, "Failed to add to foo_sub to vector for id '%s'\n", id);
          ao2_ref(sub, -1);
          break;
       }
       sum_total += i;
    }
    if (i != TOPIC_COUNT || running_total != sum_total) {
       ast_log(LOG_ERROR, "Failed to create all subscriptions: running=%zu, sum=%zu\n",
             running_total, sum_total);
       subscriptions_destroy(manager, subs);
       return -1;
    }
    return 0;
 }
subscriptions_destroy()
static int subscriptions_destroy (struct stasis_state_manager * manager, struct subscriptions * subs) static
Definition at line 113 of file test_stasis_state.c.
References ast_log, AST_VECTOR_CALLBACK_VOID, AST_VECTOR_FREE, expect_null, LOG_ERROR, running_total, stasis_state_remove_observer(), stasis_state_unsubscribe_and_join(), and sum_total.
Referenced by AST_TEST_DEFINE(), and subscriptions_create().
 {
    running_total = expect_null = 0;
    AST_VECTOR_CALLBACK_VOID(subs, stasis_state_unsubscribe_and_join);
    AST_VECTOR_FREE(subs);
    stasis_state_remove_observer(manager, &foo_observer);
    if (running_total != sum_total) {
       ast_log(LOG_ERROR, "Failed to destroy all subscriptions: running=%zu, sum=%zu\n",
             running_total, sum_total);
       return -1;
    }
    return 0;
 }
unload_module()
static int unload_module (void) static
Definition at line 444 of file test_stasis_state.c.
References AST_TEST_UNREGISTER, foo_type(), and STASIS_MESSAGE_TYPE_CLEANUP.
 {
    AST_TEST_UNREGISTER(implicit_publish);
    AST_TEST_UNREGISTER(explicit_publish);
    STASIS_MESSAGE_TYPE_CLEANUP(foo_type);
    return 0;
 }
validate_data()
static int validate_data (const char * id, struct foo_data * foo) static
Definition at line 63 of file test_stasis_state.c.
References ast_log, ast_str_to_umax(), foo_data::bar, expect_null, LOG_ERROR, and running_total.
Referenced by explicit_publish_cb(), handle_validate(), and implicit_publish_cb().
 {
    size_t num;
    if (ast_str_to_umax(id, &num)) {
       ast_log(LOG_ERROR, "Unable to convert the state's id '%s' to numeric\n", id);
       return -1;
    }
    running_total += num;
    if (!foo) {
       if (expect_null) {
          return 0;
       }
       ast_log(LOG_ERROR, "Expected state data for '%s'\n", id);
       return -1;
    }
    if (expect_null) {
       ast_log(LOG_ERROR, "Expected NULL state data for '%s'\n", id);
       return -1;
    }
    if (foo->bar != num) {
       ast_log(LOG_ERROR, "Unexpected state data for '%s'\n", id);
       return -1;
    }
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Stasis state testing" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, } static
Definition at line 466 of file test_stasis_state.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 466 of file test_stasis_state.c.
expect_null
int expect_null static
This value is set to check if state data is NULL before publishing
Definition at line 61 of file test_stasis_state.c.
Referenced by publish(), subscriptions_create(), subscriptions_destroy(), and validate_data().
foo_observer
struct stasis_state_observer foo_observer
Initial value:
= {
   .on_subscribe = handle_validate,
   .on_unsubscribe = handle_validate
}
Definition at line 103 of file test_stasis_state.c.
running_total
size_t running_total static
Test variable that tracks the running total of state ids
Definition at line 58 of file test_stasis_state.c.
Referenced by publish(), subscriptions_create(), subscriptions_destroy(), and validate_data().
sum_total
size_t sum_total static
For testing purposes each subscribed state's id is a number. This value is the summation of all id's.
Definition at line 55 of file test_stasis_state.c.
Referenced by publish(), subscriptions_create(), and subscriptions_destroy().