Asterisk - The Open Source Telephony Project: app_attended_transfer.c File Reference
app_attended_transfer.c File Reference
Dial plan applications
Attended transfer by caller channel.
#include "asterisk.h"
#include "asterisk/pbx.h"
#include "asterisk/module.h"
#include "asterisk/app.h"
#include "asterisk/channel.h"
#include "asterisk/bridge.h"
#include "asterisk/features_config.h"
Functions
AST_MODULE_INFO_STANDARD_EXTENDED (ASTERISK_GPL_KEY, "Attended transfer to the given extension")
static int attended_transfer_exec (struct ast_channel *chan, const char *data)
static int load_module (void)
static int unload_module (void)
Variables
static const char *const app = "AttendedTransfer"
Detailed Description
Attended transfer by caller channel.
Author
Alexei Gradinari alex2.nosp@m.grad.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Definition in file app_attended_transfer.c.
Function Documentation
AST_MODULE_INFO_STANDARD_EXTENDED()
AST_MODULE_INFO_STANDARD_EXTENDED (ASTERISK_GPL_KEY , "Attended transfer to the given extension")
Referenced by load_module().
attended_transfer_exec()
static int attended_transfer_exec (struct ast_channel * chan, const char * data) static
Definition at line 77 of file app_attended_transfer.c.
References app, args, AST_APP_ARG, ast_channel_lock, ast_channel_unlock, AST_DECLARE_APP_ARGS, AST_FEATURE_MAX_LEN, AST_FRAME_DTMF, ast_get_builtin_feature(), ast_log, ast_queue_frame(), AST_STANDARD_APP_ARGS, ast_strdupa, ast_strlen_zero, context, digit, exten, ast_frame::frametype, ast_frame_subclass::integer, LOG_WARNING, NULL, parse(), pbx_builtin_getvar_helper(), pbx_builtin_setvar_helper(), and ast_frame::subclass.
Referenced by load_module().
 {
    char *exten = NULL;
    const char *context = NULL;
    char *parse;
    AST_DECLARE_APP_ARGS(args,
       AST_APP_ARG(exten);
    );
    char feature_code[AST_FEATURE_MAX_LEN];
    const char *digit;
    struct ast_frame f = { .frametype = AST_FRAME_DTMF };
    if (ast_strlen_zero((char *)data)) {
       ast_log(LOG_WARNING, "%s requires an argument (exten)\n", app);
       pbx_builtin_setvar_helper(chan, "ATTENDEDTRANSFERSTATUS", "FAILURE");
       return 0;
    }
    context = pbx_builtin_getvar_helper(chan, "TRANSFER_CONTEXT");
    if (ast_strlen_zero(context)) {
       pbx_builtin_setvar_helper(chan, "ATTENDEDTRANSFERSTATUS", "NOTPERMITTED");
       return 0;
    }
    ast_channel_lock(chan);
    if (ast_get_builtin_feature(chan, "atxfer", feature_code, sizeof(feature_code)) ||
       ast_strlen_zero(feature_code)) {
       pbx_builtin_setvar_helper(chan, "ATTENDEDTRANSFERSTATUS", "NOTPERMITTED");
       ast_channel_unlock(chan);
       return 0;
    }
    ast_channel_unlock(chan);
    parse = ast_strdupa(data);
    AST_STANDARD_APP_ARGS(args, parse);
    exten = args.exten;
    for (digit = feature_code; *digit; ++digit) {
       f.subclass.integer = *digit;
       ast_queue_frame(chan, &f);
    }
    for (digit = exten; *digit; ++digit) {
       f.subclass.integer = *digit;
       ast_queue_frame(chan, &f);
    }
    f.subclass.integer = '#';
    ast_queue_frame(chan, &f);
    pbx_builtin_setvar_helper(chan, "ATTENDEDTRANSFERSTATUS", "SUCCESS");
    return 0;
 }
load_module()
static int load_module (void) static
Definition at line 138 of file app_attended_transfer.c.
References app, AST_MODULE_INFO_STANDARD_EXTENDED(), ast_register_application_xml, ASTERISK_GPL_KEY, and attended_transfer_exec().
 {
    return ast_register_application_xml(app, attended_transfer_exec);
 }
unload_module()
static int unload_module (void) static
Definition at line 133 of file app_attended_transfer.c.
References app, and ast_unregister_application().
 {
    return ast_unregister_application(app);
 }
Variable Documentation
app
const char* const app = "AttendedTransfer" static
Definition at line 75 of file app_attended_transfer.c.
Referenced by attended_transfer_exec(), load_module(), and unload_module().