Asterisk - The Open Source Telephony Project: format_wav.c File Reference
format_wav.c File Reference
Module: Media File Formats
Work with WAV in the proprietary Microsoft format. Microsoft WAV format (8000hz Signed Linear)
#include "asterisk.h"
#include "asterisk/mod_format.h"
#include "asterisk/module.h"
#include "asterisk/endian.h"
#include "asterisk/format_cache.h"
#include "asterisk/format.h"
#include "asterisk/codec.h"
Data Structures
struct wav_desc
Macros
#define BLOCKSIZE 160
#define WAV_BUF_SIZE 320
#define WAV_HEADER_SIZE 44
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int check_header (FILE *f, int hz)
static int check_header_fmt (FILE *f, int hsize, int hz)
static int load_module (void)
static int unload_module (void)
static int update_header (FILE *f)
static void wav_close (struct ast_filestream *s)
static int wav_open (struct ast_filestream *s)
static struct ast_frame * wav_read (struct ast_filestream *s, int *whennext)
static int wav_rewrite (struct ast_filestream *s, const char *comment)
static int wav_seek (struct ast_filestream *fs, off_t sample_offset, int whence)
static off_t wav_tell (struct ast_filestream *fs)
static int wav_trunc (struct ast_filestream *fs)
static int wav_write (struct ast_filestream *fs, struct ast_frame *f)
static int write_header (FILE *f, int writehz)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Microsoft WAV/WAV16 format (8kHz/16kHz Signed Linear)" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_APP_DEPEND }
static const struct ast_module_info * ast_module_info = &__mod_info
static struct ast_format_def wav16_f
static struct ast_format_def wav_f
Detailed Description
Work with WAV in the proprietary Microsoft format. Microsoft WAV format (8000hz Signed Linear)
File name extension: wav (lower case)
Definition in file format_wav.c.
Macro Definition Documentation
BLOCKSIZE
#define BLOCKSIZE 160
Definition at line 56 of file format_wav.c.
WAV_BUF_SIZE
#define WAV_BUF_SIZE 320
Definition at line 44 of file format_wav.c.
Referenced by wav_read().
WAV_HEADER_SIZE
#define WAV_HEADER_SIZE 44
Definition at line 46 of file format_wav.c.
Referenced by wav_seek().
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 572 of file format_wav.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 572 of file format_wav.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 572 of file format_wav.c.
check_header()
static int check_header (FILE * f, int hz) static
Definition at line 140 of file format_wav.c.
References ast_log, buf, check_header_fmt(), LOG_DEBUG, LOG_WARNING, and type.
Referenced by wav_open().
 {
    int type, size, formtype;
    int data;
    if (fread(&type, 1, 4, f) != 4) {
       ast_log(LOG_WARNING, "Read failed (type)\n");
       return -1;
    }
    if (fread(&size, 1, 4, f) != 4) {
       ast_log(LOG_WARNING, "Read failed (size)\n");
       return -1;
    }
 #if __BYTE_ORDER == __BIG_ENDIAN
    size = ltohl(size);
 #endif
    if (fread(&formtype, 1, 4, f) != 4) {
       ast_log(LOG_WARNING, "Read failed (formtype)\n");
       return -1;
    }
    if (memcmp(&type, "RIFF", 4)) {
       ast_log(LOG_WARNING, "Does not begin with RIFF\n");
       return -1;
    }
    if (memcmp(&formtype, "WAVE", 4)) {
       ast_log(LOG_WARNING, "Does not contain WAVE\n");
       return -1;
    }
    /* Skip any facts and get the first data block */
    for(;;)
    {
       char buf[4];
       /* Begin data chunk */
       if (fread(&buf, 1, 4, f) != 4) {
          ast_log(LOG_WARNING, "Read failed (block header format)\n");
          return -1;
       }
       /* Data has the actual length of data in it */
       if (fread(&data, 1, 4, f) != 4) {
          ast_log(LOG_WARNING, "Read failed (block '%.4s' header length)\n", buf);
          return -1;
       }
 #if __BYTE_ORDER == __BIG_ENDIAN
       data = ltohl(data);
 #endif
       if (memcmp(&buf, "fmt ", 4) == 0) {
          if (check_header_fmt(f, data, hz))
             return -1;
          continue;
       }
       if(memcmp(buf, "data", 4) == 0 )
          break;
       ast_log(LOG_DEBUG, "Skipping unknown block '%.4s'\n", buf);
       if (fseek(f,data,SEEK_CUR) == -1 ) {
          ast_log(LOG_WARNING, "Failed to skip '%.4s' block: %d\n", buf, data);
          return -1;
       }
    }
 #if 0
    curpos = lseek(fd, 0, SEEK_CUR);
    truelength = lseek(fd, 0, SEEK_END);
    lseek(fd, curpos, SEEK_SET);
    truelength -= curpos;
 #endif
    return data;
 }
check_header_fmt()
static int check_header_fmt (FILE * f, int hsize, int hz) static
Definition at line 81 of file format_wav.c.
References ast_log, chans, format, and LOG_WARNING.
Referenced by check_header().
 {
    unsigned short format, chans, bysam, bisam;
    unsigned int freq, bysec;
    if (hsize < 16) {
       ast_log(LOG_WARNING, "Unexpected header size %d\n", hsize);
       return -1;
    }
    if (fread(&format, 1, 2, f) != 2) {
       ast_log(LOG_WARNING, "Read failed (format)\n");
       return -1;
    }
    if (ltohs(format) != 1) {
       ast_log(LOG_WARNING, "Not a supported wav file format (%d). Only PCM encoded, 16 bit, mono, 8kHz/16kHz files are supported with a lowercase '.wav' extension.\n", ltohs(format));
       return -1;
    }
    if (fread(&chans, 1, 2, f) != 2) {
       ast_log(LOG_WARNING, "Read failed (format)\n");
       return -1;
    }
    if (ltohs(chans) != 1) {
       ast_log(LOG_WARNING, "Not in mono %d\n", ltohs(chans));
       return -1;
    }
    if (fread(&freq, 1, 4, f) != 4) {
       ast_log(LOG_WARNING, "Read failed (freq)\n");
       return -1;
    }
    freq = ltohl(freq);
    if ((freq != 8000 && freq != 16000) || freq != hz) {
       ast_log(LOG_WARNING, "Unexpected frequency mismatch %d (expecting %d)\n", freq, hz);
       return -1;
    }
    /* Ignore the byte frequency */
    if (fread(&bysec, 1, 4, f) != 4) {
       ast_log(LOG_WARNING, "Read failed (BYTES_PER_SECOND)\n");
       return -1;
    }
    /* Check bytes per sample */
    if (fread(&bysam, 1, 2, f) != 2) {
       ast_log(LOG_WARNING, "Read failed (BYTES_PER_SAMPLE)\n");
       return -1;
    }
    if (ltohs(bysam) != 2) {
       ast_log(LOG_WARNING, "Can only handle 16bits per sample: %d\n", ltohs(bysam));
       return -1;
    }
    if (fread(&bisam, 1, 2, f) != 2) {
       ast_log(LOG_WARNING, "Read failed (Bits Per Sample): %d\n", ltohs(bisam));
       return -1;
    }
    /* Skip any additional header */
    if (fseek(f,hsize-16,SEEK_CUR) == -1 ) {
       ast_log(LOG_WARNING, "Failed to skip remaining header bytes: %d\n", hsize-16 );
       return -1;
    }
    return 0;
 }
load_module()
static int load_module (void) static
Definition at line 555 of file format_wav.c.
References ast_format_def_register, ast_format_slin, ast_format_slin16, AST_MODFLAG_LOAD_ORDER, AST_MODPRI_APP_DEPEND, AST_MODULE_INFO(), AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, AST_MODULE_SUPPORT_CORE, ASTERISK_GPL_KEY, ast_format_def::format, and unload_module().
 {
    wav_f.format = ast_format_slin;
    wav16_f.format = ast_format_slin16;
    if (ast_format_def_register(&wav_f)
       || ast_format_def_register(&wav16_f)) {
       unload_module();
       return AST_MODULE_LOAD_DECLINE;
    }
    return AST_MODULE_LOAD_SUCCESS;
 }
unload_module()
static int unload_module (void) static
Definition at line 549 of file format_wav.c.
References ast_format_def_unregister(), and ast_format_def::name.
Referenced by load_module().
 {
    return ast_format_def_unregister(wav_f.name)
       || ast_format_def_unregister(wav16_f.name);
 }
update_header()
static int update_header (FILE * f) static
Definition at line 207 of file format_wav.c.
References ast_log, wav_desc::bytes, end, and LOG_WARNING.
Referenced by wav_close(), and wav_trunc().
 {
    off_t cur,end;
    int datalen,filelen,bytes;
    cur = ftello(f);
    fseek(f, 0, SEEK_END);
    end = ftello(f);
    /* data starts 44 bytes in */
    bytes = end - 44;
    datalen = htoll(bytes);
    /* chunk size is bytes of data plus 36 bytes of header */
    filelen = htoll(36 + bytes);
    if (cur < 0) {
       ast_log(LOG_WARNING, "Unable to find our position\n");
       return -1;
    }
    if (fseek(f, 4, SEEK_SET)) {
       ast_log(LOG_WARNING, "Unable to set our position\n");
       return -1;
    }
    if (fwrite(&filelen, 1, 4, f) != 4) {
       ast_log(LOG_WARNING, "Unable to set write file size\n");
       return -1;
    }
    if (fseek(f, 40, SEEK_SET)) {
       ast_log(LOG_WARNING, "Unable to set our position\n");
       return -1;
    }
    if (fwrite(&datalen, 1, 4, f) != 4) {
       ast_log(LOG_WARNING, "Unable to set write datalen\n");
       return -1;
    }
    if (fseeko(f, cur, SEEK_SET)) {
       ast_log(LOG_WARNING, "Unable to return to position\n");
       return -1;
    }
    return 0;
 }
wav_close()
static void wav_close (struct ast_filestream * s) static
Definition at line 349 of file format_wav.c.
References ast_filestream::_private, ast_log, wav_desc::bytes, errno, ast_filestream::f, ast_filestream::filename, if(), LOG_WARNING, ast_filestream::mode, and update_header().
 {
    char zero = 0;
    struct wav_desc *fs = (struct wav_desc *)s->_private;
    if (s->mode == O_RDONLY) {
       return;
    }
    if (s->filename) {
       update_header(s->f);
    }
    /* Pad to even length */
    if (fs->bytes & 0x1) {
       if (fwrite(&zero, 1, 1, s->f) != 1) {
          ast_log(LOG_WARNING, "fwrite() failed: %s\n", strerror(errno));
       }
    }
 }
wav_open()
static int wav_open (struct ast_filestream * s) static
Definition at line 319 of file format_wav.c.
References ast_filestream::_private, ast_format_get_sample_rate(), check_header(), ast_filestream::f, ast_filestream::fmt, ast_format_def::format, wav_desc::hz, wav_desc::maxlen, and tmp().
 {
    /* We don't have any header to read or anything really, but
       if we did, it would go here.  We also might want to check
       and be sure it's a valid file.  */
    struct wav_desc *tmp = s->_private;
    unsigned int sample_rate = ast_format_get_sample_rate(s->fmt->format);
    tmp->maxlen = check_header(s->f, sample_rate);
    if (tmp->maxlen < 0) {
       return -1;
    }
    tmp->hz = sample_rate;
    return 0;
 }
wav_read()
static struct ast_frame* wav_read (struct ast_filestream * s, int * whennext) static
Definition at line 370 of file format_wav.c.
References ast_filestream::_private, ast_format_get_name(), AST_FRAME_SET_BUFFER, AST_FRIENDLY_OFFSET, ast_log, ast_filestream::buf, wav_desc::bytes, ast_frame::data, ast_frame::datalen, errno, ast_filestream::f, ast_frame_subclass::format, ast_filestream::fr, wav_desc::hz, LOG_WARNING, wav_desc::maxlen, NULL, ast_frame::ptr, ast_frame::samples, ast_frame::subclass, tmp(), and WAV_BUF_SIZE.
 {
    size_t res;
    int samples;   /* actual samples read */
 #if __BYTE_ORDER == __BIG_ENDIAN
    int x;
    short *tmp;
 #endif
    int bytes;
    off_t here;
    /* Send a frame from the file to the appropriate channel */
    struct wav_desc *fs = (struct wav_desc *)s->_private;
    bytes = (fs->hz == 16000 ? (WAV_BUF_SIZE * 2) : WAV_BUF_SIZE);
    here = ftello(s->f);
    if (fs->maxlen - here < bytes)      /* truncate if necessary */
       bytes = fs->maxlen - here;
    if (bytes <= 0) {
       return NULL;
    }
 /*    ast_debug(1, "here: %d, maxlen: %d, bytes: %d\n", here, s->maxlen, bytes); */
    AST_FRAME_SET_BUFFER(&s->fr, s->buf, AST_FRIENDLY_OFFSET, bytes);
    if ((res = fread(s->fr.data.ptr, 1, s->fr.datalen, s->f)) == 0) {
       if (res) {
          ast_log(LOG_WARNING, "Short read of %s data (expected %d bytes, read %zu): %s\n",
                ast_format_get_name(s->fr.subclass.format), s->fr.datalen, res,
                strerror(errno));
       }
       return NULL;
    }
    s->fr.datalen = res;
    s->fr.samples = samples = res / 2;
 #if __BYTE_ORDER == __BIG_ENDIAN
    tmp = (short *)(s->fr.data.ptr);
    /* file format is little endian so we need to swap */
    for( x = 0; x < samples; x++)
       tmp[x] = (tmp[x] << 8) | ((tmp[x] & 0xff00) >> 8);
 #endif
    *whennext = samples;
    return &s->fr;
 }
wav_rewrite()
static int wav_rewrite (struct ast_filestream * s, const char * comment) static
Definition at line 336 of file format_wav.c.
References ast_filestream::_private, ast_format_get_sample_rate(), ast_filestream::f, ast_filestream::fmt, ast_format_def::format, wav_desc::hz, tmp(), and write_header().
 {
    /* We don't have any header to read or anything really, but
       if we did, it would go here.  We also might want to check
       and be sure it's a valid file.  */
    struct wav_desc *tmp = (struct wav_desc *)s->_private;
    tmp->hz = ast_format_get_sample_rate(s->fmt->format);
    if (write_header(s->f,tmp->hz))
       return -1;
    return 0;
 }
wav_seek()
static int wav_seek (struct ast_filestream * fs, off_t sample_offset, int whence) static
Definition at line 453 of file format_wav.c.
References ast_log, AST_LOG_WARNING, errno, ast_filestream::f, max, min, SEEK_FORCECUR, and WAV_HEADER_SIZE.
 {
    off_t min = WAV_HEADER_SIZE, max, cur, offset = 0, samples;
    samples = sample_offset * 2; /* SLINEAR is 16 bits mono, so sample_offset * 2 = bytes */
    if ((cur = ftello(fs->f)) < 0) {
       ast_log(AST_LOG_WARNING, "Unable to determine current position in wav filestream %p: %s\n", fs, strerror(errno));
       return -1;
    }
    if (fseeko(fs->f, 0, SEEK_END) < 0) {
       ast_log(AST_LOG_WARNING, "Unable to seek to end of wav filestream %p: %s\n", fs, strerror(errno));
       return -1;
    }
    if ((max = ftello(fs->f)) < 0) {
       ast_log(AST_LOG_WARNING, "Unable to determine max position in wav filestream %p: %s\n", fs, strerror(errno));
       return -1;
    }
    if (whence == SEEK_SET) {
       offset = samples + min;
    } else if (whence == SEEK_CUR || whence == SEEK_FORCECUR) {
       offset = samples + cur;
    } else if (whence == SEEK_END) {
       offset = max - samples;
    }
    if (whence != SEEK_FORCECUR) {
       offset = (offset > max)?max:offset;
    }
    /* always protect the header space. */
    offset = (offset < min)?min:offset;
    return fseeko(fs->f, offset, SEEK_SET);
 }
wav_tell()
static off_t wav_tell (struct ast_filestream * fs) static
Definition at line 509 of file format_wav.c.
References ast_filestream::f.
 {
    off_t offset;
    offset = ftello(fs->f);
    /* subtract header size to get samples, then divide by 2 for 16 bit samples */
    return (offset - 44)/2;
 }
wav_trunc()
static int wav_trunc (struct ast_filestream * fs) static
Definition at line 489 of file format_wav.c.
References ast_log, AST_LOG_WARNING, errno, ast_filestream::f, and update_header().
 {
    int fd;
    off_t cur;
    if ((fd = fileno(fs->f)) < 0) {
       ast_log(AST_LOG_WARNING, "Unable to determine file descriptor for wav filestream %p: %s\n", fs, strerror(errno));
       return -1;
    }
    if ((cur = ftello(fs->f)) < 0) {
       ast_log(AST_LOG_WARNING, "Unable to determine current position in wav filestream %p: %s\n", fs, strerror(errno));
       return -1;
    }
    /* Truncate file to current length */
    if (ftruncate(fd, cur)) {
       return -1;
    }
    return update_header(fs->f);
 }
wav_write()
static int wav_write (struct ast_filestream * fs, struct ast_frame * f) static
Definition at line 416 of file format_wav.c.
References ast_filestream::_private, ast_log, wav_desc::bytes, ast_frame::data, ast_frame::datalen, errno, ast_filestream::f, if(), LOG_WARNING, ast_frame::ptr, and tmp().
 {
 #if __BYTE_ORDER == __BIG_ENDIAN
    int x;
    short tmp[16000], *tmpi;
 #endif
    struct wav_desc *s = (struct wav_desc *)fs->_private;
    int res;
    if (!f->datalen)
       return -1;
 #if __BYTE_ORDER == __BIG_ENDIAN
    /* swap and write */
    if (f->datalen > sizeof(tmp)) {
       ast_log(LOG_WARNING, "Data length is too long\n");
       return -1;
    }
    tmpi = f->data.ptr;
    for (x=0; x < f->datalen/2; x++)
       tmp[x] = (tmpi[x] << 8) | ((tmpi[x] & 0xff00) >> 8);
    if ((res = fwrite(tmp, 1, f->datalen, fs->f)) != f->datalen ) {
 #else
    /* just write */
    if ((res = fwrite(f->data.ptr, 1, f->datalen, fs->f)) != f->datalen ) {
 #endif
       ast_log(LOG_WARNING, "Bad write (%d): %s\n", res, strerror(errno));
       return -1;
    }
    s->bytes += f->datalen;
    return 0;
 }
write_header()
static int write_header (FILE * f, int writehz) static
Definition at line 248 of file format_wav.c.
References ast_log, wav_desc::hz, and LOG_WARNING.
Referenced by wav_rewrite().
 {
    unsigned int hz;
    unsigned int bhz;
    unsigned int hs = htoll(16);
    unsigned short fmt = htols(1);
    unsigned short chans = htols(1);
    unsigned short bysam = htols(2);
    unsigned short bisam = htols(16);
    unsigned int size = htoll(0);
    if (writehz == 16000) {
       hz = htoll(16000);
       bhz = htoll(32000);
    } else {
       hz = htoll(8000);
       bhz = htoll(16000);
    }
    /* Write a wav header, ignoring sizes which will be filled in later */
    fseek(f,0,SEEK_SET);
    if (fwrite("RIFF", 1, 4, f) != 4) {
       ast_log(LOG_WARNING, "Unable to write header\n");
       return -1;
    }
    if (fwrite(&size, 1, 4, f) != 4) {
       ast_log(LOG_WARNING, "Unable to write header\n");
       return -1;
    }
    if (fwrite("WAVEfmt ", 1, 8, f) != 8) {
       ast_log(LOG_WARNING, "Unable to write header\n");
       return -1;
    }
    if (fwrite(&hs, 1, 4, f) != 4) {
       ast_log(LOG_WARNING, "Unable to write header\n");
       return -1;
    }
    if (fwrite(&fmt, 1, 2, f) != 2) {
       ast_log(LOG_WARNING, "Unable to write header\n");
       return -1;
    }
    if (fwrite(&chans, 1, 2, f) != 2) {
       ast_log(LOG_WARNING, "Unable to write header\n");
       return -1;
    }
    if (fwrite(&hz, 1, 4, f) != 4) {
       ast_log(LOG_WARNING, "Unable to write header\n");
       return -1;
    }
    if (fwrite(&bhz, 1, 4, f) != 4) {
       ast_log(LOG_WARNING, "Unable to write header\n");
       return -1;
    }
    if (fwrite(&bysam, 1, 2, f) != 2) {
       ast_log(LOG_WARNING, "Unable to write header\n");
       return -1;
    }
    if (fwrite(&bisam, 1, 2, f) != 2) {
       ast_log(LOG_WARNING, "Unable to write header\n");
       return -1;
    }
    if (fwrite("data", 1, 4, f) != 4) {
       ast_log(LOG_WARNING, "Unable to write header\n");
       return -1;
    }
    if (fwrite(&size, 1, 4, f) != 4) {
       ast_log(LOG_WARNING, "Unable to write header\n");
       return -1;
    }
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Microsoft WAV/WAV16 format (8kHz/16kHz Signed Linear)" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_APP_DEPEND } static
Definition at line 572 of file format_wav.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 572 of file format_wav.c.
wav16_f
struct ast_format_def wav16_f static
Definition at line 517 of file format_wav.c.
wav_f
struct ast_format_def wav_f static
Definition at line 533 of file format_wav.c.