Asterisk - The Open Source Telephony Project: security_events.c File Reference
main/security_events.c File Reference
Security Event Reporting Helpers.
#include "asterisk.h"
#include "asterisk/utils.h"
#include "asterisk/strings.h"
#include "asterisk/network.h"
#include "asterisk/event.h"
#include "asterisk/security_events.h"
#include "asterisk/netsock2.h"
#include "asterisk/stasis.h"
#include "asterisk/json.h"
#include "asterisk/astobj2.h"
Macros
#define MAX_SECURITY_IES 12
#define SEC_EVT_FIELD(e, field) (offsetof(struct ast_security_event_##e, field))
Enumerations
enum ie_required { NOT_REQUIRED, REQUIRED, NOT_REQUIRED, REQUIRED }
Functions
static int add_ip_json_object (struct ast_json *json, enum ast_event_ie_type ie_type, const struct ast_security_event_ip_addr *addr)
static int add_json_object (struct ast_json *json, const struct ast_security_event_common *sec, const struct ast_security_event_ie_type *ie_type, enum ie_required req)
static struct ast_json * alloc_security_event_json_object (const struct ast_security_event_common *sec)
static int append_event_str_from_json (struct ast_str **str, struct ast_json *json, const struct ast_security_event_ie_type *ies)
static int append_event_str_single (struct ast_str **str, struct ast_json *json, const enum ast_event_ie_type ie_type)
const char * ast_security_event_get_name (const enum ast_security_event_type event_type)
Get the name of a security event sub-type.
const struct ast_security_event_ie_type * ast_security_event_get_optional_ies (const enum ast_security_event_type event_type)
Get the list of optional IEs for a given security event sub-type.
const struct ast_security_event_ie_type * ast_security_event_get_required_ies (const enum ast_security_event_type event_type)
Get the list of required IEs for a given security event sub-type.
int ast_security_event_report (const struct ast_security_event_common *sec)
Report a security event.
const char * ast_security_event_severity_get_name (const enum ast_security_event_severity severity)
Get the name of a security event severity.
int ast_security_stasis_init (void)
initializes stasis topic/event types for ast_security_topic and ast_security_event_type
struct stasis_topic * ast_security_topic (void)
A stasis_topic which publishes messages for security related issues.
static int check_event_type (const enum ast_security_event_type event_type)
static int handle_security_event (const struct ast_security_event_common *sec)
static struct ast_manager_event_blob * security_event_to_ami (struct stasis_message *message)
static struct ast_manager_event_blob * security_event_to_ami_blob (struct ast_json *json)
static void security_stasis_cleanup (void)
STASIS_MESSAGE_TYPE_DEFN (ast_security_event_type,.to_ami=security_event_to_ami,)
Message type for security events.
Variables
struct {
const char * name
struct ast_security_event_ie_type optional_ies [MAX_SECURITY_IES]
struct ast_security_event_ie_type required_ies [MAX_SECURITY_IES]
enum ast_security_event_severity severity
uint32_t version
} sec_events [AST_SECURITY_EVENT_NUM_TYPES]
static const size_t SECURITY_EVENT_BUF_INIT_LEN = 256
static struct stasis_topic * security_topic
Security Topic.
struct {
enum ast_security_event_severity severity
const char * str
} severities []
Detailed Description
Security Event Reporting Helpers.
Author
Russell Bryant russe.nosp@m.ll@d.nosp@m.igium.nosp@m..com
Definition in file main/security_events.c.
Macro Definition Documentation
MAX_SECURITY_IES
#define MAX_SECURITY_IES 12
Definition at line 504 of file main/security_events.c.
SEC_EVT_FIELD
#define SEC_EVT_FIELD (e, field) (offsetof(struct ast_security_event_##e, field))
Enumeration Type Documentation
ie_required
enum ie_required
Enumerator
NOT_REQUIRED
REQUIRED
NOT_REQUIRED
REQUIRED
Definition at line 937 of file main/security_events.c.
                  {
    NOT_REQUIRED,
    REQUIRED
 };
Function Documentation
add_ip_json_object()
static int add_ip_json_object (struct ast_json * json, enum ast_event_ie_type ie_type, const struct ast_security_event_ip_addr * addr) static
Definition at line 924 of file main/security_events.c.
References ast_security_event_ip_addr::addr, ast_event_get_ie_type_name(), ast_json_ipaddr(), ast_json_object_set(), and ast_security_event_ip_addr::transport.
Referenced by add_json_object().
 {
    struct ast_json *json_ip;
    json_ip = ast_json_ipaddr(addr->addr, addr->transport);
    if (!json_ip) {
       return -1;
    }
    return ast_json_object_set(json, ast_event_get_ie_type_name(ie_type), json_ip);
 }
add_json_object()
static int add_json_object (struct ast_json * json, const struct ast_security_event_common * sec, const struct ast_security_event_ie_type * ie_type, enum ie_required req) static
Definition at line 942 of file main/security_events.c.
References add_ip_json_object(), ast_security_event_ip_addr::addr, ast_event_get_ie_type_name(), AST_EVENT_IE_ACCOUNT_ID, AST_EVENT_IE_ACL_NAME, AST_EVENT_IE_ATTEMPTED_TRANSPORT, AST_EVENT_IE_AUTH_METHOD, AST_EVENT_IE_CHALLENGE, AST_EVENT_IE_EVENT_TV, AST_EVENT_IE_EVENT_VERSION, AST_EVENT_IE_EXPECTED_ADDR, AST_EVENT_IE_EXPECTED_RESPONSE, AST_EVENT_IE_LOCAL_ADDR, AST_EVENT_IE_MODULE, AST_EVENT_IE_RECEIVED_CHALLENGE, AST_EVENT_IE_RECEIVED_HASH, AST_EVENT_IE_REMOTE_ADDR, AST_EVENT_IE_REQUEST_PARAMS, AST_EVENT_IE_REQUEST_TYPE, AST_EVENT_IE_RESPONSE, AST_EVENT_IE_SERVICE, AST_EVENT_IE_SESSION_ID, AST_EVENT_IE_SESSION_TV, AST_EVENT_IE_SEVERITY, AST_EVENT_IE_USING_PASSWORD, ast_json_object_set(), ast_json_string_create(), ast_json_stringf(), ast_json_timeval(), ast_log, ast_security_event_get_name(), ast_security_event_ie_type::ie_type, LOG_WARNING, NULL, ast_security_event_ie_type::offset, and str.
Referenced by handle_security_event().
 {
    int res = 0;
    switch (ie_type->ie_type) {
    case AST_EVENT_IE_SERVICE:
    case AST_EVENT_IE_ACCOUNT_ID:
    case AST_EVENT_IE_SESSION_ID:
    case AST_EVENT_IE_MODULE:
    case AST_EVENT_IE_ACL_NAME:
    case AST_EVENT_IE_REQUEST_TYPE:
    case AST_EVENT_IE_REQUEST_PARAMS:
    case AST_EVENT_IE_AUTH_METHOD:
    case AST_EVENT_IE_CHALLENGE:
    case AST_EVENT_IE_RESPONSE:
    case AST_EVENT_IE_EXPECTED_RESPONSE:
    case AST_EVENT_IE_RECEIVED_CHALLENGE:
    case AST_EVENT_IE_RECEIVED_HASH:
    case AST_EVENT_IE_ATTEMPTED_TRANSPORT:
    {
       const char *str;
       struct ast_json *json_string;
       str = *((const char **)(((const char *) sec) + ie_type->offset));
       if (req && !str) {
          ast_log(LOG_WARNING, "Required IE '%d' (%s) for security event "
                "type '%u' (%s) not present\n", ie_type->ie_type,
                ast_event_get_ie_type_name(ie_type->ie_type),
                sec->event_type, ast_security_event_get_name(sec->event_type));
          res = -1;
          break;
       }
       if (!str) {
          break;
       }
       json_string = ast_json_string_create(str);
       if (!json_string) {
          res = -1;
          break;
       }
       res = ast_json_object_set(json, ast_event_get_ie_type_name(ie_type->ie_type), json_string);
       break;
    }
    case AST_EVENT_IE_EVENT_VERSION:
    case AST_EVENT_IE_USING_PASSWORD:
    {
       struct ast_json *json_string;
       uint32_t val;
       val = *((const uint32_t *)(((const char *) sec) + ie_type->offset));
       json_string = ast_json_stringf("%u", val);
       if (!json_string) {
          res = -1;
          break;
       }
       res = ast_json_object_set(json, ast_event_get_ie_type_name(ie_type->ie_type), json_string);
       break;
    }
    case AST_EVENT_IE_LOCAL_ADDR:
    case AST_EVENT_IE_REMOTE_ADDR:
    case AST_EVENT_IE_EXPECTED_ADDR:
    {
       const struct ast_security_event_ip_addr *addr;
       addr = (const struct ast_security_event_ip_addr *)(((const char *) sec) + ie_type->offset);
       if (req && !addr->addr) {
          ast_log(LOG_WARNING, "Required IE '%d' (%s) for security event "
                "type '%u' (%s) not present\n", ie_type->ie_type,
                ast_event_get_ie_type_name(ie_type->ie_type),
                sec->event_type, ast_security_event_get_name(sec->event_type));
          res = -1;
       }
       if (addr->addr) {
          res = add_ip_json_object(json, ie_type->ie_type, addr);
       }
       break;
    }
    case AST_EVENT_IE_SESSION_TV:
    {
       const struct timeval *tval;
       tval = *((const struct timeval **)(((const char *) sec) + ie_type->offset));
       if (req && !tval) {
          ast_log(LOG_WARNING, "Required IE '%d' (%s) for security event "
                "type '%u' (%s) not present\n", ie_type->ie_type,
                ast_event_get_ie_type_name(ie_type->ie_type),
                sec->event_type, ast_security_event_get_name(sec->event_type));
          res = -1;
       }
       if (tval) {
          struct ast_json *json_tval = ast_json_timeval(*tval, NULL);
          if (!json_tval) {
             res = -1;
             break;
          }
          res = ast_json_object_set(json, ast_event_get_ie_type_name(ie_type->ie_type), json_tval);
       }
       break;
    }
    case AST_EVENT_IE_EVENT_TV:
    case AST_EVENT_IE_SEVERITY:
       /* Added automatically, nothing to do here. */
       break;
    default:
       ast_log(LOG_WARNING, "Unhandled IE type '%d' (%s), this security event "
             "will be missing data.\n", ie_type->ie_type,
             ast_event_get_ie_type_name(ie_type->ie_type));
       break;
    }
    return res;
 }
alloc_security_event_json_object()
static struct ast_json* alloc_security_event_json_object (const struct ast_security_event_common * sec) static
Definition at line 1067 of file main/security_events.c.
References ast_event_get_ie_type_name(), AST_EVENT_IE_EVENT_TV, AST_EVENT_IE_EVENT_VERSION, AST_EVENT_IE_SERVICE, AST_EVENT_IE_SEVERITY, ast_json_integer_create(), ast_json_object_create(), ast_json_object_set(), ast_json_ref(), ast_json_string_create(), ast_json_stringf(), ast_json_timeval(), ast_json_unref(), ast_security_event_severity_get_name(), ast_tvnow(), ast_security_event_common::event_type, NULL, RAII_VAR, S_OR, sec_events, ast_security_event_common::service, and ast_security_event_common::version.
Referenced by handle_security_event().
 {
    struct timeval tv = ast_tvnow();
    const char *severity_str;
    struct ast_json *json_temp;
    RAII_VAR(struct ast_json *, json_object, ast_json_object_create(), ast_json_unref);
    if (!json_object) {
       return NULL;
    }
    /* NOTE: Every time ast_json_object_set is used, json_temp becomes a stale pointer since the reference is taken.
     *       This is true even if ast_json_object_set fails.
     */
    json_temp = ast_json_integer_create(sec->event_type);
    if (!json_temp || ast_json_object_set(json_object, "SecurityEvent", json_temp)) {
       return NULL;
    }
    json_temp = ast_json_stringf("%u", sec->version);
    if (!json_temp || ast_json_object_set(json_object, ast_event_get_ie_type_name(AST_EVENT_IE_EVENT_VERSION), json_temp)) {
       return NULL;
    }
    /* AST_EVENT_IE_EVENT_TV */
    json_temp  = ast_json_timeval(tv, NULL);
    if (!json_temp || ast_json_object_set(json_object, ast_event_get_ie_type_name(AST_EVENT_IE_EVENT_TV), json_temp)) {
       return NULL;
    }
    /* AST_EVENT_IE_SERVICE */
    json_temp = ast_json_string_create(sec->service);
    if (!json_temp || ast_json_object_set(json_object, ast_event_get_ie_type_name(AST_EVENT_IE_SERVICE), json_temp)) {
       return NULL;
    }
    /* AST_EVENT_IE_SEVERITY */
    severity_str = S_OR(
       ast_security_event_severity_get_name(sec_events[sec->event_type].severity),
       "Unknown"
    );
    json_temp = ast_json_string_create(severity_str);
    if (!json_temp || ast_json_object_set(json_object, ast_event_get_ie_type_name(AST_EVENT_IE_SEVERITY), json_temp)) {
       return NULL;
    }
    return ast_json_ref(json_object);
 }
append_event_str_from_json()
static int append_event_str_from_json (struct ast_str ** str, struct ast_json * json, const struct ast_security_event_ie_type * ies) static
Definition at line 402 of file main/security_events.c.
References append_event_str_single(), AST_EVENT_IE_END, and ast_security_event_ie_type::ie_type.
Referenced by security_event_to_ami_blob().
 {
    unsigned int i;
    if (!ies) {
       return 0;
    }
    for (i = 0; ies[i].ie_type != AST_EVENT_IE_END; i++) {
       if (append_event_str_single(str, json, ies[i].ie_type)) {
          return -1;
       }
    }
    return 0;
 }
append_event_str_single()
static int append_event_str_single (struct ast_str ** str, struct ast_json * json, const enum ast_event_ie_type ie_type) static
Definition at line 385 of file main/security_events.c.
References ast_event_get_ie_type_name(), ast_json_object_get(), ast_json_string_get(), ast_str_append(), and S_OR.
Referenced by append_event_str_from_json().
 {
    const char *ie_type_key = ast_event_get_ie_type_name(ie_type);
    struct ast_json *json_string = ast_json_object_get(json, ie_type_key);
    if (!json_string) {
       return 0;
    }
    if (ast_str_append(str, 0, "%s: %s\r\n", ie_type_key, S_OR(ast_json_string_get(json_string), "")) == -1) {
       return -1;
    }
    return 0;
 }
ast_security_event_get_name()
const char* ast_security_event_get_name (const enum ast_security_event_type event_type)
Get the name of a security event sub-type.
Parameters
[in] event_type security event sub-type
Return values
NULL if event_type is invalid
non-NULL the name of the security event type
Since
1.8
Definition at line 895 of file main/security_events.c.
References check_event_type(), NULL, and sec_events.
Referenced by add_json_object(), ast_security_event_report(), gen_events(), security_event_stasis_cb(), and security_event_to_ami_blob().
 {
    if (check_event_type(event_type)) {
       return NULL;
    }
    return sec_events[event_type].name;
 }
ast_security_event_get_optional_ies()
const struct ast_security_event_ie_type* ast_security_event_get_optional_ies (const enum ast_security_event_type event_type)
Get the list of optional IEs for a given security event sub-type.
Parameters
[in] event_type security event sub-type
Return values
NULL invalid event_type
non-NULL An array terminated with the value AST_EVENT_IE_END
Since
1.8
Definition at line 914 of file main/security_events.c.
References check_event_type(), NULL, and sec_events.
Referenced by handle_security_event(), security_event_stasis_cb(), and security_event_to_ami_blob().
 {
    if (check_event_type(event_type)) {
       return NULL;
    }
    return sec_events[event_type].optional_ies;
 }
ast_security_event_get_required_ies()
const struct ast_security_event_ie_type* ast_security_event_get_required_ies (const enum ast_security_event_type event_type)
Get the list of required IEs for a given security event sub-type.
Parameters
[in] event_type security event sub-type
Return values
NULL invalid event_type
non-NULL An array terminated with the value AST_EVENT_IE_END
Since
1.8
Definition at line 904 of file main/security_events.c.
References check_event_type(), NULL, and sec_events.
Referenced by handle_security_event(), security_event_stasis_cb(), and security_event_to_ami_blob().
 {
    if (check_event_type(event_type)) {
       return NULL;
    }
    return sec_events[event_type].required_ies;
 }
ast_security_event_report()
int ast_security_event_report (const struct ast_security_event_common * sec)
Report a security event.
Parameters
[in] sec security event data. Callers of this function should never declare an instance of ast_security_event_common directly. The argument should be an instance of a specific security event descriptor which has ast_security_event_common at the very beginning.
Return values
0 success
non-zero failure
Definition at line 1171 of file main/security_events.c.
References ast_log, ast_security_event_get_name(), AST_SECURITY_EVENT_NUM_TYPES, ast_security_event_common::event_type, handle_security_event(), LOG_ERROR, LOG_WARNING, sec_events, and ast_security_event_common::version.
Referenced by ast_sip_report_auth_challenge_sent(), ast_sip_report_auth_failed_challenge_response(), ast_sip_report_auth_success(), ast_sip_report_failed_acl(), ast_sip_report_invalid_endpoint(), ast_sip_report_mem_limit(), ast_sip_report_req_no_support(), evt_gen_auth_method_not_allowed(), evt_gen_chal_resp_failed(), evt_gen_chal_sent(), evt_gen_failed_acl(), evt_gen_inval_acct_id(), evt_gen_inval_password(), evt_gen_inval_transport(), evt_gen_load_avg(), evt_gen_mem_limit(), evt_gen_req_bad_format(), evt_gen_req_no_support(), evt_gen_req_not_allowed(), evt_gen_session_limit(), evt_gen_successful_auth(), evt_gen_unexpected_addr(), report_auth_success(), report_failed_acl(), report_failed_challenge_response(), report_inval_password(), report_invalid_user(), report_req_bad_format(), report_req_not_allowed(), report_session_limit(), sip_report_auth_success(), sip_report_chal_sent(), sip_report_failed_acl(), sip_report_failed_challenge_response(), sip_report_inval_password(), sip_report_inval_transport(), sip_report_invalid_peer(), and sip_report_session_limit().
 {
    if ((unsigned int)sec->event_type >= AST_SECURITY_EVENT_NUM_TYPES) {
       ast_log(LOG_ERROR, "Invalid security event type\n");
       return -1;
    }
    if (!sec_events[sec->event_type].name) {
       ast_log(LOG_WARNING, "Security event type %u not handled\n",
             sec->event_type);
       return -1;
    }
    if (sec->version != sec_events[sec->event_type].version) {
       ast_log(LOG_WARNING, "Security event %u version mismatch\n",
             sec->event_type);
       return -1;
    }
    if (handle_security_event(sec)) {
       ast_log(LOG_ERROR, "Failed to issue security event of type %s.\n",
             ast_security_event_get_name(sec->event_type));
    }
    return 0;
 }
ast_security_event_severity_get_name()
const char* ast_security_event_severity_get_name (const enum ast_security_event_severity severity)
Get the name of a security event severity.
Parameters
[in] severity security event severity
Return values
NULL if severity is invalid
non-NULL the name of the security event severity
Since
1.8
Definition at line 871 of file main/security_events.c.
References ARRAY_LEN, NULL, and severities.
Referenced by alloc_security_event_json_object().
 {
    unsigned int i;
    for (i = 0; i < ARRAY_LEN(severities); i++) {
       if (severities[i].severity == severity) {
          return severities[i].str;
       }
    }
    return NULL;
 }
ast_security_stasis_init()
int ast_security_stasis_init (void)
initializes stasis topic/event types for ast_security_topic and ast_security_event_type
Since
12
Return values
0 on success
-1 on failure
Definition at line 483 of file main/security_events.c.
References ast_register_cleanup(), security_stasis_cleanup(), STASIS_MESSAGE_TYPE_INIT, and stasis_topic_create().
Referenced by asterisk_daemon().
 {
    ast_register_cleanup(security_stasis_cleanup);
    security_topic = stasis_topic_create("security:all");
    if (!security_topic) {
       return -1;
    }
    if (STASIS_MESSAGE_TYPE_INIT(ast_security_event_type)) {
       return -1;
    }
    return 0;
 }
ast_security_topic()
struct stasis_topic* ast_security_topic (void)
A stasis_topic which publishes messages for security related issues.
Since
12
Return values
Definition at line 380 of file main/security_events.c.
References security_topic.
Referenced by acl_change_stasis_subscribe(), ast_res_pjsip_initialize_configuration(), handle_security_event(), load_module(), manager_subscriptions_init(), publish_acl_change(), and rtp_reload().
 {
    return security_topic;
 }
check_event_type()
static int check_event_type (const enum ast_security_event_type event_type) static
Definition at line 885 of file main/security_events.c.
References ast_log, AST_SECURITY_EVENT_NUM_TYPES, and LOG_ERROR.
Referenced by ast_security_event_get_name(), ast_security_event_get_optional_ies(), and ast_security_event_get_required_ies().
 {
    if ((unsigned int)event_type >= AST_SECURITY_EVENT_NUM_TYPES) {
       ast_log(LOG_ERROR, "Invalid security event type %u\n", event_type);
       return -1;
    }
    return 0;
 }
handle_security_event()
static int handle_security_event (const struct ast_security_event_common * sec) static
Definition at line 1118 of file main/security_events.c.
References add_json_object(), alloc_security_event_json_object(), ao2_cleanup, AST_EVENT_IE_END, ast_json_payload_create(), ast_json_unref(), ast_security_event_get_optional_ies(), ast_security_event_get_required_ies(), ast_security_topic(), ast_security_event_common::event_type, ast_security_event_ie_type::ie_type, NOT_REQUIRED, NULL, RAII_VAR, REQUIRED, stasis_message_create(), and stasis_publish().
Referenced by ast_security_event_report().
 {
    RAII_VAR(struct stasis_message *, msg, NULL, ao2_cleanup);
    RAII_VAR(struct ast_json_payload *, json_payload, NULL, ao2_cleanup);
    RAII_VAR(struct ast_json *, json_object, NULL, ast_json_unref);
    const struct ast_security_event_ie_type *ies;
    unsigned int i;
    if (!ast_security_event_type()) {
       return -1;
    }
    json_object = alloc_security_event_json_object(sec);
    if (!json_object) {
       return -1;
    }
    for (ies = ast_security_event_get_required_ies(sec->event_type), i = 0;
          ies[i].ie_type != AST_EVENT_IE_END;
          i++) {
       if (add_json_object(json_object, sec, ies + i, REQUIRED)) {
          goto return_error;
       }
    }
    for (ies = ast_security_event_get_optional_ies(sec->event_type), i = 0;
          ies[i].ie_type != AST_EVENT_IE_END;
          i++) {
       if (add_json_object(json_object, sec, ies + i, NOT_REQUIRED)) {
          goto return_error;
       }
    }
    /* The json blob is ready.  Throw it in the payload and send it out over stasis. */
    if (!(json_payload = ast_json_payload_create(json_object))) {
       goto return_error;
    }
    msg = stasis_message_create(ast_security_event_type(), json_payload);
    if (!msg) {
       goto return_error;
    }
    stasis_publish(ast_security_topic(), msg);
    return 0;
 return_error:
    return -1;
 }
security_event_to_ami()
static struct ast_manager_event_blob* security_event_to_ami (struct stasis_message * message) static
Definition at line 455 of file main/security_events.c.
References ast_json_payload::json, NULL, security_event_to_ami_blob(), stasis_message_data(), stasis_message_type(), STASIS_MESSAGE_TYPE_DEFN(), and to_ami().
 {
    struct ast_json_payload *payload = stasis_message_data(message);
    if (stasis_message_type(message) != ast_security_event_type()) {
       return NULL;
    }
    if (!payload) {
       return NULL;
    }
    return security_event_to_ami_blob(payload->json);
 }
security_event_to_ami_blob()
static struct ast_manager_event_blob* security_event_to_ami_blob (struct ast_json * json) static
Definition at line 420 of file main/security_events.c.
References append_event_str_from_json(), ast_assert, ast_free, ast_json_integer_get(), ast_json_object_get(), ast_log, AST_LOG_ERROR, ast_manager_event_blob_create(), ast_security_event_get_name(), ast_security_event_get_optional_ies(), ast_security_event_get_required_ies(), AST_SECURITY_EVENT_NUM_TYPES, ast_str_buffer(), ast_str_create, EVENT_FLAG_SECURITY, NULL, RAII_VAR, SECURITY_EVENT_BUF_INIT_LEN, and str.
Referenced by security_event_to_ami().
 {
    RAII_VAR(struct ast_str *, str, NULL, ast_free);
    struct ast_json *event_type_json;
    enum ast_security_event_type event_type;
    event_type_json = ast_json_object_get(json, "SecurityEvent");
    event_type = ast_json_integer_get(event_type_json);
    ast_assert((unsigned int)event_type < AST_SECURITY_EVENT_NUM_TYPES);
    if (!(str = ast_str_create(SECURITY_EVENT_BUF_INIT_LEN))) {
       return NULL;
    }
    if (append_event_str_from_json(&str, json,
          ast_security_event_get_required_ies(event_type))) {
       ast_log(AST_LOG_ERROR, "Failed to issue a security event to AMI: "
          "error occurred when adding required event fields.\n");
       return NULL;
    }
    if (append_event_str_from_json(&str, json,
          ast_security_event_get_optional_ies(event_type))) {
       ast_log(AST_LOG_ERROR, "Failed to issue a security event to AMI: "
          "error occurred when adding optional event fields.\n");
       return NULL;
    }
    return ast_manager_event_blob_create(EVENT_FLAG_SECURITY,
       ast_security_event_get_name(event_type),
       "%s",
       ast_str_buffer(str));
 }
security_stasis_cleanup()
static void security_stasis_cleanup (void) static
Definition at line 475 of file main/security_events.c.
References ao2_cleanup, NULL, and STASIS_MESSAGE_TYPE_CLEANUP.
Referenced by ast_security_stasis_init().
 {
    ao2_cleanup(security_topic);
    security_topic = NULL;
    STASIS_MESSAGE_TYPE_CLEANUP(ast_security_event_type);
 }
STASIS_MESSAGE_TYPE_DEFN()
STASIS_MESSAGE_TYPE_DEFN (ast_security_event_type , . to_ami = security_event_to_ami)
Message type for security events.
Referenced by security_event_to_ami().
Variable Documentation
name
const char* name
Definition at line 501 of file main/security_events.c.
optional_ies
struct ast_security_event_ie_type optional_ies[MAX_SECURITY_IES]
Definition at line 506 of file main/security_events.c.
required_ies
struct ast_security_event_ie_type required_ies[MAX_SECURITY_IES]
Definition at line 505 of file main/security_events.c.
sec_events
const { ... } sec_events[AST_SECURITY_EVENT_NUM_TYPES]
Referenced by alloc_security_event_json_object(), ast_security_event_get_name(), ast_security_event_get_optional_ies(), ast_security_event_get_required_ies(), and ast_security_event_report().
SECURITY_EVENT_BUF_INIT_LEN
const size_t SECURITY_EVENT_BUF_INIT_LEN = 256 static
Definition at line 375 of file main/security_events.c.
Referenced by security_event_to_ami_blob().
security_topic
struct stasis_topic* security_topic static
Security Topic.
Definition at line 378 of file main/security_events.c.
Referenced by ast_security_topic().
severities
const { ... } severities[]
Initial value:
= {
   { AST_SECURITY_EVENT_SEVERITY_INFO,  "Informational" },
   { AST_SECURITY_EVENT_SEVERITY_ERROR, "Error" },
}
Referenced by ast_security_event_severity_get_name().
severity
enum ast_security_event_severity severity
Definition at line 503 of file main/security_events.c.
str
const char* str
Definition at line 865 of file main/security_events.c.
Referenced by add_json_object(), and security_event_to_ami_blob().
version
uint32_t version
Definition at line 502 of file main/security_events.c.