Asterisk - The Open Source Telephony Project: res_stasis_test.c File Reference
res_stasis_test.c File Reference
Test infrastructure for dealing with Stasis.
#include "asterisk.h"
#include "asterisk/astobj2.h"
#include "asterisk/module.h"
#include "asterisk/stasis_test.h"
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int load_module (void)
static struct timespec make_deadline (int timeout_millis)
static void message_sink_cb (void *data, struct stasis_subscription *sub, struct stasis_message *message)
Implementation of the stasis_message_sink_cb() callback.
stasis_subscription_cb stasis_message_sink_cb (void)
Topic callback to receive messages.
struct stasis_message_sink * stasis_message_sink_create (void)
Create a message sink.
static void stasis_message_sink_dtor (void *obj)
int stasis_message_sink_should_stay (struct stasis_message_sink *sink, int num_messages, int timeout_millis)
Ensures that no new messages are received.
int stasis_message_sink_wait_for (struct stasis_message_sink *sink, int start, stasis_wait_cb cmp_cb, const void *data, int timeout_millis)
Wait for a message that matches the given criteria.
int stasis_message_sink_wait_for_count (struct stasis_message_sink *sink, int num_messages, int timeout_millis)
Wait for a sink's num_messages field to reach a certain level.
STASIS_MESSAGE_TYPE_DEFN (stasis_test_message_type)
struct stasis_message * stasis_test_message_create (void)
Creates a test message.
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_GLOBAL_SYMBOLS | AST_MODFLAG_LOAD_ORDER , .description = "Stasis test utilities" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_APP_DEPEND, }
static const struct ast_module_info * ast_module_info = &__mod_info
Detailed Description
Test infrastructure for dealing with Stasis.
Author
David M. Lee, II dlee@.nosp@m.digi.nosp@m.um.co.nosp@m.m
Definition in file res_stasis_test.c.
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 273 of file res_stasis_test.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 273 of file res_stasis_test.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 273 of file res_stasis_test.c.
load_module()
static int load_module (void) static
Definition at line 259 of file res_stasis_test.c.
References AST_MODFLAG_GLOBAL_SYMBOLS, AST_MODFLAG_LOAD_ORDER, AST_MODPRI_APP_DEPEND, AST_MODULE_INFO(), AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, AST_MODULE_SUPPORT_CORE, ASTERISK_GPL_KEY, STASIS_MESSAGE_TYPE_INIT, stasis_test_message_type(), and unload_module().
 {
    if (STASIS_MESSAGE_TYPE_INIT(stasis_test_message_type) != 0) {
       return AST_MODULE_LOAD_DECLINE;
    }
    return AST_MODULE_LOAD_SUCCESS;
 }
make_deadline()
static struct timespec make_deadline (int timeout_millis) static
Definition at line 63 of file res_stasis_test.c.
References ast_tvadd(), and ast_tvnow().
Referenced by stasis_message_sink_should_stay(), stasis_message_sink_wait_for(), and stasis_message_sink_wait_for_count().
 {
    struct timeval start = ast_tvnow();
    struct timeval delta = {
       .tv_sec = timeout_millis / 1000,
       .tv_usec = (timeout_millis % 1000) * 1000,
    };
    struct timeval deadline_tv = ast_tvadd(start, delta);
    struct timespec deadline = {
       .tv_sec = deadline_tv.tv_sec,
       .tv_nsec = 1000 * deadline_tv.tv_usec,
    };
    return deadline;
 }
message_sink_cb()
static void message_sink_cb (void * data, struct stasis_subscription * sub, struct stasis_message * message) static
Implementation of the stasis_message_sink_cb() callback.
Why the roundabout way of exposing this via stasis_message_sink_cb()? Well, it has to do with how we previously loaded modules, using RTLD_LAZY.
The stasis_message_sink_cb() function gave us a layer of indirection so that the initial lazy binding would still work as expected.
Definition at line 108 of file res_stasis_test.c.
References ao2_ref, ast_cond_signal, ast_realloc, stasis_message_sink::cond, stasis_message_sink::is_done, stasis_message_sink::lock, lock, stasis_message_sink::max_messages, stasis_message_sink::messages, stasis_message_sink::num_messages, SCOPED_MUTEX, stasis_message_type(), stasis_subscription_change_type(), and stasis_subscription_final_message().
Referenced by stasis_message_sink_cb().
 {
    struct stasis_message_sink *sink = data;
    SCOPED_MUTEX(lock, &sink->lock);
    if (stasis_subscription_final_message(sub, message)) {
       sink->is_done = 1;
       ast_cond_signal(&sink->cond);
       return;
    }
    if (stasis_subscription_change_type() == stasis_message_type(message)) {
       /* Ignore subscription changes */
       return;
    }
    if (sink->num_messages == sink->max_messages) {
       size_t new_max_messages = sink->max_messages * 2;
       struct stasis_message **new_messages = ast_realloc(
          sink->messages,
          sizeof(*new_messages) * new_max_messages);
       if (!new_messages) {
          return;
       }
       sink->max_messages = new_max_messages;
       sink->messages = new_messages;
    }
    ao2_ref(message, +1);
    sink->messages[sink->num_messages++] = message;
    ast_cond_signal(&sink->cond);
 }
stasis_message_sink_cb()
stasis_subscription_cb stasis_message_sink_cb (void)
Topic callback to receive messages.
We return a function pointer instead of simply exposing the function because of the vagaries of dlopen(), RTLD_LAZY, and function pointers. See the comment on the implementation for details why.
Returns
Function pointer to stasis_message_sink's message handling function
Definition at line 143 of file res_stasis_test.c.
References message_sink_cb().
Referenced by AST_TEST_DEFINE().
 {
    return message_sink_cb;
 }
stasis_message_sink_create()
struct stasis_message_sink* stasis_message_sink_create (void)
Create a message sink.
This is an AO2 managed object, which you ao2_cleanup() when done. The destructor waits for an unsubscribe message to be received, to ensure the object isn't disposed of before the topic is finished.
Definition at line 79 of file res_stasis_test.c.
References ao2_alloc, ao2_cleanup, ao2_ref, ast_cond_init, ast_malloc, ast_mutex_init, NULL, RAII_VAR, and stasis_message_sink_dtor().
Referenced by AST_TEST_DEFINE().
 {
    RAII_VAR(struct stasis_message_sink *, sink, NULL, ao2_cleanup);
    sink = ao2_alloc(sizeof(*sink), stasis_message_sink_dtor);
    if (!sink) {
       return NULL;
    }
    ast_mutex_init(&sink->lock);
    ast_cond_init(&sink->cond, NULL);
    sink->max_messages = 4;
    sink->messages =
       ast_malloc(sizeof(*sink->messages) * sink->max_messages);
    if (!sink->messages) {
       return NULL;
    }
    ao2_ref(sink, +1);
    return sink;
 }
stasis_message_sink_dtor()
static void stasis_message_sink_dtor (void * obj) static
Definition at line 39 of file res_stasis_test.c.
References ao2_cleanup, ast_cond_destroy, ast_cond_wait, ast_free, ast_mutex_destroy, stasis_message_sink::cond, stasis_message_sink::is_done, stasis_message_sink::lock, lock, stasis_message_sink::max_messages, stasis_message_sink::messages, NULL, stasis_message_sink::num_messages, and SCOPED_MUTEX.
Referenced by stasis_message_sink_create().
 {
    struct stasis_message_sink *sink = obj;
    {
       SCOPED_MUTEX(lock, &sink->lock);
       while (!sink->is_done) {
          /* Normally waiting forever is bad, but if we're not
           * done, we're not done. */
          ast_cond_wait(&sink->cond, &sink->lock);
       }
    }
    ast_mutex_destroy(&sink->lock);
    ast_cond_destroy(&sink->cond);
    while (sink->num_messages > 0) {
       ao2_cleanup(sink->messages[--sink->num_messages]);
    }
    ast_free(sink->messages);
    sink->messages = NULL;
    sink->max_messages = 0;
 }
stasis_message_sink_should_stay()
int stasis_message_sink_should_stay (struct stasis_message_sink * sink, int num_messages, int timeout_millis)
Ensures that no new messages are received.
The optional timeout prevents complete deadlock in a test.
Parameters
sink Sink to wait on.
num_messages expecte sink->num_messages.
timeout_millis Number of milliseconds to wait for.
Returns
Actual sink->num_messages value at return. If this is < num_messages, then the timeout expired.
Definition at line 170 of file res_stasis_test.c.
References ast_cond_timedwait, ast_log, stasis_message_sink::cond, stasis_message_sink::lock, lock, LOG_ERROR, make_deadline(), stasis_message_sink::num_messages, and SCOPED_MUTEX.
 {
    struct timespec deadline = make_deadline(timeout_millis);
    SCOPED_MUTEX(lock, &sink->lock);
    while (sink->num_messages == num_messages) {
       int r = ast_cond_timedwait(&sink->cond, &sink->lock, &deadline);
       if (r == ETIMEDOUT) {
          break;
       }
       if (r != 0) {
          ast_log(LOG_ERROR, "Unexpected condition error: %s\n",
             strerror(r));
          break;
       }
    }
    return sink->num_messages;
 }
stasis_message_sink_wait_for()
int stasis_message_sink_wait_for (struct stasis_message_sink * sink, int start, stasis_wait_cb cmp_cb, const void * data, int timeout_millis)
Wait for a message that matches the given criteria.
Parameters
sink Sink to wait on.
start Index of message to start with.
cmp_cb comparison function. This returns true (non-zero) on match and false (zero) on match.
timeout_millis Number of milliseconds to wait.
Returns
Index of the matching message.
Negative for no match.
Definition at line 191 of file res_stasis_test.c.
References ast_cond_timedwait, ast_log, stasis_message_sink::cond, stasis_message_sink::lock, lock, LOG_ERROR, make_deadline(), stasis_message_sink::messages, stasis_message_sink::num_messages, and SCOPED_MUTEX.
Referenced by AST_TEST_DEFINE().
 {
    struct timespec deadline = make_deadline(timeout_millis);
    SCOPED_MUTEX(lock, &sink->lock);
    /* wait for the start */
    while (sink->num_messages < start + 1) {
       int r = ast_cond_timedwait(&sink->cond, &sink->lock, &deadline);
       if (r == ETIMEDOUT) {
          /* Timed out waiting for the start */
          return -1;
       }
       if (r != 0) {
          ast_log(LOG_ERROR, "Unexpected condition error: %s\n",
             strerror(r));
          return -2;
       }
    }
    while (!cmp_cb(sink->messages[start], data)) {
       ++start;
       while (sink->num_messages < start + 1) {
          int r = ast_cond_timedwait(&sink->cond,
             &sink->lock, &deadline);
          if (r == ETIMEDOUT) {
             return -1;
          }
          if (r != 0) {
             ast_log(LOG_ERROR,
                "Unexpected condition error: %s\n",
                strerror(r));
             return -2;
          }
       }
    }
    return start;
 }
stasis_message_sink_wait_for_count()
int stasis_message_sink_wait_for_count (struct stasis_message_sink * sink, int num_messages, int timeout_millis)
Wait for a sink's num_messages field to reach a certain level.
The optional timeout prevents complete deadlock in a test.
Parameters
sink Sink to wait on.
num_messages sink->num_messages value to wait for.
timeout_millis Number of milliseconds to wait. -1 to wait forever.
Returns
Actual sink->num_messages value at return. If this is < num_messages, then the timeout expired.
Definition at line 149 of file res_stasis_test.c.
References ast_cond_timedwait, ast_log, stasis_message_sink::cond, stasis_message_sink::lock, lock, LOG_ERROR, make_deadline(), stasis_message_sink::num_messages, and SCOPED_MUTEX.
Referenced by AST_TEST_DEFINE().
 {
    struct timespec deadline = make_deadline(timeout_millis);
    SCOPED_MUTEX(lock, &sink->lock);
    while (sink->num_messages < num_messages) {
       int r = ast_cond_timedwait(&sink->cond, &sink->lock, &deadline);
       if (r == ETIMEDOUT) {
          break;
       }
       if (r != 0) {
          ast_log(LOG_ERROR, "Unexpected condition error: %s\n",
             strerror(r));
          break;
       }
    }
    return sink->num_messages;
 }
STASIS_MESSAGE_TYPE_DEFN()
STASIS_MESSAGE_TYPE_DEFN (stasis_test_message_type)
unload_module()
static int unload_module (void) static
Definition at line 253 of file res_stasis_test.c.
References STASIS_MESSAGE_TYPE_CLEANUP, and stasis_test_message_type().
Referenced by load_module().
 {
    STASIS_MESSAGE_TYPE_CLEANUP(stasis_test_message_type);
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_GLOBAL_SYMBOLS | AST_MODFLAG_LOAD_ORDER , .description = "Stasis test utilities" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_APP_DEPEND, } static
Definition at line 273 of file res_stasis_test.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 273 of file res_stasis_test.c.