Asterisk - The Open Source Telephony Project: dns.h File Reference
dns.h File Reference
DNS support for Asterisk.
Enumerations
enum ast_dns_search_result { AST_DNS_SEARCH_FAILURE = -1, AST_DNS_SEARCH_NO_RECORDS = 0, AST_DNS_SEARCH_SUCCESS = 1 }
DNS search return values.
Functions
struct ao2_container * ast_dns_get_nameservers (void)
Retrieve the configured nameservers of the system.
int ast_search_dns (void *context, const char *dname, int class, int type, int(*callback)(void *context, unsigned char *answer, int len, unsigned char *fullanswer))
Perform DNS lookup (used by DNS, enum and SRV lookups)
enum ast_dns_search_result ast_search_dns_ex (void *context, const char *dname, int rr_class, int rr_type, int(*response_handler)(void *context, unsigned char *dns_response, int dns_response_len, int rcode), int(*record_handler)(void *context, unsigned char *record, int record_len, int ttl))
Extended version of the DNS search function.
Detailed Description
DNS support for Asterisk.
Author
Thorsten Lockert tholo.nosp@m.@tro.nosp@m.llpho.nosp@m.ne.o.nosp@m.rg
Definition in file dns.h.
Enumeration Type Documentation
ast_dns_search_result
enum ast_dns_search_result
DNS search return values.
Enumerator
AST_DNS_SEARCH_FAILURE
DNS search resulted in failure
AST_DNS_SEARCH_NO_RECORDS
DNS search yielded no results
AST_DNS_SEARCH_SUCCESS
DNS search yielded at least one discovered record
Definition at line 28 of file dns.h.
{
    AST_DNS_SEARCH_FAILURE = -1,     /*!< DNS search resulted in failure */
    AST_DNS_SEARCH_NO_RECORDS = 0,   /*!< DNS search yielded no results */
    AST_DNS_SEARCH_SUCCESS = 1       /*!< DNS search yielded at least one discovered record */
 };
Function Documentation
ast_dns_get_nameservers()
struct ao2_container* ast_dns_get_nameservers (void)
Retrieve the configured nameservers of the system.
Definition at line 583 of file dns.c.
References AO2_ALLOC_OPT_LOCK_NOLOCK, ast_inet_ntoa(), ast_mutex_lock, ast_mutex_unlock, ast_str_container_add(), ast_str_container_alloc_options(), NULL, and state.
Referenced by system_create_resolver_and_set_nameservers().
 {
 #ifdef HAVE_RES_NINIT
    struct __res_state dnsstate;
 #endif
    struct __res_state *state;
    struct ao2_container *nameservers;
    int i;
    nameservers = ast_str_container_alloc_options(AO2_ALLOC_OPT_LOCK_NOLOCK, 3);
    if (!nameservers) {
       return NULL;
    }
 #ifdef HAVE_RES_NINIT
    memset(&dnsstate, 0, sizeof(dnsstate));
    res_ninit(&dnsstate);
    state = &dnsstate;
 #else
    ast_mutex_lock(&res_lock);
    res_init();
    state = &_res;
 #endif
    for (i = 0; i < state->nscount; i++) {
       ast_str_container_add(nameservers, ast_inet_ntoa(state->nsaddr_list[i].sin_addr));
    }
 #ifdef HAVE_RES_NINIT
 #ifdef HAVE_RES_NDESTROY
    res_ndestroy(&dnsstate);
 #else
    res_nclose(&dnsstate);
 #endif
 #else
 #ifdef HAVE_RES_CLOSE
    res_close();
 #endif
    ast_mutex_unlock(&res_lock);
 #endif
    return nameservers;
 }
ast_search_dns()
int ast_search_dns (void * context, const char * dname, int class, int type, int(*)(void *context, unsigned char *answer, int len, unsigned char *fullanswer) callback)
Perform DNS lookup (used by DNS, enum and SRV lookups)
Parameters
context Void pointer containing data to use in the callback function.
dname Domain name to lookup (host, SRV domain, TXT record name).
class Record Class (see "man res_search").
type Record type (see "man res_search").
answer The full DNS response.
len The length of the full DNS response.
callback Callback function for handling the discovered resource records from the DNS search.
Return values
-1 on search failure
0 on no records found
1 on success
Note
Asterisk DNS is synchronus at this time. This means that if your DNS service does not work, Asterisk may lock while waiting for a response.
Perform DNS lookup (used by DNS, enum and SRV lookups)
Note
Asterisk DNS is synchronus at this time. This means that if your DNS does not work properly, Asterisk might not start properly or a channel may lock.
Definition at line 493 of file dns.c.
References ast_debug, ast_log, ast_mutex_lock, ast_mutex_unlock, dns_parse_answer(), LOG_WARNING, and MAX_SIZE.
Referenced by ast_get_enum(), ast_get_srv(), ast_get_txt(), ast_srv_lookup(), blr_ebl(), and blr_txt().
 {
 #ifdef HAVE_RES_NINIT
    struct __res_state dnsstate;
 #endif
    unsigned char answer[MAX_SIZE];
    int res, ret = -1;
 #ifdef HAVE_RES_NINIT
    memset(&dnsstate, 0, sizeof(dnsstate));
    res_ninit(&dnsstate);
    res = res_nsearch(&dnsstate, dname, class, type, answer, sizeof(answer));
 #else
    ast_mutex_lock(&res_lock);
    res_init();
    res = res_search(dname, class, type, answer, sizeof(answer));
 #endif
    if (res > 0) {
       if ((res = dns_parse_answer(context, class, type, answer, res, callback)) < 0) {
          ast_log(LOG_WARNING, "DNS Parse error for %s\n", dname);
          ret = -1;
       } else if (res == 0) {
          ast_debug(1, "No matches found in DNS for %s\n", dname);
          ret = 0;
       } else
          ret = 1;
    }
 #ifdef HAVE_RES_NINIT
 #ifdef HAVE_RES_NDESTROY
    res_ndestroy(&dnsstate);
 #else
    res_nclose(&dnsstate);
 #endif
 #else
 #ifdef HAVE_RES_CLOSE
    res_close();
 #endif
    ast_mutex_unlock(&res_lock);
 #endif
    return ret;
 }
ast_search_dns_ex()
enum ast_dns_search_result ast_search_dns_ex (void * context, const char * dname, int rr_class, int rr_type, int(*)(void *context, unsigned char *dns_response, int dns_response_len, int rcode) response_handler, int(*)(void *context, unsigned char *record, int record_len, int ttl) record_handler)
Extended version of the DNS search function.
Performs a DNS lookup, (used by DNS, enum and SRV lookups), parses the results and notifies the observer with the response and discovered records via invoking the provided callbacks (used by ast_dns_system_resolver).
Parameters
context Void pointer containing data to use in the handler functions.
dname Domain name to lookup (host, SRV domain, TXT record name).
rr_class Record Class (see "man res_search").
rr_type Record type (see "man res_search").
response_handler Callback function for handling the DNS response. Invoked upon completion of the DNS search.
record_handler Callback function for handling the discovered resource records from the DNS search. Invoked n times, where n is the number of records discovered while parsing the DNS response.
Return values
AST_DNS_SEARCH_FAILURE on search failure
AST_DNS_SEARCH_NO_RECORDS on no records found
AST_DNS_SEARCH_SUCCESS on success
Note
Asterisk DNS is synchronus at this time. This means that if your DNS service does not work, Asterisk may lock while waiting for a response.
Definition at line 538 of file dns.c.
References ast_assert, ast_debug, AST_DNS_SEARCH_FAILURE, AST_DNS_SEARCH_NO_RECORDS, ast_log, dns_parse_answer_ex(), dns_search_res(), LOG_WARNING, MAX_SIZE, and NULL.
Referenced by dns_system_resolver_process_query().
 {
    int ret, dns_response_len;
    unsigned char dns_response[MAX_SIZE];
    /* Assert that the callbacks are not NULL */
    ast_assert(response_handler != NULL);
    ast_assert(record_handler != NULL);
    /* Try the DNS search. */
    dns_response_len = dns_search_res(dname,
                                      rr_class,
                                      rr_type,
                                      dns_response,
                                      sizeof(dns_response));
    if (dns_response_len < 0) {
       ast_debug(1, "DNS search failed for %s\n", dname);
       response_handler(context, (unsigned char *)"", 0, NXDOMAIN);
       return AST_DNS_SEARCH_FAILURE;
    }
    /* Parse records from DNS response */
    ret = dns_parse_answer_ex(context,
                              rr_class,
                              rr_type,
                              dns_response,
                              dns_response_len,
                              response_handler,
                              record_handler);
    /* Handle the return code from parsing the DNS response */
    if (ret == AST_DNS_SEARCH_FAILURE) {
       /* Parsing Error */
       ast_log(LOG_WARNING, "DNS Parse error for %s\n", dname);
    } else if (ret == AST_DNS_SEARCH_NO_RECORDS) {
       /* No results found */
       ast_debug(1, "DNS search yielded no results for %s\n", dname);
    }
    return ret;
 }