Asterisk - The Open Source Telephony Project: misdn_lib_iface Struct Reference
misdn_lib_iface Struct Reference
#include <isdn_lib.h>
Data Fields
enum event_response_e(* cb_event)(enum event_e event, struct misdn_bchannel *bc, void *user_data)
int(* cb_jb_empty)(struct misdn_bchannel *bc, char *buffer, int len)
void(* cb_log)(int level, int port, char *tmpl,...)
Detailed Description
Definition at line 728 of file isdn_lib.h.
Field Documentation
cb_event
enum event_response_e(* cb_event) (enum event_e event, struct misdn_bchannel *bc, void *user_data)
Definition at line 729 of file isdn_lib.h.
Referenced by load_module(), and misdn_lib_init().
cb_jb_empty
int(* cb_jb_empty) (struct misdn_bchannel *bc, char *buffer, int len)
Definition at line 732 of file isdn_lib.h.
Referenced by misdn_lib_init().
cb_log
void(* cb_log) (int level, int port, char *tmpl,...)
Definition at line 730 of file isdn_lib.h.
Referenced by misdn_lib_init().
The documentation for this struct was generated from the following file:
isdn_lib.h