Asterisk - The Open Source Telephony Project: resource_recordings.c File Reference
resource_recordings.c File Reference
/api-docs/recordings.{format} implementation- Recording resources
#include "asterisk.h"
#include "asterisk/stasis_app_recording.h"
#include "resource_recordings.h"
Functions
void ast_ari_recordings_cancel (struct ast_variable *headers, struct ast_ari_recordings_cancel_args *args, struct ast_ari_response *response)
Stop a live recording and discard it.
void ast_ari_recordings_copy_stored (struct ast_variable *headers, struct ast_ari_recordings_copy_stored_args *args, struct ast_ari_response *response)
Copy a stored recording.
void ast_ari_recordings_delete_stored (struct ast_variable *headers, struct ast_ari_recordings_delete_stored_args *args, struct ast_ari_response *response)
Delete a stored recording.
void ast_ari_recordings_get_live (struct ast_variable *headers, struct ast_ari_recordings_get_live_args *args, struct ast_ari_response *response)
List live recordings.
void ast_ari_recordings_get_stored (struct ast_variable *headers, struct ast_ari_recordings_get_stored_args *args, struct ast_ari_response *response)
Get a stored recording's details.
void ast_ari_recordings_get_stored_file (struct ast_tcptls_session_instance *ser, struct ast_variable *headers, struct ast_ari_recordings_get_stored_file_args *args, struct ast_ari_response *response)
Get the file associated with the stored recording.
void ast_ari_recordings_list_stored (struct ast_variable *headers, struct ast_ari_recordings_list_stored_args *args, struct ast_ari_response *response)
List recordings that are complete.
void ast_ari_recordings_mute (struct ast_variable *headers, struct ast_ari_recordings_mute_args *args, struct ast_ari_response *response)
Mute a live recording.
void ast_ari_recordings_pause (struct ast_variable *headers, struct ast_ari_recordings_pause_args *args, struct ast_ari_response *response)
Pause a live recording.
void ast_ari_recordings_stop (struct ast_variable *headers, struct ast_ari_recordings_stop_args *args, struct ast_ari_response *response)
Stop a live recording and store it.
void ast_ari_recordings_unmute (struct ast_variable *headers, struct ast_ari_recordings_unmute_args *args, struct ast_ari_response *response)
Unmute a live recording.
void ast_ari_recordings_unpause (struct ast_variable *headers, struct ast_ari_recordings_unpause_args *args, struct ast_ari_response *response)
Unpause a live recording.
static void control_recording (const char *name, enum stasis_app_recording_media_operation operation, struct ast_ari_response *response)
Detailed Description
/api-docs/recordings.{format} implementation- Recording resources
Author
David M. Lee, II dlee@.nosp@m.digi.nosp@m.um.co.nosp@m.m
Definition in file resource_recordings.c.
Function Documentation
ast_ari_recordings_cancel()
void ast_ari_recordings_cancel (struct ast_variable * headers, struct ast_ari_recordings_cancel_args * args, struct ast_ari_response * response)
Stop a live recording and discard it.
Parameters
headers HTTP headers
args Swagger parameters
[out] response HTTP response
Definition at line 313 of file resource_recordings.c.
References control_recording(), ast_ari_recordings_cancel_args::recording_name, and STASIS_APP_RECORDING_CANCEL.
Referenced by ast_ari_recordings_cancel_cb().
 {
    control_recording(args->recording_name, STASIS_APP_RECORDING_CANCEL,
       response);
 }
ast_ari_recordings_copy_stored()
void ast_ari_recordings_copy_stored (struct ast_variable * headers, struct ast_ari_recordings_copy_stored_args * args, struct ast_ari_response * response)
Copy a stored recording.
Parameters
headers HTTP headers
args Swagger parameters
[out] response HTTP response
Definition at line 145 of file resource_recordings.c.
References ao2_cleanup, ast_ari_response_error(), ast_ari_response_ok(), ast_log, ast_ari_recordings_copy_stored_args::destination_recording_name, errno, LOG_WARNING, NULL, RAII_VAR, ast_ari_recordings_copy_stored_args::recording_name, stasis_app_stored_recording_copy(), stasis_app_stored_recording_find_by_name(), and stasis_app_stored_recording_to_json().
Referenced by ast_ari_recordings_copy_stored_cb().
 {
    RAII_VAR(struct stasis_app_stored_recording *, src_recording, NULL,
       ao2_cleanup);
    RAII_VAR(struct stasis_app_stored_recording *, dst_recording, NULL,
       ao2_cleanup);
    struct ast_json *json;
    int res;
    src_recording = stasis_app_stored_recording_find_by_name(
       args->recording_name);
    if (src_recording == NULL) {
       ast_ari_response_error(response, 404, "Not Found",
          "Recording not found");
       return;
    }
    dst_recording = stasis_app_stored_recording_find_by_name(
       args->destination_recording_name);
    if (dst_recording) {
       ast_ari_response_error(response, 409, "Conflict",
          "A recording with the same name already exists on the system");
       return;
    }
    /* See if we got our name rejected */
    switch (errno) {
    case EINVAL:
       ast_ari_response_error(response, 400, "Bad request",
          "Invalid destination recording name");
       return;
    case EACCES:
       ast_ari_response_error(response, 403, "Forbidden",
          "Destination file path is forbidden");
       return;
    default:
       break;
    }
    res = stasis_app_stored_recording_copy(src_recording,
       args->destination_recording_name, &dst_recording);
    if (res) {
       switch (errno) {
       case EACCES:
       case EPERM:
          ast_ari_response_error(response, 500,
             "Internal Server Error",
             "Copy failed");
          break;
       default:
          ast_log(LOG_WARNING,
             "Unexpected error copying recording %s to %s: %s\n",
             args->recording_name, args->destination_recording_name, strerror(errno));
          ast_ari_response_error(response, 500,
             "Internal Server Error",
             "Copy failed");
          break;
       }
       return;
    }
    json = stasis_app_stored_recording_to_json(dst_recording);
    if (json == NULL) {
       ast_ari_response_error(response, 500,
          "Internal Server Error", "Error building response");
       return;
    }
    ast_ari_response_ok(response, json);
 }
ast_ari_recordings_delete_stored()
void ast_ari_recordings_delete_stored (struct ast_variable * headers, struct ast_ari_recordings_delete_stored_args * args, struct ast_ari_response * response)
Delete a stored recording.
Parameters
headers HTTP headers
args Swagger parameters
[out] response HTTP response
Definition at line 218 of file resource_recordings.c.
References ao2_cleanup, ast_ari_response_error(), ast_ari_response_no_content(), ast_log, errno, LOG_WARNING, NULL, RAII_VAR, ast_ari_recordings_delete_stored_args::recording_name, stasis_app_stored_recording_delete(), and stasis_app_stored_recording_find_by_name().
Referenced by ast_ari_recordings_delete_stored_cb().
 {
    RAII_VAR(struct stasis_app_stored_recording *, recording, NULL,
       ao2_cleanup);
    int res;
    recording = stasis_app_stored_recording_find_by_name(
       args->recording_name);
    if (recording == NULL) {
       ast_ari_response_error(response, 404, "Not Found",
          "Recording not found");
       return;
    }
    res = stasis_app_stored_recording_delete(recording);
    if (res != 0) {
       switch (errno) {
       case EACCES:
       case EPERM:
          ast_ari_response_error(response, 500,
             "Internal Server Error",
             "Delete failed");
          break;
       default:
          ast_log(LOG_WARNING,
             "Unexpected error deleting recording %s: %s\n",
             args->recording_name, strerror(errno));
          ast_ari_response_error(response, 500,
             "Internal Server Error",
             "Delete failed");
          break;
       }
       return;
    }
    ast_ari_response_no_content(response);
 }
ast_ari_recordings_get_live()
void ast_ari_recordings_get_live (struct ast_variable * headers, struct ast_ari_recordings_get_live_args * args, struct ast_ari_response * response)
List live recordings.
Parameters
headers HTTP headers
args Swagger parameters
[out] response HTTP response
Definition at line 259 of file resource_recordings.c.
References ao2_cleanup, ast_ari_response_error(), ast_ari_response_ok(), NULL, RAII_VAR, ast_ari_recordings_get_live_args::recording_name, stasis_app_recording_find_by_name(), and stasis_app_recording_to_json().
Referenced by ast_ari_recordings_get_live_cb().
 {
    RAII_VAR(struct stasis_app_recording *, recording, NULL, ao2_cleanup);
    struct ast_json *json;
    recording = stasis_app_recording_find_by_name(args->recording_name);
    if (recording == NULL) {
       ast_ari_response_error(response, 404, "Not Found",
          "Recording not found");
       return;
    }
    json = stasis_app_recording_to_json(recording);
    if (json == NULL) {
       ast_ari_response_error(response, 500,
          "Internal Server Error", "Error building response");
       return;
    }
    ast_ari_response_ok(response, json);
 }
ast_ari_recordings_get_stored()
void ast_ari_recordings_get_stored (struct ast_variable * headers, struct ast_ari_recordings_get_stored_args * args, struct ast_ari_response * response)
Get a stored recording's details.
Parameters
headers HTTP headers
args Swagger parameters
[out] response HTTP response
Definition at line 75 of file resource_recordings.c.
References ao2_cleanup, ast_ari_response_error(), ast_ari_response_ok(), NULL, RAII_VAR, ast_ari_recordings_get_stored_args::recording_name, stasis_app_stored_recording_find_by_name(), and stasis_app_stored_recording_to_json().
Referenced by ast_ari_recordings_get_stored_cb().
 {
    RAII_VAR(struct stasis_app_stored_recording *, recording, NULL,
       ao2_cleanup);
    struct ast_json *json;
    recording = stasis_app_stored_recording_find_by_name(
       args->recording_name);
    if (recording == NULL) {
       ast_ari_response_error(response, 404, "Not Found",
          "Recording not found");
       return;
    }
    json = stasis_app_stored_recording_to_json(recording);
    if (json == NULL) {
       ast_ari_response_error(response, 500,
          "Internal Server Error", "Error building response");
       return;
    }
    ast_ari_response_ok(response, json);
 }
ast_ari_recordings_get_stored_file()
void ast_ari_recordings_get_stored_file (struct ast_tcptls_session_instance * ser, struct ast_variable * headers, struct ast_ari_recordings_get_stored_file_args * args, struct ast_ari_response * response)
Get the file associated with the stored recording.
Parameters
ser TCP/TLS session instance
headers HTTP headers
args Swagger parameters
[out] response HTTP response
Definition at line 101 of file resource_recordings.c.
References ao2_cleanup, ast_ari_response_error(), ast_ari_response_ok(), ast_format_get_type(), ast_get_format_for_file_ext(), ast_json_null(), AST_MEDIA_TYPE_AUDIO, AST_MEDIA_TYPE_IMAGE, AST_MEDIA_TYPE_TEXT, AST_MEDIA_TYPE_UNKNOWN, AST_MEDIA_TYPE_VIDEO, ast_str_append(), ast_ari_response::fd, format, ast_ari_response::headers, ast_ari_response::message, RAII_VAR, ast_ari_recordings_get_stored_file_args::recording_name, stasis_app_stored_recording_find_by_name(), stasis_app_stored_recording_get_extension(), and stasis_app_stored_recording_get_filename().
Referenced by ast_ari_recordings_get_stored_file_cb().
 {
    RAII_VAR(struct stasis_app_stored_recording *, recording,
       stasis_app_stored_recording_find_by_name(args->recording_name),
       ao2_cleanup);
    static const char *format_type_names[AST_MEDIA_TYPE_TEXT + 1] = {
       [AST_MEDIA_TYPE_UNKNOWN] = "binary",
       [AST_MEDIA_TYPE_AUDIO] = "audio",
       [AST_MEDIA_TYPE_VIDEO] = "video",
       [AST_MEDIA_TYPE_IMAGE] = "image",
       [AST_MEDIA_TYPE_TEXT] = "text",
    };
    struct ast_format *format;
    response->message = ast_json_null();
    if (!recording) {
       ast_ari_response_error(response, 404, "Not Found",
          "Recording not found");
       return;
    }
    format = ast_get_format_for_file_ext(stasis_app_stored_recording_get_extension(recording));
    if (!format) {
       ast_ari_response_error(response, 500, "Internal Server Error",
          "Format specified by recording not available or loaded");
       return;
    }
    response->fd = open(stasis_app_stored_recording_get_filename(recording), O_RDONLY);
    if (response->fd < 0) {
       ast_ari_response_error(response, 403, "Forbidden",
          "Recording could not be opened");
       return;
    }
    ast_str_append(&response->headers, 0, "Content-Type: %s/%s\r\n",
       format_type_names[ast_format_get_type(format)],
       stasis_app_stored_recording_get_extension(recording));
    ast_ari_response_ok(response, ast_json_null());
 }
ast_ari_recordings_list_stored()
void ast_ari_recordings_list_stored (struct ast_variable * headers, struct ast_ari_recordings_list_stored_args * args, struct ast_ari_response * response)
List recordings that are complete.
Parameters
headers HTTP headers
args Swagger parameters
[out] response HTTP response
Definition at line 35 of file resource_recordings.c.
References ao2_cleanup, ao2_iterator_destroy(), ao2_iterator_init(), ao2_iterator_next, ast_ari_response_alloc_failed(), ast_ari_response_ok(), ast_json_array_append(), ast_json_array_create(), ast_json_ref(), ast_json_unref(), NULL, RAII_VAR, recordings, stasis_app_stored_recording_find_all(), and stasis_app_stored_recording_to_json().
Referenced by ast_ari_recordings_list_stored_cb().
 {
    RAII_VAR(struct ao2_container *, recordings, NULL, ao2_cleanup);
    RAII_VAR(struct ast_json *, json, NULL, ast_json_unref);
    struct ao2_iterator i;
    void *obj;
    recordings = stasis_app_stored_recording_find_all();
    if (!recordings) {
       ast_ari_response_alloc_failed(response);
       return;
    }
    json = ast_json_array_create();
    if (!json) {
       ast_ari_response_alloc_failed(response);
       return;
    }
    i = ao2_iterator_init(recordings, 0);
    while ((obj = ao2_iterator_next(&i))) {
       RAII_VAR(struct stasis_app_stored_recording *, recording, obj,
          ao2_cleanup);
       int r = ast_json_array_append(
          json, stasis_app_stored_recording_to_json(recording));
       if (r != 0) {
          ast_ari_response_alloc_failed(response);
          ao2_iterator_destroy(&i);
          return;
       }
    }
    ao2_iterator_destroy(&i);
    ast_ari_response_ok(response, ast_json_ref(json));
 }
ast_ari_recordings_mute()
void ast_ari_recordings_mute (struct ast_variable * headers, struct ast_ari_recordings_mute_args * args, struct ast_ari_response * response)
Mute a live recording.
Muting a recording suspends silence detection, which will be restarted when the recording is unmuted.
Parameters
headers HTTP headers
args Swagger parameters
[out] response HTTP response
Definition at line 345 of file resource_recordings.c.
References control_recording(), ast_ari_recordings_mute_args::recording_name, and STASIS_APP_RECORDING_MUTE.
Referenced by ast_ari_recordings_mute_cb().
 {
    control_recording(args->recording_name, STASIS_APP_RECORDING_MUTE,
       response);
 }
ast_ari_recordings_pause()
void ast_ari_recordings_pause (struct ast_variable * headers, struct ast_ari_recordings_pause_args * args, struct ast_ari_response * response)
Pause a live recording.
Pausing a recording suspends silence detection, which will be restarted when the recording is unpaused. Paused time is not included in the accounting for maxDurationSeconds.
Parameters
headers HTTP headers
args Swagger parameters
[out] response HTTP response
Definition at line 329 of file resource_recordings.c.
References control_recording(), ast_ari_recordings_pause_args::recording_name, and STASIS_APP_RECORDING_PAUSE.
Referenced by ast_ari_recordings_pause_cb().
 {
    control_recording(args->recording_name, STASIS_APP_RECORDING_PAUSE,
       response);
 }
ast_ari_recordings_stop()
void ast_ari_recordings_stop (struct ast_variable * headers, struct ast_ari_recordings_stop_args * args, struct ast_ari_response * response)
Stop a live recording and store it.
Parameters
headers HTTP headers
args Swagger parameters
[out] response HTTP response
Definition at line 321 of file resource_recordings.c.
References control_recording(), ast_ari_recordings_stop_args::recording_name, and STASIS_APP_RECORDING_STOP.
Referenced by ast_ari_recordings_stop_cb().
 {
    control_recording(args->recording_name, STASIS_APP_RECORDING_STOP,
       response);
 }
ast_ari_recordings_unmute()
void ast_ari_recordings_unmute (struct ast_variable * headers, struct ast_ari_recordings_unmute_args * args, struct ast_ari_response * response)
Unmute a live recording.
Parameters
headers HTTP headers
args Swagger parameters
[out] response HTTP response
Definition at line 353 of file resource_recordings.c.
References control_recording(), ast_ari_recordings_unmute_args::recording_name, and STASIS_APP_RECORDING_UNMUTE.
Referenced by ast_ari_recordings_unmute_cb().
 {
    control_recording(args->recording_name, STASIS_APP_RECORDING_UNMUTE,
       response);
 }
ast_ari_recordings_unpause()
void ast_ari_recordings_unpause (struct ast_variable * headers, struct ast_ari_recordings_unpause_args * args, struct ast_ari_response * response)
Unpause a live recording.
Parameters
headers HTTP headers
args Swagger parameters
[out] response HTTP response
Definition at line 337 of file resource_recordings.c.
References control_recording(), ast_ari_recordings_unpause_args::recording_name, and STASIS_APP_RECORDING_UNPAUSE.
Referenced by ast_ari_recordings_unpause_cb().
 {
    control_recording(args->recording_name, STASIS_APP_RECORDING_UNPAUSE,
       response);
 }
control_recording()
static void control_recording (const char * name, enum stasis_app_recording_media_operation operation, struct ast_ari_response * response) static
Definition at line 283 of file resource_recordings.c.
References ao2_cleanup, ast_ari_response_error(), ast_ari_response_no_content(), NULL, RAII_VAR, stasis_app_recording_find_by_name(), STASIS_APP_RECORDING_OPER_FAILED, STASIS_APP_RECORDING_OPER_NOT_RECORDING, STASIS_APP_RECORDING_OPER_OK, and stasis_app_recording_operation().
Referenced by ast_ari_recordings_cancel(), ast_ari_recordings_mute(), ast_ari_recordings_pause(), ast_ari_recordings_stop(), ast_ari_recordings_unmute(), and ast_ari_recordings_unpause().
 {
    RAII_VAR(struct stasis_app_recording *, recording, NULL, ao2_cleanup);
    enum stasis_app_recording_oper_results res;
    recording = stasis_app_recording_find_by_name(name);
    if (recording == NULL) {
       ast_ari_response_error(response, 404, "Not Found",
          "Recording not found");
       return;
    }
    res = stasis_app_recording_operation(recording, operation);
    switch (res) {
    case STASIS_APP_RECORDING_OPER_OK:
       ast_ari_response_no_content(response);
       return;
    case STASIS_APP_RECORDING_OPER_FAILED:
       ast_ari_response_error(response, 500,
          "Internal Server Error", "Recording operation failed");
       return;
    case STASIS_APP_RECORDING_OPER_NOT_RECORDING:
       ast_ari_response_error(response, 409,
          "Conflict", "Recording not in session");
    }
 }