Asterisk - The Open Source Telephony Project: LPCdecode.c File Reference
LPCdecode.c File Reference
#include <math.h>
#include <string.h>
#include "helpfun.h"
#include "lsf.h"
#include "iLBC_define.h"
#include "constants.h"
Functions
void DecoderInterpolateLSF (float *syntdenum, float *weightdenum, float *lsfdeq, int length, iLBC_Dec_Inst_t *iLBCdec_inst)
void LSFinterpolate2a_dec (float *a, float *lsf1, float *lsf2, float coef, int length)
void SimplelsfDEQ (float *lsfdeq, int *index, int lpc_n)
Function Documentation
DecoderInterpolateLSF()
void DecoderInterpolateLSF (float * syntdenum, float * weightdenum, float * lsfdeq, int length, iLBC_Dec_Inst_t * iLBCdec_inst)
Definition at line 89 of file LPCdecode.c.
References bwexpand(), LPC_CHIRP_WEIGHTDENUM, LPC_FILTERORDER, lsf_weightTbl_20ms, lsf_weightTbl_30ms, iLBC_Dec_Inst_t_::lsfdeqold, LSFinterpolate2a_dec(), iLBC_Dec_Inst_t_::mode, and iLBC_Dec_Inst_t_::nsub.
Referenced by iLBC_decode().
     {
        int    i, pos, lp_length;
        float  lp[LPC_FILTERORDER + 1], *lsfdeq2;
        lsfdeq2 = lsfdeq + length;
        lp_length = length + 1;
        if (iLBCdec_inst->mode==30) {
            /* sub-frame 1: Interpolation between old and first */
            LSFinterpolate2a_dec(lp, iLBCdec_inst->lsfdeqold, lsfdeq,
                lsf_weightTbl_30ms[0], length);
            memcpy(syntdenum,lp,lp_length*sizeof(float));
            bwexpand(weightdenum, lp, LPC_CHIRP_WEIGHTDENUM,
                lp_length);
            /* sub-frames 2 to 6: interpolation between first
               and last LSF */
            pos = lp_length;
            for (i = 1; i < 6; i++) {
                LSFinterpolate2a_dec(lp, lsfdeq, lsfdeq2,
                    lsf_weightTbl_30ms[i], length);
                memcpy(syntdenum + pos,lp,lp_length*sizeof(float));
                bwexpand(weightdenum + pos, lp,
                    LPC_CHIRP_WEIGHTDENUM, lp_length);
                pos += lp_length;
            }
        }
        else {
            pos = 0;
            for (i = 0; i < iLBCdec_inst->nsub; i++) {
                LSFinterpolate2a_dec(lp, iLBCdec_inst->lsfdeqold,
                    lsfdeq, lsf_weightTbl_20ms[i], length);
                memcpy(syntdenum+pos,lp,lp_length*sizeof(float));
                bwexpand(weightdenum+pos, lp, LPC_CHIRP_WEIGHTDENUM,
                    lp_length);
                pos += lp_length;
            }
        }
        /* update memory */
        if (iLBCdec_inst->mode==30)
            memcpy(iLBCdec_inst->lsfdeqold, lsfdeq2,
                        length*sizeof(float));
        else
            memcpy(iLBCdec_inst->lsfdeqold, lsfdeq,
                        length*sizeof(float));
    }
LSFinterpolate2a_dec()
void LSFinterpolate2a_dec (float * a, float * lsf1, float * lsf2, float coef, int length)
Definition at line 25 of file LPCdecode.c.
References interpolate(), LPC_FILTERORDER, and lsf2a().
Referenced by DecoderInterpolateLSF().
     {
        float  lsftmp[LPC_FILTERORDER];
        interpolate(lsftmp, lsf1, lsf2, coef, length);
        lsf2a(a, lsftmp);
    }
SimplelsfDEQ()
void SimplelsfDEQ (float * lsfdeq, int * index, int lpc_n)
Definition at line 42 of file LPCdecode.c.
References dim_lsfCbTbl, LPC_FILTERORDER, LSF_NSPLIT, lsfCbTbl, and size_lsfCbTbl.
Referenced by iLBC_decode().
     {
        int i, j, pos, cb_pos;
        /* decode first LSF */
        pos = 0;
        cb_pos = 0;
        for (i = 0; i < LSF_NSPLIT; i++) {
            for (j = 0; j < dim_lsfCbTbl[i]; j++) {
                lsfdeq[pos + j] = lsfCbTbl[cb_pos +
                    (long)(index[i])*dim_lsfCbTbl[i] + j];
            }
            pos += dim_lsfCbTbl[i];
            cb_pos += size_lsfCbTbl[i]*dim_lsfCbTbl[i];
        }
        if (lpc_n>1) {
            /* decode last LSF */
            pos = 0;
            cb_pos = 0;
            for (i = 0; i < LSF_NSPLIT; i++) {
                for (j = 0; j < dim_lsfCbTbl[i]; j++) {
                    lsfdeq[LPC_FILTERORDER + pos + j] =
                        lsfCbTbl[cb_pos +
                        (long)(index[LSF_NSPLIT + i])*
                        dim_lsfCbTbl[i] + j];
                }
                pos += dim_lsfCbTbl[i];
                cb_pos += size_lsfCbTbl[i]*dim_lsfCbTbl[i];
            }
        }
    }