Asterisk - The Open Source Telephony Project: res_rtp_multicast.c File Reference
res_rtp_multicast.c File Reference
Module: RTP Engines
Multicast RTP Engine.
#include "asterisk.h"
#include <sys/time.h>
#include <signal.h>
#include <fcntl.h>
#include <math.h>
#include "asterisk/pbx.h"
#include "asterisk/frame.h"
#include "asterisk/channel.h"
#include "asterisk/acl.h"
#include "asterisk/config.h"
#include "asterisk/lock.h"
#include "asterisk/utils.h"
#include "asterisk/cli.h"
#include "asterisk/manager.h"
#include "asterisk/unaligned.h"
#include "asterisk/module.h"
#include "asterisk/rtp_engine.h"
#include "asterisk/format_cache.h"
#include "asterisk/multicast_rtp.h"
#include "asterisk/app.h"
#include "asterisk/smoother.h"
Data Structures
struct ast_multicast_rtp_options
struct multicast_control_packet
Structure for a Linksys control packet.
struct multicast_rtp
Structure for a multicast paging instance.
Macros
#define LINKSYS_MCAST_STARTCMD 6
#define LINKSYS_MCAST_STOPCMD 7
#define MAX_TIMESTAMP_SKEW 640
Enumerations
enum { OPT_CODEC = (1 << 0), OPT_LOOP = (1 << 1), OPT_TTL = (1 << 2), OPT_IF = (1 << 3) }
enum {
OPT_ARG_CODEC = 0, OPT_ARG_LOOP, OPT_ARG_TTL, OPT_ARG_IF,
OPT_ARG_ARRAY_SIZE
}
enum multicast_type { MULTICAST_TYPE_UNSPECIFIED = 0, MULTICAST_TYPE_BASIC, MULTICAST_TYPE_LINKSYS }
Type of paging to do.
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
struct ast_multicast_rtp_options * ast_multicast_rtp_create_options (const char *type, const char *options)
Create multicast RTP options.
void ast_multicast_rtp_free_options (struct ast_multicast_rtp_options *mcast_options)
Free multicast RTP options.
struct ast_format * ast_multicast_rtp_options_get_format (struct ast_multicast_rtp_options *mcast_options)
Get format specified in multicast options.
static unsigned int calc_txstamp (struct multicast_rtp *rtp, struct timeval *delivery)
static int load_module (void)
static int multicast_rtp_activate (struct ast_rtp_instance *instance)
Function called to indicate that audio is now going to flow.
static int multicast_rtp_destroy (struct ast_rtp_instance *instance)
Function called to destroy a multicast instance.
static int multicast_rtp_new (struct ast_rtp_instance *instance, struct ast_sched_context *sched, struct ast_sockaddr *addr, void *data)
Function called to create a new multicast instance.
static struct ast_frame * multicast_rtp_read (struct ast_rtp_instance *instance, int rtcp)
Function called to read from a multicast instance.
static int multicast_rtp_write (struct ast_rtp_instance *instance, struct ast_frame *frame)
Function called to broadcast some audio on a multicast instance.
static int multicast_send_control_packet (struct ast_rtp_instance *instance, struct multicast_rtp *multicast, int command)
Helper function which populates a control packet with useful information and sends it.
static int rtp_get_rate (struct ast_format *format)
static int rtp_raw_write (struct ast_rtp_instance *instance, struct ast_frame *frame, int codec)
static void set_if (int sock, const char *if_str)
static void set_loop (int sock, const char *loop_str)
static void set_ttl (int sock, const char *ttl_str)
static int set_type (struct multicast_rtp *multicast, const char *type)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_GLOBAL_SYMBOLS | AST_MODFLAG_LOAD_ORDER , .description = "Multicast RTP Engine" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_CHANNEL_DEPEND, }
static const struct ast_module_info * ast_module_info = &__mod_info
static struct ast_rtp_engine multicast_rtp_engine
static const struct ast_app_option multicast_rtp_options [128] = { [ 'c' ] = { .flag = OPT_CODEC , .arg_index = OPT_ARG_CODEC + 1 }, [ 'l' ] = { .flag = OPT_LOOP , .arg_index = OPT_ARG_LOOP + 1 }, [ 't' ] = { .flag = OPT_TTL , .arg_index = OPT_ARG_TTL + 1 }, [ 'i' ] = { .flag = OPT_IF , .arg_index = OPT_ARG_IF + 1 }, }
Detailed Description
Multicast RTP Engine.
Author
Joshua Colp jcolp.nosp@m.@dig.nosp@m.ium.c.nosp@m.om
Andreas 'MacBrody' Brodmann andre.nosp@m.as.b.nosp@m.rodma.nosp@m.nn@g.nosp@m.mail..nosp@m.com
Definition in file res_rtp_multicast.c.
Macro Definition Documentation
LINKSYS_MCAST_STARTCMD
#define LINKSYS_MCAST_STARTCMD 6
Command value used for Linksys paging to indicate we are starting
Definition at line 60 of file res_rtp_multicast.c.
Referenced by multicast_rtp_activate().
LINKSYS_MCAST_STOPCMD
#define LINKSYS_MCAST_STOPCMD 7
Command value used for Linksys paging to indicate we are stopping
Definition at line 63 of file res_rtp_multicast.c.
Referenced by multicast_rtp_destroy().
MAX_TIMESTAMP_SKEW
#define MAX_TIMESTAMP_SKEW 640
Definition at line 102 of file res_rtp_multicast.c.
Referenced by rtp_raw_write().
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
OPT_CODEC
OPT_LOOP
OPT_TTL
OPT_IF
Definition at line 104 of file res_rtp_multicast.c.
      {
    OPT_CODEC = (1 << 0),
    OPT_LOOP =  (1 << 1),
    OPT_TTL =   (1 << 2),
    OPT_IF =    (1 << 3),
 };
anonymous enum
anonymous enum
Enumerator
OPT_ARG_CODEC
OPT_ARG_LOOP
OPT_ARG_TTL
OPT_ARG_IF
OPT_ARG_ARRAY_SIZE
Definition at line 111 of file res_rtp_multicast.c.
      {
    OPT_ARG_CODEC = 0,
    OPT_ARG_LOOP,
    OPT_ARG_TTL,
    OPT_ARG_IF,
    OPT_ARG_ARRAY_SIZE,
 };
multicast_type
enum multicast_type
Type of paging to do.
Enumerator
MULTICAST_TYPE_UNSPECIFIED
Type has not been set yet
MULTICAST_TYPE_BASIC
Simple multicast enabled client/receiver paging like Snom and Barix uses
MULTICAST_TYPE_LINKSYS
More advanced Linksys type paging which requires a start and stop packet
Definition at line 66 of file res_rtp_multicast.c.
                     {
    /*! Type has not been set yet */
    MULTICAST_TYPE_UNSPECIFIED = 0,
    /*! Simple multicast enabled client/receiver paging like Snom and Barix uses */
    MULTICAST_TYPE_BASIC,
    /*! More advanced Linksys type paging which requires a start and stop packet */
    MULTICAST_TYPE_LINKSYS,
 };
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 567 of file res_rtp_multicast.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 567 of file res_rtp_multicast.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 567 of file res_rtp_multicast.c.
ast_multicast_rtp_create_options()
struct ast_multicast_rtp_options* ast_multicast_rtp_create_options (const char * type, const char * options)
Create multicast RTP options.
These are passed to the multicast RTP engine on its creation.
Parameters
type The type of multicast RTP, either "basic" or "linksys"
options Miscellaneous options
Return values
NULL Failure
non-NULL success
Definition at line 140 of file res_rtp_multicast.c.
References ast_app_parse_options(), ast_calloc, ast_log, ast_multicast_rtp_free_options(), ast_strlen_zero, ast_multicast_rtp_options::buf, LOG_WARNING, multicast_rtp_options, NULL, ast_multicast_rtp_options::opt_args, ast_multicast_rtp_options::options, ast_multicast_rtp_options::opts, S_OR, and ast_multicast_rtp_options::type.
Referenced by multicast_rtp_request().
 {
    struct ast_multicast_rtp_options *mcast_options;
    char *pos;
    mcast_options = ast_calloc(1, sizeof(*mcast_options)
          + strlen(type)
          + strlen(S_OR(options, "")) + 2);
    if (!mcast_options) {
       return NULL;
    }
    pos = mcast_options->buf;
    /* Safe */
    strcpy(pos, type);
    mcast_options->type = pos;
    pos += strlen(type) + 1;
    if (!ast_strlen_zero(options)) {
       strcpy(pos, options); /* Safe */
    }
    mcast_options->options = pos;
    if (ast_app_parse_options(multicast_rtp_options, &mcast_options->opts,
       mcast_options->opt_args, mcast_options->options)) {
       ast_log(LOG_WARNING, "Error parsing multicast RTP options\n");
       ast_multicast_rtp_free_options(mcast_options);
       return NULL;
    }
    return mcast_options;
 }
ast_multicast_rtp_free_options()
void ast_multicast_rtp_free_options (struct ast_multicast_rtp_options * mcast_options)
Free multicast RTP options.
This function is NULL-tolerant
Parameters
mcast_options Options to free
Definition at line 175 of file res_rtp_multicast.c.
References ast_free.
Referenced by ast_multicast_rtp_create_options(), and multicast_rtp_request().
 {
    ast_free(mcast_options);
 }
ast_multicast_rtp_options_get_format()
struct ast_format* ast_multicast_rtp_options_get_format (struct ast_multicast_rtp_options * mcast_options)
Get format specified in multicast options.
Multicast options allow for a format to be selected. This function accesses the selected format and creates an ast_format structure for it.
Parameters
mcast_options The options where a codec was specified
Return values
NULL No format specified in the options non-NULL The format to use for communication
Definition at line 180 of file res_rtp_multicast.c.
References ast_format_cache_get, ast_strlen_zero, ast_test_flag, multicast_rtp_activate(), multicast_rtp_destroy(), multicast_rtp_new(), multicast_rtp_read(), multicast_rtp_write(), NULL, OPT_ARG_CODEC, ast_multicast_rtp_options::opt_args, OPT_CODEC, and ast_multicast_rtp_options::opts.
Referenced by multicast_rtp_request().
 {
    if (ast_test_flag(&mcast_options->opts, OPT_CODEC)
       && !ast_strlen_zero(mcast_options->opt_args[OPT_ARG_CODEC])) {
       return ast_format_cache_get(mcast_options->opt_args[OPT_ARG_CODEC]);
    }
    return NULL;
 }
calc_txstamp()
static unsigned int calc_txstamp (struct multicast_rtp * rtp, struct timeval * delivery) static
Definition at line 328 of file res_rtp_multicast.c.
References ast_tvdiff_ms(), ast_tvnow(), ast_tvzero(), and multicast_rtp::txcore.
Referenced by rtp_raw_write().
 {
         struct timeval t;
         long ms;
         if (ast_tvzero(rtp->txcore)) {
                 rtp->txcore = ast_tvnow();
                 rtp->txcore.tv_usec -= rtp->txcore.tv_usec % 20000;
         }
         t = (delivery && !ast_tvzero(*delivery)) ? *delivery : ast_tvnow();
         if ((ms = ast_tvdiff_ms(t, rtp->txcore)) < 0) {
                 ms = 0;
         }
         rtp->txcore = t;
         return (unsigned int) ms;
 }
load_module()
static int load_module (void) static
Definition at line 546 of file res_rtp_multicast.c.
References AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, and ast_rtp_engine_register.
Referenced by unload_module().
 {
    if (ast_rtp_engine_register(&multicast_rtp_engine)) {
       return AST_MODULE_LOAD_DECLINE;
    }
    return AST_MODULE_LOAD_SUCCESS;
 }
multicast_rtp_activate()
static int multicast_rtp_activate (struct ast_rtp_instance * instance) static
Function called to indicate that audio is now going to flow.
Definition at line 382 of file res_rtp_multicast.c.
References ast_rtp_instance_get_data(), LINKSYS_MCAST_STARTCMD, multicast_send_control_packet(), MULTICAST_TYPE_LINKSYS, and multicast_rtp::type.
Referenced by ast_multicast_rtp_options_get_format().
 {
    struct multicast_rtp *multicast = ast_rtp_instance_get_data(instance);
    if (multicast->type != MULTICAST_TYPE_LINKSYS) {
       return 0;
    }
    return multicast_send_control_packet(instance, multicast, LINKSYS_MCAST_STARTCMD);
 }
multicast_rtp_destroy()
static int multicast_rtp_destroy (struct ast_rtp_instance * instance) static
Function called to destroy a multicast instance.
Definition at line 394 of file res_rtp_multicast.c.
References ast_free, ast_rtp_instance_get_data(), ast_smoother_free(), LINKSYS_MCAST_STOPCMD, multicast_send_control_packet(), MULTICAST_TYPE_LINKSYS, multicast_rtp::smoother, multicast_rtp::socket, and multicast_rtp::type.
Referenced by ast_multicast_rtp_options_get_format().
 {
    struct multicast_rtp *multicast = ast_rtp_instance_get_data(instance);
    if (multicast->type == MULTICAST_TYPE_LINKSYS) {
       multicast_send_control_packet(instance, multicast, LINKSYS_MCAST_STOPCMD);
    }
    if (multicast->smoother) {
       ast_smoother_free(multicast->smoother);
    }
    close(multicast->socket);
    ast_free(multicast);
    return 0;
 }
multicast_rtp_new()
static int multicast_rtp_new (struct ast_rtp_instance * instance, struct ast_sched_context * sched, struct ast_sockaddr * addr, void * data) static
Function called to create a new multicast instance.
Definition at line 284 of file res_rtp_multicast.c.
References ast_calloc, ast_free, ast_random(), ast_rtp_instance_set_data(), ast_test_flag, OPT_ARG_IF, OPT_ARG_LOOP, OPT_ARG_TTL, ast_multicast_rtp_options::opt_args, OPT_IF, OPT_LOOP, OPT_TTL, ast_multicast_rtp_options::opts, set_if(), set_loop(), set_ttl(), set_type(), multicast_rtp::socket, multicast_rtp::ssrc, and ast_multicast_rtp_options::type.
Referenced by ast_multicast_rtp_options_get_format().
 {
    struct multicast_rtp *multicast;
    struct ast_multicast_rtp_options *mcast_options = data;
    if (!(multicast = ast_calloc(1, sizeof(*multicast)))) {
       return -1;
    }
    if (set_type(multicast, mcast_options->type)) {
       ast_free(multicast);
       return -1;
    }
    if ((multicast->socket = socket(AF_INET, SOCK_DGRAM, 0)) < 0) {
       ast_free(multicast);
       return -1;
    }
    if (ast_test_flag(&mcast_options->opts, OPT_LOOP)) {
       set_loop(multicast->socket, mcast_options->opt_args[OPT_ARG_LOOP]);
    }
    if (ast_test_flag(&mcast_options->opts, OPT_TTL)) {
       set_ttl(multicast->socket, mcast_options->opt_args[OPT_ARG_TTL]);
    }
    if (ast_test_flag(&mcast_options->opts, OPT_IF)) {
       set_if(multicast->socket, mcast_options->opt_args[OPT_ARG_IF]);
    }
    multicast->ssrc = ast_random();
    ast_rtp_instance_set_data(instance, multicast);
    return 0;
 }
multicast_rtp_read()
static struct ast_frame * multicast_rtp_read (struct ast_rtp_instance * instance, int rtcp) static
Function called to read from a multicast instance.
Definition at line 541 of file res_rtp_multicast.c.
References ast_null_frame.
Referenced by ast_multicast_rtp_options_get_format().
 {
    return &ast_null_frame;
 }
multicast_rtp_write()
static int multicast_rtp_write (struct ast_rtp_instance * instance, struct ast_frame * frame) static
Function called to broadcast some audio on a multicast instance.
Definition at line 469 of file res_rtp_multicast.c.
References ast_format_can_be_smoothed(), ast_format_get_default_ms(), ast_format_get_minimum_bytes(), ast_format_get_minimum_ms(), ast_format_get_name(), ast_format_get_smoother_flags(), AST_FRAME_VOICE, ast_frdup, ast_frfree, ast_log, ast_rtp_codecs_get_framing(), ast_rtp_codecs_payload_code_tx(), ast_rtp_instance_get_codecs(), ast_rtp_instance_get_data(), ast_smoother_feed, ast_smoother_feed_be, AST_SMOOTHER_FLAG_BE, AST_SMOOTHER_FLAG_FORCED, ast_smoother_new(), ast_smoother_read(), ast_smoother_set_flags(), ast_smoother_test_flag(), ast_frame::data, format, ast_frame_subclass::format, ast_frame::frametype, LOG_WARNING, ast_frame::offset, ast_frame::ptr, rtp_raw_write(), multicast_rtp::smoother, and ast_frame::subclass.
Referenced by ast_multicast_rtp_options_get_format().
 {
    struct multicast_rtp *multicast = ast_rtp_instance_get_data(instance);
    struct ast_format *format;
    struct ast_frame *f;
    int codec;
    /* We only accept audio, nothing else */
    if (frame->frametype != AST_FRAME_VOICE) {
       return 0;
    }
    /* Grab the actual payload number for when we create the RTP packet */
    codec = ast_rtp_codecs_payload_code_tx(ast_rtp_instance_get_codecs(instance),
       1, frame->subclass.format, 0);
    if (codec < 0) {
       return -1;
    }
    format = frame->subclass.format;
    if (!multicast->smoother && ast_format_can_be_smoothed(format)) {
       unsigned int smoother_flags = ast_format_get_smoother_flags(format);
       unsigned int framing_ms = ast_rtp_codecs_get_framing(ast_rtp_instance_get_codecs(instance));
       if (!framing_ms && (smoother_flags & AST_SMOOTHER_FLAG_FORCED)) {
          framing_ms = ast_format_get_default_ms(format);
       }
       if (framing_ms) {
          multicast->smoother = ast_smoother_new((framing_ms * ast_format_get_minimum_bytes(format)) / ast_format_get_minimum_ms(format));
          if (!multicast->smoother) {
             ast_log(LOG_WARNING, "Unable to create smoother: format %s ms: %u len %u\n",
                   ast_format_get_name(format), framing_ms, ast_format_get_minimum_bytes(format));
             return -1;
          }
          ast_smoother_set_flags(multicast->smoother, smoother_flags);
       }
    }
    if (multicast->smoother) {
       if (ast_smoother_test_flag(multicast->smoother, AST_SMOOTHER_FLAG_BE)) {
          ast_smoother_feed_be(multicast->smoother, frame);
       } else {
          ast_smoother_feed(multicast->smoother, frame);
       }
       while ((f = ast_smoother_read(multicast->smoother)) && f->data.ptr) {
          rtp_raw_write(instance, f, codec);
       }
    } else {
       int hdrlen = 12;
       /* If we do not have space to construct an RTP header duplicate the frame so we get some */
       if (frame->offset < hdrlen) {
          f = ast_frdup(frame);
       } else {
          f = frame;
       }
       if (f->data.ptr) {
          rtp_raw_write(instance, f, codec);
       }
       if (f != frame) {
          ast_frfree(f);
       }
    }
    return 0;
 }
multicast_send_control_packet()
static int multicast_send_control_packet (struct ast_rtp_instance * instance, struct multicast_rtp * multicast, int command) static
Helper function which populates a control packet with useful information and sends it.
Definition at line 348 of file res_rtp_multicast.c.
References ast_log, ast_rtp_instance_get_local_address(), ast_rtp_instance_get_remote_address, ast_sendto(), ast_sockaddr_ipv4(), ast_sockaddr_is_ipv6(), ast_sockaddr_isnull(), ast_sockaddr_port, multicast_control_packet::ip, LOG_WARNING, NULL, multicast_control_packet::port, multicast_rtp::socket, and multicast_control_packet::unique_id.
Referenced by multicast_rtp_activate(), and multicast_rtp_destroy().
 {
    struct multicast_control_packet control_packet = { .unique_id = htonl((u_long)time(NULL)),
                         .command = htonl(command),
    };
    struct ast_sockaddr control_address, remote_address;
    ast_rtp_instance_get_local_address(instance, &control_address);
    ast_rtp_instance_get_remote_address(instance, &remote_address);
    /* Ensure the user of us have given us both the control address and destination address */
    if (ast_sockaddr_isnull(&control_address) ||
        ast_sockaddr_isnull(&remote_address)) {
       return -1;
    }
    /* The protocol only supports IPv4. */
    if (ast_sockaddr_is_ipv6(&remote_address)) {
       ast_log(LOG_WARNING, "Cannot send control packet for IPv6 "
          "remote address.\n");
       return -1;
    }
    control_packet.ip = htonl(ast_sockaddr_ipv4(&remote_address));
    control_packet.port = htonl(ast_sockaddr_port(&remote_address));
    /* Based on a recommendation by Brian West who did the FreeSWITCH implementation we send control packets twice */
    ast_sendto(multicast->socket, &control_packet, sizeof(control_packet), 0, &control_address);
    ast_sendto(multicast->socket, &control_packet, sizeof(control_packet), 0, &control_address);
    return 0;
 }
rtp_get_rate()
static int rtp_get_rate (struct ast_format * format) static
Definition at line 322 of file res_rtp_multicast.c.
References ast_format_cmp(), AST_FORMAT_CMP_EQUAL, ast_format_g722, and ast_format_get_sample_rate().
Referenced by rtp_raw_write().
 {
    return ast_format_cmp(format, ast_format_g722) == AST_FORMAT_CMP_EQUAL ?
       8000 : ast_format_get_sample_rate(format);
 }
rtp_raw_write()
static int rtp_raw_write (struct ast_rtp_instance * instance, struct ast_frame * frame, int codec) static
Definition at line 413 of file res_rtp_multicast.c.
References abs, ast_debug, ast_format_cmp(), AST_FORMAT_CMP_EQUAL, ast_format_g722, AST_FRFLAG_HAS_TIMING_INFO, ast_log, ast_rtp_instance_get_data(), ast_rtp_instance_get_remote_address, ast_sendto(), ast_sockaddr_stringify(), ast_test_flag, ast_tvzero(), calc_txstamp(), ast_frame::data, ast_frame::datalen, ast_frame::delivery, errno, ast_frame_subclass::format, multicast_rtp::lastts, LOG_ERROR, MAX_TIMESTAMP_SKEW, ast_frame::ptr, put_unaligned_uint32(), rtp_get_rate(), ast_frame::samples, multicast_rtp::seqno, multicast_rtp::socket, multicast_rtp::ssrc, ast_frame::subclass, and ast_frame::ts.
Referenced by multicast_rtp_write().
 {
    struct multicast_rtp *multicast = ast_rtp_instance_get_data(instance);
    unsigned int ms = calc_txstamp(multicast, &frame->delivery);
    unsigned char *rtpheader;
    struct ast_sockaddr remote_address = { {0,} };
    int rate = rtp_get_rate(frame->subclass.format) / 1000;
    int hdrlen = 12, mark = 0;
    if (ast_format_cmp(frame->subclass.format, ast_format_g722) == AST_FORMAT_CMP_EQUAL) {
       frame->samples /= 2;
    }
    if (ast_test_flag(frame, AST_FRFLAG_HAS_TIMING_INFO)) {
       multicast->lastts = frame->ts * rate;
    } else {
       /* Try to predict what our timestamp should be */
       int pred = multicast->lastts + frame->samples;
       /* Calculate last TS */
       multicast->lastts = multicast->lastts + ms * rate;
       if (ast_tvzero(frame->delivery)) {
          int delta = abs((int) multicast->lastts - pred);
          if (delta < MAX_TIMESTAMP_SKEW) {
             multicast->lastts = pred;
          } else {
             ast_debug(3, "Difference is %d, ms is %u\n", delta, ms);
             mark = 1;
          }
       }
    }
    /* Construct an RTP header for our packet */
    rtpheader = (unsigned char *)(frame->data.ptr - hdrlen);
    put_unaligned_uint32(rtpheader, htonl((2 << 30) | (codec << 16) | (multicast->seqno) | (mark << 23)));
    put_unaligned_uint32(rtpheader + 4, htonl(multicast->lastts));
    put_unaligned_uint32(rtpheader + 8, htonl(multicast->ssrc));
    /* Increment sequence number and wrap to 0 if it overflows 16 bits. */
    multicast->seqno = 0xFFFF & (multicast->seqno + 1);
    /* Finally send it out to the eager phones listening for us */
    ast_rtp_instance_get_remote_address(instance, &remote_address);
    if (ast_sendto(multicast->socket, (void *) rtpheader, frame->datalen + hdrlen, 0, &remote_address) < 0) {
       ast_log(LOG_ERROR, "Multicast RTP Transmission error to %s: %s\n",
          ast_sockaddr_stringify(&remote_address),
          strerror(errno));
       return -1;
    }
    return 0;
 }
set_if()
static void set_if (int sock, const char * if_str) static
Definition at line 263 of file res_rtp_multicast.c.
References ast_debug, ast_log, ast_strlen_zero, errno, inet_aton(), and LOG_WARNING.
Referenced by multicast_rtp_new().
 {
    struct in_addr iface;
    if (ast_strlen_zero(if_str)) {
       return;
    }
    ast_debug(3, "Setting multicast if to %s\n", if_str);
    if (!inet_aton(if_str, &iface)) {
       ast_log(LOG_WARNING, "Cannot parse if option '%s'\n", if_str);
    }
    if (setsockopt(sock, IPPROTO_IP, IP_MULTICAST_IF, &iface, sizeof(iface)) < 0) {
       ast_log(LOG_WARNING, "Could not set multicast if to '%s': %s\n",
          if_str, strerror(errno));
    }
 }
set_loop()
static void set_loop (int sock, const char * loop_str) static
Definition at line 242 of file res_rtp_multicast.c.
References ast_debug, ast_log, ast_strlen_zero, errno, and LOG_WARNING.
Referenced by multicast_rtp_new().
 {
    unsigned char loop;
    if (ast_strlen_zero(loop_str)) {
       return;
    }
    ast_debug(3, "Setting multicast loop to %s\n", loop_str);
    if (sscanf(loop_str, "%30hhu", &loop) < 1) {
       ast_log(LOG_WARNING, "Invalid multicast loop option '%s'\n", loop_str);
       return;
    }
    if (setsockopt(sock, IPPROTO_IP, IP_MULTICAST_LOOP, &loop, sizeof(loop)) < 0) {
       ast_log(LOG_WARNING, "Could not set multicast loop to '%s': %s\n",
          loop_str, strerror(errno));
    }
 }
set_ttl()
static void set_ttl (int sock, const char * ttl_str) static
Definition at line 221 of file res_rtp_multicast.c.
References ast_debug, ast_log, ast_strlen_zero, errno, and LOG_WARNING.
Referenced by multicast_rtp_new().
 {
    int ttl;
    if (ast_strlen_zero(ttl_str)) {
       return;
    }
    ast_debug(3, "Setting multicast TTL to %s\n", ttl_str);
    if (sscanf(ttl_str, "%30d", &ttl) < 1) {
       ast_log(LOG_WARNING, "Invalid multicast ttl option '%s'\n", ttl_str);
       return;
    }
    if (setsockopt(sock, IPPROTO_IP, IP_MULTICAST_TTL, &ttl, sizeof(ttl)) < 0) {
       ast_log(LOG_WARNING, "Could not set multicast ttl to '%s': %s\n",
          ttl_str, strerror(errno));
    }
 }
set_type()
static int set_type (struct multicast_rtp * multicast, const char * type) static
Definition at line 207 of file res_rtp_multicast.c.
References ast_log, LOG_WARNING, MULTICAST_TYPE_BASIC, MULTICAST_TYPE_LINKSYS, and multicast_rtp::type.
Referenced by multicast_rtp_new().
 {
    if (!strcasecmp(type, "basic")) {
       multicast->type = MULTICAST_TYPE_BASIC;
    } else if (!strcasecmp(type, "linksys")) {
       multicast->type = MULTICAST_TYPE_LINKSYS;
    } else {
       ast_log(LOG_WARNING, "Unrecognized multicast type '%s' specified.\n", type);
       return -1;
    }
    return 0;
 }
unload_module()
static int unload_module (void) static
Definition at line 555 of file res_rtp_multicast.c.
References AST_MODFLAG_GLOBAL_SYMBOLS, AST_MODFLAG_LOAD_ORDER, AST_MODPRI_CHANNEL_DEPEND, AST_MODULE_INFO(), AST_MODULE_SUPPORT_CORE, ast_rtp_engine_unregister(), ASTERISK_GPL_KEY, and load_module().
 {
    ast_rtp_engine_unregister(&multicast_rtp_engine);
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_GLOBAL_SYMBOLS | AST_MODFLAG_LOAD_ORDER , .description = "Multicast RTP Engine" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_CHANNEL_DEPEND, } static
Definition at line 567 of file res_rtp_multicast.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 567 of file res_rtp_multicast.c.
multicast_rtp_engine
struct ast_rtp_engine multicast_rtp_engine static
Definition at line 198 of file res_rtp_multicast.c.
multicast_rtp_options
const struct ast_app_option multicast_rtp_options[128] = { [ 'c' ] = { .flag = OPT_CODEC , .arg_index = OPT_ARG_CODEC + 1 }, [ 'l' ] = { .flag = OPT_LOOP , .arg_index = OPT_ARG_LOOP + 1 }, [ 't' ] = { .flag = OPT_TTL , .arg_index = OPT_ARG_TTL + 1 }, [ 'i' ] = { .flag = OPT_IF , .arg_index = OPT_ARG_IF + 1 }, } static
Definition at line 128 of file res_rtp_multicast.c.
Referenced by ast_multicast_rtp_create_options().