Asterisk - The Open Source Telephony Project: app_bridgeaddchan.c File Reference
app_bridgeaddchan.c File Reference
Dial plan applications
Application to place the channel into an existing Bridge.
#include "asterisk.h"
#include "asterisk/file.h"
#include "asterisk/module.h"
#include "asterisk/channel.h"
#include "asterisk/bridge.h"
#include "asterisk/features.h"
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int bridgeadd_exec (struct ast_channel *chan, const char *data)
static int load_module (void)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Bridge Add Channel Application" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, }
static const char app [] = "BridgeAdd"
static const struct ast_module_info * ast_module_info = &__mod_info
Detailed Description
Application to place the channel into an existing Bridge.
Author
Alec Davis
Definition in file app_bridgeaddchan.c.
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 144 of file app_bridgeaddchan.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 144 of file app_bridgeaddchan.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 144 of file app_bridgeaddchan.c.
bridgeadd_exec()
static int bridgeadd_exec (struct ast_channel * chan, const char * data) static
Definition at line 74 of file app_bridgeaddchan.c.
References ao2_cleanup, ast_answer(), ast_bridge_features_cleanup(), ast_bridge_features_init(), ast_bridge_join(), ast_channel_get_bridge(), ast_channel_get_by_name_prefix(), ast_channel_lock, ast_channel_name(), ast_channel_unlock, ast_channel_unref, AST_STATE_UP, ast_strdupa, ast_strlen_zero, ast_verb, NULL, pbx_builtin_setvar_helper(), and ast_bridge::uniqueid.
Referenced by load_module().
 {
    struct ast_channel *c_ref;
    struct ast_bridge_features chan_features;
    struct ast_bridge *bridge;
    char *c_name;
    int failed;
    /* Answer the channel if needed */
    if (ast_channel_state(chan) != AST_STATE_UP) {
       ast_answer(chan);
    }
    if (ast_strlen_zero(data)) {
       data = "";
       c_ref = NULL;
    } else {
       c_ref = ast_channel_get_by_name_prefix(data, strlen(data));
    }
    if (!c_ref) {
       ast_verb(4, "Channel '%s' not found\n", data);
       pbx_builtin_setvar_helper(chan, "BRIDGERESULT", "NONEXISTENT");
       return 0;
    }
    if (chan == c_ref) {
       ast_channel_unref(c_ref);
       pbx_builtin_setvar_helper(chan, "BRIDGERESULT", "LOOP");
       return 0;
    }
    c_name = ast_strdupa(ast_channel_name(c_ref));
    ast_channel_lock(c_ref);
    bridge = ast_channel_get_bridge(c_ref);
    ast_channel_unlock(c_ref);
    ast_channel_unref(c_ref);
    if (!bridge) {
       ast_verb(4, "Channel '%s' is not in a bridge\n", c_name);
       pbx_builtin_setvar_helper(chan, "BRIDGERESULT", "FAILURE");
       return 0;
    }
    ast_verb(4, "%s is joining %s in bridge %s\n",
       ast_channel_name(chan), c_name, bridge->uniqueid);
    failed = ast_bridge_features_init(&chan_features)
       || ast_bridge_join(bridge, chan, NULL, &chan_features, NULL, 0);
    if (failed) {
       ast_verb(4, "%s failed to join %s in bridge %s\n",
          ast_channel_name(chan), c_name, bridge->uniqueid);
    }
    ast_bridge_features_cleanup(&chan_features);
    ao2_cleanup(bridge);
    pbx_builtin_setvar_helper(chan, "BRIDGERESULT", failed ? "FAILURE" : "SUCCESS");
    return 0;
 }
load_module()
static int load_module (void) static
Definition at line 139 of file app_bridgeaddchan.c.
References app, ast_register_application_xml, and bridgeadd_exec().
 {
    return ast_register_application_xml(app, bridgeadd_exec);
 }
unload_module()
static int unload_module (void) static
Definition at line 134 of file app_bridgeaddchan.c.
References app, and ast_unregister_application().
 {
    return ast_unregister_application(app);
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Bridge Add Channel Application" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, } static
Definition at line 144 of file app_bridgeaddchan.c.
app
const char app[] = "BridgeAdd" static
Definition at line 72 of file app_bridgeaddchan.c.
Referenced by load_module(), and unload_module().
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 144 of file app_bridgeaddchan.c.