Asterisk - The Open Source Telephony Project: netsock2.h File Reference
netsock2.h File Reference
Network socket handling.
#include <sys/socket.h>
#include <netinet/in.h>
#include "asterisk/logger.h"
Data Structures
struct ast_sockaddr
Socket address structure.
Macros
#define AST_SOCKADDR_BUFLEN (45 + 2 + 1 + 5 + 1)
#define ast_sockaddr_port(addr) _ast_sockaddr_port(addr, __FILE__, __LINE__, __PRETTY_FUNCTION__)
Get the port number of a socket address.
#define ast_sockaddr_set_port(addr, port) _ast_sockaddr_set_port(addr,port,__FILE__,__LINE__,__PRETTY_FUNCTION__)
Sets the port number of a socket address.
#define AST_SOCKADDR_STR_ADDR (1 << 0)
#define AST_SOCKADDR_STR_ADDR_REMOTE (AST_SOCKADDR_STR_ADDR | AST_SOCKADDR_STR_REMOTE)
#define AST_SOCKADDR_STR_BRACKETS (1 << 2)
#define AST_SOCKADDR_STR_DEFAULT (AST_SOCKADDR_STR_ADDR | AST_SOCKADDR_STR_PORT)
#define AST_SOCKADDR_STR_DEFAULT_REMOTE (AST_SOCKADDR_STR_DEFAULT | AST_SOCKADDR_STR_REMOTE)
#define AST_SOCKADDR_STR_FORMAT_MASK (AST_SOCKADDR_STR_ADDR | AST_SOCKADDR_STR_PORT | AST_SOCKADDR_STR_BRACKETS)
#define AST_SOCKADDR_STR_HOST (AST_SOCKADDR_STR_ADDR | AST_SOCKADDR_STR_BRACKETS)
#define AST_SOCKADDR_STR_HOST_REMOTE (AST_SOCKADDR_STR_HOST | AST_SOCKADDR_STR_REMOTE)
#define AST_SOCKADDR_STR_PORT (1 << 1)
#define AST_SOCKADDR_STR_REMOTE (1 << 3)
#define V6_WORD(sin6, index) ((uint32_t *)&((sin6)->sin6_addr))[(index)]
Isolate a 32-bit section of an IPv6 address.
Enumerations
enum { AST_AF_UNSPEC = AF_UNSPEC, AST_AF_INET = AF_INET, AST_AF_INET6 = AF_INET6 }
enum ast_transport {
AST_TRANSPORT_UDP = 1, AST_TRANSPORT_TCP = 1 << 1, AST_TRANSPORT_TLS = 1 << 2, AST_TRANSPORT_WS = 1 << 3,
AST_TRANSPORT_WSS = 1 << 4
}
Functions
uint16_t _ast_sockaddr_port (const struct ast_sockaddr *addr, const char *file, int line, const char *func)
void _ast_sockaddr_set_port (struct ast_sockaddr *addr, uint16_t port, const char *file, int line, const char *func)
int ast_accept (int sockfd, struct ast_sockaddr *addr)
Wrapper around accept(2) that uses struct ast_sockaddr.
int ast_bind (int sockfd, const struct ast_sockaddr *addr)
Wrapper around bind(2) that uses struct ast_sockaddr.
int ast_connect (int sockfd, const struct ast_sockaddr *addr)
Wrapper around connect(2) that uses struct ast_sockaddr.
int ast_getsockname (int sockfd, struct ast_sockaddr *addr)
Wrapper around getsockname(2) that uses struct ast_sockaddr.
ssize_t ast_recvfrom (int sockfd, void *buf, size_t len, int flags, struct ast_sockaddr *src_addr)
Wrapper around recvfrom(2) that uses struct ast_sockaddr.
ssize_t ast_sendto (int sockfd, const void *buf, size_t len, int flags, const struct ast_sockaddr *dest_addr)
Wrapper around sendto(2) that uses ast_sockaddr.
int ast_set_qos (int sockfd, int tos, int cos, const char *desc)
Set type of service.
int ast_sockaddr_apply_netmask (const struct ast_sockaddr *addr, const struct ast_sockaddr *netmask, struct ast_sockaddr *result)
Apply a netmask to an address and store the result in a separate structure.
int ast_sockaddr_cidr_bits (const struct ast_sockaddr *sa)
Count the 1 bits in a netmask.
int ast_sockaddr_cmp (const struct ast_sockaddr *a, const struct ast_sockaddr *b)
Compares two ast_sockaddr structures.
int ast_sockaddr_cmp_addr (const struct ast_sockaddr *a, const struct ast_sockaddr *b)
Compares the addresses of two ast_sockaddr structures.
static void ast_sockaddr_copy (struct ast_sockaddr *dst, const struct ast_sockaddr *src)
Copies the data from one ast_sockaddr to another.
static void ast_sockaddr_copy_sockaddr (struct ast_sockaddr *dst, struct sockaddr *src, socklen_t len)
Copies the data from a sockaddr to an ast_sockaddr.
int ast_sockaddr_hash (const struct ast_sockaddr *addr)
Computes a hash value from the address. The port is ignored.
uint32_t ast_sockaddr_ipv4 (const struct ast_sockaddr *addr)
Get an IPv4 address of an ast_sockaddr.
int ast_sockaddr_ipv4_mapped (const struct ast_sockaddr *addr, struct ast_sockaddr *ast_mapped)
Convert an IPv4-mapped IPv6 address into an IPv4 address.
int ast_sockaddr_is_any (const struct ast_sockaddr *addr)
Determine if the address type is unspecified, or "any" address.
int ast_sockaddr_is_ipv4 (const struct ast_sockaddr *addr)
Determine if the address is an IPv4 address.
int ast_sockaddr_is_ipv4_mapped (const struct ast_sockaddr *addr)
Determine if this is an IPv4-mapped IPv6 address.
int ast_sockaddr_is_ipv4_multicast (const struct ast_sockaddr *addr)
Determine if an IPv4 address is a multicast address.
int ast_sockaddr_is_ipv6 (const struct ast_sockaddr *addr)
Determine if this is an IPv6 address.
int ast_sockaddr_is_ipv6_link_local (const struct ast_sockaddr *addr)
Determine if this is a link-local IPv6 address.
static int ast_sockaddr_isnull (const struct ast_sockaddr *addr)
Checks if the ast_sockaddr is null. "null" in this sense essentially means uninitialized, or having a 0 length.
int ast_sockaddr_parse (struct ast_sockaddr *addr, const char *str, int flags)
Parse an IPv4 or IPv6 address string.
int ast_sockaddr_resolve (struct ast_sockaddr **addrs, const char *str, int flags, int family)
Parses a string with an IPv4 or IPv6 address and place results into an array.
int ast_sockaddr_resolve_first_af (struct ast_sockaddr *addr, const char *name, int flag, int family)
Return the first entry from ast_sockaddr_resolve filtered by address family.
static void ast_sockaddr_setnull (struct ast_sockaddr *addr)
Sets address addr to null.
int ast_sockaddr_split_hostport (char *str, char **host, char **port, int flags)
Splits a string into its host and port components.
static char * ast_sockaddr_stringify (const struct ast_sockaddr *addr)
Wrapper around ast_sockaddr_stringify_fmt() with default format.
static char * ast_sockaddr_stringify_addr (const struct ast_sockaddr *addr)
Wrapper around ast_sockaddr_stringify_fmt() to return an address only.
static char * ast_sockaddr_stringify_addr_remote (const struct ast_sockaddr *addr)
Wrapper around ast_sockaddr_stringify_fmt() to return an address only.
char * ast_sockaddr_stringify_fmt (const struct ast_sockaddr *addr, int format)
Convert a socket address to a string.
static char * ast_sockaddr_stringify_host (const struct ast_sockaddr *addr)
Wrapper around ast_sockaddr_stringify_fmt() to return an address only, suitable for a URL (with brackets for IPv6).
static char * ast_sockaddr_stringify_host_remote (const struct ast_sockaddr *addr)
Wrapper around ast_sockaddr_stringify_fmt() to return an address only, suitable for a URL (with brackets for IPv6).
static char * ast_sockaddr_stringify_port (const struct ast_sockaddr *addr)
Wrapper around ast_sockaddr_stringify_fmt() to return a port only.
static char * ast_sockaddr_stringify_remote (const struct ast_sockaddr *addr)
Wrapper around ast_sockaddr_stringify_fmt() with default format.
const char * ast_transport2str (enum ast_transport transport)
Returns a string representation of an ast_transport.
#define ast_sockaddr_to_sin(addr, sin) _ast_sockaddr_to_sin(addr,sin, __FILE__, __LINE__, __PRETTY_FUNCTION__)
Converts a struct ast_sockaddr to a struct sockaddr_in.
#define ast_sockaddr_from_sin(addr, sin) _ast_sockaddr_from_sin(addr,sin, __FILE__, __LINE__, __PRETTY_FUNCTION__)
Converts a struct sockaddr_in to a struct ast_sockaddr.
#define ast_addressfamily_to_sockaddrsize(family) _ast_addressfamily_to_sockaddrsize(family, __FILE__, __LINE__, __PRETTY_FUNCTION__)
Takes an AF_XXX value as input and returns the size of the underlying sockaddr structure if known, or zero if not.
#define ast_sockaddr_from_sockaddr(addr, sa) ast_sockaddr_copy_sockaddr(addr, sa, ast_addressfamily_to_sockaddrsize(((const struct sockaddr*)(sa))->sa_family))
Converts a struct sockaddr to a struct ast_sockaddr.
int _ast_sockaddr_to_sin (const struct ast_sockaddr *addr, struct sockaddr_in *sin, const char *file, int line, const char *func)
void _ast_sockaddr_from_sin (struct ast_sockaddr *addr, const struct sockaddr_in *sin, const char *file, int line, const char *func)
static int _ast_addressfamily_to_sockaddrsize (int af, const char *file, int line, const char *func)
Detailed Description
Network socket handling.
Definition in file netsock2.h.
Macro Definition Documentation
ast_addressfamily_to_sockaddrsize
#define ast_addressfamily_to_sockaddrsize (family) _ast_addressfamily_to_sockaddrsize(family, __FILE__, __LINE__, __PRETTY_FUNCTION__)
Takes an AF_XXX value as input and returns the size of the underlying sockaddr structure if known, or zero if not.
Since
13.31.0, 16.8.0, 17.2.0
Parameters
family The AF_XXX value to determine the size of
Returns
Size of the applicable struct sockaddr.
Definition at line 795 of file netsock2.h.
AST_SOCKADDR_BUFLEN
#define AST_SOCKADDR_BUFLEN (45 + 2 + 1 + 5 + 1)
Definition at line 46 of file netsock2.h.
Referenced by ast_ha_output(), digest_create_request_with_auth(), log_failed_request(), logging_on_rx_msg(), logging_on_tx_msg(), new_invite(), and websocket_on_rx_msg().
ast_sockaddr_from_sin
#define ast_sockaddr_from_sin (addr, sin) _ast_sockaddr_from_sin(addr,sin, __FILE__, __LINE__, __PRETTY_FUNCTION__)
Converts a struct sockaddr_in to a struct ast_sockaddr.
Since
1.8
Parameters
addr
sin The sockaddr_in to convert
Returns
an ast_sockaddr structure
Definition at line 782 of file netsock2.h.
Referenced by ast_rtcp_read(), ast_rtp_read(), ast_rtp_stun_request(), ast_sockaddr_apply_netmask(), ast_sockaddr_ipv4_mapped(), build_gateway(), find_subchannel_and_lock(), handle_open_receive_channel_ack_message(), parse_cidr_mask(), process_sdp(), skinny_register(), and start_rtp().
ast_sockaddr_from_sockaddr
#define ast_sockaddr_from_sockaddr (addr, sa) ast_sockaddr_copy_sockaddr(addr, sa, ast_addressfamily_to_sockaddrsize(((const struct sockaddr*)(sa))->sa_family))
Converts a struct sockaddr to a struct ast_sockaddr.
Since
13.31.0, 16.8.0, 17.2.0
Note that there is an underlying assumption that sockaddr data is valid, more specifically, if sa_family is set to AF_INET that it's actually a sockaddr_in, and in the case of AF_INET6 a valid sockaddr_in6 structure.
You can check for failure with ast_sockaddr_isnull.
Parameters
[out] addr The address of the ast_sockaddr to store into
sa The sockaddr structure (sockaddr_in or sockaddr_in6) to convert
Returns
Nothing
Definition at line 824 of file netsock2.h.
Referenced by rtp_add_candidates_to_ice().
ast_sockaddr_port
#define ast_sockaddr_port (addr) _ast_sockaddr_port(addr, __FILE__, __LINE__, __PRETTY_FUNCTION__)
Get the port number of a socket address.
Since
1.8
Warning
Do not use this function unless you really know what you are doing. And "I want the port number" is not knowing what you are doing.
Return values
0 Address is null
non-zero The port number of the ast_sockaddr
Definition at line 521 of file netsock2.h.
Referenced by __ast_http_load(), __iax2_do_register_s(), __init_manager(), __set_address_from_contact(), __sip_subscribe_mwi_do(), _sip_show_peer(), _sip_show_peers_one(), add_sdp(), app_exec(), append_ha_core(), ast_apply_ha(), ast_audiosocket_connect(), ast_find_ourip(), ast_ha_join(), ast_netsock_bind(), ast_ouraddrfor(), ast_rtp_ice_turn_request(), ast_rtp_prop_set(), ast_rtp_read(), ast_rtp_remote_address_set(), ast_sip_ouraddrfor(), build_peer(), check_via(), cli_print_body(), conf_server(), configure_local_rtp(), copy_via_headers(), create_addr(), create_outgoing_sdp_stream(), dnsmgr_refresh(), dundi_show_trans(), dundi_sockaddr_port(), function_sippeer(), get_our_media_address(), handle_cli_rtp_drop_incoming_packets(), hep_queue_cb(), iax2_append_register(), iax2_do_register(), iax_outputframe(), ice_create(), initreqprep(), launch_netscript(), match_to_var_list_append(), multicast_send_control_packet(), on_dns_update_peer(), on_dns_update_registry(), ooh323_get_rtp_peer(), ooh323_set_rtp_peer(), parse_register_contact(), peer_ipcmp_cb_full(), realtime_peer(), realtime_update_peer(), reload_config(), set_config(), set_destination(), setup_udptl_connection(), sip_debug_test_addr(), transmit_notify_with_mwi(), transmit_register(), transport_create(), transport_read(), udptl_debug_test_addr(), and update_registry().
ast_sockaddr_set_port
#define ast_sockaddr_set_port (addr, port) _ast_sockaddr_set_port(addr,port,__FILE__,__LINE__,__PRETTY_FUNCTION__)
Sets the port number of a socket address.
Since
1.8
Warning
Do not use this function unless you really know what you are doing. And "I want the port number" is not knowing what you are doing.
Parameters
addr Address on which to set the port
port The port you wish to set the address to use
Return values
void
Definition at line 537 of file netsock2.h.
Referenced by __ast_http_load(), __iax2_do_register_s(), __init_manager(), __set_address_from_contact(), __sip_subscribe_mwi_do(), add_sdp(), app_exec(), append_ha_core(), apply_acl(), apply_endpoint_acl(), apply_negotiated_sdp_stream(), ast_apply_ha(), ast_find_ourip(), ast_get_ip_or_srv(), ast_netsock_bind(), ast_ouraddrfor(), ast_rtp_ice_add_cand(), ast_rtp_ice_turn_request(), ast_rtp_prop_set(), ast_rtp_read(), ast_rtp_remote_address_set(), ast_sip_ouraddrfor(), ast_udptl_new_with_bindaddr(), build_peer(), check_via(), conf_server(), create_addr(), dnsmgr_refresh(), get_our_media_address(), iax2_append_register(), iax2_call(), iax2_do_register(), iax2_request(), ip_identify(), jingle_interpret_google_transport(), jingle_interpret_ice_udp_transport(), launch_netscript(), on_dns_update_peer(), on_dns_update_registry(), parse_register_contact(), peer_set_srcaddr(), pjsip_log_test_addr(), populate_addr(), process_ice_attributes(), process_nat(), process_sdp(), process_sdp_a_ice(), process_via(), proxy_update(), realtime_peer(), reload_config(), rtp_allocate_transport(), security_event_populate(), set_config(), set_destination(), setup_rtp_connection(), setup_rtp_remote(), setup_udptl_connection(), sip_prepare_socket(), stun_monitor_request(), transmit_register(), and update_address_with_ice_candidate().
AST_SOCKADDR_STR_ADDR
#define AST_SOCKADDR_STR_ADDR (1 << 0)
Definition at line 202 of file netsock2.h.
Referenced by ast_sockaddr_stringify_addr(), ast_sockaddr_stringify_fmt(), and create_outgoing_sdp_stream().
AST_SOCKADDR_STR_ADDR_REMOTE
#define AST_SOCKADDR_STR_ADDR_REMOTE (AST_SOCKADDR_STR_ADDR | AST_SOCKADDR_STR_REMOTE)
Definition at line 208 of file netsock2.h.
Referenced by ast_sockaddr_stringify_addr_remote().
AST_SOCKADDR_STR_BRACKETS
#define AST_SOCKADDR_STR_BRACKETS (1 << 2)
Definition at line 204 of file netsock2.h.
AST_SOCKADDR_STR_DEFAULT
#define AST_SOCKADDR_STR_DEFAULT (AST_SOCKADDR_STR_ADDR | AST_SOCKADDR_STR_PORT)
Definition at line 207 of file netsock2.h.
Referenced by ast_sockaddr_stringify(), ast_sockaddr_stringify_fmt(), and statsd_init().
AST_SOCKADDR_STR_DEFAULT_REMOTE
#define AST_SOCKADDR_STR_DEFAULT_REMOTE (AST_SOCKADDR_STR_DEFAULT | AST_SOCKADDR_STR_REMOTE)
Definition at line 210 of file netsock2.h.
Referenced by ast_sockaddr_stringify_remote().
AST_SOCKADDR_STR_FORMAT_MASK
#define AST_SOCKADDR_STR_FORMAT_MASK (AST_SOCKADDR_STR_ADDR | AST_SOCKADDR_STR_PORT | AST_SOCKADDR_STR_BRACKETS)
Definition at line 211 of file netsock2.h.
Referenced by ast_sockaddr_stringify_fmt().
AST_SOCKADDR_STR_HOST
#define AST_SOCKADDR_STR_HOST (AST_SOCKADDR_STR_ADDR | AST_SOCKADDR_STR_BRACKETS)
Definition at line 206 of file netsock2.h.
Referenced by ast_sockaddr_stringify_fmt(), and ast_sockaddr_stringify_host().
AST_SOCKADDR_STR_HOST_REMOTE
#define AST_SOCKADDR_STR_HOST_REMOTE (AST_SOCKADDR_STR_HOST | AST_SOCKADDR_STR_REMOTE)
Definition at line 209 of file netsock2.h.
Referenced by ast_sockaddr_stringify_host_remote().
AST_SOCKADDR_STR_PORT
#define AST_SOCKADDR_STR_PORT (1 << 1)
Definition at line 203 of file netsock2.h.
Referenced by ast_sockaddr_stringify_fmt(), and ast_sockaddr_stringify_port().
AST_SOCKADDR_STR_REMOTE
#define AST_SOCKADDR_STR_REMOTE (1 << 3)
Definition at line 205 of file netsock2.h.
Referenced by ast_sockaddr_stringify_fmt().
ast_sockaddr_to_sin
#define ast_sockaddr_to_sin (addr, sin) _ast_sockaddr_to_sin(addr,sin, __FILE__, __LINE__, __PRETTY_FUNCTION__)
Converts a struct ast_sockaddr to a struct sockaddr_in.
These are backward compatibility functions that may be used by subsystems that have not yet been converted to IPv6. They will be removed when all subsystems are IPv6-ready.
Since
1.8
Parameters
addr The ast_sockaddr to convert
[out] sin The resulting sockaddr_in struct
Return values
nonzero Success
zero Failure
Definition at line 769 of file netsock2.h.
Referenced by add_sdp(), ast_rtcp_read(), ast_rtp_read(), ast_rtp_stun_request(), build_gateway(), config_parse_variables(), find_rtp_port(), find_subchannel_and_lock(), handle_open_receive_channel_ack_message(), send_start_rtp(), skinny_set_rtp_peer(), transmit_modify_with_sdp(), and unistim_set_rtp_peer().
V6_WORD
#define V6_WORD (sin6, index) ((uint32_t *)&((sin6)->sin6_addr))[(index)]
Isolate a 32-bit section of an IPv6 address.
An IPv6 address can be divided into 4 32-bit chunks. This gives easy access to one of these chunks.
Parameters
sin6 A pointer to a struct sockaddr_in6
index Which 32-bit chunk to operate on. Must be in the range 0-3.
Definition at line 77 of file netsock2.h.
Referenced by ast_sockaddr_apply_netmask(), and parse_cidr_mask().
Enumeration Type Documentation
anonymous enum
anonymous enum
Values for address families that we support. This is reproduced from socket.h because we do not want users to include that file. Only netsock2.c should ever include socket.h.
Enumerator
AST_AF_UNSPEC
AST_AF_INET
AST_AF_INET6
Definition at line 53 of file netsock2.h.
      {
    AST_AF_UNSPEC = AF_UNSPEC,
    AST_AF_INET   = AF_INET,
    AST_AF_INET6  = AF_INET6,
 };
ast_transport
enum ast_transport
Enumerator
AST_TRANSPORT_UDP
AST_TRANSPORT_TCP
AST_TRANSPORT_TLS
AST_TRANSPORT_WS
AST_TRANSPORT_WSS
Definition at line 59 of file netsock2.h.
                    {
    AST_TRANSPORT_UDP   = 1,
    AST_TRANSPORT_TCP   = 1 << 1,
    AST_TRANSPORT_TLS   = 1 << 2,
    AST_TRANSPORT_WS    = 1 << 3,
    AST_TRANSPORT_WSS   = 1 << 4,
 };
Function Documentation
_ast_addressfamily_to_sockaddrsize()
static int _ast_addressfamily_to_sockaddrsize (int af, const char * file, int line, const char * func) inline static
Definition at line 796 of file netsock2.h.
References __LOG_WARNING, and ast_log.
 {
    switch (af) {
    case AF_INET:
       return sizeof(struct sockaddr_in);
    case AF_INET6:
       return sizeof(struct sockaddr_in6);
    default:
       ast_log(__LOG_WARNING, file, line, func, "Unknown address family %d encountered.\n", af);
       return 0;
    }
 }
_ast_sockaddr_from_sin()
void _ast_sockaddr_from_sin (struct ast_sockaddr * addr, const struct sockaddr_in * sin, const char * file, int line, const char * func)
Definition at line 689 of file netsock2.c.
References __LOG_DEBUG, ast_log, DEBUG_ATLEAST, ast_sockaddr::len, and ast_sockaddr::ss.
 {
    memcpy(&addr->ss, sin, sizeof(*sin));
    if (addr->ss.ss_family != AF_INET && DEBUG_ATLEAST(1)) {
       ast_log(__LOG_DEBUG, file, line, func, "Address family is not AF_INET\n");
    }
    addr->len = sizeof(*sin);
 }
_ast_sockaddr_port()
uint16_t _ast_sockaddr_port (const struct ast_sockaddr * addr, const char * file, int line, const char * func)
Definition at line 453 of file netsock2.c.
References __LOG_DEBUG, ast_log, DEBUG_ATLEAST, ast_sockaddr::len, and ast_sockaddr::ss.
 {
    /*
     * Test addr->len first to be tolerant of an ast_sockaddr_setnull()
     * addr.  In that case addr->len might be the only value initialized.
     */
    if (addr->len == sizeof(struct sockaddr_in)
       && addr->ss.ss_family == AF_INET) {
       return ntohs(((struct sockaddr_in *)&addr->ss)->sin_port);
    }
    if (addr->len == sizeof(struct sockaddr_in6)
       && addr->ss.ss_family == AF_INET6) {
       return ntohs(((struct sockaddr_in6 *)&addr->ss)->sin6_port);
    }
    if (DEBUG_ATLEAST(1)) {
       ast_log(__LOG_DEBUG, file, line, func, "Not an IPv4 nor IPv6 address, cannot get port.\n");
    }
    return 0;
 }
_ast_sockaddr_set_port()
void _ast_sockaddr_set_port (struct ast_sockaddr * addr, uint16_t port, const char * file, int line, const char * func)
Definition at line 473 of file netsock2.c.
References __LOG_DEBUG, ast_log, DEBUG_ATLEAST, ast_sockaddr::len, and ast_sockaddr::ss.
 {
    /*
     * Test addr->len first to be tolerant of an ast_sockaddr_setnull()
     * addr.  In that case addr->len might be the only value initialized.
     */
    if (addr->len == sizeof(struct sockaddr_in)
       && addr->ss.ss_family == AF_INET) {
       ((struct sockaddr_in *)&addr->ss)->sin_port = htons(port);
    } else if (addr->len == sizeof(struct sockaddr_in6)
       && addr->ss.ss_family == AF_INET6) {
       ((struct sockaddr_in6 *)&addr->ss)->sin6_port = htons(port);
    } else if (DEBUG_ATLEAST(1)) {
       ast_log(__LOG_DEBUG, file, line, func,
          "Not an IPv4 nor IPv6 address, cannot set port.\n");
    }
 }
_ast_sockaddr_to_sin()
int _ast_sockaddr_to_sin (const struct ast_sockaddr * addr, struct sockaddr_in * sin, const char * file, int line, const char * func)
Definition at line 668 of file netsock2.c.
References __LOG_DEBUG, __LOG_ERROR, ast_log, ast_sockaddr_isnull(), DEBUG_ATLEAST, ast_sockaddr::len, and ast_sockaddr::ss.
 {
    if (ast_sockaddr_isnull(addr)) {
       memset(sin, 0, sizeof(*sin));
       return 1;
    }
    if (addr->len != sizeof(*sin)) {
       ast_log(__LOG_ERROR, file, line, func, "Bad address cast to IPv4\n");
       return 0;
    }
    if (addr->ss.ss_family != AF_INET && DEBUG_ATLEAST(1)) {
       ast_log(__LOG_DEBUG, file, line, func, "Address family is not AF_INET\n");
    }
    *sin = *(struct sockaddr_in *)&addr->ss;
    return 1;
 }
ast_accept()
int ast_accept (int sockfd, struct ast_sockaddr * addr)
Wrapper around accept(2) that uses struct ast_sockaddr.
Since
1.8
For parameter and return information, see the man page for accept(2).
Definition at line 584 of file netsock2.c.
References ast_sockaddr::len, and ast_sockaddr::ss.
Referenced by ast_tcptls_server_root().
 {
    addr->len = sizeof(addr->ss);
    return accept(sockfd, (struct sockaddr *)&addr->ss, &addr->len);
 }
ast_bind()
int ast_bind (int sockfd, const struct ast_sockaddr * addr)
Wrapper around bind(2) that uses struct ast_sockaddr.
Since
1.8
For parameter and return information, see the man page for bind(2).
Definition at line 590 of file netsock2.c.
References ast_sockaddr::len, and ast_sockaddr::ss.
Referenced by ast_netsock_bindaddr(), ast_rtp_prop_set(), ast_tcptls_client_create(), ast_tcptls_server_start(), ast_udptl_new_with_bindaddr(), check_srcaddr(), load_module(), reload_config(), and rtp_allocate_transport().
 {
    return bind(sockfd, (const struct sockaddr *)&addr->ss, addr->len);
 }
ast_connect()
int ast_connect (int sockfd, const struct ast_sockaddr * addr)
Wrapper around connect(2) that uses struct ast_sockaddr.
Since
1.8
For parameter and return information, see the man page for connect(2).
Definition at line 595 of file netsock2.c.
References ast_sockaddr::len, and ast_sockaddr::ss.
Referenced by ast_audiosocket_connect(), ast_ouraddrfor(), ast_tcptls_client_start(), launch_netscript(), and stun_monitor_request().
 {
    return connect(sockfd, (const struct sockaddr *)&addr->ss, addr->len);
 }
ast_getsockname()
int ast_getsockname (int sockfd, struct ast_sockaddr * addr)
Wrapper around getsockname(2) that uses struct ast_sockaddr.
Since
1.8
For parameter and return information, see the man page for getsockname(2).
Definition at line 600 of file netsock2.c.
References ast_sockaddr::len, and ast_sockaddr::ss.
Referenced by ast_ouraddrfor(), ast_set_qos(), and ast_websocket_uri_cb().
 {
    addr->len = sizeof(addr->ss);
    return getsockname(sockfd, (struct sockaddr *)&addr->ss, &addr->len);
 }
ast_recvfrom()
ssize_t ast_recvfrom (int sockfd, void * buf, size_t len, int flags, struct ast_sockaddr * src_addr)
Wrapper around recvfrom(2) that uses struct ast_sockaddr.
Since
1.8
For parameter and return information, see the man page for recvfrom(2).
Definition at line 606 of file netsock2.c.
References ast_sockaddr::len, and ast_sockaddr::ss.
Referenced by __rtp_recvfrom(), ast_udptl_read(), sipsock_read(), and socket_read().
 {
    src_addr->len = sizeof(src_addr->ss);
    return recvfrom(sockfd, buf, len, flags,
          (struct sockaddr *)&src_addr->ss, &src_addr->len);
 }
ast_sendto()
ssize_t ast_sendto (int sockfd, const void * buf, size_t len, int flags, const struct ast_sockaddr * dest_addr)
Wrapper around sendto(2) that uses ast_sockaddr.
Since
1.8
For parameter and return information, see the man page for sendto(2)
Definition at line 614 of file netsock2.c.
References ast_sockaddr::len, and ast_sockaddr::ss.
Referenced by __rtp_sendto(), __sip_xmit(), ast_rtp_on_turn_rx_rtcp_data(), ast_rtp_on_turn_rx_rtp_data(), ast_statsd_log_string(), ast_udptl_write(), dundi_xmit(), hep_queue_cb(), multicast_send_control_packet(), raw_hangup(), rtp_raw_write(), send_apathetic_reply(), send_packet(), sip_send_keepalive(), and transmit_trunk().
 {
    return sendto(sockfd, buf, len, flags,
             (const struct sockaddr *)&dest_addr->ss, dest_addr->len);
 }
ast_set_qos()
int ast_set_qos (int sockfd, int tos, int cos, const char * desc)
Set type of service.
Since
1.8
Set ToS ("Type of Service for IPv4 and "Traffic Class for IPv6) and CoS (Linux's SO_PRIORITY)
Parameters
sockfd File descriptor for socket on which to set the parameters
tos The type of service for the socket
cos The cost of service for the socket
desc A text description of the socket in question.
Return values
0 Success
-1 Error, with errno set to an appropriate value
Definition at line 621 of file netsock2.c.
References ast_getsockname(), ast_log, ast_sockaddr_is_any(), ast_sockaddr_is_ipv6(), ast_verb, errno, and LOG_WARNING.
Referenced by ast_netsock_bindaddr(), ast_netsock_set_qos(), ast_rtp_qos_set(), ast_udptl_setqos(), config_load(), load_module(), reload_config(), and sip_prepare_socket().
 {
    int res = 0;
    int set_tos;
    int set_tclass;
    struct ast_sockaddr addr;
    /* If the sock address is IPv6, the TCLASS field must be set. */
    set_tclass = !ast_getsockname(sockfd, &addr) && ast_sockaddr_is_ipv6(&addr) ? 1 : 0;
    /* If the sock address is IPv4 or (IPv6 set to any address [::]) set TOS bits */
    set_tos = (!set_tclass || (set_tclass && ast_sockaddr_is_any(&addr))) ? 1 : 0;
    if (set_tos) {
       if ((res = setsockopt(sockfd, IPPROTO_IP, IP_TOS, &tos, sizeof(tos)))) {
          ast_log(LOG_WARNING, "Unable to set %s DSCP TOS value to %d (may be you have no "
             "root privileges): %s\n", desc, tos, strerror(errno));
       } else if (tos) {
          ast_verb(2, "Using %s TOS bits %d\n", desc, tos);
       }
    }
 #if defined(IPV6_TCLASS) && defined(IPPROTO_IPV6)
    if (set_tclass) {
       if (!ast_getsockname(sockfd, &addr) && ast_sockaddr_is_ipv6(&addr)) {
          if ((res = setsockopt(sockfd, IPPROTO_IPV6, IPV6_TCLASS, &tos, sizeof(tos)))) {
             ast_log(LOG_WARNING, "Unable to set %s DSCP TCLASS field to %d (may be you have no "
                "root privileges): %s\n", desc, tos, strerror(errno));
          } else if (tos) {
             ast_verb(2, "Using %s TOS bits %d in TCLASS field.\n", desc, tos);
          }
       }
    }
 #endif
 #ifdef linux
    if (setsockopt(sockfd, SOL_SOCKET, SO_PRIORITY, &cos, sizeof(cos))) {
       ast_log(LOG_WARNING, "Unable to set %s CoS to %d: %s\n", desc, cos,
          strerror(errno));
    } else if (cos) {
       ast_verb(2, "Using %s CoS mark %d\n", desc, cos);
    }
 #endif
    return res;
 }
ast_sockaddr_apply_netmask()
int ast_sockaddr_apply_netmask (const struct ast_sockaddr * addr, const struct ast_sockaddr * netmask, struct ast_sockaddr * result)
Apply a netmask to an address and store the result in a separate structure.
When dealing with IPv6 addresses, one cannot apply a netmask with a simple logical AND operation. Futhermore, the incoming address may be an IPv4 address and needs to be mapped properly before attempting to apply a rule.
Parameters
addr The IP address to apply the mask to.
netmask The netmask configured in the host access rule.
result The resultant address after applying the netmask to the given address
Return values
0 Successfully applied netmask
-1 Failed to apply netmask
Definition at line 357 of file netsock2.c.
References ast_sockaddr_from_sin, ast_sockaddr_is_ipv4(), ast_sockaddr_is_ipv6(), ast_sockaddr::len, ast_sockaddr::ss, and V6_WORD.
Referenced by addr_range_match_address_cb(), append_ha_core(), ast_apply_ha(), ast_sockaddr_stringify_port(), and authenticate_reply().
 {
    int res = 0;
    if (ast_sockaddr_is_ipv4(addr)) {
       struct sockaddr_in result4 = { 0, };
       struct sockaddr_in *addr4 = (struct sockaddr_in *) &addr->ss;
       struct sockaddr_in *mask4 = (struct sockaddr_in *) &netmask->ss;
       result4.sin_family = AF_INET;
       result4.sin_addr.s_addr = addr4->sin_addr.s_addr & mask4->sin_addr.s_addr;
       ast_sockaddr_from_sin(result, &result4);
    } else if (ast_sockaddr_is_ipv6(addr)) {
       struct sockaddr_in6 result6 = { 0, };
       struct sockaddr_in6 *addr6 = (struct sockaddr_in6 *) &addr->ss;
       struct sockaddr_in6 *mask6 = (struct sockaddr_in6 *) &netmask->ss;
       int i;
       result6.sin6_family = AF_INET6;
       for (i = 0; i < 4; ++i) {
          V6_WORD(&result6, i) = V6_WORD(addr6, i) & V6_WORD(mask6, i);
       }
       memcpy(&result->ss, &result6, sizeof(result6));
       result->len = sizeof(result6);
    } else {
       /* Unsupported address scheme */
       res = -1;
    }
    return res;
 }
ast_sockaddr_cidr_bits()
int ast_sockaddr_cidr_bits (const struct ast_sockaddr * sa)
Count the 1 bits in a netmask.
Since
12.4
Returns
number of 1 bits
Definition at line 130 of file netsock2.c.
References ast_sockaddr_ipv4_mapped(), ast_sockaddr_isnull(), ast_sockaddr::len, and ast_sockaddr::ss.
Referenced by ast_ha_join_cidr(), ast_sockaddr_stringify_addr(), and cli_print_body().
 {
    struct ast_sockaddr sa_ipv4;
    const struct ast_sockaddr *sa_tmp;
    int bits = 0;
    int bytes;
    int i;
    int j;
    char *addr;
    if (ast_sockaddr_isnull(sa)) {
       return 0;
    }
    if (ast_sockaddr_ipv4_mapped(sa, &sa_ipv4)) {
       sa_tmp = &sa_ipv4;
    } else {
       sa_tmp = sa;
    }
    bytes = sa_tmp->len;
    addr = ((struct sockaddr *)&sa_tmp->ss)->sa_data;
    for (i = 0; i < bytes ; ++i) {
       for (j = 0; j < 8; ++j) {
          if ((addr[i] >> j) & 1) {
             bits++;
          }
       }
    }
    return bits;
 }
ast_sockaddr_cmp()
int ast_sockaddr_cmp (const struct ast_sockaddr * a, const struct ast_sockaddr * b)
Compares two ast_sockaddr structures.
Since
1.8
Return values
-1 a is lexicographically smaller than b
0 a is equal to b
1 b is lexicographically smaller than a
Definition at line 388 of file netsock2.c.
References a, ast_sockaddr_ipv4_mapped(), b, ast_sockaddr::len, and ast_sockaddr::ss.
Referenced by __rtp_recvfrom(), ast_netsock_find(), ast_rtcp_interpret(), ast_rtp_instance_get_and_cmp_local_address(), ast_rtp_instance_get_and_cmp_requested_target_address(), ast_rtp_read(), ast_rtp_remote_address_set(), ast_sd_notify(), ast_sockaddr_copy(), ast_tcptls_client_create(), ast_tcptls_server_start(), AST_TEST_DEFINE(), ast_udptl_read(), dnsmgr_refresh(), find_tpeer(), find_transaction(), handle_command_response(), has_state_changed(), iax2_ack_registry(), iax2_getpeername(), iax2_getpeertrunk(), ice_candidate_cmp(), match(), parse_register_contact(), realtime_peer_by_name(), registry_rerequest(), reload_config(), rtcp_debug_test_addr(), rtp_add_candidates_to_ice(), rtp_debug_test_addr(), should_drop_packets(), sip_debug_test_addr(), sip_uri_domain_cmp(), socket_process_helper(), threadinfo_locate_cb(), transmit_register(), udptl_debug_test_addr(), and update_registry().
 {
    const struct ast_sockaddr *a_tmp, *b_tmp;
    struct ast_sockaddr ipv4_mapped;
    a_tmp = a;
    b_tmp = b;
    if (a_tmp->len != b_tmp->len) {
       if (ast_sockaddr_ipv4_mapped(a, &ipv4_mapped)) {
          a_tmp = &ipv4_mapped;
       } else if (ast_sockaddr_ipv4_mapped(b, &ipv4_mapped)) {
          b_tmp = &ipv4_mapped;
       }
    }
    if (a_tmp->len < b_tmp->len) {
       return -1;
    } else if (a_tmp->len > b_tmp->len) {
       return 1;
    }
    return memcmp(&a_tmp->ss, &b_tmp->ss, a_tmp->len);
 }
ast_sockaddr_cmp_addr()
int ast_sockaddr_cmp_addr (const struct ast_sockaddr * a, const struct ast_sockaddr * b)
Compares the addresses of two ast_sockaddr structures.
Since
1.8
Return values
-1 a is lexicographically smaller than b
0 a is equal to b
1 b is lexicographically smaller than a
Definition at line 413 of file netsock2.c.
References a, ast_sockaddr_ipv4_mapped(), b, ast_sockaddr::len, and ast_sockaddr::ss.
Referenced by add_sdp(), addr_range_cmp_cb(), addr_range_match_address_cb(), ast_apply_ha(), ast_sockaddr_copy(), AST_TEST_DEFINE(), authenticate_reply(), check_for_nat(), get_our_media_address(), iax_outputframe(), peer_ipcmp_cb_full(), peercnt_cmp_cb(), realtime_peer(), realtime_user(), reload_config(), rtcp_debug_test_addr(), rtp_add_candidates_to_ice(), rtp_debug_test_addr(), should_drop_packets(), sip_debug_test_addr(), socket_read(), and udptl_debug_test_addr().
 {
    const struct ast_sockaddr *a_tmp, *b_tmp;
    struct ast_sockaddr ipv4_mapped;
    const struct in_addr *ip4a, *ip4b;
    const struct in6_addr *ip6a, *ip6b;
    int ret = -1;
    a_tmp = a;
    b_tmp = b;
    if (a_tmp->len != b_tmp->len) {
       if (ast_sockaddr_ipv4_mapped(a, &ipv4_mapped)) {
          a_tmp = &ipv4_mapped;
       } else if (ast_sockaddr_ipv4_mapped(b, &ipv4_mapped)) {
          b_tmp = &ipv4_mapped;
       }
    }
    if (a->len < b->len) {
       ret = -1;
    } else if (a->len > b->len) {
       ret = 1;
    }
    switch (a_tmp->ss.ss_family) {
    case AF_INET:
       ip4a = &((const struct sockaddr_in*)&a_tmp->ss)->sin_addr;
       ip4b = &((const struct sockaddr_in*)&b_tmp->ss)->sin_addr;
       ret = memcmp(ip4a, ip4b, sizeof(*ip4a));
       break;
    case AF_INET6:
       ip6a = &((const struct sockaddr_in6*)&a_tmp->ss)->sin6_addr;
       ip6b = &((const struct sockaddr_in6*)&b_tmp->ss)->sin6_addr;
       ret = memcmp(ip6a, ip6b, sizeof(*ip6a));
       break;
    }
    return ret;
 }
ast_sockaddr_copy()
static void ast_sockaddr_copy (struct ast_sockaddr * dst, const struct ast_sockaddr * src) inline static
Copies the data from one ast_sockaddr to another.
Since
1.8
Parameters
dst The destination ast_sockaddr
src The source ast_sockaddr
Return values
void
Definition at line 171 of file netsock2.h.
References a, ast_sockaddr_cmp(), ast_sockaddr_cmp_addr(), b, and ast_sockaddr::len.
Referenced by __ast_http_load(), __find_callno(), __init_manager(), __rtp_recvfrom(), __sip_alloc(), add_sdp(), app_exec(), apply_peer(), ast_copy_ha(), ast_find_ourip(), ast_netsock_bindaddr(), ast_rtcp_interpret(), ast_rtcp_read(), ast_rtcp_write(), ast_rtp_ice_add_remote_candidate(), ast_rtp_ice_turn_request(), ast_rtp_instance_get_and_cmp_local_address(), ast_rtp_instance_get_and_cmp_requested_target_address(), ast_rtp_instance_get_incoming_source_address(), ast_rtp_instance_get_local_address(), ast_rtp_instance_get_requested_target_address(), ast_rtp_instance_new(), ast_rtp_instance_set_local_address(), ast_rtp_instance_set_requested_target_address(), ast_rtp_new(), ast_rtp_prop_set(), ast_rtp_read(), ast_rtp_remote_address_set(), ast_sip_ouraddrfor(), ast_sockaddr_resolve_first_af(), ast_tcptls_client_create(), ast_tcptls_server_root(), ast_tcptls_server_start(), ast_udptl_get_peer(), ast_udptl_get_us(), ast_udptl_new_with_bindaddr(), ast_udptl_read(), ast_udptl_set_peer(), ast_websocket_uri_cb(), auth_manager_http_callback(), auth_mxml_http_callback(), auth_rawman_http_callback(), authenticate_reply(), build_mansession(), build_peer(), check_peer_ok(), configure_local_rtp(), create_addr(), dialog_initialize_rtp(), dnsmgr_refresh(), dundi_reject(), find_tpeer(), find_transaction(), get_our_media_address(), handle_cli_iax2_set_debug(), handle_cli_iax2_show_callno_limits(), handle_cli_rtp_drop_incoming_packets(), handle_cli_udptl_set_debug(), handle_command_response(), handle_request_do(), iax2_ack_registry(), iax2_provision(), manager_http_callback(), mxml_http_callback(), on_dns_update_mwi(), on_dns_update_peer(), on_dns_update_registry(), parse_register_contact(), peercnt_add(), peercnt_modify(), peercnt_remove(), peercnt_remove_by_addr(), populate_addr(), rawman_http_callback(), reg_source_db(), reload_config(), resolve_first(), rtp_allocate_transport(), rtp_instance_set_incoming_source_address_nolock(), rtp_reload(), rtp_transport_wide_cc_feedback_produce(), sched_delay_remove(), session_do(), set_peercnt_limit(), sip_do_debug_peer(), sip_find_peer_full(), sip_prepare_socket(), socket_process_helper(), socket_read(), transmit_response_using_temp(), try_transfer(), unicast_rtp_request(), update_registry(), websocket_client_args_create(), and websocket_client_connect().
 {
    memcpy(dst, src, src->len);
    dst->len = src->len;
 };
ast_sockaddr_copy_sockaddr()
static void ast_sockaddr_copy_sockaddr (struct ast_sockaddr * dst, struct sockaddr * src, socklen_t len) inline static
Copies the data from a sockaddr to an ast_sockaddr.
Parameters
dst The destination ast_sockaddr
src The source sockaddr
len Length of the value stored in sockaddr
Return values
void
Definition at line 154 of file netsock2.h.
References ast_sockaddr::len.
Referenced by ast_sd_notify().
 {
    memcpy(dst, src, len);
    dst->len = len;
 }
ast_sockaddr_hash()
int ast_sockaddr_hash (const struct ast_sockaddr * addr)
Computes a hash value from the address. The port is ignored.
Since
1.8
Return values
0 Unknown address family
other A 32-bit hash derived from the address
Definition at line 548 of file netsock2.c.
References ast_log, LOG_ERROR, and ast_sockaddr::ss.
Referenced by addr_range_hash_cb(), peer_iphash_cb(), peercnt_hash_cb(), and threadt_hash_cb().
 {
    /*
     * For IPv4, return the IP address as-is. For IPv6, return the last 32
     * bits.
     */
    switch (addr->ss.ss_family) {
    case AF_INET:
       return ((const struct sockaddr_in *)&addr->ss)->sin_addr.s_addr;
    case AF_INET6:
       return ((uint32_t *)&((const struct sockaddr_in6 *)&addr->ss)->sin6_addr)[3];
    default:
       ast_log(LOG_ERROR, "Unknown address family '%d'.\n",
          addr->ss.ss_family);
       return 0;
    }
 }
ast_sockaddr_ipv4()
uint32_t ast_sockaddr_ipv4 (const struct ast_sockaddr * addr)
Get an IPv4 address of an ast_sockaddr.
Since
1.8
Warning
You should rarely need this function. Only use if you know what you're doing.
Returns
IPv4 address in network byte order
Definition at line 491 of file netsock2.c.
References ast_sockaddr::ss.
Referenced by ast_sockaddr_is_ipv4_multicast(), and multicast_send_control_packet().
 {
    const struct sockaddr_in *sin = (struct sockaddr_in *)&addr->ss;
    return ntohl(sin->sin_addr.s_addr);
 }
ast_sockaddr_ipv4_mapped()
int ast_sockaddr_ipv4_mapped (const struct ast_sockaddr * addr, struct ast_sockaddr * ast_mapped)
Convert an IPv4-mapped IPv6 address into an IPv4 address.
Warning
You should rarely need this function. Only call this if you know what you're doing.
Parameters
addr The IPv4-mapped address to convert
ast_mapped The resulting IPv4 address
Return values
0 Unable to make the conversion
1 Successful conversion
Definition at line 37 of file netsock2.c.
References ast_sockaddr_from_sin, ast_sockaddr_is_ipv4_mapped(), ast_sockaddr_is_ipv6(), and ast_sockaddr::ss.
Referenced by append_ha_core(), ast_apply_ha(), ast_rtcp_read(), ast_rtp_read(), ast_sockaddr_cidr_bits(), ast_sockaddr_cmp(), ast_sockaddr_cmp_addr(), and ast_sockaddr_stringify_fmt().
 {
    const struct sockaddr_in6 *sin6;
    struct sockaddr_in sin4;
    if (!ast_sockaddr_is_ipv6(addr)) {
       return 0;
    }
    if (!ast_sockaddr_is_ipv4_mapped(addr)) {
       return 0;
    }
    sin6 = (const struct sockaddr_in6*)&addr->ss;
    memset(&sin4, 0, sizeof(sin4));
    sin4.sin_family = AF_INET;
    sin4.sin_port = sin6->sin6_port;
    sin4.sin_addr.s_addr = ((uint32_t *)&sin6->sin6_addr)[3];
    ast_sockaddr_from_sin(ast_mapped, &sin4);
    return 1;
 }
ast_sockaddr_is_any()
int ast_sockaddr_is_any (const struct ast_sockaddr * addr)
Determine if the address type is unspecified, or "any" address.
Since
1.8
For IPv4, this would be the address 0.0.0.0, and for IPv6, this would be the address ::. The port number is ignored.
Return values
1 This is an "any" address
0 This is not an "any" address
Definition at line 534 of file netsock2.c.
References ast_sockaddr_is_ipv4(), ast_sockaddr_is_ipv6(), and ast_sockaddr::ss.
Referenced by ast_find_ourip(), ast_set_qos(), ast_sip_ouraddrfor(), ast_tcptls_client_create(), get_address_family_filter(), get_our_media_address(), negotiate_incoming_sdp_stream(), reload_config(), rtp_add_candidates_to_ice(), sip_show_settings(), and sockaddr_is_null_or_any().
 {
    union {
       struct sockaddr_storage ss;
       struct sockaddr_in sin;
       struct sockaddr_in6 sin6;
    } tmp_addr = {
       .ss = addr->ss,
    };
    return (ast_sockaddr_is_ipv4(addr) && (tmp_addr.sin.sin_addr.s_addr == INADDR_ANY)) ||
        (ast_sockaddr_is_ipv6(addr) && IN6_IS_ADDR_UNSPECIFIED(&tmp_addr.sin6.sin6_addr));
 }
ast_sockaddr_is_ipv4()
int ast_sockaddr_is_ipv4 (const struct ast_sockaddr * addr)
Determine if the address is an IPv4 address.
Since
1.8
Warning
You should rarely need this function. Only use if you know what you're doing.
Return values
1 This is an IPv4 address
0 This is an IPv6 or IPv4-mapped IPv6 address
Definition at line 497 of file netsock2.c.
References ast_sockaddr::len, and ast_sockaddr::ss.
Referenced by append_ha_core(), ast_apply_ha(), ast_json_ipaddr(), ast_rtcp_read(), ast_rtp_ice_turn_request(), ast_rtp_prop_set(), ast_rtp_read(), ast_sockaddr_apply_netmask(), ast_sockaddr_is_any(), dump_addr(), dundi_xmit(), hep_queue_cb(), jingle_interpret_ice_udp_transport(), load_module(), negotiate_incoming_sdp_stream(), rtp_add_candidates_to_ice(), and rtp_allocate_transport().
 {
    /*
     * Test addr->len first to be tolerant of an ast_sockaddr_setnull()
     * addr.  In that case addr->len might be the only value initialized.
     */
    return addr->len == sizeof(struct sockaddr_in)
       && addr->ss.ss_family == AF_INET;
 }
ast_sockaddr_is_ipv4_mapped()
int ast_sockaddr_is_ipv4_mapped (const struct ast_sockaddr * addr)
Determine if this is an IPv4-mapped IPv6 address.
Since
1.8
Warning
You should rarely need this function. Only use if you know what you're doing.
Return values
1 This is an IPv4-mapped IPv6 address.
0 This is not an IPv4-mapped IPv6 address.
Definition at line 507 of file netsock2.c.
References ast_sockaddr::len, and ast_sockaddr::ss.
Referenced by add_sdp(), ast_apply_ha(), ast_json_ipaddr(), ast_sip_ouraddrfor(), ast_sockaddr_ipv4_mapped(), build_peer(), and dump_addr().
 {
    const struct sockaddr_in6 *sin6 = (struct sockaddr_in6 *)&addr->ss;
    return addr->len && IN6_IS_ADDR_V4MAPPED(&sin6->sin6_addr);
 }
ast_sockaddr_is_ipv4_multicast()
int ast_sockaddr_is_ipv4_multicast (const struct ast_sockaddr * addr)
Determine if an IPv4 address is a multicast address.
Since
10.0
Parameters
addr the address to check
This function checks if an address is in the 224.0.0.0/4 network block.
Returns
non-zero if this is a multicast address
Definition at line 513 of file netsock2.c.
References ast_sockaddr_ipv4().
Referenced by process_via().
 {
    return ((ast_sockaddr_ipv4(addr) & 0xf0000000) == 0xe0000000);
 }
ast_sockaddr_is_ipv6()
int ast_sockaddr_is_ipv6 (const struct ast_sockaddr * addr)
Determine if this is an IPv6 address.
Since
1.8
Warning
You should rarely need this function. Only use if you know what you're doing.
Return values
1 This is an IPv6 or IPv4-mapped IPv6 address.
0 This is an IPv4 address.
Definition at line 524 of file netsock2.c.
References ast_sockaddr::len, and ast_sockaddr::ss.
Referenced by add_sdp(), ast_apply_ha(), ast_netsock_bindaddr(), ast_ouraddrfor(), ast_rtp_prop_set(), ast_set_qos(), ast_sip_ouraddrfor(), ast_sockaddr_apply_netmask(), ast_sockaddr_ipv4_mapped(), ast_sockaddr_is_any(), ast_sockaddr_is_ipv6_link_local(), ast_tcptls_client_create(), ast_tcptls_server_start(), ast_udptl_new_with_bindaddr(), build_peer(), get_address_family_filter(), hepv3_data_alloc(), load_module(), multicast_send_control_packet(), negotiate_incoming_sdp_stream(), reload_config(), rtp_allocate_transport(), set_host_ipaddr(), and sip_show_settings().
 {
    /*
     * Test addr->len first to be tolerant of an ast_sockaddr_setnull()
     * addr.  In that case addr->len might be the only value initialized.
     */
    return addr->len == sizeof(struct sockaddr_in6)
       && addr->ss.ss_family == AF_INET6;
 }
ast_sockaddr_is_ipv6_link_local()
int ast_sockaddr_is_ipv6_link_local (const struct ast_sockaddr * addr)
Determine if this is a link-local IPv6 address.
Since
1.8
Warning
You should rarely need this function. Only use if you know what you're doing.
Return values
1 This is a link-local IPv6 address.
0 This is link-local IPv6 address.
Definition at line 518 of file netsock2.c.
References ast_sockaddr_is_ipv6(), and ast_sockaddr::ss.
Referenced by ast_sockaddr_stringify_fmt().
 {
    const struct sockaddr_in6 *sin6 = (struct sockaddr_in6 *)&addr->ss;
    return ast_sockaddr_is_ipv6(addr) && IN6_IS_ADDR_LINKLOCAL(&sin6->sin6_addr);
 }
ast_sockaddr_isnull()
static int ast_sockaddr_isnull (const struct ast_sockaddr * addr) inline static
Checks if the ast_sockaddr is null. "null" in this sense essentially means uninitialized, or having a 0 length.
Since
1.8
Parameters
addr Pointer to the ast_sockaddr we wish to check
Return values
1 addr is null
0 addr is non-null.
Definition at line 127 of file netsock2.h.
References ast_sockaddr::len.
Referenced by __ast_http_load(), __iax2_do_register_s(), __iax2_show_peers(), __init_manager(), __rtp_recvfrom(), _ast_sockaddr_to_sin(), _sip_show_peers_one(), acf_channel_read(), add_ice_to_sdp(), add_ice_to_stream(), add_sdp(), append_transaction(), apply_peer(), ast_rtcp_calculate_sr_rr_statistics(), ast_rtcp_generate_nack(), ast_rtcp_generate_report(), ast_rtcp_generate_sdes(), ast_rtp_dtmf_begin(), ast_rtp_dtmf_continuation(), ast_rtp_dtmf_end_with_duration(), ast_rtp_ice_start(), ast_rtp_ice_start_media(), ast_rtp_interpret(), ast_rtp_read(), ast_rtp_remote_address_set(), ast_rtp_sendcng(), ast_rtp_write(), ast_sip_ouraddrfor(), ast_sockaddr_cidr_bits(), ast_sockaddr_stringify_fmt(), ast_tcptls_client_create(), ast_tcptls_server_start(), ast_udptl_read(), ast_udptl_write(), authenticate_reply(), bridge_p2p_rtp_write(), build_peer(), check_for_rtp_changes(), check_rtp_timeout(), create_addr(), create_addr_from_peer(), create_outgoing_sdp_stream(), create_transaction(), dialog_initialize_rtp(), do_monitor(), dundi_show_peer(), dundi_show_peers(), dundi_sockaddr_port(), dundi_sockaddr_stringify_host(), expire_register(), function_iaxpeer(), get_our_media_address(), handle_cli_iax2_show_registry(), handle_response_invite(), handle_show_http(), iax2_ack_registry(), iax2_devicestate(), iax2_do_register(), iax2_poke_peer(), iax2_prov_app(), iax_outputframe(), jingle_interpret_ice_udp_transport(), load_module(), manager_iax2_show_registry(), multicast_send_control_packet(), negotiate_incoming_sdp_stream(), on_dns_update_mwi(), on_dns_update_peer(), on_dns_update_registry(), ooh323_indicate(), ooh323_set_rtp_peer(), parse_register_contact(), peer_iphash_cb(), peercnt_hash_cb(), process_nat(), process_sdp(), realtime_peer(), realtime_update_peer(), realtime_user(), register_verify(), reload_config(), rtcp_debug_test_addr(), rtp_add_candidates_to_ice(), rtp_check_timeout(), rtp_debug_test_addr(), rtp_raw_write(), rtp_write_rtcp_fir(), rtp_write_rtcp_psfb(), send_keepalive(), set_caps(), set_config(), should_drop_packets(), sip_acf_channel_read(), sip_debug_test_addr(), sip_devicestate(), sip_do_debug_peer(), sip_poke_peer(), sip_prepare_socket(), sip_prune_realtime(), sip_send_keepalive(), sip_send_mwi_to_peer(), sip_set_rtp_peer(), sip_show_channel(), sip_show_settings(), sockaddr_is_null_or_any(), socket_process_helper(), transmit_register(), transmit_reinvite_with_sdp(), try_transfer(), udptl_debug_test_addr(), and update_registry().
 {
    return !addr || addr->len == 0;
 }
ast_sockaddr_parse()
int ast_sockaddr_parse (struct ast_sockaddr * addr, const char * str, int flags)
Parse an IPv4 or IPv6 address string.
Since
1.8
Parses a string containing an IPv4 or IPv6 address followed by an optional port (separated by a colon) into a struct ast_sockaddr. The allowed formats are the following:
a.b.c.d a.b.c.d:port a:b:c:...:d [a:b:c:...:d]
Host names are NOT allowed.
Parameters
[out] addr The resulting ast_sockaddr. This MAY be NULL from functions that are performing validity checks only, e.g. ast_parse_arg().
str The string to parse
flags If set to zero, a port MAY be present. If set to PARSE_PORT_IGNORE, a port MAY be present but will be ignored. If set to PARSE_PORT_REQUIRE, a port MUST be present. If set to PARSE_PORT_FORBID, a port MUST NOT be present.
Return values
1 Success
0 Failure
Definition at line 230 of file netsock2.c.
References ast_log, ast_sockaddr_split_hostport(), ast_strdupa, host, ast_sockaddr::len, LOG_ERROR, LOG_WARNING, NULL, S_OR, and ast_sockaddr::ss.
Referenced by __init_manager(), append_ha_core(), apply_acl(), apply_endpoint_acl(), ast_netsock_bind(), ast_parse_arg(), ast_rtp_ice_add_cand(), ast_rtp_ice_turn_request(), ast_sip_get_transport_name(), ast_sockaddr_stringify_port(), AST_TEST_DEFINE(), build_peer(), change_outgoing_sdp_stream_media_address(), corosync_node_alloc(), create_rtp(), evt_gen_auth_method_not_allowed(), evt_gen_chal_resp_failed(), evt_gen_chal_sent(), evt_gen_failed_acl(), evt_gen_inval_acct_id(), evt_gen_inval_password(), evt_gen_inval_transport(), evt_gen_load_avg(), evt_gen_mem_limit(), evt_gen_req_bad_format(), evt_gen_req_no_support(), evt_gen_req_not_allowed(), evt_gen_session_limit(), evt_gen_successful_auth(), evt_gen_unexpected_addr(), handle_cli_rtp_drop_incoming_packets(), internal_dnsmgr_lookup(), ip_identify(), ip_identify_match_handler(), jingle_alloc(), jingle_enable_video(), jingle_interpret_google_transport(), jingle_interpret_ice_udp_transport(), load_module(), logging_on_rx_msg(), logging_on_tx_msg(), multicast_rtp_request(), peer_set_srcaddr(), pjsip_enable_logger_host(), pjsip_log_test_addr(), process_ice_attributes(), process_nat(), process_sdp_a_ice(), proxy_update(), realtime_peer(), reg_source_db(), reload_config(), rtcp_do_debug_ip(), rtcp_message_handler(), rtp_do_debug_ip(), security_event_populate(), session_outgoing_nat_hook(), set_config(), sip_sanitized_host(), sip_uri_domain_cmp(), test_init_rtp_instances(), unicast_rtp_request(), and update_address_with_ice_candidate().
 {
    struct addrinfo hints;
    struct addrinfo   *res;
    char *s;
    char *host;
    char *port;
    int   e;
    s = ast_strdupa(str);
    if (!ast_sockaddr_split_hostport(s, &host, &port, flags)) {
       return 0;
    }
    memset(&hints, 0, sizeof(hints));
    /* Hint to get only one entry from getaddrinfo */
    hints.ai_socktype = SOCK_DGRAM;
 #ifdef AI_NUMERICSERV
    hints.ai_flags = AI_NUMERICHOST | AI_NUMERICSERV;
 #else
    hints.ai_flags = AI_NUMERICHOST;
 #endif
    if ((e = getaddrinfo(host, port, &hints, &res))) {
       if (e != EAI_NONAME) { /* if this was just a host name rather than a ip address, don't print error */
          ast_log(LOG_ERROR, "getaddrinfo(\"%s\", \"%s\", ...): %s\n",
             host, S_OR(port, "(null)"), gai_strerror(e));
       }
       return 0;
    }
    /*
     * I don't see how this could be possible since we're not resolving host
     * names. But let's be careful...
     */
    if (res->ai_next != NULL) {
       ast_log(LOG_WARNING, "getaddrinfo() returned multiple "
          "addresses. Ignoring all but the first.\n");
    }
    if (addr) {
       addr->len = res->ai_addrlen;
       memcpy(&addr->ss, res->ai_addr, addr->len);
    }
    freeaddrinfo(res);
    return 1;
 }
ast_sockaddr_resolve()
int ast_sockaddr_resolve (struct ast_sockaddr ** addrs, const char * str, int flags, int family)
Parses a string with an IPv4 or IPv6 address and place results into an array.
Since
1.8
Parses a string containing a host name or an IPv4 or IPv6 address followed by an optional port (separated by a colon). The result is returned into a array of struct ast_sockaddr. Allowed formats for str are the following:
hostname:port host.example.com:port a.b.c.d a.b.c.d:port a:b:c:...:d [a:b:c:...:d]
Parameters
[out] addrs The resulting array of ast_sockaddrs
str The string to parse
flags If set to zero, a port MAY be present. If set to PARSE_PORT_IGNORE, a port MAY be present but will be ignored. If set to PARSE_PORT_REQUIRE, a port MUST be present. If set to PARSE_PORT_FORBID, a port MUST NOT be present.
family Only addresses of the given family will be returned. Use 0 or AST_AF_UNSPEC to get addresses of all families.
Return values
0 Failure
non-zero The number of elements in addrs array.
Definition at line 280 of file netsock2.c.
References ast_log, ast_malloc, ast_sockaddr_split_hostport(), ast_strdupa, cleanup(), host, LOG_ERROR, NULL, and S_OR.
Referenced by __ast_http_load(), app_exec(), apply_negotiated_sdp_stream(), ast_audiosocket_connect(), ast_sockaddr_resolve_first_af(), ast_sockaddr_stringify_port(), build_peer(), extract_contact_addr(), get_ipaddress(), handle_cli_udptl_set_debug(), ip_identify_match_host_lookup(), launch_netscript(), negotiate_incoming_sdp_stream(), populate_addr(), realtime_peer(), realtime_peer_by_name(), realtime_user(), resolve_first(), and websocket_client_args_create().
 {
    struct addrinfo hints, *res, *ai;
    char *s, *host, *port;
    int   e, i, res_cnt;
    if (!str) {
       *addrs = NULL;
       return 0;
    }
    s = ast_strdupa(str);
    if (!ast_sockaddr_split_hostport(s, &host, &port, flags)) {
       *addrs = NULL;
       return 0;
    }
    memset(&hints, 0, sizeof(hints));
    hints.ai_family = family;
    hints.ai_socktype = SOCK_DGRAM;
    if ((e = getaddrinfo(host, port, &hints, &res))) {
       ast_log(LOG_ERROR, "getaddrinfo(\"%s\", \"%s\", ...): %s\n",
          host, S_OR(port, "(null)"), gai_strerror(e));
       *addrs = NULL;
       return 0;
    }
    res_cnt = 0;
    for (ai = res; ai; ai = ai->ai_next) {
       res_cnt++;
    }
    if (res_cnt == 0) {
       *addrs = NULL;
       goto cleanup;
    }
    if ((*addrs = ast_malloc(res_cnt * sizeof(struct ast_sockaddr))) == NULL) {
       res_cnt = 0;
       goto cleanup;
    }
    i = 0;
    for (ai = res; ai; ai = ai->ai_next) {
       (*addrs)[i].len = ai->ai_addrlen;
       memcpy(&(*addrs)[i].ss, ai->ai_addr, ai->ai_addrlen);
       ++i;
    }
 cleanup:
    freeaddrinfo(res);
    return res_cnt;
 }
ast_sockaddr_resolve_first_af()
int ast_sockaddr_resolve_first_af (struct ast_sockaddr * addr, const char * name, int flag, int family)
Return the first entry from ast_sockaddr_resolve filtered by address family.
Since
16.0
Parses a string containing a host name or an IPv4 or IPv6 address followed by an optional port (separated by a colon). This function only returns the first address into the ast_sockaddr. Allowed formats for name are the following:
hostname:port host.example.com:port a.b.c.d a.b.c.d:port a:b:c:...:d [a:b:c:...:d]
Parameters
[out] addr The resulting ast_sockaddr
name The string to parse
flags If set to zero, a port MAY be present. If set to PARSE_PORT_IGNORE, a port MAY be present but will be ignored. If set to PARSE_PORT_REQUIRE, a port MUST be present. If set to PARSE_PORT_FORBID, a port MUST NOT be present.
family Only addresses of the given family will be returned. Use 0 or AST_AF_UNSPEC to specify any address family. Behavior is ultimately determined by getaddrinfo in how it orders return results. First result is selected to be returned.
Return values
0 Success
non-zero Failure
Warning
Using this function potentially means you have a faulty design.
Return the first entry from ast_sockaddr_resolve filtered by address family.
Definition at line 337 of file netsock2.c.
References ast_debug, ast_free, ast_sockaddr_copy(), and ast_sockaddr_resolve().
Referenced by ast_sip_ouraddrfor(), ast_sockaddr_resolve_first(), ast_sockaddr_resolve_first_transport(), ast_sockaddr_stringify_port(), audiosocket_request(), hepv3_data_alloc(), pjsip_enable_logger_host(), process_sdp_c(), reload_config(), and sip_do_debug_ip().
 {
    struct ast_sockaddr *addrs;
    int addrs_cnt;
    addrs_cnt = ast_sockaddr_resolve(&addrs, name, flag, family);
    if (addrs_cnt <= 0) {
       return 1;
    }
    if (addrs_cnt > 1) {
       ast_debug(1, "Multiple addresses resolving %s, using the first one only\n", name);
    }
    ast_sockaddr_copy(addr, &addrs[0]);
    ast_free(addrs);
    return 0;
 }
ast_sockaddr_setnull()
static void ast_sockaddr_setnull (struct ast_sockaddr * addr) inline static
Sets address addr to null.
Since
1.8
Return values
void
Definition at line 140 of file netsock2.h.
References ast_sockaddr::len.
Referenced by __ast_http_load(), __expire_registry(), ast_rtp_ice_start_media(), ast_tcptls_client_create(), ast_tcptls_server_start(), ast_udptl_stop(), build_peer(), check_for_rtp_changes(), do_register_expire(), get_local_address(), load_module(), manager_set_defaults(), multicast_rtp_request(), reload(), reload_config(), rtp_add_candidates_to_ice(), rtp_reload(), set_peer_defaults(), and socket_process_helper().
 {
    addr->len = 0;
 }
ast_sockaddr_split_hostport()
int ast_sockaddr_split_hostport (char * str, char ** host, char ** port, int flags)
Splits a string into its host and port components.
Since
1.8
Parameters
[in] str The string to parse. May be modified by writing a NUL at the end of the host part.
[out] host Pointer to the host component within str.
[out] port Pointer to the port component within str.
flags If set to zero, a port MAY be present. If set to PARSE_PORT_IGNORE, a port MAY be present but will be ignored. If set to PARSE_PORT_REQUIRE, a port MUST be present. If set to PARSE_PORT_FORBID, a port MUST NOT be present.
Return values
1 Success
0 Failure
Definition at line 164 of file netsock2.c.
References ast_debug, ast_log, LOG_WARNING, NULL, PARSE_PORT_FORBID, PARSE_PORT_IGNORE, PARSE_PORT_MASK, PARSE_PORT_REQUIRE, and str.
Referenced by ast_ari_channels_external_media(), ast_sockaddr_parse(), ast_sockaddr_resolve(), ast_sockaddr_stringify_port(), extract_host_from_hostport(), peer_set_srcaddr(), rtcp_do_debug_ip(), rtp_do_debug_ip(), setup_stunaddr(), sip_parse_host(), and unicast_rtp_request().
 {
    char *s = str;
    char *orig_str = str;/* Original string in case the port presence is incorrect. */
    char *host_end = NULL;/* Delay terminating the host in case the port presence is incorrect. */
    ast_debug(5, "Splitting '%s' into...\n", str);
    *host = NULL;
    *port = NULL;
    if (*s == '[') {
       *host = ++s;
       for (; *s && *s != ']'; ++s) {
       }
       if (*s == ']') {
          host_end = s;
          ++s;
       }
       if (*s == ':') {
          *port = s + 1;
       }
    } else {
       *host = s;
       for (; *s; ++s) {
          if (*s == ':') {
             if (*port) {
                *port = NULL;
                break;
             } else {
                *port = s;
             }
          }
       }
       if (*port) {
          host_end = *port;
          ++*port;
       }
    }
    switch (flags & PARSE_PORT_MASK) {
    case PARSE_PORT_IGNORE:
       *port = NULL;
       break;
    case PARSE_PORT_REQUIRE:
       if (*port == NULL) {
          ast_log(LOG_WARNING, "Port missing in %s\n", orig_str);
          return 0;
       }
       break;
    case PARSE_PORT_FORBID:
       if (*port != NULL) {
          ast_log(LOG_WARNING, "Port disallowed in %s\n", orig_str);
          return 0;
       }
       break;
    }
    /* Can terminate the host string now if needed. */
    if (host_end) {
       *host_end = '\0';
    }
    ast_debug(5, "...host '%s' and port '%s'.\n", *host, *port ? *port : "");
    return 1;
 }
ast_sockaddr_stringify()
static char* ast_sockaddr_stringify (const struct ast_sockaddr * addr) inline static
Wrapper around ast_sockaddr_stringify_fmt() with default format.
Since
1.8
Returns
same as ast_sockaddr_stringify_fmt()
Definition at line 260 of file netsock2.h.
References AST_SOCKADDR_STR_DEFAULT, and ast_sockaddr_stringify_fmt().
Referenced by __ast_http_load(), __find_callno(), __rtp_recvfrom(), __sip_xmit(), _sip_show_peer(), add_sdp(), append_ha_core(), apply_acl(), apply_contact_acl(), ast_apply_ha(), ast_ari_callback(), ast_ari_websocket_session_write(), ast_audiosocket_connect(), ast_ha_join(), ast_netsock_bindaddr(), ast_parse_arg(), ast_rtcp_calculate_sr_rr_statistics(), ast_rtcp_interpret(), ast_rtcp_read(), ast_rtcp_write(), ast_rtp_dtmf_begin(), ast_rtp_dtmf_continuation(), ast_rtp_dtmf_end_with_duration(), ast_rtp_ice_add_cand(), ast_rtp_ice_start(), ast_rtp_interpret(), ast_rtp_prop_set(), ast_rtp_read(), ast_rtp_remote_address_set(), ast_rtp_sendcng(), ast_sip_ouraddrfor(), ast_tcptls_client_create(), ast_tcptls_client_start(), ast_tcptls_server_root(), ast_tcptls_server_start(), AST_TEST_DEFINE(), ast_udptl_read(), ast_udptl_write(), ast_websocket_close(), ast_websocket_uri_cb(), bridge_p2p_rtp_write(), channel_read_rtp(), check_peer_ok(), check_via(), cli_print_body(), create_dtmf_frame(), debug_ha_sense_appended(), dnsmgr_refresh(), do_message_auth(), dump_addr(), dump_ipaddr(), dundi_rexmit(), dundi_showframe(), dundi_xmit(), find_tpeer(), handle_audiosocket_connection(), handle_call_token(), handle_cli_iax2_show_callno_limits(), handle_cli_iax2_show_registry(), handle_cli_udptl_set_debug(), handle_command_response(), handle_connection(), handle_incoming(), handle_manager_show_settings(), handle_request_bye(), handle_request_do(), handle_request_invite(), handle_request_register(), handle_request_subscribe(), handle_response(), handle_response_info(), handle_response_message(), handle_response_notify(), handle_response_refer(), handle_show_http(), handle_tcptls_connection(), iax2_ack_registry(), iax2_devicestate(), iax2_prov_app(), iax2_trunk_queue(), iax_showframe(), ice_reset_session(), ip_identify_match_check(), ip_identify_match_host_lookup(), launch_netscript(), load_module(), manager_iax2_show_registry(), match_to_var_list_append(), on_dns_update_mwi(), on_dns_update_peer(), on_dns_update_registry(), parse_register_contact(), pjsip_enable_logger_host(), process_cn_rfc3389(), process_dtmf_rfc2833(), process_sdp(), raw_hangup(), receive_message(), reg_source_db(), register_verify(), registry_rerequest(), reload_config(), retrans_pkt(), rtcp_do_debug_ip(), rtp_allocate_transport(), rtp_do_debug_ip(), rtp_raw_write(), rtp_transport_wide_cc_feedback_produce(), send_packet(), send_request(), send_response(), session_destroy_fn(), set_config(), set_destination(), set_peercnt_limit(), sip_acf_channel_read(), sip_allow_anyrtp_remote(), sip_send_keepalive(), sip_set_rtp_peer(), sip_show_channel(), sip_show_settings(), sip_show_tcp(), sip_tcptls_read(), sockaddr_handler_fn(), socket_process_helper(), socket_process_meta(), stasis_app_message_handler(), stun_monitor_request(), timing_read(), transport_create(), transport_read(), and update_registry().
 {
    return ast_sockaddr_stringify_fmt(addr, AST_SOCKADDR_STR_DEFAULT);
 }
ast_sockaddr_stringify_addr()
static char* ast_sockaddr_stringify_addr (const struct ast_sockaddr * addr) inline static
Wrapper around ast_sockaddr_stringify_fmt() to return an address only.
Since
1.8
Returns
same as ast_sockaddr_stringify_fmt()
Definition at line 290 of file netsock2.h.
References ast_sockaddr_cidr_bits(), AST_SOCKADDR_STR_ADDR, and ast_sockaddr_stringify_fmt().
Referenced by __attempt_transmit(), __init_manager(), _iax2_show_peers_one(), _sip_show_peer(), _sip_show_peers_one(), acf_channel_read(), action_hangup(), action_login(), add_sdp(), ast_apply_acl_internal(), ast_ha_join(), ast_ha_join_cidr(), ast_ha_output(), ast_json_ipaddr(), ast_ouraddrfor(), auth_http_callback(), authenticate(), build_peer(), build_user(), calltoken_required(), check_access(), check_for_nat(), cli_print_body(), configure_local_rtp(), do_message(), function_iaxpeer(), function_sippeer(), generic_http_callback(), get_input(), handle_cli_iax2_show_channels(), handle_cli_iax2_show_peer(), handle_command_response(), handle_showmanconn(), hep_queue_cb(), httpstatus_callback(), localnet_to_vl_append(), match_to_var_list_append(), ooh323_get_rtp_peer(), ooh323_set_rtp_peer(), parse_register_contact(), peercnt_add(), peercnt_modify(), peercnt_remove(), pjsip_enable_logger_host(), publish_cluster_discovery_to_stasis_full(), purge_sessions(), realtime_peer(), realtime_update_peer(), realtime_user(), register_verify(), reload_config(), sched_delay_remove(), session_do(), show_channels_cb(), show_chanstats_cb(), sip_acf_channel_read(), sip_do_debug_ip(), sip_do_debug_peer(), sip_show_channel(), sip_show_settings(), transport_create(), transport_read(), unicast_rtp_request(), and update_registry().
 {
    return ast_sockaddr_stringify_fmt(addr, AST_SOCKADDR_STR_ADDR);
 }
ast_sockaddr_stringify_addr_remote()
static char* ast_sockaddr_stringify_addr_remote (const struct ast_sockaddr * addr) inline static
Wrapper around ast_sockaddr_stringify_fmt() to return an address only.
Since
1.8
Note
This address will be suitable for passing to a remote machine via the application layer. For example, the scope-id on a link-local IPv6 address will be stripped.
Returns
same as ast_sockaddr_stringify_fmt()
Definition at line 317 of file netsock2.h.
References AST_SOCKADDR_STR_ADDR_REMOTE, and ast_sockaddr_stringify_fmt().
Referenced by add_ice_to_sdp(), add_ice_to_stream(), add_sdp(), change_outgoing_sdp_stream_media_address(), and copy_via_headers().
 {
    return ast_sockaddr_stringify_fmt(addr, AST_SOCKADDR_STR_ADDR_REMOTE);
 }
ast_sockaddr_stringify_fmt()
char* ast_sockaddr_stringify_fmt (const struct ast_sockaddr * addr, int format)
Convert a socket address to a string.
Since
1.8
This will be of the form a.b.c.d:xyz for IPv4 and [a:b:c:...:d]:xyz for IPv6.
This function is thread-safe. The returned string is on static thread-specific storage.
Parameters
addr The input to be stringified
format one of the following: AST_SOCKADDR_STR_DEFAULT: a.b.c.d:xyz for IPv4 [a:b:c:...:d]:xyz for IPv6. AST_SOCKADDR_STR_ADDR: address only a.b.c.d for IPv4 a:b:c:...:d for IPv6. AST_SOCKADDR_STR_HOST: address only, suitable for a URL a.b.c.d for IPv4 [a:b:c:...:d] for IPv6. AST_SOCKADDR_STR_PORT: port only
Note
The string pointer returned by this function will point to a string that will be changed whenever any form of ast_sockaddr_stringify_fmt is called on that thread. Because of this, it is important that if you use this function, you use the string before another use of this function is made elsewhere in the same thread. The easiest way to accomplish this is by immediately copying the string to a buffer with something like ast_strdupa.
Return values
(null) addr is null
"" An error occurred during processing
string The stringified form of the address
Definition at line 65 of file netsock2.c.
References ast_log, ast_sockaddr_ipv4_mapped(), ast_sockaddr_is_ipv6_link_local(), ast_sockaddr_isnull(), AST_SOCKADDR_STR_ADDR, AST_SOCKADDR_STR_DEFAULT, AST_SOCKADDR_STR_FORMAT_MASK, AST_SOCKADDR_STR_HOST, AST_SOCKADDR_STR_PORT, AST_SOCKADDR_STR_REMOTE, ast_sockaddr_stringify_buf, ast_str_buffer(), ast_str_set(), ast_str_thread_get(), host, ast_sockaddr::len, LOG_ERROR, NULL, ast_sockaddr::ss, and str.
Referenced by ast_sockaddr_stringify(), ast_sockaddr_stringify_addr(), ast_sockaddr_stringify_addr_remote(), ast_sockaddr_stringify_host(), ast_sockaddr_stringify_host_remote(), ast_sockaddr_stringify_port(), ast_sockaddr_stringify_remote(), create_outgoing_sdp_stream(), and statsd_init().
 {
    struct ast_sockaddr sa_ipv4;
    const struct ast_sockaddr *sa_tmp;
    char host[NI_MAXHOST];
    char port[NI_MAXSERV];
    struct ast_str *str;
    int e;
    static const size_t size = sizeof(host) - 1 + sizeof(port) - 1 + 4;
    if (ast_sockaddr_isnull(sa)) {
       return "(null)";
    }
    if (!(str = ast_str_thread_get(&ast_sockaddr_stringify_buf, size))) {
       return "";
    }
    if (ast_sockaddr_ipv4_mapped(sa, &sa_ipv4)) {
       sa_tmp = &sa_ipv4;
    } else {
       sa_tmp = sa;
    }
    if ((e = getnameinfo((struct sockaddr *)&sa_tmp->ss, sa_tmp->len,
               format & AST_SOCKADDR_STR_ADDR ? host : NULL,
               format & AST_SOCKADDR_STR_ADDR ? sizeof(host) : 0,
               format & AST_SOCKADDR_STR_PORT ? port : 0,
               format & AST_SOCKADDR_STR_PORT ? sizeof(port): 0,
               NI_NUMERICHOST | NI_NUMERICSERV))) {
       ast_log(LOG_ERROR, "getnameinfo(): %s\n", gai_strerror(e));
       return "";
    }
    if ((format & AST_SOCKADDR_STR_REMOTE) == AST_SOCKADDR_STR_REMOTE) {
       char *p;
       if (ast_sockaddr_is_ipv6_link_local(sa) && (p = strchr(host, '%'))) {
          *p = '\0';
       }
    }
    switch ((format & AST_SOCKADDR_STR_FORMAT_MASK))  {
    case AST_SOCKADDR_STR_DEFAULT:
       ast_str_set(&str, 0, sa_tmp->ss.ss_family == AF_INET6 ?
             "[%s]:%s" : "%s:%s", host, port);
       break;
    case AST_SOCKADDR_STR_ADDR:
       ast_str_set(&str, 0, "%s", host);
       break;
    case AST_SOCKADDR_STR_HOST:
       ast_str_set(&str, 0,
              sa_tmp->ss.ss_family == AF_INET6 ? "[%s]" : "%s", host);
       break;
    case AST_SOCKADDR_STR_PORT:
       ast_str_set(&str, 0, "%s", port);
       break;
    default:
       ast_log(LOG_ERROR, "Invalid format\n");
       return "";
    }
    return ast_str_buffer(str);
 }
ast_sockaddr_stringify_host()
static char* ast_sockaddr_stringify_host (const struct ast_sockaddr * addr) inline static
Wrapper around ast_sockaddr_stringify_fmt() to return an address only, suitable for a URL (with brackets for IPv6).
Since
1.8
Returns
same as ast_sockaddr_stringify_fmt()
Definition at line 331 of file netsock2.h.
References AST_SOCKADDR_STR_HOST, and ast_sockaddr_stringify_fmt().
Referenced by build_peer(), change_outgoing_sdp_stream_media_address(), dundi_show_peer(), dundi_show_trans(), dundi_sockaddr_stringify_host(), get_ipaddress(), jingle_add_google_candidates_to_transport(), jingle_add_ice_udp_candidates_to_transport(), process_nat(), reg_source_db(), session_outgoing_nat_hook(), and setup_udptl_connection().
 {
    return ast_sockaddr_stringify_fmt(addr, AST_SOCKADDR_STR_HOST);
 }
ast_sockaddr_stringify_host_remote()
static char* ast_sockaddr_stringify_host_remote (const struct ast_sockaddr * addr) inline static
Wrapper around ast_sockaddr_stringify_fmt() to return an address only, suitable for a URL (with brackets for IPv6).
Since
1.8
Note
This address will be suitable for passing to a remote machine via the application layer. For example, the scope-id on a link-local IPv6 address will be stripped.
Returns
same as ast_sockaddr_stringify_fmt()
Definition at line 349 of file netsock2.h.
References AST_SOCKADDR_STR_HOST_REMOTE, and ast_sockaddr_stringify_fmt().
Referenced by add_diversion(), add_rpid(), build_callid_registry(), build_reply_digest(), create_addr_from_peer(), initreqprep(), sip_poke_peer(), sip_sanitized_host(), and transmit_notify_with_mwi().
 {
    return ast_sockaddr_stringify_fmt(addr, AST_SOCKADDR_STR_HOST_REMOTE);
 }
ast_sockaddr_stringify_port()
static char* ast_sockaddr_stringify_port (const struct ast_sockaddr * addr) inline static
Wrapper around ast_sockaddr_stringify_fmt() to return a port only.
Since
1.8
Returns
same as ast_sockaddr_stringify_fmt()
Definition at line 362 of file netsock2.h.
References ast_sockaddr_apply_netmask(), ast_sockaddr_parse(), ast_sockaddr_resolve(), ast_sockaddr_resolve_first_af(), ast_sockaddr_split_hostport(), AST_SOCKADDR_STR_PORT, ast_sockaddr_stringify_fmt(), host, name, result, and str.
Referenced by _iax2_show_peers_one(), _sip_show_peers_one(), add_ice_to_sdp(), add_ice_to_stream(), add_sdp(), ast_json_ipaddr(), handle_cli_iax2_set_debug(), handle_cli_iax2_show_peer(), httpstatus_callback(), jingle_add_google_candidates_to_transport(), jingle_add_ice_udp_candidates_to_transport(), realtime_peer(), realtime_peer_by_addr(), realtime_update_peer(), realtime_user(), register_verify(), sip_acf_channel_read(), and unicast_rtp_request().
 {
    return ast_sockaddr_stringify_fmt(addr, AST_SOCKADDR_STR_PORT);
 }
ast_sockaddr_stringify_remote()
static char* ast_sockaddr_stringify_remote (const struct ast_sockaddr * addr) inline static
Wrapper around ast_sockaddr_stringify_fmt() with default format.
Since
1.8
Note
This address will be suitable for passing to a remote machine via the application layer. For example, the scope-id on a link-local IPv6 address will be stripped.
Returns
same as ast_sockaddr_stringify_fmt()
Definition at line 277 of file netsock2.h.
References AST_SOCKADDR_STR_DEFAULT_REMOTE, and ast_sockaddr_stringify_fmt().
Referenced by build_callid_pvt(), build_contact(), build_via(), and generate_uri().
 {
    return ast_sockaddr_stringify_fmt(addr, AST_SOCKADDR_STR_DEFAULT_REMOTE);
 }
ast_transport2str()
const char* ast_transport2str (enum ast_transport transport)
Returns a string representation of an ast_transport.
Since
12.3
Return values
Name of the tranpsort if it is defined
Undefined if the transport is undefined
Definition at line 566 of file netsock2.c.
References AST_TRANSPORT_TCP, AST_TRANSPORT_TLS, AST_TRANSPORT_UDP, AST_TRANSPORT_WS, and AST_TRANSPORT_WSS.
Referenced by sip_show_channel().
 {
    switch (transport) {
    case AST_TRANSPORT_TLS:
       return "TLS";
    case AST_TRANSPORT_UDP:
       return "UDP";
    case AST_TRANSPORT_TCP:
       return "TCP";
    case AST_TRANSPORT_WS:
       return "WS";
    case AST_TRANSPORT_WSS:
       return "WSS";
    }
    return "Undefined";
 }