Asterisk - The Open Source Telephony Project: fskmodem_int.c File Reference
fskmodem_int.c File Reference
FSK Modulator/Demodulator.
#include "asterisk.h"
#include "asterisk/fskmodem.h"
Macros
#define BWLIST {75,800}
#define FLIST {1400,1800,1200,2200,1300,2100}
#define IGET_SAMPLE iget_sample(&buffer, len)
#define NBW 2
#define NF 6
#define STATE_GET_BYTE 3
#define STATE_SEARCH_STARTBIT 0
#define STATE_SEARCH_STARTBIT2 1
#define STATE_SEARCH_STARTBIT3 2
Functions
int fsk_serial (fsk_data *fskd, short *buffer, int *len, int *outbyte)
int fskmodem_init (fsk_data *fskd)
static int get_bit_raw (fsk_data *fskd, short *buffer, int *len)
static int ibpdfilter (struct filter_struct *fs, int in)
static int ibpfilter (struct filter_struct *fs, int in)
static int idemodulator (fsk_data *fskd, int *retval, int x)
static int iget_sample (short **buffer, int *len)
Variables
static double coef_in [NF][NBW][8]
Coefficients for input filters Coefficients table, generated by program "mkfilter" mkfilter is part of the zapatatelephony.org distribution Format: coef[IDX_FREC][IDX_BW][IDX_COEF] IDX_COEF = 0 => 1/GAIN IDX_COEF = 1-6 => Coefficientes y[n].
static double coef_out [NBW][8]
Coefficients for output filter Coefficients table, generated by program "mkfilter" Format: coef[IDX_BW][IDX_COEF] IDX_COEF = 0 => 1/GAIN IDX_COEF = 1-6 => Coefficientes y[n].
Detailed Description
FSK Modulator/Demodulator.
Author
Mark Spencer marks.nosp@m.ter@.nosp@m.digiu.nosp@m.m.co.nosp@m.m
Includes code and algorithms from the Zapata library.
Definition in file fskmodem_int.c.
Macro Definition Documentation
BWLIST
#define BWLIST {75,800}
Definition at line 40 of file fskmodem_int.c.
FLIST
#define FLIST {1400,1800,1200,2200,1300,2100}
Definition at line 42 of file fskmodem_int.c.
IGET_SAMPLE
#define IGET_SAMPLE iget_sample(&buffer, len)
Definition at line 58 of file fskmodem_int.c.
Referenced by fsk_serial(), and get_bit_raw().
NBW
#define NBW 2
Definition at line 39 of file fskmodem_int.c.
NF
#define NF 6
Definition at line 41 of file fskmodem_int.c.
STATE_GET_BYTE
#define STATE_GET_BYTE 3
Definition at line 47 of file fskmodem_int.c.
Referenced by fsk_serial().
STATE_SEARCH_STARTBIT
#define STATE_SEARCH_STARTBIT 0
Definition at line 44 of file fskmodem_int.c.
Referenced by fsk_serial().
STATE_SEARCH_STARTBIT2
#define STATE_SEARCH_STARTBIT2 1
Definition at line 45 of file fskmodem_int.c.
Referenced by fsk_serial().
STATE_SEARCH_STARTBIT3
#define STATE_SEARCH_STARTBIT3 2
Definition at line 46 of file fskmodem_int.c.
Referenced by fsk_serial().
Function Documentation
fsk_serial()
int fsk_serial (fsk_data * fskd, short * buffer, int * len, int * outbyte)
Definition at line 222 of file fskmodem_int.c.
References a, get_bit_raw(), idemodulator(), IGET_SAMPLE, fsk_data::instop, fsk_data::ispb, len(), fsk_data::nbit, fsk_data::parity, fsk_data::state, STATE_GET_BYTE, STATE_SEARCH_STARTBIT, STATE_SEARCH_STARTBIT2, STATE_SEARCH_STARTBIT3, fsk_data::xi1, and fsk_data::xi2.
Referenced by callerid_feed(), callerid_feed_jp(), and tdd_feed().
 {
    int a;
    int i, j, n1, r;
    int samples = 0;
    int olen;
    int beginlen = *len;
    int beginlenx;
    switch (fskd->state) {
       /* Pick up where we left off */
    case STATE_SEARCH_STARTBIT2:
       goto search_startbit2;
    case STATE_SEARCH_STARTBIT3:
       goto search_startbit3;
    case STATE_GET_BYTE:
       goto getbyte;
    }
    /* We await for start bit  */
    do {
       /* this was jesus's nice, reasonable, working (at least with RTTY) code
       to look for the beginning of the start bit. Unfortunately, since TTY/TDD's
       just start sending a start bit with nothing preceding it at the beginning
       of a transmission (what a LOSING design), we cant do it this elegantly */
       /* NOT USED
             if (demodulator(zap,&x1))
                return -1;
             for(;;) {
                if (demodulator(zap,&x2))
                   return -1;
                if (x1>0 && x2<0) break;
                x1=x2;
             }
       */
       /* this is now the imprecise, losing, but functional code to detect the
       beginning of a start bit in the TDD sceanario. It just looks for sufficient
       level to maybe, perhaps, guess, maybe that its maybe the beginning of
       a start bit, perhaps. This whole thing stinks! */
       beginlenx = beginlen; /* just to avoid unused war warnings */
       if (idemodulator(fskd, &fskd->xi1, IGET_SAMPLE))
          return -1;
       samples++;
       for(;;) {
 search_startbit2:
          if (*len <= 0) {
             fskd->state = STATE_SEARCH_STARTBIT2;
             return 0;
          }
          samples++;
          if (idemodulator(fskd, &fskd->xi2, IGET_SAMPLE))
             return -1;
 #if 0
          printf("xi2 = %d ", fskd->xi2);
 #endif
          if (fskd->xi2 < 512) {
             break;
          }
       }
 search_startbit3:
       /* We await for 0.5 bits before using DPLL */
       i = fskd->ispb / 2;
       if (*len < i) {
          fskd->state = STATE_SEARCH_STARTBIT3;
          return 0;
       }
       for (; i > 0; i--) {
          if (idemodulator(fskd, &fskd->xi1, IGET_SAMPLE))
             return(-1);
 #if 0
          printf("xi1 = %d ", fskd->xi1);
 #endif
          samples++;
       }
       /* x1 must be negative (start bit confirmation) */
    } while (fskd->xi1 > 0);
    fskd->state = STATE_GET_BYTE;
 getbyte:
    /* Need at least 80 samples (for 1200) or
       1320 (for 45.5) to be sure we'll have a byte */
    if (fskd->nbit < 8) {
       if (*len < 1320)
          return 0;
    } else {
       if (*len < 80)
          return 0;
    }
    /* Now we read the data bits */
    j = fskd->nbit;
    for (a = n1 = 0; j; j--) {
       olen = *len;
       i = get_bit_raw(fskd, buffer, len);
       buffer += (olen - *len);
       if (i == -1)
          return -1;
       if (i)
          n1++;
       a >>= 1;
       a |= i;
    }
    j = 8 - fskd->nbit;
    a >>= j;
    /* We read parity bit (if exists) and check parity */
    if (fskd->parity) {
       olen = *len;
       i = get_bit_raw(fskd, buffer, len);
       buffer += (olen - *len);
       if (i == -1)
          return -1;
       if (i)
          n1++;
       if (fskd->parity == 1) {   /* parity=1 (even) */
          if (n1 & 1)
             a |= 0x100;       /* error */
       } else {             /* parity=2 (odd) */
          if (!(n1 & 1))
             a |= 0x100;       /* error */
       }
    }
    /* We read STOP bits. All of them must be 1 */
    for (j = fskd->instop; j; j--) {
       r = get_bit_raw(fskd, buffer, len);
       if (r == -1)
          return -1;
       if (!r)
          a |= 0x200;
    }
    /* And finally we return
     * Bit 8 : Parity error
     * Bit 9 : Framming error
    */
    *outbyte = a;
    fskd->state = STATE_SEARCH_STARTBIT;
    return 1;
 }
fskmodem_init()
int fskmodem_init (fsk_data * fskd)
Definition at line 195 of file fskmodem_int.c.
References fsk_data::bw, coef_in, coef_out, fsk_data::demod_filter, fsk_data::f_mark_idx, fsk_data::f_space_idx, filter_struct::icoefs, filter_struct::ip, filter_struct::ixv, filter_struct::iyv, fsk_data::mark_filter, and fsk_data::space_filter.
Referenced by callerid_new(), and tdd_new().
 {
    int i;
    fskd->space_filter.ip  = 0;
    fskd->mark_filter.ip   = 0;
    fskd->demod_filter.ip  = 0;
    for ( i = 0 ; i < 7 ; i++ ) {
       fskd->space_filter.icoefs[i] =
          coef_in[fskd->f_space_idx][fskd->bw][i] * 256;
       fskd->space_filter.ixv[i] = 0;;
       fskd->space_filter.iyv[i] = 0;;
       fskd->mark_filter.icoefs[i] =
          coef_in[fskd->f_mark_idx][fskd->bw][i] * 256;
       fskd->mark_filter.ixv[i] = 0;;
       fskd->mark_filter.iyv[i] = 0;;
       fskd->demod_filter.icoefs[i] =
          coef_out[fskd->bw][i] * 1024;
       fskd->demod_filter.ixv[i] = 0;;
       fskd->demod_filter.iyv[i] = 0;;
    }
    return 0;
 }
get_bit_raw()
static int get_bit_raw (fsk_data * fskd, short * buffer, int * len) static
Definition at line 165 of file fskmodem_int.c.
References fsk_data::icont, idemodulator(), IGET_SAMPLE, fsk_data::pllids, fsk_data::pllispb, fsk_data::pllispb2, and fsk_data::xi0.
Referenced by fsk_serial().
 {
    /* This function implements a DPLL to synchronize with the bits */
    int f;
    int ix;
    /* PLL coeffs are set up in callerid_new */
    for (f = 0;;) {
       if (idemodulator(fskd, &ix, IGET_SAMPLE)) return(-1);
       if ((ix * fskd->xi0) < 0) { /* Transicion */
          if (!f) {
             if (fskd->icont < (fskd->pllispb2)) {
                fskd->icont += fskd->pllids;
             } else {
                fskd->icont -= fskd->pllids;
             }
             f = 1;
          }
       }
       fskd->xi0 = ix;
       fskd->icont += 32;
       if (fskd->icont > fskd->pllispb) {
          fskd->icont -= fskd->pllispb;
          break;
       }
    }
    f = (ix > 0) ? 0x80 : 0;
    return f;
 }
ibpdfilter()
static int ibpdfilter (struct filter_struct * fs, int in) inline static
Integer Pass Band demodulator filter
Definition at line 95 of file fskmodem_int.c.
References filter_struct::icoefs, filter_struct::ip, filter_struct::ixv, and filter_struct::iyv.
Referenced by idemodulator().
 {
    int i,j;
    int s;
    int64_t s_interim;
    /* integer filter */
    s =  in * fs->icoefs[0];
    fs->ixv[(fs->ip + 6) & 7] = s;
    s =      (fs->ixv[fs->ip]           + fs->ixv[(fs->ip + 6) & 7]) +
       6  * (fs->ixv[(fs->ip + 1) & 7] + fs->ixv[(fs->ip + 5) & 7]) +
       15 * (fs->ixv[(fs->ip + 2) & 7] + fs->ixv[(fs->ip + 4) & 7]) +
       20 *  fs->ixv[(fs->ip + 3) & 7];
    for (i = 1, j = fs->ip; i < 7; i++, j++) {
       /* Promote operation to 64 bit to prevent overflow that occurred in 32 bit) */
       s_interim = (int64_t)(fs->iyv[j & 7]) *
             (int64_t)(fs->icoefs[i]) /
             (int64_t)(1024);
       s += (int) s_interim;
    }
    fs->iyv[j & 7] = s;
    fs->ip++;
    fs->ip &= 7;
    return s;
 }
ibpfilter()
static int ibpfilter (struct filter_struct * fs, int in) inline static
Integer Band Pass filter
Definition at line 124 of file fskmodem_int.c.
References filter_struct::icoefs, filter_struct::ip, filter_struct::ixv, and filter_struct::iyv.
Referenced by idemodulator().
 {
    int i, j;
    int s;
    int64_t s_interim;
    /* integer filter */
    s =  in * fs->icoefs[0] / 256;
    fs->ixv[(fs->ip + 6) & 7] = s;
    s = (fs->ixv[(fs->ip + 6) & 7] - fs->ixv[fs->ip])
       + 3 * (fs->ixv[(fs->ip + 2) & 7] - fs->ixv[(fs->ip + 4) & 7]);
    for (i = 1, j = fs->ip; i < 7; i++, j++) {
       s_interim = (int64_t)(fs->iyv[j & 7]) *
             (int64_t)(fs->icoefs[i]) /
             (int64_t)(256);
       s += (int) s_interim;
    }
    fs->iyv[j & 7] = s;
    fs->ip++;
    fs->ip &= 7;
    return s;
 }
idemodulator()
static int idemodulator (fsk_data * fskd, int * retval, int x) inline static
Definition at line 149 of file fskmodem_int.c.
References fsk_data::demod_filter, ibpdfilter(), ibpfilter(), id, fsk_data::mark_filter, and fsk_data::space_filter.
Referenced by fsk_serial(), and get_bit_raw().
 {
    int is, im, id;
    int ilin2;
    is = ibpfilter(&fskd->space_filter, x);
    im = ibpfilter(&fskd->mark_filter, x);
    ilin2 = ((im * im) - (is * is)) / (256 * 256);
    id = ibpdfilter(&fskd->demod_filter, ilin2);
    *retval = id;
    return 0;
 }
iget_sample()
static int iget_sample (short ** buffer, int * len) inline static
Definition at line 49 of file fskmodem_int.c.
References retval.
 {
    int retval;
    retval = (int) **buffer;
    (*buffer)++;
    (*len)--;
    return retval;
 }
Variable Documentation
coef_in
double coef_in[NF][NBW][8] static
Coefficients for input filters Coefficients table, generated by program "mkfilter" mkfilter is part of the zapatatelephony.org distribution Format: coef[IDX_FREC][IDX_BW][IDX_COEF] IDX_COEF = 0 => 1/GAIN IDX_COEF = 1-6 => Coefficientes y[n].
Definition at line 66 of file fskmodem_int.c.
Referenced by fskmodem_init().
coef_out
double coef_out[NBW][8] static
Initial value:
={
   { 1.3868644653e-08,-6.3283665042e-01,4.0895057217e+00,-1.1020074592e+01,1.5850766191e+01,-1.2835109292e+01,5.5477477340e+00,0.0000000000e+00,
   },  { 3.1262119724e-03,-7.8390522307e-03,8.5209627801e-02,-4.0804129163e-01,1.1157139955e+00,-1.8767603680e+00,1.8916395224e+00,0.0000000000e+00
   },
}
Coefficients for output filter Coefficients table, generated by program "mkfilter" Format: coef[IDX_BW][IDX_COEF] IDX_COEF = 0 => 1/GAIN IDX_COEF = 1-6 => Coefficientes y[n].
Definition at line 88 of file fskmodem_int.c.
Referenced by fskmodem_init().