Asterisk - The Open Source Telephony Project: res_mwi_external_ami.c File Reference
res_mwi_external_ami.c File Reference
AMI wrapper for external MWI.
#include "asterisk.h"
#include "asterisk/module.h"
#include "asterisk/res_mwi_external.h"
#include "asterisk/manager.h"
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int load_module (void)
static int mwi_mailbox_delete (struct mansession *s, const struct message *m)
static int mwi_mailbox_get (struct mansession *s, const struct message *m)
static int mwi_mailbox_update (struct mansession *s, const struct message *m)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_DEFAULT , .description = "AMI support for external MWI" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_CHANNEL_DEPEND - 5, .requires = "res_mwi_external", }
static const struct ast_module_info * ast_module_info = &__mod_info
Detailed Description
AMI wrapper for external MWI.
Author
Richard Mudgett rmudg.nosp@m.ett@.nosp@m.digiu.nosp@m.m.co.nosp@m.m
See Also:
CREDITS
Definition in file res_mwi_external_ami.c.
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 370 of file res_mwi_external_ami.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 370 of file res_mwi_external_ami.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 370 of file res_mwi_external_ami.c.
load_module()
static int load_module (void) static
Definition at line 348 of file res_mwi_external_ami.c.
References ast_manager_register_xml, AST_MODFLAG_DEFAULT, AST_MODPRI_CHANNEL_DEPEND, AST_MODULE_INFO(), AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, AST_MODULE_SUPPORT_CORE, ASTERISK_GPL_KEY, EVENT_FLAG_CALL, EVENT_FLAG_REPORTING, mwi_mailbox_delete(), mwi_mailbox_get(), mwi_mailbox_update(), and unload_module().
 {
    int res;
    res = 0;
    res |= ast_manager_register_xml("MWIGet", EVENT_FLAG_CALL | EVENT_FLAG_REPORTING, mwi_mailbox_get);
    res |= ast_manager_register_xml("MWIDelete", EVENT_FLAG_CALL, mwi_mailbox_delete);
    res |= ast_manager_register_xml("MWIUpdate", EVENT_FLAG_CALL, mwi_mailbox_update);
    if (res) {
       unload_module();
       return AST_MODULE_LOAD_DECLINE;
    }
    return AST_MODULE_LOAD_SUCCESS;
 }
mwi_mailbox_delete()
static int mwi_mailbox_delete (struct mansession * s, const struct message * m) static
Definition at line 244 of file res_mwi_external_ami.c.
References ast_free, ast_mwi_mailbox_delete(), ast_mwi_mailbox_delete_by_regex(), ast_regex_string_to_regex_pattern(), ast_str_buffer(), ast_str_create, ast_strlen_zero, astman_get_header(), astman_send_ack(), astman_send_error(), astman_send_error_va(), and NULL.
Referenced by load_module().
 {
    const char *mailbox_id = astman_get_header(m, "Mailbox");
    if (ast_strlen_zero(mailbox_id)) {
       astman_send_error(s, m, "Missing mailbox parameter in request");
       return 0;
    }
    if (*mailbox_id == '/') {
       struct ast_str *regex_string;
       regex_string = ast_str_create(strlen(mailbox_id) + 1);
       if (!regex_string) {
          astman_send_error(s, m, "Memory Allocation Failure");
          return 0;
       }
       /* Make "/regex/" into "regex" */
       if (ast_regex_string_to_regex_pattern(mailbox_id, &regex_string) != 0) {
          astman_send_error_va(s, m, "Mailbox regex format invalid in: %s", mailbox_id);
          ast_free(regex_string);
          return 0;
       }
       ast_mwi_mailbox_delete_by_regex(ast_str_buffer(regex_string));
       ast_free(regex_string);
    } else {
       ast_mwi_mailbox_delete(mailbox_id);
    }
    astman_send_ack(s, m, NULL);
    return 0;
 }
mwi_mailbox_get()
static int mwi_mailbox_get (struct mansession * s, const struct message * m) static
Definition at line 147 of file res_mwi_external_ami.c.
References AO2_ALLOC_OPT_LOCK_NOLOCK, ao2_container_alloc_list, ao2_iterator_destroy(), ao2_iterator_init(), ao2_iterator_next, AO2_ITERATOR_UNLINK, ao2_link, ao2_ref, ast_free, ast_mwi_mailbox_get(), ast_mwi_mailbox_get_by_regex(), ast_mwi_mailbox_get_id(), ast_mwi_mailbox_get_msgs_new(), ast_mwi_mailbox_get_msgs_old(), ast_mwi_mailbox_unref, ast_regex_string_to_regex_pattern(), ast_str_buffer(), ast_str_create, ast_strlen_zero, astman_append(), astman_get_header(), astman_send_error(), astman_send_error_va(), astman_send_list_complete_end(), astman_send_list_complete_start(), astman_send_listack(), id, mailbox, mailboxes, and NULL.
Referenced by load_module().
 {
    char id_text[256];
    const char *id;
    const char *mailbox_id = astman_get_header(m, "Mailbox");
    const struct ast_mwi_mailbox_object *mailbox;
    struct ao2_container *mailboxes;
    unsigned count;
    struct ao2_iterator iter;
    if (ast_strlen_zero(mailbox_id)) {
       astman_send_error(s, m, "Missing mailbox parameter in request");
       return 0;
    }
    if (*mailbox_id == '/') {
       struct ast_str *regex_string;
       regex_string = ast_str_create(strlen(mailbox_id) + 1);
       if (!regex_string) {
          astman_send_error(s, m, "Memory Allocation Failure");
          return 0;
       }
       /* Make "/regex/" into "regex" */
       if (ast_regex_string_to_regex_pattern(mailbox_id, &regex_string) != 0) {
          astman_send_error_va(s, m, "Mailbox regex format invalid in: %s", mailbox_id);
          ast_free(regex_string);
          return 0;
       }
       mailboxes = ast_mwi_mailbox_get_by_regex(ast_str_buffer(regex_string));
       ast_free(regex_string);
    } else {
       mailboxes = ao2_container_alloc_list(AO2_ALLOC_OPT_LOCK_NOLOCK, 0, NULL, NULL);
       if (mailboxes) {
          mailbox = ast_mwi_mailbox_get(mailbox_id);
          if (mailbox) {
             if (!ao2_link(mailboxes, (void *) mailbox)) {
                ao2_ref(mailboxes, -1);
                mailboxes = NULL;
             }
             ast_mwi_mailbox_unref(mailbox);
          }
       }
    }
    if (!mailboxes) {
       astman_send_error(s, m, "Mailbox container creation failure");
       return 0;
    }
    astman_send_listack(s, m, "Mailboxes will follow", "start");
    id = astman_get_header(m, "ActionID");
    if (!ast_strlen_zero(id)) {
       snprintf(id_text, sizeof(id_text), "ActionID: %s\r\n", id);
    } else {
       id_text[0] = '\0';
    }
    /* Output mailbox list. */
    count = 0;
    iter = ao2_iterator_init(mailboxes, AO2_ITERATOR_UNLINK);
    for (; (mailbox = ao2_iterator_next(&iter)); ast_mwi_mailbox_unref(mailbox)) {
       ++count;
       astman_append(s,
          "Event: MWIGet\r\n"
          "Mailbox: %s\r\n"
          "OldMessages: %u\r\n"
          "NewMessages: %u\r\n"
          "%s"
          "\r\n",
          ast_mwi_mailbox_get_id(mailbox),
          ast_mwi_mailbox_get_msgs_old(mailbox),
          ast_mwi_mailbox_get_msgs_new(mailbox),
          id_text);
    }
    ao2_iterator_destroy(&iter);
    ao2_ref(mailboxes, -1);
    astman_send_list_complete_start(s, m, "MWIGetComplete", count);
    astman_send_list_complete_end(s);
    return 0;
 }
mwi_mailbox_update()
static int mwi_mailbox_update (struct mansession * s, const struct message * m) static
Definition at line 290 of file res_mwi_external_ami.c.
References ast_mwi_mailbox_alloc(), ast_mwi_mailbox_set_msgs_new(), ast_mwi_mailbox_set_msgs_old(), ast_mwi_mailbox_unref, ast_mwi_mailbox_update(), ast_strlen_zero, astman_get_header(), astman_send_ack(), astman_send_error(), astman_send_error_va(), mailbox, and NULL.
Referenced by load_module().
 {
    const char *mailbox_id = astman_get_header(m, "Mailbox");
    const char *msgs_old = astman_get_header(m, "OldMessages");
    const char *msgs_new = astman_get_header(m, "NewMessages");
    struct ast_mwi_mailbox_object *mailbox;
    unsigned int num_old;
    unsigned int num_new;
    if (ast_strlen_zero(mailbox_id)) {
       astman_send_error(s, m, "Missing mailbox parameter in request");
       return 0;
    }
    num_old = 0;
    if (!ast_strlen_zero(msgs_old)) {
       if (sscanf(msgs_old, "%u", &num_old) != 1) {
          astman_send_error_va(s, m, "Invalid OldMessages: %s", msgs_old);
          return 0;
       }
    }
    num_new = 0;
    if (!ast_strlen_zero(msgs_new)) {
       if (sscanf(msgs_new, "%u", &num_new) != 1) {
          astman_send_error_va(s, m, "Invalid NewMessages: %s", msgs_new);
          return 0;
       }
    }
    mailbox = ast_mwi_mailbox_alloc(mailbox_id);
    if (!mailbox) {
       astman_send_error(s, m, "Mailbox object creation failure");
       return 0;
    }
    /* Update external mailbox. */
    ast_mwi_mailbox_set_msgs_old(mailbox, num_old);
    ast_mwi_mailbox_set_msgs_new(mailbox, num_new);
    if (ast_mwi_mailbox_update(mailbox)) {
       astman_send_error(s, m, "Update attempt failed");
    } else {
       astman_send_ack(s, m, NULL);
    }
    ast_mwi_mailbox_unref(mailbox);
    return 0;
 }
unload_module()
static int unload_module (void) static
Definition at line 339 of file res_mwi_external_ami.c.
References ast_manager_unregister().
Referenced by load_module().
 {
    ast_manager_unregister("MWIGet");
    ast_manager_unregister("MWIDelete");
    ast_manager_unregister("MWIUpdate");
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_DEFAULT , .description = "AMI support for external MWI" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_CHANNEL_DEPEND - 5, .requires = "res_mwi_external", } static
Definition at line 370 of file res_mwi_external_ami.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 370 of file res_mwi_external_ami.c.