Asterisk - The Open Source Telephony Project: res_sorcery_astdb.c File Reference
res_sorcery_astdb.c File Reference
Sorcery Astdb Object Wizard.
#include "asterisk.h"
#include <regex.h>
#include "asterisk/module.h"
#include "asterisk/sorcery.h"
#include "asterisk/astdb.h"
#include "asterisk/json.h"
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int load_module (void)
static int make_astdb_prefix_pattern (char *tree, const char *regex)
static void sorcery_astdb_close (void *data)
static int sorcery_astdb_create (const struct ast_sorcery *sorcery, void *data, void *object)
static int sorcery_astdb_delete (const struct ast_sorcery *sorcery, void *data, void *object)
static struct ast_variable * sorcery_astdb_filter_objectset (struct ast_variable *objectset, const struct ast_sorcery *sorcery, const char *type)
Internal helper function which returns a filtered objectset.
static void * sorcery_astdb_open (const char *data)
static void * sorcery_astdb_retrieve_fields (const struct ast_sorcery *sorcery, void *data, const char *type, const struct ast_variable *fields)
static void * sorcery_astdb_retrieve_fields_common (const struct ast_sorcery *sorcery, void *data, const char *type, const struct ast_variable *fields, struct ao2_container *objects)
Internal helper function which retrieves an object, or multiple objects, using fields for criteria.
static void * sorcery_astdb_retrieve_id (const struct ast_sorcery *sorcery, void *data, const char *type, const char *id)
static void sorcery_astdb_retrieve_multiple (const struct ast_sorcery *sorcery, void *data, const char *type, struct ao2_container *objects, const struct ast_variable *fields)
static void sorcery_astdb_retrieve_prefix (const struct ast_sorcery *sorcery, void *data, const char *type, struct ao2_container *objects, const char *prefix, const size_t prefix_len)
static void sorcery_astdb_retrieve_regex (const struct ast_sorcery *sorcery, void *data, const char *type, struct ao2_container *objects, const char *regex)
static int sorcery_astdb_update (const struct ast_sorcery *sorcery, void *data, void *object)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_GLOBAL_SYMBOLS | AST_MODFLAG_LOAD_ORDER , .description = "Sorcery Astdb Object Wizard" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_REALTIME_DRIVER, }
static const struct ast_module_info * ast_module_info = &__mod_info
static struct ast_sorcery_wizard astdb_object_wizard
Detailed Description
Sorcery Astdb Object Wizard.
Author
Joshua Colp jcolp.nosp@m.@dig.nosp@m.ium.c.nosp@m.om
Definition in file res_sorcery_astdb.c.
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 434 of file res_sorcery_astdb.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 434 of file res_sorcery_astdb.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 434 of file res_sorcery_astdb.c.
load_module()
static int load_module (void) static
Definition at line 414 of file res_sorcery_astdb.c.
References AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, and ast_sorcery_wizard_register.
Referenced by unload_module().
 {
    if (ast_sorcery_wizard_register(&astdb_object_wizard)) {
       return AST_MODULE_LOAD_DECLINE;
    }
    return AST_MODULE_LOAD_SUCCESS;
 }
make_astdb_prefix_pattern()
static int make_astdb_prefix_pattern (char * tree, const char * regex) static
Definition at line 235 of file res_sorcery_astdb.c.
Referenced by sorcery_astdb_retrieve_regex().
 {
    const char *src;
    char *dst;
    for (dst = tree, src = regex + 1; *src; ++src) {
       if (*src == '\\') {
          /* Escaped regex char. */
          ++src;
          if (!*src) {
             /* Invalid regex.  The caller escaped the string terminator. */
             return -1;
          }
       } else if (*src == '$') {
          if (!src[1]) {
             /* Remove the tail anchor character. */
             *dst = '\0';
             return 0;
          }
       } else if (strchr(".?*+{[(|", *src)) {
          /*
           * The regex is not a simple prefix pattern.
           *
           * XXX With more logic, it is possible to simply
           * use the current prefix pattern.  The last character
           * needs to be removed if possible when the current regex
           * token is "?*{".  Also the rest of the regex pattern
           * would need to be checked for subgroup/alternation.
           * Subgroup/alternation is too complex for a simple prefix
           * match.
           */
          dst = tree;
          break;
       }
       *dst++ = *src;
    }
    if (dst != tree) {
       *dst++ = '%';
    }
    *dst = '\0';
    return 0;
 }
sorcery_astdb_close()
static void sorcery_astdb_close (void * data) static
Definition at line 409 of file res_sorcery_astdb.c.
References ast_free.
 {
    ast_free(data);
 }
sorcery_astdb_create()
static int sorcery_astdb_create (const struct ast_sorcery * sorcery, void * data, void * object) static
Definition at line 66 of file res_sorcery_astdb.c.
References ast_db_put(), ast_json_dump_string, ast_json_free(), ast_json_unref(), ast_sorcery_object_get_id(), ast_sorcery_object_get_type(), ast_sorcery_objectset_json_create(), NULL, prefix, RAII_VAR, and value.
Referenced by sorcery_astdb_update().
 {
    RAII_VAR(struct ast_json *, objset, ast_sorcery_objectset_json_create(sorcery, object), ast_json_unref);
    RAII_VAR(char *, value, NULL, ast_json_free);
    const char *prefix = data;
    char family[strlen(prefix) + strlen(ast_sorcery_object_get_type(object)) + 2];
    if (!objset || !(value = ast_json_dump_string(objset))) {
       return -1;
    }
    snprintf(family, sizeof(family), "%s/%s", prefix, ast_sorcery_object_get_type(object));
    return ast_db_put(family, ast_sorcery_object_get_id(object), value);
 }
sorcery_astdb_delete()
static int sorcery_astdb_delete (const struct ast_sorcery * sorcery, void * data, void * object) static
Definition at line 384 of file res_sorcery_astdb.c.
References ast_db_del(), ast_db_get(), ast_sorcery_object_get_id(), ast_sorcery_object_get_type(), prefix, and value.
 {
    const char *prefix = data;
    char family[strlen(prefix) + strlen(ast_sorcery_object_get_type(object)) + 2];
    char value[2];
    snprintf(family, sizeof(family), "%s/%s", prefix, ast_sorcery_object_get_type(object));
    if (ast_db_get(family, ast_sorcery_object_get_id(object), value, sizeof(value))) {
       return -1;
    }
    return ast_db_del(family, ast_sorcery_object_get_id(object));
 }
sorcery_astdb_filter_objectset()
static struct ast_variable* sorcery_astdb_filter_objectset (struct ast_variable * objectset, const struct ast_sorcery * sorcery, const char * type) static
Internal helper function which returns a filtered objectset.
The following are filtered out of the objectset:
Fields that are not registered with sorcery.
Parameters
objectset Objectset to filter.
sorcery The sorcery instance that is requesting an objectset.
type The object type
Returns
The filtered objectset
Definition at line 93 of file res_sorcery_astdb.c.
References ao2_cleanup, ast_debug, ast_log, ast_sorcery_get_object_type(), ast_sorcery_is_object_field_registered(), ast_variables_destroy(), LOG_WARNING, ast_sorcery_object_type::name, ast_variable::next, and NULL.
Referenced by sorcery_astdb_retrieve_fields_common(), sorcery_astdb_retrieve_id(), sorcery_astdb_retrieve_prefix(), and sorcery_astdb_retrieve_regex().
 {
    struct ast_variable *previous = NULL, *field = objectset;
    struct ast_sorcery_object_type *object_type;
    object_type = ast_sorcery_get_object_type(sorcery, type);
    if (!object_type) {
       ast_log(LOG_WARNING, "Unknown sorcery object type %s. Expect errors\n", type);
       return objectset;
    }
    while (field) {
       struct ast_variable *removed;
       if (ast_sorcery_is_object_field_registered(object_type, field->name)) {
          previous = field;
          field = field->next;
          continue;
       }
       ast_debug(1, "Filtering out astdb field '%s' from retrieval\n", field->name);
       if (previous) {
          previous->next = field->next;
       } else {
          objectset = field->next;
       }
       removed = field;
       field = field->next;
       removed->next = NULL;
       ast_variables_destroy(removed);
    }
    ao2_cleanup(object_type);
    return objectset;
 }
sorcery_astdb_open()
static void * sorcery_astdb_open (const char * data) static
Definition at line 399 of file res_sorcery_astdb.c.
References ast_strdup, ast_strlen_zero, and NULL.
 {
    /* We require a prefix for family string generation, or else stuff could mix together */
    if (ast_strlen_zero(data)) {
       return NULL;
    }
    return ast_strdup(data);
 }
sorcery_astdb_retrieve_fields()
static void * sorcery_astdb_retrieve_fields (const struct ast_sorcery * sorcery, void * data, const char * type, const struct ast_variable * fields) static
Definition at line 186 of file res_sorcery_astdb.c.
References NULL, and sorcery_astdb_retrieve_fields_common().
 {
    return sorcery_astdb_retrieve_fields_common(sorcery, data, type, fields, NULL);
 }
sorcery_astdb_retrieve_fields_common()
static void* sorcery_astdb_retrieve_fields_common (const struct ast_sorcery * sorcery, void * data, const char * type, const struct ast_variable * fields, struct ao2_container * objects) static
Internal helper function which retrieves an object, or multiple objects, using fields for criteria.
Definition at line 135 of file res_sorcery_astdb.c.
References ao2_cleanup, ao2_link, ast_db_freetree(), ast_db_gettree(), ast_json_load_string(), ast_json_to_ast_variables(), AST_JSON_TO_AST_VARS_CODE_SUCCESS, ast_json_unref(), ast_sorcery_alloc(), ast_sorcery_objectset_apply(), ast_variable_lists_match(), ast_variables_destroy(), ast_db_entry::data, ast_db_entry::key, ast_db_entry::next, NULL, prefix, RAII_VAR, and sorcery_astdb_filter_objectset().
Referenced by sorcery_astdb_retrieve_fields(), and sorcery_astdb_retrieve_multiple().
 {
    const char *prefix = data;
    char family[strlen(prefix) + strlen(type) + 2];
    RAII_VAR(struct ast_db_entry *, entries, NULL, ast_db_freetree);
    struct ast_db_entry *entry;
    snprintf(family, sizeof(family), "%s/%s", prefix, type);
    if (!(entries = ast_db_gettree(family, NULL))) {
       return NULL;
    }
    for (entry = entries; entry; entry = entry->next) {
       const char *key = entry->key + strlen(family) + 2;
       RAII_VAR(struct ast_json *, json, NULL, ast_json_unref);
       struct ast_json_error error;
       RAII_VAR(struct ast_variable *, existing, NULL, ast_variables_destroy);
       void *object = NULL;
       if (!(json = ast_json_load_string(entry->data, &error))) {
          return NULL;
       }
       if (ast_json_to_ast_variables(json, &existing) != AST_JSON_TO_AST_VARS_CODE_SUCCESS) {
          return NULL;
       }
       existing = sorcery_astdb_filter_objectset(existing, sorcery, type);
       if (fields && !ast_variable_lists_match(existing, fields, 0)) {
          continue;
       }
       if (!(object = ast_sorcery_alloc(sorcery, type, key)) ||
          ast_sorcery_objectset_apply(sorcery, object, existing)) {
          ao2_cleanup(object);
          return NULL;
       }
       if (!objects) {
          return object;
       }
       ao2_link(objects, object);
       ao2_cleanup(object);
    }
    return NULL;
 }
sorcery_astdb_retrieve_id()
static void * sorcery_astdb_retrieve_id (const struct ast_sorcery * sorcery, void * data, const char * type, const char * id) static
Definition at line 191 of file res_sorcery_astdb.c.
References ao2_cleanup, ast_db_get_allocated(), ast_debug, ast_free_ptr(), ast_json_load_string(), ast_json_to_ast_variables(), AST_JSON_TO_AST_VARS_CODE_SUCCESS, ast_json_unref(), ast_sorcery_alloc(), ast_sorcery_objectset_apply(), ast_variables_destroy(), NULL, prefix, RAII_VAR, sorcery_astdb_filter_objectset(), and value.
 {
    const char *prefix = data;
    char family[strlen(prefix) + strlen(type) + 2];
    RAII_VAR(char *, value, NULL, ast_free_ptr);
    RAII_VAR(struct ast_json *, json, NULL, ast_json_unref);
    struct ast_json_error error;
    RAII_VAR(struct ast_variable *, objset, NULL, ast_variables_destroy);
    void *object = NULL;
    snprintf(family, sizeof(family), "%s/%s", prefix, type);
    if (ast_db_get_allocated(family, id, &value)
       || !(json = ast_json_load_string(value, &error))
       || (ast_json_to_ast_variables(json, &objset) != AST_JSON_TO_AST_VARS_CODE_SUCCESS)
       || !(objset = sorcery_astdb_filter_objectset(objset, sorcery, type))
       || !(object = ast_sorcery_alloc(sorcery, type, id))
       || ast_sorcery_objectset_apply(sorcery, object, objset)) {
       ast_debug(3, "Failed to retrieve object '%s' from astdb\n", id);
       ao2_cleanup(object);
       return NULL;
    }
    return object;
 }
sorcery_astdb_retrieve_multiple()
static void sorcery_astdb_retrieve_multiple (const struct ast_sorcery * sorcery, void * data, const char * type, struct ao2_container * objects, const struct ast_variable * fields) static
Definition at line 217 of file res_sorcery_astdb.c.
References sorcery_astdb_retrieve_fields_common().
 {
    sorcery_astdb_retrieve_fields_common(sorcery, data, type, fields, objects);
 }
sorcery_astdb_retrieve_prefix()
static void sorcery_astdb_retrieve_prefix (const struct ast_sorcery * sorcery, void * data, const char * type, struct ao2_container * objects, const char * prefix, const size_t prefix_len) static
Definition at line 332 of file res_sorcery_astdb.c.
References ao2_cleanup, ao2_link, ast_db_freetree(), ast_db_gettree_by_prefix(), ast_json_load_string(), ast_json_to_ast_variables(), AST_JSON_TO_AST_VARS_CODE_SUCCESS, ast_json_unref(), ast_sorcery_alloc(), ast_sorcery_objectset_apply(), ast_variables_destroy(), ast_db_entry::data, ast_db_entry::key, ast_db_entry::next, NULL, RAII_VAR, and sorcery_astdb_filter_objectset().
 {
    const char *family_prefix = data;
    size_t family_len = strlen(family_prefix) + strlen(type) + 1; /* +1 for slash delimiter */
    char family[family_len + 1];
    char tree[prefix_len + 1];
    RAII_VAR(struct ast_db_entry *, entries, NULL, ast_db_freetree);
    struct ast_db_entry *entry;
    snprintf(tree, sizeof(tree), "%.*s", (int) prefix_len, prefix);
    snprintf(family, sizeof(family), "%s/%s", family_prefix, type);
    if (!(entries = ast_db_gettree_by_prefix(family, tree))) {
       return;
    }
    for (entry = entries; entry; entry = entry->next) {
       /* The key in the entry includes the family, so we need to strip it out */
       const char *key = entry->key + family_len + 2;
       RAII_VAR(struct ast_json *, json, NULL, ast_json_unref);
       struct ast_json_error error;
       RAII_VAR(void *, object, NULL, ao2_cleanup);
       RAII_VAR(struct ast_variable *, objset, NULL, ast_variables_destroy);
       if (!(json = ast_json_load_string(entry->data, &error))
          || (ast_json_to_ast_variables(json, &objset) != AST_JSON_TO_AST_VARS_CODE_SUCCESS)
          || !(objset = sorcery_astdb_filter_objectset(objset, sorcery, type))
          || !(object = ast_sorcery_alloc(sorcery, type, key))
          || ast_sorcery_objectset_apply(sorcery, object, objset)) {
          return;
       }
       ao2_link(objects, object);
    }
 }
sorcery_astdb_retrieve_regex()
static void sorcery_astdb_retrieve_regex (const struct ast_sorcery * sorcery, void * data, const char * type, struct ao2_container * objects, const char * regex) static
Definition at line 278 of file res_sorcery_astdb.c.
References ao2_cleanup, ao2_link, ast_db_freetree(), ast_db_gettree(), ast_json_load_string(), ast_json_to_ast_variables(), AST_JSON_TO_AST_VARS_CODE_SUCCESS, ast_json_unref(), ast_sorcery_alloc(), ast_sorcery_objectset_apply(), ast_variables_destroy(), ast_db_entry::data, ast_db_entry::key, make_astdb_prefix_pattern(), ast_db_entry::next, NULL, prefix, RAII_VAR, and sorcery_astdb_filter_objectset().
 {
    const char *prefix = data;
    char family[strlen(prefix) + strlen(type) + 2];
    char tree[strlen(regex) + 1];
    RAII_VAR(struct ast_db_entry *, entries, NULL, ast_db_freetree);
    regex_t expression;
    struct ast_db_entry *entry;
    snprintf(family, sizeof(family), "%s/%s", prefix, type);
    if (regex[0] == '^') {
       /*
        * For performance reasons, try to create an astDB prefix
        * pattern from the regex to reduce the number of entries
        * retrieved from astDB for regex to then match.
        */
       if (make_astdb_prefix_pattern(tree, regex)) {
          return;
       }
    } else {
       tree[0] = '\0';
    }
    if (!(entries = ast_db_gettree(family, tree))
       || regcomp(&expression, regex, REG_EXTENDED | REG_NOSUB)) {
       return;
    }
    for (entry = entries; entry; entry = entry->next) {
       /* The key in the entry includes the family, so we need to strip it out for regex purposes */
       const char *key = entry->key + strlen(family) + 2;
       RAII_VAR(struct ast_json *, json, NULL, ast_json_unref);
       struct ast_json_error error;
       RAII_VAR(void *, object, NULL, ao2_cleanup);
       RAII_VAR(struct ast_variable *, objset, NULL, ast_variables_destroy);
       if (regexec(&expression, key, 0, NULL, 0)) {
          continue;
       } else if (!(json = ast_json_load_string(entry->data, &error))
          || (ast_json_to_ast_variables(json, &objset) != AST_JSON_TO_AST_VARS_CODE_SUCCESS)
          || !(objset = sorcery_astdb_filter_objectset(objset, sorcery, type))
          || !(object = ast_sorcery_alloc(sorcery, type, key))
          || ast_sorcery_objectset_apply(sorcery, object, objset)) {
          regfree(&expression);
          return;
       }
       ao2_link(objects, object);
    }
    regfree(&expression);
 }
sorcery_astdb_update()
static int sorcery_astdb_update (const struct ast_sorcery * sorcery, void * data, void * object) static
Definition at line 368 of file res_sorcery_astdb.c.
References ast_db_get(), ast_sorcery_object_get_id(), ast_sorcery_object_get_type(), prefix, sorcery_astdb_create(), and value.
 {
    const char *prefix = data;
    char family[strlen(prefix) + strlen(ast_sorcery_object_get_type(object)) + 2], value[2];
    snprintf(family, sizeof(family), "%s/%s", prefix, ast_sorcery_object_get_type(object));
    /* It is okay for the value to be truncated, we are only checking that it exists */
    if (ast_db_get(family, ast_sorcery_object_get_id(object), value, sizeof(value))) {
       return -1;
    }
    /* The only difference between update and create is that for update the object must already exist */
    return sorcery_astdb_create(sorcery, data, object);
 }
unload_module()
static int unload_module (void) static
Definition at line 423 of file res_sorcery_astdb.c.
References AST_MODFLAG_GLOBAL_SYMBOLS, AST_MODFLAG_LOAD_ORDER, AST_MODPRI_REALTIME_DRIVER, AST_MODULE_INFO(), AST_MODULE_SUPPORT_CORE, ast_sorcery_wizard_unregister(), ASTERISK_GPL_KEY, and load_module().
 {
    ast_sorcery_wizard_unregister(&astdb_object_wizard);
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_GLOBAL_SYMBOLS | AST_MODFLAG_LOAD_ORDER , .description = "Sorcery Astdb Object Wizard" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_REALTIME_DRIVER, } static
Definition at line 434 of file res_sorcery_astdb.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 434 of file res_sorcery_astdb.c.
astdb_object_wizard
struct ast_sorcery_wizard astdb_object_wizard static
Definition at line 52 of file res_sorcery_astdb.c.