Asterisk - The Open Source Telephony Project: dundi-parser.c File Reference
dundi-parser.c File Reference
Distributed Universal Number Discovery (DUNDi)
#include "asterisk.h"
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include "asterisk/frame.h"
#include "asterisk/utils.h"
#include "asterisk/dundi.h"
#include "dundi-parser.h"
Data Structures
struct dundi_ie
Functions
static void dump_answer (char *output, int maxlen, void *value, int len)
static void dump_byte (char *output, int maxlen, void *value, int len)
static void dump_cause (char *output, int maxlen, void *value, int len)
static void dump_cbypass (char *output, int maxlen, void *value, int len)
static void dump_eid (char *output, int maxlen, void *value, int len)
static void dump_encrypted (char *output, int maxlen, void *value, int len)
static void dump_hint (char *output, int maxlen, void *value, int len)
static void dump_ies (unsigned char *iedata, int spaces, int len)
static void dump_int (char *output, int maxlen, void *value, int len)
static void dump_raw (char *output, int maxlen, void *value, int len)
static void dump_short (char *output, int maxlen, void *value, int len)
static void dump_string (char *output, int maxlen, void *value, int len)
char * dundi_eid_to_str_short (char *s, int maxlen, dundi_eid *eid)
int dundi_eid_zero (dundi_eid *eid)
char * dundi_flags2str (char *buf, int bufsiz, int flags)
char * dundi_hint2str (char *buf, int bufsiz, int flags)
const char * dundi_ie2str (int ie)
int dundi_ie_append (struct dundi_ie_data *ied, unsigned char ie)
int dundi_ie_append_addr (struct dundi_ie_data *ied, unsigned char ie, struct sockaddr_in *sin)
int dundi_ie_append_answer (struct dundi_ie_data *ied, unsigned char ie, dundi_eid *eid, unsigned char protocol, unsigned short flags, unsigned short weight, char *data)
int dundi_ie_append_byte (struct dundi_ie_data *ied, unsigned char ie, unsigned char dat)
int dundi_ie_append_cause (struct dundi_ie_data *ied, unsigned char ie, unsigned char cause, char *data)
int dundi_ie_append_eid (struct dundi_ie_data *ied, unsigned char ie, dundi_eid *eid)
int dundi_ie_append_encdata (struct dundi_ie_data *ied, unsigned char ie, unsigned char *iv, void *data, int datalen)
int dundi_ie_append_hint (struct dundi_ie_data *ied, unsigned char ie, unsigned short flags, char *data)
int dundi_ie_append_int (struct dundi_ie_data *ied, unsigned char ie, unsigned int value)
int dundi_ie_append_raw (struct dundi_ie_data *ied, unsigned char ie, void *data, int datalen)
int dundi_ie_append_short (struct dundi_ie_data *ied, unsigned char ie, unsigned short value)
int dundi_ie_append_str (struct dundi_ie_data *ied, unsigned char ie, char *str)
int dundi_parse_ies (struct dundi_ies *ies, unsigned char *data, int datalen)
void dundi_set_error (void(*func)(const char *))
void dundi_set_output (void(*func)(const char *))
void dundi_showframe (struct dundi_hdr *fhi, int rx, struct ast_sockaddr *sin, int datalen)
int dundi_str_short_to_eid (dundi_eid *eid, const char *s)
static void internalerror (const char *str)
static void internaloutput (const char *str)
static char * proto2str (int proto, char *buf, int bufsiz)
Variables
static void(* errorf)(const char *str) = internalerror
static struct dundi_ie infoelts []
static void(* outputf)(const char *str) = internaloutput
Detailed Description
Distributed Universal Number Discovery (DUNDi)
Definition in file dundi-parser.c.
Function Documentation
dump_answer()
static void dump_answer (char * output, int maxlen, void * value, int len) static
Definition at line 284 of file dundi-parser.c.
References answer(), ast_eid_to_str(), dundi_answer::data, dundi_flags2str(), dundi_answer::eid, dundi_answer::flags, proto2str(), dundi_answer::protocol, tmp(), and dundi_answer::weight.
 {
    struct dundi_answer *answer;
    char proto[40];
    char flags[40];
    char eid_str[40];
    char tmp[512]="";
    int datalen;
    if (len < sizeof(*answer)) {
       snprintf(output, maxlen, "Invalid Answer");
       return;
    }
    answer = (struct dundi_answer *)(value);
    datalen = len - offsetof(struct dundi_answer, data);
    if (datalen > sizeof(tmp) - 1)
       datalen = sizeof(tmp) - 1;
    memcpy(tmp, answer->data, datalen);
    tmp[datalen] = '\0';
    ast_eid_to_str(eid_str, sizeof(eid_str), &answer->eid);
    snprintf(output, maxlen, "[%s] %d <%s/%s> from [%s]",
       dundi_flags2str(flags, sizeof(flags), ntohs(answer->flags)),
       ntohs(answer->weight),
       proto2str(answer->protocol, proto, sizeof(proto)),
          tmp, eid_str);
 }
dump_byte()
static void dump_byte (char * output, int maxlen, void * value, int len) static
Definition at line 216 of file dundi-parser.c.
References ast_copy_string().
 {
    if (len == (int)sizeof(unsigned char))
       snprintf(output, maxlen, "%d", *((unsigned char *)value));
    else
       ast_copy_string(output, "Invalid BYTE", maxlen);
 }
dump_cause()
static void dump_cause (char * output, int maxlen, void * value, int len) static
Definition at line 159 of file dundi-parser.c.
References ARRAY_LEN, ast_strlen_zero, dundi_cause::causecode, causes, desc, and dundi_cause::desc.
 {
    static const char * const causes[] = {
       "SUCCESS",
       "GENERAL",
       "DYNAMIC",
       "NOAUTH" ,
       };
    char tmp2[256];
    struct dundi_cause *cause;
    int datalen;
    int causecode;
    if (len < sizeof(*cause)) {
       snprintf(output, maxlen, "<invalid contents>");
       return;
    }
    cause = (struct dundi_cause*) value;
    causecode = cause->causecode;
    datalen = len - offsetof(struct dundi_cause, desc);
    if (datalen > sizeof(tmp2) - 1)
       datalen = sizeof(tmp2) - 1;
    memcpy(tmp2, cause->desc, datalen);
    tmp2[datalen] = '\0';
    if (causecode < ARRAY_LEN(causes)) {
       if (ast_strlen_zero(tmp2))
          snprintf(output, maxlen, "%s", causes[causecode]);
       else
          snprintf(output, maxlen, "%s: %s", causes[causecode], tmp2);
    } else {
       if (ast_strlen_zero(tmp2))
          snprintf(output, maxlen, "%d", causecode);
       else
          snprintf(output, maxlen, "%d: %s", causecode, tmp2);
    }
 }
dump_cbypass()
static void dump_cbypass (char * output, int maxlen, void * value, int len) static
Definition at line 98 of file dundi-parser.c.
 {
    snprintf(output, maxlen, "Bypass Caches");
 }
dump_eid()
static void dump_eid (char * output, int maxlen, void * value, int len) static
Definition at line 103 of file dundi-parser.c.
References ast_eid_to_str().
 {
    if (len == 6)
       ast_eid_to_str(output, maxlen, (dundi_eid *)value);
    else
       snprintf(output, maxlen, "Invalid EID len %d", len);
 }
dump_encrypted()
static void dump_encrypted (char * output, int maxlen, void * value, int len) static
Definition at line 315 of file dundi-parser.c.
 {
    char iv[33];
    int x;
    if ((len > 16) && !(len % 16)) {
       /* Build up IV */
       for (x=0;x<16;x++) {
          snprintf(iv + (x << 1), 3, "%02hhx", ((unsigned char *)value)[x]);
       }
       snprintf(output, maxlen, "[IV %s] %d encrypted blocks\n", iv, len / 16);
    } else
       snprintf(output, maxlen, "Invalid Encrypted Datalen %d", len);
 }
dump_hint()
static void dump_hint (char * output, int maxlen, void * value, int len) static
Definition at line 131 of file dundi-parser.c.
References ast_strlen_zero, dundi_hint::data, ast_frame::datalen, dundi_hint2str(), and dundi_hint::flags.
 {
    char tmp2[256];
    char tmp3[256];
    int datalen;
    struct dundi_hint *hint;
    if (len < sizeof(*hint)) {
       snprintf(output, maxlen, "<invalid contents>");
       return;
    }
    hint = (struct dundi_hint *) value;;
    datalen = len - offsetof(struct dundi_hint, data);
    if (datalen > sizeof(tmp3) - 1)
       datalen = sizeof(tmp3) - 1;
    memcpy(tmp3, hint->data, datalen);
    tmp3[datalen] = '\0';
    dundi_hint2str(tmp2, sizeof(tmp2), ntohs(hint->flags));
    if (ast_strlen_zero(tmp3))
       snprintf(output, maxlen, "[%s]", tmp2);
    else
       snprintf(output, maxlen, "[%s] %s", tmp2, tmp3);
 }
dump_ies()
static void dump_ies (unsigned char * iedata, int spaces, int len) static
Definition at line 383 of file dundi-parser.c.
References ARRAY_LEN, dundi_ie::dump, DUNDI_IE_ENCDATA, dundi_ie::ie, infoelts, dundi_ie::name, outputf, and tmp().
Referenced by dundi_showframe().
 {
    int ielen;
    int ie;
    int x;
    int found;
    char interp[1024];
    char tmp[1051];
    if (len < 2)
       return;
    while(len >= 2) {
       ie = iedata[0];
       ielen = iedata[1];
       /* Encrypted data is the remainder */
       if (ie == DUNDI_IE_ENCDATA)
          ielen = len - 2;
       if (ielen + 2> len) {
          snprintf(tmp, (int)sizeof(tmp), "Total IE length of %d bytes exceeds remaining frame length of %d bytes\n", ielen + 2, len);
          outputf(tmp);
          return;
       }
       found = 0;
       for (x = 0; x < ARRAY_LEN(infoelts); x++) {
          if (infoelts[x].ie == ie) {
             if (infoelts[x].dump) {
                infoelts[x].dump(interp, (int)sizeof(interp), iedata + 2, ielen);
                snprintf(tmp, (int)sizeof(tmp), "   %s%-15.15s : %s\n", (spaces ? "     " : "" ), infoelts[x].name, interp);
                outputf(tmp);
             } else {
                if (ielen)
                   snprintf(interp, (int)sizeof(interp), "%d bytes", ielen);
                else
                   strcpy(interp, "Present");
                snprintf(tmp, (int)sizeof(tmp), "   %s%-15.15s : %s\n", (spaces ? "     " : "" ), infoelts[x].name, interp);
                outputf(tmp);
             }
             found++;
          }
       }
       if (!found) {
          snprintf(tmp, (int)sizeof(tmp), "   %sUnknown IE %03d  : Present\n", (spaces ? "     " : "" ), ie);
          outputf(tmp);
       }
       iedata += (2 + ielen);
       len -= (2 + ielen);
    }
    outputf("\n");
 }
dump_int()
static void dump_int (char * output, int maxlen, void * value, int len) static
Definition at line 200 of file dundi-parser.c.
References ast_copy_string().
 {
    if (len == (int)sizeof(unsigned int))
       snprintf(output, maxlen, "%lu", (unsigned long)ntohl(*((unsigned int *)value)));
    else
       ast_copy_string(output, "Invalid INT", maxlen);
 }
dump_raw()
static void dump_raw (char * output, int maxlen, void * value, int len) static
Definition at line 329 of file dundi-parser.c.
References len(), and value.
 {
    int x;
    unsigned char *u = value;
    output[maxlen - 1] = '\0';
    strcpy(output, "[ ");
    for (x=0;x<len;x++) {
       snprintf(output + strlen(output), maxlen - strlen(output) - 1, "%02hhx ", u[x]);
    }
    strncat(output + strlen(output), "]", maxlen - strlen(output) - 1);
 }
dump_short()
static void dump_short (char * output, int maxlen, void * value, int len) static
Definition at line 208 of file dundi-parser.c.
References ast_copy_string().
 {
    if (len == (int)sizeof(unsigned short))
       snprintf(output, maxlen, "%d", ntohs(*((unsigned short *)value)));
    else
       ast_copy_string(output, "Invalid SHORT", maxlen);
 }
dump_string()
static void dump_string (char * output, int maxlen, void * value, int len) static
Definition at line 90 of file dundi-parser.c.
 {
    if (maxlen > len + 1)
       maxlen = len + 1;
    snprintf(output, maxlen, "%s", (char *) value);
 }
dundi_eid_to_str_short()
char* dundi_eid_to_str_short (char * s, int maxlen, dundi_eid * eid)
Definition at line 54 of file dundi-parser.c.
References ast_eid::eid.
Referenced by cache_lookup(), cache_save(), cache_save_hint(), do_register_expire(), and handle_command_response().
 {
    int x;
    char *os = s;
    if (maxlen < 13) {
       if (s && (maxlen > 0))
          *s = '\0';
    } else {
       for (x=0;x<6;x++) {
          sprintf(s, "%02hhX", (unsigned char)eid->eid[x]);
          s += 2;
       }
    }
    return os;
 }
dundi_eid_zero()
int dundi_eid_zero (dundi_eid * eid)
Definition at line 82 of file dundi-parser.c.
References ARRAY_LEN, and ast_eid::eid.
Referenced by build_transactions(), dundi_discover(), dundi_query(), dundi_show_cache(), dundi_show_requests(), and precache_trans().
 {
    int x;
    for (x = 0; x < ARRAY_LEN(eid->eid); x++)
       if (eid->eid[x]) return 0;
    return 1;
 }
dundi_flags2str()
char* dundi_flags2str (char * buf, int bufsiz, int flags)
Definition at line 246 of file dundi-parser.c.
References ast_strlen_zero, buf, DUNDI_FLAG_CANMATCH, DUNDI_FLAG_COMMERCIAL, DUNDI_FLAG_EXISTS, DUNDI_FLAG_IGNOREPAT, DUNDI_FLAG_MATCHMORE, DUNDI_FLAG_MOBILE, DUNDI_FLAG_NOCOMUNSOLICIT, DUNDI_FLAG_NOUNSOLICITED, and DUNDI_FLAG_RESIDENTIAL.
Referenced by cache_lookup_internal(), dump_answer(), dundi_do_lookup(), dundi_show_cache(), and dundi_show_mappings().
 {
    strcpy(buf, "");
    buf[bufsiz-1] = '\0';
    if (flags & DUNDI_FLAG_EXISTS) {
       strncat(buf, "EXISTS|", bufsiz - strlen(buf) - 1);
    }
    if (flags & DUNDI_FLAG_MATCHMORE) {
       strncat(buf, "MATCHMORE|", bufsiz - strlen(buf) - 1);
    }
    if (flags & DUNDI_FLAG_CANMATCH) {
       strncat(buf, "CANMATCH|", bufsiz - strlen(buf) - 1);
    }
    if (flags & DUNDI_FLAG_IGNOREPAT) {
       strncat(buf, "IGNOREPAT|", bufsiz - strlen(buf) - 1);
    }
    if (flags & DUNDI_FLAG_RESIDENTIAL) {
       strncat(buf, "RESIDENCE|", bufsiz - strlen(buf) - 1);
    }
    if (flags & DUNDI_FLAG_COMMERCIAL) {
       strncat(buf, "COMMERCIAL|", bufsiz - strlen(buf) - 1);
    }
    if (flags & DUNDI_FLAG_MOBILE) {
       strncat(buf, "MOBILE", bufsiz - strlen(buf) - 1);
    }
    if (flags & DUNDI_FLAG_NOUNSOLICITED) {
       strncat(buf, "NOUNSLCTD|", bufsiz - strlen(buf) - 1);
    }
    if (flags & DUNDI_FLAG_NOCOMUNSOLICIT) {
       strncat(buf, "NOCOMUNSLTD|", bufsiz - strlen(buf) - 1);
    }
    /* Get rid of trailing | */
    if (ast_strlen_zero(buf))
       strcpy(buf, "NONE|");
    buf[strlen(buf)-1] = '\0';
    return buf;
 }
dundi_hint2str()
char* dundi_hint2str (char * buf, int bufsiz, int flags)
Definition at line 111 of file dundi-parser.c.
References ast_strlen_zero, buf, DUNDI_HINT_DONT_ASK, DUNDI_HINT_TTL_EXPIRED, and DUNDI_HINT_UNAFFECTED.
Referenced by dump_hint().
 {
    strcpy(buf, "");
    buf[bufsiz-1] = '\0';
    if (flags & DUNDI_HINT_TTL_EXPIRED) {
       strncat(buf, "TTLEXPIRED|", bufsiz - strlen(buf) - 1);
    }
    if (flags & DUNDI_HINT_DONT_ASK) {
       strncat(buf, "DONTASK|", bufsiz - strlen(buf) - 1);
    }
    if (flags & DUNDI_HINT_UNAFFECTED) {
       strncat(buf, "UNAFFECTED|", bufsiz - strlen(buf) - 1);
    }
    /* Get rid of trailing | */
    if (ast_strlen_zero(buf))
       strcpy(buf, "NONE|");
    buf[strlen(buf)-1] = '\0';
    return buf;
 }
dundi_ie2str()
const char* dundi_ie2str (int ie)
Definition at line 373 of file dundi-parser.c.
References ARRAY_LEN, infoelts, and dundi_ie::name.
Referenced by dundi_ie_append_answer(), dundi_ie_append_cause(), dundi_ie_append_encdata(), dundi_ie_append_hint(), dundi_ie_append_raw(), and dundi_parse_ies().
 {
    int x;
    for (x = 0; x < ARRAY_LEN(infoelts); x++) {
       if (infoelts[x].ie == ie)
          return infoelts[x].name;
    }
    return "Unknown IE";
 }
dundi_ie_append()
int dundi_ie_append (struct dundi_ie_data * ied, unsigned char ie)
Definition at line 620 of file dundi-parser.c.
References dundi_ie_append_raw(), and NULL.
Referenced by dundi_discover().
 {
    return dundi_ie_append_raw(ied, ie, NULL, 0);
 }
dundi_ie_append_addr()
int dundi_ie_append_addr (struct dundi_ie_data * ied, unsigned char ie, struct sockaddr_in * sin)
Definition at line 586 of file dundi-parser.c.
References dundi_ie_append_raw().
 {
    return dundi_ie_append_raw(ied, ie, sin, (int)sizeof(struct sockaddr_in));
 }
dundi_ie_append_answer()
int dundi_ie_append_answer (struct dundi_ie_data * ied, unsigned char ie, dundi_eid * eid, unsigned char protocol, unsigned short flags, unsigned short weight, char * data)
Definition at line 559 of file dundi-parser.c.
References dundi_ie_data::buf, dundi_ie2str(), ast_eid::eid, errorf, dundi_ie::ie, dundi_ie_data::pos, and tmp().
Referenced by dundi_lookup_thread(), and precache_trans().
 {
    char tmp[256];
    int datalen = data ? strlen(data) + 11 : 11;
    int x;
    unsigned short myw;
    if (datalen > ((int)sizeof(ied->buf) - ied->pos)) {
       snprintf(tmp, (int)sizeof(tmp), "Out of space for ie '%s' (%d), need %d have %d\n", dundi_ie2str(ie), ie, datalen, (int)sizeof(ied->buf) - ied->pos);
       errorf(tmp);
       return -1;
    }
    ied->buf[ied->pos++] = ie;
    ied->buf[ied->pos++] = datalen;
    for (x=0;x<6;x++)
       ied->buf[ied->pos++] = eid->eid[x];
    ied->buf[ied->pos++] = protocol;
    myw = htons(flags);
    memcpy(ied->buf + ied->pos, &myw, 2);
    ied->pos += 2;
    myw = htons(weight);
    memcpy(ied->buf + ied->pos, &myw, 2);
    ied->pos += 2;
    memcpy(ied->buf + ied->pos, data, datalen-11);
    ied->pos += datalen-11;
    return 0;
 }
dundi_ie_append_byte()
int dundi_ie_append_byte (struct dundi_ie_data * ied, unsigned char ie, unsigned char dat)
Definition at line 615 of file dundi-parser.c.
References dundi_ie_append_raw().
Referenced by handle_command_response().
 {
    return dundi_ie_append_raw(ied, ie, &dat, 1);
 }
dundi_ie_append_cause()
int dundi_ie_append_cause (struct dundi_ie_data * ied, unsigned char ie, unsigned char cause, char * data)
Definition at line 499 of file dundi-parser.c.
References dundi_ie_data::buf, dundi_ie2str(), errorf, dundi_ie::ie, dundi_ie_data::pos, and tmp().
Referenced by dundi_answer_entity(), dundi_answer_query(), dundi_lookup_thread(), dundi_prop_precache(), and handle_command_response().
 {
    char tmp[256];
    int datalen = data ? strlen(data) + 1 : 1;
    if (datalen > ((int)sizeof(ied->buf) - ied->pos)) {
       snprintf(tmp, (int)sizeof(tmp), "Out of space for ie '%s' (%d), need %d have %d\n", dundi_ie2str(ie), ie, datalen, (int)sizeof(ied->buf) - ied->pos);
       errorf(tmp);
       return -1;
    }
    ied->buf[ied->pos++] = ie;
    ied->buf[ied->pos++] = datalen;
    ied->buf[ied->pos++] = cause;
    if (data) {
       memcpy(ied->buf + ied->pos, data, datalen-1);
       ied->pos += datalen-1;
    }
    return 0;
 }
dundi_ie_append_eid()
int dundi_ie_append_eid (struct dundi_ie_data * ied, unsigned char ie, dundi_eid * eid)
Definition at line 610 of file dundi-parser.c.
References dundi_ie_append_raw().
Referenced by do_register(), dundi_discover(), dundi_encrypt(), dundi_ie_append_eid_appropriately(), dundi_query(), handle_command_response(), and precache_trans().
 {
    return dundi_ie_append_raw(ied, ie, (unsigned char *)eid, sizeof(dundi_eid));
 }
dundi_ie_append_encdata()
int dundi_ie_append_encdata (struct dundi_ie_data * ied, unsigned char ie, unsigned char * iv, void * data, int datalen)
Definition at line 539 of file dundi-parser.c.
References dundi_ie_data::buf, dundi_ie2str(), errorf, dundi_ie::ie, dundi_ie_data::pos, and tmp().
Referenced by dundi_encrypt(), and handle_command_response().
 {
    char tmp[256];
    datalen += 16;
    if (datalen > ((int)sizeof(ied->buf) - ied->pos)) {
       snprintf(tmp, (int)sizeof(tmp), "Out of space for ie '%s' (%d), need %d have %d\n", dundi_ie2str(ie), ie, datalen, (int)sizeof(ied->buf) - ied->pos);
       errorf(tmp);
       return -1;
    }
    ied->buf[ied->pos++] = ie;
    ied->buf[ied->pos++] = datalen;
    memcpy(ied->buf + ied->pos, iv, 16);
    ied->pos += 16;
    if (data) {
       memcpy(ied->buf + ied->pos, data, datalen-16);
       ied->pos += datalen-16;
    }
    return 0;
 }
dundi_ie_append_hint()
int dundi_ie_append_hint (struct dundi_ie_data * ied, unsigned char ie, unsigned short flags, char * data)
Definition at line 518 of file dundi-parser.c.
References dundi_ie_data::buf, dundi_ie2str(), errorf, dundi_ie::ie, dundi_ie_data::pos, and tmp().
Referenced by dundi_lookup_thread(), dundi_query_thread(), and precache_trans().
 {
    char tmp[256];
    int datalen = data ? strlen(data) + 2 : 2;
    if (datalen > ((int)sizeof(ied->buf) - ied->pos)) {
       snprintf(tmp, (int)sizeof(tmp), "Out of space for ie '%s' (%d), need %d have %d\n", dundi_ie2str(ie), ie, datalen, (int)sizeof(ied->buf) - ied->pos);
       errorf(tmp);
       return -1;
    }
    ied->buf[ied->pos++] = ie;
    ied->buf[ied->pos++] = datalen;
    flags = htons(flags);
    memcpy(ied->buf + ied->pos, &flags, sizeof(flags));
    ied->pos += 2;
    if (data) {
       memcpy(ied->buf + ied->pos, data, datalen-2);
       ied->pos += datalen-2;
    }
    return 0;
 }
dundi_ie_append_int()
int dundi_ie_append_int (struct dundi_ie_data * ied, unsigned char ie, unsigned int value)
Definition at line 591 of file dundi-parser.c.
References dundi_ie_append_raw().
Referenced by dundi_encrypt().
 {
    unsigned int newval;
    newval = htonl(value);
    return dundi_ie_append_raw(ied, ie, &newval, (int)sizeof(newval));
 }
dundi_ie_append_raw()
int dundi_ie_append_raw (struct dundi_ie_data * ied, unsigned char ie, void * data, int datalen)
Definition at line 484 of file dundi-parser.c.
References dundi_ie_data::buf, dundi_ie2str(), errorf, dundi_ie::ie, dundi_ie_data::pos, and tmp().
Referenced by dundi_encrypt(), dundi_ie_append(), dundi_ie_append_addr(), dundi_ie_append_byte(), dundi_ie_append_eid(), dundi_ie_append_int(), dundi_ie_append_short(), dundi_ie_append_str(), and handle_command_response().
 {
    char tmp[256];
    if (datalen > ((int)sizeof(ied->buf) - ied->pos)) {
       snprintf(tmp, (int)sizeof(tmp), "Out of space for ie '%s' (%d), need %d have %d\n", dundi_ie2str(ie), ie, datalen, (int)sizeof(ied->buf) - ied->pos);
       errorf(tmp);
       return -1;
    }
    ied->buf[ied->pos++] = ie;
    ied->buf[ied->pos++] = datalen;
    memcpy(ied->buf + ied->pos, data, datalen);
    ied->pos += datalen;
    return 0;
 }
dundi_ie_append_short()
int dundi_ie_append_short (struct dundi_ie_data * ied, unsigned char ie, unsigned short value)
Definition at line 598 of file dundi-parser.c.
References dundi_ie_append_raw().
Referenced by do_register(), dundi_discover(), dundi_lookup_thread(), dundi_query(), handle_command_response(), and precache_trans().
 {
    unsigned short newval;
    newval = htons(value);
    return dundi_ie_append_raw(ied, ie, &newval, (int)sizeof(newval));
 }
dundi_ie_append_str()
int dundi_ie_append_str (struct dundi_ie_data * ied, unsigned char ie, char * str)
Definition at line 605 of file dundi-parser.c.
References dundi_ie_append_raw().
Referenced by dundi_discover(), dundi_query(), dundi_query_thread(), and precache_trans().
 {
    return dundi_ie_append_raw(ied, ie, str, strlen(str));
 }
dundi_parse_ies()
int dundi_parse_ies (struct dundi_ies * ies, unsigned char * data, int datalen)
Definition at line 635 of file dundi-parser.c.
References dundi_ies::anscount, dundi_ies::answers, dundi_ies::called_context, dundi_ies::called_number, dundi_ies::cause, dundi_ies::causestr, dundi_ies::cbypass, dundi_ie2str(), DUNDI_IE_ANSWER, DUNDI_IE_CACHEBYPASS, DUNDI_IE_CALLED_CONTEXT, DUNDI_IE_CALLED_NUMBER, DUNDI_IE_CAUSE, DUNDI_IE_COUNTRY, DUNDI_IE_DEPARTMENT, DUNDI_IE_EID, DUNDI_IE_EID_DIRECT, DUNDI_IE_EMAIL, DUNDI_IE_ENCDATA, DUNDI_IE_EXPIRATION, DUNDI_IE_HINT, DUNDI_IE_IPADDR, DUNDI_IE_KEYCRC32, DUNDI_IE_LOCALITY, DUNDI_IE_ORGANIZATION, DUNDI_IE_PHONE, DUNDI_IE_REQEID, DUNDI_IE_SHAREDKEY, DUNDI_IE_SIGNATURE, DUNDI_IE_STATE_PROV, DUNDI_IE_TTL, DUNDI_IE_UNKNOWN, DUNDI_IE_VERSION, DUNDI_MAX_ANSWERS, DUNDI_MAX_STACK, dundi_ies::eid_direct, dundi_ies::eidcount, dundi_ies::eids, dundi_ies::encblock, dundi_ies::enclen, dundi_ies::encsharedkey, dundi_ies::encsig, errorf, dundi_ies::expiration, dundi_ies::hint, dundi_ie::ie, dundi_ies::keycrc32, len(), outputf, dundi_ies::q_country, dundi_ies::q_dept, dundi_ies::q_email, dundi_ies::q_ipaddr, dundi_ies::q_locality, dundi_ies::q_org, dundi_ies::q_phone, dundi_ies::q_stateprov, dundi_ies::reqeid, tmp(), dundi_ies::ttl, dundi_ies::unknowncmd, and dundi_ies::version.
Referenced by handle_command_response().
 {
    /* Parse data into information elements */
    int len;
    int ie;
    char tmp[256];
    memset(ies, 0, (int)sizeof(struct dundi_ies));
    ies->ttl = -1;
    ies->expiration = -1;
    ies->unknowncmd = -1;
    ies->cause = -1;
    while(datalen >= 2) {
       ie = data[0];
       len = data[1];
       if (len > datalen - 2) {
          errorf("Information element length exceeds message size\n");
          return -1;
       }
       switch(ie) {
       case DUNDI_IE_EID:
       case DUNDI_IE_EID_DIRECT:
          if (len != (int)sizeof(dundi_eid)) {
             errorf("Improper entity identifer, expecting 6 bytes!\n");
          } else if (ies->eidcount < DUNDI_MAX_STACK) {
             ies->eids[ies->eidcount] = (dundi_eid *)(data + 2);
             ies->eid_direct[ies->eidcount] = (ie == DUNDI_IE_EID_DIRECT);
             ies->eidcount++;
          } else
             errorf("Too many entities in stack!\n");
          break;
       case DUNDI_IE_REQEID:
          if (len != (int)sizeof(dundi_eid)) {
             errorf("Improper requested entity identifer, expecting 6 bytes!\n");
          } else
             ies->reqeid = (dundi_eid *)(data + 2);
          break;
       case DUNDI_IE_CALLED_CONTEXT:
          ies->called_context = (char *)data + 2;
          break;
       case DUNDI_IE_CALLED_NUMBER:
          ies->called_number = (char *)data + 2;
          break;
       case DUNDI_IE_ANSWER:
          if (len < sizeof(struct dundi_answer)) {
             snprintf(tmp, (int)sizeof(tmp), "Answer expected to be >=%d bytes long but was %d\n", (int)sizeof(struct dundi_answer), len);
             errorf(tmp);
          } else {
             if (ies->anscount < DUNDI_MAX_ANSWERS)
                ies->answers[ies->anscount++]= (struct dundi_answer *)(data + 2);
             else
                errorf("Ignoring extra answers!\n");
          }
          break;
       case DUNDI_IE_TTL:
          if (len != (int)sizeof(unsigned short)) {
             snprintf(tmp, (int)sizeof(tmp), "Expecting ttl to be %d bytes long but was %d\n", (int)sizeof(unsigned short), len);
             errorf(tmp);
          } else
             ies->ttl = ntohs(*((unsigned short *)(data + 2)));
          break;
       case DUNDI_IE_VERSION:
          if (len != (int)sizeof(unsigned short)) {
             snprintf(tmp, (int)sizeof(tmp),  "Expecting version to be %d bytes long but was %d\n", (int)sizeof(unsigned short), len);
             errorf(tmp);
          } else
             ies->version = ntohs(*((unsigned short *)(data + 2)));
          break;
       case DUNDI_IE_EXPIRATION:
          if (len != (int)sizeof(unsigned short)) {
             snprintf(tmp, (int)sizeof(tmp),  "Expecting expiration to be %d bytes long but was %d\n", (int)sizeof(unsigned short), len);
             errorf(tmp);
          } else
             ies->expiration = ntohs(*((unsigned short *)(data + 2)));
          break;
       case DUNDI_IE_KEYCRC32:
          if (len != (int)sizeof(unsigned int)) {
             snprintf(tmp, (int)sizeof(tmp),  "Expecting expiration to be %d bytes long but was %d\n", (int)sizeof(unsigned int), len);
             errorf(tmp);
          } else
             ies->keycrc32 = ntohl(*((unsigned int *)(data + 2)));
          break;
       case DUNDI_IE_UNKNOWN:
          if (len == 1)
             ies->unknowncmd = data[2];
          else {
             snprintf(tmp, (int)sizeof(tmp), "Expected single byte Unknown command, but was %d long\n", len);
             errorf(tmp);
          }
          break;
       case DUNDI_IE_CAUSE:
          if (len >= 1) {
             ies->cause = data[2];
             ies->causestr = (char *)data + 3;
          } else {
             snprintf(tmp, (int)sizeof(tmp), "Expected at least one byte cause, but was %d long\n", len);
             errorf(tmp);
          }
          break;
       case DUNDI_IE_HINT:
          if (len >= 2) {
             ies->hint = (struct dundi_hint *)(data + 2);
          } else {
             snprintf(tmp, (int)sizeof(tmp), "Expected at least two byte hint, but was %d long\n", len);
             errorf(tmp);
          }
          break;
       case DUNDI_IE_DEPARTMENT:
          ies->q_dept = (char *)data + 2;
          break;
       case DUNDI_IE_ORGANIZATION:
          ies->q_org = (char *)data + 2;
          break;
       case DUNDI_IE_LOCALITY:
          ies->q_locality = (char *)data + 2;
          break;
       case DUNDI_IE_STATE_PROV:
          ies->q_stateprov = (char *)data + 2;
          break;
       case DUNDI_IE_COUNTRY:
          ies->q_country = (char *)data + 2;
          break;
       case DUNDI_IE_EMAIL:
          ies->q_email = (char *)data + 2;
          break;
       case DUNDI_IE_PHONE:
          ies->q_phone = (char *)data + 2;
          break;
       case DUNDI_IE_IPADDR:
          ies->q_ipaddr = (char *)data + 2;
          break;
       case DUNDI_IE_ENCDATA:
          /* Recalculate len as the remainder of the message, regardless of
             theoretical length */
          len = datalen - 2;
          if ((len > 16) && !(len % 16)) {
             ies->encblock = (struct dundi_encblock *)(data + 2);
             ies->enclen = len - 16;
          } else {
             snprintf(tmp, (int)sizeof(tmp), "Invalid encrypted data length %d\n", len);
             errorf(tmp);
          }
          break;
       case DUNDI_IE_SHAREDKEY:
          if (len == 128) {
             ies->encsharedkey = (unsigned char *)(data + 2);
          } else {
             snprintf(tmp, (int)sizeof(tmp), "Invalid encrypted shared key length %d\n", len);
             errorf(tmp);
          }
          break;
       case DUNDI_IE_SIGNATURE:
          if (len == 128) {
             ies->encsig = (unsigned char *)(data + 2);
          } else {
             snprintf(tmp, (int)sizeof(tmp), "Invalid encrypted signature length %d\n", len);
             errorf(tmp);
          }
          break;
       case DUNDI_IE_CACHEBYPASS:
          ies->cbypass = 1;
          break;
       default:
          snprintf(tmp, (int)sizeof(tmp), "Ignoring unknown information element '%s' (%d) of length %d\n", dundi_ie2str(ie), ie, len);
          outputf(tmp);
       }
       /* Overwrite information element with 0, to null terminate previous portion */
       data[0] = 0;
       datalen -= (len + 2);
       data += (len + 2);
    }
    /* Null-terminate last field */
    *data = '\0';
    if (datalen) {
       errorf("Invalid information element contents, strange boundary\n");
       return -1;
    }
    return 0;
 }
dundi_set_error()
void dundi_set_error (void(*)(const char *) func)
Definition at line 630 of file dundi-parser.c.
References errorf.
Referenced by load_module().
 {
    errorf = func;
 }
dundi_set_output()
void dundi_set_output (void(*)(const char *) func)
Definition at line 625 of file dundi-parser.c.
References outputf.
Referenced by load_module().
 {
    outputf = func;
 }
dundi_showframe()
void dundi_showframe (struct dundi_hdr * fhi, int rx, struct ast_sockaddr * sin, int datalen)
Definition at line 432 of file dundi-parser.c.
References ARRAY_LEN, ast_sockaddr_stringify(), dundi_hdr::cmdflags, dundi_hdr::cmdresp, commands, dundi_hdr::dtrans, dump_ies(), DUNDI_FLAG_RESERVED, DUNDI_FLAG_RETRANS, dundi_hdr::ies, dundi_hdr::iseqno, dundi_hdr::oseqno, outputf, dundi_hdr::strans, and tmp().
Referenced by dundi_send(), dundi_xmit(), handle_command_response(), and socket_read().
 {
    char *pref[] = {
       "Tx",
       "Rx",
       "    ETx",
       "    Erx" };
    char *commands[] = {
       "ACK         ",
       "DPDISCOVER  ",
       "DPRESPONSE  ",
       "EIDQUERY    ",
       "EIDRESPONSE ",
       "PRECACHERQ  ",
       "PRECACHERP  ",
       "INVALID     ",
       "UNKNOWN CMD ",
       "NULL        ",
       "REGREQ      ",
       "REGRESPONSE ",
       "CANCEL      ",
       "ENCRYPT     ",
       "ENCREJ      " };
    char class2[20];
    char *class;
    char subclass2[20];
    char *subclass;
    char tmp[256];
    if ((fhi->cmdresp & 0x3f) >= ARRAY_LEN(commands)) {
       snprintf(class2, sizeof(class2), "(%d?)", fhi->cmdresp & 0x3f);
       class = class2;
    } else {
       class = commands[fhi->cmdresp & 0x3f];
    }
    snprintf(subclass2, sizeof(subclass2), "%02hhx", (unsigned char)fhi->cmdflags);
    subclass = subclass2;
    snprintf(tmp, sizeof(tmp),
       "%s-Frame -- OSeqno: %3.3d ISeqno: %3.3d Type: %s (%s)\n",
       pref[rx],
       fhi->oseqno, fhi->iseqno, class, fhi->cmdresp & 0x40 ? "Response" : "Command");
    outputf(tmp);
    snprintf(tmp, (int)sizeof(tmp),
       "%s     Flags: %s STrans: %5.5d  DTrans: %5.5d [%s]%s\n", (rx > 1) ? "     " : "",
       subclass, ntohs(fhi->strans) & ~DUNDI_FLAG_RESERVED, ntohs(fhi->dtrans) & ~DUNDI_FLAG_RETRANS,
       ast_sockaddr_stringify(sin),
       fhi->cmdresp & 0x80 ? " (Final)" : "");
    outputf(tmp);
    dump_ies(fhi->ies, rx > 1, datalen);
 }
dundi_str_short_to_eid()
int dundi_str_short_to_eid (dundi_eid * eid, const char * s)
Definition at line 70 of file dundi-parser.c.
References ast_eid::eid.
Referenced by cache_lookup_internal(), dundi_show_cache(), and dundi_show_hints().
 {
    unsigned int eid_int[6];
    int x;
    if (sscanf(s, "%2x%2x%2x%2x%2x%2x", &eid_int[0], &eid_int[1], &eid_int[2],
        &eid_int[3], &eid_int[4], &eid_int[5]) != 6)
          return -1;
    for (x = 0; x < 6; x++)
       eid->eid[x] = eid_int[x];
    return 0;
 }
internalerror()
static void internalerror (const char * str) static
Definition at line 46 of file dundi-parser.c.
 {
    fprintf(stderr, "WARNING: %s", str);
 }
internaloutput()
static void internaloutput (const char * str) static
Definition at line 41 of file dundi-parser.c.
 {
    fputs(str, stdout);
 }
proto2str()
static char* proto2str (int proto, char * buf, int bufsiz) static
Definition at line 224 of file dundi-parser.c.
References buf, DUNDI_PROTO_H323, DUNDI_PROTO_IAX, DUNDI_PROTO_NONE, and DUNDI_PROTO_SIP.
Referenced by dump_answer().
 {
    switch(proto) {
    case DUNDI_PROTO_NONE:
       strncpy(buf, "None", bufsiz - 1);
       break;
    case DUNDI_PROTO_IAX:
       strncpy(buf, "IAX", bufsiz - 1);
       break;
    case DUNDI_PROTO_SIP:
       strncpy(buf, "SIP", bufsiz - 1);
       break;
    case DUNDI_PROTO_H323:
       strncpy(buf, "H.323", bufsiz - 1);
       break;
    default:
       snprintf(buf, bufsiz, "Unknown Proto(%d)", proto);
    }
    buf[bufsiz-1] = '\0';
    return buf;
 }
Variable Documentation
errorf
void(* errorf) (const char *str) = internalerror static
Definition at line 52 of file dundi-parser.c.
Referenced by dundi_ie_append_answer(), dundi_ie_append_cause(), dundi_ie_append_encdata(), dundi_ie_append_hint(), dundi_ie_append_raw(), dundi_parse_ies(), and dundi_set_error().
infoelts
struct dundi_ie infoelts[] static
Referenced by dump_ies(), and dundi_ie2str().
outputf
void(* outputf) (const char *str) = internaloutput static
Definition at line 51 of file dundi-parser.c.
Referenced by dump_ies(), dundi_parse_ies(), dundi_set_output(), and dundi_showframe().