Asterisk - The Open Source Telephony Project: dns_txt.c File Reference
dns_txt.c File Reference
DNS TXT Record Parsing API.
#include "asterisk.h"
#include <netinet/in.h>
#include <resolv.h>
#include "asterisk/dns_core.h"
#include "asterisk/dns_txt.h"
#include "asterisk/dns_internal.h"
#include "asterisk/utils.h"
Functions
void ast_dns_txt_free_strings (struct ast_vector_string *strings)
Free strings returned by ast_dns_txt_get_strings.
size_t ast_dns_txt_get_count (const struct ast_dns_record *record)
Get the number of character strings in a TXT record.
struct ast_vector_string * ast_dns_txt_get_strings (const struct ast_dns_record *record)
Get the character strings from this TXT record.
struct ast_dns_record * dns_txt_alloc (struct ast_dns_query *query, const char *data, const size_t size)
Allocate and parse a DNS TXT record.
Detailed Description
DNS TXT Record Parsing API.
Author
Sean Bright sean..nosp@m.brig.nosp@m.ht@gm.nosp@m.ail..nosp@m.com
Definition in file dns_txt.c.
Function Documentation
ast_dns_txt_free_strings()
void ast_dns_txt_free_strings (struct ast_vector_string * strings)
Free strings returned by ast_dns_txt_get_strings.
Since
16.10.0, 17.4.0
Parameters
strings The vector to free
Definition at line 123 of file dns_txt.c.
References ast_free, AST_VECTOR_CALLBACK_VOID, and AST_VECTOR_PTR_FREE.
Referenced by ast_dns_txt_get_strings().
 {
    AST_VECTOR_CALLBACK_VOID(strings, ast_free);
    AST_VECTOR_PTR_FREE(strings);
 }
ast_dns_txt_get_count()
size_t ast_dns_txt_get_count (const struct ast_dns_record * record)
Get the number of character strings in a TXT record.
Since
16.10.0, 17.4.0
Parameters
record The DNS record
Returns
the number of character strings in this TXT record
Definition at line 68 of file dns_txt.c.
References ast_assert, ast_dns_record_get_rr_type(), and ast_dns_txt_record::count.
Referenced by ast_dns_txt_get_strings().
 {
    struct ast_dns_txt_record *txt = (struct ast_dns_txt_record *) record;
    ast_assert(ast_dns_record_get_rr_type(record) == T_TXT);
    return txt->count;
 }
ast_dns_txt_get_strings()
struct ast_vector_string* ast_dns_txt_get_strings (const struct ast_dns_record * record)
Get the character strings from this TXT record.
Since
16.10.0, 17.4.0
Parameters
record The DNS record
Return values
NULL Unable to allocate memory
Returns
Vector of strings. Free with ast_dns_txt_free_strings
Definition at line 75 of file dns_txt.c.
References ast_assert, ast_dns_record_get_data(), ast_dns_record_get_data_size(), ast_dns_record_get_rr_type(), ast_dns_txt_free_strings(), ast_dns_txt_get_count(), ast_free, ast_malloc, AST_VECTOR_APPEND, AST_VECTOR_INIT, and NULL.
 {
    struct ast_vector_string *strings;
    const size_t size = ast_dns_record_get_data_size(record);
    const char *data = ast_dns_record_get_data(record);
    const char *end_of_record = data + size;
    ast_assert(ast_dns_record_get_rr_type(record) == T_TXT);
    strings = ast_malloc(sizeof(struct ast_vector_const_string));
    if (!strings) {
       return NULL;
    }
    if (AST_VECTOR_INIT(strings, ast_dns_txt_get_count(record))) {
       ast_free(strings);
       return NULL;
    }
    while (data < end_of_record) {
       char *s;
       uint8_t bytes = (uint8_t) *data;
       s = ast_malloc(bytes + 1);
       if (!s) {
          ast_dns_txt_free_strings(strings);
          return NULL;
       }
       memcpy(s, &data[1], bytes);
       s[bytes] = 0;
       /* We know the size in advance so this can't fail */
       AST_VECTOR_APPEND(strings, s);
       data += bytes + 1;
    }
    /* Sanity check */
    if (data != end_of_record) {
       ast_dns_txt_free_strings(strings);
       return NULL;
    }
    return strings;
 }
dns_txt_alloc()
struct ast_dns_record* dns_txt_alloc (struct ast_dns_query * query, const char * data, const size_t size)
Allocate and parse a DNS TXT record.
Since
16.10.0, 17.4.0
Parameters
query The DNS query
data This specific TXT record
size The size of the TXT record
Return values
non-NULL success
NULL failure
Definition at line 38 of file dns_txt.c.
References ast_calloc, ast_dns_txt_record::count, ast_dns_txt_record::data, ast_dns_record::data_ptr, ast_dns_txt_record::generic, and NULL.
 {
    struct ast_dns_txt_record *txt;
    const char *end_of_record = data + size;
    size_t count = 0;
    /* Because we can't allocate additional memory, the best we can do here is just
     * validate that this conforms to a TXT record. */
    while (data < end_of_record) {
       uint8_t byte_count = (uint8_t) *data;
       count++;
       data += byte_count + 1;
    }
    if (data != end_of_record) {
       /* This is not a valid TXT record, so we can bail out */
       return NULL;
    }
    txt = ast_calloc(1, sizeof(*txt) + size);
    if (!txt) {
       return NULL;
    }
    txt->count = count;
    txt->generic.data_ptr = txt->data;
    return (struct ast_dns_record *) txt;
 }