Asterisk - The Open Source Telephony Project: func_jitterbuffer.c File Reference
func_jitterbuffer.c File Reference
Module: Dial plan functions
Put a jitterbuffer on the read side of a channel.
#include "asterisk.h"
#include "asterisk/module.h"
#include "asterisk/channel.h"
#include "asterisk/framehook.h"
#include "asterisk/frame.h"
#include "asterisk/pbx.h"
#include "asterisk/abstract_jb.h"
#include "asterisk/timing.h"
#include "asterisk/app.h"
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int jb_helper (struct ast_channel *chan, const char *cmd, char *data, const char *value)
static int load_module (void)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Jitter buffer for read side of channel." , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, }
static const struct ast_module_info * ast_module_info = &__mod_info
static struct ast_custom_function jb_function
Detailed Description
Put a jitterbuffer on the read side of a channel.
Author
David Vossel dvoss.nosp@m.el@d.nosp@m.igium.nosp@m..com
Definition in file func_jitterbuffer.c.
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 196 of file func_jitterbuffer.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 196 of file func_jitterbuffer.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 196 of file func_jitterbuffer.c.
jb_helper()
static int jb_helper (struct ast_channel * chan, const char * cmd, char * data, const char * value) static
Definition at line 115 of file func_jitterbuffer.c.
References args, AST_APP_ARG, ast_copy_string(), AST_DECLARE_APP_ARGS, ast_jb_conf_default(), ast_jb_create_framehook(), ast_jb_read_conf(), ast_log, AST_STANDARD_APP_ARGS, ast_strdupa, ast_strlen_zero, ast_jb_conf::impl, LOG_WARNING, ast_jb_conf::max_size, parse(), ast_jb_conf::resync_threshold, and ast_jb_conf::target_extra.
 {
    struct ast_jb_conf jb_conf;
    if (!chan) {
       ast_log(LOG_WARNING, "No channel was provided to %s function.\n", cmd);
       return -1;
    }
    /* Initialize and set jb_conf */
    ast_jb_conf_default(&jb_conf);
    /* Now check user options to see if any of the defaults need to change. */
    if (!ast_strlen_zero(data)) {
       if (strcasecmp(data, "fixed") &&
             strcasecmp(data, "adaptive") &&
             strcasecmp(data, "disabled")) {
          ast_log(LOG_WARNING, "Unknown Jitterbuffer type %s. Failed to create jitterbuffer.\n", data);
          return -1;
       }
       ast_copy_string(jb_conf.impl, data, sizeof(jb_conf.impl));
    }
    if (!ast_strlen_zero(value) && strcasecmp(value, "default")) {
       char *parse = ast_strdupa(value);
       int res = 0;
       AST_DECLARE_APP_ARGS(args,
          AST_APP_ARG(max_size);
          AST_APP_ARG(resync_threshold);
          AST_APP_ARG(target_extra);
          AST_APP_ARG(sync_video);
       );
       AST_STANDARD_APP_ARGS(args, parse);
       if (!ast_strlen_zero(args.max_size)) {
          res |= ast_jb_read_conf(&jb_conf,
             "jbmaxsize",
             args.max_size);
       }
       if (!ast_strlen_zero(args.resync_threshold)) {
          res |= ast_jb_read_conf(&jb_conf,
             "jbresyncthreshold",
             args.resync_threshold);
       }
       if (!ast_strlen_zero(args.target_extra)) {
          res |= ast_jb_read_conf(&jb_conf,
             "jbtargetextra",
             args.target_extra);
       }
       if (!ast_strlen_zero(args.sync_video)) {
          res |= ast_jb_read_conf(&jb_conf,
             "jbsyncvideo",
             args.sync_video);
       }
       if (res) {
          ast_log(LOG_WARNING, "Invalid jitterbuffer parameters %s\n", value);
       }
    }
    ast_jb_create_framehook(chan, &jb_conf, 0);
    return 0;
 }
load_module()
static int load_module (void) static
Definition at line 190 of file func_jitterbuffer.c.
References ast_custom_function_register, AST_MODULE_LOAD_DECLINE, and AST_MODULE_LOAD_SUCCESS.
 {
    int res = ast_custom_function_register(&jb_function);
    return res ? AST_MODULE_LOAD_DECLINE : AST_MODULE_LOAD_SUCCESS;
 }
unload_module()
static int unload_module (void) static
Definition at line 185 of file func_jitterbuffer.c.
References ast_custom_function_unregister().
 {
    return ast_custom_function_unregister(&jb_function);
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Jitter buffer for read side of channel." , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, } static
Definition at line 196 of file func_jitterbuffer.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 196 of file func_jitterbuffer.c.
jb_function
struct ast_custom_function jb_function static
Initial value:
= {
   .name = "JITTERBUFFER",
   .write = jb_helper,
}
Definition at line 180 of file func_jitterbuffer.c.