Asterisk - The Open Source Telephony Project: func_strings.c File Reference
func_strings.c File Reference
Module: Dial plan functions
String manipulation dialplan functions.
#include "asterisk.h"
#include <regex.h>
#include <ctype.h>
#include "asterisk/module.h"
#include "asterisk/channel.h"
#include "asterisk/pbx.h"
#include "asterisk/utils.h"
#include "asterisk/app.h"
#include "asterisk/localtime.h"
#include "asterisk/test.h"
Macros
#define beginning (cmd[0] == 'S') /* SHIFT */
#define beginning (cmd[0] == 'U') /* UNSHIFT */
#define HASH_FORMAT HASH_PREFIX "%s~"
#define HASH_PREFIX "~HASH~%s~"
Functions
static void __init_result_buf (void)
static void __init_tmp_buf (void)
static void __reg_module (void)
static void __unreg_module (void)
static int acf_strftime (struct ast_channel *chan, const char *cmd, char *parse, char *buf, size_t buflen)
static int acf_strptime (struct ast_channel *chan, const char *cmd, char *data, char *buf, size_t buflen)
static int array (struct ast_channel *chan, const char *cmd, char *var, const char *value)
struct ast_module * AST_MODULE_SELF_SYM (void)
AST_TEST_DEFINE (test_FIELDNUM)
AST_TEST_DEFINE (test_REPLACE)
AST_TEST_DEFINE (test_FILTER)
AST_TEST_DEFINE (test_STRREPLACE)
static void clearvar_prefix (struct ast_channel *chan, const char *prefix)
static int csv_quote (struct ast_channel *chan, const char *cmd, char *data, char *buf, size_t len)
static int exec_clearhash (struct ast_channel *chan, const char *data)
static int filter (struct ast_channel *chan, const char *cmd, char *parse, char *buf, size_t len)
static int function_eval (struct ast_channel *chan, const char *cmd, char *data, char *buf, size_t buflen)
static int function_eval2 (struct ast_channel *chan, const char *cmd, char *data, struct ast_str **buf, ssize_t buflen)
static int function_fieldnum (struct ast_channel *chan, const char *cmd, char *parse, char *buf, size_t len)
static int function_fieldnum_helper (struct ast_channel *chan, const char *cmd, char *parse, char *buf, struct ast_str **sbuf, ssize_t len)
static int function_fieldnum_str (struct ast_channel *chan, const char *cmd, char *parse, struct ast_str **buf, ssize_t len)
static int function_fieldqty (struct ast_channel *chan, const char *cmd, char *parse, char *buf, size_t len)
static int function_fieldqty_helper (struct ast_channel *chan, const char *cmd, char *parse, char *buf, struct ast_str **sbuf, ssize_t len)
static int function_fieldqty_str (struct ast_channel *chan, const char *cmd, char *parse, struct ast_str **buf, ssize_t len)
static const char * get_key (const struct ast_str *prefix, const struct ast_var_t *var)
static int hash_read (struct ast_channel *chan, const char *cmd, char *data, char *buf, size_t len)
static int hash_write (struct ast_channel *chan, const char *cmd, char *var, const char *value)
static int hashkeys_read (struct ast_channel *chan, const char *cmd, char *data, char *buf, size_t len)
static int hashkeys_read2 (struct ast_channel *chan, const char *cmd, char *data, struct ast_str **buf, ssize_t len)
static int keypadhash (struct ast_channel *chan, const char *cmd, char *data, char *buf, size_t buflen)
static int len (struct ast_channel *chan, const char *cmd, char *data, char *buf, size_t buflen)
static int listfilter (struct ast_channel *chan, const char *cmd, char *parse, char *buf, struct ast_str **bufstr, ssize_t len)
static int listfilter_read (struct ast_channel *chan, const char *cmd, char *parse, char *buf, size_t len)
static int listfilter_read2 (struct ast_channel *chan, const char *cmd, char *parse, struct ast_str **buf, ssize_t len)
static int load_module (void)
static int passthru (struct ast_channel *chan, const char *cmd, char *data, struct ast_str **buf, ssize_t len)
static int quote (struct ast_channel *chan, const char *cmd, char *data, char *buf, size_t len)
static int regex (struct ast_channel *chan, const char *cmd, char *parse, char *buf, size_t len)
static int replace (struct ast_channel *chan, const char *cmd, char *data, struct ast_str **buf, ssize_t len)
static int shift_pop (struct ast_channel *chan, const char *cmd, char *data, struct ast_str **buf, ssize_t len)
static int string_tolower (struct ast_channel *chan, const char *cmd, char *data, char *buf, size_t buflen)
static int string_tolower2 (struct ast_channel *chan, const char *cmd, char *data, struct ast_str **buf, ssize_t buflen)
static int string_toupper (struct ast_channel *chan, const char *cmd, char *data, char *buf, size_t buflen)
static int string_toupper2 (struct ast_channel *chan, const char *cmd, char *data, struct ast_str **buf, ssize_t buflen)
static int strreplace (struct ast_channel *chan, const char *cmd, char *data, struct ast_str **buf, ssize_t len)
static int unload_module (void)
static int unshift_push (struct ast_channel *chan, const char *cmd, char *data, const char *new_value)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "String handling dialplan functions" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, }
static char * app_clearhash = "ClearHash"
static struct ast_custom_function array_function
static const struct ast_module_info * ast_module_info = &__mod_info
static struct ast_custom_function csv_quote_function
static struct ast_custom_function eval_function
static struct ast_custom_function fieldnum_function
static struct ast_custom_function fieldqty_function
static struct ast_custom_function filter_function
static struct ast_custom_function hash_function
static struct ast_custom_function hashkeys_function
static struct ast_custom_function keypadhash_function
static struct ast_custom_function len_function
static struct ast_custom_function listfilter_function
static struct ast_custom_function passthru_function
static struct ast_custom_function pop_function
static struct ast_custom_function push_function
static struct ast_custom_function quote_function
static struct ast_custom_function regex_function
static struct ast_custom_function replace_function
static struct ast_threadstorage result_buf = { .once = PTHREAD_ONCE_INIT , .key_init = __init_result_buf , .custom_init = NULL , }
static struct ast_custom_function shift_function
static struct ast_custom_function strftime_function
static struct ast_custom_function strptime_function
static struct ast_custom_function strreplace_function
static struct ast_threadstorage tmp_buf = { .once = PTHREAD_ONCE_INIT , .key_init = __init_tmp_buf , .custom_init = NULL , }
static struct ast_custom_function tolower_function
static struct ast_custom_function toupper_function
static struct ast_custom_function unshift_function
Detailed Description
String manipulation dialplan functions.
Author
Tilghman Lesher
Anothony Minessale II
Definition in file func_strings.c.
Macro Definition Documentation
beginning [1/2]
#define beginning (cmd[0] == 'S') /* SHIFT */
Referenced by shift_pop(), and unshift_push().
beginning [2/2]
#define beginning (cmd[0] == 'U') /* UNSHIFT */
HASH_FORMAT
#define HASH_FORMAT HASH_PREFIX "%s~"
Definition at line 991 of file func_strings.c.
Referenced by array(), hash_read(), and hash_write().
HASH_PREFIX
#define HASH_PREFIX "~HASH~%s~"
Definition at line 990 of file func_strings.c.
Referenced by exec_clearhash(), hashkeys_read(), and hashkeys_read2().
Function Documentation
__init_result_buf()
static void __init_result_buf (void) static
Definition at line 45 of file func_strings.c.
 {
__init_tmp_buf()
static void __init_tmp_buf (void) static
Definition at line 46 of file func_strings.c.
 {
__reg_module()
static void __reg_module (void) static
Definition at line 2032 of file func_strings.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 2032 of file func_strings.c.
acf_strftime()
static int acf_strftime (struct ast_channel * chan, const char * cmd, char * parse, char * buf, size_t buflen) static
Definition at line 1362 of file func_strings.c.
References args, AST_APP_ARG, AST_DECLARE_APP_ARGS, ast_get_timeval(), ast_localtime(), ast_log, AST_STANDARD_APP_ARGS, ast_strftime(), ast_tvnow(), format, LOG_WARNING, and NULL.
 {
    AST_DECLARE_APP_ARGS(args,
               AST_APP_ARG(epoch);
               AST_APP_ARG(timezone);
               AST_APP_ARG(format);
    );
    struct timeval when;
    struct ast_tm tm;
    buf[0] = '\0';
    AST_STANDARD_APP_ARGS(args, parse);
    ast_get_timeval(args.epoch, &when, ast_tvnow(), NULL);
    ast_localtime(&when, &tm, args.timezone);
    if (!args.format)
       args.format = "%c";
    if (ast_strftime(buf, buflen, args.format, &tm) <= 0)
       ast_log(LOG_WARNING, "C function strftime() output nothing?!!\n");
    buf[buflen - 1] = '\0';
    return 0;
 }
acf_strptime()
static int acf_strptime (struct ast_channel * chan, const char * cmd, char * data, char * buf, size_t buflen) static
Definition at line 1396 of file func_strings.c.
References args, AST_APP_ARG, AST_DECLARE_APP_ARGS, ast_log, ast_mktime(), AST_STANDARD_APP_ARGS, ast_strlen_zero, ast_strptime(), format, LOG_ERROR, and LOG_WARNING.
 {
    AST_DECLARE_APP_ARGS(args,
               AST_APP_ARG(timestring);
               AST_APP_ARG(timezone);
               AST_APP_ARG(format);
    );
    struct ast_tm tm;
    buf[0] = '\0';
    if (!data) {
       ast_log(LOG_ERROR,
             "Asterisk function STRPTIME() requires an argument.\n");
       return -1;
    }
    AST_STANDARD_APP_ARGS(args, data);
    if (ast_strlen_zero(args.format)) {
       ast_log(LOG_ERROR,
             "No format supplied to STRPTIME(<timestring>,<timezone>,<format>)");
       return -1;
    }
    if (!ast_strptime(args.timestring, args.format, &tm)) {
       ast_log(LOG_WARNING, "STRPTIME() found no time specified within the string\n");
    } else {
       struct timeval when;
       when = ast_mktime(&tm, args.timezone);
       snprintf(buf, buflen, "%d", (int) when.tv_sec);
    }
    return 0;
 }
array()
static int array (struct ast_channel * chan, const char * cmd, char * var, const char * value) static
Examples:
/usr/src/asterisk-18.5.0/main/app.c.
Definition at line 1017 of file func_strings.c.
References AST_APP_ARG, ast_autoservice_stop(), ast_debug, AST_DECLARE_APP_ARGS, AST_STANDARD_APP_ARGS, ast_strdupa, HASH_FORMAT, pbx_builtin_getvar_helper(), pbx_builtin_setvar_helper(), S_OR, and var.
Referenced by app_to_json(), append_json(), device_to_json_cb(), devices_to_json(), hash_write(), json_array_from_list(), stasis_app_device_states_to_json(), and stasis_app_mailboxes_to_json().
 {
    AST_DECLARE_APP_ARGS(arg1,
               AST_APP_ARG(var)[100];
    );
    AST_DECLARE_APP_ARGS(arg2,
               AST_APP_ARG(val)[100];
    );
    char *origvar = "", *value2, varname[256];
    int i, ishash = 0;
    if (!var) {
       return -1;
    }
    value2 = ast_strdupa(value);
    if (!strcmp(cmd, "HASH")) {
       const char *var2 = pbx_builtin_getvar_helper(chan, "~ODBCFIELDS~");
       origvar = var;
       if (var2)
          var = ast_strdupa(var2);
       else {
          if (chan)
             ast_autoservice_stop(chan);
          return -1;
       }
       ishash = 1;
    }
    /* The functions this will generally be used with are SORT and ODBC_*, which
     * both return comma-delimited lists.  However, if somebody uses literal lists,
     * their commas will be translated to vertical bars by the load, and I don't
     * want them to be surprised by the result.  Hence, we prefer commas as the
     * delimiter, but we'll fall back to vertical bars if commas aren't found.
     */
    ast_debug(1, "array (%s=%s)\n", var, S_OR(value2, ""));
    AST_STANDARD_APP_ARGS(arg1, var);
    AST_STANDARD_APP_ARGS(arg2, value2);
    for (i = 0; i < arg1.argc; i++) {
       ast_debug(1, "array set value (%s=%s)\n", arg1.var[i],
             S_OR(arg2.val[i], ""));
       if (i < arg2.argc) {
          if (ishash) {
             if (origvar[0] == '_') {
                if (origvar[1] == '_') {
                   snprintf(varname, sizeof(varname), "__" HASH_FORMAT, origvar + 2, arg1.var[i]);
                } else {
                   snprintf(varname, sizeof(varname), "_" HASH_FORMAT, origvar + 1, arg1.var[i]);
                }
             } else {
                snprintf(varname, sizeof(varname), HASH_FORMAT, origvar, arg1.var[i]);
             }
             pbx_builtin_setvar_helper(chan, varname, arg2.val[i]);
          } else {
             pbx_builtin_setvar_helper(chan, arg1.var[i], arg2.val[i]);
          }
       } else {
          /* We could unset the variable, by passing a NULL, but due to
           * pushvar semantics, that could create some undesired behavior. */
          if (ishash) {
             snprintf(varname, sizeof(varname), HASH_FORMAT, origvar, arg1.var[i]);
             pbx_builtin_setvar_helper(chan, varname, "");
          } else {
             pbx_builtin_setvar_helper(chan, arg1.var[i], "");
          }
       }
    }
    return 0;
 }
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 2032 of file func_strings.c.
AST_TEST_DEFINE() [1/4]
AST_TEST_DEFINE (test_FIELDNUM)
Definition at line 1704 of file func_strings.c.
References ARRAY_LEN, ast_channel_release(), ast_channel_varshead(), ast_dummy_channel_alloc, ast_free, AST_LIST_INSERT_HEAD, AST_LIST_REMOVE, ast_str_buffer(), ast_str_create, ast_str_substitute_variables(), AST_TEST_FAIL, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_test_status_update, ast_var_assign, ast_var_delete(), ast_var_t::entries, sip_to_pjsip::info(), ast_var_t::name, str, TEST_EXECUTE, TEST_INIT, and var.
 {
    int i, res = AST_TEST_PASS;
    struct ast_channel *chan;
    struct ast_str *str;
    char expression[256];
    struct {
       const char *fields;
       const char *delim;
       const char *field;
       const char *expected;
    } test_args[] = {
       {"abc,def,ghi,jkl", "\\,",     "ghi", "3"},
       {"abc def ghi jkl", " ",       "abc", "1"},
       {"abc/def/ghi/jkl", "\\\\x2f", "def", "2"},
       {"abc$def$ghi$jkl", "",        "ghi", "0"},
       {"abc,def,ghi,jkl", "-",       "",    "0"},
       {"abc-def-ghi-jkl", "-",       "mno", "0"}
    };
    switch (cmd) {
    case TEST_INIT:
       info->name = "func_FIELDNUM_test";
       info->category = "/funcs/func_strings/";
       info->summary = "Test FIELDNUM function";
       info->description = "Verify FIELDNUM behavior";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    if (!(chan = ast_dummy_channel_alloc())) {
       ast_test_status_update(test, "Unable to allocate dummy channel\n");
       return AST_TEST_FAIL;
    }
    if (!(str = ast_str_create(16))) {
       ast_test_status_update(test, "Unable to allocate dynamic string buffer\n");
       ast_channel_release(chan);
       return AST_TEST_FAIL;
    }
    for (i = 0; i < ARRAY_LEN(test_args); i++) {
       struct ast_var_t *var = ast_var_assign("FIELDS", test_args[i].fields);
       if (!var) {
          ast_test_status_update(test, "Out of memory\n");
          res = AST_TEST_FAIL;
          break;
       }
       AST_LIST_INSERT_HEAD(ast_channel_varshead(chan), var, entries);
       snprintf(expression, sizeof(expression), "${FIELDNUM(%s,%s,%s)}", var->name, test_args[i].delim, test_args[i].field);
       ast_str_substitute_variables(&str, 0, chan, expression);
       AST_LIST_REMOVE(ast_channel_varshead(chan), var, entries);
       ast_var_delete(var);
       if (strcasecmp(ast_str_buffer(str), test_args[i].expected)) {
          ast_test_status_update(test, "Evaluation of '%s' returned '%s' instead of the expected value '%s'\n",
             expression, ast_str_buffer(str), test_args[i].expected);
          res = AST_TEST_FAIL;
          break;
       }
    }
    ast_free(str);
    ast_channel_release(chan);
    return res;
 }
AST_TEST_DEFINE() [2/4]
AST_TEST_DEFINE (test_REPLACE)
Definition at line 1776 of file func_strings.c.
References ARRAY_LEN, ast_channel_release(), ast_channel_varshead(), ast_dummy_channel_alloc, ast_free, AST_LIST_INSERT_HEAD, AST_LIST_REMOVE, ast_str_buffer(), ast_str_create, ast_str_substitute_variables(), AST_TEST_FAIL, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_test_status_update, ast_var_assign, ast_var_delete(), ast_var_t::entries, sip_to_pjsip::info(), ast_var_t::name, str, TEST_EXECUTE, TEST_INIT, and var.
 {
    int i, res = AST_TEST_PASS;
    struct ast_channel *chan;
    struct ast_str *str;
    char expression[256];
    struct {
       const char *test_string;
       const char *find_chars;
       const char *replace_char;
       const char *expected;
    } test_args[] = {
       {"abc,def", "\\,", "-", "abc-def"},
       {"abc,abc", "bc",  "a", "aaa,aaa"},
       {"abc,def", "x",   "?", "abc,def"},
       {"abc,def", "\\,", "",  "abcdef"}
    };
    switch (cmd) {
    case TEST_INIT:
       info->name = "func_REPLACE_test";
       info->category = "/funcs/func_strings/";
       info->summary = "Test REPLACE function";
       info->description = "Verify REPLACE behavior";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    if (!(chan = ast_dummy_channel_alloc())) {
       ast_test_status_update(test, "Unable to allocate dummy channel\n");
       return AST_TEST_FAIL;
    }
    if (!(str = ast_str_create(16))) {
       ast_test_status_update(test, "Unable to allocate dynamic string buffer\n");
       ast_channel_release(chan);
       return AST_TEST_FAIL;
    }
    for (i = 0; i < ARRAY_LEN(test_args); i++) {
       struct ast_var_t *var = ast_var_assign("TEST_STRING", test_args[i].test_string);
       if (!var) {
          ast_test_status_update(test, "Out of memory\n");
          res = AST_TEST_FAIL;
          break;
       }
       AST_LIST_INSERT_HEAD(ast_channel_varshead(chan), var, entries);
       snprintf(expression, sizeof(expression), "${REPLACE(%s,%s,%s)}", var->name, test_args[i].find_chars, test_args[i].replace_char);
       ast_str_substitute_variables(&str, 0, chan, expression);
       AST_LIST_REMOVE(ast_channel_varshead(chan), var, entries);
       ast_var_delete(var);
       if (strcasecmp(ast_str_buffer(str), test_args[i].expected)) {
          ast_test_status_update(test, "Evaluation of '%s' returned '%s' instead of the expected value '%s'\n",
             expression, ast_str_buffer(str), test_args[i].expected);
          res = AST_TEST_FAIL;
          break;
       }
    }
    ast_free(str);
    ast_channel_release(chan);
    return res;
 }
AST_TEST_DEFINE() [3/4]
AST_TEST_DEFINE (test_FILTER)
Definition at line 1846 of file func_strings.c.
References AST_TEST_FAIL, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_test_status_update, sip_to_pjsip::info(), NULL, pbx_substitute_variables_helper(), TEST_EXECUTE, TEST_INIT, test_strings, and tmp().
 {
    int i, res = AST_TEST_PASS;
    const char *test_strings[][2] = {
       {"A-R",            "DAHDI"},
       {"A\\-R",          "A"},
       {"\\x41-R",        "DAHDI"},
       {"0-9A-Ca-c",      "0042133333A12212"},
       {"0-9a-cA-C_+\\-", "0042133333A12212"},
       {NULL,             NULL},
    };
    switch (cmd) {
    case TEST_INIT:
       info->name = "func_FILTER_test";
       info->category = "/funcs/func_strings/";
       info->summary = "Test FILTER function";
       info->description = "Verify FILTER behavior";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    for (i = 0; test_strings[i][0]; i++) {
       char tmp[256], tmp2[256] = "";
       snprintf(tmp, sizeof(tmp), "${FILTER(%s,0042133333&DAHDI/g1/2212)}", test_strings[i][0]);
       pbx_substitute_variables_helper(NULL, tmp, tmp2, sizeof(tmp2) - 1);
       if (strcmp(test_strings[i][1], tmp2)) {
          ast_test_status_update(test, "Format string '%s' substituted to '%s'.  Expected '%s'.\n", test_strings[i][0], tmp2, test_strings[i][1]);
          res = AST_TEST_FAIL;
       }
    }
    return res;
 }
AST_TEST_DEFINE() [4/4]
AST_TEST_DEFINE (test_STRREPLACE)
Definition at line 1881 of file func_strings.c.
References ARRAY_LEN, ast_channel_release(), ast_channel_varshead(), ast_dummy_channel_alloc, ast_free, AST_LIST_INSERT_HEAD, ast_str_buffer(), ast_str_create, ast_str_substitute_variables(), AST_TEST_FAIL, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_test_status_update, ast_var_assign, ast_var_t::entries, sip_to_pjsip::info(), NULL, str, TEST_EXECUTE, TEST_INIT, test_strings, tmp(), and var.
 {
    int i, res = AST_TEST_PASS;
    struct ast_channel *chan; /* dummy channel */
    struct ast_str *str; /* fancy string for holding comparing value */
    const char *test_strings[][5] = {
       {"Weasels have eaten my telephone system", "have eaten my", "are eating our", "", "Weasels are eating our telephone system"}, /*Test normal conditions */
       {"Did you know twenty plus two is twenty-two?", "twenty", "thirty", NULL, "Did you know thirty plus two is thirty-two?"}, /* Test no third comma */
       {"foofoofoofoofoofoofoo", "foofoo", "bar", NULL, "barbarbarfoo"}, /* Found string within previous match */
       {"My pet dog once ate a dog who sat on a dog while eating a corndog.", "dog", "cat", "3", "My pet cat once ate a cat who sat on a cat while eating a corndog."},
       {"One and one and one is three", "and", "plus", "1", "One plus one and one is three"}, /* Test <max-replacements> = 1*/
       {"", "fhqwagads", "spelunker", NULL, ""}, /* Empty primary string */
       {"Part of this string is missing.", "missing", NULL, NULL, "Part of this string is ."}, /* Empty replace string */
       {"'Accidentally' left off a bunch of stuff.", NULL, NULL, NULL, ""}, /* Deliberate error test from too few args */
       {"This test will also error.", "", "", "", ""}, /* Deliberate error test from blank find string */
       {"This is an \"escape character\" test.", "\\\"escape character\\\"", "evil", NULL, "This is an evil test."}
    };
    switch (cmd) {
    case TEST_INIT:
       info->name = "func_STRREPLACE_test";
       info->category = "/funcs/func_strings/";
       info->summary = "Test STRREPLACE function";
       info->description = "Verify STRREPLACE behavior";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    if (!(chan = ast_dummy_channel_alloc())) {
       ast_test_status_update(test, "Unable to allocate dummy channel\n");
       return AST_TEST_FAIL;
    }
    if (!(str = ast_str_create(64))) {
       ast_test_status_update(test, "Unable to allocate dynamic string buffer\n");
       ast_channel_release(chan);
       return AST_TEST_FAIL;
    }
    for (i = 0; i < ARRAY_LEN(test_strings); i++) {
       char tmp[512], tmp2[512] = "";
       struct ast_var_t *var = ast_var_assign("test_string", test_strings[i][0]);
       if (!var) {
          ast_test_status_update(test, "Unable to allocate variable\n");
          ast_free(str);
          ast_channel_release(chan);
          return AST_TEST_FAIL;
       }
       AST_LIST_INSERT_HEAD(ast_channel_varshead(chan), var, entries);
       if (test_strings[i][3]) {
          snprintf(tmp, sizeof(tmp), "${STRREPLACE(%s,%s,%s,%s)}", "test_string", test_strings[i][1], test_strings[i][2], test_strings[i][3]);
       } else if (test_strings[i][2]) {
          snprintf(tmp, sizeof(tmp), "${STRREPLACE(%s,%s,%s)}", "test_string", test_strings[i][1], test_strings[i][2]);
       } else if (test_strings[i][1]) {
          snprintf(tmp, sizeof(tmp), "${STRREPLACE(%s,%s)}", "test_string", test_strings[i][1]);
       } else {
          snprintf(tmp, sizeof(tmp), "${STRREPLACE(%s)}", "test_string");
       }
       ast_str_substitute_variables(&str, 0, chan, tmp);
       if (strcmp(test_strings[i][4], ast_str_buffer(str))) {
          ast_test_status_update(test, "Format string '%s' substituted to '%s'.  Expected '%s'.\n", test_strings[i][0], tmp2, test_strings[i][4]);
          res = AST_TEST_FAIL;
       }
    }
    ast_free(str);
    ast_channel_release(chan);
    return res;
 }
clearvar_prefix()
static void clearvar_prefix (struct ast_channel * chan, const char * prefix) static
Definition at line 996 of file func_strings.c.
References ast_channel_varshead(), ast_free, AST_LIST_REMOVE_CURRENT, AST_LIST_TRAVERSE_SAFE_BEGIN, AST_LIST_TRAVERSE_SAFE_END, ast_var_name(), ast_var_t::entries, len(), and var.
Referenced by exec_clearhash().
 {
    struct ast_var_t *var;
    int len = strlen(prefix);
    AST_LIST_TRAVERSE_SAFE_BEGIN(ast_channel_varshead(chan), var, entries) {
       if (strncmp(prefix, ast_var_name(var), len) == 0) {
          AST_LIST_REMOVE_CURRENT(entries);
          ast_free(var);
       }
    }
    AST_LIST_TRAVERSE_SAFE_END
 }
csv_quote()
static int csv_quote (struct ast_channel * chan, const char * cmd, char * data, char * buf, size_t len) static
Definition at line 1309 of file func_strings.c.
References ast_copy_string(), ast_log, ast_strlen_zero, buf, and LOG_ERROR.
 {
    char *bufptr = buf, *dataptr = data;
    if (len < 3) { /* at least two for quotes and one for binary zero */
       ast_log(LOG_ERROR, "Not enough buffer\n");
       return -1;
    }
    if (ast_strlen_zero(data)) {
       ast_copy_string(buf, "\"\"", len);
       return 0;
    }
    *bufptr++ = '"';
    for (; bufptr < buf + len - 3; dataptr++){
       if (*dataptr == '"') {
          *bufptr++ = '"';
          *bufptr++ = '"';
       } else if (*dataptr == '\0') {
          break;
       } else {
          *bufptr++ = *dataptr;
       }
    }
    *bufptr++ = '"';
    *bufptr='\0';
    return 0;
 }
exec_clearhash()
static int exec_clearhash (struct ast_channel * chan, const char * data) static
Definition at line 1009 of file func_strings.c.
References clearvar_prefix(), HASH_PREFIX, and prefix.
Referenced by load_module().
 {
    char prefix[80];
    snprintf(prefix, sizeof(prefix), HASH_PREFIX, data ? (char *)data : "null");
    clearvar_prefix(chan, prefix);
    return 0;
 }
filter()
static int filter (struct ast_channel * chan, const char * cmd, char * parse, char * buf, size_t len) static
Note
Looks a little strange, until you realize that we can overflow the size of a char.
Definition at line 709 of file func_strings.c.
References args, AST_APP_ARG, ast_debug, AST_DECLARE_APP_ARGS, ast_get_encoded_char(), ast_log, ast_opt_dont_warn, AST_STANDARD_RAW_ARGS, buf, LOG_ERROR, and LOG_WARNING.
Referenced by action_filter(), action_getconfig(), action_getconfigjson(), create_lookup_filter(), kqueue_timer_ack(), process_text_line(), realtime_ldap_base_ap(), stasis_subscription_set_filter(), and update2_ldap().
 {
    AST_DECLARE_APP_ARGS(args,
               AST_APP_ARG(allowed);
               AST_APP_ARG(string);
    );
    char *outbuf = buf;
    unsigned char ac;
    char allowed[256] = "";
    size_t allowedlen = 0;
    int32_t bitfield[8] = { 0, }; /* 256 bits */
    AST_STANDARD_RAW_ARGS(args, parse);
    if (!args.string) {
       ast_log(LOG_ERROR, "Usage: FILTER(<allowed-chars>,<string>)\n");
       return -1;
    }
    if (args.allowed[0] == '"' && !ast_opt_dont_warn) {
       ast_log(LOG_WARNING, "FILTER allowed characters includes the quote (\") character.  This may not be what you want.\n");
    }
    /* Expand ranges */
    for (; *(args.allowed);) {
       char c1 = 0, c2 = 0;
       size_t consumed = 0;
       if (ast_get_encoded_char(args.allowed, &c1, &consumed))
          return -1;
       args.allowed += consumed;
       if (*(args.allowed) == '-') {
          if (ast_get_encoded_char(args.allowed + 1, &c2, &consumed))
             c2 = c1;
          args.allowed += consumed + 1;
          if ((unsigned char) c2 < (unsigned char) c1 && !ast_opt_dont_warn) {
             ast_log(LOG_WARNING, "Range wrapping in FILTER(%s,%s).  This may not be what you want.\n", parse, args.string);
          }
          /*!\note
           * Looks a little strange, until you realize that we can overflow
           * the size of a char.
           */
          for (ac = (unsigned char) c1; ac != (unsigned char) c2; ac++) {
             bitfield[ac / 32] |= 1 << (ac % 32);
          }
          bitfield[ac / 32] |= 1 << (ac % 32);
          ast_debug(4, "c1=%d, c2=%d\n", c1, c2);
       } else {
          ac = (unsigned char) c1;
          ast_debug(4, "c1=%d, consumed=%d, args.allowed=%s\n", c1, (int) consumed, args.allowed - consumed);
          bitfield[ac / 32] |= 1 << (ac % 32);
       }
    }
    for (ac = 1; ac != 0; ac++) {
       if (bitfield[ac / 32] & (1 << (ac % 32))) {
          allowed[allowedlen++] = ac;
       }
    }
    ast_debug(1, "Allowed: %s\n", allowed);
    for (; *(args.string) && (buf + len - 1 > outbuf); (args.string)++) {
       if (strchr(allowed, *(args.string)))
          *outbuf++ = *(args.string);
    }
    *outbuf = '\0';
    return 0;
 }
function_eval()
static int function_eval (struct ast_channel * chan, const char * cmd, char * data, char * buf, size_t buflen) static
Definition at line 1438 of file func_strings.c.
References ast_log, ast_strlen_zero, LOG_WARNING, and pbx_substitute_variables_helper().
 {
    if (ast_strlen_zero(data)) {
       ast_log(LOG_WARNING, "EVAL requires an argument: EVAL(<string>)\n");
       return -1;
    }
    pbx_substitute_variables_helper(chan, data, buf, buflen - 1);
    return 0;
 }
function_eval2()
static int function_eval2 (struct ast_channel * chan, const char * cmd, char * data, struct ast_str ** buf, ssize_t buflen) static
Definition at line 1451 of file func_strings.c.
References ast_log, ast_str_substitute_variables(), ast_strlen_zero, and LOG_WARNING.
 {
    if (ast_strlen_zero(data)) {
       ast_log(LOG_WARNING, "EVAL requires an argument: EVAL(<string>)\n");
       return -1;
    }
    ast_str_substitute_variables(buf, buflen, chan, data);
    return 0;
 }
function_fieldnum()
static int function_fieldnum (struct ast_channel * chan, const char * cmd, char * parse, char * buf, size_t len) static
Definition at line 564 of file func_strings.c.
References function_fieldnum_helper(), and NULL.
 {
    return function_fieldnum_helper(chan, cmd, parse, buf, NULL, len);
 }
function_fieldnum_helper()
static int function_fieldnum_helper (struct ast_channel * chan, const char * cmd, char * parse, char * buf, struct ast_str ** sbuf, ssize_t len) static
Definition at line 503 of file func_strings.c.
References args, ast_alloca, AST_APP_ARG, AST_DECLARE_APP_ARGS, ast_get_encoded_char(), ast_log, AST_STANDARD_APP_ARGS, ast_str_buffer(), ast_str_set(), ast_str_strlen(), ast_str_substitute_variables(), ast_str_thread_get(), ast_strlen_zero, LOG_ERROR, NULL, result_buf, str, and strsep().
Referenced by function_fieldnum(), and function_fieldnum_str().
 {
    char *varsubst, *field;
    struct ast_str *str = ast_str_thread_get(&result_buf, 16);
    int fieldindex = 0, res = 0;
    AST_DECLARE_APP_ARGS(args,
       AST_APP_ARG(varname);
       AST_APP_ARG(delim);
       AST_APP_ARG(field);
    );
    char delim[2] = "";
    size_t delim_used;
    if (!str) {
       return -1;
    }
    AST_STANDARD_APP_ARGS(args, parse);
    if (args.argc < 3) {
       ast_log(LOG_ERROR, "Usage: FIELDNUM(<listname>,<delimiter>,<fieldvalue>)\n");
       res = -1;
    } else {
       varsubst = ast_alloca(strlen(args.varname) + 4);
       sprintf(varsubst, "${%s}", args.varname);
       ast_str_substitute_variables(&str, 0, chan, varsubst);
       if (ast_str_strlen(str) == 0 || ast_strlen_zero(args.delim)) {
          fieldindex = 0;
       } else if (ast_get_encoded_char(args.delim, delim, &delim_used) == -1) {
          res = -1;
       } else {
          char *varval = ast_str_buffer(str);
          while ((field = strsep(&varval, delim)) != NULL) {
             fieldindex++;
             if (!strcasecmp(field, args.field)) {
                break;
             }
          }
          if (!field) {
             fieldindex = 0;
          }
          res = 0;
       }
    }
    if (sbuf) {
       ast_str_set(sbuf, len, "%d", fieldindex);
    } else {
       snprintf(buf, len, "%d", fieldindex);
    }
    return res;
 }
function_fieldnum_str()
static int function_fieldnum_str (struct ast_channel * chan, const char * cmd, char * parse, struct ast_str ** buf, ssize_t len) static
Definition at line 570 of file func_strings.c.
References function_fieldnum_helper(), and NULL.
 {
    return function_fieldnum_helper(chan, cmd, parse, NULL, buf, len);
 }
function_fieldqty()
static int function_fieldqty (struct ast_channel * chan, const char * cmd, char * parse, char * buf, size_t len) static
Definition at line 485 of file func_strings.c.
References function_fieldqty_helper(), and NULL.
 {
    return function_fieldqty_helper(chan, cmd, parse, buf, NULL, len);
 }
function_fieldqty_helper()
static int function_fieldqty_helper (struct ast_channel * chan, const char * cmd, char * parse, char * buf, struct ast_str ** sbuf, ssize_t len) static
Definition at line 440 of file func_strings.c.
References args, ast_alloca, AST_APP_ARG, AST_DECLARE_APP_ARGS, ast_get_encoded_char(), AST_STANDARD_APP_ARGS, ast_str_buffer(), ast_str_set(), ast_str_strlen(), ast_str_substitute_variables(), ast_str_thread_get(), result_buf, str, and strsep().
Referenced by function_fieldqty(), and function_fieldqty_str().
 {
    char *varsubst;
    struct ast_str *str = ast_str_thread_get(&result_buf, 16);
    int fieldcount = 0;
    AST_DECLARE_APP_ARGS(args,
               AST_APP_ARG(varname);
               AST_APP_ARG(delim);
       );
    char delim[2] = "";
    size_t delim_used;
    if (!str) {
       return -1;
    }
    AST_STANDARD_APP_ARGS(args, parse);
    if (args.delim) {
       ast_get_encoded_char(args.delim, delim, &delim_used);
       varsubst = ast_alloca(strlen(args.varname) + 4);
       sprintf(varsubst, "${%s}", args.varname);
       ast_str_substitute_variables(&str, 0, chan, varsubst);
       if (ast_str_strlen(str) == 0) {
          fieldcount = 0;
       } else {
          char *varval = ast_str_buffer(str);
          while (strsep(&varval, delim)) {
             fieldcount++;
          }
       }
    } else {
       fieldcount = 1;
    }
    if (sbuf) {
       ast_str_set(sbuf, len, "%d", fieldcount);
    } else {
       snprintf(buf, len, "%d", fieldcount);
    }
    return 0;
 }
function_fieldqty_str()
static int function_fieldqty_str (struct ast_channel * chan, const char * cmd, char * parse, struct ast_str ** buf, ssize_t len) static
Definition at line 491 of file func_strings.c.
References function_fieldqty_helper(), and NULL.
 {
    return function_fieldqty_helper(chan, cmd, parse, NULL, buf, len);
 }
get_key()
static const char* get_key (const struct ast_str * prefix, const struct ast_var_t * var) static
Definition at line 1092 of file func_strings.c.
References ast_str_buffer(), ast_str_strlen(), ast_strlen_zero, ast_var_name(), and NULL.
Referenced by hashkeys_read(), and hashkeys_read2().
 {
    const char *prefix_name = ast_str_buffer(prefix);
    const char *var_name = ast_var_name(var);
    int prefix_len;
    int var_len;
    if (ast_strlen_zero(var_name)) {
       return NULL;
    }
    prefix_len = ast_str_strlen(prefix);
    var_len = strlen(var_name);
    /*
     * Make sure we only match on non-empty, hash function created keys. If valid
     * then return a pointer to the variable that's just after the prefix.
     */
    return var_len > (prefix_len + 1) && var_name[var_len - 1] == '~' &&
       strncmp(prefix_name, var_name, prefix_len) == 0 ? var_name + prefix_len : NULL;
 }
hash_read()
static int hash_read (struct ast_channel * chan, const char * cmd, char * data, char * buf, size_t len) static
Definition at line 1202 of file func_strings.c.
References AST_APP_ARG, ast_copy_string(), AST_DECLARE_APP_ARGS, ast_log, AST_STANDARD_APP_ARGS, HASH_FORMAT, hashkeys_read(), LOG_WARNING, pbx_builtin_getvar_helper(), and pbx_builtin_setvar_helper().
 {
    char varname[256];
    const char *varvalue;
    AST_DECLARE_APP_ARGS(arg,
       AST_APP_ARG(hashname);
       AST_APP_ARG(hashkey);
    );
    AST_STANDARD_APP_ARGS(arg, data);
    if (arg.argc == 2) {
       snprintf(varname, sizeof(varname), HASH_FORMAT, arg.hashname, arg.hashkey);
       varvalue = pbx_builtin_getvar_helper(chan, varname);
       if (varvalue)
          ast_copy_string(buf, varvalue, len);
       else
          *buf = '\0';
    } else if (arg.argc == 1) {
       char colnames[4096];
       int i;
       AST_DECLARE_APP_ARGS(arg2,
          AST_APP_ARG(col)[100];
       );
       if (!chan) {
          ast_log(LOG_WARNING, "No channel and only 1 parameter was provided to %s function.\n", cmd);
          return -1;
       }
       /* Get column names, in no particular order */
       hashkeys_read(chan, "HASHKEYS", arg.hashname, colnames, sizeof(colnames));
       pbx_builtin_setvar_helper(chan, "~ODBCFIELDS~", colnames);
       AST_STANDARD_APP_ARGS(arg2, colnames);
       *buf = '\0';
       /* Now get the corresponding column values, in exactly the same order */
       for (i = 0; i < arg2.argc; i++) {
          snprintf(varname, sizeof(varname), HASH_FORMAT, arg.hashname, arg2.col[i]);
          varvalue = pbx_builtin_getvar_helper(chan, varname);
          strncat(buf, varvalue, len - strlen(buf) - 1);
          strncat(buf, ",", len - strlen(buf) - 1);
       }
       /* Strip trailing comma */
       buf[strlen(buf) - 1] = '\0';
    }
    return 0;
 }
hash_write()
static int hash_write (struct ast_channel * chan, const char * cmd, char * var, const char * value) static
Definition at line 1174 of file func_strings.c.
References array(), AST_APP_ARG, AST_DECLARE_APP_ARGS, AST_STANDARD_APP_ARGS, HASH_FORMAT, and pbx_builtin_setvar_helper().
 {
    char varname[256];
    AST_DECLARE_APP_ARGS(arg,
       AST_APP_ARG(hashname);
       AST_APP_ARG(hashkey);
    );
    if (!strchr(var, ',')) {
       /* Single argument version */
       return array(chan, "HASH", var, value);
    }
    AST_STANDARD_APP_ARGS(arg, var);
    if (arg.hashname[0] == '_') {
       if (arg.hashname[1] == '_') {
          snprintf(varname, sizeof(varname), "__" HASH_FORMAT, arg.hashname + 2, arg.hashkey);
       } else {
          snprintf(varname, sizeof(varname), "_" HASH_FORMAT, arg.hashname + 1, arg.hashkey);
       }
    } else {
       snprintf(varname, sizeof(varname), HASH_FORMAT, arg.hashname, arg.hashkey);
    }
    pbx_builtin_setvar_helper(chan, varname, value);
    return 0;
 }
hashkeys_read()
static int hashkeys_read (struct ast_channel * chan, const char * cmd, char * data, char * buf, size_t len) static
Definition at line 1114 of file func_strings.c.
References ast_channel_varshead(), AST_LIST_TRAVERSE, ast_log, ast_str_alloca, ast_str_set(), get_key(), HASH_PREFIX, LOG_WARNING, and prefix.
Referenced by hash_read().
 {
    struct ast_var_t *newvar;
    struct ast_str *prefix = ast_str_alloca(80);
    size_t buf_len;
    if (!chan) {
       ast_log(LOG_WARNING, "No channel was provided to %s function.\n", cmd);
       return -1;
    }
    ast_str_set(&prefix, -1, HASH_PREFIX, data);
    memset(buf, 0, len);
    AST_LIST_TRAVERSE(ast_channel_varshead(chan), newvar, entries) {
       const char *key = get_key(prefix, newvar);
       if (key) {
          strncat(buf, key, len - strlen(buf) - 1);
          /* Replace the trailing ~ */
          buf[strlen(buf) - 1] = ',';
       }
    }
    /* Trim the trailing comma */
    buf_len = strlen(buf);
    if (buf_len) {
       buf[buf_len - 1] = '\0';
    }
    return 0;
 }
hashkeys_read2()
static int hashkeys_read2 (struct ast_channel * chan, const char * cmd, char * data, struct ast_str ** buf, ssize_t len) static
Definition at line 1145 of file func_strings.c.
References ast_channel_varshead(), AST_LIST_TRAVERSE, ast_log, ast_str_alloca, ast_str_append(), ast_str_buffer(), ast_str_set(), ast_str_strlen(), ast_str_truncate(), get_key(), HASH_PREFIX, LOG_WARNING, prefix, and tmp().
 {
    struct ast_var_t *newvar;
    struct ast_str *prefix = ast_str_alloca(80);
    if (!chan) {
       ast_log(LOG_WARNING, "No channel was provided to %s function.\n", cmd);
       return -1;
    }
    ast_str_set(&prefix, -1, HASH_PREFIX, data);
    AST_LIST_TRAVERSE(ast_channel_varshead(chan), newvar, entries) {
       const char *key = get_key(prefix, newvar);
       if (key) {
          char *tmp;
          ast_str_append(buf, len, "%s", key);
          /* Replace the trailing ~ */
          tmp = ast_str_buffer(*buf);
          tmp[ast_str_strlen(*buf) - 1] = ',';
       }
    }
    ast_str_truncate(*buf, -1);
    return 0;
 }
keypadhash()
static int keypadhash (struct ast_channel * chan, const char * cmd, char * data, char * buf, size_t buflen) static
Definition at line 1470 of file func_strings.c.
 {
    char *bufptr, *dataptr;
    for (bufptr = buf, dataptr = data; bufptr < buf + buflen - 1; dataptr++) {
       if (*dataptr == '\0') {
          *bufptr++ = '\0';
          break;
       } else if (*dataptr == '1') {
          *bufptr++ = '1';
       } else if (strchr("AaBbCc2", *dataptr)) {
          *bufptr++ = '2';
       } else if (strchr("DdEeFf3", *dataptr)) {
          *bufptr++ = '3';
       } else if (strchr("GgHhIi4", *dataptr)) {
          *bufptr++ = '4';
       } else if (strchr("JjKkLl5", *dataptr)) {
          *bufptr++ = '5';
       } else if (strchr("MmNnOo6", *dataptr)) {
          *bufptr++ = '6';
       } else if (strchr("PpQqRrSs7", *dataptr)) {
          *bufptr++ = '7';
       } else if (strchr("TtUuVv8", *dataptr)) {
          *bufptr++ = '8';
       } else if (strchr("WwXxYyZz9", *dataptr)) {
          *bufptr++ = '9';
       } else if (*dataptr == '0') {
          *bufptr++ = '0';
       }
    }
    buf[buflen - 1] = '\0';
    return 0;
 }
len()
static int len (struct ast_channel * chan, const char * cmd, char * data, char * buf, size_t buflen) static
Examples:
/usr/src/asterisk-18.5.0/include/asterisk/strings.h, and /usr/src/asterisk-18.5.0/main/app.c.
Definition at line 1344 of file func_strings.c.
Referenced by __analog_ss_thread(), __ast_cli_register(), __ast_cli_register_multiple(), __ast_dsp_call_progress(), __ast_dsp_silence_noise(), __ast_frdup(), __big_return(), __bt_defcmp(), __bt_defpfx(), OrderedDict::__eq__(), __get_header(), OrderedDict::__init__(), __rec_fmap(), __rec_fpipe(), __rec_vpipe(), __rtp_recvfrom(), __rtp_sendto(), MultiOrderedDict::__setitem__(), __stub__ast_agi_unregister(), _parse(), AbsQuantW(), acf_escape(), action_command(), FaxPcap::add(), add_sdp(), adsi_careful_send(), ael_token_subst(), alsa_write(), amdf_pitch(), anaFilter(), analog_ss_thread(), anti_injection(), ao2_container_check(), aoc_parse_ie(), append_interface(), append_var_and_value_to_filter(), apply_outgoing(), ast_agi_register_multiple(), ast_agi_unregister_multiple(), ast_app_group_set_channel(), ast_app_options2str64(), ast_audiosocket_receive_frame(), ast_beep_start(), ast_bucket_alloc(), ast_bucket_file_alloc(), ast_channel_get_cc_agent_type(), ast_channel_get_device_name(), ast_cli_complete(), ast_cli_unregister_multiple(), ast_dns_test_write_string(), ast_dsp_process(), ast_dsp_silence_noise_with_energy(), ast_format_str_reduce(), ast_get_namedgroups(), ast_http_send(), ast_http_uri_link(), ast_iostream_gets(), ast_iostream_printf(), ast_join_delim(), ast_json_utf8_check_len(), ast_mkdir(), ast_msg_data_alloc(), ast_read_image(), ast_register_cleanup(), ast_rtcp_generate_report(), ast_rtcp_generate_sdes(), ast_rtp_interpret(), ast_say_number_full_ka(), ast_srtp_protect(), ast_srtp_unprotect(), ast_statsd_log_string(), ast_str_buffer(), ast_str_substitute_variables_full(), ast_tdd_gen_ecdisa(), AST_TEST_DEFINE(), ast_translate(), ast_websocket_write_string(), ast_xml_escape(), ast_xmldoc_printable(), auth_exec(), authenticate(), bucket_copy(), bucket_file_wizard_retrieve(), bucket_wizard_retrieve(), build_device(), build_facility(), build_ha(), build_regex(), build_route(), calc_energy(), category_set_sublevels(), CB_ADD_LEN(), cdr_read(), channel_do_masquerade(), chararray_handler_fn(), cleaned_basedn(), clearvar_prefix(), cli_complete(), cli_console_sendtext(), sip_to_pjsql::cli_options(), sip_to_pjsip::cli_options(), closefrom(), complete_confno(), complete_dialplan_add_extension(), complete_dialplan_add_ignorepat(), complete_dialplan_add_include(), complete_dialplan_remove_context(), complete_dialplan_remove_extension(), complete_dialplan_remove_ignorepat(), complete_dialplan_remove_include(), complete_meetmecmd_list(), complete_meetmecmd_mute_kick(), complete_peer_helper(), complete_userno(), conf_get_pin(), conf_play(), config_jitterbuffer(), cops_getmsg(), copy(), create_video_frame(), dahdi_cc_callback(), dahdi_chan_conf_default(), dahdi_sendtext(), dahdi_setoption(), dbl_list_expect_reverse(), dbm_open(), dcbias_(), devstate_write(), dialgroup_refreshdb(), dictate_exec(), do_pktccops(), do_tone(), dtmf_store_framehook(), dump_addr(), dump_ipaddr(), dump_prefs(), dump_raw(), dump_string(), dump_versioned_codec(), dundi_encrypt(), dundi_parse_ies(), dundi_send(), enc_ie_facility(), energy_(), eval_exten_read(), expand_gosub_args(), expr2_token_subst(), ext_cmp_exten_strlen(), fax_generator_generate(), fbuf_append(), fetch_response_reader(), ffmpeg_decode(), flip_buf_bits(), frame_set_var(), fsk_serial(), func_read_header(), g722_decode(), g722_encode(), PathSegment::get_child(), get_content_line(), get_name_from_resource(), get_sdp(), get_sdp_iterate(), gsm_write(), gsmtolin_framein(), h261_encap(), h263_encap(), h263_read(), h263_write(), h263p_encap(), h264_read(), h264_write(), handle_cli_devstate_change(), handle_cli_mobile_search(), handle_cli_moh_unregister_class(), handle_cli_presencestate_change(), handle_commandmatchesarray(), handle_incoming(), handle_keypad_button_message(), handle_output(), handle_response(), handle_show_sysinfo(), handle_soft_key_event_message(), Model::has_properties(), Model::has_subtypes(), header_identify_match_check(), help1(), hepv3_create_capture_info(), hpInput(), hpOutput(), http_request_headers_get(), httpd_process_request(), iax_parse_ies(), iax_str2flags(), inner_product_single(), interpolate_product_single(), ip_identify_apply(), ivfilt_(), jb_debug_output(), json_utf8_check_full(), listener(), lpc10_decode(), lpc10tolin_framein(), lpfilt_(), lws2sws(), make_ari_stubs::main(), main(), refcounter::main(), spandspflow2pcap::main(), manager_login(), memcpy_decrypt(), memcpy_encrypt(), message_template_parse_emailbody(), method_match(), mgcp_postrequest(), mgcp_ss(), mgcpsock_read(), milliwatt_generate(), misdn_jb_empty(), misdn_jb_fill(), misdn_lib_tx2misdn_frm(), misdn_read(), misdn_tx_jitter(), monmp3thread(), mpeg4_encap(), my_dahdi_write(), newpvt(), PathSegment::num_children(), openssl_error_string(), parse_bookmark(), parse_ie(), refcounter::parse_line(), get_documentation::parse_manager_event_instance(), pbx_substitute_variables_helper_full(), phone_write_buf(), pjsip_acf_channel_read(), playtones_generator(), plc_fillin(), plc_rx(), pp_each_extension_helper(), presence_write(), reflocks::process_file(), refstats::process_file(), process_sdp(), read_credentials(), receive_message(), refer_blind_callback(), remove_header(), res_sdp_srtp_get_attr(), reschedule_precache(), resource_name_baselen(), rtp_instance_parse_extmap_extensions(), run_agi(), save_history(), scan_thread(), schedule_delivery(), sco_accept(), send_string(), set(), set_bridge_peer_vars_multiparty(), shared_write(), sip_addheader(), sip_route_process_header(), sip_show_channel(), sip_show_history(), sip_tcptls_write(), sms_messagetx(), socket_process_meta(), start_automixmonitor(), start_automonitor(), StateConstructW(), StateSearchW(), static_callback(), strnncpy(), syntFilter(), tdd_feed(), term_filter_escapes(), threadstorage_init(), tonepair_generator(), transfer_exec(), transmit_response_bysession(), try_firmware(), unistim_sp(), unquote(), OrderedDict::update(), uri_parse_and_default(), vm_allocate_dh(), wav_write(), ws_safe_read(), ws_send_msg(), xmldoc_get_syntax_fun(), xmldoc_setpostbr(), xmpp_client_authenticate_sasl(), xmpp_client_receive(), xmpp_client_send_raw_message(), and xmpp_io_recv().
 {
    int length = 0;
    if (data)
       length = strlen(data);
    snprintf(buf, buflen, "%d", length);
    return 0;
 }
listfilter()
static int listfilter (struct ast_channel * chan, const char * cmd, char * parse, char * buf, struct ast_str ** bufstr, ssize_t len) static
Definition at line 582 of file func_strings.c.
References args, ast_alloca, AST_APP_ARG, ast_channel_lock, ast_channel_unlock, ast_copy_string(), AST_DECLARE_APP_ARGS, ast_get_encoded_str(), ast_log, AST_STANDARD_APP_ARGS, ast_str_append(), ast_str_append_substr(), ast_str_buffer(), ast_str_make_space, ast_str_reset(), ast_str_set(), ast_str_strlen(), ast_str_substitute_variables(), ast_str_thread_get(), first, LOG_ERROR, result, result_buf, and tmp_buf.
Referenced by listfilter_read(), and listfilter_read2().
 {
    AST_DECLARE_APP_ARGS(args,
       AST_APP_ARG(listname);
       AST_APP_ARG(delimiter);
       AST_APP_ARG(fieldvalue);
    );
    struct ast_str *orig_list = ast_str_thread_get(&tmp_buf, 16);
    const char *begin, *cur, *next;
    int dlen, flen, first = 1;
    struct ast_str *result, **result_ptr = &result;
    char *delim, *varsubst;
    AST_STANDARD_APP_ARGS(args, parse);
    if (buf) {
       if (!(result = ast_str_thread_get(&result_buf, 16))) {
          return -1;
       }
    } else {
       /* Place the result directly into the output buffer */
       result_ptr = bufstr;
    }
    if (args.argc < 3) {
       ast_log(LOG_ERROR, "Usage: LISTFILTER(<listname>,<delimiter>,<fieldvalue>)\n");
       return -1;
    }
    varsubst = ast_alloca(strlen(args.listname) + 4);
    sprintf(varsubst, "${%s}", args.listname);
    /* If we don't lock the channel, the variable could disappear out from underneath us. */
    if (chan) {
       ast_channel_lock(chan);
    }
    ast_str_substitute_variables(&orig_list, 0, chan, varsubst);
    if (!ast_str_strlen(orig_list)) {
       if (chan) {
          ast_channel_unlock(chan);
       }
       return -1;
    }
    /* If the string isn't there, just copy out the string and be done with it. */
    if (!strstr(ast_str_buffer(orig_list), args.fieldvalue)) {
       if (buf) {
          ast_copy_string(buf, ast_str_buffer(orig_list), len);
       } else {
          ast_str_set(result_ptr, len, "%s", ast_str_buffer(orig_list));
       }
       if (chan) {
          ast_channel_unlock(chan);
       }
       return 0;
    }
    dlen = strlen(args.delimiter);
    delim = ast_alloca(dlen + 1);
    ast_get_encoded_str(args.delimiter, delim, dlen + 1);
    if ((dlen = strlen(delim)) == 0) {
       delim = ",";
       dlen = 1;
    }
    flen = strlen(args.fieldvalue);
    ast_str_reset(*result_ptr);
    /* Enough space for any result */
    if (len > -1) {
       ast_str_make_space(result_ptr, len ? len : ast_str_strlen(orig_list) + 1);
    }
    begin = ast_str_buffer(orig_list);
    next = strstr(begin, delim);
    do {
       /* Find next boundary */
       if (next) {
          cur = next;
          next = strstr(cur + dlen, delim);
       } else {
          cur = strchr(begin + dlen, '\0');
       }
       if (flen == cur - begin && !strncmp(begin, args.fieldvalue, flen)) {
          /* Skip field */
          begin += flen + dlen;
       } else {
          /* Copy field to output */
          if (!first) {
             ast_str_append(result_ptr, len, "%s", delim);
          }
          ast_str_append_substr(result_ptr, len, begin, cur - begin);
          first = 0;
          begin = cur + dlen;
       }
    } while (*cur != '\0');
    if (chan) {
       ast_channel_unlock(chan);
    }
    if (buf) {
       ast_copy_string(buf, ast_str_buffer(result), len);
    }
    return 0;
 }
listfilter_read()
static int listfilter_read (struct ast_channel * chan, const char * cmd, char * parse, char * buf, size_t len) static
Definition at line 693 of file func_strings.c.
References listfilter(), and NULL.
 {
    return listfilter(chan, cmd, parse, buf, NULL, len);
 }
listfilter_read2()
static int listfilter_read2 (struct ast_channel * chan, const char * cmd, char * parse, struct ast_str ** buf, ssize_t len) static
Definition at line 698 of file func_strings.c.
References listfilter(), and NULL.
 {
    return listfilter(chan, cmd, parse, NULL, buf, len);
 }
load_module()
static int load_module (void) static
Definition at line 1995 of file func_strings.c.
References app_clearhash, ast_custom_function_register, ast_register_application_xml, AST_TEST_REGISTER, and exec_clearhash().
 {
    int res = 0;
    AST_TEST_REGISTER(test_FIELDNUM);
    AST_TEST_REGISTER(test_REPLACE);
    AST_TEST_REGISTER(test_FILTER);
    AST_TEST_REGISTER(test_STRREPLACE);
    res |= ast_custom_function_register(&fieldqty_function);
    res |= ast_custom_function_register(&fieldnum_function);
    res |= ast_custom_function_register(&filter_function);
    res |= ast_custom_function_register(&replace_function);
    res |= ast_custom_function_register(&strreplace_function);
    res |= ast_custom_function_register(&listfilter_function);
    res |= ast_custom_function_register(&regex_function);
    res |= ast_custom_function_register(&array_function);
    res |= ast_custom_function_register(&quote_function);
    res |= ast_custom_function_register(&csv_quote_function);
    res |= ast_custom_function_register(&len_function);
    res |= ast_custom_function_register(&strftime_function);
    res |= ast_custom_function_register(&strptime_function);
    res |= ast_custom_function_register(&eval_function);
    res |= ast_custom_function_register(&keypadhash_function);
    res |= ast_custom_function_register(&hashkeys_function);
    res |= ast_custom_function_register(&hash_function);
    res |= ast_register_application_xml(app_clearhash, exec_clearhash);
    res |= ast_custom_function_register(&toupper_function);
    res |= ast_custom_function_register(&tolower_function);
    res |= ast_custom_function_register(&shift_function);
    res |= ast_custom_function_register(&pop_function);
    res |= ast_custom_function_register(&push_function);
    res |= ast_custom_function_register(&unshift_function);
    res |= ast_custom_function_register(&passthru_function);
    return res;
 }
passthru()
static int passthru (struct ast_channel * chan, const char * cmd, char * data, struct ast_str ** buf, ssize_t len) static
Definition at line 1692 of file func_strings.c.
References ast_str_set().
 {
    ast_str_set(buf, len, "%s", data);
    return 0;
 }
quote()
static int quote (struct ast_channel * chan, const char * cmd, char * data, char * buf, size_t len) static
Examples:
/usr/src/asterisk-18.5.0/main/app.c.
Definition at line 1270 of file func_strings.c.
References ast_copy_string(), ast_log, ast_strlen_zero, buf, LOG_ERROR, and LOG_WARNING.
Referenced by __ast_app_separate_args(), ast_app_separate_args(), parse_options(), and vm_allocate_dh().
 {
    char *bufptr = buf, *dataptr = data;
    if (len < 3){ /* at least two for quotes and one for binary zero */
       ast_log(LOG_ERROR, "Not enough buffer\n");
       return -1;
    }
    if (ast_strlen_zero(data)) {
       ast_log(LOG_WARNING, "No argument specified!\n");
       ast_copy_string(buf, "\"\"", len);
       return 0;
    }
    *bufptr++ = '"';
    for (; bufptr < buf + len - 3; dataptr++) {
       if (*dataptr == '\\') {
          *bufptr++ = '\\';
          *bufptr++ = '\\';
       } else if (*dataptr == '"') {
          *bufptr++ = '\\';
          *bufptr++ = '"';
       } else if (*dataptr == '\0') {
          break;
       } else {
          *bufptr++ = *dataptr;
       }
    }
    *bufptr++ = '"';
    *bufptr = '\0';
    return 0;
 }
regex()
static int regex (struct ast_channel * chan, const char * cmd, char * parse, char * buf, size_t len) static
Definition at line 948 of file func_strings.c.
References args, AST_APP_ARG, ast_debug, AST_DECLARE_APP_ARGS, ast_log, AST_NONSTANDARD_APP_ARGS, LOG_ERROR, LOG_WARNING, NULL, and str.
Referenced by ast_sip_cli_traverse_objects(), ast_strings_match(), build_regex(), cli_list_subscriptions_inout(), cli_show_subscriptions_inout(), cli_show_tasks(), config_option_destroy(), and xmldoc_get_syntax_config_option().
 {
    AST_DECLARE_APP_ARGS(args,
               AST_APP_ARG(null);
               AST_APP_ARG(reg);
               AST_APP_ARG(str);
    );
    int errcode;
    regex_t regexbuf;
    buf[0] = '\0';
    AST_NONSTANDARD_APP_ARGS(args, parse, '"');
    if (args.argc != 3) {
       ast_log(LOG_ERROR, "Unexpected arguments: should have been in the form '\"<regex>\" <string>'\n");
       return -1;
    }
    if ((*args.str == ' ') || (*args.str == '\t'))
       args.str++;
    ast_debug(1, "FUNCTION REGEX (%s)(%s)\n", args.reg, args.str);
    if ((errcode = regcomp(&regexbuf, args.reg, REG_EXTENDED | REG_NOSUB))) {
       regerror(errcode, &regexbuf, buf, len);
       ast_log(LOG_WARNING, "Malformed input %s(%s): %s\n", cmd, parse, buf);
       return -1;
    }
    strcpy(buf, regexec(&regexbuf, args.str, 0, NULL, 0) ? "0" : "1");
    regfree(&regexbuf);
    return 0;
 }
replace()
static int replace (struct ast_channel * chan, const char * cmd, char * data, struct ast_str ** buf, ssize_t len) static
Definition at line 790 of file func_strings.c.
References args, ast_alloca, AST_APP_ARG, ast_debug, AST_DECLARE_APP_ARGS, ast_free, ast_get_encoded_char(), ast_get_encoded_str(), ast_log, AST_STANDARD_APP_ARGS, ast_str_buffer(), ast_str_create, ast_str_set(), ast_str_strlen(), ast_str_substitute_variables(), ast_strlen_zero, LOG_ERROR, RAII_VAR, and str.
Referenced by FaxPcap::add(), app_get_replace_channel_app(), app_set_replace_channel_app(), app_set_replace_channel_snapshot(), get_replace_channel_snapshot(), ResourceApi::load(), ApiDeclaration::load_file(), manager_dialplan_extension_add(), spandspflow2pcap::n2b(), get_documentation::parse_manager_event_instance(), pj_thread_register_check(), process_text_line(), replace_channel_destroy(), and astconfigparser::try_section().
 {
    AST_DECLARE_APP_ARGS(args,
       AST_APP_ARG(varname);
       AST_APP_ARG(find);
       AST_APP_ARG(replace);
    );
    char *strptr, *varsubst;
    RAII_VAR(struct ast_str *, str, ast_str_create(16), ast_free);
    char find[256]; /* Only 256 characters possible */
    char replace[2] = "";
    size_t unused;
    AST_STANDARD_APP_ARGS(args, data);
    if (!str) {
       return -1;
    }
    if (args.argc < 2) {
       ast_log(LOG_ERROR, "Usage: %s(<varname>,<search-chars>[,<replace-char>])\n", cmd);
       return -1;
    }
    /* Decode escapes */
    ast_get_encoded_str(args.find, find, sizeof(find));
    ast_get_encoded_char(args.replace, replace, &unused);
    if (ast_strlen_zero(find) || ast_strlen_zero(args.varname)) {
       ast_log(LOG_ERROR, "The characters to search for and the variable name must not be empty.\n");
       return -1;
    }
    varsubst = ast_alloca(strlen(args.varname) + 4);
    sprintf(varsubst, "${%s}", args.varname);
    ast_str_substitute_variables(&str, 0, chan, varsubst);
    if (!ast_str_strlen(str)) {
       /* Blank, nothing to replace */
       return -1;
    }
    ast_debug(3, "String to search: (%s)\n", ast_str_buffer(str));
    ast_debug(3, "Characters to find: (%s)\n", find);
    ast_debug(3, "Character to replace with: (%s)\n", replace);
    for (strptr = ast_str_buffer(str); *strptr; strptr++) {
       /* buf is already a mutable buffer, so we construct the result
        * directly there */
       if (strchr(find, *strptr)) {
          if (ast_strlen_zero(replace)) {
             memmove(strptr, strptr + 1, strlen(strptr + 1) + 1);
             strptr--;
          } else {
             /* Replace character */
             *strptr = *replace;
          }
       }
    }
    ast_str_set(buf, len, "%s", ast_str_buffer(str));
    return 0;
 }
shift_pop()
static int shift_pop (struct ast_channel * chan, const char * cmd, char * data, struct ast_str ** buf, ssize_t len) static
Definition at line 1568 of file func_strings.c.
References args, ast_alloca, AST_APP_ARG, AST_DECLARE_APP_ARGS, ast_get_encoded_char(), ast_log, AST_STANDARD_APP_ARGS, ast_str_buffer(), ast_str_set(), ast_str_strlen(), ast_str_substitute_variables(), ast_str_thread_get(), ast_strlen_zero, beginning, c, LOG_WARNING, pbx_builtin_setvar_helper(), result_buf, and var.
 {
 #define beginning (cmd[0] == 'S') /* SHIFT */
    char *after, delimiter[2] = ",", *varsubst;
    size_t unused;
    struct ast_str *before = ast_str_thread_get(&result_buf, 16);
    char *(*search_func)(const char *s, int c) = (beginning ? strchr : strrchr);
    AST_DECLARE_APP_ARGS(args,
       AST_APP_ARG(var);
       AST_APP_ARG(delimiter);
    );
    if (!before) {
       return -1;
    }
    AST_STANDARD_APP_ARGS(args, data);
    if (ast_strlen_zero(args.var)) {
       ast_log(LOG_WARNING, "%s requires a variable name\n", cmd);
       return -1;
    }
    varsubst = ast_alloca(strlen(args.var) + 4);
    sprintf(varsubst, "${%s}", args.var);
    ast_str_substitute_variables(&before, 0, chan, varsubst);
    if (args.argc > 1 && !ast_strlen_zero(args.delimiter)) {
       ast_get_encoded_char(args.delimiter, delimiter, &unused);
    }
    if (!ast_str_strlen(before)) {
       /* Nothing to pop */
       return -1;
    }
    if (!(after = search_func(ast_str_buffer(before), delimiter[0]))) {
       /* Only one entry in array */
       ast_str_set(buf, len, "%s", ast_str_buffer(before));
       pbx_builtin_setvar_helper(chan, args.var, "");
    } else {
       *after++ = '\0';
       ast_str_set(buf, len, "%s", beginning ? ast_str_buffer(before) : after);
       pbx_builtin_setvar_helper(chan, args.var, beginning ? after : ast_str_buffer(before));
    }
    return 0;
 #undef beginning
 }
string_tolower()
static int string_tolower (struct ast_channel * chan, const char * cmd, char * data, char * buf, size_t buflen) static
Definition at line 1539 of file func_strings.c.
References buf.
 {
    char *bufptr = buf, *dataptr = data;
    while ((bufptr < buf + buflen - 1) && (*bufptr++ = tolower(*dataptr++)));
    return 0;
 }
string_tolower2()
static int string_tolower2 (struct ast_channel * chan, const char * cmd, char * data, struct ast_str ** buf, ssize_t buflen) static
Definition at line 1548 of file func_strings.c.
References ast_str_buffer(), ast_str_make_space, ast_str_size(), and ast_str_update().
 {
    char *bufptr, *dataptr = data;
    if (buflen > -1) {
       ast_str_make_space(buf, buflen > 0 ? buflen : strlen(data) + 1);
    }
    bufptr = ast_str_buffer(*buf);
    while ((bufptr < ast_str_buffer(*buf) + ast_str_size(*buf) - 1) && (*bufptr++ = tolower(*dataptr++)));
    ast_str_update(*buf);
    return 0;
 }
string_toupper()
static int string_toupper (struct ast_channel * chan, const char * cmd, char * data, char * buf, size_t buflen) static
Definition at line 1510 of file func_strings.c.
References buf.
 {
    char *bufptr = buf, *dataptr = data;
    while ((bufptr < buf + buflen - 1) && (*bufptr++ = toupper(*dataptr++)));
    return 0;
 }
string_toupper2()
static int string_toupper2 (struct ast_channel * chan, const char * cmd, char * data, struct ast_str ** buf, ssize_t buflen) static
Definition at line 1519 of file func_strings.c.
References ast_str_buffer(), ast_str_make_space, ast_str_size(), and ast_str_update().
 {
    char *bufptr, *dataptr = data;
    if (buflen > -1) {
       ast_str_make_space(buf, buflen > 0 ? buflen : strlen(data) + 1);
    }
    bufptr = ast_str_buffer(*buf);
    while ((bufptr < ast_str_buffer(*buf) + ast_str_size(*buf) - 1) && (*bufptr++ = toupper(*dataptr++)));
    ast_str_update(*buf);
    return 0;
 }
strreplace()
static int strreplace (struct ast_channel * chan, const char * cmd, char * data, struct ast_str ** buf, ssize_t len) static
Definition at line 859 of file func_strings.c.
References args, ast_alloca, AST_APP_ARG, AST_DECLARE_APP_ARGS, ast_log, AST_STANDARD_APP_ARGS, ast_str_append(), ast_str_buffer(), ast_str_reset(), ast_str_substitute_variables(), ast_str_thread_get(), ast_strlen_zero, end, LOG_ERROR, result_buf, and str.
 {
    char *varsubstr; /* substring for input var */
    char *start; /* Starting pos of substring search. */
    char *end; /* Ending pos of substring search. */
    int find_size; /* length of given find-string */
    unsigned max_matches; /* number of matches we find before terminating search */
    unsigned count; /* loop counter */
    struct ast_str *str = ast_str_thread_get(&result_buf, 16); /* Holds the data obtained from varname */
    AST_DECLARE_APP_ARGS(args,
       AST_APP_ARG(varname);
       AST_APP_ARG(find_string);
       AST_APP_ARG(replace_string);
       AST_APP_ARG(max_replacements);
       AST_APP_ARG(other);  /* Any remining unused arguments */
    );
    /* Guarantee output string is empty to start with. */
    ast_str_reset(*buf);
    if (!str) {
       /* We failed to allocate str, forget it.  We failed. */
       return -1;
    }
    /* Parse the arguments. */
    AST_STANDARD_APP_ARGS(args, data);
    if (args.argc < 2) {
       /* Didn't receive enough arguments to do anything */
       ast_log(LOG_ERROR,
          "Usage: %s(<varname>,<find-string>[,<replace-string>,[<max-replacements>]])\n",
          cmd);
       return -1;
    }
    /* No var name specified. Return failure, string is already empty. */
    if (ast_strlen_zero(args.varname)) {
       return -1;
    }
    /* Zero length find strings are a no-no. Kill the function if we run into one. */
    if (ast_strlen_zero(args.find_string)) {
       ast_log(LOG_ERROR, "No <find-string> specified\n");
       return -1;
    }
    find_size = strlen(args.find_string);
    /* set varsubstr to the matching variable */
    varsubstr = ast_alloca(strlen(args.varname) + 4);
    sprintf(varsubstr, "${%s}", args.varname);
    ast_str_substitute_variables(&str, 0, chan, varsubstr);
    /* Determine how many replacements are allowed. */
    if (!args.max_replacements
       || (max_matches = atoi(args.max_replacements)) <= 0) {
       /* Unlimited replacements are allowed. */
       max_matches = -1;
    }
    /* Generate the search and replaced string. */
    start = ast_str_buffer(str);
    for (count = 0; count < max_matches; ++count) {
       end = strstr(start, args.find_string);
       if (!end) {
          /* Did not find a matching substring in the remainder. */
          break;
       }
       /* Replace the found substring. */
       *end = '\0';
       ast_str_append(buf, len, "%s", start);
       if (args.replace_string) {
          /* Append the replacement string */
          ast_str_append(buf, len, "%s", args.replace_string);
       }
       start = end + find_size;
    }
    ast_str_append(buf, len, "%s", start);
    return 0;
 }
unload_module()
static int unload_module (void) static
Definition at line 1958 of file func_strings.c.
References app_clearhash, ast_custom_function_unregister(), AST_TEST_UNREGISTER, and ast_unregister_application().
 {
    int res = 0;
    AST_TEST_UNREGISTER(test_FIELDNUM);
    AST_TEST_UNREGISTER(test_REPLACE);
    AST_TEST_UNREGISTER(test_FILTER);
    AST_TEST_UNREGISTER(test_STRREPLACE);
    res |= ast_custom_function_unregister(&fieldqty_function);
    res |= ast_custom_function_unregister(&fieldnum_function);
    res |= ast_custom_function_unregister(&filter_function);
    res |= ast_custom_function_unregister(&replace_function);
    res |= ast_custom_function_unregister(&strreplace_function);
    res |= ast_custom_function_unregister(&listfilter_function);
    res |= ast_custom_function_unregister(&regex_function);
    res |= ast_custom_function_unregister(&array_function);
    res |= ast_custom_function_unregister(&quote_function);
    res |= ast_custom_function_unregister(&csv_quote_function);
    res |= ast_custom_function_unregister(&len_function);
    res |= ast_custom_function_unregister(&strftime_function);
    res |= ast_custom_function_unregister(&strptime_function);
    res |= ast_custom_function_unregister(&eval_function);
    res |= ast_custom_function_unregister(&keypadhash_function);
    res |= ast_custom_function_unregister(&hashkeys_function);
    res |= ast_custom_function_unregister(&hash_function);
    res |= ast_unregister_application(app_clearhash);
    res |= ast_custom_function_unregister(&toupper_function);
    res |= ast_custom_function_unregister(&tolower_function);
    res |= ast_custom_function_unregister(&shift_function);
    res |= ast_custom_function_unregister(&pop_function);
    res |= ast_custom_function_unregister(&push_function);
    res |= ast_custom_function_unregister(&unshift_function);
    res |= ast_custom_function_unregister(&passthru_function);
    return res;
 }
unshift_push()
static int unshift_push (struct ast_channel * chan, const char * cmd, char * data, const char * new_value) static
Definition at line 1628 of file func_strings.c.
References args, ast_alloca, AST_APP_ARG, AST_DECLARE_APP_ARGS, ast_get_encoded_char(), ast_log, AST_STANDARD_APP_ARGS, ast_str_buffer(), ast_str_set(), ast_str_strlen(), ast_str_substitute_variables(), ast_str_thread_get(), ast_strlen_zero, beginning, buf, LOG_WARNING, MIN, pbx_builtin_setvar_helper(), result_buf, tmp_buf, and var.
 {
 #define beginning (cmd[0] == 'U') /* UNSHIFT */
    char delimiter[2] = ",", *varsubst;
    size_t unused;
    struct ast_str *buf, *previous_value;
    AST_DECLARE_APP_ARGS(args,
       AST_APP_ARG(var);
       AST_APP_ARG(delimiter);
    );
    const char *stripped_var;
    if (!(buf = ast_str_thread_get(&result_buf, 16)) ||
       !(previous_value = ast_str_thread_get(&tmp_buf, 16))) {
       return -1;
    }
    AST_STANDARD_APP_ARGS(args, data);
    if (ast_strlen_zero(args.var)) {
       ast_log(LOG_WARNING, "%s requires a variable name\n", cmd);
       return -1;
    }
    if (args.argc > 1 && !ast_strlen_zero(args.delimiter)) {
       ast_get_encoded_char(args.delimiter, delimiter, &unused);
    }
    /* UNSHIFT and PUSH act as ways of setting a variable, so we need to be
     * sure to skip leading underscores if they appear. However, we only want
     * to skip up to two since that is the maximum number that can be used to
     * indicate variable inheritance. Any further underscores are part of the
     * variable name.
     */
    stripped_var = args.var + MIN(strspn(args.var, "_"), 2);
    varsubst = ast_alloca(strlen(stripped_var) + 4);
    sprintf(varsubst, "${%s}", stripped_var);
    ast_str_substitute_variables(&previous_value, 0, chan, varsubst);
    if (!ast_str_strlen(previous_value)) {
       ast_str_set(&buf, 0, "%s", new_value);
    } else {
       ast_str_set(&buf, 0, "%s%c%s",
          beginning ? new_value : ast_str_buffer(previous_value),
          delimiter[0],
          beginning ? ast_str_buffer(previous_value) : new_value);
    }
    pbx_builtin_setvar_helper(chan, args.var, ast_str_buffer(buf));
    return 0;
 #undef beginning
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "String handling dialplan functions" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, } static
Definition at line 2032 of file func_strings.c.
app_clearhash
char* app_clearhash = "ClearHash" static
Definition at line 993 of file func_strings.c.
Referenced by load_module(), and unload_module().
array_function
struct ast_custom_function array_function static
Initial value:
= {
   .name = "ARRAY",
   .write = array,
}
Definition at line 1265 of file func_strings.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 2032 of file func_strings.c.
csv_quote_function
struct ast_custom_function csv_quote_function static
Initial value:
= {
   .name = "CSV_QUOTE",
   .read = csv_quote,
}
Definition at line 1339 of file func_strings.c.
eval_function
struct ast_custom_function eval_function static
Initial value:
= {
   .name = "EVAL",
   .read = function_eval,
   .read2 = function_eval2,
}
Definition at line 1464 of file func_strings.c.
fieldnum_function
struct ast_custom_function fieldnum_function static
Initial value:
= {
   .name = "FIELDNUM",
   .read = function_fieldnum,
   .read2 = function_fieldnum_str,
}
Definition at line 576 of file func_strings.c.
fieldqty_function
struct ast_custom_function fieldqty_function static
Initial value:
= {
   .name = "FIELDQTY",
   .read = function_fieldqty,
   .read2 = function_fieldqty_str,
}
Definition at line 497 of file func_strings.c.
filter_function
struct ast_custom_function filter_function static
Initial value:
= {
   .name = "FILTER",
   .read = filter,
}
Definition at line 785 of file func_strings.c.
hash_function
struct ast_custom_function hash_function static
Initial value:
= {
   .name = "HASH",
   .write = hash_write,
   .read = hash_read,
}
Definition at line 1253 of file func_strings.c.
hashkeys_function
struct ast_custom_function hashkeys_function static
Initial value:
= {
   .name = "HASHKEYS",
   .read = hashkeys_read,
   .read2 = hashkeys_read2,
}
Definition at line 1259 of file func_strings.c.
keypadhash_function
struct ast_custom_function keypadhash_function static
Initial value:
= {
   .name = "KEYPADHASH",
   .read = keypadhash,
}
Definition at line 1505 of file func_strings.c.
len_function
struct ast_custom_function len_function static
Initial value:
= {
   .name = "LEN",
   .read = len,
   .read_max = 12,
}
Definition at line 1356 of file func_strings.c.
listfilter_function
struct ast_custom_function listfilter_function static
Initial value:
= {
   .name = "LISTFILTER",
   .read = listfilter_read,
   .read2 = listfilter_read2,
}
Definition at line 703 of file func_strings.c.
passthru_function
struct ast_custom_function passthru_function static
Initial value:
= {
   .name = "PASSTHRU",
   .read2 = passthru,
}
Definition at line 1698 of file func_strings.c.
pop_function
struct ast_custom_function pop_function static
Initial value:
= {
   .name = "POP",
   .read2 = shift_pop,
}
Definition at line 1623 of file func_strings.c.
push_function
struct ast_custom_function push_function static
Initial value:
= {
   .name = "PUSH",
   .write = unshift_push,
}
Definition at line 1682 of file func_strings.c.
quote_function
struct ast_custom_function quote_function static
Initial value:
= {
   .name = "QUOTE",
   .read = quote,
}
Definition at line 1304 of file func_strings.c.
regex_function
struct ast_custom_function regex_function static
Initial value:
= {
   .name = "REGEX",
   .read = regex,
}
Definition at line 985 of file func_strings.c.
replace_function
struct ast_custom_function replace_function static
Initial value:
= {
   .name = "REPLACE",
   .read2 = replace,
}
Definition at line 854 of file func_strings.c.
result_buf
struct ast_threadstorage result_buf = { .once = PTHREAD_ONCE_INIT , .key_init = __init_result_buf , .custom_init = NULL , } static
Definition at line 45 of file func_strings.c.
Referenced by function_fieldnum_helper(), function_fieldqty_helper(), listfilter(), shift_pop(), strreplace(), and unshift_push().
shift_function
struct ast_custom_function shift_function static
Initial value:
= {
   .name = "SHIFT",
   .read2 = shift_pop,
}
Definition at line 1618 of file func_strings.c.
strftime_function
struct ast_custom_function strftime_function static
Initial value:
= {
   .name = "STRFTIME",
   .read = acf_strftime,
}
Definition at line 1391 of file func_strings.c.
strptime_function
struct ast_custom_function strptime_function static
Initial value:
= {
   .name = "STRPTIME",
   .read = acf_strptime,
}
Definition at line 1433 of file func_strings.c.
strreplace_function
struct ast_custom_function strreplace_function static
Initial value:
= {
   .name = "STRREPLACE",
   .read2 = strreplace,
}
Definition at line 943 of file func_strings.c.
tmp_buf
struct ast_threadstorage tmp_buf = { .once = PTHREAD_ONCE_INIT , .key_init = __init_tmp_buf , .custom_init = NULL , } static
Definition at line 46 of file func_strings.c.
Referenced by listfilter(), and unshift_push().
tolower_function
struct ast_custom_function tolower_function static
Initial value:
= {
   .name = "TOLOWER",
   .read = string_tolower,
   .read2 = string_tolower2,
}
Definition at line 1562 of file func_strings.c.
toupper_function
struct ast_custom_function toupper_function static
Initial value:
= {
   .name = "TOUPPER",
   .read = string_toupper,
   .read2 = string_toupper2,
}
Definition at line 1533 of file func_strings.c.
unshift_function
struct ast_custom_function unshift_function static
Initial value:
= {
   .name = "UNSHIFT",
   .write = unshift_push,
}
Definition at line 1687 of file func_strings.c.