Asterisk - The Open Source Telephony Project: manager_endpoints.c File Reference
manager_endpoints.c File Reference
The Asterisk Management Interface - AMI (endpoint handling)
#include "asterisk.h"
#include "asterisk/callerid.h"
#include "asterisk/channel.h"
#include "asterisk/manager.h"
#include "asterisk/stasis_message_router.h"
#include "asterisk/pbx.h"
#include "asterisk/stasis_endpoints.h"
Functions
static void endpoint_state_cb (void *data, struct stasis_subscription *sub, struct stasis_message *message)
int manager_endpoints_init (void)
Initialize support for AMI endpoint events.
static void manager_endpoints_shutdown (void)
Variables
static struct stasis_message_router * endpoint_router
Detailed Description
The Asterisk Management Interface - AMI (endpoint handling)
Author
Joshua Colp jcolp.nosp@m.@dig.nosp@m.ium.c.nosp@m.om
David M. Lee, II dlee@.nosp@m.digi.nosp@m.um.co.nosp@m.m
Definition in file manager_endpoints.c.
Function Documentation
endpoint_state_cb()
static void endpoint_state_cb (void * data, struct stasis_subscription * sub, struct stasis_message * message) static
Definition at line 46 of file manager_endpoints.c.
References ast_manager_get_topic(), and stasis_publish().
Referenced by manager_endpoints_init().
 {
    stasis_publish(ast_manager_get_topic(), message);
 }
manager_endpoints_init()
int manager_endpoints_init (void)
Initialize support for AMI endpoint events.
Returns
0 on success.
non-zero on error.
Since
12
Definition at line 52 of file manager_endpoints.c.
References ast_endpoint_contact_state_type(), ast_endpoint_state_type(), ast_endpoint_topic_all_cached(), ast_register_cleanup(), endpoint_state_cb(), manager_endpoints_shutdown(), NULL, stasis_message_router_add(), and stasis_message_router_create.
Referenced by subscribe_all().
 {
    struct stasis_topic *endpoint_topic;
    int ret = 0;
    if (endpoint_router) {
       /* Already initialized */
       return 0;
    }
    ast_register_cleanup(manager_endpoints_shutdown);
    endpoint_topic = ast_endpoint_topic_all_cached();
    if (!endpoint_topic) {
       return -1;
    }
    endpoint_router = stasis_message_router_create(endpoint_topic);
    if (!endpoint_router) {
       return -1;
    }
    ret |= stasis_message_router_add(endpoint_router, ast_endpoint_state_type(), endpoint_state_cb, NULL);
    ret |= stasis_message_router_add(endpoint_router, ast_endpoint_contact_state_type(), endpoint_state_cb, NULL);
    /* If somehow we failed to add any routes, just shut down the whole
     * thing and fail it.
     */
    if (ret) {
       manager_endpoints_shutdown();
       return -1;
    }
    return 0;
 }
manager_endpoints_shutdown()
static void manager_endpoints_shutdown (void) static
Definition at line 40 of file manager_endpoints.c.
References NULL, and stasis_message_router_unsubscribe_and_join().
Referenced by manager_endpoints_init().
 {
    stasis_message_router_unsubscribe_and_join(endpoint_router);
    endpoint_router = NULL;
 }
Variable Documentation
endpoint_router
struct stasis_message_router* endpoint_router static
Definition at line 38 of file manager_endpoints.c.