Asterisk - The Open Source Telephony Project: MultiOrderedDict Class Reference
MultiOrderedDict Class Reference
Public Member Functions
def __init__ (self, args, kwds)
def __setitem__ (self, key, val, i=None)
def copy (self)
def insert (self, i, key, val)
Public Member Functions inherited from OrderedDict
def __delitem__ (self, key, dict_delitem=dict.__delitem__)
def __eq__ (self, other)
def __init__ (self, args, kwds)
def __iter__ (self)
def __ne__ (self, other)
def __reduce__ (self)
def __repr__ (self, _repr_running={})
def __reversed__ (self)
def __setitem__ (self, key, value, dict_setitem=dict.__setitem__)
def clear (self)
def copy (self)
def fromkeys (cls, iterable, value=None)
def items (self)
def iteritems (self)
def iterkeys (self)
def itervalues (self)
def keys (self)
def pop (self, key, default=__marker)
def popitem (self, last=True)
def setdefault (self, key, default=None)
def update (args, kwds)
def values (self)
def viewitems (self)
def viewkeys (self)
def viewvalues (self)
Detailed Description
Definition at line 266 of file astdicts.py.
Constructor & Destructor Documentation
__init__()
def __init__ (self, args, kwds)
Definition at line 267 of file astdicts.py.
     def __init__(self, *args, **kwds):
         OrderedDict.__init__(self, *args, **kwds)
Member Function Documentation
__setitem__()
def __setitem__ (self, key, val, i = None)
Definition at line 270 of file astdicts.py.
References len().
     def __setitem__(self, key, val, i=None):
         if key not in self:
 #            print("__setitem__ key = " + key + " val = " + val)
             OrderedDict.__setitem__(
                 self, key, val if isinstance(val, list) else [val])
             return
 #        print("inserting key = " + key + " val = " + val)
         vals = self[key]
         if i is None:
             i = len(vals)
         if not isinstance(val, list):
             if val not in vals:
                 vals.insert(i, val)
         else:
             for j in val.reverse():
                 if j not in vals:
                     vals.insert(i, j)
copy()
def copy (self)
Definition at line 293 of file astdicts.py.
References OrderedDict.iteritems().
     def copy(self):
         # TODO - find out why for some reason copies
         #        the [] as an [[]], so do manually
         c = MultiOrderedDict() #self.__class__(self)
         for key, val in self.iteritems():
             for v in val:
                 c[key] = v
         return c
insert()
def insert (self, i, key, val)
Definition at line 290 of file astdicts.py.
References OrderedDict.__setitem__().
Referenced by Section.add_defaults(), and Section.add_templates().
     def insert(self, i, key, val):
         self.__setitem__(key, val, i)
The documentation for this class was generated from the following file:
astdicts.py