Asterisk - The Open Source Telephony Project: format_gsm.c File Reference
format_gsm.c File Reference
Module: Media File Formats
Save to raw, headerless GSM data.
#include "asterisk.h"
#include "asterisk/mod_format.h"
#include "asterisk/module.h"
#include "asterisk/endian.h"
#include "asterisk/format_cache.h"
#include "msgsm.h"
Macros
#define GSM_FRAME_SIZE 33
#define GSM_SAMPLES 160
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static struct ast_frame * gsm_read (struct ast_filestream *s, int *whennext)
static int gsm_seek (struct ast_filestream *fs, off_t sample_offset, int whence)
static off_t gsm_tell (struct ast_filestream *fs)
static int gsm_trunc (struct ast_filestream *fs)
static int gsm_write (struct ast_filestream *fs, struct ast_frame *f)
static int load_module (void)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Raw GSM data" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_APP_DEPEND }
static const struct ast_module_info * ast_module_info = &__mod_info
static struct ast_format_def gsm_f
static const char gsm_silence []
Detailed Description
Save to raw, headerless GSM data.
File name extension: gsm
Definition in file format_gsm.c.
Macro Definition Documentation
GSM_FRAME_SIZE
#define GSM_FRAME_SIZE 33
Definition at line 43 of file format_gsm.c.
Referenced by gsm_read(), gsm_seek(), gsm_tell(), and gsm_write().
GSM_SAMPLES
#define GSM_SAMPLES 160
Definition at line 44 of file format_gsm.c.
Referenced by gsm_read(), gsm_seek(), and gsm_tell().
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 203 of file format_gsm.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 203 of file format_gsm.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 203 of file format_gsm.c.
gsm_read()
static struct ast_frame* gsm_read (struct ast_filestream * s, int * whennext) static
Definition at line 54 of file format_gsm.c.
References ast_format_get_name(), AST_FRAME_SET_BUFFER, AST_FRIENDLY_OFFSET, ast_log, ast_filestream::buf, ast_frame::data, errno, ast_filestream::f, ast_frame_subclass::format, ast_filestream::fr, GSM_FRAME_SIZE, GSM_SAMPLES, LOG_WARNING, NULL, ast_frame::ptr, ast_frame::samples, and ast_frame::subclass.
 {
    size_t res;
    AST_FRAME_SET_BUFFER(&(s->fr), s->buf, AST_FRIENDLY_OFFSET, GSM_FRAME_SIZE);
    if ((res = fread(s->fr.data.ptr, 1, GSM_FRAME_SIZE, s->f)) != GSM_FRAME_SIZE) {
       if (res) {
          ast_log(LOG_WARNING, "Short read of %s data (expected %d bytes, read %zu): %s\n",
                ast_format_get_name(s->fr.subclass.format), GSM_FRAME_SIZE, res,
                strerror(errno));
       }
       return NULL;
    }
    *whennext = s->fr.samples = GSM_SAMPLES;
    return &s->fr;
 }
gsm_seek()
static int gsm_seek (struct ast_filestream * fs, off_t sample_offset, int whence) static
Definition at line 100 of file format_gsm.c.
References ast_log, AST_LOG_WARNING, errno, ast_filestream::f, GSM_FRAME_SIZE, GSM_SAMPLES, gsm_silence, LOG_WARNING, max, min, ast_frame::offset, and SEEK_FORCECUR.
 {
    off_t offset = 0, min = 0, cur, max, distance;
    if ((cur = ftello(fs->f)) < 0) {
       ast_log(AST_LOG_WARNING, "Unable to determine current position in g719 filestream %p: %s\n", fs, strerror(errno));
       return -1;
    }
    if (fseeko(fs->f, 0, SEEK_END) < 0) {
       ast_log(AST_LOG_WARNING, "Unable to seek to end of g719 filestream %p: %s\n", fs, strerror(errno));
       return -1;
    }
    if ((max = ftello(fs->f)) < 0) {
       ast_log(AST_LOG_WARNING, "Unable to determine max position in g719 filestream %p: %s\n", fs, strerror(errno));
       return -1;
    }
    /* have to fudge to frame here, so not fully to sample */
    distance = (sample_offset / GSM_SAMPLES) * GSM_FRAME_SIZE;
    if (whence == SEEK_SET) {
       offset = distance;
    } else if (whence == SEEK_CUR || whence == SEEK_FORCECUR) {
       offset = distance + cur;
    } else if (whence == SEEK_END) {
       offset = max - distance;
    }
    /* Always protect against seeking past the begining. */
    offset = (offset < min)?min:offset;
    if (whence != SEEK_FORCECUR) {
       offset = (offset > max)?max:offset;
    } else if (offset > max) {
       int i;
       fseeko(fs->f, 0, SEEK_END);
       for (i=0; i< (offset - max) / GSM_FRAME_SIZE; i++) {
          if (fwrite(gsm_silence, 1, GSM_FRAME_SIZE, fs->f) != GSM_FRAME_SIZE) {
             ast_log(LOG_WARNING, "fwrite() failed: %s\n", strerror(errno));
          }
       }
    }
    return fseeko(fs->f, offset, SEEK_SET);
 }
gsm_tell()
static off_t gsm_tell (struct ast_filestream * fs) static
Definition at line 162 of file format_gsm.c.
References ast_log, AST_LOG_WARNING, errno, ast_filestream::f, GSM_FRAME_SIZE, GSM_SAMPLES, and ast_frame::offset.
 {
    off_t offset = ftello(fs->f);
    if (offset < 0) {
       ast_log(AST_LOG_WARNING, "Unable to determine offset for gsm filestream %p: %s\n", fs, strerror(errno));
       return 0;
    }
    return (offset / GSM_FRAME_SIZE) * GSM_SAMPLES;
 }
gsm_trunc()
static int gsm_trunc (struct ast_filestream * fs) static
Definition at line 145 of file format_gsm.c.
References ast_log, AST_LOG_WARNING, errno, and ast_filestream::f.
 {
    int fd;
    off_t cur;
    if ((fd = fileno(fs->f)) < 0) {
       ast_log(AST_LOG_WARNING, "Unable to determine file descriptor for gsm filestream %p: %s\n", fs, strerror(errno));
       return -1;
    }
    if ((cur = ftello(fs->f)) < 0) {
       ast_log(AST_LOG_WARNING, "Unable to determine current position in gsm filestream %p: %s\n", fs, strerror(errno));
       return -1;
    }
    /* Truncate file to current length */
    return ftruncate(fd, cur);
 }
gsm_write()
static int gsm_write (struct ast_filestream * fs, struct ast_frame * f) static
Definition at line 71 of file format_gsm.c.
References ast_log, conv65(), ast_frame::data, ast_frame::datalen, errno, ast_filestream::f, GSM_FRAME_SIZE, len(), LOG_WARNING, and ast_frame::ptr.
 {
    int res;
    unsigned char gsm[2*GSM_FRAME_SIZE];
    if (!(f->datalen % 65)) {
       /* This is in MSGSM format, need to be converted */
       int len=0;
       while(len < f->datalen) {
          conv65(f->data.ptr + len, gsm);
          if ((res = fwrite(gsm, 1, 2*GSM_FRAME_SIZE, fs->f)) != 2*GSM_FRAME_SIZE) {
             ast_log(LOG_WARNING, "Bad write (%d/66): %s\n", res, strerror(errno));
             return -1;
          }
          len += 65;
       }
    } else {
       if (f->datalen % GSM_FRAME_SIZE) {
          ast_log(LOG_WARNING, "Invalid data length, %d, should be multiple of 33\n", f->datalen);
          return -1;
       }
       if ((res = fwrite(f->data.ptr, 1, f->datalen, fs->f)) != f->datalen) {
             ast_log(LOG_WARNING, "Bad write (%d/33): %s\n", res, strerror(errno));
             return -1;
       }
    }
    return 0;
 }
load_module()
static int load_module (void) static
Definition at line 185 of file format_gsm.c.
References ast_format_def_register, ast_format_gsm, AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, and ast_format_def::format.
Referenced by unload_module().
 {
    gsm_f.format = ast_format_gsm;
    if (ast_format_def_register(&gsm_f))
       return AST_MODULE_LOAD_DECLINE;
    return AST_MODULE_LOAD_SUCCESS;
 }
unload_module()
static int unload_module (void) static
Definition at line 193 of file format_gsm.c.
References ast_format_def_unregister(), AST_MODFLAG_LOAD_ORDER, AST_MODPRI_APP_DEPEND, AST_MODULE_INFO(), AST_MODULE_SUPPORT_CORE, ASTERISK_GPL_KEY, load_module(), and ast_format_def::name.
 {
    return ast_format_def_unregister(gsm_f.name);
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Raw GSM data" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_APP_DEPEND } static
Definition at line 203 of file format_gsm.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 203 of file format_gsm.c.
gsm_f
struct ast_format_def gsm_f static
Definition at line 174 of file format_gsm.c.
gsm_silence
const char gsm_silence[] static
Initial value:
=
{0xD8,0x20,0xA2,0xE1,0x5A,0x50,0x00,0x49,0x24,0x92,0x49,0x24,0x50,0x00,0x49
,0x24,0x92,0x49,0x24,0x50,0x00,0x49,0x24,0x92,0x49,0x24,0x50,0x00,0x49,0x24
,0x92,0x49,0x24}
Definition at line 48 of file format_gsm.c.
Referenced by gsm_seek().