Asterisk - The Open Source Telephony Project: StateConstructW.h File Reference
StateConstructW.h File Reference
Functions
void StateConstructW (int idxForMax, int *idxVec, float *syntDenum, float *out, int len)
Function Documentation
StateConstructW()
void StateConstructW (int idxForMax, int * idxVec, float * syntDenum, float * out, int len)
Definition at line 24 of file StateConstructW.c.
References len(), LPC_FILTERORDER, state_frgqTbl, STATE_LEN, state_sq3Tbl, tmp(), and ZeroPoleFilter().
Referenced by Decode(), and iLBC_encode().
     {
        float maxVal, tmpbuf[LPC_FILTERORDER+2*STATE_LEN], *tmp,
            numerator[LPC_FILTERORDER+1];
        float foutbuf[LPC_FILTERORDER+2*STATE_LEN], *fout;
        int k,tmpi;
        /* decoding of the maximum value */
        maxVal = state_frgqTbl[idxForMax];
        maxVal = (float)pow(10,maxVal)/(float)4.5;
        /* initialization of buffers and coefficients */
        memset(tmpbuf, 0, LPC_FILTERORDER*sizeof(float));
        memset(foutbuf, 0, LPC_FILTERORDER*sizeof(float));
        for (k=0; k<LPC_FILTERORDER; k++) {
            numerator[k]=syntDenum[LPC_FILTERORDER-k];
        }
        numerator[LPC_FILTERORDER]=syntDenum[0];
        tmp = &tmpbuf[LPC_FILTERORDER];
        fout = &foutbuf[LPC_FILTERORDER];
        /* decoding of the sample values */
        for (k=0; k<len; k++) {
            tmpi = len-1-k;
            /* maxVal = 1/scal */
            tmp[k] = maxVal*state_sq3Tbl[idxVec[tmpi]];
        }
        /* circular convolution with all-pass filter */
        memset(tmp+len, 0, len*sizeof(float));
        ZeroPoleFilter(tmp, numerator, syntDenum, 2*len,
            LPC_FILTERORDER, fout);
        for (k=0;k<len;k++) {
            out[k] = fout[len-1-k]+fout[2*len-1-k];
        }
    }