Asterisk - The Open Source Telephony Project: bt_overflow.c File Reference
bt_overflow.c File Reference
#include <sys/param.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "../include/db.h"
#include "btree.h"
Functions
int __ovfl_delete (BTREE *t, void *p)
int __ovfl_get (BTREE *t, void *p, size_t *ssz, void **buf, size_t *bufsz)
int __ovfl_put (BTREE *t, const DBT *dbt, pgno_t *pg)
Function Documentation
__ovfl_delete()
int __ovfl_delete (BTREE * t, void * p)
Definition at line 193 of file bt_overflow.c.
References __bt_free(), _btree::bt_mp, _btree::bt_psize, BTDATAOFF, _page::flags, mpool_get(), mpool_put(), _page::nextpg, NULL, P_INVALID, P_PRESERVE, RET_ERROR, and RET_SUCCESS.
Referenced by __bt_dleaf(), __bt_pdelete(), and __rec_dleaf().
 {
    PAGE *h;
    pgno_t pg;
    size_t plen;
    u_int32_t sz;
    memmove(&pg, p, sizeof(pgno_t));
    memmove(&sz, (char *)p + sizeof(pgno_t), sizeof(u_int32_t));
 #ifdef DEBUG
    if (pg == P_INVALID || sz == 0)
       abort();
 #endif
    if ((h = mpool_get(t->bt_mp, pg, 0)) == NULL)
       return (RET_ERROR);
    /* Don't delete chains used by internal pages. */
    if (h->flags & P_PRESERVE) {
       mpool_put(t->bt_mp, h, 0);
       return (RET_SUCCESS);
    }
    /* Step through the chain, calling the free routine for each page. */
    for (plen = t->bt_psize - BTDATAOFF;; sz -= plen) {
       pg = h->nextpg;
       __bt_free(t, h);
       if (sz <= plen)
          break;
       if ((h = mpool_get(t->bt_mp, pg, 0)) == NULL)
          return (RET_ERROR);
    }
    return (RET_SUCCESS);
 }
__ovfl_get()
int __ovfl_get (BTREE * t, void * p, size_t * ssz, void ** buf, size_t * bufsz)
Definition at line 80 of file bt_overflow.c.
References _btree::bt_mp, _btree::bt_psize, BTDATAOFF, buf, malloc(), MIN, mpool_get(), mpool_put(), _page::nextpg, NULL, P_INVALID, realloc, RET_ERROR, and RET_SUCCESS.
Referenced by __bt_cmp(), __bt_ret(), and __rec_ret().
 {
    PAGE *h;
    pgno_t pg;
    size_t nb, plen;
    u_int32_t sz;
    memmove(&pg, p, sizeof(pgno_t));
    memmove(&sz, (char *)p + sizeof(pgno_t), sizeof(u_int32_t));
    *ssz = sz;
 #ifdef DEBUG
    if (pg == P_INVALID || sz == 0)
       abort();
 #endif
    /* Make the buffer bigger as necessary. */
    if (*bufsz < sz) {
       *buf = (char *)(*buf == NULL ? malloc(sz) : realloc(*buf, sz));
       if (*buf == NULL)
          return (RET_ERROR);
       *bufsz = sz;
    }
    /*
     * Step through the linked list of pages, copying the data on each one
     * into the buffer.  Never copy more than the data's length.
     */
    plen = t->bt_psize - BTDATAOFF;
    for (p = *buf;; p = (char *)p + nb, pg = h->nextpg) {
       if ((h = mpool_get(t->bt_mp, pg, 0)) == NULL)
          return (RET_ERROR);
       nb = MIN(sz, plen);
       memmove(p, (char *)h + BTDATAOFF, nb);
       mpool_put(t->bt_mp, h, 0);
       if ((sz -= nb) == 0)
          break;
    }
    return (RET_SUCCESS);
 }
__ovfl_put()
int __ovfl_put (BTREE * t, const DBT * dbt, pgno_t * pg)
Definition at line 139 of file bt_overflow.c.
References __bt_new(), _btree::bt_mp, _btree::bt_psize, BTDATAOFF, DBT::data, _page::flags, last, _page::lower, MIN, MPOOL_DIRTY, mpool_put(), _page::nextpg, NULL, P_INVALID, P_OVERFLOW, _page::pgno, _page::prevpg, RET_ERROR, RET_SUCCESS, DBT::size, and _page::upper.
Referenced by __bt_put(), and __rec_iput().
 {
    PAGE *h, *last;
    void *p;
    pgno_t npg;
    size_t nb, plen;
    u_int32_t sz;
    /*
     * Allocate pages and copy the key/data record into them.  Store the
     * number of the first page in the chain.
     */
    plen = t->bt_psize - BTDATAOFF;
    for (last = NULL, p = dbt->data, sz = dbt->size;;
        p = (char *)p + plen, last = h) {
       if ((h = __bt_new(t, &npg)) == NULL)
          return (RET_ERROR);
       h->pgno = npg;
       h->nextpg = h->prevpg = P_INVALID;
       h->flags = P_OVERFLOW;
       h->lower = h->upper = 0;
       nb = MIN(sz, plen);
       memmove((char *)h + BTDATAOFF, p, nb);
       if (last) {
          last->nextpg = h->pgno;
          mpool_put(t->bt_mp, last, MPOOL_DIRTY);
       } else
          *pg = h->pgno;
       if ((sz -= nb) == 0) {
          mpool_put(t->bt_mp, h, MPOOL_DIRTY);
          break;
       }
    }
    return (RET_SUCCESS);
 }