Asterisk - The Open Source Telephony Project: mwi.c File Reference
mwi.c File Reference
#include "asterisk.h"
#include "asterisk/app.h"
#include "asterisk/mwi.h"
#include "asterisk/stasis_channels.h"
Data Structures
struct ast_mwi_publisher
struct ast_mwi_subscriber
struct mwi_handler_data
Functions
int ast_delete_mwi_state_full (const char *mailbox, const char *context, struct ast_eid *eid)
Delete MWI state cached by stasis with all parameters.
int ast_mwi_add_observer (struct ast_mwi_observer *observer)
Add an observer to receive MWI state related events.
struct ast_mwi_publisher * ast_mwi_add_publisher (const char *mailbox)
Add an MWI state publisher to the mailbox.
struct ast_mwi_subscriber * ast_mwi_add_subscriber (const char *mailbox)
Add an MWI state subscriber to the mailbox.
struct stasis_message * ast_mwi_blob_create (struct ast_mwi_state *mwi_state, struct stasis_message_type *message_type, struct ast_json *blob)
Creates a ast_mwi_blob message.
struct ast_mwi_state * ast_mwi_create (const char *mailbox, const char *context)
Create a ast_mwi_state object.
int ast_mwi_publish (struct ast_mwi_publisher *pub, int urgent_msgs, int new_msgs, int old_msgs, const char *channel_id, struct ast_eid *eid)
Publish MWI for the given mailbox.
int ast_mwi_publish_by_mailbox (const char *mailbox, const char *context, int urgent_msgs, int new_msgs, int old_msgs, const char *channel_id, struct ast_eid *eid)
Publish MWI for the given mailbox.
void ast_mwi_remove_observer (struct ast_mwi_observer *observer)
Remove an MWI state observer.
struct stasis_cache * ast_mwi_state_cache (void)
Backend cache for ast_mwi_topic_cached().
void ast_mwi_state_callback_all (on_mwi_state handler, void *data)
For each managed mailbox call the given handler.
void ast_mwi_state_callback_subscribed (on_mwi_state handler, void *data)
For each managed mailbox that has a subscriber call the given handler.
struct ast_mwi_subscriber * ast_mwi_subscribe_pool (const char *mailbox, stasis_subscription_cb callback, void *data)
Add an MWI state subscriber, and stasis subscription to the mailbox.
struct ast_mwi_state * ast_mwi_subscriber_data (struct ast_mwi_subscriber *sub)
Retrieves the state data object associated with the MWI subscriber.
struct stasis_subscription * ast_mwi_subscriber_subscription (struct ast_mwi_subscriber *sub)
Retrieve the stasis MWI topic subscription if available.
struct stasis_topic * ast_mwi_subscriber_topic (struct ast_mwi_subscriber *sub)
Retrieves the MWI subscriber's topic.
struct stasis_topic * ast_mwi_topic (const char *uniqueid)
Get the Stasis Message Bus API topic for MWI messages on a unique ID.
struct stasis_topic * ast_mwi_topic_all (void)
Get the Stasis Message Bus API topic for MWI messages.
struct stasis_topic * ast_mwi_topic_cached (void)
Get the Stasis Message Bus API caching topic for MWI messages.
void * ast_mwi_unsubscribe (struct ast_mwi_subscriber *sub)
Unsubscribe from the stasis topic and MWI.
void * ast_mwi_unsubscribe_and_join (struct ast_mwi_subscriber *sub)
Unsubscribe from the stasis topic, block until the final message is received, and then unsubscribe from MWI.
int ast_publish_mwi_state_full (const char *mailbox, const char *context, int new_msgs, int old_msgs, const char *channel_id, struct ast_eid *eid)
Publish a MWI state update via stasis with all parameters.
static int handle_mwi_state (const char *id, struct stasis_message *msg, void *user_data)
static void mwi_blob_dtor (void *obj)
static void mwi_cleanup (void)
static struct ast_mwi_state * mwi_create_state (const char *mailbox, const char *context, int urgent_msgs, int new_msgs, int old_msgs)
int mwi_init (void)
Initialize the mwi core.
static struct ast_mwi_state * mwi_retrieve_then_create_state (const char *mailbox)
static struct stasis_message * mwi_state_create_message (const char *mailbox, const char *context, int urgent_msgs, int new_msgs, int old_msgs, const char *channel_id, struct ast_eid *eid)
static void mwi_state_dtor (void *obj)
static const char * mwi_state_get_id (struct stasis_message *message)
static struct ast_event * mwi_to_event (struct stasis_message *message)
Convert a MWI stasis_message to a ast_event.
STASIS_MESSAGE_TYPE_DEFN (ast_mwi_state_type,.to_event=mwi_to_event,)
STASIS_MESSAGE_TYPE_DEFN (ast_mwi_vm_app_type)
Variables
static struct stasis_cache * mwi_state_cache
static struct stasis_state_manager * mwi_state_manager
static struct stasis_caching_topic * mwi_topic_cached
Function Documentation
ast_delete_mwi_state_full()
int ast_delete_mwi_state_full (const char * mailbox, const char * context, struct ast_eid * eid)
Delete MWI state cached by stasis with all parameters.
Since
12.2.0
Parameters
[in] mailbox The mailbox identifier string.
[in] context The context this mailbox resides in (NULL or "" if only using mailbox)
[in] eid The EID of the server that originally published the message
Return values
0 Success
-1 Failure
Definition at line 399 of file mwi.c.
References ao2_cleanup, ast_eid_default, ast_mwi_state_cache(), ast_mwi_state_type(), mwi_state_create_message(), NULL, RAII_VAR, stasis_cache_clear_create(), stasis_cache_get_by_eid(), stasis_message_data(), stasis_state_remove_publish_by_id(), and ast_mwi_state::uniqueid.
Referenced by free_user_final(), and mwi_handle_unsubscribe2().
 {
    RAII_VAR(struct stasis_message *, msg, NULL, ao2_cleanup);
    struct stasis_message *cached_msg;
    struct stasis_message *clear_msg;
    struct ast_mwi_state *mwi_state;
    msg = mwi_state_create_message(mailbox, context, 0, 0, 0, NULL, eid);
    if (!msg) {
       return -1;
    }
    mwi_state = stasis_message_data(msg);
    /*
     * XXX As far as stasis is concerned, all MWI events are local.
     *
     * For now, it is assumed that there is only one entity
     * maintaining the state of a particular mailbox.
     *
     * If we ever have multiple MWI event entities maintaining
     * the same mailbox that wish to delete their cached entry
     * we will need to do something about the race condition
     * potential between checking the cache and removing the
     * cache entry.
     */
    cached_msg = stasis_cache_get_by_eid(ast_mwi_state_cache(),
       ast_mwi_state_type(), mwi_state->uniqueid, &ast_eid_default);
    if (!cached_msg) {
       /* Nothing to clear from the cache, but still need to remove state */
       stasis_state_remove_publish_by_id(mwi_state_manager, mwi_state->uniqueid, eid, NULL);
       return -1;
    }
    ao2_cleanup(cached_msg);
    clear_msg = stasis_cache_clear_create(msg);
    stasis_state_remove_publish_by_id(mwi_state_manager, mwi_state->uniqueid, eid, clear_msg);
    ao2_cleanup(clear_msg);
    return 0;
 }
ast_mwi_add_observer()
int ast_mwi_add_observer (struct ast_mwi_observer * observer)
Add an observer to receive MWI state related events.
Parameters
observer The observer handling events
Return values
0 if successfully registered, -1 otherwise
Since
13.28.0
16.5.0
Definition at line 296 of file mwi.c.
References stasis_state_add_observer().
Referenced by start_poll_thread(), and subscriptions_create().
 {
    return stasis_state_add_observer(mwi_state_manager,
       (struct stasis_state_observer *)observer);
 }
ast_mwi_add_publisher()
struct ast_mwi_publisher* ast_mwi_add_publisher (const char * mailbox)
Add an MWI state publisher to the mailbox.
Adding a publisher to a mailbox will create a stasis topic for the mailbox if one does not already exist. A publisher can be removed by releasing its reference. Doing so releases its underlying reference to the MWI state.
Parameters
mailbox The mailbox id to publish to
Return values
An MWI publisher object
NULl on error
Since
13.28.0
16.5.0
Definition at line 290 of file mwi.c.
References stasis_state_add_publisher().
Referenced by publishers_create().
 {
    return (struct ast_mwi_publisher *)stasis_state_add_publisher(
       mwi_state_manager, mailbox);
 }
ast_mwi_add_subscriber()
struct ast_mwi_subscriber* ast_mwi_add_subscriber (const char * mailbox)
Add an MWI state subscriber to the mailbox.
Adding a subscriber to a mailbox will create a stasis topic for the mailbox if one does not already exist. It does not however subscribe to the topic itself. This is done separately using a call to stasis_subscribe or stasis_subscribe_pool.
A subscriber can be removed by releasing its reference. Doing so releases its underlying reference to the MWI state. It does not unsubscribe from the topic. Unsubscribing from a topic should be done prior to unsubscribing the state.
Parameters
mailbox The subscription state mailbox id
Return values
An MWI subscriber object
NULL on error
Since
13.28.0
16.5.0
Definition at line 224 of file mwi.c.
References stasis_state_add_subscriber().
 {
    return (struct ast_mwi_subscriber *)stasis_state_add_subscriber(
       mwi_state_manager, mailbox);
 }
ast_mwi_publish()
int ast_mwi_publish (struct ast_mwi_publisher * publisher, int urgent_msgs, int new_msgs, int old_msgs, const char * channel_id, struct ast_eid * eid)
Publish MWI for the given mailbox.
Parameters
publisher The publisher to publish a mailbox update on
urgent_msgs The number of urgent messages in this mailbox
new_msgs The number of new messages in this mailbox
old_msgs The number of old messages in this mailbox
channel_id A unique identifier for a channel associated with this change in mailbox state
eid The EID of the server that originally published the message
Return values
0 on success
-1 on failure
Since
13.28.0
16.5.0
Definition at line 353 of file mwi.c.
References ao2_ref, mwi_state_create_message(), NULL, stasis_state_publish(), and stasis_state_publisher_id().
Referenced by explicit_publish_cb().
 {
    struct stasis_state_publisher *p = (struct stasis_state_publisher *)pub;
    struct stasis_message *msg = mwi_state_create_message(stasis_state_publisher_id(p),
       NULL, urgent_msgs, new_msgs, old_msgs, channel_id, eid);
    if (!msg) {
       return -1;
    }
    stasis_state_publish(p, msg);
    ao2_ref(msg, -1);
    return 0;
 }
ast_mwi_publish_by_mailbox()
int ast_mwi_publish_by_mailbox (const char * mailbox, const char * context, int urgent_msgs, int new_msgs, int old_msgs, const char * channel_id, struct ast_eid * eid)
Publish MWI for the given mailbox.
Parameters
mailbox The mailbox identifier string.
context The context this mailbox resides in (NULL or "" if only using mailbox)
urgent_msgs The number of urgent messages in this mailbox
new_msgs The number of new messages in this mailbox
old_msgs The number of old messages in this mailbox
channel_id A unique identifier for a channel associated with this change in mailbox state
eid The EID of the server that originally published the message
Return values
0 on success
-1 on failure
Since
13.28.0
16.5.0
Definition at line 370 of file mwi.c.
References ao2_ref, mwi_state_create_message(), NULL, stasis_message_data(), stasis_state_publish_by_id(), and ast_mwi_state::uniqueid.
Referenced by ast_publish_mwi_state_full(), and implicit_publish_cb().
 {
    struct ast_mwi_state *mwi_state;
    struct stasis_message *msg = mwi_state_create_message(
       mailbox, context, urgent_msgs, new_msgs, old_msgs, channel_id, eid);
    if (!msg) {
       return -1;
    }
    mwi_state = stasis_message_data(msg);
    stasis_state_publish_by_id(mwi_state_manager, mwi_state->uniqueid, NULL, msg);
    ao2_ref(msg, -1);
    return 0;
 }
ast_mwi_remove_observer()
void ast_mwi_remove_observer (struct ast_mwi_observer * observer)
Remove an MWI state observer.
Parameters
observer The observer being removed
Since
13.28.0
16.5.0
Definition at line 302 of file mwi.c.
References stasis_state_remove_observer().
Referenced by stop_poll_thread(), and subscriptions_destroy().
 {
    stasis_state_remove_observer(mwi_state_manager,
       (struct stasis_state_observer *)observer);
 }
ast_mwi_state_callback_all()
void ast_mwi_state_callback_all (on_mwi_state handler, void * data)
For each managed mailbox call the given handler.
Parameters
handler The mwi state handler to call for each managed mailbox
data User to data to pass on to the handler
Since
13.28.0
16.5.0
Definition at line 333 of file mwi.c.
References handle_mwi_state(), handler(), mwi_handler_data::handler, and stasis_state_callback_all().
Referenced by actual_load_config(), manager_voicemail_refresh(), publish(), and unload_module().
 {
    struct mwi_handler_data d = {
       .handler = handler,
       .data = data
    };
    stasis_state_callback_all(mwi_state_manager, handle_mwi_state, &d);
 }
ast_mwi_state_callback_subscribed()
void ast_mwi_state_callback_subscribed (on_mwi_state handler, void * data)
For each managed mailbox that has a subscriber call the given handler.
Parameters
handler The mwi state handler to call for each managed mailbox
data User to data to pass on to the handler
Since
13.28.0
16.5.0
Definition at line 343 of file mwi.c.
References handle_mwi_state(), handler(), mwi_handler_data::handler, and stasis_state_callback_subscribed().
Referenced by mb_poll_thread().
 {
    struct mwi_handler_data d = {
       .handler = handler,
       .data = data
    };
    stasis_state_callback_subscribed(mwi_state_manager, handle_mwi_state, &d);
 }
ast_mwi_subscribe_pool()
struct ast_mwi_subscriber* ast_mwi_subscribe_pool (const char * mailbox, stasis_subscription_cb callback, void * data)
Add an MWI state subscriber, and stasis subscription to the mailbox.
Adding a subscriber to a mailbox will create a stasis topic for the mailbox if one does not already exist. Once successfully create the underlying stasis topic is then subscribed to as well.
A subscriber can be removed by releasing its reference. Doing so releases its underlying reference to the MWI state. It does not unsubscribe from the topic. Unsubscribing from a topic should be done prior to unsubscribing the state.
Parameters
mailbox The subscription state mailbox id
callback The stasis subscription callback
data A user data object passed to the stasis subscription
Return values
An MWI subscriber object
NULL on error
Since
13.28.0
16.5.0
Definition at line 230 of file mwi.c.
References ast_mwi_state_type(), ast_mwi_subscriber_subscription(), NULL, stasis_state_subscribe_pool(), stasis_subscription_accept_message_type(), STASIS_SUBSCRIPTION_FILTER_SELECTIVE, stasis_subscription_set_filter(), and sub.
Referenced by add_peer_mwi_subs(), build_gateway(), build_peer(), config_line(), mkintf(), mwi_stasis_subscription_alloc(), and subscriptions_create().
 {
    struct stasis_subscription *stasis_sub;
    struct ast_mwi_subscriber *sub = (struct ast_mwi_subscriber *)stasis_state_subscribe_pool(
       mwi_state_manager, mailbox, callback, data);
    if (!sub) {
       return NULL;
    }
    stasis_sub = ast_mwi_subscriber_subscription(sub);
    stasis_subscription_accept_message_type(stasis_sub, ast_mwi_state_type());
    stasis_subscription_set_filter(stasis_sub, STASIS_SUBSCRIPTION_FILTER_SELECTIVE);
    return sub;
 }
ast_mwi_subscriber_data()
struct ast_mwi_state* ast_mwi_subscriber_data (struct ast_mwi_subscriber * sub)
Retrieves the state data object associated with the MWI subscriber.
Note
Returned data's reference count is incremented
Parameters
sub An MWI subscriber
Return values
The state data object
Since
13.28.0
16.5.0
Definition at line 264 of file mwi.c.
References mwi_retrieve_then_create_state(), stasis_state_subscriber_data(), and stasis_state_subscriber_id().
Referenced by get_message_count(), handle_validate(), mwi_handle_subscribe(), and mwi_handle_unsubscribe().
 {
    struct stasis_state_subscriber *s = (struct stasis_state_subscriber *)sub;
    struct ast_mwi_state *mwi_state = stasis_state_subscriber_data(s);
    return mwi_state ?: mwi_retrieve_then_create_state(stasis_state_subscriber_id(s));
 }
ast_mwi_subscriber_subscription()
struct stasis_subscription* ast_mwi_subscriber_subscription (struct ast_mwi_subscriber * sub)
Retrieve the stasis MWI topic subscription if available.
Parameters
sub An MWI subscriber
Return values
The subscriber's stasis subscription
NULL if no subscription available
Since
13.28.0
16.5.0
Definition at line 272 of file mwi.c.
References stasis_state_subscriber_subscription().
Referenced by add_peer_mwi_subs(), ast_mwi_subscribe_pool(), and mwi_stasis_subscription_alloc().
 {
    return stasis_state_subscriber_subscription((struct stasis_state_subscriber *)sub);
 }
ast_mwi_subscriber_topic()
struct stasis_topic* ast_mwi_subscriber_topic (struct ast_mwi_subscriber * sub)
Retrieves the MWI subscriber's topic.
Note
Returned topic's reference count is NOT incremented. However, the topic is guaranteed to live for the lifetime of the subscriber.
Parameters
sub An MWI subscriber
Return values
A stasis topic subscribed to by the subscriber
Since
13.28.0
16.5.0
Definition at line 259 of file mwi.c.
References stasis_state_subscriber_topic().
 {
    return stasis_state_subscriber_topic((struct stasis_state_subscriber *)sub);
 }
ast_mwi_unsubscribe()
void* ast_mwi_unsubscribe (struct ast_mwi_subscriber * sub)
Unsubscribe from the stasis topic and MWI.
Parameters
sub An MWI subscriber
Return values
NULL
Since
13.28.0
16.5.0
Definition at line 249 of file mwi.c.
References stasis_state_unsubscribe().
Referenced by destroy_dahdi_pvt(), destroy_endpoint(), peer_destructor(), and skinny_reload().
 {
    return stasis_state_unsubscribe((struct stasis_state_subscriber *)sub);
 }
ast_mwi_unsubscribe_and_join()
void* ast_mwi_unsubscribe_and_join (struct ast_mwi_subscriber * sub)
Unsubscribe from the stasis topic, block until the final message is received, and then unsubscribe from MWI.
Parameters
sub An MWI subscriber
Return values
NULL
Since
13.28.0
16.5.0
Definition at line 254 of file mwi.c.
References stasis_state_unsubscribe_and_join().
Referenced by destroy_mailbox(), subscriptions_destroy(), unload_module(), and unsubscribe_stasis().
 {
    return stasis_state_unsubscribe_and_join((struct stasis_state_subscriber *)sub);
 }
ast_publish_mwi_state_full()
int ast_publish_mwi_state_full (const char * mailbox, const char * context, int new_msgs, int old_msgs, const char * channel_id, struct ast_eid * eid)
Publish a MWI state update via stasis with all parameters.
Since
12
Parameters
[in] mailbox The mailbox identifier string.
[in] context The context this mailbox resides in (NULL or "" if only using mailbox)
[in] new_msgs The number of new messages in this mailbox
[in] old_msgs The number of old messages in this mailbox
[in] channel_id A unique identifier for a channel associated with this change in mailbox state
[in] eid The EID of the server that originally published the message
Return values
0 Success
-1 Failure
Definition at line 388 of file mwi.c.
References ast_mwi_publish_by_mailbox().
Referenced by asterisk_publication_mailboxstate(), publish_mwi_to_stasis(), and xmpp_pubsub_handle_event().
 {
    return ast_mwi_publish_by_mailbox(mailbox, context, 0, new_msgs, old_msgs, channel_id, eid);
 }
handle_mwi_state()
static int handle_mwi_state (const char * id, struct stasis_message * msg, void * user_data) static
Definition at line 313 of file mwi.c.
References ao2_ref, d, mwi_handler_data::data, mwi_handler_data::handler, mwi_create_state(), NULL, and stasis_message_data().
Referenced by ast_mwi_state_callback_all(), and ast_mwi_state_callback_subscribed().
 {
    struct mwi_handler_data *d = user_data;
    struct ast_mwi_state *mwi_state = stasis_message_data(msg);
    int res;
    if (mwi_state) {
       return d->handler(mwi_state, d->data);
    }
    mwi_state = mwi_create_state(id, NULL, 0, 0, 0);
    if (!mwi_state) {
       return 0;
    }
    res = d->handler(mwi_state, d->data);
    ao2_ref(mwi_state, -1);
    return res;
 }
mwi_blob_dtor()
static void mwi_blob_dtor (void * obj) static
Definition at line 454 of file mwi.c.
References ao2_cleanup, ast_json_unref(), ast_mwi_blob::blob, and ast_mwi_blob::mwi_state.
Referenced by ast_mwi_blob_create().
 {
    struct ast_mwi_blob *mwi_blob = obj;
    ao2_cleanup(mwi_blob->mwi_state);
    ast_json_unref(mwi_blob->blob);
 }
mwi_cleanup()
static void mwi_cleanup (void) static
Definition at line 491 of file mwi.c.
References ao2_cleanup, ast_mwi_state_type(), ast_mwi_vm_app_type(), NULL, stasis_caching_unsubscribe_and_join(), and STASIS_MESSAGE_TYPE_CLEANUP.
Referenced by mwi_init().
 {
    ao2_cleanup(mwi_state_cache);
    mwi_state_cache = NULL;
    mwi_topic_cached = stasis_caching_unsubscribe_and_join(mwi_topic_cached);
    ao2_cleanup(mwi_state_manager);
    mwi_state_manager = NULL;
    STASIS_MESSAGE_TYPE_CLEANUP(ast_mwi_state_type);
    STASIS_MESSAGE_TYPE_CLEANUP(ast_mwi_vm_app_type);
 }
mwi_create_state()
static struct ast_mwi_state* mwi_create_state (const char * mailbox, const char * context, int urgent_msgs, int new_msgs, int old_msgs) static
Definition at line 105 of file mwi.c.
References ao2_alloc, ao2_ref, ast_assert, ast_log, ast_string_field_build, ast_string_field_init, ast_string_field_set, ast_strlen_zero, LOG_ERROR, mwi_state_dtor(), ast_mwi_state::new_msgs, NULL, ast_mwi_state::old_msgs, ast_mwi_state::uniqueid, and ast_mwi_state::urgent_msgs.
Referenced by ast_mwi_create(), handle_mwi_state(), mwi_retrieve_then_create_state(), and mwi_state_create_message().
 {
    struct ast_mwi_state *mwi_state;
    ast_assert(!ast_strlen_zero(mailbox));
    mwi_state = ao2_alloc(sizeof(*mwi_state), mwi_state_dtor);
    if (!mwi_state) {
       ast_log(LOG_ERROR, "Unable to create MWI state for mailbox '%s@%s'\n",
             mailbox, ast_strlen_zero(context) ? "" : context);
       return NULL;
    }
    if (ast_string_field_init(mwi_state, 256)) {
       ast_log(LOG_ERROR, "Unable to initialize MWI state for mailbox '%s@%s'\n",
             mailbox, ast_strlen_zero(context) ? "" : context);
       ao2_ref(mwi_state, -1);
       return NULL;
    }
    if (!ast_strlen_zero(context)) {
       ast_string_field_build(mwi_state, uniqueid, "%s@%s", mailbox, context);
    } else {
       ast_string_field_set(mwi_state, uniqueid, mailbox);
    }
    mwi_state->urgent_msgs = urgent_msgs;
    mwi_state->new_msgs = new_msgs;
    mwi_state->old_msgs = old_msgs;
    return mwi_state;
 }
mwi_retrieve_then_create_state()
static struct ast_mwi_state* mwi_retrieve_then_create_state (const char * mailbox) static
Definition at line 138 of file mwi.c.
References ast_app_inboxcount2(), mwi_create_state(), ast_mwi_state::new_msgs, NULL, ast_mwi_state::old_msgs, and ast_mwi_state::urgent_msgs.
Referenced by ast_mwi_subscriber_data().
 {
    int urgent_msgs;
    int new_msgs;
    int old_msgs;
    ast_app_inboxcount2(mailbox, &urgent_msgs, &new_msgs, &old_msgs);
    return mwi_create_state(mailbox, NULL, urgent_msgs, new_msgs, old_msgs);
 }
mwi_state_create_message()
static struct stasis_message* mwi_state_create_message (const char * mailbox, const char * context, int urgent_msgs, int new_msgs, int old_msgs, const char * channel_id, struct ast_eid * eid) static
Definition at line 169 of file mwi.c.
References ao2_cleanup, ast_channel_snapshot_get_latest(), ast_eid_default, ast_mwi_state_type(), ast_strlen_zero, stasis_message::eid, ast_mwi_state::eid, mwi_create_state(), NULL, ast_mwi_state::snapshot, and stasis_message_create_full().
Referenced by ast_delete_mwi_state_full(), ast_mwi_publish(), and ast_mwi_publish_by_mailbox().
 {
    struct ast_mwi_state *mwi_state;
    struct stasis_message *message;
    if (!ast_mwi_state_type()) {
       return NULL;
    }
    mwi_state = mwi_create_state(mailbox, context, urgent_msgs, new_msgs, old_msgs);
    if (!mwi_state) {
       return NULL;
    }
    if (!ast_strlen_zero(channel_id)) {
       mwi_state->snapshot = ast_channel_snapshot_get_latest(channel_id);
    }
    if (eid) {
       mwi_state->eid = *eid;
    } else {
       mwi_state->eid = ast_eid_default;
    }
    /*
     * XXX As far as stasis is concerned, all MWI events are local.
     *
     * We may in the future want to make MWI aggregate local/remote
     * message counts similar to how device state aggregates state.
     */
    message = stasis_message_create_full(ast_mwi_state_type(), mwi_state, &ast_eid_default);
    ao2_cleanup(mwi_state);
    return message;
 }
mwi_state_dtor()
static void mwi_state_dtor (void * obj) static
Definition at line 77 of file mwi.c.
References ao2_cleanup, ast_string_field_free_memory, NULL, and ast_mwi_state::snapshot.
Referenced by mwi_create_state().
 {
    struct ast_mwi_state *mwi_state = obj;
    ast_string_field_free_memory(mwi_state);
    ao2_cleanup(mwi_state->snapshot);
    mwi_state->snapshot = NULL;
 }
mwi_state_get_id()
static const char* mwi_state_get_id (struct stasis_message * message) static
Definition at line 441 of file mwi.c.
References ast_mwi_state_type(), NULL, stasis_message_data(), stasis_message_type(), stasis_subscription_change_type(), ast_mwi_state::uniqueid, and stasis_subscription_change::uniqueid.
Referenced by mwi_init().
 {
    if (ast_mwi_state_type() == stasis_message_type(message)) {
       struct ast_mwi_state *mwi_state = stasis_message_data(message);
       return mwi_state->uniqueid;
    } else if (stasis_subscription_change_type() == stasis_message_type(message)) {
       struct stasis_subscription_change *change = stasis_message_data(message);
       return change->uniqueid;
    }
    return NULL;
 }
mwi_to_event()
static struct ast_event* mwi_to_event (struct stasis_message * message) static
Convert a MWI stasis_message to a ast_event.
Definition at line 38 of file mwi.c.
References AST_EVENT_IE_CONTEXT, AST_EVENT_IE_EID, AST_EVENT_IE_END, AST_EVENT_IE_MAILBOX, AST_EVENT_IE_NEWMSGS, AST_EVENT_IE_OLDMSGS, AST_EVENT_IE_PLTYPE_RAW, AST_EVENT_IE_PLTYPE_STR, AST_EVENT_IE_PLTYPE_UINT, AST_EVENT_MWI, ast_event_new(), ast_mwi_state_type(), ast_mwi_vm_app_type(), ast_strdupa, ast_strlen_zero, context, ast_mwi_state::eid, mailbox, ast_mwi_state::new_msgs, NULL, ast_mwi_state::old_msgs, stasis_message_data(), STASIS_MESSAGE_TYPE_DEFN(), strsep(), and ast_mwi_state::uniqueid.
 {
    struct ast_event *event;
    struct ast_mwi_state *mwi_state;
    char *mailbox;
    char *context;
    if (!message) {
       return NULL;
    }
    mwi_state = stasis_message_data(message);
    /* Strip off @context */
    context = mailbox = ast_strdupa(mwi_state->uniqueid);
    strsep(&context, "@");
    if (ast_strlen_zero(context)) {
       context = "default";
    }
    event = ast_event_new(AST_EVENT_MWI,
             AST_EVENT_IE_MAILBOX, AST_EVENT_IE_PLTYPE_STR, mailbox,
             AST_EVENT_IE_CONTEXT, AST_EVENT_IE_PLTYPE_STR, context,
             AST_EVENT_IE_NEWMSGS, AST_EVENT_IE_PLTYPE_UINT, mwi_state->new_msgs,
             AST_EVENT_IE_OLDMSGS, AST_EVENT_IE_PLTYPE_UINT, mwi_state->old_msgs,
             AST_EVENT_IE_EID, AST_EVENT_IE_PLTYPE_RAW, &mwi_state->eid, sizeof(mwi_state->eid),
             AST_EVENT_IE_END);
    return event;
 }
STASIS_MESSAGE_TYPE_DEFN() [1/2]
STASIS_MESSAGE_TYPE_DEFN (ast_mwi_state_type , . to_event = mwi_to_event)
Referenced by mwi_to_event().
STASIS_MESSAGE_TYPE_DEFN() [2/2]
STASIS_MESSAGE_TYPE_DEFN (ast_mwi_vm_app_type)
Variable Documentation
mwi_state_cache
struct stasis_cache* mwi_state_cache static
Definition at line 33 of file mwi.c.
Referenced by ast_mwi_state_cache().
mwi_state_manager
struct stasis_state_manager* mwi_state_manager static
Definition at line 32 of file mwi.c.
mwi_topic_cached
struct stasis_caching_topic* mwi_topic_cached static
Definition at line 34 of file mwi.c.