Asterisk - The Open Source Telephony Project: astman.c File Reference
astman.c File Reference
#include "asterisk.h"
#include <newt.h>
#include <stdio.h>
#include <sys/time.h>
#include <netdb.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <sys/socket.h>
#include <sys/select.h>
#include <fcntl.h>
#include <string.h>
#include <errno.h>
#include <unistd.h>
#include <stdlib.h>
#include "asterisk/md5.h"
#include "asterisk/linkedlists.h"
Data Structures
struct ast_chan
struct ast_mansession
struct chans
struct event
struct message
Macros
#define _NEWT_CAST (void *)
#define ARRAY_LEN(a) (sizeof(a) / sizeof(a[0]))
#define ASTMM_LIBC ASTMM_IGNORE
#define DEFAULT_MANAGER_PORT 5038
#define MAX_HEADERS 80
#define MAX_LEN 256
Functions
int ast_add_profile (const char *, uint64_t scale)
support for event profiling
int64_t ast_mark (int, int start1_stop0)
int64_t ast_profile (int, int64_t)
static void del_chan (char *name)
static int event_hangup (struct ast_mansession *s, struct message *m)
static int event_ignore (struct ast_mansession *s, struct message *m)
static int event_newchannel (struct ast_mansession *s, struct message *m)
static int event_newexten (struct ast_mansession *s, struct message *m)
static int event_newstate (struct ast_mansession *s, struct message *m)
static int event_rename (struct ast_mansession *s, struct message *m)
static int event_status (struct ast_mansession *s, struct message *m)
static void fdprintf (int fd, char *fmt,...)
static struct ast_chan * find_chan (char *name)
static char * get_header (struct message *m, char *var)
static int get_input (struct ast_mansession *s, char *output)
static int get_user_input (char *msg, char *buf, int buflen)
static int has_input (struct ast_mansession *s)
static int hide_doing (void)
static int input_check (struct ast_mansession *s, struct message **mout)
int main (int argc, char *argv[])
static int manage_calls (char *host)
static int manager_action (char *action, char *fmt,...)
static int manager_login (char *hostname)
static int process_message (struct ast_mansession *s, struct message *m)
static void rebuild_channels (newtComponent c)
static int show_doing (char *title, char *tmp)
static int show_message (char *title, char *msg)
static void try_hangup (newtComponent c)
static void try_redirect (newtComponent c)
static void try_status (void)
static struct message * wait_for_response (int timeout)
Variables
static struct chans chans = { .first = NULL, .last = NULL, }
static struct event events []
static struct ast_mansession session
static newtComponent showform
Macro Definition Documentation
_NEWT_CAST
#define _NEWT_CAST (void *)
Definition at line 62 of file astman.c.
Referenced by get_user_input(), and manager_login().
ARRAY_LEN
#define ARRAY_LEN (a) (sizeof(a) / sizeof(a[0]))
Definition at line 49 of file astman.c.
Referenced by process_message().
ASTMM_LIBC
#define ASTMM_LIBC ASTMM_IGNORE
Definition at line 29 of file astman.c.
DEFAULT_MANAGER_PORT
#define DEFAULT_MANAGER_PORT 5038
Definition at line 64 of file astman.c.
Referenced by manager_login().
MAX_HEADERS
#define MAX_HEADERS 80
Definition at line 53 of file astman.c.
Referenced by input_check().
MAX_LEN
#define MAX_LEN 256
Definition at line 54 of file astman.c.
Function Documentation
ast_add_profile()
int ast_add_profile (const char * s, uint64_t scale)
support for event profiling
(note, this must be documented a lot more) ast_add_profile allocates a generic 'counter' with a given name, which can be shown with the command 'core show profile <name>'
The counter accumulates positive or negative values supplied by
See also
ast_add_profile(), dividing them by the 'scale' value passed in the create call, and also counts the number of 'events'. Values can also be taked by the TSC counter on ia32 architectures, in which case you can mark the start of an event calling ast_mark(id, 1) and then the end of the event with ast_mark(id, 0). For non-i386 architectures, these two calls return 0.
support for event profiling
Returns
Returns the identifier of the counter.
Definition at line 92 of file astman.c.
References ast_profile().
 {
    return -1;
 }
ast_mark()
int64_t ast_mark (int key, int start1_stop0)
Definition at line 103 of file astman.c.
Referenced by __ast_pthread_mutex_lock(), ao2_weakproxy_unsubscribe(), ast_profile(), and extension_match_core().
 {
    return 0;
 }
ast_profile()
int64_t ast_profile (int key, int64_t val)
Definition at line 98 of file astman.c.
References ast_mark().
Referenced by ast_add_profile().
 {
    return 0;
 }
del_chan()
static void del_chan (char * name) static
Definition at line 126 of file astman.c.
References AST_LIST_REMOVE_CURRENT, AST_LIST_TRAVERSE_SAFE_BEGIN, AST_LIST_TRAVERSE_SAFE_END, free(), ast_chan::list, and ast_chan::name.
Referenced by event_hangup().
 {
    struct ast_chan *chan;
    AST_LIST_TRAVERSE_SAFE_BEGIN(&chans, chan, list) {
       if (!strcmp(name, chan->name)) {
          AST_LIST_REMOVE_CURRENT(list);
          free(chan);
          return;
       }
    }
    AST_LIST_TRAVERSE_SAFE_END;
 }
event_hangup()
static int event_hangup (struct ast_mansession * s, struct message * m) static
Definition at line 204 of file astman.c.
References del_chan(), and get_header().
 {
    del_chan(get_header(m, "Channel"));
    return 0;
 }
event_ignore()
static int event_ignore (struct ast_mansession * s, struct message * m) static
Definition at line 210 of file astman.c.
 {
    return 0;
 }
event_newchannel()
static int event_newchannel (struct ast_mansession * s, struct message * m) static
Definition at line 183 of file astman.c.
References ast_chan::callerid, find_chan(), get_header(), and ast_chan::state.
 {
    struct ast_chan *chan;
    chan = find_chan(get_header(m, "Channel"));
    strncpy(chan->state, get_header(m, "State"), sizeof(chan->state) - 1);
    strncpy(chan->callerid, get_header(m, "Callerid"), sizeof(chan->callerid) - 1);
    return 0;
 }
event_newexten()
static int event_newexten (struct ast_mansession * s, struct message * m) static
Definition at line 173 of file astman.c.
References ast_chan::context, ast_chan::exten, find_chan(), get_header(), and ast_chan::priority.
 {
    struct ast_chan *chan;
    chan = find_chan(get_header(m, "Channel"));
    strncpy(chan->exten, get_header(m, "Extension"), sizeof(chan->exten) - 1);
    strncpy(chan->context, get_header(m, "Context"), sizeof(chan->context) - 1);
    strncpy(chan->priority, get_header(m, "Priority"), sizeof(chan->priority) - 1);
    return 0;
 }
event_newstate()
static int event_newstate (struct ast_mansession * s, struct message * m) static
Definition at line 165 of file astman.c.
References find_chan(), get_header(), and ast_chan::state.
 {
    struct ast_chan *chan;
    chan = find_chan(get_header(m, "Channel"));
    strncpy(chan->state, get_header(m, "State"), sizeof(chan->state) - 1);
    return 0;
 }
event_rename()
static int event_rename (struct ast_mansession * s, struct message * m) static
Definition at line 215 of file astman.c.
References find_chan(), get_header(), and ast_chan::name.
 {
    struct ast_chan *chan;
    chan = find_chan(get_header(m, "Oldname"));
    strncpy(chan->name, get_header(m, "Newname"), sizeof(chan->name) - 1);
    return 0;
 }
event_status()
static int event_status (struct ast_mansession * s, struct message * m) static
Definition at line 192 of file astman.c.
References ast_chan::callerid, ast_chan::context, ast_chan::exten, find_chan(), get_header(), ast_chan::priority, and ast_chan::state.
 {
    struct ast_chan *chan;
    chan = find_chan(get_header(m, "Channel"));
    strncpy(chan->state, get_header(m, "State"), sizeof(chan->state) - 1);
    strncpy(chan->callerid, get_header(m, "Callerid"), sizeof(chan->callerid) - 1);
    strncpy(chan->exten, get_header(m, "Extension"), sizeof(chan->exten) - 1);
    strncpy(chan->context, get_header(m, "Context"), sizeof(chan->context) - 1);
    strncpy(chan->priority, get_header(m, "Priority"), sizeof(chan->priority) - 1);
    return 0;
 }
fdprintf()
static void fdprintf (int fd, char * fmt, ...) static
Definition at line 141 of file astman.c.
References errno.
Referenced by manager_action().
 {
    char stuff[4096];
    va_list ap;
    va_start(ap, fmt);
    vsnprintf(stuff, sizeof(stuff), fmt, ap);
    va_end(ap);
    if (write(fd, stuff, strlen(stuff)) < 0) {
       fprintf(stderr, "write() failed: %s\n", strerror(errno));
    }
 }
find_chan()
static struct ast_chan* find_chan (char * name) static
Definition at line 110 of file astman.c.
References AST_LIST_INSERT_TAIL, AST_LIST_TRAVERSE, ast_chan::list, malloc(), and ast_chan::name.
Referenced by event_newchannel(), event_newexten(), event_newstate(), event_rename(), and event_status().
 {
    struct ast_chan *chan;
    AST_LIST_TRAVERSE(&chans, chan, list) {
       if (!strcmp(name, chan->name))
          return chan;
    }
    chan = malloc(sizeof(struct ast_chan));
    if (chan) {
       memset(chan, 0, sizeof(struct ast_chan));
       strncpy(chan->name, name, sizeof(chan->name) - 1);
       AST_LIST_INSERT_TAIL(&chans, chan, list);
    }
    return chan;
 }
get_header()
static char* get_header (struct message * m, char * var) static
Definition at line 154 of file astman.c.
References message::hdrcount, and message::headers.
Referenced by event_hangup(), event_newchannel(), event_newexten(), event_newstate(), event_rename(), event_status(), input_check(), manager_login(), process_message(), try_hangup(), try_redirect(), and try_status().
 {
    char cmp[80];
    int x;
    snprintf(cmp, sizeof(cmp), "%s: ", var);
    for (x=0;x<m->hdrcount;x++)
       if (!strncasecmp(cmp, m->headers[x], strlen(cmp)))
          return m->headers[x] + strlen(cmp);
    return "";
 }
get_input()
static int get_input (struct ast_mansession * s, char * output) static
Definition at line 310 of file astman.c.
References errno, ast_mansession::fd, FD_SET, FD_ZERO, ast_mansession::inbuf, inet_ntoa, ast_mansession::inlen, NULL, and ast_mansession::sin.
Referenced by input_check().
 {
    /* output must have at least sizeof(s->inbuf) space */
    int res;
    int x;
    struct timeval tv = {0, 0};
    fd_set fds;
    for (x=1;x<s->inlen;x++) {
       if ((s->inbuf[x] == '\n') && (s->inbuf[x-1] == '\r')) {
          /* Copy output data up to and including \r\n */
          memcpy(output, s->inbuf, x + 1);
          /* Add trailing \0 */
          output[x+1] = '\0';
          /* Move remaining data back to the front */
          memmove(s->inbuf, s->inbuf + x + 1, s->inlen - x);
          s->inlen -= (x + 1);
          return 1;
       }
    }
    if (s->inlen >= sizeof(s->inbuf) - 1) {
       fprintf(stderr, "Dumping long line with no return from %s: %s\n", inet_ntoa(s->sin.sin_addr), s->inbuf);
       s->inlen = 0;
    }
    FD_ZERO(&fds);
    FD_SET(s->fd, &fds);
    res = select(s->fd + 1, &fds, NULL, NULL, &tv);
    if (res < 0) {
       fprintf(stderr, "Select returned error: %s\n", strerror(errno));
    } else if (res > 0) {
       res = read(s->fd, s->inbuf + s->inlen, sizeof(s->inbuf) - 1 - s->inlen);
       if (res < 1)
          return -1;
       s->inlen += res;
       s->inbuf[s->inlen] = '\0';
    } else {
       return 2;
    }
    return 0;
 }
get_user_input()
static int get_user_input (char * msg, char * buf, int buflen) static
Definition at line 500 of file astman.c.
References _NEWT_CAST, input(), and NULL.
Referenced by try_redirect().
 {
    newtComponent form;
    newtComponent ok;
    newtComponent cancel;
    newtComponent inpfield;
    const char *input;
    int res = -1;
    struct newtExitStruct es;
    newtCenteredWindow(60,7, msg);
    inpfield = newtEntry(5, 2, "", 50, _NEWT_CAST &input, 0);
    ok = newtButton(22, 3, "OK");
    cancel = newtButton(32, 3, "Cancel");
    form = newtForm(NULL, NULL, 0);
    newtFormAddComponents(form, inpfield, ok, cancel, NULL);
    newtFormRun(form, &es);
    strncpy(buf, input, buflen - 1);
    if (es.u.co == ok)
       res = 0;
    else
       res = -1;
    newtPopWindow();
    newtFormDestroy(form);
    return res;
 }
has_input()
static int has_input (struct ast_mansession * s) static
Definition at line 301 of file astman.c.
References ast_mansession::inbuf, and ast_mansession::inlen.
Referenced by manage_calls().
 {
    int x;
    for (x=1;x<s->inlen;x++)
       if ((s->inbuf[x] == '\n') && (s->inbuf[x-1] == '\r'))
          return 1;
    return 0;
 }
hide_doing()
static int hide_doing (void) static
Definition at line 462 of file astman.c.
Referenced by manage_calls(), and manager_login().
 {
    newtPopWindow();
    newtFormDestroy(showform);
    return 0;
 }
input_check()
static int input_check (struct ast_mansession * s, struct message ** mout) static
Definition at line 350 of file astman.c.
References get_header(), get_input(), message::hdrcount, message::headers, MAX_HEADERS, NULL, and process_message().
Referenced by manage_calls(), and wait_for_response().
 {
    static struct message m;
    int res;
    if (mout)
       *mout = NULL;
    for(;;) {
       res = get_input(s, m.headers[m.hdrcount]);
       if (res == 1) {
 #if 0
          fprintf(stderr, "Got header: %s", m.headers[m.hdrcount]);
          fgetc(stdin);
 #endif
          /* Strip trailing \r\n */
          if (strlen(m.headers[m.hdrcount]) < 2)
             continue;
          m.headers[m.hdrcount][strlen(m.headers[m.hdrcount]) - 2] = '\0';
          if (!strlen(m.headers[m.hdrcount])) {
             if (mout && strlen(get_header(&m, "Response"))) {
                *mout = &m;
                return 0;
             }
             if (process_message(s, &m))
                break;
             memset(&m, 0, sizeof(m));
          } else if (m.hdrcount < MAX_HEADERS - 1)
             m.hdrcount++;
       } else if (res < 0) {
          return -1;
       } else if (res == 2)
          return 0;
    }
    return -1;
 }
main()
int main (int argc, char * argv[])
Definition at line 748 of file astman.c.
References manage_calls(), and manager_login().
 {
    if (argc < 2) {
       fprintf(stderr, "Usage: astman <host>\n");
       exit(1);
    }
    newtInit();
    newtCls();
    newtDrawRootText(0, 0, "Asterisk Manager (C)2002, Linux Support Services, Inc.");
    newtPushHelpLine("Welcome to the Asterisk Manager!");
    if (manager_login(argv[1])) {
       newtFinished();
       exit(1);
    }
    manage_calls(argv[1]);
    newtFinished();
    return 0;
 }
manage_calls()
static int manage_calls (char * host) static
Definition at line 561 of file astman.c.
References channels, ast_mansession::fd, hangup(), has_input(), hide_doing(), input_check(), NULL, rebuild_channels(), session, show_doing(), show_message(), tmp(), try_hangup(), try_redirect(), and try_status().
Referenced by main().
 {
    newtComponent form;
    newtComponent quit;
    newtComponent hangup;
    newtComponent redirect;
    newtComponent channels;
    struct newtExitStruct es;
    char tmp[80];
    /* Mark: If there's one thing you learn from this code, it is this...
       Never, ever fly Air France.  Their customer service is absolutely
       the worst.  I've never heard the words "That's not my problem" as
       many times as I have from their staff -- It should, without doubt
       be their corporate motto if it isn't already.  Don't bother giving
       them business because you're just a pain in their side and they
       will be sure to let you know the first time you speak to them.
       If you ever want to make me happy just tell me that you, too, will
       never fly Air France again either (in spite of their excellent
       cuisine).
       Update by oej: The merger with KLM has transferred this
       behaviour to KLM as well.
       Don't bother giving them business either...
       Only if you want to travel randomly without luggage, you
       might pick either of them.
    */
    snprintf(tmp, sizeof(tmp), "Asterisk Manager at %s", host);
    newtCenteredWindow(74, 20, tmp);
    form = newtForm(NULL, NULL, 0);
    newtFormWatchFd(form, session.fd, NEWT_FD_READ);
    newtFormSetTimer(form, 100);
    quit = newtButton(62, 16, "Quit");
    redirect = newtButton(35, 16, "Redirect");
    hangup = newtButton(50, 16, "Hangup");
    channels = newtListbox(1,1,14, NEWT_FLAG_SCROLL);
    newtFormAddComponents(form, channels, redirect, hangup, quit, NULL);
    newtListboxSetWidth(channels, 72);
    show_doing("Getting Status", "Retrieving system status...");
    try_status();
    hide_doing();
    for(;;) {
       newtFormRun(form, &es);
       if (has_input(&session) || (es.reason == NEWT_EXIT_FDREADY)) {
          if (input_check(&session, NULL)) {
             show_message("Disconnected", "Disconnected from remote host");
             break;
          }
       } else if (es.reason == NEWT_EXIT_COMPONENT) {
          if (es.u.co == quit)
             break;
          if (es.u.co == hangup) {
             try_hangup(channels);
          } else if (es.u.co == redirect) {
             try_redirect(channels);
          }
       }
       rebuild_channels(channels);
    }
    newtFormDestroy(form);
    return 0;
 }
manager_action()
static int manager_action (char * action, char * fmt, ...) static
Definition at line 410 of file astman.c.
References errno, ast_mansession::fd, fdprintf(), session, and tmp().
Referenced by manager_login(), try_hangup(), try_redirect(), and try_status().
 {
    struct ast_mansession *s;
    char tmp[4096];
    va_list ap;
    int res;
    s = &session;
    fdprintf(s->fd, "Action: %s\r\n", action);
    va_start(ap, fmt);
    vsnprintf(tmp, sizeof(tmp), fmt, ap);
    va_end(ap);
    if ((res = write(s->fd, tmp, strlen(tmp))) < 0) {
       fprintf(stderr, "write() failed: %s\n", strerror(errno));
    }
    fdprintf(s->fd, "\r\n");
    return 0;
 }
manager_login()
static int manager_login (char * hostname) static
Definition at line 629 of file astman.c.
References _NEWT_CAST, challenge(), DEFAULT_MANAGER_PORT, errno, ast_mansession::fd, get_header(), gethostbyname, hide_doing(), hp, len(), manager_action(), MD5Final(), MD5Init(), MD5Update(), NULL, pass, password, session, show_doing(), show_message(), ast_mansession::sin, tmp(), user, and wait_for_response().
Referenced by main().
 {
    newtComponent form;
    newtComponent cancel;
    newtComponent login;
    newtComponent username;
    newtComponent password;
    newtComponent label;
    newtComponent ulabel;
    newtComponent plabel;
    const char *user;
    const char *pass;
    struct message *m;
    struct newtExitStruct es;
    char tmp[55];
    struct hostent *hp;
    int res = -1;
    session.fd = socket(AF_INET, SOCK_STREAM, 0);
    if (session.fd < 0) {
       snprintf(tmp, sizeof(tmp), "socket() failed: %s\n", strerror(errno));
       show_message("Socket failed", tmp);
       return -1;
    }
    snprintf(tmp, sizeof(tmp), "Looking up %s\n", hostname);
    show_doing("Connecting....", tmp);
    hp = gethostbyname(hostname);
    if (!hp) {
       snprintf(tmp, sizeof(tmp), "No such address: %s\n", hostname);
       show_message("Host lookup failed", tmp);
       return -1;
    }
    hide_doing();
    snprintf(tmp, sizeof(tmp), "Connecting to %s", hostname);
    show_doing("Connecting...", tmp);
    session.sin.sin_family = AF_INET;
    session.sin.sin_port = htons(DEFAULT_MANAGER_PORT);
    memcpy(&session.sin.sin_addr, hp->h_addr, sizeof(session.sin.sin_addr));
    if (connect(session.fd,(struct sockaddr*)&session.sin, sizeof(session.sin))) {
       snprintf(tmp, sizeof(tmp), "%s failed: %s\n", hostname, strerror(errno));
       show_message("Connect Failed", tmp);
       return -1;
    }
    hide_doing();
    login = newtButton(5, 6, "Login");
    cancel = newtButton(25, 6, "Cancel");
    newtCenteredWindow(40, 10, "Asterisk Manager Login");
    snprintf(tmp, sizeof(tmp), "Host:     %s", hostname);
    label = newtLabel(4,1, tmp);
    ulabel = newtLabel(4,2,"Username:");
    plabel = newtLabel(4,3,"Password:");
    username = newtEntry(14, 2, "", 20, _NEWT_CAST &user, 0);
    password = newtEntry(14, 3, "", 20, _NEWT_CAST &pass, NEWT_FLAG_HIDDEN);
    form = newtForm(NULL, NULL, 0);
    newtFormAddComponents(form, username, password, login, cancel, label, ulabel, plabel,NULL);
    newtFormRun(form, &es);
    if (es.reason == NEWT_EXIT_COMPONENT) {
       if (es.u.co == login) {
          snprintf(tmp, sizeof(tmp), "Logging in '%s'...", user);
          show_doing("Logging in", tmp);
          /* Check to see if the remote host supports MD5 Authentication */
          manager_action("Challenge", "AuthType: MD5\r\n");
          m = wait_for_response(10000);
          if (m && !strcasecmp(get_header(m, "Response"), "Success")) {
             char *challenge = get_header(m, "Challenge");
             int x;
             int len = 0;
             char md5key[256] = "";
             struct MD5Context md5;
             unsigned char digest[16];
             MD5Init(&md5);
             MD5Update(&md5, (unsigned char *)challenge, strlen(challenge));
             MD5Update(&md5, (unsigned char *)pass, strlen(pass));
             MD5Final(digest, &md5);
             for (x=0; x<16; x++)
                len += sprintf(md5key + len, "%02hhx", digest[x]);
             manager_action("Login",
                   "AuthType: MD5\r\n"
                   "Username: %s\r\n"
                   "Key: %s\r\n",
                   user, md5key);
             m = wait_for_response(10000);
             hide_doing();
             if (!strcasecmp(get_header(m, "Response"), "Success")) {
                res = 0;
             } else {
                show_message("Login Failed", get_header(m, "Message"));
             }
          } else {
             manager_action("Login",
                "Username: %s\r\n"
                "Secret: %s\r\n",
                   user, pass);
             m = wait_for_response(10000);
             hide_doing();
             if (m) {
                if (!strcasecmp(get_header(m, "Response"), "Success")) {
                   res = 0;
                } else {
                   show_message("Login Failed", get_header(m, "Message"));
                }
             }
          }
       }
    }
    newtFormDestroy(form);
    return res;
 }
process_message()
static int process_message (struct ast_mansession * s, struct message * m) static
Definition at line 249 of file astman.c.
References ARRAY_LEN, events, get_header(), message::hdrcount, and message::headers.
Referenced by input_check().
 {
    int x;
    char event[80] = "";
    strncpy(event, get_header(m, "Event"), sizeof(event) - 1);
    if (!strlen(event)) {
       fprintf(stderr, "Missing event in request");
       return 0;
    }
    for (x = 0; x < ARRAY_LEN(events); x++) {
       if (!strcasecmp(event, events[x].event)) {
          if (events[x].func(s, m))
             return -1;
          break;
       }
    }
    if (x >= ARRAY_LEN(events))
       fprintf(stderr, "Ignoring unknown event '%s'", event);
 #if 0
    for (x=0;x<m->hdrcount;x++) {
       printf("Header: %s\n", m->headers[x]);
    }
 #endif
    return 0;
 }
rebuild_channels()
static void rebuild_channels (newtComponent c) static
Definition at line 275 of file astman.c.
References AST_LIST_TRAVERSE, ast_chan::callerid, ast_chan::context, ast_chan::exten, ast_chan::list, ast_chan::name, NULL, ast_chan::priority, ast_chan::state, and tmp().
Referenced by manage_calls().
 {
    void *prev = NULL;
    struct ast_chan *chan;
    char tmpn[sizeof(chan->name) + sizeof(chan->callerid) + 3 - 1];
    char tmp[256];
    int x=0;
    prev = newtListboxGetCurrent(c);
    newtListboxClear(c);
    AST_LIST_TRAVERSE(&chans, chan, list) {
       snprintf(tmpn, sizeof(tmpn), "%s (%s)", chan->name, chan->callerid);
       if (strlen(chan->exten))
          snprintf(tmp, sizeof(tmp), "%-30s %8s -> %s@%s:%s",
             tmpn, chan->state,
             chan->exten, chan->context, chan->priority);
       else
          snprintf(tmp, sizeof(tmp), "%-30s %8s",
             tmpn, chan->state);
       newtListboxAppendEntry(c, tmp, chan);
       x++;
    }
    if (!x)
       newtListboxAppendEntry(c, " << No Active Channels >> ", NULL);
    newtListboxSetCurrentByKey(c, prev);
 }
show_doing()
static int show_doing (char * title, char * tmp) static
Definition at line 449 of file astman.c.
References NULL.
Referenced by manage_calls(), and manager_login().
 {
    struct newtExitStruct es;
    newtComponent label;
    showform = newtForm(NULL, NULL, 0);
    newtCenteredWindow(70,4, title);
    label = newtLabel(3,1,tmp);
    newtFormAddComponents(showform,label, NULL);
    newtFormSetTimer(showform, 200);
    newtFormRun(showform, &es);
    return 0;
 }
show_message()
static int show_message (char * title, char * msg) static
Definition at line 429 of file astman.c.
References NULL.
Referenced by manage_calls(), manager_login(), try_hangup(), try_redirect(), and try_status().
 {
    newtComponent form;
    newtComponent label;
    newtComponent ok;
    struct newtExitStruct es;
    newtCenteredWindow(60,7, title);
    label = newtLabel(4,1,msg);
    ok = newtButton(27, 3, "OK");
    form = newtForm(NULL, NULL, 0);
    newtFormAddComponents(form, label, ok, NULL);
    newtFormRun(form, &es);
    newtPopWindow();
    newtFormDestroy(form);
    return 0;
 }
try_hangup()
static void try_hangup (newtComponent c) static
Definition at line 482 of file astman.c.
References get_header(), manager_action(), ast_chan::name, show_message(), and wait_for_response().
Referenced by manage_calls().
 {
    struct ast_chan *chan;
    struct message *m;
    chan = newtListboxGetCurrent(c);
    if (chan) {
       manager_action("Hangup", "Channel: %s\r\n", chan->name);
       m = wait_for_response(10000);
       if (!m) {
          show_message("Hangup Failed", "Timeout waiting for response");
       } else if (strcasecmp(get_header(m, "Response"), "Success"))  {
          show_message("Hangup Failed", get_header(m, "Message"));
       }
    }
 }
try_redirect()
static void try_redirect (newtComponent c) static
Definition at line 528 of file astman.c.
References context, get_header(), get_user_input(), manager_action(), ast_chan::name, show_message(), tmp(), and wait_for_response().
Referenced by manage_calls().
 {
    struct ast_chan *chan;
    char dest[256];
    struct message *m;
    static const char tmp_prefix[] = "Enter new extension for ";
    char channame[256];
    char tmp[sizeof(tmp_prefix) + sizeof(channame)];
    char *context;
    chan = newtListboxGetCurrent(c);
    if (chan) {
       snprintf(channame, sizeof(channame), "%s", chan->name);
       snprintf(tmp, sizeof(tmp), "%s%s", tmp_prefix, channame);
       if (get_user_input(tmp, dest, sizeof(dest)))
          return;
       if ((context = strchr(dest, '@'))) {
          *context = '\0';
          context++;
          manager_action("Redirect", "Channel: %s\r\nContext: %s\r\nExten: %s\r\nPriority: 1\r\n", chan->name,context,dest);
       } else {
          manager_action("Redirect", "Channel: %s\r\nExten: %s\r\nPriority: 1\r\n", chan->name, dest);
       }
       m = wait_for_response(10000);
       if (!m) {
          show_message("Hangup Failed", "Timeout waiting for response");
       } else if (strcasecmp(get_header(m, "Response"), "Success"))  {
          show_message("Hangup Failed", get_header(m, "Message"));
       }
    }
 }
try_status()
static void try_status (void) static
Definition at line 469 of file astman.c.
References get_header(), manager_action(), show_message(), and wait_for_response().
Referenced by manage_calls().
 {
    struct message *m;
    manager_action("Status", "%s", "");
    m = wait_for_response(10000);
    if (!m) {
       show_message("Status Failed", "Timeout waiting for response");
    } else if (strcasecmp(get_header(m, "Response"), "Success"))  {
       show_message("Status Failed Failed", get_header(m, "Message"));
    }
 }
wait_for_response()
static struct message* wait_for_response (int timeout) static
Definition at line 387 of file astman.c.
References ast_mansession::fd, FD_SET, input_check(), NULL, and session.
Referenced by manager_login(), try_hangup(), try_redirect(), and try_status().
 {
    struct message *m;
    struct timeval tv;
    int res;
    fd_set fds;
    for (;;) {
       tv.tv_sec = timeout / 1000;
       tv.tv_usec = (timeout % 1000) * 1000;
       FD_SET(session.fd, &fds);
       res = select(session.fd + 1, &fds, NULL, NULL, &tv);
       if (res < 1)
          break;
       if (input_check(&session, &m) < 0) {
          return NULL;
       }
       if (m)
          return m;
    }
    return NULL;
 }
Variable Documentation
chans
struct chans chans = { .first = NULL, .last = NULL, } static
Referenced by check_header(), check_header_fmt(), and setup_dahdi_int().
events
struct event events[] static
Referenced by process_message().
session
struct ast_mansession session static
Referenced by __manager_event_sessions_va(), add_header(), assign_uuid(), ast_ari_events_event_websocket_ws_established_cb(), ast_ari_websocket_events_event_websocket_established(), ast_ari_websocket_session_create(), ast_sip_channel_pvt_alloc(), ast_sip_dialog_get_session(), ast_sip_session_alloc(), ast_sip_session_create_outgoing(), ast_websocket_uri_cb(), astman_is_authed(), astman_verify_session_readpermissions(), astman_verify_session_writepermissions(), auth_http_callback(), channel_read_rtcp(), channel_read_rtp(), check_manager_session_inuse(), cli_channelstats_print_body(), defer_termination_cancel_task(), destroy_session(), event_session_alloc(), event_session_dtor(), event_session_hash(), find_session(), find_session_by_nonce(), generic_http_callback(), get_manager_sessions_cb(), handle_new_invite_request(), handle_showmanconn(), invite_collision_timeout(), invite_proceeding(), invite_terminated(), jingle_action_hook(), jingle_alloc(), jingle_answer(), jingle_call(), jingle_digit_begin(), jingle_digit_end(), jingle_fixup(), jingle_get_rtp_peer(), jingle_hangup(), jingle_indicate(), jingle_outgoing_hook(), jingle_read(), jingle_request(), jingle_sendtext(), jingle_session_destructor(), jingle_session_hash(), jingle_write(), manage_calls(), manager_action(), manager_fax_session(), manager_fax_sessions(), manager_login(), notify_ami_channel_data_create(), outbound_invite_auth(), pjsip_logger_session_alloc(), pjsip_logger_session_destroy(), purge_sessions(), push_notify_channel(), rcvfax_exec(), sdp_register(), sdp_search(), session_destroy_fn(), session_destructor(), session_do(), session_end_if_deferred_task(), session_end_if_disconnected(), session_inv_on_redirected(), sip_websocket_callback(), sndfax_exec(), stasis_app_message_handler(), t38_automatic_reject(), t38_automatic_reject_timer_cb(), t38_parameters_task_data_alloc(), transport_read(), unistim_call(), update_completed(), wait_for_response(), websocket_cb(), and websocket_session_dtor().
showform
newtComponent showform static
Definition at line 448 of file astman.c.