Asterisk - The Open Source Telephony Project: file.h File Reference
file.h File Reference
Generic File Format Support. Should be included by clients of the file handling routines. File service providers should instead include mod_format.h.
#include <fcntl.h>
#include <sys/mman.h>
Macros
#define AST_DIGIT_ANY "0123456789#*ABCD"
#define AST_DIGIT_ANYNUM "0123456789"
#define AST_DIGIT_NONE ""
#define ast_file_read_dir(dir_name, on_file, obj) ast_file_read_dirs(dir_name, on_file, obj, 1)
Iterate over each file in a given directory.
#define AST_MAX_FORMATS 10
#define AST_RESERVED_POINTERS 20
#define SEEK_FORCECUR 10
Typedefs
typedef int(* ast_file_on_file) (const char *dir_name, const char *filename, void *obj)
Callback called for each file found when reading directories.
typedef void() ast_waitstream_fr_cb(struct ast_channel *chan, long ms, enum ast_waitstream_fr_cb_values val)
callback used during dtmf controlled file playback to indicate location of playback in a file after rewinding or fastfowarding a file.
Enumerations
enum ast_waitstream_fr_cb_values { AST_WAITSTREAM_CB_REWIND = 1, AST_WAITSTREAM_CB_FASTFORWARD, AST_WAITSTREAM_CB_START }
Functions
int ast_applystream (struct ast_channel *chan, struct ast_filestream *s)
Applys a open stream to a channel.
int ast_closestream (struct ast_filestream *f)
Closes a stream.
int ast_file_init (void)
int ast_file_read_dirs (const char *dir_name, ast_file_on_file on_file, void *obj, int max_depth)
Recursively iterate through files and directories up to max_depth.
int ast_filecopy (const char *oldname, const char *newname, const char *fmt)
Copies a file.
int ast_filedelete (const char *filename, const char *fmt)
Deletes a file.
int ast_fileexists (const char *filename, const char *fmt, const char *preflang)
Checks for the existence of a given file.
int ast_filerename (const char *oldname, const char *newname, const char *fmt)
Renames a file.
char * ast_format_str_reduce (char *fmts)
int ast_get_extension_for_mime_type (const char *mime_type, char *buffer, size_t capacity)
Get a suitable filename extension for the given MIME type.
struct ast_format * ast_get_format_for_file_ext (const char *file_ext)
Get the ast_format associated with the given file extension.
struct ast_filestream * ast_openstream (struct ast_channel *chan, const char *filename, const char *preflang)
Opens stream for use in seeking, playing.
struct ast_filestream * ast_openstream_full (struct ast_channel *chan, const char *filename, const char *preflang, int asis)
Opens stream for use in seeking, playing.
struct ast_filestream * ast_openvstream (struct ast_channel *chan, const char *filename, const char *preflang)
Opens stream for use in seeking, playing.
int ast_playstream (struct ast_filestream *s)
Play a open stream on a channel.
int ast_ratestream (struct ast_filestream *fs)
Return the sample rate of the stream's format.
struct ast_filestream * ast_readfile (const char *filename, const char *type, const char *comment, int flags, int check, mode_t mode)
Starts reading from a file.
struct ast_frame * ast_readframe (struct ast_filestream *s)
Read a frame from a filestream.
int ast_seekstream (struct ast_filestream *fs, off_t sample_offset, int whence)
Seeks into stream.
int ast_stopstream (struct ast_channel *c)
Stops a stream.
int ast_stream_and_wait (struct ast_channel *chan, const char *file, const char *digits)
stream file until digit If the file name is non-empty, try to play it.
int ast_stream_fastforward (struct ast_filestream *fs, off_t ms)
Fast forward stream ms.
int ast_stream_rewind (struct ast_filestream *fs, off_t ms)
Rewind stream ms.
int ast_streamfile (struct ast_channel *c, const char *filename, const char *preflang)
Streams a file.
off_t ast_tellstream (struct ast_filestream *fs)
Tell where we are in a stream.
int ast_truncstream (struct ast_filestream *fs)
Trunc stream at current location.
int ast_waitstream (struct ast_channel *c, const char *breakon)
Waits for a stream to stop or digit to be pressed.
int ast_waitstream_exten (struct ast_channel *c, const char *context)
Waits for a stream to stop or digit matching a valid one digit exten to be pressed.
int ast_waitstream_fr (struct ast_channel *c, const char *breakon, const char *forward, const char *rewind, int ms)
Same as waitstream but allows stream to be forwarded or rewound.
int ast_waitstream_fr_w_cb (struct ast_channel *c, const char *breakon, const char *forward, const char *rewind, int ms, ast_waitstream_fr_cb cb)
Same as waitstream_fr but allows a callback to be alerted when a user fastforwards or rewinds the file.
int ast_waitstream_full (struct ast_channel *c, const char *breakon, int audiofd, int monfd)
struct ast_filestream * ast_writefile (const char *filename, const char *type, const char *comment, int flags, int check, mode_t mode)
Starts writing a file.
int ast_writestream (struct ast_filestream *fs, struct ast_frame *f)
Writes a frame to a stream.
Detailed Description
Generic File Format Support. Should be included by clients of the file handling routines. File service providers should instead include mod_format.h.
Definition in file file.h.
Macro Definition Documentation
AST_DIGIT_ANY
#define AST_DIGIT_ANY "0123456789#*ABCD"
Examples:
/usr/src/asterisk-18.5.0/main/app.c.
Definition at line 48 of file file.h.
Referenced by action_playback_and_continue(), agent_alert(), ast_ivr_menu_run_internal(), ast_play_and_wait(), ast_readstring_full(), ast_record_review(), ast_sip_add_usereqphone(), conf_exec(), conf_get_pin(), conf_run(), dial_exec_full(), dictate_exec(), directory_exec(), festival_exec(), get_folder(), get_folder_ja(), grab_transfer(), ivr_dispatch(), meetme_menu_admin(), meetme_menu_admin_extended(), pbx_builtin_background(), pbx_builtin_saycharacters(), pbx_builtin_saycharacters_case(), pbx_builtin_saydigits(), pbx_builtin_saymoney(), pbx_builtin_saynumber(), pbx_builtin_sayphonetic(), pbx_builtin_waitdigit(), play_file(), play_mailbox_owner(), play_message(), play_message_callerid(), play_message_datetime(), play_message_duration(), play_record_review(), retrydial_exec(), say_and_wait(), say_position(), sayname(), sayunixtime_exec(), select_item_menu(), select_item_seq(), try_calling(), vm_intro_gr(), vm_intro_he(), vm_intro_multilang(), vm_intro_pt(), vm_intro_pt_BR(), vmsayname_exec(), and wait_file2().
AST_DIGIT_ANYNUM
#define AST_DIGIT_ANYNUM "0123456789"
Definition at line 49 of file file.h.
Referenced by initreqprep().
AST_DIGIT_NONE
#define AST_DIGIT_NONE ""
Convenient for waiting
Definition at line 47 of file file.h.
Referenced by agent_login_exec(), ast_bridge_channel_playfile(), bridge_features_duration_callback(), grab_transfer(), limits_interval_playback(), play_file(), sayunixtime_exec(), and stream_failsound().
ast_file_read_dir
#define ast_file_read_dir (dir_name, on_file, obj) ast_file_read_dirs(dir_name, on_file, obj, 1)
Iterate over each file in a given directory.
Parameters
dir_name the name of the directory to search
on_file callback called on each file
obj user data object
Returns
-1 or errno on failure, otherwise 0
Definition at line 171 of file file.h.
Referenced by find_recording(), and moh_scan_files().
AST_MAX_FORMATS
#define AST_MAX_FORMATS 10
The maximum number of formats we expect to see in a format string
Examples:
/usr/src/asterisk-18.5.0/main/app.c.
Definition at line 44 of file file.h.
Referenced by ast_format_str_reduce().
AST_RESERVED_POINTERS
#define AST_RESERVED_POINTERS 20
Definition at line 409 of file file.h.
SEEK_FORCECUR
#define SEEK_FORCECUR 10
Definition at line 51 of file file.h.
Referenced by __ast_read(), ast_write_stream(), au_seek(), g719seek(), g726_seek(), g729_seek(), gsm_seek(), ilbc_seek(), mp3_seek(), pcm_seek(), siren14seek(), siren7seek(), slinear_seek(), vox_seek(), and wav_seek().
Typedef Documentation
ast_file_on_file
typedef int(* ast_file_on_file) (const char *dir_name, const char *filename, void *obj)
Callback called for each file found when reading directories.
Parameters
dir_name the name of the directory
filename the name of the file
obj user data object
Returns
non-zero to stop reading, otherwise zero to continue
Note
dir_name is not processed by realpath or other functions, symbolic links are not resolved. This ensures dir_name always starts with the exact string originally passed to ast_file_read_dir or ast_file_read_dirs.
Definition at line 152 of file file.h.
ast_waitstream_fr_cb
typedef void() ast_waitstream_fr_cb(struct ast_channel *chan, long ms, enum ast_waitstream_fr_cb_values val)
callback used during dtmf controlled file playback to indicate location of playback in a file after rewinding or fastfowarding a file.
Examples:
/usr/src/asterisk-18.5.0/main/app.c.
Definition at line 65 of file file.h.
Enumeration Type Documentation
ast_waitstream_fr_cb_values
enum ast_waitstream_fr_cb_values
The type of event associated with a ast_waitstream_fr_cb invocation
Enumerator
AST_WAITSTREAM_CB_REWIND
AST_WAITSTREAM_CB_FASTFORWARD
AST_WAITSTREAM_CB_START
Definition at line 54 of file file.h.
{
    AST_WAITSTREAM_CB_REWIND = 1,
    AST_WAITSTREAM_CB_FASTFORWARD,
    AST_WAITSTREAM_CB_START
 };
Function Documentation
ast_applystream()
int ast_applystream (struct ast_channel * chan, struct ast_filestream * s)
Applys a open stream to a channel.
Parameters
chan channel to work
s ast_filestream to apply
Return values
0 on success.
-1 on failure.
Definition at line 1020 of file file.c.
References ast_filestream::owner.
Referenced by ast_streamfile(), handle_getoption(), handle_recordfile(), handle_streamfile(), and speech_streamfile().
 {
    s->owner = chan;
    return 0;
 }
ast_closestream()
int ast_closestream (struct ast_filestream * f)
Closes a stream.
Parameters
f filestream to close Close a playback or recording stream
Return values
0 on success.
-1 on failure.
Examples:
/usr/src/asterisk-18.5.0/main/app.c.
Definition at line 1068 of file file.c.
References ao2_ref, filestream_close(), and NULL.
Referenced by __ast_play_and_record(), ast_hangup(), ast_moh_files_next(), ast_monitor_start(), ast_monitor_stop(), ast_readfile(), ast_stopstream(), ast_writefile(), dictate_exec(), filehelper(), filestream_destructor(), gen_closestream(), handle_cli_file_convert(), handle_recordfile(), local_ast_moh_stop(), mixmonitor_ds_close_fs(), moh_files_release(), msg_create_from_file(), record_exec(), and recordthread().
 {
    /* This used to destroy the filestream, but it now just decrements a refcount.
     * We close the stream in order to quit queuing frames now, because we might
     * change the writeformat, which could result in a subsequent write error, if
     * the format is different. */
    if (f == NULL) {
       return 0;
    }
    filestream_close(f);
    ao2_ref(f, -1);
    return 0;
 }
ast_file_init()
int ast_file_init (void)
Initialize file stuff
Initializes all the various file stuff. Basically just registers the cli stuff Returns 0 all the time
Provided by file.c
Definition at line 1983 of file file.c.
References ARRAY_LEN, ast_cli_register_multiple, ast_format_register_type(), ast_format_unregister_type(), ast_register_cleanup(), file_shutdown(), and STASIS_MESSAGE_TYPE_INIT.
 {
    STASIS_MESSAGE_TYPE_INIT(ast_format_register_type);
    STASIS_MESSAGE_TYPE_INIT(ast_format_unregister_type);
    ast_cli_register_multiple(cli_file, ARRAY_LEN(cli_file));
    ast_register_cleanup(file_shutdown);
    return 0;
 }
ast_file_read_dirs()
int ast_file_read_dirs (const char * dir_name, ast_file_on_file on_file, void * obj, int max_depth)
Recursively iterate through files and directories up to max_depth.
Parameters
dir_name the name of the directory to search
on_file callback called on each file
obj user data object
max_depth re-curse into sub-directories up to a given maximum (-1 = infinite)
Returns
-1 or errno on failure, otherwise 0
Definition at line 1231 of file file.c.
References __ast_file_read_dirs(), ast_mutex_lock, ast_mutex_unlock, errno, and read_dirs_lock.
Referenced by ast_media_index_update_for_file(), AST_TEST_DEFINE(), module_load_helper(), and stasis_app_stored_recording_find_all().
 {
    int res;
    errno = 0;
 #if !defined(__GLIBC__)
    ast_mutex_lock(&read_dirs_lock);
 #endif
    res = __ast_file_read_dirs(dir_name, on_file, obj, max_depth);
 #if !defined(__GLIBC__)
    ast_mutex_unlock(&read_dirs_lock);
 #endif
    return res;
 }
ast_filecopy()
int ast_filecopy (const char * oldname, const char * newname, const char * fmt)
Copies a file.
Parameters
oldname name of the file you wish to copy (minus extension)
newname name you wish the file to be copied to (minus extension)
fmt the format of the file Copy a given file in a given format, or if fmt is NULL, then do so for all
Definition at line 1108 of file file.c.
References ACTION_COPY, and filehelper().
Referenced by copy_plain_file(), msg_create_from_file(), and vm_forwardoptions().
 {
    return filehelper(filename, filename2, fmt, ACTION_COPY);
 }
ast_filedelete()
int ast_filedelete (const char * filename, const char * fmt)
Deletes a file.
Parameters
filename name of the file you wish to delete (minus the extension)
fmt of the file Delete a given file in a given format, or if fmt is NULL, then do so for all
Examples:
/usr/src/asterisk-18.5.0/main/app.c.
Definition at line 1098 of file file.c.
References ACTION_DELETE, filehelper(), and NULL.
Referenced by __ast_play_and_record(), announce_thread(), ast_monitor_start(), ast_monitor_stop(), async_delete_name_rec_task(), conf_free(), conf_rec_name(), conf_run(), confbridge_exec(), dial_exec_full(), handle_cli_file_convert(), leave_voicemail(), msg_create_from_file(), play_message(), play_record_review(), record_exec(), recording_cancel(), setup_privacy_args(), valid_priv_reply(), vm_allocate_dh(), and vm_delete().
 {
    return filehelper(filename, NULL, fmt, ACTION_DELETE);
 }
ast_fileexists()
int ast_fileexists (const char * filename, const char * fmt, const char * preflang)
Checks for the existence of a given file.
Parameters
filename name of the file you wish to check, minus the extension
fmt the format you wish to check (the extension)
preflang (the preferred language you wisht to find the file in) See if a given file exists in a given format. If fmt is NULL, any format is accepted.
Return values
0,false. The file does not exist
1,true. The file does exist.
Definition at line 1086 of file file.c.
References ast_alloca, buf, fileexists_core(), and NULL.
Referenced by announce_thread(), app_exec(), ast_get_character_str(), ast_get_digit_str(), ast_get_phonetic_str(), ast_moh_files_next(), ast_monitor_start(), ast_monitor_stop(), AST_TEST_DEFINE(), common_exec(), conf_run(), dial_exec_full(), eivr_comm(), forward_message(), get_folder(), invent_message(), leave_voicemail(), meetme_menu_admin_extended(), minivm_delete_exec(), msg_create_from_file(), page_exec(), play_file(), play_message(), play_message_by_id_helper(), play_message_callerid(), readexten_exec(), record_exec(), retrydial_exec(), sayname(), setup_privacy_args(), sound_file_exists(), stasis_app_control_record(), valid_priv_reply(), vm_allocate_dh(), vm_intro(), vm_msg_play(), vm_newuser_setup(), vm_options(), and vm_tempgreeting().
 {
    char *buf;
    int buflen;
    if (preflang == NULL)
       preflang = "";
    buflen = strlen(preflang) + strlen(filename) + 4;  /* room for everything */
    buf = ast_alloca(buflen);
    return fileexists_core(filename, fmt, preflang, buf, buflen, NULL) ? 1 : 0;
 }
ast_filerename()
int ast_filerename (const char * oldname, const char * newname, const char * fmt)
Renames a file.
Parameters
oldname the name of the file you wish to act upon (minus the extension)
newname the name you wish to rename the file to (minus the extension)
fmt the format of the file Rename a given file in a given format, or if fmt is NULL, then do so for all
Returns
-1 on failure
Examples:
/usr/src/asterisk-18.5.0/main/app.c.
Definition at line 1103 of file file.c.
References ACTION_RENAME, and filehelper().
Referenced by __ast_play_and_record(), ast_monitor_stop(), forward_message(), leave_voicemail(), msg_create_from_file(), play_record_review(), rename_file(), and vm_forwardoptions().
 {
    return filehelper(filename, filename2, fmt, ACTION_RENAME);
 }
ast_format_str_reduce()
char* ast_format_str_reduce (char * fmts)
Remove duplicate formats from a format string.
Parameters
fmts a format string, this string will be modified
Return values
NULL error
Returns
a pointer to the reduced format string, this is a pointer to fmts
Definition at line 1826 of file file.c.
References ast_log, AST_MAX_FORMATS, AST_RWLIST_RDLOCK, AST_RWLIST_TRAVERSE, AST_RWLIST_UNLOCK, ast_strdupa, ast_format_def::exts, exts_compare, first, len(), LOG_WARNING, NULL, strsep(), and type.
Referenced by actual_load_config(), and AST_TEST_DEFINE().
 {
    struct ast_format_def *f;
    struct ast_format_def *fmts_ptr[AST_MAX_FORMATS];
    char *fmts_str[AST_MAX_FORMATS];
    char *stringp, *type;
    char *orig = fmts;
    int i, j, x, first, found = 0;
    int len = strlen(fmts) + 1;
    int res;
    if (AST_RWLIST_RDLOCK(&formats)) {
       ast_log(LOG_WARNING, "Unable to lock format list\n");
       return NULL;
    }
    stringp = ast_strdupa(fmts);
    for (x = 0; (type = strsep(&stringp, "|")) && x < AST_MAX_FORMATS; x++) {
       AST_RWLIST_TRAVERSE(&formats, f, list) {
          if (exts_compare(f->exts, type)) {
             found = 1;
             break;
          }
       }
       fmts_str[x] = type;
       if (found) {
          fmts_ptr[x] = f;
       } else {
          fmts_ptr[x] = NULL;
       }
    }
    AST_RWLIST_UNLOCK(&formats);
    first = 1;
    for (i = 0; i < x; i++) {
       /* ignore invalid entries */
       if (!fmts_ptr[i]) {
          ast_log(LOG_WARNING, "ignoring unknown format '%s'\n", fmts_str[i]);
          continue;
       }
       /* special handling for the first entry */
       if (first) {
          res = snprintf(fmts, len, "%s", fmts_str[i]);
          fmts += res;
          len -= res;
          first = 0;
          continue;
       }
       found = 0;
       for (j = 0; j < i; j++) {
          /* this is a duplicate */
          if (fmts_ptr[j] == fmts_ptr[i]) {
             found = 1;
             break;
          }
       }
       if (!found) {
          res = snprintf(fmts, len, "|%s", fmts_str[i]);
          fmts += res;
          len -= res;
       }
    }
    if (first) {
       ast_log(LOG_WARNING, "no known formats found in format list (%s)\n", orig);
       return NULL;
    }
    return orig;
 }
ast_get_extension_for_mime_type()
int ast_get_extension_for_mime_type (const char * mime_type, char * buffer, size_t capacity)
Get a suitable filename extension for the given MIME type.
Parameters
mime_type The MIME type for which to find extensions
buffer A pointer to a buffer to receive the extension
capacity The size of 'buffer' in bytes
Return values
1 if an extension was found for the provided MIME type
0 if the MIME type was not found
Definition at line 1951 of file file.c.
References ast_assert, AST_RWLIST_TRAVERSE, ast_format_def::exts, formats::lock, lock, ast_format_def::mime_types, SCOPED_RDLOCK, and type_in_list().
Referenced by bucket_file_update_path().
 {
    struct ast_format_def *f;
    SCOPED_RDLOCK(lock, &formats.lock);
    ast_assert(buffer && capacity);
    AST_RWLIST_TRAVERSE(&formats, f, list) {
       if (type_in_list(f->mime_types, mime_type, strcasecmp)) {
          size_t item_len = strcspn(f->exts, "|");
          size_t bytes_written = snprintf(buffer, capacity, ".%.*s", (int) item_len, f->exts);
          if (bytes_written < capacity) {
             /* Only return success if we didn't truncate */
             return 1;
          }
       }
    }
    return 0;
 }
ast_get_format_for_file_ext()
struct ast_format* ast_get_format_for_file_ext (const char * file_ext)
Get the ast_format associated with the given file extension.
Since
12
Parameters
file_ext The file extension for which to find the format
Return values
NULL if not found
A pointer to the ast_format associated with this file extension
Definition at line 1938 of file file.c.
References AST_RWLIST_TRAVERSE, ast_format_def::exts, exts_compare, ast_format_def::format, formats::lock, lock, NULL, and SCOPED_RDLOCK.
Referenced by ast_ari_bridges_record(), ast_ari_channels_record(), ast_ari_recordings_get_stored_file(), bucket_file_update_path(), is_recording(), and process_media_file().
 {
    struct ast_format_def *f;
    SCOPED_RDLOCK(lock, &formats.lock);
    AST_RWLIST_TRAVERSE(&formats, f, list) {
       if (exts_compare(f->exts, file_ext)) {
          return f->format;
       }
    }
    return NULL;
 }
ast_openstream()
struct ast_filestream* ast_openstream (struct ast_channel * chan, const char * filename, const char * preflang)
Opens stream for use in seeking, playing.
Parameters
chan channel to work with
filename to use
preflang prefered language to use
Return values
a ast_filestream pointer if it opens the file.
NULL on error.
Definition at line 755 of file file.c.
References ast_openstream_full().
Referenced by ast_streamfile(), dictate_exec(), handle_getoption(), handle_streamfile(), and speech_streamfile().
 {
    return ast_openstream_full(chan, filename, preflang, 0);
 }
ast_openstream_full()
struct ast_filestream* ast_openstream_full (struct ast_channel * chan, const char * filename, const char * preflang, int asis)
Opens stream for use in seeking, playing.
Parameters
chan channel to work with
filename to use
preflang prefered language to use
asis if set, don't clear generators
Return values
a ast_filestream pointer if it opens the file.
NULL on error.
Definition at line 760 of file file.c.
References ACTION_OPEN, ao2_ref, ast_alloca, ast_channel_generator(), ast_channel_lock, ast_channel_set_oldwriteformat(), ast_channel_stream(), ast_channel_unlock, ast_channel_writeformat(), ast_deactivate_generator(), ast_format_cap_alloc, AST_FORMAT_CAP_FLAG_DEFAULT, ast_format_cap_has_type(), ast_log, AST_MEDIA_TYPE_AUDIO, ast_set_write_format_from_cap(), ast_stopstream(), buf, fileexists_core(), filehelper(), LOG_WARNING, and NULL.
Referenced by ast_moh_files_next(), ast_openstream(), and gen_nextfile().
 {
    /*
     * Use fileexists_core() to find a file in a compatible
     * language and format, set up a suitable translator,
     * and open the stream.
     */
    struct ast_format_cap *file_fmt_cap;
    int res;
    int buflen;
    char *buf;
    if (!asis) {
       /* do this first, otherwise we detect the wrong writeformat */
       ast_stopstream(chan);
       if (ast_channel_generator(chan))
          ast_deactivate_generator(chan);
    }
    if (preflang == NULL)
       preflang = "";
    buflen = strlen(preflang) + strlen(filename) + 4;
    buf = ast_alloca(buflen);
    if (!(file_fmt_cap = ast_format_cap_alloc(AST_FORMAT_CAP_FLAG_DEFAULT))) {
       return NULL;
    }
    if (!fileexists_core(filename, NULL, preflang, buf, buflen, file_fmt_cap) ||
       !ast_format_cap_has_type(file_fmt_cap, AST_MEDIA_TYPE_AUDIO)) {
       ast_log(LOG_WARNING, "File %s does not exist in any format\n", filename);
       ao2_ref(file_fmt_cap, -1);
       return NULL;
    }
    /* Set the channel to a format we can work with and save off the previous format. */
    ast_channel_lock(chan);
    ast_channel_set_oldwriteformat(chan, ast_channel_writeformat(chan));
    /* Set the channel to the best format that exists for the file. */
    res = ast_set_write_format_from_cap(chan, file_fmt_cap);
    ast_channel_unlock(chan);
    /* don't need this anymore now that the channel's write format is set. */
    ao2_ref(file_fmt_cap, -1);
    if (res == -1) {  /* No format available that works with this channel */
       return NULL;
    }
    res = filehelper(buf, chan, NULL, ACTION_OPEN);
    if (res >= 0)
       return ast_channel_stream(chan);
    return NULL;
 }
ast_openvstream()
struct ast_filestream* ast_openvstream (struct ast_channel * chan, const char * filename, const char * preflang)
Opens stream for use in seeking, playing.
Parameters
chan channel to work with
filename to use
preflang prefered language to use
Return values
a ast_filestream pointer if it opens the file.
NULL on error.
Definition at line 812 of file file.c.
References ACTION_OPEN, ao2_bump, ao2_cleanup, ao2_ref, ast_alloca, ast_channel_lock, ast_channel_nativeformats(), ast_channel_unlock, ast_channel_vstream(), ast_format_cap_alloc, ast_format_cap_count(), AST_FORMAT_CAP_FLAG_DEFAULT, ast_format_cap_get_format(), ast_format_cap_has_type(), ast_format_cap_iscompatible(), ast_format_get_name(), ast_format_get_type(), ast_log, AST_MEDIA_TYPE_VIDEO, buf, fileexists_core(), filehelper(), format, LOG_WARNING, and NULL.
Referenced by ast_streamfile(), handle_getoption(), and handle_streamfile().
 {
    /* As above, but for video. But here we don't have translators
     * so we must enforce a format.
     */
    struct ast_format_cap *nativeformats, *tmp_cap;
    char *buf;
    int buflen;
    int i, fd;
    if (preflang == NULL) {
       preflang = "";
    }
    buflen = strlen(preflang) + strlen(filename) + 4;
    buf = ast_alloca(buflen);
    ast_channel_lock(chan);
    nativeformats = ao2_bump(ast_channel_nativeformats(chan));
    ast_channel_unlock(chan);
    /* is the channel capable of video without translation ?*/
    if (!ast_format_cap_has_type(nativeformats, AST_MEDIA_TYPE_VIDEO)) {
       ao2_cleanup(nativeformats);
       return NULL;
    }
    if (!(tmp_cap = ast_format_cap_alloc(AST_FORMAT_CAP_FLAG_DEFAULT))) {
       ao2_cleanup(nativeformats);
       return NULL;
    }
    /* Video is supported, so see what video formats exist for this file */
    if (!fileexists_core(filename, NULL, preflang, buf, buflen, tmp_cap)) {
       ao2_ref(tmp_cap, -1);
       ao2_cleanup(nativeformats);
       return NULL;
    }
    /* iterate over file formats and pick the first one compatible with the channel's native formats */
    for (i = 0; i < ast_format_cap_count(tmp_cap); ++i) {
       struct ast_format *format = ast_format_cap_get_format(tmp_cap, i);
       if ((ast_format_get_type(format) != AST_MEDIA_TYPE_VIDEO) ||
          !ast_format_cap_iscompatible(nativeformats, tmp_cap)) {
          ao2_ref(format, -1);
          continue;
       }
       fd = filehelper(buf, chan, ast_format_get_name(format), ACTION_OPEN);
       if (fd >= 0) {
          ao2_ref(format, -1);
          ao2_ref(tmp_cap, -1);
          ao2_cleanup(nativeformats);
          return ast_channel_vstream(chan);
       }
       ast_log(LOG_WARNING, "File %s has video but couldn't be opened\n", filename);
       ao2_ref(format, -1);
    }
    ao2_ref(tmp_cap, -1);
    ao2_cleanup(nativeformats);
    return NULL;
 }
ast_playstream()
int ast_playstream (struct ast_filestream * s)
Play a open stream on a channel.
Parameters
s filestream to play
Return values
0 on success.
-1 on failure.
Definition at line 1026 of file file.c.
References ast_format_get_type(), AST_MEDIA_TYPE_AUDIO, ast_readaudio_callback(), ast_readvideo_callback(), ast_filestream::fmt, ast_format_def::format, and FSREAD_FAILURE.
Referenced by ast_streamfile(), handle_getoption(), handle_streamfile(), and speech_streamfile().
 {
    enum fsread_res res;
    if (ast_format_get_type(s->fmt->format) == AST_MEDIA_TYPE_AUDIO)
       res = ast_readaudio_callback(s);
    else
       res = ast_readvideo_callback(s);
    return (res == FSREAD_FAILURE) ? -1 : 0;
 }
ast_ratestream()
int ast_ratestream (struct ast_filestream * fs)
Return the sample rate of the stream's format.
Parameters
fs fs to act on
Returns
sample rate in Hz
Definition at line 1053 of file file.c.
References ast_format_get_sample_rate(), ast_filestream::fmt, and ast_format_def::format.
Referenced by msg_create_from_file().
 {
    return ast_format_get_sample_rate(fs->fmt->format);
 }
ast_readfile()
struct ast_filestream* ast_readfile (const char * filename, const char * type, const char * comment, int flags, int check, mode_t mode)
Starts reading from a file.
Parameters
filename the name of the file to read from
type format of file you wish to read from
comment comment to go with
flags file flags
check (unimplemented, hence negligible)
mode Open mode Open an incoming file stream. flags are flags for the open() command, and if check is non-zero, then it will not read a file if there are any files that start with that name and have an extension Please note, this is a blocking function. Program execution will not return until ast_waitstream completes it's execution.
Return values
a struct ast_filestream on success.
NULL on failure.
Examples:
/usr/src/asterisk-18.5.0/main/app.c.
Definition at line 1309 of file file.c.
References ast_closestream(), ast_free, ast_log, AST_RWLIST_RDLOCK, AST_RWLIST_TRAVERSE, AST_RWLIST_UNLOCK, ast_strdup, build_filename(), errno, ast_format_def::exts, exts_compare, ast_filestream::f, ast_filestream::filename, ast_filestream::flags, ast_filestream::fmt, get_filestream(), LOG_WARNING, ast_filestream::mode, NULL, open_wrapper(), ast_filestream::trans, and ast_filestream::vfs.
Referenced by __ast_play_and_record(), handle_cli_file_convert(), and msg_create_from_file().
 {
    FILE *bfile;
    struct ast_format_def *f;
    struct ast_filestream *fs = NULL;
    char *fn;
    int format_found = 0;
    AST_RWLIST_RDLOCK(&formats);
    AST_RWLIST_TRAVERSE(&formats, f, list) {
       fs = NULL;
       if (!exts_compare(f->exts, type))
          continue;
       else
          format_found = 1;
       fn = build_filename(filename, type);
       if (!fn) {
          continue;
       }
       errno = 0;
       bfile = fopen(fn, "r");
       if (!bfile || (fs = get_filestream(f, bfile)) == NULL || open_wrapper(fs) ) {
          ast_log(LOG_WARNING, "Unable to open %s\n", fn);
          if (fs) {
             ast_closestream(fs);
          }
          fs = NULL;
          bfile = NULL;
          ast_free(fn);
          break;
       }
       /* found it */
       fs->trans = NULL;
       fs->fmt = f;
       fs->flags = flags;
       fs->mode = mode;
       fs->filename = ast_strdup(filename);
       fs->vfs = NULL;
       ast_free(fn);
       break;
    }
    AST_RWLIST_UNLOCK(&formats);
    if (!format_found)
       ast_log(LOG_WARNING, "No such format '%s'\n", type);
    return fs;
 }
ast_readframe()
struct ast_frame* ast_readframe (struct ast_filestream * s)
Read a frame from a filestream.
Parameters
s ast_filestream to act on
Returns
a frame.
Return values
NULL if read failed.
Examples:
/usr/src/asterisk-18.5.0/main/app.c.
Definition at line 899 of file file.c.
References read_frame().
Referenced by __ast_play_and_record(), dictate_exec(), gen_readframe(), handle_cli_file_convert(), and moh_files_readframe().
 {
    int whennext = 0;
    return read_frame(s, &whennext);
 }
ast_seekstream()
int ast_seekstream (struct ast_filestream * fs, off_t sample_offset, int whence)
Seeks into stream.
Parameters
fs ast_filestream to perform seek on
sample_offset numbers of samples to seek
whence SEEK_SET, SEEK_CUR, SEEK_END
Return values
0 on success.
-1 on failure.
Examples:
/usr/src/asterisk-18.5.0/main/app.c.
Definition at line 1038 of file file.c.
References ast_filestream::fmt, and ast_format_def::seek.
Referenced by __ast_read(), ast_moh_files_next(), ast_stream_fastforward(), ast_stream_rewind(), ast_streamfile(), ast_write_stream(), control_streamfile(), dictate_exec(), handle_getoption(), handle_recordfile(), handle_streamfile(), msg_create_from_file(), and speech_streamfile().
 {
    return fs->fmt->seek(fs, sample_offset, whence);
 }
ast_stopstream()
int ast_stopstream (struct ast_channel * c)
Stops a stream.
Parameters
c The channel you wish to stop playback on
Stop playback of a stream
Return values
0 always
Note
The channel does not need to be locked before calling this function.
Examples:
/usr/src/asterisk-18.5.0/main/app.c.
Definition at line 187 of file file.c.
References ast_channel_lock, ast_channel_oldwriteformat(), ast_channel_stream(), ast_channel_stream_set(), ast_channel_unlock, ast_channel_vstream(), ast_channel_vstream_set(), ast_closestream(), ast_format_get_name(), ast_log, ast_set_write_format(), LOG_WARNING, and NULL.
Referenced by action_playback_and_continue(), adsi_transmit_message_full(), agent_alert(), announce_to_dial(), ast_openstream_full(), ast_play_and_wait(), ast_readstring_full(), ast_say_enumeration_full_da(), ast_say_enumeration_full_de(), ast_say_enumeration_full_en(), ast_say_enumeration_full_he(), ast_say_enumeration_full_is(), ast_say_enumeration_full_vi(), ast_say_number_full_cs(), ast_say_number_full_da(), ast_say_number_full_de(), ast_say_number_full_en(), ast_say_number_full_en_GB(), ast_say_number_full_es(), ast_say_number_full_fr(), ast_say_number_full_gr(), ast_say_number_full_he(), ast_say_number_full_hu(), ast_say_number_full_is(), ast_say_number_full_it(), ast_say_number_full_ja(), ast_say_number_full_ka(), ast_say_number_full_nl(), ast_say_number_full_no(), ast_say_number_full_pt(), ast_say_number_full_ru(), ast_say_number_full_se(), ast_say_number_full_th(), ast_say_number_full_ur(), ast_say_number_full_vi(), ast_say_number_full_zh(), background_detect_exec(), conf_exec(), conf_run(), control_streamfile(), dial_exec_full(), directory_exec(), grab_transfer(), handle_getoption(), handle_speechrecognize(), handle_streamfile(), ices_exec(), ivr_dispatch(), leave_voicemail(), meetme_menu_admin(), meetme_menu_admin_extended(), minivm_greet_exec(), mp3_exec(), NBScat_exec(), pbx_builtin_background(), pl_odtworz_plik(), play_file(), play_files_helper(), play_mailbox_owner(), playback_exec(), queue_exec(), read_exec(), readexten_exec(), record_exec(), recordthread(), s_streamwait3(), say_character_str_full(), say_digit_str_full(), say_money_str_full(), say_phonetic_str_full(), select_item_seq(), send_waveform_to_channel(), speech_background(), vm_authenticate(), vm_execmain(), wait_for_winner(), waitstream_core(), and zapateller_exec().
 {
    ast_channel_lock(tmp);
    /* Stop a running stream if there is one */
    if (ast_channel_stream(tmp)) {
       ast_closestream(ast_channel_stream(tmp));
       ast_channel_stream_set(tmp, NULL);
       if (ast_channel_oldwriteformat(tmp) && ast_set_write_format(tmp, ast_channel_oldwriteformat(tmp)))
          ast_log(LOG_WARNING, "Unable to restore format back to %s\n", ast_format_get_name(ast_channel_oldwriteformat(tmp)));
    }
    /* Stop the video stream too */
    if (ast_channel_vstream(tmp) != NULL) {
       ast_closestream(ast_channel_vstream(tmp));
       ast_channel_vstream_set(tmp, NULL);
    }
    ast_channel_unlock(tmp);
    return 0;
 }
ast_stream_and_wait()
int ast_stream_and_wait (struct ast_channel * chan, const char * file, const char * digits)
stream file until digit If the file name is non-empty, try to play it.
Note
If digits == "" then we can simply check for non-zero.
Returns
0 if success.
Return values
-1 if error.
digit if interrupted by a digit.
Examples:
/usr/src/asterisk-18.5.0/main/app.c.
Definition at line 1814 of file file.c.
References ast_channel_language(), ast_streamfile(), ast_strlen_zero, and ast_waitstream().
Referenced by __ast_play_and_record(), action_playback(), action_toggle_mute_participants(), agent_alert(), agent_login_exec(), announce_user_count(), app_exec(), ast_bridge_channel_playfile(), ast_pickup_call(), ast_record_review(), bridge_features_duration_callback(), confbridge_exec(), directory_exec(), forward_message(), grab_transfer(), invent_message(), ivr_dispatch(), join_conference_bridge(), leave_voicemail(), limits_interval_playback(), mixmonitor_thread(), park_app_exec(), parked_call_app_exec(), play_file(), play_files_helper(), play_mailbox_owner(), play_message_callerid(), play_prompt_to_user(), play_record_review(), playback_common(), sayname(), select_item_seq(), setup_mixmonitor_ds(), stream_failsound(), vm_forwardoptions(), vmsayname_exec(), and wait_file2().
 {
    int res = 0;
    if (!ast_strlen_zero(file)) {
       res = ast_streamfile(chan, file, ast_channel_language(chan));
       if (!res) {
          res = ast_waitstream(chan, digits);
       }
    }
    return res;
 }
ast_stream_fastforward()
int ast_stream_fastforward (struct ast_filestream * fs, off_t ms)
Fast forward stream ms.
Parameters
fs filestream to act on
ms milliseconds to move
Return values
0 on success.
-1 on failure.
Definition at line 1058 of file file.c.
References ast_seekstream(), and DEFAULT_SAMPLES_PER_MS.
Referenced by waitstream_control().
 {
    return ast_seekstream(fs, ms * DEFAULT_SAMPLES_PER_MS, SEEK_CUR);
 }
ast_stream_rewind()
int ast_stream_rewind (struct ast_filestream * fs, off_t ms)
Rewind stream ms.
Parameters
fs filestream to act on
ms milliseconds to move
Return values
0 on success.
-1 on failure.
Examples:
/usr/src/asterisk-18.5.0/main/app.c.
Definition at line 1063 of file file.c.
References ast_seekstream(), and DEFAULT_SAMPLES_PER_MS.
Referenced by __ast_play_and_record(), handle_recordfile(), record_exec(), and waitstream_control().
 {
    return ast_seekstream(fs, -ms * DEFAULT_SAMPLES_PER_MS, SEEK_CUR);
 }
ast_streamfile()
int ast_streamfile (struct ast_channel * c, const char * filename, const char * preflang)
Streams a file.
Parameters
c channel to stream the file to
filename the name of the file you wish to stream, minus the extension
preflang the preferred language you wish to have the file streamed to you in Prepares a channel for the streaming of a file. To start the stream, afterward do a ast_waitstream() on the channel Also, it will stop any existing streams on the channel.
Return values
0 on success.
-1 on failure.
Examples:
/usr/src/asterisk-18.5.0/main/app.c.
Definition at line 1250 of file file.c.
References ast_applystream(), ast_channel_flags(), ast_channel_lock, ast_channel_name(), ast_channel_nativeformats(), ast_channel_unlock, ast_channel_writeformat(), ast_debug, AST_FLAG_MASQ_NOSTREAM, ast_format_cap_get_names(), AST_FORMAT_CAP_NAMES_LEN, ast_format_get_name(), ast_log, ast_openstream(), ast_openvstream(), ast_playstream(), ast_seekstream(), ast_str_alloca, ast_strdup, ast_test_flag, ast_test_suite_event_notify, ast_verb, errno, ast_filestream::f, ast_filestream::fmt, ast_format_def::format, LOG_WARNING, NULL, ast_filestream::orig_chan_name, VERBOSITY_ATLEAST, and ast_filestream::vfs.
Referenced by __analog_ss_thread(), action_playback_and_continue(), analog_ss_thread(), announce_thread(), announce_to_dial(), app_exec(), ast_app_getdata(), ast_app_getdata_full(), ast_play_and_wait(), ast_say_date_da(), ast_say_date_de(), ast_say_date_en(), ast_say_date_fr(), ast_say_date_gr(), ast_say_date_he(), ast_say_date_hu(), ast_say_date_is(), ast_say_date_ja(), ast_say_date_ka(), ast_say_date_nl(), ast_say_date_th(), ast_say_date_with_format_gr(), ast_say_datetime_en(), ast_say_datetime_fr(), ast_say_datetime_from_now_en(), ast_say_datetime_from_now_fr(), ast_say_datetime_from_now_he(), ast_say_datetime_from_now_ka(), ast_say_datetime_gr(), ast_say_datetime_he(), ast_say_datetime_ja(), ast_say_datetime_nl(), ast_say_datetime_pt(), ast_say_datetime_th(), ast_say_datetime_zh(), ast_say_enumeration_full_da(), ast_say_enumeration_full_de(), ast_say_enumeration_full_en(), ast_say_enumeration_full_he(), ast_say_enumeration_full_is(), ast_say_enumeration_full_vi(), ast_say_number_full_cs(), ast_say_number_full_da(), ast_say_number_full_de(), ast_say_number_full_en(), ast_say_number_full_en_GB(), ast_say_number_full_es(), ast_say_number_full_fr(), ast_say_number_full_gr(), ast_say_number_full_he(), ast_say_number_full_hu(), ast_say_number_full_is(), ast_say_number_full_it(), ast_say_number_full_ja(), ast_say_number_full_ka(), ast_say_number_full_nl(), ast_say_number_full_no(), ast_say_number_full_pt(), ast_say_number_full_ru(), ast_say_number_full_se(), ast_say_number_full_th(), ast_say_number_full_ur(), ast_say_number_full_vi(), ast_say_number_full_zh(), ast_say_time_de(), ast_say_time_en(), ast_say_time_fr(), ast_say_time_gr(), ast_say_time_hu(), ast_say_time_ja(), ast_say_time_ka(), ast_say_time_nl(), ast_say_time_zh(), ast_stream_and_wait(), auth_exec(), background_detect_exec(), common_exec(), conf_exec(), conf_get_pin(), conf_run(), control_streamfile(), dial_exec_full(), do_directory(), find_conf_realtime(), forward_message(), gr_say_number_female(), handle_recordfile(), invent_message(), leave_voicemail(), meetme_menu_admin(), meetme_menu_admin_extended(), meetme_menu_normal(), minivm_greet_exec(), page_exec(), pbx_builtin_background(), pl_odtworz_plik(), play_and_wait(), play_file(), play_record_review(), playback_exec(), privacy_exec(), readexten_exec(), record_exec(), retrydial_exec(), s_streamwait3(), say_character_str_full(), say_digit_str_full(), say_money_str_full(), say_phonetic_str_full(), select_item_menu(), setup_privacy_args(), vm_authenticate(), wait_file(), and wait_for_winner().
 {
    struct ast_filestream *fs;
    struct ast_filestream *vfs=NULL;
    off_t pos;
    int seekattempt;
    int res;
    fs = ast_openstream(chan, filename, preflang);
    if (!fs) {
       struct ast_str *codec_buf = ast_str_alloca(AST_FORMAT_CAP_NAMES_LEN);
       ast_channel_lock(chan);
       ast_log(LOG_WARNING, "Unable to open %s (format %s): %s\n",
          filename, ast_format_cap_get_names(ast_channel_nativeformats(chan), &codec_buf), strerror(errno));
       ast_channel_unlock(chan);
       return -1;
    }
    /* check to see if there is any data present (not a zero length file),
     * done this way because there is no where for ast_openstream_full to
     * return the file had no data. */
    pos = ftello(fs->f);
    seekattempt = fseeko(fs->f, -1, SEEK_END);
    if (seekattempt) {
       if (errno == EINVAL) {
          /* Zero-length file, as opposed to a pipe */
          return 0;
       } else {
          ast_seekstream(fs, 0, SEEK_SET);
       }
    } else {
       fseeko(fs->f, pos, SEEK_SET);
    }
    vfs = ast_openvstream(chan, filename, preflang);
    if (vfs) {
       ast_debug(1, "Ooh, found a video stream, too, format %s\n", ast_format_get_name(vfs->fmt->format));
    }
    if (ast_test_flag(ast_channel_flags(chan), AST_FLAG_MASQ_NOSTREAM))
       fs->orig_chan_name = ast_strdup(ast_channel_name(chan));
    if (ast_applystream(chan, fs))
       return -1;
    if (vfs && ast_applystream(chan, vfs))
       return -1;
    ast_test_suite_event_notify("PLAYBACK", "Message: %s\r\nChannel: %s", filename, ast_channel_name(chan));
    res = ast_playstream(fs);
    if (!res && vfs)
       res = ast_playstream(vfs);
    if (VERBOSITY_ATLEAST(3)) {
       ast_channel_lock(chan);
       ast_verb(3, "<%s> Playing '%s.%s' (language '%s')\n", ast_channel_name(chan), filename, ast_format_get_name(ast_channel_writeformat(chan)), preflang ? preflang : "default");
       ast_channel_unlock(chan);
    }
    return res;
 }
ast_tellstream()
off_t ast_tellstream (struct ast_filestream * fs)
Tell where we are in a stream.
Parameters
fs fs to act on
Returns
a long as a sample offset into stream
Examples:
/usr/src/asterisk-18.5.0/main/app.c.
Definition at line 1048 of file file.c.
References ast_filestream::fmt, and ast_format_def::tell.
Referenced by __ast_play_and_record(), ast_moh_files_next(), control_streamfile(), handle_getoption(), handle_recordfile(), handle_speechrecognize(), handle_streamfile(), msg_create_from_file(), waitstream_control(), and waitstream_core().
 {
    return fs->fmt->tell(fs);
 }
ast_truncstream()
int ast_truncstream (struct ast_filestream * fs)
Trunc stream at current location.
Parameters
fs filestream to act on
Return values
0 on success.
-1 on failure.
Examples:
/usr/src/asterisk-18.5.0/main/app.c.
Definition at line 1043 of file file.c.
References ast_filestream::fmt, and ast_format_def::trunc.
Referenced by __ast_play_and_record(), handle_recordfile(), and record_exec().
 {
    return fs->fmt->trunc(fs);
 }
ast_waitstream()
int ast_waitstream (struct ast_channel * c, const char * breakon)
Waits for a stream to stop or digit to be pressed.
Parameters
c channel to waitstream on
breakon string of DTMF digits to break upon Begins playback of a stream... Wait for a stream to stop or for any one of a given digit to arrive,
Return values
0 if the stream finishes
the character if it was interrupted by the channel.
-1 on error
Examples:
/usr/src/asterisk-18.5.0/main/app.c.
Definition at line 1776 of file file.c.
References NULL, sanitize_waitstream_return(), and waitstream_core().
Referenced by __analog_ss_thread(), action_playback_and_continue(), analog_ss_thread(), announce_thread(), announce_to_dial(), app_exec(), ast_play_and_wait(), ast_say_date_da(), ast_say_date_de(), ast_say_date_en(), ast_say_date_fr(), ast_say_date_gr(), ast_say_date_he(), ast_say_date_hu(), ast_say_date_is(), ast_say_date_ja(), ast_say_date_ka(), ast_say_date_nl(), ast_say_date_th(), ast_say_date_with_format_gr(), ast_say_datetime_en(), ast_say_datetime_fr(), ast_say_datetime_from_now_en(), ast_say_datetime_from_now_fr(), ast_say_datetime_from_now_he(), ast_say_datetime_from_now_ka(), ast_say_datetime_gr(), ast_say_datetime_he(), ast_say_datetime_ja(), ast_say_datetime_nl(), ast_say_datetime_pt(), ast_say_datetime_th(), ast_say_datetime_zh(), ast_say_enumeration_full_da(), ast_say_enumeration_full_de(), ast_say_enumeration_full_en(), ast_say_enumeration_full_he(), ast_say_enumeration_full_is(), ast_say_enumeration_full_vi(), ast_say_number_full_cs(), ast_say_number_full_da(), ast_say_number_full_de(), ast_say_number_full_en(), ast_say_number_full_en_GB(), ast_say_number_full_es(), ast_say_number_full_fr(), ast_say_number_full_gr(), ast_say_number_full_he(), ast_say_number_full_hu(), ast_say_number_full_is(), ast_say_number_full_it(), ast_say_number_full_ja(), ast_say_number_full_ka(), ast_say_number_full_nl(), ast_say_number_full_no(), ast_say_number_full_pt(), ast_say_number_full_ru(), ast_say_number_full_se(), ast_say_number_full_th(), ast_say_number_full_ur(), ast_say_number_full_vi(), ast_say_number_full_zh(), ast_say_time_de(), ast_say_time_en(), ast_say_time_gr(), ast_say_time_he(), ast_say_time_hu(), ast_say_time_ja(), ast_say_time_ka(), ast_say_time_nl(), ast_say_time_zh(), ast_stream_and_wait(), auth_exec(), common_exec(), conf_exec(), conf_get_pin(), conf_run(), directory_exec(), find_conf_realtime(), gr_say_number_female(), handle_recordfile(), invent_message(), leave_voicemail(), meetme_menu_admin(), meetme_menu_admin_extended(), meetme_menu_normal(), minivm_greet_exec(), page_exec(), pbx_builtin_background(), pl_odtworz_plik(), play_and_wait(), play_file(), play_record_review(), playback_exec(), privacy_exec(), record_exec(), retrydial_exec(), s_streamwait3(), say_character_str_full(), say_digit_str_full(), say_money_str_full(), say_phonetic_str_full(), select_item_menu(), setup_privacy_args(), vm_authenticate(), and wait_file().
 {
    int res;
    res = waitstream_core(c, breakon, NULL, NULL, 0, -1, -1, NULL, NULL /* no callback */);
    return sanitize_waitstream_return(res);
 }
ast_waitstream_exten()
int ast_waitstream_exten (struct ast_channel * c, const char * context)
Waits for a stream to stop or digit matching a valid one digit exten to be pressed.
Parameters
c channel to waitstream on
context string of context to match digits to break upon Begins playback of a stream... Wait for a stream to stop or for any one of a valid extension digit to arrive,
Return values
0 if the stream finishes.
the character if it was interrupted.
-1 on error.
Definition at line 1795 of file file.c.
References ast_channel_context(), NULL, sanitize_waitstream_return(), and waitstream_core().
Referenced by pbx_builtin_background().
 {
    int res;
    /* Waitstream, with return in the case of a valid 1 digit extension */
    /* in the current or specified context being pressed */
    if (!context)
       context = ast_channel_context(c);
    res = waitstream_core(c, NULL, NULL, NULL, 0,
       -1, -1, context, NULL /* no callback */);
    return sanitize_waitstream_return(res);
 }
ast_waitstream_fr()
int ast_waitstream_fr (struct ast_channel * c, const char * breakon, const char * forward, const char * rewind, int ms)
Same as waitstream but allows stream to be forwarded or rewound.
Parameters
c channel to waitstream on
breakon string of DTMF digits to break upon
forward DTMF digit to fast forward upon
rewind DTMF digit to rewind upon
ms How many miliseconds to skip forward/back Begins playback of a stream... Wait for a stream to stop or for any one of a given digit to arrive,
Return values
0 if the stream finishes.
the character if it was interrupted,
the value of the control frame if it was interrupted by some other party,
-1 on error.
Examples:
/usr/src/asterisk-18.5.0/main/app.c.
Definition at line 1745 of file file.c.
References NULL, and waitstream_core().
Referenced by control_streamfile().
 {
    return waitstream_core(c, breakon, forward, reverse, ms,
       -1 /* no audiofd */, -1 /* no cmdfd */, NULL /* no context */, NULL /* no callback */);
 }
ast_waitstream_fr_w_cb()
int ast_waitstream_fr_w_cb (struct ast_channel * c, const char * breakon, const char * forward, const char * rewind, int ms, ast_waitstream_fr_cb cb)
Same as waitstream_fr but allows a callback to be alerted when a user fastforwards or rewinds the file.
Parameters
c channel to waitstream on
breakon string of DTMF digits to break upon
forward DTMF digit to fast forward upon
rewind DTMF digit to rewind upon
ms How many milliseconds to skip forward/back
cb to call when rewind or fastfoward occurs. Begins playback of a stream... Wait for a stream to stop or for any one of a given digit to arrive,
Return values
0 if the stream finishes.
the character if it was interrupted,
the value of the control frame if it was interrupted by some other party,
-1 on error.
Examples:
/usr/src/asterisk-18.5.0/main/app.c.
Definition at line 1734 of file file.c.
References NULL, and waitstream_core().
Referenced by control_streamfile().
 {
    return waitstream_core(c, breakon, forward, reverse, ms,
       -1 /* no audiofd */, -1 /* no cmdfd */, NULL /* no context */, cb);
 }
ast_waitstream_full()
int ast_waitstream_full (struct ast_channel * c, const char * breakon, int audiofd, int monfd)
Same as waitstream, but with audio output to fd and monitored fd checking.
Returns
1 if monfd is ready for reading
Definition at line 1785 of file file.c.
References NULL, sanitize_waitstream_return(), and waitstream_core().
Referenced by ast_readstring_full(), ast_say_enumeration_full_da(), ast_say_enumeration_full_de(), ast_say_enumeration_full_en(), ast_say_enumeration_full_he(), ast_say_enumeration_full_is(), ast_say_enumeration_full_vi(), ast_say_number_full_cs(), ast_say_number_full_da(), ast_say_number_full_de(), ast_say_number_full_en(), ast_say_number_full_en_GB(), ast_say_number_full_es(), ast_say_number_full_fr(), ast_say_number_full_gr(), ast_say_number_full_he(), ast_say_number_full_hu(), ast_say_number_full_is(), ast_say_number_full_it(), ast_say_number_full_ja(), ast_say_number_full_ka(), ast_say_number_full_nl(), ast_say_number_full_no(), ast_say_number_full_pt(), ast_say_number_full_ru(), ast_say_number_full_se(), ast_say_number_full_th(), ast_say_number_full_ur(), ast_say_number_full_vi(), ast_say_number_full_zh(), handle_getoption(), handle_streamfile(), pl_odtworz_plik(), s_streamwait3(), say_character_str_full(), say_digit_str_full(), say_money_str_full(), and say_phonetic_str_full().
 {
    int res;
    res = waitstream_core(c, breakon, NULL, NULL, 0,
       audiofd, cmdfd, NULL /* no context */, NULL /* no callback */);
    return sanitize_waitstream_return(res);
 }
ast_writefile()
struct ast_filestream* ast_writefile (const char * filename, const char * type, const char * comment, int flags, int check, mode_t mode)
Starts writing a file.
Parameters
filename the name of the file to write to
type format of file you wish to write out to
comment comment to go with
flags output file flags
check (unimplemented, hence negligible)
mode Open mode Create an outgoing file stream. oflags are flags for the open() command, and if check is non-zero, then it will not write a file if there are any files that start with that name and have an extension Please note, this is a blocking function. Program execution will not return until ast_waitstream completes it's execution.
Return values
a struct ast_filestream on success.
NULL on failure.
Examples:
/usr/src/asterisk-18.5.0/main/app.c.
Definition at line 1361 of file file.c.
References ast_closestream(), ast_free, ast_log, ast_malloc, ast_opt_cache_record_files, AST_RWLIST_RDLOCK, AST_RWLIST_TRAVERSE, AST_RWLIST_UNLOCK, ast_strdup, buf, build_filename(), c, errno, ast_format_def::exts, exts_compare, ast_filestream::f, ast_filestream::filename, ast_filestream::flags, ast_filestream::fmt, get_filestream(), LOG_WARNING, ast_filestream::mode, NULL, ast_filestream::realfilename, record_cache_dir, rewrite_wrapper(), ast_format_def::seek, ast_filestream::trans, ast_filestream::vfs, and ast_filestream::write_buffer.
Referenced by __ast_play_and_record(), ast_monitor_start(), ast_writestream(), dictate_exec(), handle_cli_file_convert(), handle_recordfile(), mixmonitor_save_prep(), record_exec(), and recordthread().
 {
    int fd, myflags = 0;
    /* compiler claims this variable can be used before initialization... */
    FILE *bfile = NULL;
    struct ast_format_def *f;
    struct ast_filestream *fs = NULL;
    char *buf = NULL;
    size_t size = 0;
    int format_found = 0;
    AST_RWLIST_RDLOCK(&formats);
    /* set the O_TRUNC flag if and only if there is no O_APPEND specified */
    /* We really can't use O_APPEND as it will break WAV header updates */
    if (flags & O_APPEND) {
       flags &= ~O_APPEND;
    } else {
       myflags = O_TRUNC;
    }
    myflags |= O_WRONLY | O_CREAT;
    /* XXX need to fix this - we should just do the fopen,
     * not open followed by fdopen()
     */
    AST_RWLIST_TRAVERSE(&formats, f, list) {
       char *fn, *orig_fn = NULL;
       if (fs)
          break;
       if (!exts_compare(f->exts, type))
          continue;
       else
          format_found = 1;
       fn = build_filename(filename, type);
       if (!fn) {
          continue;
       }
       fd = open(fn, flags | myflags, mode);
       if (fd > -1) {
          /* fdopen() the resulting file stream */
          bfile = fdopen(fd, ((flags | myflags) & O_RDWR) ? "w+" : "w");
          if (!bfile) {
             ast_log(LOG_WARNING, "Whoa, fdopen failed: %s!\n", strerror(errno));
             close(fd);
             fd = -1;
          }
       }
       if (ast_opt_cache_record_files && (fd > -1)) {
          char *c;
          fclose(bfile); /* this also closes fd */
          /*
            We touch orig_fn just as a place-holder so other things (like vmail) see the file is there.
            What we are really doing is writing to record_cache_dir until we are done then we will mv the file into place.
          */
          orig_fn = ast_strdup(fn);
          for (c = fn; *c; c++)
             if (*c == '/')
                *c = '_';
          size = strlen(fn) + strlen(record_cache_dir) + 2;
          buf = ast_malloc(size);
          strcpy(buf, record_cache_dir);
          strcat(buf, "/");
          strcat(buf, fn);
          ast_free(fn);
          fn = buf;
          fd = open(fn, flags | myflags, mode);
          if (fd > -1) {
             /* fdopen() the resulting file stream */
             bfile = fdopen(fd, ((flags | myflags) & O_RDWR) ? "w+" : "w");
             if (!bfile) {
                ast_log(LOG_WARNING, "Whoa, fdopen failed: %s!\n", strerror(errno));
                close(fd);
                fd = -1;
             }
          }
       }
       if (fd > -1) {
          errno = 0;
          fs = get_filestream(f, bfile);
          if (fs) {
             if ((fs->write_buffer = ast_malloc(32768))) {
                setvbuf(fs->f, fs->write_buffer, _IOFBF, 32768);
             }
          }
          if (!fs || rewrite_wrapper(fs, comment)) {
             ast_log(LOG_WARNING, "Unable to rewrite %s\n", fn);
             close(fd);
             if (orig_fn) {
                unlink(fn);
                unlink(orig_fn);
                ast_free(orig_fn);
             }
             if (fs) {
                ast_closestream(fs);
                fs = NULL;
             }
             /*
              * 'fn' was has either been allocated from build_filename, or that was freed
              * and now 'fn' points to memory allocated for 'buf'. Either way the memory
              * now needs to be released.
              */
             ast_free(fn);
             continue;
          }
          fs->trans = NULL;
          fs->fmt = f;
          fs->flags = flags;
          fs->mode = mode;
          if (orig_fn) {
             fs->realfilename = orig_fn;
             fs->filename = fn;
             /*
              * The above now manages the memory allocated for 'orig_fn' and 'fn', so
              * set them to NULL, so they don't get released at the end of the loop.
              */
             orig_fn = NULL;
             fn = NULL;
          } else {
             fs->realfilename = NULL;
             fs->filename = ast_strdup(filename);
          }
          fs->vfs = NULL;
          /* If truncated, we'll be at the beginning; if not truncated, then append */
          f->seek(fs, 0, SEEK_END);
       } else if (errno != EEXIST) {
          ast_log(LOG_WARNING, "Unable to open file %s: %s\n", fn, strerror(errno));
          if (orig_fn)
             unlink(orig_fn);
       }
       /* Free 'fn', or if 'fn' points to 'buf' then free 'buf' */
       ast_free(fn);
       ast_free(orig_fn);
    }
    AST_RWLIST_UNLOCK(&formats);
    if (!format_found)
       ast_log(LOG_WARNING, "No such format '%s'\n", type);
    return fs;
 }
ast_writestream()
int ast_writestream (struct ast_filestream * fs, struct ast_frame * f)
Writes a frame to a stream.
Parameters
fs filestream to write to
f frame to write to the filestream Send a frame to a filestream – note: does NOT free the frame, call ast_frfree manually
Return values
0 on success.
-1 on failure.
Examples:
/usr/src/asterisk-18.5.0/main/app.c.
Definition at line 209 of file file.c.
References ao2_replace, ast_debug, ast_format_cmp(), AST_FORMAT_CMP_EQUAL, AST_FORMAT_CMP_NOT_EQUAL, ast_format_get_name(), ast_format_get_type(), AST_FRAME_VIDEO, AST_FRAME_VOICE, ast_frfree, AST_LIST_NEXT, ast_log, AST_MEDIA_TYPE_AUDIO, ast_translate(), ast_translator_build_path(), ast_translator_free_path(), ast_writefile(), ast_filestream::filename, ast_filestream::flags, ast_filestream::fmt, ast_format_def::format, ast_frame_subclass::format, ast_frame::frametype, ast_filestream::lastwriteformat, LOG_WARNING, ast_filestream::mode, ast_format_def::name, NULL, ast_frame::subclass, ast_filestream::trans, type, ast_filestream::vfs, and ast_format_def::write.
Referenced by __ast_play_and_record(), __ast_read(), ast_write_stream(), dictate_exec(), handle_cli_file_convert(), handle_recordfile(), mixmonitor_thread(), record_exec(), and recordthread().
 {
    int res = -1;
    if (f->frametype == AST_FRAME_VIDEO) {
       if (ast_format_get_type(fs->fmt->format) == AST_MEDIA_TYPE_AUDIO) {
          /* This is the audio portion.  Call the video one... */
          if (!fs->vfs && fs->filename) {
             const char *type = ast_format_get_name(f->subclass.format);
             fs->vfs = ast_writefile(fs->filename, type, NULL, fs->flags, 0, fs->mode);
             ast_debug(1, "Opened video output file\n");
          }
          if (fs->vfs)
             return ast_writestream(fs->vfs, f);
          /* else ignore */
          return 0;
       }
    } else if (f->frametype != AST_FRAME_VOICE) {
       ast_log(LOG_WARNING, "Tried to write non-voice frame\n");
       return -1;
    }
    if (ast_format_cmp(f->subclass.format, fs->fmt->format) != AST_FORMAT_CMP_NOT_EQUAL) {
       res =  fs->fmt->write(fs, f);
       if (res < 0)
          ast_log(LOG_WARNING, "Natural write failed\n");
       else if (res > 0)
          ast_log(LOG_WARNING, "Huh??\n");
    } else {
       /* XXX If they try to send us a type of frame that isn't the normal frame, and isn't
              the one we've setup a translator for, we do the "wrong thing" XXX */
       if (fs->trans && (ast_format_cmp(f->subclass.format, fs->lastwriteformat) != AST_FORMAT_CMP_EQUAL)) {
          ast_translator_free_path(fs->trans);
          fs->trans = NULL;
       }
       if (!fs->trans) {
          fs->trans = ast_translator_build_path(fs->fmt->format, f->subclass.format);
       }
       if (!fs->trans) {
          ast_log(LOG_WARNING, "Unable to translate to format %s, source format %s\n",
             fs->fmt->name, ast_format_get_name(f->subclass.format));
       } else {
          struct ast_frame *trf;
          ao2_replace(fs->lastwriteformat, f->subclass.format);
          /* Get the translated frame but don't consume the original in case they're using it on another stream */
          if ((trf = ast_translate(fs->trans, f, 0))) {
             struct ast_frame *cur;
             /* the translator may have returned multiple frames, so process them */
             for (cur = trf; cur; cur = AST_LIST_NEXT(cur, frame_list)) {
                if ((res = fs->fmt->write(fs, trf))) {
                   ast_log(LOG_WARNING, "Translated frame write failed\n");
                   break;
                }
             }
             ast_frfree(trf);
          } else {
             res = 0;
          }
       }
    }
    return res;
 }