Asterisk - The Open Source Telephony Project: filter.c File Reference
filter.c File Reference
#include "iLBC_define.h"
Functions
void AllPoleFilter (float *InOut, float *Coef, int lengthInOut, int orderCoef)
void AllZeroFilter (float *In, float *Coef, int lengthInOut, int orderCoef, float *Out)
void DownSample (float *In, float *Coef, int lengthIn, float *state, float *Out)
void ZeroPoleFilter (float *In, float *ZeroCoef, float *PoleCoef, int lengthInOut, int orderCoef, float *Out)
Function Documentation
AllPoleFilter()
void AllPoleFilter (float * InOut, float * Coef, int lengthInOut, int orderCoef)
Definition at line 19 of file filter.c.
Referenced by AbsQuantW(), iCBSearch(), and ZeroPoleFilter().
     {
        int n,k;
        for(n=0;n<lengthInOut;n++){
            for(k=1;k<=orderCoef;k++){
                *InOut -= Coef[k]*InOut[-k];
            }
            InOut++;
        }
    }
AllZeroFilter()
void AllZeroFilter (float * In, float * Coef, int lengthInOut, int orderCoef, float * Out)
Definition at line 52 of file filter.c.
Referenced by ZeroPoleFilter().
     {
        int n,k;
        for(n=0;n<lengthInOut;n++){
            *Out = Coef[0]*In[0];
            for(k=1;k<=orderCoef;k++){
                *Out += Coef[k]*In[-k];
            }
            Out++;
            In++;
        }
    }
DownSample()
void DownSample (float * In, float * Coef, int lengthIn, float * state, float * Out)
Definition at line 110 of file filter.c.
References DELAY_DS, FACTOR_DS, FILTERORDER_DS, and stop.
Referenced by enhancerInterface().
     {
        float   o;
        float *Out_ptr = Out;
        float *Coef_ptr, *In_ptr;
        float *state_ptr;
        int i, j, stop;
        /* LP filter and decimate at the same time */
        for (i = DELAY_DS; i < lengthIn; i+=FACTOR_DS)
        {
            Coef_ptr = &Coef[0];
            In_ptr = &In[i];
            state_ptr = &state[FILTERORDER_DS-2];
            o = (float)0.0;
            stop = (i < FILTERORDER_DS) ? i + 1 : FILTERORDER_DS;
            for (j = 0; j < stop; j++)
            {
                o += *Coef_ptr++ * (*In_ptr--);
            }
            for (j = i + 1; j < FILTERORDER_DS; j++)
            {
                o += *Coef_ptr++ * (*state_ptr--);
            }
            *Out_ptr++ = o;
        }
        /* Get the last part (use zeros as input for the future) */
        for (i=(lengthIn+FACTOR_DS); i<(lengthIn+DELAY_DS);
                i+=FACTOR_DS) {
            o=(float)0.0;
            if (i<lengthIn) {
                Coef_ptr = &Coef[0];
                In_ptr = &In[i];
                for (j=0; j<FILTERORDER_DS; j++) {
                        o += *Coef_ptr++ * (*Out_ptr--);
                }
            } else {
                Coef_ptr = &Coef[i-lengthIn];
                In_ptr = &In[lengthIn-1];
                for (j=0; j<FILTERORDER_DS-(i-lengthIn); j++) {
                        o += *Coef_ptr++ * (*In_ptr--);
                }
            }
            *Out_ptr++ = o;
        }
    }
ZeroPoleFilter()
void ZeroPoleFilter (float * In, float * ZeroCoef, float * PoleCoef, int lengthInOut, int orderCoef, float * Out)
Definition at line 80 of file filter.c.
References AllPoleFilter(), and AllZeroFilter().
Referenced by StateConstructW(), and StateSearchW().
     {
        AllZeroFilter(In,ZeroCoef,lengthInOut,orderCoef,Out);
        AllPoleFilter(Out,PoleCoef,lengthInOut,orderCoef);
    }