Asterisk - The Open Source Telephony Project: asterisk_processor Namespace Reference
asterisk_processor Namespace Reference
Data Structures
class AsteriskProcessor
class PathSegment
Functions
def simple_name (name)
def snakify (name)
def wikify (str)
Function Documentation
simple_name()
def asterisk_processor.simple_name (name)
Removes the {markers} from a path segement.
@param name: Swagger path segement, with {pathVar} markers.
Definition at line 34 of file asterisk_processor.py.
Referenced by PathSegment.get_child().
 def simple_name(name):
     """Removes the {markers} from a path segement.
     @param name: Swagger path segement, with {pathVar} markers.
     """
     if name.startswith('{') and name.endswith('}'):
         return name[1:-1]
     return name
snakify()
def asterisk_processor.snakify (name)
Helper to take a camelCase or dash-seperated name and make it
snake_case.
Definition at line 54 of file asterisk_processor.py.
Referenced by AsteriskProcessor.process_model(), AsteriskProcessor.process_operation(), AsteriskProcessor.process_parameter(), AsteriskProcessor.process_resource_api(), and AsteriskProcessor.process_type().
 def snakify(name):
     """Helper to take a camelCase or dash-seperated name and make it
     snake_case.
     """
     r = ''
     prior_lower = False
     for c in name:
         if c.isupper() and prior_lower:
             r += "_"
         if c is '-':
             c = '_'
         prior_lower = c.islower()
         r += c.lower()
     return r
wikify()
def asterisk_processor.wikify (str)
Escapes a string for the wiki.
@param str: String to escape
Definition at line 44 of file asterisk_processor.py.
Referenced by AsteriskProcessor.process_api(), AsteriskProcessor.process_model(), AsteriskProcessor.process_operation(), AsteriskProcessor.process_parameter(), AsteriskProcessor.process_property(), and AsteriskProcessor.process_type().
 def wikify(str):
     """Escapes a string for the wiki.
     @param str: String to escape
     """
     # Replace all line breaks with line feeds
     str = re.sub(r'<br\s*/?>', '\n', str)
     return re.sub(r'([{}\[\]])', r'\\\1', str)