Asterisk - The Open Source Telephony Project: pjsip_distributor.c File Reference
pjsip_distributor.c File Reference
#include "asterisk.h"
#include <pjsip.h>
#include "asterisk/res_pjsip.h"
#include "asterisk/acl.h"
#include "include/res_pjsip_private.h"
#include "asterisk/taskprocessor.h"
#include "asterisk/threadpool.h"
#include "asterisk/res_pjsip_cli.h"
Data Structures
struct distributor_dialog_data
struct unidentified_request
Macros
#define DEFAULT_SUSPECTS_BUCKETS 53
#define DIALOG_ASSOCIATIONS_BUCKETS 251
#define DISTRIBUTOR_POOL_SIZE 31
#define MAX_REALM_LENGTH 40
Functions
static struct ast_sip_auth * alloc_artificial_auth (char *default_realm)
static AO2_GLOBAL_OBJ_STATIC (artificial_auth)
static void apply_acls (pjsip_rx_data *rdata)
static int apply_endpoint_acl (pjsip_rx_data *rdata, struct ast_sip_endpoint *endpoint)
static int apply_endpoint_contact_acl (pjsip_rx_data *rdata, struct ast_sip_endpoint *endpoint)
struct ast_sip_endpoint * ast_pjsip_rdata_get_endpoint (pjsip_rx_data *rdata)
Get the looked-up endpoint on an out-of dialog request or response.
void ast_sip_destroy_distributor (void)
struct ast_sip_endpoint * ast_sip_dialog_get_endpoint (pjsip_dialog *dlg)
Get the endpoint associated with this dialog.
void ast_sip_dialog_set_endpoint (pjsip_dialog *dlg, struct ast_sip_endpoint *endpoint)
Set an endpoint on a SIP dialog so in-dialog requests do not undergo endpoint lookup.
void ast_sip_dialog_set_serializer (pjsip_dialog *dlg, struct ast_taskprocessor *serializer)
Set a serializer on a SIP dialog so requests and responses are automatically serialized.
struct ast_sip_auth * ast_sip_get_artificial_auth (void)
Retrieves a reference to the artificial auth.
struct ast_sip_endpoint * ast_sip_get_artificial_endpoint (void)
Retrieves a reference to the artificial endpoint.
struct ast_taskprocessor * ast_sip_get_distributor_serializer (pjsip_rx_data *rdata)
Determine the distributor serializer for the SIP message.
int ast_sip_initialize_distributor (void)
static pj_bool_t authenticate (pjsip_rx_data *rdata)
static int buf_hash (const char *pos, size_t len)
static int buf_hash_add (const char *pos, size_t len, int hash)
static void check_endpoint (pjsip_rx_data *rdata, struct unidentified_request *unid, const char *name)
static int clean_task (const void *data)
static struct ao2_container * cli_unid_get_container (const char *regex)
static const char * cli_unid_get_id (const void *obj)
static int cli_unid_iterate (void *container, ao2_callback_fn callback, void *args)
static int cli_unid_print_body (void *obj, void *arg, int flags)
static int cli_unid_print_header (void *obj, void *arg, int flags)
static void * cli_unid_retrieve_by_id (const char *id)
static int create_artificial_auth (void)
static int create_artificial_endpoint (void)
static int dialog_associations_cmp (void *obj, void *arg, int flags)
static int dialog_associations_hash (const void *obj, int flags)
static int distribute (void *data)
static pj_bool_t distributor (pjsip_rx_data *rdata)
static int distributor_pool_setup (void)
static void distributor_pool_shutdown (void)
static pj_bool_t endpoint_lookup (pjsip_rx_data *rdata)
static int expire_requests (void *object, void *arg, int flags)
static int extract_contact_addr (pjsip_contact_hdr *contact, struct ast_sockaddr **addrs)
static pjsip_dialog * find_dialog (pjsip_rx_data *rdata)
static struct ast_taskprocessor * find_request_serializer (pjsip_rx_data *rdata)
static void global_loaded (const char *object_type)
static void log_failed_request (pjsip_rx_data *rdata, char *msg, unsigned int count, unsigned int period)
static int pjstr_hash (pj_str_t *str)
static int pjstr_hash_add (pj_str_t *str, int hash)
static int prune_task (const void *data)
static pj_status_t record_serializer (pjsip_tx_data *tdata)
static int suspects_compare (void *obj, void *arg, int flags)
static int suspects_hash (const void *obj, int flags)
static int suspects_sort (const void *obj, const void *arg, int flags)
Variables
static struct ast_sip_endpoint * artificial_endpoint = NULL
static pjsip_module auth_mod
static struct ast_cli_entry cli_commands []
static struct ao2_container * dialog_associations
static pjsip_module distributor_mod
static struct ast_taskprocessor * distributor_pool [DISTRIBUTOR_POOL_SIZE]
static pjsip_module endpoint_mod
static struct ast_sorcery_observer global_observer
Observer which is used to update our interval and default_realm when the global setting changes.
static enum ast_sip_taskprocessor_overload_trigger overload_trigger
struct ast_sched_context * prune_context
struct ast_sip_cli_formatter_entry * unid_formatter
static unsigned int unidentified_count
static unsigned int unidentified_period
static unsigned int unidentified_prune_interval
static struct ao2_container * unidentified_requests
static int using_auth_username
Macro Definition Documentation
DEFAULT_SUSPECTS_BUCKETS
#define DEFAULT_SUSPECTS_BUCKETS 53
Definition at line 47 of file pjsip_distributor.c.
Referenced by ast_sip_initialize_distributor().
DIALOG_ASSOCIATIONS_BUCKETS
#define DIALOG_ASSOCIATIONS_BUCKETS 251
Definition at line 162 of file pjsip_distributor.c.
Referenced by ast_sip_initialize_distributor().
DISTRIBUTOR_POOL_SIZE
#define DISTRIBUTOR_POOL_SIZE 31
Number of serializers in pool if one not otherwise known. (Best if prime number)
Definition at line 63 of file pjsip_distributor.c.
MAX_REALM_LENGTH
#define MAX_REALM_LENGTH 40
Definition at line 45 of file pjsip_distributor.c.
Referenced by create_artificial_auth(), and global_loaded().
Function Documentation
alloc_artificial_auth()
static struct ast_sip_auth* alloc_artificial_auth (char * default_realm) static
Definition at line 594 of file pjsip_distributor.c.
References AO2_GLOBAL_OBJ_STATIC(), AST_SIP_AUTH_TYPE_ARTIFICIAL, ast_sip_get_sorcery(), ast_sorcery_alloc(), ast_string_field_set, ast_sip_auth::auth_pass, ast_sip_auth::auth_user, NULL, ast_sip_auth::realm, and ast_sip_auth::type.
Referenced by create_artificial_auth(), and global_loaded().
 {
    struct ast_sip_auth *fake_auth;
    fake_auth = ast_sorcery_alloc(ast_sip_get_sorcery(), SIP_SORCERY_AUTH_TYPE,
       "artificial");
    if (!fake_auth) {
       return NULL;
    }
    ast_string_field_set(fake_auth, realm, default_realm);
    ast_string_field_set(fake_auth, auth_user, "");
    ast_string_field_set(fake_auth, auth_pass, "");
    fake_auth->type = AST_SIP_AUTH_TYPE_ARTIFICIAL;
    return fake_auth;
 }
AO2_GLOBAL_OBJ_STATIC()
static AO2_GLOBAL_OBJ_STATIC (artificial_auth) static
Referenced by alloc_artificial_auth().
apply_acls()
static void apply_acls (pjsip_rx_data * rdata) static
Definition at line 701 of file pjsip_distributor.c.
References ao2_replace, apply_endpoint_acl(), apply_endpoint_contact_acl(), ast_debug, ast_sorcery_object_get_id(), and endpoint_mod.
Referenced by endpoint_lookup().
 {
    struct ast_sip_endpoint *endpoint;
    /* Is the endpoint allowed with the source or contact address? */
    endpoint = rdata->endpt_info.mod_data[endpoint_mod.id];
    if (endpoint != artificial_endpoint
       && (apply_endpoint_acl(rdata, endpoint)
          || apply_endpoint_contact_acl(rdata, endpoint))) {
       ast_debug(1, "Endpoint '%s' not allowed by ACL\n",
          ast_sorcery_object_get_id(endpoint));
       /* Replace the rdata endpoint with the artificial endpoint. */
       ao2_replace(rdata->endpt_info.mod_data[endpoint_mod.id], artificial_endpoint);
    }
 }
apply_endpoint_acl()
static int apply_endpoint_acl (pjsip_rx_data * rdata, struct ast_sip_endpoint * endpoint) static
Definition at line 807 of file pjsip_distributor.c.
References ast_sip_endpoint::acl, ast_acl_list_is_empty(), ast_apply_acl(), AST_SENSE_ALLOW, ast_sip_report_failed_acl(), ast_sockaddr_parse(), ast_sockaddr_set_port, log_failed_request(), and PARSE_PORT_FORBID.
Referenced by apply_acls(), and check_endpoint().
 {
    struct ast_sockaddr addr;
    if (ast_acl_list_is_empty(endpoint->acl)) {
       return 0;
    }
    memset(&addr, 0, sizeof(addr));
    ast_sockaddr_parse(&addr, rdata->pkt_info.src_name, PARSE_PORT_FORBID);
    ast_sockaddr_set_port(&addr, rdata->pkt_info.src_port);
    if (ast_apply_acl(endpoint->acl, &addr, "SIP ACL: ") != AST_SENSE_ALLOW) {
       log_failed_request(rdata, "Not match Endpoint ACL", 0, 0);
       ast_sip_report_failed_acl(endpoint, rdata, "not_match_endpoint_acl");
       return 1;
    }
    return 0;
 }
apply_endpoint_contact_acl()
static int apply_endpoint_contact_acl (pjsip_rx_data * rdata, struct ast_sip_endpoint * endpoint) static
Definition at line 845 of file pjsip_distributor.c.
References ast_acl_list_is_empty(), ast_apply_acl(), ast_free, AST_SENSE_ALLOW, ast_sip_report_failed_acl(), ast_sip_endpoint::contact_acl, extract_contact_addr(), if(), and log_failed_request().
Referenced by apply_acls(), and check_endpoint().
 {
    int num_contact_addrs;
    int forbidden = 0;
    struct ast_sockaddr *contact_addrs;
    int i;
    pjsip_contact_hdr *contact = (pjsip_contact_hdr *)&rdata->msg_info.msg->hdr;
    if (ast_acl_list_is_empty(endpoint->contact_acl)) {
       return 0;
    }
    while ((contact = pjsip_msg_find_hdr(rdata->msg_info.msg, PJSIP_H_CONTACT, contact->next))) {
       num_contact_addrs = extract_contact_addr(contact, &contact_addrs);
       if (num_contact_addrs <= 0) {
          continue;
       }
       for (i = 0; i < num_contact_addrs; ++i) {
          if (ast_apply_acl(endpoint->contact_acl, &contact_addrs[i], "SIP Contact ACL: ") != AST_SENSE_ALLOW) {
             log_failed_request(rdata, "Not match Endpoint Contact ACL", 0, 0);
             ast_sip_report_failed_acl(endpoint, rdata, "not_match_endpoint_contact_acl");
             forbidden = 1;
             break;
          }
       }
       ast_free(contact_addrs);
       if (forbidden) {
          /* No use checking other contacts if we already have failed ACL check */
          break;
       }
    }
    return forbidden;
 }
ast_pjsip_rdata_get_endpoint()
struct ast_sip_endpoint* ast_pjsip_rdata_get_endpoint (pjsip_rx_data * rdata)
Get the looked-up endpoint on an out-of dialog request or response.
The function may ONLY be called on out-of-dialog requests or responses. For in-dialog requests and responses, it is required that the user of the dialog has the looked-up endpoint stored locally.
This function should never return NULL if the message is out-of-dialog. It will always return NULL if the message is in-dialog.
This function will increase the reference count of the returned endpoint by one. Release your reference using the ao2_ref function when finished.
Parameters
rdata Out-of-dialog request or response
Returns
The looked up endpoint
Definition at line 969 of file pjsip_distributor.c.
References ao2_ref, and endpoint_mod.
Referenced by authenticate(), handle_new_invite_request(), nat_on_rx_message(), options_on_rx_request(), pubsub_on_rx_mwi_notify_request(), pubsub_on_rx_publish_request(), pubsub_on_rx_subscribe_request(), registrar_on_rx_request(), rx_data_to_ast_msg(), send_options_response(), send_response(), and supplement_on_rx_request().
 {
    struct ast_sip_endpoint *endpoint = rdata->endpt_info.mod_data[endpoint_mod.id];
    if (endpoint) {
       ao2_ref(endpoint, +1);
    }
    return endpoint;
 }
ast_sip_destroy_distributor()
void ast_sip_destroy_distributor (void)
Definition at line 1334 of file pjsip_distributor.c.
References ao2_cleanup, ao2_global_obj_release, ARRAY_LEN, ast_cli_unregister_multiple(), ast_sched_context_destroy(), ast_sip_get_sorcery(), ast_sip_unregister_cli_formatter(), ast_sip_unregister_service(), ast_sorcery_observer_remove(), auth_mod, distributor_mod, distributor_pool_shutdown(), and endpoint_mod.
Referenced by ast_sip_initialize_distributor(), and unload_pjsip().
 {
    ast_cli_unregister_multiple(cli_commands, ARRAY_LEN(cli_commands));
    ast_sip_unregister_cli_formatter(unid_formatter);
    ast_sip_unregister_service(&auth_mod);
    ast_sip_unregister_service(&endpoint_mod);
    ast_sip_unregister_service(&distributor_mod);
    ao2_global_obj_release(artificial_auth);
    ao2_cleanup(artificial_endpoint);
    ast_sorcery_observer_remove(ast_sip_get_sorcery(), "global", &global_observer);
    if (prune_context) {
       ast_sched_context_destroy(prune_context);
    }
    distributor_pool_shutdown();
    ao2_cleanup(dialog_associations);
    ao2_cleanup(unidentified_requests);
 }
ast_sip_get_artificial_auth()
struct ast_sip_auth* ast_sip_get_artificial_auth (void)
Retrieves a reference to the artificial auth.
Return values
The artificial auth
Definition at line 631 of file pjsip_distributor.c.
References ao2_global_obj_ref.
Referenced by digest_check_auth(), and global_loaded().
 {
    return ao2_global_obj_ref(artificial_auth);
 }
ast_sip_get_artificial_endpoint()
struct ast_sip_endpoint* ast_sip_get_artificial_endpoint (void)
Retrieves a reference to the artificial endpoint.
Return values
The artificial endpoint
Definition at line 654 of file pjsip_distributor.c.
References ao2_ref, and artificial_endpoint.
Referenced by digest_check_auth(), digest_requires_authentication(), endpoint_lookup(), and get_account_id().
 {
    ao2_ref(artificial_endpoint, +1);
    return artificial_endpoint;
 }
ast_sip_initialize_distributor()
int ast_sip_initialize_distributor (void)
Definition at line 1260 of file pjsip_distributor.c.
References AO2_ALLOC_OPT_LOCK_NOLOCK, AO2_ALLOC_OPT_LOCK_RWLOCK, ao2_alloc_options, ao2_container_alloc_hash, ARRAY_LEN, ast_cli_register_multiple, ast_log, ast_sched_context_create(), ast_sched_start_thread(), ast_sip_destroy_distributor(), ast_sip_get_sorcery(), ast_sip_register_cli_formatter(), ast_sip_register_service(), ast_sorcery_observer_add(), ast_sorcery_reload_object(), auth_mod, cli_unid_get_container(), cli_unid_get_id(), cli_unid_iterate(), cli_unid_print_body(), cli_unid_print_header(), cli_unid_retrieve_by_id(), create_artificial_auth(), create_artificial_endpoint(), DEFAULT_SUSPECTS_BUCKETS, DIALOG_ASSOCIATIONS_BUCKETS, dialog_associations_cmp(), dialog_associations_hash(), distributor_mod, distributor_pool_setup(), endpoint_mod, ast_sip_cli_formatter_entry::get_container, ast_sip_cli_formatter_entry::get_id, ast_sip_cli_formatter_entry::iterate, LOG_ERROR, ast_sip_cli_formatter_entry::name, NULL, ast_sip_cli_formatter_entry::print_body, ast_sip_cli_formatter_entry::print_header, ast_sip_cli_formatter_entry::retrieve_by_id, suspects_compare(), and suspects_hash().
Referenced by load_module().
 {
    unidentified_requests = ao2_container_alloc_hash(AO2_ALLOC_OPT_LOCK_RWLOCK, 0,
       DEFAULT_SUSPECTS_BUCKETS, suspects_hash, NULL, suspects_compare);
    if (!unidentified_requests) {
       return -1;
    }
    dialog_associations = ao2_container_alloc_hash(AO2_ALLOC_OPT_LOCK_RWLOCK, 0,
       DIALOG_ASSOCIATIONS_BUCKETS, dialog_associations_hash, NULL,
       dialog_associations_cmp);
    if (!dialog_associations) {
       ast_sip_destroy_distributor();
       return -1;
    }
    if (distributor_pool_setup()) {
       ast_sip_destroy_distributor();
       return -1;
    }
    prune_context = ast_sched_context_create();
    if (!prune_context) {
       ast_sip_destroy_distributor();
       return -1;
    }
    if (ast_sched_start_thread(prune_context)) {
       ast_sip_destroy_distributor();
       return -1;
    }
    ast_sorcery_observer_add(ast_sip_get_sorcery(), "global", &global_observer);
    ast_sorcery_reload_object(ast_sip_get_sorcery(), "global");
    if (create_artificial_endpoint() || create_artificial_auth()) {
       ast_sip_destroy_distributor();
       return -1;
    }
    if (ast_sip_register_service(&distributor_mod)) {
       ast_sip_destroy_distributor();
       return -1;
    }
    if (ast_sip_register_service(&endpoint_mod)) {
       ast_sip_destroy_distributor();
       return -1;
    }
    if (ast_sip_register_service(&auth_mod)) {
       ast_sip_destroy_distributor();
       return -1;
    }
    unid_formatter = ao2_alloc_options(sizeof(struct ast_sip_cli_formatter_entry), NULL,
       AO2_ALLOC_OPT_LOCK_NOLOCK);
    if (!unid_formatter) {
       ast_sip_destroy_distributor();
       ast_log(LOG_ERROR, "Unable to allocate memory for unid_formatter\n");
       return -1;
    }
    unid_formatter->name = "unidentified_request";
    unid_formatter->print_header = cli_unid_print_header;
    unid_formatter->print_body = cli_unid_print_body;
    unid_formatter->get_container = cli_unid_get_container;
    unid_formatter->iterate = cli_unid_iterate;
    unid_formatter->get_id = cli_unid_get_id;
    unid_formatter->retrieve_by_id = cli_unid_retrieve_by_id;
    ast_sip_register_cli_formatter(unid_formatter);
    ast_cli_register_multiple(cli_commands, ARRAY_LEN(cli_commands));
    return 0;
 }
authenticate()
static pj_bool_t authenticate (pjsip_rx_data * rdata) static
Definition at line 880 of file pjsip_distributor.c.
References ao2_cleanup, ao2_find, ao2_ref, ao2_unlink, ast_assert, ast_pjsip_rdata_get_endpoint(), AST_SIP_AUTHENTICATION_CHALLENGE, AST_SIP_AUTHENTICATION_ERROR, AST_SIP_AUTHENTICATION_FAILED, AST_SIP_AUTHENTICATION_SUCCESS, ast_sip_check_authentication(), ast_sip_get_pjsip_endpoint(), ast_sip_report_auth_challenge_sent(), ast_sip_report_auth_failed_challenge_response(), ast_sip_report_auth_success(), ast_sip_requires_authentication(), log_failed_request(), NULL, OBJ_SEARCH_KEY, and RAII_VAR.
 {
    RAII_VAR(struct ast_sip_endpoint *, endpoint, ast_pjsip_rdata_get_endpoint(rdata), ao2_cleanup);
    int is_ack = rdata->msg_info.msg->line.req.method.id == PJSIP_ACK_METHOD;
    ast_assert(endpoint != NULL);
    if (is_ack) {
       return PJ_FALSE;
    }
    if (ast_sip_requires_authentication(endpoint, rdata)) {
       pjsip_tx_data *tdata;
       struct unidentified_request *unid;
       pjsip_endpt_create_response(ast_sip_get_pjsip_endpoint(), rdata, 401, NULL, &tdata);
       switch (ast_sip_check_authentication(endpoint, rdata, tdata)) {
       case AST_SIP_AUTHENTICATION_CHALLENGE:
          /* Send the 401 we created for them */
          ast_sip_report_auth_challenge_sent(endpoint, rdata, tdata);
          if (pjsip_endpt_send_response2(ast_sip_get_pjsip_endpoint(), rdata, tdata, NULL, NULL) != PJ_SUCCESS) {
             pjsip_tx_data_dec_ref(tdata);
          }
          return PJ_TRUE;
       case AST_SIP_AUTHENTICATION_SUCCESS:
          /* See note in endpoint_lookup about not holding an unnecessary write lock */
          unid = ao2_find(unidentified_requests, rdata->pkt_info.src_name, OBJ_SEARCH_KEY);
          if (unid) {
             ao2_unlink(unidentified_requests, unid);
             ao2_ref(unid, -1);
          }
          ast_sip_report_auth_success(endpoint, rdata);
          break;
       case AST_SIP_AUTHENTICATION_FAILED:
          log_failed_request(rdata, "Failed to authenticate", 0, 0);
          ast_sip_report_auth_failed_challenge_response(endpoint, rdata);
          if (pjsip_endpt_send_response2(ast_sip_get_pjsip_endpoint(), rdata, tdata, NULL, NULL) != PJ_SUCCESS) {
             pjsip_tx_data_dec_ref(tdata);
          }
          return PJ_TRUE;
       case AST_SIP_AUTHENTICATION_ERROR:
          log_failed_request(rdata, "Error to authenticate", 0, 0);
          ast_sip_report_auth_failed_challenge_response(endpoint, rdata);
          pjsip_tx_data_dec_ref(tdata);
          pjsip_endpt_respond_stateless(ast_sip_get_pjsip_endpoint(), rdata, 500, NULL, NULL, NULL);
          return PJ_TRUE;
       }
       pjsip_tx_data_dec_ref(tdata);
    } else if (endpoint == artificial_endpoint) {
       /* Uh. Oh.  The artificial endpoint couldn't challenge so block the request. */
       pjsip_endpt_respond_stateless(ast_sip_get_pjsip_endpoint(), rdata, 500, NULL, NULL, NULL);
       return PJ_TRUE;
    }
    return PJ_FALSE;
 }
buf_hash()
static int buf_hash (const char * pos, size_t len) static
Definition at line 210 of file pjsip_distributor.c.
References buf_hash_add().
Referenced by dialog_associations_hash().
 {
    return buf_hash_add(pos, len, 5381);
 }
buf_hash_add()
static int buf_hash_add (const char * pos, size_t len, int hash) static
Definition at line 184 of file pjsip_distributor.c.
Referenced by buf_hash(), and pjstr_hash_add().
 {
    while (len--) {
       hash = hash * 33 ^ *pos++;
    }
    return hash;
 }
check_endpoint()
static void check_endpoint (pjsip_rx_data * rdata, struct unidentified_request * unid, const char * name) static
Definition at line 683 of file pjsip_distributor.c.
References ao2_unlock, ao2_wrlock, apply_endpoint_acl(), apply_endpoint_contact_acl(), ast_sip_report_invalid_endpoint(), ast_tvdiff_ms(), ast_tvnow(), unidentified_request::count, unidentified_request::first_seen, log_failed_request(), unidentified_count, and unidentified_period.
Referenced by endpoint_lookup().
 {
    int64_t ms = ast_tvdiff_ms(ast_tvnow(), unid->first_seen);
    ao2_wrlock(unid);
    unid->count++;
    if (ms < (unidentified_period * 1000) && unid->count >= unidentified_count) {
       log_failed_request(rdata, "No matching endpoint found", unid->count, ms);
       ast_sip_report_invalid_endpoint(name, rdata);
    }
    ao2_unlock(unid);
 }
clean_task()
static int clean_task (const void * data) static
Definition at line 1160 of file pjsip_distributor.c.
Referenced by global_loaded().
 {
    return 0;
 }
cli_unid_get_container()
static struct ao2_container* cli_unid_get_container (const char * regex) static
Definition at line 1051 of file pjsip_distributor.c.
References AO2_ALLOC_OPT_LOCK_NOLOCK, ao2_container_alloc_list, ao2_container_dup(), ao2_ref, NULL, suspects_compare(), and suspects_sort().
Referenced by ast_sip_initialize_distributor().
 {
    struct ao2_container *s_container;
    s_container = ao2_container_alloc_list(AO2_ALLOC_OPT_LOCK_NOLOCK, 0,
       suspects_sort, suspects_compare);
    if (!s_container) {
       return NULL;
    }
    if (ao2_container_dup(s_container, unidentified_requests, 0)) {
       ao2_ref(s_container, -1);
       return NULL;
    }
    return s_container;
 }
cli_unid_get_id()
static const char* cli_unid_get_id (const void * obj) static
Definition at line 1081 of file pjsip_distributor.c.
References unidentified_request::src_name.
Referenced by ast_sip_initialize_distributor().
 {
    const struct unidentified_request *unid = obj;
    return unid->src_name;
 }
cli_unid_iterate()
static int cli_unid_iterate (void * container, ao2_callback_fn callback, void * args) static
Definition at line 1069 of file pjsip_distributor.c.
References ao2_callback.
Referenced by ast_sip_initialize_distributor().
 {
    ao2_callback(container, 0, callback, args);
    return 0;
 }
cli_unid_print_body()
static int cli_unid_print_body (void * obj, void * arg, int flags) static
Definition at line 1105 of file pjsip_distributor.c.
References ast_assert, ast_str_append(), ast_tvdiff_ms(), ast_tvnow(), CLI_INDENT_TO_SPACES, CLI_LAST_TABSTOP, context, unidentified_request::count, unidentified_request::first_seen, ast_sip_cli_context::indent_level, NULL, ast_sip_cli_context::output_buffer, and unidentified_request::src_name.
Referenced by ast_sip_initialize_distributor().
 {
    struct unidentified_request *unid = obj;
    struct ast_sip_cli_context *context = arg;
    int indent;
    int flexwidth;
    int64_t ms = ast_tvdiff_ms(ast_tvnow(), unid->first_seen);
    ast_assert(context->output_buffer != NULL);
    indent = CLI_INDENT_TO_SPACES(context->indent_level);
    flexwidth = CLI_LAST_TABSTOP - 4;
    ast_str_append(&context->output_buffer, 0, "%*s:  %-*.*s  %7d %10.3f\n",
       indent,
       "Request",
       flexwidth, flexwidth,
       unid->src_name, unid->count,  ms / 1000.0);
    return 0;
 }
cli_unid_print_header()
static int cli_unid_print_header (void * obj, void * arg, int flags) static
Definition at line 1088 of file pjsip_distributor.c.
References ao2_cleanup, ast_assert, ast_str_append(), CLI_HEADER_FILLER, CLI_INDENT_TO_SPACES, CLI_LAST_TABSTOP, context, ast_sip_cli_context::indent_level, NULL, ast_sip_cli_context::output_buffer, and RAII_VAR.
Referenced by ast_sip_initialize_distributor().
 {
    struct ast_sip_cli_context *context = arg;
    RAII_VAR(struct ast_sip_cli_formatter_entry *, formatter_entry, NULL, ao2_cleanup);
    int indent = CLI_INDENT_TO_SPACES(context->indent_level);
    int filler = CLI_LAST_TABSTOP - indent - 7;
    ast_assert(context->output_buffer != NULL);
    ast_str_append(&context->output_buffer, 0,
       "%*s:  <IP Address%*.*s>  <Count> <Age(sec)>\n",
       indent, "Request", filler, filler, CLI_HEADER_FILLER);
    return 0;
 }
cli_unid_retrieve_by_id()
static void* cli_unid_retrieve_by_id (const char * id) static
Definition at line 1076 of file pjsip_distributor.c.
References ao2_find, and OBJ_SEARCH_KEY.
Referenced by ast_sip_initialize_distributor().
 {
    return ao2_find(unidentified_requests, id, OBJ_SEARCH_KEY);
 }
create_artificial_auth()
static int create_artificial_auth (void) static
Definition at line 614 of file pjsip_distributor.c.
References alloc_artificial_auth(), ao2_global_obj_replace_unref, ao2_ref, ast_log, ast_sip_get_default_realm(), default_realm, LOG_ERROR, and MAX_REALM_LENGTH.
Referenced by ast_sip_initialize_distributor().
 {
    char default_realm[MAX_REALM_LENGTH + 1];
    struct ast_sip_auth *fake_auth;
    ast_sip_get_default_realm(default_realm, sizeof(default_realm));
    fake_auth = alloc_artificial_auth(default_realm);
    if (!fake_auth) {
       ast_log(LOG_ERROR, "Unable to create artificial auth\n");
       return -1;
    }
    ao2_global_obj_replace_unref(artificial_auth, fake_auth);
    ao2_ref(fake_auth, -1);
    return 0;
 }
create_artificial_endpoint()
static int create_artificial_endpoint (void) static
Definition at line 638 of file pjsip_distributor.c.
References ast_sip_get_sorcery(), ast_sorcery_alloc(), ast_strdup, AST_VECTOR_APPEND, AST_VECTOR_INIT, ast_sip_endpoint::inbound_auths, and NULL.
Referenced by ast_sip_initialize_distributor().
 {
    artificial_endpoint = ast_sorcery_alloc(ast_sip_get_sorcery(), "endpoint", NULL);
    if (!artificial_endpoint) {
       return -1;
    }
    AST_VECTOR_INIT(&artificial_endpoint->inbound_auths, 1);
    /* Pushing a bogus value into the vector will ensure that
     * the proper size of the vector is returned. This value is
     * not actually used anywhere
     */
    AST_VECTOR_APPEND(&artificial_endpoint->inbound_auths, ast_strdup("artificial-auth"));
    return 0;
 }
dialog_associations_cmp()
static int dialog_associations_cmp (void * obj, void * arg, int flags) static
Definition at line 239 of file pjsip_distributor.c.
References ast_assert, CMP_MATCH, distributor_dialog_data::dlg, OBJ_SEARCH_KEY, OBJ_SEARCH_MASK, OBJ_SEARCH_OBJECT, and OBJ_SEARCH_PARTIAL_KEY.
Referenced by ast_sip_initialize_distributor().
 {
    const struct distributor_dialog_data *object_left = obj;
    const struct distributor_dialog_data *object_right = arg;
    const pjsip_dialog *right_key = arg;
    int cmp = 0;
    switch (flags & OBJ_SEARCH_MASK) {
    case OBJ_SEARCH_OBJECT:
       right_key = object_right->dlg;
       /* Fall through */
    case OBJ_SEARCH_KEY:
       if (object_left->dlg == right_key) {
          cmp = CMP_MATCH;
       }
       break;
    case OBJ_SEARCH_PARTIAL_KEY:
       /* There is no such thing for this container. */
       ast_assert(0);
       break;
    default:
       cmp = 0;
       break;
    }
    return cmp;
 }
dialog_associations_hash()
static int dialog_associations_hash (const void * obj, int flags) static
Definition at line 215 of file pjsip_distributor.c.
References ast_assert, ast_str_hash_restrict(), buf, buf_hash(), OBJ_SEARCH_KEY, OBJ_SEARCH_MASK, and OBJ_SEARCH_OBJECT.
Referenced by ast_sip_initialize_distributor().
 {
    const struct distributor_dialog_data *object;
    union {
       const pjsip_dialog *dlg;
       const char buf[sizeof(pjsip_dialog *)];
    } key;
    switch (flags & OBJ_SEARCH_MASK) {
    case OBJ_SEARCH_KEY:
       key.dlg = obj;
       break;
    case OBJ_SEARCH_OBJECT:
       object = obj;
       key.dlg = object->dlg;
       break;
    default:
       /* Hash can only work on something with a full key. */
       ast_assert(0);
       return 0;
    }
    return ast_str_hash_restrict(buf_hash(key.buf, sizeof(key.buf)));
 }
distribute()
static int distribute (void * data) static
Definition at line 943 of file pjsip_distributor.c.
References ao2_cleanup, ast_sip_get_pjsip_endpoint(), distributor_mod, endpoint_mod, and NULL.
Referenced by distributor().
 {
    static pjsip_process_rdata_param param = {
       .start_mod = &distributor_mod,
       .idx_after_start = 1,
    };
    pj_bool_t handled = PJ_FALSE;
    pjsip_rx_data *rdata = data;
    int is_request = rdata->msg_info.msg->type == PJSIP_REQUEST_MSG;
    int is_ack = is_request ? rdata->msg_info.msg->line.req.method.id == PJSIP_ACK_METHOD : 0;
    struct ast_sip_endpoint *endpoint;
    pjsip_endpt_process_rx_data(ast_sip_get_pjsip_endpoint(), rdata, &param, &handled);
    if (!handled && is_request && !is_ack) {
       pjsip_endpt_respond_stateless(ast_sip_get_pjsip_endpoint(), rdata, 501, NULL, NULL, NULL);
    }
    /* The endpoint_mod stores an endpoint reference in the mod_data of rdata. This
     * is the only appropriate spot to actually decrement the reference.
     */
    endpoint = rdata->endpt_info.mod_data[endpoint_mod.id];
    ao2_cleanup(endpoint);
    pjsip_rx_data_free_cloned(rdata);
    return 0;
 }
distributor()
static pj_bool_t distributor (pjsip_rx_data * rdata) static
Definition at line 485 of file pjsip_distributor.c.
References ao2_bump, ao2_cleanup, ao2_find, ao2_lock, ao2_unlock, ast_debug, AST_OPT_FLAG_FULLY_BOOTED, ast_options, ast_sip_get_distributor_serializer(), ast_sip_get_pjsip_endpoint(), ast_sip_push_task(), ast_taskprocessor_alert_get(), ast_taskprocessor_get_subsystem_alert(), ast_taskprocessor_name(), ast_taskprocessor_unreference(), ast_test_flag, distribute(), distributor_dialog_data::endpoint, endpoint_mod, find_dialog(), find_request_serializer(), NULL, OBJ_SEARCH_KEY, overload_trigger, distributor_dialog_data::serializer, TASKPROCESSOR_OVERLOAD_TRIGGER_GLOBAL, and TASKPROCESSOR_OVERLOAD_TRIGGER_PJSIP_ONLY.
 {
    pjsip_dialog *dlg;
    struct distributor_dialog_data *dist = NULL;
    struct ast_taskprocessor *serializer = NULL;
    pjsip_rx_data *clone;
    if (!ast_test_flag(&ast_options, AST_OPT_FLAG_FULLY_BOOTED)) {
       /*
        * Ignore everything until we are fully booted.  Let the
        * peer retransmit messages until we are ready.
        */
       return PJ_TRUE;
    }
    dlg = find_dialog(rdata);
    if (dlg) {
       ast_debug(3, "Searching for serializer associated with dialog %s for %s\n",
          dlg->obj_name, pjsip_rx_data_get_info(rdata));
       dist = ao2_find(dialog_associations, dlg, OBJ_SEARCH_KEY);
       if (dist) {
          ao2_lock(dist);
          serializer = ao2_bump(dist->serializer);
          ao2_unlock(dist);
          if (serializer) {
             ast_debug(3, "Found serializer %s associated with dialog %s\n",
                ast_taskprocessor_name(serializer), dlg->obj_name);
          }
       }
    }
    if (serializer) {
       /* We have a serializer so we know where to send the message. */
    } else if (rdata->msg_info.msg->type == PJSIP_RESPONSE_MSG) {
       ast_debug(3, "No dialog serializer for %s.  Using request transaction as basis.\n",
          pjsip_rx_data_get_info(rdata));
       serializer = find_request_serializer(rdata);
       if (!serializer) {
          /*
           * Pick a serializer for the unmatched response.
           * We couldn't determine what serializer originally
           * sent the request or the serializer is gone.
           */
          serializer = ast_sip_get_distributor_serializer(rdata);
       }
    } else if (!pjsip_method_cmp(&rdata->msg_info.msg->line.req.method, &pjsip_cancel_method)
       || !pjsip_method_cmp(&rdata->msg_info.msg->line.req.method, &pjsip_bye_method)) {
       /* We have a BYE or CANCEL request without a serializer. */
       pjsip_endpt_respond_stateless(ast_sip_get_pjsip_endpoint(), rdata,
          PJSIP_SC_CALL_TSX_DOES_NOT_EXIST, NULL, NULL, NULL);
       ao2_cleanup(dist);
       return PJ_TRUE;
    } else {
       if ((overload_trigger == TASKPROCESSOR_OVERLOAD_TRIGGER_GLOBAL &&
          ast_taskprocessor_alert_get())
          || (overload_trigger == TASKPROCESSOR_OVERLOAD_TRIGGER_PJSIP_ONLY &&
          ast_taskprocessor_get_subsystem_alert("pjsip"))) {
          /*
           * When taskprocessors get backed up, there is a good chance that
           * we are being overloaded and need to defer adding new work to
           * the system.  To defer the work we will ignore the request and
           * rely on the peer's transport layer to retransmit the message.
           * We usually work off the overload within a few seconds.
           * If transport is non-UDP we send a 503 response instead.
           */
          switch (rdata->tp_info.transport->key.type) {
          case PJSIP_TRANSPORT_UDP6:
          case PJSIP_TRANSPORT_UDP:
             ast_debug(3, "Taskprocessor overload alert: Ignoring '%s'.\n",
                pjsip_rx_data_get_info(rdata));
             break;
          default:
             ast_debug(3, "Taskprocessor overload on non-udp transport. Received:'%s'. "
                "Responding with a 503.\n", pjsip_rx_data_get_info(rdata));
             pjsip_endpt_respond_stateless(ast_sip_get_pjsip_endpoint(), rdata,
                PJSIP_SC_SERVICE_UNAVAILABLE, NULL, NULL, NULL);
             break;
          }
          ao2_cleanup(dist);
          return PJ_TRUE;
       }
       /* Pick a serializer for the out-of-dialog request. */
       serializer = ast_sip_get_distributor_serializer(rdata);
    }
    if (pjsip_rx_data_clone(rdata, 0, &clone) != PJ_SUCCESS) {
       ast_taskprocessor_unreference(serializer);
       ao2_cleanup(dist);
       return PJ_TRUE;
    }
    if (dist) {
       ao2_lock(dist);
       clone->endpt_info.mod_data[endpoint_mod.id] = ao2_bump(dist->endpoint);
       ao2_unlock(dist);
       ao2_cleanup(dist);
    }
    if (ast_sip_push_task(serializer, distribute, clone)) {
       ao2_cleanup(clone->endpt_info.mod_data[endpoint_mod.id]);
       pjsip_rx_data_free_cloned(clone);
    }
    ast_taskprocessor_unreference(serializer);
    return PJ_TRUE;
 }
distributor_pool_setup()
static int distributor_pool_setup (void) static
Definition at line 1243 of file pjsip_distributor.c.
References ARRAY_LEN, ast_sip_create_serializer(), ast_taskprocessor_build_name(), and AST_TASKPROCESSOR_MAX_NAME.
Referenced by ast_sip_initialize_distributor().
 {
    char tps_name[AST_TASKPROCESSOR_MAX_NAME + 1];
    int idx;
    for (idx = 0; idx < ARRAY_LEN(distributor_pool); ++idx) {
       /* Create name with seq number appended. */
       ast_taskprocessor_build_name(tps_name, sizeof(tps_name), "pjsip/distributor");
       distributor_pool[idx] = ast_sip_create_serializer(tps_name);
       if (!distributor_pool[idx]) {
          return -1;
       }
    }
    return 0;
 }
distributor_pool_shutdown()
static void distributor_pool_shutdown (void) static
Definition at line 1225 of file pjsip_distributor.c.
References ARRAY_LEN, ast_taskprocessor_unreference(), and NULL.
Referenced by ast_sip_destroy_distributor().
 {
    int idx;
    for (idx = 0; idx < ARRAY_LEN(distributor_pool); ++idx) {
       ast_taskprocessor_unreference(distributor_pool[idx]);
       distributor_pool[idx] = NULL;
    }
 }
endpoint_lookup()
static pj_bool_t endpoint_lookup (pjsip_rx_data * rdata) static
Definition at line 718 of file pjsip_distributor.c.
References AO2_ALLOC_OPT_LOCK_RWLOCK, ao2_alloc_options, ao2_find, ao2_link_flags, ao2_ref, ao2_unlink, ao2_unlock, ao2_wrlock, apply_acls(), ast_copy_pj_str(), ast_sip_get_artificial_endpoint(), ast_sip_get_pjsip_endpoint(), ast_sip_identify_endpoint(), ast_sip_report_invalid_endpoint(), ast_tvnow(), AST_UUID_STR_LEN, check_endpoint(), unidentified_request::count, endpoint_mod, unidentified_request::first_seen, log_failed_request(), name, NULL, OBJ_NOLOCK, OBJ_SEARCH_KEY, unidentified_request::src_name, and using_auth_username.
Referenced by ast_sip_get_distributor_serializer().
 {
    struct ast_sip_endpoint *endpoint;
    struct unidentified_request *unid;
    int is_ack = rdata->msg_info.msg->line.req.method.id == PJSIP_ACK_METHOD;
    endpoint = rdata->endpt_info.mod_data[endpoint_mod.id];
    if (endpoint) {
       /*
        * ao2_find with OBJ_UNLINK always write locks the container before even searching
        * for the object.  Since the majority case is that the object won't be found, do
        * the find without OBJ_UNLINK to prevent the unnecessary write lock, then unlink
        * if needed.
        */
       unid = ao2_find(unidentified_requests, rdata->pkt_info.src_name, OBJ_SEARCH_KEY);
       if (unid) {
          ao2_unlink(unidentified_requests, unid);
          ao2_ref(unid, -1);
       }
       apply_acls(rdata);
       return PJ_FALSE;
    }
    endpoint = ast_sip_identify_endpoint(rdata);
    if (endpoint) {
       unid = ao2_find(unidentified_requests, rdata->pkt_info.src_name, OBJ_SEARCH_KEY);
       if (unid) {
          ao2_unlink(unidentified_requests, unid);
          ao2_ref(unid, -1);
       }
    }
    if (!endpoint) {
       /* always use an artificial endpoint - per discussion no reason
          to have "alwaysauthreject" as an option.  It is felt using it
          was a bug fix and it is not needed since we are not worried about
          breaking old stuff and we really don't want to enable the discovery
          of SIP accounts */
       endpoint = ast_sip_get_artificial_endpoint();
    }
    /* endpoint ref held by mod_data[] */
    rdata->endpt_info.mod_data[endpoint_mod.id] = endpoint;
    if (endpoint == artificial_endpoint && !is_ack) {
       char name[AST_UUID_STR_LEN] = "";
       pjsip_uri *from = rdata->msg_info.from->uri;
       if (PJSIP_URI_SCHEME_IS_SIP(from) || PJSIP_URI_SCHEME_IS_SIPS(from)) {
          pjsip_sip_uri *sip_from = pjsip_uri_get_uri(from);
          ast_copy_pj_str(name, &sip_from->user, sizeof(name));
       }
       unid = ao2_find(unidentified_requests, rdata->pkt_info.src_name, OBJ_SEARCH_KEY);
       if (unid) {
          check_endpoint(rdata, unid, name);
          ao2_ref(unid, -1);
       } else if (using_auth_username) {
          ao2_wrlock(unidentified_requests);
          /* Checking again with the write lock held allows us to eliminate the DUPS_REPLACE and sort_fn */
          unid = ao2_find(unidentified_requests, rdata->pkt_info.src_name,
             OBJ_SEARCH_KEY | OBJ_NOLOCK);
          if (unid) {
             check_endpoint(rdata, unid, name);
          } else {
             unid = ao2_alloc_options(sizeof(*unid) + strlen(rdata->pkt_info.src_name) + 1,
                NULL, AO2_ALLOC_OPT_LOCK_RWLOCK);
             if (!unid) {
                ao2_unlock(unidentified_requests);
                pjsip_endpt_respond_stateless(ast_sip_get_pjsip_endpoint(), rdata, 500, NULL, NULL, NULL);
                return PJ_TRUE;
             }
             strcpy(unid->src_name, rdata->pkt_info.src_name); /* Safe */
             unid->first_seen = ast_tvnow();
             unid->count = 1;
             ao2_link_flags(unidentified_requests, unid, OBJ_NOLOCK);
          }
          ao2_ref(unid, -1);
          ao2_unlock(unidentified_requests);
       } else {
          log_failed_request(rdata, "No matching endpoint found", 0, 0);
          ast_sip_report_invalid_endpoint(name, rdata);
       }
    }
    apply_acls(rdata);
    return PJ_FALSE;
 }
expire_requests()
static int expire_requests (void * object, void * arg, int flags) static
Definition at line 1136 of file pjsip_distributor.c.
References ast_tvdiff_ms(), ast_tvnow(), CMP_MATCH, and unidentified_request::first_seen.
Referenced by prune_task().
 {
    struct unidentified_request *unid = object;
    int *maxage = arg;
    int64_t ms = ast_tvdiff_ms(ast_tvnow(), unid->first_seen);
    if (ms > (*maxage) * 2 * 1000) {
       return CMP_MATCH;
    }
    return 0;
 }
extract_contact_addr()
static int extract_contact_addr (pjsip_contact_hdr * contact, struct ast_sockaddr ** addrs) static
Definition at line 827 of file pjsip_distributor.c.
References AST_AF_UNSPEC, ast_copy_pj_str(), ast_sockaddr_resolve(), host, NULL, and PARSE_PORT_FORBID.
Referenced by apply_endpoint_contact_acl().
 {
    pjsip_sip_uri *sip_uri;
    char host[256];
    if (!contact || contact->star) {
       *addrs = NULL;
       return 0;
    }
    if (!PJSIP_URI_SCHEME_IS_SIP(contact->uri) && !PJSIP_URI_SCHEME_IS_SIPS(contact->uri)) {
       *addrs = NULL;
       return 0;
    }
    sip_uri = pjsip_uri_get_uri(contact->uri);
    ast_copy_pj_str(host, &sip_uri->host, sizeof(host));
    return ast_sockaddr_resolve(addrs, host, PARSE_PORT_FORBID, AST_AF_UNSPEC);
 }
find_dialog()
static pjsip_dialog* find_dialog (pjsip_rx_data * rdata) static
Definition at line 339 of file pjsip_distributor.c.
References ast_debug, and NULL.
Referenced by distributor().
 {
    pj_str_t tsx_key;
    pjsip_transaction *tsx;
    pjsip_dialog *dlg;
    pj_str_t *local_tag;
    pj_str_t *remote_tag;
    if (!rdata->msg_info.msg) {
       return NULL;
    }
    if (rdata->msg_info.msg->type == PJSIP_REQUEST_MSG) {
       local_tag = &rdata->msg_info.to->tag;
       remote_tag = &rdata->msg_info.from->tag;
    } else {
       local_tag = &rdata->msg_info.from->tag;
       remote_tag = &rdata->msg_info.to->tag;
    }
    /* We can only call the convenient method for
     *  1) responses
     *  2) non-CANCEL requests
     *  3) CANCEL requests with a to-tag
     */
    if (rdata->msg_info.msg->type == PJSIP_RESPONSE_MSG ||
          pjsip_method_cmp(&rdata->msg_info.msg->line.req.method, &pjsip_cancel_method) ||
          rdata->msg_info.to->tag.slen != 0) {
       dlg = pjsip_ua_find_dialog(&rdata->msg_info.cid->id, local_tag,
             remote_tag, PJ_FALSE);
       if (dlg) {
          return dlg;
       }
    }
    /*
     * There may still be a matching dialog if this is
     * 1) an incoming CANCEL request without a to-tag
     * 2) an incoming response to a dialog-creating request.
     */
    if (rdata->msg_info.msg->type == PJSIP_REQUEST_MSG) {
       /* CANCEL requests will need to match the INVITE we initially received. Any
        * other request type will either have been matched already or is not in
        * dialog
        */
       pjsip_tsx_create_key(rdata->tp_info.pool, &tsx_key, PJSIP_ROLE_UAS,
             pjsip_get_invite_method(), rdata);
    } else {
       pjsip_tsx_create_key(rdata->tp_info.pool, &tsx_key, PJSIP_ROLE_UAC,
             &rdata->msg_info.cseq->method, rdata);
    }
    tsx = pjsip_tsx_layer_find_tsx(&tsx_key, PJ_TRUE);
    if (!tsx) {
       ast_debug(3, "Could not find matching transaction for %s\n",
          pjsip_rx_data_get_info(rdata));
       return NULL;
    }
    dlg = pjsip_tsx_get_dlg(tsx);
 #ifdef HAVE_PJ_TRANSACTION_GRP_LOCK
    pj_grp_lock_release(tsx->grp_lock);
 #else
    pj_mutex_unlock(tsx->mutex);
 #endif
    return dlg;
 }
find_request_serializer()
static struct ast_taskprocessor* find_request_serializer (pjsip_rx_data * rdata) static
Definition at line 112 of file pjsip_distributor.c.
References ast_debug, ast_strlen_zero, ast_taskprocessor_get(), distributor_mod, NULL, and TPS_REF_IF_EXISTS.
Referenced by distributor().
 {
    struct ast_taskprocessor *serializer = NULL;
    pj_str_t tsx_key;
    pjsip_transaction *tsx;
    pjsip_tsx_create_key(rdata->tp_info.pool, &tsx_key, PJSIP_ROLE_UAC,
       &rdata->msg_info.cseq->method, rdata);
    tsx = pjsip_tsx_layer_find_tsx(&tsx_key, PJ_TRUE);
    if (!tsx) {
       ast_debug(1, "Could not find transaction for %s.\n",
          pjsip_rx_data_get_info(rdata));
       return NULL;
    }
    ast_debug(3, "Found transaction %s for %s.\n",
       tsx->obj_name, pjsip_rx_data_get_info(rdata));
    if (tsx->last_tx) {
       const char *serializer_name;
       serializer_name = tsx->last_tx->mod_data[distributor_mod.id];
       if (!ast_strlen_zero(serializer_name)) {
          serializer = ast_taskprocessor_get(serializer_name, TPS_REF_IF_EXISTS);
          if (serializer) {
             ast_debug(3, "Found serializer %s on transaction %s\n",
                   serializer_name, tsx->obj_name);
          }
       }
    }
 #ifdef HAVE_PJ_TRANSACTION_GRP_LOCK
    pj_grp_lock_release(tsx->grp_lock);
 #else
    pj_mutex_unlock(tsx->mutex);
 #endif
    return serializer;
 }
global_loaded()
static void global_loaded (const char * object_type) static
Definition at line 1165 of file pjsip_distributor.c.
References alloc_artificial_auth(), ao2_cleanup, ao2_global_obj_replace_unref, ast_free, ast_sched_add_variable(), ast_sched_clean_by_callback(), ast_sip_get_artificial_auth(), ast_sip_get_default_realm(), ast_sip_get_endpoint_identifier_order(), ast_sip_get_taskprocessor_overload_trigger(), ast_sip_get_unidentified_request_thresholds(), ast_strdupa, ast_strip(), clean_task(), default_realm, MAX_REALM_LENGTH, NULL, overload_trigger, prune_task(), ast_sip_auth::realm, strsep(), unidentified_count, unidentified_period, unidentified_prune_interval, and using_auth_username.
 {
    char default_realm[MAX_REALM_LENGTH + 1];
    struct ast_sip_auth *fake_auth;
    char *identifier_order;
    /* Update using_auth_username */
    identifier_order = ast_sip_get_endpoint_identifier_order();
    if (identifier_order) {
       char *identify_method;
       char *io_copy = ast_strdupa(identifier_order);
       int new_using = 0;
       ast_free(identifier_order);
       while ((identify_method = ast_strip(strsep(&io_copy, ",")))) {
          if (!strcmp(identify_method, "auth_username")) {
             new_using = 1;
             break;
          }
       }
       using_auth_username = new_using;
    }
    /* Update default_realm of artificial_auth */
    ast_sip_get_default_realm(default_realm, sizeof(default_realm));
    fake_auth = ast_sip_get_artificial_auth();
    if (!fake_auth || strcmp(fake_auth->realm, default_realm)) {
       ao2_cleanup(fake_auth);
       fake_auth = alloc_artificial_auth(default_realm);
       if (fake_auth) {
          ao2_global_obj_replace_unref(artificial_auth, fake_auth);
       }
    }
    ao2_cleanup(fake_auth);
    ast_sip_get_unidentified_request_thresholds(&unidentified_count, &unidentified_period, &unidentified_prune_interval);
    overload_trigger = ast_sip_get_taskprocessor_overload_trigger();
    /* Clean out the old task, if any */
    ast_sched_clean_by_callback(prune_context, prune_task, clean_task);
    /* Have to do something with the return value to shut up the stupid compiler. */
    if (ast_sched_add_variable(prune_context, unidentified_prune_interval * 1000, prune_task, NULL, 1) < 0) {
       return;
    }
 }
log_failed_request()
static void log_failed_request (pjsip_rx_data * rdata, char * msg, unsigned int count, unsigned int period) static
Definition at line 660 of file pjsip_distributor.c.
References ast_copy_pj_str(), ast_log, AST_SOCKADDR_BUFLEN, and LOG_NOTICE.
Referenced by apply_endpoint_acl(), apply_endpoint_contact_acl(), authenticate(), check_endpoint(), and endpoint_lookup().
 {
    char from_buf[PJSIP_MAX_URL_SIZE];
    char callid_buf[PJSIP_MAX_URL_SIZE];
    char method_buf[PJSIP_MAX_URL_SIZE];
    char src_addr_buf[AST_SOCKADDR_BUFLEN];
    pjsip_uri_print(PJSIP_URI_IN_FROMTO_HDR, rdata->msg_info.from->uri, from_buf, PJSIP_MAX_URL_SIZE);
    ast_copy_pj_str(callid_buf, &rdata->msg_info.cid->id, PJSIP_MAX_URL_SIZE);
    ast_copy_pj_str(method_buf, &rdata->msg_info.msg->line.req.method.name, PJSIP_MAX_URL_SIZE);
    if (count) {
       ast_log(LOG_NOTICE, "Request '%s' from '%s' failed for '%s' (callid: %s) - %s"
          " after %u tries in %.3f ms\n",
          method_buf, from_buf,
          pj_sockaddr_print(&rdata->pkt_info.src_addr, src_addr_buf, sizeof(src_addr_buf), 3),
          callid_buf, msg, count, period / 1000.0);
    } else {
       ast_log(LOG_NOTICE, "Request '%s' from '%s' failed for '%s' (callid: %s) - %s\n",
          method_buf, from_buf,
          pj_sockaddr_print(&rdata->pkt_info.src_addr, src_addr_buf, sizeof(src_addr_buf), 3),
          callid_buf, msg);
    }
 }
pjstr_hash()
static int pjstr_hash (pj_str_t * str) static
Definition at line 443 of file pjsip_distributor.c.
References pjstr_hash_add().
Referenced by ast_sip_get_distributor_serializer().
 {
    return pjstr_hash_add(str, 5381);
 }
pjstr_hash_add()
static int pjstr_hash_add (pj_str_t * str, int hash) static
Definition at line 426 of file pjsip_distributor.c.
References buf_hash_add().
Referenced by ast_sip_get_distributor_serializer(), and pjstr_hash().
 {
    return buf_hash_add(pj_strbuf(str), pj_strlen(str), hash);
 }
prune_task()
static int prune_task (const void * data) static
Definition at line 1149 of file pjsip_distributor.c.
References ao2_callback, ast_sip_get_unidentified_request_thresholds(), expire_requests(), OBJ_MULTIPLE, OBJ_NODATA, OBJ_UNLINK, unidentified_count, unidentified_period, and unidentified_prune_interval.
Referenced by global_loaded().
 {
    unsigned int maxage;
    ast_sip_get_unidentified_request_thresholds(&unidentified_count, &unidentified_period, &unidentified_prune_interval);
    maxage = unidentified_period * 2;
    ao2_callback(unidentified_requests, OBJ_MULTIPLE | OBJ_NODATA | OBJ_UNLINK, expire_requests, &maxage);
    return unidentified_prune_interval * 1000;
 }
record_serializer()
static pj_status_t record_serializer (pjsip_tx_data * tdata) static
Definition at line 77 of file pjsip_distributor.c.
References ast_strlen_zero, ast_taskprocessor_name(), ast_threadpool_serializer_get_current(), distributor_mod, and name.
 {
    struct ast_taskprocessor *serializer;
    serializer = ast_threadpool_serializer_get_current();
    if (serializer) {
       const char *name;
       name = ast_taskprocessor_name(serializer);
       if (!ast_strlen_zero(name)
          && (!tdata->mod_data[distributor_mod.id]
             || strcmp(tdata->mod_data[distributor_mod.id], name))) {
          char *tdata_name;
          /* The serializer in use changed. */
          tdata_name = pj_pool_alloc(tdata->pool, strlen(name) + 1);
          strcpy(tdata_name, name);/* Safe */
          tdata->mod_data[distributor_mod.id] = tdata_name;
       }
    }
    return PJ_SUCCESS;
 }
suspects_compare()
static int suspects_compare (void * obj, void * arg, int flags) static
Definition at line 1002 of file pjsip_distributor.c.
References CMP_MATCH, OBJ_SEARCH_KEY, OBJ_SEARCH_MASK, OBJ_SEARCH_OBJECT, OBJ_SEARCH_PARTIAL_KEY, and unidentified_request::src_name.
Referenced by ast_sip_initialize_distributor(), and cli_unid_get_container().
 {
    const struct unidentified_request *object_left = obj;
    const struct unidentified_request *object_right = arg;
    const char *right_key = arg;
    int cmp = 0;
    switch (flags & OBJ_SEARCH_MASK) {
    case OBJ_SEARCH_OBJECT:
       right_key = object_right->src_name;
       /* Fall through */
    case OBJ_SEARCH_KEY:
       if (strcmp(object_left->src_name, right_key) == 0) {
          cmp = CMP_MATCH;
       }
       break;
    case OBJ_SEARCH_PARTIAL_KEY:
       if (strncmp(object_left->src_name, right_key, strlen(right_key)) == 0) {
          cmp = CMP_MATCH;
       }
       break;
    default:
       cmp = 0;
       break;
    }
    return cmp;
 }
suspects_hash()
static int suspects_hash (const void * obj, int flags) static
Definition at line 1030 of file pjsip_distributor.c.
References ast_assert, ast_str_hash(), OBJ_SEARCH_KEY, OBJ_SEARCH_MASK, and OBJ_SEARCH_OBJECT.
Referenced by ast_sip_initialize_distributor().
 {
    const struct unidentified_request *object;
    const char *key;
    switch (flags & OBJ_SEARCH_MASK) {
    case OBJ_SEARCH_KEY:
       key = obj;
       break;
    case OBJ_SEARCH_OBJECT:
       object = obj;
       key = object->src_name;
       break;
    default:
       /* Hash can only work on something with a full key. */
       ast_assert(0);
       return 0;
    }
    return ast_str_hash(key);
 }
suspects_sort()
static int suspects_sort (const void * obj, const void * arg, int flags) static
Definition at line 978 of file pjsip_distributor.c.
References OBJ_SEARCH_KEY, OBJ_SEARCH_MASK, OBJ_SEARCH_OBJECT, OBJ_SEARCH_PARTIAL_KEY, and unidentified_request::src_name.
Referenced by cli_unid_get_container().
 {
    const struct unidentified_request *object_left = obj;
    const struct unidentified_request *object_right = arg;
    const char *right_key = arg;
    int cmp;
    switch (flags & OBJ_SEARCH_MASK) {
    case OBJ_SEARCH_OBJECT:
       right_key = object_right->src_name;
       /* Fall through */
    case OBJ_SEARCH_KEY:
       cmp = strcmp(object_left->src_name, right_key);
       break;
    case OBJ_SEARCH_PARTIAL_KEY:
       cmp = strncmp(object_left->src_name, right_key, strlen(right_key));
       break;
    default:
       cmp = 0;
       break;
    }
    return cmp;
 }
Variable Documentation
artificial_endpoint
struct ast_sip_endpoint* artificial_endpoint = NULL static
Definition at line 636 of file pjsip_distributor.c.
Referenced by ast_sip_get_artificial_endpoint(), and digest_check_auth().
auth_mod
pjsip_module auth_mod static
Initial value:
= {
   .name = {"Request Authenticator", 21},
   .priority = PJSIP_MOD_PRIORITY_APPLICATION - 2,
   .on_rx_request = authenticate,
}
Definition at line 937 of file pjsip_distributor.c.
Referenced by ast_sip_destroy_distributor(), and ast_sip_initialize_distributor().
cli_commands
struct ast_cli_entry cli_commands[] static
Definition at line 1127 of file pjsip_distributor.c.
dialog_associations
struct ao2_container* dialog_associations static
Definition at line 164 of file pjsip_distributor.c.
distributor_mod
pjsip_module distributor_mod static
Definition at line 34 of file pjsip_distributor.c.
Referenced by ast_sip_destroy_distributor(), ast_sip_initialize_distributor(), distribute(), find_request_serializer(), and record_serializer().
distributor_pool
struct ast_taskprocessor* distributor_pool[DISTRIBUTOR_POOL_SIZE] static
Pool of serializers to use if not supplied.
Definition at line 66 of file pjsip_distributor.c.
endpoint_mod
pjsip_module endpoint_mod static
Initial value:
= {
   .name = {"Endpoint Identifier", 19},
   .priority = PJSIP_MOD_PRIORITY_TSX_LAYER - 3,
   .on_rx_request = endpoint_lookup,
}
Definition at line 479 of file pjsip_distributor.c.
Referenced by apply_acls(), ast_pjsip_rdata_get_endpoint(), ast_sip_destroy_distributor(), ast_sip_initialize_distributor(), distribute(), distributor(), and endpoint_lookup().
global_observer
struct ast_sorcery_observer global_observer static
Initial value:
= {
   .loaded = global_loaded,
}
Observer which is used to update our interval and default_realm when the global setting changes.
Definition at line 1214 of file pjsip_distributor.c.
overload_trigger
enum ast_sip_taskprocessor_overload_trigger overload_trigger static
Definition at line 54 of file pjsip_distributor.c.
Referenced by distributor(), and global_loaded().
prune_context
struct ast_sched_context* prune_context
Definition at line 42 of file pjsip_distributor.c.
unid_formatter
struct ast_sip_cli_formatter_entry* unid_formatter
Definition at line 1134 of file pjsip_distributor.c.
unidentified_count
unsigned int unidentified_count static
Definition at line 50 of file pjsip_distributor.c.
Referenced by check_endpoint(), global_loaded(), and prune_task().
unidentified_period
unsigned int unidentified_period static
Definition at line 51 of file pjsip_distributor.c.
Referenced by check_endpoint(), global_loaded(), and prune_task().
unidentified_prune_interval
unsigned int unidentified_prune_interval static
Definition at line 52 of file pjsip_distributor.c.
Referenced by global_loaded(), and prune_task().
unidentified_requests
struct ao2_container* unidentified_requests static
Definition at line 49 of file pjsip_distributor.c.
using_auth_username
int using_auth_username static
Definition at line 53 of file pjsip_distributor.c.
Referenced by endpoint_lookup(), and global_loaded().