Asterisk - The Open Source Telephony Project: dialplan_functions.h File Reference
pjsip/include/dialplan_functions.h File Reference
PJSIP dialplan functions header file.
Functions
int pjsip_acf_channel_read (struct ast_channel *chan, const char *cmd, char *data, char *buf, size_t len)
CHANNEL function read callback.
int pjsip_acf_dial_contacts_read (struct ast_channel *chan, const char *cmd, char *data, char *buf, size_t len)
PJSIP_DIAL_CONTACTS function read callback.
int pjsip_acf_dtmf_mode_read (struct ast_channel *chan, const char *cmd, char *data, char *buf, size_t len)
PJSIP_DTMF_MODE function read callback.
int pjsip_acf_dtmf_mode_write (struct ast_channel *chan, const char *cmd, char *data, const char *value)
PJSIP_DTMF_MODE function write callback.
int pjsip_acf_media_offer_read (struct ast_channel *chan, const char *cmd, char *data, char *buf, size_t len)
PJSIP_MEDIA_OFFER function read callback.
int pjsip_acf_media_offer_write (struct ast_channel *chan, const char *cmd, char *data, const char *value)
PJSIP_MEDIA_OFFER function write callback.
int pjsip_acf_moh_passthrough_read (struct ast_channel *chan, const char *cmd, char *data, char *buf, size_t len)
PJSIP_MOH_PASSTHROUGH function read callback.
int pjsip_acf_moh_passthrough_write (struct ast_channel *chan, const char *cmd, char *data, const char *value)
PJSIP_MOH_PASSTHROUGH function write callback.
int pjsip_acf_parse_uri_read (struct ast_channel *chan, const char *cmd, char *data, char *buf, size_t len)
PJSIP_PARSE_URI function read callback.
int pjsip_acf_session_refresh_write (struct ast_channel *chan, const char *cmd, char *data, const char *value)
PJSIP_SEND_SESSION_REFRESH function write callback.
Detailed Description
PJSIP dialplan functions header file.
Definition in file pjsip/include/dialplan_functions.h.
Function Documentation
pjsip_acf_channel_read()
int pjsip_acf_channel_read (struct ast_channel * chan, const char * cmd, char * data, char * buf, size_t len)
CHANNEL function read callback.
Parameters
chan The channel the function is called on
cmd The name of the function
data Arguments passed to the function
buf Out buffer that should be populated with the data
len Size of the buffer
Return values
0 on success
-1 on failure
Definition at line 916 of file pjsip/dialplan_functions.c.
References ao2_bump, ao2_ref, args, AST_APP_ARG, ast_channel_lock, ast_channel_name(), ast_channel_tech(), ast_channel_tech_pvt(), ast_channel_unlock, AST_DECLARE_APP_ARGS, ast_log, ast_sip_push_task_wait_serializer(), AST_STANDARD_APP_ARGS, ast_strdupa, ast_strlen_zero, buf, pjsip_func_args::buf, pjsip_func_args::field, pjsip_func_args::len, len(), LOG_ERROR, LOG_WARNING, pjsip_func_args::param, parse(), read_pjsip(), pjsip_func_args::ret, ast_sip_session::serializer, ast_sip_channel_pvt::session, pjsip_func_args::session, type, and pjsip_func_args::type.
 {
    struct pjsip_func_args func_args = { 0, };
    struct ast_sip_channel_pvt *channel;
    char *parse = ast_strdupa(data);
    AST_DECLARE_APP_ARGS(args,
       AST_APP_ARG(param);
       AST_APP_ARG(type);
       AST_APP_ARG(field);
    );
    if (!chan) {
       ast_log(LOG_WARNING, "No channel was provided to %s function.\n", cmd);
       return -1;
    }
    /* Check for zero arguments */
    if (ast_strlen_zero(parse)) {
       ast_log(LOG_ERROR, "Cannot call %s without arguments\n", cmd);
       return -1;
    }
    AST_STANDARD_APP_ARGS(args, parse);
    ast_channel_lock(chan);
    /* Sanity check */
    if (strcmp(ast_channel_tech(chan)->type, "PJSIP")) {
       ast_log(LOG_WARNING, "Cannot call %s on a non-PJSIP channel\n", cmd);
       ast_channel_unlock(chan);
       return 0;
    }
    channel = ast_channel_tech_pvt(chan);
    if (!channel) {
       ast_log(LOG_WARNING, "Channel %s has no pvt!\n", ast_channel_name(chan));
       ast_channel_unlock(chan);
       return -1;
    }
    if (!channel->session) {
       ast_log(LOG_WARNING, "Channel %s has no session\n", ast_channel_name(chan));
       ast_channel_unlock(chan);
       return -1;
    }
    func_args.session = ao2_bump(channel->session);
    ast_channel_unlock(chan);
    memset(buf, 0, len);
    func_args.param = args.param;
    func_args.type = args.type;
    func_args.field = args.field;
    func_args.buf = buf;
    func_args.len = len;
    if (ast_sip_push_task_wait_serializer(func_args.session->serializer, read_pjsip, &func_args)) {
       ast_log(LOG_WARNING, "Unable to read properties of channel %s: failed to push task\n", ast_channel_name(chan));
       ao2_ref(func_args.session, -1);
       return -1;
    }
    ao2_ref(func_args.session, -1);
    return func_args.ret;
 }
pjsip_acf_dial_contacts_read()
int pjsip_acf_dial_contacts_read (struct ast_channel * chan, const char * cmd, char * data, char * buf, size_t len)
PJSIP_DIAL_CONTACTS function read callback.
Parameters
chan The channel the function is called on
cmd The name of the function
data Arguments passed to the function
buf Out buffer that should be populated with the data
len Size of the buffer
Return values
0 on success
-1 on failure
Definition at line 983 of file pjsip/dialplan_functions.c.
References ao2_cleanup, ao2_container_count(), ao2_iterator_destroy(), ao2_iterator_init(), ao2_iterator_next, ao2_ref, ast_sip_contact::aor, args, AST_APP_ARG, ast_copy_string(), AST_DECLARE_APP_ARGS, ast_free_ptr(), ast_log, AST_SIP_CONTACT_FILTER_REACHABLE, ast_sip_get_sorcery(), ast_sip_location_retrieve_aor(), ast_sip_location_retrieve_aor_contacts_filtered(), ast_sorcery_retrieve_by_id(), AST_STANDARD_APP_ARGS, ast_str_append(), ast_str_buffer(), ast_str_create, ast_str_strlen(), ast_str_truncate(), ast_strdupa, ast_strip(), ast_strlen_zero, LOG_WARNING, NULL, RAII_VAR, S_OR, strsep(), and ast_sip_contact::uri.
 {
    RAII_VAR(struct ast_sip_endpoint *, endpoint, NULL, ao2_cleanup);
    RAII_VAR(struct ast_str *, dial, NULL, ast_free_ptr);
    const char *aor_name;
    char *rest;
    AST_DECLARE_APP_ARGS(args,
       AST_APP_ARG(endpoint_name);
       AST_APP_ARG(aor_name);
       AST_APP_ARG(request_user);
    );
    AST_STANDARD_APP_ARGS(args, data);
    if (ast_strlen_zero(args.endpoint_name)) {
       ast_log(LOG_WARNING, "An endpoint name must be specified when using the '%s' dialplan function\n", cmd);
       return -1;
    } else if (!(endpoint = ast_sorcery_retrieve_by_id(ast_sip_get_sorcery(), "endpoint", args.endpoint_name))) {
       ast_log(LOG_WARNING, "Specified endpoint '%s' was not found\n", args.endpoint_name);
       return -1;
    }
    aor_name = S_OR(args.aor_name, endpoint->aors);
    if (ast_strlen_zero(aor_name)) {
       ast_log(LOG_WARNING, "No AOR has been provided and no AORs are configured on endpoint '%s'\n", args.endpoint_name);
       return -1;
    } else if (!(dial = ast_str_create(len))) {
       ast_log(LOG_WARNING, "Could not get enough buffer space for dialing contacts\n");
       return -1;
    } else if (!(rest = ast_strdupa(aor_name))) {
       ast_log(LOG_WARNING, "Could not duplicate provided AORs\n");
       return -1;
    }
    while ((aor_name = ast_strip(strsep(&rest, ",")))) {
       RAII_VAR(struct ast_sip_aor *, aor, ast_sip_location_retrieve_aor(aor_name), ao2_cleanup);
       RAII_VAR(struct ao2_container *, contacts, NULL, ao2_cleanup);
       struct ao2_iterator it_contacts;
       struct ast_sip_contact *contact;
       if (!aor) {
          /* If the AOR provided is not found skip it, there may be more */
          continue;
       } else if (!(contacts = ast_sip_location_retrieve_aor_contacts_filtered(aor, AST_SIP_CONTACT_FILTER_REACHABLE))) {
          /* No contacts are available, skip it as well */
          continue;
       } else if (!ao2_container_count(contacts)) {
          /* We were given a container but no contacts are in it... */
          continue;
       }
       it_contacts = ao2_iterator_init(contacts, 0);
       for (; (contact = ao2_iterator_next(&it_contacts)); ao2_ref(contact, -1)) {
          ast_str_append(&dial, -1, "PJSIP/");
          if (!ast_strlen_zero(args.request_user)) {
             ast_str_append(&dial, -1, "%s@", args.request_user);
          }
          ast_str_append(&dial, -1, "%s/%s&", args.endpoint_name, contact->uri);
       }
       ao2_iterator_destroy(&it_contacts);
    }
    /* Trim the '&' at the end off */
    ast_str_truncate(dial, ast_str_strlen(dial) - 1);
    ast_copy_string(buf, ast_str_buffer(dial), len);
    return 0;
 }
pjsip_acf_dtmf_mode_read()
int pjsip_acf_dtmf_mode_read (struct ast_channel * chan, const char * cmd, char * data, char * buf, size_t len)
PJSIP_DTMF_MODE function read callback.
Parameters
chan The channel the function is called on
cmd The name of the function
data Arguments passed to the function
buf Out buffer that should be populated with the data
len Size of the buffer
Return values
0 on success
-1 on failure
Definition at line 1429 of file pjsip/dialplan_functions.c.
References ast_channel_lock, ast_channel_name(), ast_channel_tech(), ast_channel_tech_pvt(), ast_channel_unlock, ast_log, ast_sip_dtmf_to_str(), ast_sip_session::dtmf, LOG_WARNING, ast_sip_channel_pvt::session, and type.
 {
    struct ast_sip_channel_pvt *channel;
    if (!chan) {
       ast_log(LOG_WARNING, "No channel was provided to %s function.\n", cmd);
       return -1;
    }
    ast_channel_lock(chan);
    if (strcmp(ast_channel_tech(chan)->type, "PJSIP")) {
       ast_log(LOG_WARNING, "Cannot call %s on a non-PJSIP channel\n", cmd);
       ast_channel_unlock(chan);
       return -1;
    }
    channel = ast_channel_tech_pvt(chan);
    if (ast_sip_dtmf_to_str(channel->session->dtmf, buf, len) < 0) {
       ast_log(LOG_WARNING, "Unknown DTMF mode %d on PJSIP channel %s\n", channel->session->dtmf, ast_channel_name(chan));
       ast_channel_unlock(chan);
       return -1;
    }
    ast_channel_unlock(chan);
    return 0;
 }
pjsip_acf_dtmf_mode_write()
int pjsip_acf_dtmf_mode_write (struct ast_channel * chan, const char * cmd, char * data, const char * value)
PJSIP_DTMF_MODE function write callback.
Parameters
chan The channel the function is called on
cmd The name of the function
data Arguments passed to the function
value Value to be set by the function
Return values
0 on success
-1 on failure
Definition at line 1530 of file pjsip/dialplan_functions.c.
References ast_sip_session::active_media_state, ast_channel_lock, ast_channel_name(), ast_channel_tech(), ast_channel_tech_pvt(), ast_channel_unlock, ast_dsp_free(), ast_dsp_get_features(), ast_dsp_new(), ast_dsp_set_features(), ast_log, AST_MEDIA_TYPE_AUDIO, AST_RTP_DTMF_MODE_INBAND, AST_RTP_DTMF_MODE_NONE, AST_RTP_DTMF_MODE_RFC2833, ast_rtp_instance_dtmf_mode_get(), ast_rtp_instance_dtmf_mode_set(), ast_rtp_instance_set_prop(), AST_RTP_PROPERTY_DTMF, AST_SIP_DTMF_AUTO, AST_SIP_DTMF_AUTO_INFO, AST_SIP_DTMF_INBAND, AST_SIP_DTMF_INFO, AST_SIP_DTMF_NONE, AST_SIP_DTMF_RFC_4733, ast_sip_push_task_wait_serializer(), AST_SIP_SESSION_REFRESH_METHOD_INVITE, ast_sip_str_to_dtmf(), ast_sip_session_media_state::default_session, ast_sip_session::dsp, DSP_FEATURE_DIGIT_DETECT, ast_sip_session::dtmf, dtmf_mode_refresh_cb(), LOG_WARNING, refresh_data::method, NULL, ast_sip_session_media::rtp, ast_sip_session::serializer, ast_sip_channel_pvt::session, refresh_data::session, and type.
 {
    struct ast_sip_channel_pvt *channel;
    struct ast_sip_session_media *media;
    int dsp_features = 0;
    int dtmf = -1;
    struct refresh_data rdata = {
          .method = AST_SIP_SESSION_REFRESH_METHOD_INVITE,
       };
    if (!chan) {
       ast_log(LOG_WARNING, "No channel was provided to %s function.\n", cmd);
       return -1;
    }
    ast_channel_lock(chan);
    if (strcmp(ast_channel_tech(chan)->type, "PJSIP")) {
       ast_log(LOG_WARNING, "Cannot call %s on a non-PJSIP channel\n", cmd);
       ast_channel_unlock(chan);
       return -1;
    }
    channel = ast_channel_tech_pvt(chan);
    rdata.session = channel->session;
    dtmf = ast_sip_str_to_dtmf(value);
    if (dtmf == -1) {
       ast_log(LOG_WARNING, "Cannot set DTMF mode to '%s' on channel '%s' as value is invalid.\n", value,
          ast_channel_name(chan));
       ast_channel_unlock(chan);
       return -1;
    }
    if (channel->session->dtmf == dtmf) {
       /* DTMF mode unchanged, nothing to do! */
       ast_channel_unlock(chan);
       return 0;
    }
    channel->session->dtmf = dtmf;
    media = channel->session->active_media_state->default_session[AST_MEDIA_TYPE_AUDIO];
    if (media && media->rtp) {
       if (channel->session->dtmf == AST_SIP_DTMF_RFC_4733) {
          ast_rtp_instance_set_prop(media->rtp, AST_RTP_PROPERTY_DTMF, 1);
          ast_rtp_instance_dtmf_mode_set(media->rtp, AST_RTP_DTMF_MODE_RFC2833);
       } else if (channel->session->dtmf == AST_SIP_DTMF_INFO) {
          ast_rtp_instance_set_prop(media->rtp, AST_RTP_PROPERTY_DTMF, 0);
          ast_rtp_instance_dtmf_mode_set(media->rtp, AST_RTP_DTMF_MODE_NONE);
       } else if (channel->session->dtmf == AST_SIP_DTMF_INBAND) {
          ast_rtp_instance_set_prop(media->rtp, AST_RTP_PROPERTY_DTMF, 0);
          ast_rtp_instance_dtmf_mode_set(media->rtp, AST_RTP_DTMF_MODE_INBAND);
       } else if (channel->session->dtmf == AST_SIP_DTMF_NONE) {
          ast_rtp_instance_set_prop(media->rtp, AST_RTP_PROPERTY_DTMF, 0);
          ast_rtp_instance_dtmf_mode_set(media->rtp, AST_RTP_DTMF_MODE_NONE);
       } else if (channel->session->dtmf == AST_SIP_DTMF_AUTO) {
          if (ast_rtp_instance_dtmf_mode_get(media->rtp) != AST_RTP_DTMF_MODE_RFC2833) {
             /* no RFC4733 negotiated, enable inband */
             ast_rtp_instance_dtmf_mode_set(media->rtp, AST_RTP_DTMF_MODE_INBAND);
          }
       } else if (channel->session->dtmf == AST_SIP_DTMF_AUTO_INFO) {
          ast_rtp_instance_set_prop(media->rtp, AST_RTP_PROPERTY_DTMF, 0);
          if (ast_rtp_instance_dtmf_mode_get(media->rtp) == AST_RTP_DTMF_MODE_INBAND) {
             /* if inband, switch to INFO */
             ast_rtp_instance_dtmf_mode_set(media->rtp, AST_RTP_DTMF_MODE_NONE);
          }
       }
    }
    if (channel->session->dsp) {
       dsp_features = ast_dsp_get_features(channel->session->dsp);
    }
    if (channel->session->dtmf == AST_SIP_DTMF_INBAND ||
       channel->session->dtmf == AST_SIP_DTMF_AUTO) {
       dsp_features |= DSP_FEATURE_DIGIT_DETECT;
    } else {
       dsp_features &= ~DSP_FEATURE_DIGIT_DETECT;
    }
    if (dsp_features) {
       if (!channel->session->dsp) {
          if (!(channel->session->dsp = ast_dsp_new())) {
             ast_channel_unlock(chan);
             return 0;
          }
       }
       ast_dsp_set_features(channel->session->dsp, dsp_features);
    } else if (channel->session->dsp) {
       ast_dsp_free(channel->session->dsp);
       channel->session->dsp = NULL;
    }
    ast_channel_unlock(chan);
    return ast_sip_push_task_wait_serializer(channel->session->serializer, dtmf_mode_refresh_cb, &rdata);
 }
pjsip_acf_media_offer_read()
int pjsip_acf_media_offer_read (struct ast_channel * chan, const char * cmd, char * data, char * buf, size_t len)
PJSIP_MEDIA_OFFER function read callback.
Parameters
chan The channel the function is called on
cmd The name of the function
data Arguments passed to the function
buf Out buffer that should be populated with the data
len Size of the buffer
Return values
0 on success
-1 on failure
Definition at line 1372 of file pjsip/dialplan_functions.c.
References ast_channel_tech(), ast_channel_tech_pvt(), ast_log, AST_MEDIA_TYPE_AUDIO, AST_MEDIA_TYPE_VIDEO, LOG_WARNING, media_offer_read_av(), ast_sip_channel_pvt::session, and type.
 {
    struct ast_sip_channel_pvt *channel;
    if (!chan) {
       ast_log(LOG_WARNING, "No channel was provided to %s function.\n", cmd);
       return -1;
    }
    if (strcmp(ast_channel_tech(chan)->type, "PJSIP")) {
       ast_log(LOG_WARNING, "Cannot call %s on a non-PJSIP channel\n", cmd);
       return -1;
    }
    channel = ast_channel_tech_pvt(chan);
    if (!strcmp(data, "audio")) {
       return media_offer_read_av(channel->session, buf, len, AST_MEDIA_TYPE_AUDIO);
    } else if (!strcmp(data, "video")) {
       return media_offer_read_av(channel->session, buf, len, AST_MEDIA_TYPE_VIDEO);
    } else {
       /* Ensure that the buffer is empty */
       buf[0] = '\0';
    }
    return 0;
 }
pjsip_acf_media_offer_write()
int pjsip_acf_media_offer_write (struct ast_channel * chan, const char * cmd, char * data, const char * value)
PJSIP_MEDIA_OFFER function write callback.
Parameters
chan The channel the function is called on
cmd The name of the function
data Arguments passed to the function
value Value to be set by the function
Return values
0 on success
-1 on failure
Definition at line 1400 of file pjsip/dialplan_functions.c.
References ast_channel_tech(), ast_channel_tech_pvt(), ast_log, AST_MEDIA_TYPE_AUDIO, AST_MEDIA_TYPE_VIDEO, ast_sip_push_task_wait_serializer(), LOG_WARNING, media_offer_write_av(), media_offer_data::media_type, ast_sip_session::serializer, ast_sip_channel_pvt::session, media_offer_data::session, type, and media_offer_data::value.
 {
    struct ast_sip_channel_pvt *channel;
    struct media_offer_data mdata = {
       .value = value
    };
    if (!chan) {
       ast_log(LOG_WARNING, "No channel was provided to %s function.\n", cmd);
       return -1;
    }
    if (strcmp(ast_channel_tech(chan)->type, "PJSIP")) {
       ast_log(LOG_WARNING, "Cannot call %s on a non-PJSIP channel\n", cmd);
       return -1;
    }
    channel = ast_channel_tech_pvt(chan);
    mdata.session = channel->session;
    if (!strcmp(data, "audio")) {
       mdata.media_type = AST_MEDIA_TYPE_AUDIO;
    } else if (!strcmp(data, "video")) {
       mdata.media_type = AST_MEDIA_TYPE_VIDEO;
    }
    return ast_sip_push_task_wait_serializer(channel->session->serializer, media_offer_write_av, &mdata);
 }
pjsip_acf_moh_passthrough_read()
int pjsip_acf_moh_passthrough_read (struct ast_channel * chan, const char * cmd, char * data, char * buf, size_t len)
PJSIP_MOH_PASSTHROUGH function read callback.
Parameters
chan The channel the function is called on
cmd The name of the function
data Arguments passed to the function
buf Out buffer that should be populated with the data
len Size of the buffer
Return values
0 on success
-1 on failure
Definition at line 1457 of file pjsip/dialplan_functions.c.
References ast_channel_lock, ast_channel_tech(), ast_channel_tech_pvt(), ast_channel_unlock, ast_log, AST_YESNO, LOG_WARNING, ast_sip_session::moh_passthrough, ast_sip_channel_pvt::session, and type.
 {
    struct ast_sip_channel_pvt *channel;
    if (!chan) {
       ast_log(LOG_WARNING, "No channel was provided to %s function.\n", cmd);
       return -1;
    }
    if (len < 3) {
       ast_log(LOG_WARNING, "%s: buffer too small\n", cmd);
       return -1;
    }
    ast_channel_lock(chan);
    if (strcmp(ast_channel_tech(chan)->type, "PJSIP")) {
       ast_log(LOG_WARNING, "Cannot call %s on a non-PJSIP channel\n", cmd);
       ast_channel_unlock(chan);
       return -1;
    }
    channel = ast_channel_tech_pvt(chan);
    strncpy(buf, AST_YESNO(channel->session->moh_passthrough), len);
    ast_channel_unlock(chan);
    return 0;
 }
pjsip_acf_moh_passthrough_write()
int pjsip_acf_moh_passthrough_write (struct ast_channel * chan, const char * cmd, char * data, const char * value)
PJSIP_MOH_PASSTHROUGH function write callback.
Parameters
chan The channel the function is called on
cmd The name of the function
data Arguments passed to the function
value Value to be set by the function
Return values
0 on success
-1 on failure
Definition at line 1628 of file pjsip/dialplan_functions.c.
References ast_channel_lock, ast_channel_tech(), ast_channel_tech_pvt(), ast_channel_unlock, ast_log, ast_true(), LOG_WARNING, ast_sip_session::moh_passthrough, ast_sip_channel_pvt::session, and type.
 {
    struct ast_sip_channel_pvt *channel;
    if (!chan) {
       ast_log(LOG_WARNING, "No channel was provided to %s function.\n", cmd);
       return -1;
    }
    ast_channel_lock(chan);
    if (strcmp(ast_channel_tech(chan)->type, "PJSIP")) {
       ast_log(LOG_WARNING, "Cannot call %s on a non-PJSIP channel\n", cmd);
       ast_channel_unlock(chan);
       return -1;
    }
    channel = ast_channel_tech_pvt(chan);
    channel->session->moh_passthrough = ast_true(value);
    ast_channel_unlock(chan);
    return 0;
 }
pjsip_acf_parse_uri_read()
int pjsip_acf_parse_uri_read (struct ast_channel * chan, const char * cmd, char * data, char * buf, size_t len)
PJSIP_PARSE_URI function read callback.
Parameters
chan The channel the function is called on
cmd The name of the function
data Arguments passed to the function
buf Out buffer that should be populated with the data
len Size of the buffer
Return values
0 on success
-1 on failure
Definition at line 1197 of file pjsip/dialplan_functions.c.
References args, AST_APP_ARG, AST_DECLARE_APP_ARGS, ast_log, ast_sip_push_task_wait_serializer(), AST_STANDARD_APP_ARGS, ast_strlen_zero, buf, parse_uri_args::buf, parse_uri_args::buflen, LOG_WARNING, NULL, parse_uri_cb(), parse_uri_args::ret, type, parse_uri_args::type, and parse_uri_args::uri.
 {
    struct parse_uri_args func_args = { 0, };
    AST_DECLARE_APP_ARGS(args,
       AST_APP_ARG(uri_str);
       AST_APP_ARG(type);
    );
    AST_STANDARD_APP_ARGS(args, data);
    if (ast_strlen_zero(args.uri_str)) {
       ast_log(LOG_WARNING, "An URI must be specified when using the '%s' dialplan function\n", cmd);
       return -1;
    }
    if (ast_strlen_zero(args.type)) {
       ast_log(LOG_WARNING, "A type part of the URI must be specified when using the '%s' dialplan function\n", cmd);
       return -1;
    }
    memset(buf, 0, buflen);
    func_args.uri = args.uri_str;
    func_args.type = args.type;
    func_args.buf = buf;
    func_args.buflen = buflen;
    if (ast_sip_push_task_wait_serializer(NULL, parse_uri_cb, &func_args)) {
       ast_log(LOG_WARNING, "Unable to parse URI: failed to push task\n");
       return -1;
    }
    return func_args.ret;
 }
pjsip_acf_session_refresh_write()
int pjsip_acf_session_refresh_write (struct ast_channel * chan, const char * cmd, char * data, const char * value)
PJSIP_SEND_SESSION_REFRESH function write callback.
Parameters
chan The channel the function is called on
cmd the Name of the function
data Arguments passed to the function
value Value to be set by the function
Return values
0 on success
-1 on failure
Definition at line 1671 of file pjsip/dialplan_functions.c.
References ast_channel_name(), ast_channel_tech(), ast_channel_tech_pvt(), ast_log, ast_sip_push_task_wait_serializer(), AST_SIP_SESSION_REFRESH_METHOD_INVITE, AST_SIP_SESSION_REFRESH_METHOD_UPDATE, AST_STATE_UP, LOG_WARNING, refresh_data::method, refresh_write_cb(), ast_sip_session::serializer, ast_sip_channel_pvt::session, refresh_data::session, and type.
 {
    struct ast_sip_channel_pvt *channel;
    struct refresh_data rdata = {
       .method = AST_SIP_SESSION_REFRESH_METHOD_INVITE,
    };
    if (!chan) {
       ast_log(LOG_WARNING, "No channel was provided to %s function.\n", cmd);
       return -1;
    }
    if (ast_channel_state(chan) != AST_STATE_UP) {
       ast_log(LOG_WARNING, "'%s' not allowed on unanswered channel '%s'.\n", cmd, ast_channel_name(chan));
       return -1;
    }
    if (strcmp(ast_channel_tech(chan)->type, "PJSIP")) {
       ast_log(LOG_WARNING, "Cannot call %s on a non-PJSIP channel\n", cmd);
       return -1;
    }
    channel = ast_channel_tech_pvt(chan);
    rdata.session = channel->session;
    if (!strcmp(value, "invite")) {
       rdata.method = AST_SIP_SESSION_REFRESH_METHOD_INVITE;
    } else if (!strcmp(value, "update")) {
       rdata.method = AST_SIP_SESSION_REFRESH_METHOD_UPDATE;
    }
    return ast_sip_push_task_wait_serializer(channel->session->serializer, refresh_write_cb, &rdata);
 }