Asterisk - The Open Source Telephony Project: pjsip_global_headers.c File Reference
pjsip_global_headers.c File Reference
#include "asterisk.h"
#include <pjsip.h>
#include <pjlib.h>
#include "asterisk/res_pjsip.h"
#include "asterisk/linkedlists.h"
#include "include/res_pjsip_private.h"
Data Structures
struct header
struct header_list
Functions
static int add_header (struct header_list *headers, const char *name, const char *value, int replace)
static void add_headers_to_message (struct header_list *headers, pjsip_tx_data *tdata)
static pj_status_t add_request_headers (pjsip_tx_data *tdata)
static pj_status_t add_response_headers (pjsip_tx_data *tdata)
static struct header * alloc_header (const char *name, const char *value)
int ast_sip_add_global_request_header (const char *name, const char *value, int replace)
int ast_sip_add_global_response_header (const char *name, const char *value, int replace)
void ast_sip_destroy_global_headers (void)
void ast_sip_initialize_global_headers (void)
static void destroy_header (struct header *to_destroy)
static void destroy_headers (struct header_list *headers)
static void remove_header (struct header_list *headers, const char *to_remove)
Variables
static pjsip_module global_header_mod
static unsigned int handled_id = 0xCA115785
Indicator we've already handled a specific request/response.
static struct header_list request_headers
static struct header_list response_headers
Function Documentation
add_header()
static int add_header (struct header_list * headers, const char * name, const char * value, int replace) static
Definition at line 130 of file pjsip_global_headers.c.
References alloc_header(), AST_LIST_INSERT_TAIL, AST_RWLIST_UNLOCK, AST_RWLIST_WRLOCK, ast_strlen_zero, header::next, NULL, and remove_header().
Referenced by ast_sip_add_global_request_header(), and ast_sip_add_global_response_header().
 {
    struct header *to_add = NULL;
    if (!ast_strlen_zero(value)) {
       to_add = alloc_header(name, value);
       if (!to_add) {
          return -1;
       }
    }
    AST_RWLIST_WRLOCK(headers);
    if (replace) {
       remove_header(headers, name);
    }
    if (to_add) {
       AST_LIST_INSERT_TAIL(headers, to_add, next);
    }
    AST_RWLIST_UNLOCK(headers);
    return 0;
 }
add_headers_to_message()
static void add_headers_to_message (struct header_list * headers, pjsip_tx_data * tdata) static
Definition at line 82 of file pjsip_global_headers.c.
References AST_LIST_TRAVERSE, AST_RWLIST_RDLOCK, AST_RWLIST_UNLOCK, ast_sip_add_header(), global_header_mod, handled_id, lock, header::name, header::next, NULL, SCOPED_LOCK, and header::value.
Referenced by add_request_headers(), and add_response_headers().
 {
    struct header *iter;
    SCOPED_LOCK(lock, headers, AST_RWLIST_RDLOCK, AST_RWLIST_UNLOCK);
    if (tdata->mod_data[global_header_mod.id] == &handled_id) {
       return;
    }
    AST_LIST_TRAVERSE(headers, iter, next) {
       pj_str_t name;
       pjsip_generic_string_hdr *hdr;
       hdr = pjsip_msg_find_hdr_by_name(tdata->msg, pj_cstr(&name, iter->name), NULL);
       if (hdr) {
          continue;
       }
       ast_sip_add_header(tdata, iter->name, iter->value);
    };
    tdata->mod_data[global_header_mod.id] = &handled_id;
 }
add_request_headers()
static pj_status_t add_request_headers (pjsip_tx_data * tdata) static
Definition at line 103 of file pjsip_global_headers.c.
References add_headers_to_message(), and request_headers.
 {
    add_headers_to_message(&request_headers, tdata);
    return PJ_SUCCESS;
 }
add_response_headers()
static pj_status_t add_response_headers (pjsip_tx_data * tdata) static
Definition at line 110 of file pjsip_global_headers.c.
References add_headers_to_message(), and response_headers.
 {
    add_headers_to_message(&response_headers, tdata);
    return PJ_SUCCESS;
 }
alloc_header()
static struct header* alloc_header (const char * name, const char * value) static
Definition at line 55 of file pjsip_global_headers.c.
References ast_calloc_with_stringfields, ast_string_field_set, and NULL.
Referenced by add_header().
 {
    struct header *alloc;
    alloc = ast_calloc_with_stringfields(1, struct header, 32);
    if (!alloc) {
       return NULL;
    }
    ast_string_field_set(alloc, name, name);
    ast_string_field_set(alloc, value, value);
    return alloc;
 }
ast_sip_add_global_request_header()
int ast_sip_add_global_request_header (const char * name, const char * value, int replace)
Definition at line 153 of file pjsip_global_headers.c.
References add_header(), and request_headers.
Referenced by global_apply().
 {
    return add_header(&request_headers, name, value, replace);
 }
ast_sip_add_global_response_header()
int ast_sip_add_global_response_header (const char * name, const char * value, int replace)
Definition at line 158 of file pjsip_global_headers.c.
References add_header(), and response_headers.
Referenced by global_apply().
 {
    return add_header(&response_headers, name, value, replace);
 }
ast_sip_destroy_global_headers()
void ast_sip_destroy_global_headers (void)
Definition at line 181 of file pjsip_global_headers.c.
References ast_sip_unregister_service(), destroy_headers(), global_header_mod, request_headers, and response_headers.
Referenced by unload_pjsip().
 {
    destroy_headers(&request_headers);
    destroy_headers(&response_headers);
    ast_sip_unregister_service(&global_header_mod);
 }
ast_sip_initialize_global_headers()
void ast_sip_initialize_global_headers (void)
Definition at line 163 of file pjsip_global_headers.c.
References AST_RWLIST_HEAD_INIT, ast_sip_register_service(), global_header_mod, request_headers, and response_headers.
Referenced by load_module().
 {
    AST_RWLIST_HEAD_INIT(&request_headers);
    AST_RWLIST_HEAD_INIT(&response_headers);
    ast_sip_register_service(&global_header_mod);
 }
destroy_header()
static void destroy_header (struct header * to_destroy) static
Definition at line 71 of file pjsip_global_headers.c.
References ast_free, and ast_string_field_free_memory.
Referenced by destroy_headers(), and remove_header().
 {
    ast_string_field_free_memory(to_destroy);
    ast_free(to_destroy);
 }
destroy_headers()
static void destroy_headers (struct header_list * headers) static
Definition at line 171 of file pjsip_global_headers.c.
References AST_RWLIST_HEAD_DESTROY, AST_RWLIST_REMOVE_HEAD, destroy_header(), and header::next.
Referenced by ast_sip_destroy_global_headers().
 {
    struct header *iter;
    while ((iter = AST_RWLIST_REMOVE_HEAD(headers, next))) {
       destroy_header(iter);
    }
    AST_RWLIST_HEAD_DESTROY(headers);
 }
remove_header()
static void remove_header (struct header_list * headers, const char * to_remove) static
Definition at line 117 of file pjsip_global_headers.c.
References AST_LIST_REMOVE_CURRENT, AST_LIST_TRAVERSE_SAFE_BEGIN, AST_LIST_TRAVERSE_SAFE_END, destroy_header(), header::name, and header::next.
Referenced by add_header().
 {
    struct header *iter;
    AST_LIST_TRAVERSE_SAFE_BEGIN(headers, iter, next) {
       if (!strcasecmp(iter->name, to_remove)) {
          AST_LIST_REMOVE_CURRENT(next);
          destroy_header(iter);
          break;
       }
    }
    AST_LIST_TRAVERSE_SAFE_END;
 }
Variable Documentation
global_header_mod
pjsip_module global_header_mod static
Definition at line 40 of file pjsip_global_headers.c.
Referenced by add_headers_to_message(), ast_sip_destroy_global_headers(), and ast_sip_initialize_global_headers().
handled_id
unsigned int handled_id = 0xCA115785 static
Indicator we've already handled a specific request/response.
PJSIP tends to reuse requests and responses. If we already have added headers to a request or response, we mark the message with this value so that we know not to re-add the headers again.
Definition at line 38 of file pjsip_global_headers.c.
Referenced by add_headers_to_message().
request_headers
struct header_list request_headers static
Definition at line 79 of file pjsip_global_headers.c.
Referenced by add_request_headers(), ast_sip_add_global_request_header(), ast_sip_destroy_global_headers(), ast_sip_initialize_global_headers(), and remove_request_headers().
response_headers
struct header_list response_headers static
Definition at line 80 of file pjsip_global_headers.c.
Referenced by add_response_headers(), ast_sip_add_global_response_header(), ast_sip_destroy_global_headers(), and ast_sip_initialize_global_headers().