Asterisk - The Open Source Telephony Project: chan_rtp.c File Reference
chan_rtp.c File Reference
Module: Asterisk Channel Drivers
RTP (Multicast and Unicast) Media Channel.
#include "asterisk.h"
#include "asterisk/channel.h"
#include "asterisk/module.h"
#include "asterisk/pbx.h"
#include "asterisk/acl.h"
#include "asterisk/app.h"
#include "asterisk/rtp_engine.h"
#include "asterisk/causes.h"
#include "asterisk/format_cache.h"
#include "asterisk/multicast_rtp.h"
#include "asterisk/dns_core.h"
Enumerations
enum { OPT_RTP_CODEC = (1 << 0), OPT_RTP_ENGINE = (1 << 1) }
enum { OPT_ARG_RTP_CODEC, OPT_ARG_RTP_ENGINE, OPT_ARG_ARRAY_SIZE }
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static struct ast_format * derive_format_from_cap (struct ast_format_cap *cap)
static int load_module (void)
Function called when our module is loaded.
static struct ast_channel * multicast_rtp_request (const char *type, struct ast_format_cap *cap, const struct ast_assigned_ids *assignedids, const struct ast_channel *requestor, const char *data, int *cause)
Function called when we should prepare to call the multicast destination.
static int rtp_call (struct ast_channel *ast, const char *dest, int timeout)
Function called when we should actually call the destination.
static int rtp_hangup (struct ast_channel *ast)
Function called when we should hang the channel up.
static struct ast_frame * rtp_read (struct ast_channel *ast)
Function called when we should read a frame from the channel.
static int rtp_write (struct ast_channel *ast, struct ast_frame *f)
Function called when we should write a frame to the channel.
static struct ast_channel * unicast_rtp_request (const char *type, struct ast_format_cap *cap, const struct ast_assigned_ids *assignedids, const struct ast_channel *requestor, const char *data, int *cause)
Function called when we should prepare to call the unicast destination.
static int unload_module (void)
Function called when our module is unloaded.
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "RTP Media Channel" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_CHANNEL_DRIVER, .requires = "res_rtp_multicast", }
static const struct ast_module_info * ast_module_info = &__mod_info
static struct ast_channel_tech multicast_rtp_tech
static const struct ast_app_option unicast_rtp_options [128] = { [ 'c' ] = { .flag = OPT_RTP_CODEC , .arg_index = OPT_ARG_RTP_CODEC + 1 }, [ 'e' ] = { .flag = OPT_RTP_ENGINE , .arg_index = OPT_ARG_RTP_ENGINE + 1 }, }
static struct ast_channel_tech unicast_rtp_tech
Detailed Description
RTP (Multicast and Unicast) Media Channel.
Author
Joshua Colp jcolp.nosp@m.@dig.nosp@m.ium.c.nosp@m.om
Andreas 'MacBrody' Broadmann andre.nosp@m.as.b.nosp@m.rodma.nosp@m.nn@g.nosp@m.mail..nosp@m.com
Definition in file chan_rtp.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
OPT_RTP_CODEC
OPT_RTP_ENGINE
Definition at line 249 of file chan_rtp.c.
      {
    OPT_RTP_CODEC =  (1 << 0),
    OPT_RTP_ENGINE = (1 << 1),
 };
anonymous enum
anonymous enum
Enumerator
OPT_ARG_RTP_CODEC
OPT_ARG_RTP_ENGINE
OPT_ARG_ARRAY_SIZE
Definition at line 254 of file chan_rtp.c.
      {
    OPT_ARG_RTP_CODEC,
    OPT_ARG_RTP_ENGINE,
    /* note: this entry _MUST_ be the last one in the enum */
    OPT_ARG_ARRAY_SIZE
 };
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 451 of file chan_rtp.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 451 of file chan_rtp.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 451 of file chan_rtp.c.
derive_format_from_cap()
static struct ast_format* derive_format_from_cap (struct ast_format_cap * cap) static
Definition at line 122 of file chan_rtp.c.
References ast_format_cap_count(), ast_format_cap_get_format(), ast_format_slin, and ast_format_ulaw.
Referenced by multicast_rtp_request(), and unicast_rtp_request().
 {
    struct ast_format *fmt = ast_format_cap_get_format(cap, 0);
    if (ast_format_cap_count(cap) == 1 && fmt == ast_format_slin) {
       /*
        * Because we have no SDP, we must use one of the static RTP payload
        * assignments. Signed linear @ 8kHz does not map, so if that is our
        * only capability, we force μ-law instead.
        */
       fmt = ast_format_ulaw;
    }
    return fmt;
 }
load_module()
static int load_module (void) static
Function called when our module is loaded.
Definition at line 419 of file chan_rtp.c.
References ast_channel_register(), ast_format_cap_alloc, ast_format_cap_append_by_type(), AST_FORMAT_CAP_FLAG_DEFAULT, ast_log, AST_MEDIA_TYPE_UNKNOWN, AST_MODFLAG_LOAD_ORDER, AST_MODPRI_CHANNEL_DRIVER, AST_MODULE_INFO(), AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, AST_MODULE_SUPPORT_CORE, ASTERISK_GPL_KEY, ast_channel_tech::capabilities, LOG_ERROR, and unload_module().
 {
    if (!(multicast_rtp_tech.capabilities = ast_format_cap_alloc(AST_FORMAT_CAP_FLAG_DEFAULT))) {
       return AST_MODULE_LOAD_DECLINE;
    }
    ast_format_cap_append_by_type(multicast_rtp_tech.capabilities, AST_MEDIA_TYPE_UNKNOWN);
    if (ast_channel_register(&multicast_rtp_tech)) {
       ast_log(LOG_ERROR, "Unable to register channel class 'MulticastRTP'\n");
       unload_module();
       return AST_MODULE_LOAD_DECLINE;
    }
    if (!(unicast_rtp_tech.capabilities = ast_format_cap_alloc(AST_FORMAT_CAP_FLAG_DEFAULT))) {
       unload_module();
       return AST_MODULE_LOAD_DECLINE;
    }
    ast_format_cap_append_by_type(unicast_rtp_tech.capabilities, AST_MEDIA_TYPE_UNKNOWN);
    if (ast_channel_register(&unicast_rtp_tech)) {
       ast_log(LOG_ERROR, "Unable to register channel class 'UnicastRTP'\n");
       unload_module();
       return AST_MODULE_LOAD_DECLINE;
    }
    return AST_MODULE_LOAD_SUCCESS;
 }
multicast_rtp_request()
static struct ast_channel * multicast_rtp_request (const char * type, struct ast_format_cap * cap, const struct ast_assigned_ids * assignedids, const struct ast_channel * requestor, const char * data, int * cause) static
Function called when we should prepare to call the multicast destination.
Definition at line 139 of file chan_rtp.c.
References ao2_cleanup, ao2_ref, args, AST_APP_ARG, AST_CAUSE_FAILURE, ast_channel_alloc, ast_channel_nativeformats_set(), ast_channel_set_rawreadformat(), ast_channel_set_rawwriteformat(), ast_channel_set_readformat(), ast_channel_set_writeformat(), ast_channel_tech_pvt_set(), ast_channel_tech_set(), ast_channel_uniqueid(), ast_channel_unlock, AST_DECLARE_APP_ARGS, ast_format_cap_alloc, ast_format_cap_append, AST_FORMAT_CAP_FLAG_DEFAULT, ast_log, ast_multicast_rtp_create_options(), ast_multicast_rtp_free_options(), ast_multicast_rtp_options_get_format(), AST_NONSTANDARD_APP_ARGS, ast_rtp_instance_destroy(), ast_rtp_instance_new(), ast_rtp_instance_set_channel_id(), ast_rtp_instance_set_remote_address, ast_sockaddr_parse(), ast_sockaddr_setnull(), AST_STATE_DOWN, ast_strdupa, ast_strlen_zero, derive_format_from_cap(), LOG_ERROR, NULL, options, parse(), and PARSE_PORT_REQUIRE.
 {
    char *parse;
    struct ast_rtp_instance *instance;
    struct ast_sockaddr control_address;
    struct ast_sockaddr destination_address;
    struct ast_channel *chan;
    struct ast_format_cap *caps = NULL;
    struct ast_format *fmt = NULL;
    AST_DECLARE_APP_ARGS(args,
       AST_APP_ARG(type);
       AST_APP_ARG(destination);
       AST_APP_ARG(control);
       AST_APP_ARG(options);
    );
    struct ast_multicast_rtp_options *mcast_options = NULL;
    if (ast_strlen_zero(data)) {
       ast_log(LOG_ERROR, "A multicast type and destination must be given to the 'MulticastRTP' channel\n");
       goto failure;
    }
    parse = ast_strdupa(data);
    AST_NONSTANDARD_APP_ARGS(args, parse, '/');
    if (ast_strlen_zero(args.type)) {
       ast_log(LOG_ERROR, "Type is required for the 'MulticastRTP' channel\n");
       goto failure;
    }
    if (ast_strlen_zero(args.destination)) {
       ast_log(LOG_ERROR, "Destination is required for the 'MulticastRTP' channel\n");
       goto failure;
    }
    if (!ast_sockaddr_parse(&destination_address, args.destination, PARSE_PORT_REQUIRE)) {
       ast_log(LOG_ERROR, "Destination address '%s' could not be parsed\n",
          args.destination);
       goto failure;
    }
    ast_sockaddr_setnull(&control_address);
    if (!ast_strlen_zero(args.control)
       && !ast_sockaddr_parse(&control_address, args.control, PARSE_PORT_REQUIRE)) {
       ast_log(LOG_ERROR, "Control address '%s' could not be parsed\n", args.control);
       goto failure;
    }
    mcast_options = ast_multicast_rtp_create_options(args.type, args.options);
    if (!mcast_options) {
       goto failure;
    }
    fmt = ast_multicast_rtp_options_get_format(mcast_options);
    if (!fmt) {
       fmt = derive_format_from_cap(cap);
    }
    if (!fmt) {
       ast_log(LOG_ERROR, "No codec available for sending RTP to '%s'\n",
          args.destination);
       goto failure;
    }
    caps = ast_format_cap_alloc(AST_FORMAT_CAP_FLAG_DEFAULT);
    if (!caps) {
       goto failure;
    }
    instance = ast_rtp_instance_new("multicast", NULL, &control_address, mcast_options);
    if (!instance) {
       ast_log(LOG_ERROR,
          "Could not create '%s' multicast RTP instance for sending media to '%s'\n",
          args.type, args.destination);
       goto failure;
    }
    chan = ast_channel_alloc(1, AST_STATE_DOWN, "", "", "", "", "", assignedids,
       requestor, 0, "MulticastRTP/%p", instance);
    if (!chan) {
       ast_rtp_instance_destroy(instance);
       goto failure;
    }
    ast_rtp_instance_set_channel_id(instance, ast_channel_uniqueid(chan));
    ast_rtp_instance_set_remote_address(instance, &destination_address);
    ast_channel_tech_set(chan, &multicast_rtp_tech);
    ast_format_cap_append(caps, fmt, 0);
    ast_channel_nativeformats_set(chan, caps);
    ast_channel_set_writeformat(chan, fmt);
    ast_channel_set_rawwriteformat(chan, fmt);
    ast_channel_set_readformat(chan, fmt);
    ast_channel_set_rawreadformat(chan, fmt);
    ast_channel_tech_pvt_set(chan, instance);
    ast_channel_unlock(chan);
    ao2_ref(fmt, -1);
    ao2_ref(caps, -1);
    ast_multicast_rtp_free_options(mcast_options);
    return chan;
 failure:
    ao2_cleanup(fmt);
    ao2_cleanup(caps);
    ast_multicast_rtp_free_options(mcast_options);
    *cause = AST_CAUSE_FAILURE;
    return NULL;
 }
rtp_call()
static int rtp_call (struct ast_channel * ast, const char * dest, int timeout) static
Function called when we should actually call the destination.
Definition at line 101 of file chan_rtp.c.
References ast_channel_tech_pvt(), AST_CONTROL_ANSWER, ast_queue_control(), and ast_rtp_instance_activate().
 {
    struct ast_rtp_instance *instance = ast_channel_tech_pvt(ast);
    ast_queue_control(ast, AST_CONTROL_ANSWER);
    return ast_rtp_instance_activate(instance);
 }
rtp_hangup()
static int rtp_hangup (struct ast_channel * ast) static
Function called when we should hang the channel up.
Definition at line 111 of file chan_rtp.c.
References ast_channel_tech_pvt(), ast_channel_tech_pvt_set(), ast_rtp_instance_destroy(), and NULL.
 {
    struct ast_rtp_instance *instance = ast_channel_tech_pvt(ast);
    ast_rtp_instance_destroy(instance);
    ast_channel_tech_pvt_set(ast, NULL);
    return 0;
 }
rtp_read()
static struct ast_frame * rtp_read (struct ast_channel * ast) static
Function called when we should read a frame from the channel.
Definition at line 79 of file chan_rtp.c.
References ast_channel_fdno(), ast_channel_tech_pvt(), ast_null_frame, and ast_rtp_instance_read().
 {
    struct ast_rtp_instance *instance = ast_channel_tech_pvt(ast);
    int fdno = ast_channel_fdno(ast);
    switch (fdno) {
    case 0:
       return ast_rtp_instance_read(instance, 0);
    default:
       return &ast_null_frame;
    }
 }
rtp_write()
static int rtp_write (struct ast_channel * ast, struct ast_frame * f) static
Function called when we should write a frame to the channel.
Definition at line 93 of file chan_rtp.c.
References ast_channel_tech_pvt(), and ast_rtp_instance_write().
 {
    struct ast_rtp_instance *instance = ast_channel_tech_pvt(ast);
    return ast_rtp_instance_write(instance, f);
 }
unicast_rtp_request()
static struct ast_channel * unicast_rtp_request (const char * type, struct ast_format_cap * cap, const struct ast_assigned_ids * assignedids, const struct ast_channel * requestor, const char * data, int * cause) static
Function called when we should prepare to call the unicast destination.
Definition at line 269 of file chan_rtp.c.
References ao2_cleanup, ao2_ref, args, AST_APP_ARG, ast_app_parse_options(), AST_CAUSE_FAILURE, ast_channel_alloc, ast_channel_nativeformats_set(), ast_channel_set_fd(), ast_channel_set_rawreadformat(), ast_channel_set_rawwriteformat(), ast_channel_set_readformat(), ast_channel_set_writeformat(), ast_channel_tech_pvt_set(), ast_channel_tech_set(), ast_channel_uniqueid(), ast_channel_unlock, AST_DECLARE_APP_ARGS, ast_dns_resolve_ipv6_and_ipv4(), ast_format_cache_get, ast_format_cap_alloc, ast_format_cap_append, AST_FORMAT_CAP_FLAG_DEFAULT, ast_log, AST_NONSTANDARD_APP_ARGS, ast_ouraddrfor(), ast_rtp_instance_destroy(), ast_rtp_instance_fd(), ast_rtp_instance_get_local_address(), ast_rtp_instance_new(), ast_rtp_instance_set_channel_id(), ast_rtp_instance_set_remote_address, ast_sockaddr_copy(), ast_sockaddr_parse(), ast_sockaddr_split_hostport(), ast_sockaddr_stringify_addr(), ast_sockaddr_stringify_port(), AST_STATE_DOWN, ast_strdupa, ast_strlen_zero, ast_test_flag, derive_format_from_cap(), host, LOG_ERROR, NULL, OPT_ARG_ARRAY_SIZE, OPT_ARG_RTP_CODEC, OPT_ARG_RTP_ENGINE, OPT_RTP_CODEC, OPT_RTP_ENGINE, options, parse(), PARSE_PORT_REQUIRE, pbx_builtin_setvar_helper(), S_COR, S_OR, and unicast_rtp_options.
 {
    char *parse;
    struct ast_rtp_instance *instance;
    struct ast_sockaddr address;
    struct ast_sockaddr local_address;
    struct ast_channel *chan;
    struct ast_format_cap *caps = NULL;
    struct ast_format *fmt = NULL;
    const char *engine_name;
    AST_DECLARE_APP_ARGS(args,
       AST_APP_ARG(destination);
       AST_APP_ARG(options);
    );
    struct ast_flags opts = { 0, };
    char *opt_args[OPT_ARG_ARRAY_SIZE];
    if (ast_strlen_zero(data)) {
       ast_log(LOG_ERROR, "Destination is required for the 'UnicastRTP' channel\n");
       goto failure;
    }
    parse = ast_strdupa(data);
    AST_NONSTANDARD_APP_ARGS(args, parse, '/');
    if (ast_strlen_zero(args.destination)) {
       ast_log(LOG_ERROR, "Destination is required for the 'UnicastRTP' channel\n");
       goto failure;
    }
    if (!ast_sockaddr_parse(&address, args.destination, PARSE_PORT_REQUIRE)) {
        int rc;
        char *host;
        char *port;
        rc = ast_sockaddr_split_hostport(args.destination, &host, &port, PARSE_PORT_REQUIRE);
        if (!rc) {
            ast_log(LOG_ERROR, "Unable to parse destination '%s' into host and port\n", args.destination);
            goto failure;
        }
        rc = ast_dns_resolve_ipv6_and_ipv4(&address, host, port);
        if (rc != 0) {
            ast_log(LOG_ERROR, "Unable to resolve host '%s'\n", host);
            goto failure;
        }
    }
    if (!ast_strlen_zero(args.options)
       && ast_app_parse_options(unicast_rtp_options, &opts, opt_args,
          ast_strdupa(args.options))) {
       ast_log(LOG_ERROR, "'UnicastRTP' channel options '%s' parse error\n",
          args.options);
       goto failure;
    }
    if (ast_test_flag(&opts, OPT_RTP_CODEC)
       && !ast_strlen_zero(opt_args[OPT_ARG_RTP_CODEC])) {
       fmt = ast_format_cache_get(opt_args[OPT_ARG_RTP_CODEC]);
       if (!fmt) {
          ast_log(LOG_ERROR, "Codec '%s' not found for sending RTP to '%s'\n",
             opt_args[OPT_ARG_RTP_CODEC], args.destination);
          goto failure;
       }
    } else {
       fmt = derive_format_from_cap(cap);
       if (!fmt) {
          ast_log(LOG_ERROR, "No codec available for sending RTP to '%s'\n",
             args.destination);
          goto failure;
       }
    }
    caps = ast_format_cap_alloc(AST_FORMAT_CAP_FLAG_DEFAULT);
    if (!caps) {
       goto failure;
    }
    engine_name = S_COR(ast_test_flag(&opts, OPT_RTP_ENGINE),
       opt_args[OPT_ARG_RTP_ENGINE], "asterisk");
    ast_sockaddr_copy(&local_address, &address);
    if (ast_ouraddrfor(&address, &local_address)) {
       ast_log(LOG_ERROR, "Could not get our address for sending media to '%s'\n",
          args.destination);
       goto failure;
    }
    instance = ast_rtp_instance_new(engine_name, NULL, &local_address, NULL);
    if (!instance) {
       ast_log(LOG_ERROR,
          "Could not create %s RTP instance for sending media to '%s'\n",
          S_OR(engine_name, "default"), args.destination);
       goto failure;
    }
    chan = ast_channel_alloc(1, AST_STATE_DOWN, "", "", "", "", "", assignedids,
       requestor, 0, "UnicastRTP/%s-%p", args.destination, instance);
    if (!chan) {
       ast_rtp_instance_destroy(instance);
       goto failure;
    }
    ast_rtp_instance_set_channel_id(instance, ast_channel_uniqueid(chan));
    ast_rtp_instance_set_remote_address(instance, &address);
    ast_channel_set_fd(chan, 0, ast_rtp_instance_fd(instance, 0));
    ast_channel_tech_set(chan, &unicast_rtp_tech);
    ast_format_cap_append(caps, fmt, 0);
    ast_channel_nativeformats_set(chan, caps);
    ast_channel_set_writeformat(chan, fmt);
    ast_channel_set_rawwriteformat(chan, fmt);
    ast_channel_set_readformat(chan, fmt);
    ast_channel_set_rawreadformat(chan, fmt);
    ast_channel_tech_pvt_set(chan, instance);
    pbx_builtin_setvar_helper(chan, "UNICASTRTP_LOCAL_ADDRESS",
       ast_sockaddr_stringify_addr(&local_address));
    ast_rtp_instance_get_local_address(instance, &local_address);
    pbx_builtin_setvar_helper(chan, "UNICASTRTP_LOCAL_PORT",
       ast_sockaddr_stringify_port(&local_address));
    ast_channel_unlock(chan);
    ao2_ref(fmt, -1);
    ao2_ref(caps, -1);
    return chan;
 failure:
    ao2_cleanup(fmt);
    ao2_cleanup(caps);
    *cause = AST_CAUSE_FAILURE;
    return NULL;
 }
unload_module()
static int unload_module (void) static
Function called when our module is unloaded.
Definition at line 405 of file chan_rtp.c.
References ao2_cleanup, ast_channel_unregister(), ast_channel_tech::capabilities, and NULL.
Referenced by load_module().
 {
    ast_channel_unregister(&multicast_rtp_tech);
    ao2_cleanup(multicast_rtp_tech.capabilities);
    multicast_rtp_tech.capabilities = NULL;
    ast_channel_unregister(&unicast_rtp_tech);
    ao2_cleanup(unicast_rtp_tech.capabilities);
    unicast_rtp_tech.capabilities = NULL;
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "RTP Media Channel" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_CHANNEL_DRIVER, .requires = "res_rtp_multicast", } static
Definition at line 451 of file chan_rtp.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 451 of file chan_rtp.c.
multicast_rtp_tech
struct ast_channel_tech multicast_rtp_tech static
Definition at line 57 of file chan_rtp.c.
unicast_rtp_options
const struct ast_app_option unicast_rtp_options[128] = { [ 'c' ] = { .flag = OPT_RTP_CODEC , .arg_index = OPT_ARG_RTP_CODEC + 1 }, [ 'e' ] = { .flag = OPT_RTP_ENGINE , .arg_index = OPT_ARG_RTP_ENGINE + 1 }, } static
Definition at line 266 of file chan_rtp.c.
Referenced by unicast_rtp_request().
unicast_rtp_tech
struct ast_channel_tech unicast_rtp_tech static
Definition at line 68 of file chan_rtp.c.