Asterisk - The Open Source Telephony Project: res_chan_stats.c File Reference
res_chan_stats.c File Reference
#include "asterisk.h"
#include "asterisk/module.h"
#include "asterisk/stasis_channels.h"
#include "asterisk/stasis_message_router.h"
#include "asterisk/statsd.h"
#include "asterisk/time.h"
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static void default_route (void *data, struct stasis_subscription *sub, struct stasis_message *message)
Router callback for any message that doesn't otherwise have a route.
static int load_module (void)
static void statsmaker (void *data, struct stasis_subscription *sub, struct stasis_message *message)
Subscription callback for all channel messages.
static int unload_module (void)
static void updates (void *data, struct stasis_subscription *sub, struct stasis_message *message)
Router callback for ast_channel_snapshot_update messages.
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_DEFAULT , .description = "Example of how to use Stasis" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_EXTENDED, .load = load_module, .unload = unload_module, .requires = "res_statsd" }
static const struct ast_module_info * ast_module_info = &__mod_info
static struct stasis_message_router * router
static struct stasis_subscription * sub
Statsd channel stats. Exmaple of how to subscribe to Stasis events.
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 177 of file res_chan_stats.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 177 of file res_chan_stats.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 177 of file res_chan_stats.c.
default_route()
static void default_route (void * data, struct stasis_subscription * sub, struct stasis_message * message) static
Router callback for any message that doesn't otherwise have a route.
Parameters
data Data pointer given when added to router.
sub This subscription.
topic The topic the message was posted to. This is not necessarily the topic you subscribed to, since messages may be forwarded between topics.
message The message itself.
Definition at line 130 of file res_chan_stats.c.
References stasis_subscription_final_message().
Referenced by load_module().
 {
    if (stasis_subscription_final_message(sub, message)) {
       /* Much like with the regular subscription, you may need to
        * perform some cleanup when done with a message router. You
        * can look for the final message in the default route.
        */
       return;
    }
 }
load_module()
static int load_module (void) static
Definition at line 151 of file res_chan_stats.c.
References ast_channel_snapshot_type(), ast_channel_topic_all(), AST_MODFLAG_DEFAULT, AST_MODULE_INFO(), AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, AST_MODULE_SUPPORT_EXTENDED, ASTERISK_GPL_KEY, default_route(), NULL, stasis_message_router_add(), stasis_message_router_create, stasis_message_router_set_default(), stasis_subscribe, statsmaker(), unload_module(), and updates().
 {
    /* You can create a message router to route messages by type */
    router = stasis_message_router_create(
       ast_channel_topic_all());
    if (!router) {
       return AST_MODULE_LOAD_DECLINE;
    }
    stasis_message_router_add(router, ast_channel_snapshot_type(),
       updates, NULL);
    stasis_message_router_set_default(router, default_route, NULL);
    /* Or a subscription to receive all of the messages from a topic */
    sub = stasis_subscribe(ast_channel_topic_all(), statsmaker, NULL);
    if (!sub) {
       unload_module();
       return AST_MODULE_LOAD_DECLINE;
    }
    return AST_MODULE_LOAD_SUCCESS;
 }
statsmaker()
static void statsmaker (void * data, struct stasis_subscription * sub, struct stasis_message * message) static
Subscription callback for all channel messages.
Parameters
data Data pointer given when creating the subscription.
sub This subscription.
topic The topic the message was posted to. This is not necessarily the topic you subscribed to, since messages may be forwarded between topics.
message The message itself.
Definition at line 57 of file res_chan_stats.c.
References ast_free, ast_statsd_log(), AST_STATSD_METER, ast_str_buffer(), ast_str_create, ast_str_set(), NULL, RAII_VAR, stasis_message_type(), stasis_message_type_name(), and stasis_subscription_final_message().
Referenced by load_module().
 {
    RAII_VAR(struct ast_str *, metric, NULL, ast_free);
    if (stasis_subscription_final_message(sub, message)) {
       /* Normally, data points to an object that must be cleaned up.
        * The final message is an unsubscribe notification that's
        * guaranteed to be the last message this subscription receives.
        * This would be a safe place to kick off any needed cleanup.
        */
       return;
    }
    /* For no good reason, count message types */
    metric = ast_str_create(80);
    if (metric) {
       ast_str_set(&metric, 0, "stasis.message.%s",
          stasis_message_type_name(stasis_message_type(message)));
       ast_statsd_log(ast_str_buffer(metric), AST_STATSD_METER, 1);
    }
 }
unload_module()
static int unload_module (void) static
Definition at line 142 of file res_chan_stats.c.
References NULL, stasis_message_router_unsubscribe_and_join(), and stasis_unsubscribe_and_join().
Referenced by load_module().
 {
    stasis_unsubscribe_and_join(sub);
    sub = NULL;
    stasis_message_router_unsubscribe_and_join(router);
    router = NULL;
    return 0;
 }
updates()
static void updates (void * data, struct stasis_subscription * sub, struct stasis_message * message) static
Router callback for ast_channel_snapshot_update messages.
Parameters
data Data pointer given when added to router.
sub This subscription.
topic The topic the message was posted to. This is not necessarily the topic you subscribed to, since messages may be forwarded between topics.
message The message itself.
Definition at line 89 of file res_chan_stats.c.
References AST_FLAG_DEAD, AST_STATSD_GAUGE, ast_statsd_log(), ast_statsd_log_string(), AST_STATSD_TIMER, ast_test_flag, ast_tvdiff_ms(), ast_channel_snapshot::base, ast_channel_snapshot_base::creationtime, ast_channel_snapshot::flags, ast_channel_snapshot_update::new_snapshot, ast_channel_snapshot_update::old_snapshot, stasis_message_data(), stasis_message_timestamp(), and update().
Referenced by load_module().
 {
    /* Since this came from a message router, we know the type of the
     * message. We can cast the data without checking its type.
     */
    struct ast_channel_snapshot_update *update = stasis_message_data(message);
    /* There are three types of channel snapshot updates.
     * !old && new -> Initial channel creation
     * old && new -> Updated channel snapshot
     * old && dead -> Final channel snapshot
     */
    if (!update->old_snapshot && update->new_snapshot) {
       /* Initial channel snapshot; count a channel creation */
       ast_statsd_log_string("channels.count", AST_STATSD_GAUGE, "+1", 1.0);
    } else if (update->old_snapshot && ast_test_flag(&update->new_snapshot->flags, AST_FLAG_DEAD)) {
       /* Channel is gone. Compute the age of the channel and post
        * that, as well as decrementing the channel count.
        */
       int64_t age;
       age = ast_tvdiff_ms(*stasis_message_timestamp(message),
          update->new_snapshot->base->creationtime);
       ast_statsd_log("channels.calltime", AST_STATSD_TIMER, age);
       /* And decrement the channel count */
       ast_statsd_log_string("channels.count", AST_STATSD_GAUGE, "-1", 1.0);
    }
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_DEFAULT , .description = "Example of how to use Stasis" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_EXTENDED, .load = load_module, .unload = unload_module, .requires = "res_statsd" } static
Definition at line 177 of file res_chan_stats.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 177 of file res_chan_stats.c.
router
struct stasis_message_router* router static
Stasis message router
Definition at line 46 of file res_chan_stats.c.
sub
struct stasis_subscription* sub static
Statsd channel stats. Exmaple of how to subscribe to Stasis events.
This module subscribes to the channel caching topic and issues statsd stats based on the received messages.
Author
David M. Lee, II dlee@.nosp@m.digi.nosp@m.um.co.nosp@m.m
Since
12
Regular Stasis subscription
Definition at line 44 of file res_chan_stats.c.