Asterisk - The Open Source Telephony Project: astdb2bdb.c File Reference
astdb2bdb.c File Reference
SQLite 3 astdb to Berkeley DB converter.
#include "asterisk.h"
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <unistd.h>
#include <sqlite3.h>
#include <libgen.h>
#include "db1-ast/include/db.h"
Functions
static int add_row_to_bdb (void *arg, int columns, char **values, char **column_names)
static int convert_bdb_to_sqlite3 (void)
static int create_bdb_astdb (void)
static int db_open_sqlite3 (const char *dbname)
int main (int argc, char *argv[])
Variables
static DB * bdb
static sqlite3 * sql3db
Detailed Description
SQLite 3 astdb to Berkeley DB converter.
Author
Terry Wilson twils.nosp@m.on@d.nosp@m.igium.nosp@m..com
Definition in file astdb2bdb.c.
Function Documentation
add_row_to_bdb()
static int add_row_to_bdb (void * arg, int columns, char ** values, char ** column_names) static
Definition at line 44 of file astdb2bdb.c.
References DBT::data, ast_db_entry::key, DBT::size, and value.
Referenced by convert_bdb_to_sqlite3().
 {
    DBT key = { 0, }, value = { 0, };
    if (columns != 2 || strcmp(column_names[0], "key") || strcmp(column_names[1], "value")) {
       fprintf(stderr, "Unknown row type\n");
       return SQLITE_ABORT;
    }
    key.data = values[0];
    key.size = strlen(values[0]) + 1;
    value.data = values[1];
    value.size = strlen(values[1]) + 1;
    if (bdb->put(bdb, &key, &value, 0)) {
       return SQLITE_ABORT;
    }
    bdb->sync(bdb, 0);
    return 0;
 }
convert_bdb_to_sqlite3()
static int convert_bdb_to_sqlite3 (void) static
Definition at line 67 of file astdb2bdb.c.
References add_row_to_bdb(), NULL, and sql3db.
Referenced by main().
 {
    char *errmsg = NULL;
    if (sqlite3_exec(sql3db, "SELECT key,value FROM astdb", add_row_to_bdb, NULL, &errmsg) != SQLITE_OK) {
       fprintf(stderr, "Could not add row to Berkeley DB: %s\n", errmsg);
       return -1;
    }
    return 0;
 }
create_bdb_astdb()
static int create_bdb_astdb (void) static
Definition at line 89 of file astdb2bdb.c.
References AST_FILE_MODE, DB_BTREE, dbopen(), errno, and NULL.
Referenced by main().
 {
    if (!bdb && !(bdb = dbopen("astdb", O_CREAT | O_RDWR | O_TRUNC, AST_FILE_MODE, DB_BTREE, NULL))) {
       fprintf(stderr, "Unable to create astdb: %s\n", strerror(errno));
       return -1;
    }
    return 0;
 }
db_open_sqlite3()
static int db_open_sqlite3 (const char * dbname) static
Definition at line 78 of file astdb2bdb.c.
References sql3db.
Referenced by main().
 {
    if (sqlite3_open(dbname, &sql3db) != SQLITE_OK) {
       fprintf(stderr, "Unable to open Asterisk database '%s': %s\n", dbname, sqlite3_errmsg(sql3db));
       sqlite3_close(sql3db);
       return -1;
    }
    return 0;
 }
main()
int main (int argc, char * argv[])
Definition at line 98 of file astdb2bdb.c.
References convert_bdb_to_sqlite3(), create_bdb_astdb(), db_open_sqlite3(), errno, and sql3db.
 {
    struct stat dont_care;
    if (argc != 2) {
       fprintf(stderr, "%s takes the path of SQLite3 astdb as its only argument\n", basename(argv[0]));
       fprintf(stderr, "and will produce a file 'astdb' in the current directory\n"
             "Make a backup of any existing Berkeley DB astdb you have and copy\n"
             "the new astdb to its location: often /var/lib/asterisk/astdb\n");
       exit(-1);
    }
    if (stat(argv[1], &dont_care)) {
       fprintf(stderr, "Unable to open %s: %s\n", argv[1], strerror(errno));
       exit(-1);
    }
    if (db_open_sqlite3(argv[1])) {
       exit(-1);
    }
    if (create_bdb_astdb()) {
       exit(-1);
    }
    if (convert_bdb_to_sqlite3()) {
       fprintf(stderr, "Database conversion failed!\n");
       exit(-1);
       sqlite3_close(sql3db);
    }
    printf("Created ./astdb. Back up any existing astdb and copy the created\n");
    printf("astdb file to the original's location. Often /var/lib/asterisk/astdb.\n");
    sqlite3_close(sql3db);
    return 0;
 }
Variable Documentation
bdb
DB* bdb static
Definition at line 42 of file astdb2bdb.c.
Referenced by convert_bdb_to_sqlite3().
sql3db
sqlite3* sql3db static
Definition at line 41 of file astdb2bdb.c.
Referenced by convert_bdb_to_sqlite3(), db_open_sqlite3(), and main().