Asterisk - The Open Source Telephony Project: test_data_buffer.c File Reference
test_data_buffer.c File Reference
Data Buffer API Unit Tests.
#include "asterisk.h"
#include "asterisk/module.h"
#include "asterisk/test.h"
#include "asterisk/data_buffer.h"
Data Structures
struct mock_payload
Macros
#define BUFFER_MAX_NOMINAL 10
Functions
static void __reg_module (void)
static void __unreg_module (void)
static void ast_data_buffer_free_wrapper (struct ast_data_buffer *buffer)
struct ast_module * AST_MODULE_SELF_SYM (void)
AST_TEST_DEFINE (buffer_create)
AST_TEST_DEFINE (buffer_put)
AST_TEST_DEFINE (buffer_resize)
AST_TEST_DEFINE (buffer_nominal)
static int load_module (void)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Data buffer API test module" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, }
static const struct ast_module_info * ast_module_info = &__mod_info
Detailed Description
Data Buffer API Unit Tests.
Author
Ben Ford bford.nosp@m.@dig.nosp@m.ium.c.nosp@m.om
Definition in file test_data_buffer.c.
Macro Definition Documentation
BUFFER_MAX_NOMINAL
#define BUFFER_MAX_NOMINAL 10
Definition at line 38 of file test_data_buffer.c.
Referenced by AST_TEST_DEFINE().
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 345 of file test_data_buffer.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 345 of file test_data_buffer.c.
ast_data_buffer_free_wrapper()
static void ast_data_buffer_free_wrapper (struct ast_data_buffer * buffer) static
Definition at line 46 of file test_data_buffer.c.
References ast_data_buffer_free().
Referenced by AST_TEST_DEFINE().
 {
    if (!buffer) {
       return;
    }
    ast_data_buffer_free(buffer);
 }
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 345 of file test_data_buffer.c.
AST_TEST_DEFINE() [1/4]
AST_TEST_DEFINE (buffer_create)
Definition at line 55 of file test_data_buffer.c.
References ast_data_buffer_alloc(), ast_data_buffer_count(), ast_data_buffer_free_wrapper(), ast_data_buffer_max(), ast_free_ptr(), AST_TEST_NOT_RUN, AST_TEST_PASS, BUFFER_MAX_NOMINAL, sip_to_pjsip::info(), NULL, RAII_VAR, TEST_EXECUTE, and TEST_INIT.
 {
    RAII_VAR(struct ast_data_buffer *, buffer, NULL, ast_data_buffer_free_wrapper);
    switch (cmd) {
    case TEST_INIT:
       info->name = "buffer_create";
       info->category = "/main/data_buffer/";
       info->summary = "buffer create unit test";
       info->description =
          "Test that creating a data buffer results in a buffer with the expected values";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    buffer = ast_data_buffer_alloc(ast_free_ptr, BUFFER_MAX_NOMINAL);
    ast_test_validate(test, buffer != NULL,
          "Failed to create buffer with valid arguments");
    ast_test_validate(test, ast_data_buffer_count(buffer) == 0,
          "Newly created buffer does not have the expected payload count");
    ast_test_validate(test, ast_data_buffer_max(buffer) == BUFFER_MAX_NOMINAL,
          "Newly created buffer does not have the expected max size");
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [2/4]
AST_TEST_DEFINE (buffer_put)
Definition at line 83 of file test_data_buffer.c.
References ast_calloc, ast_data_buffer_alloc(), ast_data_buffer_count(), ast_data_buffer_free_wrapper(), ast_data_buffer_get(), ast_data_buffer_put(), ast_free_ptr(), AST_TEST_NOT_RUN, AST_TEST_PASS, mock_payload::id, sip_to_pjsip::info(), NULL, RAII_VAR, TEST_EXECUTE, and TEST_INIT.
 {
    RAII_VAR(struct ast_data_buffer *, buffer, NULL, ast_data_buffer_free_wrapper);
    struct mock_payload *payload;
    struct mock_payload *fetched_payload;
    int ret;
    switch (cmd) {
    case TEST_INIT:
       info->name = "buffer_put";
       info->category = "/main/data_buffer/";
       info->summary = "buffer put unit test";
       info->description =
          "Test that putting payloads in the buffer yields the expected results";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    buffer = ast_data_buffer_alloc(ast_free_ptr, 2);
    ast_test_validate(test, buffer != NULL,
          "Failed to create buffer with valid arguments");
    ast_test_validate(test, ast_data_buffer_count(buffer) == 0,
          "Newly created buffer is not empty");
    payload = ast_calloc(1, sizeof(*payload));
    ast_test_validate(test, payload != NULL,
          "Failed to allocate memory for first payload");
    payload->id = 2;
    ret = ast_data_buffer_put(buffer, 2, payload);
    ast_test_validate(test, ret == 0,
          "Adding a payload to an empty buffer did not return the expected value");
    ast_test_validate(test, ast_data_buffer_count(buffer) == 1,
          "Adding a payload to an empty buffer did not update count to the expected value");
    fetched_payload = (struct mock_payload *)ast_data_buffer_get(buffer, 2);
    ast_test_validate(test, fetched_payload != NULL,
          "Failed to get only payload from buffer given valid arguments");
    ast_data_buffer_put(buffer, 2, payload);
    ast_test_validate(test, ast_data_buffer_count(buffer) == 1,
          "Adding a payload that is already in the buffer should not do anything");
    payload = ast_calloc(1, sizeof(*payload));
    ast_test_validate(test, payload != NULL,
          "Failed to allocate memory for second payload");
    payload->id = 1;
    ast_data_buffer_put(buffer, 1, payload);
    fetched_payload = ast_data_buffer_get(buffer, 1);
    ast_test_validate(test, fetched_payload != NULL,
          "Failed to get a payload from buffer given valid arguments");
    ast_test_validate(test, ast_data_buffer_count(buffer) == 2,
          "Buffer does not have the expected count after removing a payload");
    ast_test_validate(test, fetched_payload->id == 1,
          "Did not get the expected payload from the buffer");
    payload = ast_calloc(1, sizeof(*payload));
    ast_test_validate(test, payload != NULL,
          "Failed to allocate memory for third payload");
    payload->id = 3;
    ret = ast_data_buffer_put(buffer, 3, payload);
    ast_test_validate(test, ret == 0,
          "Failed to replace a payload in the buffer");
    ast_test_validate(test, ast_data_buffer_count(buffer) <= 2,
          "Buffer count exceeded the max");
    fetched_payload = (struct mock_payload *)ast_data_buffer_get(buffer, 3);
    ast_test_validate(test, fetched_payload != NULL,
          "Failed to get a payload from buffer at position 3 given valid arguments");
    ast_test_validate(test, fetched_payload->id == 3,
          "Did not get the expected payload at position 3 from the buffer");
    fetched_payload = (struct mock_payload *)ast_data_buffer_get(buffer, 2);
    ast_test_validate(test, fetched_payload != NULL,
          "Failed to get a payload from buffer at position 2 given valid arguments");
    ast_test_validate(test, fetched_payload->id == 2,
          "Did not get the expected payload at position 2 from the buffer");
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [3/4]
AST_TEST_DEFINE (buffer_resize)
Definition at line 178 of file test_data_buffer.c.
References ast_data_buffer_alloc(), ast_data_buffer_free_wrapper(), ast_data_buffer_max(), ast_data_buffer_resize(), ast_free_ptr(), AST_TEST_NOT_RUN, AST_TEST_PASS, BUFFER_MAX_NOMINAL, sip_to_pjsip::info(), NULL, RAII_VAR, TEST_EXECUTE, and TEST_INIT.
 {
    RAII_VAR(struct ast_data_buffer *, buffer, NULL, ast_data_buffer_free_wrapper);
    switch (cmd) {
    case TEST_INIT:
       info->name = "buffer_resize";
       info->category = "/main/data_buffer/";
       info->summary = "buffer resize unit test";
       info->description =
          "Tests resizing a data buffer to make sure it has the expected outcome";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    buffer = ast_data_buffer_alloc(ast_free_ptr, BUFFER_MAX_NOMINAL);
    ast_test_validate(test, buffer != NULL,
          "Failed to create buffer with valid arguments");
    ast_data_buffer_resize(buffer, BUFFER_MAX_NOMINAL);
    ast_test_validate(test, ast_data_buffer_max(buffer) == BUFFER_MAX_NOMINAL,
          "Trying to resize buffer to same size should not change its max size");
    ast_data_buffer_resize(buffer, BUFFER_MAX_NOMINAL + 2);
    ast_test_validate(test, ast_data_buffer_max(buffer) == BUFFER_MAX_NOMINAL + 2,
          "Increasing buffer size did not return the expected max");
    ast_data_buffer_resize(buffer, 1);
    ast_test_validate(test, ast_data_buffer_max(buffer) == 1,
          "Decreasing buffer size did not return the expected max");
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [4/4]
AST_TEST_DEFINE (buffer_nominal)
Definition at line 217 of file test_data_buffer.c.
References ast_calloc, ast_data_buffer_alloc(), ast_data_buffer_count(), ast_data_buffer_free_wrapper(), ast_data_buffer_get(), ast_data_buffer_put(), ast_data_buffer_remove(), ast_data_buffer_remove_head(), ast_free, ast_free_ptr(), AST_TEST_NOT_RUN, AST_TEST_PASS, BUFFER_MAX_NOMINAL, mock_payload::id, sip_to_pjsip::info(), NULL, RAII_VAR, TEST_EXECUTE, and TEST_INIT.
 {
    RAII_VAR(struct ast_data_buffer *, buffer, NULL, ast_data_buffer_free_wrapper);
    RAII_VAR(struct mock_payload *, removed_payload, NULL, ast_free_ptr);
    struct mock_payload *payload;
    struct mock_payload *fetched_payload;
    int ret;
    int i;
    switch (cmd) {
    case TEST_INIT:
       info->name = "buffer_nominal";
       info->category = "/main/data_buffer/";
       info->summary = "buffer nominal unit test";
       info->description =
          "Tests the normal usage of a data buffer to ensure the expected payloads "
          "are present after multiple insertions";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    buffer = ast_data_buffer_alloc(ast_free_ptr, BUFFER_MAX_NOMINAL);
    ast_test_validate(test, buffer != NULL,
          "Failed to create buffer with valid arguments");
    for (i = 1; i <= BUFFER_MAX_NOMINAL; i++) {
       payload = ast_calloc(1, sizeof(*payload));
       ast_test_validate(test, payload != NULL,
             "Failed to allocate memory for payload %d", i);
       ret = ast_data_buffer_put(buffer, i, payload);
       if (ret) {
          ast_free(payload);
       }
       ast_test_validate(test, ret == 0,
             "Failed to add payload %d to buffer", i);
    }
    ast_test_validate(test, ast_data_buffer_count(buffer) == BUFFER_MAX_NOMINAL,
          "Buffer does not have the expected count after adding payloads");
    for (i = 1; i <= BUFFER_MAX_NOMINAL; i++) {
       fetched_payload = (struct mock_payload *)ast_data_buffer_get(buffer, i);
       ast_test_validate(test, fetched_payload != NULL,
             "Failed to get payload at position %d during first loop", i);
    }
    for (i = 1; i <= BUFFER_MAX_NOMINAL; i++) {
       payload = ast_calloc(1, sizeof(*payload));
       ast_test_validate(test, payload != NULL,
             "Failed to allocate memory for payload %d", i + BUFFER_MAX_NOMINAL);
       payload->id = i;
       ret = ast_data_buffer_put(buffer, i + BUFFER_MAX_NOMINAL, payload);
       if (ret) {
          ast_free(payload);
       }
       ast_test_validate(test, ret == 0,
             "Failed to add payload %d to buffer", i + BUFFER_MAX_NOMINAL);
    }
    ast_test_validate(test, ast_data_buffer_count(buffer) == BUFFER_MAX_NOMINAL,
          "Buffer does not have the expected count after replacing payloads");
    for (i = 1; i <= BUFFER_MAX_NOMINAL; i++) {
       fetched_payload = (struct mock_payload *)ast_data_buffer_get(buffer, i);
       ast_test_validate(test, fetched_payload == NULL,
             "Got an unexpected payload at position %d", i);
       fetched_payload = (struct mock_payload *)ast_data_buffer_get(buffer, i + BUFFER_MAX_NOMINAL);
       ast_test_validate(test, fetched_payload != NULL,
             "Failed to get payload at position %d during second loop", i + BUFFER_MAX_NOMINAL);
    }
    removed_payload = (struct mock_payload *)ast_data_buffer_remove_head(buffer);
    ast_test_validate(test, removed_payload != NULL,
          "Failed to get the payload at the HEAD of the buffer");
    ast_test_validate(test, ast_data_buffer_count(buffer) == BUFFER_MAX_NOMINAL - 1,
          "Removing payload from HEAD of buffer did not decrease buffer size");
    ast_test_validate(test, removed_payload->id == 1,
          "Removing payload from HEAD of buffer did not return expected payload");
    ast_free(removed_payload);
    removed_payload = (struct mock_payload *)ast_data_buffer_remove(buffer, BUFFER_MAX_NOMINAL * 2);
    ast_test_validate(test, removed_payload != NULL,
          "Failed to get payload at position %d from buffer", BUFFER_MAX_NOMINAL * 2);
    ast_test_validate(test, ast_data_buffer_count(buffer) == BUFFER_MAX_NOMINAL - 2,
          "Removing payload from buffer did not decrease buffer size");
    ast_test_validate(test, removed_payload->id == BUFFER_MAX_NOMINAL,
          "Removing payload from buffer did not return expected payload");
    return AST_TEST_PASS;
 }
load_module()
static int load_module (void) static
Definition at line 336 of file test_data_buffer.c.
References AST_MODULE_LOAD_SUCCESS, and AST_TEST_REGISTER.
 {
    AST_TEST_REGISTER(buffer_create);
    AST_TEST_REGISTER(buffer_put);
    AST_TEST_REGISTER(buffer_resize);
    AST_TEST_REGISTER(buffer_nominal);
    return AST_MODULE_LOAD_SUCCESS;
 }
unload_module()
static int unload_module (void) static
Definition at line 327 of file test_data_buffer.c.
References AST_TEST_UNREGISTER.
 {
    AST_TEST_UNREGISTER(buffer_create);
    AST_TEST_UNREGISTER(buffer_put);
    AST_TEST_UNREGISTER(buffer_resize);
    AST_TEST_UNREGISTER(buffer_nominal);
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Data buffer API test module" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, } static
Definition at line 345 of file test_data_buffer.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 345 of file test_data_buffer.c.