Asterisk - The Open Source Telephony Project: app_statsd.c File Reference
app_statsd.c File Reference
#include "asterisk.h"
#include <math.h>
#include "asterisk/module.h"
#include "asterisk/logger.h"
#include "asterisk/app.h"
#include "asterisk/pbx.h"
#include "asterisk/strings.h"
#include "asterisk/statsd.h"
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int determine_actual_value (const char *raw_value)
Determines the actual value of a number by looking for a leading + or -.
static int load_module (void)
static int non_neg_value_range (const char *value)
Check to ensure the value is within the allowed range.
static int statsd_exec (struct ast_channel *chan, const char *data)
static int unload_module (void)
static int validate_metric (const char *metric)
Check to ensure the metric type is a valid metric type.
static int validate_metric_type_counter (const char *statistic_name, const char *value)
Calls the appropriate functions to validate a counter metric.
static int validate_metric_type_gauge (const char *statistic_name, const char *value)
Calls the appropriate functions to validate a gauge metric.
static int validate_metric_type_set (const char *statistic_name, const char *value)
Calls the appropriate functions to validate a set metric.
static int validate_metric_type_timer (const char *statistic_name, const char *value)
Calls the appropriate functions to validate a timer metric.
static int validate_name (const char *name)
Check to ensure the statistic name is valid.
static int validate_numeric (const char *numeric_value)
Check to ensure that a numeric value is valid.
static int value_in_range (const char *value)
Check to ensure the value is within the allowed range.
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_DEFAULT , .description = "StatsD Dialplan Application" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_EXTENDED, .load = load_module, .unload = unload_module, .requires = "res_statsd", }
static const char app [] = "StatsD"
static const struct ast_module_info * ast_module_info = &__mod_info
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 428 of file app_statsd.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 428 of file app_statsd.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 428 of file app_statsd.c.
determine_actual_value()
static int determine_actual_value (const char * raw_value) static
Determines the actual value of a number by looking for a leading + or -.
Parameters
raw_value The entire numeric string to be sent to StatsD.
This function checks to see if the numeric string contains valid characters and then isolates the actual number to be sent for validation. Returns the result of the numeric validation.
Return values
zero on success.
1 on error.
Definition at line 194 of file app_statsd.c.
References ast_log, AST_LOG_ERROR, ast_strlen_zero, and validate_numeric().
Referenced by validate_metric_type_counter(), and validate_metric_type_gauge().
{
    const char *actual_value;
    if ((raw_value[0] == '+') || (raw_value[0] == '-')) {
       actual_value = &raw_value[1];
       if (ast_strlen_zero(actual_value)) {
          ast_log(AST_LOG_ERROR, "Value argument %s only contains a sign"
             " operator.\n", raw_value);
          return 1;
       }
    } else {
       actual_value = &raw_value[0];
    }
    return validate_numeric(actual_value);
 }
load_module()
static int load_module (void) static
Definition at line 418 of file app_statsd.c.
References app, AST_MODFLAG_DEFAULT, AST_MODULE_INFO(), AST_MODULE_SUPPORT_EXTENDED, ast_register_application_xml, ASTERISK_GPL_KEY, statsd_exec(), and unload_module().
 {
    return ast_register_application_xml(app, statsd_exec);
 }
non_neg_value_range()
static int non_neg_value_range (const char * value) static
Check to ensure the value is within the allowed range.
Parameters
value The value of the statistic to be sent to StatsD.
This function checks to see if the value given to the StatsD daialplan application is within the allowed range of [0, 2^64] as specified by StatsD.
Return values
zero on success.
1 on error.
Definition at line 109 of file app_statsd.c.
References ast_log, AST_LOG_WARNING, and NULL.
Referenced by validate_metric_type_timer().
{
    double numerical_value = strtod(value, NULL);
    if (numerical_value < 0 || numerical_value > pow(2, 64)) {
       ast_log(AST_LOG_WARNING, "Value %lf out of range!\n", numerical_value);
       return 1;
    }
    return 0;
 }
statsd_exec()
static int statsd_exec (struct ast_channel * chan, const char * data) static
Definition at line 347 of file app_statsd.c.
References args, AST_APP_ARG, AST_DECLARE_APP_ARGS, ast_log, AST_LOG_ERROR, AST_STANDARD_APP_ARGS, ast_statsd_log_string(), ast_strdupa, NULL, validate_metric(), validate_metric_type_counter(), validate_metric_type_gauge(), validate_metric_type_set(), validate_metric_type_timer(), validate_numeric(), and value.
Referenced by load_module().
 {
    char *stats;
    double numerical_rate = 1.0;
    AST_DECLARE_APP_ARGS(args,
          AST_APP_ARG(metric_type);
          AST_APP_ARG(statistic_name);
          AST_APP_ARG(value);
          AST_APP_ARG(sample_rate);
    );
    if (!data) {
       ast_log(AST_LOG_ERROR, "No parameters were provided. Correct format is "
          "StatsD(metric_type,statistic_name,value[,sample_rate]). Sample rate is the "
          "only optional parameter.\n");
       return 1;
    }
    stats = ast_strdupa(data);
    AST_STANDARD_APP_ARGS(args, stats);
    if (validate_metric(args.metric_type)) {
       return 1;
    }
    if (!strcmp(args.metric_type, "g")) {
       if (validate_metric_type_gauge(args.statistic_name, args.value)) {
          ast_log(AST_LOG_ERROR, "Invalid input for a gauge metric.\n");
          return 1;
       }
    }
    else if (!strcmp(args.metric_type, "c")) {
       if (validate_metric_type_counter(args.statistic_name, args.value)) {
          ast_log(AST_LOG_ERROR, "Invalid input for a counter metric.\n");
          return 1;
       }
    }
    else if (!strcmp(args.metric_type, "ms")) {
       if (validate_metric_type_timer(args.statistic_name, args.value)) {
          ast_log(AST_LOG_ERROR, "Invalid input for a timer metric.\n");
          return 1;
       }
    }
    else if (!strcmp(args.metric_type, "s")) {
       if (validate_metric_type_set(args.statistic_name, args.value)) {
          ast_log(AST_LOG_ERROR, "Invalid input for a set metric.\n");
          return 1;
       }
    }
    if (args.sample_rate) {
       if (validate_numeric(args.sample_rate)) {
          return 1;
       }
       numerical_rate = strtod(args.sample_rate, NULL);
    }
    ast_statsd_log_string(args.statistic_name, args.metric_type, args.value,
       numerical_rate);
    return 0;
 }
unload_module()
static int unload_module (void) static
Definition at line 413 of file app_statsd.c.
References app, and ast_unregister_application().
Referenced by load_module().
 {
    return ast_unregister_application(app);
 }
validate_metric()
static int validate_metric (const char * metric) static
Check to ensure the metric type is a valid metric type.
Parameters
metric The metric type to be sent to StatsD.
This function checks to see if the metric type given to the StatsD dialplan is a valid metric type. Metric types are determined by StatsD.
Return values
zero on success.
1 on error.
Definition at line 131 of file app_statsd.c.
References ARRAY_LEN, ast_log, AST_LOG_ERROR, and ast_strlen_zero.
Referenced by statsd_exec().
 {
    const char *valid_metrics[] = {"g","s","ms","c"};
    int i;
    if (ast_strlen_zero(metric)) {
       ast_log(AST_LOG_ERROR, "Missing metric type argument.\n");
       return 1;
    }
    for (i = 0; i < ARRAY_LEN(valid_metrics); i++) {
       if (!strcmp(valid_metrics[i], metric)) {
          return 0;
       }
    }
    ast_log(AST_LOG_ERROR, "Invalid metric type %s.\n", metric);
    return 1;
 }
validate_metric_type_counter()
static int validate_metric_type_counter (const char * statistic_name, const char * value) static
Calls the appropriate functions to validate a counter metric.
Parameters
statistic_name The statistic name to be sent to StatsD.
value The value to be sent to StatsD.
This function calls other validating functions to correctly validate each input based on allowable input for a counter metric.
Return values
zero on success.
1 on error.
Definition at line 274 of file app_statsd.c.
References ast_log, AST_LOG_ERROR, ast_strlen_zero, determine_actual_value(), validate_name(), and value_in_range().
Referenced by statsd_exec().
{
    if (ast_strlen_zero(value)) {
       ast_log(AST_LOG_ERROR, "Missing value argument.\n");
       return 1;
    }
    if (validate_name(statistic_name) || determine_actual_value(value)
       || value_in_range(value)) {
       return 1;
    }
    return 0;
 }
validate_metric_type_gauge()
static int validate_metric_type_gauge (const char * statistic_name, const char * value) static
Calls the appropriate functions to validate a gauge metric.
Parameters
statistic_name The statistic name to be sent to StatsD.
value The value to be sent to StatsD.
This function calls other validating functions to correctly validate each input based on allowable input for a gauge metric.
Return values
zero on success.
1 on error.
Definition at line 247 of file app_statsd.c.
References ast_log, AST_LOG_ERROR, ast_strlen_zero, determine_actual_value(), validate_name(), and value_in_range().
Referenced by statsd_exec().
{
    if (ast_strlen_zero(value)) {
       ast_log(AST_LOG_ERROR, "Missing value argument.\n");
       return 1;
    }
    if (validate_name(statistic_name) || determine_actual_value(value)
       || value_in_range(value)) {
       return 1;
    }
    return 0;
 }
validate_metric_type_set()
static int validate_metric_type_set (const char * statistic_name, const char * value) static
Calls the appropriate functions to validate a set metric.
Parameters
statistic_name The statistic name to be sent to StatsD.
value The value to be sent to StatsD.
This function calls other validating functions to correctly validate each input based on allowable input for a set metric.
Return values
zero on success.
1 on error.
Definition at line 328 of file app_statsd.c.
References ast_log, AST_LOG_ERROR, ast_strlen_zero, NULL, and validate_name().
Referenced by statsd_exec().
{
    if (ast_strlen_zero(value)) {
       ast_log(AST_LOG_ERROR, "Missing value argument.\n");
       return 1;
    }
    if (validate_name(statistic_name)) {
       return 1;
    }
    if (strstr(value, "|") != NULL) {
       ast_log(AST_LOG_ERROR, "Pipe (|) character is not allowed for value %s"
          " in a set metric.\n", value);
       return 1;
    }
    return 0;
 }
validate_metric_type_timer()
static int validate_metric_type_timer (const char * statistic_name, const char * value) static
Calls the appropriate functions to validate a timer metric.
Parameters
statistic_name The statistic name to be sent to StatsD.
value The value to be sent to StatsD.
This function calls other validating functions to correctly validate each input based on allowable input for a timer metric.
Return values
zero on success.
1 on error.
Definition at line 301 of file app_statsd.c.
References ast_log, AST_LOG_ERROR, ast_strlen_zero, non_neg_value_range(), validate_name(), and validate_numeric().
Referenced by statsd_exec().
{
    if (ast_strlen_zero(value)) {
       ast_log(AST_LOG_ERROR, "Missing value argument.\n");
       return 1;
    }
    if (validate_name(statistic_name) || validate_numeric(value)
       || non_neg_value_range(value)) {
       return 1;
    }
    return 0;
 }
validate_name()
static int validate_name (const char * name) static
Check to ensure the statistic name is valid.
Parameters
name The variable name to be sent to StatsD.
This function checks to see if the statistic name given to the StatsD dialplan application is valid by ensuring that the name does not have any invalid characters.
Return values
zero on success.
1 on error.
Definition at line 223 of file app_statsd.c.
References ast_log, AST_LOG_ERROR, ast_strlen_zero, and NULL.
Referenced by validate_metric_type_counter(), validate_metric_type_gauge(), validate_metric_type_set(), and validate_metric_type_timer().
 {
    if (ast_strlen_zero(name) || (strstr(name, "|") != NULL)) {
       ast_log(AST_LOG_ERROR, "Statistic name %s is missing or contains a pipe (|)"
          " character.\n", name);
       return 1;
    }
    return 0;
 }
validate_numeric()
static int validate_numeric (const char * numeric_value) static
Check to ensure that a numeric value is valid.
Parameters
numeric_value The numeric value to be sent to StatsD.
This function checks to see if a number to be sent to StatsD is actually a valid number. One decimal is allowed.
Return values
zero on success.
1 on error.
Definition at line 163 of file app_statsd.c.
References ast_log, AST_LOG_ERROR, and NULL.
Referenced by determine_actual_value(), statsd_exec(), and validate_metric_type_timer().
{
    const char *num;
    int decimal_counter = 0;
    num = numeric_value;
    while (*num) {
       if (!isdigit(*num++)) {
          if (strstr(numeric_value, ".") != NULL && decimal_counter == 0) {
             decimal_counter++;
             continue;
          }
          ast_log(AST_LOG_ERROR, "%s is not a number!\n", numeric_value);
          return 1;
       }
    }
    return 0;
 }
value_in_range()
static int value_in_range (const char * value) static
Check to ensure the value is within the allowed range.
Parameters
value The value of the statistic to be sent to StatsD.
This function checks to see if the value given to the StatsD daialplan application is within the allowed range of [-2^63, 2^63] as specified by StatsD.
Return values
zero on success.
1 on error.
Definition at line 87 of file app_statsd.c.
References ast_log, AST_LOG_WARNING, and NULL.
Referenced by validate_metric_type_counter(), and validate_metric_type_gauge().
{
    double numerical_value = strtod(value, NULL);
    if (numerical_value < pow(-2, 63) || numerical_value > pow(2, 63)) {
       ast_log(AST_LOG_WARNING, "Value %lf out of range!\n", numerical_value);
       return 1;
    }
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_DEFAULT , .description = "StatsD Dialplan Application" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_EXTENDED, .load = load_module, .unload = unload_module, .requires = "res_statsd", } static
Definition at line 428 of file app_statsd.c.
app
const char app[] = "StatsD" static
Definition at line 74 of file app_statsd.c.
Referenced by load_module(), and unload_module().
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 428 of file app_statsd.c.