Asterisk - The Open Source Telephony Project: rec_delete.c File Reference
rec_delete.c File Reference
#include <sys/types.h>
#include <errno.h>
#include <stdio.h>
#include <string.h>
#include "../include/db.h"
#include "recno.h"
Functions
static int rec_rdelete __P ((BTREE *, recno_t))
int __rec_delete (DB *dbp, const DBT *key, u_int flags) const
int __rec_dleaf (BTREE *t, PAGE *h, u_int32_t idx)
static int rec_rdelete (BTREE *t, recno_t nrec)
Function Documentation
__P()
static int rec_rdelete __P ((BTREE *, recno_t)) static
__rec_delete()
int __rec_delete (DB * dbp, const DBT * key, u_int flags) const
Definition at line 64 of file rec_delete.c.
References B_MODIFIED, _btree::bt_cursor, _btree::bt_mp, _btree::bt_nrecs, _btree::bt_pinned, CURS_INIT, DBT::data, errno, F_ISSET, F_SET, __db::internal, mpool_put(), NULL, R_CURSOR, R_MODIFIED, _cursor::rcursor, rec_rdelete(), RET_ERROR, RET_SPECIAL, RET_SUCCESS, and status.
Referenced by __rec_open().
 {
    BTREE *t;
    recno_t nrec;
    int status;
    t = dbp->internal;
    /* Toss any page pinned across calls. */
    if (t->bt_pinned != NULL) {
       mpool_put(t->bt_mp, t->bt_pinned, 0);
       t->bt_pinned = NULL;
    }
    switch(flags) {
    case 0:
       if ((nrec = *(recno_t *)key->data) == 0)
          goto einval;
       if (nrec > t->bt_nrecs)
          return (RET_SPECIAL);
       --nrec;
       status = rec_rdelete(t, nrec);
       break;
    case R_CURSOR:
       if (!F_ISSET(&t->bt_cursor, CURS_INIT))
          goto einval;
       if (t->bt_nrecs == 0)
          return (RET_SPECIAL);
       status = rec_rdelete(t, t->bt_cursor.rcursor - 1);
       if (status == RET_SUCCESS)
          --t->bt_cursor.rcursor;
       break;
    default:
 einval:     errno = EINVAL;
       return (RET_ERROR);
    }
    if (status == RET_SUCCESS)
       F_SET(t, B_MODIFIED | R_MODIFIED);
    return (status);
 }
__rec_dleaf()
int __rec_dleaf (BTREE * t, PAGE * h, u_int32_t idx)
Definition at line 154 of file rec_delete.c.
References __ovfl_delete(), _btree::bt_nrecs, _rleaf::bytes, _rleaf::flags, GETRLEAF, _page::linp, _page::lower, NEXTINDEX, NRLEAF, P_BIGDATA, RET_ERROR, RET_SUCCESS, and _page::upper.
Referenced by __rec_iput(), and rec_rdelete().
 {
    RLEAF *rl;
    indx_t *ip, cnt, offset;
    u_int32_t nbytes;
    char *from;
    void *to;
    /*
     * Delete a record from a recno leaf page.  Internal records are never
     * deleted from internal pages, regardless of the records that caused
     * them to be added being deleted.  Pages made empty by deletion are
     * not reclaimed.  They are, however, made available for reuse.
     *
     * Pack the remaining entries at the end of the page, shift the indices
     * down, overwriting the deleted record and its index.  If the record
     * uses overflow pages, make them available for reuse.
     */
    to = rl = GETRLEAF(h, idx);
    if (rl->flags & P_BIGDATA && __ovfl_delete(t, rl->bytes) == RET_ERROR)
       return (RET_ERROR);
    nbytes = NRLEAF(rl);
    /*
     * Compress the key/data pairs.  Compress and adjust the [BR]LEAF
     * offsets.  Reset the headers.
     */
    from = (char *)h + h->upper;
    memmove(from + nbytes, from, (char *)to - from);
    h->upper += nbytes;
    offset = h->linp[idx];
    for (cnt = &h->linp[idx] - (ip = &h->linp[0]); cnt--; ++ip)
       if (ip[0] < offset)
          ip[0] += nbytes;
    for (cnt = &h->linp[NEXTINDEX(h)] - ip; --cnt; ++ip)
       ip[0] = ip[1] < offset ? ip[1] + nbytes : ip[1];
    h->lower -= sizeof(indx_t);
    --t->bt_nrecs;
    return (RET_SUCCESS);
 }
rec_rdelete()
static int rec_rdelete (BTREE * t, recno_t nrec) static
Definition at line 120 of file rec_delete.c.
References __rec_dleaf(), __rec_search(), _btree::bt_mp, _epg::index, MPOOL_DIRTY, mpool_put(), NULL, _epg::page, RET_ERROR, RET_SUCCESS, SDELETE, and status.
Referenced by __rec_delete().
 {
    EPG *e;
    PAGE *h;
    int status;
    /* Find the record; __rec_search pins the page. */
    if ((e = __rec_search(t, nrec, SDELETE)) == NULL)
       return (RET_ERROR);
    /* Delete the record. */
    h = e->page;
    status = __rec_dleaf(t, h, e->index);
    if (status != RET_SUCCESS) {
       mpool_put(t->bt_mp, h, 0);
       return (status);
    }
    mpool_put(t->bt_mp, h, MPOOL_DIRTY);
    return (RET_SUCCESS);
 }