Asterisk - The Open Source Telephony Project: iCBConstruct.c File Reference
iCBConstruct.c File Reference
#include <math.h>
#include "iLBC_define.h"
#include "gainquant.h"
#include "getCBvec.h"
Functions
void iCBConstruct (float *decvector, int *index, int *gain_index, float *mem, int lMem, int veclen, int nStages)
void index_conv_dec (int *index)
void index_conv_enc (int *index)
Function Documentation
iCBConstruct()
void iCBConstruct (float * decvector, int * index, int * gain_index, float * mem, int lMem, int veclen, int nStages)
Definition at line 66 of file iCBConstruct.c.
References CB_NSTAGES, gaindequant(), getCBvec(), and SUBL.
Referenced by Decode(), and iLBC_encode().
     {
        int j,k;
        float gain[CB_NSTAGES];
        float cbvec[SUBL];
        /* gain de-quantization */
        gain[0] = gaindequant(gain_index[0], 1.0, 32);
        if (nStages > 1) {
            gain[1] = gaindequant(gain_index[1],
                (float)fabs(gain[0]), 16);
        }
        if (nStages > 2) {
            gain[2] = gaindequant(gain_index[2],
                (float)fabs(gain[1]), 8);
        }
        /* codebook vector construction and construction of
        total vector */
        getCBvec(cbvec, mem, index[0], lMem, veclen);
        for (j=0;j<veclen;j++){
            decvector[j] = gain[0]*cbvec[j];
        }
        if (nStages > 1) {
            for (k=1; k<nStages; k++) {
                getCBvec(cbvec, mem, index[k], lMem, veclen);
                for (j=0;j<veclen;j++) {
                    decvector[j] += gain[k]*cbvec[j];
                }
            }
        }
    }
index_conv_dec()
void index_conv_dec (int * index)
Definition at line 45 of file iCBConstruct.c.
References CB_NSTAGES.
Referenced by iLBC_decode().
     {
        int k;
        for (k=1; k<CB_NSTAGES; k++) {
            if ((index[k]>=44)&&(index[k]<108)) {
                index[k]+=64;
            } else if ((index[k]>=108)&&(index[k]<128)) {
                index[k]+=128;
            } else {
                /* ERROR */
            }
        }
    }
index_conv_enc()
void index_conv_enc (int * index)
Definition at line 28 of file iCBConstruct.c.
References CB_NSTAGES.
Referenced by iLBC_encode().
     {
        int k;
        for (k=1; k<CB_NSTAGES; k++) {
            if ((index[k]>=108)&&(index[k]<172)) {
                index[k]-=64;
            } else if (index[k]>=236) {
                index[k]-=128;
            } else {
                /* ERROR */
            }
        }
    }