Asterisk - The Open Source Telephony Project: cli.c File Reference
res/prometheus/cli.c File Reference
Prometheus CLI Commands.
#include "asterisk.h"
#include "asterisk/cli.h"
#include "asterisk/localtime.h"
#include "asterisk/res_prometheus.h"
#include "prometheus_internal.h"
Functions
int cli_init (void)
Initialize CLI command.
static void cli_unload_cb (void)
static char * prometheus_show_metrics (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static char * prometheus_show_status (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
Variables
static struct ast_cli_entry cli_prometheus []
static struct prometheus_metrics_provider provider
Detailed Description
Prometheus CLI Commands.
Author
Matt Jordan mjord.nosp@m.an@d.nosp@m.igium.nosp@m..com
Definition in file res/prometheus/cli.c.
Function Documentation
cli_init()
int cli_init (void)
Initialize CLI command.
Return values
0 success
-1 error
Definition at line 137 of file res/prometheus/cli.c.
References ARRAY_LEN, ast_cli_register_multiple, and prometheus_metrics_provider_register().
Referenced by load_module().
 {
    prometheus_metrics_provider_register(&provider);
    ast_cli_register_multiple(cli_prometheus, ARRAY_LEN(cli_prometheus));
    return 0;
 }
cli_unload_cb()
static void cli_unload_cb (void) static
Definition at line 123 of file res/prometheus/cli.c.
References ARRAY_LEN, and ast_cli_unregister_multiple().
 {
    ast_cli_unregister_multiple(cli_prometheus, ARRAY_LEN(cli_prometheus));
 }
prometheus_show_metrics()
static char* prometheus_show_metrics (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) static
Definition at line 33 of file res/prometheus/cli.c.
References ast_cli_args::argc, ast_cli(), ast_free, ast_str_buffer(), CLI_FAILURE, CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::command, ast_cli_args::fd, NULL, prometheus_scrape_to_string(), and ast_cli_entry::usage.
 {
    struct ast_str *response;
    if (cmd == CLI_INIT) {
       e->command = "prometheus show metrics";
       e->usage =
          "Usage: prometheus show metrics\n"
          "       Displays the current metrics and their values,\n"
          "       without counting as an actual scrape.\n";
          return NULL;
    } else if (cmd == CLI_GENERATE) {
       return NULL;
    }
    if (a->argc != 3) {
       return CLI_SHOWUSAGE;
    }
    response = prometheus_scrape_to_string();
    if (!response) {
       ast_cli(a->fd, "Egads! An unknown error occurred getting the metrics\n");
       return CLI_FAILURE;
    }
    ast_cli(a->fd, "%s\n", ast_str_buffer(response));
    ast_free(response);
    return CLI_SUCCESS;
 }
prometheus_show_status()
static char* prometheus_show_status (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) static
Definition at line 63 of file res/prometheus/cli.c.
References ao2_ref, ast_cli_args::argc, ast_cli(), ast_localtime(), ast_strftime(), ast_strlen_zero, prometheus_general_config::auth_username, CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::command, config, prometheus_general_config::enabled, ast_cli_args::fd, NULL, prometheus_general_config_get(), prometheus_last_scrape_duration_get(), prometheus_last_scrape_time_get(), prometheus_general_config::uri, and ast_cli_entry::usage.
 {
    struct prometheus_general_config *config;
    char time_buffer[64];
    struct ast_tm last_scrape_local;
    struct timeval last_scrape_time;
    int64_t scrape_duration;
    if (cmd == CLI_INIT) {
       e->command = "prometheus show status";
       e->usage =
          "Usage: prometheus show status\n"
          "       Displays the status of metrics collection.\n";
       return NULL;
    } else if (cmd == CLI_GENERATE) {
       return NULL;
    }
    if (a->argc != 3) {
       return CLI_SHOWUSAGE;
    }
    config = prometheus_general_config_get();
    ast_cli(a->fd, "Prometheus Metrics Status:\n");
    ast_cli(a->fd, "\tEnabled: %s\n", config->enabled ? "Yes" : "No");
    ast_cli(a->fd, "\tURI: %s\n", config->uri);
    ast_cli(a->fd, "\tBasic Auth: %s\n", ast_strlen_zero(config->auth_username) ? "No": "Yes");
    ast_cli(a->fd, "\tLast Scrape Time: ");
    last_scrape_time = prometheus_last_scrape_time_get();
    if (last_scrape_time.tv_sec == 0 && last_scrape_time.tv_usec == 0) {
       snprintf(time_buffer, sizeof(time_buffer), "%s", "(N/A)");
    } else {
       ast_localtime(&last_scrape_time, &last_scrape_local, NULL);
       ast_strftime(time_buffer, sizeof(time_buffer), "%Y-%m-%d %H:%M:%S", &last_scrape_local);
    }
    ast_cli(a->fd, "%s\n", time_buffer);
    ast_cli(a->fd, "\tLast Scrape Duration: ");
    scrape_duration = prometheus_last_scrape_duration_get();
    if (scrape_duration < 0) {
       ast_cli(a->fd, "(N/A)\n");
    } else {
       ast_cli(a->fd, "%" PRIu64 " ms\n", scrape_duration);
    }
    ao2_ref(config, -1);
    return CLI_SUCCESS;
 }
Variable Documentation
cli_prometheus
struct ast_cli_entry cli_prometheus[] static
Initial value:
= {
   { .handler =  prometheus_show_metrics , .summary =  "Display the current metrics and their values" ,},
   { .handler =  prometheus_show_status , .summary =  "Display the status of Prometheus metrics collection" ,},
}
Definition at line 114 of file res/prometheus/cli.c.
provider
struct prometheus_metrics_provider provider static
Initial value:
= {
   .name = "cli",
   .unload_cb = cli_unload_cb,
}
Definition at line 132 of file res/prometheus/cli.c.