Asterisk - The Open Source Telephony Project: hash_buf.c File Reference
hash_buf.c File Reference
#include <sys/param.h>
#include <errno.h>
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include "../include/db.h"
#include "hash.h"
#include "page.h"
#include "extern.h"
Macros
#define BUF_INSERT(B, P)
#define BUF_REMOVE(B)
#define LRU hashp->bufhead.prev
#define LRU_INSERT(B) BUF_INSERT((B), LRU)
#define MRU hashp->bufhead.next
#define MRU_INSERT(B) BUF_INSERT((B), &hashp->bufhead)
Functions
int __buf_free (HTAB *hashp, int do_free, int to_disk)
void __buf_init (HTAB *hashp, int nbytes)
BUFHEAD * __get_buf (HTAB *hashp, u_int32_t addr, BUFHEAD *prev_bp, int newpage)
static BUFHEAD *newbuf __P ((HTAB *, u_int32_t, BUFHEAD *))
void __reclaim_buf (HTAB *hashp, BUFHEAD *bp)
static BUFHEAD * newbuf (HTAB *hashp, u_int32_t addr, BUFHEAD *prev_bp)
Macro Definition Documentation
BUF_INSERT
#define BUF_INSERT (B, P)
Definition at line 82 of file hash_buf.c.
BUF_REMOVE
#define BUF_REMOVE (B)
Value:
{ \
   (B)->prev->next = (B)->next; \
   (B)->next->prev = (B)->prev; \
}
Definition at line 76 of file hash_buf.c.
Referenced by __buf_free(), __get_buf(), __reclaim_buf(), and newbuf().
LRU
#define LRU hashp->bufhead.prev
Definition at line 90 of file hash_buf.c.
Referenced by __buf_free(), and newbuf().
LRU_INSERT
#define LRU_INSERT (B) BUF_INSERT((B), LRU)
Definition at line 93 of file hash_buf.c.
Referenced by __reclaim_buf(), and newbuf().
MRU
#define MRU hashp->bufhead.next
Definition at line 89 of file hash_buf.c.
MRU_INSERT
#define MRU_INSERT (B) BUF_INSERT((B), &hashp->bufhead)
Definition at line 92 of file hash_buf.c.
Referenced by __get_buf(), and newbuf().
Function Documentation
__buf_free()
int __buf_free (HTAB * hashp, int do_free, int to_disk)
Definition at line 315 of file hash_buf.c.
References __put_page(), _bufhead::addr, BUF_MOD, BUF_REMOVE, htab::bufhead, _bufhead::flags, free(), IS_BUCKET, LRU, _bufhead::page, and _bufhead::prev.
Referenced by hash_sync(), and hdestroy().
 {
    BUFHEAD *bp;
    /* Need to make sure that buffer manager has been initialized */
    if (!LRU)
       return (0);
    for (bp = LRU; bp != &hashp->bufhead;) {
       /* Check that the buffer is valid */
       if (bp->addr || IS_BUCKET(bp->flags)) {
          if (to_disk && (bp->flags & BUF_MOD) &&
              __put_page(hashp, bp->page,
              bp->addr, IS_BUCKET(bp->flags), 0))
             return (-1);
       }
       /* Check if we are freeing stuff */
       if (do_free) {
          if (bp->page)
             free(bp->page);
          BUF_REMOVE(bp);
          free(bp);
          bp = LRU;
       } else
          bp = bp->prev;
    }
    return (0);
 }
__buf_init()
void __buf_init (HTAB * hashp, int nbytes)
Definition at line 290 of file hash_buf.c.
References htab::bufhead, MAX, MIN_BUFFERS, htab::nbufs, _bufhead::next, and _bufhead::prev.
Referenced by __hash_open().
 {
    BUFHEAD *bfp;
    int npages;
    bfp = &(hashp->bufhead);
    npages = (nbytes + hashp->BSIZE - 1) >> hashp->BSHIFT;
    npages = MAX(npages, MIN_BUFFERS);
    hashp->nbufs = npages;
    bfp->next = bfp;
    bfp->prev = bfp;
    /*
     * This space is calloc'd so these are already null.
     *
     * bfp->ovfl = NULL;
     * bfp->flags = 0;
     * bfp->page = NULL;
     * bfp->addr = 0;
     */
 }
__get_buf()
BUFHEAD* __get_buf (HTAB * hashp, u_int32_t addr, BUFHEAD * prev_bp, int newpage)
Definition at line 105 of file hash_buf.c.
References __get_page(), _bufhead::addr, BUF_DISK, BUF_REMOVE, htab::dir, ISDISK, MRU_INSERT, htab::new_file, newbuf(), NULL, _bufhead::ovfl, _bufhead::page, and PTROF.
Referenced by __add_ovflpage(), __addel(), __big_delete(), __big_return(), __big_split(), __find_bigpair(), __find_last_page(), __split_page(), collect_data(), collect_key(), fetch_bitmap(), hash_access(), hash_seq(), and ugly_split().
 {
    register BUFHEAD *bp;
    register u_int32_t is_disk_mask;
    register int is_disk, segment_ndx = 0;
    SEGMENT segp = 0;
    is_disk = 0;
    is_disk_mask = 0;
    if (prev_bp) {
       bp = prev_bp->ovfl;
       if (!bp || (bp->addr != addr))
          bp = NULL;
       if (!newpage)
          is_disk = BUF_DISK;
    } else {
       /* Grab buffer out of directory */
       segment_ndx = addr & (hashp->SGSIZE - 1);
       /* valid segment ensured by __call_hash() */
       segp = hashp->dir[addr >> hashp->SSHIFT];
 #ifdef DEBUG
       assert(segp != NULL);
 #endif
       bp = PTROF(segp[segment_ndx]);
       is_disk_mask = ISDISK(segp[segment_ndx]);
       is_disk = is_disk_mask || !hashp->new_file;
    }
    if (!bp) {
       bp = newbuf(hashp, addr, prev_bp);
       if (!bp ||
           __get_page(hashp, bp->page, addr, !prev_bp, is_disk, 0))
          return (NULL);
       if (!prev_bp)
          segp[segment_ndx] =
              (BUFHEAD *)((ptrdiff_t)bp | is_disk_mask);
    } else {
       BUF_REMOVE(bp);
       MRU_INSERT(bp);
    }
    return (bp);
 }
__P()
static BUFHEAD* newbuf __P ((HTAB *, u_int32_t, BUFHEAD *)) static
__reclaim_buf()
void __reclaim_buf (HTAB * hashp, BUFHEAD * bp)
Definition at line 346 of file hash_buf.c.
References _bufhead::addr, BUF_REMOVE, _bufhead::flags, LRU_INSERT, and _bufhead::ovfl.
Referenced by __free_ovflpage().
 {
    bp->ovfl = 0;
    bp->addr = 0;
    bp->flags = 0;
    BUF_REMOVE(bp);
    LRU_INSERT(bp);
 }
newbuf()
static BUFHEAD* newbuf (HTAB * hashp, u_int32_t addr, BUFHEAD * prev_bp) static
Definition at line 160 of file hash_buf.c.
References __put_page(), _bufhead::addr, BUF_BUCKET, BUF_DISK, BUF_MOD, BUF_PIN, BUF_REMOVE, htab::dir, _bufhead::flags, free(), if(), IS_BUCKET, ISDISK, LRU, LRU_INSERT, malloc(), MRU_INSERT, htab::nbufs, htab::new_file, NULL, _bufhead::ovfl, and _bufhead::page.
Referenced by __get_buf(), and xmpp_client_receive().
 {
    register BUFHEAD *bp;      /* The buffer we're going to use */
    register BUFHEAD *xbp;     /* Temp pointer */
    register BUFHEAD *next_xbp;
    SEGMENT segp;
    int segment_ndx;
    u_int16_t oaddr, *shortp;
    oaddr = 0;
    bp = LRU;
    /*
     * If LRU buffer is pinned, the buffer pool is too small. We need to
     * allocate more buffers.
     */
    if (hashp->nbufs || (bp->flags & BUF_PIN)) {
       /* Allocate a new one */
       if ((bp = (BUFHEAD *)malloc(sizeof(BUFHEAD))) == NULL)
          return (NULL);
 #ifdef PURIFY
       memset(bp, 0xff, sizeof(BUFHEAD));
 #endif
       if ((bp->page = (char *)malloc(hashp->BSIZE)) == NULL) {
          free(bp);
          return (NULL);
       }
 #ifdef PURIFY
       memset(bp->page, 0xff, hashp->BSIZE);
 #endif
       if (hashp->nbufs)
          hashp->nbufs--;
    } else {
       /* Kick someone out */
       BUF_REMOVE(bp);
       /*
        * If this is an overflow page with addr 0, it's already been
        * flushed back in an overflow chain and initialized.
        */
       if ((bp->addr != 0) || (bp->flags & BUF_BUCKET)) {
          /*
           * Set oaddr before __put_page so that you get it
           * before bytes are swapped.
           */
          shortp = (u_int16_t *)bp->page;
          if (shortp[0])
             oaddr = shortp[shortp[0] - 1];
          if ((bp->flags & BUF_MOD) && __put_page(hashp, bp->page,
              bp->addr, (int)IS_BUCKET(bp->flags), 0))
             return (NULL);
          /*
           * Update the pointer to this page (i.e. invalidate it).
           *
           * If this is a new file (i.e. we created it at open
           * time), make sure that we mark pages which have been
           * written to disk so we retrieve them from disk later,
           * rather than allocating new pages.
           */
          if (IS_BUCKET(bp->flags)) {
             segment_ndx = bp->addr & (hashp->SGSIZE - 1);
             segp = hashp->dir[bp->addr >> hashp->SSHIFT];
 #ifdef DEBUG
             assert(segp != NULL);
 #endif
             if (hashp->new_file &&
                 ((bp->flags & BUF_MOD) ||
                 ISDISK(segp[segment_ndx])))
                segp[segment_ndx] = (BUFHEAD *)BUF_DISK;
             else
                segp[segment_ndx] = NULL;
          }
          /*
           * Since overflow pages can only be access by means of
           * their bucket, free overflow pages associated with
           * this bucket.
           */
          for (xbp = bp; xbp->ovfl;) {
             next_xbp = xbp->ovfl;
             xbp->ovfl = 0;
             xbp = next_xbp;
             /* Check that ovfl pointer is up date. */
             if (IS_BUCKET(xbp->flags) ||
                 (oaddr != xbp->addr))
                break;
             shortp = (u_int16_t *)xbp->page;
             if (shortp[0])
                /* set before __put_page */
                oaddr = shortp[shortp[0] - 1];
             if ((xbp->flags & BUF_MOD) && __put_page(hashp,
                 xbp->page, xbp->addr, 0, 0))
                return (NULL);
             xbp->addr = 0;
             xbp->flags = 0;
             BUF_REMOVE(xbp);
             LRU_INSERT(xbp);
          }
       }
    }
    /* Now assign this buffer */
    bp->addr = addr;
 #ifdef DEBUG1
    (void)fprintf(stderr, "NEWBUF1: %d->ovfl was %d is now %d\n",
        bp->addr, (bp->ovfl ? bp->ovfl->addr : 0), 0);
 #endif
    bp->ovfl = NULL;
    if (prev_bp) {
       /*
        * If prev_bp is set, this is an overflow page, hook it in to
        * the buffer overflow links.
        */
 #ifdef DEBUG1
       (void)fprintf(stderr, "NEWBUF2: %d->ovfl was %d is now %d\n",
           prev_bp->addr, (prev_bp->ovfl ? bp->ovfl->addr : 0),
           (bp ? bp->addr : 0));
 #endif
       prev_bp->ovfl = bp;
       bp->flags = 0;
    } else
       bp->flags = BUF_BUCKET;
    MRU_INSERT(bp);
    return (bp);
 }