Asterisk - The Open Source Telephony Project: message.h File Reference
message.h File Reference
Out-of-call text message support.
Data Structures
struct ast_msg_data_attribute
struct ast_msg_handler
An external processor of received messages.
struct ast_msg_tech
A message technology.
Enumerations
enum ast_msg_data_attribute_type {
AST_MSG_DATA_ATTR_TO = 0, AST_MSG_DATA_ATTR_FROM, AST_MSG_DATA_ATTR_CONTENT_TYPE, AST_MSG_DATA_ATTR_BODY,
__AST_MSG_DATA_ATTR_LAST
}
enum ast_msg_data_source_type {
AST_MSG_DATA_SOURCE_TYPE_UNKNOWN = 0, AST_MSG_DATA_SOURCE_TYPE_T140, AST_MSG_DATA_SOURCE_TYPE_IN_DIALOG, AST_MSG_DATA_SOURCE_TYPE_OUT_OF_DIALOG,
__AST_MSG_DATA_SOURCE_TYPE_LAST
}
Functions
struct ast_msg * ast_msg_alloc (void)
Allocate a message.
struct ast_msg_data * ast_msg_data_alloc (enum ast_msg_data_source_type source, struct ast_msg_data_attribute attributes[], size_t count)
Allocates an ast_msg_data structure.
struct ast_msg_data * ast_msg_data_alloc2 (enum ast_msg_data_source_type source_type, const char *to, const char *from, const char *content_type, const char *body)
Allocates an ast_msg_data structure.
struct ast_msg_data * ast_msg_data_dup (struct ast_msg_data *msg)
Clone an ast_msg_data structure.
const char * ast_msg_data_get_attribute (struct ast_msg_data *msg, enum ast_msg_data_attribute_type attribute_type)
Get attribute from ast_msg_data.
size_t ast_msg_data_get_length (struct ast_msg_data *msg)
Get length of the structure.
enum ast_msg_data_source_type ast_msg_data_get_source_type (struct ast_msg_data *msg)
Get "source type" from ast_msg_data.
int ast_msg_data_queue_frame (struct ast_channel *channel, struct ast_msg_data *msg)
Queue an AST_FRAME_TEXT_DATA frame containing an ast_msg_data structure.
struct ast_msg * ast_msg_destroy (struct ast_msg *msg)
Destroy an ast_msg.
const char * ast_msg_get_body (const struct ast_msg *msg)
Get the body of a message.
const char * ast_msg_get_endpoint (const struct ast_msg *msg)
Retrieve the endpoint associated with this message.
const char * ast_msg_get_from (const struct ast_msg *msg)
Retrieve the source of this message.
const char * ast_msg_get_tech (const struct ast_msg *msg)
Retrieve the technology associated with this message.
const char * ast_msg_get_to (const struct ast_msg *msg)
Retrieve the destination of this message.
const char * ast_msg_get_var (struct ast_msg *msg, const char *name)
Get the specified variable on the message.
int ast_msg_handler_register (const struct ast_msg_handler *handler)
Register a ast_msg_handler.
int ast_msg_handler_unregister (const struct ast_msg_handler *handler)
Unregister a ast_msg_handler.
int ast_msg_has_destination (const struct ast_msg *msg)
Determine if a particular message has a destination via some handler.
int ast_msg_queue (struct ast_msg *msg)
Queue a message for routing through the dialplan.
struct ast_msg * ast_msg_ref (struct ast_msg *msg)
Bump a msg's ref count.
int ast_msg_send (struct ast_msg *msg, const char *to, const char *from)
Send a msg directly to an endpoint.
int ast_msg_set_body (struct ast_msg *msg, const char *fmt,...)
Set the 'body' text of a message (in UTF-8)
int ast_msg_set_context (struct ast_msg *msg, const char *fmt,...)
Set the dialplan context for this message.
int ast_msg_set_endpoint (struct ast_msg *msg, const char *fmt,...)
Set the technology's endpoint associated with this message.
int ast_msg_set_exten (struct ast_msg *msg, const char *fmt,...)
Set the dialplan extension for this message.
int ast_msg_set_from (struct ast_msg *msg, const char *fmt,...)
Set the 'from' URI of a message.
int ast_msg_set_tech (struct ast_msg *msg, const char *fmt,...)
Set the technology associated with this message.
int ast_msg_set_to (struct ast_msg *msg, const char *fmt,...)
Set the 'to' URI of a message.
int ast_msg_set_var (struct ast_msg *msg, const char *name, const char *value)
Set a variable on the message going to the dialplan.
int ast_msg_set_var_outbound (struct ast_msg *msg, const char *name, const char *value)
Set a variable on the message being sent to a message tech directly.
int ast_msg_tech_register (const struct ast_msg_tech *tech)
Register a message technology.
int ast_msg_tech_unregister (const struct ast_msg_tech *tech)
Unregister a message technology.
void ast_msg_var_iterator_destroy (struct ast_msg_var_iterator *iter)
Destroy a message variable iterator.
struct ast_msg_var_iterator * ast_msg_var_iterator_init (const struct ast_msg *msg)
Create a new message variable iterator.
int ast_msg_var_iterator_next (const struct ast_msg *msg, struct ast_msg_var_iterator *iter, const char **name, const char **value)
Get the next variable name and value that is set for sending outbound.
int ast_msg_var_iterator_next_received (const struct ast_msg *msg, struct ast_msg_var_iterator *iter, const char **name, const char **value)
Get the next variable name and value that was set on a received message.
void ast_msg_var_unref_current (struct ast_msg_var_iterator *iter)
Unref a message var from inside an iterator loop.
Detailed Description
Out-of-call text message support.
Author
Russell Bryant russe.nosp@m.ll@d.nosp@m.igium.nosp@m..com
The purpose of this API is to provide support for text messages that are not session based. The messages are passed into the Asterisk core to be routed through the dialplan or another interface and potentially sent back out through a message technology that has been registered through this API.
Definition in file message.h.
Function Documentation
ast_msg_alloc()
struct ast_msg* ast_msg_alloc (void)
Allocate a message.
Allocate a message for the purposes of passing it into the Asterisk core to be routed through the dialplan. If ast_msg_queue() is not called, this message must be destroyed using ast_msg_destroy(). Otherwise, the message core code will take care of it.
Returns
A message object. This function will return NULL if an allocation error occurs.
Definition at line 418 of file message.c.
References ao2_alloc, AO2_ALLOC_OPT_LOCK_MUTEX, ao2_container_alloc_list, ao2_ref, ast_string_field_init, ast_string_field_set, context, msg_data::msg, msg_data_cmp_fn(), msg_destructor(), NULL, and ast_msg::vars.
Referenced by action_messagesend(), AST_TEST_DEFINE(), module_on_rx_request(), msg_datastore_find_or_create(), receive_message(), send_message(), and xmpp_pak_message().
 {
    struct ast_msg *msg;
    if (!(msg = ao2_alloc(sizeof(*msg), msg_destructor))) {
       return NULL;
    }
    if (ast_string_field_init(msg, 128)) {
       ao2_ref(msg, -1);
       return NULL;
    }
    msg->vars = ao2_container_alloc_list(AO2_ALLOC_OPT_LOCK_MUTEX, 0,
       NULL, msg_data_cmp_fn);
    if (!msg->vars) {
       ao2_ref(msg, -1);
       return NULL;
    }
    ast_string_field_set(msg, context, "default");
    return msg;
 }
ast_msg_destroy()
struct ast_msg* ast_msg_destroy (struct ast_msg * msg)
Destroy an ast_msg.
This should only be called on a message if it was not passed on to ast_msg_queue().
Returns
NULL, always.
Definition at line 448 of file message.c.
References ao2_ref, and NULL.
Referenced by ast_msg_safe_destroy(), module_on_rx_request(), msg_data_destroy(), receive_message(), send_message(), and xmpp_pak_message().
 {
    ao2_ref(msg, -1);
    return NULL;
 }
ast_msg_get_body()
const char* ast_msg_get_body (const struct ast_msg * msg)
Get the body of a message.
Note
The return value is valid only as long as the ast_message is valid. Hold a reference to the message if you plan on storing the return value.
Returns
The body of the messsage, encoded in UTF-8.
Definition at line 531 of file message.c.
References ast_msg::body.
Referenced by AST_TEST_DEFINE(), msg_send(), msg_to_json(), sip_msg_send(), and xmpp_send_cb().
 {
    return msg->body;
 }
ast_msg_get_endpoint()
const char* ast_msg_get_endpoint (const struct ast_msg * msg)
Retrieve the endpoint associated with this message.
Since
12.5.0
Parameters
msg The message to get the endpoint from
Return values
The endpoint associated with the message
NULL or empty string if the message has no associated endpoint
Definition at line 551 of file message.c.
References ast_msg::endpoint.
Referenced by AST_TEST_DEFINE(), and msg_to_endpoint().
 {
    return msg->endpoint;
 }
ast_msg_get_from()
const char* ast_msg_get_from (const struct ast_msg * msg)
Retrieve the source of this message.
Since
12.5.0
Parameters
msg The message to get the soure from
Return values
The source of the message
NULL or empty string if the message has no source
Definition at line 536 of file message.c.
References ast_msg::from.
Referenced by AST_TEST_DEFINE(), msg_send(), and msg_to_json().
 {
    return msg->from;
 }
ast_msg_get_tech()
const char* ast_msg_get_tech (const struct ast_msg * msg)
Retrieve the technology associated with this message.
Since
12.5.0
Parameters
msg The message to get the technology from
Return values
The technology of the message
NULL or empty string if the message has no associated technology
Definition at line 546 of file message.c.
References ast_msg::tech.
Referenced by AST_TEST_DEFINE(), and msg_to_endpoint().
 {
    return msg->tech;
 }
ast_msg_get_to()
const char* ast_msg_get_to (const struct ast_msg * msg)
Retrieve the destination of this message.
Since
12.5.0
Parameters
msg The message to get the destination from
Return values
The destination of the message
NULL or empty string if the message has no destination
Definition at line 541 of file message.c.
References ast_msg::to.
Referenced by AST_TEST_DEFINE(), msg_send(), msg_to_json(), and test_msg_has_destination_cb().
 {
    return msg->to;
 }
ast_msg_get_var()
const char* ast_msg_get_var (struct ast_msg * msg, const char * name)
Get the specified variable on the message.
Note
The return value is valid only as long as the ast_message is valid. Hold a reference to the message if you plan on storing the return value. Do re-set the same message var name while holding a pointer to the result of this function.
Returns
The value associated with variable "name". NULL if variable not found.
Definition at line 620 of file message.c.
References ao2_ref, msg_data_find(), NULL, msg_data::value, and ast_msg::vars.
Referenced by AST_TEST_DEFINE(), msg_data_func_read(), and update_content_type().
 {
    struct msg_data *data;
    const char *val = NULL;
    if (!(data = msg_data_find(msg->vars, name))) {
       return NULL;
    }
    /* Yep, this definitely looks like val would be a dangling pointer
     * after the ref count is decremented.  As long as the message structure
     * is used in a thread safe manner, this will not be the case though.
     * The ast_msg holds a reference to this object in the msg->vars container. */
    val = data->value;
    ao2_ref(data, -1);
    return val;
 }
ast_msg_handler_register()
int ast_msg_handler_register (const struct ast_msg_handler * handler)
Register a ast_msg_handler.
Since
12.5.0
Parameters
handler The handler to register
Return values
0 Success
non-zero Error
Definition at line 1629 of file message.c.
References ast_log, ast_rwlock_unlock, ast_rwlock_wrlock, AST_VECTOR_APPEND, ast_verb, LOG_ERROR, match(), msg_handler_find_by_tech_name(), and ast_msg_handler::name.
Referenced by ast_msg_init(), AST_TEST_DEFINE(), and messaging_init().
 {
    const struct ast_msg_handler *match;
    ast_rwlock_wrlock(&msg_handlers_lock);
    match = msg_handler_find_by_tech_name(handler->name);
    if (match) {
       ast_log(LOG_ERROR, "Message handler already registered for '%s'\n",
               handler->name);
       ast_rwlock_unlock(&msg_handlers_lock);
       return -1;
    }
    if (AST_VECTOR_APPEND(&msg_handlers, handler)) {
       ast_log(LOG_ERROR, "Failed to register message handler for '%s'\n",
               handler->name);
       ast_rwlock_unlock(&msg_handlers_lock);
       return -1;
    }
    ast_verb(2, "Message handler '%s' registered.\n", handler->name);
    ast_rwlock_unlock(&msg_handlers_lock);
    return 0;
 }
ast_msg_handler_unregister()
int ast_msg_handler_unregister (const struct ast_msg_handler * handler)
Unregister a ast_msg_handler.
Since
12.5.0
Parameters
handler The handler to unregister
Return values
0 Success
non-zero Error
Definition at line 1671 of file message.c.
References ast_log, ast_rwlock_unlock, ast_rwlock_wrlock, AST_VECTOR_ELEM_CLEANUP_NOOP, AST_VECTOR_REMOVE_CMP_UNORDERED, ast_verb, LOG_ERROR, match(), msg_handler_cmp(), and ast_msg_handler::name.
Referenced by AST_TEST_DEFINE(), message_shutdown(), and messaging_cleanup().
 {
    int match;
    ast_rwlock_wrlock(&msg_handlers_lock);
    match = AST_VECTOR_REMOVE_CMP_UNORDERED(&msg_handlers, handler, msg_handler_cmp,
                                            AST_VECTOR_ELEM_CLEANUP_NOOP);
    ast_rwlock_unlock(&msg_handlers_lock);
    if (match) {
       ast_log(LOG_ERROR, "No '%s' message handler found.\n", handler->name);
       return -1;
    }
    ast_verb(3, "Message handler '%s' unregistered.\n", handler->name);
    return 0;
 }
ast_msg_has_destination()
int ast_msg_has_destination (const struct ast_msg * msg)
Determine if a particular message has a destination via some handler.
Since
12.5.0
Parameters
msg The message to check
Return values
0 if the message has no handler that can find a destination
1 if the message has a handler that can find a destination
Definition at line 937 of file message.c.
References ast_debug, ast_rwlock_rdlock, ast_rwlock_unlock, AST_VECTOR_GET, AST_VECTOR_SIZE, handler(), ast_msg_handler::has_destination, ast_msg_handler::name, and result.
Referenced by AST_TEST_DEFINE(), module_on_rx_request(), and receive_message().
 {
    int i;
    int result = 0;
    ast_rwlock_rdlock(&msg_handlers_lock);
    for (i = 0; i < AST_VECTOR_SIZE(&msg_handlers); i++) {
       const struct ast_msg_handler *handler = AST_VECTOR_GET(&msg_handlers, i);
       ast_debug(5, "Seeing if %s can handle message\n", handler->name);
       if (handler->has_destination(msg)) {
          ast_debug(5, "%s can handle message\n", handler->name);
          result = 1;
          break;
       }
    }
    ast_rwlock_unlock(&msg_handlers_lock);
    return result;
 }
ast_msg_queue()
int ast_msg_queue (struct ast_msg * msg)
Queue a message for routing through the dialplan.
Regardless of the return value of this function, this funciton will take care of ensuring that the message object is properly destroyed when needed.
Return values
0 message successfully queued
non-zero failure, message not sent to dialplan
Definition at line 958 of file message.c.
References ao2_ref, ast_taskprocessor_push(), and msg_q_cb().
Referenced by AST_TEST_DEFINE(), module_on_rx_request(), receive_message(), and xmpp_pak_message().
 {
    int res;
    res = ast_taskprocessor_push(msg_q_tp, msg_q_cb, msg);
    if (res == -1) {
       ao2_ref(msg, -1);
    }
    return res;
 }
ast_msg_ref()
struct ast_msg* ast_msg_ref (struct ast_msg * msg)
Bump a msg's ref count.
Definition at line 442 of file message.c.
References ao2_ref, and msg_data::msg.
Referenced by msg_data_create().
 {
    ao2_ref(msg, 1);
    return msg;
 }
ast_msg_send()
int ast_msg_send (struct ast_msg * msg, const char * to, const char * from)
Send a msg directly to an endpoint.
Regardless of the return value of this function, this funciton will take care of ensuring that the message object is properly destroyed when needed.
Return values
0 message successfully queued to be sent out
non-zero failure, message not get sent out.
Definition at line 1369 of file message.c.
References ao2_ref, ast_log, ast_rwlock_rdlock, ast_rwlock_unlock, ast_strdupa, ast_strlen_zero, LOG_ERROR, msg_find_by_tech_name(), ast_msg_tech::msg_send, msg_tech, NULL, S_OR, and strsep().
Referenced by AST_TEST_DEFINE(), and send_message().
 {
    char *tech_name = NULL;
    const struct ast_msg_tech *msg_tech;
    int res = -1;
    if (ast_strlen_zero(to)) {
       ao2_ref(msg, -1);
       return -1;
    }
    tech_name = ast_strdupa(to);
    tech_name = strsep(&tech_name, ":");
    ast_rwlock_rdlock(&msg_techs_lock);
    msg_tech = msg_find_by_tech_name(tech_name);
    if (!msg_tech) {
       ast_log(LOG_ERROR, "Unknown message tech: %s\n", tech_name);
       ast_rwlock_unlock(&msg_techs_lock);
       return -1;
    }
    res = msg_tech->msg_send(msg, S_OR(to, ""), S_OR(from, ""));
    ast_rwlock_unlock(&msg_techs_lock);
    ao2_ref(msg, -1);
    return res;
 }
ast_msg_set_body()
int ast_msg_set_body (struct ast_msg * msg, const char * fmt, ...)
Set the 'body' text of a message (in UTF-8)
Return values
0 success
-1 failure
Definition at line 476 of file message.c.
References ast_string_field_build_va, and ast_msg::body.
Referenced by action_messagesend(), AST_TEST_DEFINE(), msg_func_write(), receive_message(), rx_data_to_ast_msg(), send_message(), and xmpp_pak_message().
 {
    va_list ap;
    va_start(ap, fmt);
    ast_string_field_build_va(msg, body, fmt, ap);
    va_end(ap);
    return 0;
 }
ast_msg_set_context()
int ast_msg_set_context (struct ast_msg * msg, const char * fmt, ...)
Set the dialplan context for this message.
Return values
0 success
-1 failure
Definition at line 487 of file message.c.
References ast_string_field_build_va, and context.
Referenced by AST_TEST_DEFINE(), receive_message(), rx_data_to_ast_msg(), and xmpp_pak_message().
 {
    va_list ap;
    va_start(ap, fmt);
    ast_string_field_build_va(msg, context, fmt, ap);
    va_end(ap);
    return 0;
 }
ast_msg_set_endpoint()
int ast_msg_set_endpoint (struct ast_msg * msg, const char * fmt, ...)
Set the technology's endpoint associated with this message.
Since
12.5.0
Return values
0 success
-1 failure
Definition at line 520 of file message.c.
References ast_string_field_build_va, and ast_msg::endpoint.
Referenced by AST_TEST_DEFINE(), receive_message(), rx_data_to_ast_msg(), and xmpp_pak_message().
 {
    va_list ap;
    va_start(ap, fmt);
    ast_string_field_build_va(msg, endpoint, fmt, ap);
    va_end(ap);
    return 0;
 }
ast_msg_set_exten()
int ast_msg_set_exten (struct ast_msg * msg, const char * fmt, ...)
Set the dialplan extension for this message.
Return values
0 success
-1 failure
Definition at line 498 of file message.c.
References ast_string_field_build_va, and exten.
Referenced by AST_TEST_DEFINE(), receive_message(), and rx_data_to_ast_msg().
 {
    va_list ap;
    va_start(ap, fmt);
    ast_string_field_build_va(msg, exten, fmt, ap);
    va_end(ap);
    return 0;
 }
ast_msg_set_from()
int ast_msg_set_from (struct ast_msg * msg, const char * fmt, ...)
Set the 'from' URI of a message.
Return values
0 success
-1 failure
Definition at line 465 of file message.c.
References ast_string_field_build_va, and msg_data::from.
Referenced by AST_TEST_DEFINE(), msg_func_write(), receive_message(), rx_data_to_ast_msg(), send_message(), and xmpp_pak_message().
 {
    va_list ap;
    va_start(ap, fmt);
    ast_string_field_build_va(msg, from, fmt, ap);
    va_end(ap);
    return 0;
 }
ast_msg_set_tech()
int ast_msg_set_tech (struct ast_msg * msg, const char * fmt, ...)
Set the technology associated with this message.
Since
12.5.0
Return values
0 success
-1 failure
Definition at line 509 of file message.c.
References ast_string_field_build_va, and ast_msg::tech.
Referenced by AST_TEST_DEFINE(), receive_message(), rx_data_to_ast_msg(), and xmpp_pak_message().
 {
    va_list ap;
    va_start(ap, fmt);
    ast_string_field_build_va(msg, tech, fmt, ap);
    va_end(ap);
    return 0;
 }
ast_msg_set_to()
int ast_msg_set_to (struct ast_msg * msg, const char * fmt, ...)
Set the 'to' URI of a message.
Return values
0 success
-1 failure
Definition at line 454 of file message.c.
References ast_string_field_build_va, and ast_msg::to.
Referenced by AST_TEST_DEFINE(), msg_func_write(), receive_message(), rx_data_to_ast_msg(), send_message(), and xmpp_pak_message().
 {
    va_list ap;
    va_start(ap, fmt);
    ast_string_field_build_va(msg, to, fmt, ap);
    va_end(ap);
    return 0;
 }
ast_msg_set_var()
int ast_msg_set_var (struct ast_msg * msg, const char * name, const char * value)
Set a variable on the message going to the dialplan.
Note
Setting a variable that already exists overwrites the existing variable value
Parameters
msg
name Name of variable to set
value Value of variable to set
Return values
0 success
-1 failure
Definition at line 615 of file message.c.
References msg_set_var_full().
Referenced by AST_TEST_DEFINE(), headers_to_vars(), receive_message(), rx_data_to_ast_msg(), set_message_vars_from_req(), and xmpp_pak_message().
 {
    return msg_set_var_full(msg, name, value, 0);
 }
ast_msg_set_var_outbound()
int ast_msg_set_var_outbound (struct ast_msg * msg, const char * name, const char * value)
Set a variable on the message being sent to a message tech directly.
Note
Setting a variable that already exists overwrites the existing variable value
Parameters
msg
name Name of variable to set
value Value of variable to set
Return values
0 success
-1 failure
Definition at line 610 of file message.c.
References msg_set_var_full().
Referenced by action_messagesend(), AST_TEST_DEFINE(), msg_data_func_write(), and send_message().
 {
    return msg_set_var_full(msg, name, value, 1);
 }
ast_msg_tech_register()
int ast_msg_tech_register (const struct ast_msg_tech * tech)
Register a message technology.
Return values
0 success
non-zero failure
Definition at line 1569 of file message.c.
References ast_log, ast_rwlock_unlock, ast_rwlock_wrlock, AST_VECTOR_APPEND, ast_verb, LOG_ERROR, match(), msg_find_by_tech_name(), and ast_msg_tech::name.
Referenced by AST_TEST_DEFINE(), and load_module().
 {
    const struct ast_msg_tech *match;
    ast_rwlock_wrlock(&msg_techs_lock);
    match = msg_find_by_tech_name(tech->name);
    if (match) {
       ast_log(LOG_ERROR, "Message technology already registered for '%s'\n",
               tech->name);
       ast_rwlock_unlock(&msg_techs_lock);
       return -1;
    }
    if (AST_VECTOR_APPEND(&msg_techs, tech)) {
       ast_log(LOG_ERROR, "Failed to register message technology for '%s'\n",
               tech->name);
       ast_rwlock_unlock(&msg_techs_lock);
       return -1;
    }
    ast_verb(3, "Message technology '%s' registered.\n", tech->name);
    ast_rwlock_unlock(&msg_techs_lock);
    return 0;
 }
ast_msg_tech_unregister()
int ast_msg_tech_unregister (const struct ast_msg_tech * tech)
Unregister a message technology.
Return values
0 success
non-zero failure
Definition at line 1610 of file message.c.
References ast_log, ast_rwlock_unlock, ast_rwlock_wrlock, AST_VECTOR_ELEM_CLEANUP_NOOP, AST_VECTOR_REMOVE_CMP_UNORDERED, ast_verb, LOG_ERROR, match(), msg_tech_cmp(), and ast_msg_tech::name.
Referenced by AST_TEST_DEFINE(), load_module(), and unload_module().
 {
    int match;
    ast_rwlock_wrlock(&msg_techs_lock);
    match = AST_VECTOR_REMOVE_CMP_UNORDERED(&msg_techs, tech, msg_tech_cmp,
                                            AST_VECTOR_ELEM_CLEANUP_NOOP);
    ast_rwlock_unlock(&msg_techs_lock);
    if (match) {
       ast_log(LOG_ERROR, "No '%s' message technology found.\n", tech->name);
       return -1;
    }
    ast_verb(2, "Message technology '%s' unregistered.\n", tech->name);
    return 0;
 }
ast_msg_var_iterator_destroy()
void ast_msg_var_iterator_destroy (struct ast_msg_var_iterator * iter)
Destroy a message variable iterator.
Parameters
iter Iterator to be destroyed
Definition at line 706 of file message.c.
References ao2_iterator_destroy(), ast_free, ast_msg_var_unref_current(), and ast_msg_var_iterator::iter.
Referenced by AST_TEST_DEFINE(), msg_to_json(), sip_msg_send(), and vars_to_headers().
 {
    if (iter) {
       ao2_iterator_destroy(&iter->iter);
       ast_msg_var_unref_current(iter);
       ast_free(iter);
    }
 }
ast_msg_var_iterator_init()
struct ast_msg_var_iterator* ast_msg_var_iterator_init (const struct ast_msg * msg)
Create a new message variable iterator.
Parameters
msg A message whose variables are to be iterated over
Returns
An opaque pointer to the new iterator
Definition at line 644 of file message.c.
References ao2_iterator_init(), ast_calloc, ast_msg_var_iterator::iter, NULL, and ast_msg::vars.
Referenced by AST_TEST_DEFINE(), msg_to_json(), sip_msg_send(), and vars_to_headers().
 {
    struct ast_msg_var_iterator *iter;
    iter = ast_calloc(1, sizeof(*iter));
    if (!iter) {
       return NULL;
    }
    iter->iter = ao2_iterator_init(msg->vars, 0);
    return iter;
 }
ast_msg_var_iterator_next()
int ast_msg_var_iterator_next (const struct ast_msg * msg, struct ast_msg_var_iterator * iter, const char ** name, const char ** value)
Get the next variable name and value that is set for sending outbound.
Parameters
msg The message with the variables
iter An iterator created with ast_msg_var_iterator_init
name A pointer to the name result pointer
value A pointer to the value result pointer
Return values
0 No more entries
1 Valid entry
Definition at line 689 of file message.c.
References ast_msg_var_iterator_get_next().
Referenced by AST_TEST_DEFINE(), sip_msg_send(), and vars_to_headers().
 {
    return ast_msg_var_iterator_get_next(msg, iter, name, value, 1);
 }
ast_msg_var_iterator_next_received()
int ast_msg_var_iterator_next_received (const struct ast_msg * msg, struct ast_msg_var_iterator * iter, const char ** name, const char ** value)
Get the next variable name and value that was set on a received message.
Parameters
msg The message with the variables
iter An iterator created with ast_msg_var_iterator_init
name A pointer to the name result pointer
value A pointer to the value result pointer
Return values
0 No more entries
1 Valid entry
Definition at line 694 of file message.c.
References ast_msg_var_iterator_get_next().
Referenced by msg_to_json().
 {
    return ast_msg_var_iterator_get_next(msg, iter, name, value, 0);
 }
ast_msg_var_unref_current()
void ast_msg_var_unref_current (struct ast_msg_var_iterator * iter)
Unref a message var from inside an iterator loop.
Definition at line 700 of file message.c.
References ao2_cleanup, ast_msg_var_iterator::current_used, and NULL.
Referenced by ast_msg_var_iterator_destroy(), AST_TEST_DEFINE(), msg_to_json(), sip_msg_send(), and vars_to_headers().
 {
    ao2_cleanup(iter->current_used);
    iter->current_used = NULL;
 }