Asterisk - The Open Source Telephony Project: res_pjsip_pidf_digium_body_supplement.c File Reference
res_pjsip_pidf_digium_body_supplement.c File Reference
#include "asterisk.h"
#include <pjsip.h>
#include <pjsip_simple.h>
#include <pjlib.h>
#include "asterisk/module.h"
#include "asterisk/presencestate.h"
#include "asterisk/res_pjsip.h"
#include "asterisk/res_pjsip_pubsub.h"
#include "asterisk/res_pjsip_presence_xml.h"
#include "asterisk/res_pjsip_body_generator_types.h"
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int load_module (void)
static int pidf_supplement_body (void *body, void *data)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "PJSIP PIDF Sangoma presence supplement" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_CHANNEL_DEPEND, .requires = "res_pjsip,res_pjsip_pubsub", }
static const struct ast_module_info * ast_module_info = &__mod_info
static struct ast_sip_pubsub_body_supplement pidf_supplement
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 118 of file res_pjsip_pidf_digium_body_supplement.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 118 of file res_pjsip_pidf_digium_body_supplement.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 118 of file res_pjsip_pidf_digium_body_supplement.c.
load_module()
static int load_module (void) static
Definition at line 98 of file res_pjsip_pidf_digium_body_supplement.c.
References AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, and ast_sip_pubsub_register_body_supplement().
Referenced by unload_module().
 {
    if (ast_sip_pubsub_register_body_supplement(&pidf_supplement)) {
       return AST_MODULE_LOAD_DECLINE;
    }
    return AST_MODULE_LOAD_SUCCESS;
 }
pidf_supplement_body()
static int pidf_supplement_body (void * body, void * data) static
Definition at line 39 of file res_pjsip_pidf_digium_body_supplement.c.
References ast_log, ast_presence_state2str(), ast_sip_presence_xml_create_attr(), ast_sip_presence_xml_create_node(), ast_sip_sanitize_xml(), ast_strlen_zero, LOG_WARNING, ast_sip_exten_state_data::pool, ast_sip_exten_state_data::presence_message, ast_sip_exten_state_data::presence_state, ast_sip_exten_state_data::presence_subtype, and ast_sip_exten_state_data::user_agent.
 {
    struct ast_sip_exten_state_data *state_data = data;
    pj_xml_node *node;
    char sanitized[1024];
    /* The res_pjsip_exten_state module converts the user agent to lower case */
    if (ast_strlen_zero(state_data->user_agent) ||
        (!strstr(state_data->user_agent, "digium") &&
       !strstr(state_data->user_agent, "sangoma"))) {
       /* not a Sangoma phone */
       return 0;
    }
    if (!(node = ast_sip_presence_xml_create_node(
             state_data->pool, body, "tuple"))) {
       ast_log(LOG_WARNING, "Unable to create PIDF tuple\n");
       return -1;
    }
    ast_sip_presence_xml_create_attr(
       state_data->pool, node, "id", "digium-presence");
    if (!(node = ast_sip_presence_xml_create_node(
             state_data->pool, node, "status"))) {
       ast_log(LOG_WARNING, "Unable to create PIDF tuple status\n");
       return -1;
    }
    if (!(node = ast_sip_presence_xml_create_node(
             state_data->pool, node, "digium_presence"))) {
       ast_log(LOG_WARNING, "Unable to create digium presence\n");
       return -1;
    }
    if (!ast_strlen_zero(state_data->presence_message)) {
       ast_sip_sanitize_xml(state_data->presence_message, sanitized, sizeof(sanitized));
       pj_strdup2(state_data->pool, &node->content, sanitized);
    }
    ast_sip_presence_xml_create_attr(
       state_data->pool, node, "type", ast_presence_state2str(
          state_data->presence_state));
    if (!ast_strlen_zero(state_data->presence_subtype)) {
       ast_sip_sanitize_xml(state_data->presence_subtype, sanitized, sizeof(sanitized));
       ast_sip_presence_xml_create_attr(
          state_data->pool, node, "subtype", sanitized);
    }
    return 0;
 }
unload_module()
static int unload_module (void) static
Definition at line 106 of file res_pjsip_pidf_digium_body_supplement.c.
References AST_MODFLAG_LOAD_ORDER, AST_MODPRI_CHANNEL_DEPEND, AST_MODULE_INFO(), AST_MODULE_SUPPORT_CORE, ast_sip_pubsub_unregister_body_supplement(), ASTERISK_GPL_KEY, and load_module().
 {
    ast_sip_pubsub_unregister_body_supplement(&pidf_supplement);
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "PJSIP PIDF Sangoma presence supplement" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_CHANNEL_DEPEND, .requires = "res_pjsip,res_pjsip_pubsub", } static
Definition at line 118 of file res_pjsip_pidf_digium_body_supplement.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 118 of file res_pjsip_pidf_digium_body_supplement.c.
pidf_supplement
struct ast_sip_pubsub_body_supplement pidf_supplement static
Initial value:
= {
   .type = "application",
   .subtype = "pidf+xml",
   .supplement_body = pidf_supplement_body,
}
Definition at line 92 of file res_pjsip_pidf_digium_body_supplement.c.