Asterisk - The Open Source Telephony Project: res_timing_dahdi.c File Reference
res_timing_dahdi.c File Reference
DAHDI timing interface.
#include "asterisk.h"
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <math.h>
#include <dahdi/user.h>
#include "asterisk/module.h"
#include "asterisk/timing.h"
#include "asterisk/utils.h"
Data Structures
struct dahdi_timer
Macros
#define SEE_TIMING "For more information on Asterisk timing modules, including ways to potentially fix this problem, please see https://wiki.asterisk.org/wiki/display/AST/Timing+Interfaces\n"
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int dahdi_test_timer (void)
static int dahdi_timer_ack (void *data, unsigned int quantity)
static void dahdi_timer_close (void *data)
static int dahdi_timer_disable_continuous (void *data)
static int dahdi_timer_enable_continuous (void *data)
static int dahdi_timer_fd (void *data)
static enum ast_timer_event dahdi_timer_get_event (void *data)
static unsigned int dahdi_timer_get_max_rate (void *data)
static void * dahdi_timer_open (void)
static int dahdi_timer_set_rate (void *data, unsigned int rate)
static int load_module (void)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "DAHDI Timing Interface" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_TIMING, }
static const struct ast_module_info * ast_module_info = &__mod_info
static struct ast_timing_interface dahdi_timing
static void * timing_funcs_handle
Detailed Description
DAHDI timing interface.
Author
Russell Bryant russe.nosp@m.ll@d.nosp@m.igium.nosp@m..com
Definition in file res_timing_dahdi.c.
Macro Definition Documentation
SEE_TIMING
#define SEE_TIMING "For more information on Asterisk timing modules, including ways to potentially fix this problem, please see https://wiki.asterisk.org/wiki/display/AST/Timing+Interfaces\n"
Definition at line 173 of file res_timing_dahdi.c.
Referenced by dahdi_test_timer().
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 240 of file res_timing_dahdi.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 240 of file res_timing_dahdi.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 240 of file res_timing_dahdi.c.
dahdi_test_timer()
static int dahdi_test_timer (void) static
Definition at line 175 of file res_timing_dahdi.c.
References ast_log, ast_wait_for_input(), dahdi_timer::fd, LOG_ERROR, and SEE_TIMING.
Referenced by load_module().
 {
    int fd;
    int x = 160;
    fd = open("/dev/dahdi/timer", O_RDWR);
    if (fd < 0) {
       return -1;
    }
    if (ioctl(fd, DAHDI_TIMERCONFIG, &x)) {
       ast_log(LOG_ERROR, "You have DAHDI built and drivers loaded, but the DAHDI timer test failed to set DAHDI_TIMERCONFIG to %d.\n" SEE_TIMING, x);
       close(fd);
       return -1;
    }
    if ((x = ast_wait_for_input(fd, 300)) < 0) {
       ast_log(LOG_ERROR, "You have DAHDI built and drivers loaded, but the DAHDI timer could not be polled during the DAHDI timer test.\n" SEE_TIMING);
       close(fd);
       return -1;
    }
    if (!x) {
       const char dahdi_timer_error[] = {
          "Asterisk has detected a problem with your DAHDI configuration and will shutdown for your protection.  You have options:"
          "\n\t1. You only have to compile DAHDI support into Asterisk if you need it.  One option is to recompile without DAHDI support."
          "\n\t2. You only have to load DAHDI drivers if you want to take advantage of DAHDI services.  One option is to unload DAHDI modules if you don't need them."
          "\n\t3. If you need DAHDI services, you must correctly configure DAHDI."
       };
       ast_log(LOG_ERROR, "%s\n" SEE_TIMING, dahdi_timer_error);
       usleep(100);
       close(fd);
       return -1;
    }
    close(fd);
    return 0;
 }
dahdi_timer_ack()
static int dahdi_timer_ack (void * data, unsigned int quantity) static
Definition at line 117 of file res_timing_dahdi.c.
References dahdi_timer::fd, and timer.
 {
    struct dahdi_timer *timer = data;
    return ioctl(timer->fd, DAHDI_TIMERACK, &quantity) ? -1 : 0;
 }
dahdi_timer_close()
static void dahdi_timer_close (void * data) static
Definition at line 91 of file res_timing_dahdi.c.
References ast_free, dahdi_timer::fd, and timer.
 {
    struct dahdi_timer *timer = data;
    close(timer->fd);
    ast_free(timer);
 }
dahdi_timer_disable_continuous()
static int dahdi_timer_disable_continuous (void * data) static
Definition at line 132 of file res_timing_dahdi.c.
References dahdi_timer::fd, and timer.
 {
    struct dahdi_timer *timer = data;
    int flags = -1;
    return ioctl(timer->fd, DAHDI_TIMERPONG, &flags) ? -1 : 0;
 }
dahdi_timer_enable_continuous()
static int dahdi_timer_enable_continuous (void * data) static
Definition at line 124 of file res_timing_dahdi.c.
References dahdi_timer::fd, and timer.
 {
    struct dahdi_timer *timer = data;
    int flags = 1;
    return ioctl(timer->fd, DAHDI_TIMERPING, &flags) ? -1 : 0;
 }
dahdi_timer_fd()
static int dahdi_timer_fd (void * data) static
Definition at line 166 of file res_timing_dahdi.c.
References dahdi_timer::fd, and timer.
 {
    struct dahdi_timer *timer = data;
    return timer->fd;
 }
dahdi_timer_get_event()
static enum ast_timer_event dahdi_timer_get_event (void * data) static
Definition at line 140 of file res_timing_dahdi.c.
References AST_TIMING_EVENT_CONTINUOUS, AST_TIMING_EVENT_EXPIRED, dahdi_timer::fd, and timer.
 {
    struct dahdi_timer *timer = data;
    int res;
    int event;
    res = ioctl(timer->fd, DAHDI_GETEVENT, &event);
    if (res) {
       event = DAHDI_EVENT_TIMER_EXPIRED;
    }
    switch (event) {
    case DAHDI_EVENT_TIMER_PING:
       return AST_TIMING_EVENT_CONTINUOUS;
    case DAHDI_EVENT_TIMER_EXPIRED:
    default:
       return AST_TIMING_EVENT_EXPIRED;
    }
 }
dahdi_timer_get_max_rate()
static unsigned int dahdi_timer_get_max_rate (void * data) static
Definition at line 161 of file res_timing_dahdi.c.
 {
    return 1000;
 }
dahdi_timer_open()
static void * dahdi_timer_open (void) static
Definition at line 74 of file res_timing_dahdi.c.
References ast_calloc, ast_free, ast_log, errno, dahdi_timer::fd, LOG_ERROR, NULL, and timer.
 {
    struct dahdi_timer *timer;
    if (!(timer = ast_calloc(1, sizeof(*timer)))) {
       return NULL;
    }
    if ((timer->fd = open("/dev/dahdi/timer", O_RDWR)) < 0) {
       ast_log(LOG_ERROR, "Failed to create dahdi timer: %s\n", strerror(errno));
       ast_free(timer);
       return NULL;
    }
    return timer;
 }
dahdi_timer_set_rate()
static int dahdi_timer_set_rate (void * data, unsigned int rate) static
Definition at line 99 of file res_timing_dahdi.c.
References ast_log, dahdi_timer::fd, LOG_ERROR, roundf(), and timer.
 {
    struct dahdi_timer *timer = data;
    int samples;
    /* DAHDI timers are configured using a number of samples,
     * based on an 8 kHz sample rate. */
    samples = (unsigned int) roundf((8000.0 / ((float) rate)));
    if (ioctl(timer->fd, DAHDI_TIMERCONFIG, &samples)) {
       ast_log(LOG_ERROR, "Failed to configure DAHDI timing fd for %d sample timer ticks\n",
          samples);
       return -1;
    }
    return 0;
 }
load_module()
static int load_module (void) static
Definition at line 216 of file res_timing_dahdi.c.
References AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, ast_register_timing_interface, dahdi_test_timer(), and timing_funcs_handle.
Referenced by unload_module().
 {
    if (dahdi_test_timer()) {
       return AST_MODULE_LOAD_DECLINE;
    }
    return (timing_funcs_handle = ast_register_timing_interface(&dahdi_timing)) ?
       AST_MODULE_LOAD_SUCCESS : AST_MODULE_LOAD_DECLINE;
 }
unload_module()
static int unload_module (void) static
Definition at line 226 of file res_timing_dahdi.c.
References AST_MODFLAG_LOAD_ORDER, AST_MODPRI_TIMING, AST_MODULE_INFO(), AST_MODULE_SUPPORT_CORE, ast_unregister_timing_interface(), ASTERISK_GPL_KEY, load_module(), and timing_funcs_handle.
 {
    if (timing_funcs_handle) {
       return ast_unregister_timing_interface(timing_funcs_handle);
    }
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "DAHDI Timing Interface" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_TIMING, } static
Definition at line 240 of file res_timing_dahdi.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 240 of file res_timing_dahdi.c.
dahdi_timing
struct ast_timing_interface dahdi_timing static
Definition at line 56 of file res_timing_dahdi.c.
timing_funcs_handle
void* timing_funcs_handle static
Definition at line 44 of file res_timing_dahdi.c.
Referenced by load_module(), and unload_module().