Asterisk - The Open Source Telephony Project: app_mf.c File Reference
app_mf.c File Reference
Dial plan applications
MF sender and receiver applications.
#include "asterisk.h"
#include "asterisk/file.h"
#include "asterisk/pbx.h"
#include "asterisk/channel.h"
#include "asterisk/dsp.h"
#include "asterisk/app.h"
#include "asterisk/module.h"
#include "asterisk/indications.h"
#include "asterisk/conversions.h"
Macros
#define MF_BETWEEN_MS 50
#define MF_DURATION 55
#define MF_KP_DURATION 120
#define MF_ST_DURATION 65
Enumerations
enum read_option_flags {
OPT_DELAY = (1 << 0), OPT_MUTE = (1 << 1), OPT_QUELCH = (1 << 2), OPT_RELAXED = (1 << 3),
OPT_LAX_KP = (1 << 4), OPT_PROCESS = (1 << 5), OPT_NO_KP = (1 << 6), OPT_NO_ST = (1 << 7),
OPT_KP_OVERRIDE = (1 << 8), OPT_EXTRAPULSES = (1 << 9), OPT_SKIP = (1 << 0), OPT_INDICATION = (1 << 1),
OPT_NOANSWER = (1 << 2)
}
Functions
AST_MODULE_INFO_STANDARD_EXTENDED (ASTERISK_GPL_KEY, "MF Sender and Receiver Applications")
static int load_module (void)
static int manager_play_mf (struct mansession *s, const struct message *m)
static int read_mf_digits (struct ast_channel *chan, char *buf, int timeout, int features, int laxkp, int override, int no_kp, int no_st)
Detects MF digits on channel using DSP, terminated by ST, STP, ST2P, or ST3P.
static int read_mf_exec (struct ast_channel *chan, const char *data)
static int read_sf_digits (struct ast_channel *chan, char *buf, int timeout, int maxdigits, int freq, int features, int extrapulses)
static int read_sf_exec (struct ast_channel *chan, const char *data)
static int sendmf_exec (struct ast_channel *chan, const char *vdata)
static int unload_module (void)
Variables
static const struct ast_app_option read_app_options [128] = { [ 'd' ] = { .flag = OPT_DELAY }, [ 'e' ] = { .flag = OPT_EXTRAPULSES }, [ 'l' ] = { .flag = OPT_LAX_KP }, [ 'k' ] = { .flag = OPT_NO_KP }, [ 'm' ] = { .flag = OPT_MUTE }, [ 'o' ] = { .flag = OPT_KP_OVERRIDE }, [ 'p' ] = { .flag = OPT_PROCESS }, [ 'q' ] = { .flag = OPT_QUELCH }, [ 'r' ] = { .flag = OPT_RELAXED }, [ 's' ] = { .flag = OPT_NO_ST }, }
static char * readmf_name = "ReceiveMF"
static char * readsf_name = "ReceiveSF"
static const char sendmf_name [] = "SendMF"
Detailed Description
MF sender and receiver applications.
Author
Naveen Albert aster.nosp@m.isk@.nosp@m.phrea.nosp@m.knet.nosp@m..org
Definition in file app_mf.c.
Macro Definition Documentation
MF_BETWEEN_MS
#define MF_BETWEEN_MS 50
Definition at line 262 of file app_mf.c.
Referenced by sendmf_exec().
MF_DURATION
#define MF_DURATION 55
Definition at line 263 of file app_mf.c.
Referenced by manager_play_mf(), and sendmf_exec().
MF_KP_DURATION
#define MF_KP_DURATION 120
Definition at line 264 of file app_mf.c.
Referenced by manager_play_mf(), and sendmf_exec().
MF_ST_DURATION
#define MF_ST_DURATION 65
Definition at line 265 of file app_mf.c.
Referenced by manager_play_mf(), and sendmf_exec().
Enumeration Type Documentation
read_option_flags
enum read_option_flags
Enumerator
OPT_DELAY
OPT_MUTE
OPT_QUELCH
OPT_RELAXED
OPT_LAX_KP
OPT_PROCESS
OPT_NO_KP
OPT_NO_ST
OPT_KP_OVERRIDE
OPT_EXTRAPULSES
OPT_SKIP
OPT_INDICATION
OPT_NOANSWER
Definition at line 232 of file app_mf.c.
{
    OPT_DELAY = (1 << 0),
    OPT_MUTE = (1 << 1),
    OPT_QUELCH = (1 << 2),
    OPT_RELAXED = (1 << 3),
    OPT_LAX_KP = (1 << 4),
    OPT_PROCESS = (1 << 5),
    OPT_NO_KP = (1 << 6),
    OPT_NO_ST = (1 << 7),
    OPT_KP_OVERRIDE = (1 << 8),
    OPT_EXTRAPULSES = (1 << 9),
 };
Function Documentation
AST_MODULE_INFO_STANDARD_EXTENDED()
AST_MODULE_INFO_STANDARD_EXTENDED (ASTERISK_GPL_KEY , "MF Sender and Receiver Applications")
Referenced by load_module().
load_module()
static int load_module (void) static
Definition at line 735 of file app_mf.c.
References ast_manager_register_xml, AST_MODULE_INFO_STANDARD_EXTENDED(), ast_register_application_xml, ASTERISK_GPL_KEY, EVENT_FLAG_CALL, manager_play_mf(), read_mf_exec(), read_sf_exec(), and sendmf_exec().
 {
    int res;
    res = ast_register_application_xml(readsf_name, read_sf_exec);
    res |= ast_register_application_xml(readmf_name, read_mf_exec);
    res |= ast_register_application_xml(sendmf_name, sendmf_exec);
    res |= ast_manager_register_xml("PlayMF", EVENT_FLAG_CALL, manager_play_mf);
    return res;
 }
manager_play_mf()
static int manager_play_mf (struct mansession * s, const struct message * m) static
Definition at line 682 of file app_mf.c.
References ast_channel_get_by_name(), ast_channel_unref, ast_mf_stream(), ast_strlen_zero, astman_get_header(), astman_send_ack(), astman_send_error(), digit, MF_DURATION, MF_KP_DURATION, MF_ST_DURATION, and NULL.
Referenced by load_module().
 {
    const char *channel = astman_get_header(m, "Channel");
    const char *digit = astman_get_header(m, "Digit");
    const char *duration = astman_get_header(m, "Duration");
    struct ast_channel *chan;
    unsigned int duration_ms = MF_DURATION;
    if (!(chan = ast_channel_get_by_name(channel))) {
       astman_send_error(s, m, "Channel not found");
       return 0;
    }
    if (ast_strlen_zero(digit)) {
       astman_send_error(s, m, "No digit specified");
       chan = ast_channel_unref(chan);
       return 0;
    }
    /* Override default duration with KP or ST-specific default durations */
    if (!strcmp(digit, "*"))
       duration_ms = MF_KP_DURATION;
    if (!strcmp(digit, "#") || !strcmp(digit, "A") || !strcmp(digit, "B") || !strcmp(digit, "C"))
       duration_ms = MF_ST_DURATION;
    if (!ast_strlen_zero(duration) && (sscanf(duration, "%30u", &duration_ms) != 1)) {
       astman_send_error(s, m, "Could not convert Duration parameter");
       chan = ast_channel_unref(chan);
       return 0;
    }
    ast_mf_stream(chan, NULL, digit, 0, duration_ms, duration_ms, duration_ms, 1);
    chan = ast_channel_unref(chan);
    astman_send_ack(s, m, "MF successfully queued");
    return 0;
 }
read_mf_digits()
static int read_mf_digits (struct ast_channel * chan, char * buf, int timeout, int features, int laxkp, int override, int no_kp, int no_st) static
Detects MF digits on channel using DSP, terminated by ST, STP, ST2P, or ST3P.
Returns
0 if successful, -1 if unsuccessful.
Parameters
chan channel on which to read digits
str buffer in which to store digits
timeout ms to wait for all digits before giving up
Definition at line 274 of file app_mf.c.
References ast_channel_name(), ast_debug, ast_dsp_free(), ast_dsp_new(), ast_dsp_process(), ast_dsp_set_digitmode(), ast_dsp_set_features(), AST_FRAME_DTMF, AST_FRAME_VOICE, ast_log, ast_read(), ast_remaining_ms(), ast_tvnow(), ast_waitfor(), buf, DSP_DIGITMODE_MF, DSP_FEATURE_DIGIT_DETECT, ast_frame::frametype, ast_frame_subclass::integer, LOG_WARNING, NULL, pbx_builtin_setvar_helper(), result, str, ast_frame::subclass, and timeout.
Referenced by read_mf_exec().
{
    struct ast_dsp *dsp;
    struct ast_frame *frame = NULL;
    struct timeval start;
    int remaining_time = timeout;
    int digits_read = 0;
    int is_start_digit = 0;
    char *str = buf;
    if (!(dsp = ast_dsp_new())) {
       ast_log(LOG_WARNING, "Unable to allocate DSP!\n");
       pbx_builtin_setvar_helper(chan, "RECEIVEMFSTATUS", "ERROR");
       return -1;
    }
    ast_dsp_set_features(dsp, DSP_FEATURE_DIGIT_DETECT);
    ast_dsp_set_digitmode(dsp, DSP_DIGITMODE_MF | features);
    start = ast_tvnow();
    *str = 0; /* start with empty output buffer */
    /* based on app_read and generic_fax_exec from res_fax */
    while (timeout == 0 || remaining_time > 0) {
       if (timeout > 0) {
          remaining_time = ast_remaining_ms(start, timeout);
          if (remaining_time <= 0) {
             pbx_builtin_setvar_helper(chan, "RECEIVEMFSTATUS", "TIMEOUT");
             break;
          }
       }
       /* ast_waitfordigit only waits for DTMF frames, we need to do DSP on voice frames */
       if (ast_waitfor(chan, 1000) > 0) {
          frame = ast_read(chan);
          if (!frame) {
             ast_debug(1, "Channel '%s' did not return a frame; probably hung up.\n", ast_channel_name(chan));
             pbx_builtin_setvar_helper(chan, "RECEIVEMFSTATUS", "HANGUP");
             break;
          } else if (frame->frametype == AST_FRAME_VOICE) {
             frame = ast_dsp_process(chan, dsp, frame);
             /* AST_FRAME_DTMF is used all over the DSP code for DTMF, MF, fax, etc.
                It's used because we can use the frame to store the digit detected.
                All this means is that we received something we care about. */
             if (frame->frametype == AST_FRAME_DTMF) {
                char result = frame->subclass.integer;
                if (digits_read == 0 && !laxkp && result != '*') {
                   ast_debug(1, "Received MF digit, but no KP yet, ignoring: %c\n", result);
                   continue;
                }
                ast_debug(1, "Received MF digit: %c\n", result);
                digits_read++;
                if (result == '*') {
                   /* We received an additional KP, start over? */
                   if (override && digits_read > 0) {
                      ast_debug(1, "Received another KP, starting over\n");
                      str = buf;
                      *str = 0;
                      digits_read = 1; /* we just detected a KP */
                   }
                   /* if we were told not to include the ST digit in the output string, then skip it */
                   if (no_kp) {
                      continue;
                   }
                }
                is_start_digit = (strchr("#", result) || strchr("A", result) || strchr("B", result) || strchr("C", result));
                /* if we were told not to include the ST digit in the output string, then skip it */
                if (!no_st || !is_start_digit) {
                   *str++ = result;
                   *str = 0;
                }
                /* we received a ST digit (ST, STP, ST2P, or ST3P), so we're done */
                if (is_start_digit) {
                   pbx_builtin_setvar_helper(chan, "RECEIVEMFSTATUS", "START");
                   break;
                }
             }
          }
       } else {
          pbx_builtin_setvar_helper(chan, "RECEIVEMFSTATUS", "HANGUP");
       }
    }
    ast_dsp_free(dsp);
    ast_debug(3, "channel '%s' - event loop stopped { timeout: %d, remaining_time: %d }\n", ast_channel_name(chan), timeout, remaining_time);
    return 0;
 }
read_mf_exec()
static int read_mf_exec (struct ast_channel * chan, const char * data) static
Definition at line 551 of file app_mf.c.
References AST_APP_ARG, ast_app_parse_options(), AST_DECLARE_APP_ARGS, ast_log, AST_STANDARD_APP_ARGS, ast_strdupa, ast_strlen_zero, ast_test_flag, ast_verb, DSP_DIGITMODE_MUTECONF, DSP_DIGITMODE_MUTEMAX, DSP_DIGITMODE_NOQUELCH, DSP_DIGITMODE_RELAXDTMF, LOG_WARNING, NULL, OPT_DELAY, OPT_KP_OVERRIDE, OPT_LAX_KP, OPT_MUTE, OPT_NO_KP, OPT_NO_ST, OPT_QUELCH, OPT_RELAXED, options, pbx_builtin_setvar_helper(), read_app_options, read_mf_digits(), timeout, and tmp().
Referenced by load_module().
 {
    char tmp[256] = "";
    int to = 0;
    double tosec;
    struct ast_flags flags = {0};
    char *argcopy = NULL;
    int features = 0;
    AST_DECLARE_APP_ARGS(arglist,
       AST_APP_ARG(variable);
       AST_APP_ARG(timeout);
       AST_APP_ARG(options);
    );
    if (ast_strlen_zero(data)) {
       ast_log(LOG_WARNING, "ReceiveMF requires an argument (variable)\n");
       return -1;
    }
    argcopy = ast_strdupa(data);
    AST_STANDARD_APP_ARGS(arglist, argcopy);
    if (!ast_strlen_zero(arglist.options)) {
       ast_app_parse_options(read_app_options, &flags, NULL, arglist.options);
    }
    if (!ast_strlen_zero(arglist.timeout)) {
       tosec = atof(arglist.timeout);
       if (tosec <= 0) {
          to = 0;
       } else {
          to = tosec * 1000.0;
       }
    }
    if (ast_strlen_zero(arglist.variable)) {
       ast_log(LOG_WARNING, "Invalid! Usage: ReceiveMF(variable[,timeout][,option])\n");
       return -1;
    }
    if (ast_test_flag(&flags, OPT_DELAY)) {
       features |= DSP_DIGITMODE_MUTEMAX;
    }
    if (ast_test_flag(&flags, OPT_MUTE)) {
       features |= DSP_DIGITMODE_MUTECONF;
    }
    if (!ast_test_flag(&flags, OPT_QUELCH)) {
       features |= DSP_DIGITMODE_NOQUELCH;
    }
    if (ast_test_flag(&flags, OPT_RELAXED)) {
       features |= DSP_DIGITMODE_RELAXDTMF;
    }
    read_mf_digits(chan, tmp, to, features, (ast_test_flag(&flags, OPT_LAX_KP)),
       (ast_test_flag(&flags, OPT_KP_OVERRIDE)), (ast_test_flag(&flags, OPT_NO_KP)), (ast_test_flag(&flags, OPT_NO_ST)));
    pbx_builtin_setvar_helper(chan, arglist.variable, tmp);
    if (!ast_strlen_zero(tmp)) {
       ast_verb(3, "MF digits received: '%s'\n", tmp);
    } else {
       ast_verb(3, "No MF digits received.\n");
    }
    return 0;
 }
read_sf_digits()
static int read_sf_digits (struct ast_channel * chan, char * buf, int timeout, int maxdigits, int freq, int features, int extrapulses) static
Definition at line 358 of file app_mf.c.
References ast_channel_name(), ast_debug, ast_dsp_free(), ast_dsp_new(), ast_dsp_process(), ast_dsp_set_features(), ast_dsp_set_freqmode(), AST_FRAME_DTMF, AST_FRAME_VOICE, ast_log, ast_read(), ast_remaining_ms(), ast_tvnow(), ast_waitfor(), buf, DSP_FEATURE_FREQ_DETECT, ast_frame::frametype, ast_frame_subclass::integer, LOG_WARNING, NULL, pbx_builtin_setvar_helper(), result, str, ast_frame::subclass, and timeout.
Referenced by read_sf_exec().
{
    struct ast_dsp *dsp;
    struct ast_frame *frame = NULL;
    struct timeval start, pulsetimer, digittimer;
    int remaining_time = timeout;
    char *str = buf;
    int hits = 0, digits_read = 0;
    unsigned short int sf_on = 0;
    if (!(dsp = ast_dsp_new())) {
       ast_log(LOG_WARNING, "Unable to allocate DSP!\n");
       pbx_builtin_setvar_helper(chan, "RECEIVEMFSTATUS", "ERROR");
       return -1;
    }
    ast_dsp_set_features(dsp, DSP_FEATURE_FREQ_DETECT);
    ast_dsp_set_freqmode(dsp, freq, 60, 16, 0);
    start = ast_tvnow();
    *str = 0; /* start with empty output buffer */
    while (timeout == 0 || remaining_time > 0) {
       if (timeout > 0) {
          remaining_time = ast_remaining_ms(start, timeout);
          if (remaining_time <= 0) {
             pbx_builtin_setvar_helper(chan, "RECEIVESFSTATUS", "TIMEOUT");
             break;
          }
       }
       if (ast_waitfor(chan, 1000) > 0) {
          frame = ast_read(chan);
          if (!frame) {
             ast_debug(1, "Channel '%s' did not return a frame; probably hung up.\n", ast_channel_name(chan));
             pbx_builtin_setvar_helper(chan, "RECEIVESFSTATUS", "HANGUP");
             break;
          } else if (frame->frametype == AST_FRAME_VOICE) {
             frame = ast_dsp_process(chan, dsp, frame);
             if (frame->frametype == AST_FRAME_DTMF) {
                char result = frame->subclass.integer;
                if (result == 'q') {
                   sf_on = 1;
                   pulsetimer = ast_tvnow(); /* reset the pulse timer */
                   /* now, we need at least a 40ms pause to register the pulse */
                }
             } else {
                if (sf_on) {
                   int timeleft = ast_remaining_ms(pulsetimer, 40);
                   if (timeleft <= 0) {
                      sf_on = 0;
                      /* The pulse needs to end no more than 75ms after we detected it */
                      if (timeleft > -75) {
                         hits++;
                         digittimer = ast_tvnow(); /* reset the digit timer */
                         ast_debug(5, "Detected SF pulse (pulse #%d)\n", hits);
                      } else {
                         ast_debug(5, "SF noise, ignoring, time elapsed was %d ms\n", timeleft);
                      }
                   }
                } else if (hits > 0 && ast_remaining_ms(digittimer, 100) <= 0) {
                   /* has the digit finished? */
                   ast_debug(2, "Received SF digit: %d\n", hits);
                   digits_read++;
                   if (hits > 10) {
                      if (extrapulses) {
                         /* dahdi-base.c translates 11 to * and 12 to # */
                         if (hits == 11)
                            hits = '*';
                         else if (hits == 12)
                            hits = '#';
                         else if (hits == 13)
                            hits = 'D';
                         else if (hits == 14)
                            hits = 'C';
                         else if (hits == 15)
                            hits = 'B';
                         else if (hits == 16)
                            hits = 'A';
                         else {
                            ast_debug(3, "Got SF pulse digit %d, is someone playing with the phone?\n", hits);
                            hits = 'A';
                         }
                         *str++ = hits;
                      } else {
                         ast_debug(2, "Got more than 10 pulses, truncating to 10\n");
                         hits = 0; /* 10 dial pulses = digit 0 */
                         *str++ = hits + '0';
                      }
                   } else {
                      if (hits == 10) {
                         hits = 0; /* 10 dial pulses = digit 0 */
                      }
                      *str++ = hits + '0';
                   }
                   *str = 0;
                   hits = 0;
                   if (maxdigits > 0 && digits_read >= maxdigits) {
                      pbx_builtin_setvar_helper(chan, "RECEIVESFSTATUS", "START");
                      break;
                   }
                }
             }
          }
       } else {
          pbx_builtin_setvar_helper(chan, "RECEIVESFSTATUS", "HANGUP");
       }
    }
    ast_dsp_free(dsp);
    ast_debug(3, "channel '%s' - event loop stopped { timeout: %d, remaining_time: %d }\n", ast_channel_name(chan), timeout, remaining_time);
    return 0;
 }
read_sf_exec()
static int read_sf_exec (struct ast_channel * chan, const char * data) static
Definition at line 472 of file app_mf.c.
References AST_APP_ARG, ast_app_parse_options(), AST_DECLARE_APP_ARGS, ast_log, AST_STANDARD_APP_ARGS, ast_str_to_int(), ast_strdupa, ast_strlen_zero, ast_test_flag, ast_verb, DSP_DIGITMODE_MUTECONF, DSP_DIGITMODE_MUTEMAX, DSP_DIGITMODE_NOQUELCH, DSP_DIGITMODE_RELAXDTMF, LOG_WARNING, NULL, OPT_DELAY, OPT_EXTRAPULSES, OPT_MUTE, OPT_QUELCH, OPT_RELAXED, options, pbx_builtin_setvar_helper(), read_app_options, read_sf_digits(), timeout, and tmp().
Referenced by load_module().
 {
    char tmp[256] = "";
    double tosec;
    struct ast_flags flags = {0};
    char *argcopy = NULL;
    int features = 0, digits = 0, to = 0, freq = 2600;
    AST_DECLARE_APP_ARGS(arglist,
       AST_APP_ARG(variable);
       AST_APP_ARG(digits);
       AST_APP_ARG(timeout);
       AST_APP_ARG(freq);
       AST_APP_ARG(options);
    );
    if (ast_strlen_zero(data)) {
       ast_log(LOG_WARNING, "ReceiveSF requires an argument (variable)\n");
       return -1;
    }
    argcopy = ast_strdupa(data);
    AST_STANDARD_APP_ARGS(arglist, argcopy);
    if (!ast_strlen_zero(arglist.options)) {
       ast_app_parse_options(read_app_options, &flags, NULL, arglist.options);
    }
    if (!ast_strlen_zero(arglist.timeout)) {
       tosec = atof(arglist.timeout);
       if (tosec <= 0) {
          to = 0;
       } else {
          to = tosec * 1000.0;
       }
    }
    if (!ast_strlen_zero(arglist.digits) && (ast_str_to_int(arglist.digits, &digits) || digits <= 0)) {
       ast_log(LOG_WARNING, "Invalid number of digits: %s\n", arglist.digits);
       return -1;
    }
    if (!ast_strlen_zero(arglist.freq) && (ast_str_to_int(arglist.freq, &freq) || freq <= 0)) {
       ast_log(LOG_WARNING, "Invalid freq: %s\n", arglist.freq);
       return -1;
    }
    if (ast_strlen_zero(arglist.variable)) {
       ast_log(LOG_WARNING, "Invalid! Usage: ReceiveSF(variable[,timeout][,option])\n");
       return -1;
    }
    if (ast_test_flag(&flags, OPT_DELAY)) {
       features |= DSP_DIGITMODE_MUTEMAX;
    }
    if (ast_test_flag(&flags, OPT_MUTE)) {
       features |= DSP_DIGITMODE_MUTECONF;
    }
    if (!ast_test_flag(&flags, OPT_QUELCH)) {
       features |= DSP_DIGITMODE_NOQUELCH;
    }
    if (ast_test_flag(&flags, OPT_RELAXED)) {
       features |= DSP_DIGITMODE_RELAXDTMF;
    }
    read_sf_digits(chan, tmp, to, digits, freq, features, ast_test_flag(&flags, OPT_EXTRAPULSES));
    pbx_builtin_setvar_helper(chan, arglist.variable, tmp);
    if (!ast_strlen_zero(tmp)) {
       ast_verb(3, "MF digits received: '%s'\n", tmp);
    } else {
       ast_verb(3, "No MF digits received.\n");
    }
    return 0;
 }
sendmf_exec()
static int sendmf_exec (struct ast_channel * chan, const char * vdata) static
Definition at line 620 of file app_mf.c.
References args, AST_APP_ARG, ast_app_parse_timelen(), ast_channel_get_by_name(), ast_channel_unref, AST_DECLARE_APP_ARGS, ast_log, ast_mf_stream(), AST_STANDARD_APP_ARGS, ast_strdupa, ast_strlen_zero, LOG_WARNING, MF_BETWEEN_MS, MF_DURATION, MF_KP_DURATION, MF_ST_DURATION, NULL, and TIMELEN_MILLISECONDS.
Referenced by load_module().
 {
    int res;
    char *data;
    int dinterval = 0, duration = 0, durationkp = 0, durationst = 0;
    struct ast_channel *chan_found = NULL;
    struct ast_channel *chan_dest = chan;
    struct ast_channel *chan_autoservice = NULL;
    AST_DECLARE_APP_ARGS(args,
       AST_APP_ARG(digits);
       AST_APP_ARG(dinterval);
       AST_APP_ARG(duration);
       AST_APP_ARG(durationkp);
       AST_APP_ARG(durationst);
       AST_APP_ARG(channel);
    );
    if (ast_strlen_zero(vdata)) {
       ast_log(LOG_WARNING, "SendMF requires an argument\n");
       return 0;
    }
    data = ast_strdupa(vdata);
    AST_STANDARD_APP_ARGS(args, data);
    if (ast_strlen_zero(args.digits)) {
       ast_log(LOG_WARNING, "The digits argument is required (0-9,*#ABC,wf)\n");
       return 0;
    }
    if (!ast_strlen_zero(args.dinterval)) {
       ast_app_parse_timelen(args.dinterval, &dinterval, TIMELEN_MILLISECONDS);
    }
    if (!ast_strlen_zero(args.duration)) {
       ast_app_parse_timelen(args.duration, &duration, TIMELEN_MILLISECONDS);
    }
    if (!ast_strlen_zero(args.durationkp)) {
       ast_app_parse_timelen(args.durationkp, &durationkp, TIMELEN_MILLISECONDS);
    }
    if (!ast_strlen_zero(args.durationst)) {
       ast_app_parse_timelen(args.durationst, &durationst, TIMELEN_MILLISECONDS);
    }
    if (!ast_strlen_zero(args.channel)) {
       chan_found = ast_channel_get_by_name(args.channel);
       if (!chan_found) {
          ast_log(LOG_WARNING, "No such channel: %s\n", args.channel);
          return 0;
       }
       chan_dest = chan_found;
       if (chan_found != chan) {
          chan_autoservice = chan;
       }
    }
    res = ast_mf_stream(chan_dest, chan_autoservice, args.digits, dinterval <= 0 ? MF_BETWEEN_MS : dinterval,
       duration <= 0 ? MF_DURATION : duration, durationkp <= 0 ? MF_KP_DURATION : durationkp,
       durationst <= 0 ? MF_ST_DURATION : durationst, 0);
    if (chan_found) {
       ast_channel_unref(chan_found);
    }
    return chan_autoservice ? 0 : res;
 }
unload_module()
static int unload_module (void) static
Definition at line 723 of file app_mf.c.
References ast_manager_unregister(), and ast_unregister_application().
 {
    int res;
    res = ast_unregister_application(readsf_name);
    res |= ast_unregister_application(readmf_name);
    res |= ast_unregister_application(sendmf_name);
    res |= ast_manager_unregister("PlayMF");
    return res;
 }
Variable Documentation
read_app_options
const struct ast_app_option read_app_options[128] = { [ 'd' ] = { .flag = OPT_DELAY }, [ 'e' ] = { .flag = OPT_EXTRAPULSES }, [ 'l' ] = { .flag = OPT_LAX_KP }, [ 'k' ] = { .flag = OPT_NO_KP }, [ 'm' ] = { .flag = OPT_MUTE }, [ 'o' ] = { .flag = OPT_KP_OVERRIDE }, [ 'p' ] = { .flag = OPT_PROCESS }, [ 'q' ] = { .flag = OPT_QUELCH }, [ 'r' ] = { .flag = OPT_RELAXED }, [ 's' ] = { .flag = OPT_NO_ST }, } static
Definition at line 256 of file app_mf.c.
Referenced by read_mf_exec(), and read_sf_exec().
readmf_name
char* readmf_name = "ReceiveMF" static
Definition at line 258 of file app_mf.c.
readsf_name
char* readsf_name = "ReceiveSF" static
Definition at line 259 of file app_mf.c.
sendmf_name
const char sendmf_name[] = "SendMF" static
Definition at line 260 of file app_mf.c.