Asterisk - The Open Source Telephony Project: func_sayfiles.c File Reference
func_sayfiles.c File Reference
Module: Dial plan functions
Returns files played by Say applications.
#include "asterisk.h"
#include "asterisk/pbx.h"
#include "asterisk/file.h"
#include "asterisk/channel.h"
#include "asterisk/say.h"
#include "asterisk/lock.h"
#include "asterisk/localtime.h"
#include "asterisk/utils.h"
#include "asterisk/app.h"
#include "asterisk/test.h"
#include "asterisk/module.h"
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
AST_TEST_DEFINE (test_SAYFILES_function)
static int load_module (void)
static int sayfile_exec (struct ast_channel *chan, const char *cmd, char *data, char *buf, size_t len)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Say application files" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, }
static const struct ast_module_info * ast_module_info = &__mod_info
static struct ast_custom_function sayfiles
Detailed Description
Returns files played by Say applications.
Author
Naveen Albert aster.nosp@m.isk@.nosp@m.phrea.nosp@m.knet.nosp@m..org
Definition in file func_sayfiles.c.
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 302 of file func_sayfiles.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 302 of file func_sayfiles.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 302 of file func_sayfiles.c.
AST_TEST_DEFINE()
AST_TEST_DEFINE (test_SAYFILES_function)
Definition at line 152 of file func_sayfiles.c.
References ast_free, ast_str_buffer(), ast_str_create, ast_str_set(), ast_str_substitute_variables(), AST_TEST_FAIL, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_test_status_update, sip_to_pjsip::info(), NULL, result, TEST_EXECUTE, and TEST_INIT.
 {
    enum ast_test_result_state res = AST_TEST_PASS;
    struct ast_str *expr, *result;
    switch (cmd) {
    case TEST_INIT:
       info->name = "test_SAYFILES_function";
       info->category = "/funcs/sayfiles/";
       info->summary = "Test SAYFILES function substitution";
       info->description =
          "Executes a series of variable substitutions using the SAYFILES function and ensures that the expected results are received.";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    ast_test_status_update(test, "Testing SAYFILES() substitution ...\n");
    if (!(expr = ast_str_create(16))) {
       return AST_TEST_FAIL;
    }
    if (!(result = ast_str_create(16))) {
       ast_free(expr);
       return AST_TEST_FAIL;
    }
    ast_str_set(&expr, 0, "${SAYFILES(hi Th3re,alpha)}");
    ast_str_substitute_variables(&result, 0, NULL, ast_str_buffer(expr));
    if (strcmp(ast_str_buffer(result), "letters/h&letters/i&letters/space&letters/t&letters/h&digits/3&letters/r&letters/e") != 0) {
       ast_test_status_update(test, "SAYFILES(hi Th3re,alpha) test failed ('%s')\n",
             ast_str_buffer(result));
       res = AST_TEST_FAIL;
    }
    ast_str_set(&expr, 0, "${SAYFILES(phreak,phonetic)}");
    ast_str_substitute_variables(&result, 0, NULL, ast_str_buffer(expr));
    if (strcmp(ast_str_buffer(result), "phonetic/p_p&phonetic/h_p&phonetic/r_p&phonetic/e_p&phonetic/a_p&phonetic/k_p") != 0) {
       ast_test_status_update(test, "SAYFILES(phreak,phonetic) test failed ('%s')\n",
             ast_str_buffer(result));
       res = AST_TEST_FAIL;
    }
    ast_str_set(&expr, 0, "${SAYFILES(35,digits)}");
    ast_str_substitute_variables(&result, 0, NULL, ast_str_buffer(expr));
    if (strcmp(ast_str_buffer(result), "digits/3&digits/5") != 0) {
       ast_test_status_update(test, "SAYFILES(35,digits) test failed ('%s')\n",
             ast_str_buffer(result));
       res = AST_TEST_FAIL;
    }
    ast_str_set(&expr, 0, "${SAYFILES(35,number)}");
    ast_str_substitute_variables(&result, 0, NULL, ast_str_buffer(expr));
    if (strcmp(ast_str_buffer(result), "digits/30&digits/5") != 0) {
       ast_test_status_update(test, "SAYFILES(35,number) test failed ('%s')\n",
             ast_str_buffer(result));
       res = AST_TEST_FAIL;
    }
    ast_str_set(&expr, 0, "${SAYFILES(1042,number)}");
    ast_str_substitute_variables(&result, 0, NULL, ast_str_buffer(expr));
    if (strcmp(ast_str_buffer(result), "digits/1&digits/thousand&digits/40&digits/2") != 0) {
       ast_test_status_update(test, "SAYFILES(1042,number) test failed ('%s')\n",
             ast_str_buffer(result));
       res = AST_TEST_FAIL;
    }
    ast_str_set(&expr, 0, "${SAYFILES(0,number)}");
    ast_str_substitute_variables(&result, 0, NULL, ast_str_buffer(expr));
    if (strcmp(ast_str_buffer(result), "digits/0") != 0) {
       ast_test_status_update(test, "SAYFILES(0,digits) test failed ('%s')\n",
             ast_str_buffer(result));
       res = AST_TEST_FAIL;
    }
    ast_str_set(&expr, 0, "${SAYFILES(0,money)}");
    ast_str_substitute_variables(&result, 0, NULL, ast_str_buffer(expr));
    if (strcmp(ast_str_buffer(result), "digits/0&cents") != 0) {
       ast_test_status_update(test, "SAYFILES(0,money) test failed ('%s')\n",
             ast_str_buffer(result));
       res = AST_TEST_FAIL;
    }
    ast_str_set(&expr, 0, "${SAYFILES(0.01,money)}");
    ast_str_substitute_variables(&result, 0, NULL, ast_str_buffer(expr));
    if (strcmp(ast_str_buffer(result), "digits/1&cent") != 0) {
       ast_test_status_update(test, "SAYFILES(0.01,money) test failed ('%s')\n",
             ast_str_buffer(result));
       res = AST_TEST_FAIL;
    }
    ast_str_set(&expr, 0, "${SAYFILES(0.42,money)}");
    ast_str_substitute_variables(&result, 0, NULL, ast_str_buffer(expr));
    if (strcmp(ast_str_buffer(result), "digits/40&digits/2&cents") != 0) {
       ast_test_status_update(test, "SAYFILES(0.42,money) test failed ('%s')\n",
             ast_str_buffer(result));
       res = AST_TEST_FAIL;
    }
    ast_str_set(&expr, 0, "${SAYFILES(1.00,money)}");
    ast_str_substitute_variables(&result, 0, NULL, ast_str_buffer(expr));
    if (strcmp(ast_str_buffer(result), "digits/1&letters/dollar") != 0) {
       ast_test_status_update(test, "SAYFILES(1.00,money) test failed ('%s')\n",
             ast_str_buffer(result));
       res = AST_TEST_FAIL;
    }
    ast_str_set(&expr, 0, "${SAYFILES(1.42,money)}");
    ast_str_substitute_variables(&result, 0, NULL, ast_str_buffer(expr));
    if (strcmp(ast_str_buffer(result), "digits/1&letters/dollar_&and&digits/40&digits/2&cents") != 0) {
       ast_test_status_update(test, "SAYFILES(1.42,money) test failed ('%s')\n",
             ast_str_buffer(result));
       res = AST_TEST_FAIL;
    }
    ast_str_set(&expr, 0, "${SAYFILES(2.00,money)}");
    ast_str_substitute_variables(&result, 0, NULL, ast_str_buffer(expr));
    if (strcmp(ast_str_buffer(result), "digits/2&dollars") != 0) {
       ast_test_status_update(test, "SAYFILES(2.00,money) test failed ('%s')\n",
             ast_str_buffer(result));
       res = AST_TEST_FAIL;
    }
    ast_str_set(&expr, 0, "${SAYFILES(2.42,money)}");
    ast_str_substitute_variables(&result, 0, NULL, ast_str_buffer(expr));
    if (strcmp(ast_str_buffer(result), "digits/2&dollars&and&digits/40&digits/2&cents") != 0) {
       ast_test_status_update(test, "SAYFILES(2.42,money) test failed ('%s')\n",
             ast_str_buffer(result));
       res = AST_TEST_FAIL;
    }
    ast_free(expr);
    ast_free(result);
    return res;
 }
load_module()
static int load_module (void) static
Definition at line 296 of file func_sayfiles.c.
References ast_custom_function_register, and AST_TEST_REGISTER.
 {
    AST_TEST_REGISTER(test_SAYFILES_function);
    return ast_custom_function_register(&sayfiles);
 }
sayfile_exec()
static int sayfile_exec (struct ast_channel * chan, const char * cmd, char * data, char * buf, size_t len) static
Definition at line 89 of file func_sayfiles.c.
References args, AST_APP_ARG, ast_channel_language(), AST_DECLARE_APP_ARGS, ast_free, ast_get_character_str(), ast_get_digit_str(), ast_get_money_str(), ast_get_number_str(), ast_get_phonetic_str(), ast_log, AST_SAY_CASE_NONE, AST_STANDARD_APP_ARGS, ast_str_buffer(), ast_strlen_zero, LOG_WARNING, NULL, type, and value.
 {
    char *value, *type, *files;
    const char *lang;
    struct ast_str *filenames = NULL;
    AST_DECLARE_APP_ARGS(args,
       AST_APP_ARG(value);
       AST_APP_ARG(type);
    );
    if (ast_strlen_zero(data)) {
       ast_log(LOG_WARNING, "SAYFILES requires an argument\n");
       return 0;
    }
    AST_STANDARD_APP_ARGS(args, data);
    value = args.value;
    if (ast_strlen_zero(args.type))
       type = "alpha";
    else
       type = args.type;
    if (chan)
       lang = ast_channel_language(chan);
    else
       lang = "en"; /* No chan for unit tests */
    if (!strcmp(type, "alpha")) {
       filenames = ast_get_character_str(value, lang, AST_SAY_CASE_NONE);
    } else if (!strcmp(type, "phonetic")) {
       filenames = ast_get_phonetic_str(value, lang);
    } else if (!strcmp(type, "digits")) {
       filenames = ast_get_digit_str(value, lang);
    } else if (!strcmp(type, "number")) {
       int num;
       if (sscanf(value, "%d", &num) == 1)
          filenames = ast_get_number_str(num, lang);
       else
          ast_log(LOG_WARNING, "Invalid numeric argument: %s\n", value);
    } else if (!strcmp(type, "money")) {
       filenames = ast_get_money_str(value, lang);
    } else {
       ast_log(LOG_WARNING, "Invalid say type specified: %s\n", type);
    }
    if (!filenames) {
       return -1;
    }
    files = ast_str_buffer(filenames);
    snprintf(buf, len, "%s", files);
    ast_free(filenames);
    return 0;
 }
unload_module()
static int unload_module (void) static
Definition at line 290 of file func_sayfiles.c.
References ast_custom_function_unregister(), and AST_TEST_UNREGISTER.
 {
    AST_TEST_UNREGISTER(test_SAYFILES_function);
    return ast_custom_function_unregister(&sayfiles);
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Say application files" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, } static
Definition at line 302 of file func_sayfiles.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 302 of file func_sayfiles.c.
sayfiles
struct ast_custom_function sayfiles static
Initial value:
= {
   .name = "SAYFILES",
   .read = sayfile_exec,
}
Definition at line 146 of file func_sayfiles.c.