Asterisk - The Open Source Telephony Project: ast_datastore_info Struct Reference
ast_datastore_info Struct Reference
Structure for a data store type.
#include <datastore.h>
Data Fields
void(* chan_breakdown)(void *data, struct ast_channel *old_chan, struct ast_channel *new_chan)
Fix up channel references on the channel being masqueraded into.
void(* chan_fixup)(void *data, struct ast_channel *old_chan, struct ast_channel *new_chan)
Fix up channel references on the masquerading channel.
void(* destroy)(void *data)
void *(* duplicate)(void *data)
const char * type
Detailed Description
Structure for a data store type.
Definition at line 31 of file datastore.h.
Field Documentation
chan_breakdown
void(* chan_breakdown) (void *data, struct ast_channel *old_chan, struct ast_channel *new_chan)
Fix up channel references on the channel being masqueraded into.
data The datastore data
old_chan The old channel owning the datastore
new_chan The new channel owning the datastore
This is the same as the above callback, except it is called for the channel being masqueraded into instead of the channel that is masquerading.
Returns
nothing.
Definition at line 64 of file datastore.h.
Referenced by channel_do_masquerade().
chan_fixup
void(* chan_fixup) (void *data, struct ast_channel *old_chan, struct ast_channel *new_chan)
Fix up channel references on the masquerading channel.
data The datastore data
old_chan The old channel owning the datastore
new_chan The new channel owning the datastore
This is exactly like the fixup callback of the channel technology interface. It allows a datastore to fix any pointers it saved to the owning channel in case that the owning channel has changed. Generally, this would happen when the datastore is set to be inherited, and a masquerade occurs.
Returns
nothing.
Definition at line 50 of file datastore.h.
Referenced by channel_do_masquerade().
destroy
void(* destroy) (void *data)
Destroy function
Definition at line 34 of file datastore.h.
Referenced by ast_datastore_free(), datastore_destroy(), session_datastore_destroy(), and sip_outbound_publish_datastore_destroy().
duplicate
void*(* duplicate) (void *data)
Duplicate item data (used for inheritance)
Definition at line 33 of file datastore.h.
Referenced by ast_channel_datastore_inherit().
type
const char* type
Type of data store
Definition at line 32 of file datastore.h.
Referenced by add_header(), bridge_basic_change_personality(), get_chan_by_ast_name(), incoming_request(), Property::load(), outgoing_request(), read_header(), remove_header(), and update_header().
The documentation for this struct was generated from the following file:
datastore.h