Asterisk - The Open Source Telephony Project: app_blind_transfer.c File Reference
app_blind_transfer.c File Reference
Dial plan applications
Blind transfer by caller channel.
#include "asterisk.h"
#include "asterisk/pbx.h"
#include "asterisk/module.h"
#include "asterisk/app.h"
#include "asterisk/channel.h"
#include "asterisk/bridge.h"
Functions
AST_MODULE_INFO_STANDARD_EXTENDED (ASTERISK_GPL_KEY, "Blind transfer channel to the given destination")
static int blind_transfer_exec (struct ast_channel *chan, const char *data)
static int load_module (void)
static int unload_module (void)
Variables
static const char *const app = "BlindTransfer"
Detailed Description
Blind transfer by caller channel.
Author
Alexei Gradinari alex2.nosp@m.grad.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Definition in file app_blind_transfer.c.
Function Documentation
AST_MODULE_INFO_STANDARD_EXTENDED()
AST_MODULE_INFO_STANDARD_EXTENDED (ASTERISK_GPL_KEY , "Blind transfer channel to the given destination")
Referenced by load_module().
blind_transfer_exec()
static int blind_transfer_exec (struct ast_channel * chan, const char * data) static
Definition at line 81 of file app_blind_transfer.c.
References app, args, AST_APP_ARG, ast_bridge_transfer_blind(), AST_BRIDGE_TRANSFER_FAIL, AST_BRIDGE_TRANSFER_INVALID, AST_BRIDGE_TRANSFER_NOT_PERMITTED, AST_BRIDGE_TRANSFER_SUCCESS, ast_channel_context(), AST_DECLARE_APP_ARGS, ast_log, AST_STANDARD_APP_ARGS, ast_strdupa, ast_strlen_zero, context, exten, LOG_WARNING, NULL, parse(), and pbx_builtin_setvar_helper().
Referenced by load_module().
 {
    char *exten = NULL;
    char *context = NULL;
    char *parse;
    AST_DECLARE_APP_ARGS(args,
       AST_APP_ARG(exten);
       AST_APP_ARG(context);
    );
    if (ast_strlen_zero((char *)data)) {
       ast_log(LOG_WARNING, "%s requires an argument (exten)\n", app);
       pbx_builtin_setvar_helper(chan, "BLINDTRANSFERSTATUS", "FAILURE");
       return 0;
    }
    parse = ast_strdupa(data);
    AST_STANDARD_APP_ARGS(args, parse);
    exten = args.exten;
    if (ast_strlen_zero(args.context)) {
       context = (char *)ast_channel_context(chan);
    } else {
       context = args.context;
    }
    switch (ast_bridge_transfer_blind(1, chan, exten, context, NULL, NULL)) {
       case AST_BRIDGE_TRANSFER_NOT_PERMITTED:
          pbx_builtin_setvar_helper(chan, "BLINDTRANSFERSTATUS", "NOTPERMITTED");
          break;
       case AST_BRIDGE_TRANSFER_INVALID:
          pbx_builtin_setvar_helper(chan, "BLINDTRANSFERSTATUS", "INVALID");
          break;
       case AST_BRIDGE_TRANSFER_FAIL:
          pbx_builtin_setvar_helper(chan, "BLINDTRANSFERSTATUS", "FAILURE");
          break;
       case AST_BRIDGE_TRANSFER_SUCCESS:
          pbx_builtin_setvar_helper(chan, "BLINDTRANSFERSTATUS", "SUCCESS");
          break;
       default:
          pbx_builtin_setvar_helper(chan, "BLINDTRANSFERSTATUS", "FAILURE");
         }
    return 0;
 }
load_module()
static int load_module (void) static
Definition at line 132 of file app_blind_transfer.c.
References app, AST_MODULE_INFO_STANDARD_EXTENDED(), ast_register_application_xml, ASTERISK_GPL_KEY, and blind_transfer_exec().
 {
    return ast_register_application_xml(app, blind_transfer_exec);
 }
unload_module()
static int unload_module (void) static
Definition at line 127 of file app_blind_transfer.c.
References app, and ast_unregister_application().
 {
    return ast_unregister_application(app);
 }
Variable Documentation
app
const char* const app = "BlindTransfer" static
Definition at line 79 of file app_blind_transfer.c.
Referenced by blind_transfer_exec(), load_module(), and unload_module().