Asterisk - The Open Source Telephony Project: dns_core.h File Reference
dns_core.h File Reference
Core DNS API.
#include "asterisk/netsock2.h"
Typedefs
typedef void(* ast_dns_resolve_callback) (const struct ast_dns_query *query)
Callback invoked when a query completes.
Functions
void * ast_dns_query_get_data (const struct ast_dns_query *query)
Get the user specific data of a DNS query.
const char * ast_dns_query_get_name (const struct ast_dns_query *query)
Get the name queried in a DNS query.
struct ast_dns_result * ast_dns_query_get_result (const struct ast_dns_query *query)
Get the result information for a DNS query.
int ast_dns_query_get_rr_class (const struct ast_dns_query *query)
Get the record resource class of a DNS query.
int ast_dns_query_get_rr_type (const struct ast_dns_query *query)
Get the record resource type of a DNS query.
const char * ast_dns_record_get_data (const struct ast_dns_record *record)
Retrieve the raw DNS record.
size_t ast_dns_record_get_data_size (const struct ast_dns_record *record)
Retrieve the size of the raw DNS record.
const struct ast_dns_record * ast_dns_record_get_next (const struct ast_dns_record *record)
Get the next DNS record.
int ast_dns_record_get_rr_class (const struct ast_dns_record *record)
Get the resource record class of a DNS record.
int ast_dns_record_get_rr_type (const struct ast_dns_record *record)
Get the resource record type of a DNS record.
int ast_dns_record_get_ttl (const struct ast_dns_record *record)
Get the TTL of a DNS record.
int ast_dns_resolve (const char *name, int rr_type, int rr_class, struct ast_dns_result **result)
Synchronously resolve a DNS query.
struct ast_dns_query_active * ast_dns_resolve_async (const char *name, int rr_type, int rr_class, ast_dns_resolve_callback callback, void *data)
Asynchronously resolve a DNS query.
int ast_dns_resolve_cancel (struct ast_dns_query_active *active)
Cancel an asynchronous DNS resolution.
int ast_dns_resolve_ipv6_and_ipv4 (struct ast_sockaddr *address, const char *host, const char *port)
Synchronously resolves host to an AAAA or A record.
void ast_dns_result_free (struct ast_dns_result *result)
Free the DNS result information.
const char * ast_dns_result_get_answer (const struct ast_dns_result *result)
Get the raw DNS answer from a DNS result.
unsigned int ast_dns_result_get_bogus (const struct ast_dns_result *result)
Get whether the result is bogus or not.
const char * ast_dns_result_get_canonical (const struct ast_dns_result *result)
Get the canonical name of the result.
int ast_dns_result_get_lowest_ttl (const struct ast_dns_result *result)
Retrieve the lowest TTL from a result.
unsigned int ast_dns_result_get_rcode (const struct ast_dns_result *result)
Get the error rcode of a DN result.
const struct ast_dns_record * ast_dns_result_get_records (const struct ast_dns_result *result)
Get the first record of a DNS Result.
unsigned int ast_dns_result_get_secure (const struct ast_dns_result *result)
Get whether the result is secure or not.
Detailed Description
Core DNS API.
Author
Joshua Colp jcolp.nosp@m.@dig.nosp@m.ium.c.nosp@m.om
Definition in file dns_core.h.
Typedef Documentation
ast_dns_resolve_callback
typedef void(* ast_dns_resolve_callback) (const struct ast_dns_query *query)
Callback invoked when a query completes.
Parameters
query The DNS query that was invoked
Definition at line 171 of file dns_core.h.
Function Documentation
ast_dns_query_get_data()
void* ast_dns_query_get_data (const struct ast_dns_query * query)
Get the user specific data of a DNS query.
Parameters
query The DNS query
Returns
the user specific data
Note
The reference count of the data is NOT incremented on return
Definition at line 72 of file dns_core.c.
References ast_dns_query::user_data.
Referenced by async_callback(), dns_query_recurring_resolution_callback(), dns_query_set_callback(), dns_synchronous_resolve_callback(), minimal_callback(), off_nominal_async_callback(), query_set_cancel(), query_set_resolve(), recurring_cancel(), recurring_resolve(), and resolution_thread().
 {
    return query->user_data;
 }
ast_dns_query_get_name()
const char* ast_dns_query_get_name (const struct ast_dns_query * query)
Get the name queried in a DNS query.
Parameters
query The DNS query
Returns
the name queried
Definition at line 57 of file dns_core.c.
References ast_dns_query::name.
Referenced by dns_system_resolver_process_query(), dns_system_resolver_resolve(), dns_system_resolver_set_response(), query_set_test(), sip_resolve_callback(), unbound_resolver_callback(), and unbound_resolver_resolve().
 {
    return query->name;
 }
ast_dns_query_get_result()
struct ast_dns_result* ast_dns_query_get_result (const struct ast_dns_query * query)
Get the result information for a DNS query.
Parameters
query The DNS query
Returns
the DNS result information
Note
The result is NOT ao2 allocated
Definition at line 77 of file dns_core.c.
References ast_dns_query::result.
Referenced by ast_dns_resolve_ipv6_and_ipv4(), AST_TEST_DEFINE(), async_callback(), dns_query_recurring_resolution_callback(), dns_system_resolver_set_response(), off_nominal_async_callback(), sip_resolve_callback(), and test_results().
 {
    return query->result;
 }
ast_dns_query_get_rr_class()
int ast_dns_query_get_rr_class (const struct ast_dns_query * query)
Get the record resource class of a DNS query.
Parameters
query The DNS query
Returns
the record resource class
Definition at line 67 of file dns_core.c.
References ast_dns_query::rr_class.
Referenced by dns_system_resolver_add_record(), dns_system_resolver_process_query(), query_set_test(), and unbound_resolver_resolve().
 {
    return query->rr_class;
 }
ast_dns_query_get_rr_type()
int ast_dns_query_get_rr_type (const struct ast_dns_query * query)
Get the record resource type of a DNS query.
Parameters
query The DNS query
Returns
the record resource type
Definition at line 62 of file dns_core.c.
References ast_dns_query::rr_type.
Referenced by ast_dns_resolver_completed(), dns_system_resolver_add_record(), dns_system_resolver_process_query(), query_set_test(), sip_resolve_callback(), and unbound_resolver_resolve().
 {
    return query->rr_type;
 }
ast_dns_record_get_data()
const char* ast_dns_record_get_data (const struct ast_dns_record * record)
Retrieve the raw DNS record.
Parameters
record The DNS record
Returns
the raw DNS record
Definition at line 160 of file dns_core.c.
References ast_dns_record::data_ptr.
Referenced by ast_dns_resolve_ipv6_and_ipv4(), ast_dns_txt_get_strings(), async_callback(), nominal_sync_run(), sip_resolve_callback(), and test_record().
 {
    return record->data_ptr;
 }
ast_dns_record_get_data_size()
size_t ast_dns_record_get_data_size (const struct ast_dns_record * record)
Retrieve the size of the raw DNS record.
Parameters
record The DNS record
Returns
the size of the raw DNS record
Definition at line 165 of file dns_core.c.
References ast_dns_record::data_len.
Referenced by ast_dns_resolve_ipv6_and_ipv4(), ast_dns_txt_get_strings(), and sip_resolve_callback().
 {
    return record->data_len;
 }
ast_dns_record_get_next()
const struct ast_dns_record* ast_dns_record_get_next (const struct ast_dns_record * record)
Get the next DNS record.
Parameters
record The current DNS record
Returns
the next DNS record
Definition at line 170 of file dns_core.c.
References AST_LIST_NEXT, and ast_dns_record::list.
Referenced by ast_dns_resolve_ipv6_and_ipv4(), ast_dns_result_get_lowest_ttl(), AST_TEST_DEFINE(), async_callback(), nominal_sync_run(), nominal_test(), and sip_resolve_callback().
 {
    return AST_LIST_NEXT(record, list);
 }
ast_dns_record_get_rr_class()
int ast_dns_record_get_rr_class (const struct ast_dns_record * record)
Get the resource record class of a DNS record.
Parameters
record The DNS record
Returns
the resource record class
Definition at line 150 of file dns_core.c.
References ast_dns_record::rr_class.
Referenced by async_callback(), nominal_sync_run(), and test_record().
 {
    return record->rr_class;
 }
ast_dns_record_get_rr_type()
int ast_dns_record_get_rr_type (const struct ast_dns_record * record)
Get the resource record type of a DNS record.
Parameters
record The DNS record
Returns
the resource record type
Definition at line 145 of file dns_core.c.
References ast_dns_record::rr_type.
Referenced by ast_dns_naptr_get_flags(), ast_dns_naptr_get_order(), ast_dns_naptr_get_preference(), ast_dns_naptr_get_regexp(), ast_dns_naptr_get_replacement(), ast_dns_naptr_get_service(), ast_dns_resolve_ipv6_and_ipv4(), ast_dns_srv_get_host(), ast_dns_srv_get_port(), ast_dns_srv_get_priority(), ast_dns_srv_get_weight(), ast_dns_txt_get_count(), ast_dns_txt_get_strings(), AST_TEST_DEFINE(), async_callback(), nominal_sync_run(), sip_resolve_callback(), and test_record().
 {
    return record->rr_type;
 }
ast_dns_record_get_ttl()
int ast_dns_record_get_ttl (const struct ast_dns_record * record)
Get the TTL of a DNS record.
Parameters
record The DNS record
Returns
the TTL
Definition at line 155 of file dns_core.c.
References ast_dns_record::ttl.
Referenced by ast_dns_result_get_lowest_ttl(), async_callback(), nominal_sync_run(), and test_record().
 {
    return record->ttl;
 }
ast_dns_resolve()
int ast_dns_resolve (const char * name, int rr_type, int rr_class, struct ast_dns_result ** result)
Synchronously resolve a DNS query.
Parameters
name The name of what to resolve
rr_type Resource record type
rr_class Resource record class
result A pointer to hold the DNS result
Return values
0 success - query was completed and result is available
-1 failure
Definition at line 314 of file dns_core.c.
References AO2_ALLOC_OPT_LOCK_NOLOCK, ao2_alloc_options, ao2_ref, ast_cond_init, ast_cond_wait, ast_dns_resolve_async(), ast_log, ast_mutex_init, ast_mutex_lock, ast_mutex_unlock, ast_strlen_zero, dns_synchronous_resolve::completed, dns_synchronous_resolve::cond, dns_synchronous_resolve_callback(), dns_synchronous_resolve_destroy(), dns_synchronous_resolve::lock, LOG_WARNING, NULL, and dns_synchronous_resolve::result.
Referenced by AST_TEST_DEFINE(), invalid_record_test(), nominal_sync_run(), nominal_test(), off_nominal_sync_run(), and off_nominal_test().
 {
    struct dns_synchronous_resolve *synchronous;
    struct ast_dns_query_active *active;
    if (ast_strlen_zero(name)) {
       ast_log(LOG_WARNING, "Could not perform synchronous resolution, no name provided\n");
       return -1;
    } else if (rr_type > 65536) {
       ast_log(LOG_WARNING, "Could not perform synchronous resolution of '%s', resource record type '%d' exceeds maximum\n",
          name, rr_type);
       return -1;
    } else if (rr_type < 0) {
       ast_log(LOG_WARNING, "Could not perform synchronous resolution of '%s', invalid resource record type '%d'\n",
          name, rr_type);
       return -1;
    } else if (rr_class > 65536) {
       ast_log(LOG_WARNING, "Could not perform synchronous resolution of '%s', resource record class '%d' exceeds maximum\n",
          name, rr_class);
       return -1;
    } else if (rr_class < 0) {
       ast_log(LOG_WARNING, "Could not perform synchronous resolution of '%s', invalid resource class '%d'\n",
          name, rr_class);
       return -1;
    } else if (!result) {
       ast_log(LOG_WARNING, "Could not perform synchronous resolution of '%s', no result pointer provided for storing results\n",
          name);
       return -1;
    }
    synchronous = ao2_alloc_options(sizeof(*synchronous), dns_synchronous_resolve_destroy, AO2_ALLOC_OPT_LOCK_NOLOCK);
    if (!synchronous) {
       return -1;
    }
    ast_mutex_init(&synchronous->lock);
    ast_cond_init(&synchronous->cond, NULL);
    active = ast_dns_resolve_async(name, rr_type, rr_class, dns_synchronous_resolve_callback, synchronous);
    if (active) {
       /* Wait for resolution to complete */
       ast_mutex_lock(&synchronous->lock);
       while (!synchronous->completed) {
          ast_cond_wait(&synchronous->cond, &synchronous->lock);
       }
       ast_mutex_unlock(&synchronous->lock);
       ao2_ref(active, -1);
    }
    *result = synchronous->result;
    ao2_ref(synchronous, -1);
    return *result ? 0 : -1;
 }
ast_dns_resolve_async()
struct ast_dns_query_active* ast_dns_resolve_async (const char * name, int rr_type, int rr_class, ast_dns_resolve_callback callback, void * data)
Asynchronously resolve a DNS query.
Parameters
name The name of what to resolve
rr_type Resource record type
rr_class Resource record class
callback The callback to invoke upon completion
data User data to make available on the query
Return values
non-NULL success - query has been sent for resolution
NULL failure
Note
The result passed to the callback does not need to be freed
The user data MUST be an ao2 object
This function increments the reference count of the user data, it does NOT steal
The active query must be released upon completion or cancellation using ao2_ref
Definition at line 247 of file dns_core.c.
References AO2_ALLOC_OPT_LOCK_NOLOCK, ao2_alloc_options, ao2_ref, ast_log, dns_query_active_destroy(), dns_query_alloc(), LOG_ERROR, ast_dns_resolver::name, NULL, ast_dns_query_active::query, ast_dns_resolver::resolve, and ast_dns_query::resolver.
Referenced by ast_dns_resolve(), ast_dns_resolve_recurring(), AST_TEST_DEFINE(), dns_query_recurring_scheduled_callback(), nominal_async_run(), and off_nominal_async_run().
 {
    struct ast_dns_query_active *active;
    active = ao2_alloc_options(sizeof(*active), dns_query_active_destroy, AO2_ALLOC_OPT_LOCK_NOLOCK);
    if (!active) {
       return NULL;
    }
    active->query = dns_query_alloc(name, rr_type, rr_class, callback, data);
    if (!active->query) {
       ao2_ref(active, -1);
       return NULL;
    }
    if (active->query->resolver->resolve(active->query)) {
       ast_log(LOG_ERROR, "Resolver '%s' returned an error when resolving '%s' of class '%d' and type '%d'\n",
          active->query->resolver->name, name, rr_class, rr_type);
       ao2_ref(active, -1);
       return NULL;
    }
    return active;
 }
ast_dns_resolve_cancel()
int ast_dns_resolve_cancel (struct ast_dns_query_active * active)
Cancel an asynchronous DNS resolution.
Parameters
active The active DNS query returned from ast_dns_resolve_async
Return values
0 success
-1 failure
Note
If successfully cancelled the callback will not be invoked
Definition at line 272 of file dns_core.c.
References ast_dns_resolver::cancel, ast_dns_query_active::query, and ast_dns_query::resolver.
Referenced by ast_dns_resolve_recurring_cancel(), and AST_TEST_DEFINE().
 {
    return active->query->resolver->cancel(active->query);
 }
ast_dns_resolve_ipv6_and_ipv4()
int ast_dns_resolve_ipv6_and_ipv4 (struct ast_sockaddr * address, const char * host, const char * port)
Synchronously resolves host to an AAAA or A record.
Since
16.6.0
Parameters
address A pointer to an ast_sockaddr structure to receive the IPv6 or IPv4 address
host The hostname to resolve
port (optional) A port to parse into the final ast_sockaddr structure
Return values
0 success - query was completed and result is available
-1 failure
Note
This function makes parallel queries for both AAAA and A records for the host. The first returned AAAA record (if any) is used and if not found, the first A record is used.
Warning
This function is synchronous and will block until records are returned or an error occurrs.
Definition at line 369 of file dns_core.c.
References ao2_cleanup, ast_debug, ast_dns_query_get_result(), ast_dns_query_set_add(), ast_dns_query_set_create(), ast_dns_query_set_get(), ast_dns_query_set_num_queries(), ast_dns_record_get_data(), ast_dns_record_get_data_size(), ast_dns_record_get_next(), ast_dns_record_get_rr_type(), ast_dns_result_get_records(), ast_log, ast_query_set_resolve(), ast_strlen_zero, ast_dns_record::data, ast_sockaddr::len, LOG_ERROR, RAII_VAR, dns_synchronous_resolve::result, ast_dns_record::rr_type, and ast_sockaddr::ss.
Referenced by unicast_rtp_request().
 {
    RAII_VAR(struct ast_dns_query_set *, queries, ast_dns_query_set_create(), ao2_cleanup);
    int i;
    int rc;
    if (!queries) {
       ast_log(LOG_ERROR, "Couldn't allocate DNS query structure\n");
       return -1;
    }
    rc = ast_dns_query_set_add(queries, host, ns_t_aaaa, ns_c_in);
    if (rc != 0) {
       ast_log(LOG_ERROR, "Couldn't add 'AAAA' DNS query for '%s'\n", host);
       return -1;
    }
    rc = ast_dns_query_set_add(queries, host, ns_t_a, ns_c_in);
    if (rc != 0) {
       ast_log(LOG_ERROR, "Couldn't add 'A' DNS query for '%s'\n", host);
       return -1;
    }
    rc = ast_query_set_resolve(queries);
    if (rc != 0) {
       ast_log(LOG_ERROR, "Query set resolve failure for '%s'\n", host);
       return -1;
    }
    for (i = 0; i < ast_dns_query_set_num_queries(queries); ++i) {
       struct ast_dns_query *query = ast_dns_query_set_get(queries, i);
       struct ast_dns_result *result = ast_dns_query_get_result(query);
       const struct ast_dns_record *record;
       in_port_t in_port = 0;
       if (!ast_strlen_zero(port)) {
          in_port = htons(atoi(port));
       }
       for (record = ast_dns_result_get_records(result); record; record = ast_dns_record_get_next(record)) {
          size_t data_size = ast_dns_record_get_data_size(record);
          const unsigned char *data = (unsigned char *)ast_dns_record_get_data(record);
          int rr_type = ast_dns_record_get_rr_type(record);
          if (rr_type == ns_t_aaaa && data_size == 16) {
             struct sockaddr_in6 sin6 = { 0, };
             sin6.sin6_port = in_port;
             memcpy(&sin6.sin6_addr, data, data_size);
             sin6.sin6_family = AF_INET6;
             memcpy(&address->ss, &sin6, sizeof(sin6));
             address->len = sizeof(sin6);
             return 0;
          } else if (rr_type == ns_t_a && data_size == 4) {
             struct sockaddr_in sin4 = { 0, };
             sin4.sin_port = in_port;
             memcpy(&sin4.sin_addr, data, data_size);
             sin4.sin_family = AF_INET;
             memcpy(&address->ss, &sin4, sizeof(sin4));
             address->len = sizeof(sin4);
             return 0;
          } else {
             ast_debug(3, "Unrecognized rr_type '%u' or data_size '%zu' from DNS query for host '%s'\n",
                rr_type, data_size, host);
             continue;
          }
       }
    }
    return -1;
 }
ast_dns_result_free()
void ast_dns_result_free (struct ast_dns_result * result)
Free the DNS result information.
Parameters
result The DNS result
Definition at line 130 of file dns_core.c.
References ast_free, AST_LIST_REMOVE_HEAD, ast_dns_record::list, and ast_dns_result::records.
Referenced by ast_dns_resolver_set_result(), AST_TEST_DEFINE(), dns_query_destroy(), invalid_record_test(), nominal_sync_run(), nominal_test(), off_nominal_sync_run(), and off_nominal_test().
 {
    struct ast_dns_record *record;
    if (!result) {
       return;
    }
    while ((record = AST_LIST_REMOVE_HEAD(&result->records, list))) {
       ast_free(record);
    }
    ast_free(result);
 }
ast_dns_result_get_answer()
const char* ast_dns_result_get_answer (const struct ast_dns_result * result)
Get the raw DNS answer from a DNS result.
Parameters
result The DNS result
Returns
The DNS result
Definition at line 107 of file dns_core.c.
References ast_dns_result::answer.
Referenced by test_results().
 {
    return result->answer;
 }
ast_dns_result_get_bogus()
unsigned int ast_dns_result_get_bogus (const struct ast_dns_result * result)
Get whether the result is bogus or not.
Parameters
result The DNS result
Returns
whether the result is bogus or not
Definition at line 87 of file dns_core.c.
References ast_dns_result::bogus.
Referenced by test_results().
 {
    return result->bogus;
 }
ast_dns_result_get_canonical()
const char* ast_dns_result_get_canonical (const struct ast_dns_result * result)
Get the canonical name of the result.
Parameters
result The DNS result
Returns
the canonical name
Definition at line 97 of file dns_core.c.
References ast_dns_result::canonical.
Referenced by test_results().
 {
    return result->canonical;
 }
ast_dns_result_get_lowest_ttl()
int ast_dns_result_get_lowest_ttl (const struct ast_dns_result * result)
Retrieve the lowest TTL from a result.
Parameters
result The DNS result
Returns
the lowest TTL
Note
If no records exist this function will return a TTL of 0
Definition at line 112 of file dns_core.c.
References ast_dns_record_get_next(), ast_dns_record_get_ttl(), ast_dns_result_get_rcode(), ast_dns_result_get_records(), and ast_dns_record::ttl.
Referenced by dns_query_recurring_resolution_callback().
 {
    int ttl = 0;
    const struct ast_dns_record *record;
    if (ast_dns_result_get_rcode(result) == NXDOMAIN) {
       return 0;
    }
    for (record = ast_dns_result_get_records(result); record; record = ast_dns_record_get_next(record)) {
       if (!ttl || (ast_dns_record_get_ttl(record) && (ast_dns_record_get_ttl(record) < ttl))) {
          ttl = ast_dns_record_get_ttl(record);
       }
    }
    return ttl;
 }
ast_dns_result_get_rcode()
unsigned int ast_dns_result_get_rcode (const struct ast_dns_result * result)
Get the error rcode of a DN result.
Parameters
query The DNS result
Returns
the DNS rcode
Definition at line 92 of file dns_core.c.
References ast_dns_result::rcode.
Referenced by ast_dns_result_get_lowest_ttl(), off_nominal_async_callback(), off_nominal_sync_run(), and test_results().
 {
    return result->rcode;
 }
ast_dns_result_get_records()
const struct ast_dns_record* ast_dns_result_get_records (const struct ast_dns_result * result)
Get the first record of a DNS Result.
Parameters
result The DNS result
Returns
first DNS record
Definition at line 102 of file dns_core.c.
References AST_LIST_FIRST, and ast_dns_result::records.
Referenced by ast_dns_resolve_ipv6_and_ipv4(), ast_dns_result_get_lowest_ttl(), AST_TEST_DEFINE(), async_callback(), invalid_record_test(), nominal_sync_run(), nominal_test(), off_nominal_async_callback(), off_nominal_sync_run(), off_nominal_test(), and sip_resolve_callback().
 {
    return AST_LIST_FIRST(&result->records);
 }
ast_dns_result_get_secure()
unsigned int ast_dns_result_get_secure (const struct ast_dns_result * result)
Get whether the result is secure or not.
Parameters
result The DNS result
Returns
whether the result is secure or not
Definition at line 82 of file dns_core.c.
References ast_dns_result::secure.
Referenced by test_results().
 {
    return result->secure;
 }