Asterisk - The Open Source Telephony Project: ast_speech_engine Struct Reference
ast_speech_engine Struct Reference
#include <speech.h>
Public Member Functions
AST_LIST_ENTRY (ast_speech_engine) list
Data Fields
int(* activate)(struct ast_speech *speech, const char *grammar_name)
int(* change)(struct ast_speech *speech, const char *name, const char *value)
int(* change_results_type)(struct ast_speech *speech, enum ast_speech_results_type results_type)
int(* create)(struct ast_speech *speech, struct ast_format *format)
int(* deactivate)(struct ast_speech *speech, const char *grammar_name)
int(* destroy)(struct ast_speech *speech)
int(* dtmf)(struct ast_speech *speech, const char *dtmf)
struct ast_format_cap * formats
struct ast_speech_result *(* get)(struct ast_speech *speech)
int(* get_setting)(struct ast_speech *speech, const char *name, char *buf, size_t len)
int(* load)(struct ast_speech *speech, const char *grammar_name, const char *grammar)
char * name
int(* start)(struct ast_speech *speech)
int(* unload)(struct ast_speech *speech, const char *grammar_name)
int(* write)(struct ast_speech *speech, void *data, int len)
Detailed Description
Definition at line 73 of file speech.h.
Member Function Documentation
AST_LIST_ENTRY()
AST_LIST_ENTRY (ast_speech_engine)
Field Documentation
activate
int(* activate) (struct ast_speech *speech, const char *grammar_name)
Activate a loaded grammar
Definition at line 85 of file speech.h.
Referenced by ast_speech_grammar_activate().
change
int(* change) (struct ast_speech *speech, const char *name, const char *value)
Change an engine specific setting
Definition at line 95 of file speech.h.
Referenced by ast_speech_change().
change_results_type
int(* change_results_type) (struct ast_speech *speech, enum ast_speech_results_type results_type)
Change the type of results we want back
Definition at line 99 of file speech.h.
Referenced by ast_speech_change_results_type().
create
int(* create) (struct ast_speech *speech, struct ast_format *format)
Set up the speech structure within the engine
Definition at line 77 of file speech.h.
Referenced by ast_speech_new(), and ast_speech_register().
deactivate
int(* deactivate) (struct ast_speech *speech, const char *grammar_name)
Deactivate a loaded grammar
Definition at line 87 of file speech.h.
Referenced by ast_speech_grammar_deactivate().
destroy
int(* destroy) (struct ast_speech *speech)
Destroy any data set on the speech structure by the engine
Definition at line 79 of file speech.h.
Referenced by ast_speech_destroy(), and ast_speech_register().
dtmf
int(* dtmf) (struct ast_speech *speech, const char *dtmf)
Signal DTMF was received
Definition at line 91 of file speech.h.
Referenced by ast_speech_dtmf().
formats
struct ast_format_cap* formats
Accepted formats by the engine
Definition at line 103 of file speech.h.
Referenced by ast_speech_new().
get
struct ast_speech_result*(* get) (struct ast_speech *speech)
Try to get results
Definition at line 101 of file speech.h.
Referenced by Section::__getitem__(), ast_speech_results_get(), and MultiOrderedConfigParser::multi_get().
get_setting
int(* get_setting) (struct ast_speech *speech, const char *name, char *buf, size_t len)
Get an engine specific setting
Definition at line 97 of file speech.h.
Referenced by ast_speech_get_setting().
load
int(* load) (struct ast_speech *speech, const char *grammar_name, const char *grammar)
Load a local grammar on the speech structure
Definition at line 81 of file speech.h.
Referenced by ast_speech_grammar_load(), ApiDeclaration::load_file(), ResourceListing::load_file(), and load_module().
name
char* name
Name of speech engine
Definition at line 75 of file speech.h.
Referenced by ast_speech_register(), ast_speech_unregister(), find_engine(), PathSegment::get_child(), Parameter::load(), SwaggerType::load(), and Property::load().
start
int(* start) (struct ast_speech *speech)
Prepare engine to accept audio
Definition at line 93 of file speech.h.
Referenced by ast_speech_start().
unload
int(* unload) (struct ast_speech *speech, const char *grammar_name)
Unload a local grammar
Definition at line 83 of file speech.h.
Referenced by ast_speech_grammar_unload(), and load_module().
write
int(* write) (struct ast_speech *speech, void *data, int len)
Write audio to the speech engine
Definition at line 89 of file speech.h.
Referenced by ast_speech_register(), ast_speech_write(), and MultiOrderedConfigParser::write().
The documentation for this struct was generated from the following file:
speech.h