Asterisk - The Open Source Telephony Project: test_endpoints.c File Reference
test_endpoints.c File Reference
Test endpoints.
#include "asterisk.h"
#include "asterisk/astobj2.h"
#include "asterisk/endpoints.h"
#include "asterisk/module.h"
#include "asterisk/stasis_endpoints.h"
#include "asterisk/test.h"
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
AST_TEST_DEFINE (create)
AST_TEST_DEFINE (defaults)
AST_TEST_DEFINE (setters)
static int load_module (void)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_DEFAULT , .description = "Endpoint testing" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, }
static const struct ast_module_info * ast_module_info = &__mod_info
static const char * test_category = "/core/endpoints/"
Detailed Description
Test endpoints.
Author
David M. Lee, II <dlee@digium.com>
Definition in file test_endpoints.c.
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 157 of file test_endpoints.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 157 of file test_endpoints.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 157 of file test_endpoints.c.
AST_TEST_DEFINE() [1/3]
AST_TEST_DEFINE (create)
Definition at line 43 of file test_endpoints.c.
References ast_endpoint_create(), ast_endpoint_get_resource(), ast_endpoint_get_tech(), ast_endpoint_shutdown(), AST_TEST_NOT_RUN, AST_TEST_PASS, sip_to_pjsip::info(), NULL, RAII_VAR, test_category, TEST_EXECUTE, and TEST_INIT.
 {
    RAII_VAR(struct ast_endpoint *, uut, NULL, ast_endpoint_shutdown);
    switch (cmd) {
    case TEST_INIT:
       info->name = __func__;
       info->category = test_category;
       info->summary = "Test endpoint creation";
       info->description = "Test endpoint creation";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    ast_test_validate(test, NULL == ast_endpoint_create(NULL, NULL));
    ast_test_validate(test, NULL == ast_endpoint_create("", ""));
    ast_test_validate(test, NULL == ast_endpoint_create("TEST", ""));
    ast_test_validate(test, NULL == ast_endpoint_create("", "test_res"));
    uut = ast_endpoint_create("TEST", "test_res");
    ast_test_validate(test, NULL != uut);
    ast_test_validate(test,
       0 == strcmp("TEST", ast_endpoint_get_tech(uut)));
    ast_test_validate(test,
       0 == strcmp("test_res", ast_endpoint_get_resource(uut)));
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [2/3]
AST_TEST_DEFINE (defaults)
Definition at line 75 of file test_endpoints.c.
References ao2_cleanup, ast_endpoint_create(), ast_endpoint_shutdown(), ast_endpoint_snapshot_create(), AST_ENDPOINT_UNKNOWN, AST_TEST_NOT_RUN, AST_TEST_PASS, sip_to_pjsip::info(), NULL, RAII_VAR, test_category, TEST_EXECUTE, and TEST_INIT.
 {
    RAII_VAR(struct ast_endpoint *, uut, NULL, ast_endpoint_shutdown);
    RAII_VAR(struct ast_endpoint_snapshot *, snapshot, NULL, ao2_cleanup);
    switch (cmd) {
    case TEST_INIT:
       info->name = __func__;
       info->category = test_category;
       info->summary = "Test defaults for new endpoints";
       info->description = "Test defaults for new endpoints";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    uut = ast_endpoint_create("TEST", "test_res");
    ast_test_validate(test, NULL != uut);
    snapshot = ast_endpoint_snapshot_create(uut);
    ast_test_validate(test, NULL != snapshot);
    ast_test_validate(test, 0 == strcmp("TEST/test_res", snapshot->id));
    ast_test_validate(test, 0 == strcmp("TEST", snapshot->tech));
    ast_test_validate(test, 0 == strcmp("test_res", snapshot->resource));
    ast_test_validate(test, AST_ENDPOINT_UNKNOWN == snapshot->state);
    ast_test_validate(test, -1 == snapshot->max_channels);
    ast_test_validate(test, 0 == snapshot->num_channels);
    return AST_TEST_PASS;
 }
AST_TEST_DEFINE() [3/3]
AST_TEST_DEFINE (setters)
Definition at line 106 of file test_endpoints.c.
References ao2_cleanup, ast_endpoint_create(), AST_ENDPOINT_ONLINE, ast_endpoint_set_max_channels(), ast_endpoint_set_state(), ast_endpoint_shutdown(), ast_endpoint_snapshot_create(), AST_TEST_NOT_RUN, AST_TEST_PASS, sip_to_pjsip::info(), NULL, RAII_VAR, test_category, TEST_EXECUTE, and TEST_INIT.
 {
    RAII_VAR(struct ast_endpoint *, uut, NULL, ast_endpoint_shutdown);
    RAII_VAR(struct ast_endpoint_snapshot *, snapshot, NULL, ao2_cleanup);
    switch (cmd) {
    case TEST_INIT:
       info->name = __func__;
       info->category = test_category;
       info->summary = "Test endpoint setters";
       info->description = "Test endpoint setters";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    uut = ast_endpoint_create("TEST", "test_res");
    ast_test_validate(test, NULL != uut);
    ast_endpoint_set_state(uut, AST_ENDPOINT_ONLINE);
    ast_endpoint_set_max_channels(uut, 314159);
    snapshot = ast_endpoint_snapshot_create(uut);
    ast_test_validate(test, NULL != snapshot);
    ast_test_validate(test, AST_ENDPOINT_ONLINE == snapshot->state);
    ast_test_validate(test, 314159 == snapshot->max_channels);
    return AST_TEST_PASS;
 }
load_module()
static int load_module (void) static
Definition at line 145 of file test_endpoints.c.
References AST_MODFLAG_DEFAULT, AST_MODULE_INFO(), AST_MODULE_LOAD_SUCCESS, AST_MODULE_SUPPORT_CORE, AST_TEST_REGISTER, ASTERISK_GPL_KEY, and unload_module().
 {
    AST_TEST_REGISTER(create);
    AST_TEST_REGISTER(defaults);
    AST_TEST_REGISTER(setters);
    return AST_MODULE_LOAD_SUCCESS;
 }
unload_module()
static int unload_module (void) static
Definition at line 137 of file test_endpoints.c.
References AST_TEST_UNREGISTER.
Referenced by load_module().
 {
    AST_TEST_UNREGISTER(create);
    AST_TEST_UNREGISTER(defaults);
    AST_TEST_UNREGISTER(setters);
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_DEFAULT , .description = "Endpoint testing" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .support_level = AST_MODULE_SUPPORT_CORE, .load = load_module, .unload = unload_module, } static
Definition at line 157 of file test_endpoints.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 157 of file test_endpoints.c.
test_category
const char* test_category = "/core/endpoints/" static
Definition at line 41 of file test_endpoints.c.
Referenced by AST_TEST_DEFINE().