Asterisk - The Open Source Telephony Project: pbx_ignorepat.c File Reference
pbx_ignorepat.c File Reference
Dialplan context ignorepat routines.
#include "asterisk.h"
#include "asterisk/_private.h"
#include "asterisk/pbx.h"
#include "pbx_private.h"
Data Structures
struct ast_ignorepat
ast_ignorepat: Ignore patterns in dial plan
Functions
const char * ast_get_ignorepat_name (const struct ast_ignorepat *ip)
const char * ast_get_ignorepat_registrar (const struct ast_ignorepat *ip)
struct ast_ignorepat * ignorepat_alloc (const char *value, const char *registrar)
void ignorepat_free (struct ast_ignorepat *ip)
Detailed Description
Dialplan context ignorepat routines.
Author
Corey Farrell git@c.nosp@m.fwar.nosp@m.e.com
Definition in file pbx_ignorepat.c.
Function Documentation
ast_get_ignorepat_name()
const char* ast_get_ignorepat_name (const struct ast_ignorepat * ip)
Definition at line 42 of file pbx_ignorepat.c.
References NULL, and ast_ignorepat::pattern.
Referenced by ast_context_add_ignorepat2(), ast_context_remove_ignorepat2(), ast_ignore_pattern(), complete_dialplan_remove_ignorepat(), context_merge_incls_swits_igps_other_registrars(), handle_cli_dialplan_save(), lookup_c_ip(), manager_show_dialplan_helper(), and show_dialplan_helper().
 {
    return ip ? ip->pattern : NULL;
 }
ast_get_ignorepat_registrar()
const char* ast_get_ignorepat_registrar (const struct ast_ignorepat * ip)
Definition at line 47 of file pbx_ignorepat.c.
References NULL, and ast_ignorepat::registrar.
Referenced by __ast_context_destroy(), ast_context_remove_ignorepat2(), context_merge_incls_swits_igps_other_registrars(), handle_cli_dialplan_save(), manager_show_dialplan_helper(), and show_dialplan_helper().
 {
    return ip ? ip->registrar : NULL;
 }
ignorepat_alloc()
struct ast_ignorepat* ignorepat_alloc (const char * value, const char * registrar)
Definition at line 52 of file pbx_ignorepat.c.
References ast_calloc, NULL, ast_ignorepat::pattern, and ast_ignorepat::registrar.
Referenced by ast_context_add_ignorepat2().
 {
    struct ast_ignorepat *ignorepat;
    int length = strlen(value) + 1;
    char *pattern;
    /* allocate new include structure ... */
    ignorepat = ast_calloc(1, sizeof(*ignorepat) + length);
    if (!ignorepat) {
       return NULL;
    }
    /* The cast to char * is because we need to write the initial value.
     * The field is not supposed to be modified otherwise.  Also, gcc 4.2
     * sees the cast as dereferencing a type-punned pointer and warns about
     * it.  This is the workaround (we're telling gcc, yes, that's really
     * what we wanted to do).
     */
    pattern = (char *) ignorepat->pattern;
    strcpy(pattern, value);
    ignorepat->registrar = registrar;
    return ignorepat;
 }
ignorepat_free()
void ignorepat_free (struct ast_ignorepat * ip)
Definition at line 77 of file pbx_ignorepat.c.
References ast_free.
Referenced by __ast_context_destroy(), __ast_internal_context_destroy(), ast_context_add_ignorepat2(), and ast_context_remove_ignorepat2().
 {
    ast_free(ip);
 }