Asterisk - The Open Source Telephony Project: mwi.h File Reference
mwi.h File Reference
Asterisk MWI API.
#include "asterisk/utils.h"
#include "asterisk/stasis_state.h"
Data Structures
struct ast_mwi_blob
Object that represents an MWI update with some additional application defined data.
struct ast_mwi_observer
MWI state event interface.
struct ast_mwi_state
The structure that contains MWI state.
Macros
#define ast_delete_mwi_state(mailbox, context) ast_delete_mwi_state_full(mailbox, context, NULL)
Delete MWI state cached by stasis.
#define AST_MAX_MAILBOX_UNIQUEID (AST_MAX_EXTENSION + AST_MAX_CONTEXT + 2)
#define ast_publish_mwi_state(mailbox, context, new_msgs, old_msgs) ast_publish_mwi_state_full(mailbox, context, new_msgs, old_msgs, NULL, NULL)
Publish a MWI state update via stasis.
#define ast_publish_mwi_state_channel(mailbox, context, new_msgs, old_msgs, channel_id) ast_publish_mwi_state_full(mailbox, context, new_msgs, old_msgs, channel_id, NULL)
Publish a MWI state update associated with some channel.
Typedefs
typedef int(* on_mwi_state) (struct ast_mwi_state *mwi_state, void *data)
The delegate called for each managed mailbox state.
Functions
int ast_delete_mwi_state_full (const char *mailbox, const char *context, struct ast_eid *eid)
Delete MWI state cached by stasis with all parameters.
int ast_mwi_add_observer (struct ast_mwi_observer *observer)
Add an observer to receive MWI state related events.
struct ast_mwi_publisher * ast_mwi_add_publisher (const char *mailbox)
Add an MWI state publisher to the mailbox.
struct ast_mwi_subscriber * ast_mwi_add_subscriber (const char *mailbox)
Add an MWI state subscriber to the mailbox.
struct stasis_message * ast_mwi_blob_create (struct ast_mwi_state *mwi_state, struct stasis_message_type *message_type, struct ast_json *blob)
Creates a ast_mwi_blob message.
struct ast_mwi_state * ast_mwi_create (const char *mailbox, const char *context)
Create a ast_mwi_state object.
int ast_mwi_publish (struct ast_mwi_publisher *publisher, int urgent_msgs, int new_msgs, int old_msgs, const char *channel_id, struct ast_eid *eid)
Publish MWI for the given mailbox.
int ast_mwi_publish_by_mailbox (const char *mailbox, const char *context, int urgent_msgs, int new_msgs, int old_msgs, const char *channel_id, struct ast_eid *eid)
Publish MWI for the given mailbox.
void ast_mwi_remove_observer (struct ast_mwi_observer *observer)
Remove an MWI state observer.
struct stasis_cache * ast_mwi_state_cache (void)
Backend cache for ast_mwi_topic_cached().
void ast_mwi_state_callback_all (on_mwi_state handler, void *data)
For each managed mailbox call the given handler.
void ast_mwi_state_callback_subscribed (on_mwi_state handler, void *data)
For each managed mailbox that has a subscriber call the given handler.
struct stasis_message_type * ast_mwi_state_type (void)
Get the Stasis Message Bus API message type for MWI messages.
struct ast_mwi_subscriber * ast_mwi_subscribe_pool (const char *mailbox, stasis_subscription_cb callback, void *data)
Add an MWI state subscriber, and stasis subscription to the mailbox.
struct ast_mwi_state * ast_mwi_subscriber_data (struct ast_mwi_subscriber *sub)
Retrieves the state data object associated with the MWI subscriber.
struct stasis_subscription * ast_mwi_subscriber_subscription (struct ast_mwi_subscriber *sub)
Retrieve the stasis MWI topic subscription if available.
struct stasis_topic * ast_mwi_subscriber_topic (struct ast_mwi_subscriber *sub)
Retrieves the MWI subscriber's topic.
struct stasis_topic * ast_mwi_topic (const char *uniqueid)
Get the Stasis Message Bus API topic for MWI messages on a unique ID.
struct stasis_topic * ast_mwi_topic_all (void)
Get the Stasis Message Bus API topic for MWI messages.
struct stasis_topic * ast_mwi_topic_cached (void)
Get the Stasis Message Bus API caching topic for MWI messages.
void * ast_mwi_unsubscribe (struct ast_mwi_subscriber *sub)
Unsubscribe from the stasis topic and MWI.
void * ast_mwi_unsubscribe_and_join (struct ast_mwi_subscriber *sub)
Unsubscribe from the stasis topic, block until the final message is received, and then unsubscribe from MWI.
struct stasis_message_type * ast_mwi_vm_app_type (void)
Get the Stasis Message Bus API message type for voicemail application specific messages.
int ast_publish_mwi_state_full (const char *mailbox, const char *context, int new_msgs, int old_msgs, const char *channel_id, struct ast_eid *eid)
Publish a MWI state update via stasis with all parameters.
int mwi_init (void)
Initialize the mwi core.
Detailed Description
Asterisk MWI API.
Intro
This module manages, and processes all things MWI. Defined are mechanisms for subscribing and publishing to MWI topics. User modules wishing to receive MWI updates for a particular mailbox should do so by adding an MWI subscriber to that mailbox, followed by subscribing to the mailbox's topic. Likewise, user modules that want to publish MWI updates about a particular mailbox should first add a publisher for that mailbox prior to publishing.
MWI state is managed via an underlying stasis_state_manager (if interested see the stasis_state.c module for the gory details). As such all last known mailbox state can be retrieve and iterated over by using the ast_mwi_callback function.
ast_mwi_subscriber
Created via ast_mwi_add_subscriber, a subscriber subscribes to a given mailbox in order to receive updates about the given mailbox. Adding a subscriber will create the underlying topic, and associated state data if those do not already exist for it. The topic, and last known state data is guaranteed to exist for the lifetime of the subscriber. State data can be NULL if nothing has been published to the mailbox's topic yet.
NOTE, currently adding a subscriber here will either create, or add a reference to the underlying stasis state (and associated topic). However, it does not actually subscribe to the stasis topic itself. You still need to explicitly call stasis_subscribe, or similar on the topic if you wish to receive published event updates.
So given that when subscribing to an MWI topic the following order should be adhered to:
Add an MWI state subscriber using ast_mwi_add_subscriber
Retrieve the topic from the subscriber using ast_mwi_subscriber_topic
Subscribe to the topic itself using stasis_subscribe or stasis_subscribe_pool
Or simply call ast_mwi_subscribe_pool, which combines those steps into a single call and returns the subscriber that is now subscribed to both the stasis topic and state.
Similarly, releasing the subscriber's reference removes a reference to the underlying state, but does not unsubscribe from the MWI topic. This should be done separately and prior to removing the subscriber's state reference:
Unsubscribe from the stasis topic subscription using stasis_unsubscribe or stasis_unsubscribe_and_join
Remove the MWI subscriber reference
Or call ast_mwi_unsubscribe (or _and_join), which combines those two steps into a single call.
ast_mwi_publisher
Before publishing to a particular topic a publisher should be created. This can be achieved by using ast_mwi_add_publisher. Publishing to a mailbox should then be done using the ast_mwi_publish function. This ensures the message is published to the appropriate topic, and the last known state is maintained.
Publishing by mailbox id alone is also allowed. However, it is not recommended to do so, and exists mainly for backwards compatibility, and legacy subsystems. If, and when this method of publishing is employed a call to one of the ast_delete_mwi_state functions should also be called for a given mailbox id after no more publishing will be done for that id. Otherwise a memory leak on the underlying stasis_state object will occur.
ast_mwi_observer
Add an observer in order to watch for particular MWI module related events. For instance if a submodule needs to know when a subscription is added to any mailbox an observer can be added to watch for that.
Definition in file mwi.h.
Macro Definition Documentation
ast_delete_mwi_state
#define ast_delete_mwi_state (mailbox, context) ast_delete_mwi_state_full(mailbox, context, NULL)
Delete MWI state cached by stasis.
Since
12.2.0
Parameters
[in] mailbox The mailbox identifier string.
[in] context The context this mailbox resides in (NULL or "" if only using mailbox)
Return values
0 Success
-1 Failure
Definition at line 433 of file mwi.h.
Referenced by mwi_observe_delete(), and publishers_destroy().
ast_publish_mwi_state
#define ast_publish_mwi_state (mailbox, context, new_msgs, old_msgs) ast_publish_mwi_state_full(mailbox, context, new_msgs, old_msgs, NULL, NULL)
Publish a MWI state update via stasis.
Since
12
Parameters
[in] mailbox The mailbox identifier string.
[in] context The context this mailbox resides in (NULL or "" if only using mailbox)
[in] new_msgs The number of new messages in this mailbox
[in] old_msgs The number of old messages in this mailbox
Return values
0 Success
-1 Failure
Definition at line 380 of file mwi.h.
Referenced by handle_request_notify(), mwi_observe_delete(), mwi_post_event(), notify_message(), and pubsub_on_rx_mwi_notify_request().
ast_publish_mwi_state_channel
#define ast_publish_mwi_state_channel (mailbox, context, new_msgs, old_msgs, channel_id) ast_publish_mwi_state_full(mailbox, context, new_msgs, old_msgs, channel_id, NULL)
Publish a MWI state update associated with some channel.
Since
12
Parameters
[in] mailbox The mailbox identifier string.
[in] context The context this mailbox resides in (NULL or "" if only using mailbox)
[in] new_msgs The number of new messages in this mailbox
[in] old_msgs The number of old messages in this mailbox
[in] channel_id A unique identifier for a channel associated with this change in mailbox state
Return values
0 Success
-1 Failure
Definition at line 397 of file mwi.h.
Referenced by queue_mwi_event().
Typedef Documentation
on_mwi_state
typedef int(* on_mwi_state) (struct ast_mwi_state *mwi_state, void *data)
The delegate called for each managed mailbox state.
Parameters
mwi_state The mwi state object
data User data passed in by the initiator
Return values
0 to continue traversing, or CMP_STOP (2) to stop traversing
Since
13.28.0
16.5.0
Definition at line 303 of file mwi.h.
Function Documentation
ast_delete_mwi_state_full()
int ast_delete_mwi_state_full (const char * mailbox, const char * context, struct ast_eid * eid)
Delete MWI state cached by stasis with all parameters.
Since
12.2.0
Parameters
[in] mailbox The mailbox identifier string.
[in] context The context this mailbox resides in (NULL or "" if only using mailbox)
[in] eid The EID of the server that originally published the message
Return values
0 Success
-1 Failure
Definition at line 399 of file mwi.c.
References ao2_cleanup, ast_eid_default, ast_mwi_state_cache(), ast_mwi_state_type(), mwi_state_create_message(), NULL, RAII_VAR, stasis_cache_clear_create(), stasis_cache_get_by_eid(), stasis_message_data(), stasis_state_remove_publish_by_id(), and ast_mwi_state::uniqueid.
Referenced by free_user_final(), and mwi_handle_unsubscribe2().
 {
    RAII_VAR(struct stasis_message *, msg, NULL, ao2_cleanup);
    struct stasis_message *cached_msg;
    struct stasis_message *clear_msg;
    struct ast_mwi_state *mwi_state;
    msg = mwi_state_create_message(mailbox, context, 0, 0, 0, NULL, eid);
    if (!msg) {
       return -1;
    }
    mwi_state = stasis_message_data(msg);
    /*
     * XXX As far as stasis is concerned, all MWI events are local.
     *
     * For now, it is assumed that there is only one entity
     * maintaining the state of a particular mailbox.
     *
     * If we ever have multiple MWI event entities maintaining
     * the same mailbox that wish to delete their cached entry
     * we will need to do something about the race condition
     * potential between checking the cache and removing the
     * cache entry.
     */
    cached_msg = stasis_cache_get_by_eid(ast_mwi_state_cache(),
       ast_mwi_state_type(), mwi_state->uniqueid, &ast_eid_default);
    if (!cached_msg) {
       /* Nothing to clear from the cache, but still need to remove state */
       stasis_state_remove_publish_by_id(mwi_state_manager, mwi_state->uniqueid, eid, NULL);
       return -1;
    }
    ao2_cleanup(cached_msg);
    clear_msg = stasis_cache_clear_create(msg);
    stasis_state_remove_publish_by_id(mwi_state_manager, mwi_state->uniqueid, eid, clear_msg);
    ao2_cleanup(clear_msg);
    return 0;
 }
ast_mwi_add_observer()
int ast_mwi_add_observer (struct ast_mwi_observer * observer)
Add an observer to receive MWI state related events.
Parameters
observer The observer handling events
Return values
0 if successfully registered, -1 otherwise
Since
13.28.0
16.5.0
Definition at line 296 of file mwi.c.
References stasis_state_add_observer().
Referenced by start_poll_thread(), and subscriptions_create().
 {
    return stasis_state_add_observer(mwi_state_manager,
       (struct stasis_state_observer *)observer);
 }
ast_mwi_add_publisher()
struct ast_mwi_publisher* ast_mwi_add_publisher (const char * mailbox)
Add an MWI state publisher to the mailbox.
Adding a publisher to a mailbox will create a stasis topic for the mailbox if one does not already exist. A publisher can be removed by releasing its reference. Doing so releases its underlying reference to the MWI state.
Parameters
mailbox The mailbox id to publish to
Return values
An MWI publisher object
NULl on error
Since
13.28.0
16.5.0
Definition at line 290 of file mwi.c.
References stasis_state_add_publisher().
Referenced by publishers_create().
 {
    return (struct ast_mwi_publisher *)stasis_state_add_publisher(
       mwi_state_manager, mailbox);
 }
ast_mwi_add_subscriber()
struct ast_mwi_subscriber* ast_mwi_add_subscriber (const char * mailbox)
Add an MWI state subscriber to the mailbox.
Adding a subscriber to a mailbox will create a stasis topic for the mailbox if one does not already exist. It does not however subscribe to the topic itself. This is done separately using a call to stasis_subscribe or stasis_subscribe_pool.
A subscriber can be removed by releasing its reference. Doing so releases its underlying reference to the MWI state. It does not unsubscribe from the topic. Unsubscribing from a topic should be done prior to unsubscribing the state.
Parameters
mailbox The subscription state mailbox id
Return values
An MWI subscriber object
NULL on error
Since
13.28.0
16.5.0
Definition at line 224 of file mwi.c.
References stasis_state_add_subscriber().
 {
    return (struct ast_mwi_subscriber *)stasis_state_add_subscriber(
       mwi_state_manager, mailbox);
 }
ast_mwi_publish()
int ast_mwi_publish (struct ast_mwi_publisher * publisher, int urgent_msgs, int new_msgs, int old_msgs, const char * channel_id, struct ast_eid * eid)
Publish MWI for the given mailbox.
Parameters
publisher The publisher to publish a mailbox update on
urgent_msgs The number of urgent messages in this mailbox
new_msgs The number of new messages in this mailbox
old_msgs The number of old messages in this mailbox
channel_id A unique identifier for a channel associated with this change in mailbox state
eid The EID of the server that originally published the message
Return values
0 on success
-1 on failure
Since
13.28.0
16.5.0
Definition at line 353 of file mwi.c.
References ao2_ref, mwi_state_create_message(), NULL, stasis_state_publish(), and stasis_state_publisher_id().
Referenced by explicit_publish_cb().
 {
    struct stasis_state_publisher *p = (struct stasis_state_publisher *)pub;
    struct stasis_message *msg = mwi_state_create_message(stasis_state_publisher_id(p),
       NULL, urgent_msgs, new_msgs, old_msgs, channel_id, eid);
    if (!msg) {
       return -1;
    }
    stasis_state_publish(p, msg);
    ao2_ref(msg, -1);
    return 0;
 }
ast_mwi_publish_by_mailbox()
int ast_mwi_publish_by_mailbox (const char * mailbox, const char * context, int urgent_msgs, int new_msgs, int old_msgs, const char * channel_id, struct ast_eid * eid)
Publish MWI for the given mailbox.
Parameters
mailbox The mailbox identifier string.
context The context this mailbox resides in (NULL or "" if only using mailbox)
urgent_msgs The number of urgent messages in this mailbox
new_msgs The number of new messages in this mailbox
old_msgs The number of old messages in this mailbox
channel_id A unique identifier for a channel associated with this change in mailbox state
eid The EID of the server that originally published the message
Return values
0 on success
-1 on failure
Since
13.28.0
16.5.0
Definition at line 370 of file mwi.c.
References ao2_ref, mwi_state_create_message(), NULL, stasis_message_data(), stasis_state_publish_by_id(), and ast_mwi_state::uniqueid.
Referenced by ast_publish_mwi_state_full(), and implicit_publish_cb().
 {
    struct ast_mwi_state *mwi_state;
    struct stasis_message *msg = mwi_state_create_message(
       mailbox, context, urgent_msgs, new_msgs, old_msgs, channel_id, eid);
    if (!msg) {
       return -1;
    }
    mwi_state = stasis_message_data(msg);
    stasis_state_publish_by_id(mwi_state_manager, mwi_state->uniqueid, NULL, msg);
    ao2_ref(msg, -1);
    return 0;
 }
ast_mwi_remove_observer()
void ast_mwi_remove_observer (struct ast_mwi_observer * observer)
Remove an MWI state observer.
Parameters
observer The observer being removed
Since
13.28.0
16.5.0
Definition at line 302 of file mwi.c.
References stasis_state_remove_observer().
Referenced by stop_poll_thread(), and subscriptions_destroy().
 {
    stasis_state_remove_observer(mwi_state_manager,
       (struct stasis_state_observer *)observer);
 }
ast_mwi_state_callback_all()
void ast_mwi_state_callback_all (on_mwi_state handler, void * data)
For each managed mailbox call the given handler.
Parameters
handler The mwi state handler to call for each managed mailbox
data User to data to pass on to the handler
Since
13.28.0
16.5.0
Definition at line 333 of file mwi.c.
References handle_mwi_state(), handler(), mwi_handler_data::handler, and stasis_state_callback_all().
Referenced by actual_load_config(), manager_voicemail_refresh(), publish(), and unload_module().
 {
    struct mwi_handler_data d = {
       .handler = handler,
       .data = data
    };
    stasis_state_callback_all(mwi_state_manager, handle_mwi_state, &d);
 }
ast_mwi_state_callback_subscribed()
void ast_mwi_state_callback_subscribed (on_mwi_state handler, void * data)
For each managed mailbox that has a subscriber call the given handler.
Parameters
handler The mwi state handler to call for each managed mailbox
data User to data to pass on to the handler
Since
13.28.0
16.5.0
Definition at line 343 of file mwi.c.
References handle_mwi_state(), handler(), mwi_handler_data::handler, and stasis_state_callback_subscribed().
Referenced by mb_poll_thread().
 {
    struct mwi_handler_data d = {
       .handler = handler,
       .data = data
    };
    stasis_state_callback_subscribed(mwi_state_manager, handle_mwi_state, &d);
 }
ast_mwi_subscribe_pool()
struct ast_mwi_subscriber* ast_mwi_subscribe_pool (const char * mailbox, stasis_subscription_cb callback, void * data)
Add an MWI state subscriber, and stasis subscription to the mailbox.
Adding a subscriber to a mailbox will create a stasis topic for the mailbox if one does not already exist. Once successfully create the underlying stasis topic is then subscribed to as well.
A subscriber can be removed by releasing its reference. Doing so releases its underlying reference to the MWI state. It does not unsubscribe from the topic. Unsubscribing from a topic should be done prior to unsubscribing the state.
Parameters
mailbox The subscription state mailbox id
callback The stasis subscription callback
data A user data object passed to the stasis subscription
Return values
An MWI subscriber object
NULL on error
Since
13.28.0
16.5.0
Definition at line 230 of file mwi.c.
References ast_mwi_state_type(), ast_mwi_subscriber_subscription(), NULL, stasis_state_subscribe_pool(), stasis_subscription_accept_message_type(), STASIS_SUBSCRIPTION_FILTER_SELECTIVE, stasis_subscription_set_filter(), and sub.
Referenced by add_peer_mwi_subs(), build_gateway(), build_peer(), config_line(), mkintf(), mwi_stasis_subscription_alloc(), and subscriptions_create().
 {
    struct stasis_subscription *stasis_sub;
    struct ast_mwi_subscriber *sub = (struct ast_mwi_subscriber *)stasis_state_subscribe_pool(
       mwi_state_manager, mailbox, callback, data);
    if (!sub) {
       return NULL;
    }
    stasis_sub = ast_mwi_subscriber_subscription(sub);
    stasis_subscription_accept_message_type(stasis_sub, ast_mwi_state_type());
    stasis_subscription_set_filter(stasis_sub, STASIS_SUBSCRIPTION_FILTER_SELECTIVE);
    return sub;
 }
ast_mwi_subscriber_data()
struct ast_mwi_state* ast_mwi_subscriber_data (struct ast_mwi_subscriber * sub)
Retrieves the state data object associated with the MWI subscriber.
Note
Returned data's reference count is incremented
Parameters
sub An MWI subscriber
Return values
The state data object
Since
13.28.0
16.5.0
Definition at line 264 of file mwi.c.
References mwi_retrieve_then_create_state(), stasis_state_subscriber_data(), and stasis_state_subscriber_id().
Referenced by get_message_count(), handle_validate(), mwi_handle_subscribe(), and mwi_handle_unsubscribe().
 {
    struct stasis_state_subscriber *s = (struct stasis_state_subscriber *)sub;
    struct ast_mwi_state *mwi_state = stasis_state_subscriber_data(s);
    return mwi_state ?: mwi_retrieve_then_create_state(stasis_state_subscriber_id(s));
 }
ast_mwi_subscriber_subscription()
struct stasis_subscription* ast_mwi_subscriber_subscription (struct ast_mwi_subscriber * sub)
Retrieve the stasis MWI topic subscription if available.
Parameters
sub An MWI subscriber
Return values
The subscriber's stasis subscription
NULL if no subscription available
Since
13.28.0
16.5.0
Definition at line 272 of file mwi.c.
References stasis_state_subscriber_subscription().
Referenced by add_peer_mwi_subs(), ast_mwi_subscribe_pool(), and mwi_stasis_subscription_alloc().
 {
    return stasis_state_subscriber_subscription((struct stasis_state_subscriber *)sub);
 }
ast_mwi_subscriber_topic()
struct stasis_topic* ast_mwi_subscriber_topic (struct ast_mwi_subscriber * sub)
Retrieves the MWI subscriber's topic.
Note
Returned topic's reference count is NOT incremented. However, the topic is guaranteed to live for the lifetime of the subscriber.
Parameters
sub An MWI subscriber
Return values
A stasis topic subscribed to by the subscriber
Since
13.28.0
16.5.0
Definition at line 259 of file mwi.c.
References stasis_state_subscriber_topic().
 {
    return stasis_state_subscriber_topic((struct stasis_state_subscriber *)sub);
 }
ast_mwi_unsubscribe()
void* ast_mwi_unsubscribe (struct ast_mwi_subscriber * sub)
Unsubscribe from the stasis topic and MWI.
Parameters
sub An MWI subscriber
Return values
NULL
Since
13.28.0
16.5.0
Definition at line 249 of file mwi.c.
References stasis_state_unsubscribe().
Referenced by destroy_dahdi_pvt(), destroy_endpoint(), peer_destructor(), and skinny_reload().
 {
    return stasis_state_unsubscribe((struct stasis_state_subscriber *)sub);
 }
ast_mwi_unsubscribe_and_join()
void* ast_mwi_unsubscribe_and_join (struct ast_mwi_subscriber * sub)
Unsubscribe from the stasis topic, block until the final message is received, and then unsubscribe from MWI.
Parameters
sub An MWI subscriber
Return values
NULL
Since
13.28.0
16.5.0
Definition at line 254 of file mwi.c.
References stasis_state_unsubscribe_and_join().
Referenced by destroy_mailbox(), subscriptions_destroy(), unload_module(), and unsubscribe_stasis().
 {
    return stasis_state_unsubscribe_and_join((struct stasis_state_subscriber *)sub);
 }
ast_publish_mwi_state_full()
int ast_publish_mwi_state_full (const char * mailbox, const char * context, int new_msgs, int old_msgs, const char * channel_id, struct ast_eid * eid)
Publish a MWI state update via stasis with all parameters.
Since
12
Parameters
[in] mailbox The mailbox identifier string.
[in] context The context this mailbox resides in (NULL or "" if only using mailbox)
[in] new_msgs The number of new messages in this mailbox
[in] old_msgs The number of old messages in this mailbox
[in] channel_id A unique identifier for a channel associated with this change in mailbox state
[in] eid The EID of the server that originally published the message
Return values
0 Success
-1 Failure
Definition at line 388 of file mwi.c.
References ast_mwi_publish_by_mailbox().
Referenced by asterisk_publication_mailboxstate(), publish_mwi_to_stasis(), and xmpp_pubsub_handle_event().
 {
    return ast_mwi_publish_by_mailbox(mailbox, context, 0, new_msgs, old_msgs, channel_id, eid);
 }