Asterisk - The Open Source Telephony Project: general.h File Reference
general.h File Reference
Functions
const char * ast_stir_shaken_ca_file (const struct stir_shaken_general *cfg)
Retrieve the 'ca_file' general configuration option value.
const char * ast_stir_shaken_ca_path (const struct stir_shaken_general *cfg)
Retrieve the 'ca_path' general configuration option value.
unsigned int ast_stir_shaken_cache_max_size (const struct stir_shaken_general *cfg)
Retrieve the 'cache_max_size' general configuration option value.
unsigned int ast_stir_shaken_curl_timeout (const struct stir_shaken_general *cfg)
Retrieve the 'curl_timeout' general configuration option value.
unsigned int ast_stir_shaken_signature_timeout (const struct stir_shaken_general *cfg)
Retrieve the 'signature_timeout' general configuration option value.
struct stir_shaken_general * stir_shaken_general_get (void)
Retrieve the stir/shaken 'general' configuration object.
int stir_shaken_general_load (void)
Load time initialization for the stir/shaken 'general' configuration.
int stir_shaken_general_unload (void)
Unload time cleanup for the stir/shaken 'general' configuration.
Function Documentation
ast_stir_shaken_ca_file()
const char* ast_stir_shaken_ca_file (const struct stir_shaken_general * cfg)
Retrieve the 'ca_file' general configuration option value.
Note
If a NULL configuration is given, then the default value is returned
Parameters
cfg A 'general' configuration object
Return values
The 'ca_file' value
Definition at line 72 of file general.c.
References stir_shaken_general::ca_file, and DEFAULT_CA_FILE.
 {
    return cfg ? cfg->ca_file : DEFAULT_CA_FILE;
 }
ast_stir_shaken_ca_path()
const char* ast_stir_shaken_ca_path (const struct stir_shaken_general * cfg)
Retrieve the 'ca_path' general configuration option value.
Note
If a NULL configuration is given, then the default value is returned
Parameters
cfg A 'general' configuration object
Return values
The 'ca_path' value
Definition at line 77 of file general.c.
References stir_shaken_general::ca_path, and DEFAULT_CA_PATH.
 {
    return cfg ? cfg->ca_path : DEFAULT_CA_PATH;
 }
ast_stir_shaken_cache_max_size()
unsigned int ast_stir_shaken_cache_max_size (const struct stir_shaken_general * cfg)
Retrieve the 'cache_max_size' general configuration option value.
Note
If a NULL configuration is given, then the default value is returned
Parameters
cfg A 'general' configuration object
Return values
The 'cache_max_size' value
Definition at line 82 of file general.c.
References stir_shaken_general::cache_max_size, and DEFAULT_CACHE_MAX_SIZE.
 {
    return cfg ? cfg->cache_max_size : DEFAULT_CACHE_MAX_SIZE;
 }
ast_stir_shaken_curl_timeout()
unsigned int ast_stir_shaken_curl_timeout (const struct stir_shaken_general * cfg)
Retrieve the 'curl_timeout' general configuration option value.
Note
If a NULL configuration is given, then the default value is returned
Parameters
cfg A 'general' configuration object
Return values
The 'curl_timeout' value
Definition at line 87 of file general.c.
References stir_shaken_general::curl_timeout, and DEFAULT_CURL_TIMEOUT.
Referenced by get_curl_instance().
 {
    return cfg ? cfg->curl_timeout : DEFAULT_CURL_TIMEOUT;
 }
ast_stir_shaken_signature_timeout()
unsigned int ast_stir_shaken_signature_timeout (const struct stir_shaken_general * cfg)
Retrieve the 'signature_timeout' general configuration option value.
Note
if a NULL configuration is given, then the default value is returned
Parameters
cfg A 'general' configuration object
Return values
The 'signature_timeout' value
Definition at line 92 of file general.c.
References DEFAULT_SIGNATURE_TIMEOUT, and stir_shaken_general::signature_timeout.
Referenced by ast_stir_shaken_get_signature_timeout().
 {
    return cfg ? cfg->signature_timeout : DEFAULT_SIGNATURE_TIMEOUT;
 }
stir_shaken_general_get()
struct stir_shaken_general* stir_shaken_general_get (void)
Retrieve the stir/shaken 'general' configuration object.
A default configuration object is returned if no configuration was specified. As well, NULL can be returned if there is no configuration, and a problem occurred while loading the defaults.
Note
Object is returned with a reference that the caller is responsible for de-referencing.
Return values
A 'general' configuration object, or NULL
Definition at line 54 of file general.c.
References ao2_bump, ao2_cleanup, ao2_container_count(), ao2_find, ao2_ref, AST_RETRIEVE_FLAG_ALL, AST_RETRIEVE_FLAG_MULTIPLE, ast_sorcery_retrieve_by_fields(), ast_stir_shaken_sorcery(), CONFIG_TYPE, container, and NULL.
Referenced by ast_stir_shaken_get_signature_timeout(), get_curl_instance(), stir_shaken_general_loaded(), and stir_shaken_general_show().
 {
    struct stir_shaken_general *cfg;
    struct ao2_container *container;
    container = ast_sorcery_retrieve_by_fields(ast_stir_shaken_sorcery(), CONFIG_TYPE,
       AST_RETRIEVE_FLAG_MULTIPLE | AST_RETRIEVE_FLAG_ALL, NULL);
    if (!container || ao2_container_count(container) == 0) {
       ao2_cleanup(container);
       return ao2_bump(default_config);
    }
    cfg = ao2_find(container, NULL, 0);
    ao2_ref(container, -1);
    return cfg;
 }
stir_shaken_general_load()
int stir_shaken_general_load (void)
Load time initialization for the stir/shaken 'general' configuration.
Return values
0 on success, -1 on error
Definition at line 248 of file general.c.
References __stringify, ARRAY_LEN, ast_cli_register_multiple, ast_log, ast_sorcery_apply_default, ast_sorcery_instance_observer_add(), ast_sorcery_object_field_register, ast_sorcery_object_field_register_custom, ast_sorcery_object_register, ast_stir_shaken_sorcery(), ca_file_to_str(), ca_path_to_str(), stir_shaken_general::cache_max_size, CONFIG_TYPE, stir_shaken_general::curl_timeout, DEFAULT_CA_FILE, DEFAULT_CA_PATH, DEFAULT_CACHE_MAX_SIZE, DEFAULT_CURL_TIMEOUT, DEFAULT_SIGNATURE_TIMEOUT, FLDSET, LOG_ERROR, NULL, on_load_ca_file(), on_load_ca_path(), OPT_NOOP_T, OPT_UINT_T, stir_shaken_general::signature_timeout, sorcery, stir_shaken_general_alloc(), and stir_shaken_general_apply().
Referenced by load_module().
 {
    struct ast_sorcery *sorcery = ast_stir_shaken_sorcery();
    ast_sorcery_apply_default(sorcery, CONFIG_TYPE, "config",
       "stir_shaken.conf,criteria=type=general,single_object=yes,explicit_name=general");
    if (ast_sorcery_object_register(sorcery, CONFIG_TYPE, stir_shaken_general_alloc,
          NULL, stir_shaken_general_apply)) {
       ast_log(LOG_ERROR, "stir/shaken - failed to register '%s' sorcery object\n", CONFIG_TYPE);
       return -1;
    }
    ast_sorcery_object_field_register(sorcery, CONFIG_TYPE, "type", "", OPT_NOOP_T, 0, 0);
    ast_sorcery_object_field_register_custom(sorcery, CONFIG_TYPE, "ca_file",
       DEFAULT_CA_FILE, on_load_ca_file, ca_file_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register_custom(sorcery, CONFIG_TYPE, "ca_path",
       DEFAULT_CA_PATH, on_load_ca_path, ca_path_to_str, NULL, 0, 0);
    ast_sorcery_object_field_register(sorcery, CONFIG_TYPE, "cache_max_size",
       __stringify(DEFAULT_CACHE_MAX_SIZE), OPT_UINT_T, 0,
       FLDSET(struct stir_shaken_general, cache_max_size));
    ast_sorcery_object_field_register(sorcery, CONFIG_TYPE, "curl_timeout",
       __stringify(DEFAULT_CURL_TIMEOUT), OPT_UINT_T, 0,
       FLDSET(struct stir_shaken_general, curl_timeout));
    ast_sorcery_object_field_register(sorcery, CONFIG_TYPE, "signature_timeout",
       __stringify(DEFAULT_SIGNATURE_TIMEOUT), OPT_UINT_T, 0,
       FLDSET(struct stir_shaken_general, signature_timeout));
    if (ast_sorcery_instance_observer_add(sorcery, &stir_shaken_general_observer)) {
       ast_log(LOG_ERROR, "stir/shaken - failed to register loaded observer for '%s' "
             "sorcery object type\n", CONFIG_TYPE);
       return -1;
    }
    ast_cli_register_multiple(stir_shaken_general_cli,
       ARRAY_LEN(stir_shaken_general_cli));
    return 0;
 }
stir_shaken_general_unload()
int stir_shaken_general_unload (void)
Unload time cleanup for the stir/shaken 'general' configuration.
Return values
0 on success, -1 on error
Definition at line 232 of file general.c.
References ao2_ref, ARRAY_LEN, ast_cli_unregister_multiple(), ast_sorcery_instance_observer_remove(), ast_stir_shaken_sorcery(), and NULL.
Referenced by unload_module().
 {
    ast_cli_unregister_multiple(stir_shaken_general_cli,
       ARRAY_LEN(stir_shaken_general_cli));
    ast_sorcery_instance_observer_remove(ast_stir_shaken_sorcery(),
       &stir_shaken_general_observer);
    if (default_config) {
       ao2_ref(default_config, -1);
       default_config = NULL;
    }
    return 0;
 }