Asterisk - The Open Source Telephony Project: res_pjsip_phoneprov_provider.c File Reference
res_pjsip_phoneprov_provider.c File Reference
PJSIP Phoneprov Configuration Provider.
#include "asterisk.h"
#include <pjsip.h>
#include "asterisk/res_pjsip.h"
#include "asterisk/module.h"
#include "asterisk/sorcery.h"
#include "asterisk/phoneprov.h"
#include "res_pjsip/include/res_pjsip_private.h"
Data Structures
struct phoneprov
Structure for a phoneprov object.
Functions
static void __reg_module (void)
static void __unreg_module (void)
static int aco_handler (const struct aco_option *opt, struct ast_variable *var, void *obj)
Adds a config name/value pair to the phoneprov object.
static int assign_and_insert (const char *name, const char *value, struct varshead *vars)
Helper that creates an ast_var_t and inserts it into the list.
struct ast_module * AST_MODULE_SELF_SYM (void)
static int fields_handler (const void *obj, struct ast_variable **fields)
Converts the phoneprov varlist to an ast_variable list.
static int load_endpoint (const char *id, const char *endpoint_name, struct varshead *vars, char *port_string)
static int load_module (void)
static int load_users (void)
Callback that loads the users from phoneprov sections.
static void * phoneprov_alloc (const char *name)
Allocator for phoneprov.
static void phoneprov_destroy (void *obj)
Destructor function for phoneprov.
static int reload_module (void)
static int unload_module (void)
static void users_apply_handler (struct phoneprov *pp)
Callback that validates the phoneprov object.
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "PJSIP Phoneprov Provider" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_EXTENDED, .load = load_module, .reload = reload_module, .unload = unload_module, .load_pri = AST_MODPRI_APP_DEPEND, .requires = "res_pjsip,res_phoneprov", }
static const struct ast_module_info * ast_module_info = &__mod_info
static struct ast_sorcery * sorcery
Detailed Description
PJSIP Phoneprov Configuration Provider.
Author
George Joseph georg.nosp@m.e.jo.nosp@m.seph@.nosp@m.fair.nosp@m.view5.nosp@m..com
Definition in file res_pjsip_phoneprov_provider.c.
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 420 of file res_pjsip_phoneprov_provider.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 420 of file res_pjsip_phoneprov_provider.c.
aco_handler()
static int aco_handler (const struct aco_option * opt, struct ast_variable * var, void * obj) static
Adds a config name/value pair to the phoneprov object.
Definition at line 187 of file res_pjsip_phoneprov_provider.c.
References assign_and_insert(), ast_variable::name, ast_variable::value, and phoneprov::vars.
Referenced by load_module().
 {
    struct phoneprov *pp = obj;
    return assign_and_insert(var->name, var->value, pp->vars);
 }
assign_and_insert()
static int assign_and_insert (const char * name, const char * value, struct varshead * vars) static
Helper that creates an ast_var_t and inserts it into the list.
Definition at line 163 of file res_pjsip_phoneprov_provider.c.
References ast_log, ast_strlen_zero, ast_var_assign, AST_VAR_LIST_INSERT_TAIL(), LOG_ERROR, and var.
Referenced by aco_handler(), load_endpoint(), and users_apply_handler().
 {
    struct ast_var_t *var;
    if (ast_strlen_zero(name) || !vars) {
       return -1;
    }
    /* Just ignore if the value is NULL or empty */
    if (ast_strlen_zero(value)) {
       return 0;
    }
    var = ast_var_assign(name, value);
    if (!var) {
       ast_log(LOG_ERROR, "Could not allocate variable memory for variable.\n");
       return -1;
    }
    AST_VAR_LIST_INSERT_TAIL(vars, var);
    return 0;
 }
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 420 of file res_pjsip_phoneprov_provider.c.
fields_handler()
static int fields_handler (const void * obj, struct ast_variable ** fields) static
Converts the phoneprov varlist to an ast_variable list.
Definition at line 195 of file res_pjsip_phoneprov_provider.c.
References AST_VAR_LIST_TRAVERSE, ast_variable_new, ast_variables_destroy(), ast_var_t::name, ast_variable::next, NULL, ast_var_t::value, var, and phoneprov::vars.
Referenced by load_module().
 {
    const struct phoneprov *pp = obj;
    struct ast_var_t *pvar;
    struct ast_variable *head = NULL;
    struct ast_variable *tail = NULL;
    struct ast_variable *var;
    AST_VAR_LIST_TRAVERSE(pp->vars, pvar) {
       var = ast_variable_new(pvar->name, pvar->value, "");
       if (!var) {
          ast_variables_destroy(head);
          return -1;
       }
       if (!head) {
          head = var;
          tail = var;
          continue;
       }
       tail->next = var;
       tail = var;
    }
    *fields = head;
    return 0;
 }
load_endpoint()
static int load_endpoint (const char * id, const char * endpoint_name, struct varshead * vars, char * port_string) static
Definition at line 223 of file res_pjsip_phoneprov_provider.c.
References ao2_cleanup, ao2_ref, assign_and_insert(), ast_log, AST_PHONEPROV_STD_CALLERID, AST_PHONEPROV_STD_DISPLAY_NAME, AST_PHONEPROV_STD_SECRET, AST_PHONEPROV_STD_USERNAME, ast_phoneprov_std_variable_lookup(), ast_sorcery_retrieve_by_id(), ast_strlen_zero, AST_VECTOR_GET, AST_VECTOR_SIZE, ast_sip_auth::auth_pass, ast_sip_auth::auth_user, LOG_ERROR, NULL, and RAII_VAR.
Referenced by users_apply_handler().
 {
    struct ast_sip_auth *auth;
    RAII_VAR(struct ast_sip_endpoint *, endpoint, NULL, ao2_cleanup);
    RAII_VAR(struct ast_sip_transport *, transport, NULL, ao2_cleanup);
    const char *auth_name;
    *port_string = '\0';
    /* We need to use res_pjsip's sorcery instance instead of our own to
     * get endpoint and auth.
     */
    endpoint = ast_sorcery_retrieve_by_id(sorcery, "endpoint",
       endpoint_name);
    if (!endpoint) {
       ast_log(LOG_ERROR, "phoneprov %s contained invalid endpoint %s.\n", id,
          endpoint_name);
       return -1;
    }
    assign_and_insert("ENDPOINT_ID", endpoint_name, vars);
    assign_and_insert("TRANSPORT_ID", endpoint->transport, vars);
    if (endpoint->id.self.number.valid && !ast_strlen_zero(endpoint->id.self.number.str)) {
       assign_and_insert(ast_phoneprov_std_variable_lookup(AST_PHONEPROV_STD_CALLERID),
          endpoint->id.self.number.str, vars);
    }
    if (endpoint->id.self.name.valid && !ast_strlen_zero(endpoint->id.self.name.str)) {
       assign_and_insert(
          ast_phoneprov_std_variable_lookup(AST_PHONEPROV_STD_DISPLAY_NAME),
          endpoint->id.self.name.str, vars);
    }
    transport = ast_sorcery_retrieve_by_id(sorcery, "transport",
       endpoint->transport);
    if (!transport) {
       ast_log(LOG_ERROR, "Endpoint %s contained invalid transport %s.\n", endpoint_name,
          endpoint->transport);
       return -1;
    }
    snprintf(port_string, 6, "%d", pj_sockaddr_get_port(&transport->host));
    if (!AST_VECTOR_SIZE(&endpoint->inbound_auths)) {
       return 0;
    }
    auth_name = AST_VECTOR_GET(&endpoint->inbound_auths, 0);
    auth = ast_sorcery_retrieve_by_id(sorcery, "auth", auth_name);
    if (!auth) {
       ast_log(LOG_ERROR, "phoneprov %s contained invalid auth %s.\n", id, auth_name);
       return -1;
    }
    assign_and_insert("AUTH_ID", auth_name, vars);
    assign_and_insert(ast_phoneprov_std_variable_lookup(AST_PHONEPROV_STD_USERNAME),
       auth->auth_user, vars);
    assign_and_insert(ast_phoneprov_std_variable_lookup(AST_PHONEPROV_STD_SECRET),
       auth->auth_pass, vars);
    ao2_ref(auth, -1);
    return 0;
 }
load_module()
static int load_module (void) static
Definition at line 368 of file res_pjsip_phoneprov_provider.c.
References aco_handler(), ast_log, AST_MODULE, AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, ast_phoneprov_provider_register(), ast_sip_get_sorcery(), ast_sorcery_apply_config, ast_sorcery_apply_default, ast_sorcery_load_object(), ast_sorcery_object_field_register, ast_sorcery_object_fields_register(), ast_sorcery_object_register, fields_handler(), load_users(), LOG_ERROR, NULL, OPT_NOOP_T, and phoneprov_alloc().
Referenced by reload_module().
 {
    sorcery = ast_sip_get_sorcery();
    ast_sorcery_apply_config(sorcery, "res_pjsip_phoneprov_provider");
    ast_sorcery_apply_default(sorcery, "phoneprov", "config",
       "pjsip.conf,criteria=type=phoneprov");
    ast_sorcery_object_register(sorcery, "phoneprov", phoneprov_alloc, NULL,
       NULL);
    ast_sorcery_object_field_register(sorcery, "phoneprov", "type", "", OPT_NOOP_T, 0,
       0);
    ast_sorcery_object_fields_register(sorcery, "phoneprov", "^", aco_handler,
       fields_handler);
    ast_sorcery_load_object(sorcery, "phoneprov");
    if (ast_phoneprov_provider_register(AST_MODULE, load_users)) {
       ast_log(LOG_ERROR, "Unable to register pjsip phoneprov provider.\n");
       return AST_MODULE_LOAD_DECLINE;
    }
    return AST_MODULE_LOAD_SUCCESS;
 }
load_users()
static int load_users (void) static
Callback that loads the users from phoneprov sections.
Definition at line 343 of file res_pjsip_phoneprov_provider.c.
References ao2_iterator_destroy(), ao2_iterator_init(), ao2_iterator_next, ao2_ref, AST_RETRIEVE_FLAG_ALL, AST_RETRIEVE_FLAG_MULTIPLE, ast_sorcery_reload_object(), ast_sorcery_retrieve_by_fields(), NULL, users, and users_apply_handler().
Referenced by load_module(), and reload_module().
 {
    struct ao2_container *users;
    struct ao2_iterator i;
    struct phoneprov *pp;
    ast_sorcery_reload_object(sorcery, "phoneprov");
    users = ast_sorcery_retrieve_by_fields(sorcery, "phoneprov",
       AST_RETRIEVE_FLAG_MULTIPLE | AST_RETRIEVE_FLAG_ALL, NULL);
    if (!users) {
       return 0;
    }
    i = ao2_iterator_init(users, 0);
    while ((pp = ao2_iterator_next(&i))) {
       users_apply_handler(pp);
       ao2_ref(pp, -1);
    }
    ao2_iterator_destroy(&i);
    ao2_ref(users, -1);
    return 0;
 }
phoneprov_alloc()
static void* phoneprov_alloc (const char * name) static
Allocator for phoneprov.
Definition at line 148 of file res_pjsip_phoneprov_provider.c.
References ao2_cleanup, ast_log, ast_sorcery_generic_alloc(), ast_var_list_create(), LOG_ERROR, NULL, phoneprov_destroy(), and phoneprov::vars.
Referenced by load_module().
 {
    struct phoneprov *pp = ast_sorcery_generic_alloc(sizeof(*pp), phoneprov_destroy);
    if (!pp || !(pp->vars = ast_var_list_create())) {
       ast_log(LOG_ERROR, "Unable to allocate memory for phoneprov structure %s\n",
          name);
       ao2_cleanup(pp);
       return NULL;
    }
    return pp;
 }
phoneprov_destroy()
static void phoneprov_destroy (void * obj) static
Destructor function for phoneprov.
Definition at line 135 of file res_pjsip_phoneprov_provider.c.
References AST_MODULE, ast_phoneprov_delete_extension(), ast_var_find(), ast_var_list_destroy(), and phoneprov::vars.
Referenced by phoneprov_alloc().
 {
    struct phoneprov *pp = obj;
    char *mac = ast_var_find(pp->vars, "MAC");
    if (mac) {
       ast_phoneprov_delete_extension(AST_MODULE, mac);
    }
    ast_var_list_destroy(pp->vars);
 }
reload_module()
static int reload_module (void) static
Definition at line 401 of file res_pjsip_phoneprov_provider.c.
References ast_log, AST_MODFLAG_LOAD_ORDER, AST_MODPRI_APP_DEPEND, AST_MODULE, AST_MODULE_INFO(), AST_MODULE_LOAD_DECLINE, AST_MODULE_SUPPORT_EXTENDED, ast_phoneprov_provider_register(), ast_phoneprov_provider_unregister(), ASTERISK_GPL_KEY, load_module(), load_users(), LOG_ERROR, reload(), and unload_module().
 {
    ast_phoneprov_provider_unregister(AST_MODULE);
    if (ast_phoneprov_provider_register(AST_MODULE, load_users)) {
       ast_log(LOG_ERROR, "Unable to register pjsip phoneprov provider.\n");
       return AST_MODULE_LOAD_DECLINE;
    }
    return 0;
 }
unload_module()
static int unload_module (void) static
Definition at line 394 of file res_pjsip_phoneprov_provider.c.
References AST_MODULE, and ast_phoneprov_provider_unregister().
Referenced by reload_module().
 {
    ast_phoneprov_provider_unregister(AST_MODULE);
    return 0;
 }
users_apply_handler()
static void users_apply_handler (struct phoneprov * pp) static
Callback that validates the phoneprov object.
Definition at line 289 of file res_pjsip_phoneprov_provider.c.
References assign_and_insert(), ast_log, AST_MODULE, ast_phoneprov_add_extension(), AST_PHONEPROV_STD_LABEL, AST_PHONEPROV_STD_MAC, AST_PHONEPROV_STD_PROFILE, AST_PHONEPROV_STD_SERVER_PORT, AST_PHONEPROV_STD_USERNAME, ast_phoneprov_std_variable_lookup(), ast_sorcery_object_get_id(), ast_var_find(), load_endpoint(), LOG_ERROR, S_OR, and phoneprov::vars.
Referenced by load_users().
 {
    const char *id = ast_sorcery_object_get_id(pp);
    const char *endpoint_name;
    char port_string[6];
    if (!ast_var_find(pp->vars,
       ast_phoneprov_std_variable_lookup(AST_PHONEPROV_STD_MAC))) {
       ast_log(LOG_ERROR, "phoneprov %s must contain a MAC entry.\n", id);
       return;
    }
    if (!ast_var_find(pp->vars,
       ast_phoneprov_std_variable_lookup(AST_PHONEPROV_STD_PROFILE))) {
       ast_log(LOG_ERROR, "phoneprov %s must contain a PROFILE entry.\n", id);
       return;
    }
    endpoint_name = ast_var_find(pp->vars, "endpoint");
    if (endpoint_name) {
       if (load_endpoint(id, endpoint_name, pp->vars, port_string)) {
          return;
       }
    }
    if (!ast_var_find(pp->vars,
       ast_phoneprov_std_variable_lookup(AST_PHONEPROV_STD_USERNAME))) {
       assign_and_insert(
          ast_phoneprov_std_variable_lookup(AST_PHONEPROV_STD_USERNAME), id,
          pp->vars);
    }
    if (!ast_var_find(pp->vars,
       ast_phoneprov_std_variable_lookup(AST_PHONEPROV_STD_LABEL))) {
       assign_and_insert(ast_phoneprov_std_variable_lookup(AST_PHONEPROV_STD_LABEL),
          id, pp->vars);
    }
    if (!ast_var_find(pp->vars,
       ast_phoneprov_std_variable_lookup(AST_PHONEPROV_STD_SERVER_PORT))) {
       assign_and_insert("SERVER_PORT", S_OR(port_string, "5060"), pp->vars);
    }
    if (!ast_var_find(pp->vars,
       ast_phoneprov_std_variable_lookup(AST_PHONEPROV_STD_PROFILE))) {
       ast_log(LOG_ERROR, "phoneprov %s didn't contain a PROFILE entry.\n", id);
    }
    ast_phoneprov_add_extension(AST_MODULE, pp->vars);
    return;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "PJSIP Phoneprov Provider" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .support_level = AST_MODULE_SUPPORT_EXTENDED, .load = load_module, .reload = reload_module, .unload = unload_module, .load_pri = AST_MODPRI_APP_DEPEND, .requires = "res_pjsip,res_phoneprov", } static
Definition at line 420 of file res_pjsip_phoneprov_provider.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 420 of file res_pjsip_phoneprov_provider.c.
sorcery
struct ast_sorcery* sorcery static
Definition at line 126 of file res_pjsip_phoneprov_provider.c.
Referenced by __ast_sorcery_open(), alloc_and_initialize_sorcery(), ast_ari_asterisk_delete_object(), ast_ari_asterisk_get_object(), ast_ari_asterisk_update_object(), ast_sip_destroy_sorcery_global(), ast_sip_initialize_sorcery_auth(), ast_sip_initialize_sorcery_domain_alias(), ast_sip_initialize_sorcery_global(), ast_sip_initialize_sorcery_location(), ast_sip_initialize_sorcery_transport(), ast_sorcery_create(), ast_sorcery_delete(), ast_sorcery_force_reload(), ast_sorcery_force_reload_object(), ast_sorcery_load(), ast_sorcery_load_object(), ast_sorcery_reload(), ast_sorcery_reload_object(), ast_sorcery_retrieve_by_id(), ast_sorcery_update(), AST_TEST_DEFINE(), can_reuse_registration(), load_module(), sorcery_config_retrieve_fields(), sorcery_config_retrieve_multiple(), sorcery_config_retrieve_prefix(), sorcery_config_retrieve_regex(), sorcery_destructor(), sorcery_function_read(), sorcery_wizard_load(), stir_shaken_certificate_load(), stir_shaken_general_load(), stir_shaken_store_load(), test_stir_shaken_cleanup_cert(), and test_stir_shaken_create_cert().