Asterisk - The Open Source Telephony Project: app_bridgewait.c File Reference
app_bridgewait.c File Reference
Dial plan applications
Application to place the channel into a holding Bridge.
#include "asterisk.h"
#include "asterisk/file.h"
#include "asterisk/channel.h"
#include "asterisk/pbx.h"
#include "asterisk/module.h"
#include "asterisk/features.h"
#include "asterisk/say.h"
#include "asterisk/lock.h"
#include "asterisk/utils.h"
#include "asterisk/app.h"
#include "asterisk/bridge.h"
#include "asterisk/musiconhold.h"
#include "asterisk/astobj2.h"
#include "asterisk/causes.h"
Data Structures
struct wait_bridge_wrapper
Macros
#define APP_NAME "BridgeWait"
#define DEFAULT_BRIDGE_NAME "default"
Enumerations
enum bridgewait_args { OPT_ARG_ENTERTAINMENT, OPT_ARG_MOHCLASS, OPT_ARG_TIMEOUT, OPT_ARG_ARRAY_SIZE }
enum bridgewait_flags { MUXFLAG_MOHCLASS = (1 << 0), MUXFLAG_ENTERTAINMENT = (1 << 1), MUXFLAG_TIMEOUT = (1 << 2) }
enum wait_bridge_roles { ROLE_PARTICIPANT = 0, ROLE_ANNOUNCER, ROLE_INVALID }
Functions
static void __reg_module (void)
static void __unreg_module (void)
static int apply_option_entertainment (struct ast_channel *chan, const char *entertainment_arg)
static int apply_option_moh (struct ast_channel *chan, const char *class_arg)
static int apply_option_timeout (struct ast_bridge_features *features, char *duration_arg)
struct ast_module * AST_MODULE_SELF_SYM (void)
static int bridgewait_exec (struct ast_channel *chan, const char *data)
static int bridgewait_timeout_callback (struct ast_bridge_channel *bridge_channel, void *hook_pvt)
static struct wait_bridge_wrapper * get_wait_bridge_wrapper (const char *bridge_name)
static int load_module (void)
static int process_options (struct ast_channel *chan, struct ast_flags *flags, char **opts, struct ast_bridge_features *features, enum wait_bridge_roles role)
static int unload_module (void)
static enum wait_bridge_roles validate_role (const char *role)
static int wait_bridge_hash_fn (const void *obj, const int flags)
static int wait_bridge_sort_fn (const void *obj_left, const void *obj_right, const int flags)
static struct wait_bridge_wrapper * wait_bridge_wrapper_alloc (const char *bridge_name, struct ast_bridge *bridge)
static void wait_bridge_wrapper_destructor (void *obj)
static struct wait_bridge_wrapper * wait_bridge_wrapper_find_by_name (const char *bridge_name)
static void wait_wrapper_removal (struct wait_bridge_wrapper *wrapper)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Place the channel into a holding bridge application" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, }
static const struct ast_module_info * ast_module_info = &__mod_info
static const struct ast_app_option bridgewait_opts [128] = { [ 'e' ] = { .flag = MUXFLAG_ENTERTAINMENT , .arg_index = OPT_ARG_ENTERTAINMENT + 1 }, [ 'm' ] = { .flag = MUXFLAG_MOHCLASS , .arg_index = OPT_ARG_MOHCLASS + 1 }, [ 'S' ] = { .flag = MUXFLAG_TIMEOUT , .arg_index = OPT_ARG_TIMEOUT + 1 }, }
static struct ao2_container * wait_bridge_wrappers
Detailed Description
Application to place the channel into a holding Bridge.
Author
Jonathan Rose jrose.nosp@m.@dig.nosp@m.ium.c.nosp@m.om
Definition in file app_bridgewait.c.
Macro Definition Documentation
APP_NAME
#define APP_NAME "BridgeWait"
Definition at line 116 of file app_bridgewait.c.
Referenced by get_wait_bridge_wrapper(), load_module(), and unload_module().
DEFAULT_BRIDGE_NAME
#define DEFAULT_BRIDGE_NAME "default"
Definition at line 117 of file app_bridgewait.c.
Referenced by bridgewait_exec().
Enumeration Type Documentation
bridgewait_args
enum bridgewait_args
Enumerator
OPT_ARG_ENTERTAINMENT
OPT_ARG_MOHCLASS
OPT_ARG_TIMEOUT
OPT_ARG_ARRAY_SIZE
Definition at line 191 of file app_bridgewait.c.
                      {
    OPT_ARG_ENTERTAINMENT,
    OPT_ARG_MOHCLASS,
    OPT_ARG_TIMEOUT,
    OPT_ARG_ARRAY_SIZE, /* Always the last element of the enum */
 };
bridgewait_flags
enum bridgewait_flags
Enumerator
MUXFLAG_MOHCLASS
MUXFLAG_ENTERTAINMENT
MUXFLAG_TIMEOUT
Definition at line 185 of file app_bridgewait.c.
                       {
    MUXFLAG_MOHCLASS = (1 << 0),
    MUXFLAG_ENTERTAINMENT = (1 << 1),
    MUXFLAG_TIMEOUT = (1 << 2),
 };
wait_bridge_roles
enum wait_bridge_roles
Enumerator
ROLE_PARTICIPANT
ROLE_ANNOUNCER
ROLE_INVALID
Definition at line 262 of file app_bridgewait.c.
{
    ROLE_PARTICIPANT = 0,
    ROLE_ANNOUNCER,
    ROLE_INVALID,
 };
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 512 of file app_bridgewait.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 512 of file app_bridgewait.c.
apply_option_entertainment()
static int apply_option_entertainment (struct ast_channel * chan, const char * entertainment_arg) static
Definition at line 241 of file app_bridgewait.c.
References ast_channel_set_bridge_role_option(), ast_log, and LOG_ERROR.
Referenced by process_options().
 {
    char entertainment = entertainment_arg[0];
    switch (entertainment) {
    case 'm':
       return ast_channel_set_bridge_role_option(chan, "holding_participant", "idle_mode", "musiconhold");
    case 'r':
       return ast_channel_set_bridge_role_option(chan, "holding_participant", "idle_mode", "ringing");
    case 's':
       return ast_channel_set_bridge_role_option(chan, "holding_participant", "idle_mode", "silence");
    case 'h':
       return ast_channel_set_bridge_role_option(chan, "holding_participant", "idle_mode", "hold");
    case 'n':
       return ast_channel_set_bridge_role_option(chan, "holding_participant", "idle_mode", "none");
    default:
       ast_log(LOG_ERROR, "Invalid argument for BridgeWait entertainment '%s'\n", entertainment_arg);
       return -1;
    }
 }
apply_option_moh()
static int apply_option_moh (struct ast_channel * chan, const char * class_arg) static
Definition at line 236 of file app_bridgewait.c.
References ast_channel_set_bridge_role_option().
Referenced by process_options().
 {
    return ast_channel_set_bridge_role_option(chan, "holding_participant", "moh_class", class_arg);
 }
apply_option_timeout()
static int apply_option_timeout (struct ast_bridge_features * features, char * duration_arg) static
Definition at line 212 of file app_bridgewait.c.
References AST_BRIDGE_HOOK_REMOVE_ON_PULL, ast_bridge_interval_hook(), ast_log, ast_strlen_zero, bridgewait_timeout_callback(), LOG_ERROR, and NULL.
Referenced by process_options().
 {
    unsigned int duration;
    if (ast_strlen_zero(duration_arg)) {
       ast_log(LOG_ERROR, "Timeout option 'S': No value provided.\n");
       return -1;
    }
    if (sscanf(duration_arg, "%u", &duration) != 1 || duration == 0) {
       ast_log(LOG_ERROR, "Timeout option 'S': Invalid value provided '%s'.\n",
          duration_arg);
       return -1;
    }
    duration *= 1000;
    if (ast_bridge_interval_hook(features, 0, duration, bridgewait_timeout_callback,
       NULL, NULL, AST_BRIDGE_HOOK_REMOVE_ON_PULL)) {
       ast_log(LOG_ERROR, "Timeout option 'S': Could not create timer.\n");
       return -1;
    }
    return 0;
 }
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 512 of file app_bridgewait.c.
bridgewait_exec()
static int bridgewait_exec (struct ast_channel * chan, const char * data) static
Definition at line 416 of file app_bridgewait.c.
References args, ast_answer(), AST_APP_ARG, ast_app_parse_options(), ast_bridge_features_cleanup(), ast_bridge_features_init(), ast_bridge_join(), ast_channel_name(), ast_check_hangup_locked(), AST_DECLARE_APP_ARGS, ast_log, AST_STANDARD_APP_ARGS, AST_STATE_UP, ast_strdupa, ast_strlen_zero, ast_verb, wait_bridge_wrapper::bridge, bridgewait_opts, DEFAULT_BRIDGE_NAME, get_wait_bridge_wrapper(), LOG_ERROR, LOG_WARNING, wait_bridge_wrapper::name, NULL, OPT_ARG_ARRAY_SIZE, options, parse(), process_options(), ROLE_INVALID, ROLE_PARTICIPANT, ast_bridge::uniqueid, validate_role(), and wait_wrapper_removal().
Referenced by load_module().
 {
    char *bridge_name = DEFAULT_BRIDGE_NAME;
    struct ast_bridge_features chan_features;
    struct ast_flags flags = { 0 };
    char *parse;
    enum wait_bridge_roles role = ROLE_PARTICIPANT;
    char *opts[OPT_ARG_ARRAY_SIZE] = { NULL, };
    struct wait_bridge_wrapper *bridge_wrapper;
    int res;
    AST_DECLARE_APP_ARGS(args,
       AST_APP_ARG(name);
       AST_APP_ARG(role);
       AST_APP_ARG(options);
       AST_APP_ARG(other);     /* Any remaining unused arguments */
    );
    parse = ast_strdupa(data);
    AST_STANDARD_APP_ARGS(args, parse);
    if (!ast_strlen_zero(args.name)) {
       bridge_name = args.name;
    }
    if (!ast_strlen_zero(args.role)) {
       role = validate_role(args.role);
       if (role == ROLE_INVALID) {
          ast_log(LOG_ERROR, "Requested waiting bridge role '%s' is invalid.\n", args.role);
          return -1;
       }
    }
    if (ast_bridge_features_init(&chan_features)) {
       ast_bridge_features_cleanup(&chan_features);
       ast_log(LOG_ERROR, "'%s' failed to enter the waiting bridge - could not set up channel features\n",
          ast_channel_name(chan));
       return -1;
    }
    if (args.options) {
       ast_app_parse_options(bridgewait_opts, &flags, opts, args.options);
    }
    /* Answer the channel if needed */
    if (ast_channel_state(chan) != AST_STATE_UP) {
       ast_answer(chan);
    }
    if (process_options(chan, &flags, opts, &chan_features, role)) {
       ast_bridge_features_cleanup(&chan_features);
       return -1;
    }
    bridge_wrapper = get_wait_bridge_wrapper(bridge_name);
    if (!bridge_wrapper) {
       ast_log(LOG_WARNING, "Failed to find or create waiting bridge '%s' for '%s'.\n", bridge_name, ast_channel_name(chan));
       ast_bridge_features_cleanup(&chan_features);
       return -1;
    }
    ast_verb(3, "%s is entering waiting bridge %s:%s\n", ast_channel_name(chan), bridge_name, bridge_wrapper->bridge->uniqueid);
    res = ast_bridge_join(bridge_wrapper->bridge, chan, NULL, &chan_features, NULL, 0);
    wait_wrapper_removal(bridge_wrapper);
    ast_bridge_features_cleanup(&chan_features);
    if (res) {
       /* For the lifetime of the bridge wrapper the bridge itself will be valid, if an error occurs it is because
        * of extreme situations.
        */
       ast_log(LOG_WARNING, "Failed to join waiting bridge '%s' for '%s'.\n", bridge_name, ast_channel_name(chan));
    }
    return (res || ast_check_hangup_locked(chan)) ? -1 : 0;
 }
bridgewait_timeout_callback()
static int bridgewait_timeout_callback (struct ast_bridge_channel * bridge_channel, void * hook_pvt) static
Definition at line 204 of file app_bridgewait.c.
References ast_bridge_channel_leave_bridge(), AST_CAUSE_NORMAL_CLEARING, ast_channel_name(), ast_verb, BRIDGE_CHANNEL_STATE_END, and ast_bridge_channel::chan.
Referenced by apply_option_timeout().
 {
    ast_verb(3, "Channel %s timed out.\n", ast_channel_name(bridge_channel->chan));
    ast_bridge_channel_leave_bridge(bridge_channel, BRIDGE_CHANNEL_STATE_END,
       AST_CAUSE_NORMAL_CLEARING);
    return -1;
 }
get_wait_bridge_wrapper()
static struct wait_bridge_wrapper* get_wait_bridge_wrapper (const char * bridge_name) static
Definition at line 341 of file app_bridgewait.c.
References APP_NAME, ast_bridge_base_new(), AST_BRIDGE_CAPABILITY_HOLDING, AST_BRIDGE_FLAG_MERGE_INHIBIT_FROM, AST_BRIDGE_FLAG_MERGE_INHIBIT_TO, AST_BRIDGE_FLAG_SWAP_INHIBIT_FROM, AST_BRIDGE_FLAG_SWAP_INHIBIT_TO, AST_BRIDGE_FLAG_TRANSFER_PROHIBITED, wait_bridge_wrapper::bridge, lock, NULL, SCOPED_AO2LOCK, wait_bridge_wrapper_alloc(), and wait_bridge_wrapper_find_by_name().
Referenced by bridgewait_exec().
 {
    struct wait_bridge_wrapper * wrapper;
    struct ast_bridge *bridge = NULL;
    SCOPED_AO2LOCK(lock, wait_bridge_wrappers);
    if ((wrapper = wait_bridge_wrapper_find_by_name(bridge_name))) {
       return wrapper;
    }
    /*
     * Holding bridges can allow local channel move/swap
     * optimization to the bridge.  However, we cannot allow it for
     * this holding bridge because the call will lose the channel
     * roles and dialplan location as a result.
     */
    bridge = ast_bridge_base_new(AST_BRIDGE_CAPABILITY_HOLDING,
       AST_BRIDGE_FLAG_MERGE_INHIBIT_TO | AST_BRIDGE_FLAG_MERGE_INHIBIT_FROM
       | AST_BRIDGE_FLAG_SWAP_INHIBIT_TO | AST_BRIDGE_FLAG_SWAP_INHIBIT_FROM
       | AST_BRIDGE_FLAG_TRANSFER_PROHIBITED, APP_NAME, bridge_name, NULL);
    if (!bridge) {
       return NULL;
    }
    /* The bridge reference is unconditionally passed. */
    return wait_bridge_wrapper_alloc(bridge_name, bridge);
 }
load_module()
static int load_module (void) static
Definition at line 499 of file app_bridgewait.c.
References AO2_ALLOC_OPT_LOCK_MUTEX, ao2_container_alloc_hash, AO2_CONTAINER_ALLOC_OPT_DUPS_REJECT, APP_NAME, ast_register_application_xml, bridgewait_exec(), NULL, wait_bridge_hash_fn(), and wait_bridge_sort_fn().
 {
    wait_bridge_wrappers = ao2_container_alloc_hash(
       AO2_ALLOC_OPT_LOCK_MUTEX, AO2_CONTAINER_ALLOC_OPT_DUPS_REJECT,
       37, wait_bridge_hash_fn, wait_bridge_sort_fn, NULL);
    if (!wait_bridge_wrappers) {
       return -1;
    }
    return ast_register_application_xml(APP_NAME, bridgewait_exec);
 }
process_options()
static int process_options (struct ast_channel * chan, struct ast_flags * flags, char ** opts, struct ast_bridge_features * features, enum wait_bridge_roles role) static
Definition at line 268 of file app_bridgewait.c.
References apply_option_entertainment(), apply_option_moh(), apply_option_timeout(), ast_assert, ast_channel_add_bridge_role(), ast_test_flag, MUXFLAG_ENTERTAINMENT, MUXFLAG_MOHCLASS, MUXFLAG_TIMEOUT, OPT_ARG_ENTERTAINMENT, OPT_ARG_MOHCLASS, OPT_ARG_TIMEOUT, ROLE_ANNOUNCER, ROLE_INVALID, and ROLE_PARTICIPANT.
Referenced by bridgewait_exec().
 {
    if (ast_test_flag(flags, MUXFLAG_TIMEOUT)) {
       if (apply_option_timeout(features, opts[OPT_ARG_TIMEOUT])) {
          return -1;
       }
    }
    switch (role) {
    case ROLE_PARTICIPANT:
       if (ast_channel_add_bridge_role(chan, "holding_participant")) {
          return -1;
       }
       if (ast_test_flag(flags, MUXFLAG_MOHCLASS)) {
          if (apply_option_moh(chan, opts[OPT_ARG_MOHCLASS])) {
             return -1;
          }
       }
       if (ast_test_flag(flags, MUXFLAG_ENTERTAINMENT)) {
          if (apply_option_entertainment(chan, opts[OPT_ARG_ENTERTAINMENT])) {
             return -1;
          }
       }
       break;
    case ROLE_ANNOUNCER:
       if (ast_channel_add_bridge_role(chan, "announcer")) {
          return -1;
       }
       break;
    case ROLE_INVALID:
       ast_assert(0);
       return -1;
    }
    return 0;
 }
unload_module()
static int unload_module (void) static
Definition at line 492 of file app_bridgewait.c.
References ao2_cleanup, APP_NAME, and ast_unregister_application().
 {
    ao2_cleanup(wait_bridge_wrappers);
    return ast_unregister_application(APP_NAME);
 }
validate_role()
static enum wait_bridge_roles validate_role (const char * role) static
Definition at line 405 of file app_bridgewait.c.
References ROLE_ANNOUNCER, ROLE_INVALID, and ROLE_PARTICIPANT.
Referenced by bridgewait_exec().
 {
    if (!strcmp(role, "participant")) {
       return ROLE_PARTICIPANT;
    } else if (!strcmp(role, "announcer")) {
       return ROLE_ANNOUNCER;
    } else {
       return ROLE_INVALID;
    }
 }
wait_bridge_hash_fn()
static int wait_bridge_hash_fn (const void * obj, const int flags) static
Definition at line 140 of file app_bridgewait.c.
References ast_assert, ast_str_hash(), wait_bridge_wrapper::name, OBJ_KEY, OBJ_PARTIAL_KEY, and OBJ_POINTER.
Referenced by load_module().
 {
    const struct wait_bridge_wrapper *entry;
    const char *key;
    switch (flags & (OBJ_POINTER | OBJ_KEY | OBJ_PARTIAL_KEY)) {
    case OBJ_KEY:
       key = obj;
       return ast_str_hash(key);
    case OBJ_POINTER:
       entry = obj;
       return ast_str_hash(entry->name);
    default:
       /* Hash can only work on something with a full key. */
       ast_assert(0);
       return 0;
    }
 }
wait_bridge_sort_fn()
static int wait_bridge_sort_fn (const void * obj_left, const void * obj_right, const int flags) static
Definition at line 159 of file app_bridgewait.c.
References ast_assert, wait_bridge_wrapper::name, OBJ_KEY, OBJ_PARTIAL_KEY, and OBJ_POINTER.
Referenced by load_module().
 {
    const struct wait_bridge_wrapper *left = obj_left;
    const struct wait_bridge_wrapper *right = obj_right;
    const char *right_key = obj_right;
    int cmp;
    switch (flags & (OBJ_POINTER | OBJ_KEY | OBJ_PARTIAL_KEY)) {
    case OBJ_POINTER:
       right_key = right->name;
       /* Fall through */
    case OBJ_KEY:
       cmp = strcmp(left->name, right_key);
       break;
    case OBJ_PARTIAL_KEY:
       cmp = strncmp(left->name, right_key, strlen(right_key));
       break;
    default:
       /* Sort can only work on something with a full or partial key. */
       ast_assert(0);
       cmp = 0;
       break;
    }
    return cmp;
 }
wait_bridge_wrapper_alloc()
static struct wait_bridge_wrapper* wait_bridge_wrapper_alloc (const char * bridge_name, struct ast_bridge * bridge) static
Definition at line 319 of file app_bridgewait.c.
References AO2_ALLOC_OPT_LOCK_NOLOCK, ao2_alloc_options, ao2_cleanup, ao2_link, ast_bridge_destroy(), wait_bridge_wrapper::bridge, wait_bridge_wrapper::name, NULL, and wait_bridge_wrapper_destructor().
Referenced by get_wait_bridge_wrapper().
 {
    struct wait_bridge_wrapper *bridge_wrapper;
    bridge_wrapper = ao2_alloc_options(sizeof(*bridge_wrapper) + strlen(bridge_name) + 1,
       wait_bridge_wrapper_destructor, AO2_ALLOC_OPT_LOCK_NOLOCK);
    if (!bridge_wrapper) {
       ast_bridge_destroy(bridge, 0);
       return NULL;
    }
    strcpy(bridge_wrapper->name, bridge_name);
    bridge_wrapper->bridge = bridge;
    if (!ao2_link(wait_bridge_wrappers, bridge_wrapper)) {
       ao2_cleanup(bridge_wrapper);
       return NULL;
    }
    return bridge_wrapper;
 }
wait_bridge_wrapper_destructor()
static void wait_bridge_wrapper_destructor (void * obj) static
Definition at line 126 of file app_bridgewait.c.
References ast_bridge_destroy(), and wait_bridge_wrapper::bridge.
Referenced by wait_bridge_wrapper_alloc().
 {
    struct wait_bridge_wrapper *wrapper = obj;
    if (wrapper->bridge) {
       ast_bridge_destroy(wrapper->bridge, 0);
    }
 }
wait_bridge_wrapper_find_by_name()
static struct wait_bridge_wrapper* wait_bridge_wrapper_find_by_name (const char * bridge_name) static
Definition at line 135 of file app_bridgewait.c.
References ao2_find, and OBJ_KEY.
Referenced by get_wait_bridge_wrapper().
 {
    return ao2_find(wait_bridge_wrappers, bridge_name, OBJ_KEY);
 }
wait_wrapper_removal()
static void wait_wrapper_removal (struct wait_bridge_wrapper * wrapper) static
Definition at line 378 of file app_bridgewait.c.
References ao2_cleanup, ao2_lock, ao2_ref, ao2_unlink, and ao2_unlock.
Referenced by bridgewait_exec().
 {
    if (!wrapper) {
       return;
    }
    ao2_lock(wait_bridge_wrappers);
    if (ao2_ref(wrapper, 0) == 2) {
       /* Either we have the only real reference or else wrapper isn't in the container anyway. */
       ao2_unlink(wait_bridge_wrappers, wrapper);
    }
    ao2_unlock(wait_bridge_wrappers);
    ao2_cleanup(wrapper);
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Place the channel into a holding bridge application" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "30ef0c93b36035ec78c9cfd712d36d9b" , .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, } static
Definition at line 512 of file app_bridgewait.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 512 of file app_bridgewait.c.
bridgewait_opts
const struct ast_app_option bridgewait_opts[128] = { [ 'e' ] = { .flag = MUXFLAG_ENTERTAINMENT , .arg_index = OPT_ARG_ENTERTAINMENT + 1 }, [ 'm' ] = { .flag = MUXFLAG_MOHCLASS , .arg_index = OPT_ARG_MOHCLASS + 1 }, [ 'S' ] = { .flag = MUXFLAG_TIMEOUT , .arg_index = OPT_ARG_TIMEOUT + 1 }, } static
Definition at line 202 of file app_bridgewait.c.
Referenced by bridgewait_exec().
wait_bridge_wrappers
struct ao2_container* wait_bridge_wrappers static
Definition at line 119 of file app_bridgewait.c.