Asterisk - The Open Source Telephony Project: reqresp_parser.h File Reference
reqresp_parser.h File Reference
sip request response parser header file
Data Structures
struct contact
struct uriparams
uri parameters
Functions
AST_LIST_HEAD_NOLOCK (contactliststruct, contact)
void free_via (struct sip_via *v)
const char * get_calleridname (const char *input, char *output, size_t outputsize)
Get caller id name from SIP headers, copy into output buffer.
int get_comma (char *parse, char **out)
Parse all contact header contacts.
char * get_in_brackets (char *tmp)
Pick out text in brackets from character string.
int get_in_brackets_const (const char *src, const char **start, int *length)
Get text in brackets on a const without copy.
int get_in_brackets_full (char *tmp, char **out, char **residue)
Get text in brackets and any trailing residue.
int get_name_and_number (const char *hdr, char **name, char **number)
Get name and number from sip header.
int parse_contact_header (char *contactheader, struct contactliststruct *contactlist)
int parse_name_andor_addr (char *uri, const char *scheme, char **name, char **user, char **pass, char **domain, struct uriparams *params, char **headers, char **remander)
Parse the ABNF structure name-andor-addr = name-addr / addr-spec into its components and return any trailing message-header parameters.
unsigned int parse_sip_options (const char *options, char *unsupported, size_t unsupported_len)
Parse supported header in incoming packet.
int parse_uri (char *uri, const char *scheme, char **ret_name, char **pass, char **hostport, char **transport)
parses a URI in its components.
int parse_uri_full (char *uri, const char *scheme, char **user, char **pass, char **hostport, struct uriparams *params, char **headers, char **residue)
parses a URI in to all of its components and any trailing residue
struct sip_via * parse_via (const char *header)
Parse a Via header.
void sip_reqresp_parser_exit (void)
Free resources used by request and response parser.
int sip_reqresp_parser_init (void)
initialize request and response parser data
void sip_request_parser_register_tests (void)
register request parsing tests
void sip_request_parser_unregister_tests (void)
unregister request parsing tests
int sip_uri_cmp (const char *input1, const char *input2)
Compare two URIs as described in RFC 3261 Section 19.1.4.
Detailed Description
sip request response parser header file
Definition in file reqresp_parser.h.
Function Documentation
AST_LIST_HEAD_NOLOCK()
AST_LIST_HEAD_NOLOCK (contactliststruct , contact)
Referenced by __ast_answer(), __ast_queue_frame(), announce_thread(), AST_TEST_DEFINE(), channel_do_masquerade(), handle_cli_test_locales(), hook_event_cb(), and safe_sleep_conditional().
free_via()
void free_via (struct sip_via * v)
Definition at line 2379 of file reqresp_parser.c.
References ast_free, and sip_via::via.
Referenced by __find_call(), __sip_alloc(), AST_TEST_DEFINE(), parse_via(), and process_via().
 {
    if (!v) {
       return;
    }
    ast_free(v->via);
    ast_free(v);
 }
get_calleridname()
const char* get_calleridname (const char * input, char * output, size_t outputsize)
Get caller id name from SIP headers, copy into output buffer.
Return values
input string pointer placed after display-name field if possible
Definition at line 695 of file reqresp_parser.c.
References ast_log, ast_skip_blanks(), input(), and LOG_WARNING.
Referenced by AST_TEST_DEFINE(), check_user_full(), get_name_and_number(), parse_name_andor_addr(), and receive_message().
 {
    /* From RFC3261:
     *
     * From           =  ( "From" / "f" ) HCOLON from-spec
     * from-spec      =  ( name-addr / addr-spec ) *( SEMI from-param )
     * name-addr      =  [ display-name ] LAQUOT addr-spec RAQUOT
     * display-name   =  *(token LWS)/ quoted-string
     * token          =  1*(alphanum / "-" / "." / "!" / "%" / "*"
     *                     / "_" / "+" / "`" / "'" / "~" )
     * quoted-string  =  SWS DQUOTE *(qdtext / quoted-pair ) DQUOTE
     * qdtext         =  LWS / %x21 / %x23-5B / %x5D-7E
     *                     / UTF8-NONASCII
     * quoted-pair    =  "\" (%x00-09 / %x0B-0C / %x0E-7F)
     *
     * HCOLON         = *WSP ":" SWS
     * SWS            = [LWS]
     * LWS            = *[*WSP CRLF] 1*WSP
     * WSP            = (SP / HTAB)
     *
     * Deviations from it:
     * - following CRLF's in LWS is not done (here at least)
     * - ascii NUL is never legal as it terminates the C-string
     * - utf8-nonascii is not checked for validity
     */
    char *orig_output = output;
    const char *orig_input = input;
    if (!output || !outputsize) {
       /* Bad output parameters.  Should never happen. */
       return input;
    }
    /* clear any empty characters in the beginning */
    input = ast_skip_blanks(input);
    /* make sure the output buffer is initilized */
    *orig_output = '\0';
    /* make room for '\0' at the end of the output buffer */
    --outputsize;
    /* no data at all or no display name? */
    if (!input || *input == '<') {
       return input;
    }
    /* quoted-string rules */
    if (input[0] == '"') {
       input++; /* skip the first " */
       for (; *input; ++input) {
          if (*input == '"') {  /* end of quoted-string */
             break;
          } else if (*input == 0x5c) { /* quoted-pair = "\" (%x00-09 / %x0B-0C / %x0E-7F) */
             ++input;
             if (!*input) {
                break;
             }
             if ((unsigned char) *input > 0x7f || *input == 0xa || *input == 0xd) {
                continue;  /* not a valid quoted-pair, so skip it */
             }
          } else if ((*input != 0x9 && (unsigned char) *input < 0x20)
             || *input == 0x7f) {
             continue; /* skip this invalid character. */
          }
          if (0 < outputsize) {
             /* We still have room for the output display-name. */
             *output++ = *input;
             --outputsize;
          }
       }
       /* if this is successful, input should be at the ending quote */
       if (*input != '"') {
          ast_log(LOG_WARNING, "No ending quote for display-name was found\n");
          *orig_output = '\0';
          return orig_input;
       }
       /* make sure input is past the last quote */
       ++input;
       /* terminate output */
       *output = '\0';
    } else {  /* either an addr-spec or tokenLWS-combo */
       for (; *input; ++input) {
          /* token or WSP (without LWS) */
          if ((*input >= '0' && *input <= '9') || (*input >= 'A' && *input <= 'Z')
             || (*input >= 'a' && *input <= 'z') || *input == '-' || *input == '.'
             || *input == '!' || *input == '%' || *input == '*' || *input == '_'
             || *input == '+' || *input == '`' || *input == '\'' || *input == '~'
             || *input == 0x9 || *input == ' ') {
             if (0 < outputsize) {
                /* We still have room for the output display-name. */
                *output++ = *input;
                --outputsize;
             }
          } else if (*input == '<') {   /* end of tokenLWS-combo */
             /* we could assert that the previous char is LWS, but we don't care */
             break;
          } else if (*input == ':') {
             /* This invalid character which indicates this is addr-spec rather than display-name. */
             *orig_output = '\0';
             return orig_input;
          } else {         /* else, invalid character we can skip. */
             continue;    /* skip this character */
          }
       }
       if (*input != '<') {   /* if we never found the start of addr-spec then this is invalid */
          *orig_output = '\0';
          return orig_input;
       }
       /* terminate output while trimming any trailing whitespace */
       do {
          *output-- = '\0';
       } while (orig_output <= output && (*output == 0x9 || *output == ' '));
    }
    return input;
 }
get_comma()
int get_comma (char * parse, char ** out)
Parse all contact header contacts.
Return values
0 success
-1 failure
1 all contacts (star)
Definition at line 1438 of file reqresp_parser.c.
References ast_log, c, find_closing_quote(), in, LOG_WARNING, NULL, and parse().
Referenced by parse_contact_header().
 {
    char *c;
    char *parse = in;
    if (out) {
       *out = in;
    }
    /* Skip any quoted text */
    while (*parse) {
       if ((c = strchr(parse, '"'))) {
          in = (char *)find_closing_quote((const char *)c + 1, NULL);
          if (!*in) {
             ast_log(LOG_WARNING, "No closing quote found in '%s'\n", c);
             return -1;
          } else {
             break;
          }
       } else {
          break;
       }
       parse++;
    }
    parse = in;
    /* Skip any userinfo components of a uri as they may contain commas */
    if ((c = strchr(parse,'@'))) {
       parse = c+1;
    }
    if ((out) && (c = strchr(parse,','))) {
       *c++ = '\0';
       *out = c;
       return 0;
    }
    return 1;
 }
get_in_brackets()
char* get_in_brackets (char * tmp)
Pick out text in brackets from character string.
Returns
pointer to terminated stripped string
Parameters
tmp input string that will be modified
Examples:
* "foo" <bar>  valid input, returns bar
*  foo returns the whole string
* < "foo ... > returns the string between brackets
* < "foo...    bogus (missing closing bracket), returns the whole string
*
Definition at line 1173 of file reqresp_parser.c.
References get_in_brackets_full(), NULL, out, and tmp().
Referenced by AST_TEST_DEFINE(), check_user_full(), extract_uri(), get_also_info(), get_destination(), get_domain(), get_name_and_number(), get_pai(), get_rdnis(), get_refer_info(), handle_cc_notify(), parse_moved_contact(), parse_ok_contact(), parse_register_contact(), receive_message(), register_verify(), reqprep(), sip_get_cc_information(), sip_msg_send(), transmit_refer(), transmit_state_notify(), uac_sips_contact(), and uas_sips_contact().
 {
    char *out;
    if ((get_in_brackets_full(tmp, &out, NULL))) {
       return tmp;
    }
    return out;
 }
get_in_brackets_const()
int get_in_brackets_const (const char * src, const char ** start, int * length)
Get text in brackets on a const without copy.
Parameters
src String to search
[out] start Set to first character inside left bracket.
[out] length Set to lenght of string inside brackets
Return values
0 success
-1 failure
1 no brackets so got all
Definition at line 1052 of file reqresp_parser.c.
References ast_log, ast_strlen_zero, find_closing_quote(), LOG_WARNING, NULL, and parse().
Referenced by build_route(), and sip_route_process_header().
 {
    const char *parse = src;
    const char *first_bracket;
    const char *second_bracket;
    if (start == NULL) {
       return -1;
    }
    if (length == NULL) {
       return -1;
    }
    *start = NULL;
    *length = -1;
    if (ast_strlen_zero(src)) {
       return 1;
    }
    /*
     * Skip any quoted text until we find the part in brackets.
     * On any error give up and return -1
     */
    while ( (first_bracket = strchr(parse, '<')) ) {
       const char *first_quote = strchr(parse, '"');
       first_bracket++;
       if (!first_quote || first_quote >= first_bracket) {
          break; /* no need to look at quoted part */
       }
       /* the bracket is within quotes, so ignore it */
       parse = find_closing_quote(first_quote + 1, NULL);
       if (!*parse) {
          ast_log(LOG_WARNING, "No closing quote found in '%s'\n", src);
          return  -1;
       }
       parse++;
    }
    /* Require a first bracket.  Unlike get_in_brackets_full, this procedure is passed a const,
     * so it can expect a pointer to an original value */
    if (!first_bracket) {
       ast_log(LOG_WARNING, "No opening bracket found in '%s'\n", src);
       return 1;
    }
    if ((second_bracket = strchr(first_bracket, '>'))) {
       *start = first_bracket;
       *length = second_bracket - first_bracket;
       return 0;
    }
    ast_log(LOG_WARNING, "No closing bracket found in '%s'\n", src);
    return -1;
 }
get_in_brackets_full()
int get_in_brackets_full (char * tmp, char ** out, char ** residue)
Get text in brackets and any trailing residue.
Return values
0 success
-1 failure
1 no brackets so got all
Definition at line 1105 of file reqresp_parser.c.
References ast_log, ast_strlen_zero, find_closing_quote(), LOG_WARNING, NULL, parse(), and tmp().
Referenced by get_in_brackets(), and parse_name_andor_addr().
 {
    const char *parse = tmp;
    char *first_bracket;
    char *second_bracket;
    if (out) {
       *out = "";
    }
    if (residue) {
       *residue = "";
    }
    if (ast_strlen_zero(tmp)) {
       return 1;
    }
    /*
     * Skip any quoted text until we find the part in brackets.
    * On any error give up and return -1
    */
    while ( (first_bracket = strchr(parse, '<')) ) {
       char *first_quote = strchr(parse, '"');
       first_bracket++;
       if (!first_quote || first_quote >= first_bracket) {
          break; /* no need to look at quoted part */
       }
       /* the bracket is within quotes, so ignore it */
       parse = find_closing_quote(first_quote + 1, NULL);
       if (!*parse) {
          ast_log(LOG_WARNING, "No closing quote found in '%s'\n", tmp);
          return  -1;
       }
       parse++;
    }
    /* If no first bracket then still look for a second bracket as some other parsing functions
    may overwrite first bracket with NULL when terminating a token based display-name. As this
    only affects token based display-names there is no danger of brackets being in quotes */
    if (first_bracket) {
       parse = first_bracket;
    } else {
       parse = tmp;
    }
    if ((second_bracket = strchr(parse, '>'))) {
       *second_bracket++ = '\0';
       if (out) {
          *out = (char *) parse;
       }
       if (residue) {
          *residue = second_bracket;
       }
       return 0;
    }
    if ((first_bracket)) {
       ast_log(LOG_WARNING, "No closing bracket found in '%s'\n", tmp);
       return -1;
    }
    if (out) {
       *out = tmp;
    }
    return 1;
 }
get_name_and_number()
int get_name_and_number (const char * hdr, char ** name, char ** number)
Get name and number from sip header.
Note
name and number point to malloced memory on return and must be freed. If name or number is not found, they will be returned as NULL.
Return values
0 success
-1 failure
Definition at line 905 of file reqresp_parser.c.
References ast_copy_string(), ast_log, ast_strdup, ast_strlen_zero, ast_uri_decode(), ast_uri_sip_user, dummy(), get_calleridname(), get_in_brackets(), LOG_ERROR, NULL, and parse_uri().
Referenced by AST_TEST_DEFINE(), change_redirecting_information(), and get_pai().
 {
    char header[256];
    char tmp_name[256];
    char *tmp_number = NULL;
    char *hostport = NULL;
    char *dummy = NULL;
    if (!name || !number || ast_strlen_zero(hdr)) {
       return -1;
    }
    *number = NULL;
    *name = NULL;
    ast_copy_string(header, hdr, sizeof(header));
    /* strip the display-name portion off the beginning of the header. */
    get_calleridname(header, tmp_name, sizeof(tmp_name));
    /* get uri within < > brackets */
    tmp_number = get_in_brackets(header);
    /* parse out the number here */
    if (parse_uri(tmp_number, "sip:,sips:", &tmp_number, &dummy, &hostport, NULL) || ast_strlen_zero(tmp_number)) {
       ast_log(LOG_ERROR, "can not parse name and number from sip header.\n");
       return -1;
    }
    /* number is not option, and must be present at this point */
    *number = ast_strdup(tmp_number);
    ast_uri_decode(*number, ast_uri_sip_user);
    /* name is optional and may not be present at this point */
    if (!ast_strlen_zero(tmp_name)) {
       *name = ast_strdup(tmp_name);
    }
    return 0;
 }
parse_contact_header()
int parse_contact_header (char * contactheader, struct contactliststruct * contactlist)
Definition at line 1475 of file reqresp_parser.c.
References ast_calloc, AST_LIST_HEAD_SET_NOLOCK, AST_LIST_INSERT_TAIL, contact::expires, get_comma(), contact::headers, contact::hostport, last, contact::name, NULL, contact::params, parse_name_andor_addr(), contact::pass, contact::q, contact::user, and value.
Referenced by AST_TEST_DEFINE().
 {
    int res;
    int last;
    char *comma;
    char *residue;
    char *param;
    char *value;
    struct contact *split_contact = NULL;
    if (*contactheader == '*') {
       return 1;
    }
    split_contact = ast_calloc(1, sizeof(*split_contact));
    AST_LIST_HEAD_SET_NOLOCK(contactlist, split_contact);
    while ((last = get_comma(contactheader, &comma)) != -1) {
       res = parse_name_andor_addr(contactheader, "sip:,sips:",
          &split_contact->name, &split_contact->user,
          &split_contact->pass, &split_contact->hostport,
          &split_contact->params, &split_contact->headers,
          &residue);
       if (res == -1) {
          return res;
       }
       /* parse contact params */
       split_contact->expires = split_contact->q = "";
       while ((value = strchr(residue,'='))) {
          *value++ = '\0';
          param = residue;
          if ((residue = strchr(value,';'))) {
             *residue++ = '\0';
          } else {
             residue = "";
          }
          if (!strcmp(param,"expires")) {
             split_contact->expires = value;
          } else if (!strcmp(param,"q")) {
             split_contact->q = value;
          }
       }
       if (last) {
          return 0;
       }
       contactheader = comma;
       split_contact = ast_calloc(1, sizeof(*split_contact));
       AST_LIST_INSERT_TAIL(contactlist, split_contact, list);
    }
    return last;
 }
parse_name_andor_addr()
int parse_name_andor_addr (char * uri, const char * scheme, char ** name, char ** user, char ** pass, char ** domain, struct uriparams * params, char ** headers, char ** remander)
Parse the ABNF structure name-andor-addr = name-addr / addr-spec into its components and return any trailing message-header parameters.
Return values
0 success
-1 failure
Definition at line 1262 of file reqresp_parser.c.
References buf, get_calleridname(), get_in_brackets_full(), NULL, and parse_uri_full().
Referenced by AST_TEST_DEFINE(), and parse_contact_header().
 {
    char buf[1024];
    char **residue2 = residue;
    char *orig_uri = uri;
    int ret;
    buf[0] = '\0';
    if (name) {
       uri = (char *) get_calleridname(uri, buf, sizeof(buf));
    }
    ret = get_in_brackets_full(uri, &uri, residue);
    if (ret == 0) {
       /*
        * The uri is in brackets so do not treat unknown trailing uri
        * parameters as potential message header parameters.
        */
       if (residue && **residue) {
          /* step over the first semicolon as per parse_uri_full residue */
          *residue = *residue + 1;
       }
       residue2 = NULL;
    }
    if (name) {
       if (buf[0]) {
          /*
           * There is always room at orig_uri for the display-name because
           * at least one character has always been removed.  A '"' or '<'
           * has been removed.
           */
          strcpy(orig_uri, buf);
          *name = orig_uri;
       } else {
          *name = "";
       }
    }
    return parse_uri_full(uri, scheme, user, pass, hostport, params, headers, residue2);
 }
parse_sip_options()
unsigned int parse_sip_options (const char * options, char * unsupported, size_t unsupported_len)
Parse supported header in incoming packet.
This function parses through the options parameters and builds a bit field representing all the SIP options in that field. When an item is found that is not supported, it is copied to the unsupported out buffer.
Parameters
option list
unsupported out buffer (optional)
unsupported out buffer length (optional)
Note
Because this function can be called multiple times, it will append whatever options are specified in options to unsupported. Callers of this function should make sure the unsupported buffer is clear before calling this function.
This function parses through the options parameters and builds a bit field representing all the SIP options in that field. When an item is found that is not supported, it is copied to the unsupported out buffer.
Parameters
options list
unsupported out buffer (optional)
unsupported_len out buffer length (optional)
Definition at line 1693 of file reqresp_parser.c.
References ARRAY_LEN, ast_copy_string(), ast_debug, ast_strdupa, ast_strip(), ast_strlen_zero, FALSE, cfsip_options::id, NULL, out, SIP_OPT_UNKNOWN, sip_options, SUPPORTED, text, and TRUE.
Referenced by AST_TEST_DEFINE(), handle_request_bye(), and handle_request_invite().
 {
    char *next, *sep;
    char *temp;
    int i, found, supported;
    unsigned int profile = 0;
    char *out = unsupported;
    size_t outlen = unsupported_len;
    char *cur_out = out;
    if (ast_strlen_zero(options) )
       return 0;
    temp = ast_strdupa(options);
    ast_debug(3, "Begin: parsing SIP \"Supported: %s\"\n", options);
    for (next = temp; next; next = sep) {
       found = FALSE;
       supported = FALSE;
       if ((sep = strchr(next, ',')) != NULL) {
          *sep++ = '\0';
       }
       /* trim leading and trailing whitespace */
       next = ast_strip(next);
       if (ast_strlen_zero(next)) {
          continue; /* if there is a blank argument in there just skip it */
       }
       ast_debug(3, "Found SIP option: -%s-\n", next);
       for (i = 0; i < ARRAY_LEN(sip_options); i++) {
          if (!strcasecmp(next, sip_options[i].text)) {
             profile |= sip_options[i].id;
             if (sip_options[i].supported == SUPPORTED) {
                supported = TRUE;
             }
             found = TRUE;
             ast_debug(3, "Matched SIP option: %s\n", next);
             break;
          }
       }
       /* If option is not supported, add to unsupported out buffer */
       if (!supported && out && outlen) {
          size_t copylen = strlen(next);
          size_t cur_outlen = strlen(out);
          /* Check to see if there is enough room to store this option.
           * Copy length is string length plus 2 for the ',' and '\0' */
          if ((cur_outlen + copylen + 2) < outlen) {
             /* if this isn't the first item, add the ',' */
             if (cur_outlen) {
                *cur_out = ',';
                cur_out++;
                cur_outlen++;
             }
             ast_copy_string(cur_out, next, (outlen - cur_outlen));
             cur_out += copylen;
          }
       }
       if (!found) {
          profile |= SIP_OPT_UNKNOWN;
          if (!strncasecmp(next, "x-", 2))
             ast_debug(3, "Found private SIP option, not supported: %s\n", next);
          else
             ast_debug(3, "Found no match for SIP option: %s (Please file bug report!)\n", next);
       }
    }
    return profile;
 }
parse_uri()
int parse_uri (char * uri, const char * scheme, char ** ret_name, char ** pass, char ** hostport, char ** transport)
parses a URI in its components.
Note
Multiple scheme's can be specified ',' delimited. ex: "sip:,sips:"
If a component is not requested, do not split around it. This means that if we don't have domain, we cannot split name:pass.
It is safe to call with ret_name, pass, hostport pointing all to the same place.
If no secret parameter is provided, ret_name will return with both parts, user:secret.
If the URI contains a port number, hostport will return with both parts, host:port.
This function overwrites the URI string.
Return values
0 on success
-1 on error.
* general form we are expecting is sip:user:password;user-parameters@host:port;uri-parameters?headers
*
Definition at line 517 of file reqresp_parser.c.
References NULL, parse_uri_full(), and uriparams::transport.
Referenced by AST_TEST_DEFINE(), check_peer_ok(), get_name_and_number(), parse_uri_legacy_check(), and sip_msg_send().
{
    int ret;
    char *headers;
    struct uriparams params;
    headers = NULL;
    ret = parse_uri_full(uri, scheme, user, pass, hostport, &params, &headers, NULL);
    if (transport) {
       *transport=params.transport;
    }
    return ret;
 }
parse_uri_full()
int parse_uri_full (char * uri, const char * scheme, char ** user, char ** pass, char ** hostport, struct uriparams * params, char ** headers, char ** residue)
parses a URI in to all of its components and any trailing residue
Return values
0 on success
-1 on error.
parses a URI in to all of its components and any trailing residue
Definition at line 37 of file reqresp_parser.c.
References ast_debug, ast_strdupa, ast_strlen_zero, c, error(), uriparams::lr, uriparams::maddr, uriparams::method, NULL, strsep(), uriparams::transport, uriparams::ttl, uriparams::user, and value.
Referenced by AST_TEST_DEFINE(), parse_name_andor_addr(), and parse_uri().
 {
    char *userinfo = NULL;
    char *parameters = NULL;
    char *endparams = NULL;
    char *c = NULL;
    int error = 0;
    int teluri_scheme = 0;
    /*
     * Initialize requested strings - some functions don't care if parse_uri fails
     * and will attempt to use string pointers passed into parse_uri even after a
     * parse_uri failure
     */
    if (user) {
       *user = "";
    }
    if (pass) {
       *pass = "";
    }
    if (hostport) {
       *hostport = "";
    }
    if (headers) {
       *headers = "";
    }
    if (residue) {
       *residue = "";
    }
    /* check for valid input */
    if (ast_strlen_zero(uri)) {
       return -1;
    }
    if (scheme) {
       int l;
       char *scheme2 = ast_strdupa(scheme);
       char *cur = strsep(&scheme2, ",");
       for (; !ast_strlen_zero(cur); cur = strsep(&scheme2, ",")) {
          l = strlen(cur);
          if (!strncasecmp(uri, cur, l)) {
             teluri_scheme = !strncasecmp(uri, "tel:", 4);   /* TEL URI */
             uri += l;
             break;
          }
       }
       if (ast_strlen_zero(cur)) {
          ast_debug(1, "No supported scheme found in '%s' using the scheme[s] %s\n", uri, scheme);
          error = -1;
       }
    }
    if (!hostport) {
       /* if we don't want to split around hostport, keep everything as a
        * userinfo - cos thats how old parse_uri operated*/
       userinfo = uri;
    } else if (teluri_scheme) {
       /*
        * tel: TEL URI INVITE RFC 3966 patch
        * See http://www.ietf.org/rfc/rfc3966.txt
        *
        * Once the full RFC 3966 parsing is implemented,
        * the ext= or isub= parameters would be extracted from userinfo.
        * When this kind of subaddressing would be implemented, the userinfo must be further parsed.
        * Those parameters would be used for ISDN or PSTN local extensions.
        *
        * Current restrictions:
        * We currently consider the ";isub=" or the ";ext=" as part of the userinfo (unparsed).
        */
       if ((c = strstr(uri, ";phone-context="))) {
          /*
           * Local number with context or domain.
           * ext= or isub= TEL URI parameters should be upfront.
           * All other parameters should come after the ";phone-context=" parameter.
           * If other parameters would occur before ";phone-context=" they will be ignored.
           */
                         *c = '\0';
                         userinfo = uri;
                         uri = c + 15;
          *hostport = uri;
                 } else if ('+' == uri[0]) {
          /* Global number without context or domain; possibly followed by RFC 3966 and optional other parameters. */
                         userinfo = uri;
          *hostport = uri;
       } else {
          ast_debug(1, "No RFC 3966 global number or context found in '%s'; returning local number anyway\n", uri);
                         userinfo = uri;      /* Return local number anyway */
          error = -1;
       }
    } else {
       char *dom = "";
       if ((c = strchr(uri, '@'))) {
          *c++ = '\0';
          dom = c;
          userinfo = uri;
          uri = c; /* userinfo can contain ? and ; chars so step forward before looking for params and headers */
       } else {
          /* domain-only URI, according to the SIP RFC. */
          dom = uri;
          userinfo = "";
       }
       *hostport = dom;
    }
    if (pass && (c = strchr(userinfo, ':'))) {     /* user:password */
       *c++ = '\0';
       *pass = c;
    } else if (pass) {
       *pass = "";
    }
    if (user) {
       *user = userinfo;
    }
    parameters = uri;
    /* strip [?headers] from end of uri  - even if no header pointer exists*/
    if ((c = strrchr(uri, '?'))) {
       *c++ = '\0';
       uri = c;
       if (headers) {
          *headers = c;
       }
       if ((c = strrchr(uri, ';'))) {
          *c++ = '\0';
       } else {
          c = strrchr(uri, '\0');
       }
       uri = c; /* residue */
    } else if (headers) {
       *headers = "";
    }
    /* parse parameters */
    endparams = strchr(parameters,'\0');
    if ((c = strchr(parameters, ';'))) {
       *c++ = '\0';
       parameters = c;
    } else {
       parameters = endparams;
    }
    if (params) {
       char *rem = parameters; /* unparsed or unrecognised remainder */
       char *label;
       char *value;
       int lr = 0;
       params->transport = "";
       params->user = "";
       params->method = "";
       params->ttl = "";
       params->maddr = "";
       params->lr = 0;
       rem = parameters;
       while ((value = strchr(parameters, '=')) || (lr = !strncmp(parameters, "lr", 2))) {
          /* The while condition will not continue evaluation to set lr if it matches "lr=" */
          if (lr) {
             value = parameters;
          } else {
             *value++ = '\0';
          }
          label = parameters;
          if ((c = strchr(value, ';'))) {
             *c++ = '\0';
             parameters = c;
          } else {
             parameters = endparams;
          }
          if (!strcmp(label, "transport")) {
             params->transport = value;
             rem = parameters;
          } else if (!strcmp(label, "user")) {
             params->user = value;
             rem = parameters;
          } else if (!strcmp(label, "method")) {
             params->method = value;
             rem = parameters;
          } else if (!strcmp(label, "ttl")) {
             params->ttl = value;
             rem = parameters;
          } else if (!strcmp(label, "maddr")) {
             params->maddr = value;
             rem = parameters;
          /* Treat "lr", "lr=yes", "lr=on", "lr=1", "lr=almostanything" as lr enabled and "", "lr=no", "lr=off", "lr=0", "lr=" and "lranything" as lr disabled */
          } else if ((!strcmp(label, "lr") && strcmp(value, "no") && strcmp(value, "off") && strcmp(value, "0") && strcmp(value, "")) || ((lr) && strcmp(value, "lr"))) {
             params->lr = 1;
             rem = parameters;
          } else {
             value--;
             *value = '=';
             if (c) {
                c--;
                *c = ';';
             }
          }
       }
       if (rem > uri) { /* no headers */
          uri = rem;
       }
    }
    if (residue) {
       *residue = uri;
    }
    return error;
 }
parse_via()
struct sip_via* parse_via (const char * header)
Parse a Via header.
This function parses the Via header and processes it according to section 18.2 of RFC 3261 and RFC 3581. Since we don't have a transport layer, we only care about the maddr and ttl parms. The received and rport params are not parsed.
Note
This function fails to parse some odd combinations of SWS in parameter lists.
VIA syntax. RFC 3261 section 25.1
Via               =  ("Via" / "v") HCOLON via-parm *(COMMA via-parm)
via-parm          =  sent-protocol LWS sent-by *(SEMI via-params)
via-params        =  via-ttl / via-maddr
                  / via-received / via-branch
                  / via-extension
via-ttl           =  "ttl" EQUAL ttl
via-maddr         =  "maddr" EQUAL host
via-received      =  "received" EQUAL (IPv4address / IPv6address)
via-branch        =  "branch" EQUAL token
via-extension     =  generic-param
sent-protocol     =  protocol-name SLASH protocol-version
                  SLASH transport
protocol-name     =  "SIP" / token
protocol-version  =  token
transport         =  "UDP" / "TCP" / "TLS" / "SCTP"
                  / other-transport
sent-by           =  host [ COLON port ]
ttl               =  1*3DIGIT ; 0 to 255
Definition at line 2389 of file reqresp_parser.c.
References ast_calloc, ast_log, ast_skip_blanks(), ast_strdup, ast_strlen_zero, sip_via::branch, c, free_via(), LOG_ERROR, sip_via::maddr, NULL, sip_via::port, sip_via::protocol, sip_via::sent_by, strsep(), sip_via::ttl, and sip_via::via.
Referenced by __find_call(), __sip_alloc(), AST_TEST_DEFINE(), and process_via().
 {
    struct sip_via *v = ast_calloc(1, sizeof(*v));
    char *via, *parm;
    if (!v) {
       return NULL;
    }
    v->via = ast_strdup(header);
    v->ttl = 1;
    via = v->via;
    if (ast_strlen_zero(via)) {
       ast_log(LOG_ERROR, "received request without a Via header\n");
       free_via(v);
       return NULL;
    }
    /* seperate the first via-parm */
    via = strsep(&via, ",");
    /* chop off sent-protocol */
    v->protocol = strsep(&via, " \t\r\n");
    if (ast_strlen_zero(v->protocol)) {
       ast_log(LOG_ERROR, "missing sent-protocol in Via header\n");
       free_via(v);
       return NULL;
    }
    v->protocol = ast_skip_blanks(v->protocol);
    if (via) {
       via = ast_skip_blanks(via);
    }
    /* chop off sent-by */
    v->sent_by = strsep(&via, "; \t\r\n");
    if (ast_strlen_zero(v->sent_by)) {
       ast_log(LOG_ERROR, "missing sent-by in Via header\n");
       free_via(v);
       return NULL;
    }
    v->sent_by = ast_skip_blanks(v->sent_by);
    /* store the port, we have to handle ipv6 addresses containing ':'
     * characters gracefully */
    if (((parm = strchr(v->sent_by, ']')) && *(++parm) == ':') || (!(parm = strchr(v->sent_by, ']')) && (parm = strchr(v->sent_by, ':')))) {
       char *endptr;
       v->port = strtol(++parm, &endptr, 10);
    }
    /* evaluate any via-parms */
    while ((parm = strsep(&via, "; \t\r\n"))) {
       char *c;
       if ((c = strstr(parm, "maddr="))) {
          v->maddr = ast_skip_blanks(c + sizeof("maddr=") - 1);
       } else if ((c = strstr(parm, "branch="))) {
          v->branch = ast_skip_blanks(c + sizeof("branch=") - 1);
       } else if ((c = strstr(parm, "ttl="))) {
          char *endptr;
          c = ast_skip_blanks(c + sizeof("ttl=") - 1);
          v->ttl = strtol(c, &endptr, 10);
          /* make sure we got a valid ttl value */
          if (c == endptr) {
             v->ttl = 1;
          }
       }
    }
    return v;
 }
sip_reqresp_parser_exit()
void sip_reqresp_parser_exit (void)
Free resources used by request and response parser.
Definition at line 2682 of file reqresp_parser.c.
References c_locale, and NULL.
Referenced by unload_module().
 {
 #ifdef HAVE_XLOCALE_H
    if (c_locale) {
       freelocale(c_locale);
       c_locale = NULL;
    }
 #endif
 }
sip_reqresp_parser_init()
int sip_reqresp_parser_init (void)
initialize request and response parser data
Return values
0 Success
-1 Failure
Definition at line 2671 of file reqresp_parser.c.
References c_locale, and NULL.
Referenced by load_module().
 {
 #ifdef HAVE_XLOCALE_H
    c_locale = newlocale(LC_CTYPE_MASK, "C", NULL);
    if (!c_locale) {
       return -1;
    }
 #endif
    return 0;
 }
sip_request_parser_register_tests()
void sip_request_parser_register_tests (void)
register request parsing tests
Definition at line 2644 of file reqresp_parser.c.
References AST_TEST_REGISTER.
Referenced by sip_register_tests().
 {
    AST_TEST_REGISTER(get_calleridname_test);
    AST_TEST_REGISTER(sip_parse_uri_test);
    AST_TEST_REGISTER(get_in_brackets_test);
    AST_TEST_REGISTER(get_name_and_number_test);
    AST_TEST_REGISTER(sip_parse_uri_full_test);
    AST_TEST_REGISTER(parse_name_andor_addr_test);
    AST_TEST_REGISTER(parse_contact_header_test);
    AST_TEST_REGISTER(sip_parse_options_test);
    AST_TEST_REGISTER(sip_uri_cmp_test);
    AST_TEST_REGISTER(parse_via_test);
 }
sip_request_parser_unregister_tests()
void sip_request_parser_unregister_tests (void)
unregister request parsing tests
Definition at line 2657 of file reqresp_parser.c.
References AST_TEST_UNREGISTER.
Referenced by sip_unregister_tests().
 {
    AST_TEST_UNREGISTER(sip_parse_uri_test);
    AST_TEST_UNREGISTER(get_calleridname_test);
    AST_TEST_UNREGISTER(get_in_brackets_test);
    AST_TEST_UNREGISTER(get_name_and_number_test);
    AST_TEST_UNREGISTER(sip_parse_uri_full_test);
    AST_TEST_UNREGISTER(parse_name_andor_addr_test);
    AST_TEST_UNREGISTER(parse_contact_header_test);
    AST_TEST_UNREGISTER(sip_parse_options_test);
    AST_TEST_UNREGISTER(sip_uri_cmp_test);
    AST_TEST_UNREGISTER(parse_via_test);
 }
sip_uri_cmp()
int sip_uri_cmp (const char * input1, const char * input2)
Compare two URIs as described in RFC 3261 Section 19.1.4.
Parameters
input1 First URI
input2 Second URI
Return values
0 URIs match
nonzero URIs do not match or one or both is malformed
Definition at line 2153 of file reqresp_parser.c.
References ast_strdupa, ast_strlen_zero, ast_uri_decode(), ast_uri_sip_user, S_OR, sip_uri_domain_cmp(), sip_uri_headers_cmp(), sip_uri_params_cmp(), and strsep().
Referenced by AST_TEST_DEFINE(), find_by_notify_uri_helper(), find_by_subscribe_uri_helper(), handle_request_invite(), and match_req_to_dialog().
 {
    char *uri1;
    char *uri2;
    char *uri_scheme1;
    char *uri_scheme2;
    char *host1;
    char *host2;
    char *params1;
    char *params2;
    char *headers1;
    char *headers2;
    /* XXX It would be really nice if we could just use parse_uri_full() here
     * to separate the components of the URI, but unfortunately it is written
     * in a way that can cause URI parameters to be discarded.
     */
    if (!input1 || !input2) {
       return 1;
    }
    uri1 = ast_strdupa(input1);
    uri2 = ast_strdupa(input2);
    ast_uri_decode(uri1, ast_uri_sip_user);
    ast_uri_decode(uri2, ast_uri_sip_user);
    uri_scheme1 = strsep(&uri1, ":");
    uri_scheme2 = strsep(&uri2, ":");
    if (strcmp(uri_scheme1, uri_scheme2)) {
       return 1;
    }
    /* This function is tailored for SIP and SIPS URIs. There's no
     * need to check uri_scheme2 since we have determined uri_scheme1
     * and uri_scheme2 are equivalent already.
     */
    if (strcmp(uri_scheme1, "sip") && strcmp(uri_scheme1, "sips")) {
       return 1;
    }
    if (ast_strlen_zero(uri1) || ast_strlen_zero(uri2)) {
       return 1;
    }
    if ((host1 = strchr(uri1, '@'))) {
       *host1++ = '\0';
    }
    if ((host2 = strchr(uri2, '@'))) {
       *host2++ = '\0';
    }
    /* Check for mismatched username and passwords. This is the
     * only case-sensitive comparison of a SIP URI
     */
    if ((host1 && !host2) ||
          (host2 && !host1) ||
          (host1 && host2 && strcmp(uri1, uri2))) {
       return 1;
    }
    if (!host1) {
       host1 = uri1;
    }
    if (!host2) {
       host2 = uri2;
    }
    /* Strip off the parameters and headers so we can compare
     * host and port
     */
    if ((params1 = strchr(host1, ';'))) {
       *params1++ = '\0';
    }
    if ((params2 = strchr(host2, ';'))) {
       *params2++ = '\0';
    }
    /* Headers come after parameters, but there may be headers without
     * parameters, thus the S_OR
     */
    if ((headers1 = strchr(S_OR(params1, host1), '?'))) {
       *headers1++ = '\0';
    }
    if ((headers2 = strchr(S_OR(params2, host2), '?'))) {
       *headers2++ = '\0';
    }
    if (sip_uri_domain_cmp(host1, host2)) {
       return 1;
    }
    /* Headers have easier rules to follow, so do those first */
    if (sip_uri_headers_cmp(headers1, headers2)) {
       return 1;
    }
    /* And now the parameters. Ugh */
    return sip_uri_params_cmp(params1, params2);
 }