Asterisk - The Open Source Telephony Project: test_netsock2.c File Reference
test_netsock2.c File Reference
Netsock2 Unit Tests.
#include "asterisk.h"
#include "asterisk/test.h"
#include "asterisk/module.h"
#include "asterisk/netsock2.h"
#include "asterisk/logger.h"
#include "asterisk/config.h"
Data Structures
struct parse_test
Macros
#define TEST_SPLIT_HOSTPORT(str, flags, expected_host, expected_port, expected_result)
Functions
static void __reg_module (void)
static void __unreg_module (void)
struct ast_module * AST_MODULE_SELF_SYM (void)
AST_TEST_DEFINE (parsing)
AST_TEST_DEFINE (split_hostport)
static int load_module (void)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Netsock2 test module" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, }
static const struct ast_module_info * ast_module_info = &__mod_info
Detailed Description
Netsock2 Unit Tests.
Author
Terry Wilson twils.nosp@m.on@d.nosp@m.igium.nosp@m..com
Definition in file test_netsock2.c.
Macro Definition Documentation
TEST_SPLIT_HOSTPORT
#define TEST_SPLIT_HOSTPORT (str, flags, expected_host, expected_port, expected_result)
Referenced by AST_TEST_DEFINE().
Function Documentation
__reg_module()
static void __reg_module (void) static
Definition at line 198 of file test_netsock2.c.
__unreg_module()
static void __unreg_module (void) static
Definition at line 198 of file test_netsock2.c.
AST_MODULE_SELF_SYM()
struct ast_module* AST_MODULE_SELF_SYM (void)
Definition at line 198 of file test_netsock2.c.
AST_TEST_DEFINE() [1/2]
AST_TEST_DEFINE (parsing)
Definition at line 44 of file test_netsock2.c.
References ARRAY_LEN, ast_copy_string(), ast_sockaddr_cmp_addr(), ast_sockaddr_parse(), ast_sockaddr_stringify(), AST_TEST_FAIL, AST_TEST_NOT_RUN, AST_TEST_PASS, ast_test_status_update, buf, parse_test::expected_result, sip_to_pjsip::info(), TEST_EXECUTE, TEST_INIT, and tmp().
 {
    int res = AST_TEST_PASS;
    struct parse_test test_vals[] = {
       { "192.168.1.0", 1 },
       { "10.255.255.254", 1 },
       { "172.18.5.4", 1 },
       { "8.8.4.4", 1 },
       { "0.0.0.0", 1 },
       { "127.0.0.1", 1 },
       { "1.256.3.4", 0 },
       { "256.0.0.1", 0 },
       { "1.2.3.4:5060", 1 },
       { "::ffff:5.6.7.8", 1 },
       { "fdf8:f53b:82e4::53", 1 },
       { "fe80::200:5aee:feaa:20a2", 1 },
       { "2001::1", 1 },
       { "2001:0000:4136:e378:8000:63bf:3fff:fdd2", 1 },
       { "2001:0002:6c::430", 1 },
       { "2001:10:240:ab::a", 1 },
       { "2002:cb0a:3cdd:1::1", 1 },
       { "2001:db8:8:4::2", 1 }, /* Documentation only, should never be used */
       { "ff01:0:0:0:0:0:0:2", 1 }, /* Multicast */
       { "[fdf8:f53b:82e4::53]", 1 },
       { "[fe80::200:5aee:feaa:20a2]", 1 },
       { "[2001::1]", 1 },
       { "[2001:0000:4136:e378:8000:63bf:3fff:fdd2]:5060", 1 },
       { "2001:0000:4136:e378:8000:63bf:3fff:fdd2:5060", 0 }, /* port, but no brackets */
       { "fe80::200::abcd", 0 }, /* multiple zero expansions */
    };
    size_t x;
    struct ast_sockaddr addr;
    int parse_result;
    switch (cmd) {
    case TEST_INIT:
       info->name = "parsing";
       info->category = "/main/netsock2/";
       info->summary = "netsock2 parsing unit test";
       info->description =
          "Test parsing of IPv4 and IPv6 network addresses";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
    for (x = 0; x < ARRAY_LEN(test_vals); x++) {
       memset(&addr, 0, sizeof(addr));
       if ((parse_result = ast_sockaddr_parse(&addr, test_vals[x].address, 0)) != test_vals[x].expected_result) {
          ast_test_status_update(test, "On '%s' expected %d but got %d\n", test_vals[x].address, test_vals[x].expected_result, parse_result);
          res = AST_TEST_FAIL;
       }
       if (parse_result) {
          struct ast_sockaddr tmp_addr;
          const char *tmp;
          tmp = ast_sockaddr_stringify(&addr);
          memset(&tmp_addr, 0, sizeof(tmp_addr));
          ast_sockaddr_parse(&tmp_addr, tmp, 0);
          if (ast_sockaddr_cmp_addr(&addr, &tmp_addr)) {
             char buf[64];
             ast_copy_string(buf, ast_sockaddr_stringify(&addr), sizeof(buf));
             ast_test_status_update(test, "Re-parsed stringification of '%s' did not match: '%s' vs '%s'\n", test_vals[x].address, buf, ast_sockaddr_stringify(&tmp_addr));
             res = AST_TEST_FAIL;
          }
       }
    }
    return res;
 }
AST_TEST_DEFINE() [2/2]
AST_TEST_DEFINE (split_hostport)
Definition at line 116 of file test_netsock2.c.
References AST_TEST_NOT_RUN, AST_TEST_PASS, buf, host, sip_to_pjsip::info(), PARSE_PORT_FORBID, PARSE_PORT_IGNORE, PARSE_PORT_REQUIRE, TEST_EXECUTE, TEST_INIT, and TEST_SPLIT_HOSTPORT.
 {
    int res = AST_TEST_PASS;
    char *host, *port, buf[128];
    switch (cmd) {
    case TEST_INIT:
       info->name = "split_hostport";
       info->category = "/main/netsock2/";
       info->summary = "netsock2 ast_sockaddr_split_hostport() unit test";
       info->description =
          "Test splitting of IPv4 and IPv6 host:port strings";
       return AST_TEST_NOT_RUN;
    case TEST_EXECUTE:
       break;
    }
 /* Assumes res, host, and port variables */
 #define TEST_SPLIT_HOSTPORT(str, flags, expected_host, expected_port, expected_result) { \
    int __res; \
    ast_copy_string(buf, str, sizeof(buf)); \
    if ((__res = ast_sockaddr_split_hostport(buf, &host, &port, flags)) != expected_result || ( \
          expected_result && ( \
             strcmp(host, expected_host) || ( \
                ast_strlen_zero(expected_port) ? !ast_strlen_zero(port) : (!ast_strlen_zero(port) && strcmp(port, expected_port)) \
             ) \
          ) \
       ) \
    ) { \
       res = AST_TEST_FAIL; \
       if (__res != expected_result) { \
          ast_test_status_update(test, "Expected %d, got %d\n", expected_result, __res); \
       } else { \
          ast_test_status_update(test, "Failed parsing '%s' into expected host '%s' (got '%s') and port '%s' (got '%s')\n", \
             str, S_OR(expected_host, ""), host, expected_port, S_OR(port, "")); \
       } \
    } \
 }
    /* Test various situations with flags = 0 */
    TEST_SPLIT_HOSTPORT("192.168.1.1", 0, "192.168.1.1", "", 1);
    TEST_SPLIT_HOSTPORT("192.168.1.1:5060", 0, "192.168.1.1", "5060", 1);
    TEST_SPLIT_HOSTPORT("::ffff:5.6.7.8", 0, "::ffff:5.6.7.8", "", 1);
    TEST_SPLIT_HOSTPORT("[::ffff:5.6.7.8]:5060", 0, "::ffff:5.6.7.8", "5060", 1);
    TEST_SPLIT_HOSTPORT("fdf8:f53b:82e4::53", 0, "fdf8:f53b:82e4::53", "", 1);
    TEST_SPLIT_HOSTPORT("fe80::200:5aee:feaa:20a2", 0, "fe80::200:5aee:feaa:20a2", "", 1);
    TEST_SPLIT_HOSTPORT("[fdf8:f53b:82e4::53]", 0, "fdf8:f53b:82e4::53", "", 1);
    TEST_SPLIT_HOSTPORT("[fe80::200:5aee:feaa:20a2]:5060", 0, "fe80::200:5aee:feaa:20a2", "5060", 1);
    TEST_SPLIT_HOSTPORT("host:port", 0, "host", "port", 1);
    TEST_SPLIT_HOSTPORT("host", 0, "host", "", 1);
    /* Make sure that flag conditions work when they should */
    TEST_SPLIT_HOSTPORT("192.168.1.1:5060", PARSE_PORT_IGNORE, "192.168.1.1", "", 1);
    TEST_SPLIT_HOSTPORT("192.168.1.1:5060", PARSE_PORT_REQUIRE, "192.168.1.1", "5060", 1);
    TEST_SPLIT_HOSTPORT("192.168.1.1", PARSE_PORT_FORBID, "192.168.1.1", "", 1);
    TEST_SPLIT_HOSTPORT("[::ffff:5.6.7.8]:5060", PARSE_PORT_IGNORE, "::ffff:5.6.7.8", "", 1);
    TEST_SPLIT_HOSTPORT("[::ffff:5.6.7.8]:5060", PARSE_PORT_REQUIRE, "::ffff:5.6.7.8", "5060", 1);
    TEST_SPLIT_HOSTPORT("::ffff:5.6.7.8", PARSE_PORT_FORBID, "::ffff:5.6.7.8", "", 1);
    /* Make sure it fails when flag requirements are not met */
    TEST_SPLIT_HOSTPORT("192.168.1.1", PARSE_PORT_REQUIRE, "<undefined>", "<undefined>", 0);
    TEST_SPLIT_HOSTPORT("192.168.1.1:5060", PARSE_PORT_FORBID, "<undefined>", "<undefined>", 0);
    TEST_SPLIT_HOSTPORT("::ffff:5.6.7.8", PARSE_PORT_REQUIRE, "<undefined>", "<undefined>", 0);
    TEST_SPLIT_HOSTPORT("[::ffff:5.6.7.8]:5060", PARSE_PORT_FORBID, "<undefined>", "<undefined>", 0);
    return res;
 }
load_module()
static int load_module (void) static
Definition at line 191 of file test_netsock2.c.
References AST_MODULE_LOAD_SUCCESS, AST_TEST_REGISTER, parsing(), and sip_to_pjsip::split_hostport().
 {
    AST_TEST_REGISTER(parsing);
    AST_TEST_REGISTER(split_hostport);
    return AST_MODULE_LOAD_SUCCESS;
 }
unload_module()
static int unload_module (void) static
Definition at line 184 of file test_netsock2.c.
References AST_TEST_UNREGISTER, parsing(), and sip_to_pjsip::split_hostport().
 {
    AST_TEST_UNREGISTER(parsing);
    AST_TEST_UNREGISTER(split_hostport);
    return 0;
 }
Variable Documentation
__mod_info
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_LOAD_ORDER , .description = "Netsock2 test module" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = AST_BUILDOPT_SUM, .load = load_module, .unload = unload_module, .load_pri = AST_MODPRI_DEFAULT, .support_level = AST_MODULE_SUPPORT_CORE, } static
Definition at line 198 of file test_netsock2.c.
ast_module_info
const struct ast_module_info* ast_module_info = &__mod_info static
Definition at line 198 of file test_netsock2.c.