Asterisk - The Open Source Telephony Project: callerid.c File Reference
callerid.c File Reference
CallerID Generation support.
#include "asterisk.h"
#include <time.h>
#include <math.h>
#include <ctype.h>
#include "asterisk/ulaw.h"
#include "asterisk/alaw.h"
#include "asterisk/frame.h"
#include "asterisk/channel.h"
#include "asterisk/callerid.h"
#include "asterisk/fskmodem.h"
#include "asterisk/utils.h"
#include "asterisk/format_cache.h"
Data Structures
struct ast_value_translation
struct callerid_state
Macros
#define AST_CALLERID_UNKNOWN "<unknown>"
#define CALLERID_MARK 1200.0
#define CALLERID_SPACE 2200.0
#define CAS_FREQ1 2130.0
#define CAS_FREQ2 2750.0
#define SAS_FREQ 440.0
Functions
static int __ast_callerid_generate (unsigned char *buf, const char *name, const char *number, int callwaiting, struct ast_format *codec)
int ast_callerid_callwaiting_generate (unsigned char *buf, const char *name, const char *number, struct ast_format *codec)
Generate Caller-ID spill but in a format suitable for Call Waiting(tm)'s Caller*ID(tm)
int ast_callerid_generate (unsigned char *buf, const char *name, const char *number, struct ast_format *codec)
Generate Caller-ID spill from the "callerid" field of asterisk (in e-mail address like format)
char * ast_callerid_merge (char *buf, int bufsiz, const char *name, const char *num, const char *unknown)
int ast_callerid_parse (char *input_str, char **name, char **location)
Destructively parse inbuf into name and location (or number)
int ast_callerid_split (const char *buf, char *name, int namelen, char *num, int numlen)
int ast_callerid_vmwi_generate (unsigned char *buf, int active, int type, struct ast_format *codec, const char *name, const char *number, int flags)
Generate message waiting indicator.
const char * ast_connected_line_source_describe (int data)
Convert connected line update source value to explanatory string.
const char * ast_connected_line_source_name (int data)
Convert connected line update source value to text code.
int ast_connected_line_source_parse (const char *data)
Convert connected line update source text code to value (used in config file parsing)
const char * ast_describe_caller_presentation (int data)
Convert caller ID pres value to explanatory string.
int ast_gen_cas (unsigned char *outbuf, int sendsas, int len, struct ast_format *codec)
Generate a CAS (CPE Alert Signal) tone for 'n' samples.
int ast_is_shrinkable_phonenumber (const char *exten)
Check if a string consists only of digits and + # () - . (meaning it can be cleaned with ast_shrink_phone_number)
static int ast_is_valid_string (const char *exten, const char *valid)
Checks if phone number consists of valid characters.
int ast_isphonenumber (const char *n)
Check if a string consists only of digits and + #.
const char * ast_named_caller_presentation (int data)
Convert caller ID pres value to text code.
int ast_parse_caller_presentation (const char *data)
Convert caller ID text code to value (used in config file parsing)
const char * ast_party_name_charset_describe (int data)
Convert ast_party_name.char_set value to explanatory string.
int ast_party_name_charset_parse (const char *data)
Convert ast_party_name.char_set text code to value (used in config file parsing)
const char * ast_party_name_charset_str (int data)
Convert ast_party_name.char_set value to text code.
const char * ast_redirecting_reason_describe (int data)
Convert redirecting reason value to explanatory string.
const char * ast_redirecting_reason_name (const struct ast_party_redirecting_reason *data)
Convert redirecting reason value to text code.
int ast_redirecting_reason_parse (const char *data)
Convert redirecting reason text code to value (used in config file parsing)
void ast_shrink_phone_number (char *n)
Clean up phone string.
static unsigned short calc_crc (unsigned short crc, unsigned char data)
int callerid_feed (struct callerid_state *cid, unsigned char *ubuf, int len, struct ast_format *codec)
Read samples into the state machine.
int callerid_feed_jp (struct callerid_state *cid, unsigned char *ubuf, int len, struct ast_format *codec)
Read samples into the state machine.
void callerid_free (struct callerid_state *cid)
This function frees callerid_state cid.
int callerid_generate (unsigned char *buf, const char *number, const char *name, int flags, int callwaiting, struct ast_format *codec)
Generates a CallerID FSK stream in ulaw format suitable for transmission.
static int callerid_genmsg (char *msg, int size, const char *number, const char *name, int flags)
void callerid_get (struct callerid_state *cid, char **name, char **number, int *flags)
Extract info out of callerID state machine. Flags are listed above.
void callerid_get_dtmf (char *cidstring, char *number, int *flags)
Get and parse DTMF-based callerid.
void callerid_init (void)
Initialize stuff for inverse FFT.
struct callerid_state * callerid_new (int cid_signalling)
Create a callerID state machine.
static void gen_tone (unsigned char *buf, int len, struct ast_format *codec, float ddr1, float ddi1, float *cr1, float *ci1)
static void gen_tones (unsigned char *buf, int len, struct ast_format *codec, float ddr1, float ddi1, float ddr2, float ddi2, float *cr1, float *ci1, float *cr2, float *ci2)
Variables
float casdi1
float casdi2
float casdr1
float casdr2
float cid_di [4]
float cid_dr [4]
float clidsb = 8000.0 / 1200.0
static const struct ast_value_translation connected_line_source_types []
Translation table for connected line update source settings.
static const struct ast_value_translation party_name_charset_tbl []
Translation table for ast_party_name char-set settings.
static const struct ast_value_translation pres_types []
Translation table for Caller ID Presentation settings.
static const struct ast_value_translation redirecting_reason_types []
Translation table for redirecting reason settings.
float sasdi
float sasdr
Detailed Description
CallerID Generation support.
Author
Mark Spencer marks.nosp@m.ter@.nosp@m.digiu.nosp@m.m.co.nosp@m.m
Definition in file callerid.c.
Macro Definition Documentation
AST_CALLERID_UNKNOWN
#define AST_CALLERID_UNKNOWN "<unknown>"
Definition at line 75 of file callerid.c.
CALLERID_MARK
#define CALLERID_MARK 1200.0
1200 hz for "1"
Definition at line 70 of file callerid.c.
Referenced by callerid_init().
CALLERID_SPACE
#define CALLERID_SPACE 2200.0
2200 hz for "0"
Definition at line 69 of file callerid.c.
Referenced by callerid_init().
CAS_FREQ1
#define CAS_FREQ1 2130.0
Definition at line 72 of file callerid.c.
Referenced by callerid_init().
CAS_FREQ2
#define CAS_FREQ2 2750.0
Definition at line 73 of file callerid.c.
Referenced by callerid_init().
SAS_FREQ
#define SAS_FREQ 440.0
Definition at line 71 of file callerid.c.
Referenced by callerid_init().
Function Documentation
__ast_callerid_generate()
static int __ast_callerid_generate (unsigned char * buf, const char * name, const char * number, int callwaiting, struct ast_format * codec) static
Definition at line 1054 of file callerid.c.
References ast_strlen_zero, callerid_generate(), and NULL.
Referenced by ast_callerid_callwaiting_generate(), and ast_callerid_generate().
 {
    if (ast_strlen_zero(name))
       name = NULL;
    if (ast_strlen_zero(number))
       number = NULL;
    return callerid_generate(buf, number, name, 0, callwaiting, codec);
 }
ast_callerid_callwaiting_generate()
int ast_callerid_callwaiting_generate (unsigned char * buf, const char * name, const char * number, struct ast_format * codec)
Generate Caller-ID spill but in a format suitable for Call Waiting(tm)'s Caller*ID(tm)
See also
ast_callerid_generate() for other details
Definition at line 1068 of file callerid.c.
References __ast_callerid_generate().
Referenced by my_send_callerid(), and send_cwcidspill().
 {
    return __ast_callerid_generate(buf, name, number, 1, codec);
 }
ast_callerid_generate()
int ast_callerid_generate (unsigned char * buf, const char * name, const char * number, struct ast_format * codec)
Generate Caller-ID spill from the "callerid" field of asterisk (in e-mail address like format)
Parameters
buf buffer for output samples. See callerid_generate() for details regarding buffer.
name Caller-ID Name
number Caller-ID Number
codec Asterisk codec (either AST_FORMAT_ALAW or AST_FORMAT_ULAW)
Acts like callerid_generate except uses an asterisk format callerid string.
Definition at line 1063 of file callerid.c.
References __ast_callerid_generate().
Referenced by my_send_callerid().
 {
    return __ast_callerid_generate(buf, name, number, 0, codec);
 }
ast_callerid_merge()
char* ast_callerid_merge (char * buf, int bufsiz, const char * name, const char * num, const char * unknown)
Definition at line 1073 of file callerid.c.
References ast_copy_string(), ast_escape_quoted(), and buf.
Referenced by _sip_show_peer(), _skinny_show_line(), caller_id_to_str(), cdr_object_create_public_records(), cdr_object_format_property(), cli_show_channel(), cli_show_subscriptions_detail(), handle_cli_iax2_show_peer(), launch_monitor_thread(), leave_voicemail(), prep_email_sub_vars(), sip_show_user(), and sip_subscription_to_ami().
 {
    if (!unknown)
       unknown = "<unknown>";
    if (name && num) {
       char name_buf[128];
       ast_escape_quoted(name, name_buf, sizeof(name_buf));
       snprintf(buf, bufsiz, "\"%s\" <%s>", name_buf, num);
    } else if (name) {
       ast_copy_string(buf, name, bufsiz);
    } else if (num) {
       ast_copy_string(buf, num, bufsiz);
    } else {
       ast_copy_string(buf, unknown, bufsiz);
    }
    return buf;
 }
ast_callerid_parse()
int ast_callerid_parse (char * instr, char ** name, char ** location)
Destructively parse inbuf into name and location (or number)
Parses callerid stream from inbuf and changes into useable form, outputed in name and location.
Parameters
instr buffer of callerid stream (in audio form) to be parsed. Warning, data in buffer is changed.
name address of a pointer-to-char for the name value of the stream.
location address of a pointer-to-char for the phone number value of the stream.
Note
XXX 'name' is not parsed consistently e.g. we have input location name " foo bar " <123> 123 ' foo bar ' (with spaces around) " foo bar " NULL 'foo bar' (without spaces around) The parsing of leading and trailing space/quotes should be more consistent.
Returns
Returns 0 on success, -1 on failure.
Definition at line 1008 of file callerid.c.
References ast_copy_string(), ast_isphonenumber(), ast_shrink_phone_number(), ast_strip(), ast_strip_quoted(), ast_unescape_quoted(), NULL, and tmp().
Referenced by action_originate(), adsi_message(), advanced_options(), ari_channels_handle_originate_with_id(), ast_callerid_split(), ast_privacy_check(), ast_privacy_set(), AST_TEST_DEFINE(), dial_exec_full(), handle_setcallerid(), misdn_new(), play_message_callerid(), read_config(), sip_msg_send(), unistim_new(), and vm_allocate_dh().
 {
    char *ls;
    char *le;
    char *name_start;
    char *instr;
    int quotes_stripped = 0;
    /* Handle surrounding quotes */
    input_str = ast_strip(input_str);
    instr = ast_strip_quoted(input_str, "\"", "\"");
    if (instr != input_str) {
       quotes_stripped = 1;
    }
    /* Try "name" <location> format or name <location> format or with a missing > */
    if ((ls = strrchr(instr, '<'))) {
       if ((le = strrchr(ls, '>'))) {
          *le = '\0'; /* location found, trim off the brackets */
       }
       *ls = '\0';
       *location = ls + 1;  /* and this is the result */
       name_start = ast_strip_quoted(instr, "\"", "\"");
    } else { /* no valid brackets */
       char tmp[256];
       ast_copy_string(tmp, instr, sizeof(tmp));
       ast_shrink_phone_number(tmp);
       if (!quotes_stripped && ast_isphonenumber(tmp)) {  /* Assume it's just a location */
          name_start = NULL;
          strcpy(instr, tmp); /* safe, because tmp will always be the same size or smaller than instr */
          *location = instr;
       } else { /* Assume it's just a name. */
          *location = NULL;
          name_start = ast_strip_quoted(instr, "\"", "\"");
       }
    }
    if (name_start) {
       ast_unescape_quoted(name_start);
    }
    *name = name_start;
    return 0;
 }
ast_callerid_split()
int ast_callerid_split (const char * buf, char * name, int namelen, char * num, int numlen)
Definition at line 1092 of file callerid.c.
References ast_callerid_parse(), ast_copy_string(), ast_shrink_phone_number(), ast_strdupa, NULL, and tmp().
Referenced by build_gateway(), build_peer(), build_user(), caller_id_handler(), callerid_read(), config_parse_variables(), disa_exec(), load_module(), parse_line(), party_id_write(), prep_email_sub_vars(), process_dahdi(), and store_callerid().
 {
    char *tmp;
    char *l = NULL, *n = NULL;
    tmp = ast_strdupa(buf);
    ast_callerid_parse(tmp, &n, &l);
    if (n)
       ast_copy_string(name, n, namelen);
    else
       name[0] = '\0';
    if (l) {
       ast_shrink_phone_number(l);
       ast_copy_string(num, l, numlen);
    } else
       num[0] = '\0';
    return 0;
 }
ast_callerid_vmwi_generate()
int ast_callerid_vmwi_generate (unsigned char * buf, int active, int type, struct ast_format * codec, const char * name, const char * number, int flags)
Generate message waiting indicator.
Parameters
buf
active The message indicator state – either 0 no messages in mailbox or 1 messages in mailbox
type Format of message (any of CID_MWI_TYPE_*)
codec
name
number
flags
See also
callerid_generate() for more info as it uses the same encoding
Version
1.6.1 changed mdmf parameter to type, added name, number and flags for caller id message generation
Definition at line 810 of file callerid.c.
References callerid_genmsg(), CID_MWI_TYPE_MDMF, CID_MWI_TYPE_MDMF_FULL, callerid_state::len, PUT_BYTE, PUT_CLID, and PUT_CLID_MARKMS.
Referenced by mwi_send_init().
 {
    char msg[256];
    int len = 0;
    int sum;
    int x;
    int bytes = 0;
    float cr = 1.0;
    float ci = 0.0;
    float scont = 0.0;
    if (type == CID_MWI_TYPE_MDMF_FULL) {
       /* MDMF Message waiting with date, number, name and MWI parameter */
       msg[0] = 0x82;
       /* put date, number info at the right place */
       len = callerid_genmsg(msg+2, sizeof(msg)-2, number, name, flags);
       /* length of MDMF CLI plus Message Waiting Structure */
       msg[1] = len+3;
       /* Go to the position to write to */
       len = len+2;
       /* "Message Waiting Parameter" */
       msg[len++] = 0x0b;
       /* Length of IE is one */
       msg[len++] = 1;
       /* Active or not */
       if (active)
          msg[len++] = 0xff;
       else
          msg[len++] = 0x00;
    } else if (type == CID_MWI_TYPE_MDMF) {
       /* MDMF Message waiting only */
       /* same as above except that the we only put MWI parameter */
       msg[len++] = 0x82;
       /* Length is 3 */
       msg[len++] = 3;
       /* IE is "Message Waiting Parameter" */
       msg[len++] = 0x0b;
       /* Length of IE is one */
       msg[len++] = 1;
       /* Active or not */
       if (active)
          msg[len++] = 0xff;
       else
          msg[len++] = 0x00;
    } else {
       /* SDMF Message waiting */
       msg[len++] = 0x6;
       /* Length is 3 */
       msg[len++] = 3;
       if (active) {
          msg[len++] = 0x42;
          msg[len++] = 0x42;
          msg[len++] = 0x42;
       } else {
          msg[len++] = 0x6f;
          msg[len++] = 0x6f;
          msg[len++] = 0x6f;
       }
    }
    sum = 0;
    for (x = 0; x < len; x++)
       sum += msg[x];
    sum = (256 - (sum & 255));
    msg[len++] = sum;
    /* Wait a half a second */
    for (x = 0; x < 4000; x++)
       PUT_BYTE(0x7f);
    /* Transmit 30 0x55's (looks like a square wave) for channel seizure */
    for (x = 0; x < 30; x++)
       PUT_CLID(0x55);
    /* Send 170ms of callerid marks */
    for (x = 0; x < 170; x++)
       PUT_CLID_MARKMS;
    for (x = 0; x < len; x++) {
       PUT_CLID(msg[x]);
    }
    /* Send 50 more ms of marks */
    for (x = 0; x < 50; x++)
       PUT_CLID_MARKMS;
    return bytes;
 }
ast_connected_line_source_describe()
const char* ast_connected_line_source_describe (int data)
Convert connected line update source value to explanatory string.
Since
1.8
Parameters
data AST_CONNECTED_LINE_UPDATE_SOURCE from callerid.h
Returns
string for human presentation
Definition at line 1292 of file callerid.c.
References ARRAY_LEN, ast_value_translation::description, and value.
 {
    int index;
    for (index = 0; index < ARRAY_LEN(connected_line_source_types); ++index) {
       if (connected_line_source_types[index].value == data) {
          return connected_line_source_types[index].description;
       }
    }
    return "not-known";
 }
ast_connected_line_source_name()
const char* ast_connected_line_source_name (int data)
Convert connected line update source value to text code.
Since
1.8
Parameters
data AST_CONNECTED_LINE_UPDATE_SOURCE from callerid.h
Returns
string for config file
Definition at line 1305 of file callerid.c.
References ARRAY_LEN, ast_value_translation::name, and value.
Referenced by connectedline_read().
 {
    int index;
    for (index = 0; index < ARRAY_LEN(connected_line_source_types); ++index) {
       if (connected_line_source_types[index].value == data) {
          return connected_line_source_types[index].name;
       }
    }
    return "not-known";
 }
ast_connected_line_source_parse()
int ast_connected_line_source_parse (const char * data)
Convert connected line update source text code to value (used in config file parsing)
Since
1.8
Parameters
data text string from config file
Return values
AST_CONNECTED_LINE_UPDATE_SOURCE from callerid.h
-1 if not in table
Definition at line 1279 of file callerid.c.
References ARRAY_LEN, callerid_state::name, and ast_value_translation::value.
Referenced by connectedline_write().
 {
    int index;
    for (index = 0; index < ARRAY_LEN(connected_line_source_types); ++index) {
       if (!strcasecmp(connected_line_source_types[index].name, data)) {
          return connected_line_source_types[index].value;
       }
    }
    return -1;
 }
ast_describe_caller_presentation()
const char* ast_describe_caller_presentation (int data)
Convert caller ID pres value to explanatory string.
Parameters
data AST_PRES_ value from callerid.h
Returns
string for human presentation
Definition at line 1164 of file callerid.c.
References ARRAY_LEN, ast_value_translation::description, and value.
Referenced by _sip_show_peer(), ast_json_party_id(), channel_callerid(), channel_new_callerid(), json_party_name(), json_party_number(), and sip_show_user().
 {
    int index;
    for (index = 0; index < ARRAY_LEN(pres_types); ++index) {
       if (pres_types[index].value == data) {
          return pres_types[index].description;
       }
    }
    return "unknown";
 }
ast_gen_cas()
int ast_gen_cas (unsigned char * outbuf, int sas, int len, struct ast_format * codec)
Generate a CAS (CPE Alert Signal) tone for 'n' samples.
Parameters
outbuf Allocated buffer for data. Must be at least 2400 bytes unless no SAS is desired
sas Non-zero if CAS should be preceeded by SAS
len How many samples to generate.
codec Which codec (AST_FORMAT_ALAW or AST_FORMAT_ULAW)
Returns
Returns -1 on error (if len is less than 2400), 0 on success.
Definition at line 261 of file callerid.c.
References casdi1, casdi2, casdr1, casdr2, gen_tone(), gen_tones(), callerid_state::pos, sasdi, and sasdr.
Referenced by __adsi_transmit_messages(), dahdi_callwait(), and my_callwait().
 {
    int pos = 0;
    int saslen = 2400;
    float cr1 = 1.0;
    float ci1 = 0.0;
    float cr2 = 1.0;
    float ci2 = 0.0;
    if (sendsas) {
       if (len < saslen)
          return -1;
       gen_tone(outbuf, saslen, codec, sasdr, sasdi, &cr1, &ci1);
       len -= saslen;
       pos += saslen;
       cr2 = cr1;
       ci2 = ci1;
    }
    gen_tones(outbuf + pos, len, codec, casdr1, casdi1, casdr2, casdi2, &cr1, &ci1, &cr2, &ci2);
    return 0;
 }
ast_is_shrinkable_phonenumber()
int ast_is_shrinkable_phonenumber (const char * exten)
Check if a string consists only of digits and + # () - . (meaning it can be cleaned with ast_shrink_phone_number)
Parameters
exten The extension (or URI) to be checked.
Return values
1 if string is valid AST shrinkable phone number
0 if not
Definition at line 1003 of file callerid.c.
References ast_is_valid_string().
Referenced by ari_channels_handle_originate_with_id(), check_peer_ok(), check_user_full(), get_pai(), and get_rpid().
 {
    return ast_is_valid_string(exten, "0123456789*#+()-.");
 }
ast_is_valid_string()
static int ast_is_valid_string (const char * exten, const char * valid) static
Checks if phone number consists of valid characters.
Parameters
exten String that needs to be checked
valid Valid characters in string
Return values
1 if valid string
0 if string contains invalid characters
Definition at line 986 of file callerid.c.
References ast_strlen_zero.
Referenced by ast_is_shrinkable_phonenumber(), and ast_isphonenumber().
 {
    int x;
    if (ast_strlen_zero(exten))
       return 0;
    for (x = 0; exten[x]; x++)
       if (!strchr(valid, exten[x]))
          return 0;
    return 1;
 }
ast_isphonenumber()
int ast_isphonenumber (const char * n)
Check if a string consists only of digits and + #.
Parameters
n number to be checked.
Returns
Returns 0 if n is a number, 1 if it's not.
Definition at line 998 of file callerid.c.
References ast_is_valid_string().
Referenced by ast_callerid_parse(), and hfp_parse_clip().
 {
    return ast_is_valid_string(n, "0123456789*#+");
 }
ast_named_caller_presentation()
const char* ast_named_caller_presentation (int data)
Convert caller ID pres value to text code.
Parameters
data AST_PRES_ value from callerid.h
Returns
string for config file
Definition at line 1182 of file callerid.c.
References ARRAY_LEN, ast_value_translation::name, and value.
Referenced by caller_id_privacy_to_str(), cb_events(), party_id_read(), party_name_read(), party_number_read(), and redirecting_read().
 {
    int index;
    for (index = 0; index < ARRAY_LEN(pres_types); ++index) {
       if (pres_types[index].value == data) {
          return pres_types[index].name;
       }
    }
    return "unknown";
 }
ast_parse_caller_presentation()
int ast_parse_caller_presentation (const char * data)
Convert caller ID text code to value (used in config file parsing)
Parameters
data text string from config file
Return values
value AST_PRES_ from callerid.h
-1 if not in table
Definition at line 1143 of file callerid.c.
References ARRAY_LEN, callerid_state::name, and ast_value_translation::value.
Referenced by build_peer(), caller_id_privacy_handler(), dial_exec_full(), party_id_write(), party_name_write(), party_number_write(), and redirecting_write().
 {
    int index;
    if (!data) {
       return -1;
    }
    for (index = 0; index < ARRAY_LEN(pres_types); ++index) {
       if (!strcasecmp(pres_types[index].name, data)) {
          return pres_types[index].value;
       }
    }
    return -1;
 }
ast_party_name_charset_describe()
const char* ast_party_name_charset_describe (int data)
Convert ast_party_name.char_set value to explanatory string.
Since
1.8
Parameters
data AST_PARTY_CHAR_SET from channel.h
Returns
string for human presentation
Definition at line 1347 of file callerid.c.
References ARRAY_LEN, ast_value_translation::description, and value.
Referenced by json_party_name().
 {
    int index;
    for (index = 0; index < ARRAY_LEN(party_name_charset_tbl); ++index) {
       if (party_name_charset_tbl[index].value == data) {
          return party_name_charset_tbl[index].description;
       }
    }
    return "not-known";
 }
ast_party_name_charset_parse()
int ast_party_name_charset_parse (const char * data)
Convert ast_party_name.char_set text code to value (used in config file parsing)
Since
1.8
Parameters
data text string from config file
Return values
AST_PARTY_CHAR_SET from channel.h
-1 if not in table
Definition at line 1334 of file callerid.c.
References ARRAY_LEN, callerid_state::name, and ast_value_translation::value.
Referenced by party_name_write().
 {
    int index;
    for (index = 0; index < ARRAY_LEN(party_name_charset_tbl); ++index) {
       if (!strcasecmp(party_name_charset_tbl[index].name, data)) {
          return party_name_charset_tbl[index].value;
       }
    }
    return -1;
 }
ast_party_name_charset_str()
const char* ast_party_name_charset_str (int data)
Convert ast_party_name.char_set value to text code.
Since
1.8
Parameters
data AST_PARTY_CHAR_SET from channel.h
Returns
string for config file
Definition at line 1360 of file callerid.c.
References ARRAY_LEN, ast_value_translation::name, and value.
Referenced by party_name_read().
 {
    int index;
    for (index = 0; index < ARRAY_LEN(party_name_charset_tbl); ++index) {
       if (party_name_charset_tbl[index].value == data) {
          return party_name_charset_tbl[index].name;
       }
    }
    return "not-known";
 }
ast_redirecting_reason_describe()
const char* ast_redirecting_reason_describe (int data)
Convert redirecting reason value to explanatory string.
Since
1.8
Parameters
data Q931_REDIRECTING_REASON from callerid.h
Returns
string for human presentation
Definition at line 1236 of file callerid.c.
References ARRAY_LEN, ast_value_translation::description, and value.
 {
    int index;
    for (index = 0; index < ARRAY_LEN(redirecting_reason_types); ++index) {
       if (redirecting_reason_types[index].value == data) {
          return redirecting_reason_types[index].description ?: "Redirecting reason alias-bug";
       }
    }
    return "not-known";
 }
ast_redirecting_reason_name()
const char* ast_redirecting_reason_name (const struct ast_party_redirecting_reason * data)
Convert redirecting reason value to text code.
Since
1.8
Parameters
data ast_party_redirecting_reason structure from channel.h
Returns
string for config file
Definition at line 1249 of file callerid.c.
References ARRAY_LEN, ast_strlen_zero, ast_party_redirecting_reason::code, ast_value_translation::name, ast_party_redirecting_reason::str, and value.
Referenced by redirecting_read().
 {
    int index;
    if (!ast_strlen_zero(data->str)) {
       /* Use this string if it has been set. Otherwise, use the table. */
       return data->str;
    }
    for (index = 0; index < ARRAY_LEN(redirecting_reason_types); ++index) {
       if (redirecting_reason_types[index].value == data->code) {
          return redirecting_reason_types[index].name;
       }
    }
    return "not-known";
 }
ast_redirecting_reason_parse()
int ast_redirecting_reason_parse (const char * data)
Convert redirecting reason text code to value (used in config file parsing)
Since
1.8
Parameters
data text string from config file
Return values
Q931_REDIRECTING_REASON from callerid.h
-1 if not in table
Definition at line 1223 of file callerid.c.
References ARRAY_LEN, callerid_state::name, and ast_value_translation::value.
Referenced by get_rdnis(), handle_response_invite(), redirecting_write(), and set_redirecting_reason().
 {
    int index;
    for (index = 0; index < ARRAY_LEN(redirecting_reason_types); ++index) {
       if (!strcasecmp(redirecting_reason_types[index].name, data)) {
          return redirecting_reason_types[index].value;
       }
    }
    return -1;
 }
ast_shrink_phone_number()
void ast_shrink_phone_number (char * n)
Clean up phone string.
Shrink a phone number in place to just digits (more accurately it just removes ()'s, .'s, and -'s...
Remove '(', ' ', ')', non-trailing '.', and '-' not in square brackets. Basically, remove anything that could be invalid in a pattern.
Definition at line 947 of file callerid.c.
Referenced by __analog_ss_thread(), action_originate(), analog_ss_thread(), ari_channels_handle_originate_with_id(), ast_callerid_parse(), ast_callerid_split(), ast_privacy_check(), ast_privacy_set(), check_access(), check_peer_ok(), check_user_full(), get_pai(), get_rpid(), handle_setcallerid(), pbx_load_config(), setup_privacy_args(), and write_metadata().
 {
    int x, y = 0;
    int bracketed = 0;
    for (x = 0; n[x]; x++) {
       switch (n[x]) {
       case '[':
          bracketed++;
          n[y++] = n[x];
          break;
       case ']':
          bracketed--;
          n[y++] = n[x];
          break;
       case '-':
          if (bracketed)
             n[y++] = n[x];
          break;
       case '.':
          if (!n[x+1])
             n[y++] = n[x];
          break;
       default:
          /* ignore parenthesis and whitespace */
          if (!strchr("( )", n[x]))
             n[y++] = n[x];
       }
    }
    n[y] = '\0';
 }
calc_crc()
static unsigned short calc_crc (unsigned short crc, unsigned char data) static
Definition at line 283 of file callerid.c.
References callerid_state::crc, and org.
Referenced by callerid_feed_jp().
 {
    unsigned int i, j, org, dst;
    org = data;
    dst = 0;
    for (i = 0; i < CHAR_BIT; i++) {
       org <<= 1;
       dst >>= 1;
       if (org & 0x100)
          dst |= 0x80;
    }
    data = (unsigned char) dst;
    crc ^= (unsigned int) data << (16 - CHAR_BIT);
    for (j = 0; j < CHAR_BIT; j++) {
       if (crc & 0x8000U)
          crc = (crc << 1) ^ 0x1021U ;
       else
          crc <<= 1 ;
    }
    return crc;
 }
callerid_feed()
int callerid_feed (struct callerid_state * cid, unsigned char * ubuf, int samples, struct ast_format * codec)
Read samples into the state machine.
Parameters
cid Which state machine to act upon
ubuf containing your samples
samples number of samples contained within the buffer.
codec which codec (AST_FORMAT_ALAW or AST_FORMAT_ULAW)
Send received audio to the Caller*ID demodulator.
Return values
-1 on error
0 for "needs more samples"
1 if the CallerID spill reception is complete.
Definition at line 545 of file callerid.c.
References ast_alloca, ast_copy_string(), ast_log, ast_strlen_zero, AST_XLAW, b, buf, CID_MSGWAITING, CID_NOMSGWAITING, CID_PRIVATE_NAME, CID_PRIVATE_NUMBER, CID_UNKNOWN_NAME, CID_UNKNOWN_NUMBER, callerid_state::cksum, callerid_state::flags, fsk_serial(), callerid_state::fskd, callerid_state::len, LOG_ERROR, LOG_NOTICE, LOG_WARNING, callerid_state::name, callerid_state::number, callerid_state::oldlen, callerid_state::oldstuff, callerid_state::pos, callerid_state::rawdata, callerid_state::sawflag, and callerid_state::type.
Referenced by analog_ss_thread(), mwi_thread(), and my_get_callerid().
 {
    int mylen = len;
    int olen;
    int b = 'X';
    int res;
    int x;
    short *buf;
    buf = ast_alloca(2 * len + cid->oldlen);
    memcpy(buf, cid->oldstuff, cid->oldlen);
    mylen += cid->oldlen/2;
    for (x = 0; x < len; x++)
       buf[x+cid->oldlen/2] = AST_XLAW(ubuf[x]);
    while (mylen >= 160) {
       olen = mylen;
       res = fsk_serial(&cid->fskd, buf, &mylen, &b);
       if (mylen < 0) {
          ast_log(LOG_ERROR, "No start bit found in fsk data.\n");
          return -1;
       }
       buf += (olen - mylen);
       if (res < 0) {
          ast_log(LOG_NOTICE, "fsk_serial failed\n");
          return -1;
       }
       if (res == 1) {
          if (b > 0xff) {
             if (cid->sawflag != 5) {
                /* Ignore invalid bytes */
                continue;
             }
             /*
              * We can tollerate an error on the checksum character since the
              * checksum character is the last character in the message and
              * it validates the message.
              *
              * Remove character error flags.
              * Bit 8 : Parity error
              * Bit 9 : Framing error
              */
             b &= 0xff;
          }
          switch (cid->sawflag) {
          case 0: /* Look for flag */
             if (b == 'U')
                cid->sawflag = 2;
             break;
          case 2: /* Get lead-in */
             if ((b == 0x04) || (b == 0x80) || (b == 0x06) || (b == 0x82)) {
                cid->type = b;
                cid->sawflag = 3;
                cid->cksum = b;
             }
             break;
          case 3:  /* Get length */
             /* Not a lead in.  We're ready  */
             cid->sawflag = 4;
             cid->len = b;
             cid->pos = 0;
             cid->cksum += b;
             break;
          case 4: /* Retrieve message */
             if (cid->pos >= 128) {
                ast_log(LOG_WARNING, "Caller ID too long???\n");
                return -1;
             }
             cid->rawdata[cid->pos++] = b;
             cid->len--;
             cid->cksum += b;
             if (!cid->len) {
                cid->rawdata[cid->pos] = '\0';
                cid->sawflag = 5;
             }
             break;
          case 5: /* Check checksum */
             if ((b + cid->cksum) & 0xff) {
                ast_log(LOG_NOTICE, "Caller*ID failed checksum\n");
                /* Try again */
                cid->sawflag = 0;
                break;
             }
             cid->number[0] = '\0';
             cid->name[0] = '\0';
             /* Update flags */
             cid->flags = 0;
             /* If we get this far we're fine.  */
             if ((cid->type == 0x80) || (cid->type == 0x82)) {
                /* MDMF */
                /* Go through each element and process */
                for (x = 0; x < cid->pos;) {
                   switch (cid->rawdata[x++]) {
                   case 1:
                      /* Date */
                      break;
                   case 2: /* Number */
                   case 3: /* Number (for Zebble) */
                   case 4: /* Number */
                      res = cid->rawdata[x];
                      if (res > 32) {
                         ast_log(LOG_NOTICE, "Truncating long caller ID number from %d bytes to 32\n", cid->rawdata[x]);
                         res = 32;
                      }
                      if (ast_strlen_zero(cid->number)) {
                         memcpy(cid->number, cid->rawdata + x + 1, res);
                         /* Null terminate */
                         cid->number[res] = '\0';
                      }
                      break;
                   case 6: /* Stentor Call Qualifier (ie. Long Distance call) */
                      break;
                   case 7: /* Name */
                   case 8: /* Name */
                      res = cid->rawdata[x];
                      if (res > 32) {
                         ast_log(LOG_NOTICE, "Truncating long caller ID name from %d bytes to 32\n", cid->rawdata[x]);
                         res = 32;
                      }
                      memcpy(cid->name, cid->rawdata + x + 1, res);
                      cid->name[res] = '\0';
                      break;
                   case 11: /* Message Waiting */
                      res = cid->rawdata[x + 1];
                      if (res)
                         cid->flags |= CID_MSGWAITING;
                      else
                         cid->flags |= CID_NOMSGWAITING;
                      break;
                   case 17: /* UK: Call type, 1=Voice Call, 2=Ringback when free, 129=Message waiting  */
                   case 19: /* UK: Network message system status (Number of messages waiting) */
                   case 22: /* Something French */
                      break;
                   default:
                      ast_log(LOG_NOTICE, "Unknown IE %d\n", cid->rawdata[x - 1]);
                   }
                   res = cid->rawdata[x];
                   if (0 > res){  /* Negative offset in the CID Spill */
                      ast_log(LOG_NOTICE, "IE %d has bad field length of %d at offset %d\n", cid->rawdata[x-1], cid->rawdata[x], x);
                      /* Try again */
                      cid->sawflag = 0;
                      break;   /* Exit the loop */
                   }
                   x += cid->rawdata[x];
                   x++;
                }
             } else if (cid->type == 0x6) {
                /* VMWI SDMF */
                if (cid->rawdata[2] == 0x42) {
                   cid->flags |= CID_MSGWAITING;
                } else if (cid->rawdata[2] == 0x6f) {
                   cid->flags |= CID_NOMSGWAITING;
                }
             } else {
                /* SDMF */
                ast_copy_string(cid->number, cid->rawdata + 8, sizeof(cid->number));
             }
             if (!strcmp(cid->number, "P")) {
                strcpy(cid->number, "");
                cid->flags |= CID_PRIVATE_NUMBER;
             } else if (!strcmp(cid->number, "O") || ast_strlen_zero(cid->number)) {
                strcpy(cid->number, "");
                cid->flags |= CID_UNKNOWN_NUMBER;
             }
             if (!strcmp(cid->name, "P")) {
                strcpy(cid->name, "");
                cid->flags |= CID_PRIVATE_NAME;
             } else if (!strcmp(cid->name, "O") || ast_strlen_zero(cid->name)) {
                strcpy(cid->name, "");
                cid->flags |= CID_UNKNOWN_NAME;
             }
             return 1;
             break;
          default:
             ast_log(LOG_ERROR, "Dunno what to do with a digit in sawflag %d\n", cid->sawflag);
          }
       }
    }
    if (mylen) {
       memcpy(cid->oldstuff, buf, mylen * 2);
       cid->oldlen = mylen * 2;
    } else
       cid->oldlen = 0;
    return 0;
 }
callerid_feed_jp()
int callerid_feed_jp (struct callerid_state * cid, unsigned char * ubuf, int samples, struct ast_format * codec)
Read samples into the state machine.
Parameters
cid Which state machine to act upon
ubuf containing your samples
samples number of samples contained within the buffer.
codec which codec (AST_FORMAT_ALAW or AST_FORMAT_ULAW)
Send received audio to the Caller*ID demodulator (for japanese style lines).
Return values
-1 on error
0 for "needs more samples"
1 if the CallerID spill reception is complete.
Definition at line 306 of file callerid.c.
References ast_alloca, ast_copy_string(), ast_debug, ast_log, AST_XLAW, b, buf, calc_crc(), CID_UNKNOWN_NUMBER, callerid_state::crc, DEBUG_ATLEAST, callerid_state::flags, fsk_serial(), callerid_state::fskd, callerid_state::len, LOG_ERROR, LOG_NOTICE, LOG_WARNING, callerid_state::name, callerid_state::number, callerid_state::oldlen, callerid_state::oldstuff, callerid_state::pos, callerid_state::rawdata, callerid_state::sawflag, and callerid_state::skipflag.
Referenced by analog_ss_thread(), and my_get_callerid().
 {
    int mylen = len;
    int olen;
    int b = 'X';
    int b2;
    int res;
    int x;
    short *buf;
    buf = ast_alloca(2 * len + cid->oldlen);
    memcpy(buf, cid->oldstuff, cid->oldlen);
    mylen += cid->oldlen / 2;
    for (x = 0; x < len; x++)
       buf[x+cid->oldlen/2] = AST_XLAW(ubuf[x]);
    while (mylen >= 160) {
       b = b2 = 0;
       olen = mylen;
       res = fsk_serial(&cid->fskd, buf, &mylen, &b);
       if (mylen < 0) {
          ast_log(LOG_ERROR, "No start bit found in fsk data.\n");
          return -1;
       }
       buf += (olen - mylen);
       if (res < 0) {
          ast_log(LOG_NOTICE, "fsk_serial failed\n");
          return -1;
       }
       if (res == 1) {
          b2 = b;
          b  &= 0x7f;
          /* crc checksum calculation */
          if (cid->sawflag > 1)
             cid->crc = calc_crc(cid->crc, (unsigned char) b2);
          /* Ignore invalid bytes */
          if (b > 0xff)
             continue;
          /* skip DLE if needed */
          if (cid->sawflag > 0) {
             if (cid->sawflag != 5 && cid->skipflag == 0 && b == 0x10) {
                cid->skipflag = 1 ;
                continue ;
             }
          }
          if (cid->skipflag == 1)
             cid->skipflag = 0 ;
          /* caller id retrieval */
          switch (cid->sawflag) {
          case 0: /* DLE */
             if (b == 0x10) {
                cid->sawflag = 1;
                cid->skipflag = 0;
                cid->crc = 0;
             }
             break;
          case 1: /* SOH */
             if (b == 0x01)
                cid->sawflag = 2;
             break ;
          case 2: /* HEADER */
             if (b == 0x07)
                cid->sawflag = 3;
             break;
          case 3: /* STX */
             if (b == 0x02)
                cid->sawflag = 4;
             break;
          case 4: /* SERVICE TYPE */
             if (b == 0x40)
                cid->sawflag = 5;
             break;
          case 5: /* Frame Length */
             cid->sawflag = 6;
             break;
          case 6: /* NUMBER TYPE */
             cid->sawflag = 7;
             cid->pos = 0;
             cid->rawdata[cid->pos++] = b;
             break;
          case 7:  /* NUMBER LENGTH */
             cid->sawflag = 8;
             cid->len = b;
             if ((cid->len+2) >= sizeof(cid->rawdata)) {
                ast_log(LOG_WARNING, "too long caller id string\n") ;
                return -1;
             }
             cid->rawdata[cid->pos++] = b;
             break;
          case 8:  /* Retrieve message */
             cid->rawdata[cid->pos++] = b;
             cid->len--;
             if (cid->len<=0) {
                cid->rawdata[cid->pos] = '\0';
                cid->sawflag = 9;
             }
             break;
          case 9:  /* ETX */
             cid->sawflag = 10;
             break;
          case 10: /* CRC Checksum 1 */
             cid->sawflag = 11;
             break;
          case 11: /* CRC Checksum 2 */
             cid->sawflag = 12;
             if (cid->crc != 0) {
                ast_log(LOG_WARNING, "crc checksum error\n") ;
                return -1;
             }
             /* extract caller id data */
             for (x = 0; x < cid->pos;) {
                switch (cid->rawdata[x++]) {
                case 0x02: /* caller id  number */
                   cid->number[0] = '\0';
                   cid->name[0] = '\0';
                   cid->flags = 0;
                   res = cid->rawdata[x++];
                   ast_copy_string(cid->number, &cid->rawdata[x], res+1);
                   x += res;
                   break;
                case 0x21: /* additional information */
                   /* length */
                   x++;
                   /* number type */
                   switch (cid->rawdata[x]) {
                   case 0x00: /* unknown */
                   case 0x01: /* international number */
                   case 0x02: /* domestic number */
                   case 0x03: /* network */
                   case 0x04: /* local call */
                   case 0x06: /* short dial number */
                   case 0x07: /* reserved */
                   default:   /* reserved */
                      ast_debug(2, "cid info:#1=%X\n", (unsigned)cid->rawdata[x]);
                      break ;
                   }
                   x++;
                   /* numbering plan octed 4 */
                   x++;
                   /* numbering plan octed 5 */
                   switch (cid->rawdata[x]) {
                   case 0x00: /* unknown */
                   case 0x01: /* recommendation E.164 ISDN */
                   case 0x03: /* recommendation X.121 */
                   case 0x04: /* telex dial plan */
                   case 0x08: /* domestic dial plan */
                   case 0x09: /* private dial plan */
                   case 0x05: /* reserved */
                   default:   /* reserved */
                      ast_debug(2, "cid info:#2=%X\n", (unsigned)cid->rawdata[x]);
                      break ;
                   }
                   x++;
                   break ;
                case 0x04: /* no callerid reason */
                   /* length */
                   x++;
                   /* no callerid reason code */
                   switch (cid->rawdata[x]) {
                   case 'P': /* caller id denied by user */
                   case 'O': /* service not available */
                   case 'C': /* pay phone */
                   case 'S': /* service congested */
                      cid->flags |= CID_UNKNOWN_NUMBER;
                      ast_debug(2, "no cid reason:%c\n", cid->rawdata[x]);
                      break ;
                   }
                   x++;
                   break ;
                case 0x09: /* dialed number */
                   /* length */
                   res = cid->rawdata[x++];
                   /* dialed number */
                   x += res;
                   break ;
                case 0x22: /* dialed number additional information */
                   /* length */
                   x++;
                   /* number type */
                   switch (cid->rawdata[x]) {
                   case 0x00: /* unknown */
                   case 0x01: /* international number */
                   case 0x02: /* domestic number */
                   case 0x03: /* network */
                   case 0x04: /* local call */
                   case 0x06: /* short dial number */
                   case 0x07: /* reserved */
                   default:   /* reserved */
                      if (DEBUG_ATLEAST(2))
                         ast_log(LOG_NOTICE, "did info:#1=%X\n", (unsigned)cid->rawdata[x]);
                      break ;
                   }
                   x++;
                   /* numbering plan octed 4 */
                   x++;
                   /* numbering plan octed 5 */
                   switch (cid->rawdata[x]) {
                   case 0x00: /* unknown */
                   case 0x01: /* recommendation E.164 ISDN */
                   case 0x03: /* recommendation X.121 */
                   case 0x04: /* telex dial plan */
                   case 0x08: /* domestic dial plan */
                   case 0x09: /* private dial plan */
                   case 0x05: /* reserved */
                   default:   /* reserved */
                      ast_debug(2, "did info:#2=%X\n", (unsigned)cid->rawdata[x]);
                      break ;
                   }
                   x++;
                   break ;
                }
             }
             return 1;
             break;
          default:
             ast_log(LOG_ERROR, "invalid value in sawflag %d\n", cid->sawflag);
          }
       }
    }
    if (mylen) {
       memcpy(cid->oldstuff, buf, mylen * 2);
       cid->oldlen = mylen * 2;
    } else
       cid->oldlen = 0;
    return 0;
 }
callerid_free()
void callerid_free (struct callerid_state * cid)
This function frees callerid_state cid.
Parameters
cid This is the callerid_state state machine to free
Definition at line 734 of file callerid.c.
References ast_free.
Referenced by analog_ss_thread(), mwi_thread(), and my_stop_cid_detect().
 {
    ast_free(cid);
 }
callerid_generate()
int callerid_generate (unsigned char * buf, const char * number, const char * name, int flags, int callwaiting, struct ast_format * codec)
Generates a CallerID FSK stream in ulaw format suitable for transmission.
Parameters
buf Buffer to use. If "buf" is supplied, it will use that buffer instead of allocating its own. "buf" must be at least 32000 bytes in size of you want to be sure you don't have an overrun.
number Use NULL for no number or "P" for "private"
name name to be used
flags passed flags
callwaiting callwaiting flag
codec – either AST_FORMAT_ULAW or AST_FORMAT_ALAW
This function creates a stream of callerid (a callerid spill) data in ulaw format.
Returns
It returns the size (in bytes) of the data (if it returns a size of 0, there is probably an error)
Definition at line 898 of file callerid.c.
References callerid_genmsg(), callerid_state::len, PUT_BYTE, PUT_CLID, and PUT_CLID_MARKMS.
Referenced by __ast_callerid_generate().
 {
    int bytes = 0;
    int x, sum;
    int len;
    /* Initial carriers (real/imaginary) */
    float cr = 1.0;
    float ci = 0.0;
    float scont = 0.0;
    char msg[256];
    len = callerid_genmsg(msg, sizeof(msg), number, name, flags);
    if (!callwaiting) {
       /* Wait a half a second */
       for (x = 0; x < 4000; x++)
          PUT_BYTE(0x7f);
       /* Transmit 30 0x55's (looks like a square wave) for channel seizure */
       for (x = 0; x < 30; x++)
          PUT_CLID(0x55);
    }
    /* Send 150ms of callerid marks */
    for (x = 0; x < 150; x++)
       PUT_CLID_MARKMS;
    /* Send 0x80 indicating MDMF format */
    PUT_CLID(0x80);
    /* Put length of whole message */
    PUT_CLID(len);
    sum = 0x80 + strlen(msg);
    /* Put each character of message and update checksum */
    for (x = 0; x < len; x++) {
       PUT_CLID(msg[x]);
       sum += msg[x];
    }
    /* Send 2's compliment of sum */
    PUT_CLID(256 - (sum & 255));
    /* Send 50 more ms of marks */
    for (x = 0; x < 50; x++)
       PUT_CLID_MARKMS;
    return bytes;
 }
callerid_genmsg()
static int callerid_genmsg (char * msg, int size, const char * number, const char * name, int flags) static
Definition at line 739 of file callerid.c.
References ast_localtime(), ast_strlen_zero, ast_tvnow(), CID_PRIVATE_NAME, CID_PRIVATE_NUMBER, CID_UNKNOWN_NAME, CID_UNKNOWN_NUMBER, NULL, ast_tm::tm_hour, ast_tm::tm_mday, ast_tm::tm_min, and ast_tm::tm_mon.
Referenced by ast_callerid_vmwi_generate(), and callerid_generate().
 {
    struct timeval now = ast_tvnow();
    struct ast_tm tm;
    char *ptr;
    int res;
    int i, x;
    /* Get the time */
    ast_localtime(&now, &tm, NULL);
    ptr = msg;
    /* Format time and message header */
    res = snprintf(ptr, size, "\001\010%02d%02d%02d%02d", tm.tm_mon + 1,
             tm.tm_mday, tm.tm_hour, tm.tm_min);
    size -= res;
    ptr += res;
    if (ast_strlen_zero(number) || (flags & CID_UNKNOWN_NUMBER)) {
       /* Indicate number not known */
       res = snprintf(ptr, size, "\004\001O");
       size -= res;
       ptr += res;
    } else if (flags & CID_PRIVATE_NUMBER) {
       /* Indicate number is private */
       res = snprintf(ptr, size, "\004\001P");
       size -= res;
       ptr += res;
    } else {
       /* Send up to 16 digits of number MAX */
       i = strlen(number);
       if (i > 16)
          i = 16;
       res = snprintf(ptr, size, "\002%c", i);
       size -= res;
       ptr += res;
       for (x = 0; x < i; x++)
          ptr[x] = number[x];
       ptr[i] = '\0';
       ptr += i;
       size -= i;
    }
    if (ast_strlen_zero(name) || (flags & CID_UNKNOWN_NAME)) {
       /* Indicate name not known */
       res = snprintf(ptr, size, "\010\001O");
       size -= res;
       ptr += res;
    } else if (flags & CID_PRIVATE_NAME) {
       /* Indicate name is private */
       res = snprintf(ptr, size, "\010\001P");
       size -= res;
       ptr += res;
    } else {
       /* Send up to 16 digits of name MAX */
       i = strlen(name);
       if (i > 16)
          i = 16;
       res = snprintf(ptr, size, "\007%c", i);
       size -= res;
       ptr += res;
       for (x = 0; x < i; x++)
          ptr[x] = name[x];
       ptr[i] = '\0';
       ptr += i;
       size -= i;
    }
    return (ptr - msg);
 }
callerid_get()
void callerid_get (struct callerid_state * cid, char ** number, char ** name, int * flags)
Extract info out of callerID state machine. Flags are listed above.
Parameters
cid Callerid state machine to act upon
number Pass the address of a pointer-to-char (will contain the phone number)
name Pass the address of a pointer-to-char (will contain the name)
flags Pass the address of an int variable(will contain the various callerid flags)
This function extracts a callerid string out of a callerid_state state machine. If no number is found, *number will be set to NULL. Likewise for the name. Flags can contain any of the following:
Returns
Returns nothing.
Definition at line 188 of file callerid.c.
References CID_PRIVATE_NAME, CID_PRIVATE_NUMBER, CID_UNKNOWN_NAME, CID_UNKNOWN_NUMBER, callerid_state::flags, callerid_state::name, NULL, and callerid_state::number.
Referenced by analog_ss_thread(), mwi_thread(), and my_get_callerid().
 {
    *flags = cid->flags;
    if (cid->flags & (CID_UNKNOWN_NAME | CID_PRIVATE_NAME))
       *name = NULL;
    else
       *name = cid->name;
    if (cid->flags & (CID_UNKNOWN_NUMBER | CID_PRIVATE_NUMBER))
       *number = NULL;
    else
       *number = cid->number;
 }
callerid_get_dtmf()
void callerid_get_dtmf (char * cidstring, char * number, int * flags)
Get and parse DTMF-based callerid.
Parameters
cidstring The actual transmitted string.
number The cid number is returned here.
flags The cid flags are returned here.
Definition at line 201 of file callerid.c.
References ast_debug, ast_log, CID_PRIVATE_NUMBER, CID_UNKNOWN_NUMBER, and LOG_WARNING.
Referenced by __analog_ss_thread(), and analog_ss_thread().
 {
    int i;
    int code;
    /* "Clear" the number-buffer. */
    number[0] = 0;
    if (strlen(cidstring) < 2) {
       ast_debug(1, "No cid detected\n");
       *flags = CID_UNKNOWN_NUMBER;
       return;
    }
    /* Detect protocol and special types */
    if (cidstring[0] == 'B') {
       /* Handle special codes */
       code = atoi(&cidstring[1]);
       if (code == 0)
          *flags = CID_UNKNOWN_NUMBER;
       else if (code == 10)
          *flags = CID_PRIVATE_NUMBER;
       else
          ast_debug(1, "Unknown DTMF code %d\n", code);
    } else if (cidstring[0] == 'D' && cidstring[2] == '#') {
       /* .DK special code */
       if (cidstring[1] == '1')
          *flags = CID_PRIVATE_NUMBER;
       if (cidstring[1] == '2' || cidstring[1] == '3')
          *flags = CID_UNKNOWN_NUMBER;
    } else if (cidstring[0] == 'D' || cidstring[0] == 'A') {
       /* "Standard" callerid */
       for (i = 1; i < strlen(cidstring); i++) {
          if (cidstring[i] == 'C' || cidstring[i] == '#')
             break;
          if (isdigit(cidstring[i]))
             number[i-1] = cidstring[i];
          else
             ast_debug(1, "Unknown CID digit '%c'\n",
                cidstring[i]);
       }
       number[i-1] = 0;
    } else if (isdigit(cidstring[0])) {
       /* It begins with a digit, so we parse it as a number and hope
        * for the best */
       ast_log(LOG_WARNING, "Couldn't detect start-character. CID "
          "parsing might be unreliable\n");
       for (i = 0; i < strlen(cidstring); i++) {
          if (isdigit(cidstring[i]))
             number[i] = cidstring[i];
          else
             break;
       }
       number[i] = 0;
    } else {
       ast_debug(1, "Unknown CID protocol, start digit '%c'\n", cidstring[0]);
       *flags = CID_UNKNOWN_NUMBER;
    }
 }
callerid_init()
void callerid_init (void)
Initialize stuff for inverse FFT.
CallerID Initialization.
Definition at line 115 of file callerid.c.
References CALLERID_MARK, CALLERID_SPACE, CAS_FREQ1, CAS_FREQ2, casdi1, casdi2, casdr1, casdr2, cid_di, cid_dr, cos, M_PI, SAS_FREQ, sasdi, and sasdr.
Referenced by asterisk_daemon().
 {
    cid_dr[0] = cos(CALLERID_SPACE * 2.0 * M_PI / 8000.0);
    cid_di[0] = sin(CALLERID_SPACE * 2.0 * M_PI / 8000.0);
    cid_dr[1] = cos(CALLERID_MARK * 2.0 * M_PI / 8000.0);
    cid_di[1] = sin(CALLERID_MARK * 2.0 * M_PI / 8000.0);
    sasdr = cos(SAS_FREQ * 2.0 * M_PI / 8000.0);
    sasdi = sin(SAS_FREQ * 2.0 * M_PI / 8000.0);
    casdr1 = cos(CAS_FREQ1 * 2.0 * M_PI / 8000.0);
    casdi1 = sin(CAS_FREQ1 * 2.0 * M_PI / 8000.0);
    casdr2 = cos(CAS_FREQ2 * 2.0 * M_PI / 8000.0);
    casdi2 = sin(CAS_FREQ2 * 2.0 * M_PI / 8000.0);
 }
callerid_new()
struct callerid_state* callerid_new (int cid_signalling)
Create a callerID state machine.
Parameters
cid_signalling Type of signalling in use
This function returns a malloc'd instance of the callerid_state data structure.
Returns
Returns a pointer to a malloc'd callerid_state structure, or NULL on error.
Definition at line 129 of file callerid.c.
References ast_calloc, fsk_data::bw, CID_UNKNOWN_NAME, CID_UNKNOWN_NUMBER, fsk_data::f_mark_idx, fsk_data::f_space_idx, callerid_state::flags, callerid_state::fskd, fskmodem_init(), fsk_data::icont, fsk_data::instop, fsk_data::ispb, fsk_data::nbit, fsk_data::nstop, fsk_data::pllids, fsk_data::pllispb, fsk_data::pllispb2, and fsk_data::spb.
Referenced by analog_ss_thread(), mwi_thread(), and my_start_cid_detect().
 {
    struct callerid_state *cid;
    if ((cid = ast_calloc(1, sizeof(*cid)))) {
 #ifdef INTEGER_CALLERID
       cid->fskd.ispb = 7;           /* 1200 baud */
       /* Set up for 1200 / 8000 freq *32 to allow ints */
       cid->fskd.pllispb  = (int)(8000 * 32  / 1200);
       cid->fskd.pllids   = cid->fskd.pllispb/32;
       cid->fskd.pllispb2 = cid->fskd.pllispb/2;
       cid->fskd.icont = 0;           /* PLL REset */
       /* cid->fskd.hdlc = 0; */        /* Async */
       cid->fskd.nbit = 8;              /* 8 bits */
       cid->fskd.instop = 1;         /* 1 stop bit */
       /* cid->fskd.paridad = 0; */     /* No parity */
       cid->fskd.bw = 1;                /* Filter 800 Hz */
       if (cid_signalling == 2) {       /* v23 signalling */
          cid->fskd.f_mark_idx  = 4; /* 1300 Hz */
          cid->fskd.f_space_idx = 5; /* 2100 Hz */
       } else {                         /* Bell 202 signalling as default */
          cid->fskd.f_mark_idx  = 2; /* 1200 Hz */
          cid->fskd.f_space_idx = 3; /* 2200 Hz */
       }
       /* cid->fskd.pcola = 0; */       /* No clue */
       /* cid->fskd.cont = 0.0; */      /* Digital PLL reset */
       /* cid->fskd.x0 = 0.0; */
       /* cid->fskd.state = 0; */
       cid->flags = CID_UNKNOWN_NAME | CID_UNKNOWN_NUMBER;
       /* cid->pos = 0; */
       fskmodem_init(&cid->fskd);
 #else
       cid->fskd.spb = 7.0;             /* 1200 baud */
       /* cid->fskd.hdlc = 0; */        /* Async */
       cid->fskd.nbit = 8;              /* 8 bits */
       cid->fskd.nstop = 1.0;           /* 1 stop bit */
       /* cid->fskd.paridad = 0; */     /* No parity */
       cid->fskd.bw = 1;                /* Filter 800 Hz */
       if (cid_signalling == 2) {       /* v23 signalling */
          cid->fskd.f_mark_idx =  4; /* 1300 Hz */
          cid->fskd.f_space_idx = 5; /* 2100 Hz */
       } else {                         /* Bell 202 signalling as default */
          cid->fskd.f_mark_idx =  2; /* 1200 Hz */
          cid->fskd.f_space_idx = 3; /* 2200 Hz */
       }
       /* cid->fskd.pcola = 0; */       /* No clue */
       /* cid->fskd.cont = 0.0; */      /* Digital PLL reset */
       /* cid->fskd.x0 = 0.0; */
       /* cid->fskd.state = 0; */
       cid->flags = CID_UNKNOWN_NAME | CID_UNKNOWN_NUMBER;
       /* cid->pos = 0; */
 #endif
    }
    return cid;
 }
gen_tone()
static void gen_tone (unsigned char * buf, int len, struct ast_format * codec, float ddr1, float ddi1, float * cr1, float * ci1) inline static
Definition at line 99 of file callerid.c.
References AST_LIN2X, and callerid_state::len.
Referenced by ast_gen_cas().
 {
    int x;
    float t;
    for (x = 0; x < len; x++) {
       t = *cr1 * ddr1 - *ci1 * ddi1;
       *ci1 = *cr1 * ddi1 + *ci1 * ddr1;
       *cr1 = t;
       t = 2.0 - (*cr1 * *cr1 + *ci1 * *ci1);
       *cr1 *= t;
       *ci1 *= t;
       buf[x] = AST_LIN2X(*cr1 * 8192.0);
    }
 }
gen_tones()
static void gen_tones (unsigned char * buf, int len, struct ast_format * codec, float ddr1, float ddi1, float ddr2, float ddi2, float * cr1, float * ci1, float * cr2, float * ci2) inline static
Definition at line 77 of file callerid.c.
References AST_LIN2X, and callerid_state::len.
Referenced by ast_gen_cas().
 {
    int x;
    float t;
    for (x = 0; x < len; x++) {
       t = *cr1 * ddr1 - *ci1 * ddi1;
       *ci1 = *cr1 * ddi1 + *ci1 * ddr1;
       *cr1 = t;
       t = 2.0 - (*cr1 * *cr1 + *ci1 * *ci1);
       *cr1 *= t;
       *ci1 *= t;
       t = *cr2 * ddr2 - *ci2 * ddi2;
       *ci2 = *cr2 * ddi2 + *ci2 * ddr2;
       *cr2 = t;
       t = 2.0 - (*cr2 * *cr2 + *ci2 * *ci2);
       *cr2 *= t;
       *ci2 *= t;
       buf[x] = AST_LIN2X((*cr1 + *cr2) * 2048.0);
    }
 }
Variable Documentation
casdi1
float casdi1
Definition at line 67 of file callerid.c.
Referenced by ast_gen_cas(), and callerid_init().
casdi2
float casdi2
Definition at line 67 of file callerid.c.
Referenced by ast_gen_cas(), and callerid_init().
casdr1
float casdr1
Definition at line 67 of file callerid.c.
Referenced by ast_gen_cas(), and callerid_init().
casdr2
float casdr2
Definition at line 67 of file callerid.c.
Referenced by ast_gen_cas(), and callerid_init().
cid_di
float cid_di[4]
Definition at line 64 of file callerid.c.
Referenced by callerid_getcarrier(), and callerid_init().
cid_dr
float cid_dr[4]
Definition at line 64 of file callerid.c.
Referenced by callerid_getcarrier(), and callerid_init().
clidsb
float clidsb = 8000.0 / 1200.0
Definition at line 65 of file callerid.c.
connected_line_source_types
const struct ast_value_translation connected_line_source_types[] static
Translation table for connected line update source settings.
Definition at line 1268 of file callerid.c.
party_name_charset_tbl
const struct ast_value_translation party_name_charset_tbl[] static
Translation table for ast_party_name char-set settings.
Definition at line 1319 of file callerid.c.
pres_types
const struct ast_value_translation pres_types[] static
Translation table for Caller ID Presentation settings.
Definition at line 1118 of file callerid.c.
redirecting_reason_types
const struct ast_value_translation redirecting_reason_types[] static
Translation table for redirecting reason settings.
Definition at line 1196 of file callerid.c.
sasdi
float sasdi
Definition at line 66 of file callerid.c.
Referenced by ast_gen_cas(), and callerid_init().
sasdr
float sasdr
Definition at line 66 of file callerid.c.
Referenced by ast_gen_cas(), and callerid_init().