Asterisk - The Open Source Telephony Project: app_waitforring.c File Reference
app_waitforring.c File Reference
Dial plan applications
Wait for Ring Application.
#include "asterisk.h"
#include "asterisk/file.h"
#include "asterisk/channel.h"
#include "asterisk/pbx.h"
#include "asterisk/module.h"
#include "asterisk/lock.h"
Functions
AST_MODULE_INFO_STANDARD_EXTENDED (ASTERISK_GPL_KEY, "Waits until first ring after time")
static int load_module (void)
static int unload_module (void)
static int waitforring_exec (struct ast_channel *chan, const char *data)
Variables
static char * app = "WaitForRing"
Detailed Description
Wait for Ring Application.
Author
Mark Spencer marks.nosp@m.ter@.nosp@m.digiu.nosp@m.m.co.nosp@m.m
Definition in file app_waitforring.c.
Function Documentation
AST_MODULE_INFO_STANDARD_EXTENDED()
AST_MODULE_INFO_STANDARD_EXTENDED (ASTERISK_GPL_KEY , "Waits until first ring after time")
Referenced by load_module().
load_module()
static int load_module (void) static
Definition at line 136 of file app_waitforring.c.
References app, AST_MODULE_INFO_STANDARD_EXTENDED(), ast_register_application_xml, ASTERISK_GPL_KEY, and waitforring_exec().
 {
    return ast_register_application_xml(app, waitforring_exec);
 }
unload_module()
static int unload_module (void) static
Definition at line 131 of file app_waitforring.c.
References app, and ast_unregister_application().
 {
    return ast_unregister_application(app);
 }
waitforring_exec()
static int waitforring_exec (struct ast_channel * chan, const char * data) static
Definition at line 58 of file app_waitforring.c.
References ast_channel_start_silence_generator(), ast_channel_stop_silence_generator(), AST_CONTROL_RING, AST_FRAME_CONTROL, ast_frfree, ast_log, ast_opt_transmit_silence, ast_read(), ast_remaining_ms(), ast_tvnow(), ast_verb, ast_waitfor(), ast_frame::frametype, ast_frame_subclass::integer, LOG_WARNING, NULL, and ast_frame::subclass.
Referenced by load_module().
 {
    struct ast_frame *f;
    struct ast_silence_generator *silgen = NULL;
    int res = 0;
    double s;
    int timeout_ms;
    int ms;
    struct timeval start = ast_tvnow();
    if (!data || (sscanf(data, "%30lg", &s) != 1)) {
       ast_log(LOG_WARNING, "WaitForRing requires an argument (minimum seconds)\n");
       return 0;
    }
    if (s < 0.0) {
       ast_log(LOG_WARNING, "Invalid timeout provided for WaitForRing (%lg)\n", s);
       return 0;
    }
    if (ast_opt_transmit_silence) {
       silgen = ast_channel_start_silence_generator(chan);
    }
    timeout_ms = s * 1000.0;
    while ((ms = ast_remaining_ms(start, timeout_ms))) {
       ms = ast_waitfor(chan, ms);
       if (ms < 0) {
          res = -1;
          break;
       }
       if (ms > 0) {
          f = ast_read(chan);
          if (!f) {
             res = -1;
             break;
          }
          if ((f->frametype == AST_FRAME_CONTROL) && (f->subclass.integer == AST_CONTROL_RING)) {
             ast_verb(3, "Got a ring but still waiting for timeout\n");
          }
          ast_frfree(f);
       }
    }
    /* Now we're really ready for the ring */
    if (!res) {
       for (;;) {
          int wait_res = ast_waitfor(chan, -1);
          if (wait_res < 0) {
             res = -1;
             break;
          } else {
             f = ast_read(chan);
             if (!f) {
                res = -1;
                break;
             }
             if ((f->frametype == AST_FRAME_CONTROL) && (f->subclass.integer == AST_CONTROL_RING)) {
                ast_verb(3, "Got a ring after the timeout\n");
                ast_frfree(f);
                break;
             }
             ast_frfree(f);
          }
       }
    }
    if (silgen) {
       ast_channel_stop_silence_generator(chan, silgen);
    }
    return res;
 }
Variable Documentation
app
char* app = "WaitForRing" static
Definition at line 56 of file app_waitforring.c.
Referenced by load_module(), and unload_module().